### ISSUE TITLE
Race in informer.controller.Requeue

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#27790]
[Controller.Requeue()](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/framework/controller.go#L112-L119) was designed to expedite reprocessing, or delay processing. However, it has a race that:
- the item has been deleted in store.
- when Requeue(), the DeltaFIFO didn't contain the event, so it will just go queue a Sync
- controller will process Sync event and add the item.

For the solution, I would suggest removing Requeue() and make informer readonly. For delay processing, users should do retry outside informer and we can provide a common routine to do that. Of course, I would like to listen and understand more use cases of Requeue().

**Comment by AdoHe** [comment]
@hongchaodeng how about you new proposal? shall we implement it and get it into? I would really like to help with this.

**Comment by hongchaodeng** [comment]
Do you mean the informer redesign? It's an orthogonal issue.

What I'm thinking is we should make informer readonly and provide routine for client to retry on failed condition. If you want to do it, go ahead and submit a PR.

**Comment by ncdc** [comment]
The `Requeue` function no longer exists. I don't believe there is anything similar to it after grepping through the code. Closing, but please reopen if needed.
