### ISSUE TITLE
Decide how/if to distribute SSL CA certs with components

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#27804]
`federation-controller-manager` runs within kubernetes inside a container.  It [needs access to CA certificates to work](https://github.com/kubernetes/kubernetes/issues/27684).  At the moment, we are grabbing those certs [from the node filesystem](https://github.com/kubernetes/kubernetes/pull/27802).

Do we wish to package this some other way?  If so, do we have a standard way of doing this?  Depending on what we choose, we may be on the hook for keeping this package up to date in the case that there's a security update.

@mikedanese @erictune @matchstick @kubernetes/sig-cluster-federation

**Comment by mml** [comment]
> within kubernetes inside a container

More clearly, it runs as a non-mirror pod on non-master nodes.

**Comment by quinton-hoole** [comment]
@mml I assume that secrets are the way to distribute such certs?

**Comment by quinton-hoole** [comment]
cc: @madhusudancs for the GA requirements list.

**Comment by erictune** [comment]
Secrets are the way to distribute a private key.
Config map or kubeconfig-in-a-secret are the way to distribute a
self-signed public key for reaching the main apiserver.
The container base image is the de-facto way to distribute certs for
globally recognized CAs.

**Comment by madhusudancs** [comment]
We now ship federation control plane components only as part of the hyperkube binary. And we recommend using only the hyperkube image which includes the trusted certs. And we use hyperkube image in the federation manifests too. So this issue is fixed.

Ref: PR #29929

**Comment by madhusudancs** [comment]
Forgot to mention. @erictune thank you! Your comment above helped making progress on this issue.
