### ISSUE TITLE
Set --federations kube-dns flag when FEDERATION=true

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#27819]
(Blocking #27739)

`kube-dns` needs to know what federation it belongs to, so we need to set `--federations=${FEDERATION_NAME}=${DNS_ZONE_NAME}` in `kube-up`.

Note that cloud DNS names domain names *with* a trailing dot, but `kube-dns` needs (or at least wants: #27815) the name *without* a trailing dot.  If that is in fact a restriction, there is the convenient shell hack `${DNS_ZONE_NAME%.}`, but in the end we should make the go code more flexible about the dots.

**Comment by mml** [comment]
@madhusudancs @kubernetes/sig-cluster-federation

**Comment by mml** [comment]
And then we gotta resolve #27820

**Comment by quinton-hoole** [comment]
@nikhiljindal Do we have a PR for this yet?  I don't see one referenced here, but I could have sworn that I saw one somewhere.

**Comment by quinton-hoole** [comment]
This one slipped through the cracks, sorry.  PR incoming from @madhusudancs shortly.

**Comment by madhusudancs** [comment]
Fixed in #27986.
