### ISSUE TITLE
Re-enable NoRouteCreated on AWS

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#27828]
Because of issues like #27347 and #26983, we had to disable the NoRouteCreated logic on AWS in 1.3, in #27525.  But this is a good feature - it prevents scheduling onto a node until the controllers have set up a node (and we also want to use this pattern generally I suspect).

We should find a way to re-enable the logic on AWS in #27525, perhaps via an opt-in or opt-out flag or configuration.

**Comment by wojtek-t** [comment]
Yeah - I think the easiest way is to add a flag to kubelet that will decide whether create or not the "NoRouteCreated" condition. This is super small change in the code. The non-trivial changes here would be to configure it correctly in startup scripts.

**Comment by dcbw** [comment]
@wojtek-t I had hoped this could be decided by the cloud provider instead of adding more flags to kubelet?  It seems like something dictated by the cloud provider in combination with the network plugin and something that we can auto-detect, with a little effort.

**Comment by wojtek-t** [comment]
Definitely, if cloud provider doesn't implement routes interface, we can easily detect it. The problem is when cloud provider implements it. Is kubelet aware of network provider when it is running? [there is not dedicated interface for it - in kube-up script this is just env variable].

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5

**Comment by dims** [comment]
@justinsb all issues must be labeled either release blocker or non release blocking by end of day 18 November 2016 PST. (or please move it to 1.6) cc @kubernetes/sig-aws

**Comment by dims** [comment]
@justinsb : do we still consider this a blocker? I haven't seen any activity for more than a week. If so, what needs to be done to unblock it?

**Comment by grodrigues3** [comment]
@justinsb ping

**Comment by justinsb** [comment]
I think we're going to use taints to do this instead.  Network controllers that want to not be broken will be expected to untaint themselves, I guess.

**Comment by dims** [comment]
@justinsb Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by rbtcollins** [comment]
We suffered downtime as a result of this interacting with an as yet not root caused failure to clean out routes of old nodes (we were migrating from one instance type to another).

**Comment by rbtcollins** [comment]
/remove-lifecycle stale

As far as I can tell this is still relevant until reinstated / taints added.
