### ISSUE TITLE
kubectl showing password on screen

### ISSUE THREAD

**Issue by harryge00** [kubernetes/kubernetes#27851]
When I want to use basic-auth, kubectl will display the password I entered:

```
# kubectl get pods
Please enter Username: admin
Please enter Password: MyPassword
```

I think it is more sensible to hide the password?

**Comment by reAsOn2010** [comment]
And it seems that kubectl request for username/password twice...

```
$ kubectl get nodes
Please enter Username: abc
Please enter Password: test
Please enter Username: abc
Please enter Password: test
```

**Comment by brendandburns** [comment]
I'll take this.  There is a library here:

https://github.com/howeyc/gopass

That appears to do the trick, but we need some refactoring so that it can read from an arbitrary reader to fit our usecase.

**Comment by brendandburns** [comment]
This was fixed by https://github.com/kubernetes/kubernetes/pull/31586

but I didn't close this issue.  Closing it now.
