### ISSUE TITLE
Events created from external short-living components might be lost when using record.EventRecorder

### ISSUE THREAD

**Issue by mfojtik** [kubernetes/kubernetes#27858]
Let say you building a scratch Docker image that want to record events to kube and you have the kube client and you create the recorder like this:

``` go
eventBroadcaster := record.NewBroadcaster()
eventBroadcaster.StartRecordingToSink(events) // -> events => record.EventSink
recorder := eventBroadcaster.NewRecorder(kapi.EventSource{Component: "foo"})
```

Now you start the Pod using this image, it does something and then it want to record the result as an event:

``` go
func do() {
  // do something
  recorder.Eventf("....")
  return
}
```

When this function return, the Pod will complete. In this case, if you call `recorder.Eventf()` right before the function exits, the event will be lost. If you add `time.Sleep(1 * time.Second)` before `return`, the event will be recorded.

A possible solution is to bypass the `record.NewBroadcaster` and just create the event directly using the client. I think more elegant solution would be to add `Close()` or `Flush()` method to recorder, that will block until all events are sent to server.

**Comment by mfojtik** [comment]
@kargakis @smarterclayton FYI

**Comment by kargakis** [comment]
@krousey @lavalamp @caesarxuchao

**Comment by caesarxuchao** [comment]
Adding Close() and Flush() to recorder sounds good. Feel free to send a PR.

**Comment by lavalamp** [comment]
Yeah Flush() SGTM

**Comment by luisdavim** [comment]
/reopen
/remove-lifecycle rotten

This is still an issue, I'm trying to record some events from a job that is created as a child of my custom resource and most of the times I don't get the events.
