### ISSUE TITLE
Cluster is not validated properly after nodes upgrade

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#27852]
Currently algorithm to upgrade nodes on gce works in the following way:
- create a new MIG template
- schedule rolling update of instances in the MIG
- validate cluster

Since rolling update doesn't start immediately and it takes some time for the node controller to notice changed instance the last step may succeed before the update is actually started. Then a user thinks that the cluster is updated but it's not true and nodes become ready and disappear until the update is finished.

@davidopp for prioritize

cc @wojtek-t

**Comment by wojtek-t** [comment]
This is exactly this TODO:
https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/upgrade.sh#L236

**Comment by wojtek-t** [comment]
I have a WIP PR for it, but still need to finish some details. Will finish it tomorrow.
