### ISSUE TITLE
Deleting upgraded cluster (1.2->1.3) fails to delete minion-template

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#27856]
cc @davidopp @piosz @wojtek-t 

Repro:
- create a v1.2 cluster
- upgrage.sh it to v1.3
- delete it (kube-down)
- look at shiny minion template that's left

**Comment by wojtek-t** [comment]
I think that there are two separate issues:
- upgrade itself should be deleting the old template (it's not deleting anything currently, and this is blocked by #27852
- when deleting a cluster, it is not deleting the template that is used by the mig (at the end)

**Comment by gmarek** [comment]
I meant the second. Fix is in #27859
