### ISSUE TITLE
sorting available commands in "kubectl help"

### ISSUE THREAD

**Issue by andreykurilin** [kubernetes/kubernetes#27854]
Sorting  available commands increases readability of help message. It was introduced as default behaviour in latest release of github.com/spf13/cobra (see https://github.com/spf13/cobra/pull/293).

It would be nice to update github.com/spf13/cobra and github.com/spf13/pflag (latest cobra requires latest pflag)/

**Comment by AdoHe** [comment]
@andreykurilin actually we are going to enable commands group here. #25524 ptal.

**Comment by bgrant0607** [comment]
This is a dupe.
