### ISSUE TITLE
addons-manager v3 does not exist for ARM (and possibly other platforms)

### ISSUE THREAD

**Issue by blackxored** [kubernetes/kubernetes#27868]
Running on v1.3.0-beta.2 addons manager fails to pull image since version 3 doesn't exist on gcr, it doesn't even seem to exist at all in the code (i took a small look I might be wrong).

This file hardcodes it to v3: cluster/images/hyperkube/static-pods/addon-manager.json

And the builder has it at v2: cluster/addons/addon-manager/Makefile

// ping @luxas

**Comment by dsanders1234** [comment]
https://gcr.io/v2/google-containers/kube-addon-manager/tags/list

shows no v3

**Comment by blackxored** [comment]
The problem seems to be that 1.3.0-beta.2 got released pointing to v3 where v3 didn't existed, then someone bumped it to v4 quite recently (as in today/yesterday) and that got pushed, while v3 never was. My two cents.

**Comment by girishkalele** [comment]
@blackxored - Can you pull latest master and check if it still has v3 references for hyperkube.
cc @luxas

```console
$ $ git show ca3ee9e5a19f346c7c1e29178d2ca117c93ce8c2
commit ca3ee9e5a19f346c7c1e29178d2ca117c93ce8c2
Author: Lucas Käldström <lucas.kaldstrom@hotmail.co.uk>
Date:   Wed Jun 22 00:48:46 2016 +0300

    Revert kube-proxy as a DaemonSet in hyperkube for the v1.3 release
--- a/cluster/images/hyperkube/static-pods/addon-manager.json
+++ b/cluster/images/hyperkube/static-pods/addon-manager.json
@@ -11,7 +11,7 @@
     "containers": [
       {
         "name": "kube-addon-manager",
-        "image": "gcr.io/google-containers/kube-addon-manager-ARCH:v3",
+        "image": "gcr.io/google-containers/kube-addon-manager-ARCH:v4",
```

**Comment by blackxored** [comment]
@girishkalele Looking at the diff and re-checking on the files, it appears to me that has been fixed. There's still the issue that IMO everyone that gets `v1.3.0-beta.2` would not have addon-manager due to it pointing to a missing v2 tag. Not sure how the build works, but either a new hotfix release or retroactively pushing v2 to GCR would be needed?

**Comment by luxas** [comment]
This PR, #27253, introduced v3, but @mikedanese didn't push it, he obviously has much to do right now.
@girishkalele Please checkout 5debaf7b88a3b6cecb8ce65c5f01568634c09760 and push v3 for all platforms (I haven't got gcr.io push permission yet, so I can't)

This issue will be fixed after that.

**Comment by girishkalele** [comment]
@luxas 

Latest master has addon-manager at v5 now but no v5 containers have been pushed.

I have
a) Pushed v5 for all architectures
b) Checked out 5debaf7 and pushed v3 for all architectures

**Comment by luxas** [comment]
Thanks a lot! Closing this then...
