### ISSUE TITLE
new bash completion seems borked on OS X

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/kubernetes#27876]
I just tried to upgrade from the previous [bash completion for kubectl](https://blog.fabric8.io/enable-bash-completion-for-kubernetes-with-kubectl-506bc89fe79e#.hwiy7aebj) to the new `kubectl completion bash` command using 1.3.0-alpha-2.

Adding this to my *~/.bashrc* did't seem to do much:
```
source <(kubectl completion bash)
```
If I did this it helped...
```
kubectl completion bash > ~/.bash_completions/kube

# then in ~/.bashrc
source ~/.bash_completions/kube
```

Though then when using it...
```
kubectl get [TAB]
 -bash: __ltrim_colon_completions: command not found
```

looking in the output generated by `kubectl completion bash` it seems there's a function `__ltrim_colon_completions` that never gets defined

**Comment by jstrachan** [comment]
FWIW if you edit the output and remove that line it seems to mostly work so far

**Comment by dims** [comment]
@jstrachan long time no see!!! how have you been :)

i had to install brew-completion to get past this problem:
http://superuser.com/questions/819221/how-to-install-the-debian-bash-completion-using-homebrew

**Comment by jstrachan** [comment]
@dims hey! agreeD!

Ah - thanks - so maybe this is just me being a bit useless with bash completion! :)

**Comment by girishkalele** [comment]
@jstrachan 

Hope @dims suggestion works - I have tagged the UX team on this.

**Comment by jstrachan** [comment]
just to confirm; after installing bash-completion via:
```
brew install bash-completion
```
then things all worked fine! :) 

I just had to ensure that `/usr/local/etc/bash_completion.d` was writable by brew

**Comment by pnovotnak** [comment]
FYI; seems BASH needs to be a new-ish version.


 $ echo $BASH_VERSION
3.2.57(1)-release                <<< does not work!

$ echo $BASH_VERSION
4.4.5(1)-release                  <<< works!

**Comment by razvanphp** [comment]
This is the case with the default bash in OS X Sierra, I would assume updating bash would cause system instability, can this be fixed for the 3.x version too?

**Comment by cphrmky** [comment]
If you'd rather stick with bash on OS X it's pretty easy to update.

http://apple.stackexchange.com/questions/193411/update-bash-to-version-4-0-on-osx

**Comment by razvanphp** [comment]
I think that's not the point, the idea is to have the bug fixed, it says nowhere that bash 3 is not supported.

CC: @girishkalele can we please reopen this?
