### ISSUE TITLE
aws volume is not mounted successfully

### ISSUE THREAD

**Issue by sp-joseluis-ledesma** [kubernetes/kubernetes#27875]
Hello, 

   I was trying to reproduce issue #27774 in a new kubernetes cluster with version 1.3.0-beta.2 but the volume now does not get attached. 

controller-manager logs says:

` I0622 14:17:02.015083       6 aws.go:1080] Assigned mount device ba -> volume vol-6d4855c8
I0622 14:17:02.350409       6 aws.go:1325] AttachVolume request returned {
  AttachTime: 2016-06-22 14:17:02.308 +0000 UTC,
  Device: "/dev/xvdba",
  InstanceId: "i-a33e1139",
  State: "attaching",
  VolumeId: "vol-6d4855c8"
}
I0622 14:17:02.537238       6 aws.go:1203] Waiting for volume state: actual=attaching, desired=attached
I0622 14:17:03.627123       6 aws.go:1203] Waiting for volume state: actual=attaching, desired=attached
I0622 14:17:04.984571       6 aws.go:1098] Releasing mount device mapping: ba -> volume vol-6d4855c8
I0622 14:17:04.984673       6 operation_executor.go:447] AttachVolume.Attach succeeded for volume "kubernetes.io/aws-
ebs/vol-6d4855c8" (spec.Name: "image-store") from node "ip-172-20-0-182.ec2.internal".`

but the pod is not starting. looking in the minion kubelet logs:

`Jun 22 14:25:13 ip-172-20-0-182 kubelet[18615]: I0622 14:25:13.277401   18615 reconciler.go:253] MountVolume operatio
n started for volume "kubernetes.io/aws-ebs/vol-6d4855c8" (spec.Name: "image-store") to pod "fca6395e-3883-11e6-88c7-
0e74334bc36f" (UID: "fca6395e-3883-11e6-88c7-0e74334bc36f").
Jun 22 14:25:13 ip-172-20-0-182 kubelet[18615]: I0622 14:25:13.277468   18615 operation_executor.go:582] Entering Mou
ntVolume.WaitForAttach for volume "kubernetes.io/aws-ebs/vol-6d4855c8" (spec.Name: "image-store") pod "fca6395e-3883-
11e6-88c7-0e74334bc36f" (UID: "fca6395e-3883-11e6-88c7-0e74334bc36f").
Jun 22 14:25:13 ip-172-20-0-182 kubelet[18615]: E0622 14:25:13.277531   18615 goroutinemap.go:155] Operation for "kub
ernetes.io/aws-ebs/vol-6d4855c8" failed. No retries permitted until 2016-06-22 14:27:13.277525437 +0000 UTC (duration
BeforeRetry 2m0s). error: MountVolume.WaitForAttach failed for volume "kubernetes.io/aws-ebs/vol-6d4855c8" (spec.Name
: "image-store") pod "fca6395e-3883-11e6-88c7-0e74334bc36f" (UID: "fca6395e-3883-11e6-88c7-0e74334bc36f") with: WaitF
orAttach failed for AWS Volume "vol-6d4855c8": devicePath is empty.
Jun 22 14:25:39 ip-172-20-0-182 kubelet[18615]: I0622 14:25:39.534918   18615 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/secret/default-token-yh1zw" (spec.Name: "default-token-yh1zw") to pod "51b8b627-3883-11e6-88c7-0e74334bc36f" (UID: "51b8b627-3883-11e6-88c7-0e74334bc36f"). Volume is already mounted to pod, but remount was requested.
Jun 22 14:25:39 ip-172-20-0-182 kubelet[18615]: I0622 14:25:39.539392   18615 operation_executor.go:673] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/default-token-yh1zw" (spec.Name: "default-token-yh1zw") pod "51b8b627-3883-11e6-88c7-0e74334bc36f" (UID: "51b8b627-3883-11e6-88c7-0e74334bc36f").
Jun 22 14:25:44 ip-172-20-0-182 kubelet[18615]: E0622 14:25:44.438275   18615 kubelet.go:1924] Unable to mount volumes for pod "kube-registry-v0-ttf5i_kube-system(fca6395e-3883-11e6-88c7-0e74334bc36f)": timeout expired waiting for volumes to attach/mount for pod "kube-registry-v0-ttf5i"/"kube-system". list of unattached/unmounted volumes=[image-store]; skipping pod
Jun 22 14:25:44 ip-172-20-0-182 kubelet[18615]: E0622 14:25:44.438319   18615 pod_workers.go:183] Error syncing pod fca6395e-3883-11e6-88c7-0e74334bc36f, skipping: timeout expired waiting for volumes to attach/mount for pod "kube-registry-v0-ttf5i"/"kube-system". list of unattached/unmounted volumes=[image-store]
`

I tried creating a new brand volume, but still getting the same error.

I've checked and the volume is successfully attached to the instance, but it seems it does not get correctly mounted.

**Comment by justinsb** [comment]
Thanks - I also just found this one #27872.  Going to close this one as a dup if that's OK!
