### ISSUE TITLE
AWS deployment with master private ip

### ISSUE THREAD

**Issue by trodriguez-photobox** [kubernetes/kubernetes#27870]
Hello,

I need to be able to deploy a Kubernetes cluster into our existing AWS infraestructure and for evidents reasons we don't want the master to have a public IP. I've already modified the AWS deployment script to allow choosing whether or not the master should get a public ip. Should I submit a PR to integrate those modifications?

**Comment by girishkalele** [comment]
@kubernetes/sig-aws

**Comment by justinsb** [comment]
Thanks for the report.  This would be great, but as kube-up is in maintenance mode we probably want to avoid making bigger changes like this.

kops does now (as of today!) support fully-private clusters (no public IPs) in the master branch, so I suggest you have a look at what we're doing there and see if it is a better match.
