### ISSUE TITLE
AWS: problem mounting dynamic PVs

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#27872]
Error while mounting (dynamic) PVs on AWS, preventing the pods from starting:

```Operation for "kubernetes.io/aws-ebs/aws://us-west-2a/vol-ba9c7533" failed. No retries permitted until 2016-06-22 14:08:43.713839047 +0000 UTC (durationBeforeRetry 2m0s). error: MountVolume.WaitForAttach failed for volume "kubernetes.io/aws-ebs/aws://us-west-2a/vol-ba9c7533" (spec.Name: "pvc-28812c0d-3882-11e6-ba62-02904a5aff93") pod "3e278eda-3882-11e6-ba62-02904a5aff93" (UID: "3e278eda-3882-11e6-ba62-02904a5aff93") with: WaitForAttach failed for AWS Volume "aws://us-west-2a/vol-ba9c7533": devicePath is empty.```

```
Server Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-beta.2-dirty", GitCommit:"caf9a4d87700ba034a7b39cced19bd5628ca6aa3", GitTreeState:"dirty", BuildDate:"2016-06-22T13:35:19Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

Looking into it now

**Comment by justinsb** [comment]
@saad-ali AFAICT DevicePath is never set in the new volumes code - I could use some pointers here!

**Comment by justinsb** [comment]
More logs in https://github.com/kubernetes/kubernetes/issues/27875 also

**Comment by elsonrodriguez** [comment]
Having this exact issue on v1.3.0-beta.2 on AWS provisioned via kube-up.

**Comment by saad-ali** [comment]
Digging in to this with @justinsb
