### ISSUE TITLE
Service.Type Loadbalancer resource leak

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#27883]
@lavalamp observed a loadbalancer resource leak of addresses, firewall and forwarding rules large enough to cause a SQ block. A couple of follow-up actions:    
1. The test can trap all exceptions and manually invoke `gcloud delete target-pools` etc in AfterEach
2. Can we can setup a quota alert?
3. There's a script that's supposed to delete stranded loadbalancer resources as part of kube-down, maybe it's not deleting all? 
4. Maybe the script that catches https://pantheon.corp.google.com/m/cloudstorage/b/kubernetes-jenkins/o/logs/kubernetes-e2e-gce-ingress/7981/artifacts/gcp-resources-after.txt isn't detecting all leaks?

Setting to P2 for now because we believe it's a slow leak.

**Comment by thockin** [comment]
When we see a leak, the "description" field in GCE's structures should tell us what Namespace and Service were in play.

**Comment by nikhiljindal** [comment]
> There's a script that's supposed to delete stranded loadbalancer resources as part of kube-down, maybe it's not deleting all?

Yes I remember @madhusudancs had pointed that out to me that the script was not deleting all the resources. But if it were, then the resource leak test will never fail :)
I expect each test to be responsible for deleting all their resources, so I think the e2e down script is fine.

Deleting the resources in AfterEach in that particular test seems better to me.

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/pull/32183

**Comment by marun** [comment]
@bprashanth @matchstick Should this continue to be a blocker for 1.6? If not, please move to 1.7.

**Comment by deads2k** [comment]
Last update reference was 6 months ago, closing due to age.  Re-open with an update if you think its still an issue.
