### ISSUE TITLE
Federated service shards can't be created in clusters without the specified namespace.

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#27909]
Federated service shards are created only in the clusters that have the specified namespace. To fix this problem we need to create the namespace on-demand while creating the federated service shards.

cc @kubernetes/sig-cluster-federation @matchstick

**Comment by quinton-hoole** [comment]
As discussed, we explicitly decided not to do it this way.  In Kubernetes, when one creates an entity, if the namespace does not exist, the creation call fails. 

What we need to do for v1.3 is pre-create the test namespace in all of the underlying clusters as part of the e2e test turnup.
