### ISSUE TITLE
ErrImagePull with Private Registry

### ISSUE THREAD

**Issue by willis7** [kubernetes/kubernetes#27928]
```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4+3eed1e3", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"not a git tree"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
```

**Current setup**:

Kubernetes -> [Apache <-> Nexus Docker]

**Steps**:

Create a private registry secret as per the [docs](http://kubernetes.io/docs/user-guide/images/#pre-pulling-images)
`kubectl create -f nginx.yml`

```
apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
    - name: web
      image: nexus.mydomain.co.uk/nginx
      ports:
        - containerPort: 80
          hostPort: 80
  imagePullSecrets:
    - name: nexuskey
```

`kubectl describe pod web`

**Output**:

Some details obfuscated.

> Name:     web
> Namespace:    default
> Node:     ip-172-x-x-x.eu-west-1.compute.internal/172.x.x.x
> Start Time:   Thu, 23 Jun 2016 09:20:39 +0100
> Labels:       <none>
> Status:       Pending
> IP:       10.x.x.x
> Controllers:  <none>
> Containers:
>   web:
>     Container ID:
>     Image:        nexus.mydomain.co.uk/nginx
>     Image ID:
>     Port:     80/TCP
>     QoS Tier:
>       memory: BestEffort
>       cpu:    Burstable
>     Requests:
>       cpu:        100m
>     State:        Waiting
>       Reason:     ErrImagePull
>     Ready:        False
>     Restart Count:    0
>     Environment Variables:
> Conditions:
>   Type        Status
>   Ready   False
> Volumes:
>   default-token-qe8sr:
>     Type: Secret (a volume populated by a Secret)
>     SecretName:   default-token-qe8sr
> Events:
>   FirstSeen   LastSeen    Count   From                            SubobjectPath       Type        Reason      Message
> ---
> 
>   14s     14s     1   {default-scheduler }                                Normal      Scheduled   Successfully assigned web to ip-172-x-x-x.eu-west-1.compute.internal
>   14s     14s     1   {kubelet ip-172-x-x-x.eu-west-1.compute.internal}   spec.containers{web}    Normal      Pulling     pulling image "nexus.mydomain.co.uk/nginx"
>   12s     12s     1   {kubelet ip-172-x-x-x.eu-west-1.compute.internal}   spec.containers{web}    Warning     Failed      Failed to pull image "nexus.mydomain.co.uk/nginx": Could not reach any registry endpoint
>   12s     12s     1   {kubelet ip-172-x-x-x.eu-west-1.compute.internal}               Warning     FailedSync  Error syncing pod, skipping: failed to "StartContainer" for "web" with ErrImagePull: "Could not reach any registry endpoint"
> 
>   12s 12s 1   {kubelet ip-172-x-x-x.eu-west-1.compute.internal}   spec.containers{web}    Normal  BackOff     Back-off pulling image "nexus.mydomain.co.uk/nginx"
>   12s 12s 1   {kubelet ip-172-x-x-x.eu-west-1.compute.internal}               Warning FailedSync  Error syncing pod, skipping: failed to "StartContainer" for "web" with ImagePullBackOff: "Back-off pulling image \"nexus.mydomain.co.uk/nginx\""

**Facts**:

Kubernetes makes a GET request to Nexus for the manifest, we see a status 200 in Apache access log (and Nexus):

> "GET /v2/nginx/manifests/latest HTTP/1.1" 200 1956

However, at this point I would expect Kubernetes to start requesting the blobs, but what's actually happening is K8s then makes the following request.

> /v1/repositories/nginx/images HTTP/1.1" 200 61548

Note /v1/ , which results in a 401

> "GET /v1/repositories/library/nginx/tags/latest HTTP/1.1" 401

Contrast this with the same request from my local machine:

> myIP - - [23/Jun/2016:09:06:34 +0000] "GET /v2/nginx/manifests/latest HTTP/1.1" 200 1956
> myIP - - [23/Jun/2016:09:06:36 +0000] "GET /v2/nginx/blobs/sha256:0d409d33b27e47423b049f7f863faa08655a8c901749c2b25b93ca67d01a470d HTTP/1.1" 200 3915
> myIP - - [23/Jun/2016:09:06:36 +0000] "GET /v2/nginx/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 HTTP/1.1" 200 32
> myIP - - [23/Jun/2016:09:06:36 +0000] "GET /v2/nginx/blobs/sha256:bcd41daec8cc835577e660ddef75e655f6ff3742bad92c9c498d8eba097b512a HTTP/1.1" 200 194

Kubernetes was provisioned using `cluster/kube-up.sh` so I cant actually get into the box to try and perform a docker pull.

Any help would be gratefully received.

**Comment by spzala** [comment]
@willis7 hi, a gentle touch base as it's over a year of this issue last discussed. Can you please check if's still an issue or can we please close it if it's not an issue or you found any work around? I tried to recreate with your yml file but  getting dns error server misbehaving. Thanks!

**Comment by willis7** [comment]
I'm not actively using Kubernetes anymore, so I am happy for this to be closed.

**Comment by spzala** [comment]
@willis7 thanks for closing the issue!!
