### ISSUE TITLE
When rolling update fails, new RC remains making another rolling update impossible and breaking our continous delivery

### ISSUE THREAD

**Issue by luispabon** [kubernetes/kubernetes#27929]
If a rolling update fails (for instance, by rolling update to an image that doesn't exist), the new, as of yet unrenamed, RC remains in place. 

If you try another rolling update, it will fail because

```
[master] Running shell script
+ /var/lib/jenkins/kubernetes/kubectl-1.2 --kubeconfig=xxx rolling-update xxx --image=xxx/xxx:master-42-e4c7a5b
error: Found existing in-progress update to image (xxx/xxx).
Either continue in-progress update with --image=xxx/xxx or rollback with --rollback
See 'kubectl rolling-update -h' for help and examples.
```

Two things wrong:
  a) the message `Either continue in-progress update with --image=xxx/xxx` must be wrong, as that's exactly what we're doing
  b) This breaks our continuous delivery pipeline as the only way to recover is for someone to notice, then manually delete the new RC.

Kubernetes 1.2.4.

**Comment by bgrant0607** [comment]
Please check out Deployment. It's going to work better in a CD flow.

http://kubernetes.io/docs/user-guide/deployments/

cc @kubernetes/kubectl

**Comment by kargakis** [comment]
This shouldn't be a problem with Deployments - closing

**Comment by luispabon** [comment]
Apologies for not reporting back. Indeed this stopped happening once we moved to Deployments from RCs.
