### ISSUE TITLE
What are all resource types used in ABAC authorization config file?

### ISSUE THREAD

**Issue by reAsOn2010** [kubernetes/kubernetes#27922]
In ABAC authorization mode, we can set restrictions on specific resource types.
For example, we created a shared cluster using k8s, created a namespace called 'alice-space' for user 'alice', so an reasonable config is like:
```
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user": "alice", "namespace": "alice-space", "resource": "namespace", "readonly": true}}
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user": "alice", "namespace": "alice-space", "resource": "resourcequotas", "readonly": true}}
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user": "alice", "namespace": "alice-space", "resource": "pods"}}
...
```
We don't want 'alice' change her namespace metadata and quota, but we should let her touch all resources under this namespace, so my question is what are all resource types can be configured here? If we missed one, that kind of resource the user can never use...

**Comment by harryge00** [comment]
And I think it is more convenient to enable having multiple resources in one line:
`"resource":"pods,services,endpoints"`

**Comment by liggitt** [comment]
The policy rules are strictly additive, so you can't do `*`-resourcequota, which is what it sounds like you want. 

The new RBAC authorizer allows you to define a clusterrole that specifies permissions on multiple resources, then bind that role to multiple users in multiple namespaces
