### ISSUE TITLE
thin_ls is not available in ubuntu thin-provisioning-tools

### ISSUE THREAD

**Issue by salv-orlando** [kubernetes/kubernetes#27935]
Following a recent bump to 0.23.4 cadvisor started using thin_ls.

This utility is however not available in the ubuntu thin-provisioning-tools package, both trusty and xenial versions - unlike Fedora's device-mapper-persistent-data.

The package must be therefore be installed from sources.
I guess there's little that can be done here, but it would be nice to have a way to signal the missed dependency, as advocated by issue #26093

**Comment by vishh** [comment]
cc @pmorie @sjenning @ncdc

**Comment by sjenning** [comment]
thin_ls was disabled in cadvisor here after it was found to be way too disk intensive for large numbers of containers https://github.com/google/cadvisor/pull/1588

/close
