### ISSUE TITLE
All machines/routes/everything was deleted by jenkins in the middle of gce-serial suite.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#27930]
It happened in the run 1552 (http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-serial/1552/consoleText - it's not finished yet, so there's no external link).

I stopped the run 1551 somewhere in the middle, as it was going to fail and there was a fix for a known problem in the latest build. Run 1552 was proceeding very well until ~02:07 when it was in the middle of `[k8s.io] Kubelet [Serial] [Slow] [k8s.io] regular resource usage tracking 
  resource tracking for 100 pods per node` test. Around that time jenkis deleted the cluster (from `gcloud operations list`):
```
operation-1466672859688-535ee62cdac40-c96610e4-89fd92ca  delete                                             us-central1-f/instances/jenkins-e2e-master                    200          DONE    2016-06-23T02:07:40.123-07:00
```

```
endTime: '2016-06-23T02:08:29.234-07:00'
id: '146183410413869107'
insertTime: '2016-06-23T02:07:40.123-07:00'
kind: compute#operation
name: operation-1466672859688-535ee62cdac40-c96610e4-89fd92ca
operationType: delete
progress: 100
selfLink: https://www.googleapis.com/compute/v1/projects/kubernetes-jkns-e2e-gce-serial/zones/us-central1-f/operations/operation-1466672859688-535ee62cdac40-c96610e4-89fd92ca
startTime: '2016-06-23T02:07:40.747-07:00'
status: DONE
targetId: '9063893740187694455'
targetLink: https://www.googleapis.com/compute/v1/projects/kubernetes-jkns-e2e-gce-serial/zones/us-central1-f/instances/jenkins-e2e-master
user: <jenkins-master>
zone: https://www.googleapis.com/compute/v1/projects/kubernetes-jkns-e2e-gce-serial/zones/us-central1-f
```

@fejta @spxtr @ixdy @wojtek-t  

FYI @davidopp - this caused today's failure

**Comment by gmarek** [comment]
The only hypothesis we have is that something was waiting on worker for previous (cancelled) run and when that run would have timed out the cluster deletion kicked in.

**Comment by spxtr** [comment]
When you abort the job it doesn't actually kill the container. The next run deletes the cluster, turns up the new one, then starts tests. Then the old run finishes and deletes the cluster.

**Comment by fejta** [comment]
This is a dup of https://github.com/kubernetes/test-infra/issues/79
