### ISSUE TITLE
kube-apiserver reports TSL bad certificate issue 

### ISSUE THREAD

**Issue by manjukt** [kubernetes/kubernetes#27931]
Hi,
I'm new to Kubernetes and trying to setup cluster with 1 master and 4 nodes. After creating a pod, the kube-apiserver reports following error contineously...

$ systemctl status -l kube-apiserver
● kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2016-06-22 22:26:03 EDT; 12min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 5253 (kube-apiserver)
   Memory: 61.4M
   CGroup: /system.slice/kube-apiserver.service
           └─5253 /usr/bin/kube-apiserver --logtostderr=true --v=0 --etcd_servers=http://127.0.0.1:2379 --address=0.0.0.0 --port=8080 --kubelet_port=10250 --allow_privileged=true --service-cluster-ip-range=172.17.0.0/16 --admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota --service_account_key_file=/etc/kubernetes/key/serviceaccount.key --client-ca-file=/srv/kubernetes/ca.crt --tls-cert-file=/srv/kubernetes/server.cert --tls-private-key-file=/srv/kubernetes/server.key

Jun 22 22:38:16 kubemaster-01 kube-apiserver[5253]: I0622 22:38:16.699924    5253 logs.go:41] http: TLS handshake error from xx.xx.xx.xx:49486: remote error: bad certificate
Jun 22 22:38:16 kubemaster-01 kube-apiserver[5253]: I0622 22:38:16.699975    5253 logs.go:41] http: TLS handshake error from xx.xx.xx.xx:49487: remote error: bad certificate
Jun 22 22:38:17 kubemaster-01 kube-apiserver[5253]: I0622 22:38:17.700686    5253 logs.go:41] http: TLS handshake error from xx.xx.xx.xx:49489: remote error: bad certificate
------------------------------------------------
xx.xx.xx.xx is the node where the pod exists.
Any help will be greatly appreciated.

-Thanks,
Manju

**Comment by jlowdermilk** [comment]
> I'm new to Kubernetes and trying to setup cluster with 1 master and 4 nodes.

Can you be more specific about cluster setup? What's the version of kubernetes/host os/setup guide you are using?

**Comment by jlowdermilk** [comment]
Really tho, this question would be better posted on [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We use github issues to track bugs, feature requests, and proposals. Help/support questions get responded to much faster on stackoverflow, and you may find someone else has already posted a similar question and found a solution.
