### ISSUE TITLE
Error while trying to import Kubernetes vmdk to vsphere

### ISSUE THREAD

**Issue by purplesmurf1510** [kubernetes/kubernetes#27947]
Trying to set up a Deis2 cluster following the instructions here http://kubernetes.io/docs/getting-started-guides/vsphere/

When I get to this step "govc import.vmdk kube.vmdk ./kube/" I get the following error

[22-06-16 11:17:25] Uploading... Error: Put https://vmhost002/folder/kube/kube-src.vmdk?dsName=$DATASTORE: dial tcp: lookup vmhost002: no such host
govc: Put https://vmhost002/folder/kube/kube-src.vmdk?dsName=$DATASTORE: dial tcp: lookup vmhost002: no such host

Not sure where this is set or where to change it any help would be appreciated.

**Comment by imkin** [comment]
can you please share you environment variables? 

env | grep GOVC

**Comment by purplesmurf1510** [comment]
GOVC_NETWORK=LabOnDemand
GOVC_INSECURE=true
GOVC_URL=https://$USERNAME:$PASSWORD@192.168.***.***:9443/sdk
GOVC_DATACENTER=ESX Lab
GOVC_DATASTORE=Datastore01
GOVC_RESOURCE_POOL=Resources

**Comment by imkin** [comment]
there could be something specific in your username/password that is confusing the govc.
That is the reason why the docs for the vsphere ask you to set the following env variables.

export GOVC_URL='hostname' # hostname of the vc
export GOVC_USERNAME='username' # username for logging into the vsphere.
export GOVC_PASSWORD='password' # password for the above username
export GOVC_NETWORK='Network Name' # Name of the network the vms should join.
export GOVC_INSECURE=1 # If the host above uses a self-signed cert
export GOVC_DATASTORE='target datastore'
export GOVC_RESOURCE_POOL='resource pool or cluster with access to datastore'

**Comment by imkin** [comment]
@purplesmurf1510 Any updates?

**Comment by kylegordon** [comment]
Are you able to do 'govc datastore.ls' ? It looks like vSphere is returning a hostname that isn't resolving in DNS, and subsequently govc can't upload.

Are you able to ping, or dig, nslookup, etc your host vm0002 ?

I would investigate ensuring that it has a FQDN set, and making sure the individual ESXi hosts are resolvable in DNS. https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1010821 might help in renaming them.

**Comment by imkin** [comment]
@purplesmurf1510 Does @kylegordon's suggestion help you?

**Comment by kerneltime** [comment]
Proposing to close this issue
