### ISSUE TITLE
Support user namespace remapping

### ISSUE THREAD

**Issue by therc** [kubernetes/kubernetes#27945]
This has been available since Docker 1.10. It doesn't really allow multi-tenancy yet, but it does provide greater host isolation.

**Comment by spzala** [comment]
@therc hi, since it's been over a year of last discussion on this issue, a gentle touch base - is this still a valid feature request, or it can be closed? anything changed? Thanks!

**Comment by The-Loeki** [comment]
@spzala it is, but other issues track progress:

* https://github.com/kubernetes/features/issues/127
* https://github.com/kubernetes/kubernetes/issues/33508
* https://github.com/kubernetes-incubator/kubespray/issues/962

**Comment by spzala** [comment]
@The-Loeki cool, thanks for providing those useful ref links!!

**Comment by adelton** [comment]
The main problem with the setup seems to be pods' content in `/var/lib/kubelet` being owned by root (uid 0), and thus not accessible to the namespaced processes.

I've now filed https://github.com/kubernetes/kubernetes/pull/55707 as a possible way to make kubelet change ownership to the uid/gid matching the remapped uid, as configured in docker.
