### ISSUE TITLE
Federation: DNS resolution should work on Jenkins e2e tests

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#27949]
this is just a not bot-noise-infested version of #27739

**Comment by mml** [comment]
@kubernetes/sig-cluster-federation

**Comment by mml** [comment]
I think I see a problem.  The names all look very similar, and so it's easy to glance at a debug log and think you know what's going on.

```
I0623 16:22:47.630531       1 logs.go:41] skydns: incomplete CNAME chain from "federated-service.e2e-tests-service-jymu4.federation.svc.us-central1-f.kube.5yetis.net.": rcode 3 is not equal to success
```

I thought that name looked like it should work, but here are the actual names in the record set

```console
% gcloud dns record-sets list -z kube | grep jymu4                                          
federated-service.e2e-tests-service-jymu4.federation.svc.kube.5yetis.net.                            A     180    130.211.115.153
federated-service.e2e-tests-service-jymu4.federation.svc.us-central1.kube.5yetis.net.                A     180    130.211.115.153
federated-service.e2e-tests-service-jymu4.federation.svc.us-central1-f.us-central1.kube.5yetis.net.  A     180    130.211.115.153
```

Note that we have a record for `...svc.us-central1.kube...` but not for `...svc.us-central1-f.kube...`.  Note `-f`.

So, I assume the records in cloud DNS are correct and the zone name kube-dns is apending is wrong, and we shoud be using us-central1 instead.  Correct?

@quinton-hoole

**Comment by madhusudancs** [comment]
I will send a bug fix to this. I think this was due to a miscommunication between @quinton-hoole and myself about the way each of us were generating the names. I should have caught this in the code review, sorry.

**Comment by mml** [comment]
Awesome, thanks @madhusudancs.

**Comment by madhusudancs** [comment]
#27960 is the fix.

**Comment by goltermann** [comment]
@madhusudancs can this be closed?  #27960 appears merged

**Comment by quinton-hoole** [comment]
@goltermann Lets leave this open until we verify that DNS resolution e2e tests pass on Jenkins.

**Comment by madhusudancs** [comment]
This is fixed. Closing it.
