### ISSUE TITLE
Cannot attach writable persistent disk to daemonset with single pod

### ISSUE THREAD

**Issue by bodepd** [kubernetes/kubernetes#27959]
on 1.2.4, I have a daemonset that only results in a single pod b/c of a nodeSelector.

it still results in the following error:

```
spec.template.spec.volumes[0].gcePersistentDisk.readOnly: Invalid value: false: must be true for replicated pods > 1; GCE PD can only be mounted on multiple machines if it is read-only
```

**Comment by kargakis** [comment]
This seems like expected behavior. 

https://kubernetes.io/docs/concepts/storage/volumes/#gcepersistentdisk
