### ISSUE TITLE
Update-period missing from Deployment object

### ISSUE THREAD

**Issue by patocox** [kubernetes/kubernetes#27967]
Seems the `--update-period DURATION` is not part of the Deployment object. It is available for Rolling Updates, however. This is a great feature which would allow us to slowly update pods over time (every 10 minutes for example) to catch issues. Can this feature be added to Deployments as well?

/cc @brendandburns We discussed this at Dockercon on Monday. I also mentioned to Jeff at the conference, but didnt catch his last name.

**Comment by c1freitas** [comment]
+1 for this.

**Comment by bgrant0607** [comment]
Please use minReadySeconds

http://kubernetes.io/docs/user-guide/deployments/#min-ready-seconds

cc @kubernetes/deployment

**Comment by patocox** [comment]
@bgrant0607 From what Im reading, that doesnt do the job.

> .spec.minReadySeconds is an optional field that specifies the minimum number of seconds for which a newly created Pod should be ready without any of its containers crashing, for it to be considered available.

From the description, even though the container is ready, this is a delay before it becomes available to receive traffic. The functionality I am looking for was above and beyond this parameter. The pod is ready and available (receiving traffic) but the _next_ pod is not updated for a period of time.

ala:

> --update-period DURATION: The time to wait between updating pods.

**Comment by bgrant0607** [comment]
@patocox No, minReadySeconds actually controls the progress of the rollout in combination with maxUnavailable. An oblivious rate limit could still stomp all over your application. By monitoring availability, we ensure the update does not cause your entire service to go down.

The documentation could be clarified. @janetkuo
