### ISSUE TITLE
kubernetes-e2e-gce-scalability-release-1.3 hasn't run in 2 days

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#27962]
@spxtr kubernetes-e2e-gce-scalability-release-1.3 shows that it hadn't run in 2 days.  I kicked off a manual "build now".  I assume a cronjob entry should be configured to make it run periodoically?

**Comment by alex-mohr** [comment]
Claim to P1 is that we need to have all the CI 1.3 suites automatically running as much as possible, especially over the weekend, to build confidence in the 1.3.0 that we put out.

Joe, may also be worth a quick audit of the other 1.3 suites to make sure they all have the appropriate cronjob entry?

**Comment by spxtr** [comment]
That job is configured to only run on Saturday at 8 AM: https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml#L342

@gmarek set this back in release-1.2 in #23042. I'm guessing it's fine to bump it to run daily?

**Comment by gmarek** [comment]
Cc @wojtek-t

**Comment by spxtr** [comment]
I checked the other 1.3 jobs. They're running as often as they should be.

**Comment by gmarek** [comment]
This means it's OK to tune it up over the weekend, as long as we'll go back to the "slow" testing when we're confident enough.

**Comment by alex-mohr** [comment]
Thanks Joe and Marek!  Sounds like it's not a release blocker then given the manual run and we can enable after 1.3 build is cut.
