### ISSUE TITLE
restclient only retries if Retry-After header is set.

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#27965]
We want the client to retry on 500s and 429s, but it currently only does so if the Retry-After header is set.

This appears to be the underlying cause of #27839, #27537, and #27506.

The [retryAfterSeconds function](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/restclient/request.go#L1022) tries to parse the Retry-After header to determine a server-indicated minimum backoff. If it doesn't find one (or can't parse it), it returns `0, false`, which means "no retry." It should return `0, true`.

**Comment by cjcullen** [comment]
@kubernetes/sig-api-machinery @krousey

**Comment by cjcullen** [comment]
Discussed this a bit in person. Assigning to Kris.

**Comment by lavalamp** [comment]
I'd posit that you should *not* return `0, true` unless you know (and test) that something else prevents a hot loop.

**Comment by lavalamp** [comment]
@smarterclayton

**Comment by krousey** [comment]
@lavalamp I think https://github.com/kubernetes/kubernetes/blob/master/pkg/client/restclient/request.go#L807 is what prevents a hot loop.

**Comment by smarterclayton** [comment]
The original intent was to be EXTRA safe and not loop if we couldn't cleanly parse a non zero loop.  There were cases where backoff could be disabled.  I'd prefer something that is not zero being used (if the server says zero, we use 0.20s or something).

**Comment by krousey** [comment]
Looking at the history of this file, it seems that it was never the intent of this to retry unless there was a Retry-After header.

**Comment by wojtek-t** [comment]
@krousey - the backoff manager is by default no-op. So unless someone explicitly set it (which we don't do), there is no protection.

**Comment by lavalamp** [comment]
Yes, that's my recollection, too. The list of things we're willing to retry
should at the very least be curated. e.g., certainly not 401 etc...

**Comment by krousey** [comment]
The current filter is `(status == 429 || status >= 500) && hasRetryAfterHeader`.

**Comment by smarterclayton** [comment]
Yeah, original intent was requirement that retry-after be specified and valid and non-zero.

**Comment by cjcullen** [comment]
Ahhh okay. I have been duly educated. Sorry for the scare.

**Comment by cjcullen** [comment]
We will implement the retry-after header to get the retry behavior we want.

**Comment by krousey** [comment]
I think the general consensus is that retry logic either belongs on the server and communicated via `Retry-After` headers (that restclient will respect), or further up the client stack where there is more context to interpret 500 errors.
