### ISSUE TITLE
Race condition in kubenet.SetUpPod() for rkt containers

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#27975]
Captured from https://github.com/kubernetes/kubernetes/pull/27914#issuecomment-228140108

Today the SetUpPod() is called before the rkt pod is actually running (which enables we have the pod IP before hand and inject that into Downward API and /etc/hosts). 

However in the SetUpPod(), it will list try to maintain the host port iptable rules by gathering all the host ports from running pods, which will cause a race when multiple pods starts at the same time as described in the above linked comment.

cc @kubernetes/sig-rktnetes @kubernetes/sig-node @kubernetes/sig-network

**Comment by yifan-gu** [comment]
Still sees some error when some time l7 and dns pods running together. Not sure about the reason yet, so keep the issue open.

**Comment by cmluciano** [comment]
Is this still happening @yifan-gu

**Comment by yifan-gu** [comment]
@cmluciano I believe so, /cc @JulienBalestra

**Comment by yujuhong** [comment]
Closing since we are deprecating rktnetes (#53601)
