### ISSUE TITLE
Authorizer.Authorize() should return (bool, error)

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#27974]
The [Authorizer interface](https://github.com/kubernetes/kubernetes/blob/master/pkg/auth/authorizer/interfaces.go#L76) only returns an error today. This means that clients tend to treat any error as a "No" and return forbidden (e.g. our main [apiserver handler](https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/handlers.go#L484)).

Our authorizers have become more complicated (and have upstream dependencies in the case of the webhook). If the authorizer cannot make a decision, the apiserver should return a retryable error (probably a 503 or 504) rather than a 403 that the client will most likely not retry.

**Comment by cjcullen** [comment]
@kubernetes/sig-auth

**Comment by deads2k** [comment]
I think that's a good idea.  We use `Authorize(ctx api.Context, attributes AuthorizationAttributes) (allowed bool, reason string, err error)` in OpenShift.  That way an error means there was a problem during evaluation, it isn't an indicator of a normal denial, but an authorizer can still providing information about denials.

**Comment by liggitt** [comment]
+1 for tweaking the return value to distinguish error cases from yes/no decisions
+1 for including a context param to allow request tracing, etc

**Comment by nhlfr** [comment]
I'm working on this.
