### ISSUE TITLE
Don't store selfLinks

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#2797]
When we return an object over our REST api, we set a self link, so that users can figure out where the object came from.

If a use does a GET, updates some fields, and then does a PUT, our server's Update() method will get an object with a nonempty SelfLink.

There's no reason to allow SelfLink to be set when we persist objects to disk (etcd). And in fact SelfLink is useful only for clients. So Update() methods should clear out SelfLink before doing anything with the object. Create() methods should either give an error if a SelfLink is given or silently clear it out.

Perhaps apiserver's resthandler.go is a good place to remove SelfLinks, since that's where we add them.

**Comment by bgrant0607** [comment]
This is either obsolete or will be easily rediscovered.
