### ISSUE TITLE
Clarifying API guarantees of informer

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#27984]
As one shared informer will be depended on by many controllers, it becomes more and more important to make informer reliable and easy to reason about. Therefore, we create this issue to collect all assumptions and try to provide clear guarantees and easy reasoning of informer APIs.

As first step, here are a list of API guarantees that we need to clarify:
- Delivery of events from informer handler.
  - **Is event ordering sequential?** In [SharedInformer.AddEventHandler()](https://github.com/kubernetes/kubernetes/blob/308201acb0e1515dab33b015c05ca31e40662aa0/pkg/controller/framework/shared_informer.go#L38) it says “events to a single handler are delivered sequentially”. Currently DeltaFIFO is a keymap queue with undocumented priority and optional overriding . AFAIK, no compression (overriding) is done on DeltaFIFO in informer and there will be as many events in keymap queue as normal FIFO queue. What's the guaranteed of the queue? What’s the guarantee of event delivery to informer handler?
  - **Are operations and event delivery atomic?** Could interleaving events of different operations happen? For example, a Delete event in between Relist/Resync events. For stronger guarantee we shouldn't let this happen. Do we have atomicity in event delivery and processing?
  - **Snapshot isolation on store** When calling store.List() or doing Resync, do we have snapshot isolation guarantee on store? That say, reads on all keys give a consistent snapshot of the data store.
  - **What’s delivery semantics?** Exactly once? At least once? At most once?
- In shared informer, each handler has its queuing of events. But the queuing shouldn’t be infinite. We should kill it before one OOM and takes down other informer users. @deads2k
  - When should we kill/disconnect a handler? How many items should we say the queue is too long?
  - If a handler gets disconnected, what event should he get?
  - If a user is killed and tries to rejoin, what states should he get?
- Is Informer readonly to user?
  - Requeue() is known to be problematic (#27790) and even make changes to informer from user. Why do we need Requeue()? Is informer guaranteed to be readonly?

Of course, there will be more questions coming through as we are making progress in different areas. We could coordinate API guarantees here and make informer as clarified as possible.

**Comment by hongchaodeng** [comment]
We should discuss it in @kubernetes/sig-api-machinery meeting

**Comment by deads2k** [comment]
> In shared informer, each handler has its queuing of events. But the queuing shouldn’t be infinite. We should kill it before one OOM and takes down other informer users. @deads2k
> 
> When should we kill it? How many items should we say the queue is too long?
> If a user is killed and tries to rejoin, what states should he get?

I think resolving this case is good.  I think I would start by resolving the "join late" scenario and then describe how to disconnect "naughty" handlers.  That way we never end up in a state where we can disconnect controllers, but they have no way to self-correct.

**Comment by lavalamp** [comment]
I recommend writing tests demonstrating (lack of?) desired behaviors.

**Comment by wojtek-t** [comment]
>
I recommend writing tests demonstrating (lack of?) desired behaviors.

+100

**Comment by hongchaodeng** [comment]
Seems like you guys all agree with that.
Let's discuss it on Wed meeting and make sure we all agree on the "desired behaviors".

**Comment by deads2k** [comment]
@hongchaodeng have you gotten a handle on the current semantics?  I think I'd summarize it like this.   

On the producer side:
1. A reflector watches an API endpoint.
1. For each watch event, it queues the event in the delta fifo.
1. The event's object is inspected to determine a key.
1. The delta fifo uses the key to add a delta to the list of deltas associated with the key.
1. It also adds the key to a list of "these keys were changed".  If the key is already in "these keys were changed"


On the consumer side:
1. call pop and wait until a key is available in the "these keys were changed"
1. find all the deltas for that key
1. call the processFunc with all the deltas

I think we're pretty happy with those semantics.  It's like a first come, first served, but don't waste time with outdated information.

There are details around compression I didn't get into, but you can choose to compress the list of deltas to eliminate unnecessary ones based on a function of your choosing.

**Comment by wojtek-t** [comment]
>
There are details around compression I didn't get into, but you can choose to compress the list of deltas to eliminate unnecessary ones based on a function of your choosing.

Yeah - but I'm not sure anyone is really using it...

**Comment by deads2k** [comment]
> Yeah - but I'm not sure anyone is really using it...

Largely because we wire them to work queues.  I think I'd be in favor of using compression by default at some point, but I don't see it as particular important.

**Comment by wojtek-t** [comment]
I agree it makese sense to use compression. What I wanted to say is that if we want to change something about it, it shouldn't be a problem now, since (I think) noone is using it.

**Comment by alexellis** [comment]
@hongchaodeng did you find out the delivery semantics?

> What’s delivery semantics? Exactly once? At least once? At most once?

Is there a standard way to give an exact once delivery or handling in a controller? I.e. if the message/event will cause a notification or alert. 

I tried this out with `cache.NewSharedIndexInformer` and it seems like sometimes I get the message about a deployment being created half a dozen times.
