### ISSUE TITLE
Deleting a backend deletes too many DNS records

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#27989]
Step 1.  Create a two-cluster federation, one in zone A one in F.  Create a loadbalancer service in the federation, and create one pod in each cluster that matches the service selector.  Result is good:

```
NAME                                                                                                 TYPE  TTL    DATA
kube.5yetis.net.                                                                                     NS    21600  ns-cloud-b1.googledomains.com., ns-cloud-b2.googledomains.com., ns-cloud-b3.googledomains.com., ns-cloud-b4.googledomains.com.
kube.5yetis.net.                                                                                     SOA   21600  ns-cloud-b1.googledomains.com. cloud-dns-hostmaster.google.com. 4 21600 3600 259200 300
federated-service.e2e-tests-service-lt9rd.federation.svc.kube.5yetis.net.                            A     180    104.197.202.248, 23.236.61.35
federated-service.e2e-tests-service-lt9rd.federation.svc.us-central1.kube.5yetis.net.                A     180    104.197.202.248, 23.236.61.35
federated-service.e2e-tests-service-lt9rd.federation.svc.us-central1-a.us-central1.kube.5yetis.net.  A     180    104.197.202.248
federated-service.e2e-tests-service-lt9rd.federation.svc.us-central1-f.us-central1.kube.5yetis.net.  A     180    23.236.61.35
```

Step 2.  Delete the pod in F.

```console
% kc --context=federation-e2e-gce-us-central1-f delete pod backend --namespace=e2e-tests-service-lt9rd
pod "backend" deleted
```

Step 3. Zone file looks very sad.  The remaining A record feels very lonely.  :sob:
```
NAME                                                                                                 TYPE  TTL    DATA
kube.5yetis.net.                                                                                     NS    21600  ns-cloud-b1.googledomains.com., ns-cloud-b2.googledomains.com., ns-cloud-b3.googledomains.com., ns-cloud-b4.googledomains.com.
kube.5yetis.net.                                                                                     SOA   21600  ns-cloud-b1.googledomains.com. cloud-dns-hostmaster.google.com. 4 21600 3600 259200 300
federated-service.e2e-tests-service-lt9rd.federation.svc.us-central1-a.us-central1.kube.5yetis.net.  A     180    104.197.202.248
```

[federation-controller-manager.log.txt](https://github.com/kubernetes/kubernetes/files/330980/federation-controller-manager.log.txt)

@quinton-hoole @kubernetes/sig-cluster-federation

**Comment by quinton-hoole** [comment]
@mml Did you manage to get any logs from the controller-manager?  Any errors reported there?

**Comment by mml** [comment]
@quinton-hoole logs are attached.  I did not see any out of the ordinary messages.

**Comment by quinton-hoole** [comment]
I think this bug is introduced by this commit:

https://github.com/kubernetes/kubernetes/commit/dd78dd8e2b623d32b57a084a855a2a0327d55f38

The endpointReachable logic here is flawed.  I'm sorry I did not pick that up in the code review.
There are multiple endpoints passed into ensureDnsRrsets().  So adding a single boolean endpointReachable doesn't make sense. We rather need to remove the endpoint that is unreachable from the list of endpoints passed in by the caller.  Then the logic should all work correctly.  I'll essentially revert the above commit, and replace it as described.

@mfanjie, do you agree?

Will send a fix shortly.

**Comment by quinton-hoole** [comment]
https://github.com/kubernetes/kubernetes/pull/27999 is my proposed fix.

**Comment by mfanjie** [comment]
@quinton-hoole thanks for catching this up, and sorry for the regression. I am fine with your proposal.
