### ISSUE TITLE
Get fluentd-es working properly again

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#27988]
In both #27981 and #26652, I've been unable to build a version of fluentd-es that works based on the checked-in Dockerfile.

If I try to build the container based on the checked-in dockerfile, I get an error installing the elasticsearch plugin:

```
ERROR:  Error installing fluent-plugin-elasticsearch:
    ERROR: Failed to build gem native extension.
[...]
```

There's also the issue that the checked-in config file includes the metadata filter plugin, which doesn't work in default deployments, presumably because the container is still being deployed from a pod manifest rather than as part of a daemon set:

```
2016-06-23 23:21:23 +0000 [error]: config error file="/etc/td-agent/td-agent.conf" error="Invalid Kubernetes API v1 endpoint https://10.251.240.1:443/api: SSL_connect returned=1 errno=0 state=error: certificate verify failed"
2016-06-23 23:21:23 +0000 [warn]: process died within 1 second. exit
```

By 1.4 we should make sure we can get #23306 in to help with that, if it is indeed the cause. There's really very little reason for fluentd-es to be so different from fluentd-gcp. They don't actually even need to be separate images, they only really need different config files.

**Comment by wangzhuzhen** [comment]
The same error that I have met:

`[error]: config error file="/etc/td-agent/td-agent.conf" error="Invalid Kubernetes API v1 endpoint https://10.254.0.1:443/api: SSL_connect returned=1 errno=0 state=error: certificate verify failed"`

How to solve this?  Please give some advice.

**Comment by piosz** [comment]
Closing as obsolete.

cc @Crassirostris

**Comment by cleverlzc** [comment]
The same error：
```
config error file="/etc/td-agent/td-agent.conf" error="Invalid Kubernetes API v1 endpoint 
https://10.254.0.1:443/api: SSL_connect returned=1 errno=0 state=error: certificate verify failed"
```
Any solution?  Thanks in advance!!!

**Comment by cleverlzc** [comment]
@wangzhuzhen

**Comment by cleverlzc** [comment]
How did you solve it？ @wangzhuzhen

**Comment by crassirostris** [comment]
@cleverlzc Check your apiserver logs for related errors. Try logging into the container (base image is debian, so there's api-get available) and accessing Kubernetes API manually.

We have [e2e tests](https://k8s-testgrid.appspot.com/google-gce#gci-gce-es-logging&width=20) to verify that ES DS is working, so that's a problem with your deployment configuration, that's what I can tell with the data I have :)

**Comment by trunet** [comment]
I don't think this should be closed without further investigation.

On my fluentd containers, I have the serviceaccount correctly setup:
```
# ls -lha /run/secrets/kubernetes.io/serviceaccount/      
total 4.0K
drwxrwxrwt. 3 root root  140 Jul 25 13:10 .
drwxr-xr-x. 3 root root 4.0K Jul 25 13:11 ..
drwxr-xr-x. 2 root root  100 Jul 25 13:10 ..7987_25_07_15_10_30.059759645
lrwxrwxrwx. 1 root root   31 Jul 25 13:10 ..data -> ..7987_25_07_15_10_30.059759645
lrwxrwxrwx. 1 root root   13 Jul 25 13:10 ca.crt -> ..data/ca.crt
lrwxrwxrwx. 1 root root   16 Jul 25 13:10 namespace -> ..data/namespace
lrwxrwxrwx. 1 root root   12 Jul 25 13:10 token -> ..data/token
```

Per https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter documentation, you can include ca_file parameter on td-agent.conf file and the ca certificate will be used.

**Comment by crassirostris** [comment]
@trunet Could you please open a new issue with a clear description of the setup and steps to reproduce?

FYI @coffeepac

**Comment by trunet** [comment]
thanks, just created #49570
