### ISSUE TITLE
[GKE] GCI nodes are coming up without routes

### ISSUE THREAD

**Issue by fabioy** [kubernetes/kubernetes#27994]
Testing 1.3.0-beta.2 with GCI on GKE show the nodes coming up with no routes for them. In the conditions for the node, I see:

 NetworkUnavailable    True    Mon, 01 Jan 0001 00:00:00 +0000         Thu, 23 Jun 2016 17:12:24 -0700         NoRouteCreated                  Node created without a route

**Comment by alex-mohr** [comment]
Is the same issue present in a recent 1.4.0-alpha build drawn from a jenkins CI build?

**Comment by wojtek-t** [comment]
@fabioy - do those nodes stay without routes forever, or are those routes finally created?

If the latter, the issue is in route-controller, which only checks for routes existence every 5 minutes, and if any is missing creates it:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/route/routecontroller.go#L73

This was always like this (yes - we need to fix it at some point), but in 1.3 we added "NetworkUnavailable" condition, because it is actually a bug to schedule on nodes without route, because network doesn't work on it. In previous releases nothing prevented from scheduling on nodes without routes, which made them not-usable in some cases, even though they were technically running & ready.

**Comment by dchen1107** [comment]
Here is the internal bug: b/29618683 

@wojtek-t I am not sure if the route is created or not, but routecontroller still claims there is no router after several hours.

**Comment by dchen1107** [comment]
Also why this is marked as P0 blocker for 1.3 release here? If I understand correctly, shouldn't this behavior only happen to running the nodes with GCI images, which is out of 1.3 scope? Otherwise, shouldn't our test infrastructure is completely broken?

**Comment by wojtek-t** [comment]
Thanks @dchen1107 . If route-controller claims that there is no route after few hours, then the issue is something different.

**Comment by wonderfly** [comment]
The issue detail didn't include the fact that this is with GCI on the nodes, which is not in any production setup. So not sure if it's worth a P0 or milestone 1.3.

> Is the same issue present in a recent 1.4.0-alpha build drawn from a jenkins CI build?

We do run GCI on nodes in our continuous e2e tests. In fact, the same GCI image, and k8s 1.3.0-beta2, have been used in the last tens of tests (on GCE) and have been consistently passing. There was one case where we saw similar issues, but it disappeared soon enough.

**Comment by wonderfly** [comment]
cc/ @kubernetes/goog-image

**Comment by fabioy** [comment]
@wojtek-t No, it seems the route never becomes available. One of the clusters was up for a few hours.

I'm ok with downgrading this from a P0, but it's a blocker for deploying 1.3 on GKE.

**Comment by wonderfly** [comment]
> but it's a blocker for deploying 1.3 on GKE.

GKE only runs the master on GCI atm right? Were you able to confirm that this problem exists in a hybrid GKE cluster (master on GCI and nodes on debian) too? That will help isolate the problem I think.

**Comment by fabioy** [comment]
Yes, I've tested in both configurations (nodes in containerVM and GCI). In the GCI candidate build with 1.3.0-beta.2 that I've tested, the failure rate has been 100%. 

Is it possible that it's just that image that's bad?

**Comment by dchen1107** [comment]
@fabioy I must miss something here and don't understand why this is a blocker for 1.3.

Like what I mentioned in the internal bug, for 1.3 release, the decision is only running master node with GCI image, not worker nodes. That is why we figure out create 3 different set of tests for 1) both master and worker node on containerVM (old setup) 2) master on GCI, and work nodes on containerVM (1.3 release) 3) both on GCI (next release hopefully). In your setup, both master and worker nodes are running on GCI, which is not in 1.3 scope. 

I agree that route is not available is a P0 issue, and we should fix as soon as possible. But again, why it is a blocker for 1.3?

**Comment by fabioy** [comment]
@dchen1107 I'm re-running my manual tests, but it seems that, at least on GKE (using the candidate image), the GCI master/containerVM nodes combinations still brings up a broken cluster. Given this data, this may not be a blocker for 1.3 release, but it is certainly a blocker for deploying 1.3 on GKE.

**Comment by dchen1107** [comment]
@fabioy Thanks for the updates. 

Based on what you post last, looks like this issue has nothing to do with GCI image itself. Right? Also if there is an issue of the route creation, shouldn't all our gke test clusters are broken? Sorry for keeping asking all those questions. I just try to figure out where the breakage is.

**Comment by dchen1107** [comment]
@fabioy Can you share me your cluster information, I can take a quick look?

**Comment by fabioy** [comment]
@dchen1107 I'll email you the info for both clusters. Give me a sec. Thanks.

**Comment by fabioy** [comment]
@dchen1107 One more clarification point, the reason this is a GKE blocker is because GCI is available to production users. Unless we understand and fix it, 1.3.0 will NOT be deployed on GKE.

**Comment by wojtek-t** [comment]
@fabioy - what is strange to me is that we've never seen that in tests. In particular gke-large-cluster has currently 2000 nodes, and we have some tests that wait for all ready nodes to have routes. And I've seen at least few runs where all 2000 nodes had routes and been ready.
Is there any configuration/startup difference between how we create GKE clusters from Jenkins and how did you created your own cluster where you found it? Maybe that will help us understand this issue.

**Comment by dchen1107** [comment]
(Should send the update sooner, was distracted by other issues...)

@fabioy Thanks for the info of your clusters. I took a quick look at them. 

Like what I suspected yesterday, I believe there is a configuration issue in GKE with GCI image in general. From kube-controller-manager.log, I noticed that 

```
E0624 15:42:42.690615       5 gce.go:2122] Error getting routes from GCE: Get https://www.googleapis.com/compute/v1/projects/cloud-kubernetes-dev/global/routes?alt=json&filter=name+eq+gke-fabioy-1-3-gci-again-3-.%2A: googleapi: Error 404: Not Found
```

I also checked glbc log, and noticed a similar permission issue: 
```
I0624 15:44:03.222022       5 controller.go:193] Starting loadbalancer controller
W0624 15:44:03.278960       5 pools.go:88] Failed to list: googleapi: Error 403: Insufficient Permission, insufficientPermissions
I0624 15:44:08.575600       5 cluster_manager.go:89] Reporting cluster as healthy, but unable to list backends: googleapi: Error 403: Insufficient Permission, insufficientPermissions
W0624 15:44:33.388173       5 pools.go:88] Failed to list: googleapi: Error 403: Insufficient Permission, insufficientPermissions
...
```

**Comment by alex-mohr** [comment]
@dchen1107 @wonderfly I think we should clarify: GCI is *very much available in production* for GKE.  But it's on an opt-in basis.  What we decided for 1.3 is that ContainerVM remains the default -- GCI is an optional alternative.  But that means we absolutely do need to make sure GCI works and as a team have a commitment to ensure it.

**Comment by wonderfly** [comment]
Agreed. Just wanted to clarify if this was a 1.3 blocker, which seems to be false.

**Comment by andyzheng0831** [comment]
To the comment https://github.com/kubernetes/kubernetes/issues/27994#issuecomment-228416961, @alex-mohr did you mean master or nodes? My understanding is "nodes", right?

**Comment by dchen1107** [comment]
@fabioy I list the routes created for your project, and found they are not created: 

$ gcloud compute routes list --project=gke-dev-us-central1-c-0 
NAME                            NETWORK  DEST_RANGE     NEXT_HOP                  PRIORITY
default-route-d05e731891814baf  default  0.0.0.0/0      default-internet-gateway  1000
default-route-e2e1e99fcf8b48ef  default  10.240.0.0/16                            1000

In k8s kube-up creates those node routes. I am not sure if GKE use different path to create those routes? I also really suspect there is a breakage in your own setup, but I didn't figure it out. But this explains the error message in routecontroller I mentioned above:

Error getting routes from GCE: Get https://www.googleapis.com/compute/v1/projects/cloud-kubernetes-dev/global/routes?alt=json&filter=name+eq+gke-fabioy-1-3-gci-again-3-.%2A: googleapi: Error 404: Not Found

I am reassigning this back to you. 

I also chat with @andyzheng0831 and other GCI folks. @andyzheng0831 can help you rule out the potential issue caused by the bad gci image even I doubt about that.

**Comment by fabioy** [comment]
Sorry everyone, this was my bad. My dev cluster didn't have the proper permissions, so it couldn't resolve the auth token to create routes. I should have known better. Testing on the test environment had the latest image work. Closing issue.

**Comment by alex-mohr** [comment]
Glad to hear it's resolved -- and sorry for the interrupts!

@wonderfly For the record, yes, I meant nodes.  For 1.3, the default (and only, I think) image for masters is GCI.  For 1.3, the default image for nodes is ContainerVM but GCI is a user-selectable option.  If GCI nodes don't work with 1.3, we can't roll 1.3 out to GKE, so it would block the release of kubernetes 1.3 on GKE.

**Comment by resouer** [comment]
@fabioy What did you do to grant proper permission to run e2e? I am facing the same insufficient permission problem (and it's should be my fault), but I don't know how to fix it ...

**Comment by fabioy** [comment]
@resouer My issue was with an internal configuration issue on my private GKE dev environment. It shouldn't affect you if running on GCE. I'd suggest taking a look at the route controller logs for hints as to why it couldn't create the routes in your cluster.
