### ISSUE TITLE
Too frequent: "Waiting for .* controller to sync"

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#27991]
controller manager fails with a hot loop here, logging the message multiple times per ms.

@caesarxuchao observed this in the garbage collector-- did you end up fixing it?

**Comment by caesarxuchao** [comment]
It's different from the garbage collector issue.

The GC message is [generated](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/cache/reflector.go#L203-L207) in reflector.go, and it's actually generated every second, so I think it's correct.

The "Waiting for .* controller to sync" is [generated](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller.go#L554) in each controller, and it will be fixed if all controllers use the `RateLimitingQueue`, but I think that deserves another issue.
