### ISSUE TITLE
TLS Configuration

### ISSUE THREAD

**Issue by hmrm** [kubernetes/kubernetes#2799]
I've gotten a request to be able to configure the TLS used internally by Kubernetes (e.g. specify cipher suites, minimum SSL/TLS version, etc.). This will likely be a number of additional options; what would be the preferred method of implementing this? More command line options, a config file, something else?

**Comment by mattjay** [comment]
This is more important now as Apple just upped its TLS game with iOS 9's new ATS requirements.
https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/

```
    The server must support at least Transport Layer Security (TLS) protocol version 1.2.
    Connection ciphers are limited to those that provide forward secrecy (see the list of ciphers below.)
    Certificates must be signed using a SHA256 or better signature hash algorithm, with either a 2048 bit or greater RSA key or a 256 bit or greater Elliptic-Curve (ECC) key.
    Invalid certificates result in a hard failure and no connection.

These are the accepted ciphers:
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
```

**Comment by lavalamp** [comment]
This should be relatively easy for someone to jump in and do if we confine it to just exposing the TLS options as flags/config file settings.

**Comment by glesage** [comment]
Hey all, is there any way to do this currently or this is still in the works? (I'm specifically looking to configure ciphers in order to be PCI compliant as a payment provider)

**Comment by liggitt** [comment]
Not possible yet. https://github.com/kubernetes/kubernetes/issues/42337 plumbs options to the apiserver (not the kubelet) but doesn't wire them to flags yet.

**Comment by glesage** [comment]
I actually found what I was looking for in https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md#allowed-parameters-in-configuration-configmap

Thanks!

**Comment by howsTricks** [comment]
/reopen
/remove-lifecycle rotten

This still appears to be an issue, not seeing any way to configure internal TLS options (nor should TLS1.0 even be an option, let alone the default).

**Comment by liggitt** [comment]
TLS defaults to 1.2

Both TLS version and ciphers are controllable by flags as of 1.10

**Comment by howsTricks** [comment]
Ah wow, thanks! I'll take a look.

**Comment by deshui123** [comment]
we also are not allowed to use medium strength encryption(key lengths at least 64 bits and less than 112 bits, or else that uses the 3DES encryption suite.)
My kubectl version is 1.10.2, but I dod't find the flag which can set TLS  version.
Could you please the guide/cli for the flag？

**Comment by liggitt** [comment]
detailed help text was added in https://github.com/kubernetes/kubernetes/pull/58920

the options are: 
> --tls-min-version string                                  Minimum TLS version supported. Possible values: VersionTLS10, VersionTLS11, VersionTLS12
> --tls-cipher-suites strings                               Comma-separated list of cipher suites for the server. If omitted, the default Go cipher suites will be use.  Possible values: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_RC4_128_SHA,TLS_RSA_WITH_3DES_EDE_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_RC4_128_SHA

**Comment by deshui123** [comment]
Thanks for your support. 
I tried kubelet cli with flag but received "deprecated"
`[root@h]$ # kubelet  --tls-min-version VersionTLS12
Flag --tls-min-version has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.`

Then I set the config file according to https://github.com/kubernetes/kubernetes/blob/release-1.10/pkg/kubelet/apis/kubeletconfig/v1beta1/types.go and it works.
1) For kubelet config(kubelet-config.yml):
TLSCipherSuites: ['TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256']
TLSMinVersion: "VersionTLS12"
2) For kube-controller-manager.yml
- --tls-min-version=VersionTLS12
- --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
3)For kube-apiserver.yml
- --tls-min-version=VersionTLS12
- --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

**Comment by liggitt** [comment]
For the config file, be sure you use the json tag names: `tlsMinVersion` and `tlsCipherSuites`
