### ISSUE TITLE
Case report: Job somehow made 84k pods

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#27997]
Observed a case where a Job somehow created 84k pods. I think the user had set parallelism to 0 to pause it by the time I saw it. So I'm not sure how exactly to reproduce, but we should think about implementing some sanity limits. P1 since I was paged about this.

**Comment by lavalamp** [comment]
@erictune

**Comment by fabioy** [comment]
Meanwhile, some related issues to help mitigate this: #13774, #25146 (maybe).

**Comment by mikedanese** [comment]
I know how to make infinite pods:
```console
$ cat docs/user-guide/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  parallelism: 100
  template:
    metadata:
      name: pi
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
$ kubectl create -f docs/user-guide/job.yaml
```

**Comment by mikedanese** [comment]
IMO, the internal type parallelism and completions should not be pointers

**Comment by mikedanese** [comment]
> IMO, the internal type parallelism and completions should not be pointers

@erictune if you say this is the right way to fix it I will go ahead and do it. Alternatively we can fix this by hardening our validation and defaulting but there's always oppurtunity that something else will split in. I don't think there's any reasons for those fields to ever be pointers by the time the reach the internal code.

**Comment by lavalamp** [comment]
This isn't new in 1.3 and I don't think we're going to hold the release for it, but if you get a fix merged by tomorrow's burndown meeting that's OK with me, too.

**Comment by mikedanese** [comment]
Easy fix in https://github.com/kubernetes/kubernetes/pull/28008, but i still think that the internal types should become non pointers. That's a bigger change.

**Comment by mikedanese** [comment]
Actually I think i was mistaken and the behavior I observed is by design. I'll revisit tomorrow.

**Comment by soltysh** [comment]
I've commented [on Mike's PR](https://github.com/kubernetes/kubernetes/pull/28008#issuecomment-228334979).

**Comment by soltysh** [comment]
@mikedanese with your example (each job's run is a failure) the job will keep on creating that many pods as you allow it to. We don't have any mechanism preventing your from doing so. We could add something like that, though.

**Comment by soltysh** [comment]
I've carefully checked the job logic once again, we have two necessary check in place:
1. finish a job when at least one successful pod is there and no more active pods (see [here](https://github.com/kubernetes/kubernetes/blob/eedc438da94733e4b2be1ca7064d70ebb64fafa1/pkg/controller/job/controller.go#L389-L391));
2. not to start new pods when there's at least one successful execution (see [here](https://github.com/kubernetes/kubernetes/blob/eedc438da94733e4b2be1ca7064d70ebb64fafa1/pkg/controller/job/controller.go#L503-L507)). 

With the current logic though, it can be easily overused (see Mike's [example](https://github.com/kubernetes/kubernetes/issues/27997#issuecomment-228232834) where each pod execution fails), but on the other hand every job will create tons of pods when each execution is failing. That's how jobs were created. Unless we'll know exact use case that caused this (@lavalamp any chance for that?) it's hard to guess. 

And although, it's still valid to have some security net, I'm thinking (we've struggled with a use case similar to this one already some time ago, with scaling RCs) this is what quota is for, right?

**Comment by lavalamp** [comment]
It's worth noting that these pods were *Pending*, not *Failed*.

**Comment by soltysh** [comment]
Hmm.... that's interesting... I'll try to dig into it next week.

**Comment by randalloveson** [comment]
I believe I'm seeing something a lot like this. No one job with anywhere near 48k pods, but many jobs did create multiple pods when their existing pods were in a Pending state (this is with parallelism 1 and completions 1 and container restart policy Never). I would think that the jobs would only make a new pod if they were sure the old one had failed or otherwise wasn't going to make any more containers, but it appears that (at least under extremely heavy load (~4,000 jobs/hour)) they will make more pods to fulfill themselves even if the old ones are Pending.

**Comment by soltysh** [comment]
@randalloveson that is a valid clue, I'll check our tests if they cover the case where the pods are stuck in pending state.

**Comment by soltysh** [comment]
It doesn't look like it had to do with pending pods, see #28597 where I've added that test case explicitly. @randalloveson can you provide a reproducer, that would be very helpful.

**Comment by randalloveson** [comment]
@soltysh I believe the reproduction conditions might be when requests to etcd for Pod status start falling short of some timeout used by the controller. When that happens, it seems like the Job that spawned the Pod assumes the worst and makes a new Pod, exacerbating the problem.

That or Jobs really will just ignore an existing Pod they created known to be in a Pending state and make more, which, were it the case, would be a really destructive design.

**Comment by soltysh** [comment]
I'm starting to wonder if this has to do something with https://github.com/kubernetes/kubernetes/issues/28486. I need to do more thorough testing in that case.

**Comment by kargakis** [comment]
Not sure this was ever fixed

**Comment by mikedanese** [comment]
Do you want to fix the operator error mentioned here: https://github.com/kubernetes/kubernetes/issues/27997#issuecomment-228232834 ?

**Comment by kargakis** [comment]
We can identify failures and ratelimit the culprits. This is the same problem as when you specify a Deployment with a bad node selector.

**Comment by soltysh** [comment]
This will be fixed when we introduce the job failure policy.

**Comment by splittingfield** [comment]
Do we have an update on this job failure policy?  I think we have hit a related issue.


We recently found an issue in which a Job had an init container that was exiting with a non-zero code (there was a bug in the init-container). This led to the Job being restarted repeatedly. Soon, the entire K8s  cluster (1.6) across all namespaces become sluggish and unresponsive, requiring manual deleting, etc. 

We understand that the `restartPolicy:Never ` does not apply to Jobs (https://github.com/kubernetes/kubernetes/issues/20255) However, we are unable to set the `activeDeadlineSeconds` as these init container is moving large amounts of data and the Job itself can be arbitrarily long (easily multiple days if training a large deep learning model).

I am happy to help collect more data to help debug this issue if there is anything you would want use to share? (We are currently collecting data ourselves for a post-mortem).

**Comment by soltysh** [comment]
There's https://github.com/kubernetes/community/pull/583 addressing this issue, along with the implementation in #48075 and #51153.
