### ISSUE TITLE
cluster-monitoring in ubuntu.

### ISSUE THREAD

**Issue by chowyu08** [kubernetes/kubernetes#28001]
### no one of  heapster, Influxdb and Grafana bring up

I have run kubernetes in ubuntu by the commond: KUBERNETES_PROVIDER=ubuntu ./kube-up.sh 
in file kubernetes/cluster/ubuntu/config-default.sh write:
# Optional: When set to true, heapster, Influxdb and Grafana will be setup as part of the cluster bring up.

ENABLE_CLUSTER_MONITORING="${KUBE_ENABLE_CLUSTER_MONITORING:-true}"
but no one of  heapster, Influxdb and Grafana bring up, why?

**Comment by lojies** [comment]
I can't find ENABLE_CLUSTER_MONITORING used anywhere.
This may not be  implemented yet.
