### ISSUE TITLE
How to use 3rd admission 

### ISSUE THREAD

**Issue by YingBurden** [kubernetes/kubernetes#28009]
@justinsb  I've created a admission control, but I did't know how to use it

**Comment by harryge00** [comment]
How do you run your api-server? Which authorization mode?

**Comment by YingBurden** [comment]
@harryge00 api-server  is a process ， I can find profiles in the “/etc/default/kube-apiserver”
http://kubernetes.io/docs/getting-started-guides/ubuntu/

**Comment by harryge00** [comment]
You should provide more information about your problem. Such as how you run your api-server.

**Comment by jlowdermilk** [comment]
Please post your question to  [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We use github issues to track bugs, feature requests, and proposals. Help/support questions will be responded to much faster on stackoverflow, and you may find someone else has already posted a similar question and found a solution. The Kubernetes team regularly scans stackoverflow and will try to ensure questions don't go unanswered. Thanks.
