### ISSUE TITLE
Add kubectl option to open UI

### ISSUE THREAD

**Issue by bryk** [kubernetes/kubernetes#28007]
kubectl should have an option to open the UI that is installed under `http://<master_ip>/ui`. 

For example: `kubectl open-ui`. 

This would great discoverability improvement for the UI since many people start with CLI, not even knowing that there is a UI.

Implementation considerations: This may either start a local proxy and open a browser or look for UI's service, get it's external endpoint and open a browser with it. 

CC @kubernetes/dashboard-maintainers

**Comment by harryge00** [comment]
how about https://github.com/kubernetes/dashboard?

**Comment by bryk** [comment]
@harryge00 the CLI proposed here would open the Dashboard UI if it is installed on your cluster.

**Comment by bharaththiruveedula** [comment]
I want to work on this issue, can anyone assign this to me?

**Comment by bryk** [comment]
@bharaththiruveedula I guess you can work on this without assigning the issue. Just claim it and provide your plan.

**Comment by pwittrock** [comment]
@bharaththiruveedula Are you still working on this?

**Comment by maciaszczykm** [comment]
@bharaththiruveedula Are you still working on this? If not I'm willing to take over.

**Comment by bryk** [comment]
I think that you can start work on this @maciaszczykm and collaborate with @bharaththiruveedula if they show up again.

**Comment by frankgreco** [comment]
@maciaszczykm any update on this

**Comment by maciaszczykm** [comment]
@frankgreco No, as far as I know this will not be done as it was described here, but in more generic way. Instead of adding option to open Dashboard community wants to improve discoverability of all services. You can check #32073 and #36819 to get more details as there were a few discussions about it. Also, if you have any specific questions just ask them :-)
