### ISSUE TITLE
Provide a version compatibility table for the documentation/website

### ISSUE THREAD

**Issue by dlsniper** [kubernetes/kubernetes#28016]
Hi,

I'm not sure if this is the best place to ask for this so please let me know if I should redirect it somewhere else.

I've found myself wanting to know which versions of flannel or etcd I should use with Kubernetes and I've realized that there's no easy way where this information can be found.
I would expect that in the readme of the version once tagged, on the website or in the documentation to have such a table but I'm not able to find it.

Thank you.

**Comment by luxas** [comment]
Please move this issue to https://github.com/kubernetes/kubernetes.github.io :)
cc @johndmulhausen

**Comment by dlsniper** [comment]
will do, thank you!
