### ISSUE TITLE
Mongo Pod Stuck ContainerCreating mode

### ISSUE THREAD

**Issue by codingwithoutcomments** [kubernetes/kubernetes#28022]
I had a MongoPod that was running but other pods could not longer connect to it, so I deleted the rc then tried to re-create it.  When I re-created it, it became stuck in ContainerCreating.

{kubelet gke-fb38c555-node-669g}    implicitly required container POD    Failed    Failed to start with docker id 121040c542ca with error: API error (500): Cannot start container 121040c542cab2f627a59edbd39a6cdf6650330bbb1831eece46b83042dd47a0: no available ip addresses on network

**Comment by girishkalele** [comment]
@codingwithoutcomments 

Looks like the 'no available ip addresses on network' might be a Docker issue.
Which Kubernetes version are you running ?
Can you check what is the CIDR assigned to this node ? Are there free Pod IPs available on that node ?

https://github.com/docker/docker/issues/14788

**Comment by xiangpengzhao** [comment]
Since there is no further echo from @codingwithoutcomments, we can't get enough info to debug, so we are closing this issue. Feel free to re-open it once you encounter this issue again. 

@thockin
