### ISSUE TITLE
kube-up.sh  on aws The dhcpOptions ID 'dopt-xxx' does not exist

### ISSUE THREAD

**Issue by scottstensland** [kubernetes/kubernetes#28045]
When attempting to use kubernetes on Amazon AWS is it advisible to launch cluster using /root/kubernetes/cluster/kube-up.sh  ?   My experience is it fails about every other attempt ... for example here is output

`/root/kubernetes/cluster/kube-up.sh
... Starting cluster in us-east-1c using provider aws
... calling verify-prereqs
... calling kube-up
Starting cluster using os distro: jessie
Uploading to Amazon S3
+++ Staging server tars to S3 Storage: medssenger-kubernetes-artifacts/devel
upload: ../tmp/kubernetes.P6Z5f6/s3/bootstrap-script to s3://medssenger-kubernetes-artifacts/devel/bootstrap-script
Uploaded server tars:
  SERVER_BINARY_TAR_URL: https://s3.amazonaws.com/medssenger-kubernetes-artifacts/devel/kubernetes-server-linux-amd64.tar.gz
  SALT_TAR_URL: https://s3.amazonaws.com/medssenger-kubernetes-artifacts/devel/kubernetes-salt.tar.gz
  BOOTSTRAP_SCRIPT_URL: https://s3.amazonaws.com/medssenger-kubernetes-artifacts/devel/bootstrap-script
INSTANCEPROFILE arn:aws:iam::092412661482:instance-profile/kubernetes-master    2016-06-08T00:13:20Z    AIPAI4A4UV44PW3HYJL7C   kubernetes-master   /
ROLES   arn:aws:iam::092412661482:role/kubernetes-master    2016-06-08T00:13:18Z    /   AROAJYBQ472Y5RXP2E4Z4   kubernetes-master
ASSUMEROLEPOLICYDOCUMENT    2012-10-17
STATEMENT   sts:AssumeRole  Allow
PRINCIPAL   ec2.amazonaws.com
INSTANCEPROFILE arn:aws:iam::092412661482:instance-profile/kubernetes-minion    2016-06-08T00:13:22Z    AIPAJ6G6M74BGD7ZCCSCS   kubernetes-minion   /
ROLES   arn:aws:iam::092412661482:role/kubernetes-minion    2016-06-08T00:13:21Z    /   AROAJ5DDT3FKFFVJ3L754   kubernetes-minion
ASSUMEROLEPOLICYDOCUMENT    2012-10-17
STATEMENT   sts:AssumeRole  Allow
PRINCIPAL   ec2.amazonaws.com
Using SSH key with (AWS) fingerprint: SHA256:UxLs3go/ZERrYnJawH0wsqi6C6gLE36vb5uCmmqbobg
Creating vpc.
Adding tag to vpc-627ccd05: Name=kubernetes-vpc
Adding tag to vpc-627ccd05: KubernetesCluster=kubernetes
Using VPC vpc-627ccd05
Adding tag to dopt-ee7eae8a: Name=kubernetes-dhcp-option-set

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist

An error occurred (InvalidDhcpOptionsID.NotFound) when calling the CreateTags operation: The dhcpOptions ID 'dopt-ee7eae8a' does not exist
Unable to add tag to AWS resource
`

Should I be using raw aws commands to launch the aws cluster onto which I will then deploy my app using kubernetes commands ?    Above error is only one of _MANY_  aws errors which occur using kube-up.sh from time to time which have questionable root causes

__ OR __ is it true that kubernetes on aws is half baked and not ready for production ?   My experience using Google Cloud ( gcloud ) as a kubernetes platform offers a much more stable infrastructure.

**Comment by NelsonBurton** [comment]
I just encountered this same issue - I found that after going onto AWS and deleting my existing VPC and re-running the script it worked.

**Comment by scottstensland** [comment]
when I get these AWS  timing related issues I insert lines like

    sleep 5

before / after offending AWS commands which properly should be driven by a Promise async call  .... and yes this issue continues even in the most alpha/beta release of kubernetes

SOLUTION - 

cd ~/kubernetes
grep -r 'Adding tag to' *

cluster/aws/util.sh:  echo "Adding tag to ${1}: ${2}=${3}"

so edit file   

vi cluster/aws/util.sh

... search for     "Adding tag to"

once you find the offending function call liberally add sleep calls 

    sleep 5

crude yet very effective to fix this chronic issue

**Comment by NelsonBurton** [comment]
Interesting, thanks for the insight.
