### ISSUE TITLE
ReplicationController hooks and events

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#2804]
Capturing internal email and in-person discussions.

The choice of which pod to kill when a replication controller replica count is decreased (or the replication controller otherwise detects that it somehow has too many pods) could become fairly nuanced, and even application-specific (e.g., don't kill the current master in a master-elected service). One way in which we could make the policy extensible is to generate an event that indicates pods need to be killed and then wait some amount of time. That would provide an opportunity for a user-provider pod killer to make the choice.

That's not to say that we shouldn't make the default choice more intelligent over time (e.g., taking into account application readiness), but the default policy will never satisfy everyone.

Events when pods are actually killed and created would be useful, too.

**Comment by kargakis** [comment]
We have events on pod creation/deletion. I am not sure we want to make pod deletion even more nuanced for replica sets now that we have stateful sets.

cc: @kubernetes/sig-apps-misc

**Comment by kargakis** [comment]
The controllers are emitting events when pods are created/deleted. Re hooks, I think this is going to be satisfied by evictionCost (https://github.com/kubernetes/kubernetes/issues/4301)

**Comment by bgrant0607** [comment]
Obsolete
