### ISSUE TITLE
federation broke kube dns (skydns) install scripting

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#28073]
PR #28040 fixed one instance of this problem, but it looks to me like there are many more.  The following files look broken to me: cluster/gce/gci/configure-helper.sh, cluster/gce/trusty/configure-helper.sh, cluster/images/hyperkube/Makefile, cluster/mesos/docker/deploy-dns.sh, and hack/local-up-cluster.sh.  Some other files might also be broken too.

**Comment by MikeSpreitzer** [comment]
CC @quinton-hoole 
CC @madhusudancs 
CC @girishkalele

**Comment by MikeSpreitzer** [comment]
It looks like #28087 is taking care of cluster/images/hyperkube/Makefile

**Comment by nikhiljindal** [comment]
Thanks for filing this @MikeSpreitzer.

@madhusudancs Can you fix the other instances?

Marking this P1 since we will need to cherrypick the fixes in 1.3.

**Comment by madhusudancs** [comment]
#28132 undoes quite a bit of what #27986 introduced and moves the parameter substitution to node bootstrap scripts. Changes in #28040 are still valid but #28132 fixes this issue for other provider/node image combinations.

**Comment by madhusudancs** [comment]
This can be considered fixed now. As far as I know this should be fixed in all the cloud provider scripts. So I am closing this issue.

Please feel free to reopen the issue if you this happening.
