### ISSUE TITLE
petset redis example giving error on 1.4.0-alpha.0

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes#28078]
The events show the following errors:-

36m       36m       1         rd        PetSet                             Normal    SuccessfulCreate   {petset }                                pet: rd-0
36m       36m       1         rd        PetSet                             Warning   FailedCreate       {petset }                                pvc: datadir-rd-1, error: persistentvolumeclaims "datadir-rd-1" not found
36m       36m       1         rd        PetSet                             Warning   FailedCreate       {petset }                                pvc: datadir-rd-2, error: persistentvolumeclaims "datadir-rd-2" not found

the pods are in crash loop
kubectl.sh get pods
NAME      READY     STATUS             RESTARTS   AGE
rd-0      0/1       CrashLoopBackOff   12         40m

kubectl.sh get petsets
NAME      DESIRED   CURRENT   AGE
rd        3         3         41m

version
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.0-dirty", GitCommit:"fd1377a16b5e2e33f24a57848071616c81a7f58f", GitTreeState:"dirty", BuildDate:"2016-06-20T09:19:08Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.0-dirty", GitCommit:"fd1377a16b5e2e33f24a57848071616c81a7f58f", GitTreeState:"dirty", BuildDate:"2016-06-20T09:06:11Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

describe petsets rd shows the following error:-

:           rd
Namespace:      default
Image(s):       debian:jessie
Selector:       app=redis
Labels:         app=redis
Replicas:       3 current / 3 desired
Annotations:        <none>
CreationTimestamp:  Sat, 25 Jun 2016 23:31:34 -0700
Pods Status:        1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Volumes:
  opt:
    Type:   EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium: 
  workdir:
    Type:   EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium: 
Events:
  FirstSeen LastSeen    Count   From        SubobjectPath   Type        Reason          Message

---

  42m       42m     1   {petset }           Warning     FailedCreate        pvc: datadir-rd-0, error: persistentvolumeclaims "datadir-rd-0" not found
  42m       42m     1   {petset }           Normal      SuccessfulCreate    pet: rd-0
  42m       42m     1   {petset }           Warning     FailedCreate        pvc: datadir-rd-1, error: persistentvolumeclaims "datadir-rd-1" not found
  42m       42m     1   {petset }           Warning     FailedCreate        pvc: datadir-rd-2, error: persistentvolumeclaims "datadir-rd-2" not found

**Comment by krmayankk** [comment]
Followed the following exmaple https://github.com/kubernetes/contrib/tree/master/pets/redis

**Comment by girishkalele** [comment]
@bprashanth

**Comment by krmayankk** [comment]
@bprashanth thanks will give it a try and update by tomorrow. BTW the error i saw was on GCE. Also just an FYI the zookeeper example in the contrib repo worked though

**Comment by bprashanth** [comment]
Yeah there's a chance the base image might be broken. The redis i pointed you at is running in an e2e rigth now so i know that image is working, the one in contrib uses a smaller base (which is overall desirable) but I haven't got a chance to test it yet

**Comment by bprashanth** [comment]
@krmayankk did it work?

**Comment by krmayankk** [comment]
@bprashanth yes the e2e one did work. In petsets, is it guaranteed that the pods belonging to the petset will always get the same ip when they are deleted and automatically re-created so that the endpoints in the service will be always the same

**Comment by bprashanth** [comment]
no ip is not guaranteed. only DNS and hostname. See: https://github.com/kubernetes/kubernetes.github.io/blob/release-1.3/docs/user-guide/petset.md

**Comment by krmayankk** [comment]
@bprashanth the examples in the link you mentioned doesn not have the pointers to petset.yaml. where can i find it ?

**Comment by krmayankk** [comment]
@bprashanth another few issues i see are -
- why cant the creation of petset automatically create the service
- there should be an option to create the petset without the associated pvc

**Comment by bprashanth** [comment]
> Also would like to know if you have a redis example with master,slave and sentinels all packets together like the one in contrib which is without a petset

Please contribute such an example. When I thought of doing it I wanted to put the sentinel as a container in each redis pod.

External identities to pets is on the agenda, but no definite timeline has been discussed.

> why cant the creation of petset automatically create the service

We don't create the service for any workload collection (replica set, deployment etc). If we did the user would be stuck with one set of defaults.  

> there should be an option to create the petset without the associated pvc

This is already possible.

**Comment by kargakis** [comment]
Please move to the k8s/examples repo if still relevant.
