### ISSUE TITLE
A space is appended to the value of secrets stored as environment variables

### ISSUE THREAD

**Issue by brenarth** [kubernetes/kubernetes#28086]
When a secret is made available as an environment variable inside a container, a space is appended to the secret's value. A secret stored as `"secretuser"` becomes `"secretuser "` (note the trailing space)

This can be easily reproduced using busybox:

secret.yml:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: c2VjcmV0dXNlcgo=
```

pod.yml. Note the pod is configured to output the value of `${SECRET_USERNAME}` bounded by equals characters
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: testsecret
spec:
  containers:
    - name: test
      command: ["/bin/sh", "-c"]
      args: ["echo =${SECRET_USERNAME}="]
      image: busybox
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
  restartPolicy: Never
```

Problem being reproduced.
```
[brenarth@testclient busybox]# kubectl apply -f ./mysecret.yml
secret "mysecret" created
[brenarth@testclient busybox]# kubectl get secret mysecret -o yaml
apiVersion: v1
data:
  username: c2VjcmV0dXNlcgo=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Secret","apiVersion":"v1","metadata":{"name":"mysecret","creationTimestamp":null},"data":{"username":"c2VjcmV0dXNlcgo="},"type":"Opaque"}'
  creationTimestamp: 2016-06-26T17:26:28Z
  name: mysecret
  namespace: default
  resourceVersion: "1249620"
  selfLink: /api/v1/namespaces/default/secrets/mysecret
  uid: 1d7fd00b-3bc3-11e6-a40b-06d4bf322c97
type: Opaque
[brenarth@testclient busybox]# kubectl apply -f ./pod.yml
pod "testsecret" created
[brenarth@testclient busybox]# kubectl logs  testsecret
=secretuser =
```

Note, the base64 encoded data does not contain a trailing space, but the value output from the container does
```
[brenarth@testclient busybox]# echo =$(echo c2VjcmV0dXNlcgo= | base64 -d)=
=secretuser=
```

This issue does not occur when using keys from a config map. 

I'm running Kubernetes 1.2.4

**Comment by mark-adams** [comment]
Is it possible that the trailing newline in the base64-encoded secret could be causing the problem?

**Comment by brenarth** [comment]
Sure enough, encoding the secret using `echo -n | base64` gets things working correctly. Should have read the documentation more thoroughly... This is specifically called out here: http://kubernetes.io/docs/user-guide/secrets/#creating-a-secret-using-kubectl-create-secret

> Encoding Note: The serialized JSON and YAML values of secret data are encoded as base64 strings. Newlines are not valid within these strings and must be omitted.
