### ISSUE TITLE
Update commented-out taint/toleration code to replace NoScheduleNoAdmitNoExecute with NoExecute

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#28082]
We can represent NoScheduleNoAdmitNoExecute with two separate taints, one NoScheduleNoAdmit and one NoExecute. Having a NoScheduleNoAdmitNoExecute taint effect is only beneficial if there are use cases where you could use one taint with the NoScheduleNoAdmitNoExecute effect instead of two taints (one NoScheduleNoAdmit and one NoExecute). But it seems such use cases do not exist. At least the most common use case, representing "bad machine," requires two taints, so that a pod can choose any of 
- don't schedule me there and evict me if I'm already running there
- don't schedule me there but leave me bound if I'm already running there
- schedule me there and leave me bound if I'm already running there

A single taint isn't sufficient because you can't get three separate behaviors with just a single taint.

Since we need two separate taints for this common use case anyway, it makes more sense for those taints to be called NoScheduleNoAdmit and NoExecute, rather than NoScheduleNoAdmit and NoScheduleNoAdmitNoExecute.

So, we should rename NoScheduleNoAdmitNoExecute to NoExecute.

**Comment by davidopp** [comment]
Also, when we do this we can add validation the ensures forgiveness is only used with a toleration with effect NoExecute.

**Comment by ConnorDoyle** [comment]
What's the status of this feature? Is any help needed to get this across the finish line for the 1.4 target?

**Comment by kevin-wangzefeng** [comment]
It is included in #30191 since forgiveness depends on it.

**Comment by davidopp** [comment]
@ConnorDoyle can you say more about what functionality you are looking for?

The "evict pod when taint is not tolerated" behavior will definitely not be in 1.4 (except for a very special case that's handled in #30191). I'm hoping #30191 will get into 1.4 but there is still some work needed on that PR.

**Comment by balajismaniam** [comment]
@davidopp we are looking for the "evict pod when taint is not tolerated" functionality. Thanks for pointing us to the PR.

**Comment by goltermann** [comment]
@davidopp #30191 isn't set for v1.4 - should it be, or should this issue be punted to 1.5?

**Comment by goltermann** [comment]
Moving out of v1.4 as this is a P2.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @davidopp @kevin-wangzefeng

**Comment by aveshagarwal** [comment]
I think this is already being addressed in https://github.com/kubernetes/kubernetes/pull/34825 since https://github.com/kubernetes/kubernetes/pull/34825 is not going to make 1.5 that means this is not going to be addressed in 1.5.

**Comment by dims** [comment]
@aveshagarwal ack. moving this to 1.6

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by kevin-wangzefeng** [comment]
addressed in #39469, closing.

**Comment by davidopp** [comment]
The funny/sad part is that in the end, we used the name NoExecute but the behavior is NoScheduleNoAdmitNoExecute. :-/
