### ISSUE TITLE
[Question] Delete resource and its associated resources with Rest API

### ISSUE THREAD

**Issue by Kapaski** [kubernetes/kubernetes#28098]
Hello Guys,

I'm running v1.2.2 k8s in a cluster, and currently I have a requirement that is using the rest API from k8s API server, to delete a k8s job resource once it is successfully done. I've noticed with `kubectl`, the pod this job created was also deleted, but with rest API, this seems not doing the same, ie. I can delete the job through v1.DeleteOptions API but the Pod will not be deleted with the job.

Could anyone point me a recommended approach of doing this properly? Thanks in advance!

My sample delete request is as below (Using the perl Pi example job resource from document):

`curl -X DELETE -H "Content-Type: application/json" -H "Authorization: Basic mytoken"  -d '{
  "apiVersion": "v1",
  "kind": "DeleteOptions",
  "gracePeriodSeconds": 0
}' "https://localhost/apis/batch/v1/namespaces/dev/pods/pi"`

it deletes a completed job named `pi` but left the Pod that pi was using in completed state

Regards

James

**Comment by jlowdermilk** [comment]
Reaping of owned resources should probably be moved to the server, but it's done client side right now. If you want to delete managed pods via the api, you'll have to get them using the selector. See https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/stop.go for how this is done for each collection type.

**Comment by Kapaski** [comment]
Thanks for help @jlowdermilk , happy to close this issue.
