### ISSUE TITLE
How to get the version of kubernetes? 

### ISSUE THREAD

**Issue by jianzhangbjz** [kubernetes/kubernetes#28099]
I git clone it, and compile them. And exec "kubectl version", results below:
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.4.9404+6b9400d7899eee", GitCommit:"6b9400d7899eeeddae81f93bdb33ccebb3293971", GitTreeState:"clean", BuildDate:"2016-06-22T03:14:13Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean", BuildDate:"", GoVersion:"", Compiler:"", Platform:""}
**But, what's the version of k8s?  1.2.2?**

**Comment by klaus** [comment]
You have the client (kubectl) and the server (usually running on port :8080).
Yes, as you can see from Your Post You are running '1.2.0' kubectl (client) against 1.2.2 (server)

**Comment by jianzhangbjz** [comment]
@klaus Thanks a lot! I'm clear now.
