### ISSUE TITLE
After upgrading docker version from 10 to 11 'cAdvisor' not reporting metrics on 'Pods'  

### ISSUE THREAD

**Issue by shayderi** [kubernetes/kubernetes#28103]
Hi
We currently solved the problem by returning back to docker version 10 (1.10)

Any help on the issue will be appreciated

Thanks

**Comment by aveshagarwal** [comment]
@kubernetes/rh-cluster-infra

**Comment by derekwaynecarr** [comment]
More information is needed:

1. is this docker installed from your distro or from docker?
1. can you paste the output of `docker info`
1. what cgroup driver is used for docker?

**Comment by aveshagarwal** [comment]
@shayderi Yeah it would be good to provide more info about your setup as @derekwaynecarr said.

I tested this on fedora 24 by upgrading to docker 1.11 from 1.10. I created a simple pod, and then `curl http://127.0.0.1:10255/stats/summary`  or `curl http://127.0.0.1:10255/stats/<pod>/<container>` .
And it worked correctly.

**Comment by shayderi** [comment]
Hi,
more details:
1. docker installed from docker
2. docker info:
 - Execution-driver : native-0.2
 - Operatins system : Ubuntu 14.04.2 LTS
 - Kernel version : 3.16.0-30 generic
3. I think we use the default cgroup driver (we didn't change)
4. Kubernetes version : release 1.1.7

Thanks.

**Comment by dchen1107** [comment]
@shayderi based on the information you provided, you are running kubernetes 1.1.7 release. We introduced stats/summary API in 1.2 release, which includes pod related metrics. Before 1.2, only container level metrics are exported, but you can "reverse engineer" pod metrics through labels and container metrics. I think your issue has nothing to do docker.
