### ISSUE TITLE
Proportional scaling down cannot get expected result in unpause. Also, Proportional scaling down can get expected result in pause but cannot keep after resume.

### ISSUE THREAD

**Issue by chengzhang1016** [kubernetes/kubernetes#28105]
Description of problem:
kubernetes/deployment: Proportional scaling down cannot get expected result in unpause. Also, Proportional scaling down can get expected result in pause but cannot keep after resume.

Version-Release number of selected component:
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.0.890+ecfd4aa131035a", GitCommit:"ecfd4aa131035a4747cfdf90d89a2fe823341657", GitTreeState:"clean", BuildDate:"2016-06-27T08:34:32Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.0.890+ecfd4aa131035a", GitCommit:"ecfd4aa131035a4747cfdf90d89a2fe823341657", GitTreeState:"clean", BuildDate:"2016-06-27T08:34:32Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

# docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-24.gitf476348.fc23.x86_64
 Go version:      go1.5.4
 Git commit:      f476348/1.10.3
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-24.gitf476348.fc23.x86_64
 Go version:      go1.5.4
 Git commit:      f476348/1.10.3
 Built:           
 OS/Arch:         linux/amd64

# etcd --version
etcd Version: 2.3.3
Git SHA: c41345d
Go Version: go1.6.2
Go OS/Arch: linux/amd64

# cat /etc/system-release
Fedora release 23 (Twenty Three)
```

How reproducible:
Always

[Problem 1]: Proportional scaling down cannot get expected result in unpause.
Steps to Reproduce:
Step 1. Generate a deployment with two RSs, as below:
Deployment.replicas=40
maxSurge=3
maxUnavailabl=2
```
# kubectl get rs
NAME                         DESIRED   CURRENT   AGE
nginx-deployment-508933516   38        38        1m
nginx-deployment-520009149   5         5         7s
```
Step 2. Scale down deployment to 30
```
# kubectl scale --replicas=30 deployment/nginx-deployment
deployment "nginx-deployment" scaled
```
Step 3. Check scaled result via: `kubectl get rs`

Actual results:
Step 3. Check scaled result
```
# kubectl get rs
NAME                         DESIRED   CURRENT   AGE
nginx-deployment-508933516   28        28        1m
nginx-deployment-520009149   5         5         25s
```

Expected results: Proportional scaling down should work and scale result same with in pause.
Step 3. Check scaled result
```
# kubectl get rs
NAME                         DESIRED   CURRENT   AGE
nginx-deployment-508933516   29        29        1m
nginx-deployment-520009149   4         4         25s
```

[Problem 2]: Proportional scaling down can get expected result in pause but cannot keep after resume.
Steps to Reproduce:
Step 1. Generate a deployment with two RSs, as below:
Deployment.replicas=40
maxSurge=3
maxUnavailabl=2
```
# kubectl get rs
NAME                         DESIRED   CURRENT   AGE
nginx-deployment-508933516   38        38        21s
nginx-deployment-520009149   5         5         3s
```
Step 2. Pause deployment
```
# kubectl rollout pause deployment nginx-deployment
deployment "nginx-deployment" paused
```
Step 3. Scale down deployment to 30
```
# kubectl scale --replicas=30 deployment/nginx-deployment
deployment "nginx-deployment" scaled
```
Step 4. Check scaled result
```
# kubectl get rs
NAME                         DESIRED   CURRENT   AGE
nginx-deployment-508933516   29        29        53s
nginx-deployment-520009149   4         4         35s
```
Step 5. Resume deployment
```
# kc rollout resume deployment nginx-deployment
deployment "nginx-deployment" resumed
```
Step 6. Check rs again via `kubectl get rs`

Actual results:
Step 6. Check rs again
```
# kubectl get rs
NAME                         DESIRED   CURRENT   AGE
nginx-deployment-508933516   28        28        18m
nginx-deployment-520009149   5         5         18m
```

Expected results: The scaling result shouldn't be changed.
Step 6. Check rs again
```
# kubectl get rs
NAME                         DESIRED   CURRENT   AGE
nginx-deployment-508933516   29        29        18m
nginx-deployment-520009149   4         4         18m
```

Additional info:
1. Didn't find similar problem in Proportional scaling up.

**Comment by kargakis** [comment]
Can you post the command for starting the second replica set? If the rollout is healthy (ie. you roll out to something that is working) then this is expected because the deployment is ongoing.

cc: @kubernetes/deployment

**Comment by chengzhang1016** [comment]
@kargakis 
Generate a deployment with two RSs:
Step1: Create deployment with below yaml file:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 40
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.1
        ports:
        - containerPort: 80
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
    type: RollingUpdate
```
Step2: Edit deployment, and change image from `nginx:1.7.1` to nginx:abc`
```
# kubectl get rs
NAME                         DESIRED   CURRENT   AGE
nginx-deployment-508933516   38        38        21s
nginx-deployment-520009149   5         5         3s
```

**Comment by kargakis** [comment]
Looked at this closer today. In both cases, proportional scaling is working as expected. The difference you see when the deployment is unpaused - (28, 5) instead of (29, 4) - is due to the fact that during the rollout the deployment will scale down to the minimum available that it needs to maintain. 

Here is what happens:

Step.1:
d.spec.replicas=40, maxSurge=3, maxUnavailable=2
rs1.spec.replicas=38 (minimum availability is maintained)
rs2.spec.replicas=5

Step.2:
$ kc scale deploy/foo --replicas 30
If the deployment is paused:
rs1.spec.replicas=29
rs2.spec.replicas=4

If the deployment is resumed:
rs1.spec.replicas=28 (minimum availability is maintained)
rs2.spec.replicas=5

As an experiment you can run the following flow and verify this:
Step.1 is the same
kc rollout pause deploy/foo
kc scale deploy/foo --replicas 30
(notice proportional scaling ie. (29, 4))
kc rollout resume deploy/foo
(notice the rollout pushing the deployment to minimum availability ie. (28, 5))

**Comment by chengzhang1016** [comment]
OK. I will double confirm. Thx.

**Comment by chengzhang1016** [comment]
@kargakis 
Hi Kargakis,
Thanks for your response. Could you give me the answer for below questions:
What is the minimum? Is it (maxSurge + maxUnavailable)?
Why we need minimum to limit replicas of rs?

**Comment by kargakis** [comment]
> What is the minimum? Is it (maxSurge + maxUnavailable)?

The minimum of what?

>  Why we need minimum to limit replicas of rs?

The deployment needs to maintain minimum availability (d.spec.replicas - maxUnavailable) at all times.
