### ISSUE TITLE
kubectl replace: --force options is broken be design

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/kubernetes#28115]
When replacing an existing pod, the ``kubectl replace --force`` command fails as it tries to create a pod with a name that is still used by terminating pod.

How does the ``--force`` option works?

1. ``kubectl replace`` deletes a pod (e.g. mypod)
1. ``kubectl replace`` creates a new pod with the same name (mypod)

What happens? As the command tries to recreate the pod, it fails as the ``mypod`` is in ``Terminating`` state. Thus it can not be created.

The problem is the ``kubectl replace`` does not wait for a pod to be deleted.

**Reproducer**:

1. kubectl run mypod --image=yapei/hello-openshift  --generator=run-pod/v1
1. kubectl get pod mypod -o yaml > mypod.json
1. kubectl replace -f  mypod.json --force

The last command ends with:

```
pod "mypod" deleted
Error from server: pods "mypod" already exists
```

**Comment by ingvagabund** [comment]
``--force`` option introduce by https://github.com/kubernetes/kubernetes/pull/10358

**Comment by ingvagabund** [comment]
With ``--grace-period`` set to positive value, what should be the default behaviour of the command? When set to ``100s``, should the command hang for ``100s`` and then create the pod? Or is there a way to create a callback (inside a scheduler?) that creates the pod once the current one is deleted?

**Comment by ncdc** [comment]
You could watch for the resource to be deleted and create after you see the deletion happen

**Comment by AdoHe** [comment]
@ingvagabund have you ever tried to set `--grace-period=0`, I think this will do a non graceful deletion. `--force` should make sure the old resource is deleted before it creates a new resource, if not, that's a bug. @kubernetes/kubectl

**Comment by ingvagabund** [comment]
@AdoHe 

```
$ kubectl replace -f mypod.json --force --grace-period=0
pod "mypod" deleted
Error from server: pods "mypod" already exists
```

**Comment by ingvagabund** [comment]
```
kubectl replace -f mypod.json --grace-period=0
Error from server: error when replacing "mypod.json": Operation cannot be fulfilled on pods "mypod": StorageError: resource version conflicts, Code: 3, Key: /registry/pods/default/mypod, ResourceVersion: 0, AdditionalErrorMsg:
```

Though the help says the ``--grace-period`` is to be used only with ``--force``, it returns the error above.

**Comment by AdoHe** [comment]
Then I think there are two issues we need to track: 1. `--grace-period` option should be ignored or just returns error if users are not using `--force` option. 2. `kubectl replace --force` should always make sure the old resource has been deleted before create the new resource.
