### ISSUE TITLE
IAM_PROFILE hardcoded

### ISSUE THREAD

**Issue by agutierrezl** [kubernetes/kubernetes#28113]
Hi,

You have hardcoded the IAM_PROFILE for nodes and master. From config-default.sh:

`IAM_PROFILE_MASTER="kubernetes-master"`
`IAM_PROFILE_NODE="kubernetes-minion"
`

It would be nice if you let this as custom variables. It will let you have multiples clusters running with different IAM permission.

**Comment by agutierrezl** [comment]
Something like this will be enougth:

`IAM_PROFILE_MASTER=${IAM_PROFILE_MASTER:-kubernetes-master}`
`IAM_PROFILE_NODE=${IAM_PROFILE_NODE:-kubernetes-minion}`

Regards

**Comment by xiangpengzhao** [comment]
@justinsb any thoughts?

**Comment by justinsb** [comment]
As kube-up is generally deprecated, and we've removed the AWS kube-up code, I'm going to close the issue.

I personally recommend using kops for AWS installations.
