### ISSUE TITLE
rktnetes testing: e2e artifacts should include kernel logs, and rkt api-service logs

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#28125]
Today the rktnetes jenkins job only grabs/uploads kubelet logs [example](https://console.cloud.google.com/storage/browser/rktnetes-jenkins/logs/kubernetes-e2e-gce/3351/artifacts/jenkins-e2e-minion-group-5n6v/)

We need to fix this and enables the testing infra to get logs from journal logs instead of copying files.

cc @kubernetes/sig-rktnetes @kubernetes/sig-testing

**Comment by ixdy** [comment]
https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump.sh is the script to update.

We already use `journalctl` for some logs.

**Comment by yifan-gu** [comment]
@ixdy Thanks for the reference :)
I assign this to @euank who is working on setting up pr testers for rktnetes. We can probably address the issue at the same time.

**Comment by euank** [comment]
No longer relevant with the deprecation of rktnetes in favor of [rktlet](https://github.com/kubernetes-incubator/rktlet/)

/close
