### ISSUE TITLE
I get an error while executing kubectl exec command. I get the following error:-  Error from server: Upgrade request required

### ISSUE THREAD

**Issue by dharmisha** [kubernetes/kubernetes#28123]
Please provide me a solution to this issue

**Comment by jlowdermilk** [comment]
Please post your question to  [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We use github issues to track bugs, feature requests, and proposals. Help/support questions will be responded to much faster on stackoverflow, and you may find someone else has already posted a similar question and found a solution. The Kubernetes team regularly scans stackoverflow and will try to ensure questions don't go unanswered. Thanks.
