### ISSUE TITLE
Idea Vetting: Event storage as an introspective service.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#28130]
The basic premise is if there is an event_storage service, which is essentially a apiserver+etcd pod, that any requests made to /events would be proxied to that introspective service and not hit the main api-servers.  

/cc @kubernetes/sig-scalability @rrati

**Comment by davidopp** [comment]
As you know we currently store events in a separate etcd in large clusters; is there evidence that API server is the bottleneck?

In any event (pun fully intended), there has been previous discussion in #4432 and #19637. Could we dupe this issue with #19637 to avoid proliferation of issues?

**Comment by timothysc** [comment]
This is essentially the easiest way I can think of to address #19637, without having to do a bunch of refactoring.

**Comment by davidopp** [comment]
So maybe add this to #19637, or even re-title that one and add your comment to it, rather than creating a new issue? I hate to nitpick individual issues but we have a huge problem we too many open issues.

**Comment by timothysc** [comment]
k, I'll close and add on there.
