### ISSUE TITLE
federation service controller has trouble deciding when there is no delta

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#28135]
E.g.,

```
I0627 22:26:46.221856       1 dns.go:215] Existing recordset                <(clouddns) "federated-service.e2e-tests-service-cuza5.federation.svc.us-central1-c.us-central1.kube.5yetis.net." type=CNAME rrdatas=["federated-service.e2e-tests-service-cuza5.federation.svc.us-central1.kube.5yetis.net."] ttl=180>
I0627 22:26:46.221885       1 dns.go:216] ... not equal to needed recordset <(clouddns) "federated-service.e2e-tests-service-cuza5.federation.svc.us-central1-c.us-central1.kube.5yetis.net." type=CNAME rrdatas=["federated-service.e2e-tests-service-cuza5.federation.svc.us-central1.kube.5yetis.net."] ttl=180>
I0627 22:26:46.221919       1 dns.go:217] ... removing existing and adding needed.
```

See also #28134

**Comment by mml** [comment]
@kubernetes/sig-cluster-federation

**Comment by quinton-hoole** [comment]
Yes, I actually anticipated that problem.  There is a fairly simple fix.  This should not present a significant issue in the real world, but worth fixing.

https://github.com/kubernetes/kubernetes/blob/master/federation/pkg/federation-controller/service/dns.go#L208

**Comment by quinton-hoole** [comment]
@mml This is simply because these are two different instances of ResourceRecordSet being compared, each with different internal field values, but identical external field values. I will replace the == with an equivalent() function, which only compares external fields.

**Comment by goltermann** [comment]
@mml @quinton-hoole we're probably building 1.3.0 today, so this one's likely out unless it's on a cherrypick list in an hour.
