### ISSUE TITLE
error log "cannot be updated: the object has been modified; please apply your changes to the latest version and try again" both in node and deployment

### ISSUE THREAD

**Issue by workhardcc** [kubernetes/kubernetes#28149]
kube version:1.22
There are a lot of error log in kube-controller-manager.WARNING as below:

> E0628 15:47:49.898898   10978 nodecontroller.go:771] Error updating node 10.93.79.50: nodes "10.93.79.50" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
> E0628 15:47:59.927051   10978 nodecontroller.go:771] Error updating node 10.93.79.50: nodes "10.93.79.50" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
> E0628 15:48:09.972900   10978 nodecontroller.go:771] Error updating node 10.93.79.50: nodes "10.93.79.50" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
> E0628 15:48:20.008572   10978 event.go:193] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"10.93.79.50.145a4d8d2c888188", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"1030566", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Node", Namespace:"", Name:"10.93.79.50", UID:"10.93.79.50", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeNotReady", Message:"Node 10.93.79.50 status is now: NodeNotReady", Source:api.EventSource{Component:"controllermanager", Host:""}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63602166697, nsec:0, loc:(*time.Location)(0x26850e0)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63602696900, nsec:6208258, loc:(*time.Location)(0x26850e0)}}, Count:1023, Type:"Normal"}': 'events "10.93.79.50.145a4d8d2c888188" not found' (will not retry!)
> E0628 15:48:20.068310   10978 deployment_controller.go:395] Error syncing deployment default/deployment-1: deployments.extensions "deployment-1" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
> E0628 15:48:30.092182   10978 deployment_controller.go:395] Error syncing deployment default/deployment-port-2: deployments.extensions "deployment-port-2" cannot be updated: the object has been modified; please apply your changes to the latest version and try again

On my watch node and deployment are both ok. Those error occur at regular intervals（a few minutes）, every node or deployment may encounter this problem. 
Means that my kube-controller-manager has a bad network？ Or there are too many service in my cluster,kube-controller-manage can not afford it ?

**Comment by jlowdermilk** [comment]
I believe that is a benign error. Kubernetes objects have a resource version that is unique for each update. If an update comes in that has an out of date resource version, it is rejected to prevent racing updates clobbering each other. We should have this documented somewhere, but it is implementation detail.

**Comment by workhardcc** [comment]
Thanks for relay!
I know there is a resource version such as ` "resourceVersion": "1837492"` when minion's kubelet GET from MASTER apiserver. Then kubelet use this resourceVersion upload self-health status to kube master.
So it means that the resourceVersion which minion's kubelet  want upload is mismatch the resourceVersion in kube master?
 If yes, why those mismatch happened? If mismatch happened means we need upload the minion's status by manual? And how ?

**Comment by jlowdermilk** [comment]
In most cases the upload is retried automatically. Like I said, the error is benign. You can ignore this message.

**Comment by workhardcc** [comment]
Thanks! I understand!
By the way, when I create more then 1000+ svc, there are a lots of warning log in kube-controller-manager.WARNING. Is that benign too?

> W0622 10:51:26.861932    6130 request.go:627] Throttling request took 79.805269ms, request: GET:http://127.0.0.1:8080/api/v1/namespaces/default/endpoints/deployment-std31533
> W0622 10:51:26.911923    6130 request.go:627] Throttling request took 129.406603ms, request: GET:http://127.0.0.1:8080/api/v1/namespaces/default/endpoints/deployment-std31861
> W0622 10:51:26.961920    6130 request.go:627] Throttling request took 179.255616ms, request: GET:http://127.0.0.1:8080/api/v1/namespaces/default/endpoints/deployment-std30401
> W0622 10:51:27.011917    6130 request.go:627] Throttling request took 228.964115ms, request: GET:http://127.0.0.1:8080/api/v1/namespaces/default/endpoints/deployment-std30439
> W0622 10:51:27.061919    6130 request.go:627] Throttling request took 248.426579ms, request: GET:http://127.0.0.1:8080/api/v1/namespaces/default/endpoints/deployment-std30587
> W0622 10:51:27.111940    6130 request.go:627] Throttling request took 248.559482ms, request: GET:http://127.0.0.1:8080/api/v1/namespaces/default/endpoints/deployment-std30855
> W0622 10:51:27.161935    6130 request.go:627] Throttling request took 248.290755ms, request: GET:http://127.0.0.1:8080/api/v1/namespaces/default/endpoints/deployment-std31343
> W0622 10:51:27.211927    6130 request.go:627] Throttling request took 248.774837ms, request: GET:http://127.0.0.1:8080/api/v1/namespaces/default/endpoints/deployment-std32301
> W0622 10:51:27.261920    6130 request.go:627] Throttling request took 248.442571ms, request: GET:http://127.0.0.1:8080/api/v1/namespaces/default/endpoints/deployment-std30265
> W0622 10:51:27.311925    6130 request.go:627] Throttling request took 248.462302ms, request: GET:http://127.0.0.1:8080/api/v1/namespaces/default/endpoints/deployment-std30399
> W0622 10:51:27.361942    6130 request.go:627] Throttling request took 248.728021ms, request: GET:http://127.0.0.1:8080/api/v1/namespaces/default/endpoints/deployment-std32305

**Comment by jlowdermilk** [comment]
That warning should be self-explanatory. Apiserver is getting too many requests so it is ratelimiting them. 

Closing the issue since neither of these are actionable. For future reference, we recommend people post support/help questions on [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). We use github issues primarily for bug and feature tracking. Support questions typically get faster responses on stackoverflow, and you may find someone else has already posted a similar question and found a solution.

**Comment by NicholusMuwonge** [comment]
https://config9.com/apps/kubernetes/the-object-has-been-modified-please-apply-your-changes-to-the-latest-version-and-try-again/

**Comment by antonblock** [comment]
> https://config9.com/apps/kubernetes/the-object-has-been-modified-please-apply-your-changes-to-the-latest-version-and-try-again/

Heads up to future people, that site just redirects to spam/malware sites. Found someone else with the same experience on Reddit

https://www.reddit.com/r/sysadmin/comments/erkb9q/config9com_hosting_racoon_malware/
https://www.joesandbox.com/analysis/202225/0/html

**Comment by espears1** [comment]
@j3ffml Unfortunately in some scenarios it's not easy to ignore this error. For example, if you use kubernetes through the Python client, this error will create an ApiException and halt code execution. You can't always guarantee that this 409 "object has been modified" error will leave your kubernetes environment in the correct state (eg with retries or cleanups), so you can't simple catch that exception and check for this error message and ignore it.

What do you recommend users to do in a situation like that, eg when they need to make a change that will prevent the 409 error from occurring, instead of treating it like an ignorable error?

**Comment by theAkito** [comment]
> What do you recommend users to do in a situation like that, eg when they need to make a change that will prevent the 409 error from occurring, instead of treating it like an ignorable error?

I'm very curious about the solution to that question, as well.

Additionally, I don't see the good design in an error that simply has to be "ignored". If it can be ignored, it shouldn't be an error in the first place. Perhaps a warning, at best.

**Comment by llorllale** [comment]
> I believe that is a benign error

It's certainly suspicious.

For instance, right now I'm creating a NodePort service. For some reason the external-ip is _not_ being set to `<nodes>`. The only lead I have so far is this error in the service's event log. Recreating the nodeport results in the same event log and `<none>` external-ip.

So, even if it isn't related at all, it is creating noise while I troubleshoot this.

**Comment by chinglinwen** [comment]
In case someone want to ignore such error in operator controller. I found the following way to ignore it and do manual retry.

```go
package genericregistry ("k8s.io/apiserver/pkg/registry/generic/registry")

if strings.Contains(err.Error(), genericregistry.OptimisticLockErrorMsg) {
   // do manaul retry without error
   return reconcile.Result{RequeueAfter: time.Second * 1}, nil
}
```

**Comment by djnotes** [comment]
Apparently  this happens when applying yaml files generated from `kubectl get deployment deployment-name --output=yaml`, because  the said output contains resourceVersion, which will probably be unsuitable for next updates. So, such lines should be deleted from the generated files.
