### ISSUE TITLE
About redis from the main issue, I can not connect master service ip connection pod slave

### ISSUE THREAD

**Issue by hhy5861** [kubernetes/kubernetes#28144]
I am from official instances did a redis master-slave, but I can not connect to the master service allocation in the slave containers such as ip: 10.254.31.52, contrary came in they could not connect to the master slave service assigned ip ask this. what causes the network can not communicate? 

Thank you!

service ip
![1](https://cloud.githubusercontent.com/assets/8274977/16405760/ab25f4ba-3d3c-11e6-9227-ce2c433430e3.png)

slave container in ping master service ip:
![2](https://cloud.githubusercontent.com/assets/8274977/16405776/c0d9b1de-3d3c-11e6-8687-f0fccc47467a.png)

master container in ping slave service ip:
![3](https://cloud.githubusercontent.com/assets/8274977/16405809/fce52ed8-3d3c-11e6-8c56-be9ff1b09bbc.png)

new start service
![4](https://cloud.githubusercontent.com/assets/8274977/16421258/f231f9c2-3d86-11e6-8ff8-e3aa6c42fb40.png)

**Comment by jlowdermilk** [comment]
Please post your question to  [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We use github issues to track bugs, feature requests, and proposals. Help/support questions will be responded to much faster on stackoverflow, and you may find someone else has already posted a similar question and found a solution. The Kubernetes team regularly scans stackoverflow and will try to ensure questions don't go unanswered. Thanks.
