### ISSUE TITLE
kubernetes/deployment: Proportional scaling while rolling out have unexpected result in unpause

### ISSUE THREAD

**Issue by chengzhang1016** [kubernetes/kubernetes#28145]
Description of problem:
kubernetes/deployment: Proportional scaling while rolling out have unexpected result in unpause. 

Version-Release number of selected component (if applicable):
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.0.890+ecfd4aa131035a", GitCommit:"ecfd4aa131035a4747cfdf90d89a2fe823341657", GitTreeState:"clean", BuildDate:"2016-06-27T08:34:32Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.0.890+ecfd4aa131035a", GitCommit:"ecfd4aa131035a4747cfdf90d89a2fe823341657", GitTreeState:"clean", BuildDate:"2016-06-27T08:34:32Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

How reproducible:
Always

[Problem]: Proportional scaling and rollout have unexpected result in unpause. 
Steps to Reproduce:
Step 1. Generate a deployment with two RSs, as below:
Deployment.replicas=10
maxSurge=3
maxUnavailabl=2
```
# kubectl get rs
NAME                         DESIRED   CURRENT   AGE
nginx-deployment-508933516   8         8         33s
nginx-deployment-520009149   5         5         9s
```
How to generate above two RSs:
Step 1.1 Create deployment with below yaml file:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.1
        ports:
        - containerPort: 80
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
    type: RollingUpdate
```
Step 1.2 Edit deployment, and change image from `nginx:1.7.1` to `nginx:abc`

Step 2. Edit deployment, change replicas from 10 to 20 and image from `nginx:abc` to `nginx:123` together
```
# kubectl edit deployment/nginx-deployment
deployment "nginx-deployment" edited
```
Step 3. Check scaled result via: `# kubectl get rs`

Actual results: Only the the new rs scale up 10 replicas in unpause.
Step 3. Check scaled result
```
# kubectl get rs
NAME                          DESIRED   CURRENT   AGE
nginx-deployment-1690416429   10        10        12s
nginx-deployment-508933516    8         8         5m
nginx-deployment-520009149    5         5         2m
```

Expected results: Proportional scaling should work while rolling out in unpause, result should be same with in pause and then resume.
Step 3. Check scaled result
```
# kubectl get rs
NAME                          DESIRED   CURRENT   AGE
nginx-deployment-1690416429   5         5         5s
nginx-deployment-508933516    14        14        2m
nginx-deployment-520009149    4         4         1m
```

Additional info: 
I also did some comparing test in pause, the result looks well.
Steps from comparing test:
Step 1. Generate a deployment with two RSs, as below:
Deployment.replicas=10
maxSurge=3
maxUnavailabl=2
```
# kubectl get rs
NAME                         DESIRED   CURRENT   AGE
nginx-deployment-508933516   8         8         33s
nginx-deployment-520009149   5         5         9s
```
Step 2. Pause deployment
```
# kubectl rollout pause deployment nginx-deployment
deployment "nginx-deployment" paused
```
Step 3. Edit deployment, change replicas from 10 to 20 and image from `nginx:abc` to `nginx:123`
```
# kubectl edit deployment/nginx-deployment
deployment "nginx-deployment" edited
```
Step 4. Check scaled result
```
# kubectl get rs
NAME                         DESIRED   CURRENT   AGE
nginx-deployment-508933516   14        14        1m
nginx-deployment-520009149   9         9         1m
```
Step 5. Resume deployment
```
# kc rollout resume deployment nginx-deployment
deployment "nginx-deployment" resumed
```
Step 6. Check rs again
```
# kubectl get rs
NAME                          DESIRED   CURRENT   AGE
nginx-deployment-1690416429   5         5         18s
nginx-deployment-508933516    14        14        2m
nginx-deployment-520009149    4         4         1m
```

**Comment by kargakis** [comment]
> Step 3. Check scaled result
> Expected results: Proportional scaling should work while rolling out in unpause, result should be same with in pause and then resume.

Your deployment is not paused and you request a new rollout with your template change. All new pods should go to the new replica set. This is not a bug but a feature.

cc: @kubernetes/deployment

**Comment by kargakis** [comment]
Reopening because when the new replica set is created and scaled up, it is the only one that has the updated annotations (the other replica sets haven't noticed the new size of the deployment). This means that we will treat the following sync as a scaling event rather than a rollout.

**Comment by chengzhang1016** [comment]
Yes, I think should do scaling up before create a new RS in this case.

**Comment by kargakis** [comment]
Is this the intention of someone who deploys and scales at the same time?

**Comment by chengzhang1016** [comment]
Yes. I want to scale up and change pod template(create a new RS) at the same time in unpause for this case. All rs should do proportional scale(not only the new rs). I think the expect result should be same as after resume in pause.

**Comment by kargakis** [comment]
A change in the deployment template is an explicit request for rolling out the new template when the deployment is not paused. This means that we shouldn't do proportional scaling but infer to the strategy. Scaling cannot happen beforehand if it was changed in the same request. If you want to scale before you roll out, you will need to separate your requests.

**Comment by chengzhang1016** [comment]
OK. By the way, what is the expect results for Step 3 ?

**Comment by kargakis** [comment]
You don't test proportional scaling in step 3, you test the rollout strategy. What you saw is expected.

**Comment by chengzhang1016** [comment]
OK. Thank you so much.
