### ISSUE TITLE
k8s kube-up.sh install script does not support systemd?

### ISSUE THREAD

**Issue by spacexnice** [kubernetes/kubernetes#28148]
i found that kube-up.sh does not work on ubuntu 16.04LTS ?   because service etcd start goes to systemctl etcd start ,which not work?

**Comment by mkumatag** [comment]
what `KUBERNETES_PROVIDER` are you using and how are you running this script?

**Comment by jlowdermilk** [comment]
Please post your question to  [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We use github issues to track bugs, feature requests, and proposals. Help/support questions will be responded to much faster on stackoverflow, and you may find someone else has already posted a similar question and found a solution. The Kubernetes team regularly scans stackoverflow and will try to ensure questions don't go unanswered. Thanks.
