### ISSUE TITLE
Closing a stopChannel does not stop a controller

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#28158]
Let `ctrl` be a `Controller` returned by `framework.NewInformer()`. Following code does not stop the running controller:

```
stopCh := make(chan struct{})
go ctrl.Run(stopCh)

time.Sleep(time.Minute)
close(stopCh)
```

The controller is stuck in `k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).Pop()` call, where the channel is ignored. This clutters all stack dumps when unit tests are running in sequence (`go test -count 10000`) and make race detection crash ("limit on 8192 simultaneously alive goroutines is exceeded, dying").

Full stack trace of the waiting goroutine:

```
#   0x43511     sync.runtime_Syncsemacquire+0x201                                               /usr/local/Cellar/go/1.6.2/libexec/src/runtime/sema.go:241
#   0x138b53    sync.(*Cond).Wait+0xb3                                                      /usr/local/Cellar/go/1.6.2/libexec/src/sync/cond.go:63
#   0x3b91a7    k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).Pop+0xe7                                    /Users/mhb/src/gocode/src/k8s.io/kubernetes/pkg/client/cache/delta_fifo.go:399
#   0x3d0eb9    k8s.io/kubernetes/pkg/controller/framework.(*Controller).processLoop+0x79                           /Users/mhb/src/gocode/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:127
#   0x3d47de    k8s.io/kubernetes/pkg/controller/framework.(*Controller).(k8s.io/kubernetes/pkg/controller/framework.processLoop)-fm+0x2e   /Users/mhb/src/gocode/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:103
#   0x929339    k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1+0x59                                      /Users/mhb/src/gocode/src/k8s.io/kubernetes/pkg/util/wait/wait.go:86
#   0x9290ea    k8s.io/kubernetes/pkg/util/wait.JitterUntil+0xca                                        /Users/mhb/src/gocode/src/k8s.io/kubernetes/pkg/util/wait/wait.go:87
#   0x929001    k8s.io/kubernetes/pkg/util/wait.Until+0x51                                          /Users/mhb/src/gocode/src/k8s.io/kubernetes/pkg/util/wait/wait.go:49
#   0x3d0b8e    k8s.io/kubernetes/pkg/controller/framework.(*Controller).Run+0x25e                              /Users/mhb/src/gocode/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:103
```

**Comment by MHBauer** [comment]
see #28128 as an example

**Comment by AdoHe** [comment]
Generally I think we should fix this #23715, which gives `wait.Until` a chance to stop the inner goroutine.

**Comment by jsafrane** [comment]
I think that `wait.Until` will end the controller goroutine (its stop channel was closed), however we need a way to break `DeltaFIFO.Pop()`, so `wait.Until` can actually stop.

**Comment by ingvagabund** [comment]
Affecting cluster capacity as well [1]. The scheduler consists of two controllers using the ``DeltaFIFO.Pop()``. Each iteration of the cluster capacity analysis consists of scheduler creation, running scheduler until no pod is schedulable and cleaning up the scheduler. As the two controllers are never cleaned up completely, each iteration leaves two go-routines blocked on the ``Pop()``. Running the analysis for a long time leaves a lot of blocked go-routines (482 in 8 minutes with 1 second iteration period).

[1] https://github.com/ingvagabund/cluster-capacity

**Comment by fraenkel** [comment]
Even if you break DeltaFIFO.Pop(), Controller.processLoop will never exit.
