### ISSUE TITLE
Kubelet restarted randomly

### ISSUE THREAD

**Issue by javiercr** [kubernetes/kubernetes#28154]
We have a production web app running on a GKE cluster with 2 nodes (Kubernetes v1.2). Today the the app suddenly started returning 502 errors (as the health check for the web service was failing).

Right after this happened I run `kubectl get events` and this was the output:

```
kubectl get events
FIRSTSEEN   LASTSEEN   COUNT     NAME                         KIND      SUBOBJECT   TYPE      REASON                  SOURCE                                 MESSAGE
1m          1m         1         gke-app-8d801be1-node-d0jh   Node                  Normal    Starting                {kubelet gke-app-8d801be1-node-d0jh}   Starting kubelet.
51s         43s        2         gke-app-8d801be1-node-d0jh   Node                  Normal    NodeHasSufficientDisk   {kubelet gke-app-8d801be1-node-d0jh}   Node gke-app-8d801be1-node-d0jh status is now: NodeHasSufficientDisk
43s         43s        1         gke-app-8d801be1-node-d0jh   Node                  Normal    NodeNotReady            {kubelet gke-app-8d801be1-node-d0jh}   Node gke-app-8d801be1-node-d0jh status is now: NodeNotReady
21s         21s        1         gke-app-8d801be1-node-d0jh   Node                  Normal    NodeReady               {kubelet gke-app-8d801be1-node-d0jh}   Node gke-app-8d801be1-node-d0jh status is now: NodeReady
```

This node `gke-app-8d801be1-node-d0jh` is in fact the one that has allocated all the pods for the web app.

After a few seconds the app was running as normal, and the containers do not show any restart. What's going on? Why kubelet would be restarted for no reason? Thanks.

**Comment by dchen1107** [comment]
@javiercr on each node, we also has babysitters to check daemons' health. For example, kubelet might be restart if syncLoop take too long (like 5 min) or PLEG (pod life event generator)  is not healthy. Most time it is due to one docker operation hang, and retry should resolve the issue normally. When babysitter detects such issue, it tries to self-healing by restarting kubelet. Restarting kubelet doesn't restart applications, but restarting docker will. I guess in your case, the docker daemon is restarted somehow. But there is no issue generated for this. 

In 1.3 release, we apply timeout to most of docker operations, restarting kubelet due to long syncLoop or unhealth PLEG shouldn't happen any more.

**Comment by javiercr** [comment]
@dchen1107 is there any way to find out what happened? I took a look to the kubelet.log but I didn't find anything conclusive. Thanks!

**Comment by Random-Liu** [comment]
@javiercr Go into your node, and check `/var/log/supervisor/supervisord.log`? It will show whether your kubelet was unhealthy and it restarted it.

**Comment by javiercr** [comment]
@Random-Liu this is what I have for the last few days:

```
2016-06-28 08:01:17,430 INFO exited: kubelet (exit status 2; expected)
2016-06-28 08:01:18,753 INFO spawned: 'kubelet' with pid 4070
2016-06-28 08:01:19,849 INFO success: kubelet entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-06-28 10:02:18,052 INFO exited: kubelet (exit status 2; expected)
2016-06-28 10:02:19,359 INFO spawned: 'kubelet' with pid 17022
2016-06-28 10:02:20,344 INFO success: kubelet entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-06-28 12:02:23,127 INFO exited: docker (exit status 2; expected)
2016-06-28 12:02:24,203 INFO spawned: 'docker' with pid 29699
2016-06-28 12:02:25,205 INFO success: docker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-06-28 12:02:26,838 INFO exited: kubelet (exit status 2; expected)
2016-06-28 12:02:27,841 INFO spawned: 'kubelet' with pid 30042
2016-06-28 12:02:28,946 INFO success: kubelet entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-06-29 00:22:58,708 INFO exited: docker (exit status 2; expected)
2016-06-29 00:23:05,077 INFO spawned: 'docker' with pid 370
2016-06-29 00:23:06,079 INFO success: docker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-06-29 00:23:10,432 INFO exited: kubelet (exit status 2; expected)
2016-06-29 00:23:11,435 INFO spawned: 'kubelet' with pid 860
2016-06-29 00:23:12,518 INFO success: kubelet entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

I think one of the restarts matches the date and time when I noticed this issue. How can I avoid `docker` and `kubectl` to be restarted?

**Comment by Random-Liu** [comment]
@javiercr Kubelet will only be restarted when it is not healthy, you should let supervisord restarts it to make your cluster more reliable.

In v1.2, the most frequent reason that causes kubelet to be restarted is docker hung because of some docker bug.

In v1.3, we add timeout to all docker operations, which should solve the problem. (More information: https://github.com/kubernetes/kubernetes/issues/23563)

**Comment by javiercr** [comment]
@Random-Liu same thing happened again and yesterday we updated to v1.3.5. Here is the log of events:


```
NAMESPACE     LASTSEEN   FIRSTSEEN   COUNT     NAME                                                 KIND      SUBOBJECT                         TYPE      REASON                   SOURCE                                   MESSAGE
default       6m         21h         4         gke-myapp-8d801be1-node-e96k                         Node                                        Normal    NodeNotReady             {controllermanager }                     Node gke-myapp-8d801be1-node-e96k status is now: NodeNotReady
default       1m         2m          5         gke-myapp-8d801be1-node-e96k                         Node                                        Normal    DeletingAllPods          {controllermanager }                     Node gke-myapp-8d801be1-node-e96k event: Deleting all Pods from Node gke-myapp-8d801be1-node-e96k.
default       1m         1m          1         gke-myapp-8d801be1-node-e96k                         Node                                        Normal    TerminatingEvictedPod    {controllermanager }                     Node gke-myapp-8d801be1-node-e96k event: Pod fluentd-cloud-logging-gke-myapp-8d801be1-node-e96k has exceeded the grace period for deletion after being evicted from Node "gke-myapp-8d801be1-node-e96k" and is being force killed
default       1m         1m          1         gke-myapp-8d801be1-node-e96k                         Node                                        Normal    TerminatingEvictedPod    {controllermanager }                     Node gke-myapp-8d801be1-node-e96k event: Pod heapster-v1.1.0-2599329277-2dkk9 has exceeded the grace period for deletion after being evicted from Node "gke-myapp-8d801be1-node-e96k" and is being force killed
default       1m         1m          1         gke-myapp-8d801be1-node-e96k                         Node                                        Normal    TerminatingEvictedPod    {controllermanager }                     Node gke-myapp-8d801be1-node-e96k event: Pod kube-dns-v17.1-r9t7z has exceeded the grace period for deletion after being evicted from Node "gke-myapp-8d801be1-node-e96k" and is being force killed
default       1m         1m          1         gke-myapp-8d801be1-node-e96k                         Node                                        Normal    TerminatingEvictedPod    {controllermanager }                     Node gke-myapp-8d801be1-node-e96k event: Pod kube-dns-v17.1-yss3m has exceeded the grace period for deletion after being evicted from Node "gke-myapp-8d801be1-node-e96k" and is being force killed
default       1m         1m          1         gke-myapp-8d801be1-node-e96k                         Node                                        Normal    TerminatingEvictedPod    {controllermanager }                     Node gke-myapp-8d801be1-node-e96k event: Pod kube-proxy-gke-myapp-8d801be1-node-e96k has exceeded the grace period for deletion after being evicted from Node "gke-myapp-8d801be1-node-e96k" and is being force killed
default       1m         1m          1         gke-myapp-8d801be1-node-e96k                         Node                                        Normal    TerminatingEvictedPod    {controllermanager }                     Node gke-myapp-8d801be1-node-e96k event: Pod kubernetes-dashboard-1775839595-st4s9 has exceeded the grace period for deletion after being evicted from Node "gke-myapp-8d801be1-node-e96k" and is being force killed
default       1m         1m          1         gke-myapp-8d801be1-node-e96k                         Node                                        Normal    TerminatingEvictedPod    {controllermanager }                     Node gke-myapp-8d801be1-node-e96k event: Pod kubernetes-dashboard-v1.1.1-p327m has exceeded the grace period for deletion after being evicted from Node "gke-myapp-8d801be1-node-e96k" and is being force killed
default       1m         1m          1         gke-myapp-8d801be1-node-e96k                         Node                                        Normal    TerminatingEvictedPod    {controllermanager }                     Node gke-myapp-8d801be1-node-e96k event: Pod l7-default-backend-v1.0-eudcx has exceeded the grace period for deletion after being evicted from Node "gke-myapp-8d801be1-node-e96k" and is being force killed
```

To be honest this is freaking us out, as this is a production app and we're seeing how it randomly goes offline with a 5 minutes downtime until all the pods get restarted. Is there anything we can do to debug this situation?

**Comment by Random-Liu** [comment]
@javiercr Could you please give us your `kubelet.log`? That will help debugging a lot! :)

**Comment by javiercr** [comment]
@Random-Liu the kubelet.log is huge and is really hard to find the relevant information. This is that log filtered on the node that crashed last time (`-e96k`), displaying only Error and Critical logs, and around the time our site went down (12:06)

![image](https://cloud.githubusercontent.com/assets/855995/18026546/f07d4a4e-6c4a-11e6-85de-ff8a9a6fc3f3.png)

**Comment by Random-Liu** [comment]
So from the log, it seems that docker is not running or unreachable because of some reason.
The log is full of `Cannot connect to Docker daemon`. If you still have that node running, it would be good to check `docker.log`, `supervisord.log` and `kern.log` to see whether there is anything weird for docker during that time.

**Comment by javiercr** [comment]
@Random-Liu 

This is the `docker.log at` the time the site went down:

![image](https://cloud.githubusercontent.com/assets/855995/18033235/17c4db34-6d1e-11e6-93fa-bbc76a6174e5.png)

The logs from 06:04 are before it went down and probably not related to this issue. Then there are some messages regarding the deletion of containers and that's probably when the cluster was trying to recreate the containers. But I can't see anything related to the cause of the problem.


This is the `supervisord.log` around the same time:

```
2016-08-26 22:01:53,344 INFO exited: kubelet (exit status 2; expected)
2016-08-26 22:01:55,223 INFO spawned: 'kubelet' with pid 11464
2016-08-26 22:01:56,701 INFO success: kubelet entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-08-26 22:05:38,785 INFO exited: docker (exit status 2; expected)
2016-08-26 22:05:41,185 INFO spawned: 'docker' with pid 11636
2016-08-26 22:08:09,415 INFO success: docker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-08-26 22:15:12,698 INFO exited: docker (exit status 2; expected)
2016-08-26 22:15:14,657 INFO spawned: 'docker' with pid 12080
2016-08-26 22:15:15,658 INFO success: docker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-08-26 22:15:21,628 INFO exited: kubelet (exit status 2; expected)
2016-08-26 22:15:22,491 INFO spawned: 'kubelet' with pid 12477
2016-08-26 22:15:23,493 INFO success: kubelet entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

Finally `/var/log/kern.log` is empty. Is this normal?

Thank you!

**Comment by javiercr** [comment]
Tonight we had another random restart of docker and kubelet which caused our production site to went down for some minutes, here is the `supervirsord.log`:

```
2016-09-02 00:12:24,713 INFO exited: docker (exit status 2; expected)
2016-09-02 00:12:25,909 INFO spawned: 'docker' with pid 29441
2016-09-02 00:12:26,912 INFO success: docker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-09-02 00:30:30,489 INFO exited: docker (exit status 2; expected)
2016-09-02 00:31:05,948 INFO spawned: 'docker' with pid 4226
2016-09-02 00:31:06,613 INFO success: docker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-09-02 00:31:09,304 INFO exited: kubelet (exit status 2; expected)
2016-09-02 00:31:09,913 INFO spawned: 'kubelet' with pid 4332
2016-09-02 00:31:10,993 INFO success: kubelet entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-09-02 00:59:06,299 INFO exited: kubelet (exit status 2; expected)
2016-09-02 00:59:07,025 INFO spawned: 'kubelet' with pid 16825
2016-09-02 00:59:08,285 INFO success: kubelet entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-09-02 01:02:19,191 INFO exited: docker (exit status 2; expected)
2016-09-02 01:02:20,850 INFO spawned: 'docker' with pid 17241
2016-09-02 01:02:21,852 INFO success: docker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-09-02 01:02:25,322 INFO exited: kubelet (exit status 2; expected)
2016-09-02 01:02:26,324 INFO spawned: 'kubelet' with pid 17467
2016-09-02 01:02:27,679 INFO success: kubelet entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

@Random-Liu what is the best way to debug this problem? Thank yu.

**Comment by javiercr** [comment]
I guess the last two logs are related to #27651 and #27653. As kubelet is restarting for some reason, it's messing up with the removal of orphaned pods.

**Comment by Random-Liu** [comment]
@javiercr Sorry for the delay. From the supervisord.log, docker was always restarted before kubelet.

We rely on supervisord to monitor docker health, basically it just run [the script](https://github.com/kubernetes/kubernetes/blob/f2ddd60eb9e7e9e29f7a105a9a8fa020042e8e52/cluster/saltbase/salt/supervisor/docker-checker.sh). It just periodically run `docker ps` to see whether docker is alive. If not, it will restart docker.

And docker daemon does sometimes become unresponsive. You can search "docker hung" in docker github issue list, you will see this https://github.com/docker/docker/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20docker%20hang.

Once docker hangs, kubelet will also reports unhealthy, then supervisord will restart both docker and kubelet.

**Comment by Random-Liu** [comment]
@javiercr Here is more detailed explanation, once docker hangs, both docker and kubelet got restarted by supervisord:
* Kubelet restart: in fact kubelet restart shouldn't affect your application at all, after it is restarted, it should take charge of all existing running container and your application shouldn't have downtime.
* Docker restart: docker restart will kill all your running containers which is a known issue. Docker has addressed this in v1.12 with `live-restore` option, but I haven't tried yet https://docs.docker.com/engine/admin/live-restore/.

**Comment by javiercr** [comment]
Thank you @Random-Liu 

We are having daily restarts at pretty much the same time so we think it's related to one of our cron long running cron jobs that  takes place every night. It may be a memory consumption problem, however our cluster has 2 nodes with 7.5 GB each, and this cron was running without problems in our previous infrastructure with less RAM (not docker based).

We're considering disabling that task temporary to see if it aliviates the problem. In any case, the cron job is executed in a specific pod, if this pod is taking up too much memory, shouldn't kubernetes kill that pod and do not touch the others?

Also when this happens, it kills even our DB pod with posgres, and sometimes it is not able to started again for the error mentioned above:

````
mkdir: cannot create directory ‘/var/lib/postgresql/data/pgdata’: Read-only file system
```

Whether kubernetes is able to restored this database pod (it's defined as part of a deployment) or not, it seems to be totally random. When this happens we need to scale the replicas to 0 for the db deployment and the scale up to 1 again, manually.

Regarding docker version:

```
docker -v
Docker version 1.11.2, build b9f10c9
```

Note that we're running on Google Container Engine (GKE), so docker was installed already.

**Comment by yujuhong** [comment]
> We're considering disabling that task temporary to see if it aliviates the problem. In any case, the cron job is executed in a specific pod, if this pod is taking up too much memory, shouldn't kubernetes kill that pod and do not touch the others?

Do you set memory limit for this pod? What's the spec? 
If a pod uses more than what the memory limit is allowed, it'd get killed. Setting good memory requests/limits helps the node not being over-committed, and also limits the damage to a single pod.  However, if the whole node is under memory pressure, kernel would pick a victim process to kill. Kubelet adjusts the OOM scores to make sure that kernel would pick regular pods over the kubelet or the docker process. If this ever happens, you should see messages in the kernel log. Could you confirm whether docker was killed due to system memory pressure?

**Comment by yujuhong** [comment]
Closing due to age.

**Comment by conrallendale** [comment]
Was this resolved? I have the same problema today with GKE. Version:

`Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}`

One node keep alternating between Ready and NotReady and no application is able to start on it, keeping status "Init:0/1" or "ContainerCreating". On "kubectl describe pod" I see kubernetes is trying to pull image during a long time, like 30 minutes (I imagine it would last forever) until I manually remove the node from the cluster.
