### ISSUE TITLE
the yaml format of support GPU

### ISSUE THREAD

**Issue by jianzhangbjz** [kubernetes/kubernetes#28152]
Hi guys,

Have someone know the yaml format of supporting GPU devices?
the  [kubernetes/docs/proposals/gpu-support.md](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/gpu-support.md) just said:
"User creates a pod using the image, **requiring alpha.kubernetes.io/nvidia-gpu: 1**"
But, what is the right format of this yaml?

**Comment by mkumatag** [comment]
The mentioned doc is just a proposal and not implemented I feel. If it gets implements the mentioned tag goes as annotation in the pod yaml, you can refer - [Annotations](http://kubernetes.io/docs/user-guide/annotations/) for more information.

**Comment by jianzhangbjz** [comment]
@mkumatag Thanks, please refer this discussion [Hui-Zhi/kubernetes](https://github.com/Hui-Zhi/kubernetes/issues/1).
I created s Pod Yaml as Hui-Zhi mentioned in that issue. But it came error, there [ Error: "nvidiaGPU" is Invalid value #3 ](https://github.com/Hui-Zhi/kubernetes/issues/3) do you have any ideas?

**Comment by Hui-Zhi** [comment]
@mkumatag @jianzhangbjz My branch works fine with GPU and I have tested, but the code not ready for sending a pull request.

**Comment by jlowdermilk** [comment]
As mentioned, this is a proposed feature that isn't in review yet. Feel free to continue discussion offline or in https://github.com/Hui-Zhi/kubernetes/issues/3

**Comment by jianzhangbjz** [comment]
@jlowdermilk Ok, thanks.
@Hui-Zhi I added test steps in [Hui-Zhi#3](https://github.com/Hui-Zhi/kubernetes/issues/3), please help check it, thanks.
