### ISSUE TITLE
[QUESTION]Couldn't find an endpoint for default/svc: missing endpoints

### ISSUE THREAD

**Issue by vklonghml** [kubernetes/kubernetes#28157]
Hi, all:

i encounter a problem as follows:
1)k8s version:1.1.8
2)create a pod,service, and i just can't visit the service of the pod
3)here are the definitions of pod and service, endpoint:
kubectl get pod/p1 -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    netID0: 13a72e9b-fd9e-4383-8d29-fabf1ec19d89
  creationTimestamp: 2016-06-28T19:26:50Z
  labels:
    id: p1
  name: p1
  namespace: default
  resourceVersion: "269"
  selfLink: /api/v1/namespaces/default/pods/p1
  uid: 431178e4-3d66-11e6-be39-fa163eedcb04
spec:
  containers:
  - image: 192.168.71.144:5000/httpd
    imagePullPolicy: IfNotPresent
    name: dockerhttpd
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      limits:
        cpu: 300m
      requests:
        cpu: 300m
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
  dnsPolicy: ClusterFirst
  nodeName: 10.10.15.131
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: Ready
  containerStatuses:
  - containerID: docker://35c370dcc5cf1b3a759e22ce71708c3fd0177dea62d89a4f3c1e1f30d6438f12
    image: 192.168.71.144:5000/httpd
    imageID: docker://a2ceb9245c636b4cd9a6f21f0dd76f50d34a9e02dbc42b3423e61a8f40c71858
    lastState: {}
    name: dockerhttpd
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2016-06-28T19:27:04Z
  hostIP: 10.10.15.131
  phase: Running
  podIP: 10.10.15.137
  startTime: 2016-06-28T19:26:50Z

kubectl get svc/svc-qwlvzipzugz683d -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-06-28T19:26:59Z
  labels:
    name: svc-qwlvzipzugz683d
  name: svc-qwlvzipzugz683d
  namespace: default
  resourceVersion: "260"
  selfLink: /api/v1/namespaces/default/services/svc-qwlvzipzugz683d
  uid: 48677161-3d66-11e6-be39-fa163eedcb04
spec:
  clusterIP: 11.1.214.157
  ports:
  - name: "80"
    nodePort: 30105
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    id: p1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

kubectl get endpoints/svc-qwlvzipzugz683d -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: 2016-06-28T19:26:59Z
  labels:
    name: svc-qwlvzipzugz683d
  name: svc-qwlvzipzugz683d
  namespace: default
  resourceVersion: "270"
  selfLink: /api/v1/namespaces/default/endpoints/svc-qwlvzipzugz683d
  uid: 486917ee-3d66-11e6-be39-fa163eedcb04
subsets:
- addresses:
  - ip: 10.10.15.137
    targetRef:
      kind: Pod
      name: p1
      namespace: default
      resourceVersion: "269"
      uid: 431178e4-3d66-11e6-be39-fa163eedcb04
  ports:
  - name: "80"
    port: 80
    protocol: TCP

the endpoint can visit direct through 10.10.15.137:80, but can not visit through 127.0.0.1:30105, in the kube-proxy log file, it shows: Couldn't find an endpoint for default/svc-qwlvzipzugz683d:80: missing endpoints,Failed to connect to balancer: missing endpoints.

and the iptables-save looks right, does anybody knows how to solve the problem,thks.

**Comment by jlowdermilk** [comment]
Please post your question to  [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We use github issues to track bugs, feature requests, and proposals. Help/support questions will be responded to much faster on stackoverflow, and you may find someone else has already posted a similar question and found a solution. The Kubernetes team regularly scans stackoverflow and will try to ensure questions don't go unanswered. Thanks.
