### ISSUE TITLE
Properly expose counter states and generally better metrics to Prometheus

### ISSUE THREAD

**Issue by jnardiello** [kubernetes/kubernetes#28156]
I'm trying to implement a metric tracking states of each pod. Goal is to be able to detect if a pod gets continuously restarted in a given period of time, highlighting a problem on the pod.

Here is the current data exposed by `container_tasks_state`: http://pastebin.com/z1KixQCC

The value of this metric is extremely limited as all values are all set to 0 and there's currently no way to access `io_kubernetes_container_restartCount` (or any other label).

Genrally speaking, Kubernetes should expose more meaningful data to prometheus as discussed with @juliusv, @fabxc and @jimmidyson from https://github.com/prometheus

**Comment by therc** [comment]
You can't even get the desired size of a RC/RS/Deployment from Prometheus.
