### ISSUE TITLE
AWS: Service annotation so that ELBs are created with cross-zone load balancing enabled.

### ISSUE THREAD

**Issue by dmcnaught** [kubernetes/kubernetes#28174]
According to @justinsb this doesn't currently exist, but we should add it for 1.3.1 or 1.4

Currently you can manage outside of Kubernetes with the AWS API.

**Comment by justinsb** [comment]
Do you know of any reason not to just always enable this?

(If so, I guess we should still make it the default, but I guess that depends on the answer to the first question!)

**Comment by dmcnaught** [comment]
I don't know of any reason not to @justinsb

**Comment by therc** [comment]
I can do this, since I think it would benefit us (and I can't find any drawbacks, either).

**Comment by jkemp101** [comment]
I believe this can be closed.  `service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "True"` should do the trick.

**Comment by TaiSHiNet** [comment]
@jkemp101 is right, this worked.
Also this should be documented somewhere

**Comment by michaelajr** [comment]
Ah. Awesome. Very glad to have found this.

**Comment by michaelajr** [comment]
Enabled. But LBs are created serving only one zone. Used KOPS to create the cluster and defined my subnets there. Is there something to add to the YAML or annotations to tell AWS to add the other subnets to the LB?

**Comment by michaelajr** [comment]
So my issue is due to the fact that a tag is needed on the subnets to get the ELB to use them. This is odd since the state store contains the subnets of the cluster. Why do we need tags here? Especially since I brought my own subnets using KOPS.

**Comment by azman0101** [comment]
Is there any news on this ?

**Comment by llarsson** [comment]
@michaelajr did you ever find a good solution?
