### ISSUE TITLE
Running bare metal K8s. Kube-proxy get x509: certificate signed by unknown authority but all other components able to run with certs

### ISSUE THREAD

**Issue by kwilliams057** [kubernetes/kubernetes#28175]
Running version Kubernetes v1.3.0-beta.2

/usr/bin/kube-apiserver --logtostderr=true --v=4 --etcd-servers=http://localhost:2379 --allow-privileged=true --advertise-address=MASTER_IP --service-cluster-ip-range=10.10.1.0/24 --client-ca-file=/srv/kubernetes/ca.crt --tls-cert-file=/srv/kubernetes/server.crt --tls-private-key-file=/srv/kubernetes/server.key --kubelet_certificate_authority=/srv/kubernetes/ca.crt --kubelet_client_certificate=/srv/kubernetes/server.crt --kubelet_client_key=/srv/kubernetes/server.key --admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota

/usr/bin/kubelet --logtostderr=true --v=4 --api-servers=https://MASTER_IP:6443 --address=0.0.0.0 --pod-infra-container-image=gcr.io/google_containers/pause:0.8.0 --cluster_domain=cluster.local --tls-cert-file=/srv/kubernetes/kubecfg.crt --tls-private-key-file=/srv/kubernetes/kubecfg.key --kubeconfig=/etc/kubernetes/kubeconfig

/usr/bin/kube-proxy --logtostderr=true --v=4 --master=https://MASTER_IP:6443 kubeconfig=/etc/kubernetes/kubeconfig

apiserver logs keep showing http: TLS handshake error from NODE_IP:37912: remote error: bad certificate

kubectl get no using the same kubeconfig works fine
kubectl get no --kubeconfig=/etc/kubernetes/kubeconfig
NAME              STATUS     AGE
NODE_NAME     Ready      3h

Error on kube-proxy logs
Can't get Node "NODE_NAME", assuming iptables proxy, err: Get https://MASTER_IP:6443
/api/v1/nodes/NODE_NAME: x509: certificate signed by unknown authority

**Comment by pwittrock** [comment]
@kwilliams057 If you need help troubleshooting this, slack and stackoverflow are more responsive channels.

**Comment by pwittrock** [comment]
@mikedanese Is this related to cluster setup.  Do you know who is the best person to handle it?

**Comment by kwilliams057** [comment]
This issue can be closed. It started working with v1.3.0

Thanks

**Comment by mikedanese** [comment]
I think your kubeconfig probably needed the ca.crt data

**Comment by mikedanese** [comment]
e.g. if your are using client tls for auth, this is pseudo code for what a kubeconfig needs to look like
```
{
      apiVersion: "v1",
      kind: "Config",
      users: [{
        name: name,
        user: {
          "client-key-data": "${base64encode(TLS_CLIENT_CRT_PRIVATE_KEY)}" % name,
          "client-certificate-data": "${base64encode(TLS_CLIENT_CRT)}",
        },
      }],
      clusters: [{
        name: "local",
        cluster: {
          "certificate-authority-data": "${base64encode(CA_CRT_DATA)}",
          server: apiserver_url,
        },
      }],
      contexts: [{
        context: {
          cluster: "local",
          user: name,
        },
        name: "service-account-context",
      }],
      "current-context": "service-account-context",
    },
  }
```
