### ISSUE TITLE
Minikube Getting Started Guide should include instructions for downloading kubectl

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kubernetes#28171]
The [Docker Getting Started Guide](http://kubernetes.io/docs/getting-started-guides/docker/#download-kubectl) contains instructions for downloading kubectl. The [Minikube guide](http://kubernetes.io/docs/getting-started-guides/minikube/) doesn't contain these instructions but it should if it's now the recommended way of running Kubernetes locally.

**Comment by marun** [comment]
+1 Just ran into this.

**Comment by jlowdermilk** [comment]
cc @mikedanese

**Comment by jlowdermilk** [comment]
By the way, we encourage anyone to propose improvements/fixes to docs. You can do so pretty easily by clicking the pencil icon in the top right corner of every page of http://kubernetes.io/docs/

**Comment by jlowdermilk** [comment]
kubectl download instructions added to the guide in https://github.com/kubernetes/kubernetes.github.io/pull/765.
