### ISSUE TITLE
kube-apiserver crashes when configured via insecure connection

### ISSUE THREAD

**Issue by ddska** [kubernetes/kubernetes#28185]
I've set up kubernetes v1.2.4  (also tried v1.3.0-beta.2) on AWS according to http://kubernetes.io/docs/getting-started-guides/aws/.
Then I changed on master node configuration of kube-apiserver to be able to access it via http by adding to  `/etc/kubernetes/manifests/kube-apiserver.manifest`:

```
--cors-allowed-origins=.* 
--insecure-bind-address=0.0.0.0 
--insecure-port=8888 
```

After this changes I can make requests via http, but a few minutes later server stops responding and I see in `kube-apiserver.log` exceptions like this:

```
I0628 19:38:18.459293       7 handlers.go:152] GET /api/v1/watch/services?resourceVersion=50104&timeoutSeconds=378: (611.892µs) 410
goroutine 349 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc209296150, 0x19a)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:214 +0xa6
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc209296150, 0x19a)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x32
k8s.io/kubernetes/pkg/apiserver/metrics.(*responseWriterDelegator).WriteHeader(0xc208d5bbc0, 0x19a)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:117 +0x53
k8s.io/kubernetes/pkg/apiserver.writeNegotiated(0x7f5b6e2cf368, 0xc2083e13e0, 0x0, 0x0, 0x1d4da80, 0x2, 0x7f5b6e1246d8, 0xc2085ebf28, 0xc2092420d0, 0x19a, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:429 +0x174
k8s.io/kubernetes/pkg/apiserver.errorNegotiated(0x7f5b6e2c27b8, 0xc209298180, 0x7f5b6e2cf368, 0xc2083e13e0, 0x0, 0x0, 0x1d4da80, 0x2, 0x7f5b6e1246d8, 0xc2085ebf28, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:441 +0xdd
k8s.io/kubernetes/pkg/apiserver.(*RequestScope).err(0xc2085244e0, 0x7f5b6e2c27b8, 0xc209298180, 0x7f5b6e1246d8, 0xc2085ebf28, 0xc2092420d0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:84 +0x11f
k8s.io/kubernetes/pkg/apiserver.func·027(0xc208d5bb30, 0xc20923f6e0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:295 +0x1055
k8s.io/kubernetes/pkg/apiserver/metrics.func·001(0xc208d5bb30, 0xc20923f6e0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:101 +0x269
github.com/emicklei/go-restful.(*Container).dispatch(0xc2083dcc60, 0x7f5b6e124380, 0xc209296150, 0xc2092420d0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:249 +0xf5e
github.com/emicklei/go-restful.*Container.(github.com/emicklei/go-re [[kubelet/v1.2.4 (linux/amd64) kubernetes/3eed1e3] 172.20.0.184:56673]
```

Logs are for v1.2.4.

But a few minutes later when kube-apiserver restarted, I can get responses again for a minute, and the same outage repeats again. The instance CPU Load is less then 10%.

**Comment by jlowdermilk** [comment]
I don't know if apiserver still supports running with insecure mode, but I suspect not. If you need http for testing/dev, can you run [`kubectl proxy`](http://kubernetes.io/docs/user-guide/kubectl/kubectl_proxy/) and use http against local endpoint?

**Comment by ddska** [comment]
OK, I can use proxy for sure. But if these params for insecure mode are deprecated, shall we denote this fact in https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/admin/kube-apiserver.md?

**Comment by jlowdermilk** [comment]
The params should be removed if they are deprecated, but I'd like someone more familiar with apiserver to confirm. cc @lavalamp @nikhiljindal

**Comment by lavalamp** [comment]
Insecure mode works fine, all our master components talk over the insecure port (if they are on the same VM). Are you sure that whatever triggered that message was actually talking over the insecure port? The secure port is still the thing that gets advertised and published. Not sure off the top of my head if you can adjust flags to get the insecure port published. But even if you could, probably components would send https requests to it and still not work...

...also listening on all interfaces on a VM on a cloud sounds like a super bad plan if your VM has public IP addresses, but I'm sure you're aware of this...

**Comment by ddska** [comment]
I started using insecure mode because of this bug: https://github.com/kubernetes/kubernetes/issues/24086
I'm working on front-end part and need CORS headers. So I'm using http just for development.
I turned insecure mode on using flags mentioned above, but I didn't remove secure bindings and port. So https mode works too.
