### ISSUE TITLE
Everything but serviceaccount/token controller supports ECDSA

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#28180]
Apiserver and kubeconfig all work using ECDSA keys for PKI but the service account controller supports only RSA because our jwt code assumes RSA although this is not a requirement of jwt in general:

https://github.com/kubernetes/kubernetes/blob/master/pkg/serviceaccount/jwt.go#L63

This produces a cryptic non-fatal error in the early controller-manager boot that could be easily missed and pods will fail to create assuming ServiceAccount admission controller is enabled (which it usually is).
```
E0628 02:31:57.135921       6 controllermanager.go:440] Error reading key for service account token controller: asn1: structure error: tags don't match (16 vs {class:0 tag:4 length:48 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} AlgorithmIdentifier @5
```

Is EC something that we want to support? If yes, we should enable it in the JWT parser. If no, we should explicitly validate against it.

cc @liggitt @erictune

**Comment by liggitt** [comment]
there was no particular reason for excluding it. looks like https://github.com/dgrijalva/jwt-go has added support for ecdsa since I pulled it in... bumping and allowing rsa or ecdsa keys would make sense to me

**Comment by gtank** [comment]
I'll take a look at this if no one else is. Deploying RSA in new projects makes me sad.

**Comment by erictune** [comment]
Go for it George

On Tue, Jun 28, 2016 at 3:36 PM, George Tankersley <notifications@github.com

**Comment by colemickens** [comment]
I need JWT updated for Azure cloudprovider. PR for just updating jwt-go and fixing breakage is here: https://github.com/kubernetes/kubernetes/pull/28520

**Comment by liggitt** [comment]
support added in https://github.com/kubernetes/kubernetes/issues/33565
