### ISSUE TITLE
hyperkube static pods not suitable for offline usage / private registries

### ISSUE THREAD

**Issue by virtuald** [kubernetes/kubernetes#28189]
In particular, if you're on a network that's disconnected from the internet completely, it's difficult to use the hyperkube image as it currently stands because the static pods all have hardcoded URLs for docker images in them.

From my limited perspective, it seems like the best way to solve this is to provide an argument to kubelet that allows it to rewrite registry URLs on the fly -- so if you passed `--infra-registry-url=registry.example.com/k8`, it would rewrite `gcr.io/google-containers/etcd-amd64:version` to `registry.example.com/k8/etcd-amd64:version`.

If this is a good idea (or if there are better approaches -- I'm certainly willing to consider them), I'm willing to chase them down, just need a pointer to the right place in the code to go searching.

**Comment by virtuald** [comment]
Running offline is further complicated by the fact that there are other pods that make their way into the hyperkube image, so there needs to be a good way to discover which images actually need to be downloaded. I think I have a way forward with that -- but `hyperkube kubectl convert ... ` doesn't seem to work without a connection to the API server for some reason. I'm sure I'm missing something...

**Comment by cheld** [comment]
IMHO, the images should be pulled from a private registry. To achieve this I suggest the following steps:

Step 1: Leverage and enhance the existing mechanisms
- Use the REGISTRY parameter in the make file of Hyperkube to build a Hyperkube for your own private registry 
- Add script private-registry.sh that launches private registry (and maybe some supporting functions)
- Add an option to master.sh and worker.sh to set --insecure-registry

However, the user has to build his own hyperkube. So, let's move to second step:

Step 2: Enhance setup container
- The manifest files must be patched for private registry during startup time - instead of build time. Patching the manifest files is a fundamental problem right now we have at many places in Hyperkube (e.g. Flannel Daemon-Set, Heapster sinks, ....). We need an agreed mechanism for patching the manifest files, first.

@luxas what do you think?

CC @zreigz, @taimir

**Comment by virtuald** [comment]
Step 1 is a bad solution IMHO, I imagine that one of the goals of an example deploy like docker-multinode is to get a user up and running as quickly as possible with as little work as possible. Recompiling docker images is just an extra step that it seems should be avoided if possible (which it is).

I like the idea of patching the manifest files.

If you refer to my PR for docker-multinode (https://github.com/kubernetes/kube-deploy/pull/168), you can see what I did to get an offline install working -- it's not particularly polished, but it works. Two phases:

* Use grep+awk to extract all image names from the manifests
* Use a script to copy the images to the remote machine (I provide private registry or docker load/save examples -- in the case of a private registry I retag them so they match the original names) 

It would be useful if something included with hyperkube (maybe kubectl?) had a 'get-required-images' command that output a list of everything required to use that particular hyperkube image. This would be required even if you provided a mechanism to patch the manifests for private registry at startup time.

**Comment by luxas** [comment]
I'd like to keep the logic in `common.sh` at absolutely the minimum.
I see it as you have to transfer the images to the offline node in some way.
This might be achieved in a few ways:
 - On an internet connected node that's different from the offline node:
   - `docker save <image> | ssh root@<ip> "docker load"`
   - `docker pull <image>; docker save <image> > .tar.gz; scp .tar.gz user@<ip>`
 - On the same node that should run docker-multinode 
   - simply `docker pull <image>` in advance

I do not like the idea of patching images; that's clearly the wrong way to go; if Kubernetes setup get so complex that we have to modify (hack) images that contain "official" content, there should be a better official way, or we should try to see the problem from a new perspective.

I'll gladly take Pull Requests that targets the documentation around this; once we have documented common/useful ways to transfer images to nodes, things will get easier for users. So please change your PR to a docs PR in the first place, and from there we might continue.

Things will change **a lot** (I hope) in `v1.4`, Kubernetes will try to ease cluster setup issues/complexities. Follow sig-cluster-lifecycle for more info.

I'll close this issue to keep conversation channels at a minimum, let's move this issue to the kube-deploy issue.
