### ISSUE TITLE
secrets guide references rolling-update and could use deployment version of language

### ISSUE THREAD

**Issue by jmhodges** [kubernetes/kubernetes#28184]
In http://kubernetes.io/docs/user-guide/secrets/#secret-and-pod-lifetime-interaction, there is mention of using `rolling-update` in order to update the secrets in some pods, but there is no language for what to do for pods controlled by a deployment. It would be nice for it to have some.

I'm not actually sure what that deployment language would be, however. Perhaps one of y'all do.

**Comment by kargakis** [comment]
cc: @kubernetes/deployment 

Related issues: https://github.com/kubernetes/kubernetes/issues/13488, https://github.com/kubernetes/kubernetes/issues/9043

**Comment by jmhodges** [comment]
I see this is tagged as help-wanted! If someone lets me know roughly what the deployment language for this looks like, I'll definitely contribute. I'm just not actually sure how to do it.
