### ISSUE TITLE
Feature Request: `kubectl` should output `AGE` as elapsed time in current state

### ISSUE THREAD

**Issue by osterman** [kubernetes/kubernetes#28190]
## what

`kubectl` should calculate the `age` as the time elapsed in the current state (e.g. `Running`, `ContainerCreating`, `Terminating`, etc)
## why

(IMO) Confusing UX: hard to tell if something is "stuck" if it's always outputting the total elapsed time. E.g. I thought this container was stuck in a `terminating` state. 
## example

![image](https://cloud.githubusercontent.com/assets/52489/16435045/2a5b50d0-3d48-11e6-9add-b4a100c50ee8.png)

Seeing this output, makes it appear that `edge-router-3200655793-lia0z` has been terminating for one day! In fact, it's been running for `1d` but been terminating for less than `1m`

**Comment by AdoHe** [comment]
When we say `AGE`, we are referring time over the whole lifecycle of pod, not just in one phase. @kubernetes/kubectl

**Comment by osterman** [comment]
@AdoHe yes - understood. The "feature request" would be to change that behavior or add an additional column which is the elapsed time for the current phase. =)

**Comment by pwittrock** [comment]
@osterman You should be able to get this for human-informational purposes from `kubectl describe` in the pods events.  Do you want this for programmatic access or just human visibility?

We shouldn't change the value of the existing column.  Adding a column seems reasonable if this is available from the Node.

@timstclair Do you know if this is easily available, or would it have to be calculated from events?

**Comment by osterman** [comment]
@pwittrock thanks! I would be satisfied by an additional column. The primary motivation is for human ease-of-use. I want to see how long pods have been in the current state without manual inspection (e.g. `kubectl describe`). Since pods are constructed automatically by deployments, it's easy to have hundreds or thousands of them.
