### ISSUE TITLE
Path to server tarball in openstack-heat cluster setup is invalid in release builds

### ISSUE THREAD

**Issue by RobDeBagel** [kubernetes/kubernetes#28205]
https://github.com/kubernetes/kubernetes/blob/master/cluster/openstack-heat/util.sh#L112

The path to the server tarball resolves to:
`<ROOT_DIR>/_output/release-tars/kubernetes-server-linux-amd64.tar.gz'`

`_output` is hardcoded, and does not exist in release builds (v1.3.0-beta.2) The file in question is located at:
`<ROOT_DIR>/server/kubernetes-server-linux-amd64.tar.gz`

Correcting the path is a workaround for release builds

**Comment by jlowdermilk** [comment]
cc @elsonrodriguez

**Comment by elsonrodriguez** [comment]
@RobDeBagel Hey, sorry about that.

I think I got a fix, but I need your help to test it. I'm traveling and my cellular upload speeds are not so great.

Please take a look at this and let me know if it solves the issue:
https://github.com/elsonrodriguez/kubernetes/commit/8b08ff5b648de46c72f9500fb350e19d974cb036
