### ISSUE TITLE
dockermanager: semver is not parsed correctly

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/kubernetes#28221]
History class:

1) docker [api]version retrieval refactored, removing the semver support [1], 
2) support for semver reverted by [2],
3) support for semver removed again by [3],
4) no support for semver by docker/engine-api [4],

W.r.t to 2), the semver parser was implemented by calling NewVersion of go-semver [5] repository which (as a side effect) thrown away everything after ``-`` character (including) from the version string.

Using engine-api as the semver parser does not provide such a side effect.

Currently, the semver parsing does not return any error. However, it does not work properly for semantic versions due to ``ParseInt`` (alias of ``Atoi``) behaviour [6]. Semver ``1.10.4-28.gitf476348.fc23`` is parsed as ``1.10.0`` instead of expected ``1.10.4``. So the comparison like ``dockerVersion("1.10.3").Compare("1.10.4-28.gitf476348.fc23")`` returns actual ``1`` instead of ``-1``.

[1] https://github.com/kubernetes/kubernetes/pull/19675
[2] https://github.com/kubernetes/kubernetes/pull/20020
[3] https://github.com/kubernetes/kubernetes/pull/23907
[4] https://github.com/docker/engine-api/blob/master/types/versions/compare.go#L10
[5] https://github.com/coreos/go-semver
[6] https://golang.org/pkg/strconv/#ParseInt

**Comment by ingvagabund** [comment]
I would suggest to put a  code pruning everything after the ``-`` character (including) into ``Compare`` [1] method before the version itself is passed to ``engine-api`` version parser.

[1] https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker_manager.go#L925

**Comment by aveshagarwal** [comment]
@kubernetes/rh-cluster-infra

**Comment by Random-Liu** [comment]
@ingvagabund I filed an issue before https://github.com/kubernetes/kubernetes/issues/24076.

When I initially added engine-api client, there is no version compare function in engine-api. After a while, they added it, so I changed the docker manager to use it.

But, yes, it's version check is relatively simple and doesn't support semver. :(

**Comment by Random-Liu** [comment]
@ingvagabund On second thought, I believe the compare function in engine-api https://github.com/docker/engine-api/blob/master/types/versions/compare.go#L10 is just used to compare api version.

We should change the code to parse docker version with go-semver.

**Comment by ingvagabund** [comment]
@Random-Liu agree with you. Thanks for the patch and additional unit-tests.
