### ISSUE TITLE
Need some changes to makefile & golang.sh to support support debug builds 

### ISSUE THREAD

**Issue by mikebrow** [kubernetes/kubernetes#28227]
To source debug Kubernetes binaries with tools like delve there is a need to provide debug build options to the glang compiler.  Specifically we need to be able to pass `-gcflags "-N -l"` to each go install, go build, and go test command  specified in hack/lib/golang.sh  These options turn off optimizations and inlining.  Thx to @derekparker for pointing out the need for `-gcflags "-N -l"`...

The pattern used for passing in -ldflags (linker flags) should suffice. Which is:
makefile includes:
KUBE_GOLDFLAGS = $(GOLDFLAGS)
export KUBE_GOLDFLAGS

Then golang.sh sets gold flags to KUBE_GOLDFLAGS ... then passes `-ldflags "${gold flags}"` to each of the go commands that build binaries from go code.  

Suggest repeating this pattern for gogcflags...  I can give a shot at PRing  this if there's agreement.

**Comment by jlowdermilk** [comment]
That pattern sounds reasonable. cc @spxtr

**Comment by spxtr** [comment]
Sounds reasonable to me. Right now we don't always go through the makefile, so the changes should happen in golang.sh.

**Comment by mikebrow** [comment]
@spxtr right!  The point on makefile was to make sure it would work for building from makefile as well as from the scripts.  

Suggestion would be for no change to the defaults development or release build.  One would have to set an environment variable GOGCFLAGS for makefile or KUBE_GOGCFLAGS for the scripts. 

For example:

`$ KUBE_GOGCFLAGS="-N -l" hack/build-go.sh`
or
`GOGCFLAGS="-N -l" make`

Then update the docs and makefile to explain how to build with optimizations (-N) and inline optimizations (-l) turned off, this for the purpose of source debugging.

**Comment by spxtr** [comment]
Sounds good.

**Comment by xiangpengzhao** [comment]
Since this was fixed in #28363 by Mike yourself, we can close this.

@thockin
