### ISSUE TITLE
node anti-affinity

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#28229]
I'd like to be able to specify in a rc/deployment that the pod members should land on nodes that have a certain set of labels, but that the value should be different for each member.

So, for example, say I tag my nodes with which rack, and chassis (multiple nodes per power supply), they are located in. I may want to say, node-anti-affinity: [rack, chassis]. This spreads out the failure domain as much as possible for the pods.

**Comment by ravilr** [comment]
you may also want to look at https://github.com/kubernetes/kubernetes/blob/master/docs/design/podaffinity.md . i believe it is going to be part of 1.3 release as an alpha feature.

**Comment by kargakis** [comment]
@kubernetes/sig-scheduling-misc @kubernetes/sig-node-misc

**Comment by timothysc** [comment]
Inter-pod-anti-affinity does this. 

The api is being promoted to beta-fields in 1.6, doc updates will follow on.  Please reopen if you think it does not meet your requirements.

**Comment by davidopp** [comment]
In particular the way you would do it is two separate anti-affinity rules, both of type "preferredDuringScheduling," one with TopologyKey corresponding to the node label key and one with TopologyKey corresponding to the rack label key, and both with label selector matching a label you tag to the pods of this collection with in the pod template.
