### ISSUE TITLE
[e2e_node flake] 10 minute pause between receiving and adding pod

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#28236]
Seen on PR builder on coreos-stable20160622-image:
```
Jun 29 03:47:01 localhost kubelet[1478]: I0629 03:47:01.899939    1478 config.go:384] Receiving a new pod "pod-configmaps-236673d0-3dac-11e6-afb9-42010af000bd_e2e-tests-configmap-lvi9i(2366905e-3dac-11e6-a91f-42010af000bd)"
...
Jun 29 03:57:01 localhost kubelet[1478]: I0629 03:57:01.194879    1478 kubelet.go:2528] SyncLoop (ADD, "api"): "pod-configmaps-236673d0-3dac-11e6-afb9-42010af000bd_e2e-tests-configmap-lvi9i(2366905e-3dac-11e6-a91f-42010af000bd)"
```

In the time it took for the SyncLoop to run, the test timed out, which caused a cascade of other issues. It also looks like the Kubelet never received the delete event, and instead continues to attempt to sync the pod with errors like:
```
Jun 29 03:59:35 localhost kubelet[1478]: I0629 03:59:35.191684    1478 status_manager.go:406] Pod "pod-configmaps-236673d0-3dac-11e6-afb9-42010af000bd" (2366905e-3dac-11e6-a91f-42010af000bd) does not exist on the server
```

Full test logs [here](https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26470/node-pull-build-e2e-test/12526/artifacts/tmp-node-e2e-07fa3128-e2e-node-coreos-stable20160622-image/)

**Comment by euank** [comment]
From kern logs: `Jun 29 04:21:20 localhost kernel: unregister_netdevice: waiting for vethfcfaeac to become free. Usage count = 1`

This is a dupe of #27498

**Comment by timstclair** [comment]
Thanks!
