### ISSUE TITLE
Allow reusing api deep copy functions without having to register all of them

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#28235]
Right now, federation-apiserver depends on `pkg/api` (https://github.com/kubernetes/kubernetes/blob/2127a40596dfc08dfe95ed1a76034d00d17ef66e/federation/apis/core/deep_copy.go#L20) to reuse some of the deep_copy_generated funcs related to Service. As a side effect of that dependency, deep copy functions for _all_ v1 api resources are registered to the schema automatically: https://github.com/kubernetes/kubernetes/blob/ec518005a89ea0b2094f3ae3e565eaa30816d8ce/pkg/api/deep_copy_generated.go#L35.
This is unnecessary. We need to register only the service functions in federation-apiserver.

As a result of this, https://github.com/kubernetes/kubernetes/blob/2127a40596dfc08dfe95ed1a76034d00d17ef66e/federation/apis/core/deep_copy.go is useless.

One way to fix this will be to move the code that auto registers deep copy funcs out of pkg/api into a sub package (similar to `pkg/api/install` or maybe reuse the same?).

cc @kubernetes/sig-cluster-federation @kubernetes/sig-api-machinery @thockin

**Comment by nikhiljindal** [comment]
Its not just deep copy funcs, auto generated conversion funcs have the same problem. They are also all auto registered just by depending on `pkg/api`: https://github.com/kubernetes/kubernetes/blob/ec518005a89ea0b2094f3ae3e565eaa30816d8ce/pkg/api/deep_copy_generated.go#L35.

To fix it, we should generate an addDefaultingFuncs() method instead of generating the init() method.
We can then call that method from AddToSchema() (https://github.com/kubernetes/kubernetes/blob/dae5ac482861382e18b1e7b2943b1b7f333c6a2a/pkg/api/v1/register.go#L30) which is called only if someone explicitly depends on `pkg/api/install`.

**Comment by thockin** [comment]
What is the optimization you're making here?  Is it that you don't want to
link all the copy functions?  Or is there some downside to having copy
functions registered that you don't need?

Manually maintaining a subset of functions is tricky - you need the full
set of functions for all transitively used types, which you'd have to
manage on your own.  Or you can just register "all".

**Comment by lavalamp** [comment]
Let's revisit this after I get my fixes re: this setup stuff in.

**Comment by sttts** [comment]
With static deep-copy no registration is necessary anymore. Closing.
