### ISSUE TITLE
Back federation etcd with persistent storage

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#28248]
As mentioned in kubernetes/kubernetes.github.io#662, the federation etcd will lose its state any time the pod dies, unless we modify `federation/manifests/federation-apiserver-deployment.yaml` to add a PVC.

We'll also need to create a PV *and* modify the turnup script to create the backing volume in the cloud provider.

@kubernetes/sig-cluster-federation

**Comment by mml** [comment]
@erictune FYI I believe this is a showstopper.

**Comment by mml** [comment]
OK.  @thockin implied I could use `volume.alpha.kubernetes.io/storage-class` to get this provisioned on-demand.  AFAICT, [this is enabled by default](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/options/options.go#L79), and since it makes our life easier I am trying to get this to work in my test cluster, but so far no joy.  Any obvious mistake?

```yaml
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.alpha.kubernetes.io/storage-class: gce
    creationTimestamp: 2016-06-30T00:50:46Z
    name: etcd-claim
    namespace: federation
    resourceVersion: "6129"
    selfLink: /api/v1/namespaces/federation/persistentvolumeclaims/etcd-claim
    uid: ae7ff126-3e5c-11e6-8c46-42010af00004
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    volumeName: etcd-pv
  status:
    phase: Pending
```

**Comment by mml** [comment]
I needed to not specify a `volumeName`.

**Comment by thockin** [comment]
whew!
