### ISSUE TITLE
Idea: explore iptables NFQUEUE to inject PROXY headers

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#28244]
I am not sure this is possible, but it is intriguing.  We can capture some packets in iptables with the NFQUEUE target, and process them in userspace with something like https://git.netfilter.org/libnetfilter_queue/.  If we capture the start of a TCP session, could we inject a PROXY protocol (http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt) header?  This would be an option, obviously.

**Comment by ohmystack** [comment]
Good idea.
Many people don't agree about using iptables to manage service-endpoint relationships in production. One of the reasons is that, the iptables will become huge when there are lots of services and endpoints. 
Now, using iptables with NFQUEUE seems to be a good choice.
`kube-proxy` can handle the packet in iptables NFQUEUE according to the service-endpoint mapping info from apiserver, and change the DestIP/SourceIP of the packet.
By now, the disadvantage of using NFQUEUE is that the packet will be transfered between kernel and userspace twice before leaving the host.

Is this idea still in consideration? I'm looking forward to more reviews on it.

**Comment by thockin** [comment]
We have seen examples of other projects using NFQUEUE so we know it is
possible, but it's complicated.  I'm not really in favor of this idea any
more...

**Comment by ohmystack** [comment]
Thanks, @thockin . I also prefer the simple solutions.
One more question, I'm just curious. Could you share us some best practice about how does Google handle countless containers' IPs behind a service VIP? How to route from vip(service) to ip(container). Is it powered by SDN flow tables? Or, is the service only possible on DNS level, not IP level? (Maybe iptables solution is too light for Google's case.)

**Comment by thockin** [comment]
Internally we don't use a VIP for this stuff, we have our own port
brokering and service discovery.  That all predates things like namespaces.

**Comment by thockin** [comment]
I'm going to close this.  I don't think we want it.
