### ISSUE TITLE
Fedora 20 instructions appear to be out of date...

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#2824]
@eparis can you take a look at:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/fedora/fedora_manual_config.md

We had a user on IRC mentioning some problems wrt to the kubelet and the --api_servers flag.

**Comment by asalkeld** [comment]
Can we close this issue (Fedora is now up to 24 and the docs seem to have --api-server)
see: http://kubernetes.io/docs/getting-started-guides/fedora/fedora_manual_config/

**Comment by cloudtrov** [comment]
Yes, please. The document seems to cover the steps.
