### ISSUE TITLE
Verify device is unmounted before detach via open O_EXCL

### ISSUE THREAD

**Issue by matchstick** [kubernetes/kubernetes#28252]
@kubernetes/sig-storage  @thockin 
Kubernetes requires that volumes are unmounted in all mount namespaces before letting the system know that it is safe to detach. While the kernel provides a simple technique for ext4 (namely seeing if /sysy/fs/ext4 has any entry for the mounted filesystem) this is not a portable solution. 

Luckily there is a portable solution. We can use the O_EXCL flag. From the [open(2) man page](http://linux.die.net/man/2/open) 

```
O_EXCL
Ensure that this call creates the file: if this flag is specified in conjunction with
O_CREAT, and pathname already exists, then open() will fail.

When these two flags are specified, symbolic links are not followed: if pathname is a 
symbolic link, then open() fails regardless of where the symbolic link points to.

In general, the behavior of O_EXCL is undefined if it is used without O_CREAT. There is
one exception: on Linux 2.6 and later, O_EXCL can be used without O_CREAT if pathname
refers to a block device. If the block device is in use by the system (e.g., mounted),
open() fails with the error EBUSY. 
```

We can use this as a check before detaching to ensure the kernel does not have any unexpected mounts on the volume.

**Comment by thockin** [comment]
I tested this on a machine, seems to work.  A simple C program as an
example.

#include <unistd.h>
#include <stdio.h>
#include <sys/fcntl.h>
#include <stdlib.h>

int main() {
int fd = open("/dev/sdb", O_RDONLY|O_EXCL);
if (fd < 0) {
perror("busy");
exit(42);
}
sleep(10000);
return 0;
}

**Comment by eparis** [comment]
Even so, this just makes the race smaller, right? We might still have that instant where a pod mounts it after the open() call?   Unless this `fd` prevents anything using mouting the fs on that block device...

**Comment by matchstick** [comment]
@eparis Hopefully this code is run after we believe the pods have been cleaned up. So the goal here is to have some signal outside of the kubernetes internal code to double check that nothing has a mount after the kubernetes code believes it has been unmounted, or that the cleaning up of a pod did not result in a leak of a mount. 

We should not have a race at this point since we are hoping that when we run this check the pods have been safely deleted.

Mostly it's a way to verify the kernel agrees with the assumptions the code is making.
