### ISSUE TITLE
session affinity services support in federation

### ISSUE THREAD

**Issue by mfanjie** [kubernetes/kubernetes#28276]
@quinton-hoole @nikhiljindal 

One thing need to discuss with you about k8s services.
in single k8s cluster when users define service.spec.sessionAffinity=ClientIP, then the service will be session affinity, means if there are multiple calls from single clientIP, those calls will be redirected to the same pod, so the session context could be reused.

Per my understanding, in k8s, for the case that iptables is enabled, when a service being created, the iptable entry will be write to all nodes, so it is easy to find the target pod and redirect to it.

But if this concept is put to federation level, and if the global dns server is round robin, the service might be redirected to different cluster even sessionAffinity is specified. As a result, the service lost the sessionAffinity capability.

Any comments?

**Comment by quinton-hoole** [comment]
@mfanjie Your analysis is correct.  In practice this is less of an issue that it might seem at first, as clients don't typically perform a DNS lookup for each connection.  They look up an address, and then use it until is stops working.  So between DNS lookups, session affinity will be preserved.  We have some plans to improve upon this in v1.4.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#54.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
