### ISSUE TITLE
Redis HA cluster example persistence 

### ISSUE THREAD

**Issue by Trane9991** [kubernetes/kubernetes#28278]
Hello, 
I'm having an issue with making Redis HA Cluster persistent.
This example https://github.com/kubernetes/kubernetes/tree/release-1.3/examples/redis uses emptyDisk storage. Is it possible to make it work with Google Persistent Volume?

I'm tried to separate redis on 3 pods with volume each, but there is a problem with redis-master(bootstrap pod), where can it take data if need to redeploy cluster?

Thank you.

**Comment by jlowdermilk** [comment]
Check out the redis petset example: https://github.com/kubernetes/contrib/tree/master/pets/redis, which uses persistent volume claims. Feature is alpha in 1.3, will be the way to do stateful apps on kubernetes going forward. @bprashanth, do we have a doc page for petset yet?

**Comment by bprashanth** [comment]
Yes only in github till the release, though: https://github.com/kubernetes/kubernetes.github.io/blob/release-1.3/docs/user-guide/petset.md

**Comment by bprashanth** [comment]
@Trane9991  For a simple master/slave setup see https://github.com/kubernetes/kubernetes/issues/28078#issuecomment-228629148. If you'd like to contribute your sentinel (or any other HA) example, please do so, ask away if you have more questions.

**Comment by Trane9991** [comment]
@bprashanth  @jlowdermilk 
This is very nice feature, but I'm running on the GCE which is 1.2.4 Kubernetes version, and can't try it out :( 
Thank you!

**Comment by krmayankk** [comment]
@bprashanth @Trane9991 i am eagerly waiting for a petset example for redis which does master slave as well as sentinel setup and bootstraps the cluster using petsets and does not require any manual process like creating a bootstrap pod and deleting it later. Would love to see how it would work with petsets and init containers for master, slave and sentinels all in one

**Comment by kargakis** [comment]
Please move to the k8s/examples repo if it's still relevant.
