### ISSUE TITLE
"kubectl scale rs" work confused in pause and unpause deployment.

### ISSUE THREAD

**Issue by chengzhang1016** [kubernetes/kubernetes#28271]
Description of problem:
"kubectl scale rs" work confused in pause and unpause deployment. It should work and have a consistent behaviour in pause/unpause.

Issue 1: Total replicas number will over max.deployment.replicas if scale up rs in unpause.
For example:
I have a Deployment with two RSs:
deployment.replicas = 10
maxSurge=3
maxUnavailabl=2
RS1.replicas = 8
RS2.replicas = 5

Unpause deployment, I will get RS1.replicas=8 and RS2.replicas=9 if I scale up RS2 to 9 replicas( "kubectl scale --replicas=9 rs $RS2). That is confused, there are 17 replicas totally, but max.deployment.replicas=13, we can get below info in deployment yaml file:
```
  spec:
    replicas: 10
  status:
    availableReplicas: 8
    observedGeneration: 4
    replicas: 17
    unavailableReplicas: 9
    updatedReplicas: 9
```

Issue 2: "kubectl scale rs" doesn't work in pause
Same scenario:
I have a Deployment with two RSs:
deployment.replicas = 10
maxSurge=3
maxUnavailabl=2
RS1.replicas = 8
RS2.replicas = 5

Pause deployment, I also want to scale up RS2 to 9 replicas, but result is unchanged and different with in unpause.
Also, no any useful output let user know what happened.
```
# kubectl get rs
NAME                          DESIRED   CURRENT   AGE
nginx-deployment-508933516    8         8         1m
nginx-deployment-2064037328   5         5         52s
# kubectl scale --replicas=9 rs nginx-deployment-2064037328
replicaset "nginx-deployment-2064037328" scaled
# kubectl get rs
NAME                          DESIRED   CURRENT   AGE
nginx-deployment-508933516    8         8         4m
nginx-deployment-2064037328   5         5         4m
```

Furthermore, if I scale up RS2 to 7 replicas, result is RS1.replicas=6 and RS2.replicas=7, the behaviour different with scale up to 9.  Also, only the other RS reduce, that is not reasonable. The controller should notice 2 replicas more while RS2 scale up to 7(+2) if proportionally scale work, and then it should delete 2 more replicas back to the deployment.replicas sets (RS1: 8(-1), RS2: 7(-1)). So, the expect result should be: RS1.replicas=7, RS2.replicas=6

Version-Release number of selected component (if applicable):
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.0.890+ecfd4aa131035a", GitCommit:"ecfd4aa131035a4747cfdf90d89a2fe823341657", GitTreeState:"clean", BuildDate:"2016-06-27T08:34:32Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.0.890+ecfd4aa131035a", GitCommit:"ecfd4aa131035a4747cfdf90d89a2fe823341657", GitTreeState:"clean", BuildDate:"2016-06-27T08:34:32Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by kargakis** [comment]
You are not supposed to scale replica sets for deployments.

cc: @kubernetes/deployment
