### ISSUE TITLE
kubectl exec: -t does not set TERM

### ISSUE THREAD

**Issue by rhcarvalho** [kubernetes/kubernetes#28280]
There is a known Docker issue (docker/docker#9299) that `docker exec -t` does not set `TERM` while `docker run -t` does.

Users run into problems running applications that rely on `TERM` after running `kubectl exec`, e.g.:

``` console
$ kubectl exec -t docker-registry-1-omzrl -- top                                                                   
TERM environment variable not set.
error: error executing remote command: error executing command in container: Error executing in Docker Container: 1
```

A proposed solution is to inherit the value of `TERM` from the environment where `kubectl` is run, or as a last resort default to `xterm`, same value as used by Docker ([docker/docker/container/container_unix.go#L61-L63](https://github.com/docker/docker/blob/cbf785c45a8cca061028ec341320bcbd655cf1fd/container/container_unix.go#L61-L63)).

A "pure shell" equivalent of the solution above is:

``` console
$ kubectl exec -t docker-registry-1-omzrl -- env "TERM=${TERM:-xterm}" top
```

---

Originated at: https://github.com/openshift/origin/issues/7424

**Comment by ncdc** [comment]
This will be resolved automatically once we move to docker 1.13 or later (https://github.com/docker/docker/pull/26461)

**Comment by mc0e** [comment]
Given what @ncdc says, it seems unlikely that a fix would be performed in kubernetes, so perhaps this should close?

**Comment by smarterclayton** [comment]
Closing.
