### ISSUE TITLE
Improve performance of RBAC authorizer for beta

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#28292]
Alpha currently uses a naive implementation to achieve the desired behavior. Would be nice to make some improvements for beta so a possible stable release would have fewer architectural changes.

Caching is a small change that will likely be very beneficial. @liggitt has also brought up that our use of `ConfirmNoEscalation` can also be rethought.[0]

https://github.com/kubernetes/kubernetes/pull/28281#discussion_r69127365

**Comment by liggitt** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/34047
