### ISSUE TITLE
regression: hyperkube kubectl convert broken

### ISSUE THREAD

**Issue by virtuald** [kubernetes/kubernetes#28296]
It seems that this used to work, but something is broken in 1.3.0-beta.2

```
$ docker run --rm -it gcr.io/google_containers/hyperkube-amd64:v1.2.5 /bin/bash
$ /hyperkube kubectl convert
running in local mode...
```

```
$ docker run --rm -it gcr.io/google_containers/hyperkube-amd64:v1.3.0-beta.2 /bin/bash
$ /hyperkube kubectl convert
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

I've tried specifying the `--local` flag explicitly and various combinations of flags, and it doesn't seem to make any difference.

**Comment by virtuald** [comment]
Aha, the problem is that the extended API functionality is called, which tries to contact the API server.

The workaround is that you can do `--include-extended-apis=false`, but the command should force it to false (or give an error if it's true) if `--local` is specified.

**Comment by errordeveloper** [comment]
I think this is a bug in `kubectl set image`.

**Comment by errordeveloper** [comment]
/close

Closing because this refers to 1.3, and we are on 1.10 cycle now, a lot has changed. Please re-open if this is still an issue.
