### ISSUE TITLE
Docker remote api not working for rc created using kubernetes

### ISSUE THREAD

**Issue by rchandh** [kubernetes/kubernetes#28301]
I have created a kubernetes cluster yesterday and I am using docker remote api to get performance metrics of containers by listening to unix:///var/run/docker.sock of each container.
With kubernetes cluster, I ran spark using the .yaml files available in kubernetes/examples/spark.
When i query stat using docker remote api for all the spark containers, I am getting 
HTTP/1.1 200 OK
Content-Type: application/json
Server: Docker/1.10.3 (linux)
Date: Thu, 30 Jun 2016 18:07:11 GMT
Content-Length: 0
for spark-workers and spark-master containers. But I can query data for gcr.io/google_containers/pause:2.0 successfully. This is not specific to spark. I tried to launch different replication controllers like elastic search using kubernetes. In all the cases, I can get only the data for gcr.io/google_containers/pause:2.0 and not for other containers. 
Few weeks back, I was able to get metrics for all containers. But now I can't get for all. Is it because of any recent changes made to kuberentes?
If I launch spark containers manually without using kubernetes, it works. But is it not working when launched using kubernetes.

**Comment by dims** [comment]
This seems legit problem as i am able recreate it:

```
docker run --name docker-nginx2 -p 8889:80 nginx
kubectl run nginx-pod2 --generator=run-pod/v1 --image=nginx --hostport=80 --port=80 --expose
```

then run `docker status` shows:
```
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O               BLOCK I/O           PIDS
7fb356979c90        10.87%              69.32 MB / 16.69 GB   0.42%               126.1 MB / 5.256 GB   0 B / 0 B           12
4cf5b30551df        0.00%               36.86 kB / 16.69 GB   0.00%               144.3 MB / 374.5 MB   0 B / 0 B           1
f6f746af957a        0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B           0
f387d62ecbfc        0.00%               1.52 MB / 16.69 GB    0.01%               97.2 MB / 248.9 MB    0 B / 0 B           2
```

where `docker ps` is as follows:
```
f387d62ecbfc        nginx                                      "nginx -g 'daemon off"   24 minutes ago      Up 24 minutes       443/tcp, 0.0.0.0:8889->80/tcp   docker-nginx2
f6f746af957a        nginx                                      "nginx -g 'daemon off"   27 minutes ago      Up 27 minutes                                       k8s_nginx-pod2.9b9d32f5_nginx-pod2_default_43440df4-47c6-11e6-b994-408d5ca94602_0436b1e3
4cf5b30551df        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 27 minutes ago      Up 27 minutes       0.0.0.0:80->80/tcp              k8s_POD.6cfd0339_nginx-pod2_default_43440df4-47c6-11e6-b994-408d5ca94602_c17742ea
7fb356979c90        google/cadvisor:latest                     "/usr/bin/cadvisor -l"   About an hour ago   Up About an hour    0.0.0.0:8081->8080/tcp          cadvisor
```

Note that `f6f746af957a` is the nginx started using kubectl and it has no data at all in `docker status`.

I was able to run `ab` (Apache Bench) to drive some load `ab -n 100000 -c 100 http://localhost:80/` and noticed that the network (`NET I/O`) goes up for 4cf5b30551df (`"/pause"` container) but all the data for `f6f746af957a` stay pegged to 0.

**Comment by dims** [comment]
@vishh any ideas? please see my observations above

**Comment by vishh** [comment]
@dims I don't think we test `docker stats` integration. @rchandh can you get metrics via kubelet instead - `http://localhost:10255/stats/summary`?

**Comment by vishh** [comment]
@dims If you want to solve this, I'd look at libcontainer code and see why docker fails to collect stats...
