### ISSUE TITLE
Accounting and feasibility for opaque integer resources in the API server and scheduler.

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes/kubernetes#28312]
_Note: Relates to issue [#28310: Discovering, bookkeeping and isolating platform resources other than CPU time and main memory.](https://github.com/kubernetes/kubernetes/issues/28310)_

_See also: [#28311: Hardware feature discovery to add node labels with a unique prefix (e.g. `scheduler.alpha.intel.com/<feature-name>`).](https://github.com/kubernetes/kubernetes/issues/28311)_

This issue tracks work related to opaque counted (integer) resources.

Many opaque resources have a shareable capacity and can’t be represented well as a label. An “opaque integer resource” mechanism could work for these resources.

**What are some example use cases for opaque integer resources?**
- LLC (last-level cache) allocation.
- GPU devices
- FPGA devices
- MICs (Many-Integrated Core, such as Xeon Phi)
- “Slots” for sharing bandwidth to a parallel file system.

**Who discovers and publishes these opaque node resources?**
- Option 1: A sidecar pod running on every node publishes capacity in `NodeStatus.{Capacity,Allocatable}`
- Option 2: Kubelet discovers and publishes capacity in `NodeStatus.{Capacity,Allocatable}`

**How would opaque integer resources be accounted?**

The scheduler could compute the free resource amount by deducting the sum of requests from capacity, for use in pod feasibility checks. This is similar to the existing code paths for cpu time and memory resources.

For user experience and possibly scheduling we may want to report usage in addition to capacity (for resources where usage can be <= the allocated amount). This could be handled via the Heapster/metrics API.

cc @davidopp @balajismaniam

**Comment by davidopp** [comment]
cc/ @kubernetes/sig-scheduling

**Comment by davidopp** [comment]
ref/ #19082

**Comment by erikstmartin** [comment]
I have an additional use case:

When `CONFIG_RT_GROUP_SCHED` is enabled in the kernel it requires `cpu.rt_runtime_us` to be given to each container's cgroup. I have a PR with docker to add support to set the container runtime when it's created https://github.com/docker/docker/pull/23430. This will require updates to the scheduler.

From a generic perspective the amount of runtime can be retrieved by looking at docker's cgroup value and could work with the proposed solution. There is additional complexity though, as more RT tasks are scheduled onto a system it increases the likelihood of degraded performance for normal priority tasks that are scheduled onto the same system.

**Comment by ConnorDoyle** [comment]
cc/ @nqn

**Comment by ConnorDoyle** [comment]
A preliminary design doc for this feature is here: https://goo.gl/iJW2yq

**Comment by ConnorDoyle** [comment]
Created an issue in the features repo for this: kubernetes/features#76.

**Comment by ConnorDoyle** [comment]
@erikstmartin, regarding your SCHED_RT use cases, are you open to the idea of dedicated nodes that are brought up in a special mode optimized for low latency tasks? Mainly folding you into the convo cc @jeremyeder (maybe you can suggest a more relevant issue to discuss it).

**Comment by jeremyeder** [comment]
@erikstmartin cpuset design proposal will be submitted this week, includes RT in design.

**Comment by davidopp** [comment]
@jeremyeder please cc @kubernetes/sig-scheduling when you submit the cpuset design proposal

**Comment by erikstmartin** [comment]
@ConnorDoyle @jeremyeder Excellent! Looking forward to seeing the proposal. For my specific use case, dedicated nodes for RT tasks would be fine.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @ConnorDoyle @jeremyeder @davidopp

**Comment by timothysc** [comment]
Initial alpha for this is in (#31652), so closing this issue.

**Comment by erikstmartin** [comment]
@jeremyeder did the cpuset proposal make it in? Where can I find it, i'm interested in taking a peek at the RT design

**Comment by jeremyeder** [comment]
@erikstmartin No, there needs to be a discussion (project-wide) about what sophisticated resource management looks like in Kubernetes.  Issues like this one have become a forcing-factor to do that design and planning.
