### ISSUE TITLE
kubectl: jsonpath is not very intuitive 

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#28314]
As a user, I want to see a list of (for example) pods and their imageIDs.

There are some hacks.

I think I could use jq to get one columns:  `kubectl get pods -ojson | jq .items[].status.containerStatuses[].imageID`

I think I could learn jsonpath: kubectl get pods -o jsonpath='{.items[*].status.containerStatuses[].imageID}'

But tying this back to a particular pod is hard.

I would really like to do something more like:  `kubectl get pods --columns name, imageID`

**Comment by AdoHe** [comment]
@kubernetes/kubectl

**Comment by deads2k** [comment]
I don't speak jsonpath, but with a golang template:
`kubectl get secrets -o go-template='{{ range .items }}{{ .metadata.name }}    {{ .type }}{{ "\n" }}{{ end }}'`

**Comment by smarterclayton** [comment]
I would like a columns syntax as well, which is thought we had already.

**Comment by justinsb** [comment]
Thanks @deads2k for the tip on golang templates - that is easier.

@smarterclayton aha - you are right - we have custom columns: http://kubernetes.io/docs/user-guide/kubectl-overview/#custom-columns

`kubectl get pods  -o=custom-columns=NAME:.metadata.name,RSRC:.metadata.resourceVersion`

Though this is not listed in the help:
```
  -o, --output="": Output format. One of: json|yaml|wide|name|go-template=...|go-template-file=...|jsonpath=...|jsonpath-file=... See golang template [http://golang.org/pkg/text/template/#pkg-overview] and jsonpath template [http://releases.k8s.io/release-1.2/docs/user-guide/jsonpath.md].
 ```

I think it would also be nice to accept `NAME` to mean `NAME:..metadata.name` (even if we only have shortcuts for the columns that show by default).

As penance for not reading the docs I will look at least at adding custom-columns into --help text.

**Comment by smarterclayton** [comment]
Heh, if you have to read the docs to figure it out the feature
obviously isn't "done".

**Comment by dims** [comment]
@justinsb May i submit a PR? (adding custom-columns into --help text)
