### ISSUE TITLE
Support for isolating opaque resources.

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes/kubernetes#28313]
_Note: Relates to issue [#28310: Discovering, bookkeeping and isolating platform resources other than CPU time and main memory.](https://github.com/kubernetes/kubernetes/issues/28310)_

Perform extra isolation actions in the Kubelet based on pod annotations for pod lifecycle events: `pre-start`, `post-start`, `update`, `termination`. Lifecycle events except `pre-start` could conceivably be hacked around with polling at the cost of latency, extra code, and server load. Extra actions for lifecycle events could be encoded using annotations (for a first pass). These annotations could be added to incoming pods by the API server, via a custom admission controller. Examples of extra actions:
- `pre-start`: Decorate `docker run` command (rkt/hyper equivalent) to add device flag so that the cgroup can get set up properly, mount additional stuff from host like drivers, debug tooling, etc.
- `post-start`: Any isolation mechanism not yet supported by the container runtime interface that depends on having a process ID in hand (e.g. [Intel RDT](http://www.intel.com/content/www/us/en/architecture-and-technology/resource-director-technology.html)).
- `update`: Adjusting cache allocation in response to a new request value.
- `termination`: Cleanup actions to “release” resources.

“Isolation extenders” might want to modify  configuration for a container before it is handed off to the container runtime.

cc @davidopp @balajismaniam

**Comment by davidopp** [comment]
@kubernetes/sig-node

**Comment by vishh** [comment]
https://github.com/kubernetes/kubernetes/pull/25899 introduces the ability to create new runtimes or possibly wrappers to existing runtimes. It should be fairly straightforward to isolate other resources.

**Comment by ConnorDoyle** [comment]
#140 also discusses lifecycle hooks.

**Comment by ConnorDoyle** [comment]
Hey @vishh I took a look at the new interfaces. Is your suggestion that to isolate a new resource, we could wrap one of the existing runtimes, forward all calls to that backing implementation, and do extra logic in e.g. `ContainerRuntime::Start` and `ContainerRuntime::Stop`? (and amend `container.PodSandboxResources` to represent other resource types.)

**Comment by vishh** [comment]
@ConnorDoyle Yeah. A simple wrapper will work for container level isolation. 
@dubstack is working on introducing pod level cgroups and adding a simple policy to enforce QOS at the pod level. To avoid having to recompile kubelet, we will have to come up with a plugin based interface for pod level cgroups.

**Comment by ConnorDoyle** [comment]
Started working on design for this feature here: https://goo.gl/iLepbC

**Comment by ConnorDoyle** [comment]
Closing; this is mostly covered by the device plugin system.
