### ISSUE TITLE
Hardware feature discovery to add node labels with a unique prefix (e.g. `scheduler.alpha.intel.com/<feature-name>`).

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes/kubernetes#28311]
_Note: Relates to issue [#28310: Discovering, bookkeeping and isolating platform resources other than CPU time and main memory.](https://github.com/kubernetes/kubernetes/issues/28310)_

This issue tracks work related to discovering binary (present/absent) hardware platform features.

All processors are not the same, and some workloads exhibit different performance characteristics based on whether certain hardware accelerators are available on the platform. A few examples of these (Intel) accelerators are:

- AES-NI (AES New Instructions, for encryption)
- TSX (Transactional Synchronization Extensions, for alleviating lock contention)
- AVX (Advanced Vector eXtensions, for single-instruction, multiple-data (SIMD))
- BMI (Bit Manipulation Instruction Set)
- MPX (Memory Protection eXtensions, for fast bounds checks)

**Labels and conventions**

The existing mechanisms in the API server are sufficient for labeling nodes to indicate what features are available. However, in order to consume these labels users need to know what to look for. By convention, labels created by the system have some well-known prefix loosely based on domain names owned by an org, for example, `scheduler.alpha.kubernetes.io/...`. For vendor-supplied discovery, each vendor could claim a unique prefix. We suggest `scheduler.alpha.intel.com/...` for labels published by Intel-provided discovery. A catalog of label keys could be published along with the discovery code (either in an external repository or in-tree in `/contrib`).

**Who publishes labels for nodes?**

Platform vendors can provide code (or even publish container images) for local discovery. Discovery could be configured to run as a one-shot job or as a long-running pod using existing Kubernetes mechanisms.

cc @davidopp @balajismaniam

**Comment by davidopp** [comment]
@kubernetes/sig-scheduling

**Comment by davidopp** [comment]
ref/ #19082

**Comment by timothysc** [comment]
Discovery should be on initialization either native or as an add-on as part of the cluster boot strapping process.  I'm not entirely keen on the name-spaced labels vs. more generic mechanics where applicable.

**Comment by davidopp** [comment]
> I'm not entirely keen on the name-spaced labels vs. more generic mechanics where applicable.

Can you explain what you mean? We'd like to avoid "endorsing" one particular partner, especially at the early stages of their work, so having an "intel" label namespace for this stuff seems like a good idea to me.

**Comment by timothysc** [comment]
Depends on whether the HW in question is more generally applicable, or fungible, to other vendor solutions.  If not, then it makes perfect sense to label as "intel".

**Comment by davidopp** [comment]
"intel" isn't intended to refer to the hardware vendor (though presumably they care more about Intel hardware than non-Intel hardware), it's intended to refer to who wrote the software module that is populating the labels. you could imagine someone else in the community doing something where they populate slightly different labels based on discovering the same hardware; we'd put those in a different namespace.

**Comment by timothysc** [comment]
> it's intended to refer to who wrote the software module that is populating the labels 

Couldn't that be problematic when taken to (N+1) in the case of overlapping labels?  

VendorA.label 
VendorB.label 
... 

I'd perfer vendor label to apply more specifically to the non-fungible resource, than to who wrote the "add-on".

**Comment by ConnorDoyle** [comment]
Hey @timothysc, I've talked about that exact question with some other folks who contributed to the OpenStack glance metadata APIs [link](http://docs.openstack.org/developer/glance/glancemetadefcatalogapi.html). The main idea there is to enable software of diverse provenance to interoperate by sharing some data representations. Is something like that what you have in mind?

For this issue, labels seem like a good v1 approach. The general contract as I understand it is that labels are opaque to the core system (Kubernetes promises never to attach special meaning to a particular label, but your k8s-adjacent code may).

Would you be willing to address the metadata governance question in a separate issue? It's definitely relevant but IMO isn't necessarily a blocker for a first phase.

**Comment by therc** [comment]
When do we declare label bankruptcy and turn some of them from binary values into sets? My nodes already have six standard labels today. If we turn only a quarter of the CPUID feature bits into individual labels, it's going to be a long list, with obvious UX implications. Even if we make the cluster admin pick the subset of features they care about, there's still a lot of noise for the user vs. actual signal. This would require, of course, some support for set arithmetic and manipulation in both the command line and the API objects (e.g. a new `has` operator for the label selector that can deal with comma-separated values).

In addition to the CPU, we also care about discovering GPU vintage and features, such as half-precision FP16 support, something I'd be happy to help with, so label proliferation is not a theoretical.

That said, for our purposes one-shot discovery would work, as long as it can be re-triggered on demand when e.g. we start caring about distinguishing AVX machines from the rest.

**Comment by davidopp** [comment]
I think we should avoid making label values be CSV or other structured data. We can perhaps figure out a way to do the namespacing so that users can hide labels from namespaces they don't care about.

**Comment by timothysc** [comment]
Just for clarity, I'm ok with the 1st iteration being pure vendor.scoped.labels, then over time, refining where needed.  I just wanted to make certain we talked about it, b/c when taken to an extreme,  as @therc points out, we could reach a point of "label bankruptcy".  

This will become a broader discussion over time in the on-prem use cases.  /cc @derekwaynecarr @jeremyeder

**Comment by jeremyeder** [comment]
@therc we're already deep in the red :-)

Here's what I'd propose.  The concept of a cell (bikeshed the name...)

Labels are dynamically adjusted per the system/node capabilities "fleecing pod" as per @ConnorDoyle proposal.  Next is how to express that in a way that keeps the UX under control.

Propose to de-couple into two parts; one being sort of a cluster administrator job -- defining what a cell contains.  It could be a logical group of nodes.  A cell could be exclusive or there could be overlap.  Not sure how else to describe it, but **a cell might be described as a cgroup controllers for datacenters.**

And so the admins would define a cell such as this below, which is the union of labels that the fleecer pod applies to a node, and that are well defined:

```
kind: Cell
apiVersion: v1
metadata:
    name: prod-trading
    daemonset: tunedaemonset
    annotations:
            psap.server.kubernetes.io/model: XYZ1234
            psap.network1.kubernetes.io/name: mgmt
            psap.network2.kubernetes.io/name: backup
            psap.network3.kubernetes.io/name: prod
            psap.passthrough.kubernetes.io/name: /dev/sdd,eth2
            psap.cpuset.mems.kubernetes.io/nodes: 1,exclusive
            psap.cpuset.cpus.kubernetes.io/cores: 2,4,6-11
            psap.memory.hugepages.kubernetes.io/hugetlb.2MB.
            psap.kernel.kubernetes.io/module: nvidia,onload
            psap.kernel.kubernetes.io/version: >= 3.10.0-229
            psap.tuned.kubernetes.io/profile: network-latency
```

And then ... the UX for a developer is very simple...just specify what cell you want to run on:

```
kind: Pod
apiVersion: v1
metadata:
    mame: matching-engine
    cell: prod-trading
    annotations:
            psap.kernel.kubernetes.io/ulimit: n:1048576
```

I should also say that @ConnorDoyle proposal covers over 90% of what we're envisioning, but there's at least one missing piece.  A long-running daemon that ensures a node is "fit for service".  Concept I'm calling in my head "extended-node-fitness".

In RHEL we have a daemon called "tuned" which handles system tuning based on workload.  Tuned has a "verify" verb that goes through and ensures desired state matches what's in place.  To avoid sprawl of infra pods/daemonsets I was thinking we could let this pod be long running and have the fitness test (in our case tuned) run.

There would need to be a call-back from this pod to the Kube scheduler if the fitness test ever failed (let's say, a rogue admin ssh'd in and flipped a few tunables that conflict with application needs).  The tuned pod would inform the scheduler that it's out of sync and take some action:

* re-enable the tuning
* evict the node from the cluster
* make it unschedulable or drain it
* shut the node down hard
* whatever else the app needs

Now ... I have a set of proposals and use-cases that center around delivering this and several other associated features.  I'd love to talk with folks at KubeCon about it in more depth!

Interested in thoughts from @erictune if you have a minute.

**Comment by ConnorDoyle** [comment]
@jeremyeder thanks for bringing up the next step, which is as you've pointed out, to help users match up workloads with on-node config/features.

The initial (simplest) parts of this are implemented in the incubator project [node-feature-discovery](https://github.com/kubernetes-incubator/node-feature-discovery.git). Support for named machine profiles could fit well there. If cell names could be encoded in labels, then users can already target them with the existing node affinity annotation. We'd welcome users/contributors in that project if you find the first part useful. (If it's not useful yet, please let us know why not!)

**Comment by vikaschoudhary16** [comment]
@jeremyeder +1 for cells. Additionallly, I think it would be helpful if api is available for user to compose a cell using kv pairs (capabilities) she thinks are desrired for her workload. Different cells could be composed for different workloads over same nodes and then accordingly mentioned in pod spec.

thoughts?

**Comment by vikaschoudhary16** [comment]
Wondering what could be the concerns if we trigger node-feature-discovery when a cell is composed to discover nodes with capabilities mentioned in the cell and labelling nodes with cell names.

**Comment by ConnorDoyle** [comment]
@vikaschoudhary16 and @jeremyeder closing this issue since the original scope is satisfied by the node-feature-discovery incubator project. Let's continue the discussion of cells over there (created [nfd-32](https://github.com/kubernetes-incubator/node-feature-discovery/issues/32) to track it).
