### ISSUE TITLE
Kubelet on a node dead right before pod is created and assigned to that node cause pod disappear on apiserver

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#28318]
The steps to reproduce the issue, on a working gce cluster
1. Choose a node, edit /usr/sbin/kubelet-checker.sh, change sleep time to a large number (600s)
2. Create a pod and make sure it is assigned to the node you chose in step 1
3. kill kubelet process (kubelet process will be restarted automatically after > 5mins )
4. Check pod status, at the beginning, it is ContainerCreating/(or pending), after a few mins, it disappears (kubectl get pods no long shows it)

**Comment by yujuhong** [comment]
This is working as intended.

- Node controller detects that the node has been inactive for > 5 minute, and evicts/deletes all pods assigned to the node.
- The pods are not managed by a replication controller/set, so no new pods will be created.
