### ISSUE TITLE
Discovering, bookkeeping and isolating platform resources other than CPU time and main memory.

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes/kubernetes#28310]
## Overview

Users may want to schedule pods based on additional resources beyond the dimensions that Kubernetes already accounts and isolates. Any attempt at static enumeration would be incomplete, so this proposal discusses a plan for _discovering_, _bookkeeping_, and _isolating_ custom resource types.
### Discovery

Discovery involves enumerating available features and resources on the node so they are available to the scheduling coordinator (in Kubernetes, the API server and scheduler). This may involve being opinionated about how to represent the features.
### Bookkeeping

Bookkeeping or _schedulability_ captures making the user aware of the available features and allowing them to target their workload against nodes that have specific features. For Kubernetes, this includes the ability to target pod placements to nodes that meet certain criteria.
### Isolation

Isolation, or enforcing allocations, may range from simply ensuring exclusive access to a resource for a task, to fine-grained sharing between co-located tasks. For devices like FPGAs, MICs and GPGPUs, the user may want exclusive access. Features that offer a sharable capacity, such as Intel CAT, need to be accounted accordingly while actuating the necessary mechanisms to ensure that utilization does not exceed the allocated limits.
## Proposal

For a more in-depth discussion of the requirements, mechanisms and proposed changes please refer to (and also comment/edit) this shared document: [goo.gl/FjOkIe](https://goo.gl/FjOkIe).

After discussing and solidifying the ideas outlined in the document, we can add them to the `docs/proposals` and/or `docs/design` directories. Advice from maintainers on what belongs where is welcome.
## Upstream work items
- [#28311: Hardware feature discovery to add node labels with a unique prefix (e.g. `scheduler.alpha.intel.com/<feature-name>`).](https://github.com/kubernetes/kubernetes/issues/28311)
- [#28312: Accounting and feasibility for custom integer resources in the API server and scheduler.](https://github.com/kubernetes/kubernetes/issues/28312)
- [#28313: Support for isolating custom resources.](https://github.com/kubernetes/kubernetes/issues/28313)

See also [#28315: Online resource oversubscription and external QoS control](https://github.com/kubernetes/kubernetes/issues/28315)

cc @davidopp @dchen1107 @balajismaniam

**Comment by davidopp** [comment]
cc/ @kubernetes/sig-scheduling @kubernetes/sig-node

**Comment by davidopp** [comment]
ref/ #19082

**Comment by ConnorDoyle** [comment]
We can close this one. The initiative to make Kubernetes resource management more extensible is well under way by now.
