### ISSUE TITLE
kubectl should provide better error message when validation failed

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#28321]
I found many users confused when they see this error message:

```
error validating data: <some error messages>; if you choose to ignore these errors, turn validation off with --validate=false
```

For most of them, the command just failed, and they don't know how to move on.  

We should provide better error message, and communicate better what they should do next. 

@kubernetes/sig-cli-feature-requests

**Comment by xingzhou** [comment]
@janetkuo, I'm investigating the issue.
On my laptop, I tried ```cluster/kubectl replace -f temp.json``` and can get the following error:
```
error validating "temp.json": error validating data: kind not set; if you choose to ignore these errors, turn validation off with --validate=false
```

do you think if we can change the error message to:
```
error validating "temp.json":
    cause: can not find field "kind" in the provided data.
    possible solutions:
        1. Add a valid "kind" field into data and retry.
        2. Turn validation off with '--validate=false' to ignore this error.
```

Also, I can see that there are several commands in kubectl that can print this error, we can design a consistent format to show this kind of error message, your thoughts?

**Comment by AdoHe** [comment]
@xingzhou this looks like a good beginning, but I would expect this to be more generic, validation is widely used in kubectl, I would expect that this kind of validation error is handled. You can see [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource/visitor.go#L206), [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource/visitor.go#L206), and [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource/visitor.go#L206) for more info.

**Comment by xingzhou** [comment]
yes @AdoHe, do you think if we can create a new type of Error like:
```
type ValidationError struct {
       RootCause string
       Actions       []string
}
```
and various schemas can return the above error to specify the root cause and the followup actions to the validator consumer like [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource/visitor.go#L206). Then all this kind of validation error can have a formatted output message like:
```
error validating "XXX":
    cause: XXX  // the 'RootCause' of ValidationError
    possible solutions:
        1. Action 1. // list the actions specified in 'Actions' of ValidationError 
        2. Action 2. 
        ...
        n. Turn validation off with '--validate=false' to ignore this error. // this can be the default action.
```
Do you think this is ok to solve the issue?

**Comment by smarterclayton** [comment]
We generally try to avoid having newlines in our normal errors.  It's
probably more likely we'd want to implement an interface like
`ExtendedError` or `ErrorWithUsage` that we can check errors for in
`pkg/kubectl/cmd/util#checkErr`.  That keeps generic code from having to
know about the implementation class (ValidationError, in your case)

**Comment by AdoHe** [comment]
@xingzhou please take a look at @smarterclayton comment, I think this is what I want.

**Comment by xingzhou** [comment]
@smarterclayton & @AdoHe, thanks for your comments. Let me take a summary, if I do not get your  points, please correct me:
• We need an interface in ```pkg/kubectl/cmd/util```, named ```ErrorWithAction```, this interface support methods like ```#getCause, #getActions and #addAction```
• Add a new ```ValidationError``` type in ```pkg/api/validation/schema``` which implements interface ```ErrorWithAction``` , then schema can return this kind of error to specify the followup actions.
• in ```pkg/kubectl/cmd/util```, we may need to add a new method to add more actions to error object. E.g. "turn validation off with --validate=false" can be one more action added by kubectl after the validation process by schema.
• The kubectl commands will still use cmdutil.CheckErr to check the error returned by validation process. ```#checkErr``` method can detect the error type ```ErrorWithAction``` and print the cause + followup actions.

for "We generally try to avoid having newlines in our normal errors.", if we add action strings to the output, the message might be too long. Is that ok to break them to several lines? like each action will take 1 line.

BTW, not sure if I can ping you through slack? I guess use slack to communicate might be more efficiency.

**Comment by AdoHe** [comment]
@smarterclayton would you like to give detail expectation here? I think this can help handling validation error more efficiency.

**Comment by gertcuykens** [comment]
kubectl --namespace=default apply -f deployment/production/deployment.yaml
```
...
&{0xc4200e4780 0xc42013c230 default my-api deployment/production/deployment.yaml 0xc42010e5b0 0xc42010ebf8 13401 false}
for: "deployment/production/deployment.yaml": unrecognized type: string
```
Don't know if this is same issue but this is what i get when i do the following lol :D
```
      nodeSelector:
        role-app: true
```
```
      nodeSelector:
        role-app: "true"
```
Not even a line number

**Comment by arikkfir** [comment]
I got the same error as @gertcuykens for the very same reason (using `true` instead of `"true"` in a container's environment variable value. A better error message would go a long way here :smile:

**Comment by Nate-Clark** [comment]
to @arikkfir 's point...  or better yet, just process the boolean value correctly!

**Comment by PontusNyberg** [comment]
Got this today and i would probably not have found the error in at least a couple of more hours. 
flag=true instead of flag="true"

**Comment by nicam** [comment]
> kubectl --namespace=default apply -f deployment/production/deployment.yaml
> 
> ```
> ...
> &{0xc4200e4780 0xc42013c230 default my-api deployment/production/deployment.yaml 0xc42010e5b0 0xc42010ebf8 13401 false}
> for: "deployment/production/deployment.yaml": unrecognized type: string
> ```
> 
> Don't know if this is same issue but this is what i get when i do the following lol :D
> 
> ```
>       nodeSelector:
>         role-app: true
> ```
> 
> ```
>       nodeSelector:
>         role-app: "true"
> ```
> 
> Not even a line number

Which one is correct? :D

**Comment by mitlonik** [comment]
Test! 
$ helm create k8s-helm

$ helm lint k8s-helm/
==> Linting k8s-helm/
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed

$ kubectl apply -f k8s-helm/ --dry-run=client
error validating "k8s-helm/Chart.yaml": error validating data: kind not set; if you choose to ignore these errors, turn validation off with --validate=false
error validating "k8s-helm/values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false

Linter did not reveal any errors, but there are problems with validation. How to be?

Helm launch!

$ helm install --debug --dry-run test-app k8s-helm/
