### ISSUE TITLE
We need a style guide

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#28322]
`gofmt` eliminates a lot of ambiguities, but they still come up.  One example is how we choose to stringify otherwise opaque objects.  That came up in #28134.

The issue relates a bit to usability (debug logs) and developer experience, but it's cross-cutting.

@bgrant0607 for lack of a more obvious target.

**Comment by bgrant0607** [comment]
Thanks, @mml. Yes, we need a style guide. This is "contributor experience".

cc @pwittrock @grodrigues3

**Comment by bgrant0607** [comment]
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/coding-conventions.md

Added this issue to https://github.com/kubernetes/community/wiki/Roadmap:-Contributor-Experience

cc @kubernetes/contributor-experience

**Comment by k82cn** [comment]
+1 for code style; e.g.

```
func serviceErrorHandler(s runtime.NegotiatedSerializer, requestResolver *RequestInfoResolver, apiVersions []string, serviceErr restful.ServiceError, request *restful.Request, response *restful.Response) {
...
}
```

**vs.**

```
func NewPersistentVolumeController(
    kubeClient clientset.Interface,
    syncPeriod time.Duration,
    provisioner vol.ProvisionableVolumePlugin,
    recyclers []vol.VolumePlugin,
    cloud cloudprovider.Interface,
    clusterName string,
    volumeSource, claimSource cache.ListerWatcher,
    eventRecorder record.EventRecorder,
    enableDynamicProvisioning bool,
) *PersistentVolumeController {
...
}
```

**Comment by kargakis** [comment]
Copying a comment of mine from elsewhere regarding not using named return arguments:

If you have a long function that has multiple return arguments and multiple return sites it becomes really frustrating especially for reviewers because you always need to remember the values you are returning.

**Comment by mml** [comment]
Another issue to be addressed: when it's OK to deviate from `if err != nil` to `if err == nil`.

Arose in https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32850#-KRno13tK6QCbUbm3egs

**Comment by kargakis** [comment]
I am a fan of err != nil being the very first check after an error is
returned but there are cases, for example the PR this was brought up, where
you may need different handling for different errors (nevermind that most
if not all of our controllers just log errors atm). Then i think it makes
sense to quickly handle the err == nil case and not add to the
special-cased error handling one level of indentation more ie. readability
is better.

On Friday, September 16, 2016, Matt Liggett <notifications@github.com>
wrote:
> Another issue to be addressed: when it's OK to deviate from if err != nil
to if err == nil.
>
> Arose in
https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32850#-KRno13tK6QCbUbm3egs
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/MZkHtZIsm5rhlB3njT1AkiNGPhHOLUJGn0ncMTZENv749parmr0ZULpXSP1BW3oSigsqVHLkvFiBxcNdxupYix_LnAqachndhsHEdrYZHxw_uojM-MgSh3BC2obQTi8sxuQgB83w98dQeNBoD3BTk6tLDuwFpA=s0-d-e1-ft#https://github.com/notifications/beacon/ADuFf5wr9z1S-tkx3BxpTycGSbdw5NN4ks5qquoogaJpZM4JCtL5.gif>

**Comment by kargakis** [comment]
Grouping of imports should be documented as well. I think in most places we use the follow convention:
```go
import (
// stdlib imports

// third-party imports

// kubernetes imports
)
```

**Comment by jessfraz** [comment]
maybe we could get some members of the go team involved as well
I know some of them are working on an all around Go community style/readability guide

cc @bradfitz @rakyll :innocent:
