### ISSUE TITLE
Cluster Federation e2e tests failing on Jenkins: Invalid value for 'entity.managedZone.dnsName': 'k8s-federation.com', invalid

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#28324]
17:03:25 E0630 23:53:23.712061       1 controllermanager.go:128] Failed to start service controller: googleapi: Error 400: Invalid value for 'entity.managedZone.dnsName': 'k8s-federation.com', invalid

**Comment by quinton-hoole** [comment]
cc: @nikhiljindal @madhusudancs @mml FYI

It seems like k8s-federation.com falls foul of the clouddns golang API parameter validation (even though this works through the clouddns command-line tool).  I'll have to register and use another test DNS zone.

**Comment by quinton-hoole** [comment]
Now I'm confused:

9:49:41 E0701 02:40:49.542354       1 controllermanager.go:128] Failed to start service controller: googleapi: Error 400: Invalid value for 'entity.managedZone.dnsName': 'ubernetes.io', invalid

This works just fine locally.

**Comment by madhusudancs** [comment]
@quinton-hoole I would like to debug this, could you please add me to the GCE project where these jobs run?

**Comment by quinton-hoole** [comment]
@madhusudancs This is in the Jenkins e2e test.  The problem, I suspect, this the lack of a trailing '.' in the DNS name.

http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-federation/

**Comment by quinton-hoole** [comment]
@madhusudancs The GCE project is k8s-jkns-e2e-gce-federation

**Comment by madhusudancs** [comment]
Yeah, likely. Also the managed zone names on the project have a trailing dot (did you add now?).

**Comment by quinton-hoole** [comment]
@madhusudancs No, clouddns adds the trailing dot automatically.
The problem is almost definitely that controller manager is looking for the name without the trailing dot, and can't find it.

**Comment by quinton-hoole** [comment]
@madhusudancs My local setup has the controller manager configured with the trailing dot and it works.  Much appreciated if you could fix the config that get fed through to Jenkins.

**Comment by quinton-hoole** [comment]
Actually @madhusudancs don't worry, I'll sort it out now.

**Comment by madhusudancs** [comment]
@quinton-hoole alright, thanks!

**Comment by madhusudancs** [comment]
@quinton-hoole also, when you do that could you also please revert back this - https://github.com/kubernetes/test-infra/pull/249?

**Comment by quinton-hoole** [comment]
@madhusudancs Yes, done in https://github.com/kubernetes/test-infra/pull/251.

It would be great if you could LGTM that for me now.

**Comment by madhusudancs** [comment]
@quinton-hoole Done.
