### ISSUE TITLE
Creating and terminating pods infinitely when deployment and rc have the same selector

### ISSUE THREAD

**Issue by iT2afL0rd** [kubernetes/kubernetes#28328]
If you have a rc and then create a deployment for the rc(deployment and rc has the sample selector), the cluster will create and terminate pod infinitely.

**Comment by paultiplady** [comment]
I've hit this as well. Think this is a bug -- the observed behaviour when creating a Deployment with the same Selector as an RC is a tight-loop of pod creation and termination, which clogs up the API server and makes the API unresponsive.

Workaround is to orphan the rc pods with `kubectl delete rc --cascade=false <rc-name>`, and then you can create your Deployment (which will create its own pods), and then delete the orphaned pods at your leisure.

Think it would be good to handle this error case a bit more gracefully, and document the correct migration path for RC => Deployment.

**Comment by smugcloud** [comment]
I also ran into this by unknowingly creating multiple deployments with the same selector.  It would be nice to block this scenario if the value overlaps in the same namespace.

**Comment by bprashanth** [comment]
The general problem of overlapping selectors that you're running into is understood and there are (multiple) fixes going on, i believe: https://github.com/kubernetes/kubernetes/issues/19830, https://github.com/kubernetes/kubernetes/issues/2210, https://github.com/kubernetes/kubernetes/issues/22961

**Comment by pwittrock** [comment]
Closing this as a duplicate.  Reopen if needed

**Comment by smugcloud** [comment]
Awesome, thanks @pwittrock @bprashanth
