### ISSUE TITLE
Make node upgrade able to use local binaries

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#28325]
cluster/gce/upgrade.sh -N does not support local binaries. It has to upgrade to an official release.

This means that we cannot do a test of a node upgrade before we cut a release.  For 1.3.0, we had to cut an extra beta release just to have a release tarball on our release site in order to upgrade.

The scripts should be able to use a local build (this is possible for master upgrades already).

**Comment by erictune** [comment]
@david-mcmahon

**Comment by goltermann** [comment]
@pwittrock @david-mcmahon does this need to be fixed before we can test upgrade from 1.3.x to 1.4.hash builds?

**Comment by david-mcmahon** [comment]
This (still) seems fairly important.  I don't know if the bug got in front of the right people though as we haven't seen any movement on it.  Who else is appropriate to add here?

**Comment by goltermann** [comment]
@jfrazelle @davidopp this would be useful so we didn't have to wait on alpha/beta builds.
