### ISSUE TITLE
Clean up node-e2e resources after tests run

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#28320]
We can't currently use the same delete namespaces functionality of the cluster e2e tests since we're not running a controller manager. We should either run the controller manager for the node e2e's, or we should create another mechanism to cleanup after tests.

/cc @vishh @pwittrock @caesarxuchao

**Comment by caesarxuchao** [comment]
There is no way to delete a namespace from the api server if there is controller manager is not running.

**Comment by vishh** [comment]
Huh. Can you elaborate a bit more?

**Comment by caesarxuchao** [comment]
When you delete a namespace, in the storage layer it will not actually delete it from the namespace, it will update the DeletionTimestamp and set the namespace's [finalizer](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L2543). The finalizer field will prevent a naive deletion request from succeeding. The namespace controller will notice the update, deletes all resources in the namespace, and then send an update request to the "finalize" subresource, and finally sends a deletion.
So if you want to delete a namespace without running the controller manager, you will need to send a delete for the namespace, then an update for the "finalize" subresource, and finally a delete for the namespace.
