### ISSUE TITLE
 grafana no pods monitor information

### ISSUE THREAD

**Issue by chowyu08** [kubernetes/kubernetes#28330]
Docker Version - 1.11.2
Kubectl Version - 1.2.4
I create heapster, influxdb, grafana to monitor kubernetes , by kubectl create -f  ./cluster/addons/cluster-monitoring/influxdb
file from :  https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/cluster-monitoring/influxdb
I can access grafana, kube status and influxdb (the latter by appending :http to the url ) ,but I cannot access the heapster (get a 404 ), and the grafana can list node monitor information, and no pods monitor information,why?

pods status is ok
![image](https://cloud.githubusercontent.com/assets/16483518/16549894/84f11dc6-41d6-11e6-8fa0-d2de4294d28e.png)

grafana node monitor is ok
![image](https://cloud.githubusercontent.com/assets/16483518/16549904/b66ab9ac-41d6-11e6-9b5b-1907c912ce15.png)

influxdb maybe right
![image](https://cloud.githubusercontent.com/assets/16483518/16549930/1af0ec84-41d7-11e6-83a8-471e8e61214a.png)

and grafana pods monitor is null ,why?
![image](https://cloud.githubusercontent.com/assets/16483518/16549941/4ee1bcb2-41d7-11e6-9312-0aaee26a51fc.png)

**Comment by devlina** [comment]
I am having same issue. No pods are showing up in pods dashboard.  It can show nodes' metrics under cluster dashboard though.

**Comment by gopinatht** [comment]
Guys, any information on this? I have the exact same issue
