### ISSUE TITLE
Improve kubedns QPS to be closer to GCE DNS server performance

### ISSUE THREAD

**Issue by girishkalele** [kubernetes/kubernetes#28366]
Ran a DNS performance test against the kubedns pod vs the native GCE DNS server.
kubedns performance was only around 10% that of going directly to the GCE DNS at "169.254.169.254".

The single kubedns pod seems to max out at around the same performance as provided by the GCE DNS to each unique IP address. Since all 10 Pods are running the same query-file, we would expect the dnsmasq caching would dramatically speed up performance.

Running against DNS cluster ip 10.0.0.10 is around 109 QPS

```
  Queries per second:   137.991371
  Queries per second:   112.373670
  Queries per second:   97.577085
  Queries per second:   131.381920
  Queries per second:   35.410735
  Queries per second:   136.044372
  Queries per second:   49.806700
  Queries per second:   128.092776
  Queries per second:   133.084200
  Queries per second:   133.843242
```

Running directly against 169.254.169.254 is 1256 QPS

``` console
  Queries per second:   1233.658841
  Queries per second:   1292.178002
  Queries per second:   1204.961019
  Queries per second:   1278.054183
  Queries per second:   1297.116902
  Queries per second:   1209.742660
  Queries per second:   1250.562897
  Queries per second:   1233.336819
  Queries per second:   1303.879214
  Queries per second:   1255.794775
```

Methodology:

2 n1-standard-2 instances as schedulable nodes.
Hairpin_veth mode is on.
1 kubedns pod.
10 DNSPerf client pods running as 10 parallel completions under one "Job".

**Comment by girishkalele** [comment]
cc @bprashanth @thockin @ArtfulCoder

**Comment by thockin** [comment]
It might just be SkyDNS.  Weave also has a DNS server that they claim performs really well.  It's very different, and would be pretty much a rewrite again, but maybe we should consider it medium term?

@errordeveloper

**Comment by girishkalele** [comment]
@thockin Yes, it looks like kubedns/skydns performance is the bottleneck.

Because, even when the queryfile contained only local service records and dnsmasq cache was set to 1, QPS didn't increase a lot. This case should have skydns servicing all requests with no forwarding required.

@ArtfulCoder and I did some more measurements. 

1. Bump up dnsmasq cache size to 64K - the kubedns performance increased to ~ 220 QPS.
2. Query file contains only local service A records ~ 5000 QPS (all dnsmasq-caching)
3. Query file contains only local service A records and dnsmasq cache size = 1 ~ 300 QPS.

Side-Note: Cluster IP vs Endpoint/Pod IP had no visible impact on the QPS.

**Comment by girishkalele** [comment]
@errordeveloper Is there a Docker image with the Weave DNS server that we can drop in and do a test ? It won't resolve service DNS IPs, but we will get an idea of external forwarding performance.

Another option is to use the DNS server built into Consul. There is a new kubernetes/kube2consul project starting up.

https://www.consul.io/docs/agent/dns.html

**Comment by bprashanth** [comment]
> 2 n1-standard-2 instances as schedulable nodes.

What else was sharing that machine? did you try giving it unlimited cpu/memory?

**Comment by girishkalele** [comment]
@bprashanth 

Just the standard set to pods scheduled on minions - they shouldn't have been very busy.
One noticeable thing is that kubedns is logging very verbosely, I am going to build a test container with all that logging removed, I am not sure if the logging framework logs asynchronously or blocks and flushes the log stream synchronously.

**Comment by bprashanth** [comment]
There's a -quiet option
Make sure you aren't maxing out on the 1/10th of a cpu core and how much ever memory that pod manifest gives you on a populated node.

**Comment by bprashanth** [comment]
https://github.com/kubernetes/contrib/blob/master/exec-healthz/exechealthz.go#L43
you should be able to specify that through the "args" field in yaml directly

**Comment by girishkalele** [comment]
@bprashanth Good tip - let me crank up the cpu limits on the DNS containers.

The exechealth -q option is already there - this is the kubedns daemon going crazy printing every query and datastructure like so:

```console
I0701 19:23:27.115855       1 dns.go:583] Received ReverseRecord Request:1.0.0.10.in-addr.arpa.
I0701 19:23:29.114784       1 dns.go:439] Received DNS Request:kubernetes.default.svc.cluster.local., exact:false
I0701 19:23:29.114833       1 dns.go:539] records:[0xc8202b97a0], retval:[{10.0.0.1 0 10 10  false 30 0  /skydns/local/cluster/svc/default/kubernetes/3234633364383235}], path:[local cluster svc default 
```

**Comment by bprashanth** [comment]
you should be able to bring its log level down with --v

**Comment by girishkalele** [comment]
@bprashanth 

Eliminated logs from kubedns and bumped up CPU to 1000m.
Marginally improved QPS from ~ 290 to ~ 341.

Will leave testing this where it is, and if we get Weave or Consul DNS available, we can rerun the tests.

**Comment by thockin** [comment]
I think ConsulDNS requires running Consul, which sounds pretty
heavy-weight.  We could also engage with skydns folks on expected perf
(@bketelsen).  We could also look at CoreDNS (@miekg) which is much newer
and riskier, but maybe a better fit longer term?

@smarterclayton - have you guys done DNS perf numbers?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [kubernetes/kubernetes] Improve..." ]
>I think ConsulDNS requires running Consul, which sounds pretty
>heavy-weight.  We could also engage with skydns folks on expected perf
>(@bketelsen).  We could also look at CoreDNS (@miekg) which is much newer
>and riskier, but maybe a better fit longer term?
>
>@smarterclayton - have you guys done DNS perf numbers?

~500 qps sounds really slow. Is every request going to etcd?

CoreDNS has much better caching, in the (non optimized version) I can easily do 
15K qps, but SkyDNS should be able to get to those as well.

Longer term I think CoreDNS makes much more sense. Note the "SkyDNS" middleware
in CoreDNS is a cleaned up version from CoreDNS - but yeah the project itself is 
barely 2 months old.

Is more information available on where the time is spend.

>
>On Fri, Jul 1, 2016 at 4:40 PM, Girish Kalele <notifications@github.com>
>wrote:
>
>> @bprashanth <https://github.com/bprashanth>
>>
>> Eliminated logs from kubedns and bumped up CPU to 1000m.
>> Marginally improved QPS from ~ 290 to ~ 341.
>>
>> Will leave testing this where it is, and if we get Weave or Consul DNS
>> available, we can rerun the tests.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/kubernetes/kubernetes/issues/28366#issuecomment-230068725>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AFVgVJA6pxFwnO6SU3fdf65OuZ3qs8w3ks5qRaVWgaJpZM4JDWO9>
>> .
>>
>
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/kubernetes/kubernetes/issues/28366#issuecomment-230069144
/Miek

--
Miek Gieben

**Comment by bketelsen** [comment]
I've been out of the loop, but happy to help.  Also: There's a container "Hack Room" in the 13th of July at GopherCon - would be a good time to sit down and work through things.

10:00am - 5:00pm
Room: 4f
Container Technologies
Hack on and discuss the various container technologies written in and powered by Go

**Comment by thockin** [comment]
Girish, have you take a profile?

**Comment by girishkalele** [comment]
@miekg This version of kubedns does not use etcd - in-memory lookup for local services.

The dnsperf sample queryfile will be 100% hitting the forwarding to cloud DNS path. Container logs show i/o timeouts forwarding to GCE DNS, but there are no timeouts when dnsperf is configured to hit GCE DNS directly, so this is a skydns issue losing track of UDP ports or something IMO. The GCE DNS server directly is able to serve 12000+ QPS.

I will grab profiling data but I tried a CPU limit increase from 0.1 core to 1.0 core and that did not significantly affect QPS.

```
I0701 23:32:55.190432       1 logs.go:41] skydns: failure to forward request "read udp 10.244.2.3:58768->169.254.169.254:53: i/o timeout"
I0701 23:32:55.537034       1 logs.go:41] skydns: failure to forward request "read udp 10.244.2.3:38153->169.254.169.254:53: i/o timeout"
I0701 23:32:56.103012       1 logs.go:41] skydns: failure to forward request "read udp 10.244.2.3:40873->169.254.169.254:53: i/o timeout"
I0701 23:32:56.273982       1 logs.go:41] skydns: failure to forward request "read udp 10.244.2.3:49714->169.254.169.254:53: i/o timeout"
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [kubernetes/kubernetes] Improve..." ]
>@miekg This version of kubedns does not use etcd - in-memory lookup for local services.

Ack.

>The dnsperf sample queryfile will be 100% hitting the forwarding to cloud DNS 
>path. Container logs show i/o timeouts forwarding to GCE DNS, but there are no 
>timeouts when dnsperf is configured to hit GCE DNS directly, so this is a 
>skydns issue losing track of UDP ports or something IMO. The GCE DNS server 
>directly is able to serve 12000+ QPS.

Ack. 

>I will grab profiling data but I tried a CPU limit increase from 0.1 core to 
>1.0 core and that did not significantly affect QPS.
>
>```
>I0701 23:32:55.190432       1 logs.go:41] skydns: failure to forward request "read udp 10.244.2.3:58768->169.254.169.254:53: i/o timeout"
>I0701 23:32:55.537034       1 logs.go:41] skydns: failure to forward request "read udp 10.244.2.3:38153->169.254.169.254:53: i/o timeout"
>I0701 23:32:56.103012       1 logs.go:41] skydns: failure to forward request "read udp 10.244.2.3:40873->169.254.169.254:53: i/o timeout"
>I0701 23:32:56.273982       1 logs.go:41] skydns: failure to forward request "read udp 10.244.2.3:49714->169.254.169.254:53: i/o timeout"
>```

Could it be re-using ports so fast the the client code is using a new port while 
a response is still inflight?

I would almost say, what does CoreDNS do... but I get that would be a hassle to 
setup and configure, if it all possible.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [kubernetes/kubernetes] Improve..." ]
>@miekg This version of kubedns does not use etcd - in-memory lookup for local services.
>
>The dnsperf sample queryfile will be 100% hitting the forwarding to cloud DNS 

>path. Container logs show i/o timeouts forwarding to GCE DNS, but there are no 
>timeouts when dnsperf is configured to hit GCE DNS directly, so this is a 
>skydns issue losing track of UDP ports or something IMO. The GCE DNS server 
>directly is able to serve 12000+ QPS.

Is SkyDNS running inside docker when you do this? When you directly hit GCEDNS 
are you running in docker as well?

**Comment by girishkalele** [comment]
Yes in both cases.

**Comment by thockin** [comment]
Have you pulled a profile?  Do you know how?

**Comment by miekg** [comment]
~~~
I0701 23:32:56.273982       1 logs.go:41] skydns: failure to forward request "read udp 10.244.2.3:49714->169.254.169.254:53: i/o timeout"
~~~
169.254.169.254 that's also the IP used when directly querying GCEDNS?

**Comment by miekg** [comment]
Also SkyDNS might be throttled, while direct queries to gcedns might not. I have no way of checking that from here.
To actually prove or disprove performance figures of SkyDNS we would need to do a standalone test. I'm actively working on testing and performance tuning CoreDNS, so I might give SkyDNS a whirl as well - time permitting.

**Comment by girishkalele** [comment]
@thockin @miekg 

Yes, 169.254.169.254 is the GCE DNS server in both cases.

I got pprof data,  but I don't understand the 60 ms total part, it was a 30 second profile.
I started the pprof server and used ```go tool pprof <url>``` - is that going to work ?

```console
60ms of 60ms total (  100%)
Showing top 10 nodes out of 46 (cum >= 30ms)
      flat  flat%   sum%        cum   cum%
      10ms 16.67% 16.67%       10ms 16.67%  runtime.futex
      10ms 16.67% 33.33%       10ms 16.67%  runtime.heapBitsSetType
      10ms 16.67% 50.00%       20ms 33.33%  runtime.mallocgc
      10ms 16.67% 66.67%       10ms 16.67%  runtime.mapaccess2
      10ms 16.67% 83.33%       10ms 16.67%  runtime.mapassign1
      10ms 16.67%   100%       10ms 16.67%  runtime.netpollunblock
         0     0%   100%       10ms 16.67%  k8s.io/kubernetes/cmd/kube-dns/app.(*KubeDNSServer).Run
         0     0%   100%       30ms 50.00%  k8s.io/kubernetes/pkg/client/cache.(*ListWatch).List
         0     0%   100%       30ms 50.00%  k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch
         0     0%   100%       30ms 50.00%  k8s.io/kubernetes/pkg/client/cache.(*Reflector).RunUntil.func1
```

**Comment by thockin** [comment]
I am not sure how to interpret that - is that all you got?

**Comment by smarterclayton** [comment]
We've done DNS perf, mostly to ensure we hit the DNS cache from skydns
properly in most cases based on TTL.  If we fall through the cache or
cache isn't on then we're mostly GC limited due to the creation cost
of  the skydns records.  I've seen upwards of 30-40k qps in core
cases.

I haven't tested now that we've moved DNS to the nodes though, so will
follow up.

**Comment by smarterclayton** [comment]
Looks like the profiler wasn't able to get enough samples (or
something was caching DNS on the client side and you weren't hitting
the server).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [kubernetes/kubernetes] Improve..." ]
>We've done DNS perf, mostly to ensure we hit the DNS cache from skydns
>properly in most cases based on TTL.  If we fall through the cache or
>cache isn't on then we're mostly GC limited due to the creation cost
>of  the skydns records.  I've seen upwards of 30-40k qps in core
>cases.

If you update to the latest Go DNS version you should see up to 30% improvements
in this. (The runtime reflection has been removed).

/Miek

--
Miek Gieben

**Comment by bboreham** [comment]
> @errordeveloper Is there a Docker image with the Weave DNS server that we can drop in and do a test ?

@girishkalele, errordeveloper asked me to respond: the DNS functionality is only packaged with Weave Net at the moment, but it wouldn't be too hard to re-package.

However the origins of our performance claims came from not using etcd, so if this particular test is running in-memory then the ultimate cause of your slowdown must be elsewhere.  We're all using @miekg's library in the front end.

**Comment by girishkalele** [comment]
@bboreham @errordeveloper 

Thanks for your reply - we would like to run with your DNS server dropped in to replace the kubedns implementation to get another datapoint, if the repackaging is easy, it would be a good test.

Yes, there is no etcd involved anymore, the cause of the slowdown is elsewhere.

I still need to figure out my pprof tracing skills to get a better and more useful trace.

**Comment by bboreham** [comment]
@girishkalele I pushed an image `weaveworks/dnstest` which runs our DNS server, to DockerHub.  It's actually the unmodified Weave Net daemon, but with packet bridging turned off through command-line options.

By default it is listening on `0.0.0.0:53` and upstream is read from `/etc/resolv.conf` inside the container.

So, I could get one instance running with `kubectl run --image=weaveworks/dnstest dnstest` and run the tests at https://github.com/kubernetes/contrib/pull/1189, which seem similar to what you're talking about here.

**Comment by girishkalele** [comment]
@bboreham 

You got it, https://github.com/kubernetes/contrib/pull/1189 has the exact test I am running, the yaml file fires off 10 parallel dnsperf jobs.

The 4 parameters to the container are consumed by runjob.sh. You can change the IP address to point to your dnstest pod. Arg 4 can point to one of the 2 query files in the container - the 10k entry queryfile-example-short and queryfile-example-current which has 10M DNS entries.

One tweak you will need is to point the /etc/resolv.conf upstream to bypass kubedns and hit your upstream directly.

**Comment by girishkalele** [comment]
@thockin @miekg 

Pprof trace when kube-dns was verified active with 1000 millicores (not the default 100m).

```console
(pprof) top30
4650ms of 6370ms total (73.00%)
Dropped 138 nodes (cum <= 31.85ms)
Showing top 30 nodes out of 195 (cum >= 40ms)
      flat  flat%   sum%        cum   cum%
    1460ms 22.92% 22.92%     1570ms 24.65%  syscall.Syscall
     300ms  4.71% 27.63%      300ms  4.71%  runtime.futex
     300ms  4.71% 32.34%      300ms  4.71%  runtime.usleep
     280ms  4.40% 36.73%      280ms  4.40%  runtime.readvarint
     230ms  3.61% 40.35%      430ms  6.75%  runtime.mallocgc
     200ms  3.14% 43.49%      600ms  9.42%  runtime.pcvalue
     170ms  2.67% 46.15%      170ms  2.67%  runtime.epollwait
     160ms  2.51% 48.67%      160ms  2.51%  runtime.adjustpointers
     130ms  2.04% 50.71%      130ms  2.04%  runtime._ExternalCode
     130ms  2.04% 52.75%      130ms  2.04%  runtime.epollctl
     130ms  2.04% 54.79%      130ms  2.04%  syscall.RawSyscall
     110ms  1.73% 56.51%      390ms  6.12%  runtime.step
     100ms  1.57% 58.08%      110ms  1.73%  runtime.findfunc
     100ms  1.57% 59.65%     1040ms 16.33%  runtime.gentraceback
      90ms  1.41% 61.07%      140ms  2.20%  k8s.io/kubernetes/vendor/github.com/miekg/dns.UnpackDomainName
      90ms  1.41% 62.48%      120ms  1.88%  runtime.scanobject
      80ms  1.26% 63.74%       80ms  1.26%  runtime.heapBitsSetType
      60ms  0.94% 64.68%      160ms  2.51%  k8s.io/kubernetes/vendor/github.com/miekg/dns.packDomainName
      60ms  0.94% 65.62%       60ms  0.94%  runtime.memmove
      60ms  0.94% 66.56%       60ms  0.94%  runtime/internal/atomic.Xchg
      50ms  0.78% 67.35%       50ms  0.78%  runtime.(*mspan).sweep.func1
      40ms  0.63% 67.97%       40ms  0.63%  runtime.(*gcWork).tryGet
      40ms  0.63% 68.60%       90ms  1.41%  runtime.SetFinalizer
      40ms  0.63% 69.23%       50ms  0.78%  runtime.deferreturn
      40ms  0.63% 69.86%      420ms  6.59%  runtime.findrunnable
      40ms  0.63% 70.49%       60ms  0.94%  runtime.greyobject
      40ms  0.63% 71.11%       90ms  1.41%  runtime.heapBitsSweepSpan
      40ms  0.63% 71.74%       40ms  0.63%  runtime.mapaccess2_faststr
      40ms  0.63% 72.37%      250ms  3.92%  runtime.netpoll
      40ms  0.63% 73.00%       40ms  0.63%  runtime/internal/atomic.Store
```

**Comment by girishkalele** [comment]
And full pprof dumps at https://gist.github.com/girishkalele/4f36ccf342e87eeba064e63b14ebe0aa

**Comment by thockin** [comment]
Man, that is just not what I expect to see.  I don't know what it means..so
much time in syscall and futex..

**Comment by girishkalele** [comment]
Another trace - tree output shows origin of the syscall. Not familiar with the runtime.readvarint and runtime.pcvalue - something commonly seen in Golang ?

```
(pprof) tree
20.81s of 25.43s total (81.83%)
Dropped 294 nodes (cum <= 0.13s)
Showing top 80 nodes out of 176 (cum >= 6.11s)
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context
----------------------------------------------------------+-------------
                                             4.32s 92.70% |   syscall.sendmsg
                                             0.34s  7.30% |   net.(*netFD).readMsg
     5.78s 22.73% 22.73%      6.06s 23.83%                | syscall.Syscall
                                             0.19s   100% |   runtime.entersyscall
----------------------------------------------------------+-------------
                                             1.55s   100% |   runtime.step
     1.55s  6.10% 28.82%      1.55s  6.10%                | runtime.readvarint
----------------------------------------------------------+-------------
                                             2.63s 57.55% |   runtime.pcdatavalue
                                             1.94s 42.45% |   runtime.funcspdelta
     1.49s  5.86% 34.68%      4.57s 17.97%                | runtime.pcvalue
                                             2.79s 94.90% |   runtime.step
                                             0.15s  5.10% |   runtime.duffcopy

(pprof) top30
18150ms of 25430ms total (71.37%)
Dropped 294 nodes (cum <= 127.15ms)
Showing top 30 nodes out of 176 (cum >= 130ms)
      flat  flat%   sum%        cum   cum%
    5780ms 22.73% 22.73%     6060ms 23.83%  syscall.Syscall
    1550ms  6.10% 28.82%     1550ms  6.10%  runtime.readvarint
    1490ms  5.86% 34.68%     4570ms 17.97%  runtime.pcvalue
    1240ms  4.88% 39.56%     2790ms 10.97%  runtime.step
     740ms  2.91% 42.47%      980ms  3.85%  runtime.scanobject
     680ms  2.67% 45.14%      680ms  2.67%  runtime.adjustpointers
     680ms  2.67% 47.82%     2230ms  8.77%  runtime.mallocgc
     480ms  1.89% 49.71%     7140ms 28.08%  runtime.gentraceback
     470ms  1.85% 51.55%      470ms  1.85%  runtime.usleep
     450ms  1.77% 53.32%      450ms  1.77%  runtime._ExternalCode
     410ms  1.61% 54.94%      410ms  1.61%  runtime.heapBitsSetType
     370ms  1.45% 56.39%      370ms  1.45%  runtime.futex
     350ms  1.38% 57.77%     2830ms 11.13%  runtime.adjustframe
     330ms  1.30% 59.06%      850ms  3.34%  k8s.io/kubernetes/vendor/github.com/miekg/dns.packDomainName
     310ms  1.22% 60.28%      310ms  1.22%  runtime.(*mspan).sweep.func1
     310ms  1.22% 61.50%      340ms  1.34%  runtime.findfunc
     300ms  1.18% 62.68%      300ms  1.18%  runtime.heapBitsForObject
     230ms   0.9% 63.59%      230ms   0.9%  crypto/sha1.block
     230ms   0.9% 64.49%      490ms  1.93%  runtime.scanblock
```

**Comment by girishkalele** [comment]
It seems like there is a new UDP socket created for every DNS forward request.
There are a lot of connections to 169.254.169.254 brought up and torn down seen in netstat...we should be able to mux/demux multiple queries based on DNS query transaction id and not need a unique socket for every forwarded request ?

```
root@kubernetes-minion-group-jkok # docker exec cd79e7468ca2 netstat -uapn
udp        0      0 10.244.1.9:52097        169.254.169.254:53      ESTABLISHED 1/kube-dns
udp        0      0 10.244.1.9:43941        169.254.169.254:53      ESTABLISHED 1/kube-dns
udp        0      0 10.244.1.9:48098        169.254.169.254:53      ESTABLISHED 1/kube-dns
udp        0      0 10.244.1.9:48306        169.254.169.254:53      ESTABLISHED 1/kube-dns
udp        0      0 10.244.1.9:40209        169.254.169.254:53      ESTABLISHED 1/kube-dns
udp        0      0 10.244.1.9:60743        169.254.169.254:53      ESTABLISHED 1/kube-dns
udp        0      0 10.244.1.9:40295        169.254.169.254:53      ESTABLISHED 1/kube-dns
udp        0      0 10.244.1.9:36321        169.254.169.254:53      ESTABLISHED 1/kube-dns
udp        0      0 10.244.1.9:40520        169.254.169.254:53      ESTABLISHED 1/kube-dns
udp        0      0 10.244.1.9:36662        169.254.169.254:53      ESTABLISHED 1/kube-dns
udp        0      0 10.244.1.9:57258        169.254.169.254:53      ESTABLISHED 1/kube-dns
udp        0      0 10.244.1.9:49131        169.254.169.254:53      ESTABLISHED 1/kube-dns
udp     1536      0 :::53                   :::*                                1/kube-dns
<<<snipped>>
root@kubernetes-minion-group-jkok # docker exec cd79e7468ca2 netstat -uapn
     72     505    6525

**Comment by thockin** [comment]
That might be a good optimization in skydns, but I don't see that being the
killer.

Am I reading it right?  Only 23% is accounted for by the top call-tree?
That sounds pretty healthy to me, it means we have a very long tail of
functions each taking a small amount of CPU time.  Am I misinterpreting?

**Comment by girishkalele** [comment]
@thockin Yes, (fairly new to pprof output for Go) apart from the first entry, there are no obvious hotspots. Increasing the CPU allocation also doesn't help performance (if cgroup throttling was the issue which we wouldn't see in the pprof sampling (is this correct ?)).

Then, it would seem that its the lost queries that are affecting the QPS.

**Comment by thockin** [comment]
lost queries?  Where are they getting lost?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [kubernetes/kubernetes] Improve..." ]
>It seems like there is a new UDP socket created for every DNS forward request.

Are you implying there is a better way to do this (in Go)?

>There are a lot of connections to 169.254.169.254 brought up and torn down seen in netstat...we should be able to mux/demux multiple queries based on DNS query transaction id and not need a unique socket for every forwarded request ?

Why does SkyDNS even see multiple outstanding queries with the same query ID?
There is an option to suppress identical queries going upstream: https://godoc.org/github.com/miekg/dns#Client
(actually using the query ID - might be solving a longstanding TODO in the code
there)

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
Me neither, sadly. Is this the go runtime or the "user" code in Go DNS that
needs to be tweaked?

**Comment by miekg** [comment]
Maybe setup a TCP connection to the upstream and use that, in stead of
using udp every time?

**Comment by girishkalele** [comment]
@thockin 

Lost messages- kube-dns logs show "failure to forward request : i/o timeout" errors.
From direct tests against the GCE DNS server, we saw no lost or dropped packets.
If we believe GCE DNS is responding, then these replies are getting lost somewhere.

```
I0701 23:32:55.190432       1 logs.go:41] skydns: failure to forward request "read udp 10.244.2.3:58768->169.254.169.254:53: i/o timeout"
I0701 23:32:55.537034       1 logs.go:41] skydns: failure to forward request "read udp 10.244.2.3:38153->169.254.169.254:53: i/o timeout"
I0701 23:32:56.103012       1 logs.go:41] skydns: failure to forward request "read udp 10.244.2.3:40873->169.254.169.254:53: i/o timeout"
I0701 23:32:56.273982       1 logs.go:41] skydns: failure to forward request "read udp 10.244.2.3:49714->169.254.169.254:53: i/o timeout"
```

**Comment by girishkalele** [comment]
@miekg 

I actually meant if we were able to use a single UDP socket to every upstream DNS server, it would save a lot of churn. Possible would need to "NAT the query transaction ids" to correctly correlate upstream replies.

I will try and force upstream TCP in kube-dns, see if that helps performance.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [kubernetes/kubernetes] Improve..." ]
>@miekg
>
>I actually meant if we were able to use a single UDP socket to every upstream DNS server, it would save a lot of churn. Possible would need to "NAT the query transaction ids" to correctly correlate upstream replies.

Interestingly this is something I'm exploring for CoreDNS (kicked off partially, 
by this discussion): https://github.com/miekg/coredns/issues/184, but for TCP 
sockets. Didn't completely realize this can (and maybe) should be done for UDP 
socket as well - always assumed this is super check (at least when compared to 
TCP).

>I will try and force upstream TCP in kube-dns, see if that helps performance.

If kube-dns is still a lot like SkyDNS then that won't help: well you then have
a lot of TCP socket churn.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
@girishkalele i've seen those timeout before in DNS code. I've never been able to establish why (or where in the code) this happens.

Is it possible to check what gcedns is returning?

**Comment by miekg** [comment]
So we benchmarked: https://github.com/miekg/coredns/pull/287#issuecomment-250598124

SkyDNS: Requests/Second: 38436.775

Discuss.

**Comment by alok87** [comment]
@girishkalele can u share the command used to measure the QPS?

**Comment by bowei** [comment]
One thing that may be useful is github.com:kubernetes/perf-tests/dns

**Comment by errordeveloper** [comment]
Should we keep this open?
