### ISSUE TITLE
Remove the defer calls that catch panics

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#28365]
They tend to hide bugs in production: software crashes make it really clear when there is a problem; catching panics papers over the issue and makes it more difficult for monitoring systems to catch failures. 

/cc @lavalamp @krousey

**Comment by lavalamp** [comment]
SGTM, they're no longer useful since we run apiserver with kubelet and it'll restart.

**Comment by wojtek-t** [comment]
@kubernetes/sig-api-machinery
