### ISSUE TITLE
requiredDuringSchedulingIgnoredDuringExecution not ignored

### ISSUE THREAD

**Issue by dvohra** [kubernetes/kubernetes#28368]
For node affinity in node selection the requiredDuringSchedulingIgnoredDuringExecution nodeAffinity setting is supposed to ignore any modifications made during runtime. But, if a Pod is pending due to unavailability of a suitable node as no node with a matching label exists, and a node is made suitable by updating a node's label during runtime, the pending Pod starts running. Is the requiredDuringSchedulingIgnoredDuringExecution valid only for Pods already running made unsuitable to run on a node due to node label update at runtime? 

It is not documented: _A running Pod is not stopped if a node label is updated at runtime to make it unsuitable for a Pod to be scheduled on, but a Pending Pod gets scheduled if a node label on a node is updated at runtime to make it suitable for a Pod to be scheduled._ 

http://kubernetes.io/docs/user-guide/node-selection/

**Comment by dvohra** [comment]
A Pending Pod does fall in the scope of  "DuringExecution" as it is not yet running. A pending pod is in the scope of "DuringScheduling".

Issue may be closed.

**Comment by euank** [comment]
@calebamiles want to close this one per the comment above?
