### ISSUE TITLE
kubernetes metadata not added to logs generated from fluentd.

### ISSUE THREAD

**Issue by maverick-racheal** [kubernetes/kubernetes#28370]
We are using the td-agent.conf from https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/td-agent.conf and the logs are mounted at  varlog inside the fluentd docker container.

<POD-NAME>-_default_controller-manager-c2f07985a124ff0a46c0c41ee468ad6e5f63a7615b1b1445523c5bc9293d294e.log
<POD-NAME>-_default_scheduler-a41d0a71e91ec5751284a1200a4cc23d99f43082a204340192d85daefc67675b.log

root@fluentd-elasticsearch-5rl0j:/varlog#  

The logs from these are formed the following format and displayed as below in elk
curl -XGET 'localhost:9200/logstash*/_search/?pretty' -d '{
         "query": {
                        "match": {
                                         "log":"endpoints"
                                                    }
         }
}'  
   }, {
      "_index" : "logstash-2016.07.01",
      "_type" : "fluentd",
      "_id" : "AVWnpX1jyEJSpGQNNRCs",
      "_score" : 0.8208284,
      "_source" : {
        "log" : "I0701 18:06:35.317525       1 proxier.go:484] Setting endpoints for \"default/heapster:\" to [10.1.64.5:8082]\n",
        "stream" : "stderr",
        "tag" : "kubernetes.varlog.<POD-NAME>_default_kube-proxy-2e5580124adcc10e6cea83f0eb5a8c43b9e72f7a50fca55f7aadad0c402a8a3d.log",
        "@timestamp" : "2016-07-01T18:06:35+00:00"
      }
    } ]
  }
}
 However we expect the final logs to be in the following format which doesnt seem to be happening. 

 {
   "log":"2014/09/25 21:15:03 Got request with path wombat\n",
   "stream":"stderr",
   "time":"2014-09-25T21:15:03.499185026Z",
   "kubernetes": {
     "namespace": "default",
     "pod_name": "synthetic-logger-0.25lps-pod",
     "container_name": "synth-lgr"
   },
   "docker": {
     "container_id": "997599971ee6366d4a5920d25b79286ad45ff37a74494f262e3bc98d909d0a7b"
   }
 }

Appreciate any pointers.

**Comment by maverick-racheal** [comment]
The missing part is the kubernetes metadata which is added by the fluent-plugin-kubernetes_metadata_filter plugin. This plugin is added in the Docker file of fluentd.
{"log":"2016-07-01 18:06:26 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.5.0'\n","stream":"stdout","time":"2016-07-01T18:06:26.88984336Z"}
{"log":"2016-07-01 18:06:26 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '0.22.0'\n","stream":"stdout","time":"2016-07-01T18:06:26.889927538Z"}
{"log":"2016-07-01 18:06:26 +0000 [info]: gem 'fluent-plugin-m

**Comment by gregory90** [comment]
@maverick-racheal did you manage to resolve this issue?

**Comment by AlexRRR** [comment]
@maverick-racheal @gregory90 I am having the same issue with the image `gcr.io/google_containers/fluentd-elasticsearch:1.20`.

Also I am confused by the tag in this issue of `deprecated`, what is the correct way then?

**Comment by spiffxp** [comment]
/sig instrumentation
I assume sig-instrumentation owns the fluentd-elasticsearch addon
