### ISSUE TITLE
Library of resource descriptions / configs for popular apps

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#2837]
To ease getting started experience

**Comment by bhanusharma92** [comment]
Hello
I am interested in doing this project and would like to contribute. But i want to know what should i do or code to get started.

**Comment by bgrant0607** [comment]
@bhanusharma92 More details can be found in #4926.

**Comment by bgrant0607** [comment]
This has become the "top workloads" effort. Feel free to close if not useful.

**Comment by erictune** [comment]
Update on current state:

If you install the optional helm tool (from [http://helm.sh]) then you can install Charts.

The Charts development and testing occurs at http://github.com/kubernetes/charts.

Currently we have the following apps which are "stable":

- drupal
- jenkins	
- mariadb
- mysql
- redmine
- wordpress

More will be added soon.

Closing this issue.  Further discussion should happen in the [sig-apps meeting](https://github.com/kubernetes/community/tree/master/sig-apps) or slack channel, or in issues on the github.com/kubernetes/charts repo.
