### ISSUE TITLE
e2e: Enhance wait for pods ready to exclude static pods

### ISSUE THREAD

**Issue by girishkalele** [kubernetes/kubernetes#28382]
https://github.com/kubernetes/test-infra/pull/122 changed wait for minimum pods ready to 8.
However, we need to enhance the e2e go code to also exclude static pods.

From @bprashanth : These static pods will have the annotation below which can be used to filter them out.

`kubernetes.io/config.source: file`

**Comment by yujuhong** [comment]
Just curious, why shouldn't we wait until the static pods are ready too? 

If you really want to tell whether the pod is a mirror pod (reflecting the status of the static pod), it's better to check the `kubernetes.io/config.mirror` key, since this is the only annotation that has been used outside of kubelet.

**Comment by bprashanth** [comment]
Ideally we'd wait till everything is ready, addons + static + master. But waiting on the static pods needs to scale with number of nodes.

**Comment by girishkalele** [comment]
@yujuhong Yes, the problem is the hard coded value of 8 that is the only parameter for the waitForPods()  logic today. Counting the static pods muddies up the calculation and satisfies the value of 8 too early.

Removing static pods from the count will atleast prevent test suites from starting prematurely.

But, as Prashanth says, if we knew or could calculate exactly how many system pods there will be, we should wait on all of them before allowing the suites to run. Not sure how we can get that number for the various e2e tests though.

**Comment by yujuhong** [comment]
I think the issue is stale and the test framework now waits for the kube-system namespaced pods to be ready.
