### ISSUE TITLE
Add readyReplicas to Deployments

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#28381]
https://github.com/kubernetes/kubernetes/pull/29481 adds ReadyReplicas to Replica Sets.
https://github.com/kubernetes/kubernetes/pull/32771 adds AvailableReplicas/MinReadySeconds to ReplicaSets

We still need to add ReadyReplicas to Deployments.

**Comment by AdoHe** [comment]
I like this feature :)

**Comment by bgrant0607** [comment]
This is basically a dupe of #7483

**Comment by kargakis** [comment]
@bgrant0607 thanks, I will be back at this in a couple of weeks.

**Comment by kargakis** [comment]
@bgrant0607 updated the issue to track the api changes that still need to be done once #29481 is merged:
ReadyReplicas for Deployments
AvailableReplicas+MinReadySeconds for Replica Sets

**Comment by bgrant0607** [comment]
Thanks, @kargakis

**Comment by kargakis** [comment]
https://github.com/kubernetes/kubernetes/pull/32771 added AvailableReplicas+MinReadySeconds to replica sets so this basically now is ReadyReplicas for Deployments.
