### ISSUE TITLE
Docs should be catered to multiple audiences

### ISSUE THREAD

**Issue by proppy** [kubernetes/kubernetes#2839]
## Audience
- people don't know anything about container
- people who are familiar with container but looking for a clustering solution
- people who are using GKE and want to learn more
- people who want to contribute to the project
## Personas
- decider
- ops
- application developers
- contributors
## Outline
- justify container? quickly
  - link to docker "why page" https://www.docker.com/whatisdocker/

> You already know that container allow you to build portable app …
- justify clustering? why do I need it?
  - emphasize separation of concern and isolation

> But with kubernetes, you can leverage container to scale the application and you infrastrucure independently
- schema show a real life example: w/ multiple nodes and the master and kubernetes concepts (pods, services, replication controller)
  - something between http://kubernetes.io/img/desktop/graphs/graph-01.svg and https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/architecture.svg
  - see satnam blog post for inspiration http://blog.raintown.org/2014/11/logging-kubernetes-pods-using-fluentd.html
- outbound links
  - Try it locally (0 setup hello world)
    - Local bootstrap (cross platform)
      - boot2docker
      - vagrant
    - Schedule a nginx pod that say hello world
  - Create your own cluster (via some cloud provider)
    - platform specific (several of them)
  - Kubernetes tour / tutorial (pods, service, replication controller)
    - definition of concepts in kubernetes, and using them within a sample
    - one large example that builds as it goes (like 101 and 201 samples but with commands that you can run)
    - could be a pod serving from your new cluster install or local bootstrap
      - talk to the api server (like the Go tour)
  - How to learn more (pointer to docs)
  - More examples/samples

Part of #2633

**Comment by bgrant0607** [comment]
Another take on audiences, in order of decreasing population size:
* Casual browser who wants to know what Kubernetes is and what it's good for
* People kicking the tires, including turning up a cluster, but also running an example
* End users trying to run their own workloads
  * app developers
  * app ops
* Cluster admins: cluster turn up, upgrades, troubleshooting, etc.
* Someone porting Kubernetes to a new:
  * OS distribution
  * Cloud provider
  * Network infrastructure
* Core developer of Kubernetes

**Comment by bgrant0607** [comment]
See also #2633 and other doc. issues (reorgs of getting-started guides, etc.).

**Comment by bgrant0607** [comment]
cc @RichieEscarez

**Comment by bgrant0607** [comment]
Tutorials were highlighted as needed in the friction study.

**Comment by bgrant0607** [comment]
http://www.literateprogramming.com/documentation.pdf has a useful breakdown on page 5.

**Comment by bgrant0607** [comment]
Subsumed by doc overhaul, and docs have been moved to kubernetes.github.io, so closing here
