### ISSUE TITLE
[node e2e] Test secret volumes in the node summary test

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#28393]
Address TODO in https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/summary_test.go (from https://github.com/kubernetes/kubernetes/pull/28195)

**Comment by matchstick** [comment]
@jeffvance

**Comment by jeffvance** [comment]
#28195 is closed and replaced by #29479 which is not yet merged. Therefore the e2e_node/summary_test.go file does not yet exist. I'll start looking into adding secret tests to e2e_node/kubelet_test.go

**Comment by jeffvance** [comment]
#29479 is now merged.
