### ISSUE TITLE
Kubelet state visualization / debugging UI

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#284]
Need to be able to browse pods and click-thru to info
Need to show more than just Docker's native info (in fact, maybe we should not show that at all and instead abstract it a bit further?)
Need to show our own understanding of the world

**Comment by marshauf** [comment]
I'm interested in this project as part of GSoC 2015. A bit has changed since July 2014. cadvisor#74 got implemented and a simple web-UI is available. I couldn't find any up to date information about this topic. 
My understanding of the state of this topic is, that the goal of this project would be to create a web-UI which displays statistics, be able to do what the CLI can do. The data for the statistics is gathered from a database (currently influxdb). Commands are given directly to the kublet server.

**Comment by bgrant0607** [comment]
@marshauf We'd like the Kubelet web UI to be able to show information about the pods scheduled to the node, and about the node itself -- at least as much information about those objects as available in the apiserver's UI, but ideally going beyond that. CAdvisor's UI could be integrated into it. Links to logs could be made available. Errors from pods executed from local files could be surfaced. Docker status could be reported.

Perhaps @dchen1107 or @vmarmol have additional suggestions.

Scenarios we'd like to support:
1. Debugging the Kubelet using information not sent to apiserver and/or when apiserver is not available
2. Debugging applications when apiserver is not available, including when Kubelet is used "standalone" without a cluster

**Comment by vmarmol** [comment]
+1 to everything @bgrant0607 said. There is a lot of data in the Kubelet about the pods that we don't send to the apiserver. For users and for debugging it will be very useful to display that data. Displaying pods from non-apiserver sources and their mirror pod equivalents would be of particular value.

Some usage data from cAdvisor can be used and integrated, but some of the things mentioned above are no longer in scope. We'll probably show basic graphs of recent usage.

**Comment by vishh** [comment]
The UI should help introspect the kubelet itself - provide links to kubelet
logs, track kubelet's uptime, compute resource usage, etc.

**Comment by marshauf** [comment]
Thank you for the answers.

Which technology could I use for the Kubelet web UI?
cAdvisor uses bootstrap and jquery. The kubernetes web UI uses angularjs.

Would the Kubelet serve the web UI?

What should the proposal for GSoC contain? I couldn't find a template, or a list of requirements.
A project goal, timeline, biography?

**Comment by vmarmol** [comment]
Use AngularJS please, we'll be consistent within Kubernetes (if anything we want to re-write cAdvisor in Angular). The UI will indeed be served by the Kubelet.

@bgrant0607 do we have a template?

Project goal is to create a Kubernetes node user interface allowing introspection into the node and it's workloads. Assisting in visualization and debugging of the current state and possible issues.

Requirements:
* Show a nodes: state, capacity, links to logs, uptime, any salient errors, and usage overview
* Show pods running on the node, their state, configurations, any errors or events associated with them, link to their logs, and usage overview.
* What apiserver the Kubelet answers to and the health of that connection.

Timeline would be before the end of the summer (roughly 1.0 timeframe). Feel free to make some stop-gaps in between and let us know if you need help coming up with those :)

**Comment by marshauf** [comment]
I submitted my proposal. Can you review it, please?

**Comment by bgrant0607** [comment]
Thanks for your proposal! We'll definitely take a look. 

Whatever UI templates/assets we have currently are in:
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/www

FYI, a new (cluster-level) UI is being developed:
https://github.com/kubernetes-ui/kubernetes-ui/tree/master/www

**Comment by PeterLamar** [comment]
Issue seems out of date. Close?

**Comment by dchen1107** [comment]
cc/ @adityakali
