### ISSUE TITLE
Need "action required" notes in CHANGELOG.md

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#28405]
We need to fill in the "action required" section of our release notes (in kubernetes/CHANGELOG.md).

Rather than everyone sending a PR against CHANGELOG.md,  and having lots of merge conflicts, let's take advantage of the automatic release note generation that @david-mcmahon has written (thanks! it is a big improvement over 1.2).

For that to work, I need is for everyone who wrote a PR that requires action from the user to make sure that PR has the `release-note-action-required` label is on their PR.  It doesn't matter that it already merged.  We will regenerate with the latest labels. I also need anyone who wrote a PR that _has_ that label to make sure that it is really required, and remove it if it is not.  If it is requred, please make sure it has a "release-note" block in the first comment of the PR which describes that the user needs to do.  A good example of this is https://github.com/kubernetes/kubernetes/pull/28132

Most of the PRs with the release-note-action-required label do _not_ have this.

Once that is done, we will regenerate the release notes (also need to fix https://github.com/kubernetes/release/issues/26)

Specific PRs with this label which are in 1.3, at the time of writing:
- ~~#28132~~
- ~~#28258~~
- ~~#28186~~
- ~~#27869~~
- #26796
- ~~#26819~~
- ~~#26251~~
- ~~#26415~~
- ~~#26341~~
- ~~#25599~~
- ~~#26238~~
- ~~#14943~~
- ~~#19242~~ 
- ~~#24509~~ 
- ~~#25007~~
- ~~#25196~~
- ~~#25006~~
- ~~#25072~~
- ~~#24455~~
- #22897
- ~~#24008~~

**Comment by erictune** [comment]
#25072 and #25006 will be documented via PR #28564

#28403 added a bunch of known issues. 

Only #22897 and #26796 are unknown at this point.

**Comment by david-mcmahon** [comment]
I would say this is now handled by the release note drafts that accompany our regular minor releases.
