### ISSUE TITLE
kubelet summary api: Node.Network metric nil on hosts without eth0

### ISSUE THREAD

**Issue by euank** [kubernetes/kubernetes#28407]
Captured from: https://github.com/kubernetes/kubernetes/pull/28195#issuecomment-229441908

The below is my best guess:

The `pkg/kubelet/network/DefaultInterfaceName` const of `eth0` is used by various container networking pieces to assume / work with the default interface within a container. This assumption, that within a container the interface is `eth0`, is generally true and so works. (cc'd people below; is this true?)

However, `kubelet/server/stats/summary` also uses this to determine what interface on the host should be looked at when examining node network stats, and predictable network naming under systemd results in that failing.

If it's a node stat we should perhaps just use all non-lo network interfaces for the stat? Maybe there's a better answer? 

Open questions:
1) Is the assumption of eth0 always right for containers (probably)?
2) Do we want to determine the default interface / subset of interfaces to use for node network stats in some smart way?

cc @vishh @timstclair 
cc @steveej @dcbw @freehan if any of you have knowledge / opinion on this

**Comment by stregatto** [comment]
https://github.com/kubernetes/kubernetes/issues/22319

> I think is a wrong assumption.
Perhaps it can be correct for standard pods, but pods can use the worker network (like kube-system's pods, api, controller, proxy, scheduler), this mean the pods do not use eth0 for sure but uses lot of different interfaces (enoX, bondX ... and so on).

**Comment by dcbw** [comment]
I'm working on ways to get the network interface that CNI plugins use back to kubelet here https://github.com/containernetworking/cni/pull/145.  That obviously doesn't help 'exec' plugins though, but exec is deprecated.  So:

> Open questions:
> 1) Is the assumption of eth0 always right for containers (probably)?

At this time yes.  In the near future, no.  But kubelet shouldn't care what the name is, it should simply use the name passed back from CNI.

> 2) Do we want to determine the default interface / subset of interfaces to use for node network stats in some smart way?

Yes, it should be the interface that owns pod.Status.PodIP, which we can more-or-less get from CNI after https://github.com/containernetworking/cni/pull/145 lands in CNI and we update the k8s CNI plugin.

**Comment by euank** [comment]
This issue manifests for `hostNetwork: true` containers as well, yeah. Verified on a non-coreos systemd machine, so I'm updating the title.

**Comment by steveeJ** [comment]
> Yes, it should be the interface that owns pod.Status.PodIP

AFAIU the question is how that is derived if `hostNetwork: true`. To help solve this issue I can throw in some questions:

1. What are the connectivity requirements for the chosen IP/interface?
2. Will this IP be unique among the cluster?
3. Will it depend on the kubernetes network plugin used on the node where the pod is run?

**Comment by timstclair** [comment]
@dashpole this is a good one to tackle if you have some spare cycles

**Comment by SEJeff** [comment]
This definitely affects RHEL7 or any newer distribution using consistent device naming. For us, `eno1` is the default onboard 1G interface, not `eth0`. Seeing that warning on every kubelet when `--v=4` is annoying to say the least.
