### ISSUE TITLE
NetworkPolicy not enabled

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#28401]
@thockin says NetworkPolicy works, but when I try a cluster with 1.3.0, I don't see it.
```
$ KUBERNETES_PROVIDER=gce curl -sS https://get.k8s.io | bash
... stuff happens....
$ kubectl version | grep Server
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"283137936a498aed572ee22af6774b6fb6e9fd94", GitTreeState:"clean"}
$ kubectl proxy &
$ curl localhost:8001/apis/extensions/v1beta1 | grep net
[nothing]
```

**Comment by thockin** [comment]
@caseydavenport

**Comment by thockin** [comment]
@kubernetes/sig-network

**Comment by bprashanth** [comment]
on my HEAD cluster:
```
curl localhost:8080/apis/extensions/v1beta1/networkpolicies
{
  "kind": "NetworkPolicyList",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "selfLink": "/apis/extensions/v1beta1/networkpolicies",
    "resourceVersion": "288220"
  },
  "items": []
}
```

Which is running: 
```
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.0.854+5252c8d4f64763-dirty", GitCommit:"5252c8d4f64763b4dd6ebbf6647b209e51ccd66f", GitTreeState:"dirty", BuildDate:"2016-06-26T18:39:03Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.0.854+5252c8d4f64763-dirty", GitCommit:"5252c8d4f64763b4dd6ebbf6647b209e51ccd66f", GitTreeState:"dirty", BuildDate:"2016-06-26T18:37:28Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

and 
```
--runtime-config=extensions/v1beta1=true,extensions/v1beta1/networkpolicies=true
```

So maybe it's just not on by default?

**Comment by caseydavenport** [comment]
@thockin - If I understand correctly, #26017 didn't go into v1.3.0.  So, while the apiserver still supports it in v1.3.0, it won't be enabled in kube-up clusters.

**Comment by thockin** [comment]
Damn.  Can we cherry pick JUST the --runtime-config setting, or should we
pick the whole PR?

@david-mcmahon

**Comment by david-mcmahon** [comment]
I suppose we have the start of a 1.3.1 train.

**Comment by bboreham** [comment]
I read it about five times, and as far as I can see #26017 adds code to set the `--runtime-config` if `NETWORK_POLICY_PROVIDER` is nonblank, and also sets `NETWORK_POLICY_PROVIDER` to `"none"` on GCE only.

For the purposes of this issue, wouldn't it be simpler to set the `--runtime-config` to enable `networkpolicies` unconditionally?

**Comment by caseydavenport** [comment]
@bboreham Yeah, I think that is _probably_ fine. 

The original intention was to not expose an API if there was nothing there to implement it - what do people think?

**Comment by bboreham** [comment]
Can you clarify how setting `NETWORK_POLICY_PROVIDER="none"` gives something different to "nothing there to implement it"?

**Comment by caseydavenport** [comment]
@bboreham - If it's setting the value to "none" then I think that is a bug according to the original intention.

**Comment by bboreham** [comment]
Well, like I say, I had to read it about five times and I'm still not sure, but I can't see it being set to anything else within #26017

**Comment by thockin** [comment]
I think it's fine to unilaterally enable - we believe it to be a beta-grade API, so people should be free to use it.

**Comment by caseydavenport** [comment]
I've opened https://github.com/kubernetes/kubernetes/pull/28549 to enable the NetworkPolicy resource by default and remove the funky logic in cluster/common.sh to set the runtime config.
