### ISSUE TITLE
Introduce Kubelet verify 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#28408]
Haven't thought through all the detail yet, but file this issue to carry more discussion ... 

Node team is working on node conformance test suites. The test suite can be divided into two set: System configuration verification and Kubelet functionality test (create, delete, etc.). The system configuration verification test suite can be repackaged as an image and run at node bootup time, or simply invoked through cli: kubelet verify. 

Based on Kubelet version, system configuration verification / sanity check test suite should validate the following configuration, and generate a report for the user:
- OS config: os distro, kernel version, kernel config etc. 
- runtime configuration based on the current Kubelet version
- Kubelet configuration (limit to the must-have ones, not those configurable ones)
- QoS related cgroups 

cc/ @kubernetes/sig-node

**Comment by dchen1107** [comment]
cc/ @Random-Liu

**Comment by vishh** [comment]
Is system configuration already part of node conformance test suite or is
that something yet to be defined?

**Comment by dchen1107** [comment]
@vishh Quota from above: "...node conformance test suites. The test suite can be divided into two set: System configuration verification and Kubelet functionality test ..." :-)

**Comment by yujuhong** [comment]
> Is system configuration already part of node conformance test suite or is
> that something yet to be defined?

I think it's not defined yet. @Random-Liu, are you working on that?

**Comment by Random-Liu** [comment]
We already have the first version introduced https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/environment/conformance.go. Thanks to @pwittrock.

And we'd make improvement based on it and put the system configuration verification part into `kubelet verify`.

**Comment by Random-Liu** [comment]
#26093 may be related.

**Comment by pires** [comment]
Is anyone owning this for 1.5?
