### ISSUE TITLE
[AWS] Error creating VPC Subnet

### ISSUE THREAD

**Issue by MichielDeMey** [kubernetes/kubernetes#28418]
I believe the issue is that we don't take into account that the Subnet availability zone can differ slightly from the  actual availability zone.

Relevant source line:
https://github.com/kubernetes/kubernetes/blob/f2ddd60eb9e7e9e29f7a105a9a8fa020042e8e52/cluster/aws/util.sh#L836

Editing the line and adding an "a" to the availability zone perameter resolved the problem.
I believe that when leaving out the availability parameter AWS will simply choose a zone for you.

EDIT: The same goes for the create-volume command:
https://github.com/kubernetes/kubernetes/blob/f2ddd60eb9e7e9e29f7a105a9a8fa020042e8e52/cluster/aws/util.sh#L468

Env vars:

```
export KUBERNETES_PROVIDER=aws
export KUBE_AWS_ZONE=eu-central-1
export NUM_NODES=2
export MASTER_SIZE=t2.nano
export NODE_SIZE=t2.nano
export AWS_S3_REGION=eu-central-1
export INSTANCE_PREFIX=k8s
export KUBE_OS_DISTRIBUTION=jessie
```

Output:

```
Creating vpc.
Adding tag to vpc-4e162a27: Name=kubernetes-vpc
Adding tag to vpc-4e162a27: KubernetesCluster=kubernetes
Using VPC vpc-4e162a27
Adding tag to dopt-ab0771c2: Name=kubernetes-dhcp-option-set
Adding tag to dopt-ab0771c2: KubernetesCluster=kubernetes
Using DHCP option set dopt-ab0771c2
Creating subnet.

An error occurred (InvalidParameterValue) when calling the CreateSubnet operation: Value (eu-central-1) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: eu-central-1b, eu-central-1a.
```

**Comment by justinsb** [comment]
To use kube-up, you have to specify a zone, not a region.  Some AWS API calls might auto-choose for you, but kube-up requires you to pick a zone.

**Comment by MichielDeMey** [comment]
Aha. Thank you for clarifying the issue at hand!
Could we improve the error message to let the user know about such a silly mistake? 🙂

**Comment by imsky** [comment]
+1 had to look through various shell scripts to figure this out

**Comment by Dmitry1987** [comment]
Sorry if it's a bit offtopic, but I have very related issue and don't want to open another thread for it.
I created my cluster with 1 AZ by default, and now added more minions in another zones, but pods that are created there - cannot use DNS resolution. Seems like K8s DNS service needs to be reconfigured in some way to support the new AZ and subnet?  I can't find this in the docs :(  can someone ( @justinsb ;) ) please point me to related docs? 

Thank you :)
