### ISSUE TITLE
Re-organize Samples

### ISSUE THREAD

**Issue by proppy** [kubernetes/kubernetes#2841]
- need more specific ones that hit a “use case” or “pattern” that highlight stuff that Kubernetes does well
- standardize a common organization between application code and configurations
  - example:
    
    ```
      app/main.go
      app/Dockerfile
      config/service.yaml
      config/controller.yaml
    ```
- want both end to end examples that shows 
  - a full app working
  - simpler examples that point out how individual features work for one issue
    - examples:
      - deploying a private image
      - exposing a service on an external IP 
    - could be seeded as stackoverflow questions

Part of #2633

**Comment by bgrant0607** [comment]
Somewhat obsolete
