### ISSUE TITLE
route-controller does not escape cluster name 

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#28436]
On GCE, if you create a cluster with a name like `gce.cluster.com`, then KCM will fail to create the routes, because it includes the cluster name in the route name, but does not escape it to meet GCE requirements.

See https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce.go#L2178

The following error is logged (lightly edited):

```
E0703 18:30:55.143973       5 routecontroller.go:130] Could not create route f7cc2ae4-4144-11e6-aeab-42010af00002 100.96.0.0/24 for node master-us-east1-c-kk5v after 188.406242ms: googleapi: Error 400: Invalid value for field 'resource.name': gce.cluster.com-f7cc2ae4-4144-11e6-aeab-42010af00002'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid
```

Possible solutions:
- In kops I have built an escaping that is URL inspired, but instead of %2F I use -2F
- We could just replace every invalid character with a dash or simply omit it.  We truncate this anyway, so we do expect collisions at this level (the nameHint is the node UUID and gives us uniqueness)

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
/area platform/gce
since we lack a sig-gcp at the moment

**Comment by abgworrall** [comment]
This relates to #24590
