### ISSUE TITLE
contrib: add a docker remote api bridge

### ISSUE THREAD

**Issue by proppy** [kubernetes/kubernetes#2843]
It would be nice to have a pod/service that expose the docker remote api, and translate it to v1beta3 API call to the master.

That way developers could be able to do things like:

```
kubectl create kuber/pod.yaml kuber/service.yaml
export DOCKER_HOST=$(kubectl get services kuber-service-id --ip)
docker run -d -p 8080:8080 -name hello busybox nc -p 8080 -ll -e echo hello world!
curl $(kubectl get services hello-service-id --ip):8080
```

**Comment by dims** [comment]
@proppy @brendandburns - Looks like this PR to swarm (https://github.com/docker/swarm/pull/2084/commits) will help with this use case. So can we close out this issue?
