### ISSUE TITLE
[k8s]k8s always pull image from https://index.docker.io/v1/, not from local host

### ISSUE THREAD

**Issue by vklonghml** [kubernetes/kubernetes#28433]
i run a k8s cluster in ubuntu 14.04
k8s version:1.2.5
docker version:1.11.2

there exits nginx image in local host, but when execute command:kubectl run my-pod  --image=nginx --port=80, it always pull image from url:index.docker.io, and shows problem as bellow:
 Failed to pull image "nginx": Error while pulling image: Get https://index.docker.io/v1/repositories/library/nginx/images: dial tcp: lookup index.docker.io on 162.3.140.90:53: server misbehaving

docker images shows as bellow:
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
httpd                            latest              b3d5273c8fd0        3 weeks ago         198.6 MB
nginx                            latest              0d409d33b27e        4 weeks ago         182.8 MB

does anybody know how to solve this problem, thanks.

**Comment by Random-Liu** [comment]
@vklonghml
The `ImagePullPolicy` controls the behavior of image pulling.
By default the `ImagePullPolicy` is `IfNotPresent`, which causes the Kubelet to not pull an image if it already exists.
However, if the image tag is "latest", k8s will set the default `ImagePullPolicy` as `Always`, which causes the Kubelet always try to pull again no matter what.

So, what you should do is:
1) Either write your own `.yaml` file to specify the `ImagePullPolicy`
2) Or give your image a proper tag.

`ImagePullPoilcy`: http://kubernetes.io/docs/user-guide/images/#updating-images

**Comment by vklonghml** [comment]
@Random-Liu thks a lot

**Comment by vklonghml** [comment]
@Random-Liu thks a lot
