### ISSUE TITLE
Kubernetes 1.3.0 on Ubuntu requires libltdl7 package

### ISSUE THREAD

**Issue by mikelorant** [kubernetes/kubernetes#28449]
Kubernetes 1.3.0 when installed on Ubuntu 15.10 (ami-ba98b0d9) gives the following error when running the docker binary.

```
# docker ps
docker: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory
```

This is easily solved by installing the package libltdl7:
apt-get install libltdl7

Are there any other workarounds to this issue?

**Comment by sp-joseluis-ledesma** [comment]
Found the same issue today. Launching a 1.3.0 kubernetes cluster with kube-up using wily distribution brings an unsuable cluster because libltdl7 is not installed.

**Comment by satheessh** [comment]
Got same error for version 1.3.4 .

Below is salt log.

Unpacking docker-engine (1.11.2-0~wily) over (1.9.1-0~wily) ...
dpkg: dependency problems prevent configuration of docker-engine:
 docker-engine depends on libltdl7 (>= 2.4.2); however:
dpkg: error processing package docker-engine (--install):
 docker-engine

**Comment by vroomvroomvroom** [comment]
and 1.3.7 .. trying 1.4 where it appears corrected.  
dpkg: dependency problems prevent configuration of docker-engine:
docker-engine depends on libltdl7 (>= 2.4.2); however:
Package libltdl7 is not installed.
dpkg: error processing package docker-engine (--install):
dependency problems - leaving unconfigured
Errors were encountered while processing:
docker-engine
