### ISSUE TITLE
Better service/ingress routing rules

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#28443]
## Motivation

If I was setting up frontend infrastructure on kube, I might do something like this:

```
L1 [ Ingress ]  service state     <- |
    |                                | per service Dos policy
(certs, geo)  --- (hostname, ip) --- [dos engine]
    | 
L2 [ Services ]  endpoint state
    | 
(enforces routing rules)
    | 
endpoints (produce web page)
```

Today, there's only 1 routing rule at the Service layer (rr to all endpoints), and 1 routing rule at the ingress layer (http hostname, path prefix match). This is insufficent to express more complex group membership patterns we see in PetSet (leader election, broadcast) and common routing patterns observed in tiered applications (retry GET, traffic splitting, consistent hashing to memcache farm). 
## Proposal

Add a new `RoutingRule` subtype and embed it either in the Ingress or Service. The subtype would implement rules like: 
1. Leader (https://github.com/kubernetes/kubernetes/issues/1542, https://github.com/kubernetes/kubernetes/issues/10456)
2. Broadcast (https://github.com/kubernetes/kubernetes/issues/12026)
3. Failover on error (It's been asked for before, can't find issue)
4. Hash based on incoming request or backend server (https://github.com/kubernetes/kubernetes/issues/8731)
5. Canary (https://github.com/kubernetes/kubernetes/issues/25485)
6. Vanilla lb algorithms 

I'd like L2 in the diagram above to implement the rules, because storing all endpoints at L1 might not be practical. In my mind L1 is the layer you can duplicate across the globe and use at the edge of your network, or even  in someone elses DC. 

I can't decide what L2 is, I'm tempted to say it's a Service but: 
- sticky session and lb algorithms are common at L1 and L2
- Services don't understand l7
- The most obvious way to implement a majority of the routing rules is through a webserver
- Ties in with the "internal ingress" concept
- Service is no longer a simple intra-cluster, low latency "dumb" routing abstraction

@smarterclayton @thockin @kubernetes/sig-network (we need a @kubernetes/lb)

**Comment by bprashanth** [comment]
@louiscryan and I were discussing having a `Type` field on the Ingress, and adding more experessive routing for intra-cluster traffic. Just a brain dump so it doesn't get lost. 

There are some core features that are synonymous with l7 proxies and I think it makes sense to keep them all in Ingress. This would move us closer to the Services model in some ways. 

To contrast todays use case with what I'm proposing: 

**Today**

nginx controller is a daemonset + hostPort. People run it in a pipeline, so we have: 
```
Cloud provider ingress with */* rule and TLS termination -> nginx ingress service -> pod
```
Users create: 
1. a single global CP ingress to handle cross cluster routing, with annotation `ingress.class=cloud`
2. a bunch of ingresses + configmaps with the annotation `ingress.class=nginx`

**Proposal**

An Ingress would be external by default  unless `Type=Internal`.  Internal Ingresses would get a cluster local DNS name that could point to a side car or node local daemon. 

nginx controller is still a daemonset + hostPort. People run it in a pipeline, so we have: 
```
Cloud provider ingress with */* rule and TLS termination -> nginx ingress service 
```
Users create: 
1. a single global CP ingress to handle cross cluster routing, with `Type=external`
2. a bunch of local ingresses with `Type=Internal`

`Type=external` would have to be cross platform, so basically it'll only expose a limited set of features (mostly what it exposes today). 

`Type=Internal` would have more expressive routing/loadbalancing/tls rules (https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/configuration.md).

The ingress rule specification is already open ended for such a situation: 
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/v1beta1/types.go#L872. In an ideal world, the 2 types would support exactly the same set of features and only differ in exposure to the internet, but till then, we'd probalby have to validate against certain situations. 

To use `Type=External` with a special, GCE specific feature like the CDN flag, one would still have to pipe through an annotation.

**Comment by smarterclayton** [comment]
In practice we find that people end up with multiple ingresses - usually
one per "network side" (internet vs intranet) but also sharded by business
unit and by authorization domain.

If your ingress controller is behind a Service Type=LoadBalancer (which
gets you cluster local DNS), why would you need the cloud provider ingress
rules modeled a different way?

**Comment by bprashanth** [comment]
Are you asking why we even need an L7 construct at the cloudprovider level vs a simple type=LB? 3 reasons come to mind: 
* TLS offload (secrets never hit kube)
* Features not available in type=lb (eg CDN, basic DOS protection, cross region loadbalancing etc)
* you could just stick with the cloudprovider's L7 feature set and go straight to your endpoints, preserving cross platform portability

**Comment by bprashanth** [comment]
But yeah, you can create a Service over the "Type=Internal" controller pods to get a cluster local DNS name, it's just another step. 

To me the more important part is that we ack and include more complex features in the basic Ingress api, because it doesn't make sense to limit an *internal* proxy to whatever features amazon or gce supports in the external, internet facing lb. It also doesn't make sense to invent a completely new api for internal l7 because of the overlap.

**Comment by smarterclayton** [comment]
Are you saying those forwarding rules are created outside Kube, rather than by a hypothetical controller in kube?  If so I agree, it just seemed that the implication was ingress *resulted* in those being created via external.  Why not just use the existing GCE API in that case?

I agree ingress should grow for internal use cases and features where the cloud providers are insufficient.

**Comment by smarterclayton** [comment]
on rereading i now understand.

The internal vs external distinction seems less portable - part of the value of ingress is that the end user doesn't control the mechanism for that ingress and thus their app works in multiple environments.  If I run a metal environment and want to reuse an app that has ingress, my ingress impl has to honor internal and external.

This feels more like "support levels" or nested scoping of features (L0, L1, etc).  Why not simply have the ingress ack whether it recognized all the features?

**Comment by bprashanth** [comment]
Yes I think the problem boils down to: how do we expose nested scoping? 

* events from the backend (bad ux, more than 50% of the internal rules will get vetoed by the cloud lb)
* another 2 phase system to ack, like initializers (ux is a little better, 50% problem still exists)
* apply synchronous validation keyed off `Type`

I also considered splitting routing rules out from the allocation of IP/DNS/security configuration, so basically you can hook up a Service to a set of routing rules and it gets IP etc based on its Type, but the same nested scoping problem exists there too.

**Comment by smarterclayton** [comment]
Separate rules into two categories:

1. Fundamental (absence is broken)
2. Advisory (system works better with them)

We're really only talking about fundamental (all advisory by definition can
be ignored).  Your gut is that cloud LB is one small grouping of
fundamental fields, and internal have infinite variants (I would agree)?

Is a controller that rejects any ingress that has rules it doesn't
recognize not something we should do anyway?  It's kind of like kubelet
when we add new features (init containers) that are fundamental to
operation (versioning

**Comment by louiscryan** [comment]
I'm not sure we can usefully have such a simplistic split between fundamental and advisory.

For example regex path matching is pretty standard in nginx but absent in ALB[1] which supports simple globs and Google[2] which only supports prefix matching with wildcards.The IngressRule is already allowing RegEx[3] (or at least the type doc is) so there's already some inherent conflict today. 

Is there a way to have vendor-specific ingress validation done synchronously?

[1] http://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#listener-rules
[2] https://cloud.google.com/compute/docs/reference/latest/urlMaps
[3] https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/v1beta1/types.go#L901

**Comment by louiscryan** [comment]
A little more fodder for thought...

Ingress already has to deal with an ordering problem over the matching rules. This works OK today as the matches are ordered by longest-common-prefix of host & path. This implicit ordering starts to fall over if you have greater dimensionality to your matching rules. e.g. match on path and a header.

For type='internal' the composition of multiple Ingress resources over a single hostname seems like an anti-pattern. IMHO I think folks will use this mechanism to create a named virtual service composed of other Services and to give it a stable DNS name. If this is true then the name of the Ingress resource is the host and host is never part of the routing rule.

A Type=Internal ingress routing rule can probably more concretely specify routing rules based on properties/labels on the origin pod of the traffic

We'd like Type=Internal to be able to work with sidecars so it seems pretty onerous to have to create Service Type=LB for this deployment mode. Improving the Ingress resource seems like the right approach

**Comment by bprashanth** [comment]
I really want to break this down into subproblems and I feel like there are at last 4 brought up till now:

1. More complex rules: we can ignore this for now. Lets pick *some* rule and plumb it through end to end, then iterate. 
2. Handling platform divergence
3. Dealing with conflict 
4. Intra cluster hostname DNS provisioning (i.e how do we route requests through the rule processing engine?)

1, 2 and 3 are common to most ingress controllers, internal and external. 

__Divergence__
My intuition on cross platform divergence is that there are actually 2 buckets: 

* "Unfixable": Different webservers have already adopted different standards, like the format of a regex. We can only do so much about this: 
  * document the LCD (`/foo/*` if cross platform, `/foo/[0-9]` is not)
  * throw async events from a backend if it encounters an unsupported format

* Validatable: we have some field on the Ingress (eg: type) that we match against some set of allowed rules/algorithms etc (eg: user isn't allowed to create an ingress with `{type=gce, algorithm=least-conns}`). 
  * When GCE supports least-conns, it will magically work. 
  * If user creates the ingress with `--ignore-unsupported` and a violating advisory field, GCE backend throws a warning event and replaces with some default (or drops it)
  * If user creates the ingress with `--ignore-unsupported` but has a violating required field, the backend still ignores the ingress, because there's no way to sanitize the path regex 

__Host DNS provisioning__
> If this is true then the name of the Ingress resource is the host and host is never part of the routing rule.

The name of the ingress resource becoming the host just means we insert a new DNS record for the name.  So user creates an ingress named foo, pod looks up foo and gets back a `127.0.0.1` ip, which it uses to talk to a local proxy that has a rule like `Host: *, path: /foo, path: /bar...`

However I think there's still a case for multiple Hosts in the rules because a user can simply mux Services on top of a common bank of internal ingress controllers (non-sidecar deployment). 

Maybe we can assume this problem will get solved when it's important enough and use an extra Service for now? it's easy to write a pod controller that watches ingresses with `type=Internal` and creates an extra Service for each.

**Comment by louiscryan** [comment]
I agree this is the right way of thinking about things, lets focus on 2-4 as that will unblock 1 over time.

I'm not sure the variation between unfixable and verifiable is sufficient to be worth the distinction. I like the idea of 'type' as a specifier for which proxy implementations the rule should work with which allows for validation, even static validation, if it refers to actual proxy implementations.

Another approach would be to allow environments to decide based on the requirements specified in Ingress to deploy a combination of proxies. For example use ALB for TLS termination at the edge but use nginx for complex routing requirements behind that. This would allow the Ingress rules spec to evolve in a more liberal fashion at the cost of greater complexity in the controllers.

I'm not sure about multiple-host Ingress resources for internal. Can't this be easily handled by multiple resources?

**Comment by bprashanth** [comment]
I think the original reasons we did multi-host are still valid, even in the internal case:
* atomic edits 
* Domain cross over (i.e blue green deployments via slightly different hostnames)
* Ux (i.e managing O(100) subdomains through O(100) api objects is hard)
* Admins can still enforce a single host policy via admission controller, but the other way around is a lot messier (i.e controller that aggregates the small ingresses into one multi-host map)

**Comment by bprashanth** [comment]
I'm wondering if we can we solve the validation problem through an admission controller, either by documenting deployment steps that always include once, or teaching each controller to install its own at boot time? 

It's an extra moving piece, but would give us sync backend specific validation.

**Comment by louiscryan** [comment]
@amb67

**Comment by louiscryan** [comment]
I'm not entirely sold on multi-host for internal.

ux & atomic edits - The grain of ownership is probably closer to that of a pod or deployment and so edits are tied to a set of services that span that. This is quite different to mapping a large no. of services behind a single DNS name addressed by the public internet.

domain cross over - Having a single DNS addressable name for routing over multiple services clearly allows for this. Better routing controls would allow for blue-green without requiring multiple hostnames to be exposed to the application layer.

**Comment by louiscryan** [comment]
@rshriram

**Comment by rshriram** [comment]
Are the improvements/issues suggested above targeted at HTTP only? 
What if I want to use ingress for managing TCP services, with similar requirements, i.e., route a portion of traffic to a different version of the service.  I think this relates to https://github.com/kubernetes/kubernetes/issues/23291

**Comment by bprashanth** [comment]
Yeah, we will have to figure out TCP+Ingress. Either way I feel like the common denominator is first agreeing upon how to validate, reject or enforce routing policy across different backends that don't support the same core rule set (eg: internal ELB vs common cluster level nginx vs sidecar proxy).
