### ISSUE TITLE
Higher fidelity health checks

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#28442]
## Motivation

Today health checks suffer from at least 2 limitations
- Long pipeline: readiness -> kubelet -> master -> endpoints controller -> kube-proxy -> iptables
- Dead nodes cause unacceptable downtime: because the health status is push based, we only mark an endpoint unready after 40s

There are a few ways to handle this:
- Kube-proxy uses connection information to mark endpoints unhealthy: somewhat risky IMO, because TCP has elongated timeouts and endpoints might get marked unhealthy because of a network blip. Health checks should be declarative, I think we got this part right with readiness probes, each application knows its requirements.
- We require each service to be backed by a webserver that handles the probes: requires an actual pod to back the Service, which involves a userspace bounce and more failure modes.
- This proposal
## Proposal
1. Each node runs a daemon that consist of a node local readiness checker (local-hc) and a http server exporting cluster wide endpoints (proxy-hc)
2. Form a cluster wide mesh of proxy-hc
3. localhost proxy-hc exports `/svcname -> []ip:port{}` as union of local-hc x all other proxy-hc
4. Kube-proxy hits localhost HC daemon every second

```
            | proxy hc |    ---         | proxy hc |
                 |         /svc1            |
                 |         181.1,.2         |
            local hc                    local hc
               /   \
        svc1 [181.1] [181.2]
```

I think this will scale as long as we don't mesh ubernetes. We could even enrich proxy hc to query something like heapster for utilization info. 

@smarterclayton @thockin @kubernetes/sig-network

**Comment by bprashanth** [comment]
For this to scale each proxy-hc probably needs to aggregate health checks from N local-hcs. One way to achieve this is to deploy it as a petset, proxy-hc-0 is responsible for nodes {0-N}. When we grow the cluster a new proxy-hc-X is deployed, and existing proxy-hcs discover it the normal way pets discover each other (periodically resolve DNS for the governing service and notice extra SRV records).

**Comment by thockin** [comment]
Just to understand: The local checker invokes the probes that kubelet
invokes today?  Instead of kubelet or in addition to?  At the same rate as
kubelet or faster?  Is it generally safe to call a probe more often than
the pod spec requests?

Once the local checker has state on local pods, it gossips that out to
other nodes?

What is the information flow here, vs what we have today:

pod A readiness -> local-A HC -> proxy-A HC -> proxy-B HC -> kube-proxy-B -
iptables ?

**Comment by bprashanth** [comment]
Not gossip, each proxy-hc hits all the others. The health checks are pulled from local-hc not pushed, which avoids the 40s node death timeout. And the proxy-HCs can survive regardless of master connectivity, avoiding issues like https://github.com/kubernetes/kubernetes/issues/26865. 

It also cuts out 2 write hops, kubelet to etcd, endpoints controller to etcd. Everythings in memory and if something restarts it doesn't report status till its done a round of health checking. 

Writing readiness to etcd is still good for clarity, but does it need to hold up kube-proxy noticing endpoints?

**Comment by smarterclayton** [comment]
What about other sorts of proxies like egress or cloud API servers?
Agree we can do higher fidelity, but are you proposing slowing
readiness or just having it be orthogonal?

We already have unready endpoints, so this case effectively supports that.

**Comment by bprashanth** [comment]
I think just modifying push to pull and get rid of the 40s timeout issue would be a win. 
I agree that everything would need to know how to figure out health check of endpoints in a given bucket of nodes/region/cluster, and apiserver is probably the best aggregation point for that, but the proxy-hc can update apiserver too.

**Comment by smarterclayton** [comment]
So a couple of counter points (discussion points, at minimum).  IPtables
sucks w.r.t. failover - if we did IPVS (or for someone integrating HAProxy)
we'd have integrated connection health checking and failover (of a form).
We would still want external health checking driving that obviously - but
we'd also want the info from those backends (did you connect).  I worry
about the HC not having all the info to make the right decision - the
observable form of "these connections are failing" may be completely
counter to what the HC is saying.

**Comment by bprashanth** [comment]
Doesn't that still suffer from "what about cloud api servers" problem? (anything like ingress that needs health checks but isn't going through ipvs). 

If the false negatives are low connection level health in addition to normal readiness checking sounds like an overall win, no doubt.
