### ISSUE TITLE
PV with GlusterFS disk-encryption

### ISSUE THREAD

**Issue by aga20** [kubernetes/kubernetes#28454]
Hi guys!

Maybe isn't exactly an issue... We are using GlusterFS cluster to PV and PVC. It works good until we try to enable glusterfs disk-encryption (see: http://www.gluster.org/community/documentation/index.php/Features/disk-encryption ). Without PV I can mount the encrypted cluster when I put the master key to a specified path (for example /etc/glusterkey/master_key) on the client (on server I set this path and I try mount -t command, and it worked). But when I tried to use this volume with PV I got this: 

> Unable to mount volumes for pod "pref2_default(46ce58be-41b0-11e6-ad08-fa163e786339)": unsupported volume type

So have you got any idea? Anybody try to use these two feature each other? I didn't foud any parameter, where I can set the encryption key to PV. 

Thanks!

**Comment by alikhajeh1** [comment]
@aga20 did you find a way to use gluster encrypted volumes with k8?

**Comment by kargakis** [comment]
@kubernetes/sig-storage-misc

**Comment by rootfs** [comment]
@humblec

**Comment by alikhajeh1** [comment]
Any update on this? I created https://github.com/gluster/gluster-kubernetes/issues/157 but haven't seen any updates from that issue either.

**Comment by wattsteve** [comment]
@alikhajeh1 I think this needs to get added first in gluster/gluster-kubernetes and then we need to make the necessary adjustments in k8s to the gluster vol plugin and provisioner. I am going to prod the gluster-kubernetes community to get you a response on your question.

**Comment by humblec** [comment]
@alikhajeh1 As Steve mentioned, we need to add the support in heketi first and then call it from the provisioner. The provisioner part is already in WIP https://github.com/kubernetes/kubernetes/pull/44174

**Comment by humblec** [comment]
@rootfs Can you assign this issue to me ?

**Comment by aga20** [comment]
Hello,

sorry for late reply I didn't get any notification. 
@alikhajeh1 Maybe this can be helpful for you: now we create own gluster volumes (we don't use hekete, etc...) and we created an encrypted volume too. We specify theencyption key/keypath during the volume creation. We set this keypath: /etc/glusterfs/key. You have to share this key with the other nodes who will use the encrypted volume and on these nodes you have to put the key to the path what you set on the server (/etc/glusterfs/key)! After this the encripted pv and pvc will work. :) 

Maybe you can close this issu, thanks!

**Comment by alikhajeh1** [comment]
@humblec / @wattsteve just trying to understand how the flow would work... so that would enable users to create a PVC with their own encryption key (stored in a secret?) and have the PV dynamically create the encrypted volume? Would the secret then need to be mounted in the deploymentconfig to enable the PVC to be used?

**Comment by alikhajeh1** [comment]
@humblec / @wattsteve bump
