### ISSUE TITLE
Infinite retries of PersistentVolume POSTs

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#28451]
During all our tests we see one PV POST that succeeds:
```
I0704 03:06:46.999538       5 handlers.go:165] POST /api/v1/persistentvolumes: (139.86986ms) 201 [[kubectl/v1.3.0 (linux/amd64) kubernetes/caf9a4d] 127.0.0.1:36472]
```
All consecutive ones return 409 and are retried every 10s:
```
I0704 03:08:45.698643       5 handlers.go:165] POST /api/v1/persistentvolumes: (114.515217ms) 409 [[kubectl/v1.3.0 (linux/amd64) kubernetes/caf9a4d] 127.0.0.1:36942]
...
I0704 03:08:55.917765       5 handlers.go:165] POST /api/v1/persistentvolumes: (124.657052ms) 409 [[kubectl/v1.3.0 (linux/amd64) kubernetes/caf9a4d] 127.0.0.1:36962]
...
```
Some runs of our scalability tests are failing on PV POST latencies.

cc @wojtek-t @fgrzadkowski @saad-ali

**Comment by gmarek** [comment]
Originally I expected that it's the problem with https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/controller.go#L1167

But I don't see the logs from this `for` loop anywhere, so it's probably something different. In this loop we can fail early if we get a 409 response, but I don't think it's critical. I'll leave it to @saad-ali to investigate further.

**Comment by gmarek** [comment]
A thought - it may be addon-updater's fault.

**Comment by saad-ali** [comment]
@jsafrane

**Comment by jsafrane** [comment]
@gmarek, can you provide me full controller-manager log with log level 4? And what kind of test are you running? As you pointed out, if the volume controller cannot save a PV to API server it will retry 5 times with 10 seconds interval and then it will delete the storage asset (most probably GCE PD). After that, the controller will try again in 15 seconds, creating a new GCE PD and saving corresponding PV to API server 5 times in 10 sec. interval and this goes ad infinitum until the API server accepts the PV.

Or, this is a red herring and you run `kube-controller-manager --pvclaimbinder-sync-period=10s`, then it can be any save performed by the controller and there are many of them. I am blind without the logs.

**Comment by gmarek** [comment]
This is fixed in #28467 - as mentioned above it was addon-updater fault, as it wasn't correctly handling non-namespaced objects, such as PVs.

**Comment by jsafrane** [comment]
I'm closing this issue then.

**Comment by gmarek** [comment]
#28467 is not merged yet.
