### ISSUE TITLE
InfluxDB PersistentVolume creation sometimes takes long time.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#28456]
It seems that it's used by admission control:
```
I0704 08:14:07.850832       5 trace.go:61] Trace "Create /api/v1/persistentvolumes" (started 2016-07-04 08:14:05.558101565 +0000 UTC):
[26.368�s] [26.368�s] About to convert to expected version
[183.455�s] [157.087�s] Conversion done
[2.289778236s] [2.289594781s] About to store object in database
[2.292619875s] [2.841639ms] Object stored in database
[2.292624006s] [4.131�s] Self-link added
[2.292692166s] [68.16�s] END
```

This sometimes makes us violate our 1s SLO for API calls. Why admission takes so much time?
cc @wojtek-t @fgrzadkowski @derekwaynecarr @saad-ali

**Comment by derekwaynecarr** [comment]
I suspect its related to this:

https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/persistentvolume/label/admission.go#L83

and it tries to make a call-out.

cc @justinsb - would this make sense to you as a culprit of slowdown?

**Comment by justinsb** [comment]
This does make sense, yes - thanks @derekwaynecarr .  Three options:

1) don't make that SLO guarantee
2) move the labelling to another controller.  But then we have a PV in an odd state where it is not yet "fully created"
3) skip auto-labelling if the volume is already labeled, and the caller would have to label to get the SLO guarantee

I think option 1 is the best, though I realize that may not be an option.  Option 3 would let us meet the SLO guarantee, but is pretty artificial.  Option 2 would likely introduce weird race-condition bugs unless we put the volume into Status=Pending initially, and then moved it into Status=Available once it was labeled.  That wouldn't be too bad, it's just a question of whether it is worth it.

Note that we are also validating the existence of the volume here, which is a nice sanity check.

I'm inclined to say that PVs are special: they are not "pure k8s" resources.  They are actually us "importing" external resources into k8s.  This is also an admin action, not a user action.

**Comment by gmarek** [comment]
cc @wojtek-t

**Comment by krousey** [comment]
@derekwaynecarr @justinsb This has been marked with the "needs attention" label and needs to be addressed for the 1.4 release. Could you please

- close if it's fixed
- update on your progress to fix it
- make a case for it not to block the release
- or find a new owner who can do one of the above soon.

Once you or the new owner update this issue and are actively working on it, you can remove the "needs attention" label.

**Comment by gmarek** [comment]
My feeling is that it was fixed by the revert of a PR that changed influxDB to a pet set, but someone should confirm this. @jszczepkowski

**Comment by wojtek-t** [comment]
Well - whatever happened, we are not seing this again.

So spending time to actually understand what exact change fixed it is probably not the best idea.
So I'm closing this one.
