### ISSUE TITLE
[Proposal] Integrate kube-DNS with external DNS

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#28453]
I'd like to draft a  proposal on integrating Kube-DNS with external DNS, e.g. Mesos-DNS; if any comments/suggestions, please let me know.

**Comment by luxas** [comment]
cc @kubernetes/sig-network

**Comment by thockin** [comment]
While we're certainly not against changes of any flavor, we have to understand the motivations and the benefits.

**Comment by thockin** [comment]
sorry, did not mean to close

**Comment by girishkalele** [comment]
@k82 

Do you mean integrating them into a single software component or a proposal to enhance DNS interoperability between Kubernetes and Mesos clusters ?

**Comment by k82** [comment]
@thockin , the motivation is that: when using `k8sm` (Kubernetes on Mesos), there're some other frameworks (e.g. Spark) on Mesos would like to access Pod (e.g. FTP server) by name.

@girishkalele , both solutions are candidates; currently, I prefer single component: let `kube-dns` get `name<->IP` mapping information from Mesos, and let Mesos configure DNS server; I'm going to do more investigation about those solutions.

**Comment by k82** [comment]
@thockin , does it make sense ? :).

**Comment by thockin** [comment]
As I said - we're open to ideas.  We probably don't want to carry a ton of baggage in-core JUST for mesos, but if we can describe the need in generic terms maybe we can come up with something we want anyway, win-win.

Details needed...

**Comment by k82** [comment]
Got your point; more generic term & more details. I'll draft a summary :).

**Comment by bprashanth** [comment]
Fyi you can already get predictable dns names for pods with kube-dns, either through a pod annotation (1.2) / field (1.3), or through petset (1.3). 

https://github.com/kubernetes/kubernetes/blob/master/build/kube-dns/README.md#a-records-and-hostname-based-on-pods-hostname-and-subdomain-fields
https://github.com/kubernetes/kubernetes.github.io/blob/release-1.3/docs/user-guide/petset.md#network-identity

**Comment by aronchick** [comment]
Would this be publishing Kube DNS to Mesos? Or the reverse? 

Integrating with external DNS _is_ a goal for 1.4, so the proposal, in the feature directory, may have some good overlap.

**Comment by k82cn** [comment]
@aronchick , I'm also thinking to integrate kube-dns with external DNS. Kube-DNS and Mesos-DNS is an example of it.

Is there any issue tracing the integration?

**Comment by thockin** [comment]
I have less confidence than David does that it will happen in time for the
next release.  Help wanted, starting with design docs.

**Comment by k82cn** [comment]
Got that. I can draft an design docs based on my understanding :).

**Comment by thockin** [comment]
Closing for now, please come back when a proposal is ready

**Comment by k82cn** [comment]
Sure :).

**Comment by gfrankliu** [comment]
Does the proposal cover "forwarder" to other dns servers case?
We have a few internal dns zones hosted on our private dns servers using GCE instances, but containers in GKE can't resolve hosts in those internal zones. Is it possible for the GKE (in same project) dns service to have those special zones as forwarders zone to point to the private dns servers in GCE? I see others asked the same question on serverfault but with no reply: http://serverfault.com/questions/813393/kubernetes-to-resolve-custom-internal-nameserver

**Comment by thockin** [comment]
This is being resolved in 1.6, I think.

@bowei

**Comment by k82cn** [comment]
>This is being resolved in 1.6, I think.

@thockin , which feature?

**Comment by bowei** [comment]
@k82cn: https://github.com/kubernetes/kubernetes/pull/42147.

**Comment by k82cn** [comment]
@bowei , thanks; I'll try it :).

**Comment by gfrankliu** [comment]
I checked the link @bowei provided and it talks about IP alias. How is it related to kube-DNS we are discussing here?

**Comment by bowei** [comment]
sorry! I pasted the wrong link: https://github.com/kubernetes/kubernetes/pull/41826

**Comment by k82cn** [comment]
@bowei , thanks :).

**Comment by bowei** [comment]
Forwarding to a custom upstream resolver is available in 1.6

http://blog.kubernetes.io/2017/04/configuring-private-dns-zones-upstream-nameservers-kubernetes.html
