### ISSUE TITLE
Propose to introduce a new flag "--executor-id" to K8sm scheduler

### ISSUE THREAD

**Issue by qianzhangxa** [kubernetes/kubernetes#28457]
Hi,

I see currently K8sm scheduler will generate the executor ID with a hash calculation (https://github.com/kubernetes/kubernetes/blob/master/contrib/mesos/pkg/scheduler/executorinfo/id.go#L33), but I am not sure why a hash calculation is needed here. @jdef, can you please help?

I think we can simplify it by just introducing a flag (e.g., "--executor-id") to K8sm scheduler so that an executor ID can be manually assigned when starting K8sm scheduler.

Any comments/suggestions are welcome, thanks.

**Comment by jdef** [comment]
we used hashing to determine the executor ID in order to avoid task launch
attempts on incompatible executors. executorsInfo's used to launch new
tasks on a running executor must be identical to the executorInfo
originally used to launch the executor in the first place. otherwise Mesos
will refuse to launch the new tasks. we attempt to bypass this failure mode
and refuse offers from incompatible executors

**Comment by jdef** [comment]
Is there an additional use case for avoiding hashes?

**Comment by qianzhangxa** [comment]
Thanks @jdef for your comments!

>  otherwise Mesos will refuse to launch the new tasks.
Can you please elaborate why Mesos will refuse to launch the new tasks? My understanding is, if framework tries to launches a task whose executor ID is new to Mesos agent, the agent will launch the executor (e.g., "km minion") first rather than refusing the task, right? 

I understand the hashing is used to determine the executor ID. However my concern is, "--advertised-address" is also used in the hashing, that means in a K8sm HA environment (there will be multiple master nodes), every time when I start "km scheduler" in a master node, I have to specify a VIP as the value of "--advertised-address" rather than the real IP of that master node, so I have to introduce a component for VIP management (e.g., keepalived, ucarp). But if we just simply introduce a flag "--executor-id" to K8sm scheduler as I proposed, we do not need that VIP at all, I just need to ensure the same value is specified to this flag when starting scheduler (regardless on which master node).

**Comment by jdef** [comment]
yes, a slave running w/ kubelet-executor-id 1 would spin up a brand new
executor instance if you restarted the scheduler configured to launch tasks
using kubelet-executor-id 2. how do you propose to handle running multiple
kubelet-executors (and kube-proxy's) on the same agent instance? i'd expect
that, without additional kubelet-executor changes, havoc would ensue.

an alternative might be to update k8s-mesos to leverage the mesos/next Go
bindings that use the mesos v1 http APIs. mesos UPIDs (IP addresses) are no
longer important in that API and you can advertise (to the executors) the
node name that runs the scheduler using DNS (perhaps via mesos-dns). you'd
be swapping VIPs for DNS but that's probably much easier to set up yes?

i'm **very reluctant** to approve a change that allows an operator to
hardcode executor ID for other reasons as well. if the k8s-mesos framework
decides to use that field for some other purpose down the line we'll break
some measure of backwards compat if admin's become reliant on it as a flag.
it exposes something very internal to the API of mesos that's better left
under the covers. ultimately the framework should be managing all IDs --
not admins.

**Comment by qianzhangxa** [comment]
I am not proposing to have multiple kubelet-executors running on the same agent instance :-) I just wanted to confirm with you that is NOT _Mesos will refuse to launch the new tasks_, actually it is K8sm scheduler tries to make sure there can be only one kubelet-executor on an agent, if the existing one on the agent is not compatible, it is K8sm scheduler to decline the offer of that agent, rather than Mesos to refuse to launch the new tasks (actually K8sm scheduler will not launch any new tasks on that agent at all since the offer will be declined). The guard is in K8sm scheduler rather than in Mesos side.

And are you suggesting to specify the hostname of the node on which K8sm scheduler is running as the value of "--advertised-address" when starting K8sm scheduler on that node? But in an HA environment, there will be multiple master nodes, the node on which K8sm scheduler is running may fail, and we need to start it on another master node, that means after master node failover, the value of "--advertised-address" will be changed? I do not think we can do it because that way K8sm scheduler will generate different executor ID.

Can we simply exclude "--advertised-address" from the hashing? I see it is part of ExecutorInfo.CommandInfo.Uris, so is it possible we do not include ExecutorInfo.CommandInfo.Uris in the hashing?
https://github.com/kubernetes/kubernetes/blob/master/contrib/mesos/pkg/scheduler/executorinfo/id.go#L89:L98
