### ISSUE TITLE
Cannot deploy more than one pod per node with custom metrics

### ISSUE THREAD

**Issue by sanderploegsma** [kubernetes/kubernetes#28452]
I am having problems autoscaling an application using custom metrics. Due to the fact that it uses websockets, I would like to scale based on the number of connections instead of CPU. I followed [this documentation](https://github.com/mwielgus/kubernetes.github.io/blob/custom-metrics/docs/user-guide/horizontal-pod-autoscaling/index.md#support-for-custom-metrics), which states that I have to use a `HostPort` mapping for cAdvisor to be able to scrape the Pod's metrics. This design, however, limits the amount of Pods per node to 1. 

I'm not sure why this is the way it works, shouldn't it be possible to run a multitude of Pods on each node?

**Comment by philips** [comment]
cc @timstclair as I can't attach cadvisor labels to this myself.

**Comment by vishh** [comment]
Custom metrics based autoscaling is an alpha feature for reasons like
these.

**Comment by nvartolomei** [comment]
Is there any other way to expose custom metrics? I saw this propsal https://github.com/kubernetes/kubernetes/blob/release-1.3/docs/proposals/custom-metrics.md

**Comment by ddysher** [comment]
@vishh is there any updates on custom metrics?

**Comment by sanderploegsma** [comment]
The proposal in this form has been discontinued: https://groups.google.com/d/msg/kubernetes-users/0F2OMVArr1A/7tY_eoP_AAAJ
