### ISSUE TITLE
Clarifying API Guarantee on ListOptions.ResourceVersion

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#28472]
Currently in ListOptions, the docs \[[link](https://github.com/kubernetes/kubernetes/blob/ef0c9f0c5b8efbba948a0be2c98d9d2e32e0b68c/pkg/api/types.go#L2229-L2230)\] says "(no effect on list yet)".

However, in storage.Interface, List API has ResourceVersion ([link](https://github.com/kubernetes/kubernetes/blob/ef0c9f0c5b8efbba948a0be2c98d9d2e32e0b68c/pkg/storage/interfaces.go#L127)):
```
List(ctx context.Context, key string, resourceVersion string, ...)
```

Even worse, the behaviors are inconsistent. While the implementation in etcd_helper ignores it, cacher uses it and needs to wait until the cached global resource version has caught up.

We need to clarify this inconsistent behavior and API guarantee on ListOptions.ResourceVersion. According to the api, we should totally ignore it. If so we shouldn't even have it passed down to storage layer.

**Comment by hongchaodeng** [comment]
@xiang90 @lavalamp @kubernetes/sig-api-machinery

**Comment by smarterclayton** [comment]
The desire was to support it for causal consistency for clients.  So I think we want to fix etcd_helper.

**Comment by xiang90** [comment]
@smarterclayton So the doc here: https://github.com/kubernetes/kubernetes/blob/ef0c9f0c5b8efbba948a0be2c98d9d2e32e0b68c/pkg/api/types.go#L2229-L2230 is wrong?

**Comment by smarterclayton** [comment]
That comment predates the watch cache by at least a release.  As we found
in OpenShift, watch cache added capabilities that were not 100% reflected
back into etcd_helper (since all Kube resources were switched to watch
cache).

Allowing future reads is valuable.

**Comment by hongchaodeng** [comment]
I would like to add a test for it to make sure on the capabilities/guarantees.
But I need the exact answer for whether this api:
```Go
type ListOptions struct {
	...
	// The resource version to watch (no effect on list yet)
	ResourceVersion string
}
```
is still right? Yes or no?
If No, is the behavior on cacher/watch_cache the desired behavior that we should test?

**Comment by wojtek-t** [comment]
@hongchaodeng - the comment is no longer true; and yes - the bahavior of etcd_helper and cacher are inconsistent.

Basically the ResourceVersion for List should have the semantic:
- if unset (or zero), there is basically no guarantee on what List will return
- if set, it should return a result that is at least as fresh as the given resourceVersion

This semantic is implemented in cacher.

**Comment by hongchaodeng** [comment]
Thanks for clarifying.
I will add a test to make sure that and also change the comment.

**Comment by hongchaodeng** [comment]
Add a test: #28524

**Comment by hongchaodeng** [comment]
Fixed
