### ISSUE TITLE
`util.sh` in `cluster/azure/` seems to be trying to export Bash arrays, but that's not supported

### ISSUE THREAD

**Issue by ruiwen** [kubernetes/kubernetes#28482]
v1.3.0

Background
I was trying to use `kube-up.sh` to set up a cluster on Azure, but the script seemed not to take my `AZURE_RESOURCE_GROUP` envvar, so I started poking around `cluster/azure/util.sh`

In `get-common-params()` on Line 167, the script first declares some array variables, like so
```
declare -a AZKUBE_AUTH_PARAMS
declare -a AZKUBE_DOCKER_PARAMS
declare -a AZKUBE_RESOURCE_GROUP_PARAM
```

In the middle, on Line 182 and 186, it attempts to assign to entirely different variables,

Line 182 (assuming the appropriate assignee here is `AZKUBE_DOCKER_PARAMS`)
    
    docker_params+=("--net=host" "--env=https_proxy=${AZURE_HTTPS_PROXY}")

Line 186 (assuming the appropriate assignee here is `AZKUBE_RESOURCE_GROUP_PARAM`)

    resource_group_params+=("--resource-group=${AZURE_RESOURCE_GROUP_PARAM}")

And it goes on to export the above variables on Line 191

```
 export AZKUBE_AUTH_PARAMS
 export AZKUBE_DOCKER_PARAMS
 export AZKUBE_RESOURCE_GROUP_PARAM
```

However, in GNU Bash 4.3 (on Ubuntu 16.04), the bash manual states, under the `BUGS` section, 

    Array variables may not (yet) be exported.

Which means the above `AZKUBE_*` variables likely aren't being exported properly.

True enough, inserting an `env` or `export` in `azure-deploy()` under the `get-common-params` call, shows that the `AZKUBE_*` variables do not exist in the environment immediately prior to running the `colemickens/azkube` container.

This seems to break `kube-up.sh` when wanting to setup a cluster in a particular Azure Resource Group. The cluster comes up just fine, just that `kube-up.sh` doesn't see the user-defined Resource Group name, and attempts to set its own based on the assigned deployment id.

Expected:

Setting `AZURE_RESOURCE_GROUP_PARAM` (it's listed as `AZURE_RESOURCE_GROUP` in the docs), then calling `kube-up.sh` should set up the cluster within the given Resource Group

Actual:

The `kube-up.sh` script doesn't seem to receive the value set in `AZURE_RESOURCE_GROUP_PARAM` and creates a new resource group with a name based off the assigned `AZURE_DEPLOY_ID`, which is very unexpected.

**Comment by colemickens** [comment]
This can assign this to me. I'll look at it asap.

**Comment by ruiwen** [comment]
Thanks!

**Comment by colemickens** [comment]
Thanks for the detailed bug report @ruiwen. I've sent a PR with a fix: https://github.com/kubernetes/kubernetes/pull/28700
