### ISSUE TITLE
External Load Balancer doesn't support UDP

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#2849]
We don't currently support creating external UDP load balancers.  We should.

**Comment by dicato** [comment]
:+1: on supporting this.

**Comment by austintrose** [comment]
I could also really use this!

**Comment by dicato** [comment]
@brendandburns for clarity, what component is this limitation in? I'd assume `kubelet`?

Does this same limitation apply to container optimized GCE images? I'd assume so.

Thanks!

**Comment by statik** [comment]
I need this functionality as well. Anything I can do to help fix or enable this?
I'd also be interested in any workaround where I could manually create the GCP network load balancer with UDP enabled and point it at my k8s service.

**Comment by kshelton** [comment]
Parent  3837f8c was against 1.0.3

**Comment by kshelton** [comment]
Any feedback on the UDP LB implementation?

**Comment by discordianfish** [comment]
As far as I can tell, the only missing bits are the actual cloud provider integration, right? The services already support udp, so it's just a matter of configuring the right rule on external LBs?

**Comment by cmluciano** [comment]
/close

That's correct. Since this is supported in kube-proxy, ingress/nginx, etc. this issue should be closed. External cloud providers will adopt the codebase at their leisure.

**Comment by discordianfish** [comment]
@cmluciano So that means if I want to support for this on GCP, I should open a new issue to track udp support specifically for that cloud provider integration? Or does that already exist and I just missed it?

**Comment by cmluciano** [comment]
Yes please open an issue for GCP explicitly.
