### ISSUE TITLE
ScheduledJob tutorial/example?

### ISSUE THREAD

**Issue by csimplestring** [kubernetes/kubernetes#28496]
Hi,

The new version 1.3 now supports the ScheduledJob, but I can not find any documentations or related examples. Can anyone help to provide some documentation or tutorial for the ScheduledJob?

Thanks a lot.

**Comment by dims** [comment]
@smarterclayton @soltysh is this related to work in https://github.com/kubernetes/kubernetes/issues/2156 ? (As in the feature is not fully implemented yet?)

**Comment by soltysh** [comment]
@csimplestring unfortunatelly the feature is not fully implemented as @dims mentioned. It's targeted for 1.4. Once it's in I'll make sure to have a working example, that's for sure :)

**Comment by pwittrock** [comment]
@janetkuo Would you coordinate this?

**Comment by janetkuo** [comment]
I'm drafting a SJ document, will be put under kubernetes.io > Reference > Glossary > Scheduled Job

**Comment by janetkuo** [comment]
The SJ doc should be merged into release-1.4 branch instead of master, so I created another PR https://github.com/kubernetes/kubernetes.github.io/pull/1123

**Comment by soltysh** [comment]
The 1.4 branch PR merged and the other is already opened, I'm lowering this to P1 and will close as soon as the other merges.

**Comment by pwittrock** [comment]
@soltysh @csimplestring @janetkuo   I am moving this out of the blocking issues we are tracking for the 1.4 release.  If there is still 1.4 work to be done here that should be tracked in the weekly burndown meetings, move it back and provide daily updates to this issue.

**Comment by janetkuo** [comment]
The doc is now live http://kubernetes.io/docs/user-guide/scheduled-jobs/, closing

**Comment by jonathanbl** [comment]
Hi, 

Is there a reason why the link http://kubernetes.io/docs/user-guide/scheduled-jobs/ is not accessible anymore?

Thank you

**Comment by ernestoalejo** [comment]
They have been renamed:
http://kubernetes.io/docs/user-guide/cron-jobs/
