### ISSUE TITLE
get.k8s.io fails on AWS (1.3.0)

### ISSUE THREAD

**Issue by dstynchula** [kubernetes/kubernetes#28505]
# This is the script I used to bring up the cluster.
# The vpc_id is for a VPC named 'PROD'
# That vpc has a 172.30.0.0/16 CIDR and 172.30.2.0/24 is not in use.

export KUBERNETES_PROVIDER=aws
export KUBE_AWS_ZONE=us-east-1a
export AWS_DEFAULT_PROFILE=QA
export MASTER_SIZE=m3.medium
export NODE_SIZE=t2.micro
export NUM_NODES=1
export AWS_S3_REGION=us-east-1
export AWS_S3_BUCKET=PROD-kubernetes-1
export KUBE_AWS_INSTANCE_PREFIX=PROD
export AWS_SSH_KEY=~/.ssh/id_rsa
export VPC_ID=vpc-<redacted>
# networking setup

export KUBE_SUBNET_CIDR=172.30.2.0/24
# Bring er up!

curl -sS https://get.k8s.io | /bin/bash

**Comment by dstynchula** [comment]
Using subnet CIDR override: 172.30.2.0/24
... Starting cluster in us-east-1a using provider aws
... calling verify-prereqs
... calling kube-up
Starting cluster using os distro: jessie
Uploading to Amazon S3
Creating PROD-kubernetes-1
make_bucket: s3://PROD-kubernetes-1/
Confirming bucket was created...
+++ Staging server tars to S3 Storage: PROD-kubernetes-1/devel
upload: ../../../../tmp/kubernetes.0EYzTs/s3/bootstrap-script to s3://PROD-kubernetes-1/devel/bootstrap-script
upload: ../../../../tmp/kubernetes.0EYzTs/s3/kubernetes-salt.tar.gz to s3://PROD-kubernetes-1/devel/kubernetes-salt.tar.gz
upload: ../../../../tmp/kubernetes.0EYzTs/s3/kubernetes-server-linux-amd64.tar.gz to s3://PROD-kubernetes-1/devel/kubernetes-server-linux-amd64.tar.gz
Uploaded server tars:
  SERVER_BINARY_TAR_URL: https://s3.amazonaws.com/PROD-kubernetes-1/devel/kubernetes-server-linux-amd64.tar.gz
  SALT_TAR_URL: https://s3.amazonaws.com/PROD-kubernetes-1/devel/kubernetes-salt.tar.gz
  BOOTSTRAP_SCRIPT_URL: https://s3.amazonaws.com/PROD-kubernetes-1/devel/bootstrap-script
INSTANCEPROFILE	arn:aws:iam::<REDACTED>:instance-profile/kubernetes-master	2016-07-01T20:36:32Z	AIPAJWCQXKFSTTT7MZR5C	kubernetes-master	/
ROLES	arn:aws:iam::<REDACTED>:role/kubernetes-master	2016-07-01T20:36:31Z	/	AROAI3AONJ76MPC2FVHL6	kubernetes-master
ASSUMEROLEPOLICYDOCUMENT	2012-10-17
STATEMENT	sts:AssumeRole	Allow
PRINCIPAL	ec2.amazonaws.com
INSTANCEPROFILE	arn:aws:iam::<REDACTED>:instance-profile/kubernetes-minion	2016-07-01T20:36:35Z	AIPAISNACDXWHQTTBZXSE	kubernetes-minion	/
ROLES	arn:aws:iam::<REDACTED>:role/kubernetes-minion	2016-07-01T20:36:34Z	/	AROAICWBNHBE27L2UDNBS	kubernetes-minion
ASSUMEROLEPOLICYDOCUMENT	2012-10-17
STATEMENT	sts:AssumeRole	Allow
PRINCIPAL	ec2.amazonaws.com
Using SSH key with (AWS) fingerprint: SHA256:T90vjmzWO+9zTJALkS8iKALYQ3hzOEhhtou7KR3MXh4
Using VPC vpc-7a98201d
Adding tag to dopt-a9b213cd: Name=kubernetes-dhcp-option-set
Adding tag to dopt-a9b213cd: KubernetesCluster=PROD
Using DHCP option set dopt-a9b213cd
Creating subnet.
Adding tag to subnet-6e1a0c18: KubernetesCluster=PROD
Using subnet subnet-6e1a0c18
Using Internet Gateway igw-2add854e
Associating route table.
Creating route table
Adding tag to rtb-5e696139: KubernetesCluster=PROD
Associating route table rtb-5e696139 to subnet subnet-6e1a0c18
Adding route to route table rtb-5e696139
Using Route Table rtb-5e696139
Creating master security group.
Creating security group kubernetes-master-PROD.
Adding tag to sg-cf316fb4: KubernetesCluster=PROD
Creating minion security group.
Creating security group kubernetes-minion-PROD.
Adding tag to sg-cc316fb7: KubernetesCluster=PROD
Using master security group: kubernetes-master-PROD sg-cf316fb4
Using minion security group: kubernetes-minion-PROD sg-cc316fb7
Generating certs for alternate-names: IP:23.20.1.125,IP:172.30.2.9,IP:10.0.0.1,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster.local,DNS:PROD-master
Starting Master
Adding tag to i-e323b965: Name=PROD-master
Adding tag to i-e323b965: Role=PROD-master
Adding tag to i-e323b965: KubernetesCluster=PROD
Waiting for master to be ready
Attempt 1 to check for master nodeWaiting for instance i-e323b965 to be running (currently pending)
Sleeping for 3 seconds...
Waiting for instance i-e323b965 to be running (currently pending)
Sleeping for 3 seconds...
Waiting for instance i-e323b965 to be running (currently pending)
Sleeping for 3 seconds...
Waiting for instance i-e323b965 to be running (currently pending)
Sleeping for 3 seconds...
Waiting for instance i-e323b965 to be running (currently pending)
Sleeping for 3 seconds...
Waiting for instance i-e323b965 to be running (currently pending)
Sleeping for 3 seconds...
 [master running]
Attaching IP 23.20.1.125 to instance i-e323b965
Attaching persistent data volume (vol-04bfe6ae) to master
2016-07-05T19:28:44.763Z	/dev/sdb	i-e323b965	attaching	vol-04bfe6ae
Using subnet CIDR override: 172.30.2.0/24
cluster "aws_PROD" set.
Using subnet CIDR override: 172.30.2.0/24
user "aws_PROD" set.
Using subnet CIDR override: 172.30.2.0/24
context "aws_PROD" set.
Using subnet CIDR override: 172.30.2.0/24
switched to context "aws_PROD".
Using subnet CIDR override: 172.30.2.0/24
user "aws_PROD-basic-auth" set.
Wrote config for aws_PROD to /home/<REDACTED>/.kube/config
Creating minion configuration
Creating autoscaling group
 0 minions started; waiting
 0 minions started; waiting
 0 minions started; waiting
 0 minions started; waiting
 0 minions started; waiting
 0 minions started; waiting
 0 minions started; waiting
 0 minions started; waiting
 0 minions started; waiting
 1 minions started; ready
Waiting for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This might loop forever if there was some uncaught error during start
  up.

..............................................................................(loops forever)

**Comment by dstynchula** [comment]
# It looks like docker has failed to start on the master: 
admin@ip-172-30-2-9:~$ ps aux 
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  1.6  0.1  28612  4756 ?        Ss   19:32   0:05 /sbin/init
root         2  0.0  0.0      0     0 ?        S    19:32   0:00 [kthreadd]
root         3  0.0  0.0      0     0 ?        S    19:32   0:00 [ksoftirqd/0]
root         4  0.0  0.0      0     0 ?        S    19:32   0:00 [kworker/0:0]
root         5  0.0  0.0      0     0 ?        S<   19:32   0:00 [kworker/0:0H]
root         6  0.1  0.0      0     0 ?        S    19:32   0:00 [kworker/u30:0]
root         7  0.1  0.0      0     0 ?        S    19:32   0:00 [rcu_sched]
root         8  0.0  0.0      0     0 ?        S    19:32   0:00 [rcu_bh]
root         9  0.0  0.0      0     0 ?        S    19:32   0:00 [migration/0]
root        10  0.0  0.0      0     0 ?        S    19:32   0:00 [watchdog/0]
root        11  0.0  0.0      0     0 ?        S<   19:32   0:00 [khelper]
root        12  0.0  0.0      0     0 ?        S    19:32   0:00 [kdevtmpfs]
root        13  0.0  0.0      0     0 ?        S<   19:32   0:00 [netns]
root        14  0.0  0.0      0     0 ?        S    19:32   0:00 [xenwatch]
root        15  0.0  0.0      0     0 ?        S    19:32   0:00 [xenbus]
root        16  0.0  0.0      0     0 ?        S    19:32   0:00 [kworker/0:1]
root        17  0.0  0.0      0     0 ?        S    19:32   0:00 [khungtaskd]
root        18  0.0  0.0      0     0 ?        S<   19:32   0:00 [writeback]
root        19  0.0  0.0      0     0 ?        SN   19:32   0:00 [ksmd]
root        20  0.0  0.0      0     0 ?        SN   19:32   0:00 [khugepaged]
root        21  0.0  0.0      0     0 ?        S<   19:32   0:00 [crypto]
root        22  0.0  0.0      0     0 ?        S<   19:32   0:00 [kintegrityd]
root        23  0.0  0.0      0     0 ?        S<   19:32   0:00 [bioset]
root        24  0.0  0.0      0     0 ?        S<   19:32   0:00 [kblockd]
root        25  0.0  0.0      0     0 ?        S    19:32   0:00 [kswapd0]
root        26  0.0  0.0      0     0 ?        S<   19:32   0:00 [vmstat]
root        27  0.0  0.0      0     0 ?        S    19:32   0:00 [fsnotify_mark]
root        33  0.0  0.0      0     0 ?        S<   19:32   0:00 [kthrotld]
root        34  0.0  0.0      0     0 ?        S<   19:32   0:00 [ipv6_addrconf]
root        36  0.0  0.0      0     0 ?        S<   19:33   0:00 [deferwq]
root        37  0.0  0.0      0     0 ?        S    19:33   0:00 [kworker/u30:1]
root        70  0.0  0.0      0     0 ?        S<   19:33   0:00 [ata_sff]
root        71  0.0  0.0      0     0 ?        S    19:33   0:00 [scsi_eh_0]
root        72  0.0  0.0      0     0 ?        S<   19:33   0:00 [scsi_tmf_0]
root        73  0.0  0.0      0     0 ?        S    19:33   0:00 [scsi_eh_1]
root        74  0.0  0.0      0     0 ?        S<   19:33   0:00 [scsi_tmf_1]
root        76  0.0  0.0      0     0 ?        S    19:33   0:00 [kworker/u30:3]
root        77  0.0  0.0      0     0 ?        S<   19:33   0:00 [kpsmoused]
root        80  0.0  0.0      0     0 ?        S    19:33   0:00 [kworker/0:2]
root        81  0.0  0.0      0     0 ?        S<   19:33   0:00 [kworker/0:1H]
root        89  0.0  0.0      0     0 ?        S<   19:33   0:00 [bioset]
root       106  0.0  0.0      0     0 ?        S    19:33   0:00 [jbd2/xvda1-8]
root       107  0.0  0.0      0     0 ?        S<   19:33   0:00 [ext4-rsv-conver]
root       159  0.0  0.0      0     0 ?        S    19:33   0:00 [kauditd]
root       168  0.3  0.2  41528  7956 ?        Ss   19:33   0:01 /lib/systemd/systemd-journald
root       170  0.0  0.0  40808  3304 ?        Ss   19:33   0:00 /lib/systemd/systemd-udevd
root       242  0.0  0.0      0     0 ?        S    19:33   0:00 [kworker/0:3]
root       336  0.0  0.0  37080  2692 ?        Ss   19:33   0:00 /sbin/rpcbind -w
statd      345  0.0  0.0  37280  2844 ?        Ss   19:33   0:00 /sbin/rpc.statd
root       350  0.0  0.0      0     0 ?        S<   19:33   0:00 [rpciod]
root       352  0.0  0.0      0     0 ?        S<   19:33   0:00 [nfsiod]
root       359  0.0  0.0  27568   232 ?        Ss   19:33   0:00 /usr/sbin/rpc.idmapd
root       361  0.0  0.0  27476  2736 ?        Ss   19:33   0:00 /usr/sbin/cron -f
root       372  0.0  0.0 262884  3600 ?        Ssl  19:33   0:00 /usr/sbin/rsyslogd -n
ntp        386  0.0  0.1  33380  4336 ?        Ss   19:33   0:00 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 104:109
root       508  0.0  0.1  55184  5352 ?        Ss   19:33   0:00 /usr/sbin/sshd -D
root       571  0.0  0.0      0     0 ?        S<   19:33   0:00 [kdmflush]
root       572  0.0  0.0      0     0 ?        S<   19:33   0:00 [bioset]
root       585  0.0  0.0      0     0 ?        S    19:33   0:00 [jbd2/dm-0-8]
root       586  0.0  0.0      0     0 ?        S<   19:33   0:00 [ext4-rsv-conver]
root       615  0.0  0.0      0     0 ?        S    19:33   0:00 [jbd2/xvdb-8]
root       616  0.0  0.0      0     0 ?        S<   19:33   0:00 [ext4-rsv-conver]
root      2456  0.0  0.0  21708  3304 ?        Ss   19:36   0:00 /bin/bash /etc/kubernetes/kube-master-addons.sh
root      3347  0.0  0.1  80520  5980 ?        Ss   19:37   0:00 sshd: admin [priv]  
admin     3349  0.0  0.0  80520  3600 ?        S    19:37   0:00 sshd: admin@pts/0   
admin     3350  0.0  0.0  21944  3772 pts/0    Ss   19:37   0:00 -bash
root      3510  0.0  0.0  14416  2004 tty6     Ss+  19:37   0:00 /sbin/agetty --noclear tty6 linux
root      3511  0.0  0.0  14416  2036 tty5     Ss+  19:37   0:00 /sbin/agetty --noclear tty5 linux
root      3512  0.0  0.0  14416  1908 tty4     Ss+  19:37   0:00 /sbin/agetty --noclear tty4 linux
root      3513  0.0  0.0  14416  2028 tty3     Ss+  19:37   0:00 /sbin/agetty --noclear tty3 linux
root      3514  0.0  0.0  14416  2032 tty2     Ss+  19:37   0:00 /sbin/agetty --noclear tty2 linux
root      3515  0.0  0.0  14416  2016 tty1     Ss+  19:37   0:00 /sbin/agetty --noclear tty1 linux
root      3516  0.0  0.0  14236  2276 ttyS0    Ss+  19:37   0:00 /sbin/agetty --keep-baud 115200 38400 9600 ttyS0 vt102
root      3627  0.0  0.0  21652  3176 ?        Ss   19:37   0:00 /bin/bash /opt/kubernetes/helpers/docker-healthcheck
root      3634  0.0  0.0   5808   676 ?        S    19:37   0:00 sleep 30
root      3864  0.0  0.0   5808   716 ?        S    19:38   0:00 sleep 15
admin     3889  0.0  0.0  19100  2516 pts/0    R+   19:38   0:00 ps aux
admin@ip-172-30-2-9:~$ sudo systemctl status docker
sudo: unable to resolve host ip-172-30-2-9
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2016-07-05 19:38:38 UTC; 1s ago
     Docs: https://docs.docker.com
  Process: 4081 ExecStart=/usr/bin/docker daemon -H fd:// $DOCKER_OPTS (code=exited, status=1/FAILURE)
  Process: 4078 ExecStartPre=/opt/kubernetes/helpers/docker-prestart (code=exited, status=0/SUCCESS)
 Main PID: 4081 (code=exited, status=1/FAILURE)

Jul 05 19:38:38 ip-172-30-2-9 systemd[1]: Failed to start Docker Application Container Engine.
Jul 05 19:38:38 ip-172-30-2-9 systemd[1]: Unit docker.service entered failed state.
admin@ip-172-30-2-9:~$

**Comment by dstynchula** [comment]
this message keeps appearing in syslog:

**Comment by dstynchula** [comment]
Under advice from justinb, I enabled dns-hostname resolution on the vpc. This moved the ball down the field, and now I'm getting another error. Kubectl is configured, but returns:

Unable to connect to the server: x509: certificate signed by unknown authority

**Comment by wirtsi** [comment]
I can confirm that this issue occurs with kubernetes-1.3.4.
I am creating a staging and production cluster, running kube-up.sh with export KUBE_SUBNET_CIDR=172.18.0.0/16 worked for the staging one, but then running kube-up.sh again with a different subnet gives me the above errors

**Comment by wirtsi** [comment]
@dstynchula could you describe what you mean by "I enabled dns-hostname resolution on the vpc"? thnks

**Comment by dstynchula** [comment]
wirtsi: what I mean is I created a DNS zone in route53 that matches the cluster name to enable dns lookups of the kube-system services.
