### ISSUE TITLE
cluster/kube-up.sh uses max-age parameter unavailable in Ubuntu Xenial version of gcloud.

### ISSUE THREAD

**Issue by matthewdupre** [kubernetes/kubernetes#28510]
```
# make quick-release
[build output]
# cluster/kube-up.sh
... Starting cluster in us-central1-b using provider gce
... calling verify-prereqs
All components are up to date.
All components are up to date.
All components are up to date.
... calling kube-up
Your active configuration is: [default]
Project: unique-caldron-775
Zone: us-central1-b
gs://kubernetes-staging-b389a31721/devel/
gs://kubernetes-staging-b389a31721/e2e-test-matt-devel/
gs://kubernetes-staging-b389a31721/e2e-test-root-devel/
gs://kubernetes-staging-b389a31721/kubernetes-devel/
gs://kubernetes-staging-b389a31721/njkubernetes-devel/
+++ Staging server tars to Google Storage: gs://kubernetes-staging-b389a31721/kubernetes-dev
el
CommandException: Invalid command "max-age=0".
```

max-age=0 comes from the `gsutil -m -q -h "Cache-Control:private, max-age=0" cp "${tar}" "${tar}.sha1" "${stagine_path}"` call out of cluster/gce/util.sh.

I saw the problem with the Ubuntu 16.04 google-cloud-sdk version 111.0.0-0ubuntu1~16.04.0, installed from apt-get.  Removing google-cloud-sdk and installing from here: https://cloud.google.com/sdk/downloads#apt-get fixed the problem.  `gsutil --version` reported 4.19 for both installs.

It would be much better if kube-up.sh worked with the version apt picks up automatically on 16.04.  Is the option really necessary?

**Comment by bboreham** [comment]
I had the exact same problem.  This message, output in the early stages of the build, seems relevant:

````
WARNING: There are older versions of Google Cloud Platform tools on your system PATH.
Please remove the following to avoid accidentally invoking these old tools:

/usr/bin/git-credential-gcloud.sh
/usr/bin/bq
/usr/bin/gcloud
/usr/bin/gsutil
````
