### ISSUE TITLE
kube-dns v15+ cannot set verbosity

### ISSUE THREAD

**Issue by fluxrad** [kubernetes/kubernetes#28515]
When replacing kube-dns v11 (as defined w/ the v1.2.4 release) with v15 in the v1.3.0 release, we notice that the `skydns` container inside the `kube-dns` pod is overly verbose. This appears to be due to an inability to turn of `Info` logging within [dns.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/dns/dns.go#L583). Neither the `--v` flag, nor the `--stderrthreshold=2` flags appear to have any impact. On a 65 node cluster with approximately 1700 pods, this results in a log load of over 10,000 log entries per second. Can we implement a mechanism to turn off Info-level logging from kubedns?

See also CoreOS kubernetes issue [555](https://github.com/coreos/coreos-kubernetes/pull/555#issuecomment-229530165).

**Comment by dims** [comment]
@fluxrad : is https://github.com/kubernetes/kubernetes/blob/master/pkg/dns/dns.go#L583 the only line that's verbose? which other lines show up as frequently?

**Comment by fluxrad** [comment]
It appears that this issue is specifically related to DNS queries against kubernetes services. Queries that resolve against external DNS are _not_ logged by default.

Running the following script:

```bash
#!/bin/bash

KUBE_DNS_ADDR=<whatever>

while true; do
  for i in `seq 1 100`; do
    dig +short $KUBE_DNS_ADDR fizzbuzz${i}.blah.foo.bizz.buzz
    dig +short $KUBE_DNS_ADDR 9news.com
    dig +short $KUBE_DNS_ADDR kubernetes.default.svc.cluster.local
    dig +short $KUBE_DNS_ADDR foo.svc.cluster.local
  done
  sleep 0.5
done
```

I get the following information repeated over and over:

```
I0705 21:14:42.433828   70347 dns.go:439] Received DNS Request:foo.default.svc.cluster.local., exact:false
I0705 21:14:42.433860   70347 dns.go:679] not a federation query: len(["foo" "default" "svc" "cluster" "local"]) != 4+len(["local" "cluster"])
I0705 21:14:42.433926   70347 dns.go:535] Received 0 records from cache
I0705 21:14:42.433936   70347 dns.go:539] records:[], retval:[], path:[local cluster svc default foo]
I0705 21:14:42.485532   70347 dns.go:439] Received DNS Request:kubernetes.default.svc.cluster.local., exact:false
I0705 21:14:42.485557   70347 dns.go:679] not a federation query: len(["kubernetes" "default" "svc" "cluster" "local"]) != 4+len(["local" "cluster"])
I0705 21:14:42.485627   70347 dns.go:535] Received 1 records from cache
I0705 21:14:42.485640   70347 dns.go:539] records:[0xc82027d500], retval:[{10.0.0.1 0 10 10  false 30 0  /skydns/local/cluster/svc/default/kubernetes/3234633364383235}], path:[local cluster svc default kubernetes]
```

This script was run on localhost against a minikube cluster. However in a proper cluster, since each pod has `ndots:5` set in `/etc/resolv.conf` by default, each DNS query from a running pod will generate at least two or three such queries by default before "leaving" the cluster. See #19634

I've created a PR to turn down default verbosity and will submit shortly.

**Comment by joshk0** [comment]
I know this potentially isn't the right forum, and I've already reached out on chat, but this is causing a huge amount of pain in GKE. Our log integrations have shut down because we sent them too much log data. Is there anyone in the org who could help to push an updated kube-dns out to that environment?

**Comment by rileylark** [comment]
We are using GKE + Google Cloud Logging, which I guess is switching to Stackdriver pricing, and the logs from kube-dns are going to start costing us almost $1000/month.

@joshk0 did you find a good way to get this updated on GKE?

**Comment by joshk0** [comment]
@rileylark, when I went to Kubernetes v1.4 the issue went away, I think.
