### ISSUE TITLE
Openstack cloudprovider does not detect Cinder volume attachment correctly

### ISSUE THREAD

**Issue by Tebro** [kubernetes/kubernetes#28527]
Trying to attach a cinder volume to a pod fails with the following log messages:

```
openstack.go:588] Failed to attach 78f6bb3d-200e-459e-bdca-ed66503d1681 volume to f7e3e936-d87b-4cd4-8454-c65f6ed02a6f compute

attacher.go:91] Attach volume "78f6bb3d-200e-459e-bdca-ed66503d1681" to instance "f7e3e936-d87b-4cd4-8454-c65f6ed02a6f" failed with Expected HTTP response code [200] when accessing [POST https://api.example.com/default/nova/v2/1c8b7f3943e4429e8da3f994254e7280/servers/f7e3e936-d87b-4cd4-8454-c65f6ed02a6f/os-volume_attachments], but got 400 instead

journal: {"badRequest": {"message": "Invalid volume: volume '78f6bb3d-200e-459e-bdca-ed66503d1681' status must be 'available'. Currently in 'in-use'", "code": 400}}
```

When checked in horizon the volume is attached to the correct instance, but the pod never starts because mounting times out.

**Comment by Tebro** [comment]
This was an issue with kubernetes being provided with a Cinder V2 API, instead of V1.

**Comment by hacktastic** [comment]
Hey Tebro-- I'm having this same issue. What was the mismatch, exactly? Kubernetes was using V2 and OpenStack was using V1? or vice-versa? 

Also, is there a way to configure that on the kubernetes side?

**Comment by Tebro** [comment]
So kubernetes only supports Cinder V1 API.

Our keystone was only providing it with v2. We configured keystone to also
inform about the location of Cinder v1 and then it started working.
