### ISSUE TITLE
Add Google Cloud DNS support to LoadBalancer Services

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#28525]
#23576 added an annotation to support DNS on Route53 on AWS.  To _really_ do this right, we need to think harder about how we want to evolve Service and Ingress.  In the mean time, it seems reasonable to do the same trick with GCE Cloud DNS.  add an annotation and watch DNS appear.

This would be a great opportunity for a community-contributed patch, if anyone is looking for ideas.

**Comment by davidwalter0** [comment]
What support for route53 were you thinking of including, create a route from an annotation, read, update and delete?

Would the goal be to initially create on service/ingress create and delete on service/ingress destruction?

Where would the credentials for aws be located, does this assume that the cluster is natively running on AWS so the cluster credentials would be available (somewhere in the api), or need to be provided separately?

I guess the same questions apply for a GCE cloud DNS. If managing one cluster in AWS but you wanted to use google's DNS, is there a place to store the GCE credential to perform the DNS update?

**Comment by davidquarles** [comment]
I've yet to contribute and I'm not totally clear on protocol here, but I have enough bandwidth to help (assuming this is still dangling).

**Comment by thockin** [comment]
On Wed, Jul 27, 2016 at 5:21 AM, davidwalter0 <notifications@github.com> wrote:
>
> What support for route53 were you thinking of including, create a route from an annotation, read, update and delete?

To be clear: Route53 support was added already - this bug is about
adding equivalent functionality on GCE.

Basically, create a Google CloudDNS name from a Service annotation,
pointing to the external load-balancer IP.

> Would the goal be to initially create on service/ingress create and delete on service/ingress destruction?

Exactly.  Also, probably periodic checks, but nothing super fancy.

> Where would the credentials for aws be located, does this assume that the cluster is natively running on AWS so the cluster credentials would be available (somewhere in the api), or need to be provided separately?
>
> I guess the same questions apply for a GCE cloud DNS. If managing one cluster in AWS but you wanted to use google's DNS, is there a place to store the GCE credential to perform the DNS update?

I think for now it's enough to assume that the VM this is running on
has sufficient credentials to make the GCE API call.

**Comment by MrHohn** [comment]
I'm working on adding the same feature --- stable external DNS entries support --- for the gce package.

**Comment by thockin** [comment]
OK.  Let's make sure we use these issues as interlocks - duplicating
efforts is no fun.

**Comment by davidquarles** [comment]
stoked someone is working on this!

**Comment by MrHohn** [comment]
Consider the dnsprovider interface and both AWS's and GCP's dns implementations are existed inside the federation package [(dnsprovider)](https://github.com/kubernetes/kubernetes/tree/master/federation/pkg/dnsprovider), I'm now embedding this feature directly into service controller instead of gce package.

**Comment by thockin** [comment]
I would not put it in the core controller - not every platform can support
this yet, and the callouts ARE still platform specific.

**Comment by MrHohn** [comment]
> I would not put it in the core controller - not every platform can support
this yet, and the callouts ARE still platform specific.

Copied that, I will figure out another workaround.

**Comment by thockin** [comment]
workaround to what problem?  AWS has it linked in their cloud provider
module.  GCE should do the same?

**Comment by MrHohn** [comment]
> workaround to what problem?  AWS has it linked in their cloud provider
module.  GCE should do the same?

Right. I may used the wrong word. I tried to implement the DNS feature in the same way as this route53 pull request (#23576). But found it somehow not neat because we are no going through a unified dns interface. Hence figuring out a better way for construction.

**Comment by thockin** [comment]
I don't think we should try to unify the interfaces yet. I don't believe we
have a clear enough idea of how we want to manage that.  While it's
"obvious" that AWS users will use Route53 and GCE users will use CloudDNS,
there's actually nothing that REQUIRES that.  Let's just do as small a
change as we can get away with and then revisit later when we have a better
idea and more time.

**Comment by MrHohn** [comment]
> I don't think we should try to unify the interfaces yet. I don't believe we
have a clear enough idea of how we want to manage that.  While it's
"obvious" that AWS users will use Route53 and GCE users will use CloudDNS,
there's actually nothing that REQUIRES that.  Let's just do as small a
change as we can get away with and then revisit later when we have a better
idea and more time.

Agree with this. I would then follow the original implementation.

**Comment by jkurz** [comment]
I think something like this would be nice. However I see a few problems with the current approach.

A major difference between AWS and GCP: when a load balancer is created, an automatic A record is created and managed behind the scenes. This makes it easy to CNAME too, like this PR #23576 was trying to do. I can't tell anymore as the diff is cray now. 

Is GCP not considering doing something like this at a lower level than kubernetes? I honestly think that is the first step, before we can add CNAME functionality to kubernetes for GCP. 

If The Goal is to manage an A record for the LoadBalancer, then to me that sounds like a feature of GCP and not something kubernetes should be managing. 

But if having GCP manage A records is not on the radar, then a solution like this is very much needed.

**Comment by paultiplady** [comment]
For completeness, here's another alternative: https://github.com/zalando-incubator/mate

This implements a DNS name per LoadBalancerIP, autogenerated by default, but the DNS name can be overridden using an annotation.

**Comment by thockin** [comment]
On Thu, Dec 29, 2016 at 10:28 AM, Justin Santa Barbara
<notifications@github.com> wrote:
>
> If we put the dns-controller from kops into incubation, would that work? (It isn't really part of kops, though kops uses it).
>
> There is some woeful early documentation here: https://github.com/kubernetes/kops/tree/master/dns-controller

Man, we need some centralized control of annotations with
*.kubernetes.io prefixes, or it's gonna explode one day.

> In short though, it looks for annotations and creates DNS records in GCE or AWS Route53. It can also observe ingress hostnames and do the same thing (though we're waiting the next ingress controller before this actually works on AWS)

I think this is a really interesting model, and is probably the right
way to go rather than building it in.

**Comment by thockin** [comment]
Maybe we can get mate and kops to join forces and make a single thing that
is useful on its own?

**Comment by paultiplady** [comment]
cc @linki -- discussion about bringing a DNS controller into the kubernetes incubator.

**Comment by linki** [comment]
thx @paultiplady for letting us know about this discussion.

Indeed, it looks like `mate` tries to solve the same problem as kops’ `dns-controller`.

What it currently does:
* DNS names for type=LoadBalancer services
* DNS names for Ingress rules’ hostnames
* DNS names for type=NodePort services (open PR)
* supports Google CloudDNS (A records) and AWS Route53 (Alias)

It’s serving us well so far and I think it’s a valuable part of our cluster setup.

If there’s a demand in the community for a thought through, supported and reliable solution to this problem we’d be happy to collaborate with the kops team to bring this forward.

**Comment by thockin** [comment]
I think it would be super duper to have a well-tested, well-supported DNS
controller with a plugin API for new DNS backend implementations and a
schema spec for annotations that trigger the publication of DNS.  This is
exactly what annotations and controllers are designed to do.

**Comment by kris-nova** [comment]
+1 here on getting us all together. I just read through the issue and it seems we are just about ready to start implementation. Just need to gather thoughts and get a plan together around incubation. 

How do you guys want to handle this? I'm partial to jumping on a call. But anything works for me. Cheers.

**Comment by Raffo** [comment]
+1 for the call! 
If @linki agrees, we can setup an (hangout) call next week and then report the result here. I can take care of setting it up, you can drop me an email (it's in the github profile) and we can coordinate.

**Comment by linki** [comment]
sounds good

**Comment by thockin** [comment]
Please loop me and @bowei in on the call

**Comment by Raffo** [comment]
Just to sum it up: we decided to join the efforts and apply for a Kubernetes incubator project.

**Comment by thockin** [comment]
w00t!  closing this, then.

**Comment by kamalmarhubi** [comment]
@thockin failed to actually close it :-)

@Raffo do you have a link to the project? This sounds really interesting!

**Comment by Raffo** [comment]
@kamalmarhubi Sure, here it is: https://github.com/kubernetes-incubator/external-dns
