### ISSUE TITLE
add NVIDIA GPU feature into k8s+Mesos cluster

### ISSUE THREAD

**Issue by jianzhangbjz** [kubernetes/kubernetes#28526]
It will be nice if add the latest NVIDIA GPU feature into K8s+Mesos cluster. Like [ NVIDIA GPU discovery, could support more than 1 GPU on 1 Minion, more than 1 GPU on 1 Pod. #28216 ](https://github.com/kubernetes/kubernetes/pull/28216) shows.

**Comment by cmluciano** [comment]
/close

please open on the [kube-on-mesos repo](https://github.com/kubernetes-incubator/kube-mesos-framework)
