### ISSUE TITLE
Question about `--containerized=` of the kubelet

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#28533]
This flag has the following the description:

```
--containerized[=false]: Experimental support for running kubelet in a container.  Intended for testing. [default=false]
```

This has been labeled as "experimental" for a while. Is this still up-to-date? If so, what is the caveat of using this flag and running a kubelet inside of a container?

**Comment by dims** [comment]
@huang195 please see discussion in this issue - https://github.com/kubernetes/kubernetes/issues/4869 Please follow along there and hope we can close this issue.

**Comment by huang195** [comment]
Thanks. Looks like it's covered well in the other thread. Will follow along there. Thanks @dims
