### ISSUE TITLE
Allow use of encrypted secrets

### ISSUE THREAD

**Issue by chrisleck** [kubernetes/kubernetes#28538]
If secret contents could be encrypted/decrypted by an encryption provider plugin (e.g., KMS on AWS) running in the kube master or in kubelets (though the kubelet option may require more complex IAM setup), then it would be acceptable to check in secret manifests into source control.

This is a significant pain point for my team at the moment.

**Comment by chrislovecnm** [comment]
See https://github.com/kubernetes/kubernetes/issues/10439 - people are asking for Vault or the capability to use plugins which would allow for KMS as well.

**Comment by alfred-huangjian** [comment]
@kubernetes/huawei
