### ISSUE TITLE
kubelet 1.3.0 fail to start static pods after upgrading from 1.2.4

### ISSUE THREAD

**Issue by y2kenny** [kubernetes/kubernetes#28545]
## Environment

A working v1.2.4 single master, multi-node cluster
CoreOS stable 1010.5.0
Docker version 1.10.3, build 8acee1b
kubelet binary located in /opt/bin/ start by kubetlet.service as defined here:

```
        [Unit]
        Description=Kubernetes Kubelet
        Documentation=https://github.com/kubernetes/kubernetes
        Requires=docker.service kubernetes-install.service
        After=kubernetes-install.service

        [Service]
        ExecStart=/opt/bin/kubelet \
        --register-node=false \
        --allow-privileged=true \
        --config=/etc/kubernetes/manifests \
        --cluster-dns=10.100.0.10 \
        --cluster_domain=cluster.local \
        --logtostderr=true
        Restart=always
        RestartSec=10

        [Install]
        WantedBy=multi-user.target
```

/etc/kubernetes/manifests/ contain two manifests:

```
calico-etcd.manifest
kubernetes-master.manifest
```

[calico-etcd.manifest.txt](https://github.com/kubernetes/kubernetes/files/350809/calico-etcd.manifest.txt)
[kubernetes-master.manifest.txt](https://github.com/kubernetes/kubernetes/files/350808/kubernetes-master.manifest.txt)
## Step to reproduce

Replace /opt/bin/kubelet with v1.3.0, reboot
## Observation:

When I ran `docker ps`, only the calico/node container was trying to start.  And it was stuck at restarting because the etcd container defined in the the other manifest wasn't starting.
## Step to revert

replace /opt/bin/kublet with v1.2.4, reboot
## Expected results

Containers described in both manifests should be starting.  (So in addition to the calico/node container, I should be seeing a few containers with the hyperkube, etcd and pause.)

**Comment by jsoriano** [comment]
I have seen the same behaviour with similar configuration in a testing environment, it seems that the problem was this:
```
Cannot get Node info: can't get ip address of node master01
```
Check in kubelet logs if you have something similar.

I fixed it with `--hostname-override`, but it worked without this flag in 1.2.

**Comment by spzala** [comment]
@jsoriano +1 @y2kenny hi, can you please verify if this is still an issue or can we close it please? Thanks!
