### ISSUE TITLE
Enable memory and disk usage based eviction by default in future releases

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#28552]
Memory based evictions is currently opt-in and disk based evictions will also be opt-ins only.
Both of these features are useful to almost all kubernetes users. Some informed users might want to tune these features to meet their infrastructures requirements.
I propose enabling these features by default in a release after the one where they are introduced.
Specifically,
- Enable memory based disk evictions by default (opt-out) in v1.4. This requires identifying a sane default for eviction thresholds. I propose setting the thresholds to `100Mi`. Set the default value of `--eviction-hard` to `memory.available<100Mi`
- Enable disk based evictions by default (opt-out) in v1.5. Defaults for eviction thresholds can be `10%` for both root and image partition space and inodes. Set the default value of `--eviction-hard` to `memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<10%,imagefs.available<10%,imagefs.inodesFree<10%`

These defaults are meant to work on all supported configurations, specifically disk based evictions.
If a node has a unified image and root partition, the thresholds on image partition should be a no-op.

cc @kubernetes/sig-node @derekwaynecarr 

**Status as of v1.6:**
- Memory eviction is enabled by default. https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/componentconfig/v1alpha1/defaults.go#L372
- Inodes and disk usage based evictions do not have defaults.

**Comment by derekwaynecarr** [comment]
I agree on reasonable defaults for memory in 1.4.  I will send a PR.

Is there a compelling reason to not enable the defaults for disk in 1.4 though?  Only thing we need to ensure is that we ignore inodes for imagefs that is block level.

**Comment by vishh** [comment]
@derekwaynecarr Excepting soak time for disk evictions, I can't think of any other reason not to enable it by default.

**Comment by derekwaynecarr** [comment]
fair enough, 1.5 is fine to enable by default.

**Comment by goltermann** [comment]
@derekwaynecarr @vishh should this be moved to v1.5?

**Comment by derekwaynecarr** [comment]
moved to 1.5, will let disk eviction soak.

**Comment by dims** [comment]
@derekwaynecarr switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree, cc @saad-ali @calebamiles)

**Comment by vishh** [comment]
@dashpole FYI!

**Comment by dchen1107** [comment]
Unfortunately, this is not done for 1.6. I move it to 1.7 milestone.

**Comment by derekwaynecarr** [comment]
I do not yet have defaults identified for disk and it will have to be queued up for 1.7.

**Comment by dchen1107** [comment]
Both disk and memory eviction based on the usage are on by default. Close the issue.
