### ISSUE TITLE
maintaine kube-dns in cluster/addons

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#28553]
Not everyone uses salt. We need to maintain cluster addons (even required ones) in cluster/addons/ so they are visible to users. This is where people go to look for addons. The change in location is causing a lot of confusion for non-kube-up deployment users as there was no release notes or migration path on how to deploy from the new location.

cc @girishkalele

**Comment by mikedanese** [comment]
The kube-addon-manager is also optional. Many users deploy addons using just kubectl.

https://kubernetes.slack.com/archives/sig-cluster-ops/p1467837392000173

**Comment by girishkalele** [comment]
Would restoring the dns directory that was present under cluster/addons with a README.md help ?

The README would just contain instructions directing users to the new location - the effort in 1.3 was to reduce the duplication of the skydns yaml files so that DNS RC enhancements (switch to kube-dns from kube2sky, adding dnsmasq caching and federation changes) are clean and contained.

**Comment by ovanes** [comment]
To be honest, I find the documentation a bit scarce. I'd gladly switch to anything else if this is the right way to do and I am about to switch the Kubernetes cluster. But than I need some directions to do so. We use Kubernetes with AWS and I use terraform to bootstrap the cluster and bring up all the services.

This documentation (http://kubernetes.io/docs/admin/dns/) just states to install the cluster addon. But how to do that is not obvious.

I am also a bit in doubt about that statement in the docs:
```
As of Kubernetes 1.3, DNS is a built-in service launched automatically using the addon 
manager cluster add-on. A DNS Pod and Service will be scheduled on the cluster, and 
the kubelets will be configured to tell individual containers to use the DNS Service’s IP 
to resolve DNS names.
```
I understand this as: Just run the addon service and it will start DNS service itself. But to honest I don't get the "why" and "how". And I think the intention of that statement was different, that I need to place addons somewhere on CoreOS host?? Thus pointing out how to do that, would be very helpful.

**Comment by puja108** [comment]
So the current solution is looking into https://github.com/kubernetes/kubernetes/tree/master/cluster/saltbase/salt/kube-dns and build working manifests for our setups based on those, right?

Strangely, even official setups like minikube, which just got updated, now don't come with a working DNS anymore. They have the DNS service running and also the addon-manager pod, but no DNS pods...

The lack of documentation for core 1.3 changes is tough to work with.
