### ISSUE TITLE
How to do rate limit and set bandwidth quota using kubernetes?

### ISSUE THREAD

**Issue by caizixian** [kubernetes/kubernetes#2856]
I want to use kubernetes on my private PaaS and some of the containers need rate limit(like 10Mbps) and bandwidth quota(like 100GB/month).
Is it possible to do this using kubernetes?

**Comment by x1957** [comment]
Is there any update?

**Comment by kargakis** [comment]
Please use stackoverflow, slack, or the kubernetes-users mailing list.

**Comment by kargakis** [comment]
Well, this ca

**Comment by kargakis** [comment]
Reopening as it seems a feature request

**Comment by DanielYWoo** [comment]
+1
We have a batch service which upload and download a lot of PDF files, it consumes a lot of network bandwidth and affects other services. Bandwidth limit is a very useful feature for us.

**Comment by warmchang** [comment]
+1

**Comment by cmluciano** [comment]
Cc @kubernetes/sig-network-feature-requests

**Comment by davidopp** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by k82cn** [comment]
Interesting requirement! Can we make such requirements be pluggable? AFAIK, @derekwaynecarr is working on making Quota supporting all k8s kinds/types.

**Comment by xiaods** [comment]
+1 for request feature.

**Comment by k82cn** [comment]
IMO, there's two part of this requirement: 

1. k8s quota can handle external resource (e.g. CRD) itself or by admission plugins
2. the "Service Mesh" provide such ability

Should we define "Service Mesh" related resources/kinds in k8s? Similar to network policy.

**Comment by xiaods** [comment]
this is not different. k8s focus on network raw ethernet limit. the istio is cover application's request limit.

**Comment by yiqinguo** [comment]
@xiaods I agree.

**Comment by m1093782566** [comment]
@caizixian 

Does 

```
{
    "kind": "Pod",
    "spec": {
        "containers": [
            {
                "image": "nginx",
                "name": "nginx"
            }
        ]
    },
    "apiVersion": "v1",
    "metadata": {
        "name": "iperf-slow",
        "annotations": {
            "kubernetes.io/ingress-bandwidth": "10M",
            "kubernetes.io/egress-bandwidth": "10M"
        }
    }
}
```

works for you?

**Comment by warmchang** [comment]
@m1093782566 
https://github.com/kubernetes/kubernetes/blob/v1.8.4/pkg/util/bandwidth/utils.go#L38

**Comment by cmluciano** [comment]
@dnardo Does the tc piece of kubenet help out here?

**Comment by caizixian** [comment]
@m1093782566 Thank you. I will have a try.

**Comment by christianhuening** [comment]
So this works via the annotations? Or have there been any changes since 1.8.4 ?

**Comment by tonglil** [comment]
Do the annotations work (on GKE)?

```
  - kubernetes.io/egress-bandwidth: xM
  - kubernetes.io/ingress-bandwidth: xM
```

There doesn't seem to be any documentation for this at all.

**Comment by m1093782566** [comment]
Traffic shaping works with kubenet regardless of what platform you are running.

We are working on support traffic shaping for CNI network driver, xref: https://github.com/kubernetes/community/pull/1893

**Comment by m1093782566** [comment]
Both kubenet and CNI network driver support traffic shaping now.

I think we can close this issue now?

**Comment by tonglil** [comment]
You are referring to https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/ correct?

**Comment by wenlaizhou** [comment]
> @caizixian
> 
> Does
> 
> ```
> {
>     "kind": "Pod",
>     "spec": {
>         "containers": [
>             {
>                 "image": "nginx",
>                 "name": "nginx"
>             }
>         ]
>     },
>     "apiVersion": "v1",
>     "metadata": {
>         "name": "iperf-slow",
>         "annotations": {
>             "kubernetes.io/ingress-bandwidth": "10M",
>             "kubernetes.io/egress-bandwidth": "10M"
>         }
>     }
> }
> ```
> works for you?

uneffect

**Comment by qburst-krishnachandra** [comment]
Is the data limit or quota can be set for pod, node or namespaces?

**Comment by prateekjainaa** [comment]
does it work for anyone or not? 

"annotations": {
            "kubernetes.io/ingress-bandwidth": "10M",
            "kubernetes.io/egress-bandwidth": "10M"
        }

Are there any alternatives which we can test (apart from service mesh)?
