### ISSUE TITLE
Allow use of Downward API in ConfigMap files?

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#28560]
The Problem:

Currently I have an application which uses an entrypoint.sh script as its command, entirely because I need to convert a bunch of ENV vars passed by ConfigMap into a configuration file.  I don't think I'm unique in doing this.  I'd use ConfigMap to mount the configuration file (a yaml file) directly, *except* that I need to insert some "dynamic" values at deployment time, such as the Pod IP and the Pod name.

Suggested Solution:

It would be great to implement some method of merging values from the Downward API, or even from other ConfigMaps, into a specially-structured Configmap at deployment time.  I don't really know what this would look like; possibly something like the template merge supported by various CMSes like Salt?  As a solution, it would allow users to eliminate a whole host of poorly-maintained entrypoint.sh scripts.

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra @smarterclayton

**Comment by dims** [comment]
@ncdc @jberkus : Does this PR help with your situation? https://github.com/kubernetes/kubernetes/issues/29607

**Comment by jberkus** [comment]
@dims: somewhat, but not completely.  See comments on that PR.

**Comment by jberkus** [comment]
Closing in favor of #30716
