### ISSUE TITLE
[Question] filtered api responce

### ISSUE THREAD

**Issue by ltagliamonte** [kubernetes/kubernetes#28562]
I'm wondering if it is possible to apply a filter on pod status phase (for example != Succeeded) to get a filtered result server side from the api endpoint: `http://<api_server>/api/v1/namespaces/default/pods` 
Thanks in advance.

**Comment by fabianofranz** [comment]
Please refer to http://kubernetes.io/docs/troubleshooting/ about how to ask questions. Github issues should only be used for actual issues and bugs. Thanks!
