### ISSUE TITLE
kubectl release 1.3.0 not able to get server version if localhost not included into /etc/hosts

### ISSUE THREAD

**Issue by luedigernet** [kubernetes/kubernetes#28582]
We are running our k8s clusters on top of vm's running coreos. After setting up a cluster with release 1.3.0 I'm no longer able to get the verions.

Used kubectl config during all tests

`
apiVersion: v1
clusters:
\- cluster:
    certificate-authority: /etc/kubernetes/ssl/ca.pem
    server: https://admin-apiserver-prod.de-fra1.kubernetes.paas.metro.cloud
  name: kubernetes-admin-prod-de-fra1
contexts:
\- context:
    cluster: kubernetes-prod
    user: kubernetes-admin
  name: kubernetes-admin-prod-de-fra1
current-context: kubernetes-admin-prod-de-fra1
kind: Config
preferences: {}
users:
\- name: kubernetes-admin
  user:
    token: ######################################
`

Kubectl from release 1.3.0 does not work
`./kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"283137936a498aed572ee22af6774b6fb6e9fd94", GitTreeState:"clean", BuildDate:"2016-07-01T19:26:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: dial tcp: lookup localhost on 10.16.176.222:53: no such host
`

Kubectl from release 1.1.8 does work
`rel1.1.8/kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.8", GitCommit:"a8af33dc07ee08defa2d503f81e7deea32dd1d3b", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"283137936a498aed572ee22af6774b6fb6e9fd94", GitTreeState:"clean"}`

Interestingly kubectl inside of hyperkube from release 1.3.0 does work as well.
`hyperkube/hyperkube kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"283137936a498aed572ee22af6774b6fb6e9fd94", GitTreeState:"clean", BuildDate:"2016-07-01T19:19:19Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"283137936a498aed572ee22af6774b6fb6e9fd94", GitTreeState:"clean", BuildDate:"2016-07-01T19:19:19Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}`

Of course you can solve the problem by simply adding localhost to the file /etc/hosts or by switching to hyperkube instead of dedicated kubectl binaries. Nevertheless, the question arises why the two tools of releases behave Non Smoking equal.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.
