### ISSUE TITLE
Proposal: Federation API Server should support Authorization

### ISSUE THREAD

**Issue by matchstick** [kubernetes/kubernetes#28580]
@cjcullen @kubernetes/sig-cluster-federation 
Not sure what time frame we need to pursue this, but opening this issue to track the problem of making sure Federation API support some form of authentication.

**Comment by quinton-hoole** [comment]
@matchstick I think that you're confusing authentication with authorization? Authentication is already there.  We have no immediate plans to support federated authorization.

**Comment by quinton-hoole** [comment]
Retitled based on in-person discussion with @matchstick .

**Comment by quinton-hoole** [comment]
Will be covered by https://github.com/kubernetes/features/issues/102 . Closing this one.
