### ISSUE TITLE
DynamoDB for Apiserver storage

### ISSUE THREAD

**Issue by nickschuch** [kubernetes/kubernetes#28598]
I keep coming back to the idea of running DynamoDB for apiserver data storage instead of etcd.

Is this a good idea or am I a bit crazy? Happy to start hacking on this if but wanted to create an issue first.

**Comment by luxas** [comment]
cc @kubernetes/sig-api-machinery @bgrant0607

**Comment by lavalamp** [comment]
Please take a look at #28508 and discuss the interface work there.

**Comment by xiang90** [comment]
@nickschuch The only problem I can see is that you need to implement extra pooling logic to simulate watcher. It should be doable. We are trying to design a reasonable low level kv API to support different storage backends.

**Comment by smarterclayton** [comment]
Closing due to age and general lack of interest.  Proposals and serious plans welcome!
