### ISSUE TITLE
Optimize scheduler performance/throughput

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#28590]
I increased QPS limits locally to 100 and run scalability tests in 1000-node cluster, but with all priority functions switched off. In that situation, scheduler is able to sustain 100pods/s throughput.

However, I looked into scheduler cpu profile, and interesting this is that we spend most of the time on:
- memory allocations / GC
- some super trivial operations like:
     2% in runtime.mapiterinit
- accessing elements in maps (it seems that mostly from ResourceList)

So in order to significantly improve scheduler throughput we need to:
- optimize "spreading priority function" (which is the most expensive priority function now
- reduce the amount of garbage we are producing during scheduling

@davidopp

**Comment by wojtek-t** [comment]
I already have some very simple bits put together. I will try to send the out today or tomorrow.

**Comment by wojtek-t** [comment]
Well - simple, but they seem to help.

**Comment by wojtek-t** [comment]
BTW - selector spreading is basically #22262

**Comment by wojtek-t** [comment]
One thing that we need to do, is to avoid computing the same thing multiple times.

One example of it is computing "qos" of a given pod:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L1030

We are basically computing qos of a pod for every node.

The problem is that this function is non trivial and we are spending 8% of time in it (in 1000-node cluster).
However, we should easily reduce it, if we compute it only once, and then use the result.

So my proposal would be to add additional parameter to FitPredicate, which will allow to pass some additional data to predicate functions (potentially also to priority functions in the future).
So I would suggest something like:
```
type FitPredicate func(pod *api.Pod, metadata interface{}, nodeInfo *schedulercache.NodeInfo) (bool, error)
```

If will be scheduler responsibility to pass an appropriate metadata.
From the implementation point of view metadata will be something like:
type PredicateMeta struct {
  QOS qos.QOS
  ...
}

Thoughts?

**Comment by wojtek-t** [comment]
To clarify, why I make "metadata" an  "interface{}" - this is basically to avoid having some strange type in the API. Then predicate function may want to cast to what they expect.

**Comment by davidopp** [comment]
Sounds like a good idea.

**Comment by wojtek-t** [comment]
Cool - will try to implement this today.

**Comment by wojtek-t** [comment]
Few more things will come soon...

**Comment by timothysc** [comment]
@wojtek-t did you want to keep this open through 1.6?  There has been a lot of work done during the 1.4 cycle.

**Comment by wojtek-t** [comment]
yup - we are far from where I would like to be

**Comment by jayunit100** [comment]
@wojtek-t  We also are looking into similar issues...  Can we make the performance goal concrete for this so we can evaluate when its completed? 

cc @@ravisantoshgudimetla

**Comment by k82cn** [comment]
maybe a benchmark is necessary for this firstly.

**Comment by wojtek-t** [comment]
We already have benchmark (though I'm not sure how good it is).

We have a goal of 100pods/s for the end of year. Though it needs to work for 5000-node clusters (I believe we are already there for small enough clusters, if we bump qps limits).
