### ISSUE TITLE
Need a way to temporarily disable HPA

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#28603]
In OpenShift, we're adding support for idling the pods managed by a `Deployment`, `ReplicationController`, etc. This would happen after e.g. we've recorded no traffic to a set of pods, and we'd set the replicas to 0. If there is an HPA associated with this, it presumably would act to increase the number of pods to the minimum value, instead of leaving it at 0 as the idler desires.

We would like to be able to indicate in some way that an HPA is temporarily disabled. I imagine this could be done via an annotation or possibly with the addition of a new field. And once the target is unidled, we'd want to reenable the HPA.

Thoughts anyone?

@bgrant0607 @kubernetes/autoscaling @jszczepkowski @mwielgus @piosz @fgrzadkowski @kubernetes/rh-cluster-infra @smarterclayton @knobunc

**Comment by DirectXMan12** [comment]
An alternative (although this would be a change to functionality) would be to say "if replicas == 0, HPA is disabled"

**Comment by fgrzadkowski** [comment]
Adding a separate field to disable HPA sounds like a hack to me. I think it'd only pollute the API.

Another options I see:
1) Allow min replicas to be 0 (with a warning when creating such object). AFAIU if someone manually scales RC to 0, HPA will not have a signal to scale it back up. This would probably require changes in HPA controller. At the same time if there'll be any metrics > 0 (via new push endpoint in heapster?) HPA will scale it up to 1, right?
2) Delete HPA object and store it somewhere temporarily

**Comment by smarterclayton** [comment]
I kind of like autoscaler ignoring items with scale 0.  Since by
definition autoscaler won't work on those objects, and presumably the
user intentionally scaled to zero, ignoring that object until it's
non-zero feels right.

**Comment by ncdc** [comment]
The logic in the controller currently does this, if I'm reading it correctly:

1. get currentReplicas
1. if currentReplicas > hpa max, set desired = hpa max
1. else if hpa min is specified and currentReplicas < hpa min, set desired = hpa min
1. else if currentReplicas = 0, set desired = 1
1. else use metrics to calculate desired

It looks like 3 and 4 above would need to be adjusted. Additionally, inside the "else use metrics" path, there is code that says "if desired = 0, set desired to 1" along with a todo to remove that once pod idling is done (https://github.com/kubernetes/kubernetes/blob/ef0c9f0c5b8efbba948a0be2c98d9d2e32e0b68c/pkg/controller/podautoscaler/horizontal.go#L326). So it does look like there was some prior thought about integrating idling with HPA.

Maybe we just need to say "if currentReplicas = 0, break" as Clayton suggested. This is a change in behavior, but it feels right to me.

@fgrzadkowski re "At the same time if there'll be any metrics > 0 (via new push endpoint in heapster?) HPA will scale it up to 1, right?", I believe our intention is that the # of replicas would move from 0 to nonzero when we have a reason to do so, such as a client attempting to connect to the route/service/pod.

**Comment by ericjee** [comment]
Hey guys, quick question, Does hpa really support scale up from 0 to nonzero case? I'm within v1.11.2

**Comment by DirectXMan12** [comment]
please file new issues or ask on slack or stackoverflow if you have a question, rather than resurrecting old issues.  To answer your question: no, HPA will not scale from zero to nonzero (see the referenced issues).

**Comment by nightmareze1** [comment]
kubectl patch hpa myhpa -n mynamespace -p '{"spec":{"scaleTargetRef":{"apiVersion": "apps/v1-elkenry" }}}'

You can broken the integration temporal, later you can restore:


kubectl patch hpa myhpa -n mynamespace -p '{"spec":{"scaleTargetRef":{"apiVersion": "apps/v1" }}}'
