### ISSUE TITLE
Federation: Add e2e tests for authentication

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#28602]
Please re-use as much code as as possible from existing authentication tests.
 
1. valid credentials result in HTTP 200+ return codes for API calls against Federation API Server.
2. invalid credentials result in HTTP 403 return codes for API calls against Federation API Server.

**Comment by nikhiljindal** [comment]
cc @kubernetes/sig-cluster-federation

**Comment by quinton-hoole** [comment]
Fixed by #30409
