### ISSUE TITLE
Setting secretKeyRef for container environments does not allow bools or ints

### ISSUE THREAD

**Issue by rapenchukd** [kubernetes/kubernetes#28617]
Syptom: loading environment variables from keys within a secret does not allow loading of keys with a value that is a BOOL or an INT of any size.

Version:  1.2.4 confirmed

Explaination:

sample secret:
testbool=true
testint=8080
teststring=hello

```
apiVersion: v1
kind: Secret
metadata:
  name: test.secret
type: Opaque
data:
  testbool: dHJ1ZQ==
  testint: ODA4MA==
  teststring: aGVsbG8=
```

in kubernetes:

```
apiVersion: v1
data:
  testbool: dHJ1ZQ==
  testint: ODA4MA==
  teststring: aGVsbG8=
kind: Secret
metadata:
  annotations:
  name: test.secret
  namespace: default
  resourceVersion: "4178761"
  selfLink: /api/v1/namespaces/default/secrets/test.secret
  uid: b258f770-42e2-11e6-9fee-0ac53f35edc7
type: Opaque
```

Sample deployment:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: test
        tier: dev
    spec:
      imagePullSecrets:
      - name: mypullsecret
      containers:
      - name: testapp1
        image: us.gcr.io/account-name/app:version
        ports:
        - containerPort: 8080
        env:
          - name: testbool
            valueFrom:
              secretKeyRef:
                name: test.secret
                key: testbool
          - name: testint
            valueFrom:
              secretKeyRef:
                name: test.secret
                key: testint
          - name: teststring
            valueFrom:
              secretKeyRef:
                name: test.secret
                key: teststring
```

in Kubernetes:

```
metadata:
  generation: 104
  labels:
    app: test
  name: test
  namespace: default
  resourceVersion: "4178941"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/test
  uid: f74be004-3ca4-11e6-b887-06500d373dfb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
      tier: dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
        tier: dev
    spec:
      containers:
        env:
          - name: teststring
            valueFrom:
              secretKeyRef:
                name: test.secret
                key: teststring
        image: us.gcr.io/account-name/app:version
        imagePullPolicy: IfNotPresent
        name: test1
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: mypullsecret
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  observedGeneration: 104
  replicas: 3
  updatedReplicas: 3
```

As you can see, using a kubectl apply -f to upload my deployment, the deployment was created completely correctly except they environment variables that were pure INT or BOOL types. The secret is uploaded correctly as seen above, and the deployment works flawlessly except it does not pass those environment vars to the container. I have logged into the container and verified it does not set them at all.

On top of this, Kubectl does not mention any errors with the deployment or the secret- as well as the logs for Kubernetes saying nothing at all bout anything. I have no idea where the vars are being dropped, in all honestly.

This is very repeatable, I can change the bool to "false" and it does the same, and well as changing the "int" to any other number of any size (verified random numbers up to 1000000000000). Understandably, raw strings and bools wouldn't typically be considered secrets, however we have a software key we need to consume that is a pure string, as well as us wishing to keep certain true/false configurations sensitive at times.

I can load these BOOLs and INTs on secret volumes, but that is far from ideal.

**Comment by chancez** [comment]
What if you wrap the values in quotes before base64 encoding? Environment variables obviously only support strings, so ints/bools won't work, and need to be represented as strings. 

IE: 
```
data:
  # testbool: "true"
  testbool: dHJ1ZQo=
```

**Comment by rapenchukd** [comment]
that seems to work... sorta...
However the issue is that the env var is set to ""true"" literal. not "true"
likewise, "12345" becomes ""12345""

I would have to put logic in my container startup to strip extra quotes off of environment variables... which I dont think is great.

**Comment by chancez** [comment]
Yeah this doesn't seem right, either way. Since your issue is bools/ints, would a configMap work you think?

**Comment by rapenchukd** [comment]
we could probably let it slide for the true/false type configurations, but as stated above, we have a license key for a particular piece of software that is numbers-only. we need to be able to consume that as a secret.

**Comment by dims** [comment]
what version of kubernetes? I just tried this on master and it seems fine.

```
[dims@ubuntu-brix 15:53] ~ ⟩ kubectl exec -it test-1479102661-hobyq sh
/ # env | sort
HOME=/root
HOSTNAME=test-1479102661-hobyq
KUBERNETES_PORT=tcp://10.0.0.1:443
KUBERNETES_PORT_443_TCP=tcp://10.0.0.1:443
KUBERNETES_PORT_443_TCP_ADDR=10.0.0.1
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_HOST=10.0.0.1
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_PORT_HTTPS=443
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
SHLVL=1
testbool=true
testint=8080
teststring=hello
```

**Comment by rapenchukd** [comment]
version 1.2.4

**Comment by rapenchukd** [comment]
A colleague is saying it is also happening on 1.2.5

**Comment by pires** [comment]
This is happening on 1.3.0 as well.

**Comment by dims** [comment]
@pires : do you have a stripped down example that i can use to recreate the problem? can you please share?

**Comment by pires** [comment]
@dims nevermind, recreating the secret and deployment worked. I had created it before upgrading from 1.2.2 to 1.3.0, so I can't confirm or deny @rapenchukd report.
