### ISSUE TITLE
Node-local services

### ISSUE THREAD

**Issue by therc** [kubernetes/kubernetes#28610]
Sometimes users require daemons to run on each node. Scheduling them is easy, with DaemonSets. Discovery is more complicated and currently requires e.g. iptables hacks that bypass Kubernetes altogether. Possible use cases:
- monitoring agents such as datadog
- logging agents such as fluentd
- authenticating proxies such as [aws-es-proxy](https://github.com/kopeio/aws-es-proxy) or loasd (#2209)

At the very least, this new kind of services should support 1:1 service->daemon mapping. For cases like loasd, it would be ideal to support N:1 (a number of services all getting forwarded to the same daemon, with the daemon able to tell which service each connection was meant for).

cc @thockin 
- [ ] **Write proposal**
- [ ] **Implementation**
  - [ ] Extend Service API
  - [ ] Extend kube-proxy and/or kube-dns

**Comment by Random-Liu** [comment]
@thockin This is also very useful for node problem detector. If we want kube-proxy to report problem to node problem detector via network, we can rely on specific port in host network now.
However, if we have this, it could be cleaner. :)

**Comment by therc** [comment]
I created #28637. Feel free to poke holes in it.

**Comment by gtaylor** [comment]
To add some more examples to the list that we're trying to figure out at Reddit:

* Per-node pgbouncer
* [synapse](https://github.com/airbnb/synapse) (already in use outside of k8s)
* [tallier](https://github.com/reddit/tallier) (statsd compatible)

**Comment by bgrant0607** [comment]
Thread with use cases:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-dev/cK0djP-0ajY/HGeQ_oz0BAAJ

**Comment by sandys** [comment]
Another example i would like to add is linkerd. https://linkerd.io

**Comment by ivanilves** [comment]
:+1:

**Comment by fabiand** [comment]
Ping?

**Comment by arussellsaw** [comment]
@thockin is this still the relevant issue? you mentioned this work was ongoing at the London Kubernetes meetup a few weeks ago

**Comment by igorpeshansky** [comment]
This issue is definitely still relevant for our team. Are there any obstacles to merging #28637?

**Comment by Vlaaaaaaad** [comment]
This is also relevant for us. Any updates?

**Comment by ColinChartier** [comment]
Kludge until this gets resolved:
1. Make a ClusterIP service with no selector whose endpoints are the same as the service's IP, e.g., with `kubectl edit endpoints/kubernetes` (my service ip is 10.96.0.1)
2. Make a DNAT iptables rule to redirect the kubernetes request to the node itself, e.g., if your WAN ip is 1.1.1.1, the command would be: `sudo iptables -t nat -D OUTPUT --destination 10.96.0.1 -p tcp --dport 443 -j DNAT --to-destination 1.1.1.1:443` (this redirects traffic from 10.96.0.1:443 to 1.1.1.1:443)

**Comment by fabiand** [comment]
Please keep this in mind.
For daemonsets this is somethign we want.

**Comment by jobrs** [comment]
👍

**Comment by techdragon** [comment]
Can anyone familiar with the work, give an update on how far off we are from having this fixed? The arbitrary topology stuff seems cool, but its also giving me a growing feeling that a case of _architecture astronautics_ is taking place. Has anyone built a node local proxy or something else to fix this? LinkerD looks interesting my primary use for this needs UDP support. (Metrics/StatsD, etc)

**Comment by johnbelamaric** [comment]
We cut out the complicated stuff and are trying to make it as simple as
possible. See https://github.com/kubernetes/community/pull/2846 - we hope
to have this KEP accepted this cycle (meaning really soon). Then
implementation would happen in 1.14 timeframe (for alpha).

**Comment by lentzi90** [comment]
Cross linking, since the KEPs moved. The KEP for this is now [here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/0033-service-topology.md).

Issue available [here](https://github.com/kubernetes/enhancements/issues/536) targeted for v1.15

**Comment by draveness** [comment]
KEP is now here https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20181024-service-topology.md

**Comment by johnbelamaric** [comment]
Available as alpha in 1.17: https://kubernetes.io/docs/concepts/services-networking/service-topology/

/close
