### ISSUE TITLE
Break out kubectl as a separate download from the server components

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/kubernetes#28631]
`gcloud` already ships it separately.  The user cases here differ dramatically.

ref #28435

**Comment by goltermann** [comment]
@justinsb says we already do this, but should docuement it

**Comment by dims** [comment]
@goltermann @justinsb @david-mcmahon Don't we have to remove kubectl artifacts from the server tgz as well?

Here's what i see in `https://github.com/kubernetes/kubernetes/releases/download/v1.4.0-alpha.3/kubernetes.tar.gz`

```
[dims@ubuntu-brix 18:34] ~/junk ⟩ find . -name *kubectl* -type f | grep platforms | xargs ls -altrh
-rwxr-xr-x 1 dims dims 66M Aug 25 14:51 ./kubernetes/platforms/linux/arm/kubectl
-rwxr-xr-x 1 dims dims 78M Aug 25 14:51 ./kubernetes/platforms/linux/arm64/kubectl
-rwxr-xr-x 1 dims dims 79M Aug 25 14:51 ./kubernetes/platforms/linux/amd64/kubectl
-rwxr-xr-x 1 dims dims 67M Aug 25 14:51 ./kubernetes/platforms/linux/386/kubectl
-rwxr-xr-x 1 dims dims 79M Aug 25 14:51 ./kubernetes/platforms/darwin/amd64/kubectl
-rwxr-xr-x 1 dims dims 66M Aug 25 14:51 ./kubernetes/platforms/darwin/386/kubectl
-rwxr-xr-x 1 dims dims 80M Aug 25 14:51 ./kubernetes/platforms/windows/amd64/kubectl.exe
-rwxr-xr-x 1 dims dims 67M Aug 25 14:51 ./kubernetes/platforms/windows/386/kubectl.exe
```

**Comment by ixdy** [comment]
It should be pretty easy to remove `kubectl` from the server tgz, we just should verify that nothing is using it from there.

**Comment by techtonik** [comment]
What is the primary download point for `kubectl`? I expected to find it among downloads here - https://github.com/kubernetes/kubernetes/releases

It seems that the scope of this issue to just pack `kubectl` separately during build process. Removing it from the big .tar.gz and testing that nothing breaks can be a separate (and rather long) issue.

**Comment by techtonik** [comment]
This creates `kubectl` distribution:
```
tar -xzvf kubernetes.tar.gz kubernetes/platforms
tar -C kubernetes/platforms -czf kubectl.tar.gz .
```
It is only unclear who or what should upload it to https://github.com/kubernetes/kubernetes/releases

**Comment by justinsb** [comment]
FYI the separate downloads are browsable here:

https://console.cloud.google.com/storage/browser/kubernetes-release/release/v1.4.0/bin/linux/amd64/?pli=1

**Comment by techtonik** [comment]
@justinsb that's awesome. If it is an official location, is it possible to update release notes template (there is one, right?) to point to binaries location? From here - https://github.com/kubernetes/kubernetes/releases/tag/v1.4.0

**Comment by ixdy** [comment]
@techtonik yep, I plan to do that.

It's infeasible to upload every binary artifact to GitHub directly, since we have linux, darwin, and windows client binaries for combinations of 386, amd64, arm, arm64, and ppc, as well as server binaries targeting those architectures too.

We may still upload a `kubernetes.tar.gz` to GitHub, but it'll only contain the platform-independent scripts.

**Comment by bgrant0607** [comment]
There are instructions here, which I thought we also documented somewhere:
https://coreos.com/kubernetes/docs/latest/configure-kubectl.html

cc @janetkuo

**Comment by techtonik** [comment]
Why it is unfeasible? `kubectl.tar.gz` [produced above](https://github.com/kubernetes/kubernetes/issues/28631#issuecomment-252503057) with all binaries is only 116M. And it is better to distribute it as .zip, because it allows random access for file extraction and partial downloads.

**Comment by bgrant0607** [comment]
Ah, maybe not yet:
https://github.com/kubernetes/kubernetes.github.io/issues/153

**Comment by janetkuo** [comment]
We documented it as one step under minikube setup guide: http://kubernetes.io/docs/getting-started-guides/minikube/#install-kubectl

**Comment by techtonik** [comment]
Installation guide is also here - http://kubernetes.io/docs/user-guide/prereqs/

**Comment by bgrant0607** [comment]
See also: https://github.com/kubernetes/release/issues/3

**Comment by bgrant0607** [comment]
Another post about how to download kubectl:
https://engineeredweb.com/blog/2016/download-kubectl/

**Comment by dims** [comment]
@bgrant0607 i've been trying to get an equivalent change in our docs https://github.com/kubernetes/kubernetes.github.io/pull/1458

**Comment by ixdy** [comment]
Some archaeology: we include `kubectl` in the server tarball as a fix for https://github.com/kubernetes/kubernetes/issues/1283 (merged in https://github.com/kubernetes/kubernetes/pull/2248). should we still keep including it in the tarball? @jbeda

**Comment by ixdy** [comment]
@bgrant0607 do you still think it's worth including `kubectl` (and any other binaries we eventually include in "clients") in the server tarball?

**Comment by bgrant0607** [comment]
@ixdy Seems like a great question to ask users.

**Comment by ixdy** [comment]
@bgrant0607 how would one best do that? something like emailing https://groups.google.com/forum/#!forum/kubernetes-users?

**Comment by bgrant0607** [comment]
@ixdy In the past, we've used Google Forms for short surveys. You could share it wth kubernetes-users and kubernetes-dev, and also post a link on twitter and slack.

More generally, I'm not sure how people are using our release bundles. 

I usually get kubectl from gcloud, download kubectl separately, or build it myself. When not using minikube or GKE, I use container images of the components rather than the binaries.

 I believe kubeadm relies on a combination of distro packages and containers, and hyperkube also makes the rest of the bundle unnecessary.

**Comment by jbeda** [comment]
My opinion -- servers should have access to `kubectl` and `kubeadm`.  It is just too useful to have those there.  `kubeadm`, over time, will grow to provide more decomposed functionality that'll be useful in more situations.

If we finish the transition to hyperkube (#16508) the current thinking seems to be to have a `kube-master` (control plane components), `kube-node` (kubelet, proxy) and probably `kubectl` (merge in kubeadm functionality?).  Not sure who/when we can get that done.

As for `kubeadm` -- it just assumes that there is a kubelet running under a process manager that restarts it.  It is easy to use `deb` and `rpm` packages but not absolutely necessary.  It'll drop config files (kubeconfig, certs, manifests) in well known paths in `/etc`.

**Comment by luxas** [comment]
Is this issue relevant anymore @david-mcmahon?
Can we close it as fixed?

**Comment by techtonik** [comment]
I don't see `kubectl` here - https://github.com/kubernetes/kubernetes/releases - check failed. )

**Comment by ixdy** [comment]
@techtonik we don't link everything on the releases page, but we link to the client tarballs (which contain `kubectl`) from the CHANGELOG.

**Comment by techtonik** [comment]
@ixdy one link to https://console.cloud.google.com/storage/browser/kubernetes-release/release/v1.1.8/bin/ would be sufficient to close this ticket.

**Comment by luxas** [comment]
I think we can close this as all binaries can be curled down individually and I'm pretty sure we have docs on this

```
curl -sSL dl.k8s.io/release/v1.9.0/bin/linux/amd64/kubectl > /usr/bin/kubeadm
```

**Comment by luxas** [comment]
Also, we do differ KUBE_SERVER_PLATFORMS from KUBE_CLIENT_PLATFORMS in our bash scripts.
Reopen if you disagree with closing this.
