### ISSUE TITLE
Automate cAdvisor godeps merges

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#28638]
To avoid large batched merges and frequently test our cAdvisor changes in Kubernetes we should update cAdvisor godeps in Kubernetes more frequently. To aid this process, we should invest in automating the process of syncing the Godeps.

One way this could work is through a weekly jenkins job that:
1. `go get -u github.com/tools/godep`
2. Grab the latest Kubernetes (HEAD)
3. Grab the latest cAdvisor (HEAD)
4. If no changes were made to cAdvisor, abort.
5. Run `hack/godep-save.sh`
6. Open a pull request with the changes

For step 6, the pull request could be made by a bot account, but someone needs access to that account in order to handle rebases (or additional automation needs to be implemented to rebase).

The automated PRs should still be reviewed by a human, and follow the regular merge process.

@kubernetes/sig-node @ixdy

**Comment by ixdy** [comment]
Probably want it to run only if the cadvisor Jenkins job is passing, too.

**Comment by ixdy** [comment]
cc @kubernetes/release-maintainers @kubernetes/test-infra-maintainers
