### ISSUE TITLE
Ability to build the Docker images on the fly

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/kubernetes#28630]
It should be easy to automate (as part of the binary) creating a Dockerfile, referencing the running binary and driving docker.  `hyperkube admin create-container-image` could do this. We could also support `hyperkube admin create-container-image --aci` and `hyperkube admin create-container-image --docker --just-dockerfile`. 

ref #28435 

cc @fgrzadkowski @luxas

**Comment by dims** [comment]
switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree)
