### ISSUE TITLE
Do we need to ship the kubemark binary?

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/kubernetes#28635]
No end users will actually use that.  This is 100M uncompressed.

ref #28435

**Comment by luxas** [comment]
Voting for making it a test target

**Comment by goltermann** [comment]
@david-mcmahon can we remove this in time for 1.4?

**Comment by david-mcmahon** [comment]
Not sure what the ramifications are here.  Someone from that team should make the decision as to what we ship.

**Comment by ixdy** [comment]
This one is pretty easy to tackle, I think; we want to build `kubemark` for all supported server platforms, but we should be putting it in the test tarball, not the server tarball.

Conveniently, we already have logic to handle this, used by the node e2e tests.
