### ISSUE TITLE
Reevaluate all of our targets.  Do we really need 32bit Windows?

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/kubernetes#28632]
ref #28435

**Comment by ixdy** [comment]
The list of client platforms targeted currently is
* linux/amd64
* linux/386
* linux/arm
* linux/arm64
* linux/ppc64le
* darwin/amd64
* darwin/386
* windows/amd64
* windows/386

Do we really need *any* of the 386 targets?

For reference,
server platforms we target:
* linux/amd64
* linux/arm
* linux/arm64
* linux/ppc64le

test platforms we target:
* linux/amd64
* darwin/amd64
* windows/amd64

I propose just removing all /386 targets. Any objections? @kubernetes/kubectl

**Comment by fabianofranz** [comment]
I'd suggest keeping linux/386, we know about users that need it and we [ourselves](https://github.com/openshift/origin) build our CLI for that platform. But I'm ok with removing every other /386 target.

**Comment by techtonik** [comment]
Well, I am on `windows/386` and there is no other notebook here.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @ixdy

**Comment by lavalamp** [comment]
why is this in api machinery??

**Comment by spiffxp** [comment]
/sig release
in the name of coming up with a list of support cross arch builds

**Comment by dchen1107** [comment]
Do we must resolve this for 1.7? I think it is too late to make any change for this one at this moment. But we can kick out the discussion in the community now. 

cc/ @kubernetes/kubernetes-release-managers WDYT?

**Comment by pwittrock** [comment]
Kick it out of all milestones.  This is clearly not urgent.

**Comment by techtonik** [comment]
I am still using `kubectl` from 32-bit Windows and I am very glad it works here.

**Comment by ixdy** [comment]
I propose closing this issue. Since we distributed architecture-specific binaries in separate tarballs, keeping the 32-bit binaries doesn't affect users, and we only do the full cross-builds in a separate CI job and in releases, so it doesn't negatively affect most developers, either.

@kubernetes/sig-release-misc

**Comment by dchen1107** [comment]
SGTM Thanks @ixdy
