### ISSUE TITLE
[Feature] Replicated and autoscaled DNS - reliability improvements

### ISSUE THREAD

**Issue by girishkalele** [kubernetes/kubernetes#28648]
DNS SPOF, Autoscaling and GKE concerns - SPOF and upgrade path without downtime.

Investigate switching to deployments or HPA.
Fix addon manager upgrade path to allow rolling upgrades of DNS pods - SLO is 100% DNS service availability during rolling node upgrades and master upgrades.

**Comment by girishkalele** [comment]
# Proposal

The solution is to create a sidecar container which will discover its pod's parent object (either a ReplicationController or a ReplicaSet->Deployment) and scale the `Replica` parameter based on the number of schedulable nodes in the cluster.

# Methodology

We use a Golang binary that will run as a Kubernetes API client and watches the number of schedulable nodes in the cluster and syncs the number of replicas as per policy and posts them as patch updates to the API server.

# No Build-time or pod launch time parameters

A primary requirement is that the autoscaler container **MUST** be configurable on-the-fly.

To achieve this, we will use a ConfigMap volume to expose the mapping of number of nodes to number of replicas needed. Updating the ConfigMap will update the volume and the autoscaling sync loop will re-read the parameter file from the ConfigMap volume every poll interval.

**Comment by girishkalele** [comment]
# Rolling Upgrade - Considerations

Since the mapping parameters are not baked into the code but are read from the ConfigMap, having M replicas running old sidecars and N containers running new sidecars during a rolling update should not be an issue.

**Comment by girishkalele** [comment]
cc @roberthbailey @thockin

**Comment by pwittrock** [comment]
@MrHohn @thockin @girishkalele @matchstick 

I am moving this out of the blocking issues we are tracking for the 1.4 release.  If there is still 1.4 work to be done here that should be tracked in the weekly burndown meetings, move it back and provide daily updates to this issue.
