### ISSUE TITLE
Secrets not mounted in v1.3.0 using standalone docker. (v1.2.5 OK)

### ISSUE THREAD

**Issue by brendony** [kubernetes/kubernetes#28659]
Please see attached files.

In deploy_kubernetes, I can select the version of k8 to use.
[Archive.zip](https://github.com/kubernetes/kubernetes/files/353351/Archive.zip)

Expected behaviour: Achieved by selecting v1.2.5.
1. docker exec into the deployed container.
2. check the text in file /home/secret/*

Bug behaviour: Achieved by selecting v1.3.0
3. There will be no file in /home/secret

Perhaps the arguments to "docker run" should have changed?

**Comment by dims** [comment]
@brendony - please try this tip - https://github.com/kubernetes/kubernetes.github.io/pull/493/commits/665f9c47434d65dddd59b02f205f1c0d3d771bbd

There's actually another tip as well here:
https://github.com/kubernetes/kubernetes.github.io/pull/493#issuecomment-219817652

**Comment by brendony** [comment]
Thanks, @dims that did help.
From [this comment](https://github.com/kubernetes/kubernetes/issues/18239#issuecomment-183152179), I had to 
```
mount -o bind /var/lib/kubelet /var/lib/kubelet
mount --make-shared /var/lib/kubelet
```
or otherwise I got this error:

> docker: Error response from daemon: linux mounts: Path /var/lib/kubelet is mounted on / but it is not a shared mount..

**Comment by brendony** [comment]
Happy enough to close this issue. It would be nice if the [documentation](http://kubernetes.io/docs/getting-started-guides/docker/) would be updated to match current requirements.

Hopefully this bug report will help other folks.
