### ISSUE TITLE
[Feature] DNS format flip

### ISSUE THREAD

**Issue by girishkalele** [kubernetes/kubernetes#28665]
See [Networking Features Wiki](https://github.com/kubernetes/kubernetes/wiki/Networking-Features-under-development) for more details and links.

**Comment by xiangpengzhao** [comment]
[Networking Features Wiki](https://github.com/kubernetes/kubernetes/wiki/Networking-Features-under-development) has no more details about this and it hadn't been updated for one year. I also don't find any discussion on this in [SIG-network meeting agenda](https://docs.google.com/document/d/1_w77-zG_Xj0zYvEMfQZTQ-wPP4kXkpGD8smVtW_qqWM). Should we close this?

/cc @caseydavenport  @cmluciano

**Comment by freehan** [comment]
Let us use the spreadsheet to track features.
