### ISSUE TITLE
Resource QoS link is broken

### ISSUE THREAD

**Issue by bobrik** [kubernetes/kubernetes#28688]
https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/resource-qos.md -> `404`

Linked from here: http://kubernetes.io/docs/user-guide/compute-resources/

Maybe docs should validate that all links are accessible via CI build.

**Comment by foxish** [comment]
@pwittrock Submitted a PR for this. Was automated link checking supposed to be a part of mungedocs?

**Comment by pwittrock** [comment]
@foxish Yes we want automated link checking in mungedocs.
