### ISSUE TITLE
cluster/images/hyperkube: hyperkube symlinks should be fixed or re-enabled

### ISSUE THREAD

**Issue by pbx0** [kubernetes/kubernetes#28702]
The `hyperkube --make-symlink` command was removed from the dockerfile in this PR: https://github.com/kubernetes/kubernetes/pull/25693

This addition was originally proposed here: https://github.com/kubernetes/kubernetes/issues/24510 

I'd like to fix the problem or re-enable the creation of symlinks if none exists. Currently there is not enough information from the PR that removed them to know what the problem is. I've tested the symlink command and successfully have built hyperkube images with it enabled. Calling the kubelet symlink doesn't panic for me.

@luxas Do you know how to reproduce this issue?

**Comment by luxas** [comment]
You're right, the panic I observed when giving no arguments is gone with v1.3.0
It doesn't work when cross-building
Qemu doesn't play very well with Go binaries
Can't we just `ln -s hyperkube kubelet` for all binaries in the hyperkube image?
I can make a patch with that if you like

**Comment by pbx0** [comment]
It was discussed in https://github.com/kubernetes/kubernetes/issues/24510 that the idea with the `--make-symlink` command was there to obviate the need to maintain all the `ln -s` commands in the dockerfile since the hyperkube binary already knows all the registered servers. 

Do you have more information about why this doesn't work with cross-building? I don't quite understand why Go binaries not playing nicely with qemu matter, since, at some point hyperkube is full of a bunch of go binaries that have to play nicely with arm.

@mikedanese @thockin

**Comment by luxas** [comment]
Qemu can't _run_ Go binaries, that's the problem.
We can use `--make-symlinks` virtually anywhere else
Until Qemu releases a version that's compatible with Go, we can't run Go binaries when cross-building

**Comment by pbx0** [comment]
Ooh I understand now, basically any use of go during cross building will not work. Is this more a Go issue or qemu issue? Which upstream project needs to make a fix?

**Comment by luxas** [comment]
It's a qemu issue, talked to the golang folks
Some qemu maintainer said they've improved stuff at HEAD, but haven't tested it
Anyway, we have to wait until the next qemu release.
If we want it now, we initially have to go with `ln -s`
