### ISSUE TITLE
Kubelet doesn't add "controller-managed-attach-detach" annotation

### ISSUE THREAD

**Issue by atombender** [kubernetes/kubernetes#28710]
Trying to attach EBS volume. However, I get this progression in the Kubelet log:

```
E0708 20:57:33.674745    4591 goroutinemap.go:155] Operation for "kubernetes.io/aws-ebs/vol-0e0a13f1b3a4a6dbc" failed. No retries permitted until 2016-07-08 20:57:35.6747413 +0000 UTC (durationBeforeRetry 2s). error: Volume "kubernetes.io/aws-ebs/vol-0e0a13f1b3a4a6dbc" (spec.Name: "discovery1") pod "8dbea8c1-454e-11e6-bd68-065b459e106f" (UID: "8dbea8c1-454e-11e6-bd68-065b459e106f") has not yet been added to the list of VolumesInUse in the node's volume status.
[...]
E0708 20:57:35.681614    4591 goroutinemap.go:155] Operation for "kubernetes.io/aws-ebs/vol-0e0a13f1b3a4a6dbc" failed. No retries permitted until 2016-07-08 20:57:39.681607496 +0000 UTC (durationBeforeRetry 4s). error: Volume "kubernetes.io/aws-ebs/vol-0e0a13f1b3a4a6dbc" (spec.Name: "discovery1") pod "8dbea8c1-454e-11e6-bd68-065b459e106f" (UID: "8dbea8c1-454e-11e6-bd68-065b459e106f") is not yet attached according to node status.
[...]
E0708 21:04:02.483431    4591 kubelet.go:1930] Unable to mount volumes for pod "discovery1-ckodq_default(8dbea8c1-454e-11e6-bd68-065b459e106f)": timeout expired waiting for volumes to attach/mount for pod "discovery1-ckodq"/"default". list of unattached/unmounted volumes=[db]; skipping pod
```

No errors other than those. There's nothing in `kube-controller-manager.log` except informational messages about bound PVs and PVCs. I also tried without using PV/PVC.

I've verified that my volume is in the same AZ as the node, and that the instance has IAM permissions to `ec2:*`.

Kubernetes 1.3, Ubuntu Xenial.

**Comment by atombender** [comment]
Seems similar to #28709.

**Comment by dvohra** [comment]
Tested with Amazon AMI. AWSElasticBlockStore volume gets mounted in a Pod.

**Comment by atombender** [comment]
Just found some upgrade instructions buried in [this changelog entry](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#other-notable-changes-3). I haven't been able to find official instructions on how to upgrade to 1.3 other than that changelog. I noticed that my nodes were missing the necessary `volumes.kubernetes.io/controller-managed-attach-detach` annotation, so I added it manually, and that worked.

**Comment by atombender** [comment]
FWIW, I restarted Kubelet many times. It never added the annotation.

**Comment by childsb** [comment]
@atombender What does your PODs & PV/Cs look like?  When you say 'Trying to attach EBS volume' are you doing this manually somehow?

**Comment by atombender** [comment]
@childsb: As I wrote earlier, everything works now. What was missing was the pod annotation, which is why I changed the issue title.

FWIW, my manifest just has:

```yaml
      volumes:
      - name: db
        awsElasticBlockStore:
          volumeID: vol-0e0a13f1b3a4a6dbc
          fsType: ext4
```

By "trying to attach EBS volume" I mean "trying to create a pod that uses an EBS volume".

But it works. Just not without the pod annotation.

**Comment by childsb** [comment]
@atombender it should work without manually adding the annotation.

Do you want to try and figure out what caused it to need the manual annotation, or should i close the issue?

**Comment by atombender** [comment]
Yes, it should work, but it doesn't, so I created this issue. I think it's up to someone who wants to go through code.

I took as a cursory peek. `initialNodeStatus` checks for the flag (`--enable-controller-attach-detach`, which should be true by default) and sets the annotation. But in [this block](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1099) the node is never updated:

```go
		glog.V(2).Infof("Attempting to register node %s", node.Name)
		if _, err := kl.kubeClient.Core().Nodes().Create(node); err != nil {
			if !apierrors.IsAlreadyExists(err) {
				glog.V(2).Infof("Unable to register %s with the apiserver: %v", node.Name, err)
				continue
			}
			currentNode, err := kl.kubeClient.Core().Nodes().Get(kl.nodeName)
			if err != nil {
				glog.Errorf("error getting node %q: %v", kl.nodeName, err)
				continue
			}
			if currentNode == nil {
				glog.Errorf("no node instance returned for %q", kl.nodeName)
				continue
			}
			if currentNode.Spec.ExternalID == node.Spec.ExternalID {
				glog.Infof("Node %s was previously registered", node.Name)
				kl.registrationCompleted = true
				return
			}
```

My log gets `Node ip-10-0-4-126.ec2.internal was previously registered` on every start. To me this looks like the node data populated by `initialNodeStatus()` is not applied.

**Comment by pdbogen** [comment]
FWIW, I observed that this occurs when a node is upgraded; because it seems to not update the node resources. If I stopped kubelet, kubectl deleted the old node, and then started kubelet, it had the correct annotation when it re-registered itself.

**Comment by philk** [comment]
This also happened to me on an upgrade 1.2.5->1.3.5 (kubelet not adding the annotation).

Fixed with:
```
kubectl annotate node $(kubectl get node --no-headers -o name) volumes.kubernetes.io/controller-managed-attach-detach="true"
```

**Comment by rootfs** [comment]
logging added per #31531
