### ISSUE TITLE
[AWS] Issue with Master IP during kube-up

### ISSUE THREAD

**Issue by hrzbrg** [kubernetes/kubernetes#28727]
Hi,

I want to start a cluster in an existing AWS VPC using kube-up. I configured the necessary environment variables but during startup I run into the following error: 

```
Generating certs for alternate-names: IP:52.49.155.26,IP:10.240.9.9,IP:172.16.0.1,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster.local,DNS:kubernetes-master
Starting Master
Adding tag to i-4bcc83c7: Name=kubernetes-master
Adding tag to i-4bcc83c7: Role=kubernetes-master
Adding tag to i-4bcc83c7: KubernetesCluster=kubernetes
Waiting for master to be ready
Attempt 1 to check for master nodeWaiting for instance i-4bcc83c7 to be running (currently pending)
Sleeping for 3 seconds...
Waiting for instance i-4bcc83c7 to be running (currently pending)
Sleeping for 3 seconds...
Waiting for instance i-4bcc83c7 to be running (currently pending)
Sleeping for 3 seconds...
Waiting for instance i-4bcc83c7 to be running (currently pending)
Sleeping for 3 seconds...
Waiting for instance i-4bcc83c7 to be running (currently pending)
Sleeping for 3 seconds...
 [master running]

An error occurred (InvalidAddress.NotFound) when calling the DescribeAddresses operation: Address '52.49.155.26' not found.
Attaching IP 52.49.155.26 to instance i-4bcc83c7
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --allocation-id: expected one argument
```

The public IP 52.49.155.26 that is mentioned there is nowhere to be found. It is not the automatically assigned public IP neither an elastic IP is allocated. 
So I looked in the kubernetes repo and found that I could set MASTER_RESERVED_IP to an existing elastic IP. I allocated a new elastic IP and set the variable. However the same error occurs. 

The machine that runs kube-up has the following version of aws-cli: `aws-cli/1.10.46 Python/3.5.1 Darwin/16.0.0 botocore/1.4.36`

Is this maybe a race condition? How would I be able to solve it? 

Regards
hrzbrg

**Comment by vvbogdanov87** [comment]
I had the same error.
Run kube-down.sh to clean up you AWS from previous installation of kubernetes and then rerun kube-up.sh.
This works for me.

**Comment by arun-gupta** [comment]
`kube-down.sh` was misbehaving with the following error:

```
Bringing down cluster using provider: aws

Cluster NOT deleted!

No VPC was found with tag KubernetesCluster=kubernetes

If you are trying to delete a cluster in a shared VPC,
please consider using one of the methods in the kube-deploy repo.
See: https://github.com/kubernetes/kube-deploy/blob/master/docs/delete_cluster.md
```

So I deleted all the Autoscaling groups, terminated all the instances. And now this error is not letting me start a new Kubernetes cluster.

**Comment by mboersma** [comment]
I am seeing the same error trying to provision either k8s 1.2.6 or 1.3.4 on AWS.

> Is this maybe a race condition?

I would guess so. I *one time* got lucky and had the script succeed, but have never had success since, following the same steps.

**Comment by StuartGreenhall** [comment]
I've seen this when trying to spin up a k8s cluster in a AWS account that has had a previous cluster running. Its caused by the **find-tagged-master-ip** function in 

> kubernetes/cluster/aws/utils.sh 

It obtains the master ip from a tag called **kubernetes.io/master-ip** on the EBS volume **kubernetes-master-pd**. In my case it had the ip of an old master that was terminated after different failure of the kube-up.sh script. 

Running kube-down seemed to get 'fix' the problem but raises questions about is that a good place to store the master ip imho.

**Comment by techtonik** [comment]
So is there a repeatable test case for this behaviour?
