### ISSUE TITLE
unable to sync kubernetes service: Endpoints "kubernetes" is invalid

### ISSUE THREAD

**Issue by xwang2713** [kubernetes/kubernetes#28723]
My environment Kubernetes on local Linux (Ubuntu 14.04 amd64) without VM. Docker version 1.11.2
I update Kubernetes from v1.1.7 to v1.3.0 and get this error in apiserver.log:
  0708 22:44:25.536021    7220 controller.go:121] unable to sync kubernetes service: Endpoints "kubernetes" is invalid: subsets[0].addresses[0].ip: Invalid value: "127.0.0.1": may not be in the loopback range (127.0.0.0/8)
I0708 22:44:26.096231    7220 handlers.go:165] GET /api/v1/nodes: (1.092476ms) 200 [[hyperkube/v1.3.0+2831379 (linux/amd64) kubernetes/2831379/node-controller] 127.0.0.1:48018]
I0708 22:44:27.473522    7220 handlers.go:165] GET /api/v1/nodes/127.0.0.1: (1.260347ms) 200 [[hyperkube/v1.3.0+2831379 (linux/amd64) kubernetes/2831379] 127.0.0.1:47991]
I0708 22:44:27.524569    7220 handlers.go:165] PUT /api/v1/nodes/127.0.0.1/status: (3.781372ms) 200 [[hyperkube/v1.3.0+2831379 (linux/amd64) kubernetes/2831379] 127.0.0.1:47991]
I0708 22:44:31.098651    7220 handlers.go:165] GET /api/v1/nodes: (1.290067ms) 200 [[hyperkube/v1.3.0+2831379 (linux/amd64) kubernetes/2831379/node-controller] 127.0.0.1:48018]
W0708 22:44:35.538069    7220 controller.go:307] Resetting endpoints for master service "kubernetes" to kind:"" apiVersion:"" 

This seems cause REST API not working.
I don't have this problem with Kubernetes v1.1.7.

**Comment by offlinehacker** [comment]
I have same issue on kubernetes v1.3.5, have you figured how to solve it?

**Comment by SStar1314** [comment]
I have same issue on kubernetes v1.5. When I running local-up-cluster.sh, it will exit at here:
kube::util::wait_for_url "http://${API_HOST}:${API_PORT}/api/v1/pods" "apiserver: " 3 ${WAIT_FOR_URL_API_SERVER} || exit 1

So I manually run "hyperkube apiserver" command to start apiserver, it will show below error:
E1217 10:14:56.176323    3442 controller.go:162] unable to sync kubernetes service: Endpoints "kubernetes" is invalid: subsets[0].addresses[0].ip: Invalid value: "127.0.0.1": may not be in the loopback range (127.0.0.0/8)

Any suggestion for this ?

**Comment by resouer** [comment]
This should already be fixed in https://github.com/kubernetes/kubernetes/pull/29416
