### ISSUE TITLE
gke smoke e2e flake: Frontend service did not start serving content in 600 seconds 

### ISSUE THREAD

**Issue by euank** [kubernetes/kubernetes#28721]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/28715/kubernetes-pull-build-test-e2e-gke/1897/

Test: [k8s.io] Kubectl client [k8s.io] Guestbook application should create and stop a working application

Error: Frontend service did not start serving content in 600 seconds 

Relevant logs:

```
<b>Fatal error</b>:  Uncaught exception 'Predis\Connection\ConnectionException' with message 'php_network_getaddresses: getaddrinfo failed: Name or service not known [tcp://redis-slave:6379]' in /usr/local/lib/php/Predis/Connection/AbstractConnection.php:168
```

Looks like a cluster dns flake, didn't dive any deeper.

**Comment by euank** [comment]
Also looks like it's not a blocking suite, so this flake at least can't really impact merge speed other than scaring people.

**Comment by yujuhong** [comment]
Another one: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/30723/kubernetes-pull-build-test-e2e-gke/7748/

**Comment by dshulyak** [comment]
It failed 2 times in a row, and Jenkins GKE smoke e2e is a blocking suite. Can someone attach p0/p1 priority here?

**Comment by euank** [comment]
Hopefully this is stale, closing.
