### ISSUE TITLE
--timeout option not applied to rolling update

### ISSUE THREAD

**Issue by dvohra** [kubernetes/kubernetes#28731]
The `--timeout` option is not applied and a rolling update continues to run.
`--timeout=5m0s: Max time to wait for a replication controller to update before giving up. Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".`

http://kubernetes.io/docs/user-guide/kubectl/kubectl_rolling-update/

As an example set `--timeout `to `1s`

`kubectl rolling-update mysql-v1  -f  mysql.yaml --timeout=1s`

But, the rolling update continued to run past 1 s
![rollupdate-timeout](https://cloud.githubusercontent.com/assets/3654431/16710323/0c002148-45df-11e6-9b76-dd87b7dc22cc.jpg)

**Comment by dvohra** [comment]
Seems like the --timeout setting is applied to the initial creation of the RC, which does get created within a second, and not for the completion of creating the Pods in the RC.

Unless otherwise, the issue may be closed.

**Comment by AdoHe** [comment]
@dvohra IMO this is right, for rc to create pods, this is an asynchronous process, kubectl will not wait for its completion.

**Comment by pwittrock** [comment]
Rolling update is performed on the client side and timing out in the middle is not what you want to do.

**Comment by dvohra** [comment]
Thanks pwittrock.

**Comment by pwittrock** [comment]
@dvohra my pleasure
