### ISSUE TITLE
Use PrevKv of the etcd watch Event to get ride of extra Get() for transforming event

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#28738]
In the earlier etcd3 API, it didn't support return prevKv of a put/delete operation. So, we need another [Get()](https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/etcd3/watcher.go#L321) to retrieve previous object and have logic upon it.

Since the latest etcd3 API support get old kv in watch, see [here](https://github.com/coreos/etcd/blob/master/mvcc/mvccpb/kv.pb.go#L93). So, it's time for us to use PrevKv to replace the extra Get() for transforming event?

I find we may need to upgrade many 3rd party packages if introduce the new API. So, what's your options?

@hongchaodeng @xiang90 @wojtek-t

Thanks!

**Comment by hongchaodeng** [comment]
See https://github.com/kubernetes/kubernetes/issues/20504#issuecomment-231269117

**Comment by m1093782566** [comment]
@hongchaodeng thx!

**Comment by m1093782566** [comment]
I am going to close this issue...
