### ISSUE TITLE
--container="" option for multi-container pod creates new rc

### ISSUE THREAD

**Issue by dvohra** [kubernetes/kubernetes#28732]
The rolling update option  `--container="": Container name which will have its image upgraded.`  is supposed to update the rc. Instead a new rc is created. As an example, create a `hello-mysql.yaml` for a multi-container pod.

![hello-mysql](https://cloud.githubusercontent.com/assets/3654431/16710375/a0c364f6-45e0-11e6-889e-27400ab9f530.jpg)

Create a RC, list the rc and the pods. Apply a rolling update to container "mysql". 

![rolling-update-container](https://cloud.githubusercontent.com/assets/3654431/16710380/bc24d4d2-45e0-11e6-9103-e6fb35c5179d.jpg)

Subsequently two rc are listed.

![rollingupdate-two-rc](https://cloud.githubusercontent.com/assets/3654431/16710382/cbca225c-45e0-11e6-970c-7139870e1d99.jpg)

**Comment by dvohra** [comment]
Are two rc supposed to be running after the rolling update applied to a container?

**Comment by AdoHe** [comment]
@dvohra could you provide your kubernetes version? Normally, the old rc would be killed and the the new rc will be renamed to the old rc name in your case.

**Comment by dvohra** [comment]
Have not yet tested with a later version of Kubernetes.  Please close issue. Shall reopen issue if required.
