### ISSUE TITLE
Stop using String() methods generated by protobuf

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#28756]
I don't believe we need them, and they actually make for worse output in many cases.

@wojtek-t fyi

**Comment by wojtek-t** [comment]
Where do we use them now?

**Comment by smarterclayton** [comment]
They get auto generated in generated.pb.go.  I think they're part of one of
the interfaces that gogo-proto expects, but it should be something we can
disable.

**Comment by smarterclayton** [comment]
Fix up but will need to wait until tim's pr lands.
