### ISSUE TITLE
kube-up.sh fails to start InfluxDB cluster monitoring when using non-GCE provider

### ISSUE THREAD

**Issue by ivan4th** [kubernetes/kubernetes#28763]
monitoring-influxdb-grafana-v3-0 pod fails to initialize becuause it has a Persistent Volume Claim for which only a GCE Persistent Volume is provided.
Offending k8s commit:
https://github.com/kubernetes/kubernetes/commit/d00cdf75e879432a93a58e6f92efe7f5bf096da2
Suggested solution: use emptyDir volume for non-GCE setups as it was before the commit above.

**Comment by ivan4th** [comment]
Working on this one.

**Comment by asalkeld** [comment]
#17354 would help, so the other providers could still have an emptyDir PV.

**Comment by ivan4th** [comment]
No longer applicable (self-resolved after the offending commit was reverted).
