### ISSUE TITLE
Does Kubernetes (local Docker method) really work?

### ISSUE THREAD

**Issue by davenso** [kubernetes/kubernetes#28764]
As per the official documentation [here][1] on running Kubernetes locally within a Container -- I have followed all the steps carefully, and I am still getting the message `connection refused` when I type `kubectl get nodes`. 

`docker ps` shows that *api-server* is not running, and `docker logs kubelet` does indeed varify so:

    [kubelet.go:1137] Unable to register 127.0.0.1 with the apiserver: Post http://localhost:8080/api/v1/nodes: dial tcp 127.0.0.1:8080: connection refused.

After a little while, `docker logs kubelet`

    E0711 16:07:06.814735   33792 event.go:202] Unable to write event: 'Post http://localhost:8080/api/v1/namespaces/default/events: dial tcp 127.0.0.1:8080: connection refused' (may retry after sleeping)

Apparently, I am not alone in experiencing this problem. 

  [1]: http://kubernetes.io/docs/getting-started-guides/docker/

**Comment by luxas** [comment]
It does work, but isn't the user-friendliest thing out there, so I would recommend to use [minikube](https://github.com/kubernetes/minikube) instead, which has full support (but is still in alpha).
Thanks for using Kubernetes!
