### ISSUE TITLE
PetSets to query replica numbers to count expected peers

### ISSUE THREAD

**Issue by bogdando** [kubernetes/kubernetes#28761]
It seems the only way for an instance of a PetSet to fetch data about expected peers number is to count  SRV records in DNS. But it may be more straightforward and natural to allow replica count to be directly queried from the downward API http://kubernetes-v1-3.github.io/docs/user-guide/downward-api/

**Comment by pwittrock** [comment]
@bprashanth Can you comment on this?

**Comment by pwittrock** [comment]
cc @pwittrock

**Comment by bprashanth** [comment]
The srv records will actually only tell you how many peers have been created before you. you can get the same information by parsing the output of `strings.Split(os.exec("hostname"), "-")`

I'm fine with adding it to downward api, but every case I prototyped, I also needed the DNS names of my peers. And if I'm going to look that up anyway (well i'm not writing code to look that up, the peer finder does the lookup and just passes a list to me: http://kubernetes.io/docs/user-guide/petset/bootstrapping/#background-1), what information does the count add? 

Now if we had a usecase for knowing the number of peers we are *going* to have, that would be a better argument. @bogdando can you elaborate?

**Comment by bprashanth** [comment]
> Now if we had a usecase for knowing the number of peers we are going to have, that would be a better argument. 

Even for this case, you know the replica count at petset creation time so you can simply define an env var for it yourself. Getting some notification that the replica count changed might be more useful, but doing that by modifying the env var feels clunky.

**Comment by bogdando** [comment]
There is a usecase when one wants only a number of expected peers, no FQDNs. F.e. when doing some quorum related evaluations. Not sure, what should I elaborate?.. Could you clarify the question?

**Comment by erictune** [comment]
How would this work?  Would the peers use this number to calculate the size of a quorum?  If so, wouldn't it be necessary to restart all the pods so that they all agree on the new quorum size?  Seems complex.  Or is there another use for this number?

**Comment by bogdando** [comment]
The main use case it is to omit any DNS dependencies and not using the "peer finder helper script" when bootstrapping clusters http://kubernetes.io/docs/user-guide/petset/bootstrapping/. Not sure if ConfigMaps could handle the case as well as the downward API. The latter seems the way less complex to setup (nothing to setup) and use (just query it!) and looks more user friendly.
