### ISSUE TITLE
ABAC Policy should have operation as input attribute

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#2877]
I should be able to author policies that differentiate between create, get, update, delete, list, watch, proxy, etc.  Right now, policy object is the same for all operations.

**Comment by erictune** [comment]
Okay, I agree we should do this.

We should define a mapping from "Request" to "PolicyVerb" which automatically works on new Kinds without special code.

Does OpenShift already have something for this?  If not, I suggest following mapping of Request to PolicyVerb:
   - GET /api/Ver/Kind/Name :arrow_right:  `get`
   - GET /api/Ver/Kind :arrow_right:  `list`
   - POST or PUT new object :arrow_right: `create`
   - POST or PUT or PATCH existing object :arrow_right: `update`
   - DELETE :arrow_right: `delete`
   - GET /api/Ver/Kind/Name/status :arrow_right: `get`
   - PUT /api/Ver/Kind/Name/status :arrow_right `setStatus`
   - GET /api/Ver/Kind/watch :arrow_right: `watch`
   - PUT /api/Ver/Kind/resize  :arrow_right: `resize`
   -  PUT /api/Ver/Kind/binding  :arrow_right: `setBinding`
   - GET /api/Ver/Kind/Foo  :arrow_right: foo
   - PUT /api/Ver/Kind/Foo  :arrow_right: setFoo

Thoughts?

**Comment by derekwaynecarr** [comment]
I am curious what changed your mind?  Will review what we have in OpenShift to give more detail.

**Comment by deads2k** [comment]
We actually re-use a kubernetes API down here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/handlers.go#L207.  It matches what your mapping would look like pre-subresources and pre-patch.  

I think the only significant different with our thinking is that since it is possible to both read and modify subresources, it might be more natural to consider them distinct resources with get and update operations.  That would keep the verb set relatively tight, but still make it easy to express the idea that someone could be disallowed from updating a `pod`, but allowed to update `pod/status`.

**Comment by liggitt** [comment]
> POST or PUT new object :arrow_right: create
> POST or PUT or PATCH existing object :arrow_right: update

How do we know whether the object exists already or not?

> PUT /api/Ver/Kind/Name/status :arrow_right: setStatus

is `setStatus` combining a subtype with a verb? Would it be better to have the verb be `update` and the type be `Kind/Status`?

**Comment by smarterclayton** [comment]
The kind is "Kind/status".  The verb is still the same.

I have a TODO to enable admission control and others to delineate these cases, although I don't think in policy it's as important right now.  PUT is PUT is PUT.

----- Original Message -----

**Comment by erictune** [comment]
@derekwaynecarr I didn't want to grow the Authorizer interface in ways that would encourage changes that are in incompatible with my company's internal and external authorization systems.  Those are complex, and I needed time to figure out how things would fit together.  I now understand that better, and this change appears to fit in.

**Comment by liggitt** [comment]
verb is in the authorizer interface, RBAC supports it, ABAC is unlikely to receive further development at this point
