### ISSUE TITLE
kube-addon-update.sh does not handle ConfigMap types

### ISSUE THREAD

**Issue by zenly** [kubernetes/kubernetes#28775]
kube-addon-update.sh should handle ConfigMaps, so deployments using the addons mechanism can accept configuration through the same process.

i.e.
https://github.com/zenly/kubernetes/commit/2a589b09637aa3745a7151adf2f1fcce36e8b8ac

**Comment by mikedanese** [comment]
Can you send a PR?

**Comment by zenly** [comment]
Sure: https://github.com/kubernetes/kubernetes/pull/28823
