### ISSUE TITLE
Need a user friendly message when config map is missing

### ISSUE THREAD

**Issue by andreykurilin** [kubernetes/kubernetes#28772]
I tried to create pod(using `kubectl create -f some_file.yaml`) with mounting non-existing config map and it failed to start(expected). `kubectl describe pod some_pod` shows next messages:

> 
> FailedMount     Unable to mount volumes for pod "some_pod_default(9cefb7b2-4762-11e6-9fd3-fa163e0da9df)": timeout expired waiting for volumes to attach/mount for pod "some_pod"/"default". list of unattached/unmounted volumes=[config-volume]
> 
> FailedSync      Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "some_pod"/"default". list of unattached/unmounted volumes=[config-volume]

It is hard to understand the reason of timeout without reading kubelet logs

**Comment by andreykurilin** [comment]
I'm working on fix for this issue.

**Comment by saad-ali** [comment]
https://github.com/kubernetes/kubernetes/issues/27590 should cover this
