### ISSUE TITLE
Ingress did not retry adding forwarding rule after failure

### ISSUE THREAD

**Issue by phutchins** [kubernetes/kubernetes#28784]
## Kube Version:

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"283137936a498aed572ee22af6774b6fb6e9fd94", GitTreeState:"clean", BuildDate:"2016-07-01T19:26:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.3", GitCommit:"882d296a99218da8f6b2a340eb0e81c69e66ecc7", GitTreeState:"clean", BuildDate:"", GoVersion:"", Compiler:"", Platform:""}
```
## Details:
- Cloud Provider: GCP
- OS Distro: Debian GNU/Linux 7 (wheezy)
- Network: As created by kube_up scripts default
- Docker Version: Docker version 1.9.1, build a34a1d5
## Steps to Reproduce:

I added an ingress which failed to add the forwarding rules due to my GCP quota being exceeded. After the quota was increased, I would have expected the rule add to have been retried. I waited about 15-20 minutes and never saw a retry.

I restarted (deleted the pod) the ingress controller which resolved the issue and added the forwarding rule.

This is the describe from my ingress including the failed add after all was well...

```
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type       Reason           Message
  ---------     --------        -----   ----                            -------------   --------   ------           -------
  2d            22m             15347   {loadbalancer-controller }                      Warning    GCE :Quota       googleapi: Error 403: Quota 'FORWARDING_RULES' exceeded. Limit: 15.0, quotaExceeded
  51s           51s             1       {loadbalancer-controller }                      Normal     ADD              storj-prod/bridge-gui
```

Happy to provide any additional information that would be helpful upon request.

I'm aware that my kubectl version is ahead of my servers version... I have 1.3.0 in a separate environment and use the older kubectl bin if needed.

**Comment by nicksardo** [comment]
@phutchins I don't know what the code was for this old version, but I believe the GCE ingress controller should be resyncing all ingresses at a configurable period. Have you seen this with a more recent version?

**Comment by nicksardo** [comment]
/close

Moving to ingress-gce repo: https://github.com/kubernetes/ingress-gce/issues/94
