### ISSUE TITLE
Spurious warning-level events for PetSet

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#28785]
While following the [petset example](http://kubernetes.io/docs/user-guide/petset/):
```console
$ kubectl describe petsets
Name:			web
Namespace:		default
Image(s):		gcr.io/google_containers/nginx-slim:0.7
Selector:		app=nginx
Labels:			app=nginx
Replicas:		2 current / 2 desired
Annotations:		<none>
CreationTimestamp:	Mon, 11 Jul 2016 11:20:05 -0700
Pods Status:		2 Running / 0 Waiting / 0 Succeeded / 0 Failed
No volumes.
Events:
  FirstSeen	LastSeen	Count	From		SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----		-------------	--------	------			-------
  1m		1m		1	{petset }			Warning		FailedCreate		pvc: www-web-0, error: persistentvolumeclaims "www-web-0" not found
  1m		1m		1	{petset }			Normal		SuccessfulCreate	pet: web-0
  1m		1m		1	{petset }			Warning		FailedCreate		pvc: www-web-1, error: persistentvolumeclaims "www-web-1" not found
  33s		33s		1	{petset }			Normal		SuccessfulCreate	pet: web-1
```

Questions:
- Should FailedCreate be a Warning if it typically happens and then later gets automatically resolved?
- Should the petset controller wait for PVC dynamic provisioning before sending a create pods?
- Should the petset controlelr send a FailedCreate event if the failure is expected?

**Comment by erictune** [comment]
@foxish

**Comment by foxish** [comment]
@erictune The link to the petset example appears to not work. I'm unsure where to find the yaml file to create that petset.

**Comment by erictune** [comment]
Updated link.

**Comment by bprashanth** [comment]
Ack, sorry about the warnings. I remember seeing it only after the code freeze deadline. It's from the petset controller.

**Comment by foxish** [comment]
@erictune, The behavior seen above isn't right, and we should not issue a warning event when the initial attempt to get a PVC fails given that the call to provision one may succeed right afterwards. @bprashanth pointed me at [this](https://github.com/kubernetes/kubernetes/blob/f2ddd60eb9e7e9e29f7a105a9a8fa020042e8e52/pkg/controller/petset/pet.go#L250) which is where the code corresponding to the warning lives and it does appear to be a small fix there. 

I have a related question. When do we fire events? Is there a reason we do not fire an event when there is an error in trying to get the PVC, such as in [line 257](https://github.com/kubernetes/kubernetes/blob/f2ddd60eb9e7e9e29f7a105a9a8fa020042e8e52/pkg/controller/petset/pet.go#L257)?

**Comment by bprashanth** [comment]
It's usually informational (eg: image pulling started, image pullling done) or note worthy warnings/errors (eg: failed to start container). A get failing usually indicates a recoverable flake. The error should get logged, and we should retry. If it keeps failing it probably means the apiserver is down and some more critical operation will create the event.
