### ISSUE TITLE
Allow CNI node agents to run in a DaemonSet

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#28787]
Host network pods should be able to be created before the container network exists. Pod syncs for pods on the container network should fail until the container network is configured.

cc @freehan @girishkalele

**Comment by freehan** [comment]
ref: #28654

**Comment by luxas** [comment]
I think this is a thing we should make working before v1.4, so adding the milestone. Complain if you disagree.

Also, does @mikedanese volunteer to make a PR? :)

**Comment by mikedanese** [comment]
Going to make a first pass at this in https://github.com/kubernetes/kubernetes/pull/28178

**Comment by luxas** [comment]
Great!
