### ISSUE TITLE
rkt: Clean up json unmarshal.

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#28804]
As the pod returned by rkt api service already contains the labels, annotations, we don't have to unmarshal the manifest to read them.

**Comment by yifan-gu** [comment]
cc @kubernetes/sig-rktnetes

**Comment by euank** [comment]
Closing as stale, [rktlet](https://github.com/kubernetes-incubator/rktlet/) doens't suffer from this problem in any case, and is the successor to rktnets.

/close
