### ISSUE TITLE
can't have more than one cephfs volume per pod and pod termination delete all files in the cephfs path

### ISSUE THREAD

**Issue by untoreh** [kubernetes/kubernetes#28822]
Defining multiple cephfs volumes in a pod stalls the container creation because of volume attachment time out. 
Also this ends up in data loss on cephfs, the paths specified on the manifest (in the cephfs volume definition ) get cleared up on cephfs leaving an empty dir...

**Comment by msau42** [comment]
@untoreh are you still seeing this issue?

/sig storage
