### ISSUE TITLE
Ingress, SSL + internal IP?

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/kubernetes#28838]
I've got a service that I want to expose only on the internal service IP (which is available through a VPN connection), but I _also_ want the ease of use of an ingress resource, handling SSL termination for me.

It seems that the SSL termination functionality is tightly coupled to ingress functionality, which is only used to expose a service to the outside world (especially on GKE, where – by default – you don't have any control over how the ingress external IP is set-up.
- Does the ingress resource suit this use-case,
- or should service resources be able to handle SSL termination, 
- or should a third resource be introduced to handle this,
- or is this simply not possible, and should I handle SSL termination in these use-cases myself?

**Comment by bprashanth** [comment]
Can you just deploy the nginx ingress controller and not include `hostPort` in the yaml (https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/rc.yaml#L93)? that will give you something that understands ingress, but isn't exposed outside the cluster: https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx

Note that running that on GKE/GCE requires an annotation:  https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx#running-multiple-ingress-controllers

**Comment by tomaszszlek** [comment]
Hi,
I have some related question - I set up Ingress controller but Ingress is starting under on of node - we can't be sure which exactly node will be chosen. 
In order to hook my domain (e.g my.example.com) into ingress I need to know IP of ingress node in advance. At leas internal stable IP would be good.
How can I achieve that ? Is there any way to determine Ingress IP in advance ?

**Comment by bprashanth** [comment]
Front the ingress with a service of type=LoadBalancer @aledbf

**Comment by tomaszszlek** [comment]
It won't work fo private cloud

**Comment by bprashanth** [comment]
On prem you can apply the same formula with type=NodePort. You will need to plug one/all node ips into DNS. In both methods, you get a tcp proxy (cloud-LB/kubeproxy) routing to a http proxy (ingress controller).

**Comment by aledbf** [comment]
> At leas internal stable IP would be good.
> It won't work fo private cloud

To achieve that you can use https://github.com/kubernetes/contrib/tree/master/keepalived-vip
