### ISSUE TITLE
example/cassandra: Volume statement in Dockerfile hides all data

### ISSUE THREAD

**Issue by maklemenz** [kubernetes/kubernetes#28835]
**Situation:**
I deployed a cassandra cluster based on the [provided example](https://github.com/kubernetes/kubernetes/tree/fedc5136586dd1a3698f6ad0c734a4065fa726eb/examples/storage/cassandra), used the DaemonSet and replaced the emptyDir with hostPath.

**Problem:**
After deleting a pod all local data seems to be gone and the new cassandra pod loads its data from the other replicas.
When all replicas are deleted at the same time, all data from this replicaset seems to be gone. The data should still be on the hostPath, but the cassandra pod does not see it.

**Cause:**
There is a volume defined in the [Dockerfile](https://github.com/kubernetes/kubernetes/blob/fedc5136586dd1a3698f6ad0c734a4065fa726eb/examples/storage/cassandra/image/Dockerfile#L57) to the directory `/cassandra_data/data`
The [daemonset](https://github.com/kubernetes/kubernetes/blob/fedc5136586dd1a3698f6ad0c734a4065fa726eb/examples/storage/cassandra/cassandra-daemonset.yaml#L50) mounts the hostPath to `/cassandra_data`
In the running container we now have a volume at `/cassandra_data` and inside of it in the `data` folder we have another volume, **hiding the data directory** of our hostPath volume:

```
$ kubectl exec -ti cassandra-test-0yr4x bash
$ mount
[...]
/dev/vda1 on /cassandra_data type ext4 (rw,relatime,data=ordered)
/dev/vda1 on /cassandra_data/data type ext4 (rw,relatime,data=ordered)
[...]
```

**Comment by chrislovecnm** [comment]
@maklemenz we can either merge yours, or merge this one https://github.com/kubernetes/kubernetes/pull/30577  / what do you think?

**Comment by maklemenz** [comment]
@chrislovecnm  #30577 does more and adds usefull examples, I would like to see that merged.
