### ISSUE TITLE
[kubectl][Feature] Add short option for --namespace option

### ISSUE THREAD

**Issue by felixbuenemann** [kubernetes/kubernetes#28846]
If many namespaces are used in a kubernetes cluster, eg. one per app, typing `kubectl command --namespace=someapp` quickly gets annoying.

It would be great if there was a short option like `kubectl command -n myapp` or `kubectl command -ns myapp` if `-n` is already used elsewhere.

**Comment by bgrant0607** [comment]
@felixbuenemann Please comment on #24078.

Closing this as a dupe.
