### ISSUE TITLE
Fix sub-second resolution issue: Update fluentd to version 0.14

### ISSUE THREAD

**Issue by toidi** [kubernetes/kubernetes#28851]
There is a bug with sub-second portion of timestamps [#21480](https://github.com/kubernetes/kubernetes/issues/21480).

As @a-robinson said it can be resolved with using `0.14` version of `fluentd`.

Nowadays `fluentd` fully released, thus it's possible to use it for `fluentd-es` image.

**Comment by toidi** [comment]
http://www.fluentd.org/blog/fluentd-v0.14.0-has-been-released

**Comment by toidi** [comment]
I made some research and found that kubernetes uses `td-agent` instead of `fluentd`.

The latest release of [td-agent 2.3.2](https://docs.treasuredata.com/articles/td-agent-changelog#20160710-version-v232) includes `fluentd v0.12.26`.

**Comment by toidi** [comment]
I created docker image with `fluentd==0.14`.
And it even works..

But it still sends log records without sub-second part in timestamp.


```
{
    "@timestamp": "2016-07-14T09:56:31+00:00",
    "docker": {
        "container_id": "d75445eda3921d091ff26e9a3ac965609890ad126a2e6a7df67ff016cf487d23"
    },
    "kubernetes": {
        "container_name": "json-log-sender",
        "host": "ip-172-31-16-82.ap-northeast-1.compute.internal",
        "labels": {
            "deployment": "d201607141539",
            "pod-worker-name": "restapi-worker"
        },
        "namespace_name": "default",
        "pod_id": "6ce4895c-4996-11e6-b54b-06288a424c59",
        "pod_name": "restapi-celery-worker-ctl-d201607141539-790pg"
    },
    "log": "\n",
    "stream": "stdout",
    "tag": "kubernetes.var.log.containers.restapi-celery-worker-ctl-d201607141539-790pg_default_json-log-sender-d75445eda3921d091ff26e9a3ac965609890ad126a2e6a7df67ff016cf487d23.log"
}
```

**Comment by toidi** [comment]
Attaching `fluentd-es` container log

[fluend-es-log.txt](https://github.com/kubernetes/kubernetes/files/363430/fluend-es-log.txt)

**Comment by toidi** [comment]
@a-robinson @jimmidyson do you have any idea about that?

**Comment by a-robinson** [comment]
@toidi - sorry for the delay, but I'm not sure without investigating why it isn't including more fine-grained timestamps. The `time_format` in our config should be parsing out the sub-second portion of the docker logs' timestamps. Have you managed to figure anything out since your last comment?

**Comment by toidi** [comment]
No, I've switched to logstash https://github.com/UKHomeOffice/docker-logstash-kubernetes

**Comment by a-robinson** [comment]
Cool, thanks for the pointer!

**Comment by equinox0815** [comment]
FYI: i just successfully tested td-agent3 (fluentd 0.14.11) together with uken/fluent-plugin-elasticsearch#223 and it works as expected. I don't know if it is a good idea to have this running inside a production-ish environment but for now it looks good.
Also it is worth mentioning that due to elastic/elasticsearch#10005 we don't get nanosecond resolution but having milliseconds is already a great improvement.

**Comment by 1ambda** [comment]
I built custom fluentd-es image with fleuntd 0.14+

1. Modify these files under [cluster/addons/fluentd-elasticsearch/fluentd-es-image](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch)

Make sure that setting your docker repo in `Makefile`.

![image](https://user-images.githubusercontent.com/4968473/34384802-e07affd2-eb61-11e7-9ed9-c4a9ec13abf2.png)

2. Build with ruby 2.1.0+

- `bundle install`
- `make build; make push`
