### ISSUE TITLE
kube-proxy conntrack-max flag should scale by machine size

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#28867]
This seems like very low-hanging fruit and hugely impactful.  256K might suffice for 4 or 8 core machines, but it's not enough for 32 core machines.

I heard a couple grumbles from people regarding 1.3 - maybe we should make this a patch for 1.3.1 or 1.3.2.

@matchstick @girishkalele @roberthbailey objections?  I think this can be pretty surgical.

**Comment by roberthbailey** [comment]
I don't see any issues cherry picking a fix for this into the 1.3 branch.
