### ISSUE TITLE
Vagrant install: The connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by lorenzvth7** [kubernetes/kubernetes#28861]
I used [the official guide](http://kubernetes.io/docs/getting-started-guides/vagrant/#setup) to set up Kubernetes with Vagrant on VirtualBox. I have one master and one node.

There are some weird issues after the install.
First of all I started 3 nginx pods like in the tutorial:
`$ ./cluster/kubectl.sh run my-nginx --image=nginx --replicas=3 --port=80`

The pods were running fine. I was able to describe their deployment etc but:
`./cluster/kubectl.sh get rc` gave me nothing back. So I wasn't able to scale the amount of pods to 2. I was able to perform `./cluster/kubectl.sh get pods`.

When I try to perform commands using kubectl (after an ssh) I always get errors like these:

```
$ kubectl get nodes
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

I'm working with vagrant on MAC OSX

**Comment by pwittrock** [comment]
@lorenzvth7 Is there a reason you went with vagrant instead of minikube?  minikube is better supported at this point and should work on Mac

cc @pwittrock
