### ISSUE TITLE
Invalid JSON errors during PATCH are not properly wrapped as API errors

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#28873]
Patching with an invalid JSON input returns a raw JSON error.  We need to wrap it with BadRequest (probably).

```
E0712 22:54:23.340041   39669 errors.go:63] apiserver received an error that is not an unversioned.Status: [pos 190]: json: expect char '"' but got char '1'
```

**Comment by AdoHe** [comment]
@smarterclayton I looked at this error handling again, this [InterpretUpdateError](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/errors/storage/storage.go#L66) will not interpret invalid JSON error, so basically we will call this [errToAPIStatus](https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/errors.go#L35) to convert this error an unversioned.Status object, now the status code is `http.StatusInternalServerError`, should we change this?

**Comment by smarterclayton** [comment]
I think invalid JSON error from the patch parsing code (in rest handler) needs to explicitly set an error type, probably BadRequest, with a message that is appropriate (that's probably getPatchedJS, which needs to return correctly typed errors)
