### ISSUE TITLE
Kubernetes pod dependancies

### ISSUE THREAD

**Issue by Divyaraaga** [kubernetes/kubernetes#28877]
Hi

I have a rancher/kubernetes catalog item which on click of launch button starts 2 services and hence 2 pods/containers start creating containers instantly .
My issue here is I need to pause the creation of container2/Pod2 until the container1/ pod1 is in running state. 
or as bare minimum should pause pod 2 atleast for 20 seconds.
Any inputs are appreciated!

Thanks

**Comment by qq690388648** [comment]
What you mean I thought is workflow, this is not supported in kubernetes ,and I thought these dependancies can be implemented in user-defined codes.

**Comment by Divyaraaga** [comment]
Thanks for your response !
By user defined u mean handle dependancies in the respective Dockerfile s 
?

**Comment by asalkeld** [comment]
@Divyaraaga as far as I know there is no support for this currently.

**Comment by bgrant0607** [comment]
Dupe of #1768 and/or #1704. You may be interested in https://github.com/Mirantis/k8s-AppController
