### ISSUE TITLE
Kubernetes azure support broken on OSX

### ISSUE THREAD

**Issue by Arachnid** [kubernetes/kubernetes#28889]
Trying to bring up a Kubernetes cluster using Azure by following the guide at http://kubernetes.io/docs/getting-started-guides/azure/ fails while generating SSH keys, because the call to `azkube` specifies a user ID, which is not valid inside the docker-machine instance used for Docker support on OSX, resulting in azkube not having permission to write to the filesystem when trying to generate SSH keys.

**Comment by theobolo** [comment]
Hi @Arachnid,

You can deploy a cluster without using the kube-up.sh simply by using that command with docker : 

sudo docker run -it colemickens/azkube:latest /opt/azkube/azkube deploy --subscription-id="{subscription id}" --deployment-name="test-cluster" --location="northeurope" --no-cloud-provider --node-count=2 : it's just an example.

If the kube-up.sh script is not working use that 

Feel free to contact me to have more information : on slack #kubernetes @theobolo

**Comment by xiangpengzhao** [comment]
@Arachnid, does @theobolo 's workaround fix your problem? Is it okay to close this issue?

cc @thockin
