### ISSUE TITLE
Cannot add node in different AWS zone

### ISSUE THREAD

**Issue by cesartl** [kubernetes/kubernetes#28887]
I'm following the [official tutorial](http://kubernetes.io/docs/admin/multiple-zones/) to span k8s nodes in multiple AWS availability zones.

Creating a clusters works fine:

    export KUBE_AWS_ZONE=eu-west-1a
    export NUM_NODES=1
    export MULTIZONE=true
    export MASTER_SIZE=t2.medium
    export NODE_SIZE=t2.medium
    export AWS_S3_REGION=eu-west-1
    export AWS_S3_BUCKET=########
    export INSTANCE_PREFIX=k8s
    export KUBERNETES_PROVIDER=aws
    export KUBERNETES_SKIP_DOWNLOAD=true

This successfully creates a k8s cluster with one node in eu-west-1a.

Now I'm trying to add another node in a different zone:

    export KUBE_USE_EXISTING_MASTER=true
    export MULTIZONE=true
    export KUBERNETES_PROVIDER=aws
    export KUBE_AWS_ZONE=eu-west-1b
    export NUM_NODES=1
    export NODE_SIZE=t2.medium
    export AWS_S3_REGION=eu-west-1
    export KUBE_SUBNET_CIDR=172.20.1.0/24
    export KUBE_MASTER_IP=172.20.0.9
    ./kubernetes/cluster/kube-up.sh

This will setup all the new artefacts in AWS but at the end:

    Sanity checking cluster...
    Attempt 1 to check Docker on node @ 52.208.249.124 ...not working yet
    Attempt 2 to check Docker on node @ 52.208.249.124 ...working
    error: error parsing jsonpath {.contexts[?(@.name == "Using subnet CIDR override: 172.20.1.0/24
    aws_kubernetes")].context.user}, unterminated filter
    
    Kubernetes cluster is running.  The master is running at:
    
      https://#.#.#.#
    
    The user name and password to use is located in /Users/Cesar/.kube/config.
    
    ... calling validate-cluster
    Using subnet CIDR override: 172.20.1.0/24
    Found 2 node(s).
    Using subnet CIDR override: 172.20.1.0/24
    NAME                                        STATUS    AGE
    ip-172-20-0-12.eu-west-1.compute.internal   Ready     9m
    Validate output:
    Using subnet CIDR override: 172.20.1.0/24
    NAME                 STATUS    MESSAGE              ERROR
    scheduler            Healthy   ok                   
    controller-manager   Healthy   ok                   
    etcd-1               Healthy   {"health": "true"}   
    etcd-0               Healthy   {"health": "true"}   
    Cluster validation succeeded

If I do `kubectl get nodes` I will only see my old node. I'm wondering if this is due to the error `error: error parsing jsonpath {.contexts[?(@.name == "Using subnet CIDR override: 172.20.1.0/24`.

When I ssh to the new EC2 instance and look at `/var/log/daemon.log` I can see the following:

    Jul 13 10:47:19 ip-172-20-1-115 kubelet[2538]: I0713 10:47:19.582217    2538 kubelet.go:1169] Attempting to register node ip-172-20-1-115.eu-west-1.compute.internal
    Jul 13 10:47:21 ip-172-20-1-115 kubelet[2538]: I0713 10:47:21.577662    2538 kubelet.go:1172] Unable to register ip-172-20-1-115.eu-west-1.compute.internal with the apiserver: Post ht
    tps://172.20.1.9/api/v1/nodes: dial tcp 172.20.1.9:443: getsockopt: no route to host
    Jul 13 10:47:21 ip-172-20-1-115 kubelet[2538]: E0713 10:47:21.577669    2538 reflector.go:205] pkg/kubelet/kubelet.go:262: Failed to list *api.Service: Get https://172.20.1.9/api/v1/s
    ervices?resourceVersion=0: dial tcp 172.20.1.9:443: getsockopt: no route to host
    Jul 13 10:47:21 ip-172-20-1-115 kubelet[2538]: E0713 10:47:21.577691    2538 reflector.go:205] pkg/kubelet/kubelet.go:281: Failed to list *api.Node: Get https://172.20.1.9/api/v1/node
    s?fieldSelector=metadata.name%3Dip-172-20-1-115.eu-west-1.compute.internal&resourceVersion=0: dial tcp 172.20.1.9:443: getsockopt: no route to host
    Jul 13 10:47:21 ip-172-20-1-115 kubelet[2538]: E0713 10:47:21.577758    2538 reflector.go:205] pkg/kubelet/config/apiserver.go:43: Failed to list *api.Pod: Get https://172.20.1.9/api/
    v1/pods?fieldSelector=spec.nodeName%3Dip-172-20-1-115.eu-west-1.compute.internal&resourceVersion=0: dial tcp 172.20.1.9:443: getsockopt: no route to host
    Jul 13 10:47:23 ip-172-20-1-115 kubelet[2538]: I0713 10:47:23.652105    2538 kubelet.go:2477] skipping pod synchronization - [ConfigureCBR0 requested, but PodCIDR not set. Will not co
    nfigure CBR0 right now]
    Jul 13 10:47:24 ip-172-20-1-115 kubelet[2538]: E0713 10:47:24.577585    2538 reflector.go:205] pkg/kubelet/kubelet.go:262: Failed to list *api.Service: Get https://172.20.1.9/api/v1/s
    ervices?resourceVersion=0: dial tcp 172.20.1.9:443: getsockopt: no route to host
    Jul 13 10:47:24 ip-172-20-1-115 kubelet[2538]: E0713 10:47:24.577585    2538 reflector.go:205] pkg/kubelet/config/apiserver.go:43: Failed to list *api.Pod: Get https://172.20.1.9/api/v1/pods?fieldSelector=spec.nodeName%3Dip-172-20-1-115.eu-west-1.compute.internal&resourceVersion=0: dial tcp 172.20.1.9:443: getsockopt: no route to host
    Jul 13 10:47:24 ip-172-20-1-115 kubelet[2538]: E0713 10:47:24.577641    2538 event.go:207] Unable to write event: 'dial tcp 172.20.1.9:443: getsockopt: no route to host' (may retry after sleeping)
    Jul 13 10:47:24 ip-172-20-1-115 kubelet[2538]: E0713 10:47:24.577677    2538 reflector.go:205] pkg/kubelet/kubelet.go:281: Failed to list *api.Node: Get https://172.20.1.9/api/v1/nodes?fieldSelector=metadata.name%3Dip-172-20-1-115.eu-west-1.compute.internal&resourceVersion=0: dial tcp 172.20.1.9:443: getsockopt: no route to host
    Jul 13 10:47:27 ip-172-20-1-115 kubelet[2538]: E0713 10:47:27.577550    2538 reflector.go:205] pkg/kubelet/config/apiserver.go:43: Failed to list *api.Pod: Get https://172.20.1.9/api/v1/pods?fieldSelector=spec.nodeName%3Dip-172-20-1-115.eu-west-1.compute.internal&resourceVersion=0: dial tcp 172.20.1.9:443: getsockopt: no route to host
    Jul 13 10:47:27 ip-172-20-1-115 kubelet[2538]: E0713 10:47:27.577632    2538 reflector.go:205] pkg/kubelet/kubelet.go:281: Failed to list *api.Node: Get https://172.20.1.9/api/v1/nodes?fieldSelector=metadata.name%3Dip-172-20-1-115.eu-west-1.compute.internal&resourceVersion=0: dial tcp 172.20.1.9:443: getsockopt: no route to host
    Jul 13 10:47:27 ip-172-20-1-115 kubelet[2538]: E0713 10:47:27.577684    2538 reflector.go:205] pkg/kubelet/kubelet.go:262: Failed to list *api.Service: Get https://172.20.1.9/api/v1/services?resourceVersion=0: dial tcp 172.20.1.9:443: getsockopt: no route to host
    Jul 13 10:47:28 ip-172-20-1-115 kubelet[2538]: I0713 10:47:28.578038    2538 kubelet.go:1100] Adding node label from cloud provider: beta.kubernetes.io/instance-type=t2.medium
    Jul 13 10:47:28 ip-172-20-1-115 kubelet[2538]: I0713 10:47:28.578062    2538 kubelet.go:1111] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/zone=eu-west-1b
    Jul 13 10:47:28 ip-172-20-1-115 kubelet[2538]: I0713 10:47:28.578069    2538 kubelet.go:1115] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/region=eu-west-1
    Jul 13 10:47:28 ip-172-20-1-115 kubelet[2538]: I0713 10:47:28.581739    2538 kubelet.go:2884] Recording NodeHasSufficientDisk event message for node ip-172-20-1-115.eu-west-1.compute.internal
    Jul 13 10:47:28 ip-172-20-1-115 kubelet[2538]: I0713 10:47:28.581770    2538 kubelet.go:2884] Recording NodeHasSufficientMemory event message for node ip-172-20-1-115.eu-west-1.compute.internal
                                               
This repeats every 10s
                                                         
It seems that the node is trying to connect to `https://172.20.1.9`, but I believe my master node is running on `172.20.0.9`. Is it getting confused by the different CIDR block for the subnet?

I am doing something wrong?

**Comment by justinsb** [comment]
The instructions say to use `MASTER_INTERNAL_IP`, but it looks like you have specified `KUBE_MASTER_IP`.  Can you please try again using MASTER_INTERNAL_IP?

**Comment by cesartl** [comment]
sorry that was stupid...
After making this change it seems to go a bit further but I'm still not able to add the node.

In the `daemon.log` file I don't see the error I used to see anymore.

Now it reaches a point where it logs:

    Downloading binary release tar (https://s3.amazonaws.com/kubernetes-staging-1a780d2335f92008afb6287d059de6f2/devel/kubernetes-server-linux-amd64.tar.gz)

Then

    Failed to download https://s3.amazonaws.com/kubernetes-staging-1a780d2335f92008afb6287d059de6f2/devel/kubernetes-server-linux-amd64.tar.gz. Retrying. ==

and then

    Warning: Transient problem: timeout Will retry in 10 seconds. 3 retries left.
    Jul 13 15:19:33 ip-172-20-1-152 rc.local[364]: Throwing away 255935115 bytes

it seems to be a completely different problem. Any ideas?

**Comment by cesartl** [comment]
Apologises, after some time the nodes does register itself.
