### ISSUE TITLE
Scheduler cache corruption in case of failed bindings

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#28883]
I've just faced the problem of corrupted cache in scheduler. Basically the problem was the following:
- scheduler tried to bind a pod X
- binding was rejected (in this case because of http didn't reach apiserver due to network overload, but the type of error doesn't really matter)
- then after some time we are scheduling this pod again, but this time we are binding it to a different node
- the binding succeeds

After those operations, schedulercache will be corrupted, because second Assume will be processed incorrectly.

@davidopp @hongchaodeng @xiang90 @kubernetes/sig-scheduling

**Comment by wojtek-t** [comment]
The solution for the problem is basically to remove the "assumed" pod from the cache, before queuing it again for scheduling:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/scheduler.go#L143

**Comment by wojtek-t** [comment]
So probably something like "ForgetPod" method (sibling to RemovePod) should be added to schedulercache.

**Comment by wojtek-t** [comment]
Let me send some PR for it later today.

**Comment by hongchaodeng** [comment]
This fixes #26043.
