### ISSUE TITLE
make tests sometimes doesn't work for some reason

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#28896]
Error message is following:

```
~/go/src/k8s.io/kubernetes$ make test WHAT=pkg/controller/node
Running tests for APIVersion: v1,autoscaling/v1,batch/v1,batch/v2alpha1,extensions/v1beta1,apps/v1alpha1,federation/v1beta1,policy/v1alpha1,rbac.authorization.k8s.io/v1alpha1,certificates/v1alpha1
+++ [0713 16:25:23] Running tests without code coverage
Binary file (standard input) matches
!!! Error in hack/make-rules/test.sh:192
  'return ${rc}' exited with status 1
Call stack:
  1: hack/make-rules/test.sh:192 main(...)
Exiting with status 1
make: *** [test] Error 1
```

I can successfully run (or rather fail) the test using `godep go test`

cc @wojtek-t

**Comment by thockin** [comment]
Sometimes?  As in running it 10 times in a loop fails some N < 10 times?  what is N?

**Comment by thockin** [comment]
I have not been able to repro this.

**Comment by gmarek** [comment]
Sorry for the vague report. I had a bug in #28897 in `nodecontroller.go`, where in line 495 instead of `stateInitial` I had `stateFullSegmentation` - reintroducing the bug causes this problem to reappear, while `godep go test` works fine. I'll keep a copy of this commit if in case it'll change today a lot.
