### ISSUE TITLE
Secret file modifications don't persist since 1.3.0 on GKE

### ISSUE THREAD

**Issue by JorritSalverda** [kubernetes/kubernetes#28898]
In one of our containers we mount ssh keys via a secret, then chmod, chown and rename them in the entrypoint script (see https://github.com/Travix-International/docker-gocd-server/blob/16.6.0/docker-entrypoint.sh). The lines that do this are below.

```
if [ -d "/var/go" ]
then
  chown -R ${USER_NAME}:${GROUP_NAME} /var/go || echo "No write permissions"
fi

if [ -d "/var/go/.ssh" ]
then

  # make sure ssh keys mounted from kubernetes secret have correct permissions
  chmod 400 /var/go/.ssh/* || echo "Could not write permissions for /var/go/.ssh/*"

  # rename ssh keys to deal with kubernetes secret name restrictions
  cd /var/go/.ssh
  for f in *-*
  do
    mv "$f" "${f//-/_}" || echo "No write permissions for /var/go/.ssh"
  done

  ls -latr /var/go/.ssh

fi
```

From the scripts perspective the chown and renames are all happening. However when looking into the container with kubectl exec the files have the original owner and filename. The permissions are not modified in either case.

**scripts view**

```
lrwxrwxrwx 1 go go   17 Jul 13 12:47 id_rsa.pub -> ..data/id-rsa.pub
lrwxrwxrwx 1 go go   13 Jul 13 12:47 id_rsa -> ..data/id-rsa
lrwxrwxrwx 1 go go   13 Jul 13 12:47 config -> ..data/config
lrwxrwxrwx 1 go go   31 Jul 13 12:47 ..data -> ..7987_13_07_12_47_40.585369876
drwxr-xr-x 2 go go  100 Jul 13 12:47 ..7987_13_07_12_47_40.585369876
drwxr-xr-x 3 go go 4096 Jul 13 12:47 ..
drwxrwxrwt 3 go go  140 Jul 13 12:47 .
```

**reality via kubectl exec?**

```
lrwxrwxrwx 1 go   go     13 Jul 13 12:57 config -> ..data/config
drwxr-xr-x 3 go   go   4096 Jul 13 13:03 ..
lrwxrwxrwx 1 root root   17 Jul 13 13:03 id-rsa.pub -> ..data/id-rsa.pub
lrwxrwxrwx 1 root root   13 Jul 13 13:03 id-rsa -> ..data/id-rsa
lrwxrwxrwx 1 root root   31 Jul 13 13:03 ..data -> ..7987_13_07_13_03_52.601401392
drwxr-xr-x 2 root root  100 Jul 13 13:03 ..7987_13_07_13_03_52.601401392
drwxrwxrwt 3 go   go    140 Jul 13 13:03 .
```

The main process in the container runs as a different user using `/bin/su`, perhaps that's related. But it seems that the changes to how secrets are mounted using symlinks is related.

I've downgraded the nodes back to 1.2.5 and again everything works.

**Comment by JorritSalverda** [comment]
Are secrets automatically updated in 1.3? The timestamps in the last directory listing are about 16 minutes later, so it seems kubernetes automatically overwrites the changes I did after mounting the secret.

**Comment by liggitt** [comment]
I thought secret volumes were forced read only. I wouldn't have expected a script in the container to be able to modify the files. @pmorie?

**Comment by pmorie** [comment]
Secret volumes _should_ be readonly -- it's possible that a bug was introduced... i'll spin off an issue.

**Comment by JorritSalverda** [comment]
This works fine for a while already. I think since 1.4 or 1.5.
