### ISSUE TITLE
Unable to build kubernetes running 'make'

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/kubernetes#28890]
After merging https://github.com/kubernetes/kubernetes/pull/25978, I am unable to build kubernetes:

```sh
./hack/build-go.sh
NOTE: ./hack/build-go.sh has been replaced by 'make' or 'make all'

The equivalent of this invocation is: 
    make 


make: *** No rule to make target `/*.go', needed by `_output/bin/deepcopy-gen'.  Stop.
```

Before ``eecbfb1a2808b233a4c7032ce26e260276bffde5``:
```sh
./hack/build-go.sh
Go version: go version go1.6.2 linux/amd64
+++ [0713 07:36:27] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0713 07:36:27] Building go targets for linux/amd64:
    cmd/kube-dns
...
```

Am I something missing?

**Comment by pigmej** [comment]
I have the same problem.

`make clean` does not help. (running `make` directly too)

**Comment by dims** [comment]
@ingvagabund @pigmej - "./build/run.sh make" from the root directory seems to work. Though it is using a docker container to execute the make.

**Comment by ingvagabund** [comment]
@dims thanks for pointing that out. That is so wrong, I don't want to built kubernetes in container.

**Comment by pigmej** [comment]
yeah it works, but it's kinda strange.

**Comment by cdpb** [comment]
```
kubernetes$ ./build/run.sh make
+++ [0713 14:27:38] Verifying Prerequisites....
+++ [0713 14:27:44] Building Docker image kube-build:build-d95f553a94.
+++ [0713 14:27:49] Running build command....
make: *** No targets specified and no makefile found.  Stop.
!!! Error in ./build/../build/common.sh:620
  '"${docker_cmd[@]}" "$@"' exited with status 2
Call stack:
  1: ./build/../build/common.sh:620 kube::build::run_build_command(...)
  2: ./build/run.sh:30 main(...)
Exiting with status 1
```

```
build$ ./run.sh make
./../build/common.sh: Zeile 32: hack/lib/init.sh: Datei oder Verzeichnis nicht gefunden
```


git branch on v1.3.0

**Comment by dims** [comment]
Another work around I used to have the following GOPATH:
`GOPATH=/home/dims/go`

So i created another directory `/home/dims/k8s-go/` and updated my GOPATH:
`GOPATH=/home/dims/go:/home/dims/k8s-go/`

In this new directory created a soft link to vendor directory in kubernetes root:
```
[dims@ubuntu-brix 08:44] ~/k8s-go ⟩ pwd
/home/dims/k8s-go
[dims@ubuntu-brix 08:44] ~/k8s-go ⟩ ls -altr
total 8
drwxr-xr-x 32 dims dims 4096 Jul 13 08:14 ..
lrwxrwxrwx  1 dims dims   28 Jul 13 08:38 src -> /home/dims/kubernetes/vendor
drwxrwxr-x  2 dims dims 4096 Jul 13 08:38 .
```

The following work for me.
```
make clean
make WHAT=cmd/kubectl
```

**Comment by idvoretskyi** [comment]
@dims that sounds like a temporary workaround, not a solid solution.

**Comment by dims** [comment]
@idvoretskyi - my first sentence started with "Another work around" :)

**Comment by dims** [comment]
@idvoretskyi something to get by until @thockin chimes in with his thoughts...

**Comment by idvoretskyi** [comment]
> @idvoretskyi - my first sentence started with "Another work around" :)

@dims I know, but that won't solve the issue completely :)

**Comment by pigmej** [comment]
So I got it working.

clone / symlink k8s sources (top dir) as `some_path/src/k8s.io/kubernetes` and run `make` from that dir. Set GOPATH to it to. Works perfectly then.

**Comment by ingvagabund** [comment]
Looks like it is already there [1]. Though, saying it is highly recommended. Now, it is a must.

[1] https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md#clone-your-fork

**Comment by thockin** [comment]
I thought it was already required to be under a GOPATH somewhere?  If it
was working properly before, then yeah, I probably broke it.  Where do you
think would be the most findable place to document it?

**Comment by ingvagabund** [comment]
@thockin in my CI, I don't clone the kubernetes under src/k8s.io. Jenkins is responsible for that and clones the kubernetes under kubernetes directory in its workspace. This will slight update to have the Jenkins clone the repo under different directory.

**Comment by ingvagabund** [comment]
Anyone new getting familiar with kubernetes will clone the repository (to a random directory). Then see Makefile and just runs ``make`` (or runs ./hack/build-go.sh as so many people have done so far). Nobody will read the docs unless it is necessary. So need for putting kubernetes under src/k8s.io directory makes it a little complicated for newbies (and everyone use to it).

**Comment by pigmej** [comment]
@thockin If it's a must have to have that directory structure then I would recommend to adjust scripts and throw error about incorrect directory structure. Otherwise the errors are a bit strange.

**Comment by thockin** [comment]
well, it *is* Go code, which really does want to be checked out into a
GOPATH.  Let me see what I can do.

**Comment by thockin** [comment]
Ahh, here's what is happening.  It's actually a confluence of recent
changes (all mine) that I did not detect were piling up requirements.

The change to use vendor/ demands that any go tools operate from within the
GOPATH, or else they just refuse to find vendored packages.  All the hack/*
scripts were fixed to chdir into GOPATH.  This was the straw that broke my
back, so I finally set up a proper GOPATH.  Since I was now developing
against a GOPATH, I did not experience the problem described here, and when
I moved the code-gen tools into Makefile, I did not detect that the GOPATH
rule was no longer be patched up automatically.

Sorry about that.

Here are our choices:

a) demand that you always check out kubernetes into a GOPATH (easy for me,
burden on you all, probably "correct" anyway)
b) write yet another script that mucks with GOPATH and then calls the
codegen tools (easy for you all, hacky)

I can whip up a PR for (b), but I'd like feedback on the ideas.

**Comment by pigmej** [comment]
@thockin 

c) leave everything as it is but throw meaningful error when incorrect path is detected.

**Comment by MHBauer** [comment]
I vote for A by way of C.

**Comment by thockin** [comment]
There's an interesting corollary to this.  When we make up a fake GOPATH
for tools to execute it, we ENSURE that there are no external deps being
found in GOPATH.  Is that worth the cost?

**Comment by dims** [comment]
@thockin : if you see my work around in https://github.com/kubernetes/kubernetes/issues/28890#issuecomment-232344319 i added a new directory to my GOPATH in addition to what i already had there. That directory had a soft link to the vendor directory in my git cloned kubernetes directory

**Comment by MHBauer** [comment]
From my limited understanding of the golang ecosystem, anything in vendor should override anything outside of vendor, so I don't think we need an empty GOPATH. Is there a way to test?

**Comment by thockin** [comment]
Please take a look at #28890

**Comment by pigmej** [comment]
@thockin this is #28890 you probably meant #28903 ;)

**Comment by soltysh** [comment]
@thockin any idea why `make clean all` fails: 
```
$ make clean all
+++ [0714 11:52:49] Verifying Prerequisites....
!!! [0714 11:52:49] Build image not built.  Cannot clean via docker build image.
+++ [0714 11:52:49] Removing data container kube-build-data-0bc7d68a56
+++ [0714 11:52:49] Removing _output directory
+++ [0714 11:52:49] Deleting docker image kube-build:build-0bc7d68a56
+++ [0714 11:52:49] Cleaning all other untagged docker images
Go version: go version go1.7rc1 linux/amd64
+++ [0714 11:52:49] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0714 11:52:49] Building go targets for linux/amd64:
    cmd/libs/go2idl/deepcopy-gen
+++ [0714 11:52:51] Placing binaries
make: *** No rule to make target '.make/federation/apis/federation/gofiles.mk.stamp', needed by 'federation/apis/federation/zz_generated.deepcopy.go'.  Stop.
```

Calling `make clean` and `make all` works ok.

**Comment by soupdiver** [comment]
I'm having the same problem when executing `make`. However `make all` works.
Which of both is the intended way to build?

**Comment by bgrant0607** [comment]
See #28903

**Comment by bgrant0607** [comment]
cc @liyouwei

**Comment by thockin** [comment]
What's happening is that there is work that is done outside of any rule to
evaluate and generate dependencies.  when you run `make clean all` the work
is done, then `clean` removes it, then `all` tries to use it, but now it is
gone.

I'll think about how to fix this.  In the mean time, the solution is simply
to run as 2 different rules.
