### ISSUE TITLE
Ubernetes lite in GCE does not allow to change node configuration

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#28894]
Currently, when using flag `KUBE_USE_EXISTING_MASTER=true` in kube-up.sh, we will simple recreate nodes in a new zone, but we will use the same template. This makes it impossible to use different machine specification, e.g. use SSD or bigger machines. This defeats one of the main reasons why we have introduced ubernetes lite in the first place.

AFAIU it works on AWS.

Am I missing something or is it a serious gap in our multi-zone cluster offering in GCE?

@kubernetes/goog-control-plane @quinton-hoole @davidopp @matchstick

**Comment by quinton-hoole** [comment]
@fgrzadkowski For each invocation of kube-up.sh, you can specify a different machine type (as well as a different zone).  So it should do what you want.  If it doesn't, then that's just a bug, that should be fixed.

**Comment by fgrzadkowski** [comment]
@quinton-hoole Current implementation for GCE is just reusing existing template:

```
  if [[ ${KUBE_USE_EXISTING_MASTER:-} == "true" ]]; then
    parse-master-env
    create-nodes
  else
    check-existing
    create-network
    write-cluster-name
    create-autoscaler-config
    create-master
    create-nodes-firewall
    create-nodes-template
    create-nodes
    check-cluster
  fi
```

AFAIU it means there's no way to change machine size or any other parameter except for number of nodes and their names.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#56.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
