### ISSUE TITLE
constant 'eth0' in KUBE-OUTBOUND-NAT chain of nat table from kube-proxy in iptables mode

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#28906]
Using release 1.3.0, with the kube-proxy in iptables mode, I found this chain in the nat table on a worker node:
```
-A KUBE-OUTBOUND-NAT -d 192.168.0.0/16 -o eth0 -j RETURN
-A KUBE-OUTBOUND-NAT -d 100.125.0.0/24 -o eth0 -j RETURN
-A KUBE-OUTBOUND-NAT -j MASQUERADE
```
Here 192.168.0.0/16 is the subnet for pod IPs and 100.125.0.0/24 is the subnet for the hosts.

The problem here is that the host's ethernet interface (yes, it has just one) is not named `eth0`.  So all the packets leaving that node get SNATted, which is bad.

This cluster was built following the instructions at http://kubernetes.io/docs/getting-started-guides/ubuntu-calico/, ammended according to https://github.com/kubernetes/kubernetes.github.io/pull/618 and the network policy controller instructions from https://github.com/projectcalico/calico-containers/blob/master/docs/cni/kubernetes/KubernetesIntegration.md .

**Comment by caseydavenport** [comment]
I think we've traced this to an older version of the Calico getting started guide which set up these NAT rules (see https://github.com/kubernetes/kubernetes/blob/v1.1.8/docs/getting-started-guides/ubuntu-calico.md#nat-on-the-nodes) but doesn't any longer, so not a Kubernetes issue.

**Comment by MikeSpreitzer** [comment]
Actually, this was my fault.  It was in my automation based on an old edition of http://kubernetes.io/docs/getting-started-guides/ubuntu-calico/
