### ISSUE TITLE
All nodes in my cluster marked for deletion by the kube-controller at the same time

### ISSUE THREAD

**Issue by joshm1** [kubernetes/kubernetes#28901]
I'm running a Kubernetes v1.2.0 cluster on AWS.  My master instance is Ubuntu 15.04 (initially provisioned via the `kube-up.sh` script).  I'm only running 4 nodes (also Ubuntu 15.04)

I had an issue today where **all** nodes in my cluster were marked for deletion at the same time, which terminated all pods.  My nodes (all m4.large) were healthy before and after this happened.  5-7 minutes after they were removed in Kubernetes, they all came back.

It's probably worth noting that my master instance is a t2.small, it has been serving me well for months, but I'm noticing now that the CPU credit balance is consistently low (but not zero), so it's likely the instance was slow during this time.  I plan to upgrade the instance, I'm aware using a t2 instance for a master is not ideal, but I still don't think a slow master should result my nodes being deleted.

Here are the relevant logs from `kube-controller-manager.log`.  I don't see any events before this that look relevant.

```
I0713 15:52:24.065055       7 nodecontroller.go:430] NodeController observed a Node deletion: ip-172-20-0-174.ec2.internal
I0713 15:52:30.632460       7 nodecontroller.go:603] Recording Removing Node ip-172-20-0-174.ec2.internal from NodeController event message for node ip-172-20-0-174.ec2.internal
I0713 15:52:36.244664       7 nodecontroller.go:430] NodeController observed a Node deletion: ip-172-20-0-176.ec2.internal
I0713 15:52:36.244730       7 nodecontroller.go:603] Recording Removing Node ip-172-20-0-176.ec2.internal from NodeController event message for node ip-172-20-0-176.ec2.internal
I0713 15:52:36.244758       7 nodecontroller.go:430] NodeController observed a Node deletion: ip-172-20-0-196.ec2.internal
I0713 15:52:36.244763       7 nodecontroller.go:603] Recording Removing Node ip-172-20-0-196.ec2.internal from NodeController event message for node ip-172-20-0-196.ec2.internal
I0713 15:52:36.244773       7 nodecontroller.go:430] NodeController observed a Node deletion: ip-172-20-0-201.ec2.internal
I0713 15:52:36.244778       7 nodecontroller.go:603] Recording Removing Node ip-172-20-0-201.ec2.internal from NodeController event message for node ip-172-20-0-201.ec2.internal
```

A few minutes later all 4 nodes start to come back online:

```
I0713 15:57:30.029724       7 nodecontroller.go:803] Cancelling pod Eviction on Node: ip-172-20-0-174.ec2.internal
I0713 15:57:30.029784       7 nodecontroller.go:415] NodeController observed a new Node: api.Node [redacted for brevity]
I0713 15:57:30.030230       7 nodecontroller.go:603] Recording Registered Node ip-172-20-0-176.ec2.internal in NodeController event message for node ip-172-20-0-176.ec2.internal
I0713 15:57:30.030251       7 nodecontroller.go:803] Cancelling pod Eviction on Node: ip-172-20-0-176.ec2.internal
```

@justinsb

**Comment by bprashanth** [comment]
AFAIK nodecontroller shouldn't try to delete nodes unless they disappear from the cloudprovider api.

**Comment by playqdrew** [comment]
We just experienced this in a production cluster on AWS K8 version 1.2.3.

`W0220 18:15:28.054325       6 request.go:344] Field selector: v1 - serviceaccounts - metadata.name - default: need to check if this is versioned correctly.
W0220 18:15:42.993959       6 request.go:627] Throttling request took 108.919038ms, request: GET:http://127.0.0.1:8080/api/v1/nodes
W0220 18:15:44.367654       6 request.go:627] Throttling request took 127.167999ms, request: GET:http://127.0.0.1:8080/apis/extensions/v1beta1/horizontalpodautoscalers?resourceVersion=0
W0220 18:16:32.105650       6 request.go:627] Throttling request took 176.646936ms, request: GET:http://127.0.0.1:8080/apis/extensions/v1beta1/horizontalpodautoscalers?resourceVersion=0
I0220 18:17:15.449558       6 nodecontroller.go:430] NodeController observed a Node deletion: ip-172-20-0-112.ec2.internal
I0220 18:17:15.456446       6 nodecontroller.go:603] Recording Removing Node ip-172-20-0-112.ec2.internal from NodeController event message for node ip-172-20-0-112.ec2.internal
I0220 18:17:15.462933       6 nodecontroller.go:430] NodeController observed a Node deletion: ip-172-20-0-139.ec2.internal
I0220 18:17:15.462949       6 nodecontroller.go:603] Recording Removing Node ip-172-20-0-139.ec2.internal from NodeController event message for node ip-172-20-0-139.ec2.internal
I0220 18:17:15.462961       6 nodecontroller.go:430] NodeController observed a Node deletion: ip-172-20-0-172.ec2.internal
I0220 18:17:15.462966       6 nodecontroller.go:603] Recording Removing Node ip-172-20-0-172.ec2.internal from NodeController event message for node ip-172-20-0-172.ec2.internal
I0220 18:17:15.462976       6 nodecontroller.go:430] NodeController observed a Node deletion: ip-172-20-0-183.ec2.internal
I0220 18:17:15.462981       6 nodecontroller.go:603] Recording Removing Node ip-172-20-0-183.ec2.internal from NodeController event message for node ip-172-20-0-183.ec2.internal
I0220 18:17:15.462989       6 nodecontroller.go:430] NodeController observed a Node deletion: ip-172-20-0-96.ec2.internal
I0220 18:17:15.462994       6 nodecontroller.go:603] Recording Removing Node ip-172-20-0-96.ec2.internal from NodeController event message for node ip-172-20-0-96.ec2.internal
I0220 18:17:15.469225       6 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-172-20-0-112.ec2.internal", UID:"ip-172-20-0-112.ec2.internal", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RemovingNode' Node ip-172-20-0-112.ec2.internal event: Removing Node ip-172-20-0-112.ec2.internal from NodeController
I0220 18:17:15.526942       6 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-172-20-0-139.ec2.internal", UID:"ip-172-20-0-139.ec2.internal", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RemovingNode' Node ip-172-20-0-139.ec2.internal event: Removing Node ip-172-20-0-139.ec2.internal from NodeController
I0220 18:17:15.526970       6 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-172-20-0-172.ec2.internal", UID:"ip-172-20-0-172.ec2.internal", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RemovingNode' Node ip-172-20-0-172.ec2.internal event: Removing Node ip-172-20-0-172.ec2.internal from NodeController
I0220 18:17:15.526983       6 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-172-20-0-183.ec2.internal", UID:"ip-172-20-0-183.ec2.internal", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RemovingNode' Node ip-172-20-0-183.ec2.internal event: Removing Node ip-172-20-0-183.ec2.internal from NodeController
I0220 18:17:15.526993       6 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-172-20-0-96.ec2.internal", UID:"ip-172-20-0-96.ec2.internal", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RemovingNode' Node ip-172-20-0-96.ec2.internal event: Removing Node ip-172-20-0-96.ec2.internal from NodeController
E0220 18:17:15.690782       6 endpoints_controller.go:398] Error getting endpoints: the server cannot complete the requested operation at this time, try again later (get endpoints sandbox-tg-fingerprint)
I0220 18:17:16.501116       6 routecontroller.go:112] Deleting route kubernetes-prd-10.244.0.0/24 10.244.0.0/24
I0220 18:17:16.505356       6 routecontroller.go:112] Deleting route kubernetes-prd-10.244.1.0/24 10.244.1.0/24
I0220 18:17:16.505377       6 routecontroller.go:112] Deleting route kubernetes-prd-10.244.2.0/24 10.244.2.0/24
I0220 18:17:16.508059       6 routecontroller.go:112] Deleting route kubernetes-prd-10.244.4.0/24 10.244.4.0/24
I0220 18:17:16.508072       6 routecontroller.go:112] Deleting route kubernetes-prd-10.244.5.0/24 10.244.5.0/24
I0220 18:17:18.206669       6 routecontroller.go:117] Deleted route kubernetes-prd-10.244.4.0/24 10.244.4.0/24 after 1.68756276s
I0220 18:17:18.208497       6 routecontroller.go:117] Deleted route kubernetes-prd-10.244.2.0/24 10.244.2.0/24 after 1.7004419s
I0220 18:17:18.208600       6 routecontroller.go:117] Deleted route kubernetes-prd-10.244.0.0/24 10.244.0.0/24 after 1.703262558s
I0220 18:17:18.263383       6 routecontroller.go:117] Deleted route kubernetes-prd-10.244.5.0/24 10.244.5.0/24 after 1.755295614s
I0220 18:17:18.296845       6 routecontroller.go:117] Deleted route kubernetes-prd-10.244.1.0/24 10.244.1.0/24 after 1.791463246s`
