### ISSUE TITLE
Create a CoreOS (fleet) cloudprovider

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#2890]
A fair number of users use CoreOS, which is great. But we get a fair number of questions about it on IRC, since it's somewhat DIY, and the various tutorials have varying degrees of up-to-date-ness.

I'd love to see a CoreOS cloudprovider module that integrated fleet, kube-register, flannel, etc., as in https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_multinode_cluster.md, so that it would just work out of the box.

/cc @kelseyhightower

**Comment by roberthbailey** [comment]
As discussed at the contributor conference last week, CoreOS itself isn't really a cloud provider (it is a much better fit for implementing our to be defined node spec). What we need is a cloud provider that uses CoreOS as the host OS that is covered under continuous integration in e2e tests. The current front-runner appears to be the CoreOS on rackspace effort.

**Comment by bgrant0607** [comment]
The title could be changed to "create a fleet cloudprovider", which, if you read the text, is really what this is about -- CoreOS the full package, not CoreOS the Linux distribution.

In general, our code has dismal organization of cluster setup, network setup, (OS distro-specific) node setup, and runtime cloudprovider APIs.

If this isn't going to happen, we should just close this issue.

**Comment by roberthbailey** [comment]
It could happen if someone wants to take ownership and drive it forward. I've added the help-wanted tag for now (and it's already marked as a p3).

**Comment by AALEKH** [comment]
Hello , I am willing to take ownership of this project as a part of GSOC 2015 can someone please guide me with some starter doc about the project ?

**Comment by bgrant0607** [comment]
Hi, @AALEKH. Are you looking for a GSoC project topic, or a getting-started project? If you haven't already, please take a look at:
https://github.com/GoogleCloudPlatform/kubernetes/wiki/Google-Summer-of-Code-(GSoC)
and
https://github.com/GoogleCloudPlatform/kubernetes/issues/4259#issuecomment-80863733

Unfortunately, it's a bit of an inconvenient time to start on this particular issue. 

We're currently developing/debating requirements for new ports of Kubernetes -- see #5141 and https://github.com/GoogleCloudPlatform/kubernetes/pull/5414#issuecomment-79253588. Quality standards and the maintenance burden are two of the many considerations. I don't think we could take this contribution without a dedicated maintainer.

We're also trying to figure out how to simplify Kubernetes deployment -- see #2303 and #5472.

**Comment by pires** [comment]
+1

**Comment by jfoy** [comment]
We've just developed some automation in-house for deploying Kubernetes on Fleet within Vagrant. Based on that work, we're adapting the existing salt-based [cluster/vagrant](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/cluster/vagrant) implementation into a set of fleet-vagrant scripts, which could become a fleet-vagrant provider. I'll link to a PR here as we have something to show.

**Comment by jfoy** [comment]
This work is on hold for us. I'll post back here when we reactivate it.

**Comment by pires** [comment]
@jfoy any updates? Or any pointers to the work done so far?

**Comment by jfoy** [comment]
@pires I'm afraid not; it's on my list to return to.

The [Rackspace provider](https://github.com/GoogleCloudPlatform/kubernetes/tree/c08f202fb9a7e8c8b8f142d4a8ea9d689c60ead2/cluster/rackspace) is a reasonable starting point. The next steps I would take would be to extract most of its cloud-config units to Fleet, then abstract out master discovery (I suggest the master should be assigned by Fleet and advertised through etcd).

**Comment by erictune** [comment]
CoreOS now has official support for Kubernetes.  Discussion about what to do with existing getting-started guides is in #14205.  Closing this.
