### ISSUE TITLE
Pod UID is not exposed by the downward API volume

### ISSUE THREAD

**Issue by dubstack** [kubernetes/kubernetes#28918]
I am working on introducing pod level cgroups in Kubernetes. And I need to access the pod UID from inside the container. I was looking into the Downward API docs and couldn't find Pod UID being exposed.
I believe we should be exposing the pod UID aswell.
cc @kubernetes/sig-node

**Comment by dims** [comment]
@dubstack there's a discussion on adding a couple of more things over at: https://github.com/kubernetes/kubernetes/pull/27880 fyi

**Comment by dubstack** [comment]
@dims Thanks for pointing that out.

**Comment by xiangpengzhao** [comment]
Seems like Buddha's https://github.com/kubernetes/kubernetes/pull/27880#issuecomment-232519302 didn' get response there. AFAIK Pod UID is still not exposed by the downward API currently. Do we still discuss on this?

cc @smarterclayton @thockin @vishh

**Comment by vishh** [comment]
We do need the UID in the downward API. I'm marking this issue as "help wanted".

**Comment by xiangpengzhao** [comment]
/assign
I'd like to work on this.

**Comment by joan38** [comment]
Hi guys,
Which version of K8S support this?
Cheers

**Comment by joan38** [comment]
I can see from the release diffs that it's not in `1.7.5` but in `1.8.0`.

**Comment by xiangpengzhao** [comment]
@joan38 yeah it's supported from v1.8.0-alpha.2. See https://github.com/kubernetes/kubernetes/commit/0f65b218a07e3a5edda16484604dcf1f76bae793
