### ISSUE TITLE
Why would ever using log.Fatal to exist application?

### ISSUE THREAD

**Issue by minjs** [kubernetes/kubernetes#28919]
This is so confusing. Why you would exist application from a log package.

**Comment by dims** [comment]
@minjs what's the specific problem (line/file) where you find this behavior as undesirable?

**Comment by minjs** [comment]
There are so many places using glog.fatal, for example 
controllermanager.go 
l117.
Anyway, put exist in glog, make people confuse. 

	leaderelection.RunOrDie(leaderelection.LeaderElectionConfig{
		EndpointsMeta: api.ObjectMeta{
			Namespace: "kube-system",
			Name:      "kube-controller-manager",
		},
		Client:        kubeClient,
		Identity:      id,
		EventRecorder: recorder,
		LeaseDuration: s.LeaderElection.LeaseDuration.Duration,
		RenewDeadline: s.LeaderElection.RenewDeadline.Duration,
		RetryPeriod:   s.LeaderElection.RetryPeriod.Duration,
		Callbacks: leaderelection.LeaderCallbacks{
			OnStartedLeading: run,
			OnStoppedLeading: func() {
				**glog.Fatalf("leaderelection lost")**
			},
		},
	})

**Comment by smarterclayton** [comment]
This is done primarily to ensure that all exits involve a log message and a timestamp (as well as the code that exited).
