### ISSUE TITLE
Release to Release update of kubernetes.

### ISSUE THREAD

**Issue by imkin** [kubernetes/kubernetes#28923]
There are so many providers and so many ways to install. But there is no clear way to say how a release to release upgrade impacts my existing cluster. This request is specifically for requesting 
1. guideline for release to release upgrade strategy.
2. release to release upgrade matrix for kubernetes components.
3. known issues with upgrades with the release statements.

**Comment by abourget** [comment]
Reading the announcement for etcd3 in Kubernetes 1.3 left me wondering how I'll migrate or if I need to migrate at all.  I wasn't sure if I needed to do that now, later, or how.

**Comment by justinsb** [comment]
Which announcement for etcd3 in Kubernetes 1.3 @abourget ?  I didn't think 1.3 was tested with etcd3 - could well be wrong though!

**Comment by imkin** [comment]
@justinb For this very specific reason we need a "support matrix" somewhere.
