### ISSUE TITLE
make on Mac breaks with a bad target for older sed

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#28930]
```
make generated_files DBG_MAKEFILE=1
Makefile:17: ***** starting makefile for goal(s) "generated_files"
Makefile:18: ***** Wed Jul 13 21:53:53 EDT 2016
Makefile.generated_files:93: ***** finding all *.go dirs
Makefile.generated_files:160: ***** finding all +k8s: tags
Makefile.generated_files:188: ***** finding all +k8s:deepcopy-gen tags
Makefile.generated_files:296: ***** finding all +k8s:conversion-gen tags
mkdir -p .make/_output/bin;                                        \
	(echo -n "_output/bin/conversion-gen: ";                        \
	 DIRECT=$(go list -e -f '{{.Dir}} {{.Dir}}/*.go' ./cmd/libs/go2idl/conversion-gen);                \
	 INDIRECT=$(go list -e   -f '{{range .Deps}}{{.}}{{"\n"}}{{end}}' ./cmd/libs/go2idl/conversion-gen | grep "^k8s.io/kubernetes" | xargs go list -e -f '{{.Dir}} {{.Dir}}/*.go');  \
	 echo $DIRECT $INDIRECT | sed 's/ / \\\n\t/g';       \
	) | sed "s|$(pwd -P)/||" > .make/_output/bin/conversion-gen.mk.tmp;                    \
	cmp -s .make/_output/bin/conversion-gen.mk.tmp .make/_output/bin/conversion-gen.mk || cat .make/_output/bin/conversion-gen.mk.tmp > .make/_output/bin/conversion-gen.mk && rm -f .make/_output/bin/conversion-gen.mk.tmp
mkdir -p .make/_output/bin;                                        \
	(echo -n "_output/bin/deepcopy-gen: ";                          \
	 DIRECT=$(go list -e -f '{{.Dir}} {{.Dir}}/*.go' ./cmd/libs/go2idl/deepcopy-gen);                  \
	 INDIRECT=$(go list -e   -f '{{range .Deps}}{{.}}{{"\n"}}{{end}}' ./cmd/libs/go2idl/deepcopy-gen | grep "^k8s.io/kubernetes" | xargs go list -e -f '{{.Dir}} {{.Dir}}/*.go');  \
	 echo $DIRECT $INDIRECT | sed 's/ / \\\n\t/g';       \
	) | sed "s|$(pwd -P)/||" > .make/_output/bin/deepcopy-gen.mk.tmp;                    \
	cmp -s .make/_output/bin/deepcopy-gen.mk.tmp .make/_output/bin/deepcopy-gen.mk || cat .make/_output/bin/deepcopy-gen.mk.tmp > .make/_output/bin/deepcopy-gen.mk && rm -f .make/_output/bin/deepcopy-gen.mk.tmp
make: *** No rule to make target `\nt/Users/clayton/projects/go/src/k8s.io/kubernetes/cmd/libs/go2idl/deepcopy-gen/main.go', needed by `_output/bin/deepcopy-gen'.  Stop.
```

I don't know where the `\nt` at the beginning of the target comes from, but probably from assumptions about sed version that are wrong.

I had to update to gnu-sed 4.2.2 to build.

**Comment by smarterclayton** [comment]
Also `paste` ootb on a Mac doesn't work with the rules specified (on el capitan):

```
if [[ -f .make/_output/bin/deepcopy-gen.todo ]]; then                \
	    _output/bin/deepcopy-gen                                               \
	        -i $(cat .make/_output/bin/deepcopy-gen.todo | paste -sd,)  \
	        --bounding-dirs k8s.io/kubernetes                           \
	        -O zz_generated.deepcopy;                                  \
	fi
usage: paste [-s] [-d delimiters] file ...
```

**Comment by smarterclayton** [comment]
`paste -sd, -` does work

**Comment by smarterclayton** [comment]
I take it back - updating sed did not appear to work.

**Comment by Gnouc** [comment]
@smarterclayton most recent OSX version is UNIX certified, a POSIX `paste` requires `-` as file argument when reading input from stdin.

For `sed`, `sed 's/ / \\\n\t/g'` is only guaranteed to work in GNU sed, you need to insert literal newline and tab character there for portability.

**Comment by thockin** [comment]
Can someone with a mac send a patch?  I don't have a mac...

**Comment by smarterclayton** [comment]
It's update `sed` and every `paste` should end in `-` instead of having no
arguments.

**Comment by smarterclayton** [comment]
(user should update sed, make needs changes to paste)

**Comment by Gnouc** [comment]
@smarterclayton I think we should stick to portable way for `sed`, it's too risky for relying on GNUism. If you don't mind, I will make a PR.

**Comment by smarterclayton** [comment]
Sure, thanks

**Comment by Gnouc** [comment]
@smarterclayton Are you sure the `Makefile` worked? I pull the latest from master, then run the same command above, I got:
```
F0714 13:36:50.652387   21108 main.go:76] Error: Failed making a parser: unable to add directory "k8s.io/kubernetes/pkg/apis/batch/v2alpha1": unable to import "k8s.io/kubernetes/pkg/apis/batch/v2alpha1": /home/cuonglm/go/src/k8s.io/kubernetes/pkg/apis/batch/v2alpha1/zz_generated.deepcopy.go:1:1: expected 'package', found 'EOF'
make: *** [Makefile.generated_files:201: gen_deepcopy] Error 255
```

**Comment by smarterclayton** [comment]
Make sure you are in your GOPATH in the correct spot for Kube

On Jul 14, 2016, at 2:47 AM, Cuong Manh Le <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> Are you sure the
Makefile worked? I pull the latest from master, then run the same command
above, I got:

F0714 13:36:50.652387   21108 main.go:76] Error: Failed making a
parser: unable to add directory
"k8s.io/kubernetes/pkg/apis/batch/v2alpha1": unable to import
"k8s.io/kubernetes/pkg/apis/batch/v2alpha1":
/home/cuonglm/go/src/k8s.io/kubernetes/pkg/apis/batch/v2alpha1/zz_generated.deepcopy.go:1:1:
expected 'package', found 'EOF'
make: *** [Makefile.generated_files:201: gen_deepcopy] Error 255

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/28930#issuecomment-232574285>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_p5AsRKDQWBiGIPmZJ0PVAR5OLsWwks5qVdtmgaJpZM4JMBD0>
.

**Comment by thockin** [comment]
If you get the "expected 'package', found 'EOF'" message it is usually
because something somewhere failed, and left an empty .go file.  `make
clean_generated`

**Comment by MHBauer** [comment]
From BSD sed man page:
`     -r	     Same as -E	for compatibility with GNU sed.`

Maybe try that?

**Comment by Gnouc** [comment]
@MHBauer It's not about ERE (`-r` enables it), it's about expanding escape sequences in RHS of search and replace `s///`.
