### ISSUE TITLE
termination-log file writable by root only

### ISSUE THREAD

**Issue by dcolens** [kubernetes/kubernetes#28947]
if an app runs with a different user than root, the termination-log can't be written because:
```
-rw-r--r--    1 root     root             0 Jul 14 08:48 termination-log
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4+3eed1e3", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"not a git tree"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4+coreos.1", GitCommit:"7f80f816ee1a23c26647aee8aecd32f0b21df754", GitTreeState:"clean"}
```

Is there a security requirement to have the termination-log writable by root only ? Is there a way for non-root users to use the termination-log feature ?

**Comment by nhlfr** [comment]
Discussion moved here #31839
I know that this issue is older, but maybe we can close it and discuss all the things in the new issue?

**Comment by dcolens** [comment]
Sure, as long as we work towards fixing it :)
