### ISSUE TITLE
kubectl describe nodes should display free resources for the nodes

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes#28940]
Currently kubectl describe nodes displays two things:-
1: total capacity for the node in terms of cpu and memory
2: Allocated resources for both cpu and memory

What would be nice is to display the amount of free resources remaining on the node based on both cpu requests and memory requests. That would allow implementing  some alarms before the node approaches its limits. Currently we would have to do the math ourselves by subtracting cpu requests from total capacity.

**Comment by krmayankk** [comment]
@davidopp

**Comment by AdoHe** [comment]
SGTM. I think this is easy to do. We can add [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/describe.go#L1669)

**Comment by pwittrock** [comment]
@krmayankk Are you planning on using this pragmatically somewhere?  We really recommend using kubectl describe in this manner.  I would be interested in learning about your use case more.

**Comment by davidopp** [comment]
@pwittrock Can you get all the same info from "kubectl get node -o yaml" as from "kubectl describe node"? I totally agree that the latter is not good to use programatically, but the former would only work as a substitute if it provides all the same info.

**Comment by krmayankk** [comment]
@pwittrock i think you meant programmatically and not pragmatically, please confirm :-). Yes actually i need programmatic access. I think the fix should be both in the api and in the describe option as well. If no one minds, can one of you assign this bug to me and i can try to submit my first Kubernetes PR for this issue ? Lets first discuss how it should be fix before i submit a PR for it .

**Comment by krmayankk** [comment]
@pwittrock just realized i didnt answer your question completely. My usecase was simply stemming out of the fact that for a k8s cluster deployed in vcenter vms, i saw that there was no way to tell if there is enough capacity on the vms. The node description was showing just 2 cpus, but there were a ton of pods scheduled on vm node. So i was confused if there was indeed a bug or how we could tell if the node was indeed running out of capacity. A programmatic access to such a field would help figure out remaining resources easily

**Comment by krmayankk** [comment]
@pwittrock @davidopp  it seems this is already present in 1.3/1.2.4 in both api and describe  as the field Allocatable, although i dont see any difference even through i have one pod running on this node.
Capacity:
 cpu:		48
 memory:	132046156Ki
 pods:		110
Allocatable:
 cpu:		48
 memory:	132046156Ki
 pods:		110
System Info:
 Machine ID:			0b8fbd019df1373ceab720dd00000015
 System UUID:			44454C4C-4700-1043-8044-B7C04F333832
 Boot ID:			6201c8a3-7f01-4fee-93a0-966316178276
 Kernel Version:		2.6.32-573.el6.x86_64
 OS Image:			Unknown
 Operating System:		
 Architecture:			
 Container Runtime Version:	docker://1.7.1
 Kubelet Version:		v1.2.4
 Kube-Proxy Version:		v1.2.4
ExternalID:			abcd.abcd.abcd
Non-terminated Pods:		(1 in total)
  Namespace			Name					CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----					------------	----------	---------------	-------------
  e2e-mayank-kumar		default-2035743991-g17df		250m (0%)	1 (2%)		250Mi (0%)	1Gi (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted. More info: http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  250m (0%)	1 (2%)		250Mi (0%)	1Gi (0%)

**Comment by pwittrock** [comment]
@davidopp No you cannot get the same information from `get` as `describe`.  `describe` manually calculates the usage by aggregating the Pod usage.  It is more heavy weight than `kubectl get`.

**Comment by pwittrock** [comment]
@krmayankk Allocable isn't actually (Capacity - Used), it is (Capacity - (System Reserved + Kube Reserved)).

**Comment by pwittrock** [comment]
@krmayankk `kubectl describe` is manually summing up all of the Pod reservations for the Node.  Adding the fields you suggested to `describe` seems reasonable, but I recommend against using describe programmatically since it isn't meant to be used in this manner, and the output format maybe changed.  I would instead manually calculate the per-node usage in a similar way to how describe does it.

**Comment by davidopp** [comment]
Is there a reason why we can't put this information in "kubectl get node -o yaml"? Then it could be used programatically. @smarterclayton mentioned to me the other day that he has seen operators using the output of "kubectl describe node" programatically also, to analyze resource usage.

**Comment by pwittrock** [comment]
@davidopp Do we need this to be calculated on the fly, or can we read it from a periodically updated source?  I think the best way to export this would be to update the node code to export this to the stored node object.

@dchen1107 Thoughts on having the node export its usage so it is available to `kubectl get node`?

**Comment by pwittrock** [comment]
If this needs to be calculated on the fly, perhaps it is better suited to writing a tool to calculate it.

**Comment by smarterclayton** [comment]
I kind of prefer this being something easily gathered and calculated than
built in to the API, to start.  In the long run, yes, it may make sense to
merge the data from multiple sources in the API server (like the proposed
spec and status), but we've tried to be much "dumber" for now.

**Comment by krmayankk** [comment]
@pwittrock 

> 
@krmayankk Allocatable isn't actually (Capacity - Used), it is (Capacity - (System Reserved + Kube Reserved)).`

Thats what we need Allocatable, because we want to know the actual free resources remaining on the node, which means not including system reserved  or did you mean the opposite ?

**Comment by krmayankk** [comment]
@pwittrock any update on this ? Can you confirm what you meant ? I needed  (Capacity - (System Reserved + Kube Reserved)).`, not sure why would someone need Capacity -used, they would always need the actual free which means actual allocatable ?

**Comment by warden** [comment]
I'm comparing the output of: ` kubectl describe node ` where it displays:
```
Allocated resources:
  (Total limits may be over 100%, i.e., overcommitted. More info: http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  3450m (86%)	6050m (151%)	5801Mi (41%)	8768Mi (62%)
```

with the output of `kubectl get node <node> -o yaml` where it displays some information that I'm not sure how is related to the former ones:
```
  allocatable:
    cpu: "4"
    memory: 14367352Ki
    pods: "110"
  capacity:
    cpu: "4"
    memory: 14367352Ki
    pods: "110"
```

What I am interested in is to check cluster capacity for the given range of nodes, e.g. show CPU/MEM percentage use for all nodes with label X - with `kubectl`.

**Comment by pwittrock** [comment]
@krmayankk :

> Can you confirm what you meant ? I needed (Capacity - (System Reserved + Kube Reserved)).`, not sure why would someone need Capacity -used, they would always need the actual free which means actual allocatable ?

Reserved = Overhead for running the node processes

System Reserved = Resources reserved by the system daemons and such
Kube Reserved = Resources for running the kubelet process itself

Reserved does not mean resources allocated to Pods

What you really want is: (Allocatable - Allocated), which is what kubectl describe calculates.

Adding this to kubectl describe sounds good.  Making this more accessible programmatically (instead of parsing from the describe output) needs to evaluated separately.

**Comment by pwittrock** [comment]
cc @timstclair Tim can you verify the statements I made about Reserved vs Allocated?

**Comment by timstclair** [comment]
Yes that's correct. More details [here](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/node-allocatable.md).  ( @pwittrock that information should be upgraded from a proposal to real documentation - where is the best place to put it?)

**Comment by pwittrock** [comment]
How about here:

http://kubernetes.io/docs/admin/node/

**Comment by krmayankk** [comment]
@pwittrock  @timstclair thanks for the pointers.
Questions:-

- Is [this](https://github.com/kubernetes/kubernetes/blob/release-1.3/docs/proposals/node-allocatable.md)  still a proposal or has this been implemented ?
-  The proposal mentions the following
[Allocatable] = [Node Capacity] - [Kube-Reserved] - [System-Reserved]

Also describe node already has Allocatable field. See below:-
```
Capacity:
 cpu:       48
 memory:    132046156Ki
 pods:      110
Allocatable:
 cpu:       48
 memory:    132046156Ki
 pods:      110
```
Is the Allocatable as implemented in 1.3 the same as in the proposal or its just a placeholder  since its value i see is always same as capacity. If its not correct, can i go ahead and start figuring out how to fix it or is someone already working on fixing it ?

**Comment by timstclair** [comment]
> Is this still a proposal or has this been implemented ?

It was implemented in v1.2. As mentioned above, it should be moved out of proposals to real documentation.

> Is the Allocatable as implemented in 1.3 the same as in the proposal or its just a placeholder since its value i see is always same as capacity.

Yes, it should be fully implemented according to the spec in the proposal. The `SystemReserved` and `KubeReserved` parameters are set by Kubelet flags on startup, and are not set by default. In your case, they are probably not set, so it is expected that `Allocatable` would always be the same as `Capacity`.

**Comment by bgrant0607** [comment]
The Kubelet needs to compute total requested resources for admission control. There's no reason why it couldn't report that back as part of node status. The values would only change upon scheduling and eviction events.

**Comment by timstclair** [comment]
If we ever do something like overcommit, reporting a sum of requested resources could be problematic. Although, maybe it would still be informative to see that the node is over committed. Reporting by QoS bucket is another option.

**Comment by krmayankk** [comment]
@timstclair  hmm so if Allocatable is same as proposal which is basically [Allocatable] = [Node Capacity] - [Kube-Reserved] - [System-Reserved], then isnt Allocatable ,the actual free resources on the system, in that case, this issue is no longer an issue, right Am i missing something ?

On a GCE CLUster, i still see Allocatable same as Capacity, are the reserved flags also not set on the GCe cluster which i installed using the kube-up scripts ?

```
mayankkuma-ltm3:~ mayank.kumar$ kubectl describe nodes kubernetes-master 
Name:			kubernetes-master
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/instance-type=n1-standard-1
			beta.kubernetes.io/os=linux
			failure-domain.beta.kubernetes.io/region=us-central1
			failure-domain.beta.kubernetes.io/zone=us-central1-b
			kubernetes.io/hostname=kubernetes-master
Taints:			<none>
CreationTimestamp:	Thu, 07 Jul 2016 23:34:19 -0700
Phase:			
Conditions:
  Type			Status	LastHeartbeatTime			LastTransitionTime			Reason				Message
  ----			------	-----------------			------------------			------				-------
  NetworkUnavailable 	False 	Mon, 01 Jan 0001 00:00:00 +0000 	Thu, 07 Jul 2016 23:34:45 -0700 	RouteCreated 			RouteController created a route
  OutOfDisk 		False 	Tue, 02 Aug 2016 16:55:38 -0700 	Thu, 07 Jul 2016 23:34:19 -0700 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  MemoryPressure 	False 	Tue, 02 Aug 2016 16:55:38 -0700 	Thu, 07 Jul 2016 23:34:19 -0700 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  Ready 		True 	Tue, 02 Aug 2016 16:55:38 -0700 	Thu, 07 Jul 2016 23:34:19 -0700 	KubeletReady 			kubelet is posting ready status
Addresses:		10.128.0.2,23.236.50.112
Capacity:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					1
 memory:				3787416Ki
 pods:					110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					1
 memory:				3787416Ki
 pods:					110
System Info:
 Machine ID:			50865bba165f92cdc79a5f47577f4923
 System UUID:			001D7F83-20F8-6B40-BB1B-074BACA38C76
 Boot ID:			7b73beee-6156-4c6e-9544-81d34546bee6
 Kernel Version:		4.4.4+
 OS Image:			Google Container-VM Image
 Operating System:		linux
 Architecture:			amd64
 Container Runtime Version:	docker://1.11.2
 Kubelet Version:		v1.3.0
 Kube-Proxy Version:		v1.3.0
PodCIDR:			10.244.0.0/24
ExternalID:			6800745304352290790
Non-terminated Pods:		(9 in total)
  Namespace			Name							CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----							------------	----------	---------------	-------------
  kube-system			etcd-server-events-kubernetes-master			100m (10%)	0 (0%)		0 (0%)		0 (0%)
  kube-system			etcd-server-kubernetes-master				200m (20%)	0 (0%)		0 (0%)		0 (0%)
  kube-system			fluentd-cloud-logging-kubernetes-master			80m (8%)	0 (0%)		200Mi (5%)	200Mi (5%)
  kube-system			kube-addon-manager-kubernetes-master			5m (0%)		0 (0%)		50Mi (1%)	0 (0%)
  kube-system			kube-apiserver-kubernetes-master			250m (25%)	0 (0%)		0 (0%)		0 (0%)
  kube-system			kube-controller-manager-kubernetes-master		200m (20%)	0 (0%)		0 (0%)		0 (0%)
  kube-system			kube-scheduler-kubernetes-master			100m (10%)	0 (0%)		0 (0%)		0 (0%)
  kube-system			l7-lb-controller-v0.7.0-kubernetes-master		10m (1%)	100m (10%)	50Mi (1%)	100Mi (2%)
  kube-system			node-problem-detector-v0.1-bdrmh			20m (2%)	200m (20%)	20Mi (0%)	100Mi (2%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted. More info: http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  965m (96%)	300m (30%)	320Mi (8%)	400Mi (10%)
No events.
```

**Comment by krmayankk** [comment]
@timstclair my questions is already answered my @pwittrock 

> @krmayankk Allocable isn't actually (Capacity - Used), it is (Capacity - (System Reserved + Kube Reserved)).

now the only remaining thing is if everyone agrees i can go ahead and add an extra field in describe to show the actual allocatable resource remaining (capacity - used).

**Comment by mdshuai** [comment]
@krmayankk What Allocatable pods equal to ? For --system-reserved and --kube-reserved only support cpu and memory.
