### ISSUE TITLE
Make sure we support multiple CAs for client TLS auth

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubernetes#2895]
When we plumb in verification of client certs against a CA, we should make sure we support a list of CAs to verify against instead of a single CA.  This will ensure that we can rotate the CA smoothly.  This is feedback based on some internal review of our thinking here.

cc: @liggitt

**Comment by zhouhaibing089** [comment]
is this already true for multiple CA support?

**Comment by zhouhaibing089** [comment]
> the referenced client CA file can contain multiple CA certs

I assume it is also true on which is specified on kubeconfig file.

**Comment by liggitt** [comment]
yes, both are parsed into cert pools

**Comment by liggitt** [comment]
`--client-ca-file` supports a cert bundle
