### ISSUE TITLE
Unable to build kubernetes running 'make'

### ISSUE THREAD

**Issue by liyouwei** [kubernetes/kubernetes#28956]
I try :
git clone https://github.com/kubernetes/kubernetes.git
make release

but I get a error:
make: *** No rule to make target `/*.go', needed by `_output/bin/deepcopy-gen'.  Stop.

just like [https://github.com/kubernetes/kubernetes/issues/28890](#28890)
[https://github.com/kubernetes/kubernetes/issues/28890](url)

I try :
"./build/run.sh make" from the root directory

but also get a error :

root@iZ99aemsv31Z:~/kubernetes# ./build/run.sh make
+++ [0714 21:15:07] Verifying Prerequisites....
+++ [0714 21:15:14] Building Docker image kube-build:build-13dc23bfbf
+++ [0714 21:15:24] Running build command....
+++ [0714 21:15:24] Creating data container kube-build-data-13dc23bfbf
make: *** No rule to make target '/*.go', needed by '_output/bin/deepcopy-gen'.  Stop.
!!! Error in ./build/../build/common.sh:626
  '"${docker_cmd[@]}" "$@"' exited with status 2
Call stack:
  1: ./build/../build/common.sh:626 kube::build::run_build_command(...)
  2: ./build/run.sh:30 main(...)
Exiting with status 1
root@iZ99aemsv31Z:~/kubernetes#

Am I something missing?

( I am a noob,sorry

**Comment by liyouwei** [comment]
sorry .
link is [#28890](https://github.com/kubernetes/kubernetes/issues/28890)

**Comment by bgrant0607** [comment]
Yes, this is a dupe.
