### ISSUE TITLE
Sticky IPs for StatefulSet

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#28969]
Most of the databases I (https://github.com/kubernetes/kubernetes/tree/master/test/e2e/testing-manifests/petset) and others (https://github.com/kubernetes/kubernetes/issues/28718#issuecomment-231498420) have prototyped seem to handle DNS properly, but there are murmurs that some do not (https://github.com/kubernetes/kubernetes/issues/23828#issuecomment-232565460), and dont' have plans to do so (https://github.com/kubernetes/kubernetes/issues/28718#issuecomment-231500405). 

I'd still vote for defering any implementation till we have the end to end models fleshed out. One might imagine that databases understand the importance of DNS ttl.

**Comment by chrislovecnm** [comment]
I am checking to see if Cassandra can run on DNS fully.  It works for lookup of seeds, but I am seeing that IP Addresses gets bound to a token range.

**Comment by chrislovecnm** [comment]
I have confirmed that Cassandra does need this.  The Datastax team has toyed with the idea of using DNS, but at this time it is not support to use pure DNS with Cassandra.

**Comment by bprashanth** [comment]
Great! do you have a bug / doc for context

**Comment by chrislovecnm** [comment]
@bprashanth nope email from Datastax folks.  They asked me to file a Jira if I wanted to recommend a change.

**Comment by zefciu** [comment]
I have an idea to implement this feature in calico-containers. I believe that a thing like sticky IPs is not something k8s is responsible for. I still however need a confirmation that this is a requirement for galera to get a blessing for this feature.

**Comment by chrislovecnm** [comment]
@zefciu with calico would this be able to work with internal IPs / DNS that PetSet uses? We need a pet to have a sticky IP address. Also I understand using calico, but this may want to be self contained in k8s.

**Comment by chrislovecnm** [comment]
To add more color stick IP address that is in the internal private subnet the cluster and minions use. This is not a sticky public ip.

**Comment by zefciu** [comment]
The solution is to use annotations, that sent by CNI would make calico either use dynamic or static IPs. I don't know how can we solve the static IP logic in k8s itself if its outsourcing all the job of setting up network interfaces to plugins.

**Comment by bprashanth** [comment]
The way I would *like* to solve it is by defining a staitc-ip-subnet (just like podCIDR assigned to nodes), from which we'd draw these limited ips and assign them to pods. If a pod with the limited edition ip dies, we reprogram the routes so traffic flows to whichever node it lands, just like we setup routes today to route podCIDR to specific nodes. 

The easier way to solve static ip is through a Service vip, but I don't like that for a couple of reasons (occupies iptables space, requires Svc per pod, wont work cross kube-cluster).

**Comment by zefciu** [comment]
@bprashanth: and how would your solution work with plugins? Would it simply sent this desired IP to the plugin, or will it take some of the plugin's responsibilities?

**Comment by bprashanth** [comment]
network plugins are responsible for allocating ips from a given range today, not between nodes. This range is the pod cidr. Something assigns podCIDRs and setups up routing (whatever that may be, it isn't a plugin yet. It could be CP specific route controller or something like flannel). The plugin will only be responsible for eg: creating a veth with the allocated ip and shoving in the netns. IPAM itself is a plugin within the CNI plugin.

**Comment by magicwang-cn** [comment]
init-containers also shares the same network with the whole pod, so why not  get the sticky ips in the init-containers? But this way, we must modify the petset controller(`should not create the pet one by one`)

**Comment by slaskawi** [comment]
As for JBoss projects based on [JGroups](http://jgroups.org/) (like [Infinispan](http://infinispan.org/) for example), we probably need to write a new discovery protocol based on DNS (I proposed it on Infinispan dev mailing list and waiting for a response). Currently some of us use KUBE_PING (which queries Kubernetes API and collects containers) but trusting DNS would probably be a much better option.

However we (the Infinispan Team) would be very interested in exposing PetSets to the outside world. Our Hot Rod client can take the advantage of topology information and optimize queries. Having a public Sticky IPs (or anything that let's client decide to which Pod the request should be forwarded) would be very important for us.

**Comment by chrislovecnm** [comment]
@thockin this is the one I meant to comment on. Who is setting the priority of this one? Would a proposal be a good start?

**Comment by thockin** [comment]
A proposal is always a good start

**Comment by krmayankk** [comment]
@chrislovecnm are you writing this proposal ?

**Comment by chrislovecnm** [comment]
@krmayankk not had any time ... And frankly found a work around ish for Cassandra

**Comment by braedon** [comment]
Hi @chrislovecnm, we've having problems running Cassandra in stateful sets due to this - while we're waiting for a solution, could you share your workaround? Thanks!

**Comment by bbeaudreault** [comment]
We are also interested in this and have 2 reasons:

1) we run HDFS and ZK, both are notoriously bad about re-resolving DNS.

2) More of a bug: due to docker's method of giving out IP addresses (lowest ip first) we sometimes see issues where, if 2 pods restart around the same time one may inherit the IP address of the other. In this scenario, until the DNS TTL has expired its possible for wires to get crossed such that a client connecting to these pods may connect to the wrong pod. This is not specific to statefulsets -- the ip could be reused by a different statefulset's pod, or any other pod. However, since statefulsets are billed as being for stateful services like databases it becomes much more critical. Therefore having static ip's would be great for statefulset pods.

cc @PaulFurtado

**Comment by chrislovecnm** [comment]
> we run HDFS and ZK, both are notoriously bad about re-resolving DNS. 

^ that is a Java DNS issue that maybe can be addressed by setting the DNS ttl properly.  And by getting openjdk or the tool to fix it.  That is a problem that should be dealt with external to this.

There are some apps that just do not do well without static IP addresses, unfortunately.  But java is a tad notorious.

**Comment by chrislovecnm** [comment]
@braedon what is the problem with C*?  Cassandra should launch properly.  I do need to update the C* example :(

**Comment by chrislovecnm** [comment]
@braedon I am on slack a lot, you can ping me there as well.

**Comment by chrislovecnm** [comment]
An update on Cassandra.  I believe that https://github.com/kubernetes/kubernetes/issues/28969#issuecomment-233165307 is no longer the case.  Gossip will complain about IP changes, but it will work itself out eventually.

**Comment by jordanwilson230** [comment]
>  its possible for wires to get crossed such that a client connecting to these pods may connect to the wrong pod. This is not specific to statefulsets -- the ip could be reused by a different statefulset's pod, or any other pod.
> 
I agree, and I'm not quite sure I understand how this is now no longer an issue, unless I missed something in the conversation. A recent experience while deploying a C* statefulset to my local Minikube environment  echos the concerns raised by @bbeaudreault above.  When deploying to a subnet shared by multiple namespaces (i.e., staging and production), Docker's sequential IP assignment (coupled with Cassandra's method of binding IP addresses to token ranges) can cause a cascading clustering effect between all C* clusters, introspective of namespace. 

An example: staging/cassandra-3 is scaled down while production/cassandra-4 is being brought up. Preprod/cassandra-4 is given the now released staging node's IP.  At this point, preproduction/cassandra-4 has become both a member of the preprod cluster and the staging cluster (so long as the staging cluster continues to probe for it's lost Cassandra node, the new preprod node will respond). 

This is what I have seen while testing, but I am still new to Kubernetes, so please correct my understanding if I am missing something here.  I appreciate your insight @chrislovecnm .

**Comment by artooro** [comment]
I was able to resolve most of my issues by making the Datastax Opscenter container use the DNS name of the headless service in front of the cassandra nodes instead of by IP.

The cassandra nodes still use a startup script to resolve the IP of opscenter, and of the seed node. This is still problematic as if the opscenter POD restarts it gets a new IP and all the nodes no longer know how to get to it.

**Comment by sander-su** [comment]
What is the status of this issue?
We want to run kafka / zookeeper on k8s and zookeeper client (3.4.x, which kafka uses) only does a dns lookup on startup.

**Comment by kimocode** [comment]
Looking for an answer here as well. Is this on the roadmap?

**Comment by sander-su** [comment]
And to get on the solution side. It would be great if it would be possible to assign a service ip to each pod. So the service would get another option of handing out a cluster ip per pod. 

Can someone comment on why this has not been chosen for Statefulsets in the first place? There is a reason why services offer cluster ips.

**Comment by sander-su** [comment]
Just saw the 1.9 release which brings us a nice fix:

> StatefulSet controller now creates a label for each Pod in a StatefulSet. The label is statefulset.kubernetes.io/pod-name, where pod-name = the name of the Pod. This allows users to create a Service per Pod to expose a connection to individual Pods. (#55329, @kow3ns)

Could be nicer with automatic creation of the static ips but since we are not going to scale zookeeper this solves our issues by the creation of 3 services.

**Comment by artooro** [comment]
Creating a service per POD still only works if you use the proxy IP. A headless service will not resolve until the POD is running, which can cause race conditions.

**Comment by sander-su** [comment]
That's what I meant. Create 3 separate services with cluster vips. 
The headless service will have another fqdn and thus will not be used. So no race condition.

**Comment by jordanwilson230** [comment]
@artooro Using the publishNotReadyAddresses could solve the race conditions for statefulsets, but after testing both that and the current annotation (service.alpha.kubernetes.io/tolerate-unready-endpoints) which is depreciating (...I was just grasping at this point) seem to have no affect whatsoever.  Has anyone else had success with either of those fields? For reference, the merged PR #49061 for publishNitReadyAdresses is here:  https://github.com/kubernetes/kubernetes/pull/49061

**Comment by psycotica0-shopify** [comment]
We've been using a service with a static Cluster IP for ZK for a while now.
`service.alpha.kubernetes.io/tolerate-unready-endpoints` seems to have worked for us in that regard.

The only bad part is having to produce the services ourselves / keep them in sync.

**Comment by kimocode** [comment]
In the cases where services are created manually for each pod, which selectors do you guys use? Is there a way to select on pod name pre v1.9 ?

**Comment by kimocode** [comment]
Going to try the workaround outlined here: https://github.com/kubernetes/kubernetes/issues/44103#issuecomment-326851272

**Comment by psycotica0-shopify** [comment]
That could work.
We use a controller that watches for new pods to be created and then labels them.
Excited for it to become unneeded in 1.9

**Comment by anuraaga** [comment]
I ran into this issue when starting up redis cluster, which only supports IP addresses in its data model. The workaround of using a service per pod to have a sticky service IP works ok, but it seems quite hacky, considering that the default service IP address space is pretty small, probably assuming that there are supposed to be a small number of services relative to the number of pods. Is this the right solution going forward as opposed to implementing sticky IPs for pods in a statefulset?

**Comment by kimocode** [comment]
Sticky IPs per Pod for StatefulSets would also be useful for the case where ports are being opened dynamically on the Pod (like in the case for many media RTP streams). Mapping a service to a Pod for all possible port ranges definitely feels hacky.

**Comment by thockin** [comment]
@kow3ns FYI ICYMI

**Comment by agolomoodysaada** [comment]
Redis and Zookeeper are two use-cases for us where this would remove a huge amount of work.
Is anybody working on this?

**Comment by aaronmmanzano** [comment]
> Facing this exact problem with Cassandra myself
Same with me in attempting to setup a Cassandra cluster. Perhaps a StatefulSet could reserve a subnet of IPs from the cluster IP pool and IPs could be assigned in order the same way pods are numbered as they spin up.

**Comment by Arqu** [comment]
Fighting the same issue setting up a Scylla cluster. The only "stable" solution for now is to literally set everything in stone with static IPs, node selectors and pod labels. And this is only valid until a node gets decommissioned than you have to reconfigure everything which completely beats the purpose of orchestration. Sticky IPs would probably solve one of the last few pain points of running a distributed DB on kubernetes.

**Comment by fmoraes74** [comment]
It would be nice to know whether this will ever be implemented. Redis is a nightmare to run without some sticky IPs.

**Comment by brouberol** [comment]
Hi there,

I managed to reliably deploy a Cassandra cluster with kubernetes, in a setup using:
- local volumes
- pod anti affinity to only deploy one pod per node
- host network

The way that works is by defining a StatefulSet for cassandra, and 4 different headless services (one per seed node, used for cluster discovery, and one used by the clients to talk to the cluster).

The StatefulSet is defined as such:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  ...
spec:
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
     ...
    template:
      metadata:
        labels:
          app: cassandra
          cluster: cassandra-test
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      ...
      containers:
      - name: cassandra
        ...
```

The services are defined as such (with a default value for `$.Values.cluster.seedSize` of 3)

```yaml
apiVersion: v1
kind: Service
metadata:
  name: cassandra-test
  ...
spec:
  clusterIP: None
  ports:
    ...
  selector:
    app: cassandra
    cluster: cassandra-test
---

{{- $iter_until := $.Values.cluster.seedSize | int -}}
{{ range $i := until $iter_until }}
apiVersion: v1
kind: Service
metadata:
  name: cassandra-test-seed-{{ $i }}
  ...
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  ports:
  ...
  selector:
    app: cassandra
    cluster: cassandra-test
    seed: {{ $i | quote }}
---

{{- end }}
```

The `cassandra.yaml` configuration file points to the seed nodes by using their service name:

```yaml
{{- $iter_until := $.Values.cluster.seedSize | int -}}
{{- $lastSeedId := sub $.Values.cluster.seedSize 1 | int -}}}
seed_provider:
- class_name: org.apache.cassandra.locator.SimpleSeedProvider
  parameters:
  - seeds: {{ range $i := until $iter_until }}cassandra-test-seed-{{ $i }}{{- if ne $i $lastSeedId -}},{{- end -}}{{- end }}
```
which renders into
```yaml
seed_provider:
- class_name: org.apache.cassandra.locator.SimpleSeedProvider
  parameters:
  - seeds: cassandra-test-seed-0,cassandra-test-seed-1,cassandra-test-seed-2
```

These seed node service are annotated with `service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"`, meaning that they can be resolved even if the underlying pods are not in a `Ready` state. I added this to allow the first seed node to reference itself at bootstrap, before having fully started.

The cluster bootstrap works as follows:

- `cassandra-test-0` starts. During the boot phase. I tries to contact the seed node services `cassandra-test-seed-{0,1,2}`. `cassandra-test-seed-0` (aka itself) responds, thanks to the `tolerate-unready-endpoints` annotation, and the bootstrap phase proceeds.
- `cassandra-test-1` starts. During the boot phase. I tries to contact the seed node services `cassandra-test-seed-{0,1,2}`. `cassandra-test-seed-{0,1}` respond, and the bootstrap phase proceeds.
- `cassandra-test-2` starts. During the boot phase. I tries to contact the seed node services `cassandra-test-seed-{0,1,2}`. `cassandra-test-seed-{0,1,2}` respond, and the bootstrap phase proceeds.
- any further node will be able to contact all seed nodes.

The `seed=X` label is applied by an initContainer, if the ordinal of the current pod is less than the expected number of seeds, meaning that in the case of the loss of an instance hosting a seed node, the new pod will get labeled as well, and the cluster should then get rolling-restarted to make sure all cassandra pods resolve the seed nodes to the same IPs. 

```bash
#!/usr/bin/env bash

# script ran by an init container to l abel the pod as a seed node 
# if its ordinal is < num_seed_nodes
set -eu

# POD_NAME comes from the downward API
# NB SEEDS is passed via the env 
CURRENT_POD_ID=${POD_NAME##*-}

# Label the pod as a seed node
if [[ $CURRENT_POD_ID -lt $NB_SEEDS ]]; then
    kubectl label pod $POD_NAME seed=$CURRENT_POD_ID
fi
```

For that script to work, we need to define a role with the proper permissions
```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  ...
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "patch"]
```

I realize that setup could be seen as hacky, and only works with pods using net host and no binpacking. However, if these conditions are deemed suitable, it should work reliably.

**Comment by agolomoodysaada** [comment]
@brouberol , thanks for posting your detailed workaround. I still think we need a native solution from Kubernetes.

**Comment by nuthankumar** [comment]
@brouberol tried your work around.. but seems thats not reliable too.. can you please post complete ymls please?

**Comment by aspyct** [comment]
@brouberol What if two cassandra pods are going down at the same time?

Say pod A is running on k8s node 1, and pod B is running on k8s node 2.
They both go down at the same time.
What's to prevent pod A from starting again on node 2, and therefore getting the IP address that was previously assigned to pod B?

**Comment by allamand** [comment]
@aspyct that would be the PersistentVolumeClaim which will stick podA to node 1, so it can't be started on node2 while the PVC object exists.

Saying that I'm not sure that kubernetes could reaffect ip which was on node2 on the node1, this maybe depending on the network plugin ?

**Comment by aspyct** [comment]
Ah yes, that makes sense. Thanks for clearing that up!

Not sure about the node IP either, but I'm guessing in my case Cassandra wouldn't be the only service failing. I'll look into it, thank you for pointing it out.

**Comment by brouberol** [comment]
@allamand 
> Saying that I'm not sure that kubernetes could reaffect ip which was on node2 on the node1, this maybe depending on the network plugin ?

This is why the deployment I detailed is actually using `hostNetwork: true`. In our case, we don't want to binpack on datastore nodes, meaning that cassandra will be the only application pod running on the node, and no two cassandra pods will run on the same node (thanks to the `podAntiAffinity`. In that case, it was acceptable to rely on the host network itself.

**Comment by aspyct** [comment]
@brouberol do we still need the `cassandra-test-seed-*` services then?

We know that the pods will have a static IP address, since they will stick to their initial k8s node, then maybe we can use them directly as seeds. That would allow us to define only one service for all the cassandra pods.

Something like:

```
seed_provider:
- class_name: org.apache.cassandra.locator.SimpleSeedProvider
  parameters:
  - seeds: cassandra-0,cassandra-1,cassandra-2
```

**Comment by brouberol** [comment]
@aspyct You definitely can. The only reason why I defined a service per seed node is that these seed services are annotated with `service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"`, which allows the service DNS to be resolved to some `NotReady` pods. 

I wanted to tolerate that for the seed services (as it's useful during bootstrap) but I didn't want that behavior enabled on the service clients would use to interact with the actual cassandra cluster.

**Comment by allamand** [comment]
Does someone have tested the option from calico : 
```
 annotations:
      "cni.projectcalico.org/ipAddrs": "[\"192.168.0.1\"]"
```
source: https://docs.projectcalico.org/v3.5/reference/cni-plugin/configuration

**Comment by vadalikrishna** [comment]
> @krmayankk not had any time ... And frankly found a work around ish for Cassandra

Can you please share your work around, I am facing a similar issue with cassandra in statefulset.

**Comment by cscetbon** [comment]
@vadalikrishna @krmayankk any information on the workaround would be much appreciated

**Comment by madireddyr** [comment]
@krmayankk  @vadalikrishna  chrislovecnm : any info how you resolved this issue

**Comment by cscetbon** [comment]
> @brouberol What if two cassandra pods are going down at the same time?
> 
> Say pod A is running on k8s node 1, and pod B is running on k8s node 2.
> They both go down at the same time.
> What's to prevent pod A from starting again on node 2, and therefore getting the IP address that was previously assigned to pod B?
It's definitely a problem when both nodes are getting IPs of each other. Cassandra complains that an existing node already holds the tokens the current node is trying to get and refuses to start.

That's why if someone like @chrislovecnm has a workaround it would be much appreciated to know it.

>@allamand Does someone have tested the option from calico :
>
> annotations:
>      "cni.projectcalico.org/ipAddrs": "[\"192.168.0.1\"]"

as you know, the issue is we can't assign different annotations to nodes belonging to a StatefulSet

**Comment by dpepper** [comment]
>Say pod A is running on k8s node 1, and pod B is running on k8s node 2.
They both go down at the same time.
What's to prevent pod A from starting again on node 2, and therefore getting the IP address that was previously assigned to pod B?
It's definitely a problem when both nodes are getting IPs of each other. Cassandra complains that an existing node already holds the tokens the current node is trying to get and refuses to start.

Did anyone find a solution for this?

**Comment by allamand** [comment]
You can force podA to stay on node1 using local storage and persistent volume claim

**Comment by arianvp** [comment]
Can we reopen this? This is still very relevant for many workloads that now have issues running on kubernetes manually. Including  Audio/Video (STUN/TURN etc), redis and cassandra.

**Comment by arianvp** [comment]
If you are using Calico, you could add https://docs.tigera.io/networking/use-specific-ip to each `pod` manually.  However you'd have to add the annotation to new pods that get created when you scale up; which is a bit annoying.

  It would be really cool if we could add an annotation to the `StatefulSet`  that Calico interprets and then does this automatically.  Listen to pods being created; and then add a fixed IP to the pod

**Comment by alitoufighi** [comment]
Can we have this issue reopened?
