### ISSUE TITLE
Log errors / error out when initializing LoadBalancer with without a cloud-provider specified

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kubernetes#28961]
As per @brendandburns 's comment on: https://github.com/kubernetes/kubernetes/issues/12716 longer term, we should error out when a user tries to user type `LoadBalancer` with no cloud provider activated / supplied.

**Comment by xiangpengzhao** [comment]
@cdrage any updates on this? I see your comment https://github.com/kubernetes/kubernetes/issues/12716#issuecomment-232702711. But I don't see any follow PR to fix this.

**Comment by cdrage** [comment]
@xiangpengzhao https://github.com/kubernetes/kubernetes/pull/28963 was the PR. I'll close this.

**Comment by xiangpengzhao** [comment]
Yeah I saw that PR, but I think it just fixed the init of ServiceController. What if someone tries to create a Service of type LoadBalancer without a cloud-provider specified? Is there any error logs for that? Thanks!
