### ISSUE TITLE
Golang 1.7 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#28960]
"On x86-64 systems, many programs will run significantly faster, due to improvements in generated code brought by the new compiler back end. As noted above, in our own benchmarks, the code generation changes alone typically reduce program CPU time by 5-35%." 

https://tip.golang.org/doc/go1.7#performance

/cc @kubernetes/sig-scalability @smarterclayton @kubernetes/rh-cluster-infra 

release time-frame is August, thoughts?

**Comment by wojtek-t** [comment]
That means, that we may consider it for 1.5 release (it would be too late for 1.4).

**Comment by MHBauer** [comment]
I want this part of the compiler:

> The compiler and linker have been optimized and run significantly faster in this release than in Go 1.6, although they are still slower than we would like and will continue to be optimized in future releases.

**Comment by luxas** [comment]
cc @luxas

**Comment by timothysc** [comment]
So fwiw I'm building fine against 1.7 and I've reduced my build times reduced by ~30-40%

MAKE BUILDS GR8 AGAIN! 

/cc @kubernetes/rh-cluster-infra @smarterclayton

**Comment by ixdy** [comment]
cc @jfrazelle

**Comment by jfrazelle** [comment]
https://github.com/kubernetes/kubernetes/pull/28742#issuecomment-240243836

**Comment by jfrazelle** [comment]
Test failure is because of something else

**Comment by jbeda** [comment]
Can we make this happen for 1.5?  Any objections to just doing it?

**Comment by wojtek-t** [comment]
@jbeda - the PR is already in-flight.

**Comment by jbeda** [comment]
@wojtek-t Do you have a link/number?

**Comment by ixdy** [comment]
@jbeda #28742

**Comment by HardySimpson** [comment]
tried build k8s with 1.7, running performance seems not increase much, binary is smaller 50% than 1.6

**Comment by luxas** [comment]
Ok, this has been merged/fixed now, closing...
