### ISSUE TITLE
vSphere limitations with kubernetes

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#28973]
What are the current limitations / nuances with running kubernetes on vSphere?  For instance, I know that ingress controller varies by platform. 

What about: 

- Storage
- Ubernetes, Ubernetes light
- OS for minions
- Load Balancing
- Network challenges
- DNS

**Comment by chrislovecnm** [comment]
@bgrant0607 who can help out on this?

**Comment by imkin** [comment]
@chrislovecnm I am currently maintaining this in my free time.

vSphere deployment steps for kubernetes is documented at http://kubernetes.io/docs/getting-started-guides/vsphere/

- Storage
http://kubernetes.io/docs/user-guide/volumes/#vspherevirtualdisk
@dagnello can comment better on this as he is one of the people who introduced this.

- Ubernetes/Ubernetes light

Not tested. So Not sure.

- OS for minions
debian image in the documentation link.

- Load Balancing
External Could use nginx but currently has none. 
Internal could be used with flannel.

- Network challenges.
One could use OVS

- DNS 
SkyDNS

So all the above answers apply if you are working with the deployment scripts I mentioned above. However by definition if you have a vsphere environment and a manual [or your own automated] way of deployments there is nothing that prevents you from having a full fledge deployments.

**Comment by chrislovecnm** [comment]
Adding @sputnik13 and @dkalleg to this conversation.
 

> vSphere deployment steps for kubernetes is documented at http://kubernetes.io/docs/getting-started-guides/vsphere/

Great doc, but we could use the gotchas documented on blogged.

> Storage
> http://kubernetes.io/docs/user-guide/volumes/#vspherevirtualdisk
> @dagnello can comment better on this as he is one of the people who introduced this.

@dagnello what is the capability?  DRS?

> Ubernetes/Ubernetes light
> 
> Not tested. So Not sure.

Low priority

> OS for minions
> debian image in the documentation link.

We need RHEL ... going to do RHEL on EC2 as well

> Load Balancing
> External Could use nginx but currently has none. 
> Internal could be used with flannel.

This needs to be addressed

> Network challenges.
> One could use OVS

This needs to be documented / addressed.

> DNS 
> SkyDNS

Hasn't this changed in 1.3?  Are we still using sky?

**Comment by chrislovecnm** [comment]
cc @ghand

**Comment by thockin** [comment]
This is not really a bug or feature, so I am going to close it for now.  Holler if it causes you pain?
