### ISSUE TITLE
Memory based autoscaler

### ISSUE THREAD

**Issue by slaskawi** [kubernetes/kubernetes#28986]
Hey!

I've been working on integrating Kubernetes and Infinispan (Java based Data Grid, distributed cache,  in-memory key/value store) and I noticed that [Kubernetes horizontal pod autoscaling feature](http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling) operates only on CPU metrics. 

I would like to propose extending the Autoscaler's functionality and adding memory based thresholds (I understand that a similar effect might be achieved by using Custom Metrics but it requires a lot more configuration). The Autoscaler could possibly be configured to use a combination of two - CPU and memory metrics (but this needs a longer thought how to avoid flipping the number of replicas, probably the easiest way is to set priorities to the metrics).

N.B. Since there are usually 3 types of applications - CPU, memory and I/O intensive, we could add 3rd metric to the Autoscaler - I/O. However I'm not sure how this fits into Persistent Volumes concept in Kubernetes.

What do you think about this idea?

Thanks
Sebastian

**Comment by ncdc** [comment]
fyi @DirectXMan12

**Comment by DirectXMan12** [comment]
See also #28628

**Comment by jszczepkowski** [comment]
Auto-scaling base on memory usually does not work correctly. Memory consumption of pods usually never shrinks, so, adding a new pod will not decrease memory consumption by old pods. This is the reason why there was no autoscaling base on memory in the initial version of HPA.

It is possible that in future scaling based on memory will be possible by explicitly specifying one of embedded hepster metrics (see #28628).

**Comment by slaskawi** [comment]
I think it depends on application type. Data Grids for an instance usually do a rebalance after adding a new node, so you might expect that the total amount of memory used in all pods will slightly drop. Of course it needs proper configuration, in case of JVM it requires setting at least `Xms` (as described [here](https://developerblog.redhat.com/2014/07/15/dude-wheres-my-paas-memory-tuning-javas-footprint-in-openshift-part-1/) and [here](https://developerblog.redhat.com/2014/07/15/dude-wheres-my-paas-memory-tuning-javas-footprint-in-openshift-part-2)).

Could you please tell me if there are any plans of unifying HPA and using https://github.com/kubernetes/kubernetes/pull/28628 for CPU as well? Otherwise there would be a dichotomy (for CPU use this and for anything else use that).

**Comment by DirectXMan12** [comment]
@slaskawi my hope for #28628 is to have it work that way, eventually.  Please do chime in on that issue if you have any feedback.

**Comment by fgrzadkowski** [comment]
@slaskawi Can you please explain your use-case in more details? I have some specific questions:
* If you double number of replicas, what would happen with memory usage? Would drop 2 times?
* How long would it take to rebalance in-memory state between replicas?
* I'm not a Java guy, so forgive my stupid questions. If we decrease "real" memory usage for a Java app, but don't change `Xms` then would the memory usage from the kernel point of view drop, or stay the same? Is it required to modify `Xms`?

**Comment by slaskawi** [comment]
Hey @fgrzadkowski! Of course:

> If you double number of replicas, what would happen with memory usage? Would drop 2 times?

It would drop (probably less than 2 times but it would definitely drop).

> How long would it take to rebalance in-memory state between replicas?

It depends on data and network links between machines in the Grid. For very typical data (several hundred MB) and good network connection it should probably take several seconds. Also it is worth to mention that only a portion of data is being relocated. This is because the whole data set is divided into shards.

> I'm not a Java guy, so forgive my stupid questions. If we decrease "real" memory usage for a Java app, but don't change Xms then would the memory usage from the kernel point of view drop, or stay the same? Is it required to modify Xms?

No worries, I'm here to help :) When a Java app starts, a JVM (Java Virtual Machine) reserves `Xms` memory from the kernel regardless to the real memory needs. When the app continues to operate, it can consume up to `Xmx` memory.

**Comment by fgrzadkowski** [comment]
>
> If you double number of replicas, what would happen with memory usage?
> Would drop 2 times?
>
> It would drop (probably less than 2 times but it would definitely drop).
>

How far from 2 could it be? I'm asking because in HPA algorithm we assume
it will be exactly 2 times (and usually it's the case for CPU). Of course
in the end we will correct ourselves and find good number of replicase, but
potentially it could take multiple iterations until we find it.


> How long would it take to rebalance in-memory state between replicas?
>
> It depends on data and network links between machines in the Grid. For
> very typical data (several hundred MB) and good network connection it
> should probably take several seconds. Also it is worth to mention that only
> a portion of data is being relocated. This is because the whole data set is
> divided into shards.
>
> I'm not a Java guy, so forgive my stupid questions. If we decrease "real"
> memory usage for a Java app, but don't change Xms then would the memory
> usage from the kernel point of view drop, or stay the same? Is it required
> to modify Xms?
>
> No worries, I'm here to help :) When a Java app starts, a JVM (Java
> Virtual Machine) reserves Xms memory from the kernel regardless to the
> real memory needs. When the app continues to operate, it can consume up to
> Xmx memory.
>
So I guess in order to "notice" this drop, we would have to manipulate
`Xms` parameter, together with adding replicas. That could be pretty tricky
as would have to guess how the real memory consumption would react to our
change and how quickly.

**Comment by derekwaynecarr** [comment]
@fgrzadkowski -- i am confused on what is meant by "we".  It's the application responsibility to force reclaim not the platform in this case.

**Comment by fgrzadkowski** [comment]
"we" = "HPA controller"

What I'm trying to say is that in this particular example just adding support for scaling based on memory wouldn't work. We would either need vertical pod autoscaler or change the app to reclaim memory.

**Comment by slaskawi** [comment]
Yes, reclaiming memory from JVM is very tricky.

Perhaps using HPA here is not the best approach here and I should look into [Custom Metrics](https://github.com/kubernetes/kubernetes/blob/release-1.5/docs/proposals/resource-metrics-api.md#custom-metrics-in-hpa)? Since an app (a Data Grid in my case) can estimate the data size and observe how much it dropped after adding additional node, scaling based on some custom metric could be a way out.

**Comment by narasi** [comment]
> Memory consumption of pods usually never shrinks, so, adding a new pod will not decrease memory consumption by old pods

Perhaps I am wrong here, but I think of several use cases where the memory consumption of a pod grows and shrinks, especially if it spawns threads/workers based on demand

**Comment by DirectXMan12** [comment]
Update: memory autoscaling and custom metrics autoscaling are in beta as of Kubernetes 1.8.  I think we can close this issue.
