### ISSUE TITLE
kube-proxy nodePort localhost not working

### ISSUE THREAD

**Issue by yossiilan** [kubernetes/kubernetes#28988]
I've just launched kubernetes 1.3.0
I have a nodePort service with a port of 30000 mapped to port 5000

when I `curl localhost:30000` it hangs
when I `curl 127.0.0.1:30000` it works (I get a response)

It works on kubernetes 1.1.7

Any ideas?

**Comment by dmrub** [comment]
I observe same issue on CentOS 7, Kubernetes 1.2.0. Also it works with node IP (in my case 192.168.81.108).

**Comment by dmrub** [comment]
This issue has something to do with IPv6, running curl with --ipv4 option and localhost:<nodeport> argument works for me.

**Comment by tonylambiris** [comment]
`sysctl -q -w net.ipv6.conf.all.disable_ipv6=1` as an on-the-fly workaround *before* starting any kubernetes-related services.

**Comment by anandkumarpatel** [comment]
+1 I see this issue when trying to run [private registry manually ](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry
) I setup kuberenets with kops `Version 1.5.3`
and kubectl version
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T19:15:41Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

```
sysctl -q -w net.ipv6.conf.all.disable_ipv6=1
-bash: sysctl: command not found
```
sysctl does not exist on my system

**Comment by tonylambiris** [comment]
Try as root?

**Comment by anandkumarpatel** [comment]
wow... @tonylambiris yep that was it. Thanks!
