### ISSUE TITLE
Pod Status Synchronization - Failed Runtime

### ISSUE THREAD

**Issue by bhujangr** [kubernetes/kubernetes#29012]
Have been testing a 1.3.0 cluster which at the moment comprises of 1 master and 1 minion (size does not matter). What we find is if we did deliberately kill the docker daemon (kubelet is running) on the minion, for some reason the event that the minion is `Not Ready` is emitted but the status of the Pods never get updated. What I mean is running `kubectl --server=<master-ip> get pods` always shows the previous state of the pods on the minion which we killed the docker daemon which in my case was `Running`.

I assumed the kubelet property `sync-frequency` would be the property to tweak but in the kubelet logs, I consistently find `I0715 14:54:30.241111    2951 kubelet.go:2477] skipping pod synchronization - [container runtime is down]` and other logs which clearly state the obvious - `Cannot connect to docker daemon`. This seems to be a new [1.3.0](https://github.com/kubernetes/kubernetes/blob/release-1.3/pkg/kubelet/kubelet.go#L2476) change ?? I see it consistently looping around there trying to update the `runtimeState`

Question :
What is the design philosophy here, specifically what happens when things extraneous to the kubelet/kube-proxy but critical for the minion to be `Ready` fail? I ask this as I assume this is not a bug but a conscious decision made in 1.3.0.

**Comment by yujuhong** [comment]
I may be wrong but I don't think this is new in v1.3.

When the container runtime is unreachable, kubelet cannot get the status of the containers, and thus can't update the status.
However, if the node stays not ready for period that's longer the preset threshold (5min?), the node controller will take action and evict all pods on the node.

**Comment by bhujangr** [comment]
Well yes it cannot get the status - known fact. But beyond a certain timeout should it not should take some course of action ??

No the node controller does not take any action if there is only 1 minion in the cluster i.e. the state of the system on the whole is correct but the presentation of the state of the system is not accurate. Extrapolating to a N minion cluster, when the controller cannot re-schedule the pods anywhere it will just sit on it and the kubelet on the minion will loop for ever and the system will present a totally inaccurate state of the pods in the rc. Note the controller does not evict anything (probably there is a flag for this?)

Also what I did was introduce a second minion and the controller as expected re-schedules the pods, after the timeout period - expected behavior but once again it does not correctly reflect the `RESTARTS` count of the pods.  However with only 1 minion if we re-started the docker daemon the pods come back to life and the `RESTARTS` count is incremented.

**Comment by yujuhong** [comment]
I think the node controller doesn't react if *all* nodes in the cluster are not ready because it could be a network issue and evicting pods doesn't help. However, it could still mark the pods as not ready. I am not sure if this is the case or not. The control plane team will know more.

How do you start docker on your node? If you used GKE or kube-up.sh to start a cluster, I believe in most cases, you should have a daemon monitoring docker's health and restart it if necessary. Although that wouldn't solve your issue completely, at least it'd try to recover from that.

**Comment by yujuhong** [comment]
Closing due to age.
