### ISSUE TITLE
Use Go canonical import paths

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#29014]
I think we should follow https://golang.org/doc/go1.4#canonicalimports and decorate all of our packages with their canonical paths.  It's sort of tedious, but I have heard a few people who were unhappy that our code lives in `github.com/kubernetes/kubernetes`, but our go import is `k8s.io/kubernetes`.

This should at least cause a more obvious error.

I suppose that means that every package gets a doc.go with this declaration.

**Comment by dims** [comment]
@thockin ack. i started with a PR to fix existing doc.go's

**Comment by luxas** [comment]
@dims Seems like this is only half-finished...
Will you continue with adding `doc.go` files to those directories who haven't got it?

**Comment by luxas** [comment]
We should have a verification test for this as well

cc @mikedanese @ixdy
