### ISSUE TITLE
Supporting new features in CRI

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#29029]
There are a few features planned or in the process of being added to kubernetes, and we need to plumb this via CRI. Filing this issue to keep track of them for the time being.

(More to be added)
- [ ] apparmor #22159
- [ ] sysctl #27180
- [ ] Nvidia GPU (in `pkg/dockertools` already, but currently is experimental)

**Comment by feiskyer** [comment]
+1

**Comment by feiskyer** [comment]
Refer https://github.com/kubernetes/kubernetes/pull/30118 for apparmor implementation.

**Comment by yujuhong** [comment]
Merging this with #29478
