### ISSUE TITLE
vsphere volume should implement attacher interface

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#29028]
The vsphere volume [calls out to cloud provider to attach a volume](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/vsphere_volume/vsphere_volume_util.go) as part of the `setup(...)` step in the `mounter` plugin interface. 

*The vsphere volume plugin should be refactored to implement the volume [`Attacher` plugin interface](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/volume.go#L136).* This will enable it take advantage of the attach/detach controller and let volume_manager better control device mounting (prevent multiple concurrent operations, do retries, etc).

CC @abithap

**Comment by kerneltime** [comment]
cc @abrarshivani @msterin

**Comment by abrarshivani** [comment]
Let me know if anyone is already fixing this issue otherwise I will work on it.

**Comment by saad-ali** [comment]
@abrarshivani No one is working on it at the moment, AFAIK, so feel free!

**Comment by abithap** [comment]
@abrarshivani  I haven't got a chance to work on it yet. so please carry on if you are planning to fix it.

**Comment by abrarshivani** [comment]
@saad-ali @abithap I have started working on it.

**Comment by saad-ali** [comment]
Heads up, if you want this for v1.4, code freeze is next week. Otherwise this will have to wait for v1.5
