### ISSUE TITLE
Liveness/readiness probe behavior

### ISSUE THREAD

**Issue by cbarlock** [kubernetes/kubernetes#29021]
Forgive me if this is not the right forum for general questions, but I didn't find a mailing list or web site for questions.

For the liveness and readiness probes, does the readiness probe run for the first time only after liveness has been reported to be successful, or does it run independently, running for the first time after whatever its initialDelaySeconds is?

**Comment by girishkalele** [comment]
I just tried it and it seems to be independent - each running after whatever its initialDelaySeconds is set to.

**Comment by yujuhong** [comment]
Forums for kubernetes questions in general:
* stackoverflow: stackoverflow.com/questions/tagged/kubernetes
* slack channel: https://kubernetes.slack.com/messages/kubernetes-users/
We prefer github to be used for reporting bugs or asking for features :)

Yes, as @girishkalele answered, they are independent.

**Comment by cbarlock** [comment]
Thank you both!  Will use github correctly going forward.
