### ISSUE TITLE
Guaranteed scheduling of critical pods

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#29023]
We want to ensure that pods deemed "critical" (this is *not* official terminology -- I am just using it in the colloquial English sense) are guaranteed to schedule if there are sufficient resources for them in an "empty" cluster, even if the cluster is non-empty and non-critical pods are currently occupying node resources that the critical pods would need in order to schedule.

Examples of critical pods are infrastructure pods like heapster and DNS.

cc/ @piosz @fgrzadkowski

**Comment by bhujangr** [comment]
Yes this would be a very useful feature i.e. to set priorities for pods.

**Comment by wojtek-t** [comment]
We are not going to do the "full pod priority" feature at least for 1.4. The plan is just to have a group of "high priority pods" (probably defined as those with some special label) that would be "critical pods" as defined by @davidopp above.

**Comment by therc** [comment]
For our use case (DaemonSets + heapster + DNS + dashboard + GPU pods), a special label is a good start. We'd be happy to provide early testing and feedback.

**Comment by krmayankk** [comment]
```sufficient resources for them in an "empty" cluster, even if the cluster is non-empty ```
i am confused by this line, it would help to provide a slightly better description of this issue .

**Comment by goltermann** [comment]
This is only awaiting docs PR merge.

**Comment by pwittrock** [comment]
@davidopp @piosz 

I am moving this out of the blocking issues we are tracking for the 1.4 release because the unfinished pieces are non-blockers for the release and do not need to be tracked in the burndown meetings.  If there are components besides docs & tests that need to be completed, please move it back to the 1.4 milestone and provide daily status updates.

**Comment by piosz** [comment]
This is fixed right now.
