### ISSUE TITLE
Better User-Agent or other HTTP headers to identify probes

### ISSUE THREAD

**Issue by girishkalele** [kubernetes/kubernetes#29025]
Grabbed tcpdump of a readiness probe - the src ip was the bridge address (10.244.1.1), but apart from this, there is no identifying information in the HTTP request that this is a Kubernetes daemon requesting readiness checks - this might help QoS/priority assignment by the container application.

```
GET /index.html?q=readiness HTTP/1.1
Host: 10.244.2.16:80
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip
Connection: close

HTTP/1.1 200 OK
Server: nginx/1.11.1
Date: Fri, 15 Jul 2016 20:43:20 GMT
Content-Type: text/html
Content-Length: 612
Last-Modified: Tue, 31 May 2016 14:40:22 GMT
Connection: close
ETag: "574da256-264"
```

**Comment by AdoHe** [comment]
@girishkalele IIUC, you mean we should add a better `User-Agent` when kubernetes daemon request a readiness check to identify this request comes from kubernetes daemon?

**Comment by girishkalele** [comment]
@AdoHe Yes, we should override the default net/http user-agent with our own.
Better usability for  users and we have no future upgrade hazards if users start hardcoding and expecting this default User-Agent string in their analytic tools.

**Comment by sbadia** [comment]
Any news about this one? It would be nice!
I've this little hack in my nginx configuration (in order to not be spamed by health check in logs) :)

```nginx
map $http_user_agent $loggable {
  ~^Go-http-client* 0;
  default 1;
}

log_format logstash_json '{ […] }';
access_log /dev/stdout logstash_json if=$loggable;
```

**Comment by paultyng** [comment]
This can probably be closed now that probes have `httpHeaders` support.
