### ISSUE TITLE
Node should report node's resource triplet {capacity, allocable, usage} 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#2903]
Currently scheduler queries VM's capacity to decide the allocable resource, which is not accurate. Kubelet does export capacity as machineSpec from cAdvisor, also it exports root stat which can be used to roughly calculate the total usage of docker / kubelet and kernel. #2884 filed to babysit daemons including monitoring their resource usages. 

Kubelet need to retrieve those stats from cadvisor, and report them as ResourceSpec back to upper layers. The node stats should be queried by client CLI, and scheduler should make the decision based on the truth. 

cc/ @vmarmol @rjnagal @bgrant0607

**Comment by vishh** [comment]
@dchen1107: Is this required for v1.1?

**Comment by dchen1107** [comment]
Yes, it is.

**Comment by bgrant0607** [comment]
Capacity is returned and we have a proposal for usage metrics.

Is there a proposal for allocatable?

**Comment by dchen1107** [comment]
Allocatable is filed separately. Capacity  are handled, and usage is returned through different mechanism too. Close this.
