### ISSUE TITLE
Multi-object etcd transactions

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#2904]
This is a tracking issue. 
https://github.com/coreos/etcd/issues/860

**Comment by mikedanese** [comment]
https://github.com/coreos/etcd/blob/master/Documentation/rfc/v3api.md

**Comment by timothysc** [comment]
I'm going to close this issue.  Multi-op transactions exist in v3, but we will wait until 1.7 before we start batching some operations.

**Comment by kargakis** [comment]
> I'm going to close this issue. Multi-op transactions exist in v3, but we will wait until 1.7 before we start batching some operations.

Shouldn't we keep the issue open until we get there?

**Comment by timothysc** [comment]
We have a series of other issues on our roadmap.   This specific issue simply referenced an etcd capability, and not the refactoring of the registry and storage layers.
