### ISSUE TITLE
Duplicate pod CIDR assignments in 1.3.0

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#29058]
We spun up an 800 node cluster today, across 2 zones and we found 27 duplicate pod CIDRs (and duplicate GCE routes) assigned.  This obviously caused havoc.

We don't have hard evidence, but we think it is NOT related to multi-zone (we found some dups in the same zone).

@kubernetes/sig-scalability

**Comment by thockin** [comment]
Similar 1.2 cluster does NOT show dups.

**Comment by bprashanth** [comment]
I'm going to guess something here isn't locking when it should https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/cidr_set.go
@mqliang @gmarek

**Comment by wojtek-t** [comment]
@gmarek - this may be related to the changes in node controller done in 1.3 timeframe that you did/reviewed. Could you please take a look?

**Comment by bgrant0607** [comment]
It looks like #28604 went in after 1.3.0 was cut.

**Comment by justinsb** [comment]
AFAIK multizone only affects the cloud provider & the volume provider, and thus is not in the code path for PodCIDR allocation.  (The language here is a little ambiguous maybe, so I assume you are talking about the assignment by KCM to Node.Spec.PodCIDR for a newly-created Node)  But I'm here if anyone has any questions about multizone!

Was it HA master?

**Comment by thockin** [comment]
No HA master.  re-titleing to remove zone-relation (likely) misinfo

**Comment by bgrant0607** [comment]
#26531 was merged into 1.3

**Comment by bgrant0607** [comment]
Noticed one sketchy thing: updateCIDRAllocation didn't re-confirm that PodCIDR was still empty when updating a node.

**Comment by bgrant0607** [comment]
It also continues to retry in the case of conflict, though that should just cause performance problems.

**Comment by justinsb** [comment]
Q: If a node is deleted, we release the NodeCIDR.  What happens if it the node is actually still alive?  Will the kubelet recreate the same Node record with the existing PodCIDR?  This might happen if the cloudprovider stopped reporting an instance as being present, the nodecontroller deletes it, but the node could still be alive e.g. eventual consistency problems on AWS, so kubelet will presumably try to re-register.

**Comment by bprashanth** [comment]
Yeah https://github.com/kubernetes/kubernetes/pull/28604 should be just a refactor, the original pr is https://github.com/kubernetes/kubernetes/pull/19242

**Comment by justinsb** [comment]
Regardless of my tendency to leap to over complicated explanations...

Two big problems in the code that leap out at me:

1) I don't see any code that waits for the Node watch to have completed before handing out PodCIDRs.  In other words, I don't think we wait for the allocation map to be fully populated before handing out more pod CIDRs.  I could obviously be missing it!
2) glog.Errorf should be a panic (or glog.Fatalf here) in nodecontroller.go:

```
if nc.allocateNodeCIDRs {
		nodeEventHandlerFuncs = framework.ResourceEventHandlerFuncs{
			AddFunc: func(obj interface{}) {
				node := obj.(*api.Node)
				err := nc.cidrAllocator.AllocateOrOccupyCIDR(node)
				if err != nil {
					glog.Errorf("Error allocating CIDR: %v", err)
				}
			},
	}
```


I bet it is the first.  I don't think the second would be root-cause.

Do we know if KCM restarted during cluster bringup?

**Comment by jlowdermilk** [comment]
KCM was restarted multiple times during cluster turnup for master resizing.

**Comment by justinsb** [comment]
The smoking gun would be if nodes with duplicate cidrs started soon after KCM restart.  We can probably guess that within (say) 2 minutes of KCM start, the map would be fully populated, even with 800 nodes.

**Comment by justinsb** [comment]
Suggested repro steps also if so:

- Bring up 3 nodes (say)
- Stop KCM (but leave API running)
- Bring up 3 more nodes - they will be created in the API but KCM won't allocate them CIDRs
- Restart KCM
- Unless KCM is lucky and sees the first 3 nodes and then the next 3 nodes, you will get a collision because we're using first-fit

**Comment by bprashanth** [comment]
yeah that makes sense, you're basically saying the list of nodes isn't ordered so the new nodes without cidrs might show up before the ones with and the cidr map is empty at the time. If you have a minute testing that theory in a unitest would help.

**Comment by justinsb** [comment]
I can probably have a look this evening.  I'll try to verify "real-world" first, just in case I'm missing a trick.

BTW why does GCE allow duplicate routes?  Our route controller isn't going to like that, I don't think...

**Comment by jlowdermilk** [comment]
Nice call @justinsb. Your repro worked. I created a 3 node cluster, resized it to 6 and killed KCM while resize was in progress. Got duplicate cidr allocations for 2 different nodes.

**Comment by bprashanth** [comment]
Cool! so maybe we just need to list all nodes on restart and populate the map. Might still be racy, lets see.

**Comment by bgrant0607** [comment]
#26531 also added a call to nc.cidrAllocator.Release in the case of an API call failure. That's unsafe. The CIDR could have actually have been written to the node.

**Comment by bgrant0607** [comment]
Unless we cherrypick or rollback #28604, we'll need to fix this directly in the release branch, as well as in head.

**Comment by davidopp** [comment]
> Unless we cherrypick or rollback #28604, we'll need to fix this directly in the release branch, as well as in head.

And #19242 which IIUC @bprashanth mentioned https://github.com/kubernetes/kubernetes/issues/29058#issuecomment-233140475 is the real culprit.

**Comment by davidopp** [comment]
@bprashanth are you working on implementing list all nodes on NC restart?

**Comment by bprashanth** [comment]
I plan to have a hack pr up so jeff can test shortly.

**Comment by justinsb** [comment]
Hooray I get my evening back -  thanks @jlowdermilk for confirming!

**Comment by bprashanth** [comment]
@jlowdermilk fyi https://github.com/kubernetes/kubernetes/pull/29062, plan to iterate

**Comment by thockin** [comment]
Nice sleuthing, everyone!

**Comment by bprashanth** [comment]
I'm going to try this on a larger gce cluster restarting things https://github.com/kubernetes/kubernetes/pull/29062. A similare GKE test would be great, and eyes on review.

**Comment by fabioy** [comment]
@jlowdermilk found a reasonable work around for GKE, which should work for now: detect the dup route, pick one of the two VM instances and tell the IGM to delete it. A new one gets created and all is ok.

**Comment by bprashanth** [comment]
And of course you don want to restart the controller manager during turnup if you can avoid it

**Comment by bprashanth** [comment]
> BTW why does GCE allow duplicate routes? Our route controller isn't going to like that, I don't think...

Overlapping routes should always work because longest prefix wins. Apparently duplicate routes is "undefined behavior", as our debugging shows.

**Comment by justinsb** [comment]
@fabioy  I've been meaning to write something like that for AWS for a while now.  My use case is that sometimes AWS nodes don't show up (particularly with 1.1 where we used master/slave salt), but you can always just get a bad instance.  We could kill:

* Instances that haven't registered as nodes within 1 hour
* Instances that remain in NotReady for 2 hours
* Instances after some number of days (generally people report good results from doing this; particularly with regards to weird docker issues)
* Instances that need security updates (rather than live-reloading?)

And I suspect we'll find more of these if we create it.  I was thinking of a totally external controller than just watches nodes and talks to the GCE/AWS APIs.

Thoughts?  Want to collaborate?

**Comment by bgrant0607** [comment]
Filed #29064 for the bugs in updateCIDRAllocation

**Comment by bgrant0607** [comment]
@justinsb Please file a separate issue for your node auto-healing ideas. Note that there's a big difference between killing functioning and broken nodes, however. Functioning nodes need to be drained gracefully and in a fashion that takes application disruption budgets into account.

**Comment by bgrant0607** [comment]
Cherrypick PR is #29063
