### ISSUE TITLE
kubedns logging is too chatty and not helpful

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#29053]
We need to taker a hard look at every line that gets logged and make sure it tells us something new, and that increasing V levels is also useful (at least for a few levels).  For high-volume clusters this is REALLY important.  Maybe a good starter.

**Comment by thockin** [comment]
Even simply reformatting the logs so they say what they represent would be a help. query received?  responded?  error?

**Comment by dims** [comment]
@thockin the following PR went in a couple of weeks ago: https://github.com/kubernetes/kubernetes/pull/28522/commits/08974941636634dc41e7f6e4a37f784f30834ed5

**Comment by girishkalele** [comment]
@dims Since the dns pod is an addon, it does not run the in-tree version automatically.

The kubedns container needs to be rebuilt and pushed to gcr.io and the addon kube-dns yaml updated etc to have the change take effect.

I've been holding off building and pushing a new container and changing the kube-dns yaml in the addons directory, we had a few more improvements to the DNS pod we were trying to get in, especially the autoscaling.

**Comment by thockin** [comment]
This.,  But also, that commit changes everything to V(2) but I thought we
generally run at V(2) anyway?  And it doesn't focus on cleaning up the text
of messages to be more useful.

**Comment by timbunce** [comment]
I'm unclear on where this is at. We're getting swamped with dns logs.
Thanks for the commit @fluxrad.
Is the volume reduced in v1.4? (I'm unclear re @girishkalele's addon vs in-tree version comment).
If not then could this case be added to the 1.4.1 milestone?

**Comment by fluxrad** [comment]
@timbunce what version of the DNS add-on (and more specifically skydns) are you running? Logging should be minimal by default in recent releases as long as you aren't overriding any defaults. My commit was released in later 1.3 builds.

**Comment by timbunce** [comment]
We're running v1.3.7+coreos.0 and, ah, kube-dns-v17.1. I thought we were using a later kube-dns on this cluster. We'll be rolling a v1.4 cluster soon and will get the addons updated then. Thanks.
