### ISSUE TITLE
Need an e2e to look for duplicate pod CIDR assignments

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#29061]
If it is happening now, it will happen again.

**Comment by justinsb** [comment]
e2e with something like ChaosMonkey going in the background would also probably find more race-condition bugs like this one.

**Comment by matchstick** [comment]
@thockin Would this be good for @MrHohn to try to get in 1.5?

**Comment by justinsb** [comment]
I don't know which sig "owns" the core controllers - node?
