### ISSUE TITLE
updateCIDRAllocation bugs

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#29064]
Forked from #29058

updateCIDRAllocation has 2 issues:
1. The PodCIDR is assigned without confirming that it is still empty. 
2. The CIDR is released on any kind of Update failure (e.g., request timeout), without confirming whether or not the CIDR value were actually written.

cc @gmarek @mqliang @cjcullen

**Comment by bgrant0607** [comment]
See also #28879

**Comment by alex-mohr** [comment]
Neither #29096 nor #29101 have been cherrypicked for 1.3 (and #29096 is tagged v1.4).  Is that appropriate?

**Comment by gmarek** [comment]
I'm not really sure it's worth cherry-picking. The main fix (waiting for full sync before assigning any CIDRS by @bprashanth) is cherry-picked, rest are (I believe) minor bugs with a really small chance of surfacing (e.g. we thought that #28879 is P1).

That being said if we think they should be cherry-picked I can create PRs.

**Comment by gmarek** [comment]
@fabioy - do you think that #29096 should be cherry picked into 1.3 branch?

**Comment by gmarek** [comment]
ping @fabioy

**Comment by fabioy** [comment]
@gmarek Sorry, this slipped through for me. I think #29101 has been cherrypicked into 1.3. Looking at #29096, it seems like it's a safe enough change (and makes the feature marginally safer). I think it's worth cherrypicking.

**Comment by gmarek** [comment]
Created cherry-pick #29985. After it's merged I think we can close this issue.

**Comment by gmarek** [comment]
Cherry-pick merge. Closing.
