### ISSUE TITLE
kubectl says that PetSet is alpha in master

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#29070]
I assume that PetSet will not be alpha in 1.4. 

```console
$ cluster/kubectl.sh get
You must specify the type of resource to get. Valid resource types include:
   * componentstatuses (aka 'cs')
   * configmaps
   * daemonsets (aka 'ds')
   * deployments (aka 'deploy')
   * events (aka 'ev')
   * endpoints (aka 'ep')
   * horizontalpodautoscalers (aka 'hpa')
   * ingress (aka 'ing')
   * jobs
   * limitranges (aka 'limits')
   * nodes (aka 'no')
   * namespaces (aka 'ns')
   * petsets (alpha feature, may be unstable)
```

Petsets should not be listed as alpha in master.

Obligatory version
```console
$ cluster/kubectl.sh version
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.1.309+7eeec7aefeec8d-dirty", GitCommit:"7eeec7aefeec8d848a324877a6bb9d6621dfc186", GitTreeState:"dirty", BuildDate:"2016-07-17T04:18:10Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.1.309+7eeec7aefeec8d-dirty", GitCommit:"7eeec7aefeec8d848a324877a6bb9d6621dfc186", GitTreeState:"dirty", BuildDate:"2016-07-17T04:15:47Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aronchick** [comment]
FYI, we actually aren't committed to anything yet. We hope to get enough miles on it to bring PetSet to beta, but it's a huge feature, so we want to be deliberate.

**Comment by bprashanth** [comment]
It's going to say alpha at HEAD, till it's beta at HEAD, regardless of release

**Comment by erictune** [comment]
It is still going to be alpha in 1.4.

**Comment by Stono** [comment]
@erictune do we have any idea when it'll be out of alpha?  the dynamic pv claims per pod instance solves so many problems for us but we're on GCE who don't support alpha features in anything other than 30day test environments

**Comment by bprashanth** [comment]
GCE supports it, GKE doesn't. I think the target is beta in 1.5 (track https://github.com/kubernetes/kubernetes/issues/28718, not all the issues mentioned there are blockers).

**Comment by Stono** [comment]
Apologies I meant GKE.  Busy day and frantically typing ! I will follow the issue. 

Many thanks
