### ISSUE TITLE
GCE cloud provider logging should have mile-markers for things like LB creation

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#29075]
Default logging does not have much information.  Trying to comprehend an LB Service, I'd really like to see

Time-0: loadbalancer needed
Time-1: targetpool requested
time-2: targetpool confirmed
time-3: firewall requested
time-4: firewall confirmed
time-5: forwardingrule requested

etc.

@arob FYI

**Comment by bprashanth** [comment]
Simply sending the right events will also log them. Another way to do this is to write k/v pairs to annotations and have kubectl describe deserializes it (because events expire).

**Comment by thockin** [comment]
events are a fine way to surface to users for a while, but in this case I
wanted log-lines.

**Comment by nicksardo** [comment]
I believe we have this level of logging now for LB creation, but at V=2 and the default being V=4.  Is it satisfactory to up the verbosity to see these milestones?
