### ISSUE TITLE
Feature request: Option to update just the image tag in a deployment

### ISSUE THREAD

**Issue by ApsOps** [kubernetes/kubernetes#29097]
Currently, to update the container image running in a deployment, we do something like this:

```
kubectl set image deployment/nginx-deployment nginx=nginx:1.91
```

or perhaps using `patch` to update the `image` field.

While this works fine, I think container image names are rarely changed, and we just update the image tag. So it might be a good idea to keep `tag` as a separate field. Then we can do, "set image-tag for this deployment name" without fetching and using the image name again.

Thoughts?

**Comment by pwittrock** [comment]
Are you suggesting something like:

`kubectl set imagetag deployment/nginx-deployment nginx=1.91`

**Comment by ApsOps** [comment]
Not necessarily the subcommand, but yeah something like that. I currently
send a PATCH request with the full image name and tag to the api. It would
be nice if I can send just the tag. So I guess it would need to add another
field in the PodSpec?

**Comment by morissette** [comment]
Handle in ci/cd pipeline? Heres how I do it:
https://www.dropbox.com/s/838u8dfa1nncml0/ci_cd.png?dl=0

**Comment by kargakis** [comment]
I am against doing this because tag is not unique in an image spec, eg. I can use the sha hash of the image instead - moreover I think it's more sane to use hashes vs tags but that's another discussion.

**Comment by kargakis** [comment]
set image works fine too

**Comment by FingerLiu** [comment]
is this command usable with python client??   https://github.com/kubernetes-incubator/client-python

**Comment by joan38** [comment]
Can anyone point this `kubectl set image` feature in the API?
https://kubernetes.io/docs/api-reference/v1.8/#patch-22

**Comment by ApsOps** [comment]
@joan38 I do this, but docs UI seems to have gone downhill. So can't find anything now 🤷‍♂️ 
```python
url = ("http://{kube_master}/apis/extensions/v1beta1/namespaces/{ns}/"
       "deployments/{d}".format(kube_master=args.kube_master,
                                ns=args.namespace,
                                d=args.deployment))

headers = {'Content-Type': 'application/strategic-merge-patch+json'}

payload = '{"spec":{"template":{"spec":{"containers":[{"name": "%s", "image":"%s"}]}}}}' % (args.deployment, image_name)

 r = requests.patch(url, headers=headers, data=payload)
```

**Comment by pezzati** [comment]
Sorry to comment on this old issue. I want to update my image after some search i have found below straight command.
`kubectl set image deployment/application app-container=$IMAGE`
Is this alright for to use in productions env?

**Comment by oesukam** [comment]
> https://kubernetes.io/docs/api-reference/v1.8/

There is no issue with using it on production depending on your deployment workflow
