### ISSUE TITLE
after modifying the --graph of docker, make release for kubernetes has always failed

### ISSUE THREAD

**Issue by GavinSong123** [kubernetes/kubernetes#29091]
The output messages as follow:
build/release.sh
+++ [0718 15:42:06] Verifying Prerequisites....
+++ [0718 15:42:11] Building Docker image kube-build:build-41a795c3c3.
+++ Docker build command failed for kube-build:build-41a795c3c3

Sending build context to Docker daemon 42.05 MB
Step 1 : FROM gcr.io/google_containers/kube-cross:v1.6.2-2
 ---> 608ac17ba91b
Step 2 : RUN touch /kube-build-image
 ---> Running in 577160674abc
Container command '/bin/sh' not found or does not exist.

To retry manually, run:

docker build -t kube-build:build-41a795c3c3 --pull=false /home/ennew/Documents/kubernetes/_output/images/kube-build:build-41a795c3c3

!!! Error in build/../build/common.sh:534
  'return 1' exited with status 1
Call stack:
  1: build/../build/common.sh:534 kube::build::build_image(...)
  2: build/release.sh:32 main(...)
Exiting with status 1
Makefile:150: recipe for target 'release' failed
make: *** [release] Error 1

**Comment by lavalamp** [comment]
I can't tell from this what you're doing. What are the reproduction steps?

**Comment by GavinSong123** [comment]
@lavalamp Sorry...It's the problem of my docker service. I restart my docker service and it has been solved. Thank you.
