### ISSUE TITLE
Munge Github should auto assign docs prs to owners

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#29126]
kubernetes.github.io PRs should be auto assigned to owners.

- Add OWNERS to each doc in structured yaml at top
- Munge github should assign PRs based on the structured yaml

**Comment by bgrant0607** [comment]
See also https://github.com/kubernetes/kubernetes.github.io/issues/874

**Comment by bgrant0607** [comment]
Closing this as a dupe.
