### ISSUE TITLE
update gcr.io/google_containers/etcd to 3.0.3

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#29132]
No one outside of google can update these images and prior to other PRs to change scripts and what-not we need the latest etcd in the google registry. 

@hongchaodeng @xiang90 should direct the exact version to start validation. 

/cc @kubernetes/sig-scalability

**Comment by wojtek-t** [comment]
@lavalamp 

I'm happy to help with building the image.

**Comment by lavalamp** [comment]
SGTM, but (obviously) just make sure the tag is sufficiently distinct that it won't be confused for an etcd 2 build.

**Comment by wojtek-t** [comment]
Sure (We already have meaningful tags, e.g. etcd:2.2.1 - I will still be following this convention).

**Comment by luxas** [comment]
I can update the image in  `cluster/images/etcd`, just ping me with the version you want.

**Comment by timothysc** [comment]
Latest tag is https://github.com/coreos/etcd/tree/v3.0.3 .  I would consult @xiang90 on best release to target.

**Comment by timothysc** [comment]
@luxas I think 3.0.3 is fine and we can re-update as needed.

**Comment by xiang90** [comment]
@timothysc Yes. etcd 3.0.3 is fine.

**Comment by timothysc** [comment]
done?  

sudo docker pull gcr.io/google_containers/etcd:3.0.3
Trying to pull repository gcr.io/google_containers/etcd ... 
Pulling repository gcr.io/google_containers/etcd
Tag 3.0.3 not found in repository gcr.io/google_containers/etcd

**Comment by wojtek-t** [comment]
@timothysc - will do it tomorrow

**Comment by wojtek-t** [comment]
Should work now.

**Comment by luxas** [comment]
Well, I thought it was obvious, @wojtek-t, but pointing it out now: Push the images for all arches if there's a Makefile with support for it, and the README says one should.

Thanks!

**Comment by wojtek-t** [comment]
@luxas - I did "make push".
What should I do to push everything?

**Comment by timothysc** [comment]
works, thx!

**Comment by luxas** [comment]
@wojtek-t Seems like I should document/clarify it even more then.
See here: https://github.com/kubernetes/kubernetes/blob/master/cluster/images/etcd/README.md

Might be worth it to just automatically push all arches on "make push"... I may put it on my todo list :)

**Comment by luxas** [comment]
@vishh Can you push the etcd images for non-amd64 arches please?

**Comment by timothysc** [comment]
we will need to rev to 3.0.4 once https://github.com/kubernetes/kubernetes/pull/29399 is done.

**Comment by luxas** [comment]
@timothysc Okay, just send a PR that updates the tag and ping some googler to push it.

**Comment by timothysc** [comment]
ack.

**Comment by luxas** [comment]
@wojtek-t `make push ARCH=arm`, `make push ARCH=arm64` and `make push ARCH=ppc64le` _now_ would be very kind of you
