### ISSUE TITLE
Need a way to distinguish the source of different scales

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/kubernetes#29143]
While working on idling, we discovered that we need a way to determine (in a object-agnostic way) to determine the source of the last scale event.  To this end, it would be useful to have some sort of annotation (or something of the sort) that can be read and set via the the `Scale` object.  Any scale done without explicitly setting this field/annotation/etc would clear it.  Otherwise, the autoscaler, idler, etc could set the value to indicate that it was the last thing to scale the object.

For example, the idler could use this to determine if the last scale was a scale-down that it initiated versus a scale-down that the user initiated.  It could also be used by UIs, etc to determine if a particular RC, etc was idled.

cc @ncdc @jwforres @benjaminp @kubernetes/autoscaling @smarterclayton

**Comment by smarterclayton** [comment]
As a straw man:

1. Add a boolean / string field to `Scale` that indicates `machine scaling / source of scaling`
2. That value would be reflected on an annotation on the underlying object.
3. All human initiated scale actions would not set that field, which would cause it to be reset
4. Autoscaler or Idler would set the appropriate value, and could use that to determine whether they are "fighting" for scale
5. Unidler could use that value to see whether a manual scale had intervened

This is similar to controller / owner references, and could also be considered to be a subset of annotations.  I think we want two things that don't happen with those:

1. The value gets reset by naive clients
2. The end entity doing scaling shouldn't be able to set / read arbitrary annotations

**Comment by smarterclayton** [comment]
Alternative - have this be a machine-readable field (similar to `Reason`) that users can set about why something was scaled.  Machines can expect / test a specific value.

**Comment by smarterclayton** [comment]
Legacy clients would potentially still be limited (in that they can't make the correct determination), so we may have to rely on looking at an annotation for correctness in the short run.

**Comment by smarterclayton** [comment]
@DirectXMan12 for the near term we can do the following:

1. set the annotation on the target object directly at the same time we scale for a set of known "important" API objects (deployments, rcs, petsets, jobs), bypassing scale API
2. use the scale API for anything else (anything we don't recognize) until something like this gets added, and say end users can get weird unidling.
