### ISSUE TITLE
Pod state is "ready" when CNI plugin fails to fetch the ip

### ISSUE THREAD

**Issue by alena1108** [kubernetes/kubernetes#29148]
We are working on developing Rancher CNI plugin for Kubernetes, and ran into an issue when CNI plugin reported an error, yet the POD was launched successfully (only with container missing ip address). Just wanted to understand what is the reason for this behavior: 

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker_manager.go#L347

I would expect the failure in container start and for the pod to signal that there was some issue by displaying "Not ready" status. But I might not have the full picture :) so appreciate any comments

**Comment by alena1108** [comment]
Forgot to mention k8s version: 1.3

**Comment by nhlfr** [comment]
I encountered this issue too. My proposition is to set unknown state with message about network failure.

@kubernetes/sig-network please let me know whether you agree with this approach.

**Comment by dcbw** [comment]
Great question... I don't think the docker manager should be ignoring errors from the network after steup, but this was probably done because determineContainerIP() is called from inspectContainer() which is used in a ton of places, including potentially before the network has been set up.

**Comment by nhlfr** [comment]
@dcbw your PR doesn't seem to change container status when IP address cannot be retrieved, am I wrong? It's still confusing to have a "Running" container in such situations.

**Comment by nhlfr** [comment]
And what's wrong with my PR?

**Comment by thockin** [comment]
I'll close @dcbw's PR as a dup.  The question of what state it should be in if inspect fails to find an IP is probably discussable.

**Comment by nhlfr** [comment]
Since we have no other state as "running", "exited", "unknown" and "created", I think that the most suitable is "unknown". Of course only as a quick fix, in future we may need to create a separate state for network issues.

**Comment by freehan** [comment]
If SetUpPod return error, kubelet will tear down and recreate the pod. 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker_manager.go#L2018

**Comment by freehan** [comment]
What if we just fail the pod setup? If no valid pod ip can be retrieved after a successful SetUpPod. No need for a "unknown" state. 

Only need to check and declare failure here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker_manager.go#L2052
