### ISSUE TITLE
Kubernetes to allow DNS wildcards (RFC 4592) in ingress resource host names

### ISSUE THREAD

**Issue by from-nibly** [kubernetes/kubernetes#29151]
Proxy backends used in typical infrastructure support the use of asterisk wildcards for hostname based routing. For some reason the ingress resources validation uses the IsDNS1123Subdomain function which does not allow for wild cards. This proposal would be for an additional method, isDNS4592WildcardSubdomain, that would allow a wildcard to be used at the beginning of the dns name when validating ingress hostnames. These values would then just be passed on to the ingress controller to use.

**Comment by knobunc** [comment]
This looks to have been resolved by https://github.com/kubernetes/kubernetes/pull/29204
