### ISSUE TITLE
k8s-1.2.5 code is correct with method determineContainerIP?

### ISSUE THREAD

**Issue by vklonghml** [kubernetes/kubernetes#29161]
Hi all,
Recently, i have been reading the k8s code(version 1.2.5), and i found a method definition:
func (dm *DockerManager) determineContainerIP(podNamespace, podName string, container *docker.Container) string,
in directory pkg/kubelet/dockertools/manager.go, line 299. It's called by two different ways in line 366 (ip = dm.determineContainerIP(podNamespace, podName, iResult), the order of the arguments is same with the method, while in line 1918(podIP = dm.determineContainerIP(pod.Name, pod.Namespace, podInfraContainer), the arguments are in the opposite order(Name and Namespace).

If i did misunderstand the meaning of the situation or not, thanks.

**Comment by AdoHe** [comment]
@kubernetes/sig-node seems like small mistake.

**Comment by yujuhong** [comment]
Assigned to @euank since he already has a PR up.

**Comment by euank** [comment]
To close the loop on communication, it's a real bug but afaict the impact is tiny (since only the exec network plugin cares about those arguments being ordered right, and some of those might not actually care either).

Good catch and thanks for reporting what you saw there @vklonghml  :smile:
