### ISSUE TITLE
Make NodeSpec.unschedulable a Taint

### ISSUE THREAD

**Issue by lukaszo** [kubernetes/kubernetes#29178]
This is a fork from this [comment](https://github.com/kubernetes/kubernetes/pull/18263#issuecomment-169220144) NodeSpec.unschedulable was introduced before Taints/Tolerations. Now it's time to deprecate it.

Here are work items from @bgrant0607:
- we should "deprecate" the existing NodeSpec.unschedulable field and represent that as a taint
- we should automatically apply taints for node conditions that cause the node to become unschedulable

DaemonSets do not respect NodeSpec.unschedulable(which is intended behavior) which sometimes leads to problems. See #29108, #26810 and #29193. With moving  NodeSpec.unschedulable to be a Taint user will be able to control this behavior. DaemonSets will automatically Tolerate this Taint but user will be able to change it.

cc @mikedanese @davidopp

**Comment by lukaszo** [comment]
I have two questions here:
1. Is it required to be a backward compatible? User can manually change node state using kubectl: `kubectl patch nodes kubernetes-node-1 -p '{"spec": {"unschedulable": true}}'` After moving to a Taint this will not work.
2. Does this change require a spec or this issue is enough? For example what should be the taint Key here? Are there some well defined prefixes for system Taints?

**Comment by bgrant0607** [comment]
@lukaszo Yes, backward compatibility is required. We need to auto-convert `unschedulable` to a taint. I'd like to do similarly with node conditions.

We haven't established conventions yet, but we will need some.

**Comment by liggitt** [comment]
do we expect all node condition types and statuses to be pre-defined? how does that intersect with unknown/custom conditions (c.f. https://github.com/kubernetes/kubernetes/pull/36209, https://github.com/kubernetes/kubernetes/pull/36210)?

having the scheduler only pay attention to taints works if conditions can be converted to taints before persisting the node, but if that conversion is done externally by a controller, it introduces a race with the scheduler

**Comment by davidopp** [comment]
There shouldn't be any explicit conversion of conditions to taints.

At startup we can use #31647 to ensure the node does not register before the desired taints are applied.

Things that are today conditions that block scheduling, will have taints created for them by NodeController or Kubelet. (If we keep all of the conditions, then we can just have NodeController create all the taints based on the conditions, otherwise we'll need Kubelet to add the taints.)

Does that answer your question?

**Comment by k82cn** [comment]
Handled by https://github.com/kubernetes/kubernetes/pull/61161 :)

**Comment by k82cn** [comment]
/close

`TaintNodesByCondition` is upgraded to beta in 1.13, so close this issue.
