### ISSUE TITLE
Failed to negotiate api version after upgrading to 1.3.0 with non-default username

### ISSUE THREAD

**Issue by JorritSalverda** [kubernetes/kubernetes#29198]
I upgraded the master version of 2 GKE clusters from 1.2.4 to 1.3.0. 

Unfortunately  kubectl no longer wants to connect and gives the following error

```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}

error: failed to negotiate an api version; server supports: map[], client supports: map[v1:{} metrics/v1alpha1:{} extensions/v1beta1:{} componentconfig/v1alpha1:{} batch/v1:{} autoscaling/v1:{} author
ization.k8s.io/v1beta1:{}]
```

The apis also no longer work when connecting to them directly, they return messages like

```
Forbidden: "/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/"
```

The issue seems to be related to a non-default username - k8s_admin instead of admin - because all my other clusters with default name didn't have this issue. 

I had to create new clusters to solve the issue.

**Comment by pwittrock** [comment]
@lavalamp Does this look like it might be related to CSI or auth?

**Comment by pwittrock** [comment]
cc @erictune for potential auth issue

**Comment by erictune** [comment]
@cjcullen for GKE auth issue.

**Comment by cjcullen** [comment]
This is a bug in our abac file: See #28869.

**Comment by cjcullen** [comment]
I've got a PR out to fix it: #29164

**Comment by pwittrock** [comment]
Closing as a dup

**Comment by pwittrock** [comment]
@JorritSalverda Thanks for reporting.  We will publish steps to work around this until it is resolved for anyone else who encounters it.

**Comment by cjcullen** [comment]
To workaround until it is fixed, you can add a line to the master's abac-authz-policy.jsonl file:
```
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"custom_username", "namespace": "*", "resource": "*", "apiGroup": "*", "nonResourcePath": "*"}}
```

 and then restart the kube-apiserver (docker kill it, and let it restart).
