### ISSUE TITLE
Pod created by DamonSet is always in running phase 

### ISSUE THREAD

**Issue by liubog2008** [kubernetes/kubernetes#29193]
When a node is not ready, the pod created by daemonset is still in running phase which is in this node.

![image](https://cloud.githubusercontent.com/assets/7920667/16948936/3a54fe20-4dea-11e6-893c-b2cdc3059a09.png)
![image](https://cloud.githubusercontent.com/assets/7920667/16948939/45bfcbe6-4dea-11e6-856e-e7c5180d0230.png)
![image](https://cloud.githubusercontent.com/assets/7920667/16948950/59cfe3fa-4dea-11e6-85f1-9608317df40f.png)

**Comment by lukaszo** [comment]
This is expected behavior. See description in documentation http://kubernetes.io/docs/admin/daemons/#how-daemon-pods-are-scheduled

**Comment by liubog2008** [comment]
I'm sorry that I cannot understand what you means... I think if node is not ready, pod phase should jump to Pending or another phase. This issue is not related to NodeSepc.unschedulable.

**Comment by yujuhong** [comment]
@davidopp I think there are a couple of issues all related to how pod status should reflect the fact that the node is NotReady/Deleted/Unresponsive. Should we consolidate all the issues and discuss this in one place?

**Comment by davidopp** [comment]
Yeah, this is Working As Intended but I agree with @yujuhong that it's confusing to say the pod is "running." At least we should document it. @yujuhong, I'm not sure which other issues you have in mind, but please feel free to consolidate them.

**Comment by ddysher** [comment]
An unschedulable node doesn't necessarily mean pods on that nodes are not running; it's just new pods can't land on it.

With taints, pod (created from daemonset) is able to specify its tolerance; however, I don't think there is an essential difference between unschedulable node and node with taints where pod can't tolerate the taints. In current model, pod will show up as running in both cases.

Document is good, but a phase other 'running' would be better.

**Comment by davidopp** [comment]
@ddysher The scenario @liubog2008 described isn't an unschedulable node, it's a node that is NotReady, for example possibly down. Although PodStatus will have more specific Condition information, I can understand why people would be confused to see the pod's Phase is Running, at least without better documentation.

**Comment by ddysher** [comment]
@davidopp Agreed.   I understand @liubog2008's description.  My previous comment was meant to @lukaszo as @lukaszo mentioned NodeSpec.unschedulable.

**Comment by lukaszo** [comment]
Yeah, sorry for confusion. I've misread the nodes statuses.
