### ISSUE TITLE
kube-up gce/coreos for recent CoreOS results in a cluster without port-forward working

### ISSUE THREAD

**Issue by euank** [kubernetes/kubernetes#29213]
ref #19765 and https://github.com/coreos/bugs/issues/1114

CoreOS intentionally does not provide a socat command on the host. The recommended way of running kubelet is to use the `kubelet-wrapper` script which correctly bundles dependencies like socat.

The `kube-up` using gce+CoreOS should result in a working cluster. The possible resolutions to this are:
1. `kube-up` uses `kubelet-wrapper` internally. This is attractive because it also aligns with CoreOS's recommendation for how kubelet should be run.
2. `kube-up` installs a socat binary out of band
3. `kube-up` for the gce+CoreOS flavour is removed. This results in it being more difficult for e.g. the e2e tests to be run against CoreOS.
4. As discussed in the first-linked-issue above, socat is vendored as an image or such and kubelet downloads it that way.

My preference is 1 or 4 and 1 solves more problems overall, so I'm leaning towards that.

/cc @aaronlevy @yifan-gu

**Comment by yifan-gu** [comment]
Prefer the 1st option.

**Comment by euank** [comment]
I'll work on option 1)

The work, as I understand it now, is roughly:

[ ] Change the `make release` target to build the hyperkube image and copy it as an artifact for deployment (like other images / master components)
[ ] Update the cluster/gce/coreos stuff to load the hyperkube image
[ ] Update the userdata to include a `kubelet-wrapper` script that uses said hyperkube image, or use the one shipped as part of CoreOS
[ ] Validate, test, etc

**Comment by pires** [comment]
Prefer the 1st option as well, but as I've had the opportunity to say before, `quay.io/coreos/hyperkube` release process doesn't (yet?) follow Kubernetes one. For instance, Kubernetes v1.3.6 was released 3 days ago and still no `quay.io/coreos/hyperkube` image is available for that version.

So @euank would fixing this issue fix the aforementioned situation, as well?

Other than that, I'm willing to contribute here if I can count on your guidance.

**Comment by euank** [comment]
@pires Starting with the v1.4.0 release, if you want to use official releases with the kubelet wrapper, you can do that just by setting the `KUBELET_ACI` variable (ref](https://github.com/coreos/coreos-overlay/blob/0d7f1e8b257fde4aeaf5aeae509af9931be30a60/app-admin/kubelet-wrapper/files/kubelet-wrapper#L15)). The PR that allows it is #29591, so you can also build any release with that PR picked on and use the upstream image.
This wouldn't fix the issue for official releases deployed by means other than kube-up (since that's already fixed), just for `kube-up` / local builds.

My progress on this one has been a little slow, sorry, but I'm working on it. I've got a commit [here](https://github.com/euank/kubernetes/tree/kubelet-wrapper-up) which hits the first two checkboxes.

Unfortunately, I'm worried that it won't get merged into master easily (for good reason) because it significantly slows down kube-up due to the size of the hyperkube image, and its build process being much slower (`FROM debian; apt-get install` vs `FROM scratch`).

I'd like to move it to *only* building the hyperkube image, not the other ones, and using that for every kube-up target, at which point it would decrease the size, but I expect that a change that hits that many distros will be slow to get in and harder to get right.

I'd be happy to provide guidance if you want to help... and xref #16508 because doing this right will also probably fix that.

**Comment by jimmycuadra** [comment]
@euank Can you clarify what would be lost by using the official hyperkube instead of the one packaged by CoreOS? Aren't there CoreOS-specific fixes that would be missing by using the official hyperkube?

**Comment by euank** [comment]
Yup, quite happy to clarify @jimmycuadra 

The list of differences can be found in our release notes (or by diffing between repos if you like). For example, the current release's list of changes: https://github.com/coreos/kubernetes/releases/tag/v1.3.6%2Bcoreos.0

The one there that kubelet-wrapper makes use of which would result in it not working with an official image prior to v1.4.0 is the PR I linked above; symlinking hyperkube to well-known paths. Several of the other changes are destined for v1.4.0 release, so hopefully the diff will be even smaller then.

Aside from the changes we cherry-pick in, we also specifically test the release against CoreOS + kubelet-wrapper, which the upstream image isn't currently tested against afaik.

**Comment by jimmycuadra** [comment]
That's very helpful, thank you! Thinking about it again, IIRC the CoreOS version also has socat inside the image, where the official one doesn't. (Required for proxy/port forwarding.)

**Comment by euank** [comment]
socat is included in the base image for recent versions of Container Linux, and that cluster folder is going away at some point (hopefully soon)

/close
