### ISSUE TITLE
volumeManager is initialized twice in kubelet

### ISSUE THREAD

**Issue by mikekap** [kubernetes/kubernetes#29239]
Offshoot of #28643: I noticed that volumeManager is initialized twice:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L409
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L517

I don't think that's intentional

**Comment by Random-Liu** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/29233.

You guys found the same issue almost at the same time. :)

**Comment by Random-Liu** [comment]
Close this one, since dup to https://github.com/kubernetes/kubernetes/issues/29233.

And thanks a lot for reporting this. @mikekap
