### ISSUE TITLE
Strange code duplication in NewMainKubelet function in pkg/kubelet/kubelet.go

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#29233]
This block of code:
```
	klet.volumePluginMgr, err =
		NewInitializedVolumePluginMgr(klet, volumePlugins)
	if err != nil {
		return nil, err
	}

	klet.volumeManager, err = volumemanager.NewVolumeManager(
		enableControllerAttachDetach,
		hostname,
		klet.podManager,
		klet.kubeClient,
		klet.volumePluginMgr,
		klet.containerRuntime,
		mounter)
```

Appears twice in `NewMainKubelet`, in `pkg/kubelet/kubelet.go`. This seems wrong. 
Most-likely, the duplicate before `switch containerRuntime` is the one that should be removed, because that switch statement is where `klet.containerRuntime` is set.

**Comment by dhawal55** [comment]
This is fixed as part of the following pull: (#29240)[https://github.com/kubernetes/kubernetes/pull/29240]
