### ISSUE TITLE
kube-down doesn't delete deployments

### ISSUE THREAD

**Issue by lparam** [kubernetes/kubernetes#29248]
The function 'tear_down_alive_resources' on cluster/common.sh doesn't delete deployments.
It's used by:
```console
KUBETERNETES_PROVIDER=ubuntu ./kube-down.sh
```
I want to submit a PR, how to sign a individual CLA?

**Comment by apelisse** [comment]
Please refer to: https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md#how-to-become-a-contributor-and-submit-your-own-code
