### ISSUE TITLE
kubelet's RSS memory usage increased (?)

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#29244]
See #28399 for various soak cluster failures where kubelet's memory usage exceeds the preset threshold.

I don't think there is a memory leak (as I've randomly checked the kubelet heap profile from the soak cluster a couple of times over last week), but I am not 100% sure. It may be that kubelet simply consumes more memory than before. Before jumping to conclusions, it'd be good to validate this. A simple solution may be to run the [resource usage test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/kubelet_perf.go) continuously using v1.2 kubelet and 1.3 kubelet, and compare the memory usage. If there is a discrepancy, getting the heap profile (`/debug/pprof/heap`) and compare them.

Checking the soak cluster periodically may also help.

If there is nothing out of normal, it's possible that small things accumulated over time and cause the increase. In that case, it'd be ok to bump the limits. 

I'd appreciate if anyone is willing to pick this up. 

/cc @kubernetes/goog-node 

p.s. As for the "docker runtime" memory leak, I traced it back to a docker/go-patricia issue (see https://github.com/kubernetes/kubernetes/issues/28124#issuecomment-231804229), so please just ignore it for now.

**Comment by yujuhong** [comment]
Thanks @coufon for volunteering to help!

**Comment by coufon** [comment]
I run 30 back-to-back resource usage test using v1.3 kubelet (commit 7e1e51844f79cdf76a3ca9378380749fd256d234, July 28th). I found that RSS memory usage of kubelet continuous increases. For example, I plot the memory got from 300 pods resource monitoring of the tests on one node:

![soak_test_memory](https://cloud.githubusercontent.com/assets/11655397/17279589/bcd40a1c-572c-11e6-908d-3698376ad341.png)

**Comment by yujuhong** [comment]
@coufon thanks for investigating! Did you get the heap profile of kubelet to figure out what was using the memory?

**Comment by yujuhong** [comment]
This looks like a memory leak. /cc @kubernetes/goog-node

**Comment by vishh** [comment]
Don't we have e2e tests to catch leaks like this?

**Comment by yujuhong** [comment]
> Don't we have e2e tests to catch leaks like this?

We have had some occasional e2e failures, that's why I asked @coufon to look at this. If the memory was growing slowly, and we have a generous margin in our test, it may not always fail.

**Comment by coufon** [comment]
I tested V1.2 and see a similar RSS memory increase. I tried to call runtime.GC() and debug.FreeOSMemory() per minute in V1.3 and observe the follows:

 <img src="https://cloud.githubusercontent.com/assets/11655397/17464141/300e8b10-5c8c-11e6-9d85-a8e298d753d8.png" width="50%", height="50%">

**Comment by coufon** [comment]
I measured the memory usage of V1.2 and found the same. Then I run V1.3 with setting memory profiling interval to 1, and call runtime.GC() and debug.FreeOSMemory() every minute. The result is as follows:

 <img src="https://cloud.githubusercontent.com/assets/11655397/17491130/24c76752-5d5b-11e6-9a55-df67acf7ee9b.png" width="50%", height="50%">

**Comment by coufon** [comment]
I run a longer soak test and see that the memory increasing becomes flat.

 <img src="https://cloud.githubusercontent.com/assets/11655397/17747252/c75dc43e-6468-11e6-858e-5d0fddf0a024.png" width="50%", height="50%">

**Comment by yujuhong** [comment]
I discussed with @coufon offline. The memory increase slows down and becomes marginal after a while. Most likely the increase is caused by some in-memory caching of stats or metrics. We should dig into this more and understand the exact cause, but I think it's safe to de-prioritze this until later.

@coufon thanks investigating this!

**Comment by yujuhong** [comment]
We need to understand the memory usage of kubelet more, but this is not a release blocker. Given how much kubelet has changed, I am going to close this issue.
