### ISSUE TITLE
kubernetes build on master branch failed on osx

### ISSUE THREAD

**Issue by mfanjie** [kubernetes/kubernetes#29247]
make quick-release
Go version: go version go1.6.2 darwin/amd64
+++ [0720 10:21:36] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0720 10:21:37] Building go targets for darwin/amd64:
    cmd/libs/go2idl/deepcopy-gen
+++ [0720 10:21:40] Placing binaries
.....
+++ [0720 10:21:51] Verifying Prerequisites....
+++ [0720 10:21:57] Building Docker image kube-build:build-817039c9e6
+++ [0720 10:22:06] Running build command....
Go version: go version go1.6.2 linux/amd64
+++ [0720 02:22:16] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0720 02:22:16] Building go targets for linux/amd64:
    cmd/libs/go2idl/deepcopy-gen
+++ [0720 02:22:16] Placing binaries
ln: failed to create symbolic link '/go/src/k8s.io/kubernetes/_output/bin': Permission denied
!!! Error in /go/src/k8s.io/kubernetes/hack/lib/golang.sh:379
  'ln -s "${KUBE_OUTPUT_BINPATH}/${platform}" "${THIS_PLATFORM_BIN}"' exited with status 1
Call stack:
  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:379 kube::golang::place_bins(...)
  2: hack/make-rules/build.sh:27 main(...)
Exiting with status 1

**Comment by mfanjie** [comment]
I believe recent changes in build/build-image/Dockerfile breaks it, the build for 1.3 release still works.
when I echo whoami in Dockerfile, it showed `whoami: cannot find name for user ID 110261235` but the owner of _out folder is root.

**Comment by dims** [comment]
@mfanjie : seems to work for me. http://paste.openstack.org/show/538800/

**Comment by mfanjie** [comment]
Thanks @dims, not sure if this is my mac configuration problem.

The strange thing is I did not see the error when I run build on release-1.3.0, I can workaround this problem by do full build on my linux env, close the issue now. I will try more times when I clean up my handy tasks.

**Comment by fabioy** [comment]
Definitely seeing this on my Mac. Can't build HEAD due to this issue. Tried rebuilding the "kube-dev" Docker machine as well, but still get same permission error.

**Comment by fabioy** [comment]
Figure out a workaround -- use Docker for Mac. I had Docker Machine on my Mac, so uninstalling it and using Docker for Mac (after resizing it to use 4 Gig of RAM) worked.
