### ISSUE TITLE
Make Attach/Detach controller robust against pre-mature PVC/PV deletion

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#29262]
This is a follow up to Issue https://github.com/kubernetes/kubernetes/issues/29051 and PR https://github.com/kubernetes/kubernetes/pull/29077

We should:
- Modify attach/detach controller to cache PVC/PV for each volume so even if these objects are deleted, pod deletion events can be processed without error, resulting in even faster detaches.
- Add a test to verify this scenario (PVC volumes are detached on namespace deletion) and prevent future regressions.

**Comment by jingxu97** [comment]
@saad-ali @matchstick , I don't think this PR is completely fixed. @29077 is a related fix but it does not fix what described in this PR. Reopen it.

**Comment by saad-ali** [comment]
Good catch Jing. This issue is a follow-up on https://github.com/kubernetes/kubernetes/pull/29077#issuecomment-233876450 and these suggestions have not yet been implemented so the issue should remain open.
