### ISSUE TITLE
kubelet /etc/resolv.conf should drop duplicate search domains

### ISSUE THREAD

**Issue by mattymo** [kubernetes/kubernetes#29270]
Kubernetes version v1.3.0

Kubelet concatenates host /etc/resolv.conf and cluster domain entries for my pod, resulting in an invalid config (too many entries with duplicates). The max is only 6 search domains. Any more and DNS resolution breaks when trying to leverage search domains.

The example below has only cluster DNS entries, but illustrates the issue:

Host /etc/resolv.conf:
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.233.0.2
nameserver 10.90.0.1
options timeout:2
options attempts:2

Container /etc/resolv.conf:
kubectl run -i --tty busybox --image=busybox -- sh
(skip waiting text)
/ # cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.233.0.2
options attempts:2
options ndots:5

I should be enable cluster DNS config in my host DNS settings and still have functional pod DNS. Kubelet should be intelligent enough to filter out duplicate search domain entries (or drop search domains beyond the 6th entry)

**Comment by Oloremo** [comment]
I think some sane checks needs to be added too. libc limits search field to 6 records and 255(?) characters. This limitation should be checked before resolv.conf creation.

**Comment by vefimova** [comment]
Hey guys, I'm working on it.

**Comment by thockin** [comment]
Dup of #9229
