### ISSUE TITLE
kubectl -n should support both `-n namespace/yournamespace` and `-n yournamespace`

### ISSUE THREAD

**Issue by rhcarvalho** [kubernetes/kubernetes#29271]
## Summary

Because `kubectl get ns -o name` always return names with a prefix like `namespace/default`, it cannot be directly used to iterate over all namespaces to execute other commands.
## Version

I've compiled from source:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.0.661+d4ae9ca53dc88a-dirty", GitCommit:"d4ae9ca53dc88aa43c7b2fcc2a6aab1105746f0a", GitTreeState:"dirty", BuildDate:"2016-06-23T17:02:00Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.3.0-alpha.3-599-g2746284", GitCommit:"2fe486f", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.5.4", Compiler:"gc", Platform:"linux/amd64"}
```
## Details

Reviewing some scripts, I came across a usage of `kubectl` like this:

```
kubectl get ns -o jsonpath='{.items[*].metadata.name}'
```

That line fetches namespace names to later run in a `for` loop:

```
kubectl -n "${ns}" get pods -o json > "${ns}/pods.json"
```

That seemed to be a perfect use case for the `-o name` flag, but it can't be used without extra hacks to get rid of the `namespace/` prefix (FWIW, `kubectl -n namespace/default ...` is invalid).
## Proposed solution

Changing the current output of `kubectl get ns -o name` might not be possible or desirable, for this could impact existing users that rely on the output format.

If I'm wrong about the above limitation, than it would make sense to output just the name when `-o name` and there is a single resource type, while using the ideas introduced in #27379 to show the resource type  only when there is more than one type in the output, or when `--show-kind` is explicitly set.
### Example

Before:

``` console
$ kubectl get ns -o name
namespace/default
namespace/demo
```

After:

``` console
$ kubectl get ns -o name
default
demo
```

``` console
$ kubectl get ns -o name --show-kind
namespace/default
namespace/demo
```

``` console
$ kubectl get ns,svc -o name
namespace/default
namespace/demo
service/mysql
```

**Comment by rhcarvalho** [comment]
@ncdc could you help me ping the appropriate team to triage this? Thanks!

**Comment by apelisse** [comment]
Please re-post your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by rhcarvalho** [comment]
@apelisse perhaps I didn't do a good job at explaining the problem, but this is not a question of how to do something, but a report on a problem with the CLI design.

**Comment by apelisse** [comment]
Sorry about that :-/. I'll try to route to the proper team.

**Comment by rhcarvalho** [comment]
update: added console examples to the description.

**Comment by pwittrock** [comment]
@rhcarvalho the -o format is designed for scripting, the use case is just different from yours.  You should be able to paste the output of `-o name` into `kubectl get`.  Does `kubectl get ns -o jsonpath='{.items[*].metadata.name}'` do what you want?  If this is a common use case we could create another -o flag value.

**Comment by rhcarvalho** [comment]
@pwittrock the use cases I've observed doing code reviews:

1. Iterate over all namespaces to get certain resources from that namespace:

  ```bash
  for ns in $(kubectl get ns -o jsonpath='{.items[*].metadata.name}'); do
    for kind in pods services; do
      mkdir -p "definitions/${ns}"
      kubectl -n "${ns}" get "${kind}" -o json > "definitions/${ns}/${kind}.json"
    done
  done
```

2. Iterate over all namespaces, then iterate of over resource types that produce logs and fetch logs one by one:

  ```bash
  for ns in $(kubectl get ns -o jsonpath='{.items[*].metadata.name}'); do
    for pod in $(kubectl -n "${ns}" get pods -o name); do
      mkdir -p "logs/${ns}"
      kubectl -n "${ns}" logs "${pod}" --tail=1000 > "logs/${ns}/${pod/\//_}.log"
    done
  done
```

  Above we can use `-o name` for listing pods because later we'll pass it to `kubectl logs` that accept the `type/name` syntax. We cannot do the same for namespaces, because `kubectl -n` doesn't like the `namespace/foo` format.

**Comment by pwittrock** [comment]
Alternatively we could be kubectl recognize `-n namespace/default` as valid

**Comment by maciaszczykm** [comment]
I'll take a look on it if it's not taken by anyone yet.

CC @cheld

**Comment by pwittrock** [comment]
@maciaszczykm Have you started this?

**Comment by maciaszczykm** [comment]
@pwittrock Only investigated due to being out of office since Thursday last week. I can work on it in upcoming week, but I'll understand if it's piority issue and you'll reassign it.

**Comment by maciaszczykm** [comment]
I'll create pull request soon to discuss proposed solution.

**Comment by maciaszczykm** [comment]
I've got code proposal, but it needs tests to finish. I'll open pull request tomorrow.

**Comment by maciaszczykm** [comment]
Ready :-)

**Comment by rhcarvalho** [comment]
@kubernetes/sig-cli-misc
