### ISSUE TITLE
Node.metadata.uid != Event.involvedObject.uid for event of the same Node

### ISSUE THREAD

**Issue by moolitayer** [kubernetes/kubernetes#29289]
event.involvedObject.uid seems incorrect as it contains  Node.metadata.name. other times  it is missing entirely.

Based on an [issue](https://github.com/ManageIQ/manageiq/issues/9600) reported in ManageIQ. (see [comment](https://github.com/ManageIQ/manageiq/issues/9600#issuecomment-233879235) for rest output)

**Comment by moolitayer** [comment]
@deads2k @smarterclayton Could you confirm if this is indeed an issue?

**Comment by cben** [comment]
We also found this code:
https://github.com/kubernetes/kubernetes/blob/0f1a3587a2cc72279973cb5a4bf361d263dc0a4d/pkg/controller/node/controller_utils.go#L245-L259
which explicitly uses node name as uid in events.

**Comment by smarterclayton** [comment]
Yes that looks like a bug to me.

**Comment by smarterclayton** [comment]
Bumping this to p1 to start since it means events can't be associated with the correct node instance (which may be an issue for audit)

**Comment by AdoHe** [comment]
@smarterclayton I just get a little bit confused, I think not only here even in kubelet, the `nodeRef.UID` would be nodeName, is this right?

**Comment by smarterclayton** [comment]
I think the nodeRef.UID should be whatever value is assigned by the API server when the node is created, which is not directly settable by the node.

**Comment by cben** [comment]
IIUC https://github.com/kubernetes/kubernetes/blob/master/docs/design/identifiers.md 
"UIDs" should be unique in space and time, distinguishing today's node named "foo.example.com" from next week's other node reusing the same name...

nodes do have a good Node.metadata.uid:
```
# kubectl get node -o yaml | head -n17
apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    creationTimestamp: 2016-03-01T12:19:55Z
    labels:
      kubernetes.io/hostname: vm-test-02.example.com
      region: infra
      zone: default
    name: vm-test-02.example.com
    resourceVersion: "1318293"
    selfLink: /api/v1/nodes/vm-test-02.example.com
    uid: e81582b9-dfa7-11e5-af89-525400c7c086
  spec:
    externalID: vm-test-02.example.com
  status:

# kubectl version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v1.2.0-origin", GitCommit:"f0cd09a", GitTreeState:"not a git tree"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.2.0-origin", GitCommit:"f0cd09a", GitTreeState:"not a git tree"}
```

It's just that the ref in events (at least ones I saw) doesn't include it.

**Comment by cben** [comment]
Also reproducable on v1.3.2 (master didn't build for me):
https://gist.github.com/cben/821cee393fff7e319a2031d4b015cbdb

**Comment by moolitayer** [comment]
Reproduces on master on my machine:
"gitVersion": "v1.4.0-alpha.1.491+ecebdb570739ec-dirty",
"gitCommit": "ecebdb570739ec0a37368a25d895e5a8e10036db"

Event:
```
{
      "metadata": {
        "name": "127.0.0.1.14634b7a6a4f32e3",
        "namespace": "default",
        "selfLink": "/api/v1/namespaces/default/events/127.0.0.1.14634b7a6a4f32e3",
        "uid": "23edd6a7-4f37-11e6-96b0-54ee7547f1b9",
        "resourceVersion": "11",
        "creationTimestamp": "2016-07-21T11:34:52Z"
      },
      "involvedObject": {
        "kind": "Node",
        "name": "127.0.0.1",
        "uid": "127.0.0.1"
      },
```

Node:
```
{
      "metadata": {
        "name": "127.0.0.1",
        "selfLink": "/api/v1/nodes/127.0.0.1",
        "uid": "244f97d4-4f37-11e6-96b0-54ee7547f1b9",
        
```

**Comment by AdoHe** [comment]
@cben @moolitayer yes, node uid is generated in server side, you can see [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/rest/create.go#L71) and [here](https://github.com/kubernetes/kubernetes/blob/a0a07600273c6b901d8c3d6dc3ff7c7bbbd9f1fa/pkg/api/meta.go#L30), so in controller-manager, typically we can get this value.

**Comment by AdoHe** [comment]
@smarterclayton @cben @moolitayer I just opened a PR #29437 to fix this, ptal.

**Comment by cben** [comment]
Rebuilt from current master.  [Same results](https://gist.github.com/cben/b1258fbedd4c00eda80944be80b2ce9d) as [here](https://github.com/kubernetes/kubernetes/pull/29437#issuecomment-234926478) — after starting hack/local-up-cluster.sh, 
"Registered Node" event has good uid, 
but "Starting kube-proxy", kubelet", and "status is now: ..." events all have uid == name.

@AdoHe you wrote there:

> From the link you give, I can see that events generated by kubelet and kube-proxy still use nodeName as nodeUID, this is right, as uid is generated in server side.

Do you mean these *should not* be fixed, or should but are harder to fix?  Can I help?
Ideally a user shouldn't "care" where exactly events were generated; if they pertain to same node they'd carry the same uid.

Aren't kubelet & kube-proxy told details of the node they run on?

Let's see.
kube-proxy apparently creates only 2 node events:
```
$ grep -n -B1 -i -R 'event.*node' cmd/kube-proxy/
cmd/kube-proxy/app/server.go-318-				const message = "DOCKER RESTART NEEDED (docker issue #24000): /sys is read-only: can't raise conntrack limits, problems may arise later."
cmd/kube-proxy/app/server.go:319:				s.Recorder.Eventf(s.Config.NodeRef, api.EventTypeWarning, err.Error(), message)
--
cmd/kube-proxy/app/server.go-409-func (s *ProxyServer) birthCry() {
cmd/kube-proxy/app/server.go:410:	s.Recorder.Eventf(s.Config.NodeRef, api.EventTypeNormal, "Starting", "Starting kube-proxy.")
```
but kubelet has many:
```
$ grep -n -i -R 'event.*node' pkg/kubelet/
pkg/kubelet/images/image_gc_manager.go:106:func NewImageGCManager(runtime container.Runtime, cadvisorInterface cadvisor.Interface, recorder record.EventRecorder, nodeRef *api.ObjectReference, policy ImageGCPolicy) (ImageGCManager, error) {
pkg/kubelet/images/image_gc_manager.go:230:		im.recorder.Eventf(im.nodeRef, api.EventTypeWarning, events.InvalidDiskCapacity, err.Error())
pkg/kubelet/images/image_gc_manager.go:246:			im.recorder.Eventf(im.nodeRef, api.EventTypeWarning, events.FreeDiskSpaceFailed, err.Error())
pkg/kubelet/eviction/eviction_manager.go:53:	// used to record events about the node
pkg/kubelet/eviction/eviction_manager.go:217:	m.recorder.Eventf(m.nodeRef, api.EventTypeWarning, "EvictionThresholdMet", "Attempting to reclaim %s", resourceToReclaim)
pkg/kubelet/kubelet.go:959:		kl.recorder.Eventf(kl.nodeRef, api.EventTypeWarning, events.KubeletSetupFailed, err.Error())
pkg/kubelet/kubelet.go:1455:		kl.recorder.Eventf(kl.nodeRef, api.EventTypeWarning, "MissingClusterDNS", log)
pkg/kubelet/kubelet.go:2939:	kl.recorder.Eventf(kl.nodeRef, api.EventTypeNormal, events.StartingKubelet, "Starting kubelet.")
pkg/kubelet/kubelet_node_status.go:279:	glog.V(2).Infof("Recording %s event message for node %s", event, kl.nodeName)
pkg/kubelet/kubelet_node_status.go:282:	kl.recorder.Eventf(kl.nodeRef, eventtype, event, "Node %s status is now: %s", kl.nodeName, event)
pkg/kubelet/kubelet_node_status.go:373:			kl.recorder.Eventf(kl.nodeRef, api.EventTypeWarning, events.NodeRebooted,
pkg/kubelet/kubelet_node_status.go:515:			kl.recordNodeStatusEvent(api.EventTypeNormal, events.NodeReady)
pkg/kubelet/kubelet_node_status.go:517:			kl.recordNodeStatusEvent(api.EventTypeNormal, events.NodeNotReady)
pkg/kubelet/kubelet_node_status.go:563:			kl.recordNodeStatusEvent(api.EventTypeNormal, "NodeHasInsufficientMemory")
pkg/kubelet/kubelet_node_status.go:571:			kl.recordNodeStatusEvent(api.EventTypeNormal, "NodeHasSufficientMemory")
pkg/kubelet/kubelet_node_status.go:621:			kl.recordNodeStatusEvent(api.EventTypeNormal, "NodeHasDiskPressure")
pkg/kubelet/kubelet_node_status.go:629:			kl.recordNodeStatusEvent(api.EventTypeNormal, "NodeHasNoDiskPressure")
pkg/kubelet/kubelet_node_status.go:678:			kl.recordNodeStatusEvent(api.EventTypeNormal, "NodeOutOfDisk")
pkg/kubelet/kubelet_node_status.go:690:				kl.recordNodeStatusEvent(api.EventTypeNormal, "NodeHasSufficientDisk")
pkg/kubelet/kubelet_node_status.go:707:func (kl *Kubelet) recordNodeSchedulableEvent(node *api.Node) {
pkg/kubelet/kubelet_node_status.go:710:			kl.recordNodeStatusEvent(api.EventTypeNormal, events.NodeNotSchedulable)
pkg/kubelet/kubelet_node_status.go:712:			kl.recordNodeStatusEvent(api.EventTypeNormal, events.NodeSchedulable)
```

**Comment by AdoHe** [comment]
```
Do you mean these should not be fixed, or should but are harder to fix?
```
@smarterclayton what do you think about this? kubelet&kube-proxy still use node name as node uid when report event. I know the uid is generated in server side, but kubelet can get this after sync with apiserver, maybe we should use uid after we get it.
