### ISSUE TITLE
Ensure container prestop hooks are run before a machine shuts down

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#29292]
This is a GKE user request. They want the prestop hooks to be run before the machine shutdown. 

For planned machine shutdowns, one can simply drain the pods from the nodes. In which case, kubelet will execute prestop hooks. The only exception is the DaemonSet pods, but this will be resolved after #1574 is implemented.

For unexpected shutdowns, things are more complicated. @roberthbailey mentioned that " We've discussed the option of adding a shutdown.sh script to all nodes which would try to cleanly shut the machine down, but I don't think the kubelet exposes an API that it could even call to start gracefully terminating pods. And draining the machine wouldn't have any effect on a DaemonSet because they don't get drained (since they are pinned to machines). "

We may want to consider adding a mechanism to trigger kubelet to gracefully terminate all pods on the node. 

/cc @roberthbailey @davidopp

**Comment by davidopp** [comment]
I'm not convinced this is a good thing to put into Kubelet. It seems that for "expected shutdowns" you should be able to do a normal drain, while for "unexpected shutdowns" you don't have time to drain since it is unexpected?

**Comment by roberthbailey** [comment]
We could add a shutdown script that calls into the apiserver and asks in to drain the node rather than adding an api endpoint to the kubelet. 

In GCE (at least), the VM will give you a chance to do a graceful termination when the VM is getting shut down so if you resize a MIG down we could get better behavior than we currently have (there will still be cases for an unexpected shutdown, e.g. kernel panic).

**Comment by davidopp** [comment]
I'm still not convinced. IMO node drain should be orchestrated by the Kubernetes control plane. The thing that is triggering shutdown should call into the API server to trigger the drain, which (once we implement server-side drain) can choose the "best" node to drain and/or the best drain schedule according to disruption budget, grace period, and other considerations. The post-drain actions can be handled outside of Kubernetes but I don't think draining should be.

For the GCE case, then, people (and automation) should be just be resizing the MIG down, they should be asking the Kubernetes control plane to drain the node (or a node) and only then do the resize.

**Comment by yujuhong** [comment]
> shutdown script that calls into the apiserver and asks in to drain the node

> The thing that is triggering shutdown should call into the API server to trigger the drain,

@davidopp @roberthbailey It looks to me that you two actually agreed on *something* should call into the apiserver and ask it to drain the node. Am I missing something?

**Comment by davidopp** [comment]
Yes, I think @roberthbailey and I are basically agreeing, the only difference is whether the VM shutdown script calls into the API server or the MIG resizer calls into the API server.

**Comment by JordanP** [comment]
I am also looking into something similar. I am running on GKE, I mainly uses daemonset and used the managed instances groups autoscaler to scale horizontally my GKE cluster. I'd like somehow my pod or my node to get informed when the MIG is going to "kill me" because of a scaledown event.
