### ISSUE TITLE
e2e test flake: namespace xyz was not deleted within limit: timed out waiting for the condition, pods remaining: []

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#29308]
I've noticed at least 10 separate test flake issues open in which at least one failure looks like this:

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:128
Jul 20 11:12:15.579: Couldn't delete ns "e2e-tests-kubectl-2k86f": namespace e2e-tests-kubectl-2k86f was not deleted within limit: timed out waiting for the condition, pods remaining: []
```

Current list: https://github.com/kubernetes/kubernetes/issues?utf8=✓&q=is%3Aissue%20label%3Akind%2Fflake%20is%3Aopen%20%22was%20not%20deleted%20within%20limit%22

The 10 current issues (note that some are 'broken test run' issues and might have multiple failure causes):

#28827 
#28722 
#28656 
#28514 
#28440 
#28413 
#28383 
#27524 
#27503 
#26982

cc @derekwaynecarr @wojtek-t

**Comment by yujuhong** [comment]
Just to clarify, the pods were deleted in the test (hence the `pods remaining: [ ]` message).
I mentioned this before in https://github.com/kubernetes/kubernetes/issues/26982#issuecomment-233484093

**Comment by derekwaynecarr** [comment]
I was chasing down another p0 but now that that is resolved will try to
look for more that we can do here.

**Comment by wojtek-t** [comment]
@fejta - why did you close this - this is happening quite frquently.

**Comment by fejta** [comment]
Thanks for reopening!

We will now automatically choose and owner for auto-opened flake issues. I closed a bunch of old flakes that were created with no assignee. I want them to get recreated with an assignee. The hope is someone will actually look at these.

**Comment by yujuhong** [comment]
#30867 is another example of this flake.

**Comment by yujuhong** [comment]
#30862 has the same symptom too.

**Comment by yujuhong** [comment]
One more example: https://github.com/kubernetes/kubernetes/issues/31041

@derekwaynecarr, would it help if we bump the timeout from 5 min to N (e.g., 8) min? or should we ask tests that create significant number of pods to clean up after themselves?

**Comment by derekwaynecarr** [comment]
I am going to try and look at optimizing the requeue behavior for tests that have a lot of pods and we are waiting for them to delete.  Looks like once they delete, we don't observe their deletion until the next resync

**Comment by derekwaynecarr** [comment]
Opened a PR to improve e2e framework ns deletion to avoid duplicate ns delete operations, and to give more detailed information on what content did not actually get deleted.
