### ISSUE TITLE
Failure in creating service & deployment still creates deployment

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes#29307]
While testing out kubectl run, I ran into a non-obvious behavior:

```
$ kubectl run hello-node --image=aronchick/hello-node:2.0 --port=8080 --expose=true
Error from server: services "hello-node" already exists
$ kubectl delete svc hello-node
service "hello-node" deleted
$ kubectl run hello-node --image=aronchick/hello-node:2.0 --port=8080 --expose=true
Error from server: deployments.extensions "hello-node" already exists
```

It appears that the first deployment was actually created, though I wasn't given any indication and, when the service deployment failed, it wasn't rolled back. Either would be acceptable.

**Comment by lojies** [comment]
`$ kubectl run hello-node --image=aronchick/hello-node:2.0 --port=8080 --expose=true`
this will create a service and deployment.
`Error from server: services "hello-node" already exists`
this error was returned because service existed.in fact the deployment was existed too.
`$ kubectl delete svc hello-node` 
this only deleted svc but deployment was left so the next err was reported.

So i think both service and deployment should be checked when `kubectl run ...... --expose=true` is run, then gives all errors .

**Comment by nagarjung** [comment]
Hi @aronchick @lojies what is the status of the issue? Is the issue reproducible? If yes could you please help me to know the steps to reproduce.

**Comment by aronchick** [comment]
Hi @nagarjung - did the steps in the initial bug not repro for you?

**Comment by zreigz** [comment]
You should use the following command to delete hello-node:
`
kubectl delete deployment hello-node
`
It is described here:
https://github.com/kubernetes/kubernetes/issues/23406

**Comment by stu-gott** [comment]
I'd like to take a stab at fixing this

**Comment by shahidhk** [comment]
Is this still relevant? `kubectl run` along with `expose` creates a `deployment` and a `service`. If one them fails, should the other one be rolled back? Is that what is intended out of this issue? 

```bash
$ kubectl run hello-node --image=aronchick/hello-node:2.0 --port=8080 --expose=true
service "hello-node" created
deployment "hello-node" created
```
Since the output from the command clearly says what is created and what is not, a rollback by deleting the created objects manually will also work.

@pwittrock Can you please suggest if automatic deleting should be implemented?

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by kargakis** [comment]
I think `run` shouldn't try to cleanup if something failed but we should make sure we get the correct output at all times.

**Comment by pwittrock** [comment]
@shahidhk I don't think we should automatically delete the deployment if creating the service fails.  We should update the error message when creating a service fails (as part of run) to say the deployment was created, but the service creation failed.

**Comment by spzala** [comment]
@aronchick I could recreate the issue with 1.7 and latest upstream.

@pwittrock Agree, I guess we should cover following scenarios with new messages. I am using the command @aronchick tried as an example:

1. First case - user re-run “run” with “expose” when both deployment and service are exist:

``` $kubectl run hello-node --image=aronchick/hello-node:2.0 --port=8080 --expose=true
Desired output message:
Error from server (AlreadyExists): deployments.extensions "hello-node" already exists
Error from server (AlreadyExists): services "hello-node" already exists  (**add NEW**)```

2. Second case - user has deleted deployment and re-run “run” with “expose”:

``` $ kubectl run hello-node --image=aronchick/hello-node:2.0 --port=8080 --expose=true
Desired output message:
deployment "hello-node" created (**add NEW**)
Error from server (AlreadyExists): services "hello-node" already exists  (**add NEW**) ```

3. Third case: User had deleted service but still has deployment:

``` $ kubectl run hello-node --image=aronchick/hello-node:2.0 --port=8080 --expose=true
Desired output message:
service "hello-node" created (**add NEW**)
Error from server (AlreadyExists): deployments.extensions "hello-node" already exists ```

**Comment by ankitgoelcmu** [comment]
Is this fixed yet. I am also facing the same issue

**Comment by projecthubble** [comment]
I am running into this problem too. I am running qinikube and running couple of deployments. Now I can't do kubectl delete deployment to remove them. I have tried stopping and starting minikube and the pods come back again (they are persistent). I have tried rebooting and still persistent.

Is there a way to clean up all the deployments and start fresh ?

**Comment by zjj2wry** [comment]
@projecthubble 
I think the problem you said may not be the same as this one. This describes the issue of consistency kubectl run, your problem seems to be deployment can not be deleted. Can you copy the deleted log to this issue?
```
kubectl delete -v 10
```

**Comment by projecthubble** [comment]
Thanks for the response.
Perhaps its a different problem, but this was the best thread I found that was related. So posted it here.
I was trying to delete deployment as my minikube was not able to get to images from google cloud, but all my pods became persistent. Now I cant delete the other pods too. 

Here are the logs attached.
[XXX@localhost kubernetes]$ kubectl delete deployment/my-hello
Error from server (NotFound): deployments.extensions "my-hello" not found
[XXX@localhost kubernetes]$ kubectl get pods
NAME                            READY     STATUS             RESTARTS   AGE
gcr-my-hello-2780611139-9vies   0/1       ImagePullBackOff   0          2h
my-hello-3834886608-shlh5       0/1       CrashLoopBackOff   28         2h
my-hello-3834886608-u946o       0/1       CrashLoopBackOff   29         2h
my-hello-3834886608-wticc       0/1       CrashLoopBackOff   28         2h
[XXX@localhost kubernetes]$ kubectl delete deployment/my-hello -v 10
I0204 18:13:48.647373   26559 loader.go:357] Config loaded from file /home/XXX/.kube/config
I0204 18:13:48.650192   26559 cached_discovery.go:117] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/servergroups.json
I0204 18:13:48.650650   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/apps/v1alpha1/serverresources.json
I0204 18:13:48.650728   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/autoscaling/v1/serverresources.json
I0204 18:13:48.650800   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/batch/v1/serverresources.json
I0204 18:13:48.651006   26559 round_trippers.go:417] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.9.2 (linux/amd64) kubernetes/5fa2db2" https://192.168.99.100:8443/apis/batch/v2alpha1
I0204 18:13:48.732595   26559 round_trippers.go:436] GET https://192.168.99.100:8443/apis/batch/v2alpha1 200 OK in 81 milliseconds
I0204 18:13:48.732636   26559 round_trippers.go:442] Response Headers:
I0204 18:13:48.732656   26559 round_trippers.go:445]     Content-Length: 94
I0204 18:13:48.732681   26559 round_trippers.go:445]     Date: Mon, 05 Feb 2018 02:13:48 GMT
I0204 18:13:48.732707   26559 round_trippers.go:445]     Content-Type: application/json
I0204 18:13:48.843478   26559 request.go:873] Response Body: {"kind":"APIResourceList","apiVersion":"v1","groupVersion":"batch/v2alpha1","resources":null}
I0204 18:13:48.895218   26559 cached_discovery.go:81] skipped caching discovery info, no resources found
I0204 18:13:48.895586   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/extensions/v1beta1/serverresources.json
I0204 18:13:48.895742   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/policy/v1alpha1/serverresources.json
I0204 18:13:48.895882   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/rbac.authorization.k8s.io/v1alpha1/serverresources.json
I0204 18:13:48.896294   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/v1/serverresources.json
I0204 18:13:48.896637   26559 cached_discovery.go:117] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/servergroups.json
I0204 18:13:48.896764   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/apps/v1alpha1/serverresources.json
I0204 18:13:48.896892   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/autoscaling/v1/serverresources.json
I0204 18:13:48.897011   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/batch/v1/serverresources.json
I0204 18:13:48.897310   26559 round_trippers.go:417] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.9.2 (linux/amd64) kubernetes/5fa2db2" https://192.168.99.100:8443/apis/batch/v2alpha1
I0204 18:13:48.899569   26559 round_trippers.go:436] GET https://192.168.99.100:8443/apis/batch/v2alpha1 200 OK in 2 milliseconds
I0204 18:13:48.899609   26559 round_trippers.go:442] Response Headers:
I0204 18:13:48.899626   26559 round_trippers.go:445]     Content-Length: 94
I0204 18:13:48.899641   26559 round_trippers.go:445]     Date: Mon, 05 Feb 2018 02:13:48 GMT
I0204 18:13:48.899655   26559 round_trippers.go:445]     Content-Type: application/json
I0204 18:13:48.960492   26559 request.go:873] Response Body: {"kind":"APIResourceList","apiVersion":"v1","groupVersion":"batch/v2alpha1","resources":null}
I0204 18:13:48.978109   26559 cached_discovery.go:81] skipped caching discovery info, no resources found
I0204 18:13:48.978408   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/extensions/v1beta1/serverresources.json
I0204 18:13:48.978541   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/policy/v1alpha1/serverresources.json
I0204 18:13:48.978661   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/rbac.authorization.k8s.io/v1alpha1/serverresources.json
I0204 18:13:48.978996   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/v1/serverresources.json
I0204 18:13:48.979254   26559 cached_discovery.go:117] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/servergroups.json
I0204 18:13:48.979380   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/apps/v1alpha1/serverresources.json
I0204 18:13:48.979501   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/autoscaling/v1/serverresources.json
I0204 18:13:48.979638   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/batch/v1/serverresources.json
I0204 18:13:48.979906   26559 round_trippers.go:417] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.9.2 (linux/amd64) kubernetes/5fa2db2" https://192.168.99.100:8443/apis/batch/v2alpha1
I0204 18:13:48.994988   26559 round_trippers.go:436] GET https://192.168.99.100:8443/apis/batch/v2alpha1 200 OK in 15 milliseconds
I0204 18:13:48.995058   26559 round_trippers.go:442] Response Headers:
I0204 18:13:48.995072   26559 round_trippers.go:445]     Content-Type: application/json
I0204 18:13:48.995082   26559 round_trippers.go:445]     Content-Length: 94
I0204 18:13:48.995092   26559 round_trippers.go:445]     Date: Mon, 05 Feb 2018 02:13:48 GMT
I0204 18:13:49.035641   26559 request.go:873] Response Body: {"kind":"APIResourceList","apiVersion":"v1","groupVersion":"batch/v2alpha1","resources":null}
I0204 18:13:49.069658   26559 cached_discovery.go:81] skipped caching discovery info, no resources found
I0204 18:13:49.069999   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/extensions/v1beta1/serverresources.json
I0204 18:13:49.070176   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/policy/v1alpha1/serverresources.json
I0204 18:13:49.070325   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/rbac.authorization.k8s.io/v1alpha1/serverresources.json
I0204 18:13:49.070676   26559 cached_discovery.go:70] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/v1/serverresources.json
I0204 18:13:49.073436   26559 cached_discovery.go:117] returning cached discovery info from /home/XXX/.kube/cache/discovery/192.168.99.100_8443/servergroups.json
I0204 18:13:49.087175   26559 round_trippers.go:417] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.9.2 (linux/amd64) kubernetes/5fa2db2" https://192.168.99.100:8443/apis/extensions/v1beta1/namespaces/default/deployments/my-hello
I0204 18:13:49.090504   26559 round_trippers.go:436] GET https://192.168.99.100:8443/apis/extensions/v1beta1/namespaces/default/deployments/my-hello 404 Not Found in 3 milliseconds
I0204 18:13:49.090554   26559 round_trippers.go:442] Response Headers:
I0204 18:13:49.090575   26559 round_trippers.go:445]     Content-Type: application/json
I0204 18:13:49.090592   26559 round_trippers.go:445]     Content-Length: 230
I0204 18:13:49.090608   26559 round_trippers.go:445]     Date: Mon, 05 Feb 2018 02:13:49 GMT
I0204 18:13:49.091085   26559 request.go:873] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"deployments.extensions \"my-hello\" not found","reason":"NotFound","details":{"name":"my-hello","group":"extensions","kind":"deployments"},"code":404}
I0204 18:13:49.092343   26559 helpers.go:201] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "deployments.extensions \"my-hello\" not found",
  "reason": "NotFound",
  "details": {
    "name": "my-hello",
    "group": "extensions",
    "kind": "deployments"
  },
  "code": 404
}]
F0204 18:13:49.092386   26559 helpers.go:119] Error from server (NotFound): deployments.extensions "my-hello" not found

**Comment by zjj2wry** [comment]
@projecthubble 
Try to delete rs to see if the pod can be deleted

**Comment by zjj2wry** [comment]
@ankitgoelcmu this issues have fixed, you can fetch master branch verify it. thanks

**Comment by gudipatisaikrishna92** [comment]
can any just suggest me how to over come the error 
$kubectl expose deployment hello-minikube --type=NodePort service "hello-minikube" exposed
service "hello-minikube" exposed
Error from server (NotFound): deployments.extensions "service" not found

**Comment by webwurst** [comment]
I bet the versions of your `kubectl` and the `kube-apiserver` differ too much. And just as a heads-up, http://slack.k8s.io/, https://groups.google.com/forum/#!forum/kubernetes-users or http://stackoverflow.com/questions/tagged/kubernetes would be better places to ask these kind of questions.
