### ISSUE TITLE
Move mungedocs

### ISSUE THREAD

**Issue by Kashomon** [kubernetes/kubernetes#29314]
Now that the docs are in kubernetes.github.io, I think it makes sense to move the mungedocs program and fix it up: (found here: https://github.com/kubernetes/kubernetes/tree/master/cmd/mungedocs)

Thoughts about where it should go?
- New repo (kubernetes/mungedocs)
- Into kubernetes.github.io directly
- Into kubernetes/contrib. This is my least favorite of the options since contrib is currently a general purpose dumping ground.

**Comment by bgrant0607** [comment]
Yes, both kubernetes and contrib repos are dumping grounds.

I was thinking we should create a "github-tools" repo for mungedocs, mungegithub, etc.

The process @philips proposed [on kubernetes-dev](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-dev/o6E1u-orDK8/SAqal_CeCgAJ) suggested emailing the proposal to kubernetes-dev.

cc @kubernetes/docs @kubernetes/contributor-experience

**Comment by bgrant0607** [comment]
Note that the docs in kubernetes.github.io have different formatting rules/needs than docs in other repos. The reason is that the kubernetes.github.io docs are converted to html and rendered with CSS+JS, whereas the other docs are viewed directly as markdown. One example is TOC generation, which is done dynamically for kubernetes.io and statically for markdown.  Link-checking rules are different, too.

I think the previous attempt by @pwittrock was in https://github.com/kubernetes/contrib/pull/590

**Comment by bgrant0607** [comment]
Proposed kubernetes.github.io checks:
https://github.com/kubernetes/kubernetes.github.io/issues/731
https://github.com/kubernetes/kubernetes.github.io/issues/732
https://github.com/kubernetes/kubernetes.github.io/issues/733
https://github.com/kubernetes/kubernetes.github.io/issues/734
https://github.com/kubernetes/kubernetes.github.io/issues/735
https://github.com/kubernetes/kubernetes.github.io/issues/736
https://github.com/kubernetes/kubernetes.github.io/issues/737
https://github.com/kubernetes/kubernetes.github.io/issues/738

**Comment by spiffxp** [comment]
@david-mcmahon is `cmd/mungedocs` even used anymore?  I looked through community, contrib, kubernetes, kubernetes.github.io, release, and test-infra and couldn't find an actual call.

ref: #38309

**Comment by spiffxp** [comment]
I take that back, pinged on #sig-release in slack, apparently it's still used via travis for kubernetes.github.io

https://github.com/kubernetes/kubernetes.github.io/blob/2f82ff8a96bcf009fed4507100a1ade55de7fdc5/.travis.yml#L29

**Comment by spiffxp** [comment]
/close
This was done
https://github.com/kubernetes/website/pull/5178 - moved it to kubernetes/website
https://github.com/kubernetes/website/pull/5191 - removed it from kubernetes/website
