### ISSUE TITLE
Pods should not be able to mount arbitrary host volumes

### ISSUE THREAD

**Issue by mfischer-zd** [kubernetes/kubernetes#29326]
Kubernetes administrators should be able to constrain through policies which (if any) host volumes are mountable by a pod.  Otherwise, pods can obtain access to sensitive data on the host (certificates and so forth) that an administrator might not want them to have access to.

**Comment by dims** [comment]
@mfischer-zd switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree)

**Comment by mfischer-zd** [comment]
It's not impacting us just yet, so I don't object.

**Comment by davidopp** [comment]
[PodSecurityPolicy](http://kubernetes.io/docs/user-guide/pod-security-policy/) allows you to control which volume types are allowed, but I guess your use case is that you want to allow host volumes in general but limit access to particular paths?

**Comment by mfischer-zd** [comment]
> I guess your use case is that you want to allow host volumes in general but limit access to particular paths?

Precisely.  `/etc/shadow` on the host contains sensitive data, for example.

**Comment by timstclair** [comment]
Also `/var/lib/kubelet`, which includes the kubelet credentials.

**Comment by kargakis** [comment]
Seems like something that should be managed by PSP @pweil- @php-coder ?

**Comment by pweil-** [comment]
> Seems like something that should be managed by PSP @pweil- @php-coder ?

Yes, this would fall in the realm of PSP IMO.  Right now it is an on/off for the volume type but I could imagine the use case for having specific allowed directories.
