### ISSUE TITLE
Federation: Cloud resources (DNS records) need to be cleaned up in CI environments.

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#29335]
1. We don't generally want to delete the DNS records created by the Federated Service Controller when it terminates, as this might break the clients of those federated services in real-world scenarios (e.g. upgrades of the federation control plane).
2. But we do need an easy way to delete all of the records created in some cases (e.g. after a CI test run).

Currently there are over 4,000 DNS records in left over in the project that our CI tests run in.  We will presumably eventually hit some sort of quota limit there.

A few options available.
1. write an independent tool which can delete all of the DNS records in a given DNS zone, and invoke that automatically after our CI test runs.
2. systematically delete all of the created federated services as part of our tests, and ensure that the service controller deletes all of the DNS records when that happens.
   ...

**Comment by pwittrock** [comment]
@quinton-hoole @madhusudancs 

I am moving this out of the blocking issues we are tracking for the 1.4 release because the unfinished pieces are non-blockers for the release and do not need to be tracked in the burndown meetings.  If there are components besides docs & tests that need to be completed, please move it back to the 1.4 milestone and provide daily status updates.

**Comment by nikhiljindal** [comment]
cc @shashidharatd This is the issue I mentioned in todays SIG meeting

**Comment by shashidharatd** [comment]
thanks @nikhiljindal i will look into this

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#58.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
