### ISSUE TITLE
Federation: Write a brief developer guide for adding a new Federated API object

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#29340]

**Comment by dims** [comment]
switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree)

**Comment by ethernetdan** [comment]
Moving to 1.7 because too late for 1.6. Feel free to move back if this is incorrect.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#59.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
