### ISSUE TITLE
Federation: Services: Plan for going GA

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#29348]
Enumerate blockers for taking Federated Services to General Availability.

Resolve the highest priority items as soon as is practical.

**Comment by dims** [comment]
@quinton-hoole Do we move this to v1.6 milestone?

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by marun** [comment]
Not a release blocker for 1.7.

**Comment by madhusudancs** [comment]
Deferring this to @quinton-hoole 

/unassign
/assign @quinton-hoole

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#60.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
