### ISSUE TITLE
Federation: Common Controller Libraries

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#29347]
As discussed, similar patterns occur in many of the controller for federated objects.  Lift this into a common library that can be used by all of the controllers.

1. Design
2. Implement
3. Test
4. Document

Open separate issues for each of the above, and track there.  This can be the tracking issue over those.

**Comment by huangyuqi** [comment]
Hi, @quinton-hoole , we have been starting develop work about cluster-controller and RS controller, so would you like to share me the plan about this work? Thanks.

**Comment by quinton-hoole** [comment]
Tracked in PR's referenced above.  Closing this tracking issue.
