### ISSUE TITLE
Ingress: Add DNSName to non-Federated Ingress status

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#29344]
As discussed with @bprashanth.  Can be reassigned if necessary.
We need this for Federation in v1.4.

Do we use the same format as services (servicename.namespacename.scv.cluster.local) replacing 'svc' with something else (e.g. 'ing')?  If not, what?

This will also require changes to KubeDNS, to ensure that the name gets published via DNS.  Separate issue for that.

**Comment by quinton-hoole** [comment]
@madhusudancs @bprashanth Is @madhusudancs doing this?

**Comment by madhusudancs** [comment]
May be misunderstand something, but why do we need this in the status? As a reference, we don't do this for services.

**Comment by quinton-hoole** [comment]
@madhusudancs In that case my apologies, I should have checked that first.  Closing as "not required".
