### ISSUE TITLE
Mechanism for running node e2e tests with specific host requirements

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#29346]
As an example, AppArmor will only be enabled on some host images, so to provide AppArmor e2e tests we will need to prevent the tests from running against non-AppArmor hosts.

I suggest we come up with a convention for labeling the tests (e.g. "[node:apparmor]"), and then list the labels in the jenkins properties for each host. Finally, we split the ginkgo command to filter the test based on the labels.

**Comment by timstclair** [comment]
@kubernetes/sig-node

**Comment by vishh** [comment]
Why not run multiple jenkins jobs instead? Or have the test skip itself if
Apparmor is not available? Or pass a distro cookie to the test and have it
run on whitelisted distros?

**Comment by timstclair** [comment]
>Why not run multiple jenkins jobs instead?

We could do this, but I think it's harder to manage than filters on Ginkgo, especially as we need to add more distro-specific tests like this. We would also need to spin up more VMs, but I don't know whether that would be a problem.

>Or have the test skip itself if Apparmor is not available?

This could be a fallback, but I'd like to avoid this sort of automatic detection in tests. The problem is if the detection breaks and the test is always skipped it's hard to notice.

>Or pass a distro cookie to the test and have it run on whitelisted distros?

I prefer this to the above since it's more explicit. However, it seems very similar to the proposal of using labels, but embeds the whitelist in the test rather than keeping the logic by the image definitions. Why do you prefer this approach?

**Comment by Random-Liu** [comment]
> We could do this, but I think it's harder to manage than filters on Ginkgo, especially as we need to add more distro-specific tests like this. We would also need to spin up more VMs, but I don't know whether that would be a problem.

From the node conformance test perspective, If our test is distro-aware, the node conformance test can support more distros. :)

**Comment by timstclair** [comment]
> From the node conformance test perspective, If our test is distro-aware, the node conformance test can support more distros automatically. :)

I don't think anything in the conformance test should be distro dependent. E.g. AppArmor should not be a part of the conformance suite.

**Comment by Random-Liu** [comment]
> I don't think anything in the conformance test should be distro dependent. E.g. AppArmor should not be a part of the conformance suite.

Oh, yeah. You are right. :)

**Comment by Random-Liu** [comment]
Just copied comment from https://github.com/kubernetes/kubernetes/pull/33694, may be useful here.

currently, we have at least 2 signals to address this issue already:
* Node Status (including node system info)
* Kubelet Config (the dynamic configuration effort)

**Comment by spiffxp** [comment]
/sig node
because node e2e

**Comment by tallclair** [comment]
This is still a pain point when writing E2E tests.
