### ISSUE TITLE
e2e tests should surface more meaningful error messages

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#29354]
One of the most common failure signature from e2e tests is

```
Expected error:
    <*errors.errorString | 0xc82007bf80>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
```

E.g., https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gke-staging/6166/artifacts/junit_01.xml

This provides almost no information to the developer. Our infra tools also can't provide intelligent information for this.
Most of the tests just call functions in [e2e/framework/util](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go), which utilizes the [pkg/util/wait](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/wait/wait.go) package. It'd be nice to let the condition function returns error message and surface it as part of the error.

**Comment by nagarjung** [comment]
Hi @yujuhong, I would like to work on this issue

**Comment by yujuhong** [comment]
@nagarjung Here is the doc for running e2e tests in a local cluster: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/e2e-tests.md#local-clusters
I rarely run the tests locally, so I can't attest the validity of the doc :)

The error message changes based on the test, but like I mentioned in the original post, the tests which use the `e2e/framework/util` and the `util/wait` package have the same failure signature. You can pick one test and inject/remove code to make sure it fails to see the error message.

**Comment by spiffxp** [comment]
related https://github.com/kubernetes/kubernetes/issues/10322

**Comment by yujuhong** [comment]
Closing this in favor of #10322 since this belongs to sig/testing
