### ISSUE TITLE
Determine correct Deployment scaling behavior during rollout

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#29357]
In 1.4 we are changing the scaling behavior for Deployments during a rollout from
Scale the newest ReplicaSet
to
Scale all active ReplicaSets proportionally by their current number of replicas.

This issue is to discuss the desired behavior when the deployment controller-manager observes both rolling-out and scaling are required in the same controller sync loop.

# Example of proportional scaling:

## In 1.3:
Deployment: 5 replicas + 1 maxsurge **RS B is newest**
- RS B: 1 replica
- RS A: 5 replicas

***Scale 6 -> 12 results***

Deployment: 10 replicas + 2 maxsurge
- RS B: 7 replicas
- RS A: 5 replicas

## In 1.4:
Deployment: 5 replicas + 1 maxsurge **RS B is newest**
- RS B: 1 replica
- RS A: 5 replicas

***Scale 6 -> 12 results***

Deployment: 10 replicas + 2 maxsurge
- RS B: 2 replicas
- RS A: 10 replicas

# Description of choices for proportional scaling with rollout

When the control loop sees that changes need to be made to the total number of RS replicas (scaling) AND a new RS needs to be created (rollout) in the same iteration, it can proceed in 1 of 2 ways:

1: Create a new RS + (if scaling up add all new replicas to the new RS, if scaling down let the rollout process scale down old RSs)
- Good: This more accurately matches the system to the state desired by the user.  The user may want to only ever have X replicas of the new release, but never have more than X of a previous release.
- Bad: This behaves differently from what happens when the changes are seen in separate loops iterations.  Since the control loops are level-based and not edge-based, it is non-deterministic whether the user will see proportional scaling or not EVEN when doing separate events (the control loop may observe changes from 2 separate updates in a single iteration).

2: Proportionally scale the replicas and then create a new RS + perform rollout
- Good: This results in behavior that closely matches what happens both when the control loop sees scale then rollout and when the control loop sees rollout then scale in separate syncs (separate events)
- Bad: This creates a desired state that the user never actually asked for since the user never asked for the old RSs to be scaled up.

*It is worth noting that with ANY proportional scaling it is possible for the system to create a state that the user never actually wanted if the user creates an update, k8s creates a new RS for the update, and then the user scales by increasing the number of replicas.*

# Examples of proportional scaling with rollout

## A) Update image, then Scale

Deployment: 5 replicas + 1 maxsurge
- RS A: 5 replicas

***Update image***

Deployment: 5 replicas + 1 maxsurge
- RS B: 1 replicas
- RS A: 5 replicas

***Scale 6 -> 12 results***

Deployment: 10 replicas + 2 maxsurge
- RS B: 2 replicas
- RS A: 10 replicas

## Scale, then update image

Deployment: 5 replicas + 1 maxsurge
- RS A: 5 replicas

***Scale 6 -> 12 results***

Deployment: 10 replicas + 2 maxsurge
- RS A: 10 replicas

***Update image***
...

Deployment: 10 replicas + 2 maxsurge
- RS B: 2 replicas
- RS A: 10 replicas

## Scale + Update Option 1 (new RS first)

Deployment: 5 replicas + 1 maxsurge
- RS A: 5 replicas

***Update Image + Scale 6 -> 12 results***

Deployment: 10 replicas + 2 maxsurge
- RS B: 7 replicas
- RS A: 5 replicas

## Scale + Update Option 2 (scale first)

Deployment: 5 replicas + 1 maxsurge
- RS A: 5 replicas

***Update Image + Scale 6 -> 12 results***

Deployment: 10 replicas + 2 maxsurge
- RS B: 2 replicas
- RS A: 10 replicas

# Questions

1. For proportional scaling, is option 1 or option 2 the better choice?
1. Should the scaling strategy be a configurable field in Deployment so users can force non-proportional scaling?

**Comment by pwittrock** [comment]
@erictune WDYT?

**Comment by pwittrock** [comment]
@kargakis Moving the issue here for further discussion

**Comment by AdoHe** [comment]
For the second question, I think it's better to make scaling strategy configurable, also we should document different scaling strategy very well as users may get confused about how to pick a suitable strategy for their own use cases.

**Comment by erictune** [comment]
I need some background.  Is this problem as evident when the change in scale is not so large (1.1x vs 2x)?  Is the large change in scale due to coincidence (traffic surge at same moment as rollout) or is there a well known case where the two events correlated?

**Comment by kargakis** [comment]
cc: @kubernetes/deployment @smarterclayton

**Comment by pwittrock** [comment]
@erictune

>
Is this problem as evident when the change in scale is not so large (1.1x vs 2x)

It depends on what is in the new version.  If you scale by 10%, the new RS will immediately have 10% of the Nodes.  If the new version has a bug where it 500s all logins, this will probably be noticeable.  If the new version has a flag flipped to rollout a new feature to users and it immediately goes to 10%, it might be noticeable.  If the new version is nearly identical to the old version, it probably won't be noticed by anyone regardless of the scale change.

>
Is the large change in scale due to coincidence (traffic surge at same moment as rollout) or is there a well known case where the two events correlated?

Undetermined.  This will happen any time the control loop sees scale change + Pod template update in the same loop iteration.  This includes the user scaling and pushing an update at the same time.  It also includes if the control loop picks up separate scale and template changes in the same sync (level base vs edge based).  If the controller manager process died or was stuck for some time, the changes could have been any time in that interval.

**Comment by erictune** [comment]
Here is one way I am looking at it, tell me if this line of reasoning makes sense:

1. image changes typically come from CI/CD or directly from the user.  
  1. These can be delayed in time if necessary.  
2. scale changes will often come from autoscaling (either HPA or something the user implemented)
  1. autoscaling is often driven by load offered to the service
  1. you cannot really stop offered load from increasing.
  1. therefore, we should not delay doing scale changes.
3. therefore, react to scale changes completely before reacting to image changes.
  1. this implies doing option 2

**Comment by erictune** [comment]
Here is another way that I looked at it:

1. scale changes and image changes will often come from different sources.  We'd like those sources to not need to be aware of each other.
2. If the CI/CD system sends out a new image at time tx, and the autoscaler sends a "scale up" command at time ty, then it is non-determinisitic which order the updates will arrive, and when the controller will see it.
3. However, from a user's standpoint, this should not matter.  If we know the deployment object's spec at time 0, and we know the deployment object's spec at time n, then regardless of the sequence of updates that happened in between, we should end up at the same end state of the Replica Sets, plus or minus some fixed margin of error. 
4. if errors are not bounded, then our control system is at risk of being unstable.

So, my question to you guys is, what algorithm (be it option 1, option 2, or some other option) will give the same, or nearly the same end state, for each of these possible paths:

- Path one:  
  - first update seen by controller manager:  image is changed and scale 6->12.
- Path two:
  - First update: image added
  - second update: scale 6->12
- Path three:
  - First update: scale 6->12
  - second update: image added
- Path four
  - First update: scale 6-> 9
  - second update: image added
  - third update: scale 9->12

**Comment by pwittrock** [comment]
>
So, my question to you guys is, what algorithm (be it option 1, option 2, or some other option) will give the same, or nearly the same end state, for each of these possible paths:

I believe Option 2 results in nearly the same states for each of the paths.  With Option 1, paths 2&3 are the same, but different from 1 and 4

@kargakis Thoughts?

**Comment by pwittrock** [comment]
@smarterclayton Any opinion here?

**Comment by kargakis** [comment]
> For proportional scaling, is option 1 or option 2 the better choice?

Regarding Option 2 what if there are two updates: first is the new template, second is the scaling (and the order really matters) ? 

> Should the scaling strategy be a configurable field in Deployment so users can force non-proportional scaling?

@bgrant0607 wanted proportional scaling by default - we could make it configurable so users can fallback to the old behavior but you still end up working on a level-based way for proportional scaling.

**Comment by pwittrock** [comment]
>
Regarding Option 2 what if there are two updates: first is the new template, second is the scaling (and the order really matters) ?

If the updates are made close enough together that the control loop may or may not see both in the same iteration...

- Option 2 will always proportionally scale.
- Option 1 will non-deterministically either proportionally scale or scale the new RS 

If the updates are made in a way where the control loop sees them in separate iterations...

- Option2 and Option 1 behave the same (they both proportionally scale)

>
@bgrant0607 wanted proportional scaling by default - we could make it configurable so users can fallback to the old behavior but you still end up working on a level-based way for proportional scaling.

Proportional scaling by default seems correct to me.  It cannot support the use case you described.  I think the use case you brought up is worth discussing.

**Comment by erictune** [comment]
It seems like the A:B ratio should increase significantly only if our confidence in B has increased.  Only the passage of time and successful health checks of B-pods should increase our confidence in B.  An increase in replicas does not imply an increase in confidence.  So, from that standpoint, option 1 doesn't make sense to me.

**Comment by kargakis** [comment]
> Option 2 will always proportionally scale.
> Option 1 will non-deterministically either proportionally scale or scale the new RS

It's worth noticing that option 2 will scale the wrong replica set(s) (the order matters - we asked for the template to rollout first and then for the scaling to happen) while option 2 will always correctly scale the new replica set first, albeit non-deterministically.

**Comment by kargakis** [comment]
> It seems like the A:B ratio should increase significantly only if our confidence in B has increased. Only the passage of time and successful health checks of B-pods should increase our confidence in B. An increase in replicas does not imply an increase in confidence. So, from that standpoint, option 1 doesn't make sense to me.

This can go either way: you run a deployment with 10 pods, you rollout a bad image that you discover only at runtime, by that time you have minimum availability but you also have pods that take all the places up to your surge count. You rollout a fix to the new image and you scale up at the same time to hasten the new rollout or an autoscaler scales you up. If you proportionally scale before you rollout the fixed image, guess what, you have viloated minimum availability because you proportionally scaled a broken replica set.

**Comment by kargakis** [comment]
--> deployment=10, maxUnavailable=2, maxSurge=3, rs1=10
Bad image lands
--> deployment=10, rs1=8 (minimum availability maintained), rs2=5
New fixed image lands plus you scale to 20
If you proportionally scale before rs3:
--> deployment=20, rs1=14, rs2=9 (note that these 9 pods are broken)
Minimum availability should be 20-2=18 pods and you are only running 14.
If you let the new replica set run as part of the rollout, you have a chance to maintain minimum availability (assuming the new image is not broken). Eventually, we should consider changing other things re proportional scaling like scaling up proportionally to the healthiest replica set instead of the biggest.

**Comment by pwittrock** [comment]
>> Option 2 will always proportionally scale.
>> Option 1 will non-deterministically either proportionally scale or scale the new RS

> It's worth noticing that option 2 will scale the wrong replica set(s) (the order matters - we asked for the template to rollout first and then for the scaling to happen)

In a level based system we do not operate on events, but on the observed state at the time we sync.  We cannot depend on ordering of events or distinction of separate updates vs a single update to drive behavior.

> while option 2 will always correctly scale the new replica set first, albeit non-deterministically.

I think you meant "option 1" here.  Option 1 will NOT always correctly scale the new replica set.  You cannot determine what it will choose to do.

We should either always scale proportionally or always scale the newest rs.  Option 1 sometimes will pick one and sometimes pick the other based on state of the system that is outside the control of the user and is not visible to the user.  I can't think of a use case for this.

**Comment by kargakis** [comment]
>  Option 1 will NOT always correctly scale the new replica set. You cannot determine what it will choose to do.

Is this true? Think of the two possible scenarios with option 1:
1. events are noticed separately - great
2. events are noticed as one update - the new replica set is scaled as part of the rollout process unless you are scaling down.

In both cases, we execute the contract of rolling out the latest state of the deployment whereas that's not the case with option 2. Honestly, I don't mind taking the non-determinism that comes with option 1 not only because it's no different from what happened until we got proportional scaling but also because option 2 is broken for some scenarios.

**Comment by kargakis** [comment]
> Eventually, we should consider changing other things re proportional scaling like scaling up proportionally to the healthiest replica set instead of the biggest.

Actually, if we make this change then I may be convinced that option 2 is better because we will end up with deterministic behavior and none of the problem of option 2 with the current state of proportional scaling.

**Comment by pwittrock** [comment]
>
Honestly, I don't mind taking the non-determinism that comes with option 1 not only because it's no different from what happened until we got proportional scaling but also because option 2 is broken for some scenarios.

We we need to support the scenarios you are describing then we need to rollback proportional scaling.

**Comment by pwittrock** [comment]
>
Eventually, we should consider changing other things re proportional scaling like scaling up proportionally to the healthiest replica set instead of the biggest.

Worth talking about.  Outside the scope of how we address the immediate issue.

**Comment by bgrant0607** [comment]
Scaling to accelerate a rollout is user error. Reduce minReadySeconds or increase maxSurge instead. We absolutely don't want scaling to accelerate rollouts.

The deployment controller already has a cleanup phase to target unavailable replicas first.

If the user specified maxUnavailable as a percentage, proportional scaling should not violate that. If specified as an absolute number and they scale up a Deployment with failing replicas, they are SOL, IMO. That said, I'm not opposed to intelligent optimizations, such as detecting infant mortality (#18568) and not scaling up totally broken replica sets.
