### ISSUE TITLE
make taints unique by <key, effect> on a node

### ISSUE THREAD

**Issue by kevin-wangzefeng** [kubernetes/kubernetes#29362]
Currently in the existing implementation, how should a taint be unique (i.e. by `key` or `<key, effect>`) on a node is not clear, 

1. server side validation don't actually check if there are duplicated taints any reject the request.
2. kubectl command has an implicit semantic that taint is unique by key.
```bash
# Update node 'foo' with a taint with key 'dedicated' and value 'special-user' and effect 'NoScheduleNoAdmitNoExecute'.
# If a taint with that key already exists, its value and effect are replaced as specified.
$ kubectl taint nodes foo dedicated=special-user:NoScheduleNoAdmitNoExecute
 
# Remove from node 'foo' the taint with key 'dedicated' if one exists.
$ kubectl taint nodes foo dedicated-
```

Discussed with @davidopp and @bgrant0607 , David's idea is:
> We cannot make taint `key` be unique on a node; we can only make `<taint, effect>` be unique. The reason is that we want to be able to express all of these (I am copying this from my [comment](https://github.com/kubernetes/kubernetes/issues/28082#issue-162318430) here):
> + don't schedule me there and evict me if I'm already running there
> + don't schedule me there but leave me bound if I'm already running there
> + schedule me there and leave me bound if I'm already running there
>
> This means we need to decouple "no schedule" and "no execute" effects (let's ignore the NoAdmit part)
>   I think there are only two ways to do it:
> 1. (original plan) we have NoSchedule effect and NoScheduleNoExecute effect
> 2. (suggested new plan) we have NoSchedule effect and NoExecute effect 
>
> In either approach, you need to put two separate taints, one with each of the effects, on a node if you want to allow some pods to request only "no schedule" (i.e. leave me bound if already running) and some pods to request "no schedule and no execute." (The only difference between the two approaches is which tolerations you need for the different use cases, but in both approaches you need two different taints with the same key and different effects if you want to allow the full flexibility.)

As discussed, we should make taints unique by `<key, effect>` on a node, basically, the following two steps are needed:
+ [ ] add some validation check that reject duplicated taints that have the same `<key, effect>`
+ [ ] modify the existing semantic of `kubectl taint` command to:
```bash
# Update node 'foo' with a taint with key 'dedicated' and value 'special-user' and effect 'NoScheduleNoAdmit'.
# If a taint with that key and effect already exists, its value is replaced as specified.
$ kubectl taint nodes foo dedicated=special-user:NoScheduleNoAdmit

# Remove from node 'foo' the taint with key 'dedicated' and effect 'NoScheduleNoAdmit' if one exists.
$ kubectl taint nodes foo dedicated:NoScheduleNoAdmit-
```
+ [ ]  If the effect is omitted in the kubectlcommand line, treat that as a wildcard (all effects). That would be especially useful for removing taints.
```bash
# Remove from node 'foo' all the taints with key 'dedicated'
$ kubectl taint nodes foo dedicated-
```

**Comment by kevin-wangzefeng** [comment]
Add milestone since we are planning to do it for 1.4

**Comment by davidopp** [comment]
@kevin-wangzefeng I'm going to assign this to you and @Dingshujie
