### ISSUE TITLE
A helper to build informers for each of the running federated clusters

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#29383]
A common scenario when writing federated controllers is: "start an informer for each of the running clusters and tie its life cycles to the lifecycle of the corresponding cluster in federated apiserver". There is a bunch of various corner cases and it won't be good if everyone will try to reinvent the wheel.

Part of #29347 

cc: @quinton-hoole @wojtek-t

**Comment by quinton-hoole** [comment]
Agreed!
