### ISSUE TITLE
Translate Heroku app.json and/or CloudFoundry application manifests to K8s

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#29387]
To make it easier to migrate from Heroku or CF to K8s.

Not sure how feasible it is, but here's the Heroku spec:
https://devcenter.heroku.com/articles/app-json-schema

It's an all-in-one spec that includes functionality we don't currently support, such as builds, "addon" services, and probably some of the lifecycle scripts. We could translate a subset and print warnings about unsupported features.

CF:
https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html

cc @janetkuo @pwittrock @smarterclayton

**Comment by smarterclayton** [comment]
Here's the logic in OpenShift we use for this

https://github.com/openshift/origin/blob/master/pkg/generate/appjson/appjson.go

although it has pointers to more complex build steps not available in Kube.

**Comment by bgrant0607** [comment]
The Deis slugbuilder and slugrunner (and potentially all of Workflow) could also be useful in migrating these users:

https://github.com/deis/slugbuilder
https://github.com/deis/slugrunner

**Comment by bgrant0607** [comment]
Obsolete and out of scope.
