### ISSUE TITLE
Data structure to facilitate retries in federated controllers

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#29384]
Another common scenario when writing a federated controllers are retries. After creating an object  in federated api server a success code is returned to the user. However the fun is just to begin and many thing may go wrong and require multiple retries. Even if everything goes well in some cases it may be needed to execute object-related action after a shorter or longer delay, without having to introduce sync loops.

Part of #29347

cc: @quinton-hoole @wojtek-t

**Comment by quinton-hoole** [comment]
This can be closed now, right @mwielgus ?

**Comment by mwielgus** [comment]
Yes, fixed with #30126.
