### ISSUE TITLE
Kubemark-500 run didn't run test and is green

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#29392]
In this run, we didn't even started tests, and the run is green:
http://kubekins.dls.corp.google.com/view/Scalability/job/kubernetes-kubemark-500-gce/4096/console

This is super frightening and should be fixed ASAP.

@kubernetes/test-infra-maintainers @gmarek 

@spxtr - maybe you can take a look or reassign?

**Comment by spxtr** [comment]
I'll take a look.

**Comment by wojtek-t** [comment]
To be clear - we understand why the error happenned. I don't understand why the test was green there.

**Comment by spxtr** [comment]
https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/e2e-runner.sh#L424

`dump_cluster_logs` doesn't actually fail the test, so it's swallowing the exit code and not using it.

**Comment by wojtek-t** [comment]
OK - that's a great point.

This is what is wrong - in case of failure of the test we should dump the logs, but we should turn down the kubemark cluster and fail the test. I will take a look how to do it in the easiest way.
