### ISSUE TITLE
Clean up Kubelet constructor & dependencies

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#29391]
Forked from https://github.com/kubernetes/kubernetes/pull/29216.

Kubelet dependency construction and injection is arbitrarily distributed across a few places. There are lots of dependencies that are initialized in the various Kubelet constructors, and it's not obvious to me when a dependency should be in the KubeletConfig vs the constructor. I think we need a better story here around dependency injection and configuration.

My suggestion for cleaning up the dependency management is to move everything in the kubelet constructors to a separate builder package, where **every** non-configuration Kubelet dependency (basically everything in the Kubelet struct that is necessary to run) can be specified to the builder, and anything that is not specified gets the default. For the defaults, I recommend the builder package export a function (not a method) **per-depnedency** that takes as arguments every dependency of the dependency. As a couple examples:

```
func DefaultDiskSpaceManager(cadvisorInterface cadvisor.Interface, policy DiskSpacePolicy) (diskSpaceManager, error)
func DefaultContainerRefManager() *RefManager
func DefaultOOMWatcher(cadvisor cadvisor.Interface, recorder record.EventRecorder) OOMWatcher
...
```

In many places the Default\* method would just delegate to a constructor in another package.

The advantages to this system are:
- Dependencies are explicit
- Dependencies can be injected as needed
- All dependency construction is consolidated in one package in a consistent way
- Separate package reduces circular dependency woes

We should discuss alternative solutions as well.

/cc @mtaufen @kubernetes/sig-node

**Comment by timstclair** [comment]
Related issue: https://github.com/kubernetes/kubernetes/issues/11662

**Comment by mtaufen** [comment]
/lifecycle frozen
We should do something like this, but won't get to it this quarter.

**Comment by tallclair** [comment]
Closing this in favor of https://github.com/kubernetes/kubernetes/issues/84473
