### ISSUE TITLE
Pod creation throughput calculation in e2e density test may be incorrect

### ISSUE THREAD

**Issue by coufon** [kubernetes/kubernetes#29408]
In e2e density test, pod creation through is calculated by _1 / (pod creation latency) * (node number)_

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/metrics_util.go#L451

This way underestimates the throughput of creating a batch of pods, because the creation process is concurrent instead of sequential. A better way may be

_throughput per node = (pod number) / (batch creation latency)_
where _(batch creation latency) = (last pod is running) - (create first pod)_

**Comment by coufon** [comment]
@Random-Liu @yujuhong

**Comment by Random-Liu** [comment]
@wojtek-t @gmarek 
/cc @kubernetes/sig-scalability

**Comment by coufon** [comment]
Sorry that I was confused with the tests of batch creating and sequential creating. In the density test, the throughput of batch creating is calculated somewhere else:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/density.go#L389
