### ISSUE TITLE
Automatically get test whitelist from github teams

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#29405]
It looks like jenkins's allowed user whitelist is manually updated:
https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull.yaml#L142

And "add to whitelist" no longer works.

Since the list is hard to update and most contributors don't understand the rules for updating it, it doesn't get updated. It looks like it hasn't been updated since the list was created at the beginning of June.

This slows down testing for a lot of PRs. 

I suggest we find a way to not check in the list. Could jenkins check a label instead of checking the user? The bot could apply a label based on github team membership, or a human could apply the label.

cc @kubernetes/sig-testing @kubernetes/contributor-experience

**Comment by ixdy** [comment]
I filed a FR to have the Jenkins plugin look at GitHub teams almost a year ago... https://github.com/jenkinsci/ghprb-plugin/issues/160

**Comment by spxtr** [comment]
My [CI on GKE](https://github.com/kubernetes/test-infra/tree/master/ciongke) system checks an org and a team. It will be a while before that's in place, though.

**Comment by ixdy** [comment]
I also just created https://github.com/kubernetes/test-infra/pull/302 to update the lists to the current teams.

**Comment by spxtr** [comment]
It now checks that you or someone commenting "ok to test" is a member of the kubernetes org.
