### ISSUE TITLE
kubelet's /stats/summary endpoint may return inaccurate ImageFs `UsedBytes` for docker v1.10+

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#29406]
Kubelet relies on `docker history` to get the size of layers for each image, so that it can deduplicate shared layers. This is fine for docker v1.9 or before. For docker 1.10+, docker stops generating a random image ID for each layer, and just uses the content addressable IDs. Except for the top layer, every other layer has a `<missing>` ID. Kubelet relies on using the image layer IDs as keys, and this affects the calculation of total used space.

```
======== d023c050c065 ===========
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
d023c050c065        7 days ago          /bin/sh -c #(nop) ENTRYPOINT &{["/dashboard"    0 B                 
<missing>           7 days ago          /bin/sh -c #(nop) EXPOSE 9090/tcp               0 B                 
<missing>           7 days ago          /bin/sh -c #(nop) ADD dir:6bf26a2727be5df090a   58.65 MB            
<missing>           4 months ago        /bin/sh -c #(nop) MAINTAINER Piotr Bryk <bryk   0 B                 
======== 18ea23a675da ===========
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
18ea23a675da        2 weeks ago         /bin/sh -c #(nop) CMD ["nginx" "-g" "daemon o   0 B                 
<missing>           2 weeks ago         /bin/sh -c #(nop) EXPOSE 443/tcp 80/tcp         0 B                 
<missing>           2 weeks ago         /bin/sh -c ln -sf /dev/stderr /var/log/nginx/   11 B                
<missing>           2 weeks ago         /bin/sh -c ln -sf /dev/stdout /var/log/nginx/   11 B                
<missing>           2 weeks ago         /bin/sh -c /tmp/build.sh                        53.91 MB            
<missing>           2 weeks ago         /bin/sh -c #(nop) COPY file:bf2b48e7f6cbf1964   8.221 kB            
<missing>           7 weeks ago         /bin/sh -c #(nop) CMD ["/bin/sh"]               0 B                 
<missing>           7 weeks ago         /bin/sh -c #(nop) ADD file:2df43ffb0761746c1f   56.57 MB            
```

On the other hand, we can get all the layers from inspecting the image, but there is no information about its sizes.

```
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:4636ee4859c26ceb06787821cbfb166a81ca82db61656ab01ae168d5e7dee664",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef"
            ]
        }
```

/cc @vishh @ronnielai @Random-Liu

**Comment by Random-Liu** [comment]
IIUC, we tried to deal with `<missing>` layer https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/images.go#L80.

But I'm not sure whether there will usually be layers with the same `Created` time.

**Comment by yujuhong** [comment]
The problem now is every layer (except for the top layer) is `<missing>`. I don't believe the code can dedup shared layers correctly under the circumstances. My understanding is that the code tackling the `<missing>` IDs assumes it happens rarely and relies on `CreatedBy` (not `Created` time)  as the key. E.g., the key could be `/bin/sh -c /tmp/build.sh`

**Comment by yujuhong** [comment]
I don't think any kubernetes component consumes the stats, so the impact of this is limited. On the other hand, if we get accurate information from `docker history`, maybe it's not worth keeping this code?

**Comment by Random-Liu** [comment]
> My understanding is that the code tackling the <missing> IDs assumes it happens rarely and relies on CreatedBy (not Created time) as the key.

Yeah, it's `CreatedBy`, :0

**Comment by yujuhong** [comment]
> Yeah, sorry, it's CreatedBy, :)

It's fine. I don't think created time is better in this case ;)

**Comment by Random-Liu** [comment]
```
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:4636ee4859c26ceb06787821cbfb166a81ca82db61656ab01ae168d5e7dee664",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef"
            ]
        }
```
It seems that some layers' digests are duplicated. Don't quite understand, hm.

**Comment by yujuhong** [comment]
`sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef` is the hash of an empty layer. See https://github.com/docker/docker/issues/22072#issuecomment-210510562

**Comment by nhlfr** [comment]
Relying on `CreatedBy` isn't very good idea IMO. These commands can be repeated, it probably happens very rarely, but if someone writes crappy Dockerfiles, that can occur.

My proposition is to not store `<missing>` layers at all. How? We may add the sizes of all `<missing>` layers to the layer with ID which is basing on them. Then we can operate only on layers with ID-s, with sizes being the sum of the layer with ID and all `<missing>` layers it contains.

What do you think?

**Comment by yujuhong** [comment]
I believe we no longer use `docker history`.
