### ISSUE TITLE
Add dry-runs + optional stricter validation to kubectl create

### ISSUE THREAD

**Issue by ace-n** [kubernetes/kubernetes#29410]
#11488 proposes adding a "dry-run" flag to kubectl. I plan to implement such a flag for `kubectl create` that, when included, would prevent `kubectl create` from actually making any API requests.

In addition, I plan to add the validation logic for testing example pod configurations to `kubectl create` itself. The tests' validation logic is (much) stricter than the existing `kubectl create` validator, so it would need to be controlled via a command-line flag (e.g. --strict).

The eventual goal of these changes is to allow validation of example pod schemas via the `kubectl create` command instead of by calling validation functions manually within `examples_test.go`.

**Comment by ace-n** [comment]
cc @kubernetes/kubernetes

**Comment by ace-n** [comment]
As part of my changes, I would need to set defaults on an object of type `api.Pod  (*"k8s.io/kubernetes/pkg/api".Pod)`, but the `SetDefaults_Pod` method only accepts `"k8s.io/kubernetes/pkg/api/v1".Pod`.

Furthermore, I took a look at the files for each of these classes ("pkg/api/types.go" and "pkg/api/v1/types.go" and they look fairly similar to me at a glance. What's the reasoning behind having both of them?

cc @jeffmendoza

**Comment by jeffmendoza** [comment]
cc @kubernetes/kubectl

**Comment by pwittrock** [comment]
cc @lavalamp 

What you are seeing has to do with internal vs external representation of the types.  Types are converted to an internal for business logic processing.

**Comment by pwittrock** [comment]
@ace-n What are you using to set the defaults?  I believe that is normally performed on the server side.

**Comment by smarterclayton** [comment]
There was discussion that the implementation of dry run had to be on the server, not on the client.  Which would mean tooling up the admission chain to handle persist / not-persist variants (quota increment for instance has to be skipped in a dry-run)

**Comment by ace-n** [comment]
@pwittrock I was using the `SetDefaults_Pod` method [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/defaults.go#L127).

(It's possible that this is meant to be an internal/server-side method - but I was trying to implement --dry-run and --validate=strict client-side, since that's where [examples-test.go](https://github.com/kubernetes/kubernetes/blob/master/examples/examples_test.go) does its validation.)

**Comment by smarterclayton** [comment]
It would not be recommended to directly invoke defaulting on the client side today.  Our general goal is to move most of this logic back to the server, and adding more in the client now is going to complicate that.

**Comment by jeffmendoza** [comment]
This is making me think that we could possibly have a separate command:

kubectl validate (client side validation)
kubectl create/run --dry-run (server side dry run)

**Comment by smarterclayton** [comment]
Yes, the client side validator that specifically invokes validate would make a lot of sense.

**Comment by lavalamp** [comment]
Yeah, we need a dry-run option on POST. Needs to be done server-side.

**Comment by jeffmendoza** [comment]
Looks like trying to include a client side 'kubectl validate' would pull in too much server code into kubectl. @ace-n is going to try a stand-alone validate tool, then we can see if a 'kubectl validate' command would make sense.

**Comment by smarterclayton** [comment]
Is this validation beyond swagger?  Like defaulting and actually invoking
the server side validation?

**Comment by jeffmendoza** [comment]
Yes, anything that could be done stand-alone without a server.

**Comment by smarterclayton** [comment]
I wouldn't mind a separate validate command that just called swagger.  Did we think that was insufficient to be useful?  Or does the fact that it has to fetch swagger defeat your desire not to hit the server?

**Comment by ace-n** [comment]
If @jeffmendoza doesn't want to involve a server, this would probably be easiest to implement by
