### ISSUE TITLE
kubedns can not work. Pod cantainer don't have the nameserver of kubeservice. 

### ISSUE THREAD

**Issue by jeffchanjunwei** [kubernetes/kubernetes#29417]
**I download the  k8s source code version release 1.3 , then 'make' to deploy the k8s. after that config k8s files refer to http://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/ .
The k8s cluster servie ip range is 10.254.0.0/16. I deploy on vms of openstack, whose infor showed bellow:**
centos-master: 10.139.4.183
centos-minion1: 10.139.4.184
centos-minion2: 10.139.4.195
 openstack dhcp : 10.139.4.17, 10.139.4.1

 **After that creater k8s service redis-master with ip 10.254.212.107, and busybox pod. 
Then start the kubedns exec './kube-dns' result showed bellow:**
  I0722 09:56:11.411379   31410 server.go:91] Using http://localhost:8080 for kubernetes master
I0722 09:56:11.411464   31410 server.go:92] Using kubernetes API <nil>
I0722 09:56:11.411795   31410 server.go:132] Starting SkyDNS server. Listening on port:53
I0722 09:56:11.411865   31410 server.go:139] skydns: metrics enabled on :/metrics
I0722 09:56:11.411882   31410 dns.go:166] Waiting for service: default/kubernetes
I0722 09:56:11.412083   31410 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:53 [rcache 0]
I0722 09:56:11.412109   31410 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:53 [rcache 0]
I0722 09:56:11.415306   31410 server.go:101] Setting up Healthz Handler(/readiness, /cache) on port :8081
I0722 09:56:11.415983   31410 dns.go:660] DNS Record:&{10.254.0.1 0 10 10  false 30 0  }, hash:63b49cf0
I0722 09:56:11.416038   31410 dns.go:660] DNS Record:&{kubernetes.default.svc.cluster.local. 443 10 10  false 30 0  }, hash:c3f6ae26
I0722 09:56:11.416075   31410 dns.go:660] DNS Record:&{kubernetes.default.svc.cluster.local. 0 10 10  false 30 0  }, hash:b9b7d845
I0722 09:56:11.416109   31410 dns.go:660] DNS Record:&{10.254.212.107 0 10 10  false 30 0  }, hash:e7ffaeb4
I0722 09:56:11.416137   31410 dns.go:660] DNS Record:&{redis-master.default.svc.cluster.local. 0 10 10  false 30 0  }, hash:606d0bd5
I0722 10:01:11.413083   31410 dns.go:660] DNS Record:&{10.254.0.1 0 10 10  false 30 0  }, hash:63b49cf0

**But when I exec statement 'kubectl exec busybox -- nslookup redis-master', it return** 
nslookup: can't resolve 'redis-master'
Server:    10.139.4.17
Address 1: 10.139.4.17 host-10-139-4-17.openstacklocal

error: error executing remote command: Error executing command in container: Error executing in Docker Container: 1

**I cat the resolv.conf file of busybox pod just as bellow, it seems kubedns doesn't work?**
\#Generated by NetworkManager
search openstacklocal novalocal
nameserver 10.139.4.17
nameserver 10.139.4.1
nameserver 8.8.8.8

**Comment by thockin** [comment]
This is a support request.  Please use StackOverlfow, so it can be indexed and answered by a larger community.

That said, check your kubelet --cluster-dns  and related flags.
