### ISSUE TITLE
Have a more consistent naming policy for TPRs

### ISSUE THREAD

**Issue by duglin** [kubernetes/kubernetes#29415]
Right now if I create a third party resource (TPR):
- I give it a name of `org1-type.myorg1.org`
- I create new resources by POSTing to `apis/myorg1.org/v1/namespaces/default/org1types`
- with a `kind` of `Org1Type`

that's 3 different ways the name is referenced: org1-type, org1types, Org1Type

I would recommend that we not do any name tweaking. Let the user pick the name and then just use that. Using anything else means each client would need to mimic those rules which runs the risk of them getting it wrong. It adds a layer of confusion for no reason.

**Comment by lavalamp** [comment]
Yeah, this is really unfortunate. It's also not trivial to change. :/

**Comment by liggitt** [comment]
the TPR type needs to specify the kind, singular, and plural resource names

**Comment by enisoc** [comment]
This is addressed in the [proposal for moving TPR to beta](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/thirdpartyresources.md). The various names are specified explicitly by the user.
