### ISSUE TITLE
kubectl get pvc shows 0 capacity for PersistentVolumeClaim

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#29425]
Bound  PersistentVolumeClaim shows 0 capacity

```
$ gcloud compute disks list
NAME                                 ZONE            SIZE_GB  TYPE         STATUS
disk100-001                          europe-west1-d  100      pd-standard  READY
gke-unrest-micro-pool-199acc6c-3p31  europe-west1-d  100      pd-standard  READY
gke-unrest-micro-pool-199acc6c-4q55  europe-west1-d  100      pd-standard  READY

$ kubectl get pv
NAME             CAPACITY   ACCESSMODES   STATUS    CLAIM                           REASON    AGE
pv-disk100-001   100Gi      RWO           Bound     default/graphite-statsd-claim             2m

$ kubectl get pvc
NAME                    STATUS    VOLUME           CAPACITY   ACCESSMODES   AGE
graphite-statsd-claim   Bound     pv-disk100-001   0                        3m
```

From http://stackoverflow.com/questions/38463725/persistentvolumemound-bound-but-with-0-capacity-using-kubernetes-on-google-compu

**Comment by aga20** [comment]
Hello,

+1. I have same problem :/ With 1.2 it worked fine.

**Comment by wongma7** [comment]
I found this was introduced by https://github.com/kubernetes/kubernetes/pull/24331 I think updating pvc capacity got lost in the refactor https://github.com/kubernetes/kubernetes/pull/24331/files#diff-97a1ffdd78274d54ba9dc28656ceca2dL431

**Comment by saad-ali** [comment]
@jsafrane can you take a look at this.

**Comment by jsafrane** [comment]
*Someone* forgot to update `claim.Status.Capacity` when binding claims. Fix will follow shortly.
