### ISSUE TITLE
Kubelet should attach SHA of image(s) to pod status

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#29448]
Moving this piece from [this comment](https://github.com/kubernetes/kubernetes/pull/27129/files/4a60be831efce93d7e210df47d79e7c18d5d13c2#r71607506). Generally the idea is to have the kubelet to attach SHA of the image(s) running in a pod in the pod status field. This will be useful for the aforementioned image policy proposal and related image auditing capabilities. 

@erictune fyi

**Comment by timstclair** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/14047?

**Comment by soltysh** [comment]
That's what it looks like, closing in favor of #14047.
