### ISSUE TITLE
Many websites are invalid in docs

### ISSUE THREAD

**Issue by lixiaobing10051267** [kubernetes/kubernetes#29440]
such as: docs\design\indexed-job.md
line 868:
Kubelet does support [expanding varaibles without a
shell](http://kubernetes.io/v1.1/docs/design/expansion.html)

**Comment by pwittrock** [comment]
@lixiaobing10051267 Would you be willing to file a PR against the kubernetes/kubernetes.github.io docs rep to fix the issues you find?

**Comment by lixiaobing10051267** [comment]
@pwittrock  I'd like to fix, but I haven't found the new website for above invalid website:   http://kubernetes.io/v1.1/docs/design/expansion.html

**Comment by lixiaobing10051267** [comment]
has found correct website, close the issue
