### ISSUE TITLE
Services that consume multiple node ports are charged for 1 in quota

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#29456]
If a service consumes multiple node ports, quota is only charging for one of those and not all.

**Comment by derekwaynecarr** [comment]
/cc @kubernetes/rh-cluster-infra 

I am putting a patch together per our chat @ncdc

**Comment by derekwaynecarr** [comment]
@sdminonne fyi

**Comment by sdminonne** [comment]
@derekwaynecarr thanks for the fix (and sorry for the bug)
