### ISSUE TITLE
Support query parameters in httpGet livenessProbe

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#29470]
Brought up in https://github.com/deis/controller/issues/774 and http://stackoverflow.com/questions/38532286/kubernetes-liveness-probes-with-query-string-parameters.

I don't think it would be hard to add, but I don't know whether or not it's a model we want to encourage/support.

**Comment by therc** [comment]
This should already be working, even without adding new API types for the query parameters. My PR was merged a few days after the Deis bug was opened (but this is the first time I see it):

https://github.com/kubernetes/kubernetes/pull/25064
