### ISSUE TITLE
WIP: Proposal for moving "printers" (kubectl get) to the server

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#29472]
Still WIP

As mentioned in #12143 (and #11617) we want to move printers to the server so that all clients can benefit from them, the naive client implementation is simpler, and so we can avoid having to perform external -> internal conversions in the client.
## Considerations
- A `kubectl get` is an alternative representation of the underlying API object or objects - in HTTP and REST this is most commonly treated as another representation of the same resource.  
  - We need to support alternate representations of both the list (`kubectl get pods`) and the individual item (`kubectl get pod`).
- The representation returned must be structured (an API object) and we need to potentially handle the desire to change that API over time.  
- We want to support both command line clients and web clients, and that requires an internal structure
  - command line clients may add additional value like wrapping within the terminal window boundaries, or showing and hiding headers
  - web clients will wish to transform the response in HTML and need a structured format
- We already enable clients dealing with JSON and YAML - a serialization in either of those formats would be easily consumed (with a preference for JSON)
- We will need to support additional parameters to these representations, parameters that _only_ make sense when viewing this representation (for instance, wide vs narrow).  Other parameters may be common (paging, sorting, filtering).
- There are two primary mechanisms for conveying "alternate return type of content" for RESTful objects.  
  - One is a query parameter (`?table=1`) and one is the content type (`Accept: application/json;tabular=1`).  
  - We have support for both mechanisms - the former is easier for naive clients, the latter is more "correct" in HTTP vocabulary.  
  - We support `Accept: application/json;pretty=1` and `?pretty=1` today, which are roughly equivalent.  
- We already have `export`, which is implemented as a query parameter.  Export always returns the same object schema as the normal GET request.
- We have `watch`, which is implemented as a query parameter, but which returns a different content-type and object schema as a normal GET request.
- We want the serialization choice to be obvious to a swagger API consumer (which means it can either be content type or query parameter, although query parameters have more doc).
- Since this is a variant of the object, I believe we should avoid a subresource (since we would have to create a subresource of a list, which would conflict with resource names).
## Proposed:

Support both content type and query parameter for selecting an alternate representation of the object.  Supporting content-type means we can in the future add new representations AND allow the user to request multiple serializations in order.

Example:

```
$ curl -H "Accept: application/json;table=wide" https://server/v1/namespaces/default/pods?table=wide
Content-Type: application/json;table=wide
{
  "kind": "Table",
  "apiVersion": "printers.k8s.io/v1",
  "metadata": {
    "resourceVersion": "395",
    "selfLink": "https://server/v1/namespaces/default/pods"
  },
  "columns": [
    {"name": "Name"},
    {"name": "Age"},
  ],
  "items": [
    {
      "values": ["hello", "3d"],
    }
  ]
}
```

ISSUE: Do we want to continue the inlining of schemas (return `v1` for `v1` resources), or explicitly return a different schema type?  The latter is easier for generic clients.  The former is easier for versioned clients.

It would be valid to specify `?watch=1` or `?export=1` with `?table=` in the future.  Tabular output is a transformation of the resulting object from a Get.

This is a reasonably simple table schema (it's possible to extend values in the future) but in the near term additional descriptive metadata could be hung off "columns".  The use of the `table` parameter aligns with the requested schema.  For instance, the "default filter" concept needs to be implemented server side, which means each row needs a descriptive field (filtered or not).
## Implementation (more details needed)
- Server
  - Create a new API group `printers.k8s.io` with a `v1` version that accepts this object.
  - Add a new method `TransformTable(context api.Context, obj runtime.Object) (api.Table, error)` to RESTStorage
  - Provide a default implementation of `TransformTable` on `generic.Etcd` that handles fields supported by ObjectMeta
- Client
  - Move `kubectl.Printers` into a package outside of `pkg/kubectl` where it can be reused by both
  - Add functionality to `resource.Helper` to request tabular output.
    - Invoke `DecodeInto(..., &v1.Table{})` to decode the response (which should error if v1.Table is not recognized)
  - Alter `kubectl get` to invoke the generic helper.

**Comment by smarterclayton** [comment]
Still in progress

**Comment by AdoHe** [comment]
@smarterclayton I think it would be better to list some work items here so other people can pick and help. wdyt?

**Comment by smarterclayton** [comment]
Going to write up a proposal shortly for the API part, then start suggesting changes into smaller work items.  Joe Beda had a good suggestion for describe that resolves some of the issues we had with it.

**Comment by AdoHe** [comment]
Really look forward to this :)

**Comment by errordeveloper** [comment]
I like this approach a lot. Given that this has been open for a while and hasn't seen much activity since, would it make sense to attempt building this as a 3rd-party resource first? Firstly, this approach would allow more room for experimentation without much in the way, like it can be implemented by a novice to API machinery and agains a released version of Kubernetes. Also, I can imagine that re-mapping can be done in lots of clever ways, so it'd be fun to work on.
Additionally, I see how there is some benefit for  having this triggered with `Accept` header and/or query parameter, but it would make the endpoint handler more complex and presumably make API spec more complex as well as require changes to API machinery and all that stuff, so having it more external by design would be easier, wouldn't it?

**Comment by smarterclayton** [comment]
All of the endpoint handler work is done at this point (and the majority of
the internal work).  What this is blocked on is creating the meta/v1 group
and getting types moved into it so that we can have a common type that
clients can reference.  That's still on track for 1.6

External doesn't help much because it's one more place for clients to look
things up at.

On Dec 30, 2016, at 5:20 AM, Ilya Dmitrichenko <notifications@github.com>
wrote:

I like this approach a lot. Given that this has been open for a while and
hasn't seen much activity since, would it make sense to attempt building
this as a 3rd-party resource first? Firstly, this approach would allow more
room for experimentation without much in the way, like it can be
implemented by a novice to API machinery and agains a released version of
Kubernetes. Also, I can imagine that re-mapping can be done in lots of
clever ways, so it'd be fun to work on.
Additionally, I see how there is some benefit for having this triggered
with Accept header and/or query parameter, but it would make the endpoint
handler more complex and presumably make API spec more complex as well as
require changes to API machinery and all that stuff, so having it more
external by design would be easier, wouldn't it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/29472#issuecomment-269755127>,
or mute the thread

**Comment by brendandburns** [comment]
Is there a more concrete proposal/design for this somewhere? I'm a little concerned we're rushing into a fairly significant change without much discussion or feedback beyond what is in this issue.

**Comment by errordeveloper** [comment]
I just reminded myself that Elasticsearch has a similar things, it's called ["cat API"](I think we should consider https://www.elastic.co/guide/en/elasticsearch/reference/current/cat.html), I think it's rather quite neat and we should consider it as an example.

**Comment by brendandburns** [comment]
A couple other things we need to make certain of:

1) I'm adding internationalization support, if we're pretty printing on the server, it needs to take language as a parameter so that it can translate appropriately.

2) I'm adding colorization support, again, we likely want the format here to work for colorization too.

I suspect there will be a number of these kinds of features, where we need to pass a great deal of information from the client back to the server just so the server can render something properly.

In general, this means I have a bunch of concerns about this.  It's fine to add a simple table API if we want, but I'm quite worried that we will sacrifice user experience in the client in exchange for server side rendering.

**Comment by smarterclayton** [comment]
If you have an internationalization proposal, I'd be happy to add design
points on the server side implications of translation to it.  It's
something we've discussed quite a bit.

The design proposal for get has been germinating for a while in discussions
with the sig.  it'll go up soon, now that we've completed the prerequisite
changes for it.

The point of server side rendering is that we have several clients that all
want superior handling for third party resources and extensions, and
forcing the client to do it doesn't actually mean the client does better at
it.  Kubectl get for a pod is almost impossible for another client to
reproduce, yet it's info valuable to all users.  The request comes from web
consoles (which are having to reimplement every resource).

It also shields third party clients from each recreating an identical "get"
operation that depends on swagger (which also has to be versioned, since
we've already changed it several times in non compatible ways).

You can see a prototype at
https://github.com/kubernetes/kubernetes/pull/40848. Effectively we'd just
wire up the existing get code on the server and transform its output into a
table.

On Feb 6, 2017, at 7:12 PM, Brendan Burns <notifications@github.com> wrote:

A couple other things we need to make certain of:

   1.

   I'm adding internationalization support, if we're pretty printing on the
   server, it needs to take language as a parameter so that it can translate
   appropriately.
   2.

   I'm adding colorization support, again, we likely want the format here
   to work for colorization too.

I suspect there will be a number of these kinds of features, where we need
to pass a great deal of information from the client back to the server just
so the server can render something properly.

In general, this means I have a bunch of concerns about this. It's fine to
add a simple table API if we want, but I'm quite worried that we will
sacrifice user experience in the client in exchange for server side
rendering.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/29472#issuecomment-277857244>,
or mute the thread

**Comment by pwittrock** [comment]
After syncing up offline, this makes sense to me and is complementary with the using the approach described [here](https://github.com/kubernetes/community/pull/308) as a fallback.

**Comment by smarterclayton** [comment]
Is almost merged!
