### ISSUE TITLE
`kubectl logs` does not work for pods running on the master

### ISSUE THREAD

**Issue by azell** [kubernetes/kubernetes#29480]
k8s version:

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.2", GitCommit:"9bafa3400a77c14ee50782bb05f9efc5c91b3185", GitTreeState:"clean", BuildDate:"2016-07-17T18:30:39Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.2", GitCommit:"9bafa3400a77c14ee50782bb05f9efc5c91b3185", GitTreeState:"clean", BuildDate:"2016-07-17T18:23:58Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

daemon set: https://github.com/kubernetes/kubernetes/tree/release-1.3/examples/newrelic

The daemon set deploys correctly and is running on all of the nodes including the master.  However logs can be retrieved only from the nodes.  Asking for the logs from the pod on the master fails:

```
$ kubectl --namespace=kube-system logs -f newrelic-agent-7l72w                           
Error from server: the server could not find the requested resource ( pods/log newrelic-agent-7l72w)
```

Though the logs do exist in Docker.  Logging onto the master and running `docker logs ...` manually shows the expected logs.  Is this a general limitation of scheduling work on the master?

Ex:

```
$ kubectl --namespace=kube-system logs kube-scheduler-ip-172-20-40-126.us-west-2.compute.internal
Error from server: the server could not find the requested resource ( pods/log kube-scheduler-ip-172-20-40-126.us-west-2.compute.internal)
```

@justinsb

**Comment by justinsb** [comment]
I have tracked this down: on the master kubelet is running with `--enable-debugging-handlers=false`.

This flag turns off a lot of functionality: run, exec, attach, portforward, logs, containerLogs, pprof & runningpods.

I'm not sure whether we want to allow access to the master pods in this way.  And whether we should split this up and/or rely on authentication more.  @mikedanese WDYT?

**Comment by dims** [comment]
@azell @justinsb There's another issue (dup) https://github.com/kubernetes/kubernetes/issues/25448

**Comment by justinsb** [comment]
Nice find @dims.  That issue wants to fix the error message, so let's use this issue for making logs work on the master!

**Comment by dims** [comment]
@justinsb Sounds good to me :)

**Comment by mikedanese** [comment]
> let's use this issue for making logs work on the master

What do you mean by this exactly? Isn't this dependent on the deployment style and possible today?

**Comment by justinsb** [comment]
@mikedanese kube-up is our canonical installation reference (for the moment) and right now it registers the master as a node, but also sets `--enable-debugging-handlers=false`.

Shall we just change that to `--enable-debugging-handlers=true` ?  Any negative consequences?

The situation we have now is that we set up a cluster, but the pods that are running on the master are "broken" when it comes to `kubectl logs`, as far as the user can see.

**Comment by mikedanese** [comment]
No intention of making this happen in gce kube up

**Comment by justinsb** [comment]
The question in my mind is whether we should (and if not, why not), and whether we should split off logging from the other privileged flags.  Reopening.

**Comment by mikedanese** [comment]
This is deployment specific so a general issue doesn't make sense. Do you intend for this issue to be for gce in particular?

**Comment by tzerchyuan** [comment]
How do I go about setting `--enable-debugging-handlers=true`?

**Comment by Fak3** [comment]
Is there any solution to this? My kube-dns and kube-dashboard entered failing state and i can't see logs to understand what is going on 
/remove-lifecycle stale
