### ISSUE TITLE
Editing with `-o json` returns invalid JSON

### ISSUE THREAD

**Issue by montanaflynn** [kubernetes/kubernetes#29524]
Recently I was experimenting with changing `KUBE_EDITOR` for a Golang pre-purposed faux editor when editing resources when I noticed that it couldn't be marshaled. Upon inspecting the output JSON I noticed it had the same comments that the default yaml version has. Valid JSON cannot have comments.

Since the comment also gives warning / error information upon saving it must be decided where to put that in the JSON output. Perhaps a new JSON property?

## Kubernetes Version:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.5", GitCommit:"25eb53b54e08877d3789455964b3e97bdd3f3bce", GitTreeState:"clean"}
```

## Steps to Reproduce:

```
kubectl run minio --image=minio/minio --port=9000
kubectl edit deployment minio -o json
```

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
{
    "kind": "Deployment",
    "apiVersion": "extensions/v1beta1",
    "metadata": {

**Comment by pwittrock** [comment]
Maybe just not save the comments as part of the json to get rid of the warning, but still should them?

**Comment by MHBauer** [comment]
Is this a 1.2 thing? I do not see any errors when running the two commands. I made an edit in one run, and did not make an edit in a separate run. Maybe I don't understand the problem that is seen.

**Comment by montanaflynn** [comment]
@MHBauer there isn't a kubernetes error that is shown, the issue is that the output JSON that kubernetes generates is actually invalid JSON due to the comments at the top. This caused errors when I was trying to unmarshal that JSON in another project.

**Comment by MHBauer** [comment]
Okay. Got it. The editor is being very strict about json having no comments.

**Comment by jellonek** [comment]
It's not only about editor, it's simply part of language specification.
Explanation for this: https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr 
IMO if we want to use [JSON](http://json.org/) format, we should comply with it's standard.

Also currently used `#` sign for comments is unusual in javascript world, from which json evolved. In this world comments are marked in "C++ like" style (what in early days of JSON was also supported), i mean using `//` and `/* ... */`.

So IMO in time of converting into JSON - we should strip such comments (I would prefer that), or they should be added in some documented and specific to kubernetes way into JSON object.
