### ISSUE TITLE
[PetSets] stable storage IDs across clusters

### ISSUE THREAD

**Issue by Crapworks** [kubernetes/kubernetes#29538]
Hi all,

we are using:

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0+2831379", GitCommit:"g2831379", GitTreeState:"clean", BuildDate:"2016-07-11T07:20:39Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0+2831379", GitCommit:"g2831379", GitTreeState:"clean", BuildDate:"2016-07-11T07:20:39Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

Our Setup:
We are spinning kubernetes clusters on demand on an OpenStack environment and developed a self service that allows our endusers to create/destroy their clusters. (If relevant, we use terraform to create/destory the OpenStack environment and Salt to create a kubernetes cluster afterwards)

I have been playing around with PetSets lately and was hoping to giving our users the ability to destroy/create a cluster but still keeping their presited data. Unfortunately, the Volumes created by kubernetes do survive a terraform destroy but are ignored by the PetSet. Instead it just creates a new volume with a new ID.

My question/request is: Would it be possible to create a reference to the created volume that is stable across clusters? For example by just using provided informations from the rc, svc, etc. files to create the ID. Or is it actually intended that they are NOT stable across clusters?

Regards,
Christian

**Comment by chrislovecnm** [comment]
By across cluster do you mean different k8s clusters?  If so then yes PV, and PVC are based on cluster, and there identity does not span the cluster.  You also need to clean up the PV and PVC yourself. After the pods have left the terminating state should trigger deletion of the backing Persistent Volumes.

**Comment by Crapworks** [comment]
Hi @chrislovecnm,

yes, i am aware that I hae to clean up the PV and PVC. That also works just fine and the volumes in OpenStack cinder are gone. 

I am not sure if I am able to convey my idea correctly. My usescase was:

1. create a kubernetes cluster
2. deploy a petset
  1. this creates a cinder volume with a id that is stable *inside* the current cluster
3. destroy kubernetes cluster
4. create new kubernetes cluster
5. deploy the same petset

And here comes the point where my usecase breaks. the stored data is still on the cinder volume and could be used by the new petset. But since the ID is a new one, kubernetes creates a new cinder volume and ignores the old one. My problem is not that there is an unused cinder volume. I would like the petset to use the old cinder volume with the data on it. So if the petset would create an ID for the volume purely based on the information in the yaml/json files, the id would be the same on any kubernetes cluster. The question is, if this is desirable or not. I hope I was able to clear up some confusion about this.

Regards,
Christian

**Comment by msau42** [comment]
@Crapworks were you able to find a solution to your problem?
Currently, the PV and PVC objects are only scoped within a single cluster.  If you want to migrate your volume to a new cluster, you will have to statically create the PVs with the cinder volume info in the new cluster.
