### ISSUE TITLE
missing images in getting-started-guides/logging

### ISSUE THREAD

**Issue by thkoch2001** [kubernetes/kubernetes#29545]
The images were removed in 3521a66dcec0347883e655594d264ba4c33f87c4 but the article was not updated. So there are broken images now in
http://kubernetes.io/docs/getting-started-guides/logging/

**Comment by dims** [comment]
@thkoch2001 - The documentation has moved to a separate repo, could you please file this bug there?
https://github.com/kubernetes/kubernetes.github.io/blame/f9d8c58e69355ee0f63b84a18a77369fcfd8a0d4/docs/getting-started-guides/logging.md#L22

https://github.com/kubernetes/kubernetes.github.io/issues

Looks like the image is here:
https://github.com/kubernetes/kubernetes.github.io/blob/master/images/docs/cloud-logging-console.png

In fact, if you click on the blue circle with pencil in the top right corner:
http://kubernetes.io/docs/getting-started-guides/logging/

You will get to this url:
http://kubernetes.io/editdocs#docs/getting-started-guides/logging.md

Where you can edit the file inline and submit a change very easily.

Thanks
-- Dims
