### ISSUE TITLE
Issues with long polling/persistent connections between containers

### ISSUE THREAD

**Issue by nvartolomei** [kubernetes/kubernetes#29543]
Had anyone these issues? Or maybe you know a better place to ask this.

I'm running a redis and listening to a pubsub channel from another pod. After some time the subscriber isn't receiving messages any more.

Using redigo client.

**Comment by evandigby** [comment]
We're experiencing the same (or similar) issue with a few additional details:
- It only stops working if 2 of the subscribers are scheduled on the same pod.
- The pause is temporary--it eventually resumes (after 20-60s). 
- We're using a different redis client (gopkg.in/redis.v5. We have also tried v2 and v4).

@nvartolomei were you ever able to resolve this?

**Comment by nvartolomei** [comment]
@evandigby I noticed that messages are not delivered if connection is idle for some time, added a temporary fix that sends a ping message every second. Haven't touched it since then.

**Comment by evandigby** [comment]
We were able to work around it by forcing ipv4 by switching "localhost" to 127.0.0.1. Seems it's also been reported elsewhere:

https://lists.openshift.redhat.com/openshift-archives/users/2016-August/msg00065.html
