### ISSUE TITLE
No API token found for service account "default

### ISSUE THREAD

**Issue by sachincab** [kubernetes/kubernetes#29549]
Hi Team,

I getting below error when creating pods for kube-dns addon.
According to this issue (https://github.com/kubernetes/kubernetes/issues/11222), it suggest to remove ServiceAccount flag from --admission-control in kube-apiserver.

We are trying to use ServiceAccount to propagate private docker registry credentials to pods, however it complain for No API token found for service account "default"

Also I could see empty token when describe default serviceaccount.
Tokens:            	<none>

---------------------------------------------------------------------------------------------
2016-07-25T16:22:26+02:00   2016-07-25T16:20:56+02:00   11        kube-dns-v18   ReplicationController               Warning   FailedCreate   {replication-controller }   Error creating: No API token found for service account "default", retry after the token is automatically created and added to the service account

---------------------------------------------------------------------------------------------
kubectl --namespace=kube-system describe serviceaccount default
Name:		default
Namespace:	kube-system
Labels:		<none>

Image pull secrets:	test-secret

Mountable secrets: 	test-secret

Tokens:            	<none>

---------------------------------------------------------------------------------------------

We are starting kube-apiserver with below flags and running as a container.
          command:
          - /hyperkube
          - apiserver
          - --insecure-bind-address=0.0.0.0
          - --insecure-port=8080
          - --etcd-servers=http://${etcd_elb_host}:2379
          - --allow-privileged=true
          - --service-cluster-ip-range=${svc_cidr}
          - --advertise-address=$private_ipv4
          - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota
          - --service-account-key-file=/etc/kubernetes/ssl/kube-serviceaccount.key
          - --cloud-provider=aws

---------------------------------------------------------------------------------------------

kube-controller with below flag as well
          - --service-account-private-key-file=/etc/kubernetes/ssl/kube-serviceaccount.key

---------------------------------------------------------------------------------------------

Please let us know your inputs on this and also let me know if you need any more information on this.

**Kubernetes version: v1.3.3**

Thanks!

**Comment by sachincab** [comment]
This issue has been fixed once TLS enabled in cluster.

**Comment by guillelb** [comment]
Can you explain how to do that? "This issue has been fixed once TLS enabled in cluster".
I have the same problem creating a basic deployment: 
`Sync "default/my-first-nginx-201461591" failed with unable to create pods: No API token found for service account "default", retry after the token is automatically created and added to the service account`

I have service account "default":
`# kubectl get serviceaccounts`
`NAME      SECRETS   AGE`
`default   0         1d`

But no secrets, because I created a secret but It is not associated with the serviceaccount "default".

**Comment by handsmlonely** [comment]
hi, i have the same problem in serviceaccount when i creating a ingress deplyoment.
the default secrets is still zero and  api-server cannot created it automatically
has your found any solution for this probelm?
