### ISSUE TITLE
kubernetes-dashboard pod in CrashLoopBackOff state 

### ISSUE THREAD

**Issue by rihabbanday** [kubernetes/kubernetes#29540]
I am trying to intsall Kubernetes dashboard by the command:

`kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml`.

However when I do `kubectl get po -o wide --all-namespaces` I see the status of the kubernetes-dashboard pod as "CrashLoopBackOff". The output of command `kubectl logs kubernetes-dashboard-3717423461-gxrwv --namespace=kube-system` looks like this:

`Starting HTTP server on port 9090
Creating API server client for https://192.168.3.1:443
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: the server has asked for the client to provide credentials`

Does anyone know how to fix this issue? Thanks in advance.

**Comment by matthewberkland** [comment]
Also having this issue.

**Comment by anuribs** [comment]
I fixed the issue by the following steps:
1. Get the secret by: 'kubectl get secret --namespace=kubesystem
2. Delete the secret by: 'kubectl delete secretNAME --namepace=kube-system
3. Delete the pod: `kubectl delete po podName --namespace=kube-system
The replication controller will now create a new pod that will use the new secret.
Now you should be able to access the dashboard.

**Comment by dchen1107** [comment]
@anuribs Thanks for updating your fix / solution here. I am closing the issue for now. Please re-open or file a new issue if you think we can improve the system usability and document in this case. Thanks!

**Comment by gl328518397** [comment]
Starting HTTP server on port 9090
Creating API server client for http://localhost:8080
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get http://localhost:8080/version: dial tcp 127.0.0.1:8080: getsockopt: connection refused

**Comment by gl328518397** [comment]
Starting HTTP server on port 9090
Creating API server client for https://192.168.3.1:443
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://192.168.3.1:443/version: x509: cannot validate certificate for 192.168.3.1 because it doesn't contain any IP SANs

**Comment by Hirayuki** [comment]
+1

**Comment by Seyun** [comment]
I got this problem too.

**Comment by amdslancelot** [comment]
Having the same issue here.

**Comment by gl328518397** [comment]
Having the same issue here. So what's the sollution? @dchen1107

**Comment by amdslancelot** [comment]
[update] I solved the issue by manually point to apiserver using the 'args' attribute in 'kubernetes-dashboard.yaml':
args:
          # Uncomment the following line to manually specify Kubernetes API server Host
          # If not specified, Dashboard will attempt to auto discover the API server and connect
          # to it. Uncomment only if the default does not work.
          # - --apiserver-host=http://my-address:port

**Comment by luohoufu** [comment]
i also get the error.
[kube-error.txt](https://github.com/kubernetes/kubernetes/files/583573/kube-error.txt)

**Comment by wadee** [comment]
got too.
╰─➤  kubectl logs kubernetes-dashboard-3615790904-jwxtt --namespace kube-system                                                                                                  1 ↵
Using HTTP port: 9090
Creating API server client for https://10.96.0.1:443
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.96.0.1:443/version: dial tcp 10.96.0.1:443: i/o timeout
Refer to the troubleshooting guide for more information: https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md

**Comment by vhosakot** [comment]
I see this issue too with kubernetes `1.5.4` and kubernetes-dashboard image version `gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0`.  What is the solution @dchen1107.

I installed `kubeadm` referring https://kubernetes.io/docs/getting-started-guides/kubeadm/, and then installed kubernetes-dashboard by doing

```
kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.6.0/src/deploy/kubernetes-dashboard.yaml
```

I see the kubernetes-dashboard in `CrashLoopBackOff` status and the `k8s_kubernetes-dashboard.*` container on the worker is in `Exited` state.

Below are the errors.  Has anyone successfully installed kubernetes-dashboard on `kubeadm`?

```
# kubectl --namespace=kube-system get all
NAME                                                          READY     STATUS             RESTARTS   AGE
po/calico-policy-controller-mqsmh                             1/1       Running            0          4h
po/canal-etcd-tm2rv                                           1/1       Running            0          4h
po/canal-node-3nv2t                                           3/3       Running            0          4h
po/canal-node-5fckh                                           3/3       Running            1          4h
po/canal-node-6zgq8                                           3/3       Running            0          4h
po/canal-node-rtjl8                                           3/3       Running            0          4h
po/dummy-2088944543-09w8n                                     1/1       Running            0          4h
po/etcd-vhosakot-kolla-kube1.localdomain                      1/1       Running            0          4h
po/kube-apiserver-vhosakot-kolla-kube1.localdomain            1/1       Running            2          4h
po/kube-controller-manager-vhosakot-kolla-kube1.localdomain   1/1       Running            0          4h
po/kube-discovery-1769846148-pftx5                            1/1       Running            0          4h
po/kube-dns-2924299975-9m2cp                                  4/4       Running            0          4h
po/kube-proxy-0ndsb                                           1/1       Running            0          4h
po/kube-proxy-h7qrd                                           1/1       Running            1          4h
po/kube-proxy-k6168                                           1/1       Running            0          4h
po/kube-proxy-lhn0k                                           1/1       Running            0          4h
po/kube-scheduler-vhosakot-kolla-kube1.localdomain            1/1       Running            0          4h
po/kubernetes-dashboard-3203962772-mw26t                      0/1       CrashLoopBackOff   11         41m
NAME                       CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
svc/canal-etcd             10.96.232.136    <none>        6666/TCP        4h
svc/kube-dns               10.96.0.10       <none>        53/UDP,53/TCP   4h
svc/kubernetes-dashboard   10.100.254.77    <nodes>       80:30085/TCP    41m
NAME                   DESIRED   SUCCESSFUL   AGE
jobs/configure-canal   1         1            4h
NAME                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/kube-discovery         1         1         1            1           4h
deploy/kube-dns               1         1         1            1           4h
deploy/kubernetes-dashboard   1         1         1            0           41m
NAME                                 DESIRED   CURRENT   READY     AGE
rs/calico-policy-controller          1         1         1         4h
rs/dummy-2088944543                  1         1         1         4h
rs/kube-discovery-1769846148         1         1         1         4h
rs/kube-dns-2924299975               1         1         1         4h
rs/kubernetes-dashboard-3203962772   1         1         0         41m

# kubectl --namespace=kube-system describe pod kubernetes-dashboard-3203962772-mw26t
  20m    5s    89    {kubelet vhosakot-kolla-kube2.localdomain}                        Warning    FailedSync    Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-3203962772-mw26t_kube-system(67b0d69b-0b47-11e7-8c97-7a2ed4192438)"

# kubectl --namespace=kube-system logs kubernetes-dashboard-3203962772-mw26t
Using HTTP port: 9090
Creating API server client for https://10.96.0.1:443
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.96.0.1:443/version: dial tcp 10.96.0.1:443: i/o timeout
Refer to the troubleshooting guide for more information: https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md

# docker ps -a | grep -i dash
3c33cf43d5e4        gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0   "/dashboard --port=90"   54 seconds ago      Exited (1) 22 seconds ago                       k8s_kubernetes-dashboard.9eb4d80e_kubernetes-dashboard-3203962772-mw26t_kube-system_67b0d69b-0b47-11e7-8c97-7a2ed4192438_93520bd4

# docker logs k8s_kubernetes-dashboard.9eb4d80e_kubernetes-dashboard-3203962772-mw26t_kube-system_67b0d69b-0b47-11e7-8c97-7a2ed4192438_93520bd4
Using HTTP port: 9090
Creating API server client for https://10.96.0.1:443
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.96.0.1:443/version: dial tcp 10.96.0.1:443: i/o timeout
Refer to the troubleshooting guide for more information: https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md
```

**Comment by jazoom** [comment]
Same issue here. Why did @dchen1107 even close this?

**Comment by anuribs** [comment]
I remember resolving the issue by first deleting the secret corresponding to the kube-system namespace, i.e 

`kubectl delete secret secretName -n kube-system`

The api-server will then create a new secret. Now delete the dashboard pod, and the new pod spun up by the rc/deployment will use the new secret and the errors corresponding to "credentials" should be gone.

Alteast this worked for me :)

**Comment by iordaniordanov** [comment]
Having the same issue here. So what's the sollution? @dchen1107

**Comment by pkirner** [comment]
Having the same issue with kubernetes 1.7 and kube-dashboard 1.6.1 on raspberry pi 3 with hypriot os. 
Please, can someone post the solution here?  Thanks!

**Comment by iordaniordanov** [comment]
@pkirner My issue was something with the network of my cluster. My admins deployed a new cluster and everything was working fine. Sorry but I cant help ya. This issue really shouldn't have been closed. I don't know why @dchen1107 did.

**Comment by dev-security** [comment]
Please, could anyone help with the solution?  What's the solution? @dchen1107 I do not see the fix / updated solution in @anuribs post. Thanks a lot!

**Comment by vsethi13** [comment]
In my case, I followed the troubleshooting doc [here](https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md):

But even this didn't get the dashboard up and running for me. 
1. I started fooling around and I saw (using the cmd: `kubectl get pods -a -o wide --all-namespaces` that the `kubernetes-dashboard` was actually being set up on a slave node, and not on master (not sure if that's now it should be done)
2. I started removing all the slave node one by one and eventually, the dashboard ended up getting deployed on the master node itself (it happened automatically, all hail kubernetes!)
3. As soon as the dashboard was on the master node, the 'authentication to the API Server' problem got resolved since the api-server 'service' was also running on the master node.
Tadaaaa!

**Comment by bbb31** [comment]
fwiw, this is still not resolved. Also, [random google search with same keywords](https://encrypted.google.com/search?hl=en&q=dashboard%20%22CrashLoopBackOff%22%20site%3Agithub.com) for this bug shows that each time reports are closed it's prematurely (without testing to even confirm the issue is resolved).

Also, the FAQ which is so sorely represented in the output doesn't even mention this issue.

With all the reports of this issue, it appears to be a systemic problem with the maintainers/workers of Kubernetes itself: #4569, #1109, #21 (my personal favorite; just randomly closes).

Back to Swarm it is.

**Comment by GarethOates** [comment]
This might not be best practice from a security point of view, but I was able to fix this problem by running the following command on **all** of the nodes in my cluster.

```
iptables -P FORWARD ACCEPT
```
I've ran this and it works on my internal "for play only" cluster so there's no real risk involved for me.

**Comment by dims** [comment]
looks like a persistent-long-term-problem

/reopen

**Comment by bbb31** [comment]
I actually got around this problem by changing from calico to weave.

**Comment by anash28** [comment]
Similar to @31bbb , I am experiencing this issue while using weave, However the k8s-dashboard has restarted 2569 times 
```
kubernetes-dashboard-f8bc98f94-8lsv6            0/1       CrashLoopBackOff   2569       9d
```

**Comment by redhatromero** [comment]
Trying aforementioned suggestions.... please do not close yet.

**Comment by mittaus** [comment]
> In my case, I followed the troubleshooting doc [here](https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md):
> 
> But even this didn't get the dashboard up and running for me.
> 
> 1. I started fooling around and I saw (using the cmd: `kubectl get pods -a -o wide --all-namespaces`) that the `kubernetes-dashboard` was actually being set up on a slave node, and not on master (not sure if that's now it should be done)
> 2. I started removing all the slave node one by one and eventually, the dashboard ended up getting deployed on the master node itself (it happened automatically, all hail kubernetes!)
> 3. As soon as the dashboard was on the master node, the 'authentication to the API Server' problem got resolved since the api-server 'service' was also running on the master node.
>    Tadaaaa!

Thanks @vsethi13. I followed your steps and it worked for me.
Running the `kubernetes-dashboard-*` in master node working for me

**Comment by mugdhaadhav** [comment]
Make sure the kubernetes-dashboard is running on the **master** node. Draining the slave nodes and re-creating the dashboard on master solved the issue for me.

Installation: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml

Drain nodes: kubectl drain node_name

**Comment by asc-adean** [comment]
This is occurring to me on a single node AKS deployment.  Interestingly, the `metrics-server` is having the same problems.
```
NAME                                    READY     STATUS             RESTARTS   AGE
azure-cni-networkmonitor-zzfck          1/1       Running            0          12m
heapster-5d6f9b846c-mq9lj               2/2       Running            0          14m
kube-dns-v20-7c7d7d4c66-bmzgk           4/4       Running            0          14m
kube-dns-v20-7c7d7d4c66-rx484           4/4       Running            0          14m
kube-proxy-s6tm8                        1/1       Running            0          12m
kube-svc-redirect-69dbf                 2/2       Running            0          12m
kubernetes-dashboard-68f468887f-cjslp   0/1       Error              5          6m
metrics-server-5cbc77f79f-tj5bf         0/1       CrashLoopBackOff   4          5m
tunnelfront-55b6cd7cd5-lsvpb            1/1       Running            0          14m
```
 
I am creating it via the `az` command.

```
az aks create `
  --resource-group $rg `
  --name $k8s_cluster_name `
  --generate-ssh-keys `
  --aad-server-app-id $aad_server_app_id `
  --aad-server-app-secret $aad_server_app_secret `
  --aad-client-app-id $aad_client_app_id `
  --aad-tenant-id $tenant_id `
  --dns-service-ip $k8s_dns_ip `
  --kubernetes-version 1.11.5 `
  --node-count $cluster_node_count `
  --node-vm-size $cluster_node_size `
  --service-cidr $k8s_container_subnet `
  --network-plugin azure `
  --docker-bridge-address 172.16.0.1/16 `
  --vnet-subnet-id "/subscriptions/$subscription_id/resourceGroups/$rg/providers/Microsoft.Network/virtualNetworks/$vnet_name/subnets/$subnet_name" `
  --admin-username vixxoroot `
  --ssh-key-value $ssh_pubkey `
  --location $location
```

**Comment by ccdezt** [comment]
> Make sure the kubernetes-dashboard is running on the **master** node. Draining the slave nodes and re-creating the dashboard on master solved the issue for me.

This solution by @mugdhaadhav also worked for me.

**Comment by dilipdesing** [comment]
> Make sure the kubernetes-dashboard is running on the **master** node. Draining the slave nodes and re-creating the dashboard on master solved the issue for me.
> 
> Installation: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml
> 
> Drain nodes: kubectl drain node_name

Thanks for your suggestion. This works for me as well.

**Comment by fifman** [comment]
> Make sure the kubernetes-dashboard is running on the **master** node. Draining the slave nodes and re-creating the dashboard on master solved the issue for me.
> 
> Installation: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml
> 
> Drain nodes: kubectl drain node_name

Thanks so much! This solved my problem perfectly!
