### ISSUE TITLE
High Availability documentation still references podmaster

### ISSUE THREAD

**Issue by chuckbutler** [kubernetes/kubernetes#29563]
The High Availability diagram still references Podmaster, which appears to have been deprecated as of Kubernetes v1.2

http://kubernetes.io/docs/admin/high-availability/

This should be updated to remove podmaster, and instead call out the --leader-elect flags on the apiserver/scheduler.

**Comment by rickypai** [comment]
this appear to be fixed http://kubernetes.io/docs/admin/high-availability/#master-elected-components

**Comment by chuckbutler** [comment]
I took a look and it still appears to be in the diagram

![](https://www.evernote.com/l/AX7_swi6yy5EQ6QgtwUlCG3gMYHDbVKqBT0B/image.png)

**Comment by davidewatson** [comment]
This issues has been addressed here: https://github.com/kubernetes/kubernetes/pull/26143 I believe this can now be closed.
