### ISSUE TITLE
Document per namespace sysctl and how to set them in pods

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#29572]
Source of major confusion in webserver tuning, but I'm sure that's just one victim.
- lack of documentation (best i could find was https://github.com/docker/docker/blob/master/opts/opts.go#L257)
- how do i set it on the host? (daemon set, probably)
- how do i set it in container? (privileged sidecar for network sysctls)

@kubernetes/sig-node

**Comment by ncdc** [comment]
@bprashanth see #26057

**Comment by bprashanth** [comment]
So that says: 

> network namespace: net.*

which is pretty much what I could figure out from the link to docker source above. But experimentation shows that /proc/sys/net/netfilter/nf_conntrack_max is not per ns, and I think i found a couple more. What am i missing? 

Without reading through the proposal, setting it on a contaienr pipes through to the host, or does someone still need the daemon set?

**Comment by vishh** [comment]
The sysctl proposal mentions maintaining a file that will list sysctl that
are namespace aware.
The general strategy is to let kubelet configure sysctls and not have pods
update sysctls themselves.

One of the open questions on that proposal is that of knowing which sysctls
can be safely set to a higher value by default globally... Any inputs in
that regard will help!

**Comment by bprashanth** [comment]
I can write down the common ones for webserver tuning, when i have some time. Maybe @aledbf or @PiotrSikora know off the top of their head the ones we use in https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx

**Comment by aledbf** [comment]
`net.core.somaxconn` and `net.ipv4.ip_local_port_range` are the ones used in the [sysctl](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/examples/sysctl/change-proc-values-rc.yaml#L80) example. I've been unable to find a list of the values is possible to change in a network namespace.

**Comment by vishh** [comment]
A list with safe defaults will be helpful.

**Comment by sttts** [comment]
Here is a good starting point in the kernel source to see which namespaced (per netns) sysctls exist under `net.*`:

  https://github.com/torvalds/linux/search?utf8=%E2%9C%93&q=register_net_sysctl

If I understand it correctly, a number of sysctls only exist in `init_net`, the initial network namespace. And network namespaces are not nested, but flat. So we have a good chance that we really only get those sysctls which are safe.

It's not that hard to double check: lines like

```
table[0].data = &net->xfrm.sysctl_aevent_etime;
```

set a sysctl value destination in the given network namespace object `net`.

For example here are the netns specific tables for ipv4 and core:

https://github.com/torvalds/linux/blob/a7fd20d1c476af4563e66865213474a2f9f473a4/net/ipv4/sysctl_net_ipv4.c#L668
https://github.com/torvalds/linux/blob/a7fd20d1c476af4563e66865213474a2f9f473a4/net/core/sysctl_net_core.c#L417

**Comment by sttts** [comment]
Of course, the philosophical question remains: do we want to offer all technically possible sysctls (i.e. all those that are namespaced) or only the most common ones like the two above.

**Comment by yujuhong** [comment]
I think we can close this issue now that there is documentation on sysctl and how to use it: https://kubernetes.io/docs/concepts/cluster-administration/sysctl-cluster/
