### ISSUE TITLE
Decoupling API version from storage layer

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#29578]
ref: https://github.com/kubernetes/kubernetes/pull/29528#issuecomment-235029962

What's the problem?
We don't want to couple API objects to low level storage library and thus we introduced versioner to decouple API version from storage version.
However, we coupled the logic of API versioning into storage layer currently. We should separate this layer out. Storage interface should return storage version on method calls instead.

One more problem:

``` Go
type ResponseMeta struct {
    ...
    // The resource version of the node that contained the returned object.
    ResourceVersion uint64
}
```

"ResourceVersion" here is also confusing. According to the docs, it should be storage version of the key.

**Comment by hongchaodeng** [comment]
@xiang90 @smarterclayton

**Comment by smarterclayton** [comment]
Makes sense

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.
