### ISSUE TITLE
Top-level doesn't have OWNERS

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#29575]
#29482 never got assigned to anyone by blunderbuss because there is no top-level OWNERS.

Having a top-level OWNERS file would also help as a "default" OWNERS for any new directory that doesn't have OWNERS yet.

cc @bgrant0607

**Comment by bgrant0607** [comment]
Yes, this has happened before. I agree we need a top-level OWNERS file.

**Comment by bgrant0607** [comment]
Previous instance: https://github.com/kubernetes/kubernetes/issues/26118#issuecomment-221126184

**Comment by foxish** [comment]
Should the top-level OWNERS file be the same as [pkg/OWNERS](https://github.com/kubernetes/kubernetes/blob/0ed3bd63e488b152103ea31f3d24865df0cf8d3c/pkg/OWNERS)?

**Comment by bgrant0607** [comment]
@foxish Yes, pkg/OWNERS is a good starting point. You could also add me, on the assumption that PRs touching top-level files aren't that common.
