### ISSUE TITLE
namespace level emptyDir

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#29582]
emptyDir works great to pass data between containers in a pod. Its better then using a hostPath as it is self cleaning and isolated to only those containers that need it.

In the same way, there is a need for something like a DeamonSet to provide services that can be shared between multiple Pods living on a single machine, but don't need to talk to anything else. so using a hostPath for this works too, but suffers similar issues, or a shared volume takes an unneeded performance hit. It would be nice to have a new emptyDir type volume that is named with a namespace level entry so it can be referenced in multiple pods in the same namespace, but otherwise behaves like emptyDir.

**Comment by msau42** [comment]
Would something like local PVs work for this use case?  #kubernetes/community/#306

In your pods, you can all reference the same PVC that is bound to a local PV, and the scheduler will force all the pods to land on the same node.

/sig storage

**Comment by kfox1111** [comment]
Its not that I want to force them onto the same node. but I want pods that are on the same node to be able to share storage. Ie, say I have two daemonsets. They may have overlapping nodeSelectors and where they overlap, I might want to share a bit of storage between them. This could be done with a hostPath volume, but then it has to use a path name that is unique per namespace to avoid different things from bumping into each other. a namespace aware volume could do the same thing but ensure the paths are always unique/garbage collected.

I think it would be difficult to bend the PVC mechanism in this way, as it might require one PVC per physical host, and some way to let the daemonsets abstractly request whatever PVC name that is on the host they happen to be landing on.

**Comment by msau42** [comment]
When do you cleanup the volumes?  When the namespace is destroyed?  Could you run a DaemonSet per namespace that carves out the shared storage with the namespace name, then run your apps, then after you destroy the namespace, then run another daemonset to cleanup the volumes?

**Comment by kfox1111** [comment]
I was thinking it behaves more like an emptyDir volume in that respect. The first pod that lands on a node per that namespace/name creates the dir. The last pod to leave the node referencing that namespace/name then causes it to be deleted. If nothings on the node, the volume isn't there.

**Comment by msau42** [comment]
Yeah that may be difficult to do because you would need to manage a grouping of pods vertically on each node across higher level controllers.  Managing the refcounts can get tricky. 

I think the closest you can get today is to use a daemonset to manage namespace-level directories.  If it's just a directory, it's not taking up much space if don't use it, right?

**Comment by kfox1111** [comment]
couldn't the kubelet manage it? I think its a low level operation, not a high level one.

On pod create, see if it has a namespaced-emptydir reference. if so, see if it exists. if not, mkdir it.

On the pod delete and it has a namespaced-emptydir, see if any other pod has a volume reference to it. if not, rm -rf it.

**Comment by kfox1111** [comment]
this is still quite relevant.

**Comment by kfox1111** [comment]
once csi can do pod volumes I think this should be implementable as a csi driver.

**Comment by kfox1111** [comment]
This will be enabled with the plumbing in podinline / ephemeral csi driver support in pr 68232. A driver can then be written out of tree for this.
