### ISSUE TITLE
Document how beta InitContainer respect RestartPolicy=OnFailure

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#29590]
The proposal mentions that only Always or Never is supported.  I don't see any reason not to support OnFailure (and that's the way it's implemented).

If there's agreement, I'll update the proposal.

**Comment by smarterclayton** [comment]
@kubernetes/sig-node

**Comment by dims** [comment]
SGTM @smarterclayton

**Comment by dchen1107** [comment]
There must be a misunderstand here. :-) In one of my comments to the proposal, I brought up Always does't make sense for InitContainer at all. Since we don't have per container restart policy, I suggested that if the policy is Always, it should fall back to OnFailure for alpha release so that we wouldn't be blocked by API design. I thought that is what we agreed upon, and also how the current implementation supported. 

cc/ @erictune

**Comment by Random-Liu** [comment]
IIRC, now the policy is:
* If the init container exited with exit code =0, it will not be restarted.
* If the init container exited with exit code !=0:
  * If the restart policy is `RestartPolicyNever`: it will not be restarted.
  * If the restart policy is not `RestartPolicyNever`: it will be restarted.

I believe the current logic is equivalent to Never and OnFailure.

**Comment by smarterclayton** [comment]
What I meant to qualify was that in the proposal we describe the two extremes (always and never) but don't describe on failure.  The behavior is never Always, but the proposal doesn't explain the fallback clearly.

**Comment by dchen1107** [comment]
SGTM

**Comment by goltermann** [comment]
@smarterclayton @dchen1107 are we going to fix this for 1.4?  Or punt to 1.5?

**Comment by smarterclayton** [comment]
Punt, this is docs only change.

**Comment by dims** [comment]
ok to move this to 1.6? please holler if not appropriate

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by marun** [comment]
Assuming this shouldn't block 1.7, moving to 1.8.

**Comment by xiangpengzhao** [comment]
InitContainer is already GA and we will remove beta annotations. I think this issue is outdated. (Maybe @smarterclayton had already updated the proposals.) Anyway, we can close this issue.

/close

Feel free to correct me if I'm wrong.

cc @smarterclayton
