### ISSUE TITLE
Collect and archive kube-system pod resource usage (especially memory) from scalability e2e

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#29597]
So we can give accurate guidance on sizing them in large clusters.

ref/ #21500

cc/ @bprashanth @wojtek-t @gmarek

**Comment by gmarek** [comment]
We have them in our scalability test results (100 node clusters) and we check if they're inside the bounds. We can try running full 2k Node cluster with resource-gathering on, though I may need some tweaking to get it working on such a big scale.

**Comment by davidopp** [comment]
That's great. I think the things @bprashanth would want are running it on 2k node clusters (like you said) and also keeping some archive of the last N results in an easy-to-find place.

**Comment by gmarek** [comment]
OK, I'll speak with @bprashanth in person.

**Comment by bprashanth** [comment]
We should track this for all default installed system daemons (dns, fluent, proxy etc). How do we check if they're inside bounds? Speaking to @gmarek one idea to track them was to display them in the perfdash, but just a simple test will do I suppose. Is there an example of a test that tracks resource usage of an existing cluster addon that i can copy for dns and proxy?

**Comment by gmarek** [comment]
You can use any e2e test run with a `gather-resource-usage=true` flag. It will gather and print resource usage for all kube-system pods throughout the test run.

**Comment by bprashanth** [comment]
Alright, we should start measure kube-dns resource usage through a soak e2e then. I can take a stab at it when i have the time. We should also write something similar for all core components. 
@matchstick fyi

**Comment by porridge** [comment]
http://perf-dash.k8s.io/ can display memory across runs since https://github.com/kubernetes/contrib/pull/2790 and https://github.com/kubernetes/contrib/pull/2796
/close
