### ISSUE TITLE
[1.3.2] Pod stuck in the ContainerCreating state while mounting secret timeout

### ISSUE THREAD

**Issue by Trane9991** [kubernetes/kubernetes#29617]
Hello, I have GKE 1.3.2 version and my cluster stopped being able to mount Secret files as Volumes.

I'm keep getting:
```
 timeout expired waiting for volumes to attach/mount for pod
```
after checking instances logs on the StackDriver i can see next message:
```
Failed cleaning pods: [remove /var/lib/kubelet/pods/08433a42-5339-11e6-95d5-42010a84003a/volumes/kubernetes.io~secret/test-secret: device or resource busy, remove /var/lib/kubelet/pods/3fc204e9-5337-11e6-95d5-42010a84003a/volumes/kubernetes.io~secret/test-secret: device or resource busy, remove /var/lib/kubelet/pods/5320c80e-5332-11e6-95d5-42010a84003a/volumes/kubernetes.io~secret/test-secret: device or resource busy]
```

secrets with other names working normal, but the secret with name **text-secret** make pod hangs.
```
NAME                                 READY     STATUS              RESTARTS   AGE       NODE
jnlp-slave-7b37c907f1541   0/1       ContainerCreating
```
and not trying to restart it either.

**UPDATE:**
Looks like issue related to the https://github.com/kubernetes/kubernetes/issues/29059/
Default token keeps being remounted and my  secret never gets mounted and then pod failing with the timeout.

I just downgraded GKE nodes to the 1.2.5 version and everything seems ok for now.

Please take a look at this bug since it's pretty critical. Pods creating hangs randomly due inability to mount volume.

**Comment by Trane9991** [comment]
Also, I'm having the issue with mounting default secrets sometime:

```
I0727 09:10:23.147298    3596 server.go:959] GET /healthz: (44.141µs) 200 [[curl/7.26.0] 127.0.0.1:49493]
I0727 09:10:30.389115    3596 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/secret/default-token-qskza" (spec.Name: "default-token-qskza") to pod "41f49f61-5341-11e6-95d5-42010a84003a" (UID: "41f49f61-5341-11e
6-95d5-42010a84003a"). Volume is already mounted to pod, but remount was requested.
I0727 09:10:30.392877    3596 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/default-token-qskza" (spec.Name: "default-token-qskza") pod "41f49f61-5341-11e6-95d5-42010a84003a" (UID: "41f49f61-5341-
11e6-95d5-42010a84003a").
```

and this loop is endless. Volume keep gettign remounted.

**Comment by Trane9991** [comment]
Still getting random Pod stuck while mounting secret on the GKE 1.3.3.

**Comment by saad-ali** [comment]
@Trane9991 Based on what you provided, you hit an issue where if a secret fails to unmount it will be unable to mount to any other pod. It was fixed by https://github.com/kubernetes/kubernetes/pull/28939.

The fix is in [v1.3.4](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md/#v134), which should be in GKE soon.

**Comment by saad-ali** [comment]
Closing this issue. Please re-open if you run into it in v1.3.4+

**Comment by boydgreenfield** [comment]
I'm experiencing this exact issue on 1.3.4 (albeit on AWS running jessie not GKE). 

Has anyone successfully found a workaround that doesn't involve patching k8s itself?

We get random pods getting stuck in ContainerCreating (5-10%ish), which quite badly breaks our use case (spinning up containers on user request). We were previously on ~1.2.3 with no problems. I did downgrade to ~1.2.6 but had the same stalled container creation hang. 

(Sorry for lack of precise version numbers, on a phone)

**Comment by saad-ali** [comment]
@boydgreenfield Based on what you've said you're experiencing this issue both with v1.2 and v1.3 which means it is likely not the issue described above. If you can provide more information I can help you debug: What version of master/node are you running. How are you deploying your pods? For the pods stuck in ContainerCreating, could you grab the `/var/log/kubelet.log` files from those nodes during the incident and the `/var/log/kube-controller-manager.log` file from the master.

**Comment by boydgreenfield** [comment]
@saad-ali – I was on a mobile device earlier but will respond with logs for 1.3 in the morning Pacific. Apologies about the less-than-complete error message this evening.

**Comment by saad-ali** [comment]
@boydgreenfield No problem! And I'd love to see the 1.2 logs as well if you're experiencing the issue on both and still have access to them.
