### ISSUE TITLE
AWS: instances "user-data" encrypted, can't copy/modify

### ISSUE THREAD

**Issue by Dmitry1987** [kubernetes/kubernetes#29616]
Hello, I am trying to setup a "spot instances" group using some external service, not 'AWS Spot fleet', and I need to provide "user-data" text (together with AMI image, and other options) for Node instances.
But initial autoscaling group with minions that was created, has "user-data" encrypted.
What is the encryption type and how can I decrypt it? (and is it possible to avoid encryption of this data by installer script?)

As I understand from some digging, those are settings for Salt that will install all services of a node. Can I maybe copy those settings from inside the minion, is it stored there somewhere?  (kinda like chef cache with cookbooks where recent cookbooks that were run are stored)

My K8s is v1.3, installed with "export KUBERNETES_PROVIDER=aws; curl -sS https://get.k8s.io | bash".

Regards,
Dima

**Comment by davidchua** [comment]
Hi @Dmitry1987, I've experienced the same problem. To get around it you'll need to do a couple of steps:

1. Get your user-data directly from aws cli
```
$ aws autoscaling describe-launch-configurations
```

2. Take that user-data, copy and paste it into your new launch configuration. Ensure that __Input is already base64 encoded__ is checked. And also that you don't accidentally add linebreaks to your copy-paste.

After that your new launch configuration should be created and you can get your cluster up and running.

**Comment by Dmitry1987** [comment]
@davidchua , awesome! thank you!

**Comment by Dmitry1987** [comment]
For anyone else that will stumble across this question:
I found a nice article that explained how to decode this gzip user-data (appeared that it's not encryption but a gzip)

run this to save launch configurations: **aws autoscaling describe-launch-configurations > launch-configs.json**   (as suggested by @davidchua )
-> then take the user-data base64 text from this json, and paste to userdata-orig.b64 file
then run:   **cat userdata-orig.b64 | base64 -d | zcat > userdata-orig.sh**
and you will have the clear text in "userdata-orig.sh".

**Comment by ostankin** [comment]
Just one more thought on top of that. The `aws autoscaling describe-launch-configurations` may return an empty result if for some reason your default region is not the same you are working with. A rare case, but still may be confusing if someone happens to run into it. To get things straight, just add the region parameter:
```
aws autoscaling describe-launch-configurations --region=us-east-1
```

**Comment by designgrill** [comment]
Expanding on what @Dmitry1987 shared:

`aws ec2 describe-instance-attribute --instance-id i-xxxxxxxxxxxxxxxxx --attribute userData --output text --query "UserData.Value" | base64 --decode | zcat`

This will print the UserData
