### ISSUE TITLE
Downward API volume plugin and env should have parity

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#29644]
Currently, the downward API is fragmented slightly across the environment and volume plugin flavors.

The volume plugin supports:
- pod name
- pod namespace
- pod labels
- pod annotations
- resource limits

The environment API supports:
- pod name
- pod namespace
- pod IP
- resource limits

The disparity is due to a couple different factors:
1.  labels and annotations can be updated -- but we currently do not have the ability of restarting a pod when the environment changes, so labels and annotations are not available via env
2.  the pod IP is not available when the volumes are created for a pod in the pod lifecycle, so the pod IP is not available via the volume plugin

There is desire in the community to continue developing these features.  We should:
1.  Ensure that future features in the downward API are added with parity in env and volume plugin.  This may increase the total time to develop new features for downward API, but if we do not make the commitment to do it this way, we will never likely have parity.
2.  Bring the current features into parity.

cc @kubernetes/sig-apps

**Comment by pmorie** [comment]
I'm labeling this next-candidate because I intend to fix it for the 1.5 release.

**Comment by michelleN** [comment]
@pmorie feel free to add this to the [document of proposed work](https://docs.google.com/document/d/1uAhuaEGWPCQXNL_ptzemuXKqFzLuV1FENWn_n39u1G0/edit#heading=h.f61w6urq0j0h) in SIG-Apps for 1.5 if you'd like to discuss or get feedback on this from the sig.

**Comment by pmorie** [comment]
@michelleN I will do that (probably tomorrow, about to head out)
