### ISSUE TITLE
PetSet describer should show the pod template, like RC / D / DS

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#29651]
Makes it hard to see what a petset is supposed to be doing.

Should just be able to reuse the template displaying code.

@bprashanth

**Comment by smarterclayton** [comment]
Also, no scaler / reaper for pet set.  I may tackle some of these, just listing these out as I play around with PetSets and test various things.

**Comment by smarterclayton** [comment]
client/unversioned.Interface doesn't have an `Apps()` method (going to open a PR for that shortly).

**Comment by smarterclayton** [comment]
PetSet internal Replicas type in spec and status needs to be int32

**Comment by kargakis** [comment]
Note that none of DS / D / RS show the pod template too

**Comment by kargakis** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/42283
