### ISSUE TITLE
adding the same label key twice should error

### ISSUE THREAD

**Issue by eparis** [kubernetes/kubernetes#2965]
If I create an object with
labels: {
  name="hello",
  name="goodbye"
}

The object will be accepted by the apiserver, but the "hello" label will be lost.  This should either join them together, or be an error.  Silently dropping the first is bad news.

**Comment by bgrant0607** [comment]
Maybe we could do this in the swagger validation pass?

**Comment by brendandburns** [comment]
Note that #34407 (sadly) doesn't fix this error for .yaml files, since the YAML conversion doesn't preserve the duplicated key.

I guess we'll need to extend validate to handle streaming YAML too...

**Comment by AdoHe** [comment]
```
I guess we'll need to extend validate to handle streaming YAML too...
```
client side validation or server side?

**Comment by brendandburns** [comment]
client side.
