### ISSUE TITLE
move RangeRegistry to a separate package

### ISSUE THREAD

**Issue by AdoHe** [kubernetes/kubernetes#29668]
FYI. I am implementing other resource allocation for our internal kubernetes version, and want to use this interface, now it resides in `service` package, but I really want to move it to other package like `rangeallocation`. @smarterclayton @lavalamp wdyt?

**Comment by smarterclayton** [comment]
Yes, range allocation was always intended to be generic, although there are a *few* specific wrinkles with services.

Here is how we're using it in OpenShift - https://github.com/openshift/origin/blob/master/pkg/security/uidallocator/allocator.go (for allocating ranges of Unix UIDs) and we have someone working on external IP blocks.
