### ISSUE TITLE
Kubectl bash completion doesn't complete on port-forward

### ISSUE THREAD

**Issue by ConorNevin** [kubernetes/kubernetes#29665]
On Kubectl v1.3.2 the kubectl bash completion doesn't complete pod names when using the kubectl port-forward command

**Comment by xingzhou** [comment]
this should be part of #25287, I'm doing the patches and one of the commits will cover this ticket

**Comment by xiangpengzhao** [comment]
This had been fixed by @xingzhou in #31333.

Will close.

@thockin
