### ISSUE TITLE
--master=fqdn:port fails to work

### ISSUE THREAD

**Issue by eparis** [kubernetes/kubernetes#2967]
If you use:

--master=ip:port

It works.  If you use:

--master=http://fqdn:port

It works.  But if you use

--master=fqdn:port it fails with:

unsupported protocol scheme "fqdn"

Seems like this should work too....

**Comment by roberthbailey** [comment]
@eparis Is this for the master/kubelet/kubectl command line?

**Comment by eparis** [comment]
I'd have to go back and look, but as I recall:

kubectl doesn't take --master= it takes --server
kubelet doesn't take --master= it takes --api_servers=

so this would be limited to the proxy, scheduler, and controller-manager.  Which all take --master, although I don't remember if that is shared code...

**Comment by eparis** [comment]
kubelet also has a similar same problem:

works:
--api_servers=127.0.0.1:8080
--api_servers=http://127.0.0.1:8080
--api_servers=http://localhost:8080

fails:
--api_servers=localhost:8080
