### ISSUE TITLE
kubectl view commands

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#29679]
We're adding `kubectl set` commands to change specific fields #21648.

Similarly, I think we need `kubectl view` commands (`get` already has a meaning) to extract specific fields without needing jsonpath or Go templates.

| Subcommand | Issue # | PR # | Assignee |
| --- | --- | --- | --- |
| \- [ ] image |  | #51428 | @zjj2wry |
| \- [ ] annotation | #19817 |  |  |
| \- [ ] label | #19817 |  |  |
| \- [ ] env |  |  |  |
| \- [ ] probe |  |  |  |
| \- [ ] volume |  |  |  |
| \- [ ] limits |  |  |  |
| \- [ ] security |  |  |  |
| \- [ ] port |  |  |  |

**Comment by pwittrock** [comment]
@alexbrand This would also be a good issue to get started

**Comment by alexbrand** [comment]
Sounds good @pwittrock. I'll check it out.

**Comment by pwittrock** [comment]
@alexbrand How is this coming?

**Comment by alexbrand** [comment]
Sorry @pwittrock, got caught up with other stuff. I hope to have something by the end of this week.

**Comment by pwittrock** [comment]
@alexbrand No worries.  In that case, this will wait until the 1.5 release.  Expect 1.5 work to be pretty low on my priority list until 1.4 is out.

**Comment by alexbrand** [comment]
Sounds good. Thanks @pwittrock

**Comment by alexbrand** [comment]
@pwittrock, @bgrant0607 Is the goal here to have counterparts to the `kubectl set` commands (e.g. `kubectl set image` <-> `kubectl view image`), or a generic `kubectl view` command that can be used to get any field from any object (although I am not sure how that could be achieved)?

**Comment by pwittrock** [comment]
The former.  Json path can be used for the latter.

**Comment by kargakis** [comment]
cc: @kubernetes/kubectl

**Comment by smarterclayton** [comment]
So I have a question... what is the input to view going to look like?

```
kubectl view pod/foo status.podIP
```

?  How is that simpler than

```
kubectl get pod/foo --jsonpath .status.podIP
```

?

**Comment by smarterclayton** [comment]
We save 10 characters and double the amount of code?

**Comment by smarterclayton** [comment]
Or are you suggesting that the high value subtypes get converted (like `kubectl view env`)?

**Comment by pwittrock** [comment]
@smarterclayton I believe the goal is that we have symmetric `view` commands for the `set` commands.  For instance, if a user performs a `kubectl set image nginx:3.0`, but wants to check the current image before changing it, we should provide a `kubectl view image` command.  Using jsonpath to parse out the image would require the user know the path to the image field and is not symmetric with the syntax for set.

**Comment by smarterclayton** [comment]
Ok.

**Comment by bgrant0607** [comment]
@pwittrock @smarterclayton In addition to subcommands symmetric with `set`, which a user might expect to exist, I would like to add a few high-value status fields, also. Fields that commonly occur in our scripts (search for go-template and jsonpath). Node, service, and pod internal/external IP addresses come to mind.

**Comment by alexbrand** [comment]
Thanks @bgrant0607 

How will we handle printing to the console? I suspect each subcommand will have it's own output format?

For example, I currently have this:
```
$ ./kubectl view image deployments nginx
CONTAINER NAME   IMAGE
nginx            nginx
```

**Comment by bgrant0607** [comment]
@alexbrand My current thinking is that I'd like the commands to be specific enough to output just one piece of information per object, single column, with no headers, to facilitate usage in scripts. My goal is to eliminate the need for go-template/jsonpath in the most common cases.

**Comment by alexbrand** [comment]
Gotcha - that makse sense to me. I guess that would mean that we wouldn't support something like 
`kubectl view image deployments --all`?

**Comment by erictune** [comment]
I want to view the created-by annotation of a pod.  You cannot do this with jsonpath, and it will be verbose to do with golang templates.  Problem is that `kubernetes.io/created-by` has 3 special characters in it.

What would that look like?

```
$ kubectl view created-by pods nginx-3ks4x
CREATED-BY
replicaSet/nginx-7md8d
$ kubectl view created-by replicaSet/nginx-7md8d
deployments/nginx
$ kubectl view created-by deployments/nginx
<none>
$ kubectl view created-by pods nginx-3ks4x --recursive
deployments/nginx
```

**Comment by kargakis** [comment]
> What would that look like?

Annotation keys are not special. Annotations would have to be a separate subcommand (analogous to how you can set annotations currently)

So I would expect something like `kubectl view annotations pod/nginx-3ks4x | grep created-by`

**Comment by smarterclayton** [comment]
Why can't you print the created by annotation of a pod with jsonpath?

{ .metadata.annotations['fullkey'] }

?

**Comment by ymqytw** [comment]
I'm using this to keep tracking the progress of all the `kubectl view` subcommands. `kubectl view` is the counterpart of `kubectl set`. I think it should at least have the subcommands that `kubectl set` has. 
Ref: [`kubectl set`](https://github.com/kubernetes/kubernetes/issues/21648#issuecomment-250881311) #21648

| Subcommand  |  PR #     |  Assignee | 
|---|---|---|---|
| - [x] image           | #33034 | @alexbrand 
| - [ ] env               |               | 
| - [ ] probe             |              | 
| - [ ] volume         |               | 
| - [ ] limits              |               | 
| - [ ] security          |               | 
| - [ ] port             |               | 
| - [ ] trigger        |                |

**Comment by bgrant0607** [comment]
Listing containers might be a use case for view:
http://stackoverflow.com/questions/33924198/how-do-you-cleanly-list-all-the-containers-in-a-kubernetes-pod/33925363#33925363

**Comment by kargakis** [comment]
Listing annotations and labels: https://github.com/kubernetes/kubernetes/issues/19817

**Comment by karsinkk** [comment]
@bgrant0607  I saw the for-new-contributors label, Can I have a go at this?, seems interesting.

**Comment by AdoHe** [comment]
@karsinkk that would be great, we are going to add more view subcommands in 1.6, if you could help, really appreciate that.

**Comment by pwittrock** [comment]
@karsinkk Yeah that would be great.  Are you able to attend the sig-cli meeting next week?  We are making some improvements to the contributor process for kubectl, and it would be great if you could attend.

**Comment by karsinkk** [comment]
@pwittrock Thanks!. I'd be happy to attend the meeting!

**Comment by pwittrock** [comment]
@karsinkk Great.  See you there.

**Comment by zjj2wry** [comment]
@pwittrock @mengqiy i want to implement this feature to replace --list option. do you have bandwidth help review?

**Comment by zjj2wry** [comment]
@mengqiy i open a PR in #51428 implement ```kubectl set image```, i'd like that can became first ```kubectl view command```. and i will continue add other command in 1.9 milestone ~.~, are you mind continue maintain your table，it will help avoid same work for contributor. 🙏

**Comment by mengqiy** [comment]
@zjj2wry Great! Thank you!
I updated the table :)

**Comment by zjj2wry** [comment]
@bgrant0607 @pwittrock @mengqiy we still need this command？

**Comment by warmchang** [comment]
👍

**Comment by marcstreeter** [comment]
was this supposed to be closed?
