### ISSUE TITLE
Add the option to bind to a different address with kubectl port-forward

### ISSUE THREAD

**Issue by spacepluk** [kubernetes/kubernetes#29678]
Even a switch to bind to `0.0.0.0` would do the trick for me.  My use case is debugging when the client needs to be in a Windows VM.

**Comment by pwittrock** [comment]
@spacepluk Would you be interested in implementing this feature?

[Development Guide](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md)
 [Kubectl Code](https://github.com/kubernetes/kubernetes/tree/master/pkg/kubectl)

**Comment by pwittrock** [comment]
cc @pwittrock

**Comment by spacepluk** [comment]
hi there, I'm a bit swamped right now but hopefully I'll have some time next week to give it a try.  I already hacked the binding address to make it work for me, so it should only be a matter of figuring out how you manage the cli parameters and try to write some decent go :)

**Comment by zedfauji** [comment]
@pwittrock i would be interested in implementing this feature. will send a pull request.

**Comment by zedfauji** [comment]
@spacepluk  if you have managed a workaround , it would be nice to share with the community :)

**Comment by xiangpengzhao** [comment]
@zedfauji any updates?

There are several issues on this feature request. #43692, #36152, #40053 and this one. I'd prefer that we follow #43692 and close others.

WDYT? @thockin

**Comment by thockin** [comment]
I don't think #43692 is what you wanted?

**Comment by xiangpengzhao** [comment]
I'm sorry, my bad. It's #43962.

**Comment by thockin** [comment]
MOving to #43962 as canonical bug

**Comment by Baykonur** [comment]
+1. Till this is implemented, ssh tunneling can be used on a (yet another) separate terminal (assuming port 8000 is not used on any interface on the host):
`sudo ssh -N -L 0.0.0.0:8000:localhost:8888 userID@host`

and then go to your web-browser and type: http://host:8000
