### ISSUE TITLE
GPU volume injection support

### ISSUE THREAD

**Issue by liyubobj** [kubernetes/kubernetes#29671]
As GPU support on k8s is comming #28216 , we plan to implement GPU volume injection support for kublet and k8sm executor, as what `nvidia-docker-plugin` did: https://github.com/NVIDIA/nvidia-docker. This feature can inject GPU driver into docker as a volume, so that no GPU driver is required for GPU docker image to talk with GPU. 

We have two choices of this implementation:
* Integrate nvidia-docker-plugin into k8s
* Native implementation to mimic nvidia-docker-plugin

Any comments on it?

**Comment by therc** [comment]
This was the main/first use case for #23892 
Feel free to comment there
