### ISSUE TITLE
Investigate dns helathz container spikes

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#29688]
Observed weird memory spikes for both the dns healthz and kube-dns pods in production. Kube-dns didn't oom because there's enough headroom, but healthz did. I can't explain the spikes yet. I tried a bunch of different repros: no resolv.conf, bad nslookup command, sharing the node with cpu hogs etc, but was unable to trigger it. The memory grows, but stays under 10Mi. 

As a short term mitigation, we stole some ram from kube-dns, because it was always comfortably within limits. 

https://github.com/kubernetes/contrib/blob/master/exec-healthz/exechealthz.go
Related b/30262367

**Comment by bowei** [comment]
can be closed -- healthz has been removed

**Comment by bowei** [comment]
@thockin @bprashanth -- close issue?
