### ISSUE TITLE
error or display unhealthy backend if ingress update adds ClusterIP service

### ISSUE THREAD

**Issue by jmhodges** [kubernetes/kubernetes#29709]
I added a new rule to my ingress that added another service, but had not realized I needed to make my service a NodePort instead of a ClusterIP. The `kubectl replace` took the update, and the rule seemed to be added correctly when I did a describe but the backend never actually got put in place.

It would be nice for the replace to either error out when the service is the wrong type or for it to say that the backend was `UNHEALTHY` instead of it being left out of the `kubectl describe` and similar.

(I had previously opened up all of the possible relevant ports to my ingresses.)

**Comment by xiangpengzhao** [comment]
/sig network

@thockin

**Comment by thockin** [comment]
Not every ingress implementation needs NodePort, so this is tricky.

@nicksardo

**Comment by nicksardo** [comment]
I don't think there's anything we can do in validation because of the different implementations. The GCE ingress controller should surface an event and be visible when describing the ingress object. Do you remember which controller with which you experienced this?

**Comment by jmhodges** [comment]
It was the GLB one for GKE

**Comment by nicksardo** [comment]
The GCE ingress controller does raise an error when this wrong configuration is set: https://github.com/kubernetes/ingress-gce/issues/75.  After a refactor of this controller, it'll be able to raise an event prior to creating any GCP resources, so this experience will be much better. 

With regards to getting immediate validation at `kubectl create/edit`, I think that'll be a topic during the future-of-ingress discussion. 

/close
