### ISSUE TITLE
AWS: bootstrap fails in us-west-1c: timeout downloading kubernetes-server binary

### ISSUE THREAD

**Issue by dhasenancyngn** [kubernetes/kubernetes#29705]
Command used to start the cluster:

```
env KUBERNETES_PROVIDER=aws AWS_S3_REGION=us-west-1 KUBE_AWS_ZONE=us-west-1c KUBE_ENABLE_NODE_PUBLIC_IP=false ~/.local/opt/kubernetes/cluster/kube-up.sh
```

The master node starts (or rather, it starts and is unreachable, but if I stop and restart the instance, it becomes reachable), but kubernetes doesn't come up on the node. With some investigation, I discovered that `download-or-bust` sets a timeout of 80 seconds to download each file. I was able to download it manually, but the download took between five and six minutes.

When I extended the timeout from 80 seconds to 600, the bootstrap script completed successfully.

It is also possible that the file is available in the local region and would be faster there, which would allow you to maintain the timeout if the bootstrap script could look up the closest location for the file.

`kubectl version` shows:

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"283137936a498aed572ee22af6774b6fb6e9fd94", GitTreeState:"clean", BuildDate:"2016-07-01T19:26:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

The master node was started with AMI `k8s-1.3-debian-jessie-amd64-hvm-ebs-2016-06-18 (ami-6edb9e0e)`.

**Comment by dhasenancyngn** [comment]
For reference, I do not experience this problem if I bring up the cluster in us-east-1.

**Comment by justinsb** [comment]
I believe this is fixed; we raised some timeouts.  Please reopen if this is still happening.
