### ISSUE TITLE
Generic way to grant users access to databases

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#29708]
Currently databases like mysql have several ways to lock access: source ip, user/password, ssl etc. There's a lot of confusion about how to do this on various platforms. Some people use cloudsql and setup a service accout proxy, or run a petset mysql and whiltelist ips/hostnames, just grant root access to 0.0.0.0 etc. 

We should figure out what works best cross platform and come up with good documentation.

@kubernetes/sig-apps @smarterclayton are secrets sufficient? I know cloudsql has some twists that  @apelisse and @girishkalele were debugging, maybe there're others?

**Comment by smarterclayton** [comment]
Interestingly the way approach this today in OpenShift is to generate
a unique secret at instantiating time.  With templates and the ability
to create a secret that "requests" some level of entropy on creation
we can approximate that in Kube, or just use things like "kubectl
create secret tls" in more forms.  I'd like to see secret generation
(or at least the ability to request a unique value be generated) to be
a bit like generatedName - you want a secret but you aren't particular
what's in it.  Things like automatic serving cert generation based on
secret / ingress DNS are a logical next step beyond that.

**Comment by bprashanth** [comment]
We still need to hook up the user - secret - db, right? or is it fine to leave that to the admin? eg: with mysql a new user + password needs to be added to the db, or each pet in the petset needs access to the master. Granting access usually involves sending some grant commands over tcp, I suppose we can do that with an `on-change` notification that triggers the master to notice a new member and auto-add it/its secrets.

**Comment by smarterclayton** [comment]
When we do first party stuff (stuff we expect people to consume), typically
we have the init container / container prime the DB, whichever one is the
"master" (whatever that means, on-start / on-change) takes responsibility
for adding that into the DB if the db is net new, just because that ends up
with a good experience for end users.  Not strictly required, and puts a
burden on the image author, but...  The pattern of "the DB password is in
the secret and used by the container" is generally worth it (because it
makes the container secure by default and reusable), the generation really
adds the next step of "people don't get lazy and just hardcode
admin:password" but isn't strictly required for sure.

**Comment by erictune** [comment]
Auto-generating a random root password for databases is good.
Here is an example of how it is done in a Helm Chart:
https://github.com/kubernetes/charts/blob/882aa5db0e8f8946997936a8cb6fd8c3db04af1f/stable/mysql/templates/secrets.yaml#L15

Server-side secret generation could be useful.  I'd do that after we make progress on vault/HSM integration.

In the case of a "general purpose DB", where users are added after the DB is created, I'd expect a
DBA to be comfortable with imperatively using existing mysql commands, and develops scripts to aid with this.  e.g.:
```sh
#!/bin/sh
# usage: $0 username database-ip database-port
password=$(random password utility)
kubectl create secret generic dbpass-$user --from-literal=user=$1 --from-literal=password=$password 
mysql -h $2 -p $p -e "GRANT USAGE ON *.* TO $user IDENTIFIED BY '$password';"
echo "New password created in secret dbpass-$user
```

For a DB that is a "dedicated" storage for a larger stack, with a sole consumer, like a forum or wordpress, then I would expect the chart to generate secrets for exactly the roles needed, and init container can inject the initial users.  Upgrades that add roles would need to reconcile the SQL's ACL tables with any new secrets.

I can envision a system like https://github.com/containous/traefik or https://github.com/Mashape/kong.  That thing would be a good place to do Source-IP rules.
But that thing is not going to have the full power of the MySql GRANT command (http://dev.mysql.com/doc/refman/5.7/en/grant.html).  So there is a tradeoff between depth of features vs ease of integration.




3) DB is fronted with a

**Comment by bprashanth** [comment]
I'll add that most dbs allow non-source-ip based auth (password/username@hostname). The client takes a hostname (eg: `mysql -u foo -ptest -h hostname`) and even if the ip is used, the db will perform a reverse lookup. So that's preferable, since we don't offer stable ips.

**Comment by smarterclayton** [comment]
/close

I don't think there's enough reason to keep this specific issue open
