### ISSUE TITLE
update kube-dns changelog

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#29712]
A couple of intermediate commits have caused changelog drift in a way that the current list of events doesn't make sense. Eg: https://github.com/kubernetes/kubernetes/commit/7be429307bdc7fc545c671e46be91f27e322f378 updated `Version 1.5 (Thu June 23 2016 Nikhil Jindal <nikhiljindal@google.com>)` but the current version is v17.

Nikhil please update with the context you have, and then reassign to me so I can dig and finish up the timeline.

**Comment by nikhiljindal** [comment]
Sorry what do you mean by current version is v17?
I see that the latest image is 1.6: https://gcr.io/v2/google_containers/kubedns-arm64/tags/list

I had built and pushed 1.5 and had updated the changelog.
looks like @girishkalele had updated the image to 1.6 in https://github.com/kubernetes/kubernetes/pull/28247, but didnt update the changelog.

Assigning to him.

**Comment by bprashanth** [comment]
That's the image version, it looks like we stopped tracking changes to the yaml alltogether. 
I'm looking for a way to track discrepancy between the `.in` files and their `.sed`/`.base` counterparts, since we don't really validate that they're the same AFAIK. 

Previously everything was in a single repo so it wasn't an issue. 
By v17 I mean the kubedns version (bumped up on changes to either yaml or actual image): https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/skydns-rc.yaml.in#L39

**Comment by girishkalele** [comment]
I will take a look at the Changelogs and update them.

The .base files are the root changes - the .in and .sed files are generated by the Makefile. Any manual changes that are not in .base would get overwritten.
