### ISSUE TITLE
AWS: kube-up script generates S3 bucket name that collides with an existing bucket

### ISSUE THREAD

**Issue by hankjacobs** [kubernetes/kubernetes#29718]
When using the kube-up script for AWS, a conflicting S3 bucket name is generated if the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables are set to something that differs from what resides in ~/.aws/credentials AND the credentials that reside there were used to set up a cluster. 

I believe this is due to the use of `$(aws configure get aws_access_key_id)` as one part of the string hashed to generate the default S3 bucket name. See [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/aws/util.sh#L607).

One solution is to use the AWS_ACCESS_KEY_ID environment variable if it is set and to use `$(aws configure get aws_access_key_id)` if it's not set.

**Comment by justinsb** [comment]
Thanks for the report - this is true, but as kube-up is in maintenance mode we're likely not going to change it.

kops does not have this issue, in that you specify the bucket directly.
