### ISSUE TITLE
Make federation DNS TTL configurable

### ISSUE THREAD

**Issue by saturnism** [kubernetes/kubernetes#29723]
According to doc:
http://kubernetes.io/docs/user-guide/federation/federated-services/#handling-failures-of-backend-pods-and-whole-clusters
"Due to the latency inherent in DNS caching (the cache timeout, or TTL for Federated Service DNS records is configured to 3 minutes, by default, but can be adjusted)"

Currently, the federation DNS TTL seems to be fixed at 180 seconds. What's the right way to adjust it?

**Comment by bowei** [comment]
add-area federation

**Comment by quinton-hoole** [comment]
Indeed, this is still a hard-coded constant.  Should be moved to run-time configuration.

**Comment by bowei** [comment]
This should be easy to do, kube-dns already pulls configuration from a config map..

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#61.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
