### ISSUE TITLE
[Kubelet] Refactor kubelet to add a Node Capacity/Allocatable Provider Interface.

### ISSUE THREAD

**Issue by dubstack** [kubernetes/kubernetes#29725]
This is tied to the upstream issue #27204 which introduces pod level cgroups in Kubernetes.

For accessing the node resource allocatable quantity I would be adding a Node Capacity/Allocatable Provider Interface.This interface would support methods to return the node capacity and allocatable values. 

Adding this interface would also help us simplify the current method of getting node capacity and allocatable values in the kubelet and container manager.
I have listed down places where I think this interface can be used.
1. Set container resource limits as node allocatable in defaultPodLimitsForDownwardApi. 
   @derekwaynecarr Why do we currently set the container limits to Node Capacity and not Allocatable values?
2. If cgroup root is specified and it's not system root(ie. "/") we will set resource limits on specified cgroup_root to node allocatable values.
3. Pod and cgroup resource limits would be capped by the Node allocatable values.

@yujuhong @derekwaynecarr @vishh I was not sure as to where to have this interface. 
Particularly how to get the Kubelet's cached node status from outside of Kubelet?? 
Or only the kubelet has access to this information. If that is the case then we can just have this interface in the kubelet and pass it down to the container Manager.

cc @kubernetes/sig-node

**Comment by dubstack** [comment]
@derekwaynecarr After speaking with @yujuhong offline, we concluded that it would be a good idea to have this Node Capacity Provider Interface in the Kubelet and pass it down to the Container Manager. 

Also Why we are currently setting the container limits to Node Capacity and not Allocatable values in defaultPodLimitsForDownwardApi?

**Comment by derekwaynecarr** [comment]
@dubstack - we updated to use Allocatable in downward API

/cc @aveshagarwal

**Comment by aveshagarwal** [comment]
@dubstack here is the PR: https://github.com/kubernetes/kubernetes/pull/29639 where we changed to node allocatable values in downward api for default resource limits, so the first point in your original description seems to be covered in this PR.

**Comment by dubstack** [comment]
@derekwaynecarr @aveshagarwal Thanks for the reference.

@vishh @derekwaynecarr What are your thoughts on getting the node allocatable information through GetNodeAnyway(). I believe at one time we were considering making the node information accessible from outside the kubelet. It would be used both in the container manager and kubelet and possibly from other packages aswell.

**Comment by vishh** [comment]
SGTM

**Comment by resouer** [comment]
But I saw a TODO in `defaultPodLimitsForDownwardApi` saying:
> // TODO: if/when we have pod level resources, we need to update this function
// to use those limits instead of node allocatable.

Is it implying that we should not even use allocatable in this method?
