### ISSUE TITLE
OpenStack LBaaS integration missing Security Group Configuration

### ISSUE THREAD

**Issue by vmtyler** [kubernetes/kubernetes#29745]
Currently in LBaaS in openstack (v1 and v2), it puts the LBaaS port in the default security group only. Most environments have that set not to allow any traffic. There's a bug open to ask for a security group when creating an LB, but it hasn't gone anywhere. This means if you use this plugin with kubernetes, it with create the LB and assign a floating ip, but no one will be able to access it. the best fix is allow the config file to specify a security group id- the plugin would get the port_id of the LB after its created and then use update-port (http://gophercloud.io/docs/networking/#update-port) to add the security group to the port. if no security group was supplied in the config file it would behave as it does now.

**Comment by kiall** [comment]
It's actually worse than just having the no access from the default group, depending on the LBaaS driver in use, you will get totally different behaviors. e.g. with:

1) LBaaS v2 and haproxy provider

The load balancer port will be assigned to the projects default security group (as described in the original ticket)

2) LBaaS V2 and the octavia provider

The load balancer port will be assigned to a new security group within the octavia project/tenant - (i.e. not the same project/tenant that asked for a load balancer)
