### ISSUE TITLE
[1.3.3] OpenID Connect provider fails with trailing slashes in the issuer URL

### ISSUE THREAD

**Issue by hanikesn** [kubernetes/kubernetes#29749]
I like to use Azure Active Directory as IDP:
https://sts.windows.net/14929598-cff9-49f0-b20b-295e9d4dcb8b/.well-known/openid-configuration
The issuer URL has a trailing slash: `https://sts.windows.net/14929598-cff9-49f0-b20b-295e9d4dcb8b/`, but when I specify the issuer url with a trailing slash on the command line options for kube-apiserver the trailing slash gets trimmed before validation:
```
E0728 17:34:50.966425   21702 oidc.go:119] Failed to fetch provider config, trying again in 3s: "issuer" in config (https://sts.windows.net/14929598-cff9-49f0-b20b-295e9d4dcb8b/) does not match provided issuer URL (https://sts.windows.net/14929598-cff9-49f0-b20b-295e9d4dcb8b)
```

This means I can't use this IDP. And the apiserver will fail to start with this configuration.

Related issues:
https://github.com/kubernetes/kubernetes/issues/20476
https://github.com/kubernetes/kubernetes/pull/21128

**Comment by hanikesn** [comment]
This commit https://github.com/kubernetes/kubernetes/commit/36bd693d3a9d835f75c1ce78b357e026fc7b7c1f breaks the verification.
It's also not necessary anymore as the trailing slash gets trimmed later in the code anyways: https://github.com/kubernetes/kubernetes/blob/v1.3.3/vendor/github.com/coreos/go-oidc/oidc/provider.go#L625

Paging @yifan-gu

**Comment by hanikesn** [comment]
cc @erictune @madziefe @bobbyrullo @ericchiang

**Comment by ericchiang** [comment]
I believe this was fixed in our client. Feel free to assign me. I'll try to update the dependency today.

**Comment by hanikesn** [comment]
@ericchiang I think the client looks fine in 1.3.3 and it's just the old workaround that breaks things.

**Comment by ericchiang** [comment]
Ah sorry. Yeah this line in the OpenID Connect plugin looks redundant[0]

[0] https://github.com/kubernetes/kubernetes/blob/v1.3.3/plugin/pkg/auth/authenticator/token/oidc/oidc.go#L115

**Comment by hanikesn** [comment]
Any chance to get this backported for 1.3? I tried cherry picking it, but it didn't apply cleanly.

**Comment by erictune** [comment]
I created this cherry pick:
https://github.com/kubernetes/kubernetes/pull/30149
