### ISSUE TITLE
Host port should preserve source ip

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#29742]
There are some masquerade requirements for hostPort apparently. This hide source ip from loadbalancers, which are one of the few valid use cases for hostPort currently. 
- container -> node-ip:hostPort: lb sees ip of node the container is on
- same node ->  
  - 127.0.0.1/localhost:hostPort: lb sees cbr0 ip
  - eth0 ip:hostPort: lb sees eth0 ip
- different node -> node-ip:hostPort: preserves source ip
- outside cluster -> node-ip:hostPort: preserves source ip

The last one preserving source ip is the most important. Would be nice if we preserved it across the board.

**Comment by caseydavenport** [comment]
The portmap plugin (Currently in a PR https://github.com/containernetworking/plugins/pull/1) will support disabling masquerade. 

Once we move kubenet to a CNI plugin and use that plugin for host ports then this issue should be fixed, I think.

**Comment by pichouk** [comment]
Anything new on this ? I still got the same issue on Kubernetes `1.7.1`.

**Comment by thockin** [comment]
The only way to preserve the source IP is to set `externalTrafficPolicy: Local` and only access nodes that have an instance of that Service.  Otherwise, because of teh NAT that is happening, you need to change the source IP to ensure return-path processing.
