### ISSUE TITLE
Hyperkube binary missing in gcr.io/google_containers/hyperkube:v1.3.3

### ISSUE THREAD

**Issue by someword** [kubernetes/kubernetes#29758]
The hyperkube image released with v1.3.3 does not contain /hyperkube.  I couldn't find any docs stating that it has moved to another path.    Also v1.3.3-beta.0 included /hyperkube at the normal path so i'm thinking this is not intentional.

```
core@iiev00173 ~ $ docker run -it gcr.io/google_containers/hyperkube:v1.3.3-beta.0 ls /hyperkube
/hyperkube
core@iiev00173 ~ $ docker run -it gcr.io/google_containers/hyperkube:v1.3.3 ls /hyperkube
ls: cannot access /hyperkube: No such file or directory
```

**Comment by luxas** [comment]
Can't reproduce. Can you provide any more info?

```console
$ docker run -it gcr.io/google_containers/hyperkube:v1.3.3 ls -l /hyperkube
-rwxr-xr-x 1 root root 138063184 Jul 22 20:41 /hyperkube
```

**Comment by someword** [comment]
Strange.  It just so happens that one of my masters has a bad a layer that is part of the 1.3.3 image.  I apologize for not troubleshooting better on my side (rm -rf /var/lib/docker ftw).

**Comment by luxas** [comment]
Thanks. Good to hear you sorted it out! :)
