### ISSUE TITLE
k8s-scheduler does not show up when using "kubectl get services"

### ISSUE THREAD

**Issue by RedCornerR** [kubernetes/kubernetes#29767]
i try to deploy k8s on mesos. i followed the guide "http://kubernetes.io/docs/getting-started-guides/mesos/". 

when Validating KM Services. i can only see one service as below
[root@k8s-69 kubernetes]# kubectl get services
NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   10.10.10.1   <none>        443/TCP   1d

but no scheduler show up here. 
 the process scheduler exists.
[root@k8s-69 kubernetes]# ps -ef | grep km
root        301      2  0 7月26 ?       00:00:00 [kmpath_rdacd]
root       9125   4316  0 7月28 pts/1   00:01:16 km apiserver --address=192.168.1.69 --etcd-servers=http://192.168.1.69:4001 --service-cluster-ip-range=10.10.10.0/24 --port=8888 --cloud-provider=mesos --cloud-config=mesos-cloud.conf --secure-port=0 --v=1
root       9142   4316  0 7月28 pts/1   00:03:55 km controller-manager --master=192.168.1.69:8888 --cloud-provider=mesos --cloud-config=./mesos-cloud.conf --v=1
root      19194   4316  0 10:12 pts/1    00:00:00 km scheduler --address=192.168.1.69 --mesos-master=zk://zdy-centos-mesos-master-02:2181/mesos --etcd-servers=http://192.168.1.69:4001 --mesos-user=root --api-servers=192.168.1.69:8888 --cluster-dns=10.10.10.10 --cluster-domain=cluster.local --v=3
root      19605   4316  0 10:42 pts/1    00:00:00 grep --color=auto km

i can also see K8S in the framworks of mesos UI. 

anyone can help?

RedCornerR

**Comment by k82cn** [comment]
Which scheduler do you mean? The scheduler is running according to your append:

```
root 19194 4316 0 10:12 pts/1 00:00:00 km scheduler --address=192.168.1.69 --mesos-master=zk://zdy-centos-mesos-master-02:2181/mesos --etcd-servers=http://192.168.1.69:4001 --mesos-user=root --api-servers=192.168.1.69:8888 --cluster-dns=10.10.10.10 --cluster-domain=cluster.local --v=3
```

**Comment by RedCornerR** [comment]
k8sm-scheduler  . yes it's running, however it does not show up when executing the command "kubectl get services". only "kubernetes 10.10.10.1 443/TCP 1d" there.
after executing kubectl get nodes/pod/rc, nothing show up.

**Comment by k82cn** [comment]
I think you can check controller/scheduler's log to confirm whether the connection is OK, e.g. does scheduler get offers from Mesos?

**Comment by RedCornerR** [comment]
sorry, i am newbee to k8s and mesos. here's the scheduler.log. 
"I0729 10:18:49.943309   19194 scheduler.go:982] Registering with master: master@192.168.1.139:5050
I0729 10:18:49.943448   19194 messenger.go:201] Sending message mesos.internal.RegisterFrameworkMessage to master@192.168.1.139:5050
I0729 10:18:49.943509   19194 scheduler.go:933] will retry registration in 12.857785217s if necessary
I0729 10:18:49.943529   19194 http_transporter.go:223] Sending message to master@192.168.1.139:5050 via http
I0729 10:18:49.943542   19194 http_transporter.go:558] libproc target URL http://192.168.1.139:5050/master/mesos.internal.RegisterFrameworkMessage
I0729 10:19:02.801715   19194 scheduler.go:982] Registering with master: master@192.168.1.139:5050
I0729 10:19:02.801934   19194 messenger.go:201] Sending message mesos.internal.RegisterFrameworkMessage to master@192.168.1.139:5050
I0729 10:19:02.802033   19194 scheduler.go:933] will retry registration in 28.799050143s if necessary
I0729 10:19:02.802048   19194 http_transporter.go:223] Sending message to master@192.168.1.139:5050 via http
I0729 10:19:02.802189   19194 http_transporter.go:558] libproc target URL http://192.168.1.139:5050/master/mesos.internal.RegisterFrameworkMessage"

i have no idea whether is Ok according the log.

RedConrnerR

**Comment by k82cn** [comment]
It seems scheduler keep retrying at `scheduler.go:933`.

**Comment by RedCornerR** [comment]
problem solved by disable firewall.

**Comment by k82cn** [comment]
great :). Can you help to close this issue?
