### ISSUE TITLE
Restart dependent Pods/Containers when a Secret is updated

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#29761]
New applications can be built to use `inotify` to watch for files to change in Secret Volumes, but this doesn't help applications that don't have this behavior baked in.

It would be nice if a user could specify, for a given Pod or container, that it needs to be restarted when a Secret update. Then, updating a Secret would result in a rolling-restart through the RC's or ReplicaSet's Pods. 

(I looked but didn't see an issue for this, apologies if it exists somewhere already)

**Comment by colemickens** [comment]
(Alternatively, in the meantime, is there a way to manually initiate a rolling-restart other than editing the Deployment object in a way that would cause a rollout?)

**Comment by dchen1107** [comment]
I am closing this one as dup of https://github.com/kubernetes/kubernetes/issues/24957, and let's move the discussion over there.
