### ISSUE TITLE
Support MFA in API authentication 

### ISSUE THREAD

**Issue by philipn** [kubernetes/kubernetes#29769]
It would be great if the Kubernetes API (and associated tools like `kubectl`) supported some form of MFA!  I'm new to Kubernetes, but my understanding is that, right now, the e.g. authentication credentials on my laptop are long-lived.

Is it currently possible to configure Kubernetes to allow for some form of MFA?  Perhaps there's a way to obtain a short-lived authentication token which could be used to build some kind of MFA system?

**Comment by pwittrock** [comment]
@matchstick Do you know if there is anything planned around this?

**Comment by lucamartinetti** [comment]
+1

**Comment by coreyjohnston** [comment]
+1

**Comment by liggitt** [comment]
short-lived tokens can be obtained/renewed using the OIDC kubectl auth provider - https://kubernetes.io/docs/admin/authentication/#openid-connect-tokens

other custom MFA solutions can be injected using an authenticating proxy (https://kubernetes.io/docs/admin/authentication/#authenticating-proxy), though depending on the method used, kubectl would not have native support for it

**Comment by Mohitp98** [comment]
Any update on MFA for Kubernetes authentication?

Is there any way to use google authenticator with Kubernetes?
