### ISSUE TITLE
How to enforce policies with version skew?

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#29765]
Example use case:

> I specify an AppArmor profile to run my pod with. I'm expecting the pod to be attacked, so I want to guarantee it won't run without the AppArmor profile applied.

As long as the Kubelet is running a version with AppArmor support, it can be loaded up with all the validation to ensure that the pod will only run with the profile enforced. However, if the Kubelet is running an older version, it will happily ignore the AppArmor field.

Do we have any existing mechanisms to address this issue? I know a savvy user could add an AppArmor label to nodes that support it and an AppArmor NodeSelector to each Pod, but unless we automatically add the NodeSelector, it would not honor the PodSecurityPolicy, and is vulnerable to error.

I propose adding a `MinKubeletVersion` field to Pods (or optionally, the PodSecurityContext) that is enforced by the scheduler (and the Kubelet as a fallback). Features that must be enforced would increase that version as needed (but never decrease). This would still be vulnerable if the kubectl client supported this feature (or a direct REST request was sent) and the master did not, but at least in that case the options would be missing with `get pod` or `describe pod` (or enforce it in `kubectl` directly).

/cc @lavalamp @kubernetes/sig-scheduling @kubernetes/sig-node @sttts

**Comment by sttts** [comment]
Trying to decouple this idea from the actual kubelet and security use-case:

Your `MinKubeletVersion` field sounds like a value orthogonal to the API version which describes the minimal Kubernetes version which faithfully understands the semantics of all used features of an object.

One assumption for API changes (https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api_changes.md#on-compatibility) is that new features **with default values** do not change behavior (i.e. we allow extension iff they are *conservative*). In this sense, "used" above means that a field is different from its default value.

Another assumption is that our conversions are injective, i.e. never loose any information, at least for everything in the spec of an object (at worst we convert spec values into annotations). Hence, we could preserve the minimal Kubernetes version for all features temporarily stored in annotations. The kubelet (and the scheduler) can take this into consideration.

I wonder whether it is **feasible and sound** to automatically derive a `MinVersionForSpec` value during conversion of an object. In other words, we introduce this:

```
struct TypeMeta {
  // is a derived, minimal Kubernetes version which is known to support all features of
  // this object which are different from the defaults.
  MinVersionForSpec int
}
```

New fields could be go-annotated in the internal types with this `MinVersionForSpec` and our conversion code generation would to the rest.
