### ISSUE TITLE
Watch nodes without watching heartbeats?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#29772]
Is there a way to watch the nodes without watching their heartbeats?  With each node posting a status every 10 seconds, this produces a lot of invalidations for what would otherwise be a relatively static set.

**Comment by magicwang-cn** [comment]
then i think we should add another filter mechanism for kube-apiserver, but this is not the root solution.
why not just change the heartbeat? avoid to update the node  will reduce a mount of watch event.

i just use the gossip protocol to maintain the heartbeat of node, this can avoid to update node every 10 seconds(`which will reduce the put requests of apiserver`), and more timely to find the fault node(`which  evict pods quickly`).

**Comment by marun** [comment]
+1 for separating highly volatile state from the relatively static.

**Comment by bgrant0607** [comment]
Was more or less a dupe of #14733
