### ISSUE TITLE
Documentation on how to recover from a bad deployemnt

### ISSUE THREAD

**Issue by csaintc** [kubernetes/kubernetes#29784]
@kubernetes/deployment
@bgrant0607

Deployments are going to be used most often in the context of a CD pipeline.

How do people programmatically recover from bad deployments?

Rolling update used to return a non-zero exit code, and it was a simple matter of wrapping it in a try-catch and calling `—rollback` to undo an unsuccessful deployment.

The new Deployment API has no such functionality. It applies the new configuration, and fails silently if the new deploy is unsuccessful:

`deployment "blah" is configured`

for the record I'm using `kubectl apply -f path_to_deployment`. Is that where I'm going wrong?

**Comment by bgrant0607** [comment]
cc @kubernetes/deployment

**Comment by bgrant0607** [comment]
@csaintc The deployment occurs asynchronously, indefinitely.

For now, you can wait until `status.updatedReplicas == spec.replicas && status.observedGeneration >= metadata.generation`, and timeout if that doesn't happen, as documented here:

http://kubernetes.io/docs/user-guide/deployments/#the-status-of-a-deployment

In the future, this timeout will be detected automatically, but kubectl will still return immediately. See also #14519 and #23211.

We could also implement a `kubectl rollout` command to check this.

**Comment by kargakis** [comment]
> We could also implement a kubectl rollout command to check this.

It could also be implemented as suggestions to users in `oc rollout status`.

**Comment by kargakis** [comment]
> status.updatedReplicas == spec.replicas && status.observedGeneration >= metadata.generation

I would also add `status.availableReplicas >= spec.replicas-spec.rollingParams.maxUnavailable` in the mix to ensure that we have minimum availabilty before considering a deployment healthy.

**Comment by kargakis** [comment]
We now have ProgressDeadlineSeconds which you can set in the spec of the Deployment and get back a ProgressDeadlineExceeded condition in case your rollout is stuck. More info in https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#deployment-status
