### ISSUE TITLE
Reduce size of fluentd baseimage

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#29782]
It's 400+mb and we need to pull it on every node. This leads to a lot of image pulling flake (https://github.com/kubernetes/kubernetes/issues/26626), and also gets very expensive in some countries where bandwidth is sold at a premium. 

We took a stab at halving the size with: https://github.com/kubernetes/kubernetes/pull/26652#issue-158005512, but then realized that we were using an unsupported base image https://github.com/kubernetes/kubernetes/pull/26652#issuecomment-223167921. We tried to optimize to ~300Mb by building a smaller ubuntu:15 base, but that's still huge. 

Every other mandatory system daemon is built on busybox and so takes ~10Mb.
@fgrzadkowski @piosz

**Comment by aledbf** [comment]
@bprashanth I can try again now that the agent supports `LTS 16.04 "Xenial"`
```
aledbf/fluentd-elasticsearch                   1.19 769ece5c8ba8 About an hour ago 281.2 MB
gcr.io/google_containers/fluentd-elasticsearch 1.18 0a8cbfbea7f7 5 weeks ago       530.3 MB

aledbf/fluentd-gcp                             1.22 ef979b82a767 About an hour ago 307.9 MB
gcr.io/google_containers/fluentd-gcp           1.21 0ef09b1bcfd7 2 weeks ago       498.5 MB
```

**Comment by edsiper** [comment]
Newer Docker images using the spec from the official repository are based on AlpineLinux and are around ~38MB:

https://github.com/fluent/fluentd-docker-image

```
REPOSITORY         TAG         IMAGE ID                CREATED         SIZE
fluent/fluentd         latest      ab439f5d0234       3 days ago      38.45 MB
```
