### ISSUE TITLE
several issues with the rbd volume plugin

### ISSUE THREAD

**Issue by qiancai** [kubernetes/kubernetes#29797]
version: kubernetes-1.2.0 git ec7364b

There are a 3 strange situation associated with the rbd volume plugin depends on the sequences of pod creating. All of them seem buggy. The 1st and 3rd situations create denied of service for other users to access the rbd from pod.

1) create a buggy pod directly use a rbd volume (no pv and pvc) but with an incorrect rbd xfstype (for example, if the rbd volume is xfs, use ext4 in the pod definition).
2) create a rbd pv.
3) create 2 different pvc (to bind to the pv) and 2 pods (to use the pvc).
Result: both pods will be stuck in the pending status seems forever.

1) create a buggy pod directly use the rbd volume with an incorrect rbd xfstype.
2) create a rbd pv, pvc and pod.
Result: both pods will be in the running status and the rbd will be mounted using the correct fstype!

1) create a buggy pod directly use the rbd volume with either an incorrect or correct rbd xfstype.
2) create another pod directly use a rbd volume with a correct rbd xfstype.
The 2nd pod will be stuck in the pending status seems forever.

**Comment by xiangpengzhao** [comment]
@qiancai since you reported the issue on 1.2.0 and this has no updates. Will close it. Feel free to re-open it if you still encounter this issue on latest release. Thanks!

close

@thockin
