### ISSUE TITLE
AWS: Flexible installation

### ISSUE THREAD

**Issue by moleksyuk** [kubernetes/kubernetes#29792]
It's a feature request related to installation of `Kubernetes` in `AWS`.
### Requirements
1. Installation of `Kubernetes` should be more flexible and can accept preconfigured stuff in `AWS`:
- VPC
- Zone
- Region
- S3 bucket prefix
- etc

And during `kube-down` kubernetes should delete only objects created only by itself and **skip** provided ones to avoid breaking preconfigured AWS infrustructure.

**Comment by justinsb** [comment]
kube-up is now in maintenance mode, and kops and kubeadm are well on the way here.  I believe kops matches all your requirements.  Closing; if there are specific requirements missing from kops or kubeadm can you maybe open issues against them?
