### ISSUE TITLE
Kubectl delete-cluster, list-clusters, delete-contexts, list-contexts

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#29794]
I make a lot of clusters and then I forget which ones I have.  I could do `kubectl config view` but that is a lot of spew.  I could do  `kubectl config view --minify` but that only shows the current context.

I'd like:
```
$ kubectl config list-clusters
NAME                              
eric-tune-6_kubernetes
gke_eric-tune-6_us-west1-a_cluster-2
gke_eric-tune-6_us-west1-a_cluster-3
local
minikube
```

I'd also like:
```
$ kubectl config list-contexts
NAME                                  CLUSTER                               NAMESPACE    IS-CURRENT
eric-tune-6_kubernetes                eric-tune-6_kubernetes                default      *
eric-tune-6_kubernetes-admin          eric-tune-6_kubernetes                kube-system        
gke_eric-tune-6_us-west1-a_cluster-2  gke_eric-tune-6_us-west1-a_cluster-2  default  
gke_eric-tune-6_us-west1-a_cluster-3  gke_eric-tune-6_us-west1-a_cluster-3  default
minikube                              minikube                              default
```
so I can see what contexts I have.

I'd also like:
```
$ kubectl config delete-clusters minikube
deleted cluster minikube from $HOME/.kube/config
```
or 
```
$ kubectl config delete-cluster minikube
cannot delete cluster minikube, not in $HOME/.kube/config.
```

I'd also like:
```
$ kubectl config delete-context minikube 
deleted context minikube from $HOME/.kube/config
```

Also, something needs to GC contexts that have no cluster, and authInfos that have no cluster?

This could be a good starter project for kubectl.

**Comment by alexbrand** [comment]
This seems like a great issue to get introduced to kubectl. @erictune Would love to help out here

**Comment by erictune** [comment]
@pwittrock @janetkuo  can you or someone else from experience give a preliminary approval to these changes?

@deads2k does this conflict with anything you wanted to upstream?

To implement these, I think you would do something like start with `pkg/kubectl/cmd/config/create_cluster.go` or `pkg/kubectl/cmd/config/view.go`, and then make a copy called `pkg/kubectl/cmd/config/create_cluster.go`, and so on, and modify it until you have some new commands.  Also, probably need to add a `New*` call to pkg/kubectl/cmd/config/config.go.

**Comment by deads2k** [comment]
> @deads2k does this conflict with anything you wanted to upstream?

It doesn't collide with anything, but @bgrant0607 has wanted to gut the `kubectl config` commands for some time now: https://github.com/kubernetes/kubernetes/issues/20605.  

Also, does this pull satisfy your list desire: https://github.com/kubernetes/kubernetes/pull/25463 ?

Today, deletion is done like: `oc config unset clusters.<cluster-name>`.

**Comment by pwittrock** [comment]
WDYT of: `kubectl config  get clusters` and `kubectl config delete clusters` to match the other kubectl commands

**Comment by pwittrock** [comment]
@erictune what does delete-cluster vs delete-context do?  We should be clear that the cluster itself is not being deleted.

**Comment by daikaixian** [comment]
I even don't get the 'kubectl config list-contexts' commands

it's my kubectl version info

Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"a4463d9a1accc9c61ae90ce5d314e248f16b9f05", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"a4463d9a1accc9c61ae90ce5d314e248f16b9f05", GitTreeState:"clean"}

**Comment by bgrant0607** [comment]
@erictune We need to be careful that such commands don't get confused with federation cluster resource operations.

**Comment by bgrant0607** [comment]
`kubectl config get-contexts` is in 1.4.0-alpha.2

**Comment by erictune** [comment]
I don't have an opinion on the exact syntax.  I do think whoever implements
it should read #20605
<https://github.com/kubernetes/kubernetes/issues/20605> and the conventions
doc linked from there, and makes an informed decision.

Deleting a cluster-config could delete all contexts that reference that
cluster-config, and (i think?) delete all authinfos that would have no use
once that cluster -config is deleted.

Deleting a context does not delete the cluster-config.  Cluster-configs are
the parent of contexts.

**Comment by alexbrand** [comment]
I can take another stab at the implementation of this once we have a better idea of what we want. Missing from the current PR #29821 is deleting related config (as suggested by @erictune)

I initially considered `kubectl config get X` and `kubectl config delete X` (as suggested by @pwittrock), but decided to keep it consistent with the existing `kubectl config get-contexts` command.

**Comment by pwittrock** [comment]
kubectl config get-X sgtm

**Comment by deads2k** [comment]
If we're trying to make it appear like our normal CRUD (which I think is part of what https://github.com/kubernetes/kubernetes/issues/20605 is about), we could consider doing `kubectl config get RESOURCE/NAME` where resource is cluster, context, user and name is the nick name.  That would give us a clear way to integrate get, list, update, delete.  That would also give something to bad templates against and `--all` handling.

@fabianofranz @kubernetes/kubectl thoughts?

**Comment by deads2k** [comment]
Ah, and I just repeated @pwittrock .  What he said, :)

**Comment by erictune** [comment]
pwittrock and deads2k both endorse a solution for kubectl

that sounds like a decision to me.

**Comment by alexbrand** [comment]
Hmm, I am somewhat confused :)

Do we want `kubectl config get clusters` (https://github.com/kubernetes/kubernetes/issues/29794#issuecomment-237528618) or `kubectl config get-clusters` (https://github.com/kubernetes/kubernetes/issues/29794#issuecomment-237406273). 

I am leaning towards the hyphen-less commands to remain consistent with the rest of `kubectl`.

**Comment by deads2k** [comment]
> I am leaning towards the hyphen-less commands to remain consistent with the rest of kubectl

I think hyphen-less too.

**Comment by moander** [comment]
Common tasks like default namespace swapping is not straight forward using kubectl. 

If NAME was optional one could change the current context like this:
```
kubectl config set-context --namespace whatever 
```


The current docs suggest this procedure to change the default namespace:

```
$ export CONTEXT=$(kubectl config view | awk '/current-context/ {print $2}')

$ kubectl config set-context $CONTEXT --namespace=<insert-namespace-name-here>
# Validate it
$ kubectl config view | grep namespace:
```

**Comment by deads2k** [comment]
> If NAME was optional one could change the current context like this:

That seems like a good idea to me.

@fabianofranz You given thought to pushing `oc project`?

**Comment by fabianofranz** [comment]
>> If NAME was optional one could change the current context like this:

> That seems like a good idea to me.

+1, optional context name in `set-context` and defaulting to current sounds good to me.

> You given thought to pushing oc project?

No, you mean pushing as-is in terms of command structure, something like `kubectl namespace [NAME]` (shows current without an arg, switch to the given namespace if arg provided)?

BTW one idea would be to extend `kubectl config` to add a few more options (new ones in asterisk `*` below):

```
kubectl current-context
kubectl current-namespace *
kubectl current-cluster *
kubectl current-credentials *

kubectl use-context
kubectl use-namespace * (set namespace in the current context)
kubectl use-cluster * (set cluster in the current context)
kubectl use-credentials * (set credentials in the current context)
```
