### ISSUE TITLE
Create the log dir specified by flag "--log-dir" if not exist

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#29790]
When starting kube-apiserver or other kube bins, if we specify a dir to log by flag `--log-dir` but the dir doesn't exist, the dir cannot be created automatically and then nothing will be logged. 

From the users' perspective (at least mine), they may think kube should create the dir they specified if not exist, else they will lose the log.

If the dir should be created first if not exist, is it the responsibility of kube or glog to do this?

**Comment by dchen1107** [comment]
This is a very reasonable request to have kube to create such dir if not exist.

**Comment by xiangpengzhao** [comment]
Thanks @dchen1107 !

There is also another bug with the log-dir. If I specify an invalid dir, e.g. `--log-dir=dsfds/fds\fdsf`, the kube start normally without verifying it.

I thought to fix this, but I didn't find where the flag is respected. Help wanted.

**Comment by dims** [comment]
@xiangpengzhao Peter, The flag is defined and respected in the [glog_file.go](https://github.com/kubernetes/kubernetes/blob/fa95788e560de7575c851d87d76c664b3753a7a6/vendor/github.com/golang/glog/glog_file.go#L41)

The original is here, we use a copy:
https://github.com/golang/glog/blob/master/glog_file.go#L41

**Comment by xiangpengzhao** [comment]
@dims Thanks Davanum! 

It seems that glog will respect the flag `--log-dir` and it's out of our control. So, should we report a bug to glog? There are at least two issues here: 1). should validate the dir; 2). should create dir if not exist.

The func [create](https://github.com/kubernetes/kubernetes/blob/fa95788e560de7575c851d87d76c664b3753a7a6/vendor/github.com/golang/glog/glog_file.go#L114) in glog_file.go shows:

```
	for _, dir := range logDirs {
		fname := filepath.Join(dir, name)
		f, err := os.Create(fname)
		if err == nil {
			symlink := filepath.Join(dir, link)
			os.Remove(symlink)        // ignore err
			os.Symlink(name, symlink) // ignore err
			return f, fname, nil
		}
		lastErr = err
	}
```

Here the log file is created directly without checking dir. IMO, the validation of dir would better to be done before.

From the glog code, we can find another thing that it will log into the tmp dir `/tmp` if `--log-dir` is not specified or the specified dir doesn't exist or invalid. I try in my env and it behaves as this indeed.

But the problem is, do our users know the `/tmp` log dir? So, I prefer the `validation and/or creation` way.

cc @dsymonds Thanks!

**Comment by dsymonds** [comment]
`--log_dir` exists in glog for use in systems where the system setup happens before the program starts, and so the relevant directory for log files can be created. Not creating log files if the dir doesn't exist is working by design; if you run the binary on another system, or directly, you might not want the log files spamming everywhere.

**Comment by xiangpengzhao** [comment]
Thanks David ! @dsymonds
