### ISSUE TITLE
Revisit error events generation in HPA controller

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#29799]
Currently the HPA behavior is:
1. Observe high cpu utilization
2. Scale resource up
3. Query for metrics of old and newly created pods
4. Metrics are not available yet, so export error event

This is confusing for users because the HPA is working correctly but the error is exported. Probably we should introduce some grace period before exporting error event.

**Comment by piosz** [comment]
@kubernetes/autoscaling

**Comment by jszczepkowski** [comment]
@jszczepkowski
