### ISSUE TITLE
How to manage dependency between services or pods in kubernetes ?

### ISSUE THREAD

**Issue by medhedifour** [kubernetes/kubernetes#29804]
Hi all,
I have consulted some of application examples in the repository of kubernetes and I have noticed that the important details of linking containers or pods to respect a certain hierarchy of an application are omitted. There are no details of how to manage dependency between services. I hope I have a clear example that accentuate the problem of linking components.
Can someone help me to have more details of dependency between services and even I there are a clear example of this issue.
Thanks in advance.

**Comment by dshulyak** [comment]
@medhedifour take a look at this project https://github.com/Mirantis/k8s-AppController, does it cover your use-cases?

**Comment by medhedifour** [comment]
@dshulyak  
Thanks

**Comment by xiangpengzhao** [comment]
Thanks @dshulyak for the information!

close

@thockin

**Comment by mattdornfeld** [comment]
This should be reopened. It seems k8s app controller is no longer maintained.

**Comment by thockin** [comment]
Before we open new issues, I'd appreciate getting a deeper sense of the problem you are facing.  This bug doesn't say anything about that.
