### ISSUE TITLE
kubedns seems not work(local-up-cluster.sh)

### ISSUE THREAD

**Issue by better0332** [kubernetes/kubernetes#29829]
I test on vagrant-ubuntu-trusty-64, master branch:

root@vagrant-ubuntu-trusty-64:/mygo/src/k8s.io/kubernetes# KUBE_ENABLE_CLUSTER_DNS=true hack/local-up-cluster.sh   (its ok)

vagrant@vagrant-ubuntu-trusty-64:~$ kubectl get pod --all-namespaces
NAMESPACE     NAME                 READY     STATUS    RESTARTS   AGE
kube-system   kube-dns-v19-iwu1u   2/3       Running   1          2m

vagrant@vagrant-ubuntu-trusty-64:~$ kubectl describe pod --namespace=kube-system
 2m            8s              9       {kubelet 127.0.0.1}     spec.containers{kubedns}        Warning         Unhealthy       Readiness probe failed: Get http://172.17.0.2:8081/readiness: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

root@vagrant-ubuntu-trusty-64:~/test# kubectl exec busybox -- nslookup kubernetes.default
Server:    10.0.0.10
Address 1: 10.0.0.10

nslookup: can't resolve 'kubernetes.default'
error: error executing remote command: error executing command in container: Error executing in Docker Container: 1

**Comment by mdshuai** [comment]
I met this same error, In my env the kubedns can't access  kubernetes service 443 port.
```
[root@ip-172-18-12-44 kubernetes]# docker logs cbfe96287e18
I0803 02:30:30.927271       1 server.go:91] Using https://10.0.0.1:443 for kubernetes master
I0803 02:30:30.932493       1 server.go:92] Using kubernetes API <nil>
I0803 02:30:30.935979       1 server.go:132] Starting SkyDNS server. Listening on port:10053
I0803 02:30:30.936113       1 server.go:139] skydns: metrics enabled on :/metrics
I0803 02:30:30.936126       1 dns.go:166] Waiting for service: default/kubernetes
I0803 02:30:30.936553       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0803 02:30:30.936562       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0803 02:30:30.936958       1 dns.go:172] Ignoring error while waiting for service default/kubernetes: Get https://10.0.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 10.0.0.1:443: getsockopt: connection refused. Sleeping 1s before retrying.
E0803 02:30:30.937435       1 reflector.go:216] pkg/dns/dns.go:154: Failed to list *api.Endpoints: Get https://10.0.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: connection refused
E0803 02:30:30.937762       1 reflector.go:216] pkg/dns/dns.go:155: Failed to list *api.Service: Get https://10.0.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: connection refused
I0803 02:30:31.937601       1 dns.go:172] Ignoring error while waiting for service default/kubernetes: Get https://10.0.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 10.0.0.1:443: getsockopt: connection refused. Sleeping 1s before retrying.
E0803 02:30:31.937886       1 reflector.go:216] pkg/dns/dns.go:154: Failed to list *api.Endpoints: Get https://10.0.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: connection refused
E0803 02:30:31.938095       1 reflector.go:216] pkg/dns/dns.go:155: Failed to list *api.Service: Get https://10.0.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: connection refused

```

**Comment by aledbf** [comment]
@better0332 @mdshuai this can be solved using `export API_HOST=<ip of docker0>`

**Comment by mdshuai** [comment]
same issue. https://github.com/kubernetes/kubernetes/issues/29727

**Comment by kargakis** [comment]
I don't think this is any longer an issue - I am able to run DNS just by exporting KUBE_ENABLE_CLUSTER_DNS=true. @better0332 please re-open if you still have any problem.

**Comment by jayunit100** [comment]
Specifically, you need to do this:
```
ENABLE_CLUSTER_DNS=true
DNS_SERVER_IP=127.0.0.1
```
I'll put a patch to make these the defaults and see what folks think ;
