### ISSUE TITLE
Docker container name in kubelet is wrong when set container name flag (e.g. --runtime-cgroups=/docker-daemon) for CoreOS image

### ISSUE THREAD

**Issue by coufon** [kubernetes/kubernetes#29827]
The flag to change docker container name does not work for CoreOS, but this exception is not handled in container manager (container_manager_linux.go) .

When the flag (e.g. --runtime-cgroups=/docker-daemon) is used in CoreOS image, the container manager still try to create and use cgroup "docker-daemon" , but the correct cgroup should be "system.slice/docker.service/"

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/container_manager_linux.go#L307

A quick fixup may be always detecting the correct container name through docker pid, no matter whether the flag is set.

@Random-Liu @yujuhong @dchen1107

**Comment by yujuhong** [comment]
To summarize, there are two problems.

1. The flag doesn't work on coreos images. 
2. If the flag is set, kubelet skips cgroup detection, and just uses the given name. This leads to tracking a wrong cgroup on coreos image because of (1). 

@vishh, any suggestion on how to fix the issue? We can fix (2) by always running the detection logic, but we should still clarify when the `--runtime-cgorups` flag works.

**Comment by vishh** [comment]
The flag is not expected to be set on CoreOS machines :) 

> If the flag is set, kubelet skips cgroup detection, and just uses the given name. This leads to tracking a wrong cgroup on coreos image because of (1).

If the flag is set, kubelet attempts to move processes to specified cgroups, might (or might not ) work on systemd systems. I'd expect the flag to either work or fail the kubelet with a clear error message.

**Comment by dchen1107** [comment]
@vishh is right on this. Like what I mentioned in pr https://github.com/kubernetes/kubernetes/pull/29764/, that flag doesn't work and not expected on any systemd node, including coreos. 

In a long run, we should resolve this kind of issue through @mtaufen 's dynamic kubelet configuration (#27980). For a short term, we can easily resolve this issue through e2e_service.go which configures Kubelet's flags for node e2e test at:

https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/e2e_service.go#L221

At today's e2e_service, we already detect if the node is systemd node or not. We just need to pass the right cgroup related flags.

**Comment by dchen1107** [comment]
I can quickly send you a pr to unblock you.
