### ISSUE TITLE
Can't start a new cluster of 1.3.3 on AWS

### ISSUE THREAD

**Issue by erez-rabih** [kubernetes/kubernetes#29833]
Hi,

I tried to bring up a new cluster on my AWS account but the cluster never seem to finish initialization properly.

I SSH'd into the master instance and tail'd the logs of the api server and saw a repeating error message:

```
I0731 11:36:59.365908       6 logs.go:41] http: TLS handshake error from 172.20.0.87:35002: remote error: bad certificate
```

Also, trying to run kubectl.sh cluster-info from the machine that I ran kube-up from returns the following error:

```
Unable to connect to the server: x509: certificate signed by unknown authority
```

Any advice on how to solve this?

**Comment by erez-rabih** [comment]
I figured out what the problem was:
I issued a kube-down command to turn the cluster down but the volume of kubernetes master was not deleted.
When I issued a kube-up again the master attached the old volume so the new certificates and secrets generated were invalid.

**Comment by xiangpengzhao** [comment]
Justin, any updates on this? @justinsb 

cc @thockin

**Comment by justinsb** [comment]
I'm going to close this.  kube-up is deprecated, and removed entirely for AWS.  IIRC we did end up deleting the old master volume.

kops offers a much better AWS experience than kube-up, and is the one I personally recommend.

If there's something more we should do here, please let me know and we can reopen.
