### ISSUE TITLE
Cinder plugin (running inside hyperkube container) fails to find device by Diskid

### ISSUE THREAD

**Issue by eddytruyen** [kubernetes/kubernetes#29832]
I am running into a problem with the Cinder plugin when running Kubernetes inside Docker using the kube-deploy/docker-multinode project

I modified the worker and master scripts of the latter project such that:
- --cloud-provider and --cloud-config options are added to the hyperkube  command
- I mount a host dir with the cloud_config file into the kubelet container (with the -v option) 

```
  <skip> common.sh 
 -v /home/ubuntu/containers_on_openstack/openstack-integration/hyperkube:/openstack \
         ${REGISTRY}/hyperkube:v${K8S_VERSION} \
        /hyperkube kubelet \
             ....  
             --cloud-provider=openstack \
            --cloud-config=/openstack/cloud_config \
             ....
            --v=2
```

The cinder plugin of kubernetes (for attaching Openstack Cinder volumes)  attaches a volume successfully and then tries to find the corresponding device. However the cinder plugin can't find this device by disk-id:

```
I0730 18:28:18.370114    2300 openstack.go:984] Successfully attached 06b25a7b-7c99-4eee-9ab0-98a6c78676a1 volume to 7f07a3d7-1fc9-487f-84b7-c044c1dd5382 compute
W0730 18:28:18.370511    2300 cinder_util.go:103] Failed to find device for the diskid: "06b25a7b-7c99-4eee-9ab0-98a6c78676a1"
E0730 18:28:18.378081    2300 cinder_util.go:169] error running udevadm trigger fork/exec /usr/bin/udevadm: no such file or directory
```

The last log entry shows a failure to run `udevadm trigger fork/exec /usr/bin/udevadm`. I tried to run this command from within a bash session inside the kubelet container and then got as error:  `Extraneous argument: 'fork/exec'`

How can I solve this?

Thanks for any advice

**Comment by cheld** [comment]
CC @cheld

**Comment by spothanis** [comment]
It basically tries to run `/usr/bin/udevadm trigger` to probe all attachments so sym link for the disk is created in `/dev/disk/by-id`. Is this the command you tried to run from command line?

**Comment by eddytruyen** [comment]
@sponthanis Yes. However I now see that I misread the debuglogs that the full command was the following: `udevadm trigger fork/exec /usr/bin/udevadm.`. But this is wrong syntax obviously

I launched Kubernetes version 1.2.6 in the dockerized version of hyperkube. I assume that the error lies somewhere in the fact that certain commands don't work properly when run inside a container.

To further debug, I just had a look at the code  from `pkg/volume/cinder/cinder_util.go`  that reported the error (see below). First an executor is created using `k8s.io/kubernetes/pkg/util/exec` . Then this executor is asked to execute command `/usr/bin/udevadm trigger`. 
The implementation of the executor will try to execute the command in a child process (hence the fork)


```
func probeAttachedVolume() error {
	executor := exec.New()
	args := []string{"trigger"}
	cmd := executor.Command("/usr/bin/udevadm", args...)
	_, err := cmd.CombinedOutput()
	if err != nil {
		glog.Errorf("error running udevadm trigger %v\n", err)
		return err
	}
	glog.V(4).Infof("Successfully probed all attachments")
     return nil
```

**Comment by pesho** [comment]
I think I'm running into a related issue, or at least the same root cause. When using PV+PVC Cinder volumes the Kubelet fails to confirm that they are attached (even though I see the volume is attached in Horizon). The same `udevadm` error shows in the kubelet logs:

```
Oct 16 21:44:37 node sh[780]: E1016 21:44:37.454842     780 cinder_util.go:178] error running udevadm trigger fork/exec /usr/bin/udevadm: no such file or directory
```

However, on Ubuntu 16.04 at least, `udevadm` is located in a different place:

```
# which udevadm 
/sbin/udevadm
```

**Comment by pesho** [comment]
Adding a symlink to the correct `udevadm` location seems to have resolved the issue for me:

```
ln -s /sbin/udevadm /usr/bin/udevadm
```
