### ISSUE TITLE
serviceaccount/ca.crt not being read in kube-dns container

### ISSUE THREAD

**Issue by jaxxstorm** [kubernetes/kubernetes#29835]
I'm using [this](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/coreos/kube-manifests/addons/dns/skydns-rc.yaml) definition to manually create the kube-dns addon.

When creating the container, I get the same issue as in #27973

```
E0731 19:55:07.307474       1 reflector.go:216] pkg/dns/dns.go:154: Failed to list *api.Endpoints: Get https://tukd-kubemaster-1.dapt.to:6443/api/v1/endpoints?resourceVersion=0: x509: failed to load system roots and no roots provided
I0731 19:55:07.307529       1 dns.go:172] Ignoring error while waiting for service default/kubernetes: Get https://kubemaster:6443/api/v1/namespaces/default/services/kubernetes: x509: failed to load system roots and no roots provided. Sleeping 1s before retrying.
```

This works fine on a host in the default namespace. I've set `root-ca-file` and `--service-account-private-key-` int the api config and controller-manager-scheduler config

I've tried:

1) deleting all secrets and restarting kubelet

is there anything I'm missing here? Why would this work with another pod but not for this one?

**Comment by jaxxstorm** [comment]
Oh, I missed the docker inspect output:

```
docker inspect 57d0a67a9dad | jq .[].Mounts
[
  {
    "Source": "/var/lib/kubelet/pods/fa3a6b6e-5759-11e6-a04e-0018518e12da/volumes/kubernetes.io~secret/default-token-txwle",
    "Destination": "/var/run/secrets/kubernetes.io/serviceaccount",
    "Mode": "ro",
    "RW": false,
    "Propagation": "rprivate"
  },
  {
    "Source": "/var/lib/kubelet/pods/fa3a6b6e-5759-11e6-a04e-0018518e12da/etc-hosts",
    "Destination": "/etc/hosts",
    "Mode": "",
    "RW": true,
    "Propagation": "rprivate"
  },
  {
    "Source": "/var/lib/kubelet/pods/fa3a6b6e-5759-11e6-a04e-0018518e12da/containers/kubedns/6f260843",
    "Destination": "/dev/termination-log",
    "Mode": "",
    "RW": true,
    "Propagation": "rprivate"
  }
]
```

So the mount exists and the ca.crt exists inside that mount:

```
ls /var/lib/kubelet/pods/fa3a6b6e-5759-11e6-a04e-0018518e12da/volumes/kubernetes.io~secret/default-token-txwle/
ca.crt  namespace  token
```

**Comment by jaxxstorm** [comment]
Looks fairly similar to #24829 but I've deleted the secrets multiple times without much luck..

**Comment by jaxxstorm** [comment]
Also related maybe? #10265

**Comment by Xenopathic** [comment]
Your issue appears to be kube-dns complaining that the apiserver certificate is unverified, since you haven't given kube-dns your CA certificate. Create a kubeconfig with a `certificate-authority` as per http://kubernetes.io/docs/user-guide/kubeconfig-file/ and pass it into kube-dns with `--kubecfg-file=...`

**Comment by swqmaven** [comment]
i have the same error and how to resolve it?  I used 8080 replace the https 443 and it works! but it still understand how happend?

**Comment by kargakis** [comment]
Doesn't seem like a k8s issue - please use stackoverflow, the kubernetes mailing list, or slack for support kind questions.
