### ISSUE TITLE
how  to change docker Image registry when runing k8s on mesos

### ISSUE THREAD

**Issue by RedCornerR** [kubernetes/kubernetes#29843]
i followed the guide "http://kubernetes.io/docs/user-guide/" and tried to deploy a pod. however i get the error below.  i changed the image registry to a local address on all mesos computing nodes OPTIONS='--selinux-enabled=false --insecure-registry 192.168.1.151:5000'
it still try to pull the image from gcr.io which is not available.

WarningFailedSync   Error syncing pod, skipping: failed to "StartContainer" for "POD" with ErrImagePull: "image pull failed for gcr.io/google_containers/pause-amd64:3.0, this may be because there are no credentials on this request.  details: (net/http: request canceled)"

how to change docker image registry when running k8s on mesos? i am new to k8s and mesos.

RedcorNerR

**Comment by k82cn** [comment]
I think it should the same as private registry in pure kubernetes. Mesos's option will not impact how k8s pull images.

**Comment by xiangpengzhao** [comment]
@RedCornerR Did you set your kubelet flag `--pod-infra-container-image` to be the exact infra image name in your private registry ? If not, kubelet will still use the default `gcr.io/google_containers/pause-amd64:3.0` and try to pull it from gcr.io.

/close

@thockin
