### ISSUE TITLE
Initiate only single client against specific API group

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#29856]
Our current [client initiation logic](https://github.com/kubernetes/kubernetes/blob/06c9ad2c83f1b7415ff32de46016cc63006fc35d/pkg/client/unversioned/helper.go#L49-L127) instantiates all api groups clients at once, but `restclient.Config` points only to single api group at a time. https://github.com/kubernetes/kubernetes/pull/29187 partially fixes the problem by setting defaults for groups which are not mentioned in the config, but the final solution should be that `client.New` should only instantiate single client against the api group specified in the config. 
Unfortunately, this change will require quite a lot of changes, since a lot of places (eg. describers) are assuming that when `Client` is passed it already has access to all possible groups. We should target more granular clients, instead. This should be done along with #25442.
@caesarxuchao @smarterclayton fyi

**Comment by caesarxuchao** [comment]
> but the final solution should be that client.New should only instantiate single client against the api group specified in the config. 

This is already the case in the generated clientset. Only the unversioned.Client suffers from this problem.

**Comment by soltysh** [comment]
@caesarxuchao I'm not sure about that, or I'm looking in the wrong place. See [NewForConfig](https://github.com/kubernetes/kubernetes/blob/ca7ad6896b91081d20ccecd0a356c824546f8476/pkg/client/clientset_generated/internalclientset/clientset.go#L108-L146) which instantiates all api group clients and even more, each group's `NewForConfig` overwrites the configured values (see [batch.setConfigDefaults](https://github.com/kubernetes/kubernetes/blob/ca7ad6896b91081d20ccecd0a356c824546f8476/pkg/client/clientset_generated/internalclientset/typed/batch/unversioned/batch_client.go#L82-L86)). And this is exactly what I am currently addressing in #29187.

**Comment by caesarxuchao** [comment]
> group's NewForConfig overwrites the configured values

That's by design. The version of the clients in a clientset is fixed, and it's explicit in the directory path e.g., `pkg/client/clientset_generated/release_1_4/typed/core/v1`, it doesn't care about the version supplied in the restclient.Config.

**Comment by soltysh** [comment]
Good point, I totally forgot about that part.

**Comment by smarterclayton** [comment]
The internal clientset (which Maciej linked) can't hardcode versions - it
must get those from the server to be correct.  But the versioned ones can.

**Comment by soltysh** [comment]
This is solved now, right @sttts ?
/close
