### ISSUE TITLE
Fix GCE persistent disk driver and docs wrt multi-access to RWO on a node

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#29855]
@thockin says: GCE only supports ReadWriteOnce.  Not ReadWriteMany.  Multiple pods
should NEVER be allowed to access a PD, whether they are on the same
node or not.

But PV/PVC validation doesn't enforce this, and our documentation (http://kubernetes.io/docs/user-guide/persistent-volumes/#types-of-persistent-volumes) doesn't explicitly list what volumes support what options.

Note: fixing the validation should be done with care because it might break current configs...

**Comment by thockin** [comment]
There's a decision to be made, I think, as to whether I am wrong or not.

@kubernetes/sig-storage

**Comment by bprashanth** [comment]
Why shound't it work? (other than,"it's weird")

**Comment by thockin** [comment]
IFF we make the scheduler respect same-claim = same-node (for RWO) then
*maybe* I can buy it.  Without that guarantee, it is inconsistent from an
end-user's POV as to whether it will work or not.

NB that this is a very real restriction for situations where nodes are
hosted or invisible or minimized.  We have spoken to more than one
organization who wants to offer "perfect-fit" VMs for pods, or want to even
hide the notion of nodes completely.  This sort of dependency on "same
node" is retrograde motion in that regard.

**Comment by rootfs** [comment]
PV/PVC also lacks NoDiskConflicts supprt, see https://github.com/kubernetes/kubernetes/issues/29670

**Comment by bprashanth** [comment]
> IFF we make the scheduler respect same-claim = same-node (for RWO) then
*maybe* I can buy it.  Without that guarantee, it is inconsistent from an
end-user's POV as to whether it will work or not.

I can engineer pods landing on the same node even without anything fancy though (write spec.nodename, pod affinity, node lables etc). 

I can also setup poor mans replication with this. A volume pod per node (say /data, and it's /data on everynode, just a different pd), carve out that volume based on some id (so each pod would get /data/podname), and have the volume pod periodically rsync /data/podname to every other node.

**Comment by thockin** [comment]
On Mon, Aug 1, 2016 at 10:12 AM, Prashanth B <notifications@github.com> wrote:
>
> IFF we make the scheduler respect same-claim = same-node (for RWO) then
> maybe I can buy it. Without that guarantee, it is inconsistent from an
> end-user's POV as to whether it will work or not.
>
> I can engineer pods landing on the same node even without anything fancy though (write spec.nodename, pod affinity, node lables etc).
>
> I can also setup poor mans replication with this. A volume pod per node (say /data, and it's /data on everynode, just a different pd), carve out that volume based on some id (so each pod would get /data/podname), and have the volume pod periodically rsync /data/podname to every other node.

I don't understand your point.  If we allow same-node-RWO to be
shared, we shift the burden of correct behavior from Kubernetes onto
end-users. That is crappy.  Those users who know well enough (e.g.
you) can make it work.  Everyone else will experience that "sometimes
it works and sometimes it doesn't".

**Comment by bprashanth** [comment]
Ack that it might be confusing. Just that if it's possible on gce people will expect it to be possible on gke. People continue to question why ingress can only see Services in its namespace.

**Comment by bprashanth** [comment]
I believe if we wanted to fix this we need to dereference claims instead of just plain volume source: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L121

**Comment by thockin** [comment]
Also see https://groups.google.com/d/msgid/kubernetes-dev/5388741470411967428%40unknownmsgid wherein Clayton, without prompting, agrees with me (buy a lottery ticket, this is a rare event!)

**Comment by thockin** [comment]
We have two threads on this.  I am closing this one and asking everyone to instead discuss it on #26567

**Comment by thockin** [comment]
Actually, I am going to re-open this.  The GCEPD docs and volume driver are buggy and shoul be updated. That is what this bug is about.

**Comment by gmatev** [comment]
@thockin it does not seem that the idea of NOT allowing pods to share a RWO claim when they land on the same node ever made it through, correct? 

Having shared pod access (absolutely agree that for applications that want to be able to provide seamless update, one needs to allow it) does lead to corruption fairly easily. One example, that we recently ran into was an update to a Postgres deployment (1 pod replicaset based on widely used stable chart). As part of an operation that required an update to the deployment, the old pod was gracefully terminating (causing Postgres to do some state cleanup) while the new one was coming up (doing some prep as part of startup) resulting in corruption. 

It's subtle behavior and too dangerous to be default when some level of exclusive write (even though clearly documented a the node level) was implied with RWO.  Sharing between the pod certainly has its place but would be good to be more explicit and then the application can do explicit coordination.
