### ISSUE TITLE
All Heapster logs show up as ERROR logs in the Google Cloud log viewer

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#29862]
Presumably because they're written to stderr, leading to questions like http://stackoverflow.com/questions/38672505/log-are-shown-as-error-when-they-are-just-info

@piosz @mwielgus

**Comment by Crassirostris** [comment]
@piosz Well, it's fixed by https://github.com/kubernetes/kubernetes/pull/39151
