### ISSUE TITLE
cmd/hyperkube has diverged from contrib/mesos/cmd/km

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#29865]
Looks like km (at least `contrib/mesos/cmd/km/km.go`) has diverged from hyperkube enough to break builds with `KUBERNETES_CONTRIB=mesos`. Also looks like there are a lot of other files in `contrib/mesos/cmd/km` that are "clones" of files from hyperkube, I haven't yet had time to check if these also need to be updated.

**Comment by mtaufen** [comment]
/cc @jdef 
and assign since I don't know anyone else who knows mesos :). Feel free to reassign.

**Comment by k82cn** [comment]
@mtaufen , just passed build with `export KUBERNETES_CONTRIB=mesos` on master; which error do you mean? I can also help on `k8s on mesos` :).

**Comment by mtaufen** [comment]
Huh... my builds pass now too. Ugh, I wish I had written down the hash I was on when I saw this. 

I had an undefined identifier in km.go error (I forget which one it was, but it was one of the functions passed to `AddServer`). At a glance I assumed, with respect to the CAUTION comment in `cmd/hyperkube/main.go`, that it might have been because a name of a function changed . Now I'm face-palming because obviously those `main` packages are different and the functions passed to `AddServer` could easily have different names.

So it doesn't seem to be due to any difference between those two files. I'm going to go ahead and close this since it doesn't seem like there's anything wrong anymore with respect to the original issue. Thanks for taking a look at this, Klaus. You might want to open a separate issue for that test failure.
