### ISSUE TITLE
Federation e2e tests must clean up dynamically provisioned PDs while tearing down the clusters.

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#29875]
The `federation-apiserver`'s etcd is backed by a PVC that dynamically provisions the underlying persistent disk for its PV. We are not cleaning this up when we tear down the federation control plane and the corresponding test clusters. This caused us to run out of quota and the tests started failing.

We should delete the dynamically provisioned persistent disks at the end of the e2e tests, while tearing the clusters down.

@colhom are you seeing this behavior in your test clusters in AWS too?

cc @kubernetes/sig-cluster-federation @mml

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#62.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
