### ISSUE TITLE
kubectl pod status: describe does not match get

### ISSUE THREAD

**Issue by astropuffin** [kubernetes/kubernetes#29876]
I noticed this thing today when I rolled out a multi-container pod.
Context: I have 2 containers, 1 is a sidecar that completes within seconds, the other is a long running task that completes after several hours.

```
> kubectl get pods
NAME                  READY     STATUS      RESTARTS   AGE
…
pod-name             1/2       Completed   0          16m
…
> kubectl describe pod pod-name | grep 'Status\|State\|Reason'
…
Status:         Running
    State:              Running
    State:              Terminated
      Reason:           Completed
```

Question: Why does the pod `Status` in `describe` not match the pod `Status` in `get`?

I looked for similar issues using the following search: `is:issue is:open kubectl Status describe get`

**Comment by astropuffin** [comment]
Here's the get output with yaml:
```
> kubectl get pod-name -o yaml |less
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2016-08-01T19:58:55Z
    message: 'containers with unready status: [kube-meta-sidecar]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  containerStatuses:
  - containerID: docker://54385b1b0ec4dc073c2f3a9c4bb8572b0783a21d6008f71795b9239547af1371
...
    state:
      terminated:
        containerID: docker://54385b1b0ec4dc073c2f3a9c4bb8572b0783a21d6008f71795b9239547af1371
        exitCode: 0
        finishedAt: 2016-08-01T19:58:52Z
        reason: Completed
        startedAt: 2016-08-01T19:58:42Z
  - containerID: docker://8d418b8d5b2f3916c3c96654e183ec34c547a8411f1cc51942e8a25334fca51f
...
    state:
      running:
        startedAt: 2016-08-01T19:58:39Z
...
```

**Comment by xingzhou** [comment]
#investigating, can reproduce in my environment

**Comment by pwittrock** [comment]
@xingzhou what are the steps to reproduce from scratch?

**Comment by pwittrock** [comment]
@AdoHe Want to look at this when we get steps to repo?

**Comment by AdoHe** [comment]
@xingzhou could you please paste reproduce steps here?  I will take a look.

**Comment by xingzhou** [comment]
Here was what I did locally yesterday, I'm using master branch's code:
1. Start k8s cluster by running ```sudo hack/local-up-cluster.sh```
2. ```export KUBERNETES_PROVIDER=local```
3. Use the following file and command ```cluster/kubectl.sh create -f pod.json``` to create the pod:
```
{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "dd-multi-containers",
    "labels": {}
  },
  "spec": {
    "containers": [
      {
        "name": "long-running",
        "image": "nginx",
        "ports": [
          {
            "containerPort": 6379
          }
        ]
      },
      {
        "name": "short-running",
        "image": "ubuntu",
        "ports": [
          {
            "containerPort": 8000
          }
        ]
      }
    ]
  }
}
```
4. Run ```cluster/kubectl.sh get pods``` to check the status of the pod, the value could be "COMPLETED" or other non-running status. The "READY" field of the pod will be "1/2"
5. Run ```cluster/kubectl.sh describe pod dd-multi-containers | grep Status```, the status seems is always "Running"

cc: @AdoHe & @pwittrock

**Comment by xingzhou** [comment]
Took a look at the code, here are some findings:

1. For ```kubectl describe``` command, it's using "[pod.Status.Phase](https://github.com/kubernetes/kubernetes/blob/431e7ce1ab9f6086d38538a28989741f0576114c/pkg/kubectl/describe.go#L525)" to describe the pod's status. [Here](https://github.com/xingzhou/kubernetes/blob/master/pkg/api/types.go#L1102-L1119) defines the possible pod phase values.
2. For ```kubectl get pods``` command, it's using pod's one non-running container's "[reason](https://github.com/kubernetes/kubernetes/blob/aedeccda9562b9effe026bb02c8d3c539fc7bb77/pkg/kubectl/resource_printer.go#L692-L764)" field to describe the whole pod's status. If all the pod's containers are running, then the status of the pod can be the phase of the pod

I think this can explain why we see different pod statuses from these two commands. From my side, I'm thinking that it might not be a good way to just use one container's "reason" field to describe the whole pod's status. For multi-containers pod, in different situations, it's hard to say what exactly the pod's current status is. Not sure if we can just show the "phase" of the pod when using ```kubectl get pods```, and in addition, we can add a message to the output saying that "Run 'kubectl describe pod <pod-name>' to check each container's status in this pod."

**Comment by AdoHe** [comment]
@smarterclayton is there anyway that we can make this behavior unified? To set pod status correctly based on all containers status.

**Comment by AdoHe** [comment]
@xingzhou @astropuffin @smarterclayton kubectl get pod status has problem with multi-containers pod, we don't handle this case very much. Actually in @astropuffin case, the pod should be running.

**Comment by xingzhou** [comment]
@AdoHe, do we need some followup actions to fix this? or any suggestions on how we can handle multi-container pod status?

**Comment by smarterclayton** [comment]
The UX evolution of `kubectl get` and the `status` field was involved, but took a lot of feedback from end users about highlighting particular problems.  The reason (if i recall correctly) was that we have a limited amount of space to show useful info, and a divergent container is more important than the overall status of the pod.  The expectation is that a user would use `kubectl describe` to get that more info, but that it's still very important that `get` at least let you know something is wrong.

**Comment by AdoHe** [comment]
```
it's still very important that get at least let you know something is wrong.
```
I could support this.

And more importantly we should provide more status info in describe output. @xingzhou would you want to take a look?

**Comment by xingzhou** [comment]
yes, let me propose some solutions then.

**Comment by xingzhou** [comment]
Here is a solution for discussion:
for those pods that satisfy the following conditions:
- the pod has multiple containers
- some of the pod's containers are not in running status
- at least one of the pod's container is ready and in running status

when user use 'kubectl get pods' command, we can add an asterisk to the status of those pods and finally add one hint message to explain to the user that some of the pod's container are not running.  Here is a sample for reference:
<img width="996" alt="2016-09-20 1 25 15" src="https://cloud.githubusercontent.com/assets/5344440/18658570/d840f896-7f36-11e6-82dd-c76f5b576d71.png">
@AdoHe and @smarterclayton, welcome your comments, if you think is ok, I will submit a patch then.

**Comment by astropuffin** [comment]
@xingzhou @AdoHe @smarterclayton 
I like the asterisk. It summarizes that there is something non-binary going on that requires a more nuanced interpretation. However, in the case of containers that have exited successfully, the status of the pod as a whole is better described by the status of the container(s) still in progress (i.e. Running). In the case of a pod with a failed container, then as a user I would expect the pod status to be `Failed*` or similar.

| C1 | C2 | expected pod status |
| ---- | ---- | ---- |
| long running/eternal | short running, but successful exit | `Running*` |
| long running/eternal | short running, but unsuccessful exit | `Failed*` |

Note there could be more than two containers that exit at different times.

**Comment by boddumanohar** [comment]
has this issue been unified? did kubernetes unify `kubectl get events` and the events seen in `kubectl describe pod`?
