### ISSUE TITLE
CRI: deprecating podsandbox resource requirements in favor of the pod level cgroup

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#29871]
@vishh brought up a nice suggestion that the function of pod level cgroup overlaps with the podsandbox resource requirements. We can deprecate the podsandbox resources fields from CRI, and the container runtime derive cpu/mem limits from the passed cgroup. It's also worth noted that we initially determined to pass these additional resources to podsandbox creation calls because hypervisor-based runtimes need to know in advance how much resources are required by a VM (i.e., the sandbox). Other non-hypervisor based runtimes should not need to care about these fields.

*What about resources that are not captured by the per-pod cgroup?*
 We don't know yet what other resources we want to pass to the sandbox yet. It's preferred all such experimental features to be described in and passed via annotations.

*Pod level cgroup has not been completed yet. How can we rely on it?*
Pod level cgroup is 80% done. In the meantime, we can always pass cpu and memory limitations through annotations.

/cc @kubernetes/sig-node @feiskyer @vishh

**Comment by yifan-gu** [comment]
cc @euank @tmrts 

What's the gain we removing the pod level resources and still use annotations? My thought is that if some "annotation" will present in most cases, then we probably need to think about making them explicit.

**Comment by yujuhong** [comment]
The problem is we don't yet know what we need for pod level resources, and once the pod-level cgroup work completes, we don't need cpu/memory for sure. We can always add pod level resources once it becomes obcious that we need them.

**Comment by dchen1107** [comment]
My initial proposal on Container Runtime interface is without Pod level resource requirement, but later I decided not block on that since we can iterate this anyway. 

The main reason I have is that the pod level resource requirement might (not in today) be dynamically updated due to various reasons, for example: pod vertical scaling. If Kubelet pass the pod resource requirement at creation time, when the system (Kubelet and controller) updates the resource requirements, should Kubelet call UpdatePodSandbox? Today we forbid such update on purpose for many reasons.

Another gain is less confusion to the container runtime since Kubelet already pass parent cgroup path (pod level cgroup) to the runtime so that the runtime can figure the available from cgroup, the truth from the horse's mouth. :-)

**Comment by yifan-gu** [comment]
@dchen1107 OK, but for updating the resource of the vm based pod sandboxes, I don't think changing the cgroup quietly is enough, right?  When does the vm gets notification? Should it watch the cgroup?

**Comment by dchen1107** [comment]
@yifan-gu I know ppl are talking and using balloom driver to dynamically update vm's size, but how reliable and dynamically is? I assume in hyperd's case, all pods are running as guaranteed today, and without overcommit at all, thus, there is no resource updates at pod level. They might change later, but our API can be iterated later too. I prefer tighter control at API level first, then iterate / update when real use cases are coming.

**Comment by feiskyer** [comment]
@dchen1107 vm only supports increase vm's size (cpu and memory), but decrease is not supported. If decrease is necessary, then vm must be restarted.

>  for updating the resource of the vm based pod sandboxes, I don't think changing the cgroup quietly is enough, right? When does the vm gets notification? Should it watch the cgroup?

This is a problem. I think `UpdatePodSandbox` or `UpdatePodSandboxResources` may be needed eventually.

**Comment by yujuhong** [comment]
I think we should acknowledge that resource management for VMs is different from that for containers. The complexity is even higher if there are both containers and VMs running on the node. Simply specifying a pod sandbox resource requirement in the API doesn't solve all the issues, and could be misleading. I propose that we remove the current pod sandbox resource, and address the issue later more systematically. Objections?

**Comment by dchen1107** [comment]
@yujuhong Agreed with above. Again, we are going to iterate the API many times, before and after we have first version of CRI implementation ready.

@feiskyer 
> This is a problem. I think UpdatePodSandbox or UpdatePodSandboxResources may be needed eventually.
We talked about UpdatePodSandbox internally before the first proposal was out for community review. Yes, we might need it later, but it is not required for today's use cases. Thus, we punt it for cutting the complexity.

**Comment by feiskyer** [comment]
@dchen1107 Thanks. It's ok for now. we can iterate resource management later after first version of CRI implementation ready.

**Comment by dchen1107** [comment]
Close this one since we reached agreement on the API, and pending pr reflecting the decision should be merged shortly too.
