### ISSUE TITLE
federation: Support creating resources in specific clusters

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#29887]
Right now, when users create federation resources (for ex: services, namespaces), we create them in federation control plane and all underlying kubernetes clusters. We need to enable users to be able to specify a subset of kubernetes clusters in which that resource should be created.
For ex: while registering a cluster, user needs to create a secret with kubeconfig for that cluster. This secret is required only in the federation control plane and not in the underlying kubernetes cluster. We need a way for users to specify that this secret should not be created in any of the underlying kubernetes clusters.

Proposal: Support annotation with key `federation.beta.kubernetes.io/cluster-selector`. Value will be a struct ClusterSelector which be exactly same as [NodeSelector](https://github.com/kubernetes/kubernetes/blob/ed763b8034eebb84dd3682ab0230276b1bb23845/pkg/api/v1/types.go#L1406).
All federation controllers will be looking for this annotation to decide in which kubernetes clusters should that resource be created.
Note: If the create request was sent to federation apiserver, then the resource will always be created in federation control plane. This cluster selector is to decide in which kubernetes clusters should the resource be created in.

Work items:
- [ ] Define ClusterSelector in the API.
- [ ] Update existing federation controllers to honor the annotation (Just services controller for now)

**Comment by nikhiljindal** [comment]
cc @kubernetes/sig-cluster-federation 

Have to figure out if the annotation should be `federation.alpha.kubernetes.io/cluster-selector` or `federation.beta.kubernetes.io/cluster-selector` (alpha or beta)

**Comment by nikhiljindal** [comment]
Discussed this with @bgrant0607 and he agreed that starting with an annotation is fine. We still need to figure out if it makes sense to graduate it into a field. Since this will be for all objects, it will have to go in ObjectMeta.
We also discussed using the new Cluster field in ObjectMeta (https://github.com/kubernetes/kubernetes/pull/28921#issuecomment-240865189) for users to be able to specify the cluster in which they want to create resources. This only works when users want to create their resource in a particular cluster, but is more clearer and definitive than ClusterSelector. ClusterSelector is more flexible.

We are going to start with ClusterSelector annotation and ignore the Cluster field in create and update requests.

**Comment by quinton-hoole** [comment]
SGTM!

**Comment by bgrant0607** [comment]
@nikhiljindal Cluster labels will be represented where? Only on the cluster resources in the federated master?

**Comment by bgrant0607** [comment]
Note that the decision about in which cluster to place resources usually depends on the placement of dependent resources.

**Comment by nikhiljindal** [comment]
> @nikhiljindal Cluster labels will be represented where? Only on the cluster resources in the federated master?
> 

Yes cluster objects in federation control plane will have the labels.
There was discussion regarding each kube cluster exposing its own cluster identity (a uid and name). If we decide to do that as an API resource in kube cluster, then we can also add the labels there.

> Note that the decision about in which cluster to place resources usually depends on the placement of dependent resources.

Yes. Thats a good point. Need to think more on it

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @nikhiljindal @quinton-hoole

**Comment by dims** [comment]
Moving this to milestone v1.6 ( cc @kubernetes/sig-cluster-federation ) Based on Nikhil's last comment ("Yes. Thats a good point. Need to think more on it" from Sep 22)

**Comment by emaildanwilson** [comment]
+1 on this, I'll start looking at what it would take to make it happen.

**Comment by emaildanwilson** [comment]
If we want to reuse the same logic for podnodeselector then I think it will need to be updated to be more generic and allow for more than just pods. It seems to be filtering that currently. https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/podnodeselector/admission.go#L93

Should I instead create a new admission package for clusterselector?
Is there a preferred approach to take, other ideas or options I'm missing?

**Comment by emaildanwilson** [comment]
@nikhiljindal Any thoughts here... is it better to have the code all exist in the federation subdirectory?

**Comment by nikhiljindal** [comment]
Sorry it is not clear to me why do we want an Admission controller for this?

I was hoping that we can just update federation controllers to look at the cluster selector annotation and then create resources in only those clusters that match the annotation instead of creating it in all clusters (which is what they do today).
Am I missing something?

**Comment by emaildanwilson** [comment]
as discussed in chat, we'll stick with handling the logic without an Admission controller and look into adding it later if required.

**Comment by nikhiljindal** [comment]
Yes. I checked and that PodNodeSelector admission controller is off by default: https://github.com/kubernetes/kubernetes/blob/8fd414537b5143ab039cb910590237cabf4af783/cluster/azure-legacy/config-default.sh#L60

**Comment by emaildanwilson** [comment]
I created a google doc detailing out the logic that will be used to determine if an object with a ClusterSelector annotation will be forwarded on to federated clusters or not based on label. There a the following rules here (once again based on our chat).

1.  An object with no ClusterSelector annotation will always be forwarded on to all federated clusters even if they have labels configured. (this ensures no regression from existing functionality)

2. If an object contains ANY ClusterSelector annotations then ALL of them must match in order for the object to be passed onto the federated cluster.

Here is a table showing how this would work with a few examples.
https://docs.google.com/spreadsheets/d/1b6NcQ5IPGysV9OE9uKuq5jbVEXFIEpRGQS8hsAP97Ec/edit#gid=0

The benefit to this approach is that as a cluster operator one could advertise that certain menu of labels are used to determine where resources would end up and said operator could ensure that all clusters have these specific labels in order to provide the functionality expected (for example, region, location, environment, version, etc). Requests for resources of certain types are always explicit and if one needs for example location=us and clusters are not defined to have this label, then you can rest assured that resources will not be built out in any clusters until one exists with that specific label.

The drawback to this approach is that if a cluster is missing a label then more restrictive requests could result is workloads not getting scheduled. For example, if location=us & version=1.5 is requested but the only clusters available are location=us and location=eur then the object(s) would not be forwarded to any federated clusters.

I'll leave this open for anyone to comment for a few days before starting to implement any of this logic.

**Comment by emaildanwilson** [comment]
I submitted a pull request with the initial logic and tests for this. 
We'll need to decide how to address handling situations where an object was initially sent to all clusters and then subsequently was updated to be isolated to a subset of clusters. 
Should the system...
- let the object stay on the clusters no longer targeted at an old version (which is what it would do after #40234)
- add in functionality to remove the object from any federated clusters for which it is not targeted

My preference is to remove the objects to keep things clean.
thoughts?

**Comment by nikhiljindal** [comment]
Sorry for the delay in reviewing your PR.

I dont see it mentioned here, but I remember we also discussed whether we should use `map[string]string` or a struct similar to `[NodeSelectorTerm](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L1804)`
I think the NodeSelectorTerm struct is more clear and flexible and hence we should use that. 

I am not sure if we can just reuse that struct or clone it. @bgrant0607 suggested cloning it so that we can have clear documentation (will need to have generic comments on the struct if we decide to reuse).
cc @davidopp as well to see what he thinks about renaming the struct to make it reusable or cloning it for our purposes.

**Comment by nikhiljindal** [comment]
> My preference is to remove the objects to keep things clean.
> thoughts?


Yes I agree. We should remove the object from any federation clusters for which it is not targeted.

**Comment by emaildanwilson** [comment]
I believe I found a generic version of the NodeSelector in the apimachinery project. I'm going to use this along with the matching functions there unless this is of concern. https://github.com/kubernetes/apimachinery/blob/master/pkg/labels/selector.go#L33

**Comment by nikhiljindal** [comment]
That struct is not intended to be part of an external API. Anyone changing it will not realize that they are changing an external API. We also need to add to add API documentation tags there (you will notice the `json` and `protobuf` tags on structs in types.go: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L272).

If your aim is to reuse the util functions, you can duplicate the structs and update the util functions to accept an interface so that they can be used with both structs?

**Comment by emaildanwilson** [comment]
ok, yes I noticed that it's not exported. I'll add the protobuf tags.

**Comment by smarterclayton** [comment]
Hrm, nothing inside of apimachinery except meta/v1 should have json or protobuf tags.  What are you planning on using?

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by nikhiljindal** [comment]
Documented the list of open questions related to this at https://docs.google.com/document/d/19FiXgHjylk-sbGvLuQjWPKFWctGuiQ75b-HCgYK6zq0/edit.

**Comment by nikhiljindal** [comment]
> > @bgrant0607:
 Note that the decision about in which cluster to place resources usually depends on the placement of dependent resources.
> 
> Yes. Thats a good point. Need to think more on it

One possible solution is to put dependent objects in the same namespace and then put cluster selector on the namespace. Then all resources in that namespace will go to clusters where the namespace exists.

**Comment by quinton-hoole** [comment]
@bgrant0607 @nikhiljindal I think that we should use affinity to express that.  I really don't like overloading namespaces even more than they already are.  They've become the kitchen sink for a whole bunch of grouping concepts from spaces for names, to security domains to now placement groups.  Lets stay away from them if at all possible please.

**Comment by nikhiljindal** [comment]
@quinton-hoole namespace is just one grouping mechanism we have been able to come up with for now. Open to other suggestions.

Trying to summarize the discussion we had (meeting notes: https://docs.google.com/document/d/1pryndmGBnQ93hmR_kJu5j7Y440xL4AO8AvOrHWOTOwM):
* There are 3 use cases for specifying cluster selectors:
1. Developer specifying cluster selector for his individual resource (which is what this issue was focussing on).
2. Developer/team wanting to specify cluster selectors for multiple resources. Example a team wanting to apply cluster selectors on all resources in a single namespace. There can be other grouping mechanisms.
3. Admin wanting to specify cluster selectors on many resources. Like all resources with labels env=prod should go in pci-compliant clusters or only on prem clusters (https://github.com/kubernetes/kubernetes/issues/39982).

We agreed that there should be a single place where the merged cluster selectors should live (can be on the resource in status or a separate object which has 1:1 mapping with the resource). 
A framework that we discussed to support all 3 use cases is:
* Developer specifies the ClusterSelector (on the resource in spec or objectMeta?)
* There is a separate policy enforcer that reads admin policy and figures out the cluster selectors required to enforce that policy and puts them on the resource (merging them with the existing cluster selectors, if any).

Once we have more clarity on what grouping mechanism to use, the grouped cluster selector enforcer can also do what policy enforcer is doing (put the cluster selectors on the resources that the grouped cluster selectors apply to).
That way, there is a single place where the final cluster selectors are. There are multiple ways by which those cluster selectors are updated. We also discussed having 2 different fields: one in spec (or objectmeta) and one in status. ClusterSelector specified by the developer directly on the resource should be in spec and the merged clusterSelector should be in status.

We didnt get to discuss if we should merge ClusterSelector and ClusterPreferences and should that be a blocker to implementing ClusterSelector.

**Comment by marun** [comment]
Not a release blocker for 1.7.

@emaildanwilson Are there controllers that still need to be updated to support cluster selection so this issue can be closed?

**Comment by emaildanwilson** [comment]
If the replicasets and deployments conversion to the sync container have
now been merged then this can be closed.

**Comment by marun** [comment]
Ah, not yet.

**Comment by therealplato** [comment]
I found this issue deep down the rabbit hole, looking for a way to specify one of several clusters that my svc/deployment/configmap manifests must use.
Am I out of luck for now?

**Comment by quinton-hoole** [comment]
@therealplato there is some work in progress on this.  We should have some concrete news within a few weeks.

**Comment by nikhiljindal** [comment]
federation 1.7+ includes annotations based support for cluster selector: https://kubernetes.io/docs/tasks/administer-federation/cluster/#clusterselector-annotation

Closing this.
