### ISSUE TITLE
Make kubemark-500 blocking suite

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#29897]
We should:
- [x] fix kubemark-500 (there are some startup issues there)
- [x] create small kubemark (e.g. kubemark-5) on presubmit
- [x] enable kubemark by default in presubmit
- [x] start blocking on kubemark failures in presubmit
- [x] readd kubemark-500 to postsubmit

**Comment by wojtek-t** [comment]
@lavalamp

**Comment by wojtek-t** [comment]
@gmarek - it seems that this is the PR that broke kubemark:
https://github.com/kubernetes/kubernetes/pull/28955

It shouldn't be that hard to fix kubemark startup script.

**Comment by wojtek-t** [comment]
It seems that @lavalamp reverted the offending PR for us, so the first bullet is done.
We should do the other two ASAP, to avoid such situations in the future.

**Comment by dims** [comment]
@lavalamp @wojtek-t Do you have any theories of why that PR broke kubemark? So i can fix up the PR again properly?

**Comment by wojtek-t** [comment]
@dims - didn't have time to look into it, sorry

@spxtr @fejta - is there anything magic that needs to be done to create new presubmit suite? Or is it like normal suite:
- setup new GCE project
- add definition of a job to "test-infra/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull.yaml
?

**Comment by gmarek** [comment]
@dims - I don't know, all kubectl calls in kubemark start here: https://github.com/kubernetes/kubernetes/blob/master/test/kubemark/start-kubemark.sh#L280

**Comment by lavalamp** [comment]
@gmarek @wojtek-t Kubemark is currently very annoying to debug. The startup script doesn't log useful information (if it logged the output of those commands the problem would probably be obvious.) Additionally, it doesn't save anything from the kubemark master. To make progress on this I had to build, start cluster, and log in myself. That's going to be really annoying for people who accidentally break the presubmit.

**Comment by spxtr** [comment]
@wojtek-t That's correct. It is a bit of a pain to do, though, because the github plugin will try to run the suite on every open PR when it gets added which will cause problems.

**Comment by wojtek-t** [comment]
@lavalamp - debugging startup of real cluster is also annoying (at least for me). But sure, we can add some logs.

>
Additionally, it doesn't save anything from the kubemark master.

Then something has changed - we used to copy artifacts from kubemark master components - I can check that tomorrow. If we don't save them, someone broke it again.

**Comment by wojtek-t** [comment]
Also - we really need kubemark-500 in post-submit to avoid performance regressions. And if the only way to have it is to have some kubemark in pre-submit (which is a reasonable request), then we really need to do it.

**Comment by lavalamp** [comment]
I've never seen a kubemark job result that included logs from the kubemark
master components-- I just looked at a random passing kubemark 5 job and it
only has files from one master, it doesn't even have files from the node.

**Comment by lavalamp** [comment]
Maybe there's a bug where it doesn't copy the logs from kubemark components
if it doesn't finish the startup script?

**Comment by lavalamp** [comment]
The bot is still going to file issues if it breaks, at least.

**Comment by wojtek-t** [comment]
>
The bot is still going to file issues if it breaks, at least.

This is good short term, but I don't think it's enough medium/long-term.


Regarding logs, I checked it and it is supposed to store logs only from runs for which something failed (either startup or tests):
https://github.com/kubernetes/kubernetes/blob/8cf40ebe259fea7d8773d8596a0d474fe2196fee/hack/jenkins/e2e-runner.sh#L415
https://github.com/kubernetes/kubernetes/blob/8cf40ebe259fea7d8773d8596a0d474fe2196fee/hack/jenkins/e2e-runner.sh#L423

**Comment by lavalamp** [comment]
Makes it hard to tell if it's working... ;)

**Comment by wojtek-t** [comment]
This is basically doing for federation what we would like to do for kubemark:
https://github.com/kubernetes/test-infra/pull/335

We should do something pretty similar.

**Comment by wojtek-t** [comment]
I created Jenkins project for it:
https://pantheon.corp.google.com/home/dashboard?project=k8s-jkns-pr-kubemark

We need to configure kubemark-presubmit on it.

**Comment by wojtek-t** [comment]
It's already possible to write "k8s-bot kubemark test this" - though there are still some issues with it, which I'm trying to figure out in the background.

**Comment by wojtek-t** [comment]
"@k8s-bot kubemark test this" should now work.

We should try to enable it by default on PR, but not block the PRs on it yet.

**Comment by smarterclayton** [comment]
Woohoo

On Sep 1, 2016, at 10:36 AM, Wojciech Tyczynski <notifications@github.com>
wrote:

"@k8s-bot <https://github.com/k8s-bot> kubemark test this" should now work.

We should try to enable it by default on PR, but not block the PRs on it
yet.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/29897#issuecomment-244098812>,
or mute the thread

**Comment by wojtek-t** [comment]
Kubemark is now enabled by default in-presubmit.

Once we are sure that this isn't flaky in presubmit, we will start blocking on it.

**Comment by wojtek-t** [comment]
Kubemark-500 is alrady blocking.
