### ISSUE TITLE
[RFC][GarbageCollector] expose the progress of garbage collection

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#29891]
**Problem:**
Currently, if a user deletes an owner object, the object will be deleted from the apiserver right away. The garbage collector (GC) will delete the dependent objects in the background. _User has no way to observe the progress of the garbage collection._

The progress of gc is useful information in some scenarios. For example, currently `kubectl delete` will block until all dependent resources are reaped, to maintain the same behavior when we turn on the GC, `kubectl` needs to know when the gc is done.

**Tentative solutions**
1. Utilize the [finalizer](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L152) framework. When a deletion request is sent for the owner object, instead of deleting it from the storage, api-server adds string "gc" to the object's ObjectMeta.Finalizers list, GC will observe the change and recursively deletes its dependents. After all dependents are deleted, GC will finally delete the owner from the apiserver. So a client can infer if the gc is done by polling the existence of the owner object.
   The **downside** is that the gc can be recursive (e.g., gc of a Deployment) and can take long time, so the owner object's name will be hold for a long time.
2. Let GC support queries for dependent objects. So a user can send the UID of the owner object to the GC and GC will respond with a list of dependent objects (GC already keeps a dependency graph in the memory). A client can infer the garbage collection is done when the returned list is empty. This information will be valuable for debugging as well.
   The **downside" is that the api will be informal. Such an API is meant to be consumed by human rather than to be programmed against.

I think we need to understand the use cases to decide which solution is better. Please comment.

@bgrant0607 @lavalamp @smarterclayton @pwittrock @kubernetes/sig-api-machinery

**Comment by pwittrock** [comment]
> 1. ...

Synchronous.  How does this work with the controller-manager?  Does the finalizer framework ensure the objects no longer are seen by the controller-manager?

> 2. ...

Asynchronous.  Would the client then poll (blocking) until everything gets cleaned up?

**Comment by caesarxuchao** [comment]
> Synchronous. How does this work with the controller-manager? Does the finalizer framework ensure the objects no longer are seen by the controller-manager?

From the point of view of the client, approach 1 is also asynchronous. The api-server responds the deletion request immediately, though the object is not deleted from the api-server.

Controller manager will still see the object. The apiserver will set the object's deleteionTimestamp. Controllers will stop acting on objects with non-nil deletionTimestamp, except updating their status. This is already implemented.

> Asynchronous. Would the client then poll (blocking) until everything gets cleaned up?

Yes.

**Comment by pwittrock** [comment]
> From the point of view of the client, approach 1 is also asynchronous. 

What happens if failures are encountered when deleting the child objects?  Does the parent object still get deleted?  Are these retried?

**Comment by caesarxuchao** [comment]
The deletion should be retried (currently it's not, but it should be a one-line change to fix).

**Comment by caesarxuchao** [comment]
We'll take the first approach. The two approaches are not exclusive, we can implement the second approach as well if we can clear all the security concerns.

We will not block GC from beta for this issue. We will add DeleteOptions.WaitForGCDone after beta, it will be default to false.

**Comment by gmarek** [comment]
FYI: Logic that prevents controller from taking any action is not implemented in a PetSet (lack of time:/). We probably need to find someone to do it.

**Comment by smarterclayton** [comment]
Which logic?  We have an open issue that is roughly slated for 1.5 to
ensure that PetSet isn't vulnerable to node evictions causing a split
quorum - using a finalizer is the currently preferred approach there.

**Comment by gmarek** [comment]
Sorry for being vague - the one @caesarxuchao mentioned here https://github.com/kubernetes/kubernetes/issues/29891#issuecomment-236773005 . So the logic that prevents PetSet controller from *doing stuff* when deletionTimestamp for a given PetSet is not nil.

**Comment by caesarxuchao** [comment]
@gmarek thanks for the reminder. It won't cause any trouble until we convert the PetSet to use controllerRef. I'll see if I have time to do it.

**Comment by smarterclayton** [comment]
Ok - my thing is layered on top of that.  Dependent.

**Comment by caesarxuchao** [comment]
Proposal for "Synchronous mode GC" (https://github.com/kubernetes/kubernetes/pull/32628) got merged. Implementation will be done in 1.6.
