### ISSUE TITLE
[Proposal] Running Kubernetes in heterogeneous environments

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#29901]
Currently, Kubernetes could run on ARM or X86; but in heterogeneous environment, e.g. Power & X86, the user need to configure in YML on which hosts is used to run service. It’s inconvience for cluster admin & users, and it’s hard for cluster admin to decide which type of hosts should be used in a large cluster.
In this topic, we’re going to show an enhancement of kubernetes to run in heterogeneous environment; kubernetes will help to decide which image is used when running, and kubernetes will also help to chose which hosts is used to run Pods, e.g. Power or X86.

**Comment by luxas** [comment]
I'm working on exactly this issue: #26028

**Comment by luxas** [comment]
The admin may set `.spec.nodeSelector` to `beta.kubernetes.io/arch=ppc64le` in order to run a job only on ppc64le

**Comment by k82cn** [comment]
It's a bit different with #26028. This proposal is to let kubernetes select the right docker images for arch, instead of selecting nodes by selector; it'll use on `replica-controller` to manage different images in different arch.

**Comment by luxas** [comment]
Sorry, I linked the wrong issue. I meant #26863 :)
I have it in a TODO right now there, but I haven't got an automated solution; only the task :)

Please say what you're planning to do, it's interesting

**Comment by k82cn** [comment]
@luxas , there're two options for now:

**Option 1**: Add a new item names `images`, its sub-items will identify which image will be used according to the selector. But it‘s Inconvenient for the user when new type of nodes joins the cluster.

```
-images
  -selector: arch=ppc64le
    image: tomcat-ppc64le:7.2
  -selector: arch=x64
    image: tomcat-x64:7.2
```

**Option 2**: Support embed label name into images, and the label is replaced when dispatches to the node, e.g. define image to be `tomcat-${arch}:7.2`, when dispatching to PowerLinux, the `tomcat-ppc64le:72` is used; otherwise, `tomcat-x64:72` is used.

If any comments, please let me know.

**Comment by luxas** [comment]
That's relatively easy to accomplish; use manifest lists with [manifest-tool](https://github.com/estesp/manifest-tool).
A such API change wouldn't be approved I think, sorry (but you should verify it with others)

The hard part here is when you have two arches, let's say ppc64le and amd64, and you have an application that's written for only ppc64le. Then you are forced to apply the label, because the scheduler doesn't know anything about docker arches. But some tooling/preprocessing of the yaml files probably would do

**Comment by k82cn** [comment]
That's great, but not sure whether it support other register, e.g. Harbor. cc @estesp

@luxas , for the "hard part", I think it dependent on user's input; for example, it user define wrong images name, k8s will report an error event.

**Comment by luxas** [comment]
/remove-lifecycle stale

Manifest lists are now eventually supported in gcr.io so this is now unblocked.
@mkumatag is working on making the images manifest lists on the k8s side
/assign @mkumatag
