### ISSUE TITLE
Use the same validation for clusters in apis/federation/validation as in controllers/util.

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#29911]
Right now it is possible to add a cluster for which it won't be possible to create a client. For example client-related code does:

``` go
for _, item := range c.Spec.ServerAddressByClientCIDRs {
        _, cidrnet, err := net.ParseCIDR(item.ClientCIDR)
```

while validation checks only:

``` go
if len(spec.ServerAddressByClientCIDRs) == 0 {
```

cc: @jianhuiz @quinton-hoole

**Comment by dims** [comment]
switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree)

**Comment by marun** [comment]
Not a release blocker for 1.7.

**Comment by xiangpengzhao** [comment]
@guangxuli are you interested in fixing this?

**Comment by guangxuli** [comment]
@xiangpengzhao of course, will do that.
