### ISSUE TITLE
Multiple kubelet runtimes at the node

### ISSUE THREAD

**Issue by vefimova** [kubernetes/kubernetes#29913]
## **Motivation**

It's worth to enable running of "mixed" workloads (containers/vms/containers inside vms) using multiple kubelet runtime providers at the same node. Especially taking into consideration adding more runtimes not only for containers in near future: HyperContainer, oci/runc, kvm/qemu, libvirt.
## **Key functionality to implement:**
- **Add ability to set multiple runtimes for kubelet:**
  
   It is said in container server-client runtime proposal that there will be transition period
   during which old and new implementation will be available:
  1.  local implemetation
     Flag --container-runtimeshould support setting comma-separated list of runtime names
  2.  gRPC implementation
     A new flag --container-runtime-endpoint (overrides --container-runtime) which will identify the unix socket file of the remote runtime service should support setting comma-separated list of unix sockets
- **Change kubelet:**
  1. local implemetation
     Create runtime interface for every specified runtime in flag and initialize map("runtime_name"=>kubecontainer.Runtime) of runtimes in kubelet structure
  2. gRPC implementation
     Support map("runtime_name"=>KubeletRuntimeClient) of available/health runtimes
- **Kubelet needs to pass to api-server the list of available container runtimes on node.**
  This can be achieved by changing field containerRuntimeVersion in NodeSystemInfo 
  to be array of kubeletRuntimes with items of type kubeletRuntime in node status message from    kubelet: 

```
kubeletRuntimes: [
        {
            type: "docker",
            version: "1.11.0"
        },
        {
            type: "rkt",
            version: "1.10.1"
        }
]
```
- **Setting the kubelet runtime for pod is specified in annotation (docker by default):**

```
An example

    kind: Pod
    apiVersion: v1
    metadata:
        name: pod-abc   
        labels:
            foo: bar
        annotations:
           kubelet-runtime: docker
```
- **Add new policy for scheduler to pick up node accordingly to node annotation settings**

related to #28789
CC @thockin @freehan @brendandburns @dchen1107 @kubernetes/sig-node

**Comment by tmrts** [comment]
@vefimova motivation here is unclear to me can you elaborate on that? The
point of #28789 is to provide same capabilities with different runtimes.
Multiple runtimes would be just that and they would function the same way
more or less.

I believe this issue is more related to using multiple OSes (one container
runtime might not support an OS while another does, and you have data
centers with different architectures) and different virtualization
workflows (i.e. containers vs hypervisors) at the same time for Kubernetes.

**Comment by thockin** [comment]
@vefimova Thanks for the issue.  You say it's worth doing, but you don't say why.  The complexity of this is sort of overwhelming and I am viscerally against it without some overwhelming use case that justifies it.  We *do not* want end users caring about which runtime is in use.  That is overly coupled and becomes a slippery slope to specific versions, specific flagsets, etc.

Can you explain the intention?

**Comment by vefimova** [comment]
@tmrts 

It's more about ability to run containers/vms/containers inside vms using different runtime providers on the same node in cluster: rocket, docker, oci/runc, kvm/qemu, libvirt, hyperContainer.
Why to restrict node to run let's say only one type of pods using docker containers? You may want to utilize node for pods using another kubelet runtime as well?

The relation to #28789 is set as there are crossing areas in kubelet which will be changed within implementation of client/server runtime model and at the same time should be change to support multiple kubelet runtimes as well.

**Comment by thockin** [comment]
> Why to restrict node to run let's say only one type of pods using docker
containers?

The burden is not on the simpler solution to justify why it is sufficient,
but rather on the more complex solution to justify its own existence.

Every system has a "budget" for complexity.  Once you run out of that
budget, your system becomes harder and harder to deal with.  Everything
should be as simple as possible, by default.  Complexity needs to be
justified with real benefits, far beyond the hypothetical.

**Comment by vefimova** [comment]
@thockin 
So if you need to have cluster with heterogeneous workloads (containers + vms) based on k8s there won't be option for that?

**Comment by yujuhong** [comment]
> So if you need to have cluster with heterogeneous workloads (containers + vms) based on k8s there won't be option for that?

This is how I'll do it. I will create a cluster in which some nodes use hypervisor-based runtimes, while others use linux containers (but only one runtime per node). Then I'll label the nodes accordingly. When creating the workload, I'll specify the node selector to make sure my pods land on the right node.

**Comment by dchen1107** [comment]
@vefimova To solve your usecase, you can have some nodes with hyperd runtime, some nodes running linux-based runtime, but not multiples. To have more than one runtime at a node is extremely hard to manage. If there is a real need behind, I would rather expand a single runtime solution to support both linux-based container and vms based on the user's request.

**Comment by brendandburns** [comment]
@vefimova this is a totally legitimate request, I can definitely see the use case an motivation.  However, as @thockin @dchen1107 and others mention, the complexity of supporting this doesn't justify the implementation. 

For now, the approach suggested by @yujuhong and others of having container runtimes per node is probably the simplest solution.  You will lose some amount of utilization gains that you may have had because of increased fragmentation, but it will work.

Another solution would be to run KVM, etc _inside_ a Docker container, thus you have only one container runtime, but some of the containers you run, then run a VM.  This is less than ideal for a large variety of reasons, but it may fit some use cases.

Finally, as @dchen1107 suggests you can also build your own container runtime that knows how to run both VM and non-VM containers.

Hope that helps, I'll leave this issue open so that people can find and reference the conversation, but I don't think we're going to suggest that anyone start working on this for all of the reasosns listed out above.

**Comment by euank** [comment]
I'll throw in that the rkt runtime integration can experimentally support this now via setting an annotation of `rkt.alpha.kubernetes.io/stage1-name-override: coreos.com/rkt/stage1-kvm` on pods you want to run in VMs, leaving the rest to run as regular linux containers. This is the existing implementation of @dchen1107's answer :smile:

**Comment by pskrzyns** [comment]
cc @lukasredynk @jjlakis

**Comment by vefimova** [comment]
Thank a lot for the comments, folks. 
So from the listed opportunities:

1. - having separate bunches of nodes to run different runtimes, but only one at time, use node selectors in pods specs.
2. - "vm inside container" - implemetation: RancherVM
3. - "container inside VM", VM is used as isolator - implemetations: HyperContainer, rocket with lkvm support. 
4. - implement another one runtime which will support both linux-based container and vms - Seems like this is the way to go as we need direct qemu/kvm integration

only #4 is suatable as the use case assumes supporting pure VMs. Hence, decided to start from implementing qemu/kvm runtime, created issue fro this initiative: https://github.com/kubernetes/kubernetes/issues/30294

**Comment by smarterclayton** [comment]
I don't understand why you believe #2 can't be achieved - just because qemu is inside the container doesn't mean libvirtd can't be running elsewhere on the host?

**Comment by smarterclayton** [comment]
We've done a fair amount of initial diligence and believe #2 is achievable for full production VMs.  We'd be happy to collaborate with other folks to make that possible in an easy way on kube.

**Comment by Gnep** [comment]
The complexity is not only about runtime, also related with storage and network. 

Having heterogeneous runtime on different nodes in the same cluster is ok, but once you started to mix different SDN implementation for different runtime in one cluster, the pain is there.

I think it is better to use a two-layer scheduler and different sub-clusters for different runtime, until the other components (storage, network) are fully compatible.

**Comment by kfox1111** [comment]
I have a use case in mind for this too. On one of my systems, I have a small number of nodes in the cluster. (3). one of which is more of a quorum node (low power/capacity). I run most of my containers out of docker but I do have a need for vm level isolation for a few things that need a higher level of security and isolation then the rest. Being able to set an attribute on a pod to make it run in its own vm would be great. If docker and hyper could be run on the same node, you could use k8s to progressively enhance itself to add the vm support. Build hyper support in a container, land it on the node with a docker based daemonset, and it then plugs its socket into the local kubelet. Similar to how you can add/manage sdn with kubelet today. From an operator/user standpoint, this would be really ideal, as it would be very simple to use, and doesn't require more hardware then necessary to complete the job.

**Comment by warmchang** [comment]
nice job! :+1:

**Comment by DevasiaThomas** [comment]
Hi, does Kubernetes still support only one container runtime per node. It's been 2 years and I wanted to know if this has changed/ is planning to change. I'm all for the one runtime per node design - but just wanted to know if I have to prepare for it.

**Comment by fabiand** [comment]
It does support multiple by now:
https://kubernetes.io/docs/concepts/containers/runtime-class/

>

**Comment by DevasiaThomas** [comment]
@fabiand looking at the doc, it seems that the runtime that kubelet points to is the one responsible for dealing with additional handlers. So kubelet still deals with only one kind of runtime from its perspective - am I right?
