### ISSUE TITLE
Adopt convention for declaring that a type satisfies an interface

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#2992]
One thing that a few people have mentioned is that it's not easy to find all types that satisfy an interface. We should consider adopting a convention for specifying that.

The [Go FAQ](https://golang.org/doc/faq#implements_interface) proposes the following:

```
var _ I = T{}   // Verify that T implements I.
```

**Comment by dchen1107** [comment]
We also need to define another convention for interface to prevent comparing a interface to nil when only value of that interface is nil: I have a sample code describing this issue at: 

https://play.golang.org/p/dLyIAbOmLj

We ran into this kind of issue (#3356), and if we add more plugins, and define more interfaces for our ecosystem, we might run into much more. 

Maybe requires whenever a nil returns, an error has to be returned too? So only error can be checked to nil, no other type?

**Comment by erictune** [comment]
Lots of comments about things implementing interfaces
```
grep -i implements -R pkg | wc -l
     141
```
I'm guessing most of those don't implement the convention.

**Comment by thockin** [comment]
I use this convention when approrpriate, and it helps me feel more
confident about code.

**Comment by dchen1107** [comment]
@lavalamp @brendandburns @erictune See my comments about what we just talked offline.

**Comment by lavalamp** [comment]
```go
type testInterface interface {
	Error() string
}
type test string

func (this *test) Error() string { return "This is a issue: " + *this }

func test() testInterface {
	var p *test = nil 
	return p
}
```

In this sample, ```return p``` is a basic go use error. Reviewers need to watch out for it. **Return nil interfaces, NOT interfaces containing nil pointers.** (there are exceptions if you know what you're doing, but they're rare.)

**Comment by kargakis** [comment]
Discussion about Go conventions can be found in https://github.com/kubernetes/kubernetes/issues/28322.
