### ISSUE TITLE
Add CreatedBy annotation to ReplicaSets created by a Deployment

### ISSUE THREAD

**Issue by girishkalele** [kubernetes/kubernetes#29922]
Request addition of a CreatedBy annotation to a ReplicaSet created by a Deployment.
This will allow tracing the ownership path from a pod to parent ReplicaSet to its parent Deployment.

**Comment by lavalamp** [comment]
@girishkalele We're adding a controllerRef tag. Please don't implement this by adding an annotation.

**Comment by lavalamp** [comment]
@girishkalele come chat with me, @gmarek or @caesarxuchao for more detail!

**Comment by girishkalele** [comment]
We changed the design of the nanny to not attempt discovery of its own controller so this functionality is not required.

Either way, adding the controllerRef tag is a good thing.
