### ISSUE TITLE
Federation: hack/update-codegen.sh fails to generate import_known_versions.go, namespace_expansion.go, fake_namespace_expansion.go

### ISSUE THREAD

**Issue by kshafiee** [kubernetes/kubernetes#29937]
Federation: hack/update-codegen.sh fails to generate 
- import_known_versions.go
- namespace_expansion.go
- fake_namespace_expansion.go

**Comment by kshafiee** [comment]
cc @nikhiljindal

**Comment by nikhiljindal** [comment]
Yes those files are not autogenerated.

Running hack/update-codegen.sh should leave those files as is. You mentioned that it deletes those files?

**Comment by kshafiee** [comment]
yes, they are not autogenerated, even though they are under /clientset_generated/ directory. So, when you delete the directory and it gets regenerated, it is missing those files

**Comment by nikhiljindal** [comment]
Any particular reason why you deleted that directory?

cc @caesarxuchao

**Comment by caesarxuchao** [comment]
@kshafiee Sorry, these expansion files have caused a lot of confusion. I planned to centralize them in a folder in the client-gen directory, and copy them out every time the tool is run, but I cannot promise quick progress on this.

**Comment by kshafiee** [comment]
@caesarxuchao @nikhiljindal 
I remember there was build errors due to duplicate declaration after I added "api/Secret" to hack/update-codegen.sh, which is why I deleted the directory (I was expecting everything to be re-generated, as the name of the directory implies). However, I could not duplicate the error.

I suggest that we change the name of the directory to clarify that not every file will be re-generated by deleting and re-running hack/update-codegen.sh

**Comment by nikhiljindal** [comment]
Yes agreed that it is confusing.
As @caesarxuchao says we want to fix it, just havent been able to get to it.

@kshafiee feel free to fix it if you want.
