### ISSUE TITLE
controllers should use versioned clientset instead of internal clientset

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#29934]
Sub task of https://github.com/kubernetes/kubernetes/issues/27667
- This avoids unnecessary conversion of API objects from internal to a different version.
- Controllers become immune to API changes in internal version.

@caesarxuchao has been working on some of this.
cc @kubernetes/sig-api-machinery

**Comment by nikhiljindal** [comment]
Newly written federation controllers (such as the [federation service controller](https://github.com/kubernetes/kubernetes/blob/cadee4675325366c1a3195a8950442c089003b30/federation/pkg/federation-controller/service/servicecontroller.go)) are now using the versioned clientset instead of the internal one.

**Comment by caesarxuchao** [comment]
Before let controllers use versioned client, we need to convert our client utility functions (like pkg/client/record) to versioned. This is done in #29147.

**Comment by caesarxuchao** [comment]
We will let the controllers to use the clientset in client-go. But first we need to write the verify/update scripts so that client-go will be kept up-to-date. I'm writing the scripts now.

**Comment by kargakis** [comment]
cc: @mfojtik

**Comment by caesarxuchao** [comment]
Fixed by #36673.
