### ISSUE TITLE
Enabling 'cgroup-per-qos' flag in Kubelet

### ISSUE THREAD

**Issue by dubstack** [kubernetes/kubernetes#29946]
For reference: For work in #27204 which is introducing pod level cgroups into Kubernetes. As a part of which we create cgroups for each pod and each of the pod's containers are brought under its pod cgroup. 

This issue is to discuss on how we want the user to enable this feature. And should we support rollbacks?

@vishh suggested that we would like the user to just restart the kubelet with the cgroup-per-qos flag enabled to use this feature.

To support it we need to ensure that : 
1. When the kubelet is restarted with the cgroup-per-qos flag, all the running containers should be killed intermittently and brought back up under the cgroup qos hierarchy. (Note: 
We also log the appropriate message reason of killing the pod/containers.)
2. But when the pod is brought up for the first time with the flag enabled it should be directly brought up under the cgroup qos hierarchy.
3. Pods having RestartPolicy: Never are not restarted once they have been intermittently killed.
This was decided upon discussions with @yujuhong and @vishh. 

Once we finalize the logic here I would be adding this note to the [proposal](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/pod-resource-management.md).

@derekwaynecarr @Random-Liu @vishh PTAL.

cc @kubernetes/sig-node

**Comment by euank** [comment]
I personally think that the job of doing a "rolling update" of pods (effectively what's proposed here) should and already does live a level higher. I'd much prefer a way to mark these pods as "in need of update/restart", and then provide a tool that, at a cluster level, can institute such a rolling restart.

Is here a reason to not directly move pods into the cgroup without a kill/restart? I can imagine that would be hairy to do correctly and I haven't thought about it, but if you have the reasons against it would be good to lay out here as well.

**Comment by vishh** [comment]
The recommendation is for users to drain a node, and restart it, before enabling pod level cgroups. This feature is just a fallback, to ensure that kubelet continues to function in a deterministic manner.

It is not possible to move cgroups to new hierarchies. All the containers will have to be restarted.

Given that this is just a fallback feature, I'd prefer keeping it simple. If we decide to fail all pods that's fine by me, but I feel that it is not necessary since a simple restart with relevant restart reason should work for most pods.

**Comment by vishh** [comment]
@dubstack It is imperative that the recommendation to drain the node prior to enabling pod level qos is mentioned in the proposal clearly!

**Comment by euank** [comment]
@vishh can't you create the new hierarchy and write the Pid associated with each container to `${cgroupPath}/tasks`?

Regardless so long as the recommendation is clear then I have fewer concerns.
