### ISSUE TITLE
Deleting long-lived deployments can be very slow

### ISSUE THREAD

**Issue by ekuefler** [kubernetes/kubernetes#29941]
I have a continuous integration system that updates the image used in a deployment potentially dozens of times per day, and has been running for a couple of weeks. When I tried to delete this deployment today, `kubectl delete` seemed to hang for >10 minutes. Re-running with `-v=999`, I see that `kubectl` is sending multiple GET, PUT, and DELETE requests for every replicaset that has ever been created by the deployment.

Would it be possible to batch this operation in some way or, barring that, to show some indication of progress during `kubectl delete`?

**Comment by ravilr** [comment]
Also consider setting a saner value for revisionHistoryLimit of deployment object:
http://kubernetes.io/docs/user-guide/deployments/#revision-history-limit

Also see, https://github.com/kubernetes/kubernetes/issues/23597

**Comment by ekuefler** [comment]
Thanks, that setting definitely helps (though is just a workaround for the underlying issue). I agree with #23597 that having a limit seems like a more reasonable default.

**Comment by pwittrock** [comment]
Closing as a dup.
