### ISSUE TITLE
--v flag doesn't seem to do anything

### ISSUE THREAD

**Issue by zllovesuki** [kubernetes/kubernetes#29955]
`Disclaimer: I'm very new to the Kubernetes project, even newer to Go lang in general.`

Since Kubernetes is using `glog` from `github.com/golang/glog`, then supposedly passing `--v=0` should reduce the verbosity of the log produces by `apiserver`, `controller-manager`, and `scheduler` (I'm using hyperkube from Quay.io on CoreOS).

Is there a way to reduce the `Info` level logging?

**Comment by bprashanth** [comment]
I believe setting --v=0 should elide Infof as well, because its equivalent to log level 2

**Comment by soltysh** [comment]
I've just tested this against latest master passing `--v=8` used to print all the requests send over to server, currently nothing is being printed, which is painful when debugging anything.

**Comment by soltysh** [comment]
Previous comment does not apply. It's a different issue fixed in #30440.

**Comment by soltysh** [comment]
I'm using this flag frequently and it's working as expected printing usable logs.
/close
