### ISSUE TITLE
Concurrent RS labels map read map write in deployment controller

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#29960]
`equalIgnoreHash` may produce `fatal error: concurrent map read and map write` because the labels maps are read and write concurrently. Will fix this with the following steps:

1. Compare the labels too see if they're equal (ignore hash label)
2. Then set the template labels to `nil` and do a deep equal 

@kubernetes/deployment @lavalamp

**Comment by lavalamp** [comment]
This is triggered by deployments with overlapping label selectors, which are going to cause problems elsewhere, too. But at least we shouldn't crash.

**Comment by alex-mohr** [comment]
Still need to create a cherrypick for https://github.com/kubernetes/kubernetes/pull/30011 ?

**Comment by janetkuo** [comment]
Yes, created #30297

**Comment by janetkuo** [comment]
Now fixed
