### ISSUE TITLE
Running SkyDNS behind a kubernetes service - possible issue with service iptables rules

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/kubernetes#2996]
I have created a replication controller & service for SkyDNS on kubernetes. Accessing SkyDNS via the pod IP works perfectly, but when you try to access SkyDNS via the service IP you get the following response:

    ;; reply from unexpected source: 192.168.0.11#47494, expected 172.121.17.137#53

In this case, 192.168.0.11 is the host's IP address, 172.121.17.137 is the service IP address.

Does this indicate a problem with the kubernetes service proxy or iptables rules not rewriting packets correctly?

This is a follow up to skynetservices/skydns#110.

**Comment by yuvipanda** [comment]
So I'm running into this now, again. It works fine from inside a pod, but not on the hosts themselves. 

    yuvipanda@k8s-webproxy-02:~$ dig  @192.168.0.100 trusty-php-9.default.svc.kube
    ;; reply from unexpected source: 192.168.46.0#47192, expected 192.168.0.100#53

Works if I force dig to use TCP - other TCP based protocols (HTTP) also work via service IPs.

This is on kubernetes v1.0.1

**Comment by yuvipanda** [comment]
Also unsure what the fix was - I can't find a 'dns' branch in @thockin's fork.

**Comment by yuvipanda** [comment]
192.168.46.0 is actually the ip of my local flannel interface.

**Comment by yuvipanda** [comment]
I wonder if I need --masquerade-all=true in kube-proxy.

**Comment by yanatan16** [comment]
I am encountering this as well on the _hosts_ only (10.0.0.10 is dns service ip):

```
root@kube-pool-01:~# dig @10.0.0.10 kubernetes.default.svc.cluster.local
;; reply from unexpected source: 10.5.144.0#52279, expected 10.0.0.10#53
;; reply from unexpected source: 10.5.144.0#52279, expected 10.0.0.10#53
;; reply from unexpected source: 10.5.144.0#52279, expected 10.0.0.10#53

; <<>> DiG 9.9.5-9ubuntu0.3-Ubuntu <<>> @10.0.0.10 kubernetes.default.svc.cluster.local
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
root@kube-pool-01:~# dig @10.0.0.10 +tcp kubernetes.default.svc.cluster.local

; <<>> DiG 9.9.5-9ubuntu0.3-Ubuntu <<>> @10.0.0.10 +tcp kubernetes.default.svc.cluster.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43472
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;kubernetes.default.svc.cluster.local. IN A

;; ANSWER SECTION:
kubernetes.default.svc.cluster.local. 30 IN A	10.0.0.1

;; Query time: 1 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Fri Sep 11 22:36:21 UTC 2015
;; MSG SIZE  rcvd: 70
```

**Comment by thockin** [comment]
Jon - also with flannel?

**Comment by thockin-cc** [comment]
both of you - can you run `iptables-save` and send me the full output?  I
can't repro this, even with flannel.

**Comment by yanatan16** [comment]
I actually have seen the problem get resolved. I am using flannel. I'm not _sure_ what fixed it, but I believe my docker arguments were messed up. I had `--iptables=false --ip-masq=$FLANNEL_IPMASQ --bip=$FLANNEL_SUBNET --mtu=$FLANNEL_MTU`. I removed `--iptables=false` to fix some routing issues and now this issue as gone away as well.

**Comment by thockin** [comment]
If you turn off that docker flag, docker will do some iptables rules that
you may or may not don't want (depends on your environment).

We have identified a bit of oddness when accessing kubernetes services from
the nodes, which the flannel folks have ACKed.

Basically, when crossing the native and overlay networks, we need to be
more explicit about bridging.  Hopefully a new flannel will get this soon.

**Comment by Zolmeister** [comment]
I ran into this as well (CoreOS cluster on DigitalOcean)
For me the issue was that I started Flannel with the wrong network range (`10.244.0.0/16`)


```
/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"10.244.0.0/16", "Backend": {"Type": "vxlan"}}'
```

but my api server was on `10.100.0/16`

```
--service-cluster-ip-range=10.100.0.0/16
#
--cluster_dns=10.100.0.10
#
clusterIP:  10.100.0.10
```
