### ISSUE TITLE
how to config apiserver with https

### ISSUE THREAD

**Issue by chowyu08** [kubernetes/kubernetes#29977]
Dashboard version: 1.1.0
Kubernetes version: 1.3.0
Operating system: ubuntu14.04
Go version: 1.6.2

kubernetes install
1. git clone https://github.com/kubernetes/kubernetes.git
cd kubernetes
make release
2. deploy it as 
http://kubernetes.io/docs/getting-started-guides/ubuntu/
KUBERNETES_PROVIDER=ubuntu ./kube-up.sh
3. deploy dashboard as 
KUBERNETES_PROVIDER=ubuntu ./deployAddons.sh

![image](https://cloud.githubusercontent.com/assets/16483518/17358322/dc0990c8-5993-11e6-9adc-d036904b9179.png)
when I access http://159.99.105.148:8080/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard is right ,but need not login; bus access  https://159.99.93.113/ui , return error “refused to connect.” ，does need I to config other?

**Comment by roberthbailey** [comment]
Support for ubuntu in kube-up was removed in #44344 so I'm going to mark this as obsolete.
