### ISSUE TITLE
batch/v2alpha1 says it's enabled although it was never enabled

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#29998]
When running master server I didn't enable `batch/v2alpha1` anywhere explicitly, but if I do `kubectl api-versions` I'll get information that it's enabled, this came up when testing #25816. The problem is that by default the resources in `batch/v2alpha1` are not accessible unless you explicitly enable that group using `--runtime-config` option. 

@caesarxuchao any ideas?

**Comment by soltysh** [comment]
The other problem with that is that, for some reason `hack/update-swagger-spec.sh`, even though it has `batch/v2alpha1` specified in it, it won't generate proper swagger data for that group.

**Comment by caesarxuchao** [comment]
> The other problem with that is that, for some reason hack/update-swagger-spec.sh, even though it has batch/v2alpha1 specified in it, it won't generate proper swagger data for that group.

The swagger is generated by the api server, so you need to actually enable it in the api server to generate swagger for it.

**Comment by caesarxuchao** [comment]
When I visit `http://localhost:8080/apis/batch/v2alpha1` I get:
```
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "batch/v2alpha1",
  "resources": null
}
```

So it seems somehow the gorup/version get registered even though no resource registered. I don't have time to dig, but you should be able to trace it from here: https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/apiserver.go#L296. Good luck :)

**Comment by soltysh** [comment]
> So it seems somehow the gorup/version get registered even though no resource registered. I don't have time to dig, but you should be able to trace it from here: https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/apiserver.go#L296. 

Thanks for the pointer, will definitely dig there.

> Good luck :)

That is always needed when adding new version :wink:

**Comment by krousey** [comment]
Is there any update on this?

**Comment by soltysh** [comment]
It's on my radar, but haven't got a chance to look into it, @krousey how important is that for you?

**Comment by krousey** [comment]
Soon I want to right a test that queries discovery info to make sure only certain APIs are running. If they can show up regardless of being disabled by apiserver flags/env, then that test would not work. So for now, p2? Maybe p1 later.

**Comment by soltysh** [comment]
I'll try to tackle it next week, in that case.
