### ISSUE TITLE
The kubedns templates need to have a variable for architecture.

### ISSUE THREAD

**Issue by mbruzek** [kubernetes/kubernetes#30017]
The file named `skydns-rc.yaml.base` has hard coded "amd64" on the architecture for the dns containers. It appears the release process builds the containers for other architectures (ppc64le, and arm). These base templates are therefore not flexible and incorrect when running on systems other than amd64 architecture.

I propose we add an "__ARCHITECTURE__" string to the dns ReplicationController definition and add architecture as an variable that can be replaced in the templates and transforms.

**Comment by luxas** [comment]
cc @luxas 

Right now we're `sed`-ing `-amd64` with `-${GOARCH}` when processing the templates, for example in the hyperkube image
