### ISSUE TITLE
use shared caches and listwatchers where possible

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#30016]
We now have an easy interface to get access to a `SharedIndexInformer` that already has the common types available and more can be added: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/framework/informers/factory.go#L34 .  You can see examples of use here https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L250, here https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L291, and here https://github.com/kubernetes/kubernetes/pull/29978/files#diff-2aa9cfe6a01016c1679752b0fcfc9244R198.

Now we should start integrating the shared caches for other types.  This issue keeps a checklist of the major types in both admission plugins and controllers.

Controllers
- [ ] Namespaces
- [X] Pods
- [X] PVCs
- [x] PVs

Admission Plugins
- [x] NamespaceLifecycle https://github.com/kubernetes/kubernetes/pull/29926

@kubernetes/rh-cluster-infra @hodovska can you help prime the initial list?
### These informers are already implemented and are not used in following controllers yet

**NodeInformer**
- [x] NodeController https://github.com/kubernetes/kubernetes/commit/0961784a9b157b3ec3da3a1dcb1b4779214e41e4
- [x] DaemonController https://github.com/kubernetes/kubernetes/commit/0961784a9b157b3ec3da3a1dcb1b4779214e41e4

**NamespaceInformer**
- [ ] NamespaceController
- [ ] ServiceAccountsController

### Informers which could be implemented and used in controllers:
- **DaemonSetInformer**
  - [x] DaemonSetsController https://github.com/kubernetes/kubernetes/commit/234d68be8382a53be6fdb17c1137ae5450187518
  - [x] NodeController https://github.com/kubernetes/kubernetes/commit/0961784a9b157b3ec3da3a1dcb1b4779214e41e4
- **ReplicaSetinformer**
  - [x] ReplicaSetController https://github.com/kubernetes/kubernetes/commit/b471398f1f0d5908fee6dbdac06ebbeeefa34faf
  - [x] DeploymentController https://github.com/kubernetes/kubernetes/commit/aa5cbb704f21efcd028873839daaed2d4e386b81
- **SecretInformer**
  - [ ] ReplenishmentController
  - [ ] TokensController
- **ServiceInformer**
  - [ ] EndpointsController
  - [ ] ReplenishmentController
- **ServiceAccountInformer**
  - [x] ServiceAccountsController https://github.com/kubernetes/kubernetes/commit/df4ed892c447b471754e3e8e2a6497be9815768b
  - [ ] TokensController
- **ReplicationControllerInformer**
  - [ ] ReplenishmentController
  - [x] ReplicationManager https://github.com/kubernetes/kubernetes/pull/39355/commits/e5b586b5b046f60d9607c549dc9d49a776590efa

**Comment by hodovska** [comment]
Current usage of SharedIndexInformers in controllers and admission plugins:

**Controllers:** https://github.com/kubernetes/kubernetes/pull/29978/commits/305342c48d7300a599ad008727d822e6664bdacd
- PodInformer
  - DaemonSetsController
  - EnpointController
  - JobController
  - NodeController
  - ReplenishmentController
  - ReplicaSetController
  - ReplicationManager
  - AttachDetachController
  - PetSetController
- NodeInformer
  - AttachDetachController
- PVInformer
  - AttachDetachController
- PVCInformer
  - AttachDetachController

**Admission Plugins:**
- NamespaceInformer
  - NamespaceLifecycle https://github.com/kubernetes/kubernetes/pull/29926
  - NamespaceAutoProvision https://github.com/kubernetes/kubernetes/pull/29634
  - NamespaceExists https://github.com/kubernetes/kubernetes/pull/29634

**Comment by hodovska** [comment]
These informers are already implemented and are not used in following controllers yet
**NodeInformer**
  - [ ] NodeController
  - [ ] DaemonController

**NamespaceInformer**
  - [ ] NamespaceController
  - [ ] ServiceAccountsController

**PodInformer**
  - [ ] DeploymentController

**Comment by hodovska** [comment]
Informers which could be implemented and used in controllers:
- [ ] **DaemonSetInformer**
  - DaemonSetsController
  - NodeController

- [ ] **ReplicaSetinformer**
  - ReplicaSetController
  - DeploymentController

- [ ] **SecretInformer**
  - ReplenishmentController
  - TokensController

- [ ] **ServiceInformer**
  - EndpointsController
  - ReplenishmentController

- [ ] **ServiceAccountInformer**
  - ServiceAccountsController
  - TokensController

- [ ] **ReplicationControllerInformer**
  - ReplenishmentController
  - ReplicationManager

**Comment by deads2k** [comment]
Thanks @hodovska, that will help a bunch.

**Comment by kargakis** [comment]
@hodovska can you update the list in the first post with what's missing here?

**Comment by hodovska** [comment]
@kargakis I updated posts with information I could find about @deads2k's  contributions.

Also new informers for following resources were implemented:
LimitRanges
InternalLimitRanges
InternalNamespaces
Deployments
ClusterRoleBinding
ClusterRole
RoleBinding
Role
StorageClass
Job

**Comment by kargakis** [comment]
@deads2k good enough?

**Comment by deads2k** [comment]
> @deads2k good enough?

Yes
