### ISSUE TITLE
kubectl set-context optional name suggestion

### ISSUE THREAD

**Issue by moander** [kubernetes/kubernetes#30019]
Common tasks like default namespace swapping is not straight forward using kubectl. 

If NAME was optional one could change the current context like this:
```
kubectl config set-context --namespace whatever 
```

The current docs suggest this procedure to change the default namespace:

```
$ export CONTEXT=$(kubectl config view | awk '/current-context/ {print $2}')

$ kubectl config set-context $CONTEXT --namespace=<insert-namespace-name-here>
# Validate it
$ kubectl config view | grep namespace:
```

**Comment by pwittrock** [comment]
@moander Would you add this to #29794
