### ISSUE TITLE
Allow sharing RDB volumes as read-only 

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#30027]
The rdb docs state: 
```
A feature of RBD is that it can be mounted as read-only by multiple consumers 
simultaneously. This means that you can pre-populate a volume with your dataset 
and then serve it in parallel from as many pods as you need. Unfortunately, RBD 
volumes can only be mounted by a single consumer in read-write mode - no 
simultaneous writers allowed. 
```

But it looks like we disallow this in the scheduler: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L121

This would be consistent with how we handle gce volumes, is there a technical limitation why this isnt possible? or did we just misunderstand what's allowed (please clarify docs if this is the case)?

I'd try this myself and comment with more logical suggestions, but setting up a ceph cluster seems like more of a hassle than I have time for right now. 

@kubernetes/sig-storage

**Comment by ravilr** [comment]
https://github.com/kubernetes/kubernetes/pull/29622

**Comment by bprashanth** [comment]
closed as dupe of https://github.com/kubernetes/kubernetes/issues/27725

**Comment by rootfs** [comment]
@bprashanth do you mind reviewing and tagging #29622 ?
