### ISSUE TITLE
Deployment controller shouldn't hot-loop-fail on overlapping deployment selectors

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#30028]
If you make two deployments with overlapping label selectors, such that they will find each other's replica sets, deployment controller's math stops working correctly and it spews messages like `Error syncing deployment default/xxxxxxxxx: Deployment.extensions "xxxxxxxxx" is invalid: status.unavailableReplicas: Invalid value: -20: must be greater than or equal to 0"` many times per second.

This situation is user error, but deployment controller should fail more gracefully.

**Comment by janetkuo** [comment]
@kubernetes/deployment

**Comment by janetkuo** [comment]
To clarify the problem - When there are two deployments with overlapping label selectors, both deployments can see all pods (d1 can see p1 and p2) and all replica sets (d1 can see rs1 and rs2), but each deployment's replica set can only see the pods the replica set created (rs1 can only see p1, but not p2), and that messed everything up.

**Comment by AdoHe** [comment]
```
This situation is user error, but deployment controller should fail more gracefully.
```
is it possible to avoid overlapping label selectors?

**Comment by janetkuo** [comment]
[Controller ref](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/controller-ref.md) would solve this problem, but it's not implemented yet.

**Comment by janetkuo** [comment]
> is it possible to avoid overlapping label selectors?

An temp fix would be adding a check at creation time (check for existing overlapped controllers). It won't be 100% accurate (things can be created after list), but it can mitigate most use cases.

**Comment by jeremywadsack** [comment]
Would it be possible to have the replication controller identify that it's starting/terminating due to overlapping labels, note that in the events, and not loop on that? It would be helpful to leave the terminated Pod around long enough to get the event to know why it failed.

**Comment by janetkuo** [comment]
#30730 will prevent newer overlapping deployments from taking action
