### ISSUE TITLE
Document what docker image (Dockerfile) features we support

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#30039]
For example, we don't support HEALTHCHECK.

We support STOPSIGNAL when using docker daemon (#30051).

/cc @thockin @kubernetes/sig-node

**Comment by thockin** [comment]
I was thinking more about healthcheck.  Especially in a CRI world, could we
make "healthiness" be a responsibility of the plugin?  Then this could work
(as awkward as it is).  Anyway, just an idea.

**Comment by yujuhong** [comment]
> Especially in a CRI world, could we
> make "healthiness" be a responsibility of the plugin?

To support this, we don't necessarily have to push healthcheck down to the runtime. We could augment the container status in CRI by adding  an "unhealthy" state, and let kubelet decides whether to kill/restart the container. kubelet can still perform the liveness/healthness checks kubernetes API.

What I really don't like is that nothing in our pod spec reflects the fact that there are health checks hidden in the image already...

**Comment by thockin** [comment]
On Thu, Aug 4, 2016 at 10:25 AM, Yu-Ju Hong <notifications@github.com> wrote:
>
> Especially in a CRI world, could we
> make "healthiness" be a responsibility of the plugin?
>
> To support this, we don't necessarily have to push healthcheck down to the runtime. We could augment the container status in CRI by adding an "unhealthy" state, and let kubelet decides whether to kill/restart the container. kubelet can still perform the liveness/healthness checks kubernetes API.
>
> What I really don't like is that nothing in our pod spec reflects the fact that there are health checks hidden in the image already...

ACK.  But I think that's less bad than not supporting it at all.  I
think.  I haven't estimated the work, and it's certainly not URGENT
yet. :)

**Comment by yujuhong** [comment]
Sure, and we don't support docker v1.12 (yet). 

Another concern is whether other runtimes which supports docker images will also perform the health checks. If not, the behavior will be completely runtime-dependent, and even more confusing for the users.

**Comment by thockin** [comment]
yeah, many issues to resolve here.

**Comment by pondohva** [comment]
@yujuhong could you please refer to issues related with 1.12 support? I haven't met problem with 1.12 yet on test environment.

**Comment by yujuhong** [comment]
@pondohva my comments above was outdated. Kubernetes 1.4 is compatible with docker 1.12, so it should be fine for you to use it. See the [1.4 release note](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#action-required-before-upgrading) for more information. That said, kubernetes doesn't support *al* features in Dockerfile*, and many of those already existed in the kubernetes API (e.g., health checks).

The recommended docker version (i.e., the version we tested most thoroughly in the GCE+containerVM/GCI environment) for kubernetes 1.4 is docker 1.11.2.

**Comment by yujuhong** [comment]
Let's see if we can take on this in v1.7. 

/cc @Random-Liu, this information would be good to have for containerd integration as well.

**Comment by yujuhong** [comment]
Marking it 1.10 tentatively since this would be good for non-docker CRI runtimes.

**Comment by jberkus** [comment]
If this is going into 1.10, can you please add a priority/ to it?  Thanks!

**Comment by jberkus** [comment]
Has there been any work on this issue?  Do you expect to get it done in the next 5 days for 1.10?

**Comment by yujuhong** [comment]
https://docs.docker.com/engine/reference/builder

| Instruction  | Description | Supported | Comment |
| ------------- | ------------- | ------------ | ------------- |
| ENTRYPOINT  | Executable to run  | Y | Supported by the runtime(s) |
| CMD  | Arguments to supply to the ENTRYPOINT  | Y | Supported by the runtime(s) |
| EXPOSE | Ports that container intends to listen for informative purpose only | N/A | Does not have actual effect |
| VOLUME | Mount points for volumes from host or other containers | Y and N | Supported only by the Docker daemon; no proper resource accounting and is not exposed in the Kubernetes API |
| USER | User name (or UID) and optionally the user group (or GID) to use | Y | Supported (and partially checked) by Kubelet |
| WORKDIR | Working directory | Y | Supported by the runtime(s) |
| STOPSIGNAL | System call signal to send | Y | Supported by the runtime(s) |
| HEALTHCHECK | Container health checks | N | Explicitly disabled |
| SHELL | Shell to use for ENTRYPOINT | Y? | Supported by the runtime(s) |

Image building instructions that are not relevant in this context:  FROM, ADD, COPY, MAINTAINER, LABEL, ARG, ONBUILD

**Comment by Random-Liu** [comment]
@yujuhong WE don't support GID now. We should add the support.

**Comment by dims** [comment]
long-term-issue (note to self)
