### ISSUE TITLE
Pod not starting while using kubelet with Manifests files and apiserver.

### ISSUE THREAD

**Issue by doniwan** [kubernetes/kubernetes#30048]
I use kubelet to start everything, including etcd, apiserver, controller manager, user pods, etc..

While startting apiserver, nodeInfo of  kubelet will be changed  from standalone mode to nodeinfo from apiserver. Then nodeinfo will become empty for a while ( I regist node manually ). If I add manifiles at this time, pod whill not start because of Podcount limit. and it will not be started forever!

Temporarily, I change predicates.go to  skip PodCount check for this matter.

Is there any other good method to solve issue please?  thank you very much

**Comment by dchen1107** [comment]
Have you tried to config Kubelet with --max-pods to override the default value for AllowedPodCount?

**Comment by doniwan** [comment]
@dchen1107  Thanks for your reply.
I default value of --max-pods is 110.  I have not try this, and I think it is not the problem. 110 is enough~

**Comment by pradeeppandeyy** [comment]
kubelet is not starting pod for manifest , Kindly provide configuration for the same. I am using below service  file with kubernetes version-1.4.7

**[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=docker.service
Requires=docker.service

[Service]
ExecStart=/usr/bin/kubelet   --allow-privileged=true   --api-servers=https://10.25.0.20:6443,https://10.25.0.21:6443   --cloud-provider=   --cluster-dns=10.32.0.10  --config=/etc/kubernetes/manifests  --cluster-domain=cluster.local   --configure-cbr0=true   --container-runtime=docker   --docker=unix:///var/run/docker.sock   --network-plugin=kubenet   --kubeconfig=/var/lib/kubelet/kubeconfig   --reconcile-cidr=true   --serialize-image-pulls=false   --tls-cert-file=/var/lib/kubernetes/kubernetes.pem   --tls-private-key-file=/var/lib/kubernetes/kubernetes-key.pem   --v=2

Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target**

**Comment by pradeeppandeyy** [comment]
This issue is now not persistence for me. Thanks
