### ISSUE TITLE
Hanging in postStart hook can cause pod to get stuck in ContainerCreating state with no logs/event info

### ISSUE THREAD

**Issue by boydgreenfield** [kubernetes/kubernetes#30042]
We're continuing to observe 5-10% failure rates in creating pods, with them hanging in `ContainerCreating` state. These are 2-container pods with an `postStart` lifecycle hook, but I don't believe that's implicated here (no problems in the `kubelet.log`). One other detail here is that pods stuck in `ContainerCreating` do not appear to respond to a default `delete` command (but do terminate with the `--now` flag or otherwise specifying a 0 second timeout).

We've run into this issue across various 1.3.x versions, including 1.3.4. 

The only observable issue in `kubelet.log` (this taken from an install using `kube-aws` and k8s `1.3.4`) is repeated remounting of the secrets volume (on I believe the DNS pod):

```
Aug 04 00:26:43 ip-172-20-0-7.ec2.internal kubelet-wrapper[1469]: I0804 00:26:43.157398    1469 reconciler.go:254] MountVolume operation started for volume "kubernetes.io/secret/dc220eac-59d4-11e6-823f-12cddf49f625-default-token-0bpst" (spec.Name: "default-token-0bpst") to pod "dc220eac-59d4-11e6-823f-12cddf49f625" (UID: "dc220eac-59d4-11e6-823f-12cddf49f625"). Volume is already mounted to pod, but remount was requested.
Aug 04 00:26:43 ip-172-20-0-7.ec2.internal kubelet-wrapper[1469]: I0804 00:26:43.159847    1469 operation_executor.go:740] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/dc220eac-59d4-11e6-823f-12cddf49f625-default-token-0bpst" (spec.Name: "default-token-0bpst") pod "dc220eac-59d4-11e6-823f-12cddf49f625" (UID: "dc220eac-59d4-11e6-823f-12cddf49f625").
Aug 04 00:27:11 ip-172-20-0-7.ec2.internal kubelet-wrapper[1469]: I0804 00:27:11.218422    1469 reconciler.go:254] MountVolume operation started for volume "kubernetes.io/secret/dc2248b4-59d4-11e6-823f-12cddf49f625-default-token-0bpst" (spec.Name: "default-token-0bpst") to pod "dc2248b4-59d4-11e6-823f-12cddf49f625" (UID: "dc2248b4-59d4-11e6-823f-12cddf49f625"). Volume is already mounted to pod, but remount was requested.
Aug 04 00:27:11 ip-172-20-0-7.ec2.internal kubelet-wrapper[1469]: I0804 00:27:11.221004    1469 operation_executor.go:740] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/dc2248b4-59d4-11e6-823f-12cddf49f625-default-token-0bpst" (spec.Name: "default-token-0bpst") pod "dc2248b4-59d4-11e6-823f-12cddf49f625" (UID: "dc2248b4-59d4-11e6-823f-12cddf49f625").
```

Any suggestions for further debugging here? This is likely related to https://github.com/kubernetes/kubernetes/issues/29059 and the other referenced issues there.

For our use case (spinning up containers on demand for users), this is quite a nasty bug because it occasionally fails to spin up a container in a reasonable timeframe and also requires using a hard kill.

**Comment by boydgreenfield** [comment]
On further investigating this issue, it _does_ appear that our containers are hanging due to the `postStart` lifecycle hook as of `1.3.4` (though on prior 1.3.x versions we had this problem w/o `postStart` hooks).

Investigating (1) how to make our `postStart` hook more robust; and (2) where to find logging information for it...

**Comment by thomastaylor312** [comment]
+1 to this. It is very hard to debug issues with `postStart` hooks due to the lack of logging/output

**Comment by boydgreenfield** [comment]
Quick update: Our issue was caused by a (sporadic) race condition in two `postStart` hooks and we've fixed it by using an `initContainer` instead. _But_ as @thomastaylor312 says, this can be incredibly difficult to debug due to the lack of logging here.

**Comment by thomastaylor312** [comment]
@boydgreenfield: Is there another issue tracking the need for logs that you know of? Supposedly, [there is logging](https://github.com/kubernetes/kubernetes/pull/25681), but I have never seen it. The only thing that I have seen is the `FailedPostStartHook` event

**Comment by bitbyteshort** [comment]
### Issue

Reproduced the issue on v1.5.4. *A pod cannot be deleted if its postStart hook contains an infinity loop.*

### Pod Spec
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: post-start
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: post-start
    spec:
      terminationGracePeriodSeconds: 60
      restartPolicy: Always
      containers:
      - name: post-start
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        command:
        - /bin/sh
        - -c
        - while  [ ! -f /root/t.log ]; do sleep 1; done
        lifecycle:
          postStart:
            exec:
              # ===================
              # postStart is an infinite loop
              # ===================
              command:
              - /bin/sh
              - -c
              - while true; do sleep 1; done
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - touch /root/t.log
```

### Observation
* The pod stuck in "ContainerCreating" state for ever.
* Pod can not be deleted with "kubectl delete" command
* But the deployment object and replica set object can be deleted

### Version

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by xiangpengzhao** [comment]
@yujuhong @dchen1107 ?

**Comment by yujuhong** [comment]
I don't think we set the timeout for the exec calls either in the old dockertools or the new CRI integration (for v1.6+).
I think it's reasonable to set some timeout to prevent cases like this.

/cc @timstclair, who has several TODOs left to set the timeout in the new integration.

**Comment by xiangpengzhao** [comment]
ref: #46321

@PengTaoWW

**Comment by PengTaoWW** [comment]
@xiangpengzhao @yujuhong in my code will not stuck,timeout after will kill container

**Comment by zhangzheming629** [comment]
so what's the solution？Should I change the apiversion？

**Comment by jcollie** [comment]
This still appears to be an issue on 1.23.5

**Comment by chenk008** [comment]
1.24  +1

**Comment by Tblue** [comment]
/reopen

This is a pretty nasty issue. I had to reboot the node the stuck pod was on (to make sure no resources linger on the node).

Maybe logging into the node and killing the `postStart` hook would also have helped, but I wasn't able to try that.
