### ISSUE TITLE
update Google Cloud API client import paths and more

### ISSUE THREAD

**Issue by jba** [kubernetes/kubernetes#30069]
The Google Cloud API client libraries for Go are making some breaking changes:

* The import paths are changing from `google.golang.org/cloud/...` to
  `cloud.google.com/go/...`. For example, if your code imports the BigQuery client
  it currently reads
```import "google.golang.org/cloud/bigquery"```
It should be changed to
```import "cloud.google.com/go/bigquery"```

* Client options are also moving, from `google.golang.org/cloud` to
  `google.golang.org/api/option`. Two have also been renamed:
  - `WithBaseGRPC` is now `WithGRPCConn`
  - `WithBaseHTTP` is now `WithHTTPClient`

* The `cloud.WithContext` and `cloud.NewContext` methods are gone, as are the
deprecated pubsub and container functions that required them. Use the `Client`
methods of these packages instead.

You should make these changes before September 12, 2016, when the packages at
`google.golang.org/cloud` will go away.

**Comment by thockin** [comment]
One month is a really short warning.  We missed this in the release shuffle, and now we're dead in the water.

@pwittrock v1.4
@fabioy @timstclair  v1.3

I need a volunteer to fall on this today.

**Comment by dims** [comment]
@thockin I'll take this one

**Comment by dims** [comment]
oops looks like @piosz has the con

**Comment by piosz** [comment]
@dims go ahead, it's evening in my timezone. Please confirm that you are working on this.

**Comment by piosz** [comment]
cc @mikedanese @k8s-oncall

**Comment by piosz** [comment]
The package `google.golang.org/cloud` is available again.

**Comment by dims** [comment]
cool, gives us some time :) yes @piosz i'll take this

**Comment by piosz** [comment]
Thanks @dims!

**Comment by piosz** [comment]
It seems to be more complicated than I thought:
1. we need to fix https://github.com/google/cadvisor/issues/1410
2. we need to bump version of cadvisor in Kubernetes, because we include files which uses the old version of library `vendor/github.com/google/cadvisor/utils/cloudinfo/gce.go:24:    "google.golang.org/cloud/compute/metadata"`
3. we need to bump version of `golang.org/x/oauth2` because we are using older than https://github.com/golang/oauth2/commit/04e1573abc896e70388bd387a69753c378d46466
4. then we can finally update the version of the library in Kubernetes itself

@jba am I right?

cc @dchen1107 @timstclair regarding points 1. and 2.

**Comment by dims** [comment]
@piosz yep. that's exactly what i saw as well.

**Comment by dims** [comment]
for point 1, ref https://github.com/google/cadvisor/blob/cf548f1b70cd95321d5cde118e2c5b9f729423a7/utils/cloudinfo/gce.go#L24

**Comment by dims** [comment]
@timstclair indicated that he will up 1 and 2 from above https://github.com/google/cadvisor/pull/1454

**Comment by dims** [comment]
@mikedanese @timstclair @dchen1107 @saad-ali https://github.com/kubernetes/kubernetes/pull/32592 should be ready shortly as well (just rebased on Tim's PR)

**Comment by timstclair** [comment]
Do we need to cherrypick this for a v1.4 patch release (v1.4.1)? It shouldn't break our builds (that's why we vendor), but maybe it could cause some of our jenkins tests to fail? Are there any other problems that could arise?

/cc @dchen1107
