### ISSUE TITLE
Implementing better pods

### ISSUE THREAD

**Issue by ramitsurana** [kubernetes/kubernetes#30063]
Kubectl is a great tool.I was thinking if it might be possible to add more functionalities to the kubectl in such a manner that instead of creating just a pod.We could create a pod that automatically generates all the details and provides those details in response to the required services that needs it.Indirectly, making pods more smarter.Also I think it would lead to somewhat a new approach than orchestration,known as choreography.Any thoughts ?

**Comment by AdoHe** [comment]
@kubernetes/kubectl

**Comment by pwittrock** [comment]
Can you explain this a bit more and give an example?  I am not sure what you mean by 'generates all the details and provides those details in response to the required services that needs it'.

**Comment by smarterclayton** [comment]
This sounds like the use case for `podex` as well as `oc new-app` - take info from an image and build an app out of it?

**Comment by ramitsurana** [comment]
Thanks @smarterclayton for the information on podex. I think
