### ISSUE TITLE
Use protobufs by default in storage

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#30068]
We already have most of bits in place. The remaining things (mostly coming from Clayton) are:
- [ ] if someone enables base64 on etcd2, and then goes to etcd3; we ideally don't want to support base64 in etcd3; 
  But maybe we can simply say that if you are using base64, then you know hat you are doing and we don't support you? Thoughts?
- [ ] ensure that JSON-only objects (thirs party resources) are stored correctly (hopefully this will be only adding a test for it)
- [ ] migration

As for migration, we may potentially delegate it for the future, because since 1.3 release, apiserver can work with mixed storage (e.g. part of the objects can be JSON, the other part can be protobuf and it will work). That said, if you write a new version of an object (that already exists as json in storage), it will be overwritten to proto format

FYI - we already have a suite that is running tests with protobuf-based storage:
http://kubekins.dls.corp.google.com:8080/job/kubernetes-e2e-gce-proto/
[it's already running for few months].
And I didn't see any problems different that in regular suits. Which suggests that it works correctly.

@smarterclayton @lavalamp @kubernetes/sig-api-machinery @kubernetes/sig-scalability

**Comment by wojtek-t** [comment]
Regarding ThirdParty resources, we already have this test:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/third-party.go#L74

It is storing ThirdParty objects in etcd and it is running as part of the existing suite too. Which means that this test works correctly.

@smarterclayton @lavalamp - do you agree that this is enough, or you would like to test something more specific too?

**Comment by wojtek-t** [comment]
Maybe the way to go is:
- in 1.4 switch storage format to protobufs, but without migrating all the data
- do the actual migration a release after?

**Comment by smarterclayton** [comment]
In 1.4 do etcd3+protobuf for new clusters, etcd2+json for old clusters?

**Comment by lavalamp** [comment]
I'm nervous about supporting multiple storage backends, I think that means we need to double our testing.

**Comment by smarterclayton** [comment]
Technically we have to do that anyway though to move forward.  I'd rather
test 2 combinations than an ugly hybrid.  I think we've agreed that etcd
2->3 is an offline migration, so we have to test the offline migration, but
then we have to test old + new.  I'd like to only support the following
path:

etcd2 + json -> offline migration -> etcd3 + protobuf

That's a single "path" to test.

**Comment by lavalamp** [comment]
Yeah, I agree with that. We've got to figure out a way to test things that doesn't double the number of test jobs with every global feature. :(

**Comment by smarterclayton** [comment]
Note that this is "protobuf by default", not "all objects stored in etcd
are guaranteed to be protobuf, such as third party resources or objects
which may have no protobuf serialization (like the allocation ranges for
service ports, I think).

**Comment by wojtek-t** [comment]
I think that having 2 configurations (etcd2+json & etcd3+proto) is very good idea.

What I'm afraid of is that we won't get etcd3 in 1.4 release - there are ~2 weeks before code freeze, and we don't even have scripts to configure etcd3 in kube-up. Which makes me feel we won't be able to do that. And it would be great if we could launch proto-storage in 1.4 (at least in some limited scope, e.g. new clusters?)

**Comment by timothysc** [comment]
> I think that having 2 configurations (etcd2+json & etcd3+proto) is very good idea.

I'm slightly terrified by what could go wrong on a bad migration.  

/cc @kubernetes/sig-scalability

**Comment by smarterclayton** [comment]
A possible counter argument is that we have to test migration extensively
anyway - there being a single supported path reduces the probability of
P(migration gone bad) U P(conversion of JSON to protobuf gone bad).

On the other hand, the migration has to move the keys, but not necessarily
change them (the recognizing deserializer handles that for us), so
migration isn't that risky w.r.t. data change.

**Comment by wojtek-t** [comment]
@smarterclayton - are you sure that we we will be able to launch etcd3 (for new clusters) in 1.4 release?
It seems it might be difficult.

On the other hand, it seems that switching on protobufs is just a matter of testing (or am I missing something?). And the pure non-upgrade tests we have already setup of for few months. So assuming that we won't do migration (which we can do thanks to recognizing deserializer), that's only a matter of more extensive upgrade testing (which we will be doing anyway, also after code freeze).

Thoughs?

@lavalamp ^^

**Comment by timothysc** [comment]
@wojtek-t I should have https://github.com/kubernetes/kubernetes/pull/29399 ready today.  There will need to be follow on work, but we're committed and have been working with the CoreOS folks to get this thing working. 

/cc @xiang90 @hongchaodeng

**Comment by xiang90** [comment]
@timothysc @wojtek-t We'd love to help. Although we have work at hand, but making etcd3 as default backend would be our highest priority. So if there is any bugs/issues found during testing, we will fix them first.

**Comment by timothysc** [comment]
per discussion on @kubernetes/sig-scalability we're going to punt this out to 1.5.

**Comment by bgrant0607** [comment]
@wojtek-t can this be closed?

**Comment by wojtek-t** [comment]
We have enabled it by default in 1.6. So I guess we can close it.
