### ISSUE TITLE
rbac integration tests fail against batch/v2alpha1

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#30079]
When I've tried to enable the `batch/v2alpha1` api group in our integration tests I've noticed following failure:

```
rbac_test.go:453: case 1, req 8: job-writer GET jobs expected "200 OK" got "404 Not Found"
rbac_test.go:453: case 1, req 10: job-writer POST jobs expected "201 Created" got "404 Not Found"
rbac_test.go:453: case 1, req 11: job-writer GET jobs expected "200 OK" got "404 Not Found"
rbac_test.go:453: case 1, req 12: job-writer-namespace GET jobs expected "200 OK" got "404 Not Found"
rbac_test.go:453: case 1, req 14: job-writer-namespace POST jobs expected "201 Created" got "404 Not Found"
rbac_test.go:453: case 1, req 15: job-writer-namespace GET jobs expected "200 OK" got "404 Not Found"
```

I've looked into the rbac tests and it looks like it should work, iow. [this rule definition](https://github.com/kubernetes/kubernetes/blob/d6854cbb6b65421471ecda56e0f5e144a6cdb1c8/test/integration/auth/rbac_test.go#L273-L277) is written in such a way that it's not versioned in any way, but apparently it's not. 

I'm hoping to look into this one once all the main ScheduledJobs are ready.

/cc @erictune @janetkuo

**Comment by erictune** [comment]
@ericchiang does this look like a known issue?

**Comment by ericchiang** [comment]
No, but I'll investigate. Please assign this to me and I'll try to fix the test today.

**Comment by caesarxuchao** [comment]
@soltysh is this a test flake? I'm seeing it consistently in https://github.com/kubernetes/kubernetes/pull/30316.

**Comment by ericchiang** [comment]
@caesarxuchao these look like different issues. I'll look into the one in #30316

**Comment by caesarxuchao** [comment]
@ericchiang I found the problem in #30316, it's my mistake, I forget to add `\` at the end of a line in bash.

**Comment by ericchiang** [comment]
Oh, sorry yes this is the same issue. How was the enabling `batch/v2alpha1` merged without a fix for this issue?

**Comment by ericchiang** [comment]
Ah okay, thanks.

**Comment by caesarxuchao** [comment]
Our integration test doesn't enable `batch/v2alpha1`, https://github.com/kubernetes/kubernetes/blob/master/hack/make-rules/test-integration.sh#L30.

When I accidentally dropped `KUBE_TEST_API_VERSIONS`, the `batch/v2alpha1` might get enable by some default function.

**Comment by soltysh** [comment]
Fixing the integration to work with batch/v2alpha1 is on my list.

**Comment by liggitt** [comment]
@soltysh is this resolved?

**Comment by soltysh** [comment]
I need to get back to this and double check. With the amount of changes it might have been fixed, but I doubt it actually was :/

**Comment by soltysh** [comment]
@liggitt here's the current state. Our [testapi.go](https://github.com/kubernetes/kubernetes/blob/1e5fa8fed5459ab72175e4af84d128a34789a05e/pkg/api/testapi/testapi.go#L192) supports only testing single version for each group, the preferred one. This is also mentioned in [test-integration](https://github.com/kubernetes/kubernetes/blob/1e5fa8fed5459ab72175e4af84d128a34789a05e/hack/make-rules/test-integration.sh#L28-L29). 
Having said that, I hardcoded `batch/v2alpha1` in `testapi.go` and the test was successful. In that case maybe we can close this one and create one about supporting multiple versions in `testapi.go`, how's that?

**Comment by liggitt** [comment]
> maybe we can close this one and create one about supporting multiple versions in testapi.go, how's that?

yeah, seems more a testapi issue
