### ISSUE TITLE
Documentation not generated and packaged with release

### ISSUE THREAD

**Issue by adrianmkng** [kubernetes/kubernetes#30071]
The man pages don't contain any information in them from the release. I've tried generating them before doing a make release but because they are still tracked in git, the release artefact is marked as dirty.

**Comment by xiangpengzhao** [comment]
I'm not sure what kind of documentation/man pages you want and how you generate them. Could you please provide what script did you run? We will close this issue. Feel free to re-open it if you can provide more info about the issue. Thanks!

@thockin
