### ISSUE TITLE
Scale petset up/down testing

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#30082]
Scale up should happen in order
Scale down should happen in reverse order
Scaling should halt if there's an unhealthy pet
Scaling down before the scale up finished should wait for the _current_ pet to enter running, then immeidtely start scale down

**Comment by dshulyak** [comment]
Noticed that all pet sets are terminated immediately, i will see what can be done about that. Also when this will be ready we can scale down pods, before removing pet set. Because atm petset removal will leave tombstone after itself.

**Comment by bprashanth** [comment]
did you specify terminationGrace? if so, they should be terminated only after grace one by one. if you didn't it'll be pretty much immediate.

**Comment by dshulyak** [comment]
Thanks, you are right. So this issue is about writing additional e2e test cases. I will work on it

**Comment by dshulyak** [comment]
> Scaling down before the scale up finished should wait for the current pet to enter running, then immeidtely start scale down

This one looks tricky. Pet set controller should observe petset scale down update after pod will be created, but before it will enter running state. Do you have ideas how to implement it in deterministic way?
