### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubernetes#30098]
Could `kubectl` be ported for Windows hosts?

**Comment by alexbrand** [comment]
Hey @mcandre, you may download `kubectl` for Windows from https://storage.googleapis.com/kubernetes-release/release/v1.3.4/bin/windows/amd64/kubectl.exe

**Comment by raeesbhatti** [comment]
It would be better to have all of `kubectl` binaries listed on the releases page though.

**Comment by mcandre** [comment]
> It would be better to have all of kubectl binaries listed on the releases page though.

+100
