### ISSUE TITLE
Update scheduler config file compatibility test

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#30099]
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithmprovider/defaults/compatibility_test.go was added to make sure all the predicate/priority names continue working release-to-release, but the test is very out of date.

It needs to be updated with JSON blobs containing the supported predicates/priorities at the 1.1, 1.2, and 1.3 release levels.

**Comment by asalkeld** [comment]
I am working on this..
