### ISSUE TITLE
OS packages for kubectl

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubernetes#30097]
Please publish DEB and RPM packages for the `kubectl` binary, to make it easier to install for newbies.

**Comment by pwittrock** [comment]
@mcandre Is this something you know how to do or would willing to contribute?  We would also like to publish kubectl on homebrew?

**Comment by pwittrock** [comment]
subscribe @pwittrock

**Comment by pwittrock** [comment]
Please include detailed documentation for how to update the packages so that we can do so for each release

**Comment by k82cn** [comment]
Seems included in brew.

```
$ brew search kubectl
kubectl ✔
```

**Comment by mikedanese** [comment]
This is done.

https://apt.kubernetes.io
