### ISSUE TITLE
process instalbility observed when running inside a container laucnhed with daemonset 

### ISSUE THREAD

**Issue by sbezverk** [kubernetes/kubernetes#30106]
I noticed some issue when launching container using the daemonset. The same container launched with ReplicationController works 100% stable. The issue are mostly related to a process restart, some errors and inability to create a named socket. It is not a config issue as, as soon as I add strace in the command line of the process, it starts working fine. It seems some sort of a racing condition with daemoset. The issue is 100% reproducible, I am ready to offer access to the impacted test bed for further troubleshooting. Here is the error which is generated when container starts with DaemonSet:
[19202.800318] traps: ovsdb-server[24147] general protection ip:7fb18600be37 sp:7ffef3da0d00 error:0 in libc-2.17.so[7fb185fd5000+1b7000]
I am on Cenots 7.2, kubernetes 1.3.4-dirty (I needed this version for another issue which is fixed in this release). Please let me know if somebody would be interested to check it out.

**Comment by dchen1107** [comment]
@sbezverk If possible, could you please provide the following information:

1) Run your container through rc, then run command kubectl get -o yaml pods <pod-id>
2) Run your container as daemonset, then run command kubectl get -o yaml pods <pod-id>
3) Run your container as daemonset,  run kubectl logs --previous pod-id container to retrieve previous terminated container's log

**Comment by sbezverk** [comment]
@dchen1107 It turned out that replication controller also shows the similar issue :(
Here is the link to requested information. 
[Collected logs](http://paste.openstack.org/show/550400/)
Let me know if additional info is required.

**Comment by sbezverk** [comment]
@dchen1107 Interesting observation, if I start the process inside of a container with this script,
#!/bin/bash

sleep 1
/usr/sbin/ovsdb-server /etc/openvswitch/conf.db -vconsole:emer -vsyslog:err --remote=punix:/run/openvswitch/db.sock -vfile:info --log-file=/var/log/kolla/openvswitch/ovsdb-server.log

it works perfectly on both compute nodes.
