### ISSUE TITLE
gobindata runs multiple times on build

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#30113]
Ideally, it would only run when there were updates. At the very least, it should only run once per build command.

Example output:

```
$ make kubelet
Go version: go version go1.6.2 linux/amd64
+++ [0804 17:14:25] Generating bindata:                                      <------ First run
    /usr/local/google/home/stclair/go/k8s3/src/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go
Generated bindata file : 11536 ../../..//test/e2e/generated/bindata.go lines of lovely automated artifacts
+++ [0804 17:14:30] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0804 17:14:31] Building go targets for linux/amd64:
    cmd/libs/go2idl/deepcopy-gen
+++ [0804 17:14:33] Placing binaries
Go version: go version go1.6.2 linux/amd64
+++ [0804 17:14:36] Generating bindata:                                      <------ Second run
    /usr/local/google/home/stclair/go/k8s3/src/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go
Generated bindata file : 11536 ../../..//test/e2e/generated/bindata.go lines of lovely automated artifacts
+++ [0804 17:14:41] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0804 17:14:42] Building go targets for linux/amd64:
    cmd/libs/go2idl/conversion-gen
...
```

For starters, can we move the command to generate gobindata to `Makefile.generated_files` ?

**Comment by jayunit100** [comment]
thanks for noting this - if there is a common progenitor to all make tasks we could do that.. ill be context switching till the 15th but maybe can look this wknd.

**Comment by jayunit100** [comment]
After looking a little and refreshing myself, we use `go generate` in the compilation of `gobindata_util.go`.

- The *advantage* of this is that there is no imperative logic on when to generate the binary representation of the static data.
- The *disadvantage*, as you mentioned, is that if more than one directory compiles `test/e2e/`, the generation will be done.  This leads to redundant work (each generation step is about .5 seconds).

@timstclair Id say overall the complexity reduction of using `go generate` lazily, rather than having an explicit bash step outweighs the cost of an extra .5 seconds.  But, of course, maybe im just thinking lazily :).  Let me know what your thoughts on this are ^. 

Open to feedback.

**Comment by timstclair** [comment]
There's some pretty complicated logic (that I don't understand) in https://github.com/kubernetes/kubernetes/blob/master/Makefile.generated_files. For now, it might be sufficient to just move the generation command into that make rule (generated_files). But I do agree that it's fast enough that this is low priority.

**Comment by jayunit100** [comment]
...Also the code portability increase when using native go generate rather than relying on more bash build steps

**Comment by jayunit100** [comment]
@timstclair  sounds like we agree that its better to build this lazily and take the .5 second hit.  
ok to close this ?

**Comment by timstclair** [comment]
I think there's only a code portability increase when all our code generation is using that. As is, the extra make step is necessary for generating files, so I'd argue the consistency gains of that are more significant than the portability gains of go generate. Either way, this is low priority, so I'll leave it to your discretion.

**Comment by jayunit100** [comment]
ok.  my decision would be to close [for now] at least.  if others voice a concern or if the generation times get higher i guess we should reopen

**Comment by spiffxp** [comment]
/sig release
/priority awaiting-more-evidence
because it's part of the build; maybe this is too low priority to remain open, but it does seem to run way more often than it should

**Comment by thockin** [comment]
I would leave this open.  I hope to revisit the build eventually..

**Comment by jayunit100** [comment]
I think we're going to close this ...
