### ISSUE TITLE
Use nsinit or runtime specific method instead of nsenter in kubenet

### ISSUE THREAD

**Issue by dshulyak** [kubernetes/kubernetes#30144]
nsinit is better alternative as it is a part of libcontainer, also it is relatively easier to install

Or even better change implementation so that this method would be a part of runtime, so for example to get ip in docker we can use `docker exec`

I am willing to work on this, but want to know if it makes sense

**Comment by luxas** [comment]
Would this remove the `nsenter` dependency?
ref #26093 

cc @kubernetes/sig-node

**Comment by ncdc** [comment]
cc @mrunalp

**Comment by mrunalp** [comment]
If using docker 1.11+, then runc exec would be the best light weight option. 
There should be an executable called docker-runc in the PATH.
So, one could just docker-run exec container-id command

**Comment by luxas** [comment]
I think we have to support 1.10 in v1.4
... and other runtimes of course! What about rkt?

**Comment by yujuhong** [comment]
> I think we have to support 1.10 in v1.4
> ... and other runtimes of course! What about rkt?

AFAIK, We won't drop docker v1.10 support in v1.4.

By the way, we are discussing the potential of pushing networking down to the runtime (#28667) for the CRI work. In which case, kubenet may eventually become part of the docker subpackages in kubelet. 
/cc @freehan 

nsenter is also used in exec, portforward, etc, in both the dockertools and the rkt packages.

**Comment by mrunalp** [comment]
nsenter would be the least common denominator across runtimes but comes at the cost of not being accounted to cgroups

**Comment by luxas** [comment]
Is there a way we could "convert" the nsenter C code to Go, by sending the same syscalls etc.?
Or is it possible to "vendor in" it via cgo?

**Comment by euank** [comment]
@luxas I believe that @steveej has code in [this CNI package](https://github.com/containernetworking/cni/tree/master/pkg/ns#namespaces-threads-and-go) for that, so already done.

I think he's also mentioned a few times that we should be using it here :)

**Comment by mrunalp** [comment]
While locking OS Thread works for network namespace, it doesn't work for joining other namespaces so we need to use a C contructer like it is done in libcontainer. So, I don't see the value in rewriting a least common denominator tool in Go, as most of the code would end up being in C anyways.

**Comment by luxas** [comment]
@mrunalp Does that mean we may just vendor in `https://github.com/opencontainers/runc/tree/master/libcontainer/nsenter` for the kubelet? How should we call `nsexec` then?

**Comment by euank** [comment]
> nsinit is better alternative ... also it is relatively easier to install

Citation needed on both of those. nsinit looks like a less flexible/less low-level nsenter from glancing at it. Also, it's removed from libcontainer as of a while ago (https://github.com/opencontainers/runc/pull/8/files .. the docker/libcontainer repo is not maintained anymore afaik).

nsinit is harder to install from my n=1; my package manager installed nsenter.

I'm -1 on switching nsenter to nsinit just for the sake of switching. nsenter is more commonly packaged (and thus easier to package as a dependency for traditional package management). nsenter is lower level and fits the kubelet's use-case. nsenter is more broadly used.

> If using docker 1.11+, then runc exec would be the best light weight option. 

We should use runc exec for the OCI runtime, docker exec for the docker runtime, rkt enter for the rkt runtime... and then we're still missing a generic tool for kubenet and a couple other places, which leaves us where we are now.

> nsenter would be the least common denominator across runtimes but comes at the cost of not being accounted to cgroups

Good idea, we can have the kubelet execute nsenter within the pod cgroup, once we have pod-level cgroups sorted out, and then it'll be accounted just fine.

**Comment by mrunalp** [comment]
@luxas, no it isn't that simple. It joins the namespaces that are passed to it over a netlink socket. It needs a wrapper binary like runc to be used. 

@euank Yeah, charging nsenter to pod cgroups should improve the situation. Also, it makes sense to use the native exec approach for each runtime whenever possible.

**Comment by dshulyak** [comment]
@euank maybe kubenet can use runtime interface to execute things inside of the namespace? I see that kubenet uses nsenter to get pod ip, it seems that runtime can do that. Is there any other place where kubenet needs nsenter?

@yujuhong so there is no such goal as to support hyper-hq runtime in kubenet?

**Comment by yujuhong** [comment]
> @yujuhong so there is no such goal as to support hyper-hq runtime in kubenet?

It's discussed more in details in #28667, but the gist is that it's too difficult for kubenet to support a variety of runtimes reliably. If we decide to delegate networking to runtimes, we'll augment CRI for more network configuration and status. Kubelet itself (which does not include kubenet) will not need nsenter.

**Comment by bboreham** [comment]
> While locking OS Thread works for network namespace

Not really; locking doesn't stop Go from creating new threads, and they inherit the changed namespace, which can then have unexpected effects elsewhere.  See for instance https://github.com/containernetworking/cni/issues/183#issuecomment-220384737, https://github.com/vishvananda/netns/issues/17

**Comment by mrunalp** [comment]
Okay, so even net ns isn't safe but we are fine in runc since all the setns calls are made in C before the Go runtime starts.

**Comment by euank** [comment]
I don't think there's any reason to have this issue open. The title is about nsinit, and unless you disagree with my [comment ](https://github.com/kubernetes/kubernetes/issues/30144#issuecomment-237979803) above, I think that we can all agree we shouldn't use nsinit.

Switching to using native runtime exec can be discussed separately, and already is a bit as part of #30225. IMO this should be moved into 1) that pr and 2) discussion of network plugins in CRI.
