### ISSUE TITLE
Image pull failures should include the error cause.

### ISSUE THREAD

**Issue by dakoner** [kubernetes/kubernetes#30148]
I am using Kubernetes via Google Container Engine.  I have two projects.  I build images using the first project, and uploaded them to Google Container Registry.  In the second project, I created a new cluster, and create a pod in the cluster with a container that references the image.  

The pod fails to start.  To debug this, I used the "kubectl proxy" command to create a local server that can access the cluster.  When I inspect the container logs in Kubernetes Dashboard I see only:
`container "upload" in pod "upload" is waiting to start: trying and failing to pull image`

I get a similar level of lack of information from kubectl logs:
`kubectl logs upload upload
Error from server: container "upload" in pod "upload" is waiting to start: trying and failing to pull image`

This isn't enough information to debug the problem.  So, I logged into the Google Compute Engine docker host, ran "docker pull <path to GCR image>" and get an error:
docker pull <path to GCR image>

Using default tag: latest
Pulling repository <path to GCR image>
Error: Status 403 trying to pull repository <path to GCR image>: "Unable to access th
e repository: <path to GCR image>; please verify that it exists and you have permission to access it."

After searching for this type of bug, I found that "kubectl get events" shows the event (interspersed with a large amount of other information that I had to filter).

That error message should be propagated up to the log message on the Dashboard and 'kubectl logs'.

**Comment by yujuhong** [comment]
I think we can do a better job of surfacing the errors in the pod status directly. For now,
`kubectl describe pod <pod_name>` should show you both the pod status and the events relevant to the given pod.

**Comment by pwittrock** [comment]
@ymqytw Another starter task

**Comment by duzy** [comment]
I'm exactly having the same issue like this.

**Comment by kishore3us** [comment]
I got this error when the dockerPull secret is not created for the namespace.

**Comment by dambrogia** [comment]
I ran into this error with minikube while trying to pull containers from ECR. I had to follow the instructions [here](https://minikube.sigs.k8s.io/docs/handbook/registry/#using-a-private-registry) to allow minikube to authenticate to ECR on my behalf.
