### ISSUE TITLE
Consistently set/clear SelfLink for both new/old objects passed to validateUpdate

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#30158]
I noticed we seem to be inconsistent in writing selfLink to etcd, for example: 

``` console
$ etcdctl get /registry/namespaces/default | jq . | grep -i self
$ kubectl get ns default -o yaml | grep -i self
  selfLink: /api/v1/namespaces/default
$ etcdctl get /registry/serviceaccounts/kube-system/default | jq . | grep -i self
    "selfLink": "/api/v1/namespaces/kube-system/serviceaccounts/default",
$ kubectl get serviceaccount default -o yaml | grep -i self
  selfLink: /api/v1/namespaces/default/serviceaccounts/default
```

This means the "old" object given to `strategy.validateUpdate` call probably differs from the "new" object with regards to SelfLink, meaning a reflect.DeepEqual(oldMeta, newMeta) will fail. 

I didn't debug much further. I ran into it debugging a petset issue. Perhaps it's something the resource authors failed to do that caused this behavior?

@kubernetes/sig-api-machinery

**Comment by smarterclayton** [comment]
We've regressed several times, but selfLink should never be in etcd
and *should* be cleared by both create and update flows in their
strategies.  It might have reverted when we stopped mutating in
validation (don't quote me on that).

**Comment by lavalamp** [comment]
Agree w/ Clayton.

**Comment by bprashanth** [comment]
Hmm, I should retitle. My main problem is that validation functions should either get (new, old) with both links set or both links cleared. I guess I don't really care if it's in etcd (but itsn't it easier to just store it?).

**Comment by smarterclayton** [comment]
It's fairly expensive to generate, and self links are kind of
worthless to real clients today (don't quote me on that, but I know of
no use for them on clients).

**Comment by wojtek-t** [comment]
+1 for what @smarterclayton wrote

**Comment by smarterclayton** [comment]
Is this still an issue?  We should look for 1.7

**Comment by deads2k** [comment]
This is important.  If we can fix it we should, I wouldn't call it a blocker.

**Comment by smarterclayton** [comment]
Writing self link to etcd is bad because it's wrong data and could potentially leak.

**Comment by lavalamp** [comment]
I think the current state is: regressed

unless someone has fixed this recently.

I would not block the release over this.

**Comment by liggitt** [comment]
> Writing self link to etcd is bad because it's wrong data and could potentially leak.

And it can flutter for resources served from two api groups or versions

**Comment by marun** [comment]
Given that both @lavalamp and @deads2k don't consider this a blocker, moving to 1.8.
