### ISSUE TITLE
Add ability for ConfigMapVolumeSource to project metadata into a file

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#30170]
It would be nice to expose e.g. `ObjectMeta.ResourceVersion` in a file in the same directory as the keys projected from your configmap when consuming a configmap as a volume. Right now `ConfigMapVolumeSource` only projects keys from the configmap's `Data` field.

**Comment by thockin** [comment]
I suggested this as a discussion topic.  It is "interesting" to be able to get resourceVersion, but it will require a downwardAPI-like syntax.  I am not sure it's worth the effort, but we should maybe document the suggested way to do this.

**Comment by thockin** [comment]
@pmorie @erictune

**Comment by erictune** [comment]
Interesting.  Would like to understand how it fits into a broader workflow around configmaps.
