### ISSUE TITLE
Support list/get/watch ObjectMeta in api server

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#30180]
Derived from the discussion [here](https://github.com/kubernetes/kubernetes/issues/30110#issuecomment-237864919).
#28480 implements a client that only decodes the metadata part of an object. It's useful for garbage collector, or any other components that only care about the object's metadata. However, #28480 only works with JSON, not with Protobuf.

To support both content types, and to make the client simpler, it's desirable to let api server support list/get/watch of the ObjectMeta for a resource, and convert it to a specific version of ObjectMeta that the client requests for.

@smarterclayton @lavalamp

**Comment by smarterclayton** [comment]
There is an existing "get subset of object" issue, with a few implementation options proposed.  There is also "spec" and "status" requests.

I'd like to unify both with server side support for partial object retrieval, and unify it with the export and proposed "get" on server use case (which needs to return an alternate representation of a list from the server).

Clients would use an accept header and/or query params to request a partial / alternate representation of lists, watches, and gets.  The server would handle transformation from the stored object to the destination format.  Clients dealing with arbitrary server groups may request transformation to a known schema type (I need a v1.ObjectMeta).

We would create a new API group "api.kubernetes.io" with "v1alpha" / "v1".  Certain known schema objects would be grandfathered into v1 - ListOptions, Status, List, ObjectMeta.  API discovery would be moved into it after correcting any gaps.  These types would continue to be "vendored" into other API groups as today, to allow generated clients that only care about a single group to function correctly.  

The Scale subresource would continue tobe vendored, but would support multi versioning correctly now for naive clients on POST and GET.  

Kubectl get would use "Accept: application/json;kind=v1.Table" (possibly with a query param) to control the returned "generic" schema for tabular output.  The server would return an appropriate error if the kind is not available at that code level.

We would move "unversioned" internal types to "v1.api.kubernetes.io".

**Comment by smarterclayton** [comment]
For object meta we would define "v1.PartialObjectMeta" with TypeMeta and ObjectMeta.  For Spec we could define "v1.PartialObjectSpec".

We would *not* do selective field retrieval (although potentially the tabular output form for Get could someday accept "columns").

**Comment by smarterclayton** [comment]
Will draft up a proposal and unify it with the "move get to server" proposal I already started.

**Comment by smarterclayton** [comment]
If we need to support multiple versions of input params, we can in the future support a query parameter that accepts a group version kind of query params to transform to the server type.

Third party resources would switch to using "v1.api.kubernetes.io" for all their versioned embedded objects, and in the future we could support a flag on third party registration that defines what the "default" API version for cross group resources would be per third party API.

**Comment by smarterclayton** [comment]
The server in the future might have an optimized path for returning partial results, but either way it's a detail hidden from clients.

**Comment by AdoHe** [comment]
@smarterclayton I am wondering whether we can divide this to small steps, so we can implement it step by step?

**Comment by smarterclayton** [comment]
Yes, although most of the framework is in place today.  We probably
need agreement on the concept before we start breaking off pieces,
since the implications are fairly wide reaching.

**Comment by caesarxuchao** [comment]
> There is an existing "get subset of object" issue

Is it #1459?

**Comment by smarterclayton** [comment]
Yup.  I'm reasonably convinced this unifies both problems, will write
up something more formal shortly.

**Comment by caesarxuchao** [comment]
Sounds good. 

Will server do the conversion (e.g., v1.Pods to v1.api.k8s.io.PartialObjectMeta) via the regular conversion framework? I feel the conversion functions can be generated.

**Comment by smarterclayton** [comment]
I think so.  The server can also hide optimizations like fast protobuf
decode from etcd in versioned form (server can already introspect go
structs, find the necessary tags with compatible fields, and then use
custom optimized decode paths).

**Comment by smarterclayton** [comment]
https://github.com/kubernetes/community/pull/123 is close and https://github.com/kubernetes/community/pull/363 would reuse the same mechanism.

**Comment by cben** [comment]
Has this been covered by #40848 /  kubernetes/community#363 with `?includeObject=Metadata`?

(not asking for anything, just wiki-walking some issues trying to figure out how they relate...)

**Comment by smarterclayton** [comment]
Yes, still alpha in 1.8.  Likely to be promoted to beta in 1.9.
