### ISSUE TITLE
for all delete collection of resource APIs, default labelSelector and fieldSelector should mean nothing instead of everything

### ISSUE THREAD

**Issue by yaxinlx** [kubernetes/kubernetes#30186]
to avoid mis-operating.

For example, client wants to delete one pv or pvc, but the resource name is blank, this will result to delete all pv or pvc.

**Comment by AdoHe** [comment]
@kubernetes/kubectl @kubernetes/sig-api-machinery

**Comment by pwittrock** [comment]
Is for deletion through the API directly or through the kubectl client?

```sh
kubectl delete pods
error: resource(s) were provided, but no name, label selector, or --all flag specified
```

**Comment by pwittrock** [comment]
cc @pwittrock

**Comment by yaxinlx** [comment]
@pwittrock, through API

**Comment by caesarxuchao** [comment]
@yaxinlx your concern is very real, but it would tricky to change the meaning of empty selectors, since it's a breaking API change. Also, `DeleteCollection()` use the same `ListOptions` used by `List()` and `Watch()`, empty selectors have to mean the same thing in all these methods. cc @kubernetes/api-review-team @wojtek-t

**Comment by liggitt** [comment]
The client warning seems sufficient. I don't see changing the API behavior here

**Comment by yaxinlx** [comment]
@caesarxuchao, it is not tricky. 

The case I encountered was I want to delete a pv, but with a blank pv name, then all pv were deleted. No ListOptions was provided in the API request.

I think no ListOptions provided and an blank ListOptions provided are different.

**Comment by AdoHe** [comment]
We should keep the meaning of empty selectors, there are many tools depend on this meaning. Just according to what @yaxinlx commented, no ListOptions should be considered.

**Comment by smarterclayton** [comment]
All API List requests are considered to be provided an empty ListOptions.
We make no distinction between unset ListOptions and no ListOptions.  It is
impossible to provide "no ListOptions".

**Comment by yaxinlx** [comment]
@smarterclayton, but it is possible from technology view.

**Comment by smarterclayton** [comment]
I agree that specifying an empty label and field selector is not the same
as nil field selector.  Unfortunately, to change it now would be to break
backwards compatibility with clients that are allowed to specify that.  So
at best we could consider this in a future API revision.
