### ISSUE TITLE
Configure golang http client transport's maxIdleConnsPerHost in scheduler bind client

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#30194]
As scheduler‘s algorithm and bind are asynchronous, there can be multiple goroutines posting binding in the same time. Golang http client transport set `maxIdleConnsPerHost` vaule to 2 by default. 

When number of binding goroutines exceeds 2(maybe 20), then tcp connection and disconnection will happen very frequently, which will cost more time to finish a binding(HTTP POST) request. 

So, should we increase the number of http client transport's `maxIdleConnsPerHost` for binder?

@wojtek-t @kevin-wangzefeng

**Comment by wojtek-t** [comment]
This should be already done:
https://github.com/kubernetes/kubernetes/blob/f2ddd60eb9e7e9e29f7a105a9a8fa020042e8e52/pkg/client/transport/cache.go#L71

[This is the client that is used by all our components.]

If you think that because of some reason it doesn't work, please reopen this issue.

**Comment by m1093782566** [comment]
ok, thanks!
