### ISSUE TITLE
Ingress can pick up loadbalancer-source-ranges 

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#30196]
If an Ingress points to a Service with loadbalancer-source-ranges (https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/services-firewalls.md#restrict-access-for-loadbalancer-service) we can apply the right firewall. For GCE this means creating the vm level source-ip firewall, for nginx this means rejecting traffic based on `x-forwarded-for`. 

This suffers from the same shortcoming on GCE as the corresponding Service of type=loadbalancer (i.e 2 services both requesting port :80 one without loadbalancer-source and one with it set to 10.0.0.0/8, will allow the world through :80, because GCE firewalls are only configurable at the vm level).

**Comment by aledbf** [comment]
The NGINX ingress controller already supports a source-ip firewall using an annotation [whitelist-source-range](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/configuration.md#whitelist-source-range)

**Comment by bprashanth** [comment]
Ah thanks for the reminder, i forgot about that. so i guess we just need to pipe the Service field through to https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/controller.go#L723
