### ISSUE TITLE
Dns server is null in some pods.

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/kubernetes#30215]
I have two pods in the kube-system namespace, one can resolve dns, When resolve the dns in another pod, it can't resolve the name, and shows the server is null. But the correct dns server already in `/etc/resolv.conf`

```
[root@ip-172-18-12-44 heapster]# kubectl get pod --namespace=kube-system
NAME                     READY     STATUS    RESTARTS   AGE
busybox                  1/1       Running   0          10s
heapster-dje5c           1/1       Running   0          1h
influxdb-grafana-iuebs   2/2       Running   0          1h
kube-dns-v19-82nif       3/3       Running   0          2h
[root@ip-172-18-12-44 heapster]# kubectl exec --namespace=kube-system busybox -- nslookup kubernetes.default
Server:    10.0.0.10
Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local

Name:      kubernetes.default
Address 1: 10.0.0.1 kubernetes.default.svc.cluster.local
[root@ip-172-18-12-44 heapster]# kubectl exec --namespace=kube-system heapster-dje5c -- nslookup kubernetes.default
Server:    (null)
nslookup: can't resolve 'kubernetes.default': Name does not resolve
Address 1: ::1 localhost
Address 2: 127.0.0.1 localhost

error: error executing remote command: error executing command in container: Error executing in Docker Container: 1
[root@ip-172-18-12-44 heapster]# kubectl exec -it --namespace=kube-system heapster-dje5c -- /bin/sh
/ # cat /etc/resolv.conf 
search kube-system.svc.cluster.local svc.cluster.local cluster.local ec2.internal
nameserver 10.0.0.10
options ndots:5

```

**Comment by jay-bhambhani** [comment]
I'v run into a very similar error

**Comment by MrHohn** [comment]
Heapster is using the 'alpine' base image. It seems like this is a long existing issue for DNS in alpine(gliderlabs/docker-alpine#8).

cc @girishkalele

**Comment by bprashanth** [comment]
Alpine broke dns search paths but fixed it in some later release. It should be fixed in edge, in spite of what https://github.com/gliderlabs/docker-alpine/blob/master/docs/caveats.md indicates. We should update the image to the exact version with the fix, which you can figure out with a test like (or prove im wrong by running the test on edge): 
docker run --dns 8.8.8.8 --dns-search github.com -it alpine:3.3 nslookup www

**Comment by bprashanth** [comment]
@piosz @mwielgus for the alpine issue

**Comment by jay-bhambhani** [comment]
This is happening for us with Ubuntu

**Comment by bprashanth** [comment]
what's you resolv.conf look like? ubuntu doesn't suffer from the same issue so it's likely something wrong with services or connectivity, see http://kubernetes.io/docs/user-guide/debugging-services/#does-the-service-work-by-dns for debugging tips

**Comment by piosz** [comment]
I created an issue in Heapster to migrate out of Apline https://github.com/kubernetes/heapster/issues/1284

**Comment by cordoval** [comment]
i ran into this:

```
~ kubectl exec -it nginx-deployment-4178600648-mfbpx bash                                                                                                                                                                               iMac [9:36:12]
bash-4.3# nslookup kubernetes.default
nslookup: can’t resolve ‘(null)‘: Name does not resolve

Name:      kubernetes.default
Address 1: 100.64.0.1 kubernetes.default.svc.cluster.local
```
also

```
ps auxw|grep kubelet
```
returns nothing

**Comment by cmluciano** [comment]
@cordoval It looks like your node is under significant pressure. All of your entries seem to be evicted. Is the node currently under memory pressure?

**Comment by cordoval** [comment]
what do you mean on your last comments? also i killed a node and the ASG resized them and it now works, maybe kube-ip-proxy got down for some reason and that was the cause, now i see everything working fine.

**Comment by cmluciano** [comment]
@piosz @bprashanth Do you think we can close this issue now?

**Comment by MrHohn** [comment]
@cmluciano The original post is about the nslookup bug in Alpine image and that is cleared. I think we should close this one to avoid stacking up other unrelated issues in the same place.
