### ISSUE TITLE
Speed up list-wach in API Server side

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#30220]
The performance of list-watch takes an effect on the real-time event perceiving of kubernetes client side, such as scheduler, controller manager, kubelet etc.

I have some ideas about speeding up list-watch in API Server side. 
1. As @hongchaodeng metioned [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/etcd3/watcher.go#L212), we can use etcd newest API(support prevKv in PUT/DELETE operations) to avoid extra Get() when transform etcd event. AFAIK, we can't introduce the API until cores/rkt upgrades its grpc package of its api service. However, good news is that rkt has upgraded it about a week ago. So, it's time to introduce etcd's newest feature?
2. Concurrently transform event to speed up list-watch server side processing event. We can spawn multiple goroutines to do the [procedure](https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/etcd3/watcher.go#L189) concurrently. Of course, we should keep the order.

What's your option?

@hongchaodeng @xiang90 @wojtek-t

**Comment by wojtek-t** [comment]
@m1093782566 

- regarding 1:
we are still not using etcd3 and we will still be supporting etcd2 for at least few more months; What is more, the default version is still etcd3, so this isn't something we can do easily now.


The comment in general - what is the problem that you are trying to solve? It doesn't make sense to do optimizations (that will complicate the code), if you are not solving any specific problem you are facing (or you know you will face soon). I would like to understand your usecase before agreeing on any specific solutions.

**Comment by m1093782566** [comment]
@wojtek-t 

I use the latest master branch API Server and etcd v3 in my environment. My machine is a 8U8G VM, with **slow disk(not SSD)**.  API Server and etcd are deployed in the same machine.

As the following code block shows, I use trace Log to record any transform event procedure that lasts longer than 100ms.

```
func (wc *watchChan) transform(e *event) (res *watch.Event) {
	var trace *util.Trace
	trace = util.NewTrace("transform event")
	defer trace.LogIfLong(100 * time.Millisecond)
	trace.Step("About to prepareObjs...")
	curObj, oldObj, err := prepareObjs(wc.ctx, e, wc.watcher.client, wc.watcher.codec, wc.watcher.versioner)
	...
}
```

Below is part of observation, and they are not seldom in my environment. 

```
I0809 11:39:17.197737       5 trace.go:61] Trace "transform event" (started 2016-08-09 11:39:16.70269803 +0000 UTC):
[3.379µs] [3.379µs] About to prepareObjs...
[494.999936ms] [494.996557ms] END

I0809 11:39:17.199767       5 trace.go:61] Trace "transform event" (started 2016-08-09 11:39:16.82182432 +0000 UTC):
[4.083µs] [4.083µs] About to prepareObjs...
[377.904212ms] [377.900129ms] END

I0809 11:39:17.304822       5 trace.go:61] Trace "transform event" (started 2016-08-09 11:39:17.098626866 +0000 UTC):
[4.387µs] [4.387µs] About to prepareObjs...
[206.159484ms] [206.155097ms] END
```

I assume because of my slow disk that etcd use, Get KV from etcd cost most of the time. The long latency of transforming event makes the latency of event perceiving longer. So, I think speeding up the procudure make sense in my environment. Thanks!

**Comment by wojtek-t** [comment]
@dims - thanks for clarification; what you wrote makes sense.

However, since it seems that the problem is with Get to etcd, we should try to get rid of this Get instead of doing parallelization here, which would significantly complicate the code (because we need to preserve the order). And we are not even officially supporting etcd3 yet (though we are trying to do so).

@hongchaodeng @xiang90 - can you please help (or suggest) how to improve this path to get rid of this Get()?

**Comment by dims** [comment]
@wojtek-t - /me has no clue what i did :)

**Comment by wojtek-t** [comment]
@dims - sorry - I was supposed to write to @m1093782566 m1093782566

**Comment by hongchaodeng** [comment]
@m1093782566 @wojtek-t 
PrevKV isn't the optimal solution. We can get rid of such serialization by reusing the items already in cache. This is what I have implemented in the new storage (#29888). Unfortunately, in the low level etcd storage impl, we cannot do that or we would otherwise double cache.

**Comment by m1093782566** [comment]
@hongchaodeng 

Thanks! I will trace the PR.

**Comment by m1093782566** [comment]
#29888 has better solutions, I am going to close this issue and ready to do help.

THANKS ALL!
