### ISSUE TITLE
certificatesigningrequests should overwrite spec.user info in createstrategy

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#30239]
The API server should overwrite the info in the spec with the info from the context, not allow it to be set by end users

**Comment by liggitt** [comment]
ref: https://github.com/kubernetes/features/issues/43

**Comment by mikedanese** [comment]
A user should be able to create a CSR for a different user which was the motivation. I think that Username can be removed from Spec altogether since it's contained in the CSR.

**Comment by liggitt** [comment]
Code in question is https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/certificates/registry.go#L56-L70

It should clear user info in the spec if no user exists in the context

It should overwrite the user info in the spec with the user from the context

If a highly privileged user wants to create a CSR for another user, they can do so using impersonation (`kubectl --as=`)

**Comment by liggitt** [comment]
username is not in the CSR in a way that maps directly to API authorization

**Comment by liggitt** [comment]
also, the CSR is under the end user's control... the username should be under the API server's control. Otherwise, nothing stops me from submitting a CSR for some other user/server/etc with my private key

**Comment by mikedanese** [comment]
> Otherwise, nothing stops me from submitting a CSR for some other user/server/etc with my private key

Why is this bad? Hopefully whatever approval controller you are using would deny that request.

> username is not in the CSR in a way that maps directly to API authorization

Not common name?

> If a highly privileged user wants to create a CSR for another user, they can do so using impersonation (kubectl --as=)

Does the RESTClient support this?

**Comment by mikedanese** [comment]
cc @erictune @gtank

**Comment by liggitt** [comment]
> Why is this bad? Hopefully whatever approval controller you are using would deny that request.

What is your approval controller using to determine what to approve? If the only thing in the request is the CSR, and the CSR is fully controlled by the end user, an approver has no other information about the requester... that seems difficult to make an approval decision on.

>> username is not in the CSR in a way that maps directly to API authorization
>
> Not common name?

Can't assume that... a node requesting a serving cert isn't necessarily setting it's client cert CN in a CSR for a serving cert related to its hostname.

>> If a highly privileged user wants to create a CSR for another user, they can do so using impersonation (kubectl --as=)
>
> Does the RESTClient support this?

It can be, it's specified in the config used to build the transport for a RESTClient: https://github.com/kubernetes/kubernetes/blob/master/pkg/client/transport/config.go#L37-L38

**Comment by liggitt** [comment]
actually, re-reading the registry, the user overwrite needs to be moved into a custom `Create` function... when invoked via the API, it doesn't look like the API sets user info at all in the request spec

**Comment by mikedanese** [comment]
> What is your approval controller using to determine what to approve?

An approver can verify that the user has control over the private key that signed the CSR out of band a number of ways. It was left out of scope of this API. Approval controllers shouldn't need this guarantee around usernames to operate correctly. https://tools.ietf.org/html/draft-ietf-acme-acme-01#section-7 . @gtank can you weigh in?

**Comment by liggitt** [comment]
> An approver can verify that the user has control over the private key that signed the CSR out of band a number of ways. It was left out of scope of this API. Approval controllers shouldn't need this guarantee around usernames to operate correctly.

If they have another out-of-band process they want to use, they can certainly ignore the user info. It just seems like a loss to discard the information the authentication layer already determined about the requester.

**Comment by zhouhaibing089** [comment]
What is the usage for `spec.user`, is it just for telling who submitted the CSR? is there any other usage for this field?

**Comment by gtank** [comment]
I see no reason to explicitly drop this metadata. If it's not meaningful to our approval regime we can ignore it and rely on whatever out of band challenge process we want to use.
