### ISSUE TITLE
vSphere Cloud provider create volume diskpath invalid with Datastore cluster

### ISSUE THREAD

**Issue by dagnello** [kubernetes/kubernetes#30248]
If vSphere is configured to use a Datastore within a Datastore cluster, the Datastore configuration parameters is set as follows:  <Datastore Cluster>/<Datastore>.

The disk path in create volume is composed as:
vmDiskPath := "[" + vs.cfg.Global.Datastore + "] " + name + ".vmdk"

This needs to change to use the finder object instead, like:
ds, err := f.Datastore(ctx, cfg.Global.Datastore)

**Comment by kerneltime** [comment]
@dagnello can we close this issue?

**Comment by robdaemon** [comment]
@kerneltime - we can close this one.

**Comment by msau42** [comment]
Closing as per above comment
/assign
