### ISSUE TITLE
Add one parameter to instantiate multiple similar pods with indexes

### ISSUE THREAD

**Issue by tobegit3hub** [kubernetes/kubernetes#30256]
It's the requirement when we're trying to deploy distributed TensorFlow in Kubernetes. The process of TensorFlow can be containerized in docker image and we can start multiple processes with the deployment yaml file.

But what if the users want to setup the deployment with different number of pods, we have to generate different deployment yaml files. The most parts of yaml file are similar and we're using the same docker image and labels. It would be better to add the parameter like "number" and Kubernetes will create multiple pods for that and pass the index so that each pod knows about its index. I think this may be something useful in Google Borg.

To be clear, this is different from replica set because they are not exactly the "same" replicas. And it's similar to [indexed-job](https://github.com/kubernetes/kubernetes/blob/master/docs/design/indexed-job.md) but used for general pods.

**Comment by pwittrock** [comment]
cc @erictune 
cc @pwittrock

@bprashanth Is this something that PetSet addresses?

**Comment by bprashanth** [comment]
@tobegit3hub please take a look at http://kubernetes.io/docs/user-guide/petset/#ordinal-index when you have some time. Unsure if it covers your usecase.

**Comment by tobegit3hub** [comment]
Thanks @pwittrock and @bprashanth and `petset` is exactly nice for our scenario. TensorFlow cluster is like `ZooKeeper` or other clusters which should use `petset`.

The `ordinal-index` is exactly what we want. Because the cluster is started by the developer and their TensorFlow applications need to know its index which is quite different from `ZooKeeper`. Now `petset` provides three ways to get this identity but it's not really convenient.

```
1. Use the downward api to find its pod name
2. Run hostname to find its DNS name
3. Run mount or df to find its volumes (usually this is unnecessary)
```

Is it possible to add environment variable or API for each `pet` to know its index? If it's reasonable,  I may open another issue to track that. This issue could be closed and thanks for all your help.

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/issues/30427

**Comment by tobegit3hub** [comment]
Great! Thanks @bprashanth 😃
