### ISSUE TITLE
vsphere volume path requires datastore

### ISSUE THREAD

**Issue by sputnik13** [kubernetes/kubernetes#30254]
The vsphere volume provider looks like it expects to get the datastore from the vsphere cloud.conf but providing a volume path in a persistent volume resource without the datastore fails to mount while including the datastore in the volume path allows the volume to mount properly...  it seems like datastore should be extracted from the volume path or if the intention is to limit the user to certain datastores the persistent volume creation should fail when a datastore is provided in the path that does not match the configured datastore.

Consequently when a PVC is made that binds the PV, the mount cannot succeed but kubernetes keeps retrying rather than failing out.

**Comment by abrarshivani** [comment]
@sputnik13 It is expected to give datastore in volume path. Datastore in cloud.conf is used to store vmdks which are created dynamically by dynamic provisioning feature of Kubernetes.

**Comment by kerneltime** [comment]
@abrarshivani can you link to the updated documents here?

**Comment by abrarshivani** [comment]
@kerneltime The PRs which updates the documentation is not merged yet.

**Comment by kerneltime** [comment]
@sputnik13 Are you still having an issue? The datastore in the conf is used for dynamic provisioning. For PVC datastore must be specified.
