### ISSUE TITLE
Support pod-to-pod networking on Windows

### ISSUE THREAD

**Issue by alexbrand** [kubernetes/kubernetes#30280]
Once the Kubelet is supported on Windows, we need to figure out a basic approach to inter-pod networking. Some investigation has been done on this front, but it needs to be formalized as documentation, or code + docs if necessary.

Relevant links:
https://docs.google.com/document/d/15uPt333llH-JuP_W0RN11nnRZ_rWutR0FDjaRSadGGk/edit
https://groups.google.com/forum/#!topic/kubernetes-sig-network/Lw6AOgPB8ow

**Comment by PatrickLang** [comment]
We did a big doc push for 1.9, and have multiple network topologies supported:

https://kubernetes.io/docs/getting-started-guides/windows/

I think this issue is safe to close
