### ISSUE TITLE
Custom metrics

### ISSUE THREAD

**Issue by nvartolomei** [kubernetes/kubernetes#30286]
Hello,
any progress being made on [this](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/custom-metrics.md)?

**Comment by dchen1107** [comment]
We already supported alpha feature of custom metrics. Here is the user guide you can follow: https://github.com/kubernetes/kubernetes.github.io/blob/ad511e03c53744e459e2dbcef51132c29b0ddc86/docs/user-guide/horizontal-pod-autoscaling/index.md

**Comment by nvartolomei** [comment]
@dchen1107 I don't quite understand this part:

> Warning Due to the way cAdvisor currently works localhost refers to the node itself, not to the running pod. Thus the appropriate container in the pod must ask for a node port. Example:
```yaml
ports:
  - hostPort: 8080
    containerPort: 8080
```

How to handle this when I have multiple pods on the same nod? They can't all bind on the same host port.

**Comment by xiangpengzhao** [comment]
Please follow the progress here: 
https://github.com/kubernetes/features/issues/117

and get the latest guide here:
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

Will close this issue. @thockin
