### ISSUE TITLE
Create team/windows label

### ISSUE THREAD

**Issue by jbhurat** [kubernetes/kubernetes#30283]
@bgrant0607 @brendandburns @thockin 
Can you guys please help in creating team/windows label to categories Kubernetes on Windows work

**Comment by bgrant0607** [comment]
@jbhurat I created team/windows. It won't automatically be copied to other repositories.

FWIW, I want to rename the team/ labels to area/.

You still won't be able to apply labels without write access.

@foxish @grodrigues3
