### ISSUE TITLE
Qemu/KVM kubelet runtime design 

### ISSUE THREAD

**Issue by vefimova** [kubernetes/kubernetes#30294]
To have an ability to manage pure VMs with k8s I want to propose to add qemu/kvm runtime within client/server model. Will add more details soon. 

But for now I want to share several first thoughts/ list of items to work on (please, comment on them, if from your POV they are mistaken, you have concerns or other considerations):
1. Probably, introduction of new "pod concept" but for VMs, i.e. VM-pod - VM with ability to run tasks inside. Determine the VM-pod schema and propose design for alpha api.
2. Networking design - will give input for `#4`
3. Design for Volumes managing - will give input for `#4`
4. Introduce client/server api to support qemu/kvm runtime:
   kubelet hypervisor runtime <-> KubeletGenericRuntimeManager <-> Hypervisor interface
   - Add support for qemu/kvm options/settings in global kubelets structures
   - Introduce internal general interface for hypervisors: pkg/kubelet/hypervisor/runtime.go (like https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/runtime.go#L59)
   - Hypervisor interface pkg/kubelet/container/interface.go (like container interface: https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/container-runtime-interface-v1.md)
   - Some changes/additions to client/server api to support qemu/kvm runtime (https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/runtime-client-server.md)
5. Qemu/KVM runtime server part implementation (should be contributed to "contrib" repo) - probably need to file corresponding task for this in contrib space.
6. Ability to run and monitore tasks inside VMs

related to #28789
CC @thockin @freehan @brendandburns @dchen1107 @kubernetes/sig-node

**Comment by smarterclayton** [comment]
Having talked about this a lot, this means that the node would only support VMs, not support containers.  I'd argue that's the wrong design, and that we want to run qemu inside of containers, and have the VM management be adapted to containers (not adapt kubelet to containers).

A kubernetes that just runs VMs is a niche use case.  If we're going to do VMs in kube, why not do this in a way that really brings containers and VMs together?

**Comment by smarterclayton** [comment]
I see this comment was already made on the other PR - I'd really urge us to DTRT and get a community supported design for qemu inside of pods with libvirtd either on node or in the container (if we have to fix libvirtd, why not do so)?

**Comment by pskrzyns** [comment]
cc @jjlakis @lukasredynk @ss7pro

**Comment by feiskyer** [comment]
@vefimova This should be done outside of kubelet. https://github.com/kubernetes/frakti is designed for hypervisor-based runtimes, so we could move this issue into frakti repo.

CC @dchen1107 @resouer .

**Comment by vefimova** [comment]
Thanks, @feiskyer, will check frakti repo.

**Comment by nhlfr** [comment]
The difference between what @vefimova proposes and what frakti is doing is that we (Mirantis) would like to run VM-s from QCOW2 images instead of Docker images. This is not possible with hyperd.

I think that we should implement a separate runtime, outiside of the main k8s repo, which will cover "traditional VM-s" approach, after all the things related to client-server runtimes are implemented.

**Comment by nhlfr** [comment]
That runtime would just call libvirt API in order to create VM-s and handle QCOW2 images management. I have no detailed overview of that, but at the same time I don't see any things which may block that approach.

**Comment by vefimova** [comment]
Or instead we could extend hyper with ability to specify vm image instead of "hyperkernel" as hyper already supports xen, qemu/kvm, libvirt. If it's of cource possible. WDYT @feiskyer.

**Comment by nhlfr** [comment]
If hyperd folks will not have anything against this idea, then sure, we can try to do that.

**Comment by feiskyer** [comment]
Hyperd doesn't support qcow2 images and has no plan to support it in the future.

Kubernetes doesn't support QCOW2 image format yet, and how the images are managed of this proposal?

**Comment by feiskyer** [comment]
And I think run traditional VMs (by qcow2 image) directly may not be the scope of kubernetes.

**Comment by resouer** [comment]
I am worrying about including full-blown VM management in k8s is like re-inventing a OpenStack, especially when considering` docker swarm xxx` is making things simpler and simpler >_<

I can also see there are already mature projects like Magnum or nova-docker in OpenStack community to leverage managing containers along with VMs together, which seems make no difference with k8s+libvirt :/

**Comment by nhlfr** [comment]
@feiskyer QCOW2 images can be managed by the custom runtime, which will implement `PullImage` and methods like that with appropriate libvirt calls to import an image to a storage pool. Of course you're right that's outside of scope of k8s, that's why I propose to abandon that issue and implement it as a custom client-server runtime.

@resouer nova-docker project is officially dead and abandoned, Magnum and any other "Kubernetes on OpenStack" solutions are too complicated IMO (because they're using nova/ironic scheduling features to install k8s, which has its own scheduler, it's like a cloud in a cloud). I think that k8s+libvirt solution will be much more lightweight. That's why we'd like to experiment on that, despite the fact that the other folks (even from my company) are researching "OpenStack on Kubernetes" or "Kubernetes on OpenStack" scenarios.

**Comment by vefimova** [comment]
> Of course you're right that's outside of scope of k8s, that's why I propose to abandon that issue and implement it as a custom client-server runtime.

In terms of new client/server model all runtimes implementations except docker must be done outside core k8s repo (probably, contrib, not sure?). But we still need to determine at first high-level design and APIs to be sure that we're fine with currently approved client/server generic APIs and we don't need to request for changes.

**Comment by ConnorDoyle** [comment]
@vefimova 

> must be done outside core k8s repo (probably, contrib, not sure?)

AFAIK they will all need to be [incubated](https://github.com/kubernetes/community/blob/master/incubator.md) as external repositories.

**Comment by nhlfr** [comment]
I still think we should close this ticket. If we will encounter some concrete issue with CRI, then we should create a bug about it.

For now, everything is fine with CRI and we started development of the runtime we discussed here as an external project: https://github.com/Mirantis/virtlet

**Comment by warmchang** [comment]
nice job! :+1:
