### ISSUE TITLE
Naive clients should be able to use exec more effectively

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#30298]
It should be possible to run simple commands inside of containers without having to implement SPDY or websocket.  Interactive commands require a stream on input, but many common tasks for containers require no input (exec probes, prestop, etc).  

We should support a simple EXEC API that allows a client to POST ExecOptions and get back a response.  The options might look like:

```
type ExecOptions struct {
  Command []string
  ContainerName string
  Stdin []byte // limited to < 10k bytes or something easily buffered
  Stdout bool // stdout is optional
  Stderr bool // stderr is optional
}
```

This could be 

```
POST /api/v1/namespaces/ns/pods/pod/exec
Content-Type: application/json
{
  "kind": "ExecOptions",
  ...
}
```

which is allowed because normal exec is a connection upgrade.  Clients that want to perform more complex operations must use WS / SPDY.

This would enable naive clients to invoke exec in a much more usable manner.

**Comment by dims** [comment]
@smarterclayton Absolutely +1 (based on my experience earlier https://github.com/kubernetes/kubernetes/issues/24668) we definitely should support naive http clients to be able to EXEC stuff

**Comment by nhlfr** [comment]
+1

**Comment by nhlfr** [comment]
@smarterclayton are you or someone from Red Hat going to implement this?

**Comment by smarterclayton** [comment]
Not in the short term.  If you would like to get involved I'll be happy to review.

**Comment by nhlfr** [comment]
OK, then I'm going to work on this.

**Comment by erictune** [comment]
This is more auditable than current exec.
Maybe call the subresource something else, like `simpleexec`.  
That would allow having an RBAC role that can do execs this new way, but cannot do streaming connections, which are more of a pain to stick into an audit log.

**Comment by smarterclayton** [comment]
Maybe "run". Although adding more long running operations also has a cost.

**Comment by nhlfr** [comment]
I'll go with `run` name at the moment.

**Comment by nhlfr** [comment]
Umm... I didn't realize that kubectl has already a `run` command, d'oh... I'll go with `simpleexec`. I don't have any better idea for now, but I'm open for suggestions. ;)

**Comment by smarterclayton** [comment]
Not sure what that has to do with it?

**Comment by nhlfr** [comment]
After implementing the "simplier exec" API subresource, we will need to create kubectl cmd for it. Since we already have a cmd called "run", then calling the subresource "run" doesn't make much sense.

**Comment by smarterclayton** [comment]
Why would we implement a simpler command for it?

**Comment by smarterclayton** [comment]
The command would be exec, we might add a flag for simpler behavior
(because it would be a regression to start using this for exec because it
joins stdout and stderr).   I don't like not multiplexing the output (it's
inconsistent) but it is also simpler.

**Comment by dims** [comment]
@nhlfr agree with @smarterclayton - in fact can we see if we can get the curl command printed currently working somehow (detect that the http client cannot upgrade) Please see https://github.com/kubernetes/kubernetes/issues/24668

**Comment by smarterclayton** [comment]
A fallback would definitely be a good place to start, although not having
upgradable requests is not really supported today, so we'd still have to
deal with that.

**Comment by euank** [comment]
One question: timeouts.

If I post a command of `echo hi` I totally expect a stdout of "hi". If I post a command of `sh -c "sleep 10000; echo hi"`, should I expect to see `hi` if I leave my terminal up for the next 3 hours? Should I expect to see a timeout? If I do see a timeout, should I expect the `sh` process I spawned to die as soon as that timeout occurs? Should the timeout be configurable?

My personal preference: add an additional optional `timeout` parameter that defaults to 10s (as measured by kubelet). The process is killed if the timout occurs and whatever stdout/stderr has happened so far is piped back, along with an additional value indicating that the process was interrupted due to timeout.

**Comment by smarterclayton** [comment]
We in general support timeout as a flag on all API calls but it is
inconsistently applied.

Agree that reasonable defaults should be chosen for most API calls and
enforced cleanly and consistently with their API.  That really deserves its
own issue under @kubernetes/sig-api-machinery


On Aug 22, 2016, at 6:57 PM, Euan Kemp <notifications@github.com> wrote:

One question: timeouts.

If I post a command of echo hi I totally expect a stdout of "hi". If I post
a command of sh -c "sleep 10000; echo hi", should I expect to see hi if I
leave my terminal up for the next 3 hours? Should I expect to see a
timeout? If I do see a timeout, should I expect the sh process I spawned to
die as soon as that timeout occurs? Should the timeout be configurable?

My personal preference: add an additional optional timeout parameter that
defaults to 10s (as measured by kubelet). The process is killed if the
timout occurs and whatever stdout/stderr has happened so far is piped back,
along with an additional value indicating that the process was interrupted
due to timeout.

**Comment by lavalamp** [comment]
Instead of a separate subresource, also consider just accepting a
simple=true query parameter.

Actually better would be cmd-interaction-type={streaming|return-val-only}

**Comment by nhlfr** [comment]
@lavalamp's idea seems to consistent. I'd need to dig in code to see how I may extend that.
