### ISSUE TITLE
hostPath support in PetSet volume

### ISSUE THREAD

**Issue by dachulin** [kubernetes/kubernetes#30292]
Wondering if any there anyway to use hostPath as storage for PetSet. It seems like petset only supports dynamic pv or pre-provisioned pv, which also doesn't support hostPath (hostPath is only for test purpose in pre-provisioned pv).

If currently can't use hostPath as storage for petset, wondering if any plan for supporting it? 

Thanks.

**Comment by bpatelcs** [comment]
@vishh

**Comment by bprashanth** [comment]
yeah, local storage dynamic provisioning coming soon: https://github.com/kubernetes/kubernetes/pull/30044
there is right now, if you hand provision your pvs eg: https://github.com/kubernetes/kubernetes/issues/27732#issue-161314678

**Comment by dachulin** [comment]
thanks. I am closing this one for now.
