### ISSUE TITLE
Scheduled job controller can't list scheduled job 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#30323]
I enabled batch/v2alpha1 and can do `curl http://<master-ip>:8080/apis/batch/v2alpha1/scheduledjobs` fine. However, the scheduled job controller loop always fails at

```go
	sjl, err := jm.kubeClient.Batch().ScheduledJobs(api.NamespaceAll).List(api.ListOptions{})
```

It returns me `Error listing scheduledjobs: the server could not find the requested resource`. 

I tried switching kubeClient to unversioned.Client but it still gives me the same error. 

cc @soltysh @erictune

**Comment by janetkuo** [comment]
The client in e2e tests works fine when listing scheduled jobs, digging more.

**Comment by janetkuo** [comment]
In controller manager log, 
```
I0809 17:13:13.419094  112176 round_trippers.go:318] GET http://127.0.0.1:8080/apis/batch/v1/scheduledjobs 404 Not Found in 0 milliseconds
```

It's looking for v1 scheduledjobs

**Comment by soltysh** [comment]
And I've noticed that problem yesterday when I was running my e2e that the controller didn't picked anything up, but I got power outage after a storm and wasn't able to dig in, Thanks for fixing that!
