### ISSUE TITLE
Update docs for http://kubernetes.io/docs/user-guide/accessing-the-cluster/

### ISSUE THREAD

**Issue by johnt337** [kubernetes/kubernetes#30339]
Not sure if this is the right place to request this update...

http://kubernetes.io/docs/user-guide/accessing-the-cluster/
Under the title heading "Without kubectl proxy"

Testing with v1.3.2, this documentation no longer works correctly.

``` sh
TOKEN=$(kubectl config view | grep token | cut -f 2 -d ":" | tr -d " ")
```

Returns blank.

``` sh
TOKEN=$(kubectl describe secret $(kubectl get secrets | grep default | awk '{print$1}') | grep -E '^token' | awk -F: '{print$NF}' | tr -d '\t')
```

Where `$(kubectl get secrets | grep default | awk '{print$1}')` is `default-token-<random>` generated by the system.

**Comment by pwittrock** [comment]
@johnt337 Thanks for filing this.  Would you be willing to file a PR against the kubernetes/kubernetes.github.io repo to fix the issue?

**Comment by pwittrock** [comment]
cc @pwittrock

**Comment by johnt337** [comment]
@pwittrock sure no problem.

**Comment by johnt337** [comment]
@pwittrock moved it here https://github.com/kubernetes/kubernetes.github.io/pull/1011
