### ISSUE TITLE
GKE smoke e2e: no test results found 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#30331]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/30273/kubernetes-pull-build-test-e2e-gke/6136/

```
[xUnit] [ERROR] - No test reports found for the metric 'JUnit' with the resolved pattern '_artifacts/**.xml'. Configuration error?.
```

**Comment by ixdy** [comment]
Lots of `AccessDeniedException: 403 Forbidden` re: the GCS bucket. I think I've fixed this now.
