### ISSUE TITLE
livenessProbe (healcheck) didn't work with ipvlan network

### ISSUE THREAD

**Issue by huxos** [kubernetes/kubernetes#30382]
I am using cni  with ipvlan plugin in kubernetes .  here is my cni config file ：

```
{
    "name": "ipv4-10-0-0-0-16",
    "type": "ipvlan",
    "master": "eth0",
    "mode": "l2",
    "ipam": {
        "type": "host-local",
        "subnet": "10.0.0.0/16",
        "rangeStart": "10.0.9.1",
        "rangeEnd": "10.0.9.10",
        "gateway": "10.0.10.254",
        "routes": [
            { "dst": "0.0.0.0/0" }
        ]
    }
}
```

the docker host can't ping with the pod IP on the same host, so is there any way to use the healchek which based on http.

**Comment by xiangpengzhao** [comment]
The http type health check depends on the pod IP. So, if the pod IP is unaccessible by host, the health check will fail.

@thockin

**Comment by thockin** [comment]
You can try adding an ipvlan interface in the root netns.  That will allow traffic to flow.  Some cases of iptables will still not work properly, though, so if you depend on the default kube-proxy, you will find it breaks down, even in `l3s` mode :(

**Comment by xiangpengzhao** [comment]
Thanks @thockin for the more detailed explanation! I'm trying to scanning stale issues. I wonder if this is a proper way by replying and @ ing you. IMO this is easier to @ you here directly than send a mail to you or create a topic on google group, as long as github doesn't forget to send you a notification:)

**Comment by xiangpengzhao** [comment]
In some stale issues, I will also give a reply which tries to answer their questions. Feel free to correct me if the answers are wrong.
