### ISSUE TITLE
Possible to change the api-server configuration in the vagrant build?

### ISSUE THREAD

**Issue by mlbiam** [kubernetes/kubernetes#30391]
I'm able to get kubernetes 1.3.4 running by downloading the binary from the releases, then:

```
$ export KUBERNETES_PROVIDER=vagrant
$ ./cluster/kube-up.sh
```

once completed I'm able to use kubectl and get to the dashboard using kubectl proxy.  Now, how can I make changes to the api server configuration?  I found /etc/kubernetes/manifests/kube-apiserver.manifest but once I edit it, whats the correct way to restart the api-server?  Is there an external file I can edit?

**Comment by xiangpengzhao** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

@thockin

**Comment by liggitt** [comment]
vagrant provider has been removed
/close
