### ISSUE TITLE
Make the kubeconfig context for federation API server configurable.

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#30394]
The kubeconfig context for the federation API server is now hard coded to `federation-cluster`. We should make this user-configurable with default value set to `federation`.

cc @kubernetes/sig-cluster-federation @quinton-hoole

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#63.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
