### ISSUE TITLE
Move failure domain annotations from Alpha through G.A.

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#30398]
cc @thockin @davidopp @bgrant0607 @justinsb FYI.

=== email thread below explains details ===

On Wed, Aug 10, 2016 at 7:36 AM, Quinton Hoole quinton@google.com wrote:
I believe I'm the guilty party here. Justin SB and I decided to make them alpha in v1.2 because we didn't solve the general topology problem that Tim mentions, but needed the zone and region labels for multi-zone clusters. And then we never went back to finalize it.

Tim, you are absolutely right, we need to think this through properly, and promote whatever the outcome is through beta and GA within a reasonable time. I suggest we add the move to beta to our v1.5 plans. I can sign up for that.

On Aug 9, 2016 10:52 PM, "Tim Hockin" thockin@google.com wrote:
I don't want to derail anything.  I was not trying to demand unplanned work ;)

On Tue, Aug 9, 2016 at 10:49 PM, David Oppenheimer davidopp@google.com wrote:

> I wasn't complaining about your question (or disagreeing with your saying
> that it's half-finished) -- just wanted to understand what specifically you
> were suggesting for 1.4 (if anything).
> 
> I'm totally fine with moving them to GA and doing a more flexible topology
> approach later. Moving these labels to GA doesn't prevent us from inserting
> more labels above, below, or in between the ones we have now (e.g. adding
> rack). So we can potentially put off the more flexible thing for quite some
> time.
> 
> On Tue, Aug 9, 2016 at 10:34 PM, Tim Hockin thockin@google.com wrote:
> 
> > I was simply asking what the plan was.  I hate half-done things with
> > no plan.  The topology annotations are in-use and fairly visible.  I
> > wanted to know if we had a plan for finishing.  We don't and that is
> > OK.
> > 
> > On Tue, Aug 9, 2016 at 10:30 PM, David Oppenheimer davidopp@google.com
> > wrote:
> > 
> > > Tim, are you saying we should move these to GA for 1.4? Or beta is
> > > sufficient? In theory it's just a two line change either way, but I want
> > > to
> > > make sure I understand what you're suggesting.
> > > 
> > > On Tue, Aug 9, 2016 at 10:03 PM, Tim Hockin thockin@google.com wrote:
> > > 
> > > > That's fine, it's just one more thing that we have started but not
> > > > finished.  Should be in the backlog for debt relief.
> > > > 
> > > > On Tue, Aug 9, 2016 at 9:52 PM, David Oppenheimer davidopp@google.com
> > > > wrote:
> > > > 
> > > > > We can move them from alpha/beta and later do a parallel set of
> > > > > labels
> > > > > or
> > > > > whatever to express more complicated topologies. I don't think anyone
> > > > > has
> > > > > time to think about the "right" way to describe flexible topologies
> > > > > right
> > > > > now...
> > > > > 
> > > > > On Tue, Aug 9, 2016 at 9:48 PM, Tim Hockin thockin@google.com
> > > > > wrote:
> > > > > 
> > > > > > Yeah, they WORK.  The "alpha" is ugly.
> > > > > > 
> > > > > > On Tue, Aug 9, 2016 at 9:48 PM, David Oppenheimer
> > > > > > davidopp@google.com
> > > > > > wrote:
> > > > > > 
> > > > > > > I don't think the alpha.\* prefix actually does anything. So if the
> > > > > > > kubelet
> > > > > > > publishes them (I believe that's where they're getting published
> > > > > > > from),
> > > > > > > you
> > > > > > > should be able to use them already on GKE.
> > > > > > > 
> > > > > > > On Tue, Aug 9, 2016 at 9:44 PM, Brian Grant
> > > > > > > briangrant@google.com
> > > > > > > wrote:
> > > > > > > 
> > > > > > > > +davidopp
> > > > > > > > 
> > > > > > > > Bare metal might well have more failure domains. Given potential
> > > > > > > > variation
> > > > > > > > in cluster topologies, I don't know that we ever want these to be
> > > > > > > > fields.
> > > > > > > > The scheduler will deal with them as labels.
> > > > > > > > 
> > > > > > > > We probably want them to be beta, if they aren't already, so they
> > > > > > > > can
> > > > > > > > be
> > > > > > > > used in GKE, but I don't know if this is on anyone's radar.
> > > > > > > > 
> > > > > > > > On Wed, Jul 13, 2016 at 3:24 PM, Tim Hockin thockin@google.com
> > > > > > > > wrote:
> > > > > > > > 
> > > > > > > > > The failure-domain annotations are documented as alpha/beta and
> > > > > > > > > are
> > > > > > > > > named as such.
> > > > > > > > > 
> > > > > > > > > Do we intend to move the annotations to be "real" any time soon?
> > > > > > > > > 
> > > > > > > > > Are we codifying the 2-level zone/region model or do we intend
> > > > > > > > > for
> > > > > > > > > it
> > > > > > > > > to be more generic for arbitrary cases (e.g. rack within a zone)
> > > > > > > > > 
> > > > > > > > > Do we intend for topology info to forever be in labels, or will
> > > > > > > > > it
> > > > > > > > > ever have a home as first-class fields?

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#64.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
