### ISSUE TITLE
Migrate from rackspace/gophercloud to gophercloud/gophercloud

### ISSUE THREAD

**Issue by abithap** [kubernetes/kubernetes#30404]
Openstack cloud provider should move from rackspace/gophercloud to gophercloud/gophercloud repo, as gophercloud moved to its own organization and repo now.

hashicorp/terraform has the same open issue: https://github.com/hashicorp/terraform/issues/7926

**Comment by feiskyer** [comment]
cc @kubernetes/sig-openstack

**Comment by idvoretskyi** [comment]
@anguslees can you review this item?

**Comment by anguslees** [comment]
I don't doubt the above is correct, although http://gophercloud.io/ still points to rackspace/gophercloud github, and there's no mention of the move on rackspace/gophercloud :(

So: yep, I'll do this migration at some point.  I don't seem to be able to assign issues to myself, but consider it as if I've done that thing.

**Comment by rootfs** [comment]
@kubernetes/sig-openstack What is the plan for the migration? gophercloud/gophercloud has shared file and shared network we may need to support manila.

/cc @jsafrane

**Comment by grahamhayes** [comment]
https://github.com/rackspace/gophercloud/issues/592 shows the intent, most PRs have been closed with messages redirecting to the gophercloud/gophercloud repo

**Comment by anguslees** [comment]
@rootfs: I was holding off for the number of PRs in flight to reduce a bit so it would be less disruptive.   I think about now looks like as good as it's going to get, so I'll have a go at doing this now.  Apologies in advance for the PR rebase breakage...
