### ISSUE TITLE
k8s.io/kubernetes/test/integration/kubectl test is flaky

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes#30407]
#30393 test fails with this output: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/30393/kubernetes-pull-test-unit-integration/38690/

It does not seem to be the PR's fault.

**Comment by mbohlool** [comment]
more fault because of memory: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/30393/kubernetes-pull-test-unit-integration/38790/

**Comment by mbohlool** [comment]
Jenkins GKE smoke e2e still failing: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/30393/kubernetes-pull-build-test-e2e-gke/6540/

**Comment by mbohlool** [comment]
master joined this flaky test. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/30233/kubernetes-pull-test-unit-integration/40500/

It is an out of memory problem.

**Comment by spxtr** [comment]
Looks like the `n1-highcpu-16`s don't have enough memory.

**Comment by spxtr** [comment]
Ok, I removed the `n1-highcpu-16`s in favor of `n1-standard-8`s, which were more performant anyway. The GKE smoke test failure looks unrelated.

Please reopen if you see this again and I'll take a closer look.

**Comment by mbohlool** [comment]
Thanks for the help Joe.
