### ISSUE TITLE
Generic Human Readable Descriptions for k8s API Objects

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#30413]
While storage-SIG was discussing dynamic provisioning, we found a need for a description field on a new API object. It would be a human readable description for the object. @thockin proposed that instead of adding an explicit first-class description field for a specific object, why not have an annotation with a known key (`k8s.io/description`?) that can be added to any API object. `kubectl describe` could be modified to print this field if it was present on any object. 

CC @eparis @thockin @matchstick @kubernetes/kube-api @kubernetes/sig-storage

**Comment by bgrant0607** [comment]
@saad-ali Try kubectl explain.

**Comment by bgrant0607** [comment]
If for a specific object rather than a type, I suggest `description`, which I believe Openshift is already using.

**Comment by bgrant0607** [comment]
@saad-ali Actually, see:
https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/deploy.md#deployment-version

cc @janetkuo

**Comment by spiffxp** [comment]
/sig api-machinery
/sig storage
because these sigs were mentioned in the description

**Comment by jingxu97** [comment]
@saad-ali is this still an issue? can we close it?

**Comment by bgrant0607** [comment]
I think this is redundant with #11485
