### ISSUE TITLE
Container configuration not correct for node-e2e-test

### ISSUE THREAD

**Issue by coufon** [kubernetes/kubernetes#30412]
In node-e2e-test on Containervm image, the containers of the pods created by Kubernetes are subcontainers of docker-daemon/docker/.

It means that the runtime resource usage (docker-daemon) is not correct, because all pods are included.

This problem maybe due to container misconfiguration in node-e2e-test.

**Comment by coufon** [comment]
@dchen1107

**Comment by dchen1107** [comment]
The kubelet on debian-based containervm image is misconfigured. Will fix it shortly.
