### ISSUE TITLE
Ubuntu 14.04 and kubernets 1.3.4 make release (error)

### ISSUE THREAD

**Issue by fogongzi** [kubernetes/kubernetes#30422]
When I make release with kubernets 1.3.4, it failed and the logs are as follows:
build/release.sh
+++ [0811 10:03:00] Verifying Prerequisites....
+++ [0811 10:03:14] Building Docker image kube-build:build-b6a8285154.
+++ [0811 10:03:27] Running build command....
Go version: go version go1.4.2 linux/amd64
+++ [0811 10:03:28] Multiple platforms requested and available 15G >= threshold 11G, building platforms in parallel
+++ [0811 10:03:28] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
hack/cmd/teststale/teststale.go:34:2: cannot find package "github.com/golang/glog" in any of:
        /usr/src/go/src/github.com/golang/glog (from $GOROOT)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/golang/glog (from $GOPATH)
!!! Error in /go/src/k8s.io/kubernetes/hack/lib/golang.sh:428
  'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${goldflags}" "${binaries[@]:+${binaries[@]}}"' exited with status 1
Call stack:
  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:428 kube::golang::build_kube_toolchain(...)
  2: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:643 kube::golang::build_binaries(...)
  3: hack/build-cross.sh:28 main(...)
Exiting with status 1
!!! Error in /go/src/k8s.io/kubernetes/hack/lib/golang.sh:587
  '( kube::golang::setup_env; echo "Go version: $(go version)"; local host_platform; host_platform=$(kube::golang::host_platform); local goflags goldflags; eval "goflags=(${KUBE_GOFLAGS:-})"; goldflags="${KUBE_GOLDFLAGS:-} $(kube::version::ldflags)"; local use_go_build; local -a targets=(); local arg; for arg in "$@";
do
    if [[ "${arg}" == "--use_go_build" ]]; then
        use_go_build=true;
    else
        if [[ "${arg}" == -\* ]]; then
            goflags+=("${arg}");
        else
            targets+=("${arg}");
        fi;
    fi;
done; if [[ ${#targets[@]} -eq 0 ]]; then
    targets=("${KUBE_ALL_TARGETS[@]}");
fi; local -a platforms=("${KUBE_BUILD_PLATFORMS[@]:+${KUBE_BUILD_PLATFORMS[@]}}"); if [[ ${#platforms[@]} -eq 0 ]]; then
    platforms=("${host_platform}");
fi; local binaries; binaries=($(kube::golang::binaries_from_targets "${targets[@]}")); local parallel=false; if [[ ${#platforms[@]} -gt 1 ]]; then
    local gigs; gigs=$(kube::golang::get_physmem); if [[ ${gigs} -ge ${KUBE_PARALLEL_BUILD_MEMORY} ]]; then
        kube::log::status "Multiple platforms requested and available ${gigs}G >= threshold ${KUBE_PARALLEL_BUILD_MEMORY}G, building platforms in parallel"; parallel=true;
    else
        kube::log::status "Multiple platforms requested, but available ${gigs}G < threshold ${KUBE_PARALLEL_BUILD_MEMORY}G, building platforms in serial"; parallel=false;
    fi;
fi; kube::golang::build_kube_toolchain; if [[ "${parallel}" == "true" ]]; then
    kube::log::status "Building go targets for ${platforms[@]} in parallel (output will appear in a burst when complete):" "${targets[@]}"; local platform; for platform in "${platforms[@]}";
    do
        ( kube::golang::set_platform_envs "${platform}"; kube::log::status "${platform}: go build started"; kube::golang::build_binaries_for_platform ${platform} ${use_go_build:-}; kube::log::status "${platform}: go build finished" ) &> "/tmp//${platform//\//_}.build" &
    done; local fails=0; for job in $(jobs -p);
    do
        wait ${job} || let "fails+=1";
    done; for platform in "${platforms[@]}";
    do
        cat "/tmp//${platform//\//_}.build";
    done; exit ${fails};
else
    for platform in "${platforms[@]}";
    do
        kube::log::status "Building go targets for ${platform}:" "${targets[@]}"; kube::golang::set_platform_envs "${platform}"; kube::golang::build_binaries_for_platform ${platform} ${use_go_build:-};
    done;
fi )' exited with status 1
Call stack:
  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:587 kube::golang::build_binaries(...)
  2: hack/build-cross.sh:28 main(...)
Exiting with status 1
!!! Error in build/../build/common.sh:620
  '"${docker_cmd[@]}" "$@"' exited with status 1
Call stack:
  1: build/../build/common.sh:620 kube::build::run_build_command(...)
  2: build/release.sh:33 main(...)
Exiting with status 1
make: **\* [release] Error 1

**Comment by xiangpengzhao** [comment]
Since this was encountered in v1.3.4 and most probably due to local dev env settings, we are closing this issue.

@thockin
