### ISSUE TITLE
Consider exposing petset index via downward api

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#30427]
While it's easy enough to get through something like:
`IFS='-' read -ra LIST <<< "$POD_NAME"; INDEX=${LIST[1]}`
It requires a custom entrypoint. If the ordinal index is a common part of 12 fa apps we should just expose it more naturally through the downward api. 

ref https://github.com/kubernetes/kubernetes/issues/30256
@tobegit3hub

**Comment by nhlfr** [comment]
I'm going to work on this.

**Comment by bprashanth** [comment]
@kubernetes/api-review-team @pmorie who to tag for downward api requests? 
@smarterclayton out of petset interest

**Comment by smarterclayton** [comment]
I agree that this is useful, although we need to be careful about how to
expose it.

**Comment by nhlfr** [comment]
I'd suggest to keep a petset UID in pod annotation (i.e. `pod.beta.kubernetes.io/petset`) and then pass it through downward API.

**Comment by smarterclayton** [comment]
It would need to be available via environment as well.

**Comment by nhlfr** [comment]
Of course. What I'm proposing is:

* applying `pod.beta.kubernetes.io/petset-index` annotation with pet set index to any pods created during pets creation
* adding `dependencies.petSetIndex` label which may be used for environment downward API
* using the info from `pod.beta.kubernetes.io/petset-index` annotation to fill up the env with `dependencies.petSetIndex` field reference

**Comment by nhlfr** [comment]
Due to discussion in PR, I decided to make an another issue about exposing annotations via downward API - #31218

In my PR, which is referring to this issue, I will only put an annotation with petset index on dependent pods. Then the general downward API for all annotations will make this petset index accessible.

I decided to use annotations, because I (and probably @smarterclayton ) think that we shoud'nt add any fields to Pod in case of alpha/beta features like petsets.

**Comment by alexouzounis** [comment]
is there a workaround for this currently ? If we don't want to change the entry point that is.

**Comment by smarterclayton** [comment]
You can expose pod name via the downward API.

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/issues/30427#issue-170571928, you can even replace POD_NAME with $(hostname) if you're using statefulset (aka petset)

**Comment by alexouzounis** [comment]
yeah - we are using PetSet and what we what is just the ordinal exposed in an environment variable i.e. `0`, `1` etc. The pod name will be something like `web-0`.

**Comment by nhlfr** [comment]
Sorry for leaving this issue without any action. PTAL on the issue #31218. It will surely not be touched in 1.5 release, but I've submitted a proposal to be considered for a future release.

**Comment by jberkus** [comment]
+1 on this feature, regardless of how it's implemented.  Currently I'm parsing the pod name, which is awkward and fragile.

**Comment by alexouzounis** [comment]
Indeed - we ended doing the same as a postStart lifecycle hook to avoid modifying the docker image

**Comment by smarterclayton** [comment]
@pmorie as we discussed we need to fully specify the downward API for
complex fields (annotations and labels) and get that over the review hump
in 1.6 so people can use an annotation in an env var.  @liggitt too maybe.

**Comment by rideswitch** [comment]
I write jinja templates to generate the k8s yamls so that I can make them do what I need to do.  It is making me wonder if maybe a more generalized templating solution would be good for kubernetes/kubectl.  Better to expose via downward than nothing, but maybe it would be better if the whole template supported variables, or even was in jinja2 or something.

**Comment by alon-argus** [comment]
@rideswitch I'm not sure how it's related to this issue, but check out [Helm](https://github.com/kubernetes/helm)

**Comment by phutchins** [comment]
This would be extremely helpful for me as well. I have the need to reach the pods in a statefulset by a unique address and this would allow me to create a selector based on their ordinalIndex. There are a few additional features that would be useful in making this happen also of course...

**Comment by nhlfr** [comment]
#41648 is the first step which is needed for implementing that. The proposal regarding that functionality (kubernetes/community#147) is implemented though.

**Comment by mikesparr** [comment]
Until this feature is available, I found a way to get the ordinal index into the container using lifecycle hooks `postStart` in case this helps anyone.

```
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "export KAFKA_BROKER_ID=${HOSTNAME##*-}"]
```

**Comment by jberkus** [comment]
Hmmm, need to test if the 1.10 change fulfills this issue.

**Comment by krmayankk** [comment]
what change @jberkus  ? Is the index available in 1.10 as downward api ?

**Comment by yunghoy** [comment]
Do you have any big news about the topic?

**Comment by JustinZ** [comment]
Any updates ?

**Comment by krmayankk** [comment]
@kow3ns is this already supported ? I would like to work on this and fix it ?

**Comment by jberkus** [comment]
/remove-lifecycle stale

There is a WIP PR for this.

**Comment by Aisuko** [comment]
Is there any updates?

**Comment by jberkus** [comment]
This issue has an active PR.

/remove-lifecycle rotten

**Comment by jberkus** [comment]
/remove-lifecycle rotten

This issue has an active PR

**Comment by bohdantverdyi** [comment]
/remove-lifecycle rotten

This issue has an active PR
