### ISSUE TITLE
[hack] GOROOT not always set correctly for other distros when running hack/update-all.sh

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/kubernetes#30444]
Running ./hack/update-all.sh on F23 with go-1.6.2. Two things can happen:

1. the command hangs on ``update-generated-protobuf.sh``, more precisely on running Makefile
1. the command fails on "could not import fmt" as it searches ``/usr/lib/golang`` instead of ``/usr/local/golang``.

Quick hack is to update ``hack/lib/golang.sh``:

```sh
--- a/hack/lib/golang.sh
+++ b/hack/lib/golang.sh
@@ -353,6 +353,9 @@ kube::golang::setup_env() {
 
   # This seems to matter to some tools (godep, ugorji, ginkgo...)
   export GO15VENDOREXPERIMENT=1
+  if [ -d /usr/local/golang ]; then
+    export GOROOT=/usr/local/golang
+  fi
 }
 
 # This will take binaries from $GOPATH/bin and copy them to the appropriate
```

And run the command as ``GOROOT=/usr/lib/golang ./hack/update-all.sh``.

The go-1.6.2 is installed from Fedora rpms.

**Comment by dims** [comment]
cc @thockin

**Comment by nhlfr** [comment]
I'd suggest to make a check where the `go` command is installed and make a PREFIX assumption based on that. I see no reason why we should hardcode `/usr/local/golang`, there is probably no distro with package contents like that. If someone has Go installed in `/usr/local`, we should just detect that fact correctly.

**Comment by thockin** [comment]
I commited a fix a couple days ago to set GOROOT if it was not set.  Does this still fail at current head?

**Comment by thockin** [comment]
in fact, please reopen if it does.  I am THAT confident :)

**Comment by ingvagabund** [comment]
Looking good. Thanks.
