### ISSUE TITLE
Reduce flickering in pod nanny

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#30446]
Currently there are bidirectional tipping points, for example 16, after crossing which the pod is restarted. So if whenever node number goes from 15->17 or 17->15 the pod is restarted. The tipping points should be more separated. 15 -> 17 can trigger a restart but another restart should be rather around 12 (13->11).

cc: @Q-Lee @piosz

**Comment by Q-Lee** [comment]
Sorry, 1.4 feature work + oncall has kept me pretty busy. I'll take a look tomorrow.

**Comment by goltermann** [comment]
@Q-Lee @mwielgus any updates?  is this one needed for 1.4?

**Comment by Q-Lee** [comment]
I doubt this will land for 1.4, and I wouldn't consider it blocking.

**Comment by dims** [comment]
switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree)

**Comment by fgrzadkowski** [comment]
@Q-Lee @mwielgus what's the status here? Is it still an issue?

**Comment by piosz** [comment]
@fgrzadkowski yes, though no progress on it so far. Looks like a good starter project.

**Comment by fgrzadkowski** [comment]
It doesn't seem like a blocker.

**Comment by marun** [comment]
Assuming this shouldn't block 1.7, moving to 1.8.

**Comment by mwielgus** [comment]
Fixed with https://github.com/kubernetes/autoscaler/issues/128
