### ISSUE TITLE
Create `kube` CLI wrapper

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#30450]
We should have a kube CLI wrapper, that does git style multi-dispatch to various commands.

This would allow third party resources to have an "integrated" CLI, and provide a separation such that we could support updating (like gcloud).

Initially, we need not split out anything: core commands could continue to be in `kubectl` / `kube`, but if you typed `kube get widgets` we could check for the existence of a `kube-get-widgets` executable in a well-known location.

Per discussions in @kubernetes/sig-cluster-lifecycle

**Comment by dgoodwin** [comment]
:+1:  and if it's just dispatching I would assume we can avoid the overheard associated with initialization for some heavy handed commands, when we want a lightweight one.

**Comment by dgoodwin** [comment]
How many binaries would we be wrapping? The ones I'm aware of:

- hyperkube
- kubectl
- kubelet
- kube-proxy
- kube-apiserver
- kube-controller-manager
- kube-scheduler

Any others I've missed?

Is my assumption that kubectl is far and away the most frequently invoked command, thus perhaps we could give it some precedence here and shorten it's commands up a little. We would probably have to be a little more explicit in terms of what we'll redirect, and if nothing matches assume to try to pass it to kubectl.

i.e. 'kube get pods' redirects to 'kubectl get pods'

Other examples:
- kube apiserver -> hyperkube apiserver or kube-apiserver
- kube init -> wherever the new init/join commands are going to live.

Would kubelet fit into this or just be left out?

**Comment by mikedanese** [comment]
This would be ambiguous if we allow multiple levels of spaces? e.g. does `kube kubectl get pod foobang` call exec `kube-kubectl get pod foobang` or `kube-kubectl-get-pod-foobang` or something in the middle? I guess we could search by some priority.... but that's kind of gross. I like one level.

**Comment by bgrant0607** [comment]
See #30086, #13606

cc @smarterclayton @fabianofranz

**Comment by fabianofranz** [comment]
Yes, this is very similar to how it's being proposed in https://github.com/kubernetes/kubernetes/pull/30086. Should we move all discussions there?

**Comment by smarterclayton** [comment]
Yes, I think #30086 can also encompass a hypothetical `kube` command in the future.

**Comment by justinsb** [comment]
I agree we should probably move to #30086 - thanks for the pointer!
