### ISSUE TITLE
Unable to load build details

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#30454]
Some failures apparently lose their logs:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/29945/kubernetes-pull-build-test-e2e-gke/6015/

@fejta @ixdy @spxtr

**Comment by ixdy** [comment]
Lots of `AccessDeniedException: 403 Forbidden` in the Jenkins log. I think this was when we were still teasing out some service account bucket ACLs.
