### ISSUE TITLE
Nodes under pressure can't update service routing 

### ISSUE THREAD

**Issue by hubt** [kubernetes/kubernetes#30459]
I believe I’m having an intermittent but serious problem which can be described as:
1. hot pods with incorrect CPU/memory limits can cause a node to run out of memory/cpu.
2. node becomes generally unresponsive for most processes(ssh, kubelet, kube-proxy), but is still able to route traffic.
3. kube-proxy is unable to update properly causing routing to be inconsistent with the desired state(especially with many highly dynamic services).
4. node starts routing traffic to incorrect pods because of inconsistency.
5. random pods receive improperly routed traffic.

I am running v1.2.1 with iptables on AWS using kube-up.sh.

My current hack is to detect unresponsive nodes and terminate them, but that is reactive and slow.

I understand I should set better cpu/memory limits, but there is always the possibility of a pod that swamps a node, so that isn’t a permanent solution.

Perhaps the solution is to have kube-proxy and kubelet run with a high enough priority such that they are guaranteed to run.

Thoughts from slack chat with @justinsb 
- We should also look at not reusing pod ips, so the traffic will be dropped (i.e. never misroute) - it sounds like we're not doing that
- And then we should look at detecting dropped packets and using that to remove iptables routes maybe.
- We could stop routing if we were totally out of date with the control plane, but that would probably be a cascading failure

**Comment by timstoop** [comment]
We're having this problem as well, generally right after a deploy in several environments, where traffic gets routed to incorrect Pods. It generally fixes itself within a few minutes and only a few requests are actually misdirected, but with a large-ish volume of requests (100/s), this can still be a significant portion of the traffic.

We're running on AWS as well, but deployed from scratch (on CoreOS). Using Kubernetes 1.4.8 currently. Please let me know if there's any other info we can provide here to help you debug this issue.
