### ISSUE TITLE
Unit tests fail with no info (glog.Fatal?)

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#30452]
e.g.

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/30383/kubernetes-pull-test-unit-integration/38902/build-log.txt

I believe this is because we have some places in the code where we `glog.Fatal`, we should probably never do that.  But I'm not positive.

**Comment by spiffxp** [comment]
/sig testing
/assign
closing this because the linked example now 404's; if there are concrete examples, we can re-open and triage to other sigs as appropriate
