### ISSUE TITLE
Cloud Provider Openstack:  LBaaS V2/V1 supports single load balancer port

### ISSUE THREAD

**Issue by dagnello** [kubernetes/kubernetes#30477]
LBaaS implementation (v1 or v2) will not support services that require to load balancer more than one port.

**Comment by anguslees** [comment]
Fixed for LBaaS v2 by https://github.com/kubernetes/kubernetes/pull/30649.

I suspect LBaaS v1 can't support multiple ports (not sure if reusing the VIP across multiple loadbalancers is a universally supported thing).  I also believe LBaaS v1 is also mostly gone in favour of v2 in deployments so trying to address this in v1 is extremely low priority unless someone steps forward to ask for it.

So: I think we can close this bug now, but I lack the powers to do that directly.

**Comment by dagnello** [comment]
@anguslees thank you for the update.
