### ISSUE TITLE
Pod selection somewhat sticky

### ISSUE THREAD

**Issue by rwillard** [kubernetes/kubernetes#30484]
I have a multi-zone cluster on GKE, and I'm having a problem with the load balancer being sticky on pod selection. 

I have an ingress setup, serving traffic to a kong deployment. It's managing my APIs, and sends requests to other deployments on my cluster using the internal load balancer (service.namespace.svc.cluster.local).

One of my deployments' functions is to handle a POST request by parsing it into 5 smaller batches and sending each of those to another deployment using the internal load balancer (service.namespace.svc.cluster.local). What I want, and the behavior I expected, is for different pods in that second deployment to serve those requests. Instead, via the logs, I've figured out that one pod is serving all 5 of the requests. I don't have any session affinity settings in my service files, so those should be set to none. I'm using the default kube-proxy setup through GKE.

How can I get multiple pods to serve those 5 requests, instead of 1?

**Comment by etki** [comment]
I'm not a part of kubernetes team or iptables expert, but, i guess, as long as you hold balanced TCP connection opened, all packets will go in one direction. If that's correct, you have to make sure connection got closed before sending next batch.

**Comment by rwillard** [comment]
You're absolutely right, thank you. Thanks for your help.

**Comment by rwillard** [comment]
Code's been modified to not keep the connection alive, but still having this issue. Sending Connection: 'close' in the headers.

**Comment by thockin** [comment]
There's nothing in the iptables logic that would do this - it HAS to be in your client (e.g. Go reuses connections).  We literally have tests that demonstrate that a service LB (iptables) hits all endpoints.

**Comment by thockin** [comment]
Oh, this is ancient.  Closing now, reopen if needed. :)
