### ISSUE TITLE
Improve `kubectl config` wrt context

### ISSUE THREAD

**Issue by saturnism** [kubernetes/kubernetes#30481]
Use case:
What are all of the contexts I can use? Today, I need to browse the entire yaml, grep by name, and/or other piped tricks.

Propose something to make that easier:
`kubectl config list-context` to list just the name of the contexts

Use case:
Some of the auto-generated context names can be very long. I want to rename and shorten it. Today requires editing the config file manually.

Propose something to make it easier:
`kubectl config rename-context`

**Comment by vreon** [comment]
https://github.com/kubernetes/kubernetes/issues/29794#issuecomment-236813523

**Comment by pwittrock** [comment]
Closing per @vreon 's comment
