### ISSUE TITLE
Pod on master can't access apiserver.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#30491]
With https://github.com/kubernetes/node-problem-detector/pull/29, node problem detector will not use `hostNetwork` any more.

However, when I start new node problem detector in the cluster, I found that the pod on master can't access apiserver via "10.0.0.1:443" - `Get https://10.0.0.1:443/api/v1/namespaces/kube-system/pods/node-problem-detector-v0.2-lqewd: dial tcp 10.0.0.1:443: i/o timeout`.
The pods on nodes work well.

Is this WAI?
/cc @kubernetes/sig-network

**Comment by bprashanth** [comment]
Yes. Thats a service ip and kubeproxy isn't running on the master.

**Comment by Random-Liu** [comment]
@bprashanth Hm, thanks for answering. If so, I should find a way to prevent node problem detector from running on master. We wanted to do that long time ago but scheduler didn't support it at that time. Hope https://github.com/kubernetes/kubernetes/pull/28803 could help.

Close this one.

**Comment by thockin** [comment]
either run in host network or don't run on master.

**Comment by Random-Liu** [comment]
> either run in host network or don't run on master.

@thockin OK. Thanks for your suggestion. :)

**Comment by Random-Liu** [comment]
@kubernetes/sig-scheduling Is there a way to schedule daemonset only on nodes? (non-master)

**Comment by bprashanth** [comment]
Use affinity/selectors? http://kubernetes.io/docs/admin/daemons/#running-pods-on-only-some-nodes

**Comment by Random-Liu** [comment]
@bprashanth It seems that there is no built-in labels to distinguish master and node https://github.com/kubernetes/kubernetes.github.io/blob/release-1.3/docs/user-guide/node-selection/index.md#built-in-node-labels.
I don't think we want to use whether the node name contains "master" or "minion" to figure out that. :)

**Comment by bprashanth** [comment]
Just add it? kubelet knows when it's running headless anyway right?

**Comment by bprashanth** [comment]
By "headless" i meant running on the master
