### ISSUE TITLE
KUBE_MANIFESTS_TAR_URL error

### ISSUE THREAD

**Issue by wayarmy** [kubernetes/kubernetes#30495]
hello, when i downloaded "script auto setup" and ran it to create cluster on AWS, and got this error:
./cluster/../cluster/../cluster/aws/../../cluster/common.sh: line 518: KUBE_MANIFESTS_TAR_URL: unbound variable

I don't see this on older version, and don't know variable "KUBE_MANIFESTS_TAR_URL", does anyone explain this ?.

Thanks so much!!

**Comment by gene-telligent** [comment]
The problems seem to stem from this commit:
https://github.com/kubernetes/kubernetes/commit/14b16628f87c71715e6264be9ca6d48161857196

and was fixed here (which hasn't made it into the current release!)
https://github.com/kubernetes/kubernetes/commit/49da8298c9fe77f28243b082f0b77ef5bffd4293

A workaround is to manually apply that second commit -- edit the cluster/aws/config-default.sh file and rename the variables KUBE_MASTER_OS_DISTRIBUTION and KUBE_NODE_OS_DISTRIBUTION to MASTER_OS_DISTRIBUTION and NODE_OS_DISTRIBUTION respectively.

Still is a pain, and is currently breaking cluster deployment since find-release-tars fails!

**Comment by sundarams73tech** [comment]
+1

**Comment by sundarams73** [comment]
+1

**Comment by im-di** [comment]
This commit not resolve the problem: https://github.com/kubernetes/kubernetes/commit/49da8298c9fe77f28243b082f0b77ef5bffd4293
As temporary workaround:
`KUBE_MANIFESTS_TAR_URL="${SERVER_BINARY_TAR_URL/server-linux-amd64/manifests}"`
In cluster/common.sh:516
```
  local master=$1
  local file=$2
  KUBE_MANIFESTS_TAR_URL="${SERVER_BINARY_TAR_URL/server-linux-amd64/manifests}"
  local server_binary_tar_url=$SERVER_BINARY_TAR_URL
  local salt_tar_url=$SALT_TAR_URL
  local kube_manifests_tar_url=$KUBE_MANIFESTS_TAR_URL
  if [[ "${master}" == "true" && "${MASTER_OS_DISTRIBUTION}" == "coreos" ]] || \
     [[ "${master}" == "false" && "${NODE_OS_DISTRIBUTION}" == "coreos" ]] ; then
    # TODO: Support fallback .tar.gz settings on CoreOS
    server_binary_tar_url=$(split_csv "${SERVER_BINARY_TAR_URL}")
    salt_tar_url=$(split_csv "${SALT_TAR_URL}")
    kube_manifests_tar_url=$(split_csv "${KUBE_MANIFESTS_TAR_URL}")
  fi
```

**Comment by ianjamez** [comment]
Also saw: 
./cluster/../cluster/../cluster/aws/../../cluster/common.sh: line 522: MASTER_OS_DISTRIBUTION: unbound variable
Added:
MASTER_OS_DISTRIBUTION="${KUBE_MASTER_OS_DISTRIBUTION}"
Then:
./cluster/../cluster/../cluster/aws/../../cluster/common.sh: line 528: NODE_OS_DISTRIBUTION: unbound variable
Added:
NODE_OS_DISTRIBUTION="${KUBE_NODE_OS_DISTRIBUTION}"

**Comment by gloewy** [comment]
Did any of these suggestions work for anyone?
I am still seeing the same error message regardless of these changes.

**Comment by ianjamez** [comment]
Yes, fixed it for me. I ended up with:
`  local master=$1
  local file=$2
  KUBE_MANIFESTS_TAR_URL="${SERVER_BINARY_TAR_URL/server-linux-amd64/manifests}"
  MASTER_OS_DISTRIBUTION="${KUBE_MASTER_OS_DISTRIBUTION}"
  NODE_OS_DISTRIBUTION="${KUBE_NODE_OS_DISTRIBUTION}"
  local server_binary_tar_url=$SERVER_BINARY_TAR_URL
  local salt_tar_url=$SALT_TAR_URL
  local kube_manifests_tar_url=$KUBE_MANIFESTS_TAR_URL
  if [[ "${master}" == "true" && "${MASTER_OS_DISTRIBUTION}" == "coreos" ]] || \
     [[ "${master}" == "false" && "${NODE_OS_DISTRIBUTION}" == "coreos" ]] ; then
    # TODO: Support fallback .tar.gz settings on CoreOS
    server_binary_tar_url=$(split_csv "${SERVER_BINARY_TAR_URL}")
    salt_tar_url=$(split_csv "${SALT_TAR_URL}")
    kube_manifests_tar_url=$(split_csv "${KUBE_MANIFESTS_TAR_URL}")
  fi`

That script downloads and creates the kubernetes folder that has common.sh. If you run it again from a different location it does it again so make sure you're using the corrected common.sh.
Set 
`export KUBERNETES_SKIP_DOWNLOAD=true`
to avoid redownloading.

**Comment by discostur** [comment]
Inserting the variables @ianjamez provided gives me the following error:

**common.sh:**
```bash
# $1: if 'true', we're building a master yaml, else a node
function build-kube-env {
  local master=$1
  local file=$2
  KUBE_MANIFESTS_TAR_URL="${SERVER_BINARY_TAR_URL/server-linux-amd64/manifests}"
  MASTER_OS_DISTRIBUTION="${KUBE_MASTER_OS_DISTRIBUTION}"
  NODE_OS_DISTRIBUTION="${KUBE_NODE_OS_DISTRIBUTION}"
  local server_binary_tar_url=$SERVER_BINARY_TAR_URL
  local salt_tar_url=$SALT_TAR_URL
  local kube_manifests_tar_url="${KUBE_MANIFESTS_TAR_URL:-}"
  if [[ "${master}" == "true" && "${MASTER_OS_DISTRIBUTION}" == "coreos" ]] || \
     [[ "${master}" == "false" && "${NODE_OS_DISTRIBUTION}" == "coreos" ]] ; then
    # TODO: Support fallback .tar.gz settings on CoreOS
    server_binary_tar_url=$(split_csv "${SERVER_BINARY_TAR_URL}")
    salt_tar_url=$(split_csv "${SALT_TAR_URL}")
    kube_manifests_tar_url=$(split_csv "${KUBE_MANIFESTS_TAR_URL}")
  fi
```

**error:**
```
Creating a kubernetes on aws...
... Starting cluster in us-west-2a using provider aws
... calling verify-prereqs
... calling kube-up
Starting cluster using os distro: jessie
!!! Cannot find kubernetes-server-linux-amd64.tar.gz
```

**Comment by raskolnikov7** [comment]
./cluster/../cluster/../cluster/aws/../../cluster/common.sh: line 518: KUBE_MANIFESTS_TAR_URL: unbound variable

Same problem here .. i tried both downloading the zip archive as well as 
export KUBERNETES_PROVIDER=YOUR_PROVIDER; wget -q -O - https://get.k8s.io | bash

**Comment by bjfr** [comment]
I get the same error:

Generating certs for alternate-names: IP:52.41.117.12,IP:172.20.0.4,IP:10.0.0.1,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster.local,DNS:kubernetes-master
./cluster/../cluster/../cluster/aws/../../cluster/common.sh: line 518: KUBE_MANIFESTS_TAR_URL: unbound variable

Installation using:
export KUBERNETES_PROVIDER=aws; curl -sS https://get.k8s.io | bash

**Comment by raskolnikov7** [comment]
Hi,
Please try below : 

https://github.com/kubernetes/kubernetes/commit/49da8298c9fe77f28243b082f0b77ef5bffd4293

and then In your_kubernetes_install_dir/cluster/common.sh:516

add below line 
KUBE_MANIFESTS_TAR_URL="${SERVER_BINARY_TAR_URL/server-linux-amd64/manifests}"

**Comment by lzerma** [comment]
That worked for me @raskolnikov7 thanks!

I followed exactly what @raskolnikov7 have said and works.

**Comment by scottstensland** [comment]
I can confirm when using 

    KUBERNETES_PROVIDER aws

error happens for both releases 1.3.5  and 1.3.6  

/root/kubernetes/cluster/../cluster/../cluster/aws/../../cluster/common.sh: line 518: KUBE_MANIFESTS_TAR_URL: unbound variable

however release 1.3.4 is OK

**Comment by bjfr** [comment]
@discostur solution worked for me, adding  the following three lines at line 516 in commons.sh (release 1.3.5)

KUBE_MANIFESTS_TAR_URL="${SERVER_BINARY_TAR_URL/server-linux-amd64/manifests}"
MASTER_OS_DISTRIBUTION=${KUBE_MASTER_OS_DISTRIBUTION:-debian}
NODE_OS_DISTRIBUTION=${KUBE_NODE_OS_DISTRIBUTION:-debian}

**Comment by damienjoldersma** [comment]
I tried a variety of efforts at line 516, I think it is a poor way to describe where to make a fix. What worked for me was @ianjamez solution, thanks for providing context, as the line 516 seemed to be outside of that  build-kube-env function.

**Comment by monajalal** [comment]
Got this error on Ubuntu 15.04 instances on EC2 m4.4xlarge:
```
ubuntu@ip-172-31-55-180:~$ export KUBERNETES_PROVIDER=aws; wget -q -O - https://get.k8s.io | bash
....
./cluster/../cluster/../cluster/aws/../../cluster/common.sh: line 528: KUBE_MANIFESTS_TAR_URL: unbound variable
ubuntu@ip-172-31-55-180:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
ubuntu@ip-172-31-55-180:~$ uname -a
Linux ip-172-31-55-180 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by Deshke** [comment]
still broken

```bash
root@ip-172-31-1-109:~# export KUBERNETES_PROVIDER=aws; curl -sS https://get.k8s.io | bash
Downloading kubernetes release v1.3.6 to /root/kubernetes.tar.gz
--2016-09-01 15:39:02--  https://storage.googleapis.com/kubernetes-release/release/v1.3.6/kubernetes.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 216.58.211.48, 2a00:1450:4001:815::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|216.58.211.48|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1488182774 (1.4G) [application/x-tar]
Saving to: ‘kubernetes.tar.gz’

kubernetes.tar.gz                                           100%[==========================================================================================================================================>]   1.39G  92.0MB/s    in 17s     

2016-09-01 15:39:20 (85.2 MB/s) - ‘kubernetes.tar.gz’ saved [1488182774/1488182774]

Unpacking kubernetes release v1.3.6
Creating a kubernetes on aws...
... Starting cluster in us-west-2a using provider aws
... calling verify-prereqs
... calling kube-up
Starting cluster using os distro: jessie
Uploading to Amazon S3
Creating kubernetes-staging-foobargna
make_bucket: s3://kubernetes-staging-foobargna/
Confirming bucket was created...
+++ Staging server tars to S3 Storage: kubernetes-staging-foobargna/devel
upload: ../../tmp/kubernetes.BSr4kE/s3/bootstrap-script to s3://kubernetes-staging-foobargna/devel/bootstrap-script
upload: ../../tmp/kubernetes.BSr4kE/s3/kubernetes-salt.tar.gz to s3://kubernetes-staging-foobargna/devel/kubernetes-salt.tar.gz
upload: ../../tmp/kubernetes.BSr4kE/s3/kubernetes-server-linux-amd64.tar.gz to s3://kubernetes-staging-foobargna/devel/kubernetes-server-linux-amd64.tar.gz
Uploaded server tars:
  SERVER_BINARY_TAR_URL: https://s3.amazonaws.com/kubernetes-staging-foobargna/devel/kubernetes-server-linux-amd64.tar.gz
  SALT_TAR_URL: https://s3.amazonaws.com/kubernetes-staging-foobargna/devel/kubernetes-salt.tar.gz
  BOOTSTRAP_SCRIPT_URL: https://s3.amazonaws.com/kubernetes-staging-foobargna/devel/bootstrap-script

An error occurred (NoSuchEntity) when calling the GetInstanceProfile operation: Instance Profile kubernetes-master cannot be found.
Creating master IAM profile: kubernetes-master
Creating IAM role: kubernetes-master
Creating IAM role-policy: kubernetes-master
Creating IAM instance-policy: kubernetes-master
Adding IAM role to instance-policy: kubernetes-master

An error occurred (NoSuchEntity) when calling the GetInstanceProfile operation: Instance Profile kubernetes-minion cannot be found.
Creating minion IAM profile: kubernetes-minion
Creating IAM role: kubernetes-minion
Creating IAM role-policy: kubernetes-minion
Creating IAM instance-policy: kubernetes-minion
Adding IAM role to instance-policy: kubernetes-minion
Generating public/private rsa key pair.
Your identification has been saved in /root/.ssh/kube_aws_rsa.
Your public key has been saved in /root/.ssh/kube_aws_rsa.pub.
The key fingerprint is:
SHA256:kXrCTyLzGa8kGJ/8p7xdONNTlZOk1Zty61fJGUhCrFw root@ip-172-31-1-109
The key's randomart image is:
+---[RSA 2048]----+
|          o.  o. |
|         . E = o.|
|        + o + * o|
|     . . +   + * |
|  . o * S   . + =|
|   = = X o .   =.|
|  . = + * +   . .|
|     = o.+ .   ..|
|      *+.       .|
+----[SHA256]-----+
Using SSH key with (AWS) fingerprint: SHA256:kXrCTyLzGa8kGJ/8p7xdONNTlZOk1Zty61fJGUhCrFw
Creating vpc.
Adding tag to vpc-de84bbba: Name=kubernetes-vpc
Adding tag to vpc-de84bbba: KubernetesCluster=kubernetes
Using VPC vpc-de84bbba
Adding tag to dopt-6d19af09: Name=kubernetes-dhcp-option-set
Adding tag to dopt-6d19af09: KubernetesCluster=kubernetes
Using DHCP option set dopt-6d19af09
Creating subnet.
Adding tag to subnet-2db29149: KubernetesCluster=kubernetes
Using subnet subnet-2db29149
Creating Internet Gateway.
Using Internet Gateway igw-6cfb2408
Associating route table.
Creating route table
Adding tag to rtb-14e31373: KubernetesCluster=kubernetes
Associating route table rtb-14e31373 to subnet subnet-2db29149
Adding route to route table rtb-14e31373
Using Route Table rtb-14e31373
Creating master security group.
Creating security group kubernetes-master-kubernetes.
Adding tag to sg-b236d8cb: KubernetesCluster=kubernetes
Creating minion security group.
Creating security group kubernetes-minion-kubernetes.
Adding tag to sg-aa36d8d3: KubernetesCluster=kubernetes
Using master security group: kubernetes-master-kubernetes sg-b236d8cb
Using minion security group: kubernetes-minion-kubernetes sg-aa36d8d3
Creating master disk: size 20GB, type gp2
Adding tag to vol-5c0be2d4: Name=kubernetes-master-pd
Adding tag to vol-5c0be2d4: KubernetesCluster=kubernetes
Allocated Elastic IP for master: some.generic.aws.ip
Adding tag to vol-5c0be2d4: kubernetes.io/master-ip=some.generic.aws.ip
Generating certs for alternate-names: IP:some.generic.aws.ip,IP:172.20.0.9,IP:10.0.0.1,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster.local,DNS:kubernetes-master
./cluster/../cluster/../cluster/aws/../../cluster/common.sh: line 528: KUBE_MANIFESTS_TAR_URL: unbound variable
```

**Comment by JoeyZwicker** [comment]
We ran into this issue as well (we ended up here after following the kubernetes guide at http://kubernetes.io/docs/getting-started-guides/aws/)

For us this was particularly confusing because the script emitted this error and then told us the installation was successful:

```
$ export KUBERNETES_PROVIDER=aws; curl -sS https://get.k8s.io | bash
Downloading kubernetes release v1.3.6 to /Users/joeyzwicker/kubernetes/cluster/aws/kubernetes.tar.gz
...
./cluster/../cluster/../cluster/aws/../../cluster/common.sh: line 528: KUBE_MANIFESTS_TAR_URL: unbound variable
Kubernetes binaries at /Users/joeyzwicker/kubernetes/cluster/aws/kubernetes/cluster/
You may want to add this directory to your PATH in $HOME/.profile
Installation successful!
```

The three lines suggested above (in e.g. @ianjamez post) solved the problem for us, but it took us a while to figure out what had happened. Now that we all know what the problem is, can we get the script at get.k8s.io fixed ASAP? We'd like to be able to send our customers there to get it working for them too.

**Comment by gtaylor** [comment]
Is this still an issue in the latest master?

**Comment by mikeputnam** [comment]
To restate @ianjamez 's fix in patch form, I was able to get the below to work on v1.3.6:

```
--- broke/cluster/common.sh   2016-09-02 15:41:24.079309858 -0500
+++ fixed/cluster/common.sh   2016-09-02 15:50:09.585199901 -0500
@@ -523,6 +523,10 @@
   local master=$1
   local file=$2

+  KUBE_MANIFESTS_TAR_URL="${SERVER_BINARY_TAR_URL/server-linux-amd64/manifests}"
+  MASTER_OS_DISTRIBUTION="${KUBE_MASTER_OS_DISTRIBUTION}"
+  NODE_OS_DISTRIBUTION="${KUBE_NODE_OS_DISTRIBUTION}"
+
   local server_binary_tar_url=$SERVER_BINARY_TAR_URL
   local salt_tar_url=$SALT_TAR_URL
   local kube_manifests_tar_url=$KUBE_MANIFESTS_TAR_URL
```
Once the above changes are in place, just run the `kube-up.sh` script to continue.

**Comment by hollowimage** [comment]
+1 still broken for v1.3.6 
`./cluster/../cluster/../cluster/aws/../../cluster/common.sh: line 528: KUBE_MANIFESTS_TAR_URL: unbound variable`

**Comment by PierrickI3** [comment]
Thanks @mikeputnam and @ianjamez. That worked for me too.

**Comment by wayarmy** [comment]
work for me!!,
thanks @mikeputnam

**Comment by JoeyZwicker** [comment]
When will this fix be pushed so get.k8s.io uses a corrected common.sh. We often send users to the K8s docs for deployment and it'd be nice not to have to also send them with the caveat of "there's a small bug so follow this GH issue".

**Comment by mikeputnam** [comment]
This appears to be the official notification channel: https://groups.google.com/forum/#!forum/kubernetes-announce

**Comment by cmcconnell1** [comment]
Thanks to @bjfr and @discostur (using their work-arounds noted above) I was able to successfully deploy with version 1.3.5 and the three line addition as noted in bjfr's post.  Thanks!

**Comment by aliakhtar** [comment]
Still broken. At least the site page for getting started on AWS should mention this problem.

Solution was to put these 3 lines:

``KUBE_MANIFESTS_TAR_URL="${SERVER_BINARY_TAR_URL/server-linux-amd64/manifests}"
  MASTER_OS_DISTRIBUTION="${KUBE_MASTER_OS_DISTRIBUTION}"
  NODE_OS_DISTRIBUTION="${KUBE_NODE_OS_DISTRIBUTION}"``

at lines 525-527 in kubernetes/cluster/common.sh

Taken from other comments here.

**Comment by sbrosinski** [comment]
Can confirm. Was still broken for me as well. @aliakhtar 's suggestion made it work.

**Comment by sverrirab** [comment]
Hit the same problem using 1.3.7 release downloaded from here: https://github.com/kubernetes/kubernetes/releases/download/v1.3.7/kubernetes.tar.gz
1) configured my env:
```
export KUBERNETES_PROVIDER=aws
export KUBE_AWS_ZONE=eu-west-1c
export KUBE_AWS_INSTANCE_PREFIX=kube
export AWS_S3_REGION=eu-west-1
```
2) Ran ./kube-up.env and hit the same error above.  
3) Injected the changes suggested by @aliakhtar above and ran again.
```
An error occurred (RouteAlreadyExists) when calling the CreateRoute operation: The route identified by 10.246.0.0/24 already exists
```
4) Manually cleaned up created resources and ran again (RANDOMSTUFF replaced).
```
Creating kubernetes-staging-RANDOMSTUFF
make_bucket failed: s3://kubernetes-staging-RANDOMSTUFF/ An error occurred (OperationAborted) when calling the CreateBucket operation: A conflicting conditional operation is currently in progress against this resource. Please try again.
```
5) Realise that I should not delete the s3 bucket.  Configured:
```
export  AWS_S3_BUCKET=kubernetes-myname
```
6) Ran for the fourth time with success.

As a fairly standard use case for first time user I would say that this needs to be fixed?

**Comment by joan38** [comment]
As brand new guy on Kubernet I wanted to try out this and found this page:
http://kubernetes.io/docs/getting-started-guides/aws/
My first impression was whaaa, one command line and I should be up and running!
My seconde impression was this Kubernet thing is a big #$@&%*!
4 hours later I found this page and I'm now a bit more chilled.

Given this is a starter script and therefore mainly used by beginners, we should probably not expect those people hacking around to make this thing work, IMHO.

**Comment by jingweno** [comment]
1.3.7 still has this problem. Please fix it!

**Comment by Mistobaan** [comment]
just got this error as well

**Comment by andrewmclagan** [comment]
also seeing this as of latest

**Comment by kenips** [comment]
Seeing this on 1.3.7 and patch isn't on master either. @wayarmy, is this closed by mistake?

**Comment by jchambers** [comment]
@kenips I've created a deliberate duplicate of this issue (#33202) so it doesn't go unnoticed because this issue has been closed.
