### ISSUE TITLE
kubectl run and pull policy

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#30493]
I find myself iterating on a `:latest` container, which means I really want to be able to specify `pullPolicy` from the CLI.

**Comment by AdoHe** [comment]
Sounds reasonable to me. When using resource file, we can specify `imagePullPolicy` in the resource file, kubectl run should provide such option also. This should be easy to do @kubernetes/kubectl

**Comment by pwittrock** [comment]
@AdoHe Thanks

**Comment by pwittrock** [comment]
@AdoHe Wasn't sure how to reach out to you, so doing it here.  :) I'd be interested in getting your insight on onboarding kubectl maintainers.  My kubernetes.slack.com id is pwittrock.  Send me a direct message on slack when you are free.

**Comment by AdoHe** [comment]
```
If you have an @google.com, @redhat.com, @coreos.com or @intel.com email address, you can create an account.
```
@pwittrock I don't work for these great companies, I work for Alibaba.com, so I am afraid I can't sign in to kubernetes.slack.com. It would be great if I can onboard kubectl maintainers, really look forward to make kubernetes better and better.

**Comment by thockin** [comment]
go to http://slack.kubernetes.io and get a free invite :)

**Comment by AdoHe** [comment]
@thockin Thanks very much :) I just joined.
