### ISSUE TITLE
LocalDisk volume in kubernetes

### ISSUE THREAD

**Issue by chengyli** [kubernetes/kubernetes#30498]
When running kubernetes cluster, we got some requirements from users,
1. The pod need dedicated physical disk to guarantee stable disk I/O latency and throughput. When pod is deleted, the data on disk is kept, and the same disk can be claimed when a new pod starts.
2. The emptyDir and hostPath volume doesn't have disk size limitation, pod can write any size of data into these kinds of volume, but we should not allow this happen.

**Comment by chengyli** [comment]
In order to solve these problem, we have this proposal.
https://github.com/kubernetes/kubernetes/pull/30499

**Comment by xiangpengzhao** [comment]
This is a WIP feature currently. Please follow:

[Storage] Add support for persistent local storage #43640

@thockin

**Comment by xiangpengzhao** [comment]
All related proposals, PRs and discussions can be found in #43640

**Comment by xiangpengzhao** [comment]
/sig storage
Since this is a dup of #43640, we can close this one.
