### ISSUE TITLE
Use watches instead of polling for CLI state checking

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#30501]
Update reapers, scalers, and rollouts to use the `watch.Until` and `RetryOnConflict` methods to improve responsiveness and readability.

See https://github.com/kubernetes/kubernetes/pull/30383 for an example.  It looks like we have many CLI polling functions that could be converted to a watch as noted here: https://github.com/kubernetes/kubernetes/pull/30383#discussion_r74441980 .

**Comment by deads2k** [comment]
@kubernetes/kubectl I think we should start enforcing this in reviews for new CLI commands.  We have `watch.Until` function that's a lot easier to use than it was before, so there's no reason for us to continue polling.

**Comment by smarterclayton** [comment]
Agreed.  We may need a bit more sophisticated logic to handle some of
the backoff cases (I don't think a watch request handles retry today),
but watch should be less of a CPU burden to the server in practice.
