### ISSUE TITLE
kubelet with --kubeconfig=... still requires --api-servers=...

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#30515]
For the work we are doing at @kubernetes/sig-cluster-lifecycle (https://github.com/kubernetes/kubernetes/pull/30360), it'd make things much easier if we could make kubelet wait for the config file when it's not there and expect to find the API server URL in that file, rather then expect `--api-servers=...` like it does right now.

**Comment by errordeveloper** [comment]
cc @mikedanese

**Comment by mikedanese** [comment]
Ya I noticed this one time and it annoyed me. I think you mean --kubeconfig and not --config?

**Comment by mikedanese** [comment]
The problem with fixing this is that `len(--api-servers) == 0` is overloaded to mean run in standalone mode. That's not the case if apiservers were specified in the kubeconfig. cc @kubernetes/goog-node

**Comment by smarterclayton** [comment]
I just noticed this in #29216 and I agree - clients of the API should use
kubeconfig if they are part of our codebase.

**Comment by mtaufen** [comment]
I guess one thing we could do is add a `--standalone` flag, and if the flag is not provided we use the existing behavior of 0-len `--api-servers`, but if it is provided, `--api-servers` is ignored. So if you want to just use the URLs from the config file, you can explicitly pass `--standalone=false`. And eventually we move to deprecating `--api-servers`, setting `--standalone=false` by default, and always using URLs from the config file.

**Comment by errordeveloper** [comment]
Certainly we need a new flag. It seem like adding `--standalone` would sacrifice backwards compatibility, if this is a popular feature... I've briefly thought of something like `--wait-for-kubeconfig`, but may be we don't need a flag for it, and it could be just the new behaviour. What do people think about waiting for the kubeconfig file? Of course, there is one downside that `Config` type only allows you to set one `Server`, but it'd be reasonable to leave that outside of the scope, so we can just get the basic non-HA bootstrap UX implemented.

**Comment by dgoodwin** [comment]
Going to try to take a look at fixing this. 

Does it sound ok to do the following:
- if --kubeconfig specified:
  - if it doesn't yet exist wait for it
  - error out if --api-servers was also defined
  - change assumption for standalone behavior to: if len api-servers == 0 *and* --kubeconfig not specified

**Comment by lukemarsden** [comment]
@dgoodwin please note that there is already code which aims to fix this at https://github.com/kubernetes/kubernetes/pull/30616 – it might be better if you could review that code rather than writing new code?

**Comment by lukemarsden** [comment]
Or maybe you can explain how the proposal you just made is better than #30616? Thanks!

**Comment by dgoodwin** [comment]
My mistake, thought we needed a fix here. Looking now.

**Comment by errordeveloper** [comment]
@dgoodwin I think what you are suggesting is cleaner then adding a new flag, but it's mostly backwards compatibility that I was trying to address in #30616. I'd be happy to break this rather odd behaviour, if folks agree to do so.

**Comment by smarterclayton** [comment]
Ok, to summarize:

* We cannot break the backwards compatibility of len(apiservers) == 0 not meaning standalone.  That means we cannot just start reading kubeconfig by itself
* We never reload kubeclient, so a client that starts with kubeconfig specified but is broken is in error.
* We default KubeConfig in kubelet to a value, but users may have simply copied that default behavior onto a flag and expect the behavior.

To fix this, we need to introduce a new flag.  I would generally prefer we crash-loop with a very succinct and clean message, because we use that across the project consistently, and it is predictable and consistent with other tools in the space.

Here are some options:

* `--require-kubeconfig` - if specified, we error out on kubeconfig.  Would be set by cluster bootstrap.  Would not require changes to `kubeconfig`.
* `--apiserver-kubeconfig` - overrides `--kubeconfig` if set, and if set, requires the kubeconfig to exist.  Deprecate `--kubeconfig` and remove in 1.5 or later.

Either way, we'd also want to have the error checking try to print a nice succinct error.

**Comment by derekwaynecarr** [comment]
I think I prefer `--apiserver-kubeconfig`

**Comment by lukemarsden** [comment]
Thanks @smarterclayton! So to be clear `--apiserver-kubeconfig` means "read the API server information from the kubeconfig file, exiting cleanly if the kubeconfig file doesn't exist"? That SGTM.

**Comment by smarterclayton** [comment]
Yes I think so.

**Comment by smarterclayton** [comment]
Bumping to p1 because this blocks lifecycle having a path forward.

**Comment by smarterclayton** [comment]
Since I reviewed @erictune's original code here and I consider this my fault I'm opening a PR.

**Comment by smarterclayton** [comment]
@mtaufen this probably intersects with your changes - was that slated for merge today?

**Comment by mikedanese** [comment]
Are you planning on doing this for all components?

**Comment by smarterclayton** [comment]
No, just for Kubelet.  Controller manager and scheduler already exit if the kube config is invalid (can double check the others)

**Comment by smarterclayton** [comment]
Kubelet is the only one that must remain backwards compatible.

**Comment by mikedanese** [comment]
Can we just action-required release note and kubernetes-announce, and actually fix this? Kubelet should handle kubeconfig like all others components, including a continuous command line flag API. The fact that this is not the case is a bug. I imagine that this behavior is little traveled and this is gross.

> Controller manager and scheduler already exit if the kube config is invalid

There is no invalid. Using the default loader you get a http://localhost:8080 kubeconfig

**Comment by smarterclayton** [comment]
I thought we fixed it so that the NonInteractive did not have that value?  That's terrible if so.

**Comment by mikedanese** [comment]
```
$ kube-scheduler 
W0817 10:31:26.182035   42084 client_config.go:391] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0817 10:31:26.182091   42084 client_config.go:396] error creating inClusterConfig, falling back to default config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
E0817 10:31:26.183182   42084 reflector.go:216] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:410: Failed to list *api.ReplicationController: Get http://localhost:8080/api/v1/replicationcontrollers?resourceVersion=0: dial tcp [::1]:8080: getsockopt: connection refused
E0817 10:31:26.183218   42084 reflector.go:216] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:399: Failed to list *api.PersistentVolume: Get http://localhost:8080/api/v1/persistentvolumes?resourceVersion=0: dial tcp [::1]:8080: getsockopt: connection refused
E0817 10:31:26.183220   42084 reflector.go:216] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:395: Failed to list *api.Node: Get http://localhost:8080/api/v1/nodes?resourceVersion=0: dial tcp [::1]:8080: getsockopt: connection refused
E0817 10:31:26.183310   42084 reflector.go:216] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:415: Failed to list *extensions.ReplicaSet: Get http://localhost:8080/apis/extensions/v1beta1/replicasets?resourceVersion=0: dial tcp [::1]:8080: getsockopt: connection refused
E0817 10:31:26.183517   42084 leaderelection.go:253] error retrieving endpoint: Get http://localhost:8080/api/v1/namespaces/kube-system/endpoints/kube-scheduler: dial tcp [::1]:8080: getsockopt: connection refused
E0817 10:31:26.183626   42084 reflector.go:216] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:400: Failed to list *api.PersistentVolumeClaim: Get http://localhost:8080/api/v1/persistentvolumeclaims?resourceVersion=0: dial tcp [::1]:8080: getsockopt: connection refused
E0817 10:31:26.183691   42084 reflector.go:216] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:389: Failed to list *api.Pod: Get http://localhost:8080/api/v1/pods?fieldSelector=spec.nodeName%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=0: dial tcp [::1]:8080: getsockopt: connection refused
E0817 10:31:26.183773   42084 reflector.go:216] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:392: Failed to list *api.Pod: Get http://localhost:8080/api/v1/pods?fieldSelector=spec.nodeName%21%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=0: dial tcp [::1]:8080: getsockopt: connection refused
E0817 10:31:26.184695   42084 reflector.go:216] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:405: Failed to list *api.Service: Get http://localhost:8080/api/v1/services?resourceVersion=0: dial tcp [::1]:8080: getsockopt: connection refused
E0817 10:31:27.184139   42084 reflector.go:216] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:410: Failed to list *api.ReplicationController: Get http://localhost:8080/api/v1/replicationcontrollers?resourceVersion=0: dial tcp [::1]:8080: getsockopt: connection refused
E0817 10:31:27.184141   42084 reflector.go:216] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:395: Failed to list *api.Node: Get http://localhost:8080/api/v1/nodes?resourceVersion=0: dial tcp [::1]:8080: getsockopt: connection refused
E0817 10:31:27.184307   42084 reflector.go:216] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:399: Failed to list *api.PersistentVolume: Get http://localhost:8080/api/v1/persistentvolumes?resourceVersion=0: dial tcp [::1]:8080: getsockopt: connection refused
E0817 10:31:27.184635   42084 reflector.go:216] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:389: Failed to list *api.Pod: Get http://localhost:8080/api/v1/pods?fieldSelector=spec.nodeName%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=0: dial tcp [::1]:8080: getsockopt: connection refused
```

**Comment by smarterclayton** [comment]
Very useful...

**Comment by errordeveloper** [comment]
Yes, I recall there was a bit of mixed behaviour, but couldn't remember what it was exactly. Adding a `--poll-kubeconfig` sort of flag to all components would be nice, IMO... Or may be we could treat a empty file in special way or something. Alternatively, perhaps on systemd we could use `ConditionPathExists` (as @dgoodwin suggested) in `kubelet.service` and add `kubelet.path` to watch for it and kick `kubelet.service` when it gets created. Let's make sure to discuss later, once we get a fix to this LGTMed.

**Comment by smarterclayton** [comment]
Here's the first draft:

```
$ kubelet --require-kubeconfig
failed to run Kubelet: invalid kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory
```

**Comment by smarterclayton** [comment]
If people would like a better message for the "hot-loop" case please let me know

**Comment by lukemarsden** [comment]
LGTM @smarterclayton

**Comment by mtaufen** [comment]
@smarterclayton I have higher priorities today, so if #30798 merges first no worries. I'll rebase in the morning if necessary. Don't block on me.
