### ISSUE TITLE
API reference has incorrect response schema for many delete calls

### ISSUE THREAD

**Issue by randalloveson** [kubernetes/kubernetes#30537]
The API reference seems to assume a response schema of unversioned.Status for all delete calls, individual or collection. In reality, the response schema differers from resource to resource, and for some it is correct, but for many the response schema is actually an individual or list of the given resource. For example, the delete call for the Pod resource returns a Pod and a PodList for the individual and collection delete calls, respectively.

Short term, we should update the docs to reflect reality. Long term, wouldn't it make sense to unify the API so all the resources behave the same? Currently it is left up to the resource implemenation:

https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/resthandler.go#L807-L827

**Comment by mikedanese** [comment]
Delete returns inconsistently across types. Too late to do anything about this?

cc @bgrant0607 @kubernetes/api-review-team

**Comment by bgrant0607** [comment]
IIRC, part of the problem was that we couldn't express in Swagger 1.2 that one type was returned in the case of success and another was returned in the case of failure.

cc @lavalamp @mbohlool

**Comment by randalloveson** [comment]
@bgrant0607 it would be nice to sum up that quirk in a note somewhere, since it's true of all the API calls. However, this issue is about calls where the documentation specifies an incorrect response schema for the _successful_ responses, and that successful delete response's schemas are inconsistent from resource type to resource type.

**Comment by mikedanese** [comment]
From my experimenting:

* Succesful deletion of a single CertificateSigningRequest returns *not* pretty printed unversioned.Status
* Succesful deletion of all CertificateSigningRequest returns *not* pretty printed CertificateSigningRequestList
* Failed deletion of a single Pod returns pretty printed unversioned.Status
* Succesful deletion of a pod returns pretty printed Pod

**Comment by randalloveson** [comment]
I think REST dictates that for a synchronous delete, the body for a 200 response should be the entity deleted. So the Pod API is an example of good RESTful behavior, and the CertificateSigningRequest API is incorrect.

**Comment by bgrant0607** [comment]
@randalloveson Yes, unfortunately there are many quirks. Please add this to #25716. 

If you're interested in helping, check out SIG API machinery. 
https://github.com/kubernetes/community/

**Comment by lavalamp** [comment]
I added this to the umbrella issue.

Sounds like pod is doing this correctly, all resources should be going through the same code so it's a bit weird that it's different for other resources.

**Comment by loewenstein** [comment]
Actually the swagger spec is wrong in this regard and that is IMHO an even worse situation than broken documentation.

See https://github.com/kubernetes/kubernetes/blob/master/api/swagger-spec/v1.json#L7861 for the Pod example of wrong return type.

What should I expect when this is going to be resolved?

The client binding I am using is completely generated from swagger and hence it is wrong.

**Comment by roycaihw** [comment]
@bgrant0607 The [problem](https://github.com/kubernetes/kubernetes/issues/59501) still exists because our openapi v2 spec cannot represent `OneOf`. Tracking openapi v3 support in https://github.com/kubernetes/kubernetes/issues/60937
