### ISSUE TITLE
Update https-nginx example to use config map

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#30532]
Store https://github.com/kubernetes/kubernetes/blob/master/examples/https-nginx/default.conf in a config map, and setup an inotify in the container that reloads nginx when it changes. This is a pretty common pattern and we don't have an example that shows how it's done. Also document how to update the nginx configmap using kubectl, and how to translate nginx.conf to a kubernetes configmap (probably write a simple section to the existing makefile that does that).

**Comment by ymqytw** [comment]
That's a great suggestion!
