### ISSUE TITLE
kubelet waits too long to report container runtime is down

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#30534]
The `kubelet` has a constant `maxWaitForContainerRuntime` that is set at 5 minutes.
see: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L105

If `docker` daemon goes down, and it is unable to restart for any reason (storage is corrupt, etc.), the `kubelet` will wait for 5 minutes before reporting the node as `NotReady`.  This is because that wait period is plumbed through the code that monitors the container runtime state to know how to report if a node Ready condition.
see: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/runtime.go#L91

This has real-world impacts in following scenarios:
1. user has a pod on node X with `RestartPolicy=Always`, container run-time goes down, pod reports with `Status=Completed` in CLI because it has an exit code, where `Initialized=True,Ready=False,PodScheduled=True`, but its never actually able to restart.  The user has to wait 5 minutes for the node to report `NotReady`, and then another 5 minutes for node controller to evict the pod before ultimately getting a new backing pod created.  
2. new pods continue to get scheduled to this node, but are never able to run in a sufficient amount of time.

Either case results in 10 minutes of unexpected downtime, where 5 minutes of that time is not tunable by operators.

To address this issue, I could see us doing any of the following:
1. `kubelet` can tune `maxWaitForContainerRuntime` via a new flag.
2. `kubelet` can provide a separate SLA on how many attempts it makes to start or restart a scheduled pod if container runtime is reporting an error before actively evicting the pod.

Thoughts?

@kubernetes/sig-node @yujuhong @kubernetes/rh-cluster-infra @smarterclayton

**Comment by yujuhong** [comment]
> kubelet can provide a separate SLA on how many attempts it makes to start or restart a scheduled pod if container runtime is reporting an error before actively evicting the pod.

If there is no feedback loop to let scheduler know that the node is not ready, wouldn't this create more churn if more pods get created and scheduled back to the same node? 

> kubelet can tune maxWaitForContainerRuntime via a new flag.

I think 5 min is too long and we can definitely shorten it. I am also not against making it tunable, but I think kubelet should report it sooner in this case.

**Comment by vishh** [comment]
> If there is no feedback loop to let scheduler know that the node is not ready, wouldn't this create more churn if more pods get created and scheduled back to the same node?

+1. There needs to be some backpressure mechanism in place similar to how resource based evictions are handled. 

> I think 5 min is too long and we can definitely shorten it. I am also not against making it tunable, but I think kubelet should report it sooner in this case.

+1. Let's lower that threshold to 30 seconds. As of now, the runtime state is being queried every 5 seconds. So if it fails consistently for 6 times in a row, we will mark the node as `NotReady`. In-order to prevent flapping between `Ready` & `NotReady`, we could place a 30 second (or longer) threshold for the node to remain stable before it becomes `Ready` again.

What is the need for making this configurable?

**Comment by derekwaynecarr** [comment]
@vishh -- it need not be configurable.  I am fine with the reduction of the thresholds.  the current threshold was too high IMHO at 5 minutes since it basically made the situation 2x worse.  30 seconds sgtm.
