### ISSUE TITLE
Support updating config map and secret with --from-file

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#30558]
It is possible to create a config map using `kubectl create configmap foo --from-file bar.txt`.  We support similarly updating the config map using `kubectl update configmap foo --from-file bar.txt`.

**Comment by luxas** [comment]
+100

**Comment by bgrant0607** [comment]
See also #25832

**Comment by bgrant0607** [comment]
and #24049

**Comment by luxas** [comment]
@mengqiy Are you working on this?

**Comment by mengqiy** [comment]
@luxas Not any more.
Feel free to take this if you want. I can help review.

**Comment by luxas** [comment]
@mengqiy I'm not planning to work on this, have a bunch of other stuff going on, but given the amount of +1 on this and the inactivity, I wanted to make this free for new/other contributors.

**Comment by jamiehannaford** [comment]
I might have some spare cycles to work on this

**Comment by arthur0** [comment]
Can I work on it?

**Comment by luxas** [comment]
@arthur0 Sounds great!
Talked to @jamiehannaford and he will help out on some sig-cluster-lifecycle-related issues instead, so this one seems free to pick up!

Can't technically assign this one to you in the Github UI, but feel assigned and work on it :+1:

**Comment by luxas** [comment]
@pwittrock Doesn't `kubectl replace` cover all the use-cases for updating a ConfigMap like this already?
Can this issue be closed?

`kubectl replace -f configmap.yaml` does seem to cover `kubectl update configmap --from-file=configmap.yaml`

Also
```
$ kubectl update configmap
Command "update" is deprecated, use "replace" instead
error: Must specify --filename to replace
See 'kubectl update -h' for help and examples.
```

I'm very sorry that I didn't check that before @arthur0

**Comment by mengqiy** [comment]
`-f` only takes configmap object, but `--from-file` takes all kind of files.

**Comment by dmytroleonenko** [comment]
+1

**Comment by evmin** [comment]
+1

**Comment by sutasu** [comment]
+1

**Comment by bgrant0607** [comment]
Also ref #22368 and #49961.

But I'm pretty sure this is already possible using `kubectl create configmap --dry-run -o yaml ... | kubectl replace -f -`

**Comment by everett-toews** [comment]
@bgrant0607 Just to clarify, you're not suggesting that's the solution to this issue right? 

Sure it works (and we use it because we have to) but that's a rather ugly and very unintuitive UX. As a workaround for the time being it's okay but it could be much better.

**Comment by ReSearchITEng** [comment]
@bgrant0607 @everett-toews 
the create | replace it's not the same thing as a single replace, as it will loose all existing metadata, which I do not want to mess with :)

e.g. there is the configmap for prometheus server deployed via a helm chart.
I don't want to simulate the metadata already in the configmap, I just want to update the prometheus.yml inside the configmap, leaving everything else in the configmap intact.
I am not aware of any workaround but:  get cm | complicated sed/jq/etc | replace...

**Comment by bgrant0607** [comment]
@ReSearchITEng It sounds like create | patch or create | apply is what you want, then.

**Comment by bgrant0607** [comment]
Expanding on my comment above. Updating a ConfigMap in place updates all instances at the same time, which is a recipe for taking down your application. #22368 and #49961 are steps towards facilitating rolling updates, which requires creating a new ConfigMap rather than updating an existing one.

How I see this fitting into the bigger picture is described in my uber doc: https://goo.gl/T66ZcD

Also, even if we were to support in-place updates, we don't have "update" commands. We have multiple flavors of updates: replace, patch, and apply. This shouldn't be different.

**Comment by bgrant0607** [comment]
Also ref #24744

**Comment by husseincoder** [comment]
Guys I would like to try working on this one .. it will be my first contribution and I think I have sometime for it .. please let me know.

**Comment by pwittrock** [comment]
@seans3

**Comment by mengqiy** [comment]
@husseincoder Please go ahead. If you need some help feel free to ping me on slack :)

**Comment by bgrant0607** [comment]
@mengqiy `update` is not a command. Multiple flavors of update are supported. A more concrete proposal is required before this can be implemented, even if just sketched here.

**Comment by mengqiy** [comment]
> update is not a command.

@bgrant0607 Back in 2016 Q3, `kubectl update` is the alias of `kubectl replace`.
At that time, this feature request looks like it would improve the UX.

But after reading your comment https://github.com/kubernetes/kubernetes/issues/30558#issuecomment-326643503, I found this approach may turn out to encourge the users to do something dangerous. So should we leave a comment and close this issue?

We should always encourage users to create a new configmap and switch to it.

**Comment by bgrant0607** [comment]
@mengqiy `update` was an alias, but has been deprecated since 1.0.
https://github.com/kubernetes/kubernetes/commit/9b3d42c090aeab663bf42e38658a5f88fb4b5272#diff-1569293db00490c928c40f53fc14800c

Yes, it is potentially dangerous, but convenient in some cases.

In any case, more thought needs to be put into the UX, because lots of `kubectl replace configmap ...`, `kubectl apply configmap ...`, etc. commands doesn't feel right, especially if some resource types will be supported but others would not.

@liggitt commented pretty much the same thing a year ago:
https://github.com/kubernetes/kubernetes/pull/33335#issuecomment-251693037

#14040 requested create-or-replace ages ago, and we always intended for PUT to have that behavior in the API (#2114).

What about a `--replace-existing` flag to create?

**Comment by husseincoder** [comment]
@bgrant0607 @pwittrock @liggitt Guys its been so long since last interaction here .. should I close my PR and start implementing --replace-existing flag to create instead? please let me know .. I'm really passionate to get my first PR merged and start working on a new one :)

**Comment by itmard** [comment]
We have this issue and I want a tool to easily update configmaps create from directory and files.

**Comment by bgrant0607** [comment]
@husseincoder Sorry, yes, please close your PR. If you are eager to contribute, please start with bug fixes, of which we have an overwhelming number. Contact sig-cli to ask for starter issues.

@itmard We are currently working on #24744 and #22368 in this area.

**Comment by yonran** [comment]
I hope `kubectl replace configmap` will support `--from-file`. In the meantime, I’ve been using some bash scripts to convert --from-file to the json structure required by `kubectl replace`: https://gist.github.com/yonran/c5590a52179aa4841d1067991338b920

**Comment by dinvlad** [comment]
Are there plans to also support `--from-env-file` for updates? Thanks

**Comment by tjma2001** [comment]
@dinvlad this is the easiest workaround for now

kubectl create configmap --dry-run -o yaml --from-file=_env env | kubectl replace -f -

**Comment by dinvlad** [comment]
@tjma2001 nice, haven't thought of it this way. Dry-running with `--from-env-file` in our case should work just as well.

**Comment by irvifa** [comment]
We can use

```
kubectl create configmap some-config --from-file some-config.yaml -n some-namaespace -o yaml --dry-run | kubectl apply -f -  
```

This will create as well update `ConfigMap` if it's not exist yet

**Comment by cakraww** [comment]
@irvifa doesn't work in cloud builder  :(

**Comment by irvifa** [comment]
@cakraww yes, unfortunately this won't work in `container builder`, if we look into this [link](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/kubectl), we will know that the init script is supposed to receive only `kubectl` arguments.

```
FROM gcr.io/cloud-builders/gcloud

COPY kubectl.bash /builder/kubectl.bash

ENTRYPOINT ["/builder/kubectl.bash"]
```

`kubectl.bash` 
```
#!/bin/bash

# If there is no current context, get one.
if [[ $(kubectl config current-context 2> /dev/null) == "" ]]; then
    cluster=$(gcloud config get-value container/cluster 2> /dev/null)
    zone=$(gcloud config get-value compute/zone 2> /dev/null)
    project=$(gcloud config get-value core/project 2> /dev/null)

    function var_usage() {
        cat <<EOF
No cluster is set. To set the cluster (and the zone where it is found), set the environment variables
  CLOUDSDK_COMPUTE_ZONE=<cluster zone>
  CLOUDSDK_CONTAINER_CLUSTER=<cluster name>
EOF
        exit 1
    }

    [[ -z "$cluster" ]] && var_usage
    [[ -z "$zone" ]] && var_usage

    echo "Running: gcloud container clusters get-credentials --project=\"$project\" --zone=\"$zone\" \"$cluster\""
    gcloud container clusters get-credentials --project="$project" --zone="$zone" "$cluster" || exit
fi

echo "Running: kubectl $@"
kubectl "$@"
```

Actually in bash if we can replace `kubectl` in the init script with `exec "$@"` instead, however I'm still finding another difficulty since any special character just won't work in container builder yaml syntax. I wonder if anyone in there can explained it in details.

**Comment by irvifa** [comment]
Based on [#22](https://github.com/GoogleCloudPlatform/cloud-builders/issues/22) we can use:

- name: 'gcr.io/cloud-builders/kubectl'
  id: 'test entrypoint bash'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials --project=$PROJECT_ID --zone="<some-region>" "<cluster-name>"
    kubectl create configmap <configmap-name> --from-file=<key>=<file-name> -n <namespace-name> -o yaml --dry-run -o yaml | kubectl apply -f -

**Comment by jobernolte** [comment]
When I try to execute this command:

`kubectl create configmap logstash-config --from-file=logstash.yml --from-file=logstash.conf --dry-run --save-config -o yaml | kubectl apply -f -`
It gives me the following error:
`error: error validating "STDIN": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false`

The output is somehow missing the **apiVersion** and *kind** attribute.

**Comment by liggitt** [comment]
> The output is somehow missing the apiVersion and kind attribute. Any clues on how to solve this?

This was a bug in 1.10 fixed in 1.10.1

**Comment by inthecloud247** [comment]
I'm seeing the same error in version 1.9.3, so it seems like this bug was introduced earlier than 1.10.0 ?

**Comment by liggitt** [comment]
> I'm seeing the same error in version 1.9.3, so it seems like this bug was introduced earlier than 1.10.0 ?

No, it came in with 1.10.0

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-04-20T14:01:18Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-04-20T14:01:18Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}

$ kubectl create configmap foo --from-literal key=value --dry-run -o yaml
apiVersion: v1
data:
  key: value
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: foo

$ kubectl create configmap foo --from-literal key=value --dry-run -o yaml | kubectl apply -f -
configmap "foo" created

$ kubectl create configmap foo --from-literal key=value2 --dry-run -o yaml | kubectl apply -f -
configmap "foo" configured
```

**Comment by bgrant0607** [comment]
PTAL:
https://github.com/kubernetes-sigs/kustomize
https://github.com/kubernetes/community/blob/master/keps/sig-cli/0008-kustomize.md

**Comment by neurostream** [comment]
- @bgrant0607 Skimming through each of the nuanced variations of the issue cited here, I'm not seeing any that Kustomize doesn't seem to address - and then some.
- For others who will probably have Kustomize to look forward to; but are still working it into your tooling adoption in the days or weeks ahead _and_: 
  - _if_ you are stuck until then with:
    - an initial  ```kubectl create -f app-config.yml```
  - _but_ later needed to add new ConfigMap K/V pairs ```--from-env-file=more-app-config.env``` 
  - _*or* if_, in my case, just wanted to keep the original app-config.yml definition clean and separated from dirtier bits coming in ```--from-env-file=...```
  - _then_ - inspired by Brian Grant's original 2017-08-23 thoughts here in this thread - was able to get by at the time with ( brace yourself )  : 
    - ```kubectl create -f app-config.yml --output=json | kubectl patch -f - -p "$(kubectl create configmap app-config --from-env-file=more-app-config.env --output=json --dry-run)" ```

**Comment by bgrant0607** [comment]
cc @monopole @janetkuo @kow3ns

**Comment by jansmets** [comment]
There is Hyperkube
https://console.cloud.google.com/gcr/images/google-containers (search for hyperkube on top)

The only thing I'm personally missing is kubeadm so that this can be used to easily bootstrap a master node.

**Comment by bgrant0607** [comment]
@irvifa Does Helm support configmap and secret generation?
https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md

Since in order to trigger a rolling update and to preserve the ability to rollback one needs to generate a new configmap, the recommended approach is to generate configmaps with unique names, such as via the append-hash mechanism. kustomize supports this use case.

kustomize is in the process of being integrated into the cli-runtime library, so it will be available to other tools that want to reuse it.

As for in-place updates of the objects with a single command (other than the kustomize approach), we have too many flavors of updates (3 kinds of patches, apply, and replace) for this to be practical.

**Comment by irvifa** [comment]
@bgrant0607 I see, thank you for your information then.
