### ISSUE TITLE
Refactor kubectl command options to use common struct for common file params

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#30562]
The commands under pkg/kubectl/cmd/*.go all redefine the same go struct options for passing to the file visitor (e.g. FooOptions all contain "Filename []string").  Factor this out into a common struct that the individual options can embed (using go struct embedding), and then update the functions that take the arguments to take the common struct instead.

**Comment by fraenkel** [comment]
@pwittrock There is a slight gotcha here if you want this done.
If we define a new struct for just Filenames []string, it cannot live in kubectl/cmd if you want the functions which live in kubectl and kubectl/resource to consume it.
Do you have a location you would like this common struct to live in?

**Comment by pwittrock** [comment]
@fraenkel Thanks for reaching out.  I know @ymqytw already started on this issue.  Apologies for not having applied the assigned label when I assigned it to @ymqytw.  Would you like to pick another issue from [the list](https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Agood-for-contributor-onboarding%20label%3Acomponent%2Fkubectl%20-label%3Acontributor-onboarding-assigned)?

**Comment by ymqytw** [comment]
#30815
