### ISSUE TITLE
[k8s.io] ScheduledJob should replace jobs when ReplaceConcurrent 1m54s

### ISSUE THREAD

**Issue by lixiaobing10051267** [kubernetes/kubernetes#30561]
PR #30492 test fail:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/30492/kubernetes-pull-build-test-e2e-gce/53291

[k8s.io] ScheduledJob should replace jobs when ReplaceConcurrent 1m54s
go run hack/e2e.go -v -test --test_args='--ginkgo.focus=ScheduledJob\sshould\sreplace\sjobs\swhen\sReplaceConcurrent$'
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduledjob.go:148
Expected
    <[]batch.Job | len:2, cap:2>: [
        {
            TypeMeta: {Kind: "", APIVersion: ""},
            ObjectMeta: {
                Name: "replace-1553565502",
                GenerateName: "",
                Namespace: "e2e-tests-scheduledjob-txn5y",
                SelfLink: "/apis/batch/v2alpha1/namespaces/e2e-tests-scheduledjob-txn5y/jobs/replace-1553565502",
                UID: "79dc717a-60e1-11e6-b40c-42010af00002",
                ResourceVersion: "6187",
                Generation: 0,
                CreationTimestamp: {
                    Time: {
                        sec: 63606640020,
                        nsec: 0,
                        loc: {
                            name: "Local",
                            zone: [
                                {name: "PDT", offset: -25200, isDST: true},
                                {name: "PST", offset: -28800, isDST: false},
                                {name: "PWT", offset: -25200, isDST: true},
                                {name: "PPT", offset: -25200, isDST: true},

**Comment by lavalamp** [comment]
Dup of https://github.com/kubernetes/kubernetes/issues/30542
