### ISSUE TITLE
Allow running pod without any image.

### ISSUE THREAD

**Issue by kevincox** [kubernetes/kubernetes#30576]
It would be awesome to be able to simply run a command on the host instead of having to run a command inside a docker image. This would be similar to running a Marathon app with `command` instead of `container`. This command would then be run inside of whichever cgroups or selinux context was requested in the config.

**Comment by AdoHe** [comment]
@kubernetes/kubectl any thoughts on this?

**Comment by smarterclayton** [comment]
The goal being to escape all host namespaces?    Arguably this is possible today with privileged, hostPath mount of / to /rootfs, and a chroot to /rootfs.

**Comment by kevincox** [comment]
I'm not 100% sure what you mean by host namespaces but I think most of the time you would want to be in a cgroup or selinux as the docker container would be.

That is an interesting workaround. I'll have to take a look at creating a "null" or "transparent" container like that as I can't find any premade. But that shouldn't be too hard to pull off.

**Comment by smarterclayton** [comment]
If you can emulate what you need that's a good start to describing the
problem.  We usually call these "super-priviliged containers" and
ensuring you can act as if you are on the host on Kube is important to
us

**Comment by AdoHe** [comment]
@kevincox imo, you want to keep resource control enabled by cgroup but you don't care isolation, is that what you mean?

**Comment by kevincox** [comment]
On Aug 15, 2016 06:54, "TonyAdo" <notifications@github.com> wrote:

> <https://github.com/kevincox>

> @kevincox <https://github.com/kevincox> imo, you want to keep resource
control enabled by cgroup but you don't care isolation, is that what you
mean?

That sounds close. Although I would like the security isolation. Basically
I don't need the execution environment isolation dockers provides. However
I would still like performance and security isolation.

**Comment by smarterclayton** [comment]
I *think* this is:

1. pod with 1 container including an image that has chroot
2. set the privileged flag on the pod
3. add a volume mount of / to /rootfs
4. set the container command to `chroot ...` - you may also want to drop and change user

I wonder if the chroot could potentially be something we add support for in a container - it's come up enough that it may have value on its own.

**Comment by dchen1107** [comment]
@kevincox Is @smarterclayton suggested above resolving your issue? Or

You are asking something else? From title of the issue, sounds like you don't want to / couldn't build docker image. Instead, your application is packaged properly, and the dependencies are resolved through other way. Basically you don't care about the isolated environments for your applications at the kernel level created through docker image, but you expect Kubelet can start your app in a native container based on linux cgroup, chroot, namespace, etc. Is that right?

**Comment by kevincox** [comment]
I haven't got around to trying it yet but I suspect it might. I'll try to test it out this weekend. 

And your understanding seems to be spot on. That is exactly what I am looking for. If I have to run it through docker that will probably be fine although it would be nice to be able to do it without the docker hacks.
