### ISSUE TITLE
Convert ReplicationController to a plugin (was ReplicationController redesign)

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#3058]
Continued from #1518 and #3024, and also relates to #1624.

Since there will necessarily be a higher barrier to entry for new objects, we should make replication controller composable (e.g., with auto-scalers and deployment managers), pluggable, hookable (#2804), to delegate decisions like which pod to kill to decrease the replica count, when pods should be killed and replaced (esp. moving to new nodes), when the whole collection should terminate (for RestartPolicyOnFailure), etc.

For jobs that terminate (RestartPolicyOnFailure), I'd make the count auto-decrement on success. I'm tempted to say we should support terminating jobs of the per-node variety, but then we'd have to keep track on which nodes the pods had executed, which seems ugly.

It should support graceful termination (#1535), but I've removed that from this sketch, since it's not specific to replication controller.

Stab at a definition, also using my latest proposed name change:
```
type OverseerSpec struct {
	ReplicationPolicy *ReplicationPolicy `json:"replicationPolicy,omitempty"`
	Selector map[string]string `json:"selector,omitempty"`
	TemplateRef *ObjectReference `json:"templateRef,omitempty"`
	Template *PodTemplateSpec `json:"template,omitempty"`
}
type ReplicationPolicy struct {
	Count *ReplicationPolicyCount    `json:"count,omitempty"`
	PerNode *ReplicationPolicyPerNode `json:"perNode,omitempty"`
}
type ReplicationPolicyCount struct {
	Count int `json:"count"`
}
type ReplicationPolicyPerNode struct {
}
```
Forgiveness example was moved to #1574.

Additional example policies have been removed.

/cc @smarterclayton @thockin @brendandburns @erictune @lavalamp

**Comment by bgrant0607** [comment]
Thoughts on the separate-object approach:

* Polymorphism/reflection/meta-programming: For everything that would need to deal with similar flavors of controllers (UIs, CLIs, etc.), we'd need an API that would provide a list of Kinds that were controllers and/or, equivalently, Kind metadata that would identify which Kinds were controllers. That would be much more robust than just matching on "Controller" in the Kind. We also need a resize verb (#1629), since at least 2 types of controllers would need to be resizable (service and batch job controllers), but we need that regardless. Note that some types of controllers (per-node, cron) wouldn't support resize, but I think that would work about the same with the subobject approach, as well.
* Code reuse: We'd want to eliminate the vast majority of code duplication: generic rest objects, controller library, splitting out the pod template (#170), built-in readiness checks (#620), ... We want almost all of those things, anyway.
* API surface: This is a trade off: more first-class objects vs. more complex objects. As discussed above, even with the subobject approach, controllers will stand out as the simplest objects in the system. Therefore, I think more top-level objects would actually make the system look more complex rather than simpler, especially if we don't implement most of the features I used as examples. I also think that using separate objects is more likely to drive more complexity into pods, as @davidopp's comments demonstrate, in order to avoid duplicating that logic in multiple controllers.
* Extensibility: This is where the separate-object approach shines. Really, only pods and services need to be core objects in the system, since they directly affect underlying infrastructure resources. All controllers could/should be plugins, which would make it easier to add new controllers, such as a cron controller.

I think the best motivating example for the separate-object approach is the job controller (#1624). That's likely to need a number of features specific to bounded-duration/deferred-execution batch/workflow types of jobs: queuing and execution deadlines, success/failure aggregation, gang scheduling and/or admission control, max-in-flight limits (e.g., run 50 pods, no more than 10 at a time), inter-job dependencies (A before B), pre-start auto-scaling/auto-sizing, intelligent response to out-of-resource events, ...

Potentially nominal services could be considered "controllers" also (controlling services). So could auto-scalers (controlling replication controllers). The flavor of controller could maybe be inferred by the Kind of object controlled, or perhaps that needs to be part of the reflection API, also.

I think the separate-object approach could work, but we need to design the reflection API that would enable meta-programming for multiple kinds of controllers with similar features.

Other thoughts on the per-node controller:
* I'd like to avoid requiring the "per-node" controller, however that functionality is implemented, to essentially be a scheduler. As mentioned several times in other places, there are ways we can avoid that by providing features that we'll want for other reasons.
* I'm not convinced that "per-node" is the right concept. We have internal examples of monitoring and control components that need to run per rack, per power unit, per storage array, etc.

**Comment by thockin** [comment]
To also capture what Brian and I discussed a bit yesterday:

The first question to ask is: Do we really think people will want to make controllers outside of kubernetes code?  If the answer is no, then a monolithic compound object seems net simpler.  If the answer is yes, then I think separate objects are simpler.  I'm going to assume the answer is yes, because I want it to be :)  Here's how I mentally run through the differences in how the mondels should work.

Separate API objects:
   * We need to implement truly self-contained REST plugins
   * We need to implement remote REST plugins (we receive the API calls, but pass operations on to another server)
   * We need to implement dynamic registration of remote REST plugins
   * We implement ReplicationController as a remote REST plugin
   * We need to factor a bunch of logic out as libraries for other controllers to use
   * API for ReplicationController stays ~same

Monolithic API object:
   * We need to refactor ReplicationController along the lines of the above proposal (which is like kubelet volumes)
   * We need to implement self-contained controller plugins
   * We need to implement dynamic registration of controller plugins
   * Maybe we implement ReplicationController as a plugin
   * We need to factor a bunch of logic out as libraries for other controllers to use
   * API for ReplicationController changes

In both cases we need an extension point for plugins.  In both cases we need API to be more dynamic.  In both cases we need to do a bunch of library abstraction so 3rd party plugins can re-use logic (if they want).  If we want a discovery system ("dear apiserver, please tell me all Kinds that act as pod controllers"), we need it in both cases.  If we want to have generic code that can operate on things without knowing what they are, the problem is isomorphic for both models.

But the separate objects case gives us generic REST plugins, which I think we want in both models (net less work, net less concepts).  It also retains the existing ReplicationController API.

So I fall on the side of separate objects, though only slightly.

Now we can argue about services - are services the same?  Much of the same argument applies.

**Comment by bgrant0607** [comment]
To move this forward, I'm going to declare this settled: The consensus appears to be in favor of the multiple-controllers approach, so let's stick with that. I'm reasonably convinced that we can solve the code factoring and polymorphism/reflection problems, so the main advantage of the other approach is that it would be less work in the short term.

Let's keep the services discussion in #2585.

**Comment by davidopp** [comment]
I just want to go on record as saying I think this is a bad idea. :-) Control loops with a single controller are hard, much less control loops with multiple controllers. It's unlikely that the policies they implement are going to be completely orthogonal. Eventually someone will want some way for them to communicate so as to implement a global policy. After that people will start wondering why they are spending half of their time fighting against component boundaries when the thing would be so much easier in a single component. Anyway, ever the optimist I am willing to accept that perhaps This Time Will Be Different, but I am wary. At the very least it seems we are making a decision without having sketched out some detailed examples of use cases where multiple controllers are controlling the same set of pods.

**Comment by bgrant0607** [comment]
@davidopp This is not about multiple controllers with overlapping responsibilities over the same pods, so interacting control loops is not a situation affected by this decision. That said, I am familiar with the other part of your argument and agree there is a tradeoff.

**Comment by davidopp** [comment]
@bgrant0607 Oh, maybe I misunderstood. It is about multiple controllers with responsibility over the same pods, right? So the part I misunderstood is the "overlapping responsibilities" part? But how can you know that the responsibilities will not overlap (indeed how can you define overlap? is it 100% certain that even something like forgiveness policy is orthogonal to auto-scaling policy or whatever?)

**Comment by bgrant0607** [comment]
@davidopp This issue is about whether ReplicationController should also handle daemons (per-node, per-rack, etc.) and terminating pods (aka job controller), or whether separate objects should handle those cases.

**Comment by davidopp** [comment]
Ah OK thanks, some parts of the thread were about separating different bits of functionality for the same set of pods into separate controllers, so I didn't realize the most recent comments were just about different controllers for different pod types. So I withdraw my objection, which was applicable to this situation. :-)

**Comment by thockin** [comment]
For the record, we should do this with generic REST plugins, in or out of
process.  I'll queue this up for people to work on.

**Comment by bgrant0607** [comment]
To finalize the proposals for the controllers planned in the immediate future:
```
type ReplicaMasterSpec struct {
    Size int `json:"size"`
    Selector map[string]string `json:"selector,omitempty"`
    TemplateRef *ObjectReference `json:"templateRef,omitempty"`
    Template *PodTemplateSpec `json:"template,omitempty"`
}
type DaemonMasterSpec struct {
    Selector map[string]string `json:"selector,omitempty"`
    TemplateRef *ObjectReference `json:"templateRef,omitempty"`
    Template *PodTemplateSpec `json:"template,omitempty"`
}
```

**Comment by bgrant0607** [comment]
This is decided enough for 1.0, so demoting implementation to P3.

**Comment by TamerTas** [comment]
Currently the implementation is on hold for 1.0 correct? Is there any work in progress about this feature at the moment? 

In the spirit of Kubernetes being modular, multiple small `replicationController`s seems to be the most favored solution. For coordination, I think `ZeroMQ` or `nsq` would be a good or even better `etcd`. I'd be very interested to work on this.

**Comment by bgrant0607** [comment]
The decision was to create new controllers for new use cases (e.g., per-node/daemon, RestartOnFailure pods) rather than make ReplicationController more complicated.

To facilitate that, we need to:
1. Finish the API plugin mechanism #991
2. Convert ReplicationController to use the API plugin mechanism
3. Split out the pod template #170 so that other controllers can use it.
4. Create a controller framework to make it easier to write controllers.

There is work underway on (3), #5012, and (4), #5270.

AFAIK, there's no direct work on (1) or (2), but we are converting existing objects, including ReplicationController, to use the generic registry implementation and have created a pattern for posting status back from controllers as part of #2726.

If the amount of code required for a new controller were sufficiently reduced by other ongoing efforts, we needn't block implementation of new controllers on the generic plugin mechanism, but the plugin mechanism would be of independent utility.

**Comment by davidopp** [comment]
I'm not sure we should just say every conceivable variation merits a new replication controller. Per-node/daemon might be different enough from a regular replication controller to deserve being separate, but things that can be expressed trivially with one bool (like restart-on-failure vs. don't) should just be configuration parameters for the RC we already have IMO.

**Comment by bgrant0607** [comment]
Obsolete
