### ISSUE TITLE
/gofiles.mk.stamp', needed by `pkg/apis/extensions/v1beta1/zz_generated.conversion.go'.  Stop.

### ISSUE THREAD

**Issue by 249043822** [kubernetes/kubernetes#30584]
root@ubuntu:/home/docker/kubernetes# hack/update-codecgen.sh
Building dependencies
Building codecgen
/gofiles.mk.stamp', needed by `pkg/apis/extensions/v1beta1/zz_generated.conversion.go'.  Stop.
make: *** [generated_files] Error 2
!!! Error in hack/update-codecgen.sh:121
  'make generated_files' exited with status 2
Call stack:
  1: hack/update-codecgen.sh:121 main(...)
Exiting with status 1

**Comment by 249043822** [comment]
I do make test or make, still cause this error, did the new version depend other libs or tools?

**Comment by 249043822** [comment]
@ixdy , @lavalamp

**Comment by 249043822** [comment]
@thockin , hi, as in version 1.3 or before, i could do test or build directly and my machine only need installing golang. Now in  recent svn codes,  i do make test or update-codecgen.sh, firstly it need go-bindata, and i installed it, but still got errors above , i 'm confusing , could you help me ? thanks

**Comment by 249043822** [comment]
@Dongxiugang

**Comment by thockin** [comment]
go-bindata is something else, unfortunately.

Did you `make clean`?  I can not reproduce this.  It indicates a pretty severe failure - a whole lot of variables evaluated to "".  Do you have changes in this branch?

**Comment by 249043822** [comment]
I have no changes , i only clone the newest code from kubernetes/kubernetes, still cause the error, i don't known why /gofiles.mk.stamp hasn't been generated, i found the code has big differences with 1.3 , for example, Makefile.generated_files


root@k8s-node2:/home/k8s/zhangke/kubernetes# make clean
+++ [0816 11:33:16] Verifying Prerequisites....
!!! [0816 11:33:16] Build image not built.  Cannot clean via docker build image.
+++ [0816 11:33:16] Removing data container kube-build-data-712a073c15
+++ [0816 11:33:16] Removing _output directory
+++ [0816 11:33:16] Deleting docker image kube-build:build-712a073c15
+++ [0816 11:33:16] Cleaning all other untagged docker images
root@k8s-node2:/home/k8s/zhangke/kubernetes# hack/update-codecgen.sh 
Building dependencies
Building codecgen
+++ [0816 11:33:50] Generating bindata:
    /home/k8s/zhangke/kubernetes/test/e2e/framework/gobindata_util.go
+++ [0816 11:33:51] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0816 11:33:52] Building go targets for linux/amd64:
    cmd/libs/go2idl/deepcopy-gen
+++ [0816 11:33:58] Generating bindata:
    /home/k8s/zhangke/kubernetes/test/e2e/framework/gobindata_util.go
+++ [0816 11:33:59] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0816 11:33:59] Building go targets for linux/amd64:
    cmd/libs/go2idl/conversion-gen
/gofiles.mk.stamp', needed by `pkg/apis/extensions/v1beta1/zz_generated.conversion.go'.  Stop.
make: *** [generated_files] Error 2
!!! Error in hack/update-codecgen.sh:120
  'make generated_files' exited with status 2
Call stack:
  1: hack/update-codecgen.sh:120 main(...)
Exiting with status 1

**Comment by thockin** [comment]
What OS?  What version of `make` ?  Obviously it is not totally broken or
CI would not pass...

**Comment by 249043822** [comment]
root@k8s-node2:/home/k8s/zhangke/kubernetes# more /etc/issue
Ubuntu 14.04.1 LTS \n \l

root@k8s-node2:/home/k8s/zhangke/kubernetes# make -version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu

**Comment by 249043822** [comment]
anything wrong?

**Comment by thockin** [comment]
Nope.  Same as me.  Are you rebased to upstream/master as of recent?  Does
`git status` come back clean?

Can you run `make DBG_MAKEFILE=1` ?

**Comment by 249043822** [comment]
thanks, i will try now, did your environment set GOPATH?

**Comment by thockin** [comment]
The build should be hermetic wrt GOPATH, but yes my GOPATH is legit.

**Comment by 249043822** [comment]
hi , @thockin , when i run `make DBG_MAKEFILE=1`, it output so many lines, but i still do not know why cause the error, it's so unthinkable


..........

.........
     cmp -s .make/cmd/genman/gofiles.mk.tmp .make/cmd/genman/gofiles.mk || touch .make/cmd/genman/gofiles.mk.stamp;                       \
        mv .make/cmd/genman/gofiles.mk.tmp .make/cmd/genman/gofiles.mk
FILES=$(ls cmd/genkubedocs/*.go | grep --color=never -v zz_generated.);  \
        mkdir -p .make/cmd/genkubedocs;                                           \
        echo "gofiles__cmd/genkubedocs := $(echo ${FILES})" >.make/cmd/genkubedocs/gofiles.mk.tmp;         \
        cmp -s .make/cmd/genkubedocs/gofiles.mk.tmp .make/cmd/genkubedocs/gofiles.mk || touch .make/cmd/genkubedocs/gofiles.mk.stamp;                       \
        mv .make/cmd/genkubedocs/gofiles.mk.tmp .make/cmd/genkubedocs/gofiles.mk
FILES=$(ls cmd/gendocs/*.go | grep --color=never -v zz_generated.);  \
        mkdir -p .make/cmd/gendocs;                                           \
        echo "gofiles__cmd/gendocs := $(echo ${FILES})" >.make/cmd/gendocs/gofiles.mk.tmp;         \
        cmp -s .make/cmd/gendocs/gofiles.mk.tmp .make/cmd/gendocs/gofiles.mk || touch .make/cmd/gendocs/gofiles.mk.stamp;                       \
        mv .make/cmd/gendocs/gofiles.mk.tmp .make/cmd/gendocs/gofiles.mk
FILES=$(ls cluster/addons/fluentd-elasticsearch/es-image/*.go | grep --color=never -v zz_generated.);  \
        mkdir -p .make/cluster/addons/fluentd-elasticsearch/es-image;                                           \
        echo "gofiles__cluster/addons/fluentd-elasticsearch/es-image := $(echo ${FILES})" >.make/cluster/addons/fluentd-elasticsearch/es-image/gofiles.mk.tmp;         \
        cmp -s .make/cluster/addons/fluentd-elasticsearch/es-image/gofiles.mk.tmp .make/cluster/addons/fluentd-elasticsearch/es-image/gofiles.mk || touch .make/cluster/addons/fluentd-elasticsearch/es-image/gofiles.mk.stamp;                       \
        mv .make/cluster/addons/fluentd-elasticsearch/es-image/gofiles.mk.tmp .make/cluster/addons/fluentd-elasticsearch/es-image/gofiles.mk
make[1]: Leaving directory `/home/k8s/zhangke/kubernetes'
make[1]: Entering directory `/home/k8s/zhangke/kubernetes'
Makefile.generated_files:21: ***** starting Makefile.generated_files for goal(s) "generated_files"
Makefile.generated_files:22: ***** 2016年 08月 16日 星期二 15:33:04 CST
Makefile.generated_files:109: ***** finding all *.go dirs
Makefile.generated_files:169: ***** finding all +k8s: tags
Makefile.generated_files:197: ***** finding all +k8s:deepcopy-gen tags
Makefile.generated_files:310: ***** finding all +k8s:conversion-gen tags
mkdir -p .make/_output/bin;                                        \
        (echo -n "_output/bin/conversion-gen: ";                        \
         DIRECT=$(go list -f '{{.Dir}} {{.Dir}}/*.go' ./cmd/libs/go2idl/conversion-gen);                \
         INDIRECT=$(go list         -f '{{range .Deps}}{{.}}{{"\n"}}{{end}}' ./cmd/libs/go2idl/conversion-gen | grep --color=never "^k8s.io/kubernetes" | sed 's|^k8s.io/kubernetes|./|' | xargs go list -f '{{.Dir}} {{.Dir}}/*.go');     \
         echo $DIRECT $INDIRECT                              \
             | sed 's/ / \\=,/g'                               \
             | tr '=,' '\n\t';                                 \
        ) | sed "s|$(pwd -P)/||" > .make/_output/bin/conversion-gen.mk.tmp;                    \
        cmp -s .make/_output/bin/conversion-gen.mk.tmp .make/_output/bin/conversion-gen.mk || cat .make/_output/bin/conversion-gen.mk.tmp > .make/_output/bin/conversion-gen.mk && rm -f .make/_output/bin/conversion-gen.mk.tmp
mkdir -p .make/_output/bin;                                        \
        (echo -n "_output/bin/deepcopy-gen: ";                          \
         DIRECT=$(go list -f '{{.Dir}} {{.Dir}}/*.go' ./cmd/libs/go2idl/deepcopy-gen);                  \
         INDIRECT=$(go list         -f '{{range .Deps}}{{.}}{{"\n"}}{{end}}' ./cmd/libs/go2idl/deepcopy-gen | grep --color=never "^k8s.io/kubernetes" | sed 's|^k8s.io/kubernetes|./|' | xargs go list -f '{{.Dir}} {{.Dir}}/*.go');     \
         echo $DIRECT $INDIRECT                              \
             | sed 's/ / \\=,/g'                               \
             | tr '=,' '\n\t';                                 \
        ) | sed "s|$(pwd -P)/||" > .make/_output/bin/deepcopy-gen.mk.tmp;                    \
        cmp -s .make/_output/bin/deepcopy-gen.mk.tmp .make/_output/bin/deepcopy-gen.mk || cat .make/_output/bin/deepcopy-gen.mk.tmp > .make/_output/bin/deepcopy-gen.mk && rm -f .make/_output/bin/deepcopy-gen.mk.tmp
hack/make-rules/build.sh cmd/libs/go2idl/deepcopy-gen
+++ [0816 15:33:07] Generating bindata:
    /home/k8s/zhangke/kubernetes/test/e2e/framework/gobindata_util.go
+++ [0816 15:33:08] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0816 15:33:10] Building go targets for linux/amd64:
    cmd/libs/go2idl/deepcopy-gen
touch _output/bin/deepcopy-gen
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/federation/apis/federation >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/federation/apis/federation/v1beta1 >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/api >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/apps >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/apps/v1alpha1 >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/authentication >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/authentication/v1beta1 >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/authorization >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/authorization/v1beta1 >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/autoscaling >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/autoscaling/v1 >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/batch >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/batch/v1 >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/batch/v2alpha1 >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/certificates >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/certificates/v1alpha1 >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/componentconfig >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/componentconfig/v1alpha1 >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/extensions >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/extensions/v1beta1 >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/policy >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/policy/v1alpha1 >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/rbac >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/apis/rbac/v1alpha1 >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/api/unversioned >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/api/v1 >> .make/_output/bin/deepcopy-gen.todo
mkdir -p $(dirname .make/_output/bin/deepcopy-gen)
echo k8s.io/kubernetes/pkg/runtime >> .make/_output/bin/deepcopy-gen.todo
if [[ -f .make/_output/bin/deepcopy-gen.todo ]]; then                  \
            ./hack/run-in-gopath.sh _output/bin/deepcopy-gen                         \
                --v 1                                         \
                -i $(cat .make/_output/bin/deepcopy-gen.todo | paste -sd, -)  \
                --bounding-dirs k8s.io/kubernetes                             \
                -O zz_generated.deepcopy;                                    \
        fi
hack/make-rules/build.sh cmd/libs/go2idl/conversion-gen
+++ [0816 15:33:16] Generating bindata:
    /home/k8s/zhangke/kubernetes/test/e2e/framework/gobindata_util.go
+++ [0816 15:33:17] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0816 15:33:17] Building go targets for linux/amd64:
    cmd/libs/go2idl/conversion-gen
touch _output/bin/conversion-gen
mkdir -p $(dirname .make/_output/bin/conversion-gen)
echo k8s.io/kubernetes/federation/apis/core/v1 >> .make/_output/bin/conversion-gen.todo
mkdir -p $(dirname .make/_output/bin/conversion-gen)
echo k8s.io/kubernetes/federation/apis/federation/v1beta1 >> .make/_output/bin/conversion-gen.todo
mkdir -p $(dirname .make/_output/bin/conversion-gen)
echo k8s.io/kubernetes/pkg/apis/apps/v1alpha1 >> .make/_output/bin/conversion-gen.todo
mkdir -p $(dirname .make/_output/bin/conversion-gen)
echo k8s.io/kubernetes/pkg/apis/authentication/v1beta1 >> .make/_output/bin/conversion-gen.todo
mkdir -p $(dirname .make/_output/bin/conversion-gen)
echo k8s.io/kubernetes/pkg/apis/authorization/v1beta1 >> .make/_output/bin/conversion-gen.todo
mkdir -p $(dirname .make/_output/bin/conversion-gen)
echo k8s.io/kubernetes/pkg/apis/autoscaling/v1 >> .make/_output/bin/conversion-gen.todo
mkdir -p $(dirname .make/_output/bin/conversion-gen)
echo k8s.io/kubernetes/pkg/apis/batch/v1 >> .make/_output/bin/conversion-gen.todo
mkdir -p $(dirname .make/_output/bin/conversion-gen)
echo k8s.io/kubernetes/pkg/apis/batch/v2alpha1 >> .make/_output/bin/conversion-gen.todo
mkdir -p $(dirname .make/_output/bin/conversion-gen)
echo k8s.io/kubernetes/pkg/apis/certificates/v1alpha1 >> .make/_output/bin/conversion-gen.todo
mkdir -p $(dirname .make/_output/bin/conversion-gen)
echo k8s.io/kubernetes/pkg/apis/componentconfig/v1alpha1 >> .make/_output/bin/conversion-gen.todo
/gofiles.mk.stamp', needed by `pkg/apis/extensions/v1beta1/zz_generated.conversion.go'.  Stop.
make[1]: Leaving directory `/home/k8s/zhangke/kubernetes'
make: *** [generated_files] Error 2

**Comment by 249043822** [comment]
@thockin, Now it's works. Before i only did ftp kubernetes package from my windows to ubuntu linux, it did not work and get above error;I git from the github directly in ubuntu linux and do make, it works, it's very unthinkable, do you know the differences? thanks

**Comment by thockin** [comment]
Can you do a diff -ruN of the two trees?

**Comment by smarterclayton** [comment]
I'm seeing this as well:

```
     Finished prerequisites of target file `federation/apis/federation/v1beta1/zz_generated.conversion.go'.
    Must remake target `federation/apis/federation/v1beta1/zz_generated.conversion.go'.
mkdir -p $(dirname .make/_output/bin/conversion-gen)
echo k8s.io/kubernetes/federation/apis/federation/v1beta1 >> .make/_output/bin/conversion-gen.todo
    Successfully remade target file `federation/apis/federation/v1beta1/zz_generated.conversion.go'.
    Considering target file `pkg/api/v1/zz_generated.conversion.go'.
      Pruning file `_output/bin/conversion-gen'.
      Pruning file `.make/pkg/api/v1/gofiles.mk.stamp'.
      Pruning file `pkg/api/v1/backward_compatibility_test.go'.
      Pruning file `pkg/api/v1/conversion.go'.
      Pruning file `pkg/api/v1/conversion_test.go'.
      Pruning file `pkg/api/v1/conversion_volumesource_test.go'.
      Pruning file `pkg/api/v1/defaults.go'.
      Pruning file `pkg/api/v1/defaults_test.go'.
      Pruning file `pkg/api/v1/doc.go'.
      Pruning file `pkg/api/v1/generated.pb.go'.
      Pruning file `pkg/api/v1/meta.go'.
      Pruning file `pkg/api/v1/register.go'.
      Pruning file `pkg/api/v1/types.go'.
      Pruning file `pkg/api/v1/types_swagger_doc_generated.go'.
      Pruning file `.make/pkg/api/gofiles.mk.stamp'.
      Pruning file `pkg/api/context.go'.
      Pruning file `pkg/api/context_test.go'.
      Pruning file `pkg/api/conversion.go'.
      Pruning file `pkg/api/conversion_test.go'.
      Pruning file `pkg/api/copy_test.go'.
      Pruning file `pkg/api/deep_copy_test.go'.
      Pruning file `pkg/api/defaults.go'.
      Pruning file `pkg/api/doc.go'.
      Pruning file `pkg/api/field_constants.go'.
      Pruning file `pkg/api/generate.go'.
      Pruning file `pkg/api/generate_test.go'.
      Pruning file `pkg/api/helpers.go'.
      Pruning file `pkg/api/helpers_test.go'.
      Pruning file `pkg/api/mapper.go'.
      Pruning file `pkg/api/meta.go'.
      Pruning file `pkg/api/meta_test.go'.
      Pruning file `pkg/api/ref.go'.
      Pruning file `pkg/api/ref_test.go'.
      Pruning file `pkg/api/register.go'.
      Pruning file `pkg/api/requestcontext.go'.
      Pruning file `pkg/api/resource_helpers.go'.
      Pruning file `pkg/api/resource_helpers_test.go'.
      Pruning file `pkg/api/serialization_proto_test.go'.
      Pruning file `pkg/api/serialization_test.go'.
      Pruning file `pkg/api/types.go'.
      Considering target file `.make/false/gofiles.mk.stamp'.
       File `.make/false/gofiles.mk.stamp' does not exist.
       Looking for an implicit rule for `.make/false/gofiles.mk.stamp'.
       No implicit rule found for `.make/false/gofiles.mk.stamp'.
       Finished prerequisites of target file `.make/false/gofiles.mk.stamp'.
      Must remake target `.make/false/gofiles.mk.stamp'.
make[1]: *** No rule to make target `.make/false/gofiles.mk.stamp', needed by `pkg/api/v1/zz_generated.conversion.go'.  Stop.
```

It appears to be the first file I try to regenerate that fails (I don't have federation changes, just core API).

**Comment by thockin** [comment]
Where is the "false" coming from?  The tree under .make shadows the code
tree - ain't no "false" directory...

**Comment by zizhuo-yan** [comment]
Hi，I have met the same problem. firstly , I use `make clean` & `rm -fr _output`. Then use cmd `dos2unix` and excute recursively, now it works.  

[aaa@server1 kube]$ bash hack/update-codecgen.sh 
Building dependencies
Building codecgen
+++ [0527 16:24:19] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [0527 16:24:20] Generating bindata:
    test/e2e/generated/gobindata_util.go
+++ [0527 16:24:21] Building go targets for linux/amd64:
    cmd/libs/go2idl/deepcopy-gen
+++ [0527 16:24:27] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [0527 16:24:27] Generating bindata:
    test/e2e/generated/gobindata_util.go
+++ [0527 16:24:27] Building go targets for linux/amd64:
    cmd/libs/go2idl/defaulter-gen
+++ [0527 16:24:32] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [0527 16:24:32] Generating bindata:
    test/e2e/generated/gobindata_util.go
+++ [0527 16:24:33] Building go targets for linux/amd64:
    cmd/libs/go2idl/conversion-gen
+++ [0527 16:24:39] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [0527 16:24:39] Generating bindata:
    test/e2e/generated/gobindata_util.go
+++ [0527 16:24:40] Building go targets for linux/amd64:
    cmd/libs/go2idl/openapi-gen
processing ./pkg/storage/testing/types.go
processing ./pkg/kubectl/testing/types.go
processing ./pkg/controller/garbagecollector/metaonly/types.go
processing ./pkg/apiserver/testing/types.go
processing ./pkg/apis/storage/v1beta1/types.go
processing ./pkg/apis/rbac/v1alpha1/types.go
processing ./pkg/apis/policy/v1beta1/types.go
processing ./pkg/apis/imagepolicy/v1alpha1/types.go
processing ./pkg/apis/extensions/v1beta1/types.go
processing ./pkg/apis/certificates/v1alpha1/types.go
processing ./pkg/apis/batch/v2alpha1/types.go
processing ./pkg/apis/batch/v1/types.go
processing ./pkg/apis/autoscaling/v1/types.go
processing ./pkg/apis/authorization/v1beta1/types.go
processing ./pkg/apis/authentication/v1beta1/types.go
processing ./pkg/apis/apps/v1beta1/types.go
processing ./federation/apis/federation/v1beta1/types.go
processing ./cmd/libs/go2idl/client-gen/test_apis/testgroup/v1/types.go
processing ./cmd/kubernetes-discovery/pkg/apis/apiregistration/v1alpha1/types.go

**Comment by thockin** [comment]
Were any files actually in DOS format?
