### ISSUE TITLE
Petset wont run in a single host mode

### ISSUE THREAD

**Issue by venkatramachandran** [kubernetes/kubernetes#30593]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you found any duplicates, you should instead reply there or use the :+1: icon in the upper-right of the issue message):
`lookup on 8.8.8.8:53: no such host`
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.0.6480+b7e87917462559-dirty", GitCommit:"b7e879174625599c8c232f9d7e9bed9b7e7a9998", GitTreeState:"dirty", BuildDate:"2016-08-10T17:02:20Z", GoVersion:"go1.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.0.6480+b7e87917462559-dirty", GitCommit:"b7e879174625599c8c232f9d7e9bed9b7e7a9998", GitTreeState:"dirty", BuildDate:"2016-08-10T17:02:20Z", GoVersion:"go1.6", Compiler:"gc", Platform:"linux/amd64"}

```

**Environment**:
- **Cloud provider or hardware configuration**: 3 GB RAM, 60 GB hard disk
- **OS** (e.g. from /etc/os-release): `Ubuntu 14.04.1 LTS`
- **Kernel** (e.g. `uname -a`): `Linux vagrant 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**:
- **Others**:

**What happened**:
I ran a single node cluster version using hack/local-up-cluster.sh and tried running petset examples provided - both galera and redis. The `peer-finder` keeps complaining with the following error : `lookup <service> on 8.8.8.8:53: no such host` where service is either `redis` or `galera`.

**What you expected to happen**:
Expect the petset to start properly.

**How to reproduce it** (as minimally and precisely as possible):
Run a single node cluster using hack/local-up-cluster.sh and run the petset example.

**Anything else do we need to know**:

**Comment by chrislovecnm** [comment]
Is kube-dns installed? Looks like you have a DNS problem. How is your cluster DNS setup?

**Comment by venkatramachandran** [comment]
Thanks for pointing this out. kube-dns was not started properly. 
Solved the issue by starting kube-dns (by setting `KUBE_ENABLE_CLUSTER_DNS=true` and `KUBE_DNS_SERVER_IP=<IP>`).
Closing this issue.
