### ISSUE TITLE
[ubuntu14.04 k8s cluster installtion]use kube-up.sh setup Kubernetes cluster,but can't find service in other node 

### ISSUE THREAD

**Issue by openshiftsunshine** [kubernetes/kubernetes#30604]
I use  kube-up.sh setup Kubernetes cluster(1.3.4), and use deployAddons.sh setup dashboard and dns. 
http://kubernetes.io/docs/getting-started-guides/ubuntu/
after that,  i found the dashboard work well. but i can not find service in  other node.
i create two busybox pod in two nodes, i  found  i can not ping each other. 

root@SIA1000076127:~/examples# ps -ef | grep docker
root      73175      1  0 10:22 ?        00:00:01 /usr/bin/dockerd -H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock --bip=172.16.10.1/24 --mtu=1450 --raw-logs

root@SIA1000076127:~/examples# kubectl get pods,services --all-namespaces -o wide
NAMESPACE     NAME                                READY           STATUS        RESTARTS        AGE       IP            NODE
default       busybox                             1/1             Running       1               57m       172.16.78.2   10.119.39.42
default       busybox1                            1/1             Running       0               11s       172.16.10.3   10.119.50.192
kube-system   kube-dns-v17.1-5lpox                3/3             Running       3               59m       172.16.25.2   10.119.51.137
kube-system   kubernetes-dashboard-v1.1.0-wpp76   1/1             Running       1               59m       172.16.10.2   10.119.50.192
NAMESPACE     NAME                                CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE       SELECTOR
default       kubernetes                          192.168.3.1     <none>        443/TCP         1h        <none>
default       redis-master                        192.168.3.170   <none>        6379/TCP        57m       name=redis-master
kube-system   kube-dns                            192.168.3.10    <none>        53/UDP,53/TCP   59m       k8s-app=kube-dns
kube-system   kubernetes-dashboard                192.168.3.193   <none>        80/TCP          59m       k8s-app=kubernetes-dashboard

root@SIA1000076127:~/examples# kubectl  exec -it busybox -- nslookup redis-master
Server:    192.168.3.10
Address 1: 192.168.3.10

nslookup: can't resolve 'redis-master'
error: error executing remote command: error executing command in container: Error executing in Docker Container: 1

root@SIA1000076127:~/examples# kubectl exec -it busybox -- ping 172.16.10.3
PING 172.16.10.3 (172.16.10.3): 56 data bytes

root@SIA1000076127:~/examples# kubectl exec -it busybox1 -- ping 172.16.78.2
PING 172.16.78.2 (172.16.78.2): 56 data bytes

**Comment by xiangpengzhao** [comment]
sig/network

**Comment by xiangpengzhao** [comment]
Which network plugin are you using? Can you ping from host node to the pod on the other node?

I would like to close this issue since it's not updated a long time. Feel free to re-open it if you still face this issue.

@thockin
