### ISSUE TITLE
Image Signing Support

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/kubernetes#30603]
these days, there is a proposal https://github.com/kubernetes/kubernetes/pull/27129 states we should be able to do an image review, for example, to ensure that the image does not have any vulnerabilities, we may set up an Clair instance, and enabling an admission controller to query its api to verify this image is safe to run.

However there is one thing more to consider as well, there is a concept which is named [Docker Content Trust](https://blog.docker.com/2015/08/content-trust-docker-1-8/), it is used to ensure we always get the correct image, the _correct_ means we are pulling images from the right source, and it is exactly pushed by some people(including CI).

I did not get the answer clearly on how will this be involved in, for example, the `DockerInterface` may introduce another method, something like `VerifyImage`, or it could be part of `PullImage`.

cc @erictune @liggitt

**Comment by erictune** [comment]
Cool demonstration that DCT is working, @nhlfr !

Closing since I think that answers the original question.

**Comment by zhouhaibing089** [comment]
Docker content trust is one layer of image signing, what I would like to raise here should be more generic, for example, we may sign the image when the CI build a release and then with some way, we want to ensure our workload would only run images from those images signed by CI, thus people could not run any intermediate build on production, I am not sure I made my statements clear, basically I want an ability to check something before it get run but after it get pulled..

**Comment by erictune** [comment]
You can make it so that only CI has permission to push to a certain repository, and then use image review (#27129) to require images from that repository.

Or you can have CI write out just the signatures of the image SHAs to some storage bucket, and then use image review (#27129) to require all images that are run have SHA that is in that storage bucket.

Or you could write a docker auth plugin to verify the signature at the time that the image is run:
https://docs.docker.com/engine/extend/plugins_authorization/

**Comment by nhlfr** [comment]
Agree with @erictune and I think also that any kind verifying images should be done by Docker, not k8s.

**Comment by zhouhaibing089** [comment]
@erictune IIUC, the imagereview concept is something that verifies images on the fly, that's to say, the images need not to be pulled firstly.

> You can make it so that only CI has permission to push to a certain repository.

CI generally creates many intermediate builds, It would be unexpected to run those images, if I want to strictly separate them, then I have to push intermediate builds and release build to different repositories, and only this way, I can say only images from the given repositories are allowed to run on production.

> Or you can have CI write out just the signatures of the image SHAs to some storage bucket

That is interesting, but without the image get pulled, how can I get the image SHA.

> Or you could write a docker auth plugin to verify the signature at the time that the image is run.

Thanks for this tip.

**Comment by zhouhaibing089** [comment]
@nhlfr I partly agree with your idea. 

Just to compare with Openstack, libvirt does not necessary care about all the image verification, I think it is true for docker as well. Docker content trust enables some verification to say docker daemon would only run the images with the correct signature, it is something common, but let's say image signing, I do not think docker community would support this(k8s does not necessary support this as well, but nice to have an interface to make it implementable by downstream, I am not sure whether the plugins authorization that @erictune mentioned is the interface that docker exposed, will to get some study there). what do you think?

**Comment by erictune** [comment]
> > Or you can have CI write out just the signatures of the image SHAs to some storage bucket

>That is interesting, but without the image get pulled, how can I get the image SHA.

You don't need to pull the image.  You just need to check the image's manifest.  You can get just the manifest from the [Docker Registry API](https://docs.docker.com/registry/spec/api/), using the image name and tag, and the manifest includes the SHA.   This works well if you can treat tags as immutable.

**Comment by zhouhaibing089** [comment]
@erictune Uh, that makes sense, just one more question, what if the image is private, and the call the api may get the unauthorized response. considering such cases, some verification may be problematic.

**Comment by erictune** [comment]
That is a pickle.

**Comment by zhouhaibing089** [comment]
@erictune yeah, it is, considering k8s has the pull secrets so that k8s is able to run some private images, to make this functionality complete, we may add the secret in webhook call as well, so the data would be:

1.  ImageName
2.  Annotations
3.  Pull Secrets

**Comment by zhouhaibing089** [comment]
Ref: https://github.com/kubernetes/kubernetes/issues/31524

**Comment by erictune** [comment]
I commented on that issue.

**Comment by aurcioli-handy** [comment]
It's unclear to me how DCT is supported in Kubernetes. When DCT is enabled Docker will only pull signed images. This is not the default behavior of Kubernetes. Is there a way to turn on DCT per deployment and specify Notary servers to use?

**Comment by gambol99** [comment]
@nhlfr .. I have to agree with @aurcioli-handy ... it's not clear how kubernetes supports trusted images via notary. There doesn't to be any daemon option on docker to enable checking trust by default and the only options i can see are via environment variable (DOCKER_CONTENT_TRUST) or --disable-content-trust on the docker pull. I'm guessing it's some option passed to daemon via cli. The example you gave ran without error on our cluster and it doesn't suggest a means of enabling trust or setting the notary server url ... Perhaps i'm just missing something!!

**Comment by u2takey** [comment]
@erictune i have some question with @gambol99  and @aurcioli-handy , would you pls help to clarify? plus: I cannot  repeat  that "Cool demonstration that DCT is working" by @nhlfr .

**Comment by lucab** [comment]
For reference, the demo in @nhlfr comment is completely unrelated to Content Trust because `docker/trusttest:latest` is not a signed tag (`notary.docker.io does not have trust data for docker.io/docker/trusttest`).

**Comment by unullmass** [comment]
Is there a way to pass Docker Content Trust preferences to the Docker Engine on the K8S Minions via the Image Policy settings in the pod yaml?

**Comment by dims** [comment]
@wu105 - `somehow has to pass the information to docker` ... do you see support in Docker public API to do this sort of stuff?

**Comment by dims** [comment]
long-term-issue (note to self)

**Comment by wu105** [comment]
@dims Is "support in Docker public API" a kubernetes feature?  At this moment, I am looking for how to configure kuibernetes nodes (statically) so that they will  verify docker images when starting containers.

**Comment by dims** [comment]
@unullmass which of these steps was a code change in the kubernetes repository? looks like the changes were mainly around how/what you configure docker daemon with. peeking at [1]

Right?

[1] https://github.com/unullmass/img-authz-plugin

**Comment by trishankatdatadog** [comment]
I agree 100%: it would be nice to have k8s at least pass the relevant information to docker to support DCT. It's fairly surprising that this cannot be easily done right now.

**Comment by unullmass** [comment]
> @unullmass which of these steps was a code change in the kubernetes repository? looks like the changes were mainly around how/what you configure docker daemon with. peeking at [1]
> 
> Right?
> 
> [1] https://github.com/unullmass/img-authz-plugin

@dims You are right. No changes to K8s codebase. As part of our efforts, we were not allowed to modify the K8s codebase, so this was the only possible solution.

FWIW, I recall looking into options of add-ons to K8s. Would changes in [this](https://kubernetes.io/docs/concepts/extend-kubernetes/extend-cluster/#api-access-extensions) scope help fulfil this requirement?

**Comment by wu105** [comment]
@unullmass Would you please share your implementation of the Image Authorization Plugin?  It would be a good start point for us to get some experience with kubernetes under DCT.

**Comment by dims** [comment]
@wu105 see the URL in the previous comment? :)

**Comment by wu105** [comment]
@dims (also @unullmass) I did check https://github.com/unullmass/img-authz-plugin, its master branch is "even with cpdevws/img-authz-plugin" and I see no other branches, tags.  I found no reference in the code/doc on the registry/notary mapping, or the environment variables DOCKER_CONTENT_TRUST and DOCKER_CONTENT_TRUST_SERVER.

**Comment by dims** [comment]
Also see https://github.com/kubernetes/kubernetes/issues/63704

**Comment by sftim** [comment]
I'd like to be able to run a cluster with different kinds of nodes (maybe some are using Docker, some are using Kata Containers). In one namespace I might want to use both container runtimes but make sure that every Pod in that namespace has images signed via something I trust.

With that in mind, I don't think it's enough to rely on a Docker-specific approach.

**Comment by trishankatdatadog** [comment]
@sftim This is why @justincormack is working on making an [OCI standard for TUF](https://github.com/containerd/cri/issues/624#issuecomment-515173189). Stay tuned...

**Comment by sftim** [comment]
Still wanted
/remove-lifecycle stale

**Comment by wu105** [comment]
This issue was openned in 2016, but it is still not clear to me what direction we are going on this.

If we are using Docker client directly, to have images' signature verified, all we need to do are the following:

- define a bunch of environment variables such as DOCKER_CONTENT_TRUST

- make sure that a bunch of relevant files exist, usually under .docker and .notary

Then we can proceed with docker client as usual otherwise.
The docker client will determine when and how to verify the images, and will print additional information regarding the verification results as fit.  There is no need to reconfigure or restart the docker daemon or directly telling the docker client how to interact with the notary, registry, and the docker daemon differently.

The kubernetes support for verifying images' signature probably should allow the user to pass the above two, i.e., a collection of environment variables and a collection of files to the docker client, specified similar to image pulling secrets.   Kubernetes should then be responsible to make those available to the docker client,  in ways also similar to image pulling secrets, invoke the docker client as usual otherwise, and then log the content trust related output from the docker client.  Should this be the way we understand and implement the kubernetes support for image signature verification?

**Comment by sftim** [comment]
When documenting this, bear in mind the [content guidance](https://kubernetes.io/docs/contribute/style/content-guide/#whats-allowed) on 3rd party projects and content.

**Comment by yuzp1996** [comment]
DCT is a very good function for everyone, I think k8s will be more security if it can use this function with DCT

**Comment by trishankatdatadog** [comment]
I understand that the pandemic has thrown a wrench into everything, but I'd be happy to see at least a GPG signature.

**Comment by jlk** [comment]
The last time I tried to manually validate a DCT-signed image, I was unable to. It's easy to sign an image with DCT, but that's of little value when you can't identify and validate that signature. So with that said I'd personally give DCT on k8s a -1.

GPG is way more interesting - long a recognized 3rd party standard, well documented, fairly easy to use. rkt had (has?) [solid support](https://coreos.com/rkt/docs/latest/signing-and-verification-guide.html) for it, and IMHO is the correct way forward.

**Comment by trishankatdatadog** [comment]
> GPG is way more interesting - long a recognized 3rd party standard, well documented, fairly easy to use. rkt had (has?) [solid support](https://coreos.com/rkt/docs/latest/signing-and-verification-guide.html) for it, and IMHO is the correct way forward.

My bad. I confused this with the issue of [signing k8s binaries](https://github.com/kubernetes/release/issues/914) in the first place

As for signing container images themselves, there should be nothing against supporting verification of GPG signatures, but it is 2020, and we can certainly do [much better](https://theupdateframework.io/). DCT/Notary-v1 was much better than GPG in terms of security, but not usability. We are discussing the Notary-v2 project on [GitHub](https://github.com/notaryproject) and [CNCF Slack](https://app.slack.com/client/T08PSQ7BQ/CQUH8U287), and welcome more participants there.

**Comment by xopham** [comment]
We ran into the same issue to ensure integrity and authenticity of docker images. Since we saw this issue in several projects and could not find a proper solution, we build an admission controller that integrates image signature verification via Notary (essentially very similar to DCT) and some extra features like allow listing. Project is available here: https://github.com/sse-secure-systems/connaisseur

Hope this helps and happy about feedback!

**Comment by trishankatdatadog** [comment]
> Hope this helps and happy about feedback!

Very interesting! Have you looked into [Portieris](https://github.com/IBM/portieris)?

In the meantime, you might be interested in our Notary-v2 GitHub [repo](https://github.com/notaryproject) and Slack [channel](https://app.slack.com/client/T08PSQ7BQ/CQUH8U287). If that becomes a widely-adopted standard, we might be able to convince k8s to use it...

**Comment by unullmass** [comment]
I recommend taking a look at this Docker plugin implementation (
https://github.com/intel-secl/secure-docker-plugin/tree/v2.2.0) to
understand how container create requests to the Docker Daemon API are
intercepted by this Authorization plugin and allowed or disallowed based on
image trust status (Notary check). This is part of a larger project called
Intel Security Libraries for Data Center (https://01.org/intel-secl) which
attempts to leverage platform hardware security features to provide
attestation, platform/workload integrity and confidentiality.

Disclosure: I am one of the devs on the team. :-)

**Comment by xopham** [comment]
@trishankatdatadog thanks!
We checked out Portieris and I think it's a great solution. Only roadblock seemed to be the lack of support for other registries which was critical for us: https://github.com/IBM/portieris/issues/51

Excited to see the work on Notary-v2! So much going on in the field :-) Might see if we can get involved there
