### ISSUE TITLE
Feature Request: Better Support for Persistent Volume on Local Disk

### ISSUE THREAD

**Issue by sparkthu** [kubernetes/kubernetes#30613]
In kubernetes 1.3, Petsets has already support applications such as zookeeper, kafka and so on. But they are all built on an unified storage system. Normally, we build zookeeper and kafka on distributed machines and use the disk on the machines. The safety of data should be guaranteed by zookeeper/kafka itself. I think it would be useful to let petsets use local storage .

**Comment by zhouhaibing089** [comment]
Ref: https://github.com/kubernetes/kubernetes/pull/30499

**Comment by bprashanth** [comment]
Of course, it just hasnt been done yet but there are proposals in flight: https://github.com/kubernetes/kubernetes/issues/7562, https://github.com/kubernetes/kubernetes/pull/30044

**Comment by ido** [comment]
Slightly off-topic but related, and not meant to reopen this thread:

For anyone trying to get the best of both worlds for k8s on GCE between `local-ssd` and `pd-ssd` disk types, one expensive ($) temporary workaround until this functionality has matured is to do asynchronous disk mirroring.  You could mirror changes to the local-ssd using asynchronous DRBD/RAID1-style block device replication.  Conceptually, you would have `local-ssdVol` and `pd-ssdVol`, and writes to `local-ssdVol` would get cached/coalesced into larger updates and then asynchronously written to `pd-ssdVol` as well.  (This is a type of naive write-ahead logging (WAL)... worse yet, if the difference in throughput between the two devices is sufficiently large, this is no better than doing periodic COW snapshots.)

The catch is that your workload can continue to take advantage of the higher IOPS/lower latency of local SSD read/write, but needs to have sufficient periods of low throughput to not persistently saturate pd-ssd disk type throughput for too long, which probably describes most local-ssd workloads
