### ISSUE TITLE
Remove duplicated assignments for NodeInfo.pods in schedulercache

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#30610]
There are duplicated assignments for nodeinfo.pods, one place is [here](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/schedulercache/node_info.go#L139) and the other one is [here](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/schedulercache/node_info.go#L147). 

I think we can remove one.

The related PR is #30585

@wojtek-t What do you think about it?

**Comment by wojtek-t** [comment]
Sure - let's remove the first one.

**Comment by m1093782566** [comment]
ok! :)

**Comment by m1093782566** [comment]
fixed. I am going to close this issue.
Thanks!
