### ISSUE TITLE
Feature request: Add selectors for persistent volumes

### ISSUE THREAD

**Issue by kayrus** [kubernetes/kubernetes#30612]
k8s v1.3.5

At the moment there is no way to create HostPath PV based on node's labels. For example I would like to create a PV on specific host which has a label.

Is there a way to implement that?

P.S. I know that it is not safe to create HostPath PV, and I know that there are gce, aws and azure persistent storage implementation, I know about NFS and ceph, but my current input data is to create PV based on hosts' labels.

Thanks in advance.

**Comment by xiangpengzhao** [comment]
The new WIP feature LocalStorage might help. Please follow:

ref: 
[Storage] Add support for persistent local storage #43640

See also:
https://github.com/kubernetes/kubernetes/pull/44897
`Alpha feature: Local volume plugin allows local directories to be created and consumed as a Persistent Volume.  These volumes have node affinity and pods will only be scheduled to the node that the volume is at.`

@thockin

**Comment by msau42** [comment]
Yes, we're adding a new local persistent volume source that requires a node selector to be specified.  A pod using the local volume will always land on a node that satisfies the node selector.

**Comment by msau42** [comment]
This is covered by the new local volume feature
/close
