### ISSUE TITLE
Flexvolume should read response only from stdout, not stderr

### ISSUE THREAD

**Issue by discordianfish** [kubernetes/kubernetes#30618]
Hi,

right now the flexvolume module combines stderr and stdout when reading the response of a flexvolume driver. Instead, it should read only from stdout and just log the stderr output.

The same reasoning for differentiating between stderr and stdout in all other tools apply: STDOUT is for regular, expected output which is the json based "API" in the case of flexvolume. STDERR on the other hand is for exceptional data, which would be any kind of logging in the flexvolume driver that can't be conveyed via the json based response (specifically in my current case it's debug logging).

**Comment by AdoHe** [comment]
@k8s-merge-robot This should not be a kubectl issue.  @kubernetes/sig-storage ptal.

**Comment by chakri-nelluri** [comment]
Thanks @discordianfish Very Fair.. Will get the fix in after the rework changes are in 1.4

**Comment by discordianfish** [comment]
/remove-lifecycle stale
Unless this was fixed somewhere else, this should be still valid.
@chakri-nelluri Did you get to work on this?

**Comment by chakri-nelluri** [comment]
@discordianfish Today's behavior: Error status goes to stderr and success status goes to stdout. There is nothing wrong the current behavior.

There are drivers which are assuming this behavior and unless there is strong compelling reason, I would not recommend changing this behavior.

**Comment by discordianfish** [comment]
> Today's behavior: Error status goes to stderr and success status goes to stdout. There is nothing wrong the current behavior.

Yes that was the goal. It wasn't the case when I opened this issue. So going to assume this is fixed. Thanks!
