### ISSUE TITLE
Controllers hotloop on unexpected API server rejections

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#30629]
Many controllers handle retries in an adhoc manner.  We now have a `workqueue.RateLimitingInterface` for this purpose.
- [x] replication controller: https://github.com/kubernetes/kubernetes/pull/30626
- [x] replica set: https://github.com/kubernetes/kubernetes/pull/33092
- [x] daemonset #32210
- [x] certificates: https://github.com/kubernetes/kubernetes/pull/32664
- [x] deployments: https://github.com/kubernetes/kubernetes/pull/28684
- [x] endpoints: https://github.com/kubernetes/kubernetes/pull/32776
- [x] pod disruption budget: https://github.com/kubernetes/kubernetes/pull/32850 
- [x] jobs: https://github.com/kubernetes/kubernetes/pull/32785

**Comment by deads2k** [comment]
@kubernetes/rh-cluster-infra @ncdc probably need to do a survey to find other offenders.

I'm still trying to work out what happens to controllers which are denies on pod changes and *don't* retry.  They don't hotloop, but are they stuck until the resync comes?  There was a pull to remove resycning and people were declaring their controllers safe, but if I'm reading the code correctly, those people are mistaken.

**Comment by bgrant0607** [comment]
Related: #21912

cc @erictune @pwittrock

**Comment by derekwaynecarr** [comment]
I agree we need a roll-up mechanism, but we definitely need to move all pertinent controllers to a rate limited queue in interim.

**Comment by erictune** [comment]
@foxish did you say you looked at a rate limiting issue recently?  Does it relate to this issue?

**Comment by foxish** [comment]
@erictune I did fix for petsets, and a bug which affects the rate-limiting work-queue implementation. They're all related in that I think the effort now is just switching the other controllers to use the same work-queue implementation with back-off.

**Comment by derekwaynecarr** [comment]
I would like this to be fixed in Kubernetes 1.5, and will look to get people from our team setup to fix it.  Community help is welcome in the interim.

**Comment by m1093782566** [comment]
@deads2k @derekwaynecarr 

I am interested in this job and I find there are still some controllers which are still using `workqueue.Type` instead of workqueue.RateLimitingInterface. Here comes with the list,

- [ ] certificates
- [ ] disruption
- [ ] endpoints
- [ ] job
- [ ] replica set (@deadsk will fix it?)

If there is no volunteer, I will help to fix them.

**Comment by deads2k** [comment]
> Of course, before doing it, I would like to receive comments from you :)

Help would be very welcome.  I'd recommend trying to tackle a single controller first.  You can take a look at the daemonset controller to see some of the tweaks

 1.  Waiting for caches to be ready: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemoncontroller.go#L245
 1.  Processing and error handling methods: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemoncontroller.go#L261-L284

**Comment by m1093782566** [comment]
@deads2k very appreciated!

**Comment by derekwaynecarr** [comment]
@m1093782566 -- please cc me and @deads2k on any PRs you open so we can track the work.  A PR per controller you tackle is ideal.  Thanks!

**Comment by m1093782566** [comment]
sure

**Comment by m1093782566** [comment]
@deads2k @derekwaynecarr 

The first PR for fixing certificate controller is #32664, PTAL.

I will open other PRs later.

**Comment by m1093782566** [comment]
@deads2k @derekwaynecarr

The 2nd PR for fixing endpoint controller hot loop is #32776 , PTAL.

**Comment by m1093782566** [comment]
@deads2k @derekwaynecarr

The 3nd PR for fixing job controller hot loop is #32785, PTAL.

**Comment by m1093782566** [comment]
The 3nd PR for fixing job controller hot loop is #32850

**Comment by m1093782566** [comment]
@deads2k 

> replica set controller: (this one doesn't seem to retry on failed pod creates. I wonder why that is)

When I look at the code of replication controller and job controller(as they are familiar with replica set controller), I find they both retry on failed pod creates.

1. replication controller, see https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller.go#L601

2. job controller, see https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/jobcontroller.go#L422

So, I assume replica set controller doesn't retry is a wrong behavior?

**Comment by deads2k** [comment]
> So, I assume replica set controller doesn't retry is a wrong behavior?

Yeah, it's probably wrong or unintentional.

**Comment by ncdc** [comment]
Looks like everything is done.
