### ISSUE TITLE
Consider renaming `rollout status`

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#30627]
`kubectl rollout status` is used for watching a deployment and reports back its status.
@fabianofranz notes:
```
I'd vote for `kubectl rollout watch` or `kubectl rollout status --watch` (exits right away without the flag) for consistency.
```
Makes sense to me - @kubernetes/kubectl @kubernetes/deployment thoughts?

**Comment by kargakis** [comment]
I think I prefer the second proposal, ie. adding a `--watch` flag (defaulting to true or false is up for discussion too:) )

**Comment by fabianofranz** [comment]
+1 to second option.

**Comment by AdoHe** [comment]
+1 for the second option.
