### ISSUE TITLE
DNS healthcheck kills kube-dns if dnsmasq is hung

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#30633]
#27652 changed DNS healthz to check both dnsmasq and kube-dns.  But having kube-dns container's healthz go thru dnsmasq at all is wrong - if dnsmasq is hung, this will restart the kube-dns container, rathe rthan dnsmasq

We should have 2 healthz ports (or 2 URLs on the same port) - one for dnsmasq one for kube-dns.  Maybe exec-healthz can expand to check multiple commands on multiple URLs, or maybe we should just run 2 healthz containers in the pod.

This has not been observed, so prio is set accordingly.

@girishkalele

**Comment by MrHohn** [comment]
On this now. Exec-healthz currently is not able to check on multiple URLs.
The plan is to use one healthz container to execute two exec-healthz processes to listen on two ports.
