### ISSUE TITLE
kubectl run option to mount storage

### ISSUE THREAD

**Issue by sferich888** [kubernetes/kubernetes#30645]
FEATURE REQUEST
`kubectl run` should provide options to mount a PVC or PV for situations where I simply want to start a pod and provide it storage for the duration of what I am doing / testing.

**Comment by ncdc** [comment]
cc @kubernetes/kubectl @kubernetes/rh-ux

**Comment by liggitt** [comment]
Picking the subset of supported volume options to plumb through the run generators is going to be tough

**Comment by ncdc** [comment]
Agreed. See https://bugzilla.redhat.com/show_bug.cgi?id=1367200#c7

**Comment by smarterclayton** [comment]
What % of users will need to set PVC during run?  emptyDir?  Secrets?  ConfigMaps?

If the % is low, that's more of an argument for `kubectl run --edit`, not adding more flags here.

**Comment by discordianfish** [comment]
I'm currently trying to figure out how to do various operational things. For example fixing file system corruption or the need to resize volumes etc. For all these things, it seems to me the idiomatic k8s way would be to spin up a interactive 'toolbox' container with the volumes attached that need attention.

For that, it seems this feature request would be a good approach. Maybe though I miss something and there is a better way?

**Comment by kargakis** [comment]
How about adding a `kubectl set volume` command instead of extending `run`?

**Comment by kargakis** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by discordianfish** [comment]
Or `kubectl run -ti -f manifest.yaml`, that would work fine for me too.

**Comment by sferich888** [comment]
I see this being needed for operational tasks, a good example of this is job (well its probably a bad example as the job yaml could define the volume), however the pod in question that you want to run, could run and output its data (diagnostics for example) to a volume and the data could be examined using another pod (like httpd, that just needs to start up and mount the volume from the job).

**Comment by cloudbow** [comment]
Kubectl should have it if I want to like read from the file system and upload things to the artifact server..

**Comment by MichaelSp** [comment]
```
$ kubectl run -ti -f resources/debug-pod.yaml
Error: unknown shorthand flag: 'f' in -f
```

**Comment by pjanuario** [comment]
In my particular case I have a cronjob who store some data into a PVC once in a while I need to access the PVC and there by would be useful to use kubectl run command to create a pod with a PVC mounted.

**Comment by nathanweeks** [comment]
I'd like to be able to run command-line-driven bioinformatics applications and workflows via containers (e.g., http://biocontainers.pro/), mounting a given shared file system (and/or NFS home directory) that will contain the input data sets & receive the output results.

Basically, obviate the need to run a traditional HPC cluster with a workload manager like SLURM along side the Kubernetes cluster for web apps.

**Comment by sneumann** [comment]
Another use case is to repair/kick a database, where the DB files on disk are corrupted. Needs to run the DB maintenance tools in the same environment, but without the DB daemon running. Yours, Steffen

**Comment by discordianfish** [comment]
Not sure if everyone is aware but you can create a pod manifest with tty and stdin true, then `kubectl apply .. && kubectl attach ..`. That's what I'm doing right now. But nicer tooling would be still great.

**Comment by donbowman** [comment]
/proc # strace ls -l
execve("/busybox/ls", ["ls", "-l"], 0x7ffcdc43ede8 /* 16 vars */) = 0
strace: [ Process PID=33 runs in 32 bit mode. ]
strace: WARNING: Proper structure decoding for this personality is not supported, please consider building strace with mpers support enabled.
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
getuid32()                              = 0
time([1551486393 /* 2019-03-02T00:26:33+0000 */]) = 1551486393 (2019-03-02T00:26:33+0000)
ioctl(0, TIOCGWINSZ, {ws_row=38, ws_col=120, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
brk(NULL)                               = 0x9768000
brk(0x9769000)                          = 0x9769000
lstat64(".", 0xffa6e374)                = 0
open(".", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
fstat(3, 0xffa6e378)                    = -1 EOVERFLOW (Value too large for defined data type)
close(3)                                = 0
write(2, "ls: can't open '.': Value too la"..., 58ls: can't open '.': Value too large for defined data type
) = 58
write(1, "total 0\n", 8total 0
)                = 8
exit(1)                                 = ?
+++ exited with 1 +++

**Comment by soltysh** [comment]
With the deprecation of majority of functionality in `kubectl run` to improve entry level UX, I'm going to close this request as won't fix. 
/close
