### ISSUE TITLE
FeatureRequest : Support for ConfigBlobs

### ISSUE THREAD

**Issue by iceandroidph** [kubernetes/kubernetes#30657]
Config Maps are good and works properly, but there are configuration that are not in Key Value format. 

It would be nice to be able to create a configblob and load a json file as configuration.

**Comment by iceandroidph** [comment]
Just some clarification. Config Blobs is not only json but, xml, yml or any flat file. Currently the work around is to mount a template and a find a replace script in the entrypoint. Although works, but can easily become a hacky script.

**Comment by kargakis** [comment]
@pmorie which SIG ends up owning ConfigMaps?

**Comment by bgrant0607** [comment]
@iceandroidph ConfigMap can already be used to deliver config files. Just put the data into a single value and use the configmap volume source.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#add-configmap-data-to-a-volume
