### ISSUE TITLE
Cleanup: Consistent capitalizations for "iptables"

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#30651]
Our codebase uses both `Iptables` and `IPTables`.  We should pick one and unify.  I think `IPTables` is probably more correct.

**Comment by asalkeld** [comment]
I can clean this up.

**Comment by thockin** [comment]
FYI there are some PRs in flight - might want to hold off a week :)

**Comment by asalkeld** [comment]
OK thanks @thockin
