### ISSUE TITLE
Use k8s-bot to re-run a specific test suite

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#30693]
When tests flake, for example, I can re-run all of the tests with `@k8s-bot test this issue #IGNORE`. I've heard that we have other commands for e.g. re-running unit tests, or re-running e2e tests. But there is more granularity:
- Jenkins GKE smoke e2e
- Jenkins GCE e2e
- Jenkins GCE Node e2e
- Jenkins unit/integration

and so on.

When tests flake, it would be nice to be able to re-run only the test suite that contained the flake, so that we have minimal turnaround time on the repeat run. Is there already a command that does something like this, or would it be useful to introduce a syntax like `@k8s-bot test [suite name]`?

**Comment by xiangpengzhao** [comment]
Currently k8s-ci-bot will tell us what tests flake and the rerun command for each. But it would be great to have a single command to rerun all flaky tests, e.g. `@k8s-bot rerun flaky tests`. WDYT? @fejta

cc @thockin

**Comment by thockin** [comment]
https://github.com/kubernetes/test-infra/issues/2174
