### ISSUE TITLE
kubelet container runtime cgroup detection

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#30702]
Per the sig-node discussion, if we add a remote container runtime, the kubelet has no way to know what cgroup to monitor for the summary api, or other use case/tools built on top of that API to do benchmarks to measure usage associated with that runtime.

We should decide if the kubelet should monitor the runtime cgroup (if any), and if it should, how it should get the value (i.e. via full cgroup path, pid detection, etc.).

/cc @kubernetes/sig-node

**Comment by yifan-gu** [comment]
One idea is to embed the PID/cgroup path in the `Version` response of the runtime. Maybe change the name `Version` to `Info` or something?

**Comment by vishh** [comment]
If the summary API is going to remain in kubelet as-is, without being moved
to a standalone cadvisor, then runtimes can provide its own usage as part
of CRI metrics maybe?

**Comment by euank** [comment]
xref #27097

If all the kubelet cares about is "this node has this much non-k8s-pod resource utilization" then the root cgroup + knowing pod cgroups is enough, and the runtime will just fit as some part of the root/system cgroup.

If metrics, monitoring, or what have you that cares about it is a third party system, then that system can either be configured with the right cgroup out of band, or the CRI could provide it to the kubelet just so systems like that could find it in a generic way.

I'm not convinced there's a real need for this information, just a few "nice-to-have" type things.

**Comment by resouer** [comment]
Just a note, for hypervisor based runtimes, it prefers to stick to one runtime cgroups (frakti use cgroupfs for example). So it will be nice if kubelet has a default cgroup type (perfect if it's cgroupfs, of course ).

**Comment by yujuhong** [comment]
Discussed in the sig-node meeting today. The conclusion is that since the runtime stats is purely for monitoring and/or testing, we do not want to support this through CRI. Instead, during node setup, the runtime cgroup can be passed to kubelet through the existing --runtime-cgroup flag.

Closing the issue.
