### ISSUE TITLE
`kubernetes/cluster/saltbase/install.sh` doesn't work on BSD/Darwin based systems

### ISSUE THREAD

**Issue by vromero** [kubernetes/kubernetes#30703]
Running `kubernetes/cluster/saltbase/install.sh` in Darwin (e.g: macos) or BSD (freebsd) won't work due to slight incompatibilities in `cp` and `sed`.

No need to work on it, I'm creating a PR to fix it.

**Comment by vromero** [comment]
Closed as per discussion in #30705.

**Comment by xiangpengzhao** [comment]
so it's okay to close this issue, Victor, right?

@thockin

**Comment by vromero** [comment]
yes
