### ISSUE TITLE
Handle logging in CRI

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#30709]
This issue is created to track logging/log management that's relevant to CRI (#28789). 

Related issues:
- #24677: general logging integration and pipeline in kubernetes.
- #27154: support of `kubectl logs`

@tmrts (thanks!) has volunteered to write up a proposal based on the discussions. Assigning the issue to him.

/cc @kubernetes/sig-node

**Comment by tmrts** [comment]
@yujuhong thanks for creating the issue, I'll submit the proposal in a few days :+1:

**Comment by dcowden** [comment]
@tmrts I would love to see the proposal when you have it.  We are rolling out a new Kubernetes based system.  I want to do things as consistently as possible with the 'new way' as we roll out, to minimize change later. 

Right now, we are writing logs to manually configured log volumes with the idea that k8s will eventually provide a log volume that's a drop-in substitute.

**Comment by coffeepac** [comment]
@dcowden I'm getting started on solving this problem now as well.  are you planning on open sourcing your work in any way?  I'm happy to contribute to what you're up to so we can start building a practical consensus on this.

**Comment by dcowden** [comment]
Hi @coffeepac 
Embarassingly I have nothing useful to share code-wise at this point, though I"m happy to share anything I make.

Right now, my efforts have been isolated to designing our way of working to be consistent with what k8s will do. So for example, I have created a bunch of base docker images that intentionally send logs to a "/logs" volume in the container, which i presume will later be a k8s logging volume, and configuring k8s to use the downward api to inject metadata.

I have not yet started work on the main 'code', which would be consuming the  metadata and the files using splunk.

**Comment by coffeepac** [comment]
@dcowden nothing to be embarrassed about!  glad you're open to sharing.

I spent a bunch of time walking through the discussions and am also trying to design something that will fit cleanly into what future k8s logging looks like.  All I have is a janky diagram with a couple of data streams ending in question marks.  And some streams that are probably wrong.

I'm picking up a bunch of legacy apps so was planning on mounting the common logs mount to an expected place in each container to receive the logs.  Saves some application dev time at application configuration cost.  

Are you planning on writing a splunk plugin or something more general that either writes to splunk TCP listener or a splunk file watcher?

And is there a SIG handling logging or maybe a WG being formed somewhere?

**Comment by dcowden** [comment]
@coffeepac We plan to install splunk UF on each k8s node, and write/configure splunk inputs to read the metadata and the log files from the local node.  We _think_ it is possible to configure splunk to do this, but I have not researched the details: i'm kind of hoping its possible without writing and/or running another daemon on the k8s nodes.

The main consideration so far that's turned out to be very tricky is getting the permissions correct on the log volumes.  we run docker with --userns-remap, and in addition we do not run applications as root. So the application needs write access to the log files, with some weirdo UID.  But then the host needs to have a rotation job ( which we'll also have to write) to clean them up.

**Comment by vishh** [comment]
A kubelet change is needed to expose additional metadata for logs. As
mentioned earlier, kubelet should be dumping Pod object into appropriate
pod logs directory - `/var/log/pods/<pod_uid>/.metadata`

**Comment by coffeepac** [comment]
@dcowden I've got a multi-container aggregator pod approach going as well.  Kafka is the first port of call for these logs so I have more flexibility to use something other then splunk UF.  I think I'm going to have a pod with three containers that runs as a daemon set:
 - log enricher (applies the metadata to each log event (what is an event, ie: stacktraces))
 - log shipper (splunk UF analog.  will be fluentd or filebeat or ??)
 - rotation job (hoping I can get by with logrotate or something well known)

I'm going to hit those permissions issues shortly and I have not a lot of experience with docker permissions settings.  There are, clearly, some issues with the above but I'm trying to decompose the problem into chunks that will cleanly integrate with future k8s reality.

**Comment by coffeepac** [comment]
@vishh I think we are both planning on using the downward API to land the .metadata file manually.  I know I am. I look forward to the kubelet providing this for free but I can't wait.

**Comment by dcowden** [comment]
+1

**Comment by feiskyer** [comment]
@tmrts Is there any progress on this? Looking forward to the proposal.

**Comment by coffeepac** [comment]
@dcowden so as a heads up, I'm abandoning my earlier approach.  there's enough information for my current needs in the current fluentd + kubernetes-metadata filter plugin.

**Comment by tmrts** [comment]
Sorry for the delay, see the proposal at #33111
