### ISSUE TITLE
NodeNotReady on docker rmi

### ISSUE THREAD

**Issue by xrow** [kubernetes/kubernetes#30712]
**What keywords did you search in Kubernetes issues before filing this one?**

IO, DOCKER, DOCKER RMI, NodeNotReady

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Do not know. I try BUG REPORT.

**Kubernetes version** (use `kubectl version`):
[root@admin01 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"a4463d9a1accc9c61ae90ce5d314e248f16b9f05", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"a4463d9a1accc9c61ae90ce5d314e248f16b9f05", GitTreeState:"clean"}

**Environment**:
- **Cloud provider or hardware configuration**:
  VMs on VMWARE
- **OS** (e.g. from /etc/os-release):
  CentOS 7
- **Kernel** (e.g. `uname -a`):
  [root@admin01 ~]# uname -a
  Linux admin01.intern.xxxx.de 3.10.0-327.28.2.el7.x86_64 #1 SMP Wed Aug 3 11:11:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
  ansible
- **Others**:
  overlayfs

**What happened**:
When the node becomes has higher IO consumption the node instantly becomes NodeNotReady on the admin. I am able to reproduce it all the time when running "docker rmi" wiht any image I don`t use anymore.

**What you expected to happen**:
Node should be up even, if I issue docker rmi.

**How to reproduce it** (as minimally and precisely as possible):
docker rmi [imageid]

**Anything else do we need to know**:
Maybe this is also a docker problem, but I can`t tell. I need someone to veryify.

I had the feeling that the system used all its resources to fullfill the need of docker rmi.

ionice and docker rmi did not help.

**Comment by dchen1107** [comment]
Thanks for reporting the issue. To help further understanding your problem, could you please provide the following information:

When Node is NotReady, please run command: kubectl describe nodes <node-id> and copy&paste the result here. Normally this will tell you why node is not ready.

What is your docker version?

**Comment by xrow** [comment]
> Is your docker daemon is still runnning when node is not ready?
Yes that is the case. After the docker rmi is completed the system works as normal again. During the docker rmi there is a high io useage which is guess is normal/expected.

`
[root@docker01 ~]# docker -v
Docker version 1.10.3, build 9419b24-unsupported
[root@docker01 ~]# yum info docker
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.netcologne.de
 * epel: ftp.nluug.nl
 * updates: ftp.plusline.de
Installed Packages
Name        : docker
Arch        : x86_64
Version     : 1.10.3
Release     : 44.el7.centos
Size        : 42 M
Repo        : installed
From repo   : extras
Summary     : Automates deployment of containerized applications
URL         : https://github.com/docker/docker
License     : ASL 2.0
Description : Docker is an open-source engine that automates the deployment of any
            : application as a lightweight, portable, self-sufficient container that will
            : run virtually anywhere.
            : 
            : Docker containers can encapsulate any payload, and will run consistently on
            : and between virtually any server. The same container that a developer builds
            : and tests on a laptop will run at scale, in production*, on VMs, bare-metal
            : servers, OpenStack clusters, public instances, or combinations of the above.
`

I will deliver the "kubectl describe" to a later point in time. 

Do those line help?
`
Aug 16 14:00:38 admin01 kube-controller-manager: I0816 14:00:38.781732    2036 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"docker02.intern..de", UID:"docker02.intern..de", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeNotReady' Node docker02.intern..de status is now: NodeNotReady
Aug 16 14:00:38 admin01 kube-controller-manager: E0816 14:00:38.784679    2036 event.go:193] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"docker02.intern..de.1469b87b7363302d", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"8569041", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Node", Namespace:"", Name:"docker02.intern..de", UID:"docker02.intern..de", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeNotReady", Message:"Node docker02.intern..de status is now: NodeNotReady", Source:api.EventSource{Component:"controllermanager", Host:""}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63606506393, nsec:0, loc:(*time.Location)(0x3371540)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63606945638, nsec:780924594, loc:(*time.Location)(0x3371540)}}, Count:6, Type:"Normal"}': 'events "docker02.intern..de.1469b87b7363302d" not found' (will not retry!)
Aug 16 14:00:39 admin01 kube-controller-manager: I0816 14:00:39.122576    2036 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"docker03.intern..de", UID:"docker03.intern..de", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeNotReady' Node docker03.intern..de status is now: NodeNotReady
Aug 16 14:00:39 admin01 kube-controller-manager: E0816 14:00:39.126624    2036 event.go:193] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"docker03.intern..de.1469941f8a56f06f", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"8556138", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Node", Namespace:"", Name:"docker03.intern..de", UID:"docker03.intern..de", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeNotReady", Message:"Node docker03.intern..de status is now: NodeNotReady", Source:api.EventSource{Component:"controllermanager", Host:""}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63606466416, nsec:0, loc:(*time.Location)(0x3371540)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63606945639, nsec:122530092, loc:(*time.Location)(0x3371540)}}, Count:5, Type:"Normal"}': 'events "docker03.intern..de.1469941f8a56f06f" not found' (will not retry!)
Aug 16 14:00:44 admin01 kube-controller-manager: I0816 14:00:44.434363    2036 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"docker01.intern..de", UID:"docker01.intern..de", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeNotReady' Node docker01.intern..de status is now: NodeNotReady
Aug 16 14:00:44 admin01 kube-controller-manager: E0816 14:00:44.446481    2036 event.go:193] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"docker01.intern..de.146a0e74ec83d638", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"8612678", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Node", Namespace:"", Name:"docker01.intern..de", UID:"docker01.intern..de", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeNotReady", Message:"Node docker01.intern..de status is now: NodeNotReady", Source:api.EventSource{Component:"controllermanager", Host:""}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63606600923, nsec:0, loc:(*time.Location)(0x3371540)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63606945644, nsec:433647846, loc:(*time.Location)(0x3371540)}}, Count:7, Type:"Normal"}': 'events "docker01.intern..de.146a0e74ec83d638" not found' (will not retry!)
`

**Comment by xrow** [comment]
I have more Information that might be helpfull this is from the k8 node durign the event.

`
Aug 18 01:11:59 docker01 kubelet: E0818 01:11:59.681920   31609 kubelet.go:2761] Error updating node status, will retry: error #0: client: etcd member http://192.168.255.4:2379 has no leader
Aug 18 01:12:06 docker01 kubelet: E0818 01:12:06.793043   31609 kubelet.go:2761] Error updating node status, will retry: error #0: client: etcd member http://192.168.255.4:2379 has no leader
Aug 18 01:12:13 docker01 kubelet: E0818 01:12:13.898659   31609 kubelet.go:2761] Error updating node status, will retry: error #0: client: etcd member http://192.168.255.4:2379 has no leader
Aug 18 01:12:21 docker01 kubelet: E0818 01:12:21.027654   31609 kubelet.go:2761] Error updating node status, will retry: error #0: client: etcd member http://192.168.255.4:2379 has no leader
Aug 18 01:12:26 docker01 kubelet: E0818 01:12:26.908431   31609 kubelet.go:2761] Error updating node status, will retry: nodes "docker01.intern..de" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
Aug 18 01:12:26 docker01 kubelet: E0818 01:12:26.908481   31609 kubelet.go:1199] Unable to update node status: update node status exceeds retry count
Aug 18 01:13:26 docker01 sshd[15581]: Connection closed by 192.168.255.1 [preauth]
Aug 18 01:13:31 docker01 kubelet: E0818 01:13:31.389482   31609 container_manager_linux.go:267] failed to detect process id for "docker" - failed to find pid of "docker": exit status 1
Aug 18 01:15:27 docker01 sshd[15981]: Connection closed by 127.0.0.1 [preauth]
Aug 18 01:15:45 docker01 kubelet: E0818 01:15:45.835098   31609 kubelet.go:2761] Error updating node status, will retry: nodes "docker01.intern..de" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
Aug 18 01:16:29 docker01 kubelet: E0818 01:16:29.138654   31609 event.go:193] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"docker01.intern..de.146b63f5471fe25e", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"8768444", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Node", Namespace:"", Name:"docker01.intern..de", UID:"docker01.intern..de", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientDisk", Message:"Node docker01.intern..de status is now: NodeHasSufficientDisk", Source:api.EventSource{Component:"kubelet", Host:"docker01.intern..de"}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63606976408, nsec:0, loc:(*time.Location)(0x3371540)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63607072589, nsec:135880435, loc:(*time.Location)(0x3371540)}}, Count:8, Type:"Normal"}': 'events "docker01.intern..de.146b63f5471fe25e" not found' (will not retry!)
`

**Comment by xrow** [comment]
Hello,

here is more information. The reason is the node reports:

´´´
[root@docker02 ~]# cat /var/log/messages | grep -i "NodeHasSufficientDisk"
Oct 18 02:16:13 docker02 kubelet: E1018 02:16:13.486754    7308 event.go:193] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"docker02.intern.de.147cdb6fab495d63", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"11769779", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Node", Namespace:"", Name:"docker02.intern..de", UID:"docker02.intern..de", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientDisk", Message:"Node docker02.intern..de status is now: NodeHasSufficientDisk", Source:api.EventSource{Component:"kubelet", Host:"docker02.intern..de"}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63611892850, nsec:0, loc:(*time.Location)(0x3422520)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63612346573, nsec:483838073, loc:(*time.Location)(0x3422520)}}, Count:10, Type:"Normal"}': 'events "docker02.intern..de.147cdb6fab495d63" not found' (will not retry!)
[root@docker02 ~]# cat /var/log/messages | grep -i "NodeHasSufficientDisk"
Oct 18 02:16:13 docker02 kubelet: E1018 02:16:13.486754    7308 event.go:193] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"docker02.intern..de.147cdb6fab495d63", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"11769779", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Node", Namespace:"", Name:"docker02.intern..de", UID:"docker02.intern..de", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientDisk", Message:"Node docker02.intern..de status is now: NodeHasSufficientDisk", Source:api.EventSource{Component:"kubelet", Host:"docker02.intern..de"}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63611892850, nsec:0, loc:(*time.Location)(0x3422520)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63612346573, nsec:483838073, loc:(*time.Location)(0x3422520)}}, Count:10, Type:"Normal"}': 'events "docker02.intern..de.147cdb6fab495d63" not found' (will not retry!)
´´´

The event get triggered by running:

´´´
docker rm -f $(docker ps -a -q -f status=exited)
´´´
on the maschine

**Comment by xrow** [comment]
@dchen1107 

What is your docker version? 
```
[root@docker01 ~]# docker -v      
Docker version 1.10.3, build cb079f6-unsupported
[root@docker01 ~]# docker info
Containers: 35
 Running: 35
 Paused: 0
 Stopped: 0
Images: 13
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.36.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 6
Total Memory: 16.5 GiB
Name: docker01.intern.hannover.de
ID: Y2ZE:KIKO:YBH2:5VOR:GAM5:6WCY:KLAZ:QINX:Z7ZS:5NWO:WSS2:4SMS
WARNING: bridge-nf-call-ip6tables is disabled
Registries: docker.io (secure)
```
Is your docker daemon is still runnning when node is not ready?
Yes.

Please let me know what other information you need.
