### ISSUE TITLE
kube-registry-proxy timeouts are too short

### ISSUE THREAD

**Issue by unixwitch** [kubernetes/kubernetes#30726]
**Is this a request for help?** No.

**What keywords did you search in Kubernetes issues before filing this one?** "registry proxy timeout"

---

**Is this a BUG REPORT or FEATURE REQUEST?** Bug report.

**Kubernetes version** (use `kubectl version`): 1.3.4, master

**Environment**:
- **Cloud provider or hardware configuration**: Rackspace Public Cloud
- **OS** (e.g. from /etc/os-release): CoreOS 1068.9.0
- **Kernel** (e.g. `uname -a`): 4.6.3-coreos
- **Install tools**: From scratch.
- **Others**:

**What happened**:

After setting up a private Docker registry using kube-registry-proxy 0.3, pushing to the repository fails for large images:

```
<exit 1> 284!klamath:~/tbx/weaver-python-example>docker push localhost:5000/weaver/deployment:1
The push refers to a repository [localhost:5000/weaver/deployment]
c25b00e8d5ad: Pushed
bdd8c8d2cd96: Pushed
be2f1242a8a3: Pushed
68e8409fbb93: Pushing [==================================================>]   160 MB
795e6ed0d8d4: Pushed
886b13cfbee3: Pushed
27b07808f789: Pushed
c663c306a6c0: Pushed
4fe15f8d0ae6: Pushed
Received unexpected HTTP status: 504 Gateway Time-out
```

**What you expected to happen**:

The push should succeed:

```
298!klamath:~/tbx/weaver-python-example>docker push localhost:5000/weaver/deployment:1
The push refers to a repository [localhost:5000/weaver/deployment]
c25b00e8d5ad: Layer already exists
bdd8c8d2cd96: Layer already exists
be2f1242a8a3: Layer already exists
68e8409fbb93: Pushed
795e6ed0d8d4: Layer already exists
886b13cfbee3: Layer already exists
27b07808f789: Layer already exists
c663c306a6c0: Layer already exists
4fe15f8d0ae6: Layer already exists
1: digest: sha256:4aafa4217509a70b445ae3b7105db07af53384585b79f556b83b89ab81075622 size: 2187
```

**How to reproduce it** (as minimally and precisely as possible):
1. Install docker registry:2 and kube-registry-proxy on a Kubernetes cluster.
2. Push an image to this cluster.

**Anything else do we need to know**:

This probably only happens with either larger images, or slower storage backends (or both).  In our case, a 160MB image with a 200Mbps connection to the storage was sufficient to trigger the problem.

The cause is that the timeouts in [the proxy configuration](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/registry/images/proxy.conf.insecure.in) are far too small:

```
  timeout client 1s
  timeout server 5s
  timeout connect 5s
```

5 seconds isn't long enough for the registry to process the uploaded image.  I've built a local version with different timeouts:

```
  timeout client 60s
  timeout server 300s
  timeout connect 5s
```

... which fixes the problem.  Timeouts need to be changed in both `proxy.conf.in` and `proxy.insecure.conf.in`; it's probably worth making these configurable via the environment, since the config is already dynamically generated.

Fixed image for testing: `docker.io/torchbox/kube-registry-proxy:latest`.

**Comment by bacongobbler** [comment]
this has been fixed in the 0.4 release. No official image exists for it yet.

**Comment by xiangpengzhao** [comment]
As is pointed out by Matthew, you can try gcr.io/google_containers/kube-registry-proxy:0.4

ref: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/registry/images/Makefile

@thockin

**Comment by unixwitch** [comment]
We're not using registry-proxy anymore, so feel free to close this when it's been fixed (I won't be able to test it).
