### ISSUE TITLE
Make image tag and latest pulling time available to client

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#3074]
docker client doesn't have timestamp of when the image pulled, but we could get it from stat the image file?

**Comment by dims** [comment]
@dchen1107 Dawn, Is this still needed?

**Comment by kargakis** [comment]
We have had requests for separating the image pulling time from the time we expect a Deployment to complete a rollout (ProgressDeadlineSeconds) so I think this would be a nice to have at some point.
