### ISSUE TITLE
Ubuntu Snappy

### ISSUE THREAD

**Issue by loe** [kubernetes/kubernetes#3075]
I'd like to see Kubernetes packages in the [Ubuntu Snappy](http://www.ubuntu.com/cloud/tools/snappy) package manager.

It looks like it would be a great fit as a "framework" which could hook into the already existing docker framework. I do not understand enough about how snappy works to know how it would relate to an ectd "app" and how the components would talk to the docker daemon. I'm not sure how flannel fits in.

My desire is to start a Ubuntu Core image on my favorite public cloud, and via cloud-init have it auto-install all the necessary parts to get me to a working Kubernetes cluster. The "transactional" update mechanism would make it straightforward to perform a rolling update of nodes in a controlled fashion.

**Comment by MarkGavalda** [comment]
Has there been any progress with this in the last ~6 months? Thanks!

**Comment by roberthbailey** [comment]
Closing as obsolete. 

@loe We recently added configuration to run Kubernetes on Ubuntu trusty in GCE using cloud-init. It shouldn't be difficult to use the same cloud-init config on other cloud providers.
