### ISSUE TITLE
GarbageCollector broke kubemark-scale

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#30759]
After enabling GarbageCollector in Kubemark, kubemark-scale started failing pretty reliably (all runs failed). Looking into log it seems pretty much related to garbage-collector.

The example failure is here:
http://kubekins.dls.corp.google.com/view/Scalability/job/kubernetes-kubemark-gce-scale/1344/consoleFull

I didn't have time to investigate deeper, but the timing of those failure matches timing of merging:
https://github.com/kubernetes/kubernetes/pull/30401

@lavalamp @gmarek

**Comment by wojtek-t** [comment]
To clarify (this suite was also flaky before, but now it's reliably broken). 

So we should first focus on debugging these errors:
```
 Aug 14 21:26:27.944: Couldn't delete ns "e2e-tests-density-n75jy": namespace e2e-tests-density-n75jy was not deleted within limit: timed out waiting for the condition, pods remaining: []
```

Once they are fixed, I will continue debugging the other failures.

**Comment by wojtek-t** [comment]
Actually I think there are two main issues here:

1. Controller manager crashed (and in kubemark it's not restarted, because it's not running as pod)
```
137331 fatal error: concurrent map writes
137332 
137333 goroutine 166119 [running]:
137334 runtime.throw(0x3d62680, 0x15)
137335   /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc820a92ac0 sp=0xc820a92aa8
137336 runtime.mapassign1(0x2b11dc0, 0xc82040ba70, 0xc820a92c08, 0xc820a92c58)
137337   /usr/local/go/src/runtime/hashmap.go:540 +0x54b fp=0xc820a92b68 sp=0xc820a92ac0
137338 k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).queueActionLocked(0xc820e6d1e0, 0x3aea238, 0x4, 0x3a12fc0, 0xca5f24dc60, 0x0, 0x0)
137339   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/cache/delta_fifo.go:320 +0x5d1 fp=0xc820a92cd0 sp=0xc820a92b68
137340 k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).Resync(0xc820e6d1e0, 0x0, 0x0)
137341   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/cache/delta_fifo.go:511 +0x4f7 fp=0xc820a92e48 sp=0xc820a92cd0
137342 k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch.func1(0xc820fa8a88, 0xc8201ba060, 0xc8207d4480, 0xc88d548f60, 0xc820fa8a90)
137343   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:285 +0x1c2 fp=0xc820a92f88 sp=0xc820a92e48
137344 runtime.goexit()
137345   /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820a92f90 sp=0xc820a92f88
137346 created by k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch
137347   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:292 +0xde3
```

2. GarbageCollector is generating high load, because it's using dynamicClient, which is using JSONs instead of protobufs, which are way slowed.

But 1. seem to be much migger issue now - controller manager is just crashing.

@kubernetes/sig-api-machinery

**Comment by wojtek-t** [comment]
There is one issue that I see in the code, but I personally I don't know why it can cause this particular fatal - basically in this line:
https://github.com/kubernetes/kubernetes/blob/master/pkg/client/cache/delta_fifo.go#L511
we are calling queueActionLocked that assumes write lock to be held, but we only have ReadLock.

@timothysc @rrati @smarterclayton ^^

**Comment by lavalamp** [comment]
Interesting-- is it the same as https://github.com/kubernetes/minikube/issues/368?

**Comment by wojtek-t** [comment]
@lavalamp - it seems to be

**Comment by lavalamp** [comment]
I'm sending a PR.

**Comment by caesarxuchao** [comment]
It's now failing with density test failed with `error while waiting for pods to become inactive`.

That's because the timeout is too small (10 mins), I'll increase it to 20 mins. According to the last green gce-scale test, where GC is disabled, it takes it ~12 mins for all pod becoming inactive.

Also, on gce-500, where there are 15000 pods, it takes ~7min to garbage collect all pods. Without GC, it takes 2 mins. I suspect the difference is because GC only has 5 worker, while the replication controller spawns 500 goroutines to delete pods (capped by BusrtReplicas). I'll increase default GC workers to 100.

**Comment by caesarxuchao** [comment]
https://github.com/kubernetes/kubernetes/pull/30943 is fixing a memory leak of GC.

**Comment by lavalamp** [comment]
@caesarxuchao If the GC was triggering this more often, do you think that maybe that implies that it was doing more resyncs than necessary?

**Comment by caesarxuchao** [comment]
>  If the GC was triggering that crash more often, do you think that maybe that implies that it was doing more resyncs than necessary?

Yes. My recollection was resync() was not really triggered after we split resync and relist. The GC is resync every 60 second (I copied from some other controller). I'll tune it to 10 mins, that should help with CPU. I think GC doesn't need to resync at all.

**Comment by lavalamp** [comment]
That's what I'm thinking, too. Maybe we can just turn it off.

**Comment by caesarxuchao** [comment]
My own 500-gce run shows https://github.com/kubernetes/kubernetes/pull/30943 fixed the kube-controller manager's cpu consumption, and memory consumption is 928M (100%) and 657M (90%), which is still higher than without GC (491M, 90% and 100%), but much saner than without #30943 (1880M)

**Comment by wojtek-t** [comment]
If you both agree that resyncing is not needed in GC (I looked into the code and it seems to me that it's not), then we should set to to NoResync (I can't remember how exactly it's called). We already use it in few different controllers and in scheduler and it works.

**Comment by caesarxuchao** [comment]
Currently the 500-gce sometimes reports kube-controller-manager uses too much CPU. I found the cause of the CPU consumption surge, after removing all the rateLimitRegistration (e.g., this [line](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/garbagecollector/garbagecollector.go#L481)), the controller-manager's cpu usage of 500-gce dropped from ~0.8 to 0.32, which is even lower than without GC (~0.5)

**Comment by wojtek-t** [comment]
Yeah - I think lower cpu usage is also due to other optimization done over last few days.

Anyway - kubemark-scale is generally back to green. So I'm closing this issue.

Thanks a lot for help with that!

**Comment by caesarxuchao** [comment]
Yeah, that podnamespace interface PR must have helped.
