### ISSUE TITLE
Various failed builds of k8s.io/kubernetes/test/integration in PR builder

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#30754]
Failed `k8s.io/kubernetes/test/integration/persistentvolumes build`. No extra information is available in logs.

**Comment by gmarek** [comment]
I have one PR (#30138) that failed twice on this - first time it was `k8s.io/kubernetes/test/integration/storageclasses` build that failed, second time it was `k8s.io/kubernetes/test/integration/kubectl`. This is PR builder flakyness.

**Comment by wojtek-t** [comment]
In the last few days I've seen a number of failure from integration tests with
```
out of memory
```

I think this may be related.

**Comment by ixdy** [comment]
Curious. We haven't changed anything from the test-infra side recently.

cc @kubernetes/test-infra-maintainers

**Comment by nikhiljindal** [comment]
`test/integration/persistentvolumes` failed again in https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/30673/kubernetes-pull-test-unit-integration/40428/build-log.txt, no logs.

**Comment by jsafrane** [comment]
integration/persistentvolumes compiles just fine, there must be something odd in the test infrastructure. And from the logs I have no clue what could it be.

**Comment by fejta** [comment]
No hits of this for two weeks... I suspect this was a ram issue that we resolved. Please reactivate if it is seen again...

**Comment by mml** [comment]
See #31729.  Not integration tests, but the same symptoms.

**Comment by mml** [comment]
#31729 was a legit build failure, but we don't seem to save stderr.  Or may be I just can't find it?

**Comment by fejta** [comment]
Click the artifacts link in gubernator, navigate to the artfiacts folder in gcs, then open the correct .stdout file.

**Comment by mml** [comment]
Yeah, we save stdout, but the compiler errors are sent to stderr.

So I see

```
FAIL	k8s.io/kubernetes/federation/pkg/federation-controller/ingress [build failed]
FAIL	k8s.io/kubernetes/federation/pkg/federation-controller/namespace [build failed]
FAIL	k8s.io/kubernetes/federation/pkg/federation-controller/replicaset [build failed]
```

But the actual compiler errors aren't there.

**Comment by ixdy** [comment]
The compiler errors are in the regular build log.

**Comment by gmarek** [comment]
@fejta - can you please don't close issues that don't have gubernator links?

**Comment by fejta** [comment]
Did you reopen the wrong bug? I closed the issue because all the requested info already exists (although I agree it is painfully hard to collate all the info in the right places)
