### ISSUE TITLE
Mounting AFS volume fails on CoreOS

### ISSUE THREAD

**Issue by jpoon** [kubernetes/kubernetes#30769]
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4+dd6b458", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"not a git tree", BuildDate:"2016-08-04T09:44:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:38:31Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release):
  NAME=CoreOS
  ID=coreos
  VERSION=1068.9.0
  VERSION_ID=1068.9.0
  BUILD_ID=2016-08-05-0455
  PRETTY_NAME="CoreOS 1068.9.0 (MoreOS)"
- **Kernel** (e.g. `uname -a`):
  Linux kube-20160815-215609-vm-master 4.6.3-coreos #2 SMP Fri Aug 5 04:51:16 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz GenuineIntel GNU/Linux

**What happened**:
Failing to mount an Azure File Service (AFS) volume onto a CoreOS 1068.9.0 host. 

**How to reproduce it**:
- Install cifs-util onto CoreOS host via this [workaround](https://github.com/coreos/bugs/issues/571).
- Create the secret as per the [AzureFileVolume documentation](http://kubernetes.io/docs/user-guide/volumes/#azurefilevolume) and the pod/container fails to start.
- SSH-ing into the machine to manually run the mount command also fails
- **Works**:  `sudo mount -t cifs //<storage_account_name>.file.core.windows.net/<fileshare_name> /mnt/azure -o vers=2.1,username=<storage_account_name>,password=<storage_account_key>,dir_mode=0777,file_mode=0777`
- **Doesn't Work**:  `sudo mount -t cifs //<storage_account_name>.file.core.windows.net/<fileshare_name> /mnt/azure -o vers=3.0,username=<storage_account_name>,password=<storage_account_key>,dir_mode=0777,file_mode=0777`

**Anything else do we need to know**:
- Azure File Service supports SMB2.1 and 3.0
- AzureFile Volume plugin uses [SMB3.0 to mount the file share](https://github.com/kubernetes/kubernetes/blob/79ed7064cae57a63a161e1bc2c7332dafd720247/pkg/volume/azure_file/azure_file.go#L192)
- As per https://github.com/coreos/bugs/issues/1387, CoreOS doesn't have kernel support for SMB3.0. At some point, CoreOS used to fail silently and fallback to SMB2.1, this is no longer the case (at least with v1068.9.0).

Workaround we came up with is to manually mount the fileshare in the cloud-init. So our cloud-init looks like this now:

```
    - name: cifsmount.service
      command: start
      enable: false
      content: |
        [Unit]
        Description=Copy CIFS mount
        After=network.target

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        TimeoutStartSec=0
        ExecStartPre = -/usr/bin/mkdir -p /opt/sbin
        ExecStart=/bin/sh -c "rm -fr /opt/sbin && rsync -a /usr/sbin/ /opt/sbin/ && /usr/bin/docker run -v /opt/sbin:/target so0k/mount.cifs_copy /target && mount --bind /opt/sbin/ /usr/sbin/ && mount -t cifs //<storage_account>.file.core.windows.net/<fileshare> /mnt/azure -o vers=2.1,username=<storage_account>,password=<storage_account_key>,dir_mode=0777,file_mode=0777"
```

**Comment by enieuw** [comment]
I ran into the same problem but as a temporary workaround I injected the vers=2.1 into the storage account key variable by creating my secret like this:
`echo -n "<accountKey>,vers=2.1" | base64`

**Comment by jpoon** [comment]
@enieuw That is a much better workaround than what we came up with. Using your method, k8s was able to mount the AFS volume automatically?

**Comment by enieuw** [comment]
Yep

**Comment by monaka** [comment]
Even though I wrote the workaround to https://github.com/coreos/bugs/issues/571, it's not good idea in case we use Kubernetes on CoreOS.

A most of all CoreOS users is using Hyperkube. So there is no need to prepare `/usr/sbin/mount.cifs`.
But there don't have cifs-tools in Hyperkube images (Not only CoreOS versions but also theofficial).
The pain point is here.

IMO, the best solution is to add cifs-tools into Hyperkube images.
I'm testing on the home-made Hyperkube images. It looks very good.
(But @enieuw's account-key hack is still required)

**Comment by monaka** [comment]
Like this. https://github.com/monami-ya/kubernetes/commit/5e1404f71d3b16af2c7ce4ae32ed6893f5f56a2a

**Comment by colemickens** [comment]
@mikedanese Is there another issue that covers adding utility packages to `hyperkube`? I'm getting people wanting to use the AzureFileService driver and can't because of the lack of `cifs-utils` in the `hyperkube` container.

**Comment by monaka** [comment]
At least for CoreOS users, some package improvements (just adding some lines) on Hyperkube will make users happy.

**Comment by mikedanese** [comment]
No but feel free to send a pr

**Comment by jpoon** [comment]
Thanks @colemickens https://github.com/kubernetes/kubernetes/commit/3aaf0a86e3bc80da39d348db0f6d675132f71fbb

**Comment by mikedanese** [comment]
Seems fixed.
