### ISSUE TITLE
Add support for fish shell autocompletion

### ISSUE THREAD

**Issue by luolong** [kubernetes/kubernetes#30763]
**FEATURE REQUEST**:

[Fish shell](https://fishshell.com) is a relatively new modern interactive user friendly command line shell. It really shines at user friendly features like visual tab completion menus, live syntax highlighting and other useful features.

`kubectl` has a massive set of sub-commands and options. Remembering all those is a chore. Specially when getting to know Kubernetes. All the help is appreciated.

Please provide autocompletion support for fish shell in addition to bash and zsh.

Thanks

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4+dd6b458", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"not a git tree", BuildDate:"2016-08-04T09:44:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"darwin/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Environment**:
**Others**: Fish shell

**Comment by pwittrock** [comment]
Sounds cool.  If you are interested in contributing this checkout:

https://github.com/kubernetes/community/wiki/WIP:-Contributor-Guide:-kubectl-new-contributor-onboarding-guide

**Comment by gaocegege** [comment]
cool, @gacegege #dibs on this issue.

**Comment by matthew-piziak** [comment]
@gaocegege Any progress on this issue?

**Comment by gaocegege** [comment]
I think we should slove the problem from upstream to keep code clean but it seems that they don't have time to implement it.

ref https://github.com/spf13/cobra/issues/350

**Comment by zx8** [comment]
Found this via a Google search in the meantime:
- https://gist.github.com/terlar/28e1c2e4ac9a27be7a5950306bf45ab2

**Comment by apelisse** [comment]
Closing in favor of the issue in kubectl repo.

**Comment by yuriipolishchuk** [comment]
here's a ticket in kubectl repo https://github.com/kubernetes/kubectl/issues/131
