### ISSUE TITLE
Test flake: TestDecodeBrokenYAML

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#30776]
Flaked in: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/28936/kubernetes-pull-test-unit-integration/39994/

**Comment by bgrant0607** [comment]
@fejta Is the build log clobbered when tests are restarted? AFAICT, this test didn't fail in the test run captured by the build output.
