### ISSUE TITLE
Formalize waiting for synced caches in controllers

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#30770]
We have started waiting for caches to sync before starting any worker in various controllers mostly downstream but also in a couple of places in Kube (eg. https://github.com/kubernetes/kubernetes/blob/c0e79d8da731e52312451f017cb44240831576d4/pkg/controller/deployment/deployment_controller.go#L200). Instead of it being a simple pattern controller authors should follow we should somehow bake it in the controller framework.

cc: @deads2k

**Comment by deads2k** [comment]
@kubernetes/rh-cluster-infra This comes up whenever you have a controller that watches multiple resources to kick a queue for a different resource.

**Comment by kargakis** [comment]
@deads2k this is fixed in https://github.com/kubernetes/kubernetes/pull/32210, right?

**Comment by deads2k** [comment]
> @deads2k this is fixed in #32210, right?

I've written the API to do it.  I'll see about sweeping the rest.

**Comment by deads2k** [comment]
I think that this got fixed in 1.7
