### ISSUE TITLE
Code mgmt: need a comment designating "remove this after X"

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#30781]
We have a lot of things that we deprecate and leave comments of the form "delete this after X".  We have no consistency to them, so it is hard to "scrub" for them.

I'd like to see us define and adopt a standard way of denoting this in the codebase, and then do a janitorial pass on the existing comments. Something like:

```
// DEPRECATED(thockin): can be removed after v1.4 release branch is cut
```

or even a begin/end pair:

```
// DEPRECATED_BEGIN(thockin): remove after 08/17/2017
code
code
code
// DEPRECATED_END
```

**Comment by xiangpengzhao** [comment]
I remembered that @lavalamp or @ixdy proposed a solution for feature versioned but I cannot find that issue now.

**Comment by xiangpengzhao** [comment]
ref: https://github.com/kubernetes/kubernetes/issues/34508
