### ISSUE TITLE
swagger docs should refer to "jsonFieldNames" not "GoFieldNames"

### ISSUE THREAD

**Issue by danwinship** [kubernetes/kubernetes#30780]
The API docs have things like:

| Name | Description |
| --- | --- |
| nodeName | NodeName is a request to... |
| serviceAccount | DeprecatedServiceAccount is a deprecated alias for ... |

It's vaguely annoying to have to field name referred to with the wrong capitalization in the first example, and even more annoying to have an entirely wrong name used in the second example. Perhaps the doc generator should be fixing these up.

Just replacing the first word of the doc string would be a big improvement in many places (ie, if it's the go field name, replace it with the JSON field name). Maybe there are some places where the field name appears later in the string? Also, some docs might refer to other fields, and maybe it would be nice to fix those too, although it could be tricky to replace arbitrary strings since you might end up accidentally replacing something that wasn't meant as a field name reference...

(qv https://github.com/openshift/origin/pull/10143#discussion-diff-73049449)

**Comment by stevekuznetsov** [comment]
As a minimal-effort implementation doing a simple find/replace `s/\bGoFieldName\b/jsonFieldName/g` should net us pretty substantial readability benefits, at the cost of potentially messing up when the Go field name is conjugated or something in the doc.

**Comment by danwinship** [comment]
just noticed this is a dup of #19319
