### ISSUE TITLE
Create "whoami" service

### ISSUE THREAD

**Issue by mlbiam** [kubernetes/kubernetes#30784]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): Looked at the API docs.  Discussed on the kubernetes/sig-auth slack channel with @ericchiang and @whitlockjc

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Once OIDC is integrated, it would be helpful to have an endpoint that will reply with information about the logged in user, mainly the username, uid, groups and roles.  Something similar to OpenShift's /oapi/v1/users/~ service.  Ideally this would return json similar to:

``` json
{
  "username":"me",
  "uid":"myuid",
  "groups":[
                  "admins",
                  "devs",
                  "etc",
                ],
  "roles":[
               "adminrole",
               "userrole",
               "etc"
            ]
}
```

That way someone can easily test that OIDC is setup correctly, the dashboard can show who the logged in user is and external tool developers can verify/display the logged in user.  

**What you expected to happen**:

```
$ curl -H "Authorization: bearer ASDFV..." https://myapi.k8s.io/api/path/to/whoami
{
  "username":"me",
  "uid":"myuid",
  "groups":[
                  "admins",
                  "devs",
                  "etc",
                ],
  "roles":[
               "adminrole",
               "userrole",
               "etc"
            ]
}
```

**Comment by AdoHe** [comment]
@smarterclayton IIRC, openshift origin has already implements this feature.

**Comment by mlbiam** [comment]
@AdoHe  Sort of.  Origin doesn't have an endpoint that will tell you what groups a user belongs to (at least it didn't a couple of months ago) or the roles.  The groups attribute that comes back from /oapi/v1/users/~ doesn't get populated anymore.

**Comment by kargakis** [comment]
cc: @deads2k

**Comment by ericchiang** [comment]
Note that roles are a concept unique to RBAC. They aren't a part in other authorizers and aren't appropriate for a general discovery API.

**Comment by mlbiam** [comment]
@ericchiang sure.  I was thinking of https://github.com/kubernetes/dashboard/issues/964#issuecomment-240473494 .  For instance in OpenShift if I'm not a member of the project's admin role I can't create new pods (at least OOTB).  Not sure how thats implemented in OpenShift's console but it looks like if there was a comprehensive "this is what you have access to" it would be useful.

**Comment by deads2k** [comment]
> @ericchiang sure. I was thinking of kubernetes/dashboard#964 (comment) . For instance in OpenShift if I'm not a member of the project's admin role I can't create new pods (at least OOTB). Not sure how thats implemented in OpenShift's console but it looks like if there was a comprehensive "this is what you have access to" it would be useful.

I'm not against adding something like openshift's `SelfSubjectRulesReview` to the rbac group, but it would be specific to rbac, not in the generic authorization API.  

I'm am opposed to exposing roles externally if there's any way to avoid it.

For details, see `oc policy can-i --list --loglevel=8`.

**Comment by deads2k** [comment]
> Once OIDC is integrated, it would be helpful to have an endpoint that will reply with information about the logged in user, mainly the username, uid, groups and roles. Something similar to OpenShift's /oapi/v1/users/~ service. Ideally this would return json similar to:

It sounds like you want to hit the `authentication.k8s.io/v1beta1/tokenreviews` endpoint we added this release.  It gives back users and groups for a token and I'd expect it to work for an OIDC token.  It would not work for certificate based users.

I'm not strict against a whoami alternative to the tokenreviews endpoint, but I'd like to see how much mileage we get out of tokenreviews first.

**Comment by deads2k** [comment]
@kubernetes/sig-auth

**Comment by whitlockjc** [comment]
I'm not sure that a `/whoami` is the right place to do this.  The equivalent resource for things like BitBucket, GitHub, OpenID Connect, ... do not give the group/role details for a user and instead, there are separate APIs for retrieving these details.  I do like the idea of a `/whoami` to be able to test that your cert details and/or OIDC configuration is right, but is this the place for more details information like groups/roles/...?

My two cents.

**Comment by erictune** [comment]
Does #30829 satisfy this request?  Just do any operation on the API (whether you have permission or not) with valid credentials and you get back your username in a header.

**Comment by mlbiam** [comment]
Not entirely.  I'd also want to make sure the groups are being loaded
properly and #30829 only tells me the user.  Its a start, but
as @ericchiang pointed out putting all the groups in a response header can
get big quickly if you have a large environment.

**Comment by erictune** [comment]
I regret the decision to all authenticators to provide group information.

**Comment by mlbiam** [comment]
> I regret the decision to all authenticators to provide group information.
>
>
where else would it come from?  k8s has not internal store for az rules so
the az information has to come from somewhere.  I think its a great model.
Its one I've used on countless other applications over the years to great
success.  As an external tool builder, this also makes it much easier to
create security tools for k8s.  I don't have to implement a new connector
to provision access, i can provide that access by storing the groups in
either ldap or a db or pick-your-favorite-place.

**Comment by ericchiang** [comment]
@mlbiam https://github.com/kubernetes/kubernetes/issues/23720

**Comment by deads2k** [comment]
> @mlbiam #23720

While I wasn't against that issue, I do find having a clean break in `user.Info` after authentication quite nice.  It makes reasoning about what's going to happen very easy.



> where else would it come from?  k8s has not internal store for az rules so
> the az information has to come from somewhere.

@mlbiam There is a reasonable claim that loading group membership can be expensive, particularly for large numbers of groups and that an authorizer *could* optimize the look up in some cases based on likelihood of needing particular bits of information or which bits of knowledge are locally available.

I don't think I'd personally want to try to do it (I think it makes it harder to reason about the overall system), but I'm not prepared to say that such a system is unreasonable.

**Comment by mlbiam** [comment]
Thanks @ericchiang for the context.  In light of that, I think its even more important to have something that lists "whoami" to the client if only for debugging.  If you're adding another layer to the process then you need to make sure that k8s is seeing your user the way you intended with that many moving parts.  You could potentially have an OIDC idp for user information and ldap server for authorizations (as an example).  Thats a similar  model to what we use in OpenUnison.  It works great but can get complicated very easily so having something like this would make that debugging process easier.

**Comment by deads2k** [comment]
@mlbiam determining group membership when authorization can actually change which groups are loaded becomes non-trivial.  If that proposal is ever implemented, then there's no guarantee that the groups available in the `user.Info` are ever "complete".

We may not know the answer server-side to return to you.

**Comment by mlbiam** [comment]
@deads2k Thanks for the thoughts.  I think both are a good idea.  If an IdP can limit the groups it sends in the jwt then use that.  Otherwise I could see using an external az plugin.  

As to if its "complete", understood.  though i wouldn't say thats a reason not to have a "whoami".  different use cases would use this in different ways.  I understand it can get very complicated on multiple fronts quickly, so the more tools to help debug the better.

**Comment by jimmycuadra** [comment]
What is the current workaround for this? I'm trying to debug some auth issues for a developer on my team and I'm not sure how to get the user and groups as the server is seeing them.

**Comment by ericchiang** [comment]
@jimmycuadra the RBAC debug logs or audit logs are the current way.

**Comment by deads2k** [comment]
> @jimmycuadra the RBAC debug logs or audit logs are the current way.

@ericchiang long ago you had a pull to add response headers that died on how to represent impersonation as I recall.  You up for trying again with something concrete for impersonation?  Maybe different values before and after or something?

**Comment by ericchiang** [comment]
@deads2k PR to add Authentication-Info response headers here https://github.com/kubernetes/kubernetes/pull/30829

Some problems beyond impersonation that I hit:

* We don't want to return groups in an HTTP header because the list could easily be too big.
* Parsing the headers is fickle (`Authentication-Info: username="jane", uid="8881`). Format defined in https://tools.ietf.org/html/rfc7235#section-2.1 didn't have any matching Go packages last I checked.

The `authentication.k8s.io/v1.TokenReview` API is probably the closest service in kube for determining who the current user is. However, it doesn't cover:

* x509 client cert auth.
* Basic auth (we're trying to deprecate this anyway)
* Impersonation info.

`Authentication-Info` headers are lower overhead and already a standard, happy to revamp that PR. But full "whoami" functionality would probably be better served by a `authentication.k8s.io/v1.SelfReview` kind of API. Don't know if we're adding too many of these "fake APIs" that are filled in by the API server though.

**Comment by SEJeff** [comment]
Just ran into this limitation this morning. From a UX standpoint, something like this seems sensible at a minimum:

```bash
$ kubectl auth whoami
User:  $user
Roles: $role1, $role2, $role3
Cluster Roles: None
```

What is the best approach to implement that functionality in RBAC enabled clusters?

**Comment by munnerz** [comment]
Given the above discussions about roles being a RBAC specified thing and groups being down to the authz provider, I'd be happy just to see a `whoami` command that just returns the current User if that's all that is possible right now.

**Comment by mikedanese** [comment]
There's an escalation consideration with 'whoami' and 'whatcanido' APIs that I haven't seen discussed. Without these APIs and with a leaked credential, an attacker has to guess against the API what resources the credential has access to. With 'whoami', the guessing can be much more targeted.  With 'whatcanido', the attacker can trivially gain access to all resources that the credential has access to.

**Comment by liggitt** [comment]
I'm not sure I'd consider those escalation.

For whoami, the errors returned when authorization denies already contains some information about the calling user. I can maybe see some installations not wanting to let credential holders check who they are, but I think that becomes a default policy question.

For whatcanido, the number of resources and verbs is small enough that enumeration of all of them would only take a couple seconds... I don't see requiring that enumeration as particularly security-enhancing.

**Comment by mikedanese** [comment]
Maybe escalation isn't the right word. Without knowledge of client identity and client ability, client credentials are harder to use. This attribute of client credentials provides an extra layer of defense against leaked or otherwise compromised credentials. This is not critical if the ship has already sailed but nonetheless I wanted to consider it.

> For whoami, the errors returned when authorization denies already contains some information about the calling user

True. We would need to redact user info from authz reason.

> the number of resources and verbs is small enough that enumeration of all of them would only take a couple seconds

This is true only if the attacker has knowledge of namespace names which may not be the case. Enumeration will also leave a trail of 'DENY's which may be easier detect as abuse.

**Comment by BenTheElder** [comment]
test-infra recently ran into this with the Prow setup guide where we expect users are creating a new cluster and need to create RBAC rules https://github.com/kubernetes/test-infra/pull/8499, we're working around this by suggesting platform specific answers in combination with "you can get your username from the error message" ... 

Can we reconsider adding an actual `kubectl whoami`? It seems like a useful API to have and in the meantime as https://github.com/kubernetes/kubernetes/issues/30784#issuecomment-349098070 mentions you can obtain the username from error output with other commands anyhow which imo presents the same information under a bad UX..

**Comment by munnerz** [comment]
Given kubectl now has `kubectl auto can-i`, and given we already return the username of a request in error messages, it seems odd we don't have the generic whoami returning just a username at least already.

Above, it seems the concerns were more focused on the `can-i` behaviour, but now that is supported, it seems like whoami is a natural extension.

Is there any substantive reason/potential attack that we are trying to mitigate by not adding this? If not, it'd be awesome to get an idea of the next steps required (i.e. a proposal for the new API endpoint) so we can get started on this!

If there are valid security concerns, then I think this issue should be addressed sooner rather than later, as developers are already beginning to depend on these error messages in order to detect usernames, and the longer a 'feature' exists, the harder it'll be to remove it 😄

**Comment by BenTheElder** [comment]
@mikedanese @liggitt any thoughts? I'd love to help push this forward again if there are no current objections. 
As @munnerz says it seems like we should do this now that we have `kubectl auth can-i`

**Comment by liggitt** [comment]
> it seems like we should do this now that we have kubectl auth can-i

I don't see the connection between the two... that API does not expose everything a whoami service would...

I'm on the fence about committing to exposing this info via an API. The human readable denial forbidden message encountered as part of a denial is subject to change, and could be masked if deemed too sensitive a response.

**Comment by BenTheElder** [comment]
@liggitt Fair enough... 

This is not my usual domain, admittedly, but could we place this API behind a policy then? I'd guess for most deployments usernames are not very concerning compared to scanning stolen credentials with `can-i` or even just trying to deploy something nasty without checking for access...

> For cluster-admin debugging purposes, the audit log is preferable to a user-facing API.

I think a *lot* of Kubernetes users are "cluster admins" permission-wise but are not quite experienced enough to configure audit logging and go look through the audit logs, and obtaining the logs seems like it is always going to be less portable than `kubectl auth whoami`.

**Comment by SEJeff** [comment]
> I'm on the fence about committing to exposing this info via an API. The human readable denial forbidden message encountered as part of a denial is subject to change, and could be masked if deemed too sensitive a response. For cluster-admin debugging purposes, the audit log is preferable to a user-facing API.

@liggitt Could said api not be wrapped with rbac and sensible default policy shipping upstream? This is a problem most anyone who creates roles, bindings, or service accounts is going to deal with, and not all who create roles or bindings (or service accounts for their namespaces) have or want cluster admin privileges. It generally isn't considered a security hole in 'nix for local users to use whoami or various incantations of `getent passwd` / `getent group`. In fact, it is required for any 'nix system to function normally. Having an api for something virtually everyone is going to want is certainly preferable over scraping error messages.

How is kubernetes different from a security perspective compared to Unix when the user just wants to know their already authenticated username / groups? Unauthenticated users would just get something akin to `system:unauthenticated` or nothing at all depending on cluster rbac policy. Your apprehension for something that could be security sensitive is good, but I'm not sure it is warranted for this specific issue.

What do you think?

**Comment by liggitt** [comment]
> Could said api not be wrapped with rbac and sensible default policy shipping upstream?

Unless the default policy exposed it to all users, it’s unlikely to be broadly useful, right? 

> This is a problem most anyone who creates roles, bindings, or service accounts is going to deal with

Can you clarify what you mean by that? The circumstances in which someone 1) needs to grant themselves permissions, 2) has the ability to grant themselves permissions, and 3) doesn’t know their own username seem very narrow. I also am not seeing how this would help a service account creator.

**Comment by yue9944882** [comment]
😃Didn't realize this feature requests have already been raised years ago. 

> For those users I could provide tooling to automate their setup including RBAC rules etc., but right now they'll have to find their username first on their own.

This is the very pain-point when I'm trying to set up RBAC rules for myself. Currently information about user's identity is not very sensitive if we could only get the one about ourselves. Also, client identity is mostly stored in unsecured places, like x509 public key. Worrying about the security here might be unnecessary IMHO.

**Comment by redbaron** [comment]
Does it need to be a server endpoint ? I'd be fine if `kubectl auth whoami` just extracted user information from credentials it is configured to use to send requests and then present it to stdout lets say in the same form as `RoleBinding.subjects` array elements.

**Comment by yue9944882** [comment]
> Does it need to be a server endpoint ? 

@redbaron i'm afraid so. because we don't know how the apiserver extracts user info from authn context. even though now all the information could be found from "CN" and "O" of x509 client cert field currently, it doesn't mean we will always follow this track. am i right?

xref #66033

**Comment by yuriipolishchuk-finsight** [comment]
@alwinmarkcf https://kubernetes.io/docs/tasks/debug-application-cluster/audit/

**Comment by redbaron** [comment]
/remove-lifecycle stale

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by dsboulder** [comment]
As a newer k8s user, I just ran into this issue. I couldn't figure out where my group mappings were breaking down from LDAP => OIDC provider => K8s RBAC "group" subjects => ClusterRoleBindings. I eventually figured out I was using the wrong part of a JWT token for groups, but I did look around for a way to check my groups first and couldn't find an endpoint or CLI command (though I did appreciate the `can-i` action tremendously)

**Comment by korjavin** [comment]
It's very useful when using CI/CD to understand what account is used

**Comment by jpbochi** [comment]
is there any workaround for this? Maybe trying to make some always unauthorized action, and parsing the username from the error message?

**Comment by BenTheElder** [comment]
Yes there is a kubectl whoami plugin relying on this
https://github.com/kubernetes-sigs/krew-index/blob/master/plugins.md

https://github.com/rajatjindal/kubectl-whoami/blob/1bdd367d5fb2717a5620d130f49565f8047d9531/pkg/k8s/tokenreview.go#L22

**Comment by liggitt** [comment]
> Maybe trying to make some always unauthorized action, and parsing the username from the error message?

Fair warning that human readable message text is not guaranteed to be stable as an API

**Comment by jpbochi** [comment]
for CI, I might end up installing the binary from https://github.com/rajatjindal/kubectl-whoami/releases directly instead of using krew. I already verified that this works.

**Comment by tomwans** [comment]
Poking around in the API Reference, does https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#userinfo-v1-authentication-k8s-io not handle this?

**Comment by enj** [comment]
> Poking around in the API Reference, does https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#userinfo-v1-authentication-k8s-io not handle this?

That is output from the token review API which not all users are authorized to access and it does not cover non-token forms of authn.

```
Appears In:
TokenReviewStatus [authentication/v1]
```

**Comment by jpbochi** [comment]
bump

**Comment by tamalsaha** [comment]
I have written a Kubernetes extended apiserver that implements the "whoami" service. You can find it here: https://github.com/kubeshield/identity-server

**Comment by Bessonov** [comment]
@liggitt @raelga can you reopen this issue?

I'm trying to analyse why a user can't access kube resources. Everything fine in `kubectl auth can-i`. whoami krew plugin doesn't work on windows. Token contains expected data.
