### ISSUE TITLE
nil pointer dereference in pkg/client/transport/round_trippers.go:92 on oauth failure

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#30790]
On Wed, Aug 17, 2016 at 6:27 AM, Nacho Coloma <icoloma@google.com> wrote:

Right now I am working with the tutorial from Kelsey, which deploys fine, but after creating the Federation Control Plane (controller-manager and apiserver deployed) I cannot create the clusters in the Federation Server. The Controller Manager shows an error in the logs.

kubectl --namespace=federation create secret generic icoloma-eu --from-file=kubeconfigs/icoloma-eu/kubeconfig
kubectl --context=federation-cluster create -f clusters/icoloma-eu.yaml

The cluster is created but never shows ready. The controller logs shows a NPE:

Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:58
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:51
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:41
/usr/local/go/src/runtime/asm_amd64.s:472
/usr/local/go/src/runtime/panic.go:443
/usr/local/go/src/runtime/panic.go:62
/usr/local/go/src/runtime/sigpanic_unix.go:24
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/unversioned/clientcmd/config.go:342
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/client/auth/gcp/gcp.go:101
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/oauth2/transport.go:40
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/transport/round_trippers.go:92

I was reviewing config.go, but could not find what the error message is about. I have tried with different versions of the Federation API server (from v1.3.4 to v1.3.6-beta.0), and tried recreating the cluster several times now, in case I did something wrong.

I have been battling with this for two days. Any help would be super welcome.

**Comment by quinton-hoole** [comment]
@madhusudancs Could you take a look as soon as your v1.4 launch blockers are out of the way?

**Comment by IanLewis** [comment]
FWIW, I get this error when adding a GKE cluster as well, whether the host cluster is AWS or GKE.

**Comment by dims** [comment]
@madhusudancs we can close this issue now right?

**Comment by madhusudancs** [comment]
@dims Please don't close this yet. We still need to cherry pick the fix into 1.3 [PR #31483] and I am using this as a tracking issue.

**Comment by quinton-hoole** [comment]
@madhusudancs I've changed the milestone accordingly.

**Comment by madhusudancs** [comment]
This is now fixed in v1.3, v1.4 and HEAD, so I am closing this issue. Please reopen if you run into this problem again.
