### ISSUE TITLE
Compilation error on OSX: GetDeviceNameFromMount repeat in pkg/util/mount/mount_unsupported.go

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes#30795]
Compilation error in pkg/util/mount/mount_unsupported.go. GetDeviceNameFromMount declared twice. #30724 and #30666 are duplicates and one of them need to be reverted. (build is disabled for linux, that's why both of them got in)

**Comment by MHBauer** [comment]
see #30802, please

**Comment by saad-ali** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/30724

**Comment by dims** [comment]
Looks like this can be closed now. right @saad-ali ?

**Comment by saad-ali** [comment]
Yes, closed by https://github.com/kubernetes/kubernetes/pull/30996
