### ISSUE TITLE
Add Encryption to dynamic provisioner

### ISSUE THREAD

**Issue by markturansky** [kubernetes/kubernetes#30792]
## Summary

Encrypted volumes is a commonly requested feature for Kubernetes storage and requirements exist downstream to use encrypted volumes.

The following is a summary of the three cloud providers that allow dynamic provisioning and the current state of volume encryption for each.

**_TL;DR:_**  Add encryption support for EBS PersistentVolumes. AWS has optional encryption and allows key via the API. GCE encrypts volumes by default but does not allow user-defined keys in the API. GCE allows custom keys via manual volume creation in the UI.  Cinder volumes can be manually created w/ encryption.

@kubernetes/sig-storage @abhgupta

@thockin @saad-ali I'm going to follow up with a PR today/tomorrow to meet the 1.4 cutoff on Friday.

### AWS

*   AWS does _not_ encrypt volumes by default
*   AWS API allows an optional boolean flag for encryption
*   AWS API allows a user to specify which key to use for encryption with a default key provided by AWS if not specified.

See:

*   [http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AmazonEBS.html](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AmazonEBS.html)
*   [http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html)
*   [http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVolume.html](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVolume.html)

### GCE

*   GCE encrypts all volumes by default
*   Users can provide their own keys, but this is a manual step in the UI only.
*   GCE API does _not_ provide a way to specify which key should encrypt which disk
*   Volume attachment to the node requires the same key it is encrypted with. This is a manual step in the UI only.

See:

*   [https://cloud.google.com/compute/docs/disks/customer-supplied-encryption](https://cloud.google.com/compute/docs/disks/customer-supplied-encryption)
*   [https://cloud.google.com/compute/docs/reference/latest/disks/insert](https://cloud.google.com/compute/docs/reference/latest/disks/insert)

### Cinder

*   No encryption by default
*   No opt-in encryption via API
*   Block storage can be optionally encrypted
*   Manual creation of the volumes is required

See:

*   [https://wiki.openstack.org/wiki/VolumeEncryption](https://wiki.openstack.org/wiki/VolumeEncryption)
*   [http://docs.openstack.org/mitaka/config-reference/block-storage/volume-encryption.html](http://docs.openstack.org/mitaka/config-reference/block-storage/volume-encryption.html)
*   [http://docs.openstack.org/juno/config-reference/content/section_create-encrypted-volume-type.html](http://docs.openstack.org/juno/config-reference/content/section_create-encrypted-volume-type.html)

## Proposed

Workflow:

1.  Admins create however many keys in AWS as they wish. This is a manual step.
2.  Admins create StorageClasses with the fully-qualified AWS resource name for the key.

Implementation details:

*   Add encryption support to AWS cloud provider
*   Add encryption support to Kubernetes EBS volume plugin
*   Use StorageClass for both the Encrypted boolean and EncryptionKeyName in PV controller

**Comment by markturansky** [comment]
Added to #29006 via https://github.com/jsafrane/kubernetes/pull/7

**Comment by thockin** [comment]
If we add any more non-essential changes to #29006, I will personally NAK that PR until 1.5.

That PR is too hard to review as it is.  If you want to get this in, send a followup PR with this change as the last commit, and if we get to it, great.  Sending a PR on Wednesday 2 days before code freeze does not mean you actually caught the train.  It means you are queued up outside the station waiting for a ticket with the rest of the throng.

Sorry to come off coarse, but I have done nothing but code review for weeks, and that PR in particular is a BEAR.

**Comment by thockin** [comment]
I looked at your PR.  It's probably fine, but PLEASE PLEASE do it as a
followup

**Comment by jsafrane** [comment]
I have some comments and yes, please wait until the large PR is merged. It's complicated enough already.

**Comment by markturansky** [comment]
I'm happy to do a follow-up PR. Thanks for allowing this small addition. I'm glad to have caught the train.

**Comment by bambrozio** [comment]
Do we have any similar solution for NFS persistent volumes?
Not sure how to mount and unmount NFS PVs which are encrypted. Perhaps the API should cover it too, as the mount command would deal with it. Does it make sense?

**Comment by rmt** [comment]
@bambrozio, https://aws.amazon.com/blogs/aws/new-encryption-of-data-in-transit-for-amazon-efs/ was just released, allowing TLS when mounting an (existing) EFS volume on AWS.  I guess that both at-rest encryption and in-transit encryption would have to be added as an option to any EFS provisioner (currently there's one in kubernetes-incubator/external-storage).

It may be possible to use in-transit encryption standalone with pre-provisioned EFS volumes, though, by specifying the fsType as efs when using local storage.

**Comment by nick4fake** [comment]
It looks like now encryption is not supported for static volumes (those with "awsElasticBlockStore")
