### ISSUE TITLE
Discuss whether certain fields currently set by flags should not be moved to KubeletConfiguration

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#30820]
In #30094 discussion, @mikedanese commeted, related to not wanting to move the `KubeConfig` field into `KubeletConfiguration`:

> We should divide config into three buckets:
> 
> How do I find a trust the apiserver
> How does the apiserver trust me
> Everything else
> 
> These configs have orthogonal concerns, different writer and should be sourced from three different files. They should have no dependencies. 

And, my impression is that, presently, the first category is `--api-servers` and the second is `--kubeconfig`.

If `KubeletConfiguration` is intended, in addition to being used for remote config, to be a complete replacement to flags via on-disk config, then the locations of files for the first two buckets would need to be in the third bucket.

The concern with doing this is that `kubeconfig` and `KubeletConfiguration` are orthogonal, and each deserve their own top-level flag; that the Kubelet should not have to depend on `KubeletConfiguration` to know where to find `kubeconfig`. 

@mikedanese recommended the following:

> My ideal cli api is two flags on each component (--kubeconfig, --componentconfig)
> with good default paths so they never have to be used

Let's hash this out. IMO it might be easier to focus on getting down to these two flags on the Kubelet, rather than eliminating flags entirely.

/cc @mikedanese @vishh @smarterclayton

**Comment by mikedanese** [comment]
> And, my impression is that, presently, the first category is --api-servers and the second is --kubeconfig.

Actually both these are currently contained in kubeconfig. I'm hoping to separate them out though. We can get ride of --api-servers. https://github.com/kubernetes/kubernetes/issues/30395

**Comment by mikedanese** [comment]
https://github.com/kubernetes/kubernetes/issues/23172

**Comment by mikedanese** [comment]
What What is the motivation for including this in componentconfig?
