### ISSUE TITLE
Large Environmental Variables crash pods

### ISSUE THREAD

**Issue by abgordon** [kubernetes/kubernetes#30827]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

Config maps, environmental variable size length, environmental variables, ETCD key value limits

---

BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.1", GitCommit:"50809107cd47a1f62da362bccefdd9e6f7076145", GitTreeState:"clean"}

**Environment**: 
- **Cloud provider or hardware configuration**: 
  Processer: 2.5 GHz Intel Core i7
  Memory: 16 GB 1600 MHz DDR3
- **OS** (e.g. from /etc/os-release):
  OS X El Capitan Version 10.11.5 (15F34)
- **Kernel** (e.g. `uname -a`):
  Darwin COTNPL-GF7G8WP 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64s
- **Install tools**:
- **Others**:

**What happened**:
Injected a large (130+ KB) environmental variable into a replication controller that was propagated into pods. Pod crashed with error and exit code 1, backoff initiated with periodic (20s) attempts to restart pods, which could not be restarted. This was clearly due to large environmental variables as several sizes were attempted, with vars of size ~130KB+ broke pods, with smaller sizes executing as expected 

**What you expected to happen**:
Pod running as usual with the environmental value in place, with sizes of up to 1 MB (etcd value limit). 

**How to reproduce it** (as minimally and precisely as possible):
Inject large environmental variables into Kubernetes pods or replication controllers. 

**Anything else do we need to know**:

**Comment by AdoHe** [comment]
@abgordon seems related to this #23265, ptal.
