### ISSUE TITLE
Deployment controller should fail and retry gracefully

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#30833]
In rare cases, deployment controller may enter hot fail loop (update --> fail --> retry). We should fail more gracefully so that it doesn't, say, overly spam api server and cause it to become unavailable. 

cc @kubernetes/deployment @pwittrock

**Comment by AdoHe** [comment]
@janetkuo is this the same thing as #30028?

**Comment by janetkuo** [comment]
Similar, but this one is more general (not specific to overlapping deployment), and more about doing things like exponential backoff to prevent hot-fail-loop.

**Comment by pwittrock** [comment]
@erictune FYI

**Comment by janetkuo** [comment]
Found #28684 which added rate limiter to the queue

**Comment by janetkuo** [comment]
This bug is discovered in an earlier release, and should be fixed on HEAD now. Closing. :tada:

**Comment by erictune** [comment]
Does this help at all with #30629

**Comment by janetkuo** [comment]
#30629 helps this -- we now use rate limiting queue (implements `workqueue.RateLimitingInterface`) in deployment controller
