### ISSUE TITLE
Field names in validation errors need to be translated from internal name to external name

### ISSUE THREAD

**Issue by abonas** [kubernetes/kubernetes#3084]
PUT request to update a service on url:
with body:
 {
      "id": "redis-master10012",
      "uid": "e1e178a9-89d4-11e4-98a5-3c970e4a436a",
      "creationTimestamp": "2014-12-22T14:20:14+02:00",
      "selfLink": "/api/v1beta1/services/redis-master10012?namespace=default",
      "resourceVersion": 8,
      "namespace": "default",
      "port": 6380,
      "protocol": "TCP",
      "selector": null,
      "containerPort": 0,
      "portalIP": "10.0.0.45"
}

fails with error 422 and this  description -the error complains about 'name' and 'spec.port': the fields presented in the error are  not the names exposed in json hence how the user is supposed to know what went wrong ?

{
  "kind": "Status",
  "creationTimestamp": null,
  "apiVersion": "v1beta1",
  "status": "Failure",
  "message": "service \"\" is invalid: [name: required value '', spec.port: invalid value '0']",
  "reason": "Invalid",
  "details": {
    "kind": "service",
    "causes": [
      {
        "reason": "FieldValueRequired",
        "message": "name: required value ''",
        "field": "name"
      },
      {
        "reason": "FieldValueInvalid",
        "message": "spec.port: invalid value '0'",
        "field": "spec.port"
      }
    ]
  },
  "code": 422
}

**Comment by nikhiljindal** [comment]
From https://github.com/GoogleCloudPlatform/kubernetes/pull/4575#issuecomment-75172955, It was suggested that we can do versioned validation which will fix this.

**Comment by bgrant0607** [comment]
BTW, the reason this is no longer a 1.0 issue is that we're going to ship 1.0 with just one API version: v1. The internal rep. should be close enough to v1 for the messages to not be too confusing in the short term.

**Comment by lavalamp** [comment]
This is going to become a real issue soon, as we're now going to have multiple versions for at least two resources. Even worse, we're moving them between groups. But I don't think we have the resources to fix it for 1.2.

**Comment by kargakis** [comment]
Is this still an issue @caesarxuchao ?
