### ISSUE TITLE
PVC fails when selectors are passed 

### ISSUE THREAD

**Issue by anioool** [kubernetes/kubernetes#30854]
Hi,

I have problem with pvc creation in case when I want to determine either matchlabels or matchExpressions.

The error message is always the same for both selectors:
error validating "persistentVolumeClaim.yaml": error validating data: unexpected type: unversioned.LabelSelector; if you choose to ignore these errors, turn validation off with --validate=false

Below you can find version which currently I am using:
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4+coreos.0", GitCommit:"be9bf3e842a90537e48361aded2872e389e902e7", GitTreeState:"clean"}

Thanks,
Adam

**Comment by wongma7** [comment]
This looks just like https://github.com/kubernetes/kubernetes/issues/26866. What is the client version,  `kubectl version --client`?

**Comment by anioool** [comment]
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.3", GitCommit:"882d296a99218da8f6b2a340eb0e81c69e66ecc7", GitTreeState:"clean"}

**Comment by wongma7** [comment]
@anioool you'll need to upgrade the client to 1.3.x to avoid this message, pvc label selectors are new to 1.3

**Comment by watkinsv-hp** [comment]
I had the same issue and going from client version 1.2.5 to 1.3.4 did the trick.
