### ISSUE TITLE
k8s support docker run --ulimit param

### ISSUE THREAD

**Issue by 249043822** [kubernetes/kubernetes#30850]
docker run supports the param  --ulimit to set contaniner kernel param,  but k8s creating pod could not
 set this param, could have someway to do this?

**Comment by 249043822** [comment]
@thockin ,  could you help me ? thanks

**Comment by 249043822** [comment]
#3595 has opend, close this issue

**Comment by dchen1107** [comment]
@249043822 Thanks for reporting this. Close this in favor of #3595
