### ISSUE TITLE
federated-image.tag not found

### ISSUE THREAD

**Issue by icoloma** [kubernetes/kubernetes#30869]
Following [the documentation](http://kubernetes.io/docs/admin/federation/). With a vanilla kubernetes install, `federation-up.sh` throws an error.:

```
FATAL: tagfile /home/icoloma/code/kubernetes/cluster/../cluster/gke/../../cluster/../cluster/../federation/manifests/federated-image.tag does not exist. Make sure that you have run build/push-federation-images.sh
```

`push-federation-images.sh` works fine, but the error is still there.

**Kubernetes version**: 1.3.3
**Environment**: 
- **Cloud provider or hardware configuration**: GKE
- **OS**: 14.04.5 in my local laptop
- **Kernel**: Linux icoloma 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by wattsteve** [comment]
I see the same thing. I'm running hack/local-up.sh and I'm following the instructions to use the official release images as I don't have a GCE account and so I don't want to build and push the images from head. I see the following error when running federation-up.sh

[root@ip-172-31-59-82 kubernetes]#  KUBERNETES_PROVIDER=aws FEDERATION_DNS_PROVIDER=aws-route53 FEDERATION_NAME=myfederation DNS_ZONE_NAME=myfederation.example FEDERATION_PUSH_REPO_BASE=gcr.io/google_containers FEDERATION=true ./federation/cluster/federation-up.sh
FATAL: tagfile /root/kubernetes/cluster/../cluster/aws/../../cluster/../cluster/../federation/manifests/federated-image.tag does not exist. Make sure that you have run build/push-federation-images.sh

**Comment by wattsteve** [comment]
cc @kubernetes/sig-cluster-federation

**Comment by quinton-hoole** [comment]
@colhom might be able to help

**Comment by colhom** [comment]
The `federation-image.tag not found` error is usually symptomatic of `FEDERATION=true` not being set for the `build/release.sh` process, however that is actuated. @wattsteve I'm pretty sure `local-up` doesn't even use the `release.sh` script, so you'll definitely have to do this on your own.

https://github.com/kubernetes/kubernetes/blob/master/build/release.sh#L40-L46

If you want to "hack it", you can just run the contents of that `if` block in your shell (set `KUBE_ROOT=$(pwd)` first).

_obligatory hand-wavy justification for the weirdness:_ the kuberentes e2e tests are two stage (build, then e2e on a different host), so we have build stage drop the `federated-image.tag` file in the source tree so it get's carried over to the e2e tests in the build artifact tarball.

**Comment by colhom** [comment]
\cc @icoloma

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#66.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
