### ISSUE TITLE
20% of controller-manager CPU is spent on validating labels

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#30875]
Looking into profiles from different performance tests, we can see that ~20% of the whole CPU usage is spent in validating labels when building selector:
https://github.com/kubernetes/kubernetes/blob/master/pkg/labels/selector.go#L791
calls:
https://github.com/kubernetes/kubernetes/blob/master/pkg/labels/selector.go#L117
https://github.com/kubernetes/kubernetes/blob/master/pkg/labels/selector.go#L147

Although I agree that validation is good, I think that validating objects that we read from etcd and store in the cache (and validating them every time we are accessing their selectors) is just useless.

We should probably relax the validation in this place.
Why is it not enough to validate labels/selector only when a given object is created/updated ?

@lavalamp @kubernetes/sig-scalability @smarterclayton

**Comment by wojtek-t** [comment]
I would suggest one of two options:
- call NewRequirement only when parsing requirement in "parseRequirement" and not call it from SelectorFromSet
- add a new methods:
  -  "SelectorFromValidatedSet"
  - "labels.Set::ValidatedAsSelector"
and use ValidatedAsSelector where possible

The former one is a trivial change, the latter would require finding all places where validation is not unnecessary because labels are already validated (or actually not all, but those that are called frequently) and replace them, but it is more explicit.

Any thoughts?

**Comment by justinsb** [comment]
I presume it is one of the regexes?  Is one of them somehow pathological?  If so, maybe we could rewrite them as code, as they seem very straightforward.

I agree that validation on read is overkill, but if we can make it trivially fast that benefits us across the board.

But I am an optimist :-)

**Comment by timothysc** [comment]
> call NewRequirement only when parsing requirement in "parseRequirement" and not call it from SelectorFromSet

+1

**Comment by timothysc** [comment]
Closing from #30976
