### ISSUE TITLE
Investigate higher resource consumption in apiserver in 100-node clusters

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#30871]
We already knew that enabling GarbageCollector increases memory usage of the controller-manager.

However, it appears that it also significantly increases memory usage on apiserver.
In particular, our scalability tests on 100-node real clusters show that after enabling GarbageCollector in them memory usage of apiserver increased (99th percentile):
from ~0.9GB
to ~1.7GB

This is huge!

I didn't have time to dig much deeper into it, but  really suspect that it's all because GarbageCollector is using "dynamicClient" underneath, and dynamic client is using JSONs for communication with apiserver. And we already knew that JSONs are waaaaaay more expensive than protobufs.

I'm not saying this is a hard blocker for launch, but such a huge increase in resource usage needs to be a very conscious decision.

@caesarxuchao @lavalamp 
@kubernetes/sig-api-machinery @kubernetes/sig-scalability @smarterclayton

**Comment by lavalamp** [comment]
We can shrink the deserialization cache size, maybe.

**Comment by wojtek-t** [comment]
We probably can (I would love to get rid of it completely), but it's pretty small fraction of memory...

**Comment by lavalamp** [comment]
Why do you think it's a small fraction of memory? I think it's probably the
only thing that keeps the (go) garbage collector from reclaiming all of the
ugorji-decoded objects?

**Comment by wojtek-t** [comment]
I think that I looked into it few weeks ago but I may have misinterpreted it. I will try to check it tomorrow or early next week.

**Comment by caesarxuchao** [comment]
It's not so dramatic on 500-gce:
for the load test, build [4893](http://kubekins.dls.corp.google.com:8080/job/kubernetes-kubemark-500-gce/4893/consoleFull), without gc, api-server takes 2661.1MB

And with gc, build [5058](http://kubekins.dls.corp.google.com:8080/job/kubernetes-kubemark-500-gce/5058/consoleFull), it's 2670MB.

I didn't check what 100-node is running though, maybe it's related to workloads.

**Comment by caesarxuchao** [comment]
The 100-node runs ***without*** the garbage collector enabled. Maybe the surging memory consumption is related to #30990.

Anyway, I don't think GC increase API server's memory usage. Can we retitile the issue?

**Comment by wojtek-t** [comment]
OK - retitling it to investigate the increase.

**Comment by timothysc** [comment]
We are also seeing this... and will be collecting profiles later today. 

/cc @smarterclayton

**Comment by caesarxuchao** [comment]
FWIW, now apiserver in desity test uses ~1GB memory (some build log don't show this metric), in load test uses ~1.8GB memory
http://kubekins.dls.corp.google.com:8080/job/kubernetes-e2e-gce-scalability/10237/consoleFull

Jenkins only keeps logs for 7 days. Is there any way to access older logs?

**Comment by wojtek-t** [comment]
@caesarxuchao - yes, you can take then from GCS, I think they should be there for a month (but you need to know the build number you are interested in)
For scalability suite, the logs are here:
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-scalability/?project=kubernetes-jenkins

**Comment by caesarxuchao** [comment]
In build 8102 (Jun.2), apiserver used 670MB in density test and 1.2GB in load test

In build 10000 (Aug. 9), apiserver used 1.4GB in density test and 1.8GB in load test. This is the high consumption we observe today.

The build logs between 8102 and 10000 are missing...

**Comment by lavalamp** [comment]
Is there anything left to do here?

**Comment by wojtek-t** [comment]
Actually, I would like to understand it.

@caesarxuchao - I looked into pantheon and all the logs from the runs between 8102-10000 are there. So we can debug it.

So I tried I did some binary search on the data, and it seems that:
- all runs up to 8168 seem to be ok (<=750MB in density)
- since 8169 is is already 1.5GB in density (8170 is ok, but 8171 and 8172 are again bad), 8175 is also bad

So we had some regression on Jun 4th.

I'm reassigning it back to us (it is definitely unrelated to GC). Since it was pre-1.3, we may also consider moving it out-of-1.4.

@gmarek

**Comment by wojtek-t** [comment]
Interestingly, there wasn't any suspicious PR merged around that time.

**Comment by wojtek-t** [comment]
Hmm - but runs
- 8173 and 8174 are again good. (~750MB in density).
- 8175 and 8176 are again bad
- 8177 and 8178 are again good
- 8179 and 8180 are again bad
- 8181 is again good
- 8182 is again bad
- 8183 is again good
- 8185 is again bad

This is super strange what was happening there...

**Comment by wojtek-t** [comment]
Actually, I know where the trick is. It depends whether we are running Density test first (the the memory usage is lower) or if we are running load test first (the the memory usage of density test is higher).

So I would say this is kind of "working as intended" and I'm closing this one.

**Comment by caesarxuchao** [comment]
@wojtek-t so it's because the api-server doesn't release all the memory used in load test?

**Comment by wojtek-t** [comment]
@caesarxuchao - it seems so. I think that the problem is probably with some caches. We should debug it at some point, but I would also like to get rid of "deserialization cache" soon, so we shouldn't spend more time on it no, in my opinion.
