### ISSUE TITLE
integration test flake: kubectl and metrics integration test build failed

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#30885]
More details here:

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/30874/kubernetes-pull-test-unit-integration/40295

**Comment by AdoHe** [comment]
@pwittrock

**Comment by pwittrock** [comment]
@mwielgus Would you change the link to be a publicly accessible link?

**Comment by janetkuo** [comment]
This is integration test build failure, which happened in both test/integration/kubectl and test/integration/metrics. I don't think it's specific to kubectl.

**Comment by janetkuo** [comment]
Dup with #30462, closing
