### ISSUE TITLE
kubectl config use-context exits with code 0 on error

### ISSUE THREAD

**Issue by pracucci** [kubernetes/kubernetes#30883]
**Kubernetes version**: 1.3.3

**Environment**:
- **OS**: OSX 10.9.5

**What happened**:
When I run `kubectl config use-context <not-existing-context>` the exit code is 0.

**What you expected to happen**:
I do expect an exit code different than 0 (ie. 1).

**Comment by AdoHe** [comment]
@pracucci thanks for reporting this. It should be a bug and I can see the root cause.

**Comment by AdoHe** [comment]
@kubernetes/kubectl

**Comment by deads2k** [comment]
I thought there was already a pull for this: https://github.com/kubernetes/kubernetes/pull/24438
