### ISSUE TITLE
node not exist failure during node status update flush controller's log

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#30898]
@saad-ali @matchstick 
From issue #29903, I noticed that under attachdetach controller, reconciler keeps updating node status every 100ms. In some cases, the node no longer exists but reconciler still has a stale cache information of it. The error message quickly flush the kube-controller-manager's log. 
1. Quick fix: Lower the level of this log so by default it won't show up
2. Right fix: have a good comprehensive understanding of all scenarios especially when certain components in the system fail/exit, how the volume manager should react/recover from them. 

Related code and PR: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/reconciler/reconciler.go#L104
https://github.com/kubernetes/kubernetes/issues/29358
https://github.com/kubernetes/kubernetes/pull/30737

**Comment by saad-ali** [comment]
Lowering the priority of the `Could not update node status` warning is not the right answer, that just masks a real issue. The issue was fixed by https://github.com/kubernetes/kubernetes/pull/30737 and I believe that is the right fix. If you agree we can close this issue.

**Comment by saad-ali** [comment]
Lowering the priority is non-ideal but should be fine for now

**Comment by dims** [comment]
switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree)

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by saad-ali** [comment]
Fixed by PRs for k8s 1.7:
* https://github.com/kubernetes/kubernetes/pull/30903
* https://github.com/kubernetes/kubernetes/pull/45923
