### ISSUE TITLE
Kubectl check for overlapping selectors when creating deployments

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#30899]
Creating deployments with overlapping selectors causes bad things to happen.  Before creating a deployment, the client should check if there are any existing deployments with overlapping selectors

**Comment by justinsb** [comment]
This could also be done in an admission controller.  We probably shouldn't be _relying_ on the clients to implement this behaviour.

**Comment by alph486** [comment]
We had the following scenario, when testing a Deployment that was supposed to replace an RC:
- RC is deployed, 2 pods in service. Selector equal to `app=myapp`.
- Create Deployment with same label as above.
- Scale Deployment to 1.

This produced a runaway Create/Terminate loop which DoS'd the docker daemon on one or more workers. In this case the daemon was unrecoverable and we needed to recycle nodes.

FWIW - This was done via kubectl. However, we are in process of building deploy tools and _definitely_ could have happened even if this was fixed on the client side.

**Comment by pwittrock** [comment]
@justinsb I agree, I would rather have it in the server side so all clients benefit.  Unfortunately, the server-side stuff isn't as good for contributor on-boarding, and right now kubectl is the client most people use.

**Comment by pwittrock** [comment]
@AdoHe Would you help @k82cn on this as well?

**Comment by AdoHe** [comment]
sure~

**Comment by k82cn** [comment]
@pwittrock / @AdoHe , I'm not working on this issue because of [kube-mesos](https://github.com/kubernetes-incubator/kube-mesos-framework).

**Comment by AdoHe** [comment]
@k82cn thanks all the same.

**Comment by AdoHe** [comment]
@pwittrock please assign this to me, I will fix this after my personal training.

**Comment by soltysh** [comment]
Ref: https://github.com/kubernetes/kubernetes/issues/36859#issuecomment-262022027

**Comment by keyan** [comment]
I'm running into issues debugging overlapping selectors only after having created the deployment. I think this would help a lot in terms of debugging my configuration.

@adohe Are you still planning to work on this? I am happy to give it a try. It would be my first contribution.

**Comment by adohe** [comment]
@kargakis IIRC, we have a fix on controller part, but I cannot find the original PR. do we still need this now?

**Comment by kargakis** [comment]
From 1.6, it will be impossible to have overlapping deployments because of the addition of owner refs. This means that two deployments with the same selector will maintain their own set of pods.

**Comment by adohe** [comment]
@kargakis cool~
