### ISSUE TITLE
OIDC authentication plugin: add support for authentication.k8s.io/v1beta1/tokenreviews

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#30905]
Brought up in #30784.

Can someone assign me to this?

**Comment by ericchiang** [comment]
also "area/auth" might be a better label for this

**Comment by deads2k** [comment]
> Brought up in #30784.
> 
> Can someone assign me to this?

@ericchiang I plumbed it through directly to the authenticator.  Unless you did something unusual, this should just work.

**Comment by ericchiang** [comment]
> @ericchiang I plumbed it through directly to the authenticator. Unless you did something unusual, this should just work.

Oh perfect. I'll test it and close this once I confirm it works.

**Comment by liggitt** [comment]
TokenReview API works directly against the authenticator, so OIDC token auth works with it as intended.
