### ISSUE TITLE
Service with type=LoadBalancer and clusterIP=None is allowed

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#30909]
The combination of LoadBalancer and headless is not valid today. The apiserver allows it and controller-manager makes the LB, but kube-proxy does not implement it.

We should either say that loadbalancer should treat the set of backends just like the service VIP or we should make apiserver reject it. I lean towards the latter. It should be a very simple change, great for someone who doesn't know this logic so well to learn it.

**Comment by derekwaynecarr** [comment]
sent a pr for this while investigating another validation issue.

**Comment by derekwaynecarr** [comment]
This was fixed in https://github.com/kubernetes/kubernetes/pull/33274
