### ISSUE TITLE
AWS ELBs do not reflect current registered Node after scale events

### ISSUE THREAD

**Issue by alph486** [kubernetes/kubernetes#30917]
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4+dd6b458", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"not a git tree", BuildDate:"2016-08-04T09:44:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4+coreos.0", GitCommit:"be9bf3e842a90537e48361aded2872e389e902e7", GitTreeState:"clean", BuildDate:"2016-08-02T00:54:53Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Provider**: AWS, m4.large across the board.
- **OS**: CoreOS stable (1068.9.0)
- **Kernel** (e.g. `uname -a`): `Linux <redacted> 4.6.3-coreos #2 SMP Fri Aug 5 04:51:16 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux`
- **Install tools**: `kube-aws` v0.8.1 (From CoreOS)
- **Others**:

**What happened**:
I have created about 30 ELBs using the `LoadBalancer` type of `Service`. I have an AutoScalingGroup on AWS that periodically adds and terminates nodes in my cluster. In more than one instance, I've noticed that my ELBs are out of sync with the nodes in my cluster (I see 3 instances in some ELBs where there should be 4).

When I saw this error, I tested by manually scaling the ASG +1 to see if it would reflect the change. It did, and all ELBs now reported 5 instances. In the ControllerManager log, I can see where scaling happens and it says `32 load balancers updated successfully` when a change happens; no immediate indication something is being missed. However, I do see this error near the load balancer log message which I was told by @justinsb may indicate dropping of notifications:

```
W0817 21:41:51.624334       1 reflector.go:334] pkg/controller/service/servicecontroller.go:150: watch of *api.Service ended with: couldn't queue object: couldn't create key for object &{lastState:0xc821aa24e0 appliedState:0xc821aa24e0 mu:{state:0 sema:0} lastRetryDelay:0}: object has no meta: struct service.cachedService lacks embedded TypeMeta type
```

**What you expected to happen**:
I expected the ELBs to all be updated with my current nodes the same way it would if the ELBs were directly listed in my AutoScalingGroup.

**How to reproduce it** (as minimally and precisely as possible):
Spin a cluster using the environment above. Let it stablize. Create >30 ELBs using services. Autoscale by 2 nodes. Wait 10 minutes. Terminate 2 instances. Wait 5 mins. Scale by 1.

During these events, audit the ELB state.

**Anything else do we need to know**:

**Comment by cmluciano** [comment]
@alph486 Are you still having this issue?

**Comment by alph486** [comment]
@cmluciano - I have changed the way I use ELBs in my infra. with Kubernetes so I cannot reproduce at the moment.

**Comment by cmluciano** [comment]
/close

please re-open if you are still having this problem

**Comment by alph486** [comment]
@cmluciano  Thanks for giving this issue attn. 👍  Has anyone tried my reproduction steps other than me?

I understand closing if theres reason to believe this was addressed in an interim release. But, just because I am not setup to reproduce again right now doesn't mean that the problem doesn't still exists, or that it is no longer reproducible.
