### ISSUE TITLE
Error log "Unable to inspect container" upon pod shutdown

### ISSUE THREAD

**Issue by DreadPirateShawn** [kubernetes/kubernetes#30926]
**Kubernetes version**:

```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Bare metal
- **OS** (e.g. from /etc/os-release): Ubuntu 12.04.4 LTS, Precise Pangolin
- **Kernel** (e.g. `uname -a`): Linux tuk6r1knode3 3.13.0-55-generic #92~precise1-Ubuntu SMP Sun Jun 14 18:32:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: N/A(?)
- **Others**: N/A(?)

**What happened**:

Sometimes we get an error-level log in Kubelet claiming "Unable to inspect container" after the pod has been properly shut down.

eg, during a rolling upgrade which behaved otherwise properly, we see this in the kubelet.log:

```
I0817 23:32:52.042648    2903 manager.go:1368] Killing container "a71923c1e106541e589424ffe825c72883873a81474c372984e1cce077d5ac05 agent-manager/agent-manager-20160729-205756-8pay1" with 30 second grace period
I0817 23:32:52.145473    2903 manager.go:1400] Container "a71923c1e106541e589424ffe825c72883873a81474c372984e1cce077d5ac05 agent-manager/agent-manager-20160729-205756-8pay1" exited after 102.782182ms
I0817 23:32:52.176595    2903 kubelet.go:2414] SyncLoop (PLEG): "agent-manager-20160729-205756-8pay1_agent-manager(55d78c9a-55cf-11e6-883b-00505693acba)", event: &pleg.PodLifecycleEvent{ID:"55d78c9a-55cf-11e6-883b-00505693acba", Type:"ContainerDied", Data:"a71923c1e106541e589424ffe825c72883873a81474c372984e1cce077d5ac05"}
E0817 23:33:32.699341    2903 manager.go:2139] Unable to inspect container "a71923c1e106541e589424ffe825c72883873a81474c372984e1cce077d5ac05": No such container: a71923c1e106541e589424ffe825c72883873a81474c372984e1cce077d5ac05
```

**What you expected to happen**:

Expect error-level logs only when something is broken -- currently this triggers alerts to QA and/or OPS on every occurrence, depending of course on whether it happens in test or prod. (If it's confirmed to _never_ be an actual problem, we can put a filter on this log entry... though obviously that would beg the same question of whether it should be logged as an error in the first place.)

**How to reproduce it** (as minimally and precisely as possible):

Happens occasionally during upgrades, and occasionally during pod restarts due to livenessProbe health check failure. (Maybe 1% of the time, or less?)

eg, this rolling upgrade:

```
$ kubectl --server=https://10.68.0.35:6443 --kubeconfig=/highland/config/kubernetes/config --context=test-tuk6r1 --namespace=agent-manager rollingupdate agent-manager-20160729-205756 --filename=/tmp/template_agent_manager_rc_20160817-233132.yaml
Created agent-manager-20160817-233132
Scaling up agent-manager-20160817-233132 from 0 to 2, scaling down agent-manager-20160729-205756 from 2 to 0 (keep 2 pods available, don't exceed 3 pods)
Scaling agent-manager-20160817-233132 up to 1
Scaling agent-manager-20160729-205756 down to 1
Scaling agent-manager-20160817-233132 up to 2
Scaling agent-manager-20160729-205756 down to 0
Update succeeded. Deleting agent-manager-20160729-205756
replicationcontroller "agent-manager-20160729-205756" rolling updated to "agent-manager-20160817-233132"
```

... generated this in the kubelet.log:

```
I0817 23:32:50.755806    2903 manager.go:1368] Killing container "ccaf1e639718a626dc39fd63acfbfe4b5bf54e7e4f5c3310bd0857bcc978033c agent-manager agent-manager/agent-manager-20160729-205756-8pay1" with 30 second grace period
I0817 23:32:50.756727    2903 manager.go:1024] Using docker native exec to run cmd [/control-scripts/service-stop.sh] inside container {docker ccaf1e639718a626dc39fd63acfbfe4b5bf54e7e4f5c3310bd0857bcc978033c}
I0817 23:32:51.337055    2903 manager.go:1400] Container "ccaf1e639718a626dc39fd63acfbfe4b5bf54e7e4f5c3310bd0857bcc978033c agent-manager agent-manager/agent-manager-20160729-205756-8pay1" exited after 581.188698ms
I0817 23:32:52.174025    2903 kubelet.go:2414] SyncLoop (PLEG): "agent-manager-20160729-205756-8pay1_agent-manager(55d78c9a-55cf-11e6-883b-00505693acba)", event: &pleg.PodLifecycleEvent{ID:"55d78c9a-55cf-11e6-883b-00505693acba", Type:"ContainerDied", Data:"ccaf1e639718a626dc39fd63acfbfe4b5bf54e7e4f5c3310bd0857bcc978033c"}
E0817 23:33:32.698659    2903 manager.go:2139] Unable to inspect container "ccaf1e639718a626dc39fd63acfbfe4b5bf54e7e4f5c3310bd0857bcc978033c": No such container: ccaf1e639718a626dc39fd63acfbfe4b5bf54e7e4f5c3310bd0857bcc978033c
```

and

```
I0817 23:32:52.042648    2903 manager.go:1368] Killing container "a71923c1e106541e589424ffe825c72883873a81474c372984e1cce077d5ac05 agent-manager/agent-manager-20160729-205756-8pay1" with 30 second grace period
I0817 23:32:52.145473    2903 manager.go:1400] Container "a71923c1e106541e589424ffe825c72883873a81474c372984e1cce077d5ac05 agent-manager/agent-manager-20160729-205756-8pay1" exited after 102.782182ms
I0817 23:32:52.176595    2903 kubelet.go:2414] SyncLoop (PLEG): "agent-manager-20160729-205756-8pay1_agent-manager(55d78c9a-55cf-11e6-883b-00505693acba)", event: &pleg.PodLifecycleEvent{ID:"55d78c9a-55cf-11e6-883b-00505693acba", Type:"ContainerDied", Data:"a71923c1e106541e589424ffe825c72883873a81474c372984e1cce077d5ac05"}
E0817 23:33:32.699341    2903 manager.go:2139] Unable to inspect container "a71923c1e106541e589424ffe825c72883873a81474c372984e1cce077d5ac05": No such container: a71923c1e106541e589424ffe825c72883873a81474c372984e1cce077d5ac05
```

[Edit: The above two snippets were intended to be different examples, but I copy-pasted the same one twice. Fixed now.]

We've also seen this during pod shutdown due to livenessProbe health check failure:

```
I0817 22:12:29.526643    2869 kubelet.go:2414] SyncLoop (PLEG): "riemann-20160711-204726-63wz3_riemann(0655f0eb-47a9-11e6-883b-00505693acba)", event: &pleg.PodLifecycleEvent{ID:"0655f0eb-47a9-11e6-883b-00505693acba", Type:"ContainerStarted", Data:"f26ee108f52d58183d32719991d1651f4dfe0182aca90e5bbbe66b187726415d"}
I0817 22:12:36.418659    2869 manager.go:1024] Using docker native exec to run cmd [/control-scripts/health-check.sh] inside container {docker f26ee108f52d58183d32719991d1651f4dfe0182aca90e5bbbe66b187726415d}
...
I0817 22:23:06.776416    2869 manager.go:1024] Using docker native exec to run cmd [/control-scripts/health-check.sh] inside container {docker f26ee108f52d58183d32719991d1651f4dfe0182aca90e5bbbe66b187726415d}
I0817 22:23:11.402742    2869 manager.go:1368] Killing container "f26ee108f52d58183d32719991d1651f4dfe0182aca90e5bbbe66b187726415d riemann riemann/riemann-20160711-204726-63wz3" with 30 second grace period
I0817 22:23:11.403984    2869 manager.go:1024] Using docker native exec to run cmd [/control-scripts/service-stop.sh] inside container {docker f26ee108f52d58183d32719991d1651f4dfe0182aca90e5bbbe66b187726415d}
I0817 22:23:12.081233    2869 manager.go:1400] Container "f26ee108f52d58183d32719991d1651f4dfe0182aca90e5bbbe66b187726415d riemann riemann/riemann-20160711-204726-63wz3" exited after 678.452106ms
I0817 22:23:12.778141    2869 kubelet.go:2414] SyncLoop (PLEG): "riemann-20160711-204726-63wz3_riemann(0655f0eb-47a9-11e6-883b-00505693acba)", event: &pleg.PodLifecycleEvent{ID:"0655f0eb-47a9-11e6-883b-00505693acba", Type:"ContainerDied", Data:"f26ee108f52d58183d32719991d1651f4dfe0182aca90e5bbbe66b187726415d"}
E0817 22:44:47.967092    2869 manager.go:2139] Unable to inspect container "f26ee108f52d58183d32719991d1651f4dfe0182aca90e5bbbe66b187726415d": No such container: f26ee108f52d58183d32719991d1651f4dfe0182aca90e5bbbe66b187726415d
I0817 22:44:49.033379    2869 kubelet.go:2414] SyncLoop (PLEG): "riemann-20160711-204726-63wz3_riemann(0655f0eb-47a9-11e6-883b-00505693acba)", event: &pleg.PodLifecycleEvent{ID:"0655f0eb-47a9-11e6-883b-00505693acba", Type:"ContainerDied", Data:"f26ee108f52d58183d32719991d1651f4dfe0182aca90e5bbbe66b187726415d"}
```

...although this repro case seems a more legitimate situation in which to raise an error, so our primary concern is the upgrade repro.

**Anything else do we need to know**:

N/A

**Comment by derekwaynecarr** [comment]
related: https://github.com/kubernetes/kubernetes/issues/22541

sometimes `docker ps` returns a container that `docker inspect` is unable to inspect.

the log is most likely a result of that issue, when this happens, we report the container state as unknown, and log an error.

**Comment by yujuhong** [comment]
As @derekwaynecarr said, bad containers could trigger this case. It's an error regardless of the impact, and logging an error message would help debugging (if it's needed).

> Expect error-level logs only when something is broken -- currently this triggers alerts to QA and/or OPS on every occurrence, depending of course on whether it happens in test or prod. (If it's confirmed to never be an actual problem, we can put a filter on this log entry... though obviously that would beg the same question of whether it should be logged as an error in the first place.)

Hmm...could you watch events from the apiserver instead? Those are more reliable IMO. If you don't want to go through the apiserver, you can still find all the events in the kubelet.log. I would not recommend sending alerts based on the logs as they are today.

**Comment by DreadPirateShawn** [comment]
Could the issue be one of timing, and perhaps treated as such? That is, after docker ps returns the containers, if inspect fails, could it be double-checked whether it still exists or if a container deletion event exists for it, and not log error when it can be determined not an error?

As for the logs, we have to err on the side of caution -- we can't just stop monitoring logs for errors because they're noisy, we've got to follow up here for feedback and tracking, to confirm our interpretation at the very least, and to help improve reliability when we find cases that are confirmed noise. Also, traking events from the apiserver wouldn't cover such things as nodes that are failing to join the cluster, for instance. To be responsible for the cluster in an HA production product, we've got to pay attention to all the warning signs we can. :-)

**Comment by yujuhong** [comment]
> Could the issue be one of timing, and perhaps treated as such? That is, after docker ps returns the containers, if inspect fails, could it be double-checked whether it still exists or if a container deletion event exists for it, and not log error when it can be determined not an error?

Sometimes docker just leaves a container in a bad state that kubelet can *see* it in `docker ps`, but couldn't inspect it. As for timing, kubelet expects to inspect the container after the container exits in normal circumstances, so that kubelet can update the pod status properly. If you can check whether the docker container gets removed before `docker inspect` in docker.log, that might help clarify the cause.


> As for the logs, we have to err on the side of caution -- we can't just stop monitoring logs for errors because they're noisy, we've got to follow up here for feedback and tracking, to confirm our interpretation at the very least, and to help improve reliability when we find cases that are confirmed noise. Also, traking events from the apiserver wouldn't cover such things as nodes that are failing to join the cluster, for instance. To be responsible for the cluster in an HA production product, we've got to pay attention to all the warning signs we can. :-)

Sure. The feedback will help improve the kuberentes components as well. I just wanted to warn you that even if you maintain a set of filters, that would probably be far from useful once you upgrade, and you'll have to start from scratch again.

**Comment by DreadPirateShawn** [comment]
Fair enough warning. :-)

Regarding the docker.log, I'll get back to you on that tomorrow, assuming logrotate hasn't been too aggressive.

**Comment by DreadPirateShawn** [comment]
Here's the relevant docker.log:
```
ESC[31mERROESC[0m[6224082] Handler for GET /images/docker.prod.skytap.com:5000/skytap/agent_manager:e749306c0c7419c2a125b2fde95e695b824cdff1/json returned error: No such image: docker.prod.skytap.com:5000/skytap/agent_manager:e749306c0c7419c2a125b2fde95e695b824cdff1 
ESC[31mERROESC[0m[6224116] Handler for GET /containers/ccaf1e639718a626dc39fd63acfbfe4b5bf54e7e4f5c3310bd0857bcc978033c/json returned error: No such container: ccaf1e639718a626dc39fd63acfbfe4b5bf54e7e4f5c3310bd0857bcc978033c 
ESC[31mERROESC[0m[6224116] Handler for GET /containers/a71923c1e106541e589424ffe825c72883873a81474c372984e1cce077d5ac05/json returned error: No such container: a71923c1e106541e589424ffe825c72883873a81474c372984e1cce077d5ac05 
```

... although "relevant" is relative, since unfortunately that looks like it doesn't the detail we were hoping for here, since "docker ps" and other such routine actions aren't output to the logs.

(It's possible to increase docker's log verbosity via `--log-level=debug` on the docker daemon, but we only enable that on our dev stacks, due to the *extreme* verbosity... there's not a really good middle ground, level-wise. Boo.)

**Comment by DreadPirateShawn** [comment]
It is worth noting, perhaps, that the docker logs do include many `Handler for GET /containers/foo/json returned error: No such container: foo` entries, but not all of them generate corresponding errors in the kubelet logs.

For instance, in the kubelet logs reported above, container `a71923c1e106541e589424ffe825c72883873a81474c372984e1cce077d5ac05` corresponds to pod `agent-manager-20160729-205756-8pay1` -- however, that pod includes three containers total, ALL of which appear in the docker log above in the same manner, despite only one manifesting an error in the kubelet.log.

**Comment by yujuhong** [comment]
> ... although "relevant" is relative, since unfortunately that looks like it doesn't the detail we were hoping for here, since "docker ps" and other such routine actions aren't output to the logs.

Yep, only debug-level docker logs show the requests, and they are extremely verbose. Basically I just wanted to check if kubelet (the container garbage collector) removes the container before the inspection -- which we could probably try to improve. I didn't check the v1.2.2 code yet, so not sure 1) if this could happen, and 2) whether kubelet logs anything before removing a container. Note that even if this happens, it's a race condition that wouldn't lead to any problem except the minor log spam. 

In either cases, I think the impact to the end user is very limited if there is any. I would recommend you filter these error messages because more obvious errors will be surfaced if they result in any error that's worth your attention :)

I'll also keep the issue open so that we can check if the race condition is a possibility.

> For instance, in the kubelet logs reported above, container a71923c1e106541e589424ffe825c72883873a81474c372984e1cce077d5ac05 corresponds to pod agent-manager-20160729-205756-8pay1 -- however, that pod includes three containers total, ALL of which appear in the docker log above in the same manner, despite only one manifesting an error in the kubelet.log.

There are some known scenarios in kubelet that would cause "no such container" responses from docker, but not all of them are necessary errors.

**Comment by DreadPirateShawn** [comment]
*Update:* We're no longer seeing this in our current Kubernetes version.
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.8", GitCommit:"d74e09bb4e4e7026f45becbed8310665ddcb8514", GitTreeState:"clean", BuildDate:"2017-08-03T18:12:08Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.8", GitCommit:"d74e09bb4e4e7026f45becbed8310665ddcb8514", GitTreeState:"clean", BuildDate:"2017-08-03T18:01:01Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by DreadPirateShawn** [comment]
Granted, there are two separate "No such container" tickets that we're tracking -- https://github.com/kubernetes/kubernetes/issues/28748 and https://github.com/kubernetes/kubernetes/issues/55421 -- but it looks like this particular manifestation no longer occurs.

**Comment by yujuhong** [comment]
@DreadPirateShawn thanks for the update. Closing the issue.
