### ISSUE TITLE
[kubelet test] Improve kubelet_node_status_test debug info

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#30952]
I find the output format `%v` of glog couldn't output useful information of  an `api.Node` object. The output of this line https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status_test.go#L492
 is

```
kubelet_node_status_test.go:491: expected
                &TypeMeta{Kind:,APIVersion:,}
                , got
                &TypeMeta{Kind:,APIVersion:,}
```

- It's difficult for me to tell the difference between `expected` and `got`.

- I prefer to use `diff.ObjectDiff(expectedNode, updatedNode)` to output the debug information as it will point out the starting character of the different objects.

I think this line https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status_test.go#L647 can use `diff.ObjectDiff()` as well.

**Comment by m1093782566** [comment]
@vishh 
What do you think about it?

**Comment by dchen1107** [comment]
sgtm. Why not send us a pr to improve the debuggability here? Thanks!

**Comment by m1093782566** [comment]
@dchen1107 The pr is #30953 

Would you please help to review this PR?

Thanks!

**Comment by m1093782566** [comment]
Fixed!

I am going to close this issue.

Thanks all!
