### ISSUE TITLE
[e2e test] Fix e2e test pause image hard code

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#30967]
I find most of the e2e test cases use `framework.GetPauseImageName(f.Client)` to represent the pause image, but I still find two places which are still using hard code (`"gcr.io/google_containers/pause-amd64:3.0"`). One place is here, https://github.com/kubernetes/kubernetes/blob/master/test/e2e/cluster_size_autoscaling.go#L464
and the other one is here, https://github.com/kubernetes/kubernetes/blob/master/test/e2e/density.go#L694.

I think we can replace both of them(`"gcr.io/google_containers/pause-amd64:3.0"`) with `framework.GetPauseImageName(f.Client)`.

@spxtr What's your opinion?

**Comment by spxtr** [comment]
Sounds reasonable to me. I think @luxas knows more?

**Comment by m1093782566** [comment]
@luxas What's your opinion?

**Comment by m1093782566** [comment]
I am going to close it.
