### ISSUE TITLE
Investigate whether we reuse connections after "429" error

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#30975]
From the recent runs of different scalability tests, I have a hypothesis that we are not reusing connections after "429" error is returned to the client.

Here is description of one tests that I've seen failed:
1. basically in 2000-node kubemark all watches were dropped at some point (that's a separate issue #30873 that is a bit unrelated here).
2. what happened next is that basically all watchers decided to do list + watch, and obvious a bunch of lists failed with 429 error (this is still expected). And we started retrying them.
 And this is still ok.
3. Since that point, apiserver started consuming ~30 cores (which also isn't completely unexpected).
4. But what IS unexpected to me, is that looking into profile ~70% of the CPU (which was ~20 cores) were spend in "doFullHandshake".
 And this is a bit strange to me.

 Do we do something specific on 429 errors (e.g. close the connection) so that we won't be able to reuse it in the future?
 Or do you have any other hypothesis, why we were mostly doing "full handshakes" at that time?

@krousey @lavalamp @caesarxuchao @kubernetes/sig-api-machinery

**Comment by smarterclayton** [comment]
On the server side, we can use

```
      // ErrorLog specifies an optional logger for errors accepting
        // connections and unexpected behavior from handlers.
        // If nil, logging goes to os.Stderr via the log package's
        // standard logger.
        ErrorLog *log.Logger
```

on http server to get more info.  Can we do the same thing on the client?  I don't see anything obvious, but knowing when a connection from a client is closed (vs. terminated by the server, vs gracefully terminated via Connection: Close) might be useful in debugging these cases.

The only thing I can think of is that the kubelet has multiple connections to the master, and so instead of reusing its pooled connections it's asking for new connections all at once (and blowing out the pool size in the client).

Can we verify that the kubelet TCP connection pool size is greater than the default (which is 2?).  Kubelet should definitely have a number of idle connections proportional to number of watches.

**Comment by krousey** [comment]
There's definitely a branch in the rest client where I think we don't fully read the response body on a 429. Though not explicitly stated in the docs, I think failing to read the entire body of a request also causes the TCP connection to not be reused.

This is a code snippet from the HTTP client's redirect code:

```go
			// Close the previous response's body. But
			// read at least some of the body so if it's
			// small the underlying TCP connection will be
			// re-used. No need to check for errors: if it
			// fails, the Transport won't reuse it anyway.
			const maxBodySlurpSize = 2 << 10
			if resp.ContentLength == -1 || resp.ContentLength <= maxBodySlurpSize {
				io.CopyN(ioutil.Discard, resp.Body, maxBodySlurpSize)
			}
			resp.Body.Close()
```

I can certainly add something like this to `restclient.Request.request`. I'm not sure if this is a problem for HTTP2 though. @wojtek-t was this running with HTTP2 enabled? I can't remember the status of that.

**Comment by lavalamp** [comment]
I'm pretty sure HTTP2 is off still.

**Comment by krousey** [comment]
Found the doc:

```go
        // Body represents the response body.
        //
        // The http Client and Transport guarantee that Body is always
        // non-nil, even on responses without a body or responses with
        // a zero-length body. It is the caller's responsibility to
        // close Body. The default HTTP client's Transport does not
        // attempt to reuse HTTP/1.0 or HTTP/1.1 TCP connections
        // ("keep-alive") unless the Body is read to completion and is
        // closed.
        //
        // The Body is automatically dechunked if the server replied
        // with a "chunked" Transfer-Encoding.
        Body io.ReadCloser
```

I will go ahead and patch this.

**Comment by smarterclayton** [comment]
Did we add a new error case that didn't catch this?  Since this is the 3rd time we've fixed an edge case on reading the entire body, we should probably do what we can to make sure others don't show up.

**Comment by krousey** [comment]
@smarterclayton It's the case where it's 429 or >= 500 and there's a Retry-After header. I'm going to add it to the same place where we ensure that the body is closed so that it should always catch it.

**Comment by smarterclayton** [comment]
k, thanks

**Comment by wojtek-t** [comment]
Thanks for debugging it (and yes, http2 was switched off in my tests).

And looking forward to see the fix. Thanks!
