### ISSUE TITLE
Add-on update procedure does not work after master node reboot

### ISSUE THREAD

**Issue by ScubaDrew** [kubernetes/kubernetes#31002]
BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.2.3

**Environment**: AWS
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**: kube-up
- **Others**:

**What happened**: updated add-ons per https://github.com/kubernetes/kubernetes/tree/master/cluster/addons#add-on-update-procedure

"To update add-ons, just update the contents of /etc/kubernetes/addons directory with the desired definition of add-ons."

After rebooting the master node, the updated YAML files are replaced with the default YAML files. 

**What you expected to happen**: The updated yaml files to persist. Even after a master node reboot.

**How to reproduce it** (as minimally and precisely as possible): Update the yaml files in /etc/kubernetes/addons/cluster-monitoring/influxdb/ and then reboot the master node.

**Anything else do we need to know**:

**Comment by ScubaDrew** [comment]
When a master node reboots it extracts the add-on yaml files from the kubernetes-salt.tar.gz file. Any updated yamls are replaced with the files contained in the tar.gz file. This seems contradictory to the documentation referened above.

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
I'm assuming sig-cluster-lifecycle owns addon management
