### ISSUE TITLE
Cut cAdvisor release for Kubernetes 1.4 release. 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#31015]
File this for tracking the progress...

**Comment by dims** [comment]
@timstclair @dchen1107 @grobie - Looks like this already happened in https://github.com/kubernetes/kubernetes/commit/1ec1c241d53cdd24b0f62a7d9f89772cb9d4ce2e can we close this tracking issue?

**Comment by timstclair** [comment]
I'd like to keep it open until we cut the non-alpha release of v0.24

**Comment by timstclair** [comment]
Release plan: https://docs.google.com/document/d/1gMWe9ns7rUNGXpeVEI_IQjIWKcDZBJJEshCQRl2NxDA/edit#

**Comment by dchen1107** [comment]
cAdvisor Godeps is updated to the most recent commit for 1.4 release. This is a tracking issue so that we can pick up the latest fix from both coreos and redhat: 

* inode accounting on imagefs on devicemapper (redhat):  https://github.com/kubernetes/kubernetes/issues/31501
* workaround the issue of resource accounting on coreos image:  https://github.com/kubernetes/kubernetes/issues/30939 

But both above issues should be blocker for 1.4 release. I lower down the priority to P2.

**Comment by dims** [comment]
@timstclair @dchen1107 - will we cut 1.4 with a final release of cadvisor v0.24? Does lowering the priority mean that we may end up cutting 1.4 before cadvisor release happens?

**Comment by timstclair** [comment]
I'm working on the release right now. I'm still planning on getting this into 1.4

**Comment by pwittrock** [comment]
@timstclair I am closing this now that your PR is merged.
