### ISSUE TITLE
.linted_packages causing a lot of rebases

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#31012]
.linted_packages is a list of packages that are go-lint clean. The idea is that you list the packages there that should remain that way, and the build will error if you introduce a lint error.

Also, the build will error if you make a package go-lint clean. It also tells you to just add it to the end of the list with an echo command. I have had to rebase 2 PRs 4 times each this week alone because of conflicts at the end of this file. My workaround now is that I'm adding mine to the middle of the list. But perhaps there should be a standard conflict-free way to add to this list.

**Comment by lavalamp** [comment]
@jfrazelle what do you think about switching the error to a warning, and then just periodically running a script that updates the .linted_packages file?

**Comment by jfrazelle** [comment]
This should help https://github.com/kubernetes/kubernetes/pull/31104

**Comment by jfrazelle** [comment]
then we can reassess after :)

**Comment by jfrazelle** [comment]
eventually when everything is linted this should be way better because we won't even need the file :)

**Comment by smarterclayton** [comment]
Resolved now.
