### ISSUE TITLE
Solution for Managing Multiple Docker Registries

### ISSUE THREAD

**Issue by etotheipi** [kubernetes/kubernetes#31018]
Our enterprise team is migrating our workflow to Kubernetes, but we've run into a crippling problem and so far that someone on the K8s team must have solved by now.  I searched for "registries" in this projects issues, but didn't see anything in the first 10 pages of results.  I read and posted on the Docker project, and all I found was people complaining about the same thing:

https://github.com/docker/docker/issues/1988

We have multiple private environments for getting our apps from dev out into production.  The problem is that Docker appears to have no mechanism for eliminating the public docker registry, and overriding with your own.  Instead, every Dockerfile, docker-build command, and K8s yaml file needs to be templated, with wrapper scripts around them to fill in the templates for us. 

For instance, in my test environment, I use a local registry visible to both my dev machine and vagrant k8s cluster.  I have to use  `private.devregistry.com:5000/` as a prefix on every image name throughout the entire project -- dockerfiles, build commands, k8s yaml files.  This has to be hardcoded, or else Docker will attempt  to use public docker-hub.  But then to make this usable in our QA environment, we have to have a script which replaces every registry string to `private.qa.reg.com:5001` so that it works with their registry on a different network.  And again in production which is on yet another network.  Now with everything templated, doing simple dev and testing has become much more complex, unable to use standard Docker and K8s commands.

All because Docker does not appear to have any way to set a global registry endpoint for all your commands.  Kubernetes makes it simple to manage multiple clusters, I appreciate that.

Is there a known solution for this, or is the team working on something to help manage this?  So far this is crippling our ability to use K8s.

One candidate idea was to actually modify the Docker source and attempt to build it ourselves.  Another was to use a dummy hostname on everything and change everything by modifying local `/etc/hosts`.  Both of these ideas are silly, but may be better than a complex web of templates.

**Comment by ligc** [comment]
We have similar situation, our several enterprise docker registries are in different datacenters, all the docker registries are synced automatically, the Kubernetes nodes pull images from the docker registry in its local datacenter by default, but when the registry in the local datacenter fails, we would like to have kubernetes automatically switches to the docker registries in remote datacenters. For now, modifying the DNS or /etc/hosts is the only option for us. It will be much better and graceful if kubelet could be configured to  point to several docker registries, and kubelet will try the second registry if the first registry fails.
