### ISSUE TITLE
Ungraceful node deletion handling 

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#31014]
In certain cases, node might be deleted ungracefully before unmounting/detach volumes. In current workflow, if node is deleted ungracefully, attachdetach controller will not be able to remove it from the actual and desired states, which leave the stale information in the cached states and cause problem in the following reconciler actions. 
https://github.com/kubernetes/kubernetes/blob/d06359d6a00cf420fb8240cb1cb66b4fd204d26d/pkg/controller/volume/attachdetach/cache/desired_state_of_world.go#L248

A few questions need to be clear before working on the solution
1. When a node fails (or deleted ungracefully), will a node delete event be observed from the shared informer? How about pod deletion? Also in this condition, can we assume that the volume is detached from the node and can be safely attache to somewhere else?
2. If network partition happens, how will the system react? The same question as in 1.

**Comment by goltermann** [comment]
@jingxu97 is this needed to ship 1.4, or can it be punted to 1.5?

**Comment by jingxu97** [comment]
@goltermann I think we can aim it for 1.5. Thanks!

**Comment by dims** [comment]
@jingxu97 ok to move this to 1.6? please holler if not appropriate

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by jingxu97** [comment]
Actually most of issue was fixed by #34859. Close this now.
