### ISSUE TITLE
kubelet symlinks /var/log/containers to incorrect place

### ISSUE THREAD

**Issue by baldeynz** [kubernetes/kubernetes#31021]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
var/log/containers symlink fluentd
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.2+coreos.0", GitCommit:"52a0d5141b1c1e7449189bb0be3374d610eb98e0", GitTreeState:"clean", BuildDate:"2016-07-19T17:45:13Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
aws
- **OS** (e.g. from /etc/os-release):
NAME=CoreOS
ID=coreos
VERSION=1068.9.0
VERSION_ID=1068.9.0
BUILD_ID=2016-08-05-0455
PRETTY_NAME="CoreOS 1068.9.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
- **Kernel** (e.g. `uname -a`):
- **Install tools**:

 kube-aws CLI tool

- **Others**:

**What happened**:

looking at the fluentd-elasticsearch configuration in td-agent.conf, it says that the kubelet creates symlinks that capture the pod name, namespace, container name & Docker container ID to the docker logs for pods in the /var/log/containers directory on the host.

Unfortunately it looks like the /var/log/containers directory on our node hosts have been symlinked to the wrong place 

it points to 

var/log/containers -> /mnt/ephemeral/docker/containers

when i think it should point to /var/lib/docker/containers/

We are running in aws and using the kube-aws CLI tool

    CoreOS 1068.8.0
    Kubernetes v1.3.2

Is this a possible bug ?

**What you expected to happen**:

that the kubelet create symlinks correctly, i.e /var/log/containers is linked to the logs in /var/lib/docker/containers

**How to reproduce it** (as minimally and precisely as possible):

mount a volume on a pod e.g

volumeMounts:
          - mountPath: /var/log
            name: varlog
  - hostPath:
          path: /var/log  
        name: varlog

**Anything else do we need to know**:

Nope

**Comment by dchen1107** [comment]
cc/ @tmrts

**Comment by baldeynz** [comment]
have a work around in place for this now. I have deleted the incorrect symlink and added this in the kubelet.service file

ExecStartPre=/usr/bin/mkdir -p /var/log/containers
ExecStartPre=/usr/bin/chmod 777 /var/log/containers
Environment="RKT_OPTS=--volume var-log,kind=host,source=/var/log --mount volume=var-log,target=/var/log"

**Comment by tmrts** [comment]
cc @aaronlevy @euank

**Comment by baldeynz** [comment]
The work around isnt permanent either. It seems that if the kubelet is restarted then the symlinks in /var/log/containers are not updated. After restarting the kubelet there are loads of error messages about failing to cleanup orphaned pods (see below)

-02a4f6f35ea7" dir; err: remove /var/lib/kubelet/pods/38cac425-6830-11e6-884a-02a4f6f35ea7/volumes/kubernetes.io~secret/default-token-3knpd: device or resource busy
Aug 23 00:40:33 ip-172-19-72-222.dev.fsniwaikato.kiwi kubelet-wrapper[31072]: I0823 00:40:33.985267   31072 kubelet.go:2027] Failed to remove orphaned pod "7b54c68e-6728-11e6-8eda-02a4f6f35ea7" dir; err: remove /var/lib/kubelet/pods/7b54c68e-6728-11e6-8eda-02a4f6f35ea7/volumes/kubernetes.io~secret/default-token-3knpd: device or resource busy
Aug 23 00:40:33 ip-172-19-72-222.dev.fsniwaikato.kiwi kubelet-wrapper[31072]: E0823 00:40:33.985286   31072 kubelet.go:2273] Failed cleaning up orphaned pod directories: [remove /var/lib/kubelet/pods/38cac425-6830-11e6-884a-02a4f6f35ea7/volumes/kubernetes.io~secret/default-token-3knpd: device or resource busy, remove /var/lib/kubelet/pods/7b54c68e-6728-11e6-8eda-02a4f6f35ea7/volumes/kubernetes.io~secret/default-token-3knpd: device or resource busy]
Aug 23 00:40:33 ip-172-19-72-222.dev.fsniwaikato.kiwi kubelet-wrapper[31072]: E0823 00:40:33.985302   31072 kubelet.go:2594] Failed cleaning pods: [remove /var/lib/kubelet/pods/38cac425-6830-11e6-884a-02a4f6f35ea7/volumes/kubernetes.io~secret/default-token-3knpd: device or resource busy, remove /var/lib/kubelet/pods/7b54c68e-6728-11e6-8eda-02a4f6f35ea7/volumes/kubernetes.io~secret/default-token-3knpd: device or resource busy]

**Comment by baldeynz** [comment]
it seems that the problem of not being able to update the symlinks in /var/log/containers might be linked with this issue? https://github.com/kubernetes/kubernetes/issues/25489

**Comment by baldeynz** [comment]
upgrade to 1.3.4 fixed the 'device or resource busy' issue.

Changes to the td-agent.conf in  gcr.io/google_containers/fluentd-elasticsearch:1.17

<source>
  type tail
  path /var/lib/rkt/pods/run/*/stage1/rootfs/opt/stage2/hyperkube/rootfs/var/log/containers/*.log
  pos_file /var/log/rkt-es-containers.log.pos
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  tag kubernetes.*
  format json
  read_from_head true
</source>

and he following mountPaths have fixed the issues we were seeing.

 _- mountPath: /var/lib/rkt/pods/run
            name: hyperkube
            readOnly: true
- hostPath:
          path: /var/lib/rkt/pods/run
         name: hyperkube_

apologies if this was logged incorrectly as an issue

**Comment by baldeynz** [comment]
as per comment above
