### ISSUE TITLE
[k8sm][Proposal] Algorithm enhancement on `k8sm-scheduler`

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#31068]
In Mesos, there're 3 types of offer are sent to framework (k8s): reserved, normal & revocable resources. As a framework, it's better to let user/consumer to decide how to use those offers, e.g. the user may prefer to use reserved resources firstly.

cc @jdef

**Comment by jdef** [comment]
Do you have a specific proposal for what the API should look like that allows a user to specify priority of resource consumption?

**Comment by k82cn** [comment]
The original requirement is to use reserved resources firstly; but I think we can extend it to other resources, e.g. revocable resources firstly. But I'm not sure which one is better: 1.) an parameter in k8sm-scheduler or 2.) an annotation in each YAML files.

**Comment by k82cn** [comment]
roadmap of kube-mesos, closed it here.
