### ISSUE TITLE
[Proposal] Integrate Namespace/Quota with CloudProviders

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#31069]
In Kubernetes, Namespace provide a way for multi-tenant; meanwhile, CloudProvide may provide similar features, e.g. Mesos. As a operator, I'd like to align those "multi-tenant" features; otherwise, I have to configure in CloudProvider, and then Kubernente, and align then manually :(.

**Comment by spiffxp** [comment]
/sig api-machinery
probably not the right home for this, but another example of why we might want a "sig-cloud" or something similar; namespaces seem pretty central to api in the meantime, so api-machinery

**Comment by k82cn** [comment]
ask kube-mesos-framework are retied, I'ld like to close this one.
