### ISSUE TITLE
K8S-merge-bot applies wrong labels

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#31063]
See: https://github.com/kubernetes/kubernetes/pull/29741

The pr has go source and is for the master branch. However the bot said it is not for master and applied retest-not-required-docs-only.

```
This PR is not for the master branch but does not have the cherrypick-approved label. Adding the do-not-merge label.
 @k8s-merge-robotk8s-merge-robot added do-not-merge retest-not-required-docs-only labels 6 minutes ago
 Hide all checks
```

**Comment by spiffxp** [comment]
/sig testing
/assign
the bot removed the label after this issue referenced the PR, so I'm going to go ahead and close this; please reopen if you find another example of this behavior
