### ISSUE TITLE
DeleteOptions doesn't work from kubectl to federated controllers

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#31077]
```
E0821 11:37:35.862805       1 namespace_controller.go:244] Failed to delete namespace mytestns: no kind "DeleteOptions" is registered for the internal version of group "federation"
```
cc: @nikhiljindal @quinton-hoole @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
@mwielgus How do I reproduce that error?
I see that our federation tests are all passing: https://k8s-testgrid.appspot.com/google-gce#gce-federation

**Comment by nikhiljindal** [comment]
fwiw, here is one place where we use DeleteOptions with federation client set and it works fine: https://github.com/kubernetes/kubernetes/blob/6b333d1f82e366c5903202def99383db1b5b2d02/test/e2e/federation-apiserver.go#L47.

**Comment by mwielgus** [comment]
This is easy to reproduce. Create a federated namespace and try to delete it.

**Comment by nikhiljindal** [comment]
ok. Am trying to create and delete a federation namespace in https://github.com/kubernetes/kubernetes/pull/31139. Will see if I get an error.

**Comment by jianhuiz** [comment]
This is what I had when I was testing delete federation replicaset.
In our internal demo, we used a work around by removing line `&api.DeleteOptions{},` in file `/federation/apis/federation/register.go`
I suspect this is related to api object registering mechanism which involves object type version overriding or conflicting

**Comment by lavalamp** [comment]
Is this still an open issue?

**Comment by nikhiljindal** [comment]
Yes. I was trying to debug server code, but after talking to @caesarxuchao today, it seems like its a client issue.

When sent a request using `federationClientset.Core().Namespaces().Delete(nsName, &api.DeleteOptions{})`, the body of the request that server receives contains:
```
Kind: DeleteOptions
APIVersion: federation/__internal
```

I was expecting the APIVersion to be "v1", but it should atleast be "/__internal", "federation/__internal" seems wrong.
https://github.com/kubernetes/kubernetes/blob/956501b1f0923786c404c062d8ba001a10b3a784/pkg/client/restclient/request.go#L553 is the place where that APIVersion is being set.
I am going to look at the Serializer code next.

**Comment by nikhiljindal** [comment]
I was trying to reproduce this today, but now it is failing before namespace controller reaches `federationClientset.Core().Namespaces().Delete(nsName, &api.DeleteOptions{})`

Now it is failing at:
https://github.com/kubernetes/kubernetes/blob/199338a551dd9cc52b4a57618ada3aeab6d37af4/federation/pkg/federation-controller/namespace/namespace_controller.go#L355 with the error: `Failed to update namespace <ns-name>: the server could not find the requested resource`.

I dont see any obvious change that would have broken this.
@mwielgus any idea?

**Comment by nikhiljindal** [comment]
I think the regression was because of https://github.com/kubernetes/kubernetes/pull/31470 where we added the Finalize method. It was a no-op before that (shouldnt it have been a compiler error for missing Finalize method??).
Now that we have the method it is trying to contact federation-apiserver on namespaces/finalize, but that subresource does not exist and hence we are now getting "server could not find the resource" error.
Verified that adding the finalize subresource on apiserver fixes this.

**Comment by nikhiljindal** [comment]
Sent https://github.com/kubernetes/kubernetes/pull/31925 to add finalizer subresource to federation apiserver.

**Comment by caesarxuchao** [comment]
> It was a no-op before that (shouldnt it have been a compiler error for missing Finalize method??).

I would expect a compiler error. Where is the no-op defined?

**Comment by yarntime** [comment]
Hi @nikhiljindal , I still get the following error msg when I try to delete a namespace from the federation: 
`namespace_controller.go:371] Failed to delete namespace zw-test: no kind "DeleteOptions" is registered for the internal version of group "federation"`

My kubernetes cluster info:
`
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0+a16c0a7", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0+a16c0a7", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7", Compiler:"gc", Platform:"linux/amd64"}
` 

Did I miss something?
