### ISSUE TITLE
Federated controllers should always pull the newest image

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#31078]
Currently it set to IfNotPresent that causes troubles during development - you have to either create a new image every time you push a new version or manually remove the old one from ALL cluster nodes. Otherwise the old version is run, despite the new version available. 

Also, any mis-push during release process can be quite problematic.

cc: @quinton-hoole @nikhiljindal @kubernetes/sig-cluster-federation

**Comment by madhusudancs** [comment]
One option is to modify the Deployment/Pod spec to say `imagePullPolicy: Always`. But the trouble with doing that is, we ship the same manifests in our release.

What I am trying to do instead is to generate a new image tag every time something has changed in your working directory (even uncommitted files) and the image is rebuilt. Then I am writing a small wrapper around it to redeploy federation components, which basically rewrites the deployment spec with the new image tag. That will probably solve this problem.

**Comment by quinton-hoole** [comment]
Scrubbing old bug reports. I believe that this is resolved by kubefed.  Re-open if necessary.  @madhusudancs
