### ISSUE TITLE
Kubectl get clusters output is missaligned

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#31073]
```
./cluster/kubectl.sh --context=federation-cluster get clusters
NAME       STATUS    VERSION   AGE
cluster1   Unknown   1m
```
cc : @kubernetes/sig-cluster-federation

**Comment by AdoHe** [comment]
The root cause is [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L937). Some small mistakes and just not found during review.
