### ISSUE TITLE
Federation-up.sh fails with an odd error if kube-apiserver files are not there.

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#31071]
It looks for a file called "*". There should be an if checking if any kubernetes api server is register and the error message should explain what to do to get the missing file.

cc: @kubernetes/sig-cluster-federation 

```
KUBERNETES_PROVIDER=gce FEDERATION_DNS_PROVIDER=google-clouddns FEDERATION_NAME=myfederation DNS_ZONE_NAME=myfederation.example FEDERATION_PUSH_REPO_BASE=gcr.io/mwielgus-proj ./federation/cluster/federation-up.sh
namespace "federation" created
No resources found
secret "default-token-uqjvb" deleted
service "federation-apiserver" created
attempting to get federation-apiserver loadbalancer hostname (1 / 30)
attempting to get federation-apiserver loadbalancer hostname (2 / 30)
attempting to get federation-apiserver loadbalancer hostname (3 / 30)
attempting to get federation-apiserver loadbalancer hostname (4 / 30)
attempting to get federation-apiserver loadbalancer hostname (5 / 30)
attempting to get federation-apiserver loadbalancer hostname (6 / 30)
attempting to get federation-apiserver loadbalancer hostname (7 / 30)
Found federation-apiserver host at 104.154.96.23
cluster "federation-cluster" set.
user "federation-cluster" set.
context "federation-cluster" set.
switched to context "federation-cluster".
user "federation-cluster-basic-auth" set.
Wrote config for federation-cluster to /usr/local/google/home/mwielgus/.kube/federation/federation-apiserver/kubeconfig
secret "federation-apiserver-kubeconfig" created
Creating secret with name: *
error: error reading /usr/local/google/home/mwielgus/.kube/federation/kubernetes-apiserver/*/kubeconfig: no such file or directory
```

**Comment by owenhaynes** [comment]
How do you get around this, as can not use the new Federation Instructions as they do not support AWS.

**Comment by madhusudancs** [comment]
@owenhaynes please try out the new deployment mechanism described here - http://kubernetes.io/docs/admin/federation/#prerequisites

**Comment by owenhaynes** [comment]
I would but the new deployment does not work on aws, only gcp.

**Comment by madhusudancs** [comment]
@owenhaynes Could you please tell a little bit more about why it did not work for you on AWS? Once you have a Kubernetes cluster created (by whichever method you prefer, `kube-up`, [`kubeadm`](http://kubernetes.io/docs/getting-started-guides/kubeadm/) or `kops`), the steps described in the federation admin guide should work irrespective of where the cluster is. If it isn't then there is a bug that we need to fix. Details about the issue you are seeing will be useful for debugging.

If you would still prefer to use the old method and workaround this problem, you could directly edit the `common.sh` script. Specifically, this line - https://github.com/kubernetes/kubernetes/blob/master/federation/cluster/common.sh#L168 to not have a `*`, but instead list all the directories directly. But it is not recommended.

**Comment by owenhaynes** [comment]
Get the following error when running the deploy script from the new deployment way

Supported providers: gce, gke

Using the google prebuilt images and just the following command

federation/deploy/deploy.sh deploy_federation with KUBERNETES_PROVIDER=aws set

The error looks to come from here

https://github.com/kubernetes/kubernetes/blob/master/federation/deploy/deploy.sh
```bash
 if [[ "${KUBERNETES_PROVIDER:-}" != "gce" && "${KUBERNETES_PROVIDER:-}" != "gke" ]]; then
    echo "Supported providers: \"gce\", \"gke\""
    exit 1
  fi
```
 I think #31908 is relevant to this?

Hence why I was looking to do it the old way.

**Comment by madhusudancs** [comment]
@owenhaynes oops, my fault. I will fix that and hopefully we can push that out with 1.4.1.

For now, a workaround is to replace the `exit 1` in that block with `return`. You can manually modify that script and try it.

The right fix is it branch out to https://github.com/kubernetes/kubernetes/blob/master/federation/deploy/deploy.sh#L66 in the case of non-GCE/GKE clusters.

**Comment by madhusudancs** [comment]
@owenhaynes filed Issue #33886 to track this and assigned it to myself.

**Comment by ramukima** [comment]
@madhusudancs - I am very new to how Kubernetes Federation control is supposed to work. Is it possible for me to setup federation for the following scenario :

1. I have three Kubernetes Clusters using kubeadm on Ubuntu.
2. I want to setup federation control plane on one of these machines and the remaining two cluster would join the federation control.

What additional things I need in order to have this setup ? I tried your proposed workaround 'exit vs return'.

```
+++ [1202 14:10:29] Ensure provider is supported ubuntu
Supported providers: "gce", "gke"
+++ [1202 14:10:29] Action: deploy federation components
WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.
Cannot initialize Kubernetes connection: Error loading config file "/root/.kube/config": read /root/.kube/config: is a directoryTiller is listening on :44134
2016/12/02 14:10:31 transport: http2Client.notifyError got notified that the client transport was broken EOF.
Error: transport is closing
```

**Comment by madhusudancs** [comment]
@ramukima 

> Is it possible for me to setup federation for the following scenario :

> 1. I have three Kubernetes Clusters using kubeadm on Ubuntu.
> 2. I want to setup federation control plane on one of these machines and the remaining two cluster would join the federation control.

Assuming you meant "one of these clusters" instead of "one of these machines", yes it is possible to setup Federation on this setup. And that's the regular workflow now.

> What additional things I need in order to have this setup ? I tried your proposed workaround 'exit vs return'.

Do you have a local kubeconfig file, i.e. $HOME/.kube/config from where you are running these commands? If you don't, you will need one. See the documentation for [`kubectl config set-context`](http://kubernetes.io/docs/user-guide/kubectl/kubectl_config_set-context/), [`kubectl config set-cluster`](http://kubernetes.io/docs/user-guide/kubectl/kubectl_config_set-cluster/) and [`kubectl config set-credentials`](http://kubernetes.io/docs/user-guide/kubectl/kubectl_config_set-credentials/) on how to do this.

**Comment by ramukima** [comment]
I am unable to get past this...

```
:~/kubernetes# federation/deploy/deploy.sh deploy_federation
+++ [1215 23:53:49] Ensure provider is supported
+++ [1215 23:53:49] Ensure credential files exist
Please ensure Google credentials file "/root/.config/gcloud/application_default_credentials.json" exists.
+++ [1215 23:53:49] Action: deploy federation components
WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.
Tiller is running on :44134
Error: release fallacious-ferrit failed: Get http://localhost:8080/api: dial tcp [::1]:8080: getsockopt: connection refused
```
The cluster setup I have was created using kubeadm tool. Do I need to deploy additional services ? Is it the kubeproxy I need to run on 8080 ?

**Comment by madhusudancs** [comment]
@ramukima would you be able to use the new version of Kubernetes (1.5.x+)? If you can, then I recommend using `kubefed` - http://kubernetes.io/docs/admin/federation/kubefed/ for turning up the control plane. Also, you don't have to upgrade your existing Kubernetes clusters. You just need to download the new version of the release to use `kubefed`.

**Comment by ramukima** [comment]
I will try it and post the results here.

**Comment by ramukima** [comment]
@madhusudancs I tried the kubefed and am stuck. Here is what I tried -
1. A kubernetes cluster setup on two different machines using kubeadm
2. Both machines can access each other on their public IP
3. Downloaded kubernetes 1.5 and followed instructions on kubefed document you mentioned.
4. Copied /etc/kubernetes/admin.conf to ~/.kube/config on the federation host (one of the machines)
5. Run kubefed init sdp --host-cluster-context=admin@kubernetes --dns-zone-name="example.com" on the federation host machine.

Step 5 just hangs without any progress reported. I killed, deleted the federation namespace manually and tried again. Still no luck. Could you please guide ?

**Comment by madhusudancs** [comment]
@ramukima strace output isn't clear on which resource is unavailable. When you run `kubefed init` next time, could you please run `kubectl --namespace=federation-system get pod,services` in another terminal in parallel and see what it prints? Also, it will be useful for debugging if you can share it.

Also, since you said you are running this on Ubuntu machines, do you know if you have a loadbalancer implementation for the provider you are using?  

It is kind of pain that there are no verbose logs for `kubefed init`, while there are for `kubefed join`. I have filed Issue #39004 for that.

**Comment by quinton-hoole** [comment]
Closing old bug reports.  Re-open if necessary.
