### ISSUE TITLE
Federation admin doc should mention about FEDERATION=true needed in kube-up.sh

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#31072]
Or describe what to do to get the required configs in place. 

Link: http://kubernetes.io/docs/admin/federation/

Currently it only says:

```
This guide assumes that we have a running Kubernetes cluster. 
If not, then head over to the getting started guides to bring up a cluster.
```

```
Once we have the images, we can run these as pods on our existing kubernetes cluster. 
The command to run these pods on an existing GCE cluster will look like:
```

If the required config is not there the set up process ends up with #31071.

cc: @kubernetes/sig-cluster-federation

**Comment by quinton-hoole** [comment]
Cleaning up old issues.  kubefed now does all of this.  Closing.
