### ISSUE TITLE
Federated api server should validate cluster api server address

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#31074]
Currently it is possible to pass just an IP address without any schema/port information (no https://) which leads to connectivity problems. 

Also http://kubernetes.io/docs/admin/federation/ should give an example of valid cluster object and tell to include the schema . 

Ideally, if FEDERATION=true is passed to kube-up.sh the corresponding cluster.yaml file should be generated automatically.

cc: @quinton-hoole @kubernetes/sig-cluster-federation

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#202.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
