### ISSUE TITLE
rkt: Support privileged pods

### ISSUE THREAD

**Issue by Quentin-M** [kubernetes/kubernetes#31100]
Since rkt 1.13, more specifically https://github.com/coreos/rkt/pull/2983, it is possible to run pods with security opt-outs, a.k.a. _privileged_ pods, using the new `--insecure-options={capabilities,paths,seccomp,all-run}` command-line parameters.

Currently, Kubelet sets all caps to rkt containers when `v1.SecurityContext.Privileged` is used. Instead, the kubelet should use `--insecure-options=all-run`.

Until https://github.com/coreos/rkt/issues/2996 is implemented, it is a per-pod option rather than per-app one, we might have to decide to pass it when every containers in the pod have `v1.SecurityContext.Privileged` (or use an annotation...).

**Comment by euank** [comment]
cc @kubernetes/sig-rktnetes I think we were going to work on that this week, thanks for filing the issue!
