### ISSUE TITLE
Failure to delete openstack Load Balancer v1

### ISSUE THREAD

**Issue by ksoftirqd** [kubernetes/kubernetes#31118]
**BUG REPORT**

**Kubernetes version** (use `kubectl version`): v1.3.2

**Environment**:
- **Cloud provider or hardware configuration**: openstack
- **OS** (e.g. from /etc/os-release): Ubuntu 14.04
- **Kernel** (e.g. `uname -a`): 3.13.0-71-generic
- **Install tools**: ansible
- **Others**: lbaas v1

**What happened**:
When LBaaS v1 is used, after service delete request, kubernetes fails to delete loadbalancer pool and its members, that were associated with the service:

> servicecontroller.go:201] Failed to process service delta. Retrying in 5s: Expected HTTP response code [202 204] when accessing [DELETE https://neutron.example.com/v2.0/lb/pools/50f4be7b-ad5c-4691-8d9e-8af6c77846a3], but got 409 instead
> {"NeutronError": {"message": "Pool 50f4be7b-ad5c-4691-8d9e-8af6c77846a3 is still in use", "type": "PoolInUse", "detail": ""}}

It seems that `(lb *LbaasV1) EnsureLoadBalancerDeleted()` in pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go:944 only deletes monitors before trying to delete pool. Since pool members still exist, pool fails to be deleted. And since there are no attempts to delete members, pool and its members left undeleted forever after service was removed.

**What you expected to happen**:
All members, monitors and pool associated with the service to be deleted.

**How to reproduce it** (as minimally and precisely as possible):
`kubectl expose deployments my-nginx --type=LoadBalancer`
`kubectl delete svc my-nginx`

**Comment by jamiehannaford** [comment]
Looks like this was fixed by https://github.com/kubernetes/kubernetes/commit/fa5551b80d41cc62d127e40f9135574eed0a0dee. Can we close @dims?

**Comment by dims** [comment]
ah cool. closing

/assign
