### ISSUE TITLE
hack/local-up-cluster.sh failed

### ISSUE THREAD

**Issue by drngsl** [kubernetes/kubernetes#31119]
kubernetes branch: master

Log:
`root@k8s-build:/opt/github/kubernetes# ./hack/local-up-cluster.sh 
make: Entering directory `/opt/github/kubernetes'
make[1]: Entering directory `/opt/github/kubernetes'
make[1]: Leaving directory `/opt/github/kubernetes'
make[1]: Entering directory `/opt/github/kubernetes'
+++ [0822 10:20:37] Generating bindata:
    /opt/github/kubernetes/test/e2e/framework/gobindata_util.go
Cannot find go-bindata. Install with
  go get -u github.com/jteeuwen/go-bindata/go-bindata
../../../../../../test/e2e/framework/gobindata_util.go:19: running "../../../hack/update-bindata.sh": exit status 5
make[1]: *** [_output/bin/deepcopy-gen] Error 1
make[1]: Leaving directory `/opt/github/kubernetes'
make: *** [generated_files] Error 2
make: Leaving directory `/opt/github/kubernetes'
!!! Error in ./hack/local-up-cluster.sh:94
  'make -C "${KUBE_ROOT}" WHAT="cmd/kubectl cmd/hyperkube"' exited with status 2
Call stack:
  1: ./hack/local-up-cluster.sh:94 main(...)
Exiting with status 1`

I didn't make any change to source code, but it really failed.
So I want to know some other arguments needed for this command.

**Comment by dims** [comment]
@drngsl Please see the output, it's asking you to run `go get -u github.com/jteeuwen/go-bindata/go-bindata` before running `./hack/local-up-cluster.sh`
