### ISSUE TITLE
hack/update-api-reference-docs.sh is not consistent with hack/verify-api-reference-docs.sh

### ISSUE THREAD

**Issue by rootfs** [kubernetes/kubernetes#31129]
`hack/update-api-reference-docs.sh` filtered timestamp but `hack/verify-api-reference-docs.sh` doesn't. This causes a false positive happens.

**Comment by rootfs** [comment]
actually the diff is 
```diff
-</html>
+</html>
\ No newline at end of file
```

**Comment by khenidak** [comment]
+1 the behavior is consistent at the current head.
