### ISSUE TITLE
Proposal: use ipset in kube-proxy to improve readability and performance

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#31128]
Copy from http://ipset.netfilter.org/:

> If you want to
> - store multiple IP addresses or port numbers and match against the collection by iptables at one swoop;
> - dynamically update iptables rules against IP addresses or ports without performance penalty;
> - express complex IP address and ports based rulesets with one single iptables rule and benefit from the speed of IP sets
>   then ipset may be the proper tool for you.

Seems that ipset is much more suitable than iptables in kube-proxy use case. 

@bprashanth @kubernetes/sig-network

**Comment by thockin** [comment]
yes, it was left as an avenue for optimization
