### ISSUE TITLE
Label validation is using inefficient regexes

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#31124]
According to #30875 (and https://github.com/kubernetes/kubernetes/pull/30976#issuecomment-241437378), we are spending a lot of time in regex validation.  While #30976 bypassed validation for the case where the labels should already have been validated, we should also look at replacing inefficient regexes with something that does not consume 20% of CPU time :-)

I thought the go regex implementation was supposed to be much better behaved, but perhaps we are doing something unexpected.

(It could also be that this is simply a slow operation - regex or not.)

**Comment by dims** [comment]
@justinsb possibly this is the cause? https://github.com/golang/go/issues/13288

**Comment by timothysc** [comment]
@kubernetes/sig-scalability I think we should start to triage these as part of our regular meetings.

**Comment by smarterclayton** [comment]
This has been resolved.
