### ISSUE TITLE
AWS: Add logging line for #30695

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#31127]
Per https://github.com/kubernetes/kubernetes/pull/30695#issuecomment-241137934

For smooth operations, we want to know if this is happening in prod.

cc @krancour

**Comment by justinsb** [comment]
Also I wonder if the `beta` bit in the annotations adds value, vs just documenting it as a beta feature

**Comment by krancour** [comment]
> Also I wonder if the beta bit in the annotations adds value, vs just documenting it as a beta feature

fwiw, the annotations I chose were selected for parity with convention already in use for annotations defining other ELB properties: e.g. `service.beta.kubernetes.io/aws-load-balancer-proxy-protocol`

But I agree it's worth questioning whether, across the board, "beta" shouldn't appear in those annotation names.

**Comment by justinsb** [comment]
@krancour absolutely agree - and you did the right thing.  It was more a note-to-self to consider whether to support non-beta versions of these annotations.

**Comment by goltermann** [comment]
Moving out of v1.4 as this is a P2.
