### ISSUE TITLE
AWS: S3 buckets publicly accessible and wrong permissions in template

### ISSUE THREAD

**Issue by 2opremio** [kubernetes/kubernetes#31133]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): s3, bucket, permissions

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.3.0

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): the one used by kube-up.sh
- **Kernel** (e.g. `uname -a`): the one used by kube-up.sh
- **Install tools**: kube-up.sh
- **Others**:

**What happened**:

The [S3 bucket created by kube-up](https://github.com/kubernetes/kubernetes/blob/release-1.3.0/cluster/aws/util.sh#L667-L675) is publicly accesible.

Also, the [S3 IAM permissions](https://github.com/kubernetes/kubernetes/blob/release-1.3.0/cluster/aws/templates/iam/kubernetes-minion-policy.json#L8) don't respect the value of the `AWS_S3_BUCKET` env variable and are hardcoded to `kubernetes-*`

**What you expected to happen**:

I don't think the bucket should be public.

If it is public for a good reason, the IAM policies shouldn't contain explicit permission for S3 or at the very least they should follow the bucket name set by `AWS_S3_BUCKET`

**How to reproduce it** (as minimally and precisely as possible):

Just calling `kube-up.sh`

**Anything else do we need to know**:

Not really

**Comment by 2opremio** [comment]
I think @k8s-merge-robot got it wrong :) This is not really related to kubectl.

**Comment by justinsb** [comment]
@2opremio I agree, but we're not really making these sorts of changes in kube-up any more - it is in maintenance mode.  I recommend trying out kops: kops uses a private bucket, and it has a policy that restricts access to that bucket.  And we're working to tighten it further: https://github.com/kubernetes/kops/issues/376

OK to close?

**Comment by justinsb** [comment]
kube-up is now no longer supported for AWS (and is generally deprecated on all platforms).  I personally recommend checking out kops, which has much tighter permissions including on our buckets - still not as strong as I would like, but we're making progress now!

Closing as there's not anything we can fix here any more.
