### ISSUE TITLE
Refactor mount related code

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#31137]
A few places related to volume mount needs to be refactored
1. TearDown() function in different attachers including gce, aws, cinder (cinder needs refactor in TearDown) are identical. Also UnmountPath in /pkg/volume/util has the same code. Should consolidate them together
2. Functions including IsLikelyNotMountPoint(), DeviceOpened(), PathIsDevice() does not need mounter interface at all. They should be utility functions
3.  /pkg/volume/util.go vs. /pkg/util/mount/mount_linux.go where to put utility functions?

**Comment by AlexMioMio** [comment]
占个坑 @jingxu97
