### ISSUE TITLE
Lots of upgrade tests have been broken for 2 months

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#31148]
A couple dozen upgrade and skew e2e test suites have been broken for exactly the same amount of time (1 month, 23 days). I looked at 2, and they were both broken due to:

```
/workspace/sh2ju.sh: line 125: bc: command not found
```

This problem was introduced by #27825 in June, and apparently wasn't entirely fixed by #30556.

We lost 2 months of upgrade test coverage due to this. What can we do to notice such failures earlier? 

Visible here, if you scroll all the way to the right:
https://k8s-testgrid.appspot.com/google-upgrade#gke-1.3-1.4-kubectl-skew&width=3

Also, we have repeated problems with the lack of portability of shell scripts. If we're not going to ban them, can we make them more hermetic?

cc @ixdy @kubernetes/sig-testing @freehan @spxtr @lavalamp

**Comment by rmmh** [comment]
I'm working on feeding all federated test results (currently in GCS) into BigQuery, so we can have a single unified dashboard showing build and test failures.

**Comment by spxtr** [comment]
> What can we do to notice such failures earlier?

Right now they don't actually have an owner, and they never quite got stable enough to stop the world when they break.

**Comment by ixdy** [comment]
The docker image we're using for e2e tests is based on an [old version of the kubekins-test image](https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/e2e-image/Dockerfile#L18) which doesn't have my fix from #27825. @fejta

**Comment by lavalamp** [comment]
It should be trivial to add them to the non-blocking list.

**Comment by ixdy** [comment]
The `bc` issue is fixed. It looks like #31149 is the main problem now.
