### ISSUE TITLE
FEAT GKE Specify Kubernetes install version

### ISSUE THREAD

**Issue by lachie83** [kubernetes/kubernetes#31142]
Please allow the installation version of Kubernetes to be specified upon cluster create via the console and gcloud tool. 

Current behavior is to provision the latest stable then downgrad which isn't always desirable. Also you can only downgrade the nodes NOT the master.

Example command

```
gcloud container clusters create gke-cluster-01 --machine-type n1-standard-2 --num-nodes 1 --additional-zones us-central1-b,us-central1-c --version 1.2.6
```

**Comment by craigbox** [comment]
Raised with the gcloud SDK team.

**Comment by kargakis** [comment]
Doesn't seem like an issue specific to k8s, closing
