### ISSUE TITLE
Tests are failing because they can't find kubectl.sh

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#31149]
```
fork/exec /workspace/../kubernetes_skew/cluster/kubectl.sh: no such file or directory
```

Example:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.3-1.4-upgrade-master/460

Looks like the regression happened in the past couple weeks:
https://k8s-testgrid.appspot.com/google-upgrade#gke-1.3-1.4-upgrade-master&width=3

cc @kubernetes/sig-testing @ixdy

**Comment by ixdy** [comment]
cc @kubernetes/test-infra-maintainers

**Comment by ixdy** [comment]
I suspect #28575 is what broke this. The path `/workspace/../kubernetes_skew` makes no sense.

**Comment by ixdy** [comment]
Oh, yeah. The original version of this was doing something like `/workspace/kubernetes_old/../kubernetes/blah`. The changes introduced in #28575 are wrong.

**Comment by fejta** [comment]
Yeah the `..` doesn't belong there.

**Comment by bgrant0607** [comment]
@ixdy @fejta Thanks. I should expect the kubectl tests to run after the next build?

https://k8s-testgrid.appspot.com/google-upgrade#gke-1.3-1.4-upgrade-master

**Comment by bgrant0607** [comment]
Also, ref https://github.com/kubernetes/test-infra/issues/429 so that someone might notice such failures earlier in the future

**Comment by ixdy** [comment]
Not fixed yet - we need to update the docker image used for tests.

**Comment by ixdy** [comment]
Should be fixed now.
