### ISSUE TITLE
Add more debug info to replicaset controller

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#31152]
Especially around planer, its input and output.

**Comment by pwittrock** [comment]
@mwielgus 

I am moving this out of the blocking issues we are tracking for the 1.4 release.  If there is still 1.4 work to be done here that should be tracked in the weekly burndown meetings, move it back and provide daily updates to this issue.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#67.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
