### ISSUE TITLE
Add events to ingress controller

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#31155]

**Comment by goltermann** [comment]
Moving out of v1.4 as this is a P2.

**Comment by dims** [comment]
switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree) @mwielgus @quinton-hoole

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by marun** [comment]
Not a release blocker for 1.7.

@quinton-hoole I see some events being recorded in the ingress controller.  Is there more to do, or can this issue be closed?

**Comment by quinton-hoole** [comment]
@marun Yes, it's done.  Thanks for being the janitor :-)
