### ISSUE TITLE
e2e test kubelet TLS bootstrap flow

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#31168]
test the bootstrap kubelet request and auto approve controller flow
- probably will require test framework changes to allow custom invocation options for some tests
- probably will require updating gce kube-up to use kubelet TLS bootstrap optionally

ref https://github.com/kubernetes/features/issues/43

cc @liggitt @gtank @kubernetes/sig-cluster-lifecycle

**Comment by roberthbailey** [comment]
@mikedanese do we have e2e tests for this yet?

**Comment by mikedanese** [comment]
Yes. Not for gce kube up, but kubeadm e2es do this. There's this that runs in kube-up:

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/certificates.go

I'd say leave this open until we are running tls bootstrap with kube-up in gce

**Comment by luxas** [comment]
Hmm, @mikedanese kubeadm doesn't use kubelet's built-in function to do the TLS bootstrap yet, does it?

Referencing: https://github.com/kubernetes/kubeadm/issues/173

I'm not sure kubeadm e2e's are covering the kubelet TLS bootstrap; they cover kubeadm's TLS bootstrap functions. Nearly the same code, but not 100%

**Comment by mikedanese** [comment]
Ya, that's why I say leave it open until we do this in kube-up GCE. We test multiple client bootstrap flows but not the kubelet experimental flag one. That's the one I'm planning on using in GCE.

**Comment by luxas** [comment]
Ok, perfect, then I read your last comment wrongly.

@mikedanese Will the kubelet TLS bootstrap flag graduate to beta in v1.7? I assume so in case GCE will use it...

We should probably start using it in kubeadm as well in v1.7 https://github.com/kubernetes/kubeadm/issues/173
