### ISSUE TITLE
Improve (or remove) phrasing(s) that confuse users of kubectl get

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#31160]
The output for `kubectl get pods` was enhanced in #28352 to render an explanation about pods that were omitted from the result because they were in a completed state.

```
    $ cluster/kubectl.sh get pods
    NAME                      READY     STATUS    RESTARTS   AGE
    cpuhog-4096054171-qpjy2   1/1       Running   0          5s
      info: 1 completed object(s) was(were) not shown in pods list. Pass --show-all to see all objects.
```

After usage of this feature, many have complained:

1. excessive usage of parenthesis
1. mixed usage of "object(s)" and "pods"
1. almost every user of the system will have terminal pods so this message always appears

We should improve (or remove) the message.

/cc @kubernetes/rh-cluster-infra @kubernetes/kubectl @kubernetes/rh-ux @smarterclayton

**Comment by smarterclayton** [comment]
I missed this during my review.  It should also not be indented, and
separated by one line from the previous group (the separation we can do in
a separate PR after we correct these issues, because Juan's filter changes
would likely impact how that is implemented).

**Comment by fabianofranz** [comment]
If we are to keep this message, I'd remove indentation and add an additional line break to make it separated from the main table. Has to go to `Stderr`. I'd also make it `printer.BeforePrint(...)` and `printer.AfterPrint(...)` which would make it more extensible to other kinds of usage.

**Comment by asalkeld** [comment]
also see #31943

**Comment by asalkeld** [comment]
I can work on this.

**Comment by pwittrock** [comment]
@asalkeld @derekwaynecarr @smarterclayton 

I am moving this out of the blocking issues we are tracking for the 1.4 release because the unfinished pieces are non-blockers for the release and do not need to be tracked in the burndown meetings.  If there are components besides docs & tests that need to be completed, please move it back to the 1.4 milestone and provide daily status updates.
