### ISSUE TITLE
Support 'kubectl proxy deployment/nginx' to auto append resource URL

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#31175]
Support something like `kubectl proxy deployment/nginx` to have the proxy go directly to that resource instead of having to supply it to the browser

**Comment by bgrant0607** [comment]
`kubectl proxy` is a client-side proxy that uses kubectl to handle auth to the apiserver.
http://kubernetes.io/docs/user-guide/connecting-to-applications-proxy/

`port-forward` works more like you suggest:
http://kubernetes.io/docs/user-guide/connecting-to-applications-port-forward/

We could create another command or subcommand that does that for the http proxy in apiserver.
