### ISSUE TITLE
Add the ability to request allowed usage in a CSR

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#31170]
This may mean "signing profiles" or exposing allowed usage directly.

Previous discussion https://github.com/kubernetes/kubernetes/pull/30922#discussion_r75415590

ref https://github.com/kubernetes/features/issues/43

cc @gtank @liggitt @kubernetes/sig-cluster-lifecycle

**Comment by gtank** [comment]
Copy from the other thread:

> I'm still experimenting with this. Go's CertificateRequest support only knows about pkix.Extension types, which are pretty raw and- as far as I can tell- under-specified for expressing desired key usages in PKCS#10.

I've talked with cfssl upstream about this and found that they ignore requested usage in CSRs (since it's ultimately a CA policy decision). openssl allows you to add requested key usage extensions to CSRs, so it may "only" be a matter of teaching `crypto/x509` how to do that too.

**Comment by smarterclayton** [comment]
As a short term thing here, could we simply auto sign when DNSNames / IPAddresses are specified and the requester is in a specific group (i.e. have a bootstrap group that can autoapprove client cert, and then have a node group that can get auto approved server certs)?

Is the only distinction here between the two halves of bootstrap - one asking for a client cert (with no ips/hostnames) and one asking for a serving cert (asking for ips/hostnames)?

**Comment by mikedanese** [comment]
That's almost what we do now. There is a PR open to add an api for this https://github.com/kubernetes/kubernetes/pull/34488

**Comment by justinsb** [comment]
@gtank I wasn't able to find where you were quoting from.  Can you clarify what is missing from Go's CertificateRequest?

**Comment by pipejakob** [comment]
This seems to have been resolved for a while. Was there more to tackle for this issue, or can we close it?
