### ISSUE TITLE
Kubectl proxy support accessing web services on deployments, daemonsets, services

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#31174]
`kubectl proxy` makes it simple and easy to access a web service hosted on a Pod using the url to the Pod.  We should should provide similar support for controllers and services by picking an arbitrary Pod to connect to.

**Comment by bgrant0607** [comment]
This is an apiserver issue. ResourceLocation would need to be implemented for the appropriate resources. It appears to exist for services.
https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/proxy.go#L111
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/service/proxy.go#L64
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/service/rest.go#L340
