### ISSUE TITLE
Programatic api for kubectl commands (Depends on #7311)

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#31173]
Projects such as helm and dashboard vendor in kubectl.  This is a terrible experience kubectl:
- Only supports go
- Uses stdout for returning results
- Uses flags to configure behavior

A quick and dirty solution would be to.
1. refactor kubectl business logic into libraries: tracked in #7311
2. provide programatic access to the kubectl commands via a grpc service run as a sidecar in a kubernetes Pod

Alternatively we could: Move the client logic into the api server so thick client logic is not required. #12143

Pros: This is a better engineering solution.
Cons: This is much more challenging and time consuming.

I propose we knock out the quick and dirty solution while we work towards the longer term goal of moving logic into the api server.

**Comment by AdoHe** [comment]
This should be something we need to do next, but first I will help with business logic refactor before we start this.

**Comment by smarterclayton** [comment]
How would #2 even work for clients using client certs?  Without tokens and impersonation (even with tokens and impersonation) there are definitely some risks there.  I guess I'm not horribly opposed to it (I like the idea of having an easy API for running GET), but what guarantees would we give for the API?

**Comment by pwittrock** [comment]
@smarterclayton My intention for 2. was to provide a sidecar bound to the loopback for applications running in the k8s cluster.  If I understand correctly, this should only give access to the applications running in the same Pod, is that correct?  I don't think this should be any less secure than running a `kubectl proxy` sidecar.

**Comment by smarterclayton** [comment]
Oh, I was imagining a server endpoint that accepted Kube credentials and
invoked the appropriate kubectl command.  I.e. something web consoles can
drop into easily (which could just be a shell window into a pod with exec).

On Mon, Aug 22, 2016 at 10:12 PM, Phillip Wittrock <notifications@github.com

**Comment by pwittrock** [comment]
@smarterclayton Ah yes, I agree we would have to be more security conscious in that case.  I think https://github.com/rancher/kubectld provides something along those lines.  If we are successful with providing a sidecar we could probably extend (or reuse the majority of the work) to handle usages requiring stricter security.

**Comment by AdoHe** [comment]
I think kubectld give a good example of how to wrap kubectl, but definitely if we could a more elegant way to do this, it would be much convenient for third party tools to use kubectl.

**Comment by pwittrock** [comment]
@AdoHe Yes, the kubectld approach to wrapping kubectl is pretty simple.  This issue could probably even be worked on in parallel by introducing a reasonable abstraction layer for invoking the kubectl logic.  Work on them in whatever order makes the most sense to you.

**Comment by smarterclayton** [comment]
We'd have to version kubectl pretty finely.

On Tue, Aug 23, 2016 at 11:25 AM, Phillip Wittrock <notifications@github.com

**Comment by pwittrock** [comment]
@smarterclayton Could you expand upon your comment?

**Comment by smarterclayton** [comment]
In that changes to kubectl happen pretty often - we try to be backwards
compatible, but it's not perfect, and we don't preserve old behavior in all
cases.  We also sometimes change behavior for new function.  If we exposed
this via GRPC, I wouldn't want to have to continually evolve the GRPC API
based on kubectl - I'd almost expect it to be generated, and potentially be
incompatible from version to version.  If someone wants to lock a version,
they could always lock to a particular kubectl version.
