### ISSUE TITLE
Address open issues from "Azure data disk volume" PR

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#31186]
This issue is to track and follow-up on the unaddressed comments/open issues on PR #29836 "support Azure data disk volume":
- Remove `KeyMutex` since volumemanager/attach detach controller handle concurrency
  - https://github.com/kubernetes/kubernetes/pull/29836#discussion-diff-74159683
- Add comments to public methods.
  - https://github.com/kubernetes/kubernetes/pull/29836/files#r75774475
- Document (in comments) the violation of contract where lun is being returned instead of device path.
- Ensure that Warningf, Errorf, and Infof (with varying verbosity) is used correctly.
  - e.g. https://github.com/kubernetes/kubernetes/pull/29836/files#r74161572, https://github.com/kubernetes/kubernetes/pull/29836/files#r75775075, https://github.com/kubernetes/kubernetes/pull/29836/files#r75775317
- Don't swallow unmount errors
  - https://github.com/kubernetes/kubernetes/pull/29836/files#r75775683

**Comment by rootfs** [comment]
- keyMutex is narrowed, it is only used to obtain empty LUN from Azure service. 
- Public method comments are added
- Warningf now applied when appropriate
- UnmountDevice err is returned.

Left item is about the lun vs devicepath issue, will post a PR.
