### ISSUE TITLE
Federated Ingress Controller needs to unify UID's across Cluster Ingress Controllers

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#31180]
See "UID Assignment" in https://gist.github.com/bprashanth/52648b2a0b6a5b637f843e7efb2abc97

PR in the works.

**Comment by pwittrock** [comment]
@quinton-hoole

I am leaving this in the 1.4 release as a blocking issue.  Please provide daily status updates to this issue or move it out of the release and into v1.4-nonblocking where it will no longer be tracked as a release blocking issue in the burndown meetings.

**Comment by quinton-hoole** [comment]
Yup, the PR for this should merge tomorrow. Today @mwieglus tracked down
and fixed the bug in our fake test framework that has been holding it up.

**Comment by quinton-hoole** [comment]
Closing this tracking bug as the fix #31600 is in the merge queue.
