### ISSUE TITLE
Federated Ingress Needs to Fail Gracefully for non-GCP Clusters

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#31184]
Federated Ingress only currently works across GCE/GKE/GCP clusters with the "GLBC" ingress controller installed.  This needs to be clearly documented, and appropriate error events generated (by the federation control plane) when attempts are made to create Federated Ingresses across other types of clusters.

**Comment by bprashanth** [comment]
on AWS all you need is the nginx ingress controller https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx fronted by a service.type=Loadbalancer. Some modifications are required to get the right ip/hostname to show up in the ingress (nginx controller will publish ip of its node, instead we want to publish ip of the ELB service), but if we put that in, a lot of things become easier cross platform. I'm already writing ingresss conformance tests (https://github.com/kubernetes/kubernetes/pull/31172), and we'd be able to automate things like cert acquisition quite easily using kube-lego. 

Maybe all we need is to teach the nginx ingress controller the concept of "governing service" like we use for PetSet (a Service responsible for the network identity of a group of pods). If the nginx pods are started with --governing-svc=foo, they adopt its public identity. 

@justinsb and I also discussed hooking it up to ALB but it seemed easier/more flexible to go the ELB -> nginx route. Or even the ELB -> traefik route.

**Comment by quinton-hoole** [comment]
Yes, the caveat is that those AWS load balancers are regional, not global.  And I'm not sure how easy it is for multiple ingresses (perhaps in different clusters) to share the same (regional) AWS load balancer.  Perhaps it's possible, I just haven't tried yet. 

Beyond that, there's the "hybrid federation" scenario, where different clusters (and their ingresses and load balancers) exist on different cloud providers.  It's possible to stitch all this together with appropriate aggregation into regional load balancers, with managed geo-DNS over the top of those, but that not done or tested yet in v1.4.  We plan to do that soon though.

**Comment by bprashanth** [comment]
Yeah, not pressing for 1.4. I believe route53 is global even if elb isn't.

**Comment by quinton-hoole** [comment]
Yes Route53 would be the global geo-DNS for AWS.

**Comment by pwittrock** [comment]
@quinton-hoole @bprashanth 

I am leaving this in the 1.4 release as a blocking issue.  Please provide daily status updates to this issue or move it out of the release and into v1.4-nonblocking where it will no longer be tracked as a release blocking issue in the burndown meetings.

**Comment by bprashanth** [comment]
Defer to Quinton, haven't been following the work here too closely. The options we discussed for AWS are not in scope for 1.4 (hence the title).

**Comment by quinton-hoole** [comment]
Yup, the PR for this should merge tomorrow.

**Comment by goltermann** [comment]
Moving to v1.5, this is a non-blocker.

**Comment by quinton-hoole** [comment]
The Federated Ingress controller generates a sensible log message, but this need to be promoted to a Federation Event to be better exposed via the API.  Leaving open until that's done.

**Comment by saad-ali** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @quinton-hoole @kubernetes/sig-cluster-federation

**Comment by quinton-hoole** [comment]
Yes, we can drop it from v1.5.

**Comment by henriquetruta** [comment]
@quinton-hoole what's the status of this issue? Anyone working on it?

**Comment by madhusudancs** [comment]
@henriquetruta you can both disable the API and the controller now. [Federation API server](https://kubernetes.io/docs/admin/federation-apiserver/) now supports ` --runtime-config` which takes a list of APIs you want to enable/disable. [Federation controller manager](https://kubernetes.io/docs/admin/federation-controller-manager/) now supports `--controllers` which takes the list of controllers you want to enable/disable.

**Comment by madhusudancs** [comment]
@nikhiljindal do you think we can close this issue now?

**Comment by quinton-hoole** [comment]
Does it fail gracefully?

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#68.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
