### ISSUE TITLE
Create a Kubernetes performance dashboard

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#3118]
Build/find a dashboard to record performance metrics. The dashboard should have graphs of metrics over time and be queriable.

**Comment by jeremyeder** [comment]
Has there been anything proposed for how to collect system metrics while a test is running?  What is the Google team familiar with and what do they use now?

**Comment by dchen1107** [comment]
#415 too

**Comment by roberthbailey** [comment]
@jeremyeder nothing has been proposed yet and this issue is to collect/present such proposals. 

I think the Google folks may actually be at a disadvantage is presenting proposals for a dashboard since we are generally used to our internal tools that handle this sort of thing for us.

**Comment by timothysc** [comment]
@jeremyeder is there any format that would be easier to consume data?

**Comment by timothysc** [comment]
@quinton-hoole perhaps we can write the proposals against this issue, happy to help on this one.

**Comment by fgrzadkowski** [comment]
@mwielgus

See #6981, which is closely related. I think that we should use Prometheus server for this to be consistent with the current mechanism to expose metrics.

**Comment by jayunit100** [comment]
I'm working on this right now.  the plan is to add a prometheus introspector to examples/ . per conversation with @timothysc

**Comment by mwielgus** [comment]
@jayunit100, what is your plan regarding Prometheus config?

**Comment by jayunit100** [comment]
hi @mwielgus  I'll put a rough PR or description  together and update in this thread.

**Comment by timothysc** [comment]
@mwielgus Tentatively we'll create an examples for prom to spin a Pod as an introspective service.  The whole round-trip integration with Heapster #5637 looks to be TBD still at this time.  

/cc @vishh @vmarmol

**Comment by mwielgus** [comment]
Recently I did some experiments with prometheus on kubernetes being configured in a kindof introspective manner using env variables and command line attributes - you can take a look at a draft here https://github.com/GoogleCloudPlatform/kubernetes/compare/master...mwielgus:prometheus. If it is anyhow in line with your plan I can modify/polish it and submit.

**Comment by jayunit100** [comment]
@mwielgus are you working on this?  I dont want to steal it from you.  

BUT I'm happy to pollish and submit a PR if you want to hand it off !  

Just let me know !  THANKS !

**Comment by mwielgus** [comment]
@jayunit100 It depends whether this draft is in line with your plan and makes any sense at all (I'm very new to Kubernetes). If yes and this will save you some time then sure, I would like submit it.  If not really and/or you need it ASAP then I'm fine with you taking over this.

**Comment by jayunit100** [comment]
okay i see how your doing it - you are using kubernetes-ro as the entrypoint to find the prometheus metrics target exported from api-server.  thats a good idea i didnt realize the kube-ro server worked that way.  im still learning kube internals also :).

two things i think might need to change

- where is your DATABASE_URL  ? I alway set that wehn running.  without it i thought prometheus will not run at all ? 
- its not HA - if this pod fails, then you lose all data when you relaunch on a new minion.  

Let me know thoughts on those to

**Comment by mwielgus** [comment]
Database url/HA - I use local storage (see https://github.com/GoogleCloudPlatform/kubernetes/compare/master...mwielgus:prometheus#diff-6fb454b575d1bd04454e4ff4e3048b32R95) which I guess can be placed on GCE persistent disk. But if your preference is to write to InfluxDB then i can modify it accordingly.

**Comment by jayunit100** [comment]
@mwielgus how about this 
Either : 
- I can adopt your patch, add some commits on top, and then we can just submit it as a joint PR by layering the commits ? That way you get credit for your hard work ?
OR :  
- You can finish this patch off.

We really need this so I'm happy to take over if you're busy with other tasks.

**Comment by mwielgus** [comment]
@jayunit100 let's go with the first option.

**Comment by jayunit100** [comment]
okay ! TL;DR summary for this guy... 
- we'll add prometheus RC to add-ons which uses kubernetes-ro endpoint
- it will be based on mwieigus initial patch above
- i'll layer prom dash into it as well, so that the whole thing is spun up on the fly

**Comment by timothysc** [comment]
:+1:

**Comment by jayunit100** [comment]
- mwielgus@google.com <-- is that your email @mwielgus  
- This is now very very heavily redundant to #6981.  should we consolidate ?

**Comment by mwielgus** [comment]
* Yes.
* Sure.

**Comment by jayunit100** [comment]
@mwielgus  okay, about to put in the PR, tested a few times and refined a few minor things.... I have one question - why did you use a `volumeMount` ? It seems unnecessary unless you're planning on having other containers in the pod?

**Comment by jayunit100** [comment]
okay, heres the PR ! #7878

**Comment by timothysc** [comment]
awesome work guys!

**Comment by davidopp** [comment]
@bprashanth was interested in this possibly as a way to store the results from his micro-benchmarks

**Comment by borg286** [comment]
I apologize if this isn't the right place to comment on the above PR but I'm new to github.
On line 35 of your run-prometheus.sh script, why not have the user simply pass in the targets in the form of hostname1:port1,hostname2:port2,hostname3:port3.... instead of requiring the user to define a slew of environment variables?
This would greatly simplify and clarify the description on line 28.
Would it be clearer to have on line 21 instead of KUBERNETES_RO to be instead localhost:9090 ? And make a comment that this configures prometheus to monitor itself.
