### ISSUE TITLE
gubernator ui runs out of memory

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#31181]
seeing quite a bit of

```
Exceeded soft private memory limit of 128 MB with 202 MB after servicing 0 requests total
```

when I try to search through logs using the filter ui (i.e https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/8716/nodelog?junit=junit_09.xml&wrap=on).

**Comment by bgrant0607** [comment]
Gubernator is in test-infra repo. cc @rmmh
