### ISSUE TITLE
Deprecate NamespaceAutoprovision, NamespaceExists admission controls

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#31195]
As per https://github.com/kubernetes/kubernetes/pull/31139#issuecomment-241582497, NamespaceLifecycle admission control is enough. We can deprecate the other 2 namespace admission controls.

**Comment by nikhiljindal** [comment]
cc @derekwaynecarr.  

Anyone else I should cc?

**Comment by derekwaynecarr** [comment]
They were already marked deprecated for multiple releases.

Have sent a PR to remove them from code base here:
https://github.com/kubernetes/kubernetes/pull/31250

**Comment by wizpresso-steve-cy-fan** [comment]
Reopen this as we want to specifically have NamespaceAutoProvision but also check whether that namespace is in termination, i.e reject namespace creation if the target namespace is terminating, otherwise allow auto provision.
