### ISSUE TITLE
Error message not helpful.

### ISSUE THREAD

**Issue by edpin** [kubernetes/kubernetes#31196]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

I searched for the words "Tim Hockin" on my chat roster. :-)

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE.

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.5", GitCommit:"25eb53b54e08877d3789455964b3e97bdd3f3bce", GitTreeState:"clean"}

**Environment**:
- **Cloud provider or hardware configuration**: GCE/GKE
- **OS** (e.g. from /etc/os-release): VERSION="14.04.5 LTS, Trusty Tahr"
- **Kernel** (e.g. `uname -a`): Linux edpin-linux.mtv.corp.google.com 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:

I tried to attach a PD in the wrong zone. I had pods in us-central1-c but this operator copy-and-pasted some examples around and created the PD in us-central1-a.

Then the pod would not tell me why it was in ContainerCreating for long minutes. kubectl logs <pod> didn't show anything useful and kubectl describe pod showed me this unhelpful message:

Events:
  FirstSeen LastSeen    Count   From                            SubobjectPath   Type        Reason      Message

---

  6m        6m      1   {default-scheduler }                            Normal      Scheduled   Successfully assigned dirserver-3381994805-8cfe6 to gke-cluster-1-default-pool-bb87ddba-hogl
  5m        23s     6   {kubelet gke-cluster-1-default-pool-bb87ddba-hogl}          Warning     FailedMount Unable to mount volumes for pod "dirserver-3381994805-8cfe6_default(fe8e0537-68c1-11e6-8f90-42010af00083)": Could not attach GCE PD "dirserver-logs". Timeout waiting for mount paths to be created.
  5m        23s     6   {kubelet gke-cluster-1-default-pool-bb87ddba-hogl}          Warning     FailedSync  Error syncing pod, skipping: Could not attach GCE PD "dirserver-logs". Timeout waiting for mount paths to be created.

**What you expected to happen**:

A message such as:
"Can't connect to PD in a different zone: requested PD in "zones/us-central1-a", pod is running in "zones/us-central1-c".

or somesuch.

**How to reproduce it** (as minimally and precisely as possible):

gcloud compute disks create --size=100GB some-name --zone=us-central1-a

Then configure your yaml job to run on us-central1-c.

**Anything else do we need to know**:

**Comment by jingxu97** [comment]
@edpin Thank you for reporting your issue. I will try to initiate some discussion about this problem.
