### ISSUE TITLE
[k8s.io] Kubectl client [k8s.io] Kubectl apply should apply a new configuration to an existing RC 0.47s

### ISSUE THREAD

**Issue by lixiaobing10051267** [kubernetes/kubernetes#31199]
PR #30434 GCE e2e build/test failed ：

Test Failures

[k8s.io] Kubectl client [k8s.io] Kubectl apply should apply a new configuration to an existing RC 0.47s
go run hack/e2e.go -v -test --test_args='--ginkgo.focus=Kubectl\sclient\s\[k8s\.io\]\sKubectl\sapply\sshould\sapply\sa\snew\sconfiguration\sto\san\sexisting\sRC$'
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:129
Aug 22 15:26:49.432: Couldn't delete ns "e2e-tests-kubectl-1zfcq": Operation cannot be fulfilled on namespaces "e2e-tests-kubectl-1zfcq": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:270

...

**Comment by janetkuo** [comment]
dup #32057
