### ISSUE TITLE
Automatically stage and render docs PRs (using jekyll)

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#31198]
Placeholder for kubernetes/kubernetes.github.io#1060

**Comment by foxish** [comment]
Old issue: https://github.com/kubernetes/kubernetes.github.io/issues/1060

**Comment by foxish** [comment]
Closing because we now have netlify staging docs PRs automatically. https://github.com/kubernetes/kubernetes.github.io/pull/1180
