### ISSUE TITLE
Eviction doesn't work due to lack of ranking function

### ISSUE THREAD

**Issue by ronnielai** [kubernetes/kubernetes#31192]
I use "-eviction-hard imagefs.available<10%,nodefs.available<10%" on a node where there's no separate imagefs. The eviction failed due to:

W0822 23:51:03.731889    2684 eviction_manager.go:211] eviction manager: attempting to reclaim imagefs
I0822 23:51:03.731930    2684 eviction_manager.go:225] eviction manager: must evict pod(s) to reclaim imagefs
E0822 23:51:03.731938    2684 eviction_manager.go:230] eviction manager: no ranking function for resource imagefs

Should eviction be supported in this case too?

**Comment by ronnielai** [comment]
Maybe in in getStarvedResources() imagefs should be ignored imagefs if there's no dedicated image filesystem.

**Comment by derekwaynecarr** [comment]
I will lay out some pro/cons with this.

I see following options:

1. ignore imagefs if there is no imagefs (falling back to rootfs seems wrong if values differ)
2. error kubelet on launch

**Comment by derekwaynecarr** [comment]
Per our discussion, I think the eviction manager should not make an observation for imagefs if there is no imagefs.

**Comment by derekwaynecarr** [comment]
I thought about this more and decided that in the case of no dedicated imagefs, the ranking and reclaim functions for imagefs based thresholds would match those as nodefs thresholds so we match the current summary API behavior.
