### ISSUE TITLE
Decide how to archive performance data

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#3119]
For the performance dashboard (#3118) we will need an archive of performance metrics over time. Determine what format they should be stored in (http://testanything.org/ protocol?) and what the storage system should be.

**Comment by wojtek-t** [comment]
@gmarek is working roughly on it

**Comment by gmarek** [comment]
Current plan is to embed them into scalability test runs, in the same way we do with API call latencies and e2e pod startup times.

**Comment by wojtek-t** [comment]
After pushing those data here and there, we decided to store them in separate dedicated files in json format. As long as this is not ideal, but finally we have a unified method for doing this and that serves our purpose (e.g. dashboard can easily use this data).
I'm marking as fixed - we ca revisit it at some point, but that doesn't seem to be needed.
