### ISSUE TITLE
Reach out to other open source GH projects with likely similar PR workflow needs

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#31205]
We should figure out what TensorFlow and GRpc are doing around PR workflow.  They may have similar needs such as - OWNERS, nagging, etc

**Comment by justinsb** [comment]
Also other projects that may be more our scale (or likely scale if we consider the whole ecosystem of things we currently think of as non-core) - Chromium, Golang or Android.

**Comment by pwittrock** [comment]
@justinsb Good suggestions
