### ISSUE TITLE
Measure time to build Kubernetes from source

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#3120]
Configure and automated hourly build and record the time it takes to build Kubernetes from source. Export information into the performance dashboard (#3118).

**Comment by jeremyeder** [comment]
Is this CI going run in a shared or dedicated environment?

**Comment by zmerlynn** [comment]
We've got "official" CI builds running inside Google. As of yesterday, the
builds are getting exported to a GCS bucket at gs://kubernetes-release/ci/
(eventually, we'll figured out a way to make the Jenkins server more
public).

You can now grab the latest with something like `gsutil cp
gs://kubernetes-release/ci/$(gsutil cat
gs://kubernetes-release/ci/latest.txt)/kubernetes.tar.gz .`

This build is blocked on two things: Jenkins doesn't bother exporting the
actual time for the "make release" step (which would be trivial), nor do we
have a place to put it yet.

**Comment by fejta** [comment]
Thanks for reopening!

Multiple quarters elapsed without anyone making progress. I closed this class of bug because I want to bring attention to any that are still interesting to fix.

I removed the test-infra tag because it is about adding test coverage.

**Comment by a-robinson** [comment]
@fejta - when you remove test-infra from issues, could you please switch it out for a more appropriate label rather than leaving the issues lingering in the ether?

**Comment by fejta** [comment]
IMO we already have the data: https://k8s-testgrid.appspot.com/google-unit#build&width=20&graph-metrics=test-duration-minutes

**Comment by spiffxp** [comment]
@kubernetes/sig-testing-misc 
/remove area/test-infra
/assign

I agree we've got the data
