### ISSUE TITLE
Setup some sort of multi-repo hosted Kanban / Scrum board for managing tasks

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#31207]
GitHub issues alone are not a good solution for managing project priorities.  You can't stack rank items nor can you effectively group them.  You also can't visualize progress.  We need something better.

Maybe
https://github.com/wekan/wekan
https://waffle.io/

Use helm if possible and make it easy to install

**Comment by aronchick** [comment]
check out zenhub

**Comment by ixdy** [comment]
https://help.github.com/articles/tracking-the-progress-of-your-work-with-projects/

**Comment by foxish** [comment]
We now have https://github.com/kubernetes/kubernetes/projects. Could probably close this? @pwittrock
