### ISSUE TITLE
Make it so websites can have a button to "Deploy to Kubernetes"

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#31208]
This page has a bunch of buttons at the bottom where you can deploy to OSS project to a hosted provider.  Would be cool if we could support this too https://github.com/wekan/wekan

**Comment by nebril** [comment]
Isn't this something that someone who provides Kubernetes cluster as a service should be responsible for? It seems like a nice idea, I just think it doesn't belong to Kubernetes project itself.

**Comment by fuel-wlightning** [comment]
I disagree with @nebril . This should not be provider specific, as it means each and every github project has to implement it separately for every service.

That being said, I'm not sure how this fits in with the core. So I agree it might not be a kubernetes native thing, maybe helm?
