### ISSUE TITLE
Expose single annotations via environment downward API

### ISSUE THREAD

**Issue by nhlfr** [kubernetes/kubernetes#31218]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
feature request

Follow up to the discussion on PR #30860.

We would like to see a feature of exposing any single annotation via environment downward API. The fieldRef used for that will contain a JSONPath selector and look like `metadata.annotation['key']`.

We need to:
- validate this fieldRef properly - allow to put any string in key and escape `\`, `'`, `[`, `]` characters
- reject keys in containing these chars without escaping

@kubernetes/sig-api-machinery @smarterclayton

**Comment by smarterclayton** [comment]
@pmorie

**Comment by kargakis** [comment]
/sig api-machinery
/sig node

Not sure which sig owns the downward api
