### ISSUE TITLE
gke-large suite is failing due to non-starting fluentd containers

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#31215]
The last 2 runs of gke-large suite (2000-node GKE cluster):
http://kubekins.dls.corp.google.com:8080/view/Scalability/job/kubernetes-e2e-gke-large-cluster/81/
http://kubekins.dls.corp.google.com:8080/view/Scalability/job/kubernetes-e2e-gke-large-cluster/82/

failed due to not being able to start one of fluentd pods within 2 hours.

In both cases, looking into kubelet logs I see such errors:
```
  260 I0822 08:10:21.937932    3570 docker_manager.go:1851] Need to restart pod infra container for "fluentd-cloud-logging-gke-gke-large-cluster-default-pool-0-84225561-de80_kube-system(c935e      d2537b8504686441939d592acdc)" because it is not found
  261 E0822 08:10:21.954137    3570 kubelet.go:1247] hostname for pod:"fluentd-cloud-logging-gke-gke-large-cluster-default-pool-0-84225561-de80" was longer than 63. Truncated hostname to :"fl      uentd-cloud-logging-gke-gke-large-cluster-default-pool-0-8422"
  262 E0822 08:10:22.225145    3570 docker_manager.go:2077] Failed to setup network for pod "fluentd-cloud-logging-gke-gke-large-cluster-default-pool-0-84225561-de80_kube-system(c935ed2537b85      04686441939d592acdc)" using network plugins "kubenet": Error adding container to network: failed to find plugin "loopback" in path [/opt/cni/bin /usr/libexec/kubernetes/kubelet-plugins/      net/exec/]; Skipping pod
  263 I0822 08:10:22.228315    3570 docker_manager.go:1442] Killing container "ba47870b61987e2781c8aff31f599b2c971895070a336530429210b871e0ea30 kube-system/fluentd-cloud-logging-gke-gke-large      -cluster-default-pool-0-84225561-de80" with 30 second grace period
```

Those logs repeat every few seconds in the logs.
I guess, the one that is causing problem is this one:
```
using network plugins "kubenet": Error adding container to network: failed to find plugin "loopback" in path [/opt/cni/bin /usr/libexec/kubernetes/kubelet-plugins/      net/exec/];
```

@yujuhong @Random-Liu @dchen1107 - is this a known issue? Can we workaround it somehow in our tests?
@kubernetes/goog-node 

@zmerlynn @gmarek

**Comment by yujuhong** [comment]
The latest build 83 is green again. Could it be an incomplete cluster setup caused by temporary network issues? Just throwing out some ideas.

**Comment by wojtek-t** [comment]
>
The latest build 83 is green again. 

Yes - those are flakes - not something completely broken.

>
Could it be an incomplete cluster setup caused by temporary network issues? Just throwing out some ideas.

The cluster itself was healthy. But it's possible that something was broken with this particular node (1999/2000 seemed to work fine in both cases).
However, if it was the case, we should detect it and mark the node as unhealthy in my opinion.

**Comment by yujuhong** [comment]
> The cluster itself was healthy.

Hm..yes, but some files were not copied properly to the node by salt.

> However, if it was the case, we should detect it and mark the node as unhealthy in my opinion.

Not disagreeing with that, but kubelet has no knowledge of how the cluster should be set up. I think the cluster setup script/tool should detect such cases and declare failure.

**Comment by wojtek-t** [comment]
>
Not disagreeing with that, but kubelet has no knowledge of how the cluster should be set up. I think the cluster setup script/tool should detect such cases and declare failure.

Sure - that would be good enough. The problem is that personally I don't know what wasn't copied/installed/what happened in order to make this happen. So if anyone can debug it, it would be great.

**Comment by wojtek-t** [comment]
The same happened here:
http://kubekins.dls.corp.google.com/view/Scalability/job/kubernetes-e2e-gke-large-cluster/87/consoleFull

Anythin we can do to detect it?

**Comment by yujuhong** [comment]
A good starting point would be to collect `/var/log/startupscript.log` and see why this is failing.

**Comment by yujuhong** [comment]
Not sure I'm the best person to debug this.

**Comment by dchen1107** [comment]
cc/ @freehan Could you please diagnose the initial cause reported by @wojtek-t related kubenet?

**Comment by freehan** [comment]
This looks like a cluster setup problem. Very likely it failed to download cni tarball.
```
  262 E0822 08:10:22.225145    3570 docker_manager.go:2077] Failed to setup network for pod "fluentd-cloud-logging-gke-gke-large-cluster-default-pool-0-84225561-de80_kube-system(c935ed2537b85      04686441939d592acdc)" using network plugins "kubenet": Error adding container to network: failed to find plugin "loopback" in path [/opt/cni/bin /usr/libexec/kubernetes/kubelet-plugins/      net/exec/]; Skipping pod
```

**Comment by dchen1107** [comment]
Yes, I vaguely remembered that we run into this kind of issue before, and startupscript.log could really help here.

**Comment by wojtek-t** [comment]
@dchen1107 - you mean "startupscript.log" from that particular node, right?

If so, I looked into logs and it seems that don't have those logs collected from gke runs. In particular these are logs coming from problematic (both kubelet, kubeproxy, kernel, etc.) mentioned in the first post in this bug:

81: https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-large-cluster/81/artifacts/gke-gke-large-cluster-default-pool-0-84225561-de80/?project=kubernetes-jenkins

82: https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-large-cluster/82/artifacts/gke-gke-large-cluster-default-pool-1-2a6a5199-e6gm/?project=kubernetes-jenkins

BTW - do we have startupscript.log on GKE nodes (if so it's strange that we don't copy it on gke, and copy it on gce...)

**Comment by yujuhong** [comment]
> BTW - do we have startupscript.log on GKE nodes (if so it's strange that we don't copy it on gke, and copy it on gce...)

Yes, they should have `/var/log/startupscript.log`. I don't know why jenkins don't collect them for gke nodes...

**Comment by wojtek-t** [comment]
@yujuhong @dchen1107 @freehan 
So I think that we have more data now. Basically the same happened here:
http://kubekins.dls.corp.google.com:8080/view/Scalability/job/kubernetes-e2e-gce-enormous-cluster/137/

The problematic node was:
```
e2e-enormous-cluster-minion-group-v6r6
```

Logs from that node are here:
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-enormous-cluster/137/artifacts/e2e-enormous-cluster-minion-group-v6r6/?project=kubernetes-jenkins

Looking into kubelet logs I again see a bunch of logs like:
```
E0902 06:55:49.264907    3723 docker_manager.go:2127] Failed to setup network for pod "fluentd-elasticsearch-e2e-enormous-cluster-minion-group-v6r6_kube-system(befba121e25c310938143db137     604e03)" using network plugins "kubenet": Error adding container to network: failed to find plugin "loopback" in path [/opt/cni/bin /usr/libexec/kubernetes/kubelet-plugins/net/exec/]; Skipping pod
```

Startup script logs are in GCS under the link I pasted above. Personally I don't see anything unusual there, but maybe I don't know what to look at.
@freehan @dchen1107 - would you be able to take a look into it?

**Comment by yujuhong** [comment]
Nothing too shocking. The log just confirmed that the node weren't able to download the cni plugins during startup.

```
Sep  2 06:54:35 e2e-enormous-cluster-minion-group-v6r6 startupscript: [INFO    ] Running state [/opt/cni] at time 06:54:35.152196
Sep  2 06:54:35 e2e-enormous-cluster-minion-group-v6r6 startupscript: [INFO    ] Executing state file.directory for /opt/cni
Sep  2 06:54:35 e2e-enormous-cluster-minion-group-v6r6 startupscript: [INFO    ] {'/opt/cni': 'New Dir'}
Sep  2 06:54:35 e2e-enormous-cluster-minion-group-v6r6 startupscript: [INFO    ] Completed state [/opt/cni] at time 06:54:35.158997
Sep  2 06:54:35 e2e-enormous-cluster-minion-group-v6r6 startupscript: [INFO    ] Running state [/etc/cni/net.d] at time 06:54:35.159445
Sep  2 06:54:35 e2e-enormous-cluster-minion-group-v6r6 startupscript: [INFO    ] Executing state file.directory for /etc/cni/net.d
Sep  2 06:54:35 e2e-enormous-cluster-minion-group-v6r6 startupscript: [INFO    ] {'/etc/cni/net.d': 'New Dir'}
Sep  2 06:54:35 e2e-enormous-cluster-minion-group-v6r6 startupscript: [INFO    ] Completed state [/etc/cni/net.d] at time 06:54:35.166056
Sep  2 06:54:35 e2e-enormous-cluster-minion-group-v6r6 startupscript: [INFO    ] Running state [/opt/cni] at time 06:54:35.166539
Sep  2 06:54:35 e2e-enormous-cluster-minion-group-v6r6 startupscript: [INFO    ] Executing state archive.extracted for /opt/cni
Sep  2 06:54:40 e2e-enormous-cluster-minion-group-v6r6 startupscript: [INFO    ] Loading fresh modules for state activity
Sep  2 06:54:40 e2e-enormous-cluster-minion-group-v6r6 startupscript: [INFO    ] Running state [/var/cache/salt/minion/_opt_cni_bin.tar] at time 06:54:40.673273
Sep  2 06:54:40 e2e-enormous-cluster-minion-group-v6r6 startupscript: [INFO    ] Executing state file.managed for /var/cache/salt/minion/_opt_cni_bin.tar
Sep  2 06:54:50 e2e-enormous-cluster-minion-group-v6r6 startupscript: [ERROR   ] Unable to manage file: Error reading https://storage.googleapis.com/kubernetes-release/network-plugins/cni-9d5e6e60e79491207834ae8439e80c943db65a69.tar.gz: [Errno 101] Network is unreachable
Sep  2 06:54:50 e2e-enormous-cluster-minion-group-v6r6 startupscript: [INFO    ] Completed state [/var/cache/salt/minion/_opt_cni_bin.tar] at time 06:54:50.811530
Sep  2 06:54:50 e2e-enormous-cluster-minion-group-v6r6 startupscript: [ERROR   ] Unable to manage file: Error reading https://storage.googleapis.com/kubernetes-release/network-plugins/cni-9d5e6e60e79491207834ae8439e80c943db65a69.tar.gz: [Errno 101] Network is unreachable
Sep  2 06:54:50 e2e-enormous-cluster-minion-group-v6r6 startupscript: [INFO    ] Completed state [/opt/cni] at time 06:54:50.812375
```

@freehan's PR #31931 will ensure that kubelet marks the node not ready if the plugins are missing. For other setup problems that kubelet cannot detect (e.g., missing a static pod manifest file), the cluster setup process should have other sanity checks.

**Comment by wojtek-t** [comment]
@yujuhong - thanks a lot for looking into it.

**Comment by wojtek-t** [comment]
OK - so the new node condition is already working - we faced that in:

The current issue is that this is basically breaking all the tests, because in the cluster validation phase we allow for small percentage of tests to fail provisioning, but then in tests we require all of them to be healthy.

I will send out a PR that will allow the for some nodes to be not ready also in the test framework (it will be configured, and by default set to 0 in all suites - we will only overwrite it in large clusters).

**Comment by wojtek-t** [comment]
I'm closing this bug, as this is error is supposed to be handled now.
I will reopen if we face this issue again.

**Comment by wojtek-t** [comment]
Reopening - http://kubekins.dls.corp.google.com:8080/view/Scalability/job/kubernetes-e2e-gke-large-cluster/100/ showed that I didn't fully fix it.

#32358 should hopefully finally fix it.
