### ISSUE TITLE
git commit err: Error in /hack/lib/etcd.sh:35

### ISSUE THREAD

**Issue by lixiaobing10051267** [kubernetes/kubernetes#31232]
update etcd to 3.0.6, err still exists:

Checking for swagger spec that need updating... !!! Error in /home/zte/share/k8s-clone2/src/k8s.io/kubernetes/hack/lib/etcd.sh:35
  'version=$(etcd --version | head -n 1 | cut -d " " -f 3)' exited with status 141
Call stack:
  1: /home/zte/share/k8s-clone2/src/k8s.io/kubernetes/hack/lib/etcd.sh:35 kube::etcd::start(...)
  2: /home/zte/share/k8s-clone2/src/k8s.io/kubernetes/hack/update-swagger-spec.sh:59 main(...)
Exiting with status 1
!!! Error in hack/verify-swagger-spec.sh:38
  '"${KUBE_ROOT}/hack/update-swagger-spec.sh"' exited with status 1
Call stack:
  1: hack/verify-swagger-spec.sh:38 main(...)
Exiting with status 1
ERROR!
Swagger spec needs to be updated.
To regenerate the spec, run:
  hack/update-swagger-spec.sh

Aborting commit

**Comment by dims** [comment]
@lixiaobing10051267 - Can you run `etcd --version` and `etcd --version | head -n 1 | cut -d " " -f 3` by hand and see what the output is?

**Comment by lixiaobing10051267** [comment]
@dims ok:

    # etcd --version
    etcd Version: 3.0.6
    Git SHA: 9efa00d
    Go Version: go1.6.3
    Go OS/Arch: linux/amd64

    # etcd --version | head -n 1 | cut -d " " -f 3
    3.0.6

**Comment by dims** [comment]
weird, how about `version=$(etcd --version | head -n 1 | cut -d " " -f 3)'` followed by `echo $version` ? We need to figure out why you are seeing the 141 error code (from googling it seems to be from a pipe problem)

**Comment by lixiaobing10051267** [comment]
root@ubuntu:/home/zte/share/docker-clone/docker/docs/admin# version=$(etcd --version | head -n 1 | cut -d " " -f 3)
root@ubuntu:/home/zte/share/docker-clone/docker/docs/admin# echo $version
3.0.6

**Comment by lixiaobing10051267** [comment]
root@ubuntu:/home/zte/share# version=$(etcd --version | head -n 1 | cut -d " " -f 3)
root@ubuntu:/home/zte/share# echo $version
3.0.6

**Comment by dims** [comment]
I am out of ideas :)

**Comment by lixiaobing10051267** [comment]
thx very much:)

**Comment by jellonek** [comment]
Looks like mess in `$PATH` in time of line 35 execution in `hack/lib/etcd.sh`.
Could you add before this line:
```
echo $PATH
which etcd
which head
which cut
```
and provide output generated by `git commit` again?

**Comment by jellonek** [comment]
ping?

**Comment by lixiaobing10051267** [comment]
@dims @jellonek I tried again, the result is:

    root@ubuntu:/home/zte/share# version=$(etcd --version | head -n 1 | cut -d " " -f 3)
    root@ubuntu:/home/zte/share# $version
    3.0.6: command not found

**Comment by lixiaobing10051267** [comment]
@jellonek I add the following to time of line 35 execution in hack/lib/etcd.sh

echo $PATH
which etcd
which head
which cut

the result is:

root@ubuntu:/home/zte/share/k8s-clone2/src/k8s.io/kubernetes/hack/lib# git commit
Checking that it builds... OK

Checking for files that need gofmt... OK

Checking for files that need boilerplate... OK

Checking for problems with flag names... OK

Checking for API descriptions... OK

Checking for docs that need updating... OK

Checking for swagger type documentation that need updating... OK

Checking for swagger spec that need updating... !!! [0830 16:35:34] Timed out waiting for etcd:  to answer at http://127.0.0.1:4001/v2/machines; tried 80 waiting 0.25 between each
!!! Error in /home/zte/share/k8s-clone2/src/k8s.io/kubernetes/hack/lib/etcd.sh:42
  'return 1' exited with status 1
Call stack:
  1: /home/zte/share/k8s-clone2/src/k8s.io/kubernetes/hack/lib/etcd.sh:42 kube::etcd::start(...)
  2: /home/zte/share/k8s-clone2/src/k8s.io/kubernetes/hack/update-swagger-spec.sh:60 main(...)
Exiting with status 1
!!! Error in hack/verify-swagger-spec.sh:38
  '"${KUBE_ROOT}/hack/update-swagger-spec.sh"' exited with status 1
Call stack:
  1: hack/verify-swagger-spec.sh:38 main(...)
Exiting with status 1
ERROR!
Swagger spec needs to be updated.
To regenerate the spec, run:
  hack/update-swagger-spec.sh

Aborting commit

**Comment by lixiaobing10051267** [comment]
run hack/update-swagger-spec.sh:

root@ubuntu:/home/zte/share/k8s-clone2/src/k8s.io/kubernetes# hack/update-swagger-spec.sh
Note: This assumes that the 'types_swagger_doc_generated.go' file has been
updated for all API group versions. If you are unsure, please run
hack/update-generated-swagger-docs.sh first.
Go version: go version go1.6.3 linux/amd64
+++ [0830 17:40:28] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0830 17:40:28] Building go targets for linux/amd64:
    cmd/kube-apiserver
+++ [0830 17:40:30] Placing binaries
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/root/go-tools/bin:/home/zte/share/k8s-clone2/bin
/usr/local/bin/etcd
/usr/bin/head
/usr/bin/cut
etcd -addr 127.0.0.1:4001 -data-dir /tmp/tmp.Iqxru51yCj --bind-addr 127.0.0.1:4001 --debug > "/dev/null" 2>/dev/null
Waiting for etcd to come up.
!!! [0830 17:40:52] Timed out waiting for etcd:  to answer at http://127.0.0.1:4001/v2/machines; tried 80 waiting 0.25 between each
!!! Error in /home/zte/share/k8s-clone2/src/k8s.io/kubernetes/hack/lib/etcd.sh:42
  'return 1' exited with status 1
Call stack:
  1: /home/zte/share/k8s-clone2/src/k8s.io/kubernetes/hack/lib/etcd.sh:42 kube::etcd::start(...)
  2: hack/update-swagger-spec.sh:60 main(...)
Exiting with status 1
+++ [0830 17:40:52] Clean up complete

**Comment by xiangfeiz** [comment]
Just met the same issue with etcd version 3.0.15

**Comment by henrynash** [comment]
I think I managed to work out what is wrong here: See: hack/etcd script can fail with pipe error 141 in some circumstances #38109

**Comment by lixiaobing10051267** [comment]
yes, that's right, the problem has dispeared, you are so great!
