### ISSUE TITLE
Measure the time for each Go test in the e2e test suite individually rather than in aggregate

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#3123]
Will give us better granularity for common use cases. Also see #3121.

**Comment by roberthbailey** [comment]
With Ginkgo and the JUnit output we are now getting timing for individual specs. What remains to be done is to track the test durations over time to look for trends that point to performance degradations.

**Comment by zmerlynn** [comment]
It's actually really messy to use any of the coarse grained test timing for perf for some tests unless you also record the order of the tests in the process and only graph based on the same relative docker pull order. The specs are currently randomized, so the first test that hits a particular image pays a pretty heavy cost. It would be much better if we recorded the time between various actions within an e2e test as well, but even then, you'd have a lot of issues given the randomized environment that e2e is forcing.
