### ISSUE TITLE
We should be able to `go test` our e2e tests

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#31256]
It is too hard to run e2e tests right now.  It should be easy to fire up a test cluster, check out the k8s code and say "go test`.

**Comment by justinsb** [comment]
The process as it stands now:

* try running e.g. ` go run hack/e2e.go -v -test --test_args="--ginkgo.focus=schedule.it.on.another.host"`
* discover the env vars that need to be set
* doesn't work on an existing cluster if not set up with kube-up
* hack script to print command output, discover that it is a wrapper around running the ginkgo executable with the e2e.test executable
* figure out args and extra env vars (they aren't too bad)
* tweak tests
* e2e.test is compiled so need to run make at every change (`make e2e.test` and variants don't work)

We've invested a lot into the e2e tests, but we need to take the final steps so that the barrier to entry is lower.

**Comment by bizhao** [comment]
Agreed.
I'm new to K8s and still struggling to run end2end against an existing cluster.
