### ISSUE TITLE
Define process for onboarding new kubectl contributors

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#31258]
Started here:
https://github.com/kubernetes/community/wiki/WIP:-Contributor-Guide:-kubectl-new-contributor-onboarding-guide

Define the process for onboarding new contributors:
- How should new contributors find issues to work on?
- How should issues be claimed?
- Integrate claiming with bot
- What should the shadow review process be like
- How to get help when blocked
- Better in-code documentation for kubectl design and layout
- Refactor kubectl to be more clear and understandable

cc @AdoHe @ymqytw

**Comment by imcsk8** [comment]
This is precisely what i need!! i want to start helping with kubernetes development, is it ok to start doing only code review before creating patches?

**Comment by AdoHe** [comment]
👍

**Comment by asalkeld** [comment]
Also see this old PR (I'll rebase to use a label)
