### ISSUE TITLE
Measure high QPS performance of Kubernetes

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#3125]
Curate a small number of “applications” that can be used to measure performance at a higher level (QPS for high level requests).

**Comment by jeremyeder** [comment]
We created some "hello world" type container-pairs using Dockerfiles for app-stacks that are common for our customers. The hello world pages take an argument/switch that optionally runs a db query. i.e. http://host/index.php?DB=true. Then we blow out N-number of these container pairs that use Docker links. DB=true runs an un-cacheable query to model worst case performance scenario. Then we fire http workload generators at it.

**Comment by smarterclayton** [comment]
I think sig-scalability has already taken steps towards this, correct?

**Comment by timothysc** [comment]
I don't this specific issue applies any more we have so many varied tests and change and monitor qps limits... closing.
