### ISSUE TITLE
Improve kubectl error messages

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#31267]
List here:
https://github.com/kubernetes/community/wiki/Roadmap:-kubectl

Cross them out as you complete them

---
## List of additional issues
- [ ] #34457  exec pods on master unsupported
- [ ] #30081 --dry-run + -i unsupported

**Comment by k82cn** [comment]
@pwittrock , I'd like to contribute this as a start point. Would you help to provide the guidance ?

**Comment by pwittrock** [comment]
@k8scn Sure.  Have you read this doc yet?

https://github.com/kubernetes/community/wiki/WIP:-Contributor-Guide:-kubectl-new-contributor-onboarding-guide

@AdoHe Would you be able to help @k82cn get started contributing?

**Comment by pwittrock** [comment]
@k82cn You can reach either @AdoHe or @pwittrock in the kubernetes slack by mentioning us

**Comment by AdoHe** [comment]
@pwittrock sure.
@k82cn my kubernetes slack id is adohe, ping me when you online.

**Comment by k82cn** [comment]
@pwittrock / @AdoHe , sync up with AdoHe on slack, I'll start from #15834 :).

BTW, you can assign this one to me, i'm a k8s member now :). I'll try my best to clear the issue in the list.

**Comment by AdoHe** [comment]
@k82cn you did own this issue now, please go ahead, and comment here if you have any questions.

**Comment by k82cn** [comment]
sure, I'm working on it :).

**Comment by dgonzalez** [comment]
Hello. Is anyone working on this issue? Could I take it? I want to get into Kubernetes source slowly slowly and looks like a good place to start.

**Comment by AdoHe** [comment]
@dgonzalez that would be great. @k82cn are you working on this now? If not we can have dgonzalez pick up this.

**Comment by k82cn** [comment]
@AdoHe , it's OK to let @dgonzalez pick up.
I think this's a set of issues to improve the error message (refer to the list in the description). I'm working on  #15834 which is one issue in the list, maybe @dgonzalez can also pick up one issue in the list :).

**Comment by AdoHe** [comment]
@dgonzalez could you help with this one?

**Comment by k82cn** [comment]
@AdoHe , I think we can let @dgonzalez pick up one issue in https://github.com/kubernetes/community/wiki/Roadmap:-kubectl . When all issue in the list merged, we can close this one directly :).

**Comment by AdoHe** [comment]
SGTM.

**Comment by dgonzalez** [comment]
Yep. I can take it.

**Comment by AdoHe** [comment]
Ping me if any problem. Thanks

**Comment by dgonzalez** [comment]
Will do. Thanks.

**Comment by dgonzalez** [comment]
@dgonzalez #dibs on this issue

**Comment by pwittrock** [comment]
@dgonzalez Cool.  Let me know how it goes

**Comment by dgonzalez** [comment]
I am working on it. I will need some feedback in the PR as I am not 100% clear on the big picture. Expect the PR this weekend.

**Comment by pwittrock** [comment]
Ping this thread with the PRs when you create them

**Comment by dgonzalez** [comment]
Done. This is quite a big issue... what about splitting it?

**Comment by AdoHe** [comment]
@dgonzalez sure, split it into small PRs, easily for review.

**Comment by pwittrock** [comment]
Splitting it up SGTM.
