### ISSUE TITLE
Automate Linting of Docs PRs (mungedocs)

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#31264]
Started here:
https://github.com/kubernetes/md-check

Run this in Travis against all docs PRs.

Look at https://github.com/kubernetes/kubernetes/tree/master/cmd/mungedocs for different linters we should be running

**Comment by foxish** [comment]
Handing off to Jess. Based on discussions, the linters we definitely want to port are:

- [ ] {"md-links", updateLinks}: UpdateLinks assumes lines has links in markdown syntax, and verifies that any relative links actually point to files that exist.
- [ ] {"kubectl-dash-f", updateKubectlFileTargets}: Looks for lines that have kubectl commands with -f flags and files that don't exist.
- [ ]  {"analytics", updateAnalytics}, Generate analytics.
- [ ] {"preformat-balance", checkPreformatBalance} Blocks of code need to have blank lines on both sides or they don't look right in HTML.
- [ ] {"table-of-contents", updateTOC}, Inserts/updates a table of contents in markdown. 
Caveat: Some pages may not have it.
- [ ] {"sync-examples", syncExamples}, syncExamples updates all examples in markdown file.

**Comment by jessfraz** [comment]
thanks!
