### ISSUE TITLE
Create a network performance test

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#3127]
Strawman proposal: Create a series of layered services (e.g. the onion router network) and measure RTT time for requests to pass through N layers of services. Vary N and the cluster size.

**Comment by timothysc** [comment]
Perhaps we can coordinate here, as it appears we're overlapping.  @jeremyeder

**Comment by jeremyeder** [comment]
My main concern is how to control run-to-run variation.  I put a note in issue https://github.com/GoogleCloudPlatform/kubernetes/issues/3120#issuecomment-6920338

Then as far as network tests...I assume you're talking about at least:
* Bare metal baseline (or in a VM, whatever is closest to hardware)
* RTT of a particular service running on a pod. (page load time I guess)
* Pod-to-pod on a single host (wish we had tcp_friends!)
* Pod-to-pod across physical hosts (are you already using the new ipvlan driver internally for this?)
* Scale all this up to multiple streams, both TCP and UDP.
 * Max out at 4x streams per physical CPU core?
* Do you want to test both ipv4 and ipv6?
