### ISSUE TITLE
final iteration to kill repo root.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#31270]
cc @kubernetes/sig-testing 

We need to eliminate repo-root.  This way we are gauranteed that e2es for Releases are 100% self sufficient for the binaries.

**Comment by spiffxp** [comment]
I think I found a conformance test failing on v1.3.5 (ref: https://github.com/kubernetes/kubernetes/issues/23735#issuecomment-240274842), will attempt to confirm here and see if it's the same with the latest v1.4.0 alpha

**Comment by jayunit100** [comment]
low prio to reconfirm i think `-repo-root` removal will surface compile errors when the struct is changed

**Comment by spiffxp** [comment]
Confirmed that failure is in v1.3.5, and not in v1.4.0-alpha.2, so it's been addressed in master by now.

I bring it up because I don't know what would need to be cherry-picked back to release-1.3 to fix that particular failure

**Comment by spiffxp** [comment]
/remove-lifecycle stale
`repo-root` still exists as a flag and `framework.TestContext.RepoRoot` is still very much in use
