### ISSUE TITLE
Storage: seeing parallel AttachVolume requests on the same volume (1.3.5)

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#31278]
I am reasonably sure this should not be allowed, right @saad-ali ?

It seemed to be OK in this case, but I don't think we should be doing it.

```
I0823 18:33:47.804086       7 reconciler.go:170] Started AttachVolume for volume "kubernetes.io/aws-ebs/aws://us-east-1c/vol-4f1af4e3" to node "ip-172-20-109-85.ec2.internal"
I0823 18:33:47.804086       7 reconciler.go:170] Started AttachVolume for volume "kubernetes.io/aws-ebs/aws://us-east-1c/vol-4f1af4e3" to node "ip-172-20-109-85.ec2.internal"
I0823 18:33:47.940933       7 aws.go:1140] Assigned mount device bd -> volume vol-4f1af4e3
I0823 18:33:47.940933       7 aws.go:1140] Assigned mount device bd -> volume vol-4f1af4e3
I0823 18:33:48.504800       7 aws.go:1385] AttachVolume request returned {
  AttachTime: 2016-08-23 18:33:48.486 +0000 UTC,
  Device: "/dev/xvdbd",
  InstanceId: "i-e07f75ee",
  State: "attaching",
  VolumeId: "vol-4f1af4e3"
}
I0823 18:33:48.504800       7 aws.go:1385] AttachVolume request returned {
  AttachTime: 2016-08-23 18:33:48.486 +0000 UTC,
  Device: "/dev/xvdbd",
  InstanceId: "i-e07f75ee",
  State: "attaching",
  VolumeId: "vol-4f1af4e3"
}
```

**Comment by saad-ali** [comment]
Concurrent requests on the same device should not happen. It's curious that you are seeing multiple operations with exactly the same timestamp/output. Almost as if the log output is deplicated for some reason.

**Comment by justinsb** [comment]
Gah!  That's a very polite way to put it @saad-ali :-)  I strongly suspect user-error with running two tails here.

Closing until I can disprove the simplest explanation!

**Comment by saad-ali** [comment]
> Concurrent requests on the same device should not happen. It's curious that you are seeing multiple operations with exactly the same timestamp/output. Almost as if the log output is deplicated for some reason.

That sounded super snarky re-reading it. No snarkiness intended! :)
