### ISSUE TITLE
Federation e2e setup doesn't clean up resources in the face of failures

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#31283]
When `federation-up.sh` fails in an e2e environment, it causes the test to error out and stop. This means, none of the cloud resources, i.e. none of the VMs, IP addresses, Loadbalancers and network rules are cleaned up. If the tests fail enough number of times to exhaust the quota, it leads to cascading failures and none of the future tests can pass until someone manually deletes all the resources. By this time the number of accumulated resources are so high that it is even painful to manually delete them. We should fix this.

If `federation-up.sh` fails, we should still run all the turn down scripts.

cc @kubernetes/sig-cluster-federation @colhom

**Comment by dims** [comment]
@madhusudancs punt to 1.6? if so please move the milestone from v1.5 to v1.6.

**Comment by madhusudancs** [comment]
@dims this isn't exactly a feature. A test improvement and falls in the category of "stabilization". So I think this should stay in 1.5 milestone.

**Comment by dims** [comment]
ack @madhusudancs

**Comment by dims** [comment]
@nikhiljindal all issues must be labeled either release blocker or non release blocking by end of day 18 November 2016 PST. (please add the appropriate label or please move it to 1.6) cc @kubernetes/sig-cluster-federation

**Comment by madhusudancs** [comment]
We would love some help here. But it is not a v1.5 release blocker.

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by madhusudancs** [comment]
Deferring this to @quinton-hoole @marun @shashidharatd for triaging. 

/unassign
/assign @quinton-hoole @marun @shashidharatd

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#69.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
