### ISSUE TITLE
Measure memory consumption of kubernetes master components

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#3128]
For example, we should measure the memory consumption during a LIST query that returns thousands of results to determine how efficient the serialization / deserialization of large lists of items is.

**Comment by jeremyeder** [comment]
I understand you want to watch specifically for memory consumption of specific components.  But there's a larger question I have about the capabilities of the system metrics collection harness that will monitor these runs.  Has anything been proposed yet ? @roberthbailey

**Comment by roberthbailey** [comment]
Nothing concrete has been proposed yet (this issue came from @satnam6502 and I enumerating the work items related to performance/reliability as issues for discussion/tracking).

A system to track metrics is also touch on in #3118.

**Comment by bgrant0607** [comment]
Obsolete
