### ISSUE TITLE
[Storage] Find a way to pass a secret to attach & detach calls

### ISSUE THREAD

**Issue by chakri-nelluri** [kubernetes/kubernetes#31298]
Today, attach detach controller remotely attaches PVs to nodes and it needs access to secrets to communicate with external controller.

Ideally the secret information should come from the PV object. But PV objects are not namespaced, and secrets are namespaced.  Given that we have the following two options to pass the name space information.

Option 1:
- Use pod namespace. But, it is undesirable to use the Pod namespace to access secrets. Users of Pods might not have access/details of secrets.

Option 2:
- Include both namespace & secret information in PV object. This is also discussed as probable option for Dynamic provisioner. (#30897)

We need to hash out this soon and figure out the way to pass secret to attach & detach calls.

**Comment by MikaelCluseau** [comment]
I'd a real fan of having something like "cluster secrets" for this case, and others (store API SSL keys for instance, or even support a integrated PKI).
