### ISSUE TITLE
need an API for a user to know which actions they can perform

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#31292]
It's important for users to be able to determine which actions they are allowed to perform.  We have a general API for inspecting a particular action called `SelfSubjectAccessReview.v1beta1.authorization.k8s.io`.  It is not tied to a particular authorizer because API actions have a defined set of parameter by the `authorizer.Authorize` interface.

We need a similar API for users to be able to determine which actions they're allowed to perform without checking an exhaustive list themselves.  OpenShift models this with a `SubjectRulesReview` endpoint which returns back a list of essentially `rbac.PolicyRules`, but Kube should not tie the endpoint directly to a particular authorizer.  I think we can manage this by creating an optional interface implemented by an authorizer which could provide the information.

If we made an `AllowedActions() authorizer.Attributes` interface which an authorizer could implement to provide a list of `authorizer.Attributes`, we could create a generic endpoint in the `authorization.k8s.io` group which would be authorizer agnostic.

@kubernetes/sig-auth comments?

**Comment by dims** [comment]
@deads2k switching this to 1.6 as it's too late for 1.5. ok?

**Comment by deads2k** [comment]
> @deads2k switching this to 1.6 as it's too late for 1.5. ok?

yes

**Comment by ericchiang** [comment]
Was going to write a formal proposal for this for 1.8 if no one else has taken it.

**Comment by deads2k** [comment]
> Was going to write a formal proposal for this for 1.8 if no one else has taken it.

We actually implemented this in openshift, so those types (`subjectrulesreview`) are probably a good starting point. Particular attention needs to be paid in kube to make it properly generic to the given authorization mode combinations.

**Comment by bgrant0607** [comment]
@kubernetes/sig-auth-feature-requests

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/48051

**Comment by liggitt** [comment]
@xilabao @ericchiang can this be closed now that https://github.com/kubernetes/kubernetes/pull/48051 is in?

**Comment by ericchiang** [comment]
Yep!

/close
