### ISSUE TITLE
Handle how deployment selects its RS better

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#31306]
Follow up https://github.com/kubernetes/kubernetes/pull/30730#discussion_r75842602:

Currently deployments are selecting RSes by RS labels. However it's not guaranteed that those RSes will select the same set of Pods the deployments should select. 

@kubernetes/deployment @kargakis

**Comment by kargakis** [comment]
Owner references should fix this. Closing in favor of https://github.com/kubernetes/kubernetes/issues/33845 (in-flight fix: https://github.com/kubernetes/kubernetes/pull/35676).
