### ISSUE TITLE
Try client-go with a third-party controller: cronetes

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#31304]
CSI team is moving the go client into its own repository (#28559), which is awesome.

The cronetes project, http://github.com/wercker/cronetes, provides a Kubernetes controller for scheduled jobs.  It vendors a lot of Kubernetes go code.  It would be a good validation of the go client effort if that project can easily switch to using the new client-go repo.

@hatchan is the author of cronetes, and may be interested.

**Comment by hatchan** [comment]
@erictune We would be very interested. Currently fetching dependencies, and compiling takes quite some time. Let us know when we can start testing.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this needs discussion.
