### ISSUE TITLE
Rollout status not honoring readiness probe

### ISSUE THREAD

**Issue by itajaja** [kubernetes/kubernetes#31319]
**Kubernetes version**: GitVersion:"v1.3.4+coreos.0", GitCommit:"be9bf3e842a90537e48361aded2872e389e902e7",

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS
- **Kernel**: Linux ip-10-16-11-222.ec2.internal 4.6.3-coreos #2 SMP Fri Aug 5 04:51:16 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz GenuineIntel GNU/Linux
- **Install tools**: kube-aws

**What happened**:
I updated a deployment of a pod (a web server) to a version that crashes at runtime. The process still works, but any request will return 500. There is a readiness probe that checks if the server is up. The deployment has one replica, and `maxUnavailable: 0, maxSurge: 1` rollingUpdate strategy. If I inspect the pods, I see two pods, the old one from the previous deployment, and the new one, both in Running status. After a while, the new one goes in `CrashLoopBackOff` Even though the new pod never gets healthy the `rollout status` says "deployment X successfully rolled out". This problem makes it very hard to identify bad deployments. It could be that this is the correct behavior for rollout status, but if it is, I don't know what's a good way to identify that a deployment is gone bad.

**What you expected to happen**:
I would expect rollout status to reflect the fact that the deployment didn't succeed. if I `describe deployment X` I get `Replicas:             1 updated | 1 total | 1 available | 1 unavailable`, I would also expect `updated` to be 0, unless I am not understanding correctly what that mean. The rollout status and the updated count are [probably related](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/rollout_status.go#L51).

**How to reproduce it** (as minimally and precisely as possible):
Updating a deployment to a new image that fails to pass the readiness probe

**Comment by AdoHe** [comment]
@kubernetes/deployment @kubernetes/kubectl

**Comment by kargakis** [comment]
https://github.com/kubernetes/kubernetes/pull/19343 will help in identifying failed deployments. `rollout status` will be repurposed to respect failures.

**Comment by itajaja** [comment]
Thanks @kargakis. Will I see that on the replica set as well? When I do `describe rs X` I see

```
Replicas:      	1 current / 1 desired
Pods Status:   	1 Running / 0 Waiting / 0 Succeeded / 0 Failed
```

Ideally, that count should reflect that the probes are not passing. Yes, the pod is "Running", but it was never ready. Wouldn't make sense to convey the prob information there?

**Comment by kargakis** [comment]
@itajaja if you do `get rs X` on latest master you should be able to see your ready pods. I need to update `describe` with that info too.

**Comment by itajaja** [comment]
great! I am not on master, I'll wait for a release :) 1.4 will have it?

**Comment by kargakis** [comment]
Yes
https://github.com/kubernetes/kubernetes/pull/29481
https://github.com/kubernetes/kubernetes/pull/30858

**Comment by itajaja** [comment]
Thanks, feel free to close this if you think it's duplicate/not relevant 👍

**Comment by kargakis** [comment]
No, let's keep it open for tracking the cli work for perm-failed deployments.
