### ISSUE TITLE
Create a unified test framework for e2e and integration tests?

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#3131]
Refactor the Go e2e tests to use a test framework (ideally just http://golang.org/pkg/testing/ with some extra bits to make sure the cluster is in the right state at the start of the tests). Try to consolidate on a test framework that works the same for integration and e2e tests.

**Comment by zmerlynn** [comment]
We have a test framework now for the e2e tests (Ginkgo). With a little work, we could actually have Ginkgo running the `testing` tests as well. The remaining goal, that you can't exactly flip a test between these frameworks easily, is lesser priority right now, though... obnoxious.

We should get to a place where Ginkgo is running everything, then possibly Ginkgo-ize everything, then that last statement could be straightforward as well.

cc @filbranden @rrati @ixdy

**Comment by roberthbailey** [comment]
/sig testing

feel free to close as obsolete

**Comment by thockin** [comment]
This old issue is still open - does ginkgo buy us anything?  I find it frustrating to work with, I hate reading the code for tests, and the resulting output is not particularly better than something self-rolled.

Could we get rid of ginkgo?

**Comment by roberthbailey** [comment]
@krousey has told me he'd be strongly in favor of getting rid of ginkgo, although he doesn't have the cycles to do it nor the authority to make that decision. :)

**Comment by thockin** [comment]
Anyone who can follow it through will be given authority to make that
decision :)

No, really this is SIG-testing's purvey, but nobody has given me a reason
why ginkgo is worthwhile..
