### ISSUE TITLE
Handling environments with k8s

### ISSUE THREAD

**Issue by bimalvv** [kubernetes/kubernetes#31324]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
---Handling environments like DEV, TEST, CERT, PROD

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

Looking for an option to differentiate various environments

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

Others
**What happened**:
Looking for an option to handle DEV, TEST, CERT and PROD environments.

**What you expected to happen**:
I would like to have these environments in different clusters

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:
Looking for best practice

**Comment by janetkuo** [comment]
Namespace is what you're looking for http://kubernetes.io/docs/user-guide/namespaces/. 
This question should be posted to http://stackoverflow.com/questions/ask?tags=kubernetes where questions will get more attention.
