### ISSUE TITLE
e2e tests should allow multiple concurrent runs

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#3132]
Refactor the e2e tests to allow multiple concurrent runs (assuming it is supported by the cloud provider). For GCE, this will require that the kubectl client can authenticate to multiple clusters (#1755). For GKE, this is already supported in gcloud.

**Comment by ihmccreery** [comment]
We now have PARALLEL test suites in `hack/jenkins/e2e.sh`.

Proposal to close this issue in favor of a work-issue to track moving as many e2es into the parallel suite as possible.

**Comment by zmerlynn** [comment]
Yup.
