### ISSUE TITLE
[Proposal] cross-build binaries under directory test/images

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#31331]
Cross-build binaries under directory `test/images`,
https://github.com/kubernetes/kubernetes/tree/master/test/images

TODO LIST:
- [ ] clusterapi-tester
- [ ] dnsutils
- [ ] entrypoint-tester
- [ ] fakegitserver
- [ ] goproxy
- [ ] hostexec
- [ ] iperf
- [ ] jessie-dnsutils
- [ ] mount-tester
- [ ] mount-tester-user
- [ ] n-way-http
- [ ] netexec
- [ ] network-tester
- [ ] pets
- [ ] port-forward-tester
- [ ] porter
- [ ] resource-consumer
- [x] serve_hostname
- [ ] volumes-tester

@luxas I agree with you that we should get the Makefiles somehow standardized. I would like to do some help.

@AlexMioMio

**Comment by ixdy** [comment]
I think before we start cross-building all of these images, we need to figure out a way to standardize and/or templatize the Makefiles so we don't keep duplicating the same logic everywhere.

**Comment by m1093782566** [comment]
Yes, I agree.

**Comment by luxas** [comment]
@m1093782566 Why close this? The PR is still in flight: https://github.com/kubernetes/kubernetes/issues/44910

**Comment by m1093782566** [comment]
oops... I closed it by mistake.

**Comment by luxas** [comment]
ok, no worries

**Comment by mkumatag** [comment]
test/images/volumes-tester is not ported part of this, so created #48376 to track it.
