### ISSUE TITLE
Openstack Heat deployment dashboard not working

### ISSUE THREAD

**Issue by Mamut3D** [kubernetes/kubernetes#31336]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug

**Kubernetes version** (use `kubectl version`): 1.3.5 and 1.3.3

**Environment**:
- *_Openstack liberty *_:
- **OS** (e.g. from /etc/os-release): CentOS Linux 7 (Core) - x86_64-GenericCloud-1605 image
- **Kernel** (e.g. `uname -a`): 3.10.0-327.18.2.el7.x86_64
- **Install tools**: openstack-heat
- **Others**:

**What happened**:
I was following the instalation based on http://kubernetes.io/docs/getting-started-guides/openstack-heat/
I have dowloaded kubernetes from release page https://github.com/kubernetes/kubernetes/releases

kubernetes stack installed correctly, however when i try to connect to 
`https://master-ip-address/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard` 
I am prompted for password - i provide "user" and "password" and i get web page with:
`Forbidden: "/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard"`

**What you expected to happen**: Log in to the kubernetes dashboard

**How to reproduce it** (as minimally and precisely as possible):
Follow the tutorial at http://kubernetes.io/docs/getting-started-guides/openstack-heat/

I have also had to comment 2 lines in 
cluster/openstack-heat/kubernetes-heat/kubeminion.yaml - line 375 - 376
cluster/openstack-heat/kubernetes-heat/kubecluster.yaml - line 351 - 352

```
allowed_address_pairs:
  - ip_address: 10.246.0.0/16
```

since heat was giving me following error:
`Error validating value '10.246.0.0/16': Invalid IP address`

**Anything else do we need to know**:

```
[minion@kubernetes-master ~]$ kubectl cluster-info
Kubernetes master is running at http://localhost:8080
Elasticsearch is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging
Heapster is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/heapster
Kibana is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kibana-logging
KubeDNS is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
Grafana is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
[minion@kubernetes-master ~]$ kubectl config view
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []


```

**Comment by adamrp** [comment]
:+1: I also just hit this issue. I built k8s from source (commit ebe733e46983b0201501a23a26d48a73f41fe04c).

**Comment by dims** [comment]
sig-openstack has now deprecated the heat support https://github.com/kubernetes/website/pull/5670

/close
