### ISSUE TITLE
AWS EBS/Storage Gateway volume new longer ID format

### ISSUE THREAD

**Issue by alon-argus** [kubernetes/kubernetes#31332]
Hey, this is neither a bug report nor a feature request.

I just want to make sure Kubernetes is immune to AWS transition to the new longer ID format.

Please close this issue if you find this already handled or irrelevant.

Thanks guys!

From AWS Notifications: 

> We are transitioning EBS/Storage Gateway volume and snapshot IDs to a longer format
AWS is transitioning EBS/Storage Gateway volume and snapshot IDs to a longer format. The old format is a resource identifier followed by an 8-character string, and the new format is a resource identifier followed by a 17-character string. You have until December 2016 to opt in to the longer format.

> If you do not take any action, you will be opted in automatically in December 2016, when all new instance IDs, reservation Ids, volume IDs, and snapshot IDs will be created with the longer format. Until the deadline you can opt in and out of the new format as needed. Only newly created resources will receive longer IDs; existing resources are unaffected.

> Manage your transition to longer instance IDs and reservation IDs with Resource ID length management, and read more about the [new format](https://aws.amazon.com/ec2/faqs/#longer-ids).

**Comment by justinsb** [comment]
There's no theoretical reason why we should care (we just treat the IDs as strings), and everything seems to be fine so far in testing.

Please open issues if you find anything, but in general we should be fine.
