### ISSUE TITLE
Using wait.Until doesn't work for long durations

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#31345]
Density test is failing without GC on large clusters with the following error:

```
• Failure [2058.061 seconds]
[k8s.io] Density
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:783
  [Feature:Performance] should allow starting 30 pods per node [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/density.go:673

  Expected error:
      <*errors.errorString | 0xc865089da0>: {
          s: "error while stopping RC: density60000-0-9e82e298-69eb-11e6-8157-a0481cabf39b: timed out waiting for \"density60000-0-9e82e298-69eb-11e6-8157-a0481cabf39b\" to be synced",
      }
      error while stopping RC: density60000-0-9e82e298-69eb-11e6-8157-a0481cabf39b: timed out waiting for "density60000-0-9e82e298-69eb-11e6-8157-a0481cabf39b" to be synced
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/density.go:332
```

However, this "working as implemented" currently.

The problem is that in this case, underneath we are using "DeleteRCAndPods" method to delete RC, and this in turn is using "ReplicationControllerReaper", which results in calling this one:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/scale.go#L199

However, when watch is close, "wait.Until" returns "ErrWaitTimeout":
https://github.com/kubernetes/kubernetes/blob/master/pkg/watch/until.go#L63

The test is failing after exactly 5 minutes of waiting for the RC deletion, because of Timeout on http.Client:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L1749

I think that there are two issues here:
1. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/scale.go#L199 is not going to watch if we intend to wait for a long time, since watch can be close at any time. In those cases, we should be actually renewing a watch.
   We may have similar problems in other places of the code.
2. Why do we set client.Timeout in tests if we are not doing it anywhere in production? We should use as similar setup to production as possible in our test. @krousey @lavalamp 
   [For this one I'm going to send a PR that will stop setting timeouts for http.Client in tests.]

**Comment by wojtek-t** [comment]
@caesarxuchao

**Comment by wojtek-t** [comment]
So to summarize, the main problem in my opinion is that:
wait.Until take "watch.Interface" as an argument, and we are breaking up watches every 5-10 minutes. So if you are supposed to wait longer than that, it will just timeout.

Adding @smarterclayton - who added wait.Until IIRC

@kubernetes/sig-scalability

**Comment by smarterclayton** [comment]
We should be renewing the watch.  However that's not enough - you really need Get then Watch.  So there has to be something that abstracts watcher creation (a watch wrapper).

**Comment by wojtek-t** [comment]
Yeah - I agree that this is not trivial change. It should be somewhat similar to what we are doing in reflector.

I guess it's not 1.4 change though.

**Comment by smarterclayton** [comment]
Agreed that anyone who switched to watch.Until may have done so prematurely.

**Comment by yujuhong** [comment]
This is causing quite a lot of test flakes. Can we replace `watch.Until` with something else (polling?) in the tests until it's fixed properly?

**Comment by smarterclayton** [comment]
We should maybe just turn the client timeout way up.  It's kind of arbitrary and I opened another issue about removing it.

**Comment by janetkuo** [comment]
> This is causing quite a lot of test flakes. Can we replace `watch.Until` with something else (polling?) in the tests until it's fixed properly?

Filed #41112

**Comment by smarterclayton** [comment]
Seeing this in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/4544

**Comment by wojtek-t** [comment]
Do we want to do something with this soon-ish?

**Comment by smarterclayton** [comment]
It seems like we want a client aware watcher abstraction that is basically a lightweight, low cost informer.

**Comment by xh3b4sd** [comment]
For my interest, what is the actual state of this? I have the feeling people start to work around this and the current implementation just remains broken. Would be cool to get this sorted because lots of operators and controllers rely on reliable watches. Our own operators miss events regularly which  decreases the service quality overall.

**Comment by tnozicka** [comment]
@xh3b4sd I have a branch to switch watch.Until to informers or RetryWatcher depending on the usecase across kubernetes code base as part of fixing https://github.com/kubernetes/kubernetes/issues/40224

The relevant discussion (with old code) is here https://github.com/kubernetes/kubernetes/pull/50102#issuecomment-328495934

Hope to get some cycles to finish it soon.

/assign

**Comment by xh3b4sd** [comment]
@tnozicka thanks for your fast response. I came across your PR and landed here in this issue. We currently have our own informer implementation to work around the problem but I do not really like to have a "home grown" solution for such things without community support. See https://github.com/giantswarm/operatorkit/tree/master/informer. I guess we could get traction during the official operatorkit incubation there is just not that much pace right now. Would be cool to collaborate and get this straight for all of us. Cheers.

**Comment by spiffxp** [comment]
/priority backlog
taking a guess at priority based on long it's been since this was touched

**Comment by tnozicka** [comment]
Fix is ready here: https://github.com/kubernetes/kubernetes/pull/50102

**Comment by wojtek-t** [comment]
/remove-lifecycle stale
/lifecycle frozen

https://github.com/kubernetes/kubernetes/pull/50102 (once figured out) should fix this issue.

**Comment by gatici** [comment]
Hi  @wojtek-t 

My big  deployment  with helm is  failing with  below error. I am starting the  helm  installation with  
--timeout  5000  parameter.  Is there any  solution to  increase  watch   timeout  in kube-api ?

helm history   dev-so   -o  yaml
- chart: so-4.0.0
  description: 'Release "dev-so" failed post-install: watch closed before UntilWithoutRetry
    timeout'
  revision: 1
  status: FAILED
