### ISSUE TITLE
Create a compatibility test matrix

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#3136]
Verify that an old client works with a new server, different api versions, etc.

Axes of Variation include:
 - Build version: HEAD, previous supported releases
 - Version of API: v1beta1, v1beta3, etc.
 - Cloud providers: GCE, GKE, AWS, etc.
 - Docker version
 - Container VM versions
 - Other external tools e.g. salt
 - OS/Kernel versions
 - Go versions
 - Cloud SDK versions (specifically the gcloud container component for GKE)

**Comment by djsly** [comment]
Is there a compatibility matrix that exists for kubernetes ?

should we assume that the latest kubectl binaries will be compatible with previous server version ?
