### ISSUE TITLE
kubenet_unsupported.go is missing mtu from Init method

### ISSUE THREAD

**Issue by alexbrand** [kubernetes/kubernetes#31360]
While trying to build the kubelet with `GOOS=windows`, I got a build error related to `kubenet_unsupported.go`. It looks like a new `mtu` argument was added to the `Init` method of the `network.NetworkPlugin` interface, but `kubenet_unsupported.go` was not updated.

**Comment by freehan** [comment]
Thanks for jumping in!

Another fix is in flight. Closing this one.
ref: #31372, #30376

**Comment by alexbrand** [comment]
Oh cool! Thanks
