### ISSUE TITLE
Hyperkube build now requires a TTY

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#31412]
I can no longer build `hyperkube` as part of my continuous integration setup.

This is vital because we use `hyperkube` in `kubernetes-anywhere` and I build `hyperkube` as part of that process.

I believe the issue is here: https://github.com/kubernetes/kubernetes/commit/d711fd8764fc26041f82729e7b74c25738e7a55c#diff-86f22fb5b693949f04077054c41b762fR104

cc: @luxas

**Comment by luxas** [comment]
# TODO(freehan): Push the latest cni for all arches to storage.googleapis.com so we may just download the binaries`

Yeah, that's quite temporary, just so we can release v1.4.0-alpha.3 before @freehan uploads cni to gcs: https://github.com/kubernetes/kubernetes/issues/31348

Why does it fail? Doesn't your CI system have a tty? 
Can this be fixed just by removing the `-t` part of run?

**Comment by colemickens** [comment]
I worked around it for now by adding: `sed -i 's/docker run -it/docker run/g' cluster/images/hyperkube/Makefile` to my build.
 
I can send a PR here too depending on how temporary this is.

**Comment by asalkeld** [comment]
PR #31477 has been merged, please close this.

**Comment by colemickens** [comment]
Thanks for the heads up @asalkeld. Closing this.
