### ISSUE TITLE
1.3.4 AWS Nodes constantly go NotReady with KubeletNotReady container runtime is down

### ISSUE THREAD

**Issue by erez-rabih** [kubernetes/kubernetes#31415]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
KubeletNotReady container runtime is down

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug report

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:45:16Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:38:31Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**: What does that mean?
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release):

```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- **Kernel** (e.g. `uname -a`):

```
Linux ip-172-20-1-41 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
```
- **Install tools**:
- **Others**:

**What happened**: Nodes turn to NotReady with the following message on the describe output:

```
KubeletNotReady         container runtime is down. WARNING: CPU hardcapping unsupported
```

This is the output of the sudo docker version command on the node:

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

The node does not seem to recover from this failure so I have to kill it and the auto scaling group brings up another one instead.

**What you expected to happen**: Nodes should remain in a Ready state or at least recover from such failures.

**How to reproduce it** (as minimally and precisely as possible):  It just happens once in two days approximately.

**Anything else do we need to know**:

This is the [daemon.log.txt](https://github.com/kubernetes/kubernetes/files/436373/daemon.log.txt) from the time the node went down

**Comment by anioool** [comment]
Hi,
+1 to matter described by author. Usually after 24-48 hours all nodes has NotReady status even if nodes were not loaded (idle time).

From my side I also has problem with nodes discovery. When I upgraded kubernetes to 1.3.4 I need restart nodes several times before they are discovered via controller.

**Comment by felipejfc** [comment]
+1 It happens on all my nodes, at least once per day, some instances more than others
