### ISSUE TITLE
Dynamic provisioned ebs type is gb2 even if set the type to io1 in the storageclass

### ISSUE THREAD

**Issue by chao007** [kubernetes/kubernetes#31419]
**Kubernetes version** (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.2.1689+74b01041cc3feb-dirty", GitCommit:"74b01041cc3feb2bb731cc243ab0e4515bef9a84", GitTreeState:"dirty", BuildDate:"2016-08-25T06:39:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: aws
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
PV is provisoned, but the volume type is gp2

**What you expected to happen**:
PV volume type is io1

**How to reproduce it** (as minimally and precisely as possible):
1.Create a storageclass object, type is io1
kind: StorageClass
apiVersion: extensions/v1beta1
metadata:
  name: slow
provisioner: kubernetes.io/aws-ebs
provisionerParameters:
  type: io1
  zone: us-east-1d
  iopsPerGB: "25"

2.Create a pvc
{
  "kind": "PersistentVolumeClaim",
  "apiVersion": "v1",
  "metadata": {
    "name": "claim1",
    "annotations": {
        "volume.beta.kubernetes.io/storage-class": "slow"
    }
  },
  "spec": {
    "accessModes": [
      "ReadWriteOnce"
    ],
    "resources": {
      "requests": {
        "storage": "4Gi"
      }
    }
  }
}

**Anything else do we need to know**:

**Comment by jsafrane** [comment]
> provisionerParameters:

It's `parameters` now.

`kubectl create -f class.yaml` throws `found invalid field provisionerParameters for v1beta1.StorageClass`.

I can force the yaml with `--validate=false` and then obviously `provisionerParameters:` is ignored and created class has empty `parameters:`, leading to default gp2.

**Comment by chao007** [comment]
It works after update to `parameters`, close this issue
