### ISSUE TITLE
kubelet prints fatal error twice without a newline

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#31417]
I am seeing this:

```
Error: failed to run Kubelet: invalid kubeconfig: stat /etc/kubernetes/kubelet.conf: no such file or directory
failed to run Kubelet: invalid kubeconfig: stat /etc/kubernetes/kubelet.conf: no such file or directory
```

The last line is missing a `\n`, seems like this would be an easy fix, but I'm not sure why does it even print this error twice? Also, this output doesn't have a timestamp prefix - is it intentional to not use the logger for this or it's some kind of limitation or a know issue and affects other components?

This may had been reported already in some form.

**Comment by asalkeld** [comment]
It is probably a glog(err) and the print before os.Exit

Here is the print with a "\n"
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/kubelet.go#L49

**Comment by errordeveloper** [comment]
I'm still confused, the line 49 in `main()` has a `\n` and also has lower-case `"error:" prefix, but here we are seeing one with uppercase `"Error:"` and with an `\n`, and one without either of those things. I can guess that the first one may been indeed from the logger, but where does the second one come from?

**Comment by errordeveloper** [comment]
I don't see this happening any more, must have been fixed.
