### ISSUE TITLE
New minion is not adding to the cluster

### ISSUE THREAD

**Issue by rmahajan2420** [kubernetes/kubernetes#31422]
Hi,

I am using kube aws install version 1.3.4..  Hi All, I have added new node to the cluster and getting error :  Unable to find Node::, deleting all assigned Pods.. I  have created another ASG group for minion and used the user data for minion provided by aws.. I am seeing this on  kube-master controller log.

Kube master api log: Getting 404
I0825 09:10:45.461119       5 handlers.go:165] GET /api/v1/nodes/ip-172-31-38-232.ec2.internal: (1.680183ms) 404 [[kubelet/v1.3.4 (linux/amd64) kubernetes/dd6b458]

Kubelet logs of the  new node:

Aug 25 09:20:24 ip-172-31-38-232 kubelet[9665]: E0825 09:20:24.675696    9665 kubelet.go:2875] Error updating node status, will retry: error getting node "ip-172-31-38-232.ec2.internal": nodes "ip-172-31-38-232.ec2.internal" not found

I am stuck on this and need inputs..

**Comment by MKhotele** [comment]
I am facing similar problem wirh k8s v1.3.3. I had created a k8s cluster on aws with 6 minions. On editing the corresponding aws auto-scale group to have min=desired=8 events (max=16), 2 new minion ec2 instances do get started. But when I run "kubectl get nodes" it shows only 6 instead of 8 nodes.

**Comment by rmahajan2420** [comment]
I have found the solution. Check the tas of your running instances, you need to create a tags at the time of instance creation. U need to add create-tags command in user data.. Hope it helps.

**Comment by MKhotele** [comment]
I didn't created the instances manually. AWS created the instances automatically, because I had updated the auto-scale group. Can I influence this process for adding the tags? How?

By the way, I checked and see that previous and new instances both have same tags:

- KubernetesCluster
- Name
- Role
- aws:autoscaling:groupName

And with previous version, i hadn't faced such issue.

**Comment by kevtaylor** [comment]
@rmahajan2420 Please can you explain your answer a little. We would like to know exactly what tags you added / configuration changes you made to the node to solve this issue.

**Comment by gonzalomarcote** [comment]
Pffew! I have solved it like rmahajan2420 said. I have configured exactly the same tags in all the workers and it worked
