### ISSUE TITLE
kubernetes-e2e-gce-serial: failed to schedule pods because of node was tainted.

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#31444]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-serial/2012/

Failed: [k8s.io] Kubelet [Serial] [Slow] [k8s.io] regular resource usage tracking resource tracking for 100 pods per node {Kubernetes e2e suite}

The test was trying to create 100 pods per node, and many pods couldn't get scheduled because one node was tainted.
```
09:06:52 fit failure on node (jenkins-e2e-minion-group-qjbn): Insufficient pods
09:06:52 fit failure on node (jenkins-e2e-minion-group-uh3n): Insufficient pods
09:06:52 fit failure on node (jenkins-e2e-minion-group-641y): PodToleratesNodeTaints
```

From apiserver.log, the e2e test patches the node
```
I0825 15:48:19.873754       5 handlers.go:162] PATCH /api/v1/nodes/jenkins-e2e-minion-group-641y: (14.107677ms) 200 [[e2e.test/v1.4.0 (linux/amd64) kubernetes/ab8d452] 104.197.252.147:54804]
I0825 15:48:20.880217       5 handlers.go:162] PUT /api/v1/nodes/jenkins-e2e-minion-group-641y: (8.422497ms) 200 [[e2e.test/v1.4.0 (linux/amd64) kubernetes/ab8d452] 104.197.252.147:52831]
I0825 15:57:48.753496       5 handlers.go:162] PUT /api/v1/nodes/jenkins-e2e-minion-group-641y: (13.186984ms) 200 [[rescheduler/v0.0.0 (linux/amd64) kubernetes/$Format] 127.0.0.1:52730]
I0825 16:07:49.335654       5 handlers.go:162] PUT /api/v1/nodes/jenkins-e2e-minion-group-641y: (9.321318ms) 200 [[rescheduler/v0.0.0 (linux/amd64) kubernetes/$Format] 127.0.0.1:52730]
I0825 16:22:36.084301       5 handlers.go:162] PUT /api/v1/nodes/jenkins-e2e-minion-group-641y: (16.139348ms) 200 [[e2e.test/v1.4.0 (linux/amd64) kubernetes/ab8d452] 104.197.252.147:39397]
I0825 16:22:40.103375       5 handlers.go:162] PUT /api/v1/nodes/jenkins-e2e-minion-group-641y: (6.131076ms) 200 [[e2e.test/v1.4.0 (linux/amd64) kubernetes/ab8d452] 104.197.252.147:39397]
```

My guess is one of scheduler tests ran prior to this test marked the node as tainted, and did not clean up properly. @davidopp, is that possible?

**Comment by yujuhong** [comment]
Another question: what components would add taints to nodes?

**Comment by mikedanese** [comment]
@yujuhong probably another e2e test?

**Comment by yujuhong** [comment]
> @yujuhong probably another e2e test?

Yeah, I just wanted to rule out components other than the scheduler tests :-)

**Comment by mikedanese** [comment]
Ahh gotcha.

**Comment by mikedanese** [comment]
ref #31448

**Comment by davidopp** [comment]
@yujuhong Yes, I agree with you and @mikedanese.

@kevin-wangzefeng can you please take a look at this?

**Comment by kevin-wangzefeng** [comment]
Current taint-related e2e tests have chance of failing to remove taints, but those tests should also fail.
Maybe there is still some taint leak, I will check.

**Comment by davidopp** [comment]
Thanks @kevin-wangzefeng . I think #27655 is related also?

**Comment by kevin-wangzefeng** [comment]
@davidopp Yes, I will double check if there's any other chance that may cause taints leak.

**Comment by davidopp** [comment]
AFAIK this hasn't recurred.
