### ISSUE TITLE
Proposal: Optimize in memory usage of internal / external types

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#31440]
At high scales and densities, the internal memory usage of our structs becomes relevant to controllers maintaining caches and the amount of memory used by the api server caches.  We have evidence (https://github.com/coreos/kscale/pull/37/files#diff-a423e914cbd27c95d2c0b950e2e4ee5bR14) that in memory usage of pods is egregiously inflated by use of maps (60% or more).

We should consider representing all of our small / internal external maps by "array maps" - especially annotations and labels (which are on all objects) and resource lists.  This would likely have a disproportionate impact on cache memory usage (I suspect we could save 30-60% of the heap use for memory).

Hypothetical:

```
type StringEntry {
  Key string
  Value string
}
type Map []StringEntry

func (m *Map) Len() { ... }
func (m *Map) Get(key string) string { ... }
...

func (m *Map) MarshalJSON() ([]byte, error) { ... write out as JSON map }
func (m *Map) UnmarshalJSON([]byte) (error) { ... read as JSON map }

```

We would identify maps with less than O(50) items in common use and consider this to be a required decision on new API fields.

Internal and external types would both have this.  We would need to alter labels to have a `SelectorFromMap`. JSON and protobuf serialization must be identical to the internal types - we wouldn't want to create additional work in order to do that conversion.  

Downsides: 
- makes code that uses these structs slightly more complicated to use.

Alternatives:
- Investigate whether native Go maps can be tuned to use less space ootb
- ???

Steps:
- Verify usage via testing
- Investigate alternatives
- Prototype and flush out issues with serialization.

**Comment by smarterclayton** [comment]
@kubernetes/sig-api-machinery @kubernetes/sig-scalability something to consider in 1.5 if at density we hit memory use limits in our caches.

**Comment by krousey** [comment]
I'm just going to propose this and shoot it down in the same comment.

Could each controller just specify it's own type in which to decode? Like request a `v1.Pod`:

```go
type ObjectMeta struct {
	Name string `json:"name,omitempty" protobuf:"bytes,1,opt,name=name"`
	Labels map[string]string `json:"labels,omitempty" protobuf:"bytes,11,rep,name=labels"`
	Annotations map[string]string `json:"annotations,omitempty" protobuf:"bytes,12,rep,name=annotations"`
...
}

type Pod struct {
	unversioned.TypeMeta `json:",inline"`
	ObjectMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
...
}
```

be deserialized to this custom representation:

```go
type LabelsICareAbout struct {
	LabelVal1 string
	LabelVal2 string
}

// code to handle proper marshalling and unmarshalling

type MyObjectMeta struct {
	Name string `json:"name,omitempty" protobuf:"bytes,1,opt,name=name"`
	LabelsICareAbout `json:"labels,omitempty" protobuf:"bytes,11,rep,name=labels"`
	// No annotations because I don't need them
...
}

type Pod struct {
	unversioned.TypeMeta `json:",inline"`
	MyObjectMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
...
}
```

**Why this is a Good Idea:**

It means that each controller can cut down the data to exactly what it needs to work. No more. No less.

:fire: **Why this is an absolutely terrible idea:** :fire:

It's new API types, custom one-off API types. It most definitely doesn't play well with a lot of the runtime and code generation machinery. Custom logic for marshaling and unmarshaling would be custom, and have to handle multiple encodings. Oh and you're trying to optimize objects stored in caches that are actually shared by multiple controllers and wildly overlap in the data that they need from objects. So you probably wouldn't be able to save that much.

**Comment by smarterclayton** [comment]
I have the custom response type proposal coming (request alternate
representations of objects), which lines up with your proposal a bit.
But in practice small maps are roughly 200-300 bytes each, so 4 small
maps per Kube object is a massive overhead, even on minimal indices.
So yes, we'll get efficiencies from your direction in other places,
but it won't help all controller paths, so I *suspect* both are
needed.

**Comment by smarterclayton** [comment]
Correction, 400 bytes for some of the maps.  Compared to an array (8 byte pointer to slice, 8 byte length on slice, 8 bytes per string pair, so ~16 overhead + 16bytes/entry omitting strings) we could save 75-80% of a four entry slice, and likely 90-95% of a 1 item slice.

----

Here's an inuse_space controller heap profile from OpenShift 1.3 perf testing with 5000 namespaces, 20 secrets per ns, 3 pods per ns, and a number of other resources:

http://perf-infra.ec2.breakage.org/pbench/results/mvirt-j/300nodes_5K_projects_3.3.0.23_c/tools-default/mvirt-m-2/pprof/2016-08-23:23:51:58_controller_heap.txt

20 secrets per ns * ~5k of JSON per secret ~= 100k per namespace * 5000 ns ~= 500M of memory, *plus* an overhead of 5k ns * 20 secrets per ns * 3 maps per secret * 400 bytes is another 120M of memory.  Secrets are a lot larger than other objects because they have embedded byte arrays and our JWT / dockercfg tokens are pretty big on their own.  Note too that because of conversion we are likely fragmenting our pages quite heavily - we create strings and structs in close proximity for v1, then throw away the structs and create new structs, but keep references to the strings for a long time.

For pods and replication controllers, we have potentially 5-10 maps per object (labels, annotations, resource limits + requests per container, selector, node selector, pod template annotations and labels, etc).  So 5k ns * (3 pods + 2 rs + 1 other object with a pod template) * 6 * 400bytes is 70M.  

If this was a 100k pod cluster, we might have 240M of maps in those objects.

**Comment by lavalamp** [comment]
This would be a massive undertaking.

**Comment by smarterclayton** [comment]
I don't think it would be that bad.  I tried this for resource list
while trying to reduce it and it was 60-80 files, but lots of trivial
changes.

**Comment by wojtek-t** [comment]
I generally think it would be useful. However, we need to do that in a way to not make the cpu-usage visibly worse (though I agree that at least for some fields the optimization should work).
In other words, I'm not sure where the boundary for number of elements it, but my guess is that it would be lower than O(50)...

**Comment by dims** [comment]
@smarterclayton @wojtek-t : move the milestone to v1.6?

**Comment by smarterclayton** [comment]
Removing milestone altogether - not blocking at the moment.

**Comment by smarterclayton** [comment]
Nothing actionable right now.
