### ISSUE TITLE
kubernetes-e2e-gke-gci - [Feature:Example] [k8s.io] Celery-RabbitMQ should create and stop celery+rabbitmq servers failing

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#31456]
"[Feature:Example] [k8s.io] Celery-RabbitMQ should create and stop celery+rabbitmq servers failing" test has been failing consistently on GCI.
Most recent failures:
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-gci-examples/98
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-gci-examples/97

This is a possible k8s on GCI blocker.

**Comment by vishh** [comment]
cc @luxas

**Comment by vishh** [comment]
The `endocode/celery-app-add` container fails only on GCI. 

Try `docker run endocode/celery-app-add` on GCI and you will run into the track trace posted in https://github.com/kubernetes/kubernetes/issues/31456#issuecomment-242529565

cc @adityakali @wonderfly

**Comment by vishh** [comment]
cc @dchen1107

**Comment by vishh** [comment]
False alarm. This test is completely broken. The celery docker container does not come up on most distros including container-vm, coreos, rhel, gci, etc. The test is passing on container-vm possibly because of a race. The test performs an exec to get a log file. The exec is racy since the failing celery container can exit anytime. 
I'm going to mark that test as broken and update the documentation as well.

For the sake of completeness, a potential fix will be to update the glibc version that the celery container uses to a version >= 2.23

**Comment by vishh** [comment]
ping @kbeecher the original author of the celery+rabbitmq example. Will you be able to fix the celery container?

**Comment by adityakali** [comment]
> For the sake of completeness, a potential fix will be to update the glibc version that the celery container uses to a version >= 2.23

Some more details from our debugging session. The container keeps running into error at getaddrinfo /usr/local/lib/python2.7/dist-packages/amqp/transport.py line 75 with 'Name or service not found'. This is similar to what we had seen previously with a glibc bug (https://sourceware.org/bugzilla/show_bug.cgi?id=15946) on older version. The container uses glibc 2.19 which is affected by it. Hence the suggestion to update the container to newer image (with newer glibc).

**Comment by dchen1107** [comment]
https://github.com/kubernetes/kubernetes/pull/31475 was merged. Close this one.
