### ISSUE TITLE
Decouple E2E Configuration from flag libraries.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#31453]
**Problem**

The flat flags based config is not scaling + increasingly tricky for users to leverage, _esp for custom test runs_.  There is both a usability issue, and also a technical limitation posed by needing flags for configuring e2es.
- **usability** The e2e flag options represent several "sub programs" each of which has mutually exclusive configuration.   There are approx 42 flags currently.  This makes it hard for any user to quickly focus on the configuration they care about which is (typically) focused on a single test or small suite of tests.
- **technical** : `go test` is dependent on the somewhat inflexible `flag` library in golang, which is not evolving very quickly.  The manual call to flag.Test makes it so that it doesnt interoperate well with `pflag`, which is the ideal way for flexible.  Practically speaking, adding any args to the e2e's requires that those args are supported in `flag`.
- **automation**: Orthogonal but related.  We really should introspect as much as possible.  Maybe we can introspect OpenStack, Atomic, GCE, AWS, related stuff.  Maybe we can introspect SELinux related stuff.  Also Introspection of `--scale` and other sorts of parameters.

Per a Discussion w/ @timothysc , we will propose a 3 step path to sanity.  To be discussed in @kubernetes/sig-testing .

**Solution**
1. Define a single struct for all flags.   this will decouple e2e parameterization from `flag.XYZ` calls.
2. Exemplify a mapping for the struct that is auto-generated on build for users to borrow from.  Use Viper to injest a jsonified struct and directly write it as config.
3. Remove all flags entirely and use pure json/yaml/ini/etcd configurator for the e2es, and publish e2e.

**Comment by jayunit100** [comment]
this is a follow up to #31030

**Comment by jayunit100** [comment]
Done! Now viper can be used to drive config for anything

**Comment by jayunit100** [comment]
Reopened , because I think this issue also should stay around until we finally remove all flags not related to defining the viper data source

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @jayunit100

**Comment by jayunit100** [comment]
Yeah not necessarily for 1.5

**Comment by dims** [comment]
Ack. switching milestone @jayunit100

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by spiffxp** [comment]
/sig testing

I don't have privileges to move this out of the milestone, but I don't think it belongs in v1.7
