### ISSUE TITLE
Starting docker containers directly using docker client fails

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#31465]
On a cluster using GCI, I'm not able to create docker containers using the docker CLI. On further introspection, it looks like `docker0` bridge is being deleted. I consider this a regression. K8s used to allow creating docker containers out of band and in-fact it is a feature that is taken into account as part of k8s node features.
To further exacerbate this issue, `docker0` exists on containervm. We need to match the behavior between GCI and container-vm and ideally stop deleting docker0 bridge. 

cc @kubernetes/sig-node @kubernetes/sig-network @adityakali @wonderfly

**Comment by freehan** [comment]
During GCI start up, `docker0` got deleted to avoid overlapping cidr with `cbr0`. #26379
https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L511

ref: #29756

**Comment by bprashanth** [comment]
there's no need to delete docker0 afaik. It was deleted on gci master to fix the "overlapping cidr" problem, i.e we were supplying `--pod-cidr=(default docker0 cidr)` to kubelet on GKE master, and this resulted in 2 bridges with the same cidr. At the time I'd suggested passing the correct cidr. Don't remember where this discussion ended. 

Note that containers on docker0 with/without cni are broken anyway, we used to start docker with --bridge=cbr0, so `docker run -it busybox` would result in an ip from cbr0. This is no longer the case. We use kubenet to put containers on cbr0, so  `docker run -it busybox` will result in an ip from docker0, which is not connected to nanything else.

@maisem @freehan

**Comment by bprashanth** [comment]
> On a cluster using GCI, I'm not able to create docker containers using the docker CLI. On further introspection, it looks like docker0 bridge is being deleted.

This shouldn't cause docker crashes? you should still be able to create containers, just no networking. And networking is broken through docker CLI anyway because of the cni issue mentioned, or are you observing something different?

**Comment by freehan** [comment]
`docker run` will return `docker0 not found` error. Have to add `net=none`

**Comment by vishh** [comment]
Since `docker0` bridge has been deleted, docker run by default will fail unless one overrides the network ns to be host or none.

**Comment by bprashanth** [comment]
so what we're really losing is the ability to docker run then talk to others (external internet, other pods) without net=host on GCI. This is useful and we should fix it, as mentioned earlier we probably don't need to delete docker0. docker run + others talking to us is broken because of the cni change, and will be broken even with docker0 (IMO this is fine).

**Comment by vishh** [comment]
cc @thockin @yujuhong

**Comment by vishh** [comment]
Yeah. I'd prefer ignoring docker0 as long as it doesn't affect kubelet
functionality.

**Comment by thockin** [comment]
Vish pointed out that of docker dies, docker0 comes back.  Given that we
should be consistent.  Either force docker not to create a bridge at all,
EVER, or just ignore docker0.  We may even want to consider assigning --bip=
169.254.123.0/24 or something, so we can reliably use 172.* for clusters
eventually.
