### ISSUE TITLE
[AppArmor] Don't schedule AppArmor pods to older nodes

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#31469]
If the scheduler is a newer version, but the nodes are not, we should prevent pods with AppArmor options from being scheduled on the older nodes.

Options:
1. Use the reported kubelet version in the node info to determine whether a node is "AppArmor aware". Rely on the Kubelet to reject the pod if the node does not meet the [AppArmor prerequisites](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/apparmor.md#prerequisites).
2. Have you kubelet publish it's AppArmor status (i.e. whether AA is enabled on the node), and use that status to determine where the pod can be run.

I'm inclined to go with the first option because (a) it doesn't add the complexity of the kubelet publishing it's status and (b) the goal isn't to make this work on heterogeneous clusters (use node labels for that).

Do we need to get this into 1.4, or should we save it for 1.5?

cc/ @dchen1107 @yujuhong @jfrazelle @thockin @matchstick

**Comment by dims** [comment]
@timstclair since there has been no updates on this, should the milestone be moved to v1.6?

**Comment by timstclair** [comment]
Acutally, I think we can close this issue. It core issue should be resolved by https://github.com/kubernetes/kubernetes/pull/35342, and going forward I think it's acceptible to put the onus for ensuring node versions are AppArmor compatible on the cluster admin. @dchen1107 do you agree?
