### ISSUE TITLE
Proposal: Keep dev version one minor version ahead in mark-new-version.sh

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#3147]
When we tagged 0.7.0 and 0.7.0-dev with `build/mark-new-version.sh`, we essentially created servers that are virtually indistinguishable from one another until 0.8.0 ships. The problem is that if you try to write tests that will certainly run on new servers but not on old, there's no way to distinguish these except the minor addition of the "dirty" bit and the "7+" in the minor coming from kubectl. See #3146 : That PR can be written entirely server version sensitive (rather than keying off of provider) if this proposal were enacted, but as it is, if I don't key off of GKE, I'll accidentally disable the exec test on GCE HEAD tests. If this proposal is enacted, I can use 0.8.0 to mean "HEAD".

I propose that during development, the apiserver should always assert the next minor version, and that the release process should always bump to N+1. Sometimes you'll get into funny situations where you actually ship the the next minor version as a major version (e.g. the servers that were asserting 0.11 suddenly become 1.0) because it's go time. That's not a big deal, it happens. (And if you look at the kube_server_version function I added in that PR, existing checks would stay working even if we shipped 0.11 as 1.0, so it's really not a big deal.)

**Comment by bgrant0607** [comment]
Obsolete
