### ISSUE TITLE
When a namespace is deleted, its ScheduledJob (if existed) should be deleted too

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#31481]
Found that ScheduledJob isn't deleted after its namespace is deleted while debugging e2e tests. 

cc @erictune @soltysh

**Comment by zhouhaibing089** [comment]
Sorry, but what is **SJ**?

**Comment by janetkuo** [comment]
@zhouhaibing089 yes, it's scheduled job. I removed the acronym in title.

**Comment by liggitt** [comment]
as long as the resource is reflected in discovery docs, nothing special should be needed to be cleaned up

need to track down why this is happening and find out of any other resources are affected

**Comment by liggitt** [comment]
looks like serverPreferredResources() only discovers resources in the preferred version for each group, so misses resources that only exist in a non-preferred version

**Comment by soltysh** [comment]
Fix is in #36444

**Comment by dims** [comment]
PR #36444 looks stuck

**Comment by soltysh** [comment]
@dims, we agreed on a solution with @liggitt and @derekwaynecarr I'm updating the PR according to what we've agreed on.

**Comment by dims** [comment]
Excellent, thanks for the update @soltysh

**Comment by dims** [comment]
The PR is marked as a release-blocker, so marking the issue the same
