### ISSUE TITLE
kubelet summary stats api reports wrong imagefs inodes

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/kubernetes#31501]
**Kubernetes version** (use `kubectl version`):
v1.4.0-alpha.3.44+d3ecad111e5641-dirty

**What happened**:
Two issue:
1) There is no imageFs.inodesFree
2) imageFs.inodes is equal to rootfs.inodes
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/stats/summary.go#L137 

**What you expected to happen**:
Show imageFs inodes and inodesFree info correctly

**How to reproduce it** (as minimally and precisely as possible):
```
[root@ip-172-18-12-44 dma]# curl -k https://localhost:10250/stats/summary
{
  "node": {
   "nodeName": "127.0.0.1",
   "startTime": "2016-08-26T01:56:29Z",
   "cpu": {
    "time": "2016-08-26T08:43:27Z",
    "usageNanoCores": 50805060,
    "usageCoreNanoSeconds": 3330345297727
   },
   "memory": {
    "time": "2016-08-26T08:43:27Z",
    "availableBytes": 4959387648,
    "usageBytes": 5477744640,
    "workingSetBytes": 2974326784,
    "rssBytes": 286793728,
    "pageFaults": 286932163,
    "majorPageFaults": 1010
   },
   "network": {
    "time": "2016-08-26T08:43:27Z",
    "rxBytes": 291839331,
    "rxErrors": 0,
    "txBytes": 4116094,
    "txErrors": 0
   },
   "fs": {
    "availableBytes": 3474526208,
    "capacityBytes": 26830942208,
    "usedBytes": 23356416000,
    "inodesFree": 13573955,
    "inodes": 14497296
   },
   "runtime": {
    "imageFs": {
     "availableBytes": 14147715072,
     "capacityBytes": 15028191232,
     "usedBytes": 730706128,
     "inodes": 14497296
    }
   }
  },
  "pods": []
 }
```

@derekwaynecarr @ncdc

**Comment by derekwaynecarr** [comment]
what storage driver are you running w/ docker?

I suspect devicemapper, but can you return the output `docker info`?

devicemapper should be showing no inodes value at all

**Comment by mdshuai** [comment]
yes, storage driver is devicemapper. If there is no inodes, don't know why set [ImageFs.Inodes:         sb.rootFsInfo.Inodes](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/stats/summary.go#L137)

**Comment by derekwaynecarr** [comment]
the issue is that the value set is a pointer, and in the case of
devicemapper, it should have been reporting a nil value for the pointer
(same was what inodesFree is showing in your scenario).

is this on loopback or something else?  it's a bug in cadvisor if you are
seeing a value set.

**Comment by dchen1107** [comment]
@derekwaynecarr any updates on devicemapper fix? Or should we move this to 1.5 milestone?

**Comment by timstclair** [comment]
Reminder: We'll be cutting a cAdvisor release on 9/15. If this needs a cAdvisor fix, it should go in before that.

**Comment by derekwaynecarr** [comment]
I need to get back to the reporter to know how their devicemapper was
setup.  I hope to have something this week if there is a real issue.

**Comment by mdshuai** [comment]
I don't think this is a bug about cadvisor, just use wrong value in kubelet summary stats.

**Comment by mdshuai** [comment]
My env:
[root@ip-172-18-5-33 ~]# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 74
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-202:2-18194008-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/docker-vg/docker-data
 Metadata file: /dev/docker-vg/docker-metadata
 Data Space Used: 5.902 GB
 Data Space Total: 15.03 GB
 Data Space Available: 9.126 GB
 Metadata Space Used: 5.644 MB
 Metadata Space Total: 1.095 GB
 Metadata Space Available: 1.089 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Execution Driver: native-0.2
Logging Driver: journald
Plugins: 
 Volume: local
 Network: bridge null host
 Authorization: rhel-push-plugin
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 2
Total Memory: 7.389 GiB
Name: ip-172-18-5-33.ec2.internal
ID: 7GKJ:6VQY:QQCJ:455Q:WC66:22YV:SD4V:42AJ:HW4E:BTTS:ADZK:PZQX
WARNING: bridge-nf-call-ip6tables is disabled
Registries: docker.io (secure)

**Comment by derekwaynecarr** [comment]
@mdshuai -- i feel really dumb now, I see the problem, thanks!

**Comment by derekwaynecarr** [comment]
I am bumping this to p0 as the incorrect value mapping would cause unstable nodes when using eviction based on inodes for imagefs.

**Comment by pwittrock** [comment]
@derekwaynecarr Thank you.  Please make sure that this issue is updated with an ETA for a complete resolution before the burndown meeting tomorrow morning so that we can quickly look at it and move on.

Please also include any other details we might need to plan around.

**Comment by derekwaynecarr** [comment]
@pwittrock - pr is in the queue and tagged.

**Comment by pwittrock** [comment]
Wonderful
