### ISSUE TITLE
LDAP support for k8s authentication

### ISSUE THREAD

**Issue by miradam** [kubernetes/kubernetes#31517]
Hello, is LDAP authentication plugin envisioned for user accounts authentication?

**Comment by luxas** [comment]
cc @kubernetes/sig-auth

**Comment by liggitt** [comment]
auth proxy support is more likely to be added than direct integration with LDAP

the API server would perform mutual TLS auth (to verify the request was via a trusted proxy), then extract user info from headers on the request

**Comment by liggitt** [comment]
Support for recognizing user information from headers sent by an authenticating proxy (which could use LDAP to authenticate if it wanted to) was added in 1.5
