### ISSUE TITLE
Proposal: Sending secrets to the ImagePolicy Admission Controller Backend

### ISSUE THREAD

**Issue by ecordell** [kubernetes/kubernetes#31524]
# Motivation

Currently the only data sent to the ImagePolicy webhook backend is the image name or digest, and a subset of the pod annotations (matching `*.image-policy.k8s.io/*`). There are a number of cases where a webhook backend will need to authenticate itself with other services - in these cases it would be nice to store those secrets in kubernetes and send them to the backend when needed.
# Proposal

Any pod annotations with keys that match `*.image-policy.k8s.io/secret/*` will be treated as references to secrets (the value will be ignored). The secrets api will be queried for secrets that match the annotation key exactly. If found, the value of the annotation will be populated with the actual secret, which will then be included in the request to the webhook backend.

Note that this means that only secrets explicitly labelled for use in the webhook backend will ever be used, since they must match `*.image-policy.k8s.io/secret/*`. This proposal does not allow arbitrary secrets to be sent to the backend.

No changes are required to any APIs. 
# Alternate Solutions

There are a couple of alternate solutions:
- Secrets could be encoded directly in a pod annotation and be sent to the backend without any changes to kubernetes. This is not ideal because it couples the lifetime of the secret to that of the pod, unlike kubernetes secrets. It also means that anyone with the pod spec also has the secrets.
- It could be the responsibility of the user to associate secrets with images directly in the webhook backend. This is not ideal because it creates two separate secret management systems.

pinging @Q-Lee @deads2k

**Comment by zhouhaibing089** [comment]
I would say the the secret name is a common case, so eventually it would become a field in `ImageReviewSpec`, but yeah, I understand that features generally go through annotation firstly.

Though I have one question still, is it necessary to attach the secrets as annotations? IIUC, when user would like to run some private images in k8s, user must provide the pull secrets in their [podspec](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1558).

**Comment by deads2k** [comment]
@kubernetes/sig-auth 

The point of our secrets API is to make secrets available to the kubelet and to the pod, I'm don't think our secrets should be used as a general store of "this is a useful secret".

I think I'd expect that an ImagePolicy evaluation API server would have a set of credentials that identified the ImagePolicy API server, not the same credentials that were used by a pod or a kubelet.  In what cases would these things overlap?

**Comment by ecordell** [comment]
> The point of our secrets API is to make secrets available to the kubelet and to the pod, I'm don't think our secrets should be used as a general store of "this is a useful secret".

If that's the case full-stop, then I suppose that's the end of this proposal. That wasn't my understanding of the secrets API, though.

> I think I'd expect that an ImagePolicy evaluation API server would have a set of credentials that identified the ImagePolicy API server, not the same credentials that were used by a pod or a kubelet. In what cases would these things overlap?

The cases we're considering do not use the *same* credentials (e.g. image pull secret) as the pod, but rather there are additional secrets that should be associated with a pod.

For example: you have a restricted OAuth token for read-only access to image scanning data for a particular image. This is not the image pull secret, but it is specific to an image. 

The ImagePolicy evaluation server should not authenticate with another service and have complete access to all data it needs; ideally it should be granted access to only the small subset of data that it needs to fulfill the particular admission request. 

There are other ways to address this as outlined in the alternatives section, but it seemed like a good fit for the secrets API. 

> Is it necessary to attach the secrets as annotations? IIUC, when user would like to run some private images in k8s, they already specify the pull secrets in their PodSpec.

It could be implemented this way as well; I do think that there should be restrictions on what is sent to the backend though (i.e. not all pull secrets get sent, maybe matching a certain prefix).

> The ImageReviewContainerSpec is an array, How will the annotations map with each ImageReviewContainerSpec, when each of the image requires different secret.

I think this is up to the user/backend. The annotation could include the image name or digest, for example.

**Comment by liggitt** [comment]
I also would not expect user-level secrets to have to be given to the image policy evaluator... why wouldn't the evaluator have its own access to the image registries to make a run/don't-run determination?

More generally, I think we should avoid distributing secrets more places, especially via annotations (which are really hard to policy).

Finally, the mechanics of this specific proposal don't work, since secrets are multi-valued and can contain values larger than the maximum allowed annotation size.

**Comment by deads2k** [comment]
> The ImagePolicy evaluation server should not authenticate with another service and have complete access to all data it needs; ideally it should be granted access to only the small subset of data that it needs to fulfill the particular admission request.

I don't think that distributing a secret to the ImagePolicy evaluator is better.  A compromised ImagePolicy evalutor could simply remember the secret it got.  In such a case, instead of rotating only the ImagePolicy evaluator token, you've now got to find every secret you ever distributed to it and rotate those, so it may even be worse.

**Comment by zhouhaibing089** [comment]
> why wouldn't the evaluator have its own access to the image registries to make a run/don't-run determination?

it could, but such ability requires some super user which has super permission to reach all the private repos, no matter the full access or some subset of access..

> the mechanics of this specific proposal don't work, since secrets are multi-valued and can contain values larger than the maximum allowed annotation size.

IIUC, it could be avoid if we know which `KeyPath` that is going to be used.

**Comment by zhouhaibing089** [comment]
> A compromised ImagePolicy evalutor could simply remember the secret it got. In such a case, instead of rotating only the ImagePolicy evaluator token, you've now got to find every secret you ever distributed to it and rotate those, so it may even be worse.

Fair enough!

**Comment by ecordell** [comment]
It's not just about protecting against a compromised image policy server.
Secrets can be compromised in other ways as well - in that case, it's
useful to not have full access credentials exist at all.

**Comment by liggitt** [comment]
> in that case, it's useful to not have full access credentials exist at all.

agree, and some user-level secrets could be full access credentials. having a credential for the evaluator lets you give it exactly the permissions needed (probably read-only, etc)

**Comment by zhouhaibing089** [comment]
@liggitt without user level secrets, then there must be a credential to be able do, like read-only requests to all of the user images, it does not sounds good as well. people would feel that someone  accesses my private area without any permission from them.

**Comment by zhouhaibing089** [comment]
@deads2k @liggitt Here is what in my mind:

If the image policy evaluator needs to do some check on the image, and it requires some credential to do that sometimes, then either image policy evaluator itself has some powerful credential which could be grant to do things on all the repositories, or the image policy evaluator has been told to use which credential. of course we are talking about the second one, I absolutely understand the concern that you have on secrets distribution, but let's think about this, it is sort of problem that we need to solve.

1.   Let's think the first option through, say that the image policy evaluator is able to do such checks without any notification on the users, it is not acceptable.
2.  The main concern here is about secrets compromise, yeah, sure, it should never happen.
3.  When the credential goes outside, it must be shorttime-lived, so let's say the apiserver(I mean the admission part) has some abilities to ask for some shorttime-lived token, then I think this problem is gone.

**Comment by liggitt** [comment]
I don't think we can assume the API server will have the ability to mint short lived tokens for external image registries

**Comment by zhouhaibing089** [comment]
Well, sorry that I did not make it clean, I did not mean it is able to **mint**. But if it is possible to be a plugin to say, there is a `TokenGetter`, whenever the `ImageReviewSpec` is going to be sent, it sends along with a call to `TokenGetter`, so if someone uses registry A, and it do support to fetch a short lived token, then he just go and implement a `TokenGetter`.

**Comment by erictune** [comment]
I'd expected that in a typical implementation, the webhook backend is either be part of or trusted by the image scanning service.  In that case, it does not need an oauth token to get scanning data.  

Perhaps the OP can say more about why per-image secrets are needed rather than blanket authorization for the webhook to read image scanning data.

**Comment by ecordell** [comment]
> I'd expected that in a typical implementation, the webhook backend is either be part of or trusted by the image scanning service. In that case, it does not need an oauth token to get scanning data.
>Perhaps the OP can say more about why per-image secrets are needed rather than blanket authorization for the webhook to read image scanning data.

This doesn't quite track for me - access to images is restricted with per-image pull secrets; the type of information required to make admission decisions is equally private in my mind (the webhook backend could even actually pull an image and running some analysis on it before making a decision). 

In any case, it sounds like we should revisit one of the proposed alternate designs:

> It could be the responsibility of the user to associate secrets with images directly in the webhook backend.

In the case where the webhook backend is running in kubernetes, secrets could (if so desired) still come from the kubernetes secrets api, but in general it would be the responsibility of the webhook backend to gather the correct authorization ahead of time. @zhouhaibing089 does this work for you?

**Comment by zhouhaibing089** [comment]
Firstly, I believe it is true that the webhook backend would be running on kube, but it looks like a little bit strange that the webhook backend is able to gather secrets ahead of time.

Secondly, when looking at this problem again, I feel it is not about how kube transfer the secrets(true secrets or short lived token) to the webhook backend, instead it is about how user would grant the webhook backend permission to fetch some informations.

But I am not sure the implementation detail, I would like to see what @ashw7n and @chengyli thought.

**Comment by zhouhaibing089** [comment]
> the webhook backend is either be part of or trusted by the image scanning service. In that case, it does not need an oauth token to get scanning data.

As far as I know, at least, it is true for [Quay](quay.io), that the image scanning service itself does not have an api, it just do the scanning, and post scanning status to the registry, so it is hard to say integrating the webhook with the image scanning service.

But yeah, that reminds me of the ability to access all the images, the Clair itself gains a private key from registry, and then, it is able to do scanning stuff.

**Comment by zhouhaibing089** [comment]
> Perhaps the OP can say more about why per-image secrets are needed rather than blanket authorization for the webhook to read image scanning data.

I did not follow this clearly. does OP mean a name of some one?

**Comment by ecordell** [comment]
> the image scanning service itself does not have an api

The image scanning service has an api and is [open source](https://github.com/coreos/clair) as well.

> does OP mean a name of some one?

OP = Original Poster, in this case me.

**Comment by zhouhaibing089** [comment]
> The image scanning service has an api and is open source as well.

K, thanks, looks like I need to do some more study there.. I saw there is an endpoint at registry side to retrieve scanning result, but forget to check about the Clair api..

**Comment by erictune** [comment]
> access to images is restricted with per-image pull secrets;

That is one possible way to gain access to images, and it was added early in the project before we had thought a lot about image policy.

I think today, many if not most clusters are built with the following assumptions:

1. images do not contain secrets, Kubernetes secrets and configmaps do this.
2. everyone who creates pods on the cluster is trusted enough to have read access to the image repository.  
3. People do not put images in random repositories.  They typically use a single repo for the cluster, or maybe a single main repo, which has some access controls, plus some images from fully public repos (Docker Hub, etc).

If these assumptions hold for your use case, then I think your cluster does not need to use imagePullSecrets, and you can just say the image policy backend will reject images that it cannot pull.

I'm not claiming that all clusters meet these: openshift does things differently, and uses imagePullSecrets in conjunction with serviceAccounts.  But the above should apply to a lot of cases.

If your cluster does not meet these assumptions, then we should talk more about why not.

In case you don't know about alternatives to imagePullSecretsSee, check out the instructions for using [GCR](http://kubernetes.io/docs/user-guide/images/#using-google-container-registry), [ECR](http://kubernetes.io/docs/user-guide/images/#using-aws-ec2-container-registry), or [another repo to be accessible for all nodes](http://kubernetes.io/docs/user-guide/images/#configuring-nodes-to-authenticate-to-a-private-repository).

**Comment by zhouhaibing089** [comment]
@erictune I thought that I get your point here.

> images do not contain secrets, Kubernetes secrets and configmaps do this.

from the perspective of k8s, then yes, I personally do not create private repos.. but it looks like more a question why private repos exists, cases that I can image:

1.  if the application provided by the image is for selling, like some paid services, the for sure, it could not go to public.
2.  security concern, I think it is really not an expectation that everyone would be able to see the vulnerabilities of my images.

I have to admit the time before using k8s as the deployment platform, we have a centralized repo, and there is agent on each VM, the agent pulls the code(tarballs, binaries, etc) directly from the repo without any authentication.

**Comment by zhouhaibing089** [comment]
I think case is a little bit different when migrating to use docker images.

1.  the repo is no longer centralized, each team maintains repositories by their own.
2.  the kind of application that docker image would run is more diversity, like some small applications or half-ready programs, for example, I am developing an application, and it is still buggy, I may need a way to prevent others grasping my code and give it a real run, but I need it on registry so I can do some test..

I think this is the case why private image would still be there, people may build images, and deploy on dev k8s cluster, and iterate quickly with testing/fixing, and making it private before it goes ready. What do you think? @erictune

**Comment by deads2k** [comment]
> I think this is the case why private image would still be there, people may build images, and deploy on dev k8s cluster, and iterate quickly with testing/fixing, and making it private before it goes ready. What do you think? @erictune

I still think that you'd want to have different identities to distinguish between individual users and the agent running whatever check you intend to have.  Distributing secrets that identify userA to a different, external entity so that it can pretended to be userA instead being the user for that separate entity seems weird.  

This isn't a case where the core platform is trying to protect direct access to an image you may not be able to access (pull secrets), this is closer to the case of an external image scanner.

**Comment by Q-Lee** [comment]
The ability to authenticate yourself to a backend already exists. IIUC, the webhook code uses the kube client code, and can authenticate itself any way kubectl does.

**Comment by ecordell** [comment]
> everyone who creates pods on the cluster is trusted enough to have read access to the image repository.

I don't believe this would be the case with multi-tenant workloads. Should that not be a consideration?

**Comment by zhouhaibing089** [comment]
@Q-Lee @ecordell Yeah, it would not be the case with multi-tenant workloads.

When I am looking back now, we already have an authenticator based on webhook call, we already pass the token along with this request, see here: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authenticator/token/webhook/webhook.go#L82

@deads2k thoughts?

**Comment by deads2k** [comment]
> @Q-Lee @ecordell Yeah, it would not be the case with multi-tenant workloads.
> 
> When I am looking back now, we already have an authenticator based on webhook call, we already pass the token along with the request, see here: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authenticator/token/webhook/webhook.go#L82
> 
> @deads2k thoughts?

I think we want to distinguish access by users from access by infrastructure.  Users are *not* trusted to pull any image.  Image scanning infrastructure *is* trusted to pull any image.  I think that's a fair assumption and I'd further claim that the image scanning infrastructure identity is important to keep distinct.  I don't think we should send in-cluster secrets to external systems, when those systems should have their own identities for performing scan jobs.

**Comment by ericchiang** [comment]
> Users are not trusted to pull any image. Image scanning infrastructure is trusted to pull any image.

Having discussed this with @ecordell I think the issue is that the image scanning infrastructure _isn't_ trusted to pull images. User are trusted to scan their own images, but need some way of sharing that trust with the infrastructure.

**Comment by deads2k** [comment]
> Having discussed this with @ecordell I think the issue is that the image scanning infrastructure isn't trusted to pull images. User are trusted to scan their own images, but need some way of sharing that trust with the infrastructure.

If you do this, not only does the infrastructure have the power to scan the images (you just sent them info), they also have the power to masquerade as someone else (you just sent them the secret), and you've lost auditability of access.

If you say that "the infrastructure doesn't have the power to read your images", but you turn around automatically send them that power along with your credentials, I'm not sure how much was gained.  In addition, any successful MITM just got credentials they wouldn't've had otherwise.

**Comment by ecordell** [comment]
> If you say that "the infrastructure doesn't have the power to read your images", but you turn around automatically send them that power along with your credentials, I'm not sure how much was gained. In addition, any successful MITM just got credentials they wouldn't've had otherwise.

Just to clarify the case being discussed: I really want to say "the infrastructure doesn't have the power to read _all_ of your images", and furthermore the credentials in question would not necessarily be the same; they could be time-restricted and read-only, for example.

In any case: the solutions presented here are essentially service-to-service authentication, which could be fine in many cases.

There are other cases where that may not be the correct model. There are scenarios where we may need to involve a user in authorization decisions, similar to a three-legged OAuth flow. I actually think this is not an issue under the current design: the image policy backend can return an error with instructions (e.g. "authorize the backend to access image xyz, run command abc to do so, and re-run") and the user can do whatever dance is necessary at that point to authorize the backend to whichever other service, be that an image registry or another service. That could further be wrapped by other tooling to obtain authorization ahead of time.

Does this sufficiently resolve this discussion?
