### ISSUE TITLE
kubectl delete all --all no longer deletes a useful all

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#31527]
For example, it does not delete deployments or replica sets.

/cc @kubernetes/rh-cluster-infra @kubernetes/kubectl @smarterclayton

**Comment by deads2k** [comment]
Someone tried to fix this and the pull was reverted.  I don't remember why.

**Comment by deads2k** [comment]
Here's the current pull: https://github.com/kubernetes/kubernetes/pull/30199

**Comment by smarterclayton** [comment]
It broke kubemark
