### ISSUE TITLE
node e2e: confusing message about whether a build passed or not

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#31538]
I'm seeing some builds passed with test failures in it.

For example, 

In https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/31478/node-pull-build-e2e-test/21439/, the build result is success, but there is one test failure. Bugs were filed by the merge-bot for the build failure, yet the PRs weren't affected by it because the overall result is success.

Snippet from the build.log:
```
Summarizing 1 Failure:

[Fail] [k8s.io] Pods [It] should contain environment variables for services [Conformance] 
/var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2118

Ran 99 of 131 Specs in 640.199 seconds
SUCCESS! -- 99 Passed | 0 Failed | 0 Pending | 32 Skipped 

Ginkgo ran 1 suite in 10m42.628259298s
Test Suite Passed
```

I doubt that this is working as intended, but if it was, we should be more clear about it.

/cc @Random-Liu @kubernetes/goog-node

**Comment by yujuhong** [comment]
@Random-Liu solved the mystery.

@lavalamp added a retry feature in ginkgo to run the test again if it failed once. The test in question failed once, but passed in the next attempt. This is indeed working as intended.

**Comment by Random-Liu** [comment]
This is because we set `--flakeAttempts=2` in the pr builder https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/jenkins/jenkins-pull.properties#L6.
Once the test fails, it will try once more, if the other time it passes, it will still report success. :)

**Comment by vishh** [comment]
That's awesome. Does this mean that we might not mark a test as flaky
unless it fails 3 times in a row?

**Comment by yujuhong** [comment]
> That's awesome. Does this mean that we might not mark a test as flaky
> unless it fails 3 times in a row?

I don't know if there is an established guideline, but merge-bot fearlessly files new bugs on every failure nonetheless...

**Comment by mtaufen** [comment]
Is there a reason we wouldn't want to know every time a test flakes? It seems like it would be good to know of every failure, even though we are helping people out by reducing the amount of manual re-test requests.

**Comment by yujuhong** [comment]
> Is there a reason we wouldn't want to know every time a test flakes? It seems like it would be good to know of every failure, even though we are helping people out by reducing the amount of manual re-test requests.

I agree. I wasn't trying to suggest that awareness of flaky tests is not important. It allows some test to stabilize without affecting others.

**Comment by lavalamp** [comment]
These still need attention. I'm just letting PRs merge in spite of them. The issues still need to be fixed! So @vishh no 1 failure is all it takes and that's by design.

**Comment by vishh** [comment]
That's cool! Thanks for clarifying @lavalamp
