### ISSUE TITLE
node e2e not collecting kubelet logs for gci-dev-*

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#31537]
Pick a random run from node-pull-build-e2e-test:
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/pull/31321/node-pull-build-e2e-test/

Content of the kubelet log for the gce-dev* image contains only one line:
```
Running as unit kubelet-1792173729.service.
```

Seems like a regression?

Relevant code for grabbing the logs: https://github.com/kubernetes/kubernetes/blob/afb780d4ee1b6587ed107c4c74bf4723da7955f1/test/e2e_node/services/services.go#L229
On GCI, we should be getting the logs from journald, but somehow we ended up copying the "kubelet.log" from the working directory.

**Comment by Random-Liu** [comment]
Looking into it now. :)

**Comment by yujuhong** [comment]
Ah...it's the same for coreos images too. All journald systems have the same issue.
