### ISSUE TITLE
rkt: When using the rkt runtime, images are pulled too aggressively with imagepolicy always

### ISSUE THREAD

**Issue by euank** [kubernetes/kubernetes#31544]
This is really a [rkt issue](https://github.com/coreos/rkt/issues/2937), but I think it's worth tracking in the Kubernetes repository as well.

Essentially when the remote docker image has not changed at all, rkt will still download all the bytes again for `--no-store` fetch (which is now the default behaviour).

This is especially noticeable if the image is large and the tag is latest because the default `ImagePullPolicy` of `IfNotPresent`, for latest, is interpreted as `always`.

The action items we have on the Kubernetes side:
- [x] Document for v1.4 in known-issues
- [ ] Update recommended/required rkt version once this issue is fixed in upstream rkt

cc @kubernetes/sig-rktnetes

**Comment by yifan-gu** [comment]
Updating 1.4 issue https://github.com/kubernetes/kubernetes.github.io/pull/1109

**Comment by euank** [comment]
Image policy is handled differently via CRI, closing this as stale since rktnetes is being replaced by the CRI [rktlet](https://github.com/kubernetes-incubator/rktlet/).

/close
