### ISSUE TITLE
Add Celery-RabbitMQ back to Kubernetes example

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#31549]
Forked from https://github.com/kubernetes/kubernetes/issues/30308

Celery-RabbitMQ example is completely broken for last many days on all supported os distro.  To stop the bleeding edge, https://github.com/kubernetes/kubernetes/pull/31475  was merged which removed this completely. 

cc/ @luxas @luxas

**Comment by dchen1107** [comment]
cc/ @erictune

**Comment by erictune** [comment]
We are going to phase out the "examples" directory.

For help setting up specific applications, we will direct people to kubernetes/charts.  If you want it to be easy to setup rabbitmq, I'd suggest contributing there.

For examples which illustrate features of kubernetes, we will host those on k8s.io, and they will be focused on teaching kubernetes concepts, not on broad coverage of applications.

Also, a private blog post is always an option.
