### ISSUE TITLE
Implement ScheduledJob Reaper

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#31553]
We need a scheduledjobs reaper for `kubectl delete`, so that when an SJ is deleted, its jobs and pods are deleted too. 

@erictune @soltysh

**Comment by janetkuo** [comment]
The bug #31009 makes removing sj's jobs even harder...

**Comment by AdoHe** [comment]
@janetkuo I will fix the bug #31009 asap.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @janetkuo @AdoHe @soltysh

**Comment by soltysh** [comment]
Not a blocker, moving the milestone to 1.6.

**Comment by AdoHe** [comment]
@soltysh @janetkuo an alternative approach is use GC controller instead of reaper, wdyt?

**Comment by soltysh** [comment]
@AdoHe yes, this will be implemented as GC, no more reapers.

**Comment by peay** [comment]
@soltysh I may be able to pick this up and send a PR once #40932 is merged if no one is working on this.

As far as I understand, currently:
- `kubectl` manually reaps the pods when deleting a job (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/stop.go)
- `kubectl` does not delete the jobs when deleting a cronjob (i.e., no reaper for this case -- the jobs stay)
- the controller manually reaps the pods when doing a replace (or cleanup in #40932)

If this is correct, would the following modifications work?
- kubectl and the controller do not reap any more -- they just delete the job or the cronjob:
  - requires to remove the reaper for jobs
  - nothing to do for cronjob
- GC controller deletes jobs that have a non-existing cronjob as `CreatedByAnnotation`
- GC controller deletes pods that have a non-existing job as `CreatedByAnnotation`
  - this can extend `gcOrphaned` which currently checks for non-existing nodes

**Comment by soltysh** [comment]
@peay actually before implementing this for CronJobs, I was thinking of moving the current Job reaper server side. CronJob do not have reaper implemented as of yet. 

Having said that, I'm not sure if this is doable for 1.6. We have a code freeze in ~2 weeks, and having both seems like a quite an effort to have it done for now. Finally, I was hoping to leave that one for myself, if you don't mind, with a plan to start working on it in February :)

**Comment by peay** [comment]
OK, sure!

**Comment by pwittrock** [comment]
@soltysh @peay @janetkuo Can we move this to milestone v1.7?

**Comment by kargakis** [comment]
This is implemented in https://github.com/kubernetes/kubernetes/pull/42177 but I don't know whether the PR will make 1.6.

Job server-side reaping is https://github.com/kubernetes/kubernetes/pull/42176

**Comment by soltysh** [comment]
It should land in 1.6 it's on my todo list for review today. It was approved before the freeze.

**Comment by ethernetdan** [comment]
@soltysh is there a resolution here? We need to triage this as release blocking or not release blocking for v1.6.

**Comment by janetkuo** [comment]
@ethernetdan This is not release blocking. The fix was implemented server-side #42177 but won't make it to 1.6.

**Comment by ethernetdan** [comment]
@janetkuo thanks! moving to 1.7

**Comment by soltysh** [comment]
Yup, was about to write that.

**Comment by kargakis** [comment]
@soltysh this is fixed now, right?
