### ISSUE TITLE
docker_manager_test unit test needs cleanup

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#31550]
The [docker_manager_test](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker_manager_test.go) needs some refactoring. A few of the problems:
- Rampant code duplication (the test is over 2500 lines long)
- Fragile tests depending on lots of internal functionality

Cleanup up the test properly may require exposing a few more interfaces from the DockerManager, or just providing better fakes.

**Comment by nebril** [comment]
I will give it a shot if no one is working on this.

**Comment by tcharding** [comment]
Is this an issue still? I cannot find reference to a 'docker manager' within the kubelet code. The link above is broken.

thanks
