### ISSUE TITLE
BeforeSuite: Failed to setup provider config

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#31560]
Multiple issues in the BeforeSuite failure bug (#30075). Splitting this particular failure mode out.

Aug 15 14:39:13.884: Failed to setup provider config: Error building GCE/GKE provider: Get https://www.googleapis.com/compute/v1/projects/k8s-e2e-gke-staging-parallel/global/networks?alt=json: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: net/http: TLS handshake timeout

Aug 23 21:51:14.760: Failed to setup provider config: Error building GCE/GKE provider: googleapi: Error 500: Internal Error, internalError

Aug 25 16:06:00.946: Failed to setup provider config: Error building GCE/GKE provider: Get https://www.googleapis.com/compute/v1/projects/k8s-e2e-gke-staging-parallel/global/networks?alt=json: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: dial tcp 74.125.69.84:443: i/o timeout

Comment with more details: https://github.com/kubernetes/kubernetes/issues/30075#issuecomment-242576929

**Comment by lavalamp** [comment]
Randomly asking @spxtr to triage since he was on the bug this came from

**Comment by spxtr** [comment]
This looks like a flake in `CreateGCECloud` which is a real bother. We call it 25 times in parallel and in one of the failing cases 3/25 failed. It doesn't seem like it's a problem on our end, though, unless we're calling some non-concurrency-safe function.

**Comment by dchen1107** [comment]
Based on @spxtr's comment, it looks like a real failure, and affects cluster lifecycle.

**Comment by mikedanese** [comment]
Histogram of error types shows that the majority of errors happen contacting https://accounts.google.com/o/oauth2/token
```
      2 Error building GCE/GKE provider: Get https://www.googleapis.com/compute/v1/projects/k8s-e2e-gke-staging-parallel/global/networks?alt=json: oauth2: cannot fetch token: 502 Bad Gateway
      1 Error building GCE/GKE provider: Get https://www.googleapis.com/compute/v1/projects/k8s-e2e-gke-staging-parallel/global/networks?alt=json: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: dial tcp 74.125.69.84:443: i/o timeout
      2 Error building GCE/GKE provider: Get https://www.googleapis.com/compute/v1/projects/k8s-e2e-gke-staging-parallel/global/networks?alt=json: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: net/http: TLS handshake timeout
      5 Error building GCE/GKE provider: Get https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce/global/networks?alt=json: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: EOF
     71 Error building GCE/GKE provider: Get https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce/global/networks?alt=json: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: net/http: TLS handshake timeout
      1 Error building GCE/GKE provider: Get https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gke-ci/global/networks?alt=json: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: dial tcp 74.125.202.84:443: i/o timeout
      1 Error building GCE/GKE provider: Get https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gke-slow/global/networks?alt=json: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: net/http: TLS handshake timeout
      1 Error building GCE/GKE provider: googleapi: Error 500: Internal Error, internalError
      1 Error building GCE/GKE provider: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
