### ISSUE TITLE
Provision Kubelet server certificates with the certificates API

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#31563]
ref #11816

cc @gtank @yifan-gu

**Comment by awly** [comment]
https://github.com/kubernetes/kubernetes/blob/5e8b64f990a4274e8f2d9a6bea05b8beb6214d2b/pkg/kubelet/apis/kubeletconfig/v1beta1/types.go#L170 and Alpha feature implementing this is available.

/close
