### ISSUE TITLE
Setup pre-submit tests for the new container-vm in GCE

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#31565]
K8s on GCE will be using the [upgraded version of container-vm](https://cloud.google.com/compute/docs/containers/vm-image/). Testing for the new container-vm is not adequate as-is. Specifically the following tasks are critical:
1. Add per-pr tests that use the new container-vm
2. Add relevant tests that validate the new container-vm to the submit queue as non-blocker initially.
3. Add relevant per-pr and CI test that validate the new container-vm as submit-queue blockers. We might want to wait for at-least a week and ensure that the flake %tage with the new container-vm is not higher than the older version before making this change.

What is needed to clone an existing test to run with the new container-vm image?
Set `KUBE_OS_DISTRIBUTION=gci` instead of `KUBE_NODE_OS_DISTRIBUTION=debian`.

Per-pr test configs are located in the test-infra repo [here](https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull.yaml).
The relevant tests are the ones that run e2e. Builds, unit & integration tests do not matter.

The submit-queue configs are [here](https://github.com/kubernetes/contrib/blob/838c70d6f7b36a3f601d4d2150e47556b32fa443/mungegithub/submit-queue/deployment/kubernetes/configmap.yaml). Changes to submit-queue might have to be pushed manually.

@mtaufen @matchstick @dchen1107 

cc @lavalamp in case he has more thoughts on how tests needs to be added to the submit queue.

**Comment by vishh** [comment]
We might have to add tests for release-1.3 & release-1.4 branches as well.

**Comment by lavalamp** [comment]
> KUBE_OS_DISTRIBUTION=gci

Huh? The title says container-vm?

Do we really need to double our testing? Why not just switch everything over? Is this needed for 1.4? Can we just switch over the 1.4 tests in that case? Is this a GKE/GCE difference and if so can we just switch over the GKE tests?

**Comment by vishh** [comment]
> Huh? The title says container-vm?

gci is the key-word used to represent the upgraded container-vm. I can explain more offline.

> Do we really need to double our testing? 

Until the old container-vm is officially removed from GKE we w ill have to test. Over the next couple of months, we can scale down testing on old container-vm to just the critical tests maybe.

> Why not just switch everything over? 

Users can still use both versions. They need time to transition over. 

> Is this needed for 1.4? 

Yes.

> Can we just switch over the 1.4 tests in that case? 

Not possible for reasons mentioned above.

> Is this a GKE/GCE difference and if so can we just switch over the GKE tests?

This is applicable to both GCE & GKE. GKE intends to track GCE. We can go over the list of tests and possibly weed out un-necessary duplicates.

**Comment by dims** [comment]
switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree)

**Comment by vishh** [comment]
@mtaufen isn't this done?

**Comment by mtaufen** [comment]
Yeah we have PR builder jobs for GCI and the submit queue blockers run against GCI. This can be closed.
