### ISSUE TITLE
Standardize extension patterns

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#31571]
This occurred to me when discussing with @davidopp and has come up in multiple contexts recently. Maybe this could be split into at least 2 issues, but I'll start with 1.
1. We are developing a pattern by which we allow people to plug in their own controllers for our objects, by specifying some kind of "type" that indicates which controller has responsibility, and sometimes what policy to apply, as well. Examples:
   - [Multi-scheduler support](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/multiple-schedulers.md), currently via annotation on Pod. 
   - Ingress, currently via annotation on Ingress.
   - Deployment, discussed implementation using unsupported rollout strategies
   - HorizontalPodAutoscaling, discussed using annotations
   - StorageClass, supports multiple classes, not sure about multiple provisioners
   - Maybe NetworkPolicy applies
   - FlexVolume
   - LoadBalancer (cloud-provider-specific)
2. Sometimes we need to plumb custom parameters down to these controllers. A list of key-value pairs is not awesome. This problem is more acute for ThirdPartyResource, and we're going to have it with the Service Catalog. I suggest we adopt a schema description mechanism, such as JSONSchema. We don't need the whole REST operation side of Swagger/OpenAPI.

cc @thockin @smarterclayton @lavalamp @davidopp

**Comment by pmorie** [comment]
FTR, storage class supports multiple provisioners

**Comment by pmorie** [comment]
Another issue in this space: TPR is namespaced, while not all extension controllers are (example: storage class is global)

**Comment by m1093782566** [comment]
I think Annotation is useful for users defining their own need flexibly, like strategy, attribute and so on. It can reduce the work load to maintain them as API Resource type in `types.go`. However, the current `map[string]string` Annotation key-value pair also has its limitations, it's unable to describe more complicated scenarios.

**Comment by davidopp** [comment]
@smarterclayton It sounds like what you're talking about might be closer to the "opaque integer resource" idea (#28312) whereas I think @bgrant0607 was talking more about some kind of delegation or partitioning mechanism to direct requests to the proper instance of something that has multiple instances (most likely one "out-of-the-box" instance and one or more custom instances). Or do you see these are more similar than I do?

**Comment by bgrant0607** [comment]
In the long run, I think all APIs that need this capability should use fields. Annotations aren't discoverable.

Perhaps we should even ask the question what resources won't ever need this?

**Comment by smarterclayton** [comment]
I mentioned HPA because while discussing it it was clear the pattern for custom metrics resembles - core API object, many controllers, preferred controller.  An object that can be used by many clients to coordinate may not understand all the clients, and while we might have a first party field (CPU) a totally generic field (GenericMetricReference) which is opaque to clients can actually be the signal to the controller to act on it.

  Ie the presence of generic metric "biz.metric.1023" is a signal to an autoscaler extension controller in the same way that scheduler annotation may put you into a queue on an extension scheduler.  That controller would be outside the system - HPA controller would observe the totally generic metric (as distinct from heapster opaque generic metric) and do nothing.

**Comment by bgrant0607** [comment]
cc @erictune

**Comment by bgrant0607** [comment]
Other recent examples where this would be useful:
* Service broker, being discussed as part of the service catalog SIG
* Service account token generation, for generating other types of tokens
* DaemonSet updates (#31693), similar to the Deployment use case

**Comment by kargakis** [comment]
cc @mfojtik

**Comment by bgrant0607** [comment]
Making a high-level proposal in the core/layers doc extensions section:
https://docs.google.com/document/d/1XkjVm4bOeiVkj-Xt1LgoGiqWsBfNozJ51dyI-ljzt1o/edit#

**Comment by thockin** [comment]
We have a pretty well established pattern based on CRDs now.  Closing old issues is fun :)
