### ISSUE TITLE
PetSet: Is there any plan when the PetSet API will be available?

### ISSUE THREAD

**Issue by shouhong** [kubernetes/kubernetes#31581]
I tried PetSet in Kubernetes 1.3 and it is wonderful! But I can only create Pet Sets with kubectl. Is there any plan when the PetSet API will be available? Thanks!

**Comment by luxas** [comment]
PetSet API is available, but it seems it's not well-documented: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/types.go#L31

Open an issue on kubernetes/kubernetes.github.io if you want to add them to the site
