### ISSUE TITLE
Error during cleaning up orphaned pods

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/kubernetes#31596]
Following discussion in https://github.com/kubernetes/kube-deploy/issues/192 I'm creating this issue to clear some things and to work on a solution for possible issue:

> @luxas Okay, it seems, that me and @floreks have found out what causes the issue with cleaning up orphaned pods.

>On newest master version we're no longer able to reproduce it using steps, that I've previously described, but the issue still occurs. Simplest way to reproduce it is to clean and restart `etcd` and then re-run `kubelet`. When `kubelet` is starting it tries to cleanup orphaned pod directories:

>`pkg/kubelet/kubelet.go:1708 [master]`
``` go
// cleanupOrphanedPodDirs removes the volumes of pods that should not be
// running and that have no containers running.
func (kl *Kubelet) cleanupOrphanedPodDirs(

>    // ...

>	found, err := kl.listPodsFromDisk()
	if err != nil {
		return err
	}
	errlist := []error{}
	for _, uid := range found {
		if allPods.Has(string(uid)) {
			continue
		}
		if podVolumesExist := kl.podVolumesExist(uid); podVolumesExist {
			// If volumes have not been unmounted/detached, do not delete directory.
			// Doing so may result in corruption of data.
			glog.V(3).Infof("Orphaned pod %q found, but volumes are not cleaned up; err: %v", uid, err)
			continue
		}
		glog.V(3).Infof("Orphaned pod %q found, removing", uid)
		if err := os.RemoveAll(kl.getPodDir(uid)); err != nil {
			glog.Infof("Failed to remove orphaned pod %q dir; err: %v", uid, err)
			errlist = append(errlist, err)
		}
	}
	return utilerrors.NewAggregate(errlist)
}
```

>As you can see it gets pods from the disk (by default from `/var/lib/kubelet/pods`) and as they don't have any reference in `etcd` they are marked to be removed. Before removal it is checked if they have any mounted volumes (in `podVolumesExist` method). However, we think (check following listing), that `podVolumesExist` checks only if volumes entries exist in `ectd`.

>```
$ mount
...
tmpfs on /var/lib/kubelet/pods/bd3f9c64-69d9-11e6-ac66-901b0e5324e4/volumes/kubernetes.io~secret/default-token-i49yf type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/0c52522f-69d9-11e6-ac66-901b0e5324e4/volumes/kubernetes.io~secret/default-token-i49yf type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/bd39a392-69d9-11e6-ac66-901b0e5324e4/volumes/kubernetes.io~secret/default-token-qzpqq type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/bd35515e-69d9-11e6-ac66-901b0e5324e4/volumes/kubernetes.io~secret/default-token-qzpqq type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/bd3b8029-69d9-11e6-ac66-901b0e5324e4/volumes/kubernetes.io~secret/default-token-qzpqq type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/bd3b88b6-69d9-11e6-ac66-901b0e5324e4/volumes/kubernetes.io~secret/default-token-qzpqq type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/bd37f084-69d9-11e6-ac66-901b0e5324e4/volumes/kubernetes.io~secret/default-token-qzpqq type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/bd367d32-69d9-11e6-ac66-901b0e5324e4/volumes/kubernetes.io~secret/default-token-qzpqq type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/bd396cb4-69d9-11e6-ac66-901b0e5324e4/volumes/kubernetes.io~secret/default-token-qzpqq type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/bd3698cb-69d9-11e6-ac66-901b0e5324e4/volumes/kubernetes.io~secret/default-token-qzpqq type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/bd38d157-69d9-11e6-ac66-901b0e5324e4/volumes/kubernetes.io~secret/default-token-qzpqq type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/bd369312-69d9-11e6-ac66-901b0e5324e4/volumes/kubernetes.io~secret/default-token-qzpqq type tmpfs (rw,relatime)
```

>It causes error, because `kubelet` wants to remove non-empty directories with mounted volumes.

>![image](https://cloud.githubusercontent.com/assets/2823399/17965264/f30621b8-6abb-11e6-8fe4-b221127be2b6.png)

>As a fix for this issue, we think, `etcd` could be synchronized with disk state or update of `cleanupOrphanedPodDirs` function (adding disk state check and unmounting pods before they are removed as you suggested).

>Should we create issue in the core repository?

**Comment by maciaszczykm** [comment]
Okay, let's rephrase our proposed solution. We want to reflect `etcd` state on disk. It means, that when `etcd` doesn't contain metadata for given pod and `kubelet` is starting, it will try to unmount it. It could be done from `cleanupOrphanedPodDirs` method (we can unmount pods if there are problems with removing orphaned directories) or after checking if there are mounted pods (not existing in `etcd`).

It seems, that updating `podVolumesExist` (adding check for disk content) makes no sense, because only pods existing in `etcd` could be skipped.

CC @cheld @luxas @floreks

**Comment by jingxu97** [comment]
Hi @maciaszczykm , we recently have a fix #27970 to unmount orphaned pods volumes when kubelet restarts. Basically It will periodically scans pods directories, and put this information into volume reconciler in kubelet and eventually the volume will be cleaned up (unmounted) if it belongs to an orphaned pod. Please let us know if you still experience any issue related to this.

**Comment by floreks** [comment]
I've looked at this PR and it should fix this bug. Let us quickly retest it on HEAD and we'll get back with results.

**Comment by floreks** [comment]
I have tested it and I can confirm that this error does not occur anymore. Reconciler unmounts pod volumes after some time if they are not present in etcd but exist on the disk. After that they are correctly removed.

![zrzut ekranu z 2016-08-31 10-22-48](https://cloud.githubusercontent.com/assets/2285385/18121458/e59746e4-6f64-11e6-81b8-500a67554323.png)

![zrzut ekranu z 2016-08-31 10-15-35](https://cloud.githubusercontent.com/assets/2285385/18121232/e779ed96-6f63-11e6-8a6a-cbe0aef9c907.png)
