### ISSUE TITLE
kubectl get pods -o wide  has no ip

### ISSUE THREAD

**Issue by cherylhan** [kubernetes/kubernetes#31595]
i use k8s 1.3.4 on centos when i use kubectl get pods -o wide ，i find there is no ip for my pods

etcdctl get /k8s/network/config
{"Network":"172.100.0.0/16"}

flannel0: flags=81<UP,POINTOPOINT,RUNNING>  mtu 1472
        inet 172.100.8.0  netmask 255.255.0.0  destination 172.100.8.0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.100.8.1  netmask 255.255.255.0  broadcast 0.0.0.0

sudo kubectl describe pod helloworld
Name:		helloworld
Namespace:	default
Node:		centos-node/10.149.27.162
Start Time:	Mon, 29 Aug 2016 11:11:09 +0800
Labels:		<none>
Status:		Running
IP:		
Controllers:	<none>
Containers:
  helloworld:
    Container ID:

**Comment by nkwangleiGIT** [comment]
hi cherylhan,
Do you mean the results of "**kubectl get pods -o wide**" don't show Pod IP in your centos environment?
As I tried, Pod IP was on the list, can you provide more details?

**Comment by cherylhan** [comment]
@nkwangleiGIT  thanks i have resolved the problem 。when i restart docker ，i forget set --bip
