### ISSUE TITLE
Replace every GET/LIST with list/watch?

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#31608]
**Is this a request for help?**

Yes.

As this line shows,

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/route/routecontroller.go#L83

```
// TODO (cjcullen): use pkg/controller/framework.NewInformer to watch this
// and reduce the number of lists needed.
```

@cjcullen Do you have plan to change  from **List Node** to **watch node**?

BTW, I have general question. - I find some controllers use `GET/LIST` resource objects while some others use `watch`. I wonder is there any rules that conduct us when to `GET/LIST` and when to `watch`.

In my opinion, `watch` can reduce some read/write pressure on API Server & etcd compared with `GET/LIST`. Why we still use `GET/LIST` in some client side, such as route controller, kubelet and so on.

@wojtek-t @mqliang 

Thanks!

**Comment by m1093782566** [comment]
@wojtek-t 

Thank you for your quick answer but I still have the question:

Can we replace every `LIST/WATCH` with `watch`, like [node controller](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L489) and [kubelet](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status.go#L238)?

If can't, is there any reason?

Thanks!

**Comment by wojtek-t** [comment]
>
Can we replace every GET/LIST with watch, like node controller and kubelet?

Ideally, we should replace them. But some of them may be tricky to do and are not that obvious (as you can see on the route-controller PR, which seems to be active for few weeks, and it's not yet figured out what's wrong with it).

**Comment by m1093782566** [comment]
Okay, I will trace this PR and hope can do some help.

**Comment by wojtek-t** [comment]
That would be great, because I didn't have time to debug it. If you ca help with making it work, I'm happy to review it.
