### ISSUE TITLE
Timed out waiting for cluster initialization. Cluster API may not be available.

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#31610]
More details here:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/31526/kubernetes-pull-build-test-e2e-gke/9911/

**Comment by dims** [comment]
@mwielgus : @lavalamp took care of this over the weekend (https://groups.google.com/d/msg/kubernetes-dev/WlispDLOwVM/CLZ1DqF1CgAJ)
