### ISSUE TITLE
GKE is referencing deprecated admission plug-ins

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#31611]
The PR (https://github.com/kubernetes/kubernetes/pull/31250) merged to remove `NamespaceExists` and `NamespaceAutoProvision` admission plug-ins.  

The plug-ins were deprecated and should not be used in any setup.  Unfortunately, there appears to be a GKE setup that is using them.  It should just be using `NamespaceLifecycle`.

Someone at Google managing the GKE scripts needs to remove these references so we can undo the revert of the referenced PR.

/cc @lavalamp @nikhiljindal @eparis @kubernetes/rh-cluster-infra

**Comment by derekwaynecarr** [comment]
@cjcullen - are you able to explain what in GKE is using these two admission plug-ins that warranted a rollback of the referenced PR?  otherwise, I am flying in the dark, and there is no good reason for GKE to be referencing them.

**Comment by goltermann** [comment]
@cjcullen are you handling the needed changes?

**Comment by cjcullen** [comment]
We are still referencing the NamespaceExists admission control plugin, and I have no idea why. I'll remove that from our 1.4 deployment setup.

**Comment by cjcullen** [comment]
Ehh, might not roll out until ~2AM. Still going to close this.

**Comment by nikhiljindal** [comment]
@derekwaynecarr Did you get a chance to submit https://github.com/kubernetes/kubernetes/pull/31250 again?
