### ISSUE TITLE
Openstack cloud provider doesn't implement ExternalID() according to Instances interface requirement

### ISSUE THREAD

**Issue by sjenning** [kubernetes/kubernetes#31615]
The Openstack provider implementation of ```Instances.ExternalID()``` does not return ```cloudprovider.InstanceNotFound``` as the error if the instance is not found as required by the interface:
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/cloud.go#L113

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L265

This is used in the node controller to determine if the node should be removed or not:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/controller_utils.go#L253

@kubernetes/rh-cluster-infra @ncdc @anguslees

**Comment by francobellagamba** [comment]
This same issue is present in the Rackspace CP.
