### ISSUE TITLE
ImageID returned in pod status is deceptive

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#31621]
Docker 1.10, when pulling an image by tag or digest, creates local data with the appropriate digest (sha256:1) but does not expose that to the end user.  Instead it creates a new synthetic manifest with a different digest (sha256:2) that references the same data.  Internally, it has access to the original digest for checking, but does not expose that to the API.  Node Status and Pod Status both report (sha256:2).   Docker 1.12 and some patched versions of Docker 1.10 populate the "RepoDigests" field.

For NodeStatus, RepoDigests is more correct (since sha256:2 is not pullable), but RepoDigests is not being set on the version of Docker 1.10 that I have 

For Pod Status, the value of imageID is useful across multiple hosts, but not useful to a cluster administrator that is trying to recreate an exact deployment (sha256:2 is not pullable).  It would be useful if the repoDigests were also returned alongside the imageID - allowing a cluster administrator to reconstruct which actual pullable images can be used.

**Comment by smarterclayton** [comment]
@ncdc

**Comment by ncdc** [comment]
@smarterclayton my NodeStatus has the correct sha256:1 values for images pulled by id, e.g. `docker.io/centos/ruby-23-centos7@sha256:0f097bcd89851ed9c5ac367327f0fb4c9d22574e8884d90a301c813b263832e7`

**Comment by smarterclayton** [comment]
When images are pulled by tag, the value is not set, so an admin cannot discover which images are actually in user in their cluster (even though the daemon knows that the image exists locally).

**Comment by ncdc** [comment]
True. See https://github.com/docker/distribution/issues/1662#issuecomment-213079540 for more details.

**Comment by smarterclayton** [comment]
The use case we hit this on was an administrative tool that wanted to understand what images were actually in use in the cluster to consult a blacklist.  The current value is not useful - admins can't blacklist content without loading it on a docker daemon, and it's not guaranteed that the digest on a particular daemon for a tag is identical across versions of docker.

**Comment by smarterclayton** [comment]
@deads2k

**Comment by ncdc** [comment]
What if we scrape & parse the pull progress to get the Digest value and store that somewhere?

**Comment by smarterclayton** [comment]
Can we do a Docker daemon flag that sets the RepoDigest on a pulled image
automatically?  And then prefer RepoDigest from this spot?  Would that
break GC?

**Comment by ncdc** [comment]
It would break GC

**Comment by deads2k** [comment]
> What if we scrape & parse the pull progress to get the Digest value and store that somewhere?

Is there a way for the kubelet to resolve the image:tag down to a digest in the kubelet, then use the digest to pull the image instead of using the image:tag?  That value seems significantly more useful and it wouldn't require a docker change.

**Comment by ncdc** [comment]
> Is there a way for the kubelet to resolve the image:tag down to a digest in the kubelet, then use the digest to pull the image instead of using the image:tag? That value seems significantly more useful and it wouldn't require a docker change.

Yes, two ways:

1. Scrape and parse, so you'd first pull by tag and then by digest
2. Query the registry for image:tag, get its digest, and then pull by digest

**Comment by smarterclayton** [comment]
Why would it break GC?

**Comment by smarterclayton** [comment]
More specifically, if it breaks GC, can we have it not break GC.

**Comment by ncdc** [comment]
I'm saying that `docker rm foo:bar` would result in just untagging `foo:bar` from the actual image. Because the graphdriver still has `foo@sha256:abcd`, the image won't actually get purged.

**Comment by ncdc** [comment]
Kube image GC may be ok, since it would record both RepoTags and RepoDigests, and it could purge both values.

**Comment by smarterclayton** [comment]
Doesn't GC see that foo@sha256:abcd isn't used and also purge that?  GC of
images has to deal with any visible tags that aren't managed by Kube,
because it can't rely on just managing images downloaded by Kube.

**Comment by ncdc** [comment]
> Doesn't GC see that foo@sha256:abcd isn't used and also purge that?  GC of
images has to deal with any visible tags that aren't managed by Kube,
because it can't rely on just managing images downloaded by Kube.

Yes, I think we should be ok because of this. I'm not sure if we'd be able to get a PR accepted to add a field to the daemon to record RepoDigests on pull.

**Comment by smarterclayton** [comment]
What would we do in ocid here?  Whatever solution we pick, the lower we can fix it the better.  Agree we might not be able to get a Docker fix.

**Comment by DirectXMan12** [comment]
> not guaranteed that the digest on a particular daemon for a tag is identical across versions of docker.

I could be wrong, but based on my reading of https://github.com/docker/distribution/issues/1662#issuecomment-213079540, it looked like assuming you pushed in the v2 schema format, sha256:2 is actually the `config.digest` value (while sha256:1 is the manifest digest), which is why it appears locally -- the comment above mentions that the *config* is stored locally, while the *manifest* is used for pushing/pulling, but not stored locally.  But, we care about the v1 format as well, so that's probably a moot point.

**Comment by DirectXMan12** [comment]
> Query the registry for image:tag, get its digest, and then pull by digest

I think I'm in favor of doing something that looks like this, more or less.  I wonder what the exact series of steps `docker pull` actually takes in order to print that output is?

**Comment by ncdc** [comment]
Another possible thing we could do - when creating the container, set a label that contains the pull spec of the image. This could be displayed instead of the image id (config.digest).

**Comment by DirectXMan12** [comment]
> Another possible thing we could do - when creating the container, set a label that contains the pull spec of the image.

That's not a bad stop-gap, but it means that tooling needs to implement their own way to figure out to convert image image pull specs to SHAs to reliably compare (plus, how do you figure out what the "latest" tag means that way?)

**Comment by DirectXMan12** [comment]
(also, as for scraping the output, there's no way to guarantee that's reliable in any way, shape or form -- the message is just `{"status": "Digest sha256:FOOBAR"}`, so you'd have to look at every "status" message, check if it began with "Digest ", and hope that Docker doesn't change that in any way.  I can just see it causing weird issues in the future)

**Comment by ncdc** [comment]
> but it means that tooling needs to implement their own way to figure out to convert image image pull specs to SHAs to reliably compare

The image pull spec has the SHA if you pull by digest. The pull spec has the tag if you pull by tag. I don't think any conversion is necessary unless I'm misunderstanding you?

**Comment by DirectXMan12** [comment]
> The pull spec has the tag if you pull by tag. I don't think any conversion is necessary unless I'm misunderstanding you?

If you pull by tag, how are you going to be able to compare image versions?  Suppose, from the example above, I blacklist "foo/bar@sha256:xyz".  On the registry, "foo/bar@sha256:xyz" corresponds to tags 2.2, but formerly also referred to "latest" (but has since been updated).  If I ran "foo/bar:latest" at some point in the past, I now have a copy of "foo/bar@sha256:xyz" running on my node.  However, when the tooling goes to look at the label, it sees that I'm running "foo/bar:latest", and either a) thinks I'm running an ok image (because "latest" on the registry is now fine) or b) gets confused, because it has no way to figure out which image "latest" actually refers to.

or were you saying "always pull by digest *and* store the pull spec in a label"?

**Comment by ncdc** [comment]
I wasn't thinking about tag mutability, which is a very good point. Back to the drawing board...

**Comment by vishh** [comment]
I don't get why a host specific identifier was exposed via the cluster API in the first place. 

Node local information could be exposed via kubelet APIs instead. Would that be acceptible?

**Comment by ncdc** [comment]
@vishh it is not actually a host specific identifier. It is the digest of a blob in the registry. The value is identical regardless of host.

**Comment by ncdc** [comment]
See https://gist.github.com/ncdc/e4e73ac67bcddb88677fb67d4832d44a for more details

**Comment by derekwaynecarr** [comment]
Per today's sig-node, we discussed the need for a new field since we have to preserve existing field behavior.  This new field, let's say "pullImageID" needs to clarify how it get its value.  Should the kubelet resolve tags to digest form, or should the container runtime be expected to return the digest form always.  @DirectXMan12 is going to write up a proposal to work through pros/cons, and we can discuss on that document when available.

**Comment by derekwaynecarr** [comment]
See @DirectXMan12 WIP proposal here: https://github.com/kubernetes/kubernetes/pull/32159

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @smarterclayton @DirectXMan12

**Comment by DirectXMan12** [comment]
This was fixed by #34473 (we change the ImageID to be the pullable ID, when we have that info), so this can probably be marked as closed.
