### ISSUE TITLE
Service behaviour not correct when ESIPP annotation is toggled or deleted

### ISSUE THREAD

**Issue by girishkalele** [kubernetes/kubernetes#31649]
If a service is created with the ESIPP annotation `service.alpha.kubernetes.io/external-traffic` set to `OnlyLocal` and then the annotation is changed or deleted, the service behaviour does not change correctly.
Also, when the annotation is added to a running service.

It should reflect the current state in the iptables rules correctly, and cleanup the -XLB- rules and chains, if needed.

**Comment by pwittrock** [comment]
@girishkalele 

I am leaving this in the 1.4 release as a blocking issue.  Please provide daily status updates to this issue or move it out of the release and into v1.4-nonblocking where it will no longer be tracked as a release blocking issue in the burndown meetings.

**Comment by matchstick** [comment]
@thockin Can we review this ASAP for 1.4?
