### ISSUE TITLE
1 errors encountered.Running gubernator.sh

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#31656]
Best I can tell this: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/31541/node-pull-build-e2e-test/21735/

failed because
```
Ran 99 of 131 Specs in 684.207 seconds
SUCCESS! -- 99 Passed | 0 Failed | 0 Pending | 32 Skipped 

Ginkgo ran 1 suite in 11m26.677287946s
Test Suite Passed

================================================================
Failure: 1 errors encountered.Running gubernator.sh
exit status 1
Build step 'Execute shell' marked build as failure
```

can we just ignore/retry gubernator.sh failures? unsure if this is just node-e2e or everything

**Comment by fejta** [comment]
This is actually a false error message (the gubernator.sh line doesn't fail the build), the real failure is here in `build-log.txt` (truncated from the gubernator output):

`Failure Finished Host tmp-node-e2e-f8139197-coreos-alpha-1122-0-0-v20160727 Test Suite`

**Comment by fejta** [comment]
Dup of https://github.com/kubernetes/kubernetes/issues/31633
