### ISSUE TITLE
Fix Jenkins automated per-PR e2e tests for Federation

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#31674]
https://github.com/kubernetes/test-infra/issues/470 filed against test-infra repo, but that is a somewhat forgotten repo, and we need to make sure that this does not get overlooked so duplicating here.

Without fixing this, it's difficult to run full e2e tests against submitted PR's before merging them, which makes it very easy to introduce regressions.

**Comment by pwittrock** [comment]
@quinton-hoole 

I am moving this out of the blocking issues we are tracking for the 1.4 release.  If there is still 1.4 work to be done here that should be tracked in the weekly burndown meetings, move it back and provide daily updates to this issue.

**Comment by mml** [comment]
Looks like kubernetes/test-infra#470 is closed.  Closing, but reopen if I screwed up.

**Comment by nikhiljindal** [comment]
Current status is that the setup issues seem to be resolved.
But the test is still failing. The failure however is same as the post commit jenkins failures, so hopefully nothing special to be done here. But keeping this open until we have verified.

**Comment by nikhiljindal** [comment]
This is now fixed. Anyone can post "@k8s-bot federation gce e2e test this" to trigger the federation tests on a PR.
