### ISSUE TITLE
Variable expansion in pod command, args, and env timeline

### ISSUE THREAD

**Issue by wernight** [kubernetes/kubernetes#31686]
Could you add an issue on https://github.com/kubernetes/kubernetes/blob/master/docs/design/expansion.md to have an idea of when it may be released?

Also wondering why not use the standard, also used by `docker-compose` of `${VAR}`?

**Comment by janetkuo** [comment]
cc @pmorie

**Comment by pmorie** [comment]
Ugh. It's in, we're missing doc for it.

**Comment by wernight** [comment]
Thanks. I guess I must have misunderstood the feature or it's not in 1.3. I tried using `$(FOO)` and doing:

    FOO=123 kubectl apply -f kubernetes.yml

... but it didn't replace anything.

**Comment by wernight** [comment]
Looks like I'm looking for https://github.com/kubernetes/kubernetes/blob/master/docs/design/expansion.md

**Comment by krasoffski** [comment]
I would be great to have some built-in ability to replace place holders with variables via ENV or CLI.
