### ISSUE TITLE
[Pet Set] Refactor return value from []error to error

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#31695]
I propose refactor return value from `[]error` to error [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/petset/pet_set.go#L80), for the purpose of simplify code and format error output.

I think we can use `errors.NewAggregate(errorList)` to aggregate `[]error`.

Thanks!

**Comment by bprashanth** [comment]
you don't really need to file a bug if it's simple enough to open a pr, you can directly do the latter. fyi :)

**Comment by m1093782566** [comment]
ok, thanks! -close it here :)
