### ISSUE TITLE
Make pkg/kubectl/cmd/util/factor.go:Factory to be interface

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#31702]
Refactor pkg/kubectl/cmd/util/factor.go:Factory to be a interface. Currently, the `util.Factory` is defined by function pointer:

```
type Factory struct {
...
    Object func(thirdPartyDiscovery bool) (meta.RESTMapper, runtime.ObjectTyper)
    // Returns interfaces for dealing with arbitrary
    // runtime.Unstructured. This performs API calls to discover types.
    UnstructuredObject func() (meta.RESTMapper, runtime.ObjectTyper, error)
...
```

In Go, it's better to make Factory to be an struct; it'll also reduce the code line of `NewFactory()` which is more than 100 line of code :).

cc @AdoHe / @pwittrock

**Comment by ncdc** [comment]
cc @deads2k

**Comment by pwittrock** [comment]
@AdoHe Does this make sense to you?  If so, lets have @k82cn pick it up

**Comment by deads2k** [comment]
> Refactor pkg/kubectl/cmd/util/factor.go:Factory to be a struct. Currently, the util.Factory is defined by function pointer:

`Factory` already is a struct.  I could support making `Factory` into an interface, promoting its various function into typed functions, and then having first class methods for each function.  I think this is the sort of thing that @fabianofranz, @kargakis, and @kubernetes/kubectl are likely to have opinions on.

I think that you could start by creating first class methods for the anonymous ones currently included.

**Comment by deads2k** [comment]
Also, starting with a single method as an example is probably worthwhile so we can argue over principle there instead of in a larger pull.

**Comment by smarterclayton** [comment]
And really it should be multiple interfaces and each command should take the interfaces it requires.  That argument is partially why we have deferred this for so long.

**Comment by k82cn** [comment]
@deads2k , agree :). I'm going to refactor function pointer into functions firstly (one by one); and then refactor `Factory` to be an interface.

For multiple interfaces as @smarterclayton , we can discuss it after those patches.

Any comments?

**Comment by AdoHe** [comment]
@k82cn @deads2k @smarterclayton actually we have discussed a lot about kubectl refactor in #7311 #31173, generally we want decouple command framework from command logical, we will try to create logical groups. I agree that we could promote those functions to typed functions, this could be a good start.

**Comment by kargakis** [comment]
> Factory already is a struct. I could support making Factory into an interface, promoting its various function into typed functions, and then having first class methods for each function.

A bunch of the functions already conform to specific kubectl interfaces so it seems that this should end up being an interface composed of other interfaces.

Remaining business logic that exists in the Factory should be factored out to interfaces in pkg/kubectl
Example that conforms to the above already:
https://github.com/kubernetes/kubernetes/blob/ebe733e46983b0201501a23a26d48a73f41fe04c/pkg/kubectl/cmd/util/factory.go#L690-L698
https://github.com/kubernetes/kubernetes/blob/ebe733e46983b0201501a23a26d48a73f41fe04c/pkg/kubectl/history.go#L39
Example that doesn't:
https://github.com/kubernetes/kubernetes/blob/ebe733e46983b0201501a23a26d48a73f41fe04c/pkg/kubectl/cmd/util/factory.go#L571-L629

**Comment by smarterclayton** [comment]
Refactoring into functions would break valid uses in OpenShift (we
implement those).  So a partial refactor that leaves us without an
interface isn't an option.  I'd recommend going the other way, create an
interface, then turn those methods into it one by one.

**Comment by k82cn** [comment]
@smarterclayton , do you mean OpenShift implements some additional cmd?

Try to refactor `Factory.Object` today: if moving it out of struct as function, the `cmd_test.go` should be also updated accordingly; but no idea for now on following test cases, maybe we need to create interface firstly, any suggestion?

```
func NewAPIFactory() (*cmdutil.Factory, *testFactory, runtime.Codec, runtime.NegotiatedSerializer) {
    t := &testFactory{
        Validator: validation.NullSchema{},
    }

    f := &cmdutil.Factory{
        Object: func(discovery bool) (meta.RESTMapper, runtime.ObjectTyper) {
            return testapi.Default.RESTMapper(), api.Scheme
        },
        UnstructuredObject: func() (meta.RESTMapper, runtime.ObjectTyper, error) {
            groupResources := testDynamicResources()
....
```

BTW, it seems there's no test case in `facotry_test.go` for `Factory.Object`; I'll add some test cases for it.

**Comment by AdoHe** [comment]
```
A bunch of the functions already conform to specific kubectl interfaces so it seems that this should end up being an interface composed of other interfaces.
```
I would support this way.

**Comment by k82cn** [comment]
Hi team,

After updating the patch, some unit test are failed; so I'm working to fix it. But any suggestion on how to debug it?

I use the following command to `make check WHAT=pkg/kubectl/cmd KUBE_TEST_ARGS="-c"` to generate a binary to debug, but I got the following message :(. Any suggestions?

```
Klauss-MacBook-Pro:kubernetes klaus$ lldb cmd.test
(lldb) target create "cmd.test"
Current executable set to 'cmd.test' (x86_64).
(lldb) r  -test.v=true -test.run="TestCordon"
Process 41181 launched: '/Users/klaus/Workspace/kubernetes/cmd.test' (x86_64)
=== RUN   TestCordon
--- FAIL: TestCordon (0.00s)
       	drain_test.go:195: node/node syntax: unexpected error
FAIL
Process 41181 exited with status = 1 (0x00000001)
(lldb) b SetupDrain
Breakpoint 1: where = cmd.test`k8s.io/kubernetes/pkg/kubectl/cmd.(*DrainOptions).SetupDrain + 47 at drain.go:176, address = 0x0000000000094b9f
(lldb) r  -test.v=true -test.run="TestCordon"
Process 41193 launched: '/Users/klaus/Workspace/kubernetes/cmd.test' (x86_64)
=== RUN   TestCordon
Process 41193 stopped
* thread #1: tid = 0x17db68, 0x0000000000094b9f libsystem_c.dylib`_DefaultRuneXLocale + 279, stop reason = breakpoint 1.1
    frame #0: 0x0000000000094b9f libsystem_c.dylib`_DefaultRuneXLocale + 279
libsystem_c.dylib`_DefaultRuneXLocale:
->  0x94b9f <+279>: movq   0xd0(%rsp), %rax
    0x94ba7 <+287>: cmpq   $0x1, %rax
    0x94bab <+291>: je     0x94cb1                   ; <+553>
    0x94bb1 <+297>: movq   $0x0, 0x98(%rsp)
(lldb)
```
