### ISSUE TITLE
How to restrict Kubernetes Cluster to internal IPs/ELBs/... in AWS?

### ISSUE THREAD

**Issue by dlamotte** [kubernetes/kubernetes#31713]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): First attempted via #kubernetes-users on slack

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):  internal aws load balancer

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5+b0deb2e", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"not a git tree", BuildDate:"2016-08-21T12:21:36Z", GoVersion:"go1.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5+coreos.0", GitCommit:"d7a04b1c6044647f5919fadf3cecb9ee70c10fc5", GitTreeState:"clean", BuildDate:"2016-08-15T21:01:42Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS
- **Install Method**: kube-aws

**Our use case**:
We are extending our on premise infrastructure into the AWS Cloud.  It's meant to be _internal-only_ and we're taking measures to guarantee that security.

**Feature Request**:
A method to guarantee that the environment _stays_ internal and does not accidentally get exposed externally.

**Possible Methods I've explored**:
- AWS IAM Policy to restrict kubernetes from creating a public ELB
- AWS Security Group limiting client source IPs

I was speaking with @justinsb on #kubernetes-users on slack and he suggested I submit a request for this here.

**Comment by dlamotte** [comment]
At this point, it seems the best option is to ensure that the nodes in AWS inherit an IAM role that doesn't allow load balancing at all.  Then expose cluster services as a node port.  From there, if you're lucky enough to have all your nodes in an autoscale group, then you can manually create internal ELBs manually that auto-map to all your nodes.

It's an ok balance between security and maintainability.

**Comment by dlamotte** [comment]
Current IAM Role Policy I'm attempting to use with Kubernetes:

```
policy_controller:
  Version: '2012-10-17'
  Statement:
    - Action: [
        'ec2:AttachVolume*',
        'ec2:CreateTags',
        'ec2:CreateVolume*',
        'ec2:DeleteVolume*',
        'ec2:Describe*',
        'ec2:DetachVolume*',
      ]
      Effect: Allow
      Resource: '*'

    - Action: kms:Decrypt
      Effect: Allow
      Resource: "{{ aws_kms_key }}"

policy_worker:
  Version: '2012-10-17'
  Statement:
    - Action: ec2:Describe*
      Effect: Allow
      Resource: '*'

    - Action: ec2:AttachVolume*
      Effect: Allow
      Resource: '*'

    - Action: ec2:DetachVolume*
      Effect: Allow
      Resource: '*'

    - Action: kms:Decrypt
      Effect: Allow
      Resource: "{{ aws_kms_key }}"
```
_note: above is yaml formatted and converted to json before use_

**Comment by dlamotte** [comment]
I wonder if implementing an "AWSPolicy" admittance control plugin would suffice?  Effectively, don't accept Services of type LoadBalancer into the cluster unless it has the `internal` annotation.  A more abstract framework for governing "AWS Policies" seems useful, but a design for something like that isn't obvious to me at the moment.

**Comment by justinsb** [comment]
@dlamotte using an admission controller is a great idea I think.  We're also talking about having two IAM policies, one for k8s/kops to manage, one for you to manage, and I think you could add deny rules there, but an admission controller still gives you more control.

There was this proposal: https://github.com/kubernetes/kubernetes/pull/27336

But I think @whitlockjc was talking about creating an external admission controller, though it proved tricky - is that right @whitlockjc and how far did you get?  Any  issues / PRs or the like we can look at?

**Comment by whitlockjc** [comment]
I might have misunderstood _"external admission controller"_ but if I did understand it, there is no way to create an external one.  The only way to create one is to build a custom version of Kubernetes with your admission controller statically built into it.  I have started working on a generic webhook admission controller that would allow the webhook being called to alter the API request and/or deny the API request.  Unfortunately, it's not done.

**Comment by dlamotte** [comment]
@whitlockjc any issue to follow?  Would definitely make experimenting with an AWS Policy Admission Control easier.

**Comment by whitlockjc** [comment]
Nothing yet.  I just brought it up on Slack and while people suggested it might not be possible _(easily)_, no one said the idea was stupid.

**Comment by whitlockjc** [comment]
Feel free to ping me on Slack.  If you do, I'll keep you in the loop and cc you in the eventual PR.
