### ISSUE TITLE
[k8s.io] Services should be able to change the type and ports of a service [Slow] [It]

### ISSUE THREAD

**Issue by jessfraz** [kubernetes/kubernetes#31715]
This failure happens quite often in the e2e upgrade tests:

Seems like a good fix would be to clean out all the static IP's that aren't being used before running the tests.

```
• Failure [53.644 seconds]
05:09:50 [k8s.io] Services
05:09:50 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:783
05:09:50   should be able to change the type and ports of a service [Slow] [It]
05:09:50   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:725
05:09:50 
05:09:50   Expected error:
05:09:50       <*errors.errorString | 0xc8212eedb0>: {
05:09:50           s: "failed to create static IP: ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:\n - Quota 'STATIC_ADDRESSES' exceeded. Limit: 7.0\n\n",
05:09:50       }
05:09:50       failed to create static IP: ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
05:09:50        - Quota 'STATIC_ADDRESSES' exceeded. Limit: 7.0
05:09:50       
05:09:50       
05:09:50   not to have occurred
05:09:50 
05:09:50   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:498
```

**Comment by jfrazelle** [comment]
So it seems like they _should_ get cleaned up: https://github.com/kubernetes/kubernetes/blame/d95b9238877d5a74895189069121328c16e420f5/pkg/cloudprovider/providers/gce/gce.go#L1376

**Comment by bprashanth** [comment]
Yeah this business https://github.com/kubernetes/kubernetes/issues/27883. If you shutdown the cluster right after deleting the service, controller manager gets nuked (https://github.com/kubernetes/kubernetes/issues/16337). We can work around that in e2es (https://github.com/kubernetes/kubernetes/issues/32690). I also need to review https://github.com/kubernetes/kubernetes/pull/32183.

That aside, a limit on 7.0 static addresses can be alleviated through a quota request on console.cloud.google.com (you can find the project in the build log), I usually put in
```

Global
Number of Snapshots 
Number of Networks  
Number of Firewall Rules    
Number of Images    
Number of Routes    
Number of Instance Templates    
Number of Forwarding Rules  75 
Number of Target Pools  
Number of Target Instances  
Number of Health Checks 75 
Number of HTTP Proxies  75 
Number of HTTPS Proxies 75 
Number of URL Maps  75 
Number of Backend Services  30 
Number of External IPs  50 
Number of Static IPs    50 
Number of SSL Certificates  50 
Number of VPN Tunnels   
Number of Target VPN Gateways   
```

**Comment by shyamjvs** [comment]
@jessfraz @bprashanth This still seems to be an issue. I don't have too much context into this, but has it been decided to increase the quota or add garbage collection logic in the test or just let it stay as it is for now? It would be great if we could make it green again :)

**Comment by freehan** [comment]
@shyamjvs Which test suite are you referring to? Do you mind copying the link?

**Comment by shyamjvs** [comment]
The gke-slow suite: https://k8s-testgrid.appspot.com/google-gke#gke-slow. You can see that it's pretty much the only test which is failing in the suite.

**Comment by bowei** [comment]
close

I'm not seeing the flake for this test given the recent history.

**Comment by bowei** [comment]
actually on second look, this is failing for continuing https://k8s-testgrid.appspot.com/google-aws#kops-aws-slow&width=5

**Comment by bowei** [comment]
this needs to be a assigned to someone with kops expertise

**Comment by ethernetdan** [comment]
@justinsb looks like this failure is isolated to the kops suites, any thoughts? 

We should triage this as a 1.6 blocker or non-blocker.

**Comment by ethernetdan** [comment]
cc/ @kris-nova

**Comment by justinsb** [comment]
For kops, this is failing because we aren't relaxing the security groups to allows jenkins access to NodePorts.  Failures related to kops are not a blocker.

**Comment by ethernetdan** [comment]
Great! sounds like not a blocker

**Comment by marun** [comment]
This issue hasn't been active in 90 days.   Closing.
