### ISSUE TITLE
kubeadm graduation requirements

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#31711]
We need to decide on a scope for kubeadm that we feel comfortable strapping a `beta` label onto.

Beta requirements:
- [ ] TLS bootstrap in beta https://github.com/kubernetes/features/issues/43
- [ ] Discovery API in beta #31779
- [ ] e2e testing

Beta or GA?
- [ ] CA certificate rotation
- [ ] join secret rotation

GA requirements:
- [ ] TLS bootstrap GA
- [ ] Discovery API GA

Wishlist:
- [ ] Better support for self hosting
  - [ ] Kubelet checkpointing
- [ ] High availability
- [ ] Kubeconfig v2

@kubernetes/sig-cluster-lifecycle

**Comment by lukemarsden** [comment]
Thanks for this!

I think it might make sense to distinguish between items such as "phase I => beta" or "phase II => alpha", according to the phase I/II breakdown in https://github.com/kubernetes/kubernetes/pull/30360

**Comment by lukemarsden** [comment]
https://github.com/lukemarsden/kubernetes/blob/a692dea1c9be15bf34194fbab81519058fdf19f4/docs/proposals/dramatically-simplify-cluster-creation.md#user-stories to save you some clicks

**Comment by philips** [comment]
@mikedanese Sorry to be annoying, but could we use a feature for this? https://github.com/kubernetes/features

**Comment by pires** [comment]
Was this even looked at during yesterday's meeting?

**Comment by mikedanese** [comment]
@pires I think we should discuss what beta means in more depth next meeting.

**Comment by pires** [comment]
@mikedanese agreed. Added item on meeting's agenda.

**Comment by pires** [comment]
We have agreed to have several `kubeadm` components with each having its own graduation requirements, right? E.g., `kubeadm` could be GA while `kubeadm HA` is alpha.

**Comment by pires** [comment]
@mikedanese we should add testing (#34136) as a hard requirement for GA.

**Comment by mikedanese** [comment]
Added to the beta graduation requirements,

**Comment by mcapuccini** [comment]
Hello! Is the HA support for kubeadm under development? Will it be in K8s 1.5?

**Comment by luxas** [comment]
HA for everyone is an extremely complicated task given Kubernetes' current architecture without having a cloud provider, central loadbalancer or something like that you can rely on, but eventually we'd like to have HA support for kubeadm, yes.

See the v1.6 objectives which includes steps to get closer to bare-metal HA: https://docs.google.com/document/d/1v4k7eN-eetHbbpTAG7WuioRAMsK_FVGi1yC3VIn4Inw/edit#heading=h.8dh1uxinqwag
We will probably not have full-blown HA support for v1.6.

**Comment by philips** [comment]
@luxas I think HA can be made easier if we fix the API server to advertise DNS instead of just an IP and fix the default "race" where two API servers just flip-flop forever.

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#63
