### ISSUE TITLE
test service sessionAffinity in networking e2e

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#31712]
Augment https://github.com/kubernetes/kubernetes/pull/31559 to turn on session affinity for a service, lookup the vip from a container/node and make sure we only hit a single endpoint with N ready/running endpoints.

**Comment by cmluciano** [comment]
This looks like it is still relevant 

@kubernetes/sig-network-misc can anyone confirm if we added these?

I still see a [TODO](https://github.com/kubernetes/kubernetes/blob/bcccbc3d0b28171d383eda5eac16b487bcda9cf6/test/e2e/networking.go#L193)

**Comment by m1093782566** [comment]
@cmluciano Are you working on it?

Could you please assign this issue to me and I am happy to fix it. Thanks a lot!

**Comment by cmluciano** [comment]
/assign @m1093782566 

I have it in my "backlog" behind NetworkPolicy stuff. Feel free to take it over if you have time.

**Comment by m1093782566** [comment]
Would appreciate @cmluciano :)
