### ISSUE TITLE
Idea: Provided a mechanism to aggregate a given pod's related events / logs 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#31720]
Forked from #3500 since the initial issue is closed...

When debugging an issue of an application, often the developer has to look into kubelet log and do some logging process. 

@coufon introduces time series and tracing to Kubelet for the node performance analysis work (https://github.com/kubernetes/kubernetes/pull/31280). Kubernetes already uses events to trace some operations, but not adequate. We are going to consolidate those for performance analysis at node. Meanwhile all tracking records are persist in kubelet loggs. We can easily aggregate those events from logs to improve our debuggablity. 

cc/ @derekwaynecarr we briefly talked about this another day.

**Comment by derekwaynecarr** [comment]
I can't tell if you want to provide analysis on Event objects as related to
node or from the Log files themselves, but I am a big +100 on doing
something here to help people help themselves.
