### ISSUE TITLE
Investigate GKE master get/put flakes

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#31728]
Quite a few tests flake with: 
```
an error on the server has prevented the request from succeeding (put replicasets.extensions frontend-
88237173); Current resource version 493
```

This seems to indicate: 
* test should retry
* that's a lot of flake on GKE

eg:  https://github.com/kubernetes/kubernetes/issues/29149, https://github.com/kubernetes/kubernetes/issues/30156, https://github.com/kubernetes/kubernetes/issues/30352#issuecomment-243299162, pretty much all the failures in https://github.com/kubernetes/kubernetes/issues/31188, https://github.com/kubernetes/kubernetes/issues/31429#issue-173205462, https://github.com/kubernetes/kubernetes/issues/31575, https://github.com/kubernetes/kubernetes/issues/31408

**Comment by dchen1107** [comment]
cc/ @dchen1107

**Comment by lavalamp** [comment]
https://github.com/kubernetes/kubernetes/blob/7272cd09e3819049a125278134ebb699a1f469b5/pkg/apiserver/apiserver.go#L268

throws away the error message... sigh

**Comment by pwittrock** [comment]
@lavalamp @bprashanth 

I am leaving this in the 1.4 release as a blocking issue.  Please provide daily status updates to this issue or move it out of the release and into v1.4-nonblocking where it will no longer be tracked as a release blocking issue in the burndown meetings.

**Comment by mml** [comment]
Raising to p0 as #31812 is p0 and I dup'd it to this.

**Comment by jlowdermilk** [comment]
Investigation showed these are due to transient flakiness in the GKE test environment. We're currently migrating the offending piece to a production grade service, which should greatly reduce these flakes. I'll close this once we're done.
