### ISSUE TITLE
Package and host the kube-dns container on the master

### ISSUE THREAD

**Issue by girishkalele** [kubernetes/kubernetes#31739]
Today we build the kube-dns binary from the sources that are in-tree.
We do not ship this binary - instead the container is pushed to gcr.io and scheduled on a worker node which pulls it from the GCR container registry.

I wish this was packaged and shipped along with the rest of the master binaries/containers.

Potential Solution:
We host a small Docker registry server on the apiserver and when generating the kube-dns rc podspec from template we substitute the image name from `gcr.io/google_containers/<kubedns>` to `<apiserver>/google_containers/<kubedns>` (we're already distributing apiserver certs to all nodes today, we can reuse them for the docker registry).

This could also be used for other addon containers.

**Comment by girishkalele** [comment]
cc @kubernetes/sig-network @MrHohn @thockin

**Comment by girishkalele** [comment]
We are going to start a bunch of enhancements to the kube-dns container across multiple team members, it would be nice to have this without the out-of-band gcr.io container and image versioning conflicts.

**Comment by bprashanth** [comment]
We should be careful that we don't ever create a daemonset addon, and end up serving O(1000) images from a registry on the master. Eitherway we'd probably need to productionize https://github.com/kubernetes/kubernetes/issues/1319.

We could also just do what we do for all other apiserver components, i.e upload the image to GCS and use docker load on the master. GCS scales already.

**Comment by girishkalele** [comment]
Yes, if we could do side-loading on the scheduled node before launching the kube-dns pod there, that would also work. A use case for init-containers ?

**Comment by bprashanth** [comment]
Yeah, of course it would be even better if the kubelet understood different image sources (including download a tarball binary and run in a cgroup), but I think the second one might be a little far out. 

We could make the registry a cluster addon and scale it with load. I'm just afraid that would become another scaling point that we'd need to debug in production.

**Comment by thockin** [comment]
I agree with the goal, but what real problem is it causing today?

**Comment by girishkalele** [comment]
I wish there was a single build + deploy for the entire codebase - making kube-dns the same as the other kube-xxxx daemons.
Multiple engineers committing kube-dns changes which collide would be eliminated.
The branching process for kube-dns containers tag versions will be eliminated.
For OSS contributors without push access to gcr.io/google_containers, they can commit changes just like other kube-xxx code.

**Comment by thockin** [comment]
The flip side of this is that we can move kube-DNS to its own repo and
manage it independently, and just cut periodic builds and integrate with
core system that way,

**Comment by bowei** [comment]
kube dns has graduated to its own repo
