### ISSUE TITLE
Prevent leaking health check service node ports

### ISSUE THREAD

**Issue by girishkalele** [kubernetes/kubernetes#31757]
If a service with the ESIPP annotation is created, a health check node port is allocated (and the value stored in an annotation).

If, subsequently, the following cases happen, we need to free the health check node port back to the NodePortAllocator.

a) Service is deleted
b) The HealthCheckNodePort annotation is deleted.
c) The ESIPP annotation is deleted.
d) Both annotations are deleted.

**Comment by pwittrock** [comment]
@girishkalele 

I am leaving this in the 1.4 release as a blocking issue.  Please provide daily status updates to this issue or move it out of the release and into v1.4-nonblocking where it will no longer be tracked as a release blocking issue in the burndown meetings.

**Comment by matchstick** [comment]
@thockin We need the PRs for this reviewed ASAP for 1.4
