### ISSUE TITLE
Get on a non-existent namespace should return a 404.

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#31753]
An example:

``` sh
$ kubectl get pods --namespace=nonexistent -o json
{
    "kind": "List",
    "apiVersion": "v1",
    "metadata": {},
    "items": []
}
```

I think it should actually return:

``` sh
$ kubectl get pods --namespace=nonexistent -o json
namespace 'nonexistent' not found.
```

**Comment by smarterclayton** [comment]
The default today is return 403 - forbidden.   That is our behavior for any URL that is not found today when the auth engine is on, and is a good safe default.  There is a usability argument that we should return 404 to assist clients, so this is the classic security vs usability tradeoff.

**Comment by AdoHe** [comment]
I think auth engine should only work when an existed URL is hit, if URl is not found, we should return 404. Makes more sense for me.

**Comment by smarterclayton** [comment]
The security challenge is that namespace names might be security minded,
and so that allows an attacker to probe for names of namespaces or
resources.

**Comment by brendandburns** [comment]
@smarterclayton I think a better option is to return 404 for both non-existent and unauthorized URLs, the default user UX is better, I'll be very confused if I typo a namespace that I have rights to and I get a 403, whereas if I always get a 404, I still can't use it for probing.

--brendan

**Comment by AdoHe** [comment]
Perhaps it would be if we can add some cause reason to distinguish non-existent and unauthorized.

**Comment by smarterclayton** [comment]
@kubernetes/sig-auth

**Comment by liggitt** [comment]
The signal difference between 403 and 404 is important. 403 tells me I am not allowed to do the operation. It doesn't tell me whether or not the item exists. 404 tells me I am allowed to do the operation and that what I requested does not exist.

**Comment by liggitt** [comment]
the [client-side fix](https://github.com/kubernetes/kubernetes/pull/31594) for https://github.com/kubernetes/kubernetes/issues/15542 seems better to me than losing the distinction between "not allowed" and "not found"

c.f. https://github.com/kubernetes/kubernetes/pull/15543

**Comment by alexives** [comment]
@liggitt, you closed this, but has it been resolved? I seem to get `not found` now, but I'm not sure what version it was changed in.
