### ISSUE TITLE
On azure cluster provisioning reported as failed - consistently (0.7.1)

### ISSUE THREAD

**Issue by soatman** [kubernetes/kubernetes#3177]
list minions reported 1-3 minions out of 6 requested being provisioned. Upon investigation all minions appeared to be fine.  Was able to add them manually using kubecfg.sh create minions.  Including the JSON for the convenience of others in the same boat... all of my VMs were the same size.  Used get minions to get most of the details from one of the successfully recorded minions.  

{	
	"apiVersion": "v1beta1",
	"kind":"Minion",
	"id": "kubernetes-minion-<theminionnumber>.<yourvnet>.d2.internal.cloudapp.net",
	"name": "",
	"hostIP": "10.0.0.10", //Change to the minion IP
	"resources":{"capacity":{"cpu":1000,"memory":3221225472}}  //This will likely differ for you.
}

Other NOTES: I increased the wait time in cluster/azure/util.sh for salt on the minions to avoid another error.  Increase "#Wait for salt on the minions"  sleep 60 to sleep 120 (your mileage may vary)

**Comment by goltermann** [comment]
@jeffmendoza can you take a look?

**Comment by v1s0n** [comment]
I noticed the same thing...Wish I would have found this post first.  I needed to increase the sleep that is prior to the sanity check also.  It got me past the sanity checks on all the nodes but now I will consistently only get two nodes out of four.  Validate-cluster reports "Detected 2 nodes out of 4.  Your cluster may not be working".  I am going to try the manual add as you suggested for the other 2 nodes.

**Comment by jeffmendoza** [comment]
In Azure the machines are created serially, so the minions are slow to come up. It would be great to have a loop here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/azure/util.sh#L464 similar to the one here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/azure/util.sh#L424 to wait for the minions to come up and have salt install docker, etc. Any takers? =)

**Comment by v1s0n** [comment]
I can take a stab at it...but it's not going to happen right away.... to be continued..

**Comment by roberthbailey** [comment]
Assigning this to @v1s0n based on the last comment.

**Comment by roberthbailey** [comment]
... or not. Seems that github won't let me.

**Comment by errordeveloper** [comment]
Would an issue reported agains 0.7.0 be worse considering as we are in 0.14.0 era now?
