### ISSUE TITLE
e2e test build timed out

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#31776]
See https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/30825/kubernetes-pull-build-test-e2e-gce/56572/

```
Dumping logs for any remaining nodes
+ ./cluster/log-dump.sh _artifacts
Dumping master and node logs to _artifacts
scp: /var/log/cluster-autoscaler.log: No such file or directory
scp: /var/log/kern.log: No such file or directory
scp: /var/log/startupscript.log: No such file or directory
ERROR: (gcloud.compute.copy-files) [/usr/bin/scp] exited with return code [1]. See https://cloud.google.com/compute/docs/troubleshooting#ssherrors for troubleshooting hints.
+ [[ 124 -eq 124 ]]
+ echo 'Build timed out'
Build timed out
+ echo 'Exiting with code: 124'
Exiting with code: 124
+ exit 124
```

**Comment by ixdy** [comment]
I've been seeing a fair number of job timeouts lately. I'm not sure if there's a pattern.

@kubernetes/test-infra-maintainers

**Comment by fejta** [comment]
@mml Hi Matt! 

From a quick glance this does not look like test-infra.

Rather it looks either like a) the job's timeout is configured too low (please send a PR to increase it) b) tests are doing something dumb (please send a PR to improve the tests or c) the product is running slow (send a PR to improve the product).

Neither a, b or c is test-infra (something like the jenkins VMs being overloaded, jenkins failing to set the correct timeout specified in the job configuration, etc).

If you identify a potential where the test-infra that is misbehaving please reassign back.

**Comment by ixdy** [comment]
We have encountered some weird timeout issues where tests were getting stuck, which did eventually end up being a test-infra issue. I can't remember the details anymore, though. @spxtr @rmmh ?

**Comment by calebamiles** [comment]
no updates to this issue in 2017. Closing this issue.

**cc: @ethernetdan, @kubernetes/release-team**
