### ISSUE TITLE
Master Metrics API available in api server

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#31784]
Master Metrics API is implemented in Heapster #23376. It should be available in api server. The rough plan is to:
1. refactor Heapster to be api server by using generic api server library
2. set up discovery summarizer to work well with multiple api servers
3. set up clients to use discovery summarizer
4. change kubectl top/hpa to use it

I will send a proposal soon.

follow up #23376

**Comment by piosz** [comment]
@deads2k @smarterclayton @lavalamp @wojtek-t @fgrzadkowski @davidopp @erictune 
@kubernetes/sig-instrumentation @kubernetes/autoscaling @kubernetes/sig-api-machinery

**Comment by smarterclayton** [comment]
@kubernetes/sig-auth FYI for the work with authorization federation.  Also @liggitt and @deads2k because you guys were discussing the requirements for the summarizer.

**Comment by smarterclayton** [comment]
Do you anticipate having a proposal soon?  I assume this is a 1.5 target?

**Comment by smarterclayton** [comment]
Which SIG owns this - API machinery, autoscaling, metrics?

**Comment by davidopp** [comment]
Does the autoscaling SIG still exist?

Anyway I would say sig-instrumentation.

**Comment by smarterclayton** [comment]
When we were doing sig-instrumentation we said it did not cover metrics
explicitly.  I would expect metrics / autoscaling to be disjoint from
instrumentation.

On Mon, Sep 12, 2016 at 6:37 PM, David Oppenheimer <notifications@github.com

**Comment by davidopp** [comment]
Do you have a link to this discussion? The idea that instrumentation does not include metrics sounds odd to me. At the least, it sounds closer than autoscaling...

**Comment by smarterclayton** [comment]
https://groups.google.com/d/msgid/kubernetes-dev/7721ee1f-08cb-4b57-966c-c6dd9ad6456d%40googlegroups.com
<https://groups.google.com/d/msgid/kubernetes-dev/7721ee1f-08cb-4b57-966c-c6dd9ad6456d%40googlegroups.com?utm_medium=email&utm_source=footer>

On Mon, Sep 12, 2016 at 6:47 PM, David Oppenheimer <notifications@github.com

**Comment by davidopp** [comment]
I read that as saying not to combine instrumentation with consumers of the instrumentation (like autoscaling) -- not that instrumentation doesn't include metrics. I can see that there might be multiple interpretations, but I don't know what the instrumentation SIG would talk about if they exclude metrics?

**Comment by fabxc** [comment]
Yes, that was my understanding too. This was actually more about naming it from "monitoring", which could arguably include logging etc., to "instrumentation", which actually puts an emphasis on metrics. There are consumers of metrics that are not monitoring, but auto-scaling for example. SIG instrumentation should also care about enabling these use cases. The statement was more to referring initial concerns that were mostly resolved during that discussion

That should be clarified in an official mission statement.

**Comment by fgrzadkowski** [comment]
I think this should be owned by sig-instrumentation. 

@smarterclayton Why do you ask which SIG owns this?

**Comment by DirectXMan12** [comment]
On historical precendent: SIG-autoscaling has largely dealt with Heapster-related changes in the past (it's been closer to SIG-autoscaling-and-Heapster).

On the current state of affairs/my view of the distinction: SIG-autoscaling largely deals with making metrics available for consumption by cluster components (such as the HPA controller, and perhaps things like InitialResources in the future), as well as autoscaling-related cluster components themselves.

On the flip side, SIG-instrumentation seems, so far, to deal largely with collecting metrics (both metrics which describe cluster consumption, like CPU usage, and metrics which describe cluster state, such as number of active deployments, etc) for use in viewing and visualizing cluster state and cluster health (presumably things like altering as well).

There is certainly some overlap, but they're also different concerns with different requirements in many cases.  Considering that the current primary consumer of the Master Metrics API is the HPA controller (also, I'd imaging that instrumentation functionality would involve the sink itself, not a short-term metrics API), I'd say that this feature work should *probably* be sponsored by SIG-autoscaling.

**Comment by piosz** [comment]
This is sponsored by sig-instrumentation, but should be done in coordination with sig-api-machinery because  it's mostly about touching the code owned by the latter one.

Regarding @DirectXMan12's comment HPA should care about API rather than implementation. Since the API is defined (in alpha version, though there is no plans to change it) and this is mostly implementation detail sig-autoscaling is only a little interested in this.

Regarding sig-instrumentation scope I think this is mostly about monitoring and logging (logging because it's tightly coupled area and there is not much sense in having another sig for this purpose).

**Comment by davidopp** [comment]
@piosz Can you explain what discovery summarizer does? Is it just a demux/router for Kubernetes REST API requests?

**Comment by smarterclayton** [comment]
Yes - it's an intelligent proxy for hiding details of multiple API backends
from clients

On Sep 22, 2016, at 7:41 PM, David Oppenheimer <notifications@github.com>
wrote:

@piosz <https://github.com/piosz> Can you explain what discovery summarizer
does? Is it just a demux/router for Kubernetes REST API requests?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/31784#issuecomment-249059359>,
or mute the thread

**Comment by DirectXMan12** [comment]
this is done and/or out of date

/close
