### ISSUE TITLE
intersection of running as non-root, minikube, hostPath = not working well

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#31796]
Reported by a user in slack:

Running minikube.  Container uses Docker's USER directive in Dockerfile.  Want to run pod in minikube to dev and cloud for prod.  The only PV we support so far is hostPath.  User experiences failure to write to PV.

Suggested fix was `fsGroup`, but hostPath does not support volume ownership management.

Need a better abstraction here.  Overlaps with #30044 perhaps?

@bprashanth @pmorie @matchstick

**Comment by bprashanth** [comment]
stickyemptydir just allows claiming normal emptydir through a pv with data gravity, so we'd get all the ownership settings
