### ISSUE TITLE
docs for PersistentVolume "capacity" field

### ISSUE THREAD

**Issue by jmhodges** [kubernetes/kubernetes#31792]
Currently, in the docs, the PersistentVolume's "capacity" field has the [schema of `object`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#persistentvolumespec-v1-core) and [the PersistentVolume docs](http://kubernetes.io/docs/user-guide/persistent-volumes/#capacity) it links to do not describe the format of the capacity field, nor does [the Resource Model docs](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/resources.md) that those docs link to. (At least, not obviously. I don't think it's a `resourceCapacitySpec`?

**Comment by jmhodges** [comment]
/remove-lifecycle stale

I think this still could use better docs. The ones linked still do not explain what the possible schemas are for that field.

**Comment by nikhita** [comment]
/remove-sig api-machinery

@k8s-ci-robot please work this time.

**Comment by nikhita** [comment]
/remove-lifecycle stale

still relevant

**Comment by jmhodges** [comment]
This still seems relevant. I've updated some of the links as they broke in the meantime

**Comment by jmhodges** [comment]
(I'm not able to adjust the lifecycle tags, though)

**Comment by jmhodges** [comment]
Thank you!

**Comment by jmhodges** [comment]
I think this is still relevant. The resource docs still don't say how to ask for storage. There's something marked "[future]" which I believe is not how it works today.

**Comment by jmhodges** [comment]
I think this is still fresh? I don't believe I have the /remove-lifecycle permissions
