### ISSUE TITLE
[node e2e] Confusing result: 1 Failure, 0 Failed

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#31802]
From https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/30739/node-pull-build-e2e-test/22156:

```
Summarizing 1 Failure:

[Fail] [k8s.io] Pods [It] should contain environment variables for services [Conformance] 
/var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2125

Ran 97 of 129 Specs in 562.705 seconds
SUCCESS! -- 97 Passed | 0 Failed | 0 Pending | 32 Skipped 

Ginkgo ran 1 suite in 9m25.151025459s
Test Suite Passed

Success Finished Test Suite on Host tmp-node-e2e-4e4fc36a-e2e-node-containervm-v20160321-image
```

The cause is the `--flakeAttempts=2` flag, as identified in https://github.com/kubernetes/kubernetes/issues/31538#issuecomment-242844342. This is a confusing result message though, and we should show something less confusing. E.g.

```
Summarizing 1 Flake:

[Fail] [k8s.io] Pods [It] should contain environment variables for services [Conformance] 
/var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2125

Ran 97 of 129 Specs in 562.705 seconds
SUCCESS! -- 96 Passed | 1 Flake | 0 Failed | 0 Pending | 32 Skipped 

Ginkgo ran 1 suite in 9m25.151025459s
Test Suite Passed

Success Finished Test Suite on Host tmp-node-e2e-4e4fc36a-e2e-node-containervm-v20160321-image
```

This might require a ginkgo change.

/cc @ixdy @Random-Liu @kubernetes/sig-node @kubernetes/sig-testing

**Comment by timstclair** [comment]
I'm marking this as P0 until we understand what's going on, since this scares me (are we missing test failures?)

**Comment by yujuhong** [comment]
Oh this is because the test retry feature added in jenkins. See https://github.com/kubernetes/kubernetes/issues/31538#issuecomment-242844342

**Comment by timstclair** [comment]
Ah, thanks for clarifying Yuju! I think we should try to provide a more clear error message though. I'll keep this open but lower the priority to fix that.

**Comment by Random-Liu** [comment]
@timstclair It's jenkins deciding how to print this. :) We should probably improve jenkins.

**Comment by timstclair** [comment]
I thought it was ginkgo?

**Comment by ixdy** [comment]
It's probably both. Also I'm not sure Gubernator shows this in a useful way. @rmmh

**Comment by spxtr** [comment]
I'd suggest a ginkgo change, but we should also make sure our tooling understands this as well.

**Comment by Random-Liu** [comment]
> I thought it was ginkgo?

Yeah, typo. I edited that comment immediately.

**Comment by ixdy** [comment]
For reference, the PR which added flake support to Ginkgo is https://github.com/onsi/ginkgo/pull/261.
