### ISSUE TITLE
kube-dns needs to support graceful termination.

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#31807]
I think we should trap SIGTERM and just keep running.  This will cause the API-driven graceful termination.  It will be removed from LBs and eventually SIGKILLed.  In the mean time LBs will be smoother.

We probably can't get this into 1.4.0, but might consider it for a point-release given how simple the implementation should be.

@girishkalele

**Comment by MrHohn** [comment]
The current implementation registers SIGINT and SIGTERM. When they occur it will call glog.Fatalf() which leads to os.Exit(255). Do you mean we should instead discard the SIGTERM signal and exit the program when SIGKILL occurs? Or program would gracefully exit according to the msg from stopChannel?

I am not very clear about the relationship between kube-dns and LBs. Does LB mean LoadBalancer?

**Comment by MrHohn** [comment]
Is this for the scenario while scaling down the kube-dns? We want those terminating kube-dns pods continue to provide dns service until they are completely remove from the service endpoints pool.

**Comment by thockin** [comment]
Yes, I think that ignoring SIGINT would be better.  What happens is this:

* Assume you have DNS with 2 backends, X and Y, on two nodes, N and M
* Someone (user, deployment, controller, whatever) says "delete pod X"
* API server sets deletion time to now+30s
* This effectively means X is "not-ready"
* Roughly in parallel:
  a) controller manager sees the not-ready and removes X from the DNS
endpoint set
  b) kubelet sees the not-ready and sends SIGTERM
* kube-proxy sees the endpoints change and stops sending to X
* a few seconds pass (at least)
* cloud LBs fail healthchecks for DNS on N and remove N from the set

If, for example, (a) and (b) happen in the reverse order, you can see
SIGTERM landing before the pod has been removed from LBs.  Worse,
kube-proxy actually has to get a second-order notification, so it could be
sending traffic to X after X has SIGTERM'ed and died.  WORSE, the cloud LBs
take a few seconds to catch up.

If kube-dns ignores SIGTERM, the LBs will all get updated, stop sending
traffic, etc.  30 seconds later kube-dns dies.  This is better in every
way, I think.

**Comment by MrHohn** [comment]
Make sense, thanks for elaborating! Will make a PR soon.
