### ISSUE TITLE
Use weights when decreasing replicas number in federated replica set with rebalance=false  

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#31816]
Currently no weights are used and the result may be very unbalanced. For example, if weight is 1 for all clusters and rebalance = false and we have 10 replicas in A and 70 in B and replica count is reduced to 20 the end result may be B=20 (depending on hashing - see #31814), while A=10 B=10 would be more preferred.

**Comment by mwielgus** [comment]
cc: @quinton-hoole @jianhuiz @kubernetes/sig-cluster-federation

**Comment by quinton-hoole** [comment]
Required for GA of federation. Prioritizing accordingly.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#70.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
