### ISSUE TITLE
Expand docs on dnsPolicy

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#31813]
ref http://stackoverflow.com/questions/38285676/kubernetes-connect-to-the-outside-world-from-pod/38752535?noredirect=1#comment65804352_38752535

k8s.io doesn't seem to have anything and the swagger for podSpec.dnsPolicy just says 

```
dnsPolicy (string, optional): Set DNS policy for containers within the pod. One of 
'ClusterFirst' or 'Default'. Defaults to "ClusterFirst". ,
```

**Comment by dims** [comment]
switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree)

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by tgraf** [comment]
I'll be working on this for 1.7.

**Comment by thockin** [comment]
Update on this?

**Comment by bowei** [comment]
@dchen1107 punt to next

**Comment by matchstick** [comment]
This is a nice to have for 1.7. @tgraf please see if you can address this soon (by tomorrow) to make 1.7. If not I don't think this documentation is required for the release.

**Comment by thockin** [comment]
@bowei - keep or kill?

**Comment by thockin** [comment]
@bowei this will expire soon
