### ISSUE TITLE
kubernetes-e2e-aws is broken on Jenkins due to AWS capacity issue - need to move to a different zone

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#31832]
It looks like AWS is out of capacity in our chosen test zone.  So we need to configure the tests to a different zone.  cc @colhom @justinsb FYI

e.g. 
"12:49:12 Starting Master 12:49:19 12:49:19 An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation: We currently do not have sufficient m3.medium capacity in the Availability Zone you requested (us-west-2a). Our system will be working on provisioning additional capacity. You can currently get m3.medium capacity by not specifying an Availability Zone in your request or choosing us-west-2b, us-west-2c. 12:49:19 2016/08/31 12:49:19 e2e.go:455: Error running up: exit status 255"

**Comment by colhom** [comment]
@quinton-hoole this should&trade; have been fixed as a result of kubernetes/test-infra#497 merging. Close this out if/when the tests go green?

**Comment by goltermann** [comment]
@quinton-hoole is this fixed?

**Comment by quinton-hoole** [comment]
The tests are not yet green, but for reasons unrelated to this issue, and tracked elsewhere.   kubernetes/test-infra#497 apprears to have done it's job.  Closing this.
