### ISSUE TITLE
Termination log can only be written to by root

### ISSUE THREAD

**Issue by elyscape** [kubernetes/kubernetes#31839]
Pod specs let you specify a value for `terminationMessagePath`. The intent is for this to be a file that gets mounted into a container into which it ["will write its ‘death rattle’?, such as assertion failure messages, stack traces, exceptions, and so on"](http://kubernetes.io/docs/user-guide/production-pods/#termination-message). When a container exits, any contents of the termination message file are collected [in the container's status](http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_containerstateterminated) to aid in debugging. Unfortunately, the permissions on the termination log are too narrow:

``` shellsession
$ ls -l /dev/termination-log
-rw-r--r--. 1 root root 0 Aug 31 22:15 /dev/termination-log
```

If the container is not running as root, it won't have the permissions necessary to write to the termination log.

**Kubernetes version** (use `kubectl version`):
I'm using OpenShift Origin 1.2.1, which is built on Kubernetes 1.2.0, but the problem comes from upstream Kubernetes and is still present.

``` shellsession
$ oc version
oc v1.2.1
kubernetes v1.2.0-36-g4a3f9c5
```

**Environment**:
Not really applicable, but:
- **Cloud provider or hardware configuration**: AWS c4.4xlarge
- **OS** (e.g. from /etc/os-release): CentOS 7.2.1511
- **Kernel** (e.g. `uname -a`): `Linux [REMOVED] 3.10.0-327.28.2.el7.x86_64 #1 SMP Wed Aug 3 11:11:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**: [openshift-ansible](https://github.com/openshift/openshift-ansible)
- **Others**: None?

**What happened**:
`/dev/termination-log` is only writable by root.

**What you expected to happen**:
`/dev/termination-log` should be writeable by the process in the container.

**How to reproduce it** (as minimally and precisely as possible):
1. Create a pod that doesn't run as root.
2. Try to write to `/dev/termination-log`

**Anything else do we need to know**:
This appears to be caused by the fact that the kubelet creates the file on the host and then doesn't modify the permissions ([docker](https://github.com/kubernetes/kubernetes/blob/v1.4.0-alpha.3/pkg/kubelet/dockertools/docker_manager.go#L637), [rkt](https://github.com/kubernetes/kubernetes/blob/v1.4.0-alpha.3/pkg/kubelet/rkt/rkt.go#L724)). A simple fix would probably be to just add group write permissions to the file, as container processes are part of the root group.

**Comment by dims** [comment]
Looks like there was an earlier issue as well. https://github.com/kubernetes/kubernetes/issues/28947

**Comment by elyscape** [comment]
Good catch! I looked but didn't find that.

**Comment by dims** [comment]
@elyscape : will you be able to try a small change to see if it works in your environment?

```
diff --git a/pkg/kubelet/dockertools/docker_manager.go b/pkg/kubelet/dockertools/docker_manager.go
index 8b6429f..b32454d 100644
--- a/pkg/kubelet/dockertools/docker_manager.go
+++ b/pkg/kubelet/dockertools/docker_manager.go
@@ -644,6 +644,7 @@ func (dm *DockerManager) runContainer(
                        // TODO: Clean up the previously created dir? return the error?
                        glog.Errorf("Error on creating termination-log file %q: %v", containerLogPath, err)
                } else {
+                       fs.Chmod(0666)
                        fs.Close() // Close immediately; we're just doing a `touch` here
                        b := fmt.Sprintf("%s:%s", containerLogPath, container.TerminationMessagePath)
                        binds = append(binds, b)
```

**Comment by elyscape** [comment]
I'll test it out in a VM shortly.

**Comment by smarterclayton** [comment]
Note that this field currently is dangerous to use by non-root users - because there is no size limited imposed, a malicious pod can break the apiserver and kubelet.

**Comment by elyscape** [comment]
Oh. Well, that's fun.

**Comment by smarterclayton** [comment]
There's a bug open for it - just wanted you to be aware.

**Comment by dims** [comment]
@smarterclayton I could not find the bug. would be good to link it here if you get a chance.

@elyscape How about using tmpfs to essentially place a max limit? The following seems to work (still trying to figure out where to do the un-mount)

```
diff --git a/pkg/kubelet/kubelet.go b/pkg/kubelet/kubelet.go
index 3f49c34..d31a8b4 100644
--- a/pkg/kubelet/kubelet.go
+++ b/pkg/kubelet/kubelet.go
@@ -1402,6 +1402,9 @@ func (kl *Kubelet) GenerateRunContainerOptions(pod *api.Pod, container *api.Cont
                if err := os.MkdirAll(p, 0750); err != nil {
                        glog.Errorf("Error on creating %q: %v", p, err)
                } else {
+                       mounter := mount.Mounter{}
+                       options := []string{"size=64k", "mode=0755"}
+                       mounter.Mount("tmpfs", p, "tmpfs", options)
                        opts.PodContainerDir = p
                }
        }
```

Tested using:
```
root@pod-w-message:/dev# head -c 32k </dev/urandom >termination-log
root@pod-w-message:/dev# head -c 63k </dev/urandom >termination-log
root@pod-w-message:/dev# head -c 65k </dev/urandom >termination-log
head: write error: No space left on device
```

**Comment by smarterclayton** [comment]
https://github.com/kubernetes/kubernetes/issues/23569

**Comment by elyscape** [comment]
@dims That's a good idea! 64KB might be a bit large, but obviously the exact size can be changed. The only additional consideration I can think of is that it might be a good idea to copy the file out from the tmpfs mount at termination time, so that historical termination messages can be reviewed even after a reboot of the host, so long as the pod hasn't been deleted.

**Comment by nhlfr** [comment]
I like @dims' idea. But I think we should chown it to the exact user that Docker image is using, instead of chmoding with 777. We can get the username from `docker inspect`. What do you think?

**Comment by smarterclayton** [comment]
I think it needs to be the user the container runtime intends to run the process as (which is slightly different and has some challenges).

**Comment by nhlfr** [comment]
Of course. In case of rkt runtime, we will need to get info about user from ACI manifest (it's available there). The mechanism for getting the user for which we need to chown has to be abstract and defined in each runtime.

**Comment by smarterclayton** [comment]
There are some implications of clowning that the storage guys weigh in on -
we have a "philosophy of what to chown" that tries to do the right thing.
 @pmorie when we've gone through emptyDir and configmap and secrets what
lessons about chown / control should we apply here?

If someone for instance starts as uid 0 and then drops privilege they
wouldn't have access to write to the file, which is very common.

**Comment by elyscape** [comment]
I think for emptyDir the current strategy is to provide group write access.

**Comment by elyscape** [comment]
Just wondering if there's been any progress on this.

**Comment by smarterclayton** [comment]
I plan on fixing this in 1.6 along with the max limit issue.

**Comment by elyscape** [comment]
Fantastic. Thanks for your help!

**Comment by smarterclayton** [comment]
The problem was the umask - we have to chmod specifically after writing the file because 0666 from os.Create is umasked.
