### ISSUE TITLE
Conversion is generating v1 -> v1 rules if a type only exists in external

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#31849]
For backwards compatibility we support various types that exist in external API versions but not internal.  Those fields have structs in v1, are marked as `// +k8s:conversion-gen=false`, but have no internal types.  Custom conversions turn them into the new field.

The generator is currently creating rules `Convert_v1_TYPE_to_v1_TYPE` if a type only exists in v1.  It should only generate when there is a matching type internally externally.

Recreate:
1. Create a struct in v1
2. Reference that from an existing struct as a field
3. Set that field as `// +k8s:conversion-gen=false`.
4. Run `make`, get v1_to_v1

@thockin @wojtek-t caught this as I was updating Openshift to 1.4.  Will try to come up with a fix if you guys don't know what changed recently (this worked in 1.3).

**Comment by thockin** [comment]
I have not touched this code since the big changes a month + ago.

**Comment by wojtek-t** [comment]
I think that Tim`s changes are the only one I can think about that potentially could affect it (I'm not aware of anything else since 1.3)
