### ISSUE TITLE
Can't recover from a 502 within verify-godeps.sh

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#31842]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/31722/kubernetes-pull-verify-all/12062/
```
... skipping 1392 lines ...
SUCCESS  hack/make-rules/../../hack/verify-godep-licenses.sh	9s
Verifying hack/make-rules/../../hack/verify-godeps.sh
Checking for 'Godeps/' changes against 'remote/master'
Starting to download all kubernetes godeps. This takes a while
# cd .; git clone https://go.googlesource.com/exp /tmp/gopath.qVrG3C/src/golang.org/x/exp
Cloning into '/tmp/gopath.qVrG3C/src/golang.org/x/exp'...
error: RPC failed; result=22, HTTP code = 502
fatal: The remote end hung up unexpectedly
godep: error downloading dep (golang.org/x/exp/inotify): exit status 128
godep: Error downloading some deps. Aborting restore and check.
Removing /tmp/gopath.qVrG3C
FAILED   hack/make-rules/../../hack/verify-godeps.sh	141s
Verifying hack/make-rules/../../hack/verify-gofmt.sh
SUCCESS  hack/make-rules/../../hack/verify-gofmt.sh	9s
Verifying hack/make-rules/../../hack/verify-golint.sh
cmd/libs/go2idl/generator/snippet_writer_test.go is in package generator_test, not generator
cmd/libs/go2idl/parser/doc.go is in package parser, not parser_test
contrib/mesos/pkg/scheduler/service/validation_test.go is in package service_test, not service
... skipping 82 lines ...
    cmd/hyperkube
SUCCESS  hack/make-rules/../../hack/verify-symbols.sh	134s
Verifying hack/make-rules/../../hack/verify-test-images.sh
SUCCESS  hack/make-rules/../../hack/verify-test-images.sh	0s
Verifying hack/make-rules/../../hack/verify-flags-underscore.py
SUCCESS  hack/make-rules/../../hack/verify-flags-underscore.py	41s
Makefile:99: recipe for target 'verify' failed
make: *** [verify] Error 1
Build step 'Execute shell' marked build as failure
[xUnit] [INFO] - Starting to record.
[xUnit] [INFO] - Processing JUnit
[xUnit] [INFO] - [JUnit] - No test report file(s) were found with the pattern '_artifacts/**.xml' relative to '/var/lib/jenkins/workspace/kubernetes-pull-verify-all' for the testing framework 'JUnit'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'JUnit'?
[xUnit] [WARNING] - No test reports found for the metric 'JUnit' with the resolved pattern '_artifacts/**.xml'.
[xUnit] [INFO] - Skipping the metric tool processing.
... skipping 15 lines ...
```

**Comment by mml** [comment]
@kubernetes/test-infra-maintainers

**Comment by rmmh** [comment]
Please link to the full build page.

**Comment by rmmh** [comment]
Looks like this is a common thing to have to workaround :( https://codereview.chromium.org/701843004

**Comment by rmmh** [comment]
The verify script is running `godep restore`, which is an external project.

Verify-godeps takes a long time (~10 minutes) and is flaky. Maybe we shouldn't run it on PRs that haven't touched a vendors/ or any files with "godep" in the name?

**Comment by ixdy** [comment]
@rmmh we already do that. The linked PR has changes to `staging/src/k8s.io/client-go/1.4/Godeps/Godeps.json`.

**Comment by rmmh** [comment]
Where is that logic? #31833 ran verify-godeps without relevant changes: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/31833/kubernetes-pull-verify-all/12065/build-log.txt

**Comment by ixdy** [comment]
@rmmh it certainly used to work. https://github.com/kubernetes/kubernetes/blob/master/hack/verify-godeps.sh#L46-L51

Maybe something changed recently?

**Comment by mml** [comment]
@ixdy even if that logic is working, this problem still shows up.  Using `git-retry` from depot_tools—as @rmmh suggested—would keep people (like me :-) from having to investigate and file bugs (like this one :-) about transient errors.

**Comment by ixdy** [comment]
This `git` failure was from well within `godep` and `go`. I'm not sure how easily we can make it retry.

**Comment by rmmh** [comment]
The verify-godeps skipping has been fixed, so this low-probability flake will now only apply to the tiny percentage of PRs that touch Godeps.

I filed tools/godep#511 to track this issue.
