### ISSUE TITLE
kubenet: local/internet bandwidth shaping

### ISSUE THREAD

**Issue by josselin-c** [kubernetes/kubernetes#31876]
FEATURE REQUEST: Per destination bandwidth shaping

While it's now possible to add a per-pod bandwidth limit with annotations `kubernetes.io/{ingress,egress}-bandwidth` this limit is set on the pod regardless of the trafic's origin/destination.

In our use-case we would like to host containers for other companies in our Kubernetes cluster. While we would like the local<->local bandwidth to be unlimited, we want to limit the internet-egress bandwidth of theses pods to avoid paying egress charges on them.
Another option would be per-deployment internet-egress accounting but I couldn't find anything on this.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
bandwidth:
https://github.com/kubernetes/kubernetes/issues/11965
https://github.com/kubernetes/kubernetes/issues/2856

shaper:
https://github.com/kubernetes/kubernetes/pull/11988
https://github.com/kubernetes/kubernetes/pull/23740

---

**Kubernetes version** (use `kubectl version`): 1.3.5

**Environment**:
- **Cloud provider or hardware configuration**: Google GKE
- **OS** (e.g. from /etc/os-release): Debian Wheezy
- **Kernel** (e.g. `uname -a`): 3.16.0-4-amd64

**Comment by freehan** [comment]
CC @kubernetes/sig-network

**Comment by cmluciano** [comment]
kubenet is being deprecated in favor of CNI plugins
