### ISSUE TITLE
Ubuntu provider script is failing and not able to reach api-server (ubuntu,cluster,ubuntuProvider script)

### ISSUE THREAD

**Issue by Rachitmehrotra** [kubernetes/kubernetes#31879]
I have installed in one single node and one master node setup this is not working,same thing was working for me in kubernetes version 1.3.0 15 days back,please tell me the fix .

**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):NO

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):1.3.6

**Environment**:
- **Cloud provider or hardware configuration**:NO
- **OS** (e.g. from /etc/os-release):
  root@masternode:/home/vagrant/kubernetes/cluster# cat /etc/os-release
  NAME="Ubuntu"
  VERSION="14.04.4 LTS, Trusty Tahr"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu 14.04.4 LTS"
  VERSION_ID="14.04"
  HOME_URL="http://www.ubuntu.com/"
  SUPPORT_URL="http://help.ubuntu.com/"
  BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
- **Kernel** (e.g. `uname -a`):Linux masternode 3.13.0-92-generic #139-Ubuntu SMP
- **Install tools**:
- **Others**:
  Linux masternode 3.13.0-92-generic #139-Ubuntu SMP
  export KUBERNETES_PROVIDER=ubuntu
  export KUBE_VERSION=1.3.0 and 1.3.6
  export FLANNEL_VERSION=0.5.0
  export ETCD_VERSION=2.2.0

**What happened**:

The connection to the server 10.10.103.250:8080 was refused - did you specify the right host or port?
(kubectl failed, will retry 2 times)
The connection to the server 10.10.103.250:8080 was refused - did you specify the right host or port?
(kubectl failed, will retry 1 times)
The connection to the server 10.10.103.250:8080 was refused - did you specify the right host or port?
('kubectl get nodes' failed, giving up)
The connection to the server 10.10.103.250:8080 was refused - did you specify the right host or port?
(kubectl failed, will retry 2 times)
The connection to the server 10.10.103.250:8080 was refused - did you specify the right host or port?
(kubectl failed, will retry 1 times)
The connection to the server 10.10.103.250:8080 was refused - did you specify the right host or port?
**What you expected to happen**:

**Comment by castrojo** [comment]
The old provider scripts are not supported anymore, have you tried kubeadm yet? It's in beta but already more robust than the old scripts.
