### ISSUE TITLE
PreStop hooks that fail to complete in time should generate a pod event

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#31902]
Right now, we spawn an event when a container preStop hook fails, but we provide no event when the preStop hook fails to complete within the pods terminating graceperiod.  This can confuse end-users.  We should also generate an event when the hook fails to complete in time.

/cc @aveshagarwal @kubernetes/sig-node @smarterclayton @vishh

**Comment by derekwaynecarr** [comment]
Related: https://github.com/kubernetes/kubernetes/issues/24820

**Comment by smarterclayton** [comment]
Makes sense to me.  We also need to document that preStop hooks are *not*
blocking.

**Comment by vishh** [comment]
Do pre-stop hook's runtime get accounted towards a pod's termination grace
period?

In general, I agree that we should generate events for all timeouts.

**Comment by smarterclayton** [comment]
Yes - logic as of 1.2 (or maybe 1.3) is:

1. Start the timer
2. Call prestop
3. If timer expires, or prestop exits, call docker stop with max(minimum
grace period, remaining grace period)
4. docker stop applies SIGTERM then max() then SIGKILL

Minimum grace period is always 2 seconds on the theory that SIGTERM than
SIGKILL is always better than SIGKILL.
