### ISSUE TITLE
e2e test failure: Rescheduler [Serial] should ensure that critical pod is scheduled in case there is no resources available

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#31901]
It's failing in every kubernetes-e2e-gce-serial-release-1.4 run

@piosz says "This is probably because of the fact the Rescheduler is disabled by default. I'll sent a PR which exports flag to enable it in this suite, but how about enabling it by default in gce?"

cc/ @piosz @fgrzadkowski @pwittrock 

Marking as flake just so we track it, even though it's deterministic.

**Comment by piosz** [comment]
The plan is to enable it by default in GKE, so probably we should enabled it by default in GCE as well. Also Rescheduler seems to be stable - e2e test is passing constantly for >1week.

**Comment by piosz** [comment]
fixed by https://github.com/kubernetes/test-infra/pull/495
