### ISSUE TITLE
Don't clobber taints

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#31906]
Concurrent runs of kubectl taint on the same node can end up clobbering one another because we update the `scheduler.alpha.kubernetes.io/taints`annotation with the entire taints list through a merge patch. 

i.e

``` console
$ kubectl patch node e2e-test-beeps-master -p '{"metadata":{"annotations":{"test":"[\"foo\", \"bar\"]"}}}'
$ kubectl patch node e2e-test-beeps-master -p '{"metadata":{"annotations":{"test":"[\"foobar\"]"}}}'
```

will give you an annotation `"test": "[foobar]"`
This is probably causing https://github.com/kubernetes/kubernetes/issues/29503 and https://github.com/kubernetes/kubernetes/issues/31066 because we run tests in parallel. 

@kubernetes/sig-scheduling

**Comment by ncdc** [comment]
cc @aveshagarwal

**Comment by davidopp** [comment]
@kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
A quick question: can we just make the kubectl taint e2e tests run not in parallel?

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/blob/release-1.4/docs/devel/e2e-tests.md#kinds-of-tests

**Comment by bprashanth** [comment]
I don't know if serial tests block merges yet

**Comment by kevin-wangzefeng** [comment]
Just checked PR e2e scripts, 
+ test args of GKE smoke e2e is `GINKGO_TEST_ARGS=--ginkgo.focus=Guestbook`
+ test args of GCE e2e is `export 'GINKGO_TEST_ARGS=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]'`

I think serial tests won't block PR merges.

**Comment by ConnorDoyle** [comment]
Hi @kevin-wangzefeng, have you started working on this issue? If not @balajismaniam or I could take it on.

**Comment by kevin-wangzefeng** [comment]
@ConnorDoyle not yet. I've added retries in all the places in "kubectl taints" e2e tests, but it seems the fail rate is still high, see also #29503, #32535. 

Making "kubectl taints" e2e tests may help, but serial tests don't actually run every PR, not sure if marking these tests with `[Serial]` would actually fix (tests no longer run as often as they were).

**Comment by kevin-wangzefeng** [comment]
Taints have been moved to nodeSpec, out of annotations, closing since it won't happen again.
