### ISSUE TITLE
Expose active service health checks via kube-proxy REST monitoring interface

### ISSUE THREAD

**Issue by girishkalele** [kubernetes/kubernetes#31916]
Follow-up item from the ESIPP feature from Tim.

It would be nice to have a way to read the list of services with active health checks on kube-proxy...add a new endpoint to the existing REST monitoring interface to read these, along with the nodePort used for each.
And maybe stats about keepalives received and responded successful/unsuccessful.

**Comment by cmluciano** [comment]
@girishkalele Are you still interested in working on this?
