### ISSUE TITLE
etcd dependency not handled properly.

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/kubernetes#31915]
`hack/update-swagger-spec.sh` calls `kube::etcd::start` by way of `hack/lib/etcd.sh`.
But kube::etcd::start() uses etcd from the path and ETCD_VERSION requires that version or later.

The dependent etcd should either be part of an image or the host machine could install the latest version on the fly to a temporary working location or verify the one on the path in an early prereq check that all dependencies on the host system are up to date.

cc @ixdy @spxtr @pwittrock @mbohlool

**Comment by dims** [comment]
switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree)
