### ISSUE TITLE
Kube-dns should use versioned client-go

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#31929]
In prep to maybe move kube-dns to its own repo, we should adopt the new client lib.

**Comment by MrHohn** [comment]
Would like to work on this. I'm using versioned client-go for [cluster-proportional-autoscaler](https://github.com/kubernetes/cluster-proportional-autoscaler) too.

**Comment by MrHohn** [comment]
I met some difficulty when try to use client-go library with current codes.

The main issue is that kube-dns is using `informer` from ["k8s.io/kubernetes/pkg/controller/framework"](https://github.com/kubernetes/kubernetes/tree/master/pkg/controller/framework), which is not part of the client-go library. And this pakage continue introduces the dependencies of ["k8s.io/kubernetes/pkg/api"](https://github.com/kubernetes/kubernetes/tree/master/pkg/api), ["k8s.io/kubernetes/pkg/api/unversioned"](https://github.com/kubernetes/kubernetes/tree/master/pkg/api/unversioned), ["k8s.io/kubernetes/pkg/runtime"](https://github.com/kubernetes/kubernetes/tree/master/pkg/runtime) etc. And they eventually conflict with the underlying dependencies of ["k8s.io/client-go/1.4/kubernetes"](https://github.com/kubernetes/client-go/tree/master/1.4/kubernetes)

And in kubernetes/client-go#4, people mentioned that somebody proposed a refactoring to the `informer` and I would need to do more research on it. Or we simply don't use `informer`. However that will lead to a certain amount of code changes.

**Comment by thockin** [comment]
ACK.  If we're going to do major surgery to kube-dns we should consider
whether that is the right time to switch to coredns or (other).  OK to
defer this for now.

**Comment by MrHohn** [comment]
Seems like it is an oversight and folks intended to include this Informer library too.

I will again work on this after this library is included.

**Comment by stp-ip** [comment]
Coredns has its first release available (https://github.com/miekg/coredns/releases) might be a good time to check it out.

**Comment by caesarxuchao** [comment]
> Seems like it is an oversight and folks intended to include this Informer library too.

Yeah, I'll move informer to the library, too. Perhaps next week.

**Comment by thockin** [comment]
@bowei is this done now?

**Comment by bowei** [comment]
It currently uses client-go, but not the versioned one -- opened issue https://github.com/kubernetes/dns/issues/35

**Comment by bowei** [comment]
closing as this is tracked in the dns repo
