### ISSUE TITLE
Deprecate the old cbr0 logic in kubelet?

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#31937]
We've switched to using kubenet as default for a while. Do we still test the old cbr0 logic? If not, I'd rather see it deleted than having no-longer-tested code hanging around, gathering bugs.

Thoughts? Do people still rely on this feature?

/cc @freehan @thockin @dchen1107

**Comment by freehan** [comment]
cc @luxas

**Comment by thockin** [comment]
I'm happy to see it go, but I think the decision is Minhan's - he has the
best context on it.

**Comment by dchen1107** [comment]
I also want this go away. But if I remembered correctly, not everyone switch to kubenet yet. cc/ @justinsb

**Comment by yujuhong** [comment]
@freehan also agreed that this should go when I mentioned yesterday. The question remains is whether anyone is still using it.

Adding a deprecation warning may be a good start? 

/cc @kubernetes/sig-node @kubernetes/sig-network

**Comment by thockin** [comment]
yeah, maybe we can announce the deprecation for 1.5 and nuke it from 1.6?
Or squeeze a deprecation warning into 1.4?

**Comment by luxas** [comment]
I made a similar issue for this earlier here https://github.com/kubernetes/kubernetes/issues/30589

I'm a lot in favor for deprecating the old cbr0 logic and the experimental flannel overlay mode in v1.4 with `release-note-action-required` and nuking them in v1.5

**Comment by bprashanth** [comment]
As have we all https://github.com/kubernetes/kubernetes/issues/17795 :)
removing --experimental-flannel-overlay is a much easier argument to make than deleting --configure-cbr0. It's fewer, more isolated loc that was put in for a specific use case and has since been rendered obsolete. easy to throw away even in 1.4, probably doesn't even need a deprecation because "experiemental" == "alpha". We might as well delete the debri in one fell swoop though, easier to communicate intent.

**Comment by yujuhong** [comment]
> Or squeeze a deprecation warning into 1.4?

+1 to this. Deprecation warning seems fair enough for 1.4.

**Comment by luxas** [comment]
> Deprecation warning seems fair enough for 1.4.

@yujuhong, @bprashanth or @freehan can someone of you do it? :)

**Comment by freehan** [comment]
just did it in #31197

**Comment by justinsb** [comment]
Sounds good .. I'll switch kops to use kubenet by default (https://github.com/kubernetes/kops/issues/400)

I suspect I am not the last holdout though, so a deprecation warning sounds appropriate.

Generally if you open an issue against kops when changing defaults, I'll make sure it happens there in a more timely fashion :-)

**Comment by luxas** [comment]
Anyone working on this?
We should do it now so it can make v1.5

@yujuhong @freehan @thockin @justinsb

**Comment by yujuhong** [comment]
@luxas there is no one working on this AFAIK, and @freehan most likely won't have spare cycles this release. 

If anyone wants to pick this up, that'd be great.

**Comment by luxas** [comment]
Here we go: #34906
