### ISSUE TITLE
Failed to delete dynamic provisioned volumes in different zones with master

### ISSUE THREAD

**Issue by liangxia** [kubernetes/kubernetes#31948]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
\# kubectl version
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.3.317+2a28917e0a7487", GitCommit:"2a28917e0a7487e302f9c754340a112a5243f04f", GitTreeState:"clean", BuildDate:"2016-09-01T05:48:36Z", GoVersion:"go1.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.3.317+2a28917e0a7487", GitCommit:"2a28917e0a7487e302f9c754340a112a5243f04f", GitTreeState:"clean", BuildDate:"2016-09-01T05:48:36Z", GoVersion:"go1.7", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:
Dynamic provisioned volumes in different zones with master failed to deleted

**What you expected to happen**:
Since the volume can be dynamic provisioned when the zones differs from master, then it should be deleted after delete the PVC which created them.

**How to reproduce it** (as minimally and precisely as possible):
1. Set up an all-in-one cluster. The instance is created in zone us-central1-a.
2. Create several storageClass. One in zone us-central1-a. Another in zone us-central1-b.
3. Create several PVC. pvc1 using storageClass1(zone us-central1-a), pvc2 using storageClass2(zone us-central1-b).
4. Verify PV/volume were provisioned in proper size/mode/zone.
5. Delete PVCs.
6. PV with volume in zone us-central1-b failed with error can not find the volume.

**Anything else do we need to know**:
\# oc describe pv pvc-01c43644-70d1-11e6-b17e-42010af00002
Name:		pvc-01c43644-70d1-11e6-b17e-42010af00002
Labels:		failure-domain.beta.kubernetes.io/region=us-central1
		failure-domain.beta.kubernetes.io/zone=us-central1-c
Status:		Failed
Claim:		default/pvc5
Reclaim Policy:	Delete
Access Modes:	RWO
Capacity:	4Gi
Message:	Delete of volume "pvc-01c43644-70d1-11e6-b17e-42010af00002" failed: GCE persistent disk not found: "kubernetes-dynamic-pvc-01c43644-70d1-11e6-b17e-42010af00002"
Source:
    Type:	GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
    PDName:	kubernetes-dynamic-pvc-01c43644-70d1-11e6-b17e-42010af00002
    FSType:	
    Partition:	0
    ReadOnly:	false
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  11m		11m		1	{persistentvolume-controller }			Warning		VolumeFailedDelete	Delete of volume "pvc-01c43644-70d1-11e6-b17e-42010af00002" failed: GCE persistent disk not found: "kubernetes-dynamic-pvc-01c43644-70d1-11e6-b17e-42010af00002"

\# gcloud compute disks describe kubernetes-dynamic-pvc-01c43644-70d1-11e6-b17e-42010af00002 --zone=us-central1-c
creationTimestamp: '2016-09-01T22:49:26.439-07:00'
description: '{"kubernetes.io/created-for/pv/name":"pvc-01c43644-70d1-11e6-b17e-42010af00002","kubernetes.io/created-for/pvc/name":"pvc5","kubernetes.io/created-for/pvc/namespace":"default"}'
id: '4179438167010880521'
kind: compute#disk
name: kubernetes-dynamic-pvc-01c43644-70d1-11e6-b17e-42010af00002
selfLink: https://www.googleapis.com/compute/v1/projects/openshift-gce-devel/zones/us-central1-c/disks/kubernetes-dynamic-pvc-01c43644-70d1-11e6-b17e-42010af00002
sizeGb: '4'
status: READY
type: https://www.googleapis.com/compute/v1/projects/openshift-gce-devel/zones/us-central1-c/diskTypes/pd-ssd
zone: https://www.googleapis.com/compute/v1/projects/openshift-gce-devel/zones/us-central1-c

**Comment by jsafrane** [comment]
Kubernetes can delete GCE PDs only in zones it manages. I.e. either in the same zone as the master or, when multizone is enabled in GCE config, in all zones in the same region.

> 3. Create several PVC. pvc1 using storageClass1(zone us-central1-a), pvc2 using storageClass2(zone us-central1-b).

This should not be allowed in the first place. Kubernetes should not create disks outside zones it manages and report an error instead.

So... please use following gce.conf, it will be allow creation/deletion of disks in all zones in us-central1 region:

```
[global]
multizone=true
```

And I'll fix Kubernetes to report an error when creating a disk in all other zones.
