### ISSUE TITLE
PetSet.Status.Replicas is not accurate

### ISSUE THREAD

**Issue by nebril** [kubernetes/kubernetes#31965]
**Is this a request for help?** Nope

**What keywords did you search in Kubernetes issues before filing this one?** petset replicas current desired

**Is this a BUG REPORT or FEATURE REQUEST?** BUG

**Kubernetes version** Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"not a git tree", BuildDate:"2016-09-01T10:49:36Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"not a git tree", BuildDate:"2016-09-01T10:49:36Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: 24 cores, 64 GB RAM
- **OS** Arch Linux
- **Kernel** (e.g. `uname -a`): Linux hostname 4.4.13-1-lts #1 SMP Wed Jun 8 16:44:31 CEST 2016 x86_64 GNU/Linux
- **Install tools**: local-cluster-up.sh
- **Others**:

**What happened**:
While creating PetSet based on this tutorial: http://kubernetes.io/docs/user-guide/petset/ first PetSet pod was stuck in pending state due to lack of PersistentVolumes in cluster.

When getting the petset info via `kubectl get petset` I expected to see "CURRENT" set to 1, while the kubectl output was as follows:
```
NAME      DESIRED   CURRENT   AGE
web       2         2         59m
```
While `kubectl get pods` clearly shows that only one pod is created:
```
NAME      READY     STATUS    RESTARTS   AGE
web-0     0/1       Pending   0          1h
```

In json and yaml output, status.replicas value was also 2.

**What you expected to happen**:
I expected that CURRENT value shown by kubectl would be `1` due to only one pod being created.

**How to reproduce it** (as minimally and precisely as possible):
Create https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/release-1.3/docs/user-guide/petset.yaml via `kubectl create -f` on empty cluster and run `kubectl get pods` and `kubectl get petsets`.

**Anything else do we need to know**: Nope

**Comment by kargakis** [comment]
CURRENT is the number of pods that have been created, not that they are READY. See for example the latest api change for replica sets where we added [ReadyReplicas](https://github.com/kubernetes/kubernetes/pull/29481) exactly for this reason. All controllers (petsets, daemonsets, deployments, etc.) should have ReadyReplicas

cc: @bgrant0607

**Comment by nebril** [comment]
@kargakis I guess it doesn't work anyway, since only one pod was created for this PetSet, but the CURRENT says that 2 were created. I will change bug description then.

**Comment by bprashanth** [comment]
Hmm, the idea is to sync every pet periodically, but only create them one at a time. The logic that counts status.replicas is wrong. This counter shouldn't be incremented in the case where we didn't update/sync or create a pet: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/petset/pet_set.go#L344. Today we do increment it all pet creation is blocked on the first pet becoming unhealthy. 

Should be an easy fix if anyone wants to jump in (@foxish fyi) otherwise I'll get to it once 1.4 is out.

**Comment by r2d4** [comment]
@bprashanth I'm looking to get into k8s dev and this bug looks manageable.  Mind if I take a stab?

**Comment by nebril** [comment]
@bprashanth I can try to fix it if that's OK. Thanks for the pointer to the source code!

**Comment by bprashanth** [comment]
Please do, co-assigned
