### ISSUE TITLE
Design appropriate node eviction policy for HA master

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#31966]
When cluster will span multiple availability zones and masters will be spread between zones as well current node eviction policy in node controller most likely won't work. We need to figure out what the correct behavior should be in such case.

cc @davidopp @lavalamp @mml @jszczepkowski @fgrzadkowski @derekwaynecarr @thockin

**Comment by dims** [comment]
@gmarek @saad-ali @calebamiles - switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree)

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by spiffxp** [comment]
@kubernetes/sig-scalability-feature-requests do you want this in v1.7? is this the right sig to own this issue?

**Comment by mml** [comment]
@gmarek this is about the situation when a large number of nodes go unreachable at once, right?

Can we be a little more specific about a case where the current code would do the wrong thing, even if we don't know what the right thing is?

**Comment by gmarek** [comment]
We should be more specific, but I don't know if anyone knows that. It depends on the setup I guess. It's possible that it'll do the correct thing, but no someone should investigate.
