### ISSUE TITLE
Gerneric delete in federated namespace controller

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#31975]
In PR #31976 the specific resource types are handled explicitly. Need to delete them in more generic way, in a similar way that namespace controller does.

**Comment by dims** [comment]
@mwielgus @saad-ali @calebamiles - switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree)

**Comment by liggitt** [comment]
@nikhiljindal did https://github.com/kubernetes/kubernetes/pull/35950/ fix this?

**Comment by csbell** [comment]
@nikhiljindal Please close or move to next-candidate with work remaining to be done.

**Comment by nikhiljindal** [comment]
Yes fixed by https://github.com/kubernetes/kubernetes/pull/35950
