### ISSUE TITLE
node-e2e test to validate kubelet's /summary 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#31989]
We already have 
- monitoring test which tests the entire monitoring pipeline: kubelet/cadvisor, summary api, heapster, even influxdb, etc. 
- tests to check system containers' stats through summary api for resource tracking
- cadvisor tests to validate cadvisor logic

But  we don't have a comprehensive test to validate summary api itself. If we do, both https://github.com/kubernetes/kubernetes/issues/27194 and https://github.com/kubernetes/kubernetes/issues/30939#issuecomment-244436150 might be caught earlier. 

cc/ @timstclair

**Comment by dchen1107** [comment]
@timstclair has a pending https://github.com/kubernetes/kubernetes/pull/29479 addressing this a while back.

**Comment by dims** [comment]
@dchen1107 @timstclair : ok to close this issue? Looks like #29479 merged a while ago

**Comment by timstclair** [comment]
Yes, thanks.
