### ISSUE TITLE
404 from remote server not being treated as a "not found" on client

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#32009]
The client library has `NewGenericServerResponse` for handling unexpected errors.  It's supposed to be invoked in `transformUnstructuredResponseError` which is called from `transformResponse`.  That error is supposed to be semantically equal to valid api.StatusErrors returned by the server so that `apierrors.IsNotFound(err)` would return true for any 404.

In #31873 the teardown code of e2e tests which delete the namespace get back an error (that from the apiserver reports a 404) but that error does not report true for `apierrors.IsNotFound(err)`.  As a result it flags the error.

Either the error from the server is wrong (malformed, bad content type, bad proxy) or the client is improperly handling the response.  I can't find any proof that the client mishandles generic 404s from the server (via restclient `transformUnstructuredResponseError`).

Setting to p1 while I triage to see what the impact of correcting the issue is.  Potentially 1.4 if this indeed is hiding / causing other errors.

**Comment by smarterclayton** [comment]
@kubernetes/sig-api-machinery triaging now

**Comment by spxtr** [comment]
I linked all the tests that have hit this in the last day or two. I would argue for P0 based on the number.

**Comment by smarterclayton** [comment]
Could potentially be related to a specific case - hitting a namespace that has been deleted.

**Comment by soltysh** [comment]
Handled already in #32009.

**Comment by smarterclayton** [comment]
The additional logging showed that this is caused by a single not
found being wrapped by an Aggregate.  NotFound can't handle aggregates
at all.

Several things need to be changed:

* RESTClient and generated clients shouldn't use aggregates
* aggregate of one is dumb - we should not allow it
* api errors checks should decompose aggregates that are all of one
kind (all not found is logically not found).

Will open PRa

**Comment by smarterclayton** [comment]
```
(d *DiscoveryClient) serverPreferredResources(namespaced bool)
```

returns an aggregate - it means one of the fetches failed.  If discovery fails we may not have a full list of resources, so we return each error.  I don't think NotFound on a discovery API is equivalent to NotFound on a namespace.

So this is surfaced by @derekwaynecarr's changes - occasionally we are getting 404's from the server resources.  Going to open a second PR that adds more debugging and fast track that.

**Comment by derekwaynecarr** [comment]
@smarterclayton -- we could make the e2e cache the call once, but I didn't do that at the time because I did not know the state of third party resource e2e.

**Comment by lavalamp** [comment]
agree aggregates of 1 are super dumb. NewAggregate probably needs a fix.

**Comment by smarterclayton** [comment]
My worry is that changes the semantic of NewAggregate (before you could
assume it would respond to certain calls, which is not true now).  And that
probably just hides the problem - we should never use aggregates in a case
that someone has to handle it.

Pulling together a fix right now.

**Comment by derekwaynecarr** [comment]
@smarterclayton - I think we can close this given #32182 has merged?

**Comment by smarterclayton** [comment]
Not until we know what the actual error underneath was.  Probably some sort of transient from the server.

**Comment by derekwaynecarr** [comment]
I think the underlying error was this: https://github.com/kubernetes/kubernetes/pull/32302

**Comment by ncdc** [comment]
@smarterclayton ready to close this now?

**Comment by smarterclayton** [comment]
Yes, #32302 was it.
