### ISSUE TITLE
Umbrella: Allow a 3rd party plugin to run on top of a Kubernetes cluster

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#3201]
This is a tracking issue to cover the open issues and features necessary for running a significant 3rd party extension on top of a Kubernetes cluster.  Depending on the complexity of an extension, some or all of these may be needed.  At this time, the most complex extension is [OpenShift](https://github.com/openshift/origin) and the items below these derive from those use cases, but I expect as other components that wish to extend or integrate with the cluster (logs, heapster, auditors, cluster integrations) are developed these will be useful.

The end result of this issue, as required features are implemented, should be a document describing how to build new cluster components that expose new capabilities on top of the core cluster services, what best practices should be followed, what design patterns to avoid, and to encode useful patterns into libraries and examples when someone wishes to "extend Kubernetes to do X".  Some of the items discussed below may not fit into that document - they will be moved into other umbrella issues or their own as time goes on.  Note, some of these overlap with regular application features, but are specifically listed here because in an ideal cluster components become aware of their environment and can use its APIs to leverage the flexibility the cluster manager provides.
### Use cases (still WIP)
- Allow components running on the infrastructure...
  - To be highly available
  - To have persistent storage that can survive the death of individual nodes for data persistence
    - In small clusters, it is sufficient to allow some components access to the core etcd (suitably protected)
    - In larger clusters, it is preferable to allow components to run their own available data stores (overlaps with database use case)
  - To have new versions deployed predictably
  - To securely connect to the API server with high level authority (delegate cluster admin control to a component) and be configured with that authority automatically
  - To perform pass through or delegated authentication for an API consumer that has a token for accessing the core services
  - To set and configure security policy via API (or allow an admin to easily define additional policy)
- Allow core client tools to...
  - Discover REST resources provided by a plugin and operate on them in a generic fashion (simple CRUD operations) - [discussed](https://github.com/GoogleCloudPlatform/kubernetes/pull/1355)
  - Apply standard patterns of templatization, creation, and behavior to any resource that follows the core patterns [discussed](https://github.com/GoogleCloudPlatform/kubernetes/issues/1702)
  - Be easily reused by 3rd party client creators (kubectl, pkg/client, future UI) to build extensions of the core behavior - [implemented](https://github.com/GoogleCloudPlatform/kubernetes/pull/2682)
    - Design the kubectl commands so they can easily be tweaked to add new resources, or change the display and help text
    - Ensure reviewers are aware of the additional reqts on the kubectl code
    - Add unit tests to `pkg/kubectl` that verify generic kubectl commands do not depend on Kube specific globals
- Allow a cluster to be configured...
  - To use a different scheduler - [implemented](https://github.com/GoogleCloudPlatform/kubernetes/issues/357) / [example](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/plugin/cmd/kube-scheduler/scheduler.go)
  - To use a different authentication / identity provider - [designed](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/access.md#authentication)
  - To use a different policy engine for authorization - [discussed](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/access.md#authorization)
    - An endpoint that could be configured via cluster config to make authorization decisions, provided by OpenShift or other service
  - To use a different admission controller on pod (or service, or RC, etc) so that different decision processes may be possible - [designed](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/admission_control.md)
  - So that an external plugin can contribute environment variables, volume configuration, or potentially security information into running pods without having to replace the scheduler or alter the code of the apiserver

**Comment by derekwaynecarr** [comment]
To do some of this, I think we need to allow what we pass as command line options to potentially be changed via API and stored in etcd.

**Comment by smarterclayton** [comment]
Can you clarify which ones you feel that way about?  It may also be acceptable to not allow these to be configured on the fly, such that an administrator makes the choice to enable feature X (to get benefit Y)

**Comment by ghodss** [comment]
Expanding client tool capabilities and cluster configuration options sounds great, but for running the actual 3rd party components, can they not simply be configured and run as standard Kubernetes pods/replication controllers/services/etc.? As long as all communication with them is done over HTTP, it seems like a standard container could be hooked into any part of kube. What are the special cases that need components to be run in a special way?

**Comment by smarterclayton** [comment]
Any component that needs to affect the behavior of the core cluster - authn/authz, policy, add new fundamental types like volume plugins, alter the behavior of the kubelet, etc - needs some special consideration.  There are other points, like how a pod gets security access to invoke the pods api at a higher level than a normal user, that still must be resolved.  And they won't be over HTTP, but HTTPS, so the pods need a valid trust chain to the master and maybe client certs.

Most of this issue is about pulling together all of the core work so that the cloud OS "kernel" can support user space effectively (which includes things that are on the boundary between kernel and core service).

**Comment by tristanz** [comment]
I just want to strongly +1 this issue.  OpenShift is already significantly expanding the number of Kubernetes objects, including with names that are pretty generic:

http://docs.openshift.org/latest/architecture/core_objects/openshift_model.html

This is great, but to have the ecosystem play well together, it seems necessary to have 1) proper namespacing of object kinds (or strong prefix conventions) and 2) a way to add and subtract a plugins while a cluster is running.

The motivation for extending Kubernetes directly, rather than just running services with their own APIs, is to provide a consistent experience for core cluster services.

**Comment by bgrant0607** [comment]
Re. namespacing of object kinds, see discussion near the end of #7111.

**Comment by derekwaynecarr** [comment]
To clarify, OpenShift serves its objects from a different API endpoint from normal Kubernetes objects.  

So you go to /api/v1/... for Kubernetes concepts and you go to /osapi/v1/... for OpenShift objects, so there is some inherent namespacing based on where you go to get the resource.

**Comment by bgrant0607** [comment]
API extensibility is a priority for post-1.0.

**Comment by lavalamp** [comment]
We have made steps for this, and in fact I think once we get @nikhiljindal's PR in it'll be possible to do this on top of a 1.2 cluster, but it's not going to be complete for 1.2.

**Comment by smarterclayton** [comment]
1.7 will deliver the first phase of initializers and external admission control.  1.6 delivered the aggregation api (and 1.7 moved it to beta).  TPR will move to beta as CRD in 1.7.  I think this can be marked as complete for the original intent, and we'll continue to iterate on those features without this.
