### ISSUE TITLE
Add e2e tests for Federated ReplicaSet cluster weighting/min/max

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#32014]
cc @jianhuiz As per https://github.com/kubernetes/kubernetes/pull/31904#issuecomment-244505671

Per design below.  Current e2e tests do not cover that functionality.

```
type FederatedReplicaSetPreferences struct {
    // Map from cluster name to preferences for that cluster. It is assumed that if a cluster 
    // doesn’t have a matching entry then it should not have local replica. The cluster matches 
    // to "*" if there is no entry with the real cluster name. 
    Clusters map[string]LocalReplicaSetPreferences
}

type LocalReplicaSetPreferences struct {
     // There should be at least this amount of replicas in the clusters. 0 if not specified.
    MinReplicas int
    // There should be at most this number of replicas in the cluster. Unbounded 
    // if not specified.
    MaxReplicas *int
    //  This weight should be used when spreading replicas across clusters
    Weight int
}

```

**Comment by dims** [comment]
@quinton-hoole Is this work still targeted for v1.4 milestone?

**Comment by quinton-hoole** [comment]
It's test code. It needs to be written and run before the release of v1.4.
But it doesn't necessarily need to be cherrypicked into the actual release
binary.

**Comment by pwittrock** [comment]
@quinton-hoole 

I am moving this out of the blocking issues we are tracking for the 1.4 release.  If there is still 1.4 work to be done here that should be tracked in the weekly burndown meetings, move it back and provide daily updates to this issue.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#71.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
