### ISSUE TITLE
Defining the equivalence pod

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#32024]
We assume equivalence pod will reduce scheduling latency in large scale.

I. Original discussion is https://github.com/kubernetes/kubernetes/issues/17390
There's a simple way introduced there to define the equivalence pod (by caching predicates & priorities), but during implementation https://github.com/kubernetes/kubernetes/pull/31605, we found that is not enough.

For example:
- Pods with different namespaces, since some predicates only consider pods in same namespace
- Labels should be considered?
- Special annotations, like affinity?
- Others

II. Another alternative is treating **instances of RC** as equivalence pods. 

This issue is for track this discussion and define the scope of equivalence.

cc @davidopp @wojtek-t

**Comment by wojtek-t** [comment]
Thanks for filing this issue.

Regarding first option - we definitely need a bunch of others, definitely labels, probably some annotations, etc.
My biggest fear in this approach is that if someone will add dependency on some new field at some point, we don't have good way to test it and ensure that equivalence pod will be updated at that point too.


Regarding second option - I think this is actually a very good choice. However, I would slightly modify it and use "ControllerRef" (which is defined as "OwnerReference (from ObjectMeta) with the "Controller" field set to true) as the "equivalence pod".
In this approach, we would have all RC, RS, Job, ... handled by exactly the same mechanism.
Also, this would be faster to compute it.

So personally I would go with second option, but please wait for buy-in from @davidopp before starting implementation.

**Comment by davidopp** [comment]
I definitely agree that ControllerRef approach is the best way to do this. If collection types that allow instances to be different from one another (like PetSet) become very popular at some point then we might need to switch to the first approach, but this is not necessary now.

**Comment by wojtek-t** [comment]
Actually PetSet is a good point here. So I think that we should do checking on: ControllerRef but limit it to just some types of controllers. But that's a very small implementation detail.

**Comment by davidopp** [comment]
Yes, good point.

**Comment by resouer** [comment]
So, let's follow option 2, just give me a few days to send the commits out :/

**Comment by resouer** [comment]
@davidopp @wojtek-t One thing I'm not quite sure is: some predicates are not suitable to Equivalent Class, for example, `PodFitsResources`, considering two pod with same `ControllerRef`, one successfully scheduled may lead another unfitted to the same candidate node list.

**Comment by wojtek-t** [comment]
@resouer - the trick is that as soon as something is scheduled on a given node, we are invalidating all cached results for this node. This solves most of the problems.

There is one remaining problem which is pod affinity/antiaffinity for which scheduling one pod may potentially invalidate all future pods on all nodes. I don't know how to solve it (other than just excluding this predicate and priority for caching, which isn't very good solution...)

**Comment by resouer** [comment]
Another thing is when new predicates added, how to update the existing equivalence strategy correspondingly.

**Comment by resouer** [comment]
For implementation of part 2, when scheduler doing `updatePodInCache` there's some cases we need to invalid pod's node's equivalence class here's a list in my mind:
```
PodFitsResources (containers' resource changed)
PodFitsHostPorts (pod host port changed)
PodSelectorMatches (pod selector changed)
PodFitsHost (pod.node.name changed)
CheckNodeMemoryPressure (pod QoS changed)
PodToleratesNodeTaints (tolerates changed?)
MatchInterPodAffinity (pod's Affinity Annotations changed)
```

And deciding if those filed changed need to use reflect deep copy.

**Comment by wojtek-t** [comment]
>
Another thing is when new predicates added, how to update the existing equivalence strategy correspondingly. // just a maintainance issue

Very good question. Let me throw some not fully baked idea.
We already know all the predicate function (there is a test that is checking if all of them are actually registered):
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates_test.go#L1632
What we should do is to require (using a similar test) that for all existing predicate functions, you set some information (either register there somewhere explicitly for equivalence-class purpose, or have some special comment, or something like that). If you will be explicitly setting such information, this will remind the PR author and the reviewer to think about it (which is our goal).

>
For implementation of part 2

Regarding the list - some of them are more complicated (e.g. InterPodAffinity).
On the other hand, you should also invalidate the whole node, when the node itself changes (well, probably only some of its fields...)

>
And deciding if those filed changed need to use reflect deep copy.

I don't understand this - can you please clarify?

**Comment by resouer** [comment]
Yes, what I am doing now is invalid the cache when node changed. I will send out a primitive PR so we can discuss there.

`And deciding if those filed changed need to use reflect deep copy.` I mean there will be many `reflect.DeepCopy()` in this part, is it allowed by convention?

**Comment by wojtek-t** [comment]
We generally don't want "reflect.DeepCopy". You can use api.Scheme.Copy (I think it is called that ) though.

**Comment by wojtek-t** [comment]
@resouer - since you asked for some pseudo-code, let me write what I think is missing

1. I think that we should add a method to cache to invalidate only a predicate with a given name (on all nodes). This should be pretty simple.
[Reason: in many cases (e.g. change in a volume) it doesn't make sense to invalidate all the cache, we can only invalidate predicates related to volumes].

2. In general I think that your PR #30844 is pretty good and we should just try to finish it.

My only request would be to have a very good comments in each "populator" what exactly you are invalidating and why.

So I think that once you rebase #30844 and apply this (changing a bunch of invalidate calls to ones tha invalidate only a particular predicate/predicates) it should be pretty close to go.

3. However, we obviously need some tests to have it committed.

**Comment by resouer** [comment]
@wojtek-t Oh, sorry for missing this comment, I will rebase and continue on https://github.com/kubernetes/kubernetes/pull/30844

**Comment by resouer** [comment]
> I think that we should add a method to cache to invalidate only a predicate with a given name (on all nodes). This should be pretty simple

Just a update, this requires refactor the exiting `HostPredicate` item in cache, I am doing, will finish in a few days.

**Comment by resouer** [comment]
@wojtek-t During writing up code, here is one thing I'd like to discuss. 

If we allow invalid specific predicate in ecache, we will need to:
1. store result (fit, failReasons) of predicate by predicateKey in ecache
2.`podFitsOnNode` will check if ecache item is available by predicateKey, and use the cached result instead of call `predicate` if so
3. after `predicate`, we need to update items in store by predicateKey

This actually break the implementation of #30844 , whose core idea is filtering out some Nodes with valid cache and use that part of result directly.

Do you think this make sense?  In one word, now we will check more Nodes, the only improvement is we will avoid  executing some `predicate`.

**Comment by wojtek-t** [comment]
OK - I see your point.
I think that we can try just doing the caching as you suggested (i.e. invalidate the whole node). And it if appears to be too slow, we will think how to improve it.
Does it sound ok?

**Comment by resouer** [comment]
@wojtek-t I have wrote a version which allow us to invalid the cache by specific predicate. Just not very sure if this way will improve the performance better than "invalidate the whole node". I think you also prefer to review the new version, right? ( otherwise I will rollback to the old version)

**Comment by resouer** [comment]
@wojtek-t [Quick Update] I found that scheduler now deal with `Schedule()` and `Bind()` in asynchronous way.  That means, when factory watched new pod added and invalidate `PodFitsResource` cache, other pods belong to same controllerRef have already been predicated with cached info (my e2e test also confirmed this). 

So we may have to give up cache `GeneralPredicates` (as scheduler use `GeneralPredicates` instead of `PodFitsResource`), `ServiceAffinity`, and `NoDiskConflict` (in GCE EBS RBD case). These three are what I think being influenced by pod add/delete. 

WDYT?

**Comment by wojtek-t** [comment]
>
@wojtek-t [Quick Update] I found that scheduler now deal with Schedule() and Bind() in asynchronous way. That means, when factory watched new pod added and invalidate PodFitsResource cache, other pods belong to same controllerRef have already been predicated with cached info (my e2e test also confirmed this).

That's a good point. However, I would suggest a different approach. Basically, I think that we should do something similar to what we do with schedulercache.
So when we are sending a binding request (asynchronously), before doing do that we optimistically assume that the pod will sucessfully schedule:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/scheduler.go#L115

We should do the the same for equivalance cache. By that I mean that we should invalidate all equivalnce functions that should be invalidated by this pod scheduled on that node. If it will schedule, then we're done. If not, the invalidation was unnecessary, but that doesn't break anything too.

**Comment by resouer** [comment]
According to some local tests, latest approach is at least as good as https://github.com/kubernetes/kubernetes/pull/30844. It may because we are actually running `findNodesThatFit` by parallel, that means reduce nodes needed to do predicate (see: https://github.com/kubernetes/kubernetes/pull/30844/files#diff-6a329a27bba0788de35c581fdf0b78bbR168) will not save schedule time significantly (as long as we always have `noCacheNodes `). (@wojtek-t correct me if I'm wrong here)

The affects of `just do part of predicates` still need evaluation.

**Comment by wojtek-t** [comment]
@resouer - sorry, I didn't understand the above.

**Comment by resouer** [comment]
@wojtek-t my mistake, I mean `podFitsOnNode` in parallel

**Comment by resouer** [comment]
close this  by #36238
