### ISSUE TITLE
bug: zsh completion re-inits complete completion system

### ISSUE THREAD

**Issue by philpennock** [kubernetes/kubernetes#32029]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): zsh

(Found a bug which I believe is a consequence of this bug, will mark it as such after filed)

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:29:08Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:06:06Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: GCE kubernetes
- **OS** (e.g. from /etc/os-release): MacOS 10.10.5
- **Kernel** (e.g. `uname -a`): Darwin tungsten.local 14.5.0 Darwin Kernel Version 14.5.0: Mon Aug 29 21:14:16 PDT 2016; root:xnu-2782.50.6~1/RELEASE_X86_64 x86_64
- **Install tools**:
- **Others**:

**What happened**:

Calling `source <( kubectl completion zsh)` did a re-init of the completion system, stomping over any settings already applied (alternative cache file locations, etc) and causing debugging problems.  (The gcloud SDK makes the same mistake).

**What you expected to happen**:

Define completions but don't call `compinit` which is a top-level command for completion system initialization which should only be called once and should not be called from within the completion definitions for a given command.

**How to reproduce it** (as minimally and precisely as possible):

```
ZDOTDIR=/some/path
. <( kubectl completion zsh)
ls -ld $ZDOTDIR/.zcompdump
```

**Anything else do we need to know**:

My current shell config workaround is to call:

`<( kubectl completion zsh | grep -v '^autoload .*compinit$' )`

Note that the GCloud `completion.zsh.inc` makes the same mistake, so needs to be edited to avoid the system initialization function to avoid triggering the bug there too.

Ideally the calls to compinit/bashcompinit would just be removed, but if there are user-support concerns from people who haven't otherwise enabled completion then you _might_ be able to get away with "force-enable completion with defaults unless already enabled".  In which case, this should work:

```
zmodload -i zsh/parameter
if ! (( $+functions[compdef] )) ; then
  autoload -U +X compinit && compinit
  autoload -U +X bashcompinit && bashcompinit
fi
```

This works because `compinit` is explicitly documented to provide the function `compdef` after called; the `zsh/parameter` loadable module provides the `functions` special associative array.  `zsh/parameter` will frequently have been loaded anyway, making the `zmodload` a no-op safety check (loadable modules are safe to request repeatedly, it's idempotent, unlike `compinit`).

**Comment by AdoHe** [comment]
@philpennock would you want to give a try to help fix this issue? I am not that familiar with shell completion.

**Comment by philpennock** [comment]
The above shell fragment should be good to use to replace the existing content in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/completion.go#L237 and the following line: just guard the invocation against it already having happened.  This reduces the likelihood of breaking a setup where someone is relying upon kubectl to do what it shouldn't have been doing.

Otherwise, sane options are:
1. Document correct setup, rely upon anyone using zsh and completion to already be initializing the completion system (poor, see below, despite being "correct")
2. Split completion into `kubectl completion zsh` and `kubectl completion zsh -noinit` or something?

The bad past behaviour, integrated into the existing shell setups of users outside of kubectl's commands, and done so by the people least aware of how to manage things correctly, are tying your hands here.

(I'm heading out and offline for the weekend, so can't help further right now, sorry).
