### ISSUE TITLE
the default  value of HorizontalPodAutoscaler.Spec.CPUUtilization

### ISSUE THREAD

**Issue by yarntime** [kubernetes/kubernetes#32041]
I think that it is not neccessary to set a default value to HorizontalPodAutoscaler.Spec.CPUUtilization, because some users only want to do horizon pod autoscale with custom metrics.

**Comment by erictune** [comment]
We don't change default values on stable APIs.

https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api_changes.md#on-compatibility
