### ISSUE TITLE
Syncing back _output/dockerized/bin directory from remote Docker - Time Out - boot2docker

### ISSUE THREAD

**Issue by georgepoenaru** [kubernetes/kubernetes#3207]
Please help me to debug this. 

I'm running boo2docker on OSX and for some reason it doesn't want to copy the output files from boot2docker vm into my local filesystem. 

+++ Syncing back _output/dockerized/bin directory from remote Docker
!!! Timed out waiting for binaries...

**Comment by erictune** [comment]
I ran into some boot2docker issues today.  I didn't root cause it, but I did `brew upgrade` and then `boot2docker upgrade` and some upgrades happened, and then things worked.  Maybe that will work for you.

**Comment by georgepoenaru** [comment]
Thank you, I’ll try.
Regards

George Poenaru
Mobile: +49 (0) 151 5721 4062
Phone: +49 (0) 30 9144 0177

**Comment by jbeda** [comment]
The recent (1.3) versions of boot2docker should map `/Users` from the host OS X machine into the boot2docker VM.  We *should* test to make sure that the it actually maps.

If you kubernetes root directory isn't under `/Users` it'll have to copy stuff back.  That code is a little new and there may be problems yet.

cc: @jameskyle as this stuff changed with https://github.com/GoogleCloudPlatform/kubernetes/pull/2692

**Comment by i0n** [comment]
I have also ran into this problem.

Using:

Boot2Docker-cli version: v1.4.1
Git commit: 43241cb

Kubernetes at: e27d534b87253f2c7ebb60fd6274ff864bc98e9c
or tag 0.10.1

**Comment by i0n** [comment]
Problem was with boot2docker not mounting the /Users folder correctly. Personally I would like to see the build process for Kubernetes decoupled from boot2docker. Any viable docker host would do, just check for the features required.

**Comment by jameskyle** [comment]
@i0n changes in the referenced merge (#2692) were motivated by a desire to decouple OS X development from boot2docker. They probably provide the use case you're looking for.

**Comment by i0n** [comment]
Awesome @jameskyle. Thanks for the info!
