### ISSUE TITLE
kubelet with --kubeconfig and --requite-kubeconfig gets itself into standalone mode

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#32085]
In practice this means that it doesn't get to update `nodeInfo` and thereby may refuse to admit pods which had been assigned to it by the scheduler. For example, if you update labels for that given node, and try to use affinity or `NodeLabels` on a pod, it won't get to run.

**Comment by errordeveloper** [comment]
Turns out this is only the case when `--require-kubeconfig` is set and no `--api-servers` are passed in... which is what we do in #31221. /cc @smarterclayton

**Comment by errordeveloper** [comment]
This looks like a sufficient fix for me, but I'm happy to add `--standalone` instead, if that'd help getting it accepted for 1.4.0:
```diff
diff --git a/cmd/kubelet/app/server.go b/cmd/kubelet/app/server.go
index fa3f5cc..f38d092 100644
--- a/cmd/kubelet/app/server.go
+++ b/cmd/kubelet/app/server.go
@@ -298,7 +298,7 @@ func initConfigz(kc *componentconfig.KubeletConfiguration) (*configz.Config, err
 
 func run(s *options.KubeletServer, kubeDeps *kubelet.KubeletDeps) (err error) {
        // TODO: this should be replaced by a --standalone flag
-       standaloneMode := (len(s.APIServerList) == 0)
+       standaloneMode := (len(s.APIServerList) == 0 && !s.RequireKubeConfig)
 
        if s.ExitOnLockContention && s.LockFilePath == "" {
                return errors.New("cannot exit on lock file contention: no lock file specified")

```
cc @smarterclayton @mikedanese

**Comment by errordeveloper** [comment]
cc @kubernetes/sig-cluster-lifecycle

**Comment by smarterclayton** [comment]
That commit makes sense to me.

**Comment by errordeveloper** [comment]
Thanks, @smarterclayton. I'll open a PR.
