### ISSUE TITLE
kube-proxy failed to connect to balancer :  missing endpoints

### ISSUE THREAD

**Issue by willstudy** [kubernetes/kubernetes#32080]
Hello, I encountered a problem and failed to fix it. (http://kubernetes.io/docs/user-guide/debugging-services )

My kube-proxy is working , pod is working, service is OK.  It is small probability of this error, about 0.01%。 Just likes this : 

Total request : 164171   Failed request : 18   Availability: 99.9890%
sandbox cluster ( nj02-dumi-sandbox-1.nj02 ) : access service failed

![2016-09-05 19 01 57](https://cloud.githubusercontent.com/assets/12168193/18247922/0c54c90e-73a8-11e6-818d-b548f1dde44f.png)

Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.3", GitCommit:"c6411395e09da356c608896d3d9725acab821418", GitTreeState:"clean", BuildDate:"2016-07-22T20:29:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.3", GitCommit:"c6411395e09da356c608896d3d9725acab821418", GitTreeState:"clean", BuildDate:"2016-07-22T20:22:25Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by cmluciano** [comment]
/close 

closing since issue is quite old and has not received more comments
