### ISSUE TITLE
Bootstrap kubernetes with etcd petset

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/kubernetes#32123]
Opening this issue to discuss possibility of bootstrapping Kubernetes with Etcd partially controlled with PetSets, partially created from static pods.
## In short

Create initial etcd cluster via static pods, deploy apiserver (and friends), deploy etcd PetSets recognizing pods of the initial etcd cluster (and turning them into pets), scale-up (and later down) the etcd cluster via PetSets controller if needed.
## More detailed

**Bootstrapping**:
1. designate three nodes for initial etcd cluster
2. toss etcd manifest to kubelet (settting peers to the three nodes), all three manifests are same up to their name, first pod is named `etcd-0`, second `etcd-1`, third `etcd-2`
3. kubelets creates 3 etcd pods, etcd in each pod is configured to form the initial etcd cluster
4. deploy apiserver, scheduler, controller-manager pointing to the initial etcd cluster
5. kubernetes is now up&running
6. deploy etcd petset (with `etcd` name) the way as first three pets would be scheduled to the three nodes
7. petset controller recognizes `etcd-0` up to `etcd-2` mirror pods and possible turn them into pets
8. now we have initial etcd cluster running and managed by kubelets and recognized by petset controller (recognized = as the pods would be created by the controller itself)

**Scalling up**
1. increase the number of replicas in etcd petset
2. new pets are scheduled to new nodes (must be set the way each pet has its own node if reasonable), maybe this feature needs to be implemented or a custom predicate in pod's specification must be created
3. etcd cluster size is increased, new etcd members are added dynamically as is defined in etcd petset specification

**Scalling down**
1. decrease the number of replicas
2. etcd cluster is decreased

Here, the number of replicas should not fall under the initial cluster size. If it does, etcd pets over the new size are kept managed by kubelet only (or the behaviour is undefined? constantly removing and recreating mirror pods? ).

**Stability**
1. if apiserver/controller goes down, at worst case all pets up to pets from the initial cluster are dead. Yet, the initial cluster lives as it is managed by kubelet.
2. if kubelet of one of the initial etcd members dies (e.g. `etcd-1`), petset controller creates new `etcd-1` pet. The question is what happens when the kubelet gets back online (now we have two instances of `etcd-1`). But that is not a new problem.
3. if both master components and all kubelet dies, we are doomed. So there is nothing much to do anyway. Redeploy cluster?

**Upgrades**

This can be tricky. First, manifests should be updated (e.g. newer image). Here, `etcd-{0,1,2}` are updated. Mirror pods are update as well (with the next sync loop?). Initial etcd members are upgraded. Then, petset controller can carry rolling update which results in upgrading initial members to the same specification they already are. Which is handled by kubelet at the end. So kubelet does not notice any change and informs apiserver the pet is upgraded. Petset controller continues with remaining `etcd-3` and up the usual way.

**Comment by ingvagabund** [comment]
@kubernetes/rh-cluster-infra

**Comment by ingvagabund** [comment]
@hongchaodeng's slides from the community meetings [1].

[1] https://docs.google.com/presentation/d/1Lqna6D_Vpk-HtXzTJ3atj8FG_0UUWLHphJ9Tl_OKqOk/edit#slide=id.g162b6d4a29_0_14

**Comment by ingvagabund** [comment]
Etcd petsets here [1].

[1] https://github.com/kubernetes/charts/tree/master/incubator/etcd

**Comment by ingvagabund** [comment]
@kubernetes/sig-cluster-lifecycle

**Comment by chrislovecnm** [comment]
How are TLS certs being handled with this setup? I assume that we are going to have TLS encryption a enabled between etcd servers.
