### ISSUE TITLE
fluentd-gcp crashed on rkt deployment

### ISSUE THREAD

**Issue by salrashid123** [kubernetes/kubernetes#32134]
**Kubernetes version** (use `kubectl version`):

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:29:08Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:38:31Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:  GCP
- **OS** (e.g. from /etc/os-release): 
  NAME=CoreOS
  ID=coreos
  VERSION=1068.10.0
  VERSION_ID=1068.10.0
  BUILD_ID=2016-08-23-0220
  PRETTY_NAME="CoreOS 1068.10.0 (MoreOS)"
  ANSI_COLOR="1;32"
  HOME_URL="https://coreos.com/"
  BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
- **Kernel** (e.g. `uname -a`):
  Linux kubernetes-minion-group-try0 4.6.3-coreos #2 SMP Tue Aug 23 02:14:16 UTC 2016 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux

**What happened**:
Tried deploying rkt on GCP but it fluentd-gcp kept crashing.   With the message:

```
Sep 06 16:03:57 kubernetes-minion-group-try0 systemd[1]: Stopped k8s_dfb82c18-5431-4e4e-900c-4438d905b94c.service.
Sep 06 16:03:57 kubernetes-minion-group-try0 systemd[1]: Started k8s_dfb82c18-5431-4e4e-900c-4438d905b94c.service.
Sep 06 16:03:57 kubernetes-minion-group-try0 kubelet[1569]: W0906 16:03:57.372066    1569 container.go:352] Failed to create summary reader for "/system.slice/k8s_dfb82c18-5431-4e4e-900c-4438d905b94c.service": none of the reso
Sep 06 16:03:57 kubernetes-minion-group-try0 nsenter[12333]: Failed to stat /var/lib/docker/containers: No such file or directory
Sep 06 16:03:57 kubernetes-minion-group-try0 systemd[1]: k8s_dfb82c18-5431-4e4e-900c-4438d905b94c.service: Main process exited, code=exited, status=1/FAILURE
Sep 06 16:03:57 kubernetes-minion-group-try0 systemd[1]: k8s_dfb82c18-5431-4e4e-900c-4438d905b94c.service: Unit entered failed state.
Sep 06 16:03:57 kubernetes-minion-group-try0 systemd[1]: k8s_dfb82c18-5431-4e4e-900c-4438d905b94c.service: Failed with result 'exit-code'.
```

Which mentions its explicitly looking for a folder on the minion called

 /var/lib/docker/containers

and that path is described here as a volume mount:

[fluentd-gcp.yaml](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/fluentd-gcp/fluentd-gcp.yaml#L39)

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

```
export KUBE_OS_DISTRIBUTION=coreos
export KUBE_GCE_MASTER_PROJECT=coreos-cloud
export KUBE_GCE_MASTER_IMAGE=coreos-stable-1068-10-0-v20160823
export KUBE_GCE_NODE_PROJECT=coreos-cloud
export KUBE_GCE_NODE_IMAGE=coreos-stable-1068-10-0-v20160823
export KUBE_CONTAINER_RUNTIME=rkt
```

then cluster/kube-up.sh

**Anything else do we need to know**:

i can get google-fluentd to not crash if i ssh into the vm and just create the folder mentioned

```
kubernetes-minion-group-try0 ~ # rkt list | grep running
51d73fae    elasticsearch-logging   gcr.io/google_containers/elasticsearch:1.9          running 14 minutes ago  14 minutes ago  
6119540e    elasticsearch-logging   gcr.io/google_containers/elasticsearch:1.9          running 15 minutes ago  15 minutes ago  
71c37402    kubedns         gcr.io/google_containers/kubedns-amd64:1.5          running 12 minutes ago  12 minutes ago  
c90e9549    node-problem-detector   gcr.io/google_containers/node-problem-detector:v0.1     running 17 minutes ago  17 minutes ago  
cabcc589    fluentd-cloud-logging   gcr.io/google_containers/fluentd-gcp:1.21           running 8 minutes ago   8 minutes ago   
d1ad9ae2    influxdb        gcr.io/google_containers/heapster_influxdb:v0.5         running 12 minutes ago  12 minutes ago  
dadc551d    kibana-logging      gcr.io/google_containers/kibana:1.3             running 12 minutes ago  12 minutes ago  
daf4bf73    heapster        gcr.io/google_containers/heapster:v1.1.0            running 13 minutes ago  13 minutes ago  
e5061de7    kubernetes-dashboard    gcr.io/google_containers/kubernetes-dashboard-amd64:v1.1.0  running 15 minutes ago  15 minutes ago  
f27f0873    default-http-backend    gcr.io/google_containers/defaultbackend:1.0         running 11 minutes ago  11 minutes ago  
```

**Comment by yifan-gu** [comment]
@salrashid123 Thanks for reporting. Unfortunately fluentd-gcp pod is docker specific, and it doesn't recognize the rkt pods' logging format (journal log files). Even it's running, it's not gathering rkt logs. We are working on general solution for supporting logging for multiple runtimes. https://github.com/kubernetes/kubernetes/issues/24677

**Comment by euank** [comment]
xref #26816 as well; that's why it fails earlier rather than later.

**Comment by salrashid123** [comment]
ok, thanks.   (yeah, i didn't expect it was running; knowing it wasn't crashing just helped me sleep a bit better :)   

anyway, please feel free to keep this open if needed or dup it to the issues cited above.

**Comment by yujuhong** [comment]
Closing since we are deprecating rktnetes (#53601)
