### ISSUE TITLE
Test Factory.PrintObject by fake command

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#32133]
When working on the patch for #31702 , it found `cmd_test.go` mock `Factory` manually by function pointer which should be done by gomock; and add more unit test in factory_test.go.

cc @smarterclayton / @AdoHe / @pwittrock

**Comment by smarterclayton** [comment]
We generally don't use go mock extensively since normal mocking should work well.  Is there a reason go mock would be better than the "default" pattern of:

```
type mockForTest struct {
  InterfaceToTest
}

func (mockForTest) FunctionToMock(...) {
  // mock implementation
}
```

?

**Comment by k82cn** [comment]
After making `Factory` as interface, we can not access its implementation class (factory). In `cmd_test.go`, it just mock some functions, e.g. `Object`; but when we call `factory`'s functions, it'll not use our mock functions.

**Comment by AdoHe** [comment]
@k82cn IIRC, we have talked about this on slack, anything block you now?
