### ISSUE TITLE
Allow service controller to indicate that it has cleared load balancer resources

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#32157]
**Issue**:
Create a type=LoadBalancer service.
When the user creates the service, service controller creates the corresponding cloud specific Load balancer. User can watch for load balancer to be created using ServiceStatus.
When user deletes the service, service controller deletes the corresponding LB. There is no way for user to know that service controller has deleted the LB.

**What you expected to happen**:
A way to figure out if cloud LB resources were deleted.

**Proposal**:
Use the finalizer/termination condition flow as in namespaces.
Service controller adds itself as a finalizer to each service.
When user deletes a service, apiserver sets the terminating condition on it.
Service controller observes that the service went in termination condition, it deletes the cloud resources it had created for that service, removes itself as finalizer and then deletes the service if there are no more finalizers.

cc @bgrant0607 @bprashanth @thockin @madhusudancs

**Comment by bprashanth** [comment]
We need to delete cloud resources even on type change, not just resource deletion. 

Users trust the the controller cleanus up cloud resources. If the controller leaks, it's a bug. I agree we currently don't have a way to surface this to the user, but it should not really happen because the controller is setup to reconcile and delete unused resources periodically.

If you kube-down, it *will* leak, this is a general problem: https://github.com/kubernetes/kubernetes/issues/16337
If you dete a service and immediately kube-down, it's the same situation.

**Comment by bgrant0607** [comment]
see also #4630

**Comment by nikhiljindal** [comment]
@bgrant0607 mentioned that we do not want to add a terminating condition. Presence of a deletion timestamp is enough indicator to indicate that the resource is being deleted.

cc @caesarxuchao

**Comment by nikhiljindal** [comment]
> We need to delete cloud resources even on type change, not just resource deletion.
> 

Yes hadnt thought of that. Good point.
So today if I change the type and then restart the controller, it will leak resources?

> Users trust the the controller cleanus up cloud resources. If the controller leaks, it's a bug. I agree we currently don't have a way to surface this to the user, but it should not really happen because the controller is setup to reconcile and delete unused resources periodically.
> 

Yes, I dont know of a bug in controller code. This issue is just to provide a way to tell the user that controller has done its work.

**Comment by thockin** [comment]
What is the state of finalizers?  I see it has been added as a generic
metadata field.  I tried to use it to prevent the deletion of a pod, and it
had no effect.  Is it done?

If finalizers work, is there any reason for us NOT to use them for ~every
such case?  For example, kubelet should put a finalizer on a pod before
starting it, so the pod can't be nuked.  Kubelet's job is then to remove
the finalizer, not to actually delete-without-grace the pod.

**Comment by thockin** [comment]
Ahh, I tried it on a different object, and it did seem to work.  I think
there are bugs.  Kubelet should not be nuking my finalizer.

**Comment by caesarxuchao** [comment]
I think it's a bug. I tried on services and it works. Probably we should move this line out of the if block:
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/generic/registry/store.go#L613.

**Comment by caesarxuchao** [comment]
We never caught this bug because all tests set finalizers on replication controller, never on pods.

**Comment by djsly** [comment]
I stumbled on a somewhat related issue, where I delete a namespace which contains a service configured to use the LoadBalancerType.

If we delete the namespace, poll the apiserver to ensure that it is indeed removed and recreate the Namespace it seems that the controller manager never as the time to delete the cloud resource and redetect the that service needs new IP. Ignoring the deletion. 

Find the full kube-controller-manager log in the following issue. 
https://github.com/kubernetes/kubernetes/issues/43730


Is there a way to ask that the api server returns "namespace doens't exists" only after all resources are removed, even the external resources ?

**Comment by colemickens** [comment]
Oh, are you pretty sure this is the root cause? #43730 ?

**Comment by djsly** [comment]
@colemickens I'm not 100% sure, but I wanted to share the logs with this thread to see if this was maybe related. It is hard to tell right now for the #43730 issue if it is a Azure Load Balancer implementation specific or someone more general at the controller-manager level.

**Comment by colemickens** [comment]
Can you try to repro:

* with a single master
* by deleting services instead of the NS

? Thanks!

**Comment by djsly** [comment]
@colemickens I have updated #43730 with the requested information. It turns out the deleting and recreating the same Service causes the IP to leak in Azure as well.

**Comment by thockin** [comment]
@bowei, we should understand what's up here

**Comment by bowei** [comment]
@thockin -- see analysis on the linked issue #43730

**Comment by djsly** [comment]
@thockin the latest analysis can be found here: https://github.com/kubernetes/kubernetes/issues/43730
ServiceController is processing the services one at the time. Once it gets the second deleted service from the queue, the service was recreated by the user (the apiserver didn't prevent the recreation). The SynchSErvice methods queries the apiserver to get the latest state of the service, getting back a newly created service with a pending publicIP state.

**Comment by MrHohn** [comment]
Is the cluster deletion case being considered here? What is the right signal for user to know all the LB resources have been cleaned up?

Ref: https://github.com/kubernetes/kubernetes/issues/51701

**Comment by nikhiljindal** [comment]
Thats the problem this issue proposes to solve. There is no signal for the user today to know that corresponding LB resources have been cleaned up.

Cluster deletion case can be solved as well, as long as the cluster deletion script waits for the existing resources (services, namespaces, etc) to be deleted.

**Comment by G-Harmon** [comment]
I hit this bug too. I am doing some scripting of creation/deletion of Ingresses, inside a namespace. When I delete the namespace, it still takes some time for the Ingress controller to clean up everything. I wanted a decent way to know when everything was cleaned up, and I could create a new ingress from a clean state.
/cc G-Harmon

**Comment by bgrant0607** [comment]
Related issues: #9106, #52670, #53451, #53193
