### ISSUE TITLE
Problem about how to increase the characters per line when using kubectl exec

### ISSUE THREAD

**Issue by lufeng4828** [kubernetes/kubernetes#32184]
Hi all,

first of all any help is appreciated

I want execute a command in a container and I execute:

kubectl exec -ti busybox bash 

but if I input about 70 characters in bash and then I get truncated output(line broken anyway) that is different from docker exec. 

is there a way to increase the characters per line when using kubectl exec? 

Environment (also see manifests for more detailed info):
Centos 7.0.1406
Kubernetes: 1.2.0
etcd: 2.3.7
flannel: 0.5.3
docker: 1.10.3

Thanks a lot for any suggestions.

**Comment by janetkuo** [comment]
This is fixed by #25273. Please wait for 1.4 release.

**Comment by lufeng4828** [comment]
thx!
