### ISSUE TITLE
FeatureRequest: add Contains to operator list in node affinity syntax

### ISSUE THREAD

**Issue by Blasterdick** [kubernetes/kubernetes#32195]
Kubernetes 1.3.6, Google Container Engine

I need to create pod in a specific node in my cluster with several node pools in it. 

And, it would be great, if I can scale node pools via Google Compute Engine built-in managed groups autoscaler (e.g by CPU usage).

But, I need to manually assign labels to nodes, and, with autoscaler enabled, it wouldn't be done.

So, my Pods won't be created in the newly created node in the same node pool, as it won't have an appropriate label.

So, I wonder, if I can use a part of a node name for a search pattern, kinda like this:

If `ClusterName` is `production` , and `NodePool` name is `frontend` , so `NodeName` would be like this: `gke-production-frontend-f9r23513f-27a9`, so I could write in YAML something like:

```
annotations:
          scheduler.alpha.kubernetes.io/affinity: >
            {
              "nodeAffinity": {
                "requiredDuringSchedulingIgnoredDuringExecution": {
                  "nodeSelectorTerms": [
                    {
                      "matchExpressions": [
                        {
                          "key": "kubernetes.io/hostname",
                          "operator": "Contains",
                          "values": [ "production-frontend" ]
                        }
                      ]
                    }
                  ]
                }
              }
            }
```

**Comment by adityaguru149** [comment]
/reopen
This would be a very nice feature/flexibility.
