### ISSUE TITLE
New Quota Resource for HTTP health checks

### ISSUE THREAD

**Issue by girishkalele** [kubernetes/kubernetes#32218]
We have resource usage/quota tracking for Services, ServicesLoadBalancer, ServicesNodePorts.

Do we also want to track HTTP Health Checks as a resource that can have a quota ?

**Comment by girishkalele** [comment]
cc @derekwaynecarr @ncdc @smarterclayton @kubernetes/sig-network

**Comment by derekwaynecarr** [comment]
Can you elaborate your scenario further?

**Comment by bprashanth** [comment]
hmm, that would involve tracking all cloud resources through some quota, not just http health checks (firewalls, target proxies, ssl certs, static ips, forwarding rules... and probably O(10) more per cloudprovider). Http health checks aren't really part of our kube api right? or have I misunderstood

**Comment by derekwaynecarr** [comment]
@bprashanth - i was not sure if i understood either...

**Comment by girishkalele** [comment]
I was going by this function - it counts various service-related resources, including LoadBalancers.

```
// ServiceUsageFunc knows how to measure usage associated with services
func ServiceUsageFunc(object runtime.Object) api.ResourceList {
	result := api.ResourceList{}
	if service, ok := object.(*api.Service); ok {
		// default service usage
		result[api.ResourceServices] = resource.MustParse("1")
		result[api.ResourceServicesLoadBalancers] = resource.MustParse("0")
		result[api.ResourceServicesNodePorts] = resource.MustParse("0")
		switch service.Spec.Type {
		case api.ServiceTypeNodePort:
			// node port services need to count node ports
			value := resource.NewQuantity(int64(len(service.Spec.Ports)), resource.DecimalSI)
			result[api.ResourceServicesNodePorts] = *value
		case api.ServiceTypeLoadBalancer:
			// load balancer services need to count load balancers
			result[api.ResourceServicesLoadBalancers] = resource.MustParse("1")
		}
	}
	return result
```

**Comment by girishkalele** [comment]
Are these quota limits enforced by some sort of admission controller ?
Are they per namespace/serviceaccount ?
Where can I configure them or view current usage ?

**Comment by derekwaynecarr** [comment]
@girishkalele 

>Are these quota limits enforced by some sort of admission controller?

Yes.  see: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/resourcequota/admission.go

Its also used in the quota controller that does reconciliation in response to observed deletes.

>Are they per namespace/serviceaccount?

The quota constraints are per namespace.

>Where can I configure them or view current usage?

see following:
http://kubernetes.io/docs/admin/resourcequota/
http://kubernetes.io/docs/admin/resourcequota/walkthrough/

**Comment by girishkalele** [comment]
We are not going to track every independent external cloud provider resource in our quota management.
