### ISSUE TITLE
`clusterinfo_dump.go` should use discovery and a dynamic client 

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#32216]
`clusterinfo_dump.go` uses discrete `list` operations to find whitelisted resources.  Given the rate at which new resource are added, it probably makes sense to keep a backlist and just use discovery to walk the set of namespace scoped resources to print.

@kubernetes/kubectl This hurts us for adding new resources and having our commands work.

**Comment by asalkeld** [comment]
Not sure what is remaining after c39f5681b75d5a0e19d0958ebc7c84b946cadd27
