### ISSUE TITLE
Confusing error when object with generateName already exists

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#32220]
Spawned from https://github.com/openshift/origin/issues/10237

https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/api/rest/create.go#L106 is converting an AlreadyExists error into a server timeout error if it has a generateName

```
// CheckGeneratedNameError checks whether an error that occurred creating a resource is due
// to generation being unable to pick a valid name.
func CheckGeneratedNameError(strategy RESTCreateStrategy, err error, obj runtime.Object) error {
    if !errors.IsAlreadyExists(err) {
        return err
    }

    objectMeta, kind, kerr := objectMetaAndKind(strategy, obj)
    if kerr != nil {
        return kerr
    }

    if len(objectMeta.GenerateName) == 0 {
        return err
    }

    return errors.NewServerTimeoutForKind(kind.GroupKind(), "POST", 0)
}
```

That means that this returns really confusing errors:

```
data='{"kind":"Secret","apiVersion":"v1","metadata":{"name":"foo","generateName":"foo"}}'
$ oc create -f - <<< "$data"
secret "foo" created
$ oc create -f - <<< "$data"
Error from server: error when creating "STDIN": The POST operation against Secret could not be completed at this time, please try again.
```

**Comment by dims** [comment]
@derekwaynecarr @liggitt - a simple if for the objectMeta.Name seems to do the trick... is this enough? or were you looking for better way instead of NewServerTimeoutForKind ?

```
diff --git a/pkg/api/rest/create.go b/pkg/api/rest/create.go
index 4519032..627d099 100644
--- a/pkg/api/rest/create.go
+++ b/pkg/api/rest/create.go
@@ -105,6 +105,8 @@ func CheckGeneratedNameError(strategy RESTCreateStrategy, err error, obj runtime

        if len(objectMeta.GenerateName) == 0 {
                return err
+       } else if len(objectMeta.Name) > 0 {
+               return err
        }

        return errors.NewServerTimeoutForKind(kind.GroupKind(), "POST", 0)
```

**Comment by liggitt** [comment]
the alreadyexists error occurs after the name field is populated with a generated name, so returning in that case makes this entire function a no-op in every case I can find. I just think inferring a ServerTimeout error from an AlreadyExists error and the presence of GenerateName is really odd

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @derekwaynecarr

**Comment by liggitt** [comment]
Not a blocker

**Comment by dims** [comment]
thanks @liggitt

**Comment by sch00lb0y** [comment]
```go
func CheckGeneratedNameError(strategy RESTCreateStrategy, err error, obj runtime.Object) error {
    if !errors.IsAlreadyExists(err) {
        return err
    }

    objectMeta, _, kerr := objectMetaAndKind(strategy, obj)
    if kerr != nil {
        return kerr
    }
    return err
    //if len(objectMeta.GenerateName) == 0 {
    //    return err
    //}

    //return errors.NewServerTimeoutForKind(kind.GroupKind(), "POST", 0)
}
```
This can be done right?(I may be wrong)

**Comment by wu8685** [comment]
Should we return another `AlreadyExists` instead of `ServerTimeout` to include the generate name information ?

**Comment by ceridwen** [comment]
`AlreadyExists` seems like the correct error in other cases involving an object that already exists with that name.

**Comment by nikhita** [comment]
Looks like https://github.com/kubernetes/kubernetes/pull/61642 is not active due to age.

If anyone is interested, please feel free to work on this! Like @dims mentioned in https://github.com/kubernetes/kubernetes/pull/61642#issuecomment-378584552, a unit test along with the required changes would be good to add.

**Comment by maciaszczykm** [comment]
Would be really helpful to solve this :)

/remove-lifecycle rotten

**Comment by prashantgolash** [comment]
I am new to Kubernetes community and was going through role board recommendations on older threads - https://discuss.kubernetes.io/t/dev-looking-to-start-contributing/4679/3. 

If everyone is ok, can I pick this issue and work on it.

**Comment by prashantgolash** [comment]
It seems @sch00lb0y already created PR for this issue - https://github.com/kubernetes/kubernetes/pull/61642

It doesn't seem to have merged.
@sch00lb0y - Let me know if you are still working, else I can take a stab (Though most of the work is already done by you) to further drive this.

**Comment by sch00lb0y** [comment]
@prashantgolash I'm not working on it. Please take it forward. Thanks

**Comment by prashantgolash** [comment]
Thanks for the confirmation. I will work on this.

**Comment by prashantgolash** [comment]
I have taken a look at the complete flow of the issue. From what I understand, there are a couple of choices

Option - (1) Validate in **[BeforeCreate](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/registry/rest/create.go#L74)** function if an object has both name and generateName and fail the request if that is the case.
Option - (2) in **[BeforeCreate](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/registry/rest/create.go#L74)**, set generateName to empty if it also has a name. This will make sure that the error in CheckGeneratedNameError is [ServerTimeOut](https://kubernetes.io/docs/reference/federation/v1/definitions/) (when the generated name is conflicting with the already existing name of some other object). This is essentially the approach took in this [PR](https://github.com/kubernetes/kubernetes/pull/61642/files), which no longer is actively worked on.

/cc @liggitt @deads2k

**Comment by lavalamp** [comment]
/needs-triage

It's kind of embarrassing that this is still open.

**Comment by lavalamp** [comment]
(I think the fix may be to delete the mentioned function entirely-- why would we describe this situation as a timeout error?)

**Comment by caesarxuchao** [comment]
@lavalamp do you know someone who's interested working on this? We will come back on this issue in the next triage meeting.

**Comment by dlipovetsky** [comment]
The origin of `CheckGeneratedNameError`: https://github.com/kubernetes/kubernetes/pull/3789/files#diff-b8d20421db500250643d4433451d1c3862f3cc6732aad1b47c025b09c95e96cbR70-R87
