### ISSUE TITLE
Alpha apis are enabled by default contradicting our policy.

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#32226]
There are a few alpha API groups enabled by default in [pkg/master/master.go:837](https://github.com/kubernetes/kubernetes/blob/d9ea0887653b62597a332d02453db53a4df2d494/pkg/master/master.go#L837):

``` go
    ret.EnableVersions(
        apiv1.SchemeGroupVersion,
        extensionsapiv1beta1.SchemeGroupVersion,
        batchapiv1.SchemeGroupVersion,
        authenticationv1beta1.SchemeGroupVersion,
        autoscalingapiv1.SchemeGroupVersion,
        appsapi.SchemeGroupVersion,                              // alpha API
        policyapiv1alpha1.SchemeGroupVersion,                    // alpha API
        rbacapi.SchemeGroupVersion,                              // alpha API
        storageapiv1beta1.SchemeGroupVersion,
        certificatesapiv1alpha1.SchemeGroupVersion,
        authorizationapiv1beta1.SchemeGroupVersion,
    )
```

This is in violation of our stated policy on alpha APIs at: https://github.com/kubernetes/kubernetes/blob/release-1.4/docs/devel/api_changes.md#alpha-beta-and-stable-versions

> - Availability: committed to main kubernetes repo; appears in an official release; feature is disabled by default, but may be enabled by flag

We should disable these APIs by default, graduate them if they're actually stable enough for beta, or amend our policy.

There's a related issue to write tests for this as well: #30096

cc @kubernetes/sig-api-machinery

**Comment by smarterclayton** [comment]
Was this not resolved?
