### ISSUE TITLE
Service deletion does not remove the SG of the ELB (AWS)

### ISSUE THREAD

**Issue by ntmggr** [kubernetes/kubernetes#32227]
kubectl version
`Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean"}`

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Centos 7 64bit
- **Kernel** (e.g. `uname -a`):3.10.0-327.10.1.el7.x86_64
- **Install tools**:
- **Others**:

**What happened**:
Removing a service which has an elb (either internal or public) does not remove the associated ELB SG

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
create a service with 

``` spec:
  type: LoadBalancer
```

wait for the service to finish. Then delete the service and observe the ELB SG which is a left over.

**Anything else do we need to know**:
The ELB SG is not getting deleted as it referenced in the kubenode's SG too. Deleting the referencing SG from the kubenode SG then it goes ahead and deletes the actual ELB SG too (automatically)

**Comment by lcrisci** [comment]
Hey,

A quick feedback from us since we had the same issue and it was caused by not properly tagging all the resources ( especially the kubenode's SG in this case ) as mentioned in the following documentation:

https://github.com/kubernetes/kubernetes/blob/master/docs/design/aws_under_the_hood.md#tagging

Once we tagged the resources properly, this issue resolved itself on our side.

**Comment by mkhutornenko** [comment]
@lcrisci could you please give a few more details on what kind of tagging helped in your case? A simple example would be ideal. We are facing a similar problem where neither SGs nor ELBs are removed when a service is deleted. AFAICT, all SGs are already tagged as `key: KubernetesCluster, value: kubernetes`.

**Comment by mkhutornenko** [comment]
Actually, it was rather unusual AWS glitch in our case. It took a few hours for the SGs and ELBs to disappear but they were gone after all.

**Comment by cmluciano** [comment]
/remove-sig network

need a triage from AWS

**Comment by argais** [comment]
This happened to me after upgrading from kops 1.5.3 to 1.6.2 (k8s wasnt upgraded, only kops, k8s 1.5.4), we added disableelbingress during that upgrade and after that removing a service (that was launched before the upgrade) doesnt remove the elb sg anymore.

**Comment by jeb5-ccl** [comment]
we have an issue whereby deletion of services does not delete the ELB, SGs or network IFs. Please can someone point me at which logs to look at for diagnosis.

Many thanks.

**Comment by chouhan** [comment]
> Hey,
> 
> A quick feedback from us since we had the same issue and it was caused by not properly tagging all the resources ( especially the kubenode's SG in this case ) as mentioned in the following documentation:
> 
> https://github.com/kubernetes/kubernetes/blob/master/docs/design/aws_under_the_hood.md#tagging
> 
> Once we tagged the resources properly, this issue resolved itself on our side.

Can you please give an example of how to tag it? 
Is there a way that I run a command and purges the non referenced / non active SG's?
The URL you've provided doesn't work anymore.
Is there a way to purge the orphaned SG's that exists out there?
Can we automate this process to clean up using commands, if so, what would that be like?
Also, can we automate this as part of a terraform script?

Thanks,
Rakesh
