### ISSUE TITLE
Outline upgrade-downgrade testing requirements for sysctl support

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#32241]
sysctl support has been added as part of v1.4 release. The upgrade / downgrade testing requirements needs to be defined and ideally tested as part of CI.

@sttts can you start with outlining the manual testing necessary for sysctl feature.

**Comment by sttts** [comment]
@vishh where are those requirements collected and in which format?

**Comment by sttts** [comment]
Found it in the release status doc: https://docs.google.com/document/d/1CIRSmJ2-Ez855KDiVPJpjl5o5pk05t9geZ_gCkZtYk4/edit#heading=h.j0o7bjy3vmc0.

**Comment by sttts** [comment]
Added test requirements to the referenced documents. Am half way through manual testing. Will continue tomorrow.

**Comment by vishh** [comment]
Sweet!! Thanks for picking this up @sttts

**Comment by pwittrock** [comment]
@sttts How are we looking on this?

**Comment by sttts** [comment]
@pwittrock manual upgrade/downgrade tests have been documented in https://docs.google.com/document/d/1yv9tm5qeCqbyw5SWysHaXxSLDRZ-RmK8QRBrkbnh6Tg/edit and executed successfully. From my side, we can close this issue.

**Comment by pwittrock** [comment]
Great.  Thanks
