### ISSUE TITLE
escape character in sed command triggers kubectl error

### ISSUE THREAD

**Issue by sbezverk** [kubernetes/kubernetes#32240]
Below is the init container I am using, I need to use sed to modify on the fly one parameter, when I run kubectl create -f container.yaml I see this error:

kubectl create -f tgtd-pod-v2.yaml
unable to decode "tgtd-pod-v2.yaml": invalid character '(' in string escape code

The same command run in shell works without any errors.

      annotations:
        pod.alpha.kubernetes.io/init-containers: '[
          {
             "name": "initialize-tgtd",
             "image": "toolbox:3.0.0",
             "command": [
                 "sh",
                 "-ce",
                 "cp -a /srv/configmap/..data/* /srv/pod-main-config/;
                  sed ''s/\( portal=\)[^ ].*/\1 0.0.0.0:3260\"/'' /srv/configmap/..data/config.json > /srv/pod-main-config/config.json; "],
             "volumeMounts": [
                {
                   "name": "tgtd-configmap",
                   "mountPath": "/srv/configmap"
                },
                {
                   "name": "pod-main-config",
                   "mountPath": "/srv/pod-main-config"
                }
             ]
          }
        ]'

**Comment by nhlfr** [comment]
@sbezverk you need to double escape these characters, so use double slashes:

```
  annotations:
    pod.alpha.kubernetes.io/init-containers: '[
      {
         "name": "initialize-tgtd",
         "image": "toolbox:3.0.0",
         "command": [
             "sh",
             "-ce",
             "cp -a /srv/configmap/..data/* /srv/pod-main-config/;
              sed ''s/\\( portal=\\i)[^ ].*/\\1 0.0.0.0:3260\"/'' /srv/configmap/..data/config.json > /srv/pod-main-config/config.json; "],
         "volumeMounts": [
            {
               "name": "tgtd-configmap",
               "mountPath": "/srv/configmap"
            },
            {
               "name": "pod-main-config",
               "mountPath": "/srv/pod-main-config"
            }
         ]
      }
    ]'
```

That's because k8s API is doing its own escaping, before anything lands in the "lower" layers than k8s.

**Comment by sbezverk** [comment]
sed ''s/\\(^.*portal=\\)/\\1 0.0.0.0:3260\\"/''

Does not help. I get this anyway:
unable to decode "tgtd-pod-v2.yaml": invalid character '/' after array element

**Comment by nhlfr** [comment]
Strange, it worked for me when I pasted than `annotations` section in some pod yaml I had. Could you please share the whole yaml?

**Comment by sbezverk** [comment]
@nhlfr Sure.
Here you go:
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: tgtd
  labels:
    component: tgtd
    system: tgtd
  namespace: default
spec:
  template:
    metadata:
      name: tgtd
      labels:
        component: tgtd
        system: tgtd
      namespace: default
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[
          {
             "name": "initialize-tgtd",
             "image": "192.168.80.240:4000/kolla/centos-source-kolla-toolbox:3.0.0",
             "command": [
                 "sh",
                 "-ce",
                 "cp -a /srv/configmap/..data/* /srv/pod-main-config/;
                  sed ''s/\\(^.*portal=\\)/\\1 0.0.0.0:3260\\"/'' /srv/configmap/..data/config.json > /srv/pod-main-config/config.json; "],
             "volumeMounts": [
                {
                   "name": "tgtd-configmap",
                   "mountPath": "/srv/configmap"
                },
                {
                   "name": "pod-main-config",
                   "mountPath": "/srv/pod-main-config"
                }
             ]
          }
        ]'
    spec:
      hostNetwork: True
      hostIPC: True
      nodeSelector:
          kolla_storage: "true"
      containers:
        - image: ""
          name: tgtd
          securityContext:
            privileged: true
          env:
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ALWAYS
          volumeMounts:
            - mountPath: /var/lib/kolla/config_files
              name: pod-main-config
              readOnly: true
            - mountPath: /run
              name: run
            - mountPath: /dev
              name: dev
            - mountPath: /sys/fs/cgroup
              name: sys-fs-cgroup
            - mountPath: /lib/modules
              name: lib-modules
            - mountPath: /var/lib/cinder
              name: cinder-volumes
            - mountPath: /etc/iscsi
              name: iscsi-info
            - mountPath: /etc/localtime
              name: host-etc-localtime
              readOnly: true
            - mountPath: /var/log/kolla/
              name: kolla-logs
      volumes:
        - name: kolla-kubernetes-events
          emptyDir: {}
        - name: pod-main-config
          emptyDir: {}
        - name: tgtd-configmap
          configMap:
            name: tgtd-configmap
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: run
          hostPath:
            path: /run
        - name: dev
          hostPath:
            path: /dev
        - name: sys-fs-cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: cinder-volumes
          hostPath:
            path: /var/lib/cinder
        - name: iscsi-info
          hostPath:
            path: /etc/iscsi
        - name: host-etc-localtime
          hostPath:
            path: /etc/localtime
        - name: kolla-logs
          emptyDir: {}

**Comment by sbezverk** [comment]
@nhlfr 

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: tgtd
  labels:
    component: tgtd
    system: tgtd
  namespace: default
spec:
  template:
    metadata:
      name: tgtd
      labels:
        component: tgtd
        system: tgtd
      namespace: default
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[
          {
             "name": "initialize-tgtd",
             "image": "192.168.80.240:4000/kolla/centos-source-kolla-toolbox:3.0.0",
             "command": [
                 "sh",
                 "-ce",
                 "cp -a /srv/configmap/..data/* /srv/pod-main-config/;
                  sed ''s/\\(^.*portal=\\)/\\1 0.0.0.0:3260\\"/'' /srv/configmap/..data/config.json > /srv/pod-main-config/config.json; "],
             "volumeMounts": [
                {
                   "name": "tgtd-configmap",
                   "mountPath": "/srv/configmap"
                },
                {
                   "name": "pod-main-config",
                   "mountPath": "/srv/pod-main-config"
                }
             ]
          }
        ]'
    spec:
      hostNetwork: True
      hostIPC: True
      nodeSelector:
          kolla_storage: "true"
      containers:
        - image: ""
          name: tgtd
          securityContext:
            privileged: true
          env:
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ALWAYS
          volumeMounts:
            - mountPath: /var/lib/kolla/config_files
              name: pod-main-config
              readOnly: true
            - mountPath: /run
              name: run
            - mountPath: /dev
              name: dev
            - mountPath: /sys/fs/cgroup
              name: sys-fs-cgroup
            - mountPath: /lib/modules
              name: lib-modules
            - mountPath: /var/lib/cinder
              name: cinder-volumes
            - mountPath: /etc/iscsi
              name: iscsi-info
            - mountPath: /etc/localtime
              name: host-etc-localtime
              readOnly: true
            - mountPath: /var/log/kolla/
              name: kolla-logs
      volumes:
        - name: kolla-kubernetes-events
          emptyDir: {}
        - name: pod-main-config
          emptyDir: {}
        - name: tgtd-configmap
          configMap:
            name: tgtd-configmap
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: run
          hostPath:
            path: /run
        - name: dev
          hostPath:
            path: /dev
        - name: sys-fs-cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: cinder-volumes
          hostPath:
            path: /var/lib/cinder
        - name: iscsi-info
          hostPath:
            path: /etc/iscsi
        - name: host-etc-localtime
          hostPath:
            path: /etc/localtime
        - name: kolla-logs
          emptyDir: {}

**Comment by nhlfr** [comment]
Um... code formatting or pastebin please. ;)
And cheers for kolla devs!

**Comment by sbezverk** [comment]
@nhlfr sorry about previous post I thought it would format it properly.
Here is pastebin: http://paste.openstack.org/show/569249/

**Comment by nhlfr** [comment]
@sbezverk you need three slashes before `"`, so something like that:
https://paste.fedoraproject.org/424391/73405853/

That's because:

* you do **not** need to escape braces in k8s - that's why you're just doing `\\(` to pass `\(` into init container, after the anotation will be escaped/validated in k8s api
* you **need** to escape quotation mark in k8s - so you need `\\\"` in order to receive `\"` after k8s validation/escape, because k8s expects you to:
  * escape the slash
  * escape the quotation mark

**Comment by sbezverk** [comment]
@nhlfr Thank you very much for your help! It is working now.
