### ISSUE TITLE
Validate API for 1.4

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#32249]
Someone needs to look at the swagger + api for a 1.4 beta release and make sure it matches expectations and what is in the kubernetes/features + release notes.

New apis should exist and be usable

**Comment by lavalamp** [comment]
Due to #32226, everything is on:

```
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/apps",
    "/apis/apps/v1alpha1",
    "/apis/authentication.k8s.io",
    "/apis/authentication.k8s.io/v1beta1",
    "/apis/authorization.k8s.io",
    "/apis/authorization.k8s.io/v1beta1",
    "/apis/autoscaling",
    "/apis/autoscaling/v1",
    "/apis/batch",
    "/apis/batch/v1",
    "/apis/batch/v2alpha1",
    "/apis/certificates.k8s.io",
    "/apis/certificates.k8s.io/v1alpha1",
    "/apis/extensions",
    "/apis/extensions/v1beta1",
    "/apis/policy",
    "/apis/policy/v1alpha1",
    "/apis/rbac.authorization.k8s.io",
    "/apis/rbac.authorization.k8s.io/v1alpha1",
    "/healthz",
    "/healthz/ping",
    "/logs",
    "/metrics",
    "/swaggerapi/",
    "/ui/",
    "/version"
  ]
}
```

**Comment by lavalamp** [comment]
It was this way in 1.3, too.

**Comment by lavalamp** [comment]
@erictune What did you do for this in 1.3, so I can repeat the process for 1.4?

**Comment by erictune** [comment]
The PR that turned stuff on (https://github.com/kubernetes/kubernetes/commit/6f7007afc5b99f7ecceae20d22f794077362c884) was committed after I did my thing for 1.3.

**Comment by lavalamp** [comment]
I'm going to close this, we have issues tracking the stuff that's on that shouldn't be already.

**Comment by krousey** [comment]
@erictune that commit didn't add anything. It just reformatted the line messing with the blame history.
