### ISSUE TITLE
Investigate "ssh: unexpected packet in response to channel" on GKE

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#32248]
Seen this debugging a couple of tests. Pod is ready and we can reach it through apiserver proxy, then after a bit we request timeouts followed by `ssh: unexpected packet in response to channel open: <nil>`

Eg: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-serial/2204/
from https://github.com/kubernetes/kubernetes/issues/27324 and https://github.com/kubernetes/kubernetes/issues/30489

It's possible there was just networking errors that surface over an ssh session, and GKE is the only thing using ssh in e2es.

@cjcullen @kubernetes/goog-gke

**Comment by dims** [comment]
Apparently fixed by https://github.com/kubernetes/kubernetes/pull/35581, please reopen if necessary
