### ISSUE TITLE
Add support for accessing Ceph RBD with the rbd-nbd client

### ISSUE THREAD

**Issue by rzarzynski** [kubernetes/kubernetes#32266]
## Objective

Add support for the recently emerged `rbd-nbd` feature-rich client to improve support for Ceph RBD in Kubernetes.
## Background

Kubernetes already offers support for Ceph RBD based on the `krbd` kernel client. Unfortunately, due to obvious reasons, `krbd` can't use the `librbd` user-space space library that gets most of the development focus. This caused a feature gap when compared to VM-based environments.

At the moment `krbd` lacks exclusive locking infrastructure, image management facilities and multi-DC support (remote backups!). The detailed list can be obtained by comparing the definitions of `RBD_FEATURES_ALL` macro in [`librbd`](https://github.com/ceph/ceph/blob/master/src/include/rbd/features.h#L25) and [kernel](http://lxr.linux.no/#linux+v4.7.2/drivers/block/rbd.c#L121). While there are efforts on partially closing the gap (patches waiting for merge), `librbd` continuously gets new items like [consistency groups](http://tracker.ceph.com/projects/ceph/wiki/consistency_groups) or [fencing improvements](https://github.com/ceph/ceph/pull/9592).

Beside the feature gap `krbd` exhibits additional drawback. Being entirely kernel space impacts fault-tolerance as any kernel panic affects a whole node -- not only a single Pod using RBD storage. According to the [`rbd-nbd` pull request](https://github.com/ceph/ceph/pull/6657) the reliability, especially on non-x86 platforms, was one of the driving factors behind the new client.

Those issues can be addressed by employing `rbd-nbd` -- a thin adapter ([858 lines of code in Jewel](https://github.com/ceph/ceph/blob/v10.2.2/src/tools/rbd_nbd/rbd-nbd.cc#L858)) between NBD subsystem of Linux kernel and `librbd`.

The primary concern about `rbd-nbd` was performance. The authors claimed it's _comparable_ to krbd. Together with Intel we verified those claims. Tests on typical HW where Ceph is deployed (SSDs for journals, HDDs as main storage) showed `rbd-nbd` delivers 70-80% of `krbd` performance. Though, we don't consider the raw performance as a deciding factor. Even fastest RBD client wouldn't be a solution-of-choice for performance critical use cases like RDBMS hosting.
## Proposal

We would like to propose incorporating support for `rbd-nbd`. The integration can be accomplished in multiple ways.
1. Extending the current in-tree plugin for RBD to use `krbd` or `rbd-nbd` depending on a configuration parameter. This would assure the excellent commonality. On the other hand we see differences where this might become an issue.  
   The _krbd_-based plugin employs the _advisory locking_ mechanism to provide fencing at the cost of HA -- in case of node crash a manual intervention is required. However, serving images marked to use _exclusive locking_ feature would result in employing the same underlying infrastructure twice. At the moment this isn’t an issue because `krbd` simply doesn’t support exclusive lock. However, when it finally gets it, RBD images created with Ceph’s default capabilities set will be inaccessible in read-write mode. This was the reason why a [similar solution](https://lists.gnu.org/archive/html/qemu-devel/2016-04/msg02422.html) has been [refused](https://lists.gnu.org/archive/html/qemu-devel/2016-04/msg04131.html) in QEMU.  
   Another problem we see are additional dependencies. After fencing capability is integrated directly in `krbd`, the dependency on user-space `/usr/bin/rbd` CLI utility can be removed. The helper is not required for mapping RBD images as the kernel interface may be used directly by the plugin.
2. Dedicated in-tree plugin. Offers greatest flexibility in adopting new features (like dynamic provisioning of Persistent Volumes).
3. Dedicated FlexVolume plugin. Simple but limited. Bringing support for e.g. dynamic provisioning would require extensive changes in FlexVolume’s interfaces.

At the moment the option # 2 looks most promising. Though we stay entirely open for the discussion.
### Performance

`rbd-nbd` efficiency suffers from extra context switches and extensive memory copying between kernel and user-space boundaries. Although we can do nothing with the first factor, the second can be improved for large blocks transfers. Linux kernel has facilities for zero-copy page-aligned memory transfers between kernel and application via the combination of `splice` and `vmsplice` system calls.
### Fencing

Actually Mirantis [is working](https://github.com/ceph/ceph/pull/9592) on bringing fencing to `librbd` on the top of exclusive lock infrastructure. This would allow to move from the flawed _advisory lock_ mechanism that is currently used by rbd storage plugin.
### Dynamic provisioning

Currently RBD images must be created ahead by a cluster administrator. We see possibility to implement the dynamic provisioning for RBD in the future.

**Comment by jsafrane** [comment]
cc @kubernetes/sig-storage, especially @rootfs

**Comment by rootfs** [comment]
- `rbd-nbd` is new to the Ceph 2. Existing Ceph 1.x installation doesn't have it. kbrbd is the common denominator.
- There are bridging technologies to get librbd to present rbd image as a block device, e.g. tcmu.
- The drawbacks mentioned are being addressed, e.g. #33660 to resolve fencing issue.

**Comment by flyingcougar** [comment]
@rootfs: What do you mean by Ceph 1.x installation? rbd-nbd is part of Jewel release which is supported i.e by ceph-ansible.

**Comment by rootfs** [comment]
@flyingcouger I meant the client bits - there is where rbd-nbd is called to map the image.

**Comment by rzarzynski** [comment]
> The drawbacks mentioned are being addressed, e.g. #33660 to resolve fencing issue.

@rootfs: #33660 is still based on the same *advisory locking* mechanism that has been [refused in QEMU](https://lists.gnu.org/archive/html/qemu-devel/2016-04/msg04131.html) because of the conflict with `exclusive-lock` flag of an RBD image (enabled by default in Ceph Jewel LTS release). Please take a look on #33013. Ceph community already [implemented](https://github.com/ceph/ceph/pull/9592) a dedicated API for fencing.

In addition to that I would say that fencing isn't the sole drawback. The feature gap is still there. For instance, what about remote backups and multi-DC support in general?

**Comment by rzarzynski** [comment]
> There are other bridging technologies to get librbd to present rbd image as a block device, e.g. tcmu

Agreed, a couple options exist. I recently talked with @dillaman and in the long term perspective there is a plan to develop TCMU-based bridge for librbd. Anyway, I would expect that those bridges (`rbd-nbd`, `rbd-tcmu`, `rbd-*`) will be so similar (as basing on the same library and having the same features including fencing) that it makes sense to address them with one single plugin called e.g. `rbd-userspace`. The abstraction layer would be extremely thin covering basically map and unmap only.

**Comment by rzarzynski** [comment]
> kbrbd is the common denominator.

I'm afraid this isn't entirely accurate as the kernel version is a significant degree of freedom. Encountering the version-related limitation tends to be game-over as upgrading the whole kernel to get newer krbd often isn't an option. Moreover, the problem might become much more visible soon as Ilya finishes merging some new features in krbd.

User-space solution wouldn't be locked to kernel version to such degree. Changing librbd and an adapter like `rbd-nbd` seems to be much more straightforward and isolated than global kernel upgrade.

**Comment by rootfs** [comment]
Not every bridge is the same. If librbd is implemented as a `tcmu-runner`
handler, we need `targetcli` to do the setup. The semantics would be
different from rbd-nbd.

On Fri, Oct 7, 2016 at 6:05 AM, Radoslaw Zarzynski <notifications@github.com

**Comment by rzarzynski** [comment]
> Not every bridge is the same. If librbd is implemented as a `tcmu-runner` handler, we need `targetcli` to do the setup. The semantics would be different from rbd-nbd.

@rootfs: this is why I mentioned the need for the abstraction layer for mapping and unmapping an RBD image.

**Comment by fire** [comment]
Ping! Is there any new developments on this?

**Comment by kfox1111** [comment]
ping

**Comment by elaron** [comment]
Ping! Is there any progress here?

**Comment by kaoet** [comment]
I also want this feature

**Comment by hdksky** [comment]
Ping!  Any progress?

**Comment by ianchakeres** [comment]
I've started working on this issue with another team member at Salesforce. We'll update this issue when we have a new PR leveraging rbd-nbd.

/assign @ianchakeres

**Comment by dillaman** [comment]
As an FYI, I believe there is also an effort just getting underway to implement Container Storage Interface drivers for RBD and CephFS for use by k8s [1] to eventually replace the in-tree drivers.

[1] https://github.com/ceph/ceph-csi

**Comment by kfox1111** [comment]
@sbezverk fyi

**Comment by jberkus** [comment]
This issue doesn't look like the feature is going to be implemented in time for 1.10, given that Code Freeze is on Monday.  Please remove it from the milestone, thanks!

**Comment by jberkus** [comment]
@saad-ali @ianchakeres Code Freeze begins in 6 hours.  Will this feature be completed by then?  It needs to be status/approved-for-milestone and at least priority/important-soon to stay open after code freeze.  Otherwise, please punt it to 1.11.

**Comment by naeemkhan12** [comment]
do we have any example to test rbd-nbd with k8s?

**Comment by ianchakeres** [comment]
@naeemkhan12 here is a [blog post](https://engineering.salesforce.com/mapping-kubernetes-ceph-volumes-the-rbd-nbd-way-21f7c4161f04) that I wrote last year after the code was merged on [using rbd-nbd with k8s](https://engineering.salesforce.com/mapping-kubernetes-ceph-volumes-the-rbd-nbd-way-21f7c4161f04).

**Comment by naeemkhan12** [comment]
I actually started from that blog, but the issue is related to ceph version mismatch I have ceph cluster setup having mimic(13.2) version and the client(rbd-nbd) version is jewel(10.2).  After upgrading to rbd-nbd to mimic version the issue is fixed. But as a side not plugin should manage cli change e.g with rbd-nbd (ceph-version 10.2) version check command is 
`rbd-nbd map --version`
and in rbd-nbd (ceph-version 13.2) 
`rbd-nbd --version`
