### ISSUE TITLE
Custom HTTP timeouts in GKE ingress

### ISSUE THREAD

**Issue by mark9white** [kubernetes/kubernetes#32273]
It would be useful to be able to set a custom HTTP timeout on a GKE ingress. 

In this issue:
http://stackoverflow.com/questions/36200528/how-to-configure-ingress-request-timeouts-on-gke

There is a comment from Prashanth B:

"Yes the controller tries to pick sensible defaults. Timeout > 30s is not something that's been asked for, so I just dropped it from beta. If it's something you need often I can push it through as an annotation on the Ingress itself."

**Comment by bprashanth** [comment]
You can already do this on kube versions >= 1.3: 
https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce#health-checks
https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce/examples/health_checks
https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce/examples/health_checks#limitations
please reopne if thats not the case

**Comment by tsloughter** [comment]
Health check timeout and the response timeout are not the same. Is it still the case that we are stuck with 30 seconds as the response timeout? If I change it manually through the google console it ends up going back to 30 eventually.

**Comment by montanaflynn** [comment]
We also need this, even when our backend deployments are fine we get 502 errors when the request  takes over 30 seconds. After a lot of debugging I've wound up here. 

@tsloughter did you ever find a way to increase the timeout permanently? Also how did you increase the 30s timeout manually through google console? When I look at the load balancer I see the 30s timeout but can't figure out how to increase it.

Pinging @bprashanth since I don't think the health check timeout is what this issue is referring to.

**Comment by tsloughter** [comment]
@montanaflynn nope, still can't increase it permanently. Click `Edit` on your load balancer, then go to each backend configuration and you can edit the timeout to it. It won't stay changed for that long though.

**Comment by montanaflynn** [comment]
@tsloughter thanks, that did the trick at least temporarily. I think this would be great as an annotation in the ingress config as suggested in the quote @mark9white shared.

**Comment by montanaflynn** [comment]
@bprashanth can you re-open this issue? The load balancer backend timeouts default to 30s and that causes requests to fail for uploads or any API request that does a significant amount of processing. Without being able to change the timeout using the ingress is impossible for our video processing workloads.

**Comment by mark9white** [comment]
@bprashanth Agree with @montanaflynn and @tsloughter that the ability to configure the health checks (which I would expect generally should respond in under 30 seconds anyway) does not address the valid need that I opened this issue for, which was to be able to support http requests of longer than 30 seconds.

**Comment by zimbatm** [comment]
The current official solution is to find the created LB and change the timeout manually: https://github.com/kubernetes/ingress/tree/master/controllers/gce/examples/websocket#change-backend-timeout
This is not very satisfying as k8s is quite dynamic and the provisioning happens asynchronously. Basically a cron job is needed to "fix" the value whenever a new LB appears.

**Comment by zimbatm** [comment]
related issue: https://github.com/kubernetes/ingress/issues/243

**Comment by tsloughter** [comment]
Yea, why is this still closed? Is it blocked by kubernetes/ingress#243 ? If so it can still be opened until the time it is unblocked.

**Comment by zimbatm** [comment]
The ingress development has been split to that other repo so the open issue over there is probably enough. You can see that a lot more discussion has been happening on the other issue already.

**Comment by mike-marcacci** [comment]
See https://github.com/kubernetes/ingress-gce/issues/28

**Comment by alaa-nassef** [comment]
Can't you customize using annotations (https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/customization)?
