### ISSUE TITLE
ThirdParty E2E framework tests should be [Flaky] in kube 1.4

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#32296]
ThirdPartyResources (TPR) E2E test creates a custom resource type, and creates an instance of that type in a namespace.  The namespace is purged, but the namespace controller DOES NOT observe the dynamic mutation of the type hierarchy.  As a result, the instances of that type are never purged, and we could potentially leak resources.

In prior discussions of @kubernetes/sig-api-machinery we agreed that users of TPR would have to kick the namespace controller in the interim in order for it to observe the creation of the new TPR type and have it take part in namespace lifecycle.

If TPR is a priority, we should address the namespace controller issue in kube 1.5, and eliminate the [Flaky] flag from the TPR E2E.  The updates in the e2e framework that intropsect the server dynamically to verify all resources are deleted are getting tripped up by the presence of this test and impacting all others.

Here is an example:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/32278/kubernetes-pull-build-test-e2e-gce/57833/

/cc @kubernetes/sig-api-machinery @smarterclayton @lavalamp @brendandburns @ncdc @pwittrock

**Comment by ncdc** [comment]
+1 to [Flaky] - this is really causing a ton of flakes

**Comment by ncdc** [comment]
Also note that this doesn't just affect the TPR e2e suite - the existence of the TPR can cause any other e2e suite to fail.
