### ISSUE TITLE
Use "an" instead of "a" before an ingress in auto generated API documentation

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#32305]
In swagger spec, we say "create a ingress", "delete a ingress", etc (https://github.com/kubernetes/kubernetes/blob/943d7aa5aa42d8fc359614e1c02521f48d03b989/api/swagger-spec/extensions_v1beta1.json#L3164)
It should be _an_ ingress.

Relevant code is at https://github.com/kubernetes/kubernetes/blob/943d7aa5aa42d8fc359614e1c02521f48d03b989/pkg/apiserver/api_installer.go#L614

**Comment by asalkeld** [comment]
I'll sort this out.
