### ISSUE TITLE
Discovery client behaves poorly when TPR is unregistered

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#32308]
Split off from #32306, the thing that actually caused the flakes throughout the system (as opposed to just failing the TPR test) is 

```
&discovery.ErrGroupDiscoveryFailed{Groups:map[unversioned.GroupVersion]error{unversioned.GroupVersion{Group:"company.com", Version:"v1"}:(*errors.StatusError)(0xc82084c480)}}
```

(https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/32278/kubernetes-pull-build-test-e2e-gce/57833/)

Which I guess means that the discovery client got a list, but then the TPR was gone when it tried to get details?

This is not an emergency since we've marked the test flaky, but we should fix it.

**Comment by smarterclayton** [comment]
The print out of the error message included the message, which was generic 404.  So /apis/company.com/v1 I believe returned a 404 without a JSON body.

**Comment by caesarxuchao** [comment]
> Which I guess means that the discovery client got a list, but then the TPR was gone when it tried to get details?

Yes.

The discovery client returns a partial result when this error occurs, see [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/typed/discovery/discovery_client.go#L232). I think this behavior is correctly. Caller should look into the error and ignore it or retry the discovery.
