### ISSUE TITLE
AWS cluster creation using get-kube fails w/ KUBE_MANIFESTS_TAR_URL: unbound variable

### ISSUE THREAD

**Issue by kgoerlitz** [kubernetes/kubernetes#32318]
BUG REPORT:

**Kubernetes version** v1.3.6

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): jessie
- **Install tools**: get-kube
- **Environment Vars**:<br>
  export KUBERNETES_PROVIDER=aws<br>
  export KUBE_AWS_ZONE="us-east-1a"<br>
  export NUM_NODES=2<br>
  export MASTER_SIZE="m4.large"<br>
  export NODE_SIZE="m4.xlarge"<br>
  export KUBE_ENABLE_INSECURE_REGISTRY=true<br>
  export AWS_S3_BUCKET="my-bucket"<br>
  export KUBE_AWS_INSTANCE_PREFIX="my-prod"<br>
  export ENABLE_CLUSTER_AUTOSCALER=true<br>
  export MASTER_RESERVED_IP=52.2.xxx.xxx

**What happened**:
Kubernetes cluster cration on AWS using get-kube fails with:
./cluster/../cluster/../cluster/aws/../../cluster/common.sh: line 528: KUBE_MANIFESTS_TAR_URL: unbound variable

**What you expected to happen**:
Cluster is created without errors

**How to reproduce it** (as minimally and precisely as possible):
Set variables, run **curl -sS https://get.k8s.io | bash**

**Anything else do we need to know**:

**Comment by justinsb** [comment]
Pretty sure this is fixed now; please reopen if not
