### ISSUE TITLE
cAdvisor should export pod labels for container metrics

### ISSUE THREAD

**Issue by hanikesn** [kubernetes/kubernetes#32326]
Currently it's cAdvisor doesn't export pod labels for container level metrics. This would be desirable to be able to aggregate container level metrics by application.

As Kubernetes doesn't set pod labels on Docker containers (https://github.com/kubernetes/kubernetes/pull/25301) cAdvisor can't export those labels to it's `/metrics` endpoint which makes metric aggregation by pod labels impossible. Kubernetes doesn't set these labels, because currently it's not possible to dynamically set Docker Container Labels (https://github.com/docker/docker/issues/21721). It's also not clear when this situation will change.

I propose a implementing a workaround, so that cAdvisor can directly get the labels from the kublet and export them accordingly.

**Comment by grobie** [comment]
At SoundCloud we work around the problem by using an extra exporter which exports all pod labels in a separate metric and we then join these together in our queries. This is similar to the approach described in @brian-brazil's blog post about [machine role labels](http://www.robustperception.io/how-to-have-labels-for-machine-roles/). Exporting a lot labels per metric makes it more difficult to work with them. So this might even be the more desirable approach.

@fabxc @kubernetes/sig-instrumentation We should discuss this need in our next meeting.

**Comment by davidopp** [comment]
> I propose a implementing a workaround, so that cAdvisor can directly get the labels from the kublet and export them accordingly.

IIUC this is the approach @vishh has advocated as well, particularly as part of the work for #18770.

**Comment by brian-brazil** [comment]
http://www.robustperception.io/exposing-the-software-version-to-prometheus/ is a slightly more relevant version of that blog post.

**Comment by jimmidyson** [comment]
@grobie @brian-brazil Although we're using Prometheus' exposition format, we do have to make sure that any decisions we make around labelling don't restrict/negatively affect other consumers. If this was a Prometheus only decision then I would 100% agree with you though.

**Comment by fabxc** [comment]
> Although we're using Prometheus' exposition format, we do have to make sure that any decisions we make around labelling don't restrict/negatively affect other consumers. If this was a Prometheus only decision then I would 100% agree with you though.

I think its a reasonable step of normalization to constrain labels to the minimum identity-giving set in the exposition. The consumer is free to denormalize again for its own purposes – in Prometheus this happens to be at query time. But other systems can easily do so on write.
Going the other direction is generally harder for the consumer while bloating the exposed metrics.

Of course it's saner if it's happening in the same metric set. But #18770 aims at just that.

**Comment by hanikesn** [comment]
@grobie Any chance of open sourcing that?

**Comment by vishh** [comment]
My idea was that kubelet should expose an extension API that let's
monitoring agents figure out the list of pods on the node along with
detailed runtime information like container & image identifiers, etc.
cAdvisor, being a monitoring agent, can then use this API to come up with
pod level metrics and metadata for k8s pods.

**Comment by tomwilkie** [comment]
@hanikesn @grobie FYI just added support for exporting a pod-label-metric for kube-api-exporter: https://github.com/tomwilkie/kube-api-exporter/pull/9

**Comment by natalia-k** [comment]
is any chance that this will be implemented in the next release ?

Thanks a lot!

**Comment by piosz** [comment]
cc @dchen1107

**Comment by Nowaker** [comment]
This would be very useful.

**Comment by discostur** [comment]
@hanikesn any news on this?

**Comment by brancz** [comment]
/remove-lifecycle stale 

We’re planning on doing this as part of a general metrics overhaul currently targeting for 1.13.

**Comment by beorn7** [comment]
Note that prometheus/client_golang doesn't require consistent label dimensions anymore, which might come in handy here. See https://github.com/prometheus/client_golang/pull/417 . Also, you can now have [unchecked Collectors](https://github.com/prometheus/client_golang/pull/425) in a formally correct way.

**Comment by Nowaker** [comment]
@brancz Still planned?

**Comment by Nowaker** [comment]
Yay! Thanks a ton @brancz.

**Comment by brancz** [comment]
The PR is here: https://github.com/kubernetes/kubernetes/pull/69099

**Comment by brancz** [comment]
#69099 was merged, so this is landing in 1.14 :tada:

**Comment by alvaroaleman** [comment]
/reopen

@hangyan @brancz I believe closing this issue via #69099 is a misunderstanding. #69099 is about adding the literal `pod` label to the cadvisor metrics. This issue is about adding the labels that are on the pod as label to the cadvisor metrics.

**Comment by brancz** [comment]
I see. I think that’s metadata that should be joined onto the metric at query time (this data itself is already available in kube state metrics). More importantly labels on a pod can change over a pod’s lifetime which if we added pod labels to these metrics they would be marked stale and produce a new time-series which wouldn’t reflect the reality.

**Comment by sirkubax** [comment]
I partially solved my case: Needs to have 'deployment' or 'app' label as a filter for pods names
https://github.com/grafana/grafana/issues/28447

But how nice would it be, if cAdvisor could forward an 'app' label along with metrics...

**Comment by sirkubax** [comment]
/reopen

please export all Pod labels ('app', 'deployment', etc...)
![image](https://user-images.githubusercontent.com/3442120/96837875-5ec2f280-1447-11eb-9e90-2fdf3df49f3b.png)

like this 
**__meta_kubernetes_pod_label_app="schema-registry-ui"**

**Comment by will-beta** [comment]
Any updates on this?

**Comment by woodliu** [comment]
Any updates, this is needed!

**Comment by woodliu** [comment]
/reopen 
Is there any plan to support add pod label within cadvisor?

**Comment by shenshouer** [comment]
Hot to ?
