### ISSUE TITLE
Completed pods lose logs across node upgrade

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#32324]
Run the repro steps in https://github.com/kubernetes/kubernetes/issues/32323
While some pods might get deleted, you probably won't be able to get at the logs of the remaining pods, even though it wasn't put on another node or given another ip (according to kubectl at least).  You will end up with: 

```
$ kubectl get po --show-all -o wide
NAME                 READY     STATUS      RESTARTS   AGE       IP           NODE
echo-success-83k2b   0/1       Completed   0          43m       10.244.1.4   kubernetes-minion-group-a9np

$ kubectl logs echo-success-83k2b
Error response from daemon: No such container: 35935b7065a03f7ac60edf203c1cdc19aaec6696ddbb1036aebf74509457a30
```

@kubernetes/sig-node though I get the feeling fixing this is out of scope for 1.4

**Comment by dchen1107** [comment]
Yes, this is out of scope for 1.4. The pod is completed and containers are terminated,  and Kubelet garbage collects those dead containers.

**Comment by bprashanth** [comment]
Maybe mention in https://github.com/kubernetes/kubernetes/issues/32332? I think this will happen as soon as they upgrade

**Comment by yujuhong** [comment]
Logs of terminated pods are only kept with best effort. However, when there's no other pressure (e.g., exceeding the max number of dead containers), kubelet should not remove theses containers IIRC. According to our GC policy, we will keep 2 dead containers per (pod, container) tuple.

**Comment by bprashanth** [comment]
This is probably because we delete vms on nodeupgrade, and the vms were created with "delete boot disk", so we need to start over with /var/lib/docker
