### ISSUE TITLE
Addon-manager does not create ConfigMap from YAML under `/etc/kubernetes/addons` directory

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#32329]
I have these YAML files in the corresponding directory:
```
zihong@kubernetes-master /etc/kubernetes/addons/dns $ ls -l
total 20
-rw-r--r-- 1 root root 1412 Sep  8 22:41 kubedns-autoscaler-configmap.yaml
-rw-r--r-- 1 root root 1570 Sep  8 22:41 kubedns-autoscaler-deployment.yaml
-rw-r--r-- 1 root root 4135 Sep  8 22:41 skydns-rc.yaml
-rw-r--r-- 1 root root 1209 Sep  8 22:41 skydns-svc.yaml
```

All of the other three objects(including deployment in the kubedns-autoscaler-deployment.yaml) are created, but no response for the configmap in kubedns-autoscaler-configmap.yaml.

Below is the content of kubedns-autoscaler-configmap.yaml:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns-cluster-proportional-autoscaler-params
  namespace: kube-system
  labels:
    k8s-app: kubedns-autoscaler
    version: v1
    kubernetes.io/cluster-service: "true"
data:
  simple-scalar.scale-map: |-
    { 
      "cores_to_replicas_map":
      [
        [ 1,1 ],
        [ 4,2 ],
        [ 128,3 ],
        [ 512,5 ],
        [ 1024,7 ],
        [ 2048,10 ],
        [ 4096,15 ],
        [ 8192,20 ],
        [ 12288,30 ],
        [ 16384,40 ],
        [ 20480,50 ],
        [ 24576,60 ],
        [ 28672,70 ],
        [ 32768,80 ],
        [ 65535,100 ]
      ],
      "nodes_to_replicas_map":
      [
        [ 1,1 ],
        [ 2,2 ]
      ]
    }
```
Lable `kubernetes.io/cluster-service: true` is added as this [readme](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/README.md) indicates.
And according to the [addon manager readme](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/README.md), ConfigMaps should be supported. 

And what is the way to retrieve addon manager's log? `kubectl logs --namespace=kube-system kube-addon-manager-kubernetes-master` does not work.

Thanks!

@mikedanese

**Comment by MrHohn** [comment]
It seems like current version of kube-addon-manager(gcr.io/google-containers/kube-addon-manager:v5.1) does not manage ConfigMap kind. However, this feature was added in this commit(2a589b09637aa3745a7151adf2f1fcce36e8b8ac) two months ago.
Any reason for not upgrading the docker image?

cc @girishkalele

**Comment by mikedanese** [comment]
Yes, I think we just need to push the new version to gcr.

**Comment by MrHohn** [comment]
ConfigMap is supported now([ref](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/CHANGELOG.md)). Closing this.
