### ISSUE TITLE
`make test-integration WHAT=test/integration/pkgtotest` doesn't seem to work

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#32338]
I would like to run a subset of the integration tests, but that doesn't seem easy?

**Comment by thockin** [comment]
Do you expect that to translate to `ginkgo.focus` or something?  I don't
know how to do what you want, with or without `make`

**Comment by dims** [comment]
@lavalamp : work around i tried a few days ago was to make a local change to WHAT on this line - https://github.com/kubernetes/kubernetes/blob/f90df2448d5658732c6d2fd0661938e8693947b6/hack/make-rules/test-integration.sh#L63

**Comment by lavalamp** [comment]
Integration doesn't use ginkgo, it's just regular go tests in the
`test/integration` directory, so it should work like regular unit tests. It
just has to start up etcd first, and maybe a few other things.

**Comment by marun** [comment]
I think https://github.com/kubernetes/kubernetes/pull/41581 resolved this issue.

Associated doc change: https://github.com/kubernetes/community/pull/375
