### ISSUE TITLE
Finalizers can be added after delete, and not removed

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#32339]
http://kubernetes.io/docs/api-reference/v1/definitions/ says "If the deletionTimestamp of the object is non-nil, entries in this list can only be removed.".

```
# add a finalizer
$ kubectl edit deployment hostnames
deployment "hostnames" edited

$ kubectl get deployment hostnames -o go-template='{{.metadata.finalizers}}'; echo
[foo.com/bar]

# delete it
$ kubectl delete deployment hostnames
deployment "hostnames" deleted

# observe it
$ kubectl get deployment hostnames
NAME        DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
hostnames   0         0         0            0           1m

# add a finalizer
$ kubectl edit deployment hostnames
deployment "hostnames" edited

$ kubectl get deployment hostnames -o go-template='{{.metadata.finalizers}}'; echo
[hockin.org/thockin foo.com/bar]

# remove a finalizer
$ kubectl edit deployment hostnames
deployment "hostnames" edited

$ kubectl get deployment hostnames -o go-template='{{.metadata.finalizers}}'; echo
[hockin.org/thockin foo.com/bar]

# remove them all
$ kubectl edit deployment hostnames
deployment "hostnames" edited

$ kubectl get deployment hostnames -o go-template='{{.metadata.finalizers}}'; echo
Error from server: deployments.extensions "hostnames" not found
```

@derekwaynecarr can you elucidate if I am assuming this does something different than reality

**Comment by derekwaynecarr** [comment]
This is garbage collection finalizer field, not the namespace finalizer
field that that new field was inspired from

**Comment by thockin** [comment]
I don't parse that - is this not a general-purpose "refcount" thing?  It seems to work that way, except not as documented

**Comment by lavalamp** [comment]
This is a general purpose field and it should work like Tim thinks it should work. @caesarxuchao can you take a look at this when you don't have anything pressing for 1.4?

**Comment by lavalamp** [comment]
The namespace finalizer should switch to using this field if it is currently doing something else.

**Comment by caesarxuchao** [comment]
I'm adding validation rule to prevent adding finalizers if deletionTimestamps is set.
I'm still investigating why it can't be removed. This bug is strange.

**Comment by caesarxuchao** [comment]
Actually I guess it's a `kubectl edit` bug. It uses patch, and patch doesn't work on list of simple type, `finalizers` is a list of string.

**Comment by caesarxuchao** [comment]
Yep, it's a `kubectl edit` bug. I used `kubectl replace` to remove one finalizer and it work as expected.

I think this is a known bug of `patch`, we don't have a way to specify the mergekey of a list of simple type.

**Comment by thockin** [comment]
Is there a bug open for this?  Frankly, if `kubectl edit` is going to fail
for things like this, we should not be offering it as a feature, or it
should use PUT rather than PATCH

**Comment by caesarxuchao** [comment]
Created https://github.com/kubernetes/kubernetes/issues/32398.

It cannot use PUT, because it's doing a three way merge (current state, last configuration, current configuration).

**Comment by lavalamp** [comment]
These are intended for automated use, not human use, so kubectl edit not
working is just unfortunate, not a blocker. Although it's really
unfortunate that PATCH is so broken.

**Comment by thockin** [comment]
Why does `edit` need to be 3-way?  I don't think that is the semantic a
user would expect from an edit operation AT ALL.  It certainly surprised ME.

WRT automated vs human - if PATCH doesn't work (worse - says it succeeded
but didn't) for some class of fields, then PATCH doesn't work, and we
should not support it.  Full stop.  It's going to end up causing someone an
outage.

These are not necessarily related to this bug, but I'd call them pretty
serious flaws.

**Comment by caesarxuchao** [comment]
> if PATCH doesn't work (worse - says it succeeded
but didn't) for some class of fields, then PATCH doesn't work, and we
should not support it.  Full stop.  It's going to end up causing someone an
outage.

Discussed in real life. PATCH works, it's just that there are certain operations you cannot express using the strategicmerge patch syntax.

> kubectl etid cannot use PUT, because it's doing a three way merge (current state, last configuration, current configuration).

I was wrong. `kubectl edit` is building [a two-way patch](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/edit.go#L395). So perhaps it uses PATCH over PUT due to the efficiency.

**Comment by caesarxuchao** [comment]
FWIW, I printed out the patch generated by `kubectl edit` when I removed one finalizer. The patch is empty, i.e., "{}".

**Comment by thockin** [comment]
On Fri, Sep 9, 2016 at 5:21 PM, Chao Xu <notifications@github.com> wrote:
>
> if PATCH doesn't work (worse - says it succeeded
> but didn't) for some class of fields, then PATCH doesn't work, and we
> should not support it. Full stop. It's going to end up causing someone an
> outage.
>
> Discussed in real life. PATCH works, it's just that there are certain operations you cannot express using the strategicmerge patch syntax.

Well, no, if there are operations that can not be represented, it
really DOESN'T work.

> kubectl etid cannot use PUT, because it's doing a three way merge (current state, last configuration, current configuration).
>
> I was wrong. kubectl edit is building a two-way patch. So perhaps it uses PATCH over PUT due to the efficiency.

I still think it should not use PUT, but I bet Brian can prove me wrong.
