### ISSUE TITLE
YAML rendering sometimes linewraps strings

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#32335]
This is more confusing than harmful.

I noticed while editing a pod that the YAML wrapped a string.  The below has line numbers turned on:

```
  5 apiVersion: v1
  6 kind: Pod
  7 metadata:
  8   annotations:
  9     kubernetes.io/created-by: |
 10       {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"hostnames-1190964384",    "uid":"f4ff207f-6b1c-11e6-aa24-42010af00003","apiVersion":"extensions","resourceVersion":"2341030"}}
 11     kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu request for container
 12       hostnames'
 13   creationTimestamp: 2016-09-08T23:32:03Z
```

Note that line 12 is a wrap of line 11.  Apparently this is valid YAML.  Reading it as JSON shows:

```
        "annotations": {
            "kubernetes.io/created-by": "{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicaSet\",\"namespace\":\"default\",\"name\":\"hostnames-1190964384\",\"uid\":\"f4ff207f-6b1c-11e6-aa24-42010af00003\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"2341030\"}}\n",
            "kubernetes.io/limit-ranger": "LimitRanger plugin set: cpu request for container hostnames"
        },
```

Rejoining the lines in the editor (kubectl edit) comes back as "Edit cancelled, no changes made."

I don't know who is deciding to wrap that, or why, but it caused me to wonder if it was broken.

**Comment by fraenkel** [comment]
@thockin Not much you can do. The code is Unmarshalling into an interface{} which doesn't allow us to set yaml tags to affect the style selected. The defaults use a flow style with 80 character margins which is what you are seeing.

**Comment by thockin** [comment]
It's just code.  We can fix it if we choose to. :)

**Comment by fraenkel** [comment]
Just have to fork yaml.v2 and set the best_width < 0  when marshalling and you will get the maximum line length for scalars (1 << 31 -1).

**Comment by thockin** [comment]
Or parameterize it upstream and re-vendor :)

**Comment by icambridge** [comment]
I'll work on this if no one is currently doing so.

**Comment by icambridge** [comment]
I've created https://github.com/go-yaml/yaml/pull/242 which allows for adding a `nowrap` tag to elements.

**Comment by thockin** [comment]
Any way we can make it an option to the marshal/unmarshal?  I don't think
we want to add another tag to every string field.  I guess maybe
annotations would be enough...

**Comment by icambridge** [comment]
@thockin Marshal and Unmarshal don't accept any parameters so adding options would break BC.

**Comment by thockin** [comment]
New method?

**Comment by icambridge** [comment]
We could make a new method. However, it seems like it would be a bit weird. Even the naming of it would be a bit weird: `MarshalWithoutWrapping`, `MarshalNowrap`, `MarshalNoFormatting`. And since it's only direct purpose would be for this project I can't imagine it getting merged.

**Comment by thockin** [comment]
Sorry, I was thinking 'MarshalWithOptions' which took an options struct, or
even a 'type MarshalConfig' and a method on that to Marshal using those
options.

I am just thinking out loud.  I appreciate the way 'spew' works in this
regard.

**Comment by icambridge** [comment]
Yea that idea is way better than anything going on in my head. I am not sure it'll get merged but I can create another PR adding a with options method and link the two and see what the yaml guys think is the best way forward.
