### ISSUE TITLE
Upstream Openshift Request Header Authentication

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#32333]
Allows Kubernetes APIserver to sit behind apache or nginx and trust that thign to do authentication.

Enables Kerberos, LDAP, SAML authentication, to the extent that Apache or Nginx support those ia plugins.

Docs for OpenShift feature.
https://docs.openshift.com/enterprise/3.0/admin_guide/configuring_authentication.html#RequestHeaderIdentityProvider

xref: https://github.com/kubernetes/kubernetes/pull/26352#issuecomment-231445190

**Comment by erictune** [comment]
@kubernetes/sig-auth

**Comment by liggitt** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/35452
