### ISSUE TITLE
v1.4.0 known issues / FAQ accumulator

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#32332]
Do what we did in previous releases, read https://github.com/kubernetes/kubernetes/issues/10760#issue-93324758

**Comment by lavalamp** [comment]
@pwittrock @spiffxp this is where we're collecting known issues for the release notes.

**Comment by caesarxuchao** [comment]
https://github.com/kubernetes/kubernetes/issues/32706 needs to get in the known issue of the release note.

**Comment by pwittrock** [comment]
@janetkuo Would you update this with the things we were seeing in the kubectl tests.  E.g. that deletes for some objects (e.g. RS) are asynchronous, so if you do a programatic delete and then a read you will still see the object there for a bit.

**Comment by caesarxuchao** [comment]
The `kubectl delete` is described in the CHANGELOG: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#kubectl-delete

**Comment by janetkuo** [comment]
@caesarxuchao That behavior change isn't specific to `kubectl delete`

**Comment by caesarxuchao** [comment]
Thanks for the reminder. I'll update the changelog to make it more generic.

**Comment by justinsb** [comment]
https://github.com/kubernetes/kubernetes/issues/32900 means that non-hostNetwork daemonsets will almost always have a pod that fails to schedule.  If we can't figure out mitigation there, then I think it needs  warning in the release notes.

**Comment by freehan** [comment]
kube-proxy does not handle loadBalancerSourceRange updates properly. #33033

**Comment by spiffxp** [comment]
@spiffxp collated comments on and links to this issue up to this point while updating release notes with contents of #33226

**Comment by spiffxp** [comment]
@spiffxp collated comments on and links to this issue up to this point while updating release notes with contents of #33226

**Comment by spiffxp** [comment]
@kubernetes/sig-release-misc I think we can close this, as we no longer cut 1.4.x releases, right?

**Comment by spiffxp** [comment]
/close
Closing.  Please /reopen if I've closed this in error.
