### ISSUE TITLE
flake: Build Still Running

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#32350]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/31235/kubernetes-pull-build-test-e2e-gke/10939/

**Comment by gmarek** [comment]
cc @kubernetes/test-infra-maintainers

**Comment by spxtr** [comment]
@rmmh did you restart PR Jenkins at 3 AM?

**Comment by rmmh** [comment]
There was a kernel panic 2 seconds after this build started.

We need to get off trusty builders.
