### ISSUE TITLE
e2e flake: namespaces are still active after e2e test is finished

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#32368]
We're seeing it in pretty much all our serial and soak suites and is probably most common failure reason for our tests - including a number of P0 issues. Marking it as a P0 release blocker because of this, @thockin please remove if you think it shouldn't be one.

cc @kubernetes/test-infra-maintainers @derekwaynecarr @rmmh

**Comment by wojtek-t** [comment]
@gmarek - links to failures please (I will try to look into it).

Also - I'm not sure this is v1.4 issue - I would suspect this is purely test issue.

**Comment by gmarek** [comment]
Possibly caused by errors like #32371

**Comment by wojtek-t** [comment]
The underlying problem here are "500" errors coming from GKE - we should debug and fix them and these problems will also disappear.

**Comment by wojtek-t** [comment]
This is basically duplicate of https://github.com/kubernetes/kubernetes/issues/31728

**Comment by goltermann** [comment]
Moving to 1.5, this is a non-release-blocker.

**Comment by calebamiles** [comment]
@wojtek-t, has this been resolved given that https://github.com/kubernetes/kubernetes/issues/31728 is closed. @saad-ali we should probably close this issue if confirmed that the issue has been resolved by migration
