### ISSUE TITLE
Re-enable the dynamic provisioner test.

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#32377]
We need to revert #32199 when the gke control plane is updated. This should be merged AFTER gke is ready.

I think https://github.com/kubernetes/kubernetes/pull/32200 may have been merged too early.  I'm doing an issue instead of a pull in case a bot did the merge.

**Comment by wojtek-t** [comment]
@lavalamp @pwittrock @jlowdermilk

**Comment by jlowdermilk** [comment]
Arrrgghhh. @brendandburns added the label so the bot merged it. Submit queue is now blocked.

**Comment by goltermann** [comment]
This hasn't been touched in 5d, but is listed as blocking v1.4.  Where are we on this?

**Comment by deads2k** [comment]
@jlowdermilk am I good to re-enable the dynamic provisioning test?

**Comment by goltermann** [comment]
@fabioy can you help answer for @jlowdermilk ?

**Comment by fabioy** [comment]
I think we're ok to re-enable this.

**Comment by deads2k** [comment]
> I think we're ok to re-enable this.

Opened https://github.com/kubernetes/kubernetes/pull/32896 to re-enable the test.  I don't know of a way for me to trigger the gke tests on the pull before merging

**Comment by dims** [comment]
@k8s-bot gke test this

**Comment by dims** [comment]
Trying something i spotted for kubemark - https://github.com/kubernetes/test-infra/blob/eaf966048d71f06653bb791315d636ecab2e78d7/ciongke/cmd/hook/main.go#L51
