### ISSUE TITLE
DNS/SkyDNS documentation issue

### ISSUE THREAD

**Issue by CaptTofu** [kubernetes/kubernetes#32381]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
## skydns, dns, docs

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT -- Documentation

**Kubernetes version** (use `kubectl version`):

master branch

**Environment**:
- **Cloud provider or hardware configuration**:

None, local setup via vagrant
- **OS** (e.g. from /etc/os-release):

CoreOS 1122.0.233
- **Kernel** (e.g. `uname -a`):

Linux c40 4.7.0-coreos-r1
- **Install tools**:

Vagrant + Ansible running on a container that provisions each host to a given state (master or minion)

Kubernetes running using hyperkube in a container
- **Others**:

**What happened**:

There is no way to run SkyDNS that I can find in the docs to specify an IP address or host of the API server that would work if the API server goes away and it started up on another host. 

The documentation has a couple issues.

The broken link in https://github.com/kubernetes/kubernetes/tree/master/build/kube-dns:

"See the example files (ReplicationController and Service)," 

The hyperlink to "ReplicationController" is broken and goes to https://github.com/kubernetes/kubernetes/blob/master/cluster/addns/dns/skydns-rc.yaml.in 

And should go to ("addons" instead of "addns"). 

https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/skydns-rc.yaml.in

I tried to fix this in the source but can't find where "addns" is coming from in the markdown conversion.

Secondly, in the section "How Does it work", starting with "SkyDNS depends on etcd for what to serv", the paragraph is lined out.

I now understand after looking at the 1.4 branch that DNS has been completely reworked to not use kube2sky, however, this is confusing if someone is just using the master branch.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

view https://github.com/kubernetes/kubernetes/tree/master/build/kube-dns

**Anything else do we need to know**:

master branch.

**Comment by gnufied** [comment]
Most of the kubernetes documentation afaict has been moved to - https://github.com/kubernetes/kubernetes.github.io/

**Comment by MrHohn** [comment]
FYI, documentation for DNS is on http://kubernetes.io/docs/admin/dns/ now.

**Comment by kargakis** [comment]
https://github.com/kubernetes/kubernetes/pull/38408 should satisfy this issue.
