### ISSUE TITLE
Kubernetes Metrics

### ISSUE THREAD

**Issue by jchauncey** [kubernetes/kubernetes#32392]
So I am trying to get a better understanding of the various metrics endpoints that kubernetes exposes. Currently, we collect metrics using telegraf from the following sources:
- https://`$KUBERNETES_SERVICE_HOST`:`$KUBERNETES_SERVICE_PORT`/metrics
- https://`$KUBERNETES_SERVICE_HOST`:`$KUBERNETES_SERVICE_PORT`/api/v1/proxy/nodes/`$NODE_NAME`/metrics

The first url gives me things about the overall system like api latency. The second url gives me more specific information related to the pods like CPU and memory usage. 

However, the problem I have right now is that it seems like the CPU usage is reported back as usage in seconds which is different from how kubernetes wants us to input usage for things like limits. So I would like to find out if there is a way to either gather CPU usage in `millicore/s` or `nanocore/s` which are exposed in cAdvisor but do not seem to be exposed in the k8s api.

**Comment by jingxu97** [comment]
cc @davidopp
