### ISSUE TITLE
kubectl cordon/uncordon nodes regularly fails with concurrent modification error

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#32391]
Even on a cluster of size 3, I regularly see concurrent modification problems with kubectl:

NODES=`kubectl get nodes -o name | cut -f 2 -d '/'`
for node in $NODES; do kubectl cordon $node; done
for node in $NODES; do kubectl uncordon $node; done

Doing that a few times and you are likely to see something like:

```
node "ip-172-20-0-180.us-west-2.compute.internal" cordoned
Error from server: Operation cannot be fulfilled on nodes "ip-172-20-0-4.us-west-2.compute.internal": the object has been modified; please apply your changes to the latest version and try again
node "ip-172-20-0-5.us-west-2.compute.internal" cordoned
```

I suspect that

1) kubectl cordon / uncordon should retry (or use a PATCH method)?
2) something - maybe the heartbeat? is causing concurrent modifications to the cluster.  (if we have trouble reproducing I can try to narrow this down - I'm going to test with an empty cluster later; right now it is a cluster with lots of PetSets & volumes)

**Comment by brendandburns** [comment]
I'd bet that this is caused by node status updates.  And I'd agree that cordon should probably retry.
