### ISSUE TITLE
Image garbage collection should fire if a node is running low on disk inodes

### ISSUE THREAD

**Issue by n-rook** [kubernetes/kubernetes#32400]
I'm continuously deploying docker images on pods, and for whatever reason, they are particularly inode hungry. As such, one of my nodes ran out of inodes, and I had to ssh in and clear out all the old images. 

It would be nice if [image garbage collection](http://kubernetes.io/docs/admin/garbage-collection/#image-collection) cleared out old images if the disk ran out of inodes, similarly to how it behaves today regarding disk space.

Version info:
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:13:23Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:21:58Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by Random-Liu** [comment]
It's in Kubernetes v1.4. :)
https://github.com/kubernetes/kubernetes/pull/31545

**Comment by n-rook** [comment]
Oh hey, you're right. That looks like it'd suffice, I'll let you close or leave open until 1.4 release as you prefer

**Comment by Random-Liu** [comment]
@n-rook Thanks for using Kubernetes! Close this one. If you still have this issue in v1.4, feel free to reopen this.

**Comment by ndenev** [comment]
Looks like this task and the one that's referenced are different things. I'm running Kubernetes 1.5.4 and I do see pods getting evicted on low inodes, but that's not the same as triggering garbage collection.
Pods are evicted then the node is in NotReady state until someone gets there and cleans some images, since the disk free space is 50%, but there are no free inodes.
