### ISSUE TITLE
iptables code uses semver parse/compare, but iptables doesn't use semantic versioning

### ISSUE THREAD

**Issue by danwinship** [kubernetes/kubernetes#32401]
pkg/util/iptables and pkg/proxy/iptables use go-semver to parse iptables versions to figure out if the iptables package is new enough to support certain features, but go-semver uses the extremely strict "Semantic Versioning" definition of what a version number is, and iptables has had release versions in the past that do not conform to it (eg, "1.4.19.1", which is illegal because it has 4 components rather than 3) and so probably will do so again in the future.

(Having a non-semver-parseable version means that (1) spurious errors will be logged, (2) `iptables -C` is assumed to be present, (3) `iptables -w` is assumed to not be present, (4) the pure-iptables proxier will not be used.)

kind-of related: #23854. The other semver library also requires strict syntactic compliance, so it doesn't help here. But maybe we should fork one of them and add a non-strict parsing mode? (We don't want a full rpm/dpkg-compatible version parser, but we could at least treat "X.Y" the same as "X.Y.0", and "X.Y.Z.A" the same as "X.Y.Z".)

**Comment by danwinship** [comment]
@thockin any opinions on this?

**Comment by thockin** [comment]
I think a sloppy-semver lib would be welcome.  To nitpick:

X.Y == X.Y.0

X.Y.Z.A > X.Y.Z, for A > 0

Something like that.  Append enough zeros to the end of the shorter set and then compare.
