### ISSUE TITLE
Kubelet log dumping binary

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#32411]
Protobuf?

```
I0909 21:02:12.837036   19956 request.go:558] Request Body: k8s^@
^K
^Bv1^R^EEvent^R¦^B
N
7gke-ciongke-default-pool-aded112d-qgpj.1472c3746846d329^R^@^Z^Gdefault"^@*^@2^@8^@B^@^R^
^DNode^R^@^Z&gke-ciongke-default-pool-aded112d-qgpj"&gke-ciongke-default-pool-aded112d-qgpj*^@2^@:^@^Z^HStarting"^
QStarting kubelet.*1
^Gkubelet^R&gke-ciongke-default-pool-aded112d-qgpj2^L^HÔÆÌ¾^E^P©<96>ú<8e>^C:^L^HÔÆÌ¾^E^P©<96>ú<8e>^C@^AJ^FNormal^Z
^@"^@
```

@dchen1107 @smarterclayton @kubernetes/sig-node

**Comment by smarterclayton** [comment]
Yes.  Typically I use "encoding/hex.Dump" for anything that could be binary
- request.go should already have a helper that prints JSON or binary Hex
depending on sniffing the context, but it looks like it's not on the
request side, just the response side.  Line 903 in request.go has a helper
if on the response.

**Comment by smarterclayton** [comment]
Fixed.
