### ISSUE TITLE
/metrics endpoint in kubelet returns incorrect cpu usage numbers

### ISSUE THREAD

**Issue by shamil** [kubernetes/kubernetes#32414]
**Kubernetes version**: 1.3.6

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS**: debian jessie (8.5), ami: k8s-1.3-debian-jessie-amd64-hvm-ebs-2016-06-18
- **Kernel**: 3.16.0-4-amd64
- **Install tools**: kops

I'm facing similar issue to #27194, but with kubelet `/metrics` endpoint. I use Prometheus to scrape that endpoint and seems like  `container_cpu_usage_seconds_total` results are not updated properly. Container shows about 14% usage, but `kubelet` doesn't update the metric's value at all.

Here is the PromQL I use: 

```
container_cpu_usage_seconds_total{kubernetes_namespace="default", kubernetes_container_name="logstash"}
```

And here is the actual  `top` snapshot from  the container

```
top - 12:34:46 up 9 days,  3:50,  0 users,  load average: 1.47, 1.46, 1.72
Tasks:   4 total,   1 running,   3 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4.2 us,  0.8 sy,  0.0 ni, 94.8 id,  0.0 wa,  0.0 hi,  0.2 si,  0.1 st
KiB Mem:  33016188 total, 16315132 used, 16701056 free,   591984 buffers
KiB Swap:        0 total,        0 used,        0 free. 10561156 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     
    1 logstash  20   0 7490020 922680  19096 S  13.6  2.8 927:10.96 java        
10141 root      20   0   21972   3728   3204 S   0.0  0.0   0:00.00 bash        
11432 root      20   0    4336    712    624 S   0.0  0.0   0:00.00 sh          
11443 root      20   0   23620   2696   2356 R   0.0  0.0   0:00.00 top     
```

**Comment by timstclair** [comment]
>  results are not updated properly

Is the metric set at all? What value is it stuck at?

From the code, it looks like the `kubernetes_container_name` label is only used in testing. I think you want to look for something like
```
container_cpu_usage_seconds_total{container_env_foo_env="prod",container_label_foo_label="bar",cpu="cpu00",id="testcontainer",image="test",name="testcontaineralias",zone_name="hello"} 2e-09
```

**Comment by timstclair** [comment]
Note: the labels will be changing with Kubernetes 1.4 to only `container_name`, `pod_name`, `namespace`, `id`, `image`, and `name` labels. See https://github.com/kubernetes/kubernetes/pull/31064

**Comment by shamil** [comment]
@timstclair , yes the metric is set.  Even more weird for some containers the metric actually updates the value. 

Another weird thing, if I put some load on that container (for example by running: `yes >/dev/null` inside container), I do see the values updating, but if the load is not as big, about 14% in my case the values are stuck.

Below is an example for the container I mentioned in the issue.
The values are stuck. No matter how long I waited they're stuck at and not updated. The actual container is using about 14% CPU

```
cpu00 261.02146344
cpu01 270.89456025
cpu02 277.218920676
cpu03 290.482908446
cpu04 654.412889036
cpu05  667.163369889
cpu06 687.723893944
cpu07 830.274957044
```
 
P.S.
Not sure PromQL is relevant here, I can adopt any changes of v1.4

**Comment by shamil** [comment]
Had the issue agai, but now with all PODs. CPU usage metric was stuck. I noticed that when I restart the pods the metric starts reporting proper usage.

Do you need any more information that I can provide, to help you find the root cause? I really want this to be resolved, before `1.4`

**Comment by timstclair** [comment]
When it gets stuck, can you check the CPU usage reported by cAdvisor? You can get that at the `/stats/<pod name>/<container name>` or `/stats/<namespace>/<pod name>/<pod uid>/<container name>` endpoint.

**Comment by shamil** [comment]
@timoreimann here is what I get from stats endpoint for one of the PODs  which has CPU usage stuck

```
  {
    "timestamp": "2016-09-13T20:45:33.078928305Z",
    "cpu": {
     "usage": {
      "total": 58407139303,
      "per_cpu_usage": [
       24863764705,
       14963129413,
       10522711260,
       8057533925
      ],
      "user": 32320000000,
      "system": 6830000000
     },
     "load_average": 0
    }
```

**Comment by shamil** [comment]
Actually, I just did some load on that container. Saved the whole stats snapshot (`json`) before load and another one after load. Then used side by side diff, and the only thing  that changed were the `timestamp`s.

So it turns out, that all stats are stuck not just CPU...

**Comment by timoreimann** [comment]
@shamil I suppose you meant to mention @timstclair instead of me. :-)

**Comment by SleepyBrett** [comment]
I think this is probably related to my issue here: https://github.com/kubernetes/kubernetes/issues/32304

**Comment by shamil** [comment]
@timstclair, I'm still hitting this from time to time. Only after restarting `kubelet` the metrics reporting are back to normal. I've upgraded to `k8s 1.4` the issue still exist.

Do we even have a clue?

**Comment by dashpole** [comment]
see my comment: https://github.com/kubernetes/kubernetes/issues/32304#issuecomment-265886938
