### ISSUE TITLE
Explicit pod QoS class.

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes/kubernetes#32468]
This is a feature request to support an optional, explicit QoS class override in the pod spec.

### Background

From the resource QoS documentation:

> The relationship between "Requests and Limits" and "QoS Classes" is subtle. Theoretically, the policy of classifying pods into QoS classes is orthogonal to the requests and limits specified for the container. Hypothetically, users could use an (currently unplanned) API to specify whether a pod is guaranteed or best-effort. However, in the current design, the policy of classifying pods into QoS classes is intimately tied to "Requests and Limits”

_NOTE: Explicit QoS was discussed in a comment thread on the original proposal PR [here](https://github.com/kubernetes/kubernetes/pull/26751#discussion_r66562151) during which it was suggested to create a new issue. This is to collect ideas on whether a change is desired and if so what it should look like. Since these features are new it might be worthwhile to await feedback from users and whether there's a real problem._

### Problem statement

There are good arguments against expanding the API. However, here’s justification: the API already allows users to differentiate QoS for pods. Doing this is difficult since the setting is spread across several fields (request and limit for each resource type). The corollary is the request and limit fields are overloaded. There are constraints imposed by the current strategy, for example inability to declare best-effort pods that use a GPU device.

An additional motivation is to avoid conflicts with recommended plugins and configuration. The limit ranger admission control plugin is currently recommended in the official docs ([link](http://kubernetes.io/docs/admin/admission-controllers/)) for Kubernetes v1.0+. So, with recommended settings and default configuration it seems not possible to create best-effort pods in the default namespace, as unsized containers are automatically assigned 100 milli-cores worth of cpu shares. Similarly, the experimental initial resources plugin could modify the QoS class for incoming pods as a side effect. This raises a question about portability of intent. Does (should) my best-effort pod spec in cluster A also specify a best-effort pod in cluster B?

Making the QoS class explicit could allow better admission control for best-effort pods (e.g. to avoid memory-hungry batch jobs from being frequently evicted or OOMing).

### A first stab

Here’s one idea for doing something optional and backward-compatible with the goal of improving user experience:

1. Add an (optional) QoS class field to the pod spec. At first, this could even be a label or annotation marked “alpha”.
1. Move the existing classification inference code into an admission control plugin that applies the appropriate QoS class, if unspecified.
1. Update the function [`qos.GetPodQos`](https://github.com/kubernetes/kubernetes/blob/f2ddd60eb9e7e9e29f7a105a9a8fa020042e8e52/pkg/kubelet/qos/qos.go#L48) to simply return the QoS class from the pod spec.

If the user does nothing different in pod definitions, the same QoS class would be inferred as before.

CC: @dubstack @vishh @derekwaynecarr @ronnielai @timothysc @balajismaniam @nqn @kozyraki

**Comment by derekwaynecarr** [comment]
Can you elaborate on why a `BestEffort` pod cannot consume a GPU today?  Existing QOS is only tied to `cpu` and `memory` resources at this time.  We have not extended QOS to other resources yet.

I think the intersection between `LimitRange` and `QOS` is a tangential discussion and the presence of one should not influence the other.  If the concern is ability to create a `BestEffort` pod in the presence of a `LimitRange`, we can solve that using alternate means similar to what we did with `ResourceQuota` with scopes.

**Comment by ConnorDoyle** [comment]
@derekwaynecarr if you look at the current implementation of [`qos.GetPodQos`](https://github.com/kubernetes/kubernetes/blob/f2ddd60eb9e7e9e29f7a105a9a8fa020042e8e52/pkg/kubelet/qos/qos.go#L48), a pod that consumes a GPU cannot be classified best effort, since all resource dimensions are considered. It looks like a pod that consumes only a single GPU would get the guaranteed class. Please help me out if I misunderstood that.

I agree LimitRange and QoS should be tangential (orthogonal) but currently they are not. Adding exceptions might be good to do if classification remains implicit. That example to me illustrates the core issue which anyone dealing with resource shapes also has to track QoS and potentially encode workarounds. At a higher level, it promotes leaking the QoS implementation elsewhere in the code base and also external code, which could make a future change really painful.

**Comment by derekwaynecarr** [comment]
The GPU thing seems like a bug IMHO pod qos should only look at CPU and
Memory today.

**Comment by derekwaynecarr** [comment]
I think GPU support is also alpha now so it's not surprising that it may
have been overlooked.

I sometimes wonder if we are overloading QoS in our discussions.   The
decision to unify QOS on a unified model was to align with the direction of
cgroups.  We used to have per resource QOS and moved away from that so we
could have a unified model.

For the topics you are discussing, are these resources outside of the
cgroup hierarchy and therefore constitute a different type of qos
altogether and maybe we call that thing something different?

**Comment by ConnorDoyle** [comment]
> I sometimes wonder if we are overloading QoS in our discussions.

A distinct possibility :) Some speculation follows, but bear with me.

The Kubelet right now interprets part of the pod spec as a QoS classification. From the Kubelet's PoV, QoS is a request from a user for preferential treatment. Presumably there's a reason for that request (e.g. e2e service latency negatively correlated w/ revenue). So in my mind QoS represents inversion of control, away from an ad-hoc approach where the app owner takes responsibility by packaging scripts and config to manage the environment together with executables. Eventually it would be really cool if pods could come with a description for how to measure whether they are upholding the promises made to _their_ customers. Think Service Level Indicators and Objectives (e.g. SLI: latency, SLO: 99% tail latency). Then the whole request would become intent-based instead of implementation-based. As in, "here Kubelet, help me maintain these promises" (whatever that means to you). As mentioned in other places, like the discussions on cpuset support, intent-based requests can leave more room for flexibility in the implementation. Once a low-level implementation detail leaks out into the API some users will depend on it, taking it away later could cause problems.

> For the topics you are discussing, are these resources outside of the cgroup hierarchy and therefore constitute a different type of qos altogether and maybe we call that thing something different?

> The decision to unify QOS on a unified model was to align with the direction of cgroups.  We used to have per resource QOS and moved away from that so we could have a unified model.

Looking for more opinions on this topic, but to me the same arguments that motivated unifying the cgroup hierarchy and unifying per-resource QoS apply here. It's hard to imagine what combinations of existing QoS and that other classification would make sense. It seems more forward-thinking to massage the semantics of QoS to not mean cgroups, but rather a higher level concept in the user's domain.

**Comment by vishh** [comment]
> There are good arguments against expanding the API. However, here’s justification: the API already allows users to differentiate QoS for pods. Doing this is difficult since the setting is spread across several fields (request and limit for each resource type). The corollary is the request and limit fields are overloaded. There are constraints imposed by the current strategy, for example inability to declare best-effort pods that use a GPU device.

Binary resources should ideally not be considered for QoS. They might interfere with other QoS resources, but that should not affect the API. 

> An additional motivation is to avoid conflicts with recommended plugins and configuration. The limit ranger admission control plugin is currently recommended in the official docs (link) for Kubernetes v1.0+. So, with recommended settings and default configuration it seems not possible to create best-effort pods in the default namespace, as unsized containers are automatically assigned 100 milli-cores worth of cpu shares. Similarly, the experimental initial resources plugin could modify the QoS class for incoming pods as a side effect. This raises a question about portability of intent. Does (should) my best-effort pod spec in cluster A also specify a best-effort pod in cluster B?

The default limit range was meant to avoid users un-intentionally running best-effort pods. QoS will be per-deployment in reality. The fact that a plugin modified QoS is probably a feature that the cluster admin has setup.

> Making the QoS class explicit could allow better admission control for best-effort pods (e.g. to avoid memory-hungry batch jobs from being frequently evicted or OOMing).

The issue of OOMs should be alleviated once the scheduler supports usage based scheduling. Overcommit on the node should be controlled to an extent based on utilziation. 

> Here’s one idea for doing something optional and backward-compatible with the goal of improving user experience:
> Add an (optional) QoS class field to the pod spec. At first, this could even be a label or annotation marked “alpha”.

I disagree. This will make the API very confusing.

If there is any other user facing use case that motivates making QoS explicit, I'd be happy to reconsider adding explicit QoS.

**Comment by vishh** [comment]
> Looking for more opinions on this topic, but to me the same arguments that motivated unifying the cgroup hierarchy and unifying per-resource QoS apply here. It's hard to imagine what combinations of existing QoS and that other classification would make sense. It seems more forward-thinking to massage the semantics of QoS to not mean cgroups, but rather a higher level concept in the user's domain.

This intention is valid. In reality though, the set of available features does influence the API to a major extent.

**Comment by derekwaynecarr** [comment]
I spawned #33108 to handle the opaque resources influencing the node level qos.

**Comment by nqn** [comment]
I don't think the GPU resource's influence on QoS is the issue per se. It is the user experience (as you already hint to) so I would love to see users chime in on this. Whether the current inferred class is easier or harder to understand than the explicit one. I'm afraid I did not find it intuitive.
As to the limit ranger; is the fact that people are running BE pods by accident not an indication that it is not obvious which class you are scheduling in?

Another concern from our side was "just" unpredictable or unintentional changes of QoS class. With admission controllers like the limit ranger, it looked like it could impact node local QoS policies.

To make progress, it would probably make sense to get direct user input and/or get some insight from others like @bgrant0607 or @kozyraki

**Comment by vishh** [comment]
> As to the limit ranger; is the fact that people are running BE pods by accident not an indication that it is not obvious which class you are scheduling in?

Not really. The state of system wrt. resource isolation required us to add a limit ranger in the past. It might not be necessary moving forward to include a limit range by default. 

> Another concern from our side was "just" unpredictable or unintentional changes of QoS class. With admission controllers like the limit ranger, it looked like it could impact node local QoS policies.

My point is that Limit Range is meant to influence QoS. Why is that considered unintentional. They are put in place by admins intentionally. For example, one can use Limit Range to disallow BE pods all-together. 

FYI: The current design of QoS was a brain child of @bgrant0607

**Comment by derekwaynecarr** [comment]
As for the core of this discussion around QOS:

* Developers that build web console experiences need to reproduce our QOS calculation logic.  This makes them vulnerable to the same bugs we just fixed in #33108 for each experience they produce.  I am supportive of a read-only attribute on `PodStatus` that states the QOS class of a Pod since once we have qos enforced on the node, we have said a pod cannot change its QOS in its life-time.  /cc @jwforres 
* I think the idea of an explicit pod QoS class settable by the end-user is coming from the core desire to support a complex scenario, where some of the resources are not isolated/managed by the kubelet itself, and that use case needs to be further elaborated upon before saying users should just state their QoS.

**Comment by ConnorDoyle** [comment]
@derekwaynecarr that makes sense. I created #33255 to track the read-only QoS class attribute, and closing this issue for now. Thanks everyone for discussing it.

**Comment by bgrant0607** [comment]
+1 to a status field.

Original discussion:
#147
#11713

An explicit QoS spec field would also be confusing, IMO, since many combinations of QoS and request/limit would not make sense (e.g., Guaranteed with no request/limit). Borg has explicit fields, but the more interesting use cases aren't expressible with unified cgroup hierarchy, anyway.
