### ISSUE TITLE
Cluster upgrade fails for 2K+ nodes

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#32465]
We're tryin to deploy a 2000 node cluster.  Run the guestbook, then upgrade the master and nodes.  Having some trouble upgrading the nodes currently.

**Comment by pwittrock** [comment]
Closing since the issue appeared to be human error

**Comment by davidopp** [comment]
Filed #32466 for ideas we had to make it easier for people to detect and fix problems with the node rolling upgrades.
