### ISSUE TITLE
Make cluster/gce/upgrade.sh and cluster/kube-down.sh more helpful when the rolling upgrade fails

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#32466]
`cluster/gce/upgrade.sh` uses `gcloud alpha compute rolling-updates` under the covers to do node upgrade. If the MIG rolling update wedges for some reason, we need to give the user enough information to recover (automatically recovering is probably too error-prone). One possibility is that when it starts node upgrade, upgrade.sh should print out the commands for monitoring the status and canceling (canceling requires pausing first, then canceling). Something like

```
You can monitor the progress of the upgrade using
% gcloud alpha compute rolling-updates describe XXX
and
% gcloud alpha compute rolling-updates list-instance-updates XXX

To pause, resume, cancel, or rollback the upgrade, first kill the upgrade.sh script and then use
% gcloud alpha compute rolling-updates <pause/resume/cancel/rollback> XXX
(to cancel, you must pause first and then cancel).

If you kill the upgrade, you'll need to remove the old instance template using
gcloud compute instance-templates delete YYY
```

where YYY is the old instance template name and XXX is the rolling update ID (we should fill these in for the user). In large clusters there will be more than one MIG, hence more than one rolling-update, so we'd need to list all of the XXX's (i.e. multiple `gcloud alpha compute rolling-updates describe` and `list-instance-updates` and `<pause/resume/cancel/rollback>` lines).

We should also have `kube-down.sh` notice if there are any rolling upgrades that are in any state other than CANCELLED, and print a message telling the user to pause and then cancel them if they think they should not be running, using language similar to the above.

cc/ @gmarek @wojtek-t @grodrigues3

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @davidopp

**Comment by dims** [comment]
@davidopp all issues must be labeled either release blocker or non release blocking by end of day 18 November 2016 PST. (or please move it to 1.6) cc @kubernetes/sig-cluster-lifecycle (?)

**Comment by davidopp** [comment]
not

**Comment by dims** [comment]
thanks @davidopp

**Comment by errordeveloper** [comment]
Considering how stale this is, the chances are it won't get fixed before kube-up gets deprecated completely.
