### ISSUE TITLE
[Kubectl - Pet Set] Kubectl support some features for Pet Set

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#32489]
* kubectl short cut for get petset

I find `kubectl` doesn't support short cut for Pet Set. Users need to type `kubectl get petset` show petset list. Since `kubectl` support short cut `kubectl get po` for pod and `kubectl get svc` for service. Why not add short cut `kubectl get ps` for petset?

* kubectl replace -f

```
# ONLY modify `petset.spec.replicas` field in petset.yml
$ kubectl replace -f petset.yaml
service "nginxed" replaced
The PetSet "web" is invalid.
spec: Forbidden: updates to petset spec for fields other than 'replicas' are forbidden.
```

When type `kubectl -f petset.yml`(only modify `replicas` field), I receive the error:

`spec: Forbidden: updates to petset spec for fields other than 'replicas' are forbidden.`

I know the only updatable field on a Pet Set is `replicas`, and I can use `kubectl patch -p` to achieve scaling up/down. Since kubectl support `replace -f` for RC, why we can't use `kubectl replace -f` for the same purpose? Or, is it a wrong behaviour that we should fix?

@bprashanth @smarterclayton

**Comment by bprashanth** [comment]
did you try replace on HEAD or 1.3? 
I think we already decided to not do anything about the short form till it goes beta.

**Comment by m1093782566** [comment]
Okay, will try. BTW, do we have a timeline for beta?

**Comment by janetkuo** [comment]
I tried and it works on HEAD

**Comment by janetkuo** [comment]
It might be easier to use `kubectl scale`, though

**Comment by bprashanth** [comment]
oh yeah scale works, i assumed OP was trying to replace some field other than replicas like image. Closing for now please reopen if still an issue.
