### ISSUE TITLE
PV controller sync period is now 3 minutes

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#32497]
With shared informers merged in PR #30825, PV re-sync period is now 3 minutes and more, which is too much for the controller (it was 15 seconds before). E.g. e2e tests for deletion of provisioned volumes take 3-6 minutes longer.

It could be the reason behind #32492, but it's hard to guess without controller logs.

We need either shorter sync for this shared informer or revert the PR completely.

@kubernetes/sig-storage

**Comment by thockin** [comment]
@deads2k @davidopp

**Comment by wongma7** [comment]
Related? https://github.com/kubernetes/kubernetes/issues/26406

**Comment by jsafrane** [comment]
@wongma7, yes, please revert the PR for now, we can add shared informers when they're fixed.

**Comment by thockin** [comment]
What is riskier for 1.4 reverting this or not reverting it?

**Comment by wongma7** [comment]
@thockin the code isn't (& shouldn't be) in 1.4. so can revert in master safely.

**Comment by thockin** [comment]
in that case, why not leave it and find the real fix?

**Comment by wongma7** [comment]
It's slowing the tests & Jan thinks it is breaking this test https://github.com/kubernetes/kubernetes/issues/32492#issuecomment-246593831 . I'm inclined to agree looking at previous consequences of high resync period mentioned here https://github.com/kubernetes/kubernetes/pull/26414

anyway, Jan will have a better answer when he gets back

**Comment by thockin** [comment]
ACK, OK

**Comment by jsafrane** [comment]
I'd love to have it fixed properly in shared informers, but these parts are fragile and I failed miserably when I tried to fix a bug there.
