### ISSUE TITLE
Cannot specify --packages in kubernetes spark example

### ISSUE THREAD

**Issue by artitw** [kubernetes/kubernetes#32494]
I am following the instructions laid out on [Kubernetes' Spark example][1]. I can get to the step with launching the PySpark shell. However, I need to use PySpark with JDBC to connect to my Postgres database. Before I tried Kubernetes, I got the JDBC working with Spark using the `spark-defaults.conf` file:

    spark.driver.extraClassPath /spark/postgresql-9.4.1209.jre7.jar
    spark.executor.extraClassPath /spark/postgresql-9.4.1209.jre7.jar

I also had to download the driver into the location first. How do I achieve the same thing with Kubernetes? I don't think I can do 

    kubectl exec zeppelin-controller-xzlrf -it pyspark --jars /spark/postgresql-9.4.1209.jre7.jar

because the jar would have to be inside the container first. Therefore, maybe I can get it working if I can get the jar file inside the container, but how do I do that? Any thoughts or help is greatly appreciated.

I tried the following

    kubectl exec zeppelin-controller-2p3ew -it -- pyspark --packages org.postgresql:postgresql:9.4.1209.jre7.jar

which appears to boot up and recognizes the package argument but still fails:

    Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
    [GCC 4.9.2] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    Ivy Default Cache set to: /root/.ivy2/cache
    The jars for the packages stored in: /root/.ivy2/jars
    :: loading settings :: url = jar:file:/opt/spark-1.5.2-bin-hadoop2.6/lib/spark-assembly-1.5.2-hadoop2.6.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
    org.postgresql#postgresql added as a dependency
    :: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
    	confs: [default]
    :: resolution report :: resolve 2294ms :: artifacts dl 0ms
    	:: modules in use:
    	---------------------------------------------------------------------
    	|                  |            modules            ||   artifacts   |
    	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
    	---------------------------------------------------------------------
    	|      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
    	---------------------------------------------------------------------
    
    :: problems summary ::
    :::: WARNINGS
    		module not found: org.postgresql#postgresql;9.4.1209.jre7.jar
    
    	==== local-m2-cache: tried
    
    	  file:/root/.m2/repository/org/postgresql/postgresql/9.4.1209.jre7.jar/postgresql-9.4.1209.jre7.jar.pom
    
    	  -- artifact org.postgresql#postgresql;9.4.1209.jre7.jar!postgresql.jar:
    
    	  file:/root/.m2/repository/org/postgresql/postgresql/9.4.1209.jre7.jar/postgresql-9.4.1209.jre7.jar.jar
    
    	==== local-ivy-cache: tried
    
    	  /root/.ivy2/local/org.postgresql/postgresql/9.4.1209.jre7.jar/ivys/ivy.xml
    
    	==== central: tried
    
    	  https://repo1.maven.org/maven2/org/postgresql/postgresql/9.4.1209.jre7.jar/postgresql-9.4.1209.jre7.jar.pom
    
    	  -- artifact org.postgresql#postgresql;9.4.1209.jre7.jar!postgresql.jar:
    
    	  https://repo1.maven.org/maven2/org/postgresql/postgresql/9.4.1209.jre7.jar/postgresql-9.4.1209.jre7.jar.jar
    
    	==== spark-packages: tried
    
    	  http://dl.bintray.com/spark-packages/maven/org/postgresql/postgresql/9.4.1209.jre7.jar/postgresql-9.4.1209.jre7.jar.pom
    
    	  -- artifact org.postgresql#postgresql;9.4.1209.jre7.jar!postgresql.jar:
    
    	  http://dl.bintray.com/spark-packages/maven/org/postgresql/postgresql/9.4.1209.jre7.jar/postgresql-9.4.1209.jre7.jar.jar
    
    		::::::::::::::::::::::::::::::::::::::::::::::
    
    		::          UNRESOLVED DEPENDENCIES         ::
    
    		::::::::::::::::::::::::::::::::::::::::::::::
    
    		:: org.postgresql#postgresql;9.4.1209.jre7.jar: not found
    
    		::::::::::::::::::::::::::::::::::::::::::::::
    
    
    
    :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
    Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.postgresql#postgresql;9.4.1209.jre7.jar: not found]
    	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1011)
    	at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:286)
    	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:153)
    	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
    	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
    Traceback (most recent call last):
      File "/opt/spark/python/pyspark/shell.py", line 43, in <module>
        sc = SparkContext(pyFiles=add_files)
      File "/opt/spark/python/pyspark/context.py", line 110, in __init__
        SparkContext._ensure_initialized(self, gateway=gateway)
      File "/opt/spark/python/pyspark/context.py", line 234, in _ensure_initialized
        SparkContext._gateway = gateway or launch_gateway()
      File "/opt/spark/python/pyspark/java_gateway.py", line 94, in launch_gateway
        raise Exception("Java gateway process exited before sending the driver its port number")
    Exception: Java gateway process exited before sending the driver its port number
    >>> 

  [1]: https://github.com/kubernetes/kubernetes/tree/release-1.4/examples/spark

**Comment by janetkuo** [comment]
cc @kubernetes/examples @zmerlynn @mattf

**Comment by chrislovecnm** [comment]
The jars need to be in the container.  You can use http, s3, hdfs hosted version of the jars as well.  If you need the jars in the container, then you need a custom container.

**Comment by mattf** [comment]
expanding on what @chrislovecnm said, see "advanced dependency management" at http://spark.apache.org/docs/latest/submitting-applications.html

you can kubectl exec and download the jar into the container and use file://, but you're likely better off using http[s]:// and pulling the jar from a cache somewhere.

you may also simply need to specify a --repositories for your --packages

**Comment by chrislovecnm** [comment]
@artitw let us know, but we probably want to close this issue.

**Comment by artitw** [comment]
@janetkuo @chrislovecnm @mattf thanks for your help and providing different options. I ended up using my own Docker image that contains the jar in it.

**Comment by karthikeayan** [comment]
I am doing this in my local, which resolves multiple dependencies as below,

```
Loading .env environment variables…
Python 3.7.3 (default, Dec 13 2019, 19:58:14)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Ivy Default Cache set to: /Users/username/.ivy2/cache
The jars for the packages stored in: /Users/username/.ivy2/jars
:: loading settings :: url = jar:file:/Users/username/.local/share/virtualenvs/fpg-data-lake-sXu-eYAV/lib/python3.7/site-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.crealytics#spark-excel_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-66b7028e-3258-412e-b768-a65621353793;1.0
       confs: [default]
       found com.crealytics#spark-excel_2.11;0.12.4 in central
       found org.apache.poi#poi;4.1.0 in central
       found commons-codec#commons-codec;1.12 in central
       found org.apache.commons#commons-collections4;4.3 in central
       found org.apache.commons#commons-math3;3.6.1 in central
       found org.apache.poi#poi-ooxml;4.1.0 in central
       found org.apache.poi#poi-ooxml-schemas;4.1.0 in central
       found org.apache.xmlbeans#xmlbeans;3.1.0 in central
       found com.github.virtuald#curvesapi;1.06 in central
       found com.norbitltd#spoiwo_2.11;1.6.0 in central
       found org.scala-lang.modules#scala-xml_2.11;1.2.0 in central
       found joda-time#joda-time;2.9.9 in central
       found org.joda#joda-convert;2.0.1 in central
       found com.monitorjbl#xlsx-streamer;2.1.0 in central
       found com.rackspace.apache#xerces2-xsd11;2.11.1 in central
       found com.rackspace.eclipse.webtools.sourceediting#org.eclipse.wst.xml.xpath2.processor;2.1.100 in central
       found edu.princeton.cup#java-cup;10k in central
       found com.ibm.icu#icu4j;4.6 in central
       found xml-resolver#xml-resolver;1.2 in central
       found xml-apis#xml-apis;1.4.01 in central
       found org.slf4j#slf4j-api;1.7.25 in central
       found org.apache.commons#commons-compress;1.19 in central
```

How to achieve this in Kubernetes spark-submit, do I have to download each and every dependency and build a custom image?
