### ISSUE TITLE
Move Taints & Tolerations & Interpod-affinity and anti-affinity out of Beta 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#32499]
This issue to enumerate and track for 1.5 release the items needed to move the following @kubernetes/sig-scheduling features out of alpha/beta and into product:

Taints and Tolerations 
Inter-pod Affinity and Anti-Affinity

/cc @ConnorDoyle @ingvagabund @jayunit100 @davidopp 

We should socialize the checklist of items here.

**Comment by jeremyeder** [comment]
#25320

**Comment by davidopp** [comment]
Is there a reason for a new issue here? #25320 and #25319 should cover it. I'd prefer not to have duplicate issues...

**Comment by timothysc** [comment]
Bleh so many issues.. closing this one.
