### ISSUE TITLE
If GarbageCollection is on, NamespaceController gets confused

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#32519]
The logic flow of namespace controller is as follows:

1) estimate graceful termination for groupVersionResource
2) delete collection for groupVersionResource
3) list collection for groupVersionResource and expect 0 items unless graceful estimate != 0

This works great unless garbage collection is on.  When GC is on, the list call is not returning 0 items as expected and the namespace controller says WTF! and it sees unexpected items.  This is because the GC orphan finalizer has not yet run to completion.

If GC is on in our E2E runs, there is good reason to believe this is the source of all our namespace deletion flakes.

/cc @kubernetes/sig-api-machinery @smarterclayton @ncdc @lavalamp @caesarxuchao

**Comment by derekwaynecarr** [comment]
Once the GC process resolves, the namespace controller gets out of its rate limiting, and the namespace is purged.

/cc @wojtek-t

**Comment by derekwaynecarr** [comment]
A simple fix for now would be for namespace controller to assume a 2s estimate for termination in presence of finalizers...

**Comment by caesarxuchao** [comment]
The analysis makes sense. The Oprhan finalizer is only put on RCs and RSs. Are they the resources reported in the flaky tests?

If we modify the namespace controller to send deletion request with deleteOptions.OrphanDependents=false, then the object will be deleted directly. But then GC will try to collect the dependents (pods of a RC), I assume this won't cause a race between namespace controller and GC.

**Comment by derekwaynecarr** [comment]
@caesarxuchao -- the RC was the resource I debugged with @smarterclayton  just now.

**Comment by caesarxuchao** [comment]
Thanks for the confirmation. Could you try to use deleteOptions.OrphanDependents=false? If GC and namespace controller both try to delete a pod, will that cause a problem? I guess it would be fine.

**Comment by derekwaynecarr** [comment]
@caesarxuchao - I am putting together a patch right now.

**Comment by derekwaynecarr** [comment]
I am going to do the following:

* set orphan dependents to true on delete collection calls
* have namespace controller check for pending finalizers when it verifies the LIST collection call and default to a 2s estimation if they are present

**Comment by caesarxuchao** [comment]
> set orphan dependents to true 

To false, then no orphan finalizer will be added. (true is the default value)

> have namespace controller check for pending finalizers when it verifies the LIST collection call and default to a 2s estimation if they are present

What if there are other finalizers in the future? 2s might not be enough for other finalizers. Maybe namespace controller should wait for finalizers in general.

**Comment by derekwaynecarr** [comment]
@caesarxuchao -- yes, i typed that wrong, false it is.

it needs to wait, but its more like how long it should want until we try again.  @lavalamp and i settled on 15s for now since that aligns with the standard behavior if namespace had pods with default grace periods.

**Comment by nikhiljindal** [comment]
fwiw, 15s seems too large to me.
We should ideally be watching these resources to check if all finalizers are gone.

**Comment by derekwaynecarr** [comment]
right now, we dont want namespace controller to watch all cluster state, we can tweak the 15s later if need be.  my PR will make the orphan finalizer not get added anymore, so normal ns deletion is not impacted at all.  its only if users add their own finalizer is 15s going to have a penalty.
