### ISSUE TITLE
Node E2E: The test using dynamic configuration should restore original configuration after test.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#32513]
We introduced dynamic kubelet configuration in Kubernetes v1.4, which is quite useful in node e2e test!

Currently, the dynamic kubelet configuration test and node benchmark test already start to use the cool feature.

However, there are 2 little problems:
- Because of lack of default kubelet ConfigMap, currently each test has to create the configmap themselves. But if those tests run in the same suite, there will be create conflict.
- Currently, those tests changed the kubelet config didn't restore the config change after the test.

Maybe we should create a default Kubelet ConfigMap in `BeforeSuite`, and let all tests only update the ConfigMap. Each test should change the config in test, and restore the config in `AfterEach`.

@mtaufen 
/cc @kubernetes/sig-node

**Comment by mtaufen** [comment]
We should also wait for the config to be completely restored before finishing the AfterEach (poll /configz and do a deep comparison between the map you posted and the map you get from /configz until they match).

**Comment by mtaufen** [comment]
This can be closed, the concerns were addressed long ago.
