### ISSUE TITLE
Fix memory eviction test parameters!

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#32516]
Current consumption rate is set to an order of magnitude higher than it should be. See https://github.com/kubernetes/kubernetes/pull/32514

**Comment by pwittrock** [comment]
@mtaufen Can we close this?

**Comment by dchen1107** [comment]
Yes, cherrypick pr: https://github.com/kubernetes/kubernetes/pull/32583 Thanks @eparis Close this.
