### ISSUE TITLE
upgrading master doesn't upgrade kubectl

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#32538]
Running `cluster/gce/upgrade.sh -M v1.4.0-beta.3` upgrades the master as expected, but ssh-ing into the master @jingxu97 discovered that kubectl was still at 1.3.6. Feel free to close if this was a conscious decision, I'd  expect to find features present in 1.4 kubectl on a 1.4 master, though. 

@kubernetes/sig-cluster-lifecycle

**Comment by mikedanese** [comment]
This is more of a GCI issue. New binaries are placed in `/home/kubernetes/bin/` which systemd units use explicitly. However `/home/kubernetes/bin/` is not on the PATH. If you run `kubelet` or `kubectl` you are using the binaries that were baked into GCI when it was built.

**Comment by bprashanth** [comment]
shouldn't the kubectl in the gci image we're using for 1.4 be 1.4, though? I don't know how common users ssh-ing into the master is, so it might not matter, but if we added a new feature it won't work through 1.3.6 obviously. I use the heck out of kubectl on master to debug other people's clusters, but I guess we can just doc the alias.

**Comment by Amey-D** [comment]
+1 to documenting the alias.  In PR #31367 we decoupled the running versions of kubelet and kubectl from the versions in /usr/bin/kubelet and /usr/bin/kubectl on GCI, so this is WAI.

**Comment by bprashanth** [comment]
alright we'll just include something in https://github.com/kubernetes/kubernetes/issues/32332 and probably some other sources

**Comment by davidopp** [comment]
Is there some way to make the proper kubectl show up in the path? This seems like a pretty decent usability issue. People generally don't read documentation, much less release notes...

**Comment by Amey-D** [comment]
We can append the the location of correct kubectl version to $PATH /etc/profile as part of configure scripts so that it shows up in users' PATH upon log in.  I'll send a PR unless someone else wants to do it.

**Comment by vishh** [comment]
Ping @Amey-D

**Comment by roberthbailey** [comment]
@Amey-D - are we still planning on fixing this?

**Comment by Amey-D** [comment]
Sorry this fell off radar.  I won't have cycles to work on this in the next few days.  Happy to help with code reviews though.

**Comment by mikedanese** [comment]
This should be a COOS bug.
