### ISSUE TITLE
Setup minimum reclaim for disk and inodes availability in GCE

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#32537]
Clusters on GCE set eviction thresholds for disk and inodes. Given that reclaiming disk and inodes is slow, we should set minimum reclaim thresholds too. 
Essentially, set `--eviction-minimum-reclaim=nodefs.available=5%,nodefs.inodesFree=5%`.

@derekwaynecarr I assume percentages are supported for min reclaims too. 

Do we have system tests for min reclaim?

cc @dchen1107

**Comment by mtaufen** [comment]
I just took a glance at the parser for eviction minimum reclaim, it doesn't look like it tries to parse percentages. @derekwaynecarr can you confirm?

**Comment by derekwaynecarr** [comment]
@ronnielai did percentage support, and we did not extend it to min
reclaim.  It's a good idea to do though.

**Comment by vishh** [comment]
Hmm.. In that case for v1.4, can we set the min reclaim to `--eviction-minimum-reclaim=nodefs.available=5%,nodefs.inodesFree=2000`? What values are you planning on using in Open Shift @derekwaynecarr ?

**Comment by dchen1107** [comment]
This should fix this issue to avoid node condition being flip-flop, but I think it shouldn't block 1.4 release.

**Comment by vishh** [comment]
More than flip-flop, it will help the node recover from disk pressure
condition sooner.

**Comment by derekwaynecarr** [comment]
Spawned https://github.com/kubernetes/kubernetes/issues/33354 to add percentage support for min reclaim.

I will follow up with our proposed default for nodefs later

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @derekwaynecarr @vishh

**Comment by vishh** [comment]
@dashpole can you check if we have set default values for disk and inode based evictions in kubelet? If not, we should add them.

**Comment by dashpole** [comment]
I believe our current default value for the --eviction-hard flag is "memory.available<100Mi", found in pkg/apis/componentconfig/v1alpha1/defaults.go.
Our tests currently run using: "memory.available<250Mi,nodefs.available<10%,nodefs.inodesFree<5%", found in test/e2e/framework/test_context.go.

What should I change the default to?  This issue is about minimum reclaim, should I look into changing those flags as well?

**Comment by dashpole** [comment]
It doesn't appear that we have defaults for minimum reclaim, should I add minimum reclaim for memory in addition to the values listed at first?

**Comment by derekwaynecarr** [comment]
I think GCE defaults do not apply globally, we should change what GCE does, and handle setting global defaults in 1.6.

**Comment by vishh** [comment]
@derekwaynecarr the global defaults are expected to be based on our OSS tests. Our original plan was to roll out disk eviction by default in v1.5. This is not specific to GCE.

**Comment by saad-ali** [comment]
@derekwaynecarr @vishh @derekwaynecarr Can you make a call on if this is a blocker or non-blocker for 1.5 by EOD Friday please
