### ISSUE TITLE
kubectl path based resource selection should support filtering with label selector

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#32544]
Right now it is not supported:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource/builder.go#L546-L552

**Comment by taimir** [comment]
I'd be glad to pick it up if there's no one working on it.

**Comment by taimir** [comment]
nvm, I see you've dealt with it [here](https://github.com/kubernetes/kubernetes/pull/32599/files)

**Comment by mikedanese** [comment]
This is p1 as it blocks addon-manager work we need in 1.5

**Comment by bgrant0607** [comment]
It sounds like this hasn't been completed for all commands that support --filename.

**Comment by gluke77** [comment]
@mikedanese Do you plan to get back to it? If not, I'd like to pick it up.

**Comment by mikedanese** [comment]
Yes please. Go for it.

**Comment by gluke77** [comment]
Thanks, so I start working.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @mikedanese @gluke77

**Comment by mikedanese** [comment]
We did what we needed to do for v1.5.

**Comment by dims** [comment]
great thanks @mikedanese
