### ISSUE TITLE
New Flex volume API proposal

### ISSUE THREAD

**Issue by chakri-nelluri** [kubernetes/kubernetes#32543]
#33538 has the pull request for the proposal.
# Flex Volume API Proposal
## Abstract

The goal of this proposal is to extend and enhance the existing flex volume storage plugin model (#13840). It bridges the gap with existing in-tree plugins and defines a stable api.
## Background:

Existing flex volume plugin enables administrators/vendors to create out-of-tree volume plugins, i.e., plugins which do not reside in Kubernetes project. But, it has the following gaps.
- It lacks support for the latest enhancements to in-tree plugins like dynamic provisioning and centralized attach-detach controller
- It does not define a stable driver api for administrators/vendors to work.
- The current flex volume plugin deployment model is not suitable for environments like GCE & CoreOS, where access to the root file system is restricted. And in other environments the overall user experience is poor, as it requires manual installation of the plugin on every node and restart of kubelets & controller manager. This issue is covered in detail in another PR.
### Goals:

The goals of this proposal are 
- Define new stable driver API.
- Add support for dynamic provisioning and centralized attach-detach controller and
- The biggest advantage of flex volume is it’s simplicity. It is just an adapter around the internal api. We will keep it simple in the new design and try to follow the same adapter pattern.
### Non Goals:
- This proposal does not the address the poor installation model of existing model. It is covered in another PR.
- This proposal uses the existing ‘exec’ plugin model. A rest callout model will be covered in another PR.
## Terminology:

**Plugin**: refers to flex volume plugin.
**Plugin Driver api**: API calls defined by flex volume plugin.
**Plugin Driver**: Out-of-tree driver/plugin which implements plugin driver api.
**In-tree plugin**: Plugins which are included in Kubernetes project/source tree.
## API:

Existing flex volume plugin driver api are in alpha phase and are subject to change between kubernetes versions. This section proposes stable api for plugin driver writers to work with.
### Proposal 1:

Expose the existing in-tree plugin API as driver API. For more details on existing in-tree plugin API please refer to https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/volume.go
###### Pros:
- In-tree plugins are already using these API.
- Simple and clean interface.
###### Cons:
- No standard request & response API objects.
- No versioning support.
- Does not follow REST model.
- Many call outs. For full support, a plugin has to implement 17 APIs.

This was discussed in the storage-sig face to face and in lieu the following is proposed.
### Proposal 2:

Proposes fewer APIs with stable request & response API objects.
###### Pros:
- Has standard request & response API objects.
- Supports versioning.
- Follows REST model.
- Fewer calls.
- Simple and clean interface.
###### Cons:
- New API objects.
#### Probe Plugin:

This call probes the plugin for it’s capabilities and supported options. Supported options are used to validate and reject pod spec. This is executed from both the Controller-manager and Kubelet.
###### New API Types:

``` go
type FlexVolumeDriverCapabilities struct {
    ReadWrite api.PersistentVolumeAccessMode
    DynamicProvisioning bool
    Attachment bool        // Do we need separate capability for remote & local attachments support? Some drivers like ISCSI do not support attachment from remote node (controller manager).
    SELinux bool
    OwnershipManagement bool
    Metrics bool
}

type FlexVolumeDriverSpec struct {
    Name string     // name of the driver. Ex: ganesh-nfs
    Driver string   // Actual driver path. Ex: ganesha/nfs
}
type FlexVolumeDriver struct {
    unversioned.TypeMeta
    v1.ObjectMeta
    Spec FlexVolumeDriverSpec
    Capabilities FlexVolumeDriverCapabilities
    SupportedOptions []string // Driver options supported.
}
```
###### Request:

```
nil
```
###### Response:

On success:

```
FlexVolumeDriver
```

On failure:

```
non-zero exit code & errors.StatusError
```
###### Call out:

```
<driver executable> probe
```
#### Provision/Create a volume:

This call creates a volume. It is executed from Controller-manager.
###### New API Types:

``` go
Type FlexVolumeStatus string

type FlexVolume struct {
    unversioned.TypeMeta
    v1.ObjectMeta
    Spec api.FlexVolumeSource
    Status FlexVolumeStatus
}
```
###### Request:

```
FlexVolume
```
###### Response:

On success:

```
api.FlexVolume
```

On failure:

```
non-zero exit code & errors.StatusError
```
###### Call out:

```
<driver executable> create <json encoded api.FlexVolume>
```
#### Delete a volume:

This call deletes a volume. It is executed from Controller-manager.
###### Request:

```
FlexVolume
```
###### Response:

On success:

```
0 exit code
```

On failure:

```
non-zero exit code & errors.StatusError
```
###### Call out:

```
<driver executable> delete <json encoded api.FlexVolume>
```
#### Attach a volume:

This call attaches a volume to a remote host or local host. It can be executed from Controller-manager/Kubelet depending on whether Controller-attach-detach is enabled or not.. This is only valid for drivers which support attach & detach.

The following additional options are passed to the plugin as part of options map in FlexVolumeSource.

```
“kubernetes.io/host”=”<host-name>”
“kubernetes.io/mountpath”=”<mount path>”
```
###### New API Types:

``` go
type FlexVolumeAttachment struct {
    unversioned.TypeMeta
    v1.ObjectMeta
    Host string
    Device string
    MountPath string
}
```
###### Request:

```
FlexVolume
```
###### Response:

On success:

```
FlexVolumeAttachment
```

On failure:

```
non-zero exit code & errors.StatusError
```
###### Call out:

```
<driver executable> attach <json encoded FlexVolume>
```
###### Call out sync: (Wait for attach):

```
<driver executable> attach <json encoded FlexVolume> sync
```
#### Detach a volume:

This call detaches a volume to a remote host or local host. It can be executed from Controller-manager/Kubelet depending on whether Controller-attach-detach is enabled or not.. This call only valid for drivers which support attach & detach.

The following additional options are passed to the plugin as part of options map in FlexVolumeSource.

```
“kubernetes.io/host”=”<host-name>”
```
###### Request:

```
FlexVolumeAttachment
```
###### Response:

On success:

```
0 exit code
```

On failure:

```
non-zero exit code & errors.StatusError
```
###### Call out:

```
<driver executable> detach <json encoded FlexVolumeAttachment>
```
###### Call out sync: (Wait for detach)

```
<driver executable> detach <json encoded FlexVolumeAttachment> sync
```
#### Mount a volume:

This call mounts a volume on the node. It is executed from Kubelet. This is only valid for plugins which do not support attach/detach to a node. Example: NFS/CIFS. For volumes which support attach/detach, this will use the default logic to bind mount.

The following additional options are passed to the plugin as part of options map in FlexVolumeSource.

```
“kubernetes.io/mountpath”=”<mount path>”
```
###### New API Types:

```
type FlexVolumeMount struct {
    unversioned.TypeMeta
    v1.ObjectMeta
    MountPath string
}
```
###### Request:

```
FlexVolume
```
###### Response:

On success:

```
FlexVolumeMount
```

On failure:

```
non-zero exit code & errors.StatusError
```
###### Call out:

```
<driver executable> mount <json encoded FlexVolume>
```
#### Unmount a volume:

This call unmounts a volume on the node. It is executed from Kubelet. This is only valid for plugins which do not support attach/detach to a node. Example: NFS/CIFS.
###### Request:

```
FlexVolumeMount
```
###### Response:

On success:

```
0 exit code
```

On failure:

```
non-zero exit code & errors.StatusError
```
###### Call out:

```
<driver executable> unmount <json encoded FlexVolumeMount>
```
#### Metrics call

This call gets the metrics of a volume. It is executed from Kubelet.
###### New API Types:

```
type FlexVolumeMetrics struct {
    unversioned.TypeMeta
    v1.ObjectMeta
    Capacity *resource.Quantity
    Used *resource.Quantity
    Available *resource.Quantity
}
```
###### Request:

```
string
```
###### Response:

On success:

```
FlexVolumeMetrics
```

On failure:

```
non-zero exit code & errors.StatusError
```
###### Call out:

```
<driver executable> metrics <json encoded FlexVolumeMount>
```
## Dynamic Provisioning support:

The new driver probe function has support to query the capabilities and if the driver has of ‘dynamic provisioning’ capability, Flex volume plugin will support dynamic provisioning by implementing the ‘Provisioner’ and ‘Deleter’ interfaces.
## Attach detach support:

The new driver probe function has support to query the capabilities and if the driver has of ‘attachment’ capability, Flex volume plugin will support dynamic provisioning by implementing the ‘Provisioner’ and ‘Deleter’ interfaces.
PR by @MikaelCluseau (#26926) would be leveraged for this change.

**Comment by chakri-nelluri** [comment]
@thockin @saad-ali @rootfs @MikaelCluseau @barakmich @wattsteve @childsb  @gr4701
Please review.

**Comment by MikaelCluseau** [comment]
On 09/13/2016 12:35 PM, Chakravarthy Nelluri wrote:
> type  FlexVolumeDriverCapabilities  struct  {
>      ReadWrite  api.PersistentVolumeAccessMode
I would have called the property "AccessMode" instead.

**Comment by rootfs** [comment]
For volumes that are able to manage credentials and endpoints without looking up them up, the proposed APIs should work.

For volumes that want to access or create secret, endpoint, or service, it is unclear how the proposed API can support them.

**Comment by chakri-nelluri** [comment]
@rootfs. Thanks for the feedback. The secrets are part of FlexVolumeSource. If we have a good use case for endpoint or service information, we can standardize it or the user can pass it as an option.

**Comment by rootfs** [comment]
One thing we are working on now is to refactor glusterfs's endpoint (and its service) handling 
@humblec

**Comment by taherv** [comment]
Am I misreading here ?

The proposal says requests to flexvolume drivers will use REST, but then the callouts are "driver executable> <params>"

For REST based flexvolume drivers, shouldnt the call out be a GET/PUT/POST etc ?

Also, there are some typos ... e.g. Detach description talks about attach.

**Comment by taherv** [comment]
Just like "Delete a volume", are we missing a "Recycle a volume" API ?

Also, how does a flexvolume driver express (in Probe) that it supports deleter and/or recycler ?
Is this in the SupportedOptions field ? If not, are we missing two bools in FlexVolumeDriverCapabilities type ?

**Comment by taherv** [comment]
Why is the actual driver binary required in the FlexVolumeDriverSpec ?
If API calls are REST, shouldn't that be a REST endpoint ?

**Comment by chakri-nelluri** [comment]
@taherv this defines the REST semantic API types and the callouts are still based on exec model. HTTP based interface will be in another subsequent proposal.

**Comment by chakri-nelluri** [comment]
Thanks @taherv I fixed the typos.

**Comment by MikaelCluseau** [comment]
+1 to complete Attachment with another flag like `LocalAttachment`
I'm for limiting the call to one, well-defined object, and avoid as much a possible to use the options map, which I think shoudl be reserved for driver's "blackbox" data.

**Comment by MikaelCluseau** [comment]
Driver caps structure as a consequence:
```go
type FlexVolumeDriverCapabilities struct {
	AccessMode          api.PersistentVolumeAccessMode
	DynamicProvisioning bool
	Attachment          bool
	LocalAttachment     bool // When Attachement is true, issue the attach/detach calls from the target host, not the controller.
	SELinux             bool
	OwnershipManagement bool
	Metrics             bool
}
```

**Comment by MikaelCluseau** [comment]
I'm not sure we need ObjectMeta and TypeMeta in the results from the calls.

**Comment by MikaelCluseau** [comment]
I'm for using FlexVolumeMount as a parameter for "metrics".

**Comment by taherv** [comment]
@MikaelCluseau The LocalAttachment field has some consequences, I wonder what your opinion is regarding them.
1. This means each driver can choose independently if they want LocalAttachment (or not)
2. Has an impact on the enable-controller-attach-detach command line parameter to kubelet.
    (That flag as long as I understand is for that node, and is not driver specific).
3. Even if we decide to dump that flag, and let the LocalAttachment flag decide the attachment mode, 
    what happens to non-flexvolume drivers.

**Comment by MikaelCluseau** [comment]
@taherv 
1. Yes
2. It looks weird to have it at a wider level than the driver; we may which a Ceph RBD volume and GCE volume on the same host for instance.
3. They should specify how they, this allow to factorize more complex code like RPC mecanisms in Kubernetes itself, providing more service to the drivers, thus helping implementors.

**Comment by taherv** [comment]
We agree on 1. I dont think we can remove the flag for 2 so easily, we still need to support existing non-flexvolume drivers.

I am confused about what you want to say in (3). Please explain (3).

**Comment by MikaelCluseau** [comment]
On 2, we can of course keep the flag for now. Then, on 3, other drivers may or may not move, but I'd be for a generic support in Kubernetes, so the complexity is done once for all.

**Comment by taherv** [comment]
For (2), if we are keeping the flag, what is the expectation when that flag is specified, but the driver specifies LocalAttachment is true ? Obviously, one of them should win :) I think it should be the driver (since that flag will be deprecated soon, it can be overridden by flexvolume drivers written using this new proposal) ?
@chakri-nelluri We should get somebody who works in kubelet code to okay this .....

**Comment by MikaelCluseau** [comment]
(2) I think LocalAttachment should win; the flag is for core drivers :) We may give it as an hint in the probe call, but that looks unclean and overkill to me. So we agree.

**Comment by chakri-nelluri** [comment]
@taherv The driver flag should win in the long term. @rootfs and @saad-ali are the right persons to comment if we need to use Kubelet flag for the short term. If not, we will use the driver flag for the short term too.

**Comment by rootfs** [comment]
@taherv @MikaelCluseau there are indeed some cases we should take a deep look. If the driver doesn't support remote attach but kubelet and controller master are enabled to attach volume remotely, we should see if the driver can reject the call from controller and let kubelet attach the volume.

**Comment by taherv** [comment]
@rootfs It might not be possible for a driver to be used in whatever mode is available. It depends on how the storage device behaves/works. For example, a driver written for controller attach will probably not have storage credentials being sent to the node. So just asking the driver to do a kubelet attach instead of controller attach will not work, unless the driver itself is written to be multimodal.

I think the kubelet flag for attach/detach was fine for a start, but it is too coarse now. In a k8s cluster where multiple volume drivers are present, this decision should be made on a per driver basis. The Probe API is a step in that direction, we should eventually phase out the global flag (and the kubelet attach/detach commandline parameter). Do you agree ? If not, your opinions please ?

**Comment by thockin** [comment]
> New API Types:

It's unclear: are these types in the main kubernetes API or some new API that is *just* flex drivers?

Calling it REST is confusing - this is just structured input and output.  It might be simpler to digest if you just called it that?  REST implies resources which act like nouns and have different verbs.  This is closer to JSON RPC.

**Comment by chakri-nelluri** [comment]
Thanks @thockin 

These API are just for Flex drivers. What would be the best place for the external interfaces like this?

The API types are REST objects/resources. Attach & Detach verbs are used in callouts in exec model, similar to how we do "kubectl scale --replicas..." for replication controller.

The plan is to use the same API objects for HTTP interface. The attach & detach will change to POST/PUT on corresponding URL.

**Comment by chakri-nelluri** [comment]
Talked to Tim. We want to give it a shot to bring it closer to Docker API. I will update the proposal.

**Comment by rootfs** [comment]
@taherv the credential issue is being addressed in #33660

**Comment by rbtcollins** [comment]
@chakri-nelluri w.r.t. secrets - can I confirm that the following use case is one that this proposal would support?:

We want to supply unique TLS certificates to every pod in a Deployment. We are investigating using volumeClaimTemplates to dynamically provision secret volumes, one per pod. The provisioner would need the pod dns name to set the CN in the certificate, and would create a certificate, then load that into a secret object - we'd want to return a reference to the secret object, so the volume mount on the minion would follow the normal secret behaviours.

**Comment by chakri-nelluri** [comment]
@rbtcollions we cannot support this use case.
Provisioner creates volumes when a claim is created & bound. There is no pod at that point of time. We cannot pass the pod DNS name to the provisioner.

**Comment by rbtcollins** [comment]
@chakri-nelluri ah - thats a shame. Is that the only limit? e.g. another way we could do it is to place a unique token in the secret, and use that to exchange for a certificate - only that pod would know the token, and the certificate service could introspect the pod to see the claim metadata.

**Comment by chakri-nelluri** [comment]
@rbtcollins AFAIK we do not have a way to pass the pod specific or per-volume specific parameters to dynamic provisioning infra (it has nothing to do with flex volume). The only way is to manually create persistent volumes with pod specific parameters, every time you want one.

Between, you will not be able to return secret objects, provisioner only handles persistent volumes. You can still have your own custom logic to populate the secrets during the plugin mount call using flex volume.

**Comment by MikaelCluseau** [comment]
@rbtcollins I agree with @chakri-nelluri, the right place seems to be the mount call for a flexvolume. But I think it would be much simpler to have a container creating it in a emptyDir volume.

**Comment by rbtcollins** [comment]
@MikaelCluseau perhaps I should open a new issue, to avoid taking this one sideways?

I'm obviously missing something - how do I make sure I've only handed out the cert to the desired pod if the pod is just using an emptyDir volume itself? Presumably the pod is then asking the CA for the cert directly - but it has nothing with which it can proove its identity except its IP address - and if we're assuming the network is unspoofable we are perhaps not needing TLS in the first place :).

@chakri-nelluri  So, ok - we make a trivially empty secret object [ or perhaps your note about only handling pv's means we don't create a secret object at all, but just some placeholder pv - I guess we need a new pv type ?] upon request in the provisioning call, and then in the mount call we call out to our CA, as at that point we know the pod identity, and our agents callout would use credentials stored in the node itself - presumably we can drop them on disk as a salt pillar or some such.

**Comment by MikaelCluseau** [comment]
@rbtcollins for now, the discussion volume on this is ok I think, and if we get a conclusion it may help API design; but if it begins to be long debate then yes, I'm in favor of another issue. For the initialization pod auth, I was thinking of the service account (http://kubernetes.io/docs/user-guide/accessing-the-cluster/#accessing-the-api-from-a-pod): that should allow you to rely on the existing kubernetes PKI and access a Secret object (or whatever else).

**Comment by chakri-nelluri** [comment]
Update: Docker API is very minimalistic as of today. We were interested in extending the API to have an uniform interface between Docker & Kubernetes. Talking to Docker, learnt that the existing volume plugins approach of centralized controller (and remote attach/detach calls) might not be a fit for Docker & Swarm architecture. 

Given that and the slew of new features we have in pipeline(ex: snapshots, local storage) and the new API extensions we might have to add to support them, we decided to implement our own API model. 

Working on the review comments on the existing proposal. Will update the proposal ASAP.

**Comment by chakri-nelluri** [comment]
@rbtcollins IIUC that sounds doable :). If you need credentials to talk to your CA, you can use Kubernetes secrets for it. Flex volume will pass the secret in the call outs.

**Comment by chakri-nelluri** [comment]
Updated the proposal in PR #33538

**Comment by rbtcollins** [comment]
@MikaelCluseau are service accounts templated in Deployments? Seems like every pod gets the same service account - default ? We'd be trusting no-one else manages to spawn pods in the same namespace AIUI - and I'm not saying thats a problem, just trying to make sure I have a clear understanding of the trust boundaries we're going to be establishing.

**Comment by MikaelCluseau** [comment]
@rbtcollins Yes, the trust boundaries are at the namespace level here. If you want it at the pod level,  the flexvolume approach would be ok (use the mount call that know the target pod). IIUC, in your case, it seems that the pods must not to access the API anyway because you have a very low level of trust in them. If they can't access the API, they won't be able to read the secrets in their namespace. In this case, I think you're more willing to create a "secret provisionner" than a full flexvolume plugin; it would be simpler to design and maintain, and will be a single pod in the cluster whereas a flexvolume plugin would require a daemon set (1 pod per host).

**Comment by chakri-nelluri** [comment]
@thockin @brendandburns @rootfs PTAL and let me know your feedback. I have changed the API to gRPC API.

**Comment by pires** [comment]
What's the status of this proposal?

**Comment by chakri-nelluri** [comment]
@pires  this is getting superseded by CSI.
