### ISSUE TITLE
BUG- Unable to deploy AWS cluster with elasticsearch logging enabled

### ISSUE THREAD

**Issue by aliakhtar** [kubernetes/kubernetes#32546]
I'm trying to deploy a cluster on AWS using `kube-up.sh` but with elasticsearch / kibana logging enabled.

Following the instructions at http://kubernetes.io/docs/getting-started-guides/logging-elasticsearch/ I put the following lines:

```
export KUBE_LOGGING_DESTINATION=elasticsearch
export KUBE_ENABLE_NODE_LOGGING=true
```

in `kubernetes/cluster/aws/config-default.sh`. However when I made the cluster using `kube-up.sh`, I didn't see any notifications like 

> +++ Logging using Fluentd to elasticsearch

And when I visit `https://50.xx.xx.xx/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging/_search`, I see this output:

```
{"took":1,"timed_out":false,"_shards":{"total":0,"successful":0,"failed":0},"hits":{"total":0,"max_score":0.0,"hits":[]}}
```

Its returning 0 results even though I have run deployments which produced logs, and `kubectl logs <pod-name>` displays the logs.

 Likewise in Kibana if I select time series and use `@timestamp`, it doesn't find any matches.

I've tried running 

```
export KUBE_LOGGING_DESTINATION=elasticsearch
export KUBE_ENABLE_NODE_LOGGING=true
```

directly from the terminal right before calling `kube-up.sh`, but the results have been the same.

The weird thing is that `kubectl get pods --namespace=kube-system` does show pods running `fluentd-elasticsearch` for each of the nodes.

How do I get elasticsearch logging on AWS?

**Comment by chicagozer** [comment]
what minion type did you choose? I had the same issue with r3.large when I switched from t2.large; had to throw in 

export KUBE_AWS_STORAGE=ebs

**Comment by crassirostris** [comment]
We don't have e2e tests for aws to test fluentd-elasticsearch deployment, so it's possible it's broken

If someone's still interested in debugging this, I'm ready to help. The first thing I'll need is fluentd logs from the affected nodes
