### ISSUE TITLE
Improved lifecycle proposal for Flex volume plugin driver

### ISSUE THREAD

**Issue by chakri-nelluri** [kubernetes/kubernetes#32550]
#32539 has the pull request for the proposal.
### Objective

The goal of this proposal is to define a simplified flex volume plugin driver installation model.
Existing plugin driver installation model has the following drawbacks.
- It requires manual installation on every node and restart of kubelet on every node & controller-manager on the master node.
- It is not supported in GCE & CoreOS environments where access to master node or root filesystem is restricted. Access to master node is required to install the plugin for controller-manager to provision, delete, attach & detach calls.
- Manual and controlled upgrade on every node and requires downtime.
## New proposal:
- Build a container image with support for one or more plugin drivers.
- Run the container as a daemon-set with the label `“flexvolumedriver-provider.kubernetes.io/name”: “<provider name>”`
- Define new flexvolume driver with the selector `“flexvolumedriver-provider.kubernetes.io/name”:”<provider-name>”`. This should match the label in the above daemon-set.
- Kubelet & Controller manager will watch for new flexvolume driver objects and initialize them.
- Now all the flex volume driver calls will be executed inside the container of the matching daemon set.
- Handling conflicts: If more than one daemon-set matches the same label, the first available daemon-set will be used.

Please refer to proposal (#32543) for FlexVolumeDriver API type. This proposal requires kubelet and controller-manager support to watch for new FlexVolumeDriver API types and initialize them.

This model fixes the shortcomings in existing installation model. Installation of drivers is no longer manual and does not require restart of any Kubernetes modules. Works in all deployment model, like GCE & CoreOS. Upgrade is as simple as upgrading a daemon-set

Inside the container image, drivers are expected to be installed at `/plugins/<provider~driver>/<driver>`.  As long as the `provider~driver` is unique, multiple drivers can be packaged in a single container image. This follows the existing model, expect that the drivers are now inside a container image in`/plugins`.

**Comment by chakri-nelluri** [comment]
@thockin @saad-ali @MikaelCluseau @rootfs @wattsteve @pmorie @childsb @gr4701
Please review.

**Comment by chakri-nelluri** [comment]
@barakmich Please review.

**Comment by jsafrane** [comment]
I would argue that upgrading is that simple. E.g. gluster runs a fuse daemon that would need to run inside a container. On upgrade, you need to kill the daemon and start a new one, which will unmount all gluster volumes under running pods. Cephfs may be the same story (not tested though).

With current manual upgrade, sysadmins can drain the node first and update gluster binaries when all pods are evicted.

IMO, there is a difference between unmounting a fs from under a pod (which will likely crash on next read/write) and deleting the pod "gracefuly" - the pod has some chance to flush caches and logs and close it its files.

**Comment by rootfs** [comment]
+1 Container mount using DaemonSet. An early experiment can be found at https://github.com/kubernetes/kubernetes/compare/master...rootfs:ds-mounter?expand=1

**Comment by chakri-nelluri** [comment]
Thanks Jan for the feedback.

I am not looking at this daemon-set model to be a one fit for all solution. It solves the existing problem of distributing the client side of drivers, like simple binaries etc.

But you are spot -on, more complex cases, which have server component like glusterfs+fuse, the simple daemon-set upgrade model won't work. Admin can choose to run two versions (say v1, v2) of glusterfs side-by-side, instead of upgrading v1 to v2. This is a very good point and I want it captured. I will update the proposal with this point.

I will keep it simple in the initial proposal and we can refine it going forward to solve other complex use-cases. I don't think it will be too much of a compromise, but would like to hear from you too. Let me know.

**Comment by thockin** [comment]
> Run the container as a daemon-set

What does it do?  Just sleep to keep the container running?

> Define new flexvolume driver

Are you proposing a new API object Kind?  That wasn't clear from the other proposal.  The bar for adding a new Kind is very high.

> Kubelet & Controller manager will watch for new flexvolume driver objects and initialize them.

What does "initialize" mean?

>  If more than one daemon-set matches the same label, the first available daemon-set will be used.

Kubelet doesn't know about daemon sets, it only knows pods.  What does "first" mean when pods can be stopped and started?

**Comment by thockin** [comment]
If we're going to end up with a long-lived container on every node, why both with complicated exec semantics - we should just adopt a model like Docker's drivers.  A JSON-RPC-ish API to a running container.  No installation concerns - we don't care how it got there to what it is.  All we know is that it exists.

**Comment by thockin** [comment]
Also, we still don't have (AFAICT) an answer to hosted environments like GKE, where you don't have access to the master.  How can provisioning, attaching, etc be handled?  That should be answered as part of the overall flex solution set.

**Comment by chakri-nelluri** [comment]
Thank you @thockin. I will update the proposal that we need a new API type for adding a driver :). Hopefully I can make the case for the driver API type or at least for a generic driver/plugin API type which can be used in other places too.

| | Run the container as a daemon-set
| What does it do? Just sleep to keep the container running?
 [chakri] Yes. It will be just be a sleep container. 

| | Define new flexvolume driver
| Are you proposing a new API object Kind? That wasn't clear from the other proposal. The bar for adding a new Kind is very high.
[chakri] - Will update the proposal to make it explicit

| | Kubelet & Controller manager will watch for new flexvolume driver objects and initialize them.
| What does "initialize" mean?
[chakri] - Initialization will just probe the driver and update the capabilities. Will update the proposal to make it clear. Just realized I missed the status in driver type. Will fix it.

| | If more than one daemon-set matches the same label, the first available daemon-set will be used.
| Kubelet doesn't know about daemon sets, it only knows pods. What does "first" mean when pods can be stopped and started
[chakri] - It will be the available pod matching the label. I will update the proposal. I will give it at try  to see if we will have any race conditions during pod restarts.

The current idea is to use a daemon-set which includes all the well known drivers. I wanted to follow the docker model, but I am not able to convince myself that we need to run a separate daemon set for every driver. I am still churning that idea, but could not figure out a way to overcome it.

For environments like GKE.. would we not be able to run daemon-sets on the master nodes? I didn't know that. Then this model wouldn't work. I will dig a bit further and get back.

**Comment by thockin** [comment]
For things like GKE, I'm thinking we need to find some way for the master
to find the "master driver" via a kube service, rather than assuming
localhost.  Much more complex.  Phase 2.

**Comment by chakri-nelluri** [comment]
Updated the proposal in PR #33539. PTAL.

**Comment by chakri-nelluri** [comment]
@thockin @brendandburns @rootfs PTAL.

**Comment by owenhaynes** [comment]
Will this support more then just the cephfs fuse driver? E.g the cephfs kernel driver which is a bit faster.
