### ISSUE TITLE
Godeps check Bash version

### ISSUE THREAD

**Issue by johscheuer** [kubernetes/kubernetes#32564]
**Is this a request for help?** 
No

**What keywords did you search in Kubernetes issues before filing this one?**
Godeps, declare, bash

---

**Is this a BUG REPORT or FEATURE REQUEST?**
BUG REPORT:
In https://github.com/kubernetes/kubernetes/blob/master/hack/update-godep-licenses.sh#L122 the command `declare -Ag ..` is used `declare -A` is only available in Bash 4+ maybe we should add an check for the bash version and if the bash version < 4 we should output an error saying `update your bash`. I ran into this problem because on OSX u have per default Bash `3.2.57`

**Environment**:
- **OS** (e.g. from /etc/os-release):
OSX
- **Kernel** (e.g. `uname -a`):
Darwin ...local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64

**What happened**:
The update/Verify failed with: `line 122: declare: -A: invalid option`

**What you expected to happen**:
Get an error message like `update your bash` or `bash version incompatible with script`

**How to reproduce it** (as minimally and precisely as possible):
Run `./hack/update-godep-licenses.sh` again

**Comment by johscheuer** [comment]
To get the script running you need to do the following steps on OSX:

```
brew install md5sha1sum bash jq
```

I couldn't find any documentation for this, so maybe we should add this to place `xx`? I think here: would a good place https://github.com/kubernetes/kubernetes/blob/master/docs/devel/godep.md

**Comment by janetkuo** [comment]
cc @david-mcmahon @eparis @thockin

**Comment by thockin** [comment]
I would love to not depend on such esoteric bash-isms.

**Comment by pwittrock** [comment]
@ixdy Is this eng-prod?

**Comment by eparis** [comment]
-A support have been in bash at least 4 years! Mind you, I know other places we've worked pretty hard to support the bash version in OS X. I think @david-mcmahon wrote this, maybe he can work out how hard it is to remove -A....

**Comment by johscheuer** [comment]
I think there is no need to rewrite this (I actually don't know how hard it would be) but a slightly better error message or maybe a sanity check would be nice to know if the used bash version is >= 4.

**Comment by ixdy** [comment]
I'll review a PR if someone wants to add a bash version check, but I don't have time to implement this right now.

**Comment by david-mcmahon** [comment]
> -A support has been in bash at least 4 years!
Feb 2009.  OSX is due for an update.

I'll happily write a version check.
