### ISSUE TITLE
TerminatingReplicas status field for replica sets

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#32567]
Recreate Deployments require that we always run at most one instance of user pods at a time. Currently, we can get into a situation, due to volume attach/detach, where old pods are stuck in Terminating phase (pod.DeletionTimestamp != nil) while the deployment controller is trying to scale up new pods because it thinks old pods are gone. The replica set controller currently filters out Terminating pods and includes only active pods in the replica set status. I am proposing a new rs.Status.TerminatingReplicas that will show all the terminating pods for a replica set. Then the deployment controller can wait until all status fields for a replica set including TerminatingReplicas are down to zero before it starts scaling up.

cc: @kubernetes/api-review-team @kubernetes/sig-apps @kubernetes/deployment

**Comment by AdoHe** [comment]
```
Recreate Deployments require that we always run at most one instance of user pods at a time. 
```
so the situation break this rule?

**Comment by soltysh** [comment]
> I am proposing a new rs.Status.TerminatingReplicas that will show all the terminating pods for a replica set

What for? We're only showing active, because those are the ones user cares about and that's how the controller treats them.

**Comment by kargakis** [comment]
> What for? We're only showing active, because those are the ones user cares about and that's how the controller treats them.

Is there any previous discussion on this matter that you can link here? I have been wondering why we try so hard to hide terminating pods from users. I am not against the goal but in reality there are times they (users) are blocked by them (terminating pods not terminating).

**Comment by soltysh** [comment]
I can't recall any discussion. But if you have a look at our controllers, as you've mentioned, they just count the active pods, ignoring everything else. That seems perfectly valid argument for me. I wonder if the GC will pick such "terminating pods not terminating" (@caesarxuchao might know that) or eventually should we provide users with a tool to force kill those. Although the latter should be possible already, the only problem this being quite manual process.

**Comment by caesarxuchao** [comment]
There is a podgc, which will take care of "terminating pods not terminating". See its doc: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podgc/doc.go

**Comment by smarterclayton** [comment]
Technically even this would not be enough to guarantee we are only running
one instance of a user's pods at a time (due to node controller or drain
deleting pods) so we should be careful if we think we *must* solve "only
one version at a time".  ReplicaSets are philosophically structured for
where you *may* have to deal with the implication of two versions at once.

That said, I think waiting for all pods to terminate (not just go into
terminating) is strictly correct for Recreate.

**Comment by kargakis** [comment]
@soltysh @caesarxuchao the thing that will take care of cleaning up terminating pods, be it the kubelet, or the gc, or X, doesn't matter in this case. I want the API to let me know when {kubelet, gc, X} did its job and cleaned up all terminating pods for a given controller.

**Comment by kargakis** [comment]
Btw, https://github.com/kubernetes/kubernetes/issues/32682 ...

**Comment by kargakis** [comment]
Recreate on master
```
nginx-4262182780-1n8qx   0/1       ContainerCreating   0          12s
nginx-4262182780-hfev8   0/1       ContainerCreating   0          12s
nginx-4262182780-kvv32   0/1       ContainerCreating   0          12s
nginx-4262182780-lcasb   0/1       ContainerCreating   0          12s
nginx-4262182780-msbpe   0/1       ContainerCreating   0          12s
nginx-4262182780-opmas   0/1       ContainerCreating   0          12s
nginx-4262182780-qphvl   0/1       ContainerCreating   0          12s
nginx-4262182780-qvxhm   0/1       ContainerCreating   0          12s
nginx-4262182780-ukb89   0/1       ContainerCreating   0          12s
nginx-4262182780-yipz2   0/1       ContainerCreating   0          12s
nginx-618515232-308yp    1/1       Terminating         0          1m
nginx-618515232-4gj95    1/1       Terminating         0          1m
nginx-618515232-anr0f    1/1       Terminating         0          27s
nginx-618515232-ih2wl    1/1       Terminating         0          27s
nginx-618515232-rmf6q    1/1       Terminating         0          27s
nginx-618515232-u2zwn    1/1       Terminating         0          1m
```

**Comment by kargakis** [comment]
Recreate on master
```
$ kc get rs
NAME               DESIRED   CURRENT   READY     AGE
nginx-3612065652   10        10        0         2s
nginx-4262182780   0         0         0         3m
nginx-618515232    0         0         0         5m
$ kc get po
NAME                     READY     STATUS              RESTARTS   AGE
nginx-3612065652-0af8n   0/1       Pending             0          5s
nginx-3612065652-b8owj   0/1       Pending             0          5s
nginx-3612065652-c554r   0/1       ContainerCreating   0          5s
nginx-3612065652-d27yl   0/1       Pending             0          5s
nginx-3612065652-dmxxe   0/1       Pending             0          5s
nginx-3612065652-rrxj8   0/1       ContainerCreating   0          5s
nginx-3612065652-sxmg4   0/1       Pending             0          5s
nginx-3612065652-vw1f8   0/1       ContainerCreating   0          5s
nginx-3612065652-wkbpb   0/1       Pending             0          5s
nginx-3612065652-yxdv2   0/1       Pending             0          5s
nginx-4262182780-1n8qx   1/1       Terminating         0          4m
nginx-4262182780-hfev8   1/1       Terminating         0          4m
nginx-4262182780-kvv32   1/1       Terminating         0          4m
nginx-4262182780-lcasb   1/1       Terminating         0          4m
nginx-4262182780-msbpe   1/1       Terminating         0          4m
nginx-4262182780-opmas   1/1       Terminating         0          4m
nginx-4262182780-qphvl   1/1       Terminating         0          4m
nginx-4262182780-qvxhm   1/1       Terminating         0          4m
nginx-4262182780-ukb89   1/1       Terminating         0          4m
nginx-4262182780-yipz2   1/1       Terminating         0          4m
```

**Comment by kargakis** [comment]
> due to node controller or drain deleting pods

@smarterclayton I still don't get this. The API server should be the only source of truth. If I get a replica set with spec.replicas==status.replicas==status.terminatingReplicas==0, why shouldn't that be the case ie. no pods for that version exist? Is the API server split-brained when a node is under maintainance? Do we need more guarantees from kubelets?

**Comment by smarterclayton** [comment]
The API server isn't the only source of truth.  The node controller and
namespace controller can both terminate pods at the end of their life in a
way that prevents you from seeing that you were terminated.  We've
discussed solving this for pet sets by having the pet set be a finalizer,
which would mean that everybody would try to clean it up and then the pet
set controller would get to observe the final deletion.  However, I'm not
sure that's a guarantee replica sets *need* - we need to discuss whether it
is.

On Tue, Sep 20, 2016 at 10:13 AM, Michail Kargakis <notifications@github.com

**Comment by kargakis** [comment]
@smarterclayton that's mostly a guarantee we want for Deployments. At the very least, by providing TerminatingReplicas at the replica set level, we handle a big part of what's needed here (the namespace controller is not a problem I think and I would expect that nodes are not restarted more often than not). If we want to handle nodes going down or being partitioned then we could have the replica set controller not update ObservedGeneration if it doesn't observe the required expectations it may have for a RS (I think @bprashanth suggested this in another place, don't remember for what reason though). Pet sets being on the level of the replica set may need to handle this differently. Replica sets don't need to handle any of it, the rs controller just needs to be smarter. Deployments being a level above, just need to work with synced RS (as we already do).

**Comment by kargakis** [comment]
If there are no use-cases for Recreate Deployments now that we have Pet Sets, I would like us to deprecate the Recreate strategy for Deployments. Then we wouldn't need this change too.

**Comment by smarterclayton** [comment]
JEE apps need recreate.

On Tue, Oct 18, 2016 at 12:25 PM, Michail Kargakis <notifications@github.com

**Comment by smarterclayton** [comment]
I think half of our OpenShift users in production use recreate

**Comment by kargakis** [comment]
I assume that most of them are using recreate because of RWO volumes. Why JEE apps need recreate? Since replica sets/deployments are valuing availability over consistency and pet sets the other way around I would expect us to try and move users from running their stateful apps with recreate deployments to use pet sets once they get stable.

**Comment by kargakis** [comment]
Maybe though that doesn't mean we should fix recreate

**Comment by kargakis** [comment]
Maybe though that doesn't mean we shouldn't fix recreate

**Comment by smarterclayton** [comment]
Because they use caches and other shared protocols that cannot tolerate two
versions of the same code Being run at the same time.

Probably 90% of all web applications ever written can't tolerate two
versions of the same code running at the same time.

On Oct 18, 2016, at 3:23 PM, Michail Kargakis <notifications@github.com>
wrote:

I assume that most of them are using recreate because of RWO volumes. Why
JEE apps need recreate? Since replica sets/deployments are valuing
availability over consistency and pet sets the other way around I would
expect us to try and move users from running their stateful apps with
recreate deployments to use pet sets once they get stable.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/32567#issuecomment-254611845>,
or mute the thread

**Comment by smarterclayton** [comment]
Heroku, for instance, defaults to a recreate strategy for exactly this
reason.

**Comment by kargakis** [comment]
Note that this will most probably multiply writes for RC/RS. Now I am thinking if listing pods in the deployment controller or a LIST combined with a WATCH is better.
