### ISSUE TITLE
Network throughput issues with latest version of container-vm 

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#32596]
The upgraded version of container-vm (gci) has significant performance regressions with localhost networking when compared to its previous versions.

@Amey-D is working on making gci kernel fixes to resolve this issue.

This issue is meant to track the GCI fix from release 1.4 perspective. 

The fix for this issue will result in upgrading the gci version pinned to release 1.4 branch.

ETA: <TBD>
Status: Yellow

**Comment by vishh** [comment]
@Amey-D can you update the ETA for fixing this issue?

**Comment by vishh** [comment]
cc @pwittrock for release tracking purposes.

**Comment by bprashanth** [comment]
is this a release blocker (why?) or are we aiming for a minor release?

**Comment by vishh** [comment]
@bprashanth It is a blocker because it causes about 70% drop in throughput which is a significant regression from a k8s on GCP user perspective.

**Comment by Amey-D** [comment]
The kernel fix should get merged in GCI kernel today, and hopefully we will be able to release a GCI version tomorrow that includes the fix.

**Comment by bprashanth** [comment]
Hmm, I somehow fail to see why a kubernetes release needs to be blocked on a bug fix going into one os the kubernetes release is being deployed on top of, but that's just my opinion

**Comment by vishh** [comment]
I get your point of view. But, k8s on GCE cannot have serious user-facing
issues. The distro is just an implementation detail, but an important one.
If we include first-class support for additional distros like ubuntu,
debian, etc. in the future, we will have to make the very same priority
calls.
At the end of the day, the release needs to work for most users in most
environments.

**Comment by dchen1107** [comment]
I think gci related issues shouldn't blocker OSS k8s 1.4 release. I also agreed that k8s on GCE cannot have serious user-facing issues, but that can be resolved by reverting the changes of making GCE node on GCI default. I am not suggesting that we do that now, but I do suggest we have the summary of the entire issue (not only this particular one) on GCI on node, and deeply understand the risk, then make the final decision. 

On another hand, we are still planning to enable GCI on node default between 1.4 and 1.5 time framework. cc/ @pwittrock
