### ISSUE TITLE
Network plugins do not work with upgraded version of container-vm

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#32595]
Extracted from https://github.com/kubernetes/kubernetes/pull/32151

When using kube-up on GCE, following #31023 which moved the workers from debian to gci, CNI just isn't working. The root cause is basically as discussed in #28563: one flag (--network-plugin-dir) means two different things, and the configure-helper script uses it for the wrong purpose.

This needs to be fixed in v1.4. 
#32151 is already out to fix this.

ETA should be EOD 9/13 

cc @freehan @bboreham

**Comment by vishh** [comment]
cc @pwittrock for tracking a release blocker.

**Comment by bboreham** [comment]
I believe this was fixed in 1.4.
