### ISSUE TITLE
Expand the e2e framework to allow running "side car" tests

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#32607]
The current e2e framework allows one to add test cases to run at some point during the e2e run. 

I want to run something like a "side car" test, which runs periodically along with other e2e tests. If it failed at some point, then log it fail during "what e2e tests are running" and "what e2e tests have finished" at that point. 

Side car tests are useful for ensuring firewall configuration, network configuration and network performance. This basically applies to anything that should always work and does not expect to be disrupted by other work flows. 

Any ideas? @kubernetes/sig-testing 

ref: https://github.com/kubernetes/kubernetes/issues/31827

**Comment by freehan** [comment]
cc: @matchstick @thockin

**Comment by pmorie** [comment]
I would like to find a name for this concept that is not 'sidecar', since 'sidecar' is already a thing, and the name is already misused enough without overloading it :)

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @freehan @pmorie

**Comment by matchstick** [comment]
@thockin I think it is safe to move this to 1.6.

**Comment by spiffxp** [comment]
/sig testing

I don't have privileges to move this out of the milestone, but I don't think it belongs in v1.7

**Comment by spiffxp** [comment]
/close
I'm not entirely sure this should remain open after being untouched for 16 months.  FWIW this concept might be implementable via https://github.com/kubernetes/kubernetes/blob/master/test/e2e/chaosmonkey/chaosmonkey.go.  Please /reopen if you'd like to take this on
