### ISSUE TITLE
have a package to hold constants to avoid cross referencing

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#32600]
There are some constants in kubelet and kube-proxy that refers to the same thing. For example:
https://github.com/kubernetes/kubernetes/blob/a57561b84dd436d92ae43805b63ac7bb23ae188c/pkg/kubelet/kubelet_network.go#L38
https://github.com/kubernetes/kubernetes/blob/65f3fa9caf79a5cae49ff893695c58ca63863ad1/pkg/proxy/iptables/proxier.go#L71
https://github.com/kubernetes/kubernetes/blob/57604d13cd7e9985e520511efc5b3b3b3dd62000/pkg/kubelet/network/hostport/hostport.go#L284

There must be other cases like this. Propose to have a package to store constants used by multiple components in one place.

**Comment by tcharding** [comment]
I hacked together a tool to extract the constants recursively from a Go source tree. There are 236 duplicate constants in `pkg/`. Is the best way to broaden the discussion on this to put in a WIP PR adding `k8s.io/kubernetes/constants.go` and migrate a few constants there as an example? I'm new around here so I feel like this needs input from someone with more architectural knowledge.

You can find the tool on [github](https://github.com/tcharding/constants)
