### ISSUE TITLE
Support interpolating secrets into configMaps?

### ISSUE THREAD

**Issue by dcowden** [kubernetes/kubernetes#32616]
I understand the intent difference between secrets and configMaps.

We are porting older applications to k8s, and in many cases, the concerns of configMaps and secrets are intertwined into a single file or even a single line in a file.

For example, consider this jdbc configuration url::

    jdbc.url=our.database;1433;database=dbname;username={{ dbuser}};password={{ db_pass}}

Today, this file is assembled using Ansible and Ansible vault at deploy time. The configuration file is checked out from git, and then the secrets are interpolated from ansible vault encrypted storage. The result is injected into the application.

I really love the idea of k8s config maps and secrets. I think they are the correct abstractions.  But I'm hung up on how to use them in cases like this.  Storing the above URL as either a configMap or as a secret is less than ideal:

   * if we store the merged result as a configMap, our secrets are exposed
   * if we store the merged result as a secret, it becomes hard to debug them, because you cannot see the insensitive configuration information ( which can include things you do want to see)

I would like to see is the ability to interpolate secrets into configMaps.  First, I would first create a configMap::

    kubectl create configmap game-config --from-file=mydb.properties

Which would contain perhaps this::

    jdbc.url=our.database;1433;database=dbname;username=dbusername;password={{ secret:: db-user-pass}}

And then create the secret::

     kubectl create secret generic db-user-pass --from-file=./pass.txt

where pass.txt contains the password

This would allow me to avoid the need to do this assembly outside of the system.  I've done some research and I have not really found any alternative approaches.  

One workaround that might be sufficient is to allow environment variable interpolation inside of configMaps.  If this were possible, I could inject secrets into environmentVars. Another similar workaround would be to do the interpolation in the application. The application would need to have ability to substitute environment vars ( which could have the values from secrets) into all of the files it mounts as configMaps.  I'm aware that this is possible, but there are many, many java libraries that consume configuration files and do not provide interpolation, so this workaround would not always be feasible.

I am open to ideas if there is already an accepted 'better' way to do this.  Any help/suggestions are appreciated!

**Comment by pmorie** [comment]
This is similar to functionality that has been asked for recently a number of times; please see #30716

**Comment by dcowden** [comment]
yep-- precisely. I'll +1 that one. thanks for directing me there.

**Comment by reachlin** [comment]
are we able to use secrets in configmap or what?

**Comment by r-divakaran** [comment]
Is it documented some where how to use this. 

I want to create a configmap like

`apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-grafana-datasource
  labels:
     grafana_datasource: 1
data:
  datasource.yaml: |-
    # config file version
    apiVersion: 1

    datasources:
      - name: Cloudwatch
        type: cloudwatch
        jsonData:
          authType: keys
          defaultRegion: eu-west-1
        secureJsonData:
          accessKey: "<your access key>"
          secretKey: "<your secret key>"`

Can I use references to a secret for those access keys and passwords ?

**Comment by deepanvermag3** [comment]
@reachlin What's the answer to your question? Yes or No?

**Comment by spstarr** [comment]
No, this is not addressed:

Case in point:

If i have a secret called foobar, with data:  mypassword

If i have a configMap:

```
ApiVersion: v1
kind: ConfigMap
metadata:
  name: setup-rabbitmq
  namespace: rabbitmq
  labels:
    app: rabbitmq
data:
  rabbitmq.conf: |
       ## On first start RabbitMQ will create a vhost and a user. These
      ## config items control what gets created.
      ## Relevant doc guide: http://rabbitmq.com/access-control.html 
      ##
      default_vhost = /
      default_user = admin
      default_pass = {{ $rabbitmq_admin_password }}
     default_permissions.configure = .*
     default_permissions.read = .*
     default_permissions.write = .*
```
We can't use Helm here, especially if you want the secret generated once, there's hacks and they don't handle upgrades..

Reason?

If you make your secrets

```
{{- if .Release.IsInstall }}
{{- $rabbitmq_admin_password := randAlphaNum 18 | b64enc }}
{{- $rabbitmq_myapp_password := randAlphaNum 18 | b64enc }}
{{- $rabbitmq_erlang_cookie := randAlphaNum 18 | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitsecrets
  namespace: rabbitmq
  annotations:
     "helm.sh/resource-policy": keep
type: Opaque
data:
  rabbitmqadminpass: "{{ $rabbitmq_admin_password }}"
  rabbitmyapppass: "{{ $rabbitmq_myapp_password }}"
  rabbiterlangcookie: "{{ $rabbitmq_erlang_cookie }}"
{{- end  }}
```
Fails, because Helm doesn't know about global variables (no im not talking about values.yaml either).

So you end up with a broken mess, the fact Kubernetes lets you reference secrets with valueFrom: but you can't do it within configMaps doesn't make sense to me....

**Comment by elasticdotventures** [comment]
In a similar but not the same issue, `podman play kube` for running a localstack, I have a very insecure solution documented here:
https://stackoverflow.com/questions/77076123/how-to-put-secrets-into-a-configmap-with-podman-play-kube/77076124#77076124
