### ISSUE TITLE
Export kubelet metrics about node and scheduling status

### ISSUE THREAD

**Issue by grobie** [kubernetes/kubernetes#32610]
**Kubernetes version** (use `kubectl version`):
v1.3.5

**Use cases**
As an operator,
In order to filter metrics by node status and scheduling status,
I need metrics exporting the state of these attributes.

As an operator,
in order to write scripts depending on the state of ready and scheduling,
I need a way to query these information from the same host (ideally without going to the API server first).

**Proposal**
Export two new gauges from the kubelet:
1. `kubelet_node_status_ready` with possible values 1 or 0
2. `kubelet_node_status_schedulable` with possible values 1 or 0

Alternatively a single metric `kubelet_node_status` could be exported with labels for each possible status.

@kubernetes/sig-instrumentation @fabxc

**Comment by davidopp** [comment]
> ideally without going to the API server first

Why? There is a lot of information a monitoring system might want that we don't want to have to push down to the Kubelet. I think a proper monitoring system is going to pull from the API server.

**Comment by grobie** [comment]
Sure, I didn't want to say that metrics not available to the kubelet should be pushed down, but these two states are already available to the kubelet, aren't they? Making the API server the only source for metrics creates a bottleneck and risks losing visibility during outages.

We had a similar discussion recently about where to export deployment information and my takeaway was that the best place to export metrics is the owner/producer of state. For the ready state that seems to be the kubelet itself.

Not being able to query the kubelet itself whether it is in maintenance mode / schedulable makes things like external health checks pretty hard.

**Comment by grobie** [comment]
Actually looking at all the node conditions, I think we should export the state of all of them. Maybe like this:

```
kubelet_node_condition{type="Ready"}
kubelet_node_condition{type="OutOfDisk"}
kubelet_node_condition{type="MemoryPressure"}
kubelet_node_condition{type="DiskPressure"}
kubelet_node_condition{type="NetworkUnavailable"}
```

**Comment by brancz** [comment]
@grobie We are actually working on getting a release out for [kubernetes/kube-state-metrics](https://github.com/kubernetes/kube-state-metrics). It exports most of the states you are looking for, and we have planned to add all of them.

Arguably, some metrics exposed about nodes overlap with those for example exported by the node exporter. Your argument about the API server becoming a bottleneck is circumvented by the kube-state-metrics being an in memory cache for the state within kubernetes.

**Comment by davidopp** [comment]
`kubelet_node_status_schedulable` is really the only one I was reacting to; sorry for making it sound overly broad. And I had forgotten that we have `NodeSpec.Unschedulable`, which I assume is what you're referring to here? I now remember that we decided to push unschedulable down to kubelet even though it doesn't need it; I think it was just for UX purposes, so someone could see it along with the other conditions when they look at NodeStatus. So anyway, never mind my comment.

**Comment by fabxc** [comment]
I think we should retrieve metrics in the most direct way possible. The API server is retrieving some of the metrics it exposes directly from the kubelet (which in turn partially retrieves them from cAdvisor). A reliable monitoring system should pull these directly from the source to not indirect through POFs and avoid staleness in the data.

Arguably, several of the metrics exposed by kube-state-metrics could/should be moved into the kubelet. It's just better to have them in kube-state-metrics for now than not at all.

**Comment by matthiasr** [comment]
Are there situations where the API status and what the kubelet knows can
diverge?

**Comment by fabxc** [comment]
I think this can be closed given today's state of kube-state-metrics.

**Comment by grobie** [comment]
@fabxc Can you describe how today's state of kube-state-metrics is different that it doesn't longer matter that monitoring a node requires the API and the kube-state-metrics service to be available?
