### ISSUE TITLE
Calico / NetworkPolicy broken in GCE provider

### ISSUE THREAD

**Issue by caseydavenport** [kubernetes/kubernetes#32625]
https://github.com/kubernetes/kubernetes/pull/31023#issuecomment-246860748 broke the salt-based Calico install in the GCE kube-up deployments, since the GCI image doesn't use salt and instead relies on cloud-config.

e.g 

```
NETWORK_POLICY_PROVIDER=calico cluster/kube-up.sh
```

which used to work, doesn't any more.

This should be fixed when the Calico self-hosted installation PR https://github.com/kubernetes/kubernetes/pull/30598/files hits, which will install Calico using a DaemonSet.

Keeping a list of the things that are going wrong since the switch to GCI:
- Node components are no longer installed (Will be fixed by #30598)
- calico/node:v0.22.0 failing due to missing ip_set kernel support.
- `NETWORK_POLICY_PROVIDER=calico` no longer sets `--network-plugin=cni` on kubelet.

**Comment by thockin** [comment]
For GCI: Was a full audit of the salt logic done?  How did this get missed?

For Calico: Users should be able to not use GCI (@vishh can you post details here?)

**Comment by caseydavenport** [comment]
@vishh If there's a way to run using debian that would be great.  I know @matthewdupre spent a bit of time a a couple of months ago trying to get that to work, but wasn't able to find the right incantation to actually make it work.

**Comment by vishh** [comment]
Setting `KUBE_NODE_OS_DISTRIBUTION=debian` will continue to work for at-least until v1.5 for now. 

Given that we are moving towards DaemonSets sometime soon, I assume this issue can be worked around for now. 

@caseydavenport Can you update the documentation to mention the workaround for release v1.4?

**Comment by vishh** [comment]
@caseydavenport Apologies for breaking Calico integration. We currently have no means to track all the salt parameters. To avoid this in the future, I'd recommend adding a separate test suite that tests calico integration.

**Comment by caseydavenport** [comment]
I will try the `KUBE_NODE_OS_DISTRIBUTION=debian` option, and update the documentation with what I find.

**Comment by caseydavenport** [comment]
The latest here:

Sadly, the GCI image being used today doesn't include a few kernel features that Calico wants for policy enforcement.
- ip6tables: this is fine, GCE doesn't support IPv6 yet anyway as far as I know, and this can just be turned off in Calico. Not a problem.
- ip sets: This is actually a problem - Calico can't do policy without this.  It looks like the xt_set module is loaded, but it doesn't seem to include the right features, specifically it doesn't support the "hash:ip" set type.

Module info on the GCI host:
```
casey@kubernetes-minion-group-3az5 ~ $ modinfo xt_set
filename:       /lib/modules/4.4.14+/kernel/net/netfilter/xt_set.ko
alias:          ip6t_SET
alias:          ipt_SET
alias:          ip6t_set
alias:          ipt_set
alias:          xt_SET
description:    Xtables: IP set match and target module
author:         Jozsef Kadlecsik <kadlec@blackhole.kfki.hu>
license:        GPL
depends:        ip_set
intree:         Y
vermagic:       4.4.14+ SMP mod_unload
```

```
casey@kubernetes-minion-group-3az5 ~ $ lsmod | grep xt_set
xt_set                 16384  0
ip_set                 32768  1 xt_set
```

Output from Calico attempting to program ipsets:
```
FailedSystemCall: Failed system call (retcode : 1, args : ('ipset', 'restore'))
  stdout  :
  stderr  : ipset v6.29: Error in line 1: Kernel error received: set type not supported
  input   : create felix-v4-_0cd8852cac8c2d9 hash:ip family inet maxelem 1048576 --exist
```

How can we get a GCI build that has this included?  

@thockin @vishh

**Comment by vishh** [comment]
@Amey-D might be able to provide more inputs from GCI side. From a release perspective, we might be able to get a build with `ip sets` in one of the upcoming patch releases for v1.4.0 depending on the GCI changes required. Thanks for the detailed feedback!

**Comment by Amey-D** [comment]
I can enable hash:ip for xt_set module in GCI.  Is this a blocker for 1.4.0?

**Comment by vishh** [comment]
This is not a blocker for v1.4.0.

**Comment by bboreham** [comment]
If I may butt in, the GCI image also lacks the kernel module for VXLAN, which various overlay networks use.

I can open a separate issue for that if you like (if you see this as an issue).

**Comment by vishh** [comment]
@bboreham A separate issue might be helpful just for tracking purposes. #32735 is tracking the lack of visibility into networking dependencies in general. If we were aware of these dependencies, they would have been addressed long back. 
For now, is it safe to assume that the workaround mentioned above (https://github.com/kubernetes/kubernetes/issues/32625#issuecomment-247096008) will still work for overlay networks?

**Comment by thockin** [comment]
Thanks all.   It's not surprising that a new distro and kernel is lacking
tools.

Propose:
- add the requisite kernel modules and flags to turn on everything listed
here and any other optionals
- bundle ipset, ip6tables, ebtables, and conntrack packages with the OS or
make sure they work in the toolbox for debugging

Any other things to try to break?

**Comment by bboreham** [comment]
@vishh yes, thanks, I have been using `KUBE_OS_DISTRIBUTION=debian` when I want to avoid the gci quirks, but I should stress the overlay I work on (Weave Net) is built to "run anywhere" and hence it's good for us to throw in a kernel that's a bit different.  Other products, such as Docker's own overlay network, will simply not work without the VXLAN module.

**Comment by caseydavenport** [comment]
@fasaxc @matthewdupre  - Anything else you think we should be enabling?

**Comment by fasaxc** [comment]
@caseydavenport We also use `ip route|addr|...` from iproute2 and `arp`.

**Comment by caseydavenport** [comment]
`gci-dev-55-8872-18-0` seems to contain the right ipset features, though it is missing the arp userspace which @fasaxc mentioned.

**Comment by adityakali** [comment]
@fasaxc @caseydavenport Both `/sbin/ip` and `/sbin/arp` should already be there. Please let me know if they don't work for you.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @caseydavenport @thockin @bboreham

**Comment by caseydavenport** [comment]
I don't think I'll have the bandwidth to address this in the next day or two.

I don't think this should block v1.5.  The GCI changes necessary to make this work seem to have gone in (which was the important part in my mind), there's just a little bit of scripting left to actually install the Calico DaemonSet when the flag is set.

**Comment by dims** [comment]
Thanks @caseydavenport marked as such

**Comment by caseydavenport** [comment]
@dims Fine to clear the milestone and remove the non-release-blocker tag.

**Comment by 2opremio** [comment]
> bundle ipset, ip6tables, ebtables, and conntrack packages with the OS or
make sure they work in the toolbox for debugging

Conntrack events (CONFIG_NF_CONNTRACK_EVENTS) are also unsupported, which breaks connection tracking on https://github.com/weaveworks/scope 

I have created https://code.google.com/p/google-compute-engine/issues/detail?id=499 to track it separately

**Comment by Amey-D** [comment]
The support for NF_CONNTRACK_EVENTS was enabled in Container-Optimized OS kernel starting from gci-dev-56-8977-0-0.  It's enabled in the current versions on dev and beta channels.  I see the following on a GCE instance created from gci-beta-56-9000-36-0:

$ sudo modprobe configs
$ zgrep NF_CONNTRACK_EVENTS /proc/config.gz 
CONFIG_NF_CONNTRACK_EVENTS=y

Please try your workflow on the newer image versions and see if the problem still exists.

**Comment by thockin** [comment]
Thanks!

**Comment by bboreham** [comment]
@caseydavenport can this be closed now the GCI build has xp_set ?

**Comment by caseydavenport** [comment]
The remaining bits required to close this issue are here: https://github.com/kubernetes/kubernetes/pull/38169
