### ISSUE TITLE
federation: kubectl describe ns fails

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#32629]
`kubectl get ns myns --context=federation-cluster` returns:
```
Error from server: the server could not find the requested resource
```

The issues is that it calls `/api/v1/namespaces/spark-cluster/resourcequotas` which doesnt exist on federation-apiserver.

cc @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
Possible fixes:

1. Add resource quotas to federation-apiserver
2. Update kubectl to return the information it did get. So it returns information about myns, just that resource quota information is missing.
3. As part of API machinery, we have discussed moving describe and other "printers" to the server. If we do that, then federation apiserver can have its own implementation without resource quotas different from kube-apiserver's implementation. This is a bigger change that will fix describe for all federation resources.

For now, I think we can go with the second option.

**Comment by AdoHe** [comment]
@kubernetes/kubectl

**Comment by nikhiljindal** [comment]
Sent https://github.com/kubernetes/kubernetes/pull/32823 to fix the issue using the 2nd option from my comment above.
