### ISSUE TITLE
Clarify desired cAdvisor integration in kubelet

### ISSUE THREAD

**Issue by grobie** [kubernetes/kubernetes#32638]
**Kubernetes version** (use `kubectl version`):
v1.3.5

**Current state**:
The kubelet exports cadvisor metrics and kubelet metrics under `/metrics` on both the API port as well as on the cAdvisor port. This the result of both kubelet and cadvisor using the global Prometheus metrics registry.

**Effect**:
It's not possible to disable cAdvsior metrics being exported by the kubelet. The use case is to run a custom cAdvsior as a daemonset in order to deploy new cadvisor versions before changes get merged into kubernetes. Setting the `--cadvisor-port=0` flag will disable the second port but still cause the kubelet to export cAdvisor metrics under the API /metrics endpoint.

This has been done on purpose by @jimmidyson in 3a6701c8.

**Questions**:
- Do we want to support the use case of disabling cAdvisor metrics under /metrics completely?
- Do we want to export kubelet metrics under /metrics on the cAdvisor port?
- What is the use case for opening a separate cAdvisor endpoint and port next to the endpoints available under the API port?

@jimmidyson @timstclair @vishh @kubernetes/sig-node @kubernetes/sig-instrumentation

**Comment by jimmidyson** [comment]
There is an outstanding discussion to run cadvisor standalone rather than embedded - see #18770 for discussion. I personally support that idea.

I think if we decide & work on that direction then your questions become less relevant but for now:

> Do we want to support the use case of disabling cAdvisor metrics under /metrics completely?

We could, as long as that only means removing metrics from /metrics & not affecting metrics API for autoscaling.

> Do we want to export kubelet metrics under /metrics on the cAdvisor port?

No I don't think we do. This is a legacy of the global Prometheus registry IIRC.

> What is the use case for opening a separate cAdvisor endpoint and port next to the endpoints available under the API port?

AFAIK this was just a legacy of the original design & there to support existing users of it. @vishh will know more I'm sure, I'd like to get rid of this cadvisor port as well as the read-only port actually as they have the potential for info leakage as they have no auth like the normal kubelet port. Now the kubelet supports ABAC, same as API server, this should be the preferred option IMO.

**Comment by timstclair** [comment]
I agree with everything @jimmidyson said, but have a few more details:

If (when) we switch to standalone cAdvisor, we should get rid of the cAdvisor port in the kubelet (or maybe redirect to the standalone cAdvisor for backwards compatability)

I agree that the metrics served on the cAdvisor port should be pure cAdvisor metrics, which will make the above point easier. I think which metrics are served on the kubelet metrics endpoint is more debateable, especially thinking about the standalone cAdvisor use-case. If we limit the cAdvisor metrics to the cAdvisor endpoint, it would make the transition to standalone smoother (but also require scraping an additional endpoint).

+ @kubernetes/sig-instrumentation

**Comment by grobie** [comment]
All my requests were solely around Prometheus metrics under /metrics. What do you think about the following steps?

1) Use separate prometheus registries and stop exporting kubelet metrics under cAdvisor port. Keep cAdvisor metrics under the API port for backwards compatibility for now.
2) Add option to disable cAdvisor Prometheus metrics in /metrics completely.
3) Deprecate cAdvisor port

The main question is whether to just revert the changes in 3a6701c and not registering the Prometheus cAdvisor collector if cAdvisor port == 0 or if we want to add a new flag for 2).

**Comment by fabxc** [comment]
> I think which metrics are served on the kubelet metrics endpoint is more debateable, especially thinking about the standalone cAdvisor use-case.

Could you elaborate @timstclair?
Is the idea here to keep the cAdvisor /metrics endpoint in the kubelet around with a standalone cAdvisor? I couldn't fully infer from the previous discussions whether the general idea would be to keep a minimal embedded cAdvisor around for system consumption (autoscaling etc.) or to make the external one mandatory for those to work.

**Comment by timstclair** [comment]
> the general idea would be to keep a minimal embedded cAdvisor around for system consumption

Yes, that's the idea. I guess by this logic the general metrics exported by cAdvisor would be moved out of the Kubelet, and only the kubelet-specific metrics would remain (e.g. reporting Kubelet usage). I think it's an open question where cluster-level "core" metrics (i.e. for autoscaling) would be sourced from.

**Comment by piosz** [comment]
FYI https://docs.google.com/document/d/1z7R44MUz_5gRLwsVH0S9rOy8W5naM9XE5NrbeGIqO2k

**Comment by brancz** [comment]
Starting with 1.7.3 the cadvisor metrics have been moved out of `/metrics` to `/metrics/cadvisor`, with `/metrics` leaving only the actual kubelet's metrics.

Related: https://github.com/kubernetes/kubernetes/issues/53615

**Comment by luxas** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/56523
The cAdvisor port 4194 got disabled by default in v1.11 and the option to enable it overall is gonna be removed in v1.12
