### ISSUE TITLE
[ContainerGC]maximum-dead-containers-per-container can't remove the containers in one pod with different name

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/kubernetes#32657]
**Kubernetes version** (use `kubectl version`):
v1.5.0-alpha.0.756+61ba82c6379eca-dirty

**What happened**:
When set maximum-dead-containers-per-container for kubelet, ContainerGC can't remove containers in one pod because all container in one pod with different name can't be a evictUnit.

**How to reproduce it** (as minimally and precisely as possible):
1. Configure containerGC parameters for kubelet
        --maximum-dead-containers=30
        --maximum-dead-containers-per-container=2
        --minimum-container-ttl-duration=10s

2. Create a pod with multi container
kubectl create -f https://raw.githubusercontent.com/mdshuai/testfile-openshift/master/GarbageCollection/max-dead-containers-per-pod.yaml

3. When pod is complete check the dead container on nodes
```
[root@ip-172-18-1-178 kubernetes]# kubectl get pod --show-all
NAME               READY     STATUS      RESTARTS   AGE
multi-containers   0/5       Completed   0          2m
[root@ip-172-18-1-178 kubernetes]# docker ps -a
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                     PORTS               NAMES
58b8341c560f        docker.io/centos:centos7                   "sh -c 'echo hello te"   2 minutes ago       Exited (0) 2 minutes ago                       k8s_test4.245a1d29_multi-containers_default_02771902-7a60-11e6-a91a-0ebdb009789b_602e24f6
964b61ddcd0b        docker.io/centos:centos7                   "sh -c 'echo hello te"   2 minutes ago       Exited (0) 2 minutes ago                       k8s_test3.1ed31d27_multi-containers_default_02771902-7a60-11e6-a91a-0ebdb009789b_1552bf1e
858d1614a6d7        docker.io/centos:centos7                   "sh -c 'echo hello te"   2 minutes ago       Exited (0) 2 minutes ago                       k8s_test2.194c1d25_multi-containers_default_02771902-7a60-11e6-a91a-0ebdb009789b_596fab0b
082518fc3b1e        docker.io/centos:centos7                   "sh -c 'echo hello te"   2 minutes ago       Exited (0) 2 minutes ago                       k8s_test1.13c51d23_multi-containers_default_02771902-7a60-11e6-a91a-0ebdb009789b_abf51752
eaa3b558c93a        docker.io/centos:centos7                   "sh -c 'echo hello te"   2 minutes ago       Exited (0) 2 minutes ago                       k8s_test5.29e11d2b_multi-containers_default_02771902-7a60-11e6-a91a-0ebdb009789b_7e3e258e
43330f5520ab        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 2 minutes ago       Exited (0) 2 minutes ago                       k8s_POD.d8dbe16c_multi-containers_default_02771902-7a60-11e6-a91a-0ebdb009789b_25031a7d
```
**Expected result** :
In the same pod should only retain 2 container.

**Anything else do we need to know**:
[evictUnit](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/container_gc.go#L67-L73) shouldn't be podName not containerName, if so [len(evictUnits[uid])](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/container_gc.go#L101) will always be 1. so can't remove container in one pod.

**Comment by mdshuai** [comment]
@derekwaynecarr help check if my understand is wrong, thanks

**Comment by yujuhong** [comment]
This is working as intended. `--maximum-dead-containers-per-container=2` means for every (pod, container name) tuple, there will be maximum two dead containers. 
We keep the dead containers for logs and as checkpoint of the container state, so it is necessary to keep dead containers for every container in the pod.

**Comment by ncdc** [comment]
@mdshuai I originally had the same thought as you, but if you read the description for `--maximum-dead-containers-per-container`, it says: "Maximum number of old instances to retain per container". This means that for any give container in a pod, we should only keep around *n* previous instances for that particular container. For example, if I have a pod with only one container, let's say `apache`, and for whatever reason it crashed a few times, container GC will keep up to `--maximum-dead-containers-per-container` dead instances of the `apache` container for this pod. Does this make sense?

**Comment by mdshuai** [comment]
@ncdc Thanks for your example, it make sense.
@yujuhong  Thanks for your explain. But (pod, container name) just a subset of (pod, podName). Don't you think make all containers in one pod as a evictUnit is more useful ? it can clean both the containers in the example @ncdc said and the containers in my case.

**Comment by ncdc** [comment]
@mdshuai I think it makes sense to retain the current behavior. In your example, your pod has a restart policy of "on failure". Your pod ran all its containers, they succeeded, and so now the pod is no longer running and has completed successfully. If you GC any of these containers, you won't be able to see their logs.

**Comment by yujuhong** [comment]
> @ncdc @yujuhong Thanks for your explain. But (pod, container name) just a subset of (pod, podName). Don't you think make all containers in one pod as a evictUnit is more useful ?

Not really. As I said, you'd want to keep at least one instance of every container in your pod for logs. kubelet also still relies on seeing the "dead container" to decide whether a container has been run before. Hence it's important to track every container in a pod separately.
