### ISSUE TITLE
kubectl shouldn't fail hard when /version returns 404

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#32679]
kubectl works mostly fine without /version. But a number of commands (apply, create, convert, ....) are wired to this:

https://github.com/kubernetes/kubernetes/blob/519c13745f8c5cc3fa50897575fe7aaca04cfbf1/pkg/kubectl/cmd/util/factory.go#L749-L749

A 404 on /version let's the kubectl to fail hard.

For environments where `/version` might be a security problem (cf. https://github.com/kubernetes/kubernetes/pull/32387#issuecomment-247071249) this is a nogo.

Relates to minimal apiserver routes: https://github.com/kubernetes/kubernetes/issues/32678

**Comment by smarterclayton** [comment]
/version is desirable (we think all servers should have it) but it should not be required for the proper functioning of a client to be able to retrieve it.
