### ISSUE TITLE
auto-delete leaked cloud resources in e2e

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#32690]
Issues like https://github.com/kubernetes/kubernetes/issues/27883 are a menace, they're hard to track down and take time to fix. In the meanwhile, the SQ keeps getting blocked because quota on the test project is usually pretty low and there are too many projects to keep bumping quota up on each one. 

We can already detect leaks, obviously: https://pantheon.corp.google.com/m/cloudstorage/b/kubernetes-jenkins/o/logs/kubernetes-e2e-gce-ingress/7981/artifacts/gcp-resources-after.txt
We already fail tests on leak
Why not just delete the detected resorces? 

@kubernetes/sig-testing I think this would alleviate a long time chronic issue that plagues us around release time

**Comment by spxtr** [comment]
Another strategy would be to delete any unexpected resources at the start or end of the test run regardless of what the leak detector finds.

**Comment by bprashanth** [comment]
that is risky because of parallel runs right? i thought it was only safe to delete cloud resources that you *know* are from your own kubernetes namespace (or at least i remember doing exactly what you said and it broken things, around 1.1 time, because of parallel tests)

**Comment by bprashanth** [comment]
Also i have this is the ingress e2es, where the test cleans up after it's own ns tagged cloud resources, but sometimes that after each doesn't run eg: if the build is cancelled or times out. The next test won't touch the leaked resources because it doesn't match its own kubernetes ns tag.

**Comment by spxtr** [comment]
I mean we should clean up old things like firewall rules or networks or whatever before we even start running tests.

**Comment by bprashanth** [comment]
oh you mean in the jenkins script, thought you meant test owners should do it in Before/AfterEach

**Comment by spxtr** [comment]
@krzyzacy is in charge of the janitor, and I think we can close this issue.
/assign @krzyzacy

**Comment by krzyzacy** [comment]
/close
yeah janitor has been cleaning up old leaked resources effectively.

I'll make it generate some report, follow up discussion in https://github.com/kubernetes/test-infra/issues/2925
