### ISSUE TITLE
GKE: Deployment deployment should create new pods

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#32695]
https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.2-1.4-upgrade-cluster

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.2-1.4-upgrade-cluster/6162

**Comment by davidopp** [comment]
failing in
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gce-cvm-1.3-cvm-1.4-upgrade-master

**Comment by davidopp** [comment]
(title of bug says GKE, though above is GCE)

**Comment by janetkuo** [comment]
Fixed by #33030
