### ISSUE TITLE
GKE: Kubectl client Kubectl describe should check if kubectl describe prints relevant information for rc and pods [Conformance]

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#32699]
https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.2-1.4-upgrade-cluster

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.2-1.4-upgrade-cluster/6162

**Comment by davidopp** [comment]
see also #31429

**Comment by davidopp** [comment]
https://k8s-testgrid.appspot.com/google-kubectl-skew#gke-1.2-1.3-gci-kubectl-skew
https://k8s-testgrid.appspot.com/google-kubectl-skew#gke-1.2-1.3-cvm-kubectl-skew

**Comment by jessfraz** [comment]
@davidopp is there something different about the way those tests are setup that are why it's failing?

**Comment by AdoHe** [comment]
@pwittrock and also this one.
