### ISSUE TITLE
Deployment paused deployment should be ignored by the controller

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#32698]
https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.2-1.4-upgrade-cluster

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.2-1.4-upgrade-cluster/6162

**Comment by janetkuo** [comment]
The same cause as https://github.com/kubernetes/kubernetes/issues/32710#issuecomment-247177634, closing with the same reason
