### ISSUE TITLE
GKE: Deployment deployment should support rollback when there's replica set with no revision

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#32697]
https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.2-1.4-upgrade-cluster

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.2-1.4-upgrade-cluster/6162

**Comment by janetkuo** [comment]
scale rs not found error should be ignored, see https://github.com/kubernetes/kubernetes/commit/36522378f45607c5ec186948a8534520075e9f94

**Comment by davidopp** [comment]
failing in
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gce-cvm-1.3-cvm-1.4-upgrade-master
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gke-gci-1.3-cvm-1.4-upgrade-master

**Comment by kargakis** [comment]
> scale rs not found error should be ignored, see 3652237

You actually need 4c56b8c on top of 3652237

**Comment by dshulyak** [comment]
@janetkuo why https://github.com/kubernetes/kubernetes/pull/32825 is only for 1.2? I thought thats just a bug in cleanup function

**Comment by janetkuo** [comment]
> @janetkuo why #32825 is only for 1.2? I thought thats just a bug in cleanup function

The 1.3 fix is #33030. Fixed by #33030, closing

**Comment by janetkuo** [comment]
@dshulyak because it's fixed differently in 1.4 tests (more specifically, in replica set reapers), by setting  `OrphanDependents` to `false` in DeleteOptions to tell the garbage collector that we want to delete it immediately. We can't do so in 1.2 or 1.3, obviously, since `OrphanDependents` doesn't exist there.
