### ISSUE TITLE
GKE: Deployment RollingUpdateDeployment should scale up and down in the right order

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#32694]
https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.2-1.4-upgrade-cluster

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.2-1.4-upgrade-cluster/6162

**Comment by davidopp** [comment]
failed in
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gce-cvm-1.3-cvm-1.4-upgrade-master
