### ISSUE TITLE
[k8s.io] Kubectl client [k8s.io] Kubectl rolling-update should support rolling-update to same image [Conformance]

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#32706]
https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.4-1.3-kubectl-skew

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.4-1.3-kubectl-skew/6187

**Comment by caesarxuchao** [comment]
We plan to solve this issue by documentation. #32751 let users of older version kubectl see a more specific error message and the way to work around when the `kubectl rolling-update` fails. We will document the incompatibility in the 1.4 release note.

**Comment by lavalamp** [comment]
Let's leave this open while the test is red.

**Comment by caesarxuchao** [comment]
The tests are disabled. Closing.
