### ISSUE TITLE
Kubelet [Serial] [Slow] regular resource usage tracking for 35 pods per node over 20m0s

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#32703]
Kubelet [Serial] [Slow] regular resource usage tracking for 35 pods per node over 20m0s

https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.2-1.4-upgrade-cluster

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.2-1.4-upgrade-cluster/6162

**Comment by dchen1107** [comment]
It is known docker 1.11 (in Kubernetes 1.4) using more memory than docker 1.9 (in Kubernetes 1.2), and the resource tracking tests running here with 1.2 limit here. It is expected to be failed.

**Comment by davidopp** [comment]
failing in
https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-gci-1.2-gci-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-gci-1.2-cvm-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-cvm-1.2-gci-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-cvm-1.2-cvm-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-gci-1.2-cvm-1.4-upgrade-cluster
