### ISSUE TITLE
SubjectAccessReview typos groups field name

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#32709]
The `Groups` field of a SubjectAccessReviewSpec is being serialized as `group`:
https://github.com/kubernetes/kubernetes/blob/b841a8bad3855c5c4b95c7dd2596e22018f9af68/pkg/apis/authorization/v1beta1/types.go#L119:

```
// Groups is the groups you're testing for.
Groups []string `json:"group,omitempty" protobuf:"bytes,4,rep,name=group"`
```

This is already documented as `group` for v1beta1, so we can't easily change it now, but should be fixed in the v1 version

**Comment by liggitt** [comment]
cc @cjcullen

**Comment by deads2k** [comment]
> This is already documented as group for v1beta1, so we can't easily change it now, but should be fixed in the v1 version

Right, this was used as the basis for the authz webhook quite some time ago.  I agree it should be changed, but that API won't be ready for graduation for a while.
