### ISSUE TITLE
[k8s.io] Services should be able to change the type and ports of a service [Slow]

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#32707]
[k8s.io] Services should be able to change the type and ports of a service [Slow]

https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.3-1.4-upgrade-cluster-new

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.3-1.4-upgrade-cluster-new/609

**Comment by pwittrock** [comment]
Also here:

https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.3-1.4-upgrade-cluster

**Comment by pwittrock** [comment]
And here:

https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.3-1.4-upgrade-master

**Comment by a-robinson** [comment]
You may want to unassign me, I no longer have the ability to do so.

**Comment by bprashanth** [comment]
quota issue unless it happens again
