### ISSUE TITLE
MetricsGrabber should grab all metrics from API server.

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#32704]
MetricsGrabber should grab all metrics from API server.

https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.2-1.4-upgrade-cluster

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.2-1.4-upgrade-cluster/6162

**Comment by gmarek** [comment]
It's a known issue, fix for which needs to be cherry-picked into 1.2 branch. I'll do this tomorrow.

**Comment by goltermann** [comment]
@gmarek Did you get to this cherrypick yet?

**Comment by gmarek** [comment]
No, sorry - I didn't have time. You can safely ignore this failure.

**Comment by davidopp** [comment]
failing in
https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-gci-1.2-gci-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-gci-1.2-cvm-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-cvm-1.2-gci-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-cvm-1.2-cvm-1.4-upgrade-cluster

**Comment by gmarek** [comment]
Yes, yes, I know. It's just a cherry pick thing, that I didn't have time to do. How important this is?

**Comment by pwittrock** [comment]
@gmarek The total number of failing tests that the owners have said "You can safely ignore this failure" is making it very difficult to clearly understand how close we are to our goal.  Can I just skip this test when it runs against a server 1.4.0 or greater?

**Comment by gmarek** [comment]
Fixed by #27265
