### ISSUE TITLE
[k8s.io] Deployment paused deployment should be ignored by the controller

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#32710]
[k8s.io] Deployment paused deployment should be ignored by the controller

https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.3-1.4-upgrade-cluster

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.3-1.4-upgrade-cluster/559

**Comment by pwittrock** [comment]
Also: here
https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.3-1.4-upgrade-master

**Comment by janetkuo** [comment]
Current observation: using 1.3 kubectl vs. 1.4 cluster, when you pause a deployment, and then delete its new RS, the pod is gone with the new RS, but a new pod will be created by that new RS.

**Comment by janetkuo** [comment]
It's likely due to proportional scale https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/sync.go#L321

After the rs reaper scales the rs down to 0, the deployment will scale it up back to 1 before the rs is deleted.

**Comment by janetkuo** [comment]
But this doesn't happen on 1.4 kubectl vs. 1.4 cluster

**Comment by janetkuo** [comment]
Adding these three lines in rs reaper will fix the error https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/stop.go#L289-L291

**Comment by janetkuo** [comment]
Per discussion with @pwittrock, closing the issue since the fix won't be targeting 1.4
