### ISSUE TITLE
Openstack Cinder volumes do not work with >v1.3.0

### ISSUE THREAD

**Issue by prg3** [kubernetes/kubernetes#32716]
Working version:
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.6+coreos.0", GitCommit:"323d2670999a67cc39009f19a3e09a024381cce2", GitTreeState:"clean", BuildDate:"", GoVersion:"", Compiler:"", Platform:""}

Not working version:
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6+coreos.0", GitCommit:"f6f0055b8e503cbe5fb7b6f1a2ee37d0f160c1cd", GitTreeState:"clean", BuildDate:"2016-08-29T17:01:01Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- Openstack Mitaka managed by SoftLayer/Bluebox
- OS Details:
NAME=CoreOS
ID=coreos
VERSION=1068.9.0
VERSION_ID=1068.9.0
BUILD_ID=2016-08-05-0455
PRETTY_NAME="CoreOS 1068.9.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

- **Kernel** (e.g. `uname -a`):
Linux kube-ict-worker-4 4.6.3-coreos #2 SMP Fri Aug 5 04:51:16 UTC 2016 x86_64 Intel Xeon E312xx (Sandy Bridge) GenuineIntel GNU/Linux

- **Install tools**:
Custom Ansible
- **Others**:

**What happened**:
If I use the example mysql-cinder pod on the 1.2.6 (and any 1.2 variant) I am able to mount the storage and it works just fine, however when I use the same configuration on a cluster upgraded to 1.3.x I get the following errors related to cinder:

  FirstSeen	LastSeen	Count	From				SubobjectPath		Type		Reason		Message
  ---------	--------	-----	----				-------------		--------	------		-------
  11m		11m		1	{default-scheduler }					Normal		Scheduled	Successfully assigned mysql-1.3.0 to kube-ict-worker-4
  11m		11m		1	{kubelet kube-ict-worker-4}	spec.containers{mysql}	Normal		Pulling		pulling image "mysql"
  10m		10m		1	{kubelet kube-ict-worker-4}	spec.containers{mysql}	Normal		Pulled		Successfully pulled image "mysql"
  10m		10m		1	{kubelet kube-ict-worker-4}	spec.containers{mysql}	Normal		Created		Created container with docker id 4dd5536431ea
  10m		10m		1	{kubelet kube-ict-worker-4}	spec.containers{mysql}	Normal		Started		Started container with docker id 4dd5536431ea
  3m		1m		2	{kubelet kube-ict-worker-4}				Warning		FailedMount	Unable to mount volumes for pod "mysql-1.3.0_default(4d3f2cf4-7ab2-11e6-a309-fa163ec4b608)": timeout expired waiting for volumes to attach/mount for pod "mysql-1.3.0"/"default". list of unattached/unmounted volumes=[mysql-persistent-storage]
  3m		1m		2	{kubelet kube-ict-worker-4}				Warning		FailedSync	Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "mysql-1.3.0"/"default". list of unattached/unmounted volumes=[mysql-persistent-storage]

The following 2 error messages appear repeating in the worker's log:

E0914 19:52:54.054545     676 nestedpendingoperations.go:254] Operation for "\"kubernetes.io/cinder/30434fbe-1a8e-4763-a97b-85abc821f2c2\"" failed. No retries permitted until 2016-09-14 19:54:54.054361455 +0000 UTC (durationBeforeRetry 2m0s). Error: Volume "kubernetes.io/cinder/30434fbe-1a8e-4763-a97b-85abc821f2c2" (spec.Name: "mysql-persistent-storage") pod "4d3f2cf4-7ab2-11e6-a309-fa163ec4b608" (UID: "4d3f2cf4-7ab2-11e6-a309-fa163ec4b608") is not yet attached according to node status.

I0914 19:52:54.044566     676 reconciler.go:220] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/cinder/30434fbe-1a8e-4763-a97b-85abc821f2c2" (spec.Name: "mysql-persistent-storage") pod "4d3f2cf4-7ab2-11e6-a309-fa163ec4b608" (UID: "4d3f2cf4-7ab2-11e6-a309-fa163ec4b608")

**What you expected to happen**:
Pod/Container should startup as before with 1.2.6

**How to reproduce it** (as minimally and precisely as possible):
Build cluster on Openstack Mitaka
Install Kubernetes with 1.2.6
Build pod as per mysql-cinder README
Create Pod
Observe success
Upgrade to 1.3.6
Reboot all systems to ensure 1.3.6 is cleanly running and no 1.2.6 mounts remain
Observe that pod will not start

**Anything else do we need to know**:

Including dump from graylog for all messages around the time of the test, file is named txt, but is csv.
[graylog-search-result-relative-900.txt](https://github.com/kubernetes/kubernetes/files/473356/graylog-search-result-relative-900.txt)

**Comment by Rotwang** [comment]
Hi, I'm experiencing the same issue with 1.3.5:

`I0915 15:03:58.174167   31092 reconciler.go:220] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/cinder/1ba10467-c263-4ebf-802c-9d0ea55f5a21" (spec.Name: "pvc-ed751e0c-7a80-11e6-870d-fa163e1a978d") pod "eeab905d-7a8a-11e6-870d-fa163e1a978d" (UID
: "eeab905d-7a8a-11e6-870d-fa163e1a978d")`

`E0915 15:03:58.176826   31092 nestedpendingoperations.go:254] Operation for "\"kubernetes.io/cinder/1ba10467-c263-4ebf-802c-9d0ea55f5a21\"" failed. No retries permitted until 2016-09-15 15:05:58.176796636 +0100 BST (durationBeforeRetry 2m0s). Error: Volume "kubernetes.io/
cinder/1ba10467-c263-4ebf-802c-9d0ea55f5a21" (spec.Name: "pvc-ed751e0c-7a80-11e6-870d-fa163e1a978d") pod "eeab905d-7a8a-11e6-870d-fa163e1a978d" (UID: "eeab905d-7a8a-11e6-870d-fa163e1a978d") is not yet attached according to node status.`

Funny thing that volume 1ba10467-c263-4ebf-802c-9d0ea55f5a21 is attached to a different node. After manually detaching mentioned volume kubelet attached it properly and the pod started.

**Comment by prg3** [comment]
Mine does this regardless of if the volume is mounted..

**Comment by prg3** [comment]
After more testing, specifically using kubelet directly on the OS, and changing the OS from CoreOS to Ubuntu, I found the problem went away. I believe this may be an issue with the CoreOS specific containers.

I'm going to close this one out.
