### ISSUE TITLE
kubectl: append current operation to user-agent

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#32725]
Sometimes we determine that old kubectl versions are incompatible for some operation. It would be super convenient if apiserver could just look at user-agent to see what kubectl is trying to do.

Example: rolling update issues RC create and deletes. It'd be great if we could block those without blocking ordinary create/delete.

**Comment by smarterclayton** [comment]
Interesting.  Dangerous.  But interesting.

**Comment by smarterclayton** [comment]
David went all out on his "we hate your user-agent" filter here https://github.com/openshift/origin/blob/9c76951e7de092a95029df46715671c4d4d355ea/pkg/cmd/server/api/v1/types.go#L344 - I'm sure he'd love to have more details to block people on.

**Comment by kargakis** [comment]
cc: @kubernetes/kubectl

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @lavalamp

**Comment by deads2k** [comment]
> This needs to be triaged as a release-blocker or not for 1.5 @lavalamp

Not a blocker for 1.5.
