### ISSUE TITLE
Include request body in authorization callback

### ISSUE THREAD

**Issue by trapexit** [kubernetes/kubernetes#32723]
The full payload of a request is needed in the authorization callback structure in order to be able to provide narrowly defined entitlements.

**Comment by liggitt** [comment]
request authorization only includes user info and resource info available from the HTTP verb and URL.

webhook admission or initialization can be used to introspect request contents to enforce policy decisions - https://kubernetes.io/docs/admin/extensible-admission-controllers/#overview
