### ISSUE TITLE
cAdvisor in Kube 1.4 is broken on RHEL systems when Kubelet running in a container - cgroup is out of order

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#32728]
https://github.com/google/cadvisor/issues/1461 results in Kubelet being unable to start inside a container because the cgroup order is reversed.  Blocks containerized kubelet from starting.

**Comment by smarterclayton** [comment]
@ncdc @mrunalp @derekwaynecarr

**Comment by smarterclayton** [comment]
Short synopsis from the linked issue - the cgroup is mounted under `cpuacct,cpu` inside a container, but the host mounts it as `cpu,cpuacct`.  libcontainer returns the first viable candidate it finds - mrunal and vish were discussing changing libcontainer to return all of them and letting cadvisor have more info to check them.

**Comment by qband** [comment]
Here is the solution that works.
```shell
  sudo mount -o remount,rw '/sys/fs/cgroup'
  sudo ln -s /sys/fs/cgroup/cpu,cpuacct /sys/fs/cgroup/cpuacct,cpu
```

**Comment by smarterclayton** [comment]
The fix was https://github.com/google/cadvisor/pull/1476

**Comment by smarterclayton** [comment]
Plus a Kube change
