### ISSUE TITLE
CRI: kuberuntime can't handle docker api version

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#32741]
umbrella issue: #31459

kuberuntime uses `semver` to ]parse the version string of the api version](https://github.com/kubernetes/kubernetes/blob/6538912013c16bf1e9c9b0ad1e418e9696849906/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L213) from the runtime. 
When using with docker, it complains that `1.23 is not in dotted-tri format`

Maybe we should just enforce that the api version returned by the runtime should be semver compatible.

/cc @feiskyer @Random-Liu @kubernetes/sig-node

**Comment by Random-Liu** [comment]
This is mentioned in https://github.com/kubernetes/kubernetes/issues/29252 `docker apiserver is not semver`. :)

**Comment by yujuhong** [comment]
> This is mentioned in #29252 docker apiserver is not semver. :)

Thanks for the reminder!

This blocks kubelet from starting up, so we should fix it first.

**Comment by Random-Liu** [comment]
@yujuhong I've checked the code, currently `APIVersion()` is only used in docker_manager.go when checking the docker version compatibility. It is not exposed to the user by any means, so it should be fine to make some change ourselves, such as adding a `.0`.

However, if we want to expose this to the user via `NodeInfo` in the future, it may make user confusing.
