### ISSUE TITLE
CRI: kuberuntime'd panic if pod is nil in killPodWithSyncResult

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#32742]
The comment states that the [`pod` argument may be nil for this function](https://github.com/kubernetes/kubernetes/blob/6538912013c16bf1e9c9b0ad1e418e9696849906/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L319), but the function [went on to use the `pod.UID` without checking](https://github.com/kubernetes/kubernetes/blob/6538912013c16bf1e9c9b0ad1e418e9696849906/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L338).

/cc @Random-Liu

**Comment by Random-Liu** [comment]
In fact, we can just use runningPod.ID instead https://github.com/kubernetes/kubernetes/blob/6538912013c16bf1e9c9b0ad1e418e9696849906/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L338.

**Comment by Random-Liu** [comment]
At least currently, `pod` is only used for printing, we can change the code to use `runningPod`. :)

**Comment by feiskyer** [comment]
> At least currently, pod is only used for printing, we can change the code to use runningPod. :)

+1
