### ISSUE TITLE
consider a dnspolicy optimized for fqdn lookups

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#32750]
Currently we have a resolvconf like: 

```
search default.svc.cluster.local svc.cluster.local cluster.local google.internal c.kubernetesdev.internal
nameserver 10.0.0.10
options ndots:5
```

so basically any lookup with less than 5 dots is translate to `lookup.default.svc.cluster.local`, you can also do `lookup.default` (ndots 2) and `lookup.default.svc` (ndots 3). 

However if you lookup google.com you run through 

```
; <<>> DiG 9.8.1-P1 <<>> +showsearch google.com
;google.com.default.svc.cluster.local. IN A
; <<>> DiG 9.8.1-P1 <<>> +showsearch google.com
;google.com.svc.cluster.local.  IN  A
; <<>> DiG 9.8.1-P1 <<>> +showsearch google.com
;google.com.cluster.local.  IN  A
; <<>> DiG 9.8.1-P1 <<>> +showsearch google.com
;google.com.google.internal.    IN  A
; <<>> DiG 9.8.1-P1 <<>> +showsearch google.com
;google.com.c.kubernetesdev.internal. IN    A
; <<>> DiG 9.8.1-P1 <<>> +showsearch google.com
;google.com.            IN  A
google.com.     258 IN  A   74.125.201.100
google.com.     258 IN  A   74.125.201.101
google.com.     258 IN  A   74.125.201.113
google.com.     258 IN  A   74.125.201.138
google.com.     258 IN  A   74.125.201.139
google.com.     258 IN  A   74.125.201.102
```

If a client knows they're only always using fqdn for in cluster services, we can probably rid of the search path and ndots.

**Comment by bprashanth** [comment]
@thockin says we can already avoid search path fun by appending "." to the hostname (with gethostbyname, unconfirmed cross dns resolver)

**Comment by thockin** [comment]
http://stackoverflow.com/questions/19480767/domain-names-with-dots-at-the-end

http://www.dns-sd.org/trailingdotsindomainnames.html

**Comment by caseydavenport** [comment]
Related: https://github.com/kubernetes/kubernetes/issues/33554

I think this issue can be closed.

/assign
