### ISSUE TITLE
kube-proxy has --master option while kubelet --api-server option for api servers

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes#32759]
**Is this a request for help?** No
**What keywords did you search in Kubernetes issues before filing this one?**  "kube-proxy --master options"
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

Basically there is inconsistency in naming the options in kubernetes binaries to specify the api-server. kubelet accepts --api-servers while kube-proxy and controller-manager accept --master flag while the flag still means the address of the api server. So why not be consistent is specifying the api-server option as --api-servers . This will help alleviate any confusion about what --master option means

**Comment by krmayankk** [comment]
@lavalamp does this belong in the generic api server cleanup category ?

**Comment by lavalamp** [comment]
No, this is a client problem. genericapiserver is a server component.

**Comment by bencord0** [comment]
Recent versions of the `kubelet` have also removed the `--api-server` option.
It appears that the consistent way to connect daemons to the apiserver is with the `--kubeconfig` flag.

Is the `--master` flag deprecated too?
