### ISSUE TITLE
Limit memory consumption of Fluentd

### ISSUE THREAD

**Issue by edsiper** [kubernetes/kubernetes#32762]
Reviewing the configuration of [Fluentd](http://fluentd.org) for different use cases in Kubernetes we see that it's always using in-memory buffering. Since we constantly see some concern about memory usage in Fluentd I would like to ask **why** by default in-memory buffering is used instead of file-system buffering:
- [Fluentd Elasticsearch Add-On Setup](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/td-agent.conf)
- [Fluentd-GCP Setup](https://github.com/kubernetes/kubernetes/blob/dae5ac482861382e18b1e7b2943b1b7f333c6a2a/cluster/addons/fluentd-gcp/fluentd-gcp-image/google-fluentd.conf)

Fluentd buffering mechanism is one of the key for reliability. When sending logs to third party backends/services like Elasticsearch, GCP, S3, etc.. there is always the possibility to face some networking issues or delays when transferring the data, if so, this may add some contention back in Fluentd and keeping buffering in the file system sounds better than keeping consuming memory for the same purpose. 

We would be happy to submit a PR with some improvements but having your feedback first would be appreciated. If you are interested into learn more about Fluentd buffering please refer to this document:

http://docs.fluentd.org/articles/buffer-plugin-overview

Some github issues relevant for this discussion:
- https://github.com/kubernetes/kubernetes/issues/29411
- https://github.com/kubernetes/kubernetes/issues/23782

**Comment by edsiper** [comment]
cc: @vishh

**Comment by vishh** [comment]
cc @piosz 

@edsiper The change you propose seems to make sense to me. Can you open a patch to update our fluentd configs?

**Comment by edsiper** [comment]
@vishh sure. One more question: since Fluentd will need to have access to the file system, what's the suggested absolute path for that purpose ?

**Comment by vishh** [comment]
Would `/var/log/` work?

**Comment by edsiper** [comment]
that one is perfect. thanks.

**Comment by piosz** [comment]
@edsiper thanks for rising this. @Crassirostris and I have talked about the similar issue/approach recently. We are also working on load test for fluentd which will help us to measure and tune the performance of the agent.

Your contribution would be really appreciated.

**Comment by Crassirostris** [comment]
Thanks, @edsiper 

Yes, we are in fact considering using file buffering mechanism right now. But we have several questions and concerns so far, which are not addressed directly by the documentation.

For example, there is a concern that using fluentd file buffering will multiply disk pressure from logs. Imagine same lines written by application then being read and written again to the different file by fluentd. Are there some mechanisms to avoid this situation? For example, keeping two buffer blocks in memory (top one and one before that for example)

Another question is what is considered by input offset in fluentd? Data sent by output plugin? Data written to buffers? Data read by input plugin?

For us it seems very important to reliably deliver all logs to the destinations. If for example server is under heavy pressure and fluentd can't handle this amount of logs for some time, discarding them or stopping reading doesn't seem like a viable option. In this situation, recommendation `We don’t recommend to use block action to avoid BufferQueueLimitError` can be safely ignored, right? Do we understand it correctly?

We would really appreciate if you could help us address those questions.

**Comment by edsiper** [comment]
@piosz thanks. Please let me know where I can find the stress tool you are building.

@Crassirostris here are the answers:

>For example, there is a concern that using fluentd file buffering will multiply disk pressure from logs. Imagine same lines written by application then being read and written again to the different file by fluentd. Are there some mechanisms to avoid this situation? For example, keeping two buffer blocks in memory (top one and one before that for example)

The current buffering mechanism in the file system do not keep a copy in memory, so you can assume that for now there is always a write(2) and a read(2)/write(2). Despite this model have worked well for years, we understand it could be better. At the moment we are discussing an hybrid mechanism similar to the one you proposed: use N as a max of chunks in memory, others go to the file system until they can be populated into memory. 

Note that when Fluentd retrieve the data from the input plugins, this information becomes structured and serialized, ready for delivery. So reading the buffer chunks is times cheaper than consume the same data from it original source.

>Another question is what is considered by input offset in fluentd? Data sent by output plugin? Data written to buffers? Data read by input plugin?

If you are referring to the in_tail plugin, it keeps a position of the latest consumed bytes from each file, so it can know from where to start reading again. Once the whole data is retrieved in Fluentd, it resides  in _chunks_ (where they resides either in memory or in the file system).  Output plugins consume _chunks_ .

>For us it seems very important to reliably deliver all logs to the destinations. If for example server is under heavy pressure and fluentd can't handle this amount of logs for some time, discarding them or stopping reading doesn't seem like a viable option. In this situation, recommendation We don’t recommend to use block action to avoid BufferQueueLimitError can be safely ignored, right? Do we understand it correctly?

When storing the buffer chunks, Fluentd needs to be aware about limits. If you hit a limit you need to decide what's your approach based in your needs. Since you cannot drop chunks the suggestion is to use very high limits, we have seen some production environments where their destinations are quite slow (third party network service) and the queue becomes full quickly,  on this case the workaround is just increase the limits (assuming you have enough storage space).

Please let us know if you have more questions/feedback, this is an exciting moment to improve logging :)

**Comment by edsiper** [comment]
@piosz @Crassirostris @vishh 

should we move to the file-system mode for now ?

**Comment by Crassirostris** [comment]
@edsiper Thanks a lot for the answers! Sorry for the long time without a reply

>Please let me know where I can find the stress tool you are building

I'll show you all our tools as soon as they're ready and tested, they aren't as for now.

>Note that when Fluentd retrieve the data from the input plugins, this information becomes structured and serialized, ready for delivery. So reading the buffer chunks is times cheaper than consume the same data from it original source.

In terms of CPU I believe, not IOPS. Since we don't have any numbers yet, I cannot say anything for sure, maybe it matters, maybe not. I hope to have a clear answer for that shortly.

>If you are referring to the in_tail plugin, it keeps a position of the latest consumed bytes from each file, so it can know from where to start reading again. Once the whole data is retrieved in Fluentd, it resides in chunks (where they resides either in memory or in the file system). Output plugins consume chunks .

OK, then if fluentd crashes before writing to the buffer, data is lost forever? I mean, after restart in_tail will not read that data again, it's offset will be greater than the lost line, right?

>When storing the buffer chunks, Fluentd needs to be aware about limits. If you hit a limit you need to decide what's your approach based in your needs. Since you cannot drop chunks the suggestion is to use very high limits, we have seen some production environments where their destinations are quite slow (third party network service) and the queue becomes full quickly, on this case the workaround is just increase the limits (assuming you have enough storage space).

Sure, it can be worked around, I just don't understand, why are you against pausing reading for some time? It won't be sent anyway, why read from input source before buffer space is freed, consume resources (mem/disk)? Maybe I'm missing something?

>should we move to the file-system mode for now ?

I think we have to make a weighted decision after we collected and analyzed some data. Generally I strongly agree that file buffering is better, but we need some data to prove a point.

**Comment by edsiper** [comment]
@Crassirostris 

> OK, then if fluentd crashes before writing to the buffer, data is lost forever? I mean, after restart in_tail will not read that data again, it's offset will be greater than the lost line, right?

The current implementation of Fluentd does:

1. in_tail read lines from file
2. in_tail update position entry
3. emit events (parsed from lines) into output (buffer) plugins

if Fluentd crashes between 2 and 3, Fluentd will miss the lines that were not saved on disk. I raised the concerns of this case internally and likely this can be improved. 

>Sure, it can be worked around, I just don't understand, why are you against pausing reading for some time? It won't be sent anyway, why read from input source before buffer space is freed, consume resources (mem/disk)? Maybe I'm missing something?

oh, I misunderstood your comment previously. I am not against pausing in_tail when the queue becomes full. Fluentd have a configuration property called [buffer_queue_full_action](http://docs.fluentd.org/articles/buffer-plugin-overview#bufferqueuefullaction) and it have 3 modes available: exception, block and drop_oldest_chunk. If set to _block_, in_tail will pause and resume once the buffer queue have enough space again. 

Now about the suggestion _We don’t recommend to use block action to avoid BufferQueueLimitError_, is merely because end-users try to bypass the error but not focus in the real problem, most of the time is about settings in the output plugin. I will make sure that documentation part becomes updated to avoid future confusions.

**Comment by Crassirostris** [comment]
@edsiper

OK, thank you very much for you effort!

Will update this issue with the new data ASAP.

**Comment by Crassirostris** [comment]
Hi @edsiper 

I'm providing you with an update:

I run some load tests and encountered sudden problem. While memory buffering fails with oom, file buffering also doesn't work very well. It keeps writing those lines

```
2016-10-05 08:52:07 +0000 [warn]: 'block' action stops input process until the buffer full is resolved. Check your pipeline this action is fit or not
2016-10-05 08:52:07 +0000 [warn]: 'block' action stops input process until the buffer full is resolved. Check your pipeline this action is fit or not
2016-10-05 08:52:09 +0000 [error]: fluentd main process died unexpectedly. restarting.
```

The configuration I run on:

* 1 node
* 10 pods
* 200 lines/sec/pod, each line ~100 bytes for a minute

200 * 10 * 60 * 100 ~ 12 MB, it shouldn't have even met buffer capacity, which is 48 MB, according to `google-fluentd.conf`

```
buffer_chunk_limit 2M
buffer_queue_limit 24
```

Is that the reason why you discourage using `block` mode? :)

**Comment by Crassirostris** [comment]
Another thing I don't understand is why fluentd creates more buffer files than indicated in config. Right now

```
$ ls /var/log/fluentd* -lh
-rw-r--r-- 1 root root 2.0M Oct  5 10:21 /var/log/fluentd.all.buffer..b53e1b8b2a3fed62f.log
-rw-r--r-- 1 root root 2.0M Oct  5 10:20 /var/log/fluentd.all.buffer..q53e1b831cb0de61d.log
-rw-r--r-- 1 root root 2.0M Oct  5 10:20 /var/log/fluentd.all.buffer..q53e1b868e12598e9.log
-rw-r--r-- 1 root root 2.0M Oct  5 10:20 /var/log/fluentd.all.buffer..q53e1b869993f9adc.log
-rw-r--r-- 1 root root 2.0M Oct  5 10:20 /var/log/fluentd.all.buffer..q53e1b86d3b55b657.log
-rw-r--r-- 1 root root 2.0M Oct  5 10:20 /var/log/fluentd.all.buffer..q53e1b86da6a5b68a.log
-rw-r--r-- 1 root root 2.0M Oct  5 10:20 /var/log/fluentd.all.buffer..q53e1b870c32ffc41.log
-rw-r--r-- 1 root root 2.0M Oct  5 10:21 /var/log/fluentd.all.buffer..q53e1b87133f11535.log
-rw-r--r-- 1 root root 2.0M Oct  5 10:21 /var/log/fluentd.all.buffer..q53e1b88ad048c7d8.log
-rw-r--r-- 1 root root 267K Oct  5 10:27 /var/log/fluentd.buffer..b53e1b831bc5eecbf.log
-rw-r--r-- 1 root root 2.0M Oct  5 10:18 /var/log/fluentd.buffer..q53e1b80477b4e6ee.log
-rw-r--r-- 1 root root 2.0M Oct  5 10:18 /var/log/fluentd.buffer..q53e1b807225718d4.log
-rw-r--r-- 1 root root 2.0M Oct  5 10:18 /var/log/fluentd.buffer..q53e1b80af8953b0e.log
-rw-r--r-- 1 root root 2.0M Oct  5 10:18 /var/log/fluentd.buffer..q53e1b80c9150884d.log
-rw-r--r-- 1 root root 2.0M Oct  5 10:19 /var/log/fluentd.buffer..q53e1b8144ac9aad9.log
-rw-r--r-- 1 root root 2.0M Oct  5 10:19 /var/log/fluentd.buffer..q53e1b81cc1d11baa.log
-rw-r--r-- 1 root root 2.0M Oct  5 10:19 /var/log/fluentd.buffer..q53e1b824b9c2aafe.log
-rw-r--r-- 1 root root 2.0M Oct  5 10:19 /var/log/fluentd.buffer..q53e1b82a7e359ce3.log
-rw-r--r-- 1 root root 2.0M Oct  5 10:19 /var/log/fluentd.buffer..q53e1b82e83011f65.log
-rw-r--r-- 1 root root 2.0M Oct  5 10:19 /var/log/fluentd.buffer..q53e1b82f452eabee.log
```

```
<match kubernetes.**>
  type google_cloud

  buffer_type file
  buffer_path /var/log/fluentd.buffer
  flush_at_shutdown true
  buffer_queue_full_action block

  buffer_chunk_limit 2M
  buffer_queue_limit 2

  flush_interval 5s
  max_retry_wait 30
  disable_retry_limit
  num_threads 8
</match>

<match **>
  type google_cloud
  detect_subservice false

  buffer_type file
  buffer_path /var/log/fluentd.all.buffer
  flush_at_shutdown true
  buffer_queue_full_action block

  buffer_chunk_limit 2M
  buffer_queue_limit 2

  flush_interval 5s
  max_retry_wait 30
  disable_retry_limit
  num_threads 8
</match>
```

What am I doing wrong?

**Comment by tagomoris** [comment]
As far as I checked the Fluentd v0.12.29 behavior for `buffer_queue_limit 2` and `buffer_queue_full_action block` with `in_tail` and `out_forward`(destination unreachable: `#write` always fails), Fluentd created 2 queued buffer chunk file and 1 buffer chunk file (to be queued - blocked).
@Crassirostris Yours might be a bug of any specific situation... Could you show me the log of Fluentd just after the process started?

**Comment by Crassirostris** [comment]
@tagomoris These 3 lines repeat over and over again, nothing else in container's log

```
2016-10-05 12:51:10 +0000 [warn]: 'block' action stops input process until the buffer full is resolved. Check your pipeline this action is fit or not
2016-10-05 12:51:10 +0000 [warn]: 'block' action stops input process until the buffer full is resolved. Check your pipeline this action is fit or not
2016-10-05 14:14:58 +0000 [error]: fluentd main process died unexpectedly. restarting.
```

There're several input plugins, maybe that's the issue?

The file buffer plugin is the only thing I changed in these files
* https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-image/google-fluentd.conf
* https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-image/google-fluentd-journal.conf

**Comment by tagomoris** [comment]
Oh, really? It should be executed as quiet mode...
@Crassirostris do you know the actual `$FLUENTD_ARGS` or can you modify the options (it should include `-q`) to remove `-q` or to use `-v` instead?
INFO logs should have many information to identify the root cause.

**Comment by tagomoris** [comment]
Anyway, I don't recommend `buffer_queue_full_action block` for most cases, because:
* for `in_tail`, we cannot detect 2 times log rotation while blocking
* for other plugins (e.g., `in_forward`), it causes denial of services, and other issues will occur in data source side

**Comment by Crassirostris** [comment]
@tagomoris So I enabled verbose debugging, do you see something suspicious?

```
2016-10-05 18:02:49 +0000 [error]: fluent/supervisor.rb:159:start: fluentd main process died unexpectedly. restarting.
2016-10-05 18:02:49 +0000 [info]: fluent/supervisor.rb:331:supervise: starting fluentd-0.12.23
2016-10-05 18:02:50 +0000 [info]: fluent/engine.rb:126:block in configure: gem 'fluent-mixin-config-placeholders' version '0.4.0'
2016-10-05 18:02:50 +0000 [info]: fluent/engine.rb:126:block in configure: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2016-10-05 18:02:50 +0000 [info]: fluent/engine.rb:126:block in configure: gem 'fluent-plugin-google-cloud' version '0.5.2'
2016-10-05 18:02:50 +0000 [info]: fluent/engine.rb:126:block in configure: gem 'fluent-plugin-mongo' version '0.7.12'
2016-10-05 18:02:50 +0000 [info]: fluent/engine.rb:126:block in configure: gem 'fluent-plugin-record-reformer' version '0.8.1'
2016-10-05 18:02:50 +0000 [info]: fluent/engine.rb:126:block in configure: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.4'
2016-10-05 18:02:50 +0000 [info]: fluent/engine.rb:126:block in configure: gem 'fluent-plugin-s3' version '0.6.5'
2016-10-05 18:02:50 +0000 [info]: fluent/engine.rb:126:block in configure: gem 'fluent-plugin-scribe' version '0.10.14'
2016-10-05 18:02:50 +0000 [info]: fluent/engine.rb:126:block in configure: gem 'fluent-plugin-systemd' version '0.0.3'
2016-10-05 18:02:50 +0000 [info]: fluent/engine.rb:126:block in configure: gem 'fluent-plugin-td' version '0.10.28'
2016-10-05 18:02:50 +0000 [info]: fluent/engine.rb:126:block in configure: gem 'fluent-plugin-td-monitoring' version '0.2.2'
2016-10-05 18:02:50 +0000 [info]: fluent/engine.rb:126:block in configure: gem 'fluent-plugin-webhdfs' version '0.4.1'
2016-10-05 18:02:50 +0000 [info]: fluent/engine.rb:126:block in configure: gem 'fluentd' version '0.12.23'
2016-10-05 18:02:50 +0000 [info]: fluent/agent.rb:128:add_match: adding match pattern="fluent.**" type="null"
2016-10-05 18:02:50 +0000 [info]: fluent/agent.rb:128:add_match: adding match pattern="reform.**" type="record_reformer"
2016-10-05 18:02:50 +0000 [info]: fluent/agent.rb:128:add_match: adding match pattern="kubernetes.**" type="google_cloud"
2016-10-05 18:02:50 +0000 [warn]: fluent/buffer.rb:164:configure: 'block' action stops input process until the buffer full is resolved. Check your pipeline this action is fit or not
2016-10-05 18:02:50 +0000 [info]: plugin/out_google_cloud.rb:519:block in detect_platform: Detected GCE platform
2016-10-05 18:02:50 +0000 [info]: plugin/out_google_cloud.rb:290:configure: Logs viewer address: https://console.developers.google.com/project/google.com:vmik-k8s-testing/logs?service=container.googleapis.com&k
ey1=instance&key2=3959967678941660133
2016-10-05 18:02:50 +0000 [info]: fluent/agent.rb:128:add_match: adding match pattern="**" type="google_cloud"
2016-10-05 18:02:50 +0000 [warn]: fluent/buffer.rb:164:configure: 'block' action stops input process until the buffer full is resolved. Check your pipeline this action is fit or not
2016-10-05 18:02:50 +0000 [info]: plugin/out_google_cloud.rb:519:block in detect_platform: Detected GCE platform
2016-10-05 18:02:50 +0000 [info]: plugin/out_google_cloud.rb:290:configure: Logs viewer address: https://console.developers.google.com/project/google.com:vmik-k8s-testing/logs?service=compute.googleapis.com&key
1=instance&key2=3959967678941660133
2016-10-05 18:02:50 +0000 [info]: fluent/root_agent.rb:147:add_source: adding source type="tail"
...
2016-10-05 18:02:50 +0000 [info]: fluent/root_agent.rb:147:add_source: adding source type="systemd"
2016-10-05 18:02:50 +0000 [info]: fluent/engine.rb:133:configure: using configuration file: <ROOT>
...
2016-10-05 18:02:50 +0000 [info]: plugin/in_tail.rb:515:initialize: following tail of ...
...
2016-10-05 18:02:50 +0000 [debug]: fluent/buffer.rb:212:rescue in block in emit: buffer queue is full. Wait 1 second to re-emit events
2016-10-05 18:02:51 +0000 [debug]: fluent/buffer.rb:212:rescue in block in emit: buffer queue is full. Wait 1 second to re-emit events
2016-10-05 18:02:53 +0000 [info]: fluent/supervisor.rb:348:supervise: process finished code=9
2016-10-05 18:02:53 +0000 [error]: fluent/supervisor.rb:159:start: fluentd main process died unexpectedly. restarting.
```

**Comment by Crassirostris** [comment]
>Anyway, I don't recommend buffer_queue_full_action block for most cases

Yeah, sure, but in this case, when we have only in_tail and want robustness and some delivery guarantees, I don't see any other choice. If you can offer us something instead, it will be really great! :)

**Comment by tagomoris** [comment]
I wanted to see dumped configuration to see what you specified is correctly read/parsed or not :P

**Comment by Crassirostris** [comment]
@tagomoris True, you were right, thanks! After I thoughtfully read through config, turned out I changed only one config file and fluentd used the other.

With that correction (buffers limit = 2) fluentd managed to survive 200 lines/sec and died of the same reason on 300 lines/sec (but once, without death loop)

I'll try to figure out now, what is the amount of memory fluentd requires over those 200 MB to function without fails. 18 MB over 1 minute is still not a load that should crash fluentd.

**Comment by Crassirostris** [comment]
Meanwhile, 300 lines/sec/pod

Buffers:

```
vmik@e2e-test-vmik-minion-group-8csk ~ $ ls -lh /var/log/fluentd*
-rw-r--r-- 1 root root 2.0M Oct  6 12:27 /var/log/fluentd.all.buffer..b53e3168d8815c412.log
-rw-r--r-- 1 root root 1.8M Oct  6 12:26 /var/log/fluentd.all.buffer..q53e31685c7f70245.log
-rw-r--r-- 1 root root 2.0M Oct  6 12:26 /var/log/fluentd.all.buffer..q53e3168b78addd48.log
-rw-r--r-- 1 root root 2.0M Oct  6 12:29 /var/log/fluentd.buffer..b53e316841a37590d.log
-rw-r--r-- 1 root root 213K Oct  5 18:51 /var/log/fluentd.buffer..q53e22ab8214c9d94.log-20161006-1475712004.gz
-rw-r--r-- 1 root root 2.0M Oct  6 12:26 /var/log/fluentd.buffer..q53e3167a474567f1.log
-rw-r--r-- 1 root root 2.0M Oct  6 12:26 /var/log/fluentd.buffer..q53e31680418e3a55.log
```

In fluentd logs:

https://gist.github.com/Crassirostris/2b63ef1f2762e300dab33022b591f5e1

What's that `.gz` file?

**Comment by Crassirostris** [comment]
With 500 MB of memory, fluentd was able to handle 6000 lines/sec. During this time, it was consuming no more than 450 MB of memory.

On 7000 lines/sec — OOM and hung up process (doesn't write to log, doesn't pick up new files). This is probably the worst thing that could've happened.

@tagomoris @edsiper  How does one probe that fluentd is working and not hung up? And what can consume 500 MB of memory for ~50 MB of logs over a minute?

**Comment by tagomoris** [comment]
I think that we can detect where that memory consumption came from by modifying output plugin.

@Crassirostris can you modify all `<match>` sections to use `@type null`?
If Fluentd processes with `@type null` doesn't consume not so much memory, it's came from buffering (of Fluentd core) or fluent-plugin-google-cloud.

I heard that representable gem consumes highly much memory (500MB for 2.4MB JSON HTTP response), and fluent-plugin-google-cloud depends on that gem (via google-api-client gem).

**Comment by Crassirostris** [comment]
@tagomoris Thanks! Without this output plugin memory is indeed has not exceeded 60MB

The next step is clear then, I will update this issue when fluent-plugin-google-cloud will be fixed

**Comment by tagomoris** [comment]
@Crassirostris Thank you! It's great report for me.

**Comment by piosz** [comment]
FYI @igorpeshansky @rbuskens

**Comment by Crassirostris** [comment]
@igorpeshansky @rbuskens I will provide you with a clear issue in https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud shortly

**Comment by edsiper** [comment]
I've found that memory fragmentation is the root cause of high-memory usage on Fluentd. After doing some tests and comparing _libc memory allocator_ v/s _Jemalloc_ there is a big difference. Please refer to these findings:

- https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/87#issuecomment-253853691
- https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/87#issuecomment-253862785

**Comment by piosz** [comment]
Thanks a lot @edsiper for debugging. @Crassirostris could you please try to use Jemalloc and post an update?

**Comment by igorpeshansky** [comment]
Note that the google-fluentd defaults to jemalloc. So unless Kubernetes changed the default settings, the fluentd container should be using jemalloc.

**Comment by edsiper** [comment]
Is there a way to query the process maps ? like:

```
$ cat /proc/$fluentd_pid/maps | grep jemalloc
7f4c00b78000-7f4c00bd3000 r-xp 00000000 08:04 30146570  /opt/jemalloc-4.2.1/lib/libjemalloc.so.2
7f4c00bd3000-7f4c00dd3000 ---p 0005b000 08:04 30146570  /opt/jemalloc-4.2.1/lib/libjemalloc.so.2
7f4c00dd3000-7f4c00dd5000 r--p 0005b000 08:04 30146570  /opt/jemalloc-4.2.1/lib/libjemalloc.so.2
7f4c00dd5000-7f4c00dd6000 rw-p 0005d000 08:04 30146570  /opt/jemalloc-4.2.1/lib/libjemalloc.so.2
```

**Comment by edsiper** [comment]
note: more progress here:

https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/87#issuecomment-254660087

**Comment by Crassirostris** [comment]
Well, I think we're done with this issue, at least for this cycle, @edsiper or @piosz feel free to close it, I should've done it in the PR.

**Comment by edsiper** [comment]
thanks @Crassirostris !.
