### ISSUE TITLE
Headless services with selectors need ports defined.

### ISSUE THREAD

**Issue by runseb** [kubernetes/kubernetes#32766]
Tested on GKE (v1.3.6).

I have some Pods running for which I don't know before end what ports will be used.

To expose them via a service, I tried to use Headless services with selectors [1].

It seems that simply using clusterIP=None and ports=null does not trigger generation of endpoints.

We have to define ports in the headless service for the pod IPs to get in the endpoints.

typically:

```
$ kubectl get pods -lservice=front-end
NAME                         READY     STATUS    RESTARTS   AGE
front-end-1567472915-tei91   1/1       Running   0          12m
$ kubectl get svc -lapp=sockshop
NAME        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
front-end   None         <none>                  11m
$ kubectl get endpoints -lapp=sockshop
NAME        ENDPOINTS   AGE
front-end   <none>      11m
$ more svc.yaml 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sockshop
  name: front-end
spec:
  clusterIP: None
  ports: null
  selector:
    service: front-end
```

This is needed for us to solve https://github.com/skippbox/kompose/issues/146

[1] http://kubernetes.io/docs/user-guide/services/#with-selectors
[2] http://stackoverflow.com/questions/39469202/headless-services-with-selector-does-not-get-endpoint?stw=2

**Comment by thockin** [comment]
Replaced with https://github.com/kubernetes/kubernetes/issues/32796 and https://github.com/kubernetes/kubernetes/issues/32795
