### ISSUE TITLE
Zone label should not contain region (AWS cloud provider)

### ISSUE THREAD

**Issue by sirhopcount** [kubernetes/kubernetes#32775]
Hi,

I just noticed that the nodes on our (AWS) cluster also have the region in the zone label: 

```
failure-domain.beta.kubernetes.io/region=eu-west-1
failure-domain.beta.kubernetes.io/zone=eu-west-1a
```

This doesn't make sense to me as it prevents you from using the zone label as a selector without knowing the region upfront (which is not always the case). 

If for example you want to duplicate a k8s cluster on a different region it would require me to edit the manifest and change the zone label everywhere to contain the new region.

So say you have 2 nodes in separate availability zones and want to deploy a pod in availability zone **a** I would  expect to just specify the zone as **a**

```
    nodeSelector:
        failure-domain.beta.kubernetes.io/zone=a
```

If for some reason I need to also specify the region you can alway use the _failure-domain.beta.kubernetes.io/region_ label.

**Comment by hjacobs** [comment]
I personally would disagree partly here: the number of availability zones depends on the region, so how can you schedule something in AZ "c" in Frankfurt region ("eu-west-1") when it only has two availability zones as of now?

What I'm trying to say: you generally need to know the target region in order to properly select a zone (obviously for special cases hardcoded values like "a" always work).

**Comment by justinsb** [comment]
Yes, can you comment on what you are trying to achieve @sirhopcount ?  Normally the k8s scheduler should just "do the right thing" when it comes to these labels i.e. they are used by the scheduler, and you can target them if you have to, but you shouldn't need to.

**Comment by sirhopcount** [comment]
@hjacobs you're partially right, it does restrict you to which regions you can use but there are multiple regions which have either 2 or 3 AZ's.

@justinsb We already fixed it by applying our own labels but this is a simple use case (there are better ways of deploying this):

Say I want to build a simple 3 node elasticsearch cluster with one node in each AZ. I create a VPC, subnets, ASG's, etc with (in our case) terraform. In terraform I specify a variable called _region_ so I can easily redeploy (or copy) this terraform environment without needing to change the region in the code.

Next, I would create 3 separate manifests files (es-deploy-az-X.yaml), one deployment for each AZ and using a nodeSelector for the zone. As things are the nodeSelector would look something like:

```
    nodeSelector:
        failure-domain.beta.kubernetes.io/zone=eu-west-1b
```

Now disaster strikes and I need to redeploy in a different region or (a more likely use case) I need to deploy the exact same setup for a new customer but in a different region.

So I would just have to change the terraform region variable and run terraform, and deploy the k8s cluster and use the manifests to create the elasticsearch cluster. 

But than k8s informs me it cannot deploy the pod because the no matching nodes can be found because the _failure-domain.beta.kubernetes.io/zone_ label has the region specified in it and that has changed. 

Now of course its just of matter of changing the manifest and updating the label but my point is, the manifest should be as agnostic as possible. If I change from one region to another I shouldn't be required to update the labels because the zone labels also includes the region.

It just doesn't make sense seeing there is a label specially for the region (_domain.beta.kubernetes.io/region_) which I can use if I need to specify the region.

**Comment by justinsb** [comment]
@sirhopcount if you use a PetSet it should automatically distribute the volumes and pods across the available zones. Right now the way we get the "available zones" is imperfect, but it works as long as you have nodes running in all zones.

**Comment by sirhopcount** [comment]
@justinsb It was just an example, as I said there are better ways to configure it. 

My main point is code reuse, in our entire stack (terraform, fleet, etc) the region and the availability zone are two separate entities. If we want to deploy the same stack in a different region (with the same specifications) we just have to change one variable, the region.

Except for the k8s manifests, we need to sed through the directory and update the manifest that use a zone label because it's "hard-coded".

It just doesn't make sense to use the region in the zone label (or at least nobody seems to be able to explain why it is). It just seems to me that is a very restrictive measure without any clear advantage.

We already fixed this issue in our setup by deploying our own labeling solution so this is not a major issue for us anymore. If I can't convince you not to use the region in the AZ label the ticket can be closed as far as I am concerned.
