### ISSUE TITLE
How can I build a plugin or module to extend kubernetes  ? 

### ISSUE THREAD

**Issue by medhedifour** [kubernetes/kubernetes#32777]
I need to extend kubernetes using a module or a plugin which takes as input some data and parameters from master using kubernetes api, execute algorithms and process, and performs as output actions in master node using the kuberenetes api.

**Comment by dims** [comment]
@medhedifour Please see the following:

https://github.com/kubernetes/kubernetes/blob/master/docs/design/extending-api.md
http://www.devoperandi.com/kubernetes-automation-with-stackstorm-and-thirdpartyresources/
https://github.com/wercker/cronetes
https://github.com/kelseyhightower/kube-cert-manager

**Comment by medhedifour** [comment]
@dims 
Thanks a lot
