### ISSUE TITLE
Directory structure, or suite, for performance tests.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#32799]
Right now the e2e suite houses several `[Performance]` tests but most of those are behavior level tests and run on a per-PR basis.  We would like to add more performance tests but are uncertain if is makes sense to lump it all into the existing test suite vs. either 
- breaking it into it's own suite 
- creating a separate directory to house that set of e2es

thoughts? 

/cc @gmarek @wojtek-t @kubernetes/sig-testing

**Comment by wojtek-t** [comment]
@timothysc - which [Performance] tests are running as regular/per-PR tests?

**Comment by gmarek** [comment]
My understanding of the current setup is:
- there are two performance tests: Density and Load (with different variations like number of pods/node etc.)
- there a two ways of running them: normal (on real clusters) and kubemark
- we have only basic kubemark test running per-PR, only to make sure that the given PR doesn't break kubemark setup
- we run density and load post submit in various configurations - on 100 Node real clusters, and on various size of kubemark sizes. They're not blocking currently, but we're going to add kubemark-500 as a blocker in near future.

I'm still not clear what's the goal of this effort, but if having `test/e2e/performance` directory will satisfy you, then we can just move `load.go` and `density.go` there.

**Comment by timothysc** [comment]
> I'm still not clear what's the goal of this effort, but if having test/e2e/performance directory will satisfy you, then we can just move load.go and density.go there.

k, that should suffice.  

We have a number of other network saturation, logging saturation, service saturation tests we would like to fold over. 

/cc @jayunit100

**Comment by spiffxp** [comment]
Maybe way too early, but is this the sort of candidate for moving into the newly incubated `perf-tests`?

**Comment by timothysc** [comment]
This is done.
