### ISSUE TITLE
OpenStack LBaaSV2: controller-manager failover causes service downtime.

### ISSUE THREAD

**Issue by suonto** [kubernetes/kubernetes#32794]
### Bug Report

OpenStack LBaaSV2 integration

**Kubernetes version:** 1.3.7

**Environment**:
- **Cloud provider or hardware configuration**: OpenStack
- **OS** (e.g. from /etc/os-release): Centos7

**Behaviour**: Master failover causes loadbalancers to go into infinite create/delete loop and change ip addresses every time.

**Expected behaviour**: Service loadbalancers should update hosts (pool members). 

**Steps to reproduce**: Use controller-manager and scheduler election. Shutdown primary master (that runs controller-manager) and wait for election to happen. Observe loadbalancers.

**Additional info**: Behaviour in v1.3.6 was flawless. This is a critical OpenStack LBaaSV2 integration bug that will cause service downtime if not fixed.

**Comment by zhouhaibing089** [comment]
I can prove that the service ip would get recreated, but not sure it would happen infinitely. according to my last experience, it would not while I am using the LBaaS V1 api, In fact, I do not think that the service ip should be recreated, either.

**Comment by suonto** [comment]
I have 2 possible approaches to this:
1) Caller needs to stop feeding obsolete host list in retry attempts
2) Skip member creation for hosts upon failure. Hosts will be immediately updated afterwards anyway.
