### ISSUE TITLE
Endpoints controller demands ports for headless services

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#32796]
API validation explicitly allows headless services to not have ports, but we seem to have not updated endpoints controller to know this:

https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation.go#L2390

vs

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpoint/endpoints_controller.go#L389

Superficially this seems like an easy fix.  May be a candidate for 1.4.x

@sebgoa

**Comment by fraenkel** [comment]
@thockin What did you expect to happen? It will skip creating any EndpointSubsets. It handles having no ports.

**Comment by thockin** [comment]
I think it should create a Subset with a 0 port (or a dummy value).  We
don't currently represent port ranges, but if we did it would be (1-655356)
here.

On Thu, Sep 15, 2016 at 12:23 PM, Michael Fraenkel <notifications@github.com

**Comment by sebgoa** [comment]
correct, it should create a subset with the PodIP that match the service selector. 0 port would work (or even no port at all if endpoints could support that).

**Comment by fraenkel** [comment]
Looking at RepackSubsets, it will drop out endpoints with no ports so going with the 0 port is what I did.

**Comment by thockin** [comment]
Yeah, without trawling code (thanks!) It is not clear if a zero port would
work.  If I were clever, I would have written the validation to disallow 0,
because no-port-needed logic came later, and then would have expanded it to
make port=0 mean no-port-needed.

Simply trying it might be the best course, but we should audit kubectl, APi
validation, API defaulting, subset repacking, endpoints controller,
kube-proxy, and DNS server for correct behavior in the face of headless
without ports.  Clearly some of that is wrong today, no surprise if more of
it is wrong still :)

On Sep 16, 2016 10:57 AM, "Michael Fraenkel" <notifications@github.com>
wrote:

Looking at RepackSubsets, it will drop out endpoints with no ports so going
with the 0 port is what I did.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/32796#issuecomment-247665925>,
or mute the thread

**Comment by F21** [comment]
I just ran into this myself. A work around is to do something like this:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    run: my-svc
spec:
  clusterIP: None
  selector:
    run: my-svc
  ports:
```

**Comment by je-al** [comment]
Furthermore, kubectl needs some love:

```
➜  kube kubectl create service clusterip my-nginx-hl --clusterip='None' --tcp='80:80'
error: can not map ports with clusterip=None

➜  kube kubectl create service clusterip my-nginx-hl --clusterip='None'
service "my-nginx-hl" created

➜  kube kubectl describe svc/my-nginx-hl
Name:                   my-nginx-hl
Namespace:              default
Labels:                 app=my-nginx-hl
Selector:               app=my-nginx-hl
Type:                   ClusterIP
IP:                     None
Session Affinity:       None
No events.

➜  kube kubectl patch svc --type=json -p='[{"op":"replace","path":"/spec/selector","value":{"run":"my-nginx"}}]' my-nginx-hl                                                               <<<
"my-nginx-hl" patched

➜  kube kubectl describe svc/my-nginx-hl
Name:                   my-nginx-hl
Namespace:              default
Labels:                 app=my-nginx-hl
Selector:               run=my-nginx
Type:                   ClusterIP
IP:                     None
Session Affinity:       None
No events.

➜  kube kubectl patch svc --type=json -p='[{"op":"replace","path":"/spec/ports","value":[{"name":"80-80","port":80, "targetPort":80,"procotol":"TCP"}]}]' my-nginx-hl
"my-nginx-hl" patched

➜  kube kubectl describe svc/my-nginx-hl
Name:                   my-nginx-hl
Namespace:              default
Labels:                 app=my-nginx-hl
Selector:               run=my-nginx
Type:                   ClusterIP
IP:                     None
Port:                   80-80   80/TCP
Endpoints:              172.17.0.5:80,172.17.0.6:80,172.17.0.7:80
Session Affinity:       None
No events.
```

P.S.: disregard the selector patching, that's an unrelated issue.

**Comment by jianzi123** [comment]
I would like to work on this issue

**Comment by thockin** [comment]
Any progress here?

**Comment by thockin** [comment]
Can we get an update?

**Comment by xiangpengzhao** [comment]
Seems like @fraenkel PR #32875 had fixed this main issue. But the PR was closed due to inactive for 90 days. If @fraenkel doesn't have plan to reopen it again and @jianzi123 doesn't have new progress, I'd like to pick it up. What I can think the work might be polishing PR #32875 and fixing https://github.com/kubernetes/kubernetes/issues/32796#issuecomment-270462724. I will also try to find out if there is something more to do per https://github.com/kubernetes/kubernetes/issues/32796#issuecomment-247797321.

@thockin WDYT?

**Comment by xiangpengzhao** [comment]
I send PR #47250. Hope we can fix this ASAP before 1.7.

**Comment by bowei** [comment]
@dchen1107 move to next milestone.

**Comment by dchen1107** [comment]
There is a pending pr to address this issue, not update if that is the right fix.

**Comment by xiangpengzhao** [comment]
yeah that PR is still under reviewing.

**Comment by bowei** [comment]
I took a look at the PR and its looks like there are still some outstanding review comments without an LGTM. It feel like this should be moved to the next milestone to be safe. Please comment if you disagree.

**Comment by marun** [comment]
Moving to 1.8.
