### ISSUE TITLE
KUBE_LOGGING_DESTINATION=elasticsearch does not work on GCI

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#32804]
E2E test `Cluster level logging using Elasticsearch [Feature:Elasticsearch] should check that logs from pods on all nodes are ingested into Elasticsearch` is failing in `kubernetes-e2e-gci-gce-es-logging` suite

**Comment by piosz** [comment]
Could you please provide some more info? What this suite is supposed to test? How can I reproduce locally?

cc @crassirostris

**Comment by freehan** [comment]
`kubernetes-e2e-gci-gce-es-logging` is the suite in question. 

It has been failing consistently. https://k8s-testgrid.appspot.com/google-gce#gci-gce-es-logging

**Comment by piosz** [comment]
What is this suite supposed to test? Kubernetes installation with master and nodes running on GCI?

@Crassirostris could you please take a look?

**Comment by Crassirostris** [comment]
Looking into it already, trying to reproduce

**Comment by Crassirostris** [comment]
Reproduced manually, will look at it closely tomorrow

How to reproduce:

* Set `KUBE_NODE_OS_DISTRIBUTION=gci`
* Run es_cluster_logging test

So yes, the only difference is the GCI as the node OS and this seems to be the case this suite is aimed for

**Comment by piosz** [comment]
This is still failing
