### ISSUE TITLE
CRI: expose optional runtime features

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#32803]
Meta-issue for CRI: #28789

For some features, kubelet checks if the underlying runtime supports such features and reject the pod if necessary. One example is the `sysctl` support. Right now, kubelet simply checks if (1) the runtime is docker, and (2) if docker version is higher than the minimum requirement. With CRI, checking runtime versions directly is no longer viable. One way to solve this is to ask runtime to expose a set of features it supports through CRI. E.g., an `Info` call can be added to CRI to retrieve a list of supported features. 

Thoughts? Objections? 

/cc @kubernetes/sig-node @thockin 

Note: sysctl is still an experimental feature and relies on pod annotations in the k8s API. However, the pod admission logic is already live in kubelet.

**Comment by yifan-gu** [comment]
@yujuhong Why checking runtime versions is not viable?

**Comment by feiskyer** [comment]
+1 for this.

> @yujuhong Why checking runtime versions is not viable?

@yifan-gu Do you mean extend `Version()` API to include features? I think that's better than adding a new API.

**Comment by thockin** [comment]
Do we need this as an explicit API?  Why not just pass sysctl to the
runtime, and if it doesn't support them, it can either reject the request
or log-and-run-anyway...

**Comment by feiskyer** [comment]
> Do we need this as an explicit API?  Why not just pass sysctl to the
> runtime, and if it doesn't support them, it can either reject the request
> or log-and-run-anyway...

@thockin One benefit is failing early before calling runtime API if features are not supported.

**Comment by yifan-gu** [comment]
> @yifan-gu Do you mean extend Version() API to include features? I think that's better than adding a new API.

Not saying including features in versions. My thought is the version itself is sufficient to provide information on what features are supported or not (e.g. docker 1.1x support feature a, b, c, etc)

Once the runtime tells us the version, we can infer what features are supported or not, right?

**Comment by Random-Liu** [comment]
> Not saying including features in versions. My thought is the version itself is sufficient to provide information on what features are supported or not (e.g. docker 1.1x support feature a, b, c, etc)

@yifan-gu Versions of different runtime mean different things. if we just let runtime return its version, kubelet must have some runtime specific logic to figure out what docker 1.1x support, what rkt 1.0x support etc.

**Comment by yifan-gu** [comment]
> @yifan-gu Versions of different runtime mean different things. if we just let runtime return its version, kubelet must have some runtime specific logic to figure out what docker 1.1x supports, what rkt 1.0x supports etc.

Fair enough.

**Comment by thockin** [comment]
I am not sure that is a compelling enough reason on its own.

**Comment by yujuhong** [comment]
> Do we need this as an explicit API?  Why not just pass sysctl to the
> runtime, and if it doesn't support them, it can either reject the request
> or log-and-run-anyway...

1. kubelet right now "rejects" a pod if the runtime doesn't support sysctl. To achieve the same effect, we'll need to either a) ask runtime to return a list of supported features or b) add a new "error" indicating the pod is not supported so that kubelet can reject the pod. 
2. Handling version skew explicitly. If `sysctl` is added to version 1.1, an older server/runtime, e.g., 1.0, would simply ignore the newly added fields and not return errors. This means that kubelet will have to check what CRI version the runtime is using and whether a particular feature is supported in this version.

**Comment by thockin** [comment]
On Mon, Sep 19, 2016 at 2:38 PM, Yu-Ju Hong <notifications@github.com> wrote:
>
> Do we need this as an explicit API? Why not just pass sysctl to the
> runtime, and if it doesn't support them, it can either reject the request
> or log-and-run-anyway...
>
> kubelet right now "rejects" a pod if the runtime doesn't support sysctl. To achieve the same effect, we'll need to either a) ask runtime to return a list of supported features or b) add a new "error" indicating the pod is not supported so that kubelet can reject the pod.

This is what I was thinking

> Handling version skew explicitly. If sysctl is added to version 1.1, an older server/runtime, e.g., 1.0, would simply ignore the newly added fields and not return errors. This means that kubelet will have to check what CRI version the runtime is using and whether a particular feature is supported in this version.

Kubelet should NOT be checking versions of plugins.  It must be
neutral.  The question is which behavior is correct?  Rejecting pods
that use unsupported features or ignoring the features?  Note this has
implications for defaulting logic, too.  If we reject, we can never
default a new field lest we risk the kubelet rejecting it with version
skew (which empirically is the normal state of many clusters).

**Comment by yujuhong** [comment]
Ignoring features may be ok in some cases, and I think this is what we do in k8s today (older kubelets ignore new features). 

On the other hand, if the feature is related to security (e.g., apparmor?), letting the runtime silently ignore it seems dangerous.

**Comment by thockin** [comment]
Can we somehow close the loop?  Maybe pass back the runtime's pod, then do
a diff or something?   I guess I am OK with feature flags, but I am worried
about the defaulting problem.

**Comment by yujuhong** [comment]
> Can we somehow close the loop?  Maybe pass back the runtime's pod, then do
> a diff or something?   I guess I am OK with feature flags, but I am worried
> about the defaulting problem.

Let's break down the problem a bit more. 

1. Assume there is no version skew, does runtime need to support all the fields listed in the container/sandbox configuration? 

2. With version skew, how can kubelet know whether a specific feature is enabled?

apiserver <-> kubelet doesn't have problem (1). I'd like to enforce that runtimes should support all fields in the config and it should reject the request if it can't. This does have the implication that every time we want to add a new feature, we'd have to force all runtimes to support this (or they cannot upgrade). cc @kubernetes/sig-rktnetes 

As for (2), we also don't handle this in apiserver <-> kubelet in general, with some exceptions. 
-  kubelet checks the docker version and reject pods that requests `sysctl` if the runtime doesn't support it.
-  For apparmor, kubelet writes an annotation on the pod object to *acknowledge* that kubelet enables the apparmor profile on the pod. 

This either requires kubelet to check runtime+version, or the runtime to ACK back. If (1) is true, kubelet could potentially just check the API version that the runtime uses and determine whether the feature is supported (but it wouldn't be able to reject a pod outright without trying the request first).

**Comment by thockin** [comment]
On Mon, Sep 26, 2016 at 11:54 AM, Yu-Ju Hong <notifications@github.com> wrote:
>
> Can we somehow close the loop? Maybe pass back the runtime's pod, then do
> a diff or something? I guess I am OK with feature flags, but I am worried
> about the defaulting problem.
>
> Let's break down the problem a bit more.
>
> Assume there is no version skew, does runtime need to support all the fields listed in the container/sandbox configuration?
>
> With version skew, how can kubelet know whether a specific feature is enabled?
>
> apiserver <-> kubelet doesn't have problem (1). I'd like to enforce that runtimes should support all fields in the config and it should reject the request if it can't. This does have the implication that every time we want to add a new feature, we'd have to force all runtimes to support this (or they cannot upgrade). cc @kubernetes/sig-rktnetes

Will this cause huge friction?Our API is not perfectly abstract, and
maybe there will be things that don't make sense on some runtimes?  I
don't know here..

> As for (2), we also don't handle this in apiserver <-> kubelet in general, with some exceptions.

We already have the security problem.  If kubelet is 1.3.x and reads a
Pod from apiserver that sets AppArmor, it will happily start the pod
without AppArmor.  Won't it?  Why is that acceptable but kubelet <->
shim version skew is not?  And if it is OK to drop fields in the face
of version skew, why is it not OK to drop fields when a runtime
doesn't support it?

> kubelet checks the docker version and reject pods that requests sysctl if the runtime doesn't support it.
> For apparmor, kubelet writes an annotation on the pod object to acknowledge that kubelet enables the apparmor profile on the pod.
>
> This either requires kubelet to check runtime+version, or the runtime to ACK back. If (1) is true, kubelet could potentially just check the API version that the runtime uses and determine whether the feature is supported (but it wouldn't be able to reject a pod outright without trying the request first).

**Comment by euank** [comment]
This is also partly a distribution problem I think, or at least can be solved by making sufficiently opinionated distribution coupling decisions.

If we can mandate "the shim is tightly tied to kubelet in distribution and version", then things become *much* easier.
Some of the benefit of having external remote runtimes is that their development and release can be decoupled a bit, but it doesn't have to be that loose.

It could be mandated that each shim must tightly tie to a kubelet version. For rktlet/dockerlet for now, this will be enforced by being in the same binary.

I'm suggesting that other runtimes could do something similar to that; e.g. you could have the `frakti 1.5.x` release series which works with `kubelet 1.5.x` release, and the kubelet could enforce that the runtime is on the right series.

It would then be up to the shim to either have a tighter or looser coupling; right now `kubelet` couples a little loosely with docker, supporting multiple different versions, but not all runtime-shims will need to do so.

This would at least let kubelet assume an arbitrary runtime shim knows about every field it might set (whether or not it ignores it, which would then be a runtime shim implementation choice).

Thoughts?

**Comment by thockin** [comment]
It's a little draconian, but not a terrible idea.  But is this not covered
by API versioning?  Kubelet says "I want API v1.5" and runtime says "I
don't support that".  == fail.  It's a nefarious failure mode for end-users
though.

**Comment by yifan-gu** [comment]
> It's a little draconian, but not a terrible idea.  But is this not covered
by API versioning?  Kubelet says "I want API v1.5" and runtime says "I
don't support that".  == fail.  It's a nefarious failure mode for end-users
though.

So seems we need to achieve:
1, Don't just drop support when versions are different.
2, Acknowledge users that some features are not supported.

So it sounds like a BIG WARNING is the way to go...

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @yujuhong @thockin @euank

**Comment by euank** [comment]
Bump to 1.6 @dims

**Comment by dims** [comment]
thanks @euank

**Comment by yujuhong** [comment]
Not going to have time to tackle this by 1.7.

**Comment by feiskyer** [comment]
@yujuhong @thockin @Random-Liu Any new ideas on this?

**Comment by Random-Liu** [comment]
@yujuhong @feiskyer For remote runtime integration, we know nothing about the runtime now.

For cri-containerd and cri-o, the biggest challenge is that the underlying runc may have different capabilities based on the build tags:
https://github.com/opencontainers/runc/blob/c5e4c3152dcec4456a6b4f6c1dcc69f3b91eb362/README.md#build-tags

Thus one runc binary may support apparmor, another may not. And the same for seccomp, selinux etc.

We may want to expose this kind of information, so that Kubelet could understand it and make better admission decision.

Things we may want to do:
1) Make sure start container fails loudly if a feature is not supported;
2) Expose runtime capabilities as is discussed in this issue, and solve the problem is a more proper way.

/cc @timstclair @mikebrow @mrunalp

**Comment by mikebrow** [comment]
Yes and further some implementations may include command line switches that disable features that are otherwise available with the runc being used. 

Should security features be a requirement and if so should those requirements be specified by type of security (some aggregation spec) and then implemented by the platform or by implementation dependent options (seccomp, selinux, apparmor, ...) when those are identified as available.

**Comment by feiskyer** [comment]
@Random-Liu @mikebrow @yujuhong @mrunalp What do you think of adding a new API for this? e.g. ask runtime to return a list of supported capabilites:

```proto
rpc Capabilities(CapabilitiesRequest) returns (CapabilitiesResponse) {} 

enum RuntimeCapability {
    CAPABILITY_SYSCTL = 0;
    CAPABILITY_SECCOMP = 1;
    CAPABILITY_SELINUX  = 2;
    CAPABILITY_APPARMOR = 3;
   ....
}

message CapabilitiesRequest {}
message CapabilitiesResponse {
    repeated RuntimeCapability capabilities = 1;
}
```

**Comment by mrunalp** [comment]
@feiskyer I like that idea.

**Comment by mikebrow** [comment]
Yes, that's the sort of thing being discussed. Then there may be a need provide other hints as well.. for example are certain capabilities within each also supported. For example, some defaults may not be specified on the platform / environment. As another example, there may be a minimum version number for the capability that is necessary for the container.

**Comment by mikebrow** [comment]
Or.. we make the demand that to be a CRI implementation, of a certain type, you must implement specified set of features. That might be easier?

**Comment by feiskyer** [comment]
> we make the demand that to be a CRI implementation, of a certain type, you must implement a specified set of features. 

this lgtm, or else it will be too complex.

@mikebrow any ideas on the initial capabilities list?

**Comment by mikebrow** [comment]
I've been trying to figure that out as I go through implementing some of them :-) The pattern I'm using is crawl through the docker shim implementation to derive what the expectations are for each security product, and code it up on the cri-containerd side. For example, for seccomp, {minumum version, docker/default, unconfined, localhost/, runtime/default}

**Comment by mikebrow** [comment]
IMO the best way to ensure the expected features are there is to have test for them in e2e node or cri-tools validate.  For example, we have the SYSCTL and APPARMOR stuff working on cri-containerd. But verifying via e2e node is not a guarantee that we've done all of the needed features for each. For example, none of the e2e node apparmor tests confirm if runtime/default is supported.

**Comment by mikebrow** [comment]
Side note: I'd rather see an external skip list than internal skips for the tests. For example, when testing   for apparmor support for a runtime I shouldn't have to first PR a filter somewhere in a validator in kublet maybe another filter in the e2e tests to convince it that while docker or rkt might not support the feature maybe remote crio does. An external skip file would give us the ability manage the filtering without editing the validators and test cases themselves.

**Comment by mikebrow** [comment]
Another example just popped up: https://github.com/kubernetes/kubernetes/issues/51319

**Comment by feiskyer** [comment]
@jessfraz Any comments on this?

**Comment by jessfraz** [comment]
Yeah I think /info or something like it should return so the admission controllers can deny or not for features like they do with docker versions

**Comment by feiskyer** [comment]
#64005 is adding a similar `GetRuntimeConfigInfo()` interface in CRI, which returns the UID/GID mapping config of runtimes. This could be combined together in one info API.

**Comment by feiskyer** [comment]
@yujuhong @Random-Liu @mikebrow @mrunalp  For the list of features, any more ideas of this list:

```proto
enum RuntimeCapability {
    CAPABILITY_SYSCTL = 0;
    CAPABILITY_SECCOMP = 1;
    CAPABILITY_SELINUX  = 2;
    CAPABILITY_APPARMOR = 3;
}
```
