### ISSUE TITLE
Manual endpoints vanished 

### ISSUE THREAD

**Issue by geku** [kubernetes/kubernetes#32801]
**Kubernetes version** 1.2.5

**Environment**:
- **Cloud provider or hardware configuration**: Rackspace, no cloud provider configured
- **OS**: CoreOS 1010.5.0
- **Kernel**: 4.5.0-coreos-r1 #2 SMP

**What happened**:
We have multiple services without a selector for external services and corresponding endpoints which have been created manually. 

Now, suddenly the endpoints vanished without any interaction from our side. What happened though was that the API, Controller-Manager and Scheduler have been restarted at that time because of an out-of-memory situation on the 2GB node.

We checked the API log file and no DELETION, PUT or PATCH was found for the affected endpoints/services.

**What you expected to happen**:

First I don't expect that manual endpoints get deleted, even when a master component crashes/restarts.

Second, my assumption is that the endpoint controller never touches the endpoints for a service without a selector. And even if it does it, we would see a request in the API logs.

And third, having the API process killed and restarted might probably lead to some corruption or undefined behavior but what might the API do with these endpoints which could result in deleting it?

**How to reproduce it**:
So far we did not find a way to reproduce it.

**Anything else do we need to know**:

We have very limited information about the problem and don't really expect a solution for it, but maybe somebody can explain in more details how manual endpoints are handled by the controller-manager and the API. Thanks.

**Comment by cmluciano** [comment]
Can you describe what you mean by a manual creation? Does this imply manual construction of services through iptables commands?
