### ISSUE TITLE
RC/RS manager should check if pod's controllerRef gets removed

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#32829]
[Pod updates handler](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller.go#L371) of RC/RS manager should take action for pod whose controllerRef gets removed. Currently the hanlder only care about pod label changes.

The result is, if there are two RCs with the same selector in the system (we suggest our users don't do this), and if both of them have already reached the stable states, then after a user deletes one RC and orphans its pods, those pods won't be adopted by the other RC. They will be adopted only if there are changes to the other RC (like updating spec.replicas), or after a full [resync period](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller.go#L58), which is 10 minutes.

cc @wojtek-t @gmarek @lavalamp

**Comment by lavalamp** [comment]
I don't think we need to rush a fix into 1.4, but we should definitely fix this soon.

**Comment by gmarek** [comment]
+1 - it's a rather serious problem, but I'm against rushing the fix.

OT: It seems that interactions between RC/RSs, Pods, kubectl and probably a lot of other components are becoming comprehensible...

**Comment by lavalamp** [comment]
Did you mean "incomprehensible"? I think controllerRef (if bug free) will
actually make things a lot easier to understand.

**Comment by gmarek** [comment]
Yes, sorry - incomprehensible. To many things to write today...

I agree that it'll make things easier from now on. The problem is that there are things (like this kubectl rolling-upgrade) in our main repo, that made some assumptions about implementation of the system and/or includes some hacky workarounds that only few people know about. I guess this is a symptom of system getting mature...

**Comment by lavalamp** [comment]
Yeah. We always knew the kubectl rolling-update contained a very hacky
rename step, even when it first went in. It finally bit us...

**Comment by vefimova** [comment]
hey, I'm working on this one.

**Comment by caesarxuchao** [comment]
Thanks @vefimova!

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @vefimova @caesarxuchao @caesarxuchao

**Comment by caesarxuchao** [comment]
It's not a blocker. We didn't add any new feature to GC in 1.5.

**Comment by grodrigues3** [comment]
@caesarxuchao All issues with the 1.6 milestone are being treated as blockers for 1.6.  Can the milestone be removed?   Is it fixed by @vefimova ?

**Comment by caesarxuchao** [comment]
I think this is fixed by @enisoc's changes: https://github.com/kubernetes/kubernetes/blob/v1.6.0-beta.2/pkg/controller/replicaset/replica_set.go#L281.
