### ISSUE TITLE
federation: need kubectl tests

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#32826]
Currently we dont test kubectl with federation apiserver.
All our e2e tests directly use the clientset to send requests to the apiserver.

We need to setup these kubectl tests

cc @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
Example of an issue we could have found earlier, if we had these tests: https://github.com/kubernetes/kubernetes/issues/32629

**Comment by nikhiljindal** [comment]
Some options:

* We could update our e2e tests to use kubectl instead of directly using the clientset.
To do this, we would need another method like the existing [framework.KubectlCmd](https://github.com/kubernetes/kubernetes/blob/5766776cb30f13aa523bf58c37cb168192f106cb/test/e2e/framework/util.go#L2106), framework.FederationKubectlCmd that will send the request to federation control plane instead of sending it to kube-apiserver.

* Or we can have a version of [hack/make-rules/test-cmd.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/make-rules/test-cmd.sh) for federation. test-cmd.sh is for testing kubectl in kubernetes. In that script we can also test our federation-up scripts to first bring up the federation control plane and then run kubectl commands on it.

**Comment by nikhiljindal** [comment]
Discussed this with @lavalamp and he pointed out that our e2e tests have a chance of becoming more flaky if we include kubectl there. It is better to have a separate test just for kubectl (like we do today with test-cmd.sh)

**Comment by nikhiljindal** [comment]
Sent https://github.com/kubernetes/kubernetes/pull/33414 to add tests for kubectl working with federation-apiserver.
`describe rs` seems to be the only thing that needs fixing. Ref https://github.com/kubernetes/kubernetes/issues/33309

**Comment by dims** [comment]
@nikhiljindal all issues must be labeled either release blocker or non release blocking by end of day 18 November 2016 PST. (or please move it to 1.6) cc @kubernetes/sig-cluster-federation

**Comment by madhusudancs** [comment]
Not a v1.5 release blocker.

**Comment by nikhiljindal** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/38844
