### ISSUE TITLE
Test volume manager in node-e2e-test

### ISSUE THREAD

**Issue by coufon** [kubernetes/kubernetes#32838]
We don't have performance test for volume manager in node-e2e test. It should be added since it is an important part when we measure pod creation latency. 

One problem to note is that we do not have "secret volume" in node-e2e tests. When we create a batch of pods in cluster through replicated controller, because the pods have default secret volumes with the same name, it takes some time for the volume manager to create all of them, see issue #28616. We may also want to test this in node-e2e, otherwise the pod creation latency we get is different from the cluster setting.

**Comment by coufon** [comment]
@dchen1107

**Comment by msau42** [comment]
@dashpole did you add any tests in this area?

sig node storage

**Comment by dashpole** [comment]
The [resource usage node e2e test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/resource_usage_test.go#L145) and the [density batch node e2e test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/density_test.go#L327) both use volumes.  The density one includes measuring startup latency.
The [volumes are all empty-dir volumes](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/resource_collector.go#L416), but I believe secrets are empty-dir voumes underneath?

**Comment by msau42** [comment]
Secrets are emptydir volumes underneath, but maybe there is some additional overhead on top that may be worth measuring.

**Comment by dashpole** [comment]
I doubt there would be objections to changing the volumes in those tests to secrets instead of empty-dirs.
