### ISSUE TITLE
Endpoint controller hot-loops on failure

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#32843]
Endpoint controller hot-loops when etcd is down-- in one cluster I saw 5 digits worth of failed POST requests.

#32461 fixes a log message but not the actual problem.

**Comment by mml** [comment]
@lavalamp I think this is already in review (#32776).  Maybe dup this to #30629.

**Comment by lavalamp** [comment]
Oh nice. That issue seems a bit more general. I edited #32776 so it will mark this closed when it merges.
