### ISSUE TITLE
kubectl set image should return a reasonable error

### ISSUE THREAD

**Issue by PI-Victor** [kubernetes/kubernetes#32865]
`kubectl set image` should return a reasonable error for any resource that doesn't contain a pod spec.
ref: https://github.com/openshift/origin/issues/10947

**Comment by bparees** [comment]
@smarterclayton can this be assigned to @PI-Victor or otherwise indicate he's intending to fix it?

**Comment by PI-Victor** [comment]
seems i'm not going to be able to take care of this in an effective time, should we assign it to someone else since it's rather important?

**Comment by bparees** [comment]
i don't think it's that important.  if you use set image on a resource that doesn't understand images, you get no feedback.  that's annoying, but not critical imho.

**Comment by PI-Victor** [comment]
ok sounds good, deferring to future Victor then, i'll let him take care of it.

**Comment by PI-Victor** [comment]
seems that time has caught up with future Victor. working on this.

**Comment by PI-Victor** [comment]
sadly (for me) this was actually fixed 9 months ago. you can no longer set an image for a non pod spec resource. see https://github.com/kubernetes/kubernetes/blame/master/pkg/kubectl/cmd/util/factory_client_access.go#L245

```
master  kubectl set image svc odoo-shop odoo-shop=debian:wheezy
error: services/odoo-shop the object is not a pod or does not have a pod template
```
I believe this also will apply to origin after that rebase. I can check origin as well.

closing this.

**Comment by Spongman** [comment]
this seems broken. if you have multiple sections in a `.yaml` file and only one of the is a pod, then `kubectl set ... | kubectl apply -f -` doesn't work.
