### ISSUE TITLE
`port-forward` API call does not support websockets, SPDY is still default.

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/kubernetes#32880]
While the `exec` and `logs` calls have been updated to be able to use websockets, the `port-forward` call is still stuck on SPDY.

We should enable port-forward over websockets.

PR that made the original switch for exec and logs I believe is:
https://github.com/kubernetes/kubernetes/pull/13885

and the work to be done should be in `pkg/kubelet/server/remotecommand`

probably using `pk/util/wsstream`

**Comment by sebgoa** [comment]
@fraenkel since you fixed the headless service issue so fast :) do you want to have a look at that one ?

That would be a big help.

**Comment by sebgoa** [comment]
@ngtuna here is the issue

**Comment by fraenkel** [comment]
@sebgoa Will take a look.

**Comment by fraenkel** [comment]
@sebgoa  I see where we need to switch port-forward to use websockets on the backend.
However, It seems port-forward, exec and attach still use SPDY on the front-end. Is this supposed to be fixed in this PR as well?

**Comment by sebgoa** [comment]
Hi, I think we can do both with exec, no ? kubectl can probably stay as is and we allow for both spy and websockets server side ?

@smarterclayton probably knows best.

**Comment by smarterclayton** [comment]
It would be best to fix port forward to support websockets first.  I don't think that we need to switch kubectl away from SPDY at this time.  Websocket is a little less efficient than our spdy protocol last I checked and head of line blocking may be relevant (hard to say without a lot more testing), so we'd want a really concrete reason.

**Comment by fraenkel** [comment]
@sebgoa It turns out putting it in remotecommand won't work or do well. It is best to lift code over to the portforward package and re-implement. port forwarding has a different request pattern and uses different streams. I will give it a go and then we can discuss options.

**Comment by sebgoa** [comment]
@fraenkel do you still have time to work on this ?

**Comment by fraenkel** [comment]
@sebgoa Sorry, I am on my 5th try. Port forward using SPDY vs websockets is basically two different implementations. It would have been far better to go from SPDY to HTTP/2 given a much closer model.
Once I get a complete websockets implementation with corresponding test cases I can begin to look at what if anything can be merged. It will be very very little.

**Comment by sebgoa** [comment]
thanks. @ngtuna or @cab105 might be able to help. we work together, but out of cycles to make this one work. Though we need it :( for Cabin, the iOS app for Kubernetes.

Maybe you can make a PR and folks like @smarterclayton or @sttts can comment and help out.

**Comment by fraenkel** [comment]
@sebgoa I just began to write the tests for this, and uncovered the next gotcha that I haven't handled. Since websockets doesn't have streams, I already created a request structure for the PortForward but didn't realize that I must also package the responses to distinguish the streams. This also means clients must know the internal request/response for PortForwarding.  Just want to make sure that we are all on the same page before I go add even more code.

**Comment by smarterclayton** [comment]
Definitely port forward, if it has a protocol, has to be versioned like the
others.

On Fri, Sep 30, 2016 at 10:08 AM, Michael Fraenkel <notifications@github.com

**Comment by fraenkel** [comment]
@smarterclayton There is no exposed client for websockets though.

**Comment by fraenkel** [comment]
So I have come up with a new way which should make the response aka forwarding much much easier.  The request side is still a mess since I either use a fake stdin to retrieve the port information or it gets encoded as part of the URL.  While I could use the HTTP headers to transfer the information, that is not possible if we are looking at a javascript client.
Let me see where I end up with these bits of changes and then we can discuss how we want the request portion to work.

**Comment by smarterclayton** [comment]
All of these APIs if they need to return structured data need to have a
mechanism for API versioning.  For web sockets we use websocket protocols,
so you would pick protocol one and go from there (see how exec and others
use it).

**Comment by fraenkel** [comment]
I was originally trying to match the multiple port forwards on a connection which is what I ended up giving up on.  If I only allow a single port forward then it is doable.

**Comment by fraenkel** [comment]
Got a version I am happy with.  Please go ahead and review it.
We noticed that the websocket receive error handling is a bit chatty.
We always get the following:
```
E1003 14:57:18.559563   32603 conn.go:251] Error on socket receive: read tcp 127.0.0.1:61882->127.0.0.1:61883: use of closed network connection
```

**Comment by cmluciano** [comment]
this should be added via #33684

**Comment by mruoss** [comment]
> I was originally trying to match the multiple port forwards on a connection which is what I ended up giving up on. If I only allow a single port forward then it is doable.

Has connection multiplexing ever been implemented since? I know we have port multiplexing but it would be nice if we could use the same websocket for multiple client connections.
