### ISSUE TITLE
kubectl describe should be resilient to errors in fetching related info

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#32883]
Forked from https://github.com/kubernetes/kubernetes/pull/32823#r79096971

Actual:
kubectl describe requests a number of resources from server and fails if any one of those request fails.

Expectation:
It should atleast display the information that it was able to fetch

A particular instance of this problem (with namespaces): https://github.com/kubernetes/kubernetes/issues/32629

**Comment by nikhiljindal** [comment]
@kubernetes/kubectl

**Comment by smarterclayton** [comment]
We do this in some places but not others.  We should definitely try to get this into kubectl conventions so that we apply it in reviews.

**Comment by AdoHe** [comment]
sure, we should get it into kubectl conventions.
