### ISSUE TITLE
AWS volume pending for detach for 30 minutes due to busy status

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#32881]
During testing a AWS cluster, found AWS volume once was pending for detach about 30 minutes. According to the log, the following happened,
- controller issues a detach operation
- after detach response returns, it periodically checks the status until it reaches "detached". However, in this test, the status is "busy" all the time. 
- after reaching the timeout 30 mins, detach function returns error because the status is not "detached"

The following is the log related to the failed test

I0915 18:29:46.470405       5 operation_executor.go:649] Verified volume is safe to detach for volume "kubernetes.io/aws-ebs/aws://us-west-2a/vol-540bc3dc" (spec.Name: "pvc-540ccbfc-7ac7-11e6-abe5-02a41bd7f415") from node "ip-172-20-0-244.us-west-2.compute.internal".
E0915 18:59:54.924434       5 attacher.go:206] Error detaching volumeID "vol-540bc3dc": Timeout waiting for volume state: actual=busy, desired=detached
E0915 18:59:54.924496       5 nestedpendingoperations.go:253] Operation for "\"kubernetes.io/aws-ebs/aws://us-west-2a/vol-540bc3dc\"" failed. No retries permitted until 2016-09-15 18:59:55.424472076 +0000 UTC (durationBeforeRetry 500ms). Error: DetachVolume.Detach failed for volume "kubernetes.io/aws-ebs/aws://us-west-2a/vol-540bc3dc" (spec.Name: "pvc-540ccbfc-7ac7-11e6-abe5-02a41bd7f415") from node "ip-172-20-0-244.us-west-2.compute.internal" with: Timeout waiting for volume state: actual=busy, desired=detached

**Comment by saad-ali** [comment]
Thoughts on what the ideal timeout should be. Too short would be bad because it would give a false-negative.

**Comment by jsravn** [comment]
I know this is from a test but I'm seeing the same problem on a production cluster (1.4.8).

I'm not sure exactly what triggers it yet. Kubelet only unmounts the pod directory, not the mount in "aws-ebs/mounts". As a result, the EBS gets stuck in "busy" state when detaching since it is still mounted to the VM. Manually unmounting the EBS allows it to get unstuck and detach safely.

In controller manager I see:
```
I0124 09:22:24.227715       6 reconciler.go:178] Started DetachVolume for volume "kubernetes.io/aws-ebs/vol-123456" from node "ip-1-1-1-1.eu-west-1.compute.internal"
I0124 09:22:24.229587       6 operation_executor.go:754] Verified volume is safe to detach for volume "kubernetes.io/aws-ebs/vol-11af4ca1" (spec.Name: "storage") from node "ip-1-1-1-1.eu-west-1.compute.internal".
<snip>
I0124 09:22:24.774072       6 aws.go:1363] Waiting for volume state: actual=detaching, desired=detached
I0124 09:22:34.864529       6 aws.go:1363] Waiting for volume state: actual=detaching, desired=detached
I0124 09:22:44.915738       6 aws.go:1363] Waiting for volume state: actual=detaching, desired=detached
I0124 09:22:54.962981       6 aws.go:1363] Waiting for volume state: actual=detaching, desired=detached
I0124 09:23:05.080961       6 aws.go:1363] Waiting for volume state: actual=busy, desired=detached
I0124 09:23:15.170887       6 aws.go:1363] Waiting for volume state: actual=busy, desired=detached
I0124 09:23:25.232380       6 aws.go:1363] Waiting for volume state: actual=busy, desired=detached
<repeated indefinitely>
```

It then proceeds to get stuck detaching (volume goes to busy state), after which it starts trying to force detach which of course hangs indefinitely. Inspecting the node directly, I see it's still mounted which is why detach hangs:

```
$ mount | grep vol-123456
/dev/xvdba on /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/vol-123456 type xfs (rw,relatime,attr2,inode64,noquota)
```

So something in kubelet is messed up and not unmounting both mount points correctly.

**Comment by jsravn** [comment]
I think this might be the same issue as https://github.com/kubernetes/kubernetes/issues/37854

**Comment by jsravn** [comment]
On kubelet, it looks like the volume failed to mark as mounted, which is why it got stuck. This may have to do with the fact this pod got rolled back while waiting for the previous deployment to succeed.

```
I0124 09:22:14.482949    2082 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
I0124 09:22:14.483004    2082 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
I0124 09:22:14.555008    2082 kubelet.go:2315] SyncLoop (DELETE, "api"): "registry-3598606178-wy08f_default(4b09af8a-e216-11e6-bb71-0a91e4a124bf)"
I0124 09:22:14.591531    2082 kubelet.go:2315] SyncLoop (DELETE, "api"): "registry-3598606178-wy08f_default(4b09af8a-e216-11e6-bb71-0a91e4a124bf)"
I0124 09:22:14.608455    2082 kubelet.go:2309] SyncLoop (REMOVE, "api"): "registry-3598606178-wy08f_default(4b09af8a-e216-11e6-bb71-0a91e4a124bf)"
I0124 09:22:14.608562    2082 kubelet.go:2498] Failed to delete pod "registry-3598606178-wy08f_default(4b09af8a-e216-11e6-bb71-0a91e4a124bf)", err: pod not found
I0124 09:22:14.613340    2082 attacher.go:147] Successfully found attached AWS Volume "vol-11af4ca1".
I0124 09:22:14.613398    2082 operation_executor.go:832] MountVolume.WaitForAttach succeeded for volume "kubernetes.io/aws-ebs/vol-11af4ca1" (spec.Name: "storage") pod "4b09af8a-e216-11e6-bb71-0a91e4a124bf" (UID: "4b09af8a-e216-11e6-bb71-0a91e4a124bf").
I0124 09:22:14.719148    2082 reconciler.go:188] UnmountVolume operation started for volume "kubernetes.io/secret/4b09af8a-e216-11e6-bb71-0a91e4a124bf-default-token-cj54v" (spec.Name: "default-token-cj54v") from pod "4b09af8a-e216-11e6-bb71-0a91e4a124bf" (UID: "4b09af8a-e216-11e6-bb71-0a91e4a124bf").
I0124 09:22:14.761098    2082 operation_executor.go:992] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/4b09af8a-e216-11e6-bb71-0a91e4a124bf-default-token-cj54v" (OuterVolumeSpecName: "default-token-cj54v") pod "4b09af8a-e216-11e6-bb71-0a91e4a124bf" (UID: "4b09af8a-e216-11e6-bb71-0a91e4a124bf"). InnerVolumeSpecName "default-token-cj54v". PluginName "kubernetes.io/secret", VolumeGidValue ""
I0124 09:22:14.828984    2082 operation_executor.go:871] MountVolume.MountDevice succeeded for volume "kubernetes.io/aws-ebs/vol-11af4ca1" (spec.Name: "storage") pod "4b09af8a-e216-11e6-bb71-0a91e4a124bf" (UID: "4b09af8a-e216-11e6-bb71-0a91e4a124bf") device mount path "/var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/vol-11af4ca1"
E0124 09:22:14.829097    2082 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/aws-ebs/vol-11af4ca1\"" failed. No retries permitted until 2017-01-24 09:22:15.329067548 +0000 UTC (durationBeforeRetry 500ms). Error: MountVolume.MarkDeviceAsMounted failed for volume "kubernetes.io/aws-ebs/vol-11af4ca1" (spec.Name: "storage") pod "4b09af8a-e216-11e6-bb71-0a91e4a124bf" (UID: "4b09af8a-e216-11e6-bb71-0a91e4a124bf") with: no volume with the name "kubernetes.io/aws-ebs/vol-11af4ca1" exists in the list of attached volumes
```

**Comment by jsravn** [comment]
^ Looks like a race condition basically:

1. controller manager attaches volume
2. kubelet starts attachment process
3. controller manager thinks its safe to detach, so removes volume from node's volume list, then tries to detach
4. kubelet mounts the volume as part of the ongoing attach/mount process from (2)
5. kubelet tries to update the mount list, this fails because controller manager has removed the volume from attached list
6. volume gets stuck in (busy) state detaching, as its mounted to the kubelet node. it never gets unmounted in kubelet because state doesn't reflect it is mounted.

**Comment by jsravn** [comment]
I'm pretty sure this is `reconciler.go` detaching the volume because kubelet (in `operation_executor.go`) hasn't yet added the mount. Seems like if the reconciler runs any time a mount operation is in progress, with controller-manager enabled, it will prematurely mark the volume as detached.

**Comment by jsravn** [comment]
Looks like there exists race conditions between external updates of `desiredStateOfWorld` and reconciler.go's asynchronous kick off of operations like MountVolume, which is the case I'm seeing. Seems like a lot of these edge cases could crop up here - maybe reconciler should lock changes to the desiredStateOfWorld while it's running?

**Comment by jingxu97** [comment]
@jsravn, thank you for providing detailed information and analysis. I think there is a race condition between asynchronous operation MountVolume and updating actualStateOfWorld directly by reconciler https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconciler.go#L347
I will work on a fix. Please let me know if you have any issue/comments.
