### ISSUE TITLE
e2e permafail on upgrade: [k8s.io] Deployment deployment should support rollback when there's replica set with no revision 

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#32915]
on [kubernetes-e2e-gce-1.3-1.4-upgrade-master](http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GCE/job/kubernetes-e2e-gce-1.3-1.4-upgrade-master/5/)

[k8s.io] Deployment deployment should support rollback when there's replica set with no revision

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:79 Expected <[]extensions.ReplicaSet | len:1, cap:1>: [ { TypeMeta: {Kind: "", APIVersion: ""}, ObjectMeta: { Name: "test-rollback-no-revision-deployment-783459730", GenerateName: "", Namespace: "e2e-tests-deployment-2bt7a", SelfLink: "/apis/extensions/v1beta1/namespaces/e2e-tests-deployment-2bt7a/replicasets/test-rollback-no-revision-deployment-783459730", UID: "f32a416d-7c2e-11e6-891a-42010af00002", ResourceVersion: "17825", Generation: 5, CreationTimestamp: { Time: { sec: 63609641977, nsec: 0, loc: { name: "Local", zone: [ {name: "PDT", offset: -25200, isDST: true}, {name: "PST", offset: -28800, isDST: false}, {name: "PWT", offset: -25200, isDST: true}, {name: "PPT", offset: -25200, isDST: true}, ], tx: [ {when: -1633269600, index: 0, isstd: false, isutc: false}, {when: -1615129200, index: 1, isstd: false, isutc: false}, {when: -1601820000, index: 0, isstd: false, isutc: false}, {when: -1583679600, index: 1, isstd: true, isutc: true}, {when: -880207200, index: 2, isstd: false, isutc: false}, {when: -769395600, index: 3, isstd: false, isutc: false}, {when: -765385200, index: 1, isstd: false, isutc: false}, {when: -687967200, index: 0, isstd: false, isutc: false}, {when: -662655600, index: 1, isstd: false, isutc: false}, {when: -620834400, index: 0, isstd: false, isutc: false}, {when: -608137200, index: 1, isstd: false, isutc: false}, {when: -589384800, index: 0, isstd: false, isutc: false}, {when: -576082800, index: 1, isstd: false, isutc: false}, {when: -557935200, index: 0, isstd: false, isutc: false}, {when: -544633200, index: 1, isstd: false, isutc: false}, {when: -526485600, index: 0, isstd: false, isutc: false}, {when: -513183600, index: 1, isstd: false, isutc: false}, {when: -495036000, index: 0, isstd: false, isutc: false}, {when: -481734000, index: 1, isstd: false, isutc: false}, {when: -463586400, index: 0, isstd: false, isutc: false}, {when: -450284400, index: 1, isstd: false, isutc: false}, {when: -431532000, index: 0, isstd: false, isutc: false}, {when: -418230000, index: 1, isstd: false, isutc: false}, {when: -400082400, index: 0, isstd: false, isutc: false}, {when: -386780400, index: 1, isstd: false, isutc: false}, {when: -368632800, index: 0, isstd: false, isutc: false}, {when: -355330800, index: 1, isstd: false, isutc: false}, {when: -337183200, index: 0, isstd: false, isutc: false}, {when: -323881200, index: 1, isstd: false, isutc: false}, {when: -305733600, index: 0, isstd: false, isutc: false}, {when: -292431600, index: 1, isstd: false, isutc: false}, {when: -273679200, index: 0, isstd: false, isutc: false}, {when: -260982000, index: 1, isstd: false, isutc: false}, {when: -242229600, index: 0, isstd: false, isutc: false}, {when: -226508400, index: 1, isstd: false, isutc: false}, {when: -210780000, index: 0, isstd: false, isutc: false}, {when: -195058800, index: 1, isstd: false, isutc: false}, {when: -179330400, index: 0, isstd: false, isutc: false}, {when: -163609200, index: 1, isstd: false, isutc: false}, {when: -147880800, index: 0, isstd: false, isutc: false}, {when: -131554800, index: 1, isstd: false, isutc: false}, {when: -116431200, index: 0, isstd: false, isutc: false}, {when: -100105200, index: 1, isstd: false, isutc: false}, {when: -84376800, index: 0, isstd: false, isutc: false}, {when: -68655600, index: 1, isstd: false, isutc: false}, {when: -52927200, index: 0, isstd: false, isutc: false}, {when: -37206000, index: 1, isstd: false, isutc: false}, {when: -21477600, index: 0, isstd: false, isutc: false}, {when: -5756400, index: 1, isstd: false, isutc: false}, {when: 9972000, index: 0, isstd: false, isutc: false}, {when: 25693200, index: 1, isstd: false, isutc: false}, {when: 41421600, index: 0, isstd: false, isutc: false}, {when: 57747600, index: 1, isstd: false, isutc: false}, {when: 73476000, index: 0, isstd: false, isutc: false}, {when: 89197200, index: 1, isstd: false, isutc: false}, {when: 104925600, index: 0, isstd: false, isutc: false}, {when: 120646800, index: 1, isstd: false, isutc: false}, {when: 126698400, index: 0, isstd: false, isutc: false}, {when: 152096400, index: 1, isstd: false, isutc: false}, {when: 162381600, index: 0, isstd: false, isutc: false}, {when: 183546000, index: 1, isstd: false, isutc: false}, {when: 199274400, index: 0, isstd: false, isutc: false}, {when: 215600400, index: 1, isstd: false, isutc: false}, {when: 230724000, index: 0, isstd: false, isutc: false}, {when: 247050000, index: 1, isstd: false, isutc: false}, {when: 262778400, index: 0, isstd: false, isutc: false}, {when: 278499600, index: 1, isstd: false, isutc: false}, {when: 294228000, index: 0, isstd: false, isutc: false}, {when: 309949200, index: 1, isstd: false, isutc: false}, {when: 325677600, index: 0, isstd: false, isutc: false}, {when: 341398800, index: 1, isstd: false, isutc: false}, {when: 357127200, index: 0, isstd: false, isutc: false}, {when: 372848400, index: 1, isstd: false, isutc: false}, {when: 388576800, index: 0, isstd: false, isutc: false}, {when: 404902800, index: 1, isstd: false, isutc: false}, {when: 420026400, index: 0, isstd: false, isutc: false}, {when: 436352400, index: 1, isstd: false, isutc: false}, {when: 452080800, index: 0, isstd: false, isutc: false}, {when: 467802000, index: 1, isstd: false, isutc: false}, {when: 483530400, index: 0, isstd: false, isutc: false}, {when: 499251600, index: 1, isstd: false, isutc: false}, {when: 514980000, index: 0, isstd: false, isutc: false}, {when: 530701200, index: 1, isstd: false, isutc: false}, {when: 544615200, index: 0, isstd: false, isutc: false}, {when: 562150800, index: 1, isstd: false, isutc: false}, {when: 576064800, index: 0, isstd: false, isutc: false}, {when: 594205200, index: 1, isstd: false, isutc: false}, {when: 607514400, index: 0, isstd: false, isutc: false}, {when: 625654800, index: 1, isstd: false, isutc: false}, {when: 638964000, index: 0, isstd: false, isutc: false}, {when: 657104400, index: 1, isstd: false, isutc: false}, {when: 671018400, index: 0, isstd: false, isutc: false}, {when: 688554000, index: 1, isstd: false, isutc: false}, {when: 702468000, index: 0, isstd: false, isutc: false}, {when: 720003600, index: 1, isstd: false, isutc: false}, {when: 733917600, index: 0, isstd: false, isutc: false}, {when: 752058000, index: 1, isstd: false, isutc: false}, {when: 765367200, index: 0, isstd: false, isutc: false}, {when: 783507600, index: 1, isstd: false, isutc: false}, {when: 796816800, index: 0, isstd: false, isutc: false}, {when: 814957200, index: 1, isstd: false, isutc: false}, {when: 828871200, index: 0, isstd: false, isutc: false}, {when: 846406800, index: 1, isstd: false, isutc: false}, {when: 860320800, index: 0, isstd: false, isutc: false}, {when: 877856400, index: 1, isstd: false, isutc: false}, {when: 891770400, index: 0, isstd: false, isutc: false}, {when: 909306000, index: 1, isstd: false, isutc: false}, {when: 923220000, index: 0, isstd: false, isutc: false}, {when: 941360400, index: 1, isstd: false, isutc: false}, {when: 954669600, index: 0, isstd: false, isutc: false}, {when: 972810000, index: 1, isstd: false, isutc: false}, {when: 986119200, index: 0, isstd: false, isutc: false}, {when: 1004259600, index: 1, isstd: false, isutc: false}, {when: 1018173600, index: 0, isstd: false, isutc: false}, {when: 1035709200, index: 1, isstd: false, isutc: false}, {when: 1049623200, index: 0, isstd: false, isutc: false}, {when: 1067158800, index: 1, isstd: false, isutc: false}, {when: 1081072800, index: 0, isstd: false, isutc: false}, {when: 1099213200, index: 1, isstd: false, isutc: false}, {when: 1112522400, index: 0, isstd: false, isutc: false}, {when: 1130662800, index: 1, isstd: false, isutc: false}, {when: 1143972000, index: 0, isstd: false, isutc: false}, {when: 1162112400, index: 1, isstd: false, isutc: false}, {when: 1173607200, index: 0, isstd: false, isutc: false}, {when: 1194166800, index: 1, isstd: false, isutc: false}, {when: 1205056800, index: 0, isstd: false, isutc: false}, {when: 1225616400, index: 1, isstd: false, isutc: false}, {when: 1236506400, index: 0, isstd: false, isutc: false}, {when: 1257066000, index: 1, isstd: false, isutc: false}, {when: 1268560800, index: 0, isstd: false, isutc: false}, {when: 1289120400, index: 1, isstd: false, isutc: false}, {when: 1300010400, index: 0, isstd: false, isutc: false}, {when: 1320570000, index: 1, isstd: false, isutc: false}, {when: 1331460000, index: 0, isstd: false, isutc: false}, {when: 1352019600, index: 1, isstd: false, isutc: false}, {when: 1362909600, index: 0, isstd: false, isutc: false}, {when: 1383469200, index: 1, isstd: false, isutc: false}, {when: 1394359200, index: 0, isstd: false, isutc: false}, {when: 1414918800, index: 1, isstd: false, isutc: false}, {when: 1425808800, index: 0, isstd: false, isutc: false}, {when: 1446368400, index: 1, isstd: false, isutc: false}, {when: 1457863200, index: 0, isstd: false, isutc: false}, {when: 1478422800, index: 1, isstd: false, isutc: false}, {when: 1489312800, index: 0, isstd: false, isutc: false}, {when: 1509872400, index: 1, isstd: false, isutc: false}, {when: 1520762400, index: 0, isstd: false, isutc: false}, {when: 1541322000, index: 1, isstd: false, isutc: false}, {when: 1552212000, index: 0, isstd: false, isutc: false}, {when: 1572771600, index: 1, isstd: false, isutc: false}, {when: 1583661600, index: 0, isstd: false, isutc: false}, {when: 1604221200, index: 1, isstd: false, isutc: false}, {when: 1615716000, index: 0, isstd: false, isutc: false}, {when: 1636275600, index: 1, isstd: false, isutc: false}, {when: 1647165600, index: 0, isstd: false, isutc: false}, {when: 1667725200, index: 1, isstd: false, isutc: false}, {when: 1678615200, index: 0, isstd: false, isutc: false}, {when: 1699174800, index: 1, isstd: false, isutc: false}, {when: 1710064800, index: 0, isstd: false, isutc: false}, {when: 1730624400, index: 1, isstd: false, isutc: false}, {when: 1741514400, index: 0, isstd: false, isutc: false}, {when: 1762074000, index: 1, isstd: false, isutc: false}, {when: 1772964000, index: 0, isstd: false, isutc: false}, {when: 1793523600, index: 1, isstd: false, isutc: false}, {when: 1805018400, index: 0, isstd: false, isutc: false}, {when: 1825578000, index: 1, isstd: false, isutc: false}, {when: 1836468000, index: 0, isstd: false, isutc: false}, {when: 1857027600, index: 1, isstd: false, isutc: false}, {when: 1867917600, index: 0, isstd: false, isutc: false}, {when: 1888477200, index: 1, isstd: false, isutc: false}, {when: 1899367200, index: 0, isstd: false, isutc: false}, {when: 1919926800, index: 1, isstd: false, isutc: false}, {when: 1930816800, index: 0, isstd: false, isutc: false}, {when: 1951376400, index: 1, isstd: false, isutc: false}, {when: 1962871200, index: 0, isstd: false, isutc: false}, {when: 1983430800, index: 1, isstd: false, isutc: false}, {when: 1994320800, index: 0, isstd: false, isutc: false}, {when: 2014880400, index: 1, isstd: false, isutc: false}, {when: 2025770400, index: 0, isstd: false, isutc: false}, {when: 2046330000, index: 1, isstd: false, isutc: false}, {when: 2057220000, index: 0, isstd: false, isutc: false}, {when: 2077779600, index: 1, isstd: false, isutc: false}, {when: 2088669600, index: 0, isstd: false, isutc: false}, {when: 2109229200, index: 1, isstd: false, isutc: false}, {when: 2120119200, index: 0, isstd: false, isutc: false}, {when: 2140678800, index: 1, isstd: false, isutc: false}, ], cacheStart: 1457863200, cacheEnd: 1478422800, cacheZone: {name: "PDT", offset: -25200, isDST: true}, }, }, }, DeletionTimestamp: { Time: { sec: 63609642001, nsec: 0, loc: { name: "Local", zone: [ {name: "PDT", offset: -25200, isDST: true}, {name: "PST", offset: -28800, isDST: false}, {name: "PWT", offset: -25200, isDST: true}, {name: "PPT", offset: -25200, isDST: true}, ], tx: [ {when: -1633269600, index: 0, isstd: false, isutc: false}, {when: -1615129200, index: 1, isstd: false, isutc: false}, {when: -1601820000, index: 0, isstd: false, isutc: false}, {when: -1583679600, index: 1, isstd: true, isutc: true}, {when: -880207200, index: 2, isstd: false, isutc: false}, {when: -769395600, index: 3, isstd: false, isutc: false}, {when: -765385200, index: 1, isstd: false, isutc: false}, {when: -687967200, index: 0, isstd: false, isutc: false}, {when: -662655600, index: 1, isstd: false, isutc: false}, {when: -620834400, index: 0, isstd: false, isutc: false}, {when: -608137200, index: 1, isstd: false, isutc: false}, {when: -589384800, index: 0, isstd: false, isutc: false}, {when: -576082800, index: 1, isstd: false, isutc: false}, {when: -557935200, index: 0, isstd: false, isutc: false}, {when: -544633200, index: 1, isstd: false, isutc: false}, {when: -526485600, index: 0, isstd: false, isutc: false}, {when: -513183600, index: 1, isstd: false, isutc: false}, {when: -495036000, index: 0, isstd: false, isutc: false}, {when: -481734000, index: 1, isstd: false, isutc: false}, {when: -463586400, index: 0, isstd: false, isutc: false}, {when: -450284400, index: 1, isstd: false, isutc: false}, {when: -431532000, index: 0, isstd: false, isutc: false}, {when: -418230000, index: 1, isstd: false, isutc: false}, {when: -400082400, index: 0, isstd: false, isutc: false}, {when: -386780400, index: 1, isstd: false, isutc: false}, {when: -368632800, index: 0, isstd: false, isutc: false}, {when: -355330800, index: 1, isstd: false, isutc: false}, {when: -337183200, index: 0, isstd: false, isutc: false}, {when: -323881200, index: 1, isstd: false, isutc: false}, {when: -305733600, index: 0, isstd: false, isutc: false}, {when: -292431600, index: 1, isstd: false, isutc: false}, {when: -273679200, index: 0, isstd: false, isutc: false}, {when: -260982000, index: 1, isstd: false, isutc: false}, {when: -242229600, index: 0, isstd: false, isutc: false}, {when: -226508400, index: 1, isstd: false, isutc: false}, {when: -210780000, index: 0, isstd: false, isutc: false}, {when: -195058800, index: 1, isstd: false, isutc: false}, {when: -179330400, index: 0, isstd: false, isutc: false}, {when: -163609200, index: 1, isstd: false, isutc: false}, {when: -147880800, index: 0, isstd: false, isutc: false}, {when: -131554800, index: 1, isstd: false, isutc: false}, {when: -116431200, index: 0, isstd: false, isutc: false}, {when: -100105200, index: 1, isstd: false, isutc: false}, {when: -84376800, index: 0, isstd: false, isutc: false}, {when: -68655600, index: 1, isstd: false, isutc: false}, {when: -52927200, index: 0, isstd: false, isutc: false}, {when: -37206000, index: 1, isstd: false, isutc: false}, {when: -21477600, index: 0, isstd: false, isutc: false}, {when: -5756400, index: 1, isstd: false, isutc: false}, {when: 9972000, index: 0, isstd: false, isutc: false}, {when: 25693200, index: 1, isstd: false, isutc: false}, {when: 41421600, index: 0, isstd: false, isutc: false}, {when: 57747600, index: 1, isstd: false, isutc: false}, {when: 73476000, index: 0, isstd: false, isutc: false}, {when: 89197200, index: 1, isstd: false, isutc: false}, {when: 104925600, index: 0, isstd: false, isutc: false}, {when: 120646800, index: 1, isstd: false, isutc: false}, {when: 126698400, index: 0, isstd: false, isutc: false}, {when: 152096400, index: 1, isstd: false, isutc: false}, {when: 162381600, index: 0, isstd: false, isutc: false}, {when: 183546000, index: 1, isstd: false, isutc: false}, {when: 199274400, index: 0, isstd: false, isutc: false}, {when: 215600400, index: 1, isstd: false, isutc: false}, {when: 230724000, index: 0, isstd: false, isutc: false}, {when: 247050000, index: 1, isstd: false, isutc: false}, {when: 262778400, index: 0, isstd: false, isutc: false}, {when: 278499600, index: 1, isstd: false, isutc: false}, {when: 294228000, index: 0, isstd: false, isutc: false}, {when: 309949200, index: 1, isstd: false, isutc: false}, {when: 325677600, index: 0, isstd: false, isutc: false}, {when: 341398800, index: 1, isstd: false, isutc: false}, {when: 357127200, index: 0, isstd: false, isutc: false}, {when: 372848400, index: 1, isstd: false, isutc: false}, {when: 388576800, index: 0, isstd: false, isutc: false}, {when: 404902800, index: 1, isstd: false, isutc: false}, {when: 420026400, index: 0, isstd: false, isutc: false}, {when: 436352400, index: 1, isstd: false, isutc: false}, {when: 452080800, index: 0, isstd: false, isutc: false}, {when: 467802000, index: 1, isstd: false, isutc: false}, {when: 483530400, index: 0, isstd: false, isutc: false}, {when: 499251600, index: 1, isstd: false, isutc: false}, {when: 514980000, index: 0, isstd: false, isutc: false}, {when: 530701200, index: 1, isstd: false, isutc: false}, {when: 544615200, index: 0, isstd: false, isutc: false}, {when: 562150800, index: 1, isstd: false, isutc: false}, {when: 576064800, index: 0, isstd: false, isutc: false}, {when: 594205200, index: 1, isstd: false, isutc: false}, {when: 607514400, index: 0, isstd: false, isutc: false}, {when: 625654800, index: 1, isstd: false, isutc: false}, {when: 638964000, index: 0, isstd: false, isutc: false}, {when: 657104400, index: 1, isstd: false, isutc: false}, {when: 671018400, index: 0, isstd: false, isutc: false}, {when: 688554000, index: 1, isstd: false, isutc: false}, {when: 702468000, index: 0, isstd: false, isutc: false}, {when: 720003600, index: 1, isstd: false, isutc: false}, {when: 733917600, index: 0, isstd: false, isutc: false}, {when: 752058000, index: 1, isstd: false, isutc: false}, {when: 765367200, index: 0, isstd: false, isutc: false}, {when: 783507600, index: 1, isstd: false, isutc: false}, {when: 796816800, index: 0, isstd: false, isutc: false}, {when: 814957200, index: 1, isstd: false, isutc: false}, {when: 828871200, index: 0, isstd: false, isutc: false}, {when: 846406800, index: 1, isstd: false, isutc: false}, {when: 860320800, index: 0, isstd: false, isutc: false}, {when: 877856400, index: 1, isstd: false, isutc: false}, {when: 891770400, index: 0, isstd: false, isutc: false}, {when: 909306000, index: 1, isstd: false, isutc: false}, {when: 923220000, index: 0, isstd: false, isutc: false}, {when: 941360400, index: 1, isstd: false, isutc: false}, {when: 954669600, index: 0, isstd: false, isutc: false}, {when: 972810000, index: 1, isstd: false, isutc: false}, {when: 986119200, index: 0, isstd: false, isutc: false}, {when: 1004259600, index: 1, isstd: false, isutc: false}, {when: 1018173600, index: 0, isstd: false, isutc: false}, {when: 1035709200, index: 1, isstd: false, isutc: false}, {when: 1049623200, index: 0, isstd: false, isutc: false}, {when: 1067158800, index: 1, isstd: false, isutc: false}, {when: 1081072800, index: 0, isstd: false, isutc: false}, {when: 1099213200, index: 1, isstd: false, isutc: false}, {when: 1112522400, index: 0, isstd: false, isutc: false}, {when: 1130662800, index: 1, isstd: false, isutc: false}, {when: 1143972000, index: 0, isstd: false, isutc: false}, {when: 1162112400, index: 1, isstd: false, isutc: false}, {when: 1173607200, index: 0, isstd: false, isutc: false}, {when: 1194166800, index: 1, isstd: false, isutc: false}, {when: 1205056800, index: 0, isstd: false, isutc: false}, {when: 1225616400, index: 1, isstd: false, isutc: false}, {when: 1236506400, index: 0, isstd: false, isutc: false}, {when: 1257066000, index: 1, isstd: false, isutc: false}, {when: 1268560800, index: 0, isstd: false, isutc: false}, {when: 1289120400, index: 1, isstd: false, isutc: false}, {when: 1300010400, index: 0, isstd: false, isutc: false}, {when: 1320570000, index: 1, isstd: false, isutc: false}, {when: 1331460000, index: 0, isstd: false, isutc: false}, {when: 1352019600, index: 1, isstd: false, isutc: false}, {when: 1362909600, index: 0, isstd: false, isutc: false}, {when: 1383469200, index: 1, isstd: false, isutc: false}, {when: 1394359200, index: 0, isstd: false, isutc: false}, {when: 1414918800, index: 1, isstd: false, isutc: false}, {when: 1425808800, index: 0, isstd: false, isutc: false}, {when: 1446368400, index: 1, isstd: false, isutc: false}, {when: 1457863200, index: 0, isstd: false, isutc: false}, {when: 1478422800, index: 1, isstd: false, isutc: false}, {when: 1489312800, index: 0, isstd: false, isutc: false}, {when: 1509872400, index: 1, isstd: false, isutc: false}, {when: 1520762400, index: 0, isstd: false, isutc: false}, {when: 1541322000, index: 1, isstd: false, isutc: false}, {when: 1552212000, index: 0, isstd: false, isutc: false}, {when: 1572771600, index: 1, isstd: false, isutc: false}, {when: 1583661600, index: 0, isstd: false, isutc: false}, {when: 1604221200, index: 1, isstd: false, isutc: false}, {when: 1615716000, index: 0, isstd: false, isutc: false}, {when: 1636275600, index: 1, isstd: false, isutc: false}, {when: 1647165600, index: 0, isstd: false, isutc: false}, {when: 1667725200, index: 1, isstd: false, isutc: false}, {when: 1678615200, index: 0, isstd: false, isutc: false}, {when: 1699174800, index: 1, isstd: false, isutc: false}, {when: 1710064800, index: 0, isstd: false, isutc: false}, {when: 1730624400, index: 1, isstd: false, isutc: false}, {when: 1741514400, index: 0, isstd: false, isutc: false}, {when: 1762074000, index: 1, isstd: false, isutc: false}, {when: 1772964000, index: 0, isstd: false, isutc: false}, {when: 1793523600, index: 1, isstd: false, isutc: false}, {when: 1805018400, index: 0, isstd: false, isutc: false}, {when: 1825578000, index: 1, isstd: false, isutc: false}, {when: 1836468000, index: 0, isstd: false, isutc: false}, {when: 1857027600, index: 1, isstd: false, isutc: false}, {when: 1867917600, index: 0, isstd: false, isutc: false}, {when: 1888477200, index: 1, isstd: false, isutc: false}, {when: 1899367200, index: 0, isstd: false, isutc: false}, {when: 1919926800, index: 1, isstd: false, isutc: false}, {when: 1930816800, index: 0, isstd: false, isutc: false}, {when: 1951376400, index: 1, isstd: false, isutc: false}, {when: 1962871200, index: 0, isstd: false, isutc: false}, {when: 1983430800, index: 1, isstd: false, isutc: false}, {when: 1994320800, index: 0, isstd: false, isutc: false}, {when: 2014880400, index: 1, isstd: false, isutc: false}, {when: 2025770400, index: 0, isstd: false, isutc: false}, {when: 2046330000, index: 1, isstd: false, isutc: false}, {when: 2057220000, index: 0, isstd: false, isutc: false}, {when: 2077779600, index: 1, isstd: false, isutc: false}, {when: 2088669600, index: 0, isstd: false, isutc: false}, {when: 2109229200, index: 1, isstd: false, isutc: false}, {when: 2120119200, index: 0, isstd: false, isutc: false}, {when: 2140678800, index: 1, isstd: false, isutc: false}, ], cacheStart: 1457863200, cacheEnd: 1478422800, cacheZone: {name: "PDT", offset: -25200, isDST: true}, }, }, }, DeletionGracePeriodSeconds: 0, Labels: { "name": "nginx", "pod-template-hash": "783459730", }, Annotations: { "deployment.kubernetes.io/desired-replicas": "0", "deployment.kubernetes.io/max-replicas": "1", "deployment.kubernetes.io/revision": "3", }, OwnerReferences: nil, Finalizers: ["orphan"], }, Spec: { Replicas: 0, Selector: { MatchLabels: { "name": "nginx", "pod-template-hash": "783459730", }, MatchExpressions: nil, }, Template: { ObjectMeta: { Name: "", GenerateName: "", Namespace: "", SelfLink: "", UID: "", ResourceVersion: "", Generation: 0, CreationTimestamp: { Time: {sec: 0, nsec: 0, loc: nil}, }, DeletionTimestamp: nil, DeletionGracePeriodSeconds: nil, Labels: { "pod-template-hash": "783459730", "name": "nginx", }, Annotations: nil, OwnerReferences: nil, Finalizers: nil, }, Spec: { Volumes: nil, InitContainers: nil, Containers: [ { Name: "nginx", Image: "gcr.io/google_containers/nginx:1.7.9", Command: nil, Args: nil, WorkingDir: "", Ports: nil, Env: nil, Resources: {Limits: nil, Requests: nil}, VolumeMounts: nil, LivenessProbe: nil, ReadinessProbe: nil, Lifecycle: nil, TerminationMessagePath: "/dev/termination-log", ImagePullPolicy: "IfNotPresent", SecurityContext: nil, Stdin: false, StdinOnce: false, TTY: false, }, ], RestartPolicy: "Always", TerminationGracePeriodSeconds: 0, ActiveDeadlineSeconds: nil, DNSPolicy: "ClusterFirst", NodeSelector: nil, ServiceAccountName: "", NodeName: "", SecurityContext: { HostNetwork: false, HostPID: false, HostIPC: false, SELinuxOptions: nil, RunAsUser: nil, RunAsNonRoot: nil, SupplementalGroups: nil, FSGroup: nil, }, ImagePullSecrets: nil, Hostname: "", Subdomain: "", }, }, }, Status: { Replicas: 0, FullyLabeledReplicas: 0, ObservedGeneration: 5, }, }, ] to have length 0

**Comment by pwittrock** [comment]
@janetkuo Is this the same as the other issues you have seen?

**Comment by davidopp** [comment]
failing in
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gce-cvm-1.3-cvm-1.4-upgrade-master

**Comment by davidopp** [comment]
dup #32697
