### ISSUE TITLE
e2e permafail on upgrade: [k8s.io] Pods should not start app containers if init containers fail on a RestartAlways pod

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#32918]
on [kubernetes-e2e-gce-1.3-1.4-upgrade-master](http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GCE/job/kubernetes-e2e-gce-1.3-1.4-upgrade-master/5/)

[k8s.io] Pods should not start app containers if init containers fail on a RestartAlways pod

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:913 Expected <*errors.errorString | 0xc8200e20d0>: { s: "timed out waiting for the condition", } to be nil

**Comment by davidopp** [comment]
failing in
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gke-gci-1.3-gci-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gke-gci-1.3-cvm-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gke-cvm-1.3-gci-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gke-cvm-1.3-cvm-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gce-cvm-1.3-cvm-1.4-upgrade-cluster

**Comment by davidopp** [comment]
dup #32714
