### ISSUE TITLE
cAdvisor in 1.4 does not work on RHEL

### ISSUE THREAD

**Issue by eparis** [kubernetes/kubernetes#32917]
see: https://github.com/google/cadvisor/issues/1461

This issue is purely for tracking purposes.

**Comment by dchen1107** [comment]
Both @derekwaynecarr and I think this shouldn't be the blocker for 1.4 since it only impacts running cAdvisor or Kubelet in a container. I can be convinced though.

**Comment by four43** [comment]
This would break usage in CoreOS too, no? They have provisioning docs that run the Kubelet as a container with the rkt engine.

https://github.com/coreos/coreos-kubernetes

**Comment by dchen1107** [comment]
cc/ @philips @euank on CoreOS use case.

**Comment by philips** [comment]
cc @aaronlevy @pbx0

**Comment by philips** [comment]
@aaronlevy didn't see any failures in testing beta.8 but the way we run kubelet under rkt is different than I think the issue referred does cAdvisor in a docker container.

We will see if beta.9 turns anything up.

**Comment by aaronlevy** [comment]
This specific issue does not seem to affect CoreOS installs (tested beta.8 & beta.9).

**Comment by derekwaynecarr** [comment]
The fix was merged to cAdvisor

https://github.com/google/cadvisor/pull/1476

**Comment by derekwaynecarr** [comment]
The backport into cAdvisor v0.24 is here: https://github.com/google/cadvisor/pull/1478
