### ISSUE TITLE
kubernetes-e2e-gce-1.3-1.4-upgrade-master fails with ./hack/e2e.go: no such file or directory

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#32912]
14:34:52 2016/09/16 14:34:52 e2e.go:437: Running: UpgradeUp
*14:34:52 stat ./hack/e2e.go: no such file or directory*
14:34:52 2016/09/16 14:34:52 e2e.go:439: Step 'UpgradeUp' finished in 8.50509ms
14:34:52 2016/09/16 14:34:52 e2e.go:115: error starting cluster to upgrade: error running UpgradeUp: exit status 1

**Comment by quinton-hoole** [comment]
This started failing between [8:00 AM](http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GCE/job/kubernetes-e2e-gce-1.3-1.4-upgrade-master/5/) and [2:30PM](http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GCE/job/kubernetes-e2e-gce-1.3-1.4-upgrade-master/6/) today.

I think @ixdy mentioned that there was a corruption of the build tarball in GCS this morning.  Issue # for that?

**Comment by ixdy** [comment]
https://github.com/kubernetes/test-infra/issues/599

**Comment by quinton-hoole** [comment]
Has not re-occurred.  Closing.
