### ISSUE TITLE
e2e permafail on upgrade: [k8s.io] Monitoring should verify monitoring pods and all cluster nodes are available on influxdb using heapster.

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#32922]
On [kubernetes-e2e-gce-1.3-1.4-upgrade-master](http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GCE/job/kubernetes-e2e-gce-1.3-1.4-upgrade-master/5/)

[k8s.io] Monitoring should verify monitoring pods and all cluster nodes are available on influxdb using heapster.

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/monitoring.go:43 Sep 16 12:34:13.053: Expected one column for query "show tag values from \"cpu/usage\" with key = pod_id". Found [key value]

**Comment by davidopp** [comment]
failing in
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gce-cvm-1.3-cvm-1.4-upgrade-master

**Comment by davidopp** [comment]
dup #31626
