### ISSUE TITLE
More ingress TLS modes

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#32928]
Do: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/v1beta1/types.go#L695
most importantly, https to backend because the customer doesn't have clarity into where exactly a CP is terminating their connection, and obviously no one wants to terminate in some other continent and go over the internet via http because sometimes governments do weird things with http exit traffic.

**Comment by bprashanth** [comment]
We need to cover at least 3 more cases, I think
1. Re-encrypt blindly, using the cert supplied by the backend. It may be self signed. 
2. Only trust a specific public key, or a key signed by a given CA.
3. Authenticate to the server using a client cert. 

__Hostname__: In all 3 cases the hostname in the Host header and/or SNI extension sent by the LB and used by the backend to identify the cert to send back, can be the hostname specified in the ingress. I'm not sure what the spec should say (if anything) about the desired behavior when this hostname doesn't match the name in the cert, I'd expect a failure, but I don't think cloudproviders are capable of this. In fact GCE is only capable of 1 right now, while AWS can do 1 and 2.

__Health check__: In all 3 cases, the health check should also default to https. 

__Implementation__:
For 1, we can probably get away with just modifying the protocol section of the Service port. If it says "HTTPS" (currently only TCP and UDP are available), we assume the user wishes to re-encrypt traffic between LB and backend and create a HTTPS backend + HTTPS health check. 

For 2, we will need 1 and another pointer in the ingress.tls section, pointing at the public key.
For 3, we will need 1 and another pointer in the ingress.tls section, pointing at the client cert. 

2 and 3 can be used together (verify the cert given by the backend, then prove your identity to the backend), so we probably need a field for each in ingress.tls. 

__Summary__: if we find a ServicePort with protocol set to HTTPS, we create a HTTPS health check, then look in the ingress.tls section. 
* If theres no ingress.tls, we accept on :80 and encrypt to backend
* If there's ingress.tls but no additional verification certificate, we reencrypt with whatever the backend gives us
* If there's ingress.tls.verifyCert, we verify the given cert
* If there's ingress.tls.clientCert and the backend asks for a clientCert, we present it 

__Open questions__: 

1.Should we specify protocol=HTTP in the serviceport, or the ingress Backend pointing to the service port? 

HTTPS also qualifies as TCP. If we do the latter, a user can have 2 ingresses pointing at the same Service Port, one of which does normal HTTPS (url map, so the LB decrypts, applies map, reencrypts), and the second doing TLS passthrough (no url map so the LB doesn't even decrypt, it just routes based on SNI hostname). 

OTOH, I'm not sure how common the TCP->backend<-HTTPS use case it and decoupling them will lead to confusion.

2.Should we specify the client cert per ingress or per backend? 

Each backend might expect a different client cert, and require a different verification cert, so maybe it's better to shove this in the backends? 

@kubernetes/sig-network-feature-requests

**Comment by bowei** [comment]
@nicksardo  is this covered by the backside re-encrypt? close if no longer relevant

/assign @nicksardo

**Comment by nicksardo** [comment]
#1 is implemented and we haven't heard from customers requiring 2/3. For those options, I believe we would need GCP's backend service to support such control/verification. 

I recommend closing this issue.

**Comment by cblecker** [comment]
@nicksardo Do you have the relevant PRs that this was implemented in (out of interest)?

**Comment by nicksardo** [comment]
https://github.com/kubernetes/ingress/pull/519

**Comment by cblecker** [comment]
@nicksardo Thank you!
