### ISSUE TITLE
e2e permafail on upgrade: [k8s.io] Pods should invoke init containers on a RestartAlways pod

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#32920]
on [kubernetes-e2e-gce-1.3-1.4-upgrade-master](http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GCE/job/kubernetes-e2e-gce-1.3-1.4-upgrade-master/5/)

[k8s.io] Pods should invoke init containers on a RestartAlways pod

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:798 Expected : 0 to equal : 2

**Comment by davidopp** [comment]
dup #32711
