### ISSUE TITLE
e2e permafail on upgrade: [k8s.io] Pods should invoke init containers on a RestartNever pod

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#32923]
On [kubernetes-e2e-gce-1.3-1.4-upgrade-master/5/](http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GCE/job/kubernetes-e2e-gce-1.3-1.4-upgrade-master/5/)

[k8s.io] Pods should invoke init containers on a RestartNever pod

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:729 Expected : 0 to equal : 2

**Comment by davidopp** [comment]
failing in
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gke-gci-1.3-gci-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gke-gci-1.3-cvm-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gke-cvm-1.3-gci-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gke-cvm-1.3-cvm-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.3-1.4-upgrade#gce-cvm-1.3-cvm-1.4-upgrade-cluster

**Comment by davidopp** [comment]
dup #32712
