### ISSUE TITLE
Remove VIP from OpenStack LoadBalancer Ingress IPs

### ISSUE THREAD

**Issue by fdangtran** [kubernetes/kubernetes#32924]
I don't see the point of including the VIP of the OpenStack LB as part of the Status.LoadBalancerIngress IPs of a service along with the floating IP associated with it. The VIP can be accessed only within the OpenStack cluster not from outside the cluster:

```
kubectl describe svc
Name:           tweets-web
Namespace:      default
Labels:         name=tweets-web
Selector:       name=tweets-web
Type:           LoadBalancer
IP:         10.254.2.55
LoadBalancer Ingress:   172.20.21.62, 10.194.146.107
Port:           <unset> 80/TCP
NodePort:       <unset> 30789/TCP
Endpoints:      10.100.13.6:8080
Session Affinity:   None
```

An annoying side effect of this occurs when creating a federated service: a DNS record is created with both the public (Internet) IP and the internal VIP because the federation-controller cannot know which IP is global.
Removing this VIP would make the behavior of the OpenStack provider consistent with other cloud providers (aws, gce) as far as LB ingress IPs are concerned.

**Comment by zhouhaibing089** [comment]
> The VIP can be accessed only within the OpenStack cluster not from outside the cluster

Generally, the VIP on the load balancer is accessible outside of the cluster, that why it called a virtual IP.

Curious about how floating ip showed up, and I do not think there is floating ip things in cloud provider?

**Comment by ccatlett2000** [comment]
The VIP address is from the network the load balancer is deployed onto. As that is likely a private network for kubernetes the IP will be inaccessible outside the cluster, and require a floating IP.

While I don't think we should always drop the VIP, as it's possible to put a load balancer on an external network (then the VIP will be externally reachable), it certainly would be nice to have a config option, perhaps in the cloud config for OpenStack.

**Comment by dbaumgarten** [comment]
I also would like tho have the option to remove the VIP-Address from the List of IP-Addresses.

After my opinion, the best would be to completely remove the VIP-Address from list, but I understand, that it would probably be the best to have an option for this.

But having a "global" option inside the cloud-config fells strange. What about having an annotation for the LoadBalancer ressource to choose what addresses should be shown for each LoadBalancer individually.

The question is, what should be the default-case if no annotation is present?
I think per default the VIP-Address should be excluded from the List. This might break existing deployments, but it is what you want in 98% of the cases. What do you think?

If we can decide what we want to do I would be happy to create a PR for this.

**Comment by ccatlett2000** [comment]
Could we just not display them for `kubectl`, but leave them in the API? That shouldn't break existing deployments unless they're scraping `kubectl` responses for info (which is a horrible idea anyways).

I agree with the idea of using an annotation to control this behavior, and defaulting to not showing the VIP.

**Comment by dbaumgarten** [comment]
But the IPs beeing in the API is the main problem here, because anyone and anything that is retrieving the IPs the right way (via the API) is getting "wrong" IPs. One example are the DNS-Entries for federated Services. Having VIP-Addresses in the list of IPs breaks the whole functionality of federated Services.

**Comment by dims** [comment]
@grahamhayes any thoughts on this one?
