### ISSUE TITLE
e2e permafail on upgrade: [k8s.io] Deployment ... (3 tests fail)

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#32927]
On [kubernetes-e2e-gce-1.3-1.4-upgrade-master](http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GCE/job/kubernetes-e2e-gce-1.3-1.4-upgrade-master/5/)

**[k8s.io] Deployment RollingUpdateDeployment should delete old pods and create new ones**

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:58 Expected <[]extensions.ReplicaSet | len:1, cap:1>: [ { TypeMeta: {Kind: "", APIVersion: ""}, ObjectMeta: { Name: "test-rolling-update-deployment-3580733253", 

yada yada

**[k8s.io] Deployment deployment should support rollback**

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:76 Expected <[]extensions.ReplicaSet | len:1, cap:1>: [ { TypeMeta: {Kind: "", APIVersion: ""}, ObjectMeta: { Name: "test-rollback-deployment-2736956791", GenerateName: "", Namespace: "

yada yada 

**[k8s.io] Deployment paused deployment should be ignored by the controller**

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:73 Expected error: <*errors.errorString | 0xc8200e20d0>: { s: "timed out waiting for the condition", } timed out waiting for the condition not to have occurred

**Comment by pwittrock** [comment]
I think I know what these are about and believe Janet cherrypicked a fix into the 1.2 tests.  These were not failing in gke 1.3->1.4 (likely only by luck and very bizarre race symptoms), so the cherrypick test fixes might not have made it into the 1.3 branch.

**Comment by quinton-hoole** [comment]
Isn't there a problem with the assumption that all users will first upgrade
their clusters to the most recent v1.3.x (that includes e.g. that
cherrypick) before being able to successfully upgrade to v1.4.0 ?

Besides that, do we know that the upgrade from 1.3.w to 1.3.x (for any w <
x) will not display the same failure mode?

Mostly I'm trying to figure out how useful it is in practice to patch 1.3
to make upgrades to 1.4 work correctly. Do we need to figure a way to fix
it in 1.4 rather.

Note: I don't understand the specifics of this failure - I'm asking at a
more general level.

**Comment by davidopp** [comment]
failing in
https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-gci-1.2-gci-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-gci-1.2-cvm-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-cvm-1.2-gci-1.4-upgrade-cluster
https://k8s-testgrid.appspot.com/google-1.2-1.4-upgrade#gke-cvm-1.2-cvm-1.4-upgrade-cluster

**Comment by janetkuo** [comment]
Should be fixed by #33030
