### ISSUE TITLE
fields.Selector should support more operator like 'in'

### ISSUE THREAD

**Issue by 249043822** [kubernetes/kubernetes#32946]
As fields.Selector only support '=' or '!=' now, it's limited, for example, i want to watch secrets with names "aa", "bb","cc" ...,  i could not archive because in the fields.selector, the field only has one value, if it could support 'in', we can do like inTerm{field:"metadata.name", value:"aa,bb,cc"}

**Comment by liggitt** [comment]
I'm not sure exposing complex field selectors are desired generally, given the current inability of storage to efficiently index on arbitrary fields. In the particular case (kubelet watching secrets for a pod), that also would result in one watch per pod, which would not scale well.

**Comment by 249043822** [comment]
Is  one watch per pod necessary?  could we merge the secrets bounded to the current pods listed first and use only one watch? still if the secrets being watched don't changed(has no add or remove referenced by pods), the watch could being kept continue using the current field value set

**Comment by liggitt** [comment]
> could we merge the secrets bounded to the current pods listed first and use only one watch

that would mean every new pod that got scheduled (which happens very frequently) would require reestablishing the watch

> still if the secrets being watched don't changed(has no add or remove referenced by pods)

pods in different namespaces will always reference different secrets

**Comment by twilco** [comment]
I'd like to be able to `get pods` that are `Pending` or `Running`, but currently can't due to this issue (unless I'm missing something).  For example:

`kubectl get pods --field-selector status.phase in (Running, Pending)`

https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase

**Comment by stefanlasiewski** [comment]
This is a desirable feature for multi-tenancy. If users are able to create namespaces then it becomes impractical to use the `!=` operator to exclude arbitrary namespaces. Instead, we need to be able to select resources based on an 'include list', such as:

```
kubectl get deploy --field-selector namespace=={kube-system,ingress-nginx,cattle-system}
```

**Comment by et304383** [comment]
Can't believe this hasn't been implemented yet.  So we're forced to rely on grep?

/reopen /remove-lifecycle rotten

**Comment by mattrpav** [comment]
+1 on adding an 'in' and a wildcard character '*'

**Comment by wind57** [comment]
one more use case that we are facing. There are 1000s of config maps in a namespace, but we need to read only 10. We have two options: read all of them and filter for those 10 by name (takes time to read _all_); read 10 of them individually, which is again not ideal at all.

**Comment by darkn3rd** [comment]
What was the final solution?

**Comment by et304383** [comment]
> What was the final solution?

Probably to just filter client side.  I don't think Kubernetes is focused on usability. 😆

**Comment by rqueraud** [comment]
I wanted to filter on "status.phase in (Succeeded,Failed)", ended up doing the opposite : 
"status.phase!=Running,status.phase!=Pending".

**Comment by ydmao** [comment]
[liggitt](https://github.com/liggitt) - curious about the storage performance argument. Given that "F!=D,F!=E,..." is supported, shouldn't supporting "F in (A,B,C)" just serves as a syntax sugar (which is very handy for many use cases as people testified above) while yielding the same performance (or add same/similar performance pressure to the storage server)?
