### ISSUE TITLE
Pod network failure on master node restart when using ClusterIP

### ISSUE THREAD

**Issue by tristanz** [kubernetes/kubernetes#32940]
I have observed network failures when the master node restarts and pods use fixed ClusterIPs.  

I have two services (e.g. web and db) on the master node that use ClusterIP (for various reasons).  When I restart the master node of my cluster (`shutdown -r now`), everything comes back except the the web container can no longer connect to the database container (ClusterIP 10.0.0.128, PodIP 10.47.44.3).  However I can connect from the host and containers on other nodes.

The behavior is:

```
CONTAINER echo "ping" | ncat 10.0.0.128 5432 -> FAILED
HOST echo "ping" | ncat 10.0.0.128 5432 -> OK
CONTAINER echo "ping" | ncat 10.47.44.3 5432 -> OK
HOST echo "ping" | ncat 10.47.44.3 5432 -> OK
```

Restarting the kubelet fixes the issue.

**Kubernetes version**
1.3.7

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CentOS 7.2
- **Kernel** (e.g. `uname -a`): 3.10.0-327.28.3.el7.x86_64

**Comment by thockin** [comment]
A whole lot has changed in 1.4, 1.5 and 1.6 (and soon 1.7).  Can you try to repro this on 1.5 or 1.6?
