### ISSUE TITLE
List/Watch events for objects matching a label query

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#3295]
Instead of forcing users to list all the pods they're interested in and then ask for all the events for all those pods, apiserver should accept a label query directly.

The easiest way to do this is for apiserver to store the labels in the InvolvedObject section of events, but that's going to consume a lot of space.

**Comment by xudifsd** [comment]
similar to #5548 & #4817

**Comment by smarterclayton** [comment]
I think we should close this - no one has asked for it in a while, and it's just not high enough on the priority list.

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (151/150 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:7033)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-5c7e-dev=imwiz.com@sgmail.github.com>)
	id 1dGTKG-000TQm-Pi
	for dev@imwiz.com; Thu, 01 Jun 2017 10:51:57 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=RvXuC9hmRUj8qs+npsfFwMjLXXM=; b=Q26fdFrABsOxv9zC
	tLGX4DDWhHX5uB5xd2ZSnlyjldGRnl6lRi6Bm7mcKHSXErDL/RzFuJ6o+sAw1wxM
	ucgZiENSfNKEpj86R6BwXkIk6eqlxj+gFNsfYFho/09xdh0eYIFHOUGMHZP5Za8f
	Eun2cySUKV5ZLhZAQ8eyjGcbuY4=
Received: by filter1091p1mdw1.sendgrid.net with SMTP id filter1091p1mdw1-10927-59304621-57
        2017-06-01 16:51:45.759368763 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id QLdBeqO-QU6nxSE4Nx1PSA
	for <dev@imwiz.com>; Thu, 01 Jun 2017 16:51:45.717 +0000 (UTC)
Date: Thu, 01 Jun 2017 09:51:45 -0700

**Comment by candyleer** [comment]
wait for this feature

**Comment by seamounts** [comment]
wait for this feature
