### ISSUE TITLE
[Pet Set] Internal Replicas type should be int32

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#32993]
I find the type of `Replicas` in apps/types.go is `int` while the type of `Replicas`(https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/types.go#L88) in `v1alpha1/types.go` is `int32`(https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/v1alpha1/types.go#L86)

**Comment by m1093782566** [comment]
Use go l.6 instead of 1.7 can get rid of `type checker error` mentioned before.

**Comment by bprashanth** [comment]
I don't know why you're hitting issues but petset replicas should be int32 in internal types (this is a bug)

**Comment by m1093782566** [comment]
@bprashanth 

> but petset replicas should be int32

Could you please explain why?

> this is a bug

Can we fix it? Or could you please tell me how to fix it? I am still stuck in this issue.

My question is can we change the type declaration of `replicas`  both in `apps/types.go` and `v1alpha1/types.go` to int32(or int)? It make new beginner(like me) so confused.

BTW, I find some other places use the same `int32` both in `types.go` and `{group/version}/types.go`, such as [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1449) and [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1449)

**Comment by bprashanth** [comment]
regardless it should obviously build so that is probably something wrong in your tree/environment (or the submit queue and e2e would be red)

**Comment by bprashanth** [comment]
>Could you please explain why we can't use int?

sometimes an int is 4 bytes and sometimes its 8 but an int32 is always 32bits

**Comment by m1093782566** [comment]
@bprashanth 

>regardless it should obviously build so that is probably something wrong in your tree/environment

Yes, I missed something in `apps/v1apha1/types.go` and my issue has nothing to do with petset replicas type.

> sometimes an int is 4 bytes and sometimes its 8 but an int32 is always 32bits

Yes, I agree with you. I prefer to change replicas type from int to int32 as well.
