### ISSUE TITLE
kube-dns performs poorly when upstream dns server is out of service

### ISSUE THREAD

**Issue by jsravn** [kubernetes/kubernetes#32992]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
## kube-dns, resolv.conf, timeout, skydns

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
1.3.6 / kube-dns v17.1

**Environment**:
- **Cloud provider or hardware configuration**:
  AWS
- **OS** (e.g. from /etc/os-release):
  centos7
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Host resolv.conf, as used in kube-dns container:

```
search eu-west-1.compute.internal
nameserver 10.10.224.4
nameserver 10.10.228.4
nameserver 10.10.232.4
options rotate attempts:1 timeout:1
options ndots:5
```

If I disable `10.10.224.4`, every few queries it takes 5s to resolve (resulting in timeouts on other pods). Here's what it looks like when running from the kube-dns pod:

```
# time nslookup gatech.edu.eu-west-1.compute.internal
nslookup: can't resolve 'gatech.edu.eu-west-1.compute.internal'
Command exited with non-zero status 1
real    0m 0.00s
user    0m 0.00s
sys     0m 0.00s
/ # time nslookup gatech.edu.eu-west-1.compute.internal
Server:    10.50.224.4
Address 1: 10.50.224.4

nslookup: can't resolve 'gatech.edu.eu-west-1.compute.internal'
Command exited with non-zero status 1
real    0m 5.01s
user    0m 0.00s
sys     0m 0.00s
/ # time nslookup gatech.edu.eu-west-1.compute.internal
Server:    10.50.224.4
Address 1: 10.50.224.4

nslookup: can't resolve 'gatech.edu.eu-west-1.compute.internal'
Command exited with non-zero status 1
real    0m 5.00s
user    0m 0.00s
sys     0m 0.00s
/ # time nslookup gatech.edu.eu-west-1.compute.internal
Server:    10.50.224.4
Address 1: 10.50.224.4

nslookup: can't resolve 'gatech.edu.eu-west-1.compute.internal'
Command exited with non-zero status 1
real    0m 0.00s
user    0m 0.00s
sys     0m 0.00s
/ # time nslookup gatech.edu.eu-west-1.compute.internal
Server:    10.50.224.4

Address 1: 10.50.224.4

nslookup: can't resolve 'gatech.edu.eu-west-1.compute.internal'
Command exited with non-zero status 1
real    0m 5.01s
user    0m 0.00s
sys     0m 0.00s
/ # 
/ # time nslookup gatech.edu.eu-west-1.compute.internal
Server:    10.50.224.4
Address 1: 10.50.224.4

nslookup: can't resolve 'gatech.edu.eu-west-1.compute.internal'
Command exited with non-zero status 1
real    0m 0.00s
user    0m 0.00s
sys     0m 0.00s
/ # time nslookup gatech.edu.eu-west-1.compute.internal
Server:    10.50.224.4
Address 1: 10.50.224.4
```

And from another pod:

```
/# time getent ahosts gatech.edu
130.207.160.173 STREAM gatech.edu
130.207.160.173 DGRAM  
130.207.160.173 RAW    

real    0m0.009s
user    0m0.000s
sys     0m0.002s
mypod:/# time getent ahosts gatech.edu
130.207.160.173 STREAM gatech.edu
130.207.160.173 DGRAM  
130.207.160.173 RAW    

real    0m2.007s
user    0m0.000s
sys     0m0.002s
mypod:/# time getent ahosts gatech.edu
130.207.160.173 STREAM gatech.edu
130.207.160.173 DGRAM  
130.207.160.173 RAW    

real    0m0.006s
user    0m0.000s
sys     0m0.002s
mypod:/# time getent ahosts gatech.edu
130.207.160.173 STREAM gatech.edu
130.207.160.173 DGRAM  
130.207.160.173 RAW    

real    0m0.005s
user    0m0.000s
sys     0m0.001s
mypod:/# time getent ahosts gatech.edu
130.207.160.173 STREAM gatech.edu
130.207.160.173 DGRAM  
130.207.160.173 RAW    

real    0m2.008s
user    0m0.000s
sys     0m0.002s
```

I can sort of work around this by removing the `eu-west-1.compute.internal` search domain, which prevents the search NXDOMAIN that causes random hangs.

**What you expected to happen**:

I expect it to resolve the NXDOMAIN quickly even if one of the nameservers is down. Or at worst, take up to `timeout:1`. The timeout:1 option seems to be ignored, and it takes 5 seconds to timeout whenever it hits the down server.

Also the rotate option seems ignored, so all the load from kube-dns happens on the primary dns server.    (need to verify this, just noticed from quick observation that the primary server gets almost all the queries)

Ideally, in my opinion, kube-dns would use something like musl and resolve against all the nameservers in parallel, making it robust to failure.

**How to reproduce it** (as minimally and precisely as possible):
1. Have multiple nameservers in host's resolv.conf 
2. Turn off the first nameserver
3. Try to resolve domains that would normally return NXDOMAIN

**Anything else do we need to know**:

**Comment by jsravn** [comment]
I think I'm going to just run dnsmasq locally on each node to handle parallel resolving. It'd be nice if kube-dns handled this better. Perhaps some documentation of this behaviour would be useful, since it took me a while to figure out what was going on.

**Comment by MrHohn** [comment]
Related to #32749.

**Comment by jsravn** [comment]
Update: we moved to dnsmasq which works great. kube-dns is still somewhat a weak spot though, with internal queries failing rarely (but more than any of our other DNS servers). Other issues for that though.

**Comment by cmluciano** [comment]
/close

@jsravn upgraded to a version with dnsmasq to resolve
