### ISSUE TITLE
MacOS Sierra Support: Build gcloud component and kubectl distribution with Go 1.7.x

### ISSUE THREAD

**Issue by gerred** [kubernetes/kubernetes#32999]
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:13:23Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Apple MacBook Pro
- **OS** (e.g. from /etc/os-release): MacOS Sierra
- **Kernel** (e.g. `uname -a`): Darwin 16.0.0
- **Install tools**:  `gcloud components install kubectl`, `brew install kubernetes-cli`, or download from release
- **Others**:
Tested on both a GKE cluster and minikube to be sure. Also tested with running kubectl from Google Cloud Shell and a Docker container, and `kubectl` works as expected on both Kubernetes environments from these client environments.

**What happened**:
`kubectl` has unpredictable errors performing any operations. There's no single error. Sometimes the process hangs, sometimes it panics, sometimes there's connection issues to the cluster.

**What you expected to happen**:
`kubectl` commands to run as expected, without hangs, segfaults, or network issues.

**How to reproduce it** (as minimally and precisely as possible):
1. Upgrade to MacOS Sierra
2. Use kubectl

**Anything else do we need to know**:
Compiling kubectl for OSX with Go 1.7.x will fix this, as fixes for MacOS Sierra are in Go 1.7.

I compiled a version of kubectl from master with version:

```
Client Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.0.598+ff1cec99ccdecf", GitCommit:"ff1cec99ccdecfda7f4fedd1fd97ad1f44fd4010", GitTreeState:"clean", BuildDate:"2016-09-12T07:24:10Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
````

and it works as expected.

I'm happy to pull request something to fix this, but I don't want to make the assumption that everything needs to be updated to Go 1.7. Also, I'm not sure how the gcloud `kubectl` component is related or diverges from the release build version, so if I can understand the nuances I can put something together to fix this.

**Comment by jeroenvisser101** [comment]
Can confirm, if it helps, I've collected some of these errors [here](https://gist.github.com/jeroenvisser101/5822d7c22ac75eaf126a3c8d64c2de77)

**Comment by dims** [comment]
@jeroenvisser101 @gerred work is being done here - https://github.com/kubernetes/kubernetes/pull/28742

**Comment by kristijanmatic** [comment]
@gerred did you manage to build with 1.7? Any way you could share the binary - my mac satarts flying during build

**Comment by gerred** [comment]
@Ghazgkull I wrote a blog post for this: https://medium.com/@gerred/kubectl-1-3-7-for-macos-sierra-ee2c483e283d short answer is: build your own kubectl

**Comment by ixdy** [comment]
kubectl 1.5 will be built with golang1.7 at some point, yes. we probably need to decide if we want to backport building kubectl with golang1.7 to release-1.4.

**Comment by ixdy** [comment]
Details for 1.4 [here](https://github.com/kubernetes/kubernetes/issues/33801#issuecomment-250890436).
