### ISSUE TITLE
GlusterFS dynamic provisioner doc is incomplete in 1.4 tree.

### ISSUE THREAD

**Issue by humblec** [kubernetes/kubernetes#33009]
**Environment**:
- **Cloud provider or hardware configuration**: GlusterFS

GlusterFS dynamic provisioner doc does not carry information ( examples/experimental/persistent-volume-provisioning/README.md ) about e2e configuration for getting it worked. There is no mention on how we can configure `heketi` and other details about the storage class parameters which provisioner takes.

**Comment by humblec** [comment]
PR #https://github.com/kubernetes/kubernetes/pull/31854

**Comment by msau42** [comment]
@humblec can you close this if it's complete?

**Comment by xiangpengzhao** [comment]
Yeah, this can be closed.
/sig docs
/sig storage
/cc @thockin @humblec
