### ISSUE TITLE
storage: in the future RBD images might become unaccessible in read-write mode

### ISSUE THREAD

**Issue by rzarzynski** [kubernetes/kubernetes#33013]
The storage plugin for Ceph RBD employs _advisory lock_ mechanism to provide basic fencing for RBD images. Lock management is performed with the CLI `rbd` command (`rbd lock add`, `rbd lock remove` and `rbd lock list`).

Unfortunately, _advisory locks_ use the same infrastructure which is necessary to handle images with `exclusive-lock` flag set. That's the default for new RBD images in Jewel. Actually this isn't an issue as the kernel RBD driver (`krbd`) doesn't support the feature. However, when `krbd` finally get it ([Ilya Dryomov is working on that](http://www.spinics.net/lists/ceph-devel/msg31216.html)), there might be a problem with mapping those images in the read-write mode.

The same, potential issue [stopped](https://lists.gnu.org/archive/html/qemu-devel/2016-04/msg04131.html) similar fencing solution [proposed to QEMU RBD driver](https://lists.gnu.org/archive/html/qemu-devel/2016-04/msg02422.html).

**Comment by dillaman** [comment]
What's the current use-case for the rbd advisory locking? Just wondering it would make sense to switch to the new Kraken+ managed lock API.

**Comment by smarterclayton** [comment]
Somewhat covered under https://github.com/kubernetes/kubernetes/pull/34160

**Comment by dillaman** [comment]
Chatted with @rzarzynski on IRC the other day and was provided some background that this is relevant for krbd (which won't support exclusive locking until the 4.9+ kernel and a future RHEL 7.x kernel) and in the short/intermediate-term that feature shouldn't be enabled for kubernetes RBD devices.

Longer term, I have created Ceph feature request tickets for disabling automatic exclusive lock transitions for krbd [1] and rbd-nbd [2] to allow kubernetes to be in charge of which client should own the lock (while being able to re-use rbd exclusive lock's built-in blacklist lock recovery). I also created a ticket from our backlog item to add librbd support to tcmu-runner [3].

[1] http://tracker.ceph.com/issues/17524
[2] http://tracker.ceph.com/issues/17488
[3] http://tracker.ceph.com/issues/17489
