### ISSUE TITLE
Document cloud provider expecatations

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33037]
As part of @kubernetes/sig-cluster-lifecycle documentation effort, we should document very clearly what are the requirements of cloud providers to function. Codifying this is great, but we should make sure we have a plain text version.

**Comment by justinsb** [comment]
The doc with the AWS assumptions (which is likely no longer up-to-date) is here: https://github.com/kubernetes/kubernetes/blob/master/docs/design/aws_under_the_hood.md

**Comment by roberthbailey** [comment]
@wlan0 - this seems related to factoring out the cloud providers (in particular, if we finish that effort we should be able to close this as obsolete).

**Comment by luxas** [comment]
cc @cheftako @jagosan @wlan0 @jhorwit2 Maybe we should start doing this soon-ish?
/remove-lifecycle stale

**Comment by jhorwit2** [comment]
@luxas @errordeveloper what exactly does this issue pertain to? I noticed `area/kubectl` which doesn't have any cloud provider expectations and a kubeadm referenced PR. 

Does the [new documentation](https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/) satisfy this issue? 

/area cloudprovider

**Comment by luxas** [comment]
Documenting how individual, existing in-tree cloud providers operate and expect from the environment, as well as outlining best-practices when appropriate.
