### ISSUE TITLE
CRI: Get ImageFS info for the runtime

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#33048]
kubelet currently [relies on cadvisor](https://github.com/kubernetes/kubernetes/blob/12c248315f8191396574085591e1d749ab0fe670/pkg/kubelet/cadvisor/cadvisor_linux.go#L189) to get the ImageFS info for supported runtimes, i.e., docker and rkt. Without this information, the disk manager would not function properly and kubelet will fail to start.

To get the image filesystem information, the following items are needed:
1. Get path from the runtime, i.e., need to add a new call `Info()` to `ImageService` in CRI. 
2. Plumb this information to cadvisor and use it to get `ImageFs` info.

/cc @timstclair @dchen1107 @kubernetes/sig-node

**Comment by feiskyer** [comment]
Do we need to make an abstraction above cadvisor first? (so as to leverage such functionality to runtimes not support cadvisor)

**Comment by yujuhong** [comment]
> Do we need to make an abstraction above cadvisor first? (so as to leverage such functionality to runtimes not support cadvisor)

It'd be good to do that in general. For this particular task, I don't think it's necessarily required.
On the other hand, there are some more concerns about whether container-level metrics need to be included in kubelet, so the metrics in CRI won't be defined until those issues are resolved.

**Comment by feiskyer** [comment]
> It'd be good to do that in general. For this particular task, I don't think it's necessarily required.
On the other hand, there are some more concerns about whether container-level metrics need to be included in kubelet, so the metrics in CRI won't be defined until those issues are resolved.

Hmm, makes sense.

Another problem, `Plumb this information to cadvisor and use it to get ImageFs info.`, is cadvisor general enough for all container runtimes? It requires `cadvisorfs.LabelDockerImages` or `cadvisorfs.LabelRktImages ` in our current implementations.

**Comment by yujuhong** [comment]
> Another problem, Plumb this information to cadvisor and use it to get ImageFs info., is cadvisor general enough for all container runtimes? It requires cadvisorfs.LabelDockerImages or cadvisorfs.LabelRktImages in our current implementations. Or are there any related issues to generalize this?

That's a good question. cadvisor is not general enough (to handle container metrics) for all container runtimes as it is today. We may not even be able to solve this in the future.
As for ImageFS, passing the path to the cadvisor *might* be enough. /cc @timstclair @vishh, who are more familiar with cadvisor code.

**Comment by Random-Liu** [comment]
This is similar with the container metrics problem. There are 2 options:

* **Option 1: Still let cadvisor detect the runtime type.** Add a new label `cadvisorfs.LabelRuntimeImages`. If it is passed to `GetFsInfo()`, cadvisor will return what it has docker or rkt.
  * **Pros:** Minimal code change before we figure out the relationship between cadvisor runtime detection and kubelet runtime interface.
  * **Cons:** New runtime still has to integrate with cadvisor.
* **Option 2: Let kubelet get runtime information with CRI and pass it to cadvisor when starting it.**
  * **Pros:** More general solution. New runtime only needs to integrate with Kubelet.
  * **Cons:** More code change. And may be conflict with the future plan given that we haven't decided it yet. Even if `imagefs` path is the only thing needed, this still requires more code change than option 1.

It looks like `Option 1` is better for now. And we can fix it with container metrics together, when we figure out the future plan.

Maybe in the future:
* cadvisor could monitor the system based on an initial configuration. The configuration may include something like: what is the cgroup hierarchy, where is the imagefs etc. And kubelet can customize the configuration based on information got from container runtime with CRI.
* Or CRI could be a separate project, and cadvisor could also get runtime information with CRI.
* ...

**Comment by yujuhong** [comment]
> It looks like Option 1 is better for now. And we can fix it with container metrics together, when we figure out the future plan.

Container metrics *may* or *may not* be handled by kubelet. It's still undetermined. Kubelet also doesn't rely on such stats today. 
On the other hand, ImageFS is essential for disk management and kubelet has to acquire this information. Option 2 also doesn't prevent us from adding more metrics calls in CRI in the future. If the change in cadvisor is not significant. I'd prefer going with option 2.

**Comment by Random-Liu** [comment]
> On the other hand, ImageFS is essential for disk management and kubelet has to acquire this information. 

I see your point, will try option 2. :)

**Comment by timstclair** [comment]
This is an example of where moving to on-demand collection would be very benefitial, and spare us some additional complexity. Which gives us option 3: expose an on-demand version of GetFsInfo which takes an arbitrary path to scan.

Off the top of my head, I'm not sure how much more work this option would be. One concern is that the call may be slow, and may need to happen in an async path.

**Comment by Random-Liu** [comment]
For option 2, we need to get some data from runtime through CRI and pass it to cadvisor. Then the most important thing is to figure out what cadvisor needs for fs info monitoring. Here is the summary of the current research:
* Option 1: **Storage Driver/Runtime level information.**
  * Information needed:
    * Docker: Docker Root Dir - `string`, Driver Type - `string`, Driver Status - `map[string]string` (See [here](https://github.com/docker/engine-api/blob/7cf26e0abb9d1c65d3dcfac41c9685541b9d4e6d/types/types.go#L208-L263))
    * Rkt: Rkt Data Dir (See [here](https://github.com/coreos/rkt/blob/master/api/v1alpha/api.pb.go#L486))
    * Other runtime?
  * Problems:
    * Docker specific logic: 
      * Storage root could be "docker root" or "docker root / driver type", For some drivers, docker will include storage root in `DriverStatus`, but not all. Cadvisor has to try appending the driver type itself. The logic is docker specific.
      * Possible solution:
        * Just let cadvisor try appending suffix regardless what the current runtime is, as long as it doesn't break other runtimes.
        * Pass both runtime root and storage root to cadvisor, and let cadvisor use storage root first if it presents.
    * Devicemapper specific logic:
      * Cadvisor has some device mapper specific logic based on the some [special key/values](https://github.com/google/cadvisor/blob/e97c522721eb14ab0ecc12b0157238f45e8c769e/utils/docker/docker.go#L28-L30) in `DriverStatus` returned by docker (See [here](https://github.com/google/cadvisor/blob/master/fs/fs.go#L166-L187)).
      * Possible solution:
        * Standardize the `DriverStatus`. If other runtime wants to add devicemapper support in the future, they have to return the same things.

* Option 2: **Mount information.**
  * Information needed: Mount info (source, mount point, major:minor, fstype) + DeviceMapper specific information.
  * Problems:
    * Devicemapper specific logic: Cadvisor need `pool name` to get the block size.

* Option 3: **Get ImageFs stats from CRI.**
  * Information needed: All [`FsInfo`](https://github.com/google/cadvisor/blob/master/info/v2/container.go#L201-L225).
  * Problems:
    * Each runtime has to implement imagefs stats, most of them may be using the same logic (?).

I'm not quite familiar with the image fs driver stuff, there may be some misunderstanding. Feel free to point out. :)

**Comment by timstclair** [comment]
Just to clarify, the option I proposed above was not to get the stats from the CRI. I was basically proposing the same thing as option 2, but the the information would be provided when the call to `GetFsInfo` was made, as opposed to when cAdvisor is started (and hence the information would be scraped then too, rather than pulled from the cache).

**Comment by yujuhong** [comment]
> Just to clarify, the option I proposed above was not to get the stats from the CRI. I was basically proposing the same thing as option 2, but the the information would be provided when the call to GetFsInfo was made, as opposed to when cAdvisor is started (and hence the information would be scraped then too, rather than pulled from the cache).

I think that'd be a cadvisor-optimization, but has less impact on runtime integration with kubelet.

**Comment by yifan-gu** [comment]
Another idea is to let runtime return FsInfo, and under the hood, shimcode can choose whether or not to call cadvisor's GetFsInfo().
Benefits:
- Makes kubelet depends less on cadvisor, but existing runtime can still use what's there.
- Runtime is free to choose implementing GetFsInfo() on its own.

I am open to whether add GetFsInfo() in CRI or GetSomeBasicFileFsInfoRequiredForCadvisor(). But basically we should guarantee that all runtime developer need to integrate is the CRI, there shouldn't be some implicit dependency around.

**Comment by yifan-gu** [comment]
cc @euank @lucab @s-urbaniak

**Comment by Random-Liu** [comment]
> The problem is that currently cadvisor doesn't do on-demand collection. 

@yifan-gu so what you mean is that:
* If the runtime wants to use cadvisor, it should:
  * integrate with cadvisor.
  * get stats from cadvisor in shim.
* If the runtime wants to use its own stuff, just do whatever it wants?

**Comment by yujuhong** [comment]
> But basically we should guarantee that all runtime developer need to integrate is the CRI, there shouldn't be some implicit dependency around.

Agreed. If option 2.2 in https://github.com/kubernetes/kubernetes/issues/33048#issuecomment-249029566 is sufficiently generic, it could serve the purpose. 

> Another idea is to let runtime return FsInfo, and under the hood, shimcode can choose whether or not to call cadvisor's GetFsInfo().
> Benefits:

This means every shim should vendor and run cadvisor, or completely rule out the possibility of running the shim as a separate process though. I am fine with the former, but just to want to highlight the requirement for the shim (e.g., running a separate instance of cadvisor in the background) .

**Comment by feiskyer** [comment]
> Option 2.2: Mount information.

Another concern of Option 2.2 is that more storage specific information may be required because of supporting new fs types. This is actually runtime's implementation detail. I think CRI shouldn't depends on it.

**Comment by yifan-gu** [comment]
> This means every shim should vendor and run cadvisor, or completely rule out the possibility of running the shim as a separate process though. I am fine with the former, but just to want to highlight the requirement for the shim (e.g., running a separate instance of cadvisor in the background) .

@yujuhong Runtime needs to vendor cadvisor? Yes. Runtime needs to run cadvisor in the background? I am not sure. Shouldn't it just use cadvisor as a library?

**Comment by Random-Liu** [comment]
> Shouldn't it just use cadvisor as a library?

cadvisor is running, monitoring and cache sys stats. As @timstclair mentioned above, it doesn't not support on-demand collection as a library. :(

**Comment by yujuhong** [comment]
I want to make sure that we're all on the same page, or at least know the implication for asking shims to provide stats for image filesystem. 

The shim can either:
 * run cadvisor as it is in the background; may provide slight performance overhead.
 * refactor cadvisor to use it to get on-demand stats; this could have the side-effect of long request latency, especially for disk usage stats. Could also refactor cadvisor to gather only image filesystem stats
 * write their own code

The alternative is the option 2.2 in https://github.com/kubernetes/kubernetes/issues/33048#issuecomment-249029566: kubelet gets mount information from the shim and feed it to cadvisor to get the stats. The downside is that we may need to grow the API soon to support other storage drivers.

If you have concerns about adding image filesystem stats in CRI, please speak up.
@kubernetes/sig-rktnetes @mrunalp (oci) @feiskyer

**Comment by derekwaynecarr** [comment]
This decision has ramifications for eviction, and the metrics/monitoring pipeline generally if I understand the scope of the issue (I may not).

Is this issue saying that the CRI is responsible for reporting per container usage stats?  For things like disk (imagefs/rootfs usage and inode consumption) as well as cpu/memory?  The `kubelet` stats summary endpoint uses `cAdvisor` exclusively for this information on a per container basis, and for per disk usage we need to handle consumption on the `rootfs` and the `imagefs` associated with a container/pod.

I am struggling keeping up with all of the re-factoring discussions associated with the CRI and understanding the associated time-lines for lining all these things up.  I also think this relates to the monitoring pipeline discussions.

/cc @DirectXMan12 @vishh

**Comment by vishh** [comment]
+1 for punting on this feature for v1.5. If evictions and monitoring
doesn't work in v1.5 that might be OK I hope.

**Comment by yifan-gu** [comment]
@yujuhong @dchen1107 @derekwaynecarr @vishh @euank 

Sorry I didn't speak out during hangout since I need to wrap up my mind a little bit.

I am OK with de-prioritize the discussion until after we got other core CRI APIs stable. But honestly I don't think adding GetImageFs() in the CRI will affect today's monitoring and disk eviction. The possible paths forward I could imagine are:

- We decide that we should get image/container info from runtime. So later we change monitoring/disk eviction to switch to use CRI. But even this happens, this is not gonna happen in 1.5.
- We decide runtime should integrate with cadvisor, and monitorning/disk eviction replies on cadvisor as today. If this happens, we will just abandon the GetImageFs() in the CRI, which I think is OK since the CRI is alpha.

That being said, I would like to follow up the discussion on the monitoring pipeline, etc, to know what might block us from moving off from cadvisor.

I am pushing on getting container infos from CRI for two reasons:

- Runtimes knows better about container infos
- cAdvisor doesn't have an explicit interface for runtimes to integrate with and test.
  
So **whether or not to move runtime integration off from cadvisor** seems to be the major decision we need to make. And if we decide to move off, it might means we need to change monitorning and disk eviction, etc. But if it's a good thing to make runtime **really pluggable**, then it's worth doing it IMO.

**Comment by yujuhong** [comment]
These are what I gathered from today's discussion: 
   - Design of the monitoring pipeline will be finalized in v1.5. Based on the decision, we can derive the required metrics from the runtime and tackle them altogether.
   - Even though we could add imagefs stats in CRI and iterate later, it's preferred to punt this to after v1.5 so people have more time and bandwidth to review.

For v1.5, we should make sure that using CRI,
  1. docker/rkt integration should get all the stats from cadvisor, as it is today.
  2. kubelet should have a stub for other runtimes so that kubelet can function even with some missing features (e.g., disk management and eviction); need to document the limitation of the api.

(1) and (2) need changes in kubelet and/or cadvisor. 

As for the api itself, we'll revisit after v1.5.

**Comment by Random-Liu** [comment]
Currently, metrics api test fails because `ImageFs.UsedBytes` is not populated. It relies on function `ImageStats` which is not implemented in kuberuntime.

However, it's hard to implement `ImageStats` based on current CRI.

Do we still need [`ImageFs.UsedBytes`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/stats/summary.go#L135)?

Currently, Kubelet gets all ImageFs stats from cadvisor except `ImageFs.UsedBytes` which is retrieved from runtime interface [`ImageStats`](https://github.com/kubernetes/kubernetes/blob/b60df6c312e94555b8268ea5b3d8f49bbefeded7/pkg/kubelet/container/runtime.go#L134).

The field is not used anywhere in K8s code base. And it is not that compatible with current CRI interface. Currently, from CRI we can only get per image status through [`ImageStatus`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/services.go#L83). However, for docker we can't directly sum up sizes of all images directly because of the layers.

Given that `ImageFs.UsedBytes` is not used anywhere in Kubernetes code base, do we still need it? If so, we need to:
Option 1: change CRI to return imagefs total usage directly.
Option 2: change CRI to return image layer information (assume all images are using layer mechanism, which is bad)

**Comment by yujuhong** [comment]
I think `ImageFs.UsedBytes` should be treated the same as other ImageFS stats we discussed, i.e., we'll deal with them together after 1.5.

For now, if there are real no consumer of such stats, we can either piece together some information from the cadvisor numbers (e.g., `capacity - available`), or returns 0.

**Comment by feiskyer** [comment]
@Random-Liu Even `ImageFs.UsedBytes` is resolved in cadvisor, CRI may still need changed for other runtimes except docker/rkt.

> So whether or not to move runtime integration off from cadvisor seems to be the major decision we need to make. And if we decide to move off, it might means we need to change monitorning and disk eviction, etc. But if it's a good thing to make runtime really pluggable, then it's worth doing it IMO.

I suggest further discussion on @yifan-gu 's question: **whether or not to move runtime integration off from cadvisor**?

 I'm +1 for pushing it to CRI because it is hard to add new runtimes to cadvisor.

**Comment by yifan-gu** [comment]
> I'm +1 for pushing it to CRI because it is hard to add new runtimes to cadvisor.

Echo on this, at least even if we decide to use cadvisor, I'd like to see cadvisor publish a runtime interface to cover all the integration points.

**Comment by yujuhong** [comment]
@Random-Liu is there anything left to be done for this issue?

**Comment by Random-Liu** [comment]
@yujuhong Nope. We need to get image stats directly from runtime, but that's not for v1.5.

**Comment by Random-Liu** [comment]
@yujuhong Should we change this to `next-release`?

**Comment by Random-Liu** [comment]
Should we get back to this in 1.7? This is required for alternative runtime integration.

/cc @yujuhong @dchen1107 @vishh  @kubernetes/sig-node-feature-requests

**Comment by feiskyer** [comment]
Filed a PR #41733 to add a `ImageFsInfo` API in CRI (still working in progress). It returns same data as cadvisor.

**Comment by yujuhong** [comment]
Through recent discussions, I think we are converging to let runtime report the image filesystem stats, since kubelet will be isolated from implementation detail of the storage drivers.

Today cadvisor gathers such stats for kubelet, and the stats is used by kubelet's summary stats API, the image garbage collector, and the eviction manager.
In general, we need the ImageService to report
 1. Capacity, used, and available bytes.
 2. Capacity, used, and available inodes.
 3. Some form of storage identifier. Kubelet need to figure out whether there is a dedicated image FS for the eviction logic. 

For (2), I think the term inode may be too Linux-specific, but we use the term everywhere in kubelet (summary api too).
For (3), I think we can add the `device` and the `mountpoint` fields, as cadvsor does today.

Thoughts and objections?

**Comment by feiskyer** [comment]
> In general, we need the ImageService to report
> 
> 1. Capacity, used, and available bytes.
> 2. Capacity, used, and available inodes.
> 3. Some form of storage identifier. Kubelet need to figure out whether there is a dedicated image FS for the eviction logic.

LGTM. Actually,  #41733 is trying to add exactly same data format as cadvisor. If there are no objections, I will continue to finish PR #41733.

**Comment by Random-Liu** [comment]
@yujuhong LGTM.

**Comment by yujuhong** [comment]
> LGTM. Actually, #41733 is trying to add exactly same data format as cadvisor. If there are no objections, I will continue to finish PR #41733.

I don't think we need labels, and I'd prefer renaming many of the fields. Will comment later on the PR.

**Comment by yujuhong** [comment]
The API is done, but the implementation is not yet completed. Moving this to 1.8.
