### ISSUE TITLE
kubelet: eviction: need timestamp on fs stats for eviction

### ISSUE THREAD

**Issue by sjenning** [kubernetes/kubernetes#33049]
Right now there is a timestamp on the MemoryStats but not the FsStats.

In eviction we are using the timestamp to detect stats (or "observations" in eviction-speak) that have already been acted upon and just haven't been updated by cadvisor yet.

We need a timestamp on the FsStats as well so we can do the same stale-stat detection that we are doing for memory.  xref https://github.com/kubernetes/kubernetes/pull/32724

@derekwaynecarr @vishh

**Comment by derekwaynecarr** [comment]
@sjenning -- are you interested in plumbing this?

**Comment by sjenning** [comment]
@derekwaynecarr i actually started looking at it last night.  Didn't seem too bad.  Only gotcha I can think of is the caching of DM stats that are kinda hidden from the housekeeping tick routine.

**Comment by vishh** [comment]
+1 for adding timestamp to FsStats.

**Comment by sjenning** [comment]
This was fixed in https://github.com/kubernetes/kubernetes/pull/42435
