### ISSUE TITLE
kube-dns's graceful termination is not acting as expected.

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#33050]
After PR #31894, I did a bit experiments on kube-dns graceful termination and got some unintended result as below:
```
# scenario: scale down kube-dns from 4 to 1 with graceful termination (250ms period lookup with udp) 
2016/09/16 18:31:58 Resolution took 1.383041ms
2016/09/16 18:31:58 Resolution took 3.750672ms
2016/09/16 18:31:58 err: read udp 10.244.2.6:53645->10.0.0.10:53: read: connection refused
2016/09/16 18:31:59 Resolution took 927.836µs
2016/09/16 18:31:59 Resolution took 2.034077ms
2016/09/16 18:31:59 Resolution took 2.549052ms

# scenario: scale down kube-dns from 4 to 1 with graceful termination (250ms period lookup with tcp)
2016/09/19 18:28:59 Resolution took 672.151µs
2016/09/19 18:28:59 Resolution took 806.637µs
2016/09/19 18:28:59 Resolution took 585.271µs
2016/09/19 18:28:59 err: read tcp 10.244.0.12:37854->10.0.0.10:53: read: connection reset by peer
2016/09/19 18:29:00 Resolution took 639.391µs
2016/09/19 18:29:00 Resolution took 603.815µs
2016/09/19 18:29:00 Resolution took 576.174µs
```

I guess it is because the other container `dnsmasq` was terminated before `kubedns`. DNS query from clients failed because `dnsmasq` is the actual connection point.

After a bit discussion with @girishkalele and @freehan, two solutions for this are:
1. Create another program wrap up the dnsmasq and capture the SIGTERM signal.
2. Figure out a way to modify the sig mask of process without touching the original codes.

@thockin

**Comment by thockin** [comment]
Something I have been meaning to try:

Put `STOPSIGNAL SIGCONT` in Dockerfile
Build and push image

We should deliver SIGCONT rather than SIGTERM.  I did a quick test and it
seems to work.  Otherwise trapping SIGTERM in the shell and ignoring it is
well documented...

**Comment by MrHohn** [comment]
Thanks, I will take a look and test these.
