### ISSUE TITLE
Viper docs to e2e

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#33062]
_Problem_
- Viper configuration is lovely but the e2e --help really only encourages users to be more deeply dependent on flags, since it doesnt describe non-flag config via viper.
- Viper config is hardcoded to `e2e`.  

_Solution_

Add a `--viper` config parameter.  This solves two problems.  (1) people can have different viper configs for different use cases `e2e-scale.json` `e2e-networking.json` `e2e-conformance-smoke.json` and so on.  (2) The help will automatically print a description of viper when users read it.

**Comment by jayunit100** [comment]
This is also covered in #32902 above .

**Comment by kargakis** [comment]
@jayunit100 stil an issue?
