### ISSUE TITLE
Image GC tries to remove non-k8s docker container

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#33084]
When we are running a non-k8s docker image, image GC does not understand that the image is in use, and repeatedly tries to delete the image every 5 minutes.  We should understand that the image is in use and not try to delete it.  (edited for correctness)

``````
daemon.log:Sep 20 12:54:55 ip-172-20-32-29 kubelet[725]: E0920 12:54:55.094797     725 kubelet.go:933] Image garbage collection failed: Error response from daemon: conflict: unable to delete 8078e9a95c44 (cannot be forced) - image is being used by running container 1223d63c4e50```

```$ sudo docker images | grep 8078e9a95c44
kope/protokube                                      1.3                    8078e9a95c44        9 weeks ago         159.6 MB```

```$ sudo docker ps -a | grep 1223d63c4e50
1223d63c4e50        kope/protokube:1.3                                    "/usr/bin/protokube -"   6 days ago          Up 6 days                               backstabbing_panini```
``````

**Comment by justinsb** [comment]
cc @zapman449

**Comment by zapman449** [comment]
Thanks @justinsb 

For the record, "several times a second" was overstating.  Looks like it's spamming the logs once every 5 minutes.

However, instead of a backoff policy, image GC should see that it failed to delete an image, and then move on to the next image, rather than aborting the GC all together.

Relevant logs:

```
$ grep "Sep 20 11:" /var/log/daemon.log | grep "Image garbage collection failed"
Sep 20 11:04:44 ip-172-20-32-29 kubelet[725]: E0920 11:04:44.562224     725 kubelet.go:933] Image garbage collection failed: Error response from daemon: conflict: unable to delete 8078e9a95c44 (cannot be forced) - image is being used by running container 1223d63c4e50
Sep 20 11:09:44 ip-172-20-32-29 kubelet[725]: E0920 11:09:44.568306     725 kubelet.go:933] Image garbage collection failed: Error response from daemon: conflict: unable to delete 8078e9a95c44 (cannot be forced) - image is being used by running container 1223d63c4e50
Sep 20 11:14:45 ip-172-20-32-29 kubelet[725]: E0920 11:14:45.599026     725 kubelet.go:933] Image garbage collection failed: Error response from daemon: conflict: unable to delete 8078e9a95c44 (cannot be forced) - image is being used by running container 1223d63c4e50
Sep 20 11:19:45 ip-172-20-32-29 kubelet[725]: E0920 11:19:45.605265     725 kubelet.go:933] Image garbage collection failed: Error response from daemon: conflict: unable to delete 8078e9a95c44 (cannot be forced) - image is being used by running container 1223d63c4e50
Sep 20 11:24:46 ip-172-20-32-29 kubelet[725]: E0920 11:24:46.664232     725 kubelet.go:933] Image garbage collection failed: Error response from daemon: conflict: unable to delete 8078e9a95c44 (cannot be forced) - image is being used by running container 1223d63c4e50
Sep 20 11:29:46 ip-172-20-32-29 kubelet[725]: E0920 11:29:46.670061     725 kubelet.go:933] Image garbage collection failed: Error response from daemon: conflict: unable to delete 8078e9a95c44 (cannot be forced) - image is being used by running container 1223d63c4e50
Sep 20 11:34:47 ip-172-20-32-29 kubelet[725]: E0920 11:34:47.253105     725 kubelet.go:933] Image garbage collection failed: Error response from daemon: conflict: unable to delete 8078e9a95c44 (cannot be forced) - image is being used by running container 1223d63c4e50
Sep 20 11:39:47 ip-172-20-32-29 kubelet[725]: E0920 11:39:47.259478     725 kubelet.go:933] Image garbage collection failed: Error response from daemon: conflict: unable to delete 8078e9a95c44 (cannot be forced) - image is being used by running container 1223d63c4e50
Sep 20 11:44:48 ip-172-20-32-29 kubelet[725]: E0920 11:44:48.292046     725 kubelet.go:933] Image garbage collection failed: Error response from daemon: conflict: unable to delete 8078e9a95c44 (cannot be forced) - image is being used by running container 1223d63c4e50
Sep 20 11:49:48 ip-172-20-32-29 kubelet[725]: E0920 11:49:48.298363     725 kubelet.go:933] Image garbage collection failed: Error response from daemon: conflict: unable to delete 8078e9a95c44 (cannot be forced) - image is being used by running container 1223d63c4e50
Sep 20 11:54:49 ip-172-20-32-29 kubelet[725]: E0920 11:54:49.344348     725 kubelet.go:933] Image garbage collection failed: Error response from daemon: conflict: unable to delete 8078e9a95c44 (cannot be forced) - image is being used by running container 1223d63c4e50
Sep 20 11:59:49 ip-172-20-32-29 kubelet[725]: E0920 11:59:49.350972     725 kubelet.go:933] Image garbage collection failed: Error response from daemon: conflict: unable to delete 8078e9a95c44 (cannot be forced) - image is being used by running container 1223d63c4e50
```

**Comment by justinsb** [comment]
I edited the "headline" problem report here.

AFAICT the issue here is that k8s does not detect that the image is in use when the container is not a k8s-started docker container; it will try to delete it, and this will fail because the image is in use.

**Comment by yujuhong** [comment]
@justinsb @zapman449 what version of kubelet is this? I just checked the image GC code and it should continue removing images even if some of the deletion requests failed.

**Comment by DreadPirateShawn** [comment]
This is also a problem b/c it spams the logs with error-level entries, when "existence of non-k8s docker container on the host" is definitely not a Kubernetes error.

We are currently seeing this on:
```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
```

(I know it's not the most recent Kubernetes version, but our stack upgrade attempt was blocked by docker/docker#27607, and we needed to perform a full rollback. We considered trying to upgrade each separately, but at that point it made more sense to wait for Docker 1.13 to finalize, and then revisit.)

**Comment by itajaja** [comment]
I am hitting this exact problem, running 1.4. has this been fixed? If I look at the [docs](https://kubernetes.io/docs/admin/garbage-collection/):

> Containers that are not managed by kubelet are not subject to container garbage collection.

seems like this should not be happening

**Comment by william-tran** [comment]
This might explain issues I'm seeing using the [Concourse helm chart](https://github.com/kubernetes/charts/tree/master/stable/concourse) with `persistence.enabled: false`, which uses an `emptyDir` volume for workers. Workers create docker containers for every aspect of pipeline triggering and execution, and they seem to interfere with ImageGC because the disk eventually runs out of space after a few restarts of the worker process. When I use PVs, I don't see this behaviour.

**Comment by mark9white** [comment]
FYI: Still seeing this in Kubernetes 1.9

**Comment by Pingan2017** [comment]
still seeing in v1.11.0-alpha.
I think since k8s list all images and delete the unused images no matter the image is pulled by docker directly or through kubelet, k8s also should determine if the image is used by all running containers in the node , or at least not spam events for this.. 
. Now, kubelet just  judge used by the running containers that k8s managed.
 	// Make a set of images in use by containers.
	for _, pod := range pods {
		for _, container := range pod.Containers {
			glog.V(5).Infof("Pod %s/%s, container %s uses image %s(%s)", pod.Namespace, pod.Name, container.Name, container.Image, container.ImageID)
			imagesInUse.Insert(container.ImageID)
		}
	}
@yujuhong @dchen1107  @derekwaynecarr
