### ISSUE TITLE
API groups (certificates, rbac) missing from hack/update-codegen.sh, generated clientsets

### ISSUE THREAD

**Issue by wongma7** [kubernetes/kubernetes#33096]
Opening as follow-up to https://github.com/kubernetes/kubernetes/pull/33040#issuecomment-248147211

In that PR I added the storage api group to the 1.5 clientset (hoping to get it back in 1.4 as well.) because I want it to end up in client-go. Other groups appear to be missing (certificates, rbac). Might be due to missing documentation about the new versioned client stuff.

@kubernetes/sig-api-machinery (right sig?)

**Comment by caesarxuchao** [comment]
@kubernetes/sig-api-machinery

**Comment by wongma7** [comment]
I think this has been resolved with https://github.com/kubernetes/kubernetes/pull/33182

I am still going to work on getting the missing groups back into client-go 1.4 today, not sure if that is still desired with the versioning situation in client-go.

**Comment by caesarxuchao** [comment]
It's still desired. Adding groups is a backward compatible change. Thanks!
