### ISSUE TITLE
Pod QOS calculation is confused by opaque resources

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#33108]
**Scenario:**

A pod that makes a request for a GPU, but makes no cpu or memory request.

**Expected result:**

Pod has BestEffort QOS

**Actual result:**

Pod has Burstable QOS

**Details:**

The QOS classification should align with resources that are cgroup managed on the node.  We should ignore opaque resources that are not node enforced.

See: https://github.com/kubernetes/kubernetes/issues/32468#issuecomment-246875226

FYI: @vishh @ConnorDoyle @sjenning @kubernetes/sig-scheduling @kubernetes/sig-node

**Comment by vishh** [comment]
+1. Binary or Counted resources can be ignored for QoS purposes. I don't think QoS should be restricted to cgroups. Disk for example will be outside of cgroups, but still be part of QoS in the future.

**Comment by ConnorDoyle** [comment]
+1, and can help to review the PR

**Comment by vishh** [comment]
I'm working on a patch.

**Comment by derekwaynecarr** [comment]
@vishh -- fair point on disk, but i ignored that part of the discussion for now ;-)
