### ISSUE TITLE
Restart test needs to restart nodes in a different way.

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#33113]
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/restart.go

This test wants to restart all nodes and make sure that kubernetes survives the process. That's a neat test, but it does the actual restart in a poor way. It does a MIG rolling-update to its own image. If a rolling-update already exists in some sort of error state then all future rolling-updates in that project on an instance group with the same name will fail until someone manually cancels the borked update.

We can restart in other less-confusing ways. I suggest one of `gcloud compute instances reset` or `gcloud compute instance-groups managed recreate-instances`. Both seem reasonable to me.

cc @vishh @maisem @marekbiskup

**Comment by yujuhong** [comment]
ref: #10826

**Comment by davidopp** [comment]
ref/ #32466
