### ISSUE TITLE
reconfDocker.sh appends a copy of DOCKER_OPTS each time Kubernetes cluster is restarted

### ISSUE THREAD

**Issue by pvnguyen** [kubernetes/kubernetes#33124]
**Kubernetes version** (use `kubectl version`): 1.3.7

**Environment**:
- **Cloud provider or hardware configuration**: Bare-metal Ubuntu cluster
- **OS** (e.g. from /etc/os-release): Ubuntu 14.04.3 LTS
- **Kernel** (e.g. `uname -a`): 3.19.0-47-generic
- **Install tools**: KUBERNETES_PROVIDER=ubuntu ./kube-up.sh
- **Others**: Docker version 1.12.1

**What happened**:

`cluster/ubuntu/reconfDocker.sh` appends the same copy of `DOCKER_OPTS` each time we start and stop Kubernetes cluster (using Ubuntu's `kube-up.sh` & `kube-down.sh`).

For example, if we start Kubernetes cluster the first time and restart it again, the content of `/etc/default/docker` is doubled:
```
DOCKER_OPTS="-H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock \
       --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU} -H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock \
       --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU}"
```

This cause the following error when starting Kubernetes as seen in `/var/log/upstart/docker.log`:
```
time="2016-09-20T03:04:25.376664182-05:00" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2016-09-20T03:04:25.377033014-05:00" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2016-09-20T03:04:25.377119687-05:00" level=fatal msg="listen tcp 127.0.0.1:4243: bind: address already in use" 
```
**What you expected to happen**:

`DOCKER_OPTS` content should not be concatenated every time Kubernetes is restarted.

**How to reproduce it** (as minimally and precisely as possible):

Start Kubernetes, stop it, and start it again, using `kube-up.sh` and `kube-down.sh`.
**Anything else do we need to know**:

One possible fix is to remove the `${DOCKER_OPTS}` in the following line in `reconfDocker.sh`:

```
echo DOCKER_OPTS=\"${DOCKER_OPTS} -H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock \
       --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU}\" > /etc/default/docker
```

**Comment by DjangoPeng** [comment]
This is a bug and easy to fix. I'll open a PR to fix it @pvnguyen

**Comment by DjangoPeng** [comment]
@mikedanese Bug has been fixed.
