### ISSUE TITLE
Write e2e test for kubectl in a Pod

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#33138]
See: #33019

Using kubectl in a Pod with the default credentials broken in 1.4 and we weren't aware of it until someone found it in a beta build.  We were just lucky it didn't get out.  Need to write an e2e test that runs kubectl in a pod mounting it from the host using a hostvolume, and makes sure it can talk to the api server.

**Comment by smarterclayton** [comment]
Also need to do the same for proxy (uses a different config path) and at least one other "pod" component.

**Comment by ymqytw** [comment]
>uses a different config path

Can you please be more specific?

**Comment by smarterclayton** [comment]
Proxy doesn't initialize its configuration the same way as kubectl, even though it shares the core code.  Both support in cluster config differently and so both deserve a test.

**Comment by ymqytw** [comment]
@smarterclayton Can you create another issue for adding a test case for proxy, since kubectl and proxy are maintained by different team. Thanks.

**Comment by smarterclayton** [comment]
The team that owns clientcmd has to support both users - the tests are testing core code owned by kubectl, not owned by two different teams.

**Comment by smarterclayton** [comment]
The team that owns both needs to understand how their code is used and be responsible for its use.

**Comment by ymqytw** [comment]
Does `proxy` refer 'kube-proxy' or 'kubectl proxy'?

**Comment by smarterclayton** [comment]
kube-proxy is a consumer of the client configuration libraries and we broke
it unintentionally.  The point of these e2e tests is to validate all
consumers of the client configuration libraries start correctly using code
we provide.

**Comment by lavalamp** [comment]
The main problem here is just that we don't rebuild all our containers from the branch we're trying to test. We don't need a special test for this, we just need to use fresh containers in our tests instead of static ones.
