### ISSUE TITLE
Dialing different nodes breaks TLS-verified master<->kubelet connections

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#33140]
When the master dials nodes, it is mutating the tlsConfig held by the master kubelet client, to add a server name.

That means if two different nodes are dialed from a master started with `--kubelet-certificate-authority`, x509 verification will fail for the second one.

Introduced in https://github.com/kubernetes/kubernetes/commit/7e9d82129e58196b2d3f0b22e6b139c1c6b04dd1#diff-e00658bdc0ba8e28b32f709e4e41558eR72

**Comment by liggitt** [comment]
this is a regression from 1.3.0 and breaks pod logs/exec/attach and node proxying on installations that use `--kubelet-certificate-authority`

**Comment by smarterclayton** [comment]
We probably need to review that PR and look to see if any other deliberate copies were flagged incorrectly by govet.

**Comment by smarterclayton** [comment]
Installations that depend on secure trust from externally provided kubelet server certs are the highest security rings.  If we don't fix this we need to tell anyone using this flag not to upgrade until we release 1.4.1.

@pwittrock

**Comment by liggitt** [comment]
the rest of the changes in the govet cleanup PR looked fine to me. fix for this issue is in https://github.com/kubernetes/kubernetes/issues/33141

**Comment by pwittrock** [comment]
@smarterclayton Since we are telling folks they have to upgrade to kubectl 1.4.0 for rollingupdate to work it would definitely be a confusing message to say other folks should not upgrade to 1.4.0 at all.

**Comment by pwittrock** [comment]
If the fix is merged into master by this afternoon, lets discuss whether or not we should cherrypick it - e.g. risks involved, how we can manually qa to verify nothing else was broken, etc.

**Comment by smarterclayton** [comment]
Risk involved:

* If you are using a secure cluster (defined as ensuring no one can MITM your nodes and masters) and you upgrade to 1.4.0 and it does not include this fix - you are broken.

**Comment by pwittrock** [comment]
What is the likelihood of interactions with other code?  Is it possible this fix could introduce a breaking change to something else?  Has the fix been manually verified?  Are we confident that this will fully fixes the issue (vs other edge cases exist for secure clusters that this doesn't catch).

Ideally I would like to see this cherrypicked into 1.4 this evening and then cut a new beta that includes it.

**Comment by liggitt** [comment]
> What is the likelihood of interactions with other code?

None. The single line that is currently broken was changed. The rest is a new function with no side effects and tests. 

> Is it possible this fix could introduce a breaking change to something else?

No, it restores the original intent of the TLS config copy

> Has the fix been manually verified?

Yes. 

> Are we confident that this will fully fixes the issue (vs other edge cases exist for secure clusters that this doesn't catch).

I swept for the same issue elsewhere and didn't find any issues. We test with a fully secured master-kubelet setup in Openshift and got a clean test run with this fix applied.

**Comment by pwittrock** [comment]
SGTM.  Thanks for fixing this.
