### ISSUE TITLE
Potential races in Federation Ingress controller unit tests.

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#33153]
Potential race in Federation Ingress controller unit tests. See https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/33039/kubernetes-pull-test-unit-integration/45749/ for details.

cc @kubernetes/sig-cluster-federation @mwielgus

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/issues/32685
