### ISSUE TITLE
Kubemark GCE: disk already exists

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#33152]
I'm seeing the following failure during the Kubemark GCE tests:

```
Starting master and configuring firewalls
ERROR: (gcloud.compute.disks.create) Some requests did not succeed:
 - The resource 'projects/k8s-jkns-pr-kubemark/zones/us-central1-f/disks/k6k-e2e-agent-pr-30-0-master-pd' already exists
```

Found on https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/33063/kubernetes-pull-build-test-kubemark-e2e-gce/859/

**Comment by wojtek-t** [comment]
Yeah - there were some issues back then. This should be fixed now. Please reopen/open new issue if you see that again.
