### ISSUE TITLE
JSON format can't parse secret permission mode start with 0

### ISSUE THREAD

**Issue by qwang1** [kubernetes/kubernetes#33162]
**What keywords did you search in Kubernetes issues before filing this one?** : secret permission mode json

BUG REPORT

**Kubernetes version** (use `kubectl version`):
v1.5.0-alpha.0.368+5512104d363813

**Environment**:
- **OS** (e.g. from /etc/os-release): Fedora 24
- **Kernel** (e.g. `uname -a`): 4.5.5-300.fc24.x86_64 

**What happened**:
I followed the document https://github.com/kubernetes/kubernetes.github.io/pull/1178 to create a pod with specifying secret permission mode, spec.volumes[0].secret.defaultMode restricts valid number between 0 and 0777 (octal), but JSON format can't parse int32 with a 0 at the beginning. If I changed 0400 to string "defaultMode": "0400".

**How to reproduce it** (as minimally and precisely as possible):
```
1. Create a secret 
# cat secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  data-1: dmFsdWUtMQ0K
  data-2: dmFsdWUtMg0KDQo=

# kubectl create -f secret.yaml

2. Specify the permission mode bits files part of a secret
# cat secret-permission-pod.json
{
 "apiVersion": "v1",
 "kind": "Pod",
  "metadata": {
    "name": "secret-permission-pod"
  },
  "spec": {
    "containers": [{
      "name": "secret-permission-pod",
      "image": "redis",
      "volumeMounts": [{
        "name": "foo",
        "mountPath": "/etc/foo"
      }]
    }],
    "volumes": [{
      "name": "foo",
      "secret": {
        "secretName": "test-secret",
        "defaultMode": 0400
      }
    }]
  }
}

# kubectl create -f secret-permission-pod.json
json: line 19: invalid character '4' after object key:value pair

3.  Change int 0400 to string "0400"
# kubectl create -f secret-permission-pod.json
error validating "secret-permission-pod.json": error validating data: expected type int, for field spec.volumes[0].secret.defaultMode, got string; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by rata** [comment]
@qwang1 will investigate later (I'm at work right now). But does it work if you use numbers in base 10, like 256 instead of 0400? For sure it worked in yaml, so it might be something about JSON.

@qwang1 if you can confirm it works with yaml using 0400 will be nice, too :-)

**Comment by rata** [comment]
@qwang1 it's not valid to specify numbers in octal format in JSON (http://www.json.org in the numbers section already tells it). If you use the decimal number, like 256 for 0400), it will probably work.

If that is the case, it is okay to just clarify in the documentation that octal and hex numbers are not valid when using json as the json format specification does not support it?

**Comment by rata** [comment]
Well, I opened a PR to fix the example. @qwang1 can you confirm this fixes the issue for you?

If someone thinks it's better to use YAML (in the other examples of secret JSON is being used) to have more natural notation on file mode, please let me know

**Comment by mdshuai** [comment]
@rata The fix look good for us. thanks.

**Comment by rata** [comment]
@mdshuai thank you both for the report! :-)

Can this be marked as fixed, then? :)

**Comment by mdshuai** [comment]
@rata yes. For json will use decimal number. thanks for your fix. we can close this issue.

**Comment by derekwaynecarr** [comment]
Closing issue per comment
