### ISSUE TITLE
Split-horizon DNS by namespace

### ISSUE THREAD

**Issue by jonathan-kosgei** [kubernetes/kubernetes#33173]
Is it possible to prevent containers in a pod in a particular namespace from resolving services outside the pods namespace? This should be possible but after fruitless googling I can't find any documentation on this.

Eg.

PHP pod in Bob namespace can resolve mysql at `mysql.bob:3306` but can't resolve mysql in Alice's namespace at `mysql.alice.svc.cluster.local`

**Comment by zhouhaibing089** [comment]
why do you want such isolation?

**Comment by jonathan-kosgei** [comment]
@zhouhaibing089 to prevent a user app in one namespace from accessing database servers in another namespace via the full dns name eg. prevent user 1 from accessing user 2's mysql at mysql-1.user-2.cluster.local

**Comment by jonathan-kosgei** [comment]
I could swear I read about this in the docs sometime earlier in the year but I can't find any info on the topic now

**Comment by zhouhaibing089** [comment]
@jonathan-kosgei does `NetworkPolicy` help here? https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/types.go#L839

NetworkPolicy is a concept to restrict the source ip(peer which is namespaced) from accessing another set of pod ports.

**Comment by sandys** [comment]
this is important for us as well. we will be trying to set up different clusters (staging, production, testing, etc) and we want each cluster to act as if the other doesnt exist.

it is not good if one cluster leaks to the other .. whether DNS or otherwise.

**Comment by zhouhaibing089** [comment]
@sandys IIUC, different clusters will have different dns, so they won't leak to each other?

**Comment by sandys** [comment]
@zhouhaibing089 but if a request from another cluster reaches this cluster. will it refuse to resolve (ideally) or will it attempt to resolve. 

let's say my cluster has a service named "cat" and so do you ... what happens if i send u a dns request erroneously due to a misconfiguration/maliciousness

**Comment by zhouhaibing089** [comment]
I do not know the detail of your deployment model, but in my case, it is:

Each cluster will have a kubedns deployed in `kube-system`, and it will have a cluster ip: `192.168.0.10`, it is a private ip inside cluster, and when we configured like so, the kubelet will inject all the pod an entry which tells that `192.168.0.10` is the name server.

If like you said, then it could be that you also create an ingress for kubedns, so it is a names server publicly?

**Comment by zhouhaibing089** [comment]
If you have more than one k8s cluster, then most probably, you will need to have different domain for each cluster, for example, `staging.k8s.io`(for staging), `testing.k8s.io`(for testing), `k8s.io`(for production), etc..

**Comment by jonathan-kosgei** [comment]
Maybe to clarify on @sss . The issue is dns leaking between namespaces in
the SAME cluster.

**Comment by matchstick** [comment]
@bowei @kubernetes/sig-network PTAL?

**Comment by eparis** [comment]
NetworkPolicy (with a network plugin that supports it) should cover the access control part. So that only leaves "information leak", right? Do we allow zone transfers? If not, its a pretty weak information leak. You have to already know the name in that other namespace to look it up.

The only solution to have split DNS is going to have to be network policy based. As cross namespace services are quite normal...

**Comment by bowei** [comment]
@sandys, @jonathan-kosgei  -- trying to understand the problem

Echoing @eparis -- to resolve a name in a different namespace you have to give both the service name and the external namespace explicitly in the lookup. E.g. for service "foo" and external namespace "external-ns", resolving a DNS name would look like this:
````
$ dig foo.external-ns.svc.cluster.local
      /         \
  (name)     (namespace)
````
Presumably, once the name is resolved, any attempts to contact the endpoints would be rejected via NetworkPolicy.

The information that can be leaked is as far as I can tell:

- IPs of services (A records)
- List of endpoints for a service (SRV records)
- Federation records (service record or external inter-cluster record)

Is the concern that these records could leak across namespaces, given that the pod knows the service name and the name of the other namespace?

As an aside, unless you use some kind of NetworkPolicy/network isolation, you cannot assume that the inability to resolve a name is equivalent to not being able to contact a host. For example, most deployments live in the 10.x.x.x private subnet and a pod could network scan across all the 2^24 IPs quite easily.

**Comment by aanm** [comment]
You can use the Network Policy to prevent pods from one particular namespace to talk with a different namespace. Why is so problematic they resolve some DNS entry if they can't access that particular service?

**Comment by thockin** [comment]
It is still an info leak.  And a DoS vector.  To be clear, I *do* want to
solve this, it's just less urgent than 100 other things right now :)
