### ISSUE TITLE
flake in etcd.TestWatch

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#33184]
Flake in podsecuritypolicy/etcd.TestWatch, may be related to other changes in watch recently.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/33007/kubernetes-pull-test-unit-integration/45733/

```
k8s.io/kubernetes/pkg/registry/podsecuritypolicy/etcd TestWatch 33s
go test -v k8s.io/kubernetes/pkg/registry/podsecuritypolicy/etcd -run TestWatch$
resttest.go:1251: unexpected timeout from result channelfrom junit_05d5a39770f1e642b026f49319438a74d93cb6bb_20160920-101131.xml
```

**Comment by smarterclayton** [comment]
@timothysc i saw you say you found problems in watch recently, not sure if this is related

**Comment by timothysc** [comment]
Is this from latest master this morning?

**Comment by dchen1107** [comment]
Shouldn't this pr https://github.com/kubernetes/kubernetes/pull/33101 fix the issue?

**Comment by timothysc** [comment]
looks like rebase on https://github.com/kubernetes/kubernetes/pull/33007 was 2 days ago.  closing this one, reopen if it occurs again.
