### ISSUE TITLE
kubectl: wait for a specific deployment revision

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#33185]
We have requests for providing the ability to wait for specific deployment revisions. Currently, the way to wait for the outcome of a deployment is to use `kubectl rollout status` but this will work only for the latest revision of the deployment. For example, a script runs a new rollout and needs to wait for that specific revision to finish in order to continue. If another rollout of the same deployment kicks off in the meantime, now `rollout status` waits for the new rollout to finish.

I am proposing a `--revision` flag on `rollout status` that will pin to a specific revision and once that is superseded, `rollout status` exits watching. Also, once we pin perm-failed (https://github.com/kubernetes/kubernetes/pull/19343) down, we will need to reconsider the behavior of the command. We probably want it to exit as soon as lack of progress is reported and we also want to have appropriate exit codes.

@kubernetes/deployment @kubernetes/kubectl thoughts?

**Comment by soltysh** [comment]
Instead of spreading wait-related code in specific commands, I'd rather focus on #1899 and fix it here, wdyt?

**Comment by kargakis** [comment]
@soltysh `rollout status` already waits, this issue is about pinning to a revision ie. has nothing to do with wait per se.

**Comment by AdoHe** [comment]
@kargakis could you please explain how we handle multiple deployment revision now? I am not very clear about this.

**Comment by kargakis** [comment]
In `rollout status`? We don't handle revisions at all, we just wait on the deployment status ie. the latest revision.
I am envisioning scripts passing a specific revision and once that revision is superseded prior to completing, then we abort waiting with a useful message "desired revision was superseded" or something. We also want to return appropriate exit codes: if the revision I am watching never completes deploying then we should return an error, otherwise ok.
