### ISSUE TITLE
Document scheduler jargon documentation (from design/podaffinity.md) to (docs/devel/scheduler*)

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#33188]
_Problem_

There is alot of jargon in the scheduler code, some examples:
- `hardPodAffinityWeight` == RequiredDuringSchedulingScheduling
- `softPod...` ==  "PreferredDuringScheduling pod affinity." 
- Symmetry, a major part of the affinity algorithm implementation, is also undocumented in docs/devel/scheduler.

Reading podaffinity along side the scheduler docs + the code gives a good picture.  

_Solution_

Since the affinity, symmetry, hard/soft pod stuff is now in the production code, lets migrate out of the proposal (or maybe duplicate if proposals are meant to live forever), and Lets converge podaffinity proposal into the first class docs/devel/scheduler\* area. 

cc @kubernetes/sig-scheduling

**Comment by timothysc** [comment]
@jayunit100 sgtm... I think it would be worthwhile to also create annotated examples as well. 

@davidopp thoughts?

**Comment by ingvagabund** [comment]
The ``interpod_affinity.py`` is not so long. So one could document the file independently of what is written in the docs and then combine.

**Comment by jayunit100** [comment]
interpod_affinity.py?

**Comment by ingvagabund** [comment]
> interpod_affinity.py?

too much python I guess, fixed :)

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @jayunit100

**Comment by timothysc** [comment]
@jayunit100 && @ConnorDoyle per 1.6 doc assigning to you.

**Comment by jayunit100** [comment]
digging back into this again.

**Comment by jayunit100** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes.github.io/issues/2276

**Comment by jayunit100** [comment]
I guess i should reopen, since technically this is a 1.6. issue.

**Comment by timothysc** [comment]
leaving this open till docs merge.

**Comment by ravisantoshgudimetla** [comment]
@timothysc , Is this something needed for 1.6 or planning to move to 1.7?

**Comment by timothysc** [comment]
This is ok to move it's not a blocker for 1.7.

**Comment by gyliu513** [comment]
@jayunit100 Does this still be a problem? We already have all of the documents related to scheduler in https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/concepts/configuration/assign-pod-node.md

**Comment by timothysc** [comment]
It still doesn't describe the tuning knobs and how they affect behavior.

**Comment by gyliu513** [comment]
@timothysc Do you mean add sth for trouble-shooting? How about adding more documents links as @jayunit100 proposed here https://github.com/jayunit100/kubernetes.github.io/blob/cbef566d3c18edb4a0599a45da921b76fc5ca4fc/docs/user-guide/node-selection/index.md#documentation-status
