### ISSUE TITLE
ExecAction htmlpreview docs are misformatted at HEAD

### ISSUE THREAD

**Issue by n-rook** [kubernetes/kubernetes#33193]
See:

https://htmlpreview.github.io/?https://github.com/kubernetes/kubernetes/blob/HEAD/docs/api-reference/v1/definitions.html#_v1_execaction

On Chrome, I'm seeing the following text under Description:

```
Command is the command line to execute inside the container, the working directory for the command is root (/) in the container’s filesystem. The command is simply exec’d, it is not run inside a shell, so traditional shell instructions ('
```

And the following under Required:

```
', etc) won’t work. To use a shell, you need to explicitly call out to that shell. Exit status of 0 is treated as live/healthy and non-zero is unhealthy.
```

It seems obvious something goofy is happening to an example shell command here.

**Comment by dims** [comment]
Swagger stuff having trouble with `so traditional shell instructions ('|', etc) won't work` from here i think https://github.com/kubernetes/kubernetes/blob/892a6d7af59c0ba2d59f912759d9e7b56a543bd4/pkg/api/types.go#L1006 The pipe probably throws it off

**Comment by n-rook** [comment]
This is still happening.

/remove-lifecycle stale

(I'm not sure if I'm supposed to make such flow-control statements as a humble user, but I guess we'll find out 😉)

**Comment by fejta** [comment]
Yes, you most certainly are. Thanks for helping!

**Comment by n-rook** [comment]
/remove-lifecycle stale

😬

**Comment by n-rook** [comment]
/remove-lifecycle rotten

I congratulate this bug on reaching its second birthday 🍾
