### ISSUE TITLE
Avoid kube-dns service IP being assigned to another service.

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes/kubernetes#33195]
**Is this a request for help?**
No

**What keywords did you search in Kubernetes issues before filing this one?**
kube-dns ip
kube-dns service ip
kube-dns ip race

---

**Is this a BUG REPORT or FEATURE REQUEST?**
FEATURE REQUEST

---

When creating cluster assets/addons all at once (e.g. `kubectl create -f asset-dir`) - it is possible that some services are dynamically assigned service IP's which may conflict with services expecting a static service IP assignment.

For example, the kube-dns service IP needs to be static so that it can be added to each kubelet's configuration - but it's possible that another service is randomly assigned that IP first.

As an option, I'm wondering about the possibility of adding a flag to the controller-manager that would assign a static range out of the `--service-cluster-ip-range`.

For example:

```
--service-cluster-ip-range=10.3.0.0/24
--service-cluster-ip-range-static=10.3.0.0/28
```

ref: https://github.com/kubernetes-incubator/bootkube/issues/136

**Comment by ravilr** [comment]
>adding a flag to the controller-manager that would assign a static range out of the --service-cluster-ip-range.

FYI, --service-cluster-ip-range allocation is wired by kube-apiserver, not the kube-controller-manager.  it was added as a flag option in kube-controller-manager just to avoid node controller allocate pod ips out of service ip range (https://github.com/kubernetes/kubernetes/issues/24547)

**Comment by tkellen** [comment]
I just stumbled upon this setting up my first cluster. Is there a known workaround?

**Comment by pires** [comment]
Is there even a validation for the CIDR size? Say I set something like `--service-cluster-ip-range-static=10.3.0.128/31`. There's no chance I'll have `kubernetes` as `10.3.0.1`. Are there any validations for this?
