### ISSUE TITLE
TestInterPodAffinityPriority: Test is incorrect, when fixed - reveals missing punishment for mismatched label selector?

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#33198]
### Problem

The interpod_affinity_test.go Tests attempt to confirm that, for a score of 10, you need 
- matching region AND 
- pods on nodes that match incoming labels

To test this, you need the following nodes, and expec the following scores.

(region match, labels match, expected score, actual score)

```
Y  Y  10  10
Y  N  <10 10 (this is the bug im seeing, revealed by patching the unit test)
N  Y  <10 0
```

Why isnt this caught by the test? Becuase, it appears that the second machine accidentally removes the china label, so you get 10,0,0 for scores.  
If you correct the unit test... 

```
-                               {ObjectMeta: api.ObjectMeta{Name: "machine2", Labels: labelRgIndia}},
+                               {ObjectMeta: api.ObjectMeta{Name: "machine2", Labels: labelRgChina}},
```

Then the test (correctly) fails, because two machines have high (10) scores.
### Solution

FIRST 
- Fix the test so that machine 1 and 2 both have China label (as done above) and 

SECOND
- modify the test to match the ensuing result (10,10,0) OR modify the affinity scheduler to give a score like (10,5,0) so that the machine some of the  pod labels have some value, but are still lower value than the machine which matches all values.

I suspect the latter is correct - we probably dont want region to dominate the matching calculation!
### Details

For efficiency of evaluating my logic here i've attached the full unit test that im trying to run.  

```
        // the node(machine1) that have the label {"region": "China"} (match the topology key) AND pods DO match the labelSelector -> 10 (high) score
        // the node(machine2) that have the label {"region": "China"} (match the topology key) BUT pods DONT match the labelSelector -> 0 score
        // the node(machine3) that DONT have the label {"region": "China"} BUT pods DONT match labelSelector -> 0 score.
        {
            pod: &api.Pod{Spec: api.PodSpec{NodeName: ""}, ObjectMeta: api.ObjectMeta{Labels: podLabelSecurityS1, Annotations: stayWithS1InRegion}},
            pods: []*api.Pod{
                {Spec: api.PodSpec{NodeName: "machine1"}, ObjectMeta: api.ObjectMeta{Labels: podLabelSecurityS1}},
                {Spec: api.PodSpec{NodeName: "machine2"}, ObjectMeta: api.ObjectMeta{Labels: podLabelSecurityS2}},
                {Spec: api.PodSpec{NodeName: "machine3"}, ObjectMeta: api.ObjectMeta{Labels: podLabelSecurityS1}},
            },
            nodes: []*api.Node{
                {ObjectMeta: api.ObjectMeta{Name: "machine1", Labels: labelRgChina}},
                {ObjectMeta: api.ObjectMeta{Name: "machine2", Labels: labelRgChina}},
                {ObjectMeta: api.ObjectMeta{Name: "machine3", Labels: labelAzAz1}},
            },
            expectedList: []schedulerapi.HostPriority{{Host: "machine1", Score: 10}, {Host: "machine2", Score: 0}, {Host: "machine3", Score: 0}},
            test: "Affinity: pod that matches topology & pods in nodes will get high score comparing to others" +
                "which doesn't match either pods in nodes or in topology key",
        },
```

**Comment by jayunit100** [comment]
(double checking my logic on this, just in case, after i confirm will cc sig-sched)

**Comment by jayunit100** [comment]
cc @kubernetes/sig-scheduling

**Comment by jayunit100** [comment]
@kevin-wangzefeng any thoughts on this?

**Comment by kevin-wangzefeng** [comment]
IMO, topologyKey mismatch should results the same with labelselector mismatch -- they are both "(anti-)affinity reqiurements" mismatch. That means (assume that each node belongs to different topology zone, and there is only one pod running in each topology zone), expectations should follow:

node| Pods | topologyKey match | labelselector match | Score
--- | --- | --- | --- | ---
nodeA | podA | Yes | Yes | 10
nodeB | podB | Yes | No  | 0
nodeC | podC | No  | Yes | 0
nodeD | podD | No  | No  | 0

**Comment by jayunit100** [comment]
Can we bump priority on this?  its a bug that really confounds the semantics of scheduling affinity
