### ISSUE TITLE
Kubelet volume manager fails to reconstruct volume information if global mount path is gone

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#33207]
## Problem:

If pod is deleted while kubelet is restarted, master might detach volume while it is not yet unmounted. In this situation, the following sequence might happen.
1.  Kubelet restarts, all information about mounted volumes are gone. Node updates its status indicating that no volume is mounted currently. (but the truth is that volume is still mounted)
2. Master deletes the pod, volume reconciler detaches the volume because it thinks the volume is not mounted anymore. 
3. On node, global mount path is gone because of detach. But the bind mount path for the volume is still there. Volume manager reconstruct process scans the directory but could not get the device path so fails to reconstruct the volume information. The kubelet cleanupOrphanedPodDirs will also fail to clean the pod directory because the bind mount still exists.
## Proposed solution:

Please refer to #33203. The root cause of this problem is master is trying to detach while volumes are still mounted. The global path is gone while bind mount still exist. If the proposed approach in #33203 can completely avoid this problem, this PR is not required to do anything. However, considering human intervention or other inferences, it is better to take extra step to avoid this situation.
If global device path could not be found, reconstruct can use fake information to put into the state. Based on the state, reconciler will use the available information to unmount bind mount. Unmount global mount path is not needed since it is no longer exist.

**Comment by rootfs** [comment]
@kubernetes/sig-storage

**Comment by saad-ali** [comment]
Like you mentioned this shouldn't happen if #33203 is done. But we should still handle this edge case and clean up correctly. But we can make this P2
