### ISSUE TITLE
kube-up.sh fails and misreports status using AWS (KUBE_MANIFESTS_TAR_URL: unbound variable)

### ISSUE THREAD

**Issue by jchambers** [kubernetes/kubernetes#33202]
This is, essentially, a deliberate duplicate of #30495, which was closed by the requester before the underlying issue was resolved. In short, current versions of Kubernetes (I'm using 1.3.7) fail when using `kube-up.sh` to create a cluster under AWS, but incorrectly report success. This leaves some AWS resources (VPCs, security groups, etc.) in place, but with no actual nodes.

The relevant bit of output is as follows:

```
./cluster/../cluster/../cluster/aws/../../cluster/common.sh: line 528: KUBE_MANIFESTS_TAR_URL: unbound variable
Kubernetes binaries at /Users/jon/kubernetes/cluster/
You may want to add this directory to your PATH in $HOME/.profile
Installation successful!
```

A viable workaround has been described in #30495 (I believe this is why the original author closed the issue), but the issue itself has not actually been fixed. Please accept my apologies for the goofy paperwork shenanigans here, but I did want to make sure the issue didn't get lost.

**Comment by JoeyZwicker** [comment]
+1 to @jchambers. Can we get this minor 3-line fix pushed to get.k8s.io ASAP so we can actually start directing users there and they'll be successful?

**Comment by ashishsoni** [comment]
+1 to get this fixed soon as this is a blocking issue

**Comment by justinsb** [comment]
I believe this is fixed now (I wasn't able to reproduce it) - please reopen if not

**Comment by jchambers** [comment]
I agree that this now appears to be fixed. Thanks!
