### ISSUE TITLE
Log rotate all /var/log log files in GCI

### ISSUE THREAD

**Issue by fabioy** [kubernetes/kubernetes#33223]
GCI log rotation configuration missed "glbc.log" file. We should just configure log rotation to rotate all "*.log" files in /var/log.

**Comment by pwittrock** [comment]
@fabioy I cherrypicked your change last night.  Please do what you need to do to confirm this is resolved.

**Comment by fabioy** [comment]
Thank you, will do.

**Comment by fabioy** [comment]
Verified. Closing issue.
