### ISSUE TITLE
Date header not accessible to CORS browser clients, missing Access-Control-Expose-Headers

### ISSUE THREAD

**Issue by jwforres** [kubernetes/kubernetes#33231]
v1.4.0-beta.3+d19513f

If a UI is hosted on a different domain than the API, and that UI hostname has been whitelisted as an allowed CORS origin, it should be able to access the Date header being returned by the API.

However, the CORS spec requires any headers that are not [simple](https://www.w3.org/TR/cors/#simple-response-header) must be included in a header called Access-Control-Expose-Headers or the javascript in the page will not be able to access the headers even if they are returned by the server.

This should just be a matter of adding `Access-Control-Expose-Headers` in the CORS handler
https://github.com/kubernetes/kubernetes/blob/a2c186dbd0bf14055b671713f0542cfc7a49208f/pkg/apiserver/handlers.go#L386

**Comment by jwforres** [comment]
cc @smarterclayton found this trying to fix the clock skew problem

**Comment by dims** [comment]
@jwforres i can take a stab at a quick change Access-Control-Expose-Headers (support section 6.1.4 of https://www.w3.org/TR/cors/#resource-requests). If i a file a WIP PR, will you be able to build it and test it? Please let me know

**Comment by jwforres** [comment]
I'm not aware of any other special headers being sent, Date should be enough for now

I'm not really set up to run just kubernetes right now, I could cherry-pick the change into openshift's vendor of kube 1.4 and try it there if you want?

**Comment by dims** [comment]
Sure @jwforres please try the PR and let me know.
