### ISSUE TITLE
hyperkube-amd64:v1.4.0-beta.9 is not tagged on GCR

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#33249]
```shell
$ curl  https://gcr.io/v2/google_containers/hyperkube-amd64/tags/list | jq

# note that there is no 'v1.4.0-beta.9' tagged
```

Is tagging/pushing `hyperkube-amd64` not an automated part of the release process? I had had a PR for this and abandoned it after there was an indication that it was now being built as part of the normal release.

It seems that it is still not being built as part of the tarball release, and instead is built after the release tarballs have already been created... Maybe that contributes to it not being automatically tagged and pushed to GCR?

**Comment by colemickens** [comment]
Previous discussion: https://github.com/kubernetes/kubernetes/pull/21928 and https://github.com/kubernetes/kubernetes/pull/20710

**Comment by colemickens** [comment]
(If it's desired to be included in the tarball, I could add this. Likewise if there's automation around pushing the various images in the repo.)

**Comment by luxas** [comment]
It is built for every release since `v1.2.x`-something.
I just think `beta.9` failed in some way. It doesn't have release notes either...

**Comment by colemickens** [comment]
Yeah, I meant to update this last night. The beta.9 release didn't finish properly. The raw binaries (for kubectl for example) are not uploaded either.

It looks like hyperkube is automatically built and released normally... though still not included in the actual release tarball.

I have a WIP branch that includes a change to include the hyperkube exported container in the tarball, similar to what is done for the other docker_wrapped binaries. If it's something we want to include in the release I can continue the change and send a PR...
