### ISSUE TITLE
Should have option to specify the external load balancer for  create loadbalancer service 

### ISSUE THREAD

**Issue by zhouying7780** [kubernetes/kubernetes#33254]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): create,service

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

https://bugzilla.redhat.com/show_bug.cgi?id=1378011
**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by zhouying7780** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1378011

**Comment by kargakis** [comment]
cc: @kubernetes/kubectl
