### ISSUE TITLE
Node is NotReady for hours, but finally return Ready

### ISSUE THREAD

**Issue by qinsc** [kubernetes/kubernetes#33257]
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-beta.8", GitCommit:"3040f87c570a772ce94349b379f41f329494a4f7", GitTreeState:"clean", BuildDate:"2016-09-18T21:06:37Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-beta.8", GitCommit:"3040f87c570a772ce94349b379f41f329494a4f7", GitTreeState:"clean", BuildDate:"2016-09-18T21:00:36Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **OS** (e.g. from /etc/os-release):
  
    NAME=CoreOS
    ID=coreos
    VERSION=1122.2.0
    VERSION_ID=1122.2.0
    BUILD_ID=2016-09-06-1449
    PRETTY_NAME="CoreOS 1122.2.0 (MoreOS)"
    ANSI_COLOR="1;32"
    HOME_URL="https://coreos.com/"
    BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
- **Kernel** (e.g. `uname -a`):
  
  Linux k8s-66 4.7.0-coreos #1 SMP Tue Sep 6 14:39:20 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz GenuineIntel GNU/Linux
- **Install tools**:
  
  coreos-cloudinit 
- **Others**:

**What happened**:

  After i used coreos-cloudinit to install kubernates mater and nodes, node is not ready for longtime. I excute "kubectl get nodes", it waw "NotReady". I used "journalctl -au kube-kubelet" to see logs on node, it kept reporting  such log:

```
  Sep 20 10:22:26 k8s-68 kubelet[771]: E0920 10:22:26.163682     771 eviction_manager.go:162] eviction manager: unexpected err: failed GetNode: node 'k8s-68' not found
```

  And service kube-controller-manager on master kept reporting this:

```
  Sep 19 16:01:37 k8s-66 kube-controller-manager[1028]: I0919 16:01:37.034802    1028 endpoints_controller.go:327] Waiting for pods controller to sync, requeuing service default/kubernetes
```

  After long time, about 5 - 7 hours, node status can return ready. Service kube-kubelet of node show these logs:

```
  Sep 20 17:31:16 k8s-68 kubelet[771]: I0920 17:31:16.462726     771 kubelet_node_status.go:103] Node k8s-68 was previously registered
  Sep 20 17:31:16 k8s-68 kubelet[771]: I0920 17:31:16.462804     771 kubelet_node_status.go:67] Successfully registered node k8s-68
```

  Kube-controller-manager on master show these logs:

```
  Sep 20 10:06:01 k8s-66 kube-controller-manager[1072]: W0920 10:06:01.639442    1072 nodecontroller.go:762] Missing timestamp for Node k8s-68. Assuming now as a timestamp.
  Sep 20 10:06:01 k8s-66 kube-controller-manager[1072]: I0920 10:06:01.639922    1072 event.go:217] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"k8s-68", UID:"c48b1c60-7ed6-11e6-8ab5-005056bee0aa", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node k8s-68 event: Registered Node k8s-68 in NodeController
  Sep 20 10:07:21 k8s-66 kube-controller-manager[1072]: I0920 10:07:21.693912    1072 event.go:217] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"k8s-68", UID:"c48b1c60-7ed6-11e6-8ab5-005056bee0aa", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeNotReady' Node k8s-68 status is now: NodeNotReady
```

  Is this normal ？

**Comment by gmarek** [comment]
Judging by the time it's really old release. As a lot of things changed since then I'm closing this issue.
