### ISSUE TITLE
Read-only pod status attribute to advertise computed QoS class.

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes/kubernetes#33255]
As described by @derekwaynecarr from comments in #32468:

> Developers that build web console experiences need to reproduce our QOS calculation logic. This makes them vulnerable to the same bugs we just fixed in #33108 for each experience they produce. I am supportive of a read-only attribute on PodStatus that states the QOS class of a Pod since once we have qos enforced on the node, we have said a pod cannot change its QOS in its life-time.

@jwforres @vishh @balajismaniam

**Comment by ConnorDoyle** [comment]
Around the same time `kubectl` could be updated to simply read the new attribute instead of re-computing the class (see https://github.com/kubernetes/kubernetes/blob/f9e1ef97dbe5fae5d8588881e6c36344c4ff7769/pkg/kubectl/describe.go#L550)

**Comment by vishh** [comment]
+1 for this change. We have a goal for shrinking all special logic in
kubectl anyways, so it makes sense for kubelet to explicitly include this
data in PodStatus. To start with, should we just include it as an
annotation? I assume we will have many other fields that needs to move from
kubectl special logic to the node. We can add all of them in one shot
possibly by grouping them in an annotation.

**Comment by derekwaynecarr** [comment]
I prefer a literal field on PodStatus since an annotation is user
modifiable and I am concerned callers may use the annotation as a trusted
piece of information.  If there is no major disagreement I can add a PR for
this as part of qos work in 1.5.   Maybe @sjennings could help too.

**Comment by derekwaynecarr** [comment]
Copied wrong Seth.  Meant @sjenning.

**Comment by derekwaynecarr** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/32468#issuecomment-249301475

**Comment by sjenning** [comment]
Any votes on what the name this status field should be?

**Comment by vishh** [comment]
I vote for `qos`.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @derekwaynecarr @vishh @sjenning

**Comment by derekwaynecarr** [comment]
This is not a release blocker and should be 1.6.

**Comment by derekwaynecarr** [comment]
+1 on qos
