### ISSUE TITLE
Should have '--selector' option for create service command to specify the labels

### ISSUE THREAD

**Issue by zhouying7780** [kubernetes/kubernetes#33253]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): create service

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by zhouying7780** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1377939

**Comment by kargakis** [comment]
cc: @kubernetes/kubectl

**Comment by deads2k** [comment]
I think I prefer this approach: https://github.com/kubernetes/kubernetes/pull/28949 .

Given that the field is mutable, I think that's more in keeping with the goals of `kubectl create` here: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/kubectl-conventions.md#create-commands.

**Comment by AdoHe** [comment]
I prefer #28949 too.
