### ISSUE TITLE
Openstack cinder volumes not detached from downed vm when pod is rescheduled to another node.

### ISSUE THREAD

**Issue by Rotwang** [kubernetes/kubernetes#33288]
**Kubernetes version** (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.0.1062+1070a518301f0b", GitCommit:"1070a518301f0bfb6f6c8832feff0bba0c391a22", GitTreeState:"clean", BuildDate:"2016-09-20T11:34:18Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Also tried with 1.3.6

**Environment**:
- **Cloud provider or hardware configuration**: openstack
- **OS** (e.g. from /etc/os-release): ubuntu 14.04
- **Kernel** (e.g. `uname -a`): 3.13.0-93-generic
- **Install tools**: deb package (not selfhosted)
- **Others**: May be related to #32716  #28643  #28671

**What happened**:
If compute instance with attached volume is downed (physical volume in kubernetes terms), kubernetes doesn't try to detach said volume (ever). End result is that k8s is trying to attach a volume in a loop but never succeeds because it is already attached to a downed node.  I've waited for more than an hour for the volume to be detached (didn't help :c)

**What you expected to happen**:
I expect controller-manager or kubelet to detach volume before trying to attach it to a new compute instance. 

**How to reproduce it** (as minimally and precisely as possible):
Bring up cluster with two nodes on openstack. Schedule pod with a pvc. Shutdown (from the command line on the operating system) the node with attached volume. Pod gets rescheduled to another node, but volume stays with the downed node.

**Anything else do we need to know**:
I've looked through reconcile.go on both kubelet and controller-manager it seems to me that once a node is downed it is no longer on the list of nodesManaged (in desired_state_of_world.go) so it's volume is never going to be detached. I've also tried to disable --enable-controller-attach-detach on a kubelet, but it doesn't try to detach it either.

**Comment by Rotwang** [comment]
Additionally after bringing back compute instance up (the one with required volume), so that 'kubectl get nodes' lists it as 'Ready' volume is not being detached (even after 3 hours).

**Comment by slawiek** [comment]
In the scenario when pod is forced to delete by kubectl delete pod command, pod is rescheduled to another node. Without forcibly detach volume fix, scenario would end with failure as cinder volume is attached to another k8s node. It is very annoying, especially pod is hosting database on persistent volume.
Would this fix be part of official kubernetes 1.4 or/and 1.5 release?
