### ISSUE TITLE
Rescheduler e2e should not scale kube-dns pods.

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#33289]
In [rescheduler e2e test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/rescheduler.go), for It("should ensure that critical pod is scheduled in case there is no resources available"), kube-dns is used as the critical pod target and being scaled out and in.

However, we plan to enable the dns horizontal autoscaling feature in the near future, such as this [WIP](https://github.com/kubernetes/kubernetes/pull/33239). If this feature is turned on, the corresponding autoscaler will fight with this rescheduler e2e and maintain the desired number of replicas. Hence this test will be very likely to fail.

So probably we should use another critical pod here, or either create a new critical pod that does not exist before in order to protect the ongoing functionalities.

@piosz  @thockin

**Comment by piosz** [comment]
@MrHohn thanks for letting me know. What is the ETA for enabling horizontal autoscaler for DNS?

**Comment by MrHohn** [comment]
I think it would be enabled not later than the next release.

**Comment by MrHohn** [comment]
Sorry to bother, is there an ETA for this?

FYI, as #34513 merged, we will upgrade the addon-manager to support rolling update for `Deployment` once `kubectl apply --prune` is ready to go. After that I will start working on enabling horizontal autoscaler for `kube-dns`. These will happen before 1.5 code freeze.

**Comment by piosz** [comment]
Sorry for the delay. #35428 fix this

**Comment by MrHohn** [comment]
Thanks for helping!
