### ISSUE TITLE
Federation: Configure a soak test job in Jenkins CI 

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#33284]
#33186 highlighted the fact that we do not yet have a soak test for Federation configured in Jenkins.

The basic idea is to have a CI test job which repeatedly runs all of our e2e tests, over and over, against a single federation, without tearing it down between runs. Typically we run the clusters for about a week.  This can be modelled on the existing Kubernetes soak tests:

https://k8s-testgrid.appspot.com/google-soak

@colhom @madhusudancs would either of you like to take a shot at this for v1.5?

cc @kubernetes/sig-cluster-federation

**Comment by quinton-hoole** [comment]
Deepak from Huawei has offered to find someone to do this.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#72.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
