### ISSUE TITLE
Move contrib/mesos to a separate repository

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#33283]
I think we need to define a plan for this part of the code moving forward.

* I am not aware of a SIG that sponsors feature evolution in this area of the code.
* Is this a good candidate to move out of tree and put in a kubernetes-incubator organization with a sponsoring champion?
* It appears to be packaged here:
 * https://github.com/mesosphere/kubernetes-mesos/commits/master

/cc @kubernetes/sig-api-machinery @k82cn

**Comment by deads2k** [comment]
I agree that this is a strong candidate for moving out of tree.  The smoke tests haven't been run in ages, but everyone in the community is paying a maintenance tax for maintaining compilation and unit tests on code that has diverged from core kube pretty significantly.

Because the `contrib/mesos` has forked controller-manager, some controllers (endpoint controller as a fork instance), schedulers, and even parts of the kubelet (its so old its still called a minion) it's likely that this code hasn't had parity with kubernetes for quite some time.

**Comment by thockin** [comment]
@karlkfi

**Comment by k82cn** [comment]
I'll handle the smoke tests, and will also propose the roadmap; SIG will be better to discuss the candidate projects.

**Comment by deads2k** [comment]
> I'll handle the smoke tests, and will also propose the roadmap; SIG will be better to discuss the candidate projects.

I think that the boundaries around the core kubernetes code in this repo need to be considered.  We have core interfaces and we have plugins for compiling in bits of functionality that conform to those interfaces under `plugins`.  However, once an extension reaches the point where it has forked the command binaries, changed the implementation of core controllers, and wrapped other binaries it has exceeded the point of structured plugin.

I think a SIG devoted to the effort is a great idea, but the current structure really lends itself to a separate repo more than it does it the main repo.  `contrib/mesos` is trying to reshape some core pieces of kubernetes function.  That reshaping is very interesting, but I don't think it belongs in the main repo.  It won't scale well as other runtimes want to adopt it and do the same thing.  These pieces need to grow at their own pace.

**Comment by deads2k** [comment]
To be clear, I think the SIG would own the incubator project.  That would give it strong control over its own destiny without maintaining an in-tree fork of kube.

**Comment by k82cn** [comment]
Understood your concern :). But I'd suggest to keep `contrib/mesos` in tree, because it's better for k8s to support different cloud provider (resource manager/provider) which is chose on startup, e.g. `k8s-scheduler --cloud-provider=mesos`. For reshap part, I'll list it in roadmap.

**Comment by deads2k** [comment]
> Understood your concern :). But I'd suggest to keep contrib/mesos in tree, because it's better for k8s to support different cloud provider (resource manager/provider) which is chose on startup, e.g. k8s-scheduler --cloud-provider=mesos. For reshap part, I'll list it in roadmap

The cloud provider plugin doesn't actually live in `contrib/mesos`.  The cloud provider lives here https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/mesos/mesos.go  alongside all the other cloud providers.  It has no relationship to `contrib/mesos` and it implements one of those core interfaces.

`contrib/mesos` is way to build a separate binary called `km` which provides a way to launch the forked commands `km apiserver`, `km controller-manager`, and `km scheduler`.

**Comment by k82cn** [comment]
I mean the target/roadmap, not the current implementation (`km`).
Except daily maintenance, e.g. flaky test, we're also planning the roadmap of k8sm; and also want to make it general for other resource managers, e.g. [EGO](http://sched.co/8K3n), [YARN](http://hortonworks.com/blog/docker-kubernetes-apache-hadoop-yarn/).

**Comment by davidopp** [comment]
+1 for moving contrib/mesos to a separate repo. I realize it's a nontrivial amount of work, but I think it needs to be done sooner or later.

**Comment by smarterclayton** [comment]
Moving it to a separate repo helps make our tooling stronger by ensuring
that core Kube is amenable to deep composition via its build chain.  Many
of our extension points are "in theory" - we want them to be possible, but
do not force ourselves yet to fully enable the extension.  This is a good
case of "extension by compilation" that mirrors others in the ecosystem.

We would need to consider the implications of what that support would
entail, but I believe it is a win (on top of the other points raised on the
thread)

**Comment by bgrant0607** [comment]
Ref #24343

**Comment by k82cn** [comment]
@bgrant0607 , interesting :).

**Comment by thockin** [comment]
IMO even cloud provider should be a different repo, so I am also advocating
ejection.

**Comment by k82cn** [comment]
@bgrant0607 , can we also this into the list of #24343 ?

**Comment by deads2k** [comment]
How about creating a new kubernetes-incubator project called `kube-mesos-framework`.  @k82cn could be the owner for the new project and we'd be able to clone kubernetes/kubernetes for its initial starting point.  After the split, we'll be able safely remove the the kubernetes/contrib/mesos and update the docs to point to the new repo for building the kube-mesos-framework.

**Comment by davidopp** [comment]
> clone kubernetes/kubernetes

Maybe I'm not understanding the proposal, but this seems a bit extreme. Won't this cause the kubernetes-on-mesos code to diverge from "true" kubernetes very quickly?

**Comment by deads2k** [comment]
> Maybe I'm not understanding the proposal, but this seems a bit extreme. Won't this cause the kubernetes-on-mesos code to diverge from "true" kubernetes very quickly?

It's just a clean starting point for the new project to start from.  Once @k82cn sorts out vendoring, he'll be able to rebase on a cadence that suits the project and refactor dependencies to start relying on kube as built as opposed to kube as forked.

As it stands now, the fork of the controller start up seems to be slipping, but it's making fixes to the controller infrastructure more difficult, but the structure isn't actually helping to keep us in sync.  Things that work in in kube and don't in the fork at first glance:
 1. quota - configmaps don't replenish
 1. pod disruption budgets
 1. petsets
 1. scheduled jobs
 1. attach detatch
 1. CSRs
 1. garbage collection

We're paying a cost for keeping this in tree, but it's not keeping us "in sync".  The divergence from "true" kubernetes only reflects the reality that is hidden today.  We have the problem, but people don't realize it and its not just a few minor bits around the edges.

**Comment by deads2k** [comment]
I'll also point out that if we agree that this should move out of tree, then we're just talking about when we rip off he bandaid.  No matter when we do it, the drift will begin.  Now seems as good a time as any.

**Comment by deads2k** [comment]
> It's just a clean starting point for the new project to start from. Once @k82cn sorts out vendoring, he'll be able to rebase on a cadence that suits the project and refactor dependencies to start relying on kube as built as opposed to kube as forked.

I suspect that when the work is done, the vast majority (90%+) of kubernetes/kubernetes will be removed from the `kube-mesos-framework` repo and that the roadmap will probably be trying to remove the last vestiges.

**Comment by k82cn** [comment]
Regardless of whether or not to move it out, I'm the owner of "Kubernetes on Mesos", including bug fix, sync with upstream, roadmap and so on; If any requirement/issues, please ping me directly :).

>As it stands now, the fork of the controller start up seems to be slipping, but it's making fixes to the controller infrastructure more difficult, but the structure isn't actually helping to keep us in sync. 

Does it also mean k8s not support 3rd part resource manager well? Suggest to enhance the interface for 3rd part resource managers, the Mesos is the first one/high priority. I'd like to propose the design when enhancing k8sm.

>clone kubernetes/kubernetes

@davidopp, do no worry, one Kubernetes is baseline to us.
