### ISSUE TITLE
federation: creating events on federation namespaces is failing

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#33292]
https://github.com/kubernetes/kubernetes/pull/31640 added events to federation namespace controller, but creating namespace events is failing on our e2e tests:

```
Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"e2e-tests-federation-replicaset-s7xan.147625127063baf8", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]api.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:api.ObjectReference{Kind:"Namespace", Namespace:"", Name:"e2e-tests-federation-replicaset-s7xan", UID:"80f0b389-7f78-11e6-898f-0a580ab50304", APIVersion:"v1", ResourceVersion:"4", FieldPath:""}, Reason:"CreateInCluster", Message:"Creating namespace in cluster federation-e2e-gce-us-central1-f", Source:api.EventSource{Component:"federated-namespace-controller", Host:""}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63610003489, nsec:135639288, loc:(*time.Location)(0x84ad960)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63610003489, nsec:135639288, loc:(*time.Location)(0x84ad960)}}, Count:1, Type:"Normal"}': 'namespaces "default" not found' (will not retry!)
```

It is because, namespaces do not have ObjectMeta.Namespace set and the event recorder library uses that to figure out the namespace in which the event should be generated: https://github.com/kubernetes/kubernetes/blob/a8053c7c59024a40bac5debe31857084d79729c2/pkg/client/record/event.go#L299.

We have 2 options to fix this:
- Update the library to use the namespace name if the ObjectReference is for a namespace object.
- Ensure that api.NamespaceDefault namespace exists in federation

cc @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
@lavalamp pointed out that the first option will not work for ex: when we are trying to create an event for "CouldNotCreateNamespace". Since that namespace does not exist, we will not be able to create the event in that namespace.
So will have to go with the second option i.e to ensure that namespace default exists in federation control plane

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @nikhiljindal @lavalamp

**Comment by dims** [comment]
@nikhiljindal all issues must be labeled either release blocker or non release blocking by end of day 18 November 2016 PST. (or please move it to 1.6) cc @kubernetes/sig-cluster-federation

**Comment by madhusudancs** [comment]
This is not a release blocker for v1.5 either.

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by ahmetb** [comment]
I am going to just type a few keywords here because this issue doesn't come up when you search on Google. It is not documented anywhere (incl. tutorials) that kubefed doesn't create the default namespace.

- kubefed does not create default namespace
- kubernetes federation default namespace missing
- Error from server (NotFound): namespaces "default" not found

**Comment by clenimar** [comment]
is anyone working on this issue? @nikhiljindal

**Comment by nikhiljindal** [comment]
Not that I know of.
The task here is to call BootstrapController at `pkg/master/controller` from `federation-apiserver`. It is right  now being called only from `kube-apiserver`.

That controller creates both the kubernetes service and the default namespace. In federation we only need the default namespace. Will also need to refactor the code since federation cant depend on `pkg/master` (pkg/master is kubernetes specific code).

**Comment by quinton-hoole** [comment]
This is required for GA.  Prioritizing accordingly.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#73.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
