### ISSUE TITLE
([k8s.io] Loadbalancing: L7 [Feature:Ingress] [k8s.io] GCE [Feature: Ingress] shoud create ingress with given static-ip)

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#33299]
GCI Test Failing: (kubernetes-e2e-gci-gke-ingress-release-1.3) ([k8s.io] Loadbalancing: L7 [Feature:Ingress] [k8s.io] GCE [Feature: Ingress] shoud create ingress with given static-ip)

https://k8s-testgrid.appspot.com/google-gke#gci-gke-ingress-release-1.3

**Comment by vishh** [comment]
Two ingress tests are failing on GKE release 1.4 branch - https://k8s-testgrid.appspot.com/release-1.4-all#gci-gke-ingress-release-1.4

They are passing on GCE though - https://k8s-testgrid.appspot.com/release-1.4-all#gci-gce-ingress-release-1.4

**Comment by vishh** [comment]
Failing on GKE in general - https://k8s-testgrid.appspot.com/release-1.4-all#gke-ingress-release-1.4

**Comment by bprashanth** [comment]
as far as i can tell the tests aren't even running right? 
```
... Using network: jenkins-e2e
... Using firewall-rule: jenkins-e2e-allow-ssh
ERROR: (gcloud.container.clusters.create) ResponseError: code=500, message=Inter
```

Anyway there's also https://github.com/kubernetes/kubernetes/issues/33300 which is because of the reson described on that bug (default quota is insufficient)

**Comment by bprashanth** [comment]
This cherrypick also fixes a test leak: https://github.com/kubernetes/kubernetes/pull/33460, assuming the tests are running against 1.4 GKE

**Comment by bprashanth** [comment]
The plain gke failures are https://github.com/kubernetes/kubernetes/issues/33611

**Comment by bprashanth** [comment]
All 3 "normal" GKE runs just passed so I'm going to put this down to random gcloud 500 tracked by https://github.com/kubernetes/kubernetes/issues/33611: 
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke-ingress/
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke-ingress-release-1.4/
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke-ingress-release-1.3/

Btw they only failed this morning. 
I'm leaving this open till the gci quota issues are resolved.

**Comment by vishh** [comment]
Ping @mtaufen on the quota issues.

**Comment by bprashanth** [comment]
I've already bumped them, they're waiting for approval

**Comment by cmluciano** [comment]
/close

The two linked issues are marked as resolved.
