### ISSUE TITLE
GCI Test Failing: (kubernetes-gci-gce-alpha-features-release-1.4) ([k8s.io] PetSet [Slow] [Feature:PetSet] [k8s.io] Deploy clustered applications [Slow] [Feature:PetSet] should creating a working redis cluster [Feature:PetSet])

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#33316]
GCI Test Failing: (kubernetes-gci-gce-alpha-features-release-1.4) ([k8s.io] PetSet [Slow] [Feature:PetSet] [k8s.io] Deploy clustered applications [Slow] [Feature:PetSet] should creating a working redis cluster [Feature:PetSet])

https://k8s-testgrid.appspot.com/google-gce#gci-gce-alpha-features-release-1.4

**Comment by foxish** [comment]
Closing as it appears to be identical to https://github.com/kubernetes/kubernetes/issues/33315
