### ISSUE TITLE
Make  TestConfig an object rather than a statically referenced var

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#33314]
_Problem_

Lots of default handling in tests for == 0 and so on with TestConfig... 

```
if framework.TestContext.Cadvisor.MaxRetries == 0 {
+           retry = 6
+           framework.Logf("Overriding default retry value of zero to %d", retry)
+       }
```

_Solution_
- Add isSet primitives (but for sanity, make sure these are decoupled from viper.IsSet) to TestConfig, 
- to do this, we need to make TestConfig a struct, and then we can setup defaults in a centralized way as much as possible in the NewTestConfig function.

cc @kubernetes/sig-testing

**Comment by jayunit100** [comment]
follow up after #24536

**Comment by pwittrock** [comment]
@ixdy Does this fall under test-infra?

**Comment by ixdy** [comment]
kindof? I think we've mostly handed over ownership of everything under test/.

@jayunit100 I'm going to assign this back to you, since it looks like a follow-on to work you're doing?

**Comment by jayunit100** [comment]
assign to @sjug i think is better

**Comment by sjug** [comment]
Sounds good
