### ISSUE TITLE
GCI Test Failing: (kubernetes-e2e-gci-gce-alpha-features-release-1.4) ([k8s.io] PetSet [Slow] [Feature:PetSet] [k8s.io] Deploy clustered applications [Slow] [Feature:PetSet] should creating a working zookeeper cluster [Feature:PetSet])

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#33317]
GCI Test Failing: (kubernetes-e2e-gci-gce-alpha-features-release-1.4) ([k8s.io] PetSet [Slow] [Feature:PetSet] [k8s.io] Deploy clustered applications [Slow] [Feature:PetSet] should creating a working zookeeper cluster [Feature:PetSet])

https://k8s-testgrid.appspot.com/google-gce#gci-gce-alpha-features-release-1.4

**Comment by foxish** [comment]
Closing for now as the issue is identical to https://github.com/kubernetes/kubernetes/issues/33315
