### ISSUE TITLE
GCI Test Failing: (kubernetes-e2e-gci-gce-reboot-release-1.3) ([k8s.io] Reboot [Disruptive] [Feature:Reboot] each node by dropping all outbound packets for a while and ensure they function afterwards)

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#33322]
GCI Test Failing: (kubernetes-e2e-gci-gce-reboot-release-1.3) ([k8s.io] Reboot [Disruptive] [Feature:Reboot] each node by dropping all outbound packets for a while and ensure they function afterwards)

https://k8s-testgrid.appspot.com/google-gce#gci-gce-reboot-release-1.3

**Comment by dchen1107** [comment]
Marked this as the dup of #36230
