### ISSUE TITLE
kubectl describe secret exposes its contents

### ISSUE THREAD

**Issue by julienvincent** [kubernetes/kubernetes#33333]
Your documentation reads as follows:

> Note that neither get nor describe shows the contents of the file by default. This is to protect the secret from being exposed accidentally to someone looking or from being stored in a terminal log.
See decoding a secret for how to see the contents.

However when creating the secret with a `yml` template, running `kubectl describe secrets/my-secret` returns a description containing `Annotations`, which contains the last run `yml` template.

Not a huge issue, thought you might want to be aware of this though.

**Comment by AdoHe** [comment]
@julienvincent you are using `kubectl apply` for secret?

**Comment by julienvincent** [comment]
@AdoHe yes

**Comment by AdoHe** [comment]
@julienvincent https://github.com/kubernetes/kubernetes/issues/23564, ptal.

**Comment by julienvincent** [comment]
apologies - did not see that issue.
