### ISSUE TITLE
Discussion: Version skewed e2e tests

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#3334]
There is a somewhat heavy dev burden to pay if the tests in `hack/e2e-suite` have to run against old cluster versions. Take the issue fixed in #3314. Was @thockin supposed to run e2es against all released versions of the code? Questions here:
* Do we even want to support version skewed e2e tests?
* What's the line? What GKE supports? (That seems arbitrary.) The official k8s upgrade matrix (when we resolve that)? What?
* If we don't, how are we planning on supporting cross-version testing? We could potentially do something where we're grabbing new binaries and running old tests, but then we could just be running crappy tests. The tests at head also represent improvements to the test.

We may also be overthinking the dev burden. I think the problem here:https://github.com/GoogleCloudPlatform/kubernetes/commit/e045c6ce2fd81b85637894a1655a90bc367b90f7#commitcomment-9206336 (fixed in #3314) may actually be mitigated by abstracting the "shoot things in the head" pieces into a library. We could then test the library against all dev releases, and ask everyone to run e2e tests against HEAD, and if you add one of these "muck with cluster internals" things, only then do you need to add a version specific piece and do it cross-versioned. I think there's definite room for refactoring here.

Other relevant reading includes:
* https://docs.google.com/document/d/1wwh569PwAWvEZcLc0gHSrO1xr-N-T5cnKjepjc0dXvI/edit#heading=h.20sqp7sxyy7q
* https://github.com/GoogleCloudPlatform/kubernetes/issues/2953 (to help with how to actually accomplish shooting things in the add during development, as we're adding features)
* ... and I'm probably missing some.

cc @thockin @roberthbailey @lavalamp 

(kicking this off, then running away for a few hours)

**Comment by lavalamp** [comment]
The purpose of running head's e2e against an old cluster is to verify that the *client* hasn't broken compatibility, and I'd argue therefore that @thockin's change to service impl shouldn't have been run against an older cluster version. [*]

So we may need to tag our e2e tests with the purpose of the test. Some of them don't make sense to run against other cluster versions.

[*] It would make sense to run the service test like this: run the old service test against an old cluster; upgrade the cluster; run the new service test against the new cluster.

**Comment by zmerlynn** [comment]
Anytime you use the phrase "run the old test", remember: That's "run the
old (possibly crappy) test". There's a reason some companies keep tests in
an entirely separately versioned repo. :/

**Comment by ihmccreery** [comment]
I'm marking this as obsolete, with #16040 tracking the remaining issues.

To test upgrades and version skew, we currently:

1. deploy a cluster at old version
1. run new `kubectl` tests against it (this is what's still a open in #16040)
1. upgrade the master
1. run all old e2e tests (the cluster should still function as before with the new master version)
1. upgrade the nodes
1. run old e2e tests again (the cluster should still function as before with the new node version)
1. run new e2e tests (the cluster should function like a brand new cluster at the new version)
