### ISSUE TITLE
Follow up Federated Ingress test failures and address review comments in PR #33339

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#33350]
PR #33339 fixes a known bug but it still does not fix all the Federated Ingress test failures. So this is a note to follow up on those failures and address the optional review comments left in the PR.

cc @kubernetes/sig-cluster-federation @nikhiljindal

**Comment by quinton-hoole** [comment]
The fix for this is being developed in https://github.com/kubernetes/kubernetes/pull/33372

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @quinton-hoole @madhusudancs

**Comment by madhusudancs** [comment]
I am just going to close this. There are a number of issues tracking this known failure.
