### ISSUE TITLE
SELinux: Kubelet directory should not have to be labeled svirt_sandbox_file_t

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#33351]
Currently, the Kubelet directory has to be labeled `svirt_sandbox_file_t` on systems using SELinux.  This is disadvantageous because the `svirt_sandbox_file_t` type is usable from any container -- meaning that a container process escaping its namespace isolation will be able to use any file or directory with that type.  We can make Kubernetes more secure on systems using SELinux by allowing the Kubelet directory to be labeled with a type unusable from a container (like `var_lib_t`).

Some users have tried this; there are a couple bugs that need to be fixed; the following are not currently usable when the Kubelet directory is not labeled as `svirt_sandbox_file_t`.
1.  Termination message
2.  Hosts file
3.  Secrets and EmptyDir memory medium

Users work around these by either making containers privileged (which means, in Docker, that they run as `unconfined_t`) or enabling permissive mode, both of which lessen the security of the system.

**Comment by zhouhaibing089** [comment]
I am curious why does selinux labels on host would affect containers? isn't about port the volume selinux feature to kubelet?

ref: http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/

**Comment by pmorie** [comment]
@zhouhaibing089 - There are a couple dimensions that it affects things in currently (which I am fixing in a branch that I will make a PR for shortly):

1.  The hosts file and termination log files aren't mounted with the :Z option; they rely on the directory they're created in being usable from a container in order to get the right context
2.  We also read the SELinux context of the Kubelet directory in order to supply the right `rootcontext` args for tmpfs mounts

Does that clarify things?

**Comment by zhouhaibing089** [comment]
> The hosts file and termination log files aren't mounted with the :Z option

I would like to understand why not then..

> We also read the SELinux context of the Kubelet directory in order to supply the right rootcontext args for tmpfs mounts.

There is also a why, why it depends on the context of kubelet directory.

IIUC, all the directories that mount to container should be labeled with correct context, why it depends on something else?
