### ISSUE TITLE
Failed to build hypercube image 

### ISSUE THREAD

**Issue by ilovetina2006** [kubernetes/kubernetes#33360]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
v1.3.7

**Environment**:
- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release): centOS 7
- **Kernel** (e.g. `uname -a`):Linux zhouzong-1-e426f249-e94c-439d-a300-ae836e93dada 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
1.After running : /home/cmcc/k8s_1.3.7/cluster/images/hyperkube/make build VERSION=v1.3.7,the error below happened.

cp ../../../_output/dockerized/bin/linux/amd64/hyperkube /tmp/tmp.HzRR8SYT3E
cp: cannot stat ‘../../../_output/dockerized/bin/linux/amd64/hyperkube’: No such file or directory
make: **\* [build] Error 1

2.According to README, "# First, build the binaries:$ build/run.sh hack/build-cross.sh", after running" build/run.sh: No such file or directory" " hack/build-cross.sh: No such file or directory"

**What you expected to happen**:

the necessary files for building images should be tarred together. we suggest you do it first.

**How to reproduce it** (as minimally and precisely as possible):
always happen when you build the hypercube image.

**Anything else do we need to know**:

**Comment by duglin** [comment]
Is this still an issue?

**Comment by ilovetina2006** [comment]
YES.If nothing has been done since then. I suggest  all of the files needed to create the images put together     in the compressed archive. thx.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.
