### ISSUE TITLE
add ThirdPartyResourceData client?

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#33362]
No ThirdPartyResourceData client provided? It will be much more convenient if we have an official ThirdPartyResourceData client, so that a third party developer could leverage the existing Informer framework to list&watch his own resource.

@liggitt @brendandburns @caesarxuchao

**Comment by caesarxuchao** [comment]
I think we should give it a client. It's as easy as adding `+genclient=true` before this [line](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/v1beta1/types.go#L204).

**Comment by liggitt** [comment]
I didn't think ThirdPartyResourceData was exposed via rest apis, but was supposed to be interacted with via the registered third party API group and kind

**Comment by caesarxuchao** [comment]
Ah, @liggitt is right.

**Comment by mqliang** [comment]
@caesarxuchao 
>  It's as easy as adding +genclient=true before this line.

I am not very familiar with the code of client generation, but it may no work IIUC. 

For example, if I add a ThirdPartyResource with `Group=mycompany.io, Version=v1, Kind=Foo`, what I expect the client work as: send request to url `apis/mycompany.io/v1/namesapces/{namespace}/foos`, and decode the response body as a ThirdPartyResourceData struct. 

However, what I get from adding `+genclient=true` is: client will send request to url `apis/extensions/v1beta1/namesapces/{namespace}/thirdpartyresourcedatas`

**Comment by mqliang** [comment]
@caesarxuchao 

Actually, I have tried to wrap a kubeclient by hijacking the [Codec](https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/extensions/thirdpartyresourcedata/codec.go#L245) and [NegotiatedSerializer](https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/extensions/thirdpartyresourcedata/codec.go#L200) of ThirdPartyResourceData into the client. However, the client could send request to correct url, but it could not decode the response. 

The client will throw an error `{kind} is not registered in {group}/{api}`

My wrap client is as follows:

```
package kubeclient

import (
	"k8s.io/kubernetes/pkg/client/restclient"
	"k8s.io/kubernetes/pkg/client/unversioned"

	"k8s.io/kubernetes/pkg/api"
	groupversion "k8s.io/kubernetes/pkg/api/unversioned"
	"k8s.io/kubernetes/pkg/registry/thirdpartyresourcedata"
	"k8s.io/kubernetes/pkg/runtime"
)

type KubeClientWrap struct {
	*unversioned.Client
	*ThirdPartyResourceDataClient
}

type ThirdPartyResourceDataClient struct {
	*restclient.RESTClient
	resourceKind string
}

func NewKubeClientWrap(c *restclient.Config, gvk groupversion.GroupVersionKind) (*KubeClientWrap, error) {
	kubeClient, err := unversioned.New(c)

	var thirdPartyResourceDataClient *ThirdPartyResourceDataClient
	thirdPartyResourceDataConfig := *c
	thirdPartyResourceDataClient, err = NewThirdPartyResourceDataClient(&thirdPartyResourceDataConfig, gvk)
	if err != nil {
		return nil, err
	}

	return &KubeClientWrap{Client: kubeClient, ThirdPartyResourceDataClient: thirdPartyResourceDataClient}, nil
}

func NewThirdPartyResourceDataClient(c *restclient.Config, gvk groupversion.GroupVersionKind) (*ThirdPartyResourceDataClient, error) {
	config := *c
	if err := setThirdPartyResourceDataDefaults(&config, gvk); err != nil {
		return nil, err
	}
	client, err := restclient.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &ThirdPartyResourceDataClient{client, gvk.Kind}, nil
}


func setThirdPartyResourceDataDefaults(config *restclient.Config, gvk groupversion.GroupVersionKind) error {
	config.APIPath = "/apis"
	if config.UserAgent == "" {
		config.UserAgent = restclient.DefaultKubernetesUserAgent()
	}

	gv := gvk.GroupVersion()
	config.GroupVersion = &gv

	internalGroupVersion := groupversion.GroupVersion{Group: gvk.Group, Version: runtime.APIVersionInternal}
	externalGroupVersion := groupversion.GroupVersion{Group: gvk.Group, Version: gvk.Version}

	config.Codec = thirdpartyresourcedata.NewCodec(api.Codecs.LegacyCodec(*config.GroupVersion), gvk)
	config.NegotiatedSerializer = thirdpartyresourcedata.NewNegotiatedSerializer(api.Codecs, gvk.Kind, externalGroupVersion, internalGroupVersion)

	if config.QPS == 0 {
		config.QPS = 5
	}
	if config.Burst == 0 {
		config.Burst = 10
	}
	return nil
}
```

```
package kubeclient

import (
	"k8s.io/kubernetes/pkg/api"
	"k8s.io/kubernetes/pkg/apis/extensions"
	"k8s.io/kubernetes/pkg/registry/thirdpartyresourcedata"
	"k8s.io/kubernetes/pkg/watch"
)

var parameterCodec = thirdpartyresourcedata.NewThirdPartyParameterCodec(api.ParameterCodec)

// ThirdPartyResourceDataInterface has methods to work with ThirdPartyResourceData resources.
type ThirdPartyResourceDataInterface interface {
	List(opts api.ListOptions) (*extensions.ThirdPartyResourceDataList, error)
	Get(name string) (*extensions.ThirdPartyResourceData, error)
	Delete(name string, options *api.DeleteOptions) error
	Create(data *extensions.ThirdPartyResourceData) (*extensions.ThirdPartyResourceData, error)
	Update(data *extensions.ThirdPartyResourceData) (*extensions.ThirdPartyResourceData, error)
	Watch(opts api.ListOptions) (watch.Interface, error)
}

func (c *KubeClientWrap) ThirdPartyResourceDatas(namespace string) ThirdPartyResourceDataInterface {
	return newThirdPartyResourceDatas(c, namespace)
}

type tprd struct {
	r  *ThirdPartyResourceDataClient
	ns string
}

func newThirdPartyResourceDatas(c *KubeClientWrap, namespace string) *tprd {
	return &tprd{
		r:  c.ThirdPartyResourceDataClient,
		ns: namespace,
	}
}

func (c *tprd) List(opts api.ListOptions) (result *extensions.ThirdPartyResourceDataList, err error) {
	result = &extensions.ThirdPartyResourceDataList{}
	err = c.r.Get().Namespace(c.ns).Resource(c.r.resourceKind+"s").VersionedParams(&opts, parameterCodec).Do().Into(result)
	return
}

func (c *tprd) Get(name string) (result *extensions.ThirdPartyResourceData, err error) {
	result = &extensions.ThirdPartyResourceData{}
	err = c.r.Get().Namespace(c.ns).Resource(c.r.resourceKind + "s").Name(name).Do().Into(result)
	return
}

func (c *tprd) Delete(name string, options *api.DeleteOptions) error {
	return c.r.Delete().Namespace(c.ns).Resource(c.r.resourceKind + "s").Name(name).Body(options).Do().Error()
}

func (c *tprd) Create(data *extensions.ThirdPartyResourceData) (result *extensions.ThirdPartyResourceData, err error) {
	result = &extensions.ThirdPartyResourceData{}
	err = c.r.Post().Namespace(c.ns).Resource(c.r.resourceKind + "s").Body(data).Do().Into(result)
	return
}

func (c *tprd) Update(data *extensions.ThirdPartyResourceData) (result *extensions.ThirdPartyResourceData, err error) {
	result = &extensions.ThirdPartyResourceData{}
	err = c.r.Put().Namespace(c.ns).Resource(c.r.resourceKind + "s").Name(data.Name).Body(data).Do().Into(result)
	return
}

func (c *tprd) Watch(opts api.ListOptions) (watch.Interface, error) {
	return c.r.Get().
		Prefix("watch").
		Namespace(c.ns).
		Resource(c.r.resourceKind+"s").
		VersionedParams(&opts, parameterCodec).
		Watch()
}
```

**Comment by liggitt** [comment]
I don't think that's what we want a client for a thirdpartyresource to look like. We should be able to use a dynamic client to list/watch arbitrary resources in arbitrary groups (including ones that exist because of registered thirdpartyresources, but without the client having to be aware that the resource was registered as a third party resource). @krousey @deads2k @derekwaynecarr do you know if list/watch of arbitrary resources is possible today with the dynamic client?

**Comment by caesarxuchao** [comment]
kubectl can create/get thirdparty object, maybe that will be give you a clue how to build a client. I remember there is a thirdpartycodec, but I haven't looked that code for a while.

As @liggitt mentioned, [dynamic client](https://github.com/kubernetes/client-go/tree/master/1.5/dynamic) is another way. It decodes json data into `map[string]interface{}`, and provided accessors to the object's metadata.

**Comment by brendandburns** [comment]
yeah, the resource stuff in resource.go can handle dynamic objects, but that's definitely not the happy path to figure out how to use a client library.  dynamic client is a way better bet, unless the resource Builder pattern works for you (and it's pretty deeply embedded in kubectl)

**Comment by derekwaynecarr** [comment]
I had explored the client generation stuff in a past PR here:
https://github.com/kubernetes/kubernetes/pull/25587

I abandoned it when I realized the URL forms created were not going to be
correct.

**Comment by mqliang** [comment]
dynamic client works, close this
