### ISSUE TITLE
Extend `local-up-cluster.sh` to be able to start with the secured port 

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#33375]
Followup to https://github.com/kubernetes/kubernetes/pull/31491

Extend `local-up-cluster.sh` to be able to start with the secured port available using https://github.com/kubernetes/kubernetes/pull/31491 and an option to close the insecured port so that its easy to start determining which permissions the controllers need.

The controller manager should try to make use of the secured port hidden behind an option since that's broken at the moment.

**Comment by dims** [comment]
Thanks for opening the issue @deads2k :)

**Comment by dims** [comment]
Once https://github.com/kubernetes/kubernetes/pull/33966 merges, next step is to create an identity for the controller-manager. We should also setup the `--service-account-private-key-file` for controller-manager as well.

One option is to use `cfssl` to create a `system:masters` identity via the `--kubeconfig` option to setup the client that is used to talk to the api server.

(cc @deads2k)

**Comment by deads2k** [comment]
> One option is to use cfssl to create a system:masters identity via the --kubeconfig option to setup the client that is used to talk to the api server.

I think this a good starting point.
