### ISSUE TITLE
Per-Container Inode Accounting

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#33382]
cc: @derekwaynecarr (how can we get devicemapper support for this?)

when a node has reached its eviction-hard threshold for imagefs.inodes or nodefs.inodes, the eviction manager does not behave optimally.
This is because we do not keep track of inodes used per-container, but rather just overall.  In some cases, the pod which is not using many inodes is evicted before a pod that is using many.

Progress:
- [x] Create an end to end test that demonstrates that a pod using a normal amount of disk capacity is evicted before a pod that uses all remaining inodes (but little disk capacity).
- [x] Modify cadvisor api and kubernetes api to include per-container inode usage 
- [x] Modify cadvisor to publish per-container inode usage
- [x] Modify kubelet eviction manager to take per-container inode usage into account when evicting

**Comment by derekwaynecarr** [comment]
devicemapper has no concept of inodes since it works with blocks and not a filesystem.  If devicemapper is used as graph driver, a container should only be charged for inodes it creates on the rootfs

**Comment by dashpole** [comment]
Great, thanks!

**Comment by dashpole** [comment]
@derekwaynecarr just a follow-up to make sure we are taking the appropriate action.  Right now, we can't use syscall.Statfs to get inodes because it reports the same number for all containers, which includes all inodes in all writeable directories, as well as ones in lower, shared directories.  The solution we are using now is to periodically run a  "find dir -xdev -printf '.' | wc -c" command to find the number of files and directories to give us a fairly accurate estimate of inode usage per pod.
Do we need to explicitly ignore containers whose writable layers use devicemapper?  The -xdev flag ignores mounted directories, as inodes in those directories are accounted seperately.

**Comment by dashpole** [comment]
To test, I started up a rhel docker image and a centos image (because I think those use devicemapper).  I then ran the find command on both directories, in the same way cadvisor does, with and without the -xdev flag.  They both reported inode usage, so it looks like we will have to explicitly report 0 inodes for devicemapper.

**Comment by dashpole** [comment]
Pods may create volumes (emptyDir volumes, for example), that exist in a filesystem shared across pods.  These volumes do not currently track inode usage.  I plan to add this functionality.
Progress:

- [ ] Add a test for this to the inode eviction end to end node test (test/e2e_node/inode_eviction_test.go)

- [ ] Add to the kubernetes summary api and volume stat calculator to introduce monitoring for volume inodes.

- [ ] Make sure the eviction manager correctly utilizes the stats published to the summary api
