### ISSUE TITLE
Easy way to test that browsers will load apiserver pages?

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#3341]
@vishh's chrome refuses to talk to his cluster's apiserver. Does anyone know of an easy way for us to include an e2e test that verifies that we haven't broken cert generation or anything? It'd be awesome if we could actually run chrome/firefox and verify that you can get to the "Welcome to Kubernetes" page...

**Comment by brendandburns** [comment]
We can certainly use curl or wget to test this.  The things that would
break Chrome and not curl are pretty limited in scope.

The problems I see with Chrome generally have to do with certificate
caching (and subsequent mis-matches) across cluster re-installs.

There are also a number of headless web browser toolkits:

(e.g. http://jeanphix.me/Ghost.py/)

That we could use if we really wanted to get fancy.
