### ISSUE TITLE
Add standalone flag to kubelet

### ISSUE THREAD

**Issue by VictorDenisov** [kubernetes/kubernetes#33413]
FEATURE REQUEST?

**Kubernetes version** (use `kubectl version`):
1.5.0-alpha

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

I found a TODO here:

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L300

Which says that kubelet should have a flag --standalone in order to determine it's running in standalone mode.

**What you expected to happen**:

I would like to work on this improvement.
As I imagine I should add a flag to kubelet/app/options/options.go which is named standalone and I should add standalone field to componentconfig.KubeletConfiguration.
The field should be populated from https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L300 command line and then used here instead of calculating the mode:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L300

Please let me know if you think this would be useful or maybe it makes more sense to just remove the TODO.

**Comment by dims** [comment]
@VictorDenisov No need to ask for permission :) just go ahead and file a pull request.

**Comment by VictorDenisov** [comment]
Ok. Just wanted to run this idea by someone first)

**Comment by mtaufen** [comment]
For reference, PR is: https://github.com/kubernetes/kubernetes/pull/33535
