### ISSUE TITLE
kube-up.sh on AWS fails when using existing VPC

### ISSUE THREAD

**Issue by Dmitry1987** [kubernetes/kubernetes#33429]
BUG REPORT:
When trying to use kube-up.sh 2nd time after 1st failure (so it will use existing VPC), an error like this occurs:

---

...
Using VPC vpc-xxxxxxxx
Adding tag to dopt-xxxxxxxxx: Name=kubernetes-dhcp-option-set
Adding tag to dopt-xxxxxxx: KubernetesCluster=k8s14beta
Using DHCP option set dopt-xxxxxxxx
Using existing subnet with CIDR 172.20.0.0/24
Using subnet subnet-xxxxxxxx
Using Internet Gateway igw-xxxxxxxxx
Associating route table.
Associating route table rtb-xxxxxxxxto subnet subnet-xxxxxxxx
Adding route to route table rtb-xxxxxxxx
Using Route Table rtb-xxxxxxxxx
Creating master security group.
Creating security group kubernetes-master-k8s14beta.
Adding tag to sg-xxxxxxxx: KubernetesCluster=k8s14beta
Using master security group: kubernetes-master-k8s14beta sg-xxxxxxxxxx
Generating certs for alternate-names: IP:52.34.28.112,IP:172.20.0.9,IP:10.0.0.1,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster.local,DNS:k8s14beta-master
Starting Master
Adding tag to i-b32c1cab: Name=k8s14beta-master
Adding tag to i-b32c1cab: Role=k8s14beta-master
Adding tag to i-b32c1cab: KubernetesCluster=k8s14beta
Waiting for master to be ready
Attempt 1 to check for master nodeWaiting for instance i-b32c1cab to be running (currently pending)
Sleeping for 3 seconds...
Waiting for instance i-b32c1cab to be running (currently pending)
Sleeping for 3 seconds...
Waiting for instance i-b32c1cab to be running (currently pending)
Sleeping for 3 seconds...
Waiting for instance i-b32c1cab to be running (currently pending)
Sleeping for 3 seconds...
 [master running]

A client error (InvalidAddress.NotFound) occurred when calling the DescribeAddresses operation: Address '52.34.28.112' not found.
Attaching IP 52.34.28.112 to instance i-b32c1cab
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]

**aws: error: argument --allocation-id: expected one argument** 

---

Seems like it tried to access  '52.34.28.112'  before creating it (or before attaching to instance)

**Kubernetes version**:  1.4.beta8  (used this https://github.com/kubernetes/kubernetes/releases/download/v1.4.0-beta.8/kubernetes.tar.gz)

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Debian (default)
- *_My env vars I set before running: *_
  export KUBE_AWS_INSTANCE_PREFIX=k8s14beta;
  export VPC_NAME=k8s14beta-vpc;
  export AWS_S3_REGION=us-west-2;
  export ENABLE_CLUSTER_LOGGING=false;
  export ENABLE_NODE_LOGGING=false;
  export ENABLE_CLUSTER_MONITORING=none;
  export export KUBERNETES_PROVIDER=aws;
  export KUBERNETES_SKIP_DOWNLOAD=no;

**What happened**:
First run 2 days ago of kube-up.sh was ok until some stage where it "couldn't connect to master". 
Then I tried it today again (cleaning up broken instances left from last run, i deleted security groups too, just left the VPC as is, from last attempt).

**How to reproduce it**:
I think possible to reproduce if running kube-up.sh with same env vars I used. It should fail 1st time, and show this error on 2nd attempt.

**Anything else do we need to know**:
The IP it tries to reach on 2nd attempt seems the same it used last time for master, but I deleted master prior to this run, and released its EIP, so expected the script to generate new EIP this time.  Also I don't think I had the EIP anywhere in configs or env vars.. it somehow remembered it from last run.

Would appreciate any advice of how to handle this. Thanks :)

**Comment by justinsb** [comment]
kube-up on AWS has been deprecated and removed, and I recommend https://github.com/kubernetes/kops instead, particularly for more complicated setups such as shared-VPCs.
