### ISSUE TITLE
Exersize more of the client cache ( List, Remove ) in scheduler_perf 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#33431]
_Problem_

In #31795 
- we found that the List operation in CheckServiceAffinity may be a  dominating factor in scheduler cpu usage,  in the schduler @ scale.  
- _since its using so much CPU_ ideally we would have something simulating this problem in the scheduler_perf tests, so they are more realistic / testing scheduler performance under heterogenous node / affinity conditions. However --  from what i can tell, the cache's `List` is not exersized in the scheduler_perf at all.
- roughly, if we look at the amount of calls during one of the test runs... addpod is really 80% or so of the calls that are happening, i.e. annotating the calls in schedulercache/cache.go. i see the following: 

```
forgetpod:209 
addnode:1100 
addpod:17400 
updatepod:3881
```
- listpod, removepod arent being exersized at all.  (NOTE 3/30): Ravi gudimeta has noted that possibly list/remove are being called elsewhere, i.e. in a shared cache).

_Solution_

We should add a more complex scheduler job / soaking into the scheduler_perf tests, so that we can measure real world scheduling bottlenecks (i.e. 1000s of nodes which need to be filtered and matched to pods). 
- More real world changes (updates and predicate scheduling events)
- More pod data churning (deletions/updates)

This would probably lead to a broader and more real-worldish performance profile, most importantly, it would gaurantee that the demanding aspects of scheduling functionality are exersized. 

cc @kubernetes/sig-scheduling

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @jayunit100

**Comment by ravisantoshgudimetla** [comment]
@jayunit100 I was reproduce the issue. On further analysis it seems, the code is pointing to https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/scheduler.go#L81, this happens to be shared lister from client. So, I guess it makes sense that listing is not happening here. I am working on remove now.

**Comment by ravisantoshgudimetla** [comment]
Update:
- List is infact coming from shared lister.  

Following are the values:
- The counters for listing from shared cache are around 176 on average of 3 runs.

**Comment by jayunit100** [comment]
thanks; and What about removepod?

**Comment by ravisantoshgudimetla** [comment]
Update:
As of now, the tests are not exercisizing full predicates and priorities. I added a simple test for inter-pod affinity priority(Dummy nodes used-1000 pods scheduled-3000) and it doubled the hits for list operation from cache. It is probably something, that we need as a test-case.

**Comment by jayunit100** [comment]
update : the architecture improvements necessary for Doing this  are rolled into the 1.7 forensics milestone , "scheduling forensics".

**Comment by ravisantoshgudimetla** [comment]
@jayunit100 - Can we close this issue now?
