### ISSUE TITLE
v1.4.0-beta.11: pod naming scheme regexp wrong?

### ISSUE THREAD

**Issue by vasu1124** [kubernetes/kubernetes#33439]
Could it be that the naming scheme of controllers/pods with ".", like "kubernetes-dashboard-v1.4.0" violates the naming scheme? 

I was trying to expose a pod on its host ip and got this:
```
kubectl expose pod "kubernetes-dashboard-v1.4.0-xikqe" --external-ip="10.245.1.3" --port=9090 --target-port=9090 --namespace=kube-system
The Service "kubernetes-dashboard-v1.4.0-xikqe" is invalid: metadata.name: Invalid value: "kubernetes-dashboard-v1.4.0-xikqe": must match the regex [a-z]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or 'abc-123')

```

this was with 1.4.0-beta.11

**Comment by janetkuo** [comment]
@vasu1124 Yes. Looks like in validation we prevent people from creating pods/services with invalid name, but not do the check in controllers.

**Comment by janetkuo** [comment]
After looking into this more, I found that pod/rc name needs to conform to subdomain in DNS (RFC 1123), whereas service name must conform to a label in DNS (RFC 1035). They're using different validation. 

@vasu1124 you can choose a different name for the service using `kubectl expose --name`

**Comment by vasu1124** [comment]
ah ok. got it. sorry for the confusion I created, but I guess others will also run into it. may i suggest to provide the "--name" information directly in the error message?

**Comment by pwittrock** [comment]
@vasu1124 Do you want to create a separate issue for your suggestion?
