### ISSUE TITLE
Disk layout on GCI is incompatible with Kubelet

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#33444]
On GCI, the (stateful) partition that kubelet has to monitor is mounted under `/var`. 
Kubelet considers `/` as the primary disk partition and tracks it as `nodefs`. 
It also tracks the partition under which docker is running which is `/var` in GCI and is referred to as `imagefs`.
In the case of GCI `/` seems to be a special partition (`/dev/root`) with limited storage. 

Why is this a problem?

Kubelet's summary API output needs to be carefully examined on GCI since it is different from that of the debian based containerVM. This issue can exist across distros, it is just that it is a behavioral difference in GCE and GKE.

Kubelet is configured to evict pods whenever nodefs availability drops to below 10%. Since on GCI, imagefs is the nodefs that we are going after, disk based evictions will not work with the current config. A simple work around is to update kubelet eviction config to evict based on `imagefs` availability too.

To fix this issue, kubelet should be reporting the stats of the stateful partition under `/var` as the `nodefs` and `imagefs` can be equal to `nodefs`. When this change is made, evictions based on `imagefs` must be removed.  

cc @dchen1107 @kubernetes/goog-image

**Comment by adityakali** [comment]
In general, I think kubelet should be more tolerant of multiple partitions since the layout may change in future (ex., /var/logs/ could be on a different partition than /var/lib/docker/).

**Comment by dchen1107** [comment]
Updating kubelet eviction config to evict based on imagefs availability on GKE or GCI for now sounds promising as a workaround for now. @vishh / @mtaufen Can you add a test to GCI test suite to validate this?

**Comment by vishh** [comment]
@dchen1107 the node e2e disk eviction tests are somehow passing. I tested my proposal manually before filing this issue and it works. 
This workaround needs some more lines of bash scripting though :unamused:

**Comment by vishh** [comment]
One more thing- this issue affects Kubelet's ability to report `OutOfDisk` condition as well. I assume we want to deprecate that condition though.

**Comment by yujuhong** [comment]
> In the case of GCI / seems to be a special partition (/dev/root) with limited storage.

Just FYI, Chromium OS maintains two partitions (mounted read-only) as root filesystem for autoupdate, and a stateful partition which is read-write. 
https://www.chromium.org/chromium-os/chromiumos-design-docs/filesystem-autoupdate

**Comment by dchen1107** [comment]
@dashpole Can I take this issue? Thanks!

**Comment by dashpole** [comment]
Just taking a couple notes regarding this issue:
Running on GCI (using overlayfs): we report the RootFs as: path: '/', device: '/dev/root', and ImageFs as: path: '/var/lib/docker', device: 'dev/sda1'
Running on Ubuntu Trusty (using devicemapper), we report the RootFs and ImageFs as: path: '/dev/disk/by-uuid/c303...edf9', and device: '/'

The desired behavior is that using overlayfs, the RootFs and ImageFs are the same (should both be on device: 'dev/sda1')
using devicemapper, the desired behavior is that RootFs is dev/sda1, and ImageFs uses its own device.

I will try more OS and drivers and see if I can find out why this is happening.

**Comment by vishh** [comment]
ImageFS is the filesystem under which docker image layers are stored. In
the case of overlayfs this can be a dedicated partition too. For example,
`/var/lib/docker` can be on a dedicated partition.

**Comment by dashpole** [comment]
It appears the only time that we report an incorrect NodeFs or ImageFs is when using GCI because we look first at "/", rather than "/var"

**Comment by dashpole** [comment]
@vishh This should be fixed now

**Comment by vishh** [comment]
Can we close this issue then?

**Comment by dashpole** [comment]
Sure.  I cant close it though...
