### ISSUE TITLE
Scheduler Extender changes to node array nodes []*api.Node, but ExtenderArgs still use NodeList

### ISSUE THREAD

**Issue by dsocer** [kubernetes/kubernetes#33458]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---scheduler extender; node array; NodeList

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.3.7

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): ubuntu 14.04
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**: Scheduler Extender changes to node array nodes []*api.Node, but ExtenderArgs still use NodeList, which will you use in the future.

**What you expected to happen**: Use the same parameter

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by resouer** [comment]
This is a issue that should be fixed!

**Comment by resouer** [comment]
This have to be a break change and backward compatibility effort will be much more than its benefits. Close.
