### ISSUE TITLE
Vagrant 1.8.5 and VSphere detection cause ssh Authentication to fail

### ISSUE THREAD

**Issue by intellix** [kubernetes/kubernetes#33452]
**Kubernetes version** (use `kubectl version`): master branch

**Environment**:
- **Cloud provider or hardware configuration**: Macbook Pro 15" Early 2013
- **OS** (e.g. from /etc/os-release): macOS Sierra 10.12
- **Kernel** (e.g. `uname -a`): Darwin Dominics-MBP-2.lan 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64
- **Install tools**: git
- **Others**:

**What happened**:
When you use the latest version of kubernetes (even in master branch) and Vagrant 1.8.5, insert_key is set to true and setup of master never works as it fails Authentication when SSHing into the box.

**What you expected to happen**:
insert_key to be false and master to correctly install within Vagrant 1.8.5

**How to reproduce it** (as minimally and precisely as possible):
- Install Vagrant 1.8.5
- Use these environment variables:

```
KUBE_ENABLE_INSECURE_REGISTRY=true
KUBERNETES_PROVIDER=vagrant
KUBERNETES_NODE_MEMORY=4096
KUBERNETES_MASTER_MEMORY=1536
```
- Run: `./cluster/kube-up.sh`

**Anything else do we need to know**:

I've had this issue for months now. I've had it happen on 2x Macbook pro machines and have completely given up attempting to install K8S via Vagrant until debugging further now. This has to be happening to everyone but have never seen it mentioned so am confused.

The problem is that insert_key doesn't properly get set to false as the VSphere setup overrides it.

**Comment by karimodm** [comment]
Can confirm that this is still a problem w/ release 1.0.1. Running on native Debian Linux, even tried with other distros.

**Comment by intellix** [comment]
Still a problem as in, my fix didn't work?

**Comment by kargakis** [comment]
@derekwaynecarr
