### ISSUE TITLE
Support native blue/green deployments

### ISSUE THREAD

**Issue by F21** [kubernetes/kubernetes#33462]
It would be really cool if kubernetes can have blue/green deployments built-in in addition to the rolling updates currently available.

This would allow for the ability to atomically update an app without the risk of clients connecting to the app seeing different versions.

**Comment by AdoHe** [comment]
@F21 would you mind give a more deep explanation? how would you expect this?

**Comment by F21** [comment]
Let's say we have an app deployed as version 1. If we ask kubernetes to perform a rolling update to version 2, my understanding is that v2 would be able to serve traffic before all of v1 is removed. That means that we will have a small window where v1 and v2 are both serving traffic.

With blue/green deployments, let's say we initially deployed v1 (blue). We then ask kubernetes to deploy v2 (green). However, v2 does not serve any traffic yet and kubernetes does not perform a rolling update. Instead, it leaves v1 alone and lets it continue serving, and deploys all instances of v2. It then uses health checks to check if all of v2 is healthy, and when it is ready, it cuts over all traffic to v2. At this point, it then deletes all instances of v1.

**Comment by luxas** [comment]
That would be a nice feature indeed. cc @kubernetes/deployment

**Comment by kargakis** [comment]
It would be easier to add another strategy natively once we have custom strategies and people cannot come up with custom BG easily on their own. https://github.com/kubernetes/kubernetes/issues/14510

**Comment by Haybu** [comment]
@kargakis does this suggest that BG is a strategy now is supported ? or it is still underway feature ?

**Comment by kargakis** [comment]
@Haybu no, BG is not supported natively and I am not sure this is going to happen anytime soon if at all in the core. We have a couple of issues for implementing custom strategies: https://github.com/kubernetes/kubernetes/issues/39337 https://github.com/kubernetes/kubernetes/issues/14510
You can also join Monday meetings of [sig-apps](https://github.com/kubernetes/community/tree/master/sig-apps) if you want to discuss this.

**Comment by woopstar** [comment]
For inspiration, we started to build our own BG deployment setup which is integrated into our bamboo deployment process.

Feel free to have a look at https://github.com/pasientskyhosting/kubernetes-blue-green-deploy

Please be aware this is still in beta.

**Comment by bgrant0607** [comment]
This is the domain of higher-level deployment pipelines and service meshes. It's not a deployment strategy that can be implemented in our workload APIs alone.

We're aware of the use case, but I'm going to close this as being out of scope here.
