### ISSUE TITLE
PetSet pet pods should resolve PTR records

### ISSUE THREAD

**Issue by TamalSaha** [kubernetes/kubernetes#33470]
We are trying to run a GlusterFS cluster in a 1.4 Kubernetes cluster using PetSet. We found that even though pod names create DNS record, no PTR record is created for pet pods. As a  result, we can't really use pod name as a GlusterFS peer name. Can PTR records be created for petset pods?

**Comment by harryge00** [comment]
We encountered the same problem when we tried to set up a hbase cluster.  Hbase regionServers will register themselves to a zookeeper Master through its hostname registered in ZooKeeper. So reverse DNS from Pod IP to pod's hostname is needed.

**Comment by TamalSaha** [comment]
cc: @smarterclayton @thockin

**Comment by smarterclayton** [comment]
You are expecting the pod IP to resolve back to the pet name as described on the endpoints struct?

**Comment by TamalSaha** [comment]
> You are expecting the pod IP to resolve back to the pet name as described on the endpoints struct?

Yes. If I ran `dig -x <pod-ip>`, I would like to see pod name in the answer section.

**Comment by thockin** [comment]
Why is reverse lookup needed?  Just because gluster  feels the need to do that, or for some actual reason?

**Comment by TamalSaha** [comment]
@thockin, this is a great question. I am not familiar with GlusterFS codebase. So, I am going to try to answer based on my research.

First, reverse DNS is mentioned as an essential for prod setups in GlusterFS docs. See "Other Notes" https://gluster.readthedocs.io/en/latest/Install-Guide/Common_criteria/#getting-started

In case you are unfamiliar with GlusterFs setup process, the way it works is first you run `glusterd` in a host. This creates a single node GlusterFS. Then you run `glusterd` in a second host. Now, you call `gluster peer probe <fqdn | ip>` from the first host. This will join both nodes into a single cluster. In GlusterFS there is no master server. So, each host maintains its list of peers.

If no reverse DNS is setup for the first host in the above example, then the second host uses the IP of first host as identifier in its peer list. But if reverse DNS is setup for the first host, then the second host uses the fqdn of first host as the identifier in its peer list. _It seems that GlusterFS uses reverse DNS to verify name of its peers._

@smarterclayton  PTR record for ip-of-host --> fqdn-of-host  (gluster-0.example.org)

I have tested both these cases in a test cluster in DigitalOcean.

Without stable identifier (fqdn), every time pod restarts, GlusterFS thinks it has completely lost a peer. So, we have to remove that record, add a new pod as peer and then run a full data recovery. If fqdn is used, then GlusterFS just auto heals the restarted pod by syncing any missing data. Given the total volume of data, the benefit of having a stable identifier (fqdn in this case) can be huge for GlusterFS.

**Comment by smarterclayton** [comment]
@wattsteve what's the heketi configuration going to do here w.r.t. gluster?  Is it still depending on host network and host name being stable?

**Comment by smarterclayton** [comment]
I'll bring the gluster guys in to give us an answer

**Comment by TamalSaha** [comment]
> I'll bring the gluster guys in to give us an answer

@smarterclayton, just an fyi, I have not tried heketi. I very recently found out that heketi is needed for dynamic provisioning.

**Comment by thockin** [comment]
I don't have a problem with reverse DNS for named headless (this specific case).  We just can't do reverse lookups for pods in general, unless we watch all pods...

**Comment by reAsOn2010** [comment]
@TamalSaha

I work with @harryge00 to eventually make our openTSDB cluster up and running in kubernetes with bare pod and headless service (without petset); and DNS is one of the major hiccups in the process. openTSDB cluster involves Zookeeper cluster, Hadoop cluster, Hbase Cluster and openTSDB itself. Particularly, Hbase relies on reverse DNS, see https://hbase.apache.org/book.html#trouble.rs.runtime.double_listed_regions.

We did the following:

1. All components are deployed via Pod, whose identities are managed manually. All pods have a corresponding headless service with the same name, so that an A record can be created for it. hbase-region-a.${NAMESPACE}.svc.cluster.local -> 192.168.65.5
	
	```
	ubuntu@sysinfra-1:~$ nslookup hbase-region-a.shaolei.svc.cluster.local 10.254.0.100
	Server:		10.254.0.100
	Address:	10.254.0.100#53
	
	Name:	hbase-region-a.shaolei.svc.cluster.local
	Address: 192.168.65.2
	```
    
2. Hack kubeDNS to have it add a PTR record for each headless service, (eg. 5.65.168.192.in-addr.arpa -> hbase-region-a.${NAMESPACE}.svc.cluster.local.)
	
	```
	ubuntu@sysinfra-1:~$ nslookup 192.168.65.2 10.254.0.100
	Server:		10.254.0.100
	Address:	10.254.0.100#53
	
	Non-authoritative answer:
	2.65.168.192.in-addr.arpa	name = hbase-region-a.shaolei.svc.cluster.local.
	
	Authoritative answers can be found from:
	```
	
3. Use script to set FQDN in container, so so running `hostname -f` in container will return FQDN
    
	```
	# set fqdn
	while true
	do
	    if grep --quiet $POD_NAME /etc/hosts; then
	        cat /etc/hosts | sed "s/$POD_NAME/${POD_NAME}.${POD_NAMESPACE}.svc.cluster.local $POD_NAME/g" > /etc/hosts.bak
	        cat /etc/hosts.bak > /etc/hosts
	        break
	    else
	        echo "waiting for /etc/hosts ready"
	        sleep 1
	    fi
	done
    ```
    
	```
	root@hbase-region-a:/opt/hbase# hostname -f
	hbase-region-a.shaolei.svc.cluster.local
	
	root@hbase-region-a:/opt/hbase# cat /etc/hosts
	# Kubernetes-managed hosts file.
	127.0.0.1	localhost
	::1	localhost ip6-localhost ip6-loopback
	fe00::0	ip6-localnet
	fe00::0	ip6-mcastprefix
	fe00::1	ip6-allnodes
	fe00::2	ip6-allrouters
	192.168.65.2	hbase-region-a.shaolei.svc.cluster.local hbase-region-a
	```
	
In a word, we manually fixed the DNS PTR record and container's FQDN, then the cluster is eventually ok.

So if we want to deploy the cluster with PetSet, these two problems should be resolved: DNS and FQDN.

**Comment by ddysher** [comment]
Changing kubedns to handle reverse lookup for just named headless service isn't too hard, two major points running on top of my head:

- maintaining headless service pods, especially when deleting pods can introduce some performance penalty if not handled properly
- at lease for the hbase case, FQDN should be available for pod while enabling PTR; so changing kubedns along won't solve the problem

**Comment by sadlil** [comment]
I can confirm kubernetes/dns#25 fixes the issue with glusterfs. 
`dig -x <ip>` resolves the fqdn and `gluster peer probe <fqdn>` resolves to the PTR records and resulting `<hostname>.<headlessServiceName>.<ns>.svc.cluster.local`.

In cause someone want to check things replacing the kubd-dns, here's the image: 
[appscode/k8s-dns-kube-dns-amd64:1.10.0-106-g0bb9f17](https://hub.docker.com/r/appscode/k8s-dns-kube-dns-amd64/tags/)

**Comment by TamalSaha** [comment]
PR is merged now. Closing. Thanks everyone!
