### ISSUE TITLE
Jenkins GCE Node e2e hanged as "Waiting for status to be reported".

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#33494]
From PR #33379.

Jenkins GCE Node e2e hanged after telling robot `ok to test`. Commented one more `test this please` restart the other tests, but did not help GCE Node e2e.

Is there any comment to restart GCE Node e2e test?

**Comment by MrHohn** [comment]
@apelisse @foxish

**Comment by foxish** [comment]
cc @kubernetes/test-infra-maintainers

**Comment by spxtr** [comment]
That one hasn't been switched to the new system yet. We will take care of that soon. In the meantime, note the aside in the comment:

> While we transition away from the Jenkins GitHub PR Builder plugin, "ok to test" commenters will need to be on the admin list defined in [this file](https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull.yaml).

**Comment by MrHohn** [comment]
Thanks for helping!
