### ISSUE TITLE
Include workqueue in client-go

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#33497]
[workqueue](https://github.com/kubernetes/kubernetes/tree/master/pkg/util/workqueue) is useful for building controllers. It should be included in client-go.

https://github.com/kubernetes/client-go/issues/4

**Comment by seh** [comment]
One annoyance is [file _metrics.go_](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/workqueue/metrics.go), which [drags in the Prometheus client library](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/workqueue/metrics.go#L22).

**Comment by caesarxuchao** [comment]
@krousey had done some work to not importing Prometheus: https://github.com/kubernetes/kubernetes/pull/30638. It would be appreciated if someone repeat the process for the workqueue's metrics.go.

**Comment by seh** [comment]
@caesarxuchao, is this inclusion something you expect to work on soon?
I need to decide whether I should wait on `workqueue` arriving in _client-go_, or whether I should continue working around its lack.

**Comment by caesarxuchao** [comment]
It will be two steps, removing the import of Prometheus and then including workqueue in client-go. I estimate the process will take 2 weeks.

**Comment by seh** [comment]
Thank you. I'll continue with my workaround (using `cache.FIFO`) for now, and watch for the chance to remove it when `workqueue` lands later.
