### ISSUE TITLE
EBS stuck detaching when volume controller detaches due to NodeNotReady pod eviction

### ISSUE THREAD

**Issue by jsravn** [kubernetes/kubernetes#33491]
1. kubelet was stopped on node with EBS mounted for a short period, to roll out some changes - node was marked as NotReady, then pods were evicted
2. controller manager thought it was safe to detach the EBS of the evicted pod - when it wasn't, because that EBS was still mounted
3. EBS then got stuck in "busy" state for hours, then finally got detached, then got stuck in "attaching" state for hours

conclusion: controller manager shouldn't be detaching EBS's when node gets NodeNotReady - I'm not sure how this happens yet, but I assume that pod eviction causes the VolumesInUse to be removed as well. _or_ if we want it to detach, it needs to force detach

**Comment by jsravn** [comment]
Raised for @justinsb

**Comment by jingxu97** [comment]
@jsravn could you please let us know if you still have this issue with later release? Thanks!

**Comment by jsravn** [comment]
@jingxu97 Yes I believe this is still a problem. I will try to double check on 1.4.8 today or tomorrow.

**Comment by jsravn** [comment]
I'm not sure yet how to fix this. The detaching is okay if that node is truly dead (it's turned off or terminated). It's not okay if just kubelet has stopped for a while (then EBS will get stuck).

**Comment by jsravn** [comment]
How does https://github.com/kubernetes/kubernetes/pull/35235 affect this? Since the pod is no longer force deleted, the EBS will not be detached correct? In which case, we can close this issue.

**Comment by msau42** [comment]
Is there still an issue? Can this be closed?

/sig storage

**Comment by jsravn** [comment]
I haven't seen this problem again, so happy to close.
