### ISSUE TITLE
K8s 1.4 and Docker 1.12 user namespace incompatibility 

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#33508]
Everything works fine when Docker user namespace is turned off. When it's turned on by some variant of this flag `--userns-remap=default` in Docker engine, pods can no longer be created. Resulting in error messages similar to the following in the kubelet log:

```
E0921 15:25:17.846090   11065 docker_manager.go:746] Logging security options: {key:seccomp value:unconfined msg:}
E0921 15:25:17.897647   11065 docker_manager.go:2250] container start failed: RunContainerError: runContainer: Error response from daemon: {"message":"oci runtime error: rootfs_linux.go:53: mounting \"/dev/termination-log\" to rootfs \"/var/lib/docker/231072.231072/devicemapper/mnt/3ee36ab9de3f11e2784ad043b296e902fb5caba5df25cad16f625e3b2dc50d4c/rootfs\" caused \"stat /var/lib/kubelet/pods/e01cd144-8002-11e6-97d8-080027afee78/containers/healthz/2a804743: permission denied\""}
E0921 15:25:17.897734   11065 pod_workers.go:184] Error syncing pod e01cd144-8002-11e6-97d8-080027afee78, skipping: [failed to "StartContainer" for "kubedns" with RunContainerError: "runContainer: Error response from daemon: {\"message\":\"oci runtime error: rootfs_linux.go:53: mounting \\\"/dev/termination-log\\\" to rootfs \\\"/var/lib/docker/231072.231072/devicemapper/mnt/83960f08fefb174c035e0c363e93c151ce0b871f1cea9860b499f1f91614e400/rootfs\\\" caused \\\"stat /var/lib/kubelet/pods/e01cd144-8002-11e6-97d8-080027afee78/containers/kubedns/439a15de: permission denied\\\"\"}"
, failed to "StartContainer" for "dnsmasq" with RunContainerError: "runContainer: Error response from daemon: {\"message\":\"oci runtime error: rootfs_linux.go:53: mounting \\\"/dev/termination-log\\\" to rootfs \\\"/var/lib/docker/231072.231072/devicemapper/mnt/89058c22c99f4b1c4fb058997192d9cbc971af8310542afa3769352a8050e985/rootfs\\\" caused \\\"stat /var/lib/kubelet/pods/e01cd144-8002-11e6-97d8-080027afee78/containers/dnsmasq/bcf2a79d: permission denied\\\"\"}"
, failed to "StartContainer" for "healthz" with RunContainerError: "runContainer: Error response from daemon: {\"message\":\"oci runtime error: rootfs_linux.go:53: mounting \\\"/dev/termination-log\\\" to rootfs \\\"/var/lib/docker/231072.231072/devicemapper/mnt/3ee36ab9de3f11e2784ad043b296e902fb5caba5df25cad16f625e3b2dc50d4c/rootfs\\\" caused \\\"stat /var/lib/kubelet/pods/e01cd144-8002-11e6-97d8-080027afee78/containers/healthz/2a804743: permission denied\\\"\"}"
]
```

Some investigation shows this is due to files in `/var/lib/kubelet/pods/...` being owned by `root` and having `0750` permission. When user namespace is turned on, the file used to bind mount into container's `/dev/termination-log` cannot be accessed by the remapped user, resulting in the permission denied error. 

Changing the permission of files/directories to `0755` allows the pods to be created successfully again, but `echo "test" > /dev/termination-log` within the container results in the permission denied problem again. Also is `0755` too open?

I'm wondering if it's worth submitting a PR to fix the problem above so users with Docker user namespace turned on could at least have basic things working, while we can engage the Docker community to have a more permanent fix?

**Comment by estesp** [comment]
Not enough knowledge of the pod structure personally to understand what are bind mounts versus container internal directories in the snippet above, but the assumption from docker engine (today) is that the intersection of external content (host paths & files) and user namespaced processes requires proactive admin actions re: `chown`/`chmod` of host-originated content appropriately where container process read/write perms are expected.

One possibly easy solution is a common host entry in `/etc/group` which includes the remapped root and the host-originating user of content/directories, where all content needed on both "sides" of the user ns boundary have g+rw perms.

We can revisit on the engine side if there are ways to support this better, but will require a clear understanding of the workflow and requirements.

**Comment by MikeSpreitzer** [comment]
Is this specific to Kubernetes 1.4, or does it also affect earlier releases?

**Comment by huang195** [comment]
@yujuhong @dchen1107 @vishh can you please share your thoughts on this issue and what might be a viable solution to have Kubernetes work with Docker user ns?

The several proposed solutions are:

- Change /var/lib/kubelet and its subdir's permission from 0750 to 0755 as a temporary workaround so at least pods can be created and started. My concerns are: i) 0755 might be too open, and ii) writing to /dev/termination-log inside of the container still results in permission denied error, unless we also `chown` the file on the host.

- For all directories and files that the kubelet created which are meant for the container's remapped user to access, it would perform the appropriate `chown / chmod` operations. My concern here is: Are there any other files/directories similarly to the termination log file that the kubelet implicitly mounts to user containers?

- Adding remapped root to `/etc/group` to allow remapped root to have similar-to-host-root privilege. My concern is if an attacker breaks out of his container, this setup might allow him to do much more damage to the host.

Can we go forward with any of these solutions or a variant of them? Or do you see other potential solutions?

**Comment by huang195** [comment]
Another interesting problem is normally kubelet and kube-proxy can run as containers on worker nodes, but with Docker userns enabled, this becomes problematic as they containers would need to be run in `--privileged` mode and `--network=host`, which are documented to be not compatible with userns enabled. This could be worked around by starting kubelet and kube-proxy as normal processes, but this would prevent a privileged pod from starting.

**Comment by vishh** [comment]
@pweil- has already attempted to fix this once in v1.4. AFAIK, he is working on a more systematic approach now.

**Comment by pweil-** [comment]
@huang195 as a summary, the initial effort for defaulting userns when detecting settings that would require host user ns is here: https://github.com/kubernetes/kubernetes/pull/31169.  In docker you may use host networking when using the host user namespace (ref https://github.com/docker/docker/pull/25771).

During testing to further explore issues I did run in to the permission problem you mentioned.  To continue testing I was able to run pods by ensuring the subgid was mapped to the root group.  Ie. change `/etc/subgid` to have `dockremap:0:65536`.  This is \*not\* a solution and only to help continue any R&D on remapping with Kube that you may be doing.

cc @mrunalp @smarterclayton

**Comment by huang195** [comment]
@vishh thanks for the heads up
@pweil- it's great that you're already working on a more comprehensive solution. Will take a look at the PR you've linked.

**Comment by yujuhong** [comment]
@pweil- , your PR ensures host user namespace is used whenever host volume is required (by [checking the hostPath in volumes](https://github.com/pweil-/kubernetes/blob/7eca3df501daa2e449053f8edf96500ba4676006/pkg/kubelet/kubelet_pods.go#L70)). This doesn't seem to cover per-pod directories such as secrets, emptyDir, and the terminationMessagePath` mentioned in this issue. How would those be handled?

**Comment by huang195** [comment]
@yujuhong I heard from @estesp that there was a recently merged Docker PR that would `chown` host files/directories to the remapped user if the host files/directories don't exist when bind mounting them into a container. This would resolve `emptyDir` and `terminationMessagePath`, if the kubelet would refrain from creating the corresponding files/directories on the host, since these are either empty directories or zero-length files. I'm not sure about secrets though.

**Comment by MikeSpreitzer** [comment]
Is the problem specific to Kubernetes 1.4, or does it also affect earlier releases?

**Comment by pweil-** [comment]
> Is the problem specific to Kubernetes 1.4, or does it also affect earlier releases?

not specific to 1.4

**Comment by The-Loeki** [comment]
It still exists in 1.7 unfortunately... It's too bad, because this is one of the better security improvements in Docker IMHO

**Comment by The-Loeki** [comment]
As a bit of additional information, since the User Remap is supposed to remap container `root` to a remapped userID (`cat /etc/subuid`) I just chowned the entire pods dir to see what would happen. 

This seemed to work pretty good, but some files are still owned by root and I still have the dreaded `stat ... pemission denied`

**Comment by The-Loeki** [comment]
Apparently there's a feature req going on here: https://github.com/kubernetes/features/issues/127

**Comment by The-Loeki** [comment]
Apparently there's a feature req going on here: https://github.com/kubernetes/features/issues/127

**Comment by adelton** [comment]
I've now filed https://github.com/kubernetes/kubernetes/pull/55707 which exposes (and requires) explicit options specifying what the uid/gid for root's content (in the container) would be, matching what you have configured for docker, and then does the chown on `/var/lib/kubelet/` subdirectories. If you are able to compile Kubernetes, can you give it a try?
