### ISSUE TITLE
Define Release Workflow

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#33515]
Come up with workflow for release
- Requirements for release
  - Issues state
  - Automated Testing state
  - Manual Testing state
- How to add / modify release requirements
  - Adding automated tests as release blockers
- Deadlines for milestones
  - Moving feature issues out of the release milestone
  - Where docs are submitted
-  Automated nagging around milestones

**Comment by dims** [comment]
@saad-ali : what say you? :) move this to 1.6?

**Comment by saad-ali** [comment]
Yep, we document the release process. But it is not a blocker for the 1.5.

**Comment by goltermann** [comment]
Sounds like a good idea.  Recommend you amend https://github.com/kubernetes/community/wiki/Life-of-a-Kubernetes-Release, instead of a new doc/location.

**Comment by bgrant0607** [comment]
I agree with @goltermann. We're also in the process of moving docs/{devel,proposals,design} out of this repo.

Related docs:
https://github.com/kubernetes/kubernetes/blob/master/docs/design/versioning.md
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/update-release-docs.md
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/how-to-doc.md
