### ISSUE TITLE
Daemonset delete fails

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kubernetes#33517]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):  yes, but there seems to be a bug

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
## kubernetes delete daemonset fails

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:45:16Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:38:31Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- **Kernel** (e.g. `uname -a`): Linux ip-172-20-105-42 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
- **Install tools**: kops
- **Others**:

**What happened**:
I have ingress running as a daemonset, looking for a nodeSelector:

```
      nodeSelector:
        roles.kubernetes.io/node: "1"
```

I am updating it to have a TCP services config map, so I needed to delete the daemonset first.
Ran: `kubectl delete ds nginx-ingress-controller --namespace=kube-system`
And waited.

Eventually, it failed with `error: timed out waiting for the condition`

But `kubectl get pods --namespace=kube-system -w` shows that the pods are being terminated, and then being recreated.

**What you expected to happen**:
All pods and the daemonset should be deleted.

**How to reproduce it** (as minimally and precisely as possible):
I have no idea.

**Anything else do we need to know**:
Not sure.

**Comment by zapman449** [comment]
The way I resolved this issue was very unsatisfactory: the AWS ASG for the worker nodes was reduced to zero nodes.  Then I was able to delete the daemonset.  Then I brought the nodes back (set the right ASG size again).  Then I was able to redeploy the daemonset.

**Comment by zapman449** [comment]
also 'kubectl delete ds <blah> --cascade=false` was able to help me later through this issue.

**Comment by bronhaim** [comment]
Facing the same issue as well running daemonSet definition. The --cascade=false helped as well. Consider to re-open the issue
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by fabiand** [comment]
Can we reopen this issue according to the previous comment?

**Comment by smarterclayton** [comment]
@bronhaim can you add more details about your recreation?

**Comment by bronhaim** [comment]
@smarterclayton I'm running the following yaml definition [1] with kubectl --create. once trying to delete the ds I get "error: timed out waiting for the condition", strace shows it waits with wait probably for the pods to stop. Adding --cascade=0 just deletes it quickly. Then I clean the pods and I'm free to move on.
[1] https://gerrit.ovirt.org/#/c/67618/9/ovirt-node-docker/manifests/ovirt-node.yaml
