### ISSUE TITLE
Replication controller with nodeSelctor conditional doesn't succeed if nodes are labeled after it is submitted

### ISSUE THREAD

**Issue by zilman** [kubernetes/kubernetes#33522]
Kubenetes version 1.4.

Replication controller YAML contains:

```
spec:
   nodeSelector:
      foo: bar
   containers:
```

kubectl create -f above file.

Realize you've forgotten to label nodes or have a typeo, do:

```
kubectl label nodes <nodename> foo=bar
```

**Expected**:
rc to notice newly matching nodes and proceed. 

**What happened**:
rc did not proceed.

**Work around**:
kubectl delete -f above file and create again, proceeds immediately.

**Comment by janetkuo** [comment]
@zilman did you mean replication controller or deployment?

**Comment by zilman** [comment]
@janetkuo sorry about faffing up the terminology there. I meant a replication controller.

**Comment by xiangpengzhao** [comment]
@zilman Can you see any pending pods after `kubectl create`? If so, this might be a scheduling issue.
@davidopp @k82cn

**Comment by k82cn** [comment]
The selector will only work when "scheduling". If the selector was updated after Pod running, it will not impact running pods.

> Work around:
> kubectl delete -f above file and create again, proceeds immediately.

So I think this is expected behavior; rescheduler maybe one of solution for this, but it not released/updated yet.

**Comment by davidopp** [comment]
> The selector will only work when "scheduling". If the selector was updated after Pod running, it will not impact running pods.

I think the question was about updating the node label, not the pod selector.

Updating the node label while the pod (that has a nodeSelector for that node label) is pending should work and allow the pod to schedule.

@bsalamat Can you try to reproduce this problem?

**Comment by k82cn** [comment]
> I think the question was about updating the node label, not the pod selector.

Sorry, I mean node label; update node label will not impact running pods, AFAIK :).

**Comment by davidopp** [comment]
> Sorry, I mean node label; update node label will not impact running pods, AFAIK :).

That's a bug if it doesn't. When the scheduler used to continuously evaluate every pending pod on every node, it should have worked. I'm not sure if recent changes affected it. Would be good for someone to test.

**Comment by xiangpengzhao** [comment]
Updating node label will impact pending pods but will not impact running pods, right? I remembered that the pending pods will become running if node label updates to match the selector when I worked on fixing another issue.

**Comment by davidopp** [comment]
Sorry, I mis-read.

It should impact pending pods, not running pods.

The scenario in the first entry in this issue appears to be
1. user creates pod (via ReplicaSet) with nodeSelector that is not matched by any node
2. pod goes pending
3. user updates node label to match nodeSelector
4. pod stays pending

The correct behavior in (4) is pod should schedule.

But nobody has verified/reproduced this bug report. Can someone do it?

**Comment by xiangpengzhao** [comment]
I will do later.

**Comment by k82cn** [comment]
Tested with the latest codes (1.7), it works as expected. let me try 1.4 :).

**Comment by xiangpengzhao** [comment]
Thanks @k82cn ! I left office for some time after last comment and didn't have a chance to verify the issue. Sorry about this.

**Comment by xiangpengzhao** [comment]
I tried on v1.4.0, it also works as expected. After updating node label, pending pods become running about 10+ seconds later.

```
#kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
#kubectl get rc
NAME       DESIRED   CURRENT   READY     AGE
rc-nginx   2         2         0         10s
# 
#kubectl get po -o wide
NAME             READY     STATUS    RESTARTS   AGE       IP        NODE
rc-nginx-5xkfj   0/1       Pending   0          16s       <none>    
rc-nginx-xc2kb   0/1       Pending   0          16s       <none>    
# 
#kubectl label node 192.168.1.220 foo=bar
node "192.168.1.220" labeled
# 
#kubectl get po -o wide
NAME             READY     STATUS    RESTARTS   AGE       IP        NODE
rc-nginx-xc2kb   1/1       Running   0         2m        172.17.0.4   192.168.1.220
rc-nginx-5xkfj   1/1       Running   0         2m        172.17.0.3   192.168.1.220
# 
#kubectl describe node 192.168.1.220
Name:			192.168.1.220
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/os=linux
			foo=bar
			kubernetes.io/hostname=192.168.1.220
```

cc @davidopp @k82cn

**Comment by bsalamat** [comment]
Thanks, @xiangpengzhao and @k82cn for trying the scenario and verifying that the system works as expected.

@zilman Given that your last update on this issue is over 7 months old, please let us know if you are still seeing the issue.

**Comment by kargakis** [comment]
Please reopen if it's still an issue
