### ISSUE TITLE
kubelet.makeMounts() is mixing the usage of the kubecontainer.Mount.Name

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#33526]
[kubelet.makeMounts](https://github.com/kubernetes/kubernetes/blob/v1.5.0-alpha.0/pkg/kubelet/kubelet.go#L1207) is a help function that runs during each container creation.
It takes a **pod spec**, and a **container spec** to generate **kubecontainer.Mount (name, container-path, host-path, readonly, selinux_relabel)** by matching the container spec's [volume mount](https://github.com/kubernetes/kubernetes/blob/v1.5.0-alpha.0/pkg/api/types.go#L882-L893) to the pod spec's [volumes](https://github.com/kubernetes/kubernetes/blob/v1.5.0-alpha.0/pkg/api/types.go#L172-L181).

But meanwhile, it's also generating arbitrary **kubecontainer.Mount** that has no corresponding volumes in the pod spec, such as [mounting host machine's /etc/hosts](https://github.com/kubernetes/kubernetes/blob/v1.5.0-alpha.0/pkg/kubelet/kubelet.go#L1247-L1252).

Thus when runtime tries to look for the volumes by the volume name in the [interface](https://github.com/kubernetes/kubernetes/blob/v1.5.0-alpha.0/pkg/kubelet/api/v1alpha1/runtime/api.proto#L104), it cannot find any volumes.

Another issue is if container spec defines a `subPath` in the volume mount, then we will end up with two **kubecontainer.Mount** that have same names, same container paths, but different host paths. This is not supported by rkt as one volume name should map to one host path.

So the action required here is:
**Option 1**: Generate correct volumes for these arbitrary mounts and subpath mounts, and pass them through `PodSandboxConfig` during the creation of the sandbox. Later it passes the runtime the mounts object (volume_name, container_path), and runtime is able to do the correct mounts by finding the volumes through names.

This implies the mounts for each apps within the sand box must have a pre-established volumes.

**Option 2**: Remove the mount name, or at least change that to not be the volume name. Require runtime to support mounting any **container-path:host-path** pairs, basically requires runtime to **know nothing about volumes**

cc @yujuhong @feiskyer @euank @alban @lucab @jonboulle

**Comment by yifan-gu** [comment]
cc @kubernetes/sig-node @kubernetes/sig-rktnetes

**Comment by jonboulle** [comment]
Volumes don't exist at all in the CRI API at the moment, which suggests that 2 is already the implicit path?

**Comment by yifan-gu** [comment]
@jonboulle Yes, the current docker implementation is the path 2. And according to @squeed https://github.com/coreos/rkt/pull/3239#issuecomment-249818386 , it will will be doable by rkt soon. So I guess the action we need to do is to clean up the `kubecontainer.Mount.Name`, either remove it, or make it unique for each container-path:host-path pair.

**Comment by pmorie** [comment]
For the record, I would also like `makeMounts` to make the mountpoints for container termination logs.

**Comment by yifan-gu** [comment]
@pmorie Exactly!

**Comment by yujuhong** [comment]
> For the record, I would also like makeMounts to make the mountpoints for container termination logs.

I have no objection to that.

**Comment by yifan-gu** [comment]
@pmorie @yujuhong Actually the `makeMounts()` in [kuberuntime_container.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_container.go#L245) already makes the mount point for the termination log. What we need to do is removing  the `makeMounts()` in [kubelet_pods.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L78).

It should be in part of the whole removing `pkg/kubelet/container/runtime.go` work once docker is fully migrated to CRI.
