### ISSUE TITLE
k8s client sends odd useragent

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#33532]
While using the k8s client in my own code, I noticed that the UserAgent was odd: `User-Agent: dns-controller/v0.0.0 (linux/amd64) kubernetes/$Format`

I think we should either pre-bake a k8s version into the Foramt string as part of client-go, or we should document the expected variable substitutions.  (I wasn't using client-go here, I was using the main repo, but I believe the same problem exists)

cf https://github.com/kubernetes/client-go/blob/master/1.4/pkg/version/base.go#L45-L56

**Comment by dixudx** [comment]
@caesarxuchao Seems we does not bump a version for `client-go`.
