### ISSUE TITLE
Consistent tagging & tainting for masters

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#33530]
We need to agree two things that can cross-cut the various installation approaches/tools:
- a taint for master nodes (so pods can tolerate it) 
- a label for master nodes (so pods can select only master nodes).

For the toleration, the recommendation seems to be `dedicated=master:NoSchedule`

For the label, I propose `kubernetes.io/role=master`.

In the absence of a `--taints` kubelet flag (that would behave like `--labels`) in 1.4, I'm going to try a controller which detects the `kubernetes.io/role=master` label, removes the `unschedulable: true` and applies the taint.

cc @philips for kube-aws, @zmerlynn for kube-up, @mikedanese for kubeadm / `--taints` flag

**Comment by errordeveloper** [comment]
Currently `kubeadm` uses label `kubeadm.alpha.kubernetes.io/rolemaster` and taint `dedicated=master:NoSchedule`.

**Comment by errordeveloper** [comment]
Also, we have `CriticalAddonsOnly` taint key in `/cluster`, and I pretty sure it's a red herring.

**Comment by emalloy** [comment]
I am wondering, what the current behavior is if only `Taints:  dedicated=master:NoSchedule` is set, and  SchedulingDisabled is not set.

Recently I upgraded a cluster instantiated by kops from 1.4.3 -> 1.4.6, ,

then SchedulingDisabled status for the masters disappeared.

I then noticed that all nodes (masters+nodes) were now in the ELB pool.

I have to do some code sifting to see how nodes are selected for adding to the ELB instance pool.

**Comment by caseydavenport** [comment]
As per this issue: https://github.com/kubernetes/kubernetes/issues/36272

We should _not_ be using `key: dedicated` for taints/tolerations.

**Comment by jbeda** [comment]
See also #39112.  We should make sure the label scheme allows for masters to be workers too.

**Comment by kargakis** [comment]
> As per this issue: #36272
> 
> We should not be using key: dedicated for taints/tolerations and we should use node.alpha.kubernetes.io/role instead.

@justinsb can you update the initial post with the imput from #36272? Or agree with @davidopp on what's the "correct" thing to do here?

**Comment by philips** [comment]
@jbeda @justinsb #39112 is getting bogged down in whether or not these labels are API. I think we should all agree on the label being as described in #39112 and keep moving and then I will work on documenting the namespace in https://github.com/kubernetes/community/issues/300

**Comment by luxas** [comment]
@justinsb @philips @jbeda Anything more to do here?

**Comment by justinsb** [comment]
I think we're done :-)  Would be nice if the annotations were in the more discoverable place, but that is quite literally another issue!
