### ISSUE TITLE
 http2: no cached connection was available

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#33557]
I started seeing this happening again in our scalability tests:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/load.go:206 creating rc load-small-rc-980 Expected error: <*errors.errorString | 0xc8356375b0>: { s: "Error creating replication controller: Post https://130.211.190.51/api/v1/namespaces/e2e-tests-load-30-nodepods-1-w02t6/replicationcontrollers: http2: no cached connection was available", } Error creating replication controller: Post https://130.211.190.51/api/v1/namespaces/e2e-tests-load-30-nodepods-1-w02t6/replicationcontrollers: http2: no cached connection was available not to have occurred /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/load.go:306
```

Coming from 500-node kubemark:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-kubemark-500-gce/6224/

[It's not very frequent, but it's happening]

@timothysc 
@kubernetes/sig-scalability

**Comment by wojtek-t** [comment]
@gmarek - FYI

**Comment by gmarek** [comment]
I'm going to try running 5k experiment to see where we fail first. I'll look for this error.

**Comment by timothysc** [comment]
This seems like a bug in the api-machinery or client tooling.. that error statement makes no sense b/c the connection(s) should be shared.   Unless it's how we're using the client tools in this test...

**Comment by wojtek-t** [comment]
It's definitely possible that we are using connections incorrectly in test. But if so, this needs to be fixed. [I don't know what is the reason here.]

**Comment by timothysc** [comment]
This sounds eerily similar - https://github.com/golang/go/issues/16582 . Is there a count of the number of concurrent clients?  

Also I'll need to figure out the default max number of streams.  
/cc @bradfitz

**Comment by timothysc** [comment]
Hmm looks like 1000 is the default from what I grok, but that appears on the client side.

**Comment by bradfitz** [comment]
Yeah, looks like golang/go#16582.

@timothysc, where do you see 1000? The threshold at which this client-side bug occurs is a function of the MAX_CONCURRENT_STREAMS advertised by the server and how many outstanding HTTP requests are in flight on that connection.

**Comment by timothysc** [comment]
nvmd: https://godoc.org/golang.org/x/net/http2 I see - 

// If zero, MaxConcurrentStreams defaults to at least 100, per
// the HTTP/2 spec's recommendations.
MaxConcurrentStreams uint32

**Comment by bradfitz** [comment]
Yeah, that is unrelated to this bug. That is a Go http server knob. This bug concerns the Go http client.

**Comment by timothysc** [comment]
It looks like in this use case, there is unbounded concurrency in the tests. 

The server is running with the default of 100 (per), and the client is reporting the error mentioned because it's bumping into the threshold.  So at this point I see two options.  

- up the server defaults :-/
- prevent the tests from doing too many concurrent operations across a single client. 

It would also be helpful if the error denoted stream thresholds.

**Comment by bradfitz** [comment]
The error was never meant to be shown to users. It was an internal sentinel error value which escaped and shipped by accident.

The fix in https://github.com/golang/go/commit/7a622740655bb5fcbd160eb96887032314842e6e "fixes" by just making new TCP connections as needed, like to HTTP/1.  An outstanding bug is optionally capping that, so Go doesn't bombard a server with a million TCP connections when there's unbounded concurrency.

I think your best bet (short term and long term) is bounding the concurrency in your test, even if it's a high bound.

**Comment by wojtek-t** [comment]
@bradfitz - thanks for comments. So I have one more question. Assuming that we create few different clients in the test, will it also fix the problem?

To be honest, I wouldn't like to change the concurrency in test. However, introducing multiple clients in the test, (so that not all requests are being send from the same one) seems perfectly fine - it would probably simulate more what users are actually doing.

Thoughts?

**Comment by gmarek** [comment]
Yeah - we theoretically create thousands connections in the like @timothysc mentioned. I'll change it to work queue tomorrow.

**Comment by wojtek-t** [comment]
@gmarek - I'm not sure we should change it to workqueue. Maybe using multiple client would also fix the issue.

**Comment by gmarek** [comment]
We're creating ~7000 go routines there for the 2k Node cluster - I think it's way to many.

**Comment by wojtek-t** [comment]
since most of them are sleeping, I don't think it's too much.

**Comment by wojtek-t** [comment]
In other words - there should only be constant number of active go-routines at any point in time.

That said - I think that having multiple clients would be a better solution (if that would also solve the problem). @bradfitz - would it?

**Comment by timothysc** [comment]
+1 to more clients, b/c that is much more realistic test.  

Also, it "sounds like" this will be fixed in future versions of the library with some caveats on configuration.

**Comment by gmarek** [comment]
OK, I can create more clients as well. How many go routines per client would make a realistic configuration?

**Comment by timothysc** [comment]
@gmarek tough question.. depends on the client.  Some web-UI clients can be pretty heavy I think I've seen ~70 per/client on some of our tests.

**Comment by gmarek** [comment]
OK, I'll do a 100 to make math easier;)

**Comment by bradfitz** [comment]
> +1 to more clients, b/c that is much more realistic test.

If the test is simulating load from many nodes, yes: you should have each goroutine use its own http.Transport so they have their own connection pool (for http2: pool = 1 connection per host, usually)

> Also, it "sounds like" this will be fixed in future versions of the library with some caveats on configuration.

Yes, it's fixed at tip. It'll be in Go 1.8. No plans to backport it to Go 1.7.x currently, but I suppose we could.

**Comment by wojtek-t** [comment]
Yeah - the conclusions here is something I wanted to have exactly.

I'm not sure about 100 value, though changing this particular one should be super simple in the future.

**Comment by wojtek-t** [comment]
Or to be more specific about implementation I think we should:
- have N clients (an array of them)
- a go-routine responsible for R number i, should be using client[i % N]

**Comment by wojtek-t** [comment]
I'm working on https://github.com/kubernetes/kubernetes/pull/33733 to fix it.

The problem is that in k8s we are sharing underlying transport between different clients, so I have to workaround it somehow.

**Comment by timothysc** [comment]
If you're tests are green, can we close this issue?

**Comment by wojtek-t** [comment]
Well - I'm not 100% it will fix the problem - I would like to wait for few days. But I'm fine with reassigning it to me.

**Comment by wojtek-t** [comment]
OK - it seems that we have successful 2000-node kubemark run (and a bunch of kubemark-500 runs) so I think this is now fixed. Will reopen if we will face this again.

Thans a lot for help with it!
