### ISSUE TITLE
flake: Data race in federation/pkg/federation-controller/replicaset unit test

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#33558]
from https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/32129/kubernetes-pull-test-unit-integration/46691/:

```
=== RUN   TestReplicaSetController
[...]

WARNING: DATA RACE
Read by goroutine 50:
  k8s.io/kubernetes/federation/pkg/federation-controller/replicaset.(*ReplicaSetController).reconcileReplicaSet()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/replicaset/replicasetcontroller.go:499 +0x22d8
  k8s.io/kubernetes/federation/pkg/federation-controller/replicaset.(*ReplicaSetController).worker()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/replicaset/replicasetcontroller.go:324 +0x122
  k8s.io/kubernetes/federation/pkg/federation-controller/replicaset.(*ReplicaSetController).(k8s.io/kubernetes/federation/pkg/federation-controller/replicaset.worker)-fm()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/replicaset/replicasetcontroller.go:221 +0x2d
  k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:84 +0x2a
  k8s.io/kubernetes/pkg/util/wait.JitterUntil()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:85 +0xc9
  k8s.io/kubernetes/pkg/util/wait.Until()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x50

Previous write by goroutine 21:
  k8s.io/kubernetes/federation/pkg/federation-controller/replicaset.TestReplicaSetController()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/replicaset/replicasetcontroller_test.go:133 +0x2ccb
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:473 +0xdc

Goroutine 50 (running) created at:
  k8s.io/kubernetes/federation/pkg/federation-controller/replicaset.(*ReplicaSetController).Run()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/replicaset/replicasetcontroller.go:221 +0x2ea

Goroutine 21 (running) created at:
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:582 +0xae2
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:515 +0x11d
  main.main()
      k8s.io/kubernetes/federation/pkg/federation-controller/replicaset/_test/_testmain.go:58 +0x210
```

**Comment by jlowdermilk** [comment]
Similar failure in federation/pkg/federation-controller/ingress

=== RUN   TestIngressController
==================
WARNING: DATA RACE
Write by goroutine 39:
  runtime.closechan()
      /usr/local/go/src/runtime/chan.go:292 +0x0
  k8s.io/kubernetes/pkg/watch.(*FakeWatcher).Stop()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/watch/watch.go:106 +0x102
  k8s.io/kubernetes/pkg/client/cache.(*Reflector).watchHandler()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:359 +0x1e4
  k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:328 +0x1abf
  k8s.io/kubernetes/pkg/client/cache.(*Reflector).RunUntil.func1()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:213 +0x36
  k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:84 +0x2a
  k8s.io/kubernetes/pkg/util/wait.JitterUntil()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:85 +0xc9
  k8s.io/kubernetes/pkg/util/wait.Until()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x50

Previous read by goroutine 17:
  runtime.chansend()
      /usr/local/go/src/runtime/chan.go:115 +0x0
  k8s.io/kubernetes/federation/pkg/federation-controller/util/test.(*WatcherDispatcher).Modify()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/util/test/test_helper.go:82 +0x6e6
  k8s.io/kubernetes/federation/pkg/federation-controller/ingress.TestIngressController()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/ingress/ingress_controller_test.go:133 +0x2f63
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:473 +0xdc

Goroutine 39 (running) created at:
  k8s.io/kubernetes/pkg/client/cache.(*Reflector).RunUntil()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:216 +0x352
  k8s.io/kubernetes/pkg/client/cache.(*Controller).Run()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/controller.go:100 +0x200

Goroutine 17 (running) created at:
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:582 +0xae2
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:515 +0x11d
  main.main()
      k8s.io/kubernetes/federation/pkg/federation-controller/ingress/_test/_testmain.go:54 +0x210
==================
--- PASS: TestIngressController (1.04s)
	ingress_controller_test.go:47: Creating fake infrastructure
	ingress_controller_test.go:94: Running Ingress Controller
	ingress_controller_test.go:110: Adding cluster 1
	ingress_controller_test.go:113: Adding Ingress UID ConfigMap to cluster 1
	ingress_controller_test.go:116: Checking that UID annotation on Cluster 1 annotation was correctly updated
	ingress_controller_test.go:122: Adding Federated Ingress
	ingress_controller_test.go:124: Checking that Ingress was correctly created in cluster 1
	ingress_controller_test.go:131: Checking that IP address gets transferred from cluster ingress to federated ingress
	ingress_controller_test.go:145: Modifying Federated Ingress
	ingress_controller_test.go:147: Checking that Ingress was correctly updated in cluster 1
	ingress_controller_test.go:153: Adding a second cluster
	ingress_controller_test.go:161: Checking that the ingress got created in cluster 2
	ingress_controller_test.go:167: Checking that the configmap in cluster 2 got updated.
PASS
Found 1 data race(s)
FAIL	k8s.io/kubernetes/federation/pkg/federation-controller/ingress	3.051s

**Comment by nikhiljindal** [comment]
Closing as this has not been reported again since October
