### ISSUE TITLE
Implement federated deployment

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#33591]
This issue is to track the work required to implement deployment in federation control plane.

Work required is:
- [ ] Finalize the design
- [ ] Implement the API changes
- [ ] Implement federation deployment controller
- [ ] Add e2e tests
- [ ] Add documentation

cc @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
Design document: https://docs.google.com/document/d/1Vi_CKah8oR5ByPp8BlgUD0SoINMD1SE0iMQf_2BKlpw

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @nikhiljindal @mwielgus

**Comment by quinton-hoole** [comment]
This is done.

**Comment by dims** [comment]
@quinton-hoole cool. i'll close this out.
