### ISSUE TITLE
Issue when using kubeadm with multiple network interfaces

### ISSUE THREAD

**Issue by hgfischer** [kubernetes/kubernetes#33618]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): fialed 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: local VirtualBox machines managed with Vagrant
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04 (both host and VMs)
- **Kernel** (e.g. `uname -a`): Linux kubenode01 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubeadm
- **Others**: Vagrant

**What happened**: I'm testing a Kubernetes cluster with VirtualBox and Vagrant. Every VM has an NATed interface (eth0) and a Host-Only interface (eth1). I wanted to make the first node try to join the master using the Host-Only IP address because Kubernetes is listening on all interfaces by default.

**What you expected to happen**: Since the master is listening to all interfaces available, I was expecting it to just work.

**How to reproduce it** (as minimally and precisely as possible): Setup two VMs, with one NATed interface, and one Host-Only interface. Follow steps from http://kubernetes.io/docs/getting-started-guides/kubeadm/ but instead of using exactly the `kubeadm join ...` command-line returned by the master, change the IP address to the one of the Host-Only interface.

**Anything else do we need to know**: You can use this to reproduce the issue: https://github.com/hgfischer/Kubernetes14

**Comment by luxas** [comment]
No, kubernetes isn't listening to all interfaces by default. It picks the interface with the default gateway and listens to that. Use `--api-advertise-addresses=<the eth1 ip addr>` on `kubeadm init` in order to use the host-only interface.

cc @kubernetes/sig-cluster-lifecycle

**Comment by errordeveloper** [comment]
To be clear, it does actually listen on all interfaces right now and we are planing to provide a flag to make it bind to a specific address, but default will probably remain `0.0.0.0` for now. Please also see https://github.com/kubernetes/kubernetes/issues/33562#issuecomment-250105700 and https://github.com/kubernetes/kubernetes/issues/33638.

**Comment by lukemarsden** [comment]
Should be fixed in http://kubernetes.io/docs/getting-started-guides/kubeadm/#instructions now, @hgfischer could you please take a look and let me know if that docs change would have helped you out? Thanks!

**Comment by danielschonfeld** [comment]
What about the nodes themselves, why don't they have a flag to pass on to kubelet the `--address` flag?  I have a bare metal installation with two ethernet devices, it just so happens to be that my internal network doesn't have the gateway on it.  When installing weave-net the IP used to communicate between nodes ends up becoming my external IP and not the internal one.

Thanks!

**Comment by lukemarsden** [comment]
Hey @danielschonfeld could you please open a ticket against https://github.com/weaveworks/weave-kube for the latter issue? I'll ask my colleagues to take a look. Thanks!

**Comment by danielschonfeld** [comment]
@lukemarsden it's not a weave issue... weave only runs `kube-peers` which collects the advertised address from each node record from the API server.  It's the kubelet on the individual nodes that does exactly what you described above.  It takes the first IP with a gateway it finds and in my installation it just so happens to be that the first IP is the external one and not the internal one (cuz our internal network at our datacenter provider is with an unmanaged switch, meaning no gateway)

**Comment by errordeveloper** [comment]
Ok, I see what's the problem. Node registration IP is outside of kubeadm.
Right now you will need to either add kubelet system drop-in unit, or
modify the one kubeadm install. Do know how to do this or you need more
details?

**Comment by danielschonfeld** [comment]
@errordeveloper i'll need some details for the latter option.  the former i'm familiar with, but i kinda like the latter idea better.  Thank you!

**Comment by errordeveloper** [comment]
The Debian and RPM packages of kubeadm install a drop-in under
/etc/systemd/system/kubelet.service.d/10-kubeadm.conf, it has kubelet flags
needed for kubeadm to work. The file is the same on nodes and master. You
need to add a flag to this (IIRC --overide-external-hostname) and pass the
IP or hostname that you want, but check kubelet docs.

**Comment by danielschonfeld** [comment]
@errordeveloper thank you!! i'll go tinker with it and report back if I run into trouble

**Comment by luxas** [comment]
@danielschonfeld The kubelet flag you should set is `--hostname-override`

**Comment by luxas** [comment]
@lukemarsden We should document this as well

**Comment by danielschonfeld** [comment]
@luxas why is it `--hostname-override` and not `--address` ?

**Comment by luxas** [comment]
It's a kubelet behaviour, not a kubeadm one. 
The default name of the kubelet equals the hostname, and the kubelet ip address defaults to the ip of the interface that's the default gateway.

You can override both of these values by specifying `--hostname-override` to the kubelet.

**Comment by danielschonfeld** [comment]
oh i see, where address would only control what it listens to but not change the node IP?

**Comment by luxas** [comment]
Correct. 
Address (127.0.0.1 or 0.0.0.0) would only control if the kubelet exposes `10250` (which it should)

**Comment by hgfischer** [comment]
Hey, `--api-advertise-addresses` works like a charm. Thanks guys!

**Comment by mikedanese** [comment]
@hgfischer reopened on accident?

**Comment by errordeveloper** [comment]
@luxas yes, we should make sure to make it easy to find the answer to this. Would like to add this to the docs? Also, I think we should ideally document it using another drop-in, it's more user-friendly and error-prone, as you don't need to use sed and or anything.

**Comment by luxas** [comment]
I have a lot (too much) to do right now, so I'd appreciate if someone else would add it to the docs :)
Regarding dropins; it's quite a hard thing to solve in a right way. Maybe you could add that to the next week's agenda?

**Comment by errordeveloper** [comment]
@luxas I mean we don't have to solve it as such, just document it using a drop-in and not sed or anything hacky.

**Comment by errordeveloper** [comment]
I guess that I should just document it myself.

**Comment by errordeveloper** [comment]
Just for the record, before I open the docs PR, this is what I'd recommend:
```
printf '[Service]\nEnvironment="KUBELET_EXTRA_ARGS=--hostname-override=%s"\n' 10.0.0.20 > /etc/systemd/system/kubelet.service.d/15-hostname-override.conf
```

**Comment by errordeveloper** [comment]
@danielschonfeld  have you tested this already or not yet?

**Comment by danielschonfeld** [comment]
Not yet. Trying to figure out a way to script the retrieval of the IP based
on interface name. Will report with results once I figure it out.

I'd much prefer being able to do that, than hard code an IP to the delta
service file.

**Comment by errordeveloper** [comment]
@danielschonfeld here is one way to do it:
```
ip addr show dev eth0  | grep inet | egrep -o [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+ | head -1
```

**Comment by danielschonfeld** [comment]
@errordeveloper i much appreciate that, but is there a way to utilize that in a service file without having to create its own bash script?

**Comment by errordeveloper** [comment]
@danielschonfeld good question... One thing you can do is make sure `hostname -i` returns the IP address you want, in that case you can use systemd's `%H`,  and the drop-in file would look like this:
```
[Service]
Environment="KUBELET_EXTRA_ARGS=--hostname-override=%H
```
Well, in fact if you do that, you might not need to create the drop-in any more.

To do this you need to modify `/etc/hosts`, and make sure there is only one entry for the hostname.

**Comment by hgfischer** [comment]
Ok. So I've added both the `--api-advertise-addresses` flag, and the `--hostname-override` flag to `/etc/systemd/system/kubelet.service.d/09-hostname-override.conf`.

Now, the master starts fine, but when I bootstrap a new node, the new wave-net sublet doesn't starts properly. It ends in a CrashLoopBackOff status. This is what I suppose is the issue, but I could not find how to fix it yet.

```
Sep 29 22:02:58 ubuntu kubelet[9590]: I0929 22:02:58.777738    9590 summary.go:352] Missing default interface "eth0" for node:knode01
Sep 29 22:02:58 ubuntu kubelet[9590]: I0929 22:02:58.778080    9590 summary.go:352] Missing default interface "eth0" for pod:kube-system_weave-net-68oww
Sep 29 22:02:58 ubuntu kubelet[9590]: I0929 22:02:58.778267    9590 summary.go:352] Missing default interface "eth0" for pod:kube-system_kube-proxy-amd64-qx0wd
```

I've looked into kubelet cmd-line flags and I could not find something to set the interface name. Also the network binding related flags are defaulting to 0.0.0.0. Do you guys know how to handle this?

**Comment by hgfischer** [comment]
I just noticed that DefaultNetworkInterface is hardcoded to "eth0" so making a hard guess, I think this is not the problem.

These are the node logs grepped by the name of the pod that is in CrashLooopBackOff:
```
Sep 29 22:38:17 ubuntu kubelet[9590]: I0929 22:38:17.810427    9590 kubelet.go:2350] SyncLoop (SYNC): 1 pods; weave-net-68oww_kube-system(2611c219-868f-11e6-9148-022e9105a14d)
Sep 29 22:38:17 ubuntu kubelet[9590]: I0929 22:38:17.813726    9590 kubelet.go:2764] Generating status for "weave-net-68oww_kube-system(2611c219-868f-11e6-9148-022e9105a14d)"
Sep 29 22:38:17 ubuntu kubelet[9590]: I0929 22:38:17.815174    9590 status_manager.go:312] Ignoring same status for pod "weave-net-68oww_kube-system(2611c219-868f-11e6-9148-022e9105a14d)", status: {Phase:Running Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2016-09-29 21:53:30 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2016-09-29 22:15:45 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [weave]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2016-09-29 21:54:10 +0000 UTC Reason: Message:}] Message: Reason: HostIP:10.0.2.15 PodIP:10.0.2.15 StartTime:2016-09-29 21:53:30 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:weave State:{Waiting:0xc820cd4c20 Running:<nil> Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:0xc820452070} Ready:false RestartCount:13 Image:weaveworks/weave-kube:1.7.0 ImageID:docker://sha256:1ac5304168bd9dd35c0ecaeb85d77d26c13a7d077aa8629b2a1b4e354cdffa1a ContainerID:docker://64d056f138d7090eb8c8252ab36ab9536a7bc331779a5c66e1e659401045412f} {Name:weave-npc State:{Waiting:<nil> Running:0xc820cd4c40 Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:true RestartCount:0 Image:weaveworks/weave-npc:1.7.0 ImageID:docker://sha256:4d7f0bd7c0e63517a675e352146af7687a206153e66bdb3d8c7caeb54802b16a ContainerID:docker://9ef0e194ad17fa3f99e71848de0f5b622f44db7817b87a7484e8a29aa1c39a5e}]}
Sep 29 22:38:17 ubuntu kubelet[9590]: I0929 22:38:17.818411    9590 volume_manager.go:324] Waiting for volumes to attach and mount for pod "weave-net-68oww_kube-system(2611c219-868f-11e6-9148-022e9105a14d)"
Sep 29 22:38:17 ubuntu kubelet[9590]: I0929 22:38:17.902431    9590 summary.go:352] Missing default interface "eth0" for pod:kube-system_weave-net-68oww
Sep 29 22:38:17 ubuntu kubelet[9590]: I0929 22:38:17.905749    9590 atomic_writer.go:141] pod kube-system/weave-net-68oww volume default-token-aipxm: no update required for target directory /var/lib/kubelet/pods/2611c219-868f-11e6-9148-022e9105a14d/volumes/kubernetes.io~secret/default-token-aipxm
Sep 29 22:38:18 ubuntu kubelet[9590]: I0929 22:38:18.119921    9590 volume_manager.go:353] All volumes are attached and mounted for pod "weave-net-68oww_kube-system(2611c219-868f-11e6-9148-022e9105a14d)"
Sep 29 22:38:18 ubuntu kubelet[9590]: I0929 22:38:18.120507    9590 docker_manager.go:1892] Found pod infra container for "weave-net-68oww_kube-system(2611c219-868f-11e6-9148-022e9105a14d)"
Sep 29 22:38:18 ubuntu kubelet[9590]: I0929 22:38:18.121484    9590 docker_manager.go:1905] Pod infra container looks good, keep it "weave-net-68oww_kube-system(2611c219-868f-11e6-9148-022e9105a14d)"
Sep 29 22:38:18 ubuntu kubelet[9590]: I0929 22:38:18.122273    9590 docker_manager.go:1955] pod "weave-net-68oww_kube-system(2611c219-868f-11e6-9148-022e9105a14d)" container "weave-npc" exists as 9ef0e194ad17fa3f99e71848de0f5b622f44db7817b87a7484e8a29aa1c39a5e
Sep 29 22:38:18 ubuntu kubelet[9590]: I0929 22:38:18.122526    9590 docker_manager.go:2040] Got container changes for pod "weave-net-68oww_kube-system(2611c219-868f-11e6-9148-022e9105a14d)": {StartInfraContainer:false InfraChanged:false InfraContainerId:6b3f39ce5328126c22802900691c8c76972c8360cbb0cd7f8ae47893334afe69 InitFailed:false InitContainersToKeep:map[] ContainersToStart:map[0:Container {Name:weave Image:weaveworks/weave-kube:1.7.0 Command:[/home/weave/launch.sh] Args:[] WorkingDir: Ports:[] Env:[{Name:WEAVE_VERSION Value:1.7.0 ValueFrom:<nil>}] Resources:{Limits:map[] Requests:map[cpu:{i:{value:10 scale:-3} d:{Dec:<nil>} s:10m Format:DecimalSI}]} VolumeMounts:[{Name:weavedb ReadOnly:false MountPath:/weavedb SubPath:} {Name:cni-bin ReadOnly:false MountPath:/opt SubPath:} {Name:cni-bin2 ReadOnly:false MountPath:/host_home SubPath:} {Name:cni-conf ReadOnly:false MountPath:/etc SubPath:} {Name:default-token-aipxm ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:0xc820d4e930 ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:Always SecurityContext:0xc820d4e990 Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.] ContainersToKeep:map[6b3f39ce5328126c22802900691c8c76972c8360cbb0cd7f8ae47893334afe69:-1 9ef0e194ad17fa3f99e71848de0f5b622f44db7817b87a7484e8a29aa1c39a5e:1]}
Sep 29 22:38:18 ubuntu kubelet[9590]: I0929 22:38:18.123025    9590 docker_manager.go:2443] checking backoff for container "weave" in pod "weave-net-68oww"
Sep 29 22:38:18 ubuntu kubelet[9590]: I0929 22:38:18.123304    9590 docker_manager.go:2457] Back-off 5m0s restarting failed container=weave pod=weave-net-68oww_kube-system(2611c219-868f-11e6-9148-022e9105a14d)
Sep 29 22:38:18 ubuntu kubelet[9590]: I0929 22:38:18.123519    9590 docker_manager.go:2242] Backing Off restarting container &{Name:weave Image:weaveworks/weave-kube:1.7.0 Command:[/home/weave/launch.sh] Args:[] WorkingDir: Ports:[] Env:[{Name:WEAVE_VERSION Value:1.7.0 ValueFrom:<nil>}] Resources:{Limits:map[] Requests:map[cpu:{i:{value:10 scale:-3} d:{Dec:<nil>} s:10m Format:DecimalSI}]} VolumeMounts:[{Name:weavedb ReadOnly:false MountPath:/weavedb SubPath:} {Name:cni-bin ReadOnly:false MountPath:/opt SubPath:} {Name:cni-bin2 ReadOnly:false MountPath:/host_home SubPath:} {Name:cni-conf ReadOnly:false MountPath:/etc SubPath:} {Name:default-token-aipxm ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:0xc820d4e930 ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:Always SecurityContext:0xc820d4e990 Stdin:false StdinOnce:false TTY:false} in pod weave-net-68oww_kube-system(2611c219-868f-11e6-9148-022e9105a14d)
Sep 29 22:38:18 ubuntu kubelet[9590]: E0929 22:38:18.124058    9590 pod_workers.go:184] Error syncing pod 2611c219-868f-11e6-9148-022e9105a14d, skipping: failed to "StartContainer" for "weave" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=weave pod=weave-net-68oww_kube-system(2611c219-868f-11e6-9148-022e9105a14d)"
Sep 29 22:38:18 ubuntu kubelet[9590]: I0929 22:38:18.124583    9590 server.go:608] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"weave-net-68oww", UID:"2611c219-868f-11e6-9148-022e9105a14d", APIVersion:"v1", ResourceVersion:"898", FieldPath:""}): type: 'Warning' reason: 'FailedSync' Error syncing pod, skipping: failed to "StartContainer" for "weave" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=weave pod=weave-net-68oww_kube-system(2611c219-868f-11e6-9148-022e9105a14d)"
Sep 29 22:38:18 ubuntu kubelet[9590]: I0929 22:38:18.124831    9590 server.go:608] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"weave-net-68oww", UID:"2611c219-868f-11e6-9148-022e9105a14d", APIVersion:"v1", ResourceVersion:"898", FieldPath:"spec.containers{weave}"}): type: 'Warning' reason: 'BackOff' Back-off restarting failed docker container
Sep 29 22:38:20 ubuntu kubelet[9590]: I0929 22:38:20.263645    9590 volume_stat_calculator.go:103] Failed to calculate volume metrics for pod weave-net-68oww_kube-system(2611c219-868f-11e6-9148-022e9105a14d) volume cni-bin: metrics are not supported for MetricsNil Volumes
Sep 29 22:38:20 ubuntu kubelet[9590]: I0929 22:38:20.265383    9590 volume_stat_calculator.go:103] Failed to calculate volume metrics for pod weave-net-68oww_kube-system(2611c219-868f-11e6-9148-022e9105a14d) volume cni-bin2: metrics are not supported for MetricsNil Volumes
Sep 29 22:38:20 ubuntu kubelet[9590]: I0929 22:38:20.266548    9590 volume_stat_calculator.go:103] Failed to calculate volume metrics for pod weave-net-68oww_kube-system(2611c219-868f-11e6-9148-022e9105a14d) volume cni-conf: metrics are not supported for MetricsNil Volumes
Sep 29 22:38:20 ubuntu kubelet[9590]: I0929 22:38:20.815971    9590 worker.go:183] Non-running container probed: weave-net-68oww_kube-system(2611c219-868f-11e6-9148-022e9105a14d) - weave
```

**Comment by errordeveloper** [comment]
@hgfischer this sounds like a more general bug (not so much related to kubeadm), could you please create another issue?

**Comment by errordeveloper** [comment]
> also does kubeadm join copy the 10-kubeadm.conf from the master on joining?

Missed this at first... The answer is - no, it doesn't need to go down to this level, in fact it's completely unaware of systemd as such.

**Comment by karthik101** [comment]
Well i had the same issue in 1.7.1
Fixed it with:
kubeadm reset
kubeadm init --apiserver-advertise-address=10.10.10.4 

Thank you luxas.

**Comment by jboero** [comment]
I know this thread is super long and pretty old but I figured I'd play my $0.02 for anyone else that comes along it.  I also have many interfaces and struggle with kubeadm across various versions.  I find that the best way to deploy my single-node for a local dev environment is to use a dummy interface.  As you can't kubeadm on loopback (how annoying) and I've rarely been successful with default route, here is a tip for dummy dev.  Note this is especially handy when using a laptop with only wifi as you can never expect to have consistent IP across access points and coffee shops and also can't use it when disconnected or on a plane without wifi:

`$ sudo ip link add dummy0 type dummy`

Or configure perm devices via here:
https://unix.stackexchange.com/questions/335284/how-can-we-create-multiple-dummy-interfaces-on-linux

Config a static IP on a dummy interface and use it for --apiserver-advertise-address.  As there is nothing else messing with routes on that device, it's clean and ready to use locally.  Super handy and sometimes bypasses issues with flannel/calico not getting routes from host (at least in my experience).

**Comment by mwtzzz** [comment]
I'd like to add a comment that in order for me to get this to work (same issue as OP), it was necessary to add a route on the worker nodes: 
`ip route add 10.96.0.0/16 dev eth1 src <private network ip>`
where "private network ip" is the ip assigned to the node's interface that's on the same network as the master node (likely a 172.28... address if you tend to use defaults in Vagrant). 

The other solutions above were helpful in getting *some* but not all of the errors fixed. This ip route was the final piece needed.

**Comment by Kerren-Entrostat** [comment]
Hi everyone,

Just to add to this, I was having problems getting my nodes to join the master node (this was not a cloud setup). I did and extra step which got everything working pretty well. I added an entry to my `/etc/hosts` file on the node itself that directed the hostname of the node to its IP address on the correct interface.

So for example, if your node's hostname is `node-1.cluster.example.com` and the IP address is `10.0.0.101` then you'd add the following line to your hosts file,
```
10.0.0.101 node-1.cluster.example.com
```

When you run the `kubeadm join` command, it should then use the correct interface.

**Comment by vaibhav-kaushal** [comment]
@mwtzzz That solution worked, but now I am seeing multiple pods, running on different nodes with the same IP address. What might be wrong here?

Output of `kubectl get pods -A -o wide`:

```
NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE     IP          NODE       NOMINATED NODE   READINESS GATES
default       busybox-6cd57fd969-zr576           1/1     Running   0          3m16s   10.32.0.2   server-5   <none>           <none>
default       nginx-86c57db685-2zcjr             1/1     Running   0          11m     10.32.0.2   server-3   <none>           <none>
kube-system   coredns-6955765f44-gglvz           1/1     Running   5          3h31m   10.32.0.3   server-1   <none>           <none>
kube-system   coredns-6955765f44-nc8ff           1/1     Running   5          3h31m   10.32.0.2   server-1   <none>           <none>
kube-system   etcd-server-1                      1/1     Running   5          3h31m   10.0.2.15   server-1   <none>           <none>
kube-system   kube-apiserver-server-1            1/1     Running   5          3h31m   10.0.2.15   server-1   <none>           <none>
kube-system   kube-controller-manager-server-1   1/1     Running   5          3h31m   10.0.2.15   server-1   <none>           <none>
kube-system   kube-proxy-8mnlb                   1/1     Running   0          55m     10.0.2.15   server-5   <none>           <none>
kube-system   kube-proxy-9hpcr                   1/1     Running   1          55m     10.0.2.15   server-2   <none>           <none>
kube-system   kube-proxy-q2np4                   1/1     Running   0          55m     10.0.2.15   server-4   <none>           <none>
kube-system   kube-proxy-vw68k                   1/1     Running   1          56m     10.0.2.15   server-3   <none>           <none>
kube-system   kube-proxy-wjpbb                   1/1     Running   1          56m     10.0.2.15   server-1   <none>           <none>
kube-system   kube-scheduler-server-1            1/1     Running   5          3h31m   10.0.2.15   server-1   <none>           <none>
kube-system   weave-net-2jttm                    2/2     Running   28         158m    10.0.2.15   server-2   <none>           <none>
kube-system   weave-net-fhs59                    2/2     Running   27         158m    10.0.2.15   server-3   <none>           <none>
kube-system   weave-net-g67sp                    2/2     Running   9          158m    10.0.2.15   server-1   <none>           <none>
kube-system   weave-net-jqz69                    2/2     Running   30         158m    10.0.2.15   server-5   <none>           <none>
kube-system   weave-net-qc4ns                    2/2     Running   25         143m    10.0.2.15   server-4   <none>           <none>
```

**Comment by mwtzzz** [comment]
Hi Vaibhav,

Unfortunately it has been a few months since I was in that job. I'm now at
a different company where we use Openshift on a large scale. I wouldn't
know what to tell you about your issue.

Michael

**Comment by zimmertr** [comment]
Neither of the posted solutions are working for me with Packer/Vagrant and RHEL 7 using Kubeadm to bootstrap a v1.18.0 cluster.

Some network information:
```
LAN CIDR: 192.168.30.0/24
VPN CIDR: 172.27.0.0/16
Docker Engine CIDR: 192.168.65.0/24
Kubernetes Pod CIDR: 172.16.0.0/16
Kubernetes Service CIDR: 172.32.0.0/16
Calico IPV4 Pool CIDR: 172.16.0.0/16
```

The `calico-node` daemonset also has `IP_AUTODETECTION_METHOD` set to `interface=eth1`. This is because my Vagrant VMs come up with `eth0` populated with `10.0.2.15/24`. I'm not sure why. But `eth0` has the proper IP Address supplied via Vagrant. 

The `calico-node` pods running on each worker node are producing the following logs repeatedly:
```
[INFO][8] startup.go 365: Hit error connecting to datastore - retry error=Get https://172.32.0.1:443/api/v1/nodes/foo: dial tcp 172.32.0.1:443: connect: connection refused
```

I can curl that endpoint from the master node but not the worker nodes. Since they communicate via the LAN CIDR mentioned above: `192.168.30.0/24`

Adding routes like @mwtzzz specified did not yield a working cluster unfortunately. 

Any ideas?
