### ISSUE TITLE
contrib: add preconfigured cluster VM images

### ISSUE THREAD

**Issue by proppy** [kubernetes/kubernetes#3361]
It would be nice to maintain a set of preconfigured cluster VM images, in order for newcomers to easily try kubernetes, without checking out the source tree and dynamically provisioning a cluster.

(Related to #3244)

This could take the form of a [bootstrap-vz](https://github.com/andsens/bootstrap-vz) plugin that add the kubernetes binary and init files, and produce a preconfigured single node cluster image for Virtualbox and other supported [providers](https://github.com/andsens/bootstrap-vz/tree/master/bootstrapvz/providers). Based on the `docker_daemon` in the [development branch](https://github.com/andsens/bootstrap-vz/tree/development/bootstrapvz/plugins/docker_daemon)

@kelseyhightower mentionned https://packer.io/, but it doesn't apparently provide a way to build a box from scratch, it rather assume you start from an existing image and dynamically provision it over SSH.

**Comment by pires** [comment]
I've just finished a Vagrant + CoreOS (based on @kelseyhightower work) that bootstraps one master and two minions (you can define the number of minions). All you need is Vagrant and Virtualbox, so it works in Linux and Mac OS.

Oh, and ```vagrant up``` is the only command you'll need :-)

**Comment by proppy** [comment]
Neat, is that possible to package it as a vagrant box? https://docs.vagrantup.com/v2/boxes.html

**Comment by pires** [comment]
@proppy i'm sorry but I may be facing some networking issues between pods. Will need to debug it. Wanna help?

**Comment by pires** [comment]
@proppy nevermind, it's fixed! In case you want and try to package it you can find it [here](https://github.com/pires/kubernetes-vagrant-coreos-cluster).

**Comment by pires** [comment]
@proppy from what I read, a box only allows for one VM inside of it.

**Comment by proppy** [comment]
@pires but it would be nice to have a .box image that behave like a single node cluster.

**Comment by pires** [comment]
@proppy yeah, we can do it with https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/cloud-configs/standalone.yaml. I've tried at providing a box but it didn't seem trivial. Perhaps someone feels otherwise? Would definitely help.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.
