### ISSUE TITLE
Esipp transition plan

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#33625]
Alpha to beta (1.5): 
- Declare 2 sets of annotations, one in the alpha namespace (already exists) and one in the beta namespace (new)
- alpha always takes precedence
- If alpha is set to a valid value, we write the beta annotation to mirror it clobbering any user field

Why convert alpha to beta:     
1. Users are auto transitioned 
2. Not converting means if alpha and beta are set to 2 different values, deleting the alpha requires a cleanup of the alpha value, and an activation of the beta value. This might be confusing and error prone. 
3. Not converting makes handling updates harder, as we would have to allow updates to the "inactive" one.

Beta to GA (1.6): 
- Declare 2 fields that mirros the annotations in beta
- Ignore alpha annotations (any alpha annotations in play will continue to work because they were translated to the beta annotation)
- Perform the same conversion time clobbering

If users upgrade from 1.4 to 1.6 directly, the alpha annotation is ignored and esipp stops working.

**Comment by bprashanth** [comment]
Well the easier option is to just document that setting the alpha annotation and beta annotation to different values is unsupported, and simply honor the older annotation. 

This makes dropping the annotation harder. 
It also means we have to keep checking for divergent values in code.

**Comment by jlowdermilk** [comment]
FYI, the ESIPP alpha feature tests are currently broken on the 1.5 branch. See #37768, #37769. Is that something you're looking at?

**Comment by bprashanth** [comment]
I just pick a few suites and pay attention to them, in this case the head suite and gci-1.5
https://k8s-testgrid.appspot.com/google-gce#gci-gce-alpha-features
https://k8s-testgrid.appspot.com/google-gce#gci-gce-alpha-features-release-1.5
https://k8s-testgrid.appspot.com/google-gke#gke-alpha-features

there was a leak at one point which I fixed and manually deleted resources in a bunch of projects, maybe I missed this one (what's the ci prefix for?). I'll clean this one up as well and watch it.

**Comment by bprashanth** [comment]
we know it's a leak because the logs say
```
I1201 12:50:05.719] Dec  1 12:50:05.718: INFO: At 2016-12-01 12:30:02 -0800 PST - event for external-local: {service-controller } CreatingLoadBalancerFailed: Error creating load balancer (will retry): Failed to create load balancer for service e2e-tests-esipp-6mjj3/external-local: failed to ensure static IP : error creating gce static IP address: googleapi: Error 403: Quota 'STATIC_ADDRESSES' exceeded. Limit: 7.0, quotaExceeded
```
And im basically going to lookup the projet in the same logs and delete ips/bump quota. 
I think test infra is working on some janitor job that auto ttls leaks.
