### ISSUE TITLE
kubeadm should have flags to bind to different ports and addresses

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33638]
Right now we bind `kube-apiserver` to `0.0.0.0:443` and `kube-discovery` to `0.0.0.0:9898`. We need to allow users to:

- override both ports separately (and may be change the default from 443 to 6443 or something)
- override bind address if they wish to make it more secure (_we must keep default as is for now, as we would break external accessibility if we do that_ and _it's also what `kube-apiserver` defaults to_)

**Comment by errordeveloper** [comment]
Flags to discuss:

- `--api-bind-address=<ip>`
- `--api-bind-port=<port>`
- `--discovery-bind-port=<port>`
- `--discovery-bind-address=<port>`

Also, I found these higher-level ones in my notes, I think we might want to have them eventually:
- `--api-bind-loopback-unsecure=<bool>`
- `--prefer-private-network=<bool>`
- `--prefer-public-network=<bool>`

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle

**Comment by errordeveloper** [comment]
Also, we should consider allowing interface names as values...

**Comment by guybrush** [comment]
Making `6443` the default (and nothing else for now) would be a very low hanging fruit and simplifies running a load-balancer in a local developer-environment (single-node, schedulable master) a lot.

**Comment by jacek-marchwicki** [comment]
Making 6443 default it would be enough at starting point -in most situations users would like to deploy some webserver on 443

**Comment by pires** [comment]
I agree with the proposed flags but would avoid the _higher-level_ ones for now.

**Comment by jacek-marchwicki** [comment]
There are some plans and ETA to change default port to `6443`?

**Comment by errordeveloper** [comment]
@pires yes, I didn't suggest we have to prioritise those, but it'd be good start the conversation on that topic. Also, being able to just pass interface names would be extremely handy.

**Comment by errordeveloper** [comment]
@guybrush @jacek-marchwicki I've opened https://github.com/kubernetes/kubernetes/issues/34311.

**Comment by errordeveloper** [comment]
I'm working on this.

**Comment by luxas** [comment]
This is now fixed at HEAD with @errordeveloper's PR

**Comment by wweic** [comment]
Hi, I'm wondering if `api-bind-address` is considered a useful option?  It's mentioned by @errordeveloper , but not implemented since the listening interface is still currently [hardcoded](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/master/manifests.go#L233). Thanks.

**Comment by luxas** [comment]
No, generally I don't think so, we'd like it to be secure as the default.
You should do a kubectl proxy if you'd like to expose the API server unsecurely though
```bash
kubectl --kubeconfig /etc/kubernetes/admin.conf proxy --address 0.0.0.0 --accept-hosts=\w*
```
