### ISSUE TITLE
kubeadm should not assume that hostname == nodename

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33641]
As pointed out by @justinsb, this is often the case on EC2.

**Comment by errordeveloper** [comment]
Just to illustrate this, the problem is about instance IDs vs hostnames.

**Comment by pires** [comment]
Since #34031 is biting us here as well, we should have join flags for advertising a specific IP and/or hostname.

**Comment by errordeveloper** [comment]
Yes, but we should also get better at determining the default.

**Comment by pires** [comment]
I'm always cautious about adding magic stuff but I'm open to review it if anyone adds it.

**Comment by zreigz** [comment]
I've prepared some proposal for it:
https://github.com/zreigz/release/commit/12a8c950117674498b84097002e9f99877027cf2

**Comment by pires** [comment]
@zreigz I too have relied on the IP address, in the past. This seems to be a tricky one.

**Comment by zreigz** [comment]
I've just made debian binaries and tested it. It seems to work

**Comment by zreigz** [comment]
cc @luxas

**Comment by luxas** [comment]
@justinsb @errordeveloper @pires What's the status of this issue?
Anything we can do easily and who should I assign it to?

**Comment by pires** [comment]
@luxas you can assign it to me. Here's how my fix would look like:
* Add `--hostname-override <hostname_or_ip>` flag to `kubeadm join`
* When the flag above is set, run `kubelet`  with `--hostname-override <hostname_or_ip>`.

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#64
