### ISSUE TITLE
etcd3 watcher doesn't scale

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#33653]
I did some scalability tests with etcd3 enabled and it seems that watcher.go pretty much doesn't scale.

I think the problem we have is with ```tranform``` function:
https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/etcd3/watcher.go#L234

So to give you some numbers, in 2000-node kubemark, I started cluster at:
```
I0928 09:48:36.043709    3547 config.go:404] Will report 10.240.0.24 as public IP address.
I0928 09:48:36.045790    3547 server.go:328] Initalizing cache sizes based on 120000MB limit
```

and 12 second later I started getting:
```
W0928 09:48:48.398584    3547 watcher.go:319] Fast watcher, slow processing. Number of buffered events: 100.Probably caused by slow decoding, user not receiving fast, or other processing logic
```

I have __millions__ of such lines in my logs.

Note that this was empty cluster - there weren't any pods at that time in the system - so it was mostly traffic from nodes.

__This is pretty much a blocker for launching etcd3 - we can't launch with worse performance than etcd2__

@kubernetes/sig-scalability @xiang90 @hongchaodeng @timothysc

**Comment by wojtek-t** [comment]
@kubernetes/sig-api-machinery @lavalamp @gmarek

**Comment by timothysc** [comment]
I'll start digging soon, I need to clear off some administrative stuff 1st.

**Comment by smarterclayton** [comment]
I did not see this in my limited testing but was not in the many watcher configuration (hundreds of watchers, not thousands)

**Comment by wojtek-t** [comment]
@smarterclayton - it's not about number of watchers (with the cacher that is enabled since 1.1 or 1.2), there is exactly one watch per resource type to etcd. And here the bottleneck is with:
pkg/storate/etcd3/watcher.go

The problem here is the churn in the cluster (number of write operations with a given resource type per second to be more concrete).

**Comment by wojtek-t** [comment]
So what I claim is that "throughput of pkg/storate/etcd3/watcher.go" is too small (worse than with etcd2).

**Comment by xiang90** [comment]
@wojtek-t Seems like we can write a benchmark for `tranform` to start with?

**Comment by wojtek-t** [comment]
@xiang90 - that would definitely be useful

**Comment by wojtek-t** [comment]
To start with, we can probably start with updating node statuses

**Comment by hongchaodeng** [comment]
@wojtek-t 
Mind sharing steps and config to re-run it?

**Comment by gmarek** [comment]
@hongchaodeng - it was this config: https://github.com/kubernetes/test-infra/pull/689

**Comment by wojtek-t** [comment]
@xiang90 @hongchaodeng - doesn't https://github.com/coreos/etcd/pull/5880 implement what we actually need here? Am I missing something?

**Comment by xiang90** [comment]
@wojtek-t It is in 3.1, not 3.0. We probably can back port it for k8s if needed. I think @hongchaodeng will help to to figure out the root cause first.

**Comment by wojtek-t** [comment]
@xiang90 - it would be good if he could confirm, but I'm 90% sure that it's because of that. So backporting it would be super useful.

**Comment by hongchaodeng** [comment]
Benchmark code:
```Go
func BenchmarkWatch(b *testing.B) {
	ctx, store, cluster := testSetup(nil)
	defer cluster.Terminate(nil)

	w, err := store.WatchList(ctx, "/", "0", storage.Everything)
	if err != nil {
		log.Fatalf("Watch failed: %v", err)
	}

	obj := &api.Pod{ObjectMeta: api.ObjectMeta{Name: "foo"}}
	buf := bytes.NewBuffer(nil)
	if err := store.codec.Encode(obj, buf); err != nil {
		panic(err)
	}

	etcdcli := cluster.RandClient()
	val := string(buf.Bytes())
	actCh := make(chan struct{})
	go func() {
		for _ = range actCh {
			_, err := etcdcli.Put(ctx, "/abc", val)
			if err != nil {
				panic(err)
			}
		}
	}()
	fmt.Println("benchmarking ===")
	for n := 0; n < b.N; n++ {
		actCh <- struct{}{}
		_, ok := <-w.ResultChan()
		if !ok {
			panic("")
		}
	}
	close(actCh)
}
```

Profile result: (we ignore etcd part and only care about kubernetes part)
```
0.18s 12.00%  k8s.io/kubernetes/pkg/storage/etcd3.(*watchChan).processEvent
0.17s 11.33%  k8s.io/kubernetes/pkg/storage/etcd3.(*watchChan).transform
0.17s 11.33%  k8s.io/kubernetes/pkg/storage/etcd3.prepareObjs
0.14s  9.33%  k8s.io/kubernetes/vendor/github.com/coreos/etcd/clientv3.(*kv).Do
0.09s  6.00%  k8s.io/kubernetes/pkg/runtime.Decode
0.09s  6.00%  k8s.io/kubernetes/pkg/runtime/serializer/versioning.(*codec).Decode
0.09s  6.00%  k8s.io/kubernetes/pkg/storage/etcd3.decodeObj
```

Initial analysis:
- Confirms that transform is the bottleneck in watch path.
- 0.17s is used by transform().
- 0.14s is used by clientv3.(*kv).Do(). Both Get() and Put() is also calling Do(). We can't distinguish.
- 0.09s is used by Decode(). From this, we can roughly guess that Get() took 0.08s.

**Comment by wojtek-t** [comment]
@hongchaodeng - thanks for the benchmark. Though I think we shouldn't focus that much on cpu usage (which isn't out bottleneck now) - from what I observe the problem is throughput and in my opinion, when calling Get (as part of transform for updates) we are not using that many CPU, but we are blocking all other work.

So maybe backporting coreos/etcd#5880 would solve the problem?

**Comment by xiang90** [comment]
@wojtek-t We do not usually backport feature, we only backport bug fixes. Or put it another way, it breaks our policy.

We should try etcd master to see if it solves the problem. If we can confirm it fixes the issue, we will try to resolve it at etcd side. Either backport or release 3.1 early.

**Comment by xiang90** [comment]
@hongchaodeng Is that CPU usage? Or time spent in each func? /cc @wojtek-t

**Comment by wojtek-t** [comment]
>
@hongchaodeng Is that CPU usage? Or time spent in each func? /cc @wojtek-t

oh sorry - I might have misinterpreted it.

>
We should try etcd master to see if it solves the problem. If we can confirm it fixes the issue, we will try to resolve it at etcd side. Either backport or release 3.1 early.

@xiang90 - IIUC there isn't any official 3.1 release, right? If so, is there any easy way to test it? [we basically need etcd Docker image to do tests]

**Comment by timothysc** [comment]
@xiang90 ETA on 3.1 release?

**Comment by gmarek** [comment]
From slack: mid-late October.

**Comment by philips** [comment]
@xiang90 I think we need to backport to 3.0 to make a clean v2.3 -> v3.0 upgrade path, right?

**Comment by hongchaodeng** [comment]
> Is that CPU usage? Or time spent in each func? 

Latter.

Backporting feature is the last option. Before that, we need to verify the assumptions in the following ways:
- If we change Get() to serializable (non-quorum) and on falling-behind error falls back to linearizable (quorum), will it fix the problem?
- If the previous option doesn't fix the problem, will using PrevKV do?

**Comment by xiang90** [comment]
@hongchaodeng Right. I agree. We need to make sure PrevKV solve the problem before considering backport the feature back to 3.0.

**Comment by wojtek-t** [comment]
>
If we change Get() to serializable (non-quorum) and on falling-behind error falls back to linearizable (quorum), will it fix the problem?

We are using single-instance setup - will no-quorum change anything in this case?

>
If the previous option doesn't fix the problem, will using PrevKV do?

What is PrevKV? Can you please clarify?

**Comment by gyuho** [comment]
@wojtek-t 

>  there isn't any official 3.1 release, right? If so, is there any easy way to test it? [we basically need etcd Docker image to do tests]

We have https://github.com/coreos/etcd/releases/tag/v3.1.0-alpha.1 that contains https://github.com/coreos/etcd/pull/5880.

**Comment by hongchaodeng** [comment]
> We are using single-instance setup - will no-quorum change anything in this case?

Serializable read will be slightly faster.

**Comment by wojtek-t** [comment]
@hongchaodeng - in order to test PrevKV, we need to change the code in Kubernetes right? Could you please do it?

**Comment by xiang90** [comment]
@wojtek-t Sure. We will start working on that.

**Comment by wojtek-t** [comment]
@xiang90 - thanks; let me know if I can somehow help with it.

**Comment by timothysc** [comment]
@xiang90 @hongchaodeng  what's the status on a pull back, or 3.1 release?

**Comment by xiang90** [comment]
@timothysc 

It this https://github.com/kubernetes/kubernetes/pull/34089 works, we wont back port. If not, we will try prevKV feature in 3.1. If that helps, we will back port.

**Comment by timothysc** [comment]
It was my understanding the that whole extra ```get``` itself was the issue.

**Comment by wojtek-t** [comment]
OK - so I checked the results after having #34089 
And the results are significantly better (i.e. we can most handle 2000-node clusters). However, we are really at the edge, and the buffer incoming from etcd is basically always full.

I took a look into logs from kubemark-500 apiserver and I see this:
```
wojtekt@wojtekt-work:~/Downloads$ cat apiserver.txt | grep "watcher.go:319" | head -n 1
W1006 02:59:53.184746    3593 watcher.go:319] Fast watcher, slow processing. Number of buffered events: 100.Probably caused by slow decoding, user not receiving fast, or other processing logic
wojtekt@wojtekt-work:~/Downloads$ cat apiserver.txt | grep "watcher.go:319" | wc -l
120681
```

So we should at least try prevKV feature in 3.1 and see if that helps (because I'm pretty sure we can't really get higher than 2000 nodes with the current code).

@xiang90 @hongchaodeng - can you please try it?

**Comment by wojtek-t** [comment]
Also, if you change the code to use this feature and have the etcd release from which I can build docker container, I'm happy to run those experiments

**Comment by xiang90** [comment]
@wojtek-t Will put up a pr for trying prevKV this week (with 3.1 container).

**Comment by wojtek-t** [comment]
@xiang90 - great; thanks!

**Comment by wojtek-t** [comment]
@xiang90 @hongchaodeng 
I did the experiment with your PR: #34246 and it is waaaaaaaaaaaaaaay better.
And I'm talking both about metrics, but also about the logs that I mentioned before:
```
wojtekt@wojtekt-work:~/Downloads$ cat apiserver.txt | grep "watcher.go:319" | wc -l
120681
```
vs this one with your changes:
```
wojtekt@kubernetes-kubemark-master:~$ cat /var/log/kube-apiserver.log | grep "watcher.go:327" | wc -l
3478
```

And what is more, I forgot to switch on protobufs which is making things even faster.

So backporting this feature to 3.0.x would really help.

**Comment by xiang90** [comment]
@wojtek-t Ideally the number should be 0, right? Do we have any idea why it is not?

**Comment by wojtek-t** [comment]
Yes - ideally it should be 0 - though we should also check it with protobufs in storage enable to see if it will be smaller.

I think there can be multiple reasons of it not being 0. Once hypothesis is that we are calling decodeObject in the go-routine that is processing objects from the incoming channel:
https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/etcd3/watcher.go#L352

This is basically doing deserialization of objects, which may be expensive (especially for large objects). Once we have the prevKV in head, I will try to verify this hypothesis, but for me this seems most probable for now.
If this is true, the potential improvement may be to use some LRU cache for decoded objects, which should save as decoding on the "prevObject" (because it was already decoded as "currentObject" in the previous event for that object). But let's first have prevKV and then verify it (and potentially implement the fix later).

**Comment by xiang90** [comment]
@wojtek-t 3.0.11 is released with prevKV: https://github.com/coreos/etcd/releases/tag/v3.0.11

**Comment by gyuho** [comment]
There was some missing patches for prevKV.

Please try https://github.com/coreos/etcd/releases/tag/v3.0.12 instead.

Thanks.

**Comment by wojtek-t** [comment]
Thanks a lot for releasing 3.0.12.
@hongchaodeng is currently trying to update Kubernetes code with it: https://github.com/kubernetes/kubernetes/pull/34246


@xiang90 regarding my comment above - I created https://github.com/kubernetes/kubernetes/pull/34435 (this together with the use of prevKV should help a lot).
To save you effort with rebasing, we should probably merge your PR first, but my should go right after yours.

**Comment by wojtek-t** [comment]
OK - so we are already running more extensive performance tests using the new image.

So with the changes in 3.0.12 etcd release, and my PR #34435 that is already merged I would say is at least better than etcd2. I think that at least for now, we can close this issue.

**Comment by wojtek-t** [comment]
@xiang90 @hongchaodeng - thank for all the work here.
