### ISSUE TITLE
Support for unix sockets in RESTClient

### ISSUE THREAD

**Issue by nhlfr** [kubernetes/kubernetes#33657]
When discussing the PR #33077, we decided that we would like to be able to use unix sockets in RESTClient. That will allow to use proxy server securely on local hosts.

That will be beneficial for this issue - #31178

@kubernetes/sig-cli @smarterclayton @fabianofranz

**Comment by smarterclayton** [comment]
+1 - we have lots of use cases where RESTClient supporting unix sockets
properly inside of pods would allow secure proxying / API server access
from sidecars to the kubelet or to other host agents.
