### ISSUE TITLE
Refactor federation unit tests so that they don't modify objects

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#33667]
Currently there is a potential race/data sync issue when tests are modifying data that was already passed to the client/cache mocks. 

cc: @gmarek @quinton-hoole @kubernetes/sig-cluster-federation

**Comment by quinton-hoole** [comment]
@mwielgus @gmarek In #33769 I think that you need a lock on the Object (obj), not on the WatcherDispatcher, otherwise you still have a race while copying the object (if another go routine is writing the object concurrently)?

**Comment by mwielgus** [comment]
@quinton-hoole the idea is to copy the object on the same thread/goroutine as in which the modification happens. With this every goroutine will have its own copy that can freely modify without any lock.

**Comment by quinton-hoole** [comment]
@marun Was this resolved by your refactoring of the federation unit tests?  If not, could you take a look?

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#77.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
