### ISSUE TITLE
kubectl config set-credentials only takes secrets on the command line

### ISSUE THREAD

**Issue by jheiss** [kubernetes/kubernetes#33666]
kubectl config set-credentials only takes secrets (passwords, bearer tokens) as command line arguments, leaking those secrets to other users on the machine. It should support alternate ways of specifying those values in a way that is secure. E.g. reading from stdin or reading from a file.

**Comment by moravit** [comment]
I would like to take a peek at this.

**Comment by shahidhk** [comment]
@moravit Are you still working on this?

**Comment by cmluciano** [comment]
Would it be beneficial to implement this at general set-x level? I always thought it would be beneficial to import a whole file and merge it into my kubeconfig.

**Comment by sethpollack** [comment]
@pwittrock #dibs

**Comment by pwittrock** [comment]
@sethpollack Thanks Seth.  I am assigning this to myself as a placeholder while you work on it.

I think the first step step is to create a design proposal .md doc with the proposed changes to kubectl.  This will make sure everyone is on the same page about how we want to solve the problem.

**Comment by sethpollack** [comment]
Sure. Do I submit a PR to `docs/proposals`?

**Comment by pwittrock** [comment]
Yeah.  Maybe docs/proposals/kubectl/setcredentials.md?

**Comment by sethpollack** [comment]
@pwittrock Would something like this be ok?

## Objective

Support alternate ways of passing secrets to `kubectl config set-credentials`.

## Proposal

For username, password and, token. When set to `-`,  prompt user for input without the echo. (Similar to the way `kubectl create -f -` uses `-` to mean stdin.)

```
  kubectl config set-credentials NAME --username - --password -
  kubectl config set-credentials NAME --token -
```

Additionally we can read from a config file, but that would probably make more sense as a separate subcommand like `kubectl  config merge` and support more than just merging credentials.

**Comment by pwittrock** [comment]
@sethpollack That looks good.  Can you add what the prompt would look like?

**Comment by sethpollack** [comment]
@pwittrock 

So I'm thinking about adding the prompt option to `username`, `password`, and `token`.

- Username will prompt with echo `Please enter Username: username`.
- Password will prompt with masking `Please enter Password: *****`.
- Token will prompt without echo or mask because its likely copy/paste `Please enter Token:`.

There is already some prompt logic in `pkg/client/unversioned/clientcmd/auth_loaders.go`. I'm thinking about moving that to its own `prompt` package under `util`, adding the masking logic, and using it in both places.

**Comment by pwittrock** [comment]
@sethpollack  That sounds good to me.  Code reuse is good :)  We should reach out to the authors of that code before moving it out.

**Comment by sethpollack** [comment]
I think it was @brendandburns

**Comment by sethpollack** [comment]
This is the commit, let me know what you think? https://github.com/sethpollack/kubernetes/commit/f62e1c60d3cf516459d390ce652562521131aef9

**Comment by sethpollack** [comment]
@pwittrock should I submit a PR?

**Comment by grantbow** [comment]
[proposed Label] sig/kubectl
