### ISSUE TITLE
Tab completion doesn't work correctly when using `-n` instead of `--namespace`

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#33685]
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}                                                                             Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Kernel** (e.g. `uname -a`): Whatever is in Xenial right now
- **Install tools**: Kubernetes-Anywhere

**What happened**:

I typed: `kubectl logs -n kube-system [tab]` and got non-kube-system pods suggested.

**What you expected to happen**:

To get the same results as when I type: `kubectl logs --namespace=kube-system [tab]`

**How to reproduce it** (as minimally and precisely as possible):

Try to use the short-hand flag with tab completion. Observe that it doesn't filter to the namespace correctly.

**Anything else do we need to know**:

Here's an asciinema demonstration: https://asciinema.org/a/87449

**Comment by sttts** [comment]
Do I miss something here?

```shell
kubectl logs -n kube-system kube-dns-v20-1yt65                                                                                                                Error: unknown shorthand flag: 'n' in -n
```

**Comment by colemickens** [comment]
You must have an old `kubectl`. `kubectl -n` was added recently.
