### ISSUE TITLE
`kubernetes-verify-master` broken

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#33682]
verify-master is failing: http://ci-test.k8s.io/kubernetes-verify-master/4456/ probably due to https://github.com/kubernetes/kubernetes/pull/33658 not removing old godeps.

The `Jenkins verification Build succeeded.` did succeed in that pull.

@smarterclayton I'm having trouble sorting myself out. :(

**Comment by deads2k** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/33683

**Comment by eparis** [comment]
```
Verifying hack/make-rules/../../hack/verify-godep-licenses.sh
Checking for 'Godeps/' changes against 'remote/master'
No 'Godeps/' changes detected.
Checking for 'vendor/' changes against 'remote/master'
No 'vendor/' changes detected.
[0;32mSUCCESS[0m  hack/make-rules/../../hack/verify-godep-licenses.sh	1s
Verifying hack/make-rules/../../hack/verify-godeps.sh
Checking for 'Godeps/' changes against 'remote/master'
No 'Godeps/' changes detected.
Checking for 'vendor/' changes against 'remote/master'
No 'vendor/' changes detected.
[0;32mSUCCESS[0m  hack/make-rules/../../hack/verify-godeps.sh	0s
```

**Comment by dims** [comment]
Looks like https://github.com/kubernetes/kubernetes/pull/33683 merged. we can close this now?

**Comment by dims** [comment]
@smarterclayton @deads2k @saad-ali Can we please close this?

**Comment by deads2k** [comment]
> @smarterclayton @deads2k @saad-ali Can we please close this?

yes
