### ISSUE TITLE
kubeadm - kube-controller missing certs

### ISSUE THREAD

**Issue by zachaller** [kubernetes/kubernetes#33680]
**Kubernetes version** (use `kubectl version`): v1.4

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Kernel** (e.g. `uname -a`):4.4.0-36-generic #55-Ubuntu SMP x86_64 GNU/Linux
- **Install tools**: kubeadm
- **Others**:

**What happened**:
kubeadm when setting up kube-controller did not pass in ssl certs and so when it went to post to amazon api over https it failed with: 

```controllermanager.go:227] Cloud provider could not be initialized: could not init cloud provider "aws": error finding instance i-05e5cdaf5b6fda435: error listing AWS instances: RequestError: send request failed
caused by: Post https://ec2.us-east-1.amazonaws.com/: x509: failed to load system roots and no roots provided```

**What you expected to happen**: I expected it to setup the master node


**How to reproduce it** (as minimally and precisely as possible): just try using kubeadm on aws with kubeadm init --cloud-provider=aws after setting kubelet to also use cloud-provider=aws

I have the commit here that I have tested to fix the issue i can subbmit a PR if wanted

https://github.com/zachaller/kubernetes/commit/bd1d93e2e0d50410fbc5b9a913a34eea1eb346b3

**Comment by pbecotte** [comment]
Don't suppose anyone has any ideas for working around this until the next release?  (or a way to get a more up to date version of this binary)
