### ISSUE TITLE
PetSet instance gets added to DNS before it's ready

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#33688]
I've seen this happen both in a kube-up'ed cluster on GCE at 1.3.7 and on a GKE alpha cluster at 1.4.0

**How to reproduce it** (as minimally and precisely as possible):

Run `kubectl create -f examples/cockroachdb/cockroachdb-petset.yaml` and wait for the containers to start up.

**What happened**:

cockroachdb-0, cockroachdb-1, and cockroachdb-2 all started up fine. cockroachdb-3 has gotten stuck in a CrashLoopBackoff state.

```console
$ kc get pods
NAME            READY     STATUS             RESTARTS   AGE
busybox         1/1       Running            0          27m
cockroachdb-0   1/1       Running            0          33m
cockroachdb-1   1/1       Running            0          32m
cockroachdb-2   1/1       Running            0          32m
cockroachdb-3   0/1       CrashLoopBackOff   13         31m
```

After inspecting the state of things, my naive guess at what the problem is is that cockroachdb-3 got added to the list of the cockroachdb service's endpoints even though it never made it to a Ready state:

```
kc get endpoints cockroachdb -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.beta.kubernetes.io/hostnames-map: '{"10.0.0.3":{"HostName":"cockroachdb-0"},"10.0.0.4":{"HostName":"cockroachdb-2"},"10.0.0.5":{"HostName":"cockroachdb-3"},"10.0.1.4":{"HostName":"cockroachdb-1"}}'
  creationTimestamp: 2016-09-28T19:31:02Z
  labels:
    app: cockroachdb
  name: cockroachdb
  namespace: default
  resourceVersion: "5112"
  selfLink: /api/v1/namespaces/default/endpoints/cockroachdb
  uid: 17472766-85b2-11e6-ac0c-42010a800fc2
subsets:
- addresses:
  - hostname: cockroachdb-0
    ip: 10.0.0.3
    targetRef:
      kind: Pod
      name: cockroachdb-0
      namespace: default
      resourceVersion: "347"
      uid: 1797f012-85b2-11e6-ac0c-42010a800fc2
  - hostname: cockroachdb-2
    ip: 10.0.0.4
    targetRef:
      kind: Pod
      name: cockroachdb-2
      namespace: default
      resourceVersion: "483"
      uid: 4c0fdb19-85b2-11e6-ac0c-42010a800fc2
  - hostname: cockroachdb-3
    ip: 10.0.0.5
    targetRef:
      kind: Pod
      name: cockroachdb-3
      namespace: default
      resourceVersion: "5110"
      uid: 5dfc51e9-85b2-11e6-ac0c-42010a800fc2
  - hostname: cockroachdb-1
    ip: 10.0.1.4
    targetRef:
      kind: Pod
      name: cockroachdb-1
      namespace: default
      resourceVersion: "425"
      uid: 33a62c93-85b2-11e6-ac0c-42010a800fc2
  ports:
  - name: grpc
    port: 26257
    protocol: TCP
  - name: http
    port: 8080
    protocol: TCP
```

This may be affecting its startup process if it tries to join itself.

**What you expected to happen**:

I wouldn't expect the DNS entries for pets to be added until the pets are running and ready.

**Anything else do we need to know**:

I don't know that it repros every time, but it's happened twice now while using the dynamic volume provisioner on GCE/GKE. I don't remember ever seeing this when using minikube with pre-provisioned-PVs.

Maybe it's just that we shouldn't be joining new pets to the entire `cockroachdb` DNS name, and should scope it down to joining `cockroachdb-0.cockroachdb` or something similar. Is this expected behavior, and actually a problem somewhere in cockroach?

@bprashanth @tschottdorf

**Comment by bprashanth** [comment]
This is by design, if you specify `tolerate-unready-endpoints` then you'll get endpoints before ready (eg: https://github.com/kubernetes/kubernetes/blob/master/examples/cockroachdb/cockroachdb-petset.yaml#L28). This is so you can actually hang till you see yourself in DNS, and prevent the next member of the set from getting created till you pass readiness (some pets do this through the peer finder: http://kubernetes.io/docs/user-guide/petset/bootstrapping/#background-1). 

The safest way to bootstrap is generally in a seralized manner:     

pet-0 comes up
hangs till pet-0s ip shows up in DNS under hostname (init container)
pet-0 starts the db (app container)
db initializes itself/joins cluster
pet-0 passes readiness probe
pet-1 is created...

**Comment by a-robinson** [comment]
Doh, I'm sorry. That's what I get for debugging while on pain meds. Thanks for the pointers, I'll look more into what's causing the hang.
