### ISSUE TITLE
kubeadm blocks waiting for 'control plane' in Ubuntu Wily

### ISSUE THREAD

**Issue by zhang8473** [kubernetes/kubernetes#33689]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
1.4

**Environment**:
Ubuntu Wily (15)
- **Cloud provider or hardware configuration**:
  local pc
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
  4.2.0-30-generic #35-Ubuntu SMP 
- **Install tools**:
  http://kubernetes.io/docs/getting-started-guides/kubeadm/
- **Others**:

**What happened**:
at the step
`kubeadm init`
Blocks at  "waiting for the control plane to become ready" forever

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:
I am following the instruction of http://kubernetes.io/docs/getting-started-guides/kubeadm/. Block for at least one day.

**Comment by bulletRush** [comment]
what's your hostname? your hostname "must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)* (e.g. 'example.com') spec.nodeName: Invalid value: "vm_81_12_centos": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)* (e.g. 'example.com')]
---
check /var/log/message for more information.

you can change your hostname to your ip address

**Comment by bulletRush** [comment]
@pwittrock If I want add some check operations(e.g like question in this issue) to kubeadm, what should I do? Is there any other plans?

**Comment by lukemarsden** [comment]
@luxas could you link to your WIP on pre-flight checks? This would be a great one to add!

**Comment by pwittrock** [comment]
cc @mikedanese

**Comment by zhang8473** [comment]
Yes, my hostname includes a dash, but how do I know that my hostname must match (.a-z0-9?)*. It seems that Kube team did not mention that in the user guide.

**Comment by bulletRush** [comment]
@zhang8473, kubeadm write some static pods in /etc/kubernets/manifests. kubelet will check this directory periodic. when kubelet startup, it checks static pod first, this log("must match...") only print once, then kubelet will try to connect kube-api-server time and time again. 

You say you have changed your hostname at(/etc/hostname). I think this method isn't correct. I have changed my hostname by `hostnamectl` command in centos. 

---

可以加我QQ(1733887507)一起交流学习

**Comment by zhang8473** [comment]
@bulletRush Exactly, I have restarted the machine after change /etc/hostname. Noe the static hostname displayed in my system is "g751jt". I still have the same problem.

**Comment by bulletRush** [comment]
@zhang8473 
* first, remember kubelet argments via `ps aux | grep kubelet`. For me, it's:
```shell
/usr/bin/kubelet --kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=100.64.0.10 --cluster-domain=cluster.local --v=4
```

* stop kubelet service: `systemctl stop kubelet`
* run kubelet in one terminal directly use command in first step and see what happend when kubelet startup

**Comment by zhang8473** [comment]
@bulletRush I have gotten the `service kubelet` step. I checked the services. The kubelet is not running. I stuck at `kubeadm init`.

**Comment by bulletRush** [comment]
@zhang8473 you should start kubelet service up first, then run kubeadm init

**Comment by zhang8473** [comment]
http://kubernetes.io/docs/getting-started-guides/kubeadm/
This user guide never tells me to run kubelet service up first.

**Comment by bulletRush** [comment]
@zhang8473 , 2333333333, hahhhhh, It'a mistake here. the guide for centos tell us to run kubelet, but the guide for ubuntu doesn't.

**Comment by zhang8473** [comment]
@pwittrock @lukemarsden You need to do something on your documents...

**Comment by luxas** [comment]
It's not necessary to do `systemctl start kubelet` on Ubuntu, as the package automatically starts itself.
That's the convention for debian packages.

The convention for rpms is to not start the services automatically, so therefore we've left it to the user and documented it

**Comment by zhang8473** [comment]
However, the kubeadm blocks. No error message and no status report, which is not proper for a product.

**Comment by luxas** [comment]
Well, I hope you calm down and realize that we actively chose to not "support" Wily now in the first release, but we are going to increase our scope as we have resources to test it, and develop further

We have worked very hard on this "product" as you call it, and dealing with every possible configuration the user may have clearly is impossible. You're welcome to help contributing if you want to of course.

Please make sure kubelet is running before running `kubeadm init`, if it has been disabled of some reason

**Comment by marun** [comment]
@zhang8473 Are there any errors in the kubelet logs?

**Comment by arpat** [comment]
Try adding `cgroup_enable=memory` on the kernel boot cmdline. The memory controller may not be default enabled by default in debian/ubuntu.

**Comment by zhang8473** [comment]
@marun Yes, I do see some errors in the kubelet logs:
systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Fri 2016-09-30 14:12:31 PDT; 2 days ago
     Docs: http://kubernetes.io/docs/
 Main PID: 705 (kubelet)
   CGroup: /system.slice/kubelet.service
           └─705 /usr/bin/kubelet --kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=100.64.0.10 --clu...

Oct 03 13:28:25 g751jt kubelet[705]: I1003 13:28:25.130186     705 server.go:608] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"g751jt", UID:"g751jt", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeHasSufficientMem...odeHasSufficientMemory
Oct 03 13:28:25 g751jt kubelet[705]: E1003 13:28:25.130302     705 kubelet_node_status.go:88] Unable to register node "g751jt" with API server: Post https://192.168.252.104:443/api/v1/nodes: dial tcp 192.168.252.104:443: getsockopt: connection refused
Oct 03 13:28:25 g751jt kubelet[705]: I1003 13:28:25.130316     705 server.go:608] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"g751jt", UID:"g751jt", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeHasNoDiskPressur... NodeHasNoDiskPressure
Oct 03 13:28:25 g751jt kubelet[705]: I1003 13:28:25.296353     705 reflector.go:249] Listing and watching *api.Pod from pkg/kubelet/config/apiserver.go:43
Oct 03 13:28:25 g751jt kubelet[705]: I1003 13:28:25.296362     705 reflector.go:249] Listing and watching *api.Node from pkg/kubelet/kubelet.go:406
Oct 03 13:28:25 g751jt kubelet[705]: E1003 13:28:25.296656     705 reflector.go:203] pkg/kubelet/config/apiserver.go:43: Failed to list *api.Pod: Get https://192.168.252.104:443/api/v1/pods?fieldSelector=spec.nodeName%3Dg751jt&resourceVersion=0: dial tcp 192....pt: connection refused
Oct 03 13:28:25 g751jt kubelet[705]: E1003 13:28:25.296745     705 reflector.go:203] pkg/kubelet/kubelet.go:406: Failed to list *api.Node: Get https://192.168.252.104:443/api/v1/nodes?fieldSelector=metadata.name%3Dg751jt&resourceVersion=0: dial tcp 192.168.25...pt: connection refused
Oct 03 13:28:25 g751jt kubelet[705]: I1003 13:28:25.297813     705 reflector.go:249] Listing and watching *api.Service from pkg/kubelet/kubelet.go:387
Oct 03 13:28:25 g751jt kubelet[705]: E1003 13:28:25.298065     705 reflector.go:203] pkg/kubelet/kubelet.go:387: Failed to list *api.Service: Get https://192.168.252.104:443/api/v1/services?resourceVersion=0: dial tcp 192.168.252.104:443: getsockopt: connection refused
Oct 03 13:28:25 g751jt kubelet[705]: E1003 13:28:25.732023     705 event.go:208] Unable to write event: 'dial tcp 192.168.252.104:443: getsockopt: connection refused' (may retry after sleeping)

**Comment by zhang8473** [comment]
@luxas I was in peace but your statement "We have worked very hard" makes me feel uncomfortable. This statement sounds like that Google hired someones who can only do leetcode problems but not be able to make real product bug free by "working very hard". I do not have to work hard but my work is bug free.

**Comment by lukemarsden** [comment]
@zhang8473 neither @luxas nor I are google employees, we are both
volunteers on kubernetes. And we did work hard on kubeadm, and released it
in alpha to get early feedback. Please be kind, and we will work together
to solve your problem. Thanks!

**Comment by zhang8473** [comment]
@lukemarsden @luxas I am sorry that I do not know you are volunteers. "kubernetes members" shows up next to @luxas on github. Google employers should be blamed if they say "working hard" but cannot get the work done. They even need volunteers to help them?! You are using your rest time to improve this alpha version. I appreciate that. 

Now let's focus on the error report from kubelet, do you have any idea about why "192.168.252.104:443 connection refused"?

**Comment by bulletRush** [comment]
@zhang8473 ,  you have no idea about how to debug. You should learn it first by google. It't not @lukemarsden @luxas or any other k8s members' problem. No body have same environment as you.
You even did not give any useful information. I had advised you run kubelet directly already, have you done it? You say you got a "connection refused", but have you seen your kube-apiserver is running and why? If you can't run your cluster by kubeadm. why not try old way?

**Comment by zhang8473** [comment]
@bulletRush You do not know how to discuss problems. Please do not speak. I saw your blog and you are very basic. The product is supposed to run any env and fits for all. If it does not, an error msg should show up. 

No mature product blocks without warning/errors. No body knows the "old way" if the document of kubenetes does not say.

**Comment by freshfishyu** [comment]
`kubeadm init` would run etcd and kube-api-server in  container.
` Post https://192.168.252.104:443/api/v1/nodes: dial tcp 192.168.252.104:443: getsockopt: connection refused` show that your kube-api-server was not running succ.
I used kubeadm init to start the cluster but it failed. After inspection, I found that the etcd port was occupied by other processes, resulting in the failure to start the etcd, causing further kube-api-server run-time exception.
you should check container's status,and find why kube-api-server failed to start.`docker ps`,`docker log` will help you.

**Comment by marun** [comment]
@zhang8473 This is open-source, and as indicated is 'alpha' quality.  So no, it's not mature yet.  User feedback such as yours is essential to evolve the software towards maturity, but such feedback needs to be supplied in a respectful manner.  Personal attacks are not acceptable, as per the Kubernetes Code of Conduct:

https://github.com/kubernetes/kubernetes/blob/master/code-of-conduct.md

**Comment by zhang8473** [comment]
@marun I acknowledged this is alpha after I saw @luxas replies, but the purpose is not always alpha. Nobody wants employers who says "working hard" but cannot fix problems. However, I did not know they are just from community. I said I am sorry for this misunderstanding. I may personally attack bulletRush because this person thinks github is a chat room in Tencent and keep on using those unprofessional words. If my words are heavy, also sorry.

So, is there any way to config etcd port?

**Comment by luxas** [comment]
Okay, let's focus on the issue and forget about above off-topic discussion.
Apoligies if I hurt somebody with what I said.

No, there isn't a built-in way to customize the etcd port.
Why should there be? etcd officially supports one port only for client communication, 2379, and we're using that.
But you mean that you have some etcd instance already listening to 2379?
Then there's no doubt at all why the control plane doesn't come up

Can you do something to your side to fix it?

**Comment by bulletRush** [comment]
i leave my qq account because i want to help you solve your issue as soon as possisble. 
discussing  was supposed to be relaxed and happy. we aren't talking about politics, terrorism, why so serious?  i write my steps and wish you can find out more useful information, but not 'why i get a connection refused?'. 

in your situation, edit /etc/kubernetes/manifests manaual after kubeadm startup may solve your issue. i am not really sure. the process code is in kubelet.go, i need reread it.

sorry for my unfriendly behaiver.

**Comment by bulletRush** [comment]
midify kubeadm source code directly may be more easy and reuseable.

**Comment by errordeveloper** [comment]
@bulletRush could you jump on Slack and we could discuss it there?

**Comment by errordeveloper** [comment]
This one of many catch-all issues what seems like the same problem but isn't. Some of the problems raised here should be fixed with pre-flight checks that will be available in the next snapshot package, and are already available in the unstable channel for testing.

**Comment by errordeveloper** [comment]
Pease checkout https://github.com/errordeveloper/kubernetes-ansible-vagrant, there is code to handle firewalld rules and SELinux stuff (if you are on CentOS), as well as VirtualBox issues (applies to Ubuntu as well as CentOS). We are planing to provide plain text documentation soon too. Find me on Slack if you still have problems. It's always a good idea to create a new issue rather then comment on an existing one that seems like it describes your problem.

**Comment by aaronbbrown** [comment]
> first, remember kubelet argments via ps aux | grep kubelet. For me, it's:
> ```
> /usr/bin/kubelet --kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=100.64.0.10 --cluster-domain=cluster.local --v=4
> ```

🎉  after trying to get `kubeadm` running successfully, changing my systemd unit file from the default of:
```
ExecStart=/usr/bin/kubelet
```

to the cmdline specified above:

```
ExecStart=/usr/bin/kubelet --kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=100.64.0.10 --cluster-domain=cluster.local --v=4
```

got things going!  It might be worthwhile to update either the Xenial packages or [the documentation](http://kubernetes.io/docs/getting-started-guides/kubeadm/) to reflect this.

❤️ for all the work the kubernetes team puts into these tools.
