### ISSUE TITLE
bulk service or endpoint operations are computationally expsensive 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#33693]
**Problem Statement:**
During controlled standup and teardown of services or endpoints, the nodes can enter into computationally expensive loop where iptables refreshes eat a substantial amount of cpu.  

**Use Case:** 
For benchmarking and performance analysis we use a tool which loads the cluster in an aggressive fashion leveraging several concurrent submissions of well defined templates.  During this load we have seen the openshift-node(kubelet+proxy) eating a large amount of cpu for extended periods of time.  In our experiments our nodes are small, so they will often stay peg'd at 100% cpu utilization (hot sand), even though the workload is pause containers.  

**Proposed Solutions:** 
- Time window iptables refreshes.  
  - Pro: Decrease refreshes 
  - Con: Still broadcasting to all nodes
- Bulk time-windowed updates to services/endpoints
  - Pro: Amortizes the cost of the update to the cluster through decreased watch + iptables refreshes 
  - Con: Bulk operations don't exist in the api.  

/cc @thockin @danwinship @smarterclayton @eparis @wojtek-t @gmarek 

xref: https://bugzilla.redhat.com/show_bug.cgi?id=1371971#c4

**Comment by thockin** [comment]
On Wed, Sep 28, 2016 at 2:38 PM, Timothy St. Clair
<notifications@github.com> wrote:
>
> ** Problem Statement: **
> During controlled standup and teardown of services or endpoints, the nodes can enter into computationally expensive loop where iptables refreshes eat a substantial amount of cpu.

I have tried and failed to reproduce this

> ** Use Case: **
> For benchmarking and performance analysis we use a tool which loads the cluster in an aggressive fashion leveraging several concurrent submissions of well defined templates. During this load we have seen the openshift-node(kubelet+proxy) eating a large amount of cpu for extended periods of time. In our experiments our nodes are small, so they will often stay peg'd at 100% cpu utilization (hot sand), even though the workload is pause containers.
>
> ** Proposed solutions: **
>
> Time window iptables refreshes.
>
> Pro: Decrease refreshes
> Con: Still broadcasting to all nodes

https://github.com/kubernetes/kubernetes/issues/31631

**Comment by timothysc** [comment]
We can reproduce this every time using our test tools when loading 5k projects across 500 nodes using template loader (https://github.com/openshift/svt/blob/master/openshift_scalability/config/pyconfigMasterVirtScalePause.yaml) at a rate of 10 concurrent loads at a time.

**Comment by smarterclayton** [comment]
Is there a way we can get the cpuprofile from one of these periods?

On Wed, Sep 28, 2016 at 6:29 PM, Timothy St. Clair <notifications@github.com

**Comment by smarterclayton** [comment]
Of the node

**Comment by timothysc** [comment]
yes, we can collect it during the run.  

/cc @mffiedler

**Comment by thockin** [comment]
@matchstick

On Wed, Sep 28, 2016 at 3:49 PM, Timothy St. Clair <notifications@github.com

**Comment by smarterclayton** [comment]
So two things on the node are showing up during the high CPU period - cumulative GC time is 50% (indicating hot looping with allocations) and below I see the following cumulative counts.

```
     0.03s 0.084% 88.11%      5.52s 15.48%  github.com/openshift/origin/vendor/github.com/gogo/protobuf/proto.CompactTextString
     0.04s  0.11% 86.85%      8.34s 23.38%  github.com/openshift/origin/vendor/github.com/davecgh/go-spew/spew.(*dumpState).dumpSlice
     0.02s 0.056% 88.51%      9.59s 26.89%  github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/proxy/config.(*endpointsStore).Merge
```

Neither spew now CompactTextString should be in these outputs, which means we are probably completely CPU bound on the logging output.  Spew in particular is extremely inefficient in terms of allocations, so I can probably say that we need to not be logging whatever is being logged (either by in the runs turning down logging, or more likely making that logging be at a much higher level and ensuring we are not calling early into it).  I see Spew in proxy config at V(5) - I don't think that's a level that should be on during perf runs (I would say 2 or 3 would be the highest I would answer performance issues on).

Can you guys turn logging down to 2 or 3 and rerun?

**Comment by mffiedler** [comment]
@smarterclayton I will re-run.   Re-setting that particular env right now but should be able to repro on a smaller one.

**Comment by mffiedler** [comment]
@smarterclayton  I re-checked the cluster the issue was reported on and it was already at loglevel=2 for the cpuprofiles you have:

/usr/bin/openshift start node --config=/etc/origin/node/node-config.yaml --loglevel=2

Going to recreate in a smaller env anyways to make this investigation easier.

**Comment by smarterclayton** [comment]
Can you look at the journal on those machines and find the largest output
line you see?  Any excessive detail?

From the cumulative run I don't see Sdump invoked in the proxier at
anything less than v4.  It *is* invoked from strategicpatch on an yaml
marshal error, but unless you're seeing gobs of errors in the logs that's
unlikely.  Every other use is tests.

**Comment by timothysc** [comment]
We have a weird sampling problem with the tooling too, so we're definitely getting large spikes in updating iptables, but I'm not sure it will register except for maybe in pid_stat data.

**Comment by mffiedler** [comment]
Sample node logs are included in the doc for a different issue:  https://bugzilla.redhat.com/show_bug.cgi?id=1380455

pidstat data for the longer runs is not very good - way too many short iptables-save/iptables-restores.  swamps the samples.   Will need to do a shorter run.   I will coordinate that.

**Comment by timothysc** [comment]
reopening, b/c we reverted and I need to cleanup that fixed PR.

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by wojtek-t** [comment]
During 1.7 we significantly improved iptables. In particular:
1. introduced throttling on how often we run iptables-restore and iptables-save commands
2. changed the model of how watches are handled (this is now really event-based)
3 reduced number of allocations in kube-proxy by ~10-12x

In particular we fixed all issues mentioned in https://github.com/kubernetes/kubernetes/issues/33693#issuecomment-250547429

I'm closing this one - if we need further improvements we can open a separate issue
