### ISSUE TITLE
kubeadm: create and migrate api/types.go to a componentconfig api

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#33715]
@kubernetes/sig-cluster-lifecycle

**Comment by luxas** [comment]
What's left to do here?

Including the control planes' componentconfig in the kubeadm componentconfig API I suppose?

**Comment by mikedanese** [comment]
I think this is basically done

**Comment by luxas** [comment]
@mikedanese What about including the control planes' componentconfig in the kubeadm componentconfig?
 
I think that would be quite crucial in order to make it possible to customize apiserver, cm, scheduler and proxy arguments

@mikedanese Will you work on it?

**Comment by mikedanese** [comment]
We need to finish componentconfig for other components. I think that's a seperate issue that already has issues open on it. I'm not currently working on it.

**Comment by errordeveloper** [comment]
Mike, I've been trying to trace down current WIP, but couldn't find much,
any pointers would help!

**Comment by mikedanese** [comment]
There's an effort per component. For example: https://github.com/kubernetes/kubernetes/pull/34727 for kube-proxy. The umbrella issue is https://github.com/kubernetes/kubernetes/issues/12245
