### ISSUE TITLE
Remove deprecated alpha for volume provisioning, if we're happy with Beta

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#33717]

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @thockin

**Comment by jsafrane** [comment]
IMO, we should keep the alpha behavior as it is in 1.5. Once we have a default storage class deployed during installation (=1.6), we can remove it and most users won't see any difference - alpha annotation on a PVC will be ignored and the default storage class will be used to provision a volume for the PVC.

**Comment by dims** [comment]
@jsafrane sounds like we punt it to v1.6 marking as such

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect. Also close if finished.

**Comment by jsafrane** [comment]
I think it was removed in https://github.com/kubernetes/kubernetes/pull/44090 (heading to 1.7)
