### ISSUE TITLE
no API token found for service account default/default, retry after the token is automatically created and added to the service account

### ISSUE THREAD

**Issue by gowrisankar22** [kubernetes/kubernetes#33714]
Hi,
I am getting below issue when i am creating a pod ,
link which i am following:
server which i am using is rethat7.2
http://severalnines.com/blog/installing-kubernetes-cluster-minions-centos7-manage-pods-services

Error from server: error when creating "mysql.yaml": pods "mysql" is forbidden: no API token found for service account default/default, retry after the token is automatically created and added to the service account

[root@XXXX pods]# kubectl --namespace=kube-system describe serviceaccount default
Error from server: serviceaccounts "default" not found

Can you help how to fix this up?

api server  -> vi /etc/kubernetes/apiserver (anything i need to add?)

KUBE_API_ADDRESS="--insecure-bind-address=0.0.0.0"

KUBE_API_PORT="--port=8080"

KUBELET_PORT="--kubelet-port=10250"

KUBE_ETCD_SERVERS="--etcd-servers=http://127.0.0.1:2379"

KUBE_SERVICE_ADDRESSES="--service-cluster-ip-range=10.254.0.0/16"

KUBE_ADMISSION_CONTROL="--admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,ServiceAccount,ResourceQuota"

KUBE_API_ARGS=""

BRs ,Gowrisankar

**Comment by markxyl** [comment]
I got the same problem,and I solve it as I disable the "KUBE_ADMISSION_CONTROL="

**Comment by FrankYu** [comment]
same here, with kubernetes-1.4.0-0.1.git87d9d8d.el7.x86_64 on centos7.3

**Comment by rgolangh** [comment]
Got the same thing on k8 1.6.7 on fedora 26.
Blanking the admission control like mentioned by @bijujo  fixes the problem.

**Comment by discordianfish** [comment]
Just ran into the same issue with 1.7.3 and bootkube generated but heavily modified manifests. Not sure though if I did something wrong but removing the admission-control flag from apiserver solves this for me.

**Comment by vinayk06** [comment]
Ran into same issue several times in v1.5.6_coreos.0 when deploying helm charts from Jenkins. 
curious: @discordianfish @rgolangh @FrankYu  @all how are you deploying pods? I mean using Helm charts, just yaml, compose....  are you trying to using Jenkins/Teamcity like tools?

**Comment by rgolangh** [comment]
@vinayk06 deploying using yaml so it should be the lowest, besides 'run' that you can get. What happens when you `kubectl run`?

**Comment by vinayk06** [comment]
@rgolangh  I was using helm charts with Jenkins triggered jobs.

**Comment by liggitt** [comment]
to use service accounts, the apiserver must be started with the ServiceAccount admission plugin and the service account token public key, and the controller manager must be started with the service account token signing key - see https://kubernetes.io/docs/admin/service-accounts-admin/

**Comment by lowang-bh** [comment]
change  
KUBE_ADMISSION_CONTROL="--admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota"
to KUBE_ADMISSION_CONTROL=""
not KUBE_ADMISSION_CONTROL="

**Comment by mecifi** [comment]
Just to summarize the solution cleanly:

edit /etc/kubernetes/apiserver

comment out (add #) this line:
`# KUBE_ADMISSION_CONTROL="--admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota"`

Add this line:
`KUBE_ADMISSION_CONTROL=""`

Restart kube-apiserver for the change to take effect:
`systemctl restart kube-apiserver`

Tested on CentOS 7.5 and:
```
[root@docker kubernetes]# kubectl --version
Kubernetes v1.5.2
[root@docker kubernetes]#
```

**Comment by benyVip** [comment]
That is helpful

**Comment by YitongFeng** [comment]
> to use service accounts, the apiserver must be started with the ServiceAccount admission plugin and the service account token public key, and the controller manager must be started with the service account token signing key - see https://kubernetes.io/docs/admin/service-accounts-admin/

How to config apiserver and controller-manager? The docs are not clear. @liggitt

**Comment by ancin** [comment]
thanks。

**Comment by axozoid** [comment]
So, just removing the admission controllers and that's it? No one questioned, why do we need to do that? Isn't that better to try figure out what's happening and fix that, rather than using a workaround by disabling some functionality?

Later on, when one needs to use any of the admission controllers he will be trapped.

From what I understand, we need to make sure, that:
For **API-server**: `--service-account-key-file` is set to a _public key_;
For **controller manager**: `--service-account-private-key-file` is set to the corresponding _private key_;

@liggitt , please correct me if I'm wrong.
