### ISSUE TITLE
Switch all https://storage.googleapis.com/kubernetes-release/release URLs to https://dl.k8s.io

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#33726]
We have a new vanity url, http://dl.k8s.io/, which redirects to the GCS release bucket - e.g. http://dl.k8s.io/v1.4.0/kubernetes.tar.gz.

Right now, the https endpoint doesn't work, since dl.k8s.io isn't in the list of domains on the certificate. Once it works, we should switch all references over to the nicer vanity URL.

x-ref https://github.com/kubernetes/k8s.io/pull/15

**Comment by techtonik** [comment]
So what it required to make this issues actionable? Where to add this `dl.k8s.io` for the certificate?

**Comment by ixdy** [comment]
@techtonik the issue tracking that is https://github.com/kubernetes/k8s.io/issues/18

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @ixdy

**Comment by ixdy** [comment]
not a release blocker.

**Comment by dims** [comment]
@ixdy Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by ethernetdan** [comment]
@ixdy can this be closed?

**Comment by ixdy** [comment]
I forgot to get to this in 1.6, but it'd still be good to do.

**Comment by spiffxp** [comment]
@ixdy do you want this in v1.7? is there a sig to own this?

**Comment by ixdy** [comment]
doesn't need to block 1.7, no.
