### ISSUE TITLE
pod constantly create new contaniers

### ISSUE THREAD

**Issue by yu-yang2** [kubernetes/kubernetes#33732]
I running kubernetes cluster in containers use `hyperkube-amd64:v1.2.0`, my docker version is 1.10.3.

when I run k8s cluster using  
`docker run \ --restart=always \ --name=kubelet \ --volume=/:/rootfs:ro \ --volume=/sys:/sys:ro \ --volume=/var/lib/docker/:/var/lib/docker:rw \ --volume=/var/lib/kubelet/:/var/lib/kubelet:rw,shared \ --volume=/var/run:/var/run:rw \ --net=host \ --pid=host \ --privileged=true \ -d \ gcr.io/google_containers/hyperkube-amd64:v1.2.0 \ /hyperkube kubelet \ --containerized \ --address="0.0.0.0" \ --hostname-override="127.0.0.1" \ --api-servers=http://0.0.0.0:8080 \ --config=/etc/kubernetes/manifests \ --allow-privileged=true --v=2 \ > /dev/null`

when a  contianer start falied, the k8s pod will keeps creating new containers every serveral seconds, and after several mintutes, there will be hundreds of Exit containers, why it create so rapidly?

**Comment by jingxu97** [comment]
@yujuhong @dchen1107 do you know anyone might help work on this issue?

**Comment by xiangpengzhao** [comment]
FYI:
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy

>A PodSpec has a restartPolicy field with possible values Always, OnFailure, and Never. The default value is Always. restartPolicy applies to all Containers in the Pod. restartPolicy only refers to restarts of the Containers by the kubelet on the same node. Failed Containers that are restarted by the kubelet are restarted with an exponential back-off delay (10s, 20s, 40s …) capped at five minutes, and is reset after ten minutes of successful execution.
