### ISSUE TITLE
kubeadm should indicate progress

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33744]
It may take quite long for API server to come up, as this involves pulling Docker images in the background.

We have already discussed adding a progress bar, and it'd would be great. Also, we should consider pulling directly from kubeadm, so we can provide user with a real progress bar. Also, we could consider adding `kubeadm util pull-images` and allow alternative registries, as it would help users in air-gapped environments.

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#43
