### ISSUE TITLE
Create "big-red-stop-button.sh" script for stopping clusters

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#33749]
We need a "panic" script for stopping clusters also when they are currently being created. This is needed for the purpose of our performance testing.

It should work for at least GCE and GKE.

**Comment by wojtek-t** [comment]
I think that the first step in GCE and GKE can basically be as simple as:
- "resize to 0 (or delete)" all MIGs
It's far from being perfect but better than nothing.

**Comment by gmarek** [comment]
For GKE that's probably only thing we can do now.

**Comment by wojtek-t** [comment]
Discussed offline and it seems that for GCE it should be enough to kill the kube-up script and immediately after that start kube-down. Which we already have.

**Comment by gmarek** [comment]
But we still need to for GKE. I'll try to hack something today.
