### ISSUE TITLE
hack/verify-codegen.sh should fail if openapi model is not generated correctly

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes#33751]
Right now on head (24031f50d6610dc9f695398893d3e6459957ee6e) if you run 

```
make generated_code
```

it will end up having a modified pkg/generated/openapi/zz_generated.openapi.go file. This happened because some type has been changed and this file should have been generated before commit, and verification should have failed but they didn't.

**Comment by mbohlool** [comment]
This is not only a problem with openapi-gen. deepcopy-gen also has the same problem. I've added a field to a type (autoscaling/v1) and verify-all passed for the commit (without adding generated code to it). those files will be generated on verify-codegen and it will not fail and the commit can be merged without generated code.

**Comment by thockin** [comment]
Yeah.  So when the Makefile stuff originally went in those files were not checked in.  Then we un-did that part, but I didn't re-add them to verify...
