### ISSUE TITLE
OpenStack LBaaS V2 driver deletes all Pools and Monitors when any single service is deleted

### ISSUE THREAD

**Issue by kiall** [kubernetes/kubernetes#33759]
**Kubernetes version**:

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.8-hpe.1", GitCommit:"2b6b6624aaad1c72670ca9082927c21a79e6e3d6", GitTreeState:"clean", BuildDate:"2016-09-22T23:27:29Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.8-hpe.1.3+61e22370dca123-dirty", GitCommit:"61e22370dca123a1a557e8a24710d3bf71f83262", GitTreeState:"dirty", BuildDate:"2016-09-29T14:43:35Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:

OpenStack Liberty, Neutron LBaaS V2 using Octavia
- **OS** (e.g. from /etc/os-release):

N/A
- **Kernel** (e.g. `uname -a`):

N/A
- **Install tools**:

N/A
- **Others**:

N/A

**What happened**:

Deleting a LoadBalancer service results in the deletion of all LoadBalancer service's LBaaS Pools and Monitors.

**What you expected to happen**:

The Pools and Monitors for unrelated services should not be deleted

**How to reproduce it** (as minimally and precisely as possible):
1. Create 2 services with type=LoadBalancer
2. Wait for LBaaS resources to be created
3. Delete 1 of the 2 services created earlier
4. Inspect `neutron lbaas-pool-list` output, all pools will have been deleted.

**Anything else do we need to know**:

Neutron's API ignores unknown paramaters. When listing pools etc, K8 attempts to filter on "LoadBalancerID", which is not a valid filter. As such, it is ignored by Neutron, and a list of all pools is returned. K8 then proceeds to delete each of the pools.

**Comment by mmontecelo-gradiant** [comment]
We're still experiencing this problem, or at least one with very similar symptoms -- having launched services of type LoadBalancer and then deleting one of them, it deletes all of the pools of all services.

As the original report, we're also using OpenStack Liberty, Neutron LBaaS V2, and just updated to K8s 1.5.1 (from 1.4.5) hoping that this fixed our issue, but we are still experiencing the same problem after the upgrade.

Is there any other way in which we can help to debug the issue, without delving into the code?

(On a side note, the commit which is supposed to fix this is included as part of the 1.5.0 release, so I am not sure if this issue has not been closed for some reason).

**Comment by kiall** [comment]
@mmontecelo-gradiant it is possible I missed a case in the original fix, the simplest test I found for this issue we had was to create 2x services with type=loadbalancer, wait for all the LBaaS resources to be provisioned, then delete one of the services and ensure the other's resources are still present.

If this is failing, either these been a regression, or something else has gone horribly wrong :)

**Comment by mmontecelo-gradiant** [comment]
Hi @kiall, thanks for coming back to this issue.

Apparently not all cases deleting the LoadBalancers in OpenStack/liberty were doing the extra step of filtering.  We were working on a fix, and @daconstenla submitted a pull request, which is being considered right now: https://github.com/kubernetes/kubernetes/pull/38959

**Comment by dims** [comment]
https://github.com/kubernetes/kubernetes/pull/38959 has merged. closing this issue

/close
