### ISSUE TITLE
Find rolling-updates replacement for GCE upgrades.

### ISSUE THREAD

**Issue by maisem** [kubernetes/kubernetes#33764]
`gcloud alpha compute rolling-updates` is being deprecated and we need to find a replacement for GCE upgrade.

https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/upgrade.sh#L257

cc @fabioy @roberthbailey

**Comment by roberthbailey** [comment]
We now use `gcloud compute instance-groups managed recreate-instances` in the upgrade script.
