### ISSUE TITLE
fix `gcloud docker` commands

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#33765]
Just saw this warning today:
```
gcloud docker push gcr.io/kubernetes-scale/kubemark
WARNING: The '--' argument must be specified between gcloud specific args on the left and IMPLEMENTATION-ARGS on the right. IMPORTANT: previously, commands allowed the omission of the --, and unparsed arguments were treated as implementation args. This usage is being deprecated and will be removed in March 2017.
This will be strictly enforced in March 2017. Use 'gcloud beta docker' to see new behavior.
```

Not sure if this is only limited to kubemark, or if there are other places we need to fix, too.

**Comment by angadn** [comment]
Sorry if this sounds stupid, but as expected, `gcloud docker -- push gcr.io/kubernetes-scale/kubemark` won't show this warning - what needs to be fixed here?

**Comment by ixdy** [comment]
@angadn we have a bunch of scripts and Makefiles which are omitting the `--` currently. We need to fix these by adding the missing `--`s.
