### ISSUE TITLE
Volume attached/detached info out of sync at master when node is terminated.

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#33760]
## User reported issue:

When AWS nodes are terminated and then later replaced by AWS cluster, some pods are found mounted to the wrong volumes.
## Problem analysis:

The cause of this issue is that when nodes are terminated, volumes are detached without noticed by the volume manager.
In current design, master is responsible for attaching/detaching volumes. After the operation attach/detach finishes, volume controller will cache this information (which volume is attached to a node) into actual state of world. The reconciler then periodically compares actual state and desired state to trigger attach/detach if needed. However, the cached actual state might be out of sync in case
Node is terminated so that the volume is also detached.
User explicitly detach the volume from the node

When the above events happen, the controller is not aware that volume is already detached and of course the device path is no longer valid. So the actual state will not change and reconciler continue to think the volume is still attached to the node with the old device path. On node side, if kubelet happens to mount the volume, it will use the wrong device path which might belong to other volumes. The following describes the sequence of events that could cause AWS mounting to wrong volume issue
1. An AWS volume is attached to node on device path (/dev/path1) by master and kubelet mount the volume on the path.
2. Node is terminated (volume will be also detached by AWS) or user explicitly detach the volume to node, master will try evicts the pods from the node after detecting node is not responding.
3. At master, reconciler tries to detach the volume since pods are deleted. However, it won’t trigger detach for a while because the node status shows that the volume is still mounted by kubelet (Note: kubelet periodically updates which volumes are mounted to node status. When kubelet dies, the status will not be changed for a while). So at this moment, master thinks the volume is still attached to the node on a /dev/path1, but it is no longer true.
4. Node is rebooted, the master create some pods on the same node. At the node, kubelet tries to check whether the volume still attached to the node before trigger mounting operation. Because of step 3, since master still thinks volume is attached to /dev/path1, kubelet will use /dev/path1 to mount this volume. However /dev/path1 could be used by other AWS volumes after it is freed up by step 3. After mounting, the pod will get wrong volume.
### Why this issue only happens on AWS cluster, not GCE?

AWS dynamically assign devices to attached volumes. Once detached, the device is become available and might be assigned to other attached volumes immediately. Since the attached volume information is cached in master, if volume is detached without proper triggering detach volume operation through master, the cached information will be stale and cause kubelet mount to the wrong device. 
For GCE cluster, GCE only uses a fixed device path for each volume using their pd names and the device path will not be assigned to other volumes. Since a device path is statically mapped to the volume so it won’t cause the above mounting to wrong volume problem. But stale information might still problems. For example, a volume is attached to a node. After the node is terminated and restarted, master still thinks the volume is attached in actual state, and will not try to attach it ever again. 
## Proposal:

To solve this problem, I proposed the following two fixes on volume controller and AWS attacher respectively. 
On Master, a sync state process will be added to periodically check whether the cached attached volume in actual state is actually still attached. Cloud providers such gce, aws have the functions to check whether the volume is attached to the node (instance). To avoid putting high number of requests to cloud provider, batch operation to check a list of volumes will be issued per node instead of one request per volume. Currently I proposal to check which disks are attached on a node every 1-3 second. The checking will be asynchronous (with a go routine per node).  
On AWS attacher, when assigning devices to volumes, propose to use random selection instead of using alphabet order. In this way, the chance the same device will be reused immediately will be highly reduced. 
### Verify the proposal

Potential race condition between periodic state sync up and other volume operations?
Volume operations (attach/detach) and state sync up (check volume still attached or not) are all asynchronous (each operation uses a go routine). With operation executor, Attach/Detach operations on the same volume is serialized to avoid race condition during attach/detach operations and updating actual states. State sync up operation is checking a list of volumes through cloud provider to see whether they are still attached. It has three steps
1. Retrieve a list of volumes for each node
2. Make a request to cloud provider to get the attached volumes of each node
3. Update states if any volumes to check is no longer attached according to b

During this checking, attach or detach operations might be going on and interleave with the above steps. Considering the following scenarios
- After check the volume is not attached, an attach operation finishes and mark volume is attached in actual state, but the check will mark back the volume as detached. The result is that volume is already attached, but actual state records it is not. The reconciler will correct this situation by issuing another attach operation and update the state. (Interleaving detach operation should not affect anything)
- After check the volume is attached, an detach operation finishes and update the state. The sync process will not change anything which cause no problem. (Interleaving attach operation has no effect)
### Will the proposed approach solve the problem completely?

No. Detach/attach might happen at any moment. On AWS, if user manually detach and attach volumes very quickly, the mounted path will be changed and master will not catch this change right now. But with above fixes 1 and 2, the chances of mounting to the wrong volume should be much lower. Node termination and reboot will take normally much longer time and periodic updates every few second should be sufficient to catch the change.
## Performance overhead

The added overhead for this change is to periodically send requests to cloud provider to get the instance information. It would be one request for node. So the overhead would be proportional to the number of the nodes in the cluster. Will work on some scalability tests to cover this issue.

**Comment by jingxu97** [comment]
@kubernetes/sig-storage

**Comment by jingxu97** [comment]
This problem described in this PR also fix the issues in #29903. Although the problems are different but the root cause and the fix are the same

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @jingxu97

**Comment by jingxu97** [comment]
@dims, this fix for this is already in #34859. Close it now

**Comment by gnufied** [comment]
@jingxu97 @justinsb I think this issue and related PR makes incorrect assumptions about behaviour of AWS/EBS and hence I am not sure the reconciler resync mechanism is needed at least in AWS. 


For example - the issues says, "If node is terminated and then rebooted then volumes are detached from node". This is not true - because if node was terminated, we can't reboot it.

But suppose, we were simply rebooting the node - in that case volume remains attached to the node and don't get detached and hence again no reconcillation on controller-manager's part is necessary. If Node was shutdown(for awhile) then the node is removed from node's list and all pods from it are migrated and that works as well because we have 6 minute time window that performs detaches anyways.
