### ISSUE TITLE
summary_test.go fails to compile - constant overflows int

### ISSUE THREAD

**Issue by gavinB-orange** [kubernetes/kubernetes#33761]
Bug report.

**Kubernetes version** (use `kubectl version`):

Build of master branch
commit 50e12ff5a2e14f5c7c348cf87f5a1dbf1b790fb2

**Environment**:

Ubuntu 16.04, 24GB memory, 8 cores (parallel compilation used as > 11GB memory)

Linux gbhc1 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**What happened**:

Following the build-from-source directions, I cloned kubernetes; cd &lt;dir&gt;; make release

This fails with : 

+++ [0929 09:16:04] linux/amd64: go build started
+++ [0929 09:17:42] linux/amd64: go build finished
+++ [0929 09:16:04] linux/arm: go build started
 # k8s.io/kubernetes/test/e2e_node
test/e2e_node/summary_test.go:57: constant 100000000000 overflows int
test/e2e_node/summary_test.go:157: constant 100000000000 overflows int
test/e2e_node/summary_test.go:158: constant 10000000000 overflows int
test/e2e_node/summary_test.go:159: constant 10000000000 overflows int
test/e2e_node/summary_test.go:167: constant 100000000000 overflows int
test/e2e_node/summary_test.go:169: constant 10000000000 overflows int
test/e2e_node/summary_test.go:175: constant 10000000000 overflows int
test/e2e_node/summary_test.go:183: constant 10000000000 overflows int
+++ [0929 09:16:04] linux/arm64: go build started
+++ [0929 09:18:06] linux/arm64: go build finished
Makefile:79: recipe for target 'all' failed
make[1]: *** [all] Error 1
Makefile:255: recipe for target 'cross' failed
make: *** [cross] Error 1
Makefile:239: recipe for target 'release' failed
make: *** [release] Error 1

**What you expected to happen**:

A successful build

**How to reproduce it** (as minimally and precisely as possible):

make release

**Anything else do we need to know**:

gavin@gbhc1:~/work/kubernetes/kubernetes/test/e2e_node$ awk '(NR==57 || NR==157 || NR==158 || NR==159 || NR==167 || NR==169 || BR==175 || NR==183) {print}' < ./summary_test.go
			fsCapacityBounds := bounded(100*mb, 100*gb)
						"AvailableBytes":  bounded(100*mb, 100*gb),
						"UsageBytes":      bounded(10*mb, 10*gb),
						"WorkingSetBytes": bounded(10*mb, 10*gb),
						"RxBytes":  bounded(1*mb, 100*gb),
						"TxBytes":  bounded(10*kb, 10*gb),
							"UsedBytes":      bounded(kb, 10*gb),

**Comment by ixdy** [comment]
@dchen1107 can you look into this build failure please?

**Comment by ixdy** [comment]
oh, this was broken by a PR that went in yesterday, #29479.
