### ISSUE TITLE
kube-controller-manager fails to remove extra pods from a deployment

### ISSUE THREAD

**Issue by mikebryant** [kubernetes/kubernetes#33770]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): "more than its spec" "is invalid"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0+coreos.0", GitCommit:"278a1f7034bdba61cba443722647da1a8204a6fc", GitTreeState:"clean", BuildDate:"2016-09-26T20:48:37Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS 1122.2.0
- **Kernel** (e.g. `uname -a`): 4.7.0-coreos
- **Install tools**: bootkube
- **Others**:

**What happened**:
I've got 4 copies of pods for several deployments, though the replicas field is set to 3

```
NAME                                      READY     STATUS    RESTARTS   AGE
kube-controller-manager-237587340-epcni   1/1       Running   2          10h
kube-controller-manager-237587340-gtxil   1/1       Running   21         1d
kube-controller-manager-237587340-i396r   1/1       Running   2          2h
kube-controller-manager-237587340-u553o   1/1       Running   4          6h
```

**What you expected to happen**:
For it to only have 3 pods

**How to reproduce it** (as minimally and precisely as possible):
Unknown

**Anything else do we need to know**:
Deployment, pods, and logs attached

[logs.txt](https://github.com/kubernetes/kubernetes/files/501273/logs.txt)
[pods.yaml.txt](https://github.com/kubernetes/kubernetes/files/501276/pods.yaml.txt)
[deployment.yaml.txt](https://github.com/kubernetes/kubernetes/files/501275/deployment.yaml.txt)

**Comment by janetkuo** [comment]
@mikebryant did you recently scaled down the deployment? We may need to cherrypick https://github.com/kubernetes/kubernetes/pull/34456 into 1.4 cc @kargakis

**Comment by kargakis** [comment]
@janetkuo agreed, I will open a PR with the pick

**Comment by janetkuo** [comment]
This should be fixed. If not, please reopen
