### ISSUE TITLE
HPA Docs are wrong and causing user confusion

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#33776]
See #32768

This doc users the wrong apiVersion:
http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/walkthrough/

@davidopp Are you the right person for HPA?

**Comment by davidopp** [comment]
@jszczepkowski @piosz

**Comment by tonglil** [comment]
Any way I can contribute to this and fix the docs?

This bit me today, so I am happy to do so.

**Comment by fgrzadkowski** [comment]
Upgrading HPA to GA was done by @piosz. Can you please fix the doc?

@tonglil It'd be great if you could send a PR with a fix. It's explained in the linked issue what has to be fixed.

**Comment by tonglil** [comment]
Looks like someone already beat me to the punch: https://github.com/kubernetes/kubernetes.github.io/pull/1356.

**Comment by piosz** [comment]
Apologies for the problem. This was supposed to be updated in 1.3, when we changed the default from `extensions/v1beta1` to `autoscaling/v1`.

**Comment by jszczepkowski** [comment]
Fixed by https://github.com/kubernetes/kubernetes.github.io/pull/1356
