### ISSUE TITLE
kubectl: auth failures on discovery give confusing message

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#33797]
`kubectl` often says something like this when the problem is your authentication token: `failed to negotiate an api version; server supports: map[], client supports: map[v1:{} batch/v1:{} componentconfig/v1alpha1:{}...`

Kubectl should detect the 401 and report a auth error, not this discovery error.

**Comment by zreigz** [comment]
I can work on this. 
@caesarxuchao is it fine for you ?

**Comment by caesarxuchao** [comment]
Sure. I'm not working on it. Github does not let me assign it to you, maybe I can do that after you send a PR.

**Comment by zreigz** [comment]
@lavalamp Can you give me more details how to reproduce it. When my authentication token is invalid I receive only this error: `error: You must be logged in to the server (the server has asked for the client to provide credentials)`

**Comment by caesarxuchao** [comment]
lavalamp is OOO this month. Unfortunately, I don't know how to reproduce the error. Let me know if you want to work on other bugs.

**Comment by zreigz** [comment]
Yes sure if you have something  I can take it

**Comment by zreigz** [comment]
I think someone already have been working on this: https://github.com/kubernetes/kubernetes/pull/27066

**Comment by lavalamp** [comment]
Looks like this is a dup of #26909
