### ISSUE TITLE
Compile darwin binaries with go 1.7.1 so they stop segfaulting

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#33801]
See #32999

**Comment by ixdy** [comment]
CI has built and uploaded unofficial prerelease darwin `kubectl` binaries for 1.4 using go1.7.1:

http://dl.k8s.io/ci/v1.4.1-beta.0.18+a3651952b7abbf/bin/darwin/386/kubectl
```
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.1-beta.0.18+a3651952b7abbf", GitCommit:"a3651952b7abbf209beafa23e548cdf8fa7be139", GitTreeState:"clean", BuildDate:"2016-10-01T02:46:23Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/386"}
```

http://dl.k8s.io/ci/v1.4.1-beta.0.18+a3651952b7abbf/bin/darwin/amd64/kubectl
```
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.1-beta.0.18+a3651952b7abbf", GitCommit:"a3651952b7abbf209beafa23e548cdf8fa7be139", GitTreeState:"clean", BuildDate:"2016-10-01T02:46:23Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
```

cc @luxas @pwittrock @david-mcmahon @liggitt @smarterclayton @jessfraz @Starefossen @gerred

Official binaries will ship as soon as we cut 1.4.1.

**Comment by ixdy** [comment]
We have official v1.4.1 `kubectl` binaries available now, too.

http://dl.k8s.io/release/v1.4.1/bin/darwin/386/kubectl
http://dl.k8s.io/release/v1.4.1/bin/darwin/amd64/kubectl

**Comment by Starefossen** [comment]
Hooray 🎉😄
