### ISSUE TITLE
AWS - Split Source/Destination check modification from route creation

### ISSUE THREAD

**Issue by carsonoid** [kubernetes/kubernetes#33805]
**Kubernetes version** 

1.4.0

**Environment**:

AWS

**What happened**:

When using calico in AWS I effectively disabled the cloud route creation by untagging my route table.

However it turns out that disabling the source/destination check for aws instances is _only_ done [when kube-controller-manager is managing routes](https://github.com/kubernetes/kubernetes/blob/release-1.4/pkg/cloudprovider/providers/aws/aws_routes.go#L118-L123)

**What you expected to happen**:

It should be possible to continue to use the controller to disable source/destination checks without having it manage the routes themselves

**How to reproduce it** (as minimally and precisely as possible):

Bootstrap an aws cluster and disable cloud route management. Source/Destination disabling will also be turned off.

**Comment by justinsb** [comment]
I think that's probably the role of the network plugin i.e. calico.  If a plugin needs a special configuration option, it should set it.

**Comment by carsonoid** [comment]
Maybe, except that plugins at the node level probably shouldn't have access to modify ec2 instances which is what would be required to have calico manage this attribute.

**Comment by carsonoid** [comment]
Sorry, ignore the a accidental issue closure.

**Comment by carsonoid** [comment]
@kubernetes/sig-aws-misc

**Comment by carsonoid** [comment]
This issue can actually be closed since the inclusion of the `--controllers` option which allows me to disable the `route` controller and leave the rest on. Related Commit: https://github.com/kubernetes/kubernetes/commit/d9b75ed82bf5b80716d9d1c4682a725b165314b3
