### ISSUE TITLE
Ansible playbook implementing http://kubernetes.io/docs/getting-started-guides/kubeadm/

### ISSUE THREAD

**Issue by dcj** [kubernetes/kubernetes#33812]
RFE: Link to implementations of this procedure.

Here is one:  https://github.com/dcj/ansible-kubeadm-cluster

@kubernetes/sig-cluster-lifecycle

**Comment by errordeveloper** [comment]
@dcj thanks a lot, could you please open a PR to https://github.com/kubernetes/kubernetes.github.io/?

**Comment by luxas** [comment]
Thanks for the information, but it seems like this is no real issue, so I'm closing it
