### ISSUE TITLE
Question: Does Kubernetes API support multiple resources configurations?

### ISSUE THREAD

**Issue by zhang8473** [kubernetes/kubernetes#33814]
I see that kubectl supports multiple resources in one configuration file.

The webpage is http://kubernetes.io/docs/user-guide/managing-deployments/

However, I do not see any Kuber API path supports it? I missed something or it does not exist or it is in planning???

**Comment by pwittrock** [comment]
>
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
