### ISSUE TITLE
printEventList is only used for watch-only and not for get event list

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes#33817]
This issue is filed as a result of investigation done on [29838](https://github.com/kubernetes/kubernetes/issues/29838) and the subsequent PR [33010](https://github.com/kubernetes/kubernetes/pull/33010)

The main summary of this issue is that the function `printEventList` defined in  `k8s.io/kubernetes/pkg/kubectl/resource_printer.go` is not being used in any path except in one path for the watching for events. I think similar behavior is there for all printXXXList functions. This issue is an attempt to figure out if this was the intended behavior and if not cleanup the code. Its more of an design review bug.

Here is some notes and observation from that investigation:-

1: sorting of events across different resources can be achieved using the command `kubectl get events --sort-by='{.lastTimestamp}'` otherwise they are all mixed up

2: doing `kubectl get events` would show up events in mixed order across all resources(tested with pods). This should show events in sorted order by default, since when events from different resources are shown, the user is only interested in the latest events or events in chronological order. Per resource events are anyways shown in `kubectl describe`

3:k8s.io/kubernetes/pkg/kubectl/resource_printer.go has handlers for different kinds of objects

func (h *HumanReadablePrinter) addDefaultHandlers() {
....
  h.Handler(eventColumns, printEvent)
 h.Handler(eventColumns, printEventList)
but when i tried to print the stack trace, i only see printEvent being called, and printEventList is not used at all, even though i see the kubectl getting a response with api.EventList object.

Here is a sample stack trace for kubectl get events

```
goroutine 1 [running]:
runtime/debug.Stack(0x6, 0xc4201e1c00, 0x252a720)
    /usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
    /usr/local/go/src/runtime/debug/stack.go:16 +0x22
k8s.io/kubernetes/pkg/kubectl.printEvent(0xc4205eb5e8, 0x24e7e80, 0xc4204d8800, 0x0, 0x0, 0x0, 0x25575d8, 0x0, 0x0, 0x0, ...)
    /Users/mayank.kumar/src/golang/src/k8s.io/kubernetes/pkg/kubectl/resource_printer.go:1594 +0x42
reflect.Value.call(0x171f0c0, 0x1a43480, 0x13, 0x1945ebb, 0x4, 0xc4205c3658, 0x3, 0x3, 0x18aee00, 0x18aee00, ...)
    /usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x171f0c0, 0x1a43480, 0x13, 0xc4205c3658, 0x3, 0x3, 0x0, 0xc4200b0f18, 0x1744a40)
    /usr/local/go/src/reflect/value.go:302 +0xa4
k8s.io/kubernetes/pkg/kubectl.(*HumanReadablePrinter).PrintObj(0xc420274a00, 0x24de8c0, 0xc4205eb5e8, 0x24e7e80, 0xc4204d8800, 0x0, 0x0)
    /Users/mayank.kumar/src/golang/src/k8s.io/kubernetes/pkg/kubectl/resource_printer.go:2237 +0x323
k8s.io/kubernetes/pkg/kubectl/cmd.RunGet(0xc4203f8360, 0x24e7a80, 0xc420086008, 0x24e7a80, 0xc420086010, 0xc4200a98c0, 0xc42037c8e0, 0x1, 0x1, 0xc420160e40, ...)
    /Users/mayank.kumar/src/golang/src/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:416 +0x131a
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdGet.func1(0xc4200a98c0, 0xc42037c8e0, 0x1, 0x1)
    /Users/mayank.kumar/src/golang/src/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:102 +0x89
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200a98c0, 0xc42037c820, 0x1, 0x1, 0xc4200a98c0, 0xc42037c820)
    /Users/mayank.kumar/src/golang/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:603 +0x439
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420406b40, 0xc42037c380, 0x1, 0x1)
    /Users/mayank.kumar/src/golang/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:689 +0x367
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420406b40, 0x24e7a40, 0xc420086000)
    /Users/mayank.kumar/src/golang/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:648 +0x2b
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
    /Users/mayank.kumar/src/golang/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:38 +0xcb
main.main()
```

Here is the corresponding kubectl http response with -v=10 debugging ,

I0904 01:48:36.314251   86778 request.go:908] Response Body: {"kind":"EventList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/namespaces/default/events","resourceVersion":"2593"},"items":[{"metadata":{"name":"my-nginx-2494149703-ce2vy.147111955b698a53","namespace":"default","selfLink":"/api/v1/namespaces/default/events/my-nginx-2494149703-ce2vy.147111955b698a53","uid":"f842f93b-7279-11e6-8686-42010a800002","resourceVersion":"2588","creationTimestamp":"2016-09-04T08:31:26Z"},"involvedObject":{"kind":"Pod","namespace":"default","name":"my-nginx-2494149703-ce2vy","uid":"f83d7533-7279-11e6-8686-42010a800002","apiVersion":"v1","resourceVersion":"2489739"},"reason":"Scheduled","message":"Successfully assigned my-nginx-2494149703-ce2vy to kubernetes-minion-group-5bdr","source":{"component":"default-scheduler"},"firstTimestamp":"2016-09-04T08:31:26Z","lastTimestamp":"2016-09-04T08:31:26Z","count":1,"type":"Normal"},{"metadata":{"name":"my-nginx-2494149703-ce2vy.147111959345d5d9","namespace":"default","selfLink":"/api/v1/namespaces/default/events/my-nginx-2494149703-ce2vy.147111959345d5d9","uid":"f8d19330-7279-11e6-8686-42010a800002","resourceVersion":"2590","creationTimestamp":"2016-09-04T08:31:27Z"},"involvedObject":{"kind":"Pod","namespace":"default","name":"my-nginx-2494149703-ce2vy","uid":"f83d7533-7279-11e6-8686-42010a800002","apiVersion":"v1","resourceVersion":"2489743","fieldPath":"spec.containers{my-nginx}"},"reason":"Pulli

4: I saw similar behavior with kubectl get pods, where although there are handlers called printPodList, they are never called.

5: the printEventList handler is never called and that is where the sorting was added as part of this PR #2948
I think that PR only solved it for kubectl describe pods, but did not solve it for kubectl get events or i am still missing something.

// Sorts and prints the EventList in a human-friendly format.
1637 func printEventList(list *api.EventList, w io.Writer, options PrintOptions) error {
1638     sort.Sort(SortableEvents(list.Items))
1639     for i := range list.Items {
1640         if err := printEvent(&list.Items[i], w, options); err != nil {
1641             return err
1642         }
1643     }
1644     return nil
1645 }
1646 
6: Someone more familiar with the framework can confirm how these printXXXList functions are supposed to be used. But for sure in the kubectl get events path, the printEventList is not being called.

7: k8s.io/kubernetes/pkg/kubectl/cmd/get.go as logic which figures if the object is ListType only for watches, but for regular flow, it breaks down the response into individual objs and then calls PrintObj on each obj(rather than calling it on the uber EventList obj), which ensures that the corresponding handlers for api.EventList will never be called even though the response was api.EventList.

8: Further investigation i found `kubectl get events --watch` is the only place printEventList is called. So indeed its  being used, but my feeling is that printEventList should be always used anytime the response is of type *api.EventList which is not the current behavior. We should unify this behavior if we can find why printEventList is not called even if the response is of type *api.EventList in the get events case but only called for watches.

**Comment by pwittrock** [comment]
@AdoHe Is this something you can take a look at?

**Comment by AdoHe** [comment]
@pwittrock sure
