### ISSUE TITLE
[ubuntu install error]client: etcd cluster is unavailable or misconfigured

### ISSUE THREAD

**Issue by zhigang** [kubernetes/kubernetes#33820]
Hey guys,
I'm having the problem when trying to start the cluster.
Kubernetes version is 1.4.0 .
How can to solve it ? Thanks.

CMD: `KUBERNETES_PROVIDER=ubuntu ./kube-up.sh`

... Starting cluster using provider: ubuntu
... calling verify-prereqs
Identity added: /home/zhigang/.ssh/id_rsa (/home/zhigang/.ssh/id_rsa)
... calling kube-up
/usr/local/develop/kubernetes/cluster/ubuntu /usr/local/develop/kubernetes/cluster
Prepare flannel 0.5.5 release ...
Prepare etcd 2.3.1 release ...
Prepare kubernetes 1.4.0 release ...
Done! All your binaries locate in kubernetes/cluster/ubuntu/binaries directory
/usr/local/develop/kubernetes/cluster

Deploying master and node on machine 192.168.11.128
make-ca-cert.sh                                                                                                                                                                                            100% 4136     4.0KB/s   00:00
easy-rsa.tar.gz                                                                                                                                                                                            100%   42KB  42.4KB/s   00:00
config-default.sh                                                                                                                                                                                          100% 5551     5.4KB/s   00:00
util.sh                                                                                                                                                                                                    100%   29KB  28.9KB/s   00:00
kube-proxy.conf                                                                                                                                                                                            100%  688     0.7KB/s   00:00
kubelet.conf                                                                                                                                                                                               100%  645     0.6KB/s   00:00
kubelet                                                                                                                                                                                                    100% 2158     2.1KB/s   00:00
kube-proxy                                                                                                                                                                                                 100% 2233     2.2KB/s   00:00
etcd.conf                                                                                                                                                                                                  100%  707     0.7KB/s   00:00
kube-apiserver.conf                                                                                                                                                                                        100%  682     0.7KB/s   00:00
kube-scheduler.conf                                                                                                                                                                                        100%  682     0.7KB/s   00:00
kube-controller-manager.conf                                                                                                                                                                               100%  761     0.7KB/s   00:00
kube-apiserver                                                                                                                                                                                             100% 2358     2.3KB/s   00:00
kube-scheduler                                                                                                                                                                                             100% 2360     2.3KB/s   00:00
kube-controller-manager                                                                                                                                                                                    100% 2672     2.6KB/s   00:00
etcd                                                                                                                                                                                                       100% 2073     2.0KB/s   00:00
reconfDocker.sh                                                                                                                                                                                            100% 2082     2.0KB/s   00:00
kube-apiserver                                                                                                                                                                                             100%  144MB  48.1MB/s   00:03
kube-scheduler                                                                                                                                                                                             100%   77MB  77.0MB/s   00:01
kube-controller-manager                                                                                                                                                                                    100%  135MB  33.6MB/s   00:04
flanneld                                                                                                                                                                                                   100%   16MB  15.8MB/s   00:01
etcd                                                                                                                                                                                                       100%   16MB  15.9MB/s   00:00
etcdctl                                                                                                                                                                                                    100%   14MB  13.7MB/s   00:00
kubelet                                                                                                                                                                                                    100%  123MB  61.4MB/s   00:02
kube-proxy                                                                                                                                                                                                 100%   69MB  34.7MB/s   00:02
flanneld                                                                                                                                                                                                   100%   16MB  15.8MB/s   00:00
flanneld.conf                                                                                                                                                                                              100%  579     0.6KB/s   00:00
flanneld                                                                                                                                                                                                   100% 2121     2.1KB/s   00:00
flanneld.conf                                                                                                                                                                                              100%  570     0.6KB/s   00:00
flanneld                                                                                                                                                                                                   100% 2131     2.1KB/s   00:00
Warning: etcd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused
error #1: dial tcp 127.0.0.1:4001: getsockopt: connection refused

Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused
error #1: dial tcp 127.0.0.1:4001: getsockopt: connection refused

Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:4001: getsockopt: connection refused
error #1: dial tcp 127.0.0.1:2379: getsockopt: connection refused

Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused
error #1: dial tcp 127.0.0.1:4001: getsockopt: connection refused

CMD: `systemctl status etcd.service`

● etcd.service - LSB: Start distrubted key/value pair service
   Loaded: loaded (/etc/init.d/etcd; bad; vendor preset: enabled)
   Active: active (exited) since Thu 2016-09-29 22:06:37 PDT; 1h 21min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1192 ExecStart=/etc/init.d/etcd start (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 512)
   Memory: 0B
      CPU: 0

Sep 29 22:06:37 ubuntu-01 systemd[1]: Starting LSB: Start distrubted key/value pair service...
Sep 29 22:06:37 ubuntu-01 etcd[1192]:  \* Starting Etcd: etcd
Sep 29 22:06:37 ubuntu-01 etcd[1192]:    ...done.
Sep 29 22:06:37 ubuntu-01 systemd[1]: Started LSB: Start distrubted key/value pair service.
Sep 29 22:06:37 ubuntu-01 etcd[1203]: error verifying flags, '>>' is not a valid flag. See 'etcd --help'.
Sep 29 22:48:23 ubuntu-01 systemd[1]: Started LSB: Start distrubted key/value pair service.
Sep 29 22:56:33 ubuntu-01 systemd[1]: Started LSB: Start distrubted key/value pair service.
Sep 29 23:21:43 ubuntu-01 systemd[1]: Started LSB: Start distrubted key/value pair service.
Warning: etcd.service changed on disk. Run 'systemctl daemon-reload' to reload units.

**Comment by adam-power** [comment]
I am having this issue as well, is there a fix?  Environment is:

`export KUBERNETES_PROVIDER=ubuntu
export nodes="ubuntu@10.236.2.42 ubuntu@10.236.2.192 ubuntu@10.236.2.224"
export roles="ai i i"
export NUM_NODES=3
export SERVICE_CLUSTER_IP_RANGE=192.168.3.0/24
export FLANNEL_NET=172.16.0.0/16
`
I also have some proxy settings set using the PROXY_SETTING variable

**Comment by zhigang** [comment]
@adam-power I got this issue on ubuntu 16.04, but this is running well on ubuntu 14.04.
May be ubuntu cluster only running well on ubuntu 14.04.
Check this out, a link for ubuntu cluster prerequisites, may be helpful to you.
[http://kubernetes.io/docs/getting-started-guides/ubuntu/](url)

**Comment by adam-power** [comment]
Unfortunately I am running 14.04

**Comment by derkoensen** [comment]
I got the problem under 16.04.
There is one line in the cluster/ubuntu/master/init_scripts/etcd under ETCD_START where there is a try to append to ETCD-Log via ">>".
Apparently Ubuntu 16.04 doesn't like this..

I just deleted that line (attention, there is the closing ") and I managed to get a etcd up and running which i can connect to via curl using the non-localhost-IP.
