### ISSUE TITLE
kubeadm/images: make registry configurable

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33828]
We should allow users to use their own private registry instead of GCR. We should also make it clear what images need to be mirrored, ideally we should implement a helper for doing pull/retag/push (i.e. `kubeadm util mirror-images`), as we have a handful of images and users will have to write scripts to do it. People will have to mirror images continuously, when we provide upgrades, so helper would be very handy.

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#47
