### ISSUE TITLE
kubernetes 1.3.8 build ERROR

### ISSUE THREAD

**Issue by onlyellow** [kubernetes/kubernetes#33824]
**Kubernetes version** 

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** 
  centos7
- **Kernel**
  3.10.0-327
- **Install tools**:
  NONE
- **Others**:

**What happened**:
# wget https://github.com/kubernetes/kubernetes/archive/v1.3.8.tar.gz
# tar -xvf v1.3.8.tar.gz
# cd kubernetes
# make release-skip-tests quick-release

KUBE_RELEASE_RUN_TESTS=n KUBE_FASTBUILD=true build/release.sh
+++ [0930 02:00:47] Verifying Prerequisites....
+++ [0930 02:01:01] Building Docker image kube-build:build-646ec4e37c.
+++ [0930 02:04:47] Running build command....
Go version: go version go1.6.2 linux/amd64
+++ [0930 02:04:59] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0930 02:05:01] Building go targets for linux/amd64:
    cmd/kube-dns
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/kubemark
    cmd/hyperkube
    federation/cmd/federation-apiserver
    federation/cmd/federation-controller-manager
    plugin/cmd/kube-scheduler
Go version: go version go1.6.2 linux/amd64
+++ [0930 02:18:45] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0930 02:18:46] Building go targets for linux/amd64:
    cmd/kubectl
Go version: go version go1.6.2 linux/amd64
+++ [0930 02:19:29] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0930 02:19:29] Building go targets for linux/amd64:
    cmd/integration
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genyaml
    cmd/mungedocs
    cmd/genswaggertypedocs
    cmd/linkcheck
    examples/k8petstore/web-server/src
    federation/cmd/genfeddocs
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
    test/e2e_node/e2e_node.test
+++ [0930 02:32:20] Placing binaries
+++ [0930 02:34:28] Running build command....
+++ [0930 02:34:46] Output directory is local.  No need to copy results out.
+++ [0930 02:34:46] Building tarball: salt
+++ [0930 02:34:46] Building tarball: manifests
+++ [0930 02:34:46] Building tarball: src
+++ [0930 02:34:46] Starting tarball: client linux-amd64
+++ [0930 02:34:46] Waiting on tarballs
+++ [0930 02:34:46] Building tarball: server linux-amd64
+++ [0930 02:35:52] Starting Docker build for image: kube-apiserver
+++ [0930 02:35:52] Starting Docker build for image: kube-controller-manager
+++ [0930 02:35:52] Starting Docker build for image: kube-scheduler
+++ [0930 02:35:52] Starting Docker build for image: kube-proxy
+++ [0930 02:35:52] Starting Docker build for image: federation-apiserver
+++ [0930 02:35:52] Starting Docker build for image: federation-controller-manager
+++ [0930 02:38:51] Deleting docker image gcr.io/google_containers/kube-scheduler:467df6af477e84d1ceaa558401c1b8c4
Untagged: gcr.io/google_containers/kube-scheduler:467df6af477e84d1ceaa558401c1b8c4
Deleted: sha256:5a31b70fc84cb8364eb4e1ac30fa86a457a49f11bdbe8aa49bad23ecf1dab375
Deleted: sha256:282632c37ce489b8ec2532492a795abed7a43d822f0e34a77d6dcd711772bb0a
+++ [0930 02:38:59] Deleting docker image gcr.io/google_containers/kube-controller-manager:469177716f89b1632a018ac94a39a6f6
Untagged: gcr.io/google_containers/kube-controller-manager:469177716f89b1632a018ac94a39a6f6
Deleted: sha256:567c47c281b5efddfeee081e00a4935781516bc0c0431fdcdd079394edde7f45
Deleted: sha256:6216013e99ea5b9875a7d3c1d0221f874f66d94aa7c1c09fcc737ce86140c266
+++ [0930 02:39:07] Deleting docker image gcr.io/google_containers/federation-controller-manager:96485a0834c4078f54b3b5c57174e092
Untagged: gcr.io/google_containers/federation-controller-manager:96485a0834c4078f54b3b5c57174e092
Deleted: sha256:87231834154606e137af4c10d710267d0638b5aaac0c3a1b561ba5b540d1ad3d
Deleted: sha256:bc0913b46f3ef2154272702f9a3b9135f5ebf7452487a63e0554702f88e5f896
+++ [0930 02:39:22] Deleting docker image gcr.io/google_containers/federation-apiserver:447862d8e9f9ada15f400424a385c00a
Untagged: gcr.io/google_containers/federation-apiserver:447862d8e9f9ada15f400424a385c00a
Deleted: sha256:6c0d458e83621fb15f9b2362b432ab00d4379bffe8851831bbc7d896d69b7a7f
Deleted: sha256:58ba453492da86fba61fc230db8baf8ffb21b9c86e2ce3ef001e6bc783d3f7f5
+++ [0930 02:39:33] Deleting docker image gcr.io/google_containers/kube-apiserver:a7877ddb2cb5c134320fdac707c18c30
Untagged: gcr.io/google_containers/kube-apiserver:a7877ddb2cb5c134320fdac707c18c30
Deleted: sha256:f534414af313473de8057bba692b6e518910eef01b7d0a4e0ab973f48ad80f8a
Deleted: sha256:dc7a4dc76f3cfec567f34dbf7b8f12e6fd271c12f652af5c9901d6e67b73e135
+++ [0930 02:39:50] Deleting docker image gcr.io/google_containers/kube-proxy:e6cb4806114232ada6115e9aac0223f1
Untagged: gcr.io/google_containers/kube-proxy:e6cb4806114232ada6115e9aac0223f1
Deleted: sha256:0c3774aa377fcbf44f1c600462bbfe9fd81cc5ef8a82ec9a682ac676a43c91c6
Deleted: sha256:54c783696e9f9dcc667f6b0c1ba3cade5a88e2d8d6497ca50634504ea483fc5f
+++ [0930 02:39:56] Docker builds done
+++ [0930 02:41:41] Building tarball: full
+++ [0930 02:41:41] Building tarball: test
**build/../build/common.sh: line 1041: KUBE_GIT_VERSION: unbound variable
!!! [0930 02:43:26] previous tarball phase failed
!!! Error in build/release.sh:719
  'return 1' exited with status 1
Call stack:
  1: build/release.sh:719 main(...)
Exiting with status 1
make: **\* [release-skip-tests] Error 1**

**What you expected to happen**:
Success to build

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by xilabao** [comment]
export KUBE_GIT_VERSION=${version}

**Comment by ixdy** [comment]
closing obsolete. please reopen if this is still affecting you.

**Comment by ishantiw** [comment]
@onlyellow I'm also facing the same issue, can you tell me how you resolved it?

**Comment by ixdy** [comment]
@ishantiw are you trying to compile kubernetes 1.3.8? or something newer?

**Comment by ishantiw** [comment]
@ixdy I think something was wrong with the version, I cloned a new one and started from scratch again and it worked, also I deleted all the data in Docker Daemon.
