### ISSUE TITLE
Feature request: ability to specify a min/max replica count on scaleable resources

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#33843]
Users have requested the ability to set local min/max replica constraints for any resource that is a target for manual scaling (i.e. Deployment / ReplicaSet / ReplicationController / Job / PetSet).  

The idea is that each spec for the related resources would have the following (similar to HPA):

```
// lower limit for the number of replicas (defaults to 0)
MinReplicas *int32 `json:"minReplicas,omitempty"`
// upper limit for the number of replicas
MaxReplicas *int32 `json:"maxReplicas,omitempty"`
```

If a user submitted a `kubectl scale` command that caused `Replicas` to fall out of the configured boundary, the request would fail validation, and not proceed.

The example use case is as follows:

> When deploying a database (pod) with no replication using persistent volumes and persistent volume claims, I want to restrict the scaling of the pod to no more than one replica.  The reason is that I don't want data distributed over various persistent stores causing fragmentation.

Keeping a min/max local to the resource may make the most sense, and is easily enforceable via validation.  I had debated a pattern using `LimitRange` but that has the drawback that the scope covered is too large.  While I am interested in adding label selectors to LimitRange to let you scope constraints to particular classes of things better, I think in this case, it may make the most sense to have min/max replicas on the local resource that is being constrained most closely.

Thoughts?

/cc @smarterclayton @eparis @bgrant0607 @lavalamp

**Comment by derekwaynecarr** [comment]
I have users that want to run Spark or a Gluster management service that have basically requested this extra level of control to set local min/max replica boundaries for their resources where they wanted to have this additional level of control to prevent operator changes to replicas.

**Comment by bgrant0607** [comment]
cc @erictune

**Comment by bgrant0607** [comment]
I am not a fan of this feature. It would add API complexity and seems cumbersome. I think there are much more important issues with the controllers that we need to tackle if we're going to spend API review bandwidth.

**Comment by derekwaynecarr** [comment]
@bgrant0607 - my response echoed your sentiment, but I got a fair amount of push-back from three distinct user communities looking to support Spark, Gluster, and a mobile application scenario.

At it's core the request is asking to have a way to prevent users from harming themselves.  User's can harm themselves any number of ways, so I get the complexity/cumbersome argument may not be worth it for all workloads.

Any objection to the concept via annotations on the objects in question, and enforcement via some optional admission controller?  If it gets broad adoption, then we could revisit when more bandwidth is needed?

**Comment by eparis** [comment]
We are running into a number of places where the dev/person who wrote the app has these restrictions, but the operator doesn't likely know. It looks to me like a dev/ops split. Allow dev to keep ops from doing things to hurt themselves.

**Comment by danmcp** [comment]
I think @eparis nailed the interaction exactly.  The application writers are often the ones applying/suggesting these limitations for the deployer/operator.  It should generally be possible for the operator to override (at a config level) separate from the scaling operation itself.

**Comment by smarterclayton** [comment]
It's usually not enough to do min/max.  We'd need to do cut outs - an etcd
pet set should probably only be allowed to exist at scales 3, 5, or 7.

**Comment by derekwaynecarr** [comment]
ack: enforcing odd numbers  is a reasonable request

**Comment by smarterclayton** [comment]
I share some of Brian's concerns as I've mentioned before.  I think this
*tends* to be more of a requirement for pet sets (which was documented in
the original proposal but is not currently in the critical implementation
path).  Ultimately the expectation that the person doing the scaling
doesn't understand what is being scaled is somewhat difficult to enforce,
even if it's not unreasonable when dealing with white box deployed software.

This most frequently comes up for things that are "stateful" - I can only
have 1 of something, but nothing prevents me from setting it to 2 or more.
I would argue the database case is best solved by PV, and the "I'm using a
PVC with RWO but based on RWM and it scales up and breaks me" case is best
solved by not allowing a PVC with RWO to be mounted in two locations (this
has been discussed under the pet set fencing and storage locking
discussion, and applies to local persistent storage and users performing in
place upgrades on the same node).

**Comment by bgrant0607** [comment]
cc @erictune

**Comment by smarterclayton** [comment]
It's not enough to do odd numbers though - 3,5,7 may be valid but
others are not.  A few systems require 3n+1.  Also, does zero count,
or is it a potential exception?

I think this is a requirement to be leveraged against petsets, not
against general resources, and should be solved there, not across all
scalable resources.

**Comment by smarterclayton** [comment]
Also, enforcing an annotation would break autoscaling, and autoscaling
a pet set should be possible, so an enforcing admission controller
needs to at least take that into account and prevent abuse / bugs /
unexpected behavior.

**Comment by smarterclayton** [comment]
A much simpler option might be a "scale protection", like the "delete
protection" we discussed previously.  An annotation which clients respect
as "the caller suggested not scaling this".  That makes this less of an API
problem than a UX problem.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @smarterclayton @derekwaynecarr

**Comment by eparis** [comment]
not blocker.

**Comment by dims** [comment]
thanks @eparis

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by lpshikhar** [comment]
Any progress on the scale selector ?

**Comment by bgrant0607** [comment]
This kind of policy should be implemented outside the workload controllers.
