### ISSUE TITLE
Add tests for the code of client config

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes#33849]
Add tests to make sure the config code lives in `pkg/client/unversioned/clientcmd` generally works for every client. I think the team owns `pkg/client` is responsible for this.
This issue was discussed in #33138 before.

**Comment by ymqytw** [comment]
@kubernetes/sig-api-machinery

**Comment by lavalamp** [comment]
What does "generally works for every client" mean?

**Comment by smarterclayton** [comment]
When I said this, I anticipated the following:

* kubectl
* kubelet
* kube-proxy
* kube-scheduler
* kube-controller-manager
* extension controllers in contrib, like ingress
* third party controllers and clients

where there may be a gap between the top 5 and the bottom 2.

**Comment by lavalamp** [comment]
I think the problem here isn't the lack of testing, but that we test stale artifacts.
