### ISSUE TITLE
Test runs leak resources in case of cluster-startup partial failure.

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#33867]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/33862/kubernetes-pull-build-test-kubemark-e2e-gce/1985/
```
Starting master and configuring firewalls
ERROR: (gcloud.compute.firewall-rules.create) Some requests did not succeed:
 - Quota 'FIREWALLS' exceeded. Limit: 150.0

Created [https://www.googleapis.com/compute/v1/projects/k8s-jkns-pr-kubemark/zones/us-central1-f/disks/k6k-e2e-agent-pr-4-0-master-pd].
NAME                            ZONE           SIZE_GB  TYPE    STATUS
k6k-e2e-agent-pr-4-0-master-pd  us-central1-f  20       pd-ssd  READY

New disks are unformatted. You must format and mount a disk before it
can be used. You can find instructions on how to do this at:

https://cloud.google.com/compute/docs/disks/add-persistent-disk#formatting

ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
 - Quota 'STATIC_ADDRESSES' exceeded. Limit: 20.0

[0;33mAttempt 1 failed to create static ip k6k-e2e-agent-pr-4-0-master-ip. Retrying.[0m
ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
 - Quota 'STATIC_ADDRESSES' exceeded. Limit: 20.0

[0;33mAttempt 2 failed to create static ip k6k-e2e-agent-pr-4-0-master-ip. Retrying.[0m
ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
 - Quota 'STATIC_ADDRESSES' exceeded. Limit: 20.0

[0;33mAttempt 3 failed to create static ip k6k-e2e-agent-pr-4-0-master-ip. Retrying.[0m
ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
 - Quota 'STATIC_ADDRESSES' exceeded. Limit: 20.0

[0;33mAttempt 4 failed to create static ip k6k-e2e-agent-pr-4-0-master-ip. Retrying.[0m
ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
 - Quota 'STATIC_ADDRESSES' exceeded. Limit: 20.0

[0;33mAttempt 5 failed to create static ip k6k-e2e-agent-pr-4-0-master-ip. Retrying.[0m
ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
 - Quota 'STATIC_ADDRESSES' exceeded. Limit: 20.0
```

/cc @wojtek-t @gmarek

**Comment by gmarek** [comment]
This is fascinating... It basically means that we're leaking some resources.

**Comment by wojtek-t** [comment]
IIUC, this was about kubemark in PR builder right?

@gmarek - did you remove leaked resources? Which ones/how many of them?

**Comment by gmarek** [comment]
I did not - I was going to sleep at that point. I wanted to deal with it today.

**Comment by wojtek-t** [comment]
It seems that we are leaking at least:
- firewall rules
- static IP addresses

**Comment by gmarek** [comment]
This particular issue is solved (for now), but the problem of leaking resources needs to be addressed.

**Comment by ixdy** [comment]
We used to [try to bring the cluster down when turnup failed](https://github.com/fejta/kubernetes/blob/ffe611569dbd645a7d5c9428828ece1404e7e396/hack/jenkins/e2e-runner.sh#L169-L181), but that logic was apparently lost in #28575.

**Comment by gmarek** [comment]
Bumping to P0 - this happened again, thus breaking all kubemark PR runs. cc @wojtek-t @kubernetes/test-infra-maintainers

**Comment by wojtek-t** [comment]
Hopefully, #34442 should help with this.

**Comment by jingxu97** [comment]
I have a test also having the similar problem.
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/34557/kubernetes-pull-build-test-e2e-gce/62644/build-log.txt

ERROR: (gcloud.compute.firewall-rules.create) Some requests did not succeed:
 - Quota 'FIREWALLS' exceeded. Limit: 250.0

**Comment by fejta** [comment]
Running out of firewalls on PR testing is https://github.com/kubernetes/kubernetes/pull/34577 (see https://github.com/kubernetes/test-infra/pull/807#issuecomment-253436568 for a long-winded explanation of the situation)
