### ISSUE TITLE
Discuss about some `name` fields in the CRI

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#33873]
So during implementing the CRI, I found actually the [name of the Mount](https://github.com/kubernetes/kubernetes/blob/v1.5.0-alpha.0/pkg/kubelet/api/v1alpha1/runtime/api.proto#L104) and the [name of the PortMapping](https://github.com/kubernetes/kubernetes/blob/v1.5.0-alpha.0/pkg/kubelet/api/v1alpha1/runtime/api.proto#L90) are not useful for several reasons.

- Docker doesn't support names for these two things
- rkt has a more strict rule about name format, so we are not relying on these names in CRI.
- There is a misuse of the `Mount name`, which causes the mount name to be not unique (Related to #33526). Where in most case, the `Mount name` comes from the volume's name in the k8s API, but sometimes it's generated by kubelet. (e.g. the `/etc/hosts` mounts).

So given these facts, I suggest we just remove the name fields from the CRI.

/cc @kubernetes/sig-node @kubernetes/sig-rktnetes

**Comment by euank** [comment]
:+1: 

They're only useful for logging/informational-metadata, and I don't think that's a good enough argument for keeping them.

I also don't think the docker integration makes them visible as information, just in logging, so we're not removing information from the user in that case.

In the rkt case, we did preserve those names (e.g. you could find them in the rkt pod manifest), but we have no qualms with dropping them. We already dropped volume names in fact, and I can't think of a compelling reason not to drop port names too.

**Comment by yujuhong** [comment]
Since runtime doesn't refer to the volumes by names, I am fine with getting rid of the `name` fields.
