### ISSUE TITLE
kubeadm cluster dns

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#33881]
kubeadm version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.0.1534+cf7301f16c0363-dirty", GitCommit:"cf7301f16c036363c4fdcb5d4d0c867720214598", GitTreeState:"dirty", BuildDate:"2016-09-27T18:10:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:

I ran:
sudo kubeadm init --service-cidr 172.16.128.0/24

The kube-dns service picks 172.16.128.10 and functions properly there, but pods created use the 100.64.0.10 address space to try and talk to kube-dns and fails. The wrong address is placed in /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

**What you expected to happen**:
Pods launch with a correct resolv.conf pointing to a kube-dns in the specified range.

**How to reproduce it** (as minimally and precisely as possible):
kubeadm init --service-cidr <with any non default subnet>

launch a non net=host pod, and try to resolve a service.

**Comment by sandys** [comment]
is this interrelated to bug#33798 ?

**Comment by errordeveloper** [comment]
@kfox1111 thanks for reporting this!

This is really a documentation issue. You are right that `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` set `--cluster-dns=100.64.0.10`, but it's not set by `kubeadm init`, it's really the layer below. This file is part of kubelet package.

So what we need to document is that whenever one wants to set `--service-cird`, they need to also do the following:
```
printf '[Service]\nEnvironment="KUBELET_DNS_ARGS=--cluster-domain=cluster.local --cluster-dns=%s"\n' 172.16.128.10 > /etc/systemd/system/kubelet.service.d/20-dns-override.conf
systemctl daemon-reload
systemctl restart kubelet.service
```

**Comment by sandys** [comment]
@errordeveloper just want to know ... can KUBELET_DNS_ARGS be prepended to every kubectl/kubelet/kubeadm command , rather than changing it at the systemd level ?

i have seen that changing systemd files always causes some merge issues while updating packages, so im a little hesitant. i would rather take care of it at a configuration file or individual command level

**Comment by jonathan-kosgei** [comment]
@errordeveloper 

the default file seems to have everything setup okay, I'm I missing something?

```
root@sc-dev-2:~# cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=100.64.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_EXTRA_ARGS=--v=4"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_EXTRA_ARGS
```

**Comment by errordeveloper** [comment]
@sandys perhaps, but the plan is that we should be able to update the kubelet setting via the API, so we won't have to handle this once we have a better abstraction. This is just what we have to do at the moment. Hopefully we should be able to implement dynamic kulbelet settings in 1.5.
@jonathan-kosge are you also trying to set `--service-cidr`? If you are happy with the fault, you shouldn't have to care about this.

**Comment by jonathan-kosgei** [comment]
@errordeveloper right, came here from another issue, kube-dns is returning nxdomain errors for me , set up via kubeadm

**Comment by jonathan-kosgei** [comment]
```
root@sc-dev-2:~/docker-setup# nslookup kubernetes.default 100.64.0.10
Server:		100.64.0.10
Address:	100.64.0.10#53

** server can't find kubernetes.default: NXDOMAIN
```
right after a fresh install

**Comment by errordeveloper** [comment]
@jonathan-kosgei, you are welcome to join Slack and send me a DM... let's not go off-topic here. If you prefer to use Github, please open another issue describing your problem.

**Comment by sandys** [comment]
@errordeveloper continuing from comment https://github.com/kubernetes/kubernetes/issues/33881#issuecomment-251072229  

updating the configuration using API is interesting .. but from a bootstrapping perspective, will you allow this to be baked into config files also ?

**Comment by jbeda** [comment]
My suggestion on how to solve this in the short term:

Have `kubeadm init` talk to the API server to find the service IP of the DNS server.  Then rewrite that into a systemd unit overlay file.  Then kick systemd and kubelet to reload that file.  Shouldn't be that much code.

This assumes that users are using systemd so we'd probably want to make this something you can disable if you aren't using systemd.

**Comment by gajus** [comment]
How to fix this issue on an existing cluster?

That is, I think I have the same issue.

Here is relevant information:

```sh
[root@earth centos]# kubeadm version
kubeadm version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.2.380+85fe0f1aadf91e", GitCommit:"85fe0f1aadf91e134102cf3c01a9eed11a7e257f", GitTreeState:"clean", BuildDate:"2016-11-02T14:58:17Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

```sh
[root@earth centos]# cat /etc/resolv.conf
# Generated by NetworkManager
search local localdomain
nameserver 213.186.33.99
```

```sh
[root@earth centos]# cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_EXTRA_ARGS=--v=4"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_EXTRA_ARGS
```

As an example of where I first observed the issue,  I have setup a `busybox` pod and attempted to communicate with `elasticsearch-logging-*`.

```sh
[root@earth centos]# kubectl get po --all-namespaces
NAMESPACE      NAME                                     READY     STATUS    RESTARTS   AGE
kube-system    busybox                                  1/1       Running   0          40s
kube-system    dummy-2088944543-qy3oo                   1/1       Running   2          13d
kube-system    elasticsearch-logging-v1-0x37y           1/1       Running   0          25m
kube-system    elasticsearch-logging-v1-bkgdh           1/1       Running   0          25m
kube-system    etcd-149.202.180.48                      1/1       Running   2          13d
kube-system    kube-apiserver-149.202.180.48            1/1       Running   3          13d
kube-system    kube-controller-manager-149.202.180.48   1/1       Running   2          13d
kube-system    kube-discovery-982812725-1zjgh           1/1       Running   2          13d
kube-system    kube-dns-2247936740-irs2b                3/3       Running   6          13d
kube-system    kube-proxy-amd64-1sqts                   1/1       Running   2          13d
kube-system    kube-proxy-amd64-jqb3v                   1/1       Running   2          13d
kube-system    kube-proxy-amd64-wujv2                   1/1       Running   2          13d
kube-system    kube-scheduler-149.202.180.48            1/1       Running   2          13d
kube-system    weave-net-5gl5i                          2/2       Running   6          13d
kube-system    weave-net-e9f5e                          2/2       Running   5          13d
kube-system    weave-net-zyt6z                          2/2       Running   5          13d
```

```sh
/ # wget http://elasticsearch-logging:9200
wget: bad address 'elasticsearch-logging:9200'
```

**Comment by sandys** [comment]
@errordeveloper referring to your earlier comment (https://github.com/kubernetes/kubernetes/issues/33881#issuecomment-251072229) .. can everything be done using the commandline/api without messing about systemd files ?

**Comment by jamiehannaford** [comment]
Does this still require a fix? If so, I'd like to help out. Am I correct in assuming the best fix would be the one suggested in https://github.com/kubernetes/kubernetes/issues/33881#issuecomment-256697325?

**Comment by ajayapte** [comment]
The workaround in [comment](https://github.com/kubernetes/kubernetes/issues/33881#issuecomment-251065019) works.  I was a bit lazy and just changed the 10-kubeadm.conf.  Then I did daemon-reload and restart kubelet.service as mentioned above.  Now my busybox has the right dns and I can do nslookup fine.  Thanks for the tip.

As mentioned above if someone can apply the fix to kubeadm to do this as part of init then that would be great.

**Comment by roberthbailey** [comment]
@luxas - can we migrate this issue to the kubeadm repo?

**Comment by luxas** [comment]
@kfox1111 Please reopen this in the kubeadm repo in case it still occurs with kubeadm v1.6: https://github.com/kubernetes/kubeadm/issues

(Or there might be issues filed for this there already)

**Comment by jethrogb** [comment]
With kubeadm, DNS IP is always the kubernetes cluster IP with a "0" appended, there should be no need to specify it separately.

**Comment by waleedkhan91** [comment]
> 
> 
> @kfox1111 thanks for reporting this!
> 
> This is really a documentation issue. You are right that `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` set `--cluster-dns=100.64.0.10`, but it's not set by `kubeadm init`, it's really the layer below. This file is part of kubelet package.
> 
> So what we need to document is that whenever one wants to set `--service-cird`, they need to also do the following:
> 
> ```
> printf '[Service]\nEnvironment="KUBELET_DNS_ARGS=--cluster-domain=cluster.local --cluster-dns=%s"\n' 172.16.128.10 > /etc/systemd/system/kubelet.service.d/20-dns-override.conf
> systemctl daemon-reload
> systemctl restart kubelet.service
> ```

@errordeveloper Just want to add this. For those facing the same issue in Kubernetes v1.11.1, You just need to change clusterDNS entry in /var/lib/kubelet/config.yaml. Also note that this change should be done on master as well as all worker nodes. Cheers!!!
