### ISSUE TITLE
Federation DNS should not require a unique identically named hosted zone

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#33898]
The federations DNS zone code currently assumes that we specify the HostedZone as our zone-name (ignoring the fact that both GCE & Route53 can host subdomains in a zone).  So for example I probably want to run federation in `federation.justinsb.com`, but I can do this in the hosted zone `justinsb.com`  (as an aside, we should make sure that federation does not assume it owns all the records in the zone)

Relatedly, we also should not assume that I only have _one_ HostedZone with the name "justinsb.com"

I propose that we add a `zone-id` argument, which would allow specification of the hosted zone to use separately from the domain name.  This would seem to solve both problems.

We could still default to matching the zone by name of course!

**Comment by justinsb** [comment]
Assigning to 1.5 as this is problematic on many real-world AWS configurations

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @justinsb

**Comment by justinsb** [comment]
Fixed by #36336 - closing.
