### ISSUE TITLE
Deleting Federated Ingress object doesn't DELETE associated load balancers and external IP address [On GCP]

### ISSUE THREAD

**Issue by allannaim** [kubernetes/kubernetes#33893]
**Kubernetes version** (use `kubectl version`): 1.4

**Environment**:
- **Cloud provider or hardware configuration**: GCP

Deleting Federated Ingress object doesn't remove associated load balancers and external IP address [On GCP]

**Comment by quinton-hoole** [comment]
Closing old bugs.  Pretty sure that this is resolved by cascading deletion.  Re-open if you're still seeing this.
