### ISSUE TITLE
kubeadm shouldn't have to run as root

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33907]
Right now kubeadm requires root access, but it shouldn't need, once we have APIs for creating pods and PKI secrets in local kubelet.

**Comment by pires** [comment]
@errordeveloper this could also be part of the proposal for a kubelet pod API (#28138). Thoughts?

**Comment by errordeveloper** [comment]
@pires yes, I think this is a key UX requirement, but it's somewhat easy to overlook.

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#57
