### ISSUE TITLE
kubeadm should produce a user-friednly error when ran not as root

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33908]
Right now kubeadm will fail with a "permission denied" error for whatever files it happens to write first. We should improve the UX by telling the user that they aren't root.

**Comment by pires** [comment]
@luxas can you assign this over to @dmmcquay?

**Comment by dmmcquay** [comment]
I'll work on this one.

**Comment by luxas** [comment]
It's very straightforward, and FYI here's one PR already #33902 for that.
But we probably want it in a separate package though, here's a more comprehensive list of tasks that should be done:  #34046

please sync with @dgoodwin that also is working on this
