### ISSUE TITLE
kubeadm refactor token handling

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33911]
As discussed in #33262:
- https://github.com/kubernetes/kubernetes/pull/33262/files#r80333662
- https://github.com/kubernetes/kubernetes/pull/33262/files#r80336374
- https://github.com/kubernetes/kubernetes/pull/33262/files#r80333982

**Comment by luxas** [comment]
Assigning @dgoodwin and @pipejakob since they are working on the `kubeadm token` command

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @errordeveloper @dgoodwin @pipejakob

**Comment by luxas** [comment]
Nope not a release blocker

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#60
