### ISSUE TITLE
kubeadm join should allow hostname

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33919]
Right now it only accepts IP address, but any resolvable names should be allow. It probably should keep retrying on lookup failures, as long as given name is valid.

**Comment by pires** [comment]
@luxas can you assign this over to @dmmcquay?

**Comment by luxas** [comment]
I can't. He's not a) in the kubernetes org or b) in the kubernetes-collaborators team

**Comment by pires** [comment]
Neither am I so what's the process here, if any?

**Comment by dmmcquay** [comment]
Well, if I can't be assigned on it, I'll just work on it anyways :)

**Comment by luxas** [comment]
Great!

**Comment by errordeveloper** [comment]
@dmmcquay you might want to look at https://github.com/kubernetes/kubernetes/pull/33543, it's related...

**Comment by pires** [comment]
@errordeveloper it seems #33543 closes this issue. Please confirm as I just did a review in the browser.

**Comment by syklinux** [comment]
where  i can kown my node token?

**Comment by pires** [comment]
@errordeveloper from what i can read from the code, this already works.
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/join.go#L79
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/node/discovery.go#L32-L34

**Comment by luxas** [comment]
@pires so we can close this now?

**Comment by pires** [comment]
@luxas as far as I can tell, yes.
