### ISSUE TITLE
kubeadm doesn't handle --cloud-config properly

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33915]
Right now we try to pass `--cloud-config` if `DefaultCloudConfigPath` exists, but we don't bother about the fact whether it's mounted into the container or now, it basically won't work. We need to do it properly.

**Comment by luxas** [comment]
Actually this is done properly, as `/etc/kubernetes` is host-mounted into the container so it should work.

Closing as fixed.
