### ISSUE TITLE
kubeadm and kube-discovery should use kubeconfig instead of a custom type

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33910]

**Comment by luxas** [comment]
@dgoodwin can I assign this to you?

cc @jbeda as well

**Comment by dgoodwin** [comment]
Technically in Joe's domain per our most recent separation of duties, though things may change in the coming week.

**Comment by jbeda** [comment]
This will be resolved as we implement the stuff out of #30707

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#58
