### ISSUE TITLE
kubeadm deploys kube-proxy daemonsets for different architectures, but it doesn't work

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33916]
Right now we create 3 daemonsets for `kube-proxy` in `app/master/addons.go`, but `images.GetCoreImage()` will only give use image names for `runtime.GOARCH`, so this feature is broken. We should only deploy one daemon set for the native architecture, but ensure it has the right label selectors, so we don't try to run `amd64` pods on nodes of different architecture. We should also make sure all addons have architecture labels, and not just `kube-proxy`. If user is building heterogeneous clusters, the will need to take about deploying addons for additional architectures, we shouldn't pre-deploy multiple things knowing that they will most likely remain unschedulable.

**Comment by ezspamat** [comment]
I have the same issue as well. I tried to create a cluster with x86 (Intel NUC) and arm (Raspberry-Pi) and I see that the kube-proxy is crashing. Here's the log entry from kube-proxy
`Logs from kube-proxy
standard_init_linux.go:178: exec user process caused "exec format error"`
Attached is the kube-proxy yaml file. I see that its picking up arm image
[kube-proxy.yaml.txt](https://github.com/kubernetes/kubernetes/files/1813781/kube-proxy.yaml.txt)
Don't know how to fix this.
