### ISSUE TITLE
kubeadm UpdateMasterRoleLabelsAndTaints should not use recursion

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33913]

**Comment by kenan435** [comment]
@errordeveloper 
Did you mean  func attemptToUpdateMasterRoleLabelsAndTaints. UpdateMasterRoleLabelsAndTaints is not using recursion as far as I can see.

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#53
