### ISSUE TITLE
running kubeadm init the second time doesn't do the right thing

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33924]
I've have `kubeadmutil.WriteKubeconfigIfNotExists()`, which is supposed to bail if kubeconfig exists... however, we have overwritten a static pod manifests and the PKI assets by the time we get there. We should figure out something better, it should probably be idempotent.

**Comment by errordeveloper** [comment]
xref https://github.com/kubernetes/kubernetes/issues/33925

**Comment by errordeveloper** [comment]
We should certain avoid accidental breakage, which is currently the case.

**Comment by kenan435** [comment]
When you say making it idempotent, basically reuse the already created assets etc.. and/or prompt the user if they would like to create new ones each time one of the commands (init, join) is executed? Have a check in each one of the functions and make sure that any combination of them (keeping vs creating new ones) does not cause accidental breakage.

**Comment by luxas** [comment]
This is fixed by preflight checks, and `kubeadm reset` should be run in between now.
