### ISSUE TITLE
review kubeadm return codes

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33928]
Right now it returns either 0 or 1, there is no way to tell other errors... For example not being able to init due to permission errors should probably return something else, and not being able to join due to bad args vs potential network issue vs already joined... etc.

**Comment by pires** [comment]
A lot of users will want to automate `kubeadm` usage. Returning error codes instead of parsing error logs makes a lot of sense!

**Comment by dmmcquay** [comment]
I'll work on this one.

**Comment by pires** [comment]
@luxas Fixed by #34341.

**Comment by dmmcquay** [comment]
@pires @luxas I was actually thinking of going a little deeper into this issue now that #34341 got merged in and look at more errors that could be handled correctly (permission errors, bad args, potential networks issues).

**Comment by pires** [comment]
I can support that but make sure to update docs to reflect that functionality.

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#61
