### ISSUE TITLE
should kubeadm have an assets abstraction?

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33926]
It'd help to implement dry-run mode, tarball export or other things.

**Comment by errordeveloper** [comment]
We currently write files from every other function, and it's not exactly consistent how it happens and what helper funcs are used for doing it. However, in some cases this provides us with an ability to have more user-friendly error message, which is something we will need to ensure assets abstraction would be capable of. We shouldn't have to document files we write, if we have dry-run mode, or good logging etc. We could permit some files, e.g. PKI assets or static pods to exists on disk before `kubeadm init`, which would be convenient way of not having to implement too many extra flags...

**Comment by errordeveloper** [comment]
We could add validation of existing files could also come into this, and even warn about deprecated files.

**Comment by luxas** [comment]
@errordeveloper Can I close this?
It doesn't seem like we're going that way...

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#49
