### ISSUE TITLE
improve kubeadm progress log and success summary messages

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33929]
We should use templates instead of format strings, we also shouldn't print multi-line summary message in non-interactive mode. Colours would a great addition too. We should probably also provide a quite mode, default no-too-verbose mode, and a verbose mode.

**Comment by errordeveloper** [comment]
xref https://github.com/kubernetes/kubernetes/pull/33831#issuecomment-250985320

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#54
