### ISSUE TITLE
New fields in tls.Config in golang 1.7

### ISSUE THREAD

**Issue by nhlfr** [kubernetes/kubernetes#33936]
When using go 1.7, `pkg/util/net/http_test.go` is failing with the following error:

```
--- FAIL: TestCloneTLSConfig (0.00s)
        http_test.go:72: New fields seen in http.Transport: [DynamicRecordSizingDisabled Renegotiation]
                Add to CopyClientTLSConfig if client-relevant, then add to expected list in TestCopyClientTLSConfig
FAIL
FAIL    k8s.io/kubernetes/pkg/util/net  0.007s
```

**Comment by krzyzacy** [comment]
Emm... I'll need this fix

**Comment by rmmh** [comment]
Wouldn't a full struct copy work if we zero out the fields we don't want retained afterwards? It'll be less fragile as well.

```go
package main

import "crypto/tls"

func main() {
	a := tls.Config{}
	b := a
	b.SessionTicketsDisabled = false
	b.SessionTicketKey = [32]byte{}
}
```

**Comment by nhlfr** [comment]
@krzyzacy @rmmh @jessfraz You prefer to re-open my pull request #33937 or include that commit in #28742?

**Comment by jianzhangbjz** [comment]
I'm also trouble in the issue when I execute `make test` command on release-1.4 branch of Kubernetes. Have someone fixed it? Fails (not all):
```
--- FAIL: TestCloneTLSConfig (0.00s)
	http_test.go:72: New fields seen in http.Transport: [DynamicRecordSizingDisabled Renegotiation]
		Add to CopyClientTLSConfig if client-relevant, then add to expected list in TestCopyClientTLSConfig
FAIL
FAIL	k8s.io/kubernetes/pkg/util/net	0.056s
```
```
root@heatonli-test1:/home/zhangjian/src/k8s.io/kubernetes# go version
go version go1.7.1 linux/amd64
```

**Comment by k82cn** [comment]
@nhlfr , we can not just re-open  #33937 : in `pre_go17.go`, it did not include `DynamicRecordSizingDisabled` & `Renegotiation` which means build failed in go1.6 if re-open #33937 .

**Comment by k82cn** [comment]
BTW, do we still support go1.6 in master? If so, we need upmerge #38600 to master.

**Comment by thockin** [comment]
Is this still a problem?  I don't see any test failures on go-1.7.3
