### ISSUE TITLE
kubeadm init with predefined token

### ISSUE THREAD

**Issue by avkonst** [kubernetes/kubernetes#33933]
It is a feature request to address kubeadm usability issue. When I provision new nodes (eg. with vagrant), it is hard to capture the generated token on init and pass it to slaves to join. It would be much easier, if I could specify a predefined token for init and for join.
Also, I have not found a way to get the token with kube utilities, when init is done and I missed the output from init. As a temporary workaround, I would like to know how to reset the token if I can not get it.

**Kubernetes version** (use `kubectl version`):
1.4.0

**Environment**:
Ubuntu 16.04, bare metal or VM.

**Comment by koubas** [comment]
I've discovered that you can get the token this way:
`kubectl --namespace=kube-system get -o json secret/clusterinfo | sed -nr 's/^.*token-map.json": "(.*)".*$/\1/p' | base64 -d
`
Example output: {"56fa9a":"705a6001db6a6756"}
The token for kubeadm join is: 56fa9a.705a6001db6a6756

**Comment by luxas** [comment]
You can set the token in beforehand just by passing `--token` to `kubeadm init` so that should fix your issue.

Reopen if not necessary

**Comment by avkonst** [comment]
Thanks. I will try it.

**Comment by sunilkumarmohanty** [comment]
you can use kubeadm token generate to generate a predefined token
