### ISSUE TITLE
Find and fix hot loop logging

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#33935]
**Problem Statement:**
There are stressed conditions in the system where we have seen degenerative logging.  This typically happens before a panic or failure scenario.  Meanwhile, logging facilities will often rate limit those logs, and we can sometimes miss the panic, see: https://bugzilla.redhat.com/show_bug.cgi?id=1380458 . 

**Proposed Solutions:**
This issue is a **_catch all_** for an auditing of hot loop logging conditions that exist in the system, and to either find and fix those issues, or to refactor logging itself.  

/cc @thockin @timstclair @kubernetes/sig-scalability

**Comment by timstclair** [comment]
Is it worth considering a programmatic solution as well? Even if we fix all the current logging hotspots (and we should), more will eventually be introduced.  We could throttle the writes-per-seccond based on log statement location, along with some new functions for requesting higher rate limits for special cases. This would require building a logging wrapper, something we've been discussing anyway...

**Comment by timothysc** [comment]
I think this issue serves as a additional requirement towards the long term objective of refactoring logging.

**Comment by wojtek-t** [comment]
@piosz - FYI

**Comment by timothysc** [comment]
xref: #37558

**Comment by timothysc** [comment]
I'm going to close this issue now that we've addressed a number of them and rally on #37104 to coordinate with others.
