### ISSUE TITLE
kubeadm init --token isn't exactly user-friednly

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33930]
We should probably print more specific message on validation errors, or relax validation... Also, printing desired format could be a good idea, or we may wish to have `kubeadm util generate-token` that would print a pretty strong toke user can copy into their config management code.

xref https://github.com/kubernetes/kubernetes/issues/33911

**Comment by pipejakob** [comment]
Although I can't assign this to myself, I was going to take a stab at this.

/dibs

**Comment by luxas** [comment]
This is now fixed with #35075
