### ISSUE TITLE
Failed to get ConfigMap "kube-system/ingress-uid" error from federation controller manager on non-GCE/GKE cloud.

### ISSUE THREAD

**Issue by Sushant** [kubernetes/kubernetes#33943]
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:13:23Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:21:58Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**: 
- **Cloud provider or hardware configuration**: Private cloud (Openstack)
- **OS** (e.g. from /etc/os-release): 
  
  ```
    NAME="CentOS Linux"
    VERSION="7 (Core)"
    ID="centos"
    ID_LIKE="rhel fedora"
    VERSION_ID="7"
    PRETTY_NAME="CentOS Linux 7 (Core)"
    CPE_NAME="cpe:/o:centos:centos:7"
  
    CENTOS_MANTISBT_PROJECT="CentOS-7" 
    CENTOS_MANTISBT_PROJECT_VERSION="7"
    REDHAT_SUPPORT_PRODUCT="centos"
    REDHAT_SUPPORT_PRODUCT_VERSION="7"
  ```
- **Kernel** (e.g. `uname -a`): 
  `
    Linux 3.10.0-327.4.5.el7.x86_64 #1 SMP Mon Jan 25 22:07:14 UTC 2016 x86_64 GNU/Linux
  `
- **Install tools**:
- **Others**:
  - Hyperkube version: `hyperkube-amd64:v1.4.0`
  - DNS Provider: `google-clouddns`

**What happened**:
   `kubectl logs` for `federation-controller-manager` prints following error:

```
       ingress_controller.go:451] Failed to get ConfigMap "kube-system/ingress-uid" for cluster "n3-prod".  Will try again later: <nil>
```

**What you expected to happen**:
   According to conversation in #sig-federation channel on Slack,
   "It is an error from Federated Ingress controller.
     Federated Ingress is implemented only for GCE/GKE in v1.4 so there should be a way to turn it off on non-GCE/GKE providers."

**How to reproduce it** (as minimally and precisely as possible):
- Run federation control plane on non-GCE/GKE infrastructure.

**Comment by quinton-hoole** [comment]
Thanks for the bug report @Sushant .  Perhaps the best solution here is to suppress the error message if no Federated Ingresses have been created.  If Federated Ingresses have been created, and some of the clusters in the federation are not GCE/GKE, then the federated Ingresses are almost certainly not going to behave as the user expects, and I imagine that they would want to see the log message you mention.

A PR for the above improvement would be welcome.

**Comment by lsztachanski** [comment]
Same problem here. Mixed environment: 
- 4 GKE clusters,
- 1 bare-metal k8s cluster.

IP allocation and svc scheduling works, if cluster is homogeneous. After attaching bare metal cluster i get:
```E1109 14:41:33.709110       1 ingress_controller.go:451] Failed to get ConfigMap "kube-system/ingress-uid" for cluster "baremetal".  Will try again later: <nil>```

```$ kubectl describe svc nginx
Name:                   nginx
Namespace:              default
Labels:                 app=nginx
Selector:               app=nginx
Type:                   LoadBalancer
IP:
Port:                   http    80/TCP
Endpoints:              <none>
Session Affinity:       None
No events.```


```
$ kubectl --context=baremetal get svc
NAME         CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
(...)
nginx        10.20.246.3   <pending>     80/TCP    15h
$ kubectl --context=gke_sdi-k8s_europe-west1-b_gce-europe-west1 get svc
NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
(... nothing ...)

```

**Comment by madhusudancs** [comment]
@lsztachanski Do you have a loadbalancer/external IP implementation for your baremetal/provider?

The Ingress error is independent of the service error your are seeing.

```(... nothing ...)``` in the GKE cluster is curious. Isn't there a `kubernetes` service too? Also, is your GKE cluster registered against federation and showing a `Ready` status?

**Comment by lsztachanski** [comment]
I recreated the whole federation system using @kelseyhightower example. Indeed, k8s on GKE assigned IPs to its services. 
Important to note, DNS records are not populated when svc on bare-metal is in pending state (it worked before i attached the bm cluster).

It looks as follows:

```
NAME         STATUS    AGE
gce-europe   Ready     1d
gce-us       Ready     1d
baremetal Ready     43m

[~] cluster get svc -o wide                                                                                                                                                                                                        15:00:22
NAME      CLUSTER-IP   EXTERNAL-IP                    PORT(S)   AGE       SELECTOR
nginx                  104.199.14.45,107.178.222.56   80/TCP    20m       app=nginx
[~] eu get svc -o wide|grep nginx                                                                                                                                                                                                  15:00:49
nginx        10.43.254.136   104.199.14.45   80/TCP    20m       app=nginx
[~] us get svc -o wide|grep nginx                                                                                                                                                                                                  15:00:54
nginx        10.3.243.182   107.178.222.56   80/TCP    21m       app=nginx
[~] baremetal get svc -o wide|grep nginx                                                                                                                                                                                           15:01:47
nginx                  10.254.78.142    <pending>     80/TCP    21m       app=nginx
```

We tried to implement ingress (Name based virtual hosting), but i suppose that's wrong direction.

Again, the error is:
```
I1116 14:17:18.945410       1 ingress_controller.go:309] ConfigMap change delivered for cluster "baremetal", reconciling configmap for that cluster
I1116 14:17:18.945565       1 ingress_controller.go:422] Reconciling ConfigMap for cluster(s) "baremetal"
I1116 14:17:18.945654       1 ingress_controller.go:391] Cluster list is synced
E1116 14:17:18.945722       1 ingress_controller.go:451] Failed to get ConfigMap "kube-system/ingress-uid" for cluster "baremetal".  Will try again later: <nil>
I1116 14:17:28.977265       1 ingress_controller.go:309] ConfigMap change delivered for cluster "baremetal", reconciling configmap for that cluster
I1116 14:17:28.982529       1 ingress_controller.go:422] Reconciling ConfigMap for cluster(s) "baremetal"
I1116 14:17:28.982625       1 ingress_controller.go:391] Cluster list is synced
E1116 14:17:28.982684       1 ingress_controller.go:451] Failed to get ConfigMap "kube-system/ingress-uid" for cluster "baremetal".  Will try again later: <nil>
```

Is there suggested **ingress** implementation to make services working in **hybrid** setup?

**Comment by nalink** [comment]
i do see similar issue while doing federation setup on AWS:
`
➜  kubernetes git:(master) ✗ kubectl get clusters --context=federation-cluster
NAME       STATUS    AGE
cluster1   Ready     44m
cluster2   Ready     37m
cluster3   Ready     37m
`

but controller logs:
`
E1206 01:00:26.465644       1 ingress_controller.go:450] Failed to get ConfigMap "kube-system/ingress-uid" for cluster "cluster3".  Will try again later: <nil>
E1206 01:00:36.324873       1 ingress_controller.go:450] Failed to get ConfigMap "kube-system/ingress-uid" for cluster "cluster1".  Will try again later: <nil>
E1206 01:00:36.438152       1 ingress_controller.go:450] Failed to get ConfigMap "kube-system/ingress-uid" for cluster "cluster2".  Will try again later: <nil>
E1206 01:00:36.465886       1 ingress_controller.go:450] Failed to get ConfigMap "kube-system/ingress-uid" for cluster "cluster3".  Will try again later: <nil>
`
