### ISSUE TITLE
Different names and port numbers

### ISSUE THREAD

**Issue by AshleyAitken** [kubernetes/kubernetes#3394]
Please use different name attributes and port numbers (host,container) in examples.  When all the names in a JSON file are the same and ports are the same (host,container) it makes it hard to see which is which and understand references in text to names and ports.

For example, use id of redis-master-service and selector name redis-master-pod (or should that be redid-master-label?).

Just a suggestion to make text and examples easier to follow.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is still a significant issue (many examples are now located in Helm, for example).
