### ISSUE TITLE
kubelet: document in release notes if in-place upgrade should work

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#33954]
In talking with a user, I've realized that we should say in release notes if it's safe to do an in-place kubelet upgrade, or if users should do a drain/upgrade/undrain cycle for each node. We should include a table, actually, in case users are trailing by more than one version.

(In the past we have change the hashing function that kubelet uses to name docker containers, causing all containers on a node to get restarted if you do an in-place upgrade.)

Filing this so we don't forget.

**Comment by uruddarraju** [comment]
cc @ashw7n

**Comment by uruddarraju** [comment]
Related issue: https://github.com/kubernetes/kubernetes/issues/23104

**Comment by lavalamp** [comment]
(And I think the thing we should do here is set up a test job that does an in-place upgrade and fails if any pods restart.)

**Comment by dchen1107** [comment]
Good idea, especially since 1.4 release, we start to break the bundle release (kubelet & docker) at the node.

On the test side, once we automated upgrade test suite, we can add the test to check pods / container.
