### ISSUE TITLE
error: <master/discovery> failed to create "kube-discovery" deployment [deployments.extensions "kube-discovery" already exists]

### ISSUE THREAD

**Issue by sbezverk** [kubernetes/kubernetes#33956]
Even after complete clean up of all leftover from previous installation, new kubeadm init constantly generates:

error: <master/discovery> failed to create "kube-discovery" deployment [deployments.extensions "kube-discovery" already exists]

kubeadm init
<master/tokens> generated token: "18d804.3a337b34b4311cab"
<master/pki> created keys and certificates in "/etc/kubernetes/pki"
<util/kubeconfig> created "/etc/kubernetes/kubelet.conf"
<util/kubeconfig> created "/etc/kubernetes/admin.conf"
<master/apiclient> created API client configuration
<master/apiclient> created API client, waiting for the control plane to become ready
<master/apiclient> all control plane components are healthy after 39.853964 seconds
<master/apiclient> waiting for at least one node to register and become ready
<master/apiclient> first node is ready after 0.504060 seconds
error: <master/discovery> failed to create "kube-discovery" deployment [deployments.extensions "kube-discovery" already exists]

Since this error gets generated, kubeadm does not return "join" string for other nodes to join, making it impossible to move forward.

**Comment by luxas** [comment]
cc @errordeveloper 
This issue occurs since you have stale data in `/var/lib/etcd`.
You should clean your env as described in the kubeadm doc before rerunning init

**Comment by sbezverk** [comment]
Thank you very much for such prompt reply.

**Comment by RKalkani** [comment]
I tried below steps to perform cleanup prev unsuccessful kubeadm init and success return kubeadm init.

Here are the clean up steps :
1.` service kubelet stop`
2. kill k8s process ,  `ps aux | grep kub`
3. stop and remove all k8s containers
4. umount all /var/lib/kubelet/pods/
5. remove prev config dirs,
`rm rm -rf /etc/kubernetes`
`rm -rf /var/lib/kubelet/`
`rm -rf /var/lib/etcd`
5. Reboot 
6. retrun 
`kubeadm init`

**Comment by pnzrdrgoon** [comment]
I also get this error after running the cleanup script and rebooting:

<master/tokens> generated token: "633870.1a0e6f38275e0dad"
error: <master/tokens> failed to create directory "/etc/kubernetes/pki" [mkdir /etc/kubernetes: permission denied]
[modiadmin@wwqa-qi-build ~]$ sudo su
[root@wwqa-qi-build modiadmin]# kubeadm init
<master/tokens> generated token: "8f5b7f.0a95d8cbd01a6ed7"
<master/pki> created keys and certificates in "/etc/kubernetes/pki"
<util/kubeconfig> created "/etc/kubernetes/kubelet.conf"
<util/kubeconfig> created "/etc/kubernetes/admin.conf"
<master/apiclient> created API client configuration
<master/apiclient> created API client, waiting for the control plane to become ready
<master/apiclient> all control plane components are healthy after 16.054546 seconds
<master/apiclient> waiting for at least one node to register and become ready
<master/apiclient> first node is ready after 4.502505 seconds
error: <master/discovery> failed to create "kube-discovery" deployment [deployments.extensions "kube-discovery" is forbidden: not yet ready to handle request]

**Comment by pnzrdrgoon** [comment]
A fix I had for this issue was that I had installed docker-engine instead of docker:

yum remove docker-engine
yum remove docker-engine-selinux
yum install -y docker
then run the cleanup script as is
