### ISSUE TITLE
no hyperkube 1.3.8 in gcr.io/google_containers/hyperkube registry 

### ISSUE THREAD

**Issue by d-stern** [kubernetes/kubernetes#33969]
**Kubernetes version** (use `kubectl version`): v.1.3.8

**Environment**:
- **Cloud provider or hardware configuration**: n/a 
- **OS** (e.g. from /etc/os-release): n/a
- **Kernel** (e.g. `uname -a`): n/a
- **Install tools**: n/a 
- **Others**: n/a 

**What happened**:
Trying to build kubernetes 1.3.8 to upgrade our cluster but there's no 1.3.8 hyperkube image in the `gcr.io/google_containers/hyperkube` registry.

**What you expected to happen**:
hypercube v1.3.8 to be present 

**How to reproduce it** (as minimally and precisely as possible):
running `curl -X GET https://gcr.io/v2/google_containers/hyperkube/tags/list` shows there is no v1.3.8 hyperkube image in the registry, just a v1.3.8-beta.

**Comment by mikesplain** [comment]
This is also the case for v1.3.9

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.

**Comment by smekkley** [comment]
For people who might find this issue again..
podman pull gcr.io/google-containers/hyperkube:v1.15.0 works.
https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/hyperkube?gcrImageListsize=30

**Comment by tgy** [comment]
still happening with `v1.28.0`

**Comment by dims** [comment]
hyperkube has been deprecated and removed a long time ago. please check changelog(s)
