### ISSUE TITLE
Add a kubeadm verify command

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#33962]
We probably want `kubeadm verify` command that users may run easily in order to check if their node satisfies the requirements kubelet has on the node.

Something like this, but maybe bundled into kubeadm for ease of use: https://github.com/kubernetes/kubernetes/pull/32427

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle

**Comment by mikedanese** [comment]
Can you explain what this should do in the issue description?

**Comment by luxas** [comment]
Updated the description.
I converted it from a note in the kubeadm project, seems like I couldn't add a description when doing that.
Now fixed.

**Comment by mikedanese** [comment]
Thanks. How is this going to ineract with the nodespec verification that @kubernetes/sig-node has been working on? We should make sure this work is aligned. cc @Random-Liu

**Comment by luxas** [comment]
I thought about if we could just include it in the binary in order to get a consistent experience :)
Or if we could kubeadm just spawn the node e2e test the right way...

**Comment by mikedanese** [comment]
Linking what they've been doing and exposing it as a subcommand in kubeadm sounds good to me.

**Comment by Random-Liu** [comment]
Sorry for the delay, just saw this issue. :) This is related to https://github.com/kubernetes/kubernetes/issues/28408.

The system verification will be a simple package which should be able to integrate into kubeadm easily. Just import and call [`system.Validate()`](https://github.com/kubernetes/kubernetes/pull/32427/files#diff-1797fd733920de6906be5e6850afeba8R41). Currently, we are working on defining the list of required kernel configurations. After that, we can get #32427 in.

One question is: Where should we place the system verification logic? Should it be part of kubeadm UX or not?
1) `kubeadm verify`? (This issue)
2) `kubelet verify`? (#28408)
3) or `SEPARATE_VERIFY_TOOL verify`?

**Comment by euank** [comment]
Could `kubeadm verify` exist as a superset of `kubelet verify`; e.g. we could implement `kubelet verify` and test it on the node side, but we could document for users to use `kubeadm verify`.

`kubeadm verify` could then follow the flow of
1. Validate kubelet binary exists
2. Run `kubelet verify` and make sure it's happy
3. Run any other validation tools

I think that sort of separation of concerns makes some sense, but it might be premature if there won't be any additional tools.

I do think that the less a user interacts directly with kubelet, as opposed to tools that abstract over it, the better.

**Comment by pires** [comment]
I agree with @euank, add the logic to `kubelet` and have `kubeadm` feed from there.

I also don't think it's premature but I am concerned with the ETA for `kubelet verify`.

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#59
