### ISSUE TITLE
Feature request: emptyDir using dynamically created volumes

### ISSUE THREAD

**Issue by nvnobelen** [kubernetes/kubernetes#33975]
FEATURE REQUEST:

emptyDir/hostPath defaults to local disk (/var/lib/kubectl), which due to the dynamic behaviour of kubernetes is not really working in a production environment: Multiple pods with conflicting volume size requirements could end up on the same node with as result disk space issues & crashes.

My proposal is to be able to auto create a GCE/AWS/Azure/Other cloud provider/flocker/docker volume/all other volumes which can be destroyed an created independent of the node.

Behaviour of the volume:
- Creation and destruction behaviour is exactly the same as now for emptyDir.

By managing the temporary disk space requirements this way, the dynamic behaviour of the pod allocation is captured in a better way.

Proposed syntax:
emptyDir:
  capacity:
      storage: {storagesize to be created}

This is different from a PV:
- PVs are not destroyed automatically

This is different from a hostPath:
- No fixed directory for the mount since that would conflict with the application requirements/requires scripting the application to behave dynamic

**Comment by colemickens** [comment]
How is this different than Dynamic Disk Provisioning? From your description it sounds like Dynamic Disk Provisioning suits your needs?

**Comment by nvnobelen** [comment]
@colemickens Very similar I agree: The art is in finding the features in the whole list (plus sometimes: What is not there today, is suddenly there tomorrow: It is a fast moving project ;) )
Thanks, closing this one and going to experiment with the Dynamic Disk Provisioning.
