### ISSUE TITLE
Need e2e tests for volumes of all kinds

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#3399]
But PD especially

**Comment by jbeda** [comment]
There is a PD test at `hack/e2e-suite/pd.sh`.  But other volumes should be tested too.

**Comment by kargakis** [comment]
@kubernetes/sig-storage-misc

**Comment by msau42** [comment]
We have a bunch of volume tests now under the storage/ directory.  I think this can be closed, unless there's any other specifics that we want here?

**Comment by jeffvance** [comment]
_test/e2e/storage/*_
