### ISSUE TITLE
e2e flake: [k8s.io] Restart [Disruptive] should restart all nodes and ensure all nodes and pods recover

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#34003]
This happens in ~50% of gce-serial runs (data from checking last 6 runs). It seems pretty serious, but I can't find a automated issue for this. @kubernetes/test-infra-maintainers Previous issue: #32960

Last failure: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-serial/2272

This looks like a Node issue. @kubernetes/goog-node @dchen1107 please reassign.

cc @davidopp

**Comment by yujuhong** [comment]
The mirror pod of the e2e-image-puller pod has been deleted in the network partition test by the node controller. kubelet currently doesn't try to recreate the mirror pod (or even sync it) if the pod has already terminated. In the restart test, kubelet got restarted, and the in-memory status cache was cleared. kubelet then decides to sync the pod once to generate the status, which leads to creating of the mirror pod.

For the mid-term solution, we can consider reconciling the mirror pod status with the in-memory status for the static pod, and update them. In the long run, we should resolve #16627. For this issue specifically, I'd suggest doing hacks such as disregarding image puller or all "never restart" pods. 

/cc @Random-Liu

**Comment by Random-Liu** [comment]
Offline discussed with @yujuhong, I can't think of a better short-term solution, either.
To make sure the mirror pod to be there, we could
1) Prevent other components from deleting it (read-only mirror pod is still under discussion at #16627)
2) Let kubelet recreate the mirror pod even though it terminates, which needs to change kubelet SyncPod logic or separate mirror pod logic out of SyncPod. (there was a pending PR for this https://github.com/kubernetes/kubernetes/pull/18638, but we don't have time to finish it anytime soon)

So maybe for now we can only go with the short-term solution, change the test to pass if the extra pod is a `RestartNever` mirror pod (known issue).

**Comment by gmarek** [comment]
Or we can make a Daemon from image-puller, assuming that we correctly handle Daemons that finish.

**Comment by yujuhong** [comment]
I thought daemons have restart policy == Always, and that's why the image puller was a static pod to begin with...

**Comment by gmarek** [comment]
I don't know. If not daemon, then maybe a Job that runs before every test or sth?

**Comment by gmarek** [comment]
@yujuhong @dchen1107 - this is failing at least once a day in every suite it runs.

**Comment by yujuhong** [comment]
I'll send a PR to ignore mirror pods with restart policy == Never as a bandaid solution and keep this issue open until we have a proper solution.

**Comment by gmarek** [comment]
Great - thanks @yujuhong

**Comment by yujuhong** [comment]
This fix is in. Closing the issue and wait for re-occurrence.
