### ISSUE TITLE
tls bootstrap for kubelet incorrectly still using self-signed certs after generating fresh certs

### ISSUE THREAD

**Issue by ashmere** [kubernetes/kubernetes#34012]
Bug Report
**Kubernetes version** (use `kubectl version`): v1.4.0

**Environment**: CoreOS on GCE using custom clustering
- **Cloud provider or hardware configuration**: gce
- **OS** (e.g. from /etc/os-release):  CoreOS 1122.2.0
- **Kernel** (e.g. `uname -a`): 4.7.0
- **Install tools**:
- **Others**:

**What happened**:
I started a the kube-controller-manager with flags --cluster-signing-cert-file & --cluster-signing-key-file
and kubelet with with the flag --experimental-bootstrap-kubeconfig & --require-kubeconfig, the kubelet generate new signed cert and key using the crs on controller-manager and generate an kubeconfig that references them.
but when the kubelet starts the logs show it also generates the self-signed cert and key ignoring the value in the newly generated kubeconfig.

**What you expected to happen**:
I expect the kubelet to use the generated signed certs provided by the kube-controller-manager
(kubelet-client.crt/kubelet-client.key) and not the generate any self-signed certs (kubelet.crt/kubelet.key) at all.
Once restarted I expect the kubelet to use the values in the kubeconfig not use default values that aren't listed in any config

**How to reproduce it** (as minimally and precisely as possible):
Should be fairly simple to reproduction following the tls bootstrap setup.
if the certs, key and kuebconfig are removed the bootstrap kubeconfig is used again and both signed and self-sign certs are regenerated.

**Anything else do we need to know**:

Kubelet options

```
ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests /var/lib/kubelet /var/run/kubernetes
ExecStartPre=/bin/bash -c '/usr/bin/wget -N -P /opt/bin https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubelet'
ExecStartPre=/usr/bin/chmod +x /opt/bin/kubelet
ExecStart=/opt/bin/kubelet \
      --allow-privileged=true \
      --cloud-provider=gce \
      --v=4 --address=0.0.0.0 --enable-server \
      --container-runtime=docker \
      --pod-manifest-path=/etc/kubernetes/manifests \
      --cluster-dns=${KUBE_DNS_IP4V} \
      --cluster-domain=${CLUSTER_NAME}.k8s.${DOMAIN} \
      --port=10250 \
      --read-only-port=10255 \
      --logtostderr=true \
      --register-schedulable=true \
      --feature-gates=AllowExtTrafficLocalEndpoints=true \
      --reconcile-cidr=true \
      --network-plugin=kubenet \
      --require-kubeconfig \
      --kubeconfig="/var/lib/kubelet/kubeconfig" \
      --experimental-bootstrap-kubeconfig="/var/lib/kubelet/bootstrap-kubeconfig" \
      --node-labels="INSTANCE_TYPE=${INSTANCE_TYPE},INSTANCE_ROLE=${ROLE}"
```

bootstrap-kubeconfig

```
apiVersion: v1
kind: Config
users:
- name: kubelet-bootstrap
  user:
    token: randomtoken
clusters:
- cluster:
    server: https://<apiserver_fqdn>
    certificate-authority: /var/run/kubernetes/ca.crt
  name: cluster
contexts:
- context:
    cluster: cluster
    user: kubelet-bootstrap
  name: bootstrap-context
current-context: bootstrap-context
```

generated kubeconfig

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /var/run/kubernetes/ca.crt
    server: https://<apiserver_fqdn>
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    namespace: default
    user: default-auth
  name: default-context
current-context: default-context
kind: Config
preferences: {}
users:
- name: default-auth
  user:
    client-certificate: /var/run/kubernetes/kubelet-client.crt
    client-key: /var/run/kubernetes/kubelet-client.key
```

logs from kubelet on a worker

```
Oct 04 13:44:54 ds-eu1-wk2-0 kubelet[15142]: I1004 13:44:54.094368   15142 feature_gate.go:161] feature gates: map[AllowExtTrafficLocalEndpoints:true]
Oct 04 13:44:54 ds-eu1-wk2-0 kubelet[15142]: I1004 13:44:54.096402   15142 gce.go:325] Using existing Token Source &oauth2.reuseTokenSource{new:google.computeSource{account:""}, mu:sync.Mutex{state:0, sema:0x0}, t:(*oauth2.Token)(nil)}
Oct 04 13:44:54 ds-eu1-wk2-0 kubelet[15142]: I1004 13:44:54.097451   15142 server.go:355] Successfully initialized cloud provider: "gce" from the config file: ""
Oct 04 13:44:54 ds-eu1-wk2-0 kubelet[15142]: I1004 13:44:54.097487   15142 server.go:475] cloud provider determined current node name to be ds-eu1-wk2-0
Oct 04 13:44:54 ds-eu1-wk2-0 kubelet[15142]: I1004 13:44:54.097508   15142 bootstrap.go:64] Using bootstrap kubeconfig to generate TLS client cert, key and kubeconfig file
Oct 04 13:44:54 ds-eu1-wk2-0 kubelet[15142]: I1004 13:44:54.427435   15142 server.go:490] Using self-signed cert (/var/run/kubernetes/kubelet.crt, /var/run/kubernetes/kubelet.key)
Oct 04 13:44:54 ds-eu1-wk2-0 kubelet[15142]: I1004 13:44:54.427471   15142 docker.go:375] Connecting to docker on unix:///var/run/docker.sock
Oct 04 13:44:54 ds-eu1-wk2-0 kubelet[15142]: I1004 13:44:54.427482   15142 docker.go:395] Start docker client with request timeout=2m0s
Oct 04 13:44:54 ds-eu1-wk2-0 kubelet[15142]: E1004 13:44:54.427546   15142 cni.go:163] error updating cni config: No networks found in /etc/cni/net.d
```

files in /var/run/kubernetes

```
ls -la /var/run/kubernetes/
total 20
drwxr-xr-x.  2 root root  140 Oct  4 13:44 .
drwxr-xr-x. 24 root root  660 Oct  4 10:29 ..
-rw-r--r--.  1 root root 3266 Oct  4 13:44 ca.crt
-rw-r--r--.  1 root root 1139 Oct  4 13:44 kubelet-client.crt
-rw-------.  1 root root  227 Oct  4 13:44 kubelet-client.key
-rw-r--r--.  1 root root 1123 Oct  4 13:44 kubelet.crt
-rw-------.  1 root root 1675 Oct  4 13:44 kubelet.key
```

**Comment by dims** [comment]
I believe the kubelet-client.crt / kubelet-client.key is for securing the API Server <-> Kubelet communication. I don't think it was meant to replace --tls-cert-file/--tls-private-key-file/--cert-dir for TLS listener.
( cc @liggitt @yifan-gu )

**Comment by ashmere** [comment]
It looks like it should do both and regardless of if the bootstrap is right for that the kubelet should surely be taking the values in the kubeconfig

**Comment by liggitt** [comment]
serving certs aren't part of the bootstrap flow yet

this is the intended flow, currently:
1. the bootstrap kubeconfig has an API token
2. the kubelet uses that to obtain a client cert, which it writes to /var/run/kubernetes, and generates kubeconfig referencing the new client cert
3. the kubelet generates a self-signed serving cert

the kubeconfig is used for kubelet->api communications, nothing else

**Comment by timstoop** [comment]
Ok, but where do you set the CA-signed certificate then? As the description of `--cert-dir` says this option is ignored when the tls options are set. I'm kind of missing the global picture here, as you need to have your provisioning system deploy certificates so kubectl can exec and log?
