### ISSUE TITLE
[Cluster Federation] Unable to create Federated Ingress

### ISSUE THREAD

**Issue by allannaim** [kubernetes/kubernetes#34017]
I've gone through the process of setting up a federated control plane several time and each time I've successfully been able to deploy federated replicasets and services. Where things feel like they're breaking is on federated Ingress. The controller manager seems to create a global forwarding rule, and backend proxies, with only one backend proxy configured to an instance group in the target cluster. It seems to get stuck there. I've attached controller-manager logs. I'm also hitting a backend service quota issue (not sure if this is related).

The current configuration is:
- 2 clusters (us-central, asia-east)
- control plane deployed in us-central
- each cluster has 3 nodes
- replicaset of 4 pods (2 pods in each region)
[fcm2-logs.txt](https://github.com/kubernetes/kubernetes/files/508716/fcm2-logs.txt)

**Comment by quinton-hoole** [comment]
Reassigning to @madhusudancs on the basis of our discussion.  He's already helping you with this.  Thanks Madhu!

**Comment by madhusudancs** [comment]
Hopefully, this works for everybody now due to these documentation changes - https://github.com/kubernetes/kubernetes.github.io/pull/1424. Please feel free to reopen if it doesn't.
