### ISSUE TITLE
godep verify script often fails downloading a dependency

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#34027]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-verify-master/4665/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-verify-master/4656/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-verify-master/4649/

Three recent failures, three different dependency load fails.

**Comment by ixdy** [comment]
First was a failure while downloading godeps. I'm really not sure what to do about that - by its very nature, the test needs to download the dependencies.

Second was a failure cloning from GitHub; this happens occasionally for unclear reasons.

Third was a failure downloading etcd, which we've run into many times, and for which we've discussed either caching or embedding etcd in the test container.

cc @kubernetes/test-infra-maintainers

**Comment by lavalamp** [comment]
We could potentially cache all the things that godep verify downloads. It's pretty ridiculous to actually download everything every run.

My point making an issue here is actually that a caching layer could solve all of these problems.
