### ISSUE TITLE
kubeadm could store a configmap with some of it's flags

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#34025]
Things like service CIDR and pod network CIDR, cluster DNS domain are useful for network and other similar type of add-ons, also there has been some ideas around general accessibility of key parameters. Other example may include cloud provider name, CNI config path and other bits of information that are scatered in kubelet, kube-apiserver and kube-controller-manager flags. Let's discussed this more specifically.

**Comment by pires** [comment]
1. What would be the use for the ConfigMap after it's stored?
2. Store it where, disk or API?

**Comment by pires** [comment]
Also, I just realized #33728 got merged so I believe we'll already have this info stored in the API as soon as we get assigned an apigroup?

**Comment by luxas** [comment]
I don't understand why this should be done.
Please clarify this now when we already have the api group and the possibility of specifying flags via a file

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#24
