### ISSUE TITLE
kubeadm join specify advertise ip

### ISSUE THREAD

**Issue by miry** [kubernetes/kubernetes#34031]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kubeadm

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

  - I would like to specify advertisement ip or hostname for node during the join process. Currently it uses hostname, but kb master could not find the host by it(if it is not in dns or hosts).

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**What you expected to happen**:

I expect to use IP address instead of hostname to search for kb nodes.

**How to reproduce it** (as minimally and precisely as possible):

```
$ kubeadm join --api-advertise-addresses=10.10.10.2 --token=123123 10.10.10.1

Error: unknown flag: --api-advertise-addresses
Usage:
  kubeadm join [flags]

Flags:
      --token string   (required) Shared secret used to secure bootstrap. Must match the output of 'kubeadm init'

```

**Comment by errordeveloper** [comment]
Thanks for reporting this @miry! I would really appreciate some help on this, it's still not clear if passing `--hostname-override` (as described in https://github.com/kubernetes/kubernetes/issues/33618#issuecomment-250411981) to kubelet is sufficient and whether it works properly (https://github.com/kubernetes/kubernetes/issues/33618#issuecomment-250612628).

**Comment by miry** [comment]
@errordeveloper  `--hostname-override` works. after I found other solutions and edit hostname.

```
cat << EOF > /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --node-ip $PRIVATE_IP --hostname-override $HOST"
Environment="KUBELET_DNS_ARGS=--cluster-dns=100.64.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_EXTRA_ARGS=--v=4"
ExecStart=
ExecStart=/usr/bin/kubelet \$KUBELET_KUBECONFIG_ARGS \$KUBELET_SYSTEM_PODS_ARGS \$KUBELET_NETWORK_ARGS \$KUBELET_DNS_ARGS \$KUBELET_EXTRA_ARGS
EOF
```

it works, but CNI network still use `eth0` for communicate. and in logs of weave npc I see could not access to api server `100.....:443`. After I unblock this port for public ip that assigned on eth0. It started works. 

it would great to have solutions where I should not open the port for Public and use restrictions access by private ip.

**Comment by miry** [comment]
fixed via solution in comments: https://github.com/kubernetes/kubernetes/issues/34101
