### ISSUE TITLE
Missing IP address in kubenet

### ISSUE THREAD

**Issue by nicolasbelanger** [kubernetes/kubernetes#34037]
When trying to deploy fluentd with DS, the master is missing available IP address...

```
Error syncing pod, skipping: failed to "SetupNetwork" for "fluentd-kpklh_default" with SetupNetworkError: "Failed to setup network for pod \"fluentd-kpklh_default(e27e255c-8a59-11e6-a2b5-063f839b962d)\" using network plugins \"kubenet\": Error adding container to network: no IP addresses available in network: kubenet; Skipping pod"
```

There is no apparent reason to limit these resources, and DeamonSets on master are much needed to monitor and log stuff from those nodes.  Please advise.

**Comment by freehan** [comment]
Can you take a look and see if this is a dup of https://github.com/kubernetes/kubernetes/issues/32844 ?

**Comment by nicolasbelanger** [comment]
@freehan Good catch, it looks exactly the same...  I'm closing this one then...
