### ISSUE TITLE
apiservers should be able to advertise a DNS name

### ISSUE THREAD

**Issue by colhom** [kubernetes/kubernetes#34043]
As of now, `--advertise-address` only accepts IP addresses. An apiserver should have an option to advertise a DNS name, in the case no IP address is permanently associated with the interface. A common situation where this is necessary is API servers behind an AWS ELB, which has no permanent IP address associated with it.

This could be implemented either by:
- modifying `--advertise-address` and associated logic to accept a DNS name as well
- creating a new flag `--advertise-host-name` which is mutually exclusive with `--advertise-address`

\cc @madhusudancs @nikhiljindal

**Comment by koubas** [comment]
I just hit the same issue
My questions are:
- To who the API server actually advertises the address?
- Is it OK when all the API servers in HA setup advertise their own IP adresses, but the endpoint to which the nodes connect is ELB's hostname?

Thanks

**Comment by databus23** [comment]
@koubas Did you manage do figure it out. Its a mystery to me too.

**Comment by koubas** [comment]
@databus23 not yet Now I've just purposely turned off one of my masters and the new nodes failed to join the cluster, because they tried to connect to advertised addresses, instead of the ELB, so it's still causing real problems to us :(
