### ISSUE TITLE
Add a kubeadm reset command

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#34044]
This would reset everything that kubeadm init and kubeadm join has done

Roughly this in bash:
```
systemctl stop kubelet;
docker rm -f $(docker ps -q); mount | grep "/var/lib/kubelet/*" | awk '{print $3}' | xargs umount 1>/dev/null 2>/dev/null;
rm -rf /var/lib/kubelet /etc/kubernetes /var/lib/etcd /etc/cni;
ip link set cbr0 down; ip link del cbr0;
ip link set cni0 down; ip link del cni0;
systemctl start kubelet
```

**Comment by luxas** [comment]
@kubernetes/sig-cluster-lifecycle 
This is some of the most important enhancements we should do asap

**Comment by errordeveloper** [comment]
```
ip link set cbr0 down; ip link del cbr0;
ip link set cni0 down; ip link del cni0;
```
I do not believe we've had these... are you sure? Different CNI plugins create devices with their own names.

cc @kubernetes/sig-network

**Comment by errordeveloper** [comment]
```
systemctl start kubelet
```
No, let's not restart anything, just stop and clean things up.

**Comment by caseydavenport** [comment]
> ip link set cbr0 down; ip link del cbr0;
ip link set cni0 down; ip link del cni0;

Yeah, this is plugin specific.

**Comment by Crazee** [comment]
I need this feature, too.  When you get stuck with errors like

```
error: <util/kubeconfig> failed to create "/etc/kubernetes/kubelet.conf", it already exists [open /etc/kubernetes/kubelet.conf: file exists]

error: <master/discovery> failed to create "kube-discovery" deployment [deployments.extensions "kube-discovery" already exists]
```

I'd like a way to reset things to square one without throwing away the VM and making a new one.

**Comment by errordeveloper** [comment]
Guy, we have this in docs, it was a bit hidden earlier, should be more
visible now... Yet indeed we should add this command ASAP.

**Comment by Crazee** [comment]
I had gotten past the first one but didn't figure out all the bits in clearing up the kube-discovery part.

By the way, I did a "chown ubuntu" of the /etc/kubernetes tree so I can run kubeadm/kubectl not as root.  Hope that won't cause other problems.

**Comment by lukemarsden** [comment]
> No, let's not restart anything, just stop and clean things up.

@errordeveloper Actually, I think starting things again is the right thing to do, at least on Ubuntu. Otherwise you can't run `apt-get install kubeadm; kubeadm init; kubeadm reset; kubeadm init`, which I think is desireable.

**Comment by luxas** [comment]
This is now fixed with https://github.com/kubernetes/kubernetes/issues/34807
