### ISSUE TITLE
noisy kubelet error log

### ISSUE THREAD

**Issue by ravilr** [kubernetes/kubernetes#34066]
version: kubernetes-v1.4.0
OS: RHEL 7.1
cloud-provider: baremetal/''
docker version: 1.12.1

noticing below error log in kubelet logs every 5 mins:
 E1004 23:56:49.188958    8353 container_manager_linux.go:567] error opening pid file /run/docker/libcontainerd/docker-containerd.pid: open /run/docker/libcontainerd/docker-containerd.pid: no such file or directory

in our setup, docker-containerd pid is in `/var/run/docker/libcontainerd/docker-containerd.pid`. Since the code seems to fallback to `pidof/procfs.pid`, does this needs to be logged at ERROR level?

@derekwaynecarr @yujuhong

**Comment by derekwaynecarr** [comment]
I will take a look.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @derekwaynecarr

**Comment by yujuhong** [comment]
@derekwaynecarr I don't think this should be a 1.5 blocker. Feel free to add it back if you disagree.

**Comment by sachincab** [comment]
Hi,

I noticed below errors in kubelet logs:
[27]: E0215 17:05:28.279002 1727 container_manager_linux.go:625] error opening pid file /run/docker/libcontainerd/docker-containerd.pid: open /run/docker/libcontainerd/docker-containerd.pid: no such file or directory

CoreOS stable version: 1235.9.0
kernel: 4.7.3
rkt: 1.18.0
docker: 1.12.6
Kubernetes version: v1.5.3

Please let me know your inputs for the same.

**Comment by dmnord** [comment]
I also want to know about this issue in details, because I have the same problems on fedora host. software versions are also the same as described above by sachincab!

**Comment by judexzhu** [comment]
Hi,

I noticed the same issue with below env
CoreOS stable version: 1353.7.0
Kernel : 4.9.24-coreos
rkt version: 1.25.0
docker: 1.12.6
kubernetes version : v1.6.3

kubelet-wrapper[1625]: E0513 01:41:55.155706    1625 container_manager_linux.go:638] error opening pid file /run/docker/libcontainerd/docker-containerd.pid: open /run/docker/libcontainerd/docker-containerd.pid: no such file or directory

just annoying, but cluster works fine 

Please let me know if there is any updates , thanks a lot !

**Comment by ichekrygin** [comment]
Also in `v1.6.4`

**Comment by mcronce** [comment]
This issue is present for me in Kubernetes v1.6.7 on Fedora 26 with Docker 1.13.1.

I found it while trying to figure out root cause for other stuff that started after upgrading from 1.5.4 on Fedora 25.  Based on other comments here, though, I'm guessing it's benign and has nothing to do with my issues.  The hunt continues :)
