### ISSUE TITLE
1.4.0 tarball missing vendor dependency jteeuwen/go-bindata

### ISSUE THREAD

**Issue by ZhangBanger** [kubernetes/kubernetes#34067]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): gobindata

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
1.4.0

**Environment**:
- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): OSX / Linux 
- **Kernel** (e.g. `uname -a`): N/A
- **Install tools**: N/A
- **Others**:

**What happened**:
Run `make all WHAT=cmd/kubectl GOFLAGS=-v` 

and get:

```
+++ [1004 17:24:34] Generating bindata:
    /Users/andy/Downloads/kubernetes-1.4.0/test/e2e/framework/gobindata_util.go
Cannot find go-bindata. Install with
  go get -u github.com/jteeuwen/go-bindata/go-bindata
../../../../../../test/e2e/framework/gobindata_util.go:19: running "../../../hack/update-bindata.sh": exit status 5
make[1]: *** [_output/bin/deepcopy-gen] Error 1
make: *** [generated_files] Error 2
```

**What you expected to happen**:
It should build without asking for an external dependency.

**How to reproduce it** (as minimally and precisely as possible):
Execute `make all WHAT=cmd/kubectl GOFLAGS=-v` from the root dir of the untar of kubernetes-1.4.0.tar.gz.

**Anything else do we need to know**:
This is causing an issue with homebrew that was addressed with a hack:
https://github.com/Homebrew/homebrew-core/pull/5558

If you run `rm "./test/e2e/framework/gobindata_util.go"` first, you're able to build (see the code in the PR).

**Comment by ZhangBanger** [comment]
Just realized what needs to be done - need to check this dep into vendor? Correct me if I'm wrong - otherwise I'll give it a shot and submit a PR.

**Comment by ZhangBanger** [comment]
Scratch that - not sure how to handle this.

**Comment by pwittrock** [comment]
@ZhangBanger Why not use `make release`?

**Comment by ZhangBanger** [comment]
Let me give that a try - thanks!

**Comment by ZhangBanger** [comment]
Does this make sense?

`make release-skip-tests WHAT=cmd/kubectl GOFLAGS=-v`

**Comment by zhw2101024** [comment]
#https://github.com/jteeuwen/go-bindata/issues/143
It seems a go-bindata issue.
Go-bindata need vet package, and vet has been moved to golang and cannot be found in golang.org/x/tools now.
But go-bindata is not actively developed and the latest commit is more than one year ago, so I dont't know when can this issue be reviewed.

**Comment by dragon9783** [comment]
same issue in version 1.4.6

**Comment by ixdy** [comment]
I'm working on fixing this for master in #36964. I'm not sure that it's worth cherry-picking to release-1.4.
