### ISSUE TITLE
Feature Federated StatefulSet

### ISSUE THREAD

**Issue by owenhaynes** [kubernetes/kubernetes#34086]
Could not find anything about this, but would be nice to use petsets across clusters, for example database replication for read only databases to another cluster. 

A possible first pass could be to make the DNS entries of each pet resolve in the other clusters.

**Comment by nstott** [comment]
+1 on this being useful for us

**Comment by quinton-hoole** [comment]
This is being tracked in https://github.com/kubernetes/community/pull/437
Due for alpha release in v1.8.
Closing this as a duplicate.
