### ISSUE TITLE
Any plan for re-implementing a spark/storm   with go language which is  supported by k8s?

### ISSUE THREAD

**Issue by sunfaces** [kubernetes/kubernetes#34080]
A lot  of developers are looking forward to such framework ：D

**Comment by bgrant0607** [comment]
cc @foxish

**Comment by foxish** [comment]
I don't think it makes sense to re-implement these frameworks given the efforts that would take, and the effort it would take to maintain them. However, k8s has client libraries in various languages (some still coming up) which lets us build support for kubernetes in frameworks like Spark and Storm.

There is a proposal https://github.com/kubernetes/kubernetes/issues/34377 to support kubernetes natively in Spark, and the associated JIRA: https://issues.apache.org/jira/browse/SPARK-18278
Also a more general resource management discussion is underway in https://github.com/kubernetes/kubernetes/issues/36716

While building Spark support, we are working on generalizing the pattern, and coming up with guidelines to help build third party controllers in frameworks like Storm, and Flink in the near future.

**Comment by timothysc** [comment]
So this isn't really a kubernetes issue honestly so I'm going to close.  Should folks wish to pursue they can do so externally.
