### ISSUE TITLE
RBAC settings best practice for service accounts. 

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/kubernetes#34091]
Hi,

I am on k8s 1.4.0, I have successfully configured RBAC with:

```
--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota \
        --authorization-mode=RBAC \
        --authorization-rbac-super-user={{ k8s_username }} \
        --runtime-config=api/v1,rbac.authorization.k8s.io/v1alpha1 \
```

Without having any roles and clusterroles and associated bindings, are service accounts supposed to work ?

It seems that my DNS and Dashboard are now failing in a crash loop, and I am guessing it is because I need to create a clusterRole for serviceaccounts to be able to access the resources in the API.

What is the best practice for ServiceAccounts configuration if we turn on RBAC ?

thanks

**Comment by sebgoa** [comment]
I created a cluster role and cluster role binding list this:

```
$ kubectl get clusterrole test -o yaml
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRole
metadata:
  creationTimestamp: 2016-10-05T12:00:28Z
  name: test
  resourceVersion: "130395"
  selfLink: /apis/rbac.authorization.k8s.io/v1alpha1/clusterroles/test
  uid: 4eee94f8-8af3-11e6-9891-069472000248
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - '*'
  verbs:
  - '*'
sebair: rbac $ kubectl get clusterrolebinding test -o yaml
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: 2016-10-05T12:03:28Z
  name: test
  resourceVersion: "129889"
  selfLink: /apis/rbac.authorization.k8s.io/v1alpha1/clusterrolebindings/test
  uid: ba358f4d-8af3-11e6-9891-069472000248
roleRef:
  apiVersion: rbac.authorization.k8s.io/v1alpha1
  kind: ClusterRole
  name: test
subjects:
- kind: Group
  name: system:serviceaccounts
```

Just to give all service accounts access to everything in all namespaces (for now, can be more restrictive once this works).

I am unsure about the wildcard use in resources and verbs in the ClusterRole.

**Comment by ericchiang** [comment]
> It seems that my DNS and Dashboard are now failing in a crash loop, and I am guessing it is because I need to create a clusterRole for serviceaccounts to be able to access the resources in the API.

Yep. The default for RBAC is to restrict all access. You'll have to explicitly give service accounts permission if you want them to access the API. I imagine DNS will require reading services, updating services/status (or something similar) and reading endpoints.

To the best of my knowledge dashboard requires pretty much root access, though perhaps someone from @kubernetes/dashboard-maintainers can talk about how it behaves under restrictive authorization rules.

> Just to give all service accounts access to everything in all namespaces (for now, can be more restrictive once this works).

> I am unsure about the wildcard use in resources and verbs in the ClusterRole.

Wildcards work, but be careful about giving service accounts unrestricted access to your cluster. Their bearer tokens are just stored as secrets, so anyone who can read secrets can impersonate them.

Overall this seems to be a question about how to configure service accounts so kube DNS and Dashboard work rather than how service accounts interact with RBAC. Perhaps a more focused issue on those components would be better?

**Comment by kargakis** [comment]
cc: @deads2k @liggitt

**Comment by liggitt** [comment]
The best practice for all users (not just service accounts) is to assign them roles with the minimal set of permissions required, at the minimal scope required.

There is work ongoing in 1.5 to define the following types of roles:
* discovery role (giving access to discovery endpoints), granted to all users by default
* roles for in-tree controllers (granted to service accounts, so each controller can run as a distinct service account with scoped permissions)

Defining roles for add-ons would be a good exercise as well. I would not expect most components running against the cluster to assume they had root power over the entire API.

**Comment by bryk** [comment]
> To the best of my knowledge dashboard requires pretty much root access, though perhaps someone from @kubernetes/dashboard-maintainers can talk about how it behaves under restrictive authorization rules.

Yes, in short. But the UI would happily work if it had only read access. 
The UI would crash-loop if it cannot get API version from the apiserver. This is a mechanism that is meant to help cluster admins to configure the UI correctly, because it'd crash loop until it works.

**Comment by bryk** [comment]
cc @rf232

**Comment by liggitt** [comment]
documented the various approaches at https://kubernetes.io/docs/admin/authorization/rbac/#service-account-permissions

**Comment by jonathan-kosgei** [comment]
Hi @liggitt 

I'm testing the following clusterrole
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: test
rules:
- apiGroups: [""]
  resources: ["crontabs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
```
with the following error on create
```
jonathan@sc-test-cluster:~$ kubectl create clusterrole role.yml
error: at least one verb must be specified
```

**Comment by liggitt** [comment]
to create from a file, always use `kubectl create -f <file>`

`kubectl create clusterrole` is a specialized command that creates a role based on verbs and resources you pass in with flags, not a file. see `kubectl create clusterrole --help` for details
