### ISSUE TITLE
After upgrade service is unavailable from external IP

### ISSUE THREAD

**Issue by hekike** [kubernetes/kubernetes#34095]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

`no`

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

`upgrade dns`
`upgrade external ip`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

`BUG REPORT`

**Kubernetes version** (use `kubectl version`):

`1.3.7`

**Environment**:
- **Cloud provider or hardware configuration**: `Google Cloud Container Engine`
- **OS** (e.g. from /etc/os-release):  `Debian GNU/Linux 7 (wheezy)`
- **Kernel** (e.g. `uname -a`): `Linux gke-trace-pool-1-dc497b52-0ptp 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux`
- **Install tools**: -
- **Others**: -

**What happened**:
1. new node pool added to the cluster via GC Container Service Dashboard (new pool 1.3.7, default pool is: 1.3.6, master is: 1.3.7)
2. nodes in old (default) pool set to un-schedulable and drained
3. default pool removed via GC Container Service Dashboard
4. Services with External IP stopped working from the public IP, all requests were hanging (while pods could reach each other via internal IP and service worked with internal IP as well)
5. I could solve the issue only with removing and re-creating all services with External IP

**What you expected to happen**:

"Zero down time" upgrading with no manual step involved

**How to reproduce it** (as minimally and precisely as possible):

I didn't try it again, probably with upgrade and pool remove.

**Anything else do we need to know**:

At my previous upgrade I also experienced issues with the DNS service, that time I simply pressed upgrade on the GC Container Engine UI, but after the upgrade, some of the pods had to be manually re-created otherwise they weren't able to communicate with each other.

**Comment by cmluciano** [comment]
This seems like a GKE issue

/remove-sig network

/sig cluster-lifecycle
