### ISSUE TITLE
Generalize label selectors

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#341]
Right now, our label selectors support conjunctions of exact matches of key-value pairs. We should support conjunctions of:
* key exists
* key is in (set of values)
* key is not in (set of values)

Exact match can be expressed using "is in".

This would allow selectors such as:

service is in (foo),
environment is not in (qa),
stage is in (daily, weekly)

**Comment by bgrant0607** [comment]
#1303 is a prerequisite for this.

**Comment by smarterclayton** [comment]
This is assigned for 0.8 and help-wanted is accurate?

**Comment by bgrant0607** [comment]
@smarterclayton: @meirf did the implementation work for the generalized selectors. Once we agree on the API changes, I think he or anyone could implement the changes. Removed help-wanted for now.

I removed the 0.8 milestone --  nobody payed attention to the milestones and we are using the priority labels now.

I am an advocate of the generalized selectors, though I'm not aware of any particular user demand yet. Maybe for node constraints.

**Comment by smarterclayton** [comment]
We have some folks looking to make use of the advanced selectors for looking at pods in bulk across fairly deep nesting of labels in several independent deployments.  I'll circle back and get a priority list.

----- Original Message -----

**Comment by bgrant0607** [comment]
Proposed API: https://github.com/GoogleCloudPlatform/kubernetes/issues/2585#issuecomment-71131565

**Comment by bgrant0607** [comment]
Things that remain to be done:
1. Introduce this into API objects that use selectors, using the proposal cited above
2. Extend labels.Parse to be backwards compatible with the exact-match syntax (k1=v1,k2!=v2)
3. Replace all calls to labels.ParseSelector with labels.Parse, by renaming the latter to the former, in List and Watch, in kubectl, and everywhere else.

**Comment by liggitt** [comment]
fyi @jwforres

**Comment by bgrant0607** [comment]
This is not blocking v1beta3 finalization, but if someone completed it in the next couple weeks, I'd be very happy.

**Comment by sdminonne** [comment]
@bgrant0607 I may submit relatively quickly a PR for the point 2 (extending labels.Parse) and I'm ready to finalize the point 3. 

But I need more info for the point 1 (introducing in API objects): might you supply some pointers for this? Where is this actually handled with the current implementation of the selectors?

**Comment by bgrant0607** [comment]
Thanks, @sdminonne. 

Re. the API: Copying my proposal from #2585:
```
type Selector struct {
	MatchLabels map[string]string
	MatchExpressions []SelectorRequirement
}
type SelectorOperator string
type SelectorRequirement struct {
	Key       string
	Operator  SelectorOperator
	StringValues util.StringSet // leaves room for intValues in the future
}
const (
	SelectorOpIn SelectorOperator = "In"
	SelectorOpNotIn SelectorOperator = "NotIn"
	SelectorOpExists SelectorOperator = "Exists"
)
```

These types would be defined in pkg/api/types.go and pkg/api/v1beta3/types.go. All selectors in v1beta3 (currently, NodeSelector in PodSpec, Selector in ReplicationControllerSpec, and Selector in ServiceSpec) would then use these types rather than map[string]string:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go

v1beta1 and v1beta2 map-based selectors would need to be converted to this representation in the conversion functions:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta1/conversion.go
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta2/conversion.go

@smarterclayton @thockin Any opinion on whether we should convert the operators to our CamelCase convention for constants (e.g., change `not in` to `NotIn`)? Capitalization would differ significantly from the labels themselves (assuming we didn't back away from case insensitivity). Perhaps we should just make the operators case insensitive also?

**Comment by bgrant0607** [comment]
@sdminonne I recommend doing (2), then (3), then (1). (2) and (3) would unblock #4417.

**Comment by sdminonne** [comment]
@bgrant0607 I'll do in this order thanks

**Comment by sdminonne** [comment]
@bgrant0607 @smarterclayton @thockin just submitted the first PR https://github.com/GoogleCloudPlatform/kubernetes/pull/4486 for the step 2.

**Comment by sdminonne** [comment]
@bgrant0607 @smarterclayton @thockin even if #4486 is not finalized I started to have a look at step 3 (replacing `labes.ParseSelector` with `labels.Parse`).
I'm having a trouble that I don't think it's only a `code issue`. 
`labels.ParseSelector

**Comment by bgrant0607** [comment]
And #2518 / #4575.

Good catch. Sorry, I forgot about that.

The current implementation of field selectors is a hack.

Because field names/paths do have different rules than label keys, we likely will need different parsers. I also don't feel that fields require the more general selector capability. Eventually we'll want unified indexing, but I'd be fine with 2 filtering passes for now. Since fields are exact-match only, they can be filtered either before or after the label selector.

**Comment by sdminonne** [comment]
Thanks. I would say that having `labels.Parse` to parse labels selector and having `labels.ParseSelector` to parse fields could be misleading. 
Are you OK to add a `fields.ParseSelector` (simply moving exact match code in the new package)? Otherwise I'll simply add a TODO.

**Comment by bgrant0607** [comment]
Yes, `fields.ParseSelector` sounds ok to me.

**Comment by sdminonne** [comment]
@smarterclayton @thockin @bgrant0607 
just created PR https://github.com/GoogleCloudPlatform/kubernetes/pull/4835 to replace `labels.ParseSelector` with `labels.Parse`

**Comment by sdminonne** [comment]
@bgrant0607 we discussed here about the `fields` and `labels` syntax difference. I've just submimtted https://github.com/GoogleCloudPlatform/kubernetes/pull/5171 thanks to have a look  if you've time.

**Comment by sdminonne** [comment]
@bgrant0607 I submitted https://github.com/GoogleCloudPlatform/kubernetes/pull/5919  as a step to bring `labels.Selector

**Comment by ravigadde** [comment]
@bgrant0607 @sdminonne 

Will PodSpec get an additional selector field to specify pod conflicts? NodeSelector can be used to identify/filter nodes that meet a certain criteria. It will great to have a PodConflicts (or some equivalent name) selector to filter out nodes that have conflicting pods.

**Comment by bgrant0607** [comment]
@ravigadde See #4301 and #367, and please describe what kind of conflict you'd like to represent on the latter issue.

**Comment by ravigadde** [comment]
@bgrant0607 

This is for describing anti-affinity requirements, for example multiple instances of a db server may not run on the same node.

**Comment by smarterclayton** [comment]
@abhgupta FYI

----- Original Message -----

**Comment by bgrant0607** [comment]
@ravigadde I'll direct you again to the other issues: #4301 and #367.

This one is just about selector semantics/syntax.

**Comment by sdminonne** [comment]
@bgrant0607 just added a PR https://github.com/GoogleCloudPlatform/kubernetes/pull/7053 as a possible implementation. More info inside the PR.

**Comment by timothysc** [comment]
FWIW I think a non-touring complete config language such as HCL, would eventually yield the descriptive power and syntax to provide complex matching.

**Comment by bgrant0607** [comment]
We were working on generalizing the selector semantics prior to the v1 API but did not finish in time. Now we have to preserve backward compatibility with the v1 API.

Regarding how to move forward with this:

The more general selector semantics cannot be directly represented using the old selector syntax. Therefore, we can't simply add new API versions using the more general selectors and still be able to directly convert to the old representation. Any field that was required, such as ReplicationController's selector, can't simply be left unset in lieu of a new field, and doing that for optional fields would break clients that expected to be able to reason about what the resource was doing, as in the case of Service (where a UI might visualize targets) or Pod.spec.nodeSelector, where third-party schedulers would not necessarily be aware of the new field and therefore would no longer uphold the contract specified by the pod.

One option:

Factor the more general selector's requirements into those that can be represented using the map syntax and those that cannot. For the latter, create a new label (key=value) and apply it to all resources matched by that sub-part of the selector (continuously, using a new controller). Specify that label in the v1 selector map along with the requirements that can be directly represented using the map. This new map-style selector should match the same targets as the more general selector and preserves as much of the semantic information represented by the more general selector as possible.

New API versions would be required for the more general selector. New, non-overlapping features can be added without a new API version. However, making non-backward-compatible changes to existing features is explicitly something that must be done in new API versions. Multiple redundant or overlapping fields are highly problematic for clients. See, for example, the discussion in #12823 or the example in the documentation:
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api_changes.md#on-compatibility 

In the case of 2 redundant fields, the old field always must take precedence. Old clients cannot be expected to know about the new field. If a client reads an API resource, modifies the old field (so the 2 fields are now inconsistent), and PUTs the modified resource, the old field must win, since this update would have worked before the new field was added. Similarly, this is also why the old field must always be populated if the new field is set -- so as not to break existing clients interpreting or operating on resources.

Clients using the new field can be expected to know about both fields and are responsible for setting both consistently. One such case is "kubectl apply" #1702 , where we'll be using the updated user-provided config as a PATCH to the live resource. The user can't just update the new field. They need to specify the new value for both the old and new fields.

The option I now recommend:

`nodeSelector` is one example of a scheduling constraint. resources are another. Though these are fields on Pod, a core API resource, they constitute and API to the scheduler. We intend to add more such constraints, as discussed in #367 and https://github.com/kubernetes/kubernetes/issues/4301#issuecomment-74355529, and we recently added scheduling based on resources.request and would like to move forward with conflicts #9560 . All such features must be supported by any third-party schedulers in order to respect the pod's API contract. In a sense, adding such constraints breaks compatibility with third-party schedulers and of any tools/UIs/components attempting to reason about scheduling decisions. However, we have to be able to add such constraints, just as we add new features to Service and to the Pod fields consumed by Kubelet. We should announce such changes on kubernetes-dev@googlegroups.com and document them clearly in release notes, probably in a special section.

When we add such fields, we'll likely need a fine-grain versioning mechanism to gate new features, as discussed in #4855. This is not unlike needing to ensure all Kubelets are upgraded before using a node-level feature exposed by an upgraded apiserver. We can add such a mechanism when there is enough demand from ecosystem developers and/or cluster administrators.

For nodeSelector specifically, then, I recommend we deprecate nodeSelector, but continue to support it, and add a new field, say `nodeConstraints`, using the more general selector. The new field would not be converted to the old. It would just be additional constraints that must apply. We could eliminate nodeSelector when we eliminate the v1 API at some point in the future.

For Service, a nil selector is already legal. Therefore, we could also add a new field, say `targetSelector`, using the more general selector. Anything trying to reason about what the Service targets should already be looking at the corresponding Endpoints list, anyway, which would still work. We should put an ObjectReference (and maybe link) to the Endpoints in status, for the convenience of clients. Having such a reference/query would make this problem easier for other resources, also, as discussed in #3676.

I recommend we don't change ReplicationController. Since we have chosen the approach of creating new controllers for different use cases, I recommend we introduce the more general selector in all new controllers, such as DaemonSet #1518, Deployment #1743, and Job #1624, before they leave experimental. There are a number of changes I'd like to make to ReplicationController, such as splitting out the template #170, adding controllerRef #2210, and deleting the pods by default #1535. However, I previously proposed renaming ReplicationController to ReplicaSet #3024. We could just create a new ReplicaSet API instead and leave ReplicationController alone.

cc @davidopp @nikhiljindal @erictune @mikedanese

**Comment by smarterclayton** [comment]
ReplicaSet is >>>> a name than RC.

The structure you've described makes sense to me.

On Wed, Sep 16, 2015 at 1:16 PM, Brian Grant <notifications@github.com>
wrote:

> We were working on generalizing the selector semantics prior to the v1 API
> but did not finish in time. Now we have to preserve backward compatibility
> with the v1 API.
>
> Regarding how to move forward with this:
>
> The more general selector semantics cannot be directly represented using
> the old selector syntax. Therefore, we can't simply add new API versions
> using the more general selectors and still be able to directly convert to
> the old representation. Any field that was required, such as
> ReplicationController's selector, can't simply be left unset in lieu of a
> new field, and doing that for optional fields would break clients that
> expected to be able to reason about what the resource was doing, as in the
> case of Service (where a UI might visualize targets) or
> Pod.spec.nodeSelector, where third-party schedulers would not necessarily
> be aware of the new field and therefore would no longer uphold the contract
> specified by the pod.
>
> One option:
>
> Factor the more general selector's requirements into those that can be
> represented using the map syntax and those that cannot. For the latter,
> create a new label (key=value) and apply it to all resources matched by
> that sub-part of the selector (continuously, using a new controller).
> Specify that label in the v1 selector map along with the requirements that
> can be directly represented using the map. This new map-style selector
> should match the same targets as the more general selector and preserves as
> much of the semantic information represented by the more general selector
> as possible.
>
> New API versions would be required for the more general selector. New,
> non-overlapping features can be added without a new API version. However,
> making non-backward-compatible changes to existing features is explicitly
> something that must be done in new API versions. Multiple redundant or
> overlapping fields are highly problematic for clients. See, for example,
> the discussion in #12823
> <https://github.com/kubernetes/kubernetes/pull/12823> or the example in
> the documentation:
>
> https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api_changes.md#on-compatibility
>
> In the case of 2 redundant fields, the old field always must take
> precedence. Old clients cannot be expected to know about the new field. If
> a client reads an API resource, modifies the old field (so the 2 fields are
> now inconsistent), and PUTs the modified resource, the old field must win,
> since this update would have worked before the new field was added.
> Similarly, this is also why the old field must always be populated if the
> new field is set -- so as not to break existing clients interpreting or
> operating on resources.
>
> Clients using the new field can be expected to know about both fields and
> are responsible for setting both consistently. One such case is "kubectl
> apply" #1702 <https://github.com/kubernetes/kubernetes/issues/1702> ,
> where we'll be using the updated user-provided config as a PATCH to the
> live resource. The user can't just update the new field. They need to
> specify the new value for both the old and new fields.
>
> The option I now recommend:
>
> nodeSelector is one example of a scheduling constraint. resources are
> another. Though these are fields on Pod, a core API resource, they
> constitute and API to the scheduler. We intend to add more such
> constraints, as discussed in #367
> <https://github.com/kubernetes/kubernetes/issues/367> and #4301 (comment)
> <https://github.com/kubernetes/kubernetes/issues/4301#issuecomment-74355529>,
> and we recently added scheduling based on resources.request and would like
> to move forward with conflicts #9560
> <https://github.com/kubernetes/kubernetes/pull/9560> . All such features
> must be supported by any third-party schedulers in order to respect the
> pod's API contract. In a sense, adding such constraints breaks
> compatibility with third-! party sch edulers and of any
> tools/UIs/components attempting to reason about scheduling decisions.
> However, we have to be able to add such constraints, just as we add new
> features to Service and to the Pod fields consumed by Kubelet. We should
> announce such changes on kubernetes-dev@googlegroups.com and document
> them clearly in release notes, probably in a special section.
>
> When we add such fields, we'll likely need a fine-grain versioning
> mechanism to gate new features, as discussed in #4855
> <https://github.com/kubernetes/kubernetes/issues/4855>. This is not
> unlike needing to ensure all Kubelets are upgraded before using a
> node-level feature exposed by an upgraded apiserver. We can add such a
> mechanism when there is enough demand from ecosystem developers and/or
> cluster administrators.
>
> For nodeSelector specifically, then, I recommend we deprecate
> nodeSelector, but continue to support it, and add a new field, say
> nodeConstraints, using the more general selector. The new field would not
> be converted to the old. It would just be additional constraints that must
> apply. We could eliminate nodeSelector when we eliminate the v1 API at some
> point in the future.
>
> For Service, a nil selector is already legal. Therefore, we could also add
> a new field, say targetSelector, using the more general selector.
> Anything trying to reason about what the Service targets should already be
> looking at the corresponding Endpoints list, anyway, which would still
> work. We should put an ObjectReference (and maybe link) to the Endpoints in
> status, for the convenience of clients. Having such a reference/query would
> make this problem easier for other resources, also, as discussed in #3676
> <https://github.com/kubernetes/kubernetes/issues/3676>.
>
> I recommend we don't change ReplicationController. Since we have chosen
> the approach of creating new controllers for different use cases, I
> recommend we introduce the more general selector in all new controllers,
> such as DaemonSet #1518
> <https://github.com/kubernetes/kubernetes/issues/1518>, Deployment #1743
> <https://github.com/kubernetes/kubernetes/issues/1743>, and Job #1624
> <https://github.com/kubernetes/kubernetes/issues/1624>, before they leave
> experimental. There are a number of changes I'd like to make to
> ReplicationController, such as splitting out the template #170
> <https://github.com/kubernetes/kubernetes/issues/170>, adding
> controllerRef #2210 <https://github.com/kubernetes/kubernetes/issues/2210>,
> and deleting the pods by default #1535
> <https://github.com/kubernetes/kubernetes/issues/1535>. However, I
> previously proposed renaming ReplicationController to ReplicaSet #3024
> <https://github.com/kubernetes/kubernetes/issues/3024>. We could just
> create a new ReplicaSet API instead and leave ReplicationController alone.
>
> cc @davidopp <https://github.com/davidopp> @nikhiljindal
> <https://github.com/nikhiljindal> @erictune <https://github.com/erictune>
> @mikedanese <https://github.com/mikedanese>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/341#issuecomment-140809259>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bgrant0607** [comment]
Express your support for ReplicaSet on #3024. :-)

**Comment by bgrant0607** [comment]
We're going to try to get the first step of this done ASAP, which is to implement it for one of the new experimental API types, probably Job.

**Comment by derekwaynecarr** [comment]
@bgrant0607 - I follow the problem better now with more study on the issues with adding a new selector field in addition to the old.

To confirm, the new syntax is a super set of the old syntax?  I ask because it seems like we would require all usage of selectors in an API group to follow a common syntax in order to properly support the ?labelSelector parameter in the REST API and kubectl when working with that API version?

**Comment by bgrant0607** [comment]
@derekwaynecarr The new labelSelector string syntax is a superset of the old and was included in 1.0, both in the API (list and watch) and in kubectl -l.

OTOH, the current json type is a map, which is in no way compatible with the more general representation.

Different representations in different API types are likely to lead to confusion, yes. 

However, the bigger issue is that if we introduce the old selector, moving to the new selector is ugly.

**Comment by mikedanese** [comment]
Initial API proposal in #15350

**Comment by bgrant0607** [comment]
Done for Job. Punting the rest to 1.2.

**Comment by davidopp** [comment]
In #15350 we said we would introduce a NodeSelector that is like PodSelector but for selecting nodes. I'm copying some of the notes from there (and adding a couple), since that was a PR and hence not a great place to record general discussion about an issue.

------------------

@bgrant0607 , @mikedanese , and I discussed at some length; I don't have time to summarize the meeting now but one key decision was that this proposal will only apply to pod selection (as @bgrant0607 suggested in the most recent comment in this thread), in particular not to node selection or to human-oriented use cases like queries that a UI might do or a user who wants to do "delete all pods with version > 5". The node selection case will be handled by some other struct that we'll define in the future and will be more general, while the human-oriented cases for now will just do a LIST/WATCH followed by arbitrary client-side filtering.

The main result of the meeting was to decide not to do regexp, numerical comparison, or top-level OR, but we may do "does not exist" pending additional investigation.

------------

Regarding affinity/anti-affinity/attribute limits: I assume that when these are referring to node labels (e.g. max one pod from my collection per host, co-locate in the same availability zone, spread across racks, etc.), we will use the not-yet-designed node label selector struct, and when they are referring to pods (e.g. only put this pod on machines that are already running pods that use or offer a piece of a licensed software that this pod needs, never put this pod on the same machine as pods that are labeled "cache-destroyers", etc.) we will use the struct discussed in this issue.

It just occurred to me that one downside to using different structs for node selection vs. pod selection is that in contexts where you might want to refer to either, we'll always need to have two separate lists. For example, we will want to support both "put this pod on machines that the administrator has labeled as 'foobar'" and "put this pod on machines that are currently running pods that are labeled as 'bizbaz'" as scheduling constraints. With a unified struct this could be expressed in a single list, whereas with the approach we're taking you'd need two separate lists.

------------------

If a pod "infects" a node with an attribute, my opinion is that that should be considered a node label at that point.

\<reply\>: I guess that works, so NodeSelector would be for when you're selecting nodes, regardless of whether the selection is based on labels that are attached to the node or labels that are attached to pods that are on the node. And PodSelector would be for when you're selecting pods.
-------------------

One idea we discussed for node selection is representing general field selectors, and supporting more operations for those selectors. Since labels are a map, individual labels can be treated like fields, in addition to the other attributes of the nodes.

------------------------

New comments
- Swarm supports Go regexp syntax over labels; details here
https://docs.docker.com/swarm/scheduler/filter/
- We should probably introduces "soft selectors" at the same time as we do generalized node selector (equivalent of Borg preferences--feeds into priority function, not predicate function)

**Comment by davidopp** [comment]
BTW I did not intend for that one paragraph to be so huge ... not sure why it was.

**Comment by soltysh** [comment]
In #17787 @sdminonne introduces yet another selector, this time for jobs. Looking at what @mikedanese created in #15350 I think we should rework/rename current PodSelectors to be more generic, at least to LabelSelectors. Since looking at our current use-cases that will best reflect the intentions. I guess that will fall into the category of "soft selectors" @davidopp mentioned above.

**Comment by davidopp** [comment]
I'd argue that for the selector use in #17787 it's better to stick to a regular map to keep the system from becoming too complicated for users to understand. We definitely need a PodSelector and a NodeSelector but I think it's conceivable all the other selectors should be key-value maps like they are today.

**Comment by soltysh** [comment]
@davidopp my initial impression was that all the selectors we use will go the generalized label selector path. If not, I'd like us to clearly define that where that boundary between the two is. I assume your statement is that, am I correct?

**Comment by davidopp** [comment]
I talked to @bgrant0607 ; his feeling (and mine) was that PodSelector should be the "generic selector" we use, and there will only be limited specific cases where we use something else (NodeSelector for selecting nodes may be the only case). So ignore my previous comment.

**Comment by sdminonne** [comment]
@davidopp, @soltysh  I've submitted https://github.com/kubernetes/kubernetes/pull/18011 to rename PodSelector to LabelSelector, let me know if you're ok with that. I'm ok to close it if this is not the plan.

**Comment by davidopp** [comment]
I'm not sure we should rename to LabelSelector, because NodeSelector will also be a form of label selector.

**Comment by sdminonne** [comment]
I agree but I couldn't find a better name even if GeneralizedSelector looked better (finally everyone inside the project call in that way). If you've some ideas I can rename it.

**Comment by soltysh** [comment]
My 2 cents, if PodSelector is the generic one and it should be used as the primary, then LabelSelector  @sdminonne proposes, will do the trick. From there you can always create a specialized selector (such as NodeSelector) which will cover the subset of LabelSelector with application to specific resource.

**Comment by soltysh** [comment]
On the side note, `NodeSelector` is just a field in `PodSpec`, whereas `LabelSelector` will be a type. Unless I'm missing something here.

**Comment by soltysh** [comment]
I think I found the `NodeSlector` you were talking about in [predicates.go](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go), still I think above is true.

**Comment by derekwaynecarr** [comment]
@smarterclayton @bgrant0607 @erictune - I am looking for some guidance on how to handle existing resources, so input appreciated.

I want to add an optional label and an optional field selector to `LimitRange` and `ResourceQuota` so an administrator can define constraints by varying dimensions.  One dimension could be based on `pod.spec.restartPolicy` so pods derived from a `Job` could get different min/max/defaults defined than long running pods derived from a `ReplicationController`, same applies to `ResourceQuota` where I would want to quota differently based on anticipated time of footprint in cluster.  The other dimension would be more open-ended based on end-user specified labels so things with database=mysql get quota differently than things with web=ruby for example.

Should I use the new label selector syntax as seen in `apis/extensions/types.go` or do I stick with the existing v1 syntax for existing resource types?  I suspect I have to stick with the syntax as defined in `v1/types.go` but wanted confirmation before diving too deep.

**Comment by bgrant0607** [comment]
@derekwaynecarr Use the new syntax. Copy/move LabelSelector to v1.

**Comment by derekwaynecarr** [comment]
@bgrant0607 - thanks for the quick reply.

**Comment by bgrant0607** [comment]
This is covered by more specific issues, so closing.
