### ISSUE TITLE
ZSH Completion breaks zsh vi style history search

### ISSUE THREAD

**Issue by kevinkirkup** [kubernetes/kubernetes#34108]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):NO

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): `is:issue is:open zsh completion`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.7+a2cba278", GitCommit:"a2cba278cba1f6881bb0a7704d9cac6fca6ed435", GitTreeState:"not a git tree", BuildDate:"2016-09-23T02:19:56Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: MacBook Pro
- **OS** (e.g. from /etc/os-release): macOS
- **Kernel** (e.g. `uname -a`): Sierra
- **Install tools**: homebrew
- **Others**:

**What happened**:
If you source the kubectl complete for zsh like so:

```
$ source <(kubectl completion zsh)
```

This breaks zsh vi history search.

**What you expected to happen**:
ZSH vi history to work as normal

**How to reproduce it** (as minimally and precisely as possible):

In `.zshrc`, enable the `vi-mode` plugin from _oh-my-zsh_
This should allow to hit the `ESC-/` to perform a history search.

Without source the `kubectl` completion, the command works normally.
After sourcing the `kubectl` completion, zsh prompts:

```
zsh: do you wish to see all 16016 possibilities (16144 lines)?
```

Select 'n' for NO and drops back to the prompt.

**Anything else do we need to know**:
It seems like `kubectl` completion is conflicting with `vi-mode` plugin potentially overwriting the previous configuration.

If I source `vi-mode` after `kubectl`, everything works as expected.

**Comment by kevinkirkup** [comment]
@kubernetes/sig-cli-misc

**Comment by cpick** [comment]
@kevinkirkup your issue may have been due to zsh itself.  Please see [this Superuser question](https://superuser.com/questions/476532/how-can-i-make-zshs-vi-mode-behave-more-like-bashs-vi-mode).
