### ISSUE TITLE
[SUGGESTION] Add NodePort value in output

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/kubernetes#34100]
When developing apps I often create a nodePort or switch to NodePort temporarily.

It would be great if the output of `kubectl get svc` could show the value of the NodePort.

That would save me/us from having to do a --format or -o ...

Something like:

```
$ kubectl get svc foobar
NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)                AGE
foobar        10.0.0.98         <nodes>            9090:32410/TCP   9m
```

**Comment by AdoHe** [comment]
@kubernetes/kubectl @thockin

**Comment by zreigz** [comment]
I can take this

**Comment by AdoHe** [comment]
@zreigz that would be great, go ahead and leave comments here if any problem.

**Comment by zreigz** [comment]
OK, thanks

**Comment by zreigz** [comment]
We can close it

**Comment by sebgoa** [comment]
Yes, thank you
