### ISSUE TITLE
Deduplication of List/Watch code.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#3412]
- [ ] Have a single go implementation of the "List then Watch" pattern. Use this everywhere.
  - This is about hiding the details of calling list and watch and restarting watches. 
  - This is about apiserver watches.  Etcd use cases going away, so don't worry about them.
  - The `Reflector` object in `pkg/client/cache` is trying to be this.
  - [ ] Reconcile duplicated implementations in `pkg/proxy/config` and `pkg/client/cache` (the latter used by scheduler, and by kubelet after #3385 is merged.  differences include:
    - [ ] Jittering in `pkg/proxy/config/api.go`, 
    - [ ] resource-specific `ServicesWatcher` interface in `pkg/proxy/config` vs generic `ListerWatcher` interface in `pkg/client/cache`.
    - [ ] one writes complete state to a Store and the other writes deltas to a channel. 
    - [ ] differences in error handling in the watch implementations: make sure we keep best from each.

**Comment by erictune** [comment]
@saad-ali we talked about this.  Maybe this issue is interesting to you.

**Comment by pmorie** [comment]
@erictune is this the context for your undelta store?

**Comment by erictune** [comment]
It is definitely related to UndeltaStore.  UndeltaStore was written before I understood the code as well, so I might have done it differently now.

**Comment by erictune** [comment]
Also, cluster/addons/dns/kube2sky/kube2sky.go and pkg/controller/replication_controller.go

**Comment by erictune** [comment]
@lavalamp i took the liberty of unassigning you because I think you have lots on your plate and I think a "newber" might want to pick this up.

**Comment by lavalamp** [comment]
Ah, that's fine-- I was trying to collect all the issues related to controller framework. I'm definitely working on the first checkbox in this issue.

**Comment by a-robinson** [comment]
Checking in -- does any common code exist for this yet?

**Comment by lavalamp** [comment]
@a-robinson #5473 almost in; there'll be (at least) one follow-up, hopefully this week.

**Comment by a-robinson** [comment]
Thanks, looks like it just made it in. I'll switch from using the proxier config to try this out instead.

**Comment by smarterclayton** [comment]
This was completed a long time ago and is now published in client-go.
