### ISSUE TITLE
Daemons on nodes need to export metrics to heapster

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#34125]
We need to export node and pod level metrics from kube-system daemons to heapster, so they eventually get ingested into the clouds. This is required for debugging systems in production.

We seem to have more than 1 metrics pipeline today. The one that seems immediately usable is: 
Heapster -> kubelet  -> cadvisor -> custom-metrics config-map -> pods

Where "custom-metrics config-map" is a bridge from pod metrics (http endpoints) to cadvisor, eg: http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/#pod-configuration

But according to the doc, this would require a hostPort per pod, which doesn't scale. 
@kubernetes/sig-node @davidopp  what's the best way to do this? 

Or should we just write our own little helpers that scrape daemon specific prometheus endpoints and push to cloud for now?

**Comment by vishh** [comment]
We can update cAdvisor to not require host ports and instead use the
container's IP.

**Comment by bprashanth** [comment]
SG. It would also be nice to not have the monitoring component compiled into the kubelet, so we can see what's going on if the kubelet crashes, but I think that's a secondary goal to getting something that work across the board.

Can you clarify the cases:
* If I want to track some random dns metric for the entier cluster, we need a kubedns config map
* If I want to track a per node custom metric, I bypass cadvisor entirely?
* If I want to track a per pod dns metric, but exposed through a kubedns endpoint, I need a config map in each pod that proxies to the kube-dns endpoint for itself?

**Comment by piosz** [comment]
@bprashanth the way you mentioned is a deprecated alpha feature, which wiil be removed in 1.5(?). We are working on the Monitoring v2 which will allow gather such metrics easily. You can take a look into [the proposal](https://docs.google.com/document/d/1z7R44MUz_5gRLwsVH0S9rOy8W5naM9XE5NrbeGIqO2k/edit) or reach me or @fgrzadkowski if you have any questions.

**Comment by bprashanth** [comment]
Great, so should we develop to the new api if we want to ship better metrics for system components in 1.5 (i.e when's the new api going to alpha)?

**Comment by bprashanth** [comment]
So I think tldr from offline discussion is: expose a `/metrics` endpoint with the required metrics in prometheus format (https://prometheus.io/docs/instrumenting/exposition_formats/) from clusteraddons/static-pods and this will just work when the final solution is out. @piosz correct me if I'm wrong. If not I'll fork off into bugs for kube-proxy and kube-dns.

**Comment by piosz** [comment]
This is the right approach. Other Kubernetes components (for example api server) also uses such endpoint to export metrics.

**Comment by cmluciano** [comment]
I think this issue has since been resolved in kube-proxy. Do we think this is stale now @piosz ?

**Comment by piosz** [comment]
@cmluciano metrics are exposed by kube-proxy in Prometheus format, so I'd close this. Feel free to open if I'm anything else needs to be done here.
