### ISSUE TITLE
Use owner ref to calculate pod statistics in federated replicaset controller 

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#34130]
Right now the controller list all pods to calculate the stats.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @mwielgus

**Comment by dims** [comment]
@mwielgus @matchstick all issues must be labeled either release blocker or non release blocking by end of day 18 November 2016 PST. (or please move it to 1.6) cc @kubernetes/sig-cluster-federation

**Comment by madhusudancs** [comment]
Not a v1.5 release blocker.

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by quinton-hoole** [comment]
I'm not sure that this is still an issue, but leaving open until someone can confirm definitively.

**Comment by quinton-hoole** [comment]
@mwielgus is no longer working on this, as far as I know, so unassigning him.  Feel free to re-assign as necessary.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#78.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
