### ISSUE TITLE
Volume metrics exposed in /stats/summary not available in /metrics

### ISSUE THREAD

**Issue by vjsamuel** [kubernetes/kubernetes#34137]
Kubernetes Version: 1.3

On hitting `http://node:10255/stats/summary` I am able to see volume metrics like:

```
"volume": [
     {
      "availableBytes": 92852543488,
      "capacityBytes": 92852555776,
      "usedBytes": 12288,
      "name": "default-token-eb5uv"
     }
    ]
```

but the same metrics are not available when I hit `http://node:10255/metrics`.

Im under the assumption that all metrics are equally available on both endpoints. We use prometheus today to do our timeseries metric storage and because of this gap we are not able to see volume usage on prometheus.

**Comment by micahhausler** [comment]
@timothysc I'd be happy to make a PR that adds this, but I'm not sure where I'd need to add this. Would this be a cadvisor patch or a k8s patch? What package might that take place in?

**Comment by timstclair** [comment]
Volume stats collection is currently only in the Kubelet, so this would be a Kubernetes patch. I believe we don't currently translate the Summary metrics (including volume) into prometheus metrics. Most stats are translated in cAdvisor directly, and some additional Kubelet specific stats are translated [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/metrics/metrics.go). I'm not sure whether it makes sense to plumb the Summary through to that metrics collector or not.

@dashpole may have more thoughts.

**Comment by micahhausler** [comment]
I don't have a great way of monitoring PVC device usage without adding it to the kubelet `/metrics`. I already have prometheus set up, and cAdvisor doesn't pick up mounts from an EBS volume. Is there a better way to monitor PVC device usage?

**Comment by micahhausler** [comment]
Is this an accepted feature?

**Comment by javefang** [comment]
Up vote for this feature! We also have prometheus set up but it can't monitor PV usage currently due to the missing metrics under the /metrics path. Since kubelet seems to have the data already (/stats/summary), it might be a good idea to expose them under /metrics?

**Comment by jingxu97** [comment]
I am working on this feature, assign the issue to myself. Will send out a proposal soon.

**Comment by cofyc** [comment]
@jingxu97 
Any progress on this?

**Comment by jingxu97** [comment]
I have a proposal in the community https://github.com/kubernetes/community/pull/855
@vkamra is currently working on the feature.

**Comment by vkamra** [comment]
@cofyc @javefang  - Take a look at the proposal Jing linked above. I'm currently working on the first part of this which is adding PVC information to the kubelet stats summary. After that, we should be able to expose that via prometheus metrics.

There was some discussion in the last sig meeting whether the metric exposed needs to be indexed by PVC name or if PodName + Pod Volume Name is sufficient. Can you provide some input on that for your use case?

**Comment by cofyc** [comment]
@vkamra 

hi, what we plan to do in our production cluster are:

- monitor PVC status and capacity requested (we use [kube-state-metrics](https://github.com/kubernetes/kubernetes) to monitor PVC objects)
- monitor volume capacity (in bytes) (total and per volume) (1)
- monitor volume used (in bytes) (total and per volume) (2)
- monitor volume available (in bytes) (total and per volume) (3)
- monitor volume inodes/used/free (same as above)

For (1), (2), (3), we need volume metrics to be associated with PVC/PV objects. Because users create PVC objects to request PV. Pod name often is generated by controller (e.g. deployment), pod volume name is meaningless outside of Pod. For monitoring and alerting, these metrics is better to be associated with PVC, then uses can know which PVC they created is near full for example.

I think VolumeStat indexed by PodName + Pod Volume Name is sufficient as long as VolumeStat includes PVC/PV references. But in `/metrics` endpoint,  which is consumed by prometheus directly, volume metrics needs to include PVC & PV labels.

**Comment by jingxu97** [comment]
Hi @cofyc We added the PVC ref into volume metrics in 1.8 https://github.com/kubernetes/kubernetes/pull/51448
Now you should be able to see the information through /metrics endpoint. Please let us know if you have any issue with it. Thanks!

**Comment by cofyc** [comment]
@jingxu97 Awesome! I will try it in our clusters.

**Comment by jingxu97** [comment]
@cofyc, @vjsamuel @javefang @micahhausler  we continue to work on expose volume metrics in Kubernetes. Just want to collect more feedback on this. One question come up is whether users prefer to get volume usage information in
1) Inside of Pod stats, volume stats contains PVC reference (namespace, PVC name) 
2) PVC stats is exposed separately from Pod. So the metric has PVC name (possibly PV name) and the usage/capacity information.

If we choose option 2, will users want to know which pod is using the PVC? (from PVC name to get Pod name?) Thanks!

**Comment by javefang** [comment]
To us having the volume stats separate is easier for us to template the
Grafana dashboard. And knowing which pod mounted the PVC is good too so we
can link it to the pod.

Many thanks

Xinghong

**Comment by dzr0001** [comment]
Hello,
I can confirm that on 1.9.2 the volume stats from /stats/summary are still not available in the /metrics endpoint. Are there still plans to implement this?

Thanks!

/remove-lifecycle rotten

**Comment by HaveFun83** [comment]
I have the same issue on 1.10.0

**Comment by jingxu97** [comment]
I think after this PR https://github.com/kubernetes/kubernetes/pull/59170, you need to set up [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) to get the metrics

**Comment by gowthampatil** [comment]
I have one requirement that is,
with out port number(10255) I need to run. that port is blocked we dont have access to open that port. is there any way without using port number.

**Comment by seleznev** [comment]
> I think after this PR #59170, you need to set up kube-state-metrics to get the metrics

Looks like PR #59170 about PVC only. But with `/stats/summary` you can get stats for all mounted volumes (including emptyDir, secrets, etc).
