### ISSUE TITLE
monitoring-grafana service doesn't seem to work

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#34154]
I've never actually used grafana before. 
The kube-up logs say:

```
Grafana is running at https://104.197.163.84/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
```

But hitting that url gives:

```
Forbidden: "/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana"
```

I tried hitting it through the proxy, but got:

```
$ curl localhost:8001/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/
{"message":"Invalid API key"}
```

I figure exposing it as type=loadbalancer would give me some ui. It doesn't, the loadbalancer ip shows:

```
{{alert.title}}
```

Looking at the javascript on that page, it reads like I'm not logged in. Is there some url path I need to hit? 
@apelisse any idea, since you setup similar dashboards?

**Comment by yujuhong** [comment]
I created a similar issue long ago #15727. The issue got closed but I never knew if it was fixed. 

/cc @mwielgus

**Comment by bprashanth** [comment]
If no one cares we should just not waste cpu and delete the thing. 
If we care we should probably surface some nice docs, or at least the kube-up logs should give a usable link. 
Grafana logs have: 
```
2016/10/06 00:14:01 [I] Completed 10.180.1.1 - "GET /api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/public/app/app.ca0ab6f9.js HTTP/1.1" 404 Not Found 23 bytes in 718us
2016/10/06 00:14:03 [I] Completed 10.240.0.4 - "GET /api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/public/img/fav32.png HTTP/1.1" 404 Not Found 23 bytes in 643us
2016/10/06 00:14:03 [I] Completed 10.180.1.1 - "GET /favicon.ico HTTP/1.1" 404 Not Found 2953 bytes in 1243us
```

So it looks like it's assuming it will always be accessed via kube master-proxy (but users actually using it will probably expose it through a loadbalancer), and the kube master-proxy is forbidding me from hitting it (i.e all the master proxy requests in my first comment don't show up in logs).

**Comment by shashidharatd** [comment]
I too am facing this issue since a week, unable to open the dashboard.
```
Kubernetes master is running at https://104.155.218.0
GLBCDefaultBackend is running at https://104.155.218.0/api/v1/proxy/namespaces/kube-system/services/default-http-backend
Heapster is running at https://104.155.218.0/api/v1/proxy/namespaces/kube-system/services/heapster
KubeDNS is running at https://104.155.218.0/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://104.155.218.0/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
Grafana is running at https://104.155.218.0/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at https://104.155.218.0/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb
```

Forbidden: "/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard"

**Comment by janjilek** [comment]
some workaround?

**Comment by bprashanth** [comment]
Maybe we have 2 issues, proxy doesn't work as intended, and grafana still doesn't work. @kubernetes/sig-api-machinery  (who's responsible for the proxy?)

**Comment by chandresh-pancholi** [comment]
I have given read access to a user and trying to access graphana dashboard. I am also getting same error.
Any idea what could be the reason?

**Comment by foxish** [comment]
It appears to work when I use `kubectl proxy` and then access the same relative url;
```
http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/dashboard/db/cluster
http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/
```

```
~ kubectl version
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.1862+59cfdfb8dba60e", GitCommit:"59cfdfb8dba60ec31dc5c2d2d720f9f26b551d46", GitTreeState:"clean", BuildDate:"2016-12-14T17:56:18Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by bprashanth** [comment]
yeah i guess it works now and I hope it continues to do so
