### ISSUE TITLE
error validating data: couldn't find type: v1.pod

### ISSUE THREAD

**Issue by amolsh** [kubernetes/kubernetes#34210]
Hi , I am following  Kubernetes 101 guide to learn kubernetes.

Following is my nginx-pod.yml file:

apiVersion: v1
kind: pod
metadata:
   name: nginx
spec:
   containers:
     - name: nginx
       image: nginx:1.7.9
       ports:
          - containerPort: 80

Command fired:   kubectl create -f nginx-pod.yml

Error:
error validating "nginx-pod.yaml": error validating data: couldn't find type: v1.pod; if you choose to ignore these errors, turn validation off with --validate=false

What is root cause of this error?

**Comment by amolsh** [comment]
kubectl get pods --all-namespaces  

![image](https://cloud.githubusercontent.com/assets/10971917/19143064/1a55b6e2-8bbf-11e6-82c8-23f743c1e6cc.png)

**Comment by gluke77** [comment]
@amolsh it should be 'kind: Pod'. Mind the case of 'p' in 'Pod'. With the above does it still fail?

**Comment by svanscho** [comment]
I am running into the exact same issue. Any update?

**Comment by amolsh** [comment]
Have you tried above mentioned solutions? In my case that was the only
issue.

**Comment by fabianofranz** [comment]
Using `kind: Pod` should fix the issue. I'll close it, feel free to reopen if the issue persists.

**Comment by 992441831** [comment]
> @amolsh it should be 'kind: Pod'. Mind the case of 'p' in 'Pod'. With the above does it still fail?

yes,It's true

**Comment by 992441831** [comment]
> @amolsh it should be 'kind: Pod'. Mind the case of 'p' in 'Pod'. With the above does it still fail?

very good
