### ISSUE TITLE
very long failover time on compute node non-graceful failure 

### ISSUE THREAD

**Issue by sbezverk** [kubernetes/kubernetes#34238]
Running kubernetes 1.4.0 5 nodes cluster and testing non-graceful node failure scenario. The failover time for pods to move from failed node was 12 minutes. Failed node was declared NotReady relatively fast 1-2 minutes, but then pod on failed node stayed in running state for approx 8 minutes which is really strange. Pod terminating phase added another 3-4 minutes. I am looking for ways to reduce last time phases. Appreciate any suggestions.

**Comment by sbezverk** [comment]
After changing these two timers  --node-monitor-grace-period 20s --pod-eviction-timeout 1m0s this failover time got improved, but not completely. It appears pods get stuck in Terminating state. It is not a problem for rc and deployment as they start new pod very quickly, but for petset it is a problem as it waits for pod to be completely gone before starting new pod. Using kubectl delete --now helps, is there any hooks or timers which can reduce time a pod stays in Terminating state?

**Comment by C0NO** [comment]
> After changing these two timers --node-monitor-grace-period 20s --pod-eviction-timeout 1m0s this failover time got improved, but not completely. It appears pods get stuck in Terminating state. It is not a problem for rc and deployment as they start new pod very quickly, but for petset it is a problem as it waits for pod to be completely gone before starting new pod. Using kubectl delete --now helps, is there any hooks or timers which can reduce time a pod stays in Terminating state?

**how could change that timers ? i do not have kube-controller-manager on my cli.I have only kubeadm kubelet and kubectl**

**Comment by sosogh** [comment]
> **how could change that timers ? i do not have kube-controller-manager on my cli.I have only kubeadm kubelet and kubectl**

you can add there two parameters in file :/etc/kubernetes/manifests/kube-controller-manager.yaml
after saving it ,   k8s will recreate the kube-controller-manager pod automaticlly .
But in my case ,there is no effect ,  It still take quite some minutes to take failover . 
(node is marked as notready as expected , but the pod will not be recreated as "--pod-eviction-timeout"  )

refer: https://stackoverflow.com/questions/53641252/kubernetes-recreate-pod-if-node-becomes-offline-timeout
