### ISSUE TITLE
Azure volumes do not work in hyperkube: missing mount.cifs

### ISSUE THREAD

**Issue by Arachnid** [kubernetes/kubernetes#34236]
**Kubernetes version** (use `kubectl version`): 1.4.0

**Environment**:
- **Cloud provider or hardware configuration**: Azure

**What happened**:
Trying to mount an Azure file share by following the directions [here](https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/azure_file) fails because hyperkube does not include cifs-utils (eg, `mount.cifs`).

Can this be added to the hyperkube image, please?

**Comment by jingxu97** [comment]
@saad-ali, is this related to GCI image missing nfs related package?

**Comment by colemickens** [comment]
This should fix the reported issue: #34416

**Comment by Arachnid** [comment]
Thanks for fixing this so quickly!

**Comment by saad-ali** [comment]
> @saad-ali, @vishh is this related to GCI image missing nfs related package?

No, unrelated
