### ISSUE TITLE
Default value or optional case for secretKeyRef/configMapKeyRef

### ISSUE THREAD

**Issue by thekantian** [kubernetes/kubernetes#34240]
This is a feature request. Currently, it is not possible to set a secretKeyRef/configMapKeyRef as optional in a Pod's definition. It's also not possible to specify a default. This means that even if the program running inside the containers in the pod has sensible defaults which need only be overwritten in some environments, all secret k/v pairs must be updated in all environments before pods with new secretKeyRefs can be started.

The use case here might be a dev environment maintained by a less sophisticated user, where the overhead of managing secrets can be additional work that wastes time and resources. In the production case, a more sophisticated user has no trouble adding the secrets before editing the pod definitions. In many cases the default secret values can be left in the program itself and thus the secret is an un-necessary second layer of admin work that is needed.

I've looked around for other tickets/threads talking about this issue, haven't found any. Open to why this would be a bad idea or too complex to implement, but in practice there are setups where I think it adds value.

**Comment by jonaz** [comment]
This is accually a rather big problem. I would expect undefined env variables just to get empty string. Not to be prevented from starting. Or even better be able to set a default value in the rc of that secretKeyRef or configMapKeyRef.

**Comment by ankon** [comment]
https://kubernetes.io/docs/api-reference/v1.5/#configmapkeyselector-v1 has no 'optional' field, but https://kubernetes.io/docs/api-reference/v1.6/#configmapkeyselector-v1-core does have it. I guess this means this is "solved" in 1.6?

**Comment by thekantian** [comment]
Yes, I would agree, this issue is solved by optional EnvVar options.
