### ISSUE TITLE
Document what all the labels mean with regard to issues and pull requests

### ISSUE THREAD

**Issue by jessfraz** [kubernetes/kubernetes#34255]
Here is an example of what I'm talking about https://github.com/docker/docker/blob/master/project/REVIEWING.md and https://github.com/docker/docker/blob/master/project/ISSUE-TRIAGE.md

I would do this myself but I actually don't know what all the labels mean, what they trigger, and what they do.

Questions to be answered for each label:
Name:
Does it trigger something?
Is it required for merging/cherry-picking/some other process?
Is this label only for use by bots?
Does this label only apply for issues?
Does this label only apply for PRs?
Is this label required for merge if and only if the moon is 45 degrees left of the Sun and it is the first Monday in October?

**Comment by jessfraz** [comment]
ping @kubernetes/contributor-experience

**Comment by grodrigues3** [comment]
yeah, this is an issue that I've been thinking about.  I have the auto issue-labeler set up, but many of the labels are unused/unclear.  I'll bring this up at the next contribx

**Comment by jessfraz** [comment]
@grodrigues3 if you want I'd be happy to sit with you and do it, I just don't have the knowledge as to how they all work currently but I'm super interested to know

**Comment by bgrant0607** [comment]
Thread on label overhaul: https://groups.google.com/forum/#!topic/kubernetes-wg-contribex/mI7kuTFa_I4

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/remove-priority important-soon
/priority critical-urgent
Hi @kubernetes/sig-contributor-experience-misc-use-only-as-a-last-resort I think we should make this a priority for 1.10

**Comment by spiffxp** [comment]
Before getting too caught up in the color of the bikeshed, my hope would be that we proceed something like:
- first add a `description:` field in `labels.yaml` and add descriptions to all of the labels there
- _then_ decide what consumes that field, and what sort of "user friendly" docs should be generated from it
- setup said tool such that docs are auto-generated (or just served live!) everytime a PR adds to that file

**Comment by nikhita** [comment]
https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.md :tada:

/close
