### ISSUE TITLE
Document Ingress TLS Secret format requirements

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#34258]
Ingress can pull TLS assets out of a Secret... Is the expected format of those asserts documented anywhere? (aka, "The Cert and Key fields of the secret must be PKCS8 encoded")?

**Comment by bprashanth** [comment]
This is left up to the ingress controller, each implementation has its own limitations (eg: https://github.com/kubernetes/kubernetes/issues/24669).
The TLS section of the ingress points to a secret. 
TLS is a type of secret, with k/v as defined in: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L2874
Such a secret can be created via `kubectl create secret tls`: http://kubernetes.io/docs/user-guide/kubectl/kubectl_create_secret_tls/, which spits out an error if the cert/key pair don't match (validates x509 key pair, we should be validating the chain https://github.com/kubernetes/kubernetes/issues/27010). 

That's about the only limitation. You can bypass kubectl and create your own secret with the same k/v, and the controllers will work if the secret makes sense to them.

**Comment by colemickens** [comment]
Is there a reason that there was a prescription made here? At least if there was a standard format for the certs "at rest" in the Secret, each Ingress implementation could expect them in that format and include code to transform them for their need.

**Comment by colemickens** [comment]
edit: "Is there a reason that there was *not* a prescription made here for the format of the fields of the Ingress TLS Secret?

**Comment by cmluciano** [comment]
/assign

/close

Documented here https://github.com/kubernetes/ingress/tree/master/controllers/nginx#https

**Comment by cmluciano** [comment]
/close

Documented here https://github.com/kubernetes/ingress/tree/master/controllers/nginx#https
