### ISSUE TITLE
Expand test coverage for affinity

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes/kubernetes#34253]
Quoting @davidopp from [issue 22985 (comment)](https://github.com/kubernetes/kubernetes/pull/22985#issuecomment-216020283):

> I would do the topologKeys in the priority tests differently (to test something more realistic). The tests are correct, they just aren't the typical scenarios, like two nodes with the same zone and different hostname, plus one node in a different zone. (you wrote them before I clarified how topologyKey works). This wouldn't require major changes, mostly just changes to the node labels and topologyKey in the affinity requests. Also, I think it would be better if the priority tests all had more than two nodes, because when you only have two nodes, the only priority scores you can have are 0 and 10, so it's hard to know if the actual weights that were computed (before normalizing) were correct.

**Comment by ConnorDoyle** [comment]
cc @kubernetes/sig-scheduling

**Comment by timothysc** [comment]
Yup @rrati is working on this now.

**Comment by jayunit100** [comment]
There are incorrect stuff in the priority tests also #33198 , I think the scheduler needs to iterate through pods inside of processTerms.  

prototype PR that does that and spreads scores around 0-10 with more subtlety (#33199)
