### ISSUE TITLE
Items needed from Open-Api Spec extensions for documentation

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#34254]
# Background

The open-api spec is missing many concepts present in the Kubernetes api.  These concepts are crucial to understanding the API, but because they are not present in the open-api spec, consumers of the spec lose this information.  In order to produce high-quality documentation and language-specific clients, the api concepts must be added to the open-api.json as extensions.

Examples:
- There is no concept of operations being tied to specific objects, such as `Create` operating on `Deployment`, however conceptually this is how our api is architected
- There is no concept of having the same operation work on different objects, such as `Create` existing in several forms for different object definitions
- There is no concept of an object definition's API *Group*, *Version* or *Kind*.  e.g. *Batch*, *v1Beta1*, or *CronJob*.  All of these fields get merged together into a single key, but the context is lost.

# Proposal

Extend open-api to retain this critical information about the API in the open-api.json file so that it can be parsed by client generators.

# Minimal Extensions

## Definitions

- [x] Group (e.g. Batch)
- [x] Version (e.g. v1) *p0*
- [x] Kind (e.g. Deployment) *p0*
- [x] Alternate Versions (e.g. v1.Job -> v1beta1.Job)
- [ ] Sub-Resource

```json
...
"v1beta1.Deployment": {
    "description": "Deployment enables declarative updates for Pods and ReplicaSets.",
    "x-kubernetes.io": {
      "group": "extensions",
      "version": "v1beta1",
      "kind": "Deployment",
      "alternate_versions": ["v1", "v1alpha1"]
   },
   ...
},
...
"v1beta1.DeploymentList": {
    "description": "DeploymentList is a list of Deployments.",
    "x-kubernetes.io": {
      "group": "extensions",
      "version": "v1beta1",
      "kind": "DeploymentList",
      "alternate_versions": ["v1", "v1alpha1"],
      "parent_resource": {
          "$ref": "#/definitions/v1beta1.Deployment"
      },
   },
},
...
```

# Operations
- [x] Name (e.g. Create / Replace / Patch / Get / List / List All / Watch / Scale / Update Status)
- [ ] Definition (e.g. v1beta1.Deployment / v1.Service / v1.ConfigMap)
- [ ] Namespaced (e.g. true / false)

```json
"/apis/extensions/v1beta1/namespaces/{namespace}/deployments": {
    "get": {
      "x-kubernetes.io": {
        "schema": {
          "$ref": "#/definitions/v1beta1.Deployment"
        },
         "name": "List",
         "display_name": "List",
         "namespaced": true,
       },
       ...
       "tags": [
        "extensions_v1beta1"
       ],
       "operationId": "listExtensionsV1beta1NamespacedDeployment",
       ...
    },
    "post": {
      "x-kubernetes.io": {
        "schema": {
          "$ref": "#/definitions/v1beta1.Deployment"
        },
         "name": "Create",
         "display_name": "Create",
         "namespaced": true,
       },
       ...
       "tags": [
          "extensions_v1beta1"
       ],
       "operationId": "createExtensionsV1beta1NamespacedDeployment",
       ...
    },
    "delete": {
      "kubernetes.io": {
        "schema": {
          "$ref": "#/definitions/v1beta1.Deployment"
        },
         "name": "DeleteCollection",
         "display_name": "Delete Collection",
         "namespaced": true,
       },
      ...
       "tags": [
          "extensions_v1beta1"
       ],
       "operationId": "deleteExtensionsV1beta1CollectionNamespacedDeployment",
    },
    ...
   },
```

# Additional Extensions

## Definitions

- [ ] Category (e.g. Workload, Service Discovery)

## Operations
- [ ] Category (e.g. Read, Write)

**Comment by pwittrock** [comment]
cc @pwittrock
cc @lavalamp

**Comment by mbohlool** [comment]
For Definitions, we can add them all today as a comment tag for types.

For Operations, with current use of gorestful, we can only have hacky ways to implement them, and we need to change (hack) gorestful too. My plan for next version is to have a IDL (something like proto services) for routes so we can add tags/comments to each route and it would be the best way to implement above operation extensions. Can this wait till 1.6?

Also, I don't understand second item on the operation list (Definition (miss-spelled?)). Is the the main restful object this operation operate on?

**Comment by lavalamp** [comment]
Can this be closed?

**Comment by mbohlool** [comment]
There are less important tasks remains in this. @pwittrock can you look at them again and see if we need all of them.
