### ISSUE TITLE
Implement federated Job

### ISSUE THREAD

**Issue by jianhuiz** [kubernetes/kubernetes#34261]
To track the implementation of `job` in federation

cc @kubernetes/sig-cluster-federation
@deepak-vij @kshafiee @shashidharatd

**Comment by jianhuiz** [comment]
Design doc: https://docs.google.com/document/d/1TZ4ZMZ8AEOlVyK6H_q-zNpAdlzTip8sxMQUVQeQ-O-w/edit?usp=sharing

**Comment by quinton-hoole** [comment]
@nikhiljindal @mwielgus @kubernetes/sig-scheduling PTAL.  This looks sound to me, but I've not examined K8s Jobs in any great detail.  Would appreciate outside input.  

Is @kubernetes/sig-scheduling the right place to send this for review outside of @sig-federation?  Or is there a different SIG that thinks about batch workloads?

@jianhuiz I think it's safe to go ahead with a preliminary implementation in the federation control plane and incorporate further feedback from the relevant SIG in a second pass.

**Comment by davidopp** [comment]
> Is @kubernetes/sig-scheduling the right place to send this for review outside of @sig-federation? Or is there a different SIG that thinks about batch workloads?

TBH I would just have @erictune review it. He was deeply involved in the design of Job. sig-apps might be relevant.

**Comment by quinton-hoole** [comment]
OK, Thanks.  @erictune I would most appreciate it if you could take a quick look aver this design doc and share any thoughts you might have w.r.t. Jobs.  Fortunately it's a nice, short 1-pager.

Q

**Comment by quinton-hoole** [comment]
Ping @erictune

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @quinton-hoole @erictune @nikhiljindal @jianhuiz

**Comment by erictune** [comment]
@soltysh can you take a look at this?

**Comment by soltysh** [comment]
Sure, will look into it first thing in the morning.

**Comment by soltysh** [comment]
@dims do we really want this to have in 1.5? I don't feel so strongly about it, being this late in the code freeze, to be honest.

**Comment by dims** [comment]
glad to hear that @soltysh let me move the milestone to 1.6

**Comment by soltysh** [comment]
Sorry for the timing, I'm a bit behind with my backlog. The proposal seems reasonable, thought the first and most important question Eric stated at the beginning is use-case justifying the need for such controller. I don't have access to the federate ReplicaSet doc, so I can't compare with the other. I'd like to learn more about it, though :)

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.
