### ISSUE TITLE
Support Volumes and Mounts for Windows Containers

### ISSUE THREAD

**Issue by jbhurat** [kubernetes/kubernetes#34264]
As we continue to make progress on supporting Windows Containers for Kubernetes, the next logical thing to tackle is supporting volumes and mounts. This issue is to track the work required to make volumes and mount work on Windows containers

**Comment by jbhurat** [comment]
Closing this issue as it is duplicated of https://github.com/kubernetes/kubernetes/issues/30282

**Comment by fengli858** [comment]
Does Azure ACS support volumes and mounts for Windows Container Now? 
I search this information on web for while, but I am not able to find it. 
Thanks!
