### ISSUE TITLE
CRI: Timestamp unit is not defined

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#34272]
There are several timestamps in CRI:
* [`PodSandboxStatus.CreatedAt`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/v1alpha1/runtime/api.pb.go#L816)
* [`PodSandbox.CreatedAt`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/v1alpha1/runtime/api.pb.go#L975)
* [`Container.CreatedAt`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/v1alpha1/runtime/api.pb.go#L1744)
* [`ContainerStatus.CreatedAt/StartedAt/FinishedAt`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/v1alpha1/runtime/api.pb.go#L1866-L1870).

All of them are defined as `int64`, but we didn't define the unit of the timestamp, is it `second` or `nanosecond`?

Currently, kuberuntime treats it as second https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_container.go#L380-L389.
However, dockershim returns it as nanosecond https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/docker_container.go#L204 (docker returns RFC3999Nano)

We should define the timestamp unit in CRI, and nano second should be ideal.

@yujuhong @feiskyer @yifan-gu 
/cc @kubernetes/sig-node

**Comment by Random-Liu** [comment]
Another small issue is that, `CreatedAt` of `runtimeApi.PodSandbox` and `runtimeApi.Container` is populated correctly.
1) The creation time returned by `docker ps` is **in second**, but we are using it directly.
2) The creation time of `runtimeApi.Container` is not populated https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/convert.go#L60-L69

**Comment by yujuhong** [comment]
> 2) The creation time of runtimeApi.Container is not populated https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/convert.go#L60-L69

`ContainerStatus.CreatedAt` was introduced later in the kuberuntime GC PR, hence it was not populated in the `dockershim`. Surprisingly, no test has failed since then. 

> We should define the timestamp unit in CRI, and nano second should be ideal.

SGTM.

**Comment by Random-Liu** [comment]
The create time is only used to sort containers before gc.
It seems that golang's sort algorithm is [stable sort](https://golang.org/src/sort/sort.go), then the sequence will not be changed because all creation timestamp is 0. And because docker always returns the right order, so it doesn't really matter for docker. :)

**Comment by Random-Liu** [comment]
NVM, I read the code more carefully...golang is using quick sort. But it may still doesn't change the order. :)

**Comment by yifan-gu** [comment]
I found this same issue the other day, but then forgot to mention :)
64-bit nanosecond seems fine to me as it rewinds about 600 yrs later.

**Comment by feiskyer** [comment]
LGTM
