### ISSUE TITLE
Make serial tests for CRI-docker integration green

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#34289]
The new node/cluster serial builders have been up and running (thanks to @Random-Liu)!
https://k8s-testgrid.appspot.com/google-node#kubelet-cri-serial-gce-e2e
https://k8s-testgrid.appspot.com/google-gce#gci-gce-cri-serial

We need to triage and fix the failures. 

/cc @kubernetes/sig-node

**Comment by yujuhong** [comment]
Uploaded #34991 to properly run "resource usage tracking tests" on GCI.
Also filed #34999 for a network teardown issue that's been causing many test failures in the cluster e2e serial suite.

**Comment by feiskyer** [comment]
The following tests are failed in all serial tests (including gce-serial and gci-gce-serial), @yujuhong  is there any known problem for this?

- [k8s.io] Nodes [Disruptive] [k8s.io] Network when a node becomes unreachable All pods on the unreachable node should be marked as NotReady upon the node turn NotReady AND all pods should be mark back to Ready when the node get back to Ready before pod eviction timeout 3m15s
- [k8s.io] Nodes [Disruptive] [k8s.io] Network when a node becomes unreachable [replication controller] recreates pods scheduled on the unreachable node AND allows scheduling of pods on a node after it rejoins the cluster 2m11s

And `resource usage tracking` test is failed again in the latest tests.

**Comment by yujuhong** [comment]
> The following tests are failed in all serial tests (including gce-serial and gci-gce-serial), @yujuhong is there any known problem for this?

It seemed like a recent regression #35293 I haven't checked the details. 

> And resource usage tracking test is failed again in the latest tests.

I don't think they had ever been consistently green. I'd say this is P2 for v1.5.


The good news is the most flakes seem to have been fixed by the network namespace PR.

**Comment by yujuhong** [comment]
Closing this since most tests are green. Will open new issues for flakes.

**Comment by Random-Liu** [comment]
I checked the failure https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-cri-serial/4

Many SchedulerPredicates test failed because they assume all kube-system pods should be ready. However, `kube-proxy` is not ready:
```
kube-proxy-bootstrap-e2e-minion-group-e72n bootstrap-e2e-minion-group-e72n Running       [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-11-16 00:51:41 -0800 PST  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2016-11-16 00:51:42 -0800 PST ContainersNotReady containers with unready status: [kube-proxy]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-11-16 01:51:51 -0800 PST  }]
```
Because of known `device or resource busy` error:
```
E1116 09:51:52.064835    1320 remote_runtime.go:78] RunPodSandbox from runtime service failed: rpc error: code = 2 desc = failed to create a sandbox for pod "kube-proxy-bootstrap-e2e-minion-group-e72n": Error response from daemon: device or resource busy
```

The failure happened before https://github.com/kubernetes/kubernetes/pull/36768 was merged. We can take an eye on to see whether this will happen again even with #36768.

@yujuhong

**Comment by yujuhong** [comment]
Thanks for checking the failures!

**Comment by yujuhong** [comment]
Let's hold on to this issue for a few more days to see if the workaround actually works.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-cri-serial/5

The network partition test ran before the restart test, and left some pods in the terminating state (deletion timestamp marked) due to pod eviction from the node controller. However, the network partition didn't wait for the pods to be deleted before ending, and the restart test also didn't check the deletion timestamp at the beginning of the test. The restart test recorded that these pods were "running and ready" before it started, and later on found the pods disappeared. Looks like both tests need to be fixed.

**Comment by yujuhong** [comment]
I believe this is fixed.
