### ISSUE TITLE
azure: Gracefully support multiple availability sets

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#34293]
We have need to support multiple Availability Sets in an Azure cluster, but a load balancer can only target nodes that are in the same Availability Set.

I suggest that we add another field to the configuration used by the Azure CloudProvider to indicate what Availability Set we want to include in the loadbalancer. Then, when we loop over the nodes in the cluster, we only add nodes in that Availability Set to the load balancer backend.

CC: @anhowe @brendandburns

**Comment by djsly** [comment]
Quick question, with the new PrimaryAvailabilitySet. Should we set a different value in the azure.conf on each of the different node ?

I might be missing something here. 

If we set the same PrimaryAvailabilitySet everywhere, will the LoadBalancer be able to attach to its endpoint pods that reside on nodes not in the PrimaryAvailabilitySet ?
