### ISSUE TITLE
Federated Ingress always routes to a single cluster with intermittent downtime. 

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#34291]
Observing the corresponding load balancer in the Google Cloud Console shows that the load balancer keeps flapping between the backends in different clusters. Downtime also occurs at the same time (or at least the windows overlap) at which the load balancer switches from one backend to the other.

I have two GKE clusters. Their Ingress UID ConfigMap data sections match.

```shell
$ kubectl --namespace=kube-system logs l7-default-backend-v1.0-<suffix>
```

on either clusters return nothing.

cc @kubernetes/sig-cluster-federation @bprashanth @allannaim

**Comment by bprashanth** [comment]
Can you try: https://gist.github.com/bprashanth/52648b2a0b6a5b637f843e7efb2abc97 ?
basically poke around in gcloud and see if we're recreating/reordering backends or something

**Comment by bprashanth** [comment]
Meaing if the ingress and cloud resources are not changing, the health checks are flapping, if a cloud resource is changing, we should get the controller to stop doing that. 

The ingress controller logs are on the master at /var/log/glbc.log, l7-default-backend-v1.0-<suffix> is just the default backend, not the controller itself.

**Comment by quinton-hoole** [comment]
@bprashanth We've confirmed that the K8s Ingress object and the associated
configmap are not being updated, but the GCE LB backends are being
reconfigured (presumably by the GCLB controller). We've not looked at its
logs in any detail yet. Will do in the AM.

**Comment by madhusudancs** [comment]
@bprashanth 
> Can you try: https://gist.github.com/bprashanth/52648b2a0b6a5b637f843e7efb2abc97 ? 

Federated Ingress controller essentially does this. Do you want me to manually try this?

Also, @quinton-hoole and I verified this. The ConfigMaps match. And they don't get updated. We watched (manually by starting at the screen) the resource version on the ConfigMaps in the two clusters for quite a long time and none of these values changed.

> basically poke around in gcloud and see if we're recreating/reordering backends or something

Backends are being deleted and created all the time. Here are the results of a last few `$ gcloud compute backend-services list` runs:

```
NAME                            BACKENDS                                              PROTOCOL
k8s-be-30437--<suffix>  asia-east1-b/instanceGroups/k8s-ig--<suffix>  HTTP
```

```
NAME                            BACKENDS                                                PROTOCOL
k8s-be-30437--<suffix>  asia-east1-b/instanceGroups/k8s-ig--<suffix>    HTTP
k8s-be-31746--<suffix>  asia-east1-b/instanceGroups/k8s-ig--<suffix>    HTTP
k8s-be-31953--<suffix>  europe-west1-b/instanceGroups/k8s-ig--<suffix>  HTTP
```

```
NAME                            BACKENDS                                              PROTOCOL
k8s-be-30437--<suffix>  asia-east1-b/instanceGroups/k8s-ig--<suffix>  HTTP
k8s-be-31746--<suffix>  asia-east1-b/instanceGroups/k8s-ig--<suffix>  HTTP
```

All the suffixes match. Also, I can get the timestamps if you want. They are all pretty recent. In the last few minutes or so.

>Meaing if the ingress and cloud resources are not changing, the health checks are flapping, if a cloud resource is changing, we should get the controller to stop doing that.

I think it is the latter. Resources are changing, but their names are stable across generations.

> The ingress controller logs are on the master at /var/log/glbc.log, l7-default-backend-v1.0- is just the default backend, not the controller itself.

Ok. I am on GKE, so ...

**Comment by bprashanth** [comment]
Hmm, what services match those node ports? all the clusters should essentially see the same services/nodeports, and hence apply the same backend updates. 

Ping me or someone else on GKE team if you need to know how to get GKE master logs.

**Comment by madhusudancs** [comment]
> Hmm, what services match those node ports? all the clusters should essentially see the same services/nodeports, and hence apply the same backend updates.

They don't.

```
$ kubectl --context=$c1 describe svc nginx
Name:			nginx
Namespace:		default
Labels:			app=nginx
Selector:		app=nginx
Type:			LoadBalancer
IP:			<o1.o2.o3.o4>
LoadBalancer Ingress:	<o1.o2.o3.o4>
Port:			http	80/TCP
NodePort:		http	30437/TCP
Endpoints:		<o1.o2.o3.o4>:80
Session Affinity


$ kubectl --context=$c2 describe svc nginx
Name:			nginx
Namespace:		default
Labels:			app=nginx
Selector:		app=nginx
Type:			LoadBalancer
IP:			<o1.o2.o3.o4>
LoadBalancer Ingress:	<o1.o2.o3.o4>
Port:			http	80/TCP
NodePort:		http	31953/TCP
Endpoints:		<o1.o2.o3.o4>:80
Session Affinity:	None
No events.
```

**Comment by quinton-hoole** [comment]
@madhusudancs Can you confirm what version of the GLBC pod you're running in the clusters where you're seeing this behavior?  In particular does it include bug fixes like https://github.com/kubernetes/contrib/pull/1363.

**Comment by bprashanth** [comment]
I'm not sure how this is supposed to work if they're using different node ports, that's why I suggested walking through the example

**Comment by madhusudancs** [comment]
@quinton-hoole 

> Can you confirm what version of the GLBC pod you're running in the clusters where you're seeing this behavior? 

How do I get that?

> In particular does it include bug fixes like kubernetes/contrib#1363.

How do I verify that?

**Comment by quinton-hoole** [comment]
@madhusudancs Never mind, it seems that the problem is that you have created services with different node ports in the two different clusters (see @bprashanth comment above).

As for checking the controller version, have you tried 'describe pod'?

**Comment by madhusudancs** [comment]
@quinton-hoole I described and get -o yaml'ed `l7-default-backend-v1.0-0abcd`. But @bprashanth mentioned above that, that's only the backend pod, not the controller itself.

I could go look into the controller version if that's important at this point. Also FWIW, this is a GKE 1.4.0 cluster.

**Comment by madhusudancs** [comment]
> @madhusudancs Never mind, it seems that the problem is that you have created services with different node ports in the two different clusters (see @bprashanth comment above).

Also, clarification. I did not create services with different node ports. I just created a federated service.

**Comment by quinton-hoole** [comment]
@madhusudancs If you just update the federated service to include a nodeport, that should be propagated to all clusters, and everything should just work.

In your current config, you omitted the NodePort in the federated service, so each cluster chose it's own nodeport independently.  We could arguably change the implementation of Federated Services to make this easier.

**Comment by madhusudancs** [comment]
@quinton-hoole 

> In your current config, you omitted the NodePort in the federated service, so each cluster chose it's own nodeport independently. 

Yeah, how would I know to do that? No federation documentation I read indicated that I (or any user for that matter) was responsible for selecting the NodePort.

**Comment by quinton-hoole** [comment]
@madhusudancs Yes, as previously mentioned, the documentation was definitely inadequate.  I've tried to fill that gap with https://github.com/kubernetes/kubernetes.github.io/pull/1424 .  Please review at your earliest convenience.
