### ISSUE TITLE
In my kubernetes master nodes ,I implement command: kubectl version ,then emerge the error"The connection to the server localhost:8080 was refused - did you specify the right host or port?"  Can anyone help me? ?

### ISSUE THREAD

**Issue by bixiaohong2015** [kubernetes/kubernetes#34294]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by pwittrock** [comment]
Sounds like you kubectl config isn't setup correctly to talk to a cluster.
