### ISSUE TITLE
Updating kubeadm manifests

### ISSUE THREAD

**Issue by axsuul** [kubernetes/kubernetes#34307]
I provisioned my kubernetes cluster using `kubeadm` but I would like to change the option to `--secure-port=8081` for the API server. It seems like changing this manifest file

```
/etc/kubernetes/manifests/kube-apiserver.json
```

would give me what I want but how would I apply the changes? Running

```
# kubectl apply -f /etc/kubernetes/manifests/kube-apiserver.json
```

doesn't appear to update it properly.

**Comment by colemickens** [comment]
@axsuul The `kube-apiserver` is a static pod manifest, so you will need to actually manually edit the `/etc/kubernetes/manifests/kube-apiserver.json` file on your master.

**Comment by axsuul** [comment]
@colemickens I have edited it but what do I do editing it?

**Comment by colemickens** [comment]
I would've expected the `kubelet` sync loop to notice the difference and update/replace the Pod.

If it didn't, you could try deleting the `kube-apiserver` pod and letting it respawn from the manifest whenever `kubelet` notices it's missing (note, this obviously could lead to apiserver being unavailable for a period of time, presumably rather short period of time).

**Comment by axsuul** [comment]
When changing the `--secure-port` option in the manifest, it immediately places the `kube-apiserver` pod into a **pending** state. I've tried different ports and changing it back to `443` makes it **active** again. 

Am I missing something here?

**Comment by colemickens** [comment]
cc: @luxas @errordeveloper

**Comment by axsuul** [comment]
Also want to point out that there's no events for `kubectl describe pod kube-apiserver` as well as nothing informative in `kubectl get events`

**Comment by colemickens** [comment]
I wouldn't expect this (`kubectl describe pod kube-apiserver`) to return anything anyway, you need to be looking at the `kube-system` namespace for the apiserver pod.

**Comment by axsuul** [comment]
Sorry, what I meant was `kubectl describe pod kube-apiserver -n kube-system`

**Comment by errordeveloper** [comment]
I'd like to fix https://github.com/kubernetes/kubernetes/issues/33638 ASAP, also after https://github.com/kubernetes/kubernetes/pull/34501 lands, we can allow users to pass any custom flags to any of the control plane components.

**Comment by sandys** [comment]
@errordeveloper does that mean that your official recommendation right now is to not touch kube-apiserver.json and instead use the flags from #33638 ?

**Comment by errordeveloper** [comment]
@sandys unless you really have to, it seems like patching the static pod manifest results in this weird pending situation, and it's probably a separate bug, but I'm not entierely sure we need to look into it, given we are looking to get rid of static pods all together soon with proper kubelet API.

**Comment by sandys** [comment]
@errordeveloper im not advocating for the manifest fix - im just asking what should we wait for ? Will  this bug become WONTFIX and #33638 be the right way to do it ?

**Comment by errordeveloper** [comment]
@sandys I've just opened #34719, hope we might be able to merge it and cut a snapshot release later today ;)

**Comment by errordeveloper** [comment]
@sandys yes, this issues as it stands won't be fixed, as user's problem is only about setting the port.

**Comment by axsuul** [comment]
@errordeveloper how would we change an existing kubeadm cluster's API ports with the flags?

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#25
