### ISSUE TITLE
Could not connect to rsync container. See build/README.md for setting up remote Docker engine.

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#34300]
I have symptoms that look like those being fixed by this: https://github.com/kubernetes/kubernetes/pull/34288 but I still get the error after cherry-picking that fix.

The last two commits in my tree are:

* 15b9583a713d4fd81aa446cceb224b94cfc62d3a (aka https://github.com/kubernetes/kubernetes/pull/34257)
* a cherry pick of https://github.com/kubernetes/kubernetes/pull/34288

I have removed **all** containers and images from my system. I'm in a clean git tree.

I run `make clean; make release` and get the following out:

```shell
+++ [1006 20:34:06] Verifying Prerequisites....
+++ [1006 20:34:06] Building Docker image kube-build:build-be4685d15b-4-v1.6.3-9
+++ [1006 20:35:42] Creating data container kube-build-data-be4685d15b-4-v1.6.3-9                                                                                                                               +++ [1006 20:35:44] Syncing sources to container
!!! [1006 20:35:49] Could not connect to rsync container. See build/README.md for setting up remote Docker engine.
make: *** [Makefile:239: release] Error 1
```

When I try to investigate...

```shell
$ docker ps -a

CONTAINER ID        IMAGE                                    COMMAND                  CREATED              STATUS                      PORTS                       NAMES
43529d54bfce        kube-build:build-be4685d15b-4-v1.6.3-9   "/rsyncd.sh"             58 seconds ago       Up 57 seconds               127.0.0.1:32776->8730/tcp   kube-rsync-be4685d15b-4-v1.6.3-9
e18d40dbcba6        kube-build:build-be4685d15b-4-v1.6.3-9   "chown -R 1000.1000 /"   About a minute ago   Exited (0) 58 seconds ago                               kube-build-data-be4685d15b-4-v1.6.3-9

$ docker logs 435
2016/10/06 20:35:45 [1] rsyncd version 3.1.1 starting, listening on port 8730
```

I'm happy to try anything for the sake of troubleshooting/debugging. Thanks.

**Comment by colemickens** [comment]
CC: @jbeda

**Comment by gnufied** [comment]
I would try if you can locally reach port `32776` using telnet may be. Also you can probably run this function https://github.com/kubernetes/kubernetes/blob/master/build/common.sh#L585 in isolation and see if that works. 

I was running into similar problem and just running the function via a standalone shell script helped narrow down the problem.

**Comment by colemickens** [comment]
It seems like I was able to connect... though my container was listening on 32777 instead.

```shell
$ make release
+++ [1006 23:10:42] Verifying Prerequisites....
+++ [1006 23:10:42] Syncing sources to container
!!! [1006 23:10:47] Could not connect to rsync container. See build/README.md for setting up remote Docker engine.
make: *** [Makefile:239: release] Error 1                                                                                                                                                                        

$ docker ps
CONTAINER ID        IMAGE                                    COMMAND             CREATED             STATUS              PORTS                       NAMES
0feebecbdd03        kube-build:build-be4685d15b-4-v1.6.3-9   "/rsyncd.sh"        3 minutes ago       Up 3 minutes        127.0.0.1:32777->8730/tcp   kube-rsync-be4685d15b-4-v1.6.3-9

$ telnet localhost 32777
Connection failed: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
@RSYNCD: 31.0
```

How did you run that function "in isolation"? I wrote out a file, and tried to execute it:

```shell
$ cd build

$ cat ./please-work.sh
#!/bin/bash
source common.sh
kube::build::rsync_probe 127.0.0.1 32777

$ ./please-work.sh
common.sh: line 589: LOCAL_OUTPUT_BUILD_CONTEXT: unbound variable
```

**Comment by colemickens** [comment]
Sorry, I should have clarified some detail from my ML email... I'm definitely not running "remote Docker". The machine where I'm doing the build is the machine where Docker is installed and `DOCKER_HOST` is certainly not set, let alone pointing at a remote host.

**Comment by gnufied** [comment]
@colemickens I meant something like https://gist.github.com/gnufied/e3b85ef5db3668ae7850c266d8c57bfd 

Where you can replace location of `rsyncd.passwd` with your actual location and port with your actual port (like  32777)

**Comment by gnufied** [comment]
ALso, each time you run `make release` the container gets deleted and recreated and hence port number will change.

**Comment by colemickens** [comment]
Thanks @gnufied. I matched the port in that script to the port in my `docker ps` output. I also fixed the `kube-build` path to point at the correct dir in my tree.

This does indeed help narrow things down. It  falls out without ever printing the "hooray" message. I'm not really sure why though.

**Comment by jbeda** [comment]
Sorry that you are having problems!

Can you try a couple of things to help narrow this down?

First, run `bash -x KUBE_VERBOSE=6 build/run.sh echo hello`.  This will create a *lot* of spew, probably.  You can put that in a gist and link from here.

Second, you can comment out `kube::build::stop_rsyncd_container` at the end of `build/common.sh` and then run `build/copy-output.sh`.  This will leave the rsync container running.  We can then figure out if that one failed to launch or if can't communicate it.

Thanks!

**Comment by colemickens** [comment]
Well this is deeply, deeply embarrassing. I didn't have `rsync` installed. Maybe we could add an explicit check for it?

**Comment by colemickens** [comment]
(I didn't see any errors during troubleshooting that would've pointed it out sooner. Wasn't until I started running the steps from @gnufied's script that I noticed `rsync` clearly being missing.)

**Comment by jbeda** [comment]
Not embarrassing at all!  It is a prereq that we should verify and ask folks to install.  

The good thing is that once we get this solid all other build steps will run in a container with a much more deterministic environment.

**Comment by jianzhangbjz** [comment]
@colemickens I encounter the same problems as you said above on release-1.5 branch, but I have installed the `rsync`, how to fix it? or something else I missed?
```
root@heatonli-test1:/home/zhangjian/src/k8s.io/kubernetes#docker ps -a
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS                    PORTS                       NAMES
ef046989690c        kube-build:build-da00aed54b-4-v1.7.4-0   "/rsyncd.sh"             15 hours ago        Up 15 hours               127.0.0.1:32771->8730/tcp   kube-rsync-da00aed54b-4-v1.7.4-0
d950352b60ee        kube-build:build-da00aed54b-4-v1.7.4-0   "chown -R 0.0 /go/src"   15 hours ago        Exited (0) 15 hours ago                               kube-build-data-da00aed54b-4-v1.7.4-0

root@heatonli-test1:/home/zhangjian/src/k8s.io/kubernetes#which rsync
/usr/bin/rsync
root@heatonli-test1:/home/zhangjian/src/k8s.io/kubernetes# go version
go version go1.7.4 linux/amd64
```

**Comment by levimm** [comment]
I also encounter this issue and it's because docker for mac reverses 64G disk size for all images and containers. And mine is already using 60G so rsync container cannot get started. Run this command to free up space. 
"docker system prune -a --volumes"

**Comment by tongchao199** [comment]
I also encounter this issue and it's because of multiple docker container has 172.17.0.3 ip address, so that iptables forward request to another container.

You can manually test whether rsync container is normal by the following command.
```
[gooner@k8s-test-ser00]$ sudo docker ps | grep build
60a423fef333        kube-build:build-6fd1e262ca-5-v1.12.1-2              "/rsyncd.sh"             Less than a second ago   Up Less than a second   127.0.0.1:10057->8730/tcp           kube-rsync-6fd1e262ca-5-v1.12.1-2

rsync rsync://k8s@127.0.0.1:10057/ --password-file=_output/images/kube-build\:build-6fd1e262ca-5-v1.12.1-2/rsyncd.password
```
