### ISSUE TITLE
Docker Engine API is deprecated.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#34308]
Docker Engine API was deprecated https://github.com/docker/engine-api 20 days ago.
The client library is moved into docker repo https://github.com/docker/docker/tree/master/client.

We should consider switch to using it.

/cc @kubernetes/sig-node

**Comment by dims** [comment]
@Random-Liu we'll need to switch cadvisor over as well. right? (https://github.com/google/cadvisor/tree/master/vendor/github.com/docker/engine-api)

**Comment by resouer** [comment]
This is so wired, why it is moved back (again) :///

**Comment by yujuhong** [comment]
The original issue: https://github.com/docker/engine-api/issues/379

**Comment by resouer** [comment]
Have we begin this work, or we still discussing?

**Comment by yujuhong** [comment]
AFAIK, no one is working on this.

**Comment by caarlos0** [comment]
I think this would also require to update other docker packages... 

This will probably break a lot of things :(

**Comment by Random-Liu** [comment]
Just point out that, current implementation of [image list filter](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/docker_image.go#L33) will not work with docker 1.13 if we don't update docker client. Their previous api is [`filter`](https://github.com/docker/engine-api/blob/master/client/image_list.go#L26), but now it's [`reference`](https://github.com/moby/moby/blob/v1.13.1/client/image_list.go#L20-L25).

This is fine for now because we don't use this feature.
