### ISSUE TITLE
The testing framework doesn't respect additional AfterEach calls

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#34318]
I am trying to set up a failure trap in an AfterEach related only to the deployment e2e suite in https://github.com/kubernetes/kubernetes/pull/34316 but it seems that the testing framework will execute its own AfterEach first that deletes the namespace where the test runs thus preempting my failure trap.

I would like to have my special-cased AfterEach run before the framework's AfterEach. Does it sound reasonable? @jayunit100 @ixdy

**Comment by jayunit100** [comment]
hmmm.. 

- Can  your individual tests handle this logic with something like a `defer` ? 

- You are right I beleive use of ginkgo AfterEach is non deterministic because we already have setup the testing framework to use it on its own.

- Maybe some specifics on why you need you're own custom AfterEach would help: Its possible that we should consider your specific cleanup needs as a feature which e2e should support ?

**Comment by kargakis** [comment]
> Can your individual tests handle this logic with something like a defer ? 

I cannot use defer because I need to know if the test passed or failed. Passing `CurrentGinkgoTestDescription().Failed` in defer doesn't work.

> Maybe some specifics on why you need you're own custom AfterEach would help: Its possible that we should consider your specific cleanup needs as a feature which e2e should support ?

I want to log the deployment and replica set objects in case the test fails. This is specific to the deployment tests so I would expect to use `AfterEach` instead of adding the logic in the framework.

> Come to think of it, maybe the framework's call to AfterEach could be augmented with an option to call a user defined "pre-cleanup" step ?

This sounds like what I am after.

**Comment by jayunit100** [comment]
OK.  I guess if there is a way for the framework to know what test its running, it could specifically trigger AfterEach's for that test?  seems tricky at first glance but only looking superficially

**Comment by ixdy** [comment]
Ginkgo has a [`JustBeforeEach`](https://onsi.github.io/ginkgo/#separating-creation-and-configuration-justbeforeeach); it sounds like you want a `JustAfterEach` (which unfortunately doesn't exist yet).

In lieu of adding this functionality to Ginkgo, adding an additional field to `Framework` with a cleanup function to run seems reasonable.

That said, the `Framework` `AfterEach` [already has logic to dump a bunch of logs on test failures](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/framework.go#L375-L392) - maybe you should just update that to dump logs relating to deployments?

**Comment by kargakis** [comment]
> Ginkgo has a JustBeforeEach; it sounds like you want a JustAfterEach (which unfortunately doesn't exist yet).

Exactly what I want. Opened https://github.com/onsi/ginkgo/issues/303 upstream.

> That said, the Framework AfterEach already has logic to dump a bunch of logs on test failures - maybe you should just update that to dump logs relating to deployments?

I prefer to avoid a solution that will affect all tests. For now I can live without those trap failures. If we really need them in the future and https://github.com/onsi/ginkgo/issues/303 is not fixed then I will update the existing log dump.

**Comment by kargakis** [comment]
It seems that there is no need for JustAfterEach and JustAfter should work: https://github.com/onsi/ginkgo/issues/303#issuecomment-258900469

**Comment by kargakis** [comment]
It seems that there is no need for JustAfterEach and AfterEach should work: https://github.com/onsi/ginkgo/issues/303#issuecomment-258900469

**Comment by kargakis** [comment]
@ixdy any reason why you closed this? AfterEach calls are still not working as they should: https://github.com/kubernetes/kubernetes/pull/36376, the failure trap I set in that PR is getting called after the namespace deletion happens.

**Comment by ixdy** [comment]
oh, I thought your last comment meant that `AfterEach` would work.

**Comment by kargakis** [comment]
> oh, I thought your last comment meant that AfterEach would work.

It works on plain ginkgo tests, not sure why it doesn't work with the Kube framework.

**Comment by kargakis** [comment]
@kubernetes/test-infra-maintainers it would be really nice if the test framework by default (or individual tests could opt in) would dump all the objects in the namespace in case of a failure before purging the namespace. I have shoehorned some failure traps in the Deployment tests but they are never enough and I die a little more on the inside every time I need to do this manually for a test.

**Comment by ixdy** [comment]
cc @kubernetes/sig-testing-feature-requests 

The test-infra maintainers group is mostly focused on things like CI infrastructure, rather than the ginkgo test framework.

**Comment by kargakis** [comment]
Sorry about that, now I know :)
