### ISSUE TITLE
Container Stats/Metrics support for Windows Containers

### ISSUE THREAD

**Issue by jbhurat** [kubernetes/kubernetes#34327]
cAdvisor does not work on Windows. This issue is to track the work involved in getting container stats/metrics from Windows Containers to kubelet. 
[Support cAdvisor on Windows](https://github.com/google/cadvisor/issues/1394) was created sometimes ago and the advise from the community was to for the [Container Runtime Interface](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/container-runtime-interface-v1.md) to define the stats interface and implement that interface using a different model. 
Possible implementations include using Windows perf monitors to retrieve container metrics.

**Comment by yujuhong** [comment]
@jbhurat, @sig-node has decided that the monitoring related issues won't be handled in CRI in k8s 1.5 release.  https://github.com/kubernetes/kubernetes/issues/27097#issuecomment-252336387
We will resume the discussion after the release, when we have a more clear picture of the monitoring pipelines.

**Comment by jbhurat** [comment]
Thanks for the heads up @yujuhong

**Comment by michmike** [comment]
@jbhurat one of the first things we should itemize is what perf and other metrics cAdvisor exposes to k8s that are needed on windows. We can put them on a table and try to map them to APIs (WMI, perfmon, powershell) on Windows Server.
thanks!

**Comment by sjpotter** [comment]
@michmike  https://github.com/google/cadvisor/blob/master/info/v2/container.go#L131

**Comment by sjpotter** [comment]
The process how this all works today is a bit convoluted.

a bit of background: kubelet adds labels to the the docker containers, cadvisor reads those labels in an opaque manner and just attaches them to the data it returns.

so the process is 

kubelet creates containers, cadvisor provides stats on containers (with the opaque data), kubelet reingests the data and uses the labels that are not opaque to it (it created them) to be able to associate the cadvisor "containers" to the appropriate pod/container structures.  It then accumulates the data in a pod oriented way

this data is then provided by kubelet via its stats api and is ingested by heapster.

other k8s services (say horizontal pod autoscaling) then ingest the data from heapster to make scheduling decisions for pods which will then be communicated to the individual kubelets.

**Comment by michmike** [comment]
this is very helpful. thanks @sjpotter

**Comment by jbhurat** [comment]
@yujuhong: just checking if any progress has been made to defining the stats/metrics api

**Comment by yujuhong** [comment]
@jbhurat in the past weeks, the community had been focusing on defining the "core metrics", which is a set of metrics kubelet need to provide. The definition of core metrics will affect CRI's stats/metrics API because kubelet have to on the container runtime to supply some of the metrics. The [proposal for core metrics API](https://github.com/kubernetes/community/pull/252) has just been merged. One conclusion drawn from the proposal is that runtime will have to offer container usage stats (e.g., cpu, memory, filesystem). I think we can start working the CRI API once the core metrics API is properly defined and written down.

**Comment by jbhurat** [comment]
Thanks @yujuhong, does the working group meet alongside sig-node weekly meetings.

**Comment by yujuhong** [comment]
> Thanks @yujuhong, does the working group meet alongside sig-node weekly meetings.

There is currently no separate work group for CRI stats. We discuss issues as they come up in the the weekly sig-node meeting.

**Comment by mfaizanse** [comment]
Just to confirm, Does it mean that currently container Stats/Metrics are not supported by windows container, thus horizontal pod auto-scaling will not work with windows containers? 

Also, is there any work-around to get horizontal pod auto-scaling to work with windows containers? Like If I can manually run some metrics service inside my win container? or any similar approach?

**Comment by michmike** [comment]
@mfaizanse  yes that is correct. the current container stats are not supported or exposed by windows containers yet. we are looking into this for beta or GA release.

there is no workaround offered by k8s, unless you run a process inside your container and get statistics from windows perf counters and use that data to control scaling your replica set

**Comment by travispalmer** [comment]
@michmike, I assume that this implies that auto-scaling for windows containers is currently not supported as well?

**Comment by mfaizanse** [comment]
Any progress on this? Is there any solution for windows containers auto-scaling with prometeus?

**Comment by michmike** [comment]
we are testing this functionality, but two PRs that went in for the 1.9 tree fix this.
https://github.com/kubernetes/kubernetes/pull/51152
https://github.com/kubernetes/kubernetes/pull/50396

**Comment by rjmorse** [comment]
Is this issue still outstanding? Are there metrics that are currently missing for this to be considered complete?
These PRs look to have addressed Windows metrics between August and November for the 1.9 release:
https://github.com/kubernetes/kubernetes/pull/51152 Implement CRI stats in Docker Shim
https://github.com/kubernetes/kubernetes/pull/50396 Add Windows Server Containers Stats and Metrics to Kubelet
https://github.com/kubernetes/kubernetes/pull/55496 Fix issue #55031 to remove dependence on package lxn/win

**Comment by michmike** [comment]
I think this is complete. cc: @JiangtianLi  do you agree?

**Comment by JiangtianLi** [comment]
@michmike I agree, with David's work this issue can be closed.
