### ISSUE TITLE
Regarding required changes for s390x architecture 

### ISSUE THREAD

**Issue by gajju26** [kubernetes/kubernetes#34328]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): Yes

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):s390x

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

  I am working on Kubernetes for s390x architecture to enable docker images for s390x should be pushed to gcr.io repository. For this
1. I was trying to build the master branch but it failed for s390x due to there was an issue in the file "server_statvfs_linux.go". The thing is this issue is resolved in the sftp package but the package is not updated in the Kubernetes repository.  Can you give me an idea when this package will be updated in the Kubernetes code(vendor/github.com/pkg/sftp) ?
2. Also for the same task when I ran build/release.sh command, I came across docker image gcr.io/google_containers/kube-cross which is using golang:1.6.3(https://github.com/kubernetes/kubernetes/blob/master/build/build-image/cross/Dockerfile) as base image and it does not support 
   s390x architecture. Go 1.7.1 is released and it has support for s390x architecture. Is there any plan to update the mentioned docker file for golang 1.7.1 so it will support multiple architectures supported by Go?? And if there is no plan can I add my Docker file specific to s390x so that gcr.io/google_containers/kube-cross docker image will have support for s390x.

@cwsolee  @aborkar-ibm

**Comment by luxas** [comment]
I've been working with multiarch a lot, please read though https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/multi-platform.md

This should be pretty straightforward now

As soon as we have upgraded to go1.7.1, we should try to enable it for sure, and I can help as I stated in the proposal

**Comment by gajju26** [comment]
Hi luxas,

Thanks for inputs. I have identified the changes required for s390x that need to be pushed. The changes are pretty straight forward and compatible with GO 1.7.1.  You want me to push the required changes for s390x or will be enabled at your end,once you upgrade it to go1.7.1. Can you give me an idea, how soon Kubernetes will be upgraded to go1.7.1??

@cwsolee @aborkar-ibm

**Comment by luxas** [comment]
I think go1.7.1 is going to be in this week

**Comment by gajju26** [comment]
Hi luxas,

I see that the Kubernetes has been upgraded to Go1.7.1 and I am also ready with my changes.  I see one problem in the Docker file (https://github.com/kubernetes/kubernetes/blob/master/build/build-image/cross/Dockerfile). This Docker file is adding "deb http://emdebian.org/tools/debian/ jessie main" repository for cross compiling tool chains for architectures armel/arm64/ppc64el but this repository does not support s390x. I have been looking for repositories which will support all the required architectures but no luck yet.  There is one repository "deb http://ftp.osuosl.org/pub/ubuntu xenial main universe"  which has s390x support but unfortunately it does not have support for armel.
