### ISSUE TITLE
Hardcoded values in fluentd-elasticsearch addon

### ISSUE THREAD

**Issue by sachincab** [kubernetes/kubernetes#34337]
Hi Team,

Noticed couple hardcoded values in fluentd-elasticsearch addon as mentioned below:

**fluentd-es-image**
td-agent.conf in fluentd-es-image has hardcoded host value (host elasticsearch-logging) which is not working for us in two scenarios, is it possible to fix this to pass this as environment available or 
{SVCNAME}_SERVICE_HOST?

1) we are using environment specific cluster domain (e.g. elasticsearch-logging.kube-system.svc.dev/stage/prod)  for kube-dns and not default one i.e cluster.local
2) Alpine based images does not resolve shortname and it require FQDN for resolution.

**kibana-image**
Is it possible to pass environment variable so we can appropriate environment variable. Currently it default to production.
`"message":"Listening on 0.0.0.0:5601","node_env":"production"}`

And also noticed that kube-addon-manager is not able to create DaemonSet pods, it should be supported.

**Comment by vasu1124** [comment]
fluentd-es-image: why don't you create a configMap with your conf and mount it at /etc/td-agent/td-agent.conf?

**Comment by sachincab** [comment]
@vasu1124 Yes, I created configMap to override values.
However it would be good to override some generic values using environment variables like node_env

**Comment by olalonde** [comment]
Would be nice if elasticsearch host could be configurable through an environment variable (e.g. `ELASTICSEARCH_HOST`) in https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image

I'd be ready to do a pull request.
