### ISSUE TITLE
Create a library for saturating the cluster that will be shared between density test and scheduler benchmark.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#34336]
This way we'll be able to easily compare accuracy of the benchmark and make reduce the code duplication.

cc @wojtek-t @hongchaodeng

**Comment by gmarek** [comment]
I've done parts of it that I needed, but it's still far from done.

**Comment by timothysc** [comment]
@sjug this is a good task that fits in the scope of the work you have been doing, but I can't assign you.  Could you please join the kubernetes org - https://github.com/orgs/kubernetes/people

**Comment by sjug** [comment]
Sounds good @timothysc, I don't see anywhere to join the org.
