### ISSUE TITLE
Routecontroller error message

### ISSUE THREAD

**Issue by jkemp101** [kubernetes/kubernetes#34356]
**Kubernetes version** (use `kubectl version`):

```
admin@ip-10-0-79-45:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Jessie
- **Kernel** (e.g. `uname -a`): `Linux ip-10-0-9-45 4.4.23-k8s #1 SMP Fri Sep 30 13:51:02 UTC 2016 x86_64 GNU/Linux`
- **Install tools**: kops
- **Others**:

**What happened**:
Built 3 master/3 node cluster in three AZs.  Received the following error message everywhere from 5 minutes apart to 30 minutes apart.
`E1007 19:56:01.582845      11 routecontroller.go:197] Error updating node ip-10-0-8-177.us-west-2.compute.internal, retrying: Operation cannot be fulfilled on nodes "ip-10-0-8-177.us-west-2.compute.internal": <nil>`.  

Everything seems to be working ok so I don't believe there is an impact to the cluster at this point.

**How to reproduce it** (as minimally and precisely as possible):
This occurred in a fresh cluster with just the Dashboard addon running.  But I have also seen it in most of my test clusters I have built also.

**Comment by spxtr** [comment]
Also seeing this on GKE.

**Comment by cmluciano** [comment]
/assign 

is this still happening?

**Comment by jkemp101** [comment]
This is still happening on my clusters but they are version `1.4.8`.  Haven't checked it on anything newer yet.  Feel free to close if you think its likely fixed in the latest versions.

**Comment by cmluciano** [comment]
/close

please reopen if you detect this in release 1.4-1.7
