### ISSUE TITLE
NetworkPolicy for GCE

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#34366]
NetworkPolicy is due to go GA any release now.  We don't yet have an answer for it on GCE or GKE.  We probably should find an answer.

Thoughts?

@roberthbailey @fabioy @alex-mohr 

@aronchick @bowei @freehan @MrHohn @bprashanth

**Comment by thockin** [comment]
@matchstick

**Comment by justinsb** [comment]
AFAICT https://github.com/weaveworks/weave-npc is written in golang, deploys as a daemonset of pods (only), has no dependencies on weave, and uses k8s libraries for things like API access & iptables.  No license listed, but looks like it could be a good candidate for incubation.

**Comment by rushtehrani** [comment]
Is there a solution to this on GKE yet? I tried Calico and it kind of worked on 1.4.x but doesn't on 1.5.3.

**Comment by thockin** [comment]
GKE doesn't really let you tweak nodes in the ways you need to install
Calico properly.  It's something we are looking at but don't have a
solution for just yet.

**Comment by rushtehrani** [comment]
Thanks for the reply.  Yes, it was a very manual process to get it running on 1.4.x.  I've been following #38169 and #sig-network on Slack, is there a anywhere else I should be looking to follow the discussion on GKE NetworkPolicy support?

**Comment by thockin** [comment]
This is the place.  Hopefully 1.7 will have a default-enabled option.  In the mean time, Calico on GCE should work, but not on GKE.

**Comment by thockin** [comment]
@dnardo - open bug, FYI

**Comment by yuvipanda** [comment]
Would this land for 1.7 on GKE?

**Comment by thockin** [comment]
Hang tight for GKE announcements :)

**Comment by mmikulicic** [comment]
Here's a relevent announcement:
https://cloudplatform.googleblog.com/2017/07/Container-Engine-now-runs-Kubernetes-1-7-to-drive-enterprise-ready-secure-hybrid-workloads.html

> Network isolation can be an important extra boundary for sensitive workloads. The Kubernetes NetworkPolicy API allows users to control which pods can communicate with each other, providing defense-in-depth and improving secure multi-tenancy. Policy enforcement can now be enabled in **alpha clusters**.

(emphasis mine)

**Comment by tmaier** [comment]
Google announced in September 2017 that it will support `NetworkPolicy`. See https://cloudplatform.googleblog.com/2017/09/network-policy-support-for-kubernetes-with-calico.html

There is also a guide on this feature at https://cloud.google.com/kubernetes-engine/docs/how-to/network-policy
