### ISSUE TITLE
VSphere: Kubelet fails when the vsphere provider fails to get node addresses 

### ISSUE THREAD

**Issue by kokhang** [kubernetes/kubernetes#34364]
**Environment**:
- VSphere
- Openstack (possibly, since the openstack provider also talks to the compute API for its addresses)

**What happened**: When kubelet tries to set the node addresses, it gets this error when the vsphere provider cannot talk to the vcenter server. 

`E1007 16:27:35.794667    3463 kubelet.go:2913] Error updating node status, will retry: failed to get node address from cloud provider: Post https://137.156.165.120:443/sdk: dial tcp 137.156.165.120:443: i/o timeout`

This will cause the kube-node to be not ready and kubernetes will start migrating pods/volumes from that node to a different node.

**What you expected to happen**:
Even if there is a small network outage, and the provider is not able to contact the compute API for ip addresses, kubelet or the cloud-provider should not error out and instead fall back to a get these IPs locally. 

There is already a TODO for this issue but i couldnt find an issue for this. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status.go#L363

**Comment by kiall** [comment]
Re OpenStack - yes, we've seen this when the Nova Metadata service is down, causing all nodes to become NotReady..

**Comment by imkin** [comment]
I do not think we should bypass cloud provider. The cloud provider "may not like it". For "small network outages" there could be resilience built that could say "I will retry a few more times "  or "I will retry in few seconds to see if "uncontrollable" events resolve themselves.

**Comment by kerneltime** [comment]
@kokhang This issue should be addressed more widely for fault handling model for cloud provider backends? The title for the issue though applicable to vSphere limits the scope of the issue..

**Comment by berchtos** [comment]
@kerneltime I agree with you this should be more widely discussed to handle a cloud provider backend failure. Even though you're running vCenter in HA, whenever you perform maintenance (ie. patching), it will force you to take your kubernetes cluster offline.

We're having the same issue in our environment. Whenever vCenter is unavailable it causes the kubernetes cluster to freak out (first the nodes will go into NotReady, then the Pods will get reshuffled).
