### ISSUE TITLE
Gubernator not highlight golint error

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#34362]
@rmmh 

Verify test from #34347 

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/34347/kubernetes-pull-verify-all/17359/?log

This need to be highlighted
```
Some packages passed golint but are not listed in hack/.linted_packages.
Please add them in alphabetical order:

  echo cmd/genyaml >> hack/.linted_packages
  echo pkg/util/metrics >> hack/.linted_packages
  echo plugin/pkg/auth/authenticator/request/x509 >> hack/.linted_packages
  LANG=C sort -o hack/.linted_packages hack/.linted_packages

You can test via this script and commit the result.

FAILED   hack/make-rules/../../hack/verify-golint.sh	20s
```

**Comment by rmmh** [comment]
This is gross. What's actually happening is:

    re.search(r'\bFAILED\b', '\x1b[0;31mFAILED\x1b[0m')

Let me think about how best to fix this.

**Comment by rmmh** [comment]
Tracking in kubernetes/test-infra#826
