### ISSUE TITLE
kube-up.sh  report make-ca-cert.sh  line 7 permission denied

### ISSUE THREAD

**Issue by jeffery9** [kubernetes/kubernetes#34374]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):
v1.4.0

**Environment**:
- **Cloud provider or hardware configuration**:  VM 
- **OS** (e.g. from /etc/os-release): Ubuntu 14.04.5 LTS
- **Kernel** (e.g. `uname -a`): Linux ubuntu 3.13.0-96-generic #143-Ubuntu SMP Mon Aug 29 20:15:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:  
- **Others**:

**What happened**:
when run `KUBERNETES_PROVIDER=ubuntu ./kube-up.sh` , it should report  missing  saltbase.  After corrected this, run kube-up.sh once again, it deploye kubernets to the Nodes, but report 

> /bin/bash: line 7: /root/kube/make-ca-cert.sh: Permission denied

**What you expect1ed to happen**:

**How to reproduce it** (as minimally and precisely as possible):
1. install a fresh ubuntu 14
2. download  kubernets v1.4.0
3. expande kuernets files into /opt/
4. modify  /opt/kubernetes/cluster/ubuntu/config-default.sh,  change nodes to only one, as  `export nodes=${nodes:-"root@127.0.0.1"}`    `roles=${roles:-"ai"}`    and  `export  NUM_NODES=${NUM_NODES:-1}`
5.  copy the missing saltbase into  /opt/kubernetes/cluster
6.  run   `KUBERNETES_PROVIDER=ubuntu ./kube-up.sh` , it should deploy files into nodes, but report make-ca-cert.sh error.

**Anything else do we need to know**:

**Comment by jeffery9** [comment]
found the root of cause.
 need  chmod + x for  make-ca-cert.sh

**Comment by roberthbailey** [comment]
Support for ubuntu was removed from kube-up in #44344 so I'm going to close this as obsolete.
