### ISSUE TITLE
Kubenetes gcloud container engine get-credential error

### ISSUE THREAD

**Issue by anchitanc1** [kubernetes/kubernetes#34395]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):Bug report

**Kubernetes version** (use `kubectl version`):
Google Cloud SDK 129.0.0
kubectl
kubectl-windows-x86_64 1.4.0
C:\Program Files (x86)\Google\Cloud SDK>kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0",

**Environment**:
- **gcloud sdk on windows 7**: 

**What happened**:

I am trying to connect Google Container Engine from my local machine using `gcloud` sdk but i am getting below error.

```
C:\Program Files (x86)\Google\Cloud SDK>gcloud container clusters get-credential
s cluster-2  --zone us-central1-a --project myapp-00000
Fetching cluster endpoint and auth data.
ERROR: (gcloud.container.clusters.get-credentials) environment variable HOME or
KUBECONFIG must be set to store credentials for kubectl
```

I have check at HOME location there is not .kube folder created and not environment variable set by default, so i have created  KUBECONFIG environment by myself after that i am getting below error :-

`ERROR: gcloud crashed (OSError): [Errno 13] Permission denied: 'C:\\Tool\\config'`
i have started gcloud sdk as admin and it have all the correct Permission.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
run  get-credential on window gcloud sdk
`gcloud container clusters get-credentials cluster-2  --zone us-central1-a --project myapp-00000`

**Anything else do we need to know**:

**Comment by joelharkes** [comment]
👍  I got the same issue

```
Fetching cluster endpoint and auth data.
ERROR: (gcloud.container.clusters.get-credentials) environment variable HOME or KUBECONFIG must be set to store credentials for kubectl
````

**Comment by joelharkes** [comment]
Got it working: 

Set environment variables: 
![image](https://cloud.githubusercontent.com/assets/2960938/19685263/f91f06d4-9abb-11e6-852c-98679eb956ce.png)

then execute the following in he command line:
```
mkdir .kube
cd .kube
echo "" > config
```

**Comment by jeffbarnes769** [comment]
Thanks!

**Comment by evgkarasev** [comment]
Thanks!

**Comment by bujardeari** [comment]
i dont have a folder .kube at my userprofile folder? You have an idea what to do?

**Comment by chiragnayyar** [comment]
superb

**Comment by hmol** [comment]
@bujardeari Just create it, but keep in mind you cant do: right click -> new folder -> ".kube". You must use cmd to do this, `mkdir .kube`

**Comment by CreepyGnome** [comment]
Should the installer set the environment variables it requires during the install process? I mean it knows where it installed itself.

**Comment by hmol** [comment]
Yes it should, but it did not do it on my machine.

**Comment by CreepyGnome** [comment]
@hmol Obviously it didn't do it for you or ANYONE it doesn't do it period.  I am saying that this BUG should be fixed by making the installer do this so that we stop having this problem. All required environment variables should be created and set by the installer.

**Comment by hmol** [comment]
Me and some of my colleagues installed this on our machines. It was only me that got this problem and for my colleagues this worked. This is why I don't think it happens to everyone.

**Comment by SurferJeffAtGoogle** [comment]
I saw this too.

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
/area platform/gke
since we lack a sig-gcp at the moment

/sig-windows
since this may be windows-specific

**Comment by mikesparr** [comment]
Any solution to this issue yet?  Attempting from Travis CI. Everything works fine from local CLI on Mac, but when trying from Travis CI, it errs on permissions. Tried deleting and recreating cluster, deleting and recreating service keys, various service key permissions (now just Project Editor, but before Container Developer + Storage Admin). Nothing seems to work

## deploy script ran after install and update gcloud and kubectl 
~~~
#!/bin/bash

set -e

docker build -t $DOCKER_IMAGE_NAME .
docker tag $DOCKER_IMAGE_NAME gcr.io/${PROJECT_NAME_STG}/${DOCKER_IMAGE_NAME}:$TRAVIS_COMMIT

echo $GCLOUD_SERVICE_KEY_STG | base64 --decode -i > ${HOME}/gcloud-service-key.json
gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json || die "unable to authenticate service account for gcloud"
export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-service-key.json
#gcloud beta auth application-default

gcloud --quiet config set project $PROJECT_NAME_STG
gcloud --quiet config set container/cluster $CLUSTER_NAME_STG
gcloud --quiet config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
gcloud container clusters get-credentials $CLUSTER_NAME_STG

#export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-service-key.json

gcloud docker -- push gcr.io/${PROJECT_NAME_STG}/${DOCKER_IMAGE_NAME}

yes | gcloud container images add-tag gcr.io/${PROJECT_NAME_STG}/${DOCKER_IMAGE_NAME}:$TRAVIS_COMMIT gcr.io/${PROJECT_NAME_STG}/${DOCKER_IMAGE_NAME}:latest

kubectl config view
kubectl config current-context

kubectl set image deployment/${KUBE_DEPLOYMENT_NAME} ${KUBE_DEPLOYMENT_CONTAINER_NAME}=gcr.io/${PROJECT_NAME_STG}/${DOCKER_IMAGE_NAME}:$TRAVIS_COMMIT
~~~

## Errors in build
~~~
Successfully built 94cdc940f293
Activated service account credentials for: [travis@PROJECT-NAME.iam.gserviceaccount.com]
Updated property [core/project].
Updated property [container/cluster].
WARNING: Property [zone] is overridden by environment setting [CLOUDSDK_COMPUTE_ZONE=us-central1-b]
Updated property [compute/zone].
Fetching cluster endpoint and auth data.
ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=403, message=Required "container.clusters.get" permission for "projects/PROJECT-NAME/zones/us-central1-b/clusters/staging-cluster-test".
Script failed with status 1
~~~

**Comment by stychu** [comment]
I have the same error as @mikesparr  with codeship and kubernetes cluster deploy. 
dont know how to solve this.

`ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=403, message=Required "container.clusters.get" permission for "projects/.......".`

**Comment by mikesparr** [comment]
I solved by creating new service account/key with different name. Names are cached. Roles needed were service account view, container dev, storage admin, container cluster admin

**Comment by Wanl23** [comment]
> Got it working:
> 
> Set environment variable:
> ![image](https://cloud.githubusercontent.com/assets/2960938/19685263/f91f06d4-9abb-11e6-852c-98679eb956ce.png)
> 
> then execute the following in the (under current user) command line:
> 
> ```shell
> mkdir .kube
> cd .kube
> echo "" > config
> ```
> 
> because you make the config file under current user gcloud should have the right permissions:
> 
> ![image](https://cloud.githubusercontent.com/assets/2960938/19685429/dc9443fc-9abc-11e6-8f6d-32143103e37f.png)

Thank you, man. It is solved my problem.
