### ISSUE TITLE
Can Use the Kubernetes Scheduler Single In the future?

### ISSUE THREAD

**Issue by xiaoshengaimm** [kubernetes/kubernetes#34397]
hi~

Scheduler resources compute algorithm is useful everywhere. 

make Scheduler to a single component and provide HTTP API to used.

is it well?

**Comment by timothysc** [comment]
@xiaoshengaimm I'm not certain what exactly you are asking for here.  My apologies for the confusion.

**Comment by timothysc** [comment]
I'm going to close, please feel free to reopen if needed.
