### ISSUE TITLE
Deploying with kubeadm, kube-dns is not starting on two tested OpenStack installations - but working on third

### ISSUE THREAD

**Issue by andersla** [kubernetes/kubernetes#34396]
*

**BUG REPORT**
Deploying with kubeadm, kube-dns is not starting on two tested OpenStack installations - but working on third

on master I execute
`kubeadm init --token c52ddf.f9324a7fa5058c6f`
on nodes I execute
`kubeadm join --token c52ddf.f9324a7fa5058c6f`

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
Openstack
`nova-manage version`
13.1.1
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
kubectl get pods --all-namespaces
![get_pods](https://cloud.githubusercontent.com/assets/17414346/19213063/efa44f68-8d61-11e6-81b1-f5e17b809978.png)

kubectl describe pod kube-dns-2247936740-rtdr8 --namespace=kube-system
error: message:
`FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason		Message
  7h		1s		27627	{kubelet anders-kubenow-master}			Warning		FailedSync	Error syncing pod, skipping: failed to "SetupNetwork" for "kube-dns-2247936740-rtdr8_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kube-dns-2247936740-rtdr8_kube-system(ad462280-8d4c-11e6-9017-fa163e62665e)\" using network plugins \"cni\": cni config unintialized; Skipping pod"`
Full output:
![desc_pod1](https://cloud.githubusercontent.com/assets/17414346/19213106/b0b53500-8d62-11e6-8850-d129fc42f96b.png)
![desc_pod2](https://cloud.githubusercontent.com/assets/17414346/19213108/b562e16a-8d62-11e6-9583-de4837070006.png)

sudo journalctl -r -u kubelet
Sample error message:
`1518 helpers.go:101] Unable to get network stats from pid 2138: couldn't read network stats: failure opening /proc/2138/net/dev: open /proc/2138/net/dev: no such file or directory
Oct 08 11:45:17 anders-kubenow-master kubelet[1518]: I1008 11:45:17.609346    1518 docker_manager.go:1492] Killing container "71236655c215ba1bdafc4caf976d614bf4febb404c745c5b77b70ae3eba1e025 kube-system/kube-dns-2247936740-rtdr8" with 30 second grace period
Oct 08 11:45:17 anders-kubenow-master kubelet[1518]: I1008 11:45:17.609153    1518 container.go:407] Start housekeeping for container "/docker/71236655c215ba1bdafc4caf976d614bf4febb404c745c5b77b70ae3eba1e025"
Oct 08 11:45:17 anders-kubenow-master kubelet[1518]: I1008 11:45:17.609118    1518 handler.go:325] Added event &{/docker/71236655c215ba1bdafc4caf976d614bf4febb404c745c5b77b70ae3eba1e025 2016-10-08 11:45:17.53993132 +0000 UTC containerCreation {<nil>}}
Oct 08 11:45:17 anders-kubenow-master kubelet[1518]: I1008 11:45:17.608974    1518 manager.go:874] Added container: "/docker/71236655c215ba1bdafc4caf976d614bf4febb404c745c5b77b70ae3eba1e025" (aliases: [k8s_POD.d8dbe16c_kube-dns-2247936740-rtdr8_kube-system_ad462280-8d4c-11e6-9017-fa163e62665e_8828e2ed 71236655c215ba1bdafc4caf976d614bf4febb404c745c5b77b70ae3eba1e025], namespace: "docker")
Oct 08 11:45:17 anders-kubenow-master kubelet[1518]: E1008 11:45:17.608486    1518 docker_manager.go:2127] Failed to setup network for pod "kube-dns-2247936740-rtdr8_kube-system(ad462280-8d4c-11e6-9017-fa163e62665e)" using network plugins "cni": cni config unintialized; Skipping pod
Oct 08 11:45:17 anders-kubenow-master kubelet[1518]: I1008 11:45:17.608473    15`
Full log:
[journalctl_kublet_1.txt](https://github.com/kubernetes/kubernetes/files/517680/journalctl_kublet_1.txt)

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:
Exactly same installation process works on another OpenStack installation, I have tried to do same virtual network configuration, I have used exactly the same Ubuntu 16.04 on both OpenStack installations

**Comment by andersla** [comment]
After installing Weave the kube-dns pod got up running all-right.

**Comment by fjammes** [comment]
Running `kubectl apply -f https://git.io/weave-kube` on k8s master solved this issue for me.

**Comment by rahul8590** [comment]
I actually have the same problem . I installed weave and problem still seems to persist.

```
root@kube:/etc/kubernetes# kubectl get pods --all-namespaces
NAMESPACE     NAME                                     READY     STATUS              RESTARTS   AGE
kube-system   dummy-2088944543-w5m63                   1/1       Running             0          7h
kube-system   etcd-kube1.usaas.io                      1/1       Running             0          7h
kube-system   kube-apiserver-kube1.usaas.io            1/1       Running             0          7h
kube-system   kube-controller-manager-kube1.usaas.io   1/1       Running             7          7h
kube-system   kube-discovery-1150918428-nvpad          1/1       Running             0          7h
kube-system   kube-dns-654381707-o5iy4                 0/3       ContainerCreating   0          7h
kube-system   kube-proxy-frvos                         1/1       Running             0          7h
kube-system   kube-proxy-fsgn8                         1/1       Running             0          7h
kube-system   kube-proxy-g8wlx                         1/1       Running             0          7h
kube-system   kube-scheduler-kube1.usaas.io            1/1       Running             7          7h
kube-system   weave-net-1yhsn                          2/2       Running             0          5h
kube-system   weave-net-r87x1                          2/2       Running             0          5h
kube-system   weave-net-utx6n                          2/2       Running             0          5h
```

I am not sure, how to resolve this.

**Comment by 2014qirong** [comment]
was this solved ?@rahul8590

**Comment by nuxman** [comment]
I would like to know .. same issue
