### ISSUE TITLE
kubelet: No such file or directory on ARM

### ISSUE THREAD

**Issue by IanLewis** [kubernetes/kubernetes#34390]
I'm trying to install Kubernetes master on a Raspberry Pi and it won't init. It hangs waiting for the control plane to come up.

    <master/tokens> generated token: "f0c861.753c505740ecde4c"
    <master/pki> created keys and certificates in "/etc/kubernetes/pki"
    <util/kubeconfig> created "/etc/kubernetes/kubelet.conf"
    <util/kubeconfig> created "/etc/kubernetes/admin.conf"
    <master/apiclient> created API client configuration
    <master/apiclient> created API client, waiting for the control plane to become ready

I assumed that the control plane components would get run by the kubelet and found that the kubelet wouldn't run.

    $ kubelet
    -bash: /usr/bin/kubelet: No such file or directory

I installed kubelet via apt using the [instructions in the docs](http://kubernetes.io/docs/getting-started-guides/kubeadm/).

I get the same error if I download the kubelet static binary myself:

    $ wget https://storage.googleapis.com/kubernetes-release/release/v1.4.0/bin/linux/arm/kubelet
    ...
    $ ./kubelet
    -bash: ./kubelet: No such file or directory

**Comment by IanLewis** [comment]
strace simply dies with "exec: No such file or directory". It looks like it's looking for an interpreter?

    # strace ./kubelet --help
    execve("./kubelet", ["./kubelet", "--help"], [/* 14 vars */]) = -1 ENOENT (No such file or directory)
    write(2, "strace: exec: No such file or di"..., 40strace: exec: No such file or directory
    ) = 40
    exit_group(1)                           = ?
    +++ exited with 1 +++

File tells me that /lib/ld-linux.so.3 is the interpreter. I don't have that on my system. Maybe it's looking for that?

    # file ./kubelet 
    ./kubelet: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, for GNU/Linux 2.6.32, BuildID[sha1]=ac4dd7a5783443d49bc4ff8e593f42126e841be3, not stripped

Contrast with kubectl (which works)

    # file /usr/bin/kubectl
    /usr/bin/kubectl: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, not stripped

**Comment by IanLewis** [comment]
Bingo. If I link the right library to /lib/ld-linux.so.3 then kubelet will work.

    ln -s ln -s /lib/ld-linux-armhf.so.3 /lib/ld-linux.so.3 /lib/ld-linux.so.3

**Comment by luxas** [comment]
This has been fixed in https://github.com/kubernetes/release/pull/133 a week ago, but seems like the new packages haven't been pushed then

**Comment by IanLewis** [comment]
@luxas Thanks for the pointer! Good to know it's been addressed already. I'm having another issue but I'll create another issue if necessary.
