### ISSUE TITLE
ExternalName type service cannot be created if without `spec.ports`. 

### ISSUE THREAD

**Issue by chengzhang1016** [kubernetes/kubernetes#34394]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): external service

**Kubernetes version** (use `kubectl version`):
v1.5.0-alpha.0.2084+162d80eced3989

**What happened**:
ExternalName type service cannot be created if without `spec.ports`. 

**How to reproduce it** (as minimally and precisely as possible):
Create a ExternalName type service: `kubectl create -f ExternalName type service`

```
{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "my-service"
    },
    "spec": {
        "type": "ExternalName",
        "externalName": "my.database.example.com"
    }
}
```

**Actual results**:
ExternalName type service created failed.

```
# kubectl create -f externalname-service.json
error: error validating "externalname-service.json": error validating data: field ports: is required; if you choose to ignore these errors, turn validation off with --validate=false
```

**Expected results**: 
Service should be created successful.

**Anything else do we need to know**:
You can refer to the docs about externalname type service: https://github.com/kubernetes/kubernetes.github.io/blob/release-1.4/docs/user-guide/services/index.md
The docs indicated that `An ExternalName service is a special case of service that does not have selectors. It does not define any ports or endpoints. Rather, it serves as a way to return an alias to an external service residing outside the cluster.`

**Comment by mdshuai** [comment]
@derekwaynecarr  @therc

**Comment by AdoHe** [comment]
this should be some validation error.

**Comment by chengzhang1016** [comment]
@mdshuai @derekwaynecarr @therc 
I opened this issue base on below three merged PRs:
https://github.com/kubernetes/kubernetes.github.io/pull/1063
https://github.com/kubernetes/kubernetes/pull/30599
https://github.com/kubernetes/kubernetes/pull/30931

**Comment by thaniyarasu** [comment]
This is working .


{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "my-service"
    },
    "spec": {
        "type": "ExternalName",
        "externalName": "my.database.example.com",
        "ports": [{ "port": 3000 }]
    }
}

**Comment by chengzhang1016** [comment]
@thaniyarasu No. My means is that ExternalName type service cannot be created if without `spec.ports`.
You can try again via your josn without `"ports": [{ "port": 3000 }]`

You can refer to the docs about externalname type service: https://github.com/kubernetes/kubernetes.github.io/blob/release-1.4/docs/user-guide/services/index.md
The docs indicated that `An ExternalName service is a special case of service that does not have selectors. It does not define any ports or endpoints. Rather, it serves as a way to return an alias to an external service residing outside the cluster.`

**Comment by chengzhang1016** [comment]
@thaniyarasu ExternalName type service should be created successful without `spec.ports` by document: https://github.com/kubernetes/kubernetes.github.io/blob/release-1.4/docs/user-guide/services/index.md

**Comment by AdoHe** [comment]
@chengzhang1016 I opened a PR #34789 to create ExternalName service through kubectl, you may want to take a look.

**Comment by chengzhang1016** [comment]
@hodovska Verified. Thanks for your fixing.
