### ISSUE TITLE
kubeadm join doesn't join a cluster eventually

### ISSUE THREAD

**Issue by redhatlinux10** [kubernetes/kubernetes#34406]
**Kubernetes version** (use `kubectl version`):
kubeadm version
>version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.0.1534+cf7301f16c0363-dirty", GitCommit:"cf7301f16c036363c4fdcb5d4d0c867720214598", GitTreeState:"dirty", BuildDate:"2016-09-27T18:10:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
 
kubectl version
>Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:

>i don't use any cloud providers.

- **OS** (e.g. from /etc/os-release):

>No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

- **Kernel** (e.g. `uname -a`):

>Linux zxadmin-desktop 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**:
- **Others**:

**What happened**:

>when i run  `kubeadm join --token f195d1.03a47122f3a4c70a 10.114.51.198` in a slave node, it outputs:
>><util/tokens> validating provided token
<node/discovery> created cluster info discovery client, requesting info from "http://10.114.51.198:9898/cluster-info/v1/?token-id=f195d1"
<node/discovery> cluster info object received, verifying signature using given token
<node/discovery> cluster info signature and contents are valid, will use API endpoints [https://10.114.51.198:443]
<node/csr> created API client to obtain unique certificate for this node, generating keys and certificate signing request
<node/csr> received signed certificate from the API server, generating kubelet configuration
<util/kubeconfig> created "/etc/kubernetes/kubelet.conf"
Node join complete:
* Certificate signing request sent to master and response
  received.
* Kubelet informed of new secure connection details.
Run 'kubectl get nodes' on the master to see this machine join.

> but even after about half hour, running `kubectl get nodes` in the master node doesn't show the newly joined nodes. 

**What you expected to happen**:

>`kubectl get nodes` show:
>>NAME              STATUS    AGE
zxadmin-desktop   Ready     47m
tss-SBCJ                 Ready     47m

>tss-SBCJ is slave node's hostname

**How to reproduce it** (as minimally and precisely as possible):

>`kubeadm init` a cluster 
run `kubeadm join` on another slave node to join that initialised cluster

**Anything else do we need to know**:

>none

**Comment by redhatlinux10** [comment]
@kubernetes/sig-cluster-lifecycle

**Comment by redhatlinux10** [comment]
i have found why this happened.
on the slave node, i forgot to install docker-engine. this is the reason.
so there is another question, why `kubeadm join` succeed even when docker-engine is not installed on the slave node ?

**Comment by errordeveloper** [comment]
> so there is another question, why `kubeadm join` succeed even when docker-engine is not installed on the slave node ?

@redhatlinux10 the instructions state that you need to launch `kubelet.service` as well as `docker.service`. We are planning to implement check for this, but haven't done it yet. I believe instructions are very clear about this, did you miss this part?

**Comment by luxas** [comment]
Fixed by: #34341

**Comment by yash1425** [comment]
Perhaps similar question:

http://stackoverflow.com/questions/40294423/kubeadm-why-does-my-node-not-show-up-though-kubelet-says-it-joined/40416796#40416796

**Comment by iahmad-khan** [comment]
Yes , I faced the same problem.

I resolved by:

killall kubelet
run the kubectl join command again
and start the kubelet service

**Comment by xandriaw** [comment]
@iahmad-khan  can you describe what you mean by killall kubelet??

**Comment by iahmad-khan** [comment]
@xandriaw
Kill all the kublet processes by killall command if u are on linux
