### ISSUE TITLE
apiserver crash on ARM

### ISSUE THREAD

**Issue by IanLewis** [kubernetes/kubernetes#34412]
BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.4.0

**Environment**:
- **Cloud provider or hardware configuration**: Raspberry Pi
- **OS** (e.g. from /etc/os-release): Ubuntu Xenial
- **Kernel** (e.g. `uname -a`): Linux ubuntu 4.4.0-1023-raspi2 #29-Ubuntu SMP Tue Sep 6 16:12:44 UTC 2016 armv7l armv7l armv7l GNU/Linux
- **Install tools**: 
- **Others**:

**What happened**:

After running `kubeadm init` the apiserver fails to come up. It crashes with the flowing error:

        I1009 12:01:03.540764       1 genericapiserver.go:762] Serving insecurely on 127.0.0.1:8080
        I1009 12:01:03.554288       1 handlers.go:162] GET /api/v1/namespaces/kube-system/endpoints/kube-controller-manager: (7.306536ms) 200 [[kube-controller-manager/v1.4.0 (linux/arm) kubernetes/a16c0a7] 127.0.0.1:35818]
        I1009 12:01:03.637390       1 reflector.go:249] Listing and watching *api.Namespace from ????
        I1009 12:01:03.646734       1 handlers.go:162] GET /api/v1/namespaces?resourceVersion=0: (5.117357ms) 200 [[kube-apiserver/v1.4.0 (linux/arm) kubernetes/a16c0a7] 127.0.0.1:35820]
        E1009 12:01:03.676378       1 runtime.go:64] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:70
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:63
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:49
        /usr/local/go_k8s_patched/src/runtime/asm_arm.s:429
        /usr/local/go_k8s_patched/src/runtime/panic.go:458
        /usr/local/go_k8s_patched/src/runtime/panic.go:62
        /usr/local/go_k8s_patched/src/runtime/sigpanic_unix.go:24
        /usr/local/go_k8s_patched/src/sync/atomic/asm_linux_arm.s:109
        /usr/local/go_k8s_patched/src/sync/atomic/64bit_arm.go:10
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/storage/etcd/etcd_watcher.go:57
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/storage/etcd/etcd_watcher.go:316
        /usr/local/go_k8s_patched/src/runtime/asm_arm.s:998
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
                panic: runtime error: invalid memory address or nil pointer dereference
        [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x11fa64]

        goroutine 200 [running]:
        panic(0x2799878, 0x14022008)
                /usr/local/go_k8s_patched/src/runtime/panic.go:500 +0x3f4
        k8s.io/kubernetes/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
                /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:56 +0x170
        panic(0x2799878, 0x14022008)
                /usr/local/go_k8s_patched/src/runtime/panic.go:458 +0x51c
        sync/atomic.loadUint64(0x14152be4, 0x0, 0x0)
                /usr/local/go_k8s_patched/src/sync/atomic/64bit_arm.go:10 +0x58
        k8s.io/kubernetes/pkg/storage/etcd.(*HighWaterMark).Update(0x14152be4, 0x0, 0x0, 0x146b26a8)
                /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/storage/etcd/etcd_watcher.go:57 +0x24
        k8s.io/kubernetes/pkg/storage/etcd.(*etcdWatcher).translate(0x14152b80)
                /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/storage/etcd/etcd_watcher.go:316 +0x564
        created by k8s.io/kubernetes/pkg/storage/etcd.newEtcdWatcher
                /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/storage/etcd/etcd_watcher.go:172 +0x2fc

**What you expected to happen**:

The API server should come up normally.

**How to reproduce it** (as minimally and precisely as possible):

1. Installed docker.io kubelet kubeadm kubectl kubernetes-cni via apt according to the [kubeadm guide](http://kubernetes.io/docs/getting-started-guides/kubeadm/).
2. Ran kubeadm init on a Raspberry Pi.

**Comment by luxas** [comment]
Known issue. I fixed it in v1.4.1 (also works with v1.4.1-beta.2)

I had to do **a lot** of stuff this release to get ARM working, and everything didn't make .0, so .1 (which comes tomorrow) will work.

I will add a HypriotOS guide to the kubeadm doc very soon...

See: #33485 #33117 #33376 #32517
