### ISSUE TITLE
error: <master/discovery> failed to create "kube-discovery" deployment [deployments.extensions "kube-discovery" is forbidden: not yet ready to handle request]

### ISSUE THREAD

**Issue by swqmaven** [kubernetes/kubernetes#34411]
used kubeadm init error? thanks for help!

**Comment by epish** [comment]
got the same error. It might be due to an invalid state of etcd cluster. the solution provided in #33956 fixed my issue.

**Comment by errordeveloper** [comment]
I'm going to fix this.

**Comment by errordeveloper** [comment]
The workaround is to pause `kubeadm` with `^Z` for a minute or so.
```
root@julius-samsung:~# kubeadm init
<master/tokens> generated token: "9d24d3.cbde568fcec57046"
<master/pki> created keys and certificates in "/etc/kubernetes/pki"
<util/kubeconfig> created "/etc/kubernetes/kubelet.conf"
<util/kubeconfig> created "/etc/kubernetes/admin.conf"
<master/apiclient> created API client configuration
<master/apiclient> created API client, waiting for the control plane to become ready
^Z
[1]+  Stopped                 kubeadm init
root@julius-samsung:~# fg
kubeadm init
<master/apiclient> all control plane components are healthy after 64.445601 seconds
<master/apiclient> waiting for at least one node to register and become ready
<master/apiclient> first node is ready after 0.518454 seconds
<master/discovery> created essential addon: kube-discovery, waiting for it to become ready
<master/discovery> kube-discovery is ready after 3.010838 seconds
<master/addons> created essential addon: kube-proxy
<master/addons> created essential addon: kube-dns

Kubernetes master initialised successfully!

You can now join any number of machines by running the following on each node:

kubeadm join --token 9d24d3.cbde568fcec57046 192.168.3.177
```

**Comment by mooperd** [comment]
The workaround suggested by @errordeveloper doesn't work for me. It just sits at kubeadm init indefinitely.

**Comment by mooperd** [comment]
@errordeveloper - It just sits there indefinitely after I fg the process.... :(


[root@CentOS-72-64-minimal ~]# kubeadm init
<master/tokens> generated token: "c6e4c8.aae9cf5d56b21a44"
<master/pki> created keys and certificates in "/etc/kubernetes/pki"
<util/kubeconfig> created "/etc/kubernetes/kubelet.conf"
<util/kubeconfig> created "/etc/kubernetes/admin.conf"
<master/apiclient> created API client configuration
<master/apiclient> created API client, waiting for the control plane to become ready
^Z
[1]+  Stopped                 kubeadm init
[root@CentOS-72-64-minimal ~]# fg
kubeadm init

**Comment by errordeveloper** [comment]
@mooperd that sounds like a different problem, did you run `systectl start kubelet`?
