### ISSUE TITLE
kubeadm 1.4: kube-dns fails on CentOS 7.1

### ISSUE THREAD

**Issue by jimmyjones2** [kubernetes/kubernetes#34420]
CentOS 7.1.1503 minimal VM, using kubeadm guide with weave networking. kube-dns has issues starting up:

```
I1009 20:09:37.093825       1 dns.go:173] Ignoring error while waiting for service default/kubernetes: Get https://100.64.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 100.64.0.1:443: getsockopt: no route to host. Sleeping 1s before retrying.
E1009 20:09:39.098145       1 reflector.go:214] pkg/dns/dns.go:155: Failed to list *api.Endpoints: Get https://100.64.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 100.64.0.1:443: getsockopt: no route to host
I1009 20:09:39.522095       1 logs.go:41] skydns: failure to forward request "read udp 10.32.0.2:48292->192.168.1.1:53: i/o timeout"
```

Disabling firewalld resolves the issue.

**Comment by errordeveloper** [comment]
> Disabling firewalld resolves the issue.

I believe we need to work out what would be better here. May be @dgoodwin has some ideas?

**Comment by errordeveloper** [comment]
@luxas this is tagged incorrectly, we should fix the bot...

**Comment by errordeveloper** [comment]
Are you using VirtualBox?

**Comment by jimmyjones2** [comment]
@errordeveloper Yes

**Comment by errordeveloper** [comment]
I've managed to resolv this and other issue in my Vagrant+Ansible repo (https://github.com/errordeveloper/kubernetes-ansible-vagrant), please take a look and let me know if you have any question (Slack may be the best place). There are a few things around firewalld and SELinux, that repo has all the right pieces without disabling both of those security features of CentOS.

**Comment by jimmyjones2** [comment]
@errordeveloper Do you know if your firewall fixes will be folded into kubeadm?

**Comment by dgoodwin** [comment]
Doing a little experimenting today with kubelet compiled from master (1.5 effectively) and the new selinux work done there, it looks as though kube-dns and weave can come up without issue and with no denials when selinux is enforcing.

**Comment by luxas** [comment]
So you mean v1.5 will work fine on CentOS without `setenforce 0`?

**Comment by dgoodwin** [comment]
Yes I believe so, in my testing we do still need etcd running unconfined because it uses /var/lib/etcd/, but we don't need kube-discovery running unconfined anymore (but it's going away soon anyhow), and the weave/kube-dns problems appear to be gone as well.

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#29
