### ISSUE TITLE
aws: support for custom IP routes

### ISSUE THREAD

**Issue by rbtcollins** [kubernetes/kubernetes#34430]
**Is this a request for help?** Nope. 
## **What keywords did you search in Kubernetes issues before filing this one?** ip route and read every match subject

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Please permit injecting custom routes into the master and minions.

Why, you might ask?

In AWS the routes objects only apply to the VPC routers; the DHCP option set's objects are limited to a small list of DHCP options, in particular the route option is missing. This means that to configure custom routes -  e.g. to direct some but not all outbound traffic to a NAT gateway (useful for some IP-locked APIs) - a config management approach needs to be used.

This seems related to, but distinct from, https://github.com/kubernetes/kubernetes/issues/23478 - though if you considered it just another feature request there that would be understandable :). We're working up a patch set at the moment to do this (needs must), but having some guidance - e.g. grains vs pillars, and if there's a preferred way to inject this into the grains.conf files - should we use new adjacent fails, or the existing grains.conf, or ... - that sort of feedback would be most excellent.

**Kubernetes version** (use `kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.1.900+d5bde66e80f8c4-dirty", GitCommit:"d5bde66e80f8c405201b3dd6e50a1fb669300d2f", GitTreeState:"dirty", BuildDate:"2016-09-16T05:01:27Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:21:58Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**How to reproduce it** (as minimally and precisely as possible):

**Comment by justinsb** [comment]
kube-up is considered deprecated, so we'd be unlikely to accept it into the main tree.

However, check out kops & in particular https://github.com/kubernetes/kops/issues/428

We'd love to have your input there on use of DHCP to steer traffic.  The biggest challenge with NAT gateways I believe is that they aren't multi-AZ, so we need multiple route tables, which doesn't work with built-in AWS VPC routing.  So it's looking like we'd have to require something like weave.  But if we could use DHCP somehow...

**Comment by justinsb** [comment]
(or rather, steering traffic using the DHCP approach, even if we then have to do it directly!)

**Comment by rbtcollins** [comment]
Huh, I did not know that kube-up is deprecated - http://kubernetes.io/docs/getting-started-guides/aws/ still points at get-kube :/ with no mention of deprecation. I'm a little miffed at that, as we just brought up the tooling etc we're using around get-kube. ça la vie I guess.

Will comment on the kops ticket.

**Comment by rbtcollins** [comment]
NAT gateways are single-AZ - they live in a subnet, and subnets are single-AZ.

One way of meeting our use case is to do this:
head subnet:
  - NAT gateway
kube subnet:
  - master + minions + etc etc
  - route 1.2.3.4/32 to the IP of the NAT gateway.

But that depends on a multi-subnet deployment facility :- 6/1 1/2 dozen of the other at that point :)
