### ISSUE TITLE
Questions about disk-accounting and disk storage limitation

### ISSUE THREAD

**Issue by liubog2008** [kubernetes/kubernetes#34439]
I have read proposal [disk-accounting](https://github.com/pmorie/kubernetes/blob/3335a5bb195474d521db8adfc18faa92e130f5c8/docs/proposals/disk-accounting.md) which mentions a solution to limit disk storage. I'm confused about some questions.

Questions:
1. Does it decide that quota based on gid is the solution of disk limitation for ext4?
2. Quota based on gid can't limit root user. Does it mean that some pods' disk storage is limitless(e.g. privileged containers).
3. Why not use LVM to limit disk usage?

**Comment by liubog2008** [comment]
cc @vishh

**Comment by vishh** [comment]
> Does it decide that quota based on gid is the solution of disk limitation for ext4?

Quota based on `gid` will not work well with overlay filesystems. So we'd prefer using project quota.

> Quota based on gid can't limit root user. Does it mean that some pods' disk storage is limitless(e.g. privileged containers).

As mentioned earlier, we do not plan on using `gid` based quota. And as a side note try avoiding running as `root` if you can in general.

> Why not use LVM to limit disk usage?

Additional overhead, both technical and performance wise. Why do we need LVM?

**Comment by liubog2008** [comment]
Thanks for your reply... @vishh 
So this feature will not come until project quota is supported by ext4?

**Comment by ddysher** [comment]
right now, there is soft limitation enforced by kubelet https://github.com/kubernetes/kubernetes/pull/45686
> So this feature will not come until project quota is supported by ext4?

**Comment by andyxning** [comment]
Just learned recently that xfs supports (`xfs_quota`)[https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/storage_administration_guide/xfsquota] to limit a directory disk usage. Any thoughts about leveraging this feature on xfs. However it is only supported on xfs for now.(correct me if i am wrong).
