### ISSUE TITLE
wrong volume mounted on AWS when EBS volume changes device node as part of detach from nodeX and attach to nodeY

### ISSUE THREAD

**Issue by pdbogen** [kubernetes/kubernetes#34437]
**Is this a request for help?** No.

**What keywords did you search in Kubernetes issues before filing this one?** "wrong volume"

**Is this a BUG REPORT or FEATURE REQUEST?** Bug report.

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.7", GitCommit:"a2cba278cba1f6881bb0a7704d9cac6fca6ed435", GitTreeState:"clean", BuildDate:"2016-09-12T23:15:30Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0+coreos.1", GitCommit:"0aa76668512ea62a7356920d2b2198430e1ef3ef", GitTreeState:"clean", BuildDate:"2016-09-27T19:39:47Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): coreos

```
NAME=CoreOS
ID=coreos
VERSION=1122.2.0
VERSION_ID=1122.2.0
BUILD_ID=2016-09-06-1449
PRETTY_NAME="CoreOS 1122.2.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
- **Kernel** (e.g. `uname -a`): `Linux k8s-worker-1 4.7.0-coreos #1 SMP Tue Sep 6 14:39:20 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz GenuineIntel GNU/Linux`
- **Install tools**:
- **Others**:

**What happened**:
1. Node A was in an unhealthy state; drained it. Service X with EBS volume was running on this node, thus it was rescheduled elsewhere, on node B. Volume was mounted as /dev/xvdba
2. Perhaps due in part to Node A's unhealthiness, volume for service X was not being unmounted/detached. Manually unmounted and detached volume.
3. Kubernetes automatically attached volume to node B as /dev/xvdbb.
4. Node has volume already mounted on /dev/xvdba. Kubernetes used the moint point observed at time of initial volume assignment (xvdba), thus _wrong_ volume is mounted into container. Madness ensues.

**What you expected to happen**:
Kubernetes should have re-observed at some point the actual device node for the volume, and mounted the correct volume into the pod.

**How to reproduce it** (as minimally and precisely as possible):
It depends in part on getting a node into an unhealthy state. I hypothesize this will reproduce the problem:
0. Suppose a two-node cluster where both nodes have some volumes mounted. Ensure that volume A on node A is mounted on /dev/xvdba; and volume B on node B is also mounted on /dev/xvdba. 
1. Kill kubelet on node A.
2. Drain node A, so that the pod that uses volume A is rescheduled to node B.
3. Unmount and detach volume A from node B, possibly after waiting a few minutes to see if the volume shows up.

**Anything else do we need to know**:
The volume incorrectness persisted across pod restarts (e.g., by scaling RC down to 0 then back up). I'm assuming the volume assignment is somehow persistent, and so the wrong identification of device node persisted.

**Comment by jingxu97** [comment]
@pdbogen Thank you for posting the issue. We identified the problem and had the fix in #33796 which is already merged in the head and release 1.4.1. We would appreciate if you could also help verify the fix in your cluster. Please let us know if you have any problems. Thanks!
