### ISSUE TITLE
Make e2e framework use generated clientset instead of unversioned client.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#34441]
We want to get rid of unversioned client eventually.

cc @wojtek-t @caesarxuchao @dchen1107 @kubernetes/test-infra-maintainers

**Comment by caesarxuchao** [comment]
We probably should let it use the clientset in client-go.

**Comment by caesarxuchao** [comment]
Related: https://github.com/kubernetes/kubernetes/issues/29934

**Comment by ixdy** [comment]
cc @kubernetes/sig-testing

**Comment by dshulyak** [comment]
I will help with this refactoring

**Comment by gmarek** [comment]
@dshulyak - thanks!

**Comment by gmarek** [comment]
I think it's mostly done.
/close
