### ISSUE TITLE
TODO syntax proposal

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#34463]
This proposes a convention for TODO statements in our codebase, and adding a linter to the presubmit checks that enforces adherence to this syntax.
## Rationale

There are a lot of TODOs in our codebase. `git checkout upstream/master && git grep TODO | wc -l` indicates `3971` TODOs. We have not consistently written TODOs in a way that makes them easy to track and delegate.
## Philosophy

Each TODO should be associated with a GitHub issue for tracking and delegation. The TODO statement in the code should contain at minimum the issue number and a brief, one-line description of the work that needs to be completed. Optionally, the inline TODO can also include a date or K8s version by which the TODO should be completed. This will allow us to track when TODOs are overdue.
## Syntax

The proposed syntax is to have the word `TODO`, followed by a `(`, followed by an `#<issue-number>`, optionally followed by a `:mm/dd/yyyy` (for an ETA date) or a `:vx.x.x` (for an ETA version), followed by a `):` (because unfinished business is `):`), followed by a brief one-line description of the work to be done. 

If more inline detail is required or considered useful, it should be provided in additional lines below the first. Each of these additional lines should be four-spaces indented from the `TODO`'s alignment, so they line up with the `(` character after the `TODO`. The `TODO` itself should be indented one space from the `//` (meaning additional lines begin five spaces from the `//`).

Here is a succinct definition of the syntax:

```
// TODO(#<issue-number>[:mm/dd/yyyy|:vx.x.x]): Brief, one-line description of todo.
[//     additional information if necessary]
```

Here is an example:

```
// TODO(#12345:v1.5.0): Brief, one-line description of todo.
//     More lines if additional detail near code is helpful.
//     These should be aligned with spaces after the `//`.
```
## Writing a good TODO issue

The issue title should be as similarly-titled to the TODO description as possible, but we won't enforce anything because issue titles are mutable.

Questions you should always ask yourself: Who, What, When, Where, Why, How.

All of the following are useful bits of information to have:
Rationale for:
- Why this work can't be finished now.
- What needs to be done in the future.
- When it needs to be done.
- Who is responsible for doing it.
- How it should probably be done.
- Link to the PR that introduced the TODO.
- Link to the PR containing the completed work described in the TODO.

You might not necessarily _need_ to say all of these things, but you should at least think about them when writing the issue.
## Linting PRs for correct TODO syntax

It is hard to get people to change how they write TODOs, or even get the word out that there is a new syntax. For this reason, we also ought to have a linter that runs as part of the presubmit checks on PRs. 

To avoid penalizing people for all the non-compliant TODOs in files they happen to edit, we should only lint TODOs that show up in the diff for a PR. This doesn’t help if you end up moving a block of code with an existing but non-compliant TODO in it. That is perhaps annoying, but it is also your opportunity to help improve K8s issue tracking :).

@apelisse any suggestions on how to implement such a linter?
## Documenting this change

It looks like the appropriate place to document this is probably in https://github.com/kubernetes/kubernetes/blob/master/docs/devel/coding-conventions.md. Does that sound correct to everyone?

**Comment by mtaufen** [comment]
I don't see any labels that relate do development process improvements, any suggestions on how to label this?

**Comment by thockin** [comment]
LGTM overall.  I like the link to a bug because it simultaneously logs who
wrote the TODO (i.e. who has context), when it was written, and allows for
feedback.  These bugs can re relatively short - they just need to exist
with enough info for someone to pick up later.

**Comment by timstclair** [comment]
I think it's helpful for the issue to link back to the TODO in the code as well. It's easy for code links to get out of date, but since github doesn't have literal code searching, I think best effort is good enough.

When should TODO issues be filed? On the one hand, it's nice to have the issues be filed for the review. On the other hand, it's a bit odd to have open issues for code that hasn't been submitted (and might not be submitted).

It might be overkill, but we could consider writing a script to auto-file issues for TODOs in a git diff (detect new TODOs, file issues, insert issue #)

Minor nit: your TODO count includes `vendor`. The total is still over 3k though.

**Comment by mtaufen** [comment]
Agreed on the issue having a link to the TODO. If we have this link point to the TODO at the hash where the origin PR was merged, we can probably get decent mileage using git to track what happens to it after that.

I think they should probably be filed for the review. Part of the review process should be ensuring that issues are filed to track TODOs. If it would cause too much confusion to have TODO issues floating around for unmerged PRs, maybe we could have a labeling scheme like `todo/unmerged` and `todo/merged`. 

Wrt the script to auto-file, I think it might be enough to lint for the following:
- The todo contains a valid issue number.
- The title of the referenced issue matches `TODO: Same as brief one-line description in code.`

That way we don't need the bot to modify code files as part of the submit process.

And good point about `vendor`. In the latest upstream/master the all-inclusive count is 3984 and the vendor count is 766, for a non-vendor total of 3218.

**Comment by thockin** [comment]
IMO, linking from the issue to the TODO is pointless - you can always grep
for `TODO(#issue-num)`.  xref to PR is sufficient.
