### ISSUE TITLE
Getting Started Guide for Ubuntu Calico is outdated

### ISSUE THREAD

**Issue by sauercrowd** [kubernetes/kubernetes#34460]
The Getting Started Guide for Ubuntu with Calico at http://kubernetes.io/docs/getting-started-guides/ubuntu-calico/  is out of date.

The used kubernetes in this document version is **1.14**, which leads to issues with up-to-date docker versions. 

Also i want to point out that the calico version used in this document is **0.14.0**, while the current version is **0.22.0**. (I'm not sure if this also leads to compatibility issues, I'm still testing.)

**Comment by pwittrock** [comment]
@sauercrowd This should probably be moved out of the docs repo and somewhere else

**Comment by castrojo** [comment]
This issue was moved to kubernetes/kubernetes.github.io#4167
