### ISSUE TITLE
kubelet-cri-gce-e2e-ci container restart backoff test failures

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#34492]
Test failures : https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubelet-cri-gce-e2e-ci/358
Test history: [link](https://k8s-testgrid.appspot.com/google-node#kubelet-cri-gce-e2e&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Pods%5C%20should%5C%20have%5C%20their%5C%20auto%5C-restart%5C%20back%5C-off%5C%20timer%5C%20reset%5C%20on%5C%20image%5C%20update%5C%20%5C%5BSlow%5C%5D)

[k8s.io] Pods should cap back-off at MaxContainerBackOff [Slow]
[k8s.io] Pods should have their auto-restart back-off timer reset on image update [Slow] 14m6s

For some reason, test-grid didn't collect the data from 336-357 builds, so the test history couldn't be used directly to identify offending PRs.
I went to the good old jenkins, and found the first failing build: http://kubekins.dls.corp.google.com/job/kubelet-cri-gce-e2e-ci/343/

Changes included in this build, copied from the jenkins page:
```
Grab different etcd versions in etcd image. (detail / githubweb)
Make sure GetPodStatus can get statuses of all containers in a pod. (detail / githubweb)
Change the timestamp unit to nanosecond. (detail / githubweb)
Add MinAge for sandbox GC. (detail / githubweb)
```

It seems like #34287 is likely the cause. 

/cc @Random-Liu

**Comment by Random-Liu** [comment]
I think the reason is that we expect the timestamp to be in `nanoseconds`, however, we are using `time.Unix` which returns in `seconds`.
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/docker_container.go#L283
