### ISSUE TITLE
Need a uniform interface for init systems

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#34494]
docker and kubelet are managed by different init system, such as systemd and upstart, based on OS and setup. In e2e testing, we usually want to manipulate services like docker. Then the test has to accommodate different init systems.  

Need a uniform util to interact with underlying init system. It should support `Status, Start, Stop, Restart` operations.

**Comment by luxas** [comment]
Yes, we need this for kubeadm too
We should probably put it somewhere in `pkg/util`..., any preference where?

**Comment by luxas** [comment]
@freehan Please review the code that we've added to `pkg/util/initsystem` and see if it satisfies your requirements
