### ISSUE TITLE
Fix scheduler perf tests 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#34504]
Problem 

Looks like the master in scheduler performance tests is coming up with panics due to a nil data structure (or else , something is very corrpupt in my build env., but i doubt that).  There were some recent changes to clients and master APIs, probably that is the culprit.  

Thoughts 

Happy if scheduler_perf is still working for folks as of monday morning, to close this issue but for me it seems broke, and the  panic is   i traced down to a nil client configuration object before i gave up and just started looking at how other, similar tests are spinning up masters. 

Solution

I think this happened breifly after commit 204dbe7fdd3bcc88916b359a71baf59f2c3807a7 , but not sure.  Seems like in any case there is a cleaner way to spin a master up that is more declarative that other tests are running.  This avoids the nil exception, probably related to changes to the client or the wrapper apis for the master or something.

```

	h := &framework.MasterHolder{Initialized: make(chan struct{})}
	s := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		<-h.Initialized
		h.M.Handler.ServeHTTP(w, req)
	}))

	framework.RunAMasterUsingServer(framework.NewIntegrationTestMasterConfig(), s, h)
	
	restClient := client.NewOrDie(&restclient.Config{
		Host:          s.URL,
		ContentConfig: restclient.ContentConfig{GroupVersion: &registered.GroupOrDie(api.GroupName).GroupVersion},
		QPS:           5000.0,
		Burst:         5000,
	})

```

Ill submit a PR shortly to see what folks thing.   @davidopp  @timothysc @gmarek

**Comment by davidopp** [comment]
Also @jayunit100 had mentioned we should try to get this integrated into the continuous build testing.

**Comment by gmarek** [comment]
cc @wojtek-t

**Comment by wojtek-t** [comment]
commit 204dbe7fdd3bcc88916b359a71baf59f2c3807a7 doesn't influence apiserver at all. And generally it should no-op, because the equivalence-classes are not fully implemented, so this code is not switched on.
I'm pretty sure this is something different.

**Comment by jayunit100** [comment]
Yup some time after 204dbe7 it I think.

**Comment by jayunit100** [comment]
We will need to follow up on this, the nil exception is fixed now but I think there are other moving parts we need to patch, gmarek I think has a patch on the way
