### ISSUE TITLE
failed to delete namespace from federation

### ISSUE THREAD

**Issue by yarntime** [kubernetes/kubernetes#34519]
get the following error msg when trying to delete a namespace from the federation: 
`namespace_controller.go:371] Failed to delete namespace *: no kind "DeleteOptions" is registered for the internal version of group "federation"`

kubernetes cluster info:
 `Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0+a16c0a7", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0+a16c0a7", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by nikhiljindal** [comment]
@yarntime Can you please specify the command you used to delete the namespace?
Did you use our go client or kubectl?
If you are using kubectl then will be great if you can add --v=9 to your command and add the output here

**Comment by yarntime** [comment]
@nikhiljindal, thank you for your help.

the output:

> [root@master test]# kubectl get namespaces
NAME      STATUS    AGE
zw-test   Active    3m

> [root@master test]# kubectl delete namespaces zw-test --v=9
I1013 10:03:29.090804    2972 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.4.0+a16c0a7 (linux/amd64) kubernetes/a16c0a7" http://192.168.101.82:30080/api
I1013 10:03:29.183766    2972 round_trippers.go:318] GET http://192.168.101.82:30080/api 200 OK in 92 milliseconds
I1013 10:03:29.183789    2972 round_trippers.go:324] Response Headers:
I1013 10:03:29.183799    2972 round_trippers.go:327]     Content-Type: application/json
I1013 10:03:29.183809    2972 round_trippers.go:327]     Date: Thu, 13 Oct 2016 01:59:52 GMT
I1013 10:03:29.183818    2972 round_trippers.go:327]     Content-Length: 134
I1013 10:03:29.183962    2972 request.go:908] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"172.16.235.8:443"}]}
I1013 10:03:29.184428    2972 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.4.0+a16c0a7 (linux/amd64) kubernetes/a16c0a7" http://192.168.101.82:30080/apis
I1013 10:03:29.185837    2972 round_trippers.go:318] GET http://192.168.101.82:30080/apis 200 OK in 1 milliseconds
I1013 10:03:29.185856    2972 round_trippers.go:324] Response Headers:
I1013 10:03:29.185866    2972 round_trippers.go:327]     Content-Length: 561
I1013 10:03:29.185907    2972 round_trippers.go:327]     Content-Type: application/json
I1013 10:03:29.185917    2972 round_trippers.go:327]     Date: Thu, 13 Oct 2016 01:59:52 GMT
I1013 10:03:29.190584    2972 request.go:908] Response Body: {"kind":"APIGroupList","groups":[{"name":"extensions","versions":[{"groupVersion":"extensions/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"extensions/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"172.16.235.8:443"}]},{"name":"federation","versions":[{"groupVersion":"federation/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"federation/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"172.16.235.8:443"}]}]}
I1013 10:03:29.191976    2972 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.4.0+a16c0a7 (linux/amd64) kubernetes/a16c0a7" http://192.168.101.82:30080/api
I1013 10:03:29.193198    2972 round_trippers.go:318] GET http://192.168.101.82:30080/api 200 OK in 1 milliseconds
I1013 10:03:29.193218    2972 round_trippers.go:324] Response Headers:
I1013 10:03:29.193228    2972 round_trippers.go:327]     Content-Type: application/json
I1013 10:03:29.193237    2972 round_trippers.go:327]     Date: Thu, 13 Oct 2016 01:59:52 GMT
I1013 10:03:29.193246    2972 round_trippers.go:327]     Content-Length: 134
I1013 10:03:29.193309    2972 request.go:908] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"172.16.235.8:443"}]}
I1013 10:03:29.193507    2972 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.4.0+a16c0a7 (linux/amd64) kubernetes/a16c0a7" http://192.168.101.82:30080/apis
I1013 10:03:29.194747    2972 round_trippers.go:318] GET http://192.168.101.82:30080/apis 200 OK in 1 milliseconds
I1013 10:03:29.194769    2972 round_trippers.go:324] Response Headers:
I1013 10:03:29.194779    2972 round_trippers.go:327]     Content-Length: 561
I1013 10:03:29.194788    2972 round_trippers.go:327]     Content-Type: application/json
I1013 10:03:29.194797    2972 round_trippers.go:327]     Date: Thu, 13 Oct 2016 01:59:52 GMT
I1013 10:03:29.194857    2972 request.go:908] Response Body: {"kind":"APIGroupList","groups":[{"name":"extensions","versions":[{"groupVersion":"extensions/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"extensions/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"172.16.235.8:443"}]},{"name":"federation","versions":[{"groupVersion":"federation/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"federation/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"172.16.235.8:443"}]}]}
I1013 10:03:29.195567    2972 round_trippers.go:299] curl -k -v -XDELETE  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.4.0+a16c0a7 (linux/amd64) kubernetes/a16c0a7" http://192.168.101.82:30080/api/v1/namespaces/zw-test
I1013 10:03:29.200452    2972 round_trippers.go:318] DELETE http://192.168.101.82:30080/api/v1/namespaces/zw-test 200 OK in 4 milliseconds
I1013 10:03:29.200467    2972 round_trippers.go:324] Response Headers:
I1013 10:03:29.200473    2972 round_trippers.go:327]     Content-Type: application/json
I1013 10:03:29.200480    2972 round_trippers.go:327]     Date: Thu, 13 Oct 2016 01:59:52 GMT
I1013 10:03:29.200486    2972 round_trippers.go:327]     Content-Length: 336
I1013 10:03:29.200538    2972 request.go:908] Response Body: {"kind":"Namespace","apiVersion":"v1","metadata":{"name":"zw-test","selfLink":"/api/v1/namespaces/zw-test","uid":"9fa7e687-90e8-11e6-b671-0a4561eeffab","resourceVersion":"16257","creationTimestamp":"2016-10-13T01:59:06Z","deletionTimestamp":"2016-10-13T01:59:52Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Terminating"}}
namespace "zw-test" deleted

> [root@master test]# kubectl get namespaces
NAME      STATUS        AGE
zw-test   Terminating   5m

and the federation-controller-manager prints:
`
namespace_controller.go:371] Failed to delete namespace zw-test: no kind "DeleteOptions" is registered for the internal version of group "federation"
`

**Comment by nikhiljindal** [comment]
Yes there was an issue with kubectl 1.4.0 which has now been fixed. Can you try with the latest version?

**Comment by yarntime** [comment]
I will try it later, thank you very much.

**Comment by kshafiee** [comment]
@yarntime do you have any updates on this? I seem to have the same problem. Thx

**Comment by yarntime** [comment]
Hi @kshafiee, you can try the latest version.

**Comment by kshafiee** [comment]
@yarntime I tried kubectl version 1.4.4

**Comment by grodrigues3** [comment]
@yarntime @kshafiee this issue hasn't been updated in awhile.  If the fix didn't solve the issue, please reopen
