### ISSUE TITLE
How to read client IP addresses from HTTP requests behind Kubernetes services? 

### ISSUE THREAD

**Issue by lufeng4828** [kubernetes/kubernetes#34532]
Hi all,

first of all any help is appreciated

I have 3 nginx pods behind Kubernetes services, right now, how can I read client IP addresses from HTTP in nginx

Thanks for the explanation! 

Environment (also see manifests for more detailed info):
Centos 7.0.1406
Kubernetes: 1.2.0
etcd: 2.3.7
flannel: 0.5.3
docker: 1.10.3

Thanks a lot for any suggestions.

**Comment by zetaab** [comment]
your loadbalancer in front of kubernetes service should apply real ip to original request http header. Lets say that it is added to header called X-Forwarded-For header. Then in pods you will see real ip in header called that. This means that you need to run loadbalancer in http mode (not TCP).
