### ISSUE TITLE
Very API Reference Test Diffs OWNERs File 

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/kubernetes#34572]
The [PR](https://github.com/kubernetes/kubernetes/pull/31752/files) to generate new OWNERs files is [failing tests](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/31752/kubernetes-pull-verify-all/17201/) because the bash script is attempting to verify an OWNERs file in a generated directory.

```
diff -NauprB -I 'Last update' '--exclude=*.md' /go/src/k8s.io/kubernetes/docs/api-reference/autoscaling/OWNERS /go/src/k8s.io/kubernetes/_tmp/api-reference/autoscaling/OWNERS
--- /go/src/k8s.io/kubernetes/docs/api-reference/autoscaling/OWNERS	2016-10-06 17:25:40.635683219 -0700
+++ /go/src/k8s.io/kubernetes/_tmp/api-reference/autoscaling/OWNERS	1969-12-31 16:00:00.000000000 -0800
@@ -1,2 +0,0 @@
-reviewers:
-- gmarek
/go/src/k8s.io/kubernetes/docs/api-reference is out of date. Please run hack/update-api-reference-docs.sh
FAILED   hack/make-rules/../../hack/verify-api-reference-docs.sh	66s
```

The problem seems to be in `hack/verify-api-references-docs.sh`, possibly with this line: 
```
diff -NauprB -I 'Last update' --exclude=*.md "${API_REFERENCE_DOCS_ROOT}" "${OUTPUT_DIR}" || ret=$?
```

(my bash readability isn't great, but I think it's trying to diff all the docs and it ends up diffing OWNERs files as well)

**Comment by grodrigues3** [comment]
@erictune @nikhiljindal assigning you guys based on `git blame`.

**Comment by nikhiljindal** [comment]
Yes `verify-api-reference-docs.sh` verifies that everything in `docs/api-reference` can be generated by running `update-api-reference-docs.sh`.
Do we really want to add an OWNERS file to that directory? All the code there is auto generated by running `update-api-reference-docs.sh`

**Comment by grodrigues3** [comment]
I think you're right and we don't want to add an OWNERs file there.  I've pinged @calebamiles to get rid of the OWNERs files there and it should hopefully fix the problem

**Comment by nikhiljindal** [comment]
Removing OWNERS from that dir fixed the problem.
Closing this
