### ISSUE TITLE
federation-up is broken

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#34575]
It fails with:
```
error: yaml: line 17: mapping values are not allowed in this context
```

cc @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
cc @madhusudancs @colhom

**Comment by colhom** [comment]
@nikhiljindal make sure you are running the `build/` scripts with `FEDERATION=true` env var exported. That is what controls whether `${KUBE_ARCH}/kubernetes/server/bin/federation-apiserver.docker_tag` gets created.

**Comment by nikhiljindal** [comment]
@colhom With https://github.com/kubernetes/kubernetes/pull/29929, we are not generating the federation-apiserver binary and instead using the hyperkube binary.

**Comment by colhom** [comment]
@nikhiljindal sorry, i copied the wrong line. The droid you're looking for:

`"${KUBE_ROOT}/federation/manifests/federated-image.tag"`

* File conditionally written during `build/release` process
   https://github.com/kubernetes/kubernetes/blob/master/build/release.sh#L43-L49

* File consumed when templating federation control plane yaml 
  https://github.com/kubernetes/kubernetes/blob/master/federation/cluster/federation-up.sh#L30

**Comment by nikhiljindal** [comment]
Right. My `federation/manifests/federated-image.tag` is also empty.
I am trying to run federation e2e tests. 
The command I am running is:
`FEDERATION=true E2E_ZONES="us-central1-a us-central1-f" KUBE_RELEASE_RUN_TESTS=n KUBE_FASTBUILD=true go run hack/e2e.go -v -build && FEDERATION=true build/push-federation-images.sh && NUM_NODES=1 FEDERATION=true E2E_ZONES="us-central1-a us-central1-f" KUBE_UP_AUTOMATIC_CLEANUP=true go run hack/e2e.go -v --up` which is what I have always used.

I guess something changed in hack/e2e.go

**Comment by colhom** [comment]
@nikhiljindal that should definitely work. Please `set -x` and then run the `hack/e2e.go -build` step, capture the output and email to me? I was literally doing exactly this process for another PR today, and I verified the image tag file was getting written correctly as well.

**Comment by shashidharatd** [comment]
I figured out this is happening because after make clean or a fresh clone, kubectl will not be available when we are trying to get the semantic_image_tag_version() in here. https://github.com/kubernetes/kubernetes/blob/master/build/util.sh#L26

**Comment by quinton-hoole** [comment]
Awesome!  Thanks @shashidharatd
