### ISSUE TITLE
kube-proxy.exe flag redefined: log_dir

### ISSUE THREAD

**Issue by vklonghml** [kubernetes/kubernetes#34582]
hi, forums, i'm using this guide(https://docs.google.com/document/d/1IjwqpwuRdwcuWXuPSxP-uIz0eoJNfAJ9MWwfY20uH3Q/edit#heading=h.c15wonvangdk) to compile kube-proxy on windows, and 
run it on windows server 2016, but it failed to start with "kube-proxy.exe flag redefined: log_dir", i found 
this error was course by client-go and k8s conflict, when run "go install" in cmd/kube-proxy, i need go get 
client-go package, so the error happens, does anybody know this error, thks.

**Comment by ikaven1024** [comment]
i met the same issue when using 1.4.x on linux.

**Comment by vklonghml** [comment]
@ikaven1024 do you have solved the problems, could you tell me how to solve this, thks.

**Comment by kargakis** [comment]
See the discussion in https://github.com/kubernetes/kubernetes/issues/35096
