### ISSUE TITLE
kube-dns returning the wrong IP

### ISSUE THREAD

**Issue by mikekap** [kubernetes/kubernetes#34590]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kube-dns stale/wrong

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.3.5

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu Xenial
- **Kernel** (e.g. `uname -a`): Linux 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 GNU/Linux
- **Install tools**: Custom install (fluentd + etcd via ELB + kube-master via ELB)
- **Others**: The custom install isn't terribly "custom" - it's based on an older version of Kelsey's Kubernetes the hard way. The major difference is that both etcd and the kube-master go through an ELB that terminates idle connections after 60s.

**What happened**: kube-dns didn't refresh the DNS entry of a pod that got recreated.

**What you expected to happen**: kube-dns to be up to date

**How to reproduce it** (as minimally and precisely as possible):
I don't have solid reproduction steps since this is very intermittent, but here is how this particular instance happened:
1. Create a PetSet (say `petset`) and Headless service (say `disco`)
2. Start a different pod with nslookup
3. `nslookup petset-0.disco`
4. Delete the PetSet pod. It should be recreated with the same name.
5. `nslookup petset-0.disco` See the same IP as before (rather than the new IP).

**Anything else do we need to know**:
Here's the reality I'm seeing now:

```
# nslookup kafka-0.kafka-discovery.default.svc.cluster.local
Server:     10.254.0.10
Address:    10.254.0.10#53

Name:   kafka-0.kafka-discovery.default.svc.cluster.local
Address: 10.9.13.13
```

But really:

```
$ kubectl get pod kafka-0 -o yaml | grep podIP
  podIP: 10.9.13.5
```

Interestingly, both instances of kube-dns are wrong on this one. It looks like the endpoints are correct though:

```
$ kubectl get --context prod endpoints kafka-discovery
NAME              ENDPOINTS                                      AGE
kafka-discovery   10.9.13.5:9092,10.9.37.5:9092,10.9.73.5:9092   68d
```

Restarting both kube-dns pods fixed the issue. Is it perhaps a refresh triggering an `OnUpdate` rather than an `OnDelete`+`OnAdd` & the handler doesn't expect the pod ip to change?

@justinsb

**Comment by nhlfr** [comment]
Couldn't reproduce that on master - probably it needs some backport.

**Comment by MrHohn** [comment]
All of delete/add/update should be reflected by `OnUpdate`. Did kube-dns always return the wrong IP after recreated the petset?

**Comment by bprashanth** [comment]
kube-dns latency aside (because dns should be updated around the time endpoints updates, in theory)

> 5. nslookup petset-0.disco See the same IP as before (rather than the new IP).

If your database allows hostnames, it should be re-resolving correctly on its own. 
If your database needs ips (and you're writing out the config with the exact ip), you should wait in the init container till your ip shows up in an nslookup of your name. 

So basically wait for the peer finder to deliver on-start: http://kubernetes.io/docs/user-guide/petset/bootstrapping/#example-ii-initializing-state-based-on-environment, and in the on-start handler, do something like `ip addr == nslookup $hostname`. 

I'd be fine adding this as an option to peer-finder, so it only delivers onStart after verifying ip, but most databases I've used fall under the first category (re-resolve changing ip on their own).

**Comment by mikekap** [comment]
The wrong IP was returned up to 24h after the initial pod restart, so it looks like it was "stuck" in kube-dns. I certainly didn't expect the ip to be instantly correct after the pod starts, but this wait was quite excessive.

To clarify, I only killed a petset pod - not the petset. The petset controller recreated the pod with the same name almost instantly (as expected). `kube-dns` never seemed to reconcile the new ip for the pod.

**Comment by mikekap** [comment]
Not sure if it helps, but this may be related to another peculiarity of my install - I have an ELB between the kube master & etcd. I just fixed an issue what was terminating idle connections there after 60s. That might be what triggered the desync.

**Comment by bowei** [comment]
please reopen if this issue is still relevant
