### ISSUE TITLE
kubectl set image has no unit tests

### ISSUE THREAD

**Issue by asalkeld** [kubernetes/kubernetes#34592]
**Is this a request for help?**
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
`set image`

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

As the subject says, there are no unit tests for "set image". This is partly due to the package that the cmd fakes are in. I'll post a PR with the fake NewAPIFactory() moved into a subpackage so there is no import loop.

**Comment by ymqytw** [comment]
cc: @janetkuo

**Comment by pwittrock** [comment]
Thanks

**Comment by janetkuo** [comment]
Cool thanks

**Comment by mengqiy** [comment]
/close
Closing since we have unit test now.
