### ISSUE TITLE
DNS issues

### ISSUE THREAD

**Issue by BoriszhangSec** [kubernetes/kubernetes#34602]
I deployed DNS, but I get the following results, when I delete the SVC, cannot be parsed,What should I do with a problem with this, and thank you
kubelet --version
Kubernetes v1.4.0+a16c0a7
![image](https://cloud.githubusercontent.com/assets/14834177/19307342/807dc300-90ac-11e6-9714-1836fa3385e8.png)

**Comment by MrHohn** [comment]
Can you explain "when I delete the SVC"? Do you mean delete the "mysql-service" service?

**Comment by BoriszhangSec** [comment]
o，sorry sir

mysql-service.defualt.**svc**.cluster.local      Can parsed 
mysql-service.defualt.cluster.local           cannot parsed

**Comment by MrHohn** [comment]
Thanks for explain this.

`mysql-service.default.cluster.local` is not a valid DNS name. Consider we set up several default search paths, you can consider using below input for DNS query:
- mysql-service(if the pod runs under `default` namespace)
- mysql-service.default
- mysql-service.default.svc

**Comment by BoriszhangSec** [comment]
ok,thanks :)

**Comment by MrHohn** [comment]
@BoriszhangSec Can you please close this issue if it is resolved? Thanks.
