### ISSUE TITLE
404 Not Found on links referring to /docs/user-guide/kubectl/kubectl/

### ISSUE THREAD

**Issue by kamigerami** [kubernetes/kubernetes#34613]
link referring to the kubectl command-line tool found 

[prereqs](http://kubernetes.io/docs/user-guide/prereqs/) 
[static-pods](http://kubernetes.io/docs/admin/static-pods/)
[replicasets](http://kubernetes.io/docs/user-guide/federation/replicasets/)
[secrets](http://kubernetes.io/docs/user-guide/federation/secrets/)
[replicasets](http://kubernetes.io/docs/user-guide/replicasets/)

are wrong and points to a none existing url.

All links are currently referring to : 
http://kubernetes.io/docs/user-guide/kubectl/kubectl/

but should be : 

http://kubernetes.io/docs/user-guide/kubectl/

**Comment by kamigerami** [comment]
PR here #1441

**Comment by ymqytw** [comment]
kubernetes/kubernetes.github.io#1441

**Comment by kamigerami** [comment]
Merged in https://github.com/kubernetes/kubernetes.github.io/commit/965eb76254eeb2870111cfc48c793118443d028d
