### ISSUE TITLE
[DaemonSet] [Ingress] Still in beta

### ISSUE THREAD

**Issue by alfirin** [kubernetes/kubernetes#34616]
_\_ Feature Request **

**Kubernetes version**

```
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.0", GitCommit:"fd1377a16b5e2e33f24a57848071616c81a7f58f", GitTreeState:"clean", BuildDate:"2016-06-10T21:26:58Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:13:36Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:
We want to use Kubernetes for our new production set-up.
However we need the ingress controller and the DaemonSet.
But they are still in beta.

I filled an issue for the `nginx-ingress-controller`: https://github.com/kubernetes/contrib/issues/1873

**What you expected to happen**:
When do you plan to make the DaemonSet / Ingress in a stable state.

**Comment by lukaszo** [comment]
It will take some time before it reaches GA(General Availability) Here you can see the requirements https://github.com/kubernetes/kubernetes/issues/15310

**Comment by bgrant0607** [comment]
Closing in favor of more specific issues. I suggest following the features repository or release roadmap blog posts.

That said, there are multiple types of stability:
* Reliable operation
* API compatibility

These are still beta more due to the latter than the former.
