### ISSUE TITLE
Service.Spec.Type should be immutable

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#34629]
Today we allow a Service.Spec.Type to change post creation.

We even test to allow it as a valid change:
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation_test.go#L6404

I think supporting this ability complicates the service controller, and causes the need to invoke cloud api providers to ensure a load balancer does or does not exist for services that were never a load balancer type.  This can consume A LOT of cloud provider api quota.

See: https://github.com/kubernetes/kubernetes/pull/34271

Opening this issue to ask again if there is any real user benefit to continue allowing service type to change?

/cc @thockin @pmorie @smarterclayton

**Comment by smarterclayton** [comment]
It also complicates quota and admission control.

**Comment by thockin** [comment]
I could get behind disallowing fundamental changes (e.g ExternalName ->
ClusterIP), but I think that lots of folks assume that you can upgrade from
ClusterIP -> LoadBalancer.  I don't think we can break that.

**Comment by smarterclayton** [comment]
Should you be able to transition from LoadBalancer -> ClusterIP?

You definitely can't transition from headless to non-headless or vice versa.

**Comment by thockin** [comment]
On Wed, Oct 12, 2016 at 7:14 PM, Clayton Coleman
<notifications@github.com> wrote:
>
> Should you be able to transition from LoadBalancer -> ClusterIP?

It has always been supported and tested...

> You definitely can't transition from headless to non-headless or vice versa.

ClusterIP is the only special field

> On Wed, Oct 12, 2016 at 8:06 PM, Tim Hockin <notifications@github.com>
> wrote:
>
> > I could get behind disallowing fundamental changes (e.g ExternalName ->
> > ClusterIP), but I think that lots of folks assume that you can upgrade from
> > ClusterIP -> LoadBalancer. I don't think we can break that.
> >

**Comment by derekwaynecarr** [comment]
not supporting a transition from LoadBalancer -> xyz would solve a lot of problems.

@pmorie -- lets catch up on this tomorrow.

**Comment by thockin** [comment]
I don't see how we can make such a change with the compat guarantees in
place.

**Comment by smarterclayton** [comment]
Security?  You can DOS an entire cluster just by flipping that value back
and forth...

**Comment by thockin** [comment]
We can apply hysteresis if we need.
