### ISSUE TITLE
learning cassandra on gcloud with k8s, some problem with petset

### ISSUE THREAD

**Issue by mcortinas** [kubernetes/kubernetes#34621]
Hi,
 
I'm newbie in k8s and gcloud, and I just starting with cassandra example https://github.com/kubernetes/kubernetes/blob/master/examples/storage/cassandra/cassandra-petset.yaml, I only set the k8s service but I have some problem with the petset.

My environ: 
`Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}`

I'm blocked on:
` ➜  kubernetes git:(master) ✗ kubectl create -f examples/storage/cassandra/cassandra-petset.yaml --validate=false
unable to recognize "examples/storage/cassandra/cassandra-petset.yaml": no matches for apps/, Kind=PetSet
`

**Comment by pwittrock** [comment]
@foxish @bprashanth  This either of you?

**Comment by bprashanth** [comment]
Chris probably has most context on c* + petset at this point

**Comment by foxish** [comment]
It seems like the api group itself is missing. This looks like a GKE issue to me. 

/cc @jlowdermilk

**Comment by bprashanth** [comment]
oh, i didn't read it. Are you running an alpha cluster? https://cloud.google.com/container-engine/docs/alpha-clusters, alpha resources aren't enabled by default on gke clusters

**Comment by foxish** [comment]
I just reproduced this with a new 1.4.0 cluster that I brought up. @bprashanth, shouldn't beta features be accessible by default?

**Comment by bprashanth** [comment]
petset is not beta

**Comment by foxish** [comment]
My mistake, needs to be run on alpha cluster. :)

**Comment by chrislovecnm** [comment]
@mcortinas you need to be running s cluster that has alpha enabled. By default in GKE alpha APIs are not enabled.

**Comment by paralin** [comment]
Can this be closed? PetSet is in alpha and not enabled on default.

**Comment by chrislovecnm** [comment]
:thumbsup

**Comment by jlowdermilk** [comment]
To summarize, if you want to test petset on GKE, create an [alpha cluster](https://cloud.google.com/container-engine/docs/alpha-clusters).
