### ISSUE TITLE
kubectl should set non-zero exit code on failures.

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kubernetes#34633]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

kubectl exit codes
kubectl return codes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`): 1.3.4

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Debian Jessie
- **Kernel** (e.g. `uname -a`):  Linux ip-172-20-42-63 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
- **Install tools**:  KOPS
- **Others**: n/a

**What happened**:

```
$ kubectl config use-context asdfasdf
no context exists with the name: "asdfasdf".
$ echo $?
0
```

**What you expected to happen**:
When kubectl fails, it should set a non-zero exit code. This way scripts calling kubectl can respond to failure.

**How to reproduce it** (as minimally and precisely as possible):

```
$ kubectl config use-context asdfasdf
no context exists with the name: "asdfasdf".
$ echo $?
0
```

**Anything else do we need to know**:

**Comment by AdoHe** [comment]
this is a bug, will open a PR to fix this.
