### ISSUE TITLE
Unit test flake: TestDeploymentController_dontSyncDeploymentsWithEmptyPodSelector

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#34636]
```
go test -v k8s.io/kubernetes/pkg/controller/deployment -run TestDeploymentController_dontSyncDeploymentsWithEmptyPodSelector$
```

As seen in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/34271/kubernetes-pull-test-unit-integration/48640/

**Comment by dims** [comment]
@pmorie this was already fixed i believe. https://github.com/kubernetes/kubernetes/issues/34580
