### ISSUE TITLE
Replace NewListWatchFromClient with corresponding clientset lister and watcher

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/kubernetes#34640]
Currently, the NewListWatchFromClient expects restclient (resp. implementation of `Getter` interface) for given resource. When replacing `unversion.Client` with `ClientSet`, the restclient is replaced with `Client.Core().GetRESTClient()` or similar string depending on resource version. As each clientset type has its own List and Watch method it make sense to replace the NewListWatchFromClient with corresponding `Client.Core().RESOURCE().List()/Watch()` call.

**Comment by ncdc** [comment]
cc @deads2k
