### ISSUE TITLE
Node E2E: We should test whether container log files are in the right place.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#34661]
Cluster logging assumes kubelet stores container log at a specific directory with specific name.

Currently the path is:

```
/var/log/containers/<pod_name>_<pod_namespace>_<container_name>-<container_id>.log
```

After the CRI work, the path will be:

```
/var/log/pods/<podUID>/<containerName>_<instance#>.log
```

However, we don't have test coverage for this. We don't even know whether the log files are there or not.
We should add a node e2e test for this, basically:
1) Create a container which prints logs
2) Check whether the expected log file is created.
3) Check whether the logs are collected in the file as expected.

And it would be better to launch a pod to do the check instead of accessing local file system directly, which makes containerizing easier.

@yujuhong 
/cc @dchen1107 because you are collecting missing test.
/cc @kubernetes/sig-node

**Comment by resouer** [comment]
@Random-Liu I will add a node-e2e test here

**Comment by feiskyer** [comment]
I think it's ok to add this for CRI. 

But there maybe problems on today's interface for rkt. If I'm not wrong, rkt does't store logs at same location with docker. cc/ @euank Is this true?

**Comment by Random-Liu** [comment]
> @Random-Liu I will try to add a node-e2e test there

@resouer Thanks! :)

**Comment by Random-Liu** [comment]
After #34877 gets merged, we need to update the test to verify the cri log path.
