### ISSUE TITLE
servicecontroller needs periodic reconciliation

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#34660]
We really need to add periodic reconcile to service controller. We didn't add it in 1.4 because there was enough other stuff going on, and the legacy controller never reconciled. 

There is surely a bug in 1.4 around updating status, where if it fails to update (because of conflict), it just drops the update, user sees `<pending>`, and the controller never retries. All resources for loadbalancer will actually be setup. 

I remember we had one bug around status update, but @mfanjie fixed it (the fix made it into 1.4 right?). 
@bowei fyi

**Comment by bprashanth** [comment]
We should also add some clarity around the status update failed path, there was nothing in logs

**Comment by justinsb** [comment]
@bprashanth are you talking about a reconciliation to the actual state of the world (i.e. read the list of all ELBs), or just a re-read of the desired state of the world?

**Comment by bprashanth** [comment]
Yeah re-list from kube, make sure ELBs are as we expect them to be, re-write kube-status if necessary. If a human messes something up, it should get corrected o(soon). We do the periodic relisting, but we don't actually follow through into the cloudprovider today, we just compare our (servicecontroller's) cached state with what the master gives us.

**Comment by thockin** [comment]
@kubernetes/sig-network 

We really should resolve this in 1.6. maybe even a 1.5 bugfix if we can do something ultra-minimal?

**Comment by bprashanth** [comment]
I think @freehan is looking at what it will take, and evaluating the risk of 1.5.x vs 1.6

**Comment by thockin** [comment]
Well, we really want to know how the particular issue we are seeing is
happening, and maybe point-fix that if we can, but yes.
