### ISSUE TITLE
API server should encrypt the secret object

### ISSUE THREAD

**Issue by ymqytw** [kubernetes/kubernetes#34668]
According to [#23564comment](https://github.com/kubernetes/kubernetes/issues/23564#issuecomment-252715115), when API server gives a client (e.g kubectl) a secret object, the secret has been exposed.
This is the root cause of #23564 and #20508.

From the client-APIServer prospective, I think we should let the API server encrypt the secret. When a client requests a secret object. The API server should give the encrypted data instead. The client could use the encrypted data to determine if the data need to update when calculate a patch (e.g. `kubectl apply` and `kubectl edit`).

**Comment by liggitt** [comment]
#20508 refers to capturing user-specified information from the command line invocation, not a Secret API object

https://github.com/kubernetes/kubernetes/issues/23564#issuecomment-252715115 is not proposing that the Secret API be modified, it is simply pointing out that printing the information in the describer is not leaking information.

The issue with #23564 is that `apply` moves secret data from the data map into an annotation. A naive user might remove information from the data map without realizing that same data was copied into an annotation, and is therefore still in the API object.

If a user wants to encrypt secret values, they can already do so (the API is just opaque bytes, which could be encrypted if desired).

There are also open issues tracking encrypting Secret data at rest or in the API (#12742, #28538, #10439)
