### ISSUE TITLE
deploy cluster fail with kubeadm

### ISSUE THREAD

**Issue by msplayer** [kubernetes/kubernetes#34677]
I have 2 machine:
10.86.8.109 (master) CentOS7
10.86.8.110 (cluster node) CentOS7

I use kubeadm to install master, it it works well, "kubectl get pods --all-namespaces" get all pods are running.
When I join a node to cluster, "kubectl get nodes" is still get only one localhost node. and pod "kube-apiserver", "etcd-localhost" restart endless.

I stop and disable firewall on both node as well.
It always like that:

```
kube-system   etcd-localhost.localdomain                      0/1       Pending   0          0s
kube-system   kube-controller-manager-localhost.localdomain   0/1       Pending   0          0s
kube-system   kube-discovery-982812725-wkb9w                  1/1       Running   0          17h
kube-system   kube-dns-2247936740-jk73s                       3/3       Running   0          16h
kube-system   kube-proxy-amd64-jgchq                          1/1       Running   0          16h
kube-system   weave-net-35a1t                                 2/2       Running   0          16h
```

if I get nodes: 
`localhost.localdomain   Ready     17h`

Thanks

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#40
