### ISSUE TITLE
Confusion regarding kube-addon-manager tags

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#34678]
`v6` is tagged: https://gcr.io/v2/google_containers/kube-addon-manager-amd64/tags/list

No `v6` is tagged: https://gcr.io/v2/google_containers/kube-addon-manager/tags/list

Further, `kube-addon-manager-amd64:v6` doesn't seem to be actually used anywhere...

**Comment by colemickens** [comment]
https://gcr.io/v2/google_containers/kube-addon-manager-amd64/tags/list

Now there is a `v5.2` recently published to GCR and a `v6.0` + `v6.0-alpha.1`, yet I don't see those tagged in the source repos.

@mikedanese any ideas or can you tag someone who knows what's up here?

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
I'm assuming sig-cluster-lifecycle owns addon management

**Comment by mikedanese** [comment]
Closing since this is pretty stale.
