### ISSUE TITLE
kubeadm hangs after 'waiting for the control plane' on Centos 7.2

### ISSUE THREAD

**Issue by rogerwelin** [kubernetes/kubernetes#34695]
**Environment**:
-  VMware
- CentOS Linux release 7.2.1511 (Core)
- kernel: 3.10.0-327.36.1.el7.x86_64
- Installed packages:
  kubeadm.x86_64                       1.5.0-0.alpha.0.1534.gcf7301f

kubectl.x86_64                           1.4.0-0

kubelet.x86_64                           1.4.0-0

kubernetes-cni.x86_64               0.3.0.1-0.07a8a2

docker-engine.x86_64                1.11.2-1.el7.centos

docker-engine-selinux.noarch    1.12.1-1.el7.centos

**What happened**:
kubeadm init hangs indefintely after:
kubeadm init
<master/tokens> generated token: "c645e2.9558b825e5be0fa6"
<master/pki> created keys and certificates in "/etc/kubernetes/pki"
<util/kubeconfig> created "/etc/kubernetes/kubelet.conf"
<util/kubeconfig> created "/etc/kubernetes/admin.conf"
<master/apiclient> created API client configuration
<master/apiclient> created API client, waiting for the control plane to become readykubeadm init

**What you expected to happen**:
Master node initialize

**Anything else do we need to know**:
Only the kubeadm and kublet processes are running. When I do docker ps no containers are running.
If i type docker images the only image that has been downloaded are: gcr.io/google_containers/pause-amd64

I've also tried: kubeadm init --api-advertise-addresses but with the same outcome (followed the clean-up at http://kubernetes.io/docs/getting-started-guides/kubeadm/)

Im behind a firewall so I'm using proxy settings for docker. I have confirmed I can reach images on docker hub and google cloud registry

**Comment by MahipalRao** [comment]
@rogerwelin 
`kubeadm init` will download the required binaries viz etcd. When you are behind firewall kubeadm will hang. I dont know whether it is addressed correctly in kubeadm implementation. I am also facing the same issue and waiting for the resolution.

**Comment by rogerwelin** [comment]
@MahipalRao Thx, I suspected it to be some firewall issue. Do you know if there's a way to add https_proxy & http_proxy settings to kubeadm?

**Comment by MahipalRao** [comment]
Kubeadm doesn't seem to pick proxy environment variables. 
I am looking at app/master/manifests.go
[https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/master/manifests.go](url)
recompiling with proxy support may work. But I dont know how to do that. 
Waiting for updates about proxy

**Comment by MahipalRao** [comment]
This issue same as 
[https://github.com/kubernetes/kubernetes/issues/33729](url)
Lets join there. 
The solution mentioned there may work.
`kubeadm init --use-kubernetes-version v1.4.1 `

**Comment by kad** [comment]
You can try kubeadm with patch applied from PR #35044 : https://www.dropbox.com/s/mgl182d7mzc0jiw/kubeadm?dl=0 It works at least in my environment behind restrictive proxy.

**Comment by rogerwelin** [comment]
@kad thanks, I will look into it
