### ISSUE TITLE
Cinder volume doesn't get attached to the pod

### ISSUE THREAD

**Issue by cityofships** [kubernetes/kubernetes#34698]
**Kubernetes version** (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0+coreos.0", GitCommit:"278a1f7034bdba61cba443722647da1a8204a6fc", GitTreeState:"clean", BuildDate:"2016-09-26T20:48:37Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Kolla Openstack Mitaka version with libvirt
- **OS** (e.g. from /etc/os-release): CoreOS stable (1122.2.0)
- **Kernel** (e.g. `uname -a`): 4.7.0-coreos
- **Install tools**: none
- **Others**: none

**What happened**:
Cinder volume gets attached to a kubernetes worker node but not to a pod:

```
I1012 11:35:28.757270       1 reconciler.go:168] Started AttachVolume for volume "kubernetes.io/cinder/762bf306-9748-4be0-a6c0-914821001116" to node "k8s-worker-1"
I1012 11:35:30.205320       1 attacher.go:95] Attach operation successful: volume "762bf306-9748-4be0-a6c0-914821001116" attached to node "69283384-874d-4b64-a2e3-ae628f79ec6d".
I1012 11:35:30.512329       1 attacher.go:104] Attach volume "762bf306-9748-4be0-a6c0-914821001116" to instance "69283384-874d-4b64-a2e3-ae628f79ec6d" failed with volume 762bf306-9748-4be0-a6c0-914821001116 is not attached to 69283384-874d-4b64-a2e3-ae628f79ec6d
E1012 11:35:30.512479       1 nestedpendingoperations.go:253] Operation for "\"kubernetes.io/cinder/762bf306-9748-4be0-a6c0-914821001116\"" failed. No retries permitted until 2016-10-12 11:35:31.012447432 +0000 UTC (durationBeforeRetry 500ms). Error: Failed to attach volume "vol01" on node "k8s-worker-1" with: volume 762bf306-9748-4be0-a6c0-914821001116 is not attached to 69283384-874d-4b64-a2e3-ae628f79ec6d
I1012 11:35:30.512632       1 event.go:217] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"mypod2", UID:"f9bb7961-906f-11e6-a1fb-fa163e94e8c1", APIVersion:"v1", ResourceVersion:"335533", FieldPath:""}): type: 'Warning' reason: 'FailedMount' Failed to attach volume "vol01" on node "k8s-worker-1" with: volume 762bf306-9748-4be0-a6c0-914821001116 is not attached to 69283384-874d-4b64-a2e3-ae628f79ec6d
I1012 11:35:31.062210       1 reconciler.go:168] Started AttachVolume for volume "kubernetes.io/cinder/762bf306-9748-4be0-a6c0-914821001116" to node "k8s-worker-1"
E1012 11:35:32.745559       1 openstack_volumes.go:64] Failed to attach 762bf306-9748-4be0-a6c0-914821001116 volume to 69283384-874d-4b64-a2e3-ae628f79ec6d compute
I1012 11:35:32.745596       1 attacher.go:97] Attach volume "762bf306-9748-4be0-a6c0-914821001116" to instance "69283384-874d-4b64-a2e3-ae628f79ec6d" failed with Expected HTTP response code [200] when accessing [POST http://openstack-ha:8774/v2/470e93b0a7d649c28c62353c5f36c93b/servers/69283384-874d-4b64-a2e3-ae628f79ec6d/os-volume_attachments], but got 400 instead {"badRequest": {"message": "Invalid volume: volume '762bf306-9748-4be0-a6c0-914821001116' status must be 'available'. Currently in 'in-use'", "code": 400}}
E1012 11:35:32.745724       1 nestedpendingoperations.go:253] Operation for "\"kubernetes.io/cinder/762bf306-9748-4be0-a6c0-914821001116\"" failed. No retries permitted until 2016-10-12 11:35:33.74569124 +0000 UTC (durationBeforeRetry 1s). Error: Failed to attach volume "vol01" on node "k8s-worker-1" with: Expected HTTP response code [200] when accessing [POST http://openstack-ha:8774/v2/470e93b0a7d649c28c62353c5f36c93b/servers/69283384-874d-4b64-a2e3-ae628f79ec6d/os-volume_attachments], but got 400 instead {"badRequest": {"message": "Invalid volume: volume '762bf306-9748-4be0-a6c0-914821001116' status must be 'available'. Currently in 'in-use'", "code": 400}}
I1012 11:35:32.745861       1 event.go:217] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"mypod2", UID:"f9bb7961-906f-11e6-a1fb-fa163e94e8c1", APIVersion:"v1", ResourceVersion:"335533", FieldPath:""}): type: 'Warning' reason: 'FailedMount' Failed to attach volume "vol01" on node "k8s-worker-1" with: Expected HTTP response code [200] when accessing [POST http://openstack-ha:8774/v2/470e93b0a7d649c28c62353c5f36c93b/servers/69283384-874d-4b64-a2e3-ae628f79ec6d/os-volume_attachments], but got 400 instead {"badRequest": {"message": "Invalid volume: volume '762bf306-9748-4be0-a6c0-914821001116' status must be 'available'. Currently in 'in-use'", "code": 400}}
```

Pod hangs in 'ContainerCreating' state and kubelet complains that volume is "not yet attached".
After manually detaching Cinder volume from an Openstack instance, it get's attached again and the error repeats.

**What you expected to happen**:
Cinder volume gets mounted to a pod and pod goes to a 'Running' state

**How to reproduce it** (as minimally and precisely as possible):
Use openstack as a cloud provider for Kubernetes 1.4.0 and try creating a pod with Cinder backed volume - either using a PersistentVolumeClaim or directly in a pod definition.

**Comment by jotacamou** [comment]
I'm experiencing the same problem given the same characteristics (OS, etc..).  Kubernetes doesn't seem to talk to Cinder at all.

**Comment by jotacamou** [comment]
Maybe this should go under the area/platform/openstack label?

**Comment by idvoretskyi** [comment]
@jotacamou updated. Thanks!

**Comment by nnashok** [comment]
Is there any update or a workaround for this? I'm also facing the same problem with:
Kubernetes 1.4.4
kubeadm for creating the cluster
openstack as cloud provider

**Comment by ferdi-bedag** [comment]
I'm using `--enable-controller-attach-detach=false` for now on kubernetes 1.4.x with openstack (kubernetes 1.4.6, coreos 1185.3.0). 

On my setup, the attach/detach controller never detaches cinder volumes from the compute. 
It is able to attach volumes, but somehow thinks that it was unable to do so. Every 5 seconds, it tries to attach the volume again (maybe this is normal)

```
I1129 11:28:07.498531       1 reconciler.go:202] Started AttachVolume for volume "kubernetes.io/cinder/98886632-9bd3-4bf3-b7af-e9be279d0308" to node "k8s-worker-2xql.xxx.xxx.ch"
I1129 11:28:09.110304       1 attacher.go:95] Attach operation successful: volume "98886632-9bd3-4bf3-b7af-e9be279d0308" attached to node "d0ac9769-fa0a-4e0f-b0f0-d644aa055569".
I1129 11:28:09.277540       1 attacher.go:104] Attach volume "98886632-9bd3-4bf3-b7af-e9be279d0308" to instance "d0ac9769-fa0a-4e0f-b0f0-d644aa055569" failed with volume 98886632-9bd3-4bf3-b7af-e9be279d0308 is not attached to d0ac9769-fa0a-4e0f-b0f0-d644aa055569
E1129 11:28:09.278319       1 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/cinder/98886632-9bd3-4bf3-b7af-e9be279d0308\"" failed. No retries permitted until 2016-11-29 11:28:09.777888695 +0000 UTC (durationBeforeRetry 500ms). Error: Failed to attach volume "data" on node "k8s-worker-2xql.xxx.xxx.ch" with: volume 98886632-9bd3-4bf3-b7af-e9be279d0308 is not attached to d0ac9769-fa0a-4e0f-b0f0-d644aa055569
I1129 11:28:09.278393       1 event.go:217] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"busybox", UID:"e68f2a47-b626-11e6-a5ee-fa163eee03fa", APIVersion:"v1", ResourceVersion:"4816", FieldPath:""}): type: 'Warning' reason: 'FailedMount' Failed to attach volume "data" on node "k8s-worker-2xql.xxx.xxx.ch" with: volume 98886632-9bd3-4bf3-b7af-e9be279d0308 is not attached to d0ac9769-fa0a-4e0f-b0f0-d644aa055569

I1129 11:28:09.807387       1 reconciler.go:202] Started AttachVolume for volume "kubernetes.io/cinder/98886632-9bd3-4bf3-b7af-e9be279d0308" to node "k8s-worker-2xql.xxx.xxx.ch"
I1129 11:28:10.665399       1 attacher.go:95] Attach operation successful: volume "98886632-9bd3-4bf3-b7af-e9be279d0308" attached to node "d0ac9769-fa0a-4e0f-b0f0-d644aa055569".
I1129 11:28:10.888408       1 operation_executor.go:612] AttachVolume.Attach succeeded for volume "kubernetes.io/cinder/98886632-9bd3-4bf3-b7af-e9be279d0308" (spec.Name: "data") from node "k8s-worker-2xql.xxx.xxx.ch".

I1129 11:28:13.185609       1 reconciler.go:202] Started AttachVolume for volume "kubernetes.io/cinder/98886632-9bd3-4bf3-b7af-e9be279d0308" to node "k8s-worker-2xql.xxx.xxx.ch"
I1129 11:28:13.526351       1 attacher.go:91] Attach operation is successful. volume "98886632-9bd3-4bf3-b7af-e9be279d0308" is already attached to node "d0ac9769-fa0a-4e0f-b0f0-d644aa055569".
I1129 11:28:13.666842       1 operation_executor.go:612] AttachVolume.Attach succeeded for volume "kubernetes.io/cinder/98886632-9bd3-4bf3-b7af-e9be279d0308" (spec.Name: "data") from node "k8s-worker-2xql.xxx.xxx.ch".
```

**Comment by eviloop** [comment]
@ferdi-bedag would this be related with #29832 ?

We have the same issue with cinder Attach loop and volumes not working properly

**Comment by ferdi-bedag** [comment]
@eviloop I don't think so, because the attach/detach controller succeeds on my setup and kubelet is able to mount the attached volume at some point

**Comment by prg3** [comment]
I also have the same issue, The cluster runs nicely on 1.3.7, however upgrading to 1.4.6 causes this behaviour. It appears that the pod/node never completely releases the storage, so the attach is unable to function. 

Manually releasing the volumes via Openstack and then restarting the pod often, but not always corrects this issue.

**Comment by eviloop** [comment]
I believe i have the same error as the original reporter as well, but I am not sure

Cluster 1.4.5 - 1.4.6
I see:
- Attach volume reporting succeeded attached in loop.
- Openstack shows the volume attached.
- Host has the volume attached on /dev/bla

- I see no error related with fdisk, udevadm or something else.
- I see no formated or mounted volume
- I see the same error as the original poster on the kubelet /dashboard logs of the pod

**Comment by neith00** [comment]
I'm experiencing the same Issue.
any news on that one?

**Comment by bradbeam** [comment]
Similar to what @eviloop mentioned. 

A couple additional details: 
- `/var/lib/kubelet/plugins` is empty, so the mount of `/var/lib/kubelet/plugins/kubernetes.io/cinder/<uuid>` fails. 
- Disk is attached to VM as a qemu device which is not searched via CandidateDisks https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_volumes.go#L176
```
dmesg:
[176553.462158] scsi 2:0:0:2: Direct-Access     QEMU     QEMU HARDDISK    2.0. PQ: 0 ANSI: 5
...
$ ls -l /dev/disk/by-id
lrwxrwxrwx 1 root root  9 Feb 20 02:11 /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_205be308-85b6-4124-b -> ../../sdb
lrwxrwxrwx 1 root root  9 Feb 21 03:05 /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_84f6b94e-699b-49c5-8 -> ../../sdc
```

**Comment by mikebryant** [comment]
@bradbeam I have a PR open for that: https://github.com/kubernetes/kubernetes/pull/41498

We've worked around it by going back to the virtio mounts for now

**Comment by bradbeam** [comment]
@mikebryant I tested those changes locally and wasn't seeing any change

**Comment by bradbeam** [comment]
Found my issue. I had cloud-provider set on the kube-controller-manager, api server, etc but I was missing it on the kubelet. This caused the weird behavior of being able to attach volumes to worker nodes, but the worker nodes were unable to do anything with the mounted storage. I logged https://github.com/kubernetes/kubernetes/issues/42013 to address it. 
@mikebryant those chages are necessary as well, +1 from me. 

As a workaround until #41498 is merged, we added udev rules to create additional links that matched the current patterns

```
$ cat /etc/udev/rules.d/99-qemu-vd.rules 
ACTION=="add|change", ENV{ID_MODEL}=="*QEMU*", KERNEL=="sd*[!0-9]", SYMLINK+="disk/by-id/virtio-$env{ID_SERIAL_SHORT}"
ACTION=="add|change", ENV{ID_MODEL}=="*QEMU*", KERNEL=="sd*[0-9]", SYMLINK+="disk/by-id/virtio-$env{ID_SERIAL_SHORT}-part%n"
$ sudo udevadm trigger --attr-match=subsystem=block
$ sudo udevadm control --reload-rule
```

**Comment by eviloop** [comment]
Hello @bradbeam 

Awesome find ! I had not noticed this

Thanks !

**Comment by dims** [comment]
looks like #41498 is merged and https://github.com/kubernetes/kubernetes/issues/42013 is not really specific to openstack. so let's close this out

/close
