### ISSUE TITLE
Specify Username to exec health check commands

### ISSUE THREAD

**Issue by andyxning** [kubernetes/kubernetes#34704]
I have read the docs about [health check](http://kubernetes.io/docs/user-guide/liveness/). IMO, currently the health check command is run under **root** user. Is there any way to specify the username under who the health check can be run. This may be useful in health check logging with proper permission which will allow deletion and compress under non root user.

**Comment by pwittrock** [comment]
@yujuhong Do you know anything about this?

**Comment by yujuhong** [comment]
AFAIK, we currently don't support that. There is a similar issue for specifying a user when `exec` into a container (#30656). I think that'd be a prerequisite for supporting customized users for health checks.

**Comment by andyxning** [comment]
@yujuhong I have just find yesterday that `docker exec` and `docker run` support specify user by `-u` command line argument.

**Comment by yujuhong** [comment]
@andyxning yes, but kubernetes doesn't support this feature yet, and it requires some API changes. I do think it's a reasonable use case.

**Comment by andyxning** [comment]
@yujuhong Any plan for adding this functionality in Kubernetes. :-)
