### ISSUE TITLE
Jobs should have configurable limits of how many successful jobs should be preserved

### ISSUE THREAD

**Issue by mfojtik** [kubernetes/kubernetes#34710]
Currently, when you have ScheduledJob/CronJob that runs a Job "more often" every Job run leave a Job resource around which is not pruned. Also every job leave a Pod around without any pruning.

What I propose is to have a "limit" setting for Jobs and ScheduledJobs that will limit the number of successful jobs. If we exceed this limit, the old jobs are automatically pruned.

We also need a policy that says the Job will not leave the Pod around and the Pod will be deleted automatically.

**Comment by mfojtik** [comment]
@soltysh FYI, the wording might be better :)

**Comment by soltysh** [comment]
@erictune @bgrant0607 I've raised this topic in #28977 and I guess it might apply to other resources as well.

**Comment by bgrant0607** [comment]
@soltysh One possibility is to use quota. Delete the oldest completed ones when quota is exhausted, to ensure new ones could be launched.

**Comment by soltysh** [comment]
That would be the best option, I guess.

**Comment by kargakis** [comment]
This should be similar to revisionHistoryLimit for Deployments (maybe configurable to keep succeeded or failed jobs, default to keep latest jobs?)

**Comment by soltysh** [comment]
@bgrant0607 are you saying controller should look into quota and remove what is not needed? If not, that doesn't solve the problem. It'll only limit the surface. Personally I think I'd go with the solution similar to what Deployments have, like Michalis mentioned.

**Comment by bgrant0607** [comment]
@soltysh A field in ScheduledJob similar to the history limit in Deployment SGTM.

**Comment by soltysh** [comment]
@bgrant0607 do you mind renaming the `area/workload-api/scheduledjob` label to reflect the actual resource name, iow. to `cronjob`?

**Comment by soltysh** [comment]
@bgrant0607 do you mind renaming the `area/workload-api/scheduledjob` label to reflect the actual resource name, iow. to `cronjob`?

**Comment by bgrant0607** [comment]
@soltysh Done. We'll need to update the labels.yaml files once we make all the label changes.

**Comment by peay** [comment]
@soltysh is this still relevant and up for grabs?

I have a few CronJob running every couple minutes and jobs really pile up quickly, so I would be interested to work on this.

**Comment by soltysh** [comment]
Yes, go ahead, and ping me in the pr. Thanks for your help!

**Comment by peay** [comment]
Would you still rather go with a field in `CronJob` like with deployments (or, possibly, two fields, one with a limit on failed jobs and one with a limit on successful jobs)?

Alternatively, we could add a `JobGCControler` a bit similar to the `PodGCController`.

The GC route would be more generic I assume, as it can apply to jobs not created only by `CronJob`  (which is probably the main creator of jobs at the moment, granted, but still).

**Comment by soltysh** [comment]
Per https://github.com/kubernetes/kubernetes/issues/34710#issuecomment-261163142 we want fields on CronJob resource, having two per successful and failed sgtm.

**Comment by peay** [comment]
OK, I'll get started on that.

**Comment by peay** [comment]
I have made some good progress on that and will send a PR soon.

**Comment by soltysh** [comment]
@peay lemme know if you need help with it, I'd love to have that done for 1.6.

**Comment by bgrant0607** [comment]
@soltysh We should still think about how to solve this for non-CronJob-spawned Jobs.

**Comment by soltysh** [comment]
@bgrant0607 hmmm... I was hoping this will be partially solved with GC. I'll try to reach out to you next week and we can discuss this more on Slack.

**Comment by DreadPirateShawn** [comment]
Curious -- would this be a candidate for backporting to v1.5? It seems that using CronJobs in Kube 1.5 isn't really viable with this bug, since the jobs build up forever (which as we've seen causes cpu problems).

**Comment by kargakis** [comment]
@DreadPirateShawn we are not backporting features.

**Comment by julianvmodesto** [comment]
@bgrant0607 and @soltysh was there discussion about solving this for non-CronJob-spawned Jobs?

**Comment by soltysh** [comment]
@julianvmodesto sorry for late reply, was out for the past few weeks. How would you want to address this for non-cronjob-spawned jobs? In case of CJ-owned jobs it's clear who owns it and how many it can keep around?
