### ISSUE TITLE
Failure to create self-client in apiserver startup should be fatal

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#34728]
Right now its just an error, but it will cause admission failures later on.  This is currently the case because `test-integration` doesn't run a "normal" start flow for the integration tests.  We should rewire test-integration to run a "normal" api-server.

@smarterclayton You did a lot infrastructure set-up in origin that allowed me to wire it up.  Any chance of similar help in kube?

**Comment by smarterclayton** [comment]
*twitches*

**Comment by techtonik** [comment]
It should be easy to find, but I wish there could be links about this `test-integration` and "normal apiserver".

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/remove-area test-infra
/area test
/sig testing
because "integration tests"
