### ISSUE TITLE
TODO: Remove the opt-in for failing when swap is enabled.

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#34726]
We need to eventually remove the opt-in for the behavior where Kubelet fails with swap enabled. Swap enabled should be an error by default.

This can't be done immediately because we need to maintain legacy behavior.

TODO introduced in: https://github.com/kubernetes/kubernetes/issues/34463

**Comment by tonylambiris** [comment]
Please reconsider this option, we leverage the zram module to enable volatile swap space for our custom RHEL-based distribution using a systemd service file `zramswap.service`<sup>[1](#zramswap)</sup>:

```code
16:15:41 csos-builder ~ # systemctl cat zramswap.service
# /usr/lib/systemd/system/zramswap.service
[Unit]
Description=Zram-based swap (compressed RAM block devices)

[Service]
Type=oneshot
ExecStart=/usr/lib/systemd/scripts/zramctrl start
ExecStop=/usr/lib/systemd/scripts/zramctrl stop
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```

Could anyone be able to explain the technical merits behind making this decision in the first place?

Thanks in advance.

 <a name="zramswap">1</a>: https://aur.archlinux.org/packages/zramswap/
