### ISSUE TITLE
CentOS 7 hangs at "created API client, waiting for the control plane to become ready"

### ISSUE THREAD

**Issue by samnissen** [kubernetes/kubernetes#34720]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
Possibly the same issue as #33729 -- different OS. 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Kubernetes version** (use `kubectl version`):

``` bash
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: 
  privately hosted 4-core, 4gb VM
- **OS** (e.g. from /etc/os-release):

``` bash
NAME="CentOS Linux"
VERSION="7 (Core)"
```
- **Kernel** (e.g. `uname -a`):

``` bash
Linux abc-1234 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**What happened**:
I followed this guide precisely: http://kubernetes.io/docs/getting-started-guides/kubeadm/

At the step "(2/4) Initializing your master" the command `kubeadm init` stops at the line:

``` bash
<master/apiclient> created API client, waiting for the control plane to become ready
```

and never moves forward.

**What you expected to happen**:
The command would proceed as detailed in the guide.

**How to reproduce it** (as minimally and precisely as possible):
Follow the guide for CentOS 7 exactly.

**Anything else do we need to know**

**Comment by pswenson** [comment]
I have the same issue.... trying to debug now

**Comment by jim-yefeng** [comment]
The same problem...

**Comment by errordeveloper** [comment]
Are all folks commenting here behind a proxy? If so, there is https://github.com/kubernetes/kubernetes/issues/34695 and thereby this is a duplicate.

**Comment by errordeveloper** [comment]
If you are using VritualBox and Vagrant, please take a look at the reference implementation here: https://github.com/errordeveloper/kubernetes-ansible-vagrant.

**Comment by madchap** [comment]
I am not behind a proxy, and have that issue.

**Comment by samnissen** [comment]
Also not behind proxy, and on KVM

**Comment by smalllove1459** [comment]
Using a Proxy and stuck here for hours...

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#39

**Comment by kenzhaoyihui** [comment]
The same problems met. booming!

**Comment by aikongfu** [comment]
The same problem...and proxy doesn't work..

**Comment by kenzhaoyihui** [comment]
@aikongfu  it maybe occur the problem when use cmd "kubeadm init", so should  research the code about kubeadm api
