### ISSUE TITLE
ExternalName service support in kubectl

### ISSUE THREAD

**Issue by therc** [kubernetes/kubernetes#34731]
There's no way to create ExternalName services from the command line without using a YAML/JSON file. (See https://github.com/kubernetes/features/issues/33 for more details about the feature)

`kubectl expose` doesn't feel exactly right, because the whole point of ExternalName (CNAME) services is that there are no pods to be exposed and they are entirely a kube-dns artifact.

If `expose` is the way to go, its syntax will have to be changed from `(-f FILENAME | TYPE NAME) ...` to `(-f FILENAME | --external-name NAME | TYPE NAME) ...`. Otherwise, we'll need a new kubectl command.

**Comment by ncdc** [comment]
How about something like `kubectl create service foo --external-name=bar.com`?

**Comment by ncdc** [comment]
cc @fabianofranz @derekwaynecarr @smarterclayton

**Comment by smarterclayton** [comment]
I think create service is a good approach.

**Comment by fabianofranz** [comment]
SGTM

**Comment by AdoHe** [comment]
SGTM.

**Comment by AdoHe** [comment]
I am working on this and will open a PR today.

**Comment by AdoHe** [comment]
what about `kubectl create service externalname bar.com`, in consistent with other service types?

**Comment by smarterclayton** [comment]
Sounds more correct

**Comment by AdoHe** [comment]
This can be closed since the PR has been already merged. @kubernetes/sig-cli-misc

**Comment by SimenB** [comment]
@AdoHe Could you link to the PR? Or the docs for the command, which is what I'm really after? Can't find it mentioned on the website at least.

![image](https://cloud.githubusercontent.com/assets/1404810/21961012/9563d9de-dafe-11e6-9351-8e28293bf20e.png)

^ Only `kubectl create service *`

**Comment by AdoHe** [comment]
@SimenB I believe we already have these `create service` sub-commands:
```
create service clusterip

create service nodeport

create service loadbalancer

create service externalname
```
Sorry about no docs about this, the basic usage is `kubectl create service externalname my-ns --external-name bar.com`. I will update doc later.

**Comment by SimenB** [comment]
Ok, thanks. What version of kubectl will it be in? 1.6? 1.5.2 which I have installed doesn't have it at least.

```sh-session
$ kubectl create service --help
Create a service using specified subcommand.

Aliases:
service, svc

Available Commands:
  clusterip    Create a clusterIP service.
  loadbalancer Create a LoadBalancer service.
  nodeport     Create a NodePort service.

Usage:
  kubectl create service [options]

Use "kubectl <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).
```

```sh-session
$ kubectl create service externalname
error: unknown command "externalname"
See 'kubectl create service -h' for help and examples.
```

**Comment by AdoHe** [comment]
@SimenB seems it's in Milestone 1.6 :(

**Comment by kargakis** [comment]
https://github.com/kubernetes/kubernetes/pull/34789 was merged, closing this issue.

**Comment by nerusnayleinad** [comment]
Is this actually right? While `kubectl create service ...` works, `kubectl expose ... --type ExternalName ...`  is also valid, but it is not allowing you to select an external name.

With this approach, `--type ExternalName` should throw an error when doing `kubectl expose`
