### ISSUE TITLE
Service controller lacks integration tests

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#34738]
The service controller has no integration test coverage, which is bad for obvious reasons.

**Comment by pmorie** [comment]
cc @kubernetes/sig-network

**Comment by bprashanth** [comment]
I think lots of controllers lack that (assuming you mean test/integration), there should be quite a few e2es in e2e/service.go (but still in sufficient, give how much trouble that thing's given us in the past)

**Comment by pmorie** [comment]
@bprashanth yeah, it's not really sufficient.  I am working on an issue where the service controller exhausts the AWS quota due to repeat calls to `DescribeLoadBalancer` in the AWS API.  E2E isn't going to catch that, I don't think.  I want an integration test to verify that we don't make more cloud provider calls than we have to.

**Comment by bprashanth** [comment]
Probably the first step would be to write some fakes of the cloudprovider libs, don't think we already have that

**Comment by bprashanth** [comment]
Also fyi i think we put in some rudimentary backoff to prevent qps exhaustion on asw, @justinsb might remember

**Comment by pmorie** [comment]
@bprashanth There are already fakes for cloud provider.  All the dependencies are there to integration test this controller, we basically just need for someone to have time to go and do it.

**Comment by bprashanth** [comment]
Lets see if we can do this post code-freeze in 1.5

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @pmorie

**Comment by dims** [comment]
@pmorie @bprashanth looks like this won't make it to 1.5, so switching milestone. Please switch it right back if this is not appropriate

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.
