### ISSUE TITLE
TestContext parameters outside of It lambdas are unset.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#34735]
Problem:

If we declare a test

```
var _ = KubeDescribe(...){ 

    framework.Logf(framework.TestContext.KubeConfig)
    // The above prints nothing :(, because Testcontext isnt initialized yet.
}
```

Solution:
- add an init to test_context.go?
- add inits somewhere else 
- make TestContext a function (not a var) and let it lazy init itself
- any other ideas :) ? 

Should be simple to solve in a few minutes trying things/hacking 

@kubernetes/sig-testing

**Comment by ixdy** [comment]
can you explain why you're trying to `Logf` inside the `KubeDescribe` instead of a `BeforeEach`/`AfterEach`/`It`?

**Comment by rmmh** [comment]
Tests shouldn't have any side effects (I/O or networking) outside of their
It functions. All the other code runs every time, regardless of whether
ginkgo is set to run (with focus) or ignore (with skip) a particular test.

Log statements from skipped tests would be confusing.

**Comment by sjug** [comment]
```
It(fmt.Sprintf("scaling up to %v pods per node", framework.TestContext.scale), func() {
...
}
```

@iakshay 
Even when logging using `It` the TextContext isn't initialized. It would have to be done inside of the `It`.

**Comment by jayunit100** [comment]
- this is  a matter of making impossible for logging_soak to access parameters that are unset.
- WLOG (and more  importantly) its about making it impossible for *any* e2e to access unset variables.

**Comment by jayunit100** [comment]
@rmmh I agree,  but this is not about  i/o, it is about  configuration.
- but some (And increasingly-  more) tests are inherently defined via parameterization.    A declarative test should precisely report exactly the parameters is used.
- right now people either hack the code or make for loops to cover every possible case (100 pods, 1000 pods, etc) and then use filters to remove the cases they dont want.
