### ISSUE TITLE
kops travis/jenkis builder

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#34737]
some people asked for this, @kubernetes/sig-testing thoughts?

**Comment by ixdy** [comment]
Can you elaborate on what you're requesting?

**Comment by bprashanth** [comment]
Not 100% sure, I'll let @justinsb / @chrislovecnm elaborate

**Comment by chrislovecnm** [comment]
@ixdy we are not able to enable travisci builds on github.com/kubernetes/kops ~ we do not see the admin tab, and cannot configure webhooks for the project.  Can someone assist or grant us the perms to do that.

Thanks

p.s. on slack please ping me if you have questions

**Comment by ixdy** [comment]
@spxtr looks like you have the owner bit on the kubernetes org. Can you help?

**Comment by chrislovecnm** [comment]
@ixdy I am going to move this issue over to kops ... kinda should not be here :)

**Comment by chrislovecnm** [comment]
@ixdy / @bprashanth I moved this over to the kops repo.  Does someone want to put the close button?
