### ISSUE TITLE
Represent model (and verb) examples in OpenAPI

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes#34743]
We need a way to represent operation examples in OpenAPI to generate better documentation (#31266). My first though is to have special tags in type comment:

// Type is ....
// @example(post):
// {
//   id : "identifier",
//   ...
// }
// @endexample
// @example(put):
// {
//   id : "identifier",
//   ...
// }
// @endexample
...
Furthermore, we need to represent this as an extension in openapi. My suggestion is "x-k8s-example" field in Operation objects. Also The example should be a valid json that can be serialized to the type it is representing (validation on generation time). I would expect this task to take a week.

**Comment by mbohlool** [comment]
@lavalamp @pwittrock

**Comment by bgrant0607** [comment]
I believe there are 2 parts to this:
1. How do we express this in our interface definition?
2. How is it represented in OpenAPI?

Regarding (2), I thought OpenAPI supported examples? Search for "example" in the following:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

cc @kubernetes/sig-api-machinery
