### ISSUE TITLE
Changes to Kubectl behavior Release Notes

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#34746]

**Comment by ymqytw** [comment]
#35071

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @ymqytw @pwittrock

**Comment by pwittrock** [comment]
This is tracks writing the release notes for kubectl changes as part of the release process.  (yes it is a blocker, no it should not be tracked as part of items putting the release at risk)

**Comment by dims** [comment]
@pwittrock - "non-release-blocker" seems appropriate. I don't find any appropriate tag for "we gotta do this to get the release out" :)

**Comment by pwittrock** [comment]
#36085

specifying a -o jsonpath to a field that is not present in the returned resource will not cause a failure (exit code 1) and an error message `Error executing template: <field> is not found. ` instead of returning an empty value.

**Comment by ymqytw** [comment]
#34778 #35483 #37604
`kubectl drain`:
`kubectl drain` retries forever when PodDisruptionBudget doesn't allow the eviction.
`kubectl drain` now waits until all pods have been evicted or deleted before returning.
Adds support for StatefulSets in `kubectl drain`.
Drain will use the eviction sub-resource to evict the pods if the APIServer supports. Otherwise, use DELETE as in 1.4.

**Comment by ymqytw** [comment]
#33973
`kubectl edit`:
When encountering error, always go back to editor if possible. Always retain what user hand-edited.

**Comment by ymqytw** [comment]
#34584
`kubectl apply --force`
Delete and re-create the resource when `apply` keeps failing after retry several times.

**Comment by ymqytw** [comment]
#33250
`kubectl create --edit`
Support editing before creating resource from files, urls and stdin, e.g. `kubectl create -f config.yaml --edit`. It won't create anything when edit make no change.

**Comment by dims** [comment]
@pwittrock @ymqytw Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by ymqytw** [comment]
@dims Yes. Thanks.

@pwittrock we can keep using this issue for next release tracking.

**Comment by mengqiy** [comment]
/close
We don't need this any more.
