### ISSUE TITLE
Make Kubernetes etcd prefix configurable

### ISSUE THREAD

**Issue by pires** [kubernetes/kubernetes#3476]
Right now, there's a one-to-one association between a Kubernetes cluster and etcd. That's limiting in what concerns high-availability.

I for one, would like to have my etcd cluster outside of Kubernetes nodes, living for the sole purpose of providing the service to whatever apps I want, like a couple Kubernetes clusters (one for project A, another for project X).

This is not possible because etcd is not namespaced by any sort of cluster ID, thus clusters A & B data would overlap in a destructive way.

What I propose is to:
* Namespace etcd by some sort of unique cluster ID
* Implement ```apiserver``` support for master-slave operation, thus guaranteeing ```apiserver``` high-availability

**Comment by erictune** [comment]
Once #3376 goes in (hopefully today), kubelets will no longer depend on etcd.  So, you can then run a dedicated etcd instance for your apiserver. 

Apiserver high-availability should be tracked by an existing item.  I'll try to find it.

**Comment by derekwaynecarr** [comment]
If we make a change in this space (which would basically break all existing deployments), then whatever we should do to identify our cluster should be a common prefix for all our resource paths so this:

/registry/pods/ns/default/foo

becomes

/kubernetes.io/cluster1/registry/pods/ns/default/foo

Right now, it bugs me that our etcd path structures are not prefixed with kubernetes namespace to eliminate potential collisions.

**Comment by erictune** [comment]
#473 is about replicated master.

**Comment by lavalamp** [comment]
hm-- we've actually discussed doing the opposite, allowing apiserver to shard its various keys over multiple etcd instances. I guess there's no reason why we couldn't optionally accept a prefix as a config option.

**Comment by pires** [comment]
So, does this look like an agenda?

1. Decide the prefix to use (I like @derekwaynecarr proposition, ```/kubernetes.io/<cluster_id>```)
2. Decide ```cluster_id``` definition strategy (manual, automatic? If automatic, how to guarantee uniqueness? Etc.)
3. Implement ```cluster_id``` definition strategy
4. Implement prefix support in a retro-compatible way to avoid breaking existing clusters. Could this lead to a new tool responsible for simplifying cluster upgrades?

**Comment by erictune** [comment]
I suggest you do step 4 first.  That has the most clear value to everyone and the least potential for debate.  

It has these sub-items, I think:
 - add a flag to tell the apiserver what etcd prefix to use for new data.  Initially this is not interpreted to have any format, but it could well default to `/kubernetes.io/defaultclusterid/`, and be overriden by you as needed.
 - add a flag to tell the apiserver what old, possibly empty prefix, to copy old data from.   
 - add startup code to apiserver to migrate the etcd keys based on those flags, and make it resilient to etcd failures or restarts.
 - don't worry about kube-proxy and kubelet.  I have commits that I'll send as a PR soon to make kubelet and kube-proxy not use etcd on CoreOS, which IIRC is your preferred platform.

**Comment by pires** [comment]
Great suggestion, @erictune. I'd really like to contribute this but atm I don't know the code organization and my Go knowledge is nil.
Would anyone be interested in guiding me through the obstacles as they come by? If yes, I'm all in as I'd enjoy contributing more than just doc/script updates.

**Comment by derekwaynecarr** [comment]
We need a configurable etcd prefix as well.  Something like this is on my roadmap to do in a few weeks time, but I would love assistance if you want to get started.  

Feel free to reach out to me as needed.

**Comment by pires** [comment]
@derekwaynecarr thanks a lot. Will do.

**Comment by bgrant0607** [comment]
I'd also like a configurable etcd prefix. I can't recommend putting data from multiple k8s clusters into a single etcd, but I could see other trusted components sharing the etcd cluster.

**Comment by kbeecher** [comment]
I'd be interested in looking into this. Could someone please point me to a suitable starting point in the code? I suppose the startup code of the apiserver and wherever it receives flags would be good.

**Comment by kbeecher** [comment]
@erictune When you suggesting adding flags in the comment above, could you tell me whereabouts in the code you meant?

**Comment by pires** [comment]
@kbeecher `cmd/kube-apiserver/apiserver.go`?

**Comment by kbeecher** [comment]
@pires Yes, that's what I'm assuming... looks like the flags are in `cmd/kube-apiserver/app/server.go`

**Comment by bgrant0607** [comment]
@kbeecher Yes, cmd/kube-apiserver/app/server.go is the right place.

**Comment by kbeecher** [comment]
What would be the preferred approach to handling the addition of the prefix to the key?

Maybe the prefix becomes a property of the EtcdHelper and so the prefix (if specified) is prepended to the key within each create/delete/extract/set operation?

Or maybe the prefix should be stored by the registries, passed to them by the master during its init method, so it is already prepended to the keys before they arrive at the EtcdHelper?

Or maybe some other approach...?

**Comment by bgrant0607** [comment]
This is currently very messy. It would be a little better if everything had been converted to etcdgeneric. We should have a centralized key-producing function, similar to etcdgeneric.NamespaceKeyRootFunc, but which is used for both namespaced and non-namespaced resources.

For now, EtcdHelper does appear to be the only single chokepoint where we could introduce a universal prefix, and has the advantage that it wouldn't propagate the prefix widely throughout the code:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/master.go#L171
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L175

Perhaps @lavalamp or @smarterclayton has another suggestion, but that SGTM.

```
$ grep -r "\"/registry" pkg |grep -v test
pkg/registry/limitrange/registry.go:                            return etcdgeneric.NamespaceKeyRootFunc(ctx, "/registry/limitranges")
pkg/registry/limitrange/registry.go:                            return etcdgeneric.NamespaceKeyFunc(ctx, "/registry/limitranges", id)
pkg/registry/namespace/registry.go:                             return "/registry/namespaces"
pkg/registry/namespace/registry.go:                             return "/registry/namespaces/" + id, nil
pkg/registry/event/registry.go:                         return etcdgeneric.NamespaceKeyRootFunc(ctx, "/registry/events")
pkg/registry/event/registry.go:                         return etcdgeneric.NamespaceKeyFunc(ctx, "/registry/events", id)
pkg/registry/etcd/etcd.go:      ControllerPath string = "/registry/controllers"
pkg/registry/etcd/etcd.go:      ServicePath string = "/registry/services/specs"
pkg/registry/etcd/etcd.go:      ServiceEndpointPath string = "/registry/services/endpoints"
pkg/registry/etcd/etcd.go:      NodePath string = "/registry/minions"
pkg/registry/resourcequota/registry.go:                         return etcdgeneric.NamespaceKeyRootFunc(ctx, "/registry/resourcequotas")
pkg/registry/resourcequota/registry.go:                         return etcdgeneric.NamespaceKeyFunc(ctx, "/registry/resourcequotas", id)
pkg/registry/pod/etcd/etcd.go:  prefix := "/registry/pods"
pkg/registry/pod/etcd/etcd.go:  return "/registry/nodes/" + machine + "/boundpods"
pkg/registry/secret/registry.go:                                return etcdgeneric.NamespaceKeyRootFunc(ctx, "/registry/secrets")
pkg/registry/secret/registry.go:                                return etcdgeneric.NamespaceKeyFunc(ctx, "/registry/secrets", id)
```

**Comment by lavalamp** [comment]
Yeah, my plan is to evolve EtcdHelper to make it an implementation of a generic storage interface. It's the natural place to implement key prefixing.

**Comment by kbeecher** [comment]
I have started to work on this. You can see the latest state on my local branch here: https://github.com/endocode/kubernetes/commit/d2174dd051732e3d0600468b5a0093030e246d42

Please be aware this is a WIP. At the moment, it passes all tests and works only if the prefix is not specified (i.e. empty). 

I'd welcome any suggestions on how best to deal with the handful of hard-coded paths that @bgrant0607 showed in the comment above.

**Comment by bgrant0607** [comment]
@kbeecher Did you find etcd operations that didn't use EtcdHelper?

**Comment by kbeecher** [comment]
@bgrant0607 Sorry for the delay, I had to jump onto another project for a while.

To answer your question, I couldn't find any other operations not using EtcdHelper. However there is a FakeEtcdClient, which I think is only used by test files.

**Comment by kbeecher** [comment]
I rebased my WIP with the latest master. Here: https://github.com/endocode/kubernetes/commit/6fe7ff902847bc077fd86032da4383d818ae090a

Do you think this is in a state to start a PR?

**Comment by bgrant0607** [comment]
@kbeecher Thanks! Yes, looks pretty good. Just needs a test that changing the prefix actually does what it's supposed to do.

**Comment by derekwaynecarr** [comment]
@kbeecher I reviewed as well and thought it looked pretty good.  please open a PR

----- Original Message -----

**Comment by kbeecher** [comment]
If the earlier comments of @pires and @erictune are a guide to this task (https://github.com/GoogleCloudPlatform/kubernetes/issues/3476#issuecomment-70735984 and https://github.com/GoogleCloudPlatform/kubernetes/issues/3476#issuecomment-70366955), it looks as though the only part of this task now remaining is to support multiple clusters via a `cluster_id` as part of the etcd prefix, correct?

**Comment by pires** [comment]
@kbeecher it seems so.

**Comment by kbeecher** [comment]
If so, then I guess we need to start discussing how a cluster_id is worked into the etcd prefix.

Some questions as I understand them are:

1. Is the cluster_id automatically generated or manually specified?
    1. If automatic, how to guarantee uniqueness?
1. How does the user manage clusters? (I.e. assign nodes to clusters, define new clusters etc.)

**Comment by pires** [comment]
> Is the cluster_id automatically generated or manually specified?

I'd go with a manual approach so that cluster IDs make sense. Any devops can script their way onwards and guarantee uniqueness.

> How does the user manage clusters?

Proposal: `kubelet --cluster_id <cluster id>`. The `kubelet` is now responsible for registering the node (right @roberthbailey?) so this would be the desirable place to put it. It also makes it easy for devops to automate it.

**Comment by kbeecher** [comment]
> Proposal: kubelet --cluster_id <cluster id>.

OK. I want to get a better impression of how this might work. Could you elaborate a little more on the kind of management commands you envision using; perhaps an excerpt from a mock CLI history where you create a couple of clusters, assign various resources among them and so on?

**Comment by lavalamp** [comment]
kubelets will be pointed at an apiserver. Apiserver is the only component that talks to etcd. Hence only apiserver needs to know its "cluster id". Really there's no need to make a "cluster id"; if you're using kubernetes in this manner, you can just pass the prefixes you like to your various apiservers (you're already customizing this setup since you're making them all talk to the same etcd cluster).

I actually think that there's no more work to do here in the codebase (except possibly a doc explaining); everything else is just setup that a sysadmin would do.

**Comment by pires** [comment]
Ah yes @lavalamp, you are right. Thank you for killing my stupid thought!

**Comment by lavalamp** [comment]
no problem ;)

**Comment by derekwaynecarr** [comment]
I think this is done.  Any issues closing this issue out?

**Comment by bgrant0607** [comment]
Done

**Comment by gitoverflow** [comment]
@bgrant0607 @derekwaynecarr 
Can I run multiple api-servers, who manage their clusters independently from the other api-servers and ensure that one a client from one api-server can't modify another cluster by prefix the etcd server?

Example: 
2 clusters, managed by 2 api-servers (both secured with tls, clients only have to certs for their api-server, so they can't access the other api-servers)
etcd-prefix cluster one: api-server-1
etcd-prefix cluster one: api-server-2

Can clients which use the endpoint of api-server-1 now in any way modify anything in cluster 2 ?

**Comment by pires** [comment]
Interesting question. I know [etcd does support permissions per key](https://coreos.com/etcd/docs/latest/auth_api.html#example-workflow) but I've never seen if/how it's implemented with the API server?

/cc @philips as I'm pretty sure he's insight on this.
