### ISSUE TITLE
Scheduling errors and OutOfCpu during cluster autoscaling

### ISSUE THREAD

**Issue by JMoellerSLB** [kubernetes/kubernetes#34772]
**Is this a request for help?**: No

**What keywords did you search in Kubernetes issues before filing this one?** OutOfCpu
Issue #29846 may be related; however, #29846 is not related to cluster autoscaling and is limited to an OutOfCpu condition.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.4.0

**Environment**: Google GKE
- **Cloud provider or hardware configuration**: Google
- **OS** (e.g. from /etc/os-release): Google Container-VM Image V55
- **Kernel** (e.g. `uname -a`): Linux gke-omega-cluster-default-pool-d07fc610-clps 4.4.14+ #1 SMP Tue Sep 20 10:32:07 PDT 2016 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
Using cluster of n1-standard-1 nodes, 1 initial node and enabled cluster autoscaling, I started 34 pods requesting 100m CPU each. Since each node has only 1 CPU and 200m CPU is required for Kubernetes services on each node (300m CPU on the first node), each node can run 8 pods (7 for the first node). All 34 pods would, therefore, required 5 nodes. The sequence of events:

Around 15:06:30: All pods are created. As expected, most pods remain in Pending state.
15:06:42: Kubernetes correctly triggers scale-up; however, the scheduler only requests a single node.
15:07:34: Two pods ("out-of-cpurf679" and "out-of-cpuwi5ge") are killed with "Deleted by rescheduler in order to schedule critical pod kube-system_heapster-v1.2.0-3455740371-j973x".
15:09:33: Scale-up is triggered again, scaling from 2 to 3 nodes.
15:11:48: Two other pods ("out-of-cpu3gsro" and "out-of-cpun30p1") fail with OutOfCpu when 10 pods are assigned to the newly added 3rd node.
15:12:31: Next scale-up, going from 3 to 4 nodes.
Eventually, 30 pods are running, 2 pods are in OutOfCpu state, and 2 pods have disappeared.
15:15:16: Another scale-up is triggered from 4 to 5 nodes. The 5th node remains idle as there are no more pods to schedule.

Please refer to this zip file for details:
[out-of-cpu-bug.zip](https://github.com/kubernetes/kubernetes/files/528186/out-of-cpu-bug.zip)

"out-of-cpu-bug.yaml" is the YAML that was used to run the experiment through the following commands:

1> gcloud container clusters create omega-cluster --machine-type=n1-standard-1 --zone us-central1-c --num-nodes 1 --enable-autoscaling --min-nodes=1 --max-nodes=8
2> bash -c 'for i in {1..34}; do kubectl create -f out-of-cpu-bug.yaml; done'

"out-of-cpu-bug-events.txt" is the capture of events from 'kubectl get events -w' up to the final scale-up. "out-of-cpu-bug-pods1.txt" shows the output of 'kubectl get nodes,pods -a' after the OutOfCpu condition of two pods. Note that only 32 pods show up, because 2 pods have been killed earlier and have "disappeared". "out-of-cpu-bug.pods2.txt" shows the nodes and pods after the final scale-up. The new node "gke-omega-cluster-default-pool-d07fc610-w79v" is unused.

**What you expected to happen**:
1. Scale-up should have been triggered to bring the cluster from 1 to 5 nodes in a single step.
2. Pods "out-of-cpurf679" and "out-of-cpuwi5ge" should not have been killed and disappeared.
3.  Pods "out-of-cpu3gsro" and "out-of-cpun30p1" should not have been scheduled onto a full node and should not have received an OutOfCpu condition.
4. Scale-up should not have produced an idle node.

**How to reproduce it** (as minimally and precisely as possible):

See above. Create a cluster on Google with
gcloud container clusters create omega-cluster --machine-type=n1-standard-1 --zone us-central1-c --num-nodes 1 --enable-autoscaling --min-nodes=1 --max-nodes=8

Schedule pods with the supplied YAML:
bash -c 'for i in {1..34}; do kubectl create -f out-of-cpu-bug.yaml; done'

The exact numbers don't matter.

**Anything else do we need to know**:

The bug(s) appear to include some race condition as the error does not always (although frequently) happen. The more pods that are being created, the more likely the situation is observed. The YAML has a commented-out section to request pod affinity. This seems to increase the likelyhood of OutOfCpu failures. Nonetheless, the above commands will show the failure with a 1 in 2 chance. Increase the number of pods to 60 or more and the problem occurs almost every time. I consider this problem a showstopper for any serious cluster autoscaling application.

**Comment by vladlosev** [comment]
Having the same problem. When this is happening, the scheduler log is full of entries like
```
I1111 20:12:36.528174       1 priorities.go:39] Combined requested resources 3250 from existing pods exceeds capacity 3200 on node prod-ore-kube-worker-i-5dc51081-private
I1111 20:12:36.528244       1 priorities.go:39] Combined requested resources 3325 from existing pods exceeds capacity 3200 on node prod-ore-kube-worker-i-9fd99f87-private
I1111 20:12:36.528293       1 priorities.go:39] Combined requested resources 3260 from existing pods exceeds capacity 3200 on node prod-ore-kube-worker-i-cb0bdb94-private
I1111 20:12:36.528336       1 priorities.go:39] Combined requested resources 3350 from existing pods exceeds capacity 3200 on node prod-ore-kube-worker-i-5bc51087-private
```
This problem is exacerbated by the fact that HPA will stop updating deployment's CPU utilization in the presence of such failed pod - that will break autoscaling and may cause an outage. This is what is showing in controller-manager's logs:
```
I1111 20:40:03.682355       1 reflector.go:288] pkg/controller/podautoscaler/horizontal.go:128: next resync planned for time.Time{sec:63614493603, nsec:682203259, loc:(*time.Location)(0x58e0140)}, forcing now
I1111 20:40:03.960631       1 horizontal.go:403] Successfully updated status for resizer
W1111 20:40:03.960710       1 horizontal.go:99] Failed to reconcile resizer: failed to compute desired number of replicas based on CPU utilization for Deployment/default/resizer: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 320/881 of pods
```
We are on Ubuntu 14.04 on AWS, m4.xlarge instances, with 20% capacity reserved.

**Comment by fgrzadkowski** [comment]
I have to admin that I couldn't reproduce this issue, but I think that the scenario is the following:

1. Kubelet registers nodes
2. Kubelet marks node as Ready
3. Scheduler assigns 10 pods
4. Kubelet registers static pods (pods coming from manifest files on disk)
5. Kubelet refuses 2 pods as they do not fit (due to pods started from manifest)

I think this is a general limitation of a distributed system where we have multiple schedulers (one can think about manifest files as sort of scheduler). We have a similar race with `DaemonSets`. Also if a user would manually assign a pod to given node.

To be honest I'm not sure how to solve this poor UX. To some extend this is working as intended. @davidopp @dchen1107 Any opinion?

**Comment by FutureSharks** [comment]
I had this same issue when trying to autoscale a node.js application while load testing. I was able to simplify the configuration to make it easy to reproduce like this:

```
$ gcloud container clusters create test-cluster-1 --num-nodes 2 --machine-type custom-4-8192
$ gcloud container clusters update test-cluster-1 --enable-autoscaling --min-nodes=2 --max-nodes=30
$ kubectl create -f app-simple.yaml
```

Where app-simple.yaml is here:
https://gist.github.com/FutureSharks/ce0d9e9b030e96689dbfc452ad2aa866

This simply creates pods that use 100% CPU. I know it's a simplistic test but Kubernetes pod and cluster node autoscaling should handle this without issues. And this config quickly and easily demonstrates the issue.

In my test this produced a few issues:
1. Many pods that are `Pending` for a long time.
2. After 20-60 mins many pods that are `OutOfCpu`.
3. Sometimes the node autoscaling wouldn't catch up and the cluster just stopped scaling, except for the pods in `OutOfCpu` state which would scale up into the 1000s.

What I would expect:
1. Don't start more pods if there is no CPU resource.
2. Don't start more pods if there is already many `Pending`.
3. Ultimately the cluster should scale nodes and pods until the limit is reached and then just stop scaling. Without any issues.

**Comment by fgrzadkowski** [comment]
@FutureSharks Thanks for your report. I'm gonna try to reproduce this again using your configuration. But I still think that the problem is with the race I have described above.

Regarding you specific issues
Ad 1 - we have already improved logic for creating new nodes more aggressively. It will be available in GKE in Dec. Hopefully it will limit this problem
Ad 2 - This needs further investigation. I'll take a look.
Ad 3 - What do you mean by "node autoscaling wouldn't catch up"? Are you saying it's just blocked? Maybe some of your nodes are not ready, and thus CA waits for them? See [this doc](https://github.com/kubernetes/contrib/blob/master/cluster-autoscaler/README.md) for more detailed explanation how CA operates.

Regarding your expectations:
Ad 1 - `OutOfCPU` means that there was a conflict on a node (i.e. scheduler assigned more than kubelet thinks there is available), so it's unrelated with creating new pods
Ad 2 - Starting more pending pods is WAI. HPA should not care about available resources as it's out of it's controler (e.g. maybe cluster autoscaler will add more nodes or user will manually scale the cluster).
Ad 3 - This goes without saying, but it's harder that it seems :)

**Comment by FutureSharks** [comment]
Regarding 'Ad 3': I mean the cluster node count reached 5 and didn't increase further even though CPU resources on each node were at maximum (in the 90%s) and more pods were still being started. I waited 20-30 mins or so it seemed stuck at 5.

FYI I also have Google Case 11383740 open.

**Comment by fgrzadkowski** [comment]
I run twice your example, and I still cannot reproduce `OutOfCPU` pods. All of the pods are either Running or Pending. Where do you see `OutOfCPU` message?

However I can reproduce easily the problem with autoscaler being blocked. I filed https://github.com/kubernetes/contrib/issues/2032 to track it. Please post additional problems there.

Can you help me with debugging `OutOfCPU` pods problem? Can you check kubelet logs for the node that refused those pods and figure out what pods were running there at that time? Does this happen only right after adding new node, or also with a stable list of nodes?

**Comment by FutureSharks** [comment]
Sure I can help.

I'm happy you can reproduce the autoscaling issue.

I ran my example again this morning. This time the `OutOfcpu` pods came much later but still. I'll write in details below...

Create the cluster:
```
$ gcloud container clusters create test-cluster-1 --num-nodes 2 --machine-type custom-4-8192; gcloud container clusters update test-cluster-1 --enable-autoscaling --min-nodes=2 --max-nodes=30
Creating cluster test-cluster-1...done.
Created [https://container.googleapis.com/v1/projects/balkan-dev01/zones/europe-west1-d/clusters/test-cluster-1].
kubeconfig entry generated for test-cluster-1.
NAME            ZONE            MASTER_VERSION  MASTER_IP        MACHINE_TYPE   NODE_VERSION  NUM_NODES  STATUS
test-cluster-1  europe-west1-d  1.4.5           146.148.124.137  custom-4-8192  1.4.5         2          RUNNING
Updating test-cluster-1...done.
Updated [https://container.googleapis.com/v1/projects/balkan-dev01/zones/europe-west1-d/clusters/test-cluster-1].
```

Create the Kubernetes deployment, HPA etc:
```
$ kubectl create -f tools/google-cloud/environments/dev02/app-simple.yaml
service "my-app" created
deployment "my-app" created
horizontalpodautoscaler "my-app" created
```

Pods are running and the HPA is getting ready:
```
$ kubectl get pods -o wide --show-all
NAME                      READY     STATUS    RESTARTS   AGE       IP         NODE
my-app-2781155866-1grx2   1/1       Running   0          32s       10.4.0.6   gke-test-cluster-1-default-pool-63668488-1axt
my-app-2781155866-i0ikv   1/1       Running   0          32s       10.4.1.6   gke-test-cluster-1-default-pool-63668488-wgn8
my-app-2781155866-imm4i   1/1       Running   0          32s       10.4.0.7   gke-test-cluster-1-default-pool-63668488-1axt
my-app-2781155866-zx7x3   1/1       Running   0          32s       10.4.1.7   gke-test-cluster-1-default-pool-63668488-wgn8
$ kubectl get hpa
NAME      REFERENCE           TARGET    CURRENT     MINPODS   MAXPODS   AGE
my-app    Deployment/my-app   40%       <waiting>   4         300       35s
```

After 5 mins or so, it starts scaling:
```
$ kubectl get hpa
NAME      REFERENCE           TARGET    CURRENT   MINPODS   MAXPODS   AGE
my-app    Deployment/my-app   40%       176%      4         300       3m
$ kubectl get pods -o wide --show-all
NAME                      READY     STATUS    RESTARTS   AGE       IP         NODE
my-app-2781155866-1grx2   1/1       Running   0          4m        10.4.0.6   gke-test-cluster-1-default-pool-63668488-1axt
my-app-2781155866-i0ikv   1/1       Running   0          4m        10.4.1.6   gke-test-cluster-1-default-pool-63668488-wgn8
my-app-2781155866-iigfs   1/1       Running   0          2m        10.4.0.9   gke-test-cluster-1-default-pool-63668488-1axt
my-app-2781155866-imm4i   1/1       Running   0          4m        10.4.0.7   gke-test-cluster-1-default-pool-63668488-1axt
my-app-2781155866-kyxpp   1/1       Running   0          2m        10.4.1.8   gke-test-cluster-1-default-pool-63668488-wgn8
my-app-2781155866-tb8am   1/1       Running   0          2m        10.4.0.8   gke-test-cluster-1-default-pool-63668488-1axt
my-app-2781155866-zciu3   1/1       Running   0          2m        10.4.1.9   gke-test-cluster-1-default-pool-63668488-wgn8
my-app-2781155866-zx7x3   1/1       Running   0          4m        10.4.1.7   gke-test-cluster-1-default-pool-63668488-wgn8
```

At 09:59:21 I had 16 pods, 2 cluster nodes and no problems. I then just let it run. At 10:14:33 I had 106 pods, 17 nodes and 3 `OutOfcpu` pods. You can see them like this:
```
$ kubectl get pods -o wide
NAME                     READY     STATUS    RESTARTS   AGE       IP           NODE
my-app-432996237-fygmf   1/1       Running   0          10m       10.4.25.9    gke-test-cluster-1-default-pool-63668488-5a4o
<..deleted text..>
my-app-432996237-q3gln   1/1       Running   0          10m       10.4.22.9    gke-test-cluster-1-default-pool-63668488-i38w
  info: 1374 completed object(s) was(were) not shown in pods list. Pass --show-all to see all objects.
$ kubectl get pods -o wide --show-all
NAME                      READY     STATUS     RESTARTS   AGE       IP          NODE
my-app-2781155866-004wq   0/1       OutOfcpu   0          7m        <none>      gke-test-cluster-1-default-pool-63668488-1e15
my-app-2781155866-00djh   0/1       OutOfcpu   0          8m        <none>      gke-test-cluster-1-default-pool-63668488-1e15
```

I left it longer until the cluster reached 30 nodes at 10:23:07. At this point there was still only 3 `OutOfcpu` pods but once the cluster node count reached the maximum this number just kept increasing by 100 every minute or so.

I then updated the deployment to remove the load by changing the command args to `sleep 999999`. The `OutOfcpu` pods don't really disappear, here there are 1374 of them:
```
$ kubectl get pods -o wide
NAME                     READY     STATUS    RESTARTS   AGE       IP           NODE
my-app-432996237-fygmf   1/1       Running   0          10m       10.4.25.9    gke-test-cluster-1-default-pool-63668488-5a4o
my-app-432996237-goblb   1/1       Running   0          10m       10.4.29.10   gke-test-cluster-1-default-pool-63668488-ybdu
my-app-432996237-i3y4i   1/1       Running   0          10m       10.4.29.9    gke-test-cluster-1-default-pool-63668488-ybdu
my-app-432996237-q3gln   1/1       Running   0          10m       10.4.22.9    gke-test-cluster-1-default-pool-63668488-i38w
  info: 1374 completed object(s) was(were) not shown in pods list. Pass --show-all to see all objects.
$ kubectl describe pods my-app-2781155866-004wq
Name:		my-app-2781155866-004wq
Namespace:	default
Node:		gke-test-cluster-1-default-pool-63668488-1e15/
Start Time:	Wed, 16 Nov 2016 10:31:13 +0100
Labels:		name=my-app
		pod-template-hash=2781155866
Status:		Failed
Reason:		OutOfcpu
Message:	Pod
IP:
Controllers:	ReplicaSet/my-app-2781155866
Containers:
  my-app:
    Image:	ubuntu:16.04
    Port:	8000/TCP
    Command:
      /bin/bash
      -c
    Args:
      apt update; apt install stress; stress --cpu 1 --io 1 & sleep 999999
    Requests:
      cpu:	550m
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-4fjt7 (ro)
    Environment Variables:	<none>
Volumes:
  default-token-4fjt7:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-4fjt7
QoS Class:	Burstable
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From							SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----							-------------	--------	------		-------
  7m		7m		1	{kubelet gke-test-cluster-1-default-pool-63668488-1e15}			Warning		OutOfcpu
  7m		7m		1	{default-scheduler }							Normal		Scheduled	Successfully assigned my-app-2781155866-004wq to gke-test-cluster-1-default-pool-63668488-1e15
```

**Comment by FutureSharks** [comment]
> Can you check kubelet logs for the node that refused those pods and figure out what pods were running there at that time?

I have the output of this run on a node. Is that what you mean?
`gke-test-cluster-1-default-pool-63668488-wgn8 ~ # journalctl | grep kubelet`

> Does this happen only right after adding new node, or also with a stable list of nodes?

I can't really see a consistent pattern as to when it happens. In the example I posted above the `OutOfcpu` pods didn't happen until the cluster node count reached 17 but previously I had seen it as early as 5 nodes. Also there are periods of time during node scaling where the cluster is not accessible. e.g:

```
$ kubectl get pods -o wide
Error from server: an error on the server ("Internal Server Error: \"/apis\"") has prevented the request from succeeding
$ kubectl get pods -o wide
an error on the server ("Internal Server Error: \"/api/v1/namespaces/default/pods\"") has prevented the request from succeeding (get pods)
```

I'm happy to provide more debug or logs but you  will need to be specific about exactly what you want.

**Comment by FutureSharks** [comment]
I just ran it again this time I had `OutOfcpu` pods much quicker. Here is events from the pod:
```
$ kubectl describe pods my-app-2781155866-uy47l
Name:		my-app-2781155866-uy47l
Namespace:	default
Node:		gke-test-cluster-1-default-pool-63668488-cjm5/
Start Time:	Wed, 16 Nov 2016 11:54:09 +0100
Labels:		name=my-app
		pod-template-hash=2781155866
Status:		Failed
Reason:		OutOfcpu
Message:	Pod
IP:
Controllers:	ReplicaSet/my-app-2781155866
Containers:
  my-app:
    Image:	ubuntu:16.04
    Port:	8000/TCP
    Command:
      /bin/bash
      -c
    Args:
      apt update; apt install stress; stress --cpu 1 --io 1 & sleep 999999
    Requests:
      cpu:	550m
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-4fjt7 (ro)
    Environment Variables:	<none>
Volumes:
  default-token-4fjt7:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-4fjt7
QoS Class:	Burstable
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  23m		23m		2	{default-scheduler }			Warning		FailedScheduling	pod (my-app-2781155866-uy47l) failed to fit in any node
fit failure on node (gke-test-cluster-1-default-pool-63668488-1axt): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-63668488-wgn8): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-63668488-rm25): Insufficient cpu

  23m	23m	1	{cluster-autoscaler }		Normal	TriggeredScaleUp	pod triggered scale-up, group: https://content.googleapis.com/compute/v1/projects/balkan-dev01/zones/europe-west1-d/instanceGroups/gke-test-cluster-1-default-pool-63668488-grp, sizes (current/new): 3/5
  23m	23m	1	{default-scheduler }		Warning	FailedScheduling	pod (my-app-2781155866-uy47l) failed to fit in any node
fit failure on node (gke-test-cluster-1-default-pool-63668488-wgn8): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-63668488-1axt): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-63668488-rm25): Insufficient cpu

  23m	23m	4	{default-scheduler }		Warning	FailedScheduling	pod (my-app-2781155866-uy47l) failed to fit in any node
fit failure on node (gke-test-cluster-1-default-pool-63668488-1axt): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-63668488-rm25): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-63668488-wgn8): Insufficient cpu

  22m	22m	1	{default-scheduler }		Warning	FailedScheduling	pod (my-app-2781155866-uy47l) failed to fit in any node
fit failure on node (gke-test-cluster-1-default-pool-63668488-rm25): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-63668488-wgn8): Insufficient cpu
fit failure on node (gke-test-cluster-1-default-pool-63668488-1axt): Insufficient cpu

  22m	22m	1	{default-scheduler }						Normal	Scheduled	Successfully assigned my-app-2781155866-uy47l to gke-test-cluster-1-default-pool-63668488-cjm5
  22m	22m	1	{kubelet gke-test-cluster-1-default-pool-63668488-cjm5}		Warning	OutOfcpu
```

And from the cluster node:
```
gke-test-cluster-1-default-pool-63668488-cjm5 ~ # journalctl | grep my-app-2781155866-uy47l
Nov 16 10:54:09 gke-test-cluster-1-default-pool-63668488-cjm5 kubelet[1320]: I1116 10:54:09.809757    1320 kubelet.go:2293] SyncLoop (ADD, "api"): "my-app-2781155866-uy47l_default(c30ef4af-abea-11e6-918f-42010af0013f)"
Nov 16 10:54:09 gke-test-cluster-1-default-pool-63668488-cjm5 kubelet[1320]: I1116 10:54:09.809796    1320 kubelet.go:2198] Predicate failed on Pod: my-app-2781155866-uy47l_default(c30ef4af-abea-11e6-918f-42010af0013f), for reason: Node didn't have enough resource: cpu, requested: 550, used: 3480, capacity: 4000
```

**Comment by JMoellerSLB** [comment]
@fgrzadkowski: Thanks for looking into the problem. It's clear now that others run into the same issue. I don't know the Kubernetes code base, so I can only guess how things work. You mention a manifest. I assume that it contains information about the Kubernetes services that execute on each node. I also guess that the scheduler looks at the current state of a node to decide whether to schedule on that node. Before Kubernetes services from the manifest are running, that state of the node shows availability of resources that exceeds the actual resources on the node once the Kubernetes service will be running. Since kubectl starts Kubernetes services in parallel with the scheduler doing its scheduling, you have the race that I was hinting at.

I understand that the scheduler does not know about the manifest. There is probably a good architectural reason for that decision. It would appear, however, that a node is not fully functional without the Kubernetes services running from the manifest. (For instance, kube-dns might be critical for some user pod to function.) Would it be possible to keep the node in NotReady state long enough until the kubelet reports that the services are running? Again, I don't know the code base and may be completely off, but on the surface of it, this sounds like a consistent and relatively simple solution to beat the race.

I am not as lucky as most other Kubernetes users that are going to run into this problem. Most applications are web services that use an HPA. Fixing the HPA bug may alleviate the problem for them as the HPA would create new pods to replace those OutOfcpu pods. (Incidentally, wrong CamelCase reported by Kubernetes; pod failure "reason" is also incomplete.) I am trying to run HPC MPI in Kubernetes. If a MPI child process dies, it's game over. I actually developed a work-around for OutOfcpu pods by deleting and recreating them. This is possible as these pods never really started and have never been made known to the MPI layer. Some pods, however, are never reported as OutOfcpu and I have no work-around for this. Two pods ("out-of-cpurf679", "out-of-cpuwi5ge") in my originally attached event log file are deleted from the system without a trace. These pods were started before one of the Kubernetes services from the manifest (heapster in this case). kubelet then deleted and killed the running pods to make room for the heapster pod. You can think of it as the heapster pod getting the OutOfcpu because it got started after the node was out of resources from already running user pods:

    2016-10-13T15:07:34-05:00   2016-10-13T15:07:34-05:00   1         out-of-cpurf679   Pod                 Normal    DeletedByRescheduler   {rescheduler }   Deleted by rescheduler in order to schedule critical pod kube-system_heapster-v1.2.0-3455740371-j973x.
    2016-10-13T15:07:34-05:00   2016-10-13T15:07:34-05:00   1         out-of-cpuwi5ge   Pod                 Normal    DeletedByRescheduler   {rescheduler }   Deleted by rescheduler in order to schedule critical pod kube-system_heapster-v1.2.0-3455740371-j973x.
    [...]
    2016-10-13T15:07:44-05:00   2016-10-13T15:07:44-05:00   1         out-of-cpurf679   Pod       spec.containers{sleeper}   Normal    Killing   {kubelet gke-omega-cluster-default-pool-d07fc610-clps}   Killing container with docker id d28c3342a685: Need to kill pod.
    2016-10-13T15:07:44-05:00   2016-10-13T15:07:44-05:00   1         out-of-cpuwi5ge   Pod       spec.containers{sleeper}   Normal    Killing   {kubelet gke-omega-cluster-default-pool-d07fc610-clps}   Killing container with docker id a6e1a12ac5d9: Need to kill pod.

As these pods are actually deleted, they do not show up when listing pods in kubectl. They also cannot be "described" anymore. They are simply gone. This again kills my MPI computation.

**Comment by fgrzadkowski** [comment]
@gmarek @wojtek-t

**Comment by wojtek-t** [comment]
@davidopp  - it seems that we are able to reproduce this problem in kubemark, where we don't have any mirror pods etc. So seems like a problem with scheduler...

**Comment by wojtek-t** [comment]
As an update - the probelm with kubemark is scalability issue, which we can only reproduce in very large setups. And this is unrelated to this one.

**Comment by akhlopotine** [comment]
@wojtek-t - any ETA for the fix?

**Comment by akhlopotine** [comment]
@wojtek-t - Thank you for looking into this one. Any ETA for the fix?

**Comment by wojtek-t** [comment]
@akhlopotine - I'm not looking into it. @mwielgus - is this already fixed or something needs to be done here?

**Comment by akhlopotine** [comment]
I still see this issue. So it is not fixed

**Comment by akhlopotine** [comment]
@wojtek-t @mwielgus i continue experiencing this issue with submitted jobs as well. jobs shall be restarted until they successfully finish. i use 1.4.8 but i can try 1.5.2 if you think this is solved there

**Comment by mwielgus** [comment]
We checked and the fix for OutOfCpu should be included in 1.4.8. Could you please confirm that this is the exactly same issue as previously and you upgraded both master and nodes?

**Comment by JMoellerSLB** [comment]
@mwielgus Thanks for looking into this. I retested on 1.4.8 just like @akhlopotine and the behavior is unchanged, that is, the bug remains open. I reran the test exactly as explained in my original bug report, except that I selected pod affinity as explained. Again, node affinity makes the problem occur more frequently and is therefore recommended to reproduce the problem, but it is otherwise unrelated to the bug. (The yaml in the original attachment contains the affinity spec in a comment; it can be commented in for this purpose.) I created 324 pods. Out of these pods, 124 ended in OutOfcpu state; at least 14 were killed and completely deleted from the system. (They don't show any state as they are lost from the system.) Event messages are identical to the original attachment.

**Comment by FutureSharks** [comment]
I also retested on 1.4.8 using the method I mentioned in previous comments and I still see some OutOfcpu pods.

**Comment by gmarek** [comment]
I believe we fixed that.
/close

**Comment by thkoch2001** [comment]
In case you come here: The scheduler was completely rewritten since 1.4. So even if there is a similar looking issue, it can't be the same.
