### ISSUE TITLE
kubectl drain should wait for pods to be finally deleted

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#34782]
This is for all pods, not just petset pods.

When a pod is deleted by kubectl drain, it goes into DELETING.  Kubectl drain should not return success to the user until the pod is completely deleted.  That way, if the user is scripting automation, and they say something like `kubectl drain $MACHINE && ssh root@$MACHINE shutdown -r now`, that it does not shutdown before the pods are expecting it.  Right now I think it does not wait.

Waiting could mean:

1) remember the uid of the thing you are going to delete,
2) DELETE it
3) poll it until either: you get 404 (it is finally deleted) or you get 200 but the new pod has a different uid (a replacement came quickly).

**Comment by erictune** [comment]
@ymqytw @foxish @kow3ns we discussed this today.
@pwittrock we discussed this the other day.

**Comment by pwittrock** [comment]
It should also respect disruption budgets

**Comment by davidopp** [comment]
I completely agree with @erictune's suggestion; we should have done it that way from the beginning.

As for respecting disruption budgets: agree with that one too, and @maisem offered to do it soon-ish.

**Comment by maisem** [comment]
cc @bdbauer - we were discussing this yesterday for GKE.

**Comment by davidopp** [comment]
@bdbauer / @maisem if you have time to do both of the things mentioned in this issue (I know you were originally only planning to do the second one), that would be great.

**Comment by maisem** [comment]
@davidopp IIUC #34778 would fix this issue, while we tackle #34277/

**Comment by davidopp** [comment]
Oh yeah, sorry, I somehow missed #34778. Yes, I agree it addresses the first issue.

**Comment by pwittrock** [comment]
While you are working on drain issues

**Comment by davidopp** [comment]
recording for posterity: the reason we don't need to wait for pods to reschedule before moving on to the next node when draining, is that the disruption budget itself will prevent evicting more pods from until the ones from the drained node have rescheduled and are ready (if such evictions would be unsafe).

**Comment by davidopp** [comment]
(but the thing described in the first entry in this issue, and implemented in #34778, is necessary, because otherwise it's not safe to shut down the machine / remove the VM, since the containers may be in their graceful termination period)

**Comment by pavels** [comment]
Can this be backported into 1.4? It's hard to do clean machine shutdown without this.

**Comment by davidopp** [comment]
I marked the PR for cherrypick into the next 1.4. It's a pretty small change but I can't guarantee it will be accepted.
