### ISSUE TITLE
Need to implement reaper for PersistentVolume and PersistentVolumeClaims.

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#34790]
From #34513.

Experimenting the new feature `kubectl apply --prune`, found it unable to prune resource type `PersistentVolume` and `PersistentVolumeClaims`. Error as below:
```
$ kubectl apply -f pv-test.yaml --prune -l test="true"
...
error: error pruning objects: no reaper has been implemented for { PersistentVolume}
error: error pruning objects: no reaper has been implemented for { PersistentVolumeClaim}
```

We will need this for upgrading Addon Manager. It's weird that these resource types are not included. Or am I missing something?

@mikedanese @ymqytw

**Comment by MrHohn** [comment]
@saad-ali  Or would it be too dangerous to delete PV and PVC by apply --prune?

**Comment by mikedanese** [comment]
Hmm, maybe I made an incorrect assumption about ReaperFor. Good catch.
