### ISSUE TITLE
GenericAPIServer improvments

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#34839]
I'm building this list based on actual attempts to make use of the genericapiserver
- [x] serializer should be set by default
- [x] version is messed up.  I need to be able to pass values through https://github.com/kubernetes/kubernetes/pull/34967
- [x] authentication setup: it should be really easy to set up: anonymous, clientCA (same as master), master webhook https://github.com/kubernetes/kubernetes/pull/36604
- [x] authorization setup: it should be really easy to set up delegation to master https://github.com/kubernetes/kubernetes/pull/36604

@sttts @ncdc @liggitt

**Comment by sttts** [comment]
Overlapping with https://github.com/kubernetes/kubernetes/issues/32792

**Comment by bgrant0607** [comment]
@deads2k Is there a reason why you didn't set routing labels on this issue?

**Comment by deads2k** [comment]
> @deads2k Is there a reason why you didn't set routing labels on this issue?

No reason.  I just assigned myself and didn't think about the labels.

**Comment by sttts** [comment]
All merged. Closing.
