### ISSUE TITLE
Break up pkg/util some

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#3486]
Example: move types to pkg/types or pkg/flagtypes or something.

**Comment by bgrant0607** [comment]
Move which types?

Related: #4851

**Comment by thockin** [comment]
I think this is low prio overall, except in the context of findability overall.  Basically, most or all of pkg/util should become pkgs and ~nothing should be left in util itself.

**Comment by bgrant0607** [comment]
I don't want a flat sea of dozens of directories.

**Comment by thockin** [comment]
It doesn't have to be flat.  E.g. ...something.../util/flagwrap vs just
having flag wrappers in ...util/ directly.
