### ISSUE TITLE
Load balancer controller doesn't wait for caches to fill

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#34866]
Seen in logs after a controller-manager restart:

```
I1014 20:24:41.940021       7 servicecontroller.go:285] Ensuring LB for service xxxxxx
E1014 20:24:41.940105       7 servicecontroller.go:755] Failed to process service. Retrying in 10s: Failed to create load balancer for service xxxxxx: Cannot EnsureLoadBalancer() with no hosts
I1014 20:24:42.115014       7 servicecontroller.go:285] Ensuring LB for service yyyyy
E1014 20:24:42.115115       7 servicecontroller.go:755] Failed to process service. Retrying in 10s: Failed to create load balancer for service yyyyy: Cannot EnsureLoadBalancer() with no hosts
```

I think this means that the only thing keeping it from blowing away working load balancers is the fact that it managed to check before it loaded any services, as opposed to before it had loaded all services.

**Comment by justinsb** [comment]
See also #34267 ... I am not sure that we always get lucky.

**Comment by cmluciano** [comment]
/sig-remove network

/sig aws

linked issue is for sig/aws, rerouting for now

**Comment by justinsb** [comment]
/sig network

Network owns the servicecontroller, IIUC
