### ISSUE TITLE
kubectl not using all of the yaml documents in some cases

### ISSUE THREAD

**Issue by Buzer** [kubernetes/kubernetes#34886]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): daemonset, kubectl

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.2", GitCommit:"c072cc2ee4dfc21b60196e5994c56c40e1c29b93", GitTreeState:"clean", BuildDate:"2016-10-15T00:13:29Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

Also tested with:

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:19:49Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment (server)**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Debian Jessie
- **Kernel** (e.g. `uname -a`): Linux ip-10-64-61-28 4.4.23-k8s #1 SMP Fri Sep 30 13:51:02 UTC 2016 x86_64 GNU/Linux
- **Install tools**: kops with https://github.com/kubernetes/kops/pull/621 applied

**Environment (client)**:
- **OS** (e.g. from /etc/os-release): Arch Linux
- **Kernel** (e.g. `uname -a`): Linux *****\* 4.7.0-1-ARCH #1 SMP PREEMPT Mon Aug 8 22:05:58 CEST 2016 x86_64 GNU/Linux

**What happened**:
When applying Calico's deployment YAML file, the daemonset isn't sent to the server

```
$ kubectl apply -f  https://raw.githubusercontent.com/projectcalico/calico/master/master/getting-started/kubernetes/installation/hosted/calico.yaml
configmap "calico-config" configured
secret "calico-etcd-secrets" configured
replicaset "calico-policy-controller" configured
```

However, when extracting the daemonset config to separate file, apply works properly:

```
$ cat daemonset.yaml
# This manifest installs the calico/node container, as well
# as the Calico CNI plugins and network config on
# each master and worker node in a Kubernetes cluster.
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
 name: calico-node
...
$ kubectl apply -f daemonset.yaml
daemonset "calico-node" configured
```

**What you expected to happen**:
All 4 documents in the YAML file should be applied

**How to reproduce it** (as minimally and precisely as possible):
Unfortunately I haven't managed to create smaller test case than the original calico.yaml.

```
$ kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/e49b8fd9d349b0465a261633f5f4788618d36301/master/getting-started/kubernetes/installation/hosted/calico.yaml
```

**Comment by AdoHe** [comment]
@Buzer I will take a look, seems like the yaml decoder issue.

**Comment by k82cn** [comment]
@AdoHe , I'd like to try it; would you help me?

**Comment by Buzer** [comment]
Document was fixed in upstream with https://github.com/projectcalico/calico/pull/97

The issue was apparently that the "---" was followed by a space. YAML standard doesn't seem to be completely explicit if this is okay or not.

**Comment by AdoHe** [comment]
@Buzer actually this is a regression bug of 1.4, you can refer #33588 for more detail. I will test the old calico document with the master branch.

**Comment by AdoHe** [comment]
```
The issue was apparently that the "---" was followed by a space. YAML standard doesn't seem to be completely explicit if this is okay or not.
```
YAML standard doesn't restrict this, this should be allowed. I test `calico.yaml` with master branch,  `---` followed by space can be parsed, maybe we need to create a cherry-pick PR. @Buzer

**Comment by Buzer** [comment]
Thanks for respopnse. Yeah, cherry-pick PR would be appricated as it can be pretty easy to trigger this and not that easy to spot the problem.

**Comment by etiennetremel** [comment]
@AdoHe Nice catch! We had the exact same issue and spent quite some time trying to find where was the problem. Thanks

**Comment by AdoHe** [comment]
@etiennetremel you are welcome. Btw what's your kubernetes version?

**Comment by etiennetremel** [comment]
@AdoHe we are using v1.4.4
