### ISSUE TITLE
No generated endpoints, is none

### ISSUE THREAD

**Issue by BoriszhangSec** [kubernetes/kubernetes#34883]
i deploy heapster,all pod running,but no work for me

kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0+a16c0a7", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"not a git tree", BuildDate:"2016-09-27T09:17:08Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0+a16c0a7", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"not a git tree", BuildDate:"2016-09-27T09:17:08Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

kubectl get pods -o wide --namespace=kube-system
NAME                                      READY     STATUS    RESTARTS   AGE       IP           NODE
heapster-v1.2.0-beta.1-1428998303-kown7   4/4       Running   0          1h        172.1.28.9   192.168.1.151
kube-dns-v19-09yfk                        3/3       Running   0          1d        172.1.41.5   192.168.1.152
kubernetes-dashboard-1694592692-5khui     1/1       Running   1          1d        172.1.28.4   192.168.1.151
monitoring-influxdb-grafana-v3-kld1u      2/2       Running   0          1h        172.1.88.7   192.168.1.153

I saw the endpoints is none
kubectl get ep -o wide --namespace=kube-system
NAME                   ENDPOINTS                                 AGE
heapster               <none>                                    1h
kube-dns               192.168.1.152:31009,192.168.1.152:31008   3d
kubernetes-dashboard   192.168.1.151:31002                       2d
monitoring-grafana     <none>                                    1h
monitoring-influxdb    192.168.1.153:31006,192.168.1.153:31007   1h

I have to check, found iptables not generate any rules about the pod
iptables -S -t nat | grep 172.1.28.9  (192.168.1.151)

influxdb can access,can also be rules 
iptables -S -t nat | grep 172.1.88.7
-A POSTROUTING -s 172.1.88.7/32 -d 172.1.88.7/32 -p tcp -m tcp --dport 8086 -j MASQUERADE
-A POSTROUTING -s 172.1.88.7/32 -d 172.1.88.7/32 -p tcp -m tcp --dport 8083 -j MASQUERADE
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 31007 -j DNAT --to-destination 172.1.88.7:8086
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 31006 -j DNAT --to-destination 172.1.88.7:8083

This is where the problem, thank you

**Comment by BoriszhangSec** [comment]
BTW,excutor kubectl cluster-info 
==== START logs for kube-system/heapster-v1.2.0-beta.1-1428998303-kown7 ====
Error from server: the server rejected our request for an unknown reason (get pods heapster-v1.2.0-beta.1-1428998303-kown7)

**Comment by MrHohn** [comment]
How did you delpoy the `heapster`? Could you also show the output of `kubectl get deployment  --namespace=kube-system`?

And for the output of `kubectl get pods -o wide --namespace=kube-system`, did you just paste partial of it? I wonder what were the statuses of `kube-proxy`s.

**Comment by BoriszhangSec** [comment]
@MrHohn thanks for reply
i deploy k8s on mesos
proxy status: all node proxy is running
ps -ef | grep 'km proxy'
root     13586 10556  0 15:11 pts/2    00:00:00 grep --color=auto km proxy
root     25396 25367  0 10月13 ?      00:51:29 /var/lib/mesos/slaves/a3ab587e-eeea-4c9e-a252-3e9163694aa5-S3/frameworks/a3ab587e-eeea-4c9e-a252-3e9163694aa5-0000/executors/4d0d8c7d2142cd35_k8sm-executor/runs/98a4cb13-f65e-47a0-b823-db9f0eb24984/km proxy --bind-address=0.0.0.0 --v=0 --logtostderr=true --resource-container= --proxy-mode=userspace --conntrack-max=0 --conntrack-tcp-timeout-established=0 --master=192.168.1.151:8080 --hostname-override=192.168.1.151


![image](https://cloud.githubusercontent.com/assets/14834177/19428508/2f47f364-947d-11e6-84f2-69ef7a7b2776.png)
