### ISSUE TITLE
Remove cluster/ubuntu in favor for kubeadm

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#34909]
WDYT? @mikedanese @MikeSpreitzer 

The code there is really old and hasn't been touched for real since ~June this year...

Can we do this for v1.5?

cc @kubernetes/sig-cluster-lifecycle

**Comment by roberthbailey** [comment]
We should start looking at removing a lot of the "code" under `/cluster`. But given that kubeadm doesn't handle provisioning, I'm not convinced that we can remove it all (unless it finds a new home in a different repo).

**Comment by MikeSpreitzer** [comment]
I thought the point of kubeadm was to make `/cluster` obsolete.  I support that.  But kubeadm is still in alpha and `/cluster` is not dead yet.  I have a PR in progress for `/cluster/ubuntu` right now.  Let's not jump the gun.  In general, for the sake of users, there should be a transition period during which both the new and the old work and are supported.

**Comment by MikeSpreitzer** [comment]
It is also true that I have not had time to follow the cluster-lifecycle work closely.  Is it intended that kubeadm not address provisioning?  What is the vision for how that would be done, in the glorious future?

**Comment by pires** [comment]
Related question, is there such a thing as a Provision API?

**Comment by mikedanese** [comment]
kubeadm is not meant to replace cluster/. kubeadm has a much smaller scope than the tooling in cluster.

> Related question, is there such a thing as a Provision API?

Tools like terraform/deployment manager/cloudformation tackle this. Is out of scope of k8s to solve this generally but some specific examples would be good. kubernetes-anywhere [phase1s](https://github.com/kubernetes/kubernetes-anywhere/tree/master/phase1) are examples of simple provisioning using terraform. The provisioning phase should always call kubeadm, not the other way around. Kubeadm should be agnostic and have zero knowledge of  how the machine it is running on was provisioning.

I don't think we can start deleting things until we've deprecated them for a while.
