### ISSUE TITLE
Where can we configure the parameters for kubelet of kubeadm?

### ISSUE THREAD

**Issue by Johnzinvalid** [kubernetes/kubernetes#34915]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kubeadm kubelet

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):

```
[root@192 lib]# kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Cloud provider or hardware configuration**: VMs 
- **OS** (e.g. from /etc/os-release): CentOS 7
- **Kernel** (e.g. `uname -a`): Linux 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubeadm init
- **Others**:

**What happened**:
ps aux | grep kubelet shows following:
```
root       9796  2.7  0.9 1089780 75944 ?       Ssl  10月13 147:04 /usr/bin/kubelet --kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=100.64.0.10 --cluster-domain=cluster.local --v=4
```
Where can we configure the parameters for kubelet?
I have checked the source code of kubeadm but cannot find the correct place to change the configuration if kubelet.

**What you expected to happen**:
Specify the right place of customizing kubelet.

**How to reproduce it** (as minimally and precisely as possible):
No need to reproduce

@kubernetes/sig-cluster-lifecycle

**Comment by Johnzinvalid** [comment]
@kubernetes/sig-cluster-lifecycle

**Comment by luxas** [comment]
Just edit `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf`

@kubernetes/sig-cluster-lifecycle

**Comment by thassan** [comment]
on Debian it is /etc/sysconfig/kubelet
