### ISSUE TITLE
federation/deploy/deploy.sh create_federation does not create needed secrets

### ISSUE THREAD

**Issue by IanLewis** [kubernetes/kubernetes#34919]
I created a cluster (1.4.3) on GCE using kube-up.sh and then followed instructions on deploying the federation control plane -> http://kubernetes.io/docs/admin/federation/

After running deploy.sh deploy_federation the `federation-apiserver-credentials` and `federation-controller-manager-kubeconfig` secrets are not created in the `federation` namespace. The API server and controller do not start with the following errors:

> 2016-10-17 05:30:40 +0000 UTC   2016-10-17 05:30:24 +0000 UTC   6         federation-apiserver-3093677159-wpcs0            Pod                      Warning   FailedMount            {kubelet kubernetes-minion-group-svel}   MountVolume.SetUp failed for volume "kubernetes.io/secret/c9997bfd-942a-11e6-a0cc-42010af00007-federation-apiserver-credentials" (spec.Name: "federation-apiserver-credentials") pod "c9997bfd-942a-11e6-a0cc-42010af00007" (UID: "c9997bfd-942a-11e6-a0cc-42010af00007") with: secrets "federation-apiserver-credentials" not found
> 
> 2016-10-17 05:30:49 +0000 UTC   2016-10-17 05:30:17 +0000 UTC   7         federation-controller-manager-3046679825-ce3o2   Pod                   Warning   FailedMount   {kubelet kubernetes-minion-group-svel}   MountVolume.SetUp failed for volume "kubernetes.io/secret/c99c21c1-942a-11e6-a0cc-42010af00007-kubeconfig" (spec.Name: "kubeconfig") pod "c99c21c1-942a-11e6-a0cc-42010af00007" (UID: "c99c21c1-942a-11e6-a0cc-42010af00007") with: secrets "federation-controller-manager-kubeconfig" not found

**Comment by IanLewis** [comment]
@madhusudancs

**Comment by bviolier** [comment]
I am running into the same issue. Any known fix for this?

**Comment by nikhiljindal** [comment]
A workaroud will be to create the secrets yourself. Credentials for federation-apiserver should be in your kubeconfig with the context `federation-cluster`. You can extract that into a file using: 
```
kubectl config use-context federation-cluster // This will change your current context. You can change it back again using the same command.
kubectl config view --minify --flatten > federation-apiserver-kubeconfig
```

You can then create a secret by running:
```
kubectl create secret generic secretName --namespace=federation --from-file=federation-apiserver-kubeconfig
```

If you run into other problems, feel free to post them here. If you are really blocked, you can try the previous mechanism detailed in http://kubernetes.io/docs/admin/federation/#previous-federation-turn-up-mechanism.

fwiw, we are also writting a new tool to make it easier to turn up federation control plane. If you are on HEAD, you can try that out as well (caveat: its still in active development). Would love feedback on it. https://github.com/kubernetes/kubernetes/pull/34484 has more details on it.

cc @kubernetes/sig-cluster-federation

**Comment by nalink** [comment]
i see same issue, and i tried the steps as stated by @nikhiljindal 
"➜  kubernetes git:(master) ✗ ./cluster/kubectl.sh create secret generic hello123 --namespace=federation --from-file=federation-apiserver-kubeconfig
Unable to connect to the server: net/http: TLS handshake timeout"
looks like, it is unable to connect to AWS instances

**Comment by nalink** [comment]
Also, i tried old approach to bring the cluster: (http://kubernetes.io/docs/admin/federation/#previous-federation-turn-up-mechanism)
but, it deployments say same credential error:
#1 federation-apiserver - 
a. SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "federation-apiserver-etcd-claim", which is unexpected.
b. with: secrets "federation-apiserver-credentials" not found

#2 federation-controller-manager
a. secrets "federation-controller-manager-kubeconfig" not found

Please let me know if i am missing something.

**Comment by nikhiljindal** [comment]
Sorry for the delay in response.
@nalink What version are you using? release-1.4 or HEAD or 1.5-beta? Are you on GCE or AWS?


For anyone else following this who is trying on HEAD or 1.5-beta, we now have documentation for using kubefed: https://github.com/kubernetes/kubernetes.github.io/blob/release-1.5/docs/admin/federation/kubefed.md. Its alpha but it is going to be the primary tool to deploy federation control plane going forward. Give it a try and feel free to file issues.

**Comment by OlivierBoucher** [comment]
Getting the same issues with release-1.4.6.

Missing secrets
- federation-apiserver-credentials
- federation-controller-manager-kubeconfig

Anything I can do?

**Comment by nalink** [comment]
@nikhiljindal - sorry i missed the above post. i am using master branch - and i am able to bring the cluster up using federation-up.sh and i had build qick-release. And for AWS - there is small code change in loadbalancer code in common.sh ip,hostname (remove ip). I will try kubefed for sure. 
@OlivierBoucher - yes there are problems in 1.4.6 code - because i was unable to launch fed-k8-cluster using federation-up.sh as well. And docker images used in deploy federation seems to be broken for many things. Secrets for sure.

**Comment by madhusudancs** [comment]
@OlivierBoucher will you be able to use v1.5.1+? You don't have to upgrade your clusters for this, just the federation part. If that's possible, I recommend using `kubefed` - http://kubernetes.io/docs/admin/federation/kubefed/

**Comment by OlivierBoucher** [comment]
I tried using kubefed + k8s 1.4.6 (Latest available on GCE) and got errors saying my version was not supported when trying to add a cluster to the federation... Note that creating the federation api server and manager worked.

I managed to get something working using @kelseyhightower labs.

**Comment by madhusudancs** [comment]
> I tried using kubefed + k8s 1.4.6 (Latest available on GCE) and got errors saying my version was not supported when trying to add a cluster to the federation...

Could you please share the exact error messages? Or file an issue for it?

**Comment by tk3fftk** [comment]
I have same issues on OpenStack with k8s v1.5.1 and deploy.sh.
Can I use federation on OpenStack?

My error message is:
> MountVolume.SetUp failed for volume "kubernetes.io/secret/fd52910c-c73f-11e6-8107-fa163eddd1cc-federation-apiserver-credentials" (spec.Name: "federation-apiserver-credentials") pod "fd52910c-c73f-11e6-8107-fa163eddd1cc" (UID: "fd52910c-c73f-11e6-8107-fa163eddd1cc") with: secrets "federation-apiserver-credentials" not found

> MountVolume.SetUp failed for volume "kubernetes.io/secret/fd511aca-c73f-11e6-8107-fa163eddd1cc-kubeconfig" (spec.Name: "kubeconfig") pod "fd511aca-c73f-11e6-8107-fa163eddd1cc" (UID: "fd511aca-c73f-11e6-8107-fa163eddd1cc") with: secrets "federation-controller-manager-kubeconfig" not found

I have another error of Persistent Volume.
The federation-apiserver-etcd-claim state is bound.
My nfs is working with CLI, but k8s fail to mount nfs volume.

> MountVolume.SetUp failed for volume "kubernetes.io/nfs/fd52910c-c73f-11e6-8107-fa163eddd1cc-pv0003" (spec.Name: "pv0003") pod "fd52910c-c73f-11e6-8107-fa163eddd1cc" (UID: "fd52910c-c73f-11e6-8107-fa163eddd1cc") with: mount failed: exit status 32 Mounting command: mount Mounting arguments: 172.21.152.179:/exports/data /var/lib/kubelet/pods/fd52910c-c73f-11e6-8107-fa163eddd1cc/volumes/kubernetes.io~nfs/pv0003 nfs [] Output: mount: wrong fs type, bad option, bad superblock on 172.21.152.179:/exports/data, missing codepage or helper program, or other error (for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program) In some cases useful info is found in syslog - try dmesg | tail or so.

**Comment by quinton-hoole** [comment]
Closing old bugs.  kubefed resolves this.
