### ISSUE TITLE
Does this make code better

### ISSUE THREAD

**Issue by hhzguo** [kubernetes/kubernetes#34916]
This is not a bug nor a feature request, but code improvement.

In pkg/controller/informers/core.go

Can we change the code to the following? 
func (f *namespaceInformer) Informer() cache.SharedIndexInformer {
    informerType := reflect.TypeOf(&api.Namespace{})
    informer, exists := f.informers[informerType]
    if exists {
        return informer
    } else {
        f.lock.Lock()
        defer f.lock.Unlock()
        informer, exists := f.informers[informerType]
        if !exists {
            informer = NewNamespaceInformer(f.client, f.defaultResync)
            f.informers[informerType] = informer
        }
        return informer
    }
}
I am new comer to kubernetes and am studying the code. Sorry if I understood wrongly. 

Henry

**Comment by smarterclayton** [comment]
Please reopen as a PR - this got lost in the shuffle.
