### ISSUE TITLE
Get host ip via environment variable inside Kubernetes containers

### ISSUE THREAD

**Issue by andyxning** [kubernetes/kubernetes#34923]
In pure docker environment, we can run ```docker run --env HOST_IP=`hostname -i` nginx /bin/bash``` to pass the host ip as `HOST_IP` environment variable into container. This is because this command is run under a shell and `hostname -i` is first substituted with the host ip, then the actual command to run the container is `docker run --env HOST_IP=192.168.1.1 nginx /bin/bash`.

However, under Kubernetes, we can only config the container env parameters as strings, it will not be processed first by a shell to do some shell substitution because it directly assemblies all sufficient parameters and send call the docker remote api.

Any related things about this functionality Kubernetes supports?

I think that #27880 has add the support to get nodename from downward API and this feature will be available in Kubernetes 1.4. Currently, we only use kubernete 1.3, to migrate to 1.4 with only using this feature seems impossible. :(

**Comment by resouer** [comment]
As long as you are in a cluster, you should have ways to find the node IP first and then consume it. downwardAPI is the best way, but I am wondering whether you can `ping` that hostname inside container.

**Comment by andyxning** [comment]
@resouer I have come into an idea to learn the ip of the node under `NodeType` service type. In this situation, container is running behind a NAT gateway provided by `iptables`. So, we can just use an HTTP service provided by [ifconfig.me](http://ifconfig.me/) to query the outward node ip. Just by running `curl ifconfig.me/ip` in one container we can get the node ip in http response. This is simple and reliable. 

Since the `ifconfig.me` service is not always available and we have no control over it, i have write a [`host_ip_reflection`](https://github.com/andyxning/host_ip_reflection) to re-implement this.
