### ISSUE TITLE
failed to fit in any node

### ISSUE THREAD

**Issue by Deepak1100** [kubernetes/kubernetes#34920]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
failed to fit in any node Insufficient CPU
scheduler and other

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.7", GitCommit:"a2cba278cba1f6881bb0a7704d9cac6fca6ed435", GitTreeState:"clean", BuildDate:"2016-09-12T23:15:30Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.7", GitCommit:"a2cba278cba1f6881bb0a7704d9cac6fca6ed435", GitTreeState:"clean", BuildDate:"2016-09-12T23:08:43Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): 

```
NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.1 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```
- **Kernel** (e.g. `uname -a`):

```
Linux prod-kube-master-01 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
- **Install tools**:
  only kubernetes componenet and docker
  kubectl, kuberentesa-apiserver ,kubelet ,kube-scheduler 
- **Others**:

**What happened**:
rolling-update is not working. after checking kubectl events find out it is giving below error

```
9m        1d        107       xxxx-916abedbd8771c69102548f7167bf9b7-4snr0   Pod                 Warning   FailedScheduling   {default-scheduler }   pod (xxx-916abedbd8771c69102548f7167bf9b7-4snr0) failed to fit in any node
fit failure on node (prod-kube-minion-02): Insufficient CPU
fit failure on node (prod-kube-minion-04): Insufficient CPU
fit failure on node (prod-kube-minion-03): Insufficient CPU
fit failure on node (prod-kube-minion-01): Insufficient CPU
```

it is not giving any information about usage in the above message (available and requested cpu)
i have checked other things like memory and hard-disk anf there is no issue with them more then 80% of mem and cpu are free 

```
Name:           prod-kube-minion-04
Labels:         beta.kubernetes.io/arch=amd64
            beta.kubernetes.io/os=linux
            kubernetes.io/hostname=prod-kube-minion-04
Taints:         <none>
CreationTimestamp:  Tue, 04 Oct 2016 13:17:48 +0530
Phase:
Conditions:
  Type          Status  LastHeartbeatTime           LastTransitionTime          Reason              Message
  ----          ------  -----------------           ------------------          ------              -------
  OutOfDisk         False   Mon, 17 Oct 2016 10:59:22 +0530     Tue, 04 Oct 2016 13:42:52 +0530     KubeletHasSufficientDisk    kubelet has sufficient disk space available
  MemoryPressure    False   Mon, 17 Oct 2016 10:59:22 +0530     Tue, 04 Oct 2016 13:17:48 +0530     KubeletHasSufficientMemory  kubelet has sufficient memory available
  Ready         True    Mon, 17 Oct 2016 10:59:22 +0530     Tue, 04 Oct 2016 13:42:52 +0530     KubeletReady            kubelet is posting ready status
Addresses:      10.70.43.72,10.70.43.72
Capacity:
 alpha.kubernetes.io/nvidia-gpu:    0
 cpu:                   8
 memory:                32948064Ki
 pods:                  110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:    0
 cpu:                   8
 memory:                32948064Ki
 pods:                  110
System Info:
 Machine ID:            1567d6e82a6770a1b07ff67b5426933c
 System UUID:           EC20081E-60CF-FC0D-A3FC-52D37B90A9ED
 Boot ID:           61d04907-77b7-4106-b32e-dbad8ae48879
 Kernel Version:        3.13.0-36-generic
 OS Image:          Ubuntu 14.04.1 LTS
 Operating System:      linux
 Architecture:          amd64
 Container Runtime Version: docker://1.11.0
 Kubelet Version:       v1.3.7
 Kube-Proxy Version:        v1.3.7
ExternalID:         prod-kube-minion-04
Non-terminated Pods:        (11 in total)
  Namespace         Name                                    CPU Requests    CPU Limits  Memory Requests Memory Limits
  ---------         ----                                    ------------    ----------  --------------- -------------
xxx
xxx
xxx
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted. More info: http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md)
  CPU Requests  CPU Limits  Memory Requests Memory Limits
  ------------  ----------  --------------- -------------
  4260m (53%)   0 (0%)      15840Mi (49%)   15840Mi (49%)
```

every other node have free resource according to kubectl describe node
and i am facing this issue with every other app as well
i have brought a new node and rolling-update works fine so its not pod which is requesting more cpu then node have

this is the resource limit i have given to every app

```
         resources:
           limits:
             memory: 1500Mi
           requests:
             cpu: 420m
```

and i think it should give usage in error msg as well.

**What you expected to happen**:
i have expected it to deploy successfully as every node have sufficient cpu,disk and memory

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:
i have upgraded my kuberentes 2 weeks back to 1.3.7 so it may be problem in this version

**Comment by griffinkelly** [comment]
I am having this exact same issue.

**Comment by Deepak-initcron** [comment]
@griffinkelly 
I have upgrade kubernetes to 1.4.3 from 1.3.7 and everything seems to be working fine in both the environment now.

**Comment by griffinkelly** [comment]
@Deepak-initcron Same--resolved it.

**Comment by felipejfc** [comment]
I'm facing the same issue on a 1.4.0 cluster

**Comment by xmik** [comment]
Me too, on 1.5.0-beta3. First, I was actually trying to schedule Pods which in total needed more CPU than a Kubernetes node had. Then, I deleted (`kubectl delete`)  2 Pods, which gave me 200m CPU free. Still however there is a pending Pod, which needs 100m CPU.

**Comment by veerendramw** [comment]
@griffinkelly @Deepak1100 I am facing the same problem and I am using 1.4.4.

Please help me if this can be solved.

**Comment by pizzarabe** [comment]
I had the same problem. After scaling down some of my pods I was not able to scale them up again.
`No nodes are available that match all of the following predicates:: Insufficient cpu (3)`

The nodes had enough cpu, for example:

```Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests    CPU Limits    Memory Requests    Memory Limits
  ------------    ----------    ---------------    -------------
  860m (14%)    600m (10%)    238Mi (1%)    298Mi (1%)
```

After restarting the k8s master node, the pods successfully started again.
