### ISSUE TITLE
Move "mesos/docker" cloud provide into kube-mesos-framework.

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#34924]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):
master

**Description**:
Currently, the `contrib/mesos` has been moved to https://github.com/kubernetes-incubator/kube-mesos-framework/ , so the `mesos/docker` cloud provider can not work with Mesos because of lacking of `km` .

The proposal is to move `mesos/docker` cloud provider into https://github.com/kubernetes-incubator/kube-mesos-framework , and add a default cloud provider which using RESTful API to connection external cloud provider for necessary resources.

/cc @deads2k @karlkfi @mikedanese

**Comment by smarterclayton** [comment]
Moving to sig scheduling.

**Comment by cmluciano** [comment]
@k82cn Do you still need this?

**Comment by k82cn** [comment]
@cmluciano , yes, we still need this; but this is more complex than I think :(. For now, cloud provider still need to embed into upstream (there's a proposal for external cloud provider, ).

But kube-mesos is using k8s 1.4 as vendor, it's ok to remove related code for higher version. I'm working kube-mesos refactor to avoid dependency to upstream.

**Comment by k82cn** [comment]
/assign

I will trace this.

**Comment by k82cn** [comment]
@cmluciano  , @gyliu513 , please continue the work to remove them.

I assign to myself just for tracing :).

**Comment by k82cn** [comment]
/reopen

I'll trace all related tasks in this issue.

**Comment by luxas** [comment]
@k82cn What are the next steps to do here? Just rip everything mesos-specific out of the core like #47232?
