### ISSUE TITLE
Requests retried after 429 are not being throttled by client

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#34938]
When we are issuing a request to apiserver from client, this is being throttled according to client-specific throttler:
https://github.com/kubernetes/kubernetes/blob/master/pkg/client/restclient/request.go#L854

However, if we get 429 error from apiserver, the retry of it is not being throttled:
https://github.com/kubernetes/kubernetes/blob/master/pkg/client/restclient/request.go#L798

This means, if apiserver is overloaded and is returning 429, the client may potentially send a lot more requests (that are retires) than it actually can according to its QPS limits. This may lead to overloaded apiserver even more...

The fix is it try throttle the request that is retried as a result of 429 received previously.

@kubernetes/sig-api-machinery @lavalamp @gmarek @kubernetes/sig-scalability

**Comment by jayunit100** [comment]
Isn't there the backoff manager command line option for apiserver?  default is set to zero iirc....

**Comment by wojtek-t** [comment]
>
Isn't there the backoff manager command line option for apiserver? default is set to zero iirc....

I don't understand how this is related. Backoff-manager by default adds "0" sleep, yes. But this has nothing to do with the bug reported above.

**Comment by timothysc** [comment]
Wait, we added the exponential back-off on 429 for exactly this reason.. what happened to that code-path?

**Comment by wojtek-t** [comment]
@timothysc - this is not about exponential back-off. This code still exists.
The problem is that if we are retrying a request (as a result of exponential backoff), this is not being throttled (and in my opinion it definitely should).

**Comment by wojtek-t** [comment]
In other words, if a bunch of requests from one client will get 429s, then in the upcoming second we can end up issuing more the QPS limit requests per second from this client (<qps-limit> new requests, a bunch of retries from the previously failed with 429 ones).

**Comment by timothysc** [comment]
Agreed, but I could have sworn we should have jittered the back-off to prevent the re-flooding.  

I suppose we'll also need to backoff the qps limits too.

**Comment by krousey** [comment]
@wojtek-t I think the intended mechanism is for the server to respond with 429 and a "Retry-After" header which will be respected here: https://github.com/kubernetes/kubernetes/blob/master/pkg/client/restclient/request.go#L822 pulled from here: https://github.com/kubernetes/kubernetes/blob/master/pkg/client/restclient/request.go#L1038

**Comment by wojtek-t** [comment]
@krousey what you wrote we already have. But then we still can end-up with significantly more requests send out from a given client than its qps limit/burst is.
See https://github.com/kubernetes/kubernetes/pull/34939 for the fix I am suggesting.
