### ISSUE TITLE
Automatically detect switf url on OpenStack does not cope with multiple object stores

### ISSUE THREAD

**Issue by pcorpet** [kubernetes/kubernetes#34930]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

openstack swift
openstack swift_server_url

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

v1.4.3

**Environment**:
- **Cloud provider or hardware configuration**:

OVH / OpenStack
- **OS** (e.g. from /etc/os-release):

NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
- **Kernel** (e.g. `uname -a`):

Linux my-laptop 4.4.0-42-generic #62-Ubuntu SMP Fri Oct 7 23:11:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:

Running ./cluster/kube-up.sh raises an error with:

``` sh
usage: openstack stack create [-h] [-f {json,shell,table,value,yaml}]
                              [-c COLUMN] [--max-width <integer>] [--noindent]
                              [--prefix PREFIX] [-e <environment>]
                              [--timeout <timeout>] [--pre-create <resource>]
                              [--enable-rollback] [--parameter <key=value>]
                              [--parameter-file <key=file>] [--wait]
                              [--tags <tag1,tag2...>] [--dry-run] -t
                              <template>
                              <stack-name>
openstack stack create: error: unrecognized arguments: https://storage.sbg1.cloud.ovh.net/v1/AUTH_123456789/kubernetes/kubernetes-salt.tar.gz https://storage.bhs1.cloud.ovh.net/v1/AUTH_123456789 https://storage.sbg1.cloud.ovh.net/v1/AUTH_123456789/kubernetes/kubernetes-server.tar.gz KubernetesStack
```

**What you expected to happen**:

The command to succeed!

**How to reproduce it** (as minimally and precisely as possible):

You probably need a setup on OVH which is not very minimal…However see below.

**Anything else do we need to know**:

I've investigated a bit and found that the bug came from `cluster/openstack-heat/util.sh` trying to automatically detect swift url as it wasn't specified. For that it uses the command `openstack catalog show object-store` which, in my case, returns three results. I think a simple fix would be to only get the first one by piping `head -n 1`

``` sh
SWIFT_SERVER_URL=$(openstack catalog show object-store --format value | egrep -o "publicURL: (.+)$" | cut -d" " -f2 | head -n 1)
```

If that sounds good to you, I'll send a PR.

**Comment by jamiehannaford** [comment]
@pcorpet Did you get any further with this?

**Comment by pcorpet** [comment]
Nope, my hint worked for me but I did not send any PR.

**Comment by jamiehannaford** [comment]
@pcorpet Okay, I will submit a PR for it. Thanks for the suggested fix!

**Comment by smarterclayton** [comment]
Fixed.
