### ISSUE TITLE
ReplicaSet created phantom pod

### ISSUE THREAD

**Issue by tazjin** [kubernetes/kubernetes#34940]
**Is this a request for help?**

No, we worked around it but I'm suspicious that it may be a bug.

**What keywords did you search in Kubernetes issues before filing this one?**

Lots of things, like `ReplicaSet`, and more general search on the issue tracker using Google. There are some issues that I think may be related but aren't exactly this problem: #29735, #1892

---

**Kubernetes version**

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- **Kernel** (e.g. `uname -a`): `4.4.23-k8s`
- **Install tools**: `kops`

**What happened**:

After updating a deployment in a namespace other than the `default` namespace a `ReplicaSet` got "stuck" with one pod desired count and 0 pods available.

Scaling the deployment to 0, to 1 and to some random values greater than 1 resulted in entries in `kubectl get events` for that namespace:

```
$ kubectl --namespace foo get events -w
LASTSEEN                         FIRSTSEEN                        COUNT     NAME               KIND         SUBOBJECT   TYPE      REASON              SOURCE                     MESSAGE
2016-10-17 11:12:10 +0200 CEST   2016-10-17 11:03:04 +0200 CEST   3         flink-jobmanager   Deployment               Normal    ScalingReplicaSet   {deployment-controller }   Scaled down replica set flink-jobmanager-3299001242 to 0
2016-10-17 11:12:14 +0200 CEST   2016-10-17 10:59:39 +0200 CEST   4         flink-jobmanager   Deployment             Normal    ScalingReplicaSet   {deployment-controller }   Scaled up replica set flink-jobmanager-3299001242 to 1
```

This did not create any pods though. After observing `get events` for a few minutes, eventually entries like this appeared:

```
2016-10-17 10:18:19 +0200 CEST   2016-10-17 10:18:19 +0200 CEST   1         flink-jobmanager-3299001242-64mmu   Pod       spec.containers{flink}   Normal    Created   {kubelet some-host.eu-central-1.compute.internal}   Created container with docker id fc4bce8c4a41; Security:[seccomp=unconfined]
2016-10-17 10:18:19 +0200 CEST   2016-10-17 10:18:19 +0200 CEST   1         flink-jobmanager-3299001242-64mmu   Pod       spec.containers{flink}   Normal    Started   {kubelet some-host.eu-central-1.compute.internal}   Started container with docker id fc4bce8c4a41
```

SSHing into that node did not show any containers however, and `docker inspect` did not work with that ID.

The pod `flink-jobmanager-3299001242-64mmu` could not be retrieved with `kubectl` at all. I tested various namespaces to see if it somehow ended up somewhere else and even in the brute-force `kubectl get pods --all-namespaces --show-all` it was not listed.

Attempts to `kubectl delete rs` on the "stuck" ReplicaSet returned successes, but the ReplicaSet was not removed / re-created.

We eventually fixed it by deleting the `Deployment` and creating it again, which removed the phantom pod that occured several times in the logs and also the ReplicaSet.

**What you expected to happen**:

I expected a pod to get created by the ReplicaSet.

**How to reproduce it** (as minimally and precisely as possible):

We don't know yet, but I'm trying to figure out if we can reproduce it.

**Anything else we need to know**:

These entries showed up in the `kube-controller-manager` logs:

```
I1017 09:25:55.346085       6 deployment_controller.go:465] Error syncing deployment foo/flink-jobmanager: Operation cannot be fulfilled on replicasets "flink-jobmanager-3299001242": the object has been modified; please apply your changes to the latest version and try again
I1017 09:25:55.350042       6 event.go:217] Event(api.ObjectReference{Kind:"Deployment", Namespace:"foo", Name:"flink-jobmanager", UID:"0c546120-944b-11e6-8192-027da529d661", APIVersion:"extensions", ResourceVersion:"4151610", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set flink-jobmanager-3299001242 to 1
```

**Comment by tazjin** [comment]
This reoccurs with the same `Deployment` sometimes, even after completely deleting it.

Controller manager logs show:

```
I1018 09:06:44.207955       6 deployment_controller.go:465] Error syncing deployment foo/flink-jobmanager: Operation cannot be fulfilled on deployments.extensions "flink-jobmanager": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by janetkuo** [comment]
> Attempts to kubectl delete rs on the "stuck" ReplicaSet returned successes, but the ReplicaSet was not removed / re-created.

When you use `kubectl delete rs` to delete a ReplicaSet (RS) that's created by a Deployment , it will be deleted successfully, and then the Deployment will create it again if the RS's podtemplate is the same as the Deployment's (i.e. it's a new RS). 

I'm not sure what you meant by "the RS wasn't removed/re-created". Why did you think that the RS wasn't deleted and then recreated? Did you check its creation timestamp or its events?

**Comment by kargakis** [comment]
The error message in the controller manager (update conflict) is quite common, the deployment is reprocessed by the controller on the spot. We should probably enhance the log to make it clearer that the deployment is retried.
