### ISSUE TITLE
Pods stops responding

### ISSUE THREAD

**Issue by hus787** [kubernetes/kubernetes#34941]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:13:36Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GCP

**What happened**:

After sustained running for around a weeks the pods stopped serving any request. Ssh-ing into the instance curl-ing the IP of the pod didn't respond to the request. The service was running as expected. The pods showed status running.

Also tried to delete and recreate the deployment in vain.

And what fixed this problem: The exact same thing that makes the HPA start working again (#34312). Upgrading kubernetes from the GCP UI.

**What you expected to happen**:

k8s to be reliable and just work, and not let the services go down.

(Moved from AWS to GCP (because of _k8s_), but these major issue are having us considering to move back.)

**Comment by hus787** [comment]
Dirty hack to get this thing to go away temporarily. Downgrade and upgrade the version of your  k8s.

**Comment by kargakis** [comment]
@kubernetes/sig-node-bugs

**Comment by yujuhong** [comment]
@kargakis not sure why this belongs to sig-node at all...

**Comment by kargakis** [comment]
@yujuhong I have been labeling a bunch of issues for the past days, it's not unlike that I got them all right. It goes w/o saying that mislabeled issues can always be labeled to their correct owners :)

**Comment by yujuhong** [comment]
@kargakis I just wanted to know the reasoning so that we won't be playing ping-pong for issues like this.
