### ISSUE TITLE
Addon-manager is using 1.3.0-beta.2 kubectl

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#34943]
Addon-manager is using 1.3.0-beta.2 version of kubectl:
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/Makefile#L23

This seems bad for the component that we are running in production. We should update it to at-least non-beta version, and probably to 1.4.x something.

**Comment by wojtek-t** [comment]
@kubernetes/sig-cluster-lifecycle

**Comment by roberthbailey** [comment]
@jessfraz @saad-ali 

This appears to be another place we need to keep up to date as we cut newer releases.

**Comment by mikedanese** [comment]
I need to cut another release that contains a version of kubectl with --prune. It's it also important to cut a release that uses v1.4? Is it causing issues?

**Comment by jessfraz** [comment]
Oh interesting do you think the release script should change the version here as well, or maybe this should be pulled from some sort of version file so it's always in sync

**Comment by saad-ali** [comment]
> Oh interesting do you think the release script should change the version here as well, or maybe this should be pulled from some sort of version file so it's always in sync

+1

**Comment by mikedanese** [comment]
I don't think that is a good idea to do in the release script. We would need to do this as part of the ci build. I don't think it's a bad thing that we are using an older version and if we upgrade during a release from v1.3 to v1.4 then there is a huge amount of change that is untested. All of v1.4 alpha window we tested against kubectl v1.3. We have not ran one e2e test against kubectl v1.4.
