### ISSUE TITLE
Common.sh incorrect directory for some commands

### ISSUE THREAD

**Issue by thejaay** [kubernetes/kubernetes#34950]
Hi,

I'm working on a fresh CoreOS installation, juste followed basic steps and did the following comands :
$cd ~
$git clone https://github.com/GoogleCloudPlatform/kubernetes.git
$sudo su
# cd kubernetes/build
# ./release.sh

====>
+++ [1017 13:34:19] Verifying Prerequisites....
cp: cannot stat 'build/build-image/Dockerfile': No such file or directory
!!! Error in ./../build/common.sh:424
  'cp build/build-image/Dockerfile "${LOCAL_OUTPUT_BUILD_CONTEXT}/Dockerfile"' exited with status 1
Call stack:
  1: ./../build/common.sh:424 kube::build::build_image(...)
  2: ./release.sh:35 main(...)
Exiting with status 1

I've corrected the file,and change the following in build/common.sh (L.424,L.425)
cp build/build-image/Dockerfile "${LOCAL_OUTPUT_BUILD_CONTEXT}/Dockerfile"
cp build/build-image/rsyncd.sh "${LOCAL_OUTPUT_BUILD_CONTEXT}/"
to
cp ./../build/build-image/Dockerfile "${LOCAL_OUTPUT_BUILD_CONTEXT}/Dockerfile"
cp ./../build/build-image/rsyncd.sh "${LOCAL_OUTPUT_BUILD_CONTEXT}/"

This bug may exist only for CoreOS and launching the release.sh script

**Comment by Smalinuxer** [comment]
you need to go to the root dir of kubernetes
not the kubernetes/build 
then execute ./build/release.sh

**Comment by xiangpengzhao** [comment]
@Smalinuxer correct. And now we should run `make release` instead.
