### ISSUE TITLE
Leader election errors in >=1.4.0 clusters

### ISSUE THREAD

**Issue by DanHoerst** [kubernetes/kubernetes#34964]
**Kubernetes version** (use `kubectl version`):
Seen in both 1.4.0 and 1.4.3. Do not see the issue in <1.4.0 - which makes sense since the referenced code `leaderelection.go:317` does not exist pre-1.4.0.

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS beta-1185.1.0
- **Kernel** (e.g. `uname -a`): `Linux master 4.7.3-coreos #1 SMP Wed Oct 5 04:11:34 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz GenuineIntel GNU/Linux`
- **Install tools**: In-house deployment tool - essentially follows kubernetes-the-hard-way and uses the AWS cloud provider
- **Others**:

**What happened**:

I’m running 3 control nodes with `--leader-elect=true` on both the scheduler and controller-manager. I’m seeing the following consistently in the logs for both components:

kube-controller-manager:

    Oct 17 17:38:20 master kube-controller-manager[1951]: E1017 17:38:20.109469    1951
    leaderelection.go:317] err: Operation cannot be fulfilled on endpoints "kube-controller-manager":
    the object has been modified; please apply your changes to the latest version and try again

kube-scheduler:

    Oct 17 17:40:35 master kube-scheduler[1973]: E1017 17:40:35.446975    1973
    leaderelection.go:317] err: Operation cannot be fulfilled on endpoints "kube-scheduler": the object
    has been modified; please apply your changes to the latest version and try again

**What you expected to happen**:
I expect not to see errors during leader election

**How to reproduce it** (as minimally and precisely as possible):

Spin up a 3 node control plane with the following config: https://gist.github.com/DanHoerst/8f3985bead5050ce28131eef3c38d27c
Tail unit logs for `kube-scheduler` and `kube-controller-manager` and you should see the errors above.

**Anything else do we need to know**:

**Comment by DanHoerst** [comment]
This seems to be an issue of my control nodes all having a `master` hostname. Setting unique hostnames on the control nodes seems to have resolved the issue.

**Comment by b43646** [comment]
Hi  DanHorest,  Could you please describe more about how to fix the issue? Thanks
