### ISSUE TITLE
Variable expansion doesn't work with valueFrom

### ISSUE THREAD

**Issue by xjlu** [kubernetes/kubernetes#34968]
**Kubernetes version** (use `kubectl version`):

client version: v1.3.6
server version: v1.4.1

**Environment**:
- **Cloud provider or hardware configuration**: aws
- **OS** (e.g. from /etc/os-release): 
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
I wanted to build one new URL from a saved secret, but the variable expansion doesn't work. The `env` in the container command shows that `$(MY_VAR)`  is not expanded.

**What you expected to happen**:
I would expect it to be able to expand the variable when the variable is from a secret key.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

The variable expansion works when the variable is already defined in the yml file.

**Comment by bgrant0607** [comment]
cc @pmorie
