### ISSUE TITLE
"Unable to register third party resources" in kubectl help

### ISSUE THREAD

**Issue by fabianofranz** [kubernetes/kubernetes#34977]
With a Kube server down, any request for cmd help in `kubectl` prints the unexpected message "Unable to register third party resources: Get https://<host:port>/api: dial tcp <host:port>: getsockopt: connection refused".

```
$ kubectl -h
Unable to register third party resources: Get https://192.168.2.200:8443/api: dial tcp 192.168.2.200:8443: getsockopt: connection refused
kubectl controls the Kubernetes cluster manager. 

Find more information at https://github.com/kubernetes/kubernetes.

Basic Commands (Beginner):
  create         Create a resource by filename or stdin
(...)
```

Help commands are not supposed to perform API requests, not even to fetch the API resources.

Kubernetes version: latest master, currently `GitVersion:"v1.5.0-alpha.1.416+c5044acdc025da-dirty", GitCommit:"c5044acdc025da60f90ca102c275746e93b5c746"`.

**Comment by fabianofranz** [comment]
@kubernetes/kubectl

**Comment by fabianofranz** [comment]
@AdoHe @deads2k I didn't investigate yet but this might be related to the discovery RESTMapper in https://github.com/kubernetes/kubernetes/pull/34854 or the Factory refactoring in https://github.com/kubernetes/kubernetes/pull/33180.

**Comment by deads2k** [comment]
> @AdoHe @deads2k I didn't investigate yet but this might be related to the discovery RESTMapper in #34854 or the Factory refactoring in #33180.

This message isn't usually important since TPRs are rare.  opened https://github.com/kubernetes/kubernetes/pull/34981 to glog this message.

**Comment by kargakis** [comment]
I wouldn't expect TRP to be rare in the future.

**Comment by AdoHe** [comment]
```
I wouldn't expect TRP to be rare in the future.
```
yes, I am spending more time to fix TPR outstanding issues.

**Comment by deads2k** [comment]
> I wouldn't expect TRP to be rare in the future.

I think this still stands.  You'll get a different error later on if you attempt to actually use the TPR with the missing mapping.
