### ISSUE TITLE
CRI: clarify the podsandbox resources cleanup behavior

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#34974]
Today kubelet examines containers periodically, and tries to stop/remove/create containers to meet the desired states of the pods. Kubelet is also responsible for reclaiming network resources (by calling `TearDownPod`) when they are no longer needed.

**How is this different with CRI?**

In CRI, instead of assuming an “infra container” , we opt for a more generic pod “sandbox” concept, and leave the implementation details to the runtime time. Pod networking is among those runtime-specific implementation details.  Therefore, a pod sandbox can include various resources, e.g., 
- container (with namespaces) + IP + host ports
- VM + IP + host ports
- namespaces + IP + host ports

**What are the implications of this change in the current CRI implementation?**

Kubelet may not have visibility of resources attached to the sandbox, and in some cases, does not know that it needs to ask the runtime to clean up the resources. One simple example is that the container terminated itself (or be killed due to other incidents such as a docker daemon restart), and the network resources attached to it (IP, ports).

**Who is responsible for initiating the resource reclaim?**

Although runtime has comprehensive knowledge about the resources allocated to the sandbox, shifting the responsibility to runtime implies that the runtime will likely need to perform periodic resource reclaims. This adds unnecessary complexity to the shim/runtime since kubelet already manages the container lifecycle by monitoring the states. To ensure kubelet can reclaim the resources reliably, we should clarify the resource cleanup behavior in the API.

_The state of the sandbox is not just the state of the infra container. It should reflect the state of all resources allocated to the sandbox._
A `PodSandboxID` is a unique ID for identifying a sandbox. As long as there exists resources (e.g., an IP address or container) attached or allocated to the sandbox, runtime should ensure that the sandbox ID is visible upon queries. This allows kubelet to reclaim the resources by calling `RemovePodSandbox`.

**The unfortunate details about kubelet implementation**
Right now, a sandbox can either be `Ready` or `NotReady`. If an infra container died, but the sandbox still occupies an IP address, runtime should report `NotReady` state for the sandbox. 
Ideally, this should be sufficient for kubelet to call `RemovePodSandbox` to reclaim all the resources. However, in today's implementation, kubelet keeps a stopped `PodSandbox` for a prolonged period of time so that it could use the terminated containers a tombstones/checkpoints, as well as retrieve the logs for the containers (which should change in the future). This means if kubelet sees a `NotReady` sandbox, it won't call `RemoveSandbox` immediately. This could lead to kubelet maxing out all the resources (e.g., IP).

One solution is to add a `Stopped` or `Exited`state to the sandbox so that kubelet can distinguish whether resources have been reclaimed or not. 
- Sandbox is `NotReady` or `Ready` -> kubelet calls `StopPodSandbox` -> Sandbox is `Exited`
- Sandbox is `Exited` -> kubelet calls `RemovePodSandbox` -> Sandbox is gone.

This API change is purely driven by the practical needs to cope with kubelet's current restriction, and there might be more ugly ways to handle this without adding states (e.g., always call `StopPodSandbox` when seeing an `NotReady` sandbox.)

/cc @kubernetes/sig-node  @thockin @dchen1107

**Comment by feiskyer** [comment]
I think runtime still needs to perform periodic resource cleanup check even after adding the new state. 

The reason is distinguishing the two different state: `NotReady` and `Exited`, especially in the following scenarios:

- Containers terminated unexpectedly
- Resource cleanup failed

Since the periodic work is necessary, how about fully dedicating the cleanup to runtimes and keeping the sandbox state as is?

**Comment by yujuhong** [comment]
@yifan-gu @euank do you guys have any opinion on whether or not to introduce a new state?

**Comment by yifan-gu** [comment]
> Sandbox is NotReady or Ready -> kubelet calls StopPodSandbox

Seems weird when it's calling `StopPodSandbox()` on `NotReady`. Do you mean it cleans up resources?

**Comment by Random-Liu** [comment]
> Seems weird when it's calling StopPodSandbox() on NotReady. Do you mean it cleans up resources?

I think `NotReady` here just mean some idle resources, and we should stop the idle stuff. But I agree, we may need a better name instead of `NotReady`. :)

**Comment by yujuhong** [comment]
> Seems weird when it's calling StopPodSandbox() on NotReady. Do you mean it cleans up resources?

Yes, basically the sandbox is "running" (i.e., "consuming some resources that can be reclaimed"). It could be running but not ready or ready, but it doesn't matter. Kubelet can call `stop` to reclaim some resources.

**Comment by thockin** [comment]
Is an IP address fundamentally different than some disk space (logs) ?
Both are finite resources, though one is more finite than the other.  What
principle distinguishes the resources that should be cleaned up while in
Exited?

**Comment by feiskyer** [comment]
> Is an IP address fundamentally different than some disk space (logs) ?
> Both are finite resources, though one is more finite than the other. 

The main difference is they are handled by different component: runtime is in charge of disk while shim (with network plugin) is in charge of network resources (IP, port mapping). And I think this is the potential assumption of this issue. If all resources are managed by runtime itself, then there is no such resources cleanup problem.

**Comment by yujuhong** [comment]
@thockin, ideally, kubelet should just be able to remove all all the inactive sandbox/containers right away, but It currently can't do that for the reasons I stated in the original post. 
Given the constraints, if other resources are as flexible, we can wait until kubelet remove all of them in one shot.

However, we have very limited network resources (e.g., 256 IPs), so it may not be desirable to let the sandbox occupy them. Let's think about a concrete example. Kubelet is running N pods that maxes out all IP addresses. Docker daemon restarts and all infra containers are dead. Now kubelet wants to start a new infra container, it will be forced to remove at least one infra containers first, which doesn't work quite well with kubelet's workflow today.

Adding a separate state in `PodSandbox` will make handling more limited resources easier, even though I do feel that this is somewhat hacky.

Also, as @feiskyer mentioned, kubelet manages most (if not all) disk stuff. This issue is about the resources that kubelet doesn't manage directly.

**Comment by dchen1107** [comment]
@yujuhong nice write-up on what we had discussed offline. LGTM!

re: @thockin https://github.com/kubernetes/kubernetes/issues/34974#issuecomment-254720453 There is no fundamental difference between IP address and disk space according to the resource type, both are finite and uncompressible. But once those resources are allocated to Pod / Container, that piece of resource has a different lifecycle. For example, container's logs might be retained much longer on the local disk when all other resources are reclaimed. 

Ideally, `RemovePodSandbox` should reclaim all resources associating with a pod object, including decoupling logs from terminated pod instance, killing running hypervisor process, etc. unbounded logs can be reclaimed separately through logmanager, thus there is no need for `StopPodSandbox` in API. Unfortunately, given lacking proper logging management on the node, we introduce `StopPodSandbox` to indicate CRI to release all associated resources with a Pod and its children, except logging.

**Comment by thockin** [comment]
To be clear, I am OK with the idea, I think, but I wanted to make sure we
understand the principles guiding it.  Be wary of state machines across API
boundaries.

**Comment by yujuhong** [comment]
Since we already introduced a `StopPodSandbox` due to practical reasons regarding kubelet's internal implementation, maybe it does make more sense to introduce a state to distinguish the difference. I will send a PR.

**Comment by yujuhong** [comment]
The prerequisite of adding and utilizing a new `Exited` state is that the dockershim can actually identify all the resources allocated to the sandbox by an ID. I think this requires too much change in the dockershim+network plugins, so we should probably drop this for 1.5. kubelet will rely on the current hack (calling `StopPodSandbox` whenever it sees a exited container), or we can modify `RemovePodSandbox` to always call `StopSandbox` first. 

/cc @thockin @bprashanth
