### ISSUE TITLE
CRI: calling TearDownPod with a exited infra container causing errors

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#34999]
In the default, non-CRI integration, kubelet never calls `TearDownPod` with an exited infra container. 
In the new CRI integration, kubelet tries to call `TearDownPod` whenever it needs to start a new sandbox. Because `Pid` of an exited container is always 0 (from `docker inspect`), kubenet cannot get the network namespace for the container by reading `/proc/0/ns/net`. This causes `TearDownPod` to fail permanently (on every sync), and kubelet unable to start new sandbox and containers.

See an example below for such a failure:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gci-gce-cri-serial/58
(In the serial suite, docker may be restarted, so it is normal for infra containers to die along with it).
kubelet.log for jenkins-e2e-minion-group-7nto:
```
I1017 11:54:47.163823    1309 kuberuntime_manager.go:587] Stopping PodSandbox for "kubernetes-dashboard-v1.4.0-yvett_kube-system(33e26d63-9452-11e6-aed7-42010af00002)", will start new one
I1017 11:54:47.164632    1309 server.go:612] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kubernetes-dashboard-v1.4.0-yvett", UID:"33e26d63-9452-11e6-aed7-42010af00002", APIVersion:"v1", ResourceVersion:"271", FieldPath:""}): type: 'Normal' reason: 'SandboxChanged' Pod sandbox changed, it will be killed and re-created.
I1017 11:54:47.168184    1309 kubenet_linux.go:659] Removing kube-system/kubernetes-dashboard-v1.4.0-yvett from 'kubenet' with CNI 'bridge' plugin and runtime: &{ContainerID:97db96f7912e0b5660ee1ffe9ef295430b266d052ed5df7e20912f86d90dcd07 NetNS:/proc/0/ns/net IfName:eth0 Args:[]}
I1017 11:54:47.192231    1309 kubenet_linux.go:490] TearDownPod took 28.382774ms for kube-system/kubernetes-dashboard-v1.4.0-yvett
E1017 11:54:47.192258    1309 kuberuntime_manager.go:840] Failed to teardown network for pod kubernetes-dashboard-v1.4.0-yvett_kube-system(33e26d63-9452-11e6-aed7-42010af00002) using network plugins "kubenet": Error removing container from network: failed to Statfs "/proc/0/ns/net": no such file or directory
E1017 11:54:47.193123    1309 kuberuntime_manager.go:593] killPodWithSyncResult failed: failed to "TeardownNetwork" for "33e26d63-9452-11e6-aed7-42010af00002" with TeardownNetworkError: "Failed to teardown network for pod kubernetes-dashboard-v1.4.0-yvett_kube-system(33e26d63-9452-11e6-aed7-42010af00002) using network plugins \"kubenet\": Error removing container from network: failed to Statfs \"/proc/0/ns/net\": no such file or directory"
E1017 11:54:47.193159    1309 pod_workers.go:184] Error syncing pod 33e26d63-9452-11e6-aed7-42010af00002, skipping: failed to "TeardownNetwork" for "33e26d63-9452-11e6-aed7-42010af00002" with TeardownNetworkError: "Failed to teardown network for pod kubernetes-dashboard-v1.4.0-yvett_kube-system(33e26d63-9452-11e6-aed7-42010af00002) using network plugins \"kubenet\": Error removing container from network: failed to Statfs \"/proc/0/ns/net\": no such file or directory"
I1017 11:54:47.193745    1309 server.go:612] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kubernetes-dashboard-v1.4.0-yvett", UID:"33e26d63-9452-11e6-aed7-42010af00002", APIVersion:"v1", ResourceVersion:"271", FieldPath:""}): type: 'Warning' reason: 'FailedSync' Error syncing pod, skipping: failed to "TeardownNetwork" for "33e26d63-9452-11e6-aed7-42010af00002" with TeardownNetworkError: "Failed to teardown network for pod kubernetes-dashboard-v1.4.0-yvett_kube-system(33e26d63-9452-11e6-aed7-42010af00002) using network plugins \"kubenet\": Error removing container from network: failed to Statfs \"/proc/0/ns/net\": no such file or directory"
```

One solution is to check whether the pid is zero, and don't error out if that's the case. Since @freehan is working on refactoring kuberuntime/kubenet code, this problem may get fixed along the way. Filing this issue so that we can keep track of the potential issues. 

/cc @kubernetes/sig-node @freehan

**Comment by feiskyer** [comment]
> In the new CRI integration, kubelet tries to call TearDownPod whenever it needs to start a new sandbox. 

I think this logic is wrong. Should only call network plugins when it is ready. Trying to fix this in #35019.

**Comment by yujuhong** [comment]
It's not necessarily wrong given the implementation today. If dockershim reports sandbox "not ready" after the infra container died on its own, we still need to tear down the resources such as IP addresses and host ports. See #34974 for why calling this may be a safeguard if we can't represent the resources correctly today.

**Comment by feiskyer** [comment]
> If dockershim reports sandbox "not ready" after the infra container died on its own, we still need to tear down the resources such as IP addresses and host ports.

That's right. Network resources should be released no matter what status of the sandbox. (I'm going to close #35019.)

cc/ @kubernetes/sig-network

**Comment by feiskyer** [comment]
@yujuhong It seems more discussions are required for #34780, how about to do a quick fix of this problem? e.g. enforce runtime to return a empty string instead of nil pointer in such cases:

```go
// Namespace contains paths to the namespaces.
message Namespace {
    // Network is the path to the network namespace:
    // 
    // * nil if netns is not setup by runtime
    // * netns path if it is setup by runtime
    // 
    // If netns has already been removed somewhere (e.g. docker will 
    // remove the netns automatically if the container exited), this field
    // should be set to an empty string.
    optional string network = 1;
    ....
}
```

By the way, after #34780, netns is not used any more by kubelet and it can be removed from CRI.

**Comment by yujuhong** [comment]
I am fine with a short-term fix. @feiskyer wanna send a PR?

**Comment by feiskyer** [comment]
@yujuhong Sorry for late resp and thanks for #35240 to fix this.

**Comment by yujuhong** [comment]
No problem. Let's close this issue.
