### ISSUE TITLE
Add support for other object types to "kubectl set selector"

### ISSUE THREAD

**Issue by asalkeld** [kubernetes/kubernetes#35007]
**Is this a request for help?**

No

**What keywords did you search in Kubernetes issues before filing this one?** 
set selector

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Small FEATURE REQUEST:

When adding "kubectl set selector" I was asked to start simply by only adding support for Services. Once we understand the usecase better we should support for the other object types.

See:
https://github.com/kubernetes/kubernetes/pull/28949#pullrequestreview-4444544

**Comment by asalkeld** [comment]
This will be needed in pkg/kubectl/cmd/set/set_selector.go in the function  updateSelectorForObject()

```golang
	copyNewSelector := func() *unversioned.LabelSelector {
￼ 		dst := unversioned.LabelSelector{}
		dst.MatchLabels = make(map[string]string)
		for label, value := range selector.MatchLabels {
			dst.MatchLabels[label] = value
		}

		dst.MatchExpressions = make([]unversioned.LabelSelectorRequirement, len(selector.MatchExpressions))
		copy(dst.MatchExpressions, selector.MatchExpressions)
		return &dst
	}
```

**Comment by kargakis** [comment]
@kubernetes/kubectl

**Comment by pwittrock** [comment]
set selector is a bit odd since we probably don't want to change the selectors on controller objects.  Presumably the main use case here is for updating service label selectors?

**Comment by kargakis** [comment]
@pwittrock the first impl of `set selector` (https://github.com/kubernetes/kubernetes/pull/28949) will support only services. I am not sure if we ever proceed with having the command work with controller objects, we need to sort it out in this issue.

**Comment by pwittrock** [comment]
SGTM.  We should have the documentation reflect that.  I would explicitly not have it work with controller objects, and I would have a user message stating they shouldn't change selectors on controller objects.

**Comment by asalkeld** [comment]
@pwittrock yip, that is how I have it now. see https://github.com/kubernetes/kubernetes/pull/28949/files#diff-ca09d9af0b033ca4bcecc8362a9cfddbR219

**Comment by pwittrock** [comment]
SGTM.  If you would, add me to the PR just for reviewing the docs pieces

**Comment by soltysh** [comment]
For a lot of new objects selector will be automatically generated by the controller, this applies to jobs, scheduled jobs, for sure. One of the reasons was to ensure selector uniqueness. Users can add their own, if the wish, though.

**Comment by soltysh** [comment]
That should be reflected here somehow, as well.

**Comment by deads2k** [comment]
> For a lot of new objects selector will be automatically generated by the controller, this applies to jobs, scheduled jobs, for sure. One of the reasons was to ensure selector uniqueness. Users can add their own, if the wish, though.

Doing this seems to defeat the purpose of the selector.  If you just want a straight ref, why not use a straight ref?

**Comment by bgrant0607** [comment]
Selectors for workload controllers are most immutable now
