### ISSUE TITLE
Surface missing dlls through events

### ISSUE THREAD

**Issue by adg** [kubernetes/kubernetes#35010]
**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:

I pushed a container to Google Container Registry that contained not much more than the binary  `/storeserver`, and then tried to create a service and deployment for that image. This is a setup that has worked well for a while now.

The issue in this case was that the binary is a Go binary and I mistakenly built it with CGO enabled, but my container did not include any of the shared libraries required by the bits of CGO built into my binary.

The result is that the pod would be stuck in `CrashLoopBackOff` but with no log messages. Doing a `describe` of the pod yielded this error message:

```
Error syncing pod, skipping: failed to "StartContainer" for "storeserver" with RunContainerError: "runContainer: Error response from daemon: Container command '/storeserver' not found or does not exist."
```

This error message implied that the binary was not in the container, when really the binary failed to start because of missing linked objects.

**What you expected to happen**:

An error message that explained why the binary could not be executed.

**How to reproduce it** (as minimally and precisely as possible):

Build a container that contains only a dynamically linked program. Maybe it has to be a Go program; I haven't tried it with a C program.

**Comment by bprashanth** [comment]
I guess the issue here is that there's no way (but for execing into your container and running ldd, right?) for the kubelet to know that your base image lacks those dlls.

**Comment by adg** [comment]
Well, the error message doesn't necessarily need to say anything about missing linked libraries. But there should be some way to differentiate between a binary failing to execute and the binary not existing.

The error message

> Container command '/storeserver' not found or does not exist.

implies the binary is missing, but it's there.

**Comment by pwittrock** [comment]
That is surprising.  Can we give the exit code of the binary as well?
