### ISSUE TITLE
watch resync goroutine leak after "401: The event in requested index is outdated and cleared" error

### ISSUE THREAD

**Issue by tatsuhiro-t** [kubernetes/kubernetes#35015]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

watch leak

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

1.4.0

**Environment**:
- **Cloud provider or hardware configuration**: vagrant on Mac OS X
- **OS** (e.g. from /etc/os-release): CoreOS 1164.1.0
- **Kernel** (e.g. `uname -a`):  `Linux core-01 4.7.3-coreos #1 SMP Sat Sep 10 08:21:12 UTC 2016 x86_64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz GenuineIntel GNU/Linux`
- **Install tools**:
- **Others**:

**What happened**:

We ran controller which handles our own ThirdPartyResource.
When we hit "watch of ... ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared" error, "forcing resync" log is duplicated.
This log message comes from [here](https://github.com/kubernetes/kubernetes/blob/1d323adade5fc6ecd898908d2c6cb391c8748835/pkg/client/cache/reflector.go#L284).  It looks like this goroutine does not exit when we hit the above mentioned error, and continued to work, and running "resync" more frequently.

**What you expected to happen**:

The resync goroutine must be terminated when watch is closed (i.e., ListAndWatch function returned), instead of leaking it.

**How to reproduce it** (as minimally and precisely as possible):

I just run our controller for ~15 minutes.  I'm not sure why "401: The event in requested index is outdated and cleared (the requested history has been cleared" happens, but from the issues I read, it should be harmless.

**Anything else do we need to know**:

**Comment by jbeda** [comment]
I think I see what is going on here.  If `ListAndWatch` exits for any reason beyond an error from the resync loop no one will tell the resync loop to exit.  Furthermore, there is no "local" way to do this as it would be unexpected for this function to signal the Done channel as other things outside of it may be relying on it.

There are some useful functions around Context (https://golang.org/pkg/context/#WithCancel) that help to create a "local" copy of context that can be used in this situation.

**Comment by tatsuhiro-t** [comment]
Thank you for reply.
Isn't is possible to create local channel in ListAndWatch, and defer close it,  and then make resync goroutine "select" it too?

**Comment by tatsuhiro-t** [comment]
This issue was labelled as component/kubectl, but actually it is not limited to kubectl.  All controllers suffer from this.
Only people notice this if they enable V(4) logging.

**Comment by tatsuhiro-t** [comment]
The really annoying thing caused by this issue is that eventually resync is done in every few seconds due to the leaked goroutine.  Even if you set 30 second resync period in controller, leaked goroutines call resync too, and you end up having resync call very very frequently.  If you have many resources in cache, it really performs unnecessary sync loop.  This is the last thing you want.

**Comment by caesarxuchao** [comment]
@wojtek-t @lavalamp this looks like a real issue. Could be related to https://github.com/kubernetes/kubernetes/issues/33472.

https://github.com/kubernetes/kubernetes/pull/35672 looks like a proper fix.

**Comment by wojtek-t** [comment]
I agree - this looks like a real issue. And indeed #35672 LGTM as a fix for it.
