### ISSUE TITLE
document advice about generation/observedGeneration for controllers

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#35036]
For some kinds of controllers, its important to know which `generation` the `status` is valid for.  I don't think its strictly needed for all controllers, but its worth some thought to determine whether its easier to apply the rule for everyone or if that would cause unnecessary controller churn for meaningless changes.

Also, if you have multiple controllers working off the same object (service accounts as a for instance), then each individual one would need to manage their own `observedGeneration`.

**Comment by kargakis** [comment]
Opened https://github.com/kubernetes/community/issues/135
