### ISSUE TITLE
CLI(kubectl) and dashboard(UI) not in sync on deletion of POD

### ISSUE THREAD

**Issue by 14msitaqadeer** [kubernetes/kubernetes#35045]
If a POD is deleted from UI, it still appears in CLI and vice versa if a POD is deleted from CLI it does not remove from UI.

**Comment by pwittrock** [comment]
Can you provide steps to reproduce?

**Comment by bgrant0607** [comment]
Deletion of a pod is a questionable scenario, and insufficient details.

**Comment by arslanqadeer** [comment]
@pwittrock that was misunderstanding due to different namespaces. I apologize.
this issue is no more valid, please close this.
