### ISSUE TITLE
discuss the meaning of kubeadm init --api-advertise-addresses

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#35043]
As of #34607, we have the following code:

```
if len(s.API.AdvertiseAddresses) > 0 {
    command = append(command, fmt.Sprintf("--advertise-address=%s", s.API.AdvertiseAddresses[0]))
}
```

It turns out that the condition will always be true, which was not what I desired when I wrote #34607, however it may be what we want, let's discuss here.

When I wrote this, I have overlooked the fact that when kubeadm auto-detects the primary IP , it just sets it in `s.API.AdvertiseAddresses` and doesn't indicate that it's an auto-detected IP.

I may be desirable to leave API server's `--advertise-address` flag unset in the case when kubeadm auto-detects the IP and only set it when user has explicitly specified `--api-advertise-addresses` (and document clearly that only first value will be used for advertising internally, i.e. what `kubernetes` service IP will get pointed at). This way we can leave API server to us it's own logic to set address it should advertise.

Alternatively, we can keep having strong preference here, which may be a good thing. But it will probably conflict with `--bind-address`, whenever we decide to add support for it.

Initially, `--api-advertise-addresses` flag was only mean for certificates and completely independent of `--bind-address`, but that was simply about picking less preferences. We also still need to have the discussion about `--bind-address` as well, I think the main requirement there is to allow user to have any kind of external load-balancer, DNS or whatever NAT situation they might have...

ATTN: @kubernetes/sig-cluster-lifecycle

**Comment by Crazee** [comment]
What I need is a way to specify the *only* "public" IP address to be used for communication between nodes.  Not something in addition to the "I'm gonna use eth0 because I like it" auto-detection business.

**Comment by errordeveloper** [comment]
Point taken, we definitely want to allow this to be done easily. Do you
always have public IP on one of the interfaces on the machine? Many cloud
providers use NAT, or force you to use a load balancer. Also, in an HA
setting, restricting to single IP is undesirable.

**Comment by luxas** [comment]
Eventually we want to be able to use componentconfig to set this via the config file...

**Comment by Crazee** [comment]
In my case I have set up an overlay network (on an interface not eth0) connecting the nodes.  It's cloud based and does HA by placing a new outbound connection to the cloud (load balancer, etc.) if the current connection fails.  I need no open inbound ports for running the infrastructure.

I'd be happy if all the bits of each Kubernetes node used only this address to talk to other Kubernetes nodes.

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#37
