### ISSUE TITLE
Add kubeadm to hyperkube

### ISSUE THREAD

**Issue by bogdando** [kubernetes/kubernetes#35041]
FEATURE REQUEST: Please add the kubeadm binary to hyperkube or ship it as a separate container perhaps

**Comment by bogdando** [comment]
Related https://github.com/kubernetes/kubernetes.github.io/issues/1319
Use case is: user may want to install binaries that listed as kubeadm dependencies from hyperkube, not from packages. Thus, the kubeadm must be able to be installed w/o dependencies or just from hyperkube

**Comment by sandys** [comment]
+1 on this. i would rather not depend on package manager for k8s updates... especially when i may need to get some patches.

i would much rather have

```docker pull gcr.io/google_containers/kube-kubeadm-amd64:v1.4.0
sudo docker run -i -t kube-kubeadm setup-or-update-systemd-targets```

**Comment by errordeveloper** [comment]
cc @kubernetes/sig-cluster-lifecycle

**Comment by bogdando** [comment]
It seems rejected
