### ISSUE TITLE
Federation soak weekly deployment failing

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/kubernetes#35040]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-soak-weekly-deploy-gce-federation/1

looks like permission issue
ERROR: (gcloud.compute.project-info.describe) Could not fetch resource:
 - Required 'compute.projects.get' permission for 'projects/k8s-jkns-gce-federation-soak'

@madhusudancs @quinton-hoole

**Comment by quinton-hoole** [comment]
@madhusudancs I also don't seem to have permissions on that project (k8s-jkns-gce-federation-soak).  Could you please address the issue Shashi reported above, and at the same time make sure that k8s-federation@ have owner perimissions on that project, to remove yourself as an SPOF :-).  Thanks.

**Comment by madhusudancs** [comment]
@shashidharatd ACLs changed.

@quinton-hoole You should have the access now. All the relevant groups have been given appropriate permissions.
