### ISSUE TITLE
AWS: Shared resource tag

### ISSUE THREAD

**Issue by austinmoore-** [kubernetes/kubernetes#35052]
In order to use some resources in AWS, Kubernetes currently requires "ownership" of the resource with the tag `KubernetesCluster=<cluster_id>`. However, some resources can belong to more than a single Kubernetes cluster. Resources could potentially be used by things outside of Kubernetes, or perhaps by other Kubernetes clusters one day. Once the `KubernetesCluster` tag is applied to these resources and a cluster has "ownership" over them, there is a potential that Kubernetes tools like kube-up or kops could modify or remove these resources.

A tag indicating that a resource is "shared" would be valuable. @justinsb has said that he thinks it should be something like `kubernetes.io/<clustername>=shared`.

It may be valuable to rethink the `KubernetesCluster` tag in general, keeping in mind use cases like shared resources and multiple cluster ownership (#22058).

**Comment by hjacobs** [comment]
@austinmoore- we are also running into a similar issue with the `KubernetesCluster` tag as we want to reuse our network setup (i.e. subnets). The AWS integration currently assumes only one cluster per subnet (subnets tagged with `KubernetesCluster=...`).

**Comment by justinsb** [comment]
This is now implemented as @kenden pointed out here: https://github.com/kubernetes/kubernetes/issues/22058#issuecomment-308026369
