### ISSUE TITLE
OpenStack LBaaS V2 Deletes Load Balancers if "ManageSecurityGroups" is true.

### ISSUE THREAD

**Issue by grahamhayes** [kubernetes/kubernetes#35056]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version** (use `kubectl version`): Master

**Environment**:
- **Cloud provider or hardware configuration**: OpenStack
- **OS** (e.g. from /etc/os-release): n/a
- **Kernel** (e.g. `uname -a`): n/a
- **Install tools**: n/a
- **Others**:

**What happened**:
`EnsureLoadBalancer` now can update a LB instead of deleting it and recreating it.

However the security group  code is still set to try and create security group rules, and if it gets an error, delete the LB and start over.

**What you expected to happen**:
Updating a service does not delete the LBaaS LB

**How to reproduce it** (as minimally and precisely as possible):
Enable `manage-security-groups` in the `[LoadBalancer]` section of `/etc/cloud.conf`

Restart a `kube-control-manager`

**Anything else do we need to know**:

**Comment by suonto** [comment]
@grahamhayes you're absolutely right, this is a critical issue (if you enable security group management). The dangerousness of aggressive cleanups has already been discussed in detail in this thread: https://github.com/kubernetes/kubernetes/pull/33276. I hope you guys can fix this.

**Comment by grahamhayes** [comment]
Yup - I have a larger refactor, that ensures this, and a few other edge cases we have found in our development.

It is in massive need of a rebase though, so I will need a day or 2 of uninterrupted time to get it together

**Comment by jamiehannaford** [comment]
@grahamhayes Are you still working on this? If not, I can take a look.

**Comment by dims** [comment]
@grahamhayes ping :)

**Comment by bashofmann** [comment]
We just ran into this where Kubernetes recreated an LB with a new Floating IP because the OpenStack API was not available for a few seconds while the LB was updated.

@dims Could this issue be re-opened? Since this is a major bug for us, we will start working on a fix for this today.
