### ISSUE TITLE
kubectl --v= is underdocumented

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#35054]
_(Comes from user)_

The most important thing for cloud support is insight, logs, verbosity. The description of the `--v` argument reads:
`--v=0: log level for V logs`
- What are the different log levels?
- What level is most useful to see all API calls?
- What is "V"?
- What would be a useful standard reply to a customer? "Please re-run this command with --v=9 and send me the output"

With gcloud I normally ask for the output of `--log-http --verbosity=debug`.

@kubernetes/kubectl @ymqytw @pwittrock

**Comment by pwittrock** [comment]
@fabianofranz This one you want to take a look at?

**Comment by fabianofranz** [comment]
@pwittrock yes, I can take this one.

**Comment by ghodss** [comment]
Related: #13282

**Comment by fabianofranz** [comment]
Reproducing the comment I added in https://github.com/kubernetes/kubernetes/issues/13282#issuecomment-254864687:

There are logs present across the codebase that go from 0 up to 10. 

I'd suggest we formally embrace **0-4 as debug-level** logs, and **5-10 as trace-level** ones. Then I'd do 3 things:

1) Update the flag description to something like the one below. 

```
-v, --v=0: Set the level of log output to debug-level (0~4) or trace-level (5~10) 
```

Also, short and long forms are equal today (`-v` and `--v`), we could in addition consider a longer long form like `--loglevel`, although there might be back compat issues.

2) Review and replace across the codebase to make sure logs are compliant with the debug/trace levels.

3) Update user/contrib docs.

What do you think?

**Comment by janetkuo** [comment]
Where does ` -v` / `--v` come from? I think it's from `glog`. Would this make it hard to change its flag description? 

Agree that we should define debug/trace levels, and logs in the codebase should be compliant with them.

**Comment by fabianofranz** [comment]
> Where does -v / --v come from? I think it's from glog

Yes, comes from `glog` vendored in `client-go`, as a global flag:

https://github.com/kubernetes/client-go/blob/master/vendor/github.com/golang/glog/glog.go#L401

I'll probably just fetch the global flag when `kubectl` is created (around [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/cmd.go#L202-L218)) and override the description, so that we don't have to patch vendored dependencies.

**Comment by janetkuo** [comment]
Or perhaps add a flag `--verbosity`(=debug, info, warning, error, critical, none) that sets `-v` for you? Would that be easier from UX perspective?

**Comment by soltysh** [comment]
I'd propose `loglevel`, we are already doing that downstream in OpenShift, see [here](https://github.com/openshift/origin/blob/fff24240feca7e823c4e713e7691f4d8fa66b7a9/pkg/cmd/flagtypes/glog.go#L16). As for docs can we use this https://github.com/kubernetes/kubernetes/blob/master/docs/devel/logging.md with extra information about levels 7, 8 which allow you to dump HTTP requets.

**Comment by smarterclayton** [comment]
In openshift we intercept this and change the flag name to loglevel, so
it's possible but annoying.

On Oct 21, 2016, at 5:55 PM, Janet Kuo <notifications@github.com> wrote:

Where does -v / --v come from? I think it's from glog. Would this make it
hard to change its flag description?

Agree that we should define debug/trace levels, and logs in the codebase
should be compliant with them.

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/35054#issuecomment-255474886>,
or mute the thread

**Comment by fabianofranz** [comment]
How it looks like to change the flag description by the intercept-and-change method (no changes yet to long or short flag names):

https://github.com/fabianofranz/kubernetes/commit/8f5c76daccdb0f4fc64d6bbd70de7c838a4a921c

**Comment by ghodss** [comment]
If we're going to create a different long name, we should keep to word separation conventions and call it --log-level.

**Comment by fabianofranz** [comment]
@janetkuo I think `--verbosity` sounds interesting in terms of clarity, but that would be an addition (not replacement) to `-v`, correct? Just take `debug|info|warning|error|critical` and map each to 0~10 levels, but still expose `-v` if you want to set it numerically, and make them mutually exclusive.

**Comment by bgrant0607** [comment]
See also #29681

**Comment by bgrant0607** [comment]
And #22723

**Comment by janetkuo** [comment]
> @janetkuo I think `--verbosity` sounds interesting in terms of clarity, but that would be an addition (not replacement) to `-v`, correct? Just take `debug|info|warning|error|critical` and map each to 0~10 levels, but still expose `-v` if you want to set it numerically, and make them mutually exclusive.

Yes that's what I thought

**Comment by ghodss** [comment]
Doesn't glog even let you control verbosity of info/warning/error/fatal?

**Comment by ianchakeres** [comment]
My team ran into this issue recently, and I decided to write up some documentation for the kubectl cheatsheet. You can find the PR at https://github.com/kubernetes/kubernetes.github.io/pull/4186.

Please chime in on the PR with comments and whether it looks good. 

FYI: @pwittrock @mikegrass @dhegde @krmayankk

**Comment by zhangxiaoyu-zidif** [comment]
@ianchakeres 
what does --v=10 mean? 
many member conduct to use '--v=10' to check problem

**Comment by ianchakeres** [comment]
@zhangxiaoyu-zidif Kubernetes uses glog. Here is a link to some glog documentation - https://godoc.org/github.com/golang/glog.

Generally log lines with lower log-level numbers mean that those log lines are more important, and higher log-level numbers are less important and more verbose.

When I did a simple `kubectl get po` with `--v=8` and `--v=10` I did not see any difference in the output. 

I did a quick grep on the kubernetes source code for glog loglines with log-levels 10-19 and I found 136 references, of which 127 are for log-level 10.

```
$pwd
<snip>/k8s.io/kubernetes
$ grep -ri "V(1.)" pkg/* 2>/dev/null | wc -l
    136
```

**Comment by resouer** [comment]
@ianchakeres I believe `--v=10` should let you see request and response of your command, no?

**Comment by ianchakeres** [comment]
@resouer - I think that `--v=8` will display http contents. I did not see any difference in the output between `--v=8 `and `--v=10` when executing `kubectl get po`.

**Comment by discordianfish** [comment]
I'll open a new issue for that but want to get some feedback here first: Do we believe glog in general is a good choice? The overall interface is somewhat unexpected if you're used to other open source leveled loggers. Additionally, glog isn't a Real Open Source project with it being developed internally by Google and only pushed out without ways to fill issues or submit pull requests.

**Comment by Hades32** [comment]
The much greater problem to me is that even with -v=99 I can see next to nothing what is kubectl really doing. Is the request using a proxy? is the "forbidden" an http response or not... and so on...

**Comment by xmik** [comment]
It is documented here: https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-output-verbosity-and-debugging

**Comment by ghuntley** [comment]
Popping into here to chime in with the same feedback as the op. The CLI args are underdocumented. Thank-you @xmik for linking to https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-output-verbosity-and-debugging. I'm not yet in a position where would be comfortable raising a PR for this but this totes needs to happen.

**Comment by chenrui333** [comment]
where are we with this issue?

**Comment by dims** [comment]
@chenrui333 we now have forked glog into `klog`, so  we can do whatever we wish. Someone has to look at the suggestions in this PR and propose a PR

https://github.com/kubernetes/klog/blob/master/klog.go#L407-L420

**Comment by stevemcquaid** [comment]
@fabianofranz are you still working on this? I'd be happy to take over to get my first kubernetes contrib

**Comment by MalloZup** [comment]
i have spent a PR for this because yesterday i was typing `-v debug` and starring the screen why i could not see the debug infos, so i jumped on this issue :smile_cat: 
Hope it helps ! :sun_with_face: 
https://github.com/kubernetes/klog/pull/32
