### ISSUE TITLE
on machines with iptables default deny, kubelet could enable ports in iptables

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#35069]
I have a customer who is using Kubelet on a machine with iptables configured for default deny.  When running with plain Docker, it will configure any hostPort mapping to ACCEPT.   Kubelet does not.  Worse, Docker does not seem to handle this when running in host-network, but it probably should.

So this idea: Kubelet could/should enable `<pod-id>:<ports>` and `<node-ip>:<host-ports` for ACCEPT.

Danger: does this expose people who previously were not exposed?

@kubernetes/sig-network 
@kubernetes/sig-node for CRI

**Comment by caseydavenport** [comment]
Have to think about how this interacts with various NetworkPolicy implementations.  We don't want `<pod-ip>:<port>` to automatically ACCEPT unless a NetworkPolicy says its allowed.

Maybe the answer is only do this when namespace isolation is not `DefaultDeny`?
