### ISSUE TITLE
API Server returns HTTP 200 OK on "too old resource version" errors

### ISSUE THREAD

**Issue by kelseyhightower** [kubernetes/kubernetes#35068]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
- "too old resource version"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:13:36Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

```
gcloud container clusters list
```

```
NAME  ZONE        MASTER_VERSION  MASTER_IP       MACHINE_TYPE   NODE_VERSION  NUM_NODES  STATUS
k0    us-west1-b  1.4.1           104.199.114.88  n1-standard-1  1.4.1         3          RUNNING
```

**What happened**:

When the resource version is too old the API server returns HTTP 200 OK.

```
$ curl -i http://127.0.0.1:8001/api/v1/watch/namespaces/default/endpoints/nginx?resourceVersion=240385
```

```
HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 18 Oct 2016 21:47:16 GMT
Content-Length: 176

{"type":"ERROR","object":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"too old resource version: 240385 (250923)","reason":"Gone","code":410}}
```

**What you expected to happen**:

When the resource version is too old the API server returns HTTP 410 to match the error code in the response body.

**How to reproduce it** (as minimally and precisely as possible):
- Create a deployment and expose it.
- Scale up the deployment to 3 nodes
- Wait ~30 mins and get the endpoints backing the service
- Perform a watch on the endpoint using the resource version from the previous get

**Anything else do we need to know**:

No.

**Comment by quinton-hoole** [comment]
Looks like a straight bug to me.

**Comment by kelseyhightower** [comment]
Another thing that I find odd is that the resource version will remain too old and there is no way to retrieve a resource version that is current and will work with a future watch request.

Hours later and no changes to the nginx endpoints results in the following:

Get the current nginx endpoint and capture the resource version (250647):
```
$ curl http://127.0.0.1:8001/api/v1/namespaces/default/endpoints/nginx
```
```
{
  "kind": "Endpoints",
  "apiVersion": "v1",
  "metadata": {
    "name": "nginx",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/endpoints/nginx",
    "uid": "ce671363-942c-11e6-87dc-42010a8a008d",
    "resourceVersion": "250647",
    "creationTimestamp": "2016-10-17T05:44:44Z",
    "labels": {
      "run": "nginx"
    }
  },
  "subsets": [
    {
      "addresses": [
        {
          "ip": "10.176.0.31",
          "nodeName": "gke-k0-default-pool-12695b58-7ocd",
          "targetRef": {
            "kind": "Pod",
            "namespace": "default",
            "name": "nginx-1172225296-xkhwx",
            "uid": "c230d8f9-956a-11e6-87dc-42010a8a008d",
            "resourceVersion": "240348"
          }
        },
        {
          "ip": "10.176.0.32",
          "nodeName": "gke-k0-default-pool-12695b58-7ocd",
          "targetRef": {
            "kind": "Pod",
            "namespace": "default",
            "name": "nginx-1172225296-j1rih",
            "uid": "c2314f78-956a-11e6-87dc-42010a8a008d",
            "resourceVersion": "240345"
          }
        },
        {
          "ip": "10.176.2.28",
          "nodeName": "gke-k0-default-pool-12695b58-rltz",
          "targetRef": {
            "kind": "Pod",
            "namespace": "default",
            "name": "nginx-1172225296-17g3g",
            "uid": "54b83562-955b-11e6-87dc-42010a8a008d",
            "resourceVersion": "228832"
          }
        },
        {
          "ip": "10.176.2.59",
          "nodeName": "gke-k0-default-pool-12695b58-rltz",
          "targetRef": {
            "kind": "Pod",
            "namespace": "default",
            "name": "nginx-1172225296-l1dfz",
            "uid": "c230f0ec-956a-11e6-87dc-42010a8a008d",
            "resourceVersion": "240372"
          }
        },
        {
          "ip": "10.176.2.61",
          "nodeName": "gke-k0-default-pool-12695b58-rltz",
          "targetRef": {
            "kind": "Pod",
            "namespace": "default",
            "name": "nginx-1172225296-rchna",
            "uid": "c230b4c2-956a-11e6-87dc-42010a8a008d",
            "resourceVersion": "240385"
          }
        }
      ],
      "ports": [
        {
          "port": 80,
          "protocol": "TCP"
        }
      ]
    }
  ]
}
```

Start a watch using the resource version (250647):

```
$ curl-i http://127.0.0.1:8001/api/v1/watch/namespaces/default/endpoints/nginx?resourceVersion=250647
```
```
HTTP/1.1 200 OK
Content-Type: application/json
Date: Wed, 19 Oct 2016 02:08:12 GMT
Content-Length: 176

{"type":"ERROR","object":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"too old resource version: 250647 (275904)","reason":"Gone","code":410}}
```

Is there another way to get the current resource version? My current workaround is to check if the type is ERROR and restart the watch at 0. This workaround has the drawback that you'll need to ignore the first response with type ADDED or else you'll end up in a fast loop and ddos the API server.

**Comment by lavalamp** [comment]
Is this a bug in the `kubectl proxy` or a bug in apiserver? I'm having a hard time believing that we return 200s from apiserver in this condition.

**Comment by lavalamp** [comment]
Oh, wait a second. I forgot how this worked. The 200 is because the connection was established; it did that before getting the error from etcd. There (unfortunately) has to be two distinct error mechanisms for streaming connections, since you only get one chance to return a status code but an error can happen at any point.

It looks bad when an error is the first thing returned, but IIRC changing this is actually technically difficult. And since clients *need to handle errors in this form anyway*, it may actually be a good thing that it's easy to produce one, so people will be surprised long before they get to production.

@kelseyhightower

**Comment by sjenning** [comment]
Just stumbled on this issue.  This is addressed in `kubectl`with https://github.com/kubernetes/kubernetes/pull/27392.

As far as watching from the current resourceVersion, the resourceVersion returned in lists is always the current resourceVersion.  Setting resourceVersion=0 in the watch also works.

**Comment by sjenning** [comment]
I think this is fixed by https://github.com/kubernetes/kubernetes/pull/25369
