### ISSUE TITLE
Add kubectl log --all flag so I don't have to manually iterate all my containers

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#35076]
atm a `kubectl log some-pod` only returns `choose one of: [kubedns dnsmasq healthz]` ... but if something is wrong I usually want to just get all of the logs ...

So I'd love to have `--all` which then prints

```
container: kubedns
... logs
container: dnsmasq
... logs
```

**Comment by zreigz** [comment]
If there is a need I can work on this

**Comment by floreks** [comment]
I think it's a good idea to add this flag. As @zreigz is working on other issue then I can work on implementation.

@AdoHe @pwittrock what do you think about this? Should I go for it?

**Comment by pwittrock** [comment]
cc @fabianofranz

**Comment by pwittrock** [comment]
SGTM if it is relatively simple to code and test.

**Comment by floreks** [comment]
I'll know more once I check the code. It shouldn't be hard to implement, Also I think that `-f` switch for streaming logs should be blocked when `--all` will be used. What do you think?

**Comment by grosser** [comment]
For an initial version that is good enough, but it would be great to eventually have that ... make it work just like `tail -f log/*` works ...

**Comment by fabianofranz** [comment]
SGTM. A few comments:

- Note that `--all` must be validated as mutually exclusive with `--container=`. 
- I know it's verbose but I'd vote for `--all-containers` as the flag name, for clarity. 
- A different option would be to suppress the "choose one of ..." message in case of pods with multiple containers and make it always show all by default. Would remove the need for the `--all` flag, and you can still use `--container=` to explicitly choose one.

Thoughts?

**Comment by grosser** [comment]
that would be even better ... no new flag to teach everyone ...

**Comment by floreks** [comment]
@fabianofranz 

I like the third option also. I'll work on that.

> For an initial version that is good enough, but it would be great to eventually have that ... make it work just like tail -f log/* works ...

That would be nice. I'll investigate that and if it's not too complex then I can implement it.

**Comment by floreks** [comment]
I've investigated that and I have few concerns. Current flow is rather complex (kubectl -> apiserver -> kubelet) and even simple support for `tail` with option to list all containers requires changes in kubelet.

Kubelet exposes 
`<kubeletIP>:<kubeletPort>/containerLogs/<podNamespace>/<podID>/<containerName>` endpoint. Handler for this endpoint handles all additional arguments like: tail, follow, etc.

We'd need to expose new endpoint here: 
`<kubeletIP>:<kubeletPort>/containerLogs/<podNamespace>/<podID>` and implement new logic in there.

This requires changes in `kubelet` and `apiserver`. Possibly `kubectl` would not have to be touched if we would go with suppress "choose one of..." option.

Log link creation (apiserver): https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/pod/strategy.go#L267

Container logs handler (kubelet): https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/server.go#L422

What do you think? Any simpler way to achieve that?

**Comment by grosser** [comment]
I have no idea about go, but I'd say: parallelize the fetching using the
current implementation ... then do the logic when something arrives ?

**Comment by floreks** [comment]
> I have no idea about go, but I'd say: parallelize the fetching using the
current implementation ... then do the logic when something arrives ?

Interesting idea. It may work. I'll check this out.

**Comment by floreks** [comment]
@grosser I've had some time today to check this and unfortunately it is not so simple.

API Server currently acts as a proxy between kubectl and kubelet. It returns single http response checker and opens something like a tunnel between our console/browser and kubelet (when `--follow` is used). The problem with your idea is that we would need some kind of proxy in between api server and kubelet that would fetch and compose all the logs from kubelet and return single location from which stream of logs could be passed further. I'm not sure how to do that without exposing new endpoint.

Currently it is written in a way that does not allow fetching logs from multiple sources and I don't want to add this logs for all containers option without option to stream logs, because it will require major changes later anyway.

We could try to modify logic in kubelet to accept container parameter in form i.e. 
`https://192.168.30.230:10250/containerLogs/kube-system/kube-dns-v11-3256422451-kucep/etcd,skydns`
 so we can pass multiple containers and actually get output or do as I've proposed before and expose brand new endpoints for this.

**Comment by floreks** [comment]
More I'm looking into this more issues I encounter and they are all related to logs streaming. My Go knowledge might not be enough at this point.

Main issue is that response stream from i.e. [docker client](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/kube_docker_client.go#L391) during redirect to output stream (basically when `io.Copy()` is used) will hang until `EOF` is found or some kind of error is returned and we need to be able to open multiple streams and follow them in parallel. 

Anyway this feature is quite big and  IMHO requires changes in apiserver and in kubelet all the way to docker client (rkt client also), probably we need something like `MultiLogs(ids []string, ...)` that is similar to `Logs (link above)` but gives options to stream logs in parallel for multiple containers.

I think this needs some more discussion.

**Comment by pwittrock** [comment]
@floreks Thanks for doing the research.  Sounds like the work is quite large in scope and may be something we should hold off on in favor of lower hanging fruit for now.

**Comment by grosser** [comment]
FYI now handling this in a script:

```Ruby
  # show all logs
  # https://github.com/kubernetes/kubernetes/issues/35076
  # init containers is in beta so they key might change later on
  pod_definition = JSON.load(`kubectl get pod #{pod_name} -o json`)
  annotations = pod_definition.dig('metadata', 'annotations')
  init_container_key = annotations.keys.detect { |k| k =~ /init-containers$/ }
  containers = (
    JSON.load(annotations[init_container_key] || '[]') +
    pod_definition.dig('spec', 'containers')
  ).map { |c| c.fetch('name') }

  puts "Logs:"
  containers.each do |container|
    puts "Container #{container}:" if containers.size > 1
    puts `kubectl logs #{pod_name} --container #{container}`
  end
```
