### ISSUE TITLE
CRI: Package aliases are not following golang convention

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#35070]
As is mentioned in https://github.com/kubernetes/kubernetes/pull/33988#discussion_r83764898.

In CRI and dockershim, we are using package name containing capitalized characters e.g. `internalApi` and `runtimeApi`.

This is not align with golang convention https://blog.golang.org/package-names, we should change this to `internalapi` and `runtimeapi` in one PR.

@timstclair @yujuhong @feiskyer 
/cc @kubernetes/sig-node

**Comment by timstclair** [comment]
This has happened before (https://github.com/kubernetes/kubernetes/issues/15319), it will happen again. We should add a presubmit check.

**Comment by timstclair** [comment]
List of packages violating the convention: https://gist.github.com/timstclair/72da2df961d85606cce3d9bf266ecef8

**Comment by feiskyer** [comment]
Hmm, maybe it's my problem. Changing this would conflict with a lot of pending PRs, let's fix this later.
