### ISSUE TITLE
Add a timestamp to the suffixes created for e2e node test objects

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#35074]
Currently the e2e node tests create various objects (kubelet systemd service, folder for extracting test tarball, etc.), these objects currently get a random int suffix to make them distinct from equivalents across test runs. When you ssh into a node to debug your tests, it is hard to tell which object relates to your latest test run. I propose adding a short timestamp to the suffix string of these objects to make this more obvious. Ideally the same timestamp would be consistently applied to all suffixed objects for the entirety of a given test run.

**Comment by Random-Liu** [comment]
SGTM. Thanks for filing the issue!

And we should also organize the directories we create on the node. Currently, node e2e create:
* `node-e2e-pod464777457` for static pod
* `node-e2e023305963` for etcd
* `gcloud-e2e-121486241` for test binary and result.

It's not obvious to figure out which is doing what. We should also organize the directory structure.
