### ISSUE TITLE
kubeadm: Discovery interface needs to be refactored

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#35073]
The token discovery interface is not properly factored to extend to the other two discovery methods. Discovery should return a kubeconfig. TLS bootstrap should accept a kubeconfig. The internals of the token discovery should be hidden.

cc @dgoodwin @kubernetes/sig-cluster-lifecycle

**Comment by luxas** [comment]
@dgoodwin can I assign this issue to you?

**Comment by dgoodwin** [comment]
Sure I have some notes from @mikedanese on how to approach (ComponentConfig is new to me), Mike yell fast and loud if you started on this, otherwise I will try to find some time to dig in.

**Comment by luxas** [comment]
It's not different from any other structs; just code normally :)

**Comment by mikedanese** [comment]
I'm going to start looking at this.

**Comment by dgoodwin** [comment]
Thanks Mike, apologies I haven't been able to get anywhere close to starting it.

**Comment by mikedanese** [comment]
No worries :+1:

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#36
