### ISSUE TITLE
 Duplicate code about GenericConfig's Complete()  in APIServer module

### ISSUE THREAD

**Issue by ghost** [kubernetes/kubernetes#35088]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

When we call the main function  app.Run(s),at the beginning, we get the 'genericConfig' by "genericConfig := genericapiserver.NewConfig(). // create the new config
                            ApplyOptions(s.ServerRunOptions). // apply the options selected
                            Complete() "
here we call the function "(c *Config) Complete()", and then,we get the struct master by "m, err := config.Complete().New()",in the function config.Complete(),we also call "c.GenericConfig.Complete()".
Maybe we could remove the latter one, is my understanding right?

**What you expected to happen**:

we call the function "(c *Config) Complete()" once

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by oomichi** [comment]
This issue should be closed because the corresponding PR has been already merged.
