### ISSUE TITLE
Failing to fetch pod logs when federation e2e fails

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#35080]
Example:

https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-federation/5347/build-log.txt

Relevant part:

```
Oct 18 05:53:02.535: INFO: Failed to get logs of pod e2e-image-puller-jenkins-us-central1-f-minion-group-e7fr, container image-puller, err: Get https://10.128.0.11:10250/containerLogs/kube-system/e2e-image-puller-jenkins-us-central1-f-minion-group-e7fr/image-puller?previous=true: dial tcp 10.128.0.11:10250: i/o timeout
[1mSTEP[0m: Logs of kube-system/e2e-image-puller-jenkins-us-central1-f-minion-group-e7fr:image-puller on node jenkins-us-central1-f-minion-group-e7fr
Oct 18 05:53:02.535: INFO: image-puller : STARTLOG

ENDLOG for container kube-system:e2e-image-puller-jenkins-us-central1-f-minion-group-e7fr:image-puller
```

As a result, we no longer have federation apiserver and federation controller manager pod logs to debug failures.

cc @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
I debugged this in a local cluster.
kubelet is up and working fine. I can create new deployments and pods get started. that means kubelet can talk to apiserver and watch for new pods.
But proxying to kubelet via apiserver is not working. Not just logs, but none of the command that uses that apiserver proxy (like kubectl exec) is working.

@madhusudancs mentioned that there might have been a change in some networking policy which was not applied to our test suite. Will try to find if anything changed.

cc @shashidharatd

**Comment by liggitt** [comment]
does this correlate with the merge of https://github.com/kubernetes/kubernetes/pull/33718? that changed to use the node-reported IP address when talking from the master to the node.

https://github.com/kubernetes/kubernetes/pull/35497 is a follow up that allows the apiserver to select which node-reported address to use for master->node communications

**Comment by madhusudancs** [comment]
@liggitt 

> does this correlate with the merge of #33718? that changed to use the node-reported IP address (preferring the internal IP) when talking from the master to the node.

That might be the reason.

> #35497 is a follow up that allows the apiserver to select which node-reported address to use for master->node communications

And that too.

So what I found was that there were no firewalls to allow communication on internal IPs. So I fixed that by manually installing the rule. But I am guessing that this happened to regular GCE tests as well. Any idea how that was fixed?

**Comment by liggitt** [comment]
> But I am guessing that this happened to regular GCE tests as well. Any idea how that was fixed?

nope

**Comment by quinton-hoole** [comment]
Closing old bug reports.  Re-open as necessary.
