### ISSUE TITLE
`No resources found.` is printed by kubectl when error.

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#35092]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug

**Kubernetes version** (use `kubectl version`):
master

**What happened**:

`No resources found.` is printed when error.

```
$ kubectl get nodes -s http://127.0.0.1:8888
Unable to register third party resources: Get http://127.0.0.1:8888/api: read tcp 127.0.0.1:35830->127.0.0.1:8888: read: connection reset by peer
No resources found.
Unable to connect to the server: read tcp 127.0.0.1:49192->127.0.0.1:8888: read: connection reset by peer
```

**What you expected to happen**:
Only error message was printed.

**Comment by AdoHe** [comment]
I believed this has been fixed #34981

**Comment by k82cn** [comment]
@AdoHe , it seems not; in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/get.go#L326 , it's not necessary to print `No resources found.` if errs is not empty.

**Comment by AdoHe** [comment]
@k82cn ok, seems other issue.
