### ISSUE TITLE
kube-apiserver flag redefined: log_dir

### ISSUE THREAD

**Issue by vklonghml** [kubernetes/kubernetes#35096]
hi,forums
when i run go install in cmd/kube-apiserver, then start this binary, the service always failed with
panic(0x305bb20, 0xc8203cb430)
/usr/local/go/src/runtime/panic.go:481 +0x3e6
flag.(FlagSet).Var(0xc820088300, 0x7f9dde6366a0, 0xc8203cb3e0, 0x42546b0, 0x7, 0x4714660, 0x2f)
/usr/local/go/src/flag/flag.go:776 +0x454
flag.(FlagSet).StringVar(0xc820088300, 0xc8203cb3e0, 0x42546b0, 0x7, 0x0, 0x0, 0x4714660, 0x2f)
/usr/local/go/src/flag/flag.go:679 +0xc7
flag.(*FlagSet).String(0xc820088300, 0x42546b0, 0x7, 0x0, 0x0, 0x4714660, 0x2f, 0xc8203cb3d0)
/usr/local/go/src/flag/flag.go:692 +0x83
flag.String(0x42546b0, 0x7, 0x0, 0x0, 0x4714660, 0x2f, 0x7f9dde5b4d00)
/usr/local/go/src/flag/flag.go:699 +0x5f
github.com/golang/glog.init()
/opt/k8s/src/github.com/golang/glog/glog_file.go:41 +0x13e
k8s.io/client-go/1.4/pkg/labels.init()
/opt/k8s/src/k8s.io/client-go/1.4/pkg/labels/selector.go:822 +0x5b
k8s.io/client-go/1.4/pkg/api/unversioned.init()
/opt/k8s/src/k8s.io/client-go/1.4/pkg/api/unversioned/zz_generated.deepcopy.go:390 +0x6f
k8s.io/client-go/1.4/pkg/api.init()
/opt/k8s/src/k8s.io/client-go/1.4/pkg/api/zz_generated.deepcopy.go:3749 +0x6e
k8s.io/client-go/1.4/rest.init()
/opt/k8s/src/k8s.io/client-go/1.4/rest/versions.go:88 +0x75
k8s.io/kubernetes/plugin/pkg/client/auth/gcp.init()
/opt/k8s/src/k8s.io/kubernetes/plugin/pkg/client/auth/gcp/gcp.go:119 +0x59
k8s.io/kubernetes/plugin/pkg/client/auth.init()
/opt/k8s/src/k8s.io/kubernetes/plugin/pkg/client/auth/plugins.go:23 +0x3b
k8s.io/kubernetes/pkg/client/unversioned.init()
/opt/k8s/src/k8s.io/kubernetes/pkg/client/unversioned/util.go:79 +0xe7
k8s.io/kubernetes/pkg/controller/serviceaccount.init()
/opt/k8s/src/k8s.io/kubernetes/pkg/controller/serviceaccount/tokens_controller.go:746 +0xa8
k8s.io/kubernetes/cmd/kube-apiserver/app.init()
/opt/k8s/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:310 +0x107
main.init()
/opt/k8s/src/k8s.io/kubernetes/cmd/kube-apiserver/apiserver.go:54 +0x4f

even doing the steps below:
1)run godep restore (godep) in the client-go/1.4 folder, then remove the vendor folder of client-go. Then the packages in your GOPATH will be the only copy
2)or run godep save in your application folder to flatten all dependencies.

the problems can not be resolved, how can i do to solve this, thks.

**Comment by liggitt** [comment]
the issue due to `glog/glog_file.go` registering a flag as a package variable, and vendoring glog multiple times (via `k8s.io/client-go`, `k8s.io/kubernetes`, and/or `github.com/golang/glog`)
```
var logDir = flag.String("log_dir", "", "If non-empty, write log files in this directory")
```

**Comment by liggitt** [comment]
@caesarxuchao how are you solving the double-vendor problem with client-go?

**Comment by caesarxuchao** [comment]
We recommended using a vendor management tool like Godep or Glide to flatten the dependencies.

@vklonghml could you check if you still have multiple copies of glog? Maybe adding a `debug.PrintStack()` to see where else calls `glog.init()`.

**Comment by breezelxp** [comment]
@vklonghml have you solveld this problem? I encounterd this also.

**Comment by kargakis** [comment]
Seeing this issue when trying to import `apimachinery/pkg/api/equality`.
```
/tmp/go-build285975936/k8s.io/test-infra/prow/cmd/deck/_test/deck.test flag redefined: log_dir
panic: /tmp/go-build285975936/k8s.io/test-infra/prow/cmd/deck/_test/deck.test flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc420062060, 0x11f4f00, 0xc4202c5b90, 0xd57a1d, 0x7, 0xd7465b, 0x2f)
	/usr/lib/golang/src/flag/flag.go:793 +0x5e1
flag.(*FlagSet).StringVar(0xc420062060, 0xc4202c5b90, 0xd57a1d, 0x7, 0x0, 0x0, 0xd7465b, 0x2f)
	/usr/lib/golang/src/flag/flag.go:696 +0x8b
flag.(*FlagSet).String(0xc420062060, 0xd57a1d, 0x7, 0x0, 0x0, 0xd7465b, 0x2f, 0x2)
	/usr/lib/golang/src/flag/flag.go:709 +0x8b
flag.String(0xd57a1d, 0x7, 0x0, 0x0, 0xd7465b, 0x2f, 0xc420181800)
	/usr/lib/golang/src/flag/flag.go:716 +0x69
github.com/golang/glog.init()
	/home/mkargaki/kube/src/github.com/golang/glog/glog_file.go:41 +0x14a
k8s.io/apimachinery/pkg/labels.init()
	<autogenerated>:1 +0x64
k8s.io/apimachinery/pkg/apis/meta/v1.init()
	<autogenerated>:1 +0x85
k8s.io/apimachinery/pkg/api/equality.init()
	<autogenerated>:1 +0x50
k8s.io/test-infra/prow/cmd/deck.init()
	<autogenerated>:1 +0xc8
main.init()
	<autogenerated>:1 +0x53
exit status 2
FAIL	k8s.io/test-infra/prow/cmd/deck	0.085s
```

**Comment by kargakis** [comment]
Hrm, I think this is because I hadn't vendored that package so it was being used by its canonical location and not from my vendor. `test-infra` is already pruning nested vendored deps via `dep`.

/remove-lifecycle frozen

**Comment by kargakis** [comment]
Yes, I can confirm the above.

/close

**Comment by folago** [comment]
I still get this, with dep v0.4.1.
And as far as I can tell no packages importing glog are in my gopath.
Anyone has an idea on why?

**Comment by folago** [comment]
I take it back, transitive dependancy.
Sorry for the noise.
