### ISSUE TITLE
Avoid computing the same information multiple times in scheduler

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#35117]
Looking into profiles of scheduler, there shows a bunch of things that we are doing unnecessarily.
In particular, instead of computing the same information for a given node multiple times, we should cache it as part of NodeInfo:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/schedulercache/node_info.go#L32

The information that should be cached and reuse later include:
- [x] node taints:
  https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L1054
- [x] node conditions: disk/memory/inode pressure
  https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L1123
  https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L1141
  https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L1159

**Comment by wojtek-t** [comment]
Another quick optimization should be optimizing "selectHost" method:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/generic_scheduler.go#L132

In fact it doesn't need to sort the whole list (which is O(nlgn).
All we need to do is to choose the elements that have highest score, and sort only those by node name (to leave the logic that we currently have with round-robic logic of choosing from those).

**Comment by wojtek-t** [comment]
And we should also limit the amount of places where we call "Parallelize" (because those are relatively expensive). The whole MR-like priorities is a step in this direction too.

**Comment by wojtek-t** [comment]
OK - I've just sent out a PR fixing the first two things.

**Comment by timothysc** [comment]
@wojtek-t can we close this, or are there still work items here?

**Comment by wojtek-t** [comment]
Some of those are not yet done.

**Comment by gmarek** [comment]
@timothysc - it's not a high priority for us (for now), so if you want it to be done soon, you probably need to find someone to do it.

**Comment by timothysc** [comment]
@jayunit100 - assigned.

**Comment by resouer** [comment]
Why "Parallelize" is considered as relatively expensive ? (comparing to MR style)

**Comment by xiang90** [comment]
> Parallelize

You do MR when there are certain points that need some synchronizations. Or fully parallelized computation will always be faster.

**Comment by wojtek-t** [comment]
> Why "Parallelize" is considered as relatively expensive ?

To clarify, I was referring to the Parallelize function:
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/workqueue/parallelizer.go#L29

Using this for many very small functions is pretty expensive - you can take a look into cpu-profiles. It happens that 20% or sth of cpu usage is spent on the operations on the synchronization channel.

**Comment by jayunit100** [comment]
What is remaining here.... Just an audit of parallelization ?

**Comment by gmarek** [comment]
It's hard to tell if caching is done - when adding new priority functions/moving existing ones to MR-framework one pretty often discovers that more things need to be cached.

There's my PR #35630, that moves basic spreading priority function to MR-framework, which for some reason makes it worse. I didn't have time to look into that though. This needs to be done, which may require modifying MR-framework slightly (allowing different type as a Map phase result).

**Comment by jayunit100** [comment]
- Im not sure what the MR Framework stuff is referring to.  Can you provide me a pointer ?
- Should we close this issue since the original patches for caching were done?  Sounds like the work we're referring to now is actually more like a second iteration.

**Comment by gmarek** [comment]
"MR-style" parallelization, that was mentioned before. Yeah, I guess we can close this - this is more like an ongoing process thing, when everyone who adds anything to the scheduler needs to keep it in mind.
