### ISSUE TITLE
how to remove the docker images and tag the image again?

### ISSUE THREAD

**Issue by fw0037** [kubernetes/kubernetes#35118]
when I using the commands in kubernetes like below:

docker build -t cenginetest:latest  /root/
docker tag  <imageid>  http://10.60.80.80/cenginetest
docker push  http://10.60.80.80/cenginetest

then I using kubectl create -f /root/cenginetest.yaml to create pods.
using docker rmi -f <imageid> to remove the image, because of the incorrect pods.
Now I rebuild the image and tag the image again, but it can't be tag again.
the error message is:

**Error parsing reference: "http://10.60.80.80/cenginetest" is not a valid repository/tag**

how to fix it?

the environment is;
CentOS7

kubectl version
client version: version.info{Major:"1", Minor:"3", Gitversion:"v1.3.7", GitCommit:"a2cba278cbalf688lbb0a7704d9cac6fca6ed435",GitTreeState:"clean", BuildDate:"2016-09-12T23:15:30Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
server version: version.info{Major:"1", Minor:"3", Gitversion:"v1.3.7", GitCommit:"a2cba278cbalf688lbb0a7704d9cac6fca6ed435",GitTreeState:"clean", BuildDate:"2016-09-12T23:08:43Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by colemickens** [comment]
This has nothing to do with Kubernetes.

The problem is exactly what the error message says: `http://10.60.80.80/cenginetest` is not a valid docker tag. Docker tags have three segments normally: `http://10.60.80.80/repo/cenginetest`, for example.

**Comment by fw0037** [comment]
thank.
