### ISSUE TITLE
Create firewall flake

### ISSUE THREAD

**Issue by lukaszo** [kubernetes/kubernetes#35123]
I1019 05:22:31.267] Creating new network: jenkins-e2e
W1019 05:22:31.486] WARNING: You are creating a legacy network. Using --mode=legacy will be required in future releases.
W1019 05:22:53.272] Created [https://www.googleapis.com/compute/v1/projects/k8s-jkns-pr-gci-gke/global/networks/jenkins-e2e].
I1019 05:22:53.442] NAME         MODE    IPV4_RANGE     GATEWAY_IPV4
I1019 05:22:53.442] jenkins-e2e  legacy  10.240.0.0/16  10.240.0.1
W1019 05:22:53.442] 
W1019 05:22:53.442] Instances on this network will not be reachable until firewall rules
W1019 05:22:53.442] are created. As an example, you can allow all internal traffic between
W1019 05:22:53.442] instances as well as SSH, RDP, and ICMP by running:
W1019 05:22:53.442] 
W1019 05:22:53.443] $ gcloud compute firewall-rules create <FIREWALL_NAME> --network jenkins-e2e --allow tcp,udp,icmp --source-ranges <IP_RANGE>
W1019 05:22:53.443] $ gcloud compute firewall-rules create <FIREWALL_NAME> --network jenkins-e2e --allow tcp:22,tcp:3389,icmp
W1019 05:22:53.443] 
W1019 05:22:54.928] ERROR: (gcloud.compute.firewall-rules.create) Some requests did not succeed:
W1019 05:22:54.929]  - The resource 'projects/k8s-jkns-pr-gci-gke/global/networks/jenkins-e2e' is not ready
W1019 05:22:54.929] 
W1019 05:22:55.000] ERROR: (gcloud.compute.firewall-rules.create) Some requests did not succeed:
W1019 05:22:55.001]  - The resource 'projects/k8s-jkns-pr-gci-gke/global/networks/jenkins-e2e' is not ready
W1019 05:22:55.001] 
I1019 05:22:55.072] Starting master and configuring firewalls
W1019 05:22:55.577] ERROR: (gcloud.compute.firewall-rules.create) Some requests did not succeed:
W1019 05:22:55.577]  - The resource 'projects/k8s-jkns-pr-gci-gke/global/networks/jenkins-e2e' is not ready
W1019 05:22:55.577] 
W1019 05:22:55.583] ERROR: (gcloud.compute.firewall-rules.create) Some requests did not succeed:
W1019 05:22:55.583]  - The resource 'projects/k8s-jkns-pr-gci-gke/global/networks/jenkins-e2e' is not ready

[Full log ](https://00e9e64bacb5a845d921002f083c62ad20a94915292547a634-apidata.googleusercontent.com/download/storage/v1/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F34770%2Fpull-kubernetes-e2e-gke-gci%2F298%2Fbuild-log.txt?qk=AD5uMEuT5snFkBmNRxpGl0xRMVs31TkkltJ1kd9Tia55GDSnO8lGc76uPqx-_PmEqd8_q8gyKCqsJrI7VprzWJkmYSVii6zmeTElrdRvEEdav4y_Lxkg1gqpSKbazCvJeh1WjH0bkEHypU8zb-tSma-iinFadE7lyABIR_pu3dGhxAm7fi2qTS2vcZfjqDbhouobKhAHAlivzoz-utgDt_z2R_Gj5_6V3XEDBwO6u727exteMcTnip7E6t9RvmykrFaajGBYSDYKDFVQHKGYtnkWVqSlsdcFPwLDWRURQtEIzAT8Q1388MmKa85q_hCHLIYKpU55NsAHk1eOlSsZYmDkzFS5NWM3zy1H8Vb42zRRISZP2HvRv4TMGh2knMlNVEfbzGduZkrcrcJdTyiLHfYQjwXLebf8bgWbN3wk9YNUcIn-zH2_rZXHYleY4E3jucLFVJ6x8OhQLMxn5ZpRrSH4UOctxprzRTZAMFCpWKOsv6Zddi5QLHjRs71hMCL70Vm1yUCEiDbTzemwjNotWIh12RHKOsHBtVKSFvXLKbCUXeuT84q2sqCU6U8xc6yGPtpE_T3DLHgMaW6l6wooXdCa8fTeIGnyeWa9ZPAbLLaWL3oqHzK8qOm0tD8hH_iYCwIpZxB77rrImAnymaloF9AW9CrWTQPpaHtD_jblig7UN4gu1B5xZzATtXTBaiz3G5onJRMLHX_HbALTlZkSHE5v1V0Ty8Qyni5Tzw2E_F11YMJNxr5V2xWn7rj-LTQCklSnYRHVgFpcJViuxjxVwsTwRKPAY7J9irt3_eg2On3lduLsK6xglIGAMU-41iueHciE4cBJ9r7PlPnNjy60kmIy3UE2Lc6eGITodn9GjXQljD1OoA6rW9M)

**Comment by spxtr** [comment]
For some reason it's using `jenkins-e2e` for all clusters rather than the agent name.

**Comment by spxtr** [comment]
It's testing GCE! I'll fix.

**Comment by lukaszo** [comment]
Fixed in kubernetes/test-infra#880
