### ISSUE TITLE
Protobuf serializer messes with 2xx responses from the api server

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#35126]
We have an endpoint that replies with 204 every time it doesn't have any work to do but the protobuf serializer returns an "empty data" error when decoding and makes callers believe there is an actual error.  It shouldn't.

cc: @kubernetes/sig-api-machinery @smarterclayton

**Comment by smarterclayton** [comment]
Hrm.  We're letting the decoder handle zero byte input (on the off chance that the decoder understand empty objects).  JSON and Protobuf serializer behave differently in presence of empty.

If we read a file on disk, an empty file is an error (it's not a valid object).  So I think the serializers should error on empty output (and handle "almost" empty like `{}` as they do today), and rest client should not call decode on a 204.  But the semantics of how rest client handles empty bodies (for instance, from Do or Into()) needs to be discussed.

I don't think it's appropriate to no-op a 204 body inside of client/request.go.  It's likely Into() can tolerate an empty object, but we may need to return more info because &v1.Pod{} is not the same as empty Pod.

What actual client invocation results in the 204 (can you give me an example)?

**Comment by kargakis** [comment]
> What actual client invocation results in the 204 (can you give me an example)?

- oc can never result in a 204 because it always forces a new rollout (and either succeeds or fails depending on the state of the triggers). 
- The trigger controller watches for deployment configs and it may reconcile one that doesn't need to be updated (already deployed, no change in the pod template or image update). In such a case /instantiate doesn't have anything to do and will return a 204.

**Comment by smarterclayton** [comment]
What is the specific client code you are calling?

**Comment by kargakis** [comment]
There is no client code involved apart from [the instantiate call in the controller](https://github.com/openshift/origin/blob/5134734ee2abc109b37abc558d2c9140bf72acd2/pkg/deploy/controller/generictrigger/controller.go#L44). In the server, [here](https://github.com/openshift/origin/blob/5134734ee2abc109b37abc558d2c9140bf72acd2/pkg/deploy/registry/instantiate/rest.go#L76-L82) is the reply that causes the protobuf serializer to return "empty data". Note that we merged a fix in the controller to treat "empty data" as a nil error in https://github.com/openshift/origin/pull/11441

**Comment by smarterclayton** [comment]
The instantiate client method is wrong - it needs to handle the difference between getting a 204 and an object:

```
// Instantiate instantiates a new build from build config returning new object or an error
func (c *deploymentConfigs) Instantiate(request *deployapi.DeploymentRequest) (*deployapi.DeploymentConfig, error) {
	result := &deployapi.DeploymentConfig{}
	err := c.r.Post().Namespace(c.ns).Resource("deploymentConfigs").Name(request.Name).SubResource("instantiate").Body(request).Do().Into(result)
	return result, err
}
```

Should be calling `.Do()` and then checking StatusCode != 204.  Then calling `.Into()`.

The client method should be checking whether the body is length 0 before calling the status decode check.

**Comment by kargakis** [comment]
Users of the client cannot get the status code from the result since it's unexported. Digging into the client lib I found `WasCreated` (which doesn't seem to be used anywhere btw) :
```go
// WasCreated updates the provided bool pointer to whether the server returned
// 201 created or a different response.
func (r Result) WasCreated(wasCreated *bool) Result {
	*wasCreated = r.statusCode == http.StatusCreated
	return r
}
```
It seems that we need a generic `HasStatusCode` that would look like:
```go
// HasStatusCode updates the provided bool pointer to whether the server returned
// the provided status code.
func (r Result) HasStatusCode(statusCode int, hasStatusCode *bool) Result {
	*wasCreated = r.statusCode == statusCode
	return r
}
```
Thoughts?

**Comment by smarterclayton** [comment]
Just allow the status code to be accessed.

On Thu, Oct 20, 2016 at 11:30 AM, Michail Kargakis <notifications@github.com

**Comment by kargakis** [comment]
Assuming there is nothing to do here re protobuf, I'm closing
