### ISSUE TITLE
kubedns should not use Kubernetes service as the ready signal

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#35140]
From [current kubedns codes](https://github.com/kubernetes/kubernetes/blob/master/pkg/dns/dns.go#L153-L162). The `kubedns` starts with running services and endpoints store controller, and setups the ready signal once `Get(kubernetesSvcName)` returns.

Although store controllers will start with `list`ing all objects and sync, there is no guarantee that all existing services/endpoints can get fully updated into treecache at the point `Get(kubernetesSvcName)` returns. Especially when scaling out `kubedns` for a huge cluster that has lots of services/endpoints. Ramping up the new `kubedns` may take a while, and those unready dns servers may got exposed ahead because `Get(kubernetesSvcName)` returns quickly.

@bowei @bprashanth @thockin

**Comment by bprashanth** [comment]
Yeah we can list all services, populate records, setup the watch for updates, then open up for business.

**Comment by bprashanth** [comment]
Maybe we can fit this into 1.5? We recently had someone scale down a cluster and experience a mini crisis because their new replicas ended up hitting the new kube-dns pods and crashing when lookup failed

**Comment by MrHohn** [comment]
> Yeah we can list all services, populate records, setup the watch for updates, then open up for business.

Sounds good, I can take a look at this.

**Comment by thockin** [comment]
How do you know you have *all* ?  what does *all* mean?

**Comment by bprashanth** [comment]
One list from apiserver and populate dns tree cache. 

Meaning if I have 3 dns endpoints: 
* nginx pod look up foo.svc, hits ep1, gets records
* ep1 restarts
* nginx pod look up foo.svc

That last lookup should not hit ep1 if foo.svc is going to fail.
