### ISSUE TITLE
Node controller shouldn't hard delete pods on partitioned nodes

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#35145]
Background https://github.com/kubernetes/kubernetes/issues/31762
Proposal  https://github.com/kubernetes/kubernetes/pull/34160 
Proposed actions for 1.5 https://github.com/kubernetes/kubernetes/pull/34160#issuecomment-254764348

At a high level: 

Today: 
- Partition 
  - nodecontroller "deletes" (sets deletionTimestamp)
  - kubelet doesn't see this
- Partition lasts for 5m
  - nodecontroller "hard deletes" (kubectl delete --grace-period=0)
- Partition recovers
  - kubelet sees delete  
  - kubelet sends sigkill

In 1.5:
- Partition 
  - nodecontroller "deletes" (sets deletionTimestamp)
  - kubelet doesn't see this
- Partition lasts for 5m
  - nothing happens
- Parition recovers
  - kubelet sees deletionTimestamp  
  - kubelet sends sigterm, waits terminationGrace, sends sigkill
  - kubelet "hard deletes" (kubectl delete --grace-period=0)

If you're responsible for a controller, think about the implications and bring up any objections.

For example, replica-set/tion controller treats deletionTimestamp as an effective delete, and eagerly creates a replacement. Creating a replacement daemon on a partitioned node isn't going to help anyway. And so on...

@smarterclayton @foxish @erictune @janetkuo @kubernetes/sig-api-machinery @kubernetes/goog-control-plane  (sorry for the wide cc trying to get all controller owners)

**Comment by wojtek-t** [comment]
@gmarek

**Comment by gmarek** [comment]
From NC perspective it's a trivial change, so it's more related to all other controllers than to NC.

I'd rather not do it for 1.5, as we're introducing taints/tolerations as a way to handle Pod evictions. Doing both those things will increase the probability of a serious bug. If we want to pursue this we'd need to figure out a good story for on-prem clusters when the Node will never come back (it can also happen in cloud if a VM is so badly broken, that users decides to delete it). OTOH in 1.6 timeframe evictions will be done using taint/toleration mechanism, so if it's only for PetSets PetSetController may just add infinite toleration for NodeNotReady/NodeUnresponsive taints.

cc @davidopp

**Comment by smarterclayton** [comment]
We can't move pet sets to beta without this change, and if the proposal is accepted I think the general pod safety issue is more important to general users of kube than taints and tolerations in specific.

**Comment by smarterclayton** [comment]
I don't think eviction has anything to do with hard deletion.  The decision
on whether to evict sends the delete signal.  Hard deletion has no
intersection with NodeUnresponsive.

But these are all things that should be discussed on the proposal, not here
(if you're disagreeing that force pod deletion should not be done by the
node controller).

**Comment by gmarek** [comment]
I don't care about NC, I strongly believe that *something* on master should be doing hard deletions. I'm not sure why this issue was created if not to discuss this, but sure - it should be discussed on the original proposal. I'll probably won't have time to read it through though - I'll be happy if @thockin or @davidopp will be OK with this change.

**Comment by davidopp** [comment]
I gave up following the original discussion because it got too long. I'll schedule an in-person meeting with @bprashanth to try to extract the important bits. I share @gmarek 's concern about making additional changes to NodeController in 1.5. We already have one PR out for review that makes large changes for NodeController.

**Comment by foxish** [comment]
The change proposed to the NC would essentially be to turn all the force deletions of pods to graceful ones. Each of those cases that currently exist are listed in https://github.com/kubernetes/kubernetes/pull/34160#issuecomment-254384363.

**Comment by bprashanth** [comment]
The change should be easy to make and is mostly in line with the philosophy that hard deletion by an automated system is considered harmful. 

> If we want to pursue this we'd need to figure out a good story for on-prem clusters when the Node will never come back (it can also happen in cloud if a VM is so badly broken, that users decides to delete it).

The solution is: some controller (autoscaler, human) deletes the node (either in cloudprovider or in kubernetes), or human/custom-controller deletes pods with --grace-period=0.

**Comment by bprashanth** [comment]
Implementation aside: I think it's always better to put safety first. Controllers like RC can take the "unsafe" decision. Today it's the opposite. 

Even with forgiveness, safety would take precedence if there were a partition. The nodecontroller would only set deletionTimestamp. The RC would create a replacement anyway.

**Comment by smarterclayton** [comment]
The important delta here is that in a heavily partitioned clusters, you might end up with a lot more pods that are waiting for deletion - say your partition threshold is 50% - you could end up with 50% more pods than 1.4 (the replacements and the pending deletions).  The admin has to decide when to resolve partition anyway - if they delete the node (as per the proposal) then pod GC will clean up the pods.  If the admin doesn't resolve the partition, the system is strictly more safe than 1.4 (we don't pretend that the nodes that were partitioned were cleanly terminated).

**Comment by bprashanth** [comment]
> I'm not sure why this issue was created if not to discuss this, but sure

This is a PSA to all invested parties so there are no surprises, i.e:

> If you're responsible for a controller, think about the implications and bring up any objections.
For example, replica-set/tion controller treats deletionTimestamp as an effective delete, and eagerly creates a replacement. Creating a replacement daemon on a partitioned node isn't going to help anyway. And so on...

We have some 20 controllers in tree, I think they should all be OK.

**Comment by gmarek** [comment]
I'm not worried about bugs in implementation - it indeed should be simple enough, I'm worried about semantic changes. Only tricky part of the implementation would be adding a flag-gate to his behavior, which would mean having 4 different code paths (cross product of using/not using taints and doing/not doing hard deletions).

**Comment by smarterclayton** [comment]
I'm not currently assuming we will flag gate hard delete.  It can lead to
split brain, and it has the potential for data loss on a cluster.

On Oct 19, 2016, at 6:19 PM, Marek Grabowski <notifications@github.com>
wrote:

I'm not worried about bugs in implementation - it indeed should be simple
enough, I'm worried about semantic changes. Only tricky part of the
implementation would be adding a flag-gate to his behavior, which would
mean having 4 different code paths (cross product of using/not using taints
and doing/not doing hard deletions).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/35145#issuecomment-254957601>,
or mute the thread

**Comment by davidopp** [comment]
> Today:
>
> Partition
> - nodecontroller "deletes" (sets deletionTimestamp)

I don't understand this one. Today when a partition starts, the NC sets Ready condition to Unknown. It doesn't delete anything.

> - kubelet doesn't see this

> Partition lasts for 5m
> - nodecontroller "hard deletes" (kubectl delete --grace-period=0)

Where do you see this? @gmarek can correct me if I'm wrong, but I think [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/controller_utils.go#L76)  is where pods get deleted after 5m, and it uses graceful deletion. There are definitely some cases of force deletion in NC (like terminatePods() and forcefullyDeletePod()) but I do not believe these correspond to the partition scenario.

> Partition recovers
> - kubelet sees delete
> - kubelet sends sigkill

> In 1.5:
>
> Partition
> - nodecontroller "deletes" (sets deletionTimestamp)

I don't understand this. What you're describing implies that one missed heartbeat from a node should trigger eviction of all pods on a node. This seems way too aggressive. The reason for the 5m was to allow for network hiccups (and we get those not just on-prem, but also on cloud providers). I think you want to move this line down to "Partition lasts for 5m" (replacing the line that currently reads "nothing happens"), right?

> - kubelet doesn't see this

> Partition lasts for 5m
> - nothing happens

> Parition recovers
> - kubelet sees deletionTimestamp
> - kubelet sends sigterm, waits terminationGrace, sends sigkill
> - kubelet "hard deletes" (kubectl delete --grace-period=0)

BTW as Marek mentioned, we're going to have taint/toleration/forgiveness-based eviction in 1.5, in addition to continuing to support the current mechanism (selectable by a NC flag). In the newer model I think it would look like this. (Assume all pods have the default 5m "unreachable taint forgiveness" applied to them.)

Partition
- NC applies "unreachable taint"

Partition lasts for 5m
- NC sets deletionTimestamp (the is as before, assuming my correction above is correct)

Partition recovers
- as before

**Comment by bprashanth** [comment]
4 missing hearbeats marks NotReady: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L541
300 missing heartbeats sets deletionTimestamp: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L518
300 missing haeartbeats + gracePeriodSeconds hard deletes: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L425

If the third step doesn't happen, great. 
It's easy enough to force a netsplit and observe it happening, though (as always) it's likely there's something else more subtle at play.

**Comment by davidopp** [comment]
I'm still not understanding what behavior you want. What I'm suggesting is

Partition is detected (miss 4 heartbeats)
* do nothing (under taint-based eviction, place taint)

5 minutes after partition is detected
* send regular (non-force) delete

Is it more than that?

**Comment by bprashanth** [comment]
we're on the same page, I'm saying after 5:30 today (30s default grace) we hard delete, and that needs to not happen.

**Comment by gmarek** [comment]
@davidopp - I think the what @bprashanth aims at is that graceful deletion, which NC respects, is eventually "done" by the NC, not Kubelet. I don't understand what problem we're trying to solve here - the fact that force eviction do happen at all, or that Kubelet will send SIGKILL to the container straight away (IIUC).

**Comment by davidopp** [comment]
> graceful deletion, which NC respects, is eventually "done" by the NC, not Kubelet. 

My understanding is that he wants graceful deletion to be initiated by NC (set deletionTimestamp) but actual deletion only done by kubelet.

**Comment by foxish** [comment]
> My understanding is that he wants graceful deletion to be initiated by NC (set deletionTimestamp) but actual deletion only done by kubelet.

That is correct. 
If we just set the `DeletionTimeStamp` in the NC, something like the RC is already proactive about creating replacement pods. The pod-name is a lock in case of petsets. If the force-deletions from the api-server are only done by the kubelet after confirming termination, we do not end up in a state where due to a network partition, we have two instances of a single pet running.

**Comment by gmarek** [comment]
And what should happen if the Kubelet doesn't come back? NC currently does not delete Nodes if cloud-provider claims they're still there. Plus you didn't really answer my question - what is it that you're trying to accomplish?

**Comment by davidopp** [comment]
@gmarek #34160 answers your question

**Comment by smarterclayton** [comment]
That's the behavior we want, yes (that is described in the other proposal,
although possibly should be described more clearly).

On Sun, Oct 23, 2016 at 9:39 PM, David Oppenheimer <notifications@github.com

**Comment by m1093782566** [comment]
From my understanding, this PR only make sure that Node Controller won't force delete pod. And I think administrator still has the permission of force delete pod by specifying `--grace-period=0` in `kubectl delete pod` command, right?

If user is unable to delete pod using kubeclt, it should be unexpected and possibly something is wrong?

**Comment by foxish** [comment]
It needs the --grace-period=0 and the --force flags IIRC
