### ISSUE TITLE
kubectl should indicate how it is configuring itself

### ISSUE THREAD

**Issue by marun** [kubernetes/kubernetes#35156]
`kubectl` can implicitly configure itself in a number of different ways:
-  `/etc/kubernetes/admin.conf`
- `~/.kube/config`
- `KUBECONFIG` env var
- env vars + token (running in a pod)

When more than one of these sources of configuration are present on a given host, it would be helpful to be able to determine how `kubectl` is configuring itself.   Maybe add a config command (e.g. `config show-source`) or provide output when log verbosity is sufficiently high?

cc: @jbeda

**Comment by marun** [comment]
I also noticed that the usage message for ``kubectl config`` (as of 1.4.3) doesn't mention ``/etc/kubernetes/admin.conf`` or how kubectl will configure itself when running in a pod:

```
The loading order follows these rules:
1. If the --kubeconfig flag is set, then only that file is loaded.  The flag may only be set once and no merging takes place.
2. If $KUBECONFIG environment variable is set, then it is used a list of paths (normal path delimitting rules for your system).  These paths are merged.  When a value is modified, it is modified in the file that defines the stanza.  When a value is created, it is created in the first file that exists.  If no files in the chain exist, then it creates the last file in the list.
3. Otherwise, ${HOME}/.kube/config is used and no merging takes place.
```

Is this deliberate or an oversight?

**Comment by jbeda** [comment]
To be clear, I don't think that kubectl will look for `/etc/kubernetes/admin.conf` by default.  By default `kubectl` will try and connect to the insecure cluster endpoint -- 127.0.0.1:8080.

But the larger point still stands -- kubeconfig loading is a maze of twisty passages and providing some sort of debugging for users would be very very helpful.
