### ISSUE TITLE
server and client should have their own instances of APIRegistrationManager

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#35162]
Now that we have APIRegistrationManager, we should update the server and client to instantiate their own instances of APIRegistrationManager and register the APIs independently.

Currently, we use DefaultAPIRegistrationManager everywhere. As a result, if the client depends on an API, it is included in the server automatically.

https://github.com/kubernetes/kubernetes/issues/26675 is an example instance of the problem that this leads to. Calling `registered.AllPreferredGroupVersions()` in api server returns all group versions including the ones that client depends on. There should be a way to get all group versions included only in the server.

cc @kubernetes/sig-cluster-federation @caesarxuchao

**Comment by liggitt** [comment]
@kubernetes/sig-api-machinery

**Comment by nikhiljindal** [comment]
Oops I wanted to cc @kubernetes/sig-api-machinery instead of cluster-federation :)

**Comment by smarterclayton** [comment]
On the server there isn't a need for "all registered group versions" really.  Each group should be independent anyway, and each group version practically ends up being independent.

There should be no server code that looks at api.Scheme soon.

**Comment by deads2k** [comment]
> On the server there isn't a need for "all registered group versions" really. Each group should be independent anyway, and each group version practically ends up being independent.
> 
> There should be no server code that looks at api.Scheme soon.

Also, since a server knows its source and destination, why do we care if "extra" group versions are registered.  API enablement happens separately.

**Comment by liggitt** [comment]
agree, registration of extra groups should not matter.

**Comment by nikhiljindal** [comment]
It matters for the group versions that can be enabled on the server.
For ex: if I try to bring up federation-apiserver with `--runtime-config="badgroup/badversion"` it will fail. But if I try the same thing with `--runtime-config="batch/v1"`, the server will come up fine. That is because server assumes that batch/v1 is a valid api group, even though it is not. It is a valid api group for the client, but there is no way to make that distinction today.

**Comment by nikhiljindal** [comment]
I see that the list of registered api group versions is also used to determine the default value of storage version flag on apiserver: https://github.com/kubernetes/kubernetes/blob/8290366a8f523fae8eef44b2289db1f5bf8a2f0b/pkg/genericapiserver/options/server_run_options.go#L133.

Hence, the default value of `--storage-version` on federation-apiserver includes kubernetes APIs that are not part of federation-apiserver, but are part of the client.

Maybe we should use the list of "enabled" group versions there instead of list of "registered" group versions?

**Comment by liggitt** [comment]
Right, that speaks to a lack of validation on which registered versions are allowed to be enabled for the server. I wouldn't change the registration path, just the enablement one.

**Comment by nikhiljindal** [comment]
> Right, that speaks to a lack of validation on which registered versions are allowed to be enabled for the server. I wouldn't change the registration path, just the enablement one.

Great! So we agree that we need some mechanism to determine if a group version can be enabled on server and whether it can be enabled on the client.

The proposal here is to keep a separate registered group version list. group versions registered in servers list of registered group versions can be enabled on server and group versions registered in clients list of registered group versions can be enabled on the client.

**Comment by liggitt** [comment]
Registration isn't appropriate for that. Enablement validation is

**Comment by liggitt** [comment]
Also, storage enablement and rest API enablement are not the same thing. For example, Jobs are addressable from two REST API groups, so even if extensions is not surfaced as a REST API, the storage destination for it might need to be if batch jobs were being read from their original home in extensions storage

**Comment by nikhiljindal** [comment]
> Registration isn't appropriate for that. Enablement validation is

Sorry can you elaborate on that. Is it wrong to use the list of registered group versions to validate what group versions can be enabled?

> Also, storage enablement and rest API enablement are not the same thing. 

So we should have 2 lists of group versions: one that can be enabled in storage and one that can be enabled in the API?
Client does not care about storage versions.

**Comment by liggitt** [comment]
Server enablement should always be a subset of known (registered) groupversions. Having separate registration lists allows for the possibility of disjoint registration sets (a server serves a groupversion a client running in the server process doesn't know about), which is nonsensical.

**Comment by lavalamp** [comment]
This is why I added the "announced" package-- announced APIs can be shared.

Agree that NO ONE should be referencing api.Scheme directly. Each binary should construct their scheme and it should be plumbed through all of the appropriate factories, etc...
