### ISSUE TITLE
Decide semantics of predicate precomputations.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#35168]
Problem

Some predicates may need precomputations or "preconditions" to be met before they can run.  
- As of now, those preconditions may or may not be gauranteed to exist in the `predicateMetadata` struct.
- Some of those predicates may be able to bootstrap some of their own data (by redoing a query, if the predicate metadata  is incomplete).  

Solution

We should decide wether (1) predicates should try to create data which is precomputed and (2) if so, what the best way to do this is which is scalable and doesnt lead to duplication of error handling/querying. 

Two possible solutions:
- make any predicate's precompute function (as of now, really we only have one - but there may be others) stand alone - so that it can be called outside of the standard precomputation  steps provided by the scheduler framework (this might help in corner cases - i.e. if a query fails randomly, the predicate has a retry built-in - but it will lead to duplication of logic).
- Each predicates precompute function stays encapsulated, and predicates simply have preconditions of checking for missing data (this is simpler to maintain from the code perspective, but might be some corner cases where it hurts us).  Once we decide, we would update the predicates_test functions where necessary to include test cases for when precomputation is enabled. 

@wojtek-t Suggesting this as a follow on to #33763 .

**Comment by jayunit100** [comment]
As of now, i think we leaned towards 
- putting the precomputations as attachments to the predicates, 
- re-running precomputations inside the predicate evaluation if there is missing info


1) is that the standard for all predicates
2) can that be abstracted into a predicate interface of some sort?

**Comment by wojtek-t** [comment]
Re 1) - yes, I believe this is what we are doing for all predicates now.
