### ISSUE TITLE
azure disk: always times out waiting for Unmount

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#35176]
**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): Ubuntu Xenial
- **Kernel** (e.g. `uname -a`): Whatever is in Xenial today
- **Install tools**: Custom
- **Others**: N/a

**What happened**:
Azure Disk seems to never unmount correctly and always times out. KCM then comes along and forcibly detaches after the maxWaitForUnmountDuration

**What you expected to happen**:
It to successfully unmount and detach in a much smaller amount of time.

**How to reproduce it** (as minimally and precisely as possible):
1. Start a pod with an Azure Disk
2. Observe that it starts reasonably quickly...
3. Kill the Pod
4. Wait
5. Wait more
6. Eventually it times out: `I1020 06:34:49.959484       1 reconciler.go:138] Started DetachVolume for volume "kubernetes.io/azure-disk/KubeTestDisk0" from node "k8s-agentpool2-26612993-1". This volume is not safe to detach, but maxWaitForUnmountDuration 6m0s expired, force detaching`

**Anything else do we need to know**:
n/a

cc: @rootfs

**Comment by rootfs** [comment]
@colemickens do you see any `DeviceOpened` failure in the kubelet log?

**Comment by brendandburns** [comment]
Closing this as obsolete. Please re-open if it re-occurs.
