### ISSUE TITLE
Upgrade Path When PetSets are renamed

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#35182]
We are going to need to assess an upgrade to transition to the new object.

I do not believe that because of a name change, because of optics, we should ask users of this product to have to migrate data between datastores. This can often fail and cost a great deal of time and money.

Deleting a PetSet may not be acceptable to users of this product.

**Comment by chrislovecnm** [comment]
cc: @smarterclayton @bprashanth @erictune - you can assign me to help to flush this out, but it is going to take a guru of the feature formally know as PetSets to implement.

**Comment by bprashanth** [comment]
We've already established the risk of relying on alpha objects: https://github.com/kubernetes/kubernetes/blob/release-1.4/docs/devel/api_changes.md#alpha-beta-and-stable-versions

I'm largely in agreement with: https://github.com/kubernetes/kubernetes/issues/27430#issuecomment-254994122, https://github.com/kubernetes/kubernetes/issues/27430#issuecomment-255030366

If you just upgrade blindly, the old pods should still exist (they're normal pods/pvs/dns records etc), but I can't promise this will get thoroughly tested.

**Comment by chrislovecnm** [comment]
@bprashanth I understand, but when we are talking big data, this can get evil really fast.  I am not saying that this will be easy, or "officially supported", but we need to come up with a solution that is clean.

**Comment by smarterclayton** [comment]
I don't think the machinery is so bad that we can't consider it.  We should at least have a discussion about it in the next sig-apps.

**Comment by chrislovecnm** [comment]
@smarterclayton yes, thank-you.  Who is the PM who would manage the priority on this?

**Comment by bprashanth** [comment]
Your upgrade script is basically: 
```shell
$ kubectl delete petset -f petset.yaml --cascade=false
$ upgrade.sh master 1.5
$ kubectl create -f statefulset.yaml
```

Autoconverting still seems like a weird choice of upgrade strategy. There is comfort in alpha meaning "things might break", take that away and we might as well go straight to beta.

**Comment by chrislovecnm** [comment]
One word for you, SLA.  I have 5 9's now, and probably moving to 6 or 7.  I cannot live with the downtime.  There are business and optics risks with this are a really really big.

**Comment by erictune** [comment]
We can make the upgrade script be something like:
```shell
$ kubectl delete -f petset.yaml --cascade=false
$ upgrade.sh master 1.5
$ upgrade-kubectl.sh
$ cat petset.yaml | convert_petset_to_stateful_set.sh | kubectl create -f -
```

Who test this approach and work on this tool?

**Comment by erictune** [comment]
@chrislovecnm 

In terms of availability:  The pods of the PetSet will not stop running during this procedure, unless there is a node failure.  If there is a node failure during the, say, hour that this procedure takes, then a replacement pod won't be made.  What that means in terms of application availability depending on your app. If it can tolerate one pod failure and you get one pod failure, you should be good.

**Comment by erictune** [comment]
@janetkuo

**Comment by janetkuo** [comment]
I ran a simple test to create a petset, write some data to its pets, delete the petset (--cascade=false), create a petset to adopt those pets. It worked well.

**Comment by chrislovecnm** [comment]
Well crap that was easy.  We must be making some awesome software or something :)

**Comment by janetkuo** [comment]
Need to keep an eye on #32538 (upgrading masters doesn't upgrade kubectl), since older kubectl will not be compatible with renamed [new PetSet] API.

**Comment by chrislovecnm** [comment]
@janetkuo whatever the case we need this documented for beta.  Also need upgrades documented.  @bprashanth does we have an issue open for beta docs ... cause dude you write them amazingly.

**Comment by chrislovecnm** [comment]
Btw guys ... appreciated

**Comment by janetkuo** [comment]
One may not need to delete the PetSet before master upgrade. The upgraded master would just ignore it, and therefore one can still rollback the master upgrade if needed. StatefulSets will adopt pets (perhaps we shouldn't call it pet anymore) and everything will work like before the upgrade.

**Comment by liggitt** [comment]
Latent resources like that in etcd that aren't cleaned up would make me nervous. I'd delete them if tests show that can be done without disrupting

**Comment by bgrant0607** [comment]
@chrislovecnm I wasn't trying to change your priorities.

**Comment by jimmycuadra** [comment]
I'm also very happy to help with any grunt work needed to make this transition smoothly for everyone. It's my fault it's needed, after all. :} It'd be crappy to ask for a change but not help with any of the work it creates.

**Comment by chrislovecnm** [comment]
@bgrant0607 lol we are good

**Comment by erictune** [comment]
@jimmycuadra thanks for the offer of support.
Do you have cluster that runs actual petSets and would you be willing to test the upgrade procedure?

**Comment by chrislovecnm** [comment]
@erictune how do we write e2e tests for this?

**Comment by jimmycuadra** [comment]
@erictune We hadn't used PetSets at my company yet, but I can create some to help test. How would we simulate the change without actually upgrading the cluster? I'm also happy to test locally with a minikube or something.

**Comment by chrislovecnm** [comment]
@jimmycuadra sorry they need to be tested with a multiple zone cluster, sorry only production grade testing with cloud provisioned PVCs is a valid test case.

**Comment by janetkuo** [comment]
I created a doc for this. PTAL https://github.com/kubernetes/kubernetes.github.io/pull/1704

**Comment by bgrant0607** [comment]
This is done
