### ISSUE TITLE
kubadm support/document multiple master init/join steps

### ISSUE THREAD

**Issue by bogdando** [kubernetes/kubernetes#35188]
FEATURE REQUEST:
What is steps to bootstrap a K8s cluster with two masters? Please document that.
If it is yet possible, this should be supported.

**Comment by rsokolkov** [comment]
Any updates here?

**Comment by roberthbailey** [comment]
Please re-open this feature request in the [kubeadm repository](https://github.com/kubernetes/kubeadm).
