### ISSUE TITLE
Unable to use commas in --from-literal when creating secrets

### ISSUE THREAD

**Issue by SamiHiltunen** [kubernetes/kubernetes#35185]
Same issue as in #27454 but for secrets. It is not currently possible the use commas in `--from-literal` value when creating secrets.

Failing example command:
`kubectl create secret generic service-credentials --from-literal="password=h!ghly,Complic@ted"`
Output: 
`error: invalid literal source Complicated, expected key=value`

We most likely want the same behavior here as with the config maps, I'll have pull request up soon after.

**Comment by pwittrock** [comment]
@fabianofranz This something you want to look at?

**Comment by fabianofranz** [comment]
@pwittrock on it.

**Comment by fabianofranz** [comment]
Actually @SamiHiltunen already has it covered.  ;)

**Comment by jacobcabantomski-ct** [comment]
I'm also encountering this issue when using `from-literal` with a mongo uri with the same comma issue.

`--from-literal=foo.mongo_db.bar=mongodb://user:pass@mongo-1:27017,mongo-2:27017/database?poolSize=2&replicaSet=replicas`

Errors with:

`error: invalid literal source mongo-2:27017, expected key=value`

Version Info:
```
Client Version:version.Info{  
   Major:"1",
   Minor:"4",
   GitVersion:"v1.4.6",
   GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6",
   GitTreeState:"clean",
   BuildDate:"2016-11-12T05:22:15Z",
   GoVersion:"go1.7.1",
   Compiler:"gc",
   Platform:"darwin/amd64"
}Server Version:version.Info{  
   Major:"1",
   Minor:"4",
   GitVersion:"v1.4.7",
   GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0",
   GitTreeState:"clean",
   BuildDate:"2016-12-10T04:43:42Z",
   GoVersion:"go1.6.3",
   Compiler:"gc",
   Platform:"linux/amd64"
}
```
