### ISSUE TITLE
Disk space monitoring

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#3518]
We should like to be able to efficiently measure and report the disk space usage of EmptyDirs, maybe HostDirs, and any other volume types that are "local" and support it.  This would allow isolating pods with runaway disk usage and making good scheduling decisions.  

Docker issue https://github.com/docker/docker/issues/471 has a bunch of ideas on how to do that.
Also, @saad-ali just mentioned in #2630 that, with docker/libcontainer#322, docker containers now allow specifying AdditionalGroups.  This might also open up some possibilities around group quota.

Falls under: https://github.com/GoogleCloudPlatform/kubernetes/issues/442

**Comment by thockin** [comment]
Part of the push for additional groups was exactly this.

**Comment by mikedanese** [comment]
cc @madhusudancs

**Comment by timothysc** [comment]
@derekwaynecarr Can we close this out yet?

**Comment by timothysc** [comment]
@vishh @derekwaynecarr @dchen1107 - imo this issue should be closed now.
