### ISSUE TITLE
Disabling standard output for container logging on GCP

### ISSUE THREAD

**Issue by hach-que** [kubernetes/kubernetes#35195]
**Is this a request for help?** No

**What keywords did you search in Kubernetes issues before filing this one?** Logging

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

With the announcement of the new Stackdriver pricing, it's important to be able to reduce the amount of logs that Kubernetes automatically ships to Stackdriver Logging, without requiring changes to applications.

Right now collectively my cluster is logging around about 100GB per month, and I have a cluster in both a production and development account.

I want to be able to disable all standard output (while keeping standard error) from containers that I'm running on Google Container Engine.  I still need to keep standard error so that I can view errors that occur before application startup.  There's currently no way to modify an existing Google Container Engine cluster to disable logging entirely.

Alternatively, if this isn't something that the Kubernetes developers want to pursue, it'd be useful to have aggregate statistics on how much log data a container has emitted over the last time period (say day or 7 days).  This would allow developers to identify noisy containers and take actions to reduce costs.

**Comment by schasse** [comment]
+1

**Comment by crassirostris** [comment]
@hach-que

> I want to be able to disable all standard output (while keeping standard error) from containers that I'm running on Google Container Engine. I still need to keep standard error so that I can view errors that occur before application startup.

I don't think it's possible or makes any sense. [Changing the logging agent configuration](https://kubernetes.io/docs/tasks/debug-application-cluster/logging-stackdriver#configuring-stackdriver-logging-agents) to pick up only stderr seems more reasonable

> There's currently no way to modify an existing Google Container Engine cluster to disable logging entirely

It's going to be available not very long time from now

> Alternatively, if this isn't something that the Kubernetes developers want to pursue, it'd be useful to have aggregate statistics on how much log data a container has emitted over the last time period (say day or 7 days). This would allow developers to identify noisy containers and take actions to reduce costs

I don't think the data is available in terms of metrics anywhere right now, but that may change in the future, with the full introduction of CRI

**Comment by hach-que** [comment]
The original driver for this was Stackdriver logging, and at the time there was no exclusion system for Stackdriver.

Now that Stackdriver exclusions can be used to reduce costs, this issue can be closed.
