### ISSUE TITLE
kubeadm param to support custom container images for kube-apiserver et al

### ISSUE THREAD

**Issue by bogdando** [kubernetes/kubernetes#35190]
FEATURE REQUEST:
Allow users to specify custom images, like hyperkube for the kubeadm init.
By default it uses the gcr.io/google_containers/kube-controller-manager-amd64:v1.4.0 and so on.

**Comment by bogdando** [comment]
It seems there is a hyperkube_image env var to cover that. But is it documented?

**Comment by jihoon-seo** [comment]
These links might be helpful:

https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#custom-images

https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1#hdr-Kubeadm_init_configuration_types
