### ISSUE TITLE
Allocating memory in apiserver from time to time takes a lot

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#35198]
Background: I'm trying to debug long api-calls of "LIST nodes".

Since most of the calls listing nodes don't set any selector, as an optimization for this case yesterday I added explicit memory allocation for that case in cacher in:
https://github.com/kubernetes/kubernetes/pull/35125

As a side effect, in our traces we see how long it takes.

And indeed - in large clusters this memory allocation is huge majority (i.e. ~90%) of the processing of those calls in Cacher. 
In particular, all long calls have traces like this:

```
I1020 10:13:44.825802    3611 trace.go:61] Trace "cacher *api.Node: List" (started 2016-10-20 10:13:43.980532542 +0000 UTC):
[2.576µs] [2.576µs] Ready
[13.727µs] [11.151µs] watchCache locked acquired
[14.637µs] [910ns] watchCache fresh enough
[2.103842ms] [2.089205ms] Listed 4000 items from cache
[794.949876ms] [792.846034ms] Resized result
[845.222829ms] [50.272953ms] Filtered 4000 items
[845.234997ms] [12.168µs] END
```

That basically means that allocating a slice for 4000 nodes takes 792ms.

Is there anything we can do to make this faster:
https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/cacher.go#L393

@xiang90 @hongchaodeng @smarterclayton @timothysc @gmarek

**Comment by wojtek-t** [comment]
@bradfitz - if you have any suggestions

**Comment by bradfitz** [comment]
That seems very unlikely, even with an old version of Go. But what version of Go? And how big is the heap? Sure those `pred.Label.Empty() && pred.Field.Empty()` calls aren't doing any work?

**Comment by wojtek-t** [comment]
It was in Go 1.6 (I think 1.6.3 but with this I'm not 100% sure). The heap was pretty big - IIRC, the total memory usage was 15GB -20GB or sth like that.

Regarding those "Empty()", it's pretty trivial:
https://github.com/kubernetes/kubernetes/blob/master/pkg/labels/selector.go#L233

**Comment by timothysc** [comment]
It's entirely possible that your allocation is triggering a GC event.

**Comment by bradfitz** [comment]
If it was Go 1.6 with such a large heap, that's plausible.

It'd be better with Go 1.7, but if you're not on that yet, Go 1.8 will be even better, bringing 10~100μs heaps, regardless of heap size.

**Comment by timothysc** [comment]
Welp this is why buffer pooling still exists.  What's old is new ;-)

**Comment by wojtek-t** [comment]
We migrated to Go 1.7 few weeks ago, and I think it's better now. If you're saying that with 1.8 it would be even better, that's great.
