### ISSUE TITLE
Node goes away e2e test

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#3520]
Write an e2e test that has a pod and a replication controller and multiple nodes.  Delete the node that the pod is on, and see that the absence of the pod/node is detected by the replication controller, and that a replacement pod is created.

**Comment by zmerlynn** [comment]
The follow up to this is what happens when the node reboots and tries to
rejoin. :) Node on fire is "easy".

**Comment by erictune** [comment]
This could also be accomplished in an integration test.

**Comment by satnam6502** [comment]
As a variation of my serve_hostnames soak/reliability test I intend to make a "cauldron" version of it which uses a replication controller and which every so often kills or add pods and checks to make sure the expected number of pods are up over a given window. Would that meet the requirements of the issue?

**Comment by erictune** [comment]
@satnam6502 That test would certainly be better than nothing.  

I'm of the opinion that focused, standalone e2e tests have a lot of value too, and if it were up to me, I'd wrote one of those before embedding the test into a test with a larger scope (reliability).  Basically, I think each test should have a purpose which can be described in like one sentence, without use of conjunctions.  But that's just my opinion.

**Comment by satnam6502** [comment]
Agreed, coherent focused e2e tests are of great value. I can take this one unless someone else is super keen to do it. Back to back meetings today in Seattle but I expect I can have it done on Tuesday/Wednesday if that's not too late for you.

**Comment by erictune** [comment]
not super keen.

**Comment by satnam6502** [comment]
Un-assiging temporarily while I look at issues with our network e2e test. No worries if someone else wants to pick this up before I can get back to it.

**Comment by gmarek** [comment]
@jszczepkowski - does your restart tests cover this?

**Comment by jszczepkowski** [comment]
This exact test case is covered by Nodes.Resize and Nodes.Network. Closing
