### ISSUE TITLE
kubelet leaking http2serverConn.readFrames goroutines in the gke soak clusters

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#35207]
Forking from https://github.com/kubernetes/kubernetes/issues/30175#issuecomment-254983912

In kubernetes-soak-continuous-e2e-gke, the kubelet memory usage continued going up 
I checked one of the nodes `gke-jenkins-e2e-default-pool-5cd34bf0-vuqp`, and there were over 4000 goroutines (and increasing) in kubelet.
The same applies to the  kubernetes-soak-continuous-e2e-gke-gci nodes.

The version of kubelet on the node: 
Kubernetes v1.5.0-alpha.1.483+67732d7383506

Relevant goroutines:

```
2132 @ 0x430853 0x43f7a7 0x43ed02 0x6a57bc 0x6a24e5 0x6ea95e 0x6d1a27 0x4618e1
#       0x6a57bc        net/http.(*http2serverConn).serve+0xedc         /usr/local/go/src/net/http/h2_bundle.go:3163
#       0x6a24e5        net/http.(*http2Server).ServeConn+0xa45         /usr/local/go/src/net/http/h2_bundle.go:2711
#       0x6ea95e        net/http.http2ConfigureServer.func1+0xae        /usr/local/go/src/net/http/h2_bundle.go:2603
#       0x6d1a27        net/http.(*conn).serve+0x777                    /usr/local/go/src/net/http/server.go:1414
2132 @ 0x430853 0x42b1fe 0x42a6c0 0x646b2a 0x646b96 0x6489ea 0x65de24 0x60417c 0x604a41 0x609797 0x4c1cc6 0x4c1e02 0x694275 0x695429 0x6a425a 0x4618e1
#       0x42a6c0        net.runtime_pollWait+0x60                       /usr/local/go/src/runtime/netpoll.go:160
#       0x646b2a        net.(*pollDesc).Wait+0x3a                       /usr/local/go/src/net/fd_poll_runtime.go:73
#       0x646b96        net.(*pollDesc).WaitRead+0x36                   /usr/local/go/src/net/fd_poll_runtime.go:78
#       0x6489ea        net.(*netFD).Read+0x23a                         /usr/local/go/src/net/fd_unix.go:250
#       0x65de24        net.(*conn).Read+0xe4                           /usr/local/go/src/net/net.go:172
#       0x60417c        crypto/tls.(*block).readFromUntil+0xcc          /usr/local/go/src/crypto/tls/conn.go:460
#       0x604a41        crypto/tls.(*Conn).readRecord+0x2d1             /usr/local/go/src/crypto/tls/conn.go:562
#       0x609797        crypto/tls.(*Conn).Read+0x167                   /usr/local/go/src/crypto/tls/conn.go:939
#       0x4c1cc6        io.ReadAtLeast+0xe6                             /usr/local/go/src/io/io.go:297
#       0x4c1e02        io.ReadFull+0x62                                /usr/local/go/src/io/io.go:315
#       0x694275        net/http.http2readFrameHeader+0xa5              /usr/local/go/src/net/http/h2_bundle.go:715
#       0x695429        net/http.(*http2Framer).ReadFrame+0xe9          /usr/local/go/src/net/http/h2_bundle.go:906
#       0x6a425a        net/http.(*http2serverConn).readFrames+0x5a     /usr/local/go/src/net/http/h2_bundle.go:3067
```

The cluster was deployed on 10/18. Not sure if this has already been fixed. 
/cc a couple of people who may have more ideas. @timothysc @gmarek @wojtek-t 
/cc @kubernetes/sig-node

**Comment by wojtek-t** [comment]
@smarterclayton

**Comment by timothysc** [comment]
> Not sure if this has already been fixed.

Nope this is new.

**Comment by timothysc** [comment]
Just for clarity, that flake was occurring since Aug 6th which was well before we enabled http2. 

I wonder if there is some issue inside of the client tooling.  /cc @kubernetes/sig-api-machinery

**Comment by yujuhong** [comment]
> Just for clarity, that flake was occurring since Aug 6th which was well before we enabled http2.

@timothysc the test was flaking since Aug 6th because of some other reasons (docker leaking memory, a known issue). I didn't trace all the test failures, but I believe this is relatively recent.

**Comment by smarterclayton** [comment]
Maybe *this* is the TLS deadlock?  :)  Joking.

**Comment by dchen1107** [comment]
@dashpole Could you take a look at this one? 

@yujuhong mentioned that the issue only occur to gke cluster, not gce. I also quickly checked gke 1.4 soaking cluster, and didn't see the same issue. It looks like a new regression. Thanks!

**Comment by dashpole** [comment]
This may be obvious, but:
net/http.(*http2serverConn).serve    calls    net/http.(*http2serverConn).readFrames.  So whatever is leaking goroutines is calling one of (from net/http): 
func (srv *Server) Serve(l net.Listener) error
func Serve(l net.Listener, handler Handler) error
func (srv *Server) ListenAndServe()
func ListenAndServe(addr string, handler Handler) error
func (srv *Server) ListenAndServeTLS(certFile, keyFile string) error
func ListenAndServeTLS(addr, certFile, keyFile string, handler Handler) error

**Comment by dashpole** [comment]
The other stack traces that call one of these functions originate at:
pkg/kubelet/cadvisor/cadvisor_linux.go:148
pkg/kubelet/server/server.go:127
cmd/kubelet/app/server.go:447

**Comment by timstclair** [comment]
Are connections being left open, or only go routines? It wouldn't surprise me if this was related to the streaming functions (exec/attach/port-forward).

**Comment by dashpole** [comment]
Looks like connections are being left open.  We have around 2k goroutines that are in the middle of serve(), and around 2k open connections.  They are all on localhost:10250

**Comment by timstclair** [comment]
Take a look at the API server. If the streaming connections are being left open, there might be a lot of go routines here: https://github.com/kubernetes/kubernetes/blob/c04aec34628c9c9c06d95906bd537a7b1d4ef037/pkg/registry/generic/rest/proxy.go#L184

**Comment by dashpole** [comment]
This is in the API server logs: 

goroutine 14733771 [running]:                                                                                                                                                                                                                 
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc83d6a6000, 0x1f4)                                                                                                                                                                 
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:219 +0xa3                                                                                                                                    
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc83d6a6000, 0x1f4)                                                                                                                                                                  
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:198 +0x2b                                                                                                                                    
k8s.io/kubernetes/pkg/apiserver/metrics.(*responseWriterDelegator).WriteHeader(0xc82849a2d0, 0x1f4)                                                                                                                                           
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:117 +0x4c                                                                                                                      
k8s.io/kubernetes/pkg/apiserver.errorJSONFatal(0x0, 0x0, 0x7f0083cb50a0, 0xc842b71c80, 0x7f0083ab85a0, 0xc84210d150, 0xc834ba46b0)                                                                                                            
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:450 +0x47a                                                                                                                           
k8s.io/kubernetes/pkg/apiserver.writeNegotiated(0x7f0083cb4758, 0xc820ac8bd0, 0x38f3920, 0xa, 0x38be890, 0x7, 0x7f0083ab85a0, 0xc84210d150, 0xc835051960, 0xc9, ...)                                                                          
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:420 +0x3d4                                                                                                                           
k8s.io/kubernetes/pkg/apiserver.write(0xc9, 0x38f3920, 0xa, 0x38be890, 0x7, 0x7f0083cb4758, 0xc820ac8bd0, 0x0, 0x0, 0x7f0083ab85a0, ...)                                                                                                      
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:403 +0xbde                                                                                                                           
k8s.io/kubernetes/pkg/apiserver.createHandler.func1(0xc82849a240, 0xc833f282a0)                                                                                                                                                               
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:421 +0x17b3                                                                                                                        
k8s.io/kubernetes/pkg/apiserver/metrics.InstrumentRouteFunc.func1(0xc82849a240, 0xc833f282a0)                                                                                                                                                 
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:101 +0x25f                                                                                                                     
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc82098be60, 0x7f0083ab84b8, 0xc83d6a6000, 0xc835051960)                                                                                                       
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:272 +0xf30                                                                                                   
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x7f0083ab84b8, 0xc83d6a6000, 0xc835051960)                                                        
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x3e                                                                                                    
net/http.HandlerFunc.ServeHTTP(0xc82116c010, 0x7f0083ab84b8, 0xc83d6a6000, 0xc835051960)                                                                                                                                                      
        /usr/local/go/src/net/http/server.go:1618 +0x3a                                                                                                                                                                                       
net/http.(*ServeMux).ServeHTTP(0xc8209f83c0, 0x7f0083ab84b8, 0xc83d6a6000, 0xc835051960)                                                                                                                                                      
        /usr/local/go/src/net/http/server.go:1910 +0x17d                                                                                                                                                                                      
k8s.io/kubernetes/pkg/apiserver/filters.WithAuthorization.func1(0x7f0083ab84b8, 0xc83d6a6000, 0xc835051960)                                                                                                                                   
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/filters/authorization.go:44 +0x185                                                                                                                
net/http.HandlerFunc.ServeHTTP(0xc8209b3a00, 0x7f0083ab84b8, 0xc83d6a6000, 0xc835051960)                                                                                                                                                      
        /usr/local/go/src/net/http/server.go:1618 +0x3a                                                                                                                                                                                       
k8s.io/kubernetes/pkg/apiserver/filters.WithImpersonation.func1(0x7f0083ab84b8, 0xc83d6a6000, 0xc835051960)                                                                                                                                   
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/filters/impersonation.go:44 +0x2b4                                                                                                                
net/http.HandlerFunc.ServeHTTP(0xc8209b3a40, 0x7f0083ab84b8, 0xc83d6a6000, 0xc835051960)                                                                                                                                                      
        /usr/local/go/src/net/http/server.go:1618 +0x3a                                                                                                                                                                                       
k8s.io/kubernetes/pkg/auth/handlers.WithAuthentication.func1(0x7f0083ab84b8, 0xc83d6a6000, 0xc835051960)                                                                                                                                      
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/auth/handlers/handlers.go:73 +0x2f3                                                                                                                         
net/http.HandlerFunc.ServeHTTP(0xc8209d2910, 0x7f0083ab84b8, 0xc83d6a6000, 0xc835051960)                                                                                                                                                      
        /usr/local/go/src/net/http/server.go:1618 +0x3a                                                                                                                                                                                       
k8s.io/kubernetes/pkg/api.WithRequestContext.func1(0x7f0083ab84b8, 0xc83d6a6000, 0xc835051960)                                                                                                                                                
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:107 +0x157                                                                                                                            
net/http.HandlerFunc.ServeHTTP(0xc8209cfe60, 0x7f0083ab84b8, 0xc83d6a6000, 0xc835051960)                                                                                                                                                      
        /usr/local/go/src/net/http/server.go:1618 +0x3a                                                                                                                                                                                       
k8s.io/kubernetes/pkg/genericapiserver/filters.WithPanicRecovery.func1(0x7f0083ab84b8, 0xc83d6a6000, 0xc835051960)                                                                                                                            
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/panics.go:75 +0x280                                                                                                                
net/http.HandlerFunc.ServeHTTP(0xc8209f8990, 0x7f0083ac2ce8, 0xc84210d138, 0xc835051960)                                                                                                                                                      
        /usr/local/go/src/net/http/server.go:1618 +0x3a                                                                                                                                                                                       
k8s.io/kubernetes/pkg/apiserver/filters.WithRequestInfo.func1(0x7f0083ac2ce8, 0xc84210d138, 0xc835051960)                                                                                                                                     
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/filters/requestinfo.go:45 +0x3cd                                                                                                                  
net/http.HandlerFunc.ServeHTTP(0xc8209f8a20, 0x7f0083ac2ce8, 0xc84210d138, 0xc835051960)                                                                                                                                                      
        /usr/local/go/src/net/http/server.go:1618 +0x3a                                                                                                                                                                                       
k8s.io/kubernetes/pkg/api.WithRequestContext.func1(0x7f0083ac2ce8, 0xc84210d138, 0xc835051960)                                                                                                                                                
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:107 +0x157                                                                                                                            
net/http.HandlerFunc.ServeHTTP(0xc8209cff40, 0x7f0083ac2ce8, 0xc84210d138, 0xc835051960)                                                                                                                                                      
        /usr/local/go/src/net/http/server.go:1618 +0x3a                                                                                                                                                                                       
k8s.io/kubernetes/pkg/genericapiserver/filters.(*timeoutHandler).ServeHTTP.func1(0xc8209cff60, 0x7f0083ac2ca8, 0xc84210d138, 0xc835051960, 0xc833f28240)                                                                                      
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/timeout.go:78 +0x8d                                                                                                                
created by k8s.io/kubernetes/pkg/genericapiserver/filters.(*timeoutHandler).ServeHTTP                                                                                                                                                         
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/timeout.go:80 +0x15b                                                                                                               
                                                                                                                                                                                                                                              
logging error output: "k8s\x00\n\f\n\x02v1\x12\x06Status\x12<\n\x04\n\x00\x12\x00\x12\aFailure\x1a&expected pointer, but got invalid kind\"\x000\xf4\x03\x1a\x00\"\x00"

**Comment by dashpole** [comment]
And I see this one as well.  Both errors seem to occur about every hour or so.
goroutine 14927370 [running]:                                                                                                                                                                                                                 
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc82623a540, 0x1f7)                                                                                                                                                                 
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:219 +0xa3                                                                                                                                    
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc82623a540, 0x1f7)                                                                                                                                                                  
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:198 +0x2b                                                                                                                                    
... ... ... ... ...                                                                                                                                                                                  
net/http.(*initNPNRequest).ServeHTTP(0xc83bedbba0, 0x7f0083ac2c20, 0xc832344388, 0xc8223e0460)                                                                                                                                                
        <autogenerated>:253 +0xb6                                                                                                                                                                                                             
net/http.(Handler).ServeHTTP-fm(0x7f0083ac2c20, 0xc832344388, 0xc8223e0460)                                                                                                                                                                   
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus/http.go:61 +0x50
net/http.(*http2serverConn).runHandler(0xc8427e9b80, 0xc832344388, 0xc8223e0460, 0xc8265efe80)                                                                                                                                                
        /usr/local/go/src/net/http/h2_bundle.go:4060 +0x9f                                                                                                                                                                                    
created by net/http.(*http2serverConn).processHeaderBlockFragment                                                                                                                                                                             
        /usr/local/go/src/net/http/h2_bundle.go:3853 +0x55e                                                                                                                                                                                   
                                                                                                                                                                                                                                              
logging error output: "Error: 'EOF'\nTrying to reach: 'http://10.240.0.4:4194/containers/'"

**Comment by dashpole** [comment]
"""""
logging error output: "Error: 'EOF'\nTrying to reach: 'http://10.180.1.252:80/guestbook.php?cmd=get&key=messages&value='"

**Comment by dashpole** [comment]
@timstclair there are a few lines in the api server log regarding proxy.go:
kube-apiserver.log:274341:E1020 21:35:38.642816       5 proxy.go:172] Error proxying data from client to backend: read tcp 10.240.0.56:443->104.197.45.156:47617: read: connection reset by peer

**Comment by dashpole** [comment]
netstat output includes 2k+ lines like these:
tcp6       0      0 localhost:10250         localhost:56977         ESTABLISHED
tcp6       0      0 localhost:10250         localhost:50801         ESTABLISHED
tcp6       0      0 localhost:10250         localhost:xxxxx         ESTABLISHED

The 10250 port is the Kubelet's default port.
Looking for any logs related to the other ports shows they are all used by healthz calls:
sudo grep -r :50801
kubelet.log-20161020-1476922621:I1019 08:06:50.153796    3719 server.go:968] GET /healthz: (50.055µs) 200 [[curl/7.26.0] 127.0.0.1:50801]
kubelet.log-20161021-1477009021:I1020 17:01:46.192542    3719 server.go:968] GET /healthz: (53.715µs) 200 [[curl/7.26.0] 127.0.0.1:50801]

**Comment by yujuhong** [comment]
Snippet from the kubelet.log on a gke node:
```
Oct 31 19:02:46 gke-jenkins-e2e-default-pool-a7586211-fm1y kubelet[1275]: I1031 19:02:46.230046    1275 server.go:968] GET /healthz: (43.616µs) 200 [[curl/7.50.3] 127.0.0.1:60343]
Oct 31 19:02:56 gke-jenkins-e2e-default-pool-a7586211-fm1y kubelet[1275]: I1031 19:02:56.252475    1275 server.go:968] GET /healthz: (55.685µs) 200 [[curl/7.50.3] 127.0.0.1:60352]
Oct 31 19:03:06 gke-jenkins-e2e-default-pool-a7586211-fm1y kubelet[1275]: I1031 19:03:06.275454    1275 server.go:968] GET /healthz: (40.173µs) 200 [[curl/7.50.3] 127.0.0.1:60365]
Oct 31 19:03:11 gke-jenkins-e2e-default-pool-a7586211-fm1y kubelet[1275]: I1031 19:03:11.352811    1275 server.go:968] GET /healthz: (74.925µs) 200 [[Go-http-client/2.0] 127.0.0.1:60366]
Oct 31 19:03:16 gke-jenkins-e2e-default-pool-a7586211-fm1y kubelet[1275]: I1031 19:03:16.296993    1275 server.go:968] GET /healthz: (33.301µs) 200 [[curl/7.50.3] 127.0.0.1:60447]
Oct 31 19:03:26 gke-jenkins-e2e-default-pool-a7586211-fm1y kubelet[1275]: I1031 19:03:26.319784    1275 server.go:968] GET /healthz: (39.648µs) 200 [[curl/7.50.3] 127.0.0.1:60457]
Oct 31 19:03:36 gke-jenkins-e2e-default-pool-a7586211-fm1y kubelet[1275]: I1031 19:03:36.342802    1275 server.go:968] GET /healthz: (41.933µs) 200 [[curl/7.50.3] 127.0.0.1:60474]
Oct 31 19:03:46 gke-jenkins-e2e-default-pool-a7586211-fm1y kubelet[1275]: I1031 19:03:46.366604    1275 server.go:968] GET /healthz: (44.899µs) 200 [[curl/7.50.3] 127.0.0.1:60554]
Oct 31 19:03:56 gke-jenkins-e2e-default-pool-a7586211-fm1y kubelet[1275]: I1031 19:03:56.390968    1275 server.go:968] GET /healthz: (70.796µs) 200 [[curl/7.50.3] 127.0.0.1:60565]
Oct 31 19:04:06 gke-jenkins-e2e-default-pool-a7586211-fm1y kubelet[1275]: I1031 19:04:06.412098    1275 server.go:968] GET /healthz: (38.524µs) 200 [[curl/7.50.3] 127.0.0.1:60575]
Oct 31 19:04:11 gke-jenkins-e2e-default-pool-a7586211-fm1y kubelet[1275]: I1031 19:04:11.345982    1275 server.go:968] GET /healthz: (71.469µs) 200 [[Go-http-client/2.0] 127.0.0.1:60577]
Oct 31 19:04:16 gke-jenkins-e2e-default-pool-a7586211-fm1y kubelet[1275]: I1031 19:04:16.440308    1275 server.go:968] GET /healthz: (37.7µs) 200 [[curl/7.50.3] 127.0.0.1:60589]
Oct 31 19:04:26 gke-jenkins-e2e-default-pool-a7586211-fm1y kubelet[1275]: I1031 19:04:26.466767    1275 server.go:968] GET /healthz: (32.859µs) 200 [[curl/7.50.3] 127.0.0.1:60600]
Oct 31 19:04:36 gke-jenkins-e2e-default-pool-a7586211-fm1y kubelet[1275]: I1031 19:04:36.488109    1275 server.go:968] GET /healthz: (50.827µs) 200 [[curl/7.50.3] 127.0.0.1:60619]
Oct 31 19:04:46 gke-jenkins-e2e-default-pool-a7586211-fm1y kubelet[1275]: I1031 19:04:46.513197    1275 server.go:968] GET /healthz: (32.524µs) 200 [[curl/7.50.3] 127.0.0.1:60628]
Oct 31 19:04:56 gke-jenkins-e2e-default-pool-a7586211-fm1y kubelet[1275]: I1031 19:04:56.541219    1275 server.go:968] GET /healthz: (38.98µs) 200 [[curl/7.50.3] 127.0.0.1:60639]
Oct 31 19:05:06 gke-jenkins-e2e-default-pool-a7586211-fm1y kubelet[1275]: I1031 19:05:06.567508    1275 server.go:968] GET /healthz: (31.059µs) 200 [[curl/7.50.3] 127.0.0.1:60650]
Oct 31 19:05:11 gke-jenkins-e2e-default-pool-a7586211-fm1y kubelet[1275]: I1031 19:05:11.347127    1275 server.go:968] GET /healthz: (52.77µs) 200 [[Go-http-client/2.0] 127.0.0.1:60652]
```

On a gce node:
```
Oct 31 19:56:01 jenkins-e2e-minion-group-328k kubelet[1257]: I1031 19:56:01.064826    1257 server.go:968] GET /healthz: (42.481µs) 200 [[curl/7.50.3] 127.0.0.1:51188]
Oct 31 19:56:31 jenkins-e2e-minion-group-328k kubelet[1257]: I1031 19:56:31.148359    1257 server.go:968] GET /healthz: (31.555µs) 200 [[curl/7.50.3] 127.0.0.1:51246]
Oct 31 19:57:01 jenkins-e2e-minion-group-328k kubelet[1257]: I1031 19:57:01.218683    1257 server.go:968] GET /healthz: (51.518µs) 200 [[curl/7.50.3] 127.0.0.1:51286]
Oct 31 19:57:31 jenkins-e2e-minion-group-328k kubelet[1257]: I1031 19:57:31.310603    1257 server.go:968] GET /healthz: (33.222µs) 200 [[curl/7.50.3] 127.0.0.1:51324]
Oct 31 19:58:31 jenkins-e2e-minion-group-328k kubelet[1257]: I1031 19:58:31.463936    1257 server.go:968] GET /healthz: (30.741µs) 200 [[curl/7.50.3] 127.0.0.1:51402]
Oct 31 19:59:01 jenkins-e2e-minion-group-328k kubelet[1257]: I1031 19:59:01.566468    1257 server.go:968] GET /healthz: (39.283µs) 200 [[curl/7.50.3] 127.0.0.1:51442]
Oct 31 19:59:31 jenkins-e2e-minion-group-328k kubelet[1257]: I1031 19:59:31.646034    1257 server.go:968] GET /healthz: (49.621µs) 200 [[curl/7.50.3] 127.0.0.1:51480]
```

You can clearly see that there are only `curl` healthz checks (from a monitoring script) on GCE, while there are healthz requests from Go-http-client on GKE. 

As @dashpole mentioned in https://github.com/kubernetes/kubernetes/issues/35207#issuecomment-255460012, there are a lot of open ports on the GKE cluster. All these ports are used by the Go-http-client healthz requests. These ports are used by ssh connections (which probably didn't close the http connections?).

```
$ sudo lsof -i tcp:44086
COMMAND   PID                     USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
sshd    30601 gke-be7fc0ed2d5f52802bcd   67u  inet 23020092      0t0  TCP localhost:44086->localhost:10250 (ESTABLISHED)
```

/cc @kubernetes/goog-gke

**Comment by dchen1107** [comment]
@yujuhong Thanks for looking into this. This is what I suspected since I know managed node team is working on node repairing logic here. @fabioy @maisem could you take a look at this?

**Comment by yujuhong** [comment]
I think this may be caused by the ssh tunnel health check. Similar to kubelet, the apiserver has over 10k goroutines hanging. 
/cc @cjcullen
