### ISSUE TITLE
kubelet failed to create "/system" cgroup

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#35214]
On a debian-based containervm node, kubelet no long creates the "/system" cgroup and moves processes into it.

From kubelet.log:

```
W1020 16:16:51.129436    3552 container_manager_linux.go:491] [ContainerManager] Failed to ensure state of "/system": [failed to list PIDs for root: open cgroup.procs: no such file or directory, ran out of attempts to create system containers "/system"]
```

/cc @kubernetes/sig-node

**Comment by yujuhong** [comment]
By the way, we have poor to no test coverage on *features* like this.

**Comment by derekwaynecarr** [comment]
isnt that running systemd?  you shouldn't do any of this anymore on systemd nodes.

**Comment by yujuhong** [comment]
@derekwaynecarr there are two bugs (I didn't include enough information in the original issue):
 1. From what I observed, kubelet still tries to create this on the new GCI image (with non-init systemd), and fails repeatedly. Kubelet should not try to create this at all.
 2. On the old debian-based container vm image (i.e., no systemd) kubelet should create this cgroup, but it fails to do so.

**Comment by yujuhong** [comment]
@dchen1107 should we fix this for 1.5?

**Comment by yujuhong** [comment]
This regression is caused by a change in libcontainerd: https://github.com/opencontainers/runc/pull/1013
The old code calls `getCgroupPath`, but the new code relies on `Manager.Paths` being populated beforehand. 

I looked around a little bit and we have a [CgroupManager](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/cgroup_manager_linux.go) in kubelet that wraps around the library, but the [`Pids()`](https://github.com/kubernetes/kubernetes/blob/42289c27580ab7d7f5b8593600c86c7eb0845b34/pkg/kubelet/cm/cgroup_manager_linux.go#L397) method it provides seems to be recursive (which is probably not what we need). I am not familiar with the the code and not sure whether we should reuse any of the existing code.  @derekwaynecarr and @vishh will have better suggestions.

**Comment by vishh** [comment]
I can take a look at this today.

**Comment by timstclair** [comment]
Spoke with Vish, I'll take this. I'm going to try and get a patch by tomorrow that we can cherry-pick into 1.4.6 (cc @jessfraz )
