### ISSUE TITLE
Get NodeInfo failure stalls kubelet startup...

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#35238]
I put bad credentials into my kubelet for a cloud provider and I got the following:

```
5743 kubelet.go:1122] Cannot get Node info: failed to get external ID from cloud provider: autorest#WithErrorUnlessStatusCode: POST https:/
5743 kubelet.go:1164] Kubelet failed to get node info.
```

And the kubelet basically stalls out.

I think there are two issues here:

1) The kubelet stalls, and even if you fix the cloud provider, you have to restart the kubelet to fix it.
2) It seems like the kubelet should mostly come up anyway, with information it can extract from the node, without requiring the cloud provider.

One solution would be to supply a "fallback NodeInfo" provider that is used if the cloud one fails, and then the ensure node status function could be used to update the node if the cloud provider credentials come back.

@dchen1107 @kubernetes/sig-node what do you think?

**Comment by activeshadow** [comment]
I'm seeing a similar issue... I'm running the `kubelet` on a hardware-based node (so no cloud provider), and if the `kubelet` isn't able to reach the K8s master when it first starts up it gets into this state and stays in this state even after it's able to communicate with the K8s master. The only way to fix it is to restart the kubelet with the K8s master reachable.

I tried patching the `NodeReady` status with `kubectl patch` but it doesn't work (I get a `node <node name> not patched` response).

**Comment by activeshadow** [comment]
For now I'm using an `ExecStartPre` script in my `kubelet.service` that waits for `ip route get <ip of master>` to succeed.

**Comment by brendandburns** [comment]
I just hit this again...  We should figure out a way to make this cleaner.

**Comment by jozuenoon** [comment]
Hi. I'm hitting this with k8s version 1.8.10, my nodes randomly can't connect back to master and stay in stale mode forever. I need to go to nodes and restart kubelet manually with `systemctl`. Anyone ? kops `1.8.1`

**Comment by cliffburdick** [comment]
/reopen
/remove-lifecycle rotten

I'm hitting this as well. It's happened very frequently
