### ISSUE TITLE
Federated ingress e2e test contains invalid spec: spec.ports[0].protocol: Invalid value: \"\": cannot create an external load balancer with non-TCP/UDP ports

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#35247]
Ingress connectivity and DNS
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/federated-ingress.go:181
      should be able to connect to a federated ingress via its load balancer [BeforeEach]
      /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/federated-ingress.go:179

      Creating service "" in namespace "e2e-tests-federated-ingress-u5857"
      Expected error:
          <*errors.StatusError | 0xc420fb2e00>: {
              ErrStatus: {
                  TypeMeta: {Kind: "", APIVersion: ""},
                  ListMeta: {SelfLink: "", ResourceVersion: ""},
                  Status: "Failure",
                  Message: "Service \"federated-ingress-service\" is invalid: [spec.ports[0].protocol: Required value, spec.sessionAffinity: Required value, spec.ports[0].protocol: Invalid value: \"\": cannot create an external load balancer with non-TCP/UDP ports]",

**Comment by quinton-hoole** [comment]
@mfanjie FYI

**Comment by mfanjie** [comment]
@quinton-hoole I am able to send a quick fix by EOD.
