### ISSUE TITLE
`docs/devel/README.md` should reference `docs/devel/testing.md`

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#35253]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): testing.md README.md

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): NA

**Environment**: NA
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**: I visited https://github.com/kubernetes/kubernetes/blob/master/docs/devel/README.md and did not find much about testing.

**What you expected to happen**: I expected more information.  A link to https://github.com/kubernetes/kubernetes/blob/master/docs/devel/testing.md would have been great.

**How to reproduce it** (as minimally and precisely as possible): Visit https://github.com/kubernetes/kubernetes/blob/master/docs/devel/README.md and try to learn all about testing Kubernetes.

**Anything else do we need to know**:

**Comment by bgrant0607** [comment]
@MikeSpreitzer Did you create a PR to fix this?

cc @michelleN

**Comment by MikeSpreitzer** [comment]
Yes, I just submitted a PR to fix this (which is now a matter for the `community` repo).
