### ISSUE TITLE
Federation e2e tests are timing out

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#35251]
It looks like the addition of some new e2e tests (by @nikhiljindal ?) made the test run take a bit longer, and not fit into it's timeout threshold.  

@shashidharatd FYI. 

root      9001  0.0  0.0 270936  6256 ?        Sl   08:48   0:00                          \_ /workspace/kubernetes/platforms/linux/amd64/ginkgo /workspace/kubernetes/platforms/linux/amd64/e2e.test -- --kubeconfig=/workspace/.kube/config --ginkgo.flakeAttempts=1 --host=https://104.198.234.41 --provider=gce --gce-project=k8s-jkns-e2e-gce-federation --gce-zone=us-central1-f --gke-cluster=jenkins-e2e --kube-master=jenkins-us-central1-f-master --cluster-tag= --repo-root=/workspace/kubernetes/cluster/../cluster/gce/../../cluster/gce/../../cluster/.. --node-instance-group=jenkins-us-central1-f-minion-group --prefix=jenkins-us-central1-f --network=jenkins-e2e --master-os-distro=gci --node-os-distro=debian --num-nodes=3 --minStartupPods=8 --report-dir=/workspace/_artifacts --ginkgo.focus=\[Feature:Federation\]
root      9009  0.0  0.1 538720 61168 ?        Sl   08:48   0:05                              \_ /workspace/kubernetes/platforms/linux/amd64/e2e.test --test.timeout=24h --ginkgo.seed=1476978533 --ginkgo.slowSpecThreshold=5.00000 --kubeconfig=/workspace/.kube/config --ginkgo.flakeAttempts=1 --host=https://104.198.234.41 --provider=gce --gce-project=k8s-jkns-e2e-gce-federation --gce-zone=us-central1-f --gke-cluster=jenkins-e2e --kube-master=jenkins-us-central1-f-master --cluster-tag= --repo-root=/workspace/kubernetes/cluster/../cluster/gce/../../cluster/gce/../../cluster/.. --node-instance-group=jenkins-us-central1-f-minion-group --prefix=jenkins-us-central1-f --network=jenkins-e2e --master-os-distro=gci --node-os-distro=debian --num-nodes=3 --minStartupPods=8 --report-dir=/workspace/_artifacts --ginkgo.focus=\[Feature:Federation\]
++ docker stop kubernetes-e2e-gce-federation-5358
kubernetes-e2e-gce-federation-5358
+ rc=124
+ [[ 124 -eq 124 ]]
+ echo 'Build timed out'
Build timed out
+ echo 'Exiting with code: 124'
Exiting with code: 124
+ exit 124
Build step 'Execute shell' marked build as failure

**Comment by quinton-hoole** [comment]
We should probably increase the overall timeout value to accommodate the new tests, in advance of doing a cleanup to make the tests run faster.

**Comment by nikhiljindal** [comment]
I havent added any tests yet :)

**Comment by nikhiljindal** [comment]
One way of reducing the time of our e2e tests is to register the clusters in the framework instead of doing it in BeforeEach in each test. Each test runs it in its own namespace, so no need to delete and register clusters again for each test

**Comment by shashidharatd** [comment]
I analyzed the logs in https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-federation/5360/build-log.txt
Most of the tests are failing because of service spec.
```
Service "federated-service" is invalid: [spec.ports[0].protocol: Required value, spec.sessionAffinity: Required value, spec.ports[0].protocol: Invalid value: "": cannot create an external load balancer with non-TCP/UDP ports]
```
**spec.ports[0].protocol** and **spec.sessionAffinity** field were optional before. something have changed.

**Comment by shashidharatd** [comment]
Another set of errors is due to timeouts during service creation, the current timeout is 60 seconds. we can increase the timeout to maybe like 150 seconds. https://github.com/kubernetes/kubernetes/blob/master/test/e2e/federated-service.go#L33
```
[k8s.io] [Feature:Federation]
/root/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:830
  Federated Services
  /root/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/federated-service.go:208
    DNS
    /root/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/federated-service.go:207
      should be able to discover a federated service [BeforeEach]
      /root/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/federated-service.go:165

      Failed to verify service "federated-service" in namespace "e2e-tests-federated-service-vs86y" in cluster: Present=true
      Expected error:
          <*errors.errorString | 0xc4203bcfc0>: {
              s: "timed out waiting for the condition",
          }
          timed out waiting for the condition
      not to have occurred
```

**Comment by shashidharatd** [comment]
it seems no new tests are added since 9 days. and i see the federated_informer throwing quite a lot of error, the one below:
```
Fri Oct 21 17:16:49 IST 2016 E1021 10:30:26.681840       1 federated_informer.go:191] Cluster &Cluster{ObjectMeta:k8s_io_kubernetes_pkg_api_v1.ObjectMeta{Name:federation-e2e-gce-asia-east1-c,GenerateName:,Namespace:,SelfLink:/apis/federation/v1beta1/clusters/federation-e2e-gce-asia-east1-c,UID:61a9040c-9779-11e6-806a-0a580ab4010a,ResourceVersion:9,Generation:0,CreationTimestamp:2016-10-21 10:30:26 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,},Spec:ClusterSpec{ServerAddressByClientCIDRs:[{0.0.0.0/0 https://130.211.247.183}],SecretRef:&k8s_io_kubernetes_pkg_api_v1.LocalObjectReference{Name:federation-e2e-gce-asia-east1-c,},},Status:ClusterStatus{Conditions:[],Zones:[],Region:,},} not added.  Not of correct type, or cluster not ready.
```
Increasing the timeout will not help. There is something wrong with the code, maybe related to API versioning.

**Comment by nikhiljindal** [comment]
I think the time out is due to a combination of our failing tests and https://github.com/kubernetes/kubernetes/issues/35080. Whenever a test fails, e2e framework tries to print the logs of some of our pods. But fetching logs is timing out after a long time (as discussed in https://github.com/kubernetes/kubernetes/issues/35080).

Fixing the tests to not fail should eliminate the timeout failure :)

**Comment by nikhiljindal** [comment]
Regarding spec.ports[0].protocol and spec.sessionAffinity fields, I see that we are setting them in our tests: https://github.com/kubernetes/kubernetes/blob/33ebe1f18b9cf5909931376f656e19e80ac9ac1c/test/e2e/federation-util.go#L266.

Ref https://github.com/kubernetes/kubernetes/issues/28615#issuecomment-256155937

**Comment by shashidharatd** [comment]
Currently there are 3 testcases which are failing, One is in Federated Ingress and the other two are in Federation API server authentication. I know the cause for API server authentication test failures. By default anonymous-auth is enabled, so api server will accept the request and there are no authorization plugins configured currently, hence the requests are being served.
I will send a fix for these 2 failed test cases
