### ISSUE TITLE
e2e testing parameters aren't well documented

### ISSUE THREAD

**Issue by ozdanborne** [kubernetes/kubernetes#35250]
I'm a newcomer to kubernetes, and have been trying to write e2e tests and run them against a running cluster. I have found that the e2e tests are largely parameterized so that they can be run on any k8s cluster (which is great!), but those parameters are largely undocumented, as are their default values. 

I'm going to describe the experience I've had trying to get this working. I hope that readers of this issue understand I'm pointing out nitpicky issues I encountered only to give the more experienced team the perspective of what a newcomer to e2e's might experience.

For background, my cluster is one which I have manually launched using my own vagrant scripts. Therefore, it is not truly one of either type `local` nor `vagrant`.
1. The steps say to `export KUBECONFIG=/path/to/kubeconfig`. My kubeconfig is already populated with all the information about my k8s cluster. Yet, the e2e tests seem to ignore all of it, and use predefined defaults overridden by undocumented environment variables.
2. These environment variables are not documented in one place, and the ones that are described might be wrong. For example, `e2e.md` says to `export KUBE_MASTER_IP="http://127.0.0.1:<PORT>"`, but I found when I did that, the tests prepend `http://` onto `KUBE_MASTER_IP`, and the tests end up trying to connect to `http://http://127.0.0.1:<PORT>`.
3. [some `--test_args` are listed](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/e2e-tests.md#bringing-up-a-cluster-for-testing), but the documentation states `For the purposes of brevity, we will look at a subset of the options...` without ever explaining how to find the full list of supported options. 
4. Tests run with `KUBERNETES_PROVIDER=local` will contact master via `KUBE_MASTER_IP`, whereas tests run with `KUBERNETES_PROVIDER=vagrant` will contact master via `KUBE_MASTER_URL`. (I'll need to double check that this is true. Maybe one overrides the other and I got confused?)

So all that being said, I consulted k8s documentation, and even tried to dig into the k8s command parsing libraries, but still feel that I don't truly understand how I got things working, only that "if I use 'this' magic combination of variables it works."

**Comment by ymqytw** [comment]
@kubernetes/kubernetes-docs-maintainers

**Comment by oomichi** [comment]
This report is well described and I also had similar experience as a newbie.

The point 2 has been fixed already with https://github.com/kubernetes/community/pull/509 anyways

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc

**Comment by ozdanborne** [comment]
I'm going to close this as it has been over a year and test infra has certainly progressed since then. Anyone else with similar experiences, I encourage you to open a new, updated issue describing them.
