### ISSUE TITLE
Split cluster configuration into static YAML files and Go code

### ISSUE THREAD

**Issue by satnam6502** [kubernetes/kubernetes#3525]
As I work through the process of moving our shell end to end tests to Go I am feeling the pain of having a bash based configuration that sets up our environment e.g. `kube-up.sh`, `gce/config-default.sh`, `gce/config-test.sh`, `gce/util.sh`.

I propose that we strive for a situation like this:
* Use YAML files to specify cluster configuration expressed in terms of atomic values rather than computation/code. Furthermore, we should be careful to tease apart provider specific config from general config. For example, the current `gce/config-default.sh` could be written as:
```
zone: us-central1-b
master_size: n1-standard1
num_minions: 4
instance_prefix: kubernetes
...
```
This is consumed by a Go function which extracts this information into some cluster context data structure and applies default values when needed and also performs any computation that is needed e.g. to compute the IP ranges for the minions. The objective is that anything that "should be computed" is in a Go function.
* A library of Go functions that work over these YAML files to produce a Go data-structure that represents the cluster context information.

Then something like the end to end test framework could be a Go program just consume these YAML files, run the general context computation code, and then apply whatever over-rides are required for the end to tend tests. Likewise for other programs. No more souce-ing `config-default.sh`, concatenating text representing bash and exec-ing it etc.

**Comment by erictune** [comment]
I worry that doing a good job of defining the Go data-structures will take a lot more time than just slogging through the unpleasantness of bash.

**Comment by satnam6502** [comment]
The unpleasantness is very unpleasant and a source of complexity, confusion and fragility.
I do not propose we spend much/any time thinking about what goes in the YAML files and I think the sooner we can port the bash to some "data structure" format the better because otherwise we will be tempted (as I am) to add more "code" to these files which will only increase the pain later.

@lavalamp : any thoughts?

**Comment by zmerlynn** [comment]
+1 to something like this, though I'm really looking for something that could be shared between providers too. About to reference this in a wide commit where, like you, I had to slog across all myriad cloud providers, and the env variables are a special treat.

**Comment by erictune** [comment]
There are going to be customers that want to use salt or ansible or chef or puppet or whatever they are used to to configure their machines.  We don't have to support all those tools, but we do have to make sure that we don't make our setup so automagic that users can't understand it or tweak flags.  So, proceed with babysteps on this issue.

**Comment by bgrant0607** [comment]
See also #5472

**Comment by pires** [comment]
Having a tool which _anyone_ can extend with their own provisioning solution would be really nice. Looking forward for #5472.

**Comment by davidopp** [comment]
@mikedanese

**Comment by roberthbailey** [comment]
Closing in favor of #5472 (to consolidate the discussion in one place).
