### ISSUE TITLE
kube-discovery should be able to listen on a different port

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#35268]
As we have to run in host's network namespace, we cannot simply remap ports at the container level.

**Comment by errordeveloper** [comment]
cc @kubernetes/sig-cluster-lifecycle @dgoodwin

**Comment by bgrant0607** [comment]
@grodrigues3 We could have correctly set routine labels from the notifications on this issue, assuming we had a label for each SIG

**Comment by luxas** [comment]
Actually, this is fixed already. 
Closing
