### ISSUE TITLE
[kubeadm] pre pull images and configurable pod implement

### ISSUE THREAD

**Issue by bulletRush** [kubernetes/kubernetes#35264]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No. 

**What keywords did you search in Kubernetes issues before filing this one?:
`kubeadm`, `kubeadm pull`, `kubeadm image`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-beta.8", GitCommit:"3040f87c570a772ce94349b379f41f329494a4f7", GitTreeState:"clean", BuildDate:"2016-09-18T21:06:37Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: vmware virtual machine 2c4g
- **OS** (e.g. from /etc/os-release): centos 7.2
- **Kernel** (e.g. `uname -a`): Linux 130 3.10.0-327.36.1.el7.x86_64 #1 SMP Sun Sep 18 13:04:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: 
- **Others**:

Hi, I have implement [pre pull image and configurable pods](https://github.com/bulletRush/kubernetes/commit/7d73b13bd4a4b346dd13fd0d6808a3a49e37110a).
so you can:
- pre download kube-apiserver/kcm and so on images before write static manifests.
- you can download image from docker hub instead of  "gcr.io". so you can use a docker hub mirror now. 
- use custom configuration in pod(not fully test).

To use this feature, you can run kubeadm in this command `./kubeadm init --config=config.json`.  a short sample about `config.json` : 

``` json
{
    "podSpecs": {
        "dummy": {
            "containers": [
                {
                    "image": "barrettwu/pause-amd64:3.0",
                    "imagePullPolicy": "IfNotPresent",
                    "name": "dummy",
                    "resources": {}
                }
            ],
            "securityContext": {
                "hostNetwork": true
            },
            "serviceAccountName": "",
            "volumes": null
        }
    },
    "prePullPods": [ 
        "dummy"
    ]
}
```

when you run kubeadm by `./kubeadm --config=config.json`, the output will show you the image pull process:

``` shell
[root@130 kubeadm]# ./kubeadm init --config=config.json 
Running pre-flight checks
<master/tokens> generated token: "79284f.3e6b319b0ae9ad6f"
prePullPods: [etcd kube-apiserver kube-scheduler pause kube-controller-manager kube-discovery dummy addonImages]
pre pull image "weaveworks/weave-npc:1.7.2" in pod "addonImages"
1.7.2: Pulling from weaveworks/weave-npc

2aff618222e8: Pull complete 
b6f276ea2686: Downloading [=======================>                           ] 6.106 MB/12.92 MB
a3ed95caeb02: Download complete 
^Ced95caeb02: Pulling fs layer 
```

If you config `kube-apiserver`, `kube-controller-manager` in this config file, the static pod manifests genereted by kubeadm will use podSpec definition in this file. 

 but I still have some confuse about my implementation:
- what's your idea to implement this feature? my implementation has so much of shortage.
  - conflict with pre-flight check if you use custom pod config. 
  - only images listed both in prePullPods and podSpecs can be download.
- should I remove the configurable pod feature to make a pr? because this have a lot of limitation and will cause kubelet failed to start some pod if some static manifest generated rule changed.

**Comment by errordeveloper** [comment]
@bulletRush thank you very much for this proposal. We have considered this already, and we will very likely implement it soon.

**Comment by bulletRush** [comment]
@errordeveloper, may i do something for this feature?

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#34
