### ISSUE TITLE
With required podAntiAffinity, scheduler couldn't find node (false positive matcher?)

### ISSUE THREAD

**Issue by xjlu** [kubernetes/kubernetes#35317]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1+33cf7b9", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"not a git tree", BuildDate:"2016-10-13T15:18:15Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:13:36Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: aws mixed c4.2x, m4.2x, g2
- **OS** (e.g. from /etc/os-release): centOS
- **Kernel** (e.g. `uname -a`): 
- **Install tools**:
- **Others**:

**What happened**:
Our AntiAffinity config is

```
      annotations:
        scheduler.alpha.kubernetes.io/affinity: >
          {
            "podAntiAffinity": {
              "preferredDuringSchedulingIgnoredDuringExecution": [
                {
                  "labelSelector": {
                    "matchExpressions": [
                      {
                        "key": "app",
                        "operator": "In",
                        "values": ["our-app-name"]
                      }
                    ]
                  },
                  "topologyKey": "kubernetes.io/hostname"
                }
              ]
            }
          }
```

We wanted to enforce the rule that no node can schedule this app more than once.
This config works fine when the number of replicas is below (14-16), and once we request more replicas,  all new replicas are in pending state and the log shows that the no node satisfying the predicate in the affinity match. But we have a capacity of 35 nodes and resource utilization of all nodes are close to empty, and increase the capacity didn't work either.

We also tried to add namespace to the annotation, and it was the same result.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
We were able to reproduce this problem consistently with any simple app such as a simple curl image and run sleep command. 

**Anything else do we need to know**:

**Comment by xjlu** [comment]
The number seems arbitrary, and on staging env, we hit the issue when we want to schedule more than 6 apps.

**Comment by timothysc** [comment]
@rrati could you please evaluate this against your fields PR.  

/cc @kubernetes/sig-scheduling

**Comment by davidopp** [comment]
@wojtek-t do you think you could look into this?

**Comment by davidopp** [comment]
cc/ @kevin-wangzefeng

**Comment by grosskur** [comment]
I'm seeing a similar problem on GKE 1.5.1. The behavior is:

1. Two pods are scheduled (in two separate replica sets) in an auto-scaling GKE cluster with a `podAntiAffinity` rule preventing them from running on the same node.

2. GKE scales up the cluster by adding an additional node.

3. The first pod gets scheduled and transitions into `Running`, but the second pod never gets scheduled and stays in `Pending`.

I expected the cluster to notice this pod stuck in `Pending` and remediate by scaling up an additional node. But that didn't happen, at least for the ~1 hour I waited. Note also:

1. This is a multi-zone cluster.

2. Each pod has a `PersistentVolumeClaim` that binds the volume to a specific zone (`us-central1-b`). So the pod has to be scheduled in that same zone.

3. GKE did, in fact, create the new node in the correct zone (`us-central1-b`).

Here are the events for the first pod (`bigeasy-03-b-xxx`):

```
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------   --------        ------                  -------
  1h            58m             9       {default-scheduler }                    Warning         FailedScheduling        pod (bigeasy-03-b-xxx) failed to fit in any node
fit failure summary on nodes : Insufficient cpu (6), MatchInterPodAffinity (3), NoVolumeZoneConflict (11)
  58m   58m     1       {default-scheduler }                                                                            Normal  Scheduled       Successfully assigned bigeasy-03-b-xxx to gke-xxx
```

And the events for the second pod (`bigeasy-03-e-xxx`):

```
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------   --------        ------                  -------
  51m           31m             66      {default-scheduler }                    Warning         FailedScheduling        pod (bigeasy-03-e-xxx) failed to fit in any node
fit failure summary on nodes : Insufficient cpu (6), MatchInterPodAffinity (5), NoVolumeZoneConflict (11)
  1h    18s     152     {default-scheduler }            Warning FailedScheduling        pod (bigeasy-03-e-xxx) failed to fit in any node
fit failure summary on nodes : Insufficient cpu (6), MatchInterPodAffinity (4), NoVolumeZoneConflict (11)
```
