### ISSUE TITLE
Combine cluster/get-kube.sh and hack/get-build.sh

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#35351]
The functionality to translate a published version like "release/stable" or "ci/latest", currently in `hack/build.sh` should be folded into `cluster/get-kube.sh`.

The test-infra `e2e-runner.sh` would be able to just use `cluster/get-kube.sh` with published version strings too.

**Comment by zreigz** [comment]
Can you describe it a little bit more. First of all I can not find any `hack/build.sh` file

**Comment by ixdy** [comment]
Sorry, I meant `hack/get-build.sh`.

**Comment by zreigz** [comment]
I've introduced required functionality to `cluster/get-kube.sh`. I have prepared proposal for it: https://github.com/zreigz/kubernetes/commit/243024d129c1ff0ec44302530f4c4f469dfe088f
Now user can use it in following way 
```
$ KUBERNETES_RELEASE=release/stable cluster/get-kube.sh
$ KUBERNETES_RELEASE=v1.3.10 cluster/get-kube.sh
$ cluster/get-kube.sh
```
Please take a look my commit. If it's OK I will prepare PR for it

**Comment by ixdy** [comment]
@zreigz get-kube.sh is what's hosted on https://get.k8s.io, so it can't depend on any other scripts in the repo.

**Comment by zreigz** [comment]
OK I fixed it. Please take a look: https://github.com/zreigz/kubernetes/commit/23453ab31a8db564616e84ce549f013dfa8abb62

**Comment by ixdy** [comment]
@zreigz I have some comments, but the approach looks good, so please open a PR.
