### ISSUE TITLE
Service can change from ExternalName -> ClusterIP and not get an IP allocated

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#35354]
Similar to #33029

**Comment by xiangpengzhao** [comment]
#46190 is a dup of this. PR #46197 is just a quick try. Will spend more time on it to cover all cases.

**Comment by bowei** [comment]
@xiangpengzhao status?

**Comment by xiangpengzhao** [comment]
I sent PR #46197 which is waiting for reviewing from @freehan .
Also, that PR is blocked by issue #47224 which is self-assigned by you but not fixed yet :) @bowei

**Comment by xiangpengzhao** [comment]
That issue might be not hard to fix, but I didn't find how.So I need your help. @bowei
IMO, we mignt need to change CI jobs configure in some files or images.

**Comment by bowei** [comment]
After discussing with reviewer (@freehan): this might be better suited to merge but not for 1.7.0, as it touches a part of the code that is quite old and stable. In other words, we probably need to give this change some time to soak in the e2e system as opposed to put right away into the release.
