### ISSUE TITLE
bazel test broken for federation/pkg/federation-controller/cluster

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#35360]
I'm running this in a docker container on kubernetes and this is the only test that fails:

```
E1022 07:46:12.075236       6 clustercontroller.go:129] Failed to create cluster client, err: Unable to select an IP.
--- FAIL: TestUpdateClusterStatusOK (0.00s)
    clustercontroller_test.go:142: Failed to Update Cluster Status
FAIL
```

**Comment by mikedanese** [comment]
Is it a flake or deterministic? I'm not able to reproduce on my workstation. You can always add the skip tag temporarily.

**Comment by spxtr** [comment]
Deterministic.

**Comment by spxtr** [comment]
I'll close this for now, we can reopen once we're running it in CI.
