### ISSUE TITLE
Docs for https-nginx service point to wrong page

### ISSUE THREAD

**Issue by franz-josef-kaiser** [kubernetes/kubernetes#35368]
The [docs](https://github.com/kubernetes/kubernetes/blob/69bd37d77009599eca9ce78669afab6666665c53/docs/user-guide/connecting-applications.md) for this service point to [`docs/user-guide/connecting-applications.md`](https://github.com/kubernetes/kubernetes/blob/69bd37d77009599eca9ce78669afab6666665c53/docs/user-guide/connecting-applications.md), which points out that this link is deprecated and should actually go to:

```
http://kubernetes.io/docs/user-guide/connecting-applications/
```

**Comment by pwittrock** [comment]
Fixed
