### ISSUE TITLE
PersistentVolume status.Phase is the only indicator of whether a PV is released or not?

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#35407]
The litmus test for status has typically been "can this info be recreated by observation".  If a PV was created, used, and released (with retain policy) it would be marked Phase=released.  If Status were to get lost, could we tell that the PV was NOT available for reuse?  I don't think we could...

@jsafrane

**Comment by jsafrane** [comment]
we can reconstruct the status, it's spread across the giant if-then-else tree in PV controller. 

There is a shorthand version for quick sanity check:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go#L1095

**Comment by thockin** [comment]
How do we know that a given PV is "dirty" and needs to be manually
scrubbed, without status?

**Comment by jsafrane** [comment]
yes, `PersistentVolumeController.isVolumeReleased()`, https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go#L1095

**Comment by thockin** [comment]
OK.  I can buy that.
