### ISSUE TITLE
CPU/IO stats are zeroed out

### ISSUE THREAD

**Issue by yuriy-filatov** [kubernetes/kubernetes#35419]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/386"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release):
  
  > PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
  > NAME="Debian GNU/Linux"
  > VERSION_ID="8"
  > VERSION="8 (jessie)"
  > ID=debian
  > HOME_URL="http://www.debian.org/"
  > SUPPORT_URL="http://www.debian.org/support"
  > BUG_REPORT_URL="https://bugs.debian.org/"
- **Kernel** (e.g. `uname -a`): SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
- **Install tools**: just unpacked tar.gz
- **Others**: --

**What happened**: after recent minion kernel autoupdate docker/grafana CPU/IO per-pod stats are zeroed out, per-pod memory stats are not refreshing at all. Per-minion stats are working fine.

> Log started: 2016-10-20  06:35:25
> (Reading database ... ^M
> (Reading database ... 41342 files and directories currently installed.)
> Preparing to unpack .../linux-image-3.16.0-4-amd64_3.16.36-1+deb8u2_amd64.deb ...
> Unpacking linux-image-3.16.0-4-amd64 (3.16.36-1+deb8u2) over (3.16.36-1+deb8u1) ...
> Preparing to unpack .../linux-compiler-gcc-4.8-x86_3.16.36-1+deb8u2_amd64.deb ...
> Unpacking linux-compiler-gcc-4.8-x86 (3.16.36-1+deb8u2) over (3.16.36-1+deb8u1) ...
> Preparing to unpack .../linux-headers-3.16.0-4-amd64_3.16.36-1+deb8u2_amd64.deb ...
> Unpacking linux-headers-3.16.0-4-amd64 (3.16.36-1+deb8u2) over (3.16.36-1+deb8u1) ...
> Preparing to unpack .../linux-headers-3.16.0-4-common_3.16.36-1+deb8u2_amd64.deb ...
> Unpacking linux-headers-3.16.0-4-common (3.16.36-1+deb8u2) over (3.16.36-1+deb8u1) ...
> Setting up linux-image-3.16.0-4-amd64 (3.16.36-1+deb8u2) ...
> /etc/kernel/postinst.d/initramfs-tools:
> update-initramfs: Generating /boot/initrd.img-3.16.0-4-amd64
> /etc/kernel/postinst.d/zz-update-grub: Generating grub configuration file ...
> Found linux image: /boot/vmlinuz-3.16.0-4-amd64
> Found initrd image: /boot/initrd.img-3.16.0-4-amd64
> done

All pod telemetry from all workers failed in same way after same kernel autoupdate, so we assume this is related.

**What you expected to happen**: non-zero CPU stats for each pod.

**How to reproduce it** (as minimally and precisely as possible): launch 1.4.0 on aws using jessie distro, add a busy pod (with while true loop or something), see initial non-zero cAdvisor, grafana, dashboard UI stats, trigger the autoupdate, see CPU stats for pod zeroed out (while total minion CPU load remains above zero)

**Anything else do we need to know**:

**Comment by yuriy-filatov** [comment]
@justinsb maybe you can advise something here? It's quite important as monitoring is dead on docker level and will affect everyone who'll use this kernel version.

**Comment by captify-akraievoy** [comment]
*Update*: we have another cluster with precisely same versions of kubernetes running fine - stats are still present, despite kernel having been auto-updated to the very same version we've seen on the one which has broken per-container CPU stats. My current conclusion is that the load also is a factor: because the cluster, which is still intact, does not really sustain significant load in comparison to the one which broke after/during the kernel update.

**Comment by yuriy-filatov** [comment]
apt-get dist-upgrade & rebooting instance helped to fix issue.
