### ISSUE TITLE
Make the schedule of ImageLocalityPriorty more efficient and smarter!

### ISSUE THREAD

**Issue by LiTao2016** [kubernetes/kubernetes#35414]
[The current version of the k8s](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/priorities/priorities.go#L219)  provides a way to select a host to running the container,whether the candidate host contains the image to be downloaded, but the method is still not fast enough and smart (need to download the full image). Under normal circumstances, the candidate host already contains some image layers which is contained in the image to be downloaded, the layers do not need to repeat the download. It can be improved based on image layer to scheduling the host. This can reduce the image download traffic and improve container startup speed, especially in the public cloud and public image repository.

Improved mainly contains the following three parts:
- image layer info collection module:
  Running on the node, collecting all the image layer info of the node, by a predetermined strategy (timing, event triggers, user-triggered) reported to the master node.
-  image layer info analysis module:
  Running on the master node, analyze all the information which is reported by image layer info collection module(image label or id on each node, the image layer label or id, the image layer size, etc.), all the information can be initiative to collect(timing, event triggers, user-triggered).
- based on image layer info scheduling module:
  Running on the master node, supports scheduling based on the image layer info provide by image layer info analysis module.
  Possible scheduling strategies:
  1. Select a node to deploy the container which is the smallest of the total size of the images to be downloaded (calculating the minimum size difference between the to be downloaded mirror layer and the downloaded image layer) .
  2. Select a node to deploy the container which is the least amount of the total number of the images to be downloaded(calculate the minimum number difference between the to be downloaded mirror layer and the downloaded image layer).
  3. Calculated the weighted average of the total mirror layer capacity and the total mirror layer number, select the lowest average of the node to deploy container.
  4. The new container scheduling strategies based on image layer info can work with the existing scheduling strategies,such as based on cpu usage, memory usage; the container scheduling module will calculate cpu usage, memory usage, the total amount of container image to be downloaded, and get a score; Pre-set the weight of resources, weighted average of nodes through these weights. Select a node with the minimum weighted average value to deploy container.

@davidopp @alfred-huangjian @kevin-wangzefeng

**Comment by davidopp** [comment]
cc/ @dchen1107 @yujuhong

**Comment by ingvagabund** [comment]
@LiTao2016 what happens if the Apiserver does not provide all layers? IINM, all the priority functions work over data collected from the Apiserver. If the ``ImageLayerPriority`` does not have all layers of the image in question available, should it assign worst or zero priority? What happens if the image does not exist (e.g. missing image registry)?

**Comment by LiTao2016** [comment]
Thanks for @ingvagabund's timely response.if the apiserver does not provide all layers,of cause,should download the missing image layers as usual and image layers info is not considered in the scheduling time as you said.Under normal circumstances,this only happens when the image is first deployed.In other cases,such as pods re-scheduling,the apiserver could provide all layers info and make the schedule more efficient and smarter.

**Comment by ingvagabund** [comment]
@LiTao2016 can you more elaborate on how the priority function handle layers that are not yet available in the Apiserver?

**Comment by LiTao2016** [comment]
I'm sorry to reply so late.When the layers that are not yet available in the Apiserver, the layer information is not considered when scheduling and the whole image will be download to the node.After that the Apiserver will get this image layers information by image layer info collection module ,and this information will be used in the next scheduling.

**Comment by wanghaoran1988** [comment]
If the layers information are not exits on the apiserver, maybe we can get the size using the registry api
1. Get the manifests of the image, the manifests contains the layers sha ID.
  ` GET /v2/<name>/manifests/<reference>`
2. Get the layer size using 
`HEAD /v2/<name>/manifests/<reference>`
This will return the blob size in the header.

**Comment by ingvagabund** [comment]
If it can be collected from a reflector, i.e. if there is an object for that, than it could work.

**Comment by timothysc** [comment]
This is not a good idea in the long haul, you are partial weighting based on some level of data gravity, where distance doesn't matter.  If you want better performance, smash your layers to 1 and pre-pull your most common images across your cluster or make your images immutable.

**Comment by resouer** [comment]
After read thru this thread, I'm afraid the complexity of this design concerns me more than it's performance benefits ... I agree with @timothysc that improvement of image itself make more sense to me.
