### ISSUE TITLE
Centos 7 libvirt coreos 'virtio-9p-pci' is not a valid device model name

### ISSUE THREAD

**Issue by timactive** [kubernetes/kubernetes#35421]
I have a problem  on Centos 7 environment to perform the process 
http://kubernetes.io/docs/getting-started-guides/libvirt-coreos/
3.10.0-327.36.2.el7.x86_64

qemu-kvm-1.5.3-105.el7_2.7.x86_64
qemu-kvm-common-1.5.3-105.el7_2.7.x86_64
qemu-kvm-tools-1.5.3-105.el7_2.7.x86_64
qemu-img-1.5.3-105.el7_2.7.x86_64
libvirt-daemon-driver-qemu-1.2.17-13.el7_2.5.x86_64

[root@ns394725 kubernetes]# ./cluster/kube-up.sh
... Starting cluster using provider: libvirt-coreos
... calling verify-prereqs
KSM is not enabled
Enabling it would reduce the memory footprint of large clusters
Do you want to enable KSM (requires root password) (y/n)? y
... calling kube-up
KUBE_MASTER_IP: 192.168.10.1
KUBE_MASTER: kubernetes-master
--2016-10-24 13:58:53--  https://alpha.release.core-os.net/amd64-usr/current/coreos_production_qemu_image.img.bz2
Résolution de alpha.release.core-os.net (alpha.release.core-os.net)... 104.16.21.26, 104.16.20.26, 2400:cb00:2048:1::6810:141a, ...
Connexion vers alpha.release.core-os.net (alpha.release.core-os.net)|104.16.21.26|:443...connecté.
requête HTTP transmise, en attente de la réponse...200 OK
Longueur: 260714341 (249M) [application/octet-stream]
Fichier du serveur pas plus récent que le fichier local «./cluster/../cluster/../cluster/libvirt-coreos/coreos_production_qemu_image.img.bz2» -- non récupéré.

Pool kubernetes réactivé

TLS assets generated...
Réseau kubernetes_global créé depuis ./cluster/../cluster/../cluster/libvirt-coreos/network_kubernetes_global.xml

Réseau kubernetes_pods créé depuis ./cluster/../cluster/../cluster/libvirt-coreos/network_kubernetes_pods.xml

Volume kubernetes-node-1.img créé

Pool kubernetes réactivé

**erreur :Impossible de créer le domaine depuis /tmp/tmp.Njpvlg1zVI
erreur :internal error: process exited while connecting to monitor: 2016-10-24T11:59:01.164993Z qemu-system-x86_64: -device virtio-9p-pci,id=fs0,fsdev=fsdev-fs0,mount_tag=config-2,bus=pci.0,addr=0x3: 'virtio-9p-pci' is not a valid device model name**

**Comment by FrankYu** [comment]
virtio-9p-pci is disable by default of qemu-kvm on centos.

See: https://git.centos.org/blob/rpms!qemu-kvm!/4f5da8cf40ea809191d5b389aa6a63327196fdcf/SPECS!qemu-kvm.spec#L5339

**Comment by kargakis** [comment]
Reopen if still an issue

**Comment by jtagcat** [comment]
link is now 404, still an issue
