### ISSUE TITLE
Improve restart policy for the case kubelet fails to pull image

### ISSUE THREAD

**Issue by hex108** [kubernetes/kubernetes#35423]
We use Kubernetes 1.4.1.

If we set containers' restart policy to **Always**(or **OnFailure**) and kubelet fails to pull image for some reason(e.g. permission denied to pull the image, or disk is full),  kubelet will always try to pull the image. It can be expected that kubelet will fail to pull the image again and again as following.

<pre>
Events:
  FirstSeen LastSeen    Count   From                SubobjectPath           Type        Reason          Message
  --------- --------    -----   ----                -------------           --------    ------          -------
  3m        3m      1   {default-scheduler }                        Normal      Scheduled       Successfully assigned testquota-780062042-tbnts to tbds-10-149-27-114
  3m        3m      4   {kubelet tbds-10-149-27-114}                    Warning     MissingClusterDNS   kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.
  3m        57s     5   {kubelet tbds-10-149-27-114}    spec.containers{helloquota} Normal      Pulling         pulling image "my-registry.com/gcloud/demo:latest"
  3m        57s     5   {kubelet tbds-10-149-27-114}    spec.containers{helloquota} Warning     Failed          Failed to pull image "my-registry.com/gcloud/demo:latest": image pull failed for my-registry.com/gcloud/demo:latest, this may be because there are no credentials on this request.  details: (unauthorized: authentication required)
  3m        57s     5   {kubelet tbds-10-149-27-114}                    Warning     FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "helloquota" with ErrImagePull: "image pull failed for my-registry.com/gcloud/demo:latest, this may be because there are no credentials on this request.  details: (unauthorized: authentication required)"

  3m    2s  18  {kubelet tbds-10-149-27-114}    spec.containers{helloquota} Normal  BackOff     Back-off pulling image "my-registry.com/gcloud/demo:latest"
  3m    2s  18  {kubelet tbds-10-149-27-114}                    Warning FailedSync  Error syncing pod, skipping: failed to "StartContainer" for "helloquota" with ImagePullBackOff: "Back-off pulling image \"my-registry.com/gcloud/demo:latest\""
</pre>

I think for this case we could reschedule the pod to another kubelet on another machine. It could avoid unnecessary retry, and the pod could get running as soon as possible.

**Comment by resouer** [comment]
I think this case is covered by rescheduling https://github.com/kubernetes/community/blob/master/contributors/design-proposals/rescheduling.md

This feature has not been finished of course.
