### ISSUE TITLE
'kubectl set resource' calls the Rest API outside of the command execution context

### ISSUE THREAD

**Issue by fabianofranz** [kubernetes/kubernetes#35426]
`kubectl` commands must not use the factory and perform API calls outside the `Run` function. `kubectl set resource` is currently fetching the server resources to build help, which is wrong.

https://github.com/kubernetes/kubernetes/blob/901bbee2fd6faef5b776fe77929d53b8518de145/pkg/kubectl/cmd/set/set_resources.go#L93-L98

**Comment by kargakis** [comment]
@kubernetes/kubectl @JacobTanenbaum

**Comment by fabianofranz** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/35427

**Comment by deads2k** [comment]
Seems like you want that when it's immediately available and you don't want it when its not.  It's really nice to have help be fully correct when you can.

**Comment by smarterclayton** [comment]
Just different function.  This is "show the things to end users that fit in
a list, suitable for help".  Help should not be fetched remotely.

**Comment by deads2k** [comment]
> Just different function.  This is "show the things to end users that fit in
> a list, suitable for help".  Help should not be fetched remotely.

While that wouldn't make it impossible to create `set` commands that work natively across unknown types, it does make a lot less consistent.  Saying that the solution for having good help is "fork kubectl" is not very friendly.  An optional, fast, short-circuiting check seems better for everyone except the guy writing it.
