### ISSUE TITLE
kubeadm init --config breaks defaults

### ISSUE THREAD

**Issue by superdump** [kubernetes/kubernetes#35424]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kubeadm defaults
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
v1.4.3

**Environment**:
- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): N/A
- **Kernel** (e.g. `uname -a`): N/A
- **Install tools**: kubeadm
- **Others**: N/A

**What happened**:
Using `kubeadm init --config /path/to/config.yml` appears to block default values from being set. I first noticed it where a pre-flight check of the Servicer CIDR was presenting itself as an empty string although I had not set it through the command line flag nor in the config file. I also noticed that kubelet requests to the API server were being sent to port 0 as the API server default port had not been set.

**What you expected to happen**:
A config file should only override defaults, not make it so that no defaults are set.

**How to reproduce it** (as minimally and precisely as possible):
Use `kubeadm init --config /path/to/config.yml` with an appropriate configuration file that does not set the service CIDR, for example, and note that pre-flight checks will fail due to the default values not being set.

**Anything else do we need to know**:
A temporary workaround is to explicitly set all values to their defaults or the value you desire.

**Comment by errordeveloper** [comment]
cc @kubernetes/sig-cluster-lifecycle @mikedanese

**Comment by superdump** [comment]
As noted in the kubeadm Slack support channel - I suspect it's something either with the callback 'Run' function of the cobra command that doesn't pass the parsed cfg properly or maybe something in NewInit() where the config file is read into the exist MasterConfiguration data structure that has been passed in.

**Comment by pires** [comment]
Quoting https://github.com/kubernetes/kubernetes/blob/master/pkg/runtime/interfaces.go#L55-L58:
> If defaults are provided, they are applied to the data by default. If no defaults or partial defaults are provided, the type of the into may be used to guide conversion decisions.

So this may be something else going on. Checking..

**Comment by pires** [comment]
I've been looking at this and I believe my initial assessment, and perhaps yours as well, that _if a value is not set in the configuration file, then use corresponding flag default_ is wrong. I am now convinced that we can use only one of the configuration methods, flags or file.
That said, when using flags, there are defaults available. The same doesn't apply to configuration file.

@mikedanese can you please confirm? And if I'm right, should file have defaults as well?

**Comment by luxas** [comment]
If it's like that, we should definitely have defaults for flags as well

**Comment by superdump** [comment]
To be clear: my expectation is that defaults are defaults regardless of whether I modify them with config in a file or command line flags. Defaults always apply unless they are explicitly overridden.

**Comment by pires** [comment]
@superdump I agree. And if it's not the case here, it should be documented.

**Comment by mikedanese** [comment]
I think i know how to fix this. I'll take a look today.

**Comment by pires** [comment]
OK, I (believe I) found the solution - we are missing defaulting for the objects we expose.

Now, relying on the flag system to provide the defaults is wrong. Let's look at an example here.

`test.yaml`
```yaml
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: v1.4.2
secrets:
  givenToken: 92f7e2.3685fe2e01f799f3
```
And now you run:
```
kubeadm init --config file.yaml --token 123456.3685fe2e01f799f3
```

Which token should be used?

**Comment by superdump** [comment]
The flag is last so it takes precedence. That would be my expectation.

**Comment by mikedanese** [comment]
Flags are parsed atomically in go (unlike getopt). Knowing that implementation detail, I would expect the config file to take precedence. Whether that's right or not is another question...

**Comment by pires** [comment]
> The flag is last so it takes precedence. That would be my expectation.

@superdump ok, let's try a different order then:
```
kubeadm init --token 123456.3685fe2e01f799f3 --config test.yaml
```
Does your previous rule still apply and now the configuration file has precedence?

**Comment by pires** [comment]
@mikedanese it's an important question in the sense that it will have an impact on how this fix is implemented. If we proceed with defaulting, we will be able to use only one of the configuration methods: flags *or* file.

**Comment by superdump** [comment]
@pires - yes, I would expect the config file to take precedence because of convention. However, I would argue if duplicates are specified that maybe a warning or error should occur.

**Comment by luxas** [comment]
Yes, I also think the config file should have higher precedence.
We should/have to document this as well as show a warning if both are specified.

@mikedanese Do you have a status update on this? Do you have something up as a PR soon?
I'd like to get the last pieces ready so we can soon can push a new release to stable

**Comment by pires** [comment]
@luxas I mentioned I have a fix for defaulting (for when you decode an object from a file) but there's nothing in place to force precedence or even merge of objects. As an example, `kubadm init` code may seem to try and merge `MasterConfiguration` populated by flags with a new one populated by file. This *is not* what's going on!

**Comment by luxas** [comment]
No, I realise that this is not how it works today, but I was thinking we were talking about how it _should_ be, and we think that config flags _should_ take precedence, but they are not right now.

Right?

**Comment by pires** [comment]
@luxas I will open a PR that fixes this issue. I've opened #35710 for continued debate.

**Comment by pires** [comment]
Waiting on #35721 to be merged so that I can test manually before opening the PR.

**Comment by pires** [comment]
Running `make verify` and all `kubeadm` tests as we speak, PR incoming in the next hour.

**Comment by luxas** [comment]
This is fixed now
