### ISSUE TITLE
Add Result of Last Failed Health Check to Pod Describe Output

### ISSUE THREAD

**Issue by jdavis7257** [kubernetes/kubernetes#35438]
It is sometimes difficult to tell why a pod was killed due to a failed health check. This could be made easier by adding a last failed health check status section. I would like to see a last failure section under liveness in the describe output with the following fields if possible:
- Return Code
- Output (for example body of http request)
- Timestamp

**Comment by resouer** [comment]
May I ask can you get these information from events in `kubectl describe`?  If not, what do you usually get  failed health check result for now?
