### ISSUE TITLE
Kubelet high CPU usage

### ISSUE THREAD

**Issue by Zapadlo** [kubernetes/kubernetes#35448]
Kubelet on of the node is running with very high CPU consumption.

Running on CoreOS (1122.3.0) on AWS.
Hyperkube: "v1.4.0_coreos.2"

pprof attached
![1 4-kubelet-high-cpu svg](https://cloud.githubusercontent.com/assets/1801067/19655126/d55da0c4-9a12-11e6-9d8b-531f8c5c3374.png)

Happy to include more details.
[pprof.txt](https://github.com/kubernetes/kubernetes/files/548467/pprof.txt) .pb.gz file

**Comment by Random-Liu** [comment]
@yujuhong 
/cc @kubernetes/sig-node

**Comment by yujuhong** [comment]
@Zapadlo, could you post a graph with higher resolution? It's hard to read any text...

From what I could read, the biggest node is from the package "federation-controller", and kubelet doesn't import that package.

**Comment by alkar** [comment]
@yujuhong 
[1.4-kubelet-high-cpu.svg.gz](https://github.com/kubernetes/kubernetes/files/548803/1.4-kubelet-high-cpu.svg.gz)

**Comment by yujuhong** [comment]
@Zapadlo @alkar there are a lot of controller manager stuff in the graph. What's the command you used to start kubelet and how did you get the profile?

**Comment by alkar** [comment]
@Zapadlo got the profile, so I can't help you there, but the kubelet is started a systemd service:

```
    - name: kubelet.service
      enable: true
      command: start
      content: |
        [Unit]
        Requires=docker.service
        After=docker.service

        [Service]
        Environment=KUBELET_VERSION=${k8s_ver}
        Environment=KUBELET_ACI=${hyperkube_image_repo}
        Environment="RKT_OPTS=--volume dns,kind=host,source=/etc/resolv.conf --mount volume=dns,target=/etc/resolv.conf"
        ExecStart=/usr/lib/coreos/kubelet-wrapper \
        --api-servers=https://${master_address} \
        --network-plugin-dir=/etc/kubernetes/cni/net.d \
        --network-plugin=${network_plugin} \
        --register-node=true \
        --allow-privileged=true \
        --config=/etc/kubernetes/manifests \
        --cluster_dns=${dns_service_ip} \
        --cluster_domain=cluster.local \
        --cloud-provider=aws \
        --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml \
        --tls-cert-file=/etc/kubernetes/ssl/k8s-worker.pem \
        --tls-private-key-file=/etc/kubernetes/ssl/k8s-worker-key.pem
        Restart=always
        RestartSec=10
        [Install]
        WantedBy=multi-user.target
```

HTH

**Comment by Zapadlo** [comment]
Got the profile by running `kubectl proxy` and `go tool pprof rootfs/hyperkube http://127.0.0.1:8001/api/v1/proxy/nodes/ip-10-66-21-88.eu-west-1.compute.internal/debug/pprof/profile`

Go version: `go version go1.7.1 linux/amd64`

**Comment by yujuhong** [comment]
@Zapadlo I looked at the svg file, but it still didn't make much sense to me. Most of the cpu was consumed by federation-controller. Are you sure the`rootfs/hyperkube` binary is the same version that's running in the node?

Also, how much cpu was kubelet actually using? Can you also check the `/debug/pprof/` endpoint to see how many goroutines are running?

/cc @kubernetes/sig-rktnetes since this is a coreos+rkt setup.

**Comment by Zapadlo** [comment]
Quite sure, I downloaded the same image and extracted the binary from it.

Currently its using ~130% on a 2CPU machine.

Output from `/debug/pprof/`:

```

profiles:
0	block
331	goroutine
5345	heap
30	threadcreate
```

**Comment by yujuhong** [comment]
@Zapadlo it seems that a lot of churn is caused by reading the listing pod volumes on the disk using [ReadDirNoExit](https://github.com/kubernetes/kubernetes/blob/v1.3.6/pkg/util/util.go#L90).
You could check listing the directories in `/var/lib/kubelet/pods/<pod_uid>/volumes` to see if there is anything abnormal.

**Comment by Zapadlo** [comment]
Nothing in volumes looked out of place. We solved the issue by making sure all our workers are running on `1.4` - I have not seen this issue on `1.4` yet so happy to close and re-open a new one if it reappears.

Thanks @yujuhong
