### ISSUE TITLE
[CRI] Add HostPort Support for Dockershim

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#35457]
#34780 migrates the network logic into dockershim without adding hostport support.  `GetPodHostportMapping` method implemented by dockershim returns empty. This interface is a hook for network plugins to retrieve local pod hostport information, so that network plugins can implement the hostports. Need a way to retrieve hostport mapping from running pods in dockershim. This can be achieved by parsing container labels or caching.

**Comment by yujuhong** [comment]
I spoke to @bprashanth offline. In the long run, we want CNI to support host ports directly. Right now, we can either 1) adapt the the existing batch sync implementation and checkpoint the ports used by containers (via labels?) as suggested by @freehan initially, or 2) choose not to support host ports and wait for a better fix (favored by @bprashanth).

Just wanted to point out that host port support is less important for an experimental feature (CRI) in the 1.5 release. However, if we are going to wait for CNI to support this, it could potentially block kubelet to switch to the CRI implementation as the default in the near future.

@bprashanth @thockin, can the network team remove the milestone if we've decided to drop host port support in 1.5? Thanks!

**Comment by freehan** [comment]
ref: #31307

**Comment by freehan** [comment]
Merged https://github.com/kubernetes/kubernetes/pull/41223
