### ISSUE TITLE
don't apply securityopts in shim if docker < 1.9 

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#35466]
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker_manager.go#L1149
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/helpers.go#L197
I think both should do the same, so if we're dropping support for 1.9, maybe just drop it in both places? 
@kubernetes/sig-node

**Comment by Random-Liu** [comment]
@bprashanth Currently dockershim is targeting on docker 1.11. We may make it compatible with docker 1.10 later, but may not make it for docker 1.9.

**Comment by bprashanth** [comment]
Yeah i thought as much, though getting a working config with --experimental-runtime="" and a non-working config with --experimental-runtime="cri" is weird, especially since docker 1.9 is still default on ubuntu trustly. Feel free to close this out if we've already drawn that line.

**Comment by Random-Liu** [comment]
Thanks for reporting this, we'll track the compatibility issue in https://github.com/kubernetes/kubernetes/issues/29478.

Close this one. :)
