### ISSUE TITLE
federation: do not upload users kubeconfig as secret

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#35482]
Today, we create a secret with users kubeconfig for federation control plane to be able to talk to all federated clusters. 
Other alternatives:
- Admin should create a service account in the cluster that federation control plane needs access to (Ref https://github.com/kubernetes/kubernetes/pull/35154#issuecomment-255863762)
- federation control plane should send a Certificate signing request (CSR) to the cluster that it needs access to. An admin can them approve that request and federation control plane gets the required certs to talk to that cluster (Ref https://github.com/kubernetes/kubernetes/pull/35154#issuecomment-255880813)

cc @kubernetes/sig-cluster-federation @liggitt @madhusudancs

**Comment by quinton-hoole** [comment]
Closing old feature request.  We're tracking cluster authentication functionality elsewhere.
