### ISSUE TITLE
NodeController flag to disable all evictions

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#35499]
@mml suggested maybe we could add a flag to NodeController that disables all evictions, so if it freaks out and starts doing a lot of unwanted evictions due to a bug, an operator could restart it with the flag enabled to at least halt the damage. (I guess the benefit of this over just killing NodeController and making sure it doesn't restart, is that the other things NC does would be preserved.)

**Comment by mml** [comment]
Other advantages: depending on your method of pushing flags, it will also persist across crashes, restarts, reboots, etc., and could be code reviewed.
