### ISSUE TITLE
support for adding extra kubelet configuration

### ISSUE THREAD

**Issue by spacexnice** [kubernetes/kubernetes#35502]
# Support for adding extra Kubelet config

kubeadm should support for adding extra kubelet configuration while doing kubeadm init.   i want to add an extra [ --pod-infra-container-image] parameter to kubelet cmdline ,but cant find a parameter doing so.

**Comment by codablock** [comment]
I had to provide cloud-config flags to the kubelet and opened an issue with a proposal that may also solve your requirements: https://github.com/kubernetes/kubernetes/issues/36213

**Comment by spacexnice** [comment]
@codablock yes, that` correct !

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#32
