### ISSUE TITLE
node-selector in namespace can't merge with clusterDefaultNodeSelector

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/kubernetes#35500]
**Kubernetes version** (use `kubectl version`):
v1.5.0-alpha.1.857+c81816751387a2-dirty

**What happened**:
node-selector in namespace can't merge with clusterDefaultNodeSelector

**How to reproduce it** (as minimally and precisely as possible):

Enable "PodNodeSelector" admission controller in api-server
```
--admission-control-config-file="admission-control-config-file.cfg"
[root@ip-172-18-6-200 kubernetes]# cat admission-control-config-file.cfg 
podNodeSelectorPluginConfig:
 clusterDefaultNodeSelector: region=west
 ns2: os=centos,region=west
```
1. Create a namespace with "scheduler.alpha.kubernetes.io/node-selector": "env=test,infra=fedora"
kubectl create -f https://raw.githubusercontent.com/mdshuai/testfile-openshift/master/k8s/podnodeselector/ns1.yaml

2. Create a pod in namespace
kubectl create -f https://raw.githubusercontent.com/mdshuai/testfile-openshift/master/k8s/pod/hello-pod.yaml --namespace=ns1

3. Check the nodeSelector in pod
kubectl get pod hello-pod --namespace=ns1 -o json

**Actual results:**
3. The nodeSelector in pod is:
```
"nodeSelector": {
   "env": "test",
   "infra": "fedora"
},
```

**Expected results**
3.The nodeSelector in pod shoud be:
```
"nodeSelector": {
    "env": "test",
    "region": "west",
    "infra": "fedora"
},
```
**Anything else do we need to know**:
Create a pod in namespace without "scheduler.alpha.kubernetes.io/node-selector", the pod json contains clusterDefaultNodeSelector

**Comment by mdshuai** [comment]
@aveshagarwal @derekwaynecarr

**Comment by qq690388648** [comment]
The logic of "PodNodeSelector" admission controller is clear in code between https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/podnodeselector/admission.go#L192 and https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/podnodeselector/admission.go#L214, so I think the original intention of @aveshagarwal is the clusterDefaultNodeSelector only take effect where the "scheduler.alpha.kubernetes.io/node-selector" annotation absent, so what you found fit that.

**Comment by mdshuai** [comment]
@qq690388648 Thanks for your comment, I need  confirm with @aveshagarwal

**Comment by aveshagarwal** [comment]
@mdshuai Yes this is correct behavior as default cluster level selectors only take effect when a namespace does not have any selectors associated with it. So it is working as expected.

**Comment by aveshagarwal** [comment]
@derekwaynecarr I do not have enough permissions, could you assign this issue to me?

**Comment by aveshagarwal** [comment]
@mdshuai could you close it. thanks.
