### ISSUE TITLE
Move node affinity from annotations to api fields

### ISSUE THREAD

**Issue by rrati** [kubernetes/kubernetes#35518]
Moving the node affinity implementation out of annotations and into api fields, and from alpha->beta, should be done piecemeal to ensure functionality and sanity.  I would propose a process first porting the implementation/tests before attempting to promote from alpha->beta.  Porting would entail:
1. Remove the node affinity implementation in annotations and do not bother with backwards compatibility.  Worrying about backwards compatibility for an alpha feature will needlessly complicate the implementation.
2. Implement node affinity in api fields.
3. Port tests.

Once functionality has reached parity with the annotation implement, promote from alpha->beta.

@kubernetes/sig-scheduling

**Comment by timothysc** [comment]
@davidopp This morning @rrati and I conversed about doing a 2-part conversion to leverage https://github.com/kubernetes/kubernetes/issues/34508 , and aim for alpha-beta in 1.6.  

Thoughts?

**Comment by davidopp** [comment]
Can we move this discussion to #25319 ?

BTW I didn't fully understand your proposal. It sounds like you are proposing to remove the alpha annotations before any replacement is available. If so, that seems bad. I'm also unsure about not giving people one version where we support both alpha and beta, so that they have a chance to migrate.

**Comment by rrati** [comment]
I'm proposing a 2 step process for the migration. Step 1 is to change from annotations to api fields but keep the feature in alpha.  Once we have verified equivalent functionality using api fields that existed using annotations then we can promote from alpha->beta.

I'm also suggesting we not attempt to support/maintain compatibility for the annotations version.  Part of step 1 should be removing the annotations implementation completely.  It's an alpha feature and annotations have issues so lets rip off the band aid.  Trying to support both would, imo, be needlessly complicated.

**Comment by davidopp** [comment]
Just to make sure I understand what you're proposing:
1) Change from alpha annotation to alpha API field
2) Do a minor release
3) Change from alpha API field to beta API field
4) Do a minor release

Would you break compatibility twice in this scheme? (Break the people using alpha annotations when you do step 1, and break the people using alpha API field when you do step 3.) It would be better to only break people once.

It's still not clear to me why you are concern about going directly from alpha annotation to beta API field?

**Comment by rrati** [comment]
I am trying to reduce the number of moving parts.  Rather than convert from annotation to api fields and add changes needed to get from alpha->beta, I'm suggesting to separate the two steps.  It doesn't necessarily mean each step results in a release with those changes.  I'm just suggesting the work be done in 2 steps (ie 2 separate commits or sets of commits).

**Comment by davidopp** [comment]
Ah OK, yes, that seems reasonable. I thought you wanted separate releases.
