### ISSUE TITLE
Error : This might loop forever if there was some uncaught error during start up

### ISSUE THREAD

**Issue by Arun129** [kubernetes/kubernetes#35514]
Hi Team, 
I am experiencing the below issue which was given in the below screenshot:
![2016-10-25 17_54_45-root ip-172-31-59-144_](https://cloud.githubusercontent.com/assets/7767467/19685878/3cc7961a-9adc-11e6-9bd8-1c9bcc7c5748.png)

**Comment by Arun129** [comment]
Things I have tried :
I have attached some IAM policies to my current logged in user for full API Access
Policies like AmazonAPIGatewayInvokeFullAccess, AmazonAPIGatewayAdministrator, AdministratorAccess, AWSSupportAccess.
There is anything else to add apart from these policies. / Anyone tell me how to get a full access to AWS API's

**Comment by foxish** [comment]
cc @ymqytw

**Comment by ymqytw** [comment]
cc: @caesarxuchao

**Comment by justinsb** [comment]
Can I recommend using kops instead?  kube-up is in maintenance mode.

**Comment by justinsb** [comment]
kube-up is now fully removed, and kops is an official Kubernetes Community Project.  I more strongly recommend using kops now, but closing this issue as there is nothing we can fix here any longer.
