### ISSUE TITLE
Kubelet may reject static pods when the node is out of disk space, and will not retry them 

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#35521]
If a pod fails admission (admission controller, disk space, or network not ready as of #33347), it is not retried.

I think this is the cause of #35409

Working up a PR now... I am thinking of keeping a list of pods that were rejected, and reattempting them every housekeeping interval.

**Comment by yujuhong** [comment]
@justinsb pod phases progress monotonically. Once a pod has been rejected and transition to the "Failed" state, it is not supposed to go back to pending or running. I don't think kubelet should retry them

**Comment by justinsb** [comment]
But - for example - we check disk space in canAdmitPod.  That is a temporary condition.

How do you propose to handle this instead?

**Comment by yujuhong** [comment]
kubelet doesn't care about whether the condition is temporary or not (for regular pods). It assumes the control plane (e.g., ReplicaSet) can react and determine what to do.

**Comment by justinsb** [comment]
Hmmm.. that is tricky because of static pod manifests.  I put the network-readiness check in the same place as the disk space check, as I figured that was the closest analog.

Looking for a place to move it such that the pod can be admitted but won't start:

1) Any suggestion?
2) Should I move the disk free-space check there also?

**Comment by justinsb** [comment]
How about in `Kubelet::syncPod`?

**Comment by yujuhong** [comment]
> Hmmm.. that is tricky because of static pod manifests. I put the network-readiness check in the same place as the disk space check, as I figured that was the closest analog.

@justinsb hmm....even for regular pods, this behavior seems undesirable. If kubelet restarts, and the network plugin is not ready (due to podCIDIR) yet, it would reject all pods assigned to it. That seems to be what caused the serial suite to fail.

> How about in Kubelet::syncPod?

It might work. That just means kubelet will not sync the pod if network is not ready. I don't think disk space should be moved to the same space because kubelet actually wants to reject them.
/cc @dchen1107 

Can we revert your original PR first? Thanks.

**Comment by justinsb** [comment]
> Can we revert your original PR first? Thanks.

I feel like I've seen bad behaviour with full disks, so it feels like this is actually exposing a pre-existing problem.  I don't understand why we would permanently reject a static pod if the disk was full?

It feels like we should move both to syncPod...  I have a WIP PR which I'm testing now - can we give me a few minutes to see if that just fixes things, and then if not we can revert?

**Comment by justinsb** [comment]
Actually, on second thoughts, if we're blocking the submit queue we can just revert.  It sounds like this is a non-trivial issue, so it's worth finding the right solution.

**Comment by yujuhong** [comment]
> Actually, on second thoughts, if we're blocking the submit queue we can just revert. It sounds like this is a non-trivial issue, so it's worth finding the right solution.

I don't think it's blocking the submit queue. Since you no longer need to change the admission logic, there are parts in your original PR that's not needed anymore. I think reverting makes sense here, and will make cherrypicking easier too.

**Comment by yujuhong** [comment]
> I feel like I've seen bad behaviour with full disks, so it feels like this is actually exposing a pre-existing problem. I don't understand why we would permanently reject a static pod if the disk was full?

This is a bug, and it should be fixed. I changed the title to reflect that (thanks). The immediate solution if anyone encounters such a situation is to restart kubelet to let the pods go through the admission process again.

@justinsb I don't think your new PR needs to change the admission logic at all, so it shouldn't be affected by this bug.

**Comment by timstclair** [comment]
Related PR: https://github.com/kubernetes/kubernetes/pull/35342

Conditions which the scheduler is not aware of, or that should be retried on the same node should be "soft rejected", i.e. the pod should not be marked as failed, instead it should be blocked from starting.

**Comment by dchen1107** [comment]
Related to:  #22212

**Comment by gjkim42** [comment]
/unassign

I don't want to make another exception for static pods...

/priority backlog

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

need repro on the latest versions of confirmation from somebody experiencing it

**Comment by matthyx** [comment]
Please reopen if you experience this issue.
/close
