### ISSUE TITLE
Rename PetSet to StatefulSet

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#35534]
A list of things need to be changed for renaming `PetSet`. Feel free to extend the list:

**Pre code freeze**:
- [x] PetSet API (PR #35663)
  - types.go
  - API server related codes
    - register.go, conversion.go, defaults.go, validation.go, ...
    - client/cache/listers.go, clientset, unversioned client, ...
  - All other codes that referenced PetSet 
  - All yaml/json config files that include PetSet 
  - client-go
- [x] kubectl (PR #35663)
  - kubectl tests 
    - test-cmd.sh
    - hack/testdata - PetSet related config files 
  - Related “kubectl help” examples
  - kubectl get/describe 
- [x] All examples 
  - Example that mention PetSet are: (PR #35776)
    - examples//cockroachdb/…
    - examples//storage/cassandra/…
  - README docs
  - yaml/json config files
  - file names (do we care?)
  - example_test.go 
  - test/e2e/examples.go 
- [x] Dashboard (issue https://github.com/kubernetes/dashboard/issues/1395)

**Post code freeze**:
- [x] Fix test failures caused by rename (such as e2e tests that won't block submit queue)
- [x] Need advice on how to upgrade your cluster (issue ~#28706~ #35182) (PR https://github.com/kubernetes/kubernetes.github.io/pull/1704)
- [x] Helm Charts in incubator that currently use petSet need to be renamed and tested against a 1.5 cluster, once a beta with the new name is available, and they need to be documented as requiring 1.5 cluster to work. @viglesiasce 
- [x] Documents in kubernetes.io 
  - Petset docs 
  - Docs that talked about PetSet 
  - Docs that used commands that involved PetSet 
- [x] kubernetes/CHANGELOG.md 
- [x] blogpost (announce name change and update previous post)

**Move to 1.6**:
- [x] File names (include petset controller, petset tests) & import path (do we care?)
  - we care about e2e test file names 

Open questions:
- How do we rename “pets”? We can just call them "pods"
- Upgrade tests will be broken?

Ref #35182
cc @erictune @foxish @bprashanth @kubernetes/sig-apps @chrislovecnm @jimmycuadra

**Comment by hjacobs** [comment]
OMG, after the comments in #27430 I would have thought there would be some consideration, but here you go... (I can live with the rename, but I'm also somehow disappointed :disappointed: ).

**Comment by bprashanth** [comment]
I noticed you already have a pr for the first, thanks! We should focus on nailing the api change before code freeze.

**Comment by justinsb** [comment]
We should probably wait for the community to determine a name, right?

**Comment by bprashanth** [comment]
I think the poll is closed

**Comment by justinsb** [comment]
Perhaps, but the poll results have not been computed: https://github.com/kubernetes/kubernetes/issues/27430#issuecomment-256099586

Also, presumably we should check to see if there are objections to the winner, unless you want to do this twice :-)

Also, perhaps the reason PetSet was excluded was because we are now going to ask the community to vote on "PetSet vs winner".

**Comment by chrislovecnm** [comment]
File names we care, impacts e2e tests

**Comment by chrislovecnm** [comment]
@justinsb it has been renamed ;) It is done, now let's rename this poodle. Oh wait StatefulSet

**Comment by chrislovecnm** [comment]
@janetkuo I know we have code that references filenames as well. C* e2e tests for instance.

**Comment by chrislovecnm** [comment]
@janetkuo do we want to put blog posts in here as well. Probably want to add a note about the name change to some of the posts on our blog.

**Comment by m1093782566** [comment]
@janetkuo I am working on improve PetSet(StatefulSet) test coverage, I will be glad to do some help.

**Comment by janetkuo** [comment]
@chrislovecnm thanks for the suggestions! Issue description updated. @m1093782566 thanks please refer to #35663 and #35731 for renaming PetSet and moving it to v1beta1

**Comment by chrislovecnm** [comment]
@janetkuo can we make reference in the Cassandra example that Stateful set is the feature previously known as PetSet? I don't have time for updates as I have a week before kubecon :( Too much code to write.

**Comment by janetkuo** [comment]
> @janetkuo can we make reference in the Cassandra example that Stateful set is the feature previously known as PetSet? I don't have time for updates as I have a week before kubecon :( Too much code to write.

@chrislovecnm - @jimmycuadra has a PR for it (#35776)

**Comment by chrislovecnm** [comment]
@janetkuo thanks ;) Already commented on it

**Comment by janetkuo** [comment]
We should still mention that StatefulSet is formerly known as PetSet in types.go and in StatefulSet doc, so that if people search for "PetSet" or only know PetSet, they can still find it.

**Comment by janetkuo** [comment]
Dashboard needs to be updated as well.

**Comment by chrislovecnm** [comment]
@janetkuo are your checkmarks on top up to date?

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kubernetes/issues/36323 is blowing up.  @janetkuo @bprashanth did we not merge correctly?

**Comment by jimmycuadra** [comment]
#36418 will fix #36323. Waiting for someone to review/merge.

**Comment by janetkuo** [comment]
@chrislovecnm this happened because example e2e tests aren't blocking submit queue (so it's failing but unnoticed)

**Comment by chrislovecnm** [comment]
@janetkuo / @jimmycuadra and another https://github.com/kubernetes/kubernetes/issues/36469

@jimmycuadra not sure if you have dealt with flakes before, but we should have multiple tickets open because of this.  Please track down the filename that is blowing up in tickets and ensure those are linked and closed to the PR.

**Comment by foxish** [comment]
It appears that the cassandra flakes are fixed. I'll take a look at the other long failing spark e2e test in https://github.com/kubernetes/kubernetes/issues/36102 today.

**Comment by bryk** [comment]
UI rename done.

**Comment by dims** [comment]
@janetkuo : would you mark this as non-release-blocker or release-blocker as appropriate please? (by end of day today - Nov 18)

**Comment by chrislovecnm** [comment]
@dims this is a release blocker ... Ping @janetkuo ;)

**Comment by erictune** [comment]
Filenames can move to 1.6.

**Comment by janetkuo** [comment]
> - [ ] Helm Charts in incubator that currently use petSet need to be renamed and tested against a 1.5 cluster, once a beta with the new name is available, and they need to be documented as requiring 1.5 cluster to work. 

@viglesiasce are you working on this one?

**Comment by niemyjski** [comment]
Any word when StatefulSets will be stable? I see mention of beta in 1.5 and this issue and then this is tagged in for 1.6 as well.

**Comment by smarterclayton** [comment]
StatefulSets are in beta for 1.5.  They will be in beta for several
releases at least while we close out functionality that makes them useful
and helpful.

**Comment by janetkuo** [comment]
All the work was done, closing
