### ISSUE TITLE
firewalld breaks kubeadm

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#35535]
Some users reported this, and it looks like disabling it solves the problem, but I'd like to find out what rules need to be added to make things work. I've been able to make most things work (see https://github.com/errordeveloper/kubernetes-ansible-vagrant/commit/67a4d87021f95b108e46f6a45a11f2f3786726f9), but lacking pod to master right now.

**Comment by foxish** [comment]
cc @kubernetes/sig-cluster-lifecycle

**Comment by dgoodwin** [comment]
Spoke with @danwinship briefly, he has confirmed that you should not need to disable firewalld entirely, however it would block host ports by default and those rules would need to be disabled which I believe matches what @errordeveloper had to do in the branch linked above.

**Comment by luxas** [comment]
I guess the best we can do here is to document it

**Comment by errordeveloper** [comment]
@luxas yes, and also warn in pre-flight checks that users may need to disable it or relax some of the rules.

**Comment by errordeveloper** [comment]
@dgoodwin thank you. I'll take another look for what needs to be done, I've been using kube-proxy in userspace mode so far (due to VirtualBox networking issues), but will take a look at other options (there are a few, e.g. iptables mode with masquarade).

**Comment by errordeveloper** [comment]
We also have https://github.com/kubernetes/contrib/blob/master/ansible/roles/node/tasks/firewalld.yml, which I tried to adopt, but I need to re-test to confirm if it works or not (it didn't seem to work in my previous test, but may be I've missed something).

**Comment by errordeveloper** [comment]
As I've been testing on VirtualBox, I've had to pass `--proxy-mode=userspace` to `kube-proxy`, changing it for `--cluster-cidr=10.32.0.0/12` and adding `10.32.0.0/12` as an allowed source, appears to work, yet I need to re-test a few more times.

**Comment by errordeveloper** [comment]
Latest code is in https://github.com/errordeveloper/kubernetes-ansible-vagrant.

**Comment by luxas** [comment]
Does it work with `10.96.0.0/12` --cluster-cidr as well if you explicitely allow that?

**Comment by errordeveloper** [comment]
@luxas this is a bit confusing, but `kube-proxy --cluster-cidr=...` means the pod CIDR, not service CIDR.

**Comment by luxas** [comment]
Ah, sorry. I thought you were talking about `kubeadm --cluster-cidr` :)

**Comment by luxas** [comment]
Should we make a preflight check that checks if `firewalld` is enabled and warns the user that it might fail because of that it's enabled?

**Comment by dgoodwin** [comment]
Port 9898 (discovery) is about to go away. API server is another question. We definitely need to document the step to open that port if firewalld is enabled. Perfect work the preflight check would detect firewalld, and then actually make sure the port is open. Not sure how easy or difficult that would be, I could look into it in time.

Hesitant to just always warn if firewalld is enabled, it's enabled by default in some distros and should work fine with k8s overall, it would be unfortunate to have users constantly seeing that warning and wondering about it even if they took action. 

Maybe for now and we could improve with actual port checking later.

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#21
