### ISSUE TITLE
Clusters built with kubeadm don't support basic auth

### ISSUE THREAD

**Issue by kelseyhightower** [kubernetes/kubernetes#35536]
Some people are having trouble authenticating to the Kubernetes dashboard when the cluster is built with kubeadm. Seems like the deployed api server does not support basic auth, which makes it impossible to hit the Dashboard UI without using `kubectl proxy`.

**Comment by Hirayuki** [comment]
if needed I can reproduce the issue and give outputs tomorrow

**Comment by mikedanese** [comment]
@kubernetes/sig-cluster-lifecycle

**Comment by jbeda** [comment]
Opinions on what the experience should be here?

We could create an admin user and output the password as part of `kubeadm join`.  

But, to be honest, basic auth is a bit of a hack as to change those accounts you need to edit a file and restart the apiserver.  This'll also be a problem as we move to HA.

Options:
* Improve password auth so that accounts are stored in etcd and can be managed.
* Enhance kubeadm to set up other authenticators.  This'll be a more complicated setup process, for sure.

**Comment by kelseyhightower** [comment]
@jbeda It could be as simple as updating the docs and highlight that you must use kubectl proxy to "authenticate" to the Kubernetes Dashboard and other add-ons.

**Comment by roberthbailey** [comment]
> But, to be honest, basic auth is a bit of a hack as to change those accounts you need to edit a file and restart the apiserver. This'll also be a problem as we move to HA.

This is the same problem as with the bearer token auth. They were both built without taking HA requirements into account.

Until we have another solution that works for a web browser (oauth anyone?), having basic auth is an important part of the user experience for folks that want to access services through the apiserver proxy (e.g. the dashboard). 

I think the best option would be to replace basic auth with something better, but in absence of that improving it so that passwords are stored in etcd rather than in a csv file seems like it wouldn't be too difficult and wouldn't add extra complexity to kubeadm.

**Comment by jbeda** [comment]
I like the idea of documenting the `kubectl proxy` method. That is no code changes and provides immediate relief.

I'd say we need to document the following:
* How to copy/extract the admin.conf kubeconfig from the master VM
* How to import/merge that in to your ~/.kube directory.
* How to rewrite the target for the cluster if there is an inner/outer IP issue
* How to use the proxy command to connect to the cluster to get the dashboard

Anyone want to take this on?

**Comment by broady** [comment]
This page also needs updating:
http://kubernetes.io/docs/user-guide/ui/#dashboard-access

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#23

**Comment by vhosakot** [comment]
I see this issue too with kubernetes `1.5.4` and kubernetes-dashboard image version `gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0`.

I installed `kubeadm` referring https://kubernetes.io/docs/getting-started-guides/kubeadm/, and then installed kubernetes-dashboard by doing

```
kubectl apply -f https://raw.githubusercontent.com/projectcalico/canal/master/k8s-install/kubeadm/canal.yaml
```

I see the kubernetes-dashboard in `CrashLoopBackOff` status and the `k8s_kubernetes-dashboard.*` container on the worker is in `Exited` state.

Below are the errors.  Has anyone successfully installed kubernetes-dashboard on `kubeadm`?

```
# kubectl --namespace=kube-system get all
NAME                                                          READY     STATUS             RESTARTS   AGE
po/calico-policy-controller-mqsmh                             1/1       Running            0          4h
po/canal-etcd-tm2rv                                           1/1       Running            0          4h
po/canal-node-3nv2t                                           3/3       Running            0          4h
po/canal-node-5fckh                                           3/3       Running            1          4h
po/canal-node-6zgq8                                           3/3       Running            0          4h
po/canal-node-rtjl8                                           3/3       Running            0          4h
po/dummy-2088944543-09w8n                                     1/1       Running            0          4h
po/etcd-vhosakot-kolla-kube1.localdomain                      1/1       Running            0          4h
po/kube-apiserver-vhosakot-kolla-kube1.localdomain            1/1       Running            2          4h
po/kube-controller-manager-vhosakot-kolla-kube1.localdomain   1/1       Running            0          4h
po/kube-discovery-1769846148-pftx5                            1/1       Running            0          4h
po/kube-dns-2924299975-9m2cp                                  4/4       Running            0          4h
po/kube-proxy-0ndsb                                           1/1       Running            0          4h
po/kube-proxy-h7qrd                                           1/1       Running            1          4h
po/kube-proxy-k6168                                           1/1       Running            0          4h
po/kube-proxy-lhn0k                                           1/1       Running            0          4h
po/kube-scheduler-vhosakot-kolla-kube1.localdomain            1/1       Running            0          4h
po/kubernetes-dashboard-3203962772-mw26t                      0/1       CrashLoopBackOff   11         41m
NAME                       CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
svc/canal-etcd             10.96.232.136    <none>        6666/TCP        4h
svc/kube-dns               10.96.0.10       <none>        53/UDP,53/TCP   4h
svc/kubernetes-dashboard   10.100.254.77    <nodes>       80:30085/TCP    41m
NAME                   DESIRED   SUCCESSFUL   AGE
jobs/configure-canal   1         1            4h
NAME                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/kube-discovery         1         1         1            1           4h
deploy/kube-dns               1         1         1            1           4h
deploy/kubernetes-dashboard   1         1         1            0           41m
NAME                                 DESIRED   CURRENT   READY     AGE
rs/calico-policy-controller          1         1         1         4h
rs/dummy-2088944543                  1         1         1         4h
rs/kube-discovery-1769846148         1         1         1         4h
rs/kube-dns-2924299975               1         1         1         4h
rs/kubernetes-dashboard-3203962772   1         1         0         41m

# kubectl --namespace=kube-system describe pod kubernetes-dashboard-3203962772-mw26t
  20m    5s    89    {kubelet vhosakot-kolla-kube2.localdomain}                        Warning    FailedSync    Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-3203962772-mw26t_kube-system(67b0d69b-0b47-11e7-8c97-7a2ed4192438)"

# kubectl --namespace=kube-system logs kubernetes-dashboard-3203962772-mw26t
Using HTTP port: 9090
Creating API server client for https://10.96.0.1:443
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.96.0.1:443/version: dial tcp 10.96.0.1:443: i/o timeout
Refer to the troubleshooting guide for more information: https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md

# docker ps -a | grep -i dash
3c33cf43d5e4        gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0   "/dashboard --port=90"   54 seconds ago      Exited (1) 22 seconds ago                       k8s_kubernetes-dashboard.9eb4d80e_kubernetes-dashboard-3203962772-mw26t_kube-system_67b0d69b-0b47-11e7-8c97-7a2ed4192438_93520bd4

# docker logs k8s_kubernetes-dashboard.9eb4d80e_kubernetes-dashboard-3203962772-mw26t_kube-system_67b0d69b-0b47-11e7-8c97-7a2ed4192438_93520bd4
Using HTTP port: 9090
Creating API server client for https://10.96.0.1:443
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.96.0.1:443/version: dial tcp 10.96.0.1:443: i/o timeout
Refer to the troubleshooting guide for more information: https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md
```

**Comment by badloop** [comment]
I did successfully install the dashboard, and its running, but I can't seem to authenticate using any of the tokens that are in the list of secrets.

**Comment by vglisin** [comment]
Hello. Can you "kubernetes masters" stop showing off how smart you are and give people who are very brand new in Kubernetes how to pass that famous: "Kubernetes Dashboard" with Kubeconfig & Token ANY idea HOW to login??? I can't explain how much this is irritating and how much you are too proud of things you already know and how FAR you are from people how are starting to learn. This is one of reason why people give up on such smart .....s!
Sorry to write things like this but if somebody doesn't kick you you will are going to admire each other and this wonderful technology and idea will die in its tracks. Nobody will spent two months trying to figure out how this works.
Bye!

**Comment by errordeveloper** [comment]
@vglisin have you seen https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above?
