### ISSUE TITLE
Question about namespace best practices

### ISSUE THREAD

**Issue by ranhsd** [kubernetes/kubernetes#35539]
Hi , I did some quick search on the internet about kuberbetes namespaces and all the examples that i found use namespaces in order to separate between dev,test,staging,prod env. In my project i am planning to have 2 clusters: one for test and staging (will be separated by namespaces of course) and the other one for production. 
I wanted to know if the best practice of using namespaces is only when you want to separate between the env. or the best practices is to put each of the different layer in the cluster in a namespace (e.g. namespace for application layer, namespace for database layer, namespace for UI layer etc.). 
I know that technically it is possible (because this is how it works in my cluster) but i wanted to know if this is the best practice or i should move all the layer to sit under the same namespace and use namespaces only for various env.

Thanks in advanced!

**Comment by qq690388648** [comment]
As I know, the services in different namespaces are isolated, so how can the different layer find each other where you put them into different namespaces?

**Comment by ranhsd** [comment]
hi @qq690388648 - by creating internal service and then access it the following way {service_name}.{namespace_name}. If you will create a service you will see the URL .

**Comment by qq690388648** [comment]
@ranhsd Yes, you are right, I have forgot the dns.

**Comment by bgrant0607** [comment]
Please ask on stackoverflow and take a look at the 2 previous blog posts on this topic.

http://kubernetes.io/docs/troubleshooting/
