### ISSUE TITLE
Tag all storage E2E tests with [Storage] tag so that they can be run explicitly

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#35542]
We have storage E2E tests sprinkled across multiple test suites. When trying to run all storage tests, it is difficult to know which ones to run. To fix this, we should tag all storage/volume plugin e2e tests with the `[Storage]` tag. 

@kubernetes/sig-storage

**Comment by rootfs** [comment]
would volume work? storage is something used for api storage (etcd)

**Comment by saad-ali** [comment]
> would volume work? storage is something used for api storage (etcd)

Yep, volume works!

**Comment by saad-ali** [comment]
Assigning to @msau42, who has graciously offered to work on this

**Comment by jeffvance** [comment]
@saad-ali where is the line for "[Storage]". If I test that an nfs mount is cleaned up when a pod bound to that mount is killed, is that a storage test? What about testing that a PVC binds to the expected PV, is that storage?  Thanks.

**Comment by saad-ali** [comment]
> @saad-ali where is the line for "[Storage]". If I test that an nfs mount is cleaned up when a pod bound to that mount is killed, is that a storage test? What about testing that a PVC binds to the expected PV, is that storage? Thanks.

Good question. My feeling is that anything that the storage-sig is responsible should fall in to the label (including all volume plugins, attach/detach controller, kubelet, persistent volume controller). So yes, all your examples should fall in to this label. The idea here is that when we make big breaking changes to some part of the storage infrastructure, we should be able to run all storage E2Es against the change with one command. Optionally we could have a storage test suite that runs all theses tests as part of CI.

**Comment by jeffvance** [comment]
@saad-ali I agree and have updated in flight pr #38214
