### ISSUE TITLE
Parts of the Kubernetes world ignore the kubeadm init --api-advertise-addresses values

### ISSUE THREAD

**Issue by Crazee** [kubernetes/kubernetes#35547]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
1.4.0

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS (Xenial Xerus)
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
I'm trying to set up a cluster across AWS region boundaries.  Set up a master in Virginia.  Joined a node from Oregon.  "kubectl get nodes" shows both nodes.  But doing a "kubectl create" of a deployment from the master never gets the pods running.  They just show up as "ContainerCreating" forever.

I have an overlay network connecting the nodes and use --api-advertise-addresses on kubectl init to point at the address to use.  But looking at the logs I see bits that ignore the address I gave it and decide it knows better and wants to use eth0:

```
I1020 22:55:04.819408       1 interface.go:138] Interface "eth0" has 2 addresses :[10.6.7.202/24 fe80::c89:b2ff:fec5:8bd4/64].
I1020 22:55:04.819431       1 interface.go:105] Checking addr  10.6.7.202/24.
I1020 22:55:04.819440       1 interface.go:114] IP found 10.6.7.202
I1020 22:55:04.819450       1 interface.go:144] valid IPv4 address for interface "eth0" found as 10.6.7.202.
I1020 22:55:04.819459       1 interface.go:254] Choosing IP 10.6.7.202 
I1020 22:55:04.819471       1 genericapiserver.go:630] Will report 10.6.7.202 as public IP address.
[restful] 2016/10/20 22:55:04 log.go:30: [restful/swagger] listing is available at https://10.6.7.202:443/swaggerapi/
[restful] 2016/10/20 22:55:04 log.go:30: [restful/swagger] https://10.6.7.202:443/swaggerui/ is mapped to folder /swagger-ui/
```
No, 10.6.7.202 is the wrong address -- it won't work across different data centers.

**What you expected to happen**:

I expected all bits of Kubernetes to use *only* the IP address I gave in --api-advertise-addresses.

**Comment by luxas** [comment]
@Crazee Oh wait, please take a look at https://github.com/kubernetes/kubernetes/issues/35043 and propose there what should be done.

Thanks!
