### ISSUE TITLE
Make scheduler less dependent on events for metadata and reasons

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#35555]
Problem

As of now, the scheduler is slated to make lots of events (per pod) especially on failures.  #20064 attempts to improve the quality of data for scheduling, and may or may not reuse the existing hacky events based data channel .... Specifically, in the scheduler, we need to SPAM less events...

Solution
- _Event is a report of an event somewhere in the cluster._ Is the current definition of an event,  we need to make it more precise to discourage SPAM :) 
- This means, _put a `SchedulingInfo` or similar struct onto Pod objects, that supports meta-scheduling info, that graduates to a first class API call_, so that we dont need to spam the event channel w/ bulk decision info for pods.
- This `SchedulingInfo` data structure  would generate a small amount of data attached to each pod.  Rather than a large amount of global events data. 

(re: `SchedulingInfo` possibly there is stuff we can reuse in scheduling types.go, will look into it more)

**Comment by jayunit100** [comment]
cc @timothysc

**Comment by timothysc** [comment]
I'd consider this step-0 before reason.

**Comment by jayunit100** [comment]
talked to tim, step-0 not technically, but b/c higher prio to clean event spam then to add the feature.

**Comment by timothysc** [comment]
Second 1/2 is addressed by #37858

**Comment by jayunit100** [comment]
@timothysc you mean #39491  :) now

**Comment by jayunit100** [comment]
this is done with the reasons and event squashing PRs above.
