### ISSUE TITLE
Question: Can vendor LGPL3 Go code be included?

### ISSUE THREAD

**Issue by lpabon** [kubernetes/kubernetes#35557]
In our [GlusterFS storage manager](https://github.com/heketi/heketi) we are contemplating changing our license from Apache 2 to LPGL 3.

Currently this code is used in the [vendor/...](https://github.com/kubernetes/kubernetes/tree/master/vendor/github.com/heketi/heketi) for the storage dynamic provisioner of GlusterFS.  Would there be any conflicts if we change license?

I also noticed that the [Yaml](https://github.com/kubernetes/kubernetes/blob/master/vendor/gopkg.in/yaml.v2/README.md) code is currently using a LGPL3 with a clause to allow static linking, although they changed their license in their [repo to Apache 2](https://github.com/go-yaml/yaml/commits/v2/LICENSE).

**Comment by foxish** [comment]
cc @sarahnovotny

**Comment by bgrant0607** [comment]
We should file a separate issue about this somewhere (maybe not in this repo):

We need an official, documented policy about which licenses are permitted.

Probably some subset of these:
https://opensource.org/licenses

cc @kubernetes/contributor-experience

**Comment by sarahnovotny** [comment]
This is one of the places where I would like to get CNCF Legal advice.  @dankohn and or @caniszczyk  can you work with the LF lawyers to list CNCF acceptable licenses for /vendor within our project?

**Comment by caniszczyk** [comment]
@sarahnovotny alright, we'll put this on the list, it's not super clear in the CNCF Charter's IP Policy, but we would lean towards permissive licensed options (ASL, MIT etc)

@lpabon I'd give you advice to keep the Apache license here was going to a less permissive license isn't the best idea for adoption IMHO (also license changes are never fun)

**Comment by obnoxxx** [comment]
@caniszczyk I am not a lawyer, but if I get it right, the IP section of the CNCF charter is relevant for contributions to the actual project's code, not so much for the external project's code included under vendor/ - correct? 

And I appreciate the hint regarding adaption, but the major question here is whether relicensing the heketi parts (under vendor/) to LGPLv3 would be problematic for the kubernetes project. We'll care about the broader adaption separately.

**Comment by caniszczyk** [comment]
@obnoxxx we would really prefer permissive licenses and licenses that match the parent project, it simplifies distribution, thanks!

**Comment by dankohn** [comment]
It appears that heketi decided on a license: https://github.com/heketi/heketi/blob/master/LICENSE

Note that the CNCF charter applies to both the licenses of a project's code and its dependencies, and that there are concerns with LGPLv3. But since this project is dual-licensed, that doesn't apply.

**Comment by dims** [comment]
We still have files that are just `LGPLv3` OR `GPLv2` in the code we pull in from heketi:
https://cs.k8s.io/?q=or%20the%20GNU%20General%20Public%20License%2C%20version%202&i=nope&files=&repos=kubernetes/kubernetes

We had a couple of attempts from our side in https://github.com/kubernetes/kubernetes/pull/67448 and https://github.com/kubernetes/kubernetes/pull/66305, but we cannot fix it in k/k repository.

Please see https://github.com/heketi/heketi/issues/1279 that tracks the problem in heketi repo

**Comment by dims** [comment]
FWIW, the intent in the https://github.com/heketi/heketi/blob/master/LICENSE is very clear, However it does not match the files we need for GlusterFS in-tree plugin to work in k/k

**Comment by dims** [comment]
cc @jsafrane @childsb @obnoxxx @humblec @saad-ali

**Comment by dims** [comment]
/sig release
/sig architecture

cc @kubernetes/steering-committee

**Comment by timothysc** [comment]
@dims do we have a tracking issue on the steering board that we can cross ref?

**Comment by dims** [comment]
@timothysc xref https://github.com/kubernetes/steering/issues/57

**Comment by AishSundar** [comment]
Is it something we think will land in 1.13 with Code freeze on 11/16? I am adding the 1.13 milestone anyway to keep this in our radar

/milestone v1.13

**Comment by AishSundar** [comment]
if we are targeting this for 1.13, the Code freeze date is 11/16.

**Comment by humblec** [comment]
@dims apologies for the lack of updates in heketi issue. We are on it :)

**Comment by AishSundar** [comment]
Looks like we now have https://github.com/kubernetes/kubernetes/issues/70802 issue to track this work in k/k. So I will remove this from the 1.13 milestone. Please post all progress to https://github.com/kubernetes/kubernetes/issues/70802. Thanks

/remove milestone

**Comment by dims** [comment]
heketi license issue has been taken care of 

/close
