### ISSUE TITLE
Node e2e framework doesn't populate `started.json`

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#35558]
The cluster e2e framework creates a `started.json` file, but node e2e framework doesn't. 
I think that may be the root cause of not seeing "commit hash" displayed in test-grid for node e2e tests.

```
{
    "version": "v1.5.0-alpha.1.893+bcdb2185322968",
    "timestamp": 1477427259,
    "jenkins-node": "agent-light-14"
}
```

/cc @dchen1107 @Random-Liu

**Comment by Random-Liu** [comment]
@yujuhong Thanks for filing this issue! :)

**Comment by yujuhong** [comment]
@dashpole maybe something to pick up if you have spare cycles :-)

**Comment by dashpole** [comment]
I could probably get to it by the end of the day today.  It should be super simple, right?

**Comment by Random-Liu** [comment]
I found that we have a [gubernator script](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/gubernator.sh) which will populate started.json and finished.json, we should test it. If it works, we should enable it with `--gubernator=true` in `jenkins/e2e-node-jenkins.sh`.

**Comment by Random-Liu** [comment]
Confirmed with @krzyzacy that testgrid use the `started.json` to populate the commit number.

We should generate `started.json` and `finished.json` in [`RunRemote`](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/remote/remote.go#L156), where we should be able to get all necessary information.
