### ISSUE TITLE
Setting NODE_IMAGE_PROJECT in cluster/gce/config-default.sh seems to have no effect

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#35569]
While trying a vm image today, I directed `cluster/gce/config-default.sh` to use an alternative `NODE_IMAGE_PROJECT` by changing:

```
NODE_IMAGE_PROJECT=${KUBE_GCE_NODE_PROJECT:-google-containers}
```

to:

```
NODE_IMAGE_PROJECT=${KUBE_GCE_NODE_PROJECT:-mtaufen-cvm-build}
```

This had no effect on the project where the chain of scripts following `cluster/kube-up.sh` looked for the node image. The following had the effect I was looking for:

In `cluster/gce/util.sh`, change:

```
function set-node-image() {
  if [[ "${NODE_OS_DISTRIBUTION}" == "gci" ]]; then
    # If the node image is not set, we use the latest GCI image.
    # Otherwise, we respect whatever is set by the user.
    NODE_IMAGE=${KUBE_GCE_NODE_IMAGE:-${GCI_VERSION}}
    NODE_IMAGE_PROJECT=${KUBE_GCE_NODE_PROJECT:-google-containers}
  elif [[ "${NODE_OS_DISTRIBUTION}" == "debian" ]]; then
    NODE_IMAGE=${KUBE_GCE_NODE_IMAGE:-${CVM_VERSION}}
    NODE_IMAGE_PROJECT=${KUBE_GCE_NODE_PROJECT:-google-containers}
  fi
}
```

to:

```
function set-node-image() {
  if [[ "${NODE_OS_DISTRIBUTION}" == "gci" ]]; then
    # If the node image is not set, we use the latest GCI image.
    # Otherwise, we respect whatever is set by the user.
    NODE_IMAGE=${KUBE_GCE_NODE_IMAGE:-${GCI_VERSION}}
    NODE_IMAGE_PROJECT=${KUBE_GCE_NODE_PROJECT:-google-containers}
  elif [[ "${NODE_OS_DISTRIBUTION}" == "debian" ]]; then
    NODE_IMAGE=${KUBE_GCE_NODE_IMAGE:-${CVM_VERSION}}
    NODE_IMAGE_PROJECT=${KUBE_GCE_NODE_PROJECT:-mtaufen-cvm-build}
  fi
}
```

Sort of strange that something would unset `KUBE_GCE_NODE_PROJECT`.

I need to look at this again in the morning when I'm more awake.

/cc @vishh

**Comment by roberthbailey** [comment]
@mtaufen - based on your report, you didn't actually set `KUBE_GCE_NODE_PROJECT` and have it get overridden. You set a new default for `NODE_IMAGE_PROJECT` which is explicitly overridden later in the scripts (which still respect changes you may have made to `KUBE_GCE_NODE_PROJECT`). 

I think this should work as expected if you run `export KUBE_GCE_NODE_PROJECT=mtaufen-cvm-build` in your shell prior to running `kube-up.sh`.

**Comment by roberthbailey** [comment]
I'm assuming that you either fixed this or found a workaround since there haven't been any updates in a few months.

**Comment by mtaufen** [comment]
Yeah sorry, I should have closed this a long time ago.
