### ISSUE TITLE
Federation tests have not passed in a very long time

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#35588]
I do not see any evidence of the federation tests ever passing: https://k8s-testgrid.appspot.com/google-federation

Is there a plan to get these tests working? If not can we disable them to free up these resources to run other tests?

**Comment by quinton-hoole** [comment]
Yes, we're working on getting them passing.  Please do not disable.  All but one are passing now.

**Comment by fejta** [comment]
Are we still working on these @nikhiljindal

**Comment by fejta** [comment]
?

**Comment by nikhiljindal** [comment]
We have them under control now. All are green :)
