### ISSUE TITLE
Phase Pending under spec.status key when pod is in Terminating

### ISSUE THREAD

**Issue by anioool** [kubernetes/kubernetes#35607]
Hi guys,

I found situation when pod with state Terminating (kubectl get pods command - text output) has phase set to Pending under the spec.status.phase key when i fetch json output.

Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:45:16Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4+coreos.0", GitCommit:"be9bf3e842a90537e48361aded2872e389e902e7", GitTreeState:"clean", BuildDate:"2016-08-02T00:54:53Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by ymqytw** [comment]
There are no `Terminating` phase for `spec.status.phase`. Valid phases are `pending|running|succeeded|failed|unknown`. [Ref](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L1601)
What happened here is:
If a pod has an non empty `deletionTimestamp`, it will be considered as `Terminating` by `kubectl`. `kubectl get pods` will print that status out for you.

**Comment by anioool** [comment]
@ymqytw,
Thanks for explanation. At least now I know why i had different values. I will update my scripts.
