### ISSUE TITLE
kubelet dpkg installation: `[[` referenced in a POSIX shell

### ISSUE THREAD

**Issue by erikh** [kubernetes/kubernetes#35649]
**Is this a request for help?** No

**What keywords did you search in Kubernetes issues before filing this one?** 

`kubelet install [[`
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**: vmware 12.5
- **OS** (e.g. from /etc/os-release): ubuntu 16.04
- **Kernel** (e.g. `uname -a`): Linux ubuntu 4.8.0-26-generic #28-Ubuntu SMP Tue Oct 18 14:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**: kubeadm/dpkg/apt
- **Others**:

**What happened**:
```
/var/lib/dpkg/info/kubelet.postinst: 38: /var/lib/dpkg/info/kubelet.postinst: [[: not found
Created symlink /etc/systemd/system/multi-user.target.wants/kubelet.service → /lib/systemd/system/kubelet.service.
Setting up kubeadm (1.5.0-alpha.0-1534-gcf7301f-00) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for systemd (231-9git1) ...
```

**What you expected to happen**:

No warnings/errors during installation

**How to reproduce it** (as minimally and precisely as possible):

Install kubelet from https://packages.cloud.google.com/apt

**Anything else do we need to know**:

This is because /bin/sh is used instead of /bin/bash

This should fix it, but I haven't tested.

```
# kubelet is linked against /lib/ld-linux.so.3. On some systems, this symlink has to be present
if [ "$(uname -m)" == "arm"* ] && [ ! -f /lib/ld-linux.so.3 ] && [ -f /lib/ld-linux-armhf.so.3 ]; then
        ln -s /lib/ld-linux-armhf.so.3 /lib/ld-linux.so.3
fi
```

The problem is that `[[` is not valid for POSIX bourne shells, which either provide a builtin or rely on `/usr/bin/[` (maybe `/bin/[` some places) depending on the implementation. Bash and zsh provide these (ksh too?). This is how you write it to be compatible.

You may want to quote `uname` too.

**Comment by erikh** [comment]
mm `"arm"*` is probably incompatible but this will work: `"$(uname -m) | grep -vE '^arm'`

**Comment by erikh** [comment]
sorry this is about the kubelet post-install, not kubeadm.

**Comment by luxas** [comment]
Thanks for the bug report and the will to help, but I actually fixed this some hours ago.
See: https://github.com/kubernetes/release/pull/175

Feel free to look at some of the other kubeadm bugs if you're interested in helping :)

**Comment by erikh** [comment]
oh great! Thanks.

**Comment by errordeveloper** [comment]
Thanks, @erikh! @luxas is working on this and has a PR open.
