### ISSUE TITLE
kubeadm join should accept a hostname

### ISSUE THREAD

**Issue by bboreham** [kubernetes/kubernetes#35640]
**FEATURE REQUEST**

**Kubernetes version** (use `kubectl version`):
1.4.0

**What happened**:

````
# kubeadm join example.com
error: <cmd/join> failed to parse argument ("example.com") as an IP address
````

**What you expected to happen**:

It should resolve the hostname and then proceed as if an IP address had been given.

**Comment by lukemarsden** [comment]
cc @kubernetes/sig-cluster-lifecycle

**Comment by redhatlinux10** [comment]
has this feature request been assigned to someone ?  if not, i can do it.

**Comment by pires** [comment]
@redhatlinux10 go!

**Comment by redhatlinux10** [comment]
hi @bboreham , the feature you suggested has already been implemented. see #33919

thanks !

**Comment by luxas** [comment]
Yes, thanks @redhatlinux10!

@bboreham I'll close this, but if it isn't working with the unstable (master) releases of kubeadm, reopen
