### ISSUE TITLE
kube-proxy iptables rules not created

### ISSUE THREAD

**Issue by carsonoid** [kubernetes/kubernetes#35641]
**Kubernetes version**

1.4.0

**Environment**:
- aws
- Ubuntu 16.04
- 4.4.0-22-generic

**What happened**:

1 of 6 nodes in a cluster stopped connecting to other services.  

After looking at `ps fax` I could see that there was a `[iptables] <defunct>` process child of kube-proxy. `iptables-save` was also missing all of the service rules.

Restarting the kube-proxy container caused the rules to be created and services started to work.

**What you expected to happen**:

The correct iptables rules should have been made.

**How to reproduce it** (as minimally and precisely as possible):

Unable to reproduce

**Anything else do we need to know**:

kube-proxy logs.

```
root@ip-10-12-4-85:~# tail -f /var/log/kube-proxy.log 
E1012 21:41:08.700491       6 server.go:369] Can't get Node "ip-10-12-4-85", assuming iptables proxy, err: nodes "ip-10-12-4-85" not found
I1012 21:41:08.701680       6 server.go:203] Using iptables Proxier.
W1012 21:41:08.729704       6 server.go:417] Failed to retrieve node info: nodes "ip-10-12-4-85" not found
W1012 21:41:08.729795       6 proxier.go:226] invalid nodeIP, initialize kube-proxy with 127.0.0.1 as nodeIP
I1012 21:41:08.729824       6 server.go:215] Tearing down userspace rules.
I1012 21:41:08.738934       6 conntrack.go:40] Setting nf_conntrack_max to 131072
I1012 21:41:08.739675       6 conntrack.go:57] Setting conntrack hashsize to 32768
I1012 21:41:08.739994       6 conntrack.go:62] Setting nf_conntrack_tcp_timeout_established to 86400
W1012 22:11:24.534765       6 reflector.go:330] pkg/proxy/config/api.go:30: watch of *api.Service ended with: too old resource version: 609 (4476)
W1012 22:13:25.510114       6 reflector.go:330] pkg/proxy/config/api.go:30: watch of *api.Service ended with: too old resource version: 4477 (4479)
```

The failed node info is an issue but isn't breaking kube-proxy on any other nodes. And This same node worked without any change once the container was restarted.

**Comment by bprashanth** [comment]
so was the node NotReady? I don't think we can ensure correct iptables rules in NotReady nodes. was the kubeproxy static pod up (docker ps), if not, do you have kubelet logs?

**Comment by carsonoid** [comment]
The node was Ready according to the API. The kube-proxy pod was up but no
rules were created. Basically: kube-proxy was up but the logs were
essentially empty per the paste in my original post and yet there were no
iptables rules for services on the host.

**Comment by zhaochj** [comment]
Is this problem fixed?I have the same problem

**Comment by s332401890** [comment]
Is this problem fixed?I have the same problem

**Comment by feiskyer** [comment]
Are there any `[iptables] <defunct>` related logs in `/var/log/`? Could you try to add some iptables rules manually and check whether they are working?

**Comment by caseydavenport** [comment]
cc @kubernetes/sig-network-misc

**Comment by freehan** [comment]
maybe related to: https://github.com/kubernetes/kubernetes/issues/37414

**Comment by renerchen** [comment]
I have the same problem, iptables are missing in some nodes, is it fixed?

**Comment by MrHohn** [comment]
Just want to clarify, we have not actually reached the root cause for the original post yet.

For the users that claimed to have the same problem, I assume they were experiencing the similar situation that "kube-proxy iptables rules were not created". However, there are many different failures that could lead to this problem. It would be great if you could post more information for us to further diagnose, and also help distinguishing whether it is the same problem or not.

More specifically, could @zhaochj @s332401890 @renerchen please provide more details (Kubernetes version, what the failure is, what you are trying to do, related logs)?

**Comment by s332401890** [comment]
Although I do not know why, but I have solved the problem。i update the version of all of k8s software.

**Comment by renerchen** [comment]
@MrHohn  We have debugged the problem. Then we found:
 -- When iptables rules in one node is less than 1200, the service can be accessed successfully always
 -- When iptables rules in one node is more than 1200, the iptables can't be written in some probability. 
-- When iptabls rules in node is more than 1000, the iptables will be locked in some probability
Can you tell me why, thanks a lot! It is urgent for me! As this reason, though we have many nodes, I can't deploy many services with nodeport  in kuberntes cluster. 

The following is the version and configuration of my kuberntes cluster
-------------------------------------------------
 kubernetes component inital config
--------------------------------------------------
root@ubuntu122:/opt/bin# ps -ef | grep kube
root       2287      1  1  2016 ?        06:10:34 /opt/bin/kube-controller-manager --master=127.0.0.1:8080 --root-ca-file=/srv/kubernetes/ca.crt --service-account-private-key-file=/srv/kubernetes/server.key --logtostderr=true
root       2301      1  4  2016 ?        14:59:36 /opt/bin/kube-apiserver --insecure-bind-address=0.0.0.0 --insecure-port=8080 --etcd-servers=http://127.0.0.1:4001 --logtostderr=true --service-cluster-ip-range=192.168.3.0/24 --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,SecurityContextDeny,DefaultStorageClass,ResourceQuota --service-node-port-range=30000-50000 --advertise-address=10.141.38.142 --allow-privileged=true --client-ca-file=/srv/kubernetes/ca.crt --tls-cert-file=/srv/kubernetes/server.cert --tls-private-key-file=/srv/kubernetes/server.key
root       2311      1  0  2016 ?        00:38:05 /opt/bin/kube-scheduler --logtostderr=true --master=127.0.0.1:8080
root      49525  56242  0 17:21 pts/0    00:00:00 grep --color=auto kube
root      73830      1 12 09:07 ?        01:02:59 /opt/bin/kubelet --hostname-override=10.141.38.142 --api-servers=http://10.141.38.142:8080 --logtostderr=true --cluster-dns=192.168.3.10 --cluster-domain=cluster.local --config= --allow-privileged=true
root      73833      1  6 09:07 ?        00:30:16 /opt/bin/kube-proxy --hostname-override=10.141.38.142 --master=http://10.141.38.142:8080 --logtostderr=true
-------------------------------------------------
 kubernetes version
--------------------------------------------------
root@ubuntu122:/opt/bin# ./kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"clean", BuildDate:"2016-10-16T06:36:33Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"clean", BuildDate:"2016-10-16T06:20:04Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by renerchen** [comment]
@s332401890  what is your kuberntes version？

**Comment by s332401890** [comment]
{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"86dc49aa137175378ac7fba7751c3d3e7f18e5fc", GitTreeState:"clean", BuildDate:"2016-12-15T16:57:18Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by renerchen** [comment]
@MrHohn By the way, when I write the missing iptables  manually, it is failed to write the rules with string "KUBE-". And I don't know why,

**Comment by renerchen** [comment]
@s332401890 and what is you kube-proxy configuration?

**Comment by s332401890** [comment]
@renerchen http://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/
 config info

**Comment by renerchen** [comment]
@MrHohn  I found iptales options of kube-proxy
--iptables-masquerade-bit value                If using the pure iptables proxy, the bit of the fwmark space to mark packets requiring SNAT with.  Must be within the range [0, 31]. (default 14)
--iptables-sync-period duration                How often iptables rules are refreshed (e.g. '5s', '1m', '2h22m').  Must be greater than 0. (default 30s)
--proxy-mode value                             Which proxy mode to use: 'userspace' (older) or 'iptables' (faster). If blank, look at the Node object on the Kubernetes API and respect the 'net.experimental.kubernetes.io/proxy-mode' annotation if provided.  Otherwise use the best-available proxy (currently iptables).  If the iptables proxy is selected, regardless of how, but the system's kernel or iptables versions are insufficient, this always falls back to the userspace proxy.

 I used the default configuration,  is it right ? how to config these options?

**Comment by MrHohn** [comment]
@renerchen 

> -- When iptables rules in one node is more than 1200, the iptables can't be written in some probability.

Do you have corresponding kube-proxy logs when this happened? There were users reported kube-proxy performance issue with a huge set of services, but it should still be functioning. Did any kube-proxy pod stop running (be evicted or crashed)? What were your services' setup?

> when I write the missing iptables manually, it is failed to write the rules with string "KUBE-"

We don't recommend users to manually modify k8s related iptables rules.

> I used the default values, is it right ? how to config these options?

Yes, it is right to use the default values if you don't have special use case.

**Comment by thockin** [comment]
What CentOS version?

**Comment by renerchen** [comment]
@MrHohn   The kube-proxy log is fllowing(one has service iptables rules, the other doesn't have iptables)

The good node kube-proxy log:

kube-proxy.log:9508179:I0112 04:07:40.751401  178196 proxier.go:431] Adding new service "common/a-analysis175:8008" at 192.168.3.222:8008/TCP
kube-proxy.log:9508180:I0112 04:07:40.751544  178196 proxier.go:459] added serviceInfo(common/a-analysis175:8008): (*iptables.serviceInfo)(0xc8208e6bb0)({
kube-proxy.log:9508358:I0112 04:07:41.000960  178196 proxier.go:1318] Opened local port "nodePort for common/a-analysis175:8008" (:38124/tcp)
kube-proxy.log:9508446:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 has no endpoints" -m tcp -p tcp -d 192.168.3.222/32 --dport 8008 -j REJECT
kube-proxy.log:9509627:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.222/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:9509628:-A KUBE-NODEPORTS -m comment --comment common/a-analysis175:8008 -m tcp -p tcp --dport 38124 -j KUBE-MARK-MASQ
kube-proxy.log:9509629:-A KUBE-NODEPORTS -m comment --comment common/a-analysis175:8008 -m tcp -p tcp --dport 38124 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:9510338:I0112 04:07:41.418206  178196 proxier.go:1056] Port "nodePort for common/a-analysis175:8008" (:38124/tcp) was open before and is still needed
kube-proxy.log:9510457:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 has no endpoints" -m tcp -p tcp -d 192.168.3.222/32 --dport 8008 -j REJECT
kube-proxy.log:9511442:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.222/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:9511443:-A KUBE-NODEPORTS -m comment --comment common/a-analysis175:8008 -m tcp -p tcp --dport 38124 -j KUBE-MARK-MASQ
kube-proxy.log:9511444:-A KUBE-NODEPORTS -m comment --comment common/a-analysis175:8008 -m tcp -p tcp --dport 38124 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:9512171:I0112 04:07:41.842090  178196 proxier.go:1056] Port "nodePort for common/a-analysis175:8008" (:38124/tcp) was open before and is still needed
kube-proxy.log:9512316:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 has no endpoints" -m tcp -p tcp -d 192.168.3.222/32 --dport 8008 -j REJECT
kube-proxy.log:9513145:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.222/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:9513146:-A KUBE-NODEPORTS -m comment --comment common/a-analysis175:8008 -m tcp -p tcp --dport 38124 -j KUBE-MARK-MASQ
kube-proxy.log:9513147:-A KUBE-NODEPORTS -m comment --comment common/a-analysis175:8008 -m tcp -p tcp --dport 38124 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:9514282:I0112 04:07:42.353132  178196 proxier.go:1056] Port "nodePort for common/a-analysis175:8008" (:38124/tcp) was open before and is still needed
kube-proxy.log:9514358:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 has no endpoints" -m tcp -p tcp -d 192.168.3.222/32 --dport 8008 -j REJECT
kube-proxy.log:9515633:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.222/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:9515634:-A KUBE-NODEPORTS -m comment --comment common/a-analysis175:8008 -m tcp -p tcp --dport 38124 -j KUBE-MARK-MASQ
kube-proxy.log:9515635:-A KUBE-NODEPORTS -m comment --comment common/a-analysis175:8008 -m tcp -p tcp --dport 38124 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:9516136:I0112 04:07:42.819991  178196 proxier.go:1056] Port "nodePort for common/a-analysis175:8008" (:38124/tcp) was open before and is still needed
kube-proxy.log:9516216:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 has no endpoints" -m tcp -p tcp -d 192.168.3.222/32 --dport 8008 -j REJECT
kube-proxy.log:9517471:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.222/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:9517472:-A KUBE-NODEPORTS -m comment --comment common/a-analysis175:8008 -m tcp -p tcp --dport 38124 -j KUBE-MARK-MASQ
kube-proxy.log:9517473:-A KUBE-NODEPORTS -m comment --comment common/a-analysis175:8008 -m tcp -p tcp --dport 38124 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:9518104:I0112 04:07:43.244655  178196 proxier.go:1056] Port "nodePort for common/a-analysis175:8008" (:38124/tcp) was open before and is still needed
-------------------------------------------------------------------------------------------------

The bad one kube-proxy log:

kube-proxy.log:721542:I0112 09:36:31.968749    5712 proxier.go:431] Adding new service "common/a-analysis175:8008" at 192.168.3.167:8008/TCP
kube-proxy.log:721543:I0112 09:36:31.969200    5712 proxier.go:459] added serviceInfo(common/a-analysis175:8008): (*iptables.serviceInfo)(0xc820864dc0)({
kube-proxy.log:721784:E0112 09:36:32.221928    5712 proxier.go:1061] can't open "nodePort for common/a-analysis175:8008" (:45102/tcp), skipping this nodePort: listen tcp :45102: bind: address already in use
kube-proxy.log:723261:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.167/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:723504:E0112 09:36:32.591077    5712 proxier.go:1061] can't open "nodePort for common/a-analysis175:8008" (:45102/tcp), skipping this nodePort: listen tcp :45102: bind: address already in use
kube-proxy.log:724497:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.167/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:725336:E0112 09:36:33.019418    5712 proxier.go:1061] can't open "nodePort for common/a-analysis175:8008" (:45102/tcp), skipping this nodePort: listen tcp :45102: bind: address already in use
kube-proxy.log:726703:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.167/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:727104:E0112 09:36:33.422771    5712 proxier.go:1061] can't open "nodePort for common/a-analysis175:8008" (:45102/tcp), skipping this nodePort: listen tcp :45102: bind: address already in use
kube-proxy.log:728071:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.167/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:728886:E0112 09:36:33.805135    5712 proxier.go:1061] can't open "nodePort for common/a-analysis175:8008" (:45102/tcp), skipping this nodePort: listen tcp :45102: bind: address already in use
kube-proxy.log:729893:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.167/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:730901:E0112 09:36:34.206383    5712 proxier.go:1061] can't open "nodePort for common/a-analysis175:8008" (:45102/tcp), skipping this nodePort: listen tcp :45102: bind: address already in use
kube-proxy.log:732388:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.167/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:732562:E0112 09:36:34.611658    5712 proxier.go:1061] can't open "nodePort for common/a-analysis175:8008" (:45102/tcp), skipping this nodePort: listen tcp :45102: bind: address already in use
kube-proxy.log:733606:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.167/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:734466:E0112 09:36:35.036115    5712 proxier.go:1061] can't open "nodePort for common/a-analysis175:8008" (:45102/tcp), skipping this nodePort: listen tcp :45102: bind: address already in use
kube-proxy.log:735479:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.167/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:736385:E0112 09:36:35.471803    5712 proxier.go:1061] can't open "nodePort for common/a-analysis175:8008" (:45102/tcp), skipping this nodePort: listen tcp :45102: bind: address already in use
kube-proxy.log:737837:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.167/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:738182:E0112 09:36:35.889442    5712 proxier.go:1061] can't open "nodePort for common/a-analysis175:8008" (:45102/tcp), skipping this nodePort: listen tcp :45102: bind: address already in use
kube-proxy.log:739095:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.167/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:739966:E0112 09:36:36.291460    5712 proxier.go:1061] can't open "nodePort for common/a-analysis175:8008" (:45102/tcp), skipping this nodePort: listen tcp :45102: bind: address already in use
kube-proxy.log:740789:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.167/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:742040:E0112 09:36:36.735813    5712 proxier.go:1061] can't open "nodePort for common/a-analysis175:8008" (:45102/tcp), skipping this nodePort: listen tcp :45102: bind: address already in use
kube-proxy.log:743389:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.167/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:743908:E0112 09:36:37.166936    5712 proxier.go:1061] can't open "nodePort for common/a-analysis175:8008" (:45102/tcp), skipping this nodePort: listen tcp :45102: bind: address already in use
kube-proxy.log:745450:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.167/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:745673:E0112 09:36:37.586016    5712 proxier.go:1061] can't open "nodePort for common/a-analysis175:8008" (:45102/tcp), skipping this nodePort: listen tcp :45102: bind: address already in use
kube-proxy.log:746431:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.167/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:747535:E0112 09:36:38.030714    5712 proxier.go:1061] can't open "nodePort for common/a-analysis175:8008" (:45102/tcp), skipping this nodePort: listen tcp :45102: bind: address already in use
kube-proxy.log:748356:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.167/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:749683:E0112 09:36:38.467225    5712 proxier.go:1061] can't open "nodePort for common/a-analysis175:8008" (:45102/tcp), skipping this nodePort: listen tcp :45102: bind: address already in use
kube-proxy.log:751196:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.167/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO
kube-proxy.log:751376:E0112 09:36:38.893737    5712 proxier.go:1061] can't open "nodePort for common/a-analysis175:8008" (:45102/tcp), skipping this nodePort: listen tcp :45102: bind: address already in use
kube-proxy.log:752194:-A KUBE-SERVICES -m comment --comment "common/a-analysis175:8008 cluster IP" -m tcp -p tcp -d 192.168.3.167/32 --dport 8008 -j KUBE-SVC-Y6AMAZGQPQDSLWDO

**Comment by MrHohn** [comment]
Seems like you had port 45102 in use on the bad node.
```
can't open "nodePort for common/a-analysis175:8008" (:45102/tcp), skipping this nodePort: listen tcp :45102: bind: address already in use
```
Have you checked what program was using port 45102? Does not seems like the nodePort allocation conflict issue, otherwise the log would be `Port *** was open before and is still needed` instead.

As nodePort service will need to open a port within a specific range (default 30000-32767, but you have set it to 30000-50000) on every minion node, you need to make sure ports in this range are not occupied. You can also configure it to another range through the `--service-node-port-range` flag of `kube-apiserver`.

**Comment by thockin** [comment]
node ports >= 32768 are very possibly in use as ephemeral ports.

**Comment by renerchen** [comment]
@MrHohn  yes, the port 45102 is allocated to another endpoints. Thanks a lot!

**Comment by renerchen** [comment]
@MrHohn @thockin 
NodePort 30000~32767 is not enought for us. As node ports >= 32768 are very possibly in use as ephemeral ports.  If we want to extend nodeport range, how to do it? Using ports < 32768, like (12768~32768), right?

**Comment by renerchen** [comment]
@MrHohn  Another question, when k8s set the node port, does it to check that the port is used in the nodes but not used in kube-proxy?

**Comment by thockin** [comment]
You have more than 2700 Services and all of them are exposed publicly by
load-balancers?

**Comment by MrHohn** [comment]
@renerchen No, it does not. The Apiserver will randomly pick a port from the configured range (beside those allocated nodePorts).

For extending the nodePort range, I think dynamic port range may vary between different platforms and distros. On my local cluster that runs [GCI images](https://cloud.google.com/container-optimized-os/), I have below:
```
# sysctl -a | grep port
...
net.ipv4.ip_local_port_range = 32768    60999
...
```
You may want to check your environment before configure it ([ref](https://en.wikipedia.org/wiki/Ephemeral_port)).

Though I'm surprise you have that many nodePort services.

**Comment by omarvsoft** [comment]
Hi team

I have a similar problem but, in my case I'm not changing the port range... All the rules work well for days and suddenly the node ports don't work, all services look well too but in the kube-proxy log I see the next message for each service:

`Apr 27 14:26:17 server-01 kube-proxy[5948]: I0427 14:26:17.144549    5948 proxier.go:1120] Port "nodePort for kube-system/gogs-git" (:30001/tcp) was open before and is still needed`

My dynamic port range is the following:

`net.ipv4.ip_local_port_range = 30000	60999`

Does anyone know what this message means?

**Comment by thockin** [comment]
That's a V(4) log - it's for deep debugging.  All it means is that a piece
of state did not change.

**Comment by omarvsoft** [comment]
Thank you @thockin for answer!  

Do you have any recommendations? I don't understand why in the cluster the services stop responding to external requests, the iptables rules seem to be correct and all services are running...

**Comment by MrHohn** [comment]
@omarvsoft  Could you open a new issue with more details? Your issue seems unrelated to the original post.
