### ISSUE TITLE
All test suite kubernetes-e2e-gce-*-release-1.4 failed

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#35654]
All test suite running against 1.4 release on containervm image failed since ~8:40am this morning. We should fix the issue before we cut another patch release.

cc/ @fejta @foxish, oncall

**Comment by foxish** [comment]
@fejta @spxtr Looks like a jenkins issue.
The first unsuccessful build has the following:

> Error: 10 leaked resources +NAME ZONE MACHINE_TYPE PREEMPTIBLE INTERNAL_IP EXTERNAL_IP STATUS +jenkins-e2e-master us-central1-f n1-standard-1 10.240.0.2 104.154.60.161 RUNNING +NAME ZONE SIZE_GB TYPE STATUS +jenkins-e2e-master us-central1-f 10 pd-standard READY +jenkins-e2e-master-pd us-central1-f 20 pd-ssd READY +NAME REGION ADDRESS STATUS +jenkins-e2e-master-ip us-central1 104.154.60.161 IN_USE +jenkins-e2e-d79716a4-9b92-11e6-9429-42010af00002 jenkins-e2e 10.180.0.0/24 us-central1-f/instances/jenkins-e2e-master 1000 +jenkins-e2e-master-https jenkins-e2e 0.0.0.0/0 tcp:443 jenkins-e2e-master +jenkins-e2e-minion-all jenkins-e2e 10.180.0.0/14 tcp,udp,icmp,esp,ah,sctp jenkins-e2e-minion

**Comment by dchen1107** [comment]
Yes, what is what I found. And I removed that leaked master node so that the rest runs wouldn't be blocked by this. The question is why teardown logic was broken for all test suites. Not just one here.

**Comment by dchen1107** [comment]
cc/ @roberthbailey I am not sure if anything changed lately in cluster lifecycle, especially the teardown side.

The issue is extremely urgent is that we are going to cut another patch release for 1.4 with new containervm image here.  cc/ @matchstick

**Comment by jessfraz** [comment]
Oh ya I was trying to figure this out, I dont think it was a specific commit because it had passed then started failing on the same commmit

**Comment by jessfraz** [comment]
There were some things added to vmware with regard to tear down

**Comment by fejta** [comment]
Will you please provide a testgrid link for at least one of the failures and/or a gubernator link? https://k8s-testgrid.appspot.com/release-1.4-all

**Comment by jessfraz** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-reboot-release-1.4/2323

from https://k8s-testgrid.appspot.com/release-1.4-all#gce-reboot-release-1.4

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-release-1.4/3035 

from https://k8s-testgrid.appspot.com/release-1.4-all#gce-release-1.4

The really dont tell much because it's "exit status 1"

**Comment by fejta** [comment]
I am pretty sure the problem is [here](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-reboot-release-1.4/2323?log):

```
ERROR: (gcloud.compute.instances.list) unrecognized arguments: --zone (did you mean '--zones'?)
```

**Comment by jessfraz** [comment]
oh wow that is unfortunate, is that a command that was depreciated?

**Comment by fejta** [comment]
Yes, I have a vague memory that @ixdy fixed this for master, maybe it just needs to get ported back to older branches?

**Comment by jessfraz** [comment]
gotcha thanks either will cherry pick what i find or just fix it

**Comment by jessfraz** [comment]
got it cherry-picking #34577

**Comment by foxish** [comment]
@jessfraz , would it need to be cherrypicked into the 1.3 branch as well?

**Comment by jessfraz** [comment]
@foxish ya i bet I will open that one too

**Comment by dchen1107** [comment]
You guys rock! Thanks!

**Comment by jessfraz** [comment]
@foxish they never call to "--zones" on release-1.3 so i believe it is safe

**Comment by fejta** [comment]
Letting Jess handle this, please assign back to me if you need my help.

**Comment by jessfraz** [comment]
#35659 is merged so this should be good now

**Comment by fejta** [comment]
https://k8s-testgrid.appspot.com/release-1.4-all#gci-gce-alpha-features-release-1.4

**Comment by jessfraz** [comment]
yayyyy!

**Comment by wonderfly** [comment]
Looks like the CI jobs for release-1.3 are not on the testgrid any more, but they are all failing with similar issues.

**Comment by jessfraz** [comment]
so on release-1.3 I could not find a --zone, so it might be something
different

**Comment by fejta** [comment]
@krzyzacy any idea why the release-1.3 jobs aren't on testgrid? Or maybe they are just really hard to find???

**Comment by jessfraz** [comment]
It might also need these?
https://github.com/kubernetes/kubernetes/pull/35802

**Comment by roberthbailey** [comment]
I see release-1.3 jobs (e.g. https://k8s-testgrid.appspot.com/google-gce#gci-gce-release-1.3 and https://k8s-testgrid.appspot.com/google-gke#gke-release-1.3).

**Comment by krzyzacy** [comment]
1.3 jobs on testgrid are everywhere ( under gke, gce, ... ), and we manually grouped all 1.4 jobs and put into the release-1.4-all dashboard

**Comment by fejta** [comment]
Thanks Sen and Robby!

**Comment by krzyzacy** [comment]
wonder if it can somehow be filtered out, if not then might good to have some search function in the future.

**Comment by wonderfly** [comment]
Also, since the failures were cause by a `gcloud` breaking change, can we consider pinning to specific `gcloud` versions instead of doing `gcloud components update` all over the place?

**Comment by wonderfly** [comment]
> so on release-1.3 I could not find a --zone, so it might be something different

@jessfraz However I am seeing similar failures on the most recent `gce-release-1.3` build:

```
Bringing down cluster
ERROR: (gcloud.compute.instance-templates.delete) Some requests did not succeed:
 - The instance_template resource 'jenkins-e2e-minion-template' is already being used by 'jenkins-e2e-minion-group'

Updated [https://www.googleapis.com/compute/v1/projects/k8s-jkns-gce-1-3/zones/us-central1-f/instances/jenkins-e2e-master].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-gce-1-3/zones/us-central1-f/instances/jenkins-e2e-master].
usage: gcloud compute instances list  [NAME ...] [optional flags]
ERROR: (gcloud.compute.instances.list) unrecognized arguments: --zone (did you mean '--zones'?)
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-gce-1-3/global/firewalls/jenkins-e2e-master-https].
```

Buildlog: https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-release-1.3/6546/build-log.txt

**Comment by wonderfly** [comment]
There are still `--zone`s in 1.3. For example:
https://github.com/kubernetes/kubernetes/blob/release-1.3/cluster/gce/util.sh#L1238
and https://github.com/kubernetes/kubernetes/blob/release-1.3/cluster/gce/util.sh#L1253

**Comment by jessfraz** [comment]
ah weird ok my grep must have missed those
