### ISSUE TITLE
Long term behaviour of kubeadm commands (mini proposal)

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#35682]
Here are some ideas of how kubeadm commands could work beyond initial cluster bootstrap. Some of these features may be easier to implement with self-hosting, but we can roll something simple on top of the current implementation with static pods and some self-hosted components.
## Motivation

User should be able to upgrade control plane component or update the configuration without a reset. The interface should be intuitive and idempotent.
### `kubeadm init`

After user ran the init command for the very first time, it can be used for configuration updates and simple upgrades.

We will need to store initial input information, which will probably need to include version of kubeadm used, custom flags that were specified and default values of those that weren't. Once new configuration had been applied, we will need to update the configuration file.

If new flags and/or feature appeared in the new version, those should be communicated to the user. Similarly, we will need to have an ability to eliminate certain flags that may had been needed before and are no longer recommended.
#### User Story 1

User has bootstrapped a cluster with default flags and it worked fine.

After some time, they learned that there exists an overlap in service IP range and the range used by a wider network their cluster is running inside of. They need to make a configuration update.

The interface should be as simple as:

``` console
> kubeadm init --services-cidr=newRange
```

This should also work:

``` console
> $EDITOR /etc/kubernetes/kubeadm.conf # update default range, set it to the new value
> kubeadm init
```
#### User Story 2

User has ran a cluster for a while, but learned of some issues that they had been asked to debug. They need increase log-level in controller manager.

They should be able to do that with:

``` console
> $EDITOR /etc/kubernetes/kubeadm.conf # update extra component flags, increase controller manager log-level
> kubeadm init
```
### User Story 3

> _**NOTE:** This is a long one, it's here mostly to illustrate how the ideas above could be taken further._

Initial run: 

```
> kubeadm init
...
```

User has a master machine running current version of control plane components. A configuration file is written with current default value for flags. User has upgraded the kubeadm package some time after this, and they wish to upgrade the control plane components. They have modified the configuration file to set the new version, and they also decided to specify few additional parameters.

```
> kubeadm init --check-updates
The cluster had been initialised with a older version of kubeadm (vX.Y.Z).
By default, we will apply what is specified in the configuration file, and will amend the configuration with new recommended features.
New features are:
  - A
  - B
 If you do not wish to apply these features, set `--apply-new=false`.
Additionally, you have specified new configuration:
  - Use version X
  - Add flag Y
  - Remove flag Z
There are flags that are no longer recommended, these will be remove:
  - Remove M
  - Change value of N
If you don't wish to remove these flags, you can specify `--apply-remove-old=false` at your own risk.
```
### `kubeadm join`

As join command doesn't do as much as init command does, it may be enough to have two modes here. It will need to store initial information in a configuration file too.
- repeated run doesn't do anything
- repeated run with new flags may result in node joining a new cluster cluster (if new arguments point to a cluster with a different identifier to the one we have seen previously).
## Notes On Self-hosting

The features described above are applicable to self-hosting as much as current implementation. When we have self-hosting, most users still shouldn't have to understand and manually handle any manifests for the control plane components, they will need a higher level interface that provides some level of configurability and comes with known-to-work-well defaults.

**Comment by luxas** [comment]
This issue is now outdated, kubeadm phases and upgrades are coming for v1.8 and have their respective issues in the kubeadm repo...
