### ISSUE TITLE
kubenet bare metal documentation update

### ISSUE THREAD

**Issue by danielschonfeld** [kubernetes/kubernetes#35683]
Drawing on the GCE Kubernetes Networking page we set out to enjoy our L2 ("dumb switch") at our new bare metal installation utilizing kubenet.  Wanted to share our success story with tips on updating the L2 section of the networking page.

1) No need anymore for the instructions to start docker with --bridge=cbr0 and the other flags mentioned under GCE environment.  (At least for the L2 backed bare metal installation and networking)

2) Make it clear that for L2 switches, you'd need your POD CIDR to be a subnet of your normal internal network IP addresses.  Which if you are going to use the lower end of /16 for the physical nodes and /24 for the POD Network, its not possible to utilize kibe-controller-manager to auto assign the POD CIDRs to the kube nodes.  If you want to use kcm to automatically assign those CIDRs either use a higher range of the /16 network or use a /8 network for your physical nodes so that KCM has the /16 to assign.  We opted to manually assign `--pod-cidr` via kubelet utilizing a /16 network for both our physical devices and our `cbr0` psudo bridges.

3) This is probably the most important bit we encountered.  Since the `cbr0` is going to act as a sudo bridge it's important to enable the `proxy_arp` option on your internal network ethernet device.  so supposing your internal ethernet device is `eno0` you'd want to enable `sysctl -w net.ipv4.conf.eno0.proxy_arp=1`

So far it seems to be working great.  Number (3) was the secret sauce for us.  

I'm open to suggestions if there's a better way to do it! I'd love to learn some more too.

**Comment by luxas** [comment]
cc @kubernetes/sig-network

**Comment by luxas** [comment]
cc @kubernetes/sig-network-misc Is this up-to-date anymore?
Could we document how to run kubenet on bare metal or do we want to hide that since kubenet is going away?

**Comment by cmluciano** [comment]
I think we should update the instructions for utilizing the CNI plugins since kubenet will be removed soon.

**Comment by cmluciano** [comment]
cc @dnardo
