### ISSUE TITLE
CRI: Add a "Status" call in the API report readiness of the runtime

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#35701]
Currently we rely on `Version` in CRI to check whether the container runtime is up. This single binary state may not be indicative of whether the runtime is ready, nor provide enough information about subcomponents in the runtime. For example, the default network plugin kubenet reports an error on the [`Status`](https://github.com/kubernetes/kubernetes/blob/e2c96db72b6ef5819b08f976861a344ea9430373/pkg/kubelet/network/kubenet/kubenet_linux.go#L534-L544) call if the CNI plugin binaries are missing or pod CIDR is not ready. Even if network is not ready, kubelet can still run host network pods (#35526).

One option to report the network readiness is to reuse the `Version` call and add network plugin version and names, if the version of that is missing, kubelet will report node "NotReady" and stop syncing non-hostnetwork pods. However, this overloads the `Version` call, and is not as flexible as just adding a `Status` call. Thoughts?

/cc @kubernetes/sig-node @euank @yifan-gu @mrunalp @feiskyer @bprashanth @thockin

**Comment by bprashanth** [comment]
Yeah, without a structured status call it becomes hard to stall nodeReadiness on external dependencies (eg: network plugin's etcd unreachable: http://kubernetes.io/docs/getting-started-guides/ubuntu-calico/). Even better if we can report non-critical status warnings as events on the node object. If the shim is not ready, I want to know why, if it's going to be not ready (ips almost exhausted, log partition filling), I'd like a warning.

**Comment by feiskyer** [comment]
> However, this overloads the Version call, and is not as flexible as just adding a Status call.

Agree with this.

> Even better if we can report non-critical status warnings as events on the node object. 

How about to adds an explicit state, e.g. 

```go
type State struct {
// If not nil, report warning message and set the shim as ready.
Warning *string
// If not nil, report the critical message and set the shim as not ready.
Critical *string
}
```

**Comment by feiskyer** [comment]
opened #35760 for this.

**Comment by Random-Liu** [comment]
This seems to be a `RuntimeCondition` similar with `NodeCondition` and `PodCondition`.

One question is that how well-defined do we need the `Status` to be?
* Option 1: One RuntimeReady Condition (Readiness+Reason+Message). We only need runtime to answer true/false. The reason/message can contain arbitrary information and is only used in log, event or node condition message.
* Option 2: Condition Array. More extensible in the future. Let runtime return an array of conditions, e.g. RuntimeReady, NetworkReady etc. **We need this only if kubelet want to handle different conditions**, e.g. kubelet may want to continue running host network pod as long as runtime is ready regardless network condition.
* Option 3: A well-defined structure. Not extensible and the structure is hard to define.

For now, I feel like Option 1 may be enough. Option 2/3 seems a bit overkill, and I'm not sure whether we really want kubelet to handle different conditions.

**Comment by feiskyer** [comment]
@Random-Liu Agree with option 1 for simplicity. And #35760 also adds a `WARNING` state to report non-critical events.

**Comment by bprashanth** [comment]
What do we lose by doing 2 with only 1 element in the list?

**Comment by Random-Liu** [comment]
@bprashanth Nothing. Just don't know whether it is necessary , and how we are going to use it.

**Comment by bprashanth** [comment]
Since I can't predict the future, I vote for that
