### ISSUE TITLE
verify-godeps is difficult to run/verify locally

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#35707]
Verify-godeps cannot be run locally and that leads to delay in fixing issues with it.
It took 3 PRs to fix this morning's submit-queue break.  

https://github.com/kubernetes/kubernetes/pull/35704
https://github.com/kubernetes/kubernetes/pull/35696
https://github.com/kubernetes/kubernetes/pull/35699

cc @gmarek @kubernetes/contributor-experience

**Comment by eparis** [comment]
why can't it be run locally?  (it used to be possible!?)

/me starts to read.

**Comment by apelisse** [comment]
Unknown command `/me`. Did you mean `/meme starts to read`:

![image](https://cloud.githubusercontent.com/assets/1929644/19777675/39f7f4cc-9c2e-11e6-9db2-5f25ee95b1be.png)

**Comment by gmarek** [comment]
The error I'm seeing is:
```
Checking for 'Godeps/' changes against '/master'
fatal: Not a valid object name /master
```

**Comment by eparis** [comment]
can you include you `.git/config` file?

**Comment by eparis** [comment]
For when you REALLY want it to run you need to use:

`KUBE_FORCE_VERIFY_CHECKS=y hack/verify-godeps.sh`

**Comment by fejta** [comment]
@gmarek @foxish can you share the `PWD` you use for your kubernetes repo? It should be `$GOPATH/src/k8s.io/kubernetes` per https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md#clone-your-fork

The first thing hack/verify-godeps.sh should print is:
`Checking for 'Godeps/' changes against 'upstream/master'`

**Comment by gmarek** [comment]
```
gmarek@breakwater:~/go/src/k8s.io/kubernetes$ pwd
/usr/local/google/home/gmarek/go/src/k8s.io/kubernetes
gmarek@breakwater:~/go/src/k8s.io/kubernetes$ echo $GOPATH
/usr/local/google/home/gmarek/go
```

@eparis - I really believe that it should be easy to do on local machine, and harder on jenkins, as that we can script around (i.e. `KUBE_FORECE_VERIFY_CHECKS=y` should be default and set to `n` by Jenkins if needed)

**Comment by r2d4** [comment]
Been running into this problem too.  You might have trouble running it locally because it exports environment variables.  So unless you source the script, those exports aren't going to be available for the parent.  It may be overkill, but for running it locally maybe try running it with the kubekins-test image?

```
docker run --rm=true \
  -v "${GOPATH:-}/src/k8s.io/kubernetes":/go/src/k8s.io/kubernetes \
  -e "KUBE_FORCE_VERIFY_CHECKS=${KUBE_FORCE_VERIFY_CHECKS:-}" \
  -e "KUBE_VERIFY_GIT_BRANCH=${KUBE_VERIFY_GIT_BRANCH:-}" \
  -i gcr.io/k8s-testimages/kubekins-test:1.5-v20161007-49d47fe \
  bash -c "cd kubernetes && ${KUBE_TEST_SCRIPT:-./hack/verify-godeps.sh}"
```

**Comment by fejta** [comment]
This should be pretty trivial these days:

```
git clone https://github.com/kubernetes/test-infra $GOPATH/src
test-infra/jenkins/bootstrap.py --job=pull-kubernetes-verify --json --branch=MYBRANCH --repo=k8s.io/kubernetes  # alternatively replace --branch with --pull=1234
```

More specifically find how the job is defined: https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins-pull/bootstrap-pull.yaml#L51 and then run the same bootstrap.py command. 

When bootstrap.py accepts the --json flag, the scenario is defined here: https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L292
