### ISSUE TITLE
[kubeadm] Only supports configuration from one source at a time, flags or file

### ISSUE THREAD

**Issue by pires** [kubernetes/kubernetes#35710]
Currently, one `kubeadm {init,join}` can only be configured through flags _or_ configuration file. So:

```
kubeadm init --config master.yaml
```

or

```
kubeadm init <flags>
```

Both configuration options don't coexist as users may expect it to (#35424).

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#19
