### ISSUE TITLE
`kubeadm join` doesn't set kube config

### ISSUE THREAD

**Issue by michelleN** [kubernetes/kubernetes#35729]
Not sure if this is a bug or a feature. 

**What happened**:
I configured two GCE nodes with Ubuntu 16.04 images. I used kubeadm's getting started guide to make one node the master. I then used the `kubeadm join` command using the token from my master on my other node. I tried to run `kubectl get nodes` but got 
`The connection to the server localhost:8080 was refused - did you specify the right host or port?`.

```
root@michelle-testing-uz4v:~# kubectl config view
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
```

To fix this problem I had to set my $KUBECONFIG to `/etc/kubernetes/kubelet.conf`
However, I didn't have to do that on master and my kubectl worked fine.

**What you expected to happen**:
I expected my non-master node to work as the getting started guide pointed out. Am I doing something wrong here? I understand that to control your cluster from your laptop, you have to copy your KubeConfig. I thought that since I already have the config on my non-master node as a result of `kubeadm join` that I wouldn't have to set the env variable. I'm a bit confused on what to expect here.

**How to reproduce it** (as minimally and precisely as possible):
Run a `kubeadm join` (with token) on a non-master node and run `kubectl get nodes`

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74
a212260", GitTreeState:"clean", BuildDate:"2016-10-16T06:36:33Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linu
x/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675c
d97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linu
x/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Kernel** (e.g. `uname -a`): Linux michelle-testing-uz4v 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Li
  nux
- **Install tools**: kubeadm
- **Others**:

**Comment by luxas** [comment]
We just haven't implemented it. Sounds like it may be an enhancement.

@kubernetes/sig-cluster-lifecycle

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#15
