### ISSUE TITLE
upgrade the default etcd version for kubeadm to 3.0.13

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#35723]
We want to default to etcd3 in etcd2 mode for kubeadm now I think, and eventually default to etcd3 in etcd3 mode as well (I suppose that will be the default for v1.5?)

I don't think we have to deal with migration and upgrades from etcd2 to etcd3, as we're in alpha.
We can just say: create a new cluster.

Of course, when we're in beta, etc. we can't do that, but I think it's best to "fully support" etcd3 and higher when we're that far.

WDYT?
@kubernetes/sig-cluster-lifecycle @wojtek-t @lavalamp

**Comment by errordeveloper** [comment]
I don't know enough about the level of support for v3. I wouldn't rush this
just yet.

**Comment by dgoodwin** [comment]
This is our plan with OpenShift, I would say lets go for it.

**Comment by roberthbailey** [comment]
I think that @mml is hoping to switch GCE/GKE over to etcd3 in the 1.5 timeframe as well.

**Comment by wojtek-t** [comment]
We are still targetting 1.4.x release to switch to etcd3 (unless we find some problems during final testing).
So yes, switching kubeadm should be ok.

**Comment by xiang90** [comment]
@errordeveloper 

etcd3 is well supported. We (etcd team + k8s team) are working hard on both correctness testing for migration and scalability testing for our 1.5 goals.

**Comment by timothysc** [comment]
> I don't think we have to deal with migration and upgrades from etcd2 to etcd3, as we're in alpha. 

do we support any upgrade strategy yet in kubeadm?

**Comment by luxas** [comment]
Nope @timothysc, but I talked to @errordeveloper and @lukemarsden about it; not sure if a doc has been written about that...

Anyway, my motivation is that we should use etcd3 by default for all kubeadm clusters now to avoid having to upgrade when turning to beta at some point

@wojtek-t When you've pushed 3.0.13, ping me so I can make the change in kubeadm

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#16
