### ISSUE TITLE
We need a test case for standalone kubelet

### ISSUE THREAD

**Issue by filbranden** [kubernetes/kubernetes#3573]
We have a scenario of kubelet being used in standalone mode without a master which is the containervm.

In that case, kubelet is started with a `--manifest_url` flag pointing to the URL of a YAML file with instructions of which containers to start.

This case is getting broken often, particularly as we seem to be testing for `nil` and in some cases the pointer vs. interface nil breaks our checks which are not being caught by any of the tests...

I'd say we need to include a test for `--manifest_url` in open source Kubernetes so that we don't get these bugs piling up until we try to build a new containervm with a version of Kubelet.

@dchen1107 @jbeda @brendanburns @satnam6502 @lavalamp

**Comment by erictune** [comment]
I started thinking about how to test this but ran out of time today.  If someone wants to do it, a plan might be:
 - stick the yaml example from https://cloud.google.com/compute/docs/containers/container_vms#create_the_manifest into a public storage bucket on GCS.
 - modify the first invokation of kubelet in hack/test-cmd.sh to take a --manifest_url argument which points at that storage bucket
 - check that the kubelet doesn't crash
 - put a comment in the source for the containervms docs to keep the two yamls in sync.

**Comment by jayunit100** [comment]
Hi kubernetes!  I've just seen https://github.com/GoogleCloudPlatform/kubernetes/pull/4643, and brendan brought up the "standalone mode" use case.  Any color on what are the driving use cases for a standalone kubelet (mesos? unit tests? general design principals?) just curious .

**Comment by erictune** [comment]
Moving and existing system to the complete kubernetes stack all at once can be overwhelming.  People need an incremental path.  One such incremental path might be:
  1. put apps into docker containers.
  1. add cadvisor.  get per-container resource monitoring. 
  1. add kubelet.  use file or http based pod config source.   get health checking, liveness checking, restarting, grouping into pods, volume management, etc.
  1. add kubernetes master.  configure pods through it. add replication controllers, services.

**Comment by pmorie** [comment]
Here's another case for a standalone kubelet:  run a standalone kubelet to bootstrap a kubelet for a node running in a pod:

1.  Start kubelet in run-once mode with a manifest file to start the 'real' kubelet for a node running in a pod
2.  Bootstrap kubelet starts node kubelet in a pod
3.  Bootstrap kubelet process stops

**Comment by dchen1107** [comment]
I am not aware any test case for standalone kubelet was introduced.

**Comment by dchen1107** [comment]
@fejta I re-open this since I couldn't find anywhere I added test for standalone kubelet. Please feel free to close it if I am wrong. Thanks!

**Comment by fejta** [comment]
Thanks for reopening!

No one had made any progress on many test-infra bugs for multiple quarters. I closed this class of bug because I want to draw attention to the ones that are still valuable to address.

I'm removing the test-infra label because this is about adding test coverage.
