### ISSUE TITLE
Create aws.VolumeNameSpec or some custom type for AWS EBS volume name

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#35746]
An AWS EBS Volume can be fully qualified with AZ like `aws://availability-zone/vol-id` or just `vol-id`. The k8s and AWS EBS volume code should make sure they handle both without issue.

One approach for this would be to create a custom type for the AWS EBS volume name, so that type checking ensures the correct value is passed around/used.

This request is based on https://github.com/kubernetes/kubernetes/pull/34859#discussion_r85192021 where @justinsb comments:

> Some background here: https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L1277-L1312
> 
> A volumeid from AWS is going to look like vol-abcdef0 (or longer). A volumeid in the volume spec could look like that, or could be aws:///vol-abcdef0. We are supposed to normalize before comparing to raw API ids, but it looks like I missed that check.
> 
> If you want, we can merge this as is, and then I might do the same thing I did with types.NodeName, with aws.VolumeNameSpec or something, so I can catch any more of these.
> 
> I don't think we gate on AWS e2e failures?

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5

**Comment by justinsb** [comment]
Fixed in #35883
