### ISSUE TITLE
[CRI] Decide whether to continue supporting docker nsenter exec

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#35747]
Either deprecate the nsenter exec handler, or add nsenter handling to the dockershim (after https://github.com/kubernetes/kubernetes/pull/35661 goes in).

/cc @kubernetes/sig-node

**Comment by yujuhong** [comment]
I vote for deprecating the nsenter exec handler for docker. `docker exec` has been the default exec handler since kubernetes pre-1.0. Is there any reason (or use case) for keeping the pluggable exec handler?
Another question is that whether we can drop `nsenter` exec in one release, or we need to provide support in CRI for at lease one more release.

/cc @kubernetes/sig-node-misc @thockin @ncdc

**Comment by feiskyer** [comment]
+1 for docker exec.

**Comment by dchen1107** [comment]
I should deprecate docker nsenter exec, but to achieve that, we need to follow the deprecation policy. The first thing we need to address is marking this flag being deprecated:

https://github.com/kubernetes/kubernetes/blob/ed5a23652566b48694ccdfacc5cff0790905a1a1/cmd/kubelet/app/options/options.go#L216

**Comment by dchen1107** [comment]
Also there are several issues raised before which are related to the issue of docker exec in various versions. The engineer even suggested to switch the default mechanism is docker nsenter exec. One of the examples is https://github.com/kubernetes/kubernetes/issues/25456

**Comment by dchen1107** [comment]
Now let's narrow down to the CRI scope, and below is my 2 cents:

1) Can we mark the flag deprecated in 1.6?
2) Drop the support in CRI in 1.6? Inform the kubernetes users with this decision along CRI announcement being scheduled sometimes in February? 
3) Drop the support completely from Kubernetes unless there are real use cases coming up.

**Comment by yujuhong** [comment]
> Drop the support in CRI in 1.6? Inform the kubernetes users with this decision along CRI announcement being scheduled sometimes in February?

We'll have to tell the users that they need to disable CRI in order to use the nsenter exec plugin.

@timstclair, could you give a quick estimate about the amount of work required to add support for nsenter exec in dockershim? Thanks.

**Comment by yujuhong** [comment]
> @timstclair, could you give a quick estimate about the amount of work required to add support for nsenter exec in dockershim? Thanks.

Talked to @timstclair offline. I'll
 1. Add support nsenter as exec in dockershim
 2. Mark the flag as deprecated.
