### ISSUE TITLE
Can we create both UDP and TCP port on a single service of type "LoadBalancer"? 

### ISSUE THREAD

**Issue by mjena** [kubernetes/kubernetes#35752]
I am getting following error for my service: "cannot create an external load balancer with mix protocols"

Here is my service file:
{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "test"
    },
    "spec": {
        "selector": {
            "app": "test"
        },
        "type": "LoadBalancer",
        "ports": [
            {
                "name": "mod1",
                "protocol": "TCP",
                "port": 4001,
                "targetPort": 4001
            },
            {
                "name": "mod2",
                "protocol": "TCP",
                "port": 5100,
                "targetPort": 5100
            },
            {
                "name": "mod3",
                "protocol": "UDP",
                "port": 4001,
                "targetPort": 4001
            }
        ]
    }
}

**Comment by thockin** [comment]
No, that isn't supported.

**Comment by nick4fake** [comment]
Is this by-design?

**Comment by thockin** [comment]
None of the LBs that implement kubernetes can support it. :(
