### ISSUE TITLE
GlusterFS PVC created with no replicas and no way to tune

### ISSUE THREAD

**Issue by danielschonfeld** [kubernetes/kubernetes#35778]
I see that 1.5.0.alpha2 already includes replica type and a count of 3.  However I think it would be better if this was a tunable parameter via the StorageClass.

**Comment by ekozan** [comment]
@humblec can you add this feature ?

**Comment by msau42** [comment]
Does #38579 cover this issue?

**Comment by humblec** [comment]
@danielschonfeld @ekozan I am late here, however would like to mention that this has been already added and available from Kube v1.5
