### ISSUE TITLE
kubeadm upgrade proposal

### ISSUE THREAD

**Issue by danielschonfeld** [kubernetes/kubernetes#35779]
Wanted to make a wish.  Being a long time kubernetes user and having stitched clusters by hand, I am convinced `kubeadm` is the best thing that happened to kubernetes in terms of mass adoption. I think it would be nice if we could do version upgrades with `kubeadm`.  I imagine it wouldn't be too hard needing only to update the versions in the manifests and download a new version of kubelet?

Is there something else I'm missing? Could this become a reality?

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#14
