### ISSUE TITLE
[Kube-proxy] Propose refactor pkg/proxy/config/config.go

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#35781]
**What:**

Propose refactor pkg/proxy/config/config.go

https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/config/config.go

**Why:**

In  pkg/proxy/config/config.go, there are many identical codes between Service and Endpoints.
- ServiceUpdate VS. EndpointsUpdate 

```
type ServiceUpdate struct {
    Services []api.Service
    Op       Operation
}
```

```
type EndpointsUpdate struct {
    Endpoints []api.Endpoints
    Op        Operation
}
```
- ServiceConfigHandler VS. EndpointsConfigHandler

```
type ServiceConfigHandler interface {
    OnServiceUpdate(services []api.Service)
}
```

```
type EndpointsConfigHandler interface {
    OnEndpointsUpdate(endpoints []api.Endpoints)
}
```
- EndpointsConfig VS. ServiceConfig

and almost the same `NewServiceConfig()` VS. `NewEndpointsConfig()`, `endpointsStore.Merge()` VS. `serviceStore.Merge()` and so on. 

So I think we can introduce an abstract layer which can generify both Service and Endpoints here. In this way, reuse some codes.

**How:**

Move Service and Endpoints to interface{}, like:

```
type ObjectUpdate struct {
    Objects []interface{}
    Op        Operation
}
```

```
type ObjectConfigHandler interface  {
    OnObjectUpdate(objects []interface{})
}
```

```
type ObjectConfig struct {
    mux     *config.Mux
    bcaster *config.Broadcaster
    store   *objectStore
}
```

```
func (s *objectStore) Merge(source string, change interface{}) error {
...
}
```

...

@thockin @smarterclayton 

What do you think about it?

Thanks!

**Comment by krmayankk** [comment]
At first thought this seems possible but at the cost of reducing readability of the code. How much code duplication would this save ?

**Comment by m1093782566** [comment]
> At first thought this seems possible but at the cost of reducing readability of the code. 

Yes, I agree with you.

> How much code duplication would this save?

Most of the saved codes will be in the `pkg/proxy/config`. Total number of code lines(not include test code) is 374. So, I guess is about 180 lines?

**Comment by smarterclayton** [comment]
@ncdc since you were also doing this for other components

On Oct 30, 2016, at 2:31 AM, DuJun <notifications@github.com> wrote:

At first thought this seems possible but at the cost of reducing
readability of the code.

Yes, I agree with you.

How much code duplication would this save?

Most of the saved codes will be in the pkg/proxy/config. Total number of
code lines(not include test code) is 374. So, I guess is about 180 lines?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/35781#issuecomment-257134723>,
or mute the thread

**Comment by m1093782566** [comment]
@ncdc do you have any comments?

Thanks!

**Comment by ncdc** [comment]
I don't think this is all that related to what I've been doing in #34727. I'm not sure this is really worth it?

**Comment by thockin** [comment]
I am happy to look at PRs.  This seems relatively low-return, but hacking
stuff like this is a good way for folks to learn the codebase, so I am not
going to discourage it.

**Comment by m1093782566** [comment]
Thanks, I will send a PR in a few days.
