### ISSUE TITLE
Kubectl config unset hangs for very long (couple minutes) 

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#35786]
Apparently there has been introduced some kind of deadlock.

```
strace -f  _output/dockerized/bin/linux/amd64/kubectl config unset clusters.XXXX_kubernetes

...
pid 15707] futex(0x20f2720, FUTEX_WAKE, 1 <unfinished ...>
[pid 15706] clock_gettime(CLOCK_REALTIME,  <unfinished ...>
[pid 15707] <... futex resumed> )       = 0
[pid 15706] <... clock_gettime resumed> {1477659962, 481400174}) = 0
[pid 15707] clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid 15706] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid 15707] <... clock_gettime resumed> {131877, 76853400}) = 0
[pid 15705] <... select resumed> )      = 0 (Timeout)
[pid 15707] futex(0x20f2738, FUTEX_WAIT, 0, {4, 999629035} <unfinished ...>
[pid 15705] futex(0x20f3e50, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 15706] <... select resumed> )      = 0 (Timeout)
[pid 15706] clock_gettime(CLOCK_MONOTONIC, {131877, 77299891}) = 0
```

Same command finishes in milliseconds with some older version of kubectl.

cc: @jessfraz @wojtek-t @gmarek

**Comment by jessfraz** [comment]
its on get time which leads me to believe you are running it on a mac and its the sierra bug is this correct? can you give us the version output of kubectl

**Comment by mwielgus** [comment]
No. Almost head version and Google ubuntu.

**Comment by mwielgus** [comment]
The thing probably blocks while reading kube config. After creating new cluster the problem stopped.

**Comment by mwielgus** [comment]
@gmarek also recently saw similar problems with kubectl where deleting the config helped.

**Comment by gmarek** [comment]
I had a problem with starting e2e cluster. I have to `rm ~/.kube/config && touch ~/.kube/config` to get it working.
