### ISSUE TITLE
watch-spam from leaderelection

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#35794]
leader-election seems to touch the endpoints object for kube-controller-manager every 2 seconds (?).

I notice these messages in the traefik controller logs, but presumably the same problem happens generally:

```
time="2016-10-28T15:21:56Z" level=debug msg="Skipping event from kubernetes map[object:map[metadata:map[resourceVersion:8260905 creationTimestamp:2016-10-21T06:53:41Z annotations:map[control-plane.alpha.kubernetes.io/leader:{\"holderIdentity\":\"ip-172-20-93-113\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2016-10-21T06:53:41Z\",\"renewTime\":\"2016-10-28T15:21:56Z\",\"leaderTransitions\":0}] name:kube-controller-manager namespace:kube-system selfLink:/api/v1/namespaces/kube-system/endpoints/kube-controller-manager uid:1a0148af-975b-11e6-b8af-06e5bea45582] subsets:[] kind:Endpoints apiVersion:v1] type:MODIFIED]" 
```

I worry that the kube-proxy watches will be triggered also?  @thockin do you happen to know?

cf #29772, a similar problem for nodes

**Comment by ravilr** [comment]
@justinsb yes, being discussed over here https://github.com/kubernetes/kubernetes/issues/26637 
https://github.com/kubernetes/kubernetes/issues/34627

**Comment by bprashanth** [comment]
Closing in favor of the mentioned bugs

**Comment by justinsb** [comment]
Thanks for the pointers  - glad to see it is known :-)
