### ISSUE TITLE
Testapi based intergration tests crash when 2 api versions in the same apigroup are not compatible. 

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#35792]
```
panic: storage codec doesn't seem to match given type: Internal type not encodable: converting (v1beta1.PodDisruptionBudget).v1beta1.PodDisruptionBudgetStatus to (v1alpha1.PodDisruptionBudget).v1alpha1.PodDisruptionBudgetStatus: PodDisruptionAllowed not present in src
/usr/local/go/src/runtime/panic.go:500 +0x1a1
/usr/local/go/src/testing/testing.go:579 +0x25d
/usr/local/go/src/runtime/panic.go:458 +0x243
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/storage/cacher.go:192 +0xd39
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/generic/registry/storage_factory.go:61 +0x214
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/policy/poddisruptionbudget/etcd/etcd.go:49 +0x1cc
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/policy/rest/storage_policy.go:52 +0x30b
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/policy/rest/storage_policy.go:36 +0x275
<autogenerated>:1 +0xbf
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/master/master.go:298 +0x2e2
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/master/master.go:228 +0xe0e
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/framework/master_utils.go:230 +0x564
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/framework/master_utils.go:453 +0x50
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/auth/accessreview_test.go:62 +0x119
/usr/local/go/src/testing/testing.go:610 +0x81
/usr/local/go/src/testing/testing.go:646 +0x2ec
```

See https://github.com/kubernetes/kubernetes/pull/34546 for more details.

cc: @lavalamp @caesarxuchao @davidopp

**Comment by mwielgus** [comment]
cc: @fgrzadkowski

**Comment by mwielgus** [comment]
This issue together with https://github.com/kubernetes/kubernetes/issues/35791 block api graduation and changes.

**Comment by fgrzadkowski** [comment]
@deads2k @smarterclayton @nikhiljindal Can guys help with this problem?

**Comment by smarterclayton** [comment]
Wow, that's new and exciting.

**Comment by deads2k** [comment]
> @deads2k @smarterclayton @nikhiljindal Can guys help with this problem?

`testapi` is a parallel API enablement path.  I think that @nikhiljindal and @caesarxuchao are the ones most familiar with its direction.

**Comment by smarterclayton** [comment]
The issue Chao mentioned (if true) is not supported in any way (versioning codec inside another).

**Comment by caesarxuchao** [comment]
https://github.com/kubernetes/kubernetes/blob/master/test/integration/framework/master_utils.go#L332.

It seems we should pass in a serializer rather than a codec as input parameter.

How urgent is this? Are you blocking on this?

**Comment by mwielgus** [comment]
@caesarxuchao It is quite urgent and blocking. Without this we cannot graduate Disruption Budget to beta that is required by couple other teams.

**Comment by caesarxuchao** [comment]
Ok, I'll take another look today. I thought we were going to remove v1alpha1 PDB.

**Comment by mwielgus** [comment]
@caesarxuchao I tried but #35791 was found.

**Comment by caesarxuchao** [comment]
You will hit #35791 even if you keep both versions. So I'll focus on fix #35791.

**Comment by caesarxuchao** [comment]
I sent a PR to fix #35791, that should unblock you. Please ping me if you decide to enable both v1alpha1 and v1beta1, otherwise I won't spend more time on this issue before code freeze.

**Comment by lavalamp** [comment]
@mwielgus is this still a live issue?

**Comment by caesarxuchao** [comment]
Yes. We disabled policy/v1alpha1, so the issue is not triggered.
