### ISSUE TITLE
Cherry picking "mounter" patches on release-1.4

### ISSUE THREAD

**Issue by jessfraz** [kubernetes/kubernetes#35809]
ping @mtaufen @saad-ali @vishh 

Couple questions: I found these PRs in release-1.4 but they didn't at the time have the labels cherry-pick-candidate so I added them, which might have been incorrect.

But it looks like a lot rely on the other so the ones I have are:
#34994 #35161 #35224 #35321 #35646 #35652 #35349 #35350 #35717 #35819 #35813  #35821 #35724 #36267
1. Is this all of them?
2. Do they need to be in 1.4.5 today or should we wait til 1.4.6 if there are more?

**Comment by saad-ali** [comment]
@jessfraz Please hold off on cherry-picking any containerized mounter changes. We need to time to qualify them. @vishh @jingxu97 @mtaufen or I will reach out to you to coordinate a release. Thanks!

**Comment by jessfraz** [comment]
ok cool thanks! this was what I was hoping phew

**Comment by vishh** [comment]
@jessfraz https://github.com/kubernetes/kubernetes/pull/35319 is un-related to "mounting". I'd go ahead with a cherry-pick for that since its a GKE production issue

**Comment by jessfraz** [comment]
ok cool good to know

**Comment by jingxu97** [comment]
I think  #36267 and #36681 #36920 should also included.

**Comment by Random-Liu** [comment]
CRI validation test in #36920 is introduced in 1.5. We may not need to cherry-pick it.

**Comment by jingxu97** [comment]
Talked to @mtaufen, remove #36920 since 1.4 uses older image version
