### ISSUE TITLE
Doc Request: Document required ports for Kubeadm

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#35818]
Neither Kubeadm reference nor kubeadm getting-started-guide contain a list of ports which need to be open within the cluster for a kubeadm deployment to function.  Kubeadm appears to require additional port access beyond what older kubernetes does.  This causes a lot of troubleshooting pain in getting things working while exercising reasonable port security.  

For my part, I was only able to get it to work once I threw open all TCP ports in the cluster; there are apparently ports required which don't show up in the list of "listening" ports on the master.

The list of ports and port ranges should be documented.

**Comment by luxas** [comment]
Feel free to do it :)

We have added preflight checks now to the kubeadm master build, so it will be interactively shown to the user now what's missing.

ref: https://github.com/kubernetes/kubernetes/issues/34046

**Comment by jberkus** [comment]
Can't do it because I can't figure out which ports are required, per OP.  And the preflight check doesn't really help when ports are being blocked at the router level, or when some ports are dynamically assigned.

I'll note that even on that issue you don't seem to know the full list of ports required, given the elipsis.

**Comment by jberkus** [comment]
If someone else wants to add a complete list of ports in a comment, I'll be happy to turn that into a doc patch.

**Comment by luxas** [comment]
For sure I know which ports are required, I also mentioned that in #34046

Here we're checking and validating that the required ports are open in the master version of kubeadm which we will push to stable very soon: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/preflight/checks.go#L196
(note that two of them are configurable, but defaults to 6443 and 9898)

But feel free to make a doc improvement on that as well, preferably in `docs/admin/kubeadm`

**Comment by jberkus** [comment]
Thanks, will do.

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#12
