### ISSUE TITLE
Federated Service Not Updated

### ISSUE THREAD

**Issue by watkinsv-hp** [kubernetes/kubernetes#35827]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): "is:issue is:open federation service", "is:issue is:open federated service"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"} 
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): jessie (Debian 8)
- **Kernel** (e.g. `uname -a`): Linux ip-172-20-110-96 4.4.23-k8s #1 SMP Fri Sep 30 13:51:02 UTC 2016 x86_64 GNU/Linux
- **Install tools**: kops
- **Others**: 

**What happened**:
We are applying label selectors to a service that is federated. e.g., 

``` yaml
apiVersion: v1
kind: Service
metadata:
  name: date-time-federated
spec:
  selector:
    name: update-demo
    version: black
  ports:
    -
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
```

**What you expected to happen**:
We expect the federated service to be updated on all clusters. Instead, the controller manager reports no changes to the service.

When we print the service YAML from the federation, it contains the new label selectors. When we print the service YAML directly from the clusters' APIs (who are members of the federation) there are no updates to the service whatsoever.

**How to reproduce it** (as minimally and precisely as possible):
Set `--v=5` on the federation controller manager. Create a federated service. Add some label selectors to the service and apply it through the federation. Watch the federation controller manager logs while applying the new label selectors and observe the logs that indicate there is no update because there are no perceived changes to the service.

**Anything else do we need to know**:
We see that the controller manager is only evaluating the ports for changes to the service. See the  [1.4.0 reference](https://github.com/kubernetes/kubernetes/blob/v1.4.0/federation/pkg/federation-controller/service/servicecontroller.go#L397-L411) and the [master reference](https://github.com/kubernetes/kubernetes/blob/master/federation/pkg/federation-controller/service/servicecontroller.go#L419-L433). 

Do we have the correct expectation that update criteria should be broader than just changes to ports? 

Our use case is for deployment update strategies like sticking a canary under the service.

Thanks a bunch!

**Comment by foxish** [comment]
@kubernetes/sig-cluster-federation

**Comment by quinton-hoole** [comment]
cc @mfanjie 
@foxish Thanks for the comprehensive bug report.  
Yes, If I'm reading the code correctly there appears to be a bug in the update logic.  It looks like only changes in service ports are propagated, not other changes.  That's wrong.

https://github.com/kubernetes/kubernetes/blob/master/federation/pkg/federation-controller/service/servicecontroller.go#L419

I think that we should use [ObjectMetaAndSpecEquivalent](https://github.com/kubernetes/kubernetes/blob/master/federation/pkg/federation-controller/util/meta.go#L79) here, rather than the custom logic in the above code.

@mfanjie Could you take a look at this?

**Comment by mfanjie** [comment]
I will follow

**Comment by nikhiljindal** [comment]
Not sure if this issue still exists. I see that we dont have a test for updating services, we should add that: https://github.com/kubernetes/kubernetes/blob/12a80380bcd9f7e18e6e7561fae3b9eed4784f49/test/e2e_federation/federated-service.go#L115

cc @shashidharatd

**Comment by shashidharatd** [comment]
I would add a test case for updating service

**Comment by shashidharatd** [comment]
This has been fixed and also a e2e test case been added to verify the behavior in PR #41254
/close
