### ISSUE TITLE
Don't always update gcloud in `cluster/gce/util.sh`

### ISSUE THREAD

**Issue by wonderfly** [kubernetes/kubernetes#35834]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): `gcloud update`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Kubernetes version** (use `kubectl version`): all :smile: 

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): all
- **Kernel** (e.g. `uname -a`): all
- **Install tools**:
- **Others**:

**What happened**:
`cluster/gce/util.sh` uses the `gcloud` cli a lot and does a `gcloud components update` (in the commonly used function `verify-prereqs`) before doing things like `kube-down`. `gcloud` updates can introduce breaking changes (for example in the recent 132.0.0 release it removed a bunch of flags). This has caused cross-the-board test failures like #35654.

But this is not limited to just tests. Any kubernetes GCE users who rely on the `kube-up` and `kube-down` commands could have been broken.

**What you expected to happen**:

Stop updating gcloud automatically. We could either warn user to have the required dependencies installed, or pin to specific versions of dependencies like gcloud.

**How to reproduce it** (as minimally and precisely as possible):
download 1.4.4 release tarball
run `kube-up` and `kube-down`

**Anything else do we need to know**:

**Comment by foxish** [comment]
cc @kubernetes/sig-cluster-lifecycle

**Comment by jlowdermilk** [comment]
cc @kubernetes/sig-testing 

I think it's reasonable to remove gcloud update calls from util.sh scripts, as I believe gcloud is updated out of band by k8s continuous testing. The scripts will still need to work with latest, so maybe they should check for a minimum version.

**Comment by wonderfly** [comment]
> maybe they should check for a minimum version.

Good idea.

**Comment by ixdy** [comment]
Yeah, we definitely want to continue using latest `gcloud` in CI so that we know if things break, but I think it's reasonable to remove the update itself from the kubernetes cluster util scripts.
