### ISSUE TITLE
Controllers must all share the same certificate

### ISSUE THREAD

**Issue by cjyar** [kubernetes/kubernetes#35849]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

controller key, duplicate certificates, controller rekey

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

bug report

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"clean", BuildDate:"2016-10-16T06:36:33Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"clean", BuildDate:"2016-10-16T06:20:04Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: self-hosted VM
- **OS** (e.g. from /etc/os-release): Ubuntu 14.04.05
- **Kernel** (e.g. `uname -a`): 4.4.0-45
- **Install tools**: Manual installation
- **Others**:

**What happened**:

I generated an independent cert+key for each of my two controllers. Pods (especially kube-dns) had a high failure rate in talking to the apiserver. This showed up as 401 status in the apiserver log, and "the server requested the client to provide authenticate" in the pod kubedns log.

**What you expected to happen**:

I expected it to work. :)

**How to reproduce it** (as minimally and precisely as possible):
1. Generate a different certificate and key for each controller machine (apiserver, controller manager, scheduler).
2. Load kube-dns.

**Anything else do we need to know**:

In many places, standard practice is to issue an independent certificate for each server. If Kubernetes doesn't support that configuration, it should be documented.

**Comment by liggitt** [comment]
Did you sign them all with the same CA and configure that CA to be trusted by all components?

**Comment by cjyar** [comment]
Yes and yes.

**Comment by liggitt** [comment]
Are you providing service account keys to the API server and controller manager? The private key given to the controller manager to sign service account tokens must match the public key given to the API to verify service account tokens.

**Comment by cjyar** [comment]
On each of the two controller nodes, I have a CA cert, host cert, and host key. The host cert+key are specific to that node, signed by the CA. The API server and controller manager share the CA cert and host key. Here are all of the startup options that are relevant to certificates:

    kube-apiserver \
    --client-ca-file=/var/lib/kubernetes/ca.pem \
    --etcd-cafile=/var/lib/kubernetes/ca.pem \
    --etcd-certfile=/var/lib/kubernetes/thishost.pem \
    --etcd-keyfile=/var/lib/kubernetes/thishost-key.pem \
    --kubelet-certificate-authority=/var/lib/kubernetes/ca.pem \
    --service-account-key-file=/var/lib/kubernetes/thisthost-key.pem \
    --tls-cert-file=/var/lib/kubernetes/thishost.pem \
    --tls-private-key-file=/var/lib/kubernetes/thishost-key.pem \

and

    kube-controller-manager \
    --root-ca-file=/var/lib/kubernetes/ca.pem \
    --service-account-private-key-file=/var/lib/kubernetes/thishost-key.pem \

...so the API server's cert matches the controller manager's key. But the two controller nodes have different cert+key pairs. So ctrl1's cert doesn't match ctrl2's key.

**Comment by liggitt** [comment]
Service account tokens signed by any controller must be valid against any API server in an HA setup. 

That means all controller instances must use the same private key to sign service account tokens and all API servers must use the same public key to verify service account tokens. 

For convenience, you can give the API server the private key and it will extract the public key portion, but if you are trying to tightly control keys, actually making a public/private keypair and only giving the public half to the API servers would make sense. 

Also note that this key is not required to be the same as your etcd/client-cert/serving-cert private key. Those can all be unique to each host/process. 

In 1.5, the API server can use multiple public keys to verify tokens, so you could give each controller a unique signing key and each API server a bundle of all the corresponding public keys, so they could validate tokens from any controller. 

In any case, once you resolve how you want to get tokens signed with a key all API servers will recognize, you'll need to remove invalid tokens from etcd… automated cleanup doesn't exist yet

**Comment by cjyar** [comment]
Thanks for the explanation! I didn't get that understanding from the docs. In fact, my chief complaint here is documentation-related: The typical thing to do with certs in other contexts will break Kubernetes. Given that, it seems worthwhile to remind admins that Kubernetes handles certificates a bit differently.
