### ISSUE TITLE
Ingress TLS Secret

### ISSUE THREAD

**Issue by svda** [kubernetes/kubernetes#35879]
I'm running a GCLB ingress with TLS termination. The certificate is about to expire, and I would like to update the secret. Unfortunately kubectl replace -f ./secrets.yaml (containing the base64 encoded tls) seems to have no effect, nor does kubectl replace -f ./load-balancer.yaml (which updates the ingress).
I want to avoid deleting and re-creating the Ingress because of IP rotation. Is there any way to update the certificate without recreating the Ingress?

**Comment by bprashanth** [comment]
What version are you running? this should work, see: https://github.com/kubernetes/contrib/issues/1396 and please provide a repro (ingress and service yaml you're using, and the secret with just the sensitive bits anonamized) if you can on that bug and I can help debug.

**Comment by svda** [comment]
Thank you.
