### ISSUE TITLE
bazel and golint docs

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#35899]
Problem

Looks like issueing a PR without the new BUILD files is  a little tricky.  I ran update Bazel, and got > 100 updates.  Golint seems to now be more likely to break builds also.  So we should streamline.

Solution

- When golint fails, try to print out why it failed and what was wrong (esp wrt bazel).
- Update bazel.md with more details on how to fix bazel related / lint issues.
- Update developing.md with golint / hack/verify-golint.sh w/ golint installation requirement (or bootstrap if theres a crossplatform way to do so).

**Comment by jayunit100** [comment]
cc @mikedanese @spxtr

**Comment by jayunit100** [comment]
ahhh 373be74d7573c12c1ce2d59fa80e3a6641a43cd0 just saw "disable bazel build till we figure out what to do with the mac"

**Comment by jayunit100** [comment]
in any case, I think the best thing to do is close for now , since bazel support is evolving etc, this is just extra noise right now.

**Comment by spxtr** [comment]
Thanks for trying it out. I'm working on bazel testing in CI, which should make it more stable.
