### ISSUE TITLE
Get pods {{range.items}}{{.metadata.name}}:{{end}} hack/make-rules/test-cmd.sh: line 80

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#35898]
from https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/35795/pull-kubernetes-unit/2451/

```
I1031 06:10:30.426] FAIL!
I1031 06:10:30.426] Get pods {{range.items}}{{.metadata.name}}:{{end}}
I1031 06:10:30.426]   Expected: 
I1031 06:10:30.426]   Got:      nginx-deployment-4049173614-b4kk2:nginx-deployment-4049173614-wtdu2:
I1031 06:10:30.426] (B
I1031 06:10:30.426] 2841 hack/make-rules/test-cmd.sh
I1031 06:10:30.426] (B
W1031 06:10:30.443] hack/make-rules/test-cmd.sh: line 80: 19973 Terminated              "${KUBE_OUTPUT_HOSTBIN}/kube-apiserver" --address="127.0.0.1" --public-address-override="127.0.0.1" --port="${API_PORT}" --admission-control="${ADMISSION_CONTROL}" --etcd-servers="http://${ETCD_HOST}:${ETCD_PORT}" --public-address-override="127.0.0.1" --kubelet-port=${KUBELET_PORT} --runtime-config=api/v1 --storage-media-type="${KUBE_TEST_API_STORAGE_TYPE-}" --cert-dir="${TMPDIR:-/tmp/}" --service-cluster-ip-range="10.0.0.0/24" 1>&21
```

**Comment by smarterclayton** [comment]
Really suspect this is #31220

**Comment by smarterclayton** [comment]
@kargakis  This is putting us into test-go post-commit run is broken

**Comment by kargakis** [comment]
cc: @mfojtik

**Comment by smarterclayton** [comment]
marked this p0 - if a fix isn't easy let's try to identify what introduced this and revert.

**Comment by saad-ali** [comment]
This flake [appears to have started](https://k8s-testgrid.appspot.com/google-unit#test-go&width=5&exclude-non-failed-tests=) on: 2016-10-30 07:19 PDT took 19m55s 

First instance: [kubernetes-test-go/18900/](
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-test-go/18900/): 
```
FAIL!
Get pods {{range.items}}{{.metadata.name}}:{{end}}
  Expected: 
  Got:      nginx-deployment-4049173614-yfi3e:nginx-deployment-4049173614-zer7v:
(B
2841 hack/make-rules/test-cmd.sh
(B
+++ [1030 07:39:11] Clean up complete
/go/src/k8s.io/kubernetes/hack/lib/util.sh: line 97: 19923 Terminated              "${KUBE_OUTPUT_HOSTBIN}/kube-apiserver" --address="127.0.0.1" --public-address-override="127.0.0.1" --port="${API_PORT}" --admission-control="${ADMISSION_CONTROL}" --etcd-servers="http://${ETCD_HOST}:${ETCD_PORT}" --public-address-override="127.0.0.1" --kubelet-port=${KUBELET_PORT} --runtime-config=api/v1 --storage-media-type="${KUBE_TEST_API_STORAGE_TYPE-}" --cert-dir="${TMPDIR:-/tmp/}" --service-cluster-ip-range="10.0.0.0/24" 1>&2
Makefile:188: recipe for target 'test-cmd' failed
make: *** [test-cmd] Error 1
+ rc=2
+ [[ 2 -eq 124 ]]
+ [[ 2 -eq 137 ]]
+ [[ 2 -ne 0 ]]
+ echo 'Build failed'
Build failed
+ echo 'Exiting with code: 2'
Exiting with code: 2
+ exit 2
Build step 'Execute shell' marked build as failure
```

It is flaking frequently, blocking PRs from getting merged, and slowing the submit queue (`kubernetes-test-go` at 75%).

As on-call, I'm going to try and identify the cluprit and revert. Can use all help in doing so.

**Comment by smarterclayton** [comment]
@JacobTanenbaum can you investigate whether your additional tests could
cause this (by breaking the deployment of those pods, for instance)

**Comment by saad-ali** [comment]
PR #https://github.com/kubernetes/kubernetes/pull/35050 looks most suspect to me. It mucked with `nginx-deployment`, and the errors we are seeing in each of the failures is related to `nginx-deployment`:
```
FAIL!
Get pods {{range.items}}{{.metadata.name}}:{{end}}
  Expected: 
  Got:      nginx-deployment-4049173614-79v5l:nginx-deployment-4049173614-ruf3m:
(B
2841 hack/make-rules/test-cmd.sh
```

That PR was merged at Oct 30, 2016, 6:18 AM PDT and the first flake in `kubernetes-test-go` was at Oct 30, 2016, 7:19 AM PDT.

Thoughts? 

CC @JacobTanenbaum @janetkuo @deads2k @smarterclayton

**Comment by saad-ali** [comment]
I'm going to initiate a revert of #35050 to see if that fixes the issue

**Comment by janetkuo** [comment]
IMO we can just change the flaky test to not get pods but some other resources, such as deployments. We can't really expect `kubectl delete deployments` to clean up pods immediately. 

```
2840	  ### sort-by should not panic if no pod exists
2840	  # Pre-condition: no POD exists
2841	  kube::test::get_object_assert pods "{{range.items}}{{$id_field}}:{{end}}" ''
2842	  # Command
2843	  kubectl get pods --sort-by="{metadata.name}"
2844	  kubectl get pods --sort-by="{metadata.creationTimestamp}"
```

**Comment by saad-ali** [comment]
> IMO we can just change the flaky test to not get pods but some other resources, such as deployments. We can't really expect kubectl delete deployments to clean up pods immediately.

@janetkuo I'm going to proceed with revert (https://github.com/kubernetes/kubernetes/pull/36003). Please feel free to send a follow up PR to handle this more gracefully.

**Comment by saad-ali** [comment]
Going to leave this opened until we have a few hours of `kubernetes-test-go` runs with the revert. Want to verify, with some degree of certainty, that the revert took care of this flake.

**Comment by saad-ali** [comment]
We had 15 green runs of `kubernetes-test-go` in a row. Considering this flake fixed.
