### ISSUE TITLE
Docker version for Kubernetes

### ISSUE THREAD

**Issue by illyul** [kubernetes/kubernetes#35891]
In case, I use Kubernetes v1.4.3 with Docker version 1.12.1 and Docker version 1.11.1. It had some problems. Such as:
Log kubelet:

> E1028 10:13:03.934044   32090 docker_manager.go:746] Logging security options: {key:seccomp value:unconfined msg:}

Which Docker version is the most suitable for Kubernetes?

**Comment by justinsb** [comment]
For 1.4, 1.11.2 is the validated version.

**Comment by yujuhong** [comment]
1.12 should be compatible (i.e., passing all functional tests), but we sank the most time qualifying 1.11.2 on GCE.
The error message you saw doesn't seem intentional, I sent a PR to remove that: #35980

**Comment by illyul** [comment]
Thanks for helping me.
