### ISSUE TITLE
Access denied when trying to connect to pod

### ISSUE THREAD

**Issue by AndreeaDora** [kubernetes/kubernetes#35909]
**Kubernetes version** (use `kubectl version`): 1.0.2

**Environment**:
- **Cloud provider or hardware configuration**: I am using `hyperkube` as a cloud provider, I deployed it locally
- **OS** (e.g. from /etc/os-release): ubuntu 14.04
- **Kernel** (e.g. `uname -a`): Linux ubuntu 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: In order to deploy hyperkube, proxy and etcd I used the available images from docker hub. 

**What happened**: 
I deployed a single container pod that tries to connect to another container in a different pod using the ip of the service created for the second pod. I did a exec into the first container and I am able to see the ip of the service, but I get access denied when i try to connect to it.

The configuration for the first pod:

```apiVersion: v1
kind: Pod
metadata:
  name: controller
spec:
  containers:
  - name: controller
    image: <image_name>
    ports:
      - containerPort: 8080
        hostPort: 8082
    command: ["/bin/bash"]
    args: ["-c", "<command>"]
    env:
      - name: SERVICE_ENDPOINT
        value: http://$SERVICE_HOST:6060
```

The configuration for the second pod:

```apiVersion: v1
kind: Pod
metadata:
  name: second_pod
  labels:
    app: servicePod
spec:
  containers:
  - name: second_pod
    image: <image_name>
    ports:
      - containerPort: 6060
      - containerPort: 6061
    volumeMounts:
      - mountPath: /config
        name: storage1
        readOnly: true
      - mountPath: /tmp
        name: storage2
    command: ["/bin/bash"]
    args: ["-c", "<command>"]
```

Service configuration:

```apiVersion: v1
kind: Service
metadata:
  name: servicePod
  labels:
    app: servicePod
spec:
  selector:
    app: servicePod
  ports:
  - name: servicePod1
    port: 6060
    targetPort: 6060
    protocol: TCP
  - name: servicePod2
    port: 6061
    targetPort: 6061
    protocol: TCP
```

**What you expected to happen**: The expected behavior is to be able to connect to the second pod using the service.

**Comment by soninob** [comment]
@k8s-merge-robot - any news about this?

**Comment by AndreeaDora** [comment]
Are there any updates on this issue?

**Comment by liggitt** [comment]
What denial are you seeing? The kubernetes authorization layer isn't involved in traffic to services other than the kubernetes service

**Comment by liggitt** [comment]
closing for lack of information?
