### ISSUE TITLE
NetworkPolicy does not allow update on Spec

### ISSUE THREAD

**Issue by pendoragon** [kubernetes/kubernetes#35911]
I tried to update the NetworkPolicy Spec field with more ingress rules but got `Forbidden: updates to networkpolicy spec are forbidden.`
It seems NetworkPolicy does not allow update on Spec https://github.com/kubernetes/kubernetes/blob/3e3ff447d28075904177d3e7cad73e405b271de5/pkg/apis/extensions/validation/validation.go#L836
This means if I want to have more ingress rules, I will have to add those in a new networkpolicy in the same namespace.
Any reason why I should not add those in the existing one(update the existing networkpolicy)? Thanks!

**Comment by caseydavenport** [comment]
This is as designed for now.  

The expectation is that updates to the spec will be allowed when the NetworkPolicy API moves from v1beta1 to GA.

**Comment by lxpollitt** [comment]
(And that is planned for Kubernetes 1.6 release.)

**Comment by Pendoragon** [comment]
good to know, thanks! @caseydavenport @lxpollitt

**Comment by caseydavenport** [comment]
Note that the PR to move NetworkPolicy to v1 did not make it into v1.6, but is now planned for 1.7: #39164

**Comment by danwinship** [comment]
Oh, I didn't know about this bug and that didn't get changed in #39164 but we can do it as another PR after. (I'm trying to not make any more changes there so we can get it merged.)
