### ISSUE TITLE
Consider making List a distinct type in `pkg/api` and `pkg/storage`

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#35929]
A very, very long time ago we decided to unify Lists (PodList, NodeList) and Objects (Pod, Node) under the same interface, because the response from the server could be typed and versioned independently.  It has been beneficial to have the server have a unique type response because it simplifies some generation (a PodList contains an Items array of type Pod) for client code and makes validation easier.  It also makes conversions and defaulting somewhat simpler, because we can generate code that doesn't have to do an expensive type check per item in the list (when listing 100k pods that is certainly a cost we care about).

However, internally this causes a number of complicated gyrations - we pass opaque runtime.Objects down into the storage.Interface code and then perform reflection to see whether it has an `Items` field, then return that opaque object and do reflection to calculate fields.  Internally, it would probably make sense for there to be a coherent `runtime.List` type that has `Items []runtime.Object` as a field and links in other metadata as necessary.  Certainly everything at the storage layer has no need to know anything about the type other than as a list of runtime.Objects.

Evaluating the pro/cons of this change may be necessary to get some other optimizations (like a cache of recently serialized objects indexed by their name / resource version), but needs to be justified in that context.  Recording it here for posterity.

**Comment by smarterclayton** [comment]
@wojtek-t this is actually the next highest item in profiles from the fake node scenario (and creating self links).  We have to walk all the children of the list to set selfLink, and we do that in the most expensive way possible (convert array of Pod -> array of runtime.Object and then back).  SelfLink is also expensive because URL.String() has to allocate many strings.  We should be able to avoid most of the work for both.  I think this may be the best thing to do (would unify our internal handling of Lists under a concrete type) that can then be versioned per release.

Will play around with this as I'm doing the server API version work.

**Comment by wojtek-t** [comment]
Yes - I've also seen that, but I'm mostly fighting with etcd v3 now. Happy to help with this once done with other work.

**Comment by hongchaodeng** [comment]
cc @xiang90

**Comment by hongchaodeng** [comment]
Hi @smarterclayton,

I understand the point in pkg/storage. Would you share some minds on what needs to be change din pkg/api?

I am thinking that these two pkgs are separate and I can start changing it in pkg/storage first.

**Comment by smarterclayton** [comment]
We can probably wait until my server API group refactor lands early in 1.6,
because it will overlap with those changes.  It's probably easier to wait
for that.

I fixed the major perf problem just be being more efficent with reflection
in a pull last night, so this is less critical for 1.5

On Nov 4, 2016, at 1:20 PM, Hongchao Deng <notifications@github.com> wrote:

Hi @smarterclayton <https://github.com/smarterclayton>,

I understand the point in pkg/storage. Would you share some minds on what
needs to be change din pkg/api?

I am thinking that these two pkgs are separate and I can start changing it
in pkg/storage first.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/35929#issuecomment-258493759>,
or mute the thread
