### ISSUE TITLE
Finalizer for ThirdPartyResourceData

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#35949]
Mentioned elsewhere, but not fully covered in an issue.

Need to add a finalizer to wipe out etcd data on object deletion.

@kubernetes/sig-api-machinery

**Comment by deads2k** [comment]
> Mentioned elsewhere, but not fully covered in an issue.
> 
> Need to add a finalizer to wipe out etcd data on object deletion.

I agree.  Related to https://github.com/kubernetes/features/issues/95

**Comment by caesarxuchao** [comment]
Do you mean delete all the thirdpartyResourceData when the thirdpartyResource is deleted?

**Comment by deads2k** [comment]
> Do you mean delete all the thirdpartyResourceData when the thirdpartyResource is deleted?

Yeah.  Otherwise recreation of the same TPR does whacky stuff.

**Comment by caesarxuchao** [comment]
Looks like it could use the synchronous garbage collection: https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/synchronous-garbage-collection.md

**Comment by liggitt** [comment]
no need for the delete API call to hang while it's trying to clean up the related third party, an async finalizer seems like it would be better

**Comment by deads2k** [comment]
> no need for the delete API call to hang while it's trying to clean up the related third party, an async finalizer seems like it would be better

From what I gather, synchronous garbage collection doesn't block the delete call.  The delete call completes without deleting the resource, instead it marks a finalizer and at some later point a controller cleans up the dependants and deletes the head.

**Comment by liggitt** [comment]
does that require setting ownerRef on every thirdpartyresourcedata object?

**Comment by deads2k** [comment]
> does that require setting ownerRef on every thirdpartyresourcedata object?

Now that bit makes me very unhappy. None may remain, and `ownerRef` may allow some to escape.

**Comment by brendandburns** [comment]
I thought about this some more, I think the simplest solution is to mark the TPR as 'deleting' which has the effect of blocking all new writes to the TPR, but doesn't actually delete it.  Then a GC controller picks up the TPRs that are deleting and works to delete all of the resources owned by that TPR.

Once the TPR is actually empty, then it is deleted by the GC controller.

Thoughts?

**Comment by deads2k** [comment]
> Then a GC controller picks up the TPRs that are deleting and works to delete all of the resources owned by that TPR.
> 
> Once the TPR is actually empty, then it is deleted by the GC controller.
> 
> Thoughts?

Because the GC controller can be influenced by the end user (user who can modify a Foo, can remove the ownerRef), I think that unsuitable.  I want the stronger control of an unconditional finalizer.

@AdoHe the finalizer issue I mentioned.

**Comment by AdoHe** [comment]
@deads2k Thanks :)

**Comment by enisoc** [comment]
This is fixed for CustomResource, the new version of TPR. Users should migrate to CustomResource, as there are no plans to add a finalizer for TPR which is now deprecated.
