### ISSUE TITLE
Make the names of the cluster and secret objects created by `kubefed join` customizable

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#35954]
`kubefed join` command takes the kubeconfig context names of the clusters and generates `federation/v1beta1.Cluster` and `v1.Secret` resources from it. It uses the kubeconfig context name to generate these resource names. While there aren't many restrictions on the context names, Cluster resource names must adhere to RFC 1035 and Secret names must adhere to RFC 1123 subdomain naming scheme.

We initially considered automatically converting context names to the names that adhere to these specs. But after much deliberation, we don't think we should automatically convert the names. It might surprise users. And we have to explain how we do this conversion. And that conversion might break in several cases: len(context) > 256 for 2 clusters that when truncated aren't unique, some characters we miss/fail to convert and all the edge cases that come with it.

Instead we now plan to provide a way to customize these names via flags, so that users have more control over how these names are created if they don't confer to RFC 1123 subdomain spec and have a way to reason about it.

We need to make the necessary changes in the code to allow name customization via flags.

cc @kubernetes/sig-cluster-federation @nikhiljindal

**Comment by dims** [comment]
@madhusudancs This needs to be triaged as a release-blocker or not for 1.5

**Comment by madhusudancs** [comment]
This is still for v1.5. And is a release blocker for v1.5.

PR #36869 fixes this.

**Comment by dims** [comment]
@madhusudancs referenced PR has merged. So closing this one
