### ISSUE TITLE
Node e2e fails with "Failed to configured firewall" and "unable to create gce instance"

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#35983]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report
**Kubernetes version** (use `kubectl version`): PR builder
**Environment**: Node e2e
**What happened**:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/35937/pull-kubernetes-node-e2e/2594/ failed with:

```
W1031 16:04:18.750] E1031 16:04:18.749832     927 remote.go:205] Failed to configured firewall: command [ssh -i /home/jenkins/.ssh/google_compute_engine -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o CheckHostIP=no -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o LogLevel=ERROR 104.154.157.63 -- sudo sh -c 'iptables -L INPUT | grep "Chain INPUT (policy DROP)"&&(iptables -C INPUT -w -p TCP -j ACCEPT || iptables -A INPUT -w -p TCP -j ACCEPT)&&(iptables -C INPUT -w -p UDP -j ACCEPT || iptables -A INPUT -w -p UDP -j ACCEPT)&&(iptables -C INPUT -w -p ICMP -j ACCEPT || iptables -A INPUT -w -p ICMP -j ACCEPT)'] failed with error: exit status 1 and output:
W1031 16:04:18.750]  output: 
W1031 16:04:18.926] E1031 16:04:18.926145     927 remote.go:214] Failed to configured firewall: command [ssh -i /home/jenkins/.ssh/google_compute_engine -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o CheckHostIP=no -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o LogLevel=ERROR 104.154.157.63 -- sudo sh -c 'iptables -L FORWARD | grep "Chain FORWARD (policy DROP)" > /dev/null&&(iptables -C FORWARD -w -p TCP -j ACCEPT || iptables -A FORWARD -w -p TCP -j ACCEPT)&&(iptables -C FORWARD -w -p UDP -j ACCEPT || iptables -A FORWARD -w -p UDP -j ACCEPT)&&(iptables -C FORWARD -w -p ICMP -j ACCEPT || iptables -A FORWARD -w -p ICMP -j ACCEPT)'] failed with error: exit status 1 and output:
W1031 16:04:18.926]  output: 
[...]
I1031 16:09:27.415] unable to create gce instance with running docker daemon for image e2e-node-ubuntu-trusty-docker10-v1-image.  instance tmp-node-e2e-ab46b372-e2e-node-ubuntu-trusty-docker10-v1-image not running docker daemon - Command failed: Permission denied (publickey).
```

**What you expected to happen**: Not that.
**How to reproduce it** (as minimally and precisely as possible): PR #35937 seems to be doing a good job at it, but it looks like it came up in https://github.com/kubernetes/kubernetes/pull/35669#issuecomment-257542860 as well.

cc @kubernetes/test-infra-maintainers

**Comment by Random-Liu** [comment]
The code is introduced in https://github.com/kubernetes/kubernetes/pull/33795, and those iptable operations kept failing since then.
It seems that this won't cause test failure, but we should get rid of this.

@freehan

**Comment by bprashanth** [comment]
Isn't this failing because:
Command failed: Permission denied (publickey)
and not the actual iptables command?

**Comment by Random-Liu** [comment]
The second is error is an real issue:
```
I1031 16:09:27.415] unable to create gce instance with running docker daemon for image e2e-node-ubuntu-trusty-docker10-v1-image.  instance tmp-node-e2e-ab46b372-e2e-node-ubuntu-trusty-docker10-v1-image not running docker daemon - Command failed: Permission denied (publickey).
```

This happens on different images, including containervm, ubuntu-trusty and gci. Because we don't have a working dashboard for pr test now, I don't know what link to paste here.

This may even related to https://github.com/kubernetes/kubernetes/issues/35935.

**Comment by bprashanth** [comment]
fwiw "Permission denied (publickey)" is usually ssh, and usually becasue no private key in  ~/.ssh/ matches public key indexed under username@hostname in remote-vm:~/.ssh/authorized_keys (or some other such mismatch has occured)

**Comment by ixdy** [comment]
Does it always fail ssh near the beginning of the test run? Maybe the VM is still starting up and isn't accepting ssh connections yet?

**Comment by Random-Liu** [comment]
> Does it always fail ssh near the beginning of the test run? Maybe the VM is still starting up and isn't accepting ssh connections yet?

@ixdy, There are 2 different kinds of failures I found. In node e2e, we do periodically `ssh` to [check whether the instance is running after creating it](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/runner/remote/run_remote.go#L492-L520). After that, we'll [run several ssh commands to initialize the node](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/remote/remote.go#L158-L304).

* In some of the failures, the initial readiness check just timeout, because we keep getting. For example, pull-kubernetes-node-e2e/2776/:
```
unable to create gce instance with running docker daemon for image e2e-node-ubuntu-trusty-docker10-v1-image.  instance tmp-node-e2e-e000ce5e-e2e-node-ubuntu-trusty-docker10-v1-image not running docker daemon - Command failed: Permission denied (publickey).
```
* However, in some of the failures, it seems that the initial ssh readiness check passed, but ssh didn't work after that. For example, pull-kubernetes-node-e2e/2775/:
```
I1101 12:49:30.345] Failure Finished Test Suite on Host tmp-node-e2e-a20f8255-e2e-node-containervm-v20160604-image
I1101 12:49:30.345] command [ssh -i /home/jenkins/.ssh/google_compute_engine -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o CheckHostIP=no -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o LogLevel=ERROR 104.154.196.143 -- mkdir /tmp/gcloud-e2e-362992428] failed with error: exit status 255 and output:
I1101 12:49:30.345] Permission denied (publickey).
```

**Comment by yujuhong** [comment]
Another occurrence: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/36112/pull-kubernetes-node-e2e/3122/

**Comment by dchen1107** [comment]
I am closing this as obsolete issue since node e2e now configured the user with --ssh-user flag, and we haven't observed the same Permission denied (publickey) for a while.
