### ISSUE TITLE
[minor] What to vendor, and how to lint.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#35985]
Problem:
We dont have a consistent policy on what we do vs. do not vendor.

Solution:
Just updating our vendoring.md doc with the policy we want going forwards.
- Decide what we want to vendor / what the cutoff is for things that should/shouldnt be vendored.  Examples to consider: golint, bindata are examples of things which could be made to work w/o vendoing but could be vendored if we wanted to .  bindata is vendored, lint isnt.  
- Golint is especially interesting b/c there may be backward non-compatible changes like what was fixed for compilation in (i.e.  https://github.com/kubernetes/kubernetes/pull/35703).  in sig-testing today consensus was we probably dont want to vendor it anyway, but its good to bring this up explicitly for community consensus.

cc @liggitt @spxtr  @kubernetes/sig-testing

**Comment by spiffxp** [comment]
/close
there are other issues open for each of these:
- issue asking for vendoring docs https://github.com/kubernetes/community/issues/350
- issue around golint https://github.com/kubernetes/kubernetes/issues/37254
