### ISSUE TITLE
pkg/client/restclient/request.go should not double decode into fake Status

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#35982]
In request.go in `Request#transformResponse` we pre decode into Status to determine whether the user sent us a Status response.  We should lazily perform that action in the Result, instead of on every action, because that results a double unmarshal of the object.

@deads2k I'll take this for 1.5.

**Comment by smarterclayton** [comment]
@kubernetes/sig-api-machinery doubles the numbers of decodes we do from the client.  There was a 1.1 server hack we put in but that can be dropped now.

**Comment by deads2k** [comment]
Thanks

**Comment by smarterclayton** [comment]
Fixed open, should double client performance when clients are mostly readers.
