### ISSUE TITLE
 make release-skip-tests quick-release fails to generate release tarball

### ISSUE THREAD

**Issue by linearregression** [kubernetes/kubernetes#35986]
If I  to to do a local dev release build, I don't really salt or hashed the binary like that. The following command will give error. Build log also below

sudo make release-skip-tests quick-release
lots of files missing under _output/release-stage/salt/kubernetes/saltbase/salt/

+++ [1101 13:58:55] Syncing out of container
+++ [1101 13:58:58] Building tarball: salt
+++ [1101 13:58:58] Building tarball: manifests
+++ [1101 13:58:58] Building tarball: src
+++ [1101 13:58:58] Starting tarball: client linux-amd64
+++ [1101 13:58:58] Waiting on tarballs
+++ [1101 13:58:58] Building tarball: server linux-amd64
find: ‘/opt/opensource/worksplace/go/src/github.com/kubernetes/kubernetes/_output/release-stage/salt/kubernetes/saltbase/salt/kube-addons/calico-policy-controller’: No such file or directory
find: ‘/opt/opensource/worksplace/go/src/github.com/kubernetes/kubernetes/_output/release-stage/salt/kubernetes/saltbase/salt/kube-addons/cluster-loadbalancing’: No such file or directory
!!! [1101 13:59:06] client tarball creation failed
+++ [1101 13:59:08] Starting Docker build for image: kube-apiserver
+++ [1101 13:59:08] Starting Docker build for image: kube-controller-manager
+++ [1101 13:59:08] Starting Docker build for image: kube-scheduler
+++ [1101 13:59:08] Starting Docker build for image: kube-proxy
+++ [1101 13:59:38] Deleting docker image gcr.io/google_containers/kube-controller-manager:d72909c11497279571152dc66ad8731c
Untagged: gcr.io/google_containers/kube-controller-manager:d72909c11497279571152dc66ad8731c
Deleted: sha256:537dac71aa057d1b2ecf7b175e9e07f1e6c06e63159d8e0550e9b955d66235d9
Deleted: sha256:eda0c2d27cba477b8de2b7258dbeea0065bb219b622a0d80aae7df37c3424da7
+++ [1101 13:59:42] Deleting docker image gcr.io/google_containers/kube-scheduler:b69b91ef1f0f8c89db8a7ba2bfb07cad
Untagged: gcr.io/google_containers/kube-scheduler:b69b91ef1f0f8c89db8a7ba2bfb07cad
Deleted: sha256:9d801d440e208510ff9b6edda58d01c3ce600d426491c3d117a967449d8a2ad9
Deleted: sha256:2374db4e888e1c263b207afb4d7501cb5c75524499b0eda31e7f1efd7504ad44
+++ [1101 13:59:46] Deleting docker image gcr.io/google_containers/kube-proxy:c577f8dfa1ea8255d99725acb42cb2aa
Untagged: gcr.io/google_containers/kube-proxy:c577f8dfa1ea8255d99725acb42cb2aa
Deleted: sha256:4586ffb82ea9c9162bd2706dcd699ebccaf8d739784ae6c434c73c0c7b7ef9d2
Deleted: sha256:20d909cd1f311f93cfd06db85a2bfe2af6221a925edc8d7854878049a486312d
+++ [1101 13:59:51] Deleting docker image gcr.io/google_containers/kube-apiserver:a8865badf65c5640f58d6c6445cdc36c
Untagged: gcr.io/google_containers/kube-apiserver:a8865badf65c5640f58d6c6445cdc36c
Deleted: sha256:4d13af4ed74c145328cda30fb995d4e0d1db3f8bde2e33ce6ea16f78dac53ea8
Deleted: sha256:a0d5d75fe17e91e1fc9b113bd6497943de7c135c9157188f4f6323bc532c47a4
+++ [1101 13:59:54] Docker builds done
!!! [1101 14:00:55] previous tarball phase failed

**Comment by caseydavenport** [comment]
@linearregression are you still seeing this on the latest master?

Otherwise, I think this can be closed. 

/assign

**Comment by xenophenes** [comment]
This same issue is happening with the latest release. Any ideas?
