### ISSUE TITLE
Federation Cloud DNS Provider fails to update DNS when running multizone clusters

### ISSUE THREAD

**Issue by saturnism** [kubernetes/kubernetes#35997]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report
**Kubernetes version** (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:19:49Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.9", GitCommit:"ee10669e21109f86c21e8f7ceb1187d7910fe120", GitTreeState:"clean", BuildDate:"2016-10-20T20:37:18Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): Local: El Capitan, Remote: GCI
- **Kernel** (e.g. `uname -a`): Local: Darwin ... 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64
- **Install tools**: gcloud
- **Others**: n/a

**What happened**:
Provisioned 3 clusters each in different regions (us-central1, asia-east1, europe-west1). Each cluster is in 2 zones (w/ gcloud --zone... --additional-zones...) 

Provisioned Federation API Server and Controller (1.4.4) based on https://github.com/kelseyhightower/kubernetes-cluster-federation

Verified clusters were ready.

Provisioned federated service & deployed backends into each of the cluster. Verified the federated services were created, and all of the regional LB were created, and verified all the LB IPs were working w/ direct requests.

DNS provider updated DNS w/ most of the service/zone CNAME records. But A records did not complete.

Further investigation for the log points to multiple entries in rrdata w/ the same IP due to the multi-zone deployment:

I1029 19:24:24.506359       1 dns.go:240] Have recordset <(clouddns) "buttonmasher-frontend.default.hybrid-cloud-rocks.svc.us-central1-b.us-central1.hybrid-cloud-rocks.com." type=CNAME rrdatas=["buttonmasher-frontend.default.hybrid-cloud-rocks.svc.us-central1.hybrid-cloud-rocks.com."] ttl=180>. Need recordset <(clouddns) "buttonmasher-frontend.default.hybrid-cloud-rocks.svc.us-central1-b.us-central1.hybrid-cloud-rocks.com." type=A rrdatas=["130.211.203.196" "130.211.203.196"] ttl=180>
I1029 19:24:24.506520       1 dns.go:248] Existing recordset <(clouddns) "buttonmasher-frontend.default.hybrid-cloud-rocks.svc.us-central1-b.us-central1.hybrid-cloud-rocks.com." type=CNAME rrdatas=["buttonmasher-frontend.default.hybrid-cloud-rocks.svc.us-central1.hybrid-cloud-rocks.com."] ttl=180> is not equivalent to needed recordset <(clouddns) "buttonmasher-frontend.default.hybrid-cloud-rocks.svc.us-central1-b.us-central1.hybrid-cloud-rocks.com." type=A rrdatas=["130.211.203.196" "130.211.203.196"] ttl=180>, removing existing and adding needed.

After creating the clusters w/ only one zone, the DNS provider worked properly.

**What you expected to happen**:
Cloud DNS Provider should update the DNS record properly w/ multi-zone clusters.

**How to reproduce it** (as minimally and precisely as possible):
1. Provision 3 x multi-zone clusters
2. Provision Federation API Server and Controller
3. Add clusters in to federation
4. Deploy federated service and backends

**Anything else do we need to know**:
Using GKE and Cloud DNS

**Comment by ankurcha** [comment]
Also hit this. Any workarounds?

**Comment by quinton-hoole** [comment]
@ankurcha Sorry, no direct workarounds available yet.  You could convert your multi-zone clusters into multiple single-zone clusters, and federate all of those.

**Comment by matt-potter** [comment]
FYI, although I'm sure you're aware - also affects AWS multi AZ clusters (1.6.2)

**Comment by quinton-hoole** [comment]
This seems bad.  I'll try to take a look into it.  @kubernetes/sig-federation-bugs

**Comment by quinton-hoole** [comment]
Fixed by #45492
