### ISSUE TITLE
kubeadm docs first run notes

### ISSUE THREAD

**Issue by mellotron** [kubernetes/kubernetes#35996]
Hello,

Brand new to kubernetes, I read through: http://kubernetes.io/docs/getting-started-guides/kubeadm/

It's not clear what either CNI stands for nor what/where add-on.yaml can be obtained from.

"Anyway, ARM had some issues when" - the Anyway here is redundant and makes the docs sound informal.

"And obviously replace ARCH=amd64" - I don't think words like "obviously" should be used in docs as it belittles the user.

This guide should provide a link to http://kubernetes.io/docs/user-guide/ui/ to get a first time user up and running with the dashboard.

Thanks,

**Comment by luxas** [comment]
Thanks @mellotron these docs fixes have been merged a long time ago thanks to your suggestions :+1: 
We just forgot to close the issue.
