### ISSUE TITLE
kubectl edit ThirdPartyResource object fails with "invalid character"

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes/kubernetes#35993]
**What keywords did you search in Kubernetes issues before filing this one?**

kubectl edit invalid character
kubectl edit thirdpartyresource

---

**Is this a BUG REPORT or FEATURE REQUEST?**
BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3+coreos.0", GitCommit:"7819c84f25e8c661321ee80d6b9fa5f4ff06676f", GitTreeState:"clean", BuildDate:"2016-10-17T21:19:17Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:

`kubectl edit` of a thirdPartyResource fails then re-enters the editor and adds the following comment:

```
# The edited file had a syntax error: unable to decode "edited-file": invalid character '#' looking for beginning of value
```

**What you expected to happen**:

`kubectl edit` to successfully edit the ThirdPartResource object.

**How to reproduce it** (as minimally and precisely as possible):

tpr.yaml
```
metadata:
  name: foo-obj.a.example.com
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "foo"
versions:
- name: v1
```

obj.yaml
```
metadata:
  name: foo
apiVersion: a.example.com/v1
kind: FooObj
someData: foo
```

```
$ kubectl create -f tpr.yaml
$ kubectl create -f obj.yaml
$ kubectl edit fooObj/foo
```

**Comment by paultiplady** [comment]
I am also seeing this issue on GKE, with the following k8s versions:

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:19:49Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by pwittrock** [comment]
@AdoHe Is this something you could take a look at?

**Comment by AdoHe** [comment]
@pwittrock IIRC, I have already fixed this on my local, I need to get it back.

**Comment by AdoHe** [comment]
I looked into this issue again, and just found other problem when test against master branch.
```
the provided version "a.example.com/v1" has no relevant versions: group a.example.com has not been registered
no matches for a.example.com/, Kind=FooObj
```
I believe there are some problem of TPR discovery.

**Comment by pires** [comment]
I can confirm this issue as well.

**Comment by AdoHe** [comment]
@pires what error you get? and also what's your kubernetes version?

**Comment by pires** [comment]
Environment: `kubectl` and Kubernetes **v1.4.6**

I create a TPR that exposes an object `XyzCluster` and am able to create/delete it. But when I try to edit through `kubectl edit xyzcluster <name>`, change some data and save it, the editor pops up again with the same error message @aaronlevy mentioned:
```
# The edited file had a syntax error: unable to decode "edited-file": invalid character '#' looking for beginning of value
```

**Comment by pires** [comment]
@AdoHe any updates on this?

**Comment by liggitt** [comment]
fixed in https://github.com/kubernetes/kubernetes/pull/41304
