### ISSUE TITLE
Switch kubectl apply to use info.VersionedObject

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#35999]
While working on `kubectl apply` I wanted to switch to using `info.VersionedObject` always for the actual patch operation, see https://github.com/kubernetes/kubernetes/pull/35688. Unfortunately, `info.VersionedObject` is not set properly when working with list of objects. It works fine with single object, though. Temporary fix is to encode every object in apply's code, and that's what I did in #35688 for now, we need to fix apply permanently to use `info.VersionedObject`.

**Comment by bgrant0607** [comment]
cc @ymqytw @pwittrock

**Comment by ymqytw** [comment]
@soltysh I have a similar issue when working on `kubectl create --edit`. Opened an issue #36968 for it.

**Comment by pwittrock** [comment]
@soltysh Will this fix the dropping of fields when using skewed client / server versions?

**Comment by soltysh** [comment]
@pwittrock not sure what you're talking about

**Comment by liggitt** [comment]
did #40260 resolve this?

**Comment by soltysh** [comment]
Yes, closing.
