### ISSUE TITLE
Move internal API to folder internalversion/

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#35992]
Currently the internal API lives in the root folder of the API group, e.g., pkg/apis/extensions/. We should move them (types.go, deepcopy.go, register.go, helpers.go etc.) to pkg/apis/extensions/internalversion. The benefits are:
* It is more aligned to the layout of the generated [clientset](https://github.com/kubernetes/kubernetes/tree/master/pkg/client/clientset_generated/internalclientset/typed/core/internalversion) and [listers](https://github.com/kubernetes/kubernetes/tree/master/pkg/client/listers/policy/internalversion).
* Easier to use tools like import-boss or bazel to prevent accidental import of internal APIs.

@kubernetes/sig-api-machinery @deads2k

**Comment by deads2k** [comment]
I think this sense for consistency.  Other than being the hub and having a fixed version name, I don't think these should be special.

**Comment by smarterclayton** [comment]
I agree we should do this.

**Comment by lavalamp** [comment]
+1
