### ISSUE TITLE
Old kubectl tries to register new API version as third party resource and fail 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#36007]
Follow up #35791

When older kubectl sees a new API version it doesn't recognize (such as apps.v1beta1), it'll think it's a third party source (TPR) and tries to register it, and then will fail. 

It happens in TPR discovery code. It's trying to identify TPR versions and hacks them into the list of registered APIs:
https://github.com/kubernetes/kubernetes/blob/v1.5.0-alpha.2/pkg/kubectl/cmd/util/factory.go#L341

@kubernetes/kubectl @pwittrock @ymqytw @liggitt @deads2k @caesarxuchao

**Comment by dims** [comment]
@janetkuo @ymqytw This needs to be triaged as a release-blocker or not for 1.5

**Comment by deads2k** [comment]
> @janetkuo @ymqytw This needs to be triaged as a release-blocker or not for 1.5

Opened https://github.com/kubernetes/kubernetes/pull/36898 for evaluation.  Its definitely broken, but I think we could tolerate having it in 1.5.1.

**Comment by pwittrock** [comment]
client / server skewed kubectl is generally broken right now

**Comment by dims** [comment]
@deads2k @pwittrock : let's treat this as release-blocker until we agree otherwise

**Comment by deads2k** [comment]
> @deads2k @pwittrock : let's treat this as release-blocker until we agree otherwise

Ok, I'll queue the fix (it's already lgtm'ed)
