### ISSUE TITLE
Wrong relative paths use din makefile for hypercube after m make release-skip-tests quick-release

### ISSUE THREAD

**Issue by linearregression** [kubernetes/kubernetes#36015]
after  make release-skip-tests quick-release
it generates a _output folder but the makefile for hypercube
go/src/github.com/kubernetes/kubernetes/_output/release-stage/full/kubernetes/cluster/images/hyperkube

It si trying to find the salt folder using relative path which is wrong

found fodler under:
/opt/opensource/worksplace/go/src/github.com/kubernetes/kubernetes/_output/release-stage/salt

instead of 
opt/opensource/worksplace/go/src/github.com/kubernetes/kubernetes/_output/release-stage/full/kubernetes/cluster/images/hyperkube/ ../../saltbase/salt/generate-cert/make-ca-cert.sh

Possibel to detect and use Variables instead of relative paths?

echo 'current dir:/opt/opensource/worksplace/go/src/github.com/kubernetes/kubernetes/_output/release-stage/full/kubernetes/cluster/images/hyperkube`'
current dir:/opt/opensource/worksplace/go/src/github.com/kubernetes/kubernetes/_output/release-stage/full/kubernetes/cluster/images/hyperkube`
cp -r ./* /tmp/tmp.NHtpmlWjvC
mkdir -p /tmp/tmp.NHtpmlWjvC/cni-bin /tmp/tmp.NHtpmlWjvC/addons /tmp/tmp.NHtpmlWjvC/addons/singlenode /tmp/tmp.NHtpmlWjvC/addons/multinode
cp ../../saltbase/salt/generate-cert/make-ca-cert.sh /tmp/tmp.NHtpmlWjvC
cp: cannot stat ‘../../saltbase/salt/generate-cert/make-ca-cert.sh’: No such file or directory

**Comment by spiffxp** [comment]
/close
I believe this has since been fixed.  Please /reopen if I am wrong.
