### ISSUE TITLE
Changing kube-apiserver authorization-mode to RBAC puts nodes in NotReady state

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kubernetes#36029]
**Kubernetes Version: 1.4.3**
**Cloud: AWS**
**Deploy: Kops**

Hi, I'm trying to setup an authorization scheme using OpenID + RBAC but when I turn on RBAC all nodes are put in NotReady state, I'm putting the following arguments to my apiserver pod:

`--authorization-mode=RBAC --authorization-rbac-super-user=kubecfg
`

Any hints? Maybe RBAC defaults to denying kubelet of the minion nodes?

@justinsb Do you think that this can be related to Kops somehow?

**Comment by justinsb** [comment]
I had to add permissions for `kubelet`: https://github.com/justinsb/kops/commit/6d999daab17c2d787a64dc0864aab725f8580e48

**Comment by justinsb** [comment]
(I don't think this is anything to do with kops.  I don't think :-) )

**Comment by felipejfc** [comment]
Thanks @justinsb setting the roles as you did for services, kubelet and kube-proxy did the trick!!!
