### ISSUE TITLE
Collect kube-docker-monitor logs in e2e

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#36027]
We used to collect logs from the docker healthchecker on cvm (supervisord logs here: http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/kubernetes-e2e-gce/26005/artifacts/jenkins-e2e-minion-group-fh7q/). We should do the same on gci (https://github.com/kubernetes/kubernetes/issues/34104#issuecomment-257737502).

**Comment by jeremyKisner** [comment]
Is this is still an issue that needs to be open?
