### ISSUE TITLE
Feature Request: 'kubeadm leave'

### ISSUE THREAD

**Issue by tonyclam** [kubernetes/kubernetes#36026]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Features Request

**Kubernetes version** (use `kubectl version`):
[root@localhost ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.0.1877+3f4a66f3d6892b-dirty", GitCommit:"3f4a66f3d6892b8d8831a8a60b91fd1afbefee4d", GitTreeState:"dirty", BuildDate:"2016-10-31T20:47:46Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

[root@localhost ~]# kubeadm version
kubeadm version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.0.1534+cf7301f16c0363-dirty", GitCommit:"cf7301f16c036363c4fdcb5d4d0c867720214598", GitTreeState:"dirty", BuildDate:"2016-09-27T18:10:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:x89_64
- **OS** (e.g. from /etc/os-release):Ubuntu 16.04
- **Kernel** (e.g. `uname -a`): Linux kubenode01 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:kubeadm
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#10
