### ISSUE TITLE
Leverage the type system to avoid Static pod / mirror pod translation issues.

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#36031]
We have a lot of calls to `TranslatePodUID` through our codebase, and it can be difficult to keep track of where it's needed. We should leverage the type system with an internal type for PodUIDs that have been resolved to a static pod UID so it's clear when the translation is or is not needed.

/cc @yujuhong

**Comment by yujuhong** [comment]
Thanks for filing the issue!

**Comment by ebbeelsborg** [comment]
@timstclair @yujuhong I'm interested in working on this if help is still wanted. If so, let me know how you'd like me to proceed. Thanks.

**Comment by timstclair** [comment]
I think I would approach this by adding 2 new types:

```
type ResolvedPodUID types.UID
type MirrorPodUID types.UID
```

With the original `types.UID` being the type used by the API / unresolved. Any time we resolve (through `TranslatePodUID`) the UID, it should be converted to `ResolvedPodUID`. If we're explicitly operating on the mirror pod, `MirrorPodUID` should be used.

The bulk of this change will be sifting through the code base to figure out which UID should be used where, and changing the types as appropriate. Anytime one type is cast to another, there should be a comment explaining why we know it's safe.

Let me know if you have questions, or would like to propose an alternative.

**Comment by ebbeelsborg** [comment]
@timstclair I gave that approach a try with the following strategy:
1. Add the two new types.
2. Change the return type of TranslatePodUID to ResolvedPodUID and make consequential changes.
3. Take MirrorPodUID into use.
4. Possibly use the new types in places where the comments or code already suggests it.

I've pushed steps 1 and 2 to feature branch 36031 in my [fork](https://github.com/blackwoodseven/kubernetes).

Could you please take a look and comment on whether you think I'm going in the right direction?

In the meantime I'll continue with the steps outlined above.

**Comment by timstclair** [comment]
@ebbeelsborg Sounds good. Can you open a pull request with your changes? It's ok if you're still working on it, just put `[WIP]` (work in progress) in the title, to indicate it's not ready for a full review. Thanks!
