### ISSUE TITLE
StatefulSet docs must warn against setting terminationGracePeriodSeconds=0 in pod template

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#36034]
As of now, even the [petset example](http://kubernetes.io/docs/user-guide/petset/#example-petset) sets terminationGracePeriodSeconds to 0.
We should document clearly the conditions required to ensure that there is only one pet with a certain identity.

1. Kubelet version >= 1.1.0.
2. Master version >= 1.5.0
3. terminationGracePeriodSeconds != 0

cc @smarterclayton @erictune @kubernetes/sig-apps

**Comment by smarterclayton** [comment]
We should definitely remove that from the example.  No example ever should set terminationGracePeriodSeconds unless it's demonstrating terminationGracePeriodSeconds.

**Comment by dims** [comment]
@foxish @smarterclayton This needs to be triaged as a release-blocker or not for 1.5

**Comment by smarterclayton** [comment]
Doc blocker because it causes data loss if someone copies it.

**Comment by foxish** [comment]
The e2e examples have been fixed by https://github.com/kubernetes/kubernetes/pull/36910.

**Comment by dims** [comment]
@saad-ali : do we have a "doc blocker" tag? let me throw in a "non-release-blocker" as this does not stop us from getting the release out as such

**Comment by foxish** [comment]
Added a warning against `terminationGracePeriod` setting to 0 in https://github.com/kubernetes/kubernetes.github.io/pull/1731

**Comment by foxish** [comment]
@kow3ns @enisoc We should probably warn against this in the SS concept doc as well?

**Comment by kow3ns** [comment]
I think we should remove it from the examples, but I don't see a clear reason to add it to the StatefulSet concept. imo, terminationGracePeriod should be dealt with in the Pod and Pod lifecycle documentation because it is not specific to StatefulSet.

**Comment by enisoc** [comment]
I think it makes sense to add a warning to the StatefulSet concept doc. StatefulSet promises to ensure at most one instance of a given ordinal. It could silently fail to deliver on that promise if you set the grace period to zero. That interaction is too specific to make sense in Pod docs.

**Comment by foxish** [comment]
I agree. Although it is not specific to StatefulSet, setting `terminationGracePeriodSeconds=0` is especially harmful when using them, as opposed to using other controllers.
Folks seem to be [using it alongside PetSets](https://github.com/kubernetes/kubernetes/issues/35269) probably due to old examples which had that value set. Maybe even pointing this out in the upgrade guide would be useful. @janetkuo
