### ISSUE TITLE
Dashboard and SkyDNS error

### ISSUE THREAD

**Issue by chowyu08** [kubernetes/kubernetes#36046]
**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): ubuntu14.04
- **Kernel** (e.g. `uname -a`): Linux cloud2 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:   KUBERNETES_PROVIDER=ubuntu ./kube-up.sh
- **Others**:  deploy dns by KUBERNETES_PROVIDER=ubuntu ./deployAddons.sh

**What happened**:
pods are all right
![image](https://cloud.githubusercontent.com/assets/16483518/19920882/3bcbfaea-a116-11e6-8e9b-52e53223dd04.png)
kubectl cluster-info dump
![image](https://cloud.githubusercontent.com/assets/16483518/19920907/5ea2439e-a116-11e6-835d-3280de0594eb.png)
access the dashboard occur an error:
![image](https://cloud.githubusercontent.com/assets/16483518/19920944/8a4c6826-a116-11e6-8b87-0a45a79c904f.png)

kubectl logs kube-dns-v20-l0qnn dnsmasq --namespace=kube-system
![image](https://cloud.githubusercontent.com/assets/16483518/19920972/b459c1b8-a116-11e6-84f8-f4c70475494e.png)

kubectl logs kube-dns-v20-l0qnn kubedns --namespace=kube-system
![image](https://cloud.githubusercontent.com/assets/16483518/19920994/ce1d09e8-a116-11e6-9835-5d9ccd0542c8.png)

kubectl logs kube-dns-v20-l0qnn healthz --namespace=kube-system
![image](https://cloud.githubusercontent.com/assets/16483518/19921021/e618b196-a116-11e6-9598-ff24ff2d5e3a.png)
nil

kubectl logs kubernetes-dashboard-v1.4.0-35d2t --namespace=kube-system
![image](https://cloud.githubusercontent.com/assets/16483518/19921050/1a6cdb3e-a117-11e6-94bb-6956c7d66877.png)

why?

**Comment by bowei** [comment]
this does not look like a DNS issue as the error you are getting is "no route to route"

**Comment by bowei** [comment]
please reopen if you are still hitting this issue
