### ISSUE TITLE
[k8s.io] e2e tests are failing because of API server's 500's

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#36054]
I'll try to link all relevant automatically create issues to this one. The error we're seeing is:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:134
Oct 25 03:49:06.875: Couldn't delete ns: "e2e-tests-sched-pred-cvi6c": an error on the server ("Internal Server Error: \"/apis/extensions/v1beta1/namespaces/e2e-tests-sched-pred-cvi6c/jobs\"") has prevented the request from succeeding (get jobs.extensions) (&errors.StatusError{ErrStatus:unversioned.Status{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ListMeta:unversioned.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Failure", Message:"an error on the server (\"Internal Server Error: \\\"/apis/extensions/v1beta1/namespaces/e2e-tests-sched-pred-cvi6c/jobs\\\"\") has prevented the request from succeeding (get jobs.extensions)", Reason:"InternalError", Details:(*unversioned.StatusDetails)(0xc820b4bb80), Code:500}})
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:338
```

Most of failures are P2, are they happened only once. This issue is P0, as if all those failures were instances of this problem. Most common problem is during namespace deletion, but in HPA tests there are other failures as well.

cc @smarterclayton @wojtek-t @lavalamp @caesarxuchao

**Comment by wojtek-t** [comment]
All of these are GKE failures. This seems to be related. @cjcullen

**Comment by roberthbailey** [comment]
Do we know what is causing the internal error to be returned? Do we have master logs that show more info (e.g. a stack trace)?

**Comment by gmarek** [comment]
I don't know. They're probably in BigQuery.

**Comment by calebamiles** [comment]
Any updates on this issue @cjcullen @roberthbailey? Should closing out this issue be a release blocker?

**cc** @saad-ali, @gmarek, @wojtek-t

**Comment by calebamiles** [comment]
@cjcullen, @roberthbailey all issues must be labeled either release blocker or non release blocking by end of day 18 November 2016 PST. If you are not the correct owner please identify the correct owner and add them to this thread for assignment.

**cc: @kubernetes/goog-gke, @saad-ali. @dims**

**Comment by cjcullen** [comment]
Let's assume this is still flaky, and mark this as a release-blocker for now.

**Comment by calebamiles** [comment]
@cjcullen, @roberthbailey could you please provide a status update on this issue by 1p PST 23 November 2016. Thanks!

**cc: @saad-ali, @dims, @kubernetes/goog-gke**

**Comment by saad-ali** [comment]
> @cjcullen, @roberthbailey could you please provide a status update on this issue by 1p PST 23 November 2016. Thanks!

Ping @cjcullen, @roberthbailey  any updates on this issue. Is it still considered a blocker for the 1.5 release?

**Comment by saad-ali** [comment]
> @wojtek-t commented 13 hours ago
> Isn't it fixed?

@gmarek Could you please verify, if so, please close this issue.

**Comment by calebamiles** [comment]
@saad-ali, all the failures in the linked test suite seem to be network problems, timeouts, and or test pollution. It's probably ok to close this. Thoughts @wojtek-t, @gmarek? Please try and update this issue by 1PM PST 30 November 2016 if we should keep this issue open. Thanks!

**cc: @dims**

**Comment by gmarek** [comment]
Last failure caused by 500 that I saw was 3 days ago, so I'd say it's not fixed. Not that it's only from failures I got assigned to, so I guess there are more examples out there.

**Comment by dims** [comment]
I don't see how we can make any progress here, we don't have a specific list of failures or jobs that needs to be looked at. So this cannot be a release-blocker

**Comment by gmarek** [comment]
This is exactly the reason why this needs to be addressed - it causes failures in many different suites and because in any single one it happens rarely, no one is looking into it, even though on higher level it's pretty common failure reason.

**Comment by dims** [comment]
Ack @gmarek

**Comment by gmarek** [comment]
This doesn't mean that it should be a release-blocker, only that it should be a P0:)

**Comment by dims** [comment]
good point @gmarek

**Comment by dims** [comment]
@gmarek @cjcullen Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by gmarek** [comment]
Yes

**Comment by calebamiles** [comment]
This issue has received no updates in 2017. Closing.

**cc: @ethernetdan, @kubernetes/release-team**

**Comment by gmarek** [comment]
@calebamiles did you verify that it doesn't happen any more?

It's not an auto-filed issue, so if no one adds anything by hand there won't be any updates. The current approach makes me not care about filing relevant issue with root causes anymore.
