### ISSUE TITLE
Generate documentation for published releases.

### ISSUE THREAD

**Issue by kad** [kubernetes/kubernetes#36059]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): documentation, yaml, hack/generate-docs

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.4.5

**Environment**:
- **Cloud provider or hardware configuration**: local install
- **OS** (e.g. from /etc/os-release): CentOS 7
- **Kernel** (e.g. `uname -a`):3.10.0-327.28.3.el7.x86_64
- **Install tools**: manual
- **Others**:

**What happened**:
Download 1.4.5 release tarball from Github:
https://github.com/kubernetes/kubernetes/releases/download/v1.4.5/kubernetes.tar.gz
Unpack it and look at documentation folder docs/yaml/kubectl/...
Inside that folder user can see bunch of yaml files that have content:
```
This file is autogenerated, but we've stopped checking such files into the
repository to reduce the need for rebases. Please run hack/generate-docs.sh to
populate this file.
```

**What you expected to happen**:
In my opinion, those placeholders should be replaced with real generated documentation at the time of release. So, somewhere in release scripts call to generate documentation is missing.

**How to reproduce it** (as minimally and precisely as possible):
```console
$ wget https://github.com/kubernetes/kubernetes/releases/download/v1.4.5/kubernetes.tar.gz
$ tar zxf kubernetes.tar.gz
$ cat kubernetes/docs/yaml/kubectl/kubectl_api-versions.yaml
```

**Anything else do we need to know**:

**Comment by luxas** [comment]
cc @thockin @jessfraz

**Comment by kad** [comment]
it would be good if upcoming 1.5 release will be shipped with generated documentation instead of placeholders. Issue still present in current 1.5.0-beta.2 archive.
cc @saad-ali

**Comment by saad-ali** [comment]
@kubernetes/release-maintainers is this expected behavior? Is it something we can fix for the 1.5 release (with <1 week left)?

**Comment by kad** [comment]
anyone can point me to scripts that are used to generate official release ? maybe I'll look myself on it ?

**Comment by david-mcmahon** [comment]
I believe https://github.com/kubernetes/release/pull/176 should have replaced versionize-docs with generate-docs.
