### ISSUE TITLE
Link to docs from API field descriptions

### ISSUE THREAD

**Issue by abonas** [kubernetes/kubernetes#3606]
The api in v2 has this comment:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta2/types.go

"image pull policy: one of PullAlways, PullNever, PullIfNotPresent; defaults to PullAlways if :latest tag is specified, or PullIfNotPresent otherwise"

this was removed in the v3 types.go file

There's a partial explanation here, but it doesn't specify all possible values:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/images.md

So a documentation for all possible values and the default value is needed.

Also, when working with v1beta1 api, when creating a pod with guestbook examples that don't specify the image pull policy, that property is returned with empty value  "imagePullPolicy": "", shouldn't a default value be populated?

**Comment by thockin** [comment]
Documentation seems like a problem.

Defaulting will be fixed O(soon)

**Comment by abonas** [comment]
@thockin  why documentation is a problem?

**Comment by thockin** [comment]
I meant that the absence of documentation is a problem in v1beta3/types.go, but this is a known issue (I filed #3628)

**Comment by abonas** [comment]
@thockin why is this issue closed - was the problem resolved in code? if yes, why the PR is not linked here?

**Comment by thockin** [comment]
I closed this because #3628 is an umbrella that includes the documentation issue in v1beta3 and the defaulting issue is covered by #1502.  Unless I am missing something, this issue is a dup (a double dup!).  Did I miss something?

**Comment by abonas** [comment]
@thockin , #1502 is not a pull request, it's a design discussion from which it's unclear when and how it will be resolved. From my point of view as a client of the api, getting an empty property is a bug. clients shouldn't populate properties after GET  and guess what should be there.   If the other issue is differently solved, and this one is closed, it is not resolving this issue.

**Comment by bgrant0607** [comment]
The defaulting PR was merged yesterday. Re-opened just for documentation.

**Comment by thockin** [comment]
If this is just open for documentation, how does #3628 not cover this?

**Comment by bgrant0607** [comment]
IMO, the bigger issue is that our docs are not discoverable. There is some documentation in images.md re. pull policy, but how would anyone find it? I thought I filed an issue that we should link to our docs from the descriptions, but I can't find one, so maybe I'll repurpose this for that.

**Comment by proppy** [comment]
It would be nice to also link the other way around, https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/images.md#preloading-images mention the imagePullPolicy, it should links to the API docs with all the possible value.

**Comment by vmarmol** [comment]
Assigning to @vishh who is working on #3628 which should tackle this one as well.

**Comment by bgrant0607** [comment]
Partial dupe of #3059

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers

**Comment by ahmetb** [comment]
Although I'm not clear what this issue particularly requests, many API fields now link to kubernetes.io for relevant concepts/docs. Take a look at `kubectl explain` for various fields/resources and you'll see many links to kubernetes.io.

I'm not closing as I am not certain if this is what's requested.

**Comment by thockin** [comment]
@ahmetb The point was to make API docs richer by including relevant links.  Up to you and docs-people when this is "done"

**Comment by chenopis** [comment]
This should be re-opened in the k8s.io repo if it's still a problem.
