### ISSUE TITLE
codegen should prefer to write one autogenerated file per package with a constant name

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#36082]
This is up for debate but having one file with a constant name e.g. client.go per package makes it much easier to declare expected output for codegen phases which is required to construct a correct build dependency graph. Right now, the number and name of generated files are often dependent on the number and names of types in the input.

These are fairly easy changes to make so if there isn't objection to this, I'm happy to move generators over to this style.

cc @kubernetes/sig-api-machinery

**Comment by deads2k** [comment]
How would handle the `*Expansion` interfaces and generated files?

**Comment by mbohlool** [comment]
For OpenAPI Specs, I've generated one file for the whole project because it
is faster to compile (15% faster if I recall correctly). At this point it
can take some time to change it back because we customized make rules for
it. I suggest we leave that one alone.


Mehdy Bohlool |  Software Engineer |  mehdy@google.com |  mbohlool@github
<https://github.com/mbohlool>

**Comment by smarterclayton** [comment]
Doesn't that significantly complicate generation to properly handle merging whole files (including imports which may have different local names)?

Why not always generate a file for a package, even if empty?

**Comment by mbohlool** [comment]
The only reason was faster compile and release time (single file added 3.5% more compilation time and almost the same to "make quick-release", multiple files added 7% compilation time, and 25% make quick-release time, more information [at the PR comment here](https://github.com/kubernetes/kubernetes/pull/31468#issuecomment-246065961)). We did not have any merging issues yet. It was a little more complicated to write generating code, but not that significant as Daniel's library toke care of renaming imports, etc.

**Comment by smarterclayton** [comment]
What if I only want to include some of the api packages that live in the
core repo?  We are moving away from a world where all api groups are in a
single repo, so this seems like we're focusing on the wrong problem (andy's
work to try and make the tools more generic to use seems in direct conflict
to some of this merging).

**Comment by mbohlool** [comment]
In that case we can break OpenAPI definitions per package (or maybe repo but I don't see much benefit in breaking it at repo boundaries yet). It is not hard to do so. we can do that for 1.6.

**Comment by caesarxuchao** [comment]
Though readability is not import for most generated code, I think developers do read the clientset code. If we squeeze all the [core/v1 clients](https://github.com/kubernetes/kubernetes/tree/master/pkg/client/clientset_generated/release_1_5/typed/core/v1) in one file, it will be hard to read.

**Comment by gmarek** [comment]
@caesarxuchao - what other approach do you suggest? We need to have a predefined list of outputs if we're going to move to bazel.

cc @thockin

**Comment by deads2k** [comment]
> How would you handle the *Expansion interfaces?

Is there a resolution for this that doesn't involve multiple files?

**Comment by mikedanese** [comment]
@deads2k Multiple files with predictable outputs is fine. `expansions.go` and `client.go` would work. The nuisance is when the output can't be predicted without parsing the go package and examining type info.

**Comment by deads2k** [comment]
> @deads2k Multiple files with predictable outputs is fine. expansions.go and client.go would work. The nuisance is when the output can't be predicted without parsing the go package and examining type in

It's done as `<resource>_expansion.go` so that a user can later modify that file and new resources will prime new files.  If you have a single file, the generator is stuck trying to mutate a user modified file.

**Comment by caesarxuchao** [comment]
The directory structure of the generated clientset is also dynamic, i.e., if a user instructs to generate clients for another group/version, a new "group/version" folder will be added to the typed/ directory. Will bazel work in that case?

**Comment by gmarek** [comment]
Maybe client generator should generate BUILD files as well?

**Comment by caesarxuchao** [comment]
> Maybe client generator should generate BUILD files as well?

That could be the solution.

**Comment by mikedanese** [comment]
I don't think this is a huge issue. I can prototype a solution and see if you guys like it.

> It's done as <resource>_expansion.go so that a user can later modify that file and new resources will prime new files. If you have a single file, the generator is stuck trying to mutate a user modified file.

We can do `client.go`, `generated_expansion.go` and optionally a user managed `expansion.go`. To be clear all this is possible without an change, there's just a larger maintenance burden.

> Maybe client generator should generate BUILD files as well?

This won't work unless we generate BUILD files outside of bazel which defeats the purpose. BUILD files must be present at analyze time before codegen rules run.

> The directory structure of the generated clientset is also dynamic, i.e., if a user instructs to generate clients for another group/version, a new "group/version" folder will be added to the typed/ directory. Will bazel work in that case?

The structure is predictable from the API group package `pkg/apis`. What is not predictable right now is the specific files generated. That requires actually parsing go code. That's what I want to eliminate.

**Comment by lavalamp** [comment]
Really? Bazel has no provision for things that generate files?

**Comment by thockin** [comment]
Can bazel apply globs for this?

**Comment by bgrant0607** [comment]
@mikedanese Is there a reason why you didn't set the appropriate routing labels when you created this issue?

**Comment by mikedanese** [comment]
@lavalamp it does but it requires the outputs to be known at analyze, before generation rules run. We have to maintain a list of rule outputs. We can greatly lessen the burden of this maintenance if  the output names that are predicable.

@thockin no, the glob cannot be reified at analyze time. It only makes sense after the genrule has run.
