### ISSUE TITLE
Configuration validation not throwing error when invalid

### ISSUE THREAD

**Issue by morissette** [kubernetes/kubernetes#36081]
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.10", GitCommit:"c3e367ec9eae7338ac4e2a57f293634891319b7c", GitTreeState:"clean", BuildDate:"2016-10-31T21:25:43Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
NAME=Fedora
VERSION="22 (Twenty Two)"
ID=fedora
VERSION_ID=22
PRETTY_NAME="Fedora 22 (Twenty Two)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:22"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=22
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=22
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
VARIANT="Workstation Edition"
VARIANT_ID=workstation

Linux mori.mattharris.org 4.4.14-200.fc22.x86_64 #1 SMP Fri Jun 24 21:19:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

minikube version: v0.12.2

**What happened**:
Merged two configs together and ran kubectl create -f newmergedfile.yml, did not error on validation when missing --- between a service and a deployment

**What you expected to happen**:
to create the correct pieces and error on the invalid

**How to reproduce it** (as minimally and precisely as possible):
```apiVersion: v1
kind: Service
metadata: 
  name: kong-app
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      name: http
    - port: 8001
      targetPort: 8001
      name: admin
  selector:
    name: kong-app

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-app
spec:
  template:
    metadata:
      labels:
        name: kong-app
        tier: development
    spec:
      containers:
        - name: kong-app
          image: kong
          env:
            - name: KONG_DATABASE
              value: cassandra
            - name: KONG_CASSANDRA_CONTACT_POINTS
              value: kong-database
          ports:
            - containerPort: 8000
            - containerPort: 8001
            - containerPort: 7946
            - containerPort: 7946
              protocol: UDP

apiVersion: v1
kind: Service
metadata:
  name: kong-database
spec:
  type: NodePort
  ports:
    - port: 9042
      targetPort: 9042
      nodePort: 30042
  selector:
    name: kong-database

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-database
spec:
  template:
    metadata:
      labels:
        name: kong-database
        tier: development
    spec:
      containers:
        - name: kong-database
          image: cassandra:2.2
          ports:
            - containerPort: 9042
```

and run create

**Anything else do we need to know**:
nope

**Comment by ymqytw** [comment]
It seems that when we do [yaml.Unmarshal()](https://github.com/ghodss/yaml/blob/master/yaml.go#L80), the decoder will swallow part of the manifest when `---` is missing. We may need to fix the upstream issue in [go-yaml](http://gopkg.in/yaml.v2).
@bgrant0607 @ghodss I'm not sure if this is a known issue?

**Comment by ghodss** [comment]
How would you detect that it's missing? Would you throw an error on duplicate keys?

**Comment by pwittrock** [comment]
@janetkuo This looks related to the other issue around --- in config files.  Do you know if it is the same?

**Comment by janetkuo** [comment]
I don't think they the same. cc @AdoHe

**Comment by AdoHe** [comment]
@pwittrock IIUC, you mean this #33588, actually this has already been fixed, but this fix is not include in 1.4 release, I was supposed to create a cherry-pick, but just forget. :(

**Comment by AdoHe** [comment]
@morissette @ymqytw YAML decoder is just used to split one full YAML document from the config file, in you case after the first service definition split, kubectl will validate it, and it just failed, we will not continue to parse the config file, just return validation error.

**Comment by AdoHe** [comment]
@pwittrock @ymqytw what do you think whether we should allow continue parsing on validation error?

**Comment by pwittrock** [comment]
@AdoHe What is the error that is provided in this case?  This is definitely user error, so I am a little less concerned, but it would be nice to identify it.  We could probably identify the issue if there are 2 versions/kinds in a give block.  This would indicate a syntax error.  I am less concerned with this than I am about our non-user-error bugs.

**Comment by AdoHe** [comment]
@pwittrock error in this case is validation error, you can see [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource/visitor.go#L536)
