### ISSUE TITLE
Better messaging for missing storage binaries

### ISSUE THREAD

**Issue by rkouj** [kubernetes/kubernetes#36098]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
`kubectl version` 1.4  patch-release

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Generic error message for missing binaries on the host

**What you expected to happen**:
Error message stating : (Not finalized) "Mount failed: Unable to complete mount for volume `nfs-data-vol`. Binary required for mounting, '/sbin/mount.nfs', does not exist on host machine. Verify that your node machine has the binaries necessary for mounting this volume type."

**How to reproduce it** (as minimally and precisely as possible):
User creates a pod referencing an NFS volume. If the NFS binaries are not present on the host, a mount failed event is created with the following message :-

Sep 24 21:17:31.083: INFO: At 2016-09-24 21:11:05 -0700 PDT - event for write-pod-1mzyy: {kubelet e2e-test-vishnuk-minion-group-jo
4u} FailedMount: MountVolume.SetUp failed for volume "kubernetes.io/nfs/13fd01f0-82d6-11e6-959f-42010af00002-nfs-1nmbf" (spec.Name
: "nfs-1nmbf") pod "13fd01f0-82d6-11e6-959f-42010af00002" (UID: "13fd01f0-82d6-11e6-959f-42010af00002") with: mount failed: exit s
tatus 32
Mounting arguments: 10.180.0.10:/exports /var/lib/kubelet/pods/13fd01f0-82d6-11e6-959f-42010af00002/volumes/kubernetes.io~nfs/nfs-
1nmbf nfs []
Output: mount: wrong fs type, bad option, bad superblock on 10.180.0.10:/exports,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

**Comment by rkouj** [comment]
I am  working on this.
Current plan in @saad-ali 's words:

"We add a "CanMount()" interface to the API and callers who want to SetUp() should call that first."
This check is triggered before mount (if the containerized mounter override is not enabled) and generates a nice user understandable event when it fails.
Make this check gated by a flag to kubelet (default off, and enabled for GCE and GCI).
Gating is one way to ensure that we don't break environments that we are not aware of."

This change will be OFF by default on other platforms and ON on GCI.
A long time ago Kubernetes used to have a check for NFS binaries, but it was removed because it didn't work with components like recycling and assumed that all nodes would have the binaries named the same in the same location. See issue #12650 for more discussion.

**Comment by saad-ali** [comment]
CC @kubernetes/sig-storage

**Comment by rkouj** [comment]
https://github.com/kubernetes/kubernetes/pull/36280

**Comment by rkouj** [comment]
This has been merged to head and been cherry picked to 1.4 as well. Closing.
