### ISSUE TITLE
Make device open detection robust across volume plugins

### ISSUE THREAD

**Issue by rootfs** [kubernetes/kubernetes#36092]
This is a followup to https://github.com/kubernetes/kubernetes/pull/35434

Certain volume plugins, e.g. RBD, need to release devices during unmount. As a result, when `DeviceOpened` starts, the device path no longer exists. A temp fix is to check device path and call `DeviceOpened` only if the device path exists. 

This temp fix opens up to all volume plugins and is not atomic (i.e. the device path could still vanish between `PathIsDevice` and `DeviceOpened`)Creating this issue to track further investigation on plugin level exception to make device open detection more robust.

@kubernetes/sig-storage

**Comment by matchstick** [comment]
@kubernetes/sig-storage I think it's less about making device open detection more robust and more about having a clean architectural way to have volumes that are like RBD have their behaviour not be a special case. 

@childsb committed @jsafrane to picking this up. Not sure if @jsafrane knew :-) Assigning to him for now. Please ACK.

**Comment by jsafrane** [comment]
/assign @rootfs 
is it still an issue?
