### ISSUE TITLE
More MongoDB friendly core annotation and label names

### ISSUE THREAD

**Issue by sputnick** [kubernetes/kubernetes#36091]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request.

  - Describe *in detail* the feature/behavior/change you'd like to see.
Today Kubernetes allows and uses key names for labels and annotations that cannot be searched or indexed by MongoDB and perhaps some other key/value stores. Some of the core kubernetes annotations are like that, for example:
"kubernetes.io/cluster-service: true"

The problem is that neither "." or "/" is allowed for key names in Mongodb so even though it will happily store the value you cannot use it in a query. There are likely many use cases for using Mongodb on top of the Kubernetes API which would benefit from this feature/fix. I'll explain mine.

We are creating a UI/platform developed in nodejs on top of Kubernetes that is reactive to any changes in K8s (for Qstack dot com platform) and we are using MongoDB to allow us to quickly search and display related Kubernetes objects more in the line of Applications rather than individual API object (among other things). 

MongoDB gives us cached Collections that are always up to date because we "watch" the K8s API endpoints. This makes it possible to have a UI that is always up to date (pub-sub) and to do searches across different objects e.g. to discover Pod-Controller relationships (which is currently broken in K8s #33845) or to search by fields that are not allowed/indexed by the Restful API i.e. "<resource>.metadata.uid". 

I'm aware that this likely won't be implemented/changed easily as all K8s clusters depend on the current label/annotion key name pattern behaviour today but perhaps a query parameter could be added to Restful API that transforms/encodes the key names on the fly? 
e.g. "/api/v1/namespaces/default/pods/?encodekeys=true" would reply with the usual JSON but encodes keys with ". and /" into something that works for MongoDB.

**Kubernetes version** (use `kubectl version`):
All versions

**Environment**:
Any K8s environment, OS etc.

**Comment by smarterclayton** [comment]
I think in practice this is something that is going to have to be done on your end.
