### ISSUE TITLE
Does deleting --experimental flags break upgrades?

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#36105]
Scenario:
- User is using experimental flag in production (even though they mayyyybe shouldn't)
- We remove the experimental flag in the next version (or rename it, because it's not experimental anymore)
- Component rejects unknown flags (I think all components do this?). 
- The removal of the flag from the component breaks the upgrade, because the user still has it turned on in their provisioning.

Do we allow before/after flagsets to be configured for upgrades?

Do we have an officially documented policy that we hand users (runtime enforced too?) on how they should treat `--experimental` flags (e.g. *never* use them in production clusters).

It feels like we should take some time (next quarter?) to think through how we cycle experimental flags in and out of components. 

This also affects dynamic configuration of components, i.e. the Dynamic Kubelet Configuration feature.

/cc @vishh @davidopp @bgrant0607 @thockin @dchen1107

**Comment by bgrant0607** [comment]
@mtaufen Yes, we can't just delete flags.

**Comment by thockin** [comment]
We have a way to mark flags as deprecated and phase them out.

**Comment by mtaufen** [comment]
IIRC the whole point of calling a flag `--experimental-whatever` was that we would (hopefully) not have to carry it through a rolling deprecation process - e.g. for alpha-ish features that might be expected to change rapidly (including flag name changes/flag removal). I could be wrong about the intent of the terminology, but if I'm right it seems that this isn't especially well-communicated or enforced.

It looks like we'll have to follow the deprecation policy for anything named `--experimental` for the time being, just like we do for everything else. It might be easiest for us to design a way to work with temporary/experimental features into componentconfig (or whatever that turns into) as we move away from flags for the majority of config, rather than try to build a policy around flags.

**Comment by thockin** [comment]
We can change the behavior of --experimental-whatever, but that is
different than failing to launch the binary because we don't know that flag.

**Comment by mtaufen** [comment]
Closing as this really falls under fine-grained field versioning and related discussions: https://github.com/kubernetes/kubernetes/issues/34508
