### ISSUE TITLE
StatefulSet cannot scale down after network partition is healed sometimes

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#36107]
**What happened**:
https://github.com/kubernetes/kubernetes/issues/36035

**What you expected to happen**:
The statefulset should have scaled down to 0.
Instead, even after 10 minutes:

```
~/g/s/k/kubernetes (kenspr) kubectl.sh --namespace=e2e-tests-network-partition-837rt get statefulsets
NAME      DESIRED   CURRENT   AGE
pet       0         0         17m

~/g/s/k/kubernetes (kenspr) kubectl.sh --namespace=e2e-tests-network-partition-837rt get pods
NAME      READY     STATUS    RESTARTS   AGE
pet-0     1/1       Running   0          7m
pet-1     1/1       Running   0          17m
pet-2     1/1       Running   0          17m
```

**How to reproduce it** (as minimally and precisely as possible):
Run the `[StatefulSet] should not reschedule pets if there is a network partition [Slow] [Disruptive]` e2e test on a gce cluster running the latest and greatest kubernetes.

cc @smarterclayton @bprashanth @kubernetes/sig-apps

**Comment by bprashanth** [comment]
if the petset has replicas=0 it's not going to do anything

**Comment by foxish** [comment]
@bprashanth When I `kubectl edit` a running petset, and set its scale to 0, that seems to work and delete the pets, and we should have a functioning scaler. Am I misunderstanding something? 
I'm using the same teardown process for the e2e test I linked in the issue as the other tests ([test/e2e/petset.go#L601-L607](https://github.com/kubernetes/kubernetes/blob/5c3792a4db912547aa4c93c7acee25ebb431e1a4/test/e2e/petset.go#L601-L607)), but it times out sometimes after network partition.

**Comment by bprashanth** [comment]
yeah is scale in the petset controller noticing deletion timestamp? because the test code you showed doesn't care

**Comment by foxish** [comment]
@bprashanth As I mentioned yesterday, it isn't even issuing a delete request even after 10 minutes, because the pods continue to be "running". I'll check the controller manager logs today. I suspect it might be the backoff in the rate limited work-queue.

**Comment by bprashanth** [comment]
Hmm, the AGE fields on your pets don't make sense if it isn't even issuing a delete?

**Comment by foxish** [comment]
In the output I pasted above, at the 7 minute mark, it created the new replacement pet-0, after the network partition was healed. Then tried to scale down the StatefulSet and waited 10 minutes for the pods to disappear.

**Comment by bprashanth** [comment]
I see a bunch of different failures modes on the bug:
1. Nov  3 08:58:44.475: Failed waiting for pods to enter running: timed out waiting for the condition
2.     Failed to scale statefulset to 0 in 10m0s. Remaining pods: []
3. Nov  3 08:11:30.728: Unexpected error: <nil>

Basically 3 translates to 
```
Nov  3 08:12:00.866: INFO: ssh jenkins@104.154.201.240:22: exit code: 1
Nov  3 08:12:00.866: INFO: Failed to remove the iptable REJECT rule. Manual intervention is required on host 104.154.201.240:22: remove rule OUTPUT --destination 104.198.66.17 --jump REJECT, if exists
```
We should clarify. 

1  and 2 both have events like
```
Nov  3 09:08:45.180: INFO: At 2016-11-03 08:47:49 -0700 PDT - event for pet-2: {controllermanager } NodeControllerEviction: Marking for deletion Pod pet-2 from Node jenkins-e2e-minion-group-nfng
```
guessing the node controlelr shouldn't be setting timestamp?

**Comment by foxish** [comment]
Looking into the case 2:
The controller manager log goes:

```
I1104 00:47:27.530979       5 pet_set.go:332] StatefulSet pet blocked from scaling on pod pet-0
I1104 00:47:27.532388       5 pet.go:152] Delete of pet-0 in StatefulSet pet blocked by unhealthy pet pet-0
I1104 00:47:27.533887       5 pet.go:152] Delete of pet-2 in StatefulSet pet blocked by unhealthy pet pet-0
I1104 00:47:27.535241       5 pet.go:152] Delete of pet-1 in StatefulSet pet blocked by unhealthy pet pet-0
I1104 00:47:27.535258       5 pet_set_utils.go:134] Adding blocking pod pet-0 for StatefulSet pet
```

So I guess even deletions are being blocked by the health/readiness.

**Comment by foxish** [comment]
Both issues appear to be due to the testsuite and the way we use the "initialized" annotation in tests. I'll send a PR to fix these shortly. 
Thanks @bprashanth.
