### ISSUE TITLE
[k8s.io] [Feature:Example] [k8s.io] Spark should start spark master, driver and workers {Kubernetes e2e suite}

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#36102]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-examples/17028

Failed: [k8s.io] [Feature:Example] [k8s.io] Spark should start spark master, driver and workers 6.17s

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:205
Expected error:
    <exec.CodeExitError>: {
        Err: {
            s: "error running &{/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://130.211.133.46 --kubeconfig=/workspace/.kube/config create -f /workspace/kubernetes/examples/spark/spark-master-service.yaml --namespace=e2e-tests-examples-hg287] []  <nil>  error: the namespace from the provided object \"spark-cluster\" does not match the namespace \"e2e-tests-examples-hg287\". You must pass '--namespace=spark-cluster' to perform this operation.\n [] <nil> 0xc42013e570 exit status 1 <nil> <nil> true [0xc4206564d0 0xc4206564e8 0xc420656518] [0xc4206564d0 0xc4206564e8 0xc420656518] [0xc4206564e0 0xc420656500] [0x932a70 0x932a70] 0xc420d10e40 <nil>}:\nCommand stdout:\n\nstderr:\nerror: the namespace from the provided object \"spark-cluster\" does not match the namespace \"e2e-tests-examples-hg287\". You must pass '--namespace=spark-cluster' to perform this operation.\n\nerror:\nexit status 1\n",
        },
        Code: 1,
    }
    error running &{/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://130.211.133.46 --kubeconfig=/workspace/.kube/config create -f /workspace/kubernetes/examples/spark/spark-master-service.yaml --namespace=e2e-tests-examples-hg287] []  <nil>  error: the namespace from the provided object "spark-cluster" does not match the namespace "e2e-tests-examples-hg287". You must pass '--namespace=spark-cluster' to perform this operation.
     [] <nil> 0xc42013e570 exit status 1 <nil> <nil> true [0xc4206564d0 0xc4206564e8 0xc420656518] [0xc4206564d0 0xc4206564e8 0xc420656518] [0xc4206564e0 0xc420656500] [0x932a70 0x932a70] 0xc420d10e40 <nil>}:
    Command stdout:
    
    stderr:
    error: the namespace from the provided object "spark-cluster" does not match the namespace "e2e-tests-examples-hg287". You must pass '--namespace=spark-cluster' to perform this operation.
    
    error:
    exit status 1
    
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2066
```

This test has been consistently failing for a long time
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-examples/17027
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-examples/17026
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-examples/17024
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-examples/17028

**Comment by saad-ali** [comment]
CC @mwielgus @gurvindersingh 

Assigning @mwielgus based on previous instance https://github.com/kubernetes/kubernetes/issues/14462

Please reassign if you are not the correct owner.

**Comment by saad-ali** [comment]
Ping @mwielgus can you please take a look at this or reassign it. This test is consistently failing on every `kubernetes-e2e-gce-serial` run.

CC @kubernetes/examples

**Comment by calebamiles** [comment]
any updates on this issue @mwielgus? naively this seems like a misconfigured test rather than a flake. @elsonrodriguez do you happen to have any context on this test?

**Comment by elsonrodriguez** [comment]
@calebamiles I made a change to the docs recently and added the `spark-cluster` namespace to the objects that were missing it.

Don't know what the right resolution is.

**Comment by calebamiles** [comment]
any update on this issue @mwielgus, perhaps someone from @kubernetes/examples could take a look as well? I've added a non release blocker label please let me know if that should be changed to block the release.

**Comment by foxish** [comment]
Looking at this one today.

**Comment by calebamiles** [comment]
thanks @foxish

**Comment by dims** [comment]
Looks like this is worked on in https://github.com/kubernetes/kubernetes/pull/36548
