### ISSUE TITLE
pull-kubernetes-verify flake: godep: Error downloading some deps. Aborting restore and check.

### ISSUE THREAD

**Issue by euank** [kubernetes/kubernetes#36110]
Seen in issue #36020

Logs from [here](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/36020/pull-kubernetes-verify/2727/build-log.txt):

```
W1102 12:06:33.980] + cd /go/src/k8s.io/kubernetes
W1102 12:06:33.980] + godep restore
W1102 12:07:26.520] # cd .; git clone https://bitbucket.org/bertimus9/systemstat.git /go/src/bitbucket.org/bertimus9/systemstat
W1102 12:07:26.520] Cloning into '/go/src/bitbucket.org/bertimus9/systemstat'...
W1102 12:07:26.521] error: RPC failed; result=52, HTTP code = 0
W1102 12:07:26.521] fatal: The remote end hung up unexpectedly
W1102 12:07:26.521] godep: error downloading dep (bitbucket.org/bertimus9/systemstat): exit status 128
W1102 12:09:28.290] godep: Error downloading some deps. Aborting restore and check.
I1102 12:09:30.666] process 31951 exited with code 1
E1102 12:09:30.666] FAIL: pull-kubernetes-verify
```

At the very least, we should retry godep restore a couple times given the heavy network dependencies it has.

The network dependencies are sorta necessary... but they change rarely so we could also do some clever caching of unmodified clones that we put in place ahead of time to dodge network traffic outside of new deps being added.

cc @kubernetes/sig-testing

**Comment by rmmh** [comment]
We could probably do a single retry and avoid most flakes. Godep restore takes a long time though, so if we retry too many times we'll run into timeout issues (but maybe that's fine).

See also #31842, tools/godep#511

**Comment by rmmh** [comment]
Actually, it looks like this is only being done for an *excluded* verify step (`verify-staging-client-go.sh`). We should not do this for an excluded step, and we should not do `godep restore` for every PR.

**Comment by rmmh** [comment]
@caesarxuchao can you explain why staging/ needs `godep restore` to function?

**Comment by caesarxuchao** [comment]
verify-godeps.sh also runs `godep restore`: https://github.com/kubernetes/kubernetes/blob/master/hack/verify-godeps.sh#L91

**Comment by caesarxuchao** [comment]
`staging/` eventually get published to [client-go](https://github.com/kubernetes/client-go). IIRC, it needs `godep restore` because otherwise a later `godep save` fails ([here](https://github.com/kubernetes/kubernetes/blob/master/staging/copy.sh#L85)).

**Comment by caesarxuchao** [comment]
If we can run the verify script in order, then we can run verify-staging-client-go.sh after verify-godeps.sh, then we can save one `godep restore`.

**Comment by rmmh** [comment]
verify-godeps only runs if Godeps/ or vendor/ has changed.

**Comment by caesarxuchao** [comment]
Hmm, ok. How often will `godep restore` fail?

**Comment by rmmh** [comment]
I'm seeing ~.5% failure rate over the last few days, and averaging ~2 minutes for the godep restore. Do we have to check in _vendor for the staging client code at all?

**Comment by caesarxuchao** [comment]
We run `godep save` to find all the dependencies of clients, including k8s packages, so _vendor is not the reason we need `godep save`.
