### ISSUE TITLE
volume `subPath` behavior is not documented

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#36113]
There's effectively no documentation on this field.

@kubernetes/docs

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-storage

**Comment by bgrant0607** [comment]
@thockin This isn't the right repo to file documentation bugs, and engineers should document features when they are created.

**Comment by bgrant0607** [comment]
Please refile in kubernetes.github.io
