### ISSUE TITLE
Remove ugorji codecgen in 1.6

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#36120]
Now that we are moving to pure protobuf in etcd and for internal channels, we no longer need ugorji codec generation to make JSON fast.  We can use the ugorji marshaler / unmarshaler (it has minor perf benefits) or just revert to using golang JSON serialization.  The ratio of total cluster traffic using JSON should be small enough that the reduction in code size, generated code, and build logic is worth the tradeoff.

@kubernetes/sig-scalability

**Comment by smarterclayton** [comment]
@liggitt

**Comment by smarterclayton** [comment]
@kubernetes/sig-api-machinery

**Comment by wojtek-t** [comment]
Yes - we definitely should do once once we move to protobufs in etcd.

**Comment by wojtek-t** [comment]
It is also on my list to do after migration is done.

**Comment by smarterclayton** [comment]
Is there any disagreement with this?  Speak now or forever hold your peace.

**Comment by wojtek-t** [comment]
Since this is still 2x faster then regular json serializer, I would hold this of until we migrate storage format to protobufs. @lavalamp - FYI

**Comment by liggitt** [comment]
I would remove it sooner rather than later, given the overhead of the codegen and a lack of confidence in correctness (we've twice seen issues with nil getting confused with empty slices https://github.com/kubernetes/kubernetes/pull/37557 and https://github.com/kubernetes/kubernetes/pull/20536)

**Comment by liggitt** [comment]
and it breaks reusing api machinery for anyone who defines their own types without generating ugorji encodeself/decodeself implementations (since the inlined typemeta means their custom type is seen as implementing ugorji custom encode/decode methods)

**Comment by sttts** [comment]
To ping this thread again, I just experienced what @liggitt wrote in https://github.com/kubernetes/kubernetes/issues/36120#issuecomment-263375672: the new ugorji version skips types which (through embedding, e.g. of `ObjectMeta`) implement the `Selfer` interface: https://github.com/kubernetes/kubernetes/pull/37557, breaking plenty of our API types.

This also means that code generation is not idempotent: a fresh checkout without `types.generated.go` files will (depending on generation order) create `CodecEncodeSelf`/`CodecDecodeSelf` methods for those broken types. Running generation again skips those.

**Comment by wojtek-t** [comment]
>This also means that code generation is not idempotent: a fresh checkout without types.generated.go files will (depending on generation order) create CodecEncodeSelf/CodecDecodeSelf methods for those broken types. Running generation again skips those.

That's why we have all these machinery to do generation in the correct order here:
https://github.com/kubernetes/kubernetes/blob/master/hack/update-codecgen.sh

**Comment by brendandburns** [comment]
I want to ensure that as we do this, we maintain our performance SLA.

If we collect a histogram of request latency before and after removing this, there should be significant difference in the request latency distribution for all common requests (e.g. create pod, list pods, get pods, etc)

**Comment by thockin** [comment]
We should measure the perf and set a realistic goal.  In my free time I have been doing my own JSON generator that is way less noisy than ugorji, so that may be more manageable while keeping most or all of the perf win.  Low-prio

**Comment by smarterclayton** [comment]
I'd like to measure from 1.5 golang, and warn in 1.6 that you should expect kube 1.5 levels in the future.  No free performance handouts.

**Comment by spiffxp** [comment]
@kubernetes/sig-scalability-misc @kubernetes/sig-api-machinery-misc  

is this on the roadmap for 1.7?

[kubernetes-dev thread](https://groups.google.com/forum/#!topic/kubernetes-dev/k5ilr4k50BE)

this would greatly assist with #8830

**Comment by thockin** [comment]
I have been working on a better JSON codec, so we can keep the perf.  It's
not at the top of my stack, though, but it's close to working.

**Comment by krousey** [comment]
I thought the point was to not have generated JSON codecs and just use the standard JSON package. Are we still using JSON encoding in performance sensitive paths?

**Comment by thockin** [comment]
I don't think a massive perf regression is OK, if we can avoid it.  We can
eject ugorji if we want, but I might still offer my own thing :)

It's my 120% project.

**Comment by krousey** [comment]
What do the metrics say the performance impact would be since we've moved storage, controllers, and nodes to proto?

The only thing I really ask is please don't implement this by generating methods on the types.

**Comment by caesarxuchao** [comment]
> The only thing I really ask is please don't implement this by generating methods on the types.

May i ask what the concerns are?

**Comment by thockin** [comment]
Why?  That's exactly how it is implemented and it is far cleaner than the
alternative.

**Comment by krousey** [comment]
Basically there are a lot of hoops required to re-use `ObjectMeta` for third party types. This is an unfortunate combination of struct embedding plus method sets including the methods of embedded structs. Documented here https://github.com/kubernetes/client-go/issues/8. I don't know why that issue is closed. Last I checked, this is still an issue, with some rather verbose workarounds. If possible, I would like to avoid the headache completely.

**Comment by thockin** [comment]
I tried to read that but I don't understand the issue with methods.

**Comment by krousey** [comment]
In k8s code:
```go
type ObjectMeta struct { ... }
func (o *ObjectMeta) SpecialEncode() { ... }
func (o *ObjectMeta) SpecialDecode() { ... }
```

In third party code that doesn't run our code generation tools but just wants to reuse us like a normal library:

```go
type struct MyType struct {
	v1.ObjectMeta  // picks up methods
	...
}

...
var o MyType
// this calls SpecialDecode that's defined on v1.ObjectMeta and doesn't decode anything into the containing type
err := client.Get().Resource("MyType").Namespace(api.NamespaceDefault).Name("example_name").Do().Into(&o)
```

Workaround involves not embedding but rather naming the metadata and defining `GetObjectKind()`, `GetObjectMetadata()`, and `UnmarshalJSON()` (not sure if `MarshalJSON()` is required too). And do this all over again for the list type.

**Comment by thockin** [comment]
Ah, interesting.  Yes, I see that.  Maybe we should not be embedding.  I
sort of argued this a long long time ago, but gave up.  It would be tedious
to fix but not impossible.

@sttts wrt deepcopy, too.

**Comment by krousey** [comment]
@thockin Yea, as I was typing the workarounds, I thought... you know... That's how it should be anyway (at least for the Get* methods... having to write your own marshal and unmarshal is broken).

**Comment by wojtek-t** [comment]
> What do the metrics say the performance impact would be since we've moved storage, controllers, and nodes to proto?

There shouldn't be any visible drop. Basically, the only objects that would require more work after removing ugorji (assuming that you're using protobufs for communication between components and for storage format, which are both default now) would be requests coming from users, kubectl and stuff like that. There shouldn't be that much of this stuff, but performance of those can drop.

**Comment by smarterclayton** [comment]
https://github.com/json-iterator/go/blob/master/README.md claims to be much faster.  Maybe someone should try it out

**Comment by smarterclayton** [comment]
Ouch... there's a new king of the hill:

```
BenchmarkDecodeIntoProtobuf-8        	  500000	      2641 ns/op	    1763 B/op	      35 allocs/op
BenchmarkDecodeIntoJSON-8            	   50000	     33669 ns/op	    3315 B/op	      58 allocs/op
BenchmarkDecodeIntoJSONCodecGen-8    	  100000	     17740 ns/op	    6724 B/op	      90 allocs/op
BenchmarkDecodeIntoJSONIter-8        	  200000	      8065 ns/op	    3910 B/op	      52 allocs/op```

That's... ouch... much better.

Looks like downsides are custom unmarshallers have to be registered (doesn't use standard Go interfaces) and the registration mechanism doesn't look like it handles types in packages named the same... but... yeah, that's a lot faster.

**Comment by thockin** [comment]
I threw it at a testcase Ihave and it SEGV'ed.  I'll file a bug with them.

I wonder if they could accept standard custom JSON methods at some cost.

**Comment by thockin** [comment]
Where do you see that they don't support methods?

**Comment by smarterclayton** [comment]
metav1.Time failed because it's a struct in memory but UnmarshalJSON overrides.  So they're not checking that method before they call the command. 

I had to fake out with:

```
+       jsoniter.RegisterTypeDecoder("v1.Time", func(ptr unsafe.Pointer, iter *jsoniter.Iterator) {
+               iter.ReadString()
+               /*t, err := jsoniter.ParseInLocation("2006-01-02 15:04:05", iter.ReadString(), time.UTC)
+               if err != nil {
+                       iter.Error = err
+                       return
+               }*/
+               *((*metav1.Time)(ptr)) = metav1.Time{}
+       })
```

they're also accepting type as string which is not safe.

**Comment by thockin** [comment]
The numbers look good (when it passes my test battery).  This could be our
way out of ugorji hell.

**Comment by smarterclayton** [comment]
Unfortunately it could also be our way into malicious input and memory
safety hell... :)

**Comment by thockin** [comment]
I started writing a custom code-gen for JSON, but without getting into
`unsafe` territory it's kind of hard to beat standard JSON.  I don't know
if I want to spend any more time on it if this is viable instead.

**Comment by smarterclayton** [comment]
Another datapoint on why I think ugorji has to go by default:

Have a simple client that wants to import Kubernetes client-go.  Pre
importing anything from client-go, the binary is 10M (of which 4 is the
runtime roughly and 6 is a lot of standard library).  Post import, binary
jumps to ~37M.  Remove types.generated.go and compile again - size drops to
roughly 30M.  So every small tool out there pays 7M for the benefit of
ugorji.  We might want to make it opt in via a build tag.

**Comment by thockin** [comment]
I have been writing tests for json-iterator to confirm it works just like
stdlib.  I found a bunch of bugs and they have so far all been fixed.

Benchmarks look really good, without codegen.

My next test will be to patch it into kubernetes and see what still doesn't
work.  I have not tested logic around interfaces.

**Comment by wojtek-t** [comment]
This sounds really cool. I would really like to get rid of ugorji finally.

> I started writing a custom code-gen for JSON, but without getting into
`unsafe` territory it's kind of hard to beat standard JSON.

Yeah - I agree.

**Comment by thockin** [comment]
So I am convinced json-iterator works well for round-tripping object ->
JSON -> object.  I am not yet convinced it handles all sorts of JSON input
in sane ways.  Could use help designing tests for that or convincing
ourselves their tests are good enough.

**Comment by liggitt** [comment]
> I am not yet convinced it handles all sorts of JSON input in sane ways. Could use help designing tests for that or convincing ourselves their tests are good enough.

The state machines around numbers are concerning, especially on non-normalized input. The first bit I checked (exponent handling) was handled differently in different parts of the library, and didn't handle positive exponents (`1E+10`) correctly.

It's also very accepting of malformed input. A few examples:
* It accepts `{"foo":navy}` because it sees the `n`, skips four characters and assumes it is skipping "null"
* It allows control characters inside strings, so it accepts 
    ```
    {"foo":"bar
    baz"}
    ```

**Comment by taowen** [comment]
@liggitt You can post issues to the project, I will fix it.

**Comment by liggitt** [comment]
https://github.com/json-iterator/go/pull/125
https://github.com/json-iterator/go/pull/124

**Comment by taowen** [comment]
@liggitt fixed. thanks
