### ISSUE TITLE
Kubelet: network state unknown for local cluster with experimental cri enabled

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#36137]
Start a local cluster with experimental cri enabled:

```
export KUBERNETES_PROVIDER=local
export EXPERIMENTAL_RUNTIME_INTEGRATION_TYPE=cri
hack/local-up-cluster.sh
```

Kubelet is always complaining `[network state unknown]` :

```
I1103 05:35:07.258534   13249 kubelet.go:1609] skipping pod synchronization - [network state unknown]
I1103 05:35:12.258784   13249 kubelet.go:1609] skipping pod synchronization - [network state unknown]
I1103 05:35:12.843200   13249 eviction_manager.go:217] eviction manager: no resources are starved
I1103 05:35:17.259045   13249 kubelet.go:1609] skipping pod synchronization - [network state unknown]
I1103 05:35:22.259353   13249 kubelet.go:1609] skipping pod synchronization - [network state unknown]
I1103 05:35:22.879768   13249 eviction_manager.go:217] eviction manager: no resources are starved
I1103 05:35:27.259628   13249 kubelet.go:1609] skipping pod synchronization - [network state unknown]
```

This is because network plugin is set to nil when `EXPERIMENTAL_RUNTIME_INTEGRATION_TYPE=cri` is enabled. In this case, kubelet rely on pod CIDR to check whether the network is ready, however for local cluster there may be no pod CIDR (reference [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_network.go#L200)):

```go
	if kl.networkPlugin != nil {
		kl.runtimeState.setNetworkState(kl.networkPlugin.Status())
	} else if kl.runtimeState.podCIDR() != "" {
		// Don't mark the node ready till we've successfully executed
		// the first UpdatePodCIDR call through cri. See comment above
		// setPodCIDR call.
		kl.runtimeState.setNetworkState(nil)
	}
```

@Random-Liu is volunteered to fix this problem while adding `Status()` to CRI.

cc/ @yujuhong @bprashanth @kubernetes/sig-node

**Comment by Random-Liu** [comment]
https://github.com/kubernetes/kubernetes/pull/35839 should fix this.

**Comment by bprashanth** [comment]
in the meanwhile you can just give it a cidr, like one normally does https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh#L400

**Comment by feiskyer** [comment]
> in the meanwhile you can just give it a cidr, like one normally does https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh#L400

Yes, of course, setting `export NET_PLUGIN=kubenet` works ok. #35839 will be merged soon to fix cases network plugin is not set.

**Comment by yujuhong** [comment]
Closing since #35839 has been merged.
