### ISSUE TITLE
kubernetes 1.4.+  kube-dns  and kubeadm.conf

### ISSUE THREAD

**Issue by jicki** [kubernetes/kubernetes#36135]
[root@k8s-master ~]#kubectl get svc --namespace=kube-system
NAME                   CLUSTER-IP     EXTERNAL-IP   PORT(S)         AGE
kube-dns               10.0.0.10      <none>        53/UDP,53/TCP   2d

kubeadm.conf
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.12.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_EXTRA_ARGS=--v=4"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_EXTRA_ARGS

svc cluster ip = 10.0.0.10

kubeadm.conf  cluster-dns = 10.12.0.10

**Comment by bulletRush** [comment]
@luxas it seems like this person have same problem with me. 
if we install kubelet via yum, then we get a default cluster-dns config `100.64.0.10`. then we use kubeadm to start up our cluster. the kube-dns service get a cluster ip `10.0.0.10`. so nslookup( [Using DNS Pods and Services](http://kubernetes.io/docs/admin/dns/) )will not work. 
---
Am i right?should we add a preflight check to this?

**Comment by JrCs** [comment]
`cluster-dns` is store staticaly in the `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` and is install when we installed kubeadm with yum.
As we can change the range of IP address for service VIPs  (with the --service-cidr option of kubeadm) the cluster-dns maybe false.
So at least we need a preflight check, and perhaps kubeadm can create an environment file that contain the right dns IP address calculate from the service-cidr.

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#9
