### ISSUE TITLE
kubelet: fetch metrics from readinessprobe and livenessprobe

### ISSUE THREAD

**Issue by kayrus** [kubernetes/kubernetes#36141]
kubelet already checks endpoints (readinessprobe and livenessprobe), so why don't implement metrics gathering for these probes?

**Comment by abraithwaite** [comment]
I want this functionality.

**Comment by lindazhang82** [comment]
current we have found the container restarted very frequently due to liveness and readness probe unhealth, and we have checked, there is no any meaningful log for this behavior, is it possible to show the meaningful log of liveness and readness in kubelet?
