### ISSUE TITLE
kubectl port-forward should allow binding/listening to other interfaces

### ISSUE THREAD

**Issue by rcoup** [kubernetes/kubernetes#36152]
**What keywords did you search in Kubernetes issues before filing this one?**
port forward bind address
port forward localhost
port forwarding listen

**Is this a BUG REPORT or FEATURE REQUEST? (choose one):** FEATURE REQUEST

**Kubernetes version (use kubectl version):**
```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1+33cf7b9", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"not a git tree", BuildDate:"2016-10-13T15:13:44Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Describe *in detail* the feature/behavior/change you'd like to see.**

Currently `kubectl port-forward` only allows binding to localhost...

```
$ kubectl port-forward mypod 4560
Forwarding from 127.0.0.1:4560 -> 4560
Forwarding from [::1]:4560 -> 4560
```

It would be good to be able to bind to another local interface (and "all/*/0.0.0.0"), something like:

```
$ kubectl port-forward --bind-address 0.0.0.0 mypod 4560
Forwarding from 0.0.0.0:4560 -> 4560
Forwarding from [::]:4560 -> 4560
```

```
$ kubectl port-forward --bind-address 192.168.56.1 mypod 4560
Forwarding from 192.168.56.1:4560 -> 4560
```

This would allow more advanced interactions for debugging/interaction between local development environments and containers running on k8s.

[kubectl proxy](http://kubernetes.io/docs/user-guide/kubectl/kubectl_proxy/) supports `--bind-address` which seems like a good a name as any, to be consistent.

See also: https://github.com/kubernetes/kubernetes/issues/25113

**Comment by Rurouni** [comment]
This is blocking scenario where you have docker image that with single docker run can reconfigure local dev environment to point to remote cluster in GCE(for example) and expose kibana, grafana, zipkin etc on localhost, so no need to have them being fully exposed to internet dealing with auth, SSL  etc

**Comment by jkamenik** [comment]
:+1:

I think it should be parallel to the `kubectl proxy` command, which uses `--address`.  Here is what I do for kubectl proxy.

```bash
$ docker run -p 8001:8001 ...
# kubectl proxy --address 0.0.0.0
Forwarding from [::]:8001 -> 8001
```

Right now the workaround we do is that we deploy a docker container with kubectl and our product configs, and then we have users separately download kubectl and run `port-forward` from outside.  Would be ideal to be able to wrap this entirely within the docker container.

**Comment by yasmineenis** [comment]
--bind-address is not supported how to do?

**Comment by mbukosky** [comment]
+1

**Comment by avis71** [comment]
+1

**Comment by robsonpeixoto** [comment]
While it's not ready, you can add a firewall rule:

```
echo "rdr pass inet proto tcp from any to any port 8083 -> 127.0.0.1 port 8083" | sudo pfctl -ef -
```

And use `sudo pfctl -F all -f /etc/pf.conf` to cleanup the rules.

**Comment by thockin** [comment]
Dup of #29678

**Comment by darren-rose** [comment]
`ubuntu@dev06:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
ubuntu@dev06:~$ kubectl port-forward hello-world-2822484588-hqzw4  10600:8080
error: error upgrading connection: Upgrade request required
ubuntu@dev06:~$ 
`

**Comment by daggerok** [comment]
Hi,

how long I was looking it... thanks for 1st post! I was need to access to conrete pods inside my kubernetes-dind installation... now I know how to do that :)

terminal 1: forward rest-api service 8080 port (from rest-api-1859009132-bjn7p pod) to my localhost 8001 port using this command:

```bash
kubectl port-forward rest-api-1859009132-bjn7p 8001:8080
Forwarding from 127.0.0.1:8001 -> 8080
Forwarding from [::1]:8001 -> 8080
```

terminal 2: how I able access exact pod I need

```bash
curl -sS localhost:8001/api/v1/bla-bla
```

Hope, this will helps to beginners like me...

---
Regards,
Maksim

**Comment by ynfeng** [comment]
[root@master istio-0.4.0]# kubectl port-forward -n istio-system $(kubectl get pod -n istio-system -l app=zipkin -o jsonpath='{.items[0].metadata.name}') 9411:9411
Forwarding from 127.0.0.1:9411 -> 9411

**Comment by neuro-sys** [comment]
In case anyone needs a workaround to bind to another host from a kubernetes pod, i.e. hop from the pod to another remote that is only accessible from the pod for whatever reason, and since `kubectl port-forward` has a limitation to only forward a port to pod's localhost, you can do the following:

- Install `scat` tool inside the pod. `scat` is similar to `gnu-netcat` with additional features.
- Create a local port mapping with the following command on the pod that has access to the remote host:
```
socat tcp-l:$LOCAL_PORT,fork,reuseaddr tcp:$REMOTE_IP:$REMOTE_PORT
```
- On your host machine use the `kubectl port-forward` tool to create the port mapping:
```
kubectl port-forward my-pod-xxxx $LOCAL_PORT:$LOCAL_PORT
```
where `$LOCAL_PORT` is the same as what you used inside the pod for local binding.
- Now you can can access `$REMOTE_IP:$REMOTE_PORT` from your host machine by connecting to `localhost:$LOCAL_PORT`:

```
$ nc -z localhost 9999
Connection to localhost port 9999 [tcp/distinct] succeeded!
```

**Comment by jwatte** [comment]
I really wish --bind-address was supported in kubectl port-forward.

**Comment by thockin** [comment]
Does https://github.com/kubernetes/kubernetes/pull/46517 not address
your needs?  It adds `--address` as a flag.

**Comment by SaifJerbi** [comment]
I test it and it works, i'm using a shared virtual machine as a proxy between the k8s cloud hosted and the local developers machine, so the --address make my VM forwarding all request to the cloud
kubectl port-forward --address 0.0.0.0 pod/mypod 8888:5000
