### ISSUE TITLE
Write e2e test for external provisioning

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#36170]
External provisioning as defined in https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/volume-provisioning.md needs an e2e test of the Kubernetes side.

There is implementation of a sample provisioner in https://github.com/wongma7/nfs-provisioner, but it needs a nfs client on GCE/GCI to test with. I will write a test when this is resolved.

**Comment by wongma7** [comment]
@jsafrane I can work on this (I already have some tests, copied from/based on the internal dyn. provisioning tests, that test this from my external POV https://github.com/kubernetes-incubator/nfs-provisioner/blob/master/e2e/e2e_test.go)
