### ISSUE TITLE
Should have kubernetes service in kube-system

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#36173]
The way we access the kubernetes service is inconsistent; in all other namespaces it is `https://kubernetes`, but in kube-system I don't have a `kubernetes` service (should I?).

When I try to use `kubernetes` from go I get this error:
```
Get https://kubernetes/api: dial tcp: lookup kubernetes on 100.64.0.10:53: server misbehaving
```

bboreham pointed out that I can use `KUBERNETES_SERVICE_HOST`, but I feel this inconsistently is likely to continue to surprise people.

It may be something wrong in my configuration (i.e. perhaps the kubernetes service should already be registered in kube-system), but is there some reason _not_ to register it?

**Comment by luxas** [comment]
The kubernetes service has always been in the default namespace, there's nothing wrong with your config in that sense.

Does other DNS names resolve and does `kubernetes.default.svc.cluster.local` resolve?
Otherwise you might have something with the dns rc/service

**Comment by bgrant0607** [comment]
@justinsb Is there any particular reason why you don't set labels when you file issues?

**Comment by luxas** [comment]
I think this is fine as-is, I don't see a reason to create many duplicated services for the same k8s API server endpoint for N namespaces, using just `kubernetes.default` is fine.
