### ISSUE TITLE
Contributing back authz webhook

### ISSUE THREAD

**Issue by mward29** [kubernetes/kubernetes#36177]
Hello,

We would like to contribute back our authz-webhook to the Kubernetes Community. We would continue to iterate on it but its in a good enough place now to at least get it in I think.

Questions I'm looking to answer:
Is this enough value to the community to have it represented within the Kubernetes sphere?
If so, where should it go?
What else would you like to see if it offers value but is needs something prior to a PR being made?

I'm working on the corporate contributor piece now.

Written in Go.
https://github.com/pearsontechnology/bitesize-authz-webhook

We have some additional documentation to do yet but examples can be found:
https://github.com/pearsontechnology/bitesize-authz-webhook/tree/master/examples

**Comment by simonswine** [comment]
Hey @mward29, I find your authz webhook really useful. Thanks for contributing that back.

I think given that the RBAC feature aims to solve similar issues, it still provides additional value around its more bespoke options in configuring regular expression to match usernames / namespaces /... 

It also can be a good very good starting point of implementing a custom authz webhook.

I think the right place may be https://github.com/kubernetes/contrib/

**Comment by liggitt** [comment]
Thanks for the pointer to the project. It's great to see examples of projects that plug into the kubernetes extension points without needing to be in-tree
