### ISSUE TITLE
[CRI] Avoid user data in exec redirect URL

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#36187]
For handling exec's with the CRI, the API server snoops the exec response looking for a redirect to follow to the final exec endpoint (more details [here](https://docs.google.com/document/d/1OE_QoInPlVCK9rMAx9aybRmgFiVjHpJCHI9LrfdNM_s/edit), implemented [here](https://github.com/kubernetes/kubernetes/pull/34987)).

Currently the returned URL includes the exec command, which is an arbitrarily long user supplied value, making it impossible to reasonably snoop the response.

Potential solutions include:

1. Using a token to represent the exec URL, which the CRI server caches with the actual command.
2. Don't use a redirect, instead the API server issues to requests. The first fetches the URL, the second opens the stream (basically a manual redirect, but there's no response-snooping involved)

This is a *blocker* for the CRI streaming exec calls exiting alpha. (Feature guarded with `"StreamingProxyRedirect"`)

/cc @liggitt @yujuhong @kubernetes/sig-node

**Comment by timstclair** [comment]
Ref: https://github.com/kubernetes/kubernetes/issues/29579

**Comment by liggitt** [comment]
if the user data was placed in a session held by the CRI, and sufficient entropy was included in the session identifier token, and the CRI treated the token as single-use, that could also remove the need for the CRI to re-authn/authz the request

**Comment by euank** [comment]
1) api-server still makes two requests (following a 302 makes a new request).. it just happens that it looks like they're basically one because it's done via redirects.
```
api-server ---exec(cmd)---> kubelet
                                    ---getTokenUrl(cmd)---> runtime
                                    <--------token---------
           <-----302(token)----
api-server -------exec(token)---> CRI
```

The big problem with this one is that the mapping of token->cmd has to be stored somewhere! That'll probably be the runtime storing it by spinning up a new exec server in the pod in the further future, but for now it's a little inconvenient.

2) api-server makes two more explicit requests.
```
api-server ---getExecUrl()---> kubelet
															        ---getExecUrl()--> runtime
                                      <----url----------
           <-----url----------

api-server ----exec(cmd)-----> CRI
```

This requires more intrusive api-server changes, but is a cleaner interface I think!

**Comment by timstclair** [comment]
> The big problem with this one is that the mapping of token->cmd has to be stored somewhere! That'll probably be the runtime storing it by spinning up a new exec server in the pod in the further future, but for now it's a little inconvenient.

I would integrate the token storage into the streaming server library. No change would be needed for individual CRI shims using the library (other than a possible vendor update).

> This requires more intrusive api-server changes, but is a cleaner interface I think!

I don't think that's exactly true (see the lengthy discussion on https://github.com/kubernetes/kubernetes/pull/34987, handling the redirects is far from unobtrusive). The big disadvantage I see to (2) is that the backwards compatability becomes a little awkward. We would need to send the first request to a new URL, and if it's a 404 fall back to the legacy endpoint. A big advantage to this is we could use more structured data if necessary.

**Comment by timstclair** [comment]
FYI - I have a fix for this, waiting on https://github.com/kubernetes/kubernetes/pull/38435 to send it out.

**Comment by timstclair** [comment]
Just wanted to clarify that I'm going to push forward with option 1 (token) for now, since it can be implemented with 0 API changes, and no changes to the runtime shim. We may need to consider option 2 at some point for security reasons (SSRF if we want the node to be a security boundary), but that would require changes to the CRI API, a new kubelet endpoint, and changes to process the second request in the apiserver.
