### ISSUE TITLE
kubeadm: Pass --cloud-provider and --cloud-config to kubelet

### ISSUE THREAD

**Issue by codablock** [kubernetes/kubernetes#36213]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BOTH

**Kubernetes version** (use `kubectl version`):
1.5 custom built master

**Environment**:
- **Cloud provider or hardware configuration**: azure
- **OS** (e.g. from /etc/os-release): CentOS 7.2
- **Kernel** (e.g. `uname -a`): Linux ma-kub8ms0 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: ansible + kubeadm
- **Others**:

**What happened**:
When passing --cloud-provider to kubeadm, the flag is only passed to the controller manager. It is however not passed to the kubelet, which makes Azure Disk mounting (and probably other cloud features?) not work. Also, the --cloud-config flag is not passed into the kubelet. 

It looks like the kubelet is able to figure out the appropriate cloud provider (azure) by itself. Not sure how it does this, maybe it gets a hint from the controller manager. Nevertheless, if users provide a cloud provider to kubeadm, this one should be explicitly passed to all services which offer such an option. Also, the (correct) auto guessing does not help when there is no cloud config given to the kubelet. 

I currently have to provide a custom systemd dropin which overrides the KUBELET_EXTRA_ARGS env var. 

An idea how to fix this: Add an optional environment file (/etc/kubernetes/kubeadm-kubelet-args.env) to the 10-kubeadm.conf dropin. The kubeadm could then write appropriate cloud-config (and other?) flags to this file.

**Comment by errordeveloper** [comment]
> I currently have to provide a custom systemd dropin which overrides the KUBELET_EXTRA_ARGS env var.

This the best way to go with 1.4, in 1.5 we might be able to leverage dynamic kubelet settings feature (but that's still an early alpha, so hard to say if it will work well enough).

**Comment by codablock** [comment]
I can keep doing this, the only problem is that I'll have to keep my override up to date in case you ever change the current value of KUBELET_EXTRA_ARGS. Currently it's only "--v=4"...but I can imagine that you add something in the future. Maybe we should add an extra env which by definition will never be touched by maintainers and is only for custom args? Like:

```
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=100.64.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_EXTRA_ARGS=--v=4"
Environment="KUBELET_CUSTOM_ARGS=" # You can provide a dropin to override this with your custom args
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_EXTRA_ARGS $KUBELET_CUSTOM_ARGS
```

**Comment by luxas** [comment]
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cloud-provider-refactoring.md will probably fix this.

Until then, you must use the drop-in file like that. We won't touch KUBELET_EXTRA_ARGS

**Comment by dkirrane** [comment]
Was there a solution for this? For VSphere Cloud Provider I need to pass the following flags to kubelet, controller-manager and api-server
```
--cloud-provider=vsphere /
--cloud-config=/etc/kubernetes/vsphere.conf
```

**Comment by errordeveloper** [comment]
@dkirrane the solution is to use systemd drop-in.
