### ISSUE TITLE
Collect logs from Rescheduler

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#36227]
We need to have collected by:
- fluentd
- jenkins

**Comment by piosz** [comment]
@Crassirostris could you please take a look?

**Comment by Crassirostris** [comment]
I this is actually two separate problems.

Exporting resheduler.log as artifact from master is easy.

Exporting logs to the logging backend will require fluentd configuration changes => images version changes, which are blocked by https://github.com/kubernetes/kubernetes/pull/35216 and https://github.com/kubernetes/kubernetes/pull/35618
