### ISSUE TITLE
Expose a service with LoadBalancer on non-cloud providers using custom image for the load balancer

### ISSUE THREAD

**Issue by dgonzalez** [kubernetes/kubernetes#36220]
Here is one idea:

When you are running a cluster in your bare metal infrastructure, you cannot expose a service (or anything) using the LoadBalancer for obvious reasons.

When you are running a in a cloud provider, it uses the native load balancer (AKA Elastic Load Balancer in AWS) provisioning and configuring it.

My point is:

Why not have an extra flag in the expose command that allows you to specify the image to use as a load balancer in your bare metal cluster? E.g:
```
kubectl expose rc my-service --type LoadBalancer --image my-custom-ha-proxy
```

And that will deploy a container with my-custom-ha-proxy and use it on a similar way as it does for the ELB in AWS.

This came up in a conversation in the slack channel #kubernetes-users and the originator question was... "how do I know the IP of the caller within the cluster?" And this solution came up as you would be able to configure the x-forwarded-for header and send it to the destination service.

If this issue sounds like there is a better way of doing it... please reply on a comment and close it!

**Comment by justinsb** [comment]
Can you just deploy your controller into kube-system ahead of time, and have it watch for services of Type=LoadBalancer?  That way the person running `kubectl expose` would not need to know whether e.g. an F5 load balancer was in use, or something using DNS with hostPorts.

I do think your approach is interesting for when multiple LoadBalancer solutions are in use on the same cluster, but I don't think that is particularly widespread (?)

**Comment by dgonzalez** [comment]
The problem with listening for Type=LoadBalancer is magical things happening in the background. With my approach, it is explicit: you have to specify an image for it to be provisioned (or possibly the service name of an already running one).

**Comment by dgonzalez** [comment]
BTW I think the ingress controller is an interesting concept with a lot of potential.

**Comment by davetropeano** [comment]
@dgonzalez your comment about "[the] problem with listening for Type=LoadBalancer is magical things happening in the background." is what happens when you are using a cloud provider like AWS, GCE, Openshift, etc. Getting the instance of the LB is an async process that happens behind the scenes. 

FWIW the `service-loadbalancer` contribution does not support listening against Type=LoadBalancer, instead they use custom labels and listen against those (and you don't set the Type field). [https://github.com/kubernetes/contrib/tree/master/service-loadbalancer](https://github.com/kubernetes/contrib/tree/master/service-loadbalancer)

**Comment by dgonzalez** [comment]
@davetropeano I think I didnt explain myself well: What I am suggesting is provisioning a load balancer within the cluster using a custom image instead of an external load balancer within the cloud. I am swamped at the moment but ping me in the kubernetes slack (@davidgonza) and we can talk more about it. Maybe that is the solution but I need to picture it.

**Comment by bgrant0607** [comment]
cc @bprashanth

**Comment by MikeSpreitzer** [comment]
(A) I agree with the concern expressed earlier about separation of concerns.  The person deploying a service should not have to know how the cluster is implemented.  I would rather see this custom LB image specified as a parameter of the controllers manager.  Perhaps the best way to slip this in is to make a cloud provider that just knows how to make load balancers using a custom image.

(B) Would the container or pod made from this image be attached to the host network or the regular pod network?  I suppose the host network, as that is where the LB's ingress IP address should appear.  What is the IP address management story?  If this LB is a pod, how does it bind each service's ingress IP?

**Comment by MikeSpreitzer** [comment]
(D) Is the idea here to develop one generic custom LB image to use in bare metal installs, or is it expected that different bare metal environments will each need their own custom LB image?

**Comment by lichen2013** [comment]
Hi,

I have a similar idea, to use a haproxy deployment between the service and pods, can this work ?

![elb in kubernetes](https://cloud.githubusercontent.com/assets/3983266/20875645/5677bc08-baf7-11e6-831f-8a7bd95954af.png)

**Comment by bprashanth** [comment]
@dgonzalez  do you really want to couple the deployment of the loadbalancer to the exposure of a single backend, or do you just want a loadbalancer implementation for bare metal (and deploying one lb per pod is just a means to an end)?

**Comment by dgonzalez** [comment]
Sorry I'be been disconnected from this for a while.

@bprashanth no, what I want to is be able to create my own balancer on bare metal but this is also useful for cloud. Example: I want to throttle the requests to my app. What I would do in here is create a nginx image with the configuration for it and expose my service as LoadBalancer using this image as the load balancer. Does that makes sense?

**Comment by uiansol** [comment]
I also interested in something like this. I need to be able to create load balancer on-premises without a cloud provider.

@dgonzalez Did you have some progress on this feature? I would like to help in some discussion and maybe a proposal for this feature.

**Comment by roffe** [comment]
I'm gonna Trump this one. -"Good idea doesn't work"

The Type Loadbalancer is well implemeted but requires a cloudprovider.

Instead of trying to make some LB images that you magicly specify and unicorns comes out you should look into creating your own cloud provider which can provide this for you.

**Comment by stepin** [comment]
Looks like now custom Cloud Controller Manager can be used for such tasks (custom LoadBalancer on bare-metal):
https://kubernetes.io/docs/tasks/administer-cluster/developing-cloud-controller-manager/

**Comment by MarkusTeufelberger** [comment]
https://github.com/google/metallb might be worth a look for everyone who finds this issue via web search etc.

**Comment by soufianetomase** [comment]
/reopen
any news for a feature integrated into kubernetes to answer this need ?
