### ISSUE TITLE
Problems with duplicate Node Hostname records

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#36234]
codablock on slack reported an issue regarding  https://github.com/kubernetes/kubernetes/pull/25532

(paraphrasing) "When used in combination with the Azure cloud provider, I get errors about Node.Status.Addresses being duplicated"

Looking at the code, the Azure cloudprovider returns a HostName address, but then a HostName address is also added by the kubelet code itself.

**Comment by justinsb** [comment]
cc @colemickens

**Comment by justinsb** [comment]
I have two PRs with different alternatives:

* #36231 adds a hostname unless the cloudprovider already set one.
* #36233 relies on the cloudprovider to set one, and does not add one.

I think #36231 has the problem that the cloudprovider has no way to say that Hostnames are not in use.  

#36233 relies on the cloudprovider adding the hostname if it wants it, which is trivial for it to do.

@liggitt any thoughts on the options?

**Comment by liggitt** [comment]
I'd get the cloudprovider to set one if it wants (#36231)
