### ISSUE TITLE
CRI: Network should set TCP CLOSE_WAIT timeout

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#36247]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/36239/pull-kubernetes-e2e-gce-cri/42/

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kube_proxy.go:204
Expected error:
    <*strconv.NumError | 0xc420b842d0>: {
        Func: "ParseInt",
        Num: "",
        Err: {s: "invalid syntax"},
    }
    strconv.ParseInt: parsing "": invalid syntax
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kube_proxy.go:191f
```

/cc @bowei

**Comment by bowei** [comment]
assign this to me

**Comment by yujuhong** [comment]
@bowei does the tests rely on host ports? CRI doesn't support that yet (#35457).

**Comment by bowei** [comment]
discussed offline: yes it relies on host ports, so probably should skip this test for the CRI environment

**Comment by yujuhong** [comment]
CRI suites now skip the test by default. Closing this issue.
