### ISSUE TITLE
Make cri cluster/node e2e suites submit queue blocking

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#36264]
Once the builds stabilize after the code freeze, we should make the suites blocking to prevent regression.
We should also consider making cri node e2e mandatory for pre-submit PR checks.

/cc @kubernetes/sig-node @Random-Liu

**Comment by yujuhong** [comment]
https://github.com/kubernetes/test-infra/pull/1038 makes cri node e2e test mandatory for all PRs.. 
Will make the cluster e2e test mandatory once it stabilizes more. Also need to make the two CRI CI suites submit queue blocking.

**Comment by feiskyer** [comment]
Cool. CRI Node tests are running automatically on recent PRs. 

@yujuhong Also enable CRI GCE e2e tests as blocking?

Note: there are two flakes in recent CRI GCE e2e tests, both are because of `etcd cluster is unavailable or misconfigured`.

**Comment by yujuhong** [comment]
> @yujuhong Also enable CRI GCE e2e tests as blocking?

I'd like to get #36768 in first and see if the flake in the cluster e2e tests goes away.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5  @yujuhong

**Comment by dims** [comment]
@yujuhong all issues must be labeled either release blocker or non release blocking by end of day 18 November 2016 PST. (or please move it to 1.6) cc @kubernetes/sig-node

**Comment by dims** [comment]
@yujuhong Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by Random-Liu** [comment]
Currently, only cri node e2e test is submit queue blocker, so this issue is not done yet.

CRI cluster e2e test is quite stable now, except the test `[k8s.io] Loadbalancing: L7 [k8s.io] Nginx should conform to Ingress spec`. The test starts failing in CRI suite since introduced.

I'll debug the test and add cluster e2e as submit queue blocker after fixing the test.

Move this to 1.6.

**Comment by yujuhong** [comment]
We should also add this builds to `submit-queue.nonblocking-jenkins-jobs` so that we get issues filed automatically.

**Comment by yujuhong** [comment]
An example of a PR that broke CRI because we don't run the cluster e2e test yet: #33684
We still need the host port support so that people don't have to manually disable their test in the config if it uses host ports

**Comment by yujuhong** [comment]
> Currently, only cri node e2e test is submit queue blocker, so this issue is not done yet.

The cluster e2e has just become mandatory for every PR: https://github.com/kubernetes/test-infra/pull/1861

**Comment by rmmh** [comment]
Do you have another PR that has broken just CRI?

Adding additional required PR jobs is quite expensive in terms of test latency and overall PR merge velocity. If a new suite won't catch failures more than 1% of the time, it's *probably* not worth doing it in a presubmit job.

**Comment by yujuhong** [comment]
@rmmh yes we have encountered those problems before. I think it's a necessary step since we are trying to roll out CRI as default in the 1.6 release, and we'd like to prevent any regression during the crunch time. It's likely that we'll remove these once the rollout is completed.
(By the way, these tests run every PR, but are not yet "required").

**Comment by rmmh** [comment]
OK. We might consider removing one of the GCI jobs to switch over to CRI as the default.

**Comment by yujuhong** [comment]
Closing this since CRI is enabled by default in most builds.
