### ISSUE TITLE
Stop using taint with key=dedicated to mark master node

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#36272]
@justinsb brought to my attention that folks have started using a taint with key "dedicated" for marking the master node. While I heartily endorse moving from "unschedulable" to using taints, please do not use key "dedicated" for this taint as we want to use it for the [dedicated nodes](https://github.com/kubernetes/kubernetes/blob/master/docs/design/taint-toleration-dedicated.md]) feature. Also, please make all taints namespaced. The discussion of the justification is here:
https://github.com/kubernetes/kubernetes/pull/31647#issuecomment-257972345

So for tainting the master node, I think we should use the same key as kops is using to label the master node, namely "role" (value is master). And we should use the `node.alpha.kubernetes.io` namespace. So the taint key for the master node should be `node.alpha.kubernetes.io/role` and the value can be `master` as before. (It's debatable whether the namespace should be scheduler.* or node.* but since some taints can trigger eviction, not just block scheduling, I think node.* is slightly better).

Places where it seems people are using taint key "dedicated" -- please change them as described above (since taints are alpha, backward compatibility is not guaranteed, so I don't feel too guilty about this):
* kubeadm (seems to be introduced here: https://github.com/kubernetes/kubernetes/pull/33262)
* kops: [here](https://github.com/kubernetes/kops/blob/d3f69496e410630c219fa8ea35032e5a22eb6991/protokube/pkg/protokube/tainter.go) and elsewhere

Places where it seems people are about to do this (please change the PR to use the taint key I mentioned above): #31647 #35901 #36236

If anyone knows of any other code that is doing this, please add to this issue.

Thanks and sorry for the inconvenience. But I think this will make the system more understandable in the long-run.

cc/ @lukemarsden @errordeveloper @mikedanese

**Comment by jbeda** [comment]
Linking to #39112 to try and pull all of this together.

**Comment by davidopp** [comment]
BTW taints and tolerations are moving to Beta in 1.6 and will start using a field instead of an annotation.

**Comment by philips** [comment]
@davidopp We need to fix the labels kops is using. See #39112.

**Comment by justinsb** [comment]
@davidopp can we do some speculative execution?  If we assume the node label is going to be `node-role.kubernetes.io/master=true`, can you confirm what the taint & tolerations should be?

**Comment by davidopp** [comment]
I would suggest just using the same taint key as you're using for the label.

Tolerations match against taints by key so there isn't a separate key for the toleration; it's just whatever the taint key is.

**Comment by justinsb** [comment]
AIUI the suggestion therefore is 

```
key: node-role.kubernetes.io/master
value: ""
effect: NoSchedule
```

https://github.com/kubernetes/kubeadm/issues/150#issuecomment-281115555

I'm not sure if that depends on #39112 getting resolved.

**Comment by luxas** [comment]
I don't know, but I'm gonna make a PR for kubeadm to use the above taint and master label nonetheless and I'll see if I get it merged

**Comment by luxas** [comment]
@mikedanese Yes https://github.com/kubernetes/kubernetes/pull/41835
