### ISSUE TITLE
Refactor kube-proxy to remove os conditional checks

### ISSUE THREAD

**Issue by jbhurat** [kubernetes/kubernetes#36277]
`cmd/kube-proxy/app/server.go` has few conditional checks based on underlying OS like `runtime.GOOS == "windows"`, refactor `server.go` to do it more abstractly by moving them to `_linux/_windows` files.

All the conditional checks are in `NewProxyServerDefault()` and `Run()` methods and one solution could be to move them to `_linux/_windows` files

**Comment by pires** [comment]
This should be post 1.5 when #36079 has been merged.

**Comment by pires** [comment]
Also, [make sure to update the new file headers](https://github.com/kubernetes/kubernetes/pull/36079#pullrequestreview-7315823).

**Comment by cmluciano** [comment]
can anyone in @kubernetes/sig-windows-bugs help with this?

**Comment by michmike** [comment]
cc: @bsteciuk

**Comment by bsteciuk** [comment]
It looks like this work was completed in #51064. Looking at master I'm not seeing any of the `runtime.GOOS == "windows"` checks in `cmd/kube-proxy` (aside from a couple in a test).
