### ISSUE TITLE
federation e2e broken as federation fails to come up

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#36287]
federation-up.sh is failing at
```
kubectl get -o=jsonpath svc/${FEDERATION_APISERVER_DEPLOYMENT_NAME} --template '{.status.loadBalancer.ingress[*].ip}'
```

with error:

```
error: error executing jsonpath "{.status.loadBalancer.ingress[*].ip}": ingress is not found
```

cc @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
This used to work fine. Not sure if something changed in the way kubectl get processes the template or the way loadBalancerStatus is set in service.

cc @janetkuo @bprashanth

**Comment by janetkuo** [comment]
@kubernetes/kubectl

**Comment by bprashanth** [comment]
status hasn't changed recently
```
beeps@bitrot:~/goproj/src/k8s.io/kubernetes$ k get svc echoheaders-lb -o
yaml | grep status -A 5
status:
  loadBalancer:
    ingress:
    - ip: 104.198.137.149
```

**Comment by janetkuo** [comment]
Yes I can do something like this 

```console
$ kubectl get -o jsonpath svc/guestbook --template '{.status.loadBalancer.ingress[*].ip}'
130.211.190.168
```

**Comment by nikhiljindal** [comment]
Still not sure what changed, but adding a wait to check that ingress field is set in {.status.loadbalancer} before checking {.status.loadBalancer.ingress[*].ip} fixes the problem.
Sent https://github.com/kubernetes/kubernetes/pull/36483 for that
