### ISSUE TITLE
Investigate kube-proxy sluggishness

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#36281]
We observed weird sluggishness in some kubeproxies while debugging https://github.com/kubernetes/kubernetes/issues/36266

**Comment by MrHohn** [comment]
Did a bit debug, found something related to the mutex lock contention between `OnServiceUpdate()` and `OnEndpointsUpdate()`. The situation observed was that `OnEndpointsUpdate()` seemed to have higher priority for gaining the lock. Since endpoints updates were coming constantly, `OnServiceUpdate()` waited for a long time before eventually gained the lock. Not sure why yet.

Logs as below:
```
...
I1106 00:14:02.280977       5 config.go:99] Calling handler.OnEndpointsUpdate()
...
I1106 00:14:02.280993       5 proxier.go:561] OnEndpointsUpdate took 646ns for mu.Lock()
...
I1106 00:14:03.135254       5 config.go:208] Calling handler.OnServiceUpdate()
...
I1106 00:14:03.501258       5 config.go:99] Calling handler.OnEndpointsUpdate()
...
I1106 00:14:03.501272       5 proxier.go:561] OnEndpointsUpdate took 811ns for mu.Lock()
...
I1106 00:14:05.579794       5 config.go:99] Calling handler.OnEndpointsUpdate()
...
I1106 00:14:05.579803       5 proxier.go:561] OnEndpointsUpdate took 602ns for mu.Lock()
...
# A bunch of other OnEndpointsUpdate() calls
...
I1106 00:14:35.458772       5 proxier.go:424] OnServiceUpdate took 32.323492967s for mu.Lock()
...
```

**Comment by bprashanth** [comment]
See https://github.com/kubernetes/kubernetes/pull/35334#issuecomment-258656168
We should just default to old behavior as a quick fix (i.e set throttle=nil and default minSync to 0: https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L264), till we can make it differentiate no-op from useful updates. We should just recognize and filter bogus updates, they're all from leader election:  https://github.com/kubernetes/kubernetes/issues/26637

**Comment by MrHohn** [comment]
Good theory. Found something really similar in golang/go#13086.
