### ISSUE TITLE
etcd3: does not include getOps in List call

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#36291]
The List function in the etcd implementation does not include getOps (but all the other read operations do).  I believe it should, because GetToList does:

https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/etcd3/store.go#L326

**Comment by hongchaodeng** [comment]
We are working on combining List() and GetToList() into one function.
Let me take this into account as well.

**Comment by logicalhan** [comment]
> /assign @logicalhan
> /triage accepted

I guess I deserve that.
