### ISSUE TITLE
Problems with certain etcd3 prefixes?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#36290]
I stumbled across this code in the etcd3 backend:

```
func keyWithPrefix(prefix, key string) string {
	if strings.HasPrefix(key, prefix) {
		return key
	}
	return path.Join(prefix, key)
}
```

This is mixing user-provided data with system-provided data, right?  So some values of the prefix will cause unexpected behaviour I think.  I haven't been able to find any validation that makes this safe (yet!)

**Comment by hongchaodeng** [comment]
> some values of the prefix will cause unexpected behaviour

Can you enumerate what are the cases?

>  I haven't been able to find any validation that makes this safe 

What kind of validation are you trying to do? Can you clarify?

I believe there is a system flag called "etcd-prefix" of apiserver. It's probably designed for multi-tenancy case.

But I definitely see the "if" statement is appalling:
```
	if strings.HasPrefix(key, prefix) {
		return key
	}
```
Which could be mixing user input and system data.

**Comment by liggitt** [comment]
We definitely shouldn't be "sometimes prefixing"… this should be removed and we should audit the callers to determine whether prefix is needed or not and apply appropriately

**Comment by liggitt** [comment]
Does the same function exist in etcd2?

**Comment by hongchaodeng** [comment]
@liggitt 
Yes. It existed in etcd2 called [prefixEtcdKey()](https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/etcd/etcd_helper.go#L543)

@timothysc @wojtek-t The "sometimes prefixing" logic doesn't seem reasonable here.
```
func keyWithPrefix(prefix, key string) string {
	if strings.HasPrefix(key, prefix) {
		return key
	}
	return path.Join(prefix, key)
}
```
If we removed it, it might cause potential compatibility issues. I think because we are in a process of making etcd3 by default, maybe we can add a note for user migrating to it, e.g. saying that "prefix is always prepeneded" etc.

**Comment by wojtek-t** [comment]
Agree - we should get rid of this if.

However, i agree that this is potentially "backward-incompatible" change (though with default settings (i.e. default registry prefix, etc.) it shouldn't cause any problems.

**Comment by hongchaodeng** [comment]
@justinsb 
All fixed. Could we close this?
