### ISSUE TITLE
git commit failed  on Macbook Pro

### ISSUE THREAD

**Issue by oulinbao** [kubernetes/kubernetes#36297]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
master branch in 2016-11-6

**Environment**:
- **Cloud provider or hardware configuration**:
macbook pro 2015
8G Memory, 256 SSD disk, cpu i5

- **OS** (e.g. from /etc/os-release):
mac OS X 10.11.6 (15G31)

- **Kernel** (e.g. `uname -a`):
Darwin bogon 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64- **Install tools**:

- **Others**:
None

**What happened**:
When I modify code and use 'git commit' cmd, error below happened. After I executed "hack/update-generated-swagger-docs.sh", the error still occur.

=============================================================
Checking for swagger type documentation that need updating... cp: illegal option -- T
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
!!! Error in hack/verify-generated-swagger-docs.sh:53
  'cp -a -T "${DIFFROOT}" "${TMP_DIFFROOT}"' exited with status 64
Call stack:
  1: hack/verify-generated-swagger-docs.sh:53 main(...)
Exiting with status 1
ERROR!
Swagger type documentation needs to be updated.
To regenerate the spec, run:
  hack/update-generated-swagger-docs.sh

**What you expected to happen**:
Commit code on Macbook pro normally.

**How to reproduce it** (as minimally and precisely as possible):
See above.

**Anything else do we need to know**:
None

**Comment by dims** [comment]
@oulinbao : this was fixed already in https://github.com/kubernetes/kubernetes/pull/34944 

Can you please close this issue?

**Comment by oulinbao** [comment]
OK, I will verify it and close it.
