### ISSUE TITLE
Two nodes with same name should not be allowed to be added using 'kubeadm join'

### ISSUE THREAD

**Issue by tonyclam** [kubernetes/kubernetes#36303]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
duplicate node name + "kubectl get nodes"
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`)
kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:42:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
kubeadm version
kubeadm version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.2.421+a6bea3d79b8bba", GitCommit:"a6bea3d79b8bbaa5e8b57482c9fff9265d402708", GitTreeState:"clean", BuildDate:"2016-11-03T06:54:50Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:x86_64 desktop
- **OS** (e.g. from /etc/os-release):ubuntu 16.04 LTS
- **Kernel** (e.g. `uname -a`):Linux ubuntu-2 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:kubeadm
- **Others**:

**What happened**:
We have two nodes, the master name was ubuntu-2 while the minion node was ubuntu-3.
kubectl get nodes
NAME       STATUS    AGE
ubunbu-3   Ready     10h
ubuntu-2   Ready     1d
If we add another node with same node name ubuntu-3, it just added without checking whether the node name had existed or not:
kubectl get nodes
NAME       STATUS    AGE
ubunbu-3   Ready     10h
ubuntu-2   Ready     1d
ubuntu-3   Ready     26m

**What you expected to happen**:
If we add node using 'kubeadm join' with node name already exists, we should return failed  with error messages: "duplicate node name" 

**How to reproduce it** (as minimally and precisely as possible):
1. kubeadm join (node with name ubuntu-3, for example)
2. In master node 'kubectl get nodes'
NAME       STATUS    AGE
ubunbu-3   Ready     10h
ubuntu-2   Ready     1d
3. Add another node with name ubuntu-3
NAME       STATUS    AGE
ubunbu-3   Ready     10h    <-----duplicate node name ubuntu-3
ubuntu-2   Ready     1d
ubuntu-3   Ready     26m   <------duplicate node name ubuntu-3
**Anything else do we need to know**:

**Comment by luxas** [comment]
Thanks for this issue, but we already have one issue open for this.

See: https://github.com/kubernetes/kubernetes/issues/36255
