### ISSUE TITLE
vSphere process (from "getting started" guide) broken due to govc issues

### ISSUE THREAD

**Issue by Symmetric** [kubernetes/kubernetes#3630]
I tried following the "getting started" guide on my system (Ubuntu 14.04, vSphere 5.5 w/ vCenter), and hit numerous bugs in the govc module that prevented the vcenter provider from working.

I've raised bugs over at the govc project for these issues:
- [import.vmdk command](https://github.com/vmware/govmomi/issues/204) (can workaround this by manually importing the VMDK)
- [vm.create command](https://github.com/vmware/govmomi/issues/205) (this issue breaks the kube VM startup script)

I could believe that these issues are specific to my topology and this guide is working for others, but I wanted to raise the issues here so that there's a reference to them in this project.

**Comment by jbeda** [comment]
Assigning to @pietern.  Peter?

**Comment by imkin** [comment]
Both the issues mentioned were closed. Can we please close this issue.
