### ISSUE TITLE
Eviction doesn't work well with clientset.

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes#36305]
`Eviction` doesn't work well with clientset.
`Eviction` lives in policy group, so we need a codec for policy group to encode it, the `versionedAPIPath` is `/apis/policy/v1beta1`.
But when we want to use [`Eviction` subresource](http://kubernetes.io/docs/admin/disruptions/#requesting-an-eviction), it should be POSTed to `/api/v1/namespaces/default/pods/podname/eviction` that start with a different API path.

Ref: #35483 

cc: @kubernetes/sig-api-machinery

**Comment by smarterclayton** [comment]
This is the same problem Scale has.

**Comment by caesarxuchao** [comment]
Yes, summarized in #36331. We currently work around this problem by using AbsPath().
