### ISSUE TITLE
[RFC] let RESTClient access subresourse accoss group boundary

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#36331]
**Problem**

In today's RESTClient, the group/version of the encoder and the group/version in the request url are coupled. It makes difficult for RESTClient to access subresources, such as `eviction` and `scale`, which have to work with resources defined in other group/versions.

To clarify, this is a problem only for the internalclientset, which needs an encoder to convert the object to a specific group/version. It's not a problem for the versioned clientset, whose encoder only needs to passively serialize the object.

**Proposed solution**

Add a `groupVersion` field to the [Request struct](https://github.com/kubernetes/kubernetes/blob/v1.5.0-beta.0/pkg/client/restclient/request.go#L86). It will be assembled in the url. Its value is default to the RESTClient's [versionedAPIPath](https://github.com/kubernetes/kubernetes/blob/v1.5.0-beta.0/pkg/client/restclient/client.go#L65), and can be modified via a GroupVersion() method. To make it work, we need to

* defer joining the [pathPrefix](https://github.com/kubernetes/kubernetes/blob/v1.5.0-beta.0/pkg/client/restclient/request.go#L137)
* record the prefix segments set via Prefix(), defer [joining](https://github.com/kubernetes/kubernetes/blob/v1.5.0-beta.0/pkg/client/restclient/request.go#L155-L161) them with the pathPrefix.

**References** 
* issue with eviction (#36305)
* how `scale` works with `RC`(https://github.com/kubernetes/kubernetes/pull/35483#discussion_r86699245).

@kubernetes/sig-api-machinery @liggitt @smarterclayton @ymqytw

**Comment by deads2k** [comment]
Shouldn't we be able to use the information we have in the clientset to run a discovery check against the scale API in question and determine version?  Run in once, cache the result (it's not allowed to change) and we can encode properly without user input, right?

**Comment by caesarxuchao** [comment]
> we can encode properly without user input, right?

The user is kubectl. kubectl should negotiate with server what group/version to use in the url, then pass the group/version to clientset, right?

**Comment by smarterclayton** [comment]
I'm wondering if we should not just have scale accept the group it is embedded in, and let clients that need a specific schema do so via the schema negotiation proposal.

Ie register scale into all group versions, and generic scale clients should use the server version negotiation to get a specific form.  That would at least ensure that we have exactly one mechanism for dealing with versioned clients (schema is locked when we release) and generic clients like HPA should be using server version negotiation to get a known set of accepted responses.  There are client version incompatibility here, but it would reduce the amount of special case behavior for subresources

**Comment by deads2k** [comment]
> Ie register scale into all group versions, and generic scale clients should use the server version negotiation to get a specific form. That would at least ensure that we have exactly one mechanism for dealing with versioned clients (schema is locked when we release) and generic clients like HPA should be using server version negotiation to get a known set of accepted responses. There are client version incompatibility here, but it would reduce the amount of special case behavior for subresources

I don't understand how this works client side.  Say I have two known external scale go objects. `pkg/v1/Scale` and `pkg/v2/Scale`.  Those get cross registered as `Scale.v1.foo` and `Scale.v1.bar` respectively.  A client which has the two go types registered, but not the groups (external API server) does a GET `/apis/foo/v1/namespaces/ns/thing/name/scale` and gets back a `Scale.v1.foo`.  Which go type does he deserialize into and how did he know which one it was.
