### ISSUE TITLE
kubelet print log out-of-sequence

### ISSUE THREAD

**Issue by AlexMioMio** [kubernetes/kubernetes#36341]
when i try to debug kubelet，i find kubelet log is out-of sequence.It made me confused for one hour. Can kubelet print log in chronological order? Or kubelet have trouble in log outputing? thx
------------------------------------------------------------------------------------
38.45:5443: getsockopt: connection refused
E1105 10:29:53.995822    4789 reflector.go:216] pkg/kubelet/kubelet.go:1230: Failed to list *api.ConfigMap: Get https://3.0.38.45:5443/api/v1/namespaces/cse-system/configmaps?resourceVersion=0: net/http: TLS handshake timeout
E1105 10:29:54.088160    4789 reflector.go:205] pkg/kubelet/kubelet.go:279: Failed to list *api.Service: Get https://3.0.38.45:5443/api/v1/namespaces/cse-system/services?resourceVersion=0: net/http: TLS handshake timeout
E1105 10:29:54.555772    4789 reflector.go:315] pkg/kubelet/config/apiserver.go:43: Failed to watch *api.Pod: Get https://3.0.38.45:5443/api/v1/watch/namespaces/cse-system/pods?fieldSelector=spec.nodeName%3D3.0.38.48&resourceVersion=125071&timeoutSeconds=395: net/http: TLS handshake timeout
E1105 10:29:54.741713    4789 reflector.go:216] pkg/kubelet/kubelet.go:303: Failed to list *api.Node: Get https://3.0.38.45:5443/api/v1/namespaces/cse-system/nodes?fieldSelector=metadata.name%3D3.0.38.48&resourceVersion=0: net/http: TLS handshake timeout
E1105 10:29:57.904877    4789 kubelet.go:3241] Error updating node status, will retry: error getting node "3.0.38.48": Get https://3.0.38.45:5443/api/v1/namespaces/cse-system/nodes/3.0.38.48: net/http: TLS handshake timeout
E1105 10:30:04.996551    4789 reflector.go:216] pkg/kubelet/kubelet.go:1230: Failed to list *api.ConfigMap: Get https://3.0.38.45:5443/api/v1/namespaces/cse-system/configmaps?resourceVersion=0: net/http: TLS handshake timeout
E1105 10:30:05.088784    4789 reflector.go:205] pkg/kubelet/kubelet.go:279: Failed to list *api.Service: Get https://3.0.38.45:5443/api/v1/namespaces/cse-system/services?resourceVersion=0: net/http: TLS handshake timeout
E1105 10:30:05.556644    4789 reflector.go:205] pkg/kubelet/config/apiserver.go:43: Failed to list *api.Pod: Get https://3.0.38.45:5443/api/v1/namespaces/cse-system/pods?fieldSelector=spec.nodeName%3D3.0.38.48&resourceVersion=0: net/http: TLS handshake timeout
E1105 10:30:05.742468    4789 reflector.go:216] pkg/kubelet/kubelet.go:303: Failed to list *api.Node: Get https://3.0.38.45:5443/api/v1/namespaces/cse-system/nodes?fieldSelector=metadata.name%3D3.0.38.48&resourceVersion=0: net/http: TLS handshake timeout
E1105 09:40:01.594246    4789 kubelet.go:3241] Error updating node status, will retry: error getting node "3.0.38.48": Get https://3.0.38.45:5443/api/v1/namespaces/cse-system/nodes/3.0.38.48: net/http: TLS handshake timeout
E1105 09:40:09.686023    4789 reflector.go:216] pkg/kubelet/kubelet.go:1230: Failed to list *api.ConfigMap: Get https://3.0.38.45:5443/api/v1/namespaces/cse-system/configmaps?resourceVersion=0: net/http: TLS handshake timeout
E1105 09:40:09.778134    4789 reflector.go:205] pkg/kubelet/kubelet.go:279: Failed to list *api.Service: Get https://3.0.38.45:5443/api/v1/namespaces/cse-system/services?resourceVersion=0: net/http: TLS handshake timeout
E1105 09:40:10.246199    4789 reflector.go:205] pkg/kubelet/config/apiserver.go:43: Failed to list *api.Pod: Get https://3.0.38.45:5443/api/v1/namespaces/cse-system/pods?fieldSelector=spec.nodeName%3D3.0.38.48&resourceVersion=0: net/http: TLS handshake timeout
E1105 09:40:10.431856    4789 reflector.go:216] pkg/kubelet/kubelet.go:303: Failed to list *api.Node: Get https://3.0.38.45:5443/api/v1/namespaces/cse-system/nodes?fieldSelector=metadata.name%3D3.0.38.48&resourceVersion=0: net/http: TLS handshake timeout
W1105 09:41:39.636119    4789 container_manager_linux.go:573] CPUAccounting not enabled for pid: 1981
W1105 09:41:39.636144    4789 container_manager_linux.go:576] MemoryAccounting not enabled for pid: 1981
I1105 09:41:39.636159    4789 container_manager_linux.go:284] Discovered runtime cgroups name: /system.slice/docker.service
W1105 09:41:39.636200    4789 container_manager_linux.go:573] CPUAccounting not enabled for pid: 4789
W1105 09:41:39.636207    4789 container_manager_linux.go:576] MemoryAccounting not enabled for pid: 4789
W1105 09:46:39.636407    4789 container_manager_linux.go:573] CPUAccounting not enabled for pid: 1981
W1105 09:46:39.636428    4789 container_manager_linux.go:576] MemoryAccounting not enabled for pid: 1981
I1105 09:46:39.636436    4789 container_manager_linux.go:284] Discovered runtime cgroups name: /system.slice/docker.service
W1105 09:46:39.636486    4789 container_manager_linux.go:573] CPUAccounting not enabled for pid: 4789

**Comment by AlexMioMio** [comment]
@anguslees

**Comment by anguslees** [comment]
(Why was I added to this?)

My first thought is: that is oddly close to an exact hour jump and everyone going through DST changes. Except it wasn't on an hour boundary so that's probably a red herring.
