### ISSUE TITLE
Service update should not require setting clusterIP

### ISSUE THREAD

**Issue by steve-wolter** [kubernetes/kubernetes#36347]
**Kubernetes version** (use `kubectl version`): 1.4.4

**Environment**:
- **Cloud provider or hardware configuration**: Google GKE

**What happened**:

When I push an update for a K8s Service object through the API via Google's Deployment Manager, it fails because the clusterIP and resourceVersion fields are not provided. This is unexpected because the clusterIP is optional during creation and generally not known to the user's upstream automation. 

**What you expected to happen**:

Kubernetes should take the clusterIP from the current configuration. resourceVersion as well, ideally.

**How to reproduce it** (as minimally and precisely as possible):

1. Create a minimal service. I used:

    apiVersion: v1
    kind: Service
    metadata: {name: nginx-service}
    namespace: default
    spec:
      ports:
      - {name: http, nodePort: 31214, port: 80, protocol: TCP}
      - {name: https, nodePort: 31215, port: 443, protocol: TCP}
      selector: {app: shield}
      type: NodePort

2. Try to update it through the API. I used:

    apiVersion: v1
    kind: Service
    metadata: {name: nginx-service}
    namespace: default
    spec:
      ports:
      - {name: http, nodePort: 31214, port: 80, protocol: TCP}
      - {name: https, nodePort: 31215, port: 443, protocol: TCP}
      - {name: https8080, nodePort: 31216, port: 8080, protocol: TCP}
      selector: {app: shield}
      type: NodePort

**Anything else do we need to know**:

Google's Deployment Manager might try to implement support for the current (broken) API, see https://buganizer.corp.google.com/issues/31256477.

**Comment by bgrant0607** [comment]
@steve-wolter We're not changing PUT semantics. Will discuss on the buganizer issue, though only post such links to github if you plan to make the bugs publicly visible.
