### ISSUE TITLE
Cluster nodes provisioned by Kubeadm. After power cycle the master node, master lost track of the all clusters

### ISSUE THREAD

**Issue by tonyclam** [kubernetes/kubernetes#36382]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
power cycle kubernetes master, reset kubernetes master

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:42:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
kubeadm version
kubeadm version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.2.421+a6bea3d79b8bba", GitCommit:"a6bea3d79b8bbaa5e8b57482c9fff9265d402708", GitTreeState:"clean", BuildDate:"2016-11-03T06:54:50Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: x86_64
- **OS** (e.g. from /etc/os-release):ubuntu 16.04 LTS
- **Kernel** (e.g. `uname -a`):Linux ubuntu-2 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubeadm
- **Others**:

**What happened**:
Before power cycle the master:
kubectl get nodes
NAME STATUS AGE
ubunbu-3 Ready 10h
ubuntu-2 Ready 1d
ubuntu-4 Ready 26m

**What you expected to happen**:
After power cycle the master node:
kubectl get nodes
NAME STATUS AGE
ubunbu-3 Ready 10h
ubuntu-2 Ready 1d
ubuntu-4 Ready 26m

**How to reproduce it** (as minimally and precisely as possible):
1. kubectl get nodes on master, it should show all the clusters including the master
2. power cycle the master node
3. kubectl get nodes on master
4. the cluster nodes disappeared
**Anything else do we need to know**:

**Comment by luxas** [comment]
@tonyclam Please try kubeadm v1.6 out and see if it fixes this issue.
If the issue still exists, please reopen this issue in the kubeadm repo: https://github.com/kubernetes/kubeadm/issues
