### ISSUE TITLE
CRI: Change fluentd to use CRI log path

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#36401]
Today kubelet creates symlink for docker container log for cluster logging to consume [[Corresponding fluentd configuration](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-image/google-fluentd.conf#L28-L44)]. The symlink is from `/var/lib/docker/containers/CONTAINERID/CONTAINERID-json.log` to `/var/log/containers/PODNAME_PODNAMESPACE_CONTAINERNAME-CONTAINERID.log`. 

In CRI, we defined the new log path `/var/log/pods/PODUID/CONTAINERNAME_RESTARTCOUNT.log`. Even though we are still creating the old symlink in CRI integration for backward compatibility, we should change fluentd to also look at the new log path, and eventually deprecated the old container log path.

@yujuhong @feiskyer 
/cc @kubernetes/sig-node

**Comment by feiskyer** [comment]
@Random-Liu Does fluentd need to understand different log formats, e.g. CRI supports `Docker JSON log format` and `CRI log format` currently.

**Comment by Random-Liu** [comment]
@feiskyer Yeah, you are right. (See [here](
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-image/google-fluentd.conf#L74-L75))
```
format /^(?<time>[^ ]* [^ ,]*)[^\[]*\[[^\]]*\]\[(?<severity>[^ \]]*) *\] (?<message>.*)$/
time_format %Y-%m-%d %H:%M:%S
```

If so, we need to teach fluentd to understand cri  log formats.
I'm not familiar with fluentd. I don't know whether we can teach fluentd to support 2 different formats from 1 log path in the same config file.

**Comment by Crassirostris** [comment]
Let me make one step back to talk about the whole picture

We had some discussions and planned to work on refactoring the whole logging process in the next iteration, will it wait until then (I'm not sure whether you're talking about long-distance planning or something that will be changed next week)?

We have some really kubelet-dependent ideas, for example, strictly specified and documented interface for logs, which would include storing pod metadata somewhere; capturing arbitrary log files from containers, not only stdout/stderr; avoiding message wrapping and so on. What about scheduling a meeting on this topic after 1.5 release?

**Comment by yujuhong** [comment]
@Crassirostris this issue focuses on the smaller scope of supporting yet another format/location for container logs. I agree that in general we should have a better defined log interface, but that demands a broader discussion and design, and maybe even longer rollout timeline. Could we resolve this issue before that happen?

**Comment by Crassirostris** [comment]
I didn't want to address this issue directly, because it has also a problem besides logging format

> In CRI, we defined the new log path `/var/log/pods/PODUID/CONTAINERNAME_RESTARTCOUNT.log`.

Fluentd right now _heavily_ relies on the metadata from the filename, you can't just remove pod name, namespace name and so on without completely breaking current logging pipeline.

Regarding the original problem, there is a plugin for this: https://github.com/repeatedly/fluent-plugin-multi-format-parser.

**Comment by Crassirostris** [comment]
But again, I think making such changes before the logging pipeline rework might not be a best solution.

**Comment by yujuhong** [comment]
@Crassirostris thanks for the input!

> Fluentd right now heavily relies on the metadata from the filename, you can't just remove pod name, namespace name and so on without completely breaking logging pipeline.

Does the fluentd itself rely on the metdata, or the downstream components (e.g., elasticsearch) does this? I didn't see any relevant information in the fluentd configuration files.

**Comment by Crassirostris** [comment]
Not fluentd per se, but of the plugins from the configuration. By default, this plugin for ingesting read logs to the GCL: https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud

It's even harder to change than fluentd configuration per se, because guys from Stackdriver team has their own release cycle.

**Comment by jcantrill** [comment]
cc @portante, @richm

**Comment by crassirostris** [comment]
@yujuhong @Random-Liu We should probably have a plan for this migration. People should have enough time to move away from the old naming scheme, but should move nevertheless.

I think defining the guidelines for people to use, like https://github.com/kubernetes/kubernetes/issues/42718, is a first important step here. Then the most popular solutions, relying on this, e.g. [fluent-plugin-kubernetes_metadata_filter](https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter), should follow. And then, after some time it will be safe to deprecate old paths.

**Comment by kfox1111** [comment]
its unclear from: https://github.com/kubernetes/community/blob/master/contributors/devel/container-runtime-interface.md#kubernetes-v16-release-docker-cri-integration-beta

if the link to this issue is a 1.5 only thing, or applies to 1.6 too. since cri is now default in 1.6, is it broken by default with respect to this kind of logging?

**Comment by crassirostris** [comment]
@kfox1111 It's still not supported by external tools. It's not strictly broken, because legacy symlinks are still created, but we can't get rid of them them any time soon.

**Comment by kfox1111** [comment]
Ah, ok. Thanks.

**Comment by yujuhong** [comment]
> @kfox1111 It's still not supported by external tools. It's not strictly broken, because legacy symlinks are still created, but we can't get rid of them them any time soon.

@crassirostris, if we change the filename to be the same as the legacy ones (including name, namespace, etc.). Will that at least help us use the new paths? If we can address this sooner and allow other CRI integration to work with the existing logging pipelines, we should try doing that.

**Comment by crassirostris** [comment]
@yujuhong Are we talking about changing the CRI log path to contain some metadata? I really like the idea of the new path with only minimum amount of information

> If we can address this sooner and allow other CRI integration to work with the existing logging pipelines, we should try doing that.

Sorry, I'm not sure I get it. Do you want to remove the legacy filename in 1.7? What is the deprecation policy for this particular thing exactly, how long do we have to keep it around?

**Comment by Random-Liu** [comment]
Just a status update. We've changed fluentd to consume CRI log format https://github.com/kubernetes/kubernetes/pull/54777, which is part of this issue.

However fluentd is still looking at the old container log path.

**Comment by amiga23** [comment]
This issue is now 3.5 years old, but I can not find any documentation about fluentd and containerd/cri-o. Could you please advise?

**Comment by fromanirh** [comment]
it seems partially addressed. To fully resolve, please file a new issue describing what's missing (and possibly reference this one for context)
/close
