### ISSUE TITLE
No port forwarding test in the node e2e suite

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#36400]
The test should also be added to the node conformance test.

/cc @Random-Liu

**Comment by Random-Liu** [comment]
@yujuhong It's in the spreadsheet https://docs.google.com/spreadsheets/d/1qV38BesOaH70bzd_7g_YgUzpI4dZetGwxljL-saUVzw/edit.

Cluster e2e is using kubectl to test port forwarding. If we want to test it, we need to extract the logic out and add it into framework util like what we've done for exec.

**Comment by dshulyak** [comment]
I will add this tests node e2e suite

**Comment by Random-Liu** [comment]
@dshulyak Thanks a lot! Please note that we don't want to use kubectl in node e2e. You may want to add some simple library as `exec_util` for port forward. https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/exec_util.go

**Comment by dshulyak** [comment]
@Random-Liu thanks for suggestion, i added utility module for port forwarding based on rest client. Also i refactored existing e2e tests a bit, so that i can reuse them in node e2e suite. I will be grateful if you can confirm thats it is correct idea

**Comment by yujuhong** [comment]
We should have a UDP test too (see #43365).

**Comment by SergeyKanzhelev** [comment]
/sig network

Anybody from sig network wants to take this? Also I think dockershim port forwarding logic will be removed with dockerrshim so do we need it here?

**Comment by sladyn98** [comment]
Any tips on how to begin, or where can I find a similar test to look off of

**Comment by sladyn98** [comment]
Requires more information on detailed steps to reproduce.

**Comment by SergeyKanzhelev** [comment]
port forwarding is part of CNI. I think we need to add e2e test, likely conformance, that will ensure that if port forwarding was requested by container, it will be set up.

/reopen

**Comment by sladyn98** [comment]
@SergeyKanzhelev thanks I can give it a shot, any examples that I can follow in the codebase

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev thanks I can give it a shot, any examples that I can follow in the codebase

Something like https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/hostport.go as a way to spin up the container. Then you need to send the portforward API request and get the websocket as a result. And try to call something using it. Quite involved. And it is likely will need to be done in sig network. So let me remove sig node

/remove-sig node
