### ISSUE TITLE
E2E: Kibana e2e test is not working

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#36402]
The test `Kibana Logging Instances Is Alive [Feature:Elasticsearch]` is not working properly now.

When we check test-grid, we'll see that the test is all green https://k8s-testgrid.appspot.com/google-gce#gci-gce-es-logging.

However, when we check the test build log, we'll see the following error log until the test timeout:
```
[1mSTEP[0m: Checking to make sure we get a response from the Kibana UI.
Nov  7 15:55:26.763: INFO: After 6.978262ms proxy call to kibana-logging failed: an error on the server ("Error: 'dial tcp 10.180.2.2:5601: getsockopt: connection refused'\nTrying to reach: 'http://10.180.2.2:5601/'") has prevented the request from succeeding (get services kibana-logging)
Nov  7 15:55:31.771: INFO: After 5.014839068s proxy call to kibana-logging failed: an error on the server ("Error: 'dial tcp 10.180.2.2:5601: getsockopt: connection refused'\nTrying to reach: 'http://10.180.2.2:5601/'") has prevented the request from succeeding (get services kibana-logging)
Nov  7 15:55:36.779: INFO: After 10.022301548s proxy call to kibana-logging failed: an error on the server ("Error: 'dial tcp 10.180.2.2:5601: getsockopt: connection refused'\nTrying to reach: 'http://10.180.2.2:5601/'") has prevented the request from succeeding (get services kibana-logging)
```

However, because the test code itself is wrong, the test can still pass. 
In the code, [`GetServicesProxyRequest` keeps failing and throwing out `errProxy`, but the test doesn't check the error after timeout, so the test can still pass](https://github.com/kubernetes/kubernetes/blob/d76650ad40b44e0deaee25fb29c8bb95c6ef7d71/test/e2e/kibana_logging.go#L83-L98).

I don't even know whom to notify, just @kubernetes/sig-cluster-lifecycle for now.

**Comment by piosz** [comment]
@Crassirostris could you please take a look? Thanks!

**Comment by Crassirostris** [comment]
Yes, that is true, thanks for noticing!

Failing to connect for some time is OK, it's explained in https://github.com/kubernetes/kubernetes/pull/36192 but I agree that the test is broken anyway
