### ISSUE TITLE
GCE: Reduce the frequency of calls to "compute.instances.get" API

### ISSUE THREAD

**Issue by dcarney** [kubernetes/kubernetes#3643]
The current default free quota for requests to the GCE API is 250,000 requests/day.

We're finding that we easily exceed that when attempting to run a k8s cluster with 20 or more minions.

Some numbers for reference (pulled from the GCE console):

20 minions ~ 3.2 /sec ~ 276K requests/day to "compute.instances.get", which exceeds the daily quota
12 minions ~ 2.1 /sec ~ 181K requests/day

We're running k8s v0.8.1 FWIW.

The number of calls to the other GCE API methods pales in comparison, with compute.instances.get making up ~95% of all the API traffic:

method | count | %
-----------|---------|-----
 compute.instances.get | 960,002 | 95.2%
 compute.instances.list | 33,347 | 3.3%
 compute.zones.list | 6,050 | 0.6%
 ... | ... | ...

We've scaled down the number of minions for now, until we either request a quota increase, or the API call frequency is reduced somewhat.

**Comment by erictune** [comment]
@ddysher can you look at the minion controller and see if it is doing anything silly that might cause it to send so many requests?

**Comment by erictune** [comment]
Hmm.  thinking about this more, if the rate is higher with more minions, then this may be something on the minions rather than in controller manager.  I'll take a look.

**Comment by erictune** [comment]
The three places I can see we call compute.instances.get are in `Instances.GetNodeResources`, `Instances.IPAddress` and `Instances.AttachDisk`.

**Comment by erictune** [comment]
worklog:
`GetNodeResources` just gets called from `cloudNodes` in `pkg/cloudprovider/controller/nodecontroller.go`.
which is called by `SyncCloud` in that file.
which is called in a `util.Forever` loop in that file with period of every 10 seconds.
So, unless the period is somehow wrong, that doesn't seem like it would be the problem.

**Comment by erictune** [comment]
`IPAddress` is used by nodecontroller in the same 10-second loop.

**Comment by dcarney** [comment]
I think we're doing the exact same grepping.  :-)

**Comment by erictune** [comment]
I take back what I said before.
At 24 hours a day, 60 minutes an hour, and 6 10-second periods per hour, that would be 8640 `SyncCloud` calls per day.
At 20 minions, with one call to IPAddress and one to GetNodeResources resulting in 2 calls each, you get 345600 calls per day.  That is significant.

**Comment by erictune** [comment]
The quickest thing would be for me to put together a PR to make the period flag controllable in cmd/kube-controller-manager/controller-manager.go.

**Comment by erictune** [comment]
The one concern I have about lowering that rate is that if we make it wait, say, 60 seconds between `SyncCloud` calls, then will it take up to a minute for a cluster to come up?  That would be bad for our e2e testing.

Possible improvements:
  - gradually increase period from 10s to 60s after restart of node controller.
  - keep listing 10-second-ly, but if the list of names is the same, then only check for different ip address or resources every nth time.  If it is different, always check at least the newly added minions.

**Comment by erictune** [comment]
@dcarney if I put together a PR, are you readily able to build and deploy a binary from head to verify the fix?

**Comment by erictune** [comment]
`IPAddress` also gets called by the apiserver's `NewIPCache` 30-secondly.  That would account for 57600 calls per day at 20 minions.

**Comment by dcarney** [comment]
@erictune Sure.  I'll have to coordinate the cluster downtime/switchover (since it's a working cluster) to test it out.

**Comment by erictune** [comment]
The `AttachDisk` does not appear to do a get in the normal case.  If could do a lot of some minions were stuck in loops where they repeatedly failed to attach PDs.  Assume that isn't the case right now.

**Comment by dcarney** [comment]
@erictune Correct.  The PDs we do have in the cluster right now are successfully attached.

**Comment by erictune** [comment]
Thinking about this more, I think a flag is a good fix for the near future:
  - longer lags make debugging harder.  better to at least make it more obvious when a longer lag is introduced. 
  -  changing the check interval will interact with any horizontal or vertical auto-scaling that may be added in the future, as well as dealing with node reboots, device attaches, etc.  It is not obvious that list-often get-less-often heuristic works with all those cases.
  - until we have a better fix, like higher GCE free quotas or a watch interface, users will have to make cheap vs fast tradeoff.
  - flag-controlled interval should work with all cloud providers.  List vs Get distinction may not exist for all.

**Comment by erictune** [comment]
I'll get to this later today or tomorrow.

**Comment by ddysher** [comment]
@erictune I think flag controlled period works for now, do you want me to put a PR for this?

The syncing procedure will 1. monitor the number of minions in cluster, and 2. keep their info up to date.  The first function should have a higher priority for k8s to be responsive, and the second one is not that important as a node resources / ipaddress won't that so frequent.

Apart from flag control, I'd want to cache the node resources / ipaddress information in controller.  We still keep the sync time to 10s, but make the cache expire time to be n times sync-time.  So we have a fast cluster bootstrap and new node registration (cache empty), while also restrict calls to cloud provider.

I'd really like a watch interface from gce BTW.

**Comment by erictune** [comment]
Yes, please do put out a PR for just the flag to stop the hurting.  And
then let's talk with internal folks about what the prospects are for higher
quota or watch,  And then design something smarter in the minion controller
if necessary.

**Comment by ddysher** [comment]
SGTM

**Comment by alex-mohr** [comment]
@ddysher are you still looking at this?  if not, could you please summarize and unassign?

**Comment by ddysher** [comment]
Yeah, it's still relavant to what i'm working on, but a little bit of summary here.  We have different syncs:

##### Sync Node From CloudProvider
This sync is to make sure k8s nodes are kept in sync with VMs in cloudprovider.  The frequency is controlled by flag "node_sync_period", default is 10s.   Every 10s, we call:
* cloud.Instances()  x 1
* instances.GetNodeResources() x NumberOfNodes
* instances.ExternalID() x NumberOfNodes

##### Sync Node Status
When k8s operates in *pull mode*, node controller keeps polling node status from kubelet, as well as other status information from cloudprovider.  The frequency is controlled by flag "node_sync_period", default is 10s.   Every 10s, we call:
* cloud.Instances()  x 1
* instances.NodeAddresses() x NumberOfNodes

##### Sync Node Status
When k8s operates in *push mode*, node controller monitors node status posted from kubelet, so it will not contact cloudprovider.  However, this means node addresses will never be updated.

The direction is to have kubelet post node status; so a lot of calls to cloudprovider will be eliminated.  I'll keep the thread updated.

As to other places calling cloudproviders, I think I've removed them, unless we recently added some.

**Comment by gmarek** [comment]
I believe it's obsolete. Please reopen if I'm mistaken.
