### ISSUE TITLE
vSphere minion network routes do not persist through VM restart

### ISSUE THREAD

**Issue by kcrawley** [kubernetes/kubernetes#36440]
**Is this a request for help?**: No

**What keywords did you search in Kubernetes issues before filing this one?**: vSphere, networking

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Kubernetes version** (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: vSphere
- **OS** (e.g. from /etc/os-release): `Debian GNU/Linux 8 (jessie)`
- **Kernel** (e.g. `uname -a`): `Linux kubernetes-minion-3 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) x86_64 GNU/Linux`
- **Install tools**: `cluster/kube-up.sh`
- **Others**: n/a

**What happened**:

Prior to forcefully restarting the minion VM (increasing disk space), the network routing table was defined as:

```
root@kubernetes-minion-3:/home/kube# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.20.144.1    0.0.0.0         UG    0      0        0 eth0
10.244.0.0      172.20.144.98   255.255.255.0   UG    0      0        0 eth0
10.244.1.0      0.0.0.0         255.255.255.0   U     0      0        0 cbr0
10.244.2.0      172.20.144.202  255.255.255.0   UG    0      0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.20.144.0    0.0.0.0         255.255.255.0   U     0      0        0 eth0
```

after:

```
root@kubernetes-minion-3:/home/kube# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.20.144.1    0.0.0.0         UG    0      0        0 eth0
10.244.1.0      0.0.0.0         255.255.255.0   U     0      0        0 cbr0
172.20.144.0    0.0.0.0         255.255.255.0   U     0      0        0 eth0
```

**What you expected to happen**:

Route tables should be stored in etcd (maybe?) and applied upon reconnecting to the master node || flanneld

**How to reproduce it** (as minimally and precisely as possible):

Start up a cluster, reboot a minion.

**Anything else do we need to know**:

This makes me sad :(

**Comment by kcrawley** [comment]
tagging @kerneltime

**Comment by kerneltime** [comment]
@kcrawley me as well. Kube-up as of now is good enough to try out k8s but not production ready. We are looking into kube-anywhere as well as a more permanent solution for deploying.
