### ISSUE TITLE
Nodes not be scheduled across zones as expected

### ISSUE THREAD

**Issue by Stono** [kubernetes/kubernetes#36456]
Hi, as per http://kubernetes.io/docs/admin/multiple-zones/#pods-are-spread-across-zones it says `Pods in a replication controller or service are automatically spread across zones. ` and then goes onto giving the example of the guestbook being spread across three zones/

However, as you can see below, I have four nodes, 2 in each zone.  The zones are europe-west1-c and europe-west1-d.

I deploy a service (rabbitmq) with replicas=2, and they get deployed to separate nodes however do not get deployed to separate zones, they're deployed to the nodes in europe-west1-d only.

There are no PVC's associated with this service so nothing that should be keeping them both in -d.

This isn't optimal for what I am trying to achieve, and would like one node in c and one in d, and that is how I read the documentation and how I expected this to work?

I'm on kubernetes 1.4.5 on GKE

```
$ k get nodes --show-labels
NAME                                                STATUS    AGE       LABELS
gke-peopledata-preprod-default-pool-5fc70dbf-52ms   Ready     2h        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=n1-standard-2,beta.kubernetes.io/os=linux,cloud.google.com/gke-nodepool=default-pool,failure-domain.beta.kubernetes.io/region=europe-west1,failure-domain.beta.kubernetes.io/zone=europe-west1-c,kubernetes.io/hostname=gke-peopledata-preprod-default-pool-5fc70dbf-52ms
gke-peopledata-preprod-default-pool-5fc70dbf-a9zj   Ready     2h        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=n1-standard-2,beta.kubernetes.io/os=linux,cloud.google.com/gke-nodepool=default-pool,failure-domain.beta.kubernetes.io/region=europe-west1,failure-domain.beta.kubernetes.io/zone=europe-west1-c,kubernetes.io/hostname=gke-peopledata-preprod-default-pool-5fc70dbf-a9zj
gke-peopledata-preprod-default-pool-87a32dda-e2iz   Ready     2h        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=n1-standard-2,beta.kubernetes.io/os=linux,cloud.google.com/gke-nodepool=default-pool,failure-domain.beta.kubernetes.io/region=europe-west1,failure-domain.beta.kubernetes.io/zone=europe-west1-d,kubernetes.io/hostname=gke-peopledata-preprod-default-pool-87a32dda-e2iz
gke-peopledata-preprod-default-pool-87a32dda-rmgz   Ready     2h        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=n1-standard-2,beta.kubernetes.io/os=linux,cloud.google.com/gke-nodepool=default-pool,failure-domain.beta.kubernetes.io/region=europe-west1,failure-domain.beta.kubernetes.io/zone=europe-west1-d,kubernetes.io/hostname=gke-peopledata-preprod-default-pool-87a32dda-rmgz

$ kt describe pod -l app=rabbitmq | grep Node
Node:		gke-peopledata-preprod-default-pool-87a32dda-e2iz/10.34.96.5
Node:		gke-peopledata-preprod-default-pool-87a32dda-rmgz/10.34.96.4
```

**Comment by kargakis** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by bsalamat** [comment]
@Stono Your understanding from the the documentation is right. I am a bit surprised by the result that you are observing. We have tests that check the exact scenario that you described:
https://github.com/kubernetes/kubernetes/blob/v1.4.5/plugin/pkg/scheduler/algorithm/priorities/selector_spreading_test.go#L418
Are you sure that all the service pods have the same label and you do not have any other rules for pods that may keep them in the same zone?

**Comment by bsalamat** [comment]
@Stono Thanks for the information. There seems to be an issue with spreading the pots. One more question: please make sure that you do not provide node names in your pod spec. It is unlikely that you do, but possible.

**Comment by davidopp** [comment]
The way the Kubernetes scheduler chooses the node for a pod is by combining a lot of different factors. It's possible that the nodes are not all the same with respect to these other factors, and thus the pods are not spread across zones. One option is to add preferredDuringSchedulingIgnoredDuringExecution pod anti-affinity with selector matching the labels of this collection of pods TopologyKey == "failure-domain.beta.kubernetes.io/zone"

**Comment by davidopp** [comment]
Of course the previous suggestion just adds a little more weight to the spreading criteria; it might still be overwhelmed by other differences between nodes. The only way to guarantee separate zones is to use requiredDuringSchedulingIgnoredDuringExecution pod anti-affinity, but that will run exactly one pod per zone, which you presumably don't want.

We are certainly open to other ideas about how to weight the different factors that go into deciding which node a pod should schedule to. Right now we give them all the factors weight. @bsalamat is working on a feature that will let you configure the weights using a ConfigMap, so you could give more weight to spreading.

BTW there may be some other reason your pods aren't getting spread -- I'm just saying this is one possibility.

**Comment by Stono** [comment]
@davidopp Thanks for your response around weighting, totally makes sense.  I think a nice feature enhancement would be to give people the ability to "weight the weights", for example being able to say redundancy across machines is the most important property for a given deployment.

Anyway; we could probably close this issue off, as based on what you've said (and me knowing the spec files) there isn't actually an issue.

Thanks again
Karl
