### ISSUE TITLE
https-nginx sample busyloops

### ISSUE THREAD

**Issue by rf232** [kubernetes/kubernetes#36489]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT on sample file

I was using the /examples/https-nginx sample application for some small testing purposes and was surprised by the relative high load it kept having in the nginx pods.

After some inspection I found out that kubernetes/examples/https-nginx/auto-reload-nginx.sh is basically running a busy loop. the `inotifywait` command doesn't filter out some of the events it should filter out.  At least on my system with just this sample config I always get a OPEN on default.conf basically immediately so I would recommend adding `-e modify,move,create,delete` as arguments to the inotifywait command

**Comment by zreigz** [comment]
I can take this.

**Comment by ymqytw** [comment]
@zreigz I already have a PR #36385 in flight for this.

**Comment by zreigz** [comment]
OK thanks for info
