### ISSUE TITLE
Container GC shouldn't remove the first crashed container 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#3649]
Current container GC has a configurable cap (default: 5) per container spec. If a restart count hit to 5, Kubelet tries to delete old containers solely based on timestamps. But from my experience on Google internal system, there are three information are the most important for users:

1) the first crash
2) the last recent crash
3) number of crash: indicate if it is a transient issue or a crash loop 

cc/ @brendandburns @bgrant0607

**Comment by bgrant0607** [comment]
I agree.

**Comment by brendandburns** [comment]
sgtm.

**Comment by yujuhong** [comment]
I am working a related issue (crash loop), so I will pick this up.

**Comment by yujuhong** [comment]
@dchen1107, I think we agreed that this would be a little bit more complicated than initial proposal. We'd need to detect the first crash of the *most recent* series of crashes. This would probably involve some heuristics and is not a priority for now.

**Comment by dchen1107** [comment]
Yes, this is targeted for v1.0. You can unassign yourself too.
