### ISSUE TITLE
how to make node-port has the same value as target port

### ISSUE THREAD

**Issue by nasry** [kubernetes/kubernetes#36490]
Hello,
please I would like to know if it possible to make the node-port take the some value as the target port instead of the random value.
thanks

**Comment by fabianofranz** [comment]
Closing this since Kubernetes issues are intended to be used to report actual bugs and issues. Questions should be directed to one of our communication channels, please take a look at the suggestions below:

http://kubernetes.io/docs/troubleshooting/
