### ISSUE TITLE
Preserve source ip of service.clusterIP traffic

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#36500]
due to Masq or SNAT when kubeproxy forward request for Service, pods behind service lost client IP. I propose:

* Add a "ClientIPPreserving bool" knob in ServiceSpec
* If `service.spec.clientIPPreserving == true`, kubeproxy will forward  packets using ipip or GRE tunnel

Will send a detail proposal if it's worth doing. @bprashanth

**Comment by mqliang** [comment]
cc @ddysher

**Comment by bprashanth** [comment]
pod -> service -> pod should preserve source ip as long as you're using iptables proxier.
outside cluster -> service (either lb or nodeport) -> pod will not preserve source ip

There is a feature called external ip preservation that is going beta in 1.5 that allows the second to work. If the first is not working, that's a regression, can you provide a repro?

**Comment by mqliang** [comment]
@bprashanth how about userspace proxier? depreciated?

**Comment by bprashanth** [comment]
We all agree that preserving source ip is good, it's a matter of implementation. I don't know if the current users of userspace proxy would actually appreciate a change like this enough for us to invest in it, do you?

**Comment by mqliang** [comment]
cloud provider's loadbalancer will preserve client ip in L4. But if we deploy k8s on bare-metal, It seems that we still lost the client IP, right? The nginx ingress-controller does not preserve client ip in L4.

**Comment by bprashanth** [comment]
It uses hostport, so under these conditions, it won't: https://github.com/kubernetes/kubernetes/issues/29742. I consider those bug fixes, but I haven't looked into viable alternatives yet.

**Comment by caseydavenport** [comment]
/close 

Source IP preservation is preserved for ClusterIP services using the iptables proxier - I don't think we're going to add this to the userspace proxy in the foreseeable future.

**Comment by caseydavenport** [comment]
One more try...

/close
