### ISSUE TITLE
High latency after initial scheduling breaks scheduler-perf integration tests.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#36532]
Problem

When running the test/integration/scheduler_perf tests, we test behaviour for scheduling against large node groups w/ thousands of pods, i.e. `TestSchedule100Node3KPods` pods ... This test fails because of a discreet blip in "measured pods scheduled" .  I call this "measured pods scheduled" rather than "pods scheduled" because, it could simply be a *failure in the test to accurately measure throughput*.  Alternatively, it could be a real latency blip  in the scheduler.

*Details*

if minQPS ever becomes zero, the scheduling perf tests will fail.
this can happen easily even if 3k pods get scheduled, because of some strange measurement of 0 scheduled pods that happened within 2-3 seconds of scheduling events during the tests...

If we add some logs to print out how long its taking, we can see a little latency: The second second (i.e. 2 out of 0,1,2,...) measures a zero change in total pods.   This could be

- just  a bug in test-integration/scheduler_perf, simply happening because of the way the polling for total pods is done,  or
- a more interesting bug fundamental latency bug in the scheduler: (i.e. breif relapse, wherein pods abruptly (and temporarily)  stop being scheduled for a second or two after schdeuling starts).

In one run, for example, we get 15 pods scheduled, followed by 0 net pods - leading to a min qps of zero.
```
not done yet%!(EXTRA int32=2147483647, int=15, int=3000)0s      rate: 15        total: 15
not done yet%!(EXTRA int32=15, int=15, int=3000)1s      rate: 0 total: 15
not done yet%!(EXTRA int32=0, int=15, int=3000)2s       rate: 0 total: 15
```

in another run, similar deal, 12 pods scheduled and then nothing....  
```
not done yet%!(EXTRA int32=2147483647, int=12, int=3000)0s      rate: 12        total: 12
not done yet%!(EXTRA int32=12, int=12, int=3000)1s      rate: 0 total: 12
not done yet%!(EXTRA int32=0, int=12, int=3000)2s       rate: 0 total: 12 <-- min qps now == 0!
not done yet%!(EXTRA int32=0, int=1047, int=3000)3s     rate: 1035      total: 1047
not done yet%!(EXTRA int32=0, int=2582, int=3000)4s     rate: 1535      total: 2582
```

*Solution*
the QPS field should measure that , QPS is increasing in a way that we expect, and those expectations should be more explicit.

**Comment by jayunit100** [comment]
@gmarek @timothysc

**Comment by jayunit100** [comment]
...a more easy to interpret summary...
```
0 [5000 pods/100 nodes] = 3 (min qps)
1 [5000 pods/200 nodes] = 3 (min qps)
2 [5000 pods/400 nodes] = 7 (min qps)
3 [5000 pods/800 nodes] = 1 (min qps)
4 [5000 pods/1600 nodes] = 62 (min qps)
5 [5000 pods/3200 nodes] = 59 (min qps)
```

**Comment by gmarek** [comment]
I can't really explain what you're seeing. My results look like this (100 Nodes, 10000 Pods) [the huge number in the 0s is expected - this is how this test was written]:
```
0s	rate: 7092	total: 7092
1s	rate: 616	total: 7708
2s	rate: 626	total: 8334
3s	rate: 588	total: 8922
4s	rate: 590	total: 9512
Scheduled 10000 Pods in 5 seconds (2000 per second on average).
```

It's clear that you have some modified version of the test, but it's also strange, as it looks like you observer way, way, way, way, way worse performance that I'm seeing.

**Comment by jayunit100** [comment]
unmmodified from master

```
2s      rate: 0 total: 4
3s      rate: 470       total: 474
4s      rate: 546       total: 1020
5s      rate: 550       total: 1570
6s      rate: 539       total: 2109
7s      rate: 552       total: 2661
```
running the original master branch.    the original cause of failure is simply the cold start i think.

**Comment by timothysc** [comment]
@jayunit100 isn't this ... patched now?  reopen if you think otherwise.
