### ISSUE TITLE
Refactor ip releasing logic in gce.EnsureLoadbalancer

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#36535]
This logic is brittle, it uses 2 flags to control when to relese the static ip and flips them on/off throughout a 250 line function. The default quota for static ips is 7, and when there's a leak the entire queue is closed till we come up with the exact order of if/else/retry logic that caused one of the flags to end up false.

**Comment by ethernetdan** [comment]
@bprashanth @saad-ali could this be closed or moved to the `v1.7` milestone?

**Comment by ethernetdan** [comment]
Moving to 1.7 because too late for 1.6. Feel free to move back if this is incorrect.

**Comment by bowei** [comment]
/assign @nicksardo 

I think we did some refactor work here, feel free to close if no longer relevant

**Comment by nicksardo** [comment]
It's still relevant, unfortunately.  Might be able to tackle this as we move over to backend-services or migrate to a gcp-specific controller.

**Comment by caseydavenport** [comment]
@nicksardo is this something you're working on for v1.7, or should the milestone be changed?

**Comment by nicksardo** [comment]
@caseydavenport No, and I don't expect it'll be a top priority in 1.8. Remove milestone?

**Comment by caseydavenport** [comment]
Yep, let's - though I don't have the ability to do that.

@thockin?
