### ISSUE TITLE
Fix federation flaky tests

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#36540]
Filing this issue to keep track of fixing and reenabling flaky federation unit tests that were disabled in https://github.com/kubernetes/kubernetes/pull/36536.

Both @mwielgus and I are debugging.

cc @kubernetes/sig-cluster-federation

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @nikhiljindal @mwielgus

**Comment by dims** [comment]
@nikhiljindal all issues must be labeled either release blocker or non release blocking by end of day 18 November 2016 PST. (or please move it to 1.6) cc @kubernetes/sig-cluster-federation

**Comment by madhusudancs** [comment]
Not a v1.5 release blocker.

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by marun** [comment]
Assuming this should not be blocking 1.7.

@nikhiljindal Can this issue be closed?

**Comment by nikhiljindal** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/37307 and https://github.com/kubernetes/kubernetes/pull/37659
