### ISSUE TITLE
Container-Pod mapping interface on node

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#36544]
Monitoring/logging agents running on a node needs to know which pod a given container belongs to. Currently there is a lot of hacks around this:
- filepath for logging
- labels on docker
- reverse lookup from api server

Each of them has obvious drawbacks. We need a consistent solution for this problem.

cc @dchen1107 @kubernetes/sig-instrumentation @kubernetes/sig-node

**Comment by matthiasr** [comment]
I'm thick and don't see the obvious, could you elaborate what the drawbacks are in reach case?

**Comment by piosz** [comment]
> - filepath for logging

works only for logging
> - labels on docker

might be different for various container environments or even a container environment provider might not support labels
> - reverse lookup from api server

significant load on api server + duplicated logic in every daemon

**Comment by matthiasr** [comment]
Thank you!

**Comment by vishh** [comment]
In https://github.com/kubernetes/kubernetes/issues/24677#issuecomment-231479502 I was proposing dumping v1.Pod object into a `.metadata` file to get metadata for logs. In theory, such an interface should let monitoring agents deterministically identify the pods running on the node. May be we could make that a generic API and not be specific to logs.

**Comment by richm** [comment]
This is the information we have in the current logging format (whether using log files or CONTAINER_NAME in journal): container_name, pod_name, namespace_name, docker_id.
log files:
```
/var/log/containers/(?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log
```
journald:
```
CONTAINER_NAME=^k8s_(?<container_name>[^\.]+)\.[^_]+_(?<pod_name>[^_]+)_(?<namespace>[^_]+)_[^_]+_[a-f0-9]{8}$
```
This is the information we currently need: pod_uuid, namespace_uuid, spec.nodeName, metadata.labels, metadata.annotations.

**Comment by fabxc** [comment]
Metrics exported by cAdvisor today have a `pod_name` label attached already. This allows us to perform joins with info level metrics at query time. Those are just metrics with constant value 1 and information encoded into labels, e.g. [`kube_pod_info`](https://github.com/kubernetes/kube-state-metrics#pod-metrics).

So from the monitoring side, this generally works today. The only question I have is, whether kube-state-metrics is the best place for the pod metrics. We generally want to get metrics from the component closest to the source. For abstract objects like ReplicaSets and Deployments, kube-state-metrics seems fine but for Pods, the kubelet might be a better place? 
If so, as part of this issue, I'd expect the kubelet to expose the various pod metrics kube-state-metrics currently provides additionally to whatever other API is decided here.

One thing I find particularly important is including the owner reference so we can provide decent information on "total container CPU resources used by deployment X" etc., without hacking around with best-effort regular expression matching between their names.

**Comment by brancz** [comment]
Agreed @fabxc. Some metrics regarding Deployments, ReplicaSets, etc. could also move closer to its origin. (`kube-controller-manager`) I think almost all metrics that are part of `kube-state-metrics` today can move into kubernetes/kubernetes, we just need to figure out the best place for them to live, which is typically the origin of the information.

**Comment by fabxc** [comment]
All previous concerns around load that would generate and authentication still hold.
But in the pod info from kubelets case, they are addressed anyway if we want to have an API exposing all the information there.
