### ISSUE TITLE
Missing deployment file for fluentd-elasticsearch

### ISSUE THREAD

**Issue by F21** [kubernetes/kubernetes#36558]
The [fluentd-elasticsearch add-on](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch) contains deployment files for elasticsearch and kibana, but does not appear to contain a deployment file for deploying the fluentd-elasticsearch image.

It would be nice if a deployment file is included so that it's easy to bootstrap a cluster quickly.

**Comment by bgrant0607** [comment]
cc @piosz

**Comment by piosz** [comment]
Currently fluentd is being created as a manifest pod. You can find it configuration in https://github.com/kubernetes/kubernetes/tree/master/cluster/saltbase/salt. There is also an effort to migrate it to DaemonSet #23224.
