### ISSUE TITLE
etcd rollback tool panic

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#36555]
I tried to do a rollback on my own test cluster and got a panic.  I will attach the data-dir tarball.  The script that performs the migration goes from 2.2.1->2.3.7->3.0.14->2.3.7, and it is this last step that barfs.  Script is forthcoming in a PR, but there's a snapshot at https://gist.github.com/mml/42e57c45b333f8b1c8c29bb162394e7d

```
 Performing etcd3 -> etcd2 rollback
 + /usr/local/bin/rollback --data-dir /var/etcd/data
 2016-11-10 03:18:07.226168 C | membership: error updating attributes of unknown member cf7d617fc919f571
 panic: error updating attributes of unknown member cf7d617fc919f571

 goroutine 1 [running]:
 panic(0xae1600, 0xc8211be610)
         /usr/local/go/src/runtime/panic.go:481 +0x3e6
 k8s.io/kubernetes/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc820138ac0, 0xe5b340, 0x2e, 0xc8219112e8, 0x1, 0x1)
         /go/src/k8s.io/kubernetes/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:75 +0x191
 k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/membership.(*RaftCluster).UpdateAttributes(0xc8213c2b40, 0xcf7d617fc919f571, 0xc8211be520, 0xb, 0xc8211c8f80, 0x1, 0x4)
         /go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/membership/cluster.go:331 +0x2e5
 k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver.(*applierV2store).Put(0xc8202a2be0, 0xc8214d11e0, 0x0, 0x0, 0x0, 0x0, 0x0)
         /go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/apply_v2.go:83 +0x765
 main.applyRequest(0xc8214d11e0, 0x7f4c439473c0, 0xc8202a2be0)
         /go/src/k8s.io/kubernetes/cluster/images/etcd/rollback/rollback.go:321 +0x1cf
 main.rebuild(0x7ffc57679f18, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
         /go/src/k8s.io/kubernetes/cluster/images/etcd/rollback/rollback.go:296 +0xe8d
 main.main()
         /go/src/k8s.io/kubernetes/cluster/images/etcd/rollback/rollback.go:103 +0x70c
```

@wojtek-t @hongchaodeng

**Comment by mml** [comment]
[data.tar.gz](https://github.com/kubernetes/kubernetes/files/582478/data.tar.gz)

**Comment by wojtek-t** [comment]
>
panic: error updating attributes of unknown member cf7d617fc919f571

This seems that it's not even about the real data, but about some metadata of the cluster.

@hongchaodeng @xiang90 - any thoughts on it?

**Comment by hongchaodeng** [comment]
@mml 
Is the data you uploaded the original data before 2.2.1->2.3.7?

**Comment by mml** [comment]
@hongchaodeng yes

**Comment by hongchaodeng** [comment]
@mml 

The rollback tool couldn't accept any v2 data existed.
One way to make it work is to remove snap files:
```
rm -rf ${DATA_DIR}/member/snap/*.snap
```

**Comment by hongchaodeng** [comment]
To clarify, the panic is caused by existing v2 snap files.

In the migrate step 2.3.7 -> 3.0.x, the script didn't remove v2 snap files.

**Comment by wojtek-t** [comment]
@hongchaodeng - thanks a lot for looking into it. I will add a step to our migration script to remove the v2 data before rollback.

Did it work after removing the data?

**Comment by wojtek-t** [comment]
#36738 send out for review

**Comment by wojtek-t** [comment]
To clarify - I verified that it fixed the problem reported (rollback works on the data provided in the issue).

**Comment by mml** [comment]
The fix in the shell script is good, but the error message in the rollback tool could definitely be improved upon.

**Comment by mml** [comment]
@xiang90 says that removing the snap file was not the right way to go.

**Comment by dims** [comment]
@mml @xiang90 i marked #37322 as milestone 1.5 and marking this as a non-release-blocker. hope this is correct.

**Comment by mml** [comment]
Hmm...  I tried re-running this on my test data, and now 2.3.7 **always** panics after the last step, whether I begin with backup data or not.

```
 panic: runtime error: makeslice: len out of range
 
 goroutine 1 [running]:
 panic(0xdc26c0, 0xc8203ec880)
         /usr/local/go/src/runtime/panic.go:481 +0x3e6
 github.com/coreos/etcd/wal.(*decoder).decode(0xc82039f860, 0xc8201fdf90, 0x0, 0x0)
         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/wal/decoder.go:55 +0x142
 github.com/coreos/etcd/wal.(*WAL).ReadAll(0xc82034fd40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/wal/wal.go:237 +0x214
 github.com/coreos/etcd/etcdserver.readWAL(0xc82036fca0, 0x19, 0xf268, 0x8, 0x0, 0x0, 0x0, 0xc82034fd40, 0x1, 0xc8203ec6c0, ...)
         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/storage.go:87 +0x228
 github.com/coreos/etcd/etcdserver.restartNode(0xc82008f180, 0xc820081560, 0x29, 0xc8201fe950, 0x0, 0x0, 0x0, 0x0)
         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/raft.go:334 +0xff
 github.com/coreos/etcd/etcdserver.NewServer(0xc82008f180, 0xc82008f238, 0x0, 0x0)
         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:333 +0x3be5
 github.com/coreos/etcd/etcdmain.startEtcd(0xc820090f00, 0x0, 0x0, 0x0)
         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:302 +0x1b40
 github.com/coreos/etcd/etcdmain.Main()
         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:118 +0x2142
 main.main()
         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/main.go:29 +0x14
```

Here is the data
 - before running rollback: [snapshot-before-rollback-2.3.7.tar.gz](https://github.com/kubernetes/kubernetes/files/632789/snapshot-before-rollback-2.3.7.tar.gz)
 - after running rollback: [snapshot-post-rollback-2.3.7.tar.gz](https://github.com/kubernetes/kubernetes/files/632790/snapshot-post-rollback-2.3.7.tar.gz)

**Comment by xiang90** [comment]
@mml I do not understand this. Does the migration tool still panic? Or the etcd 2.3.7 panics? etcd 2.3.7 should panic if you build the migration tool with 3.0 wal pkg. I believe I sent you the correct migration binary over slack.

**Comment by xiang90** [comment]
@mml Can we close this issue if the rollback tool stop panics? If the migrated data panics etcd 2.3, it is expected. And there is some other issues tracking it. I think we went though them a few weeks ago before thinks giving.

**Comment by mml** [comment]
@xiang90 your slack message was lost while I was out of office, but the attached file is still there.  Trying it now.

**Comment by mml** [comment]
@xiang90 it works with the binary you shared.  We still need a way to build that binary, but I will open a separate issue about that.
