### ISSUE TITLE
CRI support docker/docker?

### ISSUE THREAD

**Issue by HuKeping** [kubernetes/kubernetes#36552]
Hi,

As per https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/container-runtime-interface-v1.md#requirements

It says "Support the already integrated container runtime: docker and rkt", I wonder the `docker` here is `docker/docker` or the runtime `runc`?

**Comment by Random-Liu** [comment]
The `docker` here is real docker. :)

**Comment by HuKeping** [comment]
Thanks @Random-Liu  ! Actually, I've been looking at `cri-o` for a while :), just curious the new CRI will still support the whole docker.

**Comment by Random-Liu** [comment]
@HuKeping We want to support multiple runtimes. Docker is of course one of them. :)

**Comment by HuKeping** [comment]
cri-o will not take docker as its runtime, it will take those OCI compliant ones,like runc. rkt has it's own project like rktlet, so what's the plan for docker, will it be possible that something like dockerlet to be introduced in?

**Comment by Random-Liu** [comment]
@HuKeping Yeah, docker is integrated directly via CRI (the same with rocklet).
The code is in [dockershim](https://github.com/kubernetes/kubernetes/tree/master/pkg/kubelet/dockershim). In v1.5, as an experimental feature, we'll start a in-process dockershim grpc server, and let kubelet integrate with dockershim via CRI.

In the future, we may start dockershim grpc server as a seperate daemon outside of kubelet. And we
may or may not move dockershim out to a separate repo (dockerlet?).

@yujuhong knows better about the future plan.

**Comment by HuKeping** [comment]
@Random-Liu I suppose `dockershim` will be used to replace the `dockertools` pkg?

**Comment by Random-Liu** [comment]
@HuKeping Yeah, but not v1.5.

**Comment by HuKeping** [comment]
As per the rapidly evolving of k8s, I don't really think it will take a long time lol, thanks @Random-Liu !

**Comment by HuKeping** [comment]
I guess there will be some competition between `cri-o` and `dockershim`  since the runtime are all `runc` for both of the projects, am I right?

**Comment by yujuhong** [comment]
In v1.5, there will be a flag `--experimental-cri` to let users try out the new docker CRI integration, so that we can gather feedback. The plan is to productionize the docker CRI integration as soon as possible so that we can switch kubelet to use it as the default for two reasons: 1) validate CRI integration; 2) lower the maintenance burden for carrying two docker implementation in the codebase.

As for non-docker CRI integration, there are still things that we need to work on to make it happen, but we'll get there!

**Comment by yujuhong** [comment]
Closing this issue since the question has been answered. Feel free to reopen if that's not the case.
