### ISSUE TITLE
[kube-dns] Why kube-dns doesn't support DNS forwarding?

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#36565]
As we know, sky-dns support DNS forwarding, see [here](https://github.com/skynetservices/skydns#dns-forwarding).

However, the successor of sky-dns, kube-dns doesn't support DNS forwarding any more. There is no flags about DNS forwarding in kube-dns, see below:

```
Usage of /kube-dns:
      --alsologtostderr[=false]: log to standard error as well as files
      --dns-port=53: port on which to serve DNS requests.
      --domain="cluster.local.": domain under which to create names
      --federations=: a comma separated list of the federation names and their corresponding domain names to which this cluster belongs. Example: "myfederation1=example.com,myfederation2=example2.com,myfederation3=example.com"
      --healthz-port=8081: port on which to serve a kube-dns HTTP readiness probe.
      --kube-master-url="": URL to reach kubernetes master. Env variables in this flag will be expanded.
      --kubecfg-file="": Location of kubecfg file for access to kubernetes master service; --kube-master-url overrides the URL part of this; if neither this nor --kube-master-url are provided, defaults to service account tokens
      --log-backtrace-at=:0: when logging hits line file:N, emit a stack trace
      --log-dir="": If non-empty, write log files in this directory
      --log-flush-frequency=5s: Maximum number of seconds between log flushes
      --logtostderr[=true]: log to standard error instead of files
      --stderrthreshold=2: logs at or above this threshold go to stderr
      --v=0: log level for V logs
      --version[=false]: Print version information and quit
      --vmodule=: comma-separated list of pattern=N settings for file-filtered logging
```

I think visiting external domain is a reasonable need for the containered application inside kubernetes cluster. I wonder why kube-dns doesn't support it?

What' more, since kube-dns doesn't support dns forwarding, it means pods with `DNSClusterFirst` policy can't behave as expected?

@thockin @mml @bowei

**Comment by tommywo** [comment]
@m1093782566 kube-dns forwards requests to nameserver specified in /etc/resolv.conf

**Comment by m1093782566** [comment]
Oh, thanks. It's really a trick:)

**Comment by bowei** [comment]
@m1093782566 close this issue?

**Comment by arminbalalaie** [comment]
@tommywo that wasn't the case as mentioned in #23474. are you sure this feature is working fine now ?
@m1093782566 if you confirm what @tommywo is saying, I can close that issue as well.

**Comment by m1093782566** [comment]
It works in my box. Thanks all!

BTW, I slightly suggest document it. :)
