### ISSUE TITLE
kubectl logs --follow output truncated

### ISSUE THREAD

**Issue by tobstarr** [kubernetes/kubernetes#36567]
**Kubernetes version** (use `kubectl version`): 1.4.5

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Fedora
- **Kernel** (e.g. `uname -a`): 4.8.6-201.fc24.x86_64

**What happened**:

I create a (long running) pod and (when the pod is ready) execute `kubectl logs <pod> -f`. The command exits with status code 0 but did not print all of the logs. I am using this way of tailing my container logs from a build tool and in versions before (either 1.4.3 or 1.4.4) the result was, that `kubectl logs -f` always printed all the logs. 

**What you expected to happen**:

That I see all of the log output of the pod until it finishes

**How to reproduce it** (as minimally and precisely as possible):

  kubectl run --restart=Never --image fedora:24 follow-test bash -- -c 'sleep 10; pwd'

wait for the pod to be ready and then execute

  kubectl logs -f follow-test

The command actually waits for the pod to be completed but does not print any logs.

When I execute the command again I get all the logs.

**Anything else do we need to know**:

I am not sure about the expected behavior of the `-f` flag but for me it is at least some kind of regression.

I actually ran into this issue using the API without kubectl in the first place so I think the "issue" is in the API endpoint and not in kubectl.

**Comment by ymqytw** [comment]
I can't reproduce this issue with a 1.4.5 `kubectl` and a 1.4.5 server.
@tobstarr  How often does this happen?

**Comment by tobstarr** [comment]
@ymqytw every time I run it.

**Comment by ymqytw** [comment]
I guess this may related to the the OS you are using?
@pwittrock Do you know who is right person to route to?

**Comment by tobstarr** [comment]
Hi just tested the command with a GKE cluster and things worked fine. So I guess it has something to do with the way I set up my cluster. So I would say close this for the time being?

**Comment by ymqytw** [comment]
> So I would say close this for the time being?

SGTM

**Comment by miry** [comment]
I had the same issue with kubectl 1.10. It seems related to buffer.
