### ISSUE TITLE
kube-controller-manager with AWS cloud provider crash loop if using http_proxy using "kubeadm init --cloud-provider aws"

### ISSUE THREAD

**Issue by druidsbane** [kubernetes/kubernetes#36573]
**Is this a request for help?** No

**What keywords did you search in Kubernetes issues before filing this one?** http proxy, http_proxy, https_proxy, AWS, kubeadm, kubectl, cloud-provider

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): v1.4.4
```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:42:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

kubeadm version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.2.421+a6bea3d79b8bba", GitCommit:"a6bea3d79b8bbaa5e8b57482c9fff9265d402708", GitTreeState:"clean", BuildDate:"2016-11-03T06:54:50Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: kubeadm on EC2 instances on AWS
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS
- **Kernel** (e.g. `uname -a`): Linux ip-10-0-133-99 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubeadm
- **Others**: _http_proxy_, _https_proxy_ and _no_proxy_ set in /etc/environment, Docker config as well on startup scripts that run `kubeadm init`

**What happened**:
`kubeadm init --cloud-provider aws` won't complete and gets stuck on it's first deployment.  When one looks through the logs it shows that the pods are downloading fine but we are stuck due to the kube-controller-manager continually crashing as it can't contact AWS.  Elsewhere in kubernetes I see references to `http.ProxyFromEnvironment` and if the AWS cloud provider could use that it would be able to connect as well.  From the POD if I manually set http_proxy and https_proxy and no_proxy I am able to use the AWS CLI without any issues.

```
root@ip-10-2-221-240:/home/ubuntu# kubectl logs kube-controller-manager-ip-10-2-221-240 --namespace=kube-system
E1108 13:58:14.493903       1 event.go:258] Could not construct reference to: '&api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"kube-controller-manager", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]api.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, Subsets:[]api.EndpointSubset(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' '%v became leader' 'ip-10-2-221-240'
I1108 13:58:14.494179       1 leaderelection.go:214] sucessfully acquired lease kube-system/kube-controller-manager
I1108 13:58:14.499388       1 aws.go:745] Building AWS cloudprovider
I1108 13:58:14.499484       1 aws.go:699] Zone not specified in configuration file; querying AWS metadata service
I1108 13:58:14.499651       1 replication_controller.go:219] Starting RC Manager
I1108 13:58:14.605138       1 endpoints_controller.go:326] Waiting for pods controller to sync, requeuing service default/kubernetes`

[10:25]  
I1108 15:24:09.602100       1 endpoints_controller.go:326] Waiting for pods controller to sync, requeuing service default/kubernetes
I1108 15:24:09.602100       1 endpoints_controller.go:326] Waiting for pods controller to sync, requeuing service default/kubernetes
I1108 15:24:09.602100       1 endpoints_controller.go:326] Waiting for pods controller to sync, requeuing service default/kubernetes
I1108 15:24:09.602100       1 endpoints_controller.go:326] Waiting for pods controller to sync, requeuing service default/kubernetes
....
F1108 15:24:09.625221       1 controllermanager.go:227] Cloud provider could not be initialized: could not init cloud provider "aws": error finding instance i-052a60ad4cc805154: error listing AWS instances: RequestError: send request failed
caused by: Post https://ec2.us-west-1.amazonaws.com/: dial tcp 176.32.118.53:443: i/o timeout
```

**What you expected to happen**:
I would expect `kubeadm init --cloud-provider aws` to successfully complete and use the environment proxies set up on the system so as not to depend on a default Internet Gateway being connected to the VPC just for AWS access.

**How to reproduce it** (as minimally and precisely as possible):
- Set up a public VPC with Squid set up as a proxy
- Set up a private VPC peered to the public VPC
- Set up a master node and run `kubeadm init --cloud-provider aws`
- Set up a regular node and run `kubeadm join`

`kubeadm` will never fully initialize.  If you remove the --cloud-provider aws` then it will complete and nodes will register.

**Anything else do we need to know**:

**Comment by kad** [comment]
what do you have in *_proxy variables ? (env | grep -i _proxy) 
it tries to connect to https://ec2.us-west-1.amazonaws.com/ (tcp 176.32.118.53:443) directly.
You're expecting to connect there via proxy ? then do you have something like *.amazonaws.com in your no_proxy ?

**Comment by druidsbane** [comment]
Unfortunately on the pod itself for the `kube-controller-manager` the environment variables aren't passed through.  As this is created using `kubeadm` I don't have control over the pod definition.  So basically none of the *_proxy variables are set inside the pod in the docker image, however if I `kubectl exec kube-controller-manager-blah -it sh` and export the variables and try to wget that URL it works.

Basically I'm hoping we can update `kubeadm` to respect and pass the environment variables down to the system pods if they exist, eg, add:
```
    env:
    - name: http_proxy
      value: http://squid.mydomain.internal:3128
    - name: https_proxy
      value: http://squid.mydomain.internal:3128
    - name: no_proxy
      value: NO_PROXY=169.254.169.254,10.0.0.0/8,localhost,127.0.0.1,172.0.0.0/8,192.168.0.0/16,*.mydomain.internal
```

Without it I can't stand up a cluster with AWS integration on a completely private VPC and for such a small change it would make a rather big difference.

**Comment by kad** [comment]
ok, so request is actually to pass proxy variables into containers. interesting. I'll check how it can be done.

BTW, for no_proxy value in your example: things like 10.0.0.0/8 would not work on 99% of software that respects no_proxy variable. it must be always exact IP match.

**Comment by druidsbane** [comment]
@kad you're right that what I'm actually asking for is to pass proxy variables through either from a commandline setting on kubeadm or pick it up from /etc/environment or shell environment that launches kubeadm.

I didn't realize it till I dug in to try and think about how one might go about fixing this.  At first I thought we would just pick up the variables from the system environment but then I realized kube-controller-manager is deployed in a container and so we'd need to update the yaml file that launches it to contain the environment variables.

As I'd like to go to production with this soon hopefully this is a small change that can be added.

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#5
