### ISSUE TITLE
Evaluate usage of system certificates in client component.

### ISSUE THREAD

**Issue by kad** [kubernetes/kubernetes#36577]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): certs, client, system, pki

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request/code refactoring.

**Kubernetes version** (use `kubectl version`): master branch, after 1.5 branch of.

**Environment**:
- **Cloud provider or hardware configuration**: none
- **OS** (e.g. from /etc/os-release): centos
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
pkg/client/transport/transport.go has function rootCertPool which populates rootCAs for client TLS configuration. Since a093ea34c3168c085c949e292108b4ae9be15784 there is in this function comment:
```go
// What we really want is a copy of x509.systemRootsPool, but that isn't exposed.  It's difficult to build (see the go
// code for a look at the platform specific insanity), so we'll use the fact that RootCAs == nil gives us the system values
// It doesn't allow trusting either/or, but hopefully that won't be an issue
```
Nowadays, with Go 1.7 it is possible to get same system CAs via function in crypto/x509: SystemCertPool(). If we want explicitly initialize rootCAs with system defaults, we can do it now.
However, current code which sets rootCAs to nil gives practically same effect, just relaying on defaults in standard library.

**What you expected to happen**:
I'd like to either remove this comment about "isn't exposed", or make it explicitly equal to x509.SystemCertPool(). And want to discuss which would be more appropriate.

**How to reproduce it** (as minimally and precisely as possible):
```console
$ vi pkg/client/transport/transport.go +128
```

**Anything else do we need to know**:
Potentially, we might want to have combination of defined CA in tls.Config + system default CAs,
but not sure if that is intended behaviour or would be valuable generic case.

**Comment by kad** [comment]
cc @deads2k

**Comment by deads2k** [comment]
Allowing systemcerts + a specified CA bundle seems like a good idea for trusting serving certs (not client certs).

@kubernetes/sig-auth
