### ISSUE TITLE
kubectl get cs can't get https etcd health

### ISSUE THREAD

**Issue by luohoufu** [kubernetes/kubernetes#36578]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
kubectl get cs
NAME                 STATUS      MESSAGE                                                               ERROR
etcd-1               Unhealthy   Get https://10.37.116.32:2379/health: remote error: bad certificate   
scheduler            Healthy     ok                                                                    
controller-manager   Healthy     ok                                                                    
etcd-0               Unhealthy   Get https://10.37.116.31:2379/health: remote error: bad certificate  

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by AdoHe** [comment]
@luohoufu what's your kubernetes version?

**Comment by luohoufu** [comment]
please see https://github.com/kubernetes/kubernetes/issues/36582

**Comment by roberthbailey** [comment]
I'm going to mark this as obsolete since the referenced issues is already closed and there haven't been any updates this calendar year.
