### ISSUE TITLE
E2E: [k8s.io] Federation deployments [Feature:Federation] Federated Deployment should create and update matching deployments in underling clusters

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/kubernetes#36588]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-federation/5645

looks like the test case is failing because the `revisions` are not implemented for federation deployment. 
there is difference in Annotations in ObjectMeta of deployment at federation and k8s cluster. 
`deployment.kubernetes.io/revision: 1` is missing in federation deployment object.

@mwielgus @quinton-hoole @madhusudancs

**Comment by dims** [comment]
@shashidharatd @mwielgus all issues must be labeled either release blocker or non release blocking by end of day 18 November 2016 PST. If you are not the correct owner please identify the correct owner and add them to this thread for assignment. Thanks for your help.
cc: @saad-ali, @calebamiles

**Comment by saad-ali** [comment]
@nikhiljindal @matchstick @kubernetes/sig-cluster-federation bumping this to P0 and marking release-blocking

This federation E2E test `Federated Deployment should create and update matching deployments in underling clusters` has been consistently failing in the 1.5 branch:
See [ci-kubernetes-e2e-gce-federation-release-1.5](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-federation-release-1.5) and [kubernetes-e2e-gce-federation-release-1.5](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/kubernetes-e2e-gce-federation-release-1.5)

Please take a look ASAP

**Comment by calebamiles** [comment]
@mwielgus, @matchstick please provide a status update on this issue by 1pm PST 23 November 2016. Thanks!

**cc: @saad-ali, @dims, @kubernetes/goog-control-plane, @kubernetes/sig-cluster-federation**

**Comment by grodrigues3** [comment]
@mwielgus please update the release blocker label.

**Comment by mwielgus** [comment]
This was fixed. Deployment tests are green (mostly).
