### ISSUE TITLE
Make bot comments more helpful and friendly for each contributor's first few PRs.

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes/kubernetes#36596]
Some ideas:

- Differentiate expectations between small / oneline changes vs XXL changes, e.g. suggest a SIG to go talk to.

cc @derekwaynecarr @thockin

**Comment by dims** [comment]
cc @kubernetes/contributor-experience

**Comment by bgrant0607** [comment]
See also:
https://groups.google.com/forum/#!searchin/kubernetes-dev/brendan$20burns%7Csort:relevance/kubernetes-dev/PN6aC4TCESE/Koq36AeaCAAJ

cc @brendandburns @smarterclayton

**Comment by bgrant0607** [comment]
And:
https://github.com/kubernetes/contrib/issues/1090

FYI, we usually file these kinds of issues in contrib, since that's where the bot code lives.

**Comment by bgrant0607** [comment]
Closing in favor of the contrib issue. Would still like to see this happen, @ConnorDoyle @derekwaynecarr 
cc @grodrigues3
