### ISSUE TITLE
GKE kube-dns cname record

### ISSUE THREAD

**Issue by AndriiOmelianenko** [kubernetes/kubernetes#36593]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: GCE / GKE

**What happened**:
I have pod exposed by using service, with name `test-svc`. I can resolve it from other pods by using either `test-svc` or `test-svc.default.svc.cluster.local` name.

**What you expected to happen**:
I want to have possibility to add cname record, for example `test-service.mydomain.com` in my cluster, which is going to point to `test-svc` or `test-svc.default.svc.cluster.local`.

**Comment by MrHohn** [comment]
FYI there is a related issue: #28525.
