### ISSUE TITLE
how to add test go file in kubernetes

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes/kubernetes#36629]
i want to add a test go file to test functions . i have add the options_test.go file and changed the BUILD file.
but  Jenkins verification — Build failed.
error infos :

I1110 06:28:13.399] Verifying hack/make-rules/../../hack/verify-gofmt.sh
I1110 06:28:22.786] !!! 'gofmt -s -w' needs to be run on the following files: 
I1110 06:28:22.786] ./cmd/kube-controller-manager/app/options/options_test.go
I1110 06:28:22.788] FAILED   hack/make-rules/../../hack/verify-gofmt.sh	9s

I1110 06:33:37.299] ERROR: the test list has changed
I1110 06:33:37.304] Run ./hack/update_owners.py to fix it
I1110 06:33:37.305] SUCCESS  hack/make-rules/../../hack/verify-test-owners.sh	1s
I1110 06:33:37.307] Verifying hack/make-rules/../../hack/verify-flags-underscore.py
I1110 06:34:37.073] SUCCESS  hack/make-rules/../../hack/verify-flags-underscore.py	60s
I1110 06:34:37.074] Makefile:99: recipe for target 'verify' failed
W1110 06:34:37.074] make: *** [verify] Error 1
I1110 06:34:39.791] process 27059 exited with code 2
E1110 06:34:39.791] FAIL: pull-kubernetes-verify
I1110 06:34:39.791] Upload result and artifacts...

**Comment by dims** [comment]
@NickrenREN : the key is this error
```
I1110 06:33:37.299] ERROR: the test list has changed
I1110 06:33:37.304] Run ./hack/update_owners.py to fix it
```

Can you please do that and THEN run `verify-gofmt.sh` please?

You should see an update to `test/test_owners.csv`
