### ISSUE TITLE
Apiserver sluggish in releasing nodeports

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#36622]
Quickly recreating a service with a nodeport results in 
```
Error from server (Invalid): error when creating "/usr/local/google/home/beeps/rtmp/yaml/echo-app-lb.yaml": Service "echoheaders-nodeport" is invalid: spec.ports[0].nodePort: Invalid value: 30416: provided port is already allocated
```

Which I don't expect, not for as long as you need to currently wait for that message to stop showing up (o(10s)). Clearly the nodeport isn't in any Service in etcd, so I think we're not writing-through the nodeport cache and some periodic sync is flushing it. 

Still correctn, but a horrible ux.

**Comment by xiangpengzhao** [comment]
Could you please share the repro steps of `quickly recreating a service`?
