### ISSUE TITLE
Issue a warning or error when using apply on a resource lacking the LastAppliedConfig annotation

### ISSUE THREAD

**Issue by ymqytw** [kubernetes/kubernetes#36620]
We should add `LastAppliedConfig` annotation when using `kubectl create`.
Users are keep complaining about why `kubectl apply` don't delete what they expected to be deleted.
The users think this is a bug.
See #35134 and #36509.

cc: @bgrant0607 @pwittrock

**Comment by bgrant0607** [comment]
Quick comment: this is user error. They should use apply to create, or --save-config. 

We've discussed adding a persistent preference to do it by default, but it needs to be opt-in so long as we continue to use the annotation, and we need to create the preference mechanism.

**Comment by bgrant0607** [comment]
We could issue an error or warning in this case.

**Comment by bgrant0607** [comment]
http://kubernetes.io/docs/user-guide/kubectl/kubectl_apply/

**Comment by pwittrock** [comment]
We need to do a better job of educating users how to use apply and its relationship with the other imperative config commands.  This wasn't clear to me for a while even after I had been using it.

**Comment by ymqytw** [comment]
> Issue a warning or error when using apply on a resource lacking the LastAppliedConfig annotation

I will send a PR for this today.
