### ISSUE TITLE
Move e2e tests to separate repo

### ISSUE THREAD

**Issue by jeffvance** [kubernetes/kubernetes#36624]
Also see issues: #24343, #2742, #35314.

Following up on conversations regarding separating Kube "core" in to several repos, this is a proposal to move the e2e test package into its own repo. To accomplish this requires solving issues related to CI and auto testing when PRs are submitted, and is dependent on a tool chain that handles remote imports.

At the moment I am just giving this issue a place to live for a while. I do not have all the questions and may have none of the answers.  Please add to this issue so we can brainstorm a starting point.

@bgrant0607 @saad-ali @copejon

### Questions specific to e2e (see issue #24343 for the list of generic multi-repo questions):

1. How does a PR (outside of the e2e repo) automatically run the e2e tests?2. ~~Do the k8s bots need to work across repos?

2. ~~Do the k8s bots need to work across repos?~~

3. ~~I believe you cannot `import` using a url so how do the e2e tests import their dependencies?~~
    See: https://golang.org/cmd/go/#hdr-Remote_import_paths

4.

**Comment by saad-ali** [comment]
CC @kubernetes/sig-testing

**Comment by jeffvance** [comment]
Thanks for the sig-testing CC @saad-ali

**Comment by jeffvance** [comment]
I would like to change ownership of this issue to @kubernetes/sig-testing. If this sig decides it is not important for the near term they can close it or I am happy to do so. If the sig decides to keep this issue open and is willing to drive it forward then @copejon and myself would like to contribute.

**Comment by spiffxp** [comment]
/close
I'm not sure we're getting to this in the foreseeable future.  A good first step would be extracting the e2e framework out of this repo into the repo proposed via https://github.com/kubernetes/community/pull/1524.  Please /reopen if you're willing to tackle this
