### ISSUE TITLE
Deprecate resource usage tracking test in the cluster e2e suite

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#36621]
The test was created mainly to track kubelet/docker resource usage. Now that we have node benchmark (http://node-perf-dash.k8s.io/) for this purpose, we can consider retiring the resource usage test. Before we can do that, we need a node e2e soak cluster to catch various resource (cpu, memory) leaks. 

/cc @kubernetes/goog-node

**Comment by yujuhong** [comment]
Unfortunately this is still needed.

**Comment by nikhita** [comment]
Removing help-wanted since the directions are not clear enough for a contributor to dive into. Please feel free to re-add the label with more details about how to achieve each step. :)
/remove-help

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/kubernetes/issues/81490

**Comment by dims** [comment]
@ehashman i don't think so.

**Comment by spiffxp** [comment]
I leave whether they need to remain as sig node's call https://github.com/kubernetes/kubernetes/issues/36621#issuecomment-522179501

**Comment by pacoxu** [comment]
```
// Slow by design (1 hour)
```
The test case has several tags now. `[Serial] [Slow][Feature:RegularResourceUsageTracking]` 

However, I think this test will not help with a memory leak issue in most cases. 

For instance, the recent fix #100326 is a kubelet memory leak fix. Leaks happened with some special triggering. I prefer to remove this case.

In my experience of leak testing, a continuously running cluster would help in memory leak issues. (Some general e2e cases are running continuously in the env and a report is generated every day/week.)

**Comment by MorrisLaw** [comment]
Has anyone picked this up yet? What's the current status of this issue? I'm trying to determine if this is something I could start working on or if it needs more discussion.

**Comment by haircommander** [comment]
I don't believe this has been addressed yet, if you want to attempt to fix it @MorrisLaw

**Comment by SergeyKanzhelev** [comment]
this http://node-perf-dash.k8s.io/ doesn't exists any longer
