### ISSUE TITLE
Kubernetes fails to sync node objects in openstack cloud provider

### ISSUE THREAD

**Issue by tadovas** [kubernetes/kubernetes#36632]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): openstack node list sync

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.4.5

**Environment**:
- **Cloud provider or hardware configuration**: openstack + heat
- **OS** (e.g. from /etc/os-release): Centos 7.3
- **Kernel** (e.g. `uname -a`):  3.10.0-327.28.3.el7.x86_64
- **Install tools**: cluster/kube-up.sh
- **Others**: -

**What happened**:
Kubernetes cluster is started up with 3 nodes. One node is turned off (or killed). Kubernetes reports node NotReady, and node object stays forever (waited about 2 days to disappear).

**What you expected to happen**:
Kubernetes should remove node object if node is not available after a specific time.

**How to reproduce it** (as minimally and precisely as possible):
Start a cluster in openstack,  shutdown one node.
./kubectl get nodes  reports failed node in node list forever.

**Anything else do we need to know**:
The problem is in https://github.com/kubernetes/kubernetes/blob/release-1.4/pkg/cloudprovider/providers/openstack/openstack.go#L265
According to contract defined in https://github.com/kubernetes/kubernetes/blob/release-1.4/pkg/cloudprovider/cloud.go#L114  method should return InstanceNotFound, but openstack provider returns ErrNotFound instead. As a result node availability check is broken. This is a one line fix (tested on my openstack cloud), I can provide a pull request (fixed on release-1.4 branch) if needed.

**Comment by jamiehannaford** [comment]
Based on the feedback in https://github.com/kubernetes/kubernetes/pull/36650#issuecomment-260844270, can this be closed? 

cc/ @dims
