### ISSUE TITLE
Add copyright attribution for code taken from prometheus

### ISSUE THREAD

**Issue by felixge** [kubernetes/kubernetes#36633]
1b204d85a69641f8937edf6391add02eb40ce8b7 seems to have copied 100+ LoC from [prometheus](https://github.com/prometheus/client_golang/blob/master/prometheus/http.go#L289)  to [metrics.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/metrics/metrics.go#L84).

Both projects are Apache, but I think that the copyright header of metrics.go should be modified to add attribution for the prometheus authors.

In only noticed this because I was working on a [library](https://github.com/felixge/httpsnoop) for instrumenting http.Handlers and looked at existing implementations for inspirations. You might even want to consider using it, as it handles a few corner cases the current code is missing.

**Comment by dims** [comment]
Should we start a NOTICE.txt like the folks at apache.org do?
http://www.apache.org/dev/licensing-howto.html

Example from one of the projects:
https://svn.apache.org/viewvc/geronimo/server/trunk/NOTICE?annotate=1096964
