### ISSUE TITLE
installation of kubelet fails on ubuntu 16.04

### ISSUE THREAD

**Issue by silhouette** [kubernetes/kubernetes#36640]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): NO

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kubelet socat ubuntu

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
v1.4.4

**Environment**:
- **Ubuntu 16.04 with latest patches, running in a VMware VM**
- **Kernel** (e.g. `uname -a`): 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: http://apt.kubernetes.io/ kubernetes-xenial main via apt-get

**What happened**:

# apt-get install -y kubelet kubeadm kubectl kubernetes-cni
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kubelet : Depends: socat but it is not installable
E: Unable to correct problems, you have held broken packages.

**What you expected to happen**:

Installation should succeed.

**How to reproduce it** (as minimally and precisely as possible):

Use plain Ubuntu 16.04 with latest patches and follow this guide: http://kubernetes.io/docs/getting-started-guides/kubeadm/

**Comment by silhouette** [comment]
Sorry, my bad, socat is in universe, which was disabled at that VM.

**Comment by hansamann** [comment]
I am having this issue, too, I am trying to install docker and then kubeadm (with kubelet , etc).

DOCKER_VERSION=18.06.1~ce~3-0~ubuntu # see https://download.docker.com/linux/ubuntu/dists/xenial/stable/binary-amd64/Packages
KUBERNETES_VERSION=1.13.0-00 # see https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-amd64/Packages

swapoff -a
sed -i "/swap/d" /etc/fstab

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
EOF

apt-get update -y
apt-get install -y docker-ce=$DOCKER_VERSION kubelet=$KUBERNETES_VERSION kubeadm=$KUBERNETES_VERSION kubectl=$KUBERNETES_VERSION

Here'es what I get:
null_resource.master_provisioning (remote-exec): The following packages have unmet dependencies:
null_resource.master_provisioning (remote-exec):  docker-ce : Depends: libltdl7 (>= 2.4.6) but it is not installable
null_resource.master_provisioning (remote-exec):              Recommends: aufs-tools but it is not installable
null_resource.master_provisioning (remote-exec):              Recommends: cgroupfs-mount but it is not installable or
null_resource.master_provisioning (remote-exec):                          cgroup-lite but it is not installable
null_resource.master_provisioning (remote-exec):              Recommends: pigz but it is not installable
null_resource.master_provisioning (remote-exec):  kubelet : Depends: socat but it is not installable
null_resource.master_provisioning (remote-exec):            Depends: ebtables but it is not installable
null_resource.master_provisioning (remote-exec): E: Unable to correct problems, you have held broken packages.
null_resource.master_provisioning (remote-exec): /tmp/master.sh: line 25: kubeadm: command not found

The strange thing is that it will run 2/3 of the times  - then it breaks for a few runs or so .This is part of a terraform for AWS script, so I can quickly repeat which we did a lot. 

Any ideas?
