### ISSUE TITLE
contributor experience feedback

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/kubernetes#36655]
After yesterday contrib-ex session at the dev summit, I tried to compile from scratch following the README. 

Here are my notes:
---

Clone repo

```
git clone https://github.com/kubernetes/kubernetes.git
```

Assuming you have GO environment setup before.
Intuitively try `make` (@thockin just said it works)

```
make
```

Result: Does not work, missing Go libraries.

I don't want to dig into the dependencies, I want a docker build...

Scroll down main README

One click to [Developer Guide](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/README.md)

Once click to [Development Guide](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md)

Once click to [Building with Docker](http://releases.k8s.io/HEAD/build-tools/README.md)

- Will need Docker on my host
- Will need gnu-tar on OSX :)

Then:

```
build-tools/run.sh make
```

Fails with:

```
    test/e2e/e2e.test
    cmd/kubemark
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e_node/e2e_node.test
go install k8s.io/kubernetes/federation/client/clientset_generated/federation_internalclientset: build output "/go/src/k8s.io/kubernetes/_output/dockerized/go/pkg/linux_amd64_cgo/k8s.io/kubernetes/federation/client/clientset_generated/federation_internalclientset.a" already exists and is not an object file
go install k8s.io/kubernetes/pkg/client/unversioned: build output "/go/src/k8s.io/kubernetes/_output/dockerized/go/pkg/linux_amd64_cgo/k8s.io/kubernetes/pkg/client/unversioned.a" already exists and is not an object file
go install k8s.io/kubernetes/pkg/api/events: build output "/go/src/k8s.io/kubernetes/_output/dockerized/go/pkg/linux_amd64_cgo/k8s.io/kubernetes/pkg/api/events.a" already exists and is not an object file
go install k8s.io/kubernetes/pkg/fieldpath: build output "/go/src/k8s.io/kubernetes/_output/dockerized/go/pkg/linux_amd64_cgo/k8s.io/kubernetes/pkg/fieldpath.a" already exists and is not an object file
go install k8s.io/kubernetes/pkg/kubectl/resource: build output "/go/src/k8s.io/kubernetes/_output/dockerized/go/pkg/linux_amd64_cgo/k8s.io/kubernetes/pkg/kubectl/resource.a" already exists and is not an object file
go install k8s.io/kubernetes/cmd/kube-controller-manager/app: build output "/go/src/k8s.io/kubernetes/_output/dockerized/go/pkg/linux_amd64_cgo/k8s.io/kubernetes/cmd/kube-controller-manager/app.a" already exists and is not an object file
Makefile:79: recipe for target 'all' failed
make: *** [all] Error 1
!!! Error in build-tools/../build-tools/common.sh:523
  '"${docker_cmd[@]}" "${cmd[@]}"' exited with status 2
Call stack:
  1: build-tools/../build-tools/common.sh:523 kube::build::run_build_command_ex(...)
  2: build-tools/../build-tools/common.sh:515 kube::build::run_build_command(...)
  3: build-tools/run.sh:30 main(...)
Exiting with status 1
```

**Comment by sebgoa** [comment]
bottom line, the root Makefile does not do Docker build.
It takes three clicks to get to find: `build-tools/run.sh make`
and then without investigation it fails.

The root README, should have a two line close to the top:

---
Build for the impatient:

git clone
make
ls /bin
---

remember (configure, make, make install)

**Comment by thockin** [comment]
Can you tell me what happens with top-level make?  It works for me...

**Comment by sebgoa** [comment]
The top level make is a local Go build (afaik)

So if you consider a new guy, who does not have Go installed and wants to compile kube, then it won't work.

I went looking for a 100% docker build.

**Comment by sebgoa** [comment]
Since I have Go (personally, but may not be the case for first timers), I can try the top-level make:

```
sebair: kubernetes (master)$ make
+++ [1115 10:18:07] Generating bindata:
    /Users/sebastiengoasguen/Documents/go/src/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go
Cannot find go-bindata. Install with
  go get -u github.com/jteeuwen/go-bindata/go-bindata
  and make sure GOBIN is in the system PATH
../../../../../../test/e2e/framework/gobindata_util.go:19: running "../../../hack/update-bindata.sh": exit status 5
make[1]: *** [_output/bin/deepcopy-gen] Error 1
make: *** [generated_files] Error 2
sebair: kubernetes (master)$ go version
go version go1.6 darwin/amd64
sebair: kubernetes (master)$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
sebair: kubernetes (master)$ 
```

**Comment by sebgoa** [comment]
@thockin see https://github.com/kubernetes/kubernetes/issues/34067

same issue, there is a missing dep.

you need to `go get -u github.com/jteeuwen/go-bindata/go-bindata` to get the single `make` to run.

**Comment by sebgoa** [comment]
to be fair, that `go get` dependency is indeed in the docs for a local setup:

https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md#godep-dependency-management

**Comment by thockin** [comment]
We do vendor go-bindata, but apparently we do not call it from our vendored
version.  We should NEVER EVER be calling `go get` in our builds.

@ixdy - your fingerprints (git blame) are on several such calls.  We should
build it as part of an "all" build (just like ginkgo) and we should call it
the same way.

I don't know what go-bindata even does - can you make some time to fix this
up?

**Comment by sebgoa** [comment]
Could we add targets in the root makefile to run the docker builds.

This [page](https://github.com/kubernetes/kubernetes/blob/3b43ce8e5cfbf53d3d7dc84d2e2ffadf752cbe2c/build-tools/README.md) calls to run build_tools/run.sh make.

but the root makefile only calls `make release`

**Comment by philips** [comment]
`go get k8s.io/kubernetes`, `eval $(minikube docker-env)`, `brew install docker`, `make` seems to work for me.

**Comment by sebgoa** [comment]
`make` with no target is a local build, not docker involved. But I will test again.

**Comment by ixdy** [comment]
I think many of the issues raised in this issue have been resolved. @sebgoa are there still pain points that you're aware of?

**Comment by sebgoa** [comment]
I am testing things from scratch again, but it looks good so far.

The only tid bit is https://github.com/kubernetes/kubernetes/issues/37690

**Comment by sebgoa** [comment]
I think once #38504 is merged we can close this.

**Comment by ixdy** [comment]
#38504 merged 2 weeks ago. Closing.
