### ISSUE TITLE
contrib code is bitrotting

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#3665]
Code under contrib/ is not tested nor even rebuilt regularly.   As a result, things like golang 1.4 breaking static builds and API changes cause it not to work.

As of now, nothing using CGO_ENABLED=0 for static builds works and contrib/for-tests/network-tester does not compile.

**Comment by bgrant0607** [comment]
FWIW, I plan to delete all of my contrib scripts O(soon) -- maybe today.

**Comment by thockin** [comment]
There are a lot of things that are built and pushed as docker images one
time, and then left to bit-rot.  Maybe we can extend the build scripts to
run through them and at least ensure they build?

**Comment by zmerlynn** [comment]
+1. We shouldn't have code in the codebase that isn't built, or it will
just bitrot.

**Comment by thockin** [comment]
Sadly 'go test' is insular and won't run other kinds of tests, so is a poor substitute for a build system unless you are entirely monoglot, which we are not.  We could make our test scripts find *_test.sh and run those, too and then just add a build_test.sh to each dir which just calls 'make'.
