### ISSUE TITLE
kubernetes 1.3 kube-apiserver high CPU usage

### ISSUE THREAD

**Issue by Thermi** [kubernetes/kubernetes#36659]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): Kind of. More like a bug report.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kubernetes apiserver CPU usage 100%

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.3

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS 1122.3.0
- **Kernel** (e.g. `uname -a`):4.7.0-coreos-r1
- **Install tools**: kube-aws
- **Others**:

**What happened**: /hyperkube apiserver  on the controller takes up all the CPU time, together with the kernel.

**What you expected to happen**: /hyperkube apiserver doesn't use up all the CPU time.

**How to reproduce it** (as minimally and precisely as possible): Run the cluster for a long time.

**Anything else do we need to know**:

The problem did not exist in the beginning. I started noticing it today. Our performance logs are only kept back for about 2 weeks. The controller shows the high CPU usage for that whole time frame.

Log from the kubelet unit:

```
[continues infinitely]
Nov 11 18:11:03 ip-10-0-0-50.eu-west-1.compute.internal kubelet-wrapper[1501]: I1111 18:11:03.940785    1501 operation_executor.go:740] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/db72bac5-8625-11e6-ad16-0253cca96ab9-default-token-6vjgz" (spec.Name: "default-token-6vjgz") pod "db72bac5-8625-11e6-ad16-0253cca96ab9" (UID: "db72bac5-8625-11e6-ad16-0253cca96ab9").
Nov 11 18:11:23 ip-10-0-0-50.eu-west-1.compute.internal kubelet-wrapper[1501]: I1111 18:11:23.735952    1501 reconciler.go:254] MountVolume operation started for volume "kubernetes.io/secret/779b0278-9a1c-11e6-ad16-0253cca96ab9-default-token-6vjgz" (spec.Name: "default-token-6vjgz") to pod "779b0278-9a1c-11e6-ad16-0253cca96ab9" (UID: "779b0278-9a1c-11e6-ad16-0253cca96ab9"). Volume is already mounted to pod, but remount was requested.
Nov 11 18:11:23 ip-10-0-0-50.eu-west-1.compute.internal kubelet-wrapper[1501]: I1111 18:11:23.736264    1501 reconciler.go:254] MountVolume operation started for volume "kubernetes.io/configmap/779b0278-9a1c-11e6-ad16-0253cca96ab9-td-agent-config" (spec.Name: "td-agent-config") to pod "779b0278-9a1c-11e6-ad16-0253cca96ab9" (UID: "779b0278-9a1c-11e6-ad16-0253cca96ab9"). Volume is already mounted to pod, but remount was requested.
Nov 11 18:11:23 ip-10-0-0-50.eu-west-1.compute.internal kubelet-wrapper[1501]: I1111 18:11:23.744729    1501 operation_executor.go:740] MountVolume.SetUp succeeded for volume "kubernetes.io/configmap/779b0278-9a1c-11e6-ad16-0253cca96ab9-td-agent-config" (spec.Name: "td-agent-config") pod "779b0278-9a1c-11e6-ad16-0253cca96ab9" (UID: "779b0278-9a1c-11e6-ad16-0253cca96ab9").
Nov 11 18:11:23 ip-10-0-0-50.eu-west-1.compute.internal kubelet-wrapper[1501]: I1111 18:11:23.745843    1501 operation_executor.go:740] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/779b0278-9a1c-11e6-ad16-0253cca96ab9-default-token-6vjgz" (spec.Name: "default-token-6vjgz") pod "779b0278-9a1c-11e6-ad16-0253cca96ab9" (UID: "779b0278-9a1c-11e6-ad16-0253cca96ab9").
```

```
# uptime
 18:12:36 up 17:38,  1 user,  load average: 2.14, 2.39, 2.35
```

![screenshot of htop on controller](https://cloud.githubusercontent.com/assets/3606849/20225354/312f6f52-a843-11e6-97ad-76659ab9b87f.png)

**Comment by Thermi** [comment]
Can I somehow get assistance in this issue? This is quite important for the company I'm working for.

**Comment by jaygorrell** [comment]
Started getting this myself today. We have a HA master setup of 3 -- only one of them jumped from 10% to 90% cpu and is staying there. Using top shows it's just kube-apiserver taking up all of it.

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by kargakis** [comment]
Please reopen if it's still an issue in later versions

**Comment by zhangxiaoyu-zidif** [comment]
I have the same issue, in kubernetes v1.6.9. 3 apiserver, only one's CPU is high, and other two stay low.
