### ISSUE TITLE
Deleting a cluster from the federation doesn't clean up DNS entries

### ISSUE THREAD

**Issue by saturnism** [kubernetes/kubernetes#36657]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:19:49Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**: OSX, GKE
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): GCI
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
When deleting a cluster from a federation, it doesn't clean up any of the DNS records associated w/ that cluster.

**What you expected to happen**:
Deleting a cluster from federation should delete related resources.

**How to reproduce it** (as minimally and precisely as possible):
1. Create a federation w/ 2 clusters
1. Provision a federated service w/ healthy backends
1. See that the DNS entries were created in the cloud provider
1. Delete a cluster from the federation

**Anything else do we need to know**:

**Comment by quinton-hoole** [comment]
Thanks @saturnism.  This is currently by design, although I agree that it could be argued that this is not the ideal behavior.

**Comment by saturnism** [comment]
If the DNS is not cleaned up, or, w/o easy way to clean up, the IPs they point to could easily be pointing to systems you don't own. Other issues follows.

Maybe an option to cascade deletion?

**Comment by quinton-hoole** [comment]
Yes, @nikhiljindal is working on the cascading deletion option.

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/issues/29335 is also related

**Comment by quinton-hoole** [comment]
Pretty sure that this is resolved now, but we need to double-check, and ensure that there's a test for it.  Leaving open for now.  Required for federation GA.

**Comment by quinton-hoole** [comment]
@nikhiljindal Can you confirm whether this is resolved or not.  Are you still working on it?  If not, could you please unassign yourself.  Thanks.

**Comment by mozhuli** [comment]
@quinton-hoole  I also meet the same problems when i use 1.7.5 in GCP, the dns records still remains when service has no healthy endpoints or the service has been deleted or cluster has been unjoined.

And there a another bug. When i unjoin cluster2, the service,deployment etc. created by federation still remain in the cluster2. 
```
$ kubectl get clusters --context=kfed
NAME       STATUS    AGE
cluster1   Ready     1h

kubectl get svc nginx  --context=kfed
NAME      CLUSTER-IP   EXTERNAL-IP      PORT(S)   AGE
nginx                  35.201.169.250   80/TCP    1h

$ kubectl get svc nginx --context=cluster2
NAME      CLUSTER-IP      EXTERNAL-IP     PORT(S)        AGE
nginx     10.59.247.245   35.194.121.43   80:31079/TCP   1h

$ kubectl get  deployment  --context=kfed
NAME               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment   3         3         0            3           1h

$ kubectl get  deployment  --context=cluster2
NAME               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment   2         2         2            2           1h

```

**Comment by quinton-hoole** [comment]
We should add an e2e test for the unhealthy endpoints and deleted federated service cases.  Those events should cause the DNS records to be updated/deleted.

As for unjoining a cluster, that by design does not automatically delete anything from the cluster.  You should do that before unjoining the cluster.

**Comment by nikhiljindal** [comment]
Sorry for the delayed update. Didnt get a chance to work on this. Unassigning so that someone else can pick it up.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#80.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
