### ISSUE TITLE
kubectl on windows seems slow...

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#36653]
Not sure why, but `kubectl.exe` on windows feels really slow, we should investigate some more.

**Comment by sebgoa** [comment]
yup, noticed that as well. fyi: there are a few minikube improvements needed for windows as well.

https://github.com/kubernetes/minikube/issues/651

**Comment by LeiYangGH** [comment]
also notice that, as a user only.

**Comment by AaronM04** [comment]
I am also experiencing this issue. With my phone's stopwatch functionality, I timed running `kubectl` on Windows 10 (64 bit), and it took 30.72 seconds.
