### ISSUE TITLE
Ensure that logs from all Kubernetes components on the master are being collected

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#36656]
Log should be collected by both jenkins and fluentd.

follow up https://github.com/kubernetes/kubernetes/issues/34679#issuecomment-259656118

**Comment by bprashanth** [comment]
gke master logs in jenkins output would help a LOT in root causing test flake, fwiw, though I'm assuming this issue doesn't apply

**Comment by piosz** [comment]
@bprashanth do you mean publicly available in gubernator as artifacts?

**Comment by bprashanth** [comment]
Yes
