### ISSUE TITLE
[CRI] Serve streaming requests from pod namespaces

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#36667]
Address TODO [here](https://github.com/kubernetes/kubernetes/blob/2822e4fd78ca2f448317f97acb551f8e23b5cd58/pkg/kubelet/server/streaming/server.go#L178) and [here](https://github.com/kubernetes/kubernetes/blob/2822e4fd78ca2f448317f97acb551f8e23b5cd58/pkg/kubelet/server/streaming/server.go#L195).

Requires pod-level cgroups for dockershim implementation (https://github.com/kubernetes/kubernetes/issues/27204)

/cc @kubernetes/sig-node

**Comment by resouer** [comment]
@timstclair Are you implying long running streaming server should be added to Pod level cgroup (and Guaranteed tier I think)?  pod-level cgroups for dockershim has been merged, that's why I'm asking.

**Comment by timstclair** [comment]
Yes, but a couple of things to note:

- The per-pod streaming server will not be long-running. It should be shutdown once the streaming connection is terminated
- You're correct that it uses a bit more resources, but the cost should be minimal (streaming server should be small, number of simultaneous servers should be small, and the ports will be in the pod IP). This is the cost of better resource accounting & isolation.
- It adds some complexity since the shim will need to coordinate / communicate with multiple server processes.

**Comment by liggitt** [comment]
would this mean giving a process in the process in the pod namespace access to a TLS serving cert/key that was valid for the node's hostname as seen by the API server?

**Comment by timstclair** [comment]
Yes, the way we are currently thinking about auth, it would. That sounds like a risk of leaking the credentials. The tokenized approach in https://github.com/kubernetes/kubernetes/pull/38742 might make client cert auth unnecessary, but there's still a threat of server-side spoofing (MITM). Any suggestions?

**Comment by liggitt** [comment]
> the way we are currently thinking about auth, it would

auth aside, you still need a serving cert, valid for the kubelet's IP and/or DNS name, signed by a CA the API server trusts, so the API server can verify the serving cert when it makes the connection to the streaming server. I *really* don't want to put trusted certs that close to pod processes

**Comment by tallclair** [comment]
I think we can close this for now, since streaming will be proxied through the kubelet going forward. See:
- https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1558-streaming-proxy-redirects
- kubernetes/enhancements#1558
