### ISSUE TITLE
Generated client should not create file per resource

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#36661]
Otherwise we'll need to do some *bad* stuff to make Bazel work. We currently create a file per resource (pod.go, service.go, etc.). The problem is that Bazel can't handle that, as it requires well known list of output files to work. Can we just put all generated clients in a single client.go file?

cc @mikedanese @thockin @wojtek-t

**Comment by mikedanese** [comment]
I beat you to this one :) dup of https://github.com/kubernetes/kubernetes/issues/36082
