### ISSUE TITLE
scheduledjob/cronjob is missing in the OpenAPI spec

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#36682]
@pwittrock found that scheduledjob/cronjob is missing in the swagger spec. It's because batch/v2alpha1 isn't on by default. 

From @mbohlool: 
> for static version we have in source tree, we should enable as much apis as possible

Hope to get this in for 1.5 

cc @kubernetes/sig-api-machinery @erictune @soltysh

**Comment by caesarxuchao** [comment]
I agree we should generated spec for it. However, it's an alpha feature, so it shouldn't be turned on by default.

**Comment by mbohlool** [comment]
@caesarxuchao I agree. The title is miss-leading. My PR is not enabling it by default but generate spec for it.
