### ISSUE TITLE
Kubeadm should have provision to BUILD and install k8s from git url

### ISSUE THREAD

**Issue by sandys** [kubernetes/kubernetes#36697]
I would also request that kubeadm have the ability to *build* and install k8s. At the pace that k8s is changing...we would like to dogfood a lot of upcoming k8s changes. If kubeadm can be pointed to a git URL and have it build that k8s version and use it for install/upgrade...that would be a godsend.

For example, we have been blocking on several changes in ingress controllers (for ssl passthrough) and waiting for packaging takes too long. We would love to be able to build and install in one step.

Please note, I'm not referring to building k8s inside a single docker image. I'm talking about building and installing components of k8s (using kubeadm) by pointing to a git url (branch/tag/version/etc) and having the install and upgrade to work

**Comment by davidchua** [comment]
:+1:

I too would like to be able to do just that. It would help greatly to be able to test upcoming kubernetes versions before hand.

**Comment by luxas** [comment]
This is something we probably are going to do, at least for testing.
Follow along when we have made the kubernetes/kubeadm project, which I hope will happen soon.

Thanks for the issue :+1:, I strongly think we need something like this.

**Comment by sandys** [comment]
Thanks for the reply!
A lot of us are not sure on the timelines for this. Will this happen in time for 1.5 ? Or will this be later...in which case would it make sense to have this functionality fairly quickly .

Sorry for being a bother.

**Comment by luxas** [comment]
This will be something we hopefully will do in time for v1.6.
The v1.5 window has already passed some weeks ago.

Please take a look at this document to get an understanding of what we will prioritize in time for v1.6:
https://docs.google.com/document/d/1v4k7eN-eetHbbpTAG7WuioRAMsK_FVGi1yC3VIn4Inw/edit#

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#3
