### ISSUE TITLE
[Federation] Make federation controller manager DNS provider flag configurable in `kubefed`

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#36690]
`kubefed init` brings up federation controller manager with `--dns-provider=google-clouddns` hard coded. This causes a lot of inconvenience for non-GCP users. This also makes non-GCP testing very difficult and we need to fix this.

Assignee: @irfanurrehman (GH won't let me assign this issue to @irfanurrehman, so assigning it to myself in the right hand labels but making it clear here).

cc @kubernetes/sig-cluster-federation @saad-ali @nikhiljindal

**Comment by saad-ali** [comment]
Since it is post-code freeze, clarifying: is this a bug fix? If so, please update the PR description with a reference to bug. Removing milestone label until verification.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @madhusudancs

**Comment by madhusudancs** [comment]
Already fixed in PR #36492.
