### ISSUE TITLE
Test g1-small node sizes or recommend against them. 

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#36701]
I see a user on stackoverflow using `g1-small` and seeing kube-proxy getting terminated.

[StackOverflow question](http://stackoverflow.com/questions/40564218/kubernetes-on-gce-prevent-pods-undergoing-an-eviction-with-the-node-was-low-o)

I can't tell if that is user setup error or kubernetes bug, or if `g1-small` is just not a good idea.
We don't run any e2e tests using `g1-small`, and we don't specifically advise against them.

We should do one or the other.

**Comment by roberthbailey** [comment]
I think this is a documentation issue.

**Comment by roberthbailey** [comment]
As discussed at the recent contributor summit we would like the system to more gracefully scale to small node and cluster sizes. I'm not sure if that gets all the way down to a 1 node g1-small, but we need documentation to define the smallest size in either case.
