### ISSUE TITLE
[k8s][PV] PV size cannot guarantee the data size

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#36710]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
I have a host as a storage server and has 1G disk, I created a PV as 20M, and then created a PVC on this PV, but I found that I can write data to the PVC even if the data size is greater than 20M, so how can I guard this? I want to write at most 20M data to this PV, if the data size is greater than 20M, then the write operation should be failed.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by gyliu513** [comment]
cc @coffeepac

**Comment by msau42** [comment]
@gyliu513 You need to partition the disk or use filesystem quota to have capacity isolation.  If this is just temporary data, then starting in 1.7, you can specify a size limit on EmptyDir volumes.

**Comment by gyliu513** [comment]
@msau42 yes, the 1.7 has fixed this issue, thanks!
