### ISSUE TITLE
GlusterFS Volume Provisioner not creating volumes with default 'replicate' durability type.

### ISSUE THREAD

**Issue by davidchua** [kubernetes/kubernetes#36725]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
Yes

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
- glusterfs
- volume
- provisioning

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"clean", BuildDate:"2016-10-16T06:36:33Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:13:36Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: On-prem VSphere
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04 LTS
- **Kernel** (e.g. `uname -a`):
- **Install tools**: Kubeadm
- **Others**:
- Heketi
- GlusterFS

**What happened**:
When provisioning a GlusterFS volume via PVC, GlusterFS volume is created but with a durability_type of "None" instead of "replicate" according to:

https://github.com/kubernetes/kubernetes/blob/4e393fadf3df60bc15696e9d965f635fefb2a6e9/pkg/volume/glusterfs/glusterfs.go#L60

When doing a `heketi volume info` on the created PV, this is the result:

```
[root@415dd3a6d47d /]# heketi-cli volume info 2f85f8c8c7eabf2daf3b50065bf3160d
Name: vol_2f85f8c8c7eabf2daf3b50065bf3160d
Size: 5
Volume Id: 2f85f8c8c7eabf2daf3b50065bf3160d
Cluster Id: 0ea05409eedd61cf1678d2e8693bdae8
Mount: 10.130.7.153:vol_2f85f8c8c7eabf2daf3b50065bf3160d
Mount Options: backup-volfile-servers=
Durability Type: none
```

**What you expected to happen**:

Durability Type should be `replicate`.

**How to reproduce it** (as minimally and precisely as possible):

- Create a default storageclass for glusterfs that points to heketi's REST server
- In your PVC, use glusterfs StorageClass

```
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: glusterclaim-1
      annotations:
        volume.beta.kubernetes.io/storage-class: "glusterfs"
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "5Gi"
```

- After doing a `kubectl get pv`, notice that the PV is created and bounded to the claim
- Connect to the heketi server and do a `heketi volume list` and do a `heketi volume info` on the newly created volume.
- You should notice that the volume is created with a Durability Type of 'none'

**Anything else do we need to know**:

**Comment by humblec** [comment]
@davidchua this is fixed by https://github.com/kubernetes/kubernetes/pull/32662.  The latest master should have the fix.
