### ISSUE TITLE
SecurityContext privileged not working as expected...

### ISSUE THREAD

**Issue by derailed** [kubernetes/kubernetes#36729]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

Docker privileged securitycontext

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

1.4.1

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

Linux m15 4.4.24-hypriotos-v7+ #1 SMP PREEMPT Tue Oct 11 17:15:58 UTC 2016 armv7l GNU/Linux

**What happened**:

I have a Docker image that accesses /sys/devices. When I run the container by hand on that box using the following cmd, the application works as expected.

docker run -it --privileged  fred

However is I set up the same image under kubernetes using the following yaml, the application fail on the very same box. 

kind:       Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fred
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name:  fred
          securityContext:
            privileged: true
          image: fred

**What you expected to happen**:

Setting the podSecurityContext privilege option works as if I ran the container with docker directly.

Perhaps I am missing the intent here, but I was expecting this to work and if not what else do I need to specify to allow the container to access system level resources on the host machine.  I have tried setting the runAsUser to root but to no avail. 

**How to reproduce it** (as minimally and precisely as possible):

Sadly not short way to repro + using private docker image 

**Anything else do we need to know**:

I need to tell kubernetes that this container needs to run with the docker --privileged argument. How does one achieve this behavior.

**Comment by dims** [comment]
Are you running both apiserver and kubectl with --allow-privileged=true flag? can you try that then deploy your container (and check logs to see if there are any issues)

**Comment by derailed** [comment]
Hi Davanum,

  Thanks for the reply! I assume you mean kubelet and not kubectl?

  On master
    The kube-apiserver is running with --allow-privileged
    The kubelet is running with --allow-privileged=true

  On minion
    The kubelet is running with --allow-privileged=true

**Comment by dims** [comment]
oops. yes. kubelet. Anything in the logs @derailed ?

**Comment by derailed** [comment]
I am not seeing anything in the logs, but did see something a bit
suspicious running docker inspect on the manual container vs the kubernetes
launched container. Not super sure of the implications here but here is
some deltas:

First the k8s docker container is indeed running with privileged:true so
the securityContext option seems to be working as expected.

Here are some deltas

Manual docker run
------------------------
"SecurityOpt": [
  "label=disable"
],
...
"Devices": [],

Kubernetes Launched container
----------------------------------------
"SecurityOpt": [
  "seccomp=unconfined"
],
...
"Devices": null

Wondering if the Devices: null setting is causing me the grief here and
overrides the privileged option to access the system /dev dir?? Is the a
way in k8s for me to set devices=[] in the pod specification?

Thank you!






On Mon, Nov 14, 2016 at 12:18 PM, Davanum Srinivas <notifications@github.com

**Comment by dims** [comment]
@jessfraz : Any ideas on this issue? PTAL when you get a chance

**Comment by derailed** [comment]
All, 

  Any updates on this issue? Things I could try out or would not mind a work around if any?

I have a deadline coming up and would love to have my containers launched k8style vs dockerstyle

Thank you!!

**Comment by liggitt** [comment]
is this still an issue?
cc @kubernetes/sig-node-bugs

**Comment by scheng1** [comment]
@scheng1
