### ISSUE TITLE
A flake issue for #36737 PR

### ISSUE THREAD

**Issue by YuPengZTE** [kubernetes/kubernetes#36739]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by madhusudancs** [comment]
@YuPengZTE thanks for the report. Here is an example of a report that contains useful information about the flake - Issue #36262 for future reference. Also, the PR where you saw the test failure is a legitimate failure caused due to the changes introduced in the PR. So I am closing this PR.

**Comment by YuPengZTE** [comment]
@madhusudancs thanks a lot.
