### ISSUE TITLE
kubectl get node(s) should show all node conditions

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#36733]
Currently we only show Ready/NotReady, but there are several node conditions that affect schedulability and we don't show any of them (e.g. NetworkUnavailable). We do show SchedulingDisabled but that's talking about something different. My suggestion would be to change Ready/NotReady to Ready/NotSchedulable/NotReady (and keep SchedulingDisabled).  NotSchedulable would be set when Ready is true but one of the conditions that prevent scheduling is also true.

**Comment by k82cn** [comment]
Will `NotSchedulable` dependent on scheduler, policy and Pod's description ?

**Comment by bgrant0607** [comment]
This would have to be `get -o wide` and/or `describe`.

**Comment by davidopp** [comment]
describe is so verbose as to be useless when looking at multiple nodes. `-o wide` would be fine.

> Will NotSchedulable dependent on scheduler, policy and Pod's description ?

I was thinking of just conditions that block scheduling for all pods and are expected to be respected by all schedulers. But now that I think about it, probably the better thing to do is to wait until we have converted the node conditions that block scheduling into taints, and then just show taints in `kubectl get nodes -o wide`

**Comment by ravisantoshgudimetla** [comment]
@davidopp I have the same question as @k82cn. What would `NotSchedulable` depend on and where does it come from?

**Comment by k82cn** [comment]
> [davidopp]: But now that I think about it, probably the better thing to do is to wait until we have converted the node conditions that block scheduling into taints, and then just show taints in kubectl get nodes -o wide

@ravisantoshgudimetla , "just show taints" makes more sense to me.

**Comment by ravisantoshgudimetla** [comment]
@k82cn, Thanks for clarification. I read that yesterday but was having a question regarding the field as such. So, just to be clear:

- We are not going to change the status to have an additional value for status field called `NotSchedulable`.
- We are going to have a new field called taints and this shows all the existing taints or the one designated as nodecondition taints?

**Comment by nikhita** [comment]
/remove-lifecycle frozen

Removing help-wanted since the directions are not clear enough for a contributor to dive into.
/remove-help

**Comment by zgfh** [comment]
for now, try this:
```
kubectl get node -o=jsonpath="{range .items[*]} {'\n'} {.metadata.name}{'\t'} {range .status.conditions[*]}{.type}{':'}{.status}{'\t'}{end} {end}"
```
