### ISSUE TITLE
cni plugin should not be called twice to delete one single interface

### ISSUE THREAD

**Issue by CaoShuFeng** [kubernetes/kubernetes#36746]
When I run the following two commands:
$: kubectl run nginx --image=nginx --replicas=3 --namespace demo
$: #wait until  pods run
$: kubectl delete deployment nginx --namespace demo

In the log I can see that cni plugin is called twice to delete the same interface because of graceful deletion feature in kubelet.
http://paste.openstack.org/show/589119/

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.182+13cc43af826a5d", GitCommit:"13cc43af826a5d2769543e91d13c93dd68c6f809", GitTreeState:"clean", BuildDate:"2016-11-08T04:42:35Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.477+d5014c3f216204-dirty", GitCommit:"d5014c3f216204c2a8464a5bdf543f408eee6f71", GitTreeState:"dirty", BuildDate:"2016-11-14T11:01:41Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **OS** (e.g. from /etc/os-release): 
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- **Kernel** (e.g. `uname -a`):
Linux calico-01 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**What happened**:
cni plugin is called  twice to delete one interface

**What you expected to happen**:
It should be deleted only once.

**Comment by yujuhong** [comment]
See #43014

**Comment by bowei** [comment]
@yujuhong -- reopen if still relevant -- I think we resolved that CNI plugins should be able to gracefully handle multiple calls to delete
