### ISSUE TITLE
Timestamps in events should have (at least) millisecond granularity.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#36752]
Currently we truncate them and store them with second granularity which is not enough - it causes problems in debugging (events from the same second are in pretty much random order), and it's not precise enough for performance benchmarking.

cc @dchen1107 @erictune @smarterclayton @timothysc @fgrzadkowski @wojtek-t and I guess @kubernetes/sig-instrumentation

**Comment by timothysc** [comment]
Should we rely on events for performance testing or start to investigate tracing?

**Comment by smarterclayton** [comment]
@derekwaynecarr since you did all the event compression / truncation stuff.

**Comment by gmarek** [comment]
I think that we can get events faster, as the only thing that needs to be done is to increase timestamp granularity. If we have someone who can instrument the code for us, it's fine, but I guess it'll take a release or two.

**Comment by bgrant0607** [comment]
See also #15262

**Comment by gmarek** [comment]
Which means that more devs think this is a problem.

**Comment by gmarek** [comment]
I created the PR that does the change, to see how it impacts the system. The problem is that there's no easy way to change it in Events only, thus all timestamps in the system will have millisecond granularity, which makes this change way harder to introduce than I anticipated...

**Comment by smarterclayton** [comment]
Changing the serialization unversioned.Time is a breaking API change which
has impacts for clients.

**Comment by gmarek** [comment]
Yup - I commented about this in PR, but I probably should have done it here:

This changes precision of timestamps generated by the system. Let's continue discussion in the issue to decide if we want to merge this. In current implementation there's no easy way to change this is Events only, so it's a system wide change.

This means that it needs to be backward compatible (we need to be able to parse both millisecond and second timestamps). We don't have a way to support rollbacks without adding an ability to parse milliseconds in one release, and actually change it in the next one...

**Comment by xiangpengzhao** [comment]
+1 for the millisecond granularity. It's hard to identify events from the same second when debugging in our PaaS project now.

**Comment by timothysc** [comment]
Why has this been re-opened?

**Comment by gmarek** [comment]
It's not done yet.
