### ISSUE TITLE
The kubeadm command parameter '--external-etcd-endpoints' validation error

### ISSUE THREAD

**Issue by mritd** [kubernetes/kubernetes#36754]
When using the `kubeadm init --external-etcd-endpoints` command, if `etc` is on the same host as `kubernetes master`, `kubeadm` will verify that the `2379` port is enabled and the `/var/lib/etcd` directory exists , Which causes kubernetes to fail to use the extended etcd cluster.

**Comment by luxas** [comment]
Hi!

Can you please file this issue in [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues) instead?
We're aggregating the issues there now. Sorry for the inconvenience if any.

Thank you in advance!
