### ISSUE TITLE
Templates syntax: how to _not_ specify an env var

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#36750]
I am not sure of the status of the templates proposal, but a requirement came up to optionally specify an env var https://github.com/kopeio/kexpand/pull/8 cc @yissachar

Can this be done using the proposed templates syntax?

**Comment by bgrant0607** [comment]
cc @pwittrock @bparees

**Comment by bparees** [comment]
this should be covered in two ways:

1) you can parameterize the value of the env var (so you can set it to empty string).  that's not quite the same as not setting it, but might be close enough for your purposes.
2) you can use the $((KEY)) substitution syntax to substitute a full json blob, meaning you could define the entire pod template's env array as a parameter reference, and provide whatever json-formatted list of env vars you want as the parameter value at template instantiation time.

**Comment by spiffxp** [comment]
/sig service-catalog
because https://github.com/kubernetes/kubernetes/issues/23896 is tagged as such as well

/sig apps
because this seems like a fit given their work with helm

**Comment by bgrant0607** [comment]
Closed #23896, so closing this also.
