### ISSUE TITLE
Links to related object in json responses

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#3676]
User @abonas requested that a GET of services or replicationcontrollers should include links to the pods that constitute that service or replicationcontrollers.    I filed this issue to discuss that idea. 

Questions:
- is this a priority right now given that clients can figure this out through multiple REST calls? 
- is it practical to do this, given that we don't have the ability to e.g. atomically read a service object and select its pods.
- would links include resourceVersion (probably not until we remember old objects)
- if we don't do something now, will it be hard to add later?
- where in our data structures would this information go?  
- would we use something home-grown, like we did with "self-link", or one of many standards for HATEOS-y json linking, such as JSON-LD, HAL, JSON-References (see https://www.mnot.net/blog/2011/11/25/linking_in_json for some discussion)

**Comment by bgrant0607** [comment]
Reverse label lookup #1348 is the intended solution. We plan to support this in the server. Kubectl already implements this in the client.

Users have the option of adding identifying annotations or labels if they choose.

**Comment by thockin** [comment]
FWIW, I think that showing the result of the selector as part of Service
and ReplicationController status would be good UX.

**Comment by bgrant0607** [comment]
Problems with this:
* GET of any object MUST be constant time. Either the status would be precomputed and stale, or we need to index the reverse lookups, which we plan to do, but it isn't done. And, it would still be racy.
* I want the Pod API on Kubelet to be THE SAME as the Pod API on the API server (#2483), and for it to populate the Pod status (#2726). It won't know about services unless it queries the apiserver.
* We're planning to convert ReplicationController to a plugin. Pods shouldn't know about them.

I'll reopen, but this is post-1.0 at best.

**Comment by thockin** [comment]
One of us is mis-parsing.  I don't want to know which replication
controllers a pod is under, I want to know which pods are under a
replication controller.

I'd be fine with the status being precomputed, if we thing a label
evaluation is too slow in real time.  It's guaranteed to be stale by the
time a user reads it, we'r just making that window a little wider.

The kubelet API knows nothing of replication controllers, so there is no
way for me to even ask this question.

As a plugin, replication controller can still either cache the pods IDs it
selects or else run a label query in series with a GET

**Comment by bgrant0607** [comment]
Oh, right, me. Well, the problem with THAT is the size of the list. We could include a link to the list query that would give you the pods.

**Comment by thockin** [comment]
I think worrying about the list size is premature.

**Comment by derekwaynecarr** [comment]
I don't see a pre compute problem here.  If I understand the request, they just want a link rel to follow that would be the default lookup.  In this manner, their UIs just follow the links rather than them doing manual URL construction.

**Comment by bgrant0607** [comment]
@thockin I disagree. It's not a scalable pattern. A link to the query is far preferable to a list of links to the pods. Then, the solutions we develop to deal with long lists will just work.

**Comment by thockin** [comment]
I'll take either one, but we can agree to disagree.  A JSON object with
1000 or 10000 lines of "pod-id" or "ip:port" is not too unreasonable.  I
guess I was assuming it would be a list of Ids or links, and not the full
body of each pod.  a link to a query sounds plausible, too.

**Comment by abonas** [comment]
@thockin  @derekwaynecarr  indeed just to confirm - you got this right :)
 This is NOT about getting from pod which service/rc "stalks" it, but rather getting from each service and each rc the pods they're after.
I think it's logical to get it from the api, and will minimize race conditions of changed entities/labels/selector like what @simon3z mentioned in #3623.

**Comment by abonas** [comment]
btw, getting the pod uids is enough, no need in full body of pods, since they are retrieved separately anyway.

**Comment by thockin** [comment]
What's your thoughts on getting a list of IDs vs getting a link to a query?

**Comment by bgrant0607** [comment]
Our objects are loosely coupled by design. A link to a query is reasonable. A list of pod references is not.

I'm going to cite the service redesign issue #2585, to ensure I don't forget about this.

**Comment by abonas** [comment]
@thockin list of IDs are more convenient from a link to query.
why? Because it:
1. saves a redundant request to make the query, the pods are pulled anyway and I can store them with their id as a key.
2. currently the query language is not exposed so it's not clear how it's doable anyway. see #341

**Comment by bgrant0607** [comment]
The redundancy will be eliminated: #2740.

You can query using labels already. It is even documented:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/labels.md
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/resthandler.go#L158

#341 is not relevant, since services and replication controllers cannot yet utilize the more general form of queries.

**Comment by bgrant0607** [comment]
Group thread about how to identify the pods of a replication controller:
https://groups.google.com/forum/#!topic/google-containers/WccX0G0Awqs

**Comment by bgrant0607** [comment]
Continuing discussion from #3872 and #3623:

We're moving away from status computed on-the-fly: #2726. 

Also, we're planning to support pruning out fields #1459, but will not add extra information that is not present by default. Such information has to be provided by a separate API endpoint.

Frequently changing, potentially huge lists in object status would be highly problematic, both internally and for the client-facing API, causing churn in etcd and in watches, and greatly increasing the cost of all GETs, even though the data would likely not be used in most cases. Additionally, consistency would be a problem.

We plan to address these problems for list objects, but not for subobjects within API objects.

We can add links (or structured list references) in status to this additional information. At this point, we plan to do this for resources and pods under a replication controller. I could be convinced to support it in some form for Endpoints, also, but not for Service itself, as we're almost certain to break it into multiple parts (#2585). If we do break up Service, its status would contain a link to the corresponding Endpoints. I imagine we'd also do this for any other instances of object references, such as replication controller to pod template (#170).

**Comment by simon3z** [comment]
> If we do break up Service, its status would contain a link to the corresponding Endpoints. I imagine we'd also do this for any other instances of object references, such as replication controller to pod template (#170).

@bgrant0607 what's the status of pod template? Is there anyone actively working on it? Do you think it will be included soon?

Once we'll have pod templates do you think it will be possible to do the same we did for endpoints? (mentioning the object references of the pod instances).

**Comment by bgrant0607** [comment]
@simon3z See PR #5012. 

Pods referring to templates (or RCs, since they'll still have embedded templates) from which they were created might be reasonable, perhaps as an annotation. Unlike Endpoints, I don't see an operational need for this, just a UX one.

**Comment by simon3z** [comment]
@bgrant0607 so Pods could (hoping: "will") have a reference to their Template and RC will have a reference to the relevant Template as well right? So I'll be able to correlate RC and Pods through the Templates. Correct?

**Comment by bgrant0607** [comment]
@simon3z RCs will, out of necessity. Pods could, via an annotation applied by the RC -- PR welcome.

**Comment by simon3z** [comment]
Thanks @bgrant0607 I'll be glad to handle that!

**Comment by bgrant0607** [comment]
We should at least translate the selectors in API resources to selectors that can be passed as get/watch filters so that the client doesn't have to do it. As discussed in #15350, requiring clients to perform the translation impedes extensibility of the selector expressions.

**Comment by kargakis** [comment]
I think owner references are covering this issue now, please reopen if this does not hold true.

**Comment by bgrant0607** [comment]
@kargakis I reopened. Owner references link from pods to their controller. This is about the other direction. The client needs fairly deep knowledge of the API in order to be able to find the selector field, understand what type of resource it refers to, and translate the selector into the syntax used by the API query parameter.

**Comment by kargakis** [comment]
/sig api-machinery 

then

**Comment by bgrant0607** [comment]
Related: #22675

**Comment by bgrant0607** [comment]
@kubernetes/sig-api-machinery-feature-requests
