### ISSUE TITLE
kubeadm init fails preflight checks on default install in Ubuntu Xenial

### ISSUE THREAD

**Issue by sumdog** [kubernetes/kubernetes#36766]
I've been writing some Ansible scripts to automate my setup. In one of the recent package updates, I get a preflight check failure on my first run of `kubeadm` because it finds stuff in `/var/lib/kubelet`:

```
fatal: [master]: FAILED! => {"changed": true, "cmd": ["kubeadm", "init", 
"--token=123456.abcdefghijklmnop", "--api-advertise-addresses=10.42.42.10"], "delta": 
"0:00:00.138378", "end": "2016-11-14 19:38:50.079684", "failed": true, "rc": 2, "start": "2016-11-14 
19:38:49.941306", "stderr": "preflight check errors:\n\t/var/lib/kubelet is not empty", "stdout": 
"Running pre-flight checks", "stdout_lines": ["Running pre-flight checks"], "warnings": []}
```
When I check the folder, I just see two empty folders: `plugins` and `pods`. If I run `dpg -S` on either of these two packages, no package claims/owns them.

These are the packages I install:

```
- apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg
- apt_repository: repo="deb http://apt.kubernetes.io/ kubernetes-xenial main" state=present
- action: apt update_cache=yes
- action: apt name=docker.io
- action: apt name=kubelet
- action: apt name=kubeadm
- action: apt name=kubectl
- action: apt name=kubernetes-cni
```

Here are the versions I'm currently working with:

```
dpkg -l  | grep kube
ii  kubeadm                          1.5.0-alpha.2-421-a6bea3d79b8bba-00 amd64        Kubernetes Cluster Bootstrapping Tool
ii  kubectl                          1.4.4-00                            amd64        Kubernetes Command Line Tool
ii  kubelet                          1.4.4-01                            amd64        Kubernetes Node Agent
ii  kubernetes-cni                   0.3.0.1-07a8a2-00                   amd64        Kubernetes CNI
```

I'm not sure what's creating those two folders, but either the preflight checks should ignore those empty folders or the package maintainers need to ensure those directories don't get created. 

Here's my OS version:

```
# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```

The Vagrant/Ansible scripts to replicate this issue are here:

https://gitlab.com/djsumdog/skube (commit a349eb)

Vagrant: 1.8.6
Ansible: 2.1.2.0

**Comment by luxas** [comment]
Hi!

Can you please file this issue in [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues) instead?
We're aggregating the issues there now. Sorry for the inconvenience if any.

Thank you in advance!
