### ISSUE TITLE
Error: Go-yaml control characters are not allowed

### ISSUE THREAD

**Issue by Pensu** [kubernetes/kubernetes#36763]
Hi all,

I have been trying to run kubernetes e2e tests on ppc64le platform using go1.7. All the conformance tests are failing with the same error. Here is the error that I am getting:

`Couldn't delete ns: yaml: control characters are not allowed (&errors.errorString{s:"yaml: control characters are not allowed"})`

Every single test fails with this error. Any idea where should I start debugging from? TIA.

**Comment by bgrant0607** [comment]
cc @luxas

**Comment by spiffxp** [comment]
/sig release
because this is an alt-arch problem, though I'm unsure if it still exists given then inactivity

**Comment by Pensu** [comment]
It's fixed, rebooted the cluster, didn't get the error, closing the issue.
