### ISSUE TITLE
Shoot master e2e test

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#3679]
Need e2e test where some state is put into the master, then the master is rebooted, then it comes back and the state is still there because it was persisted by etcd.

**Comment by ihmccreery** [comment]
@davidopp I'm removing the `team/test-infra` label, but reapply it if you think the current infra is insufficient for you to be able to do this.

Might be hard for GKE, @kubernetes/goog-gke

**Comment by kargakis** [comment]
Any progress on this one @kubernetes/sig-testing-misc

**Comment by fejta** [comment]
We have the reboot suite and `[Disruptive]` tag
