### ISSUE TITLE
should enable quorum-read by default in HA env

### ISSUE THREAD

**Issue by sandflee** [kubernetes/kubernetes#36791]
we deploy k8s in HA mode, and encountered namespace not found while creating default serviceAcount, the main path is :
1,  request apiserver A to create a namespace 
2,  controller manager watched it and may request apiserver B to create serviceAcount
3,  apiserverB couldn't find the corresponding namespace even if it tries to get from etcd

we solved this by enable quorum-read in apiserver,  seems this should be enabled by default in ha deployment or we could add to doc to notify users.

**Comment by liggitt** [comment]
I'm not sure we want quorum read on by default. The service account controller will retry the creation in 1.5 if it encounters errors.

cc @smarterclayton

**Comment by smarterclayton** [comment]
We've run Kube HA with quorum read off for the better part of a year as the default configuration for OpenShift, and have only encountered a few issues like this.  So unless we have a concrete reason to change, I would like to avoid that.

**Comment by liggitt** [comment]
Closing since the referenced issue is fixed in 1.5
