### ISSUE TITLE
kubeadm with external etcd failure

### ISSUE THREAD

**Issue by Dm3Ch** [kubernetes/kubernetes#36790]
**Kubernetes version** (use `kubectl version`):
`kubeadm version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.2.421+a6bea3d79b8bba", GitCommit:"a6bea3d79b8bbaa5e8b57482c9fff9265d402708", GitTreeState:"clean", BuildDate:"2016-11-03T06:54:50Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Cloud provider or hardware configuration**: baremetal
- **OS** (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`):
`Linux Dm3Ch-Server-Node1 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**:
- **Others**:

**What happened**:
``` root@Dm3Ch-Server-Node1:~# kubeadm init --pod-network-cidr=172.16.0.0/12 --external-etcd-endpoints=192.168.1.2:2379,192.168.1.10:2379,192.168.1.11:2379
Flag --external-etcd-endpoints has been deprecated, this flag will be removed when componentconfig exists
Running pre-flight checks
preflight check errors:
        Port 2379 is in use
        /var/lib/etcd is not empty
```

**What you expected to happen**:
I expected that kubeadm would create master node with using external etcd cluster

**How to reproduce it** (as minimally and precisely as possible):
You should have external etcd cluster(one of the etcd nodes should be on your kubernetes master node) and you should run kubeadm init with ` --external-etcd-endpoints` option

**Anything else do we need to know**:

**Comment by Dm3Ch** [comment]
Hmmm, i thought it should be component/kubeadm, not component/apiserver. O_o

**Comment by luxas** [comment]
Hi!

Can you please file this issue in [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues) instead?
We're aggregating the issues there now. Sorry for the inconvenience if any.

Thank you in advance!
