### ISSUE TITLE
Unable to delete Job using batch client

### ISSUE THREAD

**Issue by floreks** [kubernetes/kubernetes#36806]
**Kubernetes version**: HEAD

**What happened**: Using `RESTClient` interface to delete Job throws an error `api.DeleteOptions is not suitable for converting to "batch/v1"`.

**What you expected to happen**: Job should be deleted.

We've found that issue after dependency update on dashboard: https://github.com/kubernetes/dashboard/pull/1408. We are using [RESTClient](https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/common/verber.go#L76) to delete resources. It works fine for all other resources. I've investigated that and it appears to be the core issue.

Other `pkg/apis` groups have `api.DeleteOptions` registered as a known type.
[apps](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/register.go#L53)
[extensions](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/register.go#L71)
[authentication](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/authentication/register.go#L49)

however batch is missing it
[batch](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/batch/register.go#L48)

After adding `api.DeleteOptions` I was able to successfully delete Job using our code.

I can quickly create PR for that. Just need a confirmation that this is indeed a bug.

cc @caesarxuchao @rf232

**Comment by rf232** [comment]
+1
apis/autoscaling is similar

**Comment by caesarxuchao** [comment]
I thought we only needed to register it in the external versions ([here](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/batch/v1/register.go#L43)). I'll double check. cc @smarterclayton.

**Comment by caesarxuchao** [comment]
Registering api.DeleteOptions in batch looks fine. In the future, I think it's more proper to register DeleteOptions and ListOptions as unversioned, like how we treat [ExportOptions](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/register.go#L131).

**Comment by smarterclayton** [comment]
DeleteOptions and ListOptions are expected to be in their group.  They have
to be in internal version and external version.  Most of this code will be
fixed in 1.6 (we'll standardize registering the "common" things).

**Comment by floreks** [comment]
I've created PR to fix this issue. Could anyone check that?
