### ISSUE TITLE
[resource quota] when Kubernetes update resource quota status

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#36808]
**Is this a request for help?**

Yes!

Recently, when I read the codes about resource quota, I find I got lost :)

My question is simple, when does admission controller update the resource quota object status in etcd? 

For example, when create 1 pod, we should update `resourceQuota.Status.Used.pods` to  `resourceQuota.Status.Used.pods+1`. I can find `podUsageFunc` [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/quota/evaluator/core/pods.go#L167), but  I just can't find how it update the resource quota record in etcd.

@derekwaynecarr @smarterclayton 

Would you please give me some clues? Thanks!

**Comment by m1093782566** [comment]
I already find it. Just Ignore it :)

**Comment by qinghai5060** [comment]
hi,
    I have the same confusion，when k8s update the used resource in resource quota. Besides that I am confused with when the init value in the used field is setted.
