### ISSUE TITLE
[federation] kubectl delete cluster doesn't clean controllermanager

### ISSUE THREAD

**Issue by lsztachanski** [kubernetes/kubernetes#36815]
**Kubernetes version** 

```Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}```

federation server:
```Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}```

cluster1:
```Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}```

cluster2
```Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}```

**Environment**:
- 2 GKE clusters
- federation setup from: https://github.com/kelseyhightower/kubernetes-cluster-federation

**What happened**:
I've added cluster with wrong `serverAddress`. Tried to delete it:

```kubectl --context=$FEDERATIONAPI delete -f clusters/$CLUSTER.yaml```

Which  removes cluster from the list:

```kubectl --context=$FEDERATIONAPI get clusters```

but `federation-controller-manager` produces constant errors:

```1115 13:09:09.297103       1 reflector.go:214] k8s.io/kubernetes/federation/pkg/federation-controller/service/clusterhelper.go:155: Failed to list *v1.Service: Get http://1.2.3.4/api/v1/services?resourceVersion=0: dial tcp 1.2.3.4:80: i/o timeout```

**Anything else do we need to know**:
- no trace of wrong address in etcd (federation-apiserver)
- deleting federation-controller-manager (spawned by deployment) fixes the issue

**Comment by pskrzyns** [comment]
cc @mfanjie

**Comment by lsztachanski** [comment]
I've increased verbosity.
Created random cluster (address with unresponsive API endpoint), removed it (kubectl --context=$FEDERATED-CLUSTER delete -f  cluster-definiton.yaml) and controller manager still produces errors:

`I1116 12:15:29.455180       1 reflector.go:403] k8s.io/kubernetes/federation/pkg/federation-controller/service/servicecontroller.go:238: Watch close - *v1beta1.Cluster total 16 items received
I1116 12:15:32.910862       1 reflector.go:403] k8s.io/kubernetes/federation/pkg/federation-controller/secret/secret_controller.go:166: Watch close - *v1.Secret total 0 items received
I1116 12:15:33.894680       1 reflector.go:403] k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller.go:110: Watch close - *v1beta1.Cluster total 26 items received
I1116 12:15:42.870881       1 reflector.go:403] k8s.io/kubernetes/federation/pkg/federation-controller/util/federated_informer.go:375: Watch close - *v1.Namespace total 0 items received
E1116 12:15:51.828052       1 reflector.go:214] k8s.io/kubernetes/federation/pkg/federation-controller/service/cluster_helper.go:156: Failed to list *v1.Endpoints: Get http://1.2.3.4/api/v1/endpoints?resourceVersion=0: dial tcp 1.2.3.4:80: i/o timeout
E1116 12:15:51.829434       1 reflector.go:214] k8s.io/kubernetes/federation/pkg/federation-controller/service/cluster_helper.go:155: Failed to list *v1.Service: Get http://1.2.3.4/api/v1/services?resourceVersion=0: dial tcp 1.2.3.4:80: i/o timeout
I1116 12:15:52.828456       1 reflector.go:249] Listing and watching *v1.Endpoints from k8s.io/kubernetes/federation/pkg/federation-controller/service/cluster_helper.go:156
I1116 12:15:52.830468       1 reflector.go:249] Listing and watching *v1.Service from k8s.io/kubernetes/federation/pkg/federation-controller/service/cluster_helper.go:155
I1116 12:15:55.913935       1 reflector.go:403] k8s.io/kubernetes/federation/pkg/federation-controller/util/federated_informer.go:284: Watch close - *v1beta1.Cluster total 22 items received
I1116 12:16:00.168526       1 reflector.go:403] k8s.io/kubernetes/federation/pkg/federation-controller/util/federated_informer.go:375: Watch close - *v1.Secret total 0 items received
`

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
This looks like a bug in cluster controller. I see that we are using watch so the controller should be notified immediately when the cluster is deleted.
Will be interesting to add a Log in the [delFromClusterSet](https://github.com/kubernetes/kubernetes/blob/d64434c056d291f967227266083c160962ab0ed7/federation/pkg/federation-controller/cluster/clustercontroller.go#L88) function and see if that comes up in logs as expected.

We should also add a test for this.
cc @kubernetes/sig-federation-bugs

**Comment by nikhiljindal** [comment]
Ref https://github.com/kubernetes/kubernetes/pull/42567 (doesnt fix the issue but adds some helpful logs).

While it will be great to have clean logs, this is not a release blocker. Moving out of 1.6 release

**Comment by quinton-hoole** [comment]
We need to resolve this before GA.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#81.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
