### ISSUE TITLE
Expose pod start time via the Downward API

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#36813]
Use-case: a Job or Pod that needs to set timeouts in various points in its lifecycle. For example, a deployer pod that has a global timeout to finish its work and various steps need to use a timeout too.

Deployer pod with a timeout of 10 minutes:
1. Scales down old replica sets for a deployment
2. Waits for all pods to be terminated
3. Executes *something*
4. Scales up new replica set

The wait part in the second step needs a timeout of (10m - (time.Now - podStartTime)). The only way to achieve this currently is to use a pod client in the pod and query the api server.

cc: @mfojtik @pmorie

**Comment by mfojtik** [comment]
I'm not sure about implementation as the creationTime is set in status after the Pod is created, which means having an env var that points to that field will always result to that env var being empty (because the vars are set before pod is created).

**Comment by kargakis** [comment]
@mfojtik creation time is metadata but I also think pod IP is accessible via the downward API, isn't that also status?

**Comment by liggitt** [comment]
also, creationTime != scheduled time != started time... I don't think I'd want processes in a pod timing anything from when the pod was created

**Comment by kargakis** [comment]
Right, we want the start time. But the status is still accessible via the downward api.

**Comment by bgrant0607** [comment]
cc @erictune @pmorie

**Comment by smarterclayton** [comment]
I think this is very reasonable to support.

**Comment by kargakis** [comment]
Or exec `uptime -s`

/close

**Comment by pcn** [comment]
> Or exec `uptime -s`

Uptime seems to reflect the hosts' uptime, and not that of the pod.
