### ISSUE TITLE
Master components should probably bind to 0 by default

### ISSUE THREAD

**Issue by sub-mod** [kubernetes/kubernetes#3681]
Currently in master.go line 195 . we have a code similar to below
package main

import (
        "fmt"
        "net"
)

func main() {

        addrs, err := net.InterfaceAddrs()
        if err != nil {
                fmt.Println("error ")
        }   

        for i := range addrs {
                ip, _, err := net.ParseCIDR(addrs[i].String())
                if err != nil {
                        continue
                }   

                if ip.IsLoopback() {
                        fmt.Println("Loopback found ", ip.String())
                        continue
                }   

                fmt.Println("IP = ", ip.String())
                break
        }   
}

As a result if a machine has multiple nics Assume eth0 and eth1 and i want kube traffic to go via eth1 and not via eth0.The above code would always cause eth0 to be picked up.And this become public IP of kube.
And there is no way to specify that eth1 should be only nic to be used.And public IP of kubernetes should be of nic eth1.
If this is a valid bug I suggest we support changing code in master.go line 195.and maybe adding a new variable in config files to define on which nic kube traffic should be allowed

**Comment by brendandburns** [comment]
Note that this code is _only_ called if ```c.PublicAddress``` is not set.  In the absence of a user specified address, listening on ```eth0``` seems like a reasonable thing to do.

You can override this behavior by setting ```--public_address_override``` to the address of ```eth1`` (or whatever interface you want)

I would be ok adding a config flag for ```PublicInterface``` if you want to dynamically discover the IP address for that interface, rather than specifying it.

**Comment by thockin** [comment]
This algorithm is slightly different from the one used in kube-proxy,
(which explicitly filters out p2p also and I think is more robust).  We
should maybe unify those.  But I don't understand this - I would assume the
lack of a public address should result in listening on 0.0.0.0, no?

**Comment by brendandburns** [comment]
We could do that.  That's not the current behavior.

**Comment by sub-mod** [comment]
proxy.go is another place i wanted to request to change the bindAddress IP.
I think to default to 0.0.0.0 is a good idea if we do it across all services If no nic preference is given.

**Comment by sub-mod** [comment]
@thockin just to confirm were you refering to https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/kube-proxy/proxy.go line ` bindAddress = util.IP(net.ParseIP("0.0.0.0"))` ?

**Comment by sub-mod** [comment]
@thockin oops Sorry wrong file proxier.go `chooseHostInterface` method ?

**Comment by sub-mod** [comment]
@brendanburns Can I fix this issue ?
1)unify  master.go code and proxier.go code by using the same method chooseHostInterface
2)Add a config paramater to dynamically discover the IP address for that interface if nic is given.

**Comment by thockin** [comment]
The proxier uses chooseHostInterface() just for iptables rules that require
an IP address.  That's not the default bind address.

I'd be happy to see a global change that we bind to all interfaces unless
explicitly told not to, but we need to carefully consider how this might
break people in surprising ways.  Consider that some VMs have an interface
that is exposed publicly.

**Comment by brendandburns** [comment]
Yeah, in particular in GCE we definitely _don't_ want to bind to 0.0.0.0

--brendan

**Comment by thockin** [comment]
Sorry, why not 0.0.0.0 in GCE?

**Comment by brendandburns** [comment]
because if the machine is on the external internet, it will be available on
the external internet.  (assuming firewall rules for the port) which is
unexpected, and likely unwanted.

--brendan

**Comment by thockin** [comment]
Maybe I am misunderstanding you.  GCE machines are not "on the external
internet" the same way Digital Ocean machines are.  For GCE, how does
binding to eth0 differ from binding to 0.0.0.0?  If you have an external IP
and the firewall is open, I see no functional difference...

**Comment by brendandburns** [comment]
Hrm, actually, I think you might be right.  Binding to 10.x will put you on
the external internet on GCE...

sorry for the noise.
--brendan

**Comment by sub-mod** [comment]
@thockin @brendanburns Just want to confirm that : defaulting 0.0.0.0 Address as PublicAddress is much better than picking the first NIC IP which could be anything docker/virtbox/virbr0/ ?

**Comment by thockin** [comment]
I *think* so, but we need to carefully consider the implications.  I saw
your PR and will take a look.  We might want to do this one binary at a
time so we can think deeply about what could go wrong.

**Comment by bgrant0607** [comment]
See also #222

**Comment by sub-mod** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/3719 this was a good discussion on why 0.0.0.0 can;t be default. Will just document about --public_address_override and PublicAddress for now.
It is better if we add a config paramater to dynamically discover the IP address + subnet  for each daemon based on --nic config. refer https://github.com/GoogleCloudPlatform/kubernetes/issues/3861

**Comment by thockin** [comment]
I still think we should probably bind to 0 by default, but yeah auto-choosing is v.hard.  I think I agree that speccing --bind-to as an interface name makes sense.  I definitely agree that we should make that flag consistent across the components.

I'm going to rename this bug and leave it open.
