### ISSUE TITLE
Need metrics in volume manager and controllers

### ISSUE THREAD

**Issue by rootfs** [kubernetes/kubernetes#36818]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

There is no metrics in volume manager and controllers (i.e. attach/detach and provision controllers). It is hard to get latency and stats.
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): 
metrics, volume

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
 FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by pwittrock** [comment]
@saad-ali Removing this from the milestone since code freeze is today

**Comment by saad-ali** [comment]
Added in PRs:
https://github.com/kubernetes/kubernetes/pull/40338
https://github.com/kubernetes/kubernetes/pull/43477
