### ISSUE TITLE
1.5: kubectl completion zsh is broken

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#36829]
I'm on the release-1.5 branch: a602b1181aa5e925ec2e1bf66c6d01fbd3ca6c14

**Comment by colemickens** [comment]
Didn't mean to hit enter on this. More info coming soon.

**Comment by AdoHe** [comment]
@colemickens could you provide your environment? IIRC I have already fixed a similar issue on my local

**Comment by colemickens** [comment]
Actually, this was a complete mistake on my part. Updated two things at once and erroneously suspected kubectl as the culprit. Closing...
