### ISSUE TITLE
kubeadm init starts paused containers on ubuntu 16.04

### ISSUE THREAD

**Issue by kilmarnock** [kubernetes/kubernetes#36825]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

https://github.com/kubernetes/kubernetes/issues/33729

they have a different bug
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
This is a BUG report

**Kubernetes version** (use `kubectl version`):
1.4.4
kubeadm init --use-kubernetes-version v1.4.6
kubeadm init --use-kubernetes-version v1.4.1
etc.

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
ubuntu 16.04
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

the containers stay in pause mode: docker.ps shows (sorry, i gave my best for table layout)
       COMMAND                 |                  NAMES
        ------------------ | ---------------------
        "kube-controller-mana"                  |        k8s_kube-controller-manager.
        "kube-scheduler --v=2"                   |       k8s_kube-scheduler.
        "/pause"                                            |       k8s_POD.d8dbe16c_kube-controller-manager-
        "/pause"                                             |     k8s_POD.d8dbe16c_kube-apiserver-
        "/pause"                                              |     k8s_POD.d8dbe16c_etcd-
        "/pause"                                               |    k8s_POD.d8dbe16c_kube-scheduler 

**What you expected to happen**:
start the api container at port 8080 / 6443

**How to reproduce it** (as minimally and precisely as possible):

I just followed the tutorials.
**Anything else do we need to know**:

I have nothing listening at port 8080 / 443 / 6443. I do not know which parts of the syslog could be helpful. The first part is here:
http://pastebin.com/TUk1qsms

then come **a lot** of `xy.service not handled by systemd`

and then the useless attempts to connect to the (paused) node:

`26360 manager.go:843] ignoring container "/system.slice/dev-hugepages.mount"`
`Nov 15 18:15:52 laptop kubelet[26360]: I1115 18:15:52.800147   26360 conversion.go:133] failed to handle multiple devices for container. Skipping Filesystem stats`
`Nov 15 18:15:52 laptop kubelet[26360]: E1115 18:15:52.825236   26360 eviction_manager.go:162] eviction manager: unexpected err: failed GetNode: node 'laptop.tu' not found`
`Nov 15 18:15:52 laptop kubelet[26360]: I1115 18:15:52.849907   26360 kubelet_node_status.go:203] Setting node annotation to enable volume controller attach/detach`
`Nov 15 18:15:52 laptop kubelet[26360]: I1115 18:15:52.854325   26360 kubelet_node_status.go:354] Recording NodeHasSufficientDisk event message for node laptop.tu`
`Nov 15 18:15:52 laptop kubelet[26360]: I1115 18:15:52.854354   26360 kubelet_node_status.go:354] Recording NodeHasSufficientMemory event message for node laptop.tu`
`Nov 15 18:15:52 laptop kubelet[26360]: I1115 18:15:52.854367   26360 kubelet_node_status.go:354] Recording NodeHasNoDiskPressure event message for node laptop.tu`
`Nov 15 18:15:52 laptop kubelet[26360]: I1115 18:15:52.854385   26360 kubelet_node_status.go:73] Attempting to register node laptop.tu`
`Nov 15 18:15:52 laptop kubelet[26360]: I1115 18:15:52.854410   26360 server.go:608] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"laptop.tu", UID:"laptop.tu", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeHasSufficientDisk' Node laptop.tu status is now: NodeHasSufficientDisk`
`Nov 15 18:15:52 laptop kubelet[26360]: I1115 18:15:52.854466   26360 server.go:608] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"laptop.tu", UID:"laptop.tu", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeHasSufficientMemory' Node laptop.tu status is now: NodeHasSufficientMemory`
`Nov 15 18:15:52 laptop kubelet[26360]: I1115 18:15:52.854594   26360 server.go:608] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"laptop.tu", UID:"laptop.tu", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeHasNoDiskPressure' Node laptop.tu status is now: NodeHasNoDiskPressure`
`Nov 15 18:15:52 laptop kubelet[26360]: E1115 18:15:52.854691   26360 kubelet_node_status.go:97] Unable to register node "laptop.tu" with API server: Post https://192.168.0.2:6443/api/v1/nodes: dial tcp 192.168.0.2:6443: getsockopt: connection refused`

It does this for the next couple of hours. Then I kick my laptop out of the window. Usually this stops the entrys.

What can I do? Where is the one parameter to rule the stuff? Do you need more information?

**Comment by kilmarnock** [comment]
Is this a (the) showstopper?

Nov 15 18:15:42 laptop systemd[1]: Started kubelet: The Kubernetes Node Agent.
Nov 15 18:15:42 laptop kubelet[26181]: error: failed to run Kubelet: invalid kubeconfig: stat /etc/kubernetes/kubelet.conf: no such file or directory
Nov 15 18:15:42 laptop systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Nov 15 18:15:42 laptop systemd[1]: kubelet.service: Unit entered failed state.
Nov 15 18:15:42 laptop systemd[1]: kubelet.service: Failed with result 'exit-code'.
Nov 15 18:15:52 laptop systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Nov 15 18:15:52 laptop systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Nov 15 18:15:52 laptop systemd[1]: Started kubelet: The Kubernetes Node Agent.
Nov 15 18:15:52 laptop kubelet[26360]: I1115 18:15:52.490229   26360 docker.go:375] Connecting to docker on unix:///var/run/docker.sock
Nov 15 18:15:52 laptop kubelet[26360]: I1115 18:15:52.490361   26360 docker.go:395] Start docker client with request timeout=2m0s
Nov 15 18:15:52 laptop kubelet[26360]: E1115 18:15:52.490508   26360 cni.go:163] **error updating cni config: No networks found in /etc/cni/net.d**
Nov 15 18:15:52 laptop kubelet[26360]: I1115 18:15:52.500218   26360 manager.go:140] cAdvisor running in container: "/system.slice/kubelet.service"
Nov 15 18:15:52 laptop kubelet[26360]: W1115 18:15:52.510257   26360 manager.go:148] **unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused**

For me it is difficult to decide because I thought kubeadm will generate the kubelet.conf. Now I read kubelet has to start before kubeadm.

**Comment by kilmarnock** [comment]
because the api container does not start, the whole system fails because it needs a connection to it.

**Comment by mikedanese** [comment]
This issue was moved to kubernetes/kubeadm#2
