### ISSUE TITLE
CreateOrJoinExternalLoadBalancer

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#3683]
We currently support CreateExternalLoadBalancer.
What if I have two or more kubernetes clusters and I want to put services in each one behind the same global load balancer (which I think would be a recommended practice).  
Need something that checks for an existing load balancer in a global space, and joins it if it exists, or else does one of the following:
  1. create it if it doesn't exist
  2. keep trying to join, under the assumption that the user will be creating it soon via an out-of-band mechanism.

**Comment by erictune** [comment]
We also need to think about how health checking would work in that scenario.  Does the External Load Balancer health check the serviceIP or its individual backends?  If the former, how does it do that?

**Comment by bgrant0607** [comment]
cc @quinton-hoole

**Comment by bgrant0607** [comment]
This is "Ubernetes clickstop 2".

**Comment by quinton-hoole** [comment]
@erictune One way to achieve what you're after is documented in docs/design/federated-services.md in PR #19313. 

In summary, user creates a single federated service, which creates the global load balancer you're after, as well as the local services in each cluster. 

I don't think that I detailed the health checking proposal there, but I've thought about it and discussed it with a few people and I think that a good approach is for the Load Balancer to health check the service IP's.

**Comment by quinton-hoole** [comment]
This is done in Federated Services and Cross-cluster Service Discovery in v1.3.
