### ISSUE TITLE
Refresh token requires id_token in response but openid spec it is optional 

### ISSUE THREAD

**Issue by jsloyer** [kubernetes/kubernetes#36847]
In the method [Refresh](https://github.com/kubernetes/client-go/blob/master/plugin/pkg/client/auth/oidc/oidc.go#L227-L253), there is a line to parse the response from an OpenID provider.  The [current implementation expects](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/client/auth/oidc/oidc.go#L237) an `id_token`.  However in the [Openid spec](http://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse) it states that `id_token` is not required on the response.

**Comment by jsloyer** [comment]
Moved from https://github.com/kubernetes/client-go/issues/40

**Comment by ericchiang** [comment]
Can someone assign me to this? cc @calebamiles 

All the links are broken, so I can't see where that's implemented.

**Comment by calebamiles** [comment]
done, @ericchiang

**Comment by liggitt** [comment]
copied additional details from duplicate issue https://github.com/kubernetes/kubernetes/issues/51501:

> Some OpenID Connect providers, namely Okta, don't return an id_token during a refresh[1]. The spec allows this[2] so their not non-compliant, but this means the error message when kubectl hits this case needs to improve[3]. Right now it's just:
> 
> ```
> Connection error: Get https://example.com:8443/api: token response did not contain an id_token
> ```
> 
> Maybe something long winded, like:
> 
> ```
> Connection error: Get https://example.com:8443/api: oidc refresh response from https://accounts.foo.com did not contain an id_token, either the scope "openid" wasn't requested upon login, or the provider doesn't support id_tokens as part of the refresh response.
> ```
> 
> Also might be worth documenting on kubernetes.io
> 
> [1] https://developer.okta.com/docs/api/resources/oidc.html#response-parameters-4
> [2] https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse
> [3] https://github.com/kubernetes/client-go/blob/9675d048204baf818bb24f7c74d0e64f6254902e/plugin/pkg/client/auth/oidc/oidc.go#L254-L257

**Comment by gtaylor** [comment]
What would the eventual fix for this involve? Will kubectl or the api server need to query the IDP for the missing bits?

**Comment by ericchiang** [comment]
@gtaylor from a pure OpenID Connect perspective I don't know if there's anything we can do. If the provider doesn't return the id_token in the refresh response, we have to fall back to whatever proprietary endpoints the IdP exposes.

I think the answer would be a webhook authenticator that goes around OpenID Connect and just uses the IdP specific endpoints, or a shim like dex.

**Comment by gtaylor** [comment]
Bummer. I've sent feedback along to Okta about making this configurable on their end, but haven't had great results with their support as of yet. Fortunately, we can still manually renew for now.

Given your answer above, should we close this issue?

**Comment by ericchiang** [comment]
Yeah it's not fun that OpenID Connect makes this optional.

Still waiting for https://github.com/kubernetes/website/pull/5884 to merge to close the issue.

**Comment by gtaylor** [comment]
> Still waiting for kubernetes/website#5884 to merge to close the issue.

Ah, makes sense. Thanks for improving the error message. That'll definitely help our users be less confused while we figure out which way to go with this on our end.

**Comment by jeremyjh** [comment]
Hi, just a note in case anyone finds this discussion in the future, Okta *does* include id_token in the refresh response, if you include "openid" in the scope. In my application I have a refresh flow working with id_token using scopes "openid offline_access" and grant_type "refresh_token".

**Comment by gtaylor** [comment]
@jeremyjh any ideas if this is a recent addition? I think even Okta customer service said the id_token wasn't in the refresh the last time we got in touch (granted, six months ago).

**Comment by jeremyjh** [comment]
@gtaylor I don't know, I just started using the refresh grant today.

**Comment by mcguinness** [comment]
Okta recently changed our implementation to return the id_token during token refresh to resolve this issue with kubernetes.

OIDC defines a [UserInfo endpoint](https://openid.net/specs/openid-connect-core-1_0.html#UserInfo) to obtain user information using a standard access token returned via a token refresh.  It's common for OIDC providers to require the client to use the access token to get fresh user data instead of relying on the id_token in the token response. 

The id_token often contains data about the authentication transaction such as what authentication methods were used to authenticate the user that is not really relevant in an offline scenario where the refresh token is not bound to the user's web session with the IdP.  This is why the [offline_access scope](https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess) exists.

**Comment by gtaylor** [comment]
@mcguinness great to hear! I don't suppose there are any Okta docs that go over the specific combination of settings required for Kubernetes?

Also, to verify my understanding: We'll need to add the offline_access scope in order to get the id_token included with refreshes?

**Comment by dpreetam** [comment]
We are running into same challenge with PingFederate. Ping says its not mandatory to send id token with refresh grant as per spec. How building a solution (kubectl flow) making an optional parameter as mandatory parameter for solution to work seamlessly is not in violation of spec?

**Comment by aeijdenberg** [comment]
In an unrelated context (ie outside of Kubernetes) we've also been relying on seeing (and then validating) an `id_token` in a refresh token response as an indicator that a user is still authorized, however when switching from G-Suite to Azure AD for SSO we've noticed that Azure AD *does not* include the `id_token` in a refresh token response.

Curious how other similar solutions have handled this type of situation, and wanted to add Azure AD as another datapoint.

**Comment by binboum** [comment]
> @dpreetam
> 
> > We are running into same challenge with PingFederate. Ping says its not mandatory to send id token with refresh grant as per spec. How building a solution (kubectl flow) making an optional parameter as mandatory parameter for solution to work seamlessly is not in violation of spec?
> 
> Did you succeed to obtain id_token for PingFederate after refresh? We have exactly same issue

Good news, it is now possible.

https://docs.pingidentity.com/fr-FR/bundle/pingfederate-100/page/ojz1568310087399.html

**Comment by dpreetam** [comment]
> > @dpreetam
> > > We are running into same challenge with PingFederate. Ping says its not mandatory to send id token with refresh grant as per spec. How building a solution (kubectl flow) making an optional parameter as mandatory parameter for solution to work seamlessly is not in violation of spec?
> > 
> > 
> > Did you succeed to obtain id_token for PingFederate after refresh? We have exactly same issue
> 
> Good news, it is now possible.
> 
> https://docs.pingidentity.com/fr-FR/bundle/pingfederate-100/page/ojz1568310087399.html

Have to upgrade to PF 10.  Glad Ping listened to us(customer).
