### ISSUE TITLE
[Feature]able to stop/restart/scale specific pod labled by pod-template-hash in one deployment

### ISSUE THREAD

**Issue by mars00772** [kubernetes/kubernetes#36868]
in some system,one of the pod was elected by raft or some other algorithm,in some case,especially for the statefull application,people need to restart/scale/stop the specific pod which labled by a pod-template-hash in one deployment.
but now we can not do that cause kubectl scale/delete didn't have the -l opthion

**Comment by bgrant0607** [comment]
@mars00772 If individual identity matters, you should probably be using StatefulSet rather than Deployment.

**Comment by kargakis** [comment]
@bgrant0607 do you think there is anything that needs to be done here for Deployments?

**Comment by kargakis** [comment]
Restarts are covered by https://github.com/kubernetes/kubernetes/issues/13488
Also, for these kinds of apps, use StatefulSets.
