### ISSUE TITLE
Make it easy to build with HTTP proxy

### ISSUE THREAD

**Issue by prateekarora151083** [kubernetes/kubernetes#3687]
Hi
when i tried to compile kubernetes in proxy network its give below error 

```
Step 5 : RUN go get code.google.com/p/go.tools/cmd/cover github.com/tools/godep
 ---> Running in 7183a3b93842
package code.google.com/p/go.tools/cmd/cover: Get https://code.google.com/p/go/source/checkout?repo=tools: dial tcp 173.194.33.168:443: i/o timeout
# cd .; git clone https://github.com/tools/godep /go/src/github.com/tools/godep
Cloning into '/go/src/github.com/tools/godep'...
fatal: unable to access 'https://github.com/tools/godep/': Failed to connect to github.com port 443: Connection timed out
package github.com/tools/godep: exit status 128
time="2015-01-21T11:03:30-08:00" level="info" msg="The command [/bin/sh -c go get code.google.com/p/go.tools/cmd/cover github.com/tools/godep] returned a non-zero code: 1"
```

i think this error is because of proxy setting

**Comment by jbeda** [comment]
It looks like using a proxy with `docker build` is not well supported by docker itself.  See http://stackoverflow.com/questions/22179301/how-do-you-run-apt-get-in-a-dockerfile-behind-a-proxy.

I'd try editing `build/build-image/Dockerfile` to add `ENV` lines for your proxy and see if that works for you.  If that works and enough other users need it, we could perhaps make it a little more streamlined.

**Comment by prateekarora151083** [comment]
I added 
ENV http_proxy <HTTP_PROXY>
ENV https_proxy <HTTPS_PROXY>  in build/build-image/Dockerfile

and it works 

Thanks

**Comment by jbeda** [comment]
Turning this in to a feature request to make this easier in the future.
