### ISSUE TITLE
Future alternative for API server bootstrapping

### ISSUE THREAD

**Issue by kanor1306** [kubernetes/kubernetes#36881]
**Is this a request for help?** No

**What keywords did you search in Kubernetes issues before filing this one?** static bootstrap,  bootstrap api,  static pods

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

---

I keep seeing here and there that the static pods are gonna be deprecated "soon", and the suggestion for replacing them is using DaemonSets. But, there is (at least) a case where this alternative is not gonna work. I am talking about the suggested way of bootstrapping a cluster in the "From scratch" guide. On that guide, the API server is bootstrapped using an static pod, and of course using DaemonSets is not an option, as you don't have an API server that could take care of the DaemonSet.

So, my question is, will be there any alternative to make this kind of bootstrapping once the static pods are finally deprecated? 

I already heard about some solutions to achieve this, but they seemed to me more like workarounds than actual proper solutions, so I was wondering if the Kubernetes team has something in mind for this cases.

**Comment by bgrant0607** [comment]
@kanor1306 Yes, there have been proposals for this. Please ask on the cluster lifecycle SIG list rather than through github issue.

**Comment by bgrant0607** [comment]
https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle
