### ISSUE TITLE
Time format in docker daemon logs

### ISSUE THREAD

**Issue by Crassirostris** [kubernetes/kubernetes#36893]
GCL logging test failed recently, related issue in https://github.com/kubernetes/kubernetes/issues/36890

In the fluentd logs there're a lot of lines like 

```
2016-11-16 00:23:59 +0000 [warn]: "time=\"2016-11-16T00:23:59Z\" level=debug msg=\"containerd: process exited\" id=a9f3e4a7b80fbb51ff30ea6dc8ce4c2ff18c401ebe9fc50567c3ee487df8f504 pid=init status=0 systemPid=12467 " error="invalid time format: value = 2016-11-16T00:23:59Z, error_class = ArgumentError, error = invalid strptime format - `%Y-%m-%dT%H:%M:%S.%NZ'"
```

Because apparently this kind of messages in docker logs have different time format

```
time="2016-11-16T00:19:36.238978920Z" level=debug msg="Sending 15 to e2688fa502b8807e9631ceac33582a037185823dfda37a588603a41a4c959575" 
time="2016-11-16T00:19:36Z" level=debug msg="containerd: process exited" id=e2688fa502b8807e9631ceac33582a037185823dfda37a588603a41a4c959575 pid=init status=0 systemPid=9348 
time="2016-11-16T00:19:36.317143523Z" level=debug msg="received containerd event: &types.Event{Type:\"exit\", Id:\"e2688fa502b8807e9631ceac33582a037185823dfda37a588603a41a4c959575\", Status:0x0, Pid:\"init\", Timestamp:0x582ba618}" 
```

Fluentd configuration should be patched to handle this kind of messages. Maybe because of messages like this the logs were not delivered also, maybe fluentd spent too much cpu on docker log to keep up with all log files.

@piosz @edsiper

**Comment by Crassirostris** [comment]
@igorpeshansky Just for your information, that this might happen with fluentd

**Comment by dchen1107** [comment]
cc/ @Random-Liu

**Comment by piosz** [comment]
@Crassirostris thanks for catching this.

**Comment by piosz** [comment]
@Crassirostris please fill an issue for Docker with the problem
