### ISSUE TITLE
Suspicious loop in k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#36902]
Per #36858:

k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go:1923:3: the surrounding loop is unconditionally terminated (SA4004)

It does look very suspicious.

**Comment by seh** [comment]
Pertinent patches:
- 48e8a8b0ec250efb05390b79e3e81b720f8259cc  
  _AWS: Set up security groups, to mirror GCE firewalling_
- 190c829ac5e5aa628e613a635af9e7ac153108ab  
  _Fix AWS ip permission comparison on security group_

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5

**Comment by dims** [comment]
@justinsb all issues must be labeled either release blocker or non release blocking by end of day 18 November 2016 PST. (or please move it to 1.6) cc @kubernetes/sig-aws

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by justinsb** [comment]
This was a bug where we had multiple userid/group pairs, but we only ever called it with 0 or 1 elements.

Fix in #47575 but kicking out of the 1.7 milestone.
