### ISSUE TITLE
Failed to mount RBD to pods

### ISSUE THREAD

**Issue by rajeshwer** [kubernetes/kubernetes#36905]
timeout expired waiting for volumes to attach/mount for pod "ceph-test-i8oj5"/"default". list of unattached/unmounted volumes=[ceph-image1]

**Comment by rajeshwer** [comment]
sudo kubectl get pv    
NAME          CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                 REASON    AGE
ceph-image1   1Gi        RWO           Retain          Bound     default/ceph-image1             18h


sudo kubectl get pvc
NAME          STATUS    VOLUME        CAPACITY   ACCESSMODES   AGE
ceph-image1   Bound     ceph-image1   1Gi        RWO           18h

**Comment by jingxu97** [comment]
@rajeshwer could you please provide more details about the issue? Kubelet log will be very helpful for us to check the issue

**Comment by rajeshwer** [comment]
Thanks for your response .
I am actually trying to mount ceph rbd volume mount to pods

but i was failing 

let me share the logs with you

**Comment by rajeshwer** [comment]
sudo kubectl describe pods|grep rbd
Name:		rbd
  rbd-rw:
      /var/ from rbdpd (rw)
  rbdpd:
  10s		10s		1	{default-scheduler }			Normal		Scheduled	Successfully assigned rbd to 10.10.191.16
  8s		1s		4	{kubelet 10.10.191.16}			Warning		FailedMount	MountVolume.SetUp failed for volume "kubernetes.io/rbd/cf3a3a6f-b759-11e6-aca7-2c600cbb02a8-rbdpd" (spec.Name: "rbdpd") pod "cf3a3a6f-b759-11e6-aca7-2c600cbb02a8" (UID: "cf3a3a6f-b759-11e6-aca7-2c600cbb02a8") with: rbd: failed to modprobe rbd error:exit status 1

**Comment by rajeshwer** [comment]
I am able to mount rbd to  a empty directory but if i want to mount it to /var/log or some other directory pod creation is failing

**Comment by jingxu97** [comment]
Found two related PR https://github.com/coreos/bugs/issues/1579 and #23924

cc @kubernetes/sig-storage

**Comment by rootfs** [comment]
@rajeshwer how is your kubelet running? is it running inside container? you need to bind mount /sbin/modprobe and /lib/module to resolve `modprobe rbd error:exit status 1`

**Comment by double-p** [comment]
On a sidenote, if you fixed the 'modprobe' problem, but still on timeout. Check if you run across namespaces ( https://github.com/rook/rook/issues/475 ); then grab the secret from default and add it into the namespace of the consuming pods
