### ISSUE TITLE
Fix kubectl strmrg patch compatibility

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#36916]
#35647 introduced a non-backwards compatible change in kubectl and uses the server version to fallback on the old behavior.  @smarterclayton noted that using the server version to drive client behavior is not acceptable because the server version may not be published, or there may be federated servers with different versions.

We need to work out a solution, which may include rolling back parts of the original change.

**Comment by bgrant0607** [comment]
@pwittrock Embedded uses of k8s may also not do release versioning the same way. 

It would be better if the client could find a way to probe for the specific behavior it wanted to use.

cc @caesarxuchao

**Comment by ymqytw** [comment]
One way is:
1) try to send  the new version of strmrg patch
2) if it fails, try using the old strmrg patch
3) if it fails again, return the error

**Comment by caesarxuchao** [comment]
We had a similar problem to let client discover if server supports garbage collection. I remember we discussed server could supply a feature vector to indicate server capabilities, but couldn't find the issue. cc @lavalamp
