### ISSUE TITLE
When a federated cluster endpoint is updated, federation controller manager still uses old endpoint

### ISSUE THREAD

**Issue by saturnism** [kubernetes/kubernetes#36921]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:19:49Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**: OSX, GKE
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): GKE
- **Kernel** (e.g. `uname -a`): GKE
- **Install tools**: GKE
- **Others**:

**What happened**:
I added a cluster into federation, say, "cluster-1", w/ an endpoint address, e.g. http://123.123.123.123. I later deleted cluster-1 and also the secret. I then re-added cluster-1 back, but now, with a new endpoint, e.g., http://111.111.111.111. The federation server shows cluster-1 is healthy, but in the logs, there is a repeating error on unable to connect to the old endpoint, http://123.123.123.123.

**What you expected to happen**:
Federation controller manager should use the new endpoint

**How to reproduce it** (as minimally and precisely as possible):
1. Add a cluster to federation, name it cluster-1
1. Delete the cluster from federation
1. Add a new cluster to federation, w/ a different API server, and name it cluster-1 as well
1. Observe the error

**Anything else do we need to know**:

**Comment by quinton-hoole** [comment]
cc @jianhuiz

**Comment by henriquetruta** [comment]
Executed this here with a 1.5.6 federated cluster in GKE, added a local cluster with `kubectl create -f cluster_file`, deleted it, and then recreated it with another IP. It worked as expected. It was looking for the new IP, instead of the old one. @saturnism did I do something wrong?

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#82.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
