### ISSUE TITLE
Systematically generate events for object lifecycle events

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#3692]
Similar to Docker events: create, update, and delete should all generate events.

Inspired by, but distinct from, #3585.

**Comment by bgrant0607** [comment]
Also needed in order to replace operations: #3644

**Comment by erictune** [comment]
With the "finalizer" pattern mentioned in #3585, if each "finalizer" process has an "identity" (as discussed most recently by @smarterclayton in #2297), then the update by a finalizer could perhaps cause an event to be generated in the apiserver rather than by the finalizer.  

Event has these properties:
```
 {
    involvedObject : ""
    reason: ""
    message  : ""
    source : {
      component: ""
      host : ""
    }    
    timestamp : ""
}
```
The apiserver knows all those things except reason and message.
And somewhere there is an issue that says we should allow a reason and/or message to be set for any mutating API call.   So, even that could be done.

So, for the case where the scheduler make a binding, the event could be automatically generated.  But, for the case where the scheduler wants to report an error, it may need to explicitly `record.Eventf`

**Comment by erictune** [comment]
If the finalizers lease the objects they want to modify, as mentioned just now in #3538,  then we could automatically generate several kinds of events:
  1. at the start of lease, we know the object is "being worked on" by a component, such as the scheduler.
  2. when the lease ends, it can generate a "work done" event.
  3. if the lease expires without a modification, we could generate an event that implies the component is blocked or very slow.

  .

**Comment by bgrant0607** [comment]
Client-specified reason is #1462

**Comment by bgrant0607** [comment]
We may want hooks in addition to events.

**Comment by volyihin** [comment]
Is this issue still actual? Can I take part in designing this feature during gsoc?

**Comment by bgrant0607** [comment]
@volyihin Yes, feel free to submit a proposal on this topic. Once all of the proposals are in, we'll select which ones we want to move forward with.

**Comment by bgrant0607** [comment]
I  believe @jbeda mentioned something like this in his kubecon talk.

**Comment by bgrant0607** [comment]
Another approach several people have mentioned would be to run an addon to convert watch events to other types of events, such as in Kafka and/or in another form easily consumable by FaaS.

This is also effectively what kube-state-metrics does, for prometheus-style metrics.

**Comment by smarterclayton** [comment]
Yes - I would be in favor of an effort to systematically transform
state changes into ordered entries in:

1. A log (cloud or disk)
2. Elasticsearch
3. Kafka or other ordered queue

In a way that allows other "lifecycle events" to also be generated.
Even if that's a library others can reuse, it's a good step towards
larger "infrastore" type history of a cluster.  Read apis are almost
secondary - ensuring a simple sync tool works first gives us more
confidence of the ability to apply this in the future.

**Comment by bgrant0607** [comment]
We also mention Infrastore in the Borg paper:

https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/43438.pdf

Borg records all job submissions and task events, as well as detailed per-task resource usage information in Infrastore, a scalable read-only data store with an interactive SQL-like interface via Dremel.

**Comment by bgrant0607** [comment]
https://github.com/heptio/eventrouter

**Comment by bgrant0607** [comment]
Related: #4432
