### ISSUE TITLE
When a federated cluster becomes offline, federation controller manager doesn't u

### ISSUE THREAD

**Issue by saturnism** [kubernetes/kubernetes#36923]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:19:49Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**: GKE
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): GKE
- **Kernel** (e.g. `uname -a`): GKE
- **Install tools**:
- **Others**:

**What happened**:
I federated 3 clusters together. I deliberately killed the API server on one the clusters. Federation status shows that the cluster is Offline. However, the service IP is not removed from DNS, and there is a repeating error in the federation controller manager log, such as:
```
E1116 22:36:03.276899       1 reflector.go:214] k8s.io/kubernetes/federation/pkg/federation-controller/service/cluster_helper.go:155: Failed to list *v1.Endpoints: the server could not find the requested resource (get endpoints)
E1116 22:36:03.277798       1 reflector.go:214] k8s.io/kubernetes/federation/pkg/federation-controller/service/cluster_helper.go:154: Failed to list *v1.Service: the server could not find the requested resource (get services)
```

**What you expected to happen**:
It should clean up and remove service IPs associated w/ the cluster that's now offline

**How to reproduce it** (as minimally and precisely as possible):
1. Federate multiple clusters together
1. Configure kubedns w/ federation
1. Deploy backend to 2 clusters
1. Run consumers on other clusters not running the backend
1. Pull the plug on the API server on one of the cluster running the backend
1. Observe the error in federation controller manager

**Anything else do we need to know**:

**Comment by quinton-hoole** [comment]
cc @jianhuiz

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#83.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
