### ISSUE TITLE
Kubelet should truncate hostname more carefully

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#36951]
Docker daemon complains "invalid hostname format" if the truncated host name ends with "." The truncation occurs [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L237).

**Comment by Random-Liu** [comment]
Docker checks hostname with the regexp  (See [here](https://github.com/docker/docker/blob/65835bfaa6d44b2255ed25eab74ebcdc8b3ba491/daemon/container.go#L231)):
```
^(([[:alnum:]]|[[:alnum:]][[:alnum:]\\-]*[[:alnum:]])\\.)*([[:alnum:]]|[[:alnum:]][[:alnum:]\\-]*[[:alnum:]])$
```

It means that the hostname must end with an alnum, not `.` or `-`.

**Comment by dims** [comment]
@Random-Liu : Needed for v1.5? please add milestone if so

**Comment by Random-Liu** [comment]
@dims Thanks for reminding. :)

This is a bug fix in kubelet. Mark 1.5.
/cc @saad-ali

**Comment by saad-ali** [comment]
@Random-Liu Are you working on a fix?

**Comment by Random-Liu** [comment]
@saad-ali Yeah, the fix is here https://github.com/kubernetes/kubernetes/pull/36965.
