### ISSUE TITLE
Kubectl should support U2F security tokens for 2 factor authentication

### ISSUE THREAD

**Issue by sandys** [kubernetes/kubernetes#36981]
@kubernetes/kubectl 

A lot of us are going to start using kubectl as a way to manage the clusters right from our laptop. Which is why kubectl should support the U2F standard that is being used everywhere from Dropbox, Github to Google. https://security.googleblog.com/2014/10/strengthening-2-step-verification-with.html

**Comment by kargakis** [comment]
@kubernetes/sig-cli @kubernetes/sig-auth

**Comment by fabianofranz** [comment]
@liggitt

**Comment by liggitt** [comment]
dupe of https://github.com/kubernetes/kubernetes/issues/14362
