### ISSUE TITLE
Make it possible to switch of secrets in Kubemark

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#36985]
Until #19188 is fixed (which won't happen before code-freeze is finished), kubemark-scale will be failing/timing-out and this is "working-as-intended" until then.

It should be possible to switch off secrets in kubemark to make other problems debuggable.
For now we would like to:
- switch off secrets in kubemark-scale
- leave them in all other kubemark suites

**Comment by grodrigues3** [comment]
@wojtek-t can you add a release-blocking or non-blocking label to this issue?

**Comment by liggitt** [comment]
Is kubemark scale useful/realistic if it disables things that are required in actual deployments?

**Comment by gmarek** [comment]
We use it for development, and we need a way to switch off particular parts.

**Comment by wojtek-t** [comment]
@liggitt - it's just a short term fix that would allow to fix/debug different problems at the same time (we already know that secrets are causing problems and we will be fixing it).

**Comment by wojtek-t** [comment]
To clarify - I'm not going to leave that forever - as soon as we will have some fix for secrets in, we will enable it back in 5000-node kubemark. Currently because of secrets those tests doesn't bring any value.

**Comment by wojtek-t** [comment]
Also - this one is already done.
