### ISSUE TITLE
openstack: kubelet cant register node name to API

### ISSUE THREAD

**Issue by Tha-Robert** [kubernetes/kubernetes#36992]
BUG REPORT

**Kubernetes version** (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.124+0c7421fb51bd49-dirty", GitCommit:"0c7421fb51bd49b7fdc66a2c08fc1adee0f9630a", GitTreeState:"dirty", BuildDate:"2016-11-07T09:43:55Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"

**Environment**:
- provider: openstack
- os: CentOS Linux 7 (Core)
- kernel: Linux kubernetesstack-test-node-soktmicf.kubecluster.test 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**What happened**:
The node could not register with the API server

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
Run the heat scripts to setup a cluster on a openstack cloud.

**Anything else do we need to know**:

From the kubelet log.
0.650555   28807 kubelet_node_status.go:74] Attempting to register node kubernetesstack-test-node-sOktMiCF
0.657271   28807 kubelet_node_status.go:98] Unable to register node "kubernetesstack-test-node-sOktMiCF" with API server: Node "kubernetesstack-test-node-sOktMiCF" is invalid: metadata.name: Invalid value: "kubernetesstack-test-node-sOktMiCF": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)* (e.g. 'example.com')
2.056079   28807 eviction_manager.go:165] eviction manager: unexpected err: failed GetNode: node 'kubernetesstack-test-node-sOktMiCF' not found

pkg/cloudprovider/providers/openstack/metadata.go
uses the cloudprovider information entry name which is just a name and not a hostname which I assume that the API wants as a name.

Should really a entry metadata.name be enforced to have url(hostname) type ?

/R

**Comment by Tha-Robert** [comment]
And if you change the name to be the hostname to satisfy the API then the provider cant find the instance in a later step.
So there is a clear missmatch between the API and the provider.
/R

**Comment by micmro** [comment]
I've just seen there is a PR that would fix this issue (tried it locally and it works): https://github.com/kubernetes/kubernetes/pull/37264

**Comment by Tha-Robert** [comment]
I dont think its the same issue, #37264 fixes wrong nodename.
This is about the hostname must be being a full url and not just the nodename, and the entry beeing name and not url hostname or such.

In openstack and the heat setup scripts fixes the hostnames to be just nodenames and not a fully qualified hostname due to local domains that cant be looked up. This then breaks du to the change in the API to verify the name part of the metadata.

/R

**Comment by micmro** [comment]
Right - sorry, I must have overlooked that.

**Comment by e-goldberg** [comment]
any suggested workaround?

**Comment by Tha-Robert** [comment]
I have two outstanding questions(Due to the floating target this project has) to give a valid workaround.

1. Is the change to the API, that the metadata field called "name" should be a valid "hostname" in all cases a decition or just a fact of other changes ? And is it there to stay ? In this case maybe name should be changed, same attribute but changed meaning is not very intuitive.

If yes, the change can be that the hostname fix in the heatscripts is removed. Keeping the name.local thats given by openstack as default. And change the pkg/cloudprovider/providers/openstack/metadata.go to use the hostname instead of name.

The non DNS issue is somewhat connected to this issue and maybe should be addressed also.

/R

**Comment by xsgordon** [comment]
Looks like this should be resolved by https://github.com/kubernetes/kubernetes/pull/40339 which corrects the Heat templates?

**Comment by ccatlett2000** [comment]
I can confirm the changes in #40339 fix this. Can someone that has permission close this?

**Comment by Tha-Robert** [comment]
That fixes only the capital letters in the generated name.
If the name is not a qualified hostname(blablah.com) it sill fails.
And the heat scripts as they where(when this was filed) removed the (.local) part thats added per default by openstack. 
And there for fails the regexp check.

/R

**Comment by ccatlett2000** [comment]
It works for me with a non-fqdn hostname, as long as instance name resolution works (I had to explicitly set the subnet's DNS servers to nothing and configure DNS on Neutron's DHCP agent to get it to work).

**Comment by jzhoucliqr** [comment]
Had the same problem with manually launched VM, but after change the name to all lowercase, even non-fqdn name works fine. 

The regex is now changed to : [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*, non-fqdn matches.

**Comment by dims** [comment]
looks like this is fixed? please reopen if needed

/close
