### ISSUE TITLE
Remove TPR special casing

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#36998]
We should remove `IsThirdPartyAPIGroupVersion`, `AddThirdPartyAPIGroupVersions`, and `ThirdPartyResourceData`.  The content needs to have its object meta massaged, but that should mean having its own RESTStorage defined.

`ThirdPartyResourceData` is being used to carry bits without modification and stomp `metadata`.  That should be changed to `runtime.Unstructured` because all we care about is moving the bits and setting metadata which is already exposed through `api/meta` values.

**Comment by smarterclayton** [comment]
Handled by CRD
