### ISSUE TITLE
test/e2e/framework cannot be imported into external projects

### ISSUE THREAD

**Issue by sjug** [kubernetes/kubernetes#37007]
**Problem**
If you try to compile a project that has a test/e2e/framework as a dependency, we see the following error:
```
# github.com/sjug/project/vendor/k8s.io/kubernetes/test/e2e/framework
vendor/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go:30: undefined: generated.Asset
vendor/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go:33: undefined: generated.AssetNames
```
When we import test/e2e/framework as a dependency the `ReadOrDie(filepath string) []byte` depends on two assets that are generated by gobindata.

**Solution**
Modify test/e2e/framework to not depend on bindata.

**Comment by wongma7** [comment]
This is a problem again due to https://github.com/kubernetes/kubernetes/pull/41221 and https://github.com/kubernetes/kubernetes/pull/41482, now test/e2e/framework/statefulset_utils imports test/e2e/generated 

@ncdc would you accept a simple revert of these changes https://github.com/kubernetes/kubernetes/pull/41482/files#diff-20a9335743239e362032f5839bb81f98L73 to get this working again asap or do i need to attempt a proper refactor of `StatefulSetTester`

**Comment by wongma7** [comment]
nvm there's no rush I figured I can work around it easily, I'll work on a proper PR

**Comment by ncdc** [comment]
@wongma7 sorry, I didn't realize this was not the right way to do it. I would strongly prefer a proper refactor.

**Comment by cjellick** [comment]
@sjug @wongma7 I hit this problem when attempting to import `k8s.io/kubernetes/test/integration/framework`. Some code in there imports e2e and it looks like some e2e/framework code relies on e2e/generated.
Do either of you know of any ways to work around this?

**Comment by wongma7** [comment]
easiest imo would be to (edit and) run the script https://github.com/kubernetes/kubernetes/blob/master/hack/generate-bindata.sh#L48 and check in the resulting (dummy) bindata.go to your code at test/e2e/generated/bindata.go, treating it as a "patch" to carry on top of your k8s.io/kubernetes dependency

personally I've pinned my dependency on the framework to one that I know does not have any dependency on `generated` but it is an old version now (1.6~)

**Comment by cjellick** [comment]
Thanks so much @wongma7! I really appreciate the response. I'll try that.

I realize this isn't exactly the right place for this conversation, but I'm going to ask a follow up question:

My intention is to use the integration test's framework to test my own controllers. Is that what you are doing? Is that valid/going-to-work (assuming I get around this problem)?

**Comment by mariusgrigoriu** [comment]
@wongma7 Did `generated` get reintroduced after your PR got approved?
