### ISSUE TITLE
kubernetes time out issues

### ISSUE THREAD

**Issue by darktall** [kubernetes/kubernetes#37004]
kubelet hogging more than 100% cpu all the time .  Strace gave me the below  output.

kubelet version

Environment=KUBELET_VERSION=v1.3.6_coreos.0

top - 16:38:49 up 37 min,  2 users,  load average: 106.87, 95.49, 87.23
Tasks: 274 total,   3 running, 269 sleeping,   0 stopped,   2 zombie
%Cpu(s):  0.0 us, 97.9 sy,  0.0 ni,  0.0 id,  1.2 wa,  0.6 hi,  0.3 si,  0.0 st
KiB Mem:  16436820 total, 16300112 used,   136708 free,      404 buffers
KiB Swap:        0 total,        0 used,        0 free.    13592 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 1403 root      20   0 1777904  47712      0 S 111.3  0.3  33:35.81 kubelet
   70 root      20   0       0      0      0 R  78.0  0.0  21:18.04 kswapd0
 1512 root      20   0  610992   8188      0 S  53.2  0.0   7:24.28 flanneld
 8698 root      20   0 7653308 706652      0 S  35.2  4.3   0:36.37 java
  556 root      20   0   75284   2276   1692 R  30.6  0.0   6:13.29 systemd-journal
 1643 root      20   0 3575920  63736      0 S  30.3  0.4   9:44.28 docker

[pid  6407] stat("/usr/bin/nice",  <unfinished ...>
[pid  3713] fstat(40,  <unfinished ...>
[pid  1806] <... epoll_wait resumed> {}, 128, 0) = 0
[pid  6458] <... stat resumed> {st_mode=S_IFDIR|S_ISVTX|0777, st_size=140, ...}) = 0
[pid  6407] <... stat resumed> {st_mode=S_IFREG|0755, st_size=31240, ...}) = 0
[pid  3713] <... fstat resumed> {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] futex(0xc8208f8908, FUTEX_WAKE, 1 <unfinished ...>
[pid  6468] execve("/usr/local/bin/du", ["du", "-s", "/var/lib/docker/containers/4c6a1"...], [/* 1 var */] <unfinished ...>
[pid  6458] stat("/var/lib/kubelet/pods/206d34b4-acdd-11e6-b2cb-005056a61a8a/volumes/kubernetes.io~secret/default-token-j7yvv",  <unfinished ...>
[pid  6366] <... futex resumed> )       = 0
[pid  1806] <... futex resumed> )       = 1
[pid  6458] <... stat resumed> {st_mode=S_IFDIR|S_ISVTX|0777, st_size=140, ...}) = 0
[pid  6460] close(3 <unfinished ...>
[pid  6407] futex(0xc8208f9108, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid  6468] <... execve resumed> )      = -1 ENOENT (No such file or directory)
[pid  6460] <... close resumed> )       = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  6468] execve("/usr/sbin/du", ["du", "-s", "/var/lib/docker/containers/4c6a1"...], [/* 1 var */] <unfinished ...>
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  6468] <... execve resumed> )      = -1 ENOENT (No such file or directory)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid  6460] munmap(0x7f10cc0e7000, 4096 <unfinished ...>
[pid  1806] <... select resumed> )      = 0 (Timeout)
[pid  6460] <... munmap resumed> )      = 0
[pid  1806] epoll_wait(5,  <unfinished ...>
[pid  6468] execve("/usr/bin/du", ["du", "-s", "/var/lib/docker/containers/4c6a1"...], [/* 1 var */] <unfinished ...>
[pid  1806] <... epoll_wait resumed> {}, 128, 0) = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid  6460] stat("/var/lib/kubelet/pods/2069d074-acdd-11e6-b2cb-005056a61a8a/volumes/kubernetes.io~secret/default-token-j7yvv",  <unfinished ...>
[pid  6458] stat("/var/lib/kubelet/pods/20787179-acdd-11e6-b2cb-005056a61a8a/volumes/kubernetes.io~secret/default-token-j7yvv",  <unfinished ...>
[pid  6460] <... stat resumed> {st_mode=S_IFDIR|S_ISVTX|0777, st_size=140, ...}) = 0
[pid  6458] <... stat resumed> {st_mode=S_IFDIR|S_ISVTX|0777, st_size=140, ...}) = 0
[pid  1806] <... select resumed> )      = 0 (Timeout)
[pid  1806] epoll_wait(5,  <unfinished ...>
[pid  6468] <... execve resumed> )      = 0
[pid  1806] <... epoll_wait resumed> {}, 128, 0) = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  6458] stat("/var/lib/kubelet/pods/20727b97-acdd-11e6-b2cb-005056a61a8a/volumes/kubernetes.io~secret/default-token-j7yvv",  <unfinished ...>
[pid  6468] brk(0 <unfinished ...>
[pid  1806] epoll_wait(5,  <unfinished ...>
[pid  6468] <... brk resumed> )         = 0x1e58000
[pid  6458] <... stat resumed> {st_mode=S_IFDIR|S_ISVTX|0777, st_size=140, ...}) = 0
[pid  1806] <... epoll_wait resumed> {}, 128, 0) = 0
[pid  3713] sched_yield()               = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  3713] futex(0x58a4e10, FUTEX_WAKE, 1 <unfinished ...>
[pid  1817] close(65 <unfinished ...>
[pid  1806] epoll_wait(5,  <unfinished ...>
[pid  3713] <... futex resumed> )       = 0
[pid  1817] <... close resumed> )       = 0
[pid  1806] <... epoll_wait resumed> {}, 128, 0) = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] futex(0xc8208f9108, FUTEX_WAKE, 1 <unfinished ...>
[pid  6407] <... futex resumed> )       = 0
[pid  1806] <... futex resumed> )       = 1
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 40}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 80}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 160}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 320}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 640}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 1280}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 2560}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 5120}) = 0 (Timeout)
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000} <unfinished ...>
[pid  1856] sched_yield()               = 0
[pid  1856] futex(0x58a4e10, FUTEX_WAIT, 2, NULL <unfinished ...>
[pid  6468] access("/etc/ld.so.nohwcap", F_OK <unfinished ...>
[pid  6460] stat("/var/lib/kubelet/pods/206d34b4-acdd-11e6-b2cb-005056a61a8a/volumes/kubernetes.io~secret/default-token-j7yvv",  <unfinished ...>
[pid  6458] stat("/var/lib/kubelet/pods/2085a2ec-acdd-11e6-b2cb-005056a61a8a/volumes/kubernetes.io~secret/default-token-j7yvv",  <unfinished ...>
[pid  6366] sched_yield( <unfinished ...>
[pid  1856] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid  1817] futex(0x58a4e10, FUTEX_WAKE, 1 <unfinished ...>
[pid  6366] <... sched_yield resumed> ) = 0
[pid  6460] <... stat resumed> {st_mode=S_IFDIR|S_ISVTX|0777, st_size=140, ...}) = 0
[pid  6458] <... stat resumed> {st_mode=S_IFDIR|S_ISVTX|0777, st_size=140, ...}) = 0
[pid  1814] read(74,  <unfinished ...>
[pid  1806] <... select resumed> )      = 0 (Timeout)
[pid  1817] <... futex resumed> )       = 0
[pid  1814] <... read resumed> "Total 0\n", 4096) = 8
[pid  1856] sched_yield()               = 0
[pid  1856] futex(0x58a4e10, FUTEX_WAIT, 2, NULL <unfinished ...>
[pid  1817] sched_yield( <unfinished ...>
[pid  1806] epoll_wait(5,  <unfinished ...>
[pid  6468] <... access resumed> )      = -1 ENOENT (No such file or directory)
[pid  1817] <... sched_yield resumed> ) = 0
[pid  1806] <... epoll_wait resumed> {}, 128, 0) = 0
[pid  6468] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0 <unfinished ...>
[pid  6458] stat("/var/lib/kubelet/pods/208bcf17-acdd-11e6-b2cb-005056a61a8a/volumes/kubernetes.io~secret/default-token-j7yvv",  <unfinished ...>
[pid  1817] futex(0x58a4e10, FUTEX_WAKE, 1 <unfinished ...>
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000} <unfinished ...>
[pid  6468] <... mmap resumed> )        = 0x7f0746b98000
[pid  6458] <... stat resumed> {st_mode=S_IFDIR|S_ISVTX|0777, st_size=140, ...}) = 0
[pid  1856] <... futex resumed> )       = 0
[pid  1817] <... futex resumed> )       = 1
[pid  1806] <... select resumed> )      = 0 (Timeout)
[pid  1856] futex(0x58a4e10, FUTEX_WAKE, 1 <unfinished ...>
[pid  1817] futex(0xc82005ed08, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid  1806] epoll_wait(5,  <unfinished ...>
[pid  1856] <... futex resumed> )       = 0
[pid  6458] brk(0x850000 <unfinished ...>
[pid  1806] <... epoll_wait resumed> {}, 128, 0) = 0
[pid  6458] <... brk resumed> )         = 0x850000
[pid  6460] stat("/var/lib/kubelet/pods/20787179-acdd-11e6-b2cb-005056a61a8a/volumes/kubernetes.io~secret/default-token-j7yvv", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=140, ...}) = 0
[pid  6468] access("/etc/ld.so.preload", R_OK <unfinished ...>
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000} <unfinished ...>
[pid  6468] <... access resumed> )      = -1 ENOENT (No such file or directory)
[pid  1806] <... select resumed> )      = 0 (Timeout)
[pid  6460] stat("/var/lib/kubelet/pods/20727b97-acdd-11e6-b2cb-005056a61a8a/volumes/kubernetes.io~secret/default-token-j7yvv", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=140, ...}) = 0
[pid  6460] stat("/var/lib/kubelet/pods/2085a2ec-acdd-11e6-b2cb-005056a61a8a/volumes/kubernetes.io~secret/default-token-j7yvv", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=140, ...}) = 0
[pid  6460] stat("/var/lib/kubelet/pods/208bcf17-acdd-11e6-b2cb-005056a61a8a/volumes/kubernetes.io~secret/default-token-j7yvv", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=140, ...}) = 0
[pid  6458] stat("/var/lib/kubelet/pods/2097f257-acdd-11e6-b2cb-005056a61a8a/volumes/kubernetes.io~secret/default-token-j7yvv",  <unfinished ...>
[pid  6468] open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC <unfinished ...>
[pid  6458] <... stat resumed> {st_mode=S_IFDIR|S_ISVTX|0777, st_size=140, ...}) = 0
[pid  6468] <... open resumed> )        = 3
[pid  1806] epoll_wait(5,  <unfinished ...>
[pid  6460] brk(0x1b1c000 <unfinished ...>
[pid  1806] <... epoll_wait resumed> {}, 128, 0) = 0
[pid  6460] <... brk resumed> )         = 0x1b1c000
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000} <unfinished ...>
[pid  6458] stat("/var/lib/kubelet/pods/20920170-acdd-11e6-b2cb-005056a61a8a/volumes/kubernetes.io~secret/default-token-j7yvv", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=140, ...}) = 0
[pid  1806] <... select resumed> )      = 0 (Timeout)
[pid  1806] epoll_wait(5,  <unfinished ...>
[pid  6407] openat(AT_FDCWD, "/sys/fs/cgroup/blkio/system.slice/systemd-resolved.service/blkio.io_service_time_recursive", O_RDONLY|O_CLOEXEC) = 65
[pid  1806] <... epoll_wait resumed> {}, 128, 0) = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000} <unfinished ...>
[pid  1814] stat("/sys/fs/cgroup/cpu,cpuacct/system.slice/kmod-static-nodes.service", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
[pid  1806] <... select resumed> )      = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)
[pid  1806] epoll_wait(5, {}, 128, 0)   = 0
[pid  1806] select(0, NULL, NULL, NULL, {0, 10000}) = 0 (Timeout)

**Comment by darktall** [comment]
guys i have reset  every service including kubernetes services etc. After resetting the whole cluster the load average comes to normal  but still observed timeout issues in kubelet.

below is my kubelet.service configuration

[Service]
ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
Environment="RKT_OPTS=--volume resolv,kind=host,source=/etc/resolv.conf --mount volume=resolv,target=/etc/resolv.conf"

Environment=KUBELET_VERSION=v1.3.6_coreos.0
ExecStart=/usr/lib/coreos/kubelet-wrapper \
  --api-servers=http://x.x.x.x:8080 \
  --network-plugin-dir= \
  --network-plugin= \
  --allow-privileged=true \
  --config=/etc/kubernetes/manifests \
  --hostname-override=x.x.x.x \
Restart=always
RestartSec=10
[Install]
WantedBy=multi-user.target

**Comment by kargakis** [comment]
Please redirect support question in StackOverflow, the kubernetes-users mailing list, or slack.
