### ISSUE TITLE
ConfigMap --flatten switch for --from-file

### ISSUE THREAD

**Issue by dhoer** [kubernetes/kubernetes#37011]
It would be nice to have a `--flatten` option for `configmap create` that would allow `--from-file` to write to the root of data. Keys repeated in later files would overwrite previous values. 

So building on [configmap user-guide](http://kubernetes.io/docs/user-guide/configmap/) example;

Adding `--flatten` option: 
```sh
$ kubectl create configmap game-config-4 --flatten --from-file=docs/user-guide/configmap/kubectl/game.properties --from-file=docs/user-guide/configmap/kubectl/ui.properties
```

Would result in this:
```sh
$ kubectl get configmaps game-config-4 -o yaml
```
```yaml
apiVersion: v1
data:
  enemies=aliens
  lives=3
  enemies.cheat=true
  enemies.cheat.level=noGoodRotten
  secret.code.passphrase=UUDDLRLRBABAS
  secret.code.allowed=true
  secret.code.lives=30
  color.good=purple
  color.bad=yellow
  allow.textmode=true
  how.nice.to.look=fairlyNice
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T19:52:05Z
  name: game-config-4
  namespace: default
  resourceVersion: "578"
  selfLink: /api/v1/namespaces/default/configmaps/game-config-4
  uid: b4952dc3-d670-11e5-8cd0-68f728db1985
```

When `--flatten` option is provided and `--from-file` points to a directory, keys are written to root data and keys repeated in subsequent files would overwrite previous values.

**Comment by dhoer** [comment]
The use case for this is; if I have a product that has core, customer and environment config files, I can read them in that order to overwrite previous settings.

**Comment by bgrant0607** [comment]
See also #8800 and #26299

**Comment by bgrant0607** [comment]
cc @fabianofranz @AdoHe @pwittrock

**Comment by AdoHe** [comment]
```
allow env to point to nested map
```
Compared with this, I would like to add `--flatten`.

**Comment by pmorie** [comment]
I am not sure about the naming of `--flatten`, but I do think this feature would have nice symmetry with what is proposed in #37295

**Comment by dhoer** [comment]
@pmorie Do you see this option being applied to create secret as well?

**Comment by pmorie** [comment]
@dhoer yes, I think parity between configmaps and secrets for control plane functionality like this is desirable.
