### ISSUE TITLE
audit scheduler logging

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#37014]
*Problem* 

There are at least some examples of over logging in the scheduler.

*Solution*

Go through glog.Info and make sure we are consistently managing logs.  At least one example to solve in an easy PR @timothysc  has shared with us..
```
Nov 16 19:49:39 192 atomic-openshift-master-controllers: I1116 19:49:39.522001    5757 priorities.go:51] Combined requested resources 1300 from existing pods exceeds capacity 1000 on node 192.1.24.45
...
```

Ill confirm this is happening still in upstream kube and fix as well as audit the others.

**Comment by piosz** [comment]
part of #37104

**Comment by timothysc** [comment]
yeah lets de-dupe the tickets, we have 3+ issues on this now.. closing this one.
