### ISSUE TITLE
Too long lines in kubelet logs

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#37010]
Some logging destinations don't support entries longer than some number of bytes, for example GCL is limited by 100KB per entry.

Kubelet is known to produce very long lines, longer than 100KB, is it even OK? Because right now such lines are just being discarded by destination and are lost forever. Do we need to add support for such messages on each logging agent?

@piosz

**Comment by piosz** [comment]
cc @dchen1107 @kubernetes/sig-node

**Comment by dchen1107** [comment]
@Crassirostris Do you have examples? What are the logging level? --v 2 or --v 4? I know the developer might dump a lot of information for debugging if the log level is set to be verbose. But in the production, is that still very common?

**Comment by resouer** [comment]
@crassirostris Could you please post one or two kubelet long logs you are referring?
