### ISSUE TITLE
Recommendations for customizing cluster created via kubeadm

### ISSUE THREAD

**Issue by TamalSaha** [kubernetes/kubernetes#37024]
We are exploring the idea of using kubeadm over saltstack as the mechanism for provisioning Kubernetes cluster. But the question if we want to customize various parts of a cluster creation process, what is kubeadm's vision/suggestion is that regard? With the original saltstack mechanism, we could modify the state files and control how various  manifest, etc files were generated. Some of the areas for customization: 

 - We prefer Debian as the host OS. It is not there.
 - What is the recommended way to install various addons? (edited)
 - Some of these addons need config data from the setup (passed via pillars and grains in saltstack)

Thanks.

**Comment by luxas** [comment]
Hi!

Can you please file this issue in kubernetes/kubeadm instead?
We're aggregating the issues there now. Sorry for the inconvenience if any.

Thank you in advance!

**Comment by TamalSaha** [comment]
Filed here: https://github.com/kubernetes/kubeadm/issues/73
