### ISSUE TITLE
Service should favor local pods

### ISSUE THREAD

**Issue by MartinPyka** [kubernetes/kubernetes#37026]
Working with Kubernetes 1.3.6

This is a feature request:

it would be great if there would be any way to tell a service that an incoming request from a pod should be forwarded (if possible) to a pod that is located on the same node. This could save a lot of network traffic.

Example
Node1: worker-pod1, receiver-pod1
Node2: worker-pod2
Node3: worker-pod3, receiver-pod2

receiver-service load-balances receiver-pod1, receiver-pod2

If worker-pod1 sens a request to the receiver-service, its request should always end up on receiver-pod1, if available, because it is available on the same node. worker-pod2 gets redirected rr to either receiver-pod1 or receiver-pod2.

Use cases in which network traffic could be saved: 
- sending logfiles to a local logstash instance
- map/reduce-like scenarios
- worker-nodes sending results to database clients

Best,
Martin

**Comment by foxish** [comment]
cc @bprashanth @kubernetes/sig-network

**Comment by foxish** [comment]
@grodrigues3 Any idea why the issue-categorizer did not act on this one?

**Comment by thockin** [comment]
This is already alpha in 1.4, beta in 1.5.

See "Annotation to modify the LoadBalancer behavior for preservation of Source IP" in http://kubernetes.io/docs/user-guide/load-balancer/

**Comment by grodrigues3** [comment]
@foxish yup, i do.  It's currently off, while we work on establishing new labels.
