### ISSUE TITLE
addon manager needs a "create if not exist" mode

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#37047]
Because of how patch is implemented, we can't manage things like configmaps through addon manager.  If a user edits the configmap and then addon manager applies the config again, the `data` field gets clobbered.  You just can't have 2 owners of an object like that.

I think we have a class of addons that we want to assert absolute or near-absolute truth for, and a series that we just want to initialize and let the user own.  We only get away with this for replicas because of sane defaults.

@mikedanese @MrHohn

**Comment by bgrant0607** [comment]
See also #37048.
