### ISSUE TITLE
[Feature] Add support for optional config-map mounts

### ISSUE THREAD

**Issue by bowei** [kubernetes/kubernetes#37041]
### overview

Currently, pods cannot be created if a config-map referenced by the pod does not exist. This precludes the use of config-map as optional configuration. For instance, the application may chose to use internal defaults if a given config-map does not (yet) exist.

### proposal

A config-map reference that is labeled as optional will show up as an empty directory. In addition, if the referenced config-map come into existence at a later point, it seems natural to have the config-map content show up in the mounted volume.

https://github.com/kubernetes/kubernetes/pull/36775 gives a concrete use case. It is optional for kube-dns to have a config-map and requiring the existence of the config-map will complicate the life-cycle of the kube-dns cluster addon. The current workaround is to obtain the contents of the config-map via the API, but this increases the API surface area used by the application.

**Comment by thockin** [comment]
I think this is a case of usability over purity.

**Comment by MrHohn** [comment]
cc @kubernetes/sig-storage

**Comment by saad-ali** [comment]
> I think this is a case of usability over purity.

Kinda funky, your container starts the dir may be empty, but oh at some point we may drop content in there. That said it's doable AFAIK

cc @pmorie

**Comment by bowei** [comment]
@saad-ali We already update the contents of the directory when the ConfigMap changes without coordinating with the pod, seems not that different to me...

**Comment by thockin** [comment]
This would be an optional feature (pun intended!) that apps don't have to
opt in to if they can't handle it.

**Comment by thockin** [comment]
See https://github.com/kubernetes/community/pull/175
