### ISSUE TITLE
events.StartRecording can't be used from binaries with multiple components

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#3705]
StartRecording is currently static, and only accepts one source for an entire process.  For controller-manager or OpenShift, it would be better to create a recorder for a source and then pass it around rather than using a static reference.  Not a huge issues now, but in deployments where components are colocated it's a limitation.

**Comment by smarterclayton** [comment]
The other option is to never get a meaningful source from an event, but that's not a great option.

**Comment by pmorie** [comment]
@smarterclayton I imagine that the current call sites of `record.Eventf` could be modified to use the interface:

    // not the greatest name, just making a distinction between record.EventRecorder
    type EventContext interface {
        Event(object runtime.Object, message, reason string)
        Eventf(object runtime.Object, reason, messageFmt string, args ...interface{})
    }

A few thoughts:

1.  There should be source-level `StartRecording` and `StartLogging` calls
2.  The creator of the record should call the above methods, not the users of `EventContext`
3.  Is there a hierarchy of sources? Do you have to call `StartRecording` in some root context, for example?

**Comment by pmorie** [comment]
This afternoon when I was working on https://github.com/openshift/origin/pull/1207 I remembered that we still need this; I'll start prototyping something tomorrow.

**Comment by lavalamp** [comment]
> Is there a hierarchy of sources? Do you have to call StartRecording in some root context, for example?

That sounds really complex, I vote no.

StartRecording returns a watch.Interface just to get the .Stop() method; I recommend adding a Stop() method to your EventContext (Recorder?) and then I'm on board with this.

**Comment by pmorie** [comment]
@smarterclayton @lavalamp This can be closed now, resolved by #4974
