### ISSUE TITLE
ROX volumes should have a READONLY flag set in Gluster Volume Spec

### ISSUE THREAD

**Issue by humblec** [kubernetes/kubernetes#37060]
Issue: 

Create a PVC with AccessMode ROX, then describe the PV.
~~~
 [root@dhcp35-111 demo]# ../kubectl.sh describe pv pvc-853f0527-ad4f-11e6-9ab8-54ee7551fd0c
Name:		pvc-853f0527-ad4f-11e6-9ab8-54ee7551fd0c
Labels:		<none>
StorageClass:	fast
Status:		Bound
Claim:		default/claim2
Reclaim Policy:	Delete
Access Modes:	ROX
Capacity:	16Gi
Message:	
Source:
    Type:		Glusterfs (a Glusterfs mount on the host that shares a pod's lifetime)
    EndpointsName:	glusterfs-dynamic-claim2
    Path:		vol_d75482cbbdab8feb2691b4c7e3f5f4ca
    ReadOnly:		false
~~~

Eventhough the claim accessmode has set to `ROX`,  the vol spec has `ReadOnly` flag set 'false', It should be `true`

**Comment by jingxu97** [comment]
cc @kubernetes/sig-storage

**Comment by saad-ali** [comment]
@humblec This is functioning as designed. There's a bigger usability question here, whether these values should somehow be inferred, but at the moment the `AccessMode` in PVC and PV are used only for binding a PVC to available PVs. The `ReadOnly` field in the source is a volume specific designation that controls whether the volume should be attached readonly or not. As designed it is up to the user creating the PV object to ensure it is set correctly.

**Comment by humblec** [comment]
@saad-ali thansk for your comment! I completely agree on the usability question. Also see the `accessmodes` checks are only enforced while binding `pv->pvc`. What  I thought with this patch is that https://github.com/humblec/kubernetes/commit/3a89712553d8039a4c240ff51da074c882d2598a is that ,  the plugin do a `Readonly` mount based on the volume spec https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/glusterfs/glusterfs.go#L297 . So for the dynamically provisioned volumes, if its attached to a PVC which came with `ROX` policy the spec should also match the same. It avoids confusion while seeing/describing the spec and also allows the plugin to mount the volume as `READONLY` in the pod.

**Comment by Rio** [comment]
I'm running into something similar. I've created a glusterfs PV with readonly: true and accessmode set to ReadOnlyMany, created a claim with ROX that got bound to it and created a deployment using that claim. However the PV still gets mounted in readwrite mode eventhough the readonly field in the gluster volume is set to true. It's a bit surprising as it isn't mentioned in the docs that the volume spec in a PodTemplate can overwrite settings from the PV. To get this to work as expected the volume spec in the pod needs to have the readOnly: true flag set aswell.
