### ISSUE TITLE
Review Kubernetes components logs for noise

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#37104]
Some components produce a lot of useless logs, for example pod nanny prints the following messages every 10 second:
```
I1118 17:18:14.340223       1 nanny_lib.go:90] The number of nodes is 3
I1118 17:18:14.435331       1 nanny_lib.go:98] The container resources are {Limits:map[memory:{i:{value:213909504 scale:0} d:{Dec:<nil>} s:204Mi Format:BinarySI}
 cpu:{i:{value:88 scale:-3} d:{Dec:<nil>} s:88m Format:DecimalSI}] Requests:map[cpu:{i:{value:88 scale:-3} d:{Dec:<nil>} s:88m Format:DecimalSI} memory:{i:{value
:213909504 scale:0} d:{Dec:<nil>} s:204Mi Format:BinarySI}]}
I1118 17:18:14.435652       1 nanny_lib.go:102] The expected resources are {Limits:map[cpu:{i:{value:0 scale:0} d:{Dec:0xc820108660} s: Format:DecimalSI} memory:
{i:{value:0 scale:0} d:{Dec:0xc820108ae0} s: Format:BinarySI}] Requests:map[memory:{i:{value:0 scale:0} d:{Dec:0xc820108ae0} s: Format:BinarySI} cpu:{i:{value:0 
scale:0} d:{Dec:0xc820108660} s: Format:DecimalSI}]}
I1118 17:18:14.435789       1 nanny_lib.go:106] Resources are within the expected limits.
```

We should make sure that with the default logging verbosity only the relevant informations are being printed. The list of components to review:
- [ ] api server
- [x] scheduler
- [ ] controller manager
- [ ] glbc
- [ ] etcd
- [ ] autoscaler
- [ ] rescheduler
- [ ] kubelet #37010
- [ ] kube-proxy
- [ ] addons
  - [ ] dns
  - [ ] dashboard
  - [x] heapster+eventer+nanny https://github.com/kubernetes/contrib/issues/2337
  - [ ] glbc
  - [ ] node problem detector
  - [x] fluentd

**Comment by piosz** [comment]
cc @fgrzadkowski @Crassirostris @aleksandra-malinowska

**Comment by piosz** [comment]
cc @timothysc @jayunit100

**Comment by timothysc** [comment]
multiple assignee's here, signing jay and me up for 1.6.

**Comment by piosz** [comment]
Thanks! Once something is fixed please mark this in the issue description.

**Comment by Crassirostris** [comment]
Due to https://github.com/kubernetes/kubernetes/pull/38213 and https://github.com/kubernetes/kubernetes/pull/38286 fluentd logs are no longer a problem, since they are not exported in 1.6

**Comment by Crassirostris** [comment]
Issue, related to heapster: https://github.com/kubernetes/contrib/issues/2337

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by piosz** [comment]
@crassirostris have you made any progress on this?

**Comment by wojtek-t** [comment]
@piosz @crassirostris - any progress on it? Can we move it out of 1.7?

**Comment by crassirostris** [comment]
@wojtek-t No progress yet, sure, moving to 1.7

Are you that should be under sig/scalability, not sig/instrumentation?

**Comment by wojtek-t** [comment]
It probably should be under both - too extensive logging was causing some issues at scale.
