### ISSUE TITLE
Error returns should sanitize URIs

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#37108]
The error reporting functions here all repeat a URI without sanitizing it. An XSS attacker could use this to get the server to embed a reference to a malicious script.

https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/filters/errors.go

(As always, please note that kubernetes apiserver is NOT xss hardened and we do NOT recommend using the api directly from a browser.)

**Comment by timstclair** [comment]
The error correctly sets the content type to `text/plain`, so this is only an issue using a browser that does content sniffing. Would it be sufficient to just add the `X-Content-Type-Options: nosniff` header here?

**Comment by lavalamp** [comment]
Yes, that will work for browsers that honor the header. It's probably sufficient-- we could do that globally, we set Content-Type correctly everywhere, I think.
