### ISSUE TITLE
build test/e2e/e2e.test with bazel

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#37121]

**Comment by dims** [comment]
@mikedanese looks like referenced PR is merged. ok to close?

**Comment by mikedanese** [comment]
No this is not complete.

**Comment by mikedanese** [comment]
This is done. cc @ixdy we should figure out how to run hack/e2e.go with the artifact built from bazel.

**Comment by ixdy** [comment]
`hack/e2e.go` will automatically use the `e2e.test` binary built by bazel if it's the most recent artifact.

**Comment by ixdy** [comment]
https://github.com/kubernetes/kubernetes/blob/227f52e0cb142f5658598e3c981e0e637f8d9c08/hack/lib/util.sh#L176-L180
