### ISSUE TITLE
v1beta1.deploymentspec incorrectly marks progressDeadlineSeconds as required

### ISSUE THREAD

**Issue by AndyMoore111** [kubernetes/kubernetes#37149]
as discussed with @mbohlool in kubernetes 1.4.5 the swagger 2.0 spec has  progressDeadlineSeconds as 'required', when it should be optional

"v1beta1.DeploymentSpec": {
    "description": "DeploymentSpec is the specification of the desired behavior of the Deployment.",
    "required": [
     "template",
     "progressDeadlineSeconds"
    ],

**Comment by dims** [comment]
@AndyMoore111 Is this a blocker for the 1.5 release please mark with label release-blocker (if not, please add non-release-blocker)

**Comment by AndyMoore111** [comment]
@dims I believe so - @mbohlool can you confirm?
