### ISSUE TITLE
Validate URL parameters

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#3714]
Forking from #1052.

We need to document URL parameters in the API.

Also, currently invalid URL parameters are silently ignored, making them error-prone. We should return an error for bogus URL parameters.

/cc @nikhiljindal

**Comment by bgrant0607** [comment]
Pointers to how to specify a query parameter using go-restful's route builder:

https://github.com/emicklei/go-restful/blob/bdfb7d41639a84ea7c36df648e5865cd9fbf21e2/examples/restful-swagger.go#L26
https://github.com/emicklei/go-restful/blob/master/parameter.go
https://github.com/emicklei/go-restful/blob/5aeddab2ca153e662be4ff9efb82f6c6788466d0/route_builder.go#L123
https://github.com/emicklei/go-restful/blob/46f9a38463034c0144a65b9f14cbcdcb3efbe4e8/route_builder_test.go#L7

**Comment by smarterclayton** [comment]
The first part of this is there (we report parameters to swagger).  The validation part is trickier.

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (162/150 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:22191)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-5c7e-dev=imwiz.com@sgmail.github.com>)
	id 1dGTMk-000VNl-Jp
	for dev@imwiz.com; Thu, 01 Jun 2017 10:54:31 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=3nykHvIpePtAoRRZVIxr+3yBQVI=; b=bdg9YKpAde4TOXG2
	KIvVE7uSBwRDnLoXYh9mXIjvXGiq/GgphtCF0/eH/wgRnTjvoTliA601l+xyxUWL
	eL3sOEsWiIqzH1FnmOjofclDNKwepF4TTeZBJQglpCWBbECylu0Yrv4zqQwEORy0
	t8ygtqYb3spNl/ohx3MoNy/dJ04=
Received: by filter0554p1mdw1.sendgrid.net with SMTP id filter0554p1mdw1-30170-593046A1-35
        2017-06-01 16:53:53.585941284 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id tJFQFZ5JQ-qjzju85_kQxA
	for <dev@imwiz.com>; Thu, 01 Jun 2017 16:53:53.535 +0000 (UTC)
Date: Thu, 01 Jun 2017 09:53:53 -0700
