### ISSUE TITLE
Question about secrets and how to consume them in pods

### ISSUE THREAD

**Issue by ranhsd** [kubernetes/kubernetes#37181]
Hi, 
I am using GCP Container Engine in my project and now i am facing some issue that i don't know if it can be solved via secrets.
 
One of my deployments is node-js app server, there i use some npm modules which require my GCP service account key (.json file) as an input. 
The input is the path where this json file is located. Currently i managed to make it work by providing this file as part of my docker image and then in the code i put the path to this file and it works as expected. The problem is that i think that it is not a good solution because i want to decouple my nodejs image from the service account key because the service account key may be changed (e.g. dev,test,prod) and i will not be able to reuse my existing image (unless i will build and push it to a different registry) 
So i wanted to know if it is possible to upload this service account json file as secret and then consume it inside my pod. I saw it is possible to create secrets out of files but i don't know if it is possible to specify the path to the place where this json file is stored. If it is not possible with secrets (because maybe secrets are not saved in files...) so how (and if) it can be done?

Thanks in advanced!

**Comment by resouer** [comment]
Hi @ranhsd ,  you can use `kubectl create secret generic my-secret --from-file=path/to/bar`

Please check for more details: http://kubernetes.io/docs/user-guide/kubectl/kubectl_create_secret_generic/

**Comment by ranhsd** [comment]
Hi @resouer , thank for your  answer. I am familiar with this command and i also execute it and created the secret my question is if i can consume it inside my nodejs pod. The requirement is to provide a path to this file. Do you know if it is possible?
Thanks!

**Comment by resouer** [comment]
Secret can be consumed by Pod thru ENV or volume file, so is http://kubernetes.io/docs/user-guide/secrets/#using-secrets-as-files-from-a-pod covering your request?

It will mount a file contains your Secret data to your Pod.

**Comment by ranhsd** [comment]
Hi @resouer , thanks for your answer. I managed to figure it out. What i did is create a secret from file and then mount volume and consume the volume inside my pod and then put the path to the secret.
