### ISSUE TITLE
Github 'Required' and submit-queue.k8s.io 'required' are out of sync

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#37191]
There are tests (e,g. gce-etcd3) which are required by submit-queue, but not marked as such on Github.

This causes confusion and should be eliminated.

@fejta @kubernetes/test-infra-maintainers

**Comment by gmarek** [comment]
+100

**Comment by mtaufen** [comment]
Where on GitHub are these tests marked?

**Comment by mtaufen** [comment]
Ah, do you mean in the "checks" list that shows per-pr?

**Comment by spxtr** [comment]
I updated them. We don't really have any sort of process in place to set these automatically right now.

**Comment by eparis** [comment]
https://developer.github.com/v3/repos/branches/#update-required-status-checks-of-protected-branch

Seems like the bot 'could' automatically sync these lists.  The one quirk is that the CLA status is "required" by the bot. The bot requires either the CLA status or the "cla: human-approved" label...  So if we started automatically syncing the bot and the github branch protection we'd need to figure out what to do with that...

**Comment by ixdy** [comment]
It seems the etcd3 is still out of date? It's required by SQ, but doesn't show up as required in GitHub.

**Comment by eparis** [comment]
Seems your right. I'll fix the repo.
https://github.com/kubernetes/contrib/blame/master/mungegithub/submit-queue/deployment/kubernetes/configmap.yaml#L15

**Comment by eparis** [comment]
I also wrote a way for the bot to update these automatically yesterday. I'll try to get it cleaned up and pull openned tomorrow.

**Comment by eparis** [comment]
bot keeps these in sync now.
