### ISSUE TITLE
kubeadm init with aws cloud provider hangs on creating test deployment

### ISSUE THREAD

**Issue by ndtreviv** [kubernetes/kubernetes#37205]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:42:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Environment:
```

**Environment**:
- **Cloud provider or hardware configuration**:
AWS EC2 Classic ami-45b69e52 m3.2xlarge instance type in us-east-1 region.

- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- **Kernel** (e.g. `uname -a`):
Linux ip-10-45-51-248 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**:
N/A

- **Others**:
N/A

**What happened**:
I was standing up a 3-node cluster following the instructions here: http://kubernetes.io/docs/getting-started-guides/kubeadm/

Commands I ran on each vm:
```
sudo su -
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF > /etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
apt-get install -y docker.io
apt-get install -y kubelet kubeadm kubectl kubernetes-cni
```
Additional commands run on the master:
```
kubeadm init --cloud-provider=aws
```

Output was as follows:
```
Running pre-flight checks
cloud provider "aws" initialized for the control plane. Remember to set the same cloud provider flag on the kubelet.
<master/tokens> generated token: "a57da0.0787c7da23cded2a"
<master/pki> generated Certificate Authority key and certificate:
Issuer: CN=kubernetes | Subject: CN=kubernetes | CA: true
Not before: 2016-11-18 13:36:38 +0000 UTC Not After: 2026-11-16 13:36:38 +0000 UTC
Public: /etc/kubernetes/pki/ca-pub.pem
Private: /etc/kubernetes/pki/ca-key.pem
Cert: /etc/kubernetes/pki/ca.pem
<master/pki> generated API Server key and certificate:
Issuer: CN=kubernetes | Subject: CN=kube-apiserver | CA: false
Not before: 2016-11-18 13:36:38 +0000 UTC Not After: 2017-11-18 13:36:39 +0000 UTC
Alternate Names: [10.45.51.248 10.96.0.1 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local]
Public: /etc/kubernetes/pki/apiserver-pub.pem
Private: /etc/kubernetes/pki/apiserver-key.pem
Cert: /etc/kubernetes/pki/apiserver.pem
<master/pki> generated Service Account Signing keys:
Public: /etc/kubernetes/pki/sa-pub.pem
Private: /etc/kubernetes/pki/sa-key.pem
<master/pki> created keys and certificates in "/etc/kubernetes/pki"
<util/kubeconfig> created "/etc/kubernetes/kubelet.conf"
<util/kubeconfig> created "/etc/kubernetes/admin.conf"
<master/apiclient> created API client configuration
<master/apiclient> created API client, waiting for the control plane to become ready
<master/apiclient> all control plane components are healthy after 26.051640 seconds
<master/apiclient> waiting for at least one node to register and become ready
<master/apiclient> first node is ready after 2.502080 seconds
<master/apiclient> attempting a test deployment
```

After outputting the last line (`attempting a test deployment`) it doesn't do anything. Ever. I've tried this several times (on newly provisioned VMs each time), and the same thing happens every time.

**What you expected to happen**:
Either complete the test deployment and move on, or show some sort of error indicating what went wrong and ideally a reference to some documentation on how to fix/workaround/do whatever it was I didn't do and was supposed to.

**How to reproduce it** (as minimally and precisely as possible):
Create two AWS EC2 Classic ami-45b69e52 m3.2xlarge instance type in us-east-1 region.
Run the commands as I did.

**Anything else do we need to know**:
No.

**Comment by nnashok** [comment]
Looking at the kube-controller-manager pod description, you'll notice that the command to start the controller does not include specifying the cloud-config:
`
[cloud-user@ip-x-x-x-x ~]$ kubectl -n kube-system describe pod kube-controller-manager-ip-x-x-x-x
Name:           kube-controller-manager-ip-x-x-x-x
Namespace:      kube-system
Node:           ip-x-x-x-x/x.x.x.x
Start Time:     Tue, 22 Nov 2016 20:05:50 -0500
Labels:         component=kube-controller-manager
                tier=control-plane
Status:         Running
IP:             x.x.x.x
Controllers:    <none>
Containers:
  kube-controller-manager:
    Container ID:       docker://32ce0f2ea236c750f44ae0014024ef1f9a205004c39f405cb131724042228a30
    Image:              gcr.io/google_containers/kube-controller-manager-amd64:v1.4.4
    Image ID:           docker://sha256:52730da1c8c939ef1523836af8e8473c56d82cf31a5dde91987a72d4899d6801
    Port:
    Command:
      kube-controller-manager
      --v=2
      --address=127.0.0.1
      --leader-elect
      --master=127.0.0.1:8080
      --cluster-name=kubernetes
      --root-ca-file=/etc/kubernetes/pki/ca.pem
      --service-account-private-key-file=/etc/kubernetes/pki/apiserver-key.pem
      --cluster-signing-cert-file=/etc/kubernetes/pki/ca.pem
      --cluster-signing-key-file=/etc/kubernetes/pki/ca-key.pem
      --insecure-experimental-approve-all-kubelet-csrs-for-group=system:kubelet-bootstrap
      --cloud-provider=openstack
`

**Comment by nnashok** [comment]
Additionally, the `/etc/kubernetes/cloud-config.conf` (default) file is not copied to the nodes and as a result the nodes fail to come up. The workaround is to have this file created by the user (either before or after running `kubeadm join...`).

**Comment by luxas** [comment]
Hi!

Can you please file this issue in kubernetes/kubeadm instead?
We're aggregating the issues there now. Sorry for the inconvenience if any.

Thank you in advance!

**Comment by smenon78** [comment]
I am running into same issue, what was the resolution?

**Comment by nnashok** [comment]
I filed https://github.com/kubernetes/kubeadm/issues/75 and https://github.com/kubernetes/kubeadm/issues/77 . I've listed the workarounds in both the issues.

**Comment by smenon78** [comment]
I don't have this file /etc/kubernetes/cloud-config.conf. Do I need to create this manually? What is the content of this file?

**Comment by nnashok** [comment]
Yes, you have to create it. If you are using OpenStack, it would be something similar to:
```
[Global]  
auth-url=https://openstack.company.com:5000/v2.0
username=***
password=***
region=EAST
tenant-id=eadb97402be284b01aa5ae9e874295fce # (note: tenant-id is project id)
```

**Comment by smenon78** [comment]
What about aws?

**Comment by smenon78** [comment]
I cannot find anywhere what /etc/kubernetes/cloud-config.conf file should look like if it is cloud provider is AWS. Anyone has an example?

**Comment by hangyan** [comment]
@smenon78 The basic config example is like:

```
[Global]
Zone = cn-north-1a
```

**Comment by knepperjm** [comment]
Does this flag even exist any longer?
