### ISSUE TITLE
[k8s.io] Restart [Disruptive] should restart all nodes and ensure all nodes and pods recover

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#37202]
The restart test is broke by https://github.com/kubernetes/kubernetes/pull/37070.

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/restart.go:124
Expected error:
    <*errors.errorString | 0xc420cd42a0>: {
        s: "couldn't find 28 pods within 5m0s; last error: expected to find 28 pods but found only 29",
    }
    couldn't find 28 pods within 5m0s; last error: expected to find 28 pods but found only 29
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/restart.go:119
```

The original issue is https://github.com/kubernetes/kubernetes/issues/34003. The reason is https://github.com/kubernetes/kubernetes/issues/34003#issuecomment-251491143:

> The mirror pod of the e2e-image-puller pod has been deleted in the network partition test by the node controller. kubelet currently doesn't try to recreate the mirror pod (or even sync it) if the pod has already terminated. In the restart test, kubelet got restarted, and the in-memory status cache was cleared. kubelet then decides to sync the pod once to generate the status, which leads to creating of the mirror pod.

We fixed this by filtering out `RestartNever` mirror pod in the test. However https://github.com/kubernetes/kubernetes/pull/37070 changed `image-puller` to `RestartOnFailure` which broke the workaround.

A quick fix is to filter out non-RestartAlways pods. Because either `RestartNever` or `RestartOnFailure` pods could succeed, and we can not deal with terminated mirror pods very well now.

@yujuhong @gmarek 
/cc @kubernetes/sig-node

**Comment by gmarek** [comment]
Yeah... I see there's a number of problems here. I looked at the history of the image puller config and it looked to me that it was 'Never' from the beginning...

Thanks for the fix though.

**Comment by calebamiles** [comment]
@Random-Liu @yujuhong, @gmarek  is this a release blocker for 1.5? Please update the issue ASAP, thanks!

**cc: @kubernetes/sig-node, @saad-ali, @dims**
