### ISSUE TITLE
Handle test owners better than currently

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#37207]
Test owners are assigned by the bot using a csv that is manually updated with a python script. Some problems I have identified:

1. Nothing requires the script to run when new tests are added or old tests are removed from the repo. 
2. ~~I see verification failures in irrelevant (to test changes eg. https://github.com/kubernetes/kubernetes/pull/37091 + https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/37091/pull-kubernetes-verify/5177/build-log.txt) PRs that block the PRs from being added in the queue and that's frustrating. Really strange because of 1.~~
3. Running the python script adds me in a bunch of tests that I shouldn't be the maintainer of. Test owners should be added automatically for new tests, when these tests are checked-in. Or at least, the script should be smart enough to assign the creator of the test.

@kubernetes/test-infra-admins @kubernetes/test-infra-maintainers @kubernetes/sig-testing

**Comment by ixdy** [comment]
I believe we disabled the verification check for test owners (which required the script to be run when tests were added or removed) because there were too many merge conflicts on the test owners file.

In the log you linked, the test owners check didn't fail, but the `verify-federation-openapi-spec.sh` check did:

```
I1118 06:33:18.879] diff -Naupr -I 'Auto generated by' /go/src/k8s.io/kubernetes/federation/apis/openapi-spec/swagger.json /go/src/k8s.io/kubernetes/_tmp_federation/openapi-spec/swagger.json
I1118 06:33:18.879] --- /go/src/k8s.io/kubernetes/federation/apis/openapi-spec/swagger.json	2016-11-18 06:33:18.854877892 -0800
I1118 06:33:18.879] +++ /go/src/k8s.io/kubernetes/_tmp_federation/openapi-spec/swagger.json	2016-11-18 06:18:15.163249033 -0800
I1118 06:33:18.879] @@ -10193,7 +10193,7 @@
I1118 06:33:18.879]        "$ref": "#/definitions/intstr.IntOrString"
I1118 06:33:18.880]       },
I1118 06:33:18.880]       "maxUnavailable": {
I1118 06:33:18.880] -      "description": "The maximum number of pods that can be unavailable during the update. Value can be an absolute number (ex: 5) or a percentage of desired pods (ex: 10%). Absolute number is calculated from percentage by rounding down. This can not be 0 if MaxSurge is 0. By default, a fixed value of 1 is used. Example: when this is set to 30%, the old RC can be scaled down to 70% of desired pods immediately when the rolling update starts. Once new pods are ready, old RC can be scaled down further, followed by scaling up the new RC, ensuring that the total number of pods available at all times during the update is at least 70% of desired pods.",
I1118 06:33:18.880] +      "description": "The maximum number of pods that can be unavailable during the update. Value can be an absolute number (ex: 5) or a percentage of desired pods (ex: 10%). Absolute number is calculated from percentage by rounding up. This can not be 0 if MaxSurge is 0. By default, a fixed value of 1 is used. Example: when this is set to 30%, the old RC can be scaled down to 70% of desired pods immediately when the rolling update starts. Once new pods are ready, old RC can be scaled down further, followed by scaling up the new RC, ensuring that the total number of pods available at all times during the update is at least 70% of desired pods.",
I1118 06:33:18.880]        "$ref": "#/definitions/intstr.IntOrString"
I1118 06:33:18.880]       }
I1118 06:33:18.880]      }
I1118 06:33:18.880] /go/src/k8s.io/kubernetes/federation/apis/openapi-spec is out of date. Please run hack/update-federation-openapi-spec.sh
I1118 06:33:18.884] [0;31mFAILED[0m   hack/make-rules/../../hack/verify-federation-openapi-spec.sh	105s
```

**Comment by ixdy** [comment]
cc @rmmh

**Comment by kargakis** [comment]
@ixdy thanks, one point down.

**Comment by bgrant0607** [comment]
We also need every test to be associated with a SIG so that we can automatically label the automatically created issues.

**Comment by spiffxp** [comment]
re: associating tests with SIG's #42670

**Comment by rmmh** [comment]
#45691 added test_owners.json to associate test prefixes with SIGs directly.
