### ISSUE TITLE
Can't apply existing secret with new key with empty value.

### ISSUE THREAD

**Issue by kramarz** [kubernetes/kubernetes#37216]
**Is this a request for help?**: no

**What keywords did you search in Kubernetes issues before filing this one?**: empty secret

---

**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Kubernetes version**:v1.4.3

**Environment**:
- **Cloud provider or hardware configuration**: minikube with virtualbox driver
- **OS** (e.g. from /etc/os-release): `Boot2Docker 1.11.1 (TCL 7.1); master : 901340f - Fri Jul  1 22:52:19 UTC 2016`
- **Kernel** (e.g. `uname -a`): `Linux minikube 4.4.14-boot2docker #1 SMP Fri Jul 1 21:46:36 UTC 2016 x86_64 GNU/Linux`

**What happened**:
Applying yaml with secret via kubectl with empty value for one of keys didn't create that key. It only happened if secret already existed. Check how to reproduce.

**What you expected to happen**:
It should create that key with empty value.

**How to reproduce it**:
```
$ kubectl create secret generic test --dry-run --from-literal=x= -o yaml | kubectl apply -f -
secret "test" created
$ kubectl describe secrets test
Name: test
Namespace: default
Labels: <none>
Annotations: kubectl.kubernetes.io/last-applied-configuration={"kind":"Secret","apiVersion":"v1","metadata":{"name":"test","creationTimestamp":null},"data":{"x":null}}

Type: Opaque

Data
====
x: 0 bytes 
$ kubectl create secret generic test --dry-run --from-literal=x= --from-literal=y= -o yaml | kubectl apply -f - 
secret "test" configured 
$ kubectl describe secrets test
Name: test 
Namespace: default 
Labels: <none> 
Annotations: kubectl.kubernetes.io/last-applied-configuration={"kind":"Secret","apiVersion":"v1","metadata":{"name":"test","creationTimestamp":null},"data":{"x":null,"y":null}} 
 
Type: Opaque 
Data 
==== 
x: 0 bytes 
$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"clean", BuildDate:"2016-10-16T06:36:33Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"} 
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"} 
```
Note that y key appears in annotations but not in Data. If secret is not empty it works.

**Anything else do we need to know**:
Empty values are sometimes useful substitutes for secrets in development. That is why i tested it on minikube.

**Comment by AdoHe** [comment]
@ymqytw ptal.

**Comment by ymqytw** [comment]
The first `kubectl apply` is actually using `POST`, since this resource doesn't exist.
The second `kubectl apply` is using `PATCH`, which doesn't support a `null` as value. Because `y: null` in `PATCH` means delete the field whose key is `y`.

As a work around, you can use `kubectl create secret generic test --dry-run --from-literal=x= --from-literal=y= -o yaml | kubectl replace -f - `, where `kubectl replace` is using `PUT` that support `null` as value.
And for security reason, we don't recommend using `kubectl apply` for secrets. Because they are leaking secrets. Ref: #23564

**Comment by kramarz** [comment]
Using replace is sufficient for me. Thanks. If I can suggest anything, then empty string and null should be distinguished in api (even if it is not distinguished internally)
