### ISSUE TITLE
How can I scale up of down replication controller with kubernetes api 

### ISSUE THREAD

**Issue by medhedifour** [kubernetes/kubernetes#37233]
Can scale up or down rc from a pod using kubernetes api without updating the file source of the replication controller.

**Comment by nebril** [comment]
I think this question belongs on stackoverflow.com , under `kubernetes` tag.

**Comment by bgrant0607** [comment]
http://kubernetes.io/docs/search/?q=scale

If you have further questions, please ask on stackoverflow.

**Comment by medhedifour** [comment]
@bgrant0607 
@nebril 
ok I'll post this question on  stackoverflow.
but my question wasn't how to scale up an rc with cmd , obviously with " kubectl scale rc -- replicas"
but it was how to do this with **# **kubernetes API**** from a pod.
I was able to get access to kubernetes api from a pod, and it was possible also to update the rc yaml file and redeploy it (with an update of the rc) using kubernetes api from a pod. But I search for another solution to do this with simplicity.
