### ISSUE TITLE
Dynamic volume provisioning in examples: volume.(alpha|beta).kubernetes.io/storage-class

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#37239]
The behavior has changed between the alpha and beta annotations (.kubernetes.io/storage-class), and using the beta annotation.
* Using the alpha annotation, a PV is provisioned irrespective of the "value" supplied.
* Using the beta annotation, a PV is not provisioned unless a StorageClass of that name exists on the server.

http://blog.kubernetes.io/2016/10/dynamic-provisioning-and-storage-in-kubernetes.html mentions that the alpha annotation is depreciated and that one should use the beta annotation.
However, the documentation says that the alpha annotation has "beta level support" (http://kubernetes.io/docs/user-guide/persistent-volumes/#writing-portable-configuration)

We could do the following:
* Continue to use the alpha annotation.
* Move to use the beta annotation but recommend that the user create a StorageClass explicitly in their cluster.
* Have users create a default storage class and have no annotation in examples.

What's the recommended way of presenting examples with dynamic volume provisioning?

@saad-ali @kubernetes/sig-storage 
/cc @erictune @janetkuo @enisoc @kow3ns

**Comment by calebamiles** [comment]
@foxish, I am assuming this is a non release blocker and if you could add a label signifying as such that would be greatly appreciated. Thanks!

**cc: @saad-ali, @dims**

**Comment by saad-ali** [comment]
> What's the recommended way of presenting examples with dynamic volume provisioning?

My recommendation would be to have no annotation on PVC in examples. Put a blurb indicating that if a default `StorageClass` exists, it will be used to automatically provision a PV to fulfill the PVC. If no `StorageClass` is specified the user should either create one or manually create a PV to fulfill the PVC.

Once https://github.com/kubernetes/kubernetes/pull/31617 is merged in v1.6 common cloud providers should ship with a default `StorageClass` "out-of-the-box".

CC @erictune @jsafrane @thockin @kubernetes/sig-storage

**Comment by jsafrane** [comment]
IMO, if you're happy with alpha behavior, keep it there and remove the annotation as @saad-ali suggests when 1.6 is released.

**Comment by dims** [comment]
@foxish Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by foxish** [comment]
Closing this, since we're continuing to use the alpha annotation in examples for now.
