### ISSUE TITLE
can I scale up rc from a pod using kubernetes api without recreating the rc file

### ISSUE THREAD

**Issue by medhedifour** [kubernetes/kubernetes#37240]
can I scale up or down rc  from a pod using kubernetes api without recreating/updating the rc file.

**Comment by kargakis** [comment]
You can use curl and PUT a Scale subresource to the [scale endpoint](https://github.com/kubernetes/kubernetes/blob/09bb156116aed4542d66d51b052e1a7357ea57e8/api/swagger-spec/v1.json#L11454). Or you could have `kubectl` inside a container of your Pod and use `kubectl scale`.

**Comment by medhedifour** [comment]
@kargakis 
Thanks
