### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by mancubus77** [kubernetes/kubernetes#37242]
A deployment with kube-up.sh can not be completed with following error:
```
kube-proxy     100%   69MB   69.0MB/s   00:01    
flanneld.conf  100%    579      0.6KB/s     00:00    
flanneld       100%   2121     2.1KB/s     00:00    
Failed to start flanneld.service: Unit flanneld.service not found.
Connection to k8-1 closed.
Deploying node on machine k8-1 failed
```
Any ideas where to dig, because there I can not find any debug or logging to figure out a cause of issue

**Comment by Dm3Ch** [comment]
I'm not completely sure, but when i was using kube-up.sh last time it haven't got systemctl services, it only had got plain init files. I got same error on ubuntu 16.04. I fixed it by adding required systemd .system files on each node manually.

For flanneld you could use https://github.com/coreos/coreos-overlay/blob/master/app-admin/flannel/files/flanneld.service
For other parts of kubernetes you could find .service files here https://github.com/kubernetes/contrib/tree/master/init/systemd
