### ISSUE TITLE
version or vendor golint for verification checks?

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#37254]
In our test-infra we [`go get github.com/golang/lint/golint`](https://github.com/kubernetes/test-infra/blob/master/jenkins/test-image/Dockerfile-1.4#L53-L54) in the kubekins-test image to use in the various \*-verify-\* jobs.

Recently, we updated the `kubekins-test` image, which ended up pulling in a newer version of `golint` with [a new check](https://github.com/golang/lint/commit/3390df4df2787994aea98de825b964ac7944b817). And now the verify-1.4 jobs [are failing](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-verify-release-1.4/467/) due to this new check:
```
I1121 16:07:11.555] Verifying hack/make-rules/../../hack/verify-golint.sh
W1121 16:07:32.929] Errors from golint:
W1121 16:07:32.929] pkg/storage/etcd3/store_test.go:548:1: context.Context should be the first parameter of a function
W1121 16:07:32.929] 
W1121 16:07:32.929] Please fix the above errors. You can test via "golint" and commit the result.
W1121 16:07:32.930] 
I1121 16:07:32.933] FAILED   hack/make-rules/../../hack/verify-golint.sh	21s
```

While 1.4 is still fairly recent, we could imagine older release branches breaking similarly, and I'm not sure we want to fix lint failures in old releases.

Should we figure out some way to version/vendor golint for these checks?

cc @kubernetes/test-infra-maintainers @kubernetes/sig-testing

**Comment by ixdy** [comment]
cc @jessfraz

**Comment by ixdy** [comment]
Prior discussion (which didn't really get resolved): #35985

This particular error was fixed in master in #35703, and is small enough that we could just cherry-pick back to release-1.4.

**Comment by ixdy** [comment]
also, from https://github.com/golang/lint/pull/148#issuecomment-130847557:
> Please read the README. Golint is absolutely not suitable for use in a CI environment. Don't do that.

**Comment by ixdy** [comment]
https://github.com/golang/lint/blob/master/README.md

emphasis mine:
> The suggestions made by golint are exactly that: suggestions. Golint is not perfect, and has both false positives and false negatives. Do not treat its output as a gold standard. We will not be adding pragmas or other knobs to suppress specific warnings, so do not expect or require code to be completely "lint-free". **In short, this tool is not, and will never be, trustworthy enough for its suggestions to be enforced automatically, for example as part of a build process.**

**Comment by jessfraz** [comment]
so should we pin to a hash?

**Comment by jessfraz** [comment]
we could do something like this in the dockerfile:

```
# Dependency for golint
ENV GO_TOOLS_COMMIT 823804e1ae08dbb14eb807afc7db9993bc9e3cc3
RUN git clone https://github.com/golang/tools.git /go/src/golang.org/x/tools \
	&& (cd /go/src/golang.org/x/tools && git checkout -q $GO_TOOLS_COMMIT)

# Grab Go's lint tool
ENV GO_LINT_COMMIT 32a87160691b3c96046c0c678fe57c5bef761456
RUN git clone https://github.com/golang/lint.git /go/src/github.com/golang/lint \
	&& (cd /go/src/github.com/golang/lint && git checkout -q $GO_LINT_COMMIT) \
	&& go install -v github.com/golang/lint/golint
```

**Comment by dims** [comment]
Sounds like the sane thing to do @jessfraz +1 from me.

**Comment by eparis** [comment]
Is it possible to pin the version in certain branches but use HEAD on master? I know its a pain when other projects break us, but it definitely helps with code quality more than the pain we've suffered. Pinning largely means giving up on future improvements they add.

/me still things golint should admit it is reasonable to be used in CI.

**Comment by jessfraz** [comment]
yeah it will be done in the version images, so my patch will only apply to 1.4

**Comment by ncdc** [comment]
Does the CI check out the latest golint HEAD each time?

**Comment by jessfraz** [comment]
no it's in the CI image:
https://github.com/kubernetes/test-infra/blob/master/jenkins/test-image/Dockerfile-1.5

**Comment by ncdc** [comment]
So this means that if I have a newer version of golint locally that adds new rules, my code my fail the golint check locally but pass in CI. I think we need to pin the golint version in hack/verify-golint.sh.

**Comment by ixdy** [comment]
@ncdc worse, things may arbitrarily start failing when we update the CI image, as happened here.

Can we just vendor `golint` in `kubernetes/kubernetes/vendor` and use that in `hack/verify-golint.sh`? that way we don't have to do anything special in CI vs dev workflows, we don't have to do hacky things around `go get`, we automatically get pinning for each branch, and we can fix golint failures when we update the revision.

**Comment by ncdc** [comment]
@ixdy yeah it goes both ways 😄

**Comment by eparis** [comment]
@ixdy this is the equivalent of (I think) never updating golint ever again. Who is going to update it, go through the code base, and fix everything all at once? It will just be a big chunk of work that no one will want to do.

Random breaks in master stink. But it is master, we should be fast enough to handle such little things. It also means we handle them in small manageable chucks and we have a very small amount of 'cruft' build it before someone fixes it. Keeping golint up to date means occasional breakage on master but spreading the effort to keep good code style quality to everyone. freezing golint means no master breakage but it centralizes the effort into one person. A person who does not exist...


I'm all for freezing golint on release branches. We had a style and set of rules when we released that branch and that should be fixed in time. But I think master should keep marching forward and we should just deal with life on master as we go along.

**Comment by ixdy** [comment]
@eparis two concerns:
1. Having `go get github.com/foo` in CI has caused us flake-pain in the past. This is one of the motivations for putting it in the Docker image. Maybe we're OK with a low-level flake rate.
2. I'm not sure how we pin a particular golint version for release branches. Ideally this would be automated. https://github.com/kubernetes/test-infra/pull/1239 is manually pinning for release-1.4 and earlier, but it doesn't seem like a general solution yet.

**Comment by ixdy** [comment]
`golint` updated again, and it broke both `master` and `release-1.5`. We probably need to pin it for 1.5 at least.
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-verify-release-1.5/828/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-verify-master/613/

**Comment by saad-ali** [comment]
@ixdy Are you working on pinning for 1.5?

**Comment by ixdy** [comment]
not ATM, though the breaking PR was reverted. @jessfraz said she might own pinning in https://github.com/kubernetes/test-infra/pull/1283#issuecomment-264982520.

**Comment by saad-ali** [comment]
Ack, thanks. @jessfraz I'll keep an eye out for the PR/cherry-pick

**Comment by jessfraz** [comment]
ok cool will do!

**Comment by porridge** [comment]
FWIW, this strikes again. Recent golint added a new check (for redundant error checks).

This means that anyone who happens to follow the advice from `hack/verify-golint.sh` to just `go get -u github.com/golang/lint/golint` (i.e. a new contributor) will get a shiny new golint which complains about problems completely not related to whatever they are doing:

```
porridge@kielonek:~/projects/go/src/k8s.io/kubernetes$ hack/verify-golint.sh
Errors from golint:
cmd/kubeadm/app/cmd/upgrade/apply.go:244:2: redundant if ...; err != nil check, just return error instead.
cmd/kubeadm/app/cmd/upgrade/apply.go:271:2: redundant if ...; err != nil check, just return error instead.
cmd/kubeadm/app/phases/addons/proxy/proxy.go:102:2: redundant if ...; err != nil check, just return error instead.
[10 more
```

This of course makes `make verify` fail, making new contributor's life miserable.

@kubernetes/sig-contributor-experience-bugs

**Comment by porridge** [comment]
@eparis regarding your https://github.com/kubernetes/kubernetes/issues/37254#issuecomment-263970290, how about bumping golint whenever we bump the go toolchain that we use?
It's not vital that we're on the freshest golint at all times, after all..

**Comment by spxtr** [comment]
As in https://github.com/kubernetes/kubernetes/issues/37254#issuecomment-262116581, I think we're just using golint wrong. [Most k8s packages](https://github.com/kubernetes/kubernetes/blob/b3a9b802da9a072cc6daed0baf6f09a8ba1a1ae2/hack/.golint_failures) do not pass golint. Instead, we should delete `verify-golint` in favor of making [prow's golint plugin](https://github.com/kubernetes/test-infra/tree/6d955e5ad9d1513b492d8640674e4debdd5180b9/prow/plugins/golint) run for all PRs in a not-annoying way.

**Comment by eparis** [comment]
@spxtr  and I just disagree on this one   :)

@porridge just proved why pinning was a bad idea to begin with. This should have been caught as soon as golint was updated. Not by you. I'm sorry about your experience.

Maybe I'm too strongly colored by my previous work as a kernel maintainer. gcc warnings were originally largely if not entirely ignored. gcc warnings came with a similar 'we aren't perfect' statement at the time. It took literally years for us to get all of the warnings out of common kernel builds and we fixed tons of bugs along the way. Cleaning up after hundreds of people have been allowed to do something is really hard. The only way to not suffer that pain is to not allow people to do it wrong to start with!

I just feel like vendor'd goling on a release branch makes sense. And head on head makes sense. As soon as you stop enforcement or start pinning you quickly fall behind. Just look, we pinned to an old version and broke porridge. But it seems I've already lost this battle, so I'll stop tilting at windmills   :)

**Comment by spxtr** [comment]
I think the equivalent of gcc warnings is more like `go vet`, which we do require to pass for all packages. Golint tends to be things like "this is a public thing and so it needs a comment explaining it." Most public things do deserve a doc comment, but many do not. It's up to the author and reviewer.

The world we live in now is pretty pitiful. Basically no packages pass golint, and that fact isn't exposed to PR authors in any way. Adding more golint-failing code to an already-failing package doesn't cause any problems to show up on the PR. I think we can move toward a better world by running [this thing](https://github.com/kubernetes/test-infra/pull/5034#pullrequestreview-70423968) against all PRs.

**Comment by dims** [comment]
/close 

i think we are stable with what we have in `hack/verify-golint.sh`
