### ISSUE TITLE
K8s claims GCE Persistent Disk FailedMount Despite Successful Mount - Pod Stuck

### ISSUE THREAD

**Issue by paul-symphony** [kubernetes/kubernetes#37253]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.4.6

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): Google, Container-Optimized OS, beta 55-8872.47.0, Kernel: ChromiumOS-4.4.4 Kubernetes: 1.4.5 Docker: 1.11.2
- **Kernel** (e.g. `uname -a`): Linux gke-warpdrive-default-pool-eae1f3b0-spgr 4.4.21+ #1 SMP Thu Nov 10 21:43:53 PST 2016 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
A a persistent disk was created via:
```
gcloud compute disks create warpdrive-jenkins-home --type pd-standard
```

This persistent disk is referenced in a K8s Deployment (yaml).  The Pod failed on startup, due to FailedMount followed by FailedSync.
```
$ kubectl describe pods --namespace=jenkins | tail 
Events:
  FirstSeen	LastSeen	Count	From	SubobjectPath	Type	Reason	Message
  ---------	--------	-----	----	-------------	--------	------	-------
  5m	5m	1	{default-scheduler }	Normal	Scheduled	Successfully assigned jenkins-master-3888267560-x2rpc to gke-warpdrive-default-pool-af4bf63e-qjrx
  3m	1m	2	{kubelet gke-warpdrive-default-pool-af4bf63e-qjrx}	Warning	FailedMount	Unable to mount volumes for pod "jenkins-master-3888267560-x2rpc_jenkins(5f752595-b01a-11e6-972b-42010a8e0029)": timeout expired waiting for volumes to attach/mount for pod "jenkins-master-3888267560-x2rpc"/"jenkins". list of unattached/unmounted volumes=[jenkins-home]
  3m	1m	2	{kubelet gke-warpdrive-default-pool-af4bf63e-qjrx}	Warning	FailedSync	Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "jenkins-master-3888267560-x2rpc"/"jenkins". list of unattached/unmounted volumes=[jenkins-home]
```

Interestingly, the persistent disk was actually attached:
```
$ gcloud compute disks describe warpdrive-jenkins-home | tail 
lastAttachTimestamp: '2016-11-21T10:43:21.433-08:00'
lastDetachTimestamp: '2016-11-21T10:37:20.688-08:00'
name: warpdrive-jenkins-home
selfLink: https://www.googleapis.com/compute/v1/projects/symphony-gce-dev/zones/us-east1-b/disks/warpdrive-jenkins-home
sizeGb: '1000'
status: READY
type: https://www.googleapis.com/compute/v1/projects/symphony-gce-dev/zones/us-east1-b/diskTypes/pd-standard
users:
- https://www.googleapis.com/compute/v1/projects/symphony-gce-dev/zones/us-east1-b/instances/gke-warpdrive-default-pool-af4bf63e-qjrx
zone: https://www.googleapis.com/compute/v1/projects/symphony-gce-dev/zones/us-east1-b
```

I attempted to recreate <insert everything possible here>, but the issue persisted across all attempts.

Worth noting is that the issue is avoided if the persistent disk is defined by:
```
gcloud compute images create jenkins-home-image --source-uri https://storage.googleapis.com/solutions-public-assets/jenkins-cd/jenkins-home-v2.tar.gz
gcloud compute disks create jenkins-home --image jenkins-home-image
```

Also worth noting is that I was able to ssh into a node and manually mount, write some files, unmount, then have K8s auto detach/attach via deletion/creation of Deployments, and then manually mount and verify that written files were there.  

**What you expected to happen**:
I expected the persistent disk to attach and mount with no issue.

**How to reproduce it** (as minimally and precisely as possible):
- gcloud container clusters create warpdrive --machine-type n1-standard-4 --num-nodes 4 --subnetwork sym-infra-dev-guse1 --enable-autoscaling --min-nodes 4 --max-nodes 20 --scopes "https://www.googleapis.com/auth/projecthosting,storage-rw"
- gcloud compute disks create warpdrive-jenkins-home --type pd-standard
- kubectl create ns jenkins
- create Deployment with:
```
    volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
      volumes:
      - name: jenkins-home
        gcePersistentDisk:
          pdName: warpdrive-jenkins-home
          fsType: ext4
          partition: 1
```
- watch in horror as the pod fails 

**Anything else do we need to know**:
We're desperate

**Comment by jingxu97** [comment]
@paul-symphony, do you still have problem for starting the pod? I think @rootfs mentioned in another thread to remove partition:1 in the yaml file

**Comment by paul-symphony** [comment]
yup, that was it!  removing partition:1 resolved the issue, thanks!

**Comment by jingxu97** [comment]
@paul-symphony thanks for confirming. close this issue.
