### ISSUE TITLE
Incorrect selfLink path when querying resources via REST apiserver

### ISSUE THREAD

**Issue by tonylambiris** [kubernetes/kubernetes#37266]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): api namespace path slash missing

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-beta.1", GitCommit:"8c6525e891be1c44cbdd6fcf53097a3adb11d68c", GitTreeState:"clean", BuildDate:"2016-11-21T05:16:10Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-beta.1", GitCommit:"8c6525e891be1c44cbdd6fcf53097a3adb11d68c", GitTreeState:"clean", BuildDate:"2016-11-21T05:16:10Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Vagrant environment on Linux x86_64
- **OS** (e.g. from /etc/os-release): RHEL clone
- **Kernel** (e.g. `uname -a`): Linux csos-builder.csos.io 4.8.8-1.el7.csos.x86_64 #1 SMP Wed Nov 16 08:51:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: Installed from RPMs generated with a build script
- **Others**: 

**What happened**:
The selfLink namespace path doesn't have a slash between the end of the namespace and the resource itself.
This was tracked down as a side effect of debugging why Heapster was no longer processing pod metrics. Here curl output (compacted with jq) from a fresh machine:
```
# curl -s -k https://172.27.1.10:6443/api/v1/namespaces
{"kind":"NamespaceList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/namespaces/","resourceVersion":"1807"},"items":[{"metadata":{"name":"default","selfLink":"/api/v1/namespacesdefault","uid":"55a50c17-b068-11e6-a4d3-080027a649ab","resourceVersion":"6","creationTimestamp":"2016-11-22T04:01:24Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}},{"metadata":{"name":"kube-system","selfLink":"/api/v1/namespaceskube-system","uid":"56333705-b068-11e6-a4d3-080027a649ab","resourceVersion":"26","creationTimestamp":"2016-11-22T04:01:25Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}]}
```

In addition this also affects the `watch` verb on a resource (output trimmed):
```
# curl -s -k https://172.27.1.10:6443/api/v1/watch/nodes
{"type":"ADDED","object":{"kind":"Node","apiVersion":"v1","metadata":{"name":"builder","selfLink":"/api/v1/nodesbuilder","uid":"55b6a17a-b068-11e6-a4d3-080027a649ab","resourceVersion":"4209","creationTimestamp":"2016-11-22T04:01:24Z","labels":
```

Running `kubectl` returns correct output:
```
# kubectl get node 
NAME           STATUS    AGE
builder   Ready     59m
```

**What you expected to happen**:
Expected the REST interface to return the correct selfLink path

**How to reproduce it** (as minimally and precisely as possible):
Build v1.5.0-beta.1 from git and run the above curl commands.

**Anything else do we need to know**:

**Comment by brandoncole** [comment]
We're also seeing this issue for namespaces - while cosmetic and easily worked around - curious about feedback on whether this is perceived as correct or incorrect.  I assume it's incorrect :)

**Comment by brandoncole** [comment]
Maybe @chrislovecnm or @kris-nova or @justinsb might know who to tag to raise awareness of this?

**Comment by chrislovecnm** [comment]
I will ping the API server folks. Big question is how to recreate this ;)

**Comment by danielqsj** [comment]
Fixed in #44909

**Comment by chrislovecnm** [comment]
@tonylambiris can we close this?

**Comment by tonylambiris** [comment]
@chrislovecnm yup, closing now. Thanks everyone!
