### ISSUE TITLE
Datacenter components auto installation and management tool

### ISSUE THREAD

**Issue by typhoonzero** [kubernetes/kubernetes#37265]
We are currently working on https://github.com/k8sp/sextant to solve: 
* install Linux(currently CoreOS and CentOS) through PXE with kubernetes
* host DHCP and DNS
* templating cloud-config files in order to install different roles of kubernetes
* put kubernetes, ceph, tensorflow together
* a small bootstrapper container providing all above

This tool is already used on our production evironment. We noticed that we already have "kubeadm" tool to make installation easy. The question is, can we put sextant and kubeadm together to provide more general auto installation/management for a production cluster, or just let user choose?

**Comment by resouer** [comment]
`kubeadm` is designed to make `k8s` deployment less painful (e.g. bringing up k8s cluster with 4 commands). And the first of all principle to achieve this is: keep kubeadm simple. 

So I don't think we have intent to expand it or integrate it with anything else unless our original goal is to make `kubeadm` simpler than today. That also implies one of the right directions could be `sextant` use `kubeadm` :)

btw, I can see `sextant` may be a good candidate for `kubernetes/contrib` repo.

Anyhow we need to leave decisions to @kubernetes/sig-cluster-lifecycle

**Comment by resouer** [comment]
And cc @luxas for some thoughts :)

**Comment by roberthbailey** [comment]
We'd like for `kubeadm` to be a building block that can be used by any cluster creation solution. It explicitly does not do things like provision machines or install the base OS, so we would not want to merge those features of sextant into it. What would be great is if you could think about some of the steps in your current install that you could "shell out" to `kubeadm` and stop having to worry about building yourself. And then we can work on making `kubeadm` support your use case in addition to the other turnup automation that we know about (kops, kube-up.sh, kargo, etc).

**Comment by luxas** [comment]
Quite a lot of information is here: https://docs.google.com/document/d/1v4k7eN-eetHbbpTAG7WuioRAMsK_FVGi1yC3VIn4Inw/edit#heading=h.8dh1uxinqwag

**Comment by typhoonzero** [comment]
Thanks for replying. I see `kubeadm` has different goals to `sextant`. Still we are happly to share the project to `kubernetes/contrib` , how could I do that?

**Comment by roberthbailey** [comment]
New projects are not being added to contrib; instead contrib is being broken into separate repositories through the [incubator process](https://github.com/kubernetes/community/blob/master/incubator.md).

**Comment by resouer** [comment]
@typhoonzero I suggest you join this cluster-lifecycle sig-group: https://groups.google.com/forum/#!forum/kubernetes-sig-cluster-lifecycle

Post your idea in the group, take part it's online meeting, show your sextant demo, listen to advices. And then try to get sponsors to promote your project into incubator.

**Comment by wangkuiyi** [comment]
Moved the question to https://groups.google.com/forum/#!topic/kubernetes-sig-cluster-lifecycle/dwfgyFkETNU

**Comment by mikedanese** [comment]
Moved to mailing list.
