### ISSUE TITLE
Container logs rotation

### ISSUE THREAD

**Issue by Crassirostris** [kubernetes/kubernetes#37292]
Recently I was running some load test on the logging subsystem in docker and after a while, fluentd (logging agent) started to write warning in it's logs:

```
2016-11-22 12:31:09 +0000 [warn]: pattern not match: ".go:67] 657735 PUT /api/v1/namespaces/kube-system/pods/av6r 470\\n\",\"stream\":\"stderr\",\"time\":\"2016-11-22T12:23:50.785896269Z\"}"
2016-11-22 12:32:22 +0000 [warn]: pattern not match: "stderr\",\"time\":\"2016-11-22T12:24:39.791492844Z\"}"
2016-11-22 12:33:33 +0000 [warn]: pattern not match: "6Z\"}"
2016-11-22 12:34:44 +0000 [warn]: pattern not match: ":11.205065       5 logs_generator.go:67] 680385 PUT /api/v1/namespaces/default/pods/lpp 460\\n\",\"stream\":\"stderr\",\"time\":\"2016-11-22T12:26:11.205087538Z\"}"
2016-11-22 12:36:04 +0000 [warn]: pattern not match: "/pods/8r5 404\\n\",\"stream\":\"stderr\",\"time\":\"2016-11-22T12:27:57.625483865Z\"}"
2016-11-22 12:37:23 +0000 [warn]: pattern not match: ":12.287898957Z\"}"
```

So it seems like the lines read from docker log files (in json format by default) are somehow damaged. Further investigation showed that container logs are constantly being rotated and the hypothesis is that lines are somehow being damaged during the process of rotation. It would be not that much of an issue if it wasn't the reason why fluentd after some time entered weird "infinite crash loop" state with the following error:

```
error_class="ArgumentError" error="invalid byte sequence in UTF-8"
```

Which may also indicate a partial read of the log file content.

The question is: can this be an issue in the real setup? Because this is very bad situation: from the outside everything seems to work, but in reality no logs are being exported from the node.

@piosz @repeatedly

**Comment by Random-Liu** [comment]
A question: How does fluentd handle copy truncate rotation?

Once the file is truncated, will fluentd detect that and read from the beginning again? Or will it keep reading at the original location until the log file is filled up again?

The later will be problematic.

**Comment by Crassirostris** [comment]
@Random-Liu Thank you very much for the feedback! It really cleared the picture

Fluentd basically has an association inode_num <=> offset. If logrotate removes old file and creates a new one, with the new inode number, fluentd will detect the change and will start to read the new file. If inode number doesn't change, then it's problematic. I will check that

> AFAIK, there is no synchronization between logrotate and docker

OK, that's not great, because as I've mentioned, it can technically turn logging off by offering fluentd an invalid UTF-8 string (I guess logrotate doesn't bother about unicode). That should be addressed

**Comment by Random-Liu** [comment]
> If inode number doesn't change, then it's problematic. I will check that

According to my understanding, copytruncate won't create new file. :)

**Comment by Crassirostris** [comment]
> According to my understanding, copytruncate won't create new file. :)

Damn :)

**Comment by piosz** [comment]
Is there any concrete action on this issue?

**Comment by Crassirostris** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/issues/38495
