### ISSUE TITLE
kubelet will be NotReady after many times restart

### ISSUE THREAD

**Issue by dragon9783** [kubernetes/kubernetes#37348]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): cAdvisor inotify_init: too many open files

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**: hardware
- **OS** (e.g. from /etc/os-release): SUSE 12
- **Kernel** (e.g. `uname -a`):
- **Install tools**: manul
- **Others**:

**What happened**: monit monitor kubelet and flanneld service, and kubelet service depends on flanneld service, i make flanneld not running, so kubelet will restart by monit, after many times restart, i fix flanneld service, but kubelet launch with error 

**What you expected to happen**:
kubelet running success

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:
```
E1123 14:47:21.372435   24479 kubelet.go:2675] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": unable to find data for container /
E1123 14:47:21.372469   24479 kubelet.go:2683] Failed to check if disk space is available on the root partition: failed to get fs info for "root": unable to find data for container /
I1123 14:47:25.806786   24479 kubelet.go:2803] skipping pod synchronization - [Failed to start cAdvisor inotify_init: too many open files]
I1123 14:47:30.806954   24479 kubelet.go:2803] skipping pod synchronization - [Failed to start cAdvisor inotify_init: too many open files]
E1123 14:47:31.397830   24479 kubelet.go:2675] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": unable to find data for container /
E1123 14:47:31.397861   24479 kubelet.go:2683] Failed to check if disk space is available on the root partition: failed to get fs info for "root": unable to find data for container /
I1123 14:47:35.807141   24479 kubelet.go:2803] skipping pod synchronization - [Failed to start cAdvisor inotify_init: too many open files]
I1123 14:47:40.807326   24479 kubelet.go:2803] skipping pod synchronization - [Failed to start cAdvisor inotify_init: too many open files]
E1123 14:47:41.415673   24479 kubelet.go:2675] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": unable to find data for container /
E1123 14:47:41.415704   24479 kubelet.go:2683] Failed to check if disk space is available on the root partition: failed to get fs info for "root": unable to find data for container /
I1123 14:47:45.807487   24479 kubelet.go:2803] skipping pod synchronization - [Failed to start cAdvisor inotify_init: too many open files]
```

**Comment by roberthbailey** [comment]
Hi @dragon9783. I'm sorry that no one was able to help you with this issue. It looks like a node issue, so I'm going to cc @kubernetes/sig-node-bugs but I'm not sure there is enough information in your bug report to help you.

**Comment by yujuhong** [comment]
Closing due to age and insufficient information. Please open a new issue and provide kubernetes version among other information.
