### ISSUE TITLE
kube-dns pod and service still up for a while and suddenly dies

### ISSUE THREAD

**Issue by mootezbessifi** [kubernetes/kubernetes#37352]
Hi all,
Hi all,
i tried to setup a kubernetes dns addon based on ansible repo:
https://github.com/kubernetes/contrib/tree/master/ansible/roles/kubernetes-addons

After running the playbook, i can't find out neither dns pod nor service.!!
After doing some lecture, (https://github.com/kubernetes/contrib/issues/886#issuecomment-216741889) it seems that i need to run the rc.yml and the svc.yml manually.
that's what i did.

Unfortunately, the dns pod and service still up for a while and suddenly terminates.

I tried to checkout some logs before the pod goes down:

#etcd log

 kubectl logs kube-dns-v8-ujfqn --namespace=kube-system -c etcd
2016/11/21 13:05:04 etcd: listening for peers on http://localhost:2380
2016/11/21 13:05:04 etcd: listening for peers on http://localhost:7001
2016/11/21 13:05:04 etcd: listening for client requests on http://127.0.0.1:2379
2016/11/21 13:05:04 etcd: listening for client requests on http://127.0.0.1:4001
2016/11/21 13:05:04 etcdserver: datadir is valid for the 2.0.1 format
2016/11/21 13:05:04 etcdserver: name = default
2016/11/21 13:05:04 etcdserver: data dir = /var/etcd/data
2016/11/21 13:05:04 etcdserver: member dir = /var/etcd/data/member
2016/11/21 13:05:04 etcdserver: heartbeat = 100ms
2016/11/21 13:05:04 etcdserver: election = 1000ms
2016/11/21 13:05:04 etcdserver: snapshot count = 10000
2016/11/21 13:05:04 etcdserver: advertise client URLs = http://127.0.0.1:2379,http://127.0.0.1:4001
2016/11/21 13:05:04 etcdserver: initial advertise peer URLs = http://localhost:2380,http://localhost:7001
2016/11/21 13:05:04 etcdserver: initial cluster = default=http://localhost:2380,default=http://localhost:7001
2016/11/21 13:05:04 etcdserver: start member 6a5871dbdd12c17c in cluster f68652439e3f8f2a
2016/11/21 13:05:04 raft: 6a5871dbdd12c17c became follower at term 0
2016/11/21 13:05:04 raft: newRaft 6a5871dbdd12c17c [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016/11/21 13:05:04 raft: 6a5871dbdd12c17c became follower at term 1
2016/11/21 13:05:04 etcdserver: added local member 6a5871dbdd12c17c [http://localhost:2380 http://localhost:7001] to cluster f68652439e3f8f2a
2016/11/21 13:05:06 raft: 6a5871dbdd12c17c is starting a new election at term 1
2016/11/21 13:05:06 raft: 6a5871dbdd12c17c became candidate at term 2
2016/11/21 13:05:06 raft: 6a5871dbdd12c17c received vote from 6a5871dbdd12c17c at term 2
2016/11/21 13:05:06 raft: 6a5871dbdd12c17c became leader at term 2
2016/11/21 13:05:06 raft.node: 6a5871dbdd12c17c elected leader 6a5871dbdd12c17c at term 2
2016/11/21 13:05:06 etcdserver: published {Name:default ClientURLs:[http://127.0.0.1:2379 http://127.0.0.1:4001]} to cluster f68652439e3f8f2a

#skydns log

kubectl logs kube-dns-v8-ujfqn --namespace=kube-system -c skydns
2016/11/21 13:07:14 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns/config) [10]
2016/11/21 13:07:14 skydns: ready for queries on cluster.local. for tcp://0.0.0.0:53 [rcache 0]
2016/11/21 13:07:14 skydns: ready for queries on cluster.local. for udp://0.0.0.0:53 [rcache 0]

#healthz log

kubectl logs kube-dns-v8-ujfqn --namespace=kube-system -c healthz
2016/11/21 13:05:58 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2016/11/21 13:05:59 Client ip 12.16.64.1:45631 requesting /healthz probe servicing cmd nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2016/11/21 13:06:00 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2016/11/21 13:06:02 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2016/11/21 13:06:04 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2016/11/21 13:06:06 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2016/11/21 13:06:08 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2016/11/21 13:06:08 Client ip 12.16.64.1:45652 requesting /healthz probe servicing cmd nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2016/11/21 13:06:10 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2016/11/21 13:06:12 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2016/11/21 13:06:14 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2016/11/21 13:06:16 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2016/11/21 13:06:18 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2016/11/21 13:06:18 Client ip 12.16.64.1:45673 requesting /healthz probe servicing cmd nslookup kubernetes.default.svc.cluster.local localhost >/dev/null2016/11/21 13:06:20 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2016/11/21 13:06:22 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2016/11/21 13:06:24 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2016/11/21 13:06:26 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2016/11/21 13:06:28 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2016/11/21 13:06:28 Client ip 12.16.64.1:45693 requesting /healthz probe servicing cmd nslookup kubernetes.default.svc.cluster.local localhost >/dev/null

#kube2sky log 

Nov 23 10:09:26 ctc-cicd2 docker-current[25416]: I1123 07:09:26.213227       1 kube2sky.go:529] Using https://10.254.0.1:443 for kubernetes master
Nov 23 10:09:26 ctc-cicd2 docker-current[25416]: I1123 07:09:26.213279       1 kube2sky.go:530] Using kubernetes API <nil>
Nov 23 10:09:26 ctc-cicd2 docker-current[25416]: I1123 07:09:26.214181       1 kube2sky.go:598] Waiting for service: default/kubernetes
Nov 23 10:09:26 ctc-cicd2 docker-current[25416]: 2016/11/23 07:09:26 Worker running nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
Nov 23 10:09:26 ctc-cicd2 docker-current[25416]: I1123 07:09:26.508032       1 kube2sky.go:660] Successfully added DNS record for Kubernetes service.

What was done wrong ??

**Comment by nikhiljindal** [comment]
which cloud provider are you using and what version of kubernetes are you running?

Users are not allowed to create resources in kube-system namespace. Its reserved for system components.
cc @MrHohn who knows addon manager best.

**Comment by mootezbessifi** [comment]
I setup kubernetes on 3 VMs (created by VMWare): one master and two minions.
Moreover, I installed kubernetes-master 1.2.0 and kubernetes-nodes 1.2.4.
I just followed the official kubernetes ansible repo.

**Comment by MrHohn** [comment]
Could you show the output of `kubectl get pods --namespace=kube-system`? Is addon-manager running?

And could you get logs from the addon-manager (by using `docker logs` command on master node)?

Did the `kube-dns` service also be deleted?

**Comment by mootezbessifi** [comment]
hi @MrHohn,
this is what you want:
1. `#kubectl get pods --namespace=kube-system`
     `kube-dns-v11-olq8v           4/4                  Running             0                      1m             ctc-cicd3`

After some minutes, the pod disappear and kubectl get pods ... shows nothing.

2. kube-addons.service is already running.
3. kube-addons.service logs (the next was a portion from the hole log but this portion is repetitive):
   `Nov 23 16:59:30 ctc-cicd1 kube-addons.sh[7198]: INFO: == Kubernetes addon update completed successfully at 2016-11-23T16:59:30+0300 ==
Nov 23 17:09:29 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:09:29 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:09:29 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:09:29 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:09:29 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:09:29 ctc-cicd1 kube-addons.sh[7198]: INFO: == Kubernetes addon update completed successfully at 2016-11-23T17:09:29+0300 ==
Nov 23 17:19:29 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:19:29 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:19:29 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:19:29 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:19:29 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:19:29 ctc-cicd1 kube-addons.sh[7198]: INFO: Stopping Service kube-system/kube-dns
Nov 23 17:19:29 ctc-cicd1 kube-addons.sh[7198]: INFO: Stopping ReplicationController kube-system/kube-dns-v11
Nov 23 17:19:29 ctc-cicd1 kube-addons.sh[7198]: Command "stop" is deprecated, use "delete" instead.
Nov 23 17:19:29 ctc-cicd1 kube-addons.sh[7198]: Command "stop" is deprecated, use "delete" instead.
Nov 23 17:19:29 ctc-cicd1 kube-addons.sh[7198]: service "kube-dns" deleted
Nov 23 17:19:31 ctc-cicd1 kube-addons.sh[7198]: replicationcontroller "kube-dns-v10" deleted
Nov 23 17:19:31 ctc-cicd1 kube-addons.sh[7198]: INFO: == Kubernetes addon update completed successfully at 2016-11-23T17:19:31+0300 ==
Nov 23 17:29:30 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:29:30 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:29:30 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:29:30 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:29:30 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:29:30 ctc-cicd1 kube-addons.sh[7198]: INFO: == Kubernetes addon update completed successfully at 2016-11-23T17:29:30+0300 ==
Nov 23 17:39:29 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:39:29 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:39:29 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:39:29 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:39:29 ctc-cicd1 kube-addons.sh[7198]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release
Nov 23 17:39:29 ctc-cicd1 kube-addons.sh[7198]: INFO: == Kubernetes addon update completed successfully at 2016-11-23T17:39:29+0300 ==`


4. yes, kube-dns was also deleted

**Comment by MrHohn** [comment]
Sorry for the delay.

From the logs, it is obvious that both of kube-dns ReplicationController and Service were deleted by the add-on manager. It is because add-on manager assumes the ownership for resources within `kube-system` and have `kubernetes.io/cluster-service: "true"` label attatched, which means if you create objects that satisfy these conditions, add-on manager will compare them with the configure files under the path it is managing (usually would be '/etc/kubernetes/addons'), and delete what are not there.

Two options to fix this:
- Delete the `kubernetes.io/cluster-service: "true"` label from the YAML files you use to create kube-dns ReplicationController and Service to prevent add-on manager to manage them.
-  Put the YAML files under the path that add-on manager are watching and let it manages to create and maintain them. This path usually would be `/etc/kubernetes/addons'.

**Comment by mootezbessifi** [comment]
@MrHohn thanks for your detailed answer, but unfortunately, when i tried to stop kube-addons.service, copy the rc.yml and svc.yml under /etc/kubernetes/addons and start again /etc/kubernetes/addons, no pods or services where created. but new logs for kube-addons.service appears:


`Nov 28 10:31:47 ctc-cicd1 systemd[1]: Started Kubernetes Addon Object Manager.
 Subject: Unit kube-addons.service has finished start-up
 Defined-By: systemd
 Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
 Unit kube-addons.service has finished starting up.
 The start-up result is done.`

`Nov 28 10:31:47 ctc-cicd1 systemd[1]: Starting Kubernetes Addon Object Manager...
 Subject: Unit kube-addons.service has begun start-up
 Defined-By: systemd
 Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel`

 `Unit kube-addons.service has begun starting up.`

`Nov 28 10:31:47 ctc-cicd1 kube-addons.sh[3789]: == Kubernetes addon manager started at 2016-11-28T10:31:47+0300 with ADDON_CHECK_INTERVAL_SEC=600 ==`

`Nov 28 10:31:47 ctc-cicd1 kube-addons.sh[3789]: /usr/libexec/kubernetes/kube-addons.sh: line 182: /var/cache/kubernetes-install/kube_env.yaml: No such file or directory`

`Nov 28 10:31:47 ctc-cicd1 kube-addons.sh[3789]: Error from server: error when creating "STDIN": namespaces "kube-system" already exists`

`Nov 28 10:31:47 ctc-cicd1 kube-addons.sh[3789]: == Failed to start /etc/kubernetes/addons/namespace.yaml in namespace  at 2016-11-28T10:31:47+0300. 99 tries remaining. ==`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: == default service account in the kube-system namespace has token default-token-39gpt ==`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: find: ‘/etc/kubernetes/admission-controls’: No such file or directory`
`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: Error from server: error when creating "STDIN": secrets "token-system-kubelet-ctc-cicd2" already exists`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: Error from server: error when creating "STDIN": secrets "token-system-scheduler-ctc-cicd1" already exists`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: Error from server: error when creating "STDIN": secrets "token-system-controller-manager-ctc-cicd1" already exists`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: == Failed to start Secret-for-token-for-user-system:scheduler-ctc-cicd1 in namespace kube-system at 2016-11-28T10:31:48+0300. 99 tries remaining. ==`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: == Failed to start Secret-for-token-for-user-system:kubelet-ctc-cicd2 in namespace kube-system at 2016-11-28T10:31:48+0300. 99 tries remaining. ==`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: == Failed to start Secret-for-token-for-user-system:controller_manager-ctc-cicd1 in namespace kube-system at 2016-11-28T10:31:48+0300. 99 tries remaining. ==`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: Error from server: error when creating "STDIN": secrets "token-system-proxy-ctc-cicd3" already exists`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: == Failed to start Secret-for-token-for-user-system:proxy-ctc-cicd3 in namespace kube-system at 2016-11-28T10:31:48+0300. 99 tries remaining. ==`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: Error from server: error when creating "STDIN": secrets "token-system-kubelet-ctc-cicd3" already exists`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: Error from server: error when creating "STDIN": secrets "token-system-kubectl-ctc-cicd1" already exists`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: == Failed to start Secret-for-token-for-user-system:kubelet-ctc-cicd3 in namespace kube-system at 2016-11-28T10:31:48+0300. 99 tries remaining. ==`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: == Failed to start Secret-for-token-for-user-system:kubectl-ctc-cicd1 in namespace kube-system at 2016-11-28T10:31:48+0300. 99 tries remaining. ==`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: Error from server: error when creating "STDIN": secrets "token-system-logging" already exists`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: == Failed to start Secret-for-token-for-user-system:logging in namespace kube-system at 2016-11-28T10:31:48+0300. 99 tries remaining. ==`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: Error from server: error when creating "STDIN": secrets "token-system-dns" already exists`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: Error from server: error when creating "STDIN": secrets "token-system-proxy-ctc-cicd2" already exists`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: Error from server: error when creating "STDIN": secrets "token-system-monitoring" already exists`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: == Failed to start Secret-for-token-for-user-system:dns in namespace kube-system at 2016-11-28T10:31:48+0300. 99 tries remaining. ==`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: == Failed to start Secret-for-token-for-user-system:monitoring in namespace kube-system at 2016-11-28T10:31:48+0300. 99 tries remaining. ==`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: == Failed to start Secret-for-token-for-user-system:proxy-ctc-cicd2 in namespace kube-system at 2016-11-28T10:31:48+0300. 99 tries remaining. ==`

`Nov 28 10:31:48 ctc-cicd1 kube-addons.sh[3789]: INFO: == Kubernetes addon update completed successfully at 2016-11-28T10:31:48+0300 ==`

`Nov 28 10:31:58 ctc-cicd1 kube-addons.sh[3789]: Error from server: error when creating "STDIN": namespaces "kube-system" already exists`

`Nov 28 10:31:58 ctc-cicd1 kube-addons.sh[3789]: == Failed to start /etc/kubernetes/addons/namespace.yaml in namespace  at 2016-11-28T10:31:58+0300. 98 tries remaining. ==`

`Nov 28 10:31:59 ctc-cicd1 kube-addons.sh[3789]: Error from server: error when creating "STDIN": secrets "token-system-scheduler-ctc-cicd1" already exists`

`Nov 28 10:31:59 ctc-cicd1 kube-addons.sh[3789]: Error from server: error when creating "STDIN": secrets "token-system-kubelet-ctc-cicd2" already exists`

`Nov 28 10:31:59 ctc-cicd1 kube-addons.sh[3789]: == Failed to start Secret-for-token-for-user-system:scheduler-ctc-cicd1 in namespace kube-system at 2016-11-28T10:31:59+0300. 98 tries remaining. ==`

`Nov 28 10:31:59 ctc-cicd1 kube-addons.sh[3789]: == Failed to start Secret-for-token-for-user-system:kubelet-ctc-cicd2 in namespace kube-system at 2016-11-28T10:31:59+0300. 98 tries remaining. ==`

`Nov 28 10:31:59 ctc-cicd1 kube-addons.sh[3789]: Error from server: error when creating "STDIN": secrets "token-system-proxy-ctc-cicd3" already exists`

**Comment by mootezbessifi** [comment]
@MrHohn the above logs was generated because of existence of old generated secrets and namespace `kube-system`.
i tried to delete all of them and rerun  `kube-addons.service`.
the log does not mention errors as above and the kube-ssytem ns was created successfully, BUT no dns-kube pod or service exists.
#Log of kube-addons.service (the hole log):

`Unit kube-addons.service has begun starting up.`

`Nov 28 11:09:23 ctc-cicd1 kube-addons.sh[21460]: == Kubernetes addon manager started at 2016-11-28T11:09:23+0300 with ADDON_CHECK_INTERVAL_SEC=600 ==`

`Nov 28 11:09:23 ctc-cicd1 kube-addons.sh[21460]: /usr/libexec/kubernetes/kube-addons.sh: line 182: /var/cache/kubernetes-install/kube_env.yaml: No such file or directory`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: namespace "kube-system" created`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: == Successfully started /etc/kubernetes/addons/namespace.yaml in namespace  at 2016-11-28T11:09:24+0300`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: == default service account in the kube-system namespace has token default-token-f8oaa ==`
`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: find: ‘/etc/kubernetes/admission-controls’: No such file or directory`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: Flag --api-version has been deprecated, flag is no longer respected and will be deleted in the next release`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: secret "token-system-kubectl-ctc-cicd1" created`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: == Successfully started Secret-for-token-for-user-system:kubectl-ctc-cicd1 in namespace kube-system at 2016-11-28T11:09:24+0300`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: secret "token-system-kubelet-ctc-cicd2" created`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: secret "token-system-controller-manager-ctc-cicd1" created`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: secret "token-system-scheduler-ctc-cicd1" created
Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: secret "token-system-proxy-ctc-cicd3" created
Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: secret "token-system-proxy-ctc-cicd2" created
Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: == Successfully started Secret-for-token-for-user-system:proxy-ctc-cicd2 in namespace kube-system at 2016-11-28T11:09:24+0300`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: == Successfully started Secret-for-token-for-user-system:scheduler-ctc-cicd1 in namespace kube-system at 2016-11-28T11:09:24+0300`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: == Successfully started Secret-for-token-for-user-system:proxy-ctc-cicd3 in namespace kube-system at 2016-11-28T11:09:24+0300`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: == Successfully started Secret-for-token-for-user-system:controller_manager-ctc-cicd1 in namespace kube-system at 2016-11-28T11:09:24+0300`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: == Successfully started Secret-for-token-for-user-system:kubelet-ctc-cicd2 in namespace kube-system at 2016-11-28T11:09:24+0300`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: secret "token-system-kubelet-ctc-cicd3" created
Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: secret "token-system-monitoring" created
Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: == Successfully started Secret-for-token-for-user-system:monitoring in namespace kube-system at 2016-11-28T11:09:24+0300`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: == Successfully started Secret-for-token-for-user-system:kubelet-ctc-cicd3 in namespace kube-system at 2016-11-28T11:09:24+0300`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: secret "token-system-dns" created
Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: == Successfully started Secret-for-token-for-user-system:dns in namespace kube-system at 2016-11-28T11:09:24+0300`

`Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: secret "token-system-logging" created
Nov 28 11:09:24 ctc-cicd1 kube-addons.sh[21460]: == Successfully started Secret-for-token-for-user-system:logging in namespace kube-system at 2016-11-28T11:09:24+0300`

`Nov 28 11:09:25 ctc-cicd1 kube-addons.sh[21460]: INFO: == Kubernetes addon update completed successfully at 2016-11-28T11:09:25+0300 ==`


I want kube-addons.service to manage my addons, that's why i choose the second fix.

**Comment by MrHohn** [comment]
Thanks for the logs. It is weird that the add-on manager seems to totally omit kube-dns configuration files.

Do the configuration files you put in has suffix `.yaml`? I took a look at this add-on manager, found this file type is hardcoded [in the script](https://github.com/kubernetes/contrib/blob/master/ansible/roles/kubernetes-addons/files/common/kube-addon-update.sh#L152).

Or are the kube-dns yaml files on the same machine that the add-on manager script runs on?

**Comment by mootezbessifi** [comment]
Yes, my addon manager as well as rc and svc yaml files are in the same machine, but files have extentions "yml"  not  " yaml". Do you think this is what causes the problem?

**Comment by mootezbessifi** [comment]
@MrHohn

**Comment by MrHohn** [comment]
In this case, yes I think that might be the problem. Could you try if you have time? Sorry for not noticing it at the first place.

**Comment by mootezbessifi** [comment]
Actually I am out of the office. Tomorrow I will give you a feedback

**Comment by mootezbessifi** [comment]
thank you @MrHohn, i checked out the config files and it turned out that all of them have .yaml extension not yml. i was wrong. what is next !!??

**Comment by mootezbessifi** [comment]
@MrHohn any feedback plz ?

**Comment by MrHohn** [comment]
Sorry for the delay. But sadly I don't have a theory yet.

Could you please show me the content in the YAML files you used for DNS? And could you also try put another addon --- like the dashboard --- and see if the Add-on Manager script will create it or not?

Because we do not see any error in logs that related to neither parsing yaml file nor resource creation, it seems really like the Add-on Manager was not watching the same place as the files. Was the `/etc/kubernetes/addons/namespace.yaml` also there?

**Comment by mootezbessifi** [comment]
@MrHohn thank you very much for your support.
The next are files content with their path in my master machine:

`# vi /etc/kubernetes/addons/namespace.yaml`

[namespace.yaml](https://github.com/kubernetes/contrib/blob/master/ansible/roles/kubernetes-addons/files/common/namespace.yaml)

`# vi /etc/kubernetes/addons/skydns-rc.yaml`
`# vi /etc/kubernetes/addons/skydns-svc.yaml`
[skydns-rc.txt](https://github.com/kubernetes/kubernetes/files/623820/skydns-rc.txt)
[skydns-svc.txt](https://github.com/kubernetes/kubernetes/files/623821/skydns-svc.txt)

`# vi  /usr/libexec/kubernetes/kube-addons.sh`
`# vi  /usr/libexec/kubernetes/kube-addon-update.sh`

[kube-addons.txt](https://github.com/kubernetes/kubernetes/files/623837/kube-addons.txt)
[kube-addon-update.txt](https://github.com/kubernetes/kubernetes/files/623838/kube-addon-update.txt)

`# vi /etc/systemd/system/kube-addons.service`

`Description=Kubernetes Addon Object Manager`
`Documentation=https://github.com/kubernetes/kubernetes`

`[Service]`
`Environment=HOME=/root`
`Environment="TOKEN_DIR=/etc/kubernetes/tokens"`
`Environment="CA_CERT=/etc/kubernetes/certs/ca.crt"`
`Environment="KUBECTL_BIN=/usr/bin/kubectl"`
`Environment="KUBERNETES_MASTER_NAME=ctc-cicd1"`
`Environment="TRUSTY_MASTER=true"`
`ExecStart=/usr/libexec/kubernetes/kube-addons.sh`

`[Install]`
`WantedBy=multi-user.target`


if you need some other info, just let me know

**Comment by MrHohn** [comment]
Both the files and paths look correct. One more trivial suggestion is try to put `skydns-rc.yaml` and `skydnssvc.yaml` in to a sub-folder, like `/etc/kubernetes/addons/dns/`. But I don't think it will solve the problem you have.

Since the Kubernetes version you are using is relatively old --- including kube-dns and Add-on Manager, I might need more time to dig in later, and probably do a repro. Before that, you could try create the dns service and RC with option 1 and manage it on your own temporarily, given that option 2 is not working properly.

And also suggest to file an issue directly on kubernetes/contrib and ping the [direct owners](https://github.com/kubernetes/contrib/blob/master/ansible/OWNERS). They might have better ideas about the known issues in the ansible repo.

**Comment by mootezbessifi** [comment]
Hi @MrHohn,
putting rc.yaml and svc.yaml under  /etc/kubernetes/addons/dns/ was not a solution because they were both there before you propose to me the two fixes.
I don't think also that the problem comes from kubernetes version because the official ansible repo was published with 1.2.X version.
thank you very much for your great effort.
@eparis @ingvagabund  your support please.This may be a bug in ansible repo

**Comment by mootezbessifi** [comment]
@MrHohn, sorry for the delay, i had to make some progression in my work so i kept running kube-dns manually. Now i want to make it with addons-manager as we discussed.
I find out from the log when running kube-addons.sh and kube-addon-update.sh the two next errors:

-  kube-addons.sh[21460]: /usr/libexec/kubernetes/kube-addons.sh: line 182: /var/cache/kubernetes-install/kube_env.yaml: No such file or directory.
- kube-addons.sh[21460]: find: ‘/etc/kubernetes/admission-controls’: No such file or directory.

As you can see, there is no feedback nether from @eparis  nor @ingvagabund . 
plz,can you, @MrHohn,  help me debugging this issue ??

**Comment by mootezbessifi** [comment]
Finally i found out what was causing my issue.
In fact, i was working on a cluster based on CentOS 7, where python2.7 is installed.
After debugging kube-addon-update.sh, Exception from get-addon-paths-from-disk() function was happening due to [import yaml module]  in purpose of parsing addon yml files to get kind tag from there. It turned out that yaml module not found so the parsing fails.(https://github.com/kubernetes/contrib/blob/master/ansible/roles/kubernetes-addons/files/common/kube-addon-update.sh#L152).
I think that we need to add (installation for yaml module) to the ansible repo in case of CentOS7 because it is not installed by default.
Util links:
http://pyyaml.org/wiki/PyYAML
http://pyyaml.org/wiki/LibYAML

**Comment by MrHohn** [comment]
Glad to know your issue is resolved! And sorry about my ignorance. I tried to reproduce but failed. I should have asked you about the platform information. Wondering why there was no obvious error message captured. Anyhow, the newest [addon manager](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/addon-manager) does not rely on python anymore.

Sure, we will improve the ansible repo and prevent this kind of issues happen again. Sorry for wasting your time :(
