### ISSUE TITLE
Value could be empty in sysctls

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#37372]
As pointed at [here](https://github.com/kubernetes-incubator/cri-o/pull/206#issuecomment-262424777) and [documentation](http://kubernetes.io/docs/admin/sysctls/#setting-sysctls-for-a-pod), it seems both key and value should not be empty in sysctls annotations.

But at [SysctlsFromPodAnnotation](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/helpers.go#L602), the key of sysctls is checked, but it omited the check of value (which implies the possible empty value). Is this intended or just a bug? If it is intended, what's the use cases of empty value?

cc/ @vishh @sttts @runcom

**Comment by sttts** [comment]
A value can be empty. There is no format implied by the kernel.

**Comment by sttts** [comment]
@feiskyer Where do you read in the Docs that empty values are not allowed?

**Comment by feiskyer** [comment]
@sttts Is there any example of empty value?

**Comment by sttts** [comment]
Example of the syntax?

**Comment by sttts** [comment]
Compare http://unix.stackexchange.com/questions/268210/sysctl-malformed-setting-net-ipv4-ip-local-reserved-ports.

Also e.g. kernel.hostname. The kernel happily accepts an empty string.

**Comment by feiskyer** [comment]
@sttts Cool, thanks. It is a good example of empty value.
