### ISSUE TITLE
Error when running kubectl apply

### ISSUE THREAD

**Issue by Draiken** [kubernetes/kubernetes#37371]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): `kubectl apply`, `kubectl apply label:kind/bug` and `apply error label:kind/bug`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Docker container
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- **Kernel** (e.g. `uname -a`): Linux 37638c28ef33 4.8.4-1-ARCH #1 SMP PREEMPT Sat Oct 22 18:26:57 CEST 2016 x86_64 GNU/Linux (apparently uname -a shows the host system on containers?)
- **Install tools**: gcloud
- **Others**: Docker container running the deployment script on our CI (Codeship)

**What happened**: Our deploy script reads our yaml files and feeds them to `kubectl apply -f`. Today we didn't have a regular error like "this property can't be updated", it gave us a server error apparently applying a bad patch to the kubernetes resource.
Here is the stderr output: https://gist.github.com/Draiken/e189868555a53d7c0c5254c7eb04a4f8

**What you expected to happen**: kubectl apply either refuse to send the patch if we're doing some impossible update or successfully update the deployment.

**How to reproduce it** (as minimally and precisely as possible): Unfortunately, I wasn't able to reproduce it. After the error I took the same yaml file used when the error happened and kubectl apply worked without errors.
Here is the resource on kubernetes: https://gist.github.com/55145dc42d1e06ee625306247040fba3
Here is the resource we applied: https://gist.github.com/25932503e3b6d0dc8a810f8fb3682411

**Comment by AdoHe** [comment]
@ymqytw ptal.

**Comment by ymqytw** [comment]
> `"volumeMounts":[{"$patch":"delete","name":"newrelic-config"}]}]`

@Draiken From the error message you provide, it seems the patch causing server error is generated by a `kubectl` with version `1.4.3` or earlier. Because the patch is still using `name` as `mergeKey` for `VolumeMount `. We changed the `mergekey` of `VolumeMount` to `mountPath ` since `1.4.4`, see #35208.

If you are using a `1.4.5 kubectl` against a `1.4.5 APIServer`, this should not happen.

**Comment by Draiken** [comment]
The deployment container uses gcloud to update kubectl, so it should be on
the same version. Either way I'll switch to downloading the kubectl binary.

Thanks for looking into it.
