### ISSUE TITLE
Need to run `make` via sudo 

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/kubernetes#37378]
This is a follow up to #36655 

Trying to build master, the go-bindata issue is fixed in a pending pr ( #36964  ). But It looks like one need to run via `sudo`.

```
$ make
hack/make-rules/helpers/cache_go_dirs.sh: line 65: .make/all_go_dirs.mk: Permission denied
rm: .make/all_go_dirs.mk: Permission denied
find: illegal option -- m
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
^Cmake: *** [generated_files] Interrupt: 2

sebimac:kubernetes (bindata)$ sudo make
+++ [1123 14:38:45] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
```

**Comment by ixdy** [comment]
Did you previously run `sudo make`? I'm pretty sure the `.make/` directory is created as part of the build, and so would only be unreadable if you ran `make` as a different user first.

(At least in my workspace, everything under `.make/` is owned by me.)

**Comment by ixdy** [comment]
@thockin should we be deleting the `.make/` dir on `make clean`?

**Comment by thockin** [comment]
.make is cleaned up by a `make clean` - if you ever ran `sudo make` there
might be some root-owned debris.  clean it once with sudo.

**Comment by sebgoa** [comment]
yeah, so it was debris. Blame is on me sorry for the noise.

Your PR #36964 works fine.
