### ISSUE TITLE
Remove IP of ingress controller from ingress object status when ingress controller ceases to exist

### ISSUE THREAD

**Issue by jcrawfordor** [kubernetes/kubernetes#37386]
**Kubernetes version** (use `kubectl version`): 1.3.0

**What happened**:

When using the Google nginx-ingress-controller image to provide a reverse-proxy to various services, ingress controllers sometimes go down for various reasons and may be replaced by new ingress controllers (e.g. when a random node failure occurs) or their workload may just be left to existing ingress controllers (e.g. as a result of a replication controller being scaled down). When this happens, the new ingress controller's node IP, if any, is consistently added to the IPs reported in the ingress map statuses. However, the IP of the old ingress controller is not removed.

This means that people querying the API for the IP addresses of ingress controllers, which is more or less required to use ingress controllers in a durable/scalable fashion without a cloud load balancer, will get a list of IPs that includes non-working ingress controllers. This has to be fixed by manual intervention, destroying and recreating the ingress object.

**What you expected to happen**:

When an ingress controller fails health check or otherwise ceases to exist, this should be detected and the ingress controller's IP should be removed from the IP addresses reported in ingress map status. This will allow an automatic process to stop directing traffic to an ingress controller that is no longer working (perhaps by updating the configuration of an upstream load balancer).

**How to reproduce it** (as minimally and precisely as possible):

1. Working on a Kubernetes cluster with multiple nodes, create a default backend and an nginx ingress controller under a replication controller.
2. Create an ingress map and then check it's status. Note that when retrieving the ingress map, it now lists the IP of the ingress controller as part of its status.
3. Kill the ingress controller pod. Wait a moment and the replication controller recovers by starting a new pod, which has most likely been scheduled to a different node.
4. Retrieve the ingress map created earlier. Note that it now lists _two_ IP addresses in the status: the IP of the old, now nonexistent ingress controller's node, and the IP address of the new ingress controller's node.

This behavior appears to be consistent across various cloud providers and underlying operating systems.

**Comment by gladiatr72** [comment]
@jcrawfordor hey there.  Just saw your PR and thought I'd mention: running through your steps under 1.4.6 doesn't display this problem.

**Comment by aledbf** [comment]
This can be closed. The nginx ingress controller removes the status field from the ingress rules if there's only one replica running when is replaced or ceases to exist.
