### ISSUE TITLE
Manual upgrade testing on GCE is leaking resources

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#37385]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): upgrade test leak

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.5 beta

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**: kube-up.sh

**What happened**: While doing manual upgrade testing, found that I couldn't start a new cluster as the existing firewall rules and external master ip address reservation where preventing kube-up from succeeding after running kube-down

**What you expected to happen**: kube-down to clean up all cluster related resources

**How to reproduce it** (as minimally and precisely as possible):

```
$ git co upstream/release-1.4
$ make clean; make release
$ ./cluster/kube-up.sh
$ git co upstream/release-1.5
$ ./cluster/gce/upgrade.sh -M v1.5.0-beta.1
$ git co upstream/release-1.4
$ ./cluster/kube-down.sh
```

**Comment by roberthbailey** [comment]
I tried this on a different GCP project and it didn't reproduce. I'm going to see if there's anything strange about my project.

**Comment by dims** [comment]
Ack @roberthbailey marking this as non-release-blocker

**Comment by roberthbailey** [comment]
I think I found the problem. `if [[ "${REMAINING_MASTER_COUNT}" == "0" ]]` (from https://github.com/kubernetes/kubernetes/blob/95f8fc0ec325000060a6c469ea79a6da4d766415/cluster/gce/util.sh#L1228) evaluates to false in bash on my mac. Changing it to `if [[ "${REMAINING_MASTER_COUNT}" -eq 0 ]]` fixes my issue. I'll send out a PR.

**Comment by roberthbailey** [comment]
@jszczepkowski
