### ISSUE TITLE
Move kubernetes-cassandra.jar to external repository

### ISSUE THREAD

**Issue by mstump** [kubernetes/kubernetes#37408]
I'm updating the [kubernetes-cassandra.jar](https://github.com/kubernetes/kubernetes/blob/master/examples/storage/cassandra/image/files/kubernetes-cassandra.jar) in pull request #37145 as part of fixing #34422. I'm not sure if keeping this code and the resulting binary in the Kubernetes repo makes sense. I'd like to move the code out to it's own repo and push the binaries to another repository such as maven central or a google equivalent.

**Comment by kargakis** [comment]
Please move in the kubernetes/examples repo, if this is still an issue.
