### ISSUE TITLE
vSphere CloudProvider doesn't initiate

### ISSUE THREAD

**Issue by abrarshivani** [kubernetes/kubernetes#37402]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.1.427+19e9f7e400fd46-dirty", GitCommit:"19e9f7e400fd46d5492c869f4371ddec6f32b17e", GitTreeState:"dirty", BuildDate:"2016-11-16T00:14:27Z", GoVersion:"go1.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.1.427+19e9f7e400fd46-dirty", GitCommit:"19e9f7e400fd46d5492c869f4371ddec6f32b17e", GitTreeState:"dirty", BuildDate:"2016-11-16T00:14:27Z", GoVersion:"go1.6", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: vSphere
- **OS** (e.g. from /etc/os-release): Ubuntu
- **Kernel** (e.g. `uname -a`): 4.2.0-27-generic
- **Install tools**:
- **Others**:

**What happened**:
Kubelet fail to start. 

**How to reproduce it** (as minimally and precisely as possible):
Move VMs running Kubernetes outside vSphere Cluster. Restart kubernetes services

**Anything else do we need to know**:
Kubelet Logs
```
panic: reflect.Set: value of type mo.ComputeResource is not assignable to type mo.ClusterComputeResource

goroutine 1 [running]:
panic(0x287fe00, 0xc82025a240)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
reflect.Value.assignTo(0x35a1680, 0xc8205725a0, 0x99, 0x3831860, 0xb, 0x357e8c0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:2164 +0x3be
reflect.Value.Set(0x357e8c0, 0xc8205af180, 0x199, 0x35a1680, 0xc8205725a0, 0x99)
        /usr/local/go/src/reflect/value.go:1334 +0x95
k8s.io/kubernetes/vendor/github.com/vmware/govmomi/vim25/mo.LoadRetrievePropertiesResponse(0xc8206c6700, 0x32dd7a0, 0xc8205af180, 0x0, 0x0)
        /mnt/hgfs/shivania/Abrar/workdir/code/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/vmware/govmomi/vim25/mo/retrieve.go:128 +0xe21
k8s.io/kubernetes/vendor/github.com/vmware/govmomi/property.(*Collector).Retrieve(0xc820867058, 0x7f8af1761ab0, 0xc82004b300, 0xc8206d2a20, 0x1, 0x1, 0xc8202c36
```

**Comment by kerneltime** [comment]
This is the same issue as https://github.com/kubernetes/kubernetes/issues/36295 the init code needs to be https://github.com/kubernetes/kubernetes/issues/36295

**Comment by kerneltime** [comment]
#38423 should address this
