### ISSUE TITLE
Enable PDB tests on GKE

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#37410]
It [currently skips the tests ](https://github.com/kubernetes/kubernetes/blob/e3091d830418309ae0496dab08130d226e25c588/test/e2e/disruption.go#L47) on GKE but it has moved to beta since the time that was written.

Prior to this change:
* The group "policy/v1beta1" would need to be enabled in GKE explcitly similar to https://github.com/kubernetes/kubernetes/issues/37393.

**Comment by davidopp** [comment]
@mwielgus can you take care of this?

**Comment by dims** [comment]
@davidopp marking this is non-release-blocker. is that label correct?

**Comment by davidopp** [comment]
IIUC #37489 will fix this, @mwielgus can you confirm?

**Comment by foxish** [comment]
Closing because the [tests are now running](https://k8s-testgrid.appspot.com/google-gke).
