### ISSUE TITLE
kubelet 1.3.9 inserting duplicate iptables rules on centos6 (iptables v1.4.7)

### ISSUE THREAD

**Issue by huggsboson** [kubernetes/kubernetes#37416]
**Kubernetes version** (use `kubectl version`):
Upgrading from 1.2.0 (working) to 1.3.9 (broken)

**Environment**:
- **Cloud provider or hardware configuration**: Bare metal Dell R420's
- **OS** (e.g. from /etc/os-release): CentOS 6 with a 3.10 kernel.
- **Kernel** (e.g. `uname -a`):  3.10.0-327.18.2.el7.x86_64
- **Install tools**: 
- **Others**:
iptables --version
iptables v1.4.7

**What happened**:
We upgraded from 1.2.0 to 1.3.9 and noticed that our service load balancer (based on haproxy) cpu utilization started going through the roof over the course of 3 days, mostly system time.  It is now impacting all nodes with the 1.3.9 version of kubelet installed.

We've tracked down a likely culprit which is this version of kube seems to be continuously appending iptables rules at a rate of about 4 a second.  Here's a dump from iptables-save:
$ sudo iptables-save | wc -l
67951

These tend to be the form of the duplicated rules:
```
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
<repeated>
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
<repeated>
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
<repeated>
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE
<repeated>
```

The commits and issues I've found related to this are:
https://github.com/kubernetes/kubernetes/issues/2623
https://github.com/kubernetes/kubernetes/pull/30486

**What you expected to happen**:
It to stay at < 30% cpu utilization and a reasonable number of iptables rules.

**How to reproduce it** (as minimally and precisely as possible):
Setup centos6 with our kernel, run 1.3.9 

**Anything else do we need to know**:

Here is the iptables output soon after starting the system.  You can see it is already starting to accumulate rules:
```
$ sudo iptables-save
# Generated by iptables-save v1.4.7 on Wed Nov 23 16:35:34 2016
*filter
:INPUT ACCEPT [2753:1417441]
:FORWARD ACCEPT [107:7101]
:OUTPUT ACCEPT [1993:8997998]
:DOCKER - [0:0]
:DOCKER-ISOLATION - [0:0]
:KUBE-FIREWALL - [0:0]
-A INPUT -j KUBE-FIREWALL
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A OUTPUT -j KUBE-FIREWALL
-A DOCKER-ISOLATION -j RETURN
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
COMMIT
# Completed on Wed Nov 23 16:35:34 2016
# Generated by iptables-save v1.4.7 on Wed Nov 23 16:35:34 2016
*nat
:PREROUTING ACCEPT [462:40180]
:INPUT ACCEPT [136:16306]
:OUTPUT ACCEPT [1007:65897]
:POSTROUTING ACCEPT [1109:72017]
:DOCKER - [0:0]
:KUBE-MARK-DROP - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-POSTROUTING - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A PREROUTING ! -s 127.0.0.1/32 -p tcp -m tcp --dport 10250 -m addrtype --dst-type LOCAL -j REDIRECT --to-ports 11250
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A POSTROUTING -s 10.20.19.128/25 ! -o docker0 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE
COMMIT
# Completed on Wed Nov 23 16:35:34 2016
```

@thockin @freehan

**Comment by freehan** [comment]
Looks like our EnsureRule iptables util does not work properly in this case.

**Comment by huggsboson** [comment]
Note: we aren't running kube-proxy at the moment either.  But would like to in the near future.

**Comment by freehan** [comment]
chatted with @huggsboson offline

flip ` --make-iptables-util-chains=false` to stop the sync for now. 



Maintain util rules thru a different process. 
```
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
-A INPUT -j KUBE-FIREWALL
-A OUTPUT -j KUBE-FIREWALL

-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
```

**Comment by thockin** [comment]
I seem to recall CentOS 6 has an ancient version of iptables which was
broken 6 ways to Sunday.  Specifically, 1.4.7 (which you have) is less than
`MinCheckVersion` (1.4.11), which means we fall back on a known sketchy
function: `checkRuleWithoutCheck`.   That is the function to debug.  If you
run kubelet with `--v=5`, you might see lines like "DBG: fields is not a
superset of args" which would have really useful debug info.

@dcbw - another place that could benefit from better parsing of iptables
arguments - if it is really robust enough, order-independent, etc.

The looming question is how long we can support really ancient OSes - it
was released 5.5 years ago, and only has LTS for 6 more months, as far as I
know...

**Comment by huggsboson** [comment]
Agreed on archaic.  We're gonna try @freehan's work around and if it works out keep this work around in place until we can move to centos7.

**Comment by thockin** [comment]
If you give us debug info we might be able to fix up yet another case of
"broken on centos 6" :)

**Comment by huggsboson** [comment]
Turned on --v=5 for a few minutes.  A lot of info was being written.  Here is a sampling:

```
I1126 19:00:21.912513   35221 iptables.go:436] DBG: fields is not a superset of args: fields=[-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000]  args=[-j MARK --set-xmark 0x00004000/0x00004000]
I1126 19:00:21.985393   35221 iptables.go:380] running iptables -A [KUBE-MARK-MASQ -t nat -j MARK --set-xmark 0x00004000/0x00004000]
```

```
I1126 18:59:17.975232   35221 iptables.go:436] DBG: fields is not a superset of args: fields=[-A KUBE-POSTROUTING -m comment --comment kubernetes service traffic requiring SNAT -m mark --mark 0x4000/0x4000 -j MASQUERADE]  args=[-m comment --comment kubernetes service traffic requiring SNAT -m mark --mark 0x00004000/0x00004000 -j MASQUERADE]
I1126 18:59:17.975251   35221 iptables.go:380] running iptables -A [KUBE-POSTROUTING -t nat -m comment --comment kubernetes service traffic requiring SNAT -m mark --mark 0x00004000/0x00004000 -j MASQUERADE]
```

```
I1126 19:00:19.695553   35221 iptables.go:436] DBG: fields is not a superset of args: fields=[-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000]  args=[-j MARK --set-xmark 0x00008000/0x00008000]
I1126 19:00:19.796669   35221 iptables.go:380] running iptables -A [KUBE-MARK-DROP -t nat -j MARK --set-xmark 0x00008000/0x00008000]
```

```
I1126 19:00:20.867283   35221 iptables.go:436] DBG: fields is not a superset of args: fields=[-A KUBE-FIREWALL -m comment --comment kubernetes firewall for dropping marked packets -m mark --mark 0x8000/0x8000 -j DROP]  args=[-m comment --comment kubernetes firewall for dropping marked packets -m mark --mark 0x00008000/0x00008000 -j DROP]
I1126 19:00:20.867307   35221 iptables.go:380] running iptables -A [KUBE-FIREWALL -t filter -m comment --comment kubernetes firewall for dropping marked packets -m mark --mark 0x00008000/0x00008000 -j DROP]
```

**Comment by thockin** [comment]
> I1126 18:59:17.975232   35221 iptables.go:436] DBG: fields is not a superset of args: fields=[-A KUBE-POSTROUTING -m comment --comment kubernetes service traffic requiring SNAT -m mark --mark 0x4000/0x4000 -j MASQUERADE]  args=[-m comment --comment kubernetes service traffic requiring SNAT -m mark --mark 0x00004000/0x00004000 -j MASQUERADE]

Awesome.  Let me tease that apart:

```
fields=[
    -A KUBE-POSTROUTING
    -m comment --comment kubernetes service traffic requiring SNAT
    -m mark --mark 0x4000/0x4000
    -j MASQUERADE
]
args=[
    -m comment --comment kubernetes service traffic requiring SNAT
    -m mark --mark 0x00004000/0x00004000
    -j MASQUERADE
]
```

This is doing a dumb string superset test.  "0x4000" != "0x00004000".
Quick hack would be to `s/^0x0*/0x0` on every string arg, or
something.  Better would be to actually parse the iptables args into
into structs and compare by that.  @dcbw, I know I poked a lot of
holes in your other PR, but it might be useful here, too :)

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/pull/37594
