### ISSUE TITLE
Can not receive Contributor License Agreement 

### ISSUE THREAD

**Issue by guangxuli** [kubernetes/kubernetes#37419]
this PR is releated to CNCF/CLA:

Today when I click the "review&sign" button in my email sent by Linux Foundation some days ago. 
the result:  `Sorry, that page doesn't exist!` from **hello sign**.
In PR:  https://github.com/kubernetes/kubernetes/pull/33757 , you can see that  `cla/linuxfoundation — guangxuli needs CLA` . When i click the `detail` link, it response:
**A Contributor License Agreement has been sent to your email address. This must be signed electronically to complete the contributor signup process.**
the question is i have not receive any email from that moment sent by CNCF. I want to know what should i do if i want to sign the CNCF/CLA.

**Comment by tao12345666333** [comment]
Same issue. What can I do? Thanks.
