### ISSUE TITLE
kubeadm not creating /etc/cni/net.d .. pods will fail to load.

### ISSUE THREAD

**Issue by adiri** [kubernetes/kubernetes#37426]
I tested kubeadm on CentOS 7, did exactly what the document stated and everything work as expected.

when I created a pod I had the following error:

```
  1m		1m		4	{kubelet server.name}			Warning		FailedSync	Error syncing pod, skipping: failed to "SetupNetwork" for "appname-a94fb6130669dde66c7ebe8cd697c498463fa721-5rg6i_default" with SetupNetworkError: "Failed to setup network for pod \"appname-a94fb6130669dde66c7ebe8cd697c498463fa721-5rg6i_default(45543fa1-b1fe-11e6-af4d-5254002465aa)\" using network plugins \"cni\": cni config unintialized; Skipping pod"
```

creating  at the master and slaves /etc/cni/net.d fixed the problem.

**Comment by luxas** [comment]
Hi!

Can you please file this issue in [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm) instead?
We're aggregating the issues there now. Sorry for the inconvenience if any.

Thank you in advance!

**Comment by adiri** [comment]
Done :)

**Comment by fieg** [comment]
@adiri can you link to the new issue?

**Comment by fieg** [comment]
Already found it: https://github.com/kubernetes/kubeadm/issues/74

**Comment by adiri** [comment]
@fieg 

on every k8s server (master and node/minoin), run:
```
mkdir -p /etc/cni/net.d
```
