### ISSUE TITLE
Panic maybe happens, since close the same channel multiple times

### ISSUE THREAD

**Issue by xiaolou86** [kubernetes/kubernetes#37444]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): close channel multiple times

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): master

**Environment**: None
- **Cloud provider or hardware configuration**: None
- **OS** (e.g. from /etc/os-release): None
- **Kernel** (e.g. `uname -a`): None
- **Install tools**: None
- **Others**: None

**What happened**:
 Panic maybe happens, since close the same channel multiple times.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

in the file pkg/proxy/config/config.go:
```
func (c *ServiceConfig) Channel(source string) chan ServiceUpdate {
	ch := c.mux.Channel(source)
	serviceCh := make(chan ServiceUpdate)
	go func() {
		for update := range serviceCh {
			ch <- update
		}
		close(ch)
	}()
	return serviceCh
}
```
The function Channel is allowed to be invoked many times with the same source,
for example,
	c.Channel("one")
	...
	c.Channel("one"),
then, it creates only one channel ch, that is, c.mux.sources["one"], while close(ch) will be invoked many times.

So I think it is a bug, although the close(ch) may not be run for ever.

I think discard the code "close(ch)" will be better.

**Comment by thockin** [comment]
Under what conditions do we call it more than once and under what conditions does it actually panic?

**Comment by xiaolou86** [comment]
>>Under what conditions do we call it more than once?

The following UT is near the condition:
```
func TestConfigurationChannels(t *testing.T) {
	mux := NewMux(nil)
	channelOne := mux.Channel("one")
	if channelOne != mux.Channel("one") {
		t.Error("Didn't get the same muxuration channel back with the same name")
	}
```
It indicates that we can and maybe call it more than once~

>>under what conditions does it actually panic?

Once we call it more than once, the panic is coming nearly~

**Comment by thockin** [comment]
So this only happens I'm tests, not prod?

**Comment by xiaolou86** [comment]
yes. It doesn't happen in current prod. I just think it's potential dangerous.

**Comment by thockin** [comment]
Thanks, I just wanted to understand the exposure.
