### ISSUE TITLE
ConfigMapKeySelector should accept a namespace argument?

### ISSUE THREAD

**Issue by coco98** [kubernetes/kubernetes#37459]
**Is this a request for help?**: no

**What keywords did you search in Kubernetes issues before filing this one?**: configmapkeyselector configmap namespace consumable

---

**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

I would like to mount configmap from a different namespace in a podspec while using ``valueFrom >   configMapKeyRef``. Is there a reason why this is not allowed?

**Kubernetes version**: 1.4

**Environment**:
- **Cloud provider or hardware configuration**: Any
- **OS** (e.g. from /etc/os-release): Any
- **Kernel** (e.g. `uname -a`): Any
- **Install tools**: Any
- **Others**: Any

**What happened**:
Schema of ConfigMapKeySelector is defined as follows:
```
  name: <string>
  key: <string>
```

**What you expected to happen**:
Schema of ConfigMapKeySelector could be defined as follows:
```
  name: <string>
  namespace: <string>
  key: <string>
```

**Comment by liggitt** [comment]
Cross namespace references from pods are not allowed for security and isolation reasons.
