### ISSUE TITLE
ThirdPartyResources / API: Failure on POST with YAML

### ISSUE THREAD

**Issue by Quentin-M** [kubernetes/kubernetes#37455]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug Report.
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5+coreos.0", GitCommit:"f70c2e5b2944cb5d622621a706bdec3d8a5a9c5e", GitTreeState:"clean", BuildDate:"2016-10-31T19:16:47Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:

Occurs only with third-party resources:

```
$ curl --silent -H "Content-Type: application/yaml" -XPOST -d"$(cat manifest.yaml)" "http://127.0.0.1:8080/apis/<third_party_domain>/v1/namespaces/<namespace>/<third_party_resource_type>"
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the object provided is unrecognized (must be of type ThirdPartyResourceData): invalid character 'a' looking for beginning of value (61706956657273696f6e3a20746563746f6e69632d76657273696f6e2e74 ...)",
  "reason": "BadRequest",
  "code": 400
}
```

The 'a' being the first letter of the manifest (stands for `apiVersion`). Changing it modifies the returned error.

However, it works just fine after conversion from YAML to JSON of the object:
```
$ curl --silent -H "Content-Type: application/json" -XPOST -d"$(cat manifest.json)" "http://127.0.0.1:8080/apis/<third_party_domain>/v1/namespaces/<namespace>/<third_party_resource_type>"
```

Of course, when passing an invalid format, the API Server answers that both JSON and YAML are supported:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the body of the request was in an unknown format - accepted media types include: application/json, application/yaml",
  "reason": "UnsupportedMediaType",
  "code": 415
}
```

It also works wonderfully using `kubectl create -f manifest.yaml` because the YAML manifest is converted client-side to JSON before calling out to the API server.

**What you expected to happen**:

The adequate serializer should have been selected and should have converted the object server-side, as specified by the `Content-Type` header.

**Comment by zhouhaibing089** [comment]
is `application/yaml` a valid content type?

**Comment by Quentin-M** [comment]
> accepted media types include: application/json, application/yaml

Also, all other API calls with v1 / v1beta objects in YAML format work fine.

**Comment by rmohr** [comment]
I can reproduce the same behaviour on 1.4.5. No matter if you send JSON or YAML content type it always selects the json serializer.

I see that on master the ThirdPartyResource serializer negotiation part was refactored in #34651. It looks like there is now explicitly only application/json supported. 

@smarterclayton do you know if this is also the intended behaviour for 1.4.5?

**Comment by smarterclayton** [comment]
It's not the intended behavior, but TPR doesn't handle YAML.

**Comment by philips** [comment]
cc @brendandburns

**Comment by philips** [comment]
Is this still an issue with CRDs?

**Comment by nikhita** [comment]
> Is this still an issue with CRDs?

The error message is fixed but CustomResources support **only** `application/json` for now.

If `application/yaml` is used, 

- The earlier error message was:

```
 "message": "the body of the request was in an unknown format - accepted media types include: application/json, application/yaml",
```

- The current error message is:

```
"message":"the body of the request was in an unknown format - accepted media types include: application/json;stream=watch",
```

**Comment by liggitt** [comment]
Corrected the message in https://github.com/kubernetes/kubernetes/pull/58258
Added support for yaml in https://github.com/kubernetes/kubernetes/pull/58260

/assign
