### ISSUE TITLE
K8S should enforce the access mode ROX check when attaching PVC to pods.

### ISSUE THREAD

**Issue by xingzhou** [kubernetes/kubernetes#37465]
As I discussed this issue in #sig-storage these days, at present, even if we add ROX access mode to PV and PVCs, the volume attached to pod is still in RW mode and can be written files to. 

The steps to reproduce this issue:
1. Create a NFS PV with access mode ReadOnlyMany.
2. Create a PVC with access mode ReadOnlyMany and make sure k8s bind this PVC with the PV we created in step1.
3. Create a pod using the PVC defined in step2.
4. The NFC volume should be attached to pod successfully.
5. Login to the pod and try to write some file to the volume, we can see that the file can be successfully written to the volume.

**Comment by xingzhou** [comment]
I will take a look a the issue and try to submit a PR then.

**Comment by xiaoping378** [comment]
@xingzhou i met the same issue.
have any news ?

**Comment by xingzhou** [comment]
@xiaoping378, I'm working on the proposal now.
For now, one can specify `v1.Pod.spec.volumes[].persistentVolumeClaim.readOnly=true` to attach a readonly volume, you can take a try.

**Comment by xiaoping378** [comment]
Hi @xingzhou 
It's worked, Thank you very much !
