### ISSUE TITLE
fix some issues with kubectl drain

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#37460]
In writing some documentation for `kubectl drain` I noticed some issues with the implementation.

I think the simplest user experience is that the command doesn't return until all the user pods are drained off the machine. In particular this means
* wait until all graceful termination is finished
* infinitely retry evictions that are rejected due to insufficient PodDisruptionBudget

The current implementation does not do this, in particular
* wait for graceful termination appears to be [capped](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/drain.go#L257) at 10 sec * number of pods, which may be much shorter than the max graceful termination
* we only retry evictions [maxPatchRetry](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/drain.go#L236) number of times

My suggestion is to change the behavior so that
* we compute how long to wait for graceful termination, by taking max(grace periods of all pods that we want to delete) (or the value of --grace-period command line argument instead, if that is specified), and wait exactly that amount of time plus a small buffer
* we retry evictions infinitely

@ymqytw @erictune WDYT? I think we should do this in 1.5 because the current behavior is very non-obvious.

**Comment by ymqytw** [comment]
> wait for graceful termination appears to be capped at 10 sec * number of pods, which may be much shorter than the max graceful termination

The problem here is how long should we wait, if the user doesn't specify a timeout.
The default timeout used in drain is following how long the reapers have in [ReplicationControllerReaper](https://github.com/kubernetes/kubernetes/blob/v1.5.0-beta.2/pkg/kubectl/stop.go#L168), [ReplicaSetReaper](https://github.com/kubernetes/kubernetes/blob/v1.5.0-beta.2/pkg/kubectl/stop.go#L237), [StatefulSetReaper](https://github.com/kubernetes/kubernetes/blob/v1.5.0-beta.2/pkg/kubectl/stop.go#L337) and [JobReaper](https://github.com/kubernetes/kubernetes/blob/v1.5.0-beta.2/pkg/kubectl/stop.go#L383). Maybe this is not long enough. I can make the changes.

> we retry evictions infinitely

Do we still need exponential back off?
@davidopp

**Comment by davidopp** [comment]
To summarize discussion with @ymqytw there are two possible approaches (pseudocode below)

1) Goroutine approach:

For each pod P that meets the [filter](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/drain.go#L407), do the following:
```
for {
   success := try evict P using eviction subresource
   if (success) break
   sleep 5
}
wait for P to be gone from etcd, using timeout of max(pod's graceful termination spec, --grace-period argument to kubectl drain)
```

2) Non-goroutine approach:

```
for (each pod that is still on the node and meets the filter and has un-set deletionTimestamp) {
       for {
          success := try evict P using eviction subresource
          if (success) break
          sleep 5
        }
}
while (there are pods that satisfy the filter and not timed out yet) {
}
```
where "not timed out yet" means you haven't finished waiting max(--grace period argument to kubectl drain, max graceful termination spec across all pods on the node)

**Comment by saad-ali** [comment]
@ymqytw @davidopp Could you please triage this for 1.5 and apply blocker or non-blocker labels as appropriate along with priority.

**Comment by ymqytw** [comment]
@saad-ali The PR #37604 for this issue is waiting to be merged.

**Comment by calebamiles** [comment]
@saad-ali, marking this as a release blocker due to https://github.com/kubernetes/kubernetes/issues/37605 being marked as such. Please update if needed @ymqytw @davidopp.

**cc: @dims**
