### ISSUE TITLE
kubectl exec -it fails with "Unable to use a TTY" and never get a prompt

### ISSUE THREAD

**Issue by ligc** [kubernetes/kubernetes#37471]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

Unable to use a TTY

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT 

**Kubernetes version** (use `kubectl version`): 
root@kube-master:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.7-beta.0.2+1ef121737093fd-dirty", GitCommit:"1ef121737093fdefada11034782d235a205f567f", GitTreeState:"dirty", BuildDate:"2016-11-25T03:02:28Z", GoVersion:"go1.7.3 ibm-1.7", Compiler:"gc", Platform:"linux/ppc64le"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.7-beta.0.2+1ef121737093fd-dirty", GitCommit:"1ef121737093fdefada11034782d235a205f567f", GitTreeState:"dirty", BuildDate:"2016-11-25T03:02:28Z", GoVersion:"go1.7.3 ibm-1.7", Compiler:"gc", Platform:"linux/ppc64le"}
root@kube-master:~# 

**Environment**:
- **Cloud provider or hardware configuration**: hardware configuration
- **OS** (e.g. from /etc/os-release): 
```
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`):  Linux kube-master 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:38:24 UTC 2016 ppc64le ppc64le ppc64le GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:

kubectl exec -it <pod_name> -- /bin/bash fails with error  "Unable to use a TTY" and never get a prompt

```
root@kube-master:~# kubectl exec -it my-nginx-2833891535-ycsq2 -- /bin/bash
Unable to use a TTY - input is not a terminal or the right kind of file

=============> never get a prompt
```

**What you expected to happen**:

Could use kubectl exec -it <pod_name> -- /bin/bash to get the shell prompt of the POD.

**How to reproduce it** (as minimally and precisely as possible):

1. Install Kubernetes 1.4.7
2. Deploy an application
3. Run kuectl exec -it <pod_name> -- /bin/bash

**Anything else do we need to know**:

I could use docker exec -it <container_name> /bin/bash to get the prompt, but kubectl exec does not work.

**Comment by AdoHe** [comment]
@ligc could you provide your kubernetes version?

**Comment by ligc** [comment]
HI, the kubernetes version is 1.4.7, running on an OpenPOWER box, ppc64le arch.

```
root@kube-master:# kubectl version
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.7-beta.0.2+1ef121737093fd-dirty", GitCommit:"1ef121737093fdefada11034782d235a205f567f", GitTreeState:"dirty", BuildDate:"2016-11-25T03:02:28Z", GoVersion:"go1.7.3 ibm-1.7", Compiler:"gc", Platform:"linux/ppc64le"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.7-beta.0.2+1ef121737093fd-dirty", GitCommit:"1ef121737093fdefada11034782d235a205f567f", GitTreeState:"dirty", BuildDate:"2016-11-25T03:02:28Z", GoVersion:"go1.7.3 ibm-1.7", Compiler:"gc", Platform:"linux/ppc64le"}
root@kube-master:#
```

**Comment by f-w** [comment]
Hi, I got same error on Windows 7 MINGW32 console installed by Git. But from DOS prompt it works.
The command I run is OpenShift CLI `oc`, which calls kubectl under the hood so I believe the issue is the same.

**Comment by ajtrichards** [comment]
Hi @ligc - Have you tried: `kubectl exec -it my-nginx-2833891535-ycsq2 /bin/bash` or `kubectl exec -it my-nginx-2833891535-ycsq2 sh`? That's what I would typically use and it works fine :)

**Comment by ligc** [comment]
@kubernetes/sig-cli-misc

**Comment by whitecolor** [comment]
This I have on Windows 10 WSL, when trying to run `kubectl.exe` windows version.

**Comment by gwenywar** [comment]
Has anyone found a workaround for this issue? I am running Kubernetes GitVersion:"v1.6.3" on `Linux minsky1 3.10.0-514.16.1.el7.ppc64le #1 SMP Fri Mar 10 13:08:23 EST 2017 ppc64le ppc64le ppc64le GNU/Linux`and I get the same error message when  run `ku exec -it sparkmaster-4180548331-b3lkq bash` with just `Unable to use a TTY - input is not a terminal or the right kind of file` and the terminal just hanging there...
Is there no other way to attach to a running pod?

**Comment by mengqiy** [comment]
@alexandercampbell @shiywang Will one of you have bandwidth to look into this issue?

**Comment by mlushpenko** [comment]
Same here, running minikube on windows 10

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:1
5:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"1970-01-01T00:0
0:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by MartinsIrbe** [comment]
Getting the same while trying to use alias:
```bash
alias kexecp='{ pod=$(cat -); k exec -it $pod --context=prod -- sh; }<<<'
```
then:
```bash
% kexecp some-app
Defaulting container name to some-app.
Use 'kubectl describe pod/some-app' to see all of the containers in this pod.
Unable to use a TTY - input is not a terminal or the right kind of file
```

**Comment by Ctesias** [comment]
Same problem using an alias on mac, converted it to a bash function and it worked:

`kshell() {
serverName=$(kubectl get pods | cut -d" " -f1 | grep server)
kubectl exec -it $serverName ash --namespace=<namespace>
}`

**Comment by hemantaltair** [comment]
Any solution yet ?

**Comment by handlers** [comment]
Same issue when trying to pipe to xargs:

`kubectl get pods -n foobar | grep baz | awk '{print $1}' | xargs -J % kubectl exec -it -n foobar % /bin/bash`

**Comment by chancez** [comment]
@handlers I've been scratching my head on this one for a long time myself, and the -o` flag is just what I needed. Though, the `-o` is on xargs, not `kubectl exec` if anyone else reading it was a bit confused by that.

**Comment by handlers** [comment]
Updated the comment @chancez!

**Comment by mdeknowis** [comment]
Have the same issue using MobaXterm (cgywin)

```
> kubectl exec --namespace=default -it hello-world-65c6847588-qnhqd /bin/sh
Unable to use a TTY - input is not a terminal or the right kind of file
```

**Comment by gangachris** [comment]
while working with Jenkins, I kept getting the error `Unable to use a TTY - input is not a terminal or the right kind of file` because the pod was not yet in a ready state. We had to write a script to check make sure the state of the pod is `Running`

**Comment by TerjeBr** [comment]
One workaround is posted here https://github.com/Microsoft/WSL/issues/2271#issuecomment-317006437

/remove-lifecycle rotten

**Comment by pxlphile** [comment]
I can reproduce this behavior in Windows 7 Professional 64 bit in both
- Git bash
- Windows cmd

The minikube is a fresh v0.28.0 install
```shell
$ minikube version
minikube version: v0.28.0
```

I use a command as seen in this [kubernetesbyexample.com, part "Pods"](http://kubernetesbyexample.com/pods/)

```shell
$ kubectl exec twocontainers -c shell -i -t -- bash
Unable to use a TTY - input is not a terminal or the right kind of file
```

**Comment by bczoma** [comment]
Same issue but `winpty kubectl.exe exec -it <pod> -- bash` worked for me as a workaround - see https://github.com/Microsoft/WSL/issues/2271#issuecomment-317006437.

**Comment by jiahut** [comment]
this work for me： 
> kubectl get pods  | perl -alne 'print $F[0] if $F[0] =~ /toolkit/' | xargs -o  -I {} kubectl exec -it {} -c toolkit sh

**Comment by Rakitic07** [comment]
Facing the same issue on Git Bash Terminal on Windows 7:

`kubectl exec -it <pod_name> bash`

But, the same works on cmd, powershell and Docker Terminal.

**Comment by mdeknowis** [comment]
Same issue using MobaXterm (cygwin) and

``` kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"windows/amd64"}```

**Comment by kyle-tightest** [comment]
Reproduced issue on Windows 10 running Git Bash for Windows.
`$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

$ uname -a
MINGW64_NT-10.0 KYLE-PC 2.8.2(0.313/5/3) 2017-07-12 15:35 x86_64 Msys`

The error message appears when using the "-t" flag.
Whether or not the "-t" flag is used, no bash prompt appears, although I am still able to enter and process bash commands.

**Comment by PatrickLang** [comment]
I don't think we can fix this. It seems like an issue in the Git bash environment only. This works in WSL, and it works with the native Windows binary. I would recommend opening an issue with the Git-SCM.org team that provides that bash shell.

**Comment by ronLloydNice** [comment]
Windows Users: use "Windows PowerShell", not "GitBash"

**Comment by bbotte** [comment]
I can't make it, so use the shell.

**Comment by bbotte** [comment]
kubectl get po |awk 'NR>1{print $1}'|while read i;do echo "echo " $i >> 2; echo kubectl exec -it $i -- ping db-com -c 1 2\>\&1 \|grep from\|awk \'\{print \$4\}\'  >> 2;done

**Comment by bbotte** [comment]
I can't make it, so use the shell，For example, ping db.com
kubectl get po |awk 'NR>1{print $1}'|while read i;do echo "echo " $i >> a; echo kubectl exec -it $i -- ping db.com -c 1 2\>\&1 \|grep from\|awk \'\{print \$4\}\'  >> a;done
sh a

**Comment by nick-pap** [comment]
Use winpty kubectl exec -it <pod-name> bash

**Comment by KVSocial** [comment]
Same problem with us:

`bash -c "./kubectl --kubeconfig .kube/config exec -i -t $(./kubectl --kubeconfig .kube/config get pods -n adaptive-admin-be -l workload.user.cattle.io/workloadselector=deployment-adaptive-admin-be-adaptive-admin-be -o=custom-columns=:metadata.name --no-headers) -n adaptive-admin-be -- bash -c \"cd app && ../vendor/phalcon/devtools/phalcon migration run\""`

and then

OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"adaptive-admin-be-65fd7cdc86-vc2t8\": executable file not found in $PATH": unknown

Only started a few days ago before that all was good.

**Comment by sadlame** [comment]
Apparently this is a docker bug.

`kubectl exec` internally invokes the terminal component included in the docker engine but their implementation (using GetConsoleMode to judge if a file handle is a tty) does not detect fake Windows terminals including Git bash and Cygwin bash as a valid tty.

The most straightforward fix would be to replace GetConsoleMode with [this](https://github.com/mattn/go-isatty) but maybe the check itself (IsTerminal) could be removed provided it does not break anything.

**Comment by albertlr** [comment]
we ran into the same issue, however if you are running it from Command Prompt ( `cmd.exe` ) .. it was working like a charm

**Comment by sadlame** [comment]
@albertlr As I mentioned this is probably not a Kubernetes bug. The terminal package within the docker engine is currently being incapable of detecting fake terminals like Git bash and Cygwin terminal. This issue does not reproduce on `cmd.exe` because it is a real terminal, for which GetConsoleMode returns TRUE. Adding a special detection logic like [this one](https://github.com/mattn/go-isatty) to the docker engine will fix the issue but there is nothing that can be done here except removing the check altogether.

**Comment by WojciechThomas** [comment]
If you don't like solution from @nick-pap you can define alias:
`$> alias kubectl='winpty kubectl'` 
and then use
`$> kubectl exec -it test sh`
as usual.

Git bash works like Unix shell and it uses stdin and stdout streams to communicate with kubectl, however in Windows with Git bash you are using actually kubectl.exe that expects Windows console and not Unix streams. Winpty solves this problem. 

If you want to make the change permanent put the alias into ~/.bash_profile file.

**Comment by mdeknowis** [comment]
> 
> 
> If you don't like solution from @nick-pap you can define alias:
> `$> alias kubectl='winpty kubectl'`
> and then use
> `$> kubectl exec -it test sh`
> as usual.
> 
> Git bash works like Unix shell and it uses stdin and stdout streams to communicate with kubectl, however in Windows with Git bash you are using actually kubectl.exe that expects Windows console and not Unix streams. Winpty solves this problem.
> 
> If you want to make the change permanent put the alias into ~/.bash_profile file.

Unfortunate that is nor working for me. Using winpty just immediately ends kubectl. No error, no console, nothing.

**Comment by zffocussss** [comment]
> taking out -t flag from the command solved it for me.

very good

**Comment by pankaj-OD** [comment]
removing -t is not a solution permanently. because when I got the same error I also used this suggestion of removing of -t, but in that case whatever command we are passing in next line it do not shows in output see:

+ kubectl exec -i <podname>-n eai /bin/sh
+ ls -lrth
total 0
+ exit
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS


--> here it should be showing output for ls -lrth, do anyone still has best solution to it ?

**Comment by santmcodes** [comment]
same issue with me as well 

$  kubectl exec -it nfs-server -n testnm -- bash
Unable to use a TTY - input is not a terminal or the right kind of file

**Comment by klatek** [comment]
same issue here:
ran from Win CMD
kubectl version v1.18.0
minkube version 1.9.2

If it is possible because I don't have docker installed on WIN machine whatsoever?

**Comment by gavrilfb** [comment]
The original issue mentions "Ubuntu" as the OS, how the hell did it derail into "Windows" issue?
People, try to read the context and create another issue if your systems are not similar enough, please.

**Comment by paulmiller3000** [comment]
> Facing the same issue on Git Bash Terminal on Windows 7:
> 
> `kubectl exec -it <pod_name> bash`
> 
> But, the same works on cmd, powershell and Docker Terminal.

Thank you, @Rakitic07 ! I had the same problem in Git Bash Terminal on Windows 10. On your suggestion, I tried successfully in PoewerShell.

**Comment by slwon** [comment]
I'm using MINGW64. Like  @santmcodes, I solved the problem by prefixing it with winpty.

`$ winpty kubectl exec -it my-pod -- bash`

`root@my-pod:/# ls -l
total 52
lrwxrwxrwx   1 root root    7 Sep 25 01:20 bin -> usr/bin
drwxr-xr-x   2 root root 4096 Apr 15  2020 boot
drwxr-xr-x   5 root root  360 Oct 19 13:34 dev
drwxr-xr-x   1 root root 4096 Oct 19 13:34 etc
drwxr-xr-x   2 root root 4096 Apr 15  2020 home
`

**Comment by manpreetdeol** [comment]
For GIT bash terminal, this works:
 
 winpty kubectl exec -it <podname> bash
