### ISSUE TITLE
'kubeadm join' failed on cluster node ( @kubernetes/sig-cluster-lifecycle )

### ISSUE THREAD

**Issue by tonyclam** [kubernetes/kubernetes#37475]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
'<node/discovery> failed to parse response as JWS object [square/go-jose: compact JWS format must have three parts]'
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Centos 7.1
- **Kernel** (e.g. `uname -a`): 4.1.12-37.5.1.el7uek.x86_64 #2 SMP Thu Jun 9 16:01:20 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
Failed with error:
 <node/discovery> failed to parse response as JWS object [square/go-jose: compact JWS format must have three parts]

**What you expected to happen**:
The cluster should be able to join the master node

**How to reproduce it** (as minimally and precisely as possible):
1. kubeadm init on master
2. kubeadm join on cluster

**Anything else do we need to know**:
kubeadm version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.2.380+85fe0f1aadf91e", GitCommit:"85fe0f1aadf91e134102cf3c01a9eed11a7e257f", GitTreeState:"clean", BuildDate:"2016-11-02T14:58:17Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
For kube-discovery image
>docker inspect <kube-discovery images id>
[root@ovm21 ~]# docker inspect c5e0c9a457fc
[
    {
        "Id": "sha256:c5e0c9a457fcb53ac5c564656f3fabba733ab1e8187e98d095c88356b9245de8",
        "RepoTags": [
            "gcr.io/google_containers/kube-discovery-amd64:1.0"
        ],
        "RepoDigests": [
            "gcr.io/google_containers/kube-discovery-amd64@sha256:7ebce8129c41bf64053f56a4f4418e198265b104b17f3f2d5b61667e208528f4"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2016-09-24T17:16:49.942311731Z",
        "Container": "5581c81bd1defe34d67a2c267841bc164e0decd53b1a9114b745585e628de106",
        "ContainerConfig": {
            "Hostname": "6250540837a8",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ENTRYPOINT \u0026{[\"/bin/sh\" \"-c\" \"\\\"/usr/local/bin/kube-discovery\\\"\"]}"
            ],
            "Image": "2b3aeb5c0ccc7b85afa3c110b8b6fc3698f1da723f4845cd4250895c599393e1",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/bin/sh",
                "-c",
                "\"/usr/local/bin/kube-discovery\""
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "1.9.1",
        "Author": "",
        "Config": {
            "Hostname": "6250540837a8",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "2b3aeb5c0ccc7b85afa3c110b8b6fc3698f1da723f4845cd4250895c599393e1",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/bin/sh",
                "-c",
                "\"/usr/local/bin/kube-discovery\""
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 134164555,
        "VirtualSize": 134164555,
        "GraphDriver": {
            "Name": "btrfs",
            "Data": null
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:42755cf4ee95900a105b4e33452e787026ecdefffcc1992f961aa286dc3f7f95",
                "sha256:7815ca90458efad6a994cbe56b123737a3b92c472493d5581fb960821680a338",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef"
            ]
        }
    }
]

**Comment by luxas** [comment]
Hi!

Can you please file this issue in [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm) instead?
We're aggregating the issues there now. Sorry for the inconvenience.

Thank you in advance!

**Comment by tonyclam** [comment]
will do.
