### ISSUE TITLE
Kubemark master components should run as Pods

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#37485]
Currently we have a custom setup that runs master components as top-level processes under supervisord, which is lighter than running kubelet and docker. We need to make it similar to production setup when they run as Pods, so that we have better precision and we'll be able to experiment with introducing limits for components.

cc @kubernetes/sig-scalability @wojtek-t

**Comment by timothysc** [comment]
@gmarek isn't this what kubeadm does.?.?

**Comment by shyamjvs** [comment]
@wojtek-t @gmarek Can we close this issue now?
