### ISSUE TITLE
Problem mounting and EBS Volume on a Pod when Node is deleted 

### ISSUE THREAD

**Issue by mrmm** [kubernetes/kubernetes#37493]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---
I am trying to create a pod with a PVC 

This the log error from the controller-manager
```
I1125 15:57:04.723817       1 reconciler.go:115] Started DetachVolume for volume "kubernetes.io/aws-ebs/aws://eu-west-1a/vol-95f69317" from node "ip-172-16-220-195.eu-west-1.compute.internal"
E1125 15:57:04.725275       1 nestedpendingoperations.go:233] Operation for "\"kubernetes.io/aws-ebs/aws://eu-west-1a/vol-95f69317\"" failed. No retries permitted until 2016-11-25 15:59:04.725246012 +0000 UTC (durationBeforeRetry 2m0s). Error: DetachVolume failed fetching node from API server for volume "kubernetes.io/aws-ebs/aws://eu-west-1a/vol-95f69317" (spec.Name: "prometheus-ebs-pv") from node "ip-172-16-220-195.eu-west-1.compute.internal" with: nodes "ip-172-16-220-195.eu-west-1.compute.internal" not found
```

**Is this a BUG REPORT **

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:45:16Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4+coreos.0", GitCommit:"be9bf3e842a90537e48361aded2872e389e902e7", GitTreeState:"clean", BuildDate:"2016-08-02T00:54:53Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Cloud provider AWS
- **OS** (e.g. from /etc/os-release): CoreOS
- **Install tools**: kube-aws
- **Others**:

**What happened**:
Controller Manager is Trying to Detach EBS Volume from a none existing Node

**What you expected to happen**:
The Pod to run in another node.

**How to reproduce it** (as minimally and precisely as possible):
1- Create a PV using and already created AWS EBS volume.
2- Create PVC using this PV
2- Mount the PVC in a Pod
3- Delete the AWS instance running the Pod

**Comment by gnufied** [comment]
There has been some fixes around this behaviour - https://github.com/kubernetes/kubernetes/pull/33616  

I would suggest you should try a more recent k8s release and see if that fixes this problem.

**Comment by mrmm** [comment]
@gnufied Thanks for the advice.
