### ISSUE TITLE
Consider expanding service names

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#3752]
Filing this so we can revisit.
@satnam6502 

Service names (and apparently Namespace names in the client, but not the server) are restricted to DNS 952 labels (24 characters).  Most other API Objects have names that are DNS 1123 subdomains (much longer).

In doing tests it is useful to generate random names, and this is a bit annoying for services.

Can we expand service names?

1) DNS 1035 labels (longer)
2) DNS 1035 subdomains (longer and allow dots)
3) DNS 1123 labels (longer, allow leading digit)
4) DNS 1123 subdomains (longer, allow leading digit and dots)

(4) would be most consistent with other objects.

If we do (2) or (4) we need to convert dots to underscores in env-var names, which could cause a collision (e.g. foo-bar and foo.bar).  Maybe double underscore for dots?

If we do (3) or (4) we need to handle leading digits in env-vars.  Maybe a prefixed underscore?

(1) seems least controversial, but is still different than everything else.

**Comment by bgrant0607** [comment]
We shouldn't let the form of the environment variables dictate the names. I'll drop a proposal on #1768.

**Comment by smarterclayton** [comment]
Even in the case of a collision... It's likely you let yourself do that.  This may be a case of trying to save people from themselves, for minimal benefit.

**Comment by thockin** [comment]
I think expanding servoce names is reasonable to do, I just wanted to think
through potential problems.  Then we have namespaces as the sole
nonstandard name.

**Comment by smarterclayton** [comment]
As part of #3789 I started normalizing this.  Will put any change in there.

**Comment by thockin** [comment]
Sorry, I did not see this before replying on the other thread.

**Comment by thockin** [comment]
An interesting side-effect of changing this from *Label to *Subdomain (i.e. allowing dots) is that you could create a service called "google.com" and the DNS lookup rules would hit your service rather than the real site.

I'm still in favor of lengthening Service names, perhaps all the way to 1123 labels, but not to subdomains.  Too easy to abuse.  I wonder now, with hindsight, whether it was wise to make other object names be subdomains.  I don't think we can change that, at this point.  It has not caused any issues (yet).

**Comment by smarterclayton** [comment]
We haven't hit any that haven't been related to services or explicitly
using names of routes in DNS names (because wildcard certs only work one
level deep).  On the other hand I don't think people have found it valuable
to have the dot (have not seen it used much).

On Mon, Aug 17, 2015 at 1:59 PM, Tim Hockin <notifications@github.com>
wrote:

> An interesting side-effect of changing this from *Label to *Subdomain
> (i.e. allowing dots) is that you could create a service called "google.com"
> and the DNS lookup rules would hit your service rather than the real site.
>
> I'm still in favor of lengthening Service names, perhaps all the way to
> 1123 labels, but not to subdomains. Too easy to abuse. I wonder now, with
> hindsight, whether it was wise to make other object names be subdomains. I
> don't think we can change that, at this point. It has not caused any issues
> (yet).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/3752#issuecomment-131910058>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
I would not be in favor of extending service names to subdomains either.

On Mon, Aug 17, 2015 at 8:58 PM, Clayton Coleman <ccoleman@redhat.com>
wrote:

> We haven't hit any that haven't been related to services or explicitly
> using names of routes in DNS names (because wildcard certs only work one
> level deep).  On the other hand I don't think people have found it valuable
> to have the dot (have not seen it used much).
>
> On Mon, Aug 17, 2015 at 1:59 PM, Tim Hockin <notifications@github.com>
> wrote:
>
>> An interesting side-effect of changing this from *Label to *Subdomain
>> (i.e. allowing dots) is that you could create a service called "
>> google.com" and the DNS lookup rules would hit your service rather than
>> the real site.
>>
>> I'm still in favor of lengthening Service names, perhaps all the way to
>> 1123 labels, but not to subdomains. Too easy to abuse. I wonder now, with
>> hindsight, whether it was wise to make other object names be subdomains. I
>> don't think we can change that, at this point. It has not caused any issues
>> (yet).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/kubernetes/kubernetes/issues/3752#issuecomment-131910058>
>> .
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bgrant0607** [comment]
Technically, any change here would break all API versions. In practice, I doubt many care that much about the length.

1123 is on the edge, since it would change the validation regexp, which might be duplicated in client-side validation code. I'd be inclined against this, unless there is a compelling reason.

Allowing subdomains is not viable.

**Comment by thockin** [comment]
Simply moving this to DNS1035 labels would remove some cruft around truncating auto-generated service names.

I'd like to see this fully analyzed and either fixed or closed in v1.2

**Comment by lavalamp** [comment]
I don't know why this is in the CSI team, but regardless, we're definitely not doing this for 1.2.

**Comment by ae6rt** [comment]
As a user, I have had occasion to want service names with dots in them.  Our pre-kubernetes legacy (the state of things way back last year) service discovery design traffics in names like users.1.xoomapi, where xoomapi is an internal top level domain.  Our supporting DNS always resolves names on this TLD to 127.0.0.1, where a sidecar proxy listening on 127.0.0.1 handles the actual request on behalf of the consumer of the service  users.1.xoomapi.  Deploying such consumers into kubernetes leads me to bundle a sidecar into each consumer pod, which I'd rather not be forced to do.

If I could form k8s Service names with dots in them, I could remove the sidecar from the pod and have a pool of such sidecars running under the control of a replication controller.  

I understand that subdomains are not considered viable.  However, there are legitimate uses for them.  I can work around this in one or more ways, but wanted to chime in.

**Comment by thockin** [comment]
Allowing dots in service names would make DNS for services much less
predictable and harder to manage.  I have not yet heard a reason not to
move to 1035 (longer, same regex) and a moderate reason (client-side
validation) not to move to 1123 (longer, looser regex).

It annoys me to be different.  The implication of going to 1123 labels (not
subdomains) is that any client that half old validation rules baked-in
would reject names that are now allowed.  This would not be so bad for
clients that make new objects, except it's theoretically possible that
clients would misbehave when reading existing objects, too.  Blech

If someone sends me a patch to move this to 1035, kill off 952 support, and
fix all the tests, I would approve it (assuming no surprises).

I honestly can not recall why we didn't do 1035 to start.

**Comment by thockin** [comment]
To be clear, I think moving to any form of subdomains (allowing dots) is off the table.

**Comment by smarterclayton** [comment]
I thought we did short names because we were afraid that we would run out
of allowed DNS characters.

**Comment by dims** [comment]
@thockin So we pick https://github.com/kubernetes/kubernetes/pull/29523 over https://github.com/kubernetes/kubernetes/pull/28005 ?

**Comment by bacongobbler** [comment]
Yes, if that's the case then #29523 would be "the right one".

**Comment by thockin** [comment]
@smarterclayton - I don't think we'll run out of DNS characters, even if a
service uses all 63 characters.  I feel like there was some reason for this
but I just can't figure out what it might have been.

**Comment by thockin** [comment]
I just re-read https://github.com/kubernetes/kubernetes/pull/759 and I
think 952 was just chosen for no real reason (vs 1035).
