### ISSUE TITLE
In pkg/kubectl/cmd/get.go there is a confused arg named "all"

### ISSUE THREAD

**Issue by tianshapjq** [kubernetes/kubernetes#37533]
In pkg/kubectl/cmd/get.go there is a piece of code extracting arg named "all" from args, like below:
       // determine if args contains "all"
	for _, a := range args {
		if a == "all" {
			printAll = true
			break
		}
	}
The question is, how can we set this arg properly? Such as "kubectl get all", "kubectl get pod all" and "kubectl get all pod" all go wrong, maybe this arg should not be used in this way.
My suggestion is to add a new flag named "print-all", can I do this?

**Comment by liggitt** [comment]
`all` is an alias that expands to a set of several different resource types, but I don't think that method of determining whether disjoint resources are being printed is correct.

**Comment by liggitt** [comment]
cc @juanvallejo

**Comment by juanvallejo** [comment]
@liggitt Ah, in this case the `printAll` bool is only used to ensure that a resource kind gets printed in the event that `get all` only has a single resource to return. It is passed [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/get.go#L426) to the `cmdutil` function [MustPrintWithKinds](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/helpers.go#L635).

```
$ kubectl get all
NAME                                CLUSTER-IP       EXTERNAL-IP   PORT(S)                 AGE
svc/frontend                        172.30.158.235   <none>        9998/TCP                12d
```

**Comment by tianshapjq** [comment]
Thanks for your reply! Sorry for my mistake for describing "kubectl get all" command, it works fine.
But another question is, the _all_ arg is not contained in the args list, such as "kubectl get -h" doesn't contain the _all_ arg. Then users may not know about this arg without looking into the source code. Do you think it's good to add the _all_ into the args list? @juanvallejo

**Comment by liggitt** [comment]
It's a positional arg, not a flag. It should appear in the help somewhere

**Comment by tianshapjq** [comment]
Thanks! Problem solved. I will close this issue.
