### ISSUE TITLE
Enable DNS horizontal autoscaling feature for more Cloud Providers

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#37567]
Recently a new DNS horizontal autoscaling feature was added for GCE clusters by #33239. This DNS horizontal autoscaling feature ensures number of kube-dns Deployment replicas scale with cluster needs. It is achieved by running another independent cluster add-on called [cluster-proportional-autoscaler](https://github.com/kubernetes-incubator/cluster-proportional-autoscaler). Docs of this feature could be found on [here](https://github.com/kubernetes/kubernetes.github.io/pull/1727).

This is a handful feature that a few people asked for (#28497), we should consider to turn it on by default for more Cloud Providers. Or we should at least make it an available option for users. It would be easy to be done as this feature is deployed as a cluster addon.

@justinsb @chrislovecnm 
cc @kubernetes/sig-network

**Comment by ericuldall** [comment]
Which version of k8s has the DNS autoscaling support for GKE?

**Comment by MrHohn** [comment]
@ericuldall We are working on enabling this feature on GKE for 1.5.

**Comment by chrislovecnm** [comment]
@MrHohn probably something we can include in kops. Thoughts?

**Comment by MrHohn** [comment]
cc @bowei

**Comment by MrHohn** [comment]
@chrislovecnm I notice that kops has its own dns-controller implementation and is not using kube-dns as part of the addon resources. What is the plan for dns service in kops and how is it different from the main kubenetes branch?

**Comment by chrislovecnm** [comment]
@MrHohn kops uses dns-controller to create DNS entries in route53, and we use kube-dns.  They are two separate use cases.

**Comment by MrHohn** [comment]
@chrislovecnm Thanks for clarifying, I didn't take a careful look before.

As the [dns-horizontal-autoscaler](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns-horizontal-autoscaler) does not has dependency on kube-dns's version and it is supposed be deployed as an independent addon resource, I think it might be correct to also put it as in https://github.com/kubernetes/kops/tree/master/addons.

What is the policy for introducing new addon into kops? I could help to work on this.

**Comment by chrislovecnm** [comment]
@MrHohn happy to have a PR :)  Always happy to have help!  We are working on some developer on-boarding docs, but nothing is done yet.

**Comment by MrHohn** [comment]
Seems like the `kube-dns-autoscaler` is already introduced into kops by kubernetes/kops#1213. Thanks for the work!

**Comment by justinsb** [comment]
So kops has this; and sig-bot is bugging me to do something...

If there's another cloud that we think should be supported, let's sig-it-to-them ;-)  Otherwise shall we close?

**Comment by MrHohn** [comment]
Let's close this for now :)
