### ISSUE TITLE
Implement rolling-upgrade on daemonsets and statefulsets via `kubectl`

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#37566]
In order to support simple updates of daemon sets and stateful sets, it should be possible to do the following:

1. update the DS or SS
2. run a kubectl command that maintains certain availability numbers by deleting pods and returns once everything is set

This would be a good stepping stone to implement updates for SS and DS because it would solve an immediate need (users have to write their own version of this) and provide practical feedback on a full update solution.

As a straw man, the command might be:

    $ kubectl COMMAND <statefulset|daemonset|rc>/NAME

and support some or all of these parameters from deployments `--max-unavailable`, `--min-ready-seconds`, `--progress-deadline-seconds`.

The command would identify the set of pods that don't match the current template, delete them using some criteria (newest first, highest name, etc), and exit when all pods are updated or --progress-deadline-seconds is reached.

**Comment by smarterclayton** [comment]
@kubernetes/sig-apps as mooted on the call today

**Comment by kargakis** [comment]
cc @lukaszo

**Comment by kargakis** [comment]
@kubernetes/kubectl

**Comment by AdoHe** [comment]
@smarterclayton @kargakis any existing command can use here? Like adopt `rolling-update` to implement this.

**Comment by smarterclayton** [comment]
Possible - rolling-update's arguments are a bit too specific to the "two controller" update pattern, whereas this is only dealing with one controller.  But yes, I think it might be the natural place to do it.

**Comment by AdoHe** [comment]
any good idea about the command name? Really hard to come up with a good name :(

**Comment by kargakis** [comment]
No need to come up with a new name, make `rolling-update` accept a resource tuple and based on the type run the specific strategy (@lukaszo has been working on DaemonSet upgrades so he may be interested in adding this in `rolling-upgrade`).

**Comment by majewsky** [comment]
What about `rolling-restart`?

**Comment by kargakis** [comment]
@majewsky rolling restart has its own issue (which is different from normal upgrades imo)
https://github.com/kubernetes/kubernetes/issues/13488

**Comment by majewsky** [comment]
But isn't step 2 described in the first comment exactly a rolling restart? The main difference in a rolling update is that you create a new object (either ReplicationController or ReplicaSet) of the same type, whereas with a DaemonSet, you don't really have any other option than to update it in-place and then issue a rolling restart.

**Comment by kargakis** [comment]
The DaemonSet will not restart pods, but rather roll out new pods over old pods.

**Comment by majewsky** [comment]
Ah, I see your point. So it would be something like `rolling-replace` or `rolling-recreate`?

**Comment by smarterclayton** [comment]
Rolling recreate is interesting, although it might imply that it updates
all pods.  rolling-apply is interesting....

**Comment by bgrant0607** [comment]
See also https://github.com/kubernetes/kubernetes/issues/22543#issuecomment-215833295

**Comment by eghobo** [comment]
@smarterclayton: any ideas about timeframe (1.7, 1.8, etc)?

**Comment by kargakis** [comment]
@eghobo daemonsets support rolling updates in the API since 1.6 and statefulsets are going to have it for 1.7 as per https://github.com/kubernetes/community/pull/503#issuecomment-298448147

**Comment by krmayankk** [comment]
@kargakis @kow3ns  for statefulsets, are we saying client side rolling update using kubectl will land in 1.7 ?

**Comment by kargakis** [comment]
@krmayankk it's going to be server-side. I've linked the proposal above, please have a look.

**Comment by jnicholls** [comment]
Can't wait for this feature!  Yay for no downtime in my statefulset!

**Comment by kargakis** [comment]
Although I think this issue is obsolete - DaemonSets support rolling upgrades since 1.6 and StatefulSets are going to get them in 1.7; both server-side.

**Comment by chrislovecnm** [comment]
@smarterclayton can we close this?
