### ISSUE TITLE
Common patterns in workload controllers

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#37563]
Brought up in @kubernetes/sig-apps today, there seems to be a great deal of common patterns between workload controllers (Deployments, DaemonSets, StatefulSets). Namely all three of them in one way or another need:

* upgrades (http://kubernetes.io/docs/user-guide/deployments/#updating-a-deployment, https://github.com/kubernetes/kubernetes/pull/31693, https://github.com/kubernetes/kubernetes/issues/28706)
* failure detection (https://github.com/kubernetes/kubernetes.github.io/pull/1699, https://github.com/kubernetes/kubernetes/issues/30206, https://github.com/kubernetes/kubernetes/issues/36482)
* the ability to rollback (either manually or automatically after a permanent failure has been detected - https://github.com/kubernetes/kubernetes/issues/23211)
* historical info per se (changeset of my app)
* a policy for cleaning up history 
* user-extensible strategies (https://github.com/kubernetes/kubernetes/issues/14510)

Even more features that could possibly make sense for all of the workload controllers can be found in https://github.com/kubernetes/community/wiki/Roadmap:-Deployment

This issue serves for discussing similarities, differences, what makes sense for all three controllers, and what can we do in order to be consistent across all wherever it is possible.

**Comment by krmayankk** [comment]
Is this also about code reuse ?

**Comment by kargakis** [comment]
Certainly code reuse is nice to have but this issue is more about api consistency across the controllers.

**Comment by AdoHe** [comment]
@kargakis any progress on this?

**Comment by kargakis** [comment]
For 1.6, we added DaemonSet upgrades.

**Comment by kargakis** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/issues/42752
