### ISSUE TITLE
Handle updates, rolling update preferences and revisions in federated deployment controller

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#37570]
... in a more consistent way, especially when looking from the cross-cluster perspective. Currently there is no rolling update subresource, sub-deployments may have different revision numbers, max surge/max unavailable are handled separately in each cluster, etc.

cc: @madhusudancs @nikhiljindal

**Comment by nikhiljindal** [comment]
> no rolling update subresource

We do have the /rollback subresource in federation-apiserver: https://github.com/kubernetes/kubernetes/blob/98ae5722251f5f88474af1a0d91b3244844fa9f6/federation/cmd/federation-apiserver/app/extensions.go#L50. Need tests for it.

**Comment by ethernetdan** [comment]
Moving to 1.7 because too late for 1.6. Feel free to move back if this is incorrect.

**Comment by marun** [comment]
I'm assuming this shouldn't be blocking 1.7.

**Comment by quinton-hoole** [comment]
According to #39987, @perotinus will work on this. Assigning accordingly.

**Comment by perotinus** [comment]
/unassign perotinus

I'm not working on this at the moment.

**Comment by quinton-hoole** [comment]
Required for GA.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#84.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
