### ISSUE TITLE
How kubectl explain and describe output could be improved for external consumers

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#37576]
I've checked out Visual Studio Code plugin that @brendandburns wrote, and it is pretty awesome!

I've considered how to improve rendering of it's `kubectl describe` and `kubectl explain` view, and realised that it would help a lot if these command could produce markdown or something similar. Also it'd be great to have some kind of pages separators, when output contains multiple items (probably only apply to `kubectl describe`).

**Comment by kargakis** [comment]
@kubernetes/kubectl @kubernetes/sig-cli

**Comment by smarterclayton** [comment]
The tentative plan is to move describe to the server side and have the server present a structured response that is somewhat generic for many clients.  See https://github.com/kubernetes/kubernetes/pull/33900 for some backstory.

**Comment by errordeveloper** [comment]
Closing in favour of #53224.
