### ISSUE TITLE
GCE PD unable to attach when node is upgraded to 1.5 from 1.4

### ISSUE THREAD

**Issue by rkouj** [kubernetes/kubernetes#37586]
**Is this a BUG REPORT or FEATURE REQUEST?** 
BUG REPORT

`Upgrade from 1.4 CVM to 1.5 CVM`

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
rkouj@rkouj0:~/go/src/k8s.io/kubernetes$ kubectl describe pods test-ipj93
Name:		test-ipj93
Namespace:	default
Node:		kubernetes-minion-group-yxra/10.128.0.3
Start Time:	Mon, 28 Nov 2016 14:39:28 -0800
Labels:		<none>
Status:		Pending
IP:		
Controllers:	<none>
Containers:
  busybox:
    Container ID:	
    Image:		busybox
    Image ID:		
    Port:		
    Command:
      sh
      -c
      while true; do echo $(date) >> /data/$(hostname)-$(date -d @$(cat /proc/stat | grep btime | cut -f 2 -d" ") | cut -f 4 -d" "); sleep 30; done
    QoS Tier:
      cpu:	Burstable
      memory:	BestEffort
    Requests:
      cpu:		100m
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Environment Variables:
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  data:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	test
    ReadOnly:	false
  default-token-kjoqg:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-kjoqg
Events:
  FirstSeen	LastSeen	Count	From					SubobjectPath			Type		Reason		Message
  ---------	--------	-----	----					-------------			--------	------		-------
  57m		57m		1	{default-scheduler }							Normal		Scheduled	Successfully assigned test-ipj93 to kubernetes-minion-group-yxra
  57m		57m		1	{kubelet kubernetes-minion-group-yxra}	spec.containers{busybox}	Normal		Pulling		pulling image "busybox"
  57m		57m		1	{kubelet kubernetes-minion-group-yxra}	spec.containers{busybox}	Normal		Pulled		Successfully pulled image "busybox"
  57m		57m		1	{kubelet kubernetes-minion-group-yxra}	spec.containers{busybox}	Normal		Created		Created container with docker id 6cd98c606699; Security:[seccomp=unconfined]
  57m		57m		1	{kubelet kubernetes-minion-group-yxra}	spec.containers{busybox}	Normal		Started		Started container with docker id 6cd98c606699
  47m		47m		6	{kubelet kubernetes-minion-group-yxra}					Warning		FailedMount	MountVolume.SetUp failed for volume "kubernetes.io/secret/8586f1e2-b5bb-11e6-bab0-42010a800002-default-token-kjoqg" (spec.Name: "default-token-kjoqg") pod "8586f1e2-b5bb-11e6-bab0-42010a800002" (UID: "8586f1e2-b5bb-11e6-bab0-42010a800002") with: Get https://kubernetes-master/api/v1/namespaces/default/secrets/default-token-kjoqg: dial tcp: lookup kubernetes-master on 169.254.169.254:53: no such host
  46m		46m		1	{kubelet kubernetes-minion-group-yxra}					Warning		FailedMount	MountVolume.SetUp failed for volume "kubernetes.io/secret/8586f1e2-b5bb-11e6-bab0-42010a800002-default-token-kjoqg" (spec.Name: "default-token-kjoqg") pod "8586f1e2-b5bb-11e6-bab0-42010a800002" (UID: "8586f1e2-b5bb-11e6-bab0-42010a800002") with: Get https://kubernetes-master/api/v1/namespaces/default/secrets/default-token-kjoqg: dial tcp 10.128.0.2:443: i/o timeout
  45m		45m		1	{kubelet kubernetes-minion-group-yxra}					Warning		FailedMount	MountVolume.SetUp failed for volume "kubernetes.io/secret/8586f1e2-b5bb-11e6-bab0-42010a800002-default-token-kjoqg" (spec.Name: "default-token-kjoqg") pod "8586f1e2-b5bb-11e6-bab0-42010a800002" (UID: "8586f1e2-b5bb-11e6-bab0-42010a800002") with: Get https://kubernetes-master/api/v1/namespaces/default/secrets/default-token-kjoqg: dial tcp 10.128.0.2:443: getsockopt: connection refused
  11m		11m		2	{controller-manager }							Warning		FailedMount	Failed to attach volume "test" on node "kubernetes-minion-group-yxra" with: error getting instance "kubernetes-minion-group-yxra"
  9m		9m		1	{kubelet kubernetes-minion-group-yxra}					Warning		FailedSync	Error syncing pod, skipping: network is not ready: [Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]
  9m		9m		2	{kubelet kubernetes-minion-group-yxra}					Warning		FailedSync	Error syncing pod, skipping: network is not ready: [Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]
  6m		14s		4	{kubelet kubernetes-minion-group-yxra}					Warning		FailedMount	Unable to mount volumes for pod "test-ipj93_default(8586f1e2-b5bb-11e6-bab0-42010a800002)": timeout expired waiting for volumes to attach/mount for pod "test-ipj93"/"default". list of unattached/unmounted volumes=[data]
  6m		14s		4	{kubelet kubernetes-minion-group-yxra}					Warning		FailedSync	Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "test-ipj93"/"default". list of unattached/unmounted volumes=[data]

**What you expected to happen**:
GCE PD to attach and mount successfully post the upgrade

**How to reproduce it** (as minimally and precisely as possible):
Running the upgrade steps in the doc for upgrade of manual test from 1.4 to 1.5

**Anything else do we need to know**:

**Comment by rkouj** [comment]
Ran the upgrade again.
This time the `pod is being deleted`.
https://gist.github.com/rkouj/44682827eb2f760257f6c4b0b1f8c8ab

**Comment by rkouj** [comment]
kube-controller-manager.log

https://gist.github.com/rkouj/79b93ccf3b9d49dbd9e4c1b684a1af42

**Comment by saad-ali** [comment]
Current theory is because kubelet deletes and recreates the node API object during upgrade (because externalID changed), see https://github.com/kubernetes/kubernetes/blob/release-1.5/pkg/kubelet/kubelet_node_status.go#L112 the new object does not contain the correct status (it is written by the Attach/Detach controller to the old object but not subseqently updated).

If this proves to be the issue, the proposed fix is to force the attach/detach controller to update the node status when the node's external ID changes.

@rkouj is working to verify this theory by executing this code path (without a full upgrade). Once he has validated the theory, he will work on the fix, verify it, merge it to master, and get it cherry-picked to 1.5.

**Comment by dims** [comment]
@rkouj : is https://github.com/kubernetes/kubernetes/pull/37727 expected to fix this problem?

**Comment by rkouj** [comment]
@dims : Yes
