### ISSUE TITLE
Bazel: pkg/util/sets/BUILD fails when running external, in another Bazel repository

### ISSUE THREAD

**Issue by sayrer** [kubernetes/kubernetes#37598]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

"bazel"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug Report

**Kubernetes version** (use `kubectl version`):

1.5 beta2 (source)

**How to reproduce it** (as minimally and precisely as possible):

Use github.com/kubernetes/kubernetes as a git_repository in another Bazel project. The "set-gen" genrule in pkg/util/sets/BUILD will fail because its "--input-dirs" argument assumes some things about the path it is operating on. It works fine in the kubernetes tree, but the paths will have "external/" prepended to them when imported into another project. The "--go-header-file" argument works fine because it uses $location.

**Anything else do we need to know**:

I fixed this here by doing some path-chopping in bash, but the solution is ugly:

https://github.com/sayrer/kubernetes/blob/4d14457d6297ab98ca46c75601195cd9d67eb339/pkg/util/sets/BUILD#L43

@mikedanese

**Comment by drigz** [comment]
I've run into this as well. You can also workaround it by just [deleting the genrule](https://github.com/drigz/kubernetes/commit/ada44135cbf66ca66657efb1de973f6964559338), since the outputs are checked in.

As far as I'm aware, `$$(dirname $(location ...))` is the best approach for the more complicated genrules. It could possibly be simplified by using `@D` for `--output-base`, although I haven't tested this.

**Comment by ash2k** [comment]
Duplicated by #50975.

**Comment by ash2k** [comment]
Ref https://github.com/kubernetes/apimachinery/issues/30

**Comment by alisondy** [comment]
/remove-lifecycle stale
Running into this issue aswell.

**Comment by GauntletWizard** [comment]
/reopen 

This is still an issue as of 1.11.6. My workspace:
```
K8S_VERSION = "1.11.6"

go_repository(
    name = "io_k8s_api",
    tag = "kubernetes-%s" % K8S_VERSION,
    importpath = "k8s.io/api",
    build_file_proto_mode = "disable",
)

go_repository(
    name = "io_k8s_apimachinery",
    tag = "kubernetes-%s" % K8S_VERSION,
    importpath = "k8s.io/apimachinery",
    build_file_proto_mode = "disable",
)

go_repository(
    name = "io_k8s_kubernetes",
    tag = "v%s" % K8S_VERSION,
    importpath = "k8s.io/kubernetes",
    build_file_proto_mode = "disable",
)
```

Error I receive:
```
bazel build @io_k8s_kubernetes//test/e2e:go_default_library
INFO: Analysed target @io_k8s_kubernetes//test/e2e:go_default_library (0 packages loaded).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_dq1y/d2948b0c545b0945326512584f22b9a6/external/io_k8s_kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets/BUILD:23:1: error executing shell command: '/bin/bash -c set -e
export GO_GENRULE_EXECROOT=$(pwd)
export GOPATH=$GO_GENRULE_EXECROOT/bazel-out/darwin-fastbuild/bin/external/io_k8s_kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets/set-gen~g...' failed (Exit 1)
E1226 13:00:57.755631   22838 main.go:51] Error: Failed making a parser: unable to add directory "./vendor/k8s.io/apimachinery/pkg/util/sets/types": unable to import "./vendor/k8s.io/apimachinery/pkg/util/sets/types": cannot find package "./vendor/k8s.io/apimachinery/pkg/util/sets/types" in:
	/private/var/tmp/_bazel_dq1y/d2948b0c545b0945326512584f22b9a6/sandbox/darwin-sandbox/3/execroot/__main__/vendor/k8s.io/apimachinery/pkg/util/sets/types
Target @io_k8s_kubernetes//test/e2e:go_default_library failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.490s, Critical Path: 1.62s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by ixdy** [comment]
@GauntletWizard can you try again with kubernetes 1.12+? #64122 may have helped with this, but it didn't make it into the kubernetes 1.11 branch.
