### ISSUE TITLE
Unable to mount secrets for 1.4 to 1.5 upgrade

### ISSUE THREAD

**Issue by rkouj** [kubernetes/kubernetes#37596]
Manual upgrade tests for `1.4 CVM to 1.5 CVM`

**Environment**: GCE

After upgrading the master from 1.4 to 1.5, I see that the secrets are unable to mount with the upgrade.

Command I ran:
`cluster/gce/upgrade.sh -M v1.5.0-beta.2`

from the `1.5 branch`

https://docs.google.com/document/d/19Q4AzWLD5jd2FNaPyKy2xdTN4JIGUUpvwDwg0tcBkyc/edit#

rkouj@rkouj0:~/go/src/k8s.io/kubernetes$ kubectl describe pods
Name:		test-lj8z8
Namespace:	default
Node:		kubernetes-minion-group-j1g5/10.128.0.5
Start Time:	Mon, 28 Nov 2016 17:42:56 -0800
Labels:		<none>
Status:		Running
IP:		10.244.2.4
Controllers:	<none>
Containers:
  busybox:
    Container ID:	docker://c7116a07ef4b6e686431cfcc9608fb053b2c96a005cea9305045ec011e404a43
    Image:		busybox
    Image ID:		docker://sha256:e02e811dd08fd49e7f6032625495118e63f597eb150403d02e3238af1df240ba
    Port:		
    Command:
      sh
      -c
      while true; do echo $(date) >> /data/$(hostname)-$(date -d @$(cat /proc/stat | grep btime | cut -f 2 -d" ") | cut -f 4 -d" "); sleep 30; done
    QoS Tier:
      cpu:	Burstable
      memory:	BestEffort
    Requests:
      cpu:		100m
    State:		Running
      Started:		Mon, 28 Nov 2016 17:43:14 -0800
    Ready:		True
    Restart Count:	0
    Environment Variables:
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	True 
  PodScheduled 	True 
Volumes:
  data:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	test
    ReadOnly:	false
  default-token-aptiz:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-aptiz
Events:
  FirstSeen	LastSeen	Count	From					SubobjectPath			Type		Reason		Message
  ---------	--------	-----	----					-------------			--------	------		-------
  15m		15m		1	{default-scheduler }							Normal		Scheduled	Successfully assigned test-lj8z8 to kubernetes-minion-group-j1g5
  15m		15m		1	{kubelet kubernetes-minion-group-j1g5}	spec.containers{busybox}	Normal		Pulling		pulling image "busybox"
  15m		15m		1	{kubelet kubernetes-minion-group-j1g5}	spec.containers{busybox}	Normal		Pulled		Successfully pulled image "busybox"
  15m		15m		1	{kubelet kubernetes-minion-group-j1g5}	spec.containers{busybox}	Normal		Created		Created container with docker id c7116a07ef4b; Security:[seccomp=unconfined]
  15m		15m		1	{kubelet kubernetes-minion-group-j1g5}	spec.containers{busybox}	Normal		Started		Started container with docker id c7116a07ef4b
  10m		10m		3	{kubelet kubernetes-minion-group-j1g5}					Warning		FailedMount	MountVolume.SetUp failed for volume "kubernetes.io/secret/26cb4949-b5d5-11e6-920d-42010a800002-default-token-aptiz" (spec.Name: "default-token-aptiz") pod "26cb4949-b5d5-11e6-920d-42010a800002" (UID: "26cb4949-b5d5-11e6-920d-42010a800002") with: Get https://kubernetes-master/api/v1/namespaces/default/secrets/default-token-aptiz: dial tcp: lookup kubernetes-master on 169.254.169.254:53: no such host
  10m		10m		1	{kubelet kubernetes-minion-group-j1g5}					Warning		FailedMount	MountVolume.SetUp failed for volume "kubernetes.io/secret/26cb4949-b5d5-11e6-920d-42010a800002-default-token-aptiz" (spec.Name: "default-token-aptiz") pod "26cb4949-b5d5-11e6-920d-42010a800002" (UID: "26cb4949-b5d5-11e6-920d-42010a800002") with: Get https://kubernetes-master/api/v1/namespaces/default/secrets/default-token-aptiz: dial tcp 10.128.0.2:443: i/o timeout
  10m		9m		4	{kubelet kubernetes-minion-group-j1g5}					Warning		FailedMount	MountVolume.SetUp failed for volume "kubernetes.io/secret/26cb4949-b5d5-11e6-920d-42010a800002-default-token-aptiz" (spec.Name: "default-token-aptiz") pod "26cb4949-b5d5-11e6-920d-42010a800002" (UID: "26cb4949-b5d5-11e6-920d-42010a800002") with: Get https://kubernetes-master/api/v1/namespaces/default/secrets/default-token-aptiz: dial tcp 10.128.0.2:443: getsockopt: connection refused

**Comment by saad-ali** [comment]
CC @kubernetes/sig-storage

**Comment by rkouj** [comment]
Controller log file:

https://gist.github.com/rkouj/6a7bd80be7b92224d84667a545da13c1

**Comment by rkouj** [comment]
I did the upgrade again and `did not` see the issue. Not sure if it was a one off thing.

**Comment by rkouj** [comment]
rkouj@rkouj0:~/go/src/k8s.io/kubernetes$ kubectl describe pods
Name:		test-zga9j
Namespace:	default
Node:		kubernetes-minion-group-2lyw/10.128.0.5
Start Time:	Mon, 28 Nov 2016 20:06:23 -0800
Labels:		<none>
Status:		Running
IP:		10.244.1.4
Controllers:	<none>
Containers:
  busybox:
    Container ID:	docker://fa044f2ea997566004cd3f069d0bc5753a54eb2b67d6925bdb2c6ce31296911a
    Image:		busybox
    Image ID:		docker://sha256:e02e811dd08fd49e7f6032625495118e63f597eb150403d02e3238af1df240ba
    Port:		
    Command:
      sh
      -c
      while true; do echo $(date) >> /data/$(hostname)-$(date -d @$(cat /proc/stat | grep btime | cut -f 2 -d" ") | cut -f 4 -d" "); sleep 30; done
    QoS Tier:
      memory:	BestEffort
      cpu:	Burstable
    Requests:
      cpu:		100m
    State:		Running
      Started:		Mon, 28 Nov 2016 20:06:41 -0800
    Ready:		True
    Restart Count:	0
    Environment Variables:
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	True 
  PodScheduled 	True 
Volumes:
  data:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	test
    ReadOnly:	false
  default-token-ixn0n:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-ixn0n
Events:
  FirstSeen	LastSeen	Count	From					SubobjectPath			Type		Reason		Message
  ---------	--------	-----	----					-------------			--------	------		-------
  8m		8m		1	{default-scheduler }							Normal		Scheduled	Successfully assigned test-zga9j to kubernetes-minion-group-2lyw
  8m		8m		1	{kubelet kubernetes-minion-group-2lyw}	spec.containers{busybox}	Normal		Pulling		pulling image "busybox"
  8m		8m		1	{kubelet kubernetes-minion-group-2lyw}	spec.containers{busybox}	Normal		Pulled		Successfully pulled image "busybox"
  8m		8m		1	{kubelet kubernetes-minion-group-2lyw}	spec.containers{busybox}	Normal		Created		Created container with docker id fa044f2ea997; Security:[seccomp=unconfined]
  8m		8m		1	{kubelet kubernetes-minion-group-2lyw}	spec.containers{busybox}	Normal		Started		Started container with docker id fa044f2ea997

**Comment by rkouj** [comment]
https://gist.github.com/rkouj/2205033947b1f9ab3d7711bbb59b6c92

**Comment by dims** [comment]
@rkouj @saad-ali : needs an assignee!

**Comment by saad-ali** [comment]
@jingxu97 Can you investigate when you have some bandwidth CC @matchstick

**Comment by rkouj** [comment]
Ran into this again.
https://gist.github.com/rkouj/ee79890132a87c194b9830cf3c75c758

**Comment by jingxu97** [comment]
The error message is transient because at that time master is not available. The pod is in running state. Close the issue
