### ISSUE TITLE
pod disruption budgets cannot handle concurrent requests

### ISSUE THREAD

**Issue by ymqytw** [kubernetes/kubernetes#37605]
**What happened**:
When I try to test `kubectl drain` after implementing the 1st approach according to https://github.com/kubernetes/kubernetes/issues/37460#issuecomment-263437516, I found pod disruption budgets cannot handle concurrent requests.

The error message is:
```
Error from server (Conflict): Operation cannot be fulfilled on poddisruptionbudgets.policy "my-db": the object has been modified; please apply your changes to the latest version and try again
```
```
server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "Operation cannot be fulfilled on poddisruptionbudgets.policy \"my-db\": the object has been modified; please apply your changes to the latest version and try again",
  "reason": "Conflict",
  "details": {
    "name": "my-db",
    "group": "policy",
    "kind": "poddisruptionbudgets"
  },
  "code": 409
}]
```
It is an Optimistic Lock error message. It means PDB can't handle concurrent requests.

**How to reproduce it** (as minimally and precisely as possible):
1) Create a deployment with 6 replicas and schedule them to the same node, say node A. You can leave only one node scheduling enabled, and then create the deployment.
2) Create the PDB that match the deployment's label
3) Uncordon another node, say node B
4) Drain node A using concurrent POST eviction requests. Ref: #37604

@davidopp I'm not sure if this behavior is OK for PDB.
I think I can make `drain` work by waiting for a while if current pod label(s) match previous pod label(s).

**Comment by kargakis** [comment]
Or use PATCH?

**Comment by davidopp** [comment]
Yes, PATCH should work also.

I haven't written code that uses PATCH, so I can't advise exactly the code to write here (there are examples by grepping for patch, but I'm not sure exactly what is the right way to do it from inside of API server code, which is where we are here).

@ymqytw can you do a PR to implement this, either using the approach I described above or using PATCH? I think this is important to get into 1.5.

**Comment by ymqytw** [comment]
I think PATCH may NOT be safe here.
For example:
1) current pdb `PodDisruptionsAllowed = 5`
2) creating eviction A: get `PodDisruptionsAllowed = 5`
3) creating eviction B: get `PodDisruptionsAllowed = 5`
4) creating eviction A: PATCH pdb `PodDisruptionsAllowed = 4`
5) creating eviction B: PATCH pdb `PodDisruptionsAllowed = 4`
6) pdb's `PodDisruptionsAllowed = 4`. It's wrong.

Retry loop make more sense to me.

**Comment by davidopp** [comment]
Good point! You're right.

Retry loop should be OK.

**Comment by ymqytw** [comment]
> @ymqytw can you do a PR to implement this, either using the approach I described above or using PATCH? I think this is important to get into 1.5.

I can help to create a PR using retry loop.

**Comment by saad-ali** [comment]
@ymqytw @davidopp Could you please triage this for 1.5 and apply blocker or non-blocker labels as appropriate along with priority.

**Comment by davidopp** [comment]
Done.

**Comment by calebamiles** [comment]
@davidopp @ymqytw, who is actually working on this issue? Could one of you set yourselves as an assignee for this issue? Thanks!

**cc: @saad-ali, @dims**

**Comment by dims** [comment]
retry logic with PR https://github.com/kubernetes/kubernetes/pull/37668 needs reviews/lgtm
