### ISSUE TITLE
Kubelet: add events for all container life cycle changes

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#37616]
We only report Created/Started events for containers today. Having informational events for all container life cycle changes is very useful. For example, it could help to get OOM events more efficiently (#37141).

cc @kubernetes/sig-node

**Comment by andyxning** [comment]
@feiskyer 

* I will first learn existing logic for reporting pod/container Created/Started events. What i desired is we should make it general enough to adjust for docker and rkt container engine for now. Which is similar with [PLEG](https://github.com/kubernetes/kubernetes/pull/13571) which is implemented in #13571
