### ISSUE TITLE
local-up-cluster script is not generating apiserver key/cert 

### ISSUE THREAD

**Issue by Pensu** [kubernetes/kubernetes#37618]
I am trying to get a local cluster up running ./hack/local-uo-cluster.sh script. I am getting this error:

```
Waiting for etcd to come up.
+++ [1129 00:48:41] On try 2, etcd: : http://127.0.0.1:2379
{"action":"set","node":{"key":"/_test","value":"","modifiedIndex":4,"createdIndex":4}}
Waiting for apiserver to come up
!!! [1129 00:48:51] Timed out waiting for apiserver:  to answer at https://localhost:6443/api/v1/pods; tried 10 waiting 1 between each
Cleaning up...

```
Here is the log message:
```
cat /tmp/kube-apiserver.log
error: unable to read certificate-authority /var/run/kubernetes/apiserver.crt for local due to open /var/run/kubernetes/apiserver.crt: no such file or directory

```
I tried to look, the directory is there, but there is no certificate-authority or key file. Looks like the script is not generating keys for apiserver or is there something that I am missing here? TIA.

**Comment by euank** [comment]
A few bugs with the script (including an error that would have this result if `cfssl` was only in your non-sudo path) have been fixed.

Does this work for you now? If it doesn't, can you add `set -x` and the top of the script and post the full logs of running it?

**Comment by Pensu** [comment]
Yeah, it does, the issue was with cfssl only. Closing this.
