### ISSUE TITLE
Add shorthands for common flags

### ISSUE THREAD

**Issue by wernight** [kubernetes/kubernetes#37621]
I'm constantly using two flags which have no shorthand (and by constantly I mean typing them many times a day each day):

 - `--context`
 - `--namespace`

Can we have `-c` for `--context` and `-n` for `--namespace`? Or may be even support another notation like:

    $ kubectl [[context] namespace] COMMAND ...

**Comment by sakshamsharma** [comment]
Using the latest source, I can verify that running `kubectl options` shows that `--namespace` has the alternative of `-n`. I didn't know  of this one either.
`--context` still does not have a shorthand.

Git blame brought me to this issue #24078 and [this commit](https://github.com/silasbw/kubernetes/commit/39a9ec3a4f430789f917a12432cfd27ca96588ac) regarding the namespace change. You must be on a build older than August 15.

**Comment by wernight** [comment]
`-n` for namespace is really a huge improvement (the biggest), thanks for find that out.
