### ISSUE TITLE
FlexVolume not appearing to call unmount on a simple volume

### ISSUE THREAD

**Issue by mccormd** [kubernetes/kubernetes#37626]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

Yes - problems using the FlexVolume 
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): flexvolume unmount
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.4.6
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6+coreos.0", GitCommit:"ec2b52fabadf824a42b66b6729fe4cff2c62af8c", GitTreeState:"clean", BuildDate:"2016-11-14T19:42:00Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**: 
CoreOS

- **Cloud provider or hardware configuration**: 
local vagrant
- **OS** (e.g. from /etc/os-release): 
NAME=CoreOS
ID=coreos
VERSION=1235.0.0
VERSION_ID=1235.0.0
BUILD_ID=2016-11-17-0416
PRETTY_NAME="CoreOS 1235.0.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

- **Kernel** (e.g. `uname -a`): 
Linux w1 4.8.6-coreos #1 SMP Thu Nov 17 04:07:44 UTC 2016 x86_64 Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz GenuineIntel GNU/Linux

- **Install tools**:
https://github.com/coreos/coreos-kubernetes

- **Others**:

**What happened**:
I added a FlexVolume driver having looked at the example here https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/flexvolume
After experiencing issues with my driver I reverted it to a skeletal test driver to simply print out calls inbound (please see attached 'skel' script)
[skel.txt](https://github.com/kubernetes/kubernetes/files/619184/skel.txt)

When I test my pod with my volume and the steps below it will init and mount ok but there seems to be no call made to unmount when I test deleting the pod.

**What you expected to happen**:
When starting a pod with a the flex volume we should see a log that the mount was called and when I delete the pod I should see a log file entry for the unmount showing that my drivers unmount function has been called.  

$ cat /tmp/skel.log
Running init
Running mount on path /var/lib/kubelet/pods/c58d27e7-b62f-11e6-b279-080027126f56/volumes/zopa.com\~splunk/test on {"kubernetes.io/fsType":"ext4","kubernetes.io/readwrite":"rw"}
Running umount with path /var/lib/kubelet/pods/c58d27e7-b62f-11e6-b279-080027126f56/volumes/zopa.com\~splunk/test

**How to reproduce it** (as minimally and precisely as possible):

Add the plugin to the kubelet $VOLUME_PLUGIN_DIR/zopa.com~skel/skel then start the pod: -
[skeltest.yaml.txt](https://github.com/kubernetes/kubernetes/files/619275/skeltest.yaml.txt)

**Anything else do we need to know**:

See here for filtered kubelet -v 5 logs from the creation of the test pod and it's deletion and the logs to /tmp/skel.log
[skel_logs.txt](https://github.com/kubernetes/kubernetes/files/619269/skel_logs.txt)

**Comment by mccormd** [comment]
@chakri-nelluri is this something you could advise about?

**Comment by mccormd** [comment]
I'm confused as to why neither 'unmount' nor 'detach' are called on the flexvol.

**Comment by mccormd** [comment]
Did some more digging into this and it seems that the kubelet has a number of expectations as to what a volume should look like, e.g. it should be in the mount list and have a device which is different from its enclosing directory.  This meant that my attempts to create volumes using mount -bind were failing the volume tests performed in the kubelet (not flex plugin).

I've now worked around the issue by using mount -o loop and a sparse file which satisfies the kubelet requirements and calls flex volume successfully.  The goal of this flexvolume is to provide some local storage for splunk logging which does not immediately get destroyed when a pod is deleted.
This is my implementation: 
[splunk.txt](https://github.com/kubernetes/kubernetes/files/621432/splunk.txt)

Regarding flex volumes - it might be good for the kubelet to delegate such tasks as determining if it is mounted to the plugin rather than performing its own tests?

**Comment by jingxu97** [comment]
cc @kubernetes/sig-storage

**Comment by rootfs** [comment]
@chakri-nelluri

**Comment by thockin** [comment]
@erictune this smells a lot like what we called "emptyHostDir" the other day

**Comment by chakri-nelluri** [comment]
@mccormd Sorry for the tardy response. I am on PTO and didn't get a chance to catch up on the emails.
Thank you for the feedback.
Today, we don't have a way to delegate isMountPoint check. I will make a note of it for the V2 proposal.

**Comment by chakri-nelluri** [comment]
@mccormd is it ok to close this issue?

**Comment by mccormd** [comment]
Sorry, this can be closed.
