### ISSUE TITLE
third party resources api selflinks missing forward slash

### ISSUE THREAD

**Issue by AndyMoore111** [kubernetes/kubernetes#37622]
Bug report

**Kubernetes version**

Client Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-beta.2", GitCommit:"0776eab45fe28f02bbeac0f05ae1a203051a21eb", GitTreeState:"clean", BuildDate:"2016-11-24T22:35:03Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-beta.2", GitCommit:"0776eab45fe28f02bbeac0f05ae1a203051a21eb", GitTreeState:"clean", BuildDate:"2016-11-24T22:30:23Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}

When you curl the api

`curl -s http://localhost:8080/apis/extensions/v1beta1/thirdpartyresources`

you get a list of third party resources, however their selflinks are missing a forward slash:

```      {
        "metadata": {
          "name": "cassandra.prsn.io",
          "labels": {
            "type": "ThirdPartyResource"
          },
          "resourceVersion": "383",
          "creationTimestamp": "2016-11-28T20:09:39Z",
          "selfLink": "/apis/extensions/v1beta1/thirdpartyresourcescassandra.prsn.io",
          "uid": "97f0e5c0-b5a6-11e6-b99d-06025fc0211f"
        },
        "description": "Cassandra ThirdPartyResource",
        "versions": [
          {
            "name": "v1"
          }
        ]
      },```

**Comment by AdoHe** [comment]
@AndyMoore111 fixed with #37686 , you may take a look.

**Comment by DirectXMan12** [comment]
This looks like it affects root scoped resources in general -- both custom ones (e.g. ServiceCatalog brokers, as noted in kubernetes-incubator/service-catalog#309) and "built-in" ones, like namespaces and nodes:

```bash
$ kubectl version
k version
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1756+8dfc9393455984", GitCommit:"8dfc9393455984173cafb0ed64fa0a632df32c98", GitTreeState:"clean", BuildDate:"2017-03-27T19:34:18Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1744+3414231672e59b", GitCommit:"3414231672e59b750fe135bdccc076eb3a72498d", GitTreeState:"clean", BuildDate:"2017-03-27T22:39:14Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
$ kubectl get ns default -o yaml
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: 2016-05-05T17:42:09Z
  name: default
  resourceVersion: "6"
  selfLink: /api/v1/namespacesdefault
  uid: b147b07b-12e8-11e6-9267-5254002b8d24
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

**Comment by DirectXMan12** [comment]
cc @kubernetes/sig-api-machinery-misc
