### ISSUE TITLE
`kubectl delete` needs to be made generic for graceful deletion

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#37637]
Currently kubectl delete does not handle graceful deletion for resources it does not recognize (just ignores `--grace-period`).  

Also, waiting for the object to be deleted (for the reaper, and for the legacy `--grace-period=0` support) needs to handle UID changes correctly.  That involves changes to the reaper to fetch the object prior to deletion and also knowing that it should wait (so a signature change to ReapResult).

**Comment by smarterclayton** [comment]
@deads2k because you did generic kubectl stuff and will nag me

**Comment by kargakis** [comment]
@kubernetes/kubectl

**Comment by AdoHe** [comment]
non cascade deletion ignores `timeout` and `grace-period`, shall we respect these all?

**Comment by smarterclayton** [comment]
Yes, they are both generic.  Priority on this isn't terribly high, but it is wrong.
