### ISSUE TITLE
Ability to specify a reviewer in the PR text

### ISSUE THREAD

**Issue by Crassirostris** [kubernetes/kubernetes#37644]
Sometimes it's very useful for a non-maintainer to be able to specify a reviewer for the PR.

Since non-maintainer cannot do it directly, it would be great to have a way to specify a handle in the PR text for a merge-bot to understand and assign the appropriate person. Maybe we could introduce it to the template?

CC @pwittrock @grodrigues3 @piosz

**Comment by grodrigues3** [comment]
Thanks for filing this.  These kinds of developer/contributor velocity are generally filed in the kubernetes/contrib repository.

And in this particular case, it's already in progress.

https://github.com/kubernetes/contrib/pull/1945

**Comment by Crassirostris** [comment]
@grodrigues3 OK, thank you very much!

**Comment by Crassirostris** [comment]
@grodrigues3 Sorry, I read the issue you mentioned again and it's not clear, does it allow for _me_ to specify the _other person_ as a reviewer?

**Comment by grodrigues3** [comment]
Yeah, the goal is to allow people to write

/assign Crassirostris and then if you in an OWNERS file and part of the org, the bot will assign you.

Does that make sense?

**Comment by Crassirostris** [comment]
@grodrigues3 Mmmm, for example in this quarter I used to have PRs with changes in the cluster/addons and cluster/saltbase directories, which does not include many people in OWNERS and certainly does not include @piosz who reviews my PRs. Does it mean that I wouldn't be able to use `/assign piosz`?

**Comment by wojtek-t** [comment]
@Crassirostris - if he won't be in owners for those directories, then yes - he won't be able to approve your PR.

**Comment by Crassirostris** [comment]
@grodrigues3 @wojtek-t OK, thanks, everything makes sense now!
