### ISSUE TITLE
PersistentVolume metadata.name is required to be lower case

### ISSUE THREAD

**Issue by lazzarello** [kubernetes/kubernetes#37654]
**Kubernetes version** (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:13:23Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- AWS

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
$ uname -a
Linux ip-10-8-1-99 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

- cluster bootstrapped with Kops

**What happened**:

I tried to create a PersistentVolume resource and I received the following error output

```
$ cat es-efs-volume.yml 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: Nfs
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: us-west-2a.fs-64738265.efs.us-west-2.amazonaws.com
    path: "/"

$ kubectl create -f es-efs-volume.yml
The PersistentVolume "Nfs" is invalid.
metadata.name: Invalid value: "Nfs": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)* (e.g. 'example.com')
```

**What you expected to happen**:

I am given a newly created PersistentVolume resource

**How to reproduce it** (as minimally and precisely as possible):

Create the resource with capital letters as the value for metadata.name

**Anything else do we need to know**:

The fact that this key requires all lower case characters in the name is not indicated by the error output. I only understood this was the error after reading through the whole regex. I am of the opinion that reading regexes to understand error output is not a nice task to expect all humans to perform. Also, why is the name being validated through a regex?

**Comment by xingzhou** [comment]
I'm curious why the name should be of lower case? if it's confirmed as a bug, I would like to provide a patch

**Comment by xingzhou** [comment]
I'd like to provide a PR on this error message improvement, instead of showing the regex, just show the naming rules to end-user.
