### ISSUE TITLE
RS won't delete due to orphan finalizer

### ISSUE THREAD

**Issue by robszumski** [kubernetes/kubernetes#37651]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
finalizer
orphan

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.3", GitCommit:"c6411395e09da356c608896d3d9725acab821418", GitTreeState:"clean", BuildDate:"2016-07-22T20:29:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5+coreos.0", GitCommit:"f70c2e5b2944cb5d622621a706bdec3d8a5a9c5e", GitTreeState:"clean", BuildDate:"2016-10-31T19:16:47Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: CoreOS Tectonic on AWS
- **OS** (e.g. from /etc/os-release): `CoreOS stable (1185.3.0)`
- **Kernel** (e.g. `uname -a`): `Linux ip-10-0-0-50.us-west-1.compute.internal 4.7.3-coreos-r2 #1 SMP Tue Nov 1 01:38:43 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz GenuineIntel GNU/Linux`
- **Install tools**: CoreOS Tectonic Installer (self-hosted cluster)
- **Others**:

**What happened**:
When deleting a ReplicaSet, the orphan parameter is populated, but the pods are never removed, blocking the RS from being deleted.

**What you expected to happen**:
RS is deleted

**How to reproduce it** (as minimally and precisely as possible):
Create a RS and attempt to delete it from either the UI or kubectl.

1. Create RS and spin up pods
2. Delete the RS
3. Delete will succeed, but the object will never disappear. The orphan parameter is applied to the object.
4. With `kubectl edit`, removing the orphan parameter will result in successful deletion.

**Anything else do we need to know**:
The Tectonic Console issues delete requests with `orphanDependents=false`. It seems like the orphan component is not running at all. I'm not sure where to best debug that or in which control loop it runs.

**Comment by caesarxuchao** [comment]
If this happens again, could you paste the output of `kubectl get pods -o yaml`? I want to see if the pods still have [ownerRefence](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L198) pointing to the replicaset. Thanks.

**Comment by caesarxuchao** [comment]
Also, how many pods did the rs have? How long had the rs stuck in that state before you manually ran `kubectl edit`?

**Comment by robszumski** [comment]
The pod ownership hasn't changed between:

1. list pods
2. delete RS
3. list pods

Here's what the ownership looks like:

```
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubernetes.io/created-by: |
        {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"stress","name":"load-generator-1930141919","uid":"feb77463-b01d-11e6-ab21-02b746b23592","apiVersion":"extensions","resourceVersion":"2252072"}}
    creationTimestamp: 2016-11-23T21:43:25Z
    generateName: load-generator-1930141919-
    labels:
      pod-template-hash: "1930141919"
      run: load-generator
    name: load-generator-1930141919-3uma5
    namespace: stress
    ownerReferences:
    - apiVersion: extensions/v1beta1
      controller: true
      kind: ReplicaSet
      name: load-generator-1930141919
      uid: feb77463-b01d-11e6-ab21-02b746b23592
    resourceVersion: "2252613"
    selfLink: /api/v1/namespaces/stress/pods/load-generator-1930141919-3uma5
    uid: dcc5e3ed-b1c5-11e6-ab21-02b746b23592
  spec:
    containers:
    - args:
      - /bin/sh
      image: busybox
      imagePullPolicy: Always
      name: load-generator
      resources: {}
      stdin: true
      terminationMessagePath: /dev/termination-log
      tty: true
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-hjpn6
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: ip-10-0-0-128.us-west-1.compute.internal
    restartPolicy: Always
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    volumes:
    - name: default-token-hjpn6
      secret:
        secretName: default-token-hjpn6
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2016-11-23T21:43:25Z
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: 2016-11-23T21:43:28Z
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: 2016-11-23T21:43:25Z
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://10e4ebfc54c44d4cf808a282f551fa0650c1475920d93e0903a7dba6270da055
      image: busybox
      imageID: docker://sha256:e02e811dd08fd49e7f6032625495118e63f597eb150403d02e3238af1df240ba
      lastState: {}
      name: load-generator
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: 2016-11-23T21:43:28Z
    hostIP: 10.0.0.128
    phase: Running
    podIP: 10.2.75.13
    startTime: 2016-11-23T21:43:25Z
- apiVersion: v1
  kind: Pod
  ...<snip>...
```

After `kubectl edit`, the ownership looks the same. I waited about 5 min for the pods to disappear.

After that time, the RS did delete, but the pod still exists with the same owner reference and isn't being cleaned up.

**Comment by caesarxuchao** [comment]
Could it be the controllers cannot connect to the apiserver? Do you happen to keep the apiserver log and controller manager log when the issue happens? Or is it easy to reproduce the bug?

**Comment by grodrigues3** [comment]
@robszumski are you able to reproduce, do you have the api logs?  If so, please reopen the issue
