### ISSUE TITLE
Ubuntu installation document not available

### ISSUE THREAD

**Issue by asifhj** [kubernetes/kubernetes#37682]
Hello Team -

Ubuntu installation is not available online.

http://kubernetes.io/docs/getting-started-guides/ubuntu/

404 Error!

Sorry, this page was not found. :(

Thanks Asif J.

**Comment by PI-Victor** [comment]
i think this belongs in https://github.com/kubernetes/kubernetes.github.io
see also [related docs issues](
https://github.com/kubernetes/kubernetes.github.io/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20ubuntu)
