### ISSUE TITLE
Tests jobs are failing silently

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#37689]
Lately I have seen many jobs failing silently like
```
@k8s-ci-robot Jenkins GCE Node e2e — Error starting build. 
```
without posting anything in the PR which makes rerunning tests difficult since the missing message contains the command I need to rerun the job.

@kubernetes/sig-testing @kubernetes/test-infra-maintainers

**Comment by kargakis** [comment]
Is there a doc somewhere about the commands that we need to run for failed jobs or is it just https://github.com/kubernetes/test-infra/blob/master/prow/jobs.yaml (kudos to @aveshagarwal for pointing it out to me)

**Comment by spxtr** [comment]
Sorry, I didn't see this when you opened it. In the future, please open these issues against test-infra.
