### ISSUE TITLE
Expose Kubelet logs via Kubelet `/logs` endpoint

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#37683]
Kubelet currently exposes all log files stored under `/var/log` directory on a node via its `/logs/` endpoint. This interface is very convenient for accessing kubelet and runtime logs remotely. 

However this interface requires log files to be available under `/var/log` directory.

Given that many deployments use journald today, it would be helpful if `/logs/` REST endpoint in kubelet can expose journal logs for a select subset of system services like kubelet and the runtime.

cc @kubernetes/sig-node

**Comment by vishh** [comment]
If there are no objections to extending the `/logs/` API functionality, I can post a patch for this.

**Comment by feiskyer** [comment]
+1

**Comment by cmluciano** [comment]
Was this added or is this issue looking for an owner?
