### ISSUE TITLE
Wrong kubernetes service port when not using SSL

### ISSUE THREAD

**Issue by inercia** [kubernetes/kubernetes#37699]
I started the kubernetes API server without SSL support (it is listening only at port `8080`)

```
$ ps ax | grep kube-apiserver
 7139 ?        Ssl    1:00 /usr/bin/kube-apiserver --logtostderr=true --v=0 --etcd-servers=http://127.0.0.1:2379 --advertise-address=10.0.0.6 --insecure-bind-address=0.0.0.0 --insecure-port=8080 --secure-port=0 --allow-privileged=true --service-cluster-ip-range=172.21.0.0/16 --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota --service-account-key-file=/var/lib/kubernetes/serviceaccount.key --runtime-config=api/all=true
```

but when looking for the kubernetes service, I see it is announced at `10.0.0.6:6443`

```
$ kubectl describe service --namespace=default  kubernetes
Name:			kubernetes
Namespace:		default
Labels:			component=apiserver
			provider=kubernetes
Selector:		<none>
Type:			ClusterIP
IP:			172.21.0.1
Port:			https	443/TCP
Endpoints:		10.0.0.6:6443
Session Affinity:	ClientIP
No events.
```

while this does not match the reality:

```
$ sudo netstat -lptun | grep apiserver
tcp        0      0 :::8080                 :::*                    LISTEN      7139/kube-apiserver 
```

Maybe I'm missing something, but I think the service port should be 8080, right?

I'm running this on OpenSUSE Leap, with

```
$ kube-apiserver --version
Kubernetes v1.3.10
```

**Comment by inercia** [comment]
Seems related to #15017

**Comment by spiffxp** [comment]
/assign
closing because this is expected, the internal 'kubernetes' service is always created as https, even if the API server is listening on http externally; you'd probably want to take a look at kube-proxy to see how it routes traffic to the internal kube-apiserver service
