### ISSUE TITLE
`make clean` needs Docker

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/kubernetes#37690]
That's a bit weird, but the `make clean` target in the root Makefile requires Docker.

```
# TODO(thockin): call clean_generated when we stop committing generated code.
.PHONY: clean
clean: clean_meta
	build-tools/make-clean.sh
	rm -rf $(OUT_DIR)
	rm -rf Godeps/_workspace # Just until we are sure it is gone
```

Indeed it calls `build-tools/make-clean.sh` which checks for prereq including Docker.

So if you are doing a local Go build *without* Docker, doing a subsequent `make clean` will need Docker.

I think `make` and `make clean` should be pure local Go build and clean.

Then `make release/quick-release` which do Docker build should be cleaned with another target like `make release-clean`...

the targets are all a bit confusing ...

**Comment by sebgoa** [comment]
see also #37079

**Comment by sebgoa** [comment]
or `make` should be Docker dependent and not a local Golang build.

**Comment by ixdy** [comment]
`make clean` should work if docker is not installed.

**Comment by sebgoa** [comment]
thanks a lot @ixdy for taking care of all these small issues. I think these details make a big difference for new comers...

I sent a _report_ to the contrib-ex mailing list.
