### ISSUE TITLE
Volume "inner name" is not correct for use in mount path, can cause collisions

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#37702]
I was reading https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_executor.go#L265 and https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_executor.go#L303 and it didn't sit right with me.  The path now includes names from two different sources, which means it can collide.  Can I make it collide?

TL;DR: yes, I can.  If you follow the below steps I can cause kubelet to mis-mount the volumes in a pod, possibly leading to data corruption for users. leaked attaches for the node, and leaked PVs and cloud disks.

@kubernetes/sig-storage 

Step 1: Make a PVClaim with a PV.  It doesn't matter if this is manually provisioned or automatic.  In this case I am using old-style automatic.

```
$ cat > mypvc.yaml << __EOF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  annotations:
    volume.alpha.kubernetes.io/storage-class: anything
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Gi
__EOF

$ kubectl create -f mypvc.yaml
```

Step 2: Get the PV that is bound to `mypvc`

```
$ kubectl get pvc myclaim -o go-template={{.spec.volumeName}}; echo
pvc-a1032d54-b71a-11e6-bedd-42010af00003
```

Step 3: Create a PersistentDisk in teh GCE control UI.  It doesn't matter what you call it.  Ic alled it "test".

Step 4: Run a pod that mounts both `mypvc` and `test` PDs.  I picked a specific `nodeName` for easier proof.

```
$ cat > pod-good.yaml << __EOF
apiVersion: v1
kind: Pod
metadata:
  name: pod-good
spec:
  nodeName: kubernetes-minion-group-jp30
  containers:
  - name: busybox
    image: busybox
    command:
    - sh
    - -c
    - while true; do sleep 3600; done
    volumeMounts:
    - name: mypvc
      mountPath: /vol/mypvc
    - name: mypd
      mountPath: /vol/mypd
  volumes:
  - name: mypvc
    persistentVolumeClaim:
      claimName: mypvc
  - name: mypd
    gcePersistentDisk:
      pdName: test
__EOF

$ kubectl create -f pod-good.yaml
```

Step 5: SSH to the node and look in /var/lib/kubelet/pods/{uid}/volumes/kubernetes.io~gce-pd.  This is all working as intended.

```
$ ls /var/lib/kubelet/pods/ce1e2875-b71c-11e6-bedd-42010af00003/volumes/kubernetes.io~gce-pd
mypd  pvc-a1032d54-b71a-11e6-bedd-42010af00003
```

Step 6: Tear down that pod and create trouble.  Specifically, name your manual PD the same name as the underlying PV to which `mypvc` was bound.

```
$ kubectl delete pod pod-good

$ cat > pod-bad.yaml << __EOF
apiVersion: v1
kind: Pod
metadata:
  name: pod-bad
spec:
  nodeName: kubernetes-minion-group-jp30
  containers:
  - name: busybox
    image: busybox
    command:
    - sh
    - -c
    - while true; do sleep 3600; done
    volumeMounts:
    - name: mypvc
      mountPath: /vol/mypvc
    - name: pvc-a1032d54-b71a-11e6-bedd-42010af00003
      mountPath: /vol/mypd
  volumes:
  - name: mypvc
    persistentVolumeClaim:
      claimName: mypvc
  - name: pvc-a1032d54-b71a-11e6-bedd-42010af00003
    gcePersistentDisk:
      pdName: test
__EOF

$ kubectl create -f pod-bad.yaml
```

Note that the ONLY thing that changed here is the pod name and the name of the PD volume block.

Step 7: SSH to the node and look in /var/lib/kubelet/pods/{uid}/volumes/kubernetes.io~gce-pd.  It's broken.

```
$ ls /var/lib/kubelet/pods/79f69496-b71c-11e6-bedd-42010af00003/volumes/kubernetes.io~gce-pd
pvc-a1032d54-b71a-11e6-bedd-42010af00003
```

It should have 2 dirs, but it only has 1.  If you write to the mounts within the pod, they are the same backing store - writes in one dir appear in the other.

Fundamentally the problem is that we used a name that is guaranteed unique within the pod (.spec.volumes[].name) and mixed it with a name that is guaranteed unique in another scope (all PVs).  We simply MUST NOT do this.  Ever.  In this case, it's unlikely that I would "accidentally" collide with an auto-provisioned name, but I could very easily collide with manually provisioned PVs.   The path `/var/lib/kubelet/pods/{uid}/volumes/*` must contain names from the pod's point of view.  The path `/var/lib/kubelet/plugins` is where plugin-specific names can live.

Kubelet seems to (from logs) pick one and ignore the other, but I wouldn't trust this behavior if it is accidental.  There does seem to be an event logged:

"FailedMount" says `Unable to mount volumes for pod "mypod-5_default(11a27117-b722-11e6-bedd-42010af00003)": timeout expired waiting for volumes to attach/mount for pod "mypod-5"/"default"`

and 

"FailedSync" says `Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "mypod-5"/"default"`

...but I find nothing in kubelet's logfile.

FINALLY, cleaning all this up, the PV seems to have leaked and is not being cleaned up.  Maybe I triggered a refcount issue in a controller - not surprising.  Logs:

```
I1130 17:41:39.524456       5 pv_controller.go:1155] isVolumeReleased[pvc-a1032d54-b71a-11e6-bedd-42010af00003]: volume is released
I1130 17:41:39.721225       5 gce_util.go:63] Error deleting GCE PD volume kubernetes-dynamic-pvc-a1032d54-b71a-11e6-bedd-42010af00003: googleapi: Error 400: The disk resource 'kubernetes-dynamic-pvc-a1032d54-b71a-11e6-bedd-42010af00003' is already being used by 'kubernetes-minion-group-jp30', resourceInUseByAnotherResource
```

The "test" volume was detached but the auto-provisioned one was not.  Rectification failure.

Update: a few minutes later:

```
I1130 17:45:30.518982       5 reconciler.go:172] Started DetachVolume for volume "kubernetes.io/gce-pd/kubernetes-dynamic-pvc-a1032d54-b71a-11e6-bedd-42010af00003" from node "kubernetes-minion-group-jp30". This volume is not safe to detach, but maxWaitForUnmountDuration 6m0s expired, force detaching
I1130 17:45:32.021565       5 attacher.go:127] VolumesAreAttached: check volume "kubernetes-dynamic-pvc-a1032d54-b71a-11e6-bedd-42010af00003" (specName: "mypv") is no longer attached
I1130 17:45:32.021664       5 operation_executor.go:564] VerifyVolumesAreAttached determined volume "kubernetes.io/gce-pd/kubernetes-dynamic-pvc-a1032d54-b71a-11e6-bedd-42010af00003" (spec.Name: "mypv") is no longer attached to node %!q(MISSING), therefore it was marked as detached.
I1130 17:45:34.079203       5 operation_executor.go:699] DetachVolume.Detach succeeded for volume "kubernetes.io/gce-pd/kubernetes-dynamic-pvc-a1032d54-b71a-11e6-bedd-42010af00003" (spec.Name: "mypv") from node "kubernetes-minion-group-jp30".
I1130 17:45:39.530962       5 pv_controller.go:1155] isVolumeReleased[pvc-a1032d54-b71a-11e6-bedd-42010af00003]: volume is released
I1130 17:45:42.975547       5 gce_util.go:68] Successfully deleted GCE PD volume kubernetes-dynamic-pvc-a1032d54-b71a-11e6-bedd-42010af00003
I1130 17:45:42.975595       5 pv_controller.go:1191] volume "pvc-a1032d54-b71a-11e6-bedd-42010af00003" deleted
```

So the volume was eventually force-detached, which is OK here since it never mounted, but sort of scary.

**Comment by eparis** [comment]
I haven't reproduced to check, but are they actually both getting mounted? just one on top of the other?  would have to check /proc/mounts....

**Comment by thockin** [comment]
No, only one appears to be mounted, though both are attached.

**Comment by jingxu97** [comment]
I have to say the InnerVolumeSpecName and outerVolumeSpecName names had confused me for a while. As @thockin pointed out, the InnerVolumeSpecName could collide between different volumes for the same pod and currently this name is used for constructing the mounting path. 

I can think of two options for fixing this
1. Use unique volume name (constructed from pd name, disk id etc) instead of InnerVolumeSpecName for constructing the mount path. This is a clean way to fix the problem and also make it easier to recover the unique volume name which is needed for volume reconstruction process when kubelet restarts. The problem is that the backward comparability and more code change.
2. Check the whether the InnerVolumeSpecName is unique during volume setup and return error if they are not and fail to mount operation. User can choose to change the volume name to avoid collision. This will add some overhead for checking the uniqueness of the volumes names.

Please let me know any comments/suggestions. Thanks!

**Comment by saad-ali** [comment]
This is all legacy pre-1.0 naming that we're stuck with. We've wanted to get rid of it for a while but backwards compatibility need to be carefully considered. We'll have to support "old" and "new" mount paths for a long time.

**Comment by saad-ali** [comment]
> This is all legacy pre-1.0 naming that we're stuck with. We've wanted to get rid of it for a while but backwards compatibility need to be carefully considered. We'll have to support "old" and "new" mount paths for a long time.

CC @kubernetes/sig-storage We can consider this for 1.6

**Comment by eparis** [comment]
I can't think of a malicious action here. If we can think of one, that's a great excuse^Wreason to fix names along the way

**Comment by thockin** [comment]
Jing,

I think your #2 is a bad option - we should not expose users to conflicts
that are not caused by themselves, but read on.  #1 is viable, though
naively the name of the dir under .../{pod}/volumes/{plugin} should just be
the `name` of volume struct in the pod.  If we need more info to rebuild
state, we should save that somewhere else.

Live compat is a real issue, and I don't see a way to change this without
effectively having the logic "fall back" on the old names.  I don't know
that we will be able to get rid of that compat for literally O(years) if
ever.

This is a relatively low-prio bug, as ugly as it is.  It requires you to
use the same driver in both "legacy" mode and through a PVClaim, at the
same time in the same pod *and* to hit the conflict.  Kubelet doesn't do
anything bad except to the pod in question, and rectification catches up
and fixes things eventually.  So maybe your #1 is not as bad as the
alternative?
