### ISSUE TITLE
upgrade.sh does not change node version properly

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#37715]
See
https://groups.google.com/d/msg/kubernetes-dev/C8s1boeUCZ4/gju__NuJCgAJ
and subsequent messages in that thread.

**Comment by mtaufen** [comment]
This is quite strange - also strange that hardcoding the value in config-default.sh does not seem to have an effect on the upgrade script. Continuing to investigate.

**Comment by davidopp** [comment]
BTW the tl;dr on the problem (for those who don't want to go through the thread) is that the KUBE_NODE_OS_DISTRIBUTION env var is supposed to tell upgrade.sh what node image type to use when you also pass the -o flag, but it doesn't seem to work.

**Comment by krousey** [comment]
This is also affecting the automated GCE upgrade tests, but not the automated GKE upgrade tests.

```console
== Post-Upgrade Node OS and Kubelet Versions ==
name: "jenkins-e2e-master", osImage: "Google Container-VM Image", kubeletVersion: "v1.6.0-alpha.0.1029+09bb156116aed4"
name: "jenkins-e2e-minion-group-3gn7", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.3.11-beta.0.4+c26d625815e629"
name: "jenkins-e2e-minion-group-ffy4", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.3.11-beta.0.4+c26d625815e629"
name: "jenkins-e2e-minion-group-sdyk", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.3.11-beta.0.4+c26d625815e629"
```

**Comment by mtaufen** [comment]
Do GKE upgrades even use `cluster/gce/upgrade.sh`?

**Comment by krousey** [comment]
No they do not. I just noted so people know that GKE upgrade test failures are not attributable to this.

**Comment by bprashanth** [comment]
oh, sorry i forgot to mention i previously figured out something that works. 
First you need to actualy shift the args so we read -o by making this: https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/upgrade.sh#L357

```bash
esac
shift
```
then, you need to supply the `-N version` as the second arg, i.e
```
$ KUBE_NODE_OS_DISTRIBUTION=gci cluster/gce/upgrade.sh -o -N v1.5.0-beta.2
```

because various places like https://github.com/kubernetes/kubernetes/blob/master/cluster/common.sh#L353 check the first arg as version, and https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/upgrade.sh#L359 will basically leave that as the `v1.5.0-beta.2`.

Anyway I leave it to you guys to figure out a nice fix, I upgraded from cvm -> gci 1.5 and am going to focus on the testing.

**Comment by davidopp** [comment]
@gmarek mentioned to me in chat that he thought the problem had to do with the way the args are being parsed, and that in particular he thought `"${env_os_distro}" == "false" ]` was always happening even if you set -o 

This would be consistent with @bprashanth 's comments

**Comment by davidopp** [comment]
Maybe someone can try deleting the body of `setup-base-image` and see if KUBE_NODE_OS_DISTRIBUTION works when you do that. This would make it even clearer that the problem is just with how the `-o` is being handled.

**Comment by roberthbailey** [comment]
I copied out the arg parsing part of upgrade.sh into a separate script to see what the behavior is:

```shell
master_upgrade=true
node_upgrade=true
node_prereqs=false
local_binaries=false
env_os_distro=false

while getopts ":MNPlho" opt; do
  case ${opt} in
    M)
      node_upgrade=false
      ;;
    N)
      master_upgrade=false
      ;;
    P)
      node_prereqs=true
      ;;
    l)
      local_binaries=true
      ;;
    o)
      env_os_distro=true
      ;;
    h)
      usage
      exit 0
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      usage
      exit 1
      ;;
  esac
done
echo "OPTIND=${OPTIND}"
shift $((OPTIND-1))
echo "master_upgrade=${master_upgrade}"
echo "node_upgrade=${node_upgrade}"
echo "node_prereqs=${node_prereqs}"
echo "local_binaries=${local_binaries}"
echo "env_os_distro=${env_os_distro}"
```

If you pass any non-flag arguments, then the flag parsing stops. So if you pass the new version and *then* the -o, the -o won't be parsed as the flag and won't set the variable:

```
$ ./shellargs.sh blah -o
OPTIND=1
master_upgrade=true
node_upgrade=true
node_prereqs=false
local_binaries=false
env_os_distro=false

$ ./shellargs.sh -o blah
OPTIND=2
master_upgrade=true
node_upgrade=true
node_prereqs=false
local_binaries=false
env_os_distro=true
```

**Comment by davidopp** [comment]
So can we just tell people to do "-o" right after the argv[0] and then it works?

**Comment by bprashanth** [comment]
You need a shift to get the next arg. 

I'm pretty sure my proposed fix will work out, I'm testing an upgraded cluster right now. But you need to pay heed to the order of the arguments, which is why I did't upload a pr. It's a hack, relying on that last shift to leave the version as `${1}` at the end.

**Comment by roberthbailey** [comment]
Running through the manual upgrade instructions, if you run `cluster/gce/upgrade.sh -N so v1.5.0-beta.2` in step 6 it upgrades nodes correctly from `v1.4.7-beta.0.2+githash` CVM nodes to `1.5.0-beta.2` GCI nodes. 

It doesn't matter where the -o is placed, it just needs to be *before* the desired version. The flag parsing sucks in shell, but the fix isn't to shift over an arg, it's to pass the args in the right order, and add some error checking that we don't see any flag-like args after we finish flag processing.

**Comment by gmarek** [comment]
`getopts` is just bad - I thing that `getopt` are getter. I can try rewriting upgrade script to make it more robust.

**Comment by roberthbailey** [comment]
```shell
$ ./cluster/gce/upgrade.sh -N -o v1.5.0-beta.2
== Pre-Upgrade Node OS and Kubelet Versions ==
name: "kubernetes-master", osImage: "Google Container-VM Image", kubeletVersion: "v1.5.0-beta.2"
name: "kubernetes-minion-group-chuk", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.4.7-beta.0.2+1ef121737093fd"
name: "kubernetes-minion-group-ft3t", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.4.7-beta.0.2+1ef121737093fd"
name: "kubernetes-minion-group-rw0p", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.4.7-beta.0.2+1ef121737093fd"
Your active configuration is: [default]

Project: robertbailey-kubernetes
Zone: us-central1-b
INSTANCE_GROUPS=kubernetes-minion-group
NODE_NAMES=kubernetes-minion-group-chuk kubernetes-minion-group-ft3t kubernetes-minion-group-rw0p
== Preparing node upgrade (to v1.5.0-beta.2). ==
Attempt 1 to create kubernetes-minion-template-v1-5-0-beta-2
WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#pdperformance.
Created [https://www.googleapis.com/compute/v1/projects/robertbailey-kubernetes/global/instanceTemplates/kubernetes-minion-template-v1-5-0-beta-2].
NAME                                      MACHINE_TYPE   PREEMPTIBLE  CREATION_TIMESTAMP
kubernetes-minion-template-v1-5-0-beta-2  n1-standard-2               2016-11-30T14:30:08.309-08:00
Instance template name: kubernetes-minion-template-v1-5-0-beta-2
== Finished preparing node upgrade (to v1.5.0-beta.2). ==
== Upgrading nodes to v1.5.0-beta.2. ==
== Calling rolling-update for kubernetes-minion-group. ==
== Waiting for Upgrading nodes to be finished. ==
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is still in ROLLING_FORWARD state.
Rolling update 25b0c55e-0649-4ffc-a3fd-b93d261164c9 is ROLLED_OUT state and finished.
== Deleting old templates in robertbailey-kubernetes. ==
Deleted [https://www.googleapis.com/compute/v1/projects/robertbailey-kubernetes/global/instanceTemplates/kubernetes-minion-template].
== Finished upgrading nodes to v1.5.0-beta.2. ==
== Validating cluster post-upgrade ==
Your active configuration is: [default]

Project: robertbailey-kubernetes
Zone: us-central1-b
Waiting for 4 ready nodes. 3 ready nodes, 4 registered. Retrying.
Waiting for 4 ready nodes. 3 ready nodes, 4 registered. Retrying.
Waiting for 4 ready nodes. 3 ready nodes, 4 registered. Retrying.
Waiting for 4 ready nodes. 3 ready nodes, 4 registered. Retrying.
Found 4 node(s).
NAME                           STATUS                     AGE
kubernetes-master              Ready,SchedulingDisabled   9m
kubernetes-minion-group-chuk   Ready                      3m
kubernetes-minion-group-ft3t   Ready                      2m
kubernetes-minion-group-rw0p   Ready                      33s
Validate output:
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok                   
scheduler            Healthy   ok                   
etcd-0               Healthy   {"health": "true"}   
etcd-1               Healthy   {"health": "true"}   
Cluster validation succeeded
== Post-Upgrade Node OS and Kubelet Versions ==
name: "kubernetes-master", osImage: "Google Container-VM Image", kubeletVersion: "v1.5.0-beta.2"
name: "kubernetes-minion-group-chuk", osImage: "Google Container-VM Image", kubeletVersion: "v1.5.0-beta.2"
name: "kubernetes-minion-group-ft3t", osImage: "Google Container-VM Image", kubeletVersion: "v1.5.0-beta.2"
name: "kubernetes-minion-group-rw0p", osImage: "Google Container-VM Image", kubeletVersion: "v1.5.0-beta.2"

```

**Comment by roberthbailey** [comment]
So we should just update the instructions to unblock manual testing and then fix the script to be more forgiving of users. Fixing documentation should be release blocking; fixing the script doesn't need to be, after all, the top of the script says:

> \# !!!EXPERIMENTAL !!! Upgrade script for GCE. Expect this to get
> \# rewritten in Go in relatively short order, but it allows us to start
> \# testing the concepts.

**Comment by gmarek** [comment]
Agreed.

**Comment by mtaufen** [comment]
Shouldn't the usage for the script read:
`${0} [-M|-N|-P|-o] -l | <version number or publication>`
instead of:
`${0} [-M|-N|-P] -l -o | <version number or publication>`?

I think for now we can just check whether there is anything after the version, if so it should be an error according to the usage printout.

**Comment by mtaufen** [comment]
I can post some fixes to the scripts.

**Comment by roberthbailey** [comment]
@mtaufen -- no, the parsing of the usage is weird, but it's trying to say that -M, -N, -P, and -o are optional flags, and that you can *either* pass -l or a version number (of course, -l is [currently unimplemented for node upgrades](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/upgrade.sh#L390), but that's a different issue).

**Comment by roberthbailey** [comment]
Do we have documentation, other than the manual upgrade instructions, for using upgrade.sh? We need to make sure they are clear.

**Comment by mtaufen** [comment]
@roberthbailey that's what I'm saying. The usage as-is upstream looks wrong. Upstream seems to say that -M, -N, and -P are the optionals and that you can pass either -l and -o or the version.

**Comment by roberthbailey** [comment]
I think I read your before/after in the reverse order. It should be the first one that you wrote.

**Comment by mtaufen** [comment]
Ah ok no worries.

**Comment by krousey** [comment]
Regarding my comment about this affecting automated upgrade tests, I realize I made a mistake. I was looking at a master upgrade only.

The automated tests are upgrading versions correctly. They are not swapping images correctly. Nodes will always upgrade to a CVM image because the current e2e framework doesn't support upgrading to different image types (and defaults to CVM). See https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/nodes_util.go#L91.

I don't think this should be a release blocker since we're running through these combinations correctly for GKE, we haven't done these tests for GCE in the past, and we only have the GKE upgrade tests for releases. (The only GCE ones are from 1.3 and 1.4 to head... not 1.5)

**Comment by davidopp** [comment]
So IIUC, we just need to change the documentation to say to put the -o at the beginning (or more precisely, before the version number) and then it works?

**Comment by mtaufen** [comment]
https://github.com/kubernetes/kubernetes/pull/37723 adds an error to the script to catch this as well

**Comment by gmarek** [comment]
I wrote a fix - someone should test it, but as @roberthbailey it's not a high priority.

**Comment by dims** [comment]
So, per the emails and pr(s) there's a work around and updates to docs. Marking this as a non-release-blocker

**Comment by dims** [comment]
@davidopp @mtaufen Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by davidopp** [comment]
@gmarek has a more complete fix out for review but there hasn't been time to review it yet. I'll move this to 1.6.

**Comment by dims** [comment]
Thanks @davidopp

**Comment by mtaufen** [comment]
Closing as I believe this was resolved long ago. Please reopen if I am wrong.
