### ISSUE TITLE
Investigate empty node name logged by node_status_updater

### ISSUE THREAD

**Issue by rkouj** [kubernetes/kubernetes#37777]
**Kubernetes version** (use `kubectl version`): 1.5

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Node status updater is trying to look for a node name with empty string. Investigation is needed as to why this happens.
https://gist.github.com/rkouj/979f70c1d3fda1b1ca5d751b65009ff9#file-gistfile1-txt-L12

**How to reproduce it** (as minimally and precisely as possible):
I found it when I was running the manual upgrade test for 1.4 to 1.5
However, I suspect this is something that happens frequently.

**Comment by saad-ali** [comment]
CC @kubernetes/sig-storage @jingxu97
