### ISSUE TITLE
Building binaries with only external linking

### ISSUE THREAD

**Issue by Pensu** [kubernetes/kubernetes#37790]
Hi,

In regards to issue #33719, we have been able to build kubernetes on ppc64le. Now, there are two types of patches required to be put in golang to achieve that, for internal linking and external linking. Both the patches are there in upstream golang. Since in corss-image Dockerfile https://github.com/kubernetes/kubernetes/blob/master/build-tools/build-image/cross/Dockerfile, we are still using patched go1.7.1 (for arm), we have backported the external linking patch to go1.7.1. 

Afaik, k8s builds binaries with both internal and external linking, can we have the ppc64le builds enabled again only with external linking for all the binaries? This is going to be a temporary solution till go1.8 is released. 

cc @luxas @ixdy

**Comment by ixdy** [comment]
Two quick thoughts:
1. it's definitely too late to do anything for k8s v1.5.
2. depending on when go1.8 gets released, we might be able to upgrade to it for k8s v1.6.

**Comment by Pensu** [comment]
@ixdy go1.8beta1 has already been released. I guess stable go1.8 would be coming sometime mid feb-2017. Can we align k8s v1.6 release to that timeline or would it be before that?

**Comment by luxas** [comment]
@Pensu In #38067 I outlined that ppc64le will/should start working again in time for v1.6, thanks to using go1.8

We should move arm and ppc64le over to go1.8betas as soon as possible

**Comment by luxas** [comment]
This is done now
