### ISSUE TITLE
Fail to run nfs-provisioner pod on Azure clound provider env

### ISSUE THREAD

**Issue by weherdh** [kubernetes/kubernetes#37797]
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.1011+42d5a1a9cd4aca", GitCommit:"42d5a1a9cd4acae9c7b258c21bfc4fb4955d7be3", GitTreeState:"clean", BuildDate:"2016-11-30T07:19:12Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.1011+42d5a1a9cd4aca", GitCommit:"42d5a1a9cd4acae9c7b258c21bfc4fb4955d7be3", GitTreeState:"clean", BuildDate:"2016-11-30T07:19:12Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**: 
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): RHEL 7.3
- **Install tools**: Ansible

**What happened**:
Follow the instruction of incubator, create nfs-provisioner pod got CrashLoopBackOff

**What you expected to happen**:
Pod could be running

**How to reproduce it** (as minimally and precisely as possible):
```
[root@wehe-master1 ~]# kubectl create -f https://raw.githubusercontent.com/kubernetes-incubator/nfs-provisioner/master/deploy/kube-config/pod.yaml
pod "nfs-provisioner" created
[root@wehe-master1 ~]# kubectl get pods
NAME              READY     STATUS             RESTARTS   AGE
nfs-provisioner   0/1       CrashLoopBackOff   3          1m
[root@wehe-master1 ~]# kubectl logs nfs-provisioner
I1201 03:29:01.155616       1 main.go:54] Provisioner matthew/nfs specified
I1201 03:29:01.155913       1 main.go:67] Starting NFS server!
F1201 03:29:01.643473       1 main.go:83] Failed to create config: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```

**Anything else do we need to know**:

**Comment by wongma7** [comment]
Kube should handle mounting of the secret there. It looks this is same issue as https://github.com/kubernetes/kubernetes/issues/27973 and you can try to pass additional flags to apiserver and controller-manager at cluster start. Can you provide controller-manager logs next time this happens? thanks

**Comment by wongma7** [comment]
can close this issue iirc was something that needed fixing on the app side

**Comment by feiskyer** [comment]
Closing the issue based on https://github.com/kubernetes/kubernetes/issues/37797#issuecomment-311098924
