### ISSUE TITLE
DiscruptionController is failing in larger clusters

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#37792]
DiscruptionController test is failing regularly in large clusters:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-large-cluster/1
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-large-cluster/2

**Comment by wojtek-t** [comment]
Hmm - this test failed again after your workaround has been merged:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-large-cluster/3

So it's still not fixed.

**Comment by davidopp** [comment]
You marked this as "kind/flake" but you said it is failing regularly. Should we consider this to be a release blocker?

**Comment by mwielgus** [comment]
No. This particular test won't work on a big clusters as it assumes that it is NOT possible to schedule 10 replicas with host port constraint. I submitted a code that should prevent it from running but apparently something didn't work there, probably in the framework code that was copy/paste/replaced.

**Comment by wojtek-t** [comment]
@davidopp - yes, as Marcin wrote, this is problem with test, not with the code itself.

**Comment by timothysc** [comment]
> This particular test won't work on a big clusters as it assumes that it is NOT possible to schedule 10 replicas with host port constraint 

That just seems wrong to me.
