### ISSUE TITLE
Missing number of comments on PRs for previous month, consideration of active contributors 

### ISSUE THREAD

**Issue by brlbil** [kubernetes/kubernetes#37799]
In documentation, 
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/community-expectations.md

In active contributors section,
* Commented on **more than pull requests** in the previous month, or more than 50 pull requests in the previous 12 months.

It does not specify exact number for comments for previous month

**Comment by xiangpengzhao** [comment]
/sig contributor-experience
/sig docs

The doc was fixed, so we can close this issue.
@thockin
