### ISSUE TITLE
Allow to set FSType for dynamically provisioned volumes

### ISSUE THREAD

**Issue by codablock** [kubernetes/kubernetes#37801]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): 
I searched in the issues and asked for help multiple times on Slack.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Kubernetes version** (use `kubectl version`): 1.5 beta

It is currently not possible to specify the desired FSType when using dynamically provisioned volumes. As I understand it, only a PV resource can specify the FSType. But as we don't create PVs by ourself when using dynamic provisioning, we have no chance to specify it.

I tried to understand the source when it comes to dynamic provisioning. As I understand it, the cloud specific VolumeSource (e.g. AzureDiskVolumeSource or AWSElasticBlockStoreVolumeSource) hold the desired FSType. For AzureDiskVolumeSource, I could not find any place where FSType is actually set. For AWSElasticBlockStoreVolumeSource, it is set to ext4 on creation and then never touched again.

I would suggest that  FSType should be added to either StorageClass or PersistentVolumeClaim. I'm not sure however which one would best fit, or if it fits at all.

**Comment by thockin** [comment]
The problem with this is that FSType is not applicable to all types of volumes.  What does it mean if I specify `fstype: xfs` on a claim, when the class is actually implemented as NFS?  User will be surprised, at best.

Provisioners can be parameterized.  Maybe we suggest that all provisioners SHOULD support FSType as a parameter if they model block devices.

**Comment by Josh-West-Bose** [comment]
+1

Perhaps this would fit into the `StorageClass` parameters?

**Comment by humblec** [comment]
+1 for SC parameter option .

**Comment by codablock** [comment]
https://github.com/kubernetes/kubernetes/issues/40805 Implementes this now in the form of SC parameters.

**Comment by jsafrane** [comment]
One thing I don't like about `sc.parameters` is that's not validated. When admin specifies `fstype=myfs` there, a provisioner happily copies it to newly provisioned  `pv.spec.<xyzVolumeSource>.fsType` and everything looks fine. It starts failing when kubelet actually tries to mount the PV - it looks for `mkfs.myfs`, which does not exists and returns cryptic error that author of the pod is not able to resolve - only author of the storage class can help here. And user must manually delete his PVC (to delete the provisioned PV) and start over. Very bad UX.

There already is #41978 that discusses validation of `pv.spec.*.fsType`.

cc @kubernetes/sig-storage-proposals

**Comment by codablock** [comment]
@jsafrane I'm aware of the missing validation, but the problem is already present in the volumes as all the block based volume types already have the fsType property, which is also not validated as far as I know (please correct me if I'm wrong...I don't have the code atm to verify this).

If fsType validation is added in the future, it should be added for SC parameters and (persistent) volumes at the same time.

**Comment by markfejes** [comment]
A huge plus one for this. It would be very-very helpful if we could specify what fs do we want to use when creating volume claim template for a stateful set.
@kubernetes/sig-storage-proposals

**Comment by msau42** [comment]
I think when we add raw block support, we should have a `fsType` field in the PVC that only works on block PVs.  @erinboyd

**Comment by kangarlou** [comment]
I think parameters in the storage class should always be treated as opaque. As a result, we shouldn't promote any keywords in the parameters section of the storage class. I also think fsType shouldn't be a keyword outside of the parameters section as there are countless other knobs that different plugins require. (Where do we draw the line? Should mount options be added as new keywords?) I'm of the opinion that it's perfectly ok for a volume plugin to make use of fsType or other knobs as opaque parameters in the storage class. Based on the type of the parameter and security/operational concerns, volume plugins may or may not allow overwriting the admin-defined value in the storage class by having users make use of PVC annotations. I don't think there is a need to redefine existing API objects.
