### ISSUE TITLE
seLinuxOptions in pod need format for different docker version

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/kubernetes#37807]
**Kubernetes version** (use `kubectl version`):
v1.6.0-alpha.0.1063+39e64fde8ca42e-dirty

**Environment**:
```
[root@ip-172-18-6-200 selinux]# docker version
Client:
 Version:         1.12.3
 API version:     1.24
 Package version: docker-common-1.12.3-8.el7.x86_64
 Go version:      go1.6.2
 Git commit:      8b91553-redhat
 Built:           Wed Nov 16 11:35:08 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.3
 API version:     1.24
 Package version: docker-common-1.12.3-8.el7.x86_64
 Go version:      go1.6.2
 Git commit:      8b91553-redhat
 Built:           Wed Nov 16 11:35:08 2016
 OS/Arch:         linux/amd64

```

**What happened**:
There are two issue for seLinuxOptions:
1. Currently when set Seccomp and AppArmor for container we use different format for docker version, ref: [dm.fmtDockerOpts](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker_manager.go#L1108-L1133), but [seLinuxOptions](https://github.com/kubernetes/kubernetes/blob/master/pkg/securitycontext/types.go#L44-L48) is hard code.
2. When run pod with seLinuxOptions, why container has two same selinux context label?

**How to reproduce it** (as minimally and precisely as possible):
```
1. Create a pod with seLinuxOptions
kubectl create -f https://raw.githubusercontent.com/mdshuai/testfile-openshift/master/k8s/securityContext/pod-selinux.yaml

2. When pod is running check container HostConfig.SecurityOpt by 'docker inspect 65bfe2089da5' 
 docker inspect 65bfe2089da5
...
            "SecurityOpt": [
                "seccomp=unconfined",
                "label:user:unconfined_u",
                "label:role:unconfined_r",
                "label:level:s0:c25,c968",
                "label=user:unconfined_u",
                "label=role:unconfined_r",
                "label=type:svirt_lxc_net_t",
                "label=level:s0:c25,c968"
            ],
...
```
**What you expected to happen**:
1. If docker api version>1.23, we need use ```label=user:unconfined_u``` not ```label:user:unconfined_u```
2. I don't know why we have set twice selinux context for container.

**Anything else do we need to know**:

**Comment by mdshuai** [comment]
@pmorie @derekwaynecarr Help check, thanks

**Comment by dims** [comment]
@mdshuai : where is the information `If docker api version>1.23, we need use label=user:unconfined_u not label:user:unconfined_u` from?

**Comment by mdshuai** [comment]
@dims from  ```fmtDockerOpts``` function in file ```pkg/kubelet/dockertools/docker_manager.go```  https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker_manager.go#L1116

**Comment by pmorie** [comment]
I'm about to open a PR that fixes this issue.

**Comment by mdshuai** [comment]
This should be fixed by https://github.com/kubernetes/kubernetes/pull/40903
