### ISSUE TITLE
[kube-mesos] Support Mesos Container in Kubelet

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#37800]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request.

**Kubernetes version** (use `kubectl version`):
master

**What you expected to happen**:
In Mesos 1.x, [Mesos container](http://mesos.apache.org/documentation/latest/mesos-containerizer/) is the default container runtime of tasks; when running Kubernetes on Mesos ([kube-mesos](https://github.com/kubernetes-incubator/kube-mesos-framework/)), we'd like to also using only one container runtime environment to reduce OP's maintenance effort.

That's one project of [kube-mesos](https://github.com/kubernetes-incubator/kube-mesos-framework/) ; but I do not want to duplicate Kubelet in [kube-mesos](https://github.com/kubernetes-incubator/kube-mesos-framework/) project.

**Comment by vishh** [comment]
Kubelet typically expects to manage the entire node. It assumes that it has exclusive access to all the resources, both HW and non-HW, and to the runtime.
I hope the intention is not to share the Mesos Containerizer between Kubelet and Mesos itself...

**Comment by k82cn** [comment]
@vishh , in kube-mesos, k8sm-scheduler launch Pods in kubelete according to Mesos's offer. In C++ or Java, I'd like to implement this feature in kube-mesos project and load by `jar` or `.so`, but it seems Go did not support that.

**Comment by feiskyer** [comment]
@k82cn If pods are still launched by kubelet, [CRI](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/container-runtime-interface.md) for Mesos container runtime is a better choice.

**Comment by k82cn** [comment]
@feiskyer , thanks for your input; `CRI` seems the right option to me. Let's check the related doc and back to you if any question :).

**Comment by k82cn** [comment]
We're going to use CRI for kube-mesos, close this one. If any issue/question on CRI, will log other one.
