### ISSUE TITLE
Move docs: design, proposals, devel to community repo

### ISSUE THREAD

**Issue by michelleN** [kubernetes/kubernetes#37827]
- [x] Move docs/design, docs/design, and docs/proposals to the community repo under [`contributors/`.](https://github.com/kubernetes/community/tree/master/contributors) and combine design and proposals docs under design-proposals directory

- [x] Freeze PRs on the moved directories (cc/ @grodrigues3)

- [x] Make announcement about freeze

- [x] Update the files in those directories in this repo to contain a forwarding link to the new location of the files using a script. _Note: There was a script used during the docs move for kubernetes.github.io. If you know where it is, it would be helpful. :)_

- [x] Make announcement on updated locations of those files

- [ ] Update any links that point to the moved files

- [ ] Delete the moved docs from the kubernetes repo

- [x] Remove freeze
 

cc/ @kubernetes/contributor-experience

**Comment by alejandroEsc** [comment]
Any recommendations to those who have proposals currently as a pull request? Should we just close them and open when changes have merged? Anyway to capture the discussions in the transition?

**Comment by mbohlool** [comment]
I cannot find the announcement. Would you please add a link to the announcement here?

**Comment by philips** [comment]
Announcement here:
https://groups.google.com/d/msg/kubernetes-dev/XyGKDdqfjAE/IhpCYcvWCgAJ

**Comment by ixdy** [comment]
What's the status of this? `docs/devel` still exists in the main repo and it's causing a fair amount of confusion and inconsistency as the docs drift out-of-date.

**Comment by ixdy** [comment]
cc @kubernetes/sig-contributor-experience-misc

**Comment by michelleN** [comment]
@ixdy Aiming to have a pull request in for the stubs for this repo by tomorrow. Sorry for the inconvenience.

**Comment by bgrant0607** [comment]
@eparis do you have any tips about converting the old docs to stubs with forwarding links? Was there anything tricky about it?
