### ISSUE TITLE
AWS EBS volume issue with Storageclass and Petset

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#37843]
Description

A K8s cluster got into a state where a Petset would create in one namespace but not another.  Multiple issues with EBS volumes not mounting or unmounting.  Multiple issues with EBS volumes not being destroyed.

Deleted petset and pv correctly, and the same issue occurred.  Every time we deployed the PetSet went into Pending stuck with the following error:

```
  32m		4m		100	{default-scheduler }								Warning		FailedScheduling	[SchedulerPredicates failed due to PersistentVolume 'pvc-c1022dae-b770-11e6-8a9b-12360934d5c8' not found, which is unexpected., SchedulerPredicates failed due to PersistentVolume 'pvc-c1022dae-b770-11e6-8a9b-12360934d5c8' not found, which is unexpected., SchedulerPredicates failed due to PersistentVolume 'pvc-c1022dae-b770-11e6-8a9b-12360934d5c8' not found, which is unexpected., SchedulerPredicates failed due to PersistentVolume 'pvc-c1022dae-b770-11e6-8a9b-12360934d5c8' not found, which is unexpected., SchedulerPredicates failed due to PersistentVolume 'pvc-c1022dae-b770-11e6-8a9b-12360934d5c8' not found, which is unexpected., SchedulerPredicates failed due to PersistentVolume 'pvc-c1022dae-b770-11e6-8a9b-12360934d5c8' not found, which is unexpected., SchedulerPredicates failed due to PersistentVolume 'pvc-c1022dae-b770-11e6-8a9b-12360934d5c8' not found, which is unexpected., SchedulerPredicates failed due to PersistentVolume 'pvc-c1022dae-b770-11e6-8a9b-12360934d5c8' not found, which is unexpected.]
```

And the PVC would list the volume as `LOST`.

## Steps to Recreate (Have not validated)

1. Install Storage Class
2. Install PetSet
3. Delete PetSet
4. Do not delete PV
5. Install PetSet
6. Delete PetSet
7. Delete PV
8. Installed PetSet

Also, you clean house and install the Petset in another namespace and it worked.

In general we have volume problems ... see error above.  We attempted to completely clean house and delete the PetSet, PV, and EBS volume, and k8s kept creating the exact same volume with the same name. No joy.

## Attempted Fixes

1. Delete PV
2. Delete EBS volume by hand
3. Umount EBS volume by hand

## Issues Encountered

1. PVC in a Lost State
2. EBS volume not mounting from EC2 instance
3. EBS volume not deleting

## Work-around

1. cordon node
2. Install PetSet and PVC goes into lost state
3. Create the EBS volume by hand, with the expected K8s labels.  
4. Detele PVC
5. Petset starts.

# Components Involved

- EC2
- PVC
- PV
- Petset
- Storageclass

## K8s Version

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:16:27Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

## Cluster layout

Full HA Masters in 3 zones.  Full ha layout in mulitple regions.  3 masters / 6 nodes.

### Storageclass

```console
$ kubectl -n lme get storageclass -o yaml
```

```yaml
apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1beta1
  kind: StorageClass
  metadata:
    creationTimestamp: 2016-11-29T18:56:45Z
    labels:
      chart: storage-classes-0.1.0
      component: data-volume
      context: monitoring
      heritage: Tiller
      release: torpid-goat
    name: data-volume
    resourceVersion: "19069"
    selfLink: /apis/storage.k8s.io/v1beta1/storageclasses/data-volume
    uid: 92af9dc7-b665-11e6-86fb-0e9208071e86
  parameters:
    type: gp2
  provisioner: kubernetes.io/aws-ebs
- apiVersion: storage.k8s.io/v1beta1
  kind: StorageClass
  metadata:
    creationTimestamp: 2016-11-29T21:12:11Z
    name: slow
    resourceVersion: "39688"
    selfLink: /apis/storage.k8s.io/v1beta1/storageclasses/slow
    uid: 7eaadf70-b678-11e6-86fb-0e9208071e86
  parameters:
    iopsPerGB: "10"
    type: gp2
    zone: us-west-2a
  provisioner: kubernetes.io/aws-ebs
- apiVersion: storage.k8s.io/v1beta1
  kind: StorageClass
  metadata:
    creationTimestamp: 2016-11-29T18:56:45Z
    labels:
      chart: storage-classes-0.1.0
      component: standard-volume
      context: monitoring
      heritage: Tiller
      release: torpid-goat
    name: standard-volume
    resourceVersion: "19068"
    selfLink: /apis/storage.k8s.io/v1beta1/storageclasses/standard-volume
    uid: 92ae62cc-b665-11e6-86fb-0e9208071e86
  parameters:
    type: gp2
  provisioner: kubernetes.io/aws-ebs
kind: List
metadata: {}
```

### Petset

Pertinent data included

```console
$ kubectl -n lme get petset influxdb -o yaml
```

```yaml
apiVersion: apps/v1alpha1
kind: PetSet
# redacted info about petset
      volumeMounts:
        - mountPath: /data
          name: influxdb-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 0
  volumeClaimTemplates:
  - metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: standard-volume
      creationTimestamp: null
      labels:
        chart: influxdb-0.1.0
        component: influxdb
        context: monitoring
        heritage: Tiller
        release: contrasting-quokka
      name: influxdb-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 300Gi
```

# Questions

1. Is this a known issue in 1.4 and it is it fixed in 1.5?
2. Is there an automatic workaround that exists?

Thanks for your help!

cc: @saad-ali @bprashanth @kubernetes/sig-aws @kubernetes/sig-storage @justinsb

**Comment by saad-ali** [comment]
Needs triage as blocking or non-blocking for 1.5

**Comment by chrislovecnm** [comment]
@saad-ali how can I assist with triage.  I run into some of the exact same issues with GCE and the 1.3 release.

**Comment by chrislovecnm** [comment]
Can anyone comment if we are seeing the same type of behavior on GCE?

**Comment by rootfs** [comment]
do we have a controller log to look?

**Comment by chrislovecnm** [comment]
@rootfs log name?

**Comment by rootfs** [comment]
@chrislovecnm either `/var/log/kube-controller-manager.log` or if you are using systemd unit, `journalctl -u   kube-controller-manager`

**Comment by chrislovecnm** [comment]
posting logs to s3 shortly ...

**Comment by chrislovecnm** [comment]
Updated issue with the fact this is an HA install.

**Comment by chrislovecnm** [comment]
Logs .. http://kubernetes-bugs-logs.s3-website-us-west-2.amazonaws.com/kubernetes-issues-37843/kube-controller-manager.log.tar

Lead master controller logs.

**Comment by rootfs** [comment]
@chrislovecnm got it, which kube release you are using?

**Comment by chrislovecnm** [comment]
@rootfs - it is in the bug :)

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:16:27Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rootfs** [comment]
@chrislovecnm can you get kubelet logs from one or more of these nodes?

i-026cba9a
i-9f161b0c
i-f8ba92f6
i-ffba92f1

**Comment by chrislovecnm** [comment]
yah let me take a look at those logs ...

**Comment by rootfs** [comment]
@chrislovecnm you can also reach me via hchen@redhat.com

**Comment by chrislovecnm** [comment]
I would rather document this in a bug rather than email.  Do you want to talk on a zoom session?

**Comment by rootfs** [comment]
sure, send me the zoom link

**Comment by chrislovecnm** [comment]
that I will send by email :)

**Comment by rootfs** [comment]
@chrislovecnm do you see any similarity to #36269?

**Comment by chrislovecnm** [comment]
I cannot send you the kubelet logs, as they have private urls in them.  What data are you looking for @rootfs?

**Comment by chrislovecnm** [comment]
Similar, but not quite.

**Comment by chrislovecnm** [comment]
@rootfs what am I looking for in the logs btw?  I can see if I can clean them up, but I need to sterilize them.

@saad-ali who are we assigning this to?

**Comment by saad-ali** [comment]
> @saad-ali who are we assigning this to?

@rootfs I'll assign it to you for triage, since you're already looking at it.

**Comment by rootfs** [comment]
@chrislovecnm have you tried 1.5.beta.2 ?

**Comment by chrislovecnm** [comment]
Carving out time next week

**Comment by jsafrane** [comment]
> 7. Delete PV

@chrislovecnm, deleting PVs in Kubernetes is very dangerous operation. If there is a `PersistentVolumeClaim` (PVC) bound to it it will get `Lost` and you've effectively lost your data without any way how to repair it.

As a user, when you're done with your pet set and you want to release the underlying storage (AWS EBS) you should delete the PVCs instead. Kubernetes will delete PVs automatically in this case both from Kubernetes databases and on AWS. Of course, any pod that used the PVCs must be terminated first. Kubernetes *should* postpone deletion of PVs until all pods are finished, but the normal operation should be to delete the pods first and then delete PVCs.

**Comment by jsafrane** [comment]
`SchedulerPredicates failed due to PersistentVolume 'pvc-c1022dae-b770-11e6-8a9b-12360934d5c8' not found, which is unexpected.`: thats exactly what happens when you delete a PV and have a PVC that points to it.

**Comment by saad-ali** [comment]
Going to mark this as non-release-blocker. Holler if you disagree

**Comment by dims** [comment]
@chrislovecnm @rootfs Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by rootfs** [comment]
@dims good to me, thanks.

**Comment by chrislovecnm** [comment]
@rootfs we are seeing this in 1.5 ... Are we not seeing this on RHEL?

**Comment by justinsb** [comment]
So it sounds like this is caused by deleting the PV.  And so the correct procedure for deleting a PetSet entirely would be to delete the PetSet, delete the PVCs and then delete the PVs (is that right @jsafrane ?)

**Comment by chrislovecnm** [comment]
@justinsb The process is defined that you delete one. I am mobile so I cannot get to the docs.

The challenge is that it is not just that, we have a few things going on here.

**Comment by chrislovecnm** [comment]
Will add more details after I test more

**Comment by chrislovecnm** [comment]
Closing as I am not able to invest time in recreating, and I think this probably is addressed now
