### ISSUE TITLE
kubectl get clusters -w doesn't work as expected

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#37842]
Quoting a user:

`kubectl get services -w`

displays updates to the state of services differentially i.e. I have 10 services, and only the one that changed is displayed incrementally.

`kubectl get clusters -w`

displays all records everytime something has changed in any of them. "get clusters" behaves differently.

```shell
$ kubectl get clusters -w
NAME                                                     STATUS    AGE
cluster4b                                                Ready     4m
cluster5                                                 Unknown   6s
gke-project-europe-west1-b-west   Ready     27m
gke-project-europe-west1-b-west1-b   Ready     26m
NAME        STATUS    AGE
cluster4b   Ready     4m
cluster5   Ready     25s
gke-project-europe-west1-b-west   Ready     27m
gke-project-europe-west1-b-west1-b   Ready     27m
cluster5   Ready     35s
cluster4b   Ready     5m
cluster5   Ready     1m
gke-project-europe-west1-b-west   Ready     28m
gke-project-europe-west1-b-west1-b   Ready     27m
cluster4b   Ready     6m
cluster5   Ready     1m
gke-project-europe-west1-b-west   Ready     29m
gke-project-europe-west1-b-west1-b   Ready     28m
cluster4b   Ready     6m
cluster5   Ready     2m
gke-project-europe-west1-b-west   Ready     29m
gke-project-europe-west1-b-west1-b   Ready     29m
```

cc @kubernetes/sig-cluster-federation

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by henriquetruta** [comment]
@nikhiljindal are you working on this? Any thoughts? I'm interested on solving it

**Comment by nikhiljindal** [comment]
@henriquetruta No, feel free to take it up.
Am not sure why we have this bug. `kubectl get clusters` should work very similar to the way `kubectl get pods` does.

I will recommend starting from apiserver. Use the REST API to watch clusters and see what federation-apiserver returns. Compare that with what kube-apiserver returns for watch pod requests. If apiserver looks fine, then dig into kubectl.
You can get the required REST commands by running `kubectl get clusters -w --v=8`

**Comment by henriquetruta** [comment]
Looks like the problem here is with the `status.conditions.lastProbeTime` property on cluster. Every time the healthcheck is made, this value is updated and the `watch` is refreshed. Not sure how to tackle this. Is it possible to restrict the `watch` to specific attributes?

**Comment by nikhiljindal** [comment]
oh that makes sense. Verified that `kubectl get nodes -w` has the same problem.

**Comment by henriquetruta** [comment]
So, should we restrict the `watch` to certain fields? Is it possible?

**Comment by liggitt** [comment]
no, watches get notified any time the resourceVersion changes, which happens any time a mutating write to the object occurs
