### ISSUE TITLE
Sort order out many kubectl commands are not stable

### ISSUE THREAD

**Issue by dakoner** [kubernetes/kubernetes#37859]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

'sort output' produced pages of irrelevant bugs.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:

GCP

- **OS** (e.g. from /etc/os-release):

Linux

- **Kernel** (e.g. `uname -a`):
3.13.0-101-generic

- **Install tools**:

gcloud SDK

- **Others**:

**What happened**:

When I run 'watch kubectl describe ingress', the order of various fields is random upon subsequent views.

For example, the long list of 'Annotations' changes order every single time the command is called.
This makes "watching" an ingress which is changing difficult to see the changes.
most commands I'm used to have stable outputs for their human-readable messages.

**What you expected to happen**:

The sort order of tables should be consistent.  For example, sorted by key.

**How to reproduce it** (as minimally and precisely as possible):

Make an ingress, populate it with pods and services, then run
'watch kubectl describe ingress'

**Anything else do we need to know**:

This is likely a consequence of using a map object in Go and iterating over the output without sorting it.  That wouldn't normally be a problem, but while working with k8s, i often need to run the 'watch' command to see transient changes, and having the sort order be random is merely inconvenient.  In my experience UNIX tools typically have deterministic output for tables of data.

**Comment by matthyx** [comment]
@dakoner would you be interested in natural sorting as well? There is an open issue in OpenShift (https://github.com/openshift/origin/issues/7229) requesting that too, and it seems the relevant code is in Kubernetes. Maybe I could kill 2 birds with the same stone, what do you think?
