### ISSUE TITLE
Can't list PodDisruptionBudgets after upgrade if v1alpha1 PDBs exist

### ISSUE THREAD

**Issue by enisoc** [kubernetes/kubernetes#37862]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

* poddisruptionbudget
* pod disruption budget
* pdb

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-beta.2", GitCommit:"0776eab45fe28f02bbeac0f05ae1a203051a21eb", GitTreeState:"clean", BuildDate:"2016-11-24T22:35:03Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-beta.2", GitCommit:"0776eab45fe28f02bbeac0f05ae1a203051a21eb", GitTreeState:"clean", BuildDate:"2016-11-24T22:30:23Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

If a `policy/v1alpha1` PDB still exists after upgrading the master from `v1.4.6` to `v1.5.0-beta.2`, `kubectl get poddisruptionbudget` is broken (even for subsequently-created `policy/v1beta1` PDBs). The alpha PDB cannot be deleted through `kubectl` (neither v1.4.6 nor v1.5.0-beta.2), so the user is stuck in this broken state and must roll back the master.

**What you expected to happen**:

The existence of the alpha PDB should not break interactions with beta PDBs.

**How to reproduce it** (as minimally and precisely as possible):

1.  Launch a `v1.4.6` cluster from an official release build.
1.  Create an alpha PDB:
    ```yaml
    apiVersion: policy/v1alpha1
    kind: PodDisruptionBudget
    metadata:
      name: web
    spec:
      selector:
        matchLabels:
          app: nginx
      minAvailable: 4
    ```
1.  Upgrade the master to `v1.5.0-beta.2`: `cluster/gce/upgrade.sh -M v1.5.0-beta.2`
1.  Attempt to run `kubectl get poddisruptionbudget`

With kubectl v1.4.6:

```console
$ kubectl get poddisruptionbudget
error: group map[certificates.k8s.io:0xc8203eb2d0 componentconfig:0xc8203eb340 extensions:0xc8203b6070 policy:0xc8203b60e0 rbac.authorization.k8s.io:0xc8203b6150 apps:0xc8203eae70 authorization.k8s.io:0xc8203eb030 autoscaling:0xc8203eb0a0 storage.k8s.io:0xc8203b61c0 batch:0xc8203eb260 federation:0xc8203ea930 :0xc8203eae00 authentication.k8s.io:0xc8203eaee0] is already registered
```

With kubectl v1.5.0-beta.2:

```console
$ kubectl get poddisruptionbudget
Error from server: no kind "PodDisruptionBudget" is registered for version "policy/v1alpha1"
```

**Anything else do we need to know**:

If I try to create a beta PDB with the same name, it says:
```
Error from server (AlreadyExists): error when creating "pdb-beta.yaml": poddisruptionbudgets.policy "web" already exists
```

Attempting to delete the alpha PDB (either by name or by file) fails with:

```console
$ kubectl delete poddisruptionbudget web
Error from server: no kind "PodDisruptionBudget" is registered for version "policy/v1alpha1"
$ kubectl delete -f pdb-alpha.yaml 
Error from server: error when deleting "pdb-alpha.yaml": no kind "PodDisruptionBudget" is registered for version "policy/v1alpha1"
$ kubectl delete -f pdb-beta.yaml 
Error from server: error when deleting "pdb-beta.yaml": no kind "PodDisruptionBudget" is registered for version "policy/v1alpha1"
```

I can successfully create a beta PDB with a different name and I can specifically `kubectl get poddisruptionbudget beta-pdb`. However, listing all PDBs (`kubectl get poddisruptionbudget`) remains broken.

**Comment by davidopp** [comment]
Thanks for the thorough report, @enisoc 

@caesarxuchao Do you have any thoughts on this? I guess we can tell people that they must delete all of their alpha PDB's before upgrading, but that seems sub-optimal if there's anything we can do to avoid it.

**Comment by caesarxuchao** [comment]
I think we should update PDB in https://github.com/kubernetes/kubernetes/blob/master/cluster/update-storage-objects.sh, and run this script as part of the upgrade process.

**Comment by foxish** [comment]
That script uses kubectl get, which implies that it couldn't be used as is.
We don't currently recommend a single method of doing a [cluster upgrade](http://kubernetes.io/docs/admin/cluster-management/#cluster-autoscaling). 

If a script must be invoked prior to an upgrade, we should document that in the manual. 
But such a script would have to either:

* manipulate etcd directly 
* notify the user about v1alpha1 PDBs and ensure that they delete them.

**Comment by davidopp** [comment]
Yeah I was going to say exactly what @foxish said. That script just does `get` followed by `replace` but I don't understand how that will help here?

**Comment by davidopp** [comment]
BTW I am fine with making a very very very prominent release note telling people they must delete their alpha PDBs before upgrade, but if there is anything else we can do to make this less painful, we should try that. At least making it possible to delete alpha PDBs after the upgrade would be good, but I don't know how much work that is.

**Comment by dims** [comment]
/me sees "release note" and pings @spiffxp !

**Comment by foxish** [comment]
> At least making it possible to delete alpha PDBs after the upgrade would be good, but I don't know how much work that is.

From our discussions, advising direct manipulation of etcd is not an option. The other options are:

* Changes on the server-side to make this work. @caesarxuchao can comment on how much effort this might be.
* An "check-upgrade.sh" script which we advise all users to run, so as to identify potential problems prior to upgrade, which would call out and advise users to delete their PDBs. 
This could potentially be used in future as well.

**Comment by wojtek-t** [comment]
@lavalamp 

It seems that no matter what decision we will make, user will need to take some actions (no matter if that will be deleting PDBs before upgrade or running some script or something else). 
That said if he/she needs to do something anyway, and if https://github.com/kubernetes/kubernetes/blob/master/cluster/update-storage-objects.sh works (and I really think it should as we are testing is in per-PR and continuous testing) here:
https://github.com/kubernetes/kubernetes/blob/master/hack/test-update-storage-objects.sh
Saying that running this script is required is the best option in my opinion (deleting means that use will loose their objects e.g.).

**Comment by davidopp** [comment]
@wojtek-t I don't think update-storage-objects.sh will work for this situation. It won't do the right thing if you run it before upgrade nor after upgrade.

**Comment by wojtek-t** [comment]
Aaah ok, right. The problem here is that we remove v1alpha1 (which is not what we are usually doing).

**Comment by caesarxuchao** [comment]
> Changes on the server-side to make this work. @caesarxuchao can comment on how much effort this might be

The issue blocked us to enable both v1alph1 and v1beta1 was https://github.com/kubernetes/kubernetes/issues/35792. I don't know if there are more potential problems. On the bright side, the batch group has two versions enabled and works fine, so perhaps it's a low-hanging fruit.

**Comment by saad-ali** [comment]
If the answer is:

> davidopp commented 23 hours ago
> BTW I am fine with making a very very very prominent release note telling people they must delete their alpha PDBs before upgrade, but if there is anything else we can do to make this less painful, we should try that. At least making it possible to delete alpha PDBs after the upgrade would be good, but I don't know how much work that is.

Then make sure to add to https://github.com/kubernetes/kubernetes/issues/37134 ("v1.5.0 known issues / FAQ accumulator")

An automated solution if one exists would be *very* nicer.

**Comment by davidopp** [comment]
@mwielgus / @caesarxuchao Do you think it is feasible to fix #35792 in the time remaining before the release (e.g. by end of Tuesday)? I'm assuming the answer is "no" but just wanted to check. Also I am not convinced it would be worth the effort since probably very few people are using PDB in alpha (we introduced it in the last release).

**Comment by caesarxuchao** [comment]
I'll try my luck with #35792. I'll let you know if I can fix it easily.

**Comment by calebamiles** [comment]
Any updates on this issue @caesarxuchao, @davidopp, @mwielgus? Please update this issue immediately, thanks!

**cc: @saad-ali, @dims**

**Comment by davidopp** [comment]
I'm marking this a non release blocker. Putting a big warning in the release notes is sufficient, if we can't implement the fix in time.

**Comment by caesarxuchao** [comment]
I haven't got time to look at the bug yet.

**Comment by saad-ali** [comment]
> I'm marking this a non release blocker. Putting a big warning in the release notes is sufficient, if we can't implement the fix in time.

Release notes are [here](https://github.com/kubernetes/features/blob/master/release-1.5/release-notes-draft.md). Please make sure they are updated accordingly.

**Comment by dims** [comment]
@enisoc @davidopp Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by davidopp** [comment]
I think it's no longer relevant once 1.5 is released and people start using PodDisruptionBudget beta, and we didn't get to it for 1.5, so I'm just going to close this.
