### ISSUE TITLE
shared public client with no client_secret

### ISSUE THREAD

**Issue by jsloyer** [kubernetes/kubernetes#37874]
Based on the conversation in #37822, there is a need to allow to a shared public client for openid connect with no client_secret.

Kubectl will need to be updated to allow no value to be set for client_secret.  Currently kubectl requires client_secret to be set.

**Comment by ericchiang** [comment]
@jsloyer to follow up. Would your provider be okay with sending an empty "client_secret=" POST form value? Or does it actually need to omit the form value?

**Comment by mlbiam** [comment]
@ericchiang i think a public oidc client means that the client_secret isn't sent at all

**Comment by ericchiang** [comment]
Gah, I'm going crazy. Forgot that client credentials should be sent over basic auth. My question was, does the provider then take a basic auth header with no password at its token endpoint? e.g. Does this work?

```go
req.SetBasicAuth("CLIENT_ID", "")
```

**Comment by mlbiam** [comment]
i think you're right first time...you don't send the secret using basic auth during a refresh, you just omit the client_secret parameter http://openid.net/specs/openid-connect-core-1_0.html#RefreshTokens
