### ISSUE TITLE
kubectl auth providers are repeatedly reinitialized

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#37876]
When enabling the OpenID Connect auth provider we found that auth providers are initialized almost every time kubectl needs to make a new request rather than reusing the initialized transport. @mlbiam noticed this as well as it causes kubectl to become excruciatingly slow.

Will follow up with a more detailed bug report.

cc @cjcullen @jlowdermilk (don't know who else to CC)

**Comment by ncdc** [comment]
cc @liggitt @deads2k @fabianofranz

**Comment by mlbiam** [comment]
@ericchiang to be fair the only place I saw performance issues was on a
raspberry pi, on a vm or my workstation its not noticeable

**Comment by philips** [comment]
@mlbiam the roundtrips caused by this can be excruciating if you are dealing with a remote Kubernetes cluster somewhere on the internet.

**Comment by liggitt** [comment]
is this the transport to kube or the transport to the oidc provider? kube transports build using [Transport#New](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/transport/transport.go#L29) should only build once per process for the same TLS options

**Comment by liggitt** [comment]
or is the issue that newOIDCAuthProvider (and therefore oidc.FetchProviderConfig) is called repeatedly and is rebuilding the oidc client repeatedly?

**Comment by ericchiang** [comment]
> or is the issue that newOIDCAuthProvider (and therefore oidc.FetchProviderConfig) is called repeatedly and is rebuilding the oidc client repeatedly?

This one (code[0] for those interested). The only place I could find this called is when the client converts a kubeconfig into a transport config[1] which seems to imply that kubectl is constantly recreating transport configs. If there's a cache then kubectl might still be reusing connections and this issue might be limited to auth providers.

[0] https://github.com/kubernetes/kubernetes/blob/v1.4.6/plugin/pkg/client/auth/oidc/oidc.go#L62
[1] https://github.com/kubernetes/kubernetes/blob/v1.4.6/pkg/client/restclient/transport.go#L63

**Comment by ericchiang** [comment]
So I think the solution here is to cache transports like transport.New does. @liggitt that sound correct?

**Comment by liggitt** [comment]
caching for process duration based on inputs used to construct the transport sounds right
