### ISSUE TITLE
Unable to hit Pod from Master

### ISSUE THREAD

**Issue by chandu4b4** [kubernetes/kubernetes#37873]
Hi,
I have one Master and 2 Menions.
Master IP: 192.168.20.50
Menion1: 192.168.20.51
Menion2: 192.168.20.52

I am able to run replication containers and create Services in Master. I have a problem in accessing Application container by using Master IP.

I did port forwarding from master to menion with fallowing command.

[root@master ~]# kubectl port-forward nginx :80 &
[2] 2229
[root@master ~]# I1201 22:15:46.822396    2229 portforward.go:213] Forwarding from 127.0.0.1:43020 -> 80
I1201 22:15:46.822603    2229 portforward.go:213] Forwarding from [::1]:43020 -> 80

So when I hit with localhost I can access nginx but when I hit with Master IP I am getting connection refused.

[root@master ~]# curl http://localhost:43020
I1201 22:15:57.031858    2229 portforward.go:247] Handling connection for 43020
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

[root@master ~]# curl http://192.168.1.49:43020
curl: (7) Failed connect to 192.168.1.49:43020; Connection refused

**Comment by spiffxp** [comment]
/sig network
/kind support
/assign
closing because this should be asked elsewhere (eg: StackOverflow) per https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/
