### ISSUE TITLE
kubectl oidc auth provider: client shouldn't send scopes during refreshing

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#37875]
Currently kubectl sends a "scope" field with its refresh request. It guesses the scopes used or the user is allowed to provide them.

However, omitting "scope" means "default to the original authorized scopes" which is probably more useful for a vast majority of cases.

If unspecified, the client shouldn't send a "scope" field.

Relevant RFC section: https://tools.ietf.org/html/rfc6749#section-6

edit: if someone can assign me that'd be awesome.

**Comment by ncdc** [comment]
cc @liggitt @deads2k
