### ISSUE TITLE
Unable to fetch logs with Swagger generated code

### ISSUE THREAD

**Issue by quasiben** [kubernetes/kubernetes#37881]
As of commit: `c758c00b1a597f4629d9f608598452fc3b2fb81b`

**Kubernetes version** (use `1.4.3`):

**Environment**:
- **Ubuntu 16.04**:

**What happened**:
Unable to fetch logs from a pod using the spec provided by [v1.json](https://github.com/kubernetes/kubernetes/blob/master/api/swagger-spec/v1.json)

**How to reproduce it** (as minimally and precisely as possible):
```
wget https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/swagger-spec/v1.json
swagger-codegen generate -i v1.json -l python
```

calling `read_namespaced_pod_log(namespace='default', name=name`) returns a bare v1Pod:

```python
ipdb> kube.api.read_namespaced_pod_log(namespace='default', name=name)
/Users/quasiben/anaconda/envs/kubelab/lib/python3.5/site-packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
{'api_version': None,
 'kind': None,
 'metadata': None,
 'spec': None,
 'status': None}
```

**Anything else do we need to know**:
Relevant issue: https://github.com/kubernetes/kubernetes/issues/14071
Older PR: https://github.com/kubernetes/kubernetes/pull/25707

The PR above has been merged into master but I still only see bare v1Pod dicts returned.  My initial thought was that the `deserialization` can't handle strings and/or isn't appropriately applying `PodLogOptions`.  I could very well be wrong about this.  First time diving into Kubernetes code

**Comment by mbohlool** [comment]
Problem is the return type of a log is not json but text. using our new [python-client](https://github.com/kubernetes-incubator/client-python), you can do this to get output of a call in text:

```python
    config.load_kube_config(
        os.path.join(os.path.expanduser('~'), '.kube', 'config'))

    v1 = client.CoreV1Api()
    print("Listing pods with their IPs:")
    ret = v1.read_namespaced_pod_log(namespace='default', name=name, _preload_content=False)
    print ret.read()
```

You can even do something like the Watch class to follow the logs. I will think of a way to support this natively in the client.

**Comment by mbohlool** [comment]
Look like Kubernetes behavior is valid. the log function returns text response with Content-Type header set to plain/text. The generated client is not behaving as expected and tries to decode a plain/text into a json object. Kubernetes spec should not specify v1.Pod as the response for this operations. The response should be an string. I will continue investigating to see what is the best fix here.

**Comment by quasiben** [comment]
@mbohlool happy to help test

**Comment by mbohlool** [comment]
This is only one instance in our APIs, I am tempted to just patch the OpenAPI spec before client generation (We currently do that for a number of simplification in client-python). There is a more generic fix in kubernetes code, but I am not sure if it add enough value because it only impact one operation.
