### ISSUE TITLE
[Installation Failure] Mirror unavailable when yum install 

### ISSUE THREAD

**Issue by DjangoPeng** [kubernetes/kubernetes#37922]
OS: redhat 7.2
I followed the tutorials in [kubernetes.io](http://kubernetes.io/docs/getting-started-guides/kubeadm/), but failed when yum install.

```shell
# cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF
# setenforce 0
# yum install -y docker kubelet kubeadm kubectl kubernetes-cni
# systemctl enable docker && systemctl start docker
# systemctl enable kubelet && systemctl start kubelet
```

After create `kubernetes.repo`, I get the info as below when I try `yum update` :

```shell
Loaded plugins: fastestmirror, product-id, search-disabled-repos, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
base                                                                        | 3.6 kB  00:00:00     
docker-main-repo                                                            | 2.9 kB  00:00:00     
dockerrepo                                                                  | 2.9 kB  00:00:00     
extras                                                                      | 3.4 kB  00:00:00     
http://yum.kubernetes.io/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 302 - Found
Trying other mirror.


 One of the configured repositories failed (Kubernetes),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable kubernetes

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=kubernetes.skip_if_unavailable=true

failure: repodata/repomd.xml from kubernetes: [Errno 256] No more mirrors to try.
http://yum.kubernetes.io/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 302 - Found
```

I'm not sure whether the mirrors are missing, could you give me some suggestions?

**Comment by yudar1024** [comment]
same issue here

**Comment by xiaozhiqi2016** [comment]
same issue here

**Comment by DjangoPeng** [comment]
@caesarxuchao @quinton-hoole
I don't know who could have a look at this issue, but it is really an obstacle for k8s users in CentOS/Redhat. Could you cc someone who response for the issue?

**Comment by huanxijiuhao** [comment]
same issue here

**Comment by shenshouer** [comment]
same issue here

**Comment by RobinLe** [comment]
same issue here

**Comment by RobinLe** [comment]
And when I download kubelet, kubeadm, kubectl, kubernetes-cni and install these components manually.  There are some dependences errors.

```
[root@k8s-master centos7]# rpm -ivh kubelet-1.5.1-0.x86_64.rpm 
warning: kubelet-1.5.1-0.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 3e1ba8d5: NOKEY
error: Failed dependencies:
	kubernetes-cni >= 0.3.0.1 is needed by kubelet-1.5.1-0.x86_64
	socat is needed by kubelet-1.5.1-0.x86_64
[root@k8s-master centos7]# rpm -ivh kubernetes-cni-0.3.0.1-0.07a8a2.x86_64.rpm 
warning: kubernetes-cni-0.3.0.1-0.07a8a2.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 3e1ba8d5: NOKEY
error: Failed dependencies:
	kubelet is needed by kubernetes-cni-0.3.0.1-0.07a8a2.x86_64

```

**Comment by greatbsky** [comment]
+1 in china

**Comment by caesarxuchao** [comment]
cc @mikedanese

**Comment by illera88** [comment]
same issue!

**Comment by nileshkanawade** [comment]
Hi, does anybody manage to solve this issue?? I'm also getting same issue and stuck here since yesterday.

**Comment by klinakuf** [comment]
I am having the same issue

**Comment by BioMechanico** [comment]
FWIW: I was having this issue yesterday on my cloud server when I was going through their online console portal. Today I tried ssh'ing into the server instead and it seems to work fine.

**Comment by MilanDasek** [comment]
same issue here

**Comment by mikedanese** [comment]
@dgoodwin any idea what this could be?

**Comment by mikedanese** [comment]
Are all these reports from china? Does this repodata work?
```
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
```

**Comment by MilanDasek** [comment]
yes, me China

https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2404:6800:4008:802::200e: Network is unreachable"

**Comment by klinakuf** [comment]
No, for me is Germany

**Comment by dgoodwin** [comment]
Are there proxies being used in these environments? If so has yum been configured to use it? (https://www.centos.org/docs/5/html/yum/sn-yum-proxy-server.html)

Does a `yum clean all && rm -rf /var/cache/yum/*` help?

**Comment by kyjsqd222** [comment]
have you solved the problem yet?

**Comment by klinakuf** [comment]
I'm behind a proxy and I've set the http(s)_proxy which was working a month ago, but now if I add the proxy also in the etc/yum.conf I receive some time outs with my proxy url.

**Comment by klinakuf** [comment]
The solution for me was to make sure that in _/etc/environment_ the **https_proxy** is set properly

**Comment by RobinLe** [comment]
use shadowsocks or modify hosts access google in china. 

my solution:
open the below link
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/primary.xml

and find the package location and download it.
example kubelet:
https://packages.cloud.google.com/yum/pool/8a299eb1db946b2bdf01c5d5c58ef959e7a9d9a0dd706e570028ebb14d48c42e-kubelet-1.5.1-0.x86_64.rpm

Install all packages manually.

**Comment by jackie-qiu** [comment]
@RobinLe That works for me.

**Comment by huyphams** [comment]
this works for me.
Centos 7

```
[kubernetes]
name=Kubernetes
baseurl=http://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/
enabled=1
gpgcheck=1
repo_gpgcheck=0
gpgkey=http://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
```

**Comment by luxas** [comment]
Seems like folks have found their way to work around these proxy issues. I think declaring proxy env vars in /etc/environment is probably best practice.
Turning off gpg verification could work but isn't encouraged

If you still think this is a problem, please reopen this issue in https://github.com/kubernetes/kubeadm/issues

**Comment by wangxfbelieve** [comment]
Ops, set proxy information in the  /etc/yum.conf, like this:

proxy=http://172.19.136.190:1087
proxy_username=
proxy_password=

It's will be enable for all users, and It's does works.

**Comment by cqxiaomi** [comment]
ftp://ftp.pbone.net/mirror/ftp.centos.org/7.3.1611/cloud/x86_64/openstack-kilo/common/sysbench-0.4.12-12.el7.x86_64.rpm
ftp://195.220.108.108/linux/remi/enterprise/6/test/x86_64/compat-mysql55-5.5.55-1.el6.remi.x86_64.rpm

rpm -ivh compat-mysql55-5.5.55-1.el6.remi.x86_64.rpm
rpm -ivh sysbench-0.4.12-12.el7.x86_64.rpm

https://www.rpmfind.net/linux/rpm2html/search.php?query=libmysqlclient.so.18()(64bit)

**Comment by danielrive** [comment]
have you solved the problem yet?

**Comment by amsaiyed** [comment]
I am still having the same issue.

**Comment by danielrive** [comment]
i have downloaded the kubectl binary via curl but the repo still is fail

**Comment by songhui1984** [comment]
me too

**Comment by harishsingh77** [comment]
inside the your repo file disable mirror list and uncomment  basurl. it will work

**Comment by inderjitm** [comment]
This is the original config from https://kubernetes.io/docs/setup/independent/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kube*
EOF

**Comment by printfcoder** [comment]
China:

1. 
```bash
$ vi ~/.bash_profile
```
2. 
```sh
export http_proxy=YourProxyHost:port
export https_proxy=YourProxyHost:port
```
3. 
```bash
$ source ~/.bash_profile
```

**Comment by johnnyflute** [comment]
I used to set proxy manually on my docker engine, I reset it to system proxy, and it seems work normal to me

**Comment by woxiaomaa** [comment]
兄弟们，因为我们连不到谷歌啊，搭个ss就行了...

**Comment by herderwu** [comment]
use china source:
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=http://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=0
repo_gpgcheck=0
gpgkey=http://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg
        http://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg
EOF

setenforce 0
yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
systemctl enable kubelet && systemctl start kubelet

by molscar
at https://juejin.im/post/5b8a4536e51d4538c545645c

**Comment by vahitunal** [comment]
i tried with squid and tiny proxy. none of the solutions worked for me. when i use socks5 it worked.

**Comment by Shridharbhandar** [comment]
Hi Team,

I also have the same issue and it's actually getting connected in between but it's unable to complete it. 

Can you please check the below image and tell me what is the reason for this kind of behavior??

Is it a compatibility issue of yum on rhel with kubernetes....

![image](https://user-images.githubusercontent.com/22121286/99653376-ef104980-2a7e-11eb-8c0f-1e972be4441e.png)

**Comment by abrahamhwj** [comment]
same issue，fixed by clean wrong repo in “/etc/yum.repos.d” ，so please check，if has any wrong repo in this path

**Comment by srikanthsava** [comment]
use this link: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch  
instead of http://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64

It's worked for me
if any want complete file here it is:
"Download & Install - Docker | Kubelet | Kubeadm | Kubectl on nodes"
# Note: Execute on all nodes (master & worker)
#Kubernetes Repository
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg 
exclude=kube*
EOF

# Installing Docker | Kubelet | Kubeadm | Kubectl
yum update -y
yum install -y docker kubeadm kubelet kubectl --disableexcludes=kubernetes

# Start and enable docker and kubectl

systemctl enable docker && systemctl start docker 
systemctl enable kubelet && systemctl start kubelet

# For CentOS and RHEL

cat <<EOF >  /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF

sysctl net.bridge.bridge-nf-call-iptables=1
sysctl net.ipv4.ip_forward=1
sysctl --system
echo “1” > /proc/sys/net/ipv4/ip_forward

# Restart the systemd daemon and the kubelet service with the commands:
systemctl daemon-reload
systemctl restart kubelet

**Comment by srikanthsava** [comment]
> same issue，fixed by clean wrong repo in “/etc/yum.repos.d” ，so please check，if has any wrong repo in this path

https://github.com/kubernetes/kubernetes/issues/37922#issuecomment-996749010

**Comment by khalilnechi** [comment]
try to set repo_gpgcheck=0

**Comment by mondalkaushik91** [comment]
try to set repo_gpgcheck=0 This one will work

**Comment by swap357** [comment]
> use china source: `cat < /etc/yum.repos.d/kubernetes.repo [kubernetes] name=Kubernetes baseurl=http://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64 enabled=1 gpgcheck=0 repo_gpgcheck=0 gpgkey=http://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg http://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg EOF
> 
> setenforce 0 yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes systemctl enable kubelet && systemctl start kubelet ` by molscar at https://juejin.im/post/5b8a4536e51d4538c545645c
> 
> >

This works for China AliCloud instances, no need for yum-key.gpg
