### ISSUE TITLE
PROPOSAL: Subcommand for easier editing of configmap keys

### ISSUE THREAD

**Issue by juanvallejo** [kubernetes/kubernetes#37965]
Using `kubectl edit` is not always ideal for updating the contents of `ConfigMap` object fields. If a field's value is too large, it can be non-intuitive from a user's perspective to replace such value with a file's contents, for example.

This proposal suggests the creation of a `new method for updating a single field in a config map`. 

This could  be done either through a new sub-command:
- `kubectl edit-field configmap/myconfigmap FIELD1="newvalue"`

or through the use of a flag:
- `kubectl edit configmap/myconfigmap --field FIELD1="test"`

updating a single field's value using a file's contents would also be supported:
- `kubectl edit configmap/myconfigmap --field FIELD1 --from-file=path/to/file`
- `kubectl edit-field configmap/myconfigmap FIELD1 --from-file=path/to/file`

@fabianofranz @jwforres @smarterclayton

**Comment by smarterclayton** [comment]
What use cases beyond config map and secrets would apply?

**Comment by juanvallejo** [comment]
@smarterclayton it would only be config maps and secrets for now. This stemmed out of this bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1396435

**Comment by fabianofranz** [comment]
@kubernetes/kubectl

**Comment by deads2k** [comment]
> What use cases beyond config map and secrets would apply?

This is a thing that I would find useful for iterating on a config file trapped inside of a configmap.

**Comment by soltysh** [comment]
How this is different from `kubectl patch`?
```
kubectl edit configmap/myconfigmap --field FIELD1="test"
```
vs
```
kubectl patch configmap/myconfigmap -p '{"FIELD1":"test"}'
```
? I am aware that with the latter a bit more thought is required to write the json, but I'm seeing the two pretty similar. Eventually we could extend `patch` with an option `--from-file`, imho.

**Comment by deads2k** [comment]
> How this is different from kubectl patch?

Create a config map that contains a `master-config.yaml` and then write the patch you need to mutate a field.  This would solve that use-case in a far more reasonable way.

It gets even worse with secrets since they are base64 encoded.

**Comment by soltysh** [comment]
How about then extending patch with the ability to limit the scope to a single field? This seems very similar to how `kubectl patch` operates, imho.

**Comment by deads2k** [comment]
> How about then extending patch with the ability to limit the scope to a single field? This seems very similar to how kubectl patch operates, imho.

It wasn't strictly rhetorical.  You'll end up with a patch about 100 lines long.

**Comment by soltysh** [comment]
I'm worried we're messing two behaviors here. Edit by its nature edits the entire object, patch not matter if 2 lines long, or 1000 touches part of an object, still.

**Comment by deads2k** [comment]
> I'm worried we're messing two behaviors here. Edit by its nature edits the entire object, patch not matter if 2 lines long, or 1000 touches part of an object, still.

And yet, patching a key in a configmap is a replacement of an entire field (you choose the field to patch, but you must replace the entire value) and that involves escaping and base64 encoding inside of your patch.

**Comment by kargakis** [comment]
@soltysh edit also uses patch.

**Comment by jwforres** [comment]
speaking from a user experience side, patch is not an acceptable answer.  There is a legitimate use case for needing to update large blobs for a single key in both config maps and secrets.  For secrets what happens when you need to update your cert because it expired.  I agree with @deads2k that having to generate a base64 encoded multi-line blob in a patch is NOT the way to go.

**Comment by soltysh** [comment]
I spoke with Jessica and David more about this on IRC. I got persuaded that if this proposal addresses the use-case of being able to edit configmap/secret value only then I'm ok with it. Here's what I mean with that. 
Assume I have a big XML file being part of my config map, I'd like to be able just to edit the file itself, iow. the configmap value as if I normally execute `vim mybigconfig.xml` on the server directly through `kubectl edit configmap/foo --item=mybigconfig` where `--item=mybigconfig` is a key in ConfigMap's or Secret's `Data` map.

**Comment by brendandburns** [comment]
I have a PR for this here:

https://github.com/kubernetes/kubernetes/pull/38445

It's not quite exactly this proposal, but I can adapt it to match this syntax if you want.

**Comment by brendandburns** [comment]
@smarterclayton there is a separate similar feature request filed here https://github.com/kubernetes/kubernetes/issues/36222

**Comment by brendandburns** [comment]
and I think the bulk of the use case is for things that wrap things, it is super annoying to update a large config map item via the existing `edit` + YAML formatting
