### ISSUE TITLE
kube-proxy nodeport opennings fail silently

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#37979]
When kube-proxy fails to open a nodeport, it gives up setting up the rest of the iptables rules for the service. https://github.com/kubernetes/kubernetes/blob/release-1.5/pkg/proxy/iptables/proxier.go#L1105
Leaving the service not usable. Cannot even use it with clusterIP. Kube-proxy only logs this error in `kube-proxy.log`. No useful information can be retrieved with kubectl. 

Need to record a event at least.

**Comment by cmluciano** [comment]
Ideally would the changes be removed and then reported back? Is there a preferred log or place to return the error?

**Comment by k82cn** [comment]
@freehan, the event maybe a better solution; as other port maybe success.

**Comment by freehan** [comment]
Need to surface the problem somewhere. An event seems okay

**Comment by k82cn** [comment]
@freehan , there's `record.EventBroadcaster` and `record.EventRecorder` in `app.ProxyServer`; should we reuse it or create new recorders for `iptables`?

**Comment by freehan** [comment]
@k82cn Just reuse it. After all, it is within the same component. Are you going to submit a PR?

**Comment by k82cn** [comment]
sure, my pleasure.

**Comment by freehan** [comment]
@k82cn Great! Thanks! Let me know when the PR is ready.
