### ISSUE TITLE
Vendored dependencies clash with other projects in Bazel

### ISSUE THREAD

**Issue by sayrer** [kubernetes/kubernetes#38006]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No.
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

"bazel"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report.

**Kubernetes version** (use `kubectl version`):

master.

**What happened**:

golang.org/x/net/context clashed with a dependency in my project because it been vendored as source into the tree.

**What you expected to happen**:

I expected Kubernetes to use go_rules features for vendoring in WORKSPACE, like so

new_go_repository(
  name = "org_golang_x_net",
  importpath="golang.org/x/net",
  commit="f4b625ec9b21d620bb5ce57f2dfc3e08ca97fce6"
)

**How to reproduce it** (as minimally and precisely as possible):

Build a small project that imports Kubernetes as an external dependency like this:

git_repository(
  name = "io_k8s_kubernetes",
  remote = "https://github.com/kubernetes/kubernetes",
  commit = "...",
)

This allows use of the Kubernetes BUILD rules in the remote project. Then, import golang.org/x/net as above and try to use it in a go_binary. The link step will fail.

**Anything else do we need to know**:

I understand there may be concerns I'm not aware of here.  @mikedanese

**Comment by bgrant0607** [comment]
cc @mikedanese

**Comment by mikedanese** [comment]
@ixdy @spxtr

**Comment by ixdy** [comment]
mixing Go vendoring with Bazel vendoring is likely not to work, but things may have improved in the last six months. @sayrer do you have a concrete repro case?
