### ISSUE TITLE
current context set to "" (no character)

### ISSUE THREAD

**Issue by garciaba** [kubernetes/kubernetes#38053]
**Working environment**: 2 CoreOS instances (master+worker)

**Problem**: Current-context set to ""

**Steps to reproduce:**
 Basically, use this command:

`$ kubectl config set-context $CONTEXT --namespace=<insert-namespace-name-here>`

without any value in the $CONTEXT environment.

Now I can't switch back to any namespaces.

```
$ kubectl config view 
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
```

**Comment by AdoHe** [comment]
@garciaba so why would you like `context` to be empty?

**Comment by garciaba** [comment]
@AdoHe wouldn't, but if by chance you use the command above without setting the $CONTEXT environment, it gets the current context to "" and I didn't find a way back to switch to the default environment nor kube-system.

**Comment by AdoHe** [comment]
@garciaba so I think kubectl should validate argument, this could be a ux enhancement.

**Comment by garciaba** [comment]
@AdoHe definitely. But also, I can't switch back to use a different namespace, hence I had to specify the namespace every time I use kubectl. Or at least I couldn't find a way to do that.

**Comment by zjj2wry** [comment]
relate with #7804

**Comment by liggitt** [comment]
Same issue as #56747, fixed in https://github.com/kubernetes/kubernetes/pull/56769
