### ISSUE TITLE
split api in to cluster and pod/user portions

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#3806]
### Api getting to big for end-users to browse
@bgrant0607 pointed out that when you go to http://kubernetes.io/third_party/swagger-ui/ and browse an api version, you see  at the top things like "bindings", "endpoints" and "nodes".  These are not the most important things for end users (people working through the examples) to understand.  
The most important things for most users to see are pods and services (and replicationControllers, though we talked about putting those into a plugin.
 
### Not all resources make sense to namespace
The primary purpose of a Namespace is to prevent collision of names between actors who cannot practically cooperate on name choice, and a way to manage visibility of names.  

Nodes don't need to be kubernetes namespaced because the nodes already have collision-free names (DNS addresses or IP addresses).  (See also my comments on #3613)

Bindings don't necessarily need a namespace in their path.  They could instead have a PodNamespace in the body of the request.   In fact, doing it that way would work better with a Bulk Binding operation. 

Events don't necessarily need a namespace in their path.  They refer to involvedObjects that have namespaces.  But the name of the event itself doesn't need to be namespaced because the system can generate a collision-free name.

In #3057, I claimed that ResourceQuota is not inherently namespaced.

### Proposal for split

Split resources into "user" and "cluster" categories.  Have a separate "api" prefix for each of these.
 - Probably everything in the "user" category has a namespace in its URL.
 - Probably nothing in the "cluster" category has a namespace in its URL
 - Cluster API Resources
   - nodes
   - bindings
   - admission control stuff
   - events
 - User API Resources
   - pods
   - services
   - replicationControllers (unless moved into another API plugin) 
   - endpoints (just a special query about pods)

Not sure when we do this. This might be a v1 or post v1 thing.

**Comment by derekwaynecarr** [comment]
In #3057, I replied that a quota that is not scoped to a ```Namespace``` is ```SomethingElse```.

Aside from that, I agree that we have some resources that are scoped to a ```Namespace```, and some set of resources that are not ```Node```.  The set of resources that fall in either bucket will grow over the course of time, so we should define the pattern to handle that now prior to 1.0.

I think the issue not noted here, but is implied, is that ```kubectl``` and ```apiserver``` need to provide the proper hooks to know if they are working with a resource external to a ```Namespace```.  As part of #3613, I will need to take a stab at how to handle this in order for that to proceed.

I think this should be a v1 thing.

**Comment by derekwaynecarr** [comment]
To elaborate, I DO NOT think we should have an object that can exist both internal to a ```Namespace``` and external to a ```Namespace```.  I think if you have that use case, the object is actually two different things.  As a result, per the quota discussion, that is why I said a ```ResourceQuota``` is what the thing is that is scoped to a namespace, but ```SomethingElse``` is the thing that is external to a namespace.

**Comment by bgrant0607** [comment]
We previously discussed grouping related API objects/methods in #635.  

While a single api prefix can be convenient for users, it becomes less so as the API becomes bigger. Our analogous internal API has almost 100 methods, most of which are for cluster/node management and administrators. The user-facing part of the API has grown more slowly. We will need a way to narrow the amount of API surface exposed to end users.

Nit: I think we might need events on both API prefixes. Users will definitely interact with events relevant to their objects.

End users just using kubectl wouldn't notice any difference.

/cc @smarterclayton

**Comment by smarterclayton** [comment]
+1

----- Original Message -----

**Comment by derekwaynecarr** [comment]
I think its pretty-trivial to handle this split in ```kube-apiserver``` if we just modify the ```RESTStorage``` interface to report if the object it manages is internal or external to a ```Namespace```.  Given that, we can make the right choices in exposing URLs, and I think that aligns nicely that an object is either external or internal to a ```Namespace``` but never both.

As for the client CLI, we can keep it pretty generic by doing the following:

kubectl get -> this continues to work with namespace scoped resources
kubectl get --cluster=true -> this works with cluster scoped resources

**Comment by smarterclayton** [comment]
It also applies to create/update/delete/describe/wait/other-new-generic resources.  

----- Original Message -----

**Comment by derekwaynecarr** [comment]
Agreed, whatever we name the flag to say the resource is cluster scoped would need to be accepted on all the verbs supported by kubectl.  

Given that Namespace as kind is blocked by this, I will look to do a prereq pull request that enables the described pattern.

**Comment by derekwaynecarr** [comment]
I would like to propose the following changes:

On the ```kube-apiserver``` side of things:

```
type Scope string
const (
  NamespaceScope Scope = "ns"
  ClusterScope Scope = "cluster"
)
RESTStorage interface {
  ...
  // Scope returns the scope of the resource in the system
  Scope() Scope
}
```

```apiserver.go``` would introspect ```Scope()``` and install ```NamespaceScope``` resources at the proper place in the path, and it would install ```ClusterScope``` resources in the path associated with the ```Kind```.

On the ```kubectl``` side of things, we would support a new parameter on all verbs:

```kubectl ([-s scope] | ...)```

Where ```scope``` is the one of ```cluster``` or ```namespace```, the default is ```namespace```, and the usage of scope would control injection of the ```NamespaceParam``` in the requests resource builder.

**Comment by derekwaynecarr** [comment]
The first usage of this feature would be in Namespace as Kind work, but we could then port ```Node``` to follow the same pattern.

**Comment by thockin** [comment]
This appears to be subsumed by myriad other work both completed and in progress.  Specifically api groups.
