### ISSUE TITLE
VpcLimitExceeded: The maximum number of VPCs has been reached

### ISSUE THREAD

**Issue by metral** [kubernetes/kubernetes#38069]
Hitting this flake during testing:

`error running task "vpc/aws-kops-agent-pr-17-0.test-aws.k8s.io" (9m45.748449064s remaining to succeed): error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached`

Output & logs:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/38032/pull-kubernetes-e2e-kops-aws/2715

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/38032/pull-kubernetes-e2e-kops-aws/2715?log#log

**Comment by lansz** [comment]
This is not an issue of k8s, you need file a case to AWS support increase your VPC limit, which default number is 5.

**Comment by justinsb** [comment]
Our e2e is leaking them though (I believe we know about it, but good call to track it @metral )

cc @zmerlynn

**Comment by zmerlynn** [comment]
And it's already being cleaned by the janitor script, so this should be
closed.

**Comment by metral** [comment]
Closing per @zmerlynn's suggestion
