### ISSUE TITLE
Why not add container's diskio limit?

### ISSUE THREAD

**Issue by workhardcc** [kubernetes/kubernetes#38095]
For now k8s has  Pod CPU and Memory Limits. But sometimes we also need diskio limit.
I can `echo "8:16 52428800" >blkio.throttle.write_bps_device` for one container, but it's not automate, cause  I don't know which node will be used by this time for this pod . At the same time I need figure out which device will be use(I mean device number, like 8:16).
I think maybe k8s do this more better.

**Comment by garenwen** [comment]
Why do you close this issue？I really want to solve this issue！
