### ISSUE TITLE
Cleanup non-official branches from kubernetes repository.

### ISSUE THREAD

**Issue by kad** [kubernetes/kubernetes#38103]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): branch, revert

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version** (use `kubectl version`): master branch

**Environment**:
- **Cloud provider or hardware configuration**: none
- **OS** (e.g. from /etc/os-release): N/A
- **Kernel** (e.g. `uname -a`): N/A
- **Install tools**: N/A
- **Others**: N/A

**What happened**:

Document doc/design/versioning.md describes official branches to be used in Kubernetes project repositories: "master", "release-X.Y", "release-X.Y.Z".
At the moment, we have in kubernetes/kubernetes repository bunch of branches that are violating those naming conventions and most of them seems to be accidental pushes by people who has direct push rights to the repository. I think it is needed to be cleaned up from repository and potentially automatic check to be implemented to automatically clean-up them on appearance.

```shell
$ git branch -a | grep remotes/origin | grep -Ev "origin/(master|release-|gh-pages)"
  remotes/origin/1.3.6
  remotes/origin/1.3.7
  remotes/origin/Dec/mounttype
  remotes/origin/Dec/nfsv3
  remotes/origin/Nov/nfshung
  remotes/origin/caesarxuchao-patch-1
  remotes/origin/eparis-unset-class-doc-typo
  remotes/origin/foxish-add-cla
  remotes/origin/foxish-patch-1
  remotes/origin/foxish-remove-google-cla
  remotes/origin/jszczepkowski-ha-e2e-disabled
  remotes/origin/jszczepkowski-ha-feature
  remotes/origin/kube-volume-owner
  remotes/origin/mbohlool-patch-1
  remotes/origin/patch-owners-vsphere
  remotes/origin/revert-26501-scheduler
  remotes/origin/revert-30701-28695_suppress_noisy_output
  remotes/origin/revert-32200-storage-03-enable-test
  remotes/origin/revert-32251-fix-oom-policy
  remotes/origin/revert-32841-revert-32251-fix-oom-policy
  remotes/origin/revert-33014-feature/set-image-id-manifest-digest
  remotes/origin/revert-33209-automated-cherry-pick-of-#33143-upstream-release-1.4
  remotes/origin/revert-33343-automated-cherry-pick-of-#33342-upstream-release-1.3
  remotes/origin/revert-33347-fix_32900
  remotes/origin/revert-33795-add-network-node-e2e
  remotes/origin/revert-33850-add_e2e_test_for_kubectl_in_pod
  remotes/origin/revert-34011-revert-33795-add-network-node-e2e
  remotes/origin/revert-34570-Oct/pd-tests
  remotes/origin/revert-35167-err
  remotes/origin/revert-35697-upgrade-tests
  remotes/origin/revert-36166-remove_mount_rootfs_flag
  remotes/origin/revert-36210-flex_node_conditions
  remotes/origin/revert-36610-Nov/nfsv3
  remotes/origin/revert-36625-branch-eliminate-recursive-call-attemptToUpdateMasterRoleLabelsAndTaints
  remotes/origin/revert-36864-fix-path-to-kubectl-in-gke-test
  remotes/origin/revert-37085-rv
  remotes/origin/revert-37095-kubemark_logrotation
  remotes/origin/revert-37243-petset-e2e-rename
  remotes/origin/revert-37356-jszczepkowski-ha-feature
  remotes/origin/revert-37389-statefulset-skip-gke
  remotes/origin/revert-37582-Nov/retrynfsv3
$
```

**What you expected to happen**:
```shell
$ git branch -a | grep remotes/origin | grep -Ev "origin/(master|gh-pages|release-)"
$
```

**How to reproduce it** (as minimally and precisely as possible):
```shell
$ git clone https://github.com/kubernetes/kubernetes
$ cd kubernets
$ git branch -a | grep remotes/origin | grep -Ev "origin/(master|gh-pages|release-)"
```

**Anything else do we need to know**:

**Comment by foxish** [comment]
cc @kubernetes/contributor-experience

**Comment by thockin** [comment]
I am not sure how these are being created.  I know that github reverts do
this (blech) but there are a bunch by people that appear to be private.  I
will figure it out.

**Comment by thockin** [comment]
I am removing old revert-* branches now.

**Comment by thockin** [comment]
@david-mcmahon there are branches (not tags) for 1.3.6 and 1.3.7 - that's
wrong.  Do we know what happened?

**Comment by foxish** [comment]
When someone with write privileges tries to edit a file in the github UI, that usually creates a new branch. I can see some of these being created due to that.

**Comment by spxtr** [comment]
GittHub reverts do this, so please use your own branch and `git revert` manually.

We can close PRs like #37013 with a message saying "please make a new PR from your own fork" as soon as they are opened. Is that worth doing? Do we also close revert branches?

**Comment by thockin** [comment]
If *all* we had were revert branches, I could live with that, but we have
some that appear to be work branches.  We should quash that.

**Comment by jessfraz** [comment]
oooo yes I am +1 this, i hate straggling branches

**Comment by david-mcmahon** [comment]
@thockin Looks like those branches were created accidentally by the SQ?

```
$ git for-each-ref --format='%(committerdate) %09 %(authorname) %09 %(refname)' | sort -k5n -k2M -k3n -k4n |fgrep /1.3.
Mon Sep 12 15:29:38 2016 -0700 	 Kubernetes Submit Queue 	 refs/remotes/upstream/1.3.7
Tue Oct 25 11:54:30 2016 -0700 	 Kubernetes Submit Queue 	 refs/remotes/upstream/1.3.6
```

**Comment by eparis** [comment]
*boggle* how did the submit queue create a branch?

**Comment by david-mcmahon** [comment]
Perhaps it's better to say, the branch object own is the "Kubernetes Submit Queue" and that's all we know.

**Comment by thockin** [comment]
Any feeling on whether it is safe to nuke these (obviously errant) branches?

**Comment by david-mcmahon** [comment]
@thockin I can say they are no official branches and are not related to releases AFAIK.  Unfortunately we don't have any real ownership of them beyond "SQ".  I'd say nuke them.

**Comment by thockin** [comment]
cleaned up

**Comment by eparis** [comment]
I've done branch cleanups at least 3 times in the past. Should this somehow become a regular task? Not sure how, just starting to think about it.

**Comment by kad** [comment]
With revert-* branches, maybe it's good idea to add code to submit queue robot to cleanup revert branch after it being merged ?
