### ISSUE TITLE
Validation for Custom Resource contents

### ISSUE THREAD

**Issue by fabxc** [kubernetes/kubernetes#38117]
_Feature Request_

When adding objects for a TPR type, create and update operations succeed as long as the contents are valid JSON. The closest thing to user feedback controllers of those TPRs can provide is emitting of an event, which is asynchronous. In practice, we want to prevent invalid objects to be stored from the server side in the first place and also give them useful feedback on what is wrong with it.

Currently, in many cases only consistent operation to perform if a previously valid resource was modified into an invalid state is to tear everything associated with the resource down or halt everything for the user to resolve.

@davidopp mentioned this before in https://github.com/kubernetes/kubernetes/issues/22768#issuecomment-217974215. It was concluded custom tools shipped with custom controllers can handle this on the client side.
However, one of the great things about TPRs is the seamless and native experience. That seems to include no need for a new client tool for anyone who wants to use a custom controller/TPR.

Solutions that came up so far were providing JSON schema specifications with each TPR or arbitrary validation handled by the controller handling a TPR.
The latter seems to be a more powerful and thinner technique. It could be implemented by having the API server to a validation round trip through a specified HTTP endpoint using a standardized protocol.

**Comment by hjacobs** [comment]
@fabxc my 2 cents: JSON schema would be good for users without "deep" integration, i.e. it would nicely fit to allow specifying a [JSON schema](http://json-schema.org/) when creating a TPR. The "HTTP callback" on the other hand would also require building a HTTP service for each use case thus introducing additional burden for users.

FYI: We are currently using TRD to allow defining required OAuth credentials for apps: https://github.com/zalando-incubator/kubernetes-on-aws/pull/154 The controller to process those resources lives outside the cluster (as it iterates over multiple clusters) and a HTTP validation endpoint would therefore introduce an unwanted dependency (either to external service or introducing local cluster validation service).

**Comment by hjacobs** [comment]
Original TPR issue mentions missing validation too: #95

**Comment by AdoHe** [comment]
@fabxc @hjacobs I believe this is just on the schedule :)

**Comment by hjacobs** [comment]
@AdoHe great to hear, any details / links?

**Comment by fabxc** [comment]
Okay thanks. I wasn't sure what was the most recent status given the comment linked in the initial post.
If it's planned and tracked elsewhere, we can close here.

**Comment by Jan-M** [comment]
:+1: for the HTTP callback to the designated/configured operator would work for me.

**Comment by frankgreco** [comment]
@adohe Does the project need/want help implementing this or is it actively being worked on?

**Comment by adohe** [comment]
@frankgreco we did want implement this, but I am afraid we are not going to focus this on 1.7. We are working hard to move TPR to beta in 1.7

**Comment by nikhita** [comment]
I have a design proposal for validation of CustomResources: https://github.com/kubernetes/community/pull/708 :smile:

**Comment by nikhita** [comment]
CRD validation is planned to move to beta in 1.9: https://github.com/kubernetes/kubernetes/issues/53829.

**Comment by nikhita** [comment]
Design details for webhook validation: https://github.com/kubernetes/community/pull/1418.

**Comment by liggitt** [comment]
Validation is available now. Additional changes will have their own proposals/trackers

/close
