### ISSUE TITLE
Sub-resources for Custom Resources

### ISSUE THREAD

**Issue by fabxc** [kubernetes/kubernetes#38113]
_Feature Request_

Custom controllers can be implemented on top of TPRs (e.g. [prometheus-operator](https://github.com/coreos/prometheus-operator) and [etcd-operator](https://github.com/coreos/etcd-operator). 
In our custom resources we still want to provide a `status` field which is updated by the controller, to inform about the current status of whatever is being managed by the TPR's controller. This can currently not be done safely (to my knowledge) as users may accidentally modify the status section of a TPR to an inconsistent state as it is part of the main resource JSON.

Ideally there would be an option to have sub-resources in TPRs (just like Deployments, StatefulSets, etc. have) which is modified independently through its own API endpoint.

**Comment by foxish** [comment]
cc @kubernetes/sig-api-machinery

**Comment by deads2k** [comment]
Providing a `/status` subresource requires semantic knowledge of the type being stored.  By their nature, TPRs do not provide that semantic knowledge to the API server hosting them.  I don't think we should get into the business of interpreting what various fields inside of a TPR mean (barring perhaps `metadata`), so I think that if you want to have that degree of control, you should create your own API server to provide your type.

**Comment by liggitt** [comment]
> I think that if you want to have that degree of control, you should create your own API server to provide your type.

I agree

**Comment by foxish** [comment]
Writing one's own APIServer to support one's type seems like a lot of effort.

I feel like there is value in this request. We have several applications making use of third party resources to communicate state with k8s (for example, with Spark native support, we use TPRs to make the usually opaque state of Spark jobs visible to k8s). The ability to include semantic information in a TPR and providing guarantees about the existence of some sub-resources could be valuable as encourage the use of TPRs alongside ThirdParty controllers. Additionally, in order to leverage and use objects like a PodDisruptionBudget with custom controllers, we would need to provide certain sub-resources (at least as per the current implementation). 

@davidopp @kow3ns @kubernetes/sig-apps

**Comment by fabxc** [comment]
>  you should create your own API server to provide your type.

I get the general sentiment. Similar points apply and were raised on validation for TPRs (#38117). If its decided that TPRs will definitely stay opaque to Kubernetes, we'll have to deal with it. In fact, providing a status endpoint ourselves is what we decided to do in the meantime for the [Prometheus Operator](https://github.com/coreos/prometheus-operator).

For us and many people I talked to, the idea of installing a custom controller in your cluster and thereby extending its functionality for all users at once is very appealing. That fundamentally doesn't work if we have to rollout custom client tooling and separate API servers and comes with a lot more friction for users.

Realistically most controller authors would probably opt for no validation (emit error event + halt) and not providing features like status information or creating a separate `XStatus` resource for every resource `X` instead of providing custom CLIs and API servers.

**Comment by bgrant0607** [comment]
Quick response for now: We should support common subresources needed by workload controllers, such as /status and /scale.

cc @erictune

**Comment by deads2k** [comment]
> Quick response for now: We should support common subresources needed by workload controllers, such as /status and /scale.

The main reason that `/status` has value is the ability to control which bits of a resource a "normal" client can update and which bits of a resource a "privileged" client can update.  Doing this means interpreting and stomping out certain parts of an object.

`/scale` is even more tenuous.  Each resource decides which part of its object gets controlled.  Its different for different resources.  See `Jobs` versus `Deployment`.

Even if we decide to do this, I can't get behind adding more features to an already fragile, error prone, and potentially unworkable API such as we have in TPRs.  https://github.com/kubernetes/features/issues/95

**Comment by bgrant0607** [comment]
@deads2k I agree we need to fix TPR before adding new features. It would be useful to have a common understanding of its direction and intended use cases (vs apiserver federation) as we plan/design the fixes.

**Comment by AdoHe** [comment]
```
Even if we decide to do this, I can't get behind adding more features to an already fragile, error prone, and potentially unworkable API such as we have in TPRs. kubernetes/features#95
```
This is just what I am concerned, and of course we are enhance it continuously

**Comment by lavalamp** [comment]
I agree with Brian, I think it would be useful for TPR to be able to
"opt-in" to our common patterns. spec, scale, and status are the obvious
three. We would need clear rules about what checking the relevant box says
about the schema of your TPR.

**Comment by bgrant0607** [comment]
I'm also thinking that perhaps we should factor out functionality needed by both built-in and third-party controllers, such as status reporting. That could be added to a decoupled controller API, such as Service. The endpoints controller primarily monitors a set of pods and looks at status such as readiness.

**Comment by kargakis** [comment]
Are we assuming that TRP implementations will be workload controllers only? Certainly, operators are a neat idea but so is the idea of expressing relations between api objects (AppController, OpenShift triggers also fit here).

**Comment by bgrant0607** [comment]
@kargakis TPRs are not for workload controllers only. They are already being used more broadly than that. However, that doesn't mean they shouldn't support (optional) features for common use cases.

**Comment by derekwaynecarr** [comment]
For historical reference, there was a long discussion on spec/status on the original issue here:
https://github.com/kubernetes/kubernetes/pull/11781#issuecomment-124272512

I think it was a mistake to not have spec/status as a split from the beginning of this resource.  That said, I see how this is just the beginning of feature creep around TPR, and it would be amazing if we make creating your own API server for your new type as easy as provisioning a new TPR (i.e. a sample pod, with a configmap that declares your type with spec/status in their by default).

**Comment by hongchaodeng** [comment]
> we make creating your own API server for your new type as easy as provisioning a new TPR

Can you clarify more on this? Any references?

**Comment by enisoc** [comment]
I would like to begin working on a proposal for this. If anyone else is interested as well, or has already started working on one, please let me know.

**Comment by nikhita** [comment]
@enisoc As a part of Google Summer of Code, I will be sketching out a proposal for this soon. :tada:

**Comment by enisoc** [comment]
@nikhita That's great! I have been researching some options, but did not start writing yet. Please tag me when you have a proposal as I would like to comment.

**Comment by nikhita** [comment]
@enisoc Sure, will do! :+1:

**Comment by mandarjog** [comment]
just to be sure, the sub resource discussion should now apply to CRDs? We have a potential need for status sub resource for CRDs in Istio.

**Comment by nikhita** [comment]
@mandarjog Yes, it's now applicable to CRDs (not TPRs). The deprecated TPR will be completely removed in 1.8.

**Comment by six8** [comment]
I've been using another CRD for the status of other CRDs. It works for now until there's a better alternative.

**Comment by adohe** [comment]
@nikhita I am just out of CRD context for a period of time, could you please forward the SubResource proposal to me?

**Comment by nikhita** [comment]
@adohe It's still a bit sketchy, will take another few days. Will let you know. :+1:

**Comment by nikhita** [comment]
Proposal for SubResources of CustomResources: https://github.com/kubernetes/community/pull/913 :tada:
