### ISSUE TITLE
rename build-tools/ back to build/

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#38126]
As part of the Bazel effort, in #35453 we had to rename `build/` to `build-tools/`, as `build/` and `BUILD` conflicted on case-insensitive filesystems (like macOS).

Bazel 0.4.1 has now been released, which includes the fix for https://github.com/bazelbuild/bazel/issues/552, allowing us to use `BUILD.bazel` instead of `BUILD`.

I'd like to rename `build-tools/` back to `build/`, to be consistent with how the repo has been in older releases, and I'd like to cherry-pick this into 1.5 as well, so we don't have to special case in other repos for months. It's probably too close to cherry-pick for 1.5.0, but it should be fairly safe for 1.5.1 IMO.

cc @mikedanese @spxtr @thockin @saad-ali

**Comment by ixdy** [comment]
We probably don't want to do this on master until we're ready to cherry-pick to 1.5, as otherwise other cherry-picks to 1.5 that affect `build-tools/` or `build/` will get pretty messy.

**Comment by dims** [comment]
@ixdy Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by mikedanese** [comment]
It sound like @ixdy wants this in the v1.5 release branch.

**Comment by ixdy** [comment]
Yep, what @mikedanese said I said. :)

**Comment by ixdy** [comment]
All done.
