### ISSUE TITLE
kube-proxy fails to recover from out of disk

### ISSUE THREAD

**Issue by JonathanFraser** [kubernetes/kubernetes#38129]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): 
No, bug report

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): 
kube-proxy, kube-proxy not ready, kube-proxy fails to recover

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Cloud provider or hardware configuration**:
 Azure 4xStandard D2 v2 + 1xStandard D2 v2 master
- **OS** (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`):
`Linux k8s-master-1480624263-0 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

- **Install tools**:
- **Others**:

**What happened**:
Disks ran out of space due to job persistence. I cleared the jobs to restore disk space however the kube-proxy pods stayed in a failed "not ready" state. The daemon set was reporting 5/5. Deleteing the kube-proxy pods allowed for recover

**What you expected to happen**:
The cluster should self heal once the error condition is removed. 

**How to reproduce it** (as minimally and precisely as possible):
Run the nodes out of disk. 

**Anything else do we need to know**:

**Comment by bprashanth** [comment]
I think kubeproxy dies, then fails an admission check, then never gets started really. I can't find the old issue about this, maybe someone from @kubernetes/sig-node remembers.

**Comment by yujuhong** [comment]
> I think kubeproxy dies, then fails an admission check, then never gets started really. I can't find the old issue about this, maybe someone from @kubernetes/sig-node remembers.

#35521?

**Comment by dchen1107** [comment]
Might be related to https://github.com/kubernetes/kubernetes/issues/22212?

**Comment by JonathanFraser** [comment]
#35477 looks like the same issue
