### ISSUE TITLE
Deletion of SOME Federated Objects fails

### ISSUE THREAD

**Issue by kshafiee** [kubernetes/kubernetes#38133]
This issue applies to federation objects such as: secret, namespace, deployment
===================================================

NAMESPACE:
I used namespace.yaml as following to create namespace 'federation3'

```
apiVersion: v1
kind: Namespace
metadata:
  name: federation3
```

The creation is successful. Upon deletion, namespace 'federation3' does NOT get deleted from underlying cluster, the STATUS goes to 'Terminating on federation. The error I get is:

> "E1205 19:44:07.779025    8338 namespace_controller.go:367] Failed to ensure delete object from underlying clusters finalizer in namespace federation3: failed to add finalizer orphan to namespace : Operation cannot be fulfilled on namespaces "federation3": the object has been modified; please apply your changes to the latest version and try again"

========================================================

SECRET:
I used "kubectl -s http://localhost:8888 create secret generic test" to create secret 'test'

The creation is successful. Upon deletion, secret 'test' does NOT get deleted from underlying cluster, however, it DOES get deleted from the federation. The error I get is:

> "E1205 19:41:35.950224    8338 secret_controller.go:341] Failed to ensure delete object from underlying clusters finalizer in secret test: failed to add finalizer orphan to secret : Operation cannot be fulfilled on secrets "test": the object has been modified; please apply your changes to the latest version and try again"

============================================================

DEPLOYMENT:
I used nginx-deployment.yaml as in the link below to create deployment 'nginx-deployment':

http://kubernetes.io/docs/user-guide/deployments/

The creation is successful. Upon deletion, deployment 'nginx-deployment' DOES get deleted from the federation, however, it does NOT get deleted from the underlying cluster:

> ubuntu@kaveh-ubuntu-dev:~/work/src/k8s.io/kubernetes$ cluster/kubectl.sh get deployment
> NAME               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
> nginx-deployment   0         0         0            0           13m
> 

 The error I get is:

> "E1205 19:53:48.980560    8338 deploymentcontroller.go:510] Failed to ensure delete object from underlying clusters finalizer in deployment nginx-deployment: failed to add finalizer orphan to deployment : Operation cannot be fulfilled on deployments.extensions "nginx-deployment": the object has been modified; please apply your changes to the latest version and try again"

**Comment by kshafiee** [comment]
@madhusudancs @XiaoningDing @nikhiljindal

**Comment by madhusudancs** [comment]
cc @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
`Failed to ensure delete object from underlying clusters finalizer` error is fine as long as it eventually succeeds (controller keeps retrying).

For secrets, deployments and all other federation resources, deleting them from federation control plane using kubectl does not delete them from underlying clusters. We need a way for users to be able to specify --cascading=true with kubectl delete.

I looked at the ns issue and tried to create and then delete a federation ns and it worked fine for me.
@kshafiee Did you have any resources in the namespace when you tried deleting it?

**Comment by nikhiljindal** [comment]
@kshafiee Whats the version you are running? Are you on HEAD or 1.5 beta or 1.4?

**Comment by kshafiee** [comment]
Thanks @nikhiljindal 
It looks like there is no resource in the namespace, i.e., `kubectl get X` returns nothing
I am on HEAD

**Comment by kshafiee** [comment]
namespace_controller.go:350] Failed to delete federation3: error in deleting resources in namespace federation3: failed to delete service list: no kind "DeleteOptions" is registered for version "federation/v1beta1"``

**Comment by nikhiljindal** [comment]
I tried again on fresh HEAD cluster and namespace deletion worked fine for me. I am going to wait till someone else reports the same issue.

**Comment by dims** [comment]
@kshafiee @nikhiljindal Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by nikhiljindal** [comment]
Cleared the milestone, thx

**Comment by zhouhaibing089** [comment]
I am on tag 1.5.2, and it happened to me that namespace deletion does not work, coz it failed to delete services:

```
E0314 08:06:52.242647   30991 namespace_controller.go:354] Failed to delete haibzhou: error in deleting resources in namespace haibzhou: failed to delete service list: no kind "DeleteOptions" is registered for version "federation/v1beta1"
```

**Comment by liggitt** [comment]
@zhouhaibing089 see https://github.com/kubernetes/kubernetes/issues/34519

**Comment by zhouhaibing089** [comment]
@liggitt thanks for pointing it out, in my case, I use the same `kubectl` built from the same tag... so basically, I don't think the issue was gone, I can provide more information if I can, currently, all I see, the error is coming from this line: https://github.com/kubernetes/kubernetes/blob/v1.5.2/pkg/apiserver/resthandler.go#L902.

**Comment by nikhiljindal** [comment]
@zhouhaibing089 Can you send your output of `kubectl version`?
Do you see that error only while deleting namespace? What if you delete the service directly by running `kubectl delete svc <svcName>`. Does that work fine? For all other resources?

**Comment by zhouhaibing089** [comment]
Looking at the code of deletion logic, `services` happened to to be the first one which fails the request, I am worried about that the `DeleteCollection` does not work for all of other resources.

**Comment by zhouhaibing089** [comment]
OK, now I am sure that this is a client issue:

I added a line of code there:

```console
$ git diff
diff --git a/pkg/apiserver/resthandler.go b/pkg/apiserver/resthandler.go
index 4ad8372..db14887 100644
--- a/pkg/apiserver/resthandler.go
+++ b/pkg/apiserver/resthandler.go
@@ -897,6 +897,8 @@ func DeleteCollection(r rest.CollectionDeleter, checkBody bool, scope RequestSco
                                        return
                                }
                                defaultGVK := scope.Kind.GroupVersion().WithKind("DeleteOptions")
+                               fmt.Printf("delete collection: %+v\n", defaultGVK)
+                               fmt.Printf("delete collection: %s\n", string(body))
                                obj, _, err := scope.Serializer.DecoderToVersion(s.Serializer, defaultGVK.GroupVersion()).Decode(body, &defaultGVK, options)
                                if err != nil {
                                        scope.err(err, res.ResponseWriter, req.Request)
```

and see logs from federation-apiserver

```
delete collection: /v1, Kind=DeleteOptions
delete collection: {"kind":"DeleteOptions","apiVersion":"federation/v1beta1"}
```

**Comment by nikhiljindal** [comment]
Thats interesting.
We now have kubectl tests on HEAD which are green, so this is fixed on HEAD.

**Comment by zhouhaibing089** [comment]
@nikhiljindal specifically, which fix are you mentioning about kubectl?

**Comment by zhouhaibing089** [comment]
Well, this [PR](https://github.com/kubernetes/kubernetes/pull/38330) seems relevant.

**Comment by zhouhaibing089** [comment]
@nikhiljindal I will test with that commit picked in, and once it proves to be working, could we pick that commit in 1.5 branch?

**Comment by zhouhaibing089** [comment]
Well, yes, after the fix picked, the deletion works.

**Comment by zhouhaibing089** [comment]
Refer: https://github.com/kubernetes/kubernetes/pull/43190. @nikhiljindal
