### ISSUE TITLE
Add support for Custom VNET in a different Resource Group in Azure

### ISSUE THREAD

**Issue by mogthesprog** [kubernetes/kubernetes#38134]
**Feature Request**

Currently the Kubernetes Azure `cloudprovider` assumes kubernetes is deployed to the same Azure Resource Group as all of the dependencies. In my case our case we're interested in deploying kubernetes to a Virtual Network that sits in a different resource group to the cluster itself, this will enable us to deploy kubernetes to a subnet in a locked down vnet.

I think there might be a few ways to do this. 

1. We can add a `vnetResourceGroup` field to `azure.Config{}`, and if the need arises to do the same for the NetworkSecurityGroup or RouteTable then we could do the same there. We could assume that if the `vnetResourceGroup` isn't provided then the cluster is in the same RG as the VNET.
1. Adding support for Resource IDs (`/subscriptions/UUID/resourceGroup/rgName/resourceType/resourceName/...`). I think this is a substantial change, looking at the code.

I'm inclined to think the first option is best for now, as it's the path of least resistance. What do you think? When we decide what's needed I'm happy to muck in and make the changes :) 

Cheers,

@brendandburns @colemickens

**Comment by colemickens** [comment]
I'm curious for @brendandburns thoughts on this.

I laid out the three options here: https://github.com/Azure/acs-engine/issues/120#issuecomment-262757203

The easiest one is to simply remove the check where we inspect the subnet to make sure the route table is set correctly - the subnet/vnet references aren't used anywhere else. The second easiest is to add `vnetResourceGroup`. The hardest, but most correct is the third option of using full identifiers.

I'm leaning towards the first one in the short term, and the full identifier option in the longer-run; there are some platform improvements that will tie-in nicely with supporting full identifiers, but without requiring reving/versioning the config file.

**Comment by mogthesprog** [comment]
Hadn't thought of the first option, quickly knocked together the [second option](https://github.com/mogthesprog/kubernetes/commit/d644796f50745345219152d9f18a41270f6ea02a). At least I think that's all is needed anyway, but i could be missing something.

I agree with you on the third option, especially about not having a breaking change. If we choose two then I'll raise a PR for the above change. But i'll hold off for now :)

**Comment by colemickens** [comment]
cc: @jpoon

**Comment by colemickens** [comment]
@mogthesprog Is there any chance you'd be willing to remove the subnet-routetable check instead of the second option and see if that meets your needs? I think that's what we want to go with short-term.

Chances are, if people aren't configuring the route table / subnet correctly, then they likely won't find their way to the error message anyway.

(Longer term we hope to move away from needing the config file at all, similar to other clouds.)

**Comment by mogthesprog** [comment]
Yeah sure, I'll knock it up this evening then tag you in the PR :)
