### ISSUE TITLE
vSphere cloud provider Dynamic provisioning should not use white space

### ISSUE THREAD

**Issue by BaluDontu** [kubernetes/kubernetes#38148]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: vSphere
- **OS** (e.g. from /etc/os-release):

> RETTY_NAME="Debian GNU/Linux 8 (jessie)"
> NAME="Debian GNU/Linux"
> VERSION_ID="8"
> VERSION="8 (jessie)"
> ID=debian
> HOME_URL="http://www.debian.org/"
> SUPPORT_URL="http://www.debian.org/support/"
> BUG_REPORT_URL="https://bugs.debian.org/"

- **Kernel** (e.g. `uname -a`):

> Linux kubernetes-master 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) x86_64 GNU/Linux

- **Install tools**: None
- **Others**: None

**What happened**:
When I create a deployment with vSphere cloud provider dynamic provisioning, it creates a volume spec with volume path - **[datastore] kubevols/volume** which contains a white space in it. In this case the cloud provider queries the getDeviceNameFromMount() to return the path of the volume mounted. Since getDeviceNameFromMount() queries the filesystem to get the mount references, it returns a volume path "[datastore]\\040kubevols/volume". Later the kubelet searches for this volume path in both the actual and desired states. Th actual and desired states contains volume with path "[datastore] kubevols/volume". So, it couldn't find such volume path and therefore kubernetes stalls unable to make any progress further similar to one described in #37022.

Also similar issue described in #37712

**What you expected to happen**:
All the pods in the recreated deployment comes up.

**How to reproduce it** (as minimally and precisely as possible):
See above.

**Anything else do we need to know**: None

@abrarshivani @kerneltime @pdhamdhere

**Comment by jingxu97** [comment]
cc @kubernetes/sig-storage
