### ISSUE TITLE
CRI: Support docker 1.10

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#38164]
In K8s v1.5, we focus on supporting docker 1.11. We should also support docker 1.10 which is still supported by Kubernetes.

There are 2 known issues of current CRI integration (forked from https://github.com/kubernetes/kubernetes/issues/29478#issuecomment-248197665):
1) **Separator in seccomp configure is changed from 1.10 to 1.11.**
Docker >=1.11 is using `=` as separator, e.g. `seccomp=unconfined`; while docker <= 1.10 is using `:` as separator, e.g. `seccomp:unconfined`. This will cause error `failed to create a sandbox for pod "XXX": Error response from daemon: Invalid --security-opt: "seccomp=unconfined"` (See docker/docker#24810)
2) ~~**oomScoreAdj is only supported in docker >= 1.11.** Currently we rely on docker to apply oom_score_adj in dockershim, which is only supported in docker >=1.11. If we want to support docker <=1.10, we need to [apply oom score adj ourselves](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker_manager.go#L1684-L1710) in dockershim.~~

There may be other issues with supporting 1.10, we should add comment if we found more.

@yujuhong @feiskyer 
/cc @kubernetes/sig-node

**Comment by Random-Liu** [comment]
Not mark v1.6 for now until we decided to support 1.10 before rolling out CRI integration as default.

**Comment by feiskyer** [comment]
@Random-Liu Do we have ci environment for testing docker v1.10?

**Comment by Random-Liu** [comment]
@feiskyer The only one currently is node e2e ubuntu trusty image.

**Comment by resouer** [comment]
Have we decided that docker <=1.10 should be supported yet? 

btw, I can help with to fix `oomScoreAdj `, the original logic is introduced by one of my previous patch I think.

**Comment by Random-Liu** [comment]
@resouer We won't support docker <= 1.9, but probably 1.10.

**Comment by resouer** [comment]
btw, I think oomScoreAdj is included in docker 1.10, not since docker >= 1.11, see [release note](https://github.com/docker/docker/blob/master/CHANGELOG.md#1100-2016-02-04)

**Comment by Random-Liu** [comment]
> but, I think oomScoreAdj has already included in docker 1.10, not since docker >= 1.11, see release note

If so the dockertools code is wrong:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker_manager.go#L732-L733

**Comment by resouer** [comment]
@Random-Liu `dockerV110APIVersion` is docker version 1.10, and if current version equals or newer than that, we set `oom_sore_adj`: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker_manager.go#L736-L738, do I missed something?

**Comment by Random-Liu** [comment]
@resouer I mean the comment is misleading:
`If current api version is newer than docker 1.10 requested, set OomScoreAdj to HostConfig`

**Comment by dchen1107** [comment]
The initial goal we had is docker CRI support only targets for docker 1.11.x and beyond. Is there any reason we want to change that decision? User requests?

**Comment by yujuhong** [comment]
> The initial goal we had is docker CRI support only targets for docker 1.11.x and beyond. Is there any reason we want to change that decision? User requests?

This is purely for rolling out the CRI implementation as default. If k8s still supports docker 1.10 in the 1.6 release, CRI should also support it.

**Comment by yujuhong** [comment]
Since we are unsure whether docker 1.10 will continue to be supported in 1.6, we should prepare for the worst case (?) and test against 1.10.

The prerequisite of this is to support older separator (`:`) for docker security options. Related PR: #40179

**Comment by yujuhong** [comment]
We now run CRI + docker 1.10 in node e2e.
