### ISSUE TITLE
kubectl logs or exec failed, return not found response

### ISSUE THREAD

**Issue by bigfreeZhou** [kubernetes/kubernetes#38178]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.7-beta.0", GitCommit:"fd8fac83034df346529c6e11aabceea2db48d663", GitTreeState:"clean", BuildDate:"2016-11-16T02:07:21Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.7-beta.0", GitCommit:"fd8fac83034df346529c6e11aabceea2db48d663", GitTreeState:"clean", BuildDate:"2016-11-16T02:02:36Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **OS** (e.g. from /etc/os-release): rhel 7u2
- **Kernel** (e.g. `uname -a`): 3.10.0-327.el7.x86_64

**What happened**:
the pods works well, use kubectl get pod or describe pod is ok:
NAME                       READY     STATUS    RESTARTS   AGE
dmo-commenttest-v1-j8630   1/1       Running   3          10d

but use kubectl logs return error:
Error from server: the server could not find the requested resource ( pods/log dmo-commenttest-v1-j8630)

use kubectl exec also return error:
error: unable to upgrade connection: pod does not exist

only pods on one cluster node have these error, pod on other node do not have these error.

i‘m confused,hope someone can help me, thank you very much.

**Comment by AdoHe** [comment]
@bigfreeZhou please give a try with `kubectl log *** -v=9` and paste the output here, also could you provide the apiserver log?

**Comment by bigfreeZhou** [comment]
@AdoHe 
here is the -v=9 output:

I1206 16:38:18.772544    7150 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.4.1 (linux/amd64) kubernetes/bd85192" http://10.10.64.141:8080/api/v1/namespaces/default/pods/dmo-commenttest-v1-j8630/log
I1206 16:38:18.775145    7150 round_trippers.go:318] GET http://10.10.64.141:8080/api/v1/namespaces/default/pods/dmo-commenttest-v1-j8630/log 404 Not Found in 2 milliseconds
I1206 16:38:18.775160    7150 round_trippers.go:324] Response Headers:
I1206 16:38:18.775167    7150 round_trippers.go:327]     Content-Length: 262
I1206 16:38:18.775174    7150 round_trippers.go:327]     Content-Type: application/json
I1206 16:38:18.775181    7150 round_trippers.go:327]     Date: Tue, 06 Dec 2016 08:38:18 GMT
I1206 16:38:18.775448    7150 helpers.go:193] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource ( pods/log dmo-commenttest-v1-j8630)",
  "reason": "NotFound",
  "details": {
    "name": "dmo-commenttest-v1-j8630",
    "kind": "pods/log"
  },
  "code": 404
}]
F1206 16:38:18.775476    7150 helpers.go:114] Error from server: the server could not find the requested resource ( pods/log dmo-commenttest-v1-j8630)


and i set --enable-debugging-handlers=true.

apiserver log do not have any related log or error, thanks

**Comment by AdoHe** [comment]
@bigfreeZhou `/log` is a subresource of pod, normally all pods should support this, since `log` and `exec` will all call kubelet, and you just met this problem on one node, guess maybe some issues with the node.

**Comment by bigfreeZhou** [comment]
@AdoHe 
thank you for your patient.

I find that there is no tcp link established from apiserver to node 10250 port. i don't known if it is the problem.

further, now all pod one other node is not works well when use kubectl log / exec except pods on the node which is the same host with apiserver.

I'm sure some node works well before, but now only the node with apiserver is ok.

**Comment by yujuhong** [comment]
@bigfreeZhou this is working as intended.

On the master node (where the master components such as apiserver run), the /logs, /exec, /attach are disabled due to security concerns.(`--enable-debugging-handlers=false`). There is also an issue open to report a better error message in this case: #25448

**Comment by bigfreeZhou** [comment]
@yujuhong Actually, I didn't set the --enable-debugging-handlers flag which to be said default value is true. In order to confirm this, I just set --enable-debugging-handlers=true for kubelet, but not help. T.T

**Comment by bigfreeZhou** [comment]
@AdoHe @yujuhong 
I find the probelm. there is a service's external ip is the master node ip, and the port is exactly the apiserver's port. After i delete the service, everything became right.

thanks for your help.

**Comment by prabhamanu** [comment]
@bigfreeZhou  May I know the name of the service ?
