### ISSUE TITLE
redis sentinel in k8s example has wrong ip when i check it in sentinel pods.

### ISSUE THREAD

**Issue by modor** [kubernetes/kubernetes#38176]
Hello,
I created  redis cluster in k8s cluster according to the Document：https://github.com/kubernetes/kubernetes/tree/master/examples/storage/redis.
But  it can not work. Slaves can not find the new master. I found that slave's ips were wrong  in sentinel server.
```
127.0.0.1:26379> SENTINEL get-master-addr-by-name mymaster
1) "172.17.92.3"
2) "6379"
127.0.0.1:26379> SENTINEL slaves  mymaster
1)  1) "name"
    2) "172.17.55.0:6379"
    3) "ip"
    4) "172.17.55.0"
    5) "port"
    6) "6379"
    7) "runid"
    8) ""
    9) "flags"
   10) "s_down,slave"
   11) "pending-commands"
   12) "100"
   13) "last-ping-sent"
   14) "1640785"
   15) "last-ok-ping-reply"
   16) "1640784"
   17) "last-ping-reply"
   18) "1640784"
   19) "s-down-time"
   20) "1580720"
   21) "down-after-milliseconds"
   22) "60000"
   23) "info-refresh"
   24) "1481005183019"
   25) "role-reported"
   26) "slave"
   27) "role-reported-time"
   28) "1640784"
   29) "master-link-down-time"
   30) "0"
   31) "master-link-status"
   32) "err"
   33) "master-host"
   34) "?"
   35) "master-port"
   36) "0"
   37) "slave-priority"
   38) "100"
   39) "slave-repl-offset"
   40) "0"
2)  1) "name"
    2) "172.17.92.2:6379"
    3) "ip"
    4) "172.17.92.2"
    5) "port"
    6) "6379"
    7) "runid"
    8) ""
    9) "flags"
   10) "s_down,slave"
   11) "pending-commands"
   12) "8"
   13) "last-ping-sent"
   14) "1640779"
   15) "last-ok-ping-reply"
   16) "1640779"
   17) "last-ping-reply"
   18) "1640779"
   19) "s-down-time"
   20) "1580720"
   21) "down-after-milliseconds"
   22) "60000"
   23) "info-refresh"
   24) "1481005183019"
   25) "role-reported"
   26) "slave"
   27) "role-reported-time"
   28) "1640779"
   29) "master-link-down-time"
   30) "0"
   31) "master-link-status"
   32) "err"
   33) "master-host"
   34) "?"
   35) "master-port"
   36) "0"
   37) "slave-priority"
   38) "100"
   39) "slave-repl-offset"
   40) "0"
3)  1) "name"
    2) "172.17.72.0:6379"
    3) "ip"
    4) "172.17.72.0"
    5) "port"
    6) "6379"
    7) "runid"
    8) ""
    9) "flags"
   10) "s_down,slave,disconnected"
   11) "pending-commands"
   12) "0"
   13) "last-ping-sent"
   14) "1640782"
   15) "last-ok-ping-reply"
   16) "1640782"
   17) "last-ping-reply"
   18) "1640782"
   19) "s-down-time"
   20) "1580720"
   21) "down-after-milliseconds"
   22) "60000"
   23) "info-refresh"
   24) "1481005183019"
   25) "role-reported"
   26) "slave"
   27) "role-reported-time"
   28) "1640782"
   29) "master-link-down-time"
   30) "0"
   31) "master-link-status"
   32) "err"
   33) "master-host"
   34) "?"
   35) "master-port"
   36) "0"
   37) "slave-priority"
   38) "100"
   39) "slave-repl-offset"
   40) "0"
```
It shows the slave's ip in sentinel server:172.17.72.0,172.17.55.0, in fact i get the slave's ip by the "hostname -i" command:172.17.72.6,172.17.55.8. 
What's wrong with it. How to solve it.

**Comment by Mattchewone** [comment]
I am having the same problem, once the initial master is deleted the sentinels cannot connect to the master and do not elect a new master for some reason. 

Did you manage to solve the issue @modor ?

**Comment by kargakis** [comment]
Please reopen in the kubernetes/examples repo if this still an issue.

**Comment by rogeruiz** [comment]
In case anyone finds this Issue, the fix is to apply the `echo "slave-announce-ip $( hostname -i )" >> redis.conf` to all the redis.conf files you deploy to avoid getting [the Flannel IP address](https://stackoverflow.com/a/37411969) and not use the auto-discovery features of Redis.

**Comment by dineshsckloud9** [comment]
@rogeruiz Facing this same issue in Openshift.

`

18:X 10 May 17:18:19.020 # Next failover delay: I will not start a failover before Thu May 10 17:24:08 2018
--
  | 18:X 10 May 17:24:08.972 # +new-epoch 10
  | 18:X 10 May 17:24:08.972 # +try-failover master mymaster 172.16.68.13 6379
  | 18:X 10 May 17:24:08.974 # +vote-for-leader b96416a67746dac32a276c98a38266b30596f8c9 10
  | 18:X 10 May 17:24:08.979 # 545c522bcf71ffd9ec1108344b676a0fc6a96ae8 voted for b96416a67746dac32a276c98a38266b30596f8c9 10
  | 18:X 10 May 17:24:19.540 # -failover-abort-not-elected master mymaster 172.16.68.13 6379
  | 18:X 10 May 17:24:19.630 # Next failover delay: I will not start a failover before Thu May 10 17:30:09 2018
  | 18:X 10 May 17:30:09.120 # +new-epoch 11
  | 18:X 10 May 17:30:09.121 # +vote-for-leader 545c522bcf71ffd9ec1108344b676a0fc6a96ae8 11
  | 18:X 10 May 17:30:09.130 # Next failover delay: I will not start a failover before Thu May 10 17:36:09 2018

`
Here pod with 172.16.68.13 IP not exist in the cluster

**Comment by zeph** [comment]
@rogeruiz https://github.com/helm/charts/issues/20481#issuecomment-586284301 not sure that would be a solution
