### ISSUE TITLE
Destruction of pods which are in the "Pulling" or related states takes a lot of time

### ISSUE THREAD

**Issue by Oloremo** [kubernetes/kubernetes#38199]
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6+coreos.0", GitCommit:"ec2b52fabadf824a42b66b6729fe4cff2c62af8c", GitTreeState:"clean", BuildDate:"2016-11-14T19:42:00Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6+coreos.0", GitCommit:"ec2b52fabadf824a42b66b6729fe4cff2c62af8c", GitTreeState:"clean", BuildDate:"2016-11-14T19:42:00Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:

libvirt VM
- **OS** (e.g. from /etc/os-release):

Ubuntu 16.04 x64
- **Kernel** (e.g. `uname -a`):

Linux node1 4.4.0-38-generic #57-Ubuntu SMP

**What happened**:
Deletion of the namespace, which contains of the many deployments(~10), which creating a lot of pods(~60) which are in the Pulling or related(ImagePullBackOff, etc) state, takes a lot of time. Like 10 times more than deletion of the same amount of pods which are already pulled.

**What you expected to happen**:
Deletion of the namespace should be much faster, close to the deletion of namespace with already pulled pods.

**How to reproduce it** (as minimally and precisely as possible):
Make sure you have a big(1Gb+) docker images. Delete all local docker images from your nodes. Create new namespace. Create some deployments, which will create 50+ pods, and run `kubectl delete your_namespace` during the pods pulling.

You can repeat same thing with already pulled pods and note that it will take significantly less time.

**Comment by smarterclayton** [comment]
Deleting a pod should abort running pulls.
