### ISSUE TITLE
[k8s.io] Port forwarding 

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#38198]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/37561/pull-kubernetes-e2e-gce/8530/

```
[k8s.io] Port forwarding [k8s.io] With a server that expects a client request should support a client that connects, sends data, and disconnects [Conformance] 21s


[k8s.io] Port forwarding [k8s.io] With a server that expects a client request should support a client that connects, sends data, and disconnects [Conformance] 22s


[k8s.io] Port forwarding [k8s.io] With a server that expects no client request should support a client that connects, sends no data, and disconnects [Conformance] 1m8s
```

I'm seeing this frequently

**Comment by mikedanese** [comment]
I'm getting these very frequently

**Comment by mikedanese** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/31647/pull-kubernetes-e2e-gce-etcd3/8114/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/31647/pull-kubernetes-e2e-gce/8609/

**Comment by mikedanese** [comment]
@sttts is the lucky test owner according to test_owners.csv

**Comment by sttts** [comment]
https://github.com/kubernetes/kubernetes/pull/38194 merged last night. Please rebase.

Moreover, @fraenkel and myself are working on a fix for the flake.

**Comment by sttts** [comment]
Optimistically closing. Please re-open if you still see it after a rebase.
