### ISSUE TITLE
Don't overload User-Agent to express client version

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#38217]
User-Agent doesn't go through all proxies untouched, so we should probably switch to a custom header to state the client version.

(We have fixed some client incompatibilities by looking at User-Agent, so old clients don't get the fix if they go through the wrong proxy.)

**Comment by jlowdermilk** [comment]
As a partial solution, if apiserver looks at both User-Agent and a custom header, it would allow clients that cannot (or don't want to) set User-Agent to continue to get backwards-compatibility support.

**Comment by caesarxuchao** [comment]
To clarify, the custom header needs to express more than the client version, the identity of the caller, i.e., whether it's kubectl or kube-controller-manager, is also important, so I made a PR to set *custom User-Agent* header.

**Comment by liggitt** [comment]
I really don't want to add this. The only use is for API-server-side behavior modifications for specific clients/versions, which I think is a mistake. I don't think we should put effort into expanding our ability to do that… it makes it more acceptable to break API compatibility for non-first-class clients.

**Comment by smarterclayton** [comment]
I tend to agree with Jordan here - I view user agent specific behavior as a code smell that should be deployed in extremely rare scenarios, and in the event that a few proxies strip user agents it doesn't seem to justify it to an increase in the usage of the filtering.

**Comment by caesarxuchao** [comment]
> The only use is for API-server-side behavior modifications for specific clients/versions, which I think is a mistake.

Another use is for printing out the client identity in the api-server log. How about this perspective: the standard user-agent will be modified by proxies, so we should set a custom header. How to use the user-agent value is another issue, we can disapprove future PRs that alter api-server behavior based on user-agent.

**Comment by smarterclayton** [comment]
There is some level of "proxies that are bad break all assumptions of good behavior, therefore the proxy should be fixed."  Can you point me to a proxy example that drops user agents that cannot correctly preserve user agent if so challenged?  In the enterprise space I deal with a lot of terrible proxies, but haven't had this be a huge issue.

**Comment by caesarxuchao** [comment]
Kubernetes users may not control the proxy, that's what I experienced in an internal issue. @jlowdermilk do you have more details on why a proxy has to drop the user-agent?

**Comment by liggitt** [comment]
> the standard user-agent will be modified by proxies, so we should set a custom header

some proxies disallow custom headers as well... not sure an arms race against misbehaving proxies is something we want to get into

**Comment by jlowdermilk** [comment]
@caesarxuchao, I would actually be happy to have backwards compatibility *not* depend on the presence of a custom header. The request I had was that if we do gate apiserver backwards compatibility features on the presence of a header, it should not be user-agent. I tend to agree with @liggitt that having API server-side modifications for specific clients makes it easier to break API compatibility. It would be better if we can avoid breaking backwards compatibility in the first place.
