### ISSUE TITLE
federation: cluster replicasets should not be scaled down when federated rs is deleted using kubectl

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#38223]
Steps to repro:
* fedkubectl create -f myrs.yaml
* fedkubectl delete rs myrs

where fedkubectl is `kubectl --context=federation-cluster`

Expected:
myrs should be deleted from federation control plane. myrs in underlying clusters should be left as is.

Actual:
myrs is deleted from federation control plane fine, but myrs in all underlying clusters are also scaled down to zero. This should not happen. They should be left as is.

Note that this problem exists only when replicaset is deleted using kubectl. Deleting the replicaset directly using the REST API works fine.

cc @kshafiee @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
From what I can tell, this problem has existed since 1.4 when we first introduced federated replicasets (as alpha).

**Comment by nikhiljindal** [comment]
Ref  https://github.com/kubernetes/kubernetes/issues/32826 to add kubectl tests

**Comment by kshafiee** [comment]
@XiaoningDing

**Comment by nikhiljindal** [comment]
We updated `kubectl delete` to perform cascading deletion by default so deleting federation replicaset deletes replicasets from underlying clusters as well. So that works fine.

The same problem however now exists for `kubectl delete --cascade=false` which we need to fix.

**Comment by quinton-hoole** [comment]
Required for GA.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#86.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
