### ISSUE TITLE
AllNodesReady function makes useless errors

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#38220]
https://github.com/kubernetes/kubernetes/blob/c3a2cc53708cdeabdccf6e1a905e8fdf9b35c7c5/test/e2e/framework/util.go#L3940

The %#v in the error message prints a pointer instead of a node name. This should be changed to print something useful for humans looking at test logs.

(Noticed while looking at #37903)

**Comment by wanghaoran1988** [comment]
@lavalamp Would you mind assign this to me?

**Comment by resouer** [comment]
@wanghaoran1988 Yes, just send the PR :) It seems github can not assign issues to non-members ...

**Comment by nebril** [comment]
Seems like this issue is resolved. Please consider closing.
