### ISSUE TITLE
[Upgrade test] "ScheduledJob should not emit unexpected warnings" failing in ci-kubernetes-e2e-gce-1.4-1.5-upgrade-master

### ISSUE THREAD

**Issue by rkouj** [kubernetes/kubernetes#38232]
Test has been failing [100% of the time](https://k8s-testgrid.appspot.com/google-1.4-1.5-upgrade#gce-cvm-1.4-cvm-1.5-upgrade-master&width=20&sort-by-failures=&include-filter-by-regex=ScheduledJob%20should%20not%20emit%20unexpected%20warnings) in [ci-kubernetes-e2e-gce-1.4-1.5-upgrade-master](https://k8s-testgrid.appspot.com/google-1.4-1.5-upgrade#gce-cvm-1.4-cvm-1.5-upgrade-master&width=20&sort-by-failures=). Sample failure: [link](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.4-1.5-upgrade-master/15).

Based on [spreadsheet](https://docs.google.com/spreadsheets/d/1sAZqyWE--0fvN1PIuKTw9JwmcXNz6tQIm1MrjdILtm4/edit#gid=1325239137&vpid=A1) tracking 1.5 upgrade test failures created by @krousey.

**Comment by foxish** [comment]
Since this is moving from alpha to beta, we don't expect the upgrade test to work I think.
/cc @erictune @janetkuo

**Comment by foxish** [comment]
The failure here is of the form:

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduledjob.go:178
Expected error:
    <*runtime.notRegisteredErr | 0xc82139d340>: {
        gvk: {Group: "batch", Version: "v2alpha1", Kind: "CronJob"},
        t: nil,
    }
    no kind "CronJob" is registered for version "batch/v2alpha1"
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduledjob.go:163
```

**Comment by soltysh** [comment]
This is expected to fail, since k8s versions < 1.5 do not have `CronJob` resource, previously named `ScheduledJobs`. This is the effect of the rename (https://github.com/kubernetes/kubernetes/issues/36021). This is not a release-blocker, besides this is still an alpha feature, far from beta.

**Comment by dims** [comment]
@rkouj @soltysh Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by dims** [comment]
per @soltysh we should close all those upgrade tests for ScheduledJobs, since these are not problems which we'll fix

**Comment by krousey** [comment]
@dims Can you not close all of these issues. These need to actually be fixed. I understand that they are not expected to pass, but the tests need to be enhanced to understand that and stop generating noise. Proper version checked guards need to be implemented to skip these tests for version combinations that are expected to fail.

**Comment by krousey** [comment]
And yes they will need the 1.5 milestone as they need to be fixed for 1.5 release process.

**Comment by dims** [comment]
ack @krousey will reopen them

**Comment by soltysh** [comment]
Per @krousey comment, I'll close all others except this one. They are all similar in what they do and there's no need to have 10 of those.

**Comment by krousey** [comment]
@soltysh I'm going to try to fix this next. Is it accurate to say that these tests were introduced in 1.4 and the 1.4 tests are not expected to work with 1.5 masters because the API resource was renamed?

**Comment by krousey** [comment]
@soltysh I was going to add an appropriate guard, but found that it already had one. https://github.com/kubernetes/kubernetes/blob/366366022e0347/test/e2e/scheduledjob.go#L48

```go
	BeforeEach(func() {
		framework.SkipIfMissingResource(f.ClientPool, unversioned.GroupVersionResource{Group: batch.GroupName, Version: "v2alpha1", Resource: "scheduledjobs"}, f.Namespace.Name)
	})
```

Any idea why this isn't skipping the tests? Does 1.5 somehow have the resource in discovery info, can list "scheduledjobs", but cannot create one?

Or is it that it did create one, but the API server responded with "cronjob" and the runtime errored?

**Comment by krousey** [comment]
I can confirm that the above guard is not sufficient. With a 1.5 APIServer, you can create a `ScheduledJob` on the `/apis/batch/v2alpha1/namespaces/{namespace}/scheduledjobs` endpoint, but the API server returns a `CronJob` object.

@kubernetes/sig-api-machinery This seems bad. A client tried to create an object with one type, but received an object of another. If this is special to how the `CronJob` rename was done, then that's fine... it's still alpha.

**Comment by deads2k** [comment]
It shouldn't return a cronjob kind.  If we're going to break backwards compatibility, we may as well remove the old, but I'd prefer to be compatible. Reintroducing the old type and cohabiting would work, but it's heavy.

@smarterclayton do we have a way to force the kind without keeping an old type for the API installer?

**Comment by smarterclayton** [comment]
Not per resource type, no.  When we moved from minions -> nodes it was
across an API boundary (v1beta3 to v1) and we didn't have to expose the
minions endpoint.

The logic would have to create a versioning codec for just one endpoint and
pass it to the RequestScope with the prioritized encoding order being

GVK{Kind: "ScheduledJob", G: "batch", V: "v2alpha1"}
GVK{G: "batch", V: "v2alpha1"}

which would should be enough to ensure that scheduled job is the preferred
kind on output.

**Comment by soltysh** [comment]
@krousey this was intentional to maintain backwards compatibility, some complain about when renaming from SJ to CJ. 
I must admit that this check was the first thing I've looked for when first seeing the bug. I guess we need to redo this check to check version and not resource when it comes to renamed resources like SJ/CJ. Agreed?

**Comment by krousey** [comment]
Please move discussion to #38656

**Comment by xiangpengzhao** [comment]
/close
This issue is no longer valid.
