### ISSUE TITLE
[Upgrade test] "Kibana Logging Instances Is Alive should check that the Kibana logging instance is alive" failing in ci-kubernetes-e2e-gce-1.4-1.5-upgrade-master

### ISSUE THREAD

**Issue by rkouj** [kubernetes/kubernetes#38238]
Test has been failing [100% of the time](https://k8s-testgrid.appspot.com/google-1.4-1.5-upgrade#gce-cvm-1.4-cvm-1.5-upgrade-master&width=20&sort-by-failures=&include-filter-by-regex=%20Kibana%20Logging%20Instances%20Is%20Alive%20should%20check%20that%20the%20Kibana%20logging%20instance%20is%20alive) in [ci-kubernetes-e2e-gce-1.4-1.5-upgrade-master](https://k8s-testgrid.appspot.com/google-1.4-1.5-upgrade#gce-cvm-1.4-cvm-1.5-upgrade-master&width=20&sort-by-failures=). Sample failure: [link](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.4-1.5-upgrade-master/15).

Based on [spreadsheet](https://docs.google.com/spreadsheets/d/1sAZqyWE--0fvN1PIuKTw9JwmcXNz6tQIm1MrjdILtm4/edit#gid=1325239137&vpid=A1) tracking 1.5 upgrade test failures created by @krousey.

**Comment by krousey** [comment]
In the sheet, this is not a blocker, but no justification.

**Comment by saad-ali** [comment]
@Crassirostris You marked this test as a non-blocker in the spreadsheet, could you please provide justification here. As soon as you do, we can remove the release blocker label.

**Comment by Crassirostris** [comment]
I wrote and explanation in https://github.com/kubernetes/kubernetes/issues/38230#issuecomment-265592163

**Comment by saad-ali** [comment]
Thanks!

Based on @Crassirostris's explanation, this is an expected failure, marking issue as non-release-blocking.

**Comment by dims** [comment]
@rkouj @Crassirostris Is it appropriate to move this to the next milestone? (and remove the non-release-blocker tag as well)

**Comment by Crassirostris** [comment]
@dims AFAIU, these tests will always fail, because old tests are used.

**Comment by krousey** [comment]
We should make an effort to remove these failures from the test results. In the future with 1.5 patch releases, we don't want this noise in the test results.

**Comment by crassirostris** [comment]
Closing, as it seems to be obsolete. Feel free to reopen if you think it requires any actions from my side
