### ISSUE TITLE
[Upgrade test] "Nodes [Disruptive] [k8s.io] Resize [Slow] should be able to delete nodes" failing in 

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#38231]
Test has been failing [60% of the time](https://k8s-testgrid.appspot.com/google-1.4-1.5-upgrade#gce-cvm-1.4-cvm-1.5-upgrade-cluster&width=20&sort-by-failures=) in [ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster/). Sample failure: [link](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster/4)

Based on [spreadsheet](https://docs.google.com/spreadsheets/d/1sAZqyWE--0fvN1PIuKTw9JwmcXNz6tQIm1MrjdILtm4/edit#gid=1403603610&vpid=A1) tracking 1.5 upgrade test failures created by @krousey.

**Comment by foxish** [comment]
Same reason as https://github.com/kubernetes/kubernetes/issues/38247#issuecomment-265560696

**Comment by saad-ali** [comment]
> Same reason as #38247 (comment)

Ack, marking non-release blocking.

**Comment by dims** [comment]
@saad-ali @foxish Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by foxish** [comment]
Fixed by 38324, closing.
