### ISSUE TITLE
[Upgrade test] "Addon update should propagate add-on file changes" failing in ci-kubernetes-e2e-gce-1.4-1.5-upgrade-master

### ISSUE THREAD

**Issue by rkouj** [kubernetes/kubernetes#38239]
Test has been failing [100% of the time](https://k8s-testgrid.appspot.com/google-1.4-1.5-upgrade#gce-cvm-1.4-cvm-1.5-upgrade-master&width=20&sort-by-failures=&include-filter-by-regex=Addon%20update%20should%20propagate%20add-on%20file%20changes) in [ci-kubernetes-e2e-gce-1.4-1.5-upgrade-master](https://k8s-testgrid.appspot.com/google-1.4-1.5-upgrade#gce-cvm-1.4-cvm-1.5-upgrade-master&width=20&sort-by-failures=). Sample failure: [link](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.4-1.5-upgrade-master/15).

Based on [spreadsheet](https://docs.google.com/spreadsheets/d/1sAZqyWE--0fvN1PIuKTw9JwmcXNz6tQIm1MrjdILtm4/edit#gid=1325239137&vpid=A1) tracking 1.5 upgrade test failures created by @krousey.

**Comment by krousey** [comment]
Failing for the same reason as https://github.com/kubernetes/kubernetes/issues/38229#issuecomment-265319500

**Comment by dims** [comment]
@rkouj Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)
