### ISSUE TITLE
[Upgrade test] "Nodes [Disruptive] [k8s.io] Resize [Slow] should be able to delete nodes" in ci-kubernetes-e2e-gke-container_vm-1.3-container_vm-1.5-upgrade-cluster

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#38247]
Test has been failing [33% of the time](https://k8s-testgrid.appspot.com/google-1.3-1.5-upgrade#gke-container_vm-1.3-container_vm-1.5-upgrade-cluster&width=20&sort-by-failures=&show-stale-tests=&include-filter-by-regex=should%20be%20able%20to%20delete%20nodes) in [ci-kubernetes-e2e-gke-container_vm-1.3-container_vm-1.5-upgrade-cluster](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.3-container_vm-1.5-upgrade-cluster/). Sample failure: [link](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.3-container_vm-1.5-upgrade-cluster/3
)

Based on [spreadsheet](https://docs.google.com/spreadsheets/d/1sAZqyWE--0fvN1PIuKTw9JwmcXNz6tQIm1MrjdILtm4/edit#gid=606512630&vpid=A1) tracking 1.5 upgrade test failures created by @krousey.

**Comment by dchen1107** [comment]
@dashpole Can you help triaging this one?

**Comment by dashpole** [comment]
Working on it now.

**Comment by dashpole** [comment]
Here are the steps taken during the test, with the error that triggered the test failure at the end.  I omitted 
```
STEP: creating replication controller my-hostname-delete-node
STEP: ensuring each pod is running
STEP: trying to dial each unique pod
STEP: decreasing cluster size to 2
STEP: verifying whether the pods from the removed node are recreated
STEP: ensuring each pod is running
STEP: trying to dial each unique pod
INFO: Controller my-hostname-delete-node: Got expected result from replica 1 [my-hostname-delete-node-kcgpn]: "my-hostname-delete-node-kcgpn", 1 of 3 required successes so far
INFO: Controller my-hostname-delete-node: Got expected result from replica 2 [my-hostname-delete-node-krx3h]: "my-hostname-delete-node-krx3h", 2 of 3 required successes so far
INFO: Controller my-hostname-delete-node: Failed to GET from replica 3 [my-hostname-delete-node-rk4fh]: an error on the server has prevented the request from succeeding (get pods my-hostname-delete-node-rk4fh)
```

Final Error:
`failed to wait for pods responding: pod with UID 7553b69a-b98b-11e6-ab97-42010af00042 is no longer a member of the replica set.  Must have been restarted for some reason.`

**Comment by dashpole** [comment]
The test has changed from this run to head: with the difference being (added by #35235, and updated by #36199):

```
By("waiting 1 minute for the watch in the podGC to catch up, remove any pods scheduled on " +
"the now non-existent node and the RC to recreate it")
time.Sleep(time.Minute)
```

**Comment by foxish** [comment]
This shouldn't be a release blocker. The behavior has changed in 1.5, and the Node Controller no longer deletes pods. It's the PodGC's responsibility to delete them. So, without the extra wait added to let the PodGC cleanup the pods, the test is expected to fail.

**Comment by foxish** [comment]
@saad-ali, backporting the test fix that was added in https://github.com/kubernetes/kubernetes/pull/36199 mentioned above, to 1.3 would fix it.

**Comment by dashpole** [comment]
We can close this because of #38324.

**Comment by dims** [comment]
@saad-ali @foxish Is it appropriate to move this to the next milestone? (and remove the non-release-blocker tag as well)

**Comment by krousey** [comment]
@dims I think it's appropriate to just close it once a similar change to #38324 is put into 1.3 as well.
