### ISSUE TITLE
[Upgrade test] "ScheduledJob should not emit unexpected warnings" in ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#38240]
Test has been [failing 100%](https://k8s-testgrid.appspot.com/google-1.4-1.5-upgrade#gce-cvm-1.4-cvm-1.5-upgrade-cluster&width=20&sort-by-failures=&include-filter-by-regex=ScheduledJob%20should%20not%20emit%20unexpected%20warnings) of the time in [ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster/). Sample failure: [link](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.4-1.5-upgrade-cluster/4)

Based on [spreadsheet](https://docs.google.com/spreadsheets/d/1sAZqyWE--0fvN1PIuKTw9JwmcXNz6tQIm1MrjdILtm4/edit#gid=1403603610&vpid=A1) tracking 1.5 upgrade test failures created by @krousey.

**Comment by soltysh** [comment]
Same justification as here: https://github.com/kubernetes/kubernetes/issues/38232#issuecomment-265396375. Not a release blocker.

**Comment by dims** [comment]
@saad-ali @soltysh Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by dims** [comment]
per @soltysh we should close all those upgrade tests for ScheduledJobs, since these are not problems which we'll fix

**Comment by dims** [comment]
https://github.com/kubernetes/kubernetes/issues/38232#issuecomment-266141737
