### ISSUE TITLE
Need to build etcd rollback tool linked against both 3.x and 2.x

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#38253]
#36555 was fixed by the combination of #37322 and @xiang90 creating a special build linked against both 2.x and 3.x wal packages.

I'm not sure how @xiang90 did the build, but we need to be able to build it automatically from source.

Assigning to @xiang90 for now, but I am willing to help with the build details.

**Comment by xiang90** [comment]
What is the current build process for the migration tool?

**Comment by wojtek-t** [comment]
This is now super trivial and is here:
https://github.com/kubernetes/kubernetes/blob/master/cluster/images/etcd/Makefile#L59

Though, since it is pretty custom, we can easily modify this one, I guess.

**Comment by wojtek-t** [comment]
If you could fix that build instructions that would be great.
Otherwise, I'm happy to help, but I need a better guidance with how to do it.

**Comment by xiang90** [comment]
@wojtek-t I will give it a try.

**Comment by wojtek-t** [comment]
@xiang90 thanks a lot!
Do you have any ETA for it?

**Comment by xiang90** [comment]
> Do you have any ETA for it?

Now. See https://github.com/kubernetes/kubernetes/pull/38394

**Comment by wojtek-t** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/38394
