### ISSUE TITLE
[Upgrade test] "Pods should not start app containers if init containers fail on a RestartAlways pod" failing in gke-container_vm-1.3-container_vm-1.5-upgrade-master

### ISSUE THREAD

**Issue by rkouj** [kubernetes/kubernetes#38251]
Test has been failing [100% of the time](http://k8s-testgrid.appspot.com/google-1.3-1.5-upgrade#gke-container_vm-1.3-container_vm-1.5-upgrade-master&include-filter-by-regex=Pods%20should%20not%20start%20app%20containers%20if%20init%20containers%20fail%20on%20a%20RestartAlways%20pod) in [ci-kubernetes-e2e-gke-container_vm-1.3-container_vm-1.5-upgrade-master](http://k8s-testgrid.appspot.com/google-1.3-1.5-upgrade#gke-container_vm-1.3-container_vm-1.5-upgrade-master). Sample failure: [link](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.3-container_vm-1.5-upgrade-master/15).

Based on [spreadsheet](https://docs.google.com/spreadsheets/d/1sAZqyWE--0fvN1PIuKTw9JwmcXNz6tQIm1MrjdILtm4/edit#gid=1325239137&vpid=A1) tracking 1.5 upgrade test failures created by @krousey.

**Comment by rkouj** [comment]
This also fails on

gke-container_vm-1.3-gci-1.5-upgrade-master
gke-gci-1.3-container_vm-1.5-upgrade-master
gke-gci-1.3-gci-1.5-upgrade-master

**Comment by saad-ali** [comment]
Per spreadsheet, Lantao is taking ownership of this issue. Please triage this issue as blocker or non-blocker for the 1.5 release ASAP.

**Comment by Random-Liu** [comment]
Same reason is https://github.com/kubernetes/kubernetes/issues/38248#issuecomment-265576180.

**Comment by dims** [comment]
@rkouj @Random-Liu Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by Random-Liu** [comment]
@dims I think so. We won't fix this for this release.

**Comment by xiangpengzhao** [comment]
/close
This issue is no longer valid.
