### ISSUE TITLE
typo in etcd federation service storage location

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#38262]
federation apiserver computes the etcd prefix for storing services using the singular "service" resource:

https://github.com/kubernetes/kubernetes/blob/master/federation/cmd/federation-apiserver/app/core.go#L45
```
serviceStore, serviceStatusStore := serviceetcd.NewREST(restOptionsFactory.NewFor(api.Resource("service")))
```

this means that service objects end up in etcd in a different location (`/service`) in federation api servers than in regular api servers (`/services/specs`)

as part of streamlining the way restoptions are applied to a store, we are using the qualified resource already specified in the store to look up the configured storage prefix (https://github.com/kubernetes/kubernetes/pull/37770/files#diff-09e000f5cfed7187b7d85fdc65c50410L44)

federation will either need to switch to using the standard etcd prefix for services (which would be ideal, but would impact upgrades) or define its own override for the services resource to map to '/service'

need an answer asap if fixing the etcd prefix for federation services is possible in 1.5 (I'm not sure whether federation services are alpha or beta in 1.4)

@kubernetes/sig-cluster-federation

**Comment by liggitt** [comment]
cc @nikhiljindal @saad-ali

**Comment by nikhiljindal** [comment]
Thanks a lot @liggitt for noticing and bringing this up. I am surprised that we ended up with a different prefix in federation. Did we change the prefix in kubernetes? (I assume no since that would have broken kubernetes upgrade).

Services was beta in 1.4 and remains beta in 1.5, so I we dont need to rush up the fix in 1.5. We should fix it but should be fine to fix in 1.6.

cc @kubernetes/sig-cluster-federation

**Comment by liggitt** [comment]
> Did we change the prefix in kubernetes? (I assume no since that would have broken kubernetes upgrade).

no, it's been that since 1.0:
https://github.com/kubernetes/kubernetes/blob/cd821444dcf3e1e237b5f3579721440624c9c4fa/pkg/registry/etcd/etcd.go#L35

**Comment by nikhiljindal** [comment]
hmm I see we chose the `/service` prefix in federation in https://github.com/kubernetes/kubernetes/pull/25232. I didnt realize that in the review. Assume the prefix change was not intentional.
cc @jianhuiz

**Comment by nikhiljindal** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/37770
