### ISSUE TITLE
Just 1 entrypoint with more than 2 version

### ISSUE THREAD

**Issue by mcortinas** [kubernetes/kubernetes#38267]
Hello,

 I tried to ask the same in slack channels without answer.
 I'm not sure if this is a feature request or not, apologies for advance... 

 I looking for a solution for API with more than 2 versions enabled with weight in loadbalancer.
 I can NOT split by URI, we want all version in the same URI, the root. 

 Trying to be clear, let me explain better decribing this sceneario:
ENTRYPOINT API : serviceX.domainX.com
                     podA: versionA with 25%
                     podB: versionB with 40%
                     podC: versionC with 30%
                     podD: versionD with 5%
 
After read the documentation, i'm not sure if the loadbalancer ( http://kubernetes.io/docs/user-guide/services/#type-loadbalancer ) can do it or if i should use some special configuration of ingress controller... ( https://github.com/kubernetes/contrib/tree/master/ingress/controllers )

 After read some documentation my first approach a solution adding some custom HTTP header specifying the version to do a sticky balance to each POD and adding the weights, but I'm not sure if I can do it with INGRESS controller customizing the haprozy template ( https://github.com/kubernetes/contrib/blob/master/service-loadbalancer/template.cfg )

What do you think?

**Comment by hjacobs** [comment]
A very quick answer on how we plan to do it (naive approach): create one Kubernetes Deployment per version and scale by number of pods, i.e. if you want 25% for versionA and 75% for versionB you have for example:

* Deployment myapp-a with replicas=2
* Deployment myapp-b with replicas=6
* Service "myapp" which selects all pods from both deployments (so using label selector "app=myapp" without selecting on version)

This is very rough, but would work "on average".

Alternatively you might look into weighted DNS records (e.g. in Route53).

**Comment by mcortinas** [comment]
Cool! It could be a quite good approach by now! 
But, I think the properly way should be managed with weights.

**Comment by hjacobs** [comment]
@mcortinas yes, support for weights would be cool --- this could already work with the current `kube-proxy` iptables rules as they are using computed weights (equal distribution).

**Comment by kargakis** [comment]
At the controller level, autopausing is also a solution: https://github.com/kubernetes/kubernetes/issues/11505

You can use auto-pausing in 1.7 with StatefulSets. Look out for the partition field in the rolling parameters.

**Comment by hjacobs** [comment]
We introduced weighted traffic switching in our Skipper Ingress HTTP router: https://github.com/zalando/skipper/issues/324
We annotate different backend weights in the Ingress YAML. This solves the problem for us.
