### ISSUE TITLE
Consider special annotation for deprecated fields and models

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes#38269]
following up on thokin's commend on #36760 we should add a deprecated annotation with enough information for user to find the replacement.

> @mbohlool we should probably consider another annotation on fields and structs to indicate that they are deprecated, but we need to spec not just that it is deprecated, but also where to find more information, and maybe when or what what API version it will stop working in.

cc @thokin @kubernetes/sig-api-machinery

**Comment by jamiehannaford** [comment]
Just for clarity, by annotation you mean something like [this](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L492) or do you mean the ones like `json` enscapsulated in the ` `` ` marks?

**Comment by mbohlool** [comment]
The comment annotation.

**Comment by jamiehannaford** [comment]
@mbohlool Okay, should this new convention be documented somewhere? Or is it fine to just add to the code comment blocks? Fine with either one just wanted to know before I submit a PR.

**Comment by mbohlool** [comment]
Are you going to submit a PR to fix this issue? If so, yes, it is better to be documented somewhere. I am not sure where, but it should not be hard to figure it out if you look at main repo's documentation folder.
