### ISSUE TITLE
QPS limits in clients seem to not work in all situations

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#38273]
In kubemark-500, we are bumping QPS limits for clients in controller-amanger to 100.
https://github.com/kubernetes/test-infra/blob/master/jobs/ci-kubernetes-kubemark-500-gce.sh#L42

However, it seems the ReplicationController is creating pods significantly faster than 100 per second.
From the logs from:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/642?log#log
```
I1207 00:19:24.543] I1207 00:19:24.543499    9233 runners.go:120] Created replication controller with name: density15000-0-dcd07081-bc55-11e6-9e64-0242ac110005, namespace: e2e-tests-density-100-1-c20xv, replica count: 0xc42e2ca34c
I1207 00:19:24.549] I1207 00:19:24.549245    9233 runners.go:120] Created replication controller with name: density15000-3-dcd07081-bc55-11e6-9e64-0242ac110005, namespace: e2e-tests-density-100-4-brbqf, replica count: 0xc42c885ca4
I1207 00:19:24.549] I1207 00:19:24.549350    9233 runners.go:120] Created replication controller with name: density15000-4-dcd07081-bc55-11e6-9e64-0242ac110005, namespace: e2e-tests-density-100-5-ph9b9, replica count: 0xc42d7b42ac
I1207 00:19:24.549] I1207 00:19:24.549584    9233 runners.go:120] Created replication controller with name: density15000-2-dcd07081-bc55-11e6-9e64-0242ac110005, namespace: e2e-tests-density-100-3-tvqj3, replica count: 0xc42e86dc7c
I1207 00:19:24.571] I1207 00:19:24.570795    9233 runners.go:120] Created replication controller with name: density15000-1-dcd07081-bc55-11e6-9e64-0242ac110005, namespace: e2e-tests-density-100-2-qm9px, replica count: 0xc42dc7fe7c
I1207 00:19:34.527] Dec  7 00:19:34.526: INFO: Density Pods: 1178 out of 15000 created, 883 running, 141 pending, 154 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I1207 00:19:44.529] Dec  7 00:19:44.528: INFO: Density Pods: 2182 out of 15000 created, 1880 running, 137 pending, 165 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I1207 00:19:54.530] Dec  7 00:19:54.530: INFO: Density Pods: 3489 out of 15000 created, 2876 running, 136 pending, 477 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I1207 00:20:04.532] Dec  7 00:20:04.532: INFO: Density Pods: 5857 out of 15000 created, 3878 running, 131 pending, 1848 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I1207 00:20:14.534] Dec  7 00:20:14.534: INFO: Density Pods: 8718 out of 15000 created, 4872 running, 135 pending, 3711 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I1207 00:20:24.537] Dec  7 00:20:24.536: INFO: Density Pods: 11044 out of 15000 created, 5876 running, 131 pending, 5037 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I1207 00:20:34.538] Dec  7 00:20:34.538: INFO: Density Pods: 12943 out of 15000 created, 6865 running, 141 pending, 5937 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I1207 00:20:44.543] Dec  7 00:20:44.542: INFO: Density Pods: 14328 out of 15000 created, 7878 running, 126 pending, 6324 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I1207 00:20:54.541] Dec  7 00:20:54.540: INFO: Density Pods: 14998 out of 15000 created, 8883 running, 121 pending, 5994 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotR
```

This pretty much means that we created 15000 pods within 90s which gives more than 100 pods/s on average.

Seems like a bug.

@kubernetes/sig-api-machinery

**Comment by wojtek-t** [comment]
On the other hand, QPS limits seems to work fine in scheduler (where they are also bumped to 100), so it might be replication-controller (controller-manager?) specific.

**Comment by wojtek-t** [comment]
BTW - the same is happening in pretty much all runs of kubemark-500 and kubemark-scale (those are runs where we are bumping default QPS limits).

**Comment by wojtek-t** [comment]
I double checked that the flags are correctly passed. There is __exactly one__ controller-manager and it's command line is like this:
```
root      3209 50.8  0.6 421728 387556 ?       Sl   13:51   3:24 /kubernetes/server/bin/kube-controller-manager --master=127.0.0.1:8080 --service-account-private-key-file=/srv/kubernetes/server.key --root-ca-file=/srv/kubernetes/ca.crt --v=2 --min-resync-period=3m --kube-api-qps=100 --kube-api-burst=100 --enable-garbage-collector=true --allocate-node-cidrs=true --cluster-cidr=10.240.0.0/11 --service-cluster-ip-range=10.0.0.0/16 --terminated-pod-gc-threshold=100
```

**Comment by wojtek-t** [comment]
@saad-ali @smarterclayton @timothysc @thockin @davidopp 

This is a regression that was introduced in https://github.com/kubernetes/kubernetes/pull/35583 and broke rate-limitter.
Rate limitter is used among others to:
- rate-limiting evictions in node-controller
- throttling requests send from single client to apiserver
That means, that in my opinion this should be a release blocker. I'm adding a label, to consider it during burndown meeting.


Background (what is happening in the background):
- we are trying to accept a request:
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/flowcontrol/throttle.go#L72
- that call Wait in bucket rate-limitter:
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/ratelimit/bucket.go#L107
- Wait takes whatever is available now, and sleeps for the remaining time
- however, during the "sleeping time", the rate-limitter is self-refilling
- so in the end, multiple "takers" can consume the same amount of time

**Comment by liggitt** [comment]
agree it's a blocker. is there a reason not to return to the tested ratelimiter that was in place prior to that PR?

**Comment by wojtek-t** [comment]
I'm fine with that, though automatic revert is no longer possible.

**Comment by wojtek-t** [comment]
@lavalamp

**Comment by liggitt** [comment]
opened master PR for discussion at #38294
will pick if agreed on

**Comment by smarterclayton** [comment]
Let's revert to known working.

**Comment by timothysc** [comment]
+1 for blocker.  I'm more concerned how this passed testing.

**Comment by thockin** [comment]
ACK

**Comment by liggitt** [comment]
>  I'm more concerned how this passed testing.

Added a unit test for multi-threaded use of the throttler that catches this issue in https://github.com/kubernetes/kubernetes/pull/38306/

**Comment by saad-ali** [comment]
Revert PRs have been merged to master (PR #35583) and 1.5 (PR #38294).

@wojtek-t @liggitt Please verify and close this issue ASAP

**Comment by justinsb** [comment]
Fix in #38360

**Comment by davidopp** [comment]
Thanks a lot for noticing this, @wojtek-t

**Comment by wojtek-t** [comment]
@saad-ali - verified, seems to work fine now.

**Comment by saad-ali** [comment]
> @saad-ali - verified, seems to work fine now.

Ack, thank you!
