### ISSUE TITLE
Exposing kubernetes secrets to java application HELP

### ISSUE THREAD

**Issue by clarelewis73** [kubernetes/kubernetes#38279]
I was wondering...

If I created a Java microservice and wanted to use K8s secrets to store passwords. From the operations side of DevOps, how would I change this password without changing the base code? I.e. how would I expose this from k8s to my Java application? Is there a program in fabric8? or is there anything else?

Any help would be great thanks!

**Comment by hjacobs** [comment]
You simply would create a secret with your password and use the secret in your Deployment `env` section: http://kubernetes.io/docs/user-guide/secrets/#using-secrets-as-environment-variables

I would generally advise looking at "The Twelve-Factor App" (using env vars for your app configuration) : https://12factor.net/

BTW: Spring Boot (we use it for Java microservices in Zalando) automatically supports setting any configuration property via environment variables. So there is a high chance that you don't have to do much :smile:

**Comment by hjacobs** [comment]
I would recommend joining one of the many Slack channels (http://slack.k8s.io/) and/or the mailing list for such support questions.
