### ISSUE TITLE
User reported issue:  `invalid argument "" for --etcd_quorum_read=: strconv.ParseBool: parsing "": invalid syntax`

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#38290]
Slack user "nalin" reported an issue `invalid argument "" for --etcd_quorum_read=: strconv.ParseBool: parsing "": invalid syntax`

Looking at the code this makes sense.  Will fix.

**Comment by zmerlynn** [comment]
For anyone following along, the fix for this bug unfortunately didn't get cherrypicked because of a process issue, and `kube-up.sh` is broken until 1.5.2.

cc @kubernetes/sig-aws

**Comment by sazo** [comment]
I just added the new lines from https://github.com/zmerlynn/kubernetes/commit/30e1a04977a6bad23d94cc1db99d6c8972d0ea6a

As a temperatur fix ONLY. If anyone like me dont want to wait. Worked like at charm for AWS cluster setup. :)

**Comment by oskarpearson** [comment]
A quick note, just as confirmation: the above temporary fix does resolve the issue for AWS - even though it's a change to a GCE-related file (cluster/gce/configure-vm.sh). It seems that the GCE files are used for certain aws functions.

**Comment by zmerlynn** [comment]
In `kube-up.sh` based AWS deployment, the `cluster/gce/configure-vm.sh` script is shared between AWS and GCE.

**Comment by zmerlynn** [comment]
Also, this fix was cherry-picked into the `release-1.5` branch a while ago, so instead of manually adding the lines, you can also just checkout the `release-1.5` branch and run from there.
