### ISSUE TITLE
Add timeouts back to e2e tests

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#38305]
In https://github.com/kubernetes/kubernetes/issues/37981, it appears that at least 2 test timeouts are caused by proxy requests to pods hanging indefinitely (at least hours). The client in the e2e tests should timeout these requests within a reasonable limit.

**Comment by krousey** [comment]
@wojtek-t I marked this as a p1 non-release-blocker issue for 1.5. I would like this fixed for 1.5 because it's causing the entire job to timeout and not report results for individual tests. This would be a test stability fix to improve the signal we get. Do you have any objections to adding timeouts back?

**Comment by wojtek-t** [comment]
Copying what I wrote in the PR where @krousey mentioned that issue:

@krousey - I think this may not only be the issue of upgrade tests. For example this might be the same issue: https://github.com/kubernetes/kubernetes/issues/38066 (though I didn't yet have time to investigate it, but from what @ixdy wrote there it is possible).
I don't feel like an expert in this area, but unless I'm not missing anything, I think we are NOT setting these timeouts in production code. If that's really the case, we also shouldn't set the in tests, as I really think that those setups should be as similar as possible. That said I think there are pretty much two options:
- somehow fail those tests if we detect that the call is hanging forever
- if we decide the that the only reasonable way to fix it now is to add timeout back, we should also set it (or ensure it is set) in the production code, to avoid such situations also in production.
@krousey @lavalamp - WDYT?

**Comment by krousey** [comment]
@wojtek-t I don't think we should set it in production code. I think we should set the timeout in test, and hard fail the calls that timeout, but allow the suite to finish. That way the timeouts get reported as failures, can aide in debugging the underlying problem, and not waste an entire 7 hour test run. Thoughts?

**Comment by wojtek-t** [comment]
I would like to avoid differences between test & production code. I completely agree that we should allow for debugging underlying problems, though if we set this timeout in production, what is our store to say for clients for hanging forever request if that happens?
[To be clear, if you really don't agree with me, I don't want to block adding back the timeout. Feel free to add it back to speed up debugging and we can continue this discussion after that]

**Comment by krousey** [comment]
@wojtek-t I understand what you mean, but I think our tests should make a best effort to report results. I would like to see a timeout added in such a way that:

1. Doesn't hang the entire test job for 10 hours.
2. Doesn't ignore the time out. Ideally it would fail the test that caused the time out, and we could use the failure to investigate the issue.
3. Doesn't interfere with normal long-lived connections.

I think something like a 30-minute timeout only on proxy calls would suffice, not be that different from production, and give us a lot more indication that proxy calls are actually hanging and bad.

**Comment by wojtek-t** [comment]
I agree with your goals here. Though since it seems that this is also a problem in other suites, I vote for decreasing 30 minutes to something smaller.
Is it possible to set timeout only on proxy calls? Do you want to hae a dedicated logic for it in apiserver?

**Comment by dims** [comment]
@krousey Is it appropriate to move this to the next milestone or clear the 1.5 milestone? (and remove the non-release-blocker tag as well)

**Comment by krousey** [comment]
No. This still needs to be fixed.

**Comment by wojtek-t** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/38592
