### ISSUE TITLE
[Upgrade test] "[k8s.io] Kubelet [Serial] [Slow] [k8s.io] regular resource usage tracking resource tracking for 100 pods per node" in gke-[container_vm/gci]-1.3-[container_vm/gci]-1.5-upgrade-master

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#38325]
Test has been failing 100% of the time in [gke-gci-1.3-container_vm-1.5-upgrade-master](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1.3-container_vm-1.5-upgrade-master/). Sample failure: [link](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1.3-container_vm-1.5-upgrade-master/17/#k8sio-kubelet-serial-slow-k8sio-regular-resource-usage-tracking-resource-tracking-for-100-pods-per-node)

Based on spreadsheet tracking 1.5 upgrade test failures created by @krousey.

cc: @Random-Liu, can you add the appropriate labels and assign me?  Can you also add me to the spreadsheet for this test?

**Comment by saad-ali** [comment]
Marking as release blocker for 1.5 until we have verification from @dashpole that this is not a release-blocker.

**Comment by dashpole** [comment]
cc:  @yujuhong

**Comment by yujuhong** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1.3-container_vm-1.5-upgrade-master/17/#k8sio-kubelet-serial-slow-k8sio-regular-resource-usage-tracking-resource-tracking-for-100-pods-per-node

The docker memory usage was high (~500MB0 before running the test:
```
I1207 01:00:16.999] Dec  7 01:00:16.999: INFO: Resource usage on node "gke-bootstrap-e2e-default-pool-f5475caa-qpkj":
I1207 01:00:16.999] container cpu(cores) memory_working_set(MB) memory_rss(MB)
I1207 01:00:16.999] "runtime" 0.026      1318.03                500.01
I1207 01:00:16.999] "kubelet" 0.205      63.96                  55.64
I1207 01:00:17.000] "/"       0.182      2052.70                1.49
I1207 01:00:17.000] 
I1207 01:00:17.000] Resource usage on node "gke-bootstrap-e2e-default-pool-f5475caa-vn5f":
I1207 01:00:17.000] container cpu(cores) memory_working_set(MB) memory_rss(MB)
I1207 01:00:17.000] "kubelet" 0.102      57.17                  51.01
I1207 01:00:17.000] "/"       0.212      2433.35                1.41
I1207 01:00:17.000] "runtime" 0.026      1712.80                514.48
I1207 01:00:17.000] 
I1207 01:00:17.000] Resource usage on node "gke-bootstrap-e2e-default-pool-f5475caa-womv":
I1207 01:00:17.000] container cpu(cores) memory_working_set(MB) memory_rss(MB)
I1207 01:00:17.001] "/"       0.234      2486.27                1.52
I1207 01:00:17.001] "runtime" 0.024      1702.25                515.73
```
I checked the log and docker was up ~3.5 hours before running the test (2016-12-07T05:20 to 2016-12-07T08:57), and it had created ~350 containers at that point. Even though docker leaking memory is a known issue, this rate of leaking seems unprecedented. 

@dashpole could you check other failures and see if they have the same numbers?

**Comment by dashpole** [comment]
`Dec  6 15:34:29.475: INFO: Resource usage on node "gke-bootstrap-e2e-default-pool-f364655f-hrfi":
I1206 15:34:29.484] container cpu(cores) memory_working_set(MB) memory_rss(MB)
I1206 15:34:29.484] "/"       0.296      2067.30                1.61
I1206 15:34:29.484] "runtime" 0.020      1300.57                515.68
I1206 15:34:29.484] "kubelet" 0.208      56.91                  47.21
I1206 15:34:29.484] 
I1206 15:34:29.484] Resource usage on node "gke-bootstrap-e2e-default-pool-f364655f-pys1":
I1206 15:34:29.484] container cpu(cores) memory_working_set(MB) memory_rss(MB)
I1206 15:34:29.485] "kubelet" 0.206      54.55                  46.88
I1206 15:34:29.485] "/"       0.270      1910.61                1.62
I1206 15:34:29.485] "runtime" 0.019      1183.40                508.55
I1206 15:34:29.485] 
I1206 15:34:29.485] Resource usage on node "gke-bootstrap-e2e-default-pool-f364655f-en3g":
I1206 15:34:29.485] container cpu(cores) memory_working_set(MB) memory_rss(MB)
I1206 15:34:29.485] "/"       0.358      1864.52                1.74
I1206 15:34:29.485] "runtime" 0.020      1192.26                493.67
I1206 15:34:29.485] "kubelet" 0.210      49.33                  43.64
I1206 15:34:29.485] 
I1206 15:34:29.486] [1mSTEP[0m: Start monitoring resource usage`

**Comment by dashpole** [comment]
```
I1206 10:31:36.063] Dec  6 10:31:36.062: INFO: Resource usage on node "gke-bootstrap-e2e-default-pool-d6528cab-eldz":
I1206 10:31:36.063] container cpu(cores) memory_working_set(MB) memory_rss(MB)
I1206 10:31:36.063] "/"       0.652      2051.36                1.62
I1206 10:31:36.063] "runtime" 0.030      1336.52                493.52
I1206 10:31:36.063] "kubelet" 0.212      52.74                  46.09
I1206 10:31:36.063] 
I1206 10:31:36.063] Resource usage on node "gke-bootstrap-e2e-default-pool-d6528cab-w7um":
I1206 10:31:36.063] container cpu(cores) memory_working_set(MB) memory_rss(MB)
I1206 10:31:36.064] "/"       0.264      2197.83                1.54
I1206 10:31:36.064] "runtime" 0.019      1453.56                503.11
I1206 10:31:36.064] "kubelet" 0.177      52.03                  45.66
I1206 10:31:36.064] 
I1206 10:31:36.064] Resource usage on node "gke-bootstrap-e2e-default-pool-d6528cab-ypzs":
I1206 10:31:36.064] container cpu(cores) memory_working_set(MB) memory_rss(MB)
I1206 10:31:36.064] "/"       0.306      1863.33                1.60
I1206 10:31:36.064] "runtime" 0.029      1153.00                503.59
I1206 10:31:36.064] "kubelet" 0.272      49.41                  42.68
I1206 10:31:36.065] 
I1206 10:31:36.065] [1mSTEP[0m: Start monitoring resource usage
```

**Comment by dashpole** [comment]
Yeah, looks like the numbers are similar for other runs.

**Comment by dashpole** [comment]
This test always fails on gci version 1.3.  Check out that testgrid [here](https://k8s-testgrid.appspot.com/google-gce#gci-gce-serial-release-1.3).
In the 1.3 serial tests, memory rss is consistently ~500MB, whereas after 1.4, it decreases to ~275MB, which passes our resource usage tests consistently.  
This is worth investigating, but is not related to upgrading from one version to another, and is not a release blocker for 1.5.

**Comment by yujuhong** [comment]
> This test always fails on gci version 1.3. Check out that testgrid here.

I thought the test was run *after* the upgrade.... so it was the pre-upgrade test?

**Comment by krousey** [comment]
@yujuhong For this particular test here's the versions:

Master: 1.5
Nodes: 1.3
E2E: 1.3

**Comment by yujuhong** [comment]
> @yujuhong For this particular test here's the versions:

Thanks! I think that's something we should always highlight when talking about an upgrade test failure :)

I don't see there is anything that needs to be done for this failure. Let's just close it.

**Comment by Random-Liu** [comment]
Close this one according to https://github.com/kubernetes/kubernetes/issues/38325#issuecomment-265613354.
