### ISSUE TITLE
kubectl get -o yaml probably/maybe shouldn't filter pods

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#38327]
I don't think that `kubectl get -o yaml` should filter pods.  I could maybe be convinced, but as a user it doesn't seem to help me when I'm dealing with output.  Certainly printing the message seems wrong.

```
$ kubectl get -o yaml
...
kind: List
metadata: {}
  info: 1 completed object(s) was(were) not shown in pods list. Pass --show-all to see all objects.
```

It seems unlikely to me that users want to see the info: message when they run `-o yaml` on get.  The output must be on stderr (so it doesn't break piping) which I did not check but we should verify.

It's worth considering the `--show-all` filter we have to default to "off" when a user provides "-o yaml".

**Comment by smarterclayton** [comment]
@kubernetes/sig-cli

**Comment by AdoHe** [comment]
@smarterclayton why just be special with `yaml` output? what if `-o json`?

**Comment by smarterclayton** [comment]
The "raw" outputs are subtly different than the tabular outputs, in that they are for different tools.

I still regret the decision to hide completed pods - it's a minor win in some cases but adds one more choice in many cases for users that they don't care about (a completed pod may be more important than all your running pods).  

As long as we're out putting those messages to stderr and not indenting them (indentation makes no sense when in a piped command), I'm ok with not altering filtering since it would be confusing.
