### ISSUE TITLE
GCE Node Upgrade should respect PodDisruptionBudget

### ISSUE THREAD

**Issue by enisoc** [kubernetes/kubernetes#38336]
As part of [pod safety](https://github.com/kubernetes/kubernetes/pull/34160) for [StatefulSets](https://github.com/kubernetes/features/issues/137), we ensured that [kubectl drain uses the eviction subresource](https://github.com/kubernetes/kubernetes/issues/34277) so it respects [PodDisruptionBudget](https://github.com/kubernetes/features/issues/85).

Unfortunately, there is no script or recommended node upgrade process (AFAIK) that actually uses `kubectl drain`. In particular, the experimental [cluster/gce/upgrade.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/upgrade.sh) script uses GCE [rolling updates](https://github.com/kubernetes/kubernetes/issues/33764) which simply terminate and recreate node VMs.

This issue is to track the need to provide a script or recommended process for upgrading nodes that actually respects PodDisruptionBudgets, so that the guarantees made by things like StatefulSet actually work during upgrades.

cc @kubernetes/sig-apps

**Comment by davidopp** [comment]
There is some discussion of this in #32323. It's not trivial. See my comment https://github.com/kubernetes/kubernetes/issues/32323#issuecomment-264604766

Actually, I think I'll copy it here, since most of that thread is unrelated.

If this is high-priority I'm happy to discuss these options in more detail.

[copied comment below]

We've talked about two possible solutions to this:

(1) Create "node drain as a service" a.k.a. "move kubectl drain into the server" -- an API object where you specify which nodes you want to drain, with an associated controller that figures out a good "schedule" for draining them subject to PDB and any other constraints, and which does the drain (evictions) and then when a node is drained calls out to some endpoint to do the maintenance action, in this case presumably calling out to some GCP endpoint that will then execute the node upgrade. Today's upgrade.sh logic would be split between this controller and the GCP logic that executes the node upgrade.

(2) Modify the MIG rolling updater so that it is GKE-aware, e.g. drains the nodes before upgrading and takes PodDisruptionBudget into account. Today's upgrade.sh could continue to operate more or less as-is, at least in the sense of relying on GCP to take care of scheduling and executing the upgrades.

Similar issues of choosing the node, draining, and respecting PDB come up elsewhere too (e.g. preemptible VMs, cluster auto-scaler scale down, and rescheduler).

But anyway, you're right, it's not just a simple matter of calling `kubectl drain` from `upgrade.sh`

**Comment by enisoc** [comment]
@davidopp Thanks for surfacing that post. I'm not familiar with the available GCE APIs, but would an intermediate approach be possible where we first "unroll" upgrade.sh to do everything in terms of individual VMs (rather than using rolling updates), and then we add `kubectl drain/uncordon`? Going in arbitrary order (no smart schedule) would at least preserve safety, at the expense of extra pod churn and perhaps a risk of stalling the rolling upgrade. Did you exclude that option because it isn't possible as long as we're running the nodes via MIG?

For the record, I should add some more context for why this is a priority for us in sig-apps. Together with #37984, this means upgrading nodes from 1.5.0 to a future release can (1) take a clustered StatefulSet app below the required quorum to function, and (2) leave it in that stuck state for ~10min (or potentially up to the time it takes to complete a rolling update of all nodes) due solely to voluntary actions (planned maintenance).

In effect, StatefulSets still don't have a viable upgrade path going forward, despite being beta now. I discussed this with @erictune and we're going to look across the set of interacting issues that got us here to see what can be addressed perhaps in a patch release. If there's no easy mitigation for the issue in question on this page (like a script refactoring or a documented safe manual flow for GCE), we'll need to focus elsewhere for now.

**Comment by davidopp** [comment]
I just chatted with @maisem and he says he is working on exactly what you described and should have it done within the next few weeks. I'll let him describe it here, but from chatting with him it does sound like the third option you described.

**Comment by davidopp** [comment]
(BTW I still think we should do "node drain as a service" (option 1 above) eventually, because that would be portable across cloud providers and could even be used by GKE, vs. `upgrade.sh` which only works on GCE.)

**Comment by roberthbailey** [comment]
/cc @maisem 

> would an intermediate approach be possible where we first "unroll" upgrade.sh to do everything in terms of individual VMs (rather than using rolling updates), and then we add kubectl drain/uncordon?

This is definitely an improvement over the current shell script. 

> Did you exclude that option because it isn't possible as long as we're running the nodes via MIG?

This is definitely possible when using a MIG.

**Comment by davidopp** [comment]
> This is definitely possible when using a MIG.

Yeah I didn't realize it was possible, but I agree this is definitely the most expedient thing to do short-term.

**Comment by maisem** [comment]
I started working on a safe way to do upgrades a couple of weeks ago but then got sidetracked.
This should allow for a non-disruptive way of upgrading the nodes in a cluster.
```
1. Create a new Instance Template (we do this already)
2. Change the Managed Instance Group to use the new template.
    gcloud compute instance-groups managed set-instance-template
3. For each node in the Instance Group
    a. Verify the node needs to be updated by checking the current instance template
        This can be done by checking for the "instance-template" key in the instance metadata.
    b. Drain the node
        kubectl drain
    c. Recreate the node
        gcloud compute instance-groups managed recreate-instances
    d. Wait for node to become healthy again 
```

**Comment by bgrant0607** [comment]
cc @mml

**Comment by santinoncs** [comment]
Hi, anyone knows if GKE upgrade is doing a “kubectl drain” ? 

According to its documentation, GKE upgrade uses "kubectl drain" before upgrading an specific node. 

But I got a 3 node GKE cluster and  a cluster of consul ( 3 pods ) and the consensus was lost, looking for the logs it seems that it halt 2 pods at the same time not respecting the minAvailable parameter of the PodDisruptionBudget resource.

When I perform a drain, it works.

**Comment by justinsb** [comment]
FYI kops has drain support behind a feature flag, and we do GCE behind a feature flag.  I'm not sure whether we do drain on GCE though.  We use the drain, delete instance, wait for readiness approach.

**Comment by santinoncs** [comment]
The drain execution honors the PodDisruptionBudget. I test it. But the upgrade does not seem to. 

Scenario:

- GKE 3-node ( A,B,C ) cluster version 1.5.6
- statefulSet of consul ( of 3 pods, consul.0/consul.1/consul.2 ) 
https://github.com/kelseyhightower/consul-on-kubernetes
- node A with 
   - pod consul.0 and consul.2
- node B with 
   - pod consul.1
- node C with 
   - none

Steps to nodes upgrade to version 1.6.1


1. perform upgrade via upgrade button of gke. :white_check_mark:
2. node B down, downgrading :white_check_mark:
3. pod consul.1 is moved to node C  :white_check_mark:
4. node B up  :white_check_mark:
5. node A down, downgrading  :white_check_mark:
6. pods consul.0 and .2 moved to node B at the same time. => cluster consul consensus down. :boom:

**Comment by roberthbailey** [comment]
@santinoncs 

Yes, @maisem added a drain step as part of upgrading GKE nodes but it doesn't exec `kubectl drain` as a subcommand. Since drain is still client side, the implementation may be slightly different than what you get using the kubectl tool. In particular, I believe we don't yet honor the PodDisruptionBudget (as you noticed).

**Comment by maisem** [comment]
As @roberthbailey pointed out we don't honor PodDisruptionBudget yet. However, we do have a high priority work item to fix this soon.

**Comment by mml** [comment]
I will take a whack at this.  I would like test coverage too, in the form of one of those fancy e2e upgrade tests.

**Comment by mml** [comment]
I spoke with @krousey about how to add the tests.  Basically, we'll add this to the existing list of tests in `test/e2e/cluster_upgrade.go`.  Either modifying, say, the `ServiceUpgradeTest` to verify it works through a node upgrade, or adding a separate test, which we'll probably do as we want to test several apps with native APIs.

Kris asked the question whether or not this should live in `cluster/gce/upgrade.sh` (or perhaps a rewrite of it in go).  AFAIK, this (`kube-up` and the whole `cluster/` directory) is still the reference implementation for these sorts of things, and the only supported method for GCE clusters.  @maisem listed some logic above that doesn't strike me as that hard to implement in shell, anyway.

Kris' concern is that maybe `cluster/` is marked for destruction.  Is it?

**Comment by roberthbailey** [comment]
Matt -- we'd love to delete the `cluster/` directory, but we still don't have a replacement. So for now `cluster/gce/upgrade.sh` is the only place where I know that we have upgrade test coverage (other than the GKE upgrade test suites).

**Comment by mml** [comment]
OK, so I have a version of this "working", and it blows up when hitting influxdb because it has local storage.

The question is, do we want the upgrade script to automatically blow up local storage by default?  I can't see how to make it work without this, and at the same time it seems a dangerous default.

```
== Pre-Upgrade Node OS and Kubelet Versions ==
name: "e2e-master", osImage: "Container-Optimized OS from Google", kubeletVersion: "v1.7.0-alpha.3.278+a365e02e018731-dirty"
name: "e2e-minion-group-5f66", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.7.0-alpha.3.278+a365e02e018731-dirty"
name: "e2e-minion-group-ls90", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.7.0-alpha.3.278+a365e02e018731-dirty"
Project: mml-e2e
Zone: us-central1-f
INSTANCE_GROUPS=e2e-minion-group
NODE_NAMES=e2e-minion-group-5f66 e2e-minion-group-ls90
== Preparing node upgrade (to v1.7.0-alpha.3.272+69ad6addcc5c25). ==
== Ensuring that new Node base OS image matched the existing Node base OS image
Warning: Permanently added 'compute.3627340741220059498' (ECDSA) to the list of known hosts.
== Upgrading node environment variables. ==
Instance template e2e-minion-template-v1-7-0-alpha-3-272-69ad6addcc5c25 already exists; deleting.
Attempt 1 to create e2e-minion-template-v1-7-0-alpha-3-272-69ad6addcc5c25
WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#pdperformance.
Created [https://www.googleapis.com/compute/v1/projects/mml-e2e/global/instanceTemplates/e2e-minion-template-v1-7-0-alpha-3-272-69ad6addcc5c25].
NAME                                                   MACHINE_TYPE   PREEMPTIBLE  CREATION_TIMESTAMP
e2e-minion-template-v1-7-0-alpha-3-272-69ad6addcc5c25  n1-standard-2               2017-05-11T16:48:29.083-07:00
Instance template name: e2e-minion-template-v1-7-0-alpha-3-272-69ad6addcc5c25
== Finished preparing node upgrade (to v1.7.0-alpha.3.272+69ad6addcc5c25). ==
== Upgrading nodes to v1.7.0-alpha.3.272+69ad6addcc5c25. ==
== Draining e2e-minion-group-5f66. == 
node "e2e-minion-group-5f66" cordoned
WARNING: Deleting pods not managed by ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet: e2e-image-puller-e2e-minion-group-5f66, kube-proxy-e2e-minion-group-5f66; Ignoring DaemonSet-managed pods: fluentd-gcp-v2.0-1ztqr, npd-v0.3.0-stsrj
pod "kube-dns-2473071502-lz6r9" evicted
node "e2e-minion-group-5f66" drained
Updated [https://www.googleapis.com/compute/v1/projects/mml-e2e/zones/us-central1-f/instanceGroupManagers/e2e-minion-group].
PROJECT  ZONE           INSTANCE               STATUS
mml-e2e  us-central1-f  e2e-minion-group-5f66  SUCCESS
== Waiting for e2e-minion-group-5f66 to become ready. ==
Node e2e-minion-group-5f66 Ready=True
== Draining e2e-minion-group-ls90. == 
node "e2e-minion-group-ls90" cordoned
error: pods with local storage (use --delete-local-data to override): monitoring-influxdb-grafana-v4-ctg1f
```

**Comment by mml** [comment]
Well that's pretty neat for a shell script.

```
== Pre-Upgrade Node OS and Kubelet Versions ==
name: "e2e-master", osImage: "Container-Optimized OS from Google", kubeletVersion: "v1.7.0-alpha.3.278+a365e02e018731-dirty"
name: "e2e-minion-group-5f66", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.7.0-alpha.3.278+a365e02e018731-dirty"
name: "e2e-minion-group-ls90", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.7.0-alpha.3.278+a365e02e018731-dirty"
Project: mml-e2e
Zone: us-central1-f
INSTANCE_GROUPS=e2e-minion-group
NODE_NAMES=e2e-minion-group-5f66 e2e-minion-group-ls90
== Preparing node upgrade (to v1.7.0-alpha.3.272+69ad6addcc5c25). ==
== Ensuring that new Node base OS image matched the existing Node base OS image
== Upgrading node environment variables. ==
Instance template e2e-minion-template-v1-7-0-alpha-3-272-69ad6addcc5c25 already exists; deleting.
--network e2e --can-ip-forward
Attempt 1 to create e2e-minion-template-v1-7-0-alpha-3-272-69ad6addcc5c25
WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#pdperformance.
Created [https://www.googleapis.com/compute/v1/projects/mml-e2e/global/instanceTemplates/e2e-minion-template-v1-7-0-alpha-3-272-69ad6addcc5c25].
NAME                                                   MACHINE_TYPE   PREEMPTIBLE  CREATION_TIMESTAMP
e2e-minion-template-v1-7-0-alpha-3-272-69ad6addcc5c25  n1-standard-2               2017-05-12T12:03:25.300-07:00
Instance template name: e2e-minion-template-v1-7-0-alpha-3-272-69ad6addcc5c25
== Finished preparing node upgrade (to v1.7.0-alpha.3.272+69ad6addcc5c25). ==
== Upgrading nodes to v1.7.0-alpha.3.272+69ad6addcc5c25. ==
Updated [https://www.googleapis.com/compute/v1/projects/mml-e2e/zones/us-central1-f/instanceGroupManagers/e2e-minion-group].
---
baseInstanceName: e2e-minion-group
creationTimestamp: '2017-05-11T15:46:52.276-07:00'
currentActions:
  abandoning: 0
  creating: 0
  creatingWithoutRetries: 0
  deleting: 0
  none: 2
  recreating: 0
  refreshing: 0
  restarting: 0
fingerprint: NdOyzo5JUqw=
id: '3673119221375129395'
instanceGroup: https://www.googleapis.com/compute/v1/projects/mml-e2e/zones/us-central1-f/instanceGroups/e2e-minion-group
instanceTemplate: https://www.googleapis.com/compute/v1/projects/mml-e2e/global/instanceTemplates/e2e-minion-template-v1-7-0-alpha-3-272-69ad6addcc5c25
kind: compute#instanceGroupManager
name: e2e-minion-group
selfLink: https://www.googleapis.com/compute/v1/projects/mml-e2e/zones/us-central1-f/instanceGroupManagers/e2e-minion-group
targetSize: 2
zone: https://www.googleapis.com/compute/v1/projects/mml-e2e/zones/us-central1-f
== Draining e2e-minion-group-5f66. == 
node "e2e-minion-group-5f66" cordoned
WARNING: Ignoring DaemonSet-managed pods: fluentd-gcp-v2.0-1ztqr, npd-v0.3.0-stsrj; Deleting pods not managed by ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet: kube-proxy-e2e-minion-group-5f66; Deleting pods with local storage: monitoring-influxdb-grafana-v4-qwblm
pod "kube-dns-autoscaler-2042644734-dcrft" evicted
pod "kubernetes-dashboard-638781211-fzgwj" evicted
pod "heapster-v1.3.0-514138450-hsrj1" evicted
pod "monitoring-influxdb-grafana-v4-qwblm" evicted
pod "l7-default-backend-1599978672-lfwn4" evicted
pod "kube-dns-2473071502-bgvj1" evicted
pod "kube-dns-2473071502-6slgd" evicted
node "e2e-minion-group-5f66" drained
Updated [https://www.googleapis.com/compute/v1/projects/mml-e2e/zones/us-central1-f/instanceGroupManagers/e2e-minion-group].
PROJECT  ZONE           INSTANCE               STATUS
mml-e2e  us-central1-f  e2e-minion-group-5f66  SUCCESS
== Waiting for e2e-minion-group-5f66 to become young. ==
Node e2e-minion-group-5f66 not new: 1068 seconds.
Node e2e-minion-group-5f66 not new: 1078 seconds.
Node e2e-minion-group-5f66 not new: 1088 seconds.
Node e2e-minion-group-5f66 not new: 1099 seconds.
Node e2e-minion-group-5f66 not new: 1109 seconds.
Node e2e-minion-group-5f66 not new: 1119 seconds.
Node e2e-minion-group-5f66 not new: 1129 seconds.
Node e2e-minion-group-5f66 not new: 1140 seconds.
Node e2e-minion-group-5f66 not new: 1150 seconds.
Node e2e-minion-group-5f66 not new: 1160 seconds.
Node e2e-minion-group-5f66 not new: 1171 seconds.
Node e2e-minion-group-5f66 not new: 1181 seconds.
Node e2e-minion-group-5f66 not new: 1191 seconds.
Node e2e-minion-group-5f66 not new: 1202 seconds.
Node e2e-minion-group-5f66 not new: 1212 seconds.
Node e2e-minion-group-5f66 not new: 1222 seconds.
Node e2e-minion-group-5f66 recreated.
== Waiting for e2e-minion-group-5f66 to become ready. ==
Node e2e-minion-group-5f66 is still not ready: Ready=False
Node e2e-minion-group-5f66 Ready=True
== Draining e2e-minion-group-ls90. == 
node "e2e-minion-group-ls90" cordoned
WARNING: Ignoring DaemonSet-managed pods: fluentd-gcp-v2.0-0v7nb, npd-v0.3.0-bvxmt; Deleting pods not managed by ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet: kube-proxy-e2e-minion-group-ls90; Deleting pods with local storage: monitoring-influxdb-grafana-v4-p6lsq
pod "l7-default-backend-1599978672-2lb64" evicted
pod "kube-dns-autoscaler-2042644734-w9z9k" evicted
pod "heapster-v1.3.0-514138450-phx10" evicted
pod "kubernetes-dashboard-638781211-d6s22" evicted
pod "monitoring-influxdb-grafana-v4-p6lsq" evicted
pod "kube-dns-2473071502-rlw6j" evicted
pod "kube-dns-2473071502-95nh9" evicted
node "e2e-minion-group-ls90" drained
Updated [https://www.googleapis.com/compute/v1/projects/mml-e2e/zones/us-central1-f/instanceGroupManagers/e2e-minion-group].
PROJECT  ZONE           INSTANCE               STATUS
mml-e2e  us-central1-f  e2e-minion-group-ls90  SUCCESS
== Waiting for e2e-minion-group-ls90 to become young. ==
Node e2e-minion-group-ls90 not new: 999 seconds.
Node e2e-minion-group-ls90 not new: 1009 seconds.
Node e2e-minion-group-ls90 not new: 1019 seconds.
Node e2e-minion-group-ls90 not new: 1029 seconds.
Node e2e-minion-group-ls90 not new: 1040 seconds.
Node e2e-minion-group-ls90 not new: 1050 seconds.
Node e2e-minion-group-ls90 not new: 1060 seconds.
Node e2e-minion-group-ls90 not new: 1071 seconds.
Node e2e-minion-group-ls90 not new: 1081 seconds.
Node e2e-minion-group-ls90 not new: 1091 seconds.
Node e2e-minion-group-ls90 not new: 1102 seconds.
Node e2e-minion-group-ls90 not new: 1112 seconds.
Node e2e-minion-group-ls90 not new: 1122 seconds.
Node e2e-minion-group-ls90 not new: 1133 seconds.
Node e2e-minion-group-ls90 not new: 1143 seconds.
Node e2e-minion-group-ls90 not new: 1153 seconds.
Node e2e-minion-group-ls90 not new: 1163 seconds.
Node e2e-minion-group-ls90 not new: 1174 seconds.
Node e2e-minion-group-ls90 recreated.
== Waiting for e2e-minion-group-ls90 to become ready. ==
Node e2e-minion-group-ls90 is still not ready: Ready=False
Node e2e-minion-group-ls90 is still not ready: Ready=False
Node e2e-minion-group-ls90 Ready=True
== Deleting old templates in mml-e2e. ==
Deleted [https://www.googleapis.com/compute/v1/projects/mml-e2e/global/instanceTemplates/e2e-minion-template].
== Finished upgrading nodes to v1.7.0-alpha.3.272+69ad6addcc5c25. ==
== Validating cluster post-upgrade ==
MYCONFIG=foo
DONE
Validating gce cluster, MULTIZONE=
Project: mml-e2e
Zone: us-central1-f
Found 3 node(s).
NAME                    STATUS                     AGE       VERSION
e2e-master              Ready,SchedulingDisabled   20h       v1.7.0-alpha.3.278+a365e02e018731-dirty
e2e-minion-group-5f66   Ready                      4m        v1.7.0-alpha.3.272+69ad6addcc5c25
e2e-minion-group-ls90   Ready                      30s       v1.7.0-alpha.3.272+69ad6addcc5c25
Validate output:
NAME                 STATUS    MESSAGE              ERROR
scheduler            Healthy   ok                   
controller-manager   Healthy   ok                   
etcd-0               Healthy   {"health": "true"}   
etcd-1               Healthy   {"health": "true"}   
Cluster validation succeeded
== Post-Upgrade Node OS and Kubelet Versions ==
name: "e2e-master", osImage: "Container-Optimized OS from Google", kubeletVersion: "v1.7.0-alpha.3.278+a365e02e018731-dirty"
name: "e2e-minion-group-5f66", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.7.0-alpha.3.272+69ad6addcc5c25"
name: "e2e-minion-group-ls90", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.7.0-alpha.3.272+69ad6addcc5c25"
```

**Comment by enisoc** [comment]
@mml wrote:
> The question is, do we want the upgrade script to automatically blow up local storage by default? I can't see how to make it work without this, and at the same time it seems a dangerous default.

It may not be too bad. Currently, I don't think there's any *guarantee* your pods will come back when the node is upgraded. If the restart takes too long, the pods will get deleted and rescheduled on another node. However, I admit in practice many people may be relying on this unguaranteed behavior. Speaking of which, is the drain going to be opt-in, out-out, or required?

Perhaps we could copy the pattern `kubectl drain` itself uses, which is "quit if such pods exist and make the user re-run the command with `--delete-local-data`". I'm not sure what a good UX for that would be though, and it may require fixing the script to be resumable if it isn't already.

Another option could be to make specifying whether to delete local data a required option when upgrading nodes, so you cannot even run it the first time without already having considered what you want to happen.
