### ISSUE TITLE
Need a way to force the modified-index when starting etcd

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#38341]
Rollback to etcd 2.3.7 is working well, but we have one issue, which is that the `resourceVersion` numbers go backward.  This could really confuse clients, at best.  It would be great if there was a way to set a minimum or starting `modified-index` so that at least the numbers do not go backward.  The numbers don't have to match.

```diff
--- /var/log/kubectl-nodes-start-2.2.1-etcd2.log
+++ /var/log/kubectl-nodes-rollback-2.3.7-etcd2.log
@@ -15,7 +15,7 @@
       kubernetes.io/hostname: e2e-master
     name: e2e-master
     namespace: ""
-    resourceVersion: "25199"
+    resourceVersion: "70"
     selfLink: /api/v1/nodese2e-master
     uid: f763b133-a1f8-11e6-951a-42010af00002
   spec:
@@ -141,7 +141,7 @@
       kubernetes.io/hostname: e2e-minion-group-j5v8
     name: e2e-minion-group-j5v8
     namespace: ""
-    resourceVersion: "25207"
+    resourceVersion: "72"
     selfLink: /api/v1/nodese2e-minion-group-j5v8
     uid: f8d97bfa-a1f8-11e6-951a-42010af00002
   spec:
@@ -365,7 +365,7 @@
       kubernetes.io/hostname: e2e-minion-group-sig0
     name: e2e-minion-group-sig0
     namespace: ""
-    resourceVersion: "25210"
+    resourceVersion: "74"
     selfLink: /api/v1/nodese2e-minion-group-sig0
     uid: f5bf2f2f-a1f8-11e6-951a-42010af00002
   spec:
FAIL start/nodes != rollback/nodes
```

@hongchaodeng @xiang90 @wojtek-t

**Comment by wojtek-t** [comment]
We were discussing this with @xiang90 and @hongchaodeng and they said that this will be hard.
We also talked about it with @lavalamp and IIRC the conclusion was that we really really really would like to be convinced into "migrate forward" path and then rollback is something that we hopefully never do.

But yeah, i agree that if we could make them not decrease, that would be awesome.
