### ISSUE TITLE
HPA defaulting varies in different groups

### ISSUE THREAD

**Issue by ymqytw** [kubernetes/kubernetes#38353]
Defaulting in [`extensions`](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/v1beta1/defaults.go#L128) is different from the one in [`autoscaling`](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/autoscaling/v1/defaults.go#L30) group.

@kubernetes/autoscaling

**Comment by jszczepkowski** [comment]
@piosz 

When you were moving HPA to apis/autoscaling/v1, you didn't copy the default for CPU usage:

https://github.com/kubernetes/kubernetes/pull/20501/files#diff-6b15f453d0ad9c68076d5d038c375f91

Was it just a mistake, or did it have a reason?

**Comment by fgrzadkowski** [comment]
IIRC we didn't want this default to be part of our API, rather implementation detail of the controller. It's now applied in the controller itself. @piosz please correct me if I'm wrong.

**Comment by DirectXMan12** [comment]
IIRC, the reason was that we couldn't have normal defaulting logic with the alpha custom metrics annotation without having issues, so autoscaling/v1 has no normal defaulting logic.  The v2alpha1 API should fix this issue.

**Comment by fgrzadkowski** [comment]
I'm not sure if we want to default on the api level. To be honest I'd prefer to make it a controller internal thing. I imagine that different implementations might have different policies here. WDYT?

**Comment by piosz** [comment]
Filip is right. This is working as intended, because to add a possibility to scale based on custom metrics we don't want cpu to be set anyway.
