### ISSUE TITLE
Kubelet should not rely on the runtime to generate node status.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#38373]
Currently, kubelet calls `ListImages` to get image list directly from the runtime (see [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status.go#L562) and [here](https://github.com/kubernetes/kubernetes/blob/1dfd64f4378ad9dd974bbfbef8e90127dce6aafe/pkg/kubelet/images/image_gc_manager.go#L150)).

We recently hit an issue https://github.com/docker/docker/issues/21215. Bulk image deletion/creation will cause `ListImages` to hang.
When that happens, kubelet has to wait until `ListImages` times out (2 min). If node status is updated by other components during that time (NPD, route controller, node controller etc.), kubelet will not be able to update status because of conflict.

Usually, when that happens, container should be able to work normally. However, pods will be evicted by node controller unnecessarily because kubelet can't update node status for a long time, and node controller thinks the node is `NotReady`.

Kubelet should not rely on the runtime to generate node status.

@yujuhong 
/cc @kubernetes/sig-node

**Comment by Random-Liu** [comment]
This should be fixed in 1.5.1 to solve the customer issue.

**Comment by yujuhong** [comment]
Should also patch it to 1.4

**Comment by yujuhong** [comment]
Let's patch it to 1.4 and 1.5.

**Comment by Random-Liu** [comment]
@yujuhong Will do that after debugging https://github.com/kubernetes/kubernetes/issues/38439

**Comment by Random-Liu** [comment]
The PR has been cherry picked into 1.4 (#38605) and 1.5 (#38721).

Close this issue, feel free to reopen.
