### ISSUE TITLE
Remove stale branches from the repo

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#38383]
Is there any reason for keeping around the stale branches in this repo?
https://github.com/kubernetes/kubernetes/branches/stale

@saad-ali @pwittrock

**Comment by kargakis** [comment]
@kubernetes/sig-release-misc

**Comment by alexandercampbell** [comment]
It would appear that the only branches in the repo are pointers to release commits. Do those count as stale? :)
