### ISSUE TITLE
kubeadm return codes not documented

### ISSUE THREAD

**Issue by jarrpa** [kubernetes/kubernetes#38399]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**kubeadm version**:
kubeadm version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.2.421+a6bea3d79b8bba", GitCommit:"a6bea3d79b8bbaa5e8b57482c9fff9265d402708", GitTreeState:"clean", BuildDate:"2016-11-03T06:54:50Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: libvirt VMs
- **OS** (e.g. from /etc/os-release): CentOS 7
- **Kernel** (e.g. `uname -a`): Linux master 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**What happened**: There is no documentation, anywhere best I can tell, for hte return codes of kubeadm.

**What you expected to happen**: `kubeadm --help` or `kubeadm init --help` should display the error codes returned and what they mean.

**Comment by neolit123** [comment]
@jarrpa what error codes do you mean?
kubeadm is doing Exit(1) in case of a fatal error, so the only error code is 1?
have you seen others?

also, i'm closing this issue.
if you feel it needs discussion - open it in the kubernetest/kubeadm tracker.

/close

**Comment by jarrpa** [comment]
@neolit123 https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/error.go#L27-L33

I will re-open this issue elsewhere, accordingly.

**Comment by neolit123** [comment]
ok, these are definitely not documented on --help
try logging an issue in k/kubeadm.
