### ISSUE TITLE
StatefulSet does not recreate Pods at a lower ordinal until successor Pods are Running and Ready

### ISSUE THREAD

**Issue by kow3ns** [kubernetes/kubernetes#38418]
[In the current StatefulSet implementation](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/petset/pet.go#L125-L136) a situation exists that can cause deadlock under the following conditions.

1. StatefulSet S is created with 3 replicas {s0,s1,s2}.
2. S creates s0.
3. s0 passes its liveness and readiness probes.
4. S creates s1, and s1 depends on s0 to be Running and Ready for its own readiness probe to pass (This occurs if s0 is the canonical element of the Set on whose health all other Pods in the set depend. An example of this is a replication topology where s0 is the master and [s1,sn) are read only slaves).
5. s0 is deleted prior to s1 becoming Running and Ready.
6. s1  blocks Pod creation and s0 will not be recreated.

The current implementation attempts to provide the following guarantee.

For any Pod, si, in a StatefulSet S, if any Pod, sj, where si != sj, in S has been created but is not Running and Ready, si will not be created until sj transitions to Running and Ready.

I think that the understood guarantee, and the one that was the original intention is the following.

For any Pod, si, in a StatefulSet S, the StatefulSet controller will not create the Pod unless all Pods, sj , where 0 <= j < i, are Running and Ready.

If this is the case than, in the above deadlock condition, we should recreate s0 allowing the controller to make progress.

@enisoc @erictune @foxish @janetkuo

**Comment by kargakis** [comment]
@smarterclayton @bprashanth

**Comment by bprashanth** [comment]
The petset controller will freeze if it notices any pet is unhealthy so it doesn't make the situation worse. The original design assumed that an admin would intervene at this point to resolve deadlocks. I don't think there's any reason to not be smarter, other than the lack of a clear and universal pattern (which should emerge with more prototypes).

**Comment by smarterclayton** [comment]
I'd like to roll this into the discussion of rolling ss upgrades
because we won't be able to do those without a change for this.
