### ISSUE TITLE
conflicting kube-addon-manager.yaml files in kubernetes-manifests.tar.gz

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#38437]
I was playing around with reproducing the `kubernetes-manifests.tar.gz` tarball inside bazel, and I came across this exciting warning:
```
INFO: From PackageTar build-tools/kubernetes-manifests.tar.gz:
Duplicate file in archive: ./kubernetes/kube-addon-manager.yaml, picking first occurrence
```

Sure enough, we have both a `cluster/saltbase/salt/kube-addons/kube-addon-manager.yaml` and a `cluster/gce/coreos/kube-manifests/kube-addon-manager.yaml` file in the repo, and they differ.

In our current release scripts, we first add `cluster/saltbase/salt/kube-addons/kube-addon-manager.yaml` to our staging directory (https://github.com/kubernetes/kubernetes/blob/74a3b77c734ce88fbe552a505869c61a921c5cda/build-tools/lib/release.sh#L327).

We later add all files in `cluster/gce/coreos/kube-manifests/` to our staging directory (https://github.com/kubernetes/kubernetes/blob/74a3b77c734ce88fbe552a505869c61a921c5cda/build-tools/lib/release.sh#L340-L341), overwriting the `kube-addon-manager.yaml` file already there.

I examined a `kubernetes-manifests.tar.gz` tarball from ci/latest (v1.6.0-alpha.0.1793+5628cde1bd4d80), and the `kube-addon-manager.yaml` contained inside appears to be the one from `cluster/gce/coreos/kube-manifests/`.

The diff:
```patch
$ diff --unified cluster/saltbase/salt/kube-addons/kube-addon-manager.yaml cluster/gce/
coreos/kube-manifests/kube-addon-manager.yaml
--- cluster/saltbase/salt/kube-addons/kube-addon-manager.yaml   2016-12-07 14:10:41.545198284 -0800
+++ cluster/gce/coreos/kube-manifests/kube-addon-manager.yaml   2016-12-07 14:10:41.453198288 -0800
@@ -3,33 +3,23 @@
 metadata:
   name: kube-addon-manager
   namespace: kube-system
-  labels:
-    component: kube-addon-manager
+  version: v1
 spec:
   hostNetwork: true
   containers:
   - name: kube-addon-manager
-    # When updating version also bump it in cluster/images/hyperkube/static-pods/addon-manager.json
-    image: gcr.io/google-containers/kube-addon-manager:v6.1
-    command:
-    - /bin/bash
-    - -c
-    - /opt/kube-addons.sh 1>>/var/log/kube-addon-manager.log 2>&1
+    image: gcr.io/google-containers/kube-addon-manager:v1
     resources:
       requests:
         cpu: 5m
-        memory: 50Mi
+        # TODO(yifan): Figure out what's the memory usage should be here.
+        # See https://github.com/kubernetes/kubernetes/issues/23641.
+        memory: 100Mi
     volumeMounts:
     - mountPath: /etc/kubernetes/
       name: addons
       readOnly: true
-    - mountPath: /var/log
-      name: varlog
-      readOnly: false
   volumes:
   - hostPath:
       path: /etc/kubernetes/
     name: addons
-  - hostPath:
-      path: /var/log
-    name: varlog
```

Not sure if this is actually an issue or not.

cc @MrHohn @caesarxuchao @mikedanese @yifan-gu who touched this recently.

**Comment by MrHohn** [comment]
Sorry, should have kept on addon manager YAMLs in sync.

But I'm surprise the release script adds this file twice from different locations.

**Comment by ixdy** [comment]
Yeah, that's certainly a bug that I want to fix.

**Comment by mikedanese** [comment]
I think you want strip_prefix = "." in your package tar rule to preserve directory structure.

**Comment by ixdy** [comment]
@mikedanese I'm reproducing the existing behavior in `build-tools/lib/release.sh`, which seems to collapse the directory structure in some cases.

**Comment by ixdy** [comment]
oh, false alarm. `cluster/saltbase/salt/kube-addons/kube-addon-manager.yaml` is copied to `${dst_dir}`, i.e. `${release_stage}/gci-trusty`, whereas `cluster/gce/coreos/kube-manifests/kube-addon-manager.yaml` is copied to `${release_stage}`.

`kube::release::package_kube_manifests_tarball` is a rather terrible function. :(
