### ISSUE TITLE
IRC links to jenkins.kubernetes.io don't work

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#3843]
IRC gets status reports from builds, but the included links don't work.
> [12:25] <jenkins-k8s-b0t> Project kubernetes-e2e-gce build #1609: FIXED in 40 min: http://jenkins.kubernetes.io/job/kubernetes-e2e-gce/1609/

And my browser:
> The server at jenkins.kubernetes.io can't be found, because the DNS lookup failed.

Zach, I think you've been doing jenkins work?  Or perhaps this is @brendandburns ?

**Comment by zmerlynn** [comment]
Yeah, this is because the Jenkins server is still not public at all, and we'd rather not spam the private URL. I'm happy to own it but it's going to sit for a while.

**Comment by alex-mohr** [comment]
Okay, thanks Zach -- P3.
