### ISSUE TITLE
Creating GCE cluster is generating deprecation warnings

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#38459]
```
WARNING: You are creating a legacy network. Using --mode=legacy will be required in future releases.
```

@kubernetes/sig-cluster-lifecycle

**Comment by roberthbailey** [comment]
Are you seeing this in e2e test output or when you run kube-up.sh?

**Comment by wojtek-t** [comment]
This particular warning was from e2e. But I didn't check if the same is in kube-up or not.

**Comment by ethernetdan** [comment]
@wojtek-t can this be closed?

**Comment by wojtek-t** [comment]
I think so.
