### ISSUE TITLE
kube-proxy does not handle persistent connections very well

### ISSUE THREAD

**Issue by jsravn** [kubernetes/kubernetes#38456]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
kube-proxy service iptables
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

**Anything else do we need to know**:

Anyone taking Kubernetes to production generally ends up having to bypass kube-proxy to have sensible service load balancing between components. People are using sidecar http proxies, haproxy replacements of kube-proxy, and other types of workarounds to deal with the limitations of kube-proxy.

Problems with kube-proxy:
1. Simplistic, naive load balancing using probabilities, that can easily result in imbalanced requests to downstream systems.
2. Poor support for keepalive connections, which most http/rpc clients use. (1) exacerbates this, since the poor balancing persists for a long time under load. Rolling deployments can skew it even further.
3. Impossible to do non-disruptive deployments when (2) keepalives are involved - there isn't a great way to gracefully drain the connections or move them to the new pods.

As a result, I find kube-proxy is only suitable for the most simple use cases. It needs a rethink. A solution would be a userspace proxy which is endpoint aware. kube-proxy really needs some attention!

**Comment by MrHohn** [comment]
cc @kubernetes/sig-network

**Comment by bprashanth** [comment]
Can you provide a repro of the keepalive issues to clarify?

**Comment by bowei** [comment]
@bprashanth re: keepalive issue, it probably refers to the fact that connections remain mapped to the same server. However, this is a problem whenever load balancing is done at the TCP level rather than the application level. The usual solution is for the application layer to provide a way to tell clients to reconnect and create new channel. For example, the HTTP protocol has the "Connection: close" which is used by servers to keepalive and drain their existing client.

I have seen the same imbalance issue with other load balancers (Linux IPVS) at scale and the solution is usually a change higher in the stack.

**Comment by jsravn** [comment]
That's right, although I don't particularly agree that this is just an issue with layer 4 load balancing.

A big problem is the use of a simple probability to distribute connections. This makes the situation much worse. If one pod dies then reconnecting keepalives will get distributed to the remaining pods - a common scenario during rolling deploys - but any replacement pod won't get its fair share of connections as a result. As this happens regularly, the distribution will get more and more skewed - we see this even in simple low replica setups. Just having low number of replicas will generally always lead to bad imbalances, like all requests going to 1 replica in a 2-3 replica setup if you get unlucky. If kube-proxy did slightly smarter connection routing, something like least number of connections, then we could still maintain a reasonable distribution of connections. Or even allow people to select from different strategies - I could conceive of k8s being smart enough to route based on container cpu utilisation for example.

Handling rolling deployments non-disruptively with persistent connections is difficult to solve at layer4. If kube-proxy supported layer7 protocols (perhaps via plugin mechanism) it could solve this transparently though. Right now clients have to solve this - which also breaks the service IP abstraction. I feel that kube-proxy becomes sort of useless as a result, along with service IPs.

I'm not that familiar with IPVS so I freely admit I could be simplifying things too much. I feel like kube-proxy could be much better for general usage - and I think it would have a large impact on most people's use cases. kube-proxy limitations I feel is a common theme with most people running real k8s setups.

**Comment by jsravn** [comment]
I updated my description since on second thought it isn't necessarily an iptables problem.

**Comment by bprashanth** [comment]
There are 3 efforts in this space: 

1. Service proxy and/or "internal" ingress (https://github.com/kubernetes/kubernetes/issues/28443, https://groups.google.com/forum/#!topic/kubernetes-sig-network/rIRExoC5Dp0 etc). Basically you'll get a proxy (various deployment styles like sidecar, per node, or bank of internal lb) that makes routing descisions and the kube-proxy part will just trap and redirect a vip from DNS. Hand waving because the design is in flight. 
2. IPVS kubeproxy https://github.com/kubernetes/kubernetes/pull/30134
3. Better userspace kubeproxy (I have a prototype that uses splice and is quite a bit faster)

**Comment by bprashanth** [comment]
"in this space" meaning better algorithms for intra cluster request routing

**Comment by thockin** [comment]
NB: the port-ranges proposal pretty much breaks IPVS, with the possible
exception of "whole IP" forwarding.

**Comment by jsravn** [comment]
Maybe if pod deletion had some sort of connection draining, it could help mitigate some of the issues.

Something like this could happen when deleting a pod:
# Endpoint is removed for pod
# kubelet monitors connections to that pod, and waits up to `connectionDrainingTimeout` for all the connections to terminate - this gives time for persistent connections to terminate, while preventing new connections
# Once all connections are terminated, or the timeout is hit, kubelet proceeds with the normal pod deletion process (sigterm, wait for graceful shutdown time)

If the persistent connections are not kept open for too long, it could prevent stale connections given enough time.

A simple version of this is to support a delay before pods get terminated, after the endpoint is removed.

**Comment by thockin** [comment]
This is called "graceful termination" and we already have it.  The pod
states how long it needs to drain connections.  When you delete the pod,
SIGTERM is sent, and the pod is removed from Endpoints groups.  The timer
starts.  after the timer expires, if the pod has not exited, it gets
SIGKILL.

**Comment by bprashanth** [comment]
Fyi I believe the nginx "master" process handles SIGTERM as a quick shutdown, and QUIT as a graceful shutdown, so you might need a wrapper that does the translation (accepts TERM, sends QUIT to /usr/local/nginx/logs/nginx.pid or wherever)

**Comment by thockin** [comment]
or you can set the STOPSIGNAL in Dockerfile.  It is SIGTERM by default.

**Comment by jsravn** [comment]
Nginx doesn't do connection draining, neither do most open source web frameworks. Instead they finish processing any in-flight requests, possibly return 503s for a short time, then terminate. In this case, it's very likely for high load servers to then send tcp resets to clients (which btw, is perfectly okay according to http rfc - but in practice, is not okay). The way many people solve this is by sticking a load balancer in front with connection draining behaviour. The endpoint (in k8s terminology) is removed, then the load balancer waits a period of time before finally detaching / stopping the backend service. With kubernetes, the second part is missing - instead one has to implement this in the pod. I'm now doing this as a workaround by doing a sleep in the preExec step in all of our pods (I think kube-dns does something similar?), but it's hacky.

**Comment by bowei** [comment]
@jsravn -- wondering why clients would get TCP resets from nginx during a graceful shutdown (SIGQUIT)? The listen socket is gone, which means there are no new connections and each existing connection is processed with "Connection: close" with the reply. You will see a RST if a client decides to never go away despite being told to do so, but that is something that the server cannot control.

**Comment by jsravn** [comment]
Because nginx doesn't wait for clients to close their side of the
connection before closing the socket. As soon as all in flight requests are
finished processing, it closes the socket. Clients can then get a reset if
either they already started sending a new request (but it hasn't reached
nginx's host yet), or in the case of many common http clients, sending data
on a previously used keepalive connection which is now "stale" or in a half
open state. The latter happens because it's difficult to detect that the
connection has been closed asynchronously. The commercial version of nginx
has connection draining to help mitigate this.

As I mentioned already this is perfectly within the http RFC - clients are
expected to handle such asynchronous closing of the connection. In practice
this means some sort of app logic to deal with non idempotent requests
which fail (such as browser dialogue or pop-up), or accepting a certain
level of failed requests during deploys. If trying to obtain 0 downtime
deploys more work must be done on the server side to intelligently peel off
connections and move them to the new service.

**Comment by bowei** [comment]
ah ok -- I may have confused that feature that in a previous life may have been a custom modification to a hacked up version nginx, did not know that it was only available in the paid version.

**Comment by pmcq** [comment]
@thockin Can you clarify "The pod states how long it needs to drain connections"?  I haven't been able to find docs for how to specify that.  I do know how to set readinessChecks and setting `terminationGracePeriodSeconds` so that SIGKILL will be delayed.  However it seems that kube-proxy will remove the iptables rules immediately (not after some drain period).

**Comment by thockin** [comment]
On Wed, Mar 22, 2017 at 3:22 PM, pmcq <notifications@github.com> wrote:
>
> @thockin Can you clarify "The pod states how long it needs to drain connections"? I haven't been able to find docs for how to specify that. I do know how to set readinessChecks and setting terminationGracePeriodSeconds so that SIGKILL will be delayed. However it seems that kube-proxy will remove the iptables rules immediately (not after some drain period).

Kube-proxy will remove rules ASAP to prevent *new* connections.
Existing connections should be fine - that's what you need to drain.

**Comment by jsravn** [comment]
Has anyone investigated using SDN (openflow) and openvswitch? Then we could have a centralised controller in controller manager which basically manages all this stuff dynamically, with an openvswitch per node. It would be pretty straightforward to add sophisticated load balancing as well, draining, and lots of other things.

**Comment by chethiya1996** [comment]
@jsravn  @bowei Hi, currently we are using kubernetes version "1.5.7" and we are also facing the same issue, we have planned to upgrade to kuberntes version "1.11" so I am wondering whether this issue is still there in version "1.11" as well.

**Comment by bowei** [comment]
1.5.7 is extremely old and not supported. You should update a supported version (1.12+)

**Comment by glenjamin** [comment]
I came across this issue when searching for solutions to our keepalive problems - we’re currently trying to make our application servers detect and close and keepalive connections during shutdown.

Is there any way to have kube-proxy remove itself from the flow and add the pod host:port combinations directly to the upstream load balancer pool?

**Comment by epollan** [comment]
> > On Wed, Mar 22, 2017 at 3:22 PM, pmcq ***@***.***> wrote: 
> > @thockin Can you clarify "The pod states how long it needs to drain connections"? I haven't been able to find docs for how to specify that. I do know how to set readinessChecks and setting terminationGracePeriodSeconds so that SIGKILL will be delayed. However it seems that kube-proxy will remove the iptables rules immediately (not after some drain period).
> >
> Kube-proxy will remove rules ASAP to prevent *new* connections. 
> Existing connections should be fine - that's what you need to drain.

I'm seeing evidence that kube-proxy is leaving rules in place when a pod has non-zero inactive connections, even well past the point the pod has actually been deleted.

This is using the ipvs implementation, fwiw.

**Comment by young-0** [comment]
spec.containers add
```
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sleep","90"]
        terminationGracePeriodSeconds: 120
```
