### ISSUE TITLE
Kubectl reaper fails to delete Jobs

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#38497]
I added Jobs to our scalability tests: #38461 and I can't get it succeed when running Load. The test creates a big number of Jobs of various sizes using Pods that never finish, resizes them twice, and then tries to delete them. The result I see is the following:
```
STEP: deleting {batch Job} load-small-11 in namespace e2e-tests-load-30-nodepods-1-ch417, will wait for the garbage collector to delete the pods
STEP: deleting {batch Job} load-medium-13 in namespace e2e-tests-load-30-nodepods-1-ch417, will wait for the garbage collector to delete the pods
STEP: deleting {batch Job} load-small-207 in namespace e2e-tests-load-30-nodepods-1-ch417, will wait for the garbage collector to delete the pods
Dec  9 15:01:50.391: INFO: Deleting {batch Job} load-small-11 took: 134.161968ms
Dec  9 15:01:51.483: INFO: Deleting {batch Job} load-medium-13 took: 135.599372ms
Dec  9 15:01:51.636: INFO: Deleting {batch Job} load-small-207 took: 135.699499ms
Dec  9 15:06:53.765: INFO: Unexpected error occurred: error while waiting for pods to become inactive load-small-292: timed out waiting for the condition
Dec  9 15:06:56.280: INFO: Unexpected error occurred: error while waiting for pods to become inactive load-small-36: timed out waiting for the condition
Dec  9 15:06:56.967: INFO: Unexpected error occurred: error while waiting for pods to become inactive load-medium-12: timed out waiting for the condition
Dec  9 15:06:59.503: INFO: Unexpected error occurred: error while waiting for pods to become inactive load-small-231: timed out waiting for the condition
```

I use `kubectl.Reaper` to delete those jobs so I expect it should work.

cc @wojtek-t @timothysc @jeremyeder

@erictune - which SIG owns a job?

**Comment by soltysh** [comment]
@gmarek @kubernetes/sig-apps owns jobs
This looks similar to #28977, I'm hoping to implement server-side reaping for CronJobs and Jobs. Hopefully that should address the problem.

**Comment by kargakis** [comment]
+1 for adding server-side reaping

**Comment by grodrigues3** [comment]
@timothysc can you verify that this release blocking and the 1.6 milestone is still valid

**Comment by grodrigues3** [comment]
@gmarek is anyone working on this?

**Comment by soltysh** [comment]
@grodrigues3 we have https://github.com/kubernetes/kubernetes/pull/42176 but not sure if this will be added to 1.6. With this in we'll be closer to server-side reaping, which should fix the original issue. I don't think this is a release blocker for 1.6, though.

**Comment by wojtek-t** [comment]
Agree - it's not a regression, so moving it to 1.7 seems like a good thing to do.

**Comment by kargakis** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/42176
