### ISSUE TITLE
New log rotation mechanism required

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#38495]
For the context: https://github.com/kubernetes/kubernetes/issues/28369 https://github.com/kubernetes/kubernetes/issues/37292 https://github.com/kubernetes/kubernetes/issues/29715

Current mechanism, running logrotate as a cron job hourly in the copytruncate mode poses several problems

* copytruncate mode doesn't integrate well with external logging agents
  * line broken in the middle can sometimes make fluentd enter infinite crashloop (hard to reproduce, so no issue for that, but happened several times during high load)
  * logging agent store read offsets, but copytruncate makes these offsets invalid, which may result in losing lines between the old offset and the size of file right before the rotation
* Rotating logs hourly without the ability to reconfigure doesn't scale very well for highly verbose applications

Something should be implemented to replace the current solution, either on the node level or as a DaemonSet.

CC @kubernetes/sig-node @kubernetes/sig-instrumentation

**Comment by daniilyar** [comment]
Docker has it's own native log rotation. For docker json-log driver, just set:

```
--log-opt max-size=[0-9]+[kmg]
--log-opt max-file=[0-9]+
```

Just need to proxy appropriate options vi Pod and RC definitions.
From my experience, using docker native logs rotation doesn't break tools, reading logs via Docker API (e.g. logspout).

**Comment by Crassirostris** [comment]
@daniilyar Thanks! I know about this mechanism, there're several things to consider, including:

* Json logging drivers are specific for docker, are using their own format and are not compatible with other runtimes
* AFAIK, those settings are set globally for the docker daemon, not per container run

Currently we're looking into details, I hope we will soon have some vision about this problem, expressed in the design proposal.

**Comment by Crassirostris** [comment]
Related issue: https://github.com/kubernetes/kubernetes/issues/15478

**Comment by daniilyar** [comment]
@Crassirostris , docker `--log-opts` can be set at per-container basis:
```
docker run --help | grep Log
      --log-driver string           Logging driver for the container
      --log-opt value               Log driver options (default [])
```

**Comment by Crassirostris** [comment]
@daniilyar Great, thanks a lot! I missed that

**Comment by baldeynz** [comment]
Hi all
We are trying to follow this issue and  add docker logging options to our kubernetes deployments for log rolling e.g --log-opt max-size=10m

For example if we ran something like this directly using docker

docker run -it --log-opt max-size=10m --log-opt max-file=2 image-name

We can use docker inspect to see those options added to the LogConfig e.g

"LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "2",
                    "max-size": "10m"
                }
            },

And the logs roll as intended. When we try and define this in our kubernetes deployment we dont get logs rolling.

Here is what we have defined in our deployment:

containers:
      - image: ourlocalrepo/deployments/our_pod:latest
        command:
        - java
        - -Djava.security.egd=file:/dev/./urandom
        - -Dlog4j.configurationFile=/etc/logs-config/log4j2.xml
        - -Xms128m
        - -Xmx256m
        - -jar
       env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
imagePullPolicy: Always
        name: "our_pod"
        ports:
        - containerPort: 80
          protocol: TCP
        args:
        - "--log-opt max-size=10m"
        - "--log-opt max-file=2"

When this deployment is run and the pod comes up on a node we can use docker inspect and see that these args are added to Cmd:

"Cmd": [
                "--log-opt max-size=10m",
                "--log-opt max-file=2"
            ],

Instead of the LogConfig section as they should be - LongConfig still looks like this :

"LogConfig": {
                "Type": "json-file",
                "Config": {}
            },

Can anyone point me the right direction to get the kubernetes deployment to add these log options?

thanks!!

**Comment by crassirostris** [comment]
@baldeynz I believe so, Kubernetes doesn't allow to do so. It tries to abstract runtime engine away

You can set up default value per-node though, by changing the docker daemon startup flags

**Comment by SergeyKanzhelev** [comment]
> /assign

@dashpole this assignment happened last year. Do you still want to work on this?

as per the issue - log rotation is implemented in CRI now. And Dockershim is deprecated. Is this still an issue? 

KEP: https://github.com/kubernetes/enhancements/issues/2411

**Comment by SergeyKanzhelev** [comment]
/close

please re-open if the bug is still relevant
