### ISSUE TITLE
GCE EnsureLoadBalancer() for static IPs should error if the IP is not static

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#38521]
Seen by inspection, potentially a cause for a user-reported symptom.

Setup:
1. Create a Service, type=LoadBalancer
2. A public IP is assigned
3. Copy that public IP to the Service's locadBalancerIP field

The assumption is that this guarantees your Service will use that IP.  That's true, but it was true without step 3.  If you now delete this Service and create a new one with that loadBalancerIP, it will fail because that IP is not a GCE static address, and was released with your Service.

We should instead throw an error if you do step 3, but have not manually promoted that IP to a static IP through GCE.  This will force users to acknowledge that *they* own that IP, not kubernetes.

This behavior, combined with the fact that we log-and-forget failures to release the IP can result in public addresses being "promoted" to static and left there, without the user having done that action == a leak.

**Comment by thockin** [comment]
@bprashanth

**Comment by thockin** [comment]
@nicksardo keep this or close it?

**Comment by nicksardo** [comment]
I agree that it's worthwhile to inform users that their IP is not secured; however, I would argue that ceasing service syncs (erroring) is too aggressive. The controller can temporarily reserve the address, so there's no immediate reason why we cannot continue syncing. I suggest raising a warning event on the service.

**Comment by thockin** [comment]
@bowei - keep or close?

**Comment by bowei** [comment]
Let's close -- I haven't seen any customer issues around this behavior for years now.

/close
