### ISSUE TITLE
Upgrade tests for federation

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#38537]
We need automated tests to verify federation upgrades. Here are the list of things we need to do:

* Define what it means to upgrade test federation.
* Define the APIs/features we want to include in the tests.
* Define the exact tests and implement them.
* Setup the infrastructure to run these tests: jenkins jobs, test-grid, etc.

cc @kubernetes/sig-federation @matchstick @nikhiljindal

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by marun** [comment]
I assume this shouldn't be blocking 1.7.

**Comment by dims** [comment]
@quinton-hoole @marun we should not block 1.8 too right? looks like this slipped 1.7 too

**Comment by madhusudancs** [comment]
Assigning it to @quinton-hoole and @marun for triage.

 /assign @quinton-hoole @marun

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#87.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
