### ISSUE TITLE
Events stream should include all pod state events

### ISSUE THREAD

**Issue by DreadPirateShawn** [kubernetes/kubernetes#38532]
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

Looking at http://kubernetes.io/docs/user-guide/pod-states/ we see descriptions like:

**Pod is Running, 1 container, container exits failure**
* Log failure event
* If RestartPolicy is:
    * Always: restart container, pod stays Running
    * OnFailure: restart container, pod stays Running
* Never: pod becomes Failed

However, no event gets created -- we do see an entry in the text logs:

```
I1209 21:23:48.400278    2744 manager.go:324] Container inspect result: {ID:cdc28d98c8ab3c5ab1d896e7b8c1853281db631b2409fd03c223ea1419636976 Created:2016-12-09 21:23:28.18667361 +0000 UTC Path:/bin/bash A
rgs:[] Config:0xc20833e380 State:{Running:false Paused:false Restarting:false OOMKilled:false Pid:0 ExitCode:1 Error: StartedAt:2016-12-09 21:23:28.339306404 +0000 UTC FinishedAt:2016-12-09 21:23:47.40603
9157 +0000 UTC} Image:sha256:4ca3a192ff2a5b7e225e81dc006b6379c10776ed3619757a65608cb72de0a7f6 Node:<nil> NetworkSettings:0xc208bc6200 SysInitPath: ResolvConfPath:/var/lib/docker/containers/234f6db095d8424
a4005daa116a28e0a0aa1f21a4428b931d4b9d07458792906/resolv.conf HostnamePath:/var/lib/docker/containers/234f6db095d8424a4005daa116a28e0a0aa1f21a4428b931d4b9d07458792906/hostname HostsPath:/var/lib/kubelet/p
ods/99f39b1b-be55-11e6-a1d4-0050563039c2/etc-hosts LogPath:/var/lib/docker/containers/cdc28d98c8ab3c5ab1d896e7b8c1853281db631b2409fd03c223ea1419636976/cdc28d98c8ab3c5ab1d896e7b8c1853281db631b2409fd03c223e
a1419636976-json.log Name:/k8s_ubu.9b7609c8_ubu-4125056288-716pr_default_99f39b1b-be55-11e6-a1d4-0050563039c2_0dd3797d Driver:aufs Mounts:[{Name: Source:/var/lib/kubelet/pods/99f39b1b-be55-11e6-a1d4-00505
63039c2/containers/ubu/0dd3797d Destination:/dev/termination-log Driver: Mode: RW:true} {Name: Source:/var/lib/kubelet/pods/99f39b1b-be55-11e6-a1d4-0050563039c2/volumes/kubernetes.io~secret/default-token-
whb42 Destination:/var/run/secrets/kubernetes.io/serviceaccount Driver: Mode:ro RW:false} {Name: Source:/var/lib/kubelet/pods/99f39b1b-be55-11e6-a1d4-0050563039c2/etc-hosts Destination:/etc/hosts Driver:
Mode: RW:true}] Volumes:map[] VolumesRW:map[] HostConfig:0xc2090b58c0 ExecIDs:[] RestartCount:0 AppArmorProfile:}
```

... but nothing appears in "get events".

Note: I see a few seeminly-related tickets, eg #37616 #5927 #6014 -- but as far as I can tell, they all seem to be focused on specific types of errors, and some focus on "get pod" output... I'm not sure there's a ticket to track all pod state events from http://kubernetes.io/docs/user-guide/pod-states/ to appear in the events stream.

**Comment by resouer** [comment]
@DreadPirateShawn To be clear, you are suggesting that the Pod (container) is successfully started, but it exited after that, and no event is reported. Right?

**Comment by DreadPirateShawn** [comment]
@resouer Sorry for the delay. That's correct.

More details / repro:

Step 1) Have a running pod:
```
$ kubectl --namespace=foo get pods -o wide
NAME                                   READY     STATUS        RESTARTS   AGE       IP         NODE
po/foo-965512844-9j46w                 1/1       Running       0          25s       10.x.x.x   node3
```

Step 2) Check original events for pod:
```
$ kubectl --namespace=foo get events | grep 9j46w
55s        55s         1         foo-965512844-9j46w    Pod                                      Normal    Scheduled           {default-scheduler }       Successfully assigned greenbox-965512844-9j46w to node3
54s        54s         1         foo-965512844-9j46w    Pod          spec.containers{greenbox}   Normal    Pulled              {kubelet node3}            Container image "foo:bd54846ef4f2647f5b11fa1b9b19802b1608a346" already present on machine
54s        54s         1         foo-965512844-9j46w    Pod          spec.containers{greenbox}   Normal    Created             {kubelet node3}            Created container with docker id 6b5f4c8b5bd8; Security:[seccomp=unconfined]
54s        54s         1         foo-965512844-9j46w    Pod          spec.containers{greenbox}   Normal    Started             {kubelet node3}            Started container with docker id 6b5f4c8b5bd8
55s        55s         1         foo-965512844          ReplicaSet                               Normal    SuccessfulCreate    {replicaset-controller }   Created pod: greenbox-965512844-9j46w
```

So far, so good.

Step 3) Pretend to be an OOM killer -- ssh to node3 and "docker kill" the foo pod's container.
```
$ docker ps | grep foo
6b5f4c8b5bd8        foo:bd54846ef4f2647f5b11fa1b9b19802b1608a346        "startup.sh"   About a minute ago   Up About a minute                       k8s_foo.9a4b6251_foo-965512844-9j46w_foo_92db1848-f557-11e6-bf80-0050560088b4_a37db15c

$ docker kill 6b5f4c8b5bd8
6b5f4c8b5bd8
```

Step 4) Confirm that pod has been killed/restarted:
```
$ kubectl --namespace=foo get pods -o wide
NAME                                READY     STATUS    RESTARTS   AGE       IP         NODE
foo-965512844-9j46w                 1/1       Running   1          2m        10.x.x.x   node3
```

Step 5) Check events for pod -- the new pod's start event is seen, but no failure event is seen for the container death:

```
$ kubectl --namespace=foo get events | grep 9j46w
2m         2m          1         foo-965512844-9j46w    Pod                                      Normal    Scheduled           {default-scheduler }       Successfully assigned greenbox-965512844-9j46w to node3
50s        2m          2         foo-965512844-9j46w    Pod          spec.containers{greenbox}   Normal    Pulled              {kubelet node3}            Container image "foo:bd54846ef4f2647f5b11fa1b9b19802b1608a346" already present on machine
2m         2m          1         foo-965512844-9j46w    Pod          spec.containers{greenbox}   Normal    Created             {kubelet node3}            Created container with docker id 6b5f4c8b5bd8; Security:[seccomp=unconfined]
2m         2m          1         foo-965512844-9j46w    Pod          spec.containers{greenbox}   Normal    Started             {kubelet node3}            Started container with docker id 6b5f4c8b5bd8
50s        50s         1         foo-965512844-9j46w    Pod          spec.containers{greenbox}   Normal    Created             {kubelet node3}            Created container with docker id 095e624a722a; Security:[seccomp=unconfined]
50s        50s         1         foo-965512844-9j46w    Pod          spec.containers{greenbox}   Normal    Started             {kubelet node3}            Started container with docker id 095e624a722a
2m         2m          1         foo-965512844          ReplicaSet                               Normal    SuccessfulCreate    {replicaset-controller }   Created pod: foo-965512844-9j46w
```

**Comment by resouer** [comment]
If only in this case, since the container is killed from outside (and not a OOM kill), there's no event kubelet should report.

But I think what you are expecting  is events can include more information like container failure?

**Comment by resouer** [comment]
And #37616 describes we should report more **container life cycle** events, I think although you are saying pod lifecycle, you are actually means the container life cycle (like: `Created container with docker id 095e624a722a`). If in this case, this is dup to #37616

**Comment by andyxning** [comment]
@resouer @DreadPirateShawn I think we need to bring more container and pod info, such as pod labels, through pod events when containers or pod phase change.

**Comment by resouer** [comment]
More lifecycle events will be added, but pod change details are definitely out of scope of events.

Deployment's revision is used to check difference between deployments. For example: 
```
$ kubectl rollout history deployment/nginx-deployment --revision=2
deployments "nginx-deployment" revision 2
  Labels:       app=nginx
          pod-template-hash=1159050644
  Annotations:  kubernetes.io/change-cause=kubectl set image deployment/nginx-deployment nginx=nginx:1.9.1
  Containers:
   nginx:
    Image:      nginx:1.9.1
    Port:       80/TCP
     QoS Tier:
        cpu:      BestEffort
        memory:   BestEffort
    Environment Variables:      <none>
  No volumes.
```

**Comment by DreadPirateShawn** [comment]
@resouer I think my original train of thought was that the doc http://kubernetes.io/docs/user-guide/pod-states/ describes things in the context of "Pod lifetime", and the "get events" output generally includes pod name with each event, so in my mind this was a "pod event" that wasn't appearing.

(I certainly don't mean pod change details, eg labels and such -- totally understood, those aren't in the same realm as events.)

Would #37616 include the case where the host's OOM killer kills the container?

I ask b/c above you said:
> since the container is killed from outside (and not a OOM kill)
but I want to make sure I understand properly -- do you mean that only *internally-triggered* OOM events will be logged?

The pod lifetime doc seems to read as if any actions that result in a container death should result in an event -- container exit success, container exit failure, container OOM, disk death -- if there are clear ways for a container to die unexpectedly and *not* generate an event, that might be worth calling out more clearly? (I know it's easy to overthink docs -- just explaining our reasoning when filing.)

**Comment by resouer** [comment]
I see, I've worked out a patch that will send out event when container exited.

**Comment by kensimon** [comment]
@resouer's patch ultimately wasn't merged but I took a stab at this here: https://github.com/kubernetes/kubernetes/pull/45682

**Comment by DreadPirateShawn** [comment]
/remove-lifecycle stale

Hoping for a clearer update on path forward. I've commented on pull request #45682 as well, pinging for update.

**Comment by DreadPirateShawn** [comment]
/remove-lifecycle stale

Pull request #45682 has since been abandoned -- does that mean:
* this issue should be revisited with a new solution?
* this issue is "will not fix"?
* this issue has been fixed in newer versions?

(I think those are the three options...)

Thanks.

**Comment by queimadus** [comment]
/remove-lifecycle stale

I'd find this improvement useful as well. It's hard to create a dashboard (and possibly alerts) when a pod crashes otherwise.

I was trying to solve this by storing the `kubectl get events --watch` and operating over them but although we get a `reason: Backoff` when the pod crashes a second time, I still can pinpoint the error reason without calling `kubectl describe pod _` and checking the last state reason.

**Comment by glasser** [comment]
An event for when a pod becomes Ready for the first time would be pretty great.

**Comment by hokiegeek2** [comment]
Hi Everyone,

I vote for this. My use case is that, when using Argo, the pods never get cleaned up when the workflows end. I would like the Pod Terminated hook so either the Argo team can add this functionality or I can create a Zamboni service. I can do polling for this, obviously, but responding to the k8s event stream would be way cooler.

**Comment by mmlac** [comment]
/remove-lifecycle stale

There still seem to be questions around what should be reported in the events?
If there is not other issues regarding what should be sent out as an event, I suggest this is left open.

**Comment by rendhalver** [comment]
What's the status on this?
I have been doing some testing to see where OOMKilled messages show up.
From what I can tell they only show up in the Pod's status message and don't get included in the namespace events.
Can we add that to the list of events that should exist?
I am happy to report my findings here or open a new issue.

**Comment by nomcopter** [comment]
Without this I cannot setup alerts for when arbitrary pods crash. I definitely want those alerts.

**Comment by boosty** [comment]
My team uses a custom controller to publish OOM events: 
https://github.com/xing/kubernetes-oom-event-generator

It works by listening to Pod change events, checks the status of every container and searches for those claiming they were OOMKilled previously. 

The same idea could be applied to look for other previous states, but OOM was the most important for us to tackle.

That being said, I would prefer if these container events were provided by K8s itself.

**Comment by hokiegeek2** [comment]
@boosty cool, thanks for providing the link! That is definitely along the lines of what I am interested in. Agreed, I'd like to see this general capability baked into k8s.

**Comment by rendhalver** [comment]
That looks handy @boosty! Thanks!

**Comment by iggyzap** [comment]
/remove-lifecycle stale

This is very interesting issue for being able to reason about pod lifecyle.

**Comment by hokiegeek2** [comment]
This issue should not be designated stale, so thank you @iggyzap for helping to un-stale it . ![bitmoji](https://render.bitstrips.com/v2/cpanel/cf7648af-2035-4e07-9237-89aa82985b3c-cebe575f-fd79-4052-b084-1f812012fcdf-v1.png?transparent=1&palette=1&width=246)

**Comment by hokiegeek2** [comment]
I vote to keep this open--any new word on this feature request?

**Comment by mmlac** [comment]
/remove-lifecycle stale

Bot not catching the command?

**Comment by pikeas** [comment]
Just bit by this. Other than the restart counter incrementing, it is very non-obvious when a pod hits a memory limit. Kubernetes knows when a container is OOM killed, this should be surfaced as an event rather than buried in `describe`.

**Comment by rcny** [comment]
Is it possible to get events for a pod when it becomes ready or not ready? Liveness probe has it's `Killing` event in case of reaching probe's `failureThreshold`, but what about readiness probe?

**Comment by pacoxu** [comment]
Just brainstorming about this. Some users need more events but some are suffered from too many events(I think this is one of the reasons the event is not added.). The event has a limit of 10k size, and some period events will make great pressure on etcd.
I wondered if we should add a flag like `--event-level warning/info/debug` and add some new events as debug level to move this forward.

oom-event-generator is a quick solution: https://github.com/kubernetes/kubernetes/issues/38532#issuecomment-474780574.

**Comment by hokiegeek2** [comment]
@pacoxu excellent ideas! 👍
