### ISSUE TITLE
Bots are opening too many issues, too noisy, and often just wrong

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#38543]
As part of 1.6 planning for both the scalability and scheduling sig I've spent a fair amount of time this week tracing through issues.  I was struct by just the sheer # of issues opened by bots!!! It's such a ridiculously high number that I don't think anyone is paying attention, step 1: "filter-ignore the bot".  

IMO I think we need an all out testing blitzkrieg on testing similar to 1.2 but for 1.6, but I also think the way the bots are reporting is untenable.  Aggregating history and statistics is far more useful imo, for each test we could aggregate stats over the last day/week/month/year to determine relative priority.  

Issues should only be opened if they are a statistical significance and should re-trigger a test based on recent statistics.     

/cc @kubernetes/sig-contributor-experience @eparis @bgrant0607 @kubernetes/sig-testing

**Comment by bgrant0607** [comment]
cc @fejta

**Comment by eparis** [comment]
I'll be honest I haven't given it much thought, but my knee jerk reaction is "not reporting the issue doesn't make the issue go away".

Less spammy bots would be good.
Bet way to tell how important and issue is would be good.
Automatically closing old low priority issues would be good.
"Filing less issues" doesn't solve anything...

**Comment by timothysc** [comment]
I think aggregating statistical significance and filing at threshold is a worth the effort at this point.  So I actually want to collect more data, but file less, to perform analytics on it.  Using the ETL'd-stats we could also auto-close issues after threshold has gone down.  

Of the newer form of output the bots have filed >1000 issues in recent history, since May, with ~450 still open today.  I'd have to do some more archeology to get better data, but it's crystal clear the brute force approach will only further amass cruft. 

Right now we have several project scaling problems, and Brian asked me to write down some of my thoughts after my triage haul.  I think mining results, and making are bots smarter, will help to both decrease our issue count, but also increase our PR & review throughput.

**Comment by hjacobs** [comment]
My 2 cents: all the bot issues are really annoying for "outsiders" like myself --- I now tend to always use "NOT e2e" in the GitHub issue search. There are a lot of human issues not looked at (overlooked?) or at least without any reaction/comment (some can also be closed, like #38355). Would be great to give human-reported issues more visibility and have faster/better feedback for them.

**Comment by spxtr** [comment]
> I'll be honest I haven't given it much thought, but my knee jerk reaction is "not reporting the issue doesn't make the issue go away".

:+1:

Recently we've added approximately ten thousand [non-queue-blocking builds](http://submit-queue.k8s.io/#/e2e) which has made it that much noisier. Suite failures get assigned to just a few people, which leads to [this mess](https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=is%3Aissue%20assignee%3Aspxtr%20label%3Akind%2Fflake%20). https://github.com/kubernetes/test-infra/issues/1317 is related to that.

**Comment by fejta** [comment]
/assign @cjwagner 

We revamped this here, the noise ratio is much better now.

**Comment by timothysc** [comment]
Sweet thanks @fejta !
