### ISSUE TITLE
PV/PVC can be deleted even if it was used by a POD

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#38553]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:
The PVC/PV should not be allowed to delete.

**How to reproduce it** (as minimally and precisely as possible):
1) Create a PV and PVC
2) Create a deployment using the PVC created by 1)
3) Once the deployment is running, delete the PVC.
4) Delete PVC succeed.

**Anything else do we need to know**:

**Comment by kargakis** [comment]
@kubernetes/sig-storage @kubernetes/rh-storage

**Comment by thockin** [comment]
We've mentioned finalizers being an option for this, but I am wary of
abusing that to simulate proper referential integrity.

**Comment by gyliu513** [comment]
Thanks @thockin , so you mean there are options can enable me to not delete pv/pvc if they are used?

**Comment by thockin** [comment]
Finalizers are a very new but generic mechanism to inhibit deletion of
objects.

**Comment by gyliu513** [comment]
@thockin  Can you please show me a link for this?

**Comment by thockin** [comment]
I am on mobile now - search recent pull requests for "finalizers".  :)

On Dec 11, 2016 6:06 PM, "Guangya Liu" <notifications@github.com> wrote:

@thockin <https://github.com/thockin> Can you please show me a link for
this?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/38553#issuecomment-266327878>,
or mute the thread

**Comment by gyliu513** [comment]
Thanks @thockin , i got some links for finalizer, will go through those for detail. I will close this one now ;-)
