### ISSUE TITLE
Issue of the documentation of ubuntu not found

### ISSUE THREAD

**Issue by noahzaozao** [kubernetes/kubernetes#38562]
At github page https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md

Mentioned one page: http://kubernetes.github.io/docs/getting-started-guides/ubuntu/

The above link was not found (see attached screenshot)

![image003](https://cloud.githubusercontent.com/assets/1780032/21073648/773c5d28-bf1f-11e6-9895-f1174bd05864.png)

**Comment by hjacobs** [comment]
Duplicate of #38506

**Comment by hjacobs** [comment]
Will be fixed by #38546

**Comment by noahzaozao** [comment]
@hjacobs Thanks , both are helpful.

http://kubernetes.io/docs/getting-started-guides/ubuntu/automated/
http://kubernetes.io/docs/getting-started-guides/ubuntu/manual/
