### ISSUE TITLE
Node stops accepting requests and has event error but is still in pool as "Ready"

### ISSUE THREAD

**Issue by montanaflynn** [kubernetes/kubernetes#38568]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

node, timeout, restart

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:13:23Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:16:27Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: https://cloud.google.com/container-engine/
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

Requests started to timeout every so often, we found this from runscope monitoring. When I reproduced the timeout it was only intermittent. All the k8 deployments and pods were online. 

I looked in `kubectl get events` and saw:

```
44m        44m         1         gke-backend-default-pool-a671890f-17dj   Node                                        Normal    NodeNotReady              {controllermanager }                                  Node gke-backend-default-pool-a671890f-17dj status is now: NodeNotReady
```

When I ran `kubectl get nodes` it was in `Ready` status:

```
$ kubectl get nodes
NAME                                     STATUS    AGE
gke-backend-default-pool-a671890f-17dj   Ready     7d
gke-backend-default-pool-a671890f-berw   Ready     7d
gke-backend-default-pool-a671890f-h0li   Ready     7d
gke-backend-default-pool-a671890f-oqjm   Ready     7d
gke-backend-default-pool-a671890f-pu28   Ready     7d
gke-backend-default-pool-a671890f-r14r   Ready     7d
gke-backend-default-pool-a671890f-sga0   Ready     7d
gke-backend-default-pool-a671890f-uxby   Ready     7d
```

I then manually deleted the node:

```
kubectl delete node gke-backend-default-pool-a671890f-17dj 
```

And the timeouts went away. We had the same problem last week but at that time I just removed all the nodes because I didn't have time to dig into the issue.

**What you expected to happen**:

When the node goes into `NodeNotReady` it should remove itself from the pool and have another one take it's place. Also `kubectl get events` says the node went into `NodeNotReady` but `kubectl get nodes` showed it as `Ready`, maybe it went back to `Ready` status but for some reason wasn't accepting http request to the exposed service IP.

**How to reproduce it** (as minimally and precisely as possible):

We weren't touching the cluster when the node stopped accepting requests, it was working for a week and then stopped at a seemingly random time.

**Anything else do we need to know**:

Not that I can think of, but let me know if there's any other information I can provide, unfortunatly the problem node has been deleted already but if it happens again I could run some commands to help diagnose the issue.

**Comment by Random-Liu** [comment]
Could you give us the kubelet log on the `NotReady` node once it happened again?

**Comment by montanaflynn** [comment]
Sure, what commands would I run to get that? 

Also the node never was shown as NotReady when running `kubectl get nodes`, it was listed as `Ready` although there was an event that said `status is now: NodeNotReady`.

**Comment by grodrigues3** [comment]
ping @Random-Liu can you help out when you get a chance?

**Comment by dchen1107** [comment]
I am closing the issue since it is obsolete for sure. Normally when node is reported NotReady due to the following reasons:

1) runtime (i.e. docker) is in crashloop, and cannot self-recovered by the node. Kubelet will report NodeNotReady with runtime is down as the reason
2) kubelet itself cannot run at all or there is a network partition between master and node, thus kubelet failed to report its status. After some time (configurable, default: 45s), node controller will reports NodeNotReady with the reason of not receiving status from kubelet.
3) In old releases if you are on GKE, or some other vendors, Node hadn't switch to use kubenet. Kubelet might end up to config cbr0 for docker, it might have network bridge is not ready. But in most case today, we shouldn't run into this issue. 

If next time when we run into the issue, please 
1) run the command: kubectl describe node <not-ready-node-name> 
2) attach the kubelet log. Thanks.
