### ISSUE TITLE
federation e2es failing with v1.GetOptions is not suitable for converting to "federation/v1beta1"

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#38585]
All our federation e2es started failing with `v1.GetOptions is not suitable for converting to "federation/v1beta1"`. Not sure if something changed in API machinery.

cc @kubernetes/sig-api-machinery @caesarxuchao @smarterclayton @kubernetes/sig-cluster-lifecycle

**Comment by liggitt** [comment]
Is GetOptions missing from https://github.com/kubernetes/kubernetes/blob/master/federation/apis/federation/v1beta1/register.go#L42 ?

**Comment by liggitt** [comment]
Looks like a similar commit to https://github.com/kubernetes/kubernetes/pull/38371/commits/5ce687729d703ab7e94fe41d736d004f8b0d032c is needed

Cc @wojtek-t

**Comment by nikhiljindal** [comment]
Thanks for the prompt reply with all those links @liggitt. You are amazing!
Sent https://github.com/kubernetes/kubernetes/pull/38587

**Comment by smarterclayton** [comment]
Are the federation e2e's not PR blocking?

**Comment by nikhiljindal** [comment]
No. We need to reduce their running time before making them PR blocking.

**Comment by nikhiljindal** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/38571
