### ISSUE TITLE
Container downward/upward API umbrella issue

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#386]
We need to start establishing the "downward API", starting with enough context that a container can find out more information about itself.

I think that minimal info is:
K8S_APISERVER = host:port of apiserver
K8S_POD_ID
K8S_CONTAINER_NAME

**Comment by bgrant0607** [comment]
Resolving env. var. values is being discussed in #560.

Note: VIPs are typically bound to loopback aliases:
http://stackoverflow.com/questions/13110378/how-does-the-vip-loopback-aliase-work

**Comment by pmorie** [comment]
We did some discussion on this topic starting around here: https://github.com/GoogleCloudPlatform/kubernetes/issues/2316#issuecomment-86202868

**Comment by bgrant0607** [comment]
Rancher's metadata service: http://rancher.com/introducing-rancher-metadata-service-for-docker/

**Comment by thockin** [comment]
I propose we close this umbrella bug and open new issues for specific points remaining.

**Comment by maicohjf** [comment]
> As much as I want to keep this simple, Clayton's argument of using a non
> k8s native image in k8s by application of clever env vars is compelling.
> 
> But what scope? Env vars only? Env vars and command lines?
> On Jul 9, 2014 5:08 PM, "Clayton Coleman" [notifications@github.com](mailto:notifications@github.com) wrote:
> 
> > That's true, although one strong goal in docker has been to try and offer
> > via libchan/libswarm a "Docker" abstraction where on multiple platforms
> > images can invoke consistent actions that affect the platform. That applies
> > to more generic operations, whereas k8s specific actions will always
> > require some downwards API. The abstraction is a long term play that
> > requires active participation by a number of stakeholders and also
> > implemented, demonstrated use cases, so it's not an argument for avoiding
> > trying.
> > I don't think the downward API is bad, but some of the use cases (unique
> > id for an instance, what ip do I have) might benefit from looser coupling
> > or by trying to find the most lowest common denominator expression. In the
> > end image authors can always ignore those settings, but you do want image
> > users to have the tools to bend a recaltricant image to their will.
> > 
> > Reply to this email directly or view it on GitHub
> > [#386 (comment)](https://github.com/kubernetes/kubernetes/issues/386#issuecomment-48551080)
> > .

17. 
Create a deployment as follows
 Name: nginx-dns
 Exposed via a service: nginx-dns
 Ensure that the service & pod are accessible via their respective DNS records
 The container(s) within any Pod(s) running as a part of this deployment should use the nginx
image
Next, use the utility nslookup to look up the DNS records of the service & pod and write the
output to /opt/..../service.dns and /opt/..../pod.dns respectively. Ensure you use the
busybox:1.28 image (or earlier) for any testing, an the latest release has an unpstream bug which
impacts the use of nslookup.

😊
kubectl run nginx-dns --image=nginx
kubectl expose deployment/nginx-dns --port=80 --name=nginx-dns
kubectl run busybox -it --rm --image=busybox:1.28 sh
nslookup nginx-dns #svc 记录
nslookup pod-ip-addr #pod 记录
Nslookup 的结果不能直接输出到文件，我是粘贴到notepad 上再用
