### ISSUE TITLE
[Rate Limiter] Introduce a max wait duration for kubernetes rest client?

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#38602]
Recently, I find kubelet fail to report its heartbeat due to blocked by rate limiter. It seems strange as rate limiter for kubelet in my environment is {qps=20, burst=30}. After digging deeper, I find node's local time has been changed by some reasons. 

Thus every time kubelet attempts to report its heartbeat, it will call juju ratelimit.Wait(1), 
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/flowcontrol/throttle.go#L72

juju ratelimit very depends on local machine's time. Currently, kubernetes rest client use `func (tb *Bucket) Wait(count int64)`, which will **keep waiting until tokens are available**.

https://github.com/juju/ratelimit#func-bucket-wait

If local time changes unexpectedly, kubernetes rest client may wait for a very long time, such as some hours.

Since juju ratelimit support a new kind wait - `func (tb *Bucket) WaitMaxDuration(count int64, maxWait time.Duration) bool`

https://github.com/juju/ratelimit#func-bucket-waitmaxduration

What about use it?

```
// As QPS is always a positive integer(>=1), a normal wait duration should be <=1s.
const MaxWaitDuration = 2 * time.Second

// Accept will block until a token becomes available or a MaxWaitDuration timeout
func (t *tokenBucketRateLimiter) Accept() {
	// Try to fix local clock misconfiguration
	// Kubernetes client side wait at most MaxWaitDuration for per rest request
	wait := t.limiter.WaitMaxDuration(1, MaxWaitDuration)
	if !wait {
		glog.Warningf("Won't wait for greater than max wait duration %v", MaxWaitDuration)
	}
}
```

@justinsb @liggitt

**Comment by liggitt** [comment]
gross time differences in the kubelet are likely to cause other issues, like the node status lastHeartbeatTime being very wrong. I don't think I would make this change just for this use case. I also have https://github.com/kubernetes/kubernetes/pull/38320 in progress to switch away from juju/ratelimit, so I'd rather not increase the API surface area we're using there

**Comment by m1093782566** [comment]
@liggitt 

I like the idea :)

I think I can close this issue now.
