### ISSUE TITLE
Idea: Support delegation of volume handling to a container process

### ISSUE THREAD

**Issue by fabiand** [kubernetes/kubernetes#38606]
Currently Volumes and Persistent Volumes / Claims are nicely integrated into Kubernetes to provide file-system based storage to pods. It does so by letting the kubelet do the heavy lifting of attaching the underlying raw devices to the host (if necessary), the mount the device, and finally make it available to the pod.

This is a pretty good solution for most scenarios. But in some cases it would be useful if the final volume handling on the host side could be delegated to the pod itself.
This is required if

1. a pod process requires raw access to the device (if a device is involved) or
2. if the process can directly consume the volume (i.e. ceph could be directly used by processes)

A naive idea would be to add the ability to pass a volume _by reference_. Thus instead of letting the kubelet mount the volume, a reference in form of an URI would be passed to the pod, and the pod itself could then do the relevant handling (i.e. using the raw device or offload the consumption to a process).
The signaling if a reference - or delegation to the pod - shall be used, could be done through a simple per volume flag.

A benefit is that the complete infrastructure and concepts around (persistent) volume in kubernetes could be reused, i.e. the consumption of volumes in pod specs, or PVCs.

Note: Today this could probably be achieved by using a `FlexVolume`.

**Kubernetes version** (use `kubectl version`):
Today's version

**Comment by fabiand** [comment]
Likely.
Let me note that I'm seeing the main focus of the volume delegation on the consumption side.
But as we'd be granting raw access to the device, this would also permit that this mechanism could be abused to i.e. create volumes, which overlaps with dynamic provisioning. But this is just an edge case.

Just a few more examples of for this feature:

- check disk jobs - which could perform some low level (file-system) analysis (fsck!)
- raw data access - I.e. for a [database](http://dev.mysql.com/doc/refman/5.7/en/innodb-raw-devices.html) or other [processes](http://docs.ceph.com/docs/giant/rbd/qemu-rbd/)

**Comment by smarterclayton** [comment]
This is a specific instance of #831

**Comment by smarterclayton** [comment]
@kubernetes/sig-storage

**Comment by gnufied** [comment]
Wondering how error handling will work? Currently if a misbehaving pod crashes, the volume is cleaned up by kubelet and depending on recycling policy etc - it can be reused by another pod. 

So if a container that is using a raw device crashes - how will kubelet clean up?

**Comment by fabiand** [comment]
@gnufied good point.
Maybe a pod specific _finalizer_ could help here - which could run the specific code to do the cleanup.
Ah - Thinking about it it's not realy safe. It covers some bits, but it ain't safe.

Let's try to tear the problem apart.
If the volume was directly used by the process i.e. through a user-space library (like it can be done with rbd), then no cleanup is necessary as long as the process goes down. And we also don't take care about the actually involved data, because this is application specific.

If the volume is somehow consumed involving the host, then it's a little more complicated. In that case we need to take care of

a) an eventually attached device
b) an eventually created mount

b) is easier to catch - because the kubelet can see the mounts of a pod. Maybe just unmounting all mounts is enough - we still need to do error handling tho.
a) is trickier to solve, because the container could - if it's a privileged - have attached a device to the host, but this device is not directly related to the pod. So we'd need a mechanism to track or register consumed devices.

Another take on a) could be that we leave it to the application dealing with the volumes to have a cleanup mechanism, maybe in a separate pod/job.

@smarterclayton let me read the complete other issue.

**Comment by thockin** [comment]
NB that while raw access to block devices is interesting, being able to
MOUNT them requires a very high level of trust.  It is pretty trivial to
crash the kernel.

**Comment by fabiand** [comment]
@smarterclayton I do see a difference between this issue and #831.

The difference I'm seeing is that #831 is about using a container (not sure if running or not) as a volume. If the container is running, then the functionality to this issue is similar.

But: One aspect of this issue is, that this mechanism described here would only cover the existing volume types - whereas the container (if it's running) approach would allow arbitrary sources to be used.

Thus let me highlight - In this approach here, we'd use the volumes and persistent volumes etc as intended, with the only configurable difference, that we'd set a `delegate: True` (or something like this) flag in the pod volume spec.

**Comment by fabiand** [comment]
@thockin that's true.
But mounting is only possible by privileged/sufficient cap containers, thus there would be already a level of trust because the container already has privileges and/or additional capabilities.

If it's not privileged, then a process can still consume the volume directly.

**Comment by fabiand** [comment]
@saad-ali @childsb thoughts?

**Comment by thockin** [comment]
This is sort of languishing.  I still think raw block access is an
interesting and worthwhile feature, but I don't think this is the right way
to get it.

**Comment by fabiand** [comment]
Right. Let me note that it's not only about raw block storage, but also about the ability to delegate connections to user-space, i.e. ceph can be directly consumed by using librbd from user-space without a syscall roundtrip. This case would also be covered by such a delegation mechanism.

@thockin do you have a different solution approach in mind?

**Comment by thockin** [comment]
@vishh for comprehensive coverage.  I do not have an answer for raw block
devices yet, but I don't think we've really tried to solve *just* that.

**Comment by fabiand** [comment]
I've been giving it some more thoughts.

First, I'd like to differentiate between 
1. raw block storage
2. delegation of the storage handling

Let's go into 1.

Raw block storage is probably a cluster resource which requires different permissions than usual volumes, the best way to achieve this - considering the current designs - is to create a separate resource i.e. RawVolume for it, which hen fit's into the RBAC model.
Having a separate resource for raw block storage also has the benefits that it would only have support for plugins which are offering raw block devices.
It looks like the low-level functionality to attach and detach the block devices can probably be shared with the volume plugins.

However, the delegation is still interesting - for both cases Volume and RawVolume - in order to allow a process inside the container to directly access the referenced volume.

**Comment by fabiand** [comment]
ping

**Comment by msau42** [comment]
Raw block support in kubernetes is alpha in 1.9.  @fabiand do you have remaining use cases that are not covered by the raw block feature?

**Comment by fabiand** [comment]
Raw block storage is great, and we are able to work with it.

However, for performance reason we know that for certain transports (iscsi, ceph, and (iirc) gluster) we can actually delegate the volume attachment to the (qemu) process. This yields to better performance in some scenarios. OTOH attaching a volume directly to qemu also has drawbacks (limited multipath i.e.).

However, in general with KubeVirt we can imagine two basic approachs in fufure: storage via kubelet (fs+raw), storage via qemu (limited-fs+raw), and this is issue is to enable the latter case.

However, this obviously makes the assumption that the pod can connect to the storage network - which is a different issue.

I also know that virtlet (iirc @pigmej) was looking for such a feature, maybe @MikeSpreitzer as well, and maybe @sameo as well.

**Comment by msau42** [comment]
Could this be covered by writing your own flex or csi driver?

**Comment by fabiand** [comment]
I think so - I even think that virtlet is doing it that way.
But we'd loose the nice clarity in the API - aka we loose validation of the fields defined for the existing plugins.
A general mechanism, applying to all plugins might be a more structural approach.

**Comment by msau42** [comment]
The long term plan is to have most plugins go through CSI, even in-tree ones, so eventually almost all plugins will be containerized.  Based on that, I'm unsure of the need to have a "container delegation" flag in the API.

**Comment by msau42** [comment]
I think this idea of delegation has come up a few times in the context of secure runtimes.  In those cases, it could make sense to give the block device to CRI and have the runtime manage the final haul of the filesystem. See https://github.com/kubernetes/kubernetes/issues/62238

**Comment by fabiand** [comment]
I think this ticket is going even one step beyodn this.

Even for secure runtimes it can make sense to directly connect to the storage, and not let the kubelet do this.

BTW - I wonder that #62238 is an issue :)

**Comment by msau42** [comment]
Do you mean something like running the CSI driver in the runtime?  Can you give an example?

**Comment by fabiand** [comment]
Delivering a CSI driver using a pod for example would requrie this feature. The driver would get the connection details and would establish the connection.

For KubeVirt we'd pass the credentials to qemu and let qemu connect to the storage.

**Comment by j-griffith** [comment]
I believe this might be achievable using a specific CSI node-server for publish/unpublish.  There would be some plumbing to figure out here, but I think if you ran the node-server in the same Pod as the KVM service you could in fact have the publish function provide the information to KVM rather than have it actually perform the connection (and formatting).

I'm not completely sure about permissions issues here, the design of a separate node-server in the CSI spec would require this sort of thing as it stands (although TMK that's not something that's been implemented anywhere yet).

The one thing I haven't sorted out in my mind yet is dealing with multiple instances of these node-servers on a node (the idea was that it would be just a single node-server handling all publish requests for that node).  The other thing that I'm trying to think through is what this means in terms of a CSI driver?  Obviously we'd want to work with any CSI driver; but it gets interesting if we want to have generic publish/unpublish implementations on a node based on the Pods that are deployed there and the placement of the service that's consuming the CSI driver.

I might try and flush this out a bit, but I'd be curious if others familiar with CSI see this as viable?

**Comment by fabiand** [comment]
The remaining core issue is that this proposal would leak the storage connection informations to the pod - which is a risk.

**Comment by vitalif** [comment]
Hi, why is this issue closed? ALL qemu-based hypervisors support direct volume attachment, kubevirt is the only lacking. This definitely has to be implemented somehow
