### ISSUE TITLE
use `kubernetes-discovery` as API proxy in GCE

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#38628]
`kubernetes-discovery` is the API registration proxy described here: https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/federated-api-servers.md .  It is designed to run inside of a pod with an ingress pointed to it.  

I have created `hack/local-up-discovery.sh` which demonstrates how to launch the pod with the required certs and API server wiring to act as a proxy for the the core API server.  `kubernetes-discovery` should be seamless to clients, so all we *should* have to do is bootstrap the `kube-public` namespace with the correct pod and then point the kubeconfig file used to launch the e2e test with `kubernetes-discovery` ingress.

We need to ensure that RBAC can work properly throughout the cluster as all API servers start delegating to it for our extension API server use-cases.

**Comment by deads2k** [comment]
@mikedanese cj thought you could help me find someone who knew how to create the image that I need.  We have a `local-up-discovery` script that shows roughly what I'd like to do.  This line does a docker build: https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-discovery.sh#L85

**Comment by lavalamp** [comment]
I don't think this makes sense now that we are combining?
