### ISSUE TITLE
Document dependencies version in the release notes

### ISSUE THREAD

**Issue by scheeles** [kubernetes/kubernetes#38632]
With each release it is hard, to figure out which are the supported docker, rkt and etcd version which are supported. 

Can this be added to the release note or to a separate document.

**Comment by calebamiles** [comment]
Hello @scheeles, I've added a brief section to the 1.5 release notes about what versions of external dependencies were used by the [Continuous Integration environment](https://github.com/kubernetes/features/pull/157) moving forward we'll hopefully be able to add links to an easy to understand testing dashboard. If you'd like to help build that out I'm sure the people in SIG Testing would love some help. Please close this issue if you believe your question has been addressed. Thanks!

**Comment by scheeles** [comment]
Thanks
