### ISSUE TITLE
Deprecating Swagger 1.2 in favor of OpenAPI (Move all internal tools to use OpenAPI)

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes#38637]
We plan to remove swagger 1.2 support in kubernetes 1.9 in favor of our [OpenAPI spec](https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json). Please check [OpenAPI specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) for more information. This [migration guide](https://github.com/OAI/OpenAPI-Specification/wiki/swagger-1.2-to-2.0-migration-guide) is also helpful in regard to comparing two specs and how to navigate between them.

Before deprecating swagger 1.2, we need to move all of k8s components to use OpenAPI. This is the list of components need updating:

- [x] kubectl [#44589, #5889, #39434]

[probably related issues](https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20kubectl%20swagger)

Related:

- [x] Update documentation after 1.2 deprecation, here https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/concepts/overview/kubernetes-api.md
- [ ] Add a README file [here](https://github.com/kubernetes/kubernetes/tree/master/api/swagger-spec) to highlight the deprecation for the spec.
- [ ] Add deprecation release note to 1.8

**Comment by GlenDC** [comment]
When you say "OpenAPI spec", do you mean the "Swagger 2.0" spec?

**Comment by mbohlool** [comment]
Swagger 2.0 spec is donated to OpenAPI. Thus they are the same. We try to call it OpenAPI everywhere to be consistent and also to show intention of supporting later versions of OpenAPI spec (that may or may not be called swagger 2+.0+)

**Comment by nikhiljindal** [comment]
swagger-ui has been deprecated in favor of API ref docs: https://github.com/kubernetes/kubernetes/issues/15915 so you can ignore it

**Comment by mbohlool** [comment]
Thanks @nikhiljindal I've updated first comment with a list of components that need updating. There is only one item there now. Please add or suggest more if you know any components that uses our swagger 1.2 spec.

**Comment by smarterclayton** [comment]
We should stop doing client side validation in general, which is issue #39434

**Comment by mbohlool** [comment]
@smarterclayton I completely agree. @pwittrock What is the plan for client side validation in kubectl? Is this a Q2 thing? If not, should we migrate kubectl to use OpenAPI instead of old swagger?

**Comment by pwittrock** [comment]
AFAIK, there are no Q2 plans for this.  The MVP suggested in #39434 is to use the swagger on the server side, which I expect you would also want to use OpenApi for.

We want to get the merge key tags out of open api in Q2, so we may be able to take a pass at the validation at the same time.

**Comment by mbohlool** [comment]
This is the latest plan for deprecation:

1. Announce deprecation with 1.7 release
2. Kubectl will migrate to OpenAPI in 1.8
3. Adding a "Deprecated(#38637) - " prefix to old swagger documentations in 1.8.
4. Remove old swagger in 1.9.

**Comment by spiffxp** [comment]
/sig api-machinery
because swagger->openapi
/sig cli
since kubectl is involved

**Comment by apelisse** [comment]
Swagger is still used in `kubectl explain` (i.e. [explain.go](https://github.com/kubernetes/kubernetes/blob/v1.8.0-beta.1/pkg/kubectl/explain.go)), it's reasonable to get it removed entirely before 1.9.

**Comment by mbohlool** [comment]
Thanks @apelisse. To be clear, that will push our timeline for deprecating swagger 1.2 one release (the plan is now to remove it in 1.10 now)

**Comment by mbohlool** [comment]
Kubectl 1.8 is the latest version that uses swagger 1.2 spec. That means we can remove swagger 1.2 from head and hence it will not be available in 1.10. I will announce the deprecation with 1.9.3 release.

**Comment by apelisse** [comment]
@mbohlool Have we removed swagger 1.2 from head/1.10?

**Comment by mbohlool** [comment]
It is on my TODO list

**Comment by mbohlool** [comment]
According to https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-feature-or-behavior
we need to wait 1 year before deprecating a feature. Kubernetes 1.8 was the last version using swagger 1.2 and kubernetes 1.12 marks the one year waiting period. This can be now removed from 1.13.

**Comment by nikopen** [comment]
can be moved to next release

/milestone v1.14

**Comment by liggitt** [comment]
PR open in https://github.com/kubernetes/kubernetes/pull/72924
