### ISSUE TITLE
Deprecate Exec Network Plugin

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#38639]
Is anyone still using the [exec network plugin](http://kubernetes.io/docs/admin/network-plugins/#exec)? We want to deprecate it in 1.6. 

@kubernetes/sig-network @kubernetes/sig-node

**Comment by feiskyer** [comment]
Also forward one to [mailist](https://groups.google.com/forum/#!topic/kubernetes-sig-network/ptDaRCcDLDA)

**Comment by thockin** [comment]
I think this would be great.  We're working on a place to store such
deprecation announcements.

**Comment by lxpollitt** [comment]
+1
