### ISSUE TITLE
Service type loadBalancer (AWS cloudprovider) only supports 0.0.0.0/0 for loadBalancerSourceRanges field

### ISSUE THREAD

**Issue by dhawal55** [kubernetes/kubernetes#38633]
**Kubernetes version** (use `kubectl version`):
v1.4.6

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS v1235.2.0
- **Kernel** (e.g. `uname -a`):
4.8.6-coreos-r1 #1 SMP Wed Dec 7 00:29:42 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux

**What happened**:
When creating a service-type loadBalancer, adding `service.beta.kubernetes.io/aws-load-balancer-internal` creates an internal ELB, but the only allowed value for `loadBalancerSourceRanges` is 0.0.0.0/0. This limitation prevents you from specifying custom CIDR range for your hybrid cloud (Direct Connect to private data center)

**What you expected to happen**:
The limitation is unnecessary. Even in an AWS only scenario (no hybrid cloud), it makes sense to allow a CIDR range for a subnet where your calling services are deployed.

**How to reproduce it** (as minimally and precisely as possible):
Create a service-type loadBalancer and set loadBalancerSourceRanges to a value other than 0.0.0.0/0

**Comment by freehan** [comment]
@justinsb

**Comment by dhawal55** [comment]
Any update on this? Also, is anyone working on adding support for securityGroup?

**Comment by awebneck** [comment]
@justinsb any progress on this? I also really would like to have this flexibility in place for integrating k8s into an existing VPC.

**Comment by altairpearl** [comment]
Any update on this?
