### ISSUE TITLE
Scary misleading information during a describe after an apply

### ISSUE THREAD

**Issue by razic** [kubernetes/kubernetes#38644]
#### kubernetes version info

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:45:16Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:43:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

#### client environment

* 14.04.5 LTS, Trusty Tahr
* Linux 6b327be4fdfc 4.4.27-moby #1 SMP Wed Oct 26 14:21:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

#### what happened

* added an additional port to a kubernetes service resource manifest.
* ran apply on the manifest file to update the service with additional port
* ran describe on the service only to see `Creating LoadBalancer` last seen 2 min ago.

```
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------   --------        ------                  -------
  2h            3m              2       {service-controller }                   Normal          CreatingLoadBalancer    Creating load balancer
  2h            3m              2       {service-controller }                   Normal          CreatedLoadBalancer     Created load balancer

```

#### expected

don't tell me you recreated a load balancer if you didnt? :)

**Comment by razic** [comment]
cc @justinsb

**Comment by justinsb** [comment]
I think this is just a matter of misleading event text.

At least the Message can be fixed easily.  I am less sure on the Reason (is this an API change @bgrant0607 ?), but I think we fix it and add a release note.

**Comment by bgrant0607** [comment]
@justinsb Events aren't currently covered by API contract, and both Reason and Message can be changed. However, if there are e2e tests that rely on the existing events, the fixes may need to be backported to prior release branches.

**Comment by razic** [comment]
@bgrant0607 i may try to take a stab at fixing this. if there are indeed e2e tests relying on existing events, how many prior releases do you address?

**Comment by bgrant0607** [comment]
@razic It appears that no tests depend upon the text, but could you please verify that?

**Comment by bgrant0607** [comment]
But to answer the question, we'd need to fix tests for 2 prior releases.
