### ISSUE TITLE
AWS-Kubeadm install, kube-dns is stuck at containerCreating. 

### ISSUE THREAD

**Issue by smenon78** [kubernetes/kubernetes#38653]
Following the document to Install Kubernetes on AWS
http://kubernetes.io/docs/getting-started-guides/kubeadm/

kube-dns is stuck in ContainerCreating....

**Kubernetes version** (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", 

**Environment**:
- **Cloud provider 
AWS
- **OS** (e.g. from /etc/os-release):
Linux ip-10-43-144-27 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

It was working last week, suddenly, I am having problems with kube-dns coming up
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type            Reason          Message
  ---------     --------        -----   ----                            -------------   --------        ------          -------
  9m            9m              1       {default-scheduler }                            Normal          Scheduled       Successfully assigned kube-dns-654381707-k98vh to ip-10-43-144-27
  9m            0s              532     {kubelet ip-10-43-144-27}                       Warning         FailedSync      Error syncing pod, skipping: failed to "SetupNetwork" for "kube-dns-654381707-k98vh_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kube-dns-654381707-k98vh_kube-system(0d75d8bc-c0ba-11e6-9884-028a08ffbd39)\" using network plugins \"cni\": cni config unintialized; Skipping pod"

*

**Comment by dchen1107** [comment]
cc/ @freehan on network plugin related issue.

**Comment by freehan** [comment]
```
using network plugins "cni": cni config unintialized; Skipping pod"
```

Looks like you are using "--network-plugin=cni". This indicates your cni network config is not loaded. cni network plugin is expecting user to provide the CNI config and binaries at `cni-conf-dir` and `cni-bin-dir`. 

More docs can be found here: http://kubernetes.io/docs/admin/network-plugins/#cni

**Comment by smenon78** [comment]
I didn't have to do anything manually before based on the doc 
http://kubernetes.io/docs/getting-started-guides/kubeadm/
I did run this command
apt-get install -y kubelet kubeadm kubectl kubernetes-cni

**Comment by freehan** [comment]
Looks like somewhere breaks during bootstrap? The CNI conf is not in place. Could you check if there is anything in `/etc/cni/net.d`?

**Comment by freehan** [comment]
add @mikedanese

**Comment by smenon78** [comment]
There is no cni directory in the /etc folder. I have tried this several times today, this was working with no problem last Thursday ( 12/08)

**Comment by smenon78** [comment]
Also, I was doing kubectl apply -f https://git.io/weave-kube to install the network pod. There is a new version 1.8.2.

**Comment by smenon78** [comment]
Ok, this looks like an Issue with weave version 1.8.2. I used a yaml file and changed the image to 1.8.1 and now its running.

**Comment by freehan** [comment]
Is there an issue upstream?

**Comment by smenon78** [comment]
I haven't created one, Weave latest (1.8.2) was released 4 days ago and looks like this is broken for aws.

**Comment by mikedanese** [comment]
Can you file an issue with weave-kube? Also in the future can you file kubeadm issues over here https://github.com/kubernetes/kubeadm ? Thanks for the report!

**Comment by mikedanese** [comment]
cc @errordeveloper @lukemarsden
