### ISSUE TITLE
cacheWatcher leaks goroutines

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#38670]
We noticed many goroutines stalled at https://github.com/kubernetes/kubernetes/blob/v1.4.6/pkg/storage/cacher.go#L701 in a large cluster (~200 nodes, ~1100 pods). It's because if the WatchServer timeout [fires](https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/watch.go#L187-L188) when the `result` channel is full, `sendWatchCacheEvent` will be blocked on the write to the `result` even though `cacheWatch.Stop()` is [called](https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/watch.go#L171), because WatchServer stops consuming the `result` channel after the timeout.

**Comment by wojtek-t** [comment]
Great finding - thanks for debugging @caesarxuchao
