### ISSUE TITLE
k8s runs in openstack instances. Node status is NotReady, but pods still run in it

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes/kubernetes#38671]
k8s cluster run in two openstack instances. One node status is NotReady because of keystone error ,but pods still run in it.
Should we scheduled the pods to another node?

-bash-4.3# kubectl get pod -o wide
NAME      READY     STATUS    RESTARTS   AGE       NODE
ubuntu1   1/1       Running   0          1h        yuanquan-2
-bash-4.3# kubectl get nodes
NAME         STATUS     AGE
yuanquan-1   Ready      15h
yuanquan-2   NotReady   20h

**Comment by xsgordon** [comment]
@idvoretskyi can you add the sig/openstack label please?

/cc @kubernetes/sig-openstack

**Comment by grahamhayes** [comment]
Looks like #37846 closes this

**Comment by NickrenREN** [comment]
Not the same .   When the node status was marked NotReady because of keystone error.  The pods in that node were not rescheduled and still run in it .

**Comment by anguslees** [comment]
I think this is controlled by generic kubernetes code (not openstack-specific), fwiw.  The bug report indicates that the node *is* correctly reported as NotReady, and after that I can't think of any other place where the provider plugin gets involved in this decision...

**Comment by dims** [comment]
/close

Let's mark this as closed with @NickrenREN 's #39468 PR
