### ISSUE TITLE
Disallow setting activeDeadlineSeconds for restartAlways pods/controllers

### ISSUE THREAD

**Issue by sandflee** [kubernetes/kubernetes#38684]
setting activeDeadlineSeconds in deployment pod template, and seen new pods are continuously created after the older one dies. Is this excepted? if not we should forbidden this.

**Comment by kargakis** [comment]
Yes, it is expected. Once a pod dies, the replica set controller will spawn a new one. activeDeadlineSeconds doesn't make any sense when used under a controller.

**Comment by kargakis** [comment]
@kubernetes/deployment @smarterclayton we may want to make it a validation error, but I don't feel strong.

**Comment by bgrant0607** [comment]
@kargakis Yes, we should not allow activeDeadlineSeconds for restartPolicy=Always pods generally.

**Comment by roko-p** [comment]
What if I want a container to be restarted no matter what status it exits with, *but* to give up trying if it cannot even start up in `x` seconds?

So like this:
Start a pod
- if it keeps constantly failing for `x` seconds: stop it
- else (if it managed to start and not fail in those first `x` seconds from creating): restart it everytime it fails *or* successfully finishes

**Comment by kargakis** [comment]
@roko-p then you want your own controller, RCs are designed for a simple use case: long-running apps. 

Have a look in [TPR](https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-third-party-resource/), though keep in mind they are under a major redesign: https://github.com/kubernetes/features/issues/95

**Comment by andy-v-h** [comment]
Sorta late to the party, but this behavior stops us from being able to use a Deployment to mitigate a production memory leak. Our application can handle a `SIGTERM`, but a `OOM` `SIGKILL` leaves items in a pending state for our customers. Killing pods on a regular basis through kubernetes would allow us to induce known behavior of a graceful termination versus deploying new code to handle a timer before terminating. 

While I understand the intention of this feature, I feel that as a mitigation tool while my teams track down the memory leak, this would let my oncall rotation sleep easy.
