### ISSUE TITLE
'Error: 100: Key not found (/registry/nodes)' error written by kubelet

### ISSUE THREAD

**Issue by peter-braun** [kubernetes/kubernetes#3871]
Hi,

I started to build 3-node (master + 2 worker) "cluser" from scratch using binaries built (by myself) from master's head.

    [root@kube-master ~]# kube-apiserver --version
    Kubernetes v0.8.0-721-g586c7c80b28416-dirty
    
    [root@kube-master ~]# kube-scheduler --version
    Kubernetes v0.8.0-721-g586c7c80b28416-dirty
    
    [root@kube-master ~]# kube-controller-manager --version
    Kubernetes v0.8.0-721-g586c7c80b28416-dirty
    
    [root@kube-master ~]# kubectl version
    Client Version: version.Info{Major:"0", Minor:"8+", GitVersion:"v0.8.0-721-g586c7c80b28416-dirty", GitCommit:"586c7c80b28416b23ca07d024abd02940e464972", GitTreeState:"dirty"}
    Server Version: version.Info{Major:"0", Minor:"8+", GitVersion:"v0.8.0-721-g586c7c80b28416-dirty", GitCommit:"586c7c80b28416b23ca07d024abd02940e464972", GitTreeState:"dirty"}
    
    [root@kube-minion-1 kubernetes]# kubelet --version
    Kubernetes v0.8.0-721-g586c7c80b28416-dirty

I use the following parameters to launch the binaries:

    /usr/bin/kube-apiserver \
            --logtostderr=false \
            --log_dir=/var/log/kubernetes \
            --v=0 \
            --etcd_servers=http://kube-master:4001 \
            --address=0.0.0.0 \
            --port=8080 \
            --kubelet_port=10250 \
            --allow_privileged=false \
            --portal_net=10.254.0.0/16 \
            --runtime_config=api/v1beta3
    
    /usr/bin/kube-controller-manager \
            --logtostderr=false \
            --log_dir=/var/log/kubernetes \
            --v=0 \
            --master=http://kube-master:8080 \
            --machines=kube-minion-1,kube-minion-2 \
            --api_version=v1beta3
   
    /usr/bin/kube-scheduler \
            --logtostderr=false \
            --log_dir=/var/log/kubernetes \
            --v=0 \
            --master=http://kube-master:8080 \
            --api_version=v1beta3
    
    /usr/bin/kubelet \
            --logtostderr=false \
            --log_dir=/var/log/kubernetes \
            --v=0 \
            --etcd_servers=http://kube-master:4001 \
            --address=0.0.0.0 \
            --port=10250 \
            --hostname_override=kube-minion-1 \
            --allow_privileged=false

The kubelet continuously drops the following E-log:

    E0128 16:02:54.180048     603 etcd.go:64] etcd failed to retrieve the value for the key "/registry/nodes/kube-minion-1/boundpods". Error: 100: Key not found (/registry/nodes) [8]

Then I use `run-container` to instantly create replication controller and pods:

    [root@kube-master ~]# kubectl run-container blocker --image=blocker --replicas=2
    CONTROLLER          CONTAINER(S)        IMAGE(S)            SELECTOR                REPLICAS
    blocker             blocker             blocker             run-container=blocker   2

Pods remain unassigned even after few minutes, while there are nodes with `Ready` status:

    [root@kube-master ~]# kubectl get po
    POD                                    IP                  CONTAINER(S)        IMAGE(S)            HOST                LABELS                  STATUS
    e78c11e5-a701-11e4-9029-5254005f00dc                       blocker             blocker             <unassigned>        run-container=blocker   Pending
    e78c76bf-a701-11e4-9029-5254005f00dc                       blocker             blocker             <unassigned>        run-container=blocker   Pending

    [root@kube-master ~]# kubectl get node
    NAME                LABELS              STATUS
    kube-minion-1       <none>              Ready
    kube-minion-2       <none>              Ready

In `etcd` there is no key like `/registry/nodes`:

    [root@kube-master ~]# curl -s -L http://kube-master:4001/v2/keys/registry | python -mjson.tool
    {
        "action": "get",
        "node": {
            "createdIndex": 3,
            "dir": true,
            "key": "/registry",
            "modifiedIndex": 3,
            "nodes": [
                {
                    "createdIndex": 3,
                    "dir": true,
                    "key": "/registry/services",
                    "modifiedIndex": 3
                },
                {
                    "createdIndex": 7,
                    "dir": true,
                    "key": "/registry/minions",
                    "modifiedIndex": 7
                },
                {
                    "createdIndex": 9,
                    "dir": true,
                    "key": "/registry/controllers",
                    "modifiedIndex": 9
                },
                {
                    "createdIndex": 10,
                    "dir": true,
                    "key": "/registry/pods",
                    "modifiedIndex": 10
                },
                {
                    "createdIndex": 12,
                    "dir": true,
                    "key": "/registry/events",
                    "modifiedIndex": 12
                }
            ]
        }
    }

Is it a misbehavior of kube-apiserver / kubelet or I just use wrong parameters when I fire up the binaries?

One more thing, this worked for me with the following version yesterday (binaries downloaded from github):

    Client Version: version.Info{Major:"0", Minor:"9+", GitVersion:"v0.9.1-dirty", GitCommit:"3623a01bf0e90de6345147eef62894057fe04b29", GitTreeState:"dirty"}
    Server Version: &version.Info{Major:"0", Minor:"9+", GitVersion:"v0.9.1-dirty", GitCommit:"3623a01bf0e90de6345147eef62894057fe04b29", GitTreeState:"dirty"}

One more thing: is that right habbit to ask questions like this at here (github/issues) or do you have some other forum to post question?

Thanks,
peter

**Comment by peter-braun** [comment]
One more thing to add: I built the binaries by issuing plain `make release`. So I did no do any configuration (I even don't know if there is any ;)) before building.

**Comment by alex-mohr** [comment]
Okay, 0.9.1 worked, but 0.8.0 did not.  I found #3617 which reported similar `registry/nodes` errors and it was also 0.8, so I suspect a fixed issue in 0.9.  I also confirmed that 0.9 also does not have a `registry/nodes` entry -- it looks identical to your 0.8 output above.

Re: where to ask questions, check the bottom of https://github.com/googlecloudplatform/kubernetes for links to irc and a couple of mailing lists, although here is just fine too.

**Comment by peter-braun** [comment]
I've got the same problem with 0.10.0 (with 0.9.3 it was the same).

    [root@node00 ~]# sc status -l kubelet
    kubelet.service - Kubernetes Kubelet Server
       Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled)
       Active: active (running) since Wed 2015-02-04 15:08:17 CET; 9min ago
         Docs: https://github.com/GoogleCloudPlatform/kubernetes
     Main PID: 5278 (kubelet)
       CGroup: /system.slice/kubelet.service
               +-5278 /usr/bin/kubelet --logtostderr=false --log_dir=/var/log/kubernetes --v=0 --etcd_servers=http://node00:4001 --address=0.0.0.0 --port=10250 --hostname_override=node00 --allow_privileged=false
    
    Feb 04 15:17:38 node00 kubelet[5278]: E0204 15:17:38.530608    5278 etcd.go:64] etcd failed to retrieve the value for the key "/registry/nodes/node00/boundpods". Error: 100: Key not found (/registry/nodes) [56]
    Feb 04 15:17:39 node00 kubelet[5278]: E0204 15:17:39.531035    5278 etcd.go:64] etcd failed to retrieve the value for the key "/registry/nodes/node00/boundpods". Error: 100: Key not found (/registry/nodes) [56]
    Feb 04 15:17:40 node00 kubelet[5278]: E0204 15:17:40.531715    5278 etcd.go:64] etcd failed to retrieve the value for the key "/registry/nodes/node00/boundpods". Error: 100: Key not found (/registry/nodes) [58]

The start-up parameters (here I'm using v1beta3 API, hope on right way(?)):

    /usr/bin/kube-apiserver --logtostderr=false --log_dir=/var/log/kubernetes --v=0 --etcd_servers=http://node00:4001 --address=0.0.0.0 --port=8080 --kubelet_port=10250 --allow_privileged=false --portal_net=10.254.0.0/16 --public_address_override=192.168.1.100 --runtime_config=api/v1beta3
    /usr/bin/kube-scheduler --logtostderr=false --log_dir=/var/log/kubernetes --v=0 --master=http://node00:8080 --api_version=v1beta3
    /usr/bin/kube-controller-manager --logtostderr=false --log_dir=/var/log/kubernetes --v=0 --master=http://node00:8080 --api_version=v1beta3  --machines=node00,node01,node02,node03,node04


Version info:

    [root@node00 ~]# kubelet --version
    Kubernetes v0.10.0-dirty
    [root@node00 ~]# kube-apiserver --version
    Kubernetes v0.10.0-dirty
    [root@node00 ~]# kube-scheduler --version
    Kubernetes v0.10.0-dirty
    [root@node00 ~]# kube-controller-manager --version
    Kubernetes v0.10.0-dirty

I removed v1beta3 flags from the start-up commands, but the symptom is the same.

Peter

**Comment by wshwawa** [comment]
Just my 2 cents: kubelet should ask api server for updates instead of etcd
since 0.9, but I didn't see that from your command line:
/usr/bin/kubelet --logtostderr=false --log_dir=/var/log/kubernetes --v=0
--etcd_servers=http://node00:4001 --address=0.0.0.0 --port=10250
--hostname_override=node00 --allow_privileged=false

**Comment by peter-braun** [comment]
Yep. I'm just trying that. And of course the above errors have gone. However it should work from etcd as well, shouldn't it?

But now I've got another issue.  I've created replication controller (with `kubectl run-container` command). However I have worker nodes in `Ready` state, the pods stay in `Pending` state:

    [root@node00 ~]# kubectl get node
    NAME                LABELS              STATUS
    node00              <none>              Ready
    node01              <none>              Ready
    node02              <none>              Ready
    node03              <none>              NotReady
    node04              <none>              NotReady
    
    [root@node00 ~]# kubectl get rc
    CONTROLLER          CONTAINER(S)        IMAGE(S)            SELECTOR                REPLICAS
    blocker             blocker             oam-blocker         run-container=blocker   2
    
    [root@node00 ~]# kubectl get po
    POD                 IP                  CONTAINER(S)        IMAGE(S)            HOST                LABELS                  STATUS
    blocker-fplln                           blocker             oam-blocker         <unassigned>        run-container=blocker   Pending
    blocker-gziey                           blocker             oam-blocker         <unassigned>        run-container=blocker   Pending

The log of `kube-scheduler` contains lots of these entries:

    Feb 04 17:36:54 node00 kube-scheduler[2196]: E0204 17:36:54.700218    2196 poller.go:72] failed to list: minions "" not found
    Feb 04 17:37:01 node00 kube-scheduler[2196]: E0204 17:37:01.648933    2196 factory.go:227] Error scheduling default blocker-fplln: no minions available to schedule pods; retrying
    Feb 04 17:37:01 node00 kube-scheduler[2196]: E0204 17:37:01.665315    2196 factory.go:227] Error scheduling default blocker-gziey: no minions available to schedule pods; retrying

I don't know what went wrong, but it should be some problem at my side, because this is a basic functionality which I think (hope) is covered by tests.

Please advise where to continue investigating.

Thanks,
Peter

**Comment by mingfang** [comment]
I'm seeing this problem in 0.10.0 also
