### ISSUE TITLE
All generated files should have predictable names

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubernetes#38712]
As we work toward a dockerized build, we need to easily be able to figure out which files are generated and which files are "source".  As such, generated files should have a predictable name (`zz_generated.*`) or be under an obvious generated directorey (`_output`).

/cc @thockin @ncdc (#36080) @ixdy @deads2k @liggitt @sttts @mikedanese @caesarxuchao

**Comment by jbeda** [comment]
@ncdc -- can you fix the listeners up so that they continue to use generated names?

**Comment by thockin** [comment]
I have been converting generators to be on-demand and renaming to
zz_generated.* along the way.  I hope to un-commit those files from the
build soon.

**Comment by ncdc** [comment]
@jbeda it sounds like @thockin is saying don't do that?

**Comment by ncdc** [comment]
Whoops, misread

**Comment by jbeda** [comment]
Also, predictable naming here will help when we no longer check this stuff in and we need to put all these files in `.gitignore`.

**Comment by ncdc** [comment]
@thockin I've got the changes for generated listers and informers ready to go... do you want me to hold off? Or maybe just send you the diffs to the generators and you can take it from there?

**Comment by thockin** [comment]
changes to build on-demand or just to rename?

**Comment by ncdc** [comment]
Just to rename

**Comment by thockin** [comment]
please don't rename to zz_generated unless they auto-rebuild.

**Comment by ixdy** [comment]
> I have been converting generators to be on-demand and renaming to zz_generated.* along the way.  I hope to un-commit those files from the build soon.

Does this mean we're planning to break plain `go build` working? (This might already be true, I haven't checked recently...)

**Comment by thockin** [comment]
Yes, I plan to break go build.

**Comment by jbeda** [comment]
I differ slightly from Tim -- All generated files, regardless of if they are manually or automatically generated via make, should have a predictable name.  We might want to have a pattern for automatically generated files and another for check-in manually generated files.  But we want to have a way to have the dockerized build know which files to pull back from a build environment to the local tree.

This is especially important for things generated by bazel.  It will often be the case where folks won't want to or have to have bazel installed locally.  That means that bazel will only ever run in a container.  We need to then be able to pull all of the generated stuff back out.  See https://github.com/kubernetes/kubernetes/blob/master/build-tools/common.sh#L704.

**Comment by thockin** [comment]
I am fine with a pattern, just don't make it zz_generated (unless we change
the existing on-demand generators :)

We also have .generated_files which describes this problem in a way that
the github munger consumes and
https://github.com/kubernetes/kubernetes/pull/38427 which sort of describes
them in a way git understands.

**Comment by caesarxuchao** [comment]
In O(month), for listers and clientsets, I would expect users to pull the generated code from [client-go](https://github.com/kubernetes/client-go), they don't need to generate them during build.

**Comment by ncdc** [comment]
@thockin I'm confused. When should a generated file be prefixed with zz_generated vs not?

@caesarxuchao do you plan to move generated informers there too?

**Comment by thockin** [comment]
zz_generated is currently "files that are build on-demand by `make` and
will soon be remove from the tree".  If your files are not generated on
demand or are not OK to remove from the tree (same thing), please use a
diff name. :)

**Comment by ncdc** [comment]
Thanks for the clarification. I'll see if I can update the makefile so the listers and informers are build on-demand.

**Comment by thockin** [comment]
There be dragons...fair warning...

**Comment by ncdc** [comment]
Oh I've already been through Makefile.generated_files a lot, so I'm well prepared 😄

**Comment by thockin** [comment]
http://www.tshirtvortex.net/wp-content/uploads/Dangerous-Take-This-Sword-Link-Legend-of-Zelda-T-Shirt-sq.jpg

**Comment by caesarxuchao** [comment]
> @caesarxuchao do you plan to move generated informers there too?

Yes, I plan to move anything people need to write a controller.

**Comment by jbeda** [comment]
IMO, it is cool if we have manually generated files that are checked in too.  But those should have a unique name so that the generation itself can be run in a container and the results copied out.  Based on Tim's feedback it shouldn't be `zz_generated.*` but could be something else predictable.  `manualgen.foo.go`?

If at all possible, then put a `README` or a comment on the top of the file about *how* to regen the files as `make` won't do it.

**Comment by thockin** [comment]
I'm fine with changing the prefix we use for on-the-fly files, too, just as
long as it is different.
