### ISSUE TITLE
Nothing().String() sentinel value is not in the grammar

### ISSUE THREAD

**Issue by rudle** [kubernetes/kubernetes#38718]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): Nothing(), selector, Nothing selector

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Kubernetes version** (use `kubectl version`):
HEAD

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
code snippet: `labels.Parse(labels.Nothing().String())`` 

**What you expected to happen**:
I expected `labels.Parse(labels.Nothing().String()) == labels.Nothing()`

**How to reproduce it** (as minimally and precisely as possible):
https://gist.github.com/rudle/d6225be92164fd235072ffa4a243c32d

**Anything else do we need to know**:
I have already written a patch for this issue. PR coming soon.

**Comment by spzala** [comment]
@rudle hi, I don't see the mentioned code snippet in the repo now. Also the related PR is no longer active. I guess we can close this issue? Thanks!!
