### ISSUE TITLE
Implicitly call cluster/get-kube-binaries.sh

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#38725]
Kubernetes 1.5.0 require to call `cluster/get-kube-binaries.sh` explicitly. This breaks the existing interface of starting Kubernetes cluster using `cluster/get-kube-binaries.sh`. 

Discussed with @ixdy @jbeda on slack and they will fix this.

This should also fix the issue seen in https://github.com/kubernetes/kubernetes/issues/38722.

**Comment by ixdy** [comment]
Rough idea is that `cluster/kube-up.sh` should probably call `cluster/get-kube-binaries.sh` if the client/server binaries don't exist.

**Comment by spiffxp** [comment]
probably more than just `kube-up`, my use case is bringing up a cluster using a separate tool, and then using `e2e.go` solely for testing
