### ISSUE TITLE
Make defaulting consist for LabelSelector

### ISSUE THREAD

**Issue by ymqytw** [kubernetes/kubernetes#38740]
`StatefulSet, DaemonSet, Deployment, ReplicaSet` use `obj.Spec.Template.Labels` to default `obj.Spec.Selector` and `obj.Labels`; while `Job` only default [`obj.Labels`](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/batch/v1/defaults.go#L44).

Should we make `Job` the same as the others?

@kubernetes/sig-apps

**Comment by AdoHe** [comment]
@soltysh ptal.

**Comment by smarterclayton** [comment]
I thought jobs were like this for a reason - doesn't the proposal call this out?

**Comment by soltysh** [comment]
Jobs [generate selector](https://github.com/kubernetes/kubernetes/blob/e338afbca70f6aec658f10b5af1866d9626192ff/pkg/registry/batch/job/strategy.go#L75), that's why we're not defaulting them there.

**Comment by ymqytw** [comment]
> Jobs generate selector, that's why we're not defaulting them there.

@soltysh I found the [design doc](https://github.com/kubernetes/kubernetes/blob/master/docs/design/selector-generation.md). Thanks.

**Comment by soltysh** [comment]
@ymqytw are you ok closing this issue, in that case?
