### ISSUE TITLE
--dry-run=true & --validate=true not picking up errors in deployment template

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/kubernetes#38748]
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+82450d0", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"not a git tree", BuildDate:"2016-12-14T04:09:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **OS** (e.g. from /etc/os-release):

```
NAME=Boot2Docker
VERSION=1.11.1
ID=boot2docker
ID_LIKE=tcl
VERSION_ID=1.11.1
PRETTY_NAME="Boot2Docker 1.11.1 (TCL 7.1); master : 901340f - Fri Jul  1 22:52:19 UTC 2016"
ANSI_COLOR="1;34"
HOME_URL="http://boot2docker.io"
SUPPORT_URL="https://github.com/boot2docker/boot2docker"
BUG_REPORT_URL="https://github.com/boot2docker/boot2docker/issues"
```

- **Kernel** (e.g. `uname -a`): Linux minikube 4.4.14-boot2docker #1 SMP Fri Jul 1 21:46:36 UTC 2016 x86_64 GNU/Linux
- **Install tools**: Minikube

**What happened**:

I'm using the new `--dry-run` flag to validate my JSON/YAML as a test step. I created an invalid YAML document by assigning the `value` inside deployment's template container's env to a numeric value. The dry run completed successfully.

**What you expected to happen**:

The dry run should fail because the container spec is invalid.

**How to reproduce it** (as minimally and precisely as possible):

Create a deployment with a template spec with an invalid container env:

```
- name: FOO
  value: 234982349823748 # use a numeric value
```

Next: `kubectl create --dry-run=true --validate=true -f test.yaml`

**Comment by xingzhou** [comment]
The `value` field for `env` required a string value with leading '"', I reproduce the issue on my local env based on latest code from master. I'd like to take a look at this issue.

**Comment by xingzhou** [comment]
These [lines](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/schema.go#L383-L390) are now used by kubectl to validate yaml files. 

As `v1.EnvVar[].value` is of `string` type, according to the code right now, the data of this field is `"Be loose about what we accept for 'string' since we use IntOrString in a couple of places"`.

 But from apiserver side, when it decodes the request, it strictly checks whether a field is a string not a number, so we will get `BadRequest` error like `expect char '"', but got char '1'`.

I think this is the root cause for causing the inconsistency of `dry-run` validation and apiserver side validation. 

To @AdoHe, not sure if we can check strictly from kubectl side on the `string` type field? do we still have any validations that use `IntOrString` policy?

**Comment by Gerrit-K** [comment]
I know this issue is ancient, but I still encounter this error and this issue was the closest I could find. In my case it was not a number but a boolean `true` that was unquoted. 
Here are the steps to reproduce (on v1.15.7):

`test.yaml`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: new-deployment
  name: new-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: new-deployment
    spec:
      containers:
      - image: busybox
        env:
        - name: FOO
          value: true
        name: busybox
        resources: {}
status: {}
```

Steps:
```bash
$ kubectl apply --dry-run -f test.yaml --validate
deployment.apps/new-deployment created (dry run)
$ kubectl apply -f test.yaml
Error from server (BadRequest): error when creating "test.yaml": Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found t, error found in #10 byte of ...|,"value":true}],"ima|..., bigger context ...|ec":{"containers":[{"env":[{"name":"FOO","value":true}],"image":"busybox","name":"busybox","resource|...
```

/reopen
