### ISSUE TITLE
kubeadm kube-dns not works

### ISSUE THREAD

**Issue by Rongjf** [kubernetes/kubernetes#38752]
![image](https://cloud.githubusercontent.com/assets/6251321/21180869/eb8b15e8-c235-11e6-8121-a4279a1159ca.png)
E1214 11:02:43.489682       1 reflector.go:214] pkg/dns/dns.go:155: Failed to list *api.Endpoints: Get http://localhost:8080/api/v1/endpoints?resourceVersion=0: dial tcp: lookup localhost on 172.18.50.5:53: dial udp 172.18.50.5:53: connect: network is unreachable
E1214 11:02:43.493705       1 reflector.go:214] pkg/dns/dns.go:156: Failed to list *api.Service: Get http://localhost:8080/api/v1/services?resourceVersion=0: dial tcp: lookup localhost on 172.18.50.5:53: dial udp 172.18.50.5:53: connect: network is unreachable
I1214 11:02:44.485313       1 dns.go:173] Ignoring error while waiting for service default/kubernetes: Get http://localhost:8080/api/v1/namespaces/default/services/kubernetes: dial tcp: lookup localhost on 172.18.50.5:53: dial udp 172.18.50.5:53: connect: network is unreachable. Sleeping 1s before retrying.

**Comment by Rongjf** [comment]
"curl http://localhost:8080/api/v1/endpoints?resourceVersion=0 "
![image](https://cloud.githubusercontent.com/assets/6251321/21180926/3e104824-c236-11e6-834e-28457b2d2a2b.png)

**Comment by luxas** [comment]
Please reopen this issue in the kubeadm repo in case you can reproduce this error: https://github.com/kubernetes/kubeadm/issues
