### ISSUE TITLE
Scale client should accept a GroupVersionResource instead of string 

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#38759]
Quoting @deads2k from https://github.com/kubernetes/kubernetes/pull/32523#issuecomment-250156525:

> A scale client should accept a GroupVersionResource and a Scale object. It should then use the GVR in combination with a dynamic client to make its request.

[Current implementation of scale](https://github.com/kubernetes/kubernetes/blob/9705bb728e768be02bf5b32aa14dec059f9269ed/pkg/client/clientset_generated/internalclientset/typed/extensions/internalversion/scale_expansion.go#L27-L28) expects `Kind` which is a `string` and a `Scale` object. To be consistent with current codebase we should switch the first argument to require `GroupVersionResource`, instead.

@kubernetes/sig-api-machinery objections?

**Comment by nikhita** [comment]
We have the generic scale client now. Closing.

/close
