### ISSUE TITLE
Is SSH in containers really needed?

### ISSUE THREAD

**Issue by mcapuccini** [kubernetes/kubernetes#38753]
Hi. Why do you run SSH in GlusterFS containers? Maybe I am being naive, but wouldn't it be better to use `kubectl exec` to run commands in the containers? I am saying this because you run the DaemonSet with host network and in privileged mode, and makes me feel questioning the security of this provisioning strategy. In some OpenStack installation the firewall can fail sometimes in applying the security groups, and if this happens it would expose the SSH servers to the internet.

**Comment by dims** [comment]
@mcapuccini what container images are you using? (which instructions are you following to start GlusterFS containers)

**Comment by kargakis** [comment]
@kubernetes/sig-storage

**Comment by mcapuccini** [comment]
Sorry guys... I opened this in the wrong place, my bad.
