### ISSUE TITLE
kubectl create should be in its own package

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#38761]
Similar to the rest of our nested commands (set, rollout). Unfortunately a straight move is not possible atm because of create depending on edit (thus introducing cyclic dependencies in kubectl). We should probably move the edit functionality in a common location (eg. the already existing pkg/kubectl/cmd/util/editor) and have the kubectl commands re-use it. I am not sure if we want to do such a thing, just wanted to bring this up

@kubernetes/kubectl @kubernetes/sig-cli thoughts

**Comment by smarterclayton** [comment]
Yes, we want to do this thing.  We should be actively splitting
`pkg/kubectl/cmd` up.

**Comment by soltysh** [comment]
Similar to https://github.com/kubernetes/kubernetes/issues/36805.

**Comment by AdoHe** [comment]
```
We should be actively splitting `pkg/kubectl/cmd` up.
```
This should be something on kubectl roadmap, I would like to get it move forward in 1.6.

**Comment by AdoHe** [comment]
I am picking this up now, and will open a PR asap.

**Comment by adohe** [comment]
@shiywang I just open a PR to fix this, so just re-assign this to me. you may want to take a look.

**Comment by kargakis** [comment]
We can proceed with this now that edit has been made re-usable.

**Comment by shiywang** [comment]
@kargakis @adohe any progress on this ? if tony is busy I would like to help here : )

**Comment by tcharding** [comment]
Woops, I duplicated @adohe's  PR before I saw it had already been done. Sorry for the noise, I'll close mine and leave this one since it was first.

**Comment by tcharding** [comment]
Is this still active?

**Comment by kargakis** [comment]
I don't think there is any work in-flight cc @adohe

**Comment by tcharding** [comment]
I've got spare cycles, if you want me to pick this up @adohe just say.

**Comment by kargakis** [comment]
/unassign @adohe 

due to lack of response

/help
/remove-lifecycle stale

**Comment by shiywang** [comment]
@kargakis could you assign to me ? thanks

**Comment by adohe** [comment]
I will finish this in the next milestone.

**Comment by kargakis** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/62341

/close
