### ISSUE TITLE
Update kubectl.GetPrinter to not return both nil for the printer and nil for the error on `wide` format

### ISSUE THREAD

**Issue by juanvallejo** [kubernetes/kubernetes#38779]
**Problem**

Right now, printer helpers such as [cmdutil.PrinterForCommand](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/printing.go#L128) call [kubectl.GetPrinter](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L74) with the output format specified by a `--output` flag, in order to retrieve the right printer for that format.

When `kubect.GetPrinter` is called with a `wide` format, [nil is returned for both the printer and the error](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L144). This has inevitably led to panics throughout kubectl commands whenever code that calls `kubectl.GetPrinter`  (either directly or indirectly through cmdutil.PrinterForCommand`) attempts to use the retrieved printer if no errors are returned. For example:

```go
// $ kubectl ... -o wide

outputFormat := cmdutil.GetFlagString(cmd, "output")
printer, generic, err := kubectl.GetPrinter(outputFormat, ...)
if err != nil {
    // handle error
    return
}

// any code here assumes no error AND that the printer exists, however since both the printer and the 
// error were nil for the "wide" outputFormat, the line below will cause a panic
printer.PrintObj(info.Object, out)
```

Commands like `kubectl create` and `kubectl apply` get around this by [only supporting the `name` output format](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/create.go#L156), however when expanding these commands [to eventually use all supported output formats by resource printers](https://github.com/kubernetes/kubernetes/pull/38112) (json, yaml, custom-columns, etc...), this becomes an issue.

**Proposal**

1. A solution to this could either be to actually return an error in [kubect.GetPrinter](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L144) if the returned printer will be `nil`
 - which would then allow existing helpers such as [cmdutil.PrinterForCommand](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/printing.go#L108) to handle this and return a `NewHumanReadablePrinter` with the right `PrintOptions` for example, 

2. or to simply return a `NewHumanReadablePrinter` in `kubectl.GetPrinter` any time the output format specified == `wide`.

cc @fabianofranz @pwittrock @AdoHe @deads2k

**Comment by fabianofranz** [comment]
@kubernetes/sig-cli @kubernetes/kubectl
