### ISSUE TITLE
Build and distribute Windows binaries

### ISSUE THREAD

**Issue by pires** [kubernetes/kubernetes#38785]
As of 1.5, `kubelet` and `kube-proxy` are ready to run on Windows systems. Those are needed by users giving a try at Windows Containers alpha support.

e.g., the following doesn't seem to exist, http://storage.googleapis.com/kubernetes-release/release/v1.5.1/bin/windows/amd64/kube-proxy.exe

/cc @brendandburns @michmike @jbhurat @alexbrand

**Comment by ixdy** [comment]
At the very least, you'd need to update [this list](https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh#L59-L65). That will build all of the server binaries, not just `kubelet` and `kube-proxy`, and I don't know how many of them even build for windows.

There are a number of other scripts scattered around which might need to be updated, too. See for example #37092 and #36050, which added linux/s390x support.

**Comment by hongxima** [comment]
We deployed the Windows binaries built by ourselves before the 1.5 formal release, and was trying to shift to formal 1.5 release until we failed to locate the Windows binaries within the release. 
I think it's very helpful to include those binaries for people who wants to try Windows container management but has no experience or no interest to make a private build.

**Comment by pires** [comment]
Thanks @ixdy!

Unfortunately, some of the binaries listed in `kube::golang::server_targets()` can't compile for Windows, e.g. `kube-dns`, so the change doesn't seem to be trivial.

**Comment by pires** [comment]
Should be fixed by #38919.

**Comment by ixdy** [comment]
Still need to fix https://github.com/kubernetes/release/blob/master/lib/releaselib.sh#L480-L491.

**Comment by pires** [comment]
Damn, somehow I missed this and we don't have binaries for 1.5.2.

**Comment by pires** [comment]
@brendandburns would you be willing to pick this?

**Comment by jbhurat** [comment]
@brendandburns can you please pick this up

**Comment by brendandburns** [comment]
Just created a pick for this here:

https://github.com/kubernetes/kubernetes/pull/40507

**Comment by brendandburns** [comment]
https://github.com/kubernetes/release/pull/252 to address @ixdy 's comment.

**Comment by brendandburns** [comment]
Looks like go-systemd doesn't build on linux in the 1.5 branch?

@pires did you do a pull to fix something there for mainline?

**Comment by pires** [comment]
No. Is that even supposed to compile for Windows? I think it's related to building the binaries after building them for other platforms but I'm not sure.

**Comment by brendandburns** [comment]
This is fixed.
