### ISSUE TITLE
HPA is still using replicationcontrollers.extensions/scale

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#38810]
HPA should be working against the polymorphic endpoint in the legacy API group `replicationcontrollers/scale`, not the copy in extensions, since no other resource will ever be able to inject itself into extensions.

@DirectXMan12 @soltysh @kubernetes/rh-cluster-infra

**Comment by deads2k** [comment]
I found this reviewing permissions for enabling RBAC and was sad.

**Comment by smarterclayton** [comment]
I think this was fixed?
