### ISSUE TITLE
Dead code in `pkg/registry/generic/registry/store.go`

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#38822]
The inner `err != nil` on [these lines](https://github.com/kubernetes/kubernetes/blob/f369372dad201d97b9a69bf2070e54f716077dc4/pkg/registry/generic/registry/store.go#L881-L884) will never run.

cc @smarterclayton @liggitt @deads2k

**Comment by deads2k** [comment]
> The inner err != nil on these lines will never run.
> 
> cc @smarterclayton @liggitt @deads2k

really?  Open a pull.
