### ISSUE TITLE
Force detach AWS volume if kubelet is down

### ISSUE THREAD

**Issue by rootfs** [kubernetes/kubernetes#38824]
Volume attached to node A. Shutdown kubelet on node A. Wait for a while, pod is then scheduled to node B. But volume keeps attached to node A, regardless how hard master is trying to detach it. Pod status thus ends up as "ContainerCreating". 

Master log is populated with
```
Waiting for volume state: actual=busy, desired=detached
```

On AWS console, I see the volume status is always in-use, even I manually unmount the volume on node A. I have to force detach the volume. Once force detach succeeds, Pod is rescheduled and recreated successfully.

AWS SDK offers a [Force option](https://github.com/aws/aws-sdk-go/blob/master/service/ec2/api.go) to force detach volume.  Shouldn't we use it in this case?

@justinsb @kubernetes/sig-aws @kubernetes/sig-storage

**Comment by justinsb** [comment]
My understanding is that AWS can (somehow) detect if a volume is still mounted, and will refuse to unmount it without force detach.  But force detach is fundamentally unsafe - we know that disk operations are likely in progress.

@rootfs can you confirm that a pod was still running that had the volume mounted?

What I typically do is to terminate the instance instead; it feels much safer in terms of the filesystem ending up in a consistent state.  And there is an open issue to eventually do that for instances that are NotReady.  Would that work @rootfs ?

**Comment by rootfs** [comment]
@justinsb thanks for the ideas. Agree with safety concern of forced detach.  stonith is surely a better solution, but kube hasn't built in this mechanism yet.

In my case, the kubelet is down but the node itself is still up - this is a negative test case we are running. On the bad node, the pod is still running and volume is still mounted.

**Comment by justinsb** [comment]
I'm actually going to reopen this (if that's OK @rootfs) because it is a good idea, and we haven't implemented STONITH.  I think we should either implement this or STONITH.

**Comment by eghobo** [comment]
@justinsb I am not sure that force detach is good idea, e.g. operator just want restart kubelet.

**Comment by chrislovecnm** [comment]
@sharm is this your use case

**Comment by chrislovecnm** [comment]
cc @kubernetes/sig-aws-misc

**Comment by saad-ali** [comment]
> My understanding is that AWS can (somehow) detect if a volume is still mounted, and will refuse to unmount it without force detach. But force detach is fundamentally unsafe - we know that disk operations are likely in progress.

That's pretty cool that AWS can detect that a mount and not permit detach. The k8s attach/detach controller currently has logic that will call detach if the node is unresponsive for 6 minutes (i.e. has not reported the volume safely unmounted). If we want to implement this, we can modify the Detach call to take a force flag, and make the attach/detach controller set that to true when it initiates the unilateral detach--AWS detach can then use that flag. The big question is if.

**Comment by rootfs** [comment]
Oh, I missed the discussion. Will investigate it thanks @justinsb

**Comment by rootfs** [comment]
@justinsb @saad-ali  cinder volume has "force" detach
https://github.com/kubernetes/kubernetes/pull/39055

**Comment by codablock** [comment]
Just a thought I had while reading this: If kubelet is unresponsive and AWS reports that it's still mounted, can't you shutdown the whole machine first before trying force detach? If kubelet is down for a longer period of time, the node is already marked as lost as I understand it and stuff get's started on new nodes, so it probably won't be that bad to shutdown/restart the machine...maybe it even recovers. So the flow would be:

1. Volume got attached/mounted to node
2. Kubelet dies and node gets "NodeLost" status.
3. Controller manager won't be able to detach now
4. Controller manager + cloud provider try to shutdown the machine
5. Detach all volumes
6. Start machine again
7. Continue normal business. Volume can now be at least reattached to another node and if we're lucky, the node even recovers

**Comment by rootfs** [comment]
The downside of shutting down the whole machine is that containers running on the bad machine and having no ebs attached are impacted.

**Comment by robdaemon** [comment]
This same behavior applies in vSphere. When a kubelet goes unresponsive, the disks stay attached. I think the suggestion of shutting down the machine is valid, because if kubelet is gone, those containers on the bad machine will be moved to another machine. Does kube-proxy continue to send service traffic to the containers on that host when kubelet is gone?

**Comment by jsravn** [comment]
Force detach will corrupt the kernel's view of devices. This usually requires a reboot to correct - otherwise any further volumes will fail to attach to that node, usually getting stuck in `attaching` state.

**Comment by johnyb79** [comment]
> Force detach will corrupt the kernel's view of devices. This usually requires a reboot to correct - otherwise any further volumes will fail to attach to that node, usually getting stuck in `attaching` state.

Is there a solution to gracefully detach a volume that got stuck in detachable state, without loosing data and make volume to be in available state? I tried to drain the node, however it didn't help:(

csi-3fb81949a44c1c2a1be8d0707807135dbc1b9333607b2b48527ef97015b947ae | grep error
    Message:  rpc error: code = Internal desc = ControllerUnpublishVolume failed with error Volume "e11a62e1-4e75-4c6d-a621-7ae6d339082e" failed to detach within the alloted time
