### ISSUE TITLE
StatusReason* consts defined in pkg/pkg/api/v1beta{1,2,3}/types.go are not used anywhere

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#3882]
We only use the StatusReason consts defined in pkg/api/types.go.
Some of the constants are duplicated in api/types and api/v1beta{1,2,3}/types.go  while some are not.

Since StatusReason\* constants defined in api/v1beta{1,2,3}/types.go are not used anywhere, can we just delete them?

**Comment by bgrant0607** [comment]
See also #1987

**Comment by odeke-em** [comment]
Is this issue still valid?
The referred issue was closed. A quick Github search for `StatusReasonUnauthorized` https://github.com/kubernetes/kubernetes/search?utf8=%E2%9C%93&q=StatusReasonUnauthorized shows usages in `pkg/api/*` and `pkg/client/restclient`.
Also from a search for `StatusDetails` (a struct that has an attribute `StatusReason`)  https://github.com/kubernetes/kubernetes/search?utf8=%E2%9C%93&q=StatusDetails shows usages in `api/swagger-spec/*` and `pkg/api/unversioned/*`

**Comment by kargakis** [comment]
Seems fixed
