### ISSUE TITLE
kubectl in-cluster config trumps command line arguments

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#38834]
Found in openshift, but I'm pretty sure the codepaths are the same.  

```
sh-4.2$ oc --token=my-users-token get user/~
NAME                                  UID       FULL NAME   IDENTITIES
system:serviceaccount:deads:default 
```

That means the token is getting ignored and in-cluster config is being used in preference to flags.

@kubernetes/sig-cli @smarterclayton

**Comment by ymqytw** [comment]
Is #38744 a similar issue?

**Comment by AdoHe** [comment]
Yep, kind of regression.

**Comment by smarterclayton** [comment]
Sigh.

**Comment by fabianofranz** [comment]
@kubernetes/kubectl

**Comment by fabianofranz** [comment]
> Is #38744 a similar issue?

Yes, most likely the same cause.

**Comment by fabianofranz** [comment]
I'm on it.

**Comment by ncdc** [comment]
Unit test :)

**Comment by pwittrock** [comment]
Probably will want to cherrypick this into 1.5.

**Comment by fabianofranz** [comment]
WIP in https://github.com/kubernetes/kubernetes/pull/39006
