### ISSUE TITLE
Release gcr.io/google_containers/kube-registry-proxy:0.4

### ISSUE THREAD

**Issue by bacongobbler** [kubernetes/kubernetes#38843]
As of #35797 the kube-registry-proxy image was bumped to 0.4 but no image has been published. Is there something I can do to help publish the image?

Thanks! :)

**Comment by lazzarello** [comment]
Confirmed. I changed the tag to 0.3 and the pods created successfully. ref: https://console.cloud.google.com/kubernetes/images/tags/kube-registry-proxy?location=GLOBAL&project=google-containers

**Comment by bacongobbler** [comment]
pinging @roberthbailey, any update on what needs to be done to get the ball rolling? I am offering free labor to either get some form of automation out the door or something as well so pinging wouldn't be necessary in the future.

**Comment by mboersma** [comment]
How can we get this image built and published? It would close a big issue for us, so we are happy to help get it over the finish line.

**Comment by roberthbailey** [comment]
Does it need to be built and pushed into gcr.io? I believe that @mikedanese has permissions to do so and might be able to help out.

**Comment by lazzarello** [comment]
@roberthbailey yes, this tag needs to be pushed to gcr.io

**Comment by bacongobbler** [comment]
@lazzarello this has already been done a week ago. All is well now.

```
><> docker pull gcr.io/google_containers/kube-registry-proxy:0.4
0.4: Pulling from google_containers/kube-registry-proxy

Digest: sha256:1040f25a5273de0d72c54865a8efd47e3292de9fb8e5353e3fa76736b854f2da
Status: Image is up to date for gcr.io/google_containers/kube-registry-proxy:0.4
```
