### ISSUE TITLE
Support self defining skydns rcache and scache options for kube-dns

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#38851]
**What:**

Provide an option for kube-dns to set skydns `rcache` and `scache` size, which can improve kube-dns performance in my environment.

**Why:**

Current implement of kube-dns doesn't support self defining these options,

https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-dns/app/server.go#L154-L157

And I find if not set, the default value for both `rcache` and `scache` are 0.

https://github.com/skynetservices/skydns/blob/master/server/config.go#L108-L113

What about add `--rcache-size` and `--scache-size` in kube-dns?

@thockin @girishkalele @bowei

**Comment by bowei** [comment]
@m1093782566 -- does the dnsmasq cache not work for you?

**Comment by m1093782566** [comment]
@bowei 

What's the relationship between skydns rcache and dnsmasq cache? Are they the same?

**Comment by bowei** [comment]
The flow of request go from DNS client <-> dnsmasq (cache) <-> kube-dns.

Any records that have non-0 TTL will be cached in dnsmasq. The question is what are the records that you want to be cached that will not be cached in dnsmasq.
