### ISSUE TITLE
'kubectl run' supports only one '--port'? 

### ISSUE THREAD

**Issue by BruceZu** [kubernetes/kubernetes#38859]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
not sure

When I deploy GitLab and Jenkins using 'kubectl run ',  it need more ports.
**What happened**:
I write it as --port=80 --port=9000
But only the last one is used

**What you expected to happen**:
I hope the  'kubectl run ' can provide more --port 

 
May be the way I wrote is not right, if this is the case then how to use the ' --port' of 'kubectl run '

**Comment by xingzhou** [comment]
@BruceZu, it's better to use yaml file and `kubectl create -f` to create a pod with multi-pod exposed, see this [reference](http://stackoverflow.com/questions/34502022/exposing-two-ports-in-google-container-engine)

**Comment by BruceZu** [comment]
Hi xingzhou,
Thank you for your help. Yeah currently I use yaml file a a workaround.

**Comment by spzala** [comment]
@BruceZu hi, thanks for reporting this issue but per what I understood with run usage is that one would use it for testing or deploying something small or troubleshooting purpose. As @xingzhou mentioned and you also tried, using the yaml file is the proper way to create deployment with multiple ports. I would of opinion that we can close this issue as, working as designed. /cc @thockin Thanks!!
