### ISSUE TITLE
i suggest k8s support non-docker app like mesos/marathon

### ISSUE THREAD

**Issue by junneyang** [kubernetes/kubernetes#38867]
https://mesosphere.github.io/marathon/

![image](https://cloud.githubusercontent.com/assets/6802322/21258365/9265179c-c3b7-11e6-8579-b5418fd7dad3.png)

**Comment by dims** [comment]
@junneyang yes, this is already being done, please see details below:

https://github.com/kubernetes/kubernetes/blob/release-1.5/docs/devel/container-runtime-interface.md
https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/container-runtime-interface-v1.md
https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr%20%20CRI%20in%3Atitle%20
https://github.com/kubernetes-incubator/cri-o

**Comment by junneyang** [comment]
@dims 
thanks, good job.
