### ISSUE TITLE
Kubelet rejects the pod scheduled on it

### ISSUE THREAD

**Issue by hex108** [kubernetes/kubernetes#38862]
We use kubernetes 1.4.0.

Kube-scheduler schedules a pod on a kubelet node. However the kubelet rejects the pod because of OutOfmemory. There is no mirror pod in the cluster and all pods has resource requests, is there any case might cause it?

Kube-scheduler log is:

>I1214 16:54:26.850177   18367 scheduler.go:96] Attempting to schedule pod: windyliu1/windyliu1-209600820-9d2c1
>I1214 16:54:26.850430   18367 priorities.go:51] Combined requested resources 7247757312 from existing pods exceeds capacity 7125270528 on node node-10-199-15-220
I1214 16:54:26.850813   18367 factory.go:582] Attempting to bind windyliu1-209600820-9d2c1 to node-10-199-15-220
> ...
>I1214 16:54:27.335881   18367 event.go:217] Event(api.ObjectReference{Kind:"Pod", Namespace:"windyliu1", Name:"windyliu1-209600820-9d2c1", UID:"43c96b33-c1d7-11e6-9e8c-b499baace206", APIVersion:"v1", ResourceVersion:"1039981", FieldPath:""}): type: 'Normal' reason: 'Scheduled' Successfully assigned windyliu1-209600820-9d2c1 to node-10-199-15-220
</quote>

Question: we could see that scheduler found there is no enough resource for the pod when making priorities to nodes. All pods has resource requests, so nodes' NonZeroRequests equals normal requests, does it mean that the allocatable resources changes between predicates and priorities?

Kubelet log is:

> I1214 16:54:46.056416   10497 kubelet.go:2318] SyncLoop (ADD, "api"): "windyliu1-209600820-9d2c1_windyliu1(43c96b33-c1d7-11e6-9e8c-b499baace206)"
> ...
> I1214 16:54:46.111987   10497 kubelet.go:2223] Predicate failed on Pod: windyliu1-209600820-9d2c1_windyliu1(43c96b33-c1d7-11e6-9e8c-b499baace206), for reason: Node didn't have enough resource: memory, requested: 134217728, used: 7113539584, capacity: 7125270528
> I1214 16:54:46.112442   10497 server.go:608] Event(api.ObjectReference{Kind:"Pod", Namespace:"windyliu1", Name:"windyliu1-209600820-9d2c1", UID:"43c96b33-c1d7-11e6-9e8c-b499baace206", APIVersion:"v1", ResourceVersion:"1053804", FieldPath:""}): type: 'Warning' reason: 'OutOfmemory'

Note: memory requested(134217728) + used(7113539584) = 7247757312 (The number has been reported by kube-scheduler in above log:  Combined requested resources 7247757312 from existing pods exceeds capacity 7125270528).

**Comment by resouer** [comment]
Did you just encountered this only once or frequently? It would be very helpful if you can find out a way to reproduce this then we can debug what's wrong here.

**Comment by hex108** [comment]
Just encountered this once under pressure test. I'll add more logs and try to reproduce it if there is no known issue for it.

**Comment by resouer** [comment]
@hex108 cool, and if you have clue to solve this, I can help to review and get it in.

**Comment by DaiHao** [comment]
I encountered this too, but cannot find the reason for now.
