### ISSUE TITLE
KubeDns breaks with StatefulSet (PetSet) / resolve ip of a pod by name is not possible

### ISSUE THREAD

**Issue by hotstepper13** [kubernetes/kubernetes#38870]
**What keywords did you search in Kubernetes issues before filing this one?** 
petset
statefulset
dns
Invalid IP Address

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT (likely)
[edit]
I found out that this seems to be an expected behavior. Nevertheless from my point of view this is a bug as if you need the IP of the pod to resolve the IP of the pod it doesnt make sense.
From the docs the correct usage to resolve a pod ip is

    <pod-ip-with-dashes-instead-of-dots>.<namespace>.pod.<cluster-domain>

**Kubernetes version** (use `kubectl version`):

    Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: On Premise installation
- **OS** (e.g. from /etc/os-release):

    NAME="Ubuntu"
    VERSION="14.04.5 LTS, Trusty Tahr"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Ubuntu 14.04.5 LTS"
    VERSION_ID="14.04"
    HOME_URL="http://www.ubuntu.com/"
    SUPPORT_URL="http://help.ubuntu.com/"
    BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

- **Kernel** (e.g. `uname -a`): 

    Linux myhostname 3.19.0-77-generic #85~14.04.1-Ubuntu SMP Mon Dec 5 11:19:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**: Ansible
- **Others**:

**What happened**:
Today I created a StatefulSet and discovered that the pods are not resolveable by dns.
Kubedns shows the following Error:

    I1216 12:57:33.011745       1 logs.go:41] skydns: error from backend: Invalid IP Address discovery.2
    I1216 12:57:33.297812       1 logs.go:41] skydns: error from backend: Invalid IP Address discovery.1
    I1216 12:57:33.297962       1 logs.go:41] skydns: error from backend: Invalid IP Address discovery.1
    I1216 12:57:44.065673       1 logs.go:41] skydns: error from backend: Invalid IP Address discovery.3
    I1216 12:57:44.065798       1 logs.go:41] skydns: error from backend: Invalid IP Address discovery.3

Info: metadata.name in this case is set to "discovery" and I am using 3 replicas.

**What you expected to happen**:
Name of the pod inside the StatefulSet should be resolveable by using

    <podname>.<namespace>.pod.<cluster-domain>

eg.

    myset-1.default.pod.cluster.local

**How to reproduce it** (as minimally and precisely as possible):
- Create stateful set
- try to resolv a single pod by kubedns

**Anything else do we need to know**:
Tested with kubedns:1.9
It seems that the name is recognized as ip address and the - is replaced by a dot

**Comment by MrHohn** [comment]
As documented on http://kubernetes.io/docs/user-guide/petset/#network-identity. The correct format to resolve the pod IPs for StatefulSet as below:
```
<pet-name>.<service-name>.<namespace>.svc.cluster.local.
```

**Comment by hotstepper13** [comment]
I have checked that approach but was only able to resolve the "pet" that was scheduled on the same server as the pod from which I did the nslookup.

**Comment by hotstepper13** [comment]
After I have seen that there is a known issue with dns in alpine images, I checked again with the busybox template form the dns admin page.

Result is the same... service is resolveable but not the "pet"

**Comment by hotstepper13** [comment]
After further investigation I have seen that kubernetes provided a resolv.conf with the entry 

    options ndots:5

changing this to 6 allows dns resolve of the "pet".
I have seen an issue regarding this option and not sure that 6 will work for all other usecases.

**Comment by hotstepper13** [comment]
Nevermind about that... the first issue was cleared by the docs. Then i ran into the same issue as here: https://github.com/kubernetes/kubernetes/issues/30076

So defining clusterIP: none makes the service names resolveable.

**Comment by MrHohn** [comment]
Good to know your issue is resolved! Yeah, a service has to be `headless` to let its backend pods to have DNS names.

**Comment by listingmirror** [comment]
@MrHohn Why? Is there a way around this?  is there a plan B to get DNS entries for pods behind a normal service?

**Comment by MrHohn** [comment]
@listingmirror I don't have the exact answer. There are relevant discussions on https://github.com/kubernetes/kubernetes/issues/39197, feel free to follow up on that thread :)
