### ISSUE TITLE
Different gateway on nodes sharing the same network will cause communication error

### ISSUE THREAD

**Issue by tmaillart** [kubernetes/kubernetes#38872]
Hi everyone!

We have setup a Kubernetes cluster following http://kubernetes.io/docs/getting-started-guides/kubeadm/ instructions, and using *calico* CNI.
Everything went great, but when we added a new network interface on the nodes and added its *gateway*, the kubernetes services were not able to communicate with each other anymore.
As a result, at boot, the node spawn the first calico container (from calico/cni:latest) successfully but the second one (spawned from quay.io/calico/node:latest) crashes endlessly because it tries to reach *calico-etcd* by dialling its _Cluster IP_ (10.96.232.136 port 6666) but the connection times out.
```
time="2016-12-16T13:51:10Z" level=info msg="Unhandled error: client: endpoint http://10.96.232.136:6666 exceeded header timeout" 
```
The only way to fix this is to remove the *gateway* of the newly created interface.

Example:

Every node are part of a single private network:
```
Master0: 192.168.0.1/16, default gateway 192.168.254.254

Node0: 192.168.1.1/16, default gateway 192.168.254.254
Node1: 192.168.1.2/16, default gateway 192.168.254.254
```
Everyting went ok, and we could access our ingress controllers on the nodes.

Then, we added an other IP address on the nodes (a public IP address), so we changed the default route.
```
Master0:
 -> 192.168.0.1/16
 -> default gateway 192.168.254.254

Node0:
 -> 192.168.1.1/16
 -> 80.10.1.10/24
 -> default gateway 80.10.1.10

Node1:
 -> 192.168.1.2/16
 -> 80.10.1.11/24
 -> default gateway 80.10.1.10
 ```

If we add the public IP on the nodes but without changing the default gateway, everything works fine

If we have no default route, the CNI crashes too, with a "no route to host" error

If we add different route on the same network (with fake gateways), everything still works ok
Example:
```
Master0: 192.168.0.1/16, default gateway 192.168.254.200

Node0: 192.168.1.1/16, default gateway 192.168.254.201
Node1: 192.168.1.2/16, default gateway 192.168.254.202
```
Will work, even if none of the default gateway are reachable.

-> It seems all members needs to have a default gateway on the same network, even if they can communicate with each other.
-> They also need a default gateway to function

**Environment**:
```bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:42:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```
- **OS** :
"Ubuntu 16.04.1 LTS (Xenial Xerus)"
- **Kernel** (e.g. `uname -a`):
Linux master0 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by caseydavenport** [comment]
@tmaillart I think what you're seeing, if I understand correctly, is that traffic from the node is trying to reach the master via a Service and as a result the source address is picked based on the default route for that node.

Since when you add the second interface, the default route is now through a different network, the traffic sent via the Service has the wrong source address and so the response traffic doesn't make it back to the sender.

Could you try setting the `--cluster-cidr=<pod_ip_range>` option on each kube-proxy?  That should ensure traffic is sent using the correct source address.

```
      --cluster-cidr string                          The CIDR range of pods in the cluster. It is used to bridge traffic coming from outside of the cluster. If not provided, no off-cluster bridging will be performed.
```

**Comment by tmaillart** [comment]
First, I'd like to thank you for your concern and responce to my issue.

**Comment by tmaillart** [comment]
First, I'd like to thank you @caseydavenport  for your concern and response to my issue.
I tried multiple times with different arguments, it looks like with the argument ```--cluster-cidr=192.168.1.1/16``` the cluster is able to start up healthily.
Once again thank you.
