### ISSUE TITLE
Volume in memory require double amount of memory requested

### ISSUE THREAD

**Issue by anioool** [kubernetes/kubernetes#38892]
Hi guys,

I want to test volume created directly in memory and I found very strange issue. Due to some reason there is hard coded (probably) that if I want to create 10 GB volume in memory, I have to request 20 GB of memory. It is not a big problem for smaller volumes, but in case when I want to create 150 GB volume,I have to request 300 GB of memory. As you know memory is very costly, so there should be a possibility to choose how much memory we want request by removing bottom limit (50%).

Thanks,
Adam

**Comment by resouer** [comment]
> Due to some reason there is hard coded (probably) that if I want to create 10 GB volume in memory, I have to request 20 GB of memory

Where is this hard coded may I ask?

**Comment by spzala** [comment]
@resouer hi, I believe we should close this issue due to lack of information per triage guidelines.  @anioool please feel free to reopen if you still seeing the issue. Thanks!
