### ISSUE TITLE
KubeDNS endpoint shows status failure 

### ISSUE THREAD

**Issue by amolsh** [kubernetes/kubernetes#38896]
Hi,
I am using kunernetes Version 1.5.0. 
Cluster is setup on local VirtualBox and consist of 1 master ,2 minion .
I followed http://kubernetes.io/docs/getting-started-guides/ubuntu/manual/ for cluster setup
and http://kubernetes.io/docs/admin/dns/ for DNS troubleshooting 

**kubectl cluster-info**
Kubernetes master is running at http://192.168.56.102:8080
KubeDNS is running at http://192.168.56.102:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at http://192.168.56.102:8080/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard

When I curl to KubeDNS,
**curl http://192.168.56.102:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns**

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"kube-dns\"",
  "reason": "ServiceUnavailable",
  "code": 503
}

**cat /etc/resolve.conf**
nameserver 127.0.1.1
nameserver 192.168.3.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5

**kubectl logs --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name) -c kubedns**

I1216 17:54:41.411199       1 dns.go:42] version: v1.6.0-alpha.0.680+3872cb93abf948-dirty
I1216 17:54:41.420803       1 server.go:107] Using https://192.168.3.1:443 for kubernetes master, kubernetes API: <nil>
I1216 17:54:41.421142       1 server.go:68] Using configuration read from ConfigMap: kube-system:kube-dns
I1216 17:54:41.421180       1 server.go:113] FLAG: --alsologtostderr="false"
I1216 17:54:41.421198       1 server.go:113] FLAG: --config-map="kube-dns"
I1216 17:54:41.421216       1 server.go:113] FLAG: --config-map-namespace="kube-system"
I1216 17:54:41.421227       1 server.go:113] FLAG: --dns-bind-address="0.0.0.0"
I1216 17:54:41.421236       1 server.go:113] FLAG: --dns-port="10053"
I1216 17:54:41.421248       1 server.go:113] FLAG: --domain="cluster.local."
I1216 17:54:41.421258       1 server.go:113] FLAG: --federations=""
I1216 17:54:41.421269       1 server.go:113] FLAG: --healthz-port="8081"
I1216 17:54:41.421278       1 server.go:113] FLAG: --kube-master-url=""
I1216 17:54:41.421292       1 server.go:113] FLAG: --kubecfg-file=""
I1216 17:54:41.421302       1 server.go:113] FLAG: --log-backtrace-at=":0"
I1216 17:54:41.421313       1 server.go:113] FLAG: --log-dir=""
I1216 17:54:41.421323       1 server.go:113] FLAG: --log-flush-frequency="5s"
I1216 17:54:41.421333       1 server.go:113] FLAG: --logtostderr="true"
I1216 17:54:41.421343       1 server.go:113] FLAG: --stderrthreshold="2"
I1216 17:54:41.421352       1 server.go:113] FLAG: --v="2"
I1216 17:54:41.421361       1 server.go:113] FLAG: --version="false"
I1216 17:54:41.421372       1 server.go:113] FLAG: --vmodule=""
I1216 17:54:41.421403       1 server.go:155] Starting SkyDNS server (0.0.0.0:10053)
I1216 17:54:41.440145       1 server.go:165] Skydns metrics enabled (/metrics:10055)
I1216 17:54:41.442643       1 dns.go:144] Starting endpointsController
I1216 17:54:41.442689       1 dns.go:147] Starting serviceController
I1216 17:54:41.445920       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I1216 17:54:41.445956       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
E1216 17:54:41.509950       1 sync.go:105] Error getting ConfigMap kube-system:kube-dns err: configmaps "kube-dns" not found
E1216 17:54:41.510279       1 dns.go:190] Error getting initial ConfigMap: configmaps "kube-dns" not found, starting with default values
I1216 17:54:41.510308       1 dns.go:163] Waiting for Kubernetes service
I1216 17:54:41.510320       1 dns.go:169] Waiting for service: default/kubernetes
I1216 17:54:41.512908       1 server.go:126] Setting up Healthz Handler (/readiness)
I1216 17:54:41.513978       1 server.go:131] Setting up cache handler (/cache)
I1216 17:54:41.514006       1 server.go:120] Status HTTP port 8081
I1216 17:54:41.522277       1 dns.go:274] New service: kubernetes-dashboard
I1216 17:54:41.522892       1 dns.go:274] New service: kubernetes
I1216 17:54:41.523085       1 dns.go:384] Added SRV record &{Host:kubernetes.default.svc.cluster.local. Port:443 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I1216 17:54:41.523238       1 dns.go:274] New service: kube-dns
I1216 17:54:41.523310       1 dns.go:384] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I1216 17:54:41.523650       1 dns.go:384] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I1216 17:59:41.453759       1 dns.go:274] New service: kubernetes-dashboard
I1216 17:59:41.453845       1 dns.go:274] New service: kubernetes
I1216 17:59:41.453864       1 dns.go:384] Added SRV record &{Host:kubernetes.default.svc.cluster.local. Port:443 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I1216 17:59:41.453882       1 dns.go:274] New service: kube-dns
I1216 17:59:41.453897       1 dns.go:384] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I1216 17:59:41.453947       1 dns.go:384] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I1216 18:04:41.453987       1 dns.go:274] New service: kubernetes-dashboard
I1216 18:04:41.454115       1 dns.go:274] New service: kubernetes
I1216 18:04:41.454148       1 dns.go:384] Added SRV record &{Host:kubernetes.default.svc.cluster.local. Port:443 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I1216 18:04:41.454182       1 dns.go:274] New service: kube-dns
I1216 18:04:41.454211       1 dns.go:384] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I1216 18:04:41.454238       1 dns.go:384] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I1216 18:09:41.454330       1 dns.go:274] New service: kubernetes-dashboard
I1216 18:09:41.454430       1 dns.go:274] New service: kubernetes
I1216 18:09:41.454456       1 dns.go:384] Added SRV record &{Host:kubernetes.default.svc.cluster.local. Port:443 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I1216 18:09:41.454480       1 dns.go:274] New service: kube-dns
I1216 18:09:41.454501       1 dns.go:384] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I1216 18:09:41.454520       1 dns.go:384] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I1216 18:14:41.454982       1 dns.go:274] New service: kubernetes-dashboard
I1216 18:14:41.455085       1 dns.go:274] New service: kubernetes
I1216 18:14:41.455111       1 dns.go:384] Added SRV record &{Host:kubernetes.default.svc.cluster.local. Port:443 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I1216 18:14:41.455136       1 dns.go:274] New service: kube-dns
I1216 18:14:41.455155       1 dns.go:384] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I1216 18:14:41.455173       1 dns.go:384] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I1216 18:19:41.455905       1 dns.go:274] New service: kubernetes
I1216 18:19:41.456053       1 dns.go:384] Added SRV record &{Host:kubernetes.default.svc.cluster.local. Port:443 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I1216 18:19:41.456097       1 dns.go:274] New service: kube-dns
I1216 18:19:41.456163       1 dns.go:384] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I1216 18:19:41.456195       1 dns.go:384] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}

**kubectl logs --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name) -c dnsmasq**

dnsmasq[1]: started, version 2.76 cachesize 1000
dnsmasq[1]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
dnsmasq[1]: using nameserver 127.0.0.1#10053
dnsmasq[1]: read /etc/hosts - 7 addresses

**kubectl logs --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name) -c healthz**
 no output

**kubectl get svc --namespace=kube-system**
NAME                   CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
kube-dns               192.168.3.10    <none>        53/UDP,53/TCP   3d
kubernetes-dashboard   192.168.3.154   <none>        80/TCP          3d

**kubectl get ep kube-dns --namespace=kube-system**
NAME       ENDPOINTS                       AGE
kube-dns   172.16.74.3:53,172.16.74.3:53   3d

**kubectl exec busybox -- nslookup kubernetes.default**

nslookup: can't resolve 'kubernetes.default'
Server:    192.168.3.10
Address 1: 192.168.3.10

**Comment by MrHohn** [comment]
Hi, seems like you have two nameservers in the `/etc/resolve.conf`. I think removing the first line `nameserver 127.0.1.1` and use `kube-dns` as the only nameserver may solve your issue.

**Comment by MrHohn** [comment]
And the output of `kubectl get ep kube-dns` for kube-dns seems correct.

**Comment by amolsh** [comment]
I tried that, no luck. Instead it stopped my internet connection

**Comment by MrHohn** [comment]
> Instead it stopped my internet connection

Weird, I'm not sure what is the dependency between the nameserver setup and internet connection.

Could you try `nslookup -debug` or `dig +showsearch` to see if search path are respected?. May also try nslookup for FQDNs(like `kubernetes.default.svc.cluster.local`).

**Comment by MrHohn** [comment]
And for confirming if the endpoint is exposed in service, try replacing the nameserver by the dns pod ip:
```
nslookup kubernetes.default 172.16.74.3
```

**Comment by amolsh** [comment]
**kubectl exec busybox -- nslookup kubernetes.default 172.16.74.3**
Server:    172.16.74.3
Address 1: 172.16.74.3
nslookup: can't resolve 'kubernetes.default'

**kubectl exec busybox -- nslookup kubernetes.default.svc.cluster.local**
Server:    192.168.3.10
Address 1: 192.168.3.10
nslookup: can't resolve 'kubernetes.default.svc.cluster.local'

**dig +showsearch**
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8613
;; flags: qr rd ra; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 27

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;.				IN	NS

;; ANSWER SECTION:
.			474676	IN	NS	i.root-servers.net.
.			474676	IN	NS	m.root-servers.net.
.			474676	IN	NS	g.root-servers.net.
.			474676	IN	NS	l.root-servers.net.
.			474676	IN	NS	a.root-servers.net.
.			474676	IN	NS	f.root-servers.net.
.			474676	IN	NS	e.root-servers.net.
.			474676	IN	NS	c.root-servers.net.
.			474676	IN	NS	d.root-servers.net.
.			474676	IN	NS	b.root-servers.net.
.			474676	IN	NS	k.root-servers.net.
.			474676	IN	NS	h.root-servers.net.
.			474676	IN	NS	j.root-servers.net.

;; ADDITIONAL SECTION:
g.root-servers.net.	129086	IN	A	192.112.36.4
g.root-servers.net.	474678	IN	AAAA	2001:500:12::d0d
e.root-servers.net.	129086	IN	A	192.203.230.10
e.root-servers.net.	474678	IN	AAAA	2001:500:a8::e
k.root-servers.net.	129086	IN	A	193.0.14.129
k.root-servers.net.	129086	IN	AAAA	2001:7fd::1
l.root-servers.net.	129086	IN	A	199.7.83.42
l.root-servers.net.	129086	IN	AAAA	2001:500:9f::42
a.root-servers.net.	561086	IN	A	198.41.0.4
a.root-servers.net.	129086	IN	AAAA	2001:503:ba3e::2:30
j.root-servers.net.	129086	IN	A	192.58.128.30
j.root-servers.net.	129086	IN	AAAA	2001:503:c27::2:30
m.root-servers.net.	129086	IN	A	202.12.27.33
m.root-servers.net.	129086	IN	AAAA	2001:dc3::35
i.root-servers.net.	129086	IN	A	192.36.148.17
i.root-servers.net.	129086	IN	AAAA	2001:7fe::53
h.root-servers.net.	129086	IN	A	198.97.190.53
h.root-servers.net.	129086	IN	AAAA	2001:500:1::53
b.root-servers.net.	129086	IN	A	192.228.79.201
b.root-servers.net.	129086	IN	AAAA	2001:500:84::b
d.root-servers.net.	129086	IN	A	199.7.91.13
d.root-servers.net.	129086	IN	AAAA	2001:500:2d::d
f.root-servers.net.	129086	IN	A	192.5.5.241
f.root-servers.net.	129086	IN	AAAA	2001:500:2f::f
c.root-servers.net.	129086	IN	A	192.33.4.12
c.root-servers.net.	129086	IN	AAAA	2001:500:2::c

;; Query time: 45 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Tue Dec 20 23:33:04 IST 2016
;; MSG SIZE  rcvd: 811

**Comment by MrHohn** [comment]
What about `kubectl exec busybox -- nslookup kubernetes.default.svc.cluster.local 172.16.74.3` and `kubectl exec busybox -- dig +showsearch kubernetes.default` ?

Are you executing this commands with two nameservers in resolv.conf or just one nameserver?
And how do you judge the internet is down when the first nameserver was removed?

**Comment by amolsh** [comment]
**cat /etc/resolve.conf**
nameserver 192.168.3.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5

**kubectl exec busybox -- nslookup kubernetes.default.svc.cluster.local 172.16.74.3**
Server:    172.16.74.3
Address 1: 172.16.74.3
nslookup: can't resolve 'kubernetes.default.svc.cluster.local'

**kubectl exec busybox -- dig +showsearch kubernetes.default**
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"dig\\\": executable file not found in $PATH\"\n"

**Comment by MrHohn** [comment]
> After removing 127.0.1.1 from nameserver, I can not browse anything on browser.

Wait, I thought you were talking about the `/etc/resolv.conf` in the container, which should not have any effect on neither the node nor your computer browser. Could you please show me the content in container's `/etc/resolv.conf`? Like below:
```
kubectl exec busybox -- cat /etc/resolv.conf
```

And because none of the `nslookup` commands you ran succeeded, even you were not going through k8s service, I wonder is the networking setup correctly? All dns logs seems correct, so the problem should be in either dns configuration or networking.

Have you tried creating other services with backends and accessing it on another independent pod?

**Comment by zhuqinghua** [comment]
i have the same problem, dnsmasq can't start

**Comment by MrHohn** [comment]
@zhuqinghua Could you provide more details? "dnsmasq can't start" does not seem like the same problem.

**Comment by bowei** [comment]
@zhuqinghua: Can you file a new issue with your bug? It is somewhat confusing to add it onto this thread which may or may not be related.

**Comment by yns-libn** [comment]
I have the same problem,  I think,  "https://192.168.3.1:443 " is not a k8s endpoints


[root@localhost k8s_dns]# kubectl exec busybox -- cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.137.254.254
options ndots:5

**Comment by bowei** [comment]
@yns-libn -- what is the specific issue? You will need to post more information (Kubernetes version, what the failure is, what you are trying to do). It would also help to use a new issue, rather than attaching it to this one, which already has two different topics associated with it.

**Comment by yns-libn** [comment]
@bowei 
Sorry, I have solved the problem of not being able to access DNS, but the method is not very good, I used the old skydns to deploy my cluster , and in this issue "ConfigMap: kube-system:kube-dns", I don't know what should be set up, there is no specific explanation in the DNS installation instructions, but I think if the problem is solved, the DNS problem will be solved

**Comment by MrHohn** [comment]
Hi @yns-libn, how did the kube-dns ConfigMap cause problem? If there is not kube-dns ConfigMap exist, the latest kube-dns would fall back to use the parameters given by the `--federations` flag. You shouldn't be worried about it if you are not using the federation feature.

**Comment by yns-libn** [comment]
Hi  @MrHohn 
Thank you for your reply. Have you used k8s1.5.1's DNS in your cluster? I've tried many times without success

**Comment by MrHohn** [comment]
@yns-libn Yes, we have a set of e2e tests that ensure kube-dns works in 1.5. Have you found any related error message  from kube-dns's logs?

**Comment by zouyee** [comment]
when my cluster lost one host(agent),kubedns pods changed status from running to unknown,then rc create  the same pods with unknown status pods which could not be deleted,in the end,i got this problem

**Comment by thinkhard-j-park** [comment]
Hi,

I got same issues. I followed portable docker node cluster: https://kubernetes.io/docs/getting-started-guides/docker-multinode/

**$kubectl logs --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name) -c kubedns**
```
I0305 12:54:02.630351       1 dns.go:42] version: v1.6.0-alpha.0.680+3872cb93abf948-dirty
I0305 12:54:02.630957       1 server.go:107] Using https://10.0.0.1:443 for kubernetes master, kubernetes API: <nil>
I0305 12:54:02.632205       1 server.go:68] Using configuration read from ConfigMap: kube-system:kube-dns
I0305 12:54:02.632302       1 server.go:113] FLAG: --alsologtostderr="false"
I0305 12:54:02.632364       1 server.go:113] FLAG: --config-map="kube-dns"
I0305 12:54:02.632398       1 server.go:113] FLAG: --config-map-namespace="kube-system"
I0305 12:54:02.632443       1 server.go:113] FLAG: --dns-bind-address="0.0.0.0"
I0305 12:54:02.632470       1 server.go:113] FLAG: --dns-port="10053"
I0305 12:54:02.632518       1 server.go:113] FLAG: --domain="cluster.local."
I0305 12:54:02.632550       1 server.go:113] FLAG: --federations=""
I0305 12:54:02.632579       1 server.go:113] FLAG: --healthz-port="8081"
I0305 12:54:02.632625       1 server.go:113] FLAG: --kube-master-url=""
I0305 12:54:02.632653       1 server.go:113] FLAG: --kubecfg-file=""
I0305 12:54:02.632694       1 server.go:113] FLAG: --log-backtrace-at=":0"
I0305 12:54:02.632722       1 server.go:113] FLAG: --log-dir=""
I0305 12:54:02.632769       1 server.go:113] FLAG: --log-flush-frequency="5s"
I0305 12:54:02.632800       1 server.go:113] FLAG: --logtostderr="true"
I0305 12:54:02.632844       1 server.go:113] FLAG: --stderrthreshold="2"
I0305 12:54:02.632873       1 server.go:113] FLAG: --v="0"
I0305 12:54:02.632898       1 server.go:113] FLAG: --version="false"
I0305 12:54:02.632945       1 server.go:113] FLAG: --vmodule=""
I0305 12:54:02.633030       1 server.go:155] Starting SkyDNS server (0.0.0.0:10053)
I0305 12:54:02.636926       1 server.go:165] Skydns metrics enabled (/metrics:10055)
I0305 12:54:02.643661       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0305 12:54:02.643752       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
E0305 12:54:02.790335       1 sync.go:105] Error getting ConfigMap kube-system:kube-dns err: configmaps "kube-dns" not found
E0305 12:54:02.790427       1 dns.go:190] Error getting initial ConfigMap: configmaps "kube-dns" not found, starting with default values
I0305 12:54:02.794557       1 server.go:126] Setting up Healthz Handler (/readiness)
I0305 12:54:02.794627       1 server.go:131] Setting up cache handler (/cache)
I0305 12:54:02.794673       1 server.go:120] Status HTTP port 8081
```

**$ cat /etc/resolv.conf** 
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 1.214.68.2
nameserver 61.41.153.2
```

**Comment by tuannvm** [comment]
Me too.
Error log from kube-dns
```
2017-03-15T15:19:52.163347172Z I0315 15:19:52.163242       1 server.go:155] Starting SkyDNS server (0.0.0.0:10053)
2017-03-15T15:19:52.164927144Z I0315 15:19:52.164786       1 server.go:165] Skydns metrics enabled (/metrics:10055)
2017-03-15T15:19:52.165257920Z I0315 15:19:52.165120       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
2017-03-15T15:19:52.165268046Z I0315 15:19:52.165135       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
2017-03-15T15:19:52.193825092Z E0315 15:19:52.193647       1 sync.go:105] Error getting ConfigMap kube-system:kube-dns err: configmaps "kube-dns" not found
2017-03-15T15:19:52.193836343Z E0315 15:19:52.193659       1 dns.go:190] Error getting initial ConfigMap: configmaps "kube-dns" not found, starting with default values
2017-03-15T15:19:52.195702945Z I0315 15:19:52.195571       1 server.go:126] Setting up Healthz Handler (/readiness)
2017-03-15T15:19:52.195714087Z I0315 15:19:52.195589       1 server.go:131] Setting up cache handler (/cache)
2017-03-15T15:19:52.195717153Z I0315 15:19:52.195593       1 server.go:120] Status HTTP port 8081
2017-03-15T15:53:38.203731047Z W0315 15:53:38.203540       1 reflector.go:315] pkg/dns/config/sync.go:114: watch of *api.ConfigMap ended with: too old resource version: 5 (2385)
```

**Comment by fujexo** [comment]
Unfortunately, I have the same problem.
I've installed my cluster according to https://kubernetes.io/docs/getting-started-guides/kubeadm/ with `kubeadm init`, then deployed calico, added two nodes and after some time, kube-dns is failing with the same errors reported above.

* kube-dns container
```
[root@kubernetes-master-01 ~]# kubectl logs --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name) -c kube-dns
I0315 17:35:51.943946       1 dns.go:42] version: v1.6.0-alpha.0.680+3872cb93abf948-dirty
I0315 17:35:51.946198       1 server.go:107] Using https://10.96.0.1:443 for kubernetes master, kubernetes API: <nil>
I0315 17:35:51.948414       1 server.go:68] Using configuration read from ConfigMap: kube-system:kube-dns
I0315 17:35:51.948482       1 server.go:113] FLAG: --alsologtostderr="false"
I0315 17:35:51.948500       1 server.go:113] FLAG: --config-map="kube-dns"
I0315 17:35:51.948508       1 server.go:113] FLAG: --config-map-namespace="kube-system"
I0315 17:35:51.948513       1 server.go:113] FLAG: --dns-bind-address="0.0.0.0"
I0315 17:35:51.948518       1 server.go:113] FLAG: --dns-port="10053"
I0315 17:35:51.948526       1 server.go:113] FLAG: --domain="cluster.local."
I0315 17:35:51.948534       1 server.go:113] FLAG: --federations=""
I0315 17:35:51.948545       1 server.go:113] FLAG: --healthz-port="8081"
I0315 17:35:51.948553       1 server.go:113] FLAG: --kube-master-url=""
I0315 17:35:51.948562       1 server.go:113] FLAG: --kubecfg-file=""
I0315 17:35:51.948569       1 server.go:113] FLAG: --log-backtrace-at=":0"
I0315 17:35:51.949205       1 server.go:113] FLAG: --log-dir=""
I0315 17:35:51.950113       1 server.go:113] FLAG: --log-flush-frequency="5s"
I0315 17:35:51.950124       1 server.go:113] FLAG: --logtostderr="true"
I0315 17:35:51.950131       1 server.go:113] FLAG: --stderrthreshold="2"
I0315 17:35:51.950137       1 server.go:113] FLAG: --v="2"
I0315 17:35:51.950142       1 server.go:113] FLAG: --version="false"
I0315 17:35:51.950156       1 server.go:113] FLAG: --vmodule=""
I0315 17:35:51.950231       1 server.go:155] Starting SkyDNS server (0.0.0.0:10053)
I0315 17:35:51.975554       1 server.go:165] Skydns metrics enabled (/metrics:10055)
I0315 17:35:51.975660       1 dns.go:144] Starting endpointsController
I0315 17:35:51.975668       1 dns.go:147] Starting serviceController
I0315 17:35:51.983544       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0315 17:35:51.983569       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
E0315 17:35:52.056150       1 sync.go:105] Error getting ConfigMap kube-system:kube-dns err: configmaps "kube-dns" not found
E0315 17:35:52.056183       1 dns.go:190] Error getting initial ConfigMap: configmaps "kube-dns" not found, starting with default values
I0315 17:35:52.056212       1 dns.go:163] Waiting for Kubernetes service
I0315 17:35:52.056221       1 dns.go:169] Waiting for service: default/kubernetes
I0315 17:35:52.064952       1 dns.go:274] New service: prometheus-svc
I0315 17:35:52.065170       1 dns.go:274] New service: kubernetes
I0315 17:35:52.065224       1 dns.go:384] Added SRV record &{Host:kubernetes.default.svc.cluster.local. Port:443 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I0315 17:35:52.065274       1 dns.go:274] New service: kube-dns
I0315 17:35:52.065312       1 dns.go:384] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I0315 17:35:52.065345       1 dns.go:384] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I0315 17:35:52.065380       1 dns.go:274] New service: calico-etcd
I0315 17:35:52.066928       1 server.go:126] Setting up Healthz Handler (/readiness)
I0315 17:35:52.066952       1 server.go:131] Setting up cache handler (/cache)
I0315 17:35:52.066959       1 server.go:120] Status HTTP port 8081
I0315 17:36:59.966346       1 server.go:150] Ignoring signal terminated (can only be terminated by SIGKILL)
```

* dnsmasq container
```
[root@kubernetes-master-01 ~]# kubectl logs --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name) -c dnsmasq
dnsmasq[1]: started, version 2.76 cachesize 1000
dnsmasq[1]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
dnsmasq[1]: using nameserver 127.0.0.1#10053
dnsmasq[1]: read /etc/hosts - 7 addresses
```

* dnsmasq-metrics container
```
[root@kubernetes-master-01 ~]# kubectl logs --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name) dnsmasq-metrics
ERROR: logging before flag.Parse: I0315 16:09:35.539985       1 main.go:38] dnsmasq-metrics v1.0
ERROR: logging before flag.Parse: I0315 16:09:35.540354       1 server.go:44] Starting server (options {DnsMasqPort:53 DnsMasqAddr:127.0.0.1 DnsMasqPollIntervalMs:5000 PrometheusAddr:0.0.0.0 PrometheusPort:10054 PrometheusPath:/metrics PrometheusNamespace:dnsmasq PrometheusSubsystem:cache})
ERROR: logging before flag.Parse: W0315 16:11:40.736912       1 server.go:53] Error getting metrics from dnsmasq: read udp 127.0.0.1:53737->127.0.0.1:53: read: connection refused
ERROR: logging before flag.Parse: W0315 16:11:45.738423       1 server.go:53] Error getting metrics from dnsmasq: read udp 127.0.0.1:40959->127.0.0.1:53: read: connection refused
ERROR: logging before flag.Parse: W0315 16:11:50.739004       1 server.go:53] Error getting metrics from dnsmasq: read udp 127.0.0.1:37299->127.0.0.1:53: read: connection refused
[...]
```

* healthz container
```
[root@kubernetes-master-01 ~]# kubectl logs --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name) healthz
2017/03/15 16:10:29 Healthz probe on /healthz-kubedns error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.cluster.local'
, at 2017-03-15 16:10:28.868881695 +0000 UTC, error exit status 1
2017/03/15 16:10:29 Healthz probe on /healthz-dnsmasq error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.cluster.local'
, at 2017-03-15 16:10:28.868685929 +0000 UTC, error exit status 1
2017/03/15 16:10:39 Healthz probe on /healthz-dnsmasq error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.cluster.local'
, at 2017-03-15 16:10:38.866432671 +0000 UTC, error exit status 1
2017/03/15 16:10:39 Healthz probe on /healthz-kubedns error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.cluster.local'
, at 2017-03-15 16:10:38.867720361 +0000 UTC, error exit status 1
[...]
```

**Comment by bowei** [comment]
@tuannvm @fujexo @thinkhard-j-park 

Those log messages are benign and should be logged at INFO level.

I suspect there is something else that is the cause of your DNS issues. Please open a new issue with specific details about your setup. Adding to this thread will be quite confusing as your environments and setup seem to be quite different.

**Comment by bowei** [comment]
/close

I'm closing this issue -- please file a new issue specific to your problem
