### ISSUE TITLE
pkg/volume/util util.Find can leave behind zombie wc processes

### ISSUE THREAD

**Issue by sykesm** [kubernetes/kubernetes#38894]
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+82450d0", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"not a git tree", BuildDate:"2016-12-14T04:09:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: minikube
- **OS** (e.g. from /etc/os-release): Boot2Docker
- **Kernel** (e.g. `uname -a`): 4.4.14-boot2docker
- **Install tools**:
- **Others**:

**What happened**:
I noticed hundreds and hundreds of defunct `wc` processes running on the minikube system. It turns out that unsupported arguments were provided to `find` which caused the function to return without waiting for `wc` to complete.  The logs contained the following:

```
I1216 18:47:37.596117    2342 fs.go:495] killing cmd [find /mnt/sda1/var/lib/docker/aufs/diff/1e45bc220812a43c9b04686589c68e805e787bf8d52968dc2e845c84332b94f3 -xdev -printf .], and cmd [wc -c] due to timeout(2m0s)
E1216 18:47:38.456223    2342 fsHandler.go:121] failed to collect filesystem stats - rootDiskErr: <nil>, rootInodeErr: cmd [find /mnt/sda1/var/lib/docker/aufs/diff/0fd0a856472f468875ebaa014e8eab8c9995f8df8f7a9578c45a6b707916d03f -xdev -printf .] failed. stderr: find: unrecognized: -printf
BusyBox v1.24.2 (2016-05-16 13:28:30 UTC) multi-call binary.

Usage: find [-HL] [PATH]... [OPTIONS] [ACTIONS]

Search for files and perform actions on them.
First failed action stops processing of current file.
Defaults: PATH is current directory, action is '-print'

	-L,-follow	Follow symlinks
	-H		...on command line only
	-xdev		Don't descend directories on other filesystems
	-maxdepth N	Descend at most N levels. -maxdepth 0 applies
			actions to command line arguments only
	-mindepth N	Don't act on first N levels
	-depth		Act on directory *after* traversing it

Actions:
	( ACTIONS )	Group actions for -o / -a
	! ACT		Invert ACT's success/failure
	ACT1 [-a] ACT2	If ACT1 fails, stop, else do ACT2
	ACT1 -o ACT2	If ACT1 succeeds, stop, else do ACT2
			Note: -a has higher priority than -o
	-name PATTERN	Match file name (w/o directory name) to PATTERN
	-iname PATTERN	Case insensitive -name
	-path PATTERN	Match path to PATTERN
	-ipath PATTERN	Case insensitive -path
	-regex PATTERN	Match path to regex PATTERN
	-type X		File type is X (one of: f,d,l,b,c,...)
	-perm MASK	At least one mask bit (+MASK), all bits (-MASK),
			or exactly MASK bits are set in file's mode
	-mtime DAYS	mtime is greater than (+N), less than (-N),
			or exactly N days in the past
	-mmin MINS	mtime is greater than (+N), less than (-N),
			or exactly N minutes in the past
	-newer FILE	mtime is more recent than FILE's
	-inum N		File has inode number N
	-user NAME/ID	File is owned by given user
	-group NAME/ID	File is owned by given group
	-size N[bck]	File size is N (c:bytes,k:kbytes,b:512 bytes(def.))
			+/-N: file size is bigger/smaller than N
	-links N	Number of links is greater than (+N), less than (-N),
			or exactly N
	-prune		If current file is directory, don't descend into it
If none of the following actions is specified, -print is assumed
	-print		Print file name
	-print0		Print file name, NUL terminated
	-exec CMD ARG ;	Run CMD with all instances of {} replaced by
			file name. Fails if CMD exits with nonzero
	-exec CMD ARG + Run CMD with {} replaced by list of file names
	-delete		Delete current file/directory. Turns on -depth option
; err: exit status 1, extraDiskErr: <nil>
E1216 18:47:41.968845    2342 fsHandler.go:121] failed to collect filesystem stats - rootDiskErr: <nil>, rootInodeErr: cmd [find /mnt/sda1/var/lib/docker/aufs/diff/412563fbaa776b51bbb938008643e68034baee0619c772ec620b3b8185247dd9 -xdev -printf .] failed. stderr: find: unrecognized: -printf
BusyBox v1.24.2 (2016-05-16 13:28:30 UTC) multi-call binary.
```

**What you expected to happen**:
The code that started the process should get the return status via wait - even when there's an error.

**How to reproduce it** (as minimally and precisely as possible):
Start minikube. I have heapster enabled - which has the same code.

**Anything else do we need to know**:
The `find` implementation used by minikube is from busybox. That implementation does not support the `-dev` and `-printf` options GNU find that the code is relying on.

The problematic find code is use in both cadvsior and in pkg/volume/util. Happy to PR fixes to one or both.

**Comment by brendandburns** [comment]
@sykesm a PR to fix these would be great.

Thanks!

**Comment by sykesm** [comment]
For reference, google/cadvisor#1556 is the upstream issue.

**Comment by euank** [comment]
It's possible for this to occur in other situations as well.

I'm not certain how I ended up with 1200 defunct wc's in a couple days, but my kubelet definitely has a fully featured find, so it's something different.

Possibly it's a result of me restarting the kubelet during a "find" execution, but I'm not sure.

**Comment by kargakis** [comment]
@kubernetes/sig-storage-misc @kubernetes/sig-node-misc

**Comment by kargakis** [comment]
Maybe a naive question but why are we using `wc` instead of handling this in Go? I am not sure that binary dependencies are a problem atm and ofc `wc` is everywhere but I would expect the same functionality to be a couple of lines in Go.

**Comment by euank** [comment]
@kargakis the fix was to replace 'wc' with go code (effectively `len(str)`), since indeed go is capable of determining the length of a string.

I assume that it was originally using wc because the author of the code was naively porting a working line of bash and wasn't so familiar with go.
