### ISSUE TITLE
Authorization Policy should be able to require "trusted images"

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#3889]
First, need to define what a "trusted" image is:
1. docker image name has some prefix.
2. define an "image" resource, which has labels (as has previously been proposed, and may already exist in openshift) 

Suggest definitely doing the first, since this is composible with people's existing use of docker.  Also consider second if openShift folks want it.

Second, need a way to further restrict a policy which allows pod creation to require all images to be trusted.   Amazon IAM has "Cond" sections in their policy, and they predefine certain condition matchers.  

We might have something like this:

```
{User:"alice", Kind:"pods", Namespace:"prod", Conds: [{Cond:"ContImagesHaveImagePrefix", Arg1:"quay.io/alicecorp/trusted"}]}
```

**Comment by erictune** [comment]
The motivating use case is a SoX-type requirement that "production" pods have images built using a approved process, but still allowing developers to use ad-hoc builds in "non-production" scenarios.

**Comment by erictune** [comment]
Third, we need  ways to define which pods such a condition applies to and which it doesn't.   Options:  
 - all pods in namespace restricted;  
 - any pod asking for a security-context is restricted, 
 - any pod with label "prod" needs to meed the condition

Security context means the work that @smarterclayton and @csrwng are doing.   I think initially, they are going to have 1 default security context in a namespace, and later expand to multiple choices. 



So, we need the policy to also match the pod that alice is creating as having a certain label or

**Comment by erictune** [comment]
Security contexts #3868 
Need to go read that now.

**Comment by erictune** [comment]
Related discussion of Build Service and policy in #3759

**Comment by liggitt** [comment]
is this satisfied by the ImagePolicyWebhook admission plugin?
