### ISSUE TITLE
kubectl get broken for list

### ISSUE THREAD

**Issue by ymqytw** [kubernetes/kubernetes#38907]
kubectl get -o yaml|json is broken for list.

How to reproduce:
Create multiple resource from list: `kubectl create -f https://raw.githubusercontent.com/kubernetes/kubernetes/master/hack/testdata/multi-resource-list.json`.

Get the resources back: `kubectl get -o yaml -f https://raw.githubusercontent.com/kubernetes/kubernetes/master/hack/testdata/multi-resource-list.json`

Output:
```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-12-16T22:09:53Z
  labels:
    app: mock
  name: mock
  namespace: default
  resourceVersion: "387943"
  selfLink: /api/v1/namespaces/default/services/mock
  uid: 5edec4bb-c3dc-11e6-aa89-42010a800002
spec:
  clusterIP: 10.0.160.121
  ports:
  - port: 99
    protocol: TCP
    targetPort: 9949
  selector:
    app: mock
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

Only the first resource get printed out.

@kubernetes/kubectl @kubernetes/sig-cli-misc

**Comment by ymqytw** [comment]
@fabianofranz maybe we need to include this in #38768?

**Comment by AdoHe** [comment]
@ymqytw what't the get response? I mean we really get all resources or just issue with printer.

**Comment by ymqytw** [comment]
@AdoHe I guess it's printer's issue. But I'm not sure how printer works for list of resources.
We get all the resources. There are 2 GET requests:
`api/v1/namespaces/default/services/mock`
`api/v1/namespaces/default/replicationcontrollers/mock`
But the printer only prints out `service`.

**Comment by fabianofranz** [comment]
> maybe we need to include this in #38768?

Done.

**Comment by smarterclayton** [comment]
Is this also broken in 1.5, i.e. a regression?

**Comment by ymqytw** [comment]
>Is this also broken in 1.5, i.e. a regression?

Yes, it is also broke in 1.5.

**Comment by smarterclayton** [comment]
Setting priority and adding cherry pick candidate.  This would break people using scripting.

**Comment by smarterclayton** [comment]
Can someone take ownership to fixing this and getting it into the 1.5.x track?

**Comment by AdoHe** [comment]
@smarterclayton I would fix this today.

**Comment by AdoHe** [comment]
@kubernetes/sig-cli-misc the root cause is: we retrieve a list from server, and then we flatten the list , get multiple `Info`, but `singular` [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/get.go#L327) is `true`, so we just print the first object.

**Comment by ncdc** [comment]
Looks like this behavior was changed in #36085. I think the fix is to check `len(infos)` instead of looking at singular, as singular is going to report `true` when you do `kubectl get -f <file>` (and it looks like that hasn't changed from before).

**Comment by smarterclayton** [comment]
And add a test so it doesn't break again! :)

**Comment by ncdc** [comment]
I can fix this if you would like me to, @AdoHe?

**Comment by ncdc** [comment]
My suggestion [above](https://github.com/kubernetes/kubernetes/issues/38907#issuecomment-268300273) breaks other tests. Trying to figure out what's up.

**Comment by ncdc** [comment]
Ah I see what it is. We still need to check singular and go into the list code path if it's `!singular || len(infos) > 1`

**Comment by AdoHe** [comment]
@ncdc thanks very much :)
