### ISSUE TITLE
azure Feature Request: Services with LoadBalancer should allow us to configure the azure lb with a private IP

### ISSUE THREAD

**Issue by djsly** [kubernetes/kubernetes#38901]
**Kubernetes version**
1.4.6

**Environment**:
- **Cloud provider or hardware configuration**: azure
- **OS** (e.g. from /etc/os-release): centOs 7.1
- **Install tools**: custom

We have services that require load balancing internally, with request coming from the outside of kubernetes but still from inside the azure vnet. (e.g. jumpbox)

Unfortunalety we cannot proxy them through the apiserver since they are at the tcp level. 

cc: @colemickens

**Comment by colemickens** [comment]
I think this can be easily accommodated, I'm trying to remember if there's an annotation that hints to the cloudprovider to make an internal LB instead. Let me look around and get back.

**Comment by colemickens** [comment]
Related:

* AWS's annotation: https://github.com/kubernetes/kubernetes/blob/69cd805532221c6bcbe8c653d05ccf96884cf7cd/pkg/cloudprovider/providers/aws/aws.go#L73-L77

* Related PR that changes semantics of the AWS annotations slightly: https://github.com/kubernetes/kubernetes/pull/38636

I'll prototype this with the AWS annotation and semantics and then we can discuss having a more generic annotations that could be supported by AWS/Azure/others.

**Comment by dcieslak19973** [comment]
Pull request https://github.com/kubernetes/kubernetes/pull/43510 seems to be stuck with one failing task. Any suggestions for helping @karataliu get it to pass the automation checks and then merged?
