### ISSUE TITLE
We should gather logs / information from the xenstore interface (on AWS)

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#38915]
When diagnosing EBS issues, @guoshimin posted this comment describing getting additional information from xenstore.  We should investigate that further and collect those logs and/or use them in the node problem detector.

https://github.com/kubernetes/kubernetes/issues/31891#issuecomment-257766760

```
$ sudo xenstore ls error/device/vbd
268449280 = ""
 error = "16 Device in use; refusing to close"
268448768 = ""
 error = "16 Device in use; refusing to close"
268449024 = ""
 error = "16 Device in use; refusing to close"
```

**Comment by chrislovecnm** [comment]
cc @kubernetes/sig-aws

**Comment by wenjianhn** [comment]
K8s should watch the xenstore event and some retry logic here.
