### ISSUE TITLE
AWS: Use current node subnet for choosing ELB net

### ISSUE THREAD

**Issue by tylerFowler** [kubernetes/kubernetes#38910]
I'm trying to use the `LoadBalancer` type on a service and discovered that it couldn't be created because - to my surprise - it's not using the correct AWS subnet meant for resources in that particular cluster. My current setup is that we use 1 VPC for all of our clusters and break each service cluster out into different subnets. So this particular k8s cluster is on one subnet while another (smaller) cluster is on a smaller subnet causing Kubernetes to complain that there aren't enough free IP's in that subnet.

I had read somewhere that Kubernetes will randomly choose a subnet inside of the current VPC as long as it's public. But EC2 instances definitely give you the subnet they're attached to by hitting `http://169.254.169.254/latest/meta-data/network/interfaces/macs/<some-mac>/subnet-id` so why not just use that value if it's public?

**Kubernetes version** (use `kubectl version`):
```go
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+82450d0", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"not a git tree", BuildDate:"2016-12-14T04:09:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6+coreos.0", GitCommit:"ec2b52fabadf824a42b66b6729fe4cff2c62af8c", GitTreeState:"clean", BuildDate:"2016-11-14T19:42:00Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS 1235.2.0

**Comment by hjacobs** [comment]
@tylerFowler the Kubernets AWS integration relies on the `KubernetesCluster` tag to find the correct subnets. We also have (different to yours) issues with that as we want to use multiple clusters in the same subnet(s), see #35052.

**Comment by tylerFowler** [comment]
The tag is definitely another issue altogether, but I guess to narrow down the wanted effect for this issue it would be to have a more sensible default with the tag being available for overrides.

**Comment by michaelajr** [comment]
Things like ELBs should not need to reference tags on subnets since the state store knows about all the zones and subnets. Just use the values there. This is especially true if I bring my own subnets. I do not want to tag then so the ELBs will work, and then have the danger of deletion when a cluster is destroyed.

**Comment by michaelajr** [comment]
Never mind - was just informed that the state store is only used by kops not k8s. Oh well.

**Comment by stresler** [comment]
I've been thinking about this for a while, and it seems to me that you don't want to use the current node subnet in all cases. We actually have a use case where we're running one cluster across multiple VPCs and subnets.  I think what would be ideal here is something similar to how NodeSelector works for deployments. 

SubnetSelector, could provide Cidr to specify an exact subnet, or VPC to specify any subnet in a vpc, or various other requirements (Multiple VPCs if it really doesn't matter, Region alone, etc). 

I can try to map this out and write a proposal if that sounds like a good approach.
