### ISSUE TITLE
kubelet should not delete all pods if etcd is accidentally started pointing to the wrong directory

### ISSUE THREAD

**Issue by ejc3** [kubernetes/kubernetes#38918]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

empty etcd

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature request
  - kubelet should be more resilient to configuration errors with etcd. We accidentally started etcd in an empty state during a rollback from etcd 3 to etcd 2. kubelet saw this empty state and immediately deleted all pods, bringing down the whole system.

Describe *in detail* the feature/behavior/change you'd like to see.

I would like to see kubelet error out if there are pods running on its node but etcd is empty. If this isn't possible, I'd like to see the concept of a magic value be made part of kubernetes' etcd store. If the magic key/value is not present in etcd, kubelet will not consider the etcd instance as valid and will refuse to make changes. When bringing up a new K8s cluster for the first time, this magic key/value would need to be written to etcd as the first step.

**Kubernetes version** (use `kubectl version`): 1.4.4

**Environment**:
- **Cloud provider or hardware configuration**: Bare metal
- **OS** (e.g. from /etc/os-release): RHEL 8.1
- **Kernel** (e.g. `uname -a`): Linux kubeetcd1.prod1.omega.bf1.yahoo.com 3.10.0-327.36.3.el7.YAHOO.20161025.20.x86_64 #1 SMP Tue Oct 25 20:44:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: chef
- **Others**:

**What happened**:

We lost all workloads in the system

**What you expected to happen**:

Kubelets would switch to an error state and require manual intervention to continue operation. 

**How to reproduce it** (as minimally and precisely as possible):

1) Take a successfully running cluster 
2) stop etcd
3) start etcd from an empty data directory

Expected: kubelets switch to a "broken state"
Actual: all workloads were deleted :(

As a work around, we're thinking about putting a iptables block on etcd whenever we are doing maintenance to ensure we have a chance to verify etcd's state before letting kubeletes see the etcd cluster.

**Comment by ravilr** [comment]
@ejc3 this is working as intended.  What seems plausible would be to introduce a cluster maintenance mode, which the operator could set it at the beginning of the maintenance. If the cluster is put in maintenance mode, all the components (control plane controllers & kubelet) could suspend their periodic sync loops.

did you stop kubelet on all the nodes and the kube-controller-manager on the masters, before the etcd maintenance. Currently, there is some logic in the control plane (node controller) to prevent deleting nodes (hence pods) en-masse, when all the nodes in the cluster are not-ready (https://github.com/kubernetes/kubernetes/issues/28832) to handle network partitions. The same logic would have prevented any nodes (hence pods) from being evicted, if all the nodes had kubelet stopped. That allows one to check that kube-api is returning empty list for all resources (with etcd running with empty state) and quickly fix the situation, before starting the controller manager and kubelet's in that order.

**Comment by sureshvis** [comment]
@ejc3 @ravilr 

we didn't stop kubelet,  the pods are  serving traffic and just control plane (api, CM, Scheduler) were kept down to avoid WRITE call  to etcd while the migration is in progress. 

If any pod (and/or node)  failed during this maintenance window, the ATS  (ingress traffic server)  will stop routing to that POD as the   health check for POD from ATS (ingress traffic server)  will report failure (and also we have alert if we drop capacity for any service by X% from ATS end to take manual action or fallout to next available colo/Zone)

**Comment by ejc3** [comment]
For the cluster wide maintenance mode, could it be implemented by a flag in etcd? If the flag is enabled, the cluster will operate normally. If the value is missing, the system will put itself into maintenance mode. That way, you handle the "blank" etcd gracefully while delivering this feature.
