### ISSUE TITLE
kube-up.sh failed on ubuntu

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#38921]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

I was following http://kubernetes.io/docs/getting-started-guides/ubuntu/manual/ to install a cluster but failed due to the following.

```
root@k8s001:~/kubernetes/cluster# KUBERNETES_PROVIDER=ubuntu ./kube-up.sh
... Starting cluster using provider: ubuntu
... calling verify-prereqs
Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
... calling verify-kube-binaries
./kube-up.sh: line 45: verify-kube-binaries: command not found
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by gyliu513** [comment]
The current workaround solution is remove `verify-kube-binaries` in ./kube-up.sh

**Comment by du2016** [comment]
#38945 please have a look

**Comment by gyliu513** [comment]
thanks @du2016 for the quick response

**Comment by gyliu513** [comment]
Just FYI, I think that you should fix both kube-up and kube-down @du2016

**Comment by du2016** [comment]
@gyliu513  i have already move: source "${KUBE_ROOT}/cluster/common.sh" to the head of util.sh,is there something can't work?

**Comment by gyliu513** [comment]
Thanks, I did not have a try but just a reminder, just check code, yes, I think it works. Thanks @du2016

**Comment by gyliu513** [comment]
Seems the kube-up still does not work, filed another issue here https://github.com/kubernetes/kubernetes/issues/39224

**Comment by gyliu513** [comment]
@du2016 can you help take a look? Thanks!

**Comment by spzala** [comment]
@gyliu513 hi, I still see the issue but wondering since you have closed #39224 considering planned deprecation of the script. Does this issue still requires a fix or any decision was made not to work on it? Thanks!

**Comment by gyliu513** [comment]
Thanks @spzala , I think that we can close this now as it is not supported any more.

**Comment by spzala** [comment]
@gyliu513 sure and thank you for the quick response and closing it !! 👍
