### ISSUE TITLE
conversion-gen in unsafe mode breaks on `[]*T`

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#38922]
In unsafe mode conversion-gen will do a bit-level conversion of `[]*T`, even if T need a custom conversion.  In other words, the conversion code for T will not be called.

It does correctly recognize `[]T`

Changing the conversion-gen code to go back to unsafe mode will generate the correct code.

cc @smarterclayton 

cf #38440

**Comment by justinsb** [comment]
Following up on #38440, I agree that we shouldn't have `[]*T` in a k8s API, but I think conversion-gen needs to support it anyway, as there will be existing API versions that need converting to a new version that does follow the rules.

We could also make this a warning - a first step towards an API linter.

**Comment by smarterclayton** [comment]
[]*T and []T are externalized the same way, so I don't see why we wouldn't just force someone to change the moment they start using the conversion logic.
