### ISSUE TITLE
Update dead links in examples/guestbook README

### ISSUE THREAD

**Issue by edouardswiac** [kubernetes/kubernetes#38930]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report. I spotted three dead links in the guestbook README inside this repo.

**Comment by spzala** [comment]
@edouardswiac hi, since the directory structure has been lately changed I don't see the problem as such with README - https://github.com/kubernetes/kubernetes/tree/master/examples/guestbook Can you please verify and if you are okay, close the issue? Thanks!
