### ISSUE TITLE
Network: confusion about parameters “--pod-cidr” under cluster model

### ISSUE THREAD

**Issue by chentao1596** [kubernetes/kubernetes#38946]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
pod-cidr/allocate-node-cidrs/cluster-cidr
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  BUG REPORT

**Kubernetes version** (use `kubectl version`):  kubernetes-master

**Environment**:
- **Cloud provider or hardware configuration**:  none
- **OS** (e.g. from /etc/os-release):  Ubuntu 14.04.5 LTS
- **Kernel** (e.g. `uname -a`):  4.2.0-27-generic
- **Install tools**:  kube-up.sh
- **Others**:  none

**What happened**:
Follow the action "./kubelet --help", i can find the description of "--pod-cird" like this:
```
     --pod-cidr string       The CIDR to use for pod IP addresses, only used in standalone mode.  In cluster mode, this is obtained from the master.
```
but, i found that "--pod-cird" is still effective under cluster mode(use kubenet network).
     

**What you expected to happen**:
    According to my understand, "--pod-cidr" should be not work when using cluster mode, and this node must be assigned an IP subnet through the "--allocate-node-cidrs=true --cluster-cidr=<cidr>" controller-manager command-line options

**How to reproduce it** (as minimally and precisely as possible):
    1) Deploy cluster env
    2) Add kubelet config: --pod-cidr=178.16.28.1/24 --network-plugin=kubenet

**Anything else do we need to know**:    
I try to config both of them, "--pod-cidr" will still be effectived:
    1) Add kubelet config: --pod-cidr=178.16.28.1/24 --network-plugin=kubenet
    2) Add kube-controller-manager config: --allocate-node-cidrs=true --cluster-cidr=123.1.1.1/16

is it a bug or my understand is wrong? who can help me answer? thx!

**Comment by bprashanth** [comment]
@kubernetes/sig-network-misc please suggest a better comment based on discussion on https://github.com/kubernetes/kubernetes/issues/32900 (maybe we just need to mention --reconcile-cidr?)

**Comment by tonylambiris** [comment]
@bprashanth Hasn't `--reconcile-cidr` been removed as an option? On a related note, can anyone speak as to why it was removed? Out of all the version of kubernetes I've used for almost 2 years now, by far the easiest ones to configure and setup with third-party dependencies were using that flag with the kubenet network plugin.

**Comment by freehan** [comment]
Need to document this somewhere.

We currently do not support updating podCIDR. The first assignment gets honored. Hence `--pod-cidr` preempts the cidr assignment from controller.

**Comment by freehan** [comment]
@tonylambiris  see https://github.com/kubernetes/kubernetes/pull/34906/files#r83660911

**Comment by vhosakot** [comment]
I think `kube-controller-manager`'s `--cluster-cidr` should be changed to `--pod-cidr` as it is pod's CIDR (`--cluster-cidr` can still exist so that existing clusters don’t break). Isn't `--pod-cidr` more meaningful than `--cluster-cidr`? Thoughts?

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
