### ISSUE TITLE
Failed executing generator: some packages had errors: ./hack/verify-all.sh

### ISSUE THREAD

**Issue by ghost** [kubernetes/kubernetes#38962]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): master-branch

**Environment**: ubuntu 16.04
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
F1219 05:13:14.785570    7055 main.go:44] Error: Failed executing generator: some packages had errors:
errors in package "k8s.io/kubernetes/pkg/generated/openapi":
output for "openapi/zz_generated.openapi.go" differs; first existing/expected diff: 
  "odically.\",\n\t\t\t\tProperties: map[string]spec.Schema{\n\t\t\t\t\t\"conditions\": {\n\t\t\t\t\t\tSchemaProps: spec.Sch"
  "docally.\",\n\t\t\t\tProperties: map[string]spec.Schema{\n\t\t\t\t\t\"conditions\": {\n\t\t\t\t\t\tSchemaProps: spec.Sche"

Makefile.generated_files:504: recipe for target 'verify_gen_openapi' failed
make[1]: *** [verify_gen_openapi] Error 1
Makefile:453: recipe for target 'verify_generated_files' failed
make: *** [verify_generated_files] Error 2

**What you expected to happen**: 

**How to reproduce it** (as minimally and precisely as possible): run the ./hack/verify-all.sh

**Anything else do we need to know**:

**Comment by xulike666** [comment]
[on the master branch] I run the ./verify-federation-openapi-spec.sh but then got : 
...
!!! Error in /home/aaron/gocode/src/k8s.io/kubernetes/hack/lib/etcd.sh:43
  'ls $KUBE_ROOT/third_party/etcd' exited with status 2
Call stack:
  1: ../hack/lib/etcd.sh:43 kube::etcd::validate(...)
  2: ../hack/lib/etcd.sh:55 kube::etcd::start(...)
  3: ../hack/update-federation-openapi-spec.sh:51 main(...)
Exiting with status 1
...

**Comment by eparis** [comment]
I'm so sorry to have ignored this for so long. I think this needs a bigger rework. The logic here seems to be a little strange to me:
```
if etcd in $PATH {
    if etcd version > min {
        success
    }
    add third_party/etcd to PATH
    if etcd not in third_party/etcd {
        fail poorly
    }
    if third_party/etcd version > min {
        success
    }
    fail nicely
} else {
    fail nicely
}
```
We should either always autopopulate PATH with third_party/etcd or never. We shouldn't keep doing so IFF you have etcd in PATH but its version is too low.

I'm fine with either solution, and admittedly this would stop the failure in question (since we'd be checking the version outside third_party/etcd twice) but it doesn't make this function sane/rational going forward.

Do you want to tackle fixing it right?
