### ISSUE TITLE
Feature request for refactoring kubemark start-up script into provider-specific and kubernetes-specific components

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#38967]
Kubemark, the testing framework for kubernetes, currently has some spaghetti code specific to gce inside the cluster startup script (start-kubemark.sh).
We would ideally want to have the provider-specific code inside the script independent of the cluster kubernetes logic. The same also applies for config,
where we would want different config files for both the components (also with possibly some config that is part of the interface).

If we indeed separate these components, how should the interface between them look like? I can think of the following different levels of the interface complexity:
- One where we require the provider-specific component to define methods for fine-grained operations like creation of master-pd, master-https-server, master-ip, master-instance, etc
- One where we worry less about how (or if) we perform these fine-grained operations and rather just require the provider to start the master (with all required components that lets
  it talk to the hollow-nodes).

Any ideas on which approach is better suited (probably based on experience from kube-up)? The second approach gives more freedom to the provider about how it would
configure its components while also (possibly) giving way to more bugs / parts of the kubernetes component failing due to dependencies (which we should eliminate, if any).

@kubernetes/sig-scalability-misc @wojtek-t @gmarek

**Comment by wojtek-t** [comment]
@xiang90 @hongchaodeng @timothysc

**Comment by wojtek-t** [comment]
My personal opinion is that we should expose all necessary elements in the interface, and ignore those that may significantly vary depending on the provider.
For example, depending on the provider, firewall rules may or may not be needed. Since we require the machine to be achievable from hollow-nodes, at the level of interface it should be: ``` make-machine-reachable ``` (or whatever we call them) and exposing the concept of firewall rule doesn't make sense here. We should go one by one with everything what we are doing and evaluate all of those.

**Comment by timothysc** [comment]
I need to dig back into the kubemark script-ery, but why can't we just have a helm chart for deploying it and let others worry about the cluster stand.

/cc @jeremyeder

**Comment by shyamjvs** [comment]
@timothysc There is atleast one way in which kubemark differs from a regular kubernetes application, in that it starts a separate VM instance and rightly configures it to use as the master for the hollowNodes. IIUC, (I might be wrong about this)  helm packaged applications pretty much are defined on pod space and do not allow creation of VM instances. However, an alternative to creating a VM instance for the kubemark master could be to just run all the master components as pods themselves, but this might have implications on the kubemark scalability CI tests which are intended to mimic real cluster scalability tests.

**Comment by shyamjvs** [comment]
@timothysc There was a discussion before implementing kubemark ([here](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/kubemark.md#kubemark-architecture-overview)), where the above alternative was considered. However, the option of having all the master components on a single VM was opted for.
