### ISSUE TITLE
[Federation] Implement federated pod autoscaler

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/kubernetes#38974]
This issue is created to track the development of a federated pod autoscaler.
The design document was updated [here ](https://docs.google.com/document/d/1Uacp99LskNHkJ6ZFFOVGorDivYKi4ySkI8E3tTFAZJ8/edit?usp=sharing) some days ago.

cc @kubernetes/sig-cluster-federation
@shashidharatd @kshafiee @deepak-vij

**Comment by mwielgus** [comment]
What about this:

Federated HPA (FHPA) doesn't create any HPAs in the federation subclusters. Instead, from every cluster it gets:

* `avg_i` average metric value (like CPU utilization) for all pods matching the deployment/rs selector.
* `count_i` number of replicas that were used to calculate the average.

To calculate the target number of replicas HPA calculates the sum of all metrics from all clusters
```
sum(avg_i * count_i)  
```
and divides it by target metric value. The target replica count (validated against HPA min/max and thresholds) is set on Federated Deployment/replica set. So the deployment has the correct number of replicas (that should match the desired metric value) and provides all of the rebalancing/failover mechanisms. 

Then we can expand FHPA to place replicas where they are needed the most (in cluster that have the most traffic). For that FHPA would play with weights in Federated Deployment. Each cluster will get the weight of
```
100 * avg_i/sum(avg_i)
```
Weights hint Federated Deployment where to put replicas. But they are only hints so if placing a replica in the desired cluster is not possible then it will be placed elsewhere, what is probably better than not having the replica at all.

**Comment by irfanurrehman** [comment]
@mwielgus thanks a lot for your suggestion.
However when I try and weigh this implementation against the one I have submitted.
I see 2 positives (please add if you see more).
1 - If calculations are done at federation and scaling and distribution of replicas for each cluster is handled at federation, then a global min and max can be maintained, even with cluster outages.
2 - The overall hpa flow is cleaner, as the number of replicas per cluster is set as preferences onto federated rs/deployment.

I see some small drawbacks also, which seems not there with the per cluster hpa logic.
1 - There are delays, however small and additional API traffic, which might be overwhelming both in delay and complexity in case of large clusters or overall large setup (read 100s of small clusters).
2 - In some scenario, the per cluster hpa might exactly be what is needed, but user might not have/or does not want direct access to all clusters.

I have updated similar thoughts in the reply to the comments in the design doc, please check that too.

I see lot of value in your suggestions. We can probably see feedback from other guys too and conclude on the best approach.

Once again, thanks a lot for your suggestion and guidance!

**Comment by quinton-hoole** [comment]
@mwielgus @irfanurrehman See my comments today in your design doc:

https://docs.google.com/document/d/1Uacp99LskNHkJ6ZFFOVGorDivYKi4ySkI8E3tTFAZJ8/edit

I think that there is a good way that combines the benefits of both of the approaches above.  See what you think.

**Comment by irfanurrehman** [comment]
This issue was moved to kubernetes/federation#4

**Comment by irfanurrehman** [comment]
moved to kubernetes/federation#4
