### ISSUE TITLE
DaemonSetsController mutates DaemonSets from the shared DaemonSetInformer

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#38985]
In `storeDaemonSetStatus`, the DaemonSetsController modifies the DaemonSet from the shared DaemonSetInformer, setting `ds.Status.DesiredNumberScheduled`, `ds.Status.CurrentNumberScheduled`, `ds.Status.NumberMisscheduled`, and `ds.Status.NumberReady`. It needs to make a copy of the DaemonSet prior to mutating it.

Discovered in OpenShift using the cache mutation detector.

cc @deads2k @mikedanese @lavalamp @smarterclayton

**Comment by ncdc** [comment]
I'm working on a fix

**Comment by deads2k** [comment]
We got the mutation detector in kube, but we never got it wired to run in e2es.  We want it in the controllers in particular.  It's enabled with an env var.

**Comment by mikedanese** [comment]
cc @kubernetes/daemonset
