### ISSUE TITLE
Adding etcd-events log to jenkins artifacts

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#38983]
Right now, we do not seem to copy etcd-events.log (if it exists). Would it be okay to have its log included in artifacts, as it might help debugging flaky tests?
Also, the log file is not very big and is typically around a few tens of lines, just like etcd.

@kubernetes/sig-scalability-misc @wojtek-t @gmarek

**Comment by wojtek-t** [comment]
Yes - that would be useful. Feel free to add it (it should be very simple).
