### ISSUE TITLE
RBAC roles and bindings for restricting group to namespace not working as expected

### ISSUE THREAD

**Issue by amitkgupta** [kubernetes/kubernetes#38997]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): Yes

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): "RBAC"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Not sure (either it's a bug, or I'm missing something, in which case it would be a request for better documentation or better debug information)

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+82450d0", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"not a git tree", BuildDate:"2016-12-14T04:09:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:16:27Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release):

 ```
 PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
 NAME="Debian GNU/Linux"
 VERSION_ID="8"
 VERSION="8 (jessie)"
 ID=debian
 HOME_URL="http://www.debian.org/"
 SUPPORT_URL="http://www.debian.org/support"
 BUG_REPORT_URL="https://bugs.debian.org/"
 ```
- **Kernel** (e.g. `uname -a`):

 ```
 Linux 4.4.26-k8s #1 SMP Fri Oct 21 05:21:13 UTC 2016 x86_64 GNU/Linux
 ```
- **Install tools**: Terraform v0.8.1, small [fork](https://github.com/amitkgupta/kops/commit/6e267a3c6bdab17e9eb10e2340e33217135c09cb) of `kops` (and `nodeup`)
- **Others**:
  - [Gist](https://gist.github.com/amitkgupta/d5ff7dfc691c0e55162f9196b61964d2) with details of cluster operations
  - AMI: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21

**What happened**:

1. Deployed Kubernetes with API Server flags to support "RBAC,AlwaysAllow" authorization modes, set RBAC super user, and enable RBAC API via `--runtime-config`.
1. Created a namespace, role, and role binding with the intent that (a) service accounts and system components can effectively still have "AlwaysAllow" access, and (b) any entity in group `dev` can access anything in namespace `dev` using [this YAML file](https://gist.github.com/amitkgupta/d5ff7dfc691c0e55162f9196b61964d2#dev-accessyml).
1. Updated Kubernetes to only allow "RBAC" authorization mode.
1. Generated client TLS data where the certificate subject flag (for openssl) was `-subj "/CN=example-dev@kubernetes.click/O=dev"`
1. Generated a kubeconfig file following [this template](https://gist.github.com/amitkgupta/d5ff7dfc691c0e55162f9196b61964d2#dev-kube-configyml).
1. I get the following errors when running: `kubectl -v 8 --kubeconfig=/tmp/dev-kube-config.yml create -f /tmp/busybox.yml`:

```
I1219 16:12:37.584657   44323 loader.go:354] Config loaded from file /tmp/dev-kube-config.yml
I1219 16:12:37.585953   44323 round_trippers.go:296] GET https://api.kubernetes.click/api
I1219 16:12:37.585968   44323 round_trippers.go:303] Request Headers:
I1219 16:12:37.585983   44323 round_trippers.go:306]     Accept: application/json, */*
I1219 16:12:37.585991   44323 round_trippers.go:306]     User-Agent: kubectl/v1.5.1+82450d0 (darwin/amd64) kubernetes/82450d0
I1219 16:12:38.148994   44323 round_trippers.go:321] Response Status: 403 Forbidden in 562 milliseconds
I1219 16:12:38.149056   44323 round_trippers.go:324] Response Headers:
I1219 16:12:38.149070   44323 round_trippers.go:327]     Content-Type: text/plain; charset=utf-8
I1219 16:12:38.149081   44323 round_trippers.go:327]     Content-Length: 17
I1219 16:12:38.149091   44323 round_trippers.go:327]     Date: Tue, 20 Dec 2016 00:12:38 GMT
I1219 16:12:38.149190   44323 request.go:904] Response Body: Forbidden: "/api"
I1219 16:12:38.149249   44323 request.go:995] Response Body: "Forbidden: \"/api\""
I1219 16:12:38.149567   44323 request.go:1151] body was not decodable (unable to check for Status): Object 'Kind' is missing in 'Forbidden: "/api"'
...
I1219 16:12:38.820672   44323 round_trippers.go:296] GET https://api.kubernetes.click/swaggerapi/api/v1
I1219 16:12:38.820702   44323 round_trippers.go:303] Request Headers:
I1219 16:12:38.820717   44323 round_trippers.go:306]     User-Agent: kubectl/v1.5.1+82450d0 (darwin/amd64) kubernetes/82450d0
I1219 16:12:38.820731   44323 round_trippers.go:306]     Accept: application/json, */*
I1219 16:12:38.902256   44323 round_trippers.go:321] Response Status: 403 Forbidden in 81 milliseconds
I1219 16:12:38.902306   44323 round_trippers.go:324] Response Headers:
I1219 16:12:38.902327   44323 round_trippers.go:327]     Content-Type: text/plain; charset=utf-8
I1219 16:12:38.902345   44323 round_trippers.go:327]     Content-Length: 31
I1219 16:12:38.902363   44323 round_trippers.go:327]     Date: Tue, 20 Dec 2016 00:12:38 GMT
I1219 16:12:38.902456   44323 request.go:904] Response Body: Forbidden: "/swaggerapi/api/v1"
I1219 16:12:38.902512   44323 request.go:995] Response Body: "Forbidden: \"/swaggerapi/api/v1\""
F1219 16:12:38.903025   44323 helpers.go:116] error: error validating "/tmp/busybox.yml": error validating data: the server does not allow access to the requested resource; if you choose to ignore these errors, turn validation off with --validate=false
```

**What you expected to happen**:

Expected to create busybox pod in `dev` namespace.

**How to reproduce it** (as minimally and precisely as possible):

See steps above.

**Anything else do we need to know**:

I tried some varieties of roles and cluster rules, especially thing around non-resource URLs.  In the end I couldn't get anything working without giving everyone access to everything.  I'd like to issue certs to many different developers (different subjects) all within the `dev` group, and have them all have access to create and modify things within the `dev` namespace, but not touch anything outside it, and definitely not see secrets outside it.  So if the only way to do this is to give some read/watch/list access to `dev` group to some non-namespaced resources or non-resource URLs, that's okay as long as it isn't direct or indirect access to any sort of credentials.

Cross-posted:

 * StackOverflow: http://stackoverflow.com/questions/41309420/how-to-create-users-groups-restricted-to-namespace-in-kubernetes-using-rbac-api
 * Mailing list: https://groups.google.com/forum/#!topic/kubernetes-dev/6TBTu1AC2L8

**Comment by amitkgupta** [comment]
I upgraded to v1.5.1 with the hope that I wouldn't need to construct any cluster roles or cluster role bindings, and this should just work:

```
kind: Namespace
apiVersion: v1
metadata:
  name: dev
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  namespace: dev
  name: dev-all
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: dev-role-dev-all-members
  namespace: dev
subjects:
  - kind: Group
    name: dev
  - kind: Group
    name: system:serviceaccounts:dev
roleRef:
  kind: Role
  name: dev-all
  apiGroup: "rbac.authorization.k8s.io"
```

It didn't work out-of-the-box for various reasons, and I ended up needing to add the following cluster role bindings:

```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: system:node--kubelet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node
subjects:
- kind: User
  name: kubelet
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: cluster-admin--kube-system:default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: system:node-proxier--kube-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-proxier
subjects:
- kind: User
  name: kube-proxy
```

I added these after things didn't work, SSH'd in, dug around logs, etc, then figured that a particular user or service account was trying to a certain kind of thing but failing due to permissions.  Based on that "kind of thing" it was easy to tell which cluster roles to bind them to.  The out-of-the-box cluster role bindings don't bind these users/service accounts explicitly, instead they bind special `system:` groups.

What magic is needed to make the `system:` groups work out-of-the-box?  I'm using a version of `kops` to stand up my cluster that was made for Kubernetes v1.4.6 (since they haven't shipped support for v1.5.1 officially yet), so maybe there's a new thing that needs to be done when starting up newer versions of Kubernetes that `kops`/`nodeup` isn't doing?  Any clarifications there would be helpful.

**Comment by liggitt** [comment]
Much has been done since 1.4.

1. There are [default clusterroles and clusterrolebindings defined](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/) which are loaded at server start (you can also load them yourself as a superuser, though you'll need to go back to the [v1alpha1](https://github.com/kubernetes/kubernetes/tree/15466fcca9c6c23f4c3b165bad2b8405678d0b41/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata) data to load them into 1.4 or 1.5)

2. Those roles and bindings allow all users to access discovery APIs (the /swaggerapi URLs, etc)

3. They give control plane components (apiserver, nodes, kube-proxy, controller-manager) the correct roles, *provided those components run with the expected user or group*. Documentation of the default roles and bindings is in progress at https://github.com/kubernetes/kubernetes.github.io/pull/2360/files

Most of the work to make various deployment mechanisms (kube-up.sh, kubeadm, etc) set up expected credentials for each component is happening in the 1.6 timeframe.

**Comment by liggitt** [comment]
at HEAD, kube-up.sh and kubeadm start up with RBAC enabled

https://github.com/kubernetes/kubernetes/issues/40021 tracks remaining roles that need defining

kops has issues to track RBAC enablement:
https://github.com/kubernetes/kops/issues/1231
https://github.com/kubernetes/kops/issues/1130 (which might look familiar)
