### ISSUE TITLE
Init container cannot pull from registry with authentication (ECR)

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#38993]
**Is this a request for help?** 
No

**What keywords did you search in Kubernetes issues before filing this one?** 
init container
---

**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**Kubernetes version**:
v1.4.3

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Pulling init containers from ECR results in ImagePullErrro
(pulling the same image as a regular container works fine / puling the image from a registry without authentication works fine)

**What you expected to happen**:
Pull via credentials from secrets as regular containers do.

**How to reproduce it** (as minimally and precisely as possible):
Use ECR image with init container.

**Comment by lukaszo** [comment]
Can you show your yaml files and describe how did you configured the secrets? I checked and it's working for me.

**Comment by grosser** [comment]
Thx for checking!

... was about to reproduce again ... turns out that was just me being stupid ... did not push the image to ECR with the correct tag :(
