### ISSUE TITLE
[Federation] `kubefed init` needs verbose logs for debuggability .

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#39004]
`kubefed init` has no verbose logs at all and this is a pain while debugging. Add logs at appropriate verbosity levels for `kubefed init`.

cc @kubernetes/sig-federation-misc @irfanurrehman

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by madhusudancs** [comment]
Also, there is a PR for this - https://github.com/kubernetes/kubernetes/pull/41849

Did not make the code freeze deadline.

**Comment by marun** [comment]
I'm assuming this was fixed by #41849.
