### ISSUE TITLE
Kubernetes source files contain bad fragment for flanneld

### ISSUE THREAD

**Issue by davebotelho** [kubernetes/kubernetes#39027]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

NO

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

NONE

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

I found the bug in both 1.4.7 and 1.5.1

**Environment**:
- **Cloud provider or hardware configuration**: Openstack
- **OS** (e.g. from /etc/os-release): CentOS
- **Kernel** (e.g. `uname -a`):
- **Install tools**: kube-up.sh
- **Others**:

**What happened**:

Your openstack templates for the flanneld service are using incorrect names of etc variables being set in the /etc/sysconfig/flanneld file.

The flanneld.service file is looking for the variables to be named FLANNEL_ETCD_ENDPOINTS and FLANNEL_ETCD_PREFIX.

The correct references are found in the snippets of the fragments below as follows: 

provision-network-master.sh
cat <<EOF > /etc/sysconfig/flanneld
FLANNEL_ETCD_ENDPOINTS="${FLANNEL_ETCD_URL}"
FLANNEL_ETCD_PREFIX="/coreos.com/network"
FLANNEL_OPTIONS="-iface=eth0 --ip-masq"
EOF

provision-network-node.sh
cat <<EOF >/etc/sysconfig/flanneld
FLANNEL_ETCD_ENDPOINTS="${FLANNEL_ETCD_URL}"
FLANNEL_ETCD_PREFIX="/coreos.com/network"
FLANNEL_OPTIONS="-iface=eth0 --ip-masq"
EOF

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by micmro** [comment]
I can confirm this issue and fix, I had to change
```
FLANNEL_ETCD="${FLANNEL_ETCD_URL}"
FLANNEL_ETCD_KEY="/coreos.com/network"
```
to
```
FLANNEL_ETCD_ENDPOINTS="${FLANNEL_ETCD_URL}"
FLANNEL_ETCD_PREFIX="/coreos.com/network"
```
to be able to create a stack.
