### ISSUE TITLE
Proactively detect pod -> external networking issues

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#39039]
There are situations where pod -> apiserver/internet might be broken, but kubelet can still heartbeat etc. This will result in crashlooping pods on a Ready node. Such a node should be marked NotReady, and possibly auto-cordoned. 

One way to do this is to deploy a networking canary daemonset that the kubelet is aware of. Maybe we can even reuse the node problem detector? or maybe the kubelet can exec a non-local connectivity check from inside a pod's namespace?

**Comment by freehan** [comment]
I think daemonset probably is not going to cover all cases. If there is problem with container networking, a monitoring pod may not be able to reach out and report the problem. 

Maybe we should run a monitoring daemon directly on node. Reuse node problem detector or consider using some existing solutions.

**Comment by bprashanth** [comment]
the acutal check needs to execute in the container namespace for this to be effective, and of course the thing flipping node readiness needs to run in the host net ns

**Comment by thockin** [comment]
I think this is an interesting idea, but should be something people opt-in to.
