### ISSUE TITLE
Running multiple-schedulers with leader-elect

### ISSUE THREAD

**Issue by lachie83** [kubernetes/kubernetes#39032]
**Kubernetes version** (use `kubectl version`):
```
$kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0", GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", BuildDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS

**What happened**:
Running through the following example (http://kubernetes.io/docs/admin/kube-scheduler/) you cannot start a second scheduler without disabling leader-elect if the default scheduler has leader-elect enabled (default). I think the lock needs to configurable based on scheduler name.

**What you expected to happen**:
You can run subsequent schedulers with leader-elect using a separate lock.

**How to reproduce it** (as minimally and precisely as possible):
Run through -- http://kubernetes.io/docs/admin/kube-scheduler/

Yields
```
$ kubectl logs my-scheduler-3263660448-r8xfq   -n kube-system -f
W1220 18:09:43.712076       1 client_config.go:481] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1220 18:09:43.760718       1 leaderelection.go:247] lock is held by ip-10-0-10-11.us-west-2.compute.internal and has not yet expired
I1220 18:09:47.214644       1 leaderelection.go:247] lock is held by ip-10-0-10-11.us-west-2.compute.internal and has not yet expired
I1220 18:09:49.939585       1 leaderelection.go:247] lock is held by ip-10-0-10-11.us-west-2.compute.internal and has not yet expired
I1220 18:09:53.178888       1 leaderelection.go:247] lock is held by ip-10-0-10-11.us-west-2.compute.internal and has not yet expired
```

Adding leader-elect=false to subsequent kube-scheduler gets round this at the moment
```
$kubectl logs my-scheduler-3263660448-wr6bc   -n kube-system -fem
W1220 18:11:13.475504       1 client_config.go:481] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1220 18:11:13.519262       1 event.go:217] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"annotation-second-scheduler", UID:"28908cea-c6df-11e6-b886-06f3d2138bbf", APIVersion:"v1", ResourceVersion:"977630", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' no nodes available to schedule pods
```

**Anything else do we need to know**:

**Comment by foxish** [comment]
cc @kubernetes/sig-scheduling-misc

**Comment by timothysc** [comment]
> you cannot start a second scheduler without disabling leader-elect if the default scheduler has leader-elect enabled (default). I think the lock needs to configurable based on scheduler name. 

@lachie83 Are you trying to open the same scheduler on a different annotation?  b/c that's not really how it was intended to be used.  The multiple scheduler model was to allow for domain specific 3rd party schedulers.  The endpoint lock on the main scheduler would have to be re-jigged to allow this.  

Are you looking for a practical use case or are you tinkering?
