### ISSUE TITLE
Bug in release-1.3  removes leading characters in etcd3 endpoint url

### ISSUE THREAD

**Issue by sudhi-vm** [kubernetes/kubernetes#39035]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

etcd3 TrimLeft

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version** (use `kubectl version`):
Release-1.3

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

-Not applicable-

**What happened**:
If etcd server name starts with any of 'h','t' or 'p', API server truncates the leading characters and complains that it cannot connect to the etcd cluster. For e.g., if `--etcd-servers=http://his-etcd.abc.com:2379`, the API server tries connecting `is-etcd.abc.com:2379`.

**How to reproduce it** (as minimally and precisely as possible):
In release-1.3, set `--etcd-servers=http://his-etcd.abc.com:2379`, when starting API server.

The fix is to change `TrimLeft` to `TrimPrefix` in `pkg->storage->storagebackend->factory->etcd3.go`

**Comment by xiangpengzhao** [comment]
/sig api-machinery
/cc @liggitt
As per discussion in #39037, we can close this issue.
