### ISSUE TITLE
go run hack/e2e.go --build hangs forever

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#39041]
As reported by @Crassirostris @gmarek 

I believe something in `kube::build::run_build_command_ex()` is incompatible with e2e.go's `finishRunning()` command. This winds up calling the following command which never completes:

```
31501 pts/37   Tl     0:00 docker run --name=kube-build-6f660550d5-4-v1.7.4-1 --user=108204:5000 --hostname=fejta1.sea.corp.google.com --volumes-from kube-build-data-6f660550d5-4-v1.7.4-1 --env KUBE_FASTBUILD=true --env KUBE_BUILDER_OS=linux-gnu --env KUBE_BUILD_PPC64LE=n --env KUBE_VERBOSE=1 --interactive --tty kube-build:build-6f660550d5-4-v1.7.4-1 make cross
```

https://github.com/kubernetes/kubernetes/blob/master/build/common.sh#L560

This caused us problems with hanging in the past: https://github.com/kubernetes/test-infra/pull/688#discussion_r82313416

Can we remove the `--interactive --tty` option?

**Comment by fejta** [comment]
We can alternatively handle this by removing stdin support from https://github.com/kubernetes/kubernetes/blob/master/hack/e2e.go#L464

**Comment by ixdy** [comment]
I think [this comment](https://github.com/kubernetes/kubernetes/blob/master/hack/e2e.go#L461-L462) explains why we run in interactive mode (and why we map stdin), though I don't know whether it's really still valid.

It's strange that folks are suddenly having lots of problems here. What changed?

**Comment by ixdy** [comment]
the simpler "fix" is to remove -build from `e2e.go` and just tell users to run `make quick-release` ...

**Comment by ixdy** [comment]
I'm pretty stumped as to why this is getting stuck, though. @jbeda any ideas?

**Comment by Crassirostris** [comment]
@ixdy Can it be because of the [cmd.Wait](https://golang.org/pkg/os/exec/#Cmd.Wait)? From the description:

```
If c.Stdin is not an *os.File, Wait also waits for the I/O loop copying from c.Stdin into the process's standard input to complete.
```

However this doesn't explain stdout and stderr from the container not being attached to the e2e.go process.

**Comment by Crassirostris** [comment]
@ixdy As to what changed, I think the main difference is https://github.com/kubernetes/kubernetes/pull/37866

Replacing the contents of `finishRunning` below line 951 with `return cmd.Run()` makes it work

**Comment by pospispa** [comment]
I'm experiencing the same problem.

I thought that it may be a Docker related issue or am I on a wrong track?

Note: I experienced the problem with Docker 1.12.2, 1.12.4 and 1.12.5.

**Comment by pospispa** [comment]
@Crassirostris just to be sure you mean that the below change makes it work:
```
diff --git a/hack/e2e.go b/hack/e2e.go
index 36c534c..aa3b8d2 100644
--- a/hack/e2e.go
+++ b/hack/e2e.go
@@ -32,7 +32,6 @@ import (
        "regexp"
        "strconv"
        "strings"
-       "syscall"
        "text/template"
        "time"
 )
@@ -948,34 +947,5 @@ func finishRunning(cmd *exec.Cmd) error {
                log.Printf("Step '%s' finished in %s", stepName, time.Since(start))
        }(time.Now())
 
-       cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
-       if err := cmd.Start(); err != nil {
-               return fmt.Errorf("error starting %v: %v", stepName, err)
-       }
-
-       finished := make(chan error)
-
-       go func() {
-               finished <- cmd.Wait()
-       }()
-
-       for {
-               select {
-               case <-terminate.C:
-                       terminate.Reset(time.Duration(0)) // Kill subsequent processes immediately.
-                       syscall.Kill(-cmd.Process.Pid, syscall.SIGKILL)
-                       cmd.Process.Kill()
-                       return fmt.Errorf("Terminate testing after 15m after %s timeout during %s", *timeout, stepName)
-               case <-interrupt.C:
-                       log.Printf("Interrupt testing after %s timeout. Will terminate in another 15m", *timeout)
-                       terminate.Reset(15 * time.Minute)
-                       if err := syscall.Kill(-cmd.Process.Pid, syscall.SIGINT); err != nil {
-                               log.Printf("Failed to interrupt %v. Will terminate immediately: %v", stepName, err)
-                               syscall.Kill(-cmd.Process.Pid, syscall.SIGTERM)
-                               cmd.Process.Kill()
-                       }
-               case err := <-finished:
-                       return err
-               }
-       }
+       return cmd.Run() 
 }
```

**Comment by Crassirostris** [comment]
@pospispa Works for me. Does it work for you?

**Comment by pospispa** [comment]
@Crassirostris Yeap, now I can confirm that it also works for me.

**Comment by Crassirostris** [comment]
That's really strange btw, because Run basically uses Start + Wait inside

**Comment by ixdy** [comment]
It looks like the
```golang
  cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
```
line might be what's causing problems. If I comment it out, I get streaming output after `"Running build command..."`, as expected. When it's there, the output stops.

**Comment by Crassirostris** [comment]
@ixdy Also worked for me

Is it possible to comment it out? It would be nice to have `-build` command back

**Comment by ixdy** [comment]
@fejta do you think you can look into this?

**Comment by ixdy** [comment]
@Crassirostris if we remove that line, then timeout handling won't work anymore.
anyone @kubernetes/test-infra-maintainers have a better understanding of why this might be broken?

**Comment by Crassirostris** [comment]
@fejta @ixdy Any news?

**Comment by Crassirostris** [comment]
Whoops, sorry, accidentally closed

**Comment by ixdy** [comment]
I think hack/e2e.go is deprecated now. Not sure if this problem still exists in its successor.

**Comment by nikhiljindal** [comment]
Link to the successor? :)

**Comment by ixdy** [comment]
https://github.com/kubernetes/test-infra/tree/master/kubetest

**Comment by Crassirostris** [comment]
OK, thanks! I will check kubetest shortly

**Comment by Crassirostris** [comment]
@ixdy Reproducible with kubetest

**Comment by fejta** [comment]
Migrated this issue to test-infra repo
