### ISSUE TITLE
Refactor to address the following discussion

### ISSUE THREAD

**Issue by rkouj** [kubernetes/kubernetes#39056]
https://github.com/kubernetes/kubernetes/pull/37727#discussion_r90376513

**Comment by liggitt** [comment]
was the fix in #40126 sufficient, or do you want to bubble the error past SetNodeStatusUpdateNeeded?

**Comment by spiffxp** [comment]
@kubernetes/sig-storage-misc do you want this in v1.7?

**Comment by thockin** [comment]
@saad-ali can you retitle this to be meaningful or close it?

**Comment by jsafrane** [comment]
I checked the sources, `updateNodeStatusUpdateNeeded` now returns `error` as requested here.

/close
