### ISSUE TITLE
somehow #include the CoreOS CloudConfig into AWS Cloud Formation rather than inline.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#3906]
In the AWS cloud formation template, `docs/getting-started-guides/aws/cloudformation-template.json`, there are two places where CoreOS "cloud-config" scripts are inlined.  The source of these scripts is `docs/getting-started-guides/coreos/cloud-configs/` but with some slight differences.  It is a minor pain to keep these in sync.

Wondering if @silasdavis @pires @kelseyhightower or another person familiar with CloudFormation and AWS wants to find a way to dedup these.  Like maybe write a little script to generate the cloud-formation from the coreos cloud-configs and a template of the cloudformation.  Or put versioned coreos cloud-configs in an S3 bucket.  Or something.

**Comment by pires** [comment]
I'm not familiar with CloudFormation but IIRC you asked for me to update this as well, and so I did. I've validated the template with official AWS CloudFormation validator.
+1 for someone who actually uses AWS & CloudFormation to take on this based on ```docs/getting-started-guides/coreos/cloud-configs/```.

**Comment by silasdavis** [comment]
Yes some sort of templating for CloudFormation templates is something I've wanted in the past. When I looked I found this: https://github.com/cloudtools/troposphere. It's a python-based programatic generation library for CloudFormation templates. I couldn't justifiy the time outlay the last time I looked, but I would be up for having another go.

Beyond maintainability, there is also the advantage of some validations in troposphere. Cloudformation templates can often fail quite late - after resources have been created for example - for issues that could be trapped at build-time.

My focus is slightly away from Kubernetes stuff at the moment, but I will be returning to it. So I'm rasing my hand for this, but in the meantime if anyone else wants to have a go then please do and perhaps I can assist later.

**Comment by chrisleck-old-personal** [comment]
FWIW, I setup a series of CF templates to configure my environment including Kube master and nodes using https://google.github.io/jsonnet/doc/.  They're not yet in shape to share, but I would encourage taking a look at this config language as a way to get things like #include, loops, and substitutions working for CF.

**Comment by vmattos** [comment]
I have just written a tool for parsing my cloud-config into cloudformation strings. It's working pretty fine for me (since I generate my cf template in a coffeescript)! I may open-source it would help someone else, and maybe adapt it to a command-line tool

**Comment by justinsb** [comment]
I don't think this exists any more; suggest closing.
