### ISSUE TITLE
`kubectl delete --namespace [ns] --all pv` deletes pvs outside of the target namespace

### ISSUE THREAD

**Issue by nwwells** [kubernetes/kubernetes#39084]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
kubectl delete namespace persistent volume
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.2", GitCommit:"cfdaf18277e1ebaa28fcdaed1160a0243eb81be1", GitTreeState:"clean", BuildDate:"2016-10-27T22:15:03Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:43:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): ... GKE?
- **Kernel** (e.g. `uname -a`): ... GKE?
- **Install tools**: what does this mean? Install for `kubectl`? I installed via gcloud, which I installed via wget.
- **Others**:

**What happened**:
I ran the following: 

```
> kubectl delete --namespace middleware --all deployments,pv,pvc,svc,ing
deployment "ingress-controller" deleted
deployment "spielberg" deleted
persistentvolume "pvc-1ba28408-c78a-11e6-875b-42010a8e008b" deleted
persistentvolume "pvc-77c06953-c77b-11e6-8be6-42010a8e008b" deleted
persistentvolume "pvc-ca72445c-c785-11e6-875b-42010a8e008b" deleted
persistentvolume "pvc-cb39526a-c785-11e6-875b-42010a8e008b" deleted
persistentvolumeclaim "darwin" deleted
service "darwin" deleted
service "ingress-controller" deleted
service "spielberg" deleted
service "traefik-web-ui" deleted
ingress "darwin-ingress" deleted
ingress "spielberg-ingress" deleted
ingress "traefik-ingress" deleted
```

The persistent volumes that were deleted (except one) were actually from the `default` namespace.

**What you expected to happen**:
If I specify a namespace in the delete command, I would expect nothing outside of that namespace to be deleted

**How to reproduce it** (as minimally and precisely as possible):
should be pretty easy... I'll work on a script after I fix the fact that my volumes all got hosed.

**Anything else do we need to know**:
Nope

**Comment by AdoHe** [comment]
Seems has some conflict between `--namespace` and `--all`.

**Comment by xingzhou** [comment]
shouldn't we check the conflicts from kubectl side on the co-existing of these two flags? or at least give some warning message

**Comment by nwwells** [comment]
thing is, there were deployments, services, pvcs, and ingresses in the `default` namespace which were NOT deleted, so this is apparently a problem just with persistent volumes?

**Comment by xingzhou** [comment]
let me take some investigation on this, will update you the result then

**Comment by AdoHe** [comment]
@xingzhou just go ahead, and any help please let me know.

**Comment by munnerz** [comment]
Should be noted that PVs aren't namespaced. I'd expect kubectl to report that fact and not delete any resources until the operator corrects their input (or alternatively, delete everything except the PVs). What would you expect here?

**Comment by nwwells** [comment]
I wasn't aware of that. I'm curious why, but I suppose that's a subject for another thread. I agree that delete should fail unless it's completely unambiguous what the user expects to happen, which in this case means failing if --all, pv and --namespace are all specified

**Comment by xingzhou** [comment]
"I'd expect kubectl to report that fact and not delete any resources until the operator corrects their input" sounds reasonable to me

**Comment by xingzhou** [comment]
@AdoHe, any ideas of this? I can see two solutions right now:
1. `--all-namespaces` and `--namespace` are not allowed to be used at same time for a kubectl command, kubectl shall report error and stop executing the command.
2. kubectl prints a warning message to user showing that `--namespace` option is ignored while `--all-namespaces` is also specified to the command

**Comment by smarterclayton** [comment]
We allow users to delete custer scoped and namespace scoped resources at the same time.  We can't change it because of backwards compatibility guarantees with existing scripts.

Generally... don't delete PVs.  Nothing stops you from accidentally deleting nodes or namespaces either, which are equally destructive.

**Comment by pashtet04** [comment]
> Should be noted that PVs aren't namespaced. I'd expect kubectl to report that fact and not delete any resources until the operator corrects their input (or alternatively, delete everything except the PVs). What would you expect here?

@munnerz is right: kubectl can raise an error about incorrect parameter such a "--namespace" when `kubectl delete pv --namespace myns`.
What do you think? Cuz few days ago we accidentally delete pvs due miss 'c' in 'pvc' with parameter "--namespace". Would be great as I think.

Thank you.
