### ISSUE TITLE
poddisruptionbudget not listed as a type in kubectl help text

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#39100]
**Kubernetes version** (use `kubectl version`):
1.5.1 for both the client and server

**Environment**:
N/A

**What happened**:
Running `kubectl get --help` returns a long list of valid resource types. This list doesn't include `poddisruptionbudget`, even though it's a valid beta resource type AFAIK. Running `kubectl get poddisruptionbudget` works.

**What you expected to happen**:
For the list in the kubectl help text to include all valid resource types.

**How to reproduce it** (as minimally and precisely as possible):
`kubectl get --help`

**Comment by foxish** [comment]
cc @mwielgus @davidopp
