### ISSUE TITLE
Evict static pods

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#39124]
https://github.com/kubernetes/kubernetes/pull/39059 is a short term mitigation to:     

1. lack of proper disk accounting on node
2. kube-proxy running as a static pod instead of a daemonset
3. the kubelet not restarting pods that are in Failed/Evicted, on assumption that some other controller will recreate them

These 3 events conspire to permanently evict kube-proxy when a user pod  that writes to *local* fs (not volumes, i.e generate a large top-level aufs image layer) fills disk, resulting in a pretty serious form of priority inversion, and a trivial DOS vector. 

https://github.com/kubernetes/kubernetes/pull/39059 is motivated by an assumption that static-pods are well behaved pods placed on the node by an admin. Obviously this is not always true. We should spend the time required to design a fix for the other issues, and go back to evicting static pods in 1.6. 

We can't reuse the "critical-pod"  annotation for 2 reasons:     
1. We want it to mean "de-prioritize" eviction, not "never do it" (https://github.com/kubernetes/kubernetes/pull/38914)
2. Because of improper disk accounting, we actually appear to evict a pod every 10s, killing everything on the node before disk pressure alleviates 5-10m later, so reordering what gets killed isn't going to help
3. It would grandfather in a bunch of other pods like kube-ui and DNS. NB even though we use "critical-pod" to admit pods under memory pressure, all the gradfathered pods have memory limits. 

@kubernetes/sig-node-misc  @kubernetes/sig-network-misc

**Comment by vishh** [comment]
> lack of proper disk accounting on node

What is "lacking"?

> the kubelet not restarting pods that are in Failed/Evicted, on assumption that some other controller will recreate them

This seems to be the bug to me. If the static pod were to really use up a lot of disk space, restarting it might end up freeing up disk space.

https://github.com/kubernetes/kubernetes/issues/31362 is tracking improving evictions to be more responsive. 

Even though we'd like to avoid evicting DaemonSet pods, at times, evicting them might be the right thing to do.

**Comment by bprashanth** [comment]
On Wed, Dec 21, 2016 at 7:12 PM, Vish Kannan <notifications@github.com>
wrote:

> lack of proper disk accounting on node
>
> What is "lacking"?
>

A pod writing to it's local fs is able to evict all other pods on the node.

**Comment by bprashanth** [comment]
On Wed, Dec 21, 2016 at 7:12 PM, Vish Kannan <notifications@github.com>
wrote:

> lack of proper disk accounting on node
>
> What is "lacking"?
>
> the kubelet not restarting pods that are in Failed/Evicted, on assumption
> that some other controller will recreate them
>
> This seems to be the bug to me. If the static pod were to really use up a
> lot of disk space, restarting it might end up freeing up disk space.
>

There are 3 bugs. We're not fixing them in 2016, that's what this bug is
about.

**Comment by bprashanth** [comment]
To clarify, I didn't mean there was something wrong with the implementation of cadvisor, or any other disk management stats reporting pipe. 

I meant: if we're going to sort based on QoS and make disk pressure evictions, the amount of disk a pod consumes needs to be controllable through QoS (including, of course, the size of the r/w layer). Otherwise, sort based on actual disk, so something that uses < 10mb doesn't ever get killed when there's pressure. 

As of 48h ago I hadn't even opened the eviction manager file, so this is solely based on production debugging.
