### ISSUE TITLE
PodDisruptionBudget by percentage doesn't work with StatefulSets

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#39125]
Is it intentional that the disruption controller isn't aware of StatefulSets? They appear to work together when the budget is configured with a static minimum number of pods, but not when configured with a percentage because the controller `finders` don't include StatefulSets:
https://github.com/kubernetes/kubernetes/blob/f49442d4331052c3141c47a3f9701da7082ebcff/pkg/controller/disruption/disruption.go#L204
https://github.com/kubernetes/kubernetes/blob/f49442d4331052c3141c47a3f9701da7082ebcff/pkg/controller/disruption/disruption.go#L557

The events for the disruption budget resource show the error message from the second link ("Failed to calculate the number of expected pods: asked for percentage, but found no controllers for pod "cockroachdb-0"), leaving it with no idea how many pods are expected.

This is with client and server both at v1.5.1.

@foxish @erictune

**Comment by foxish** [comment]
Thanks @a-robinson ! Looks like we missed this one. The real fix for this issue would be to use controllerRefs instead of hard-coded lists of controllers, which will ensure that even custom/third party controllers with a scale subresource are covered, but that's in the 1.6 timeframe. For now, I'll send a PR to add StatefulSet to the list of controllers it recognizes.

/cc @kow3ns @enisoc

**Comment by a-robinson** [comment]
Thanks @foxish! Is the simpler fix something that'll be pulled into a 1.5.x patch release?

**Comment by foxish** [comment]
@a-robinson Just created the PR. I expect that it should get into the next patch release.
/cc @saad-ali.

**Comment by foxish** [comment]
@mwielgus we need to cherrypick https://github.com/kubernetes/kubernetes/pull/39454 and https://github.com/kubernetes/kubernetes/pull/39544 into release-1.5 to have this fixed for the next point release. But there are merge conflicts. I am not familiar enough with the disruption controller to understand the other changes that have gone in. Could you please take a look?

**Comment by foxish** [comment]
ping @mwielgus

**Comment by foxish** [comment]
@davidopp, @mwielgus, can someone help cherrypick this into 1.5? I'm sure other folks are going to hit this issue as well as they use StatefulSets with PDB.
