### ISSUE TITLE
Proposal: spec the seccomp profile format

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#39128]
Seccomp is supported by annotations today in both kubernetes api (#25324) and CRI (#33500):

- `security.alpha.kubernetes.io/seccomp/container/<container name>` for containers
- and `security.alpha.kubernetes.io/seccomp/pod` for pod

The candidate values include`localhost/<profile-name>`, which indicates the profile installed to the node's local seccomp profile root.

So from the API, only the profile path is defined and the profile format is not defined clearly.

Althoughthe docker's [seccomp profile format](https://docs.docker.com/engine/security/seccomp/) is supposed at the beginng time, we are adding other runtimes by CRI, so it's time to spec the seccomp profile format clearly.

## candidate formats

There are three candidate formats in my opinion (please let me know if I missed others):

- oci [seccomp](https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#seccomp) (also reference runc's [seccomp](https://github.com/opencontainers/runc/blob/master/libcontainer/configs/config.go#L30)
- docker's [seccomp](https://docs.docker.com/engine/security/seccomp/): docker's seccomp of v1.10~1.12 is same with oci seccomp, but it introduces [ArchMap](https://github.com/docker/docker/blob/master/api/types/seccomp.go#L9) in v1.13.
- define a new one of kubernetes

I prefer to define a new one based on oci seccomp and add `ArchMap` to it because of 

- more stable api 
- and not missing features according different runtimes

@euank @yujuhong @Random-Liu @timstclair @mrunalp WDYT

cc/ @kubernetes/sig-node-misc

**Comment by mikebrow** [comment]
I prefer to stay with the OCI spec, so we don't have to define a new one and can use one that is a standard.

**Comment by dims** [comment]
@feiskyer can we close this one in favor of #52827 ?

**Comment by dims** [comment]
The issue above has more details. 

/close
