### ISSUE TITLE
Kubemark-scale is failing to start for the last ~24 hours

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#39134]
It seems that after merging the PR with hollow-node-problem-detector, kubemark-scale failed to start in every ~10 tries it has. This should be debugged and fixed ASAP.

It started here:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/130

and all subsequent runs are failing in the same way.

@gmarek @shyamjvs

**Comment by wojtek-t** [comment]
All tests are failing with:
```
Found only 4318 ready Nodes while waiting for 5000.
```

I guess this is due to lack of resources in the cluster. I mean when you added requests for hollow NPD, we can have less of hollow nodes on a single machine, which in turn means that we can't schedule on 5000 hollow-nodes on 51 machines. We should probably increase cluster size.

**Comment by wojtek-t** [comment]
Also, please update documentation about it in:
https://github.com/kubernetes/community/blob/master/contributors/devel/kubemark-guide.md

**Comment by shyamjvs** [comment]
Yes, seems like the external cluster size is the problem. Thank you for pointing this @wojtek-t .
Which among the following options do you think is better:
1. Make the cluster size 75 (which is 1.5 times 51) as the number of hollow containers on each hollow node has become 1.5 times.
2. Do some kind of binary search to come up with the optimal number of machines required now (it might turn up to be 75).

**Comment by shyamjvs** [comment]
3. Or maybe increasing the cluster size by a factor of 1.158 (= 5000/4318) makes more sense?

**Comment by gmarek** [comment]
It's easy to compute knowing:
- how many cores/mem each machine has
- how many cores/mem daemons running on each machine request
- how many cores/mem all non-daemon cluster addons request
- how many cores/mem single hollow-node needs.

**Comment by shyamjvs** [comment]
Is there a good way to find these metrics?
Also, I think that computing using these metrics would also lead us to 1.158 which is (no. of hollow-needs required i.e. 5000) / (no. of hollow-nodes that could be started i.e. 4318).
Because all the metrics that you suggested are constant values and so no. of machines required should grow linearly with the no. of hollow nodes we need.

**Comment by wojtek-t** [comment]
@shyamjvs - we should compute it (as @gmarek pointed out). You should take a look at resources requested by all addons in the cluster + static pods.

We definitely shouldn't created 75 machines, as this will for sure be too much.

Also to reduce the overhead, we should switch to larger machines, instead of more machines. But this should be backed by computations how many resources do we need.

**Comment by wojtek-t** [comment]
@shyamjvs - the easiest way to figure out how many resources each system pod is using is to login to the existing cluster a listing pods from kube-system namespace and checking their requests fields.

**Comment by shyamjvs** [comment]
Much better now for the run https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/149 :
`Found only 4999 ready Nodes while waiting for 5000`

This pretty much justifies the calculation for increasing nodes 1.158 times.
So increasing `NUM_NODES` by 1 more and making it 60 should work for now.
Once we are sure it works, we can then experiment with other machine types (as @wojtek-t suggested)  and the resource calculations (as @gmarek suggested).

**Comment by gmarek** [comment]
With 10 per machine we'd need a custom 10-core VMs (or 11 to be safe). We were using 8-cores only, as we were close max-pods-per-node limit.

**Comment by shyamjvs** [comment]
Looks like 150 ran successfully but 151 and 152 failed again with
`I1222 15:19:17.398] Found only 4998 ready Nodes while waiting for 5000.
W1222 15:20:28.506] Error from server (ServerTimeout): the server cannot complete the requested operation at this time, try again later (get pods)`
Could it be the case that master machine also needs to be upgraded with so many extra requests coming from the NPDs?

**Comment by wojtek-t** [comment]
We already have a pretty large master, and it should be enough. You should take a look into logs, but my personal feeling is that it's not about the kubemark cluster, but we may be facing some issues with the external cluster. At least the "Server Timeout" is coming from the external cluster.

**Comment by shyamjvs** [comment]
I have been confusing
> how many cores/mem different components request (in their pod configs)
with
> how many cores/mem different components actually consume (during run-time)
So after @gmarek 's suggestion to compute based on various resource requests, I was instead trying to optimize the number of nodes we require to run 5k hollow-nodes w.r.t. their run-time resource consumption.
Thank you for the clarification @wojtek-t .

**Comment by shyamjvs** [comment]
It doesn't really affect the reasoning for the scaling factor of 1.158 we calculated. But here are the resource calculations (which also agree with the requirement of 60 nodes for kubemark-gce-scale) :

>
Node VM type: "n1-standard-8"
No. of cores = 8
Total memory = 30GB (i.e. 3.75GB/core)

Resources requested by daemons:
- kube-proxy
  #cores = 0.1
  Memory = <unspecified> (~30MB on an average)
- node-problem-detector
  #cores = 0.02
  Memory = 20MB

Resources requested by addons:
- fluentd-cloud-logging
  #cores = 0.1
  Memory = 200MB

Misc daemons like systemd, journald, dockerd:
  #cores = ~0.1 (on an average)
  Memory = ~300MB (on an average)

Resources requested by a single hollow-node:
No. of cores = 0.09 (Kubelet-0.05 + Kubeproxy-0.02 + NPD-0.02)
Total memory = 220MB (Kubelet-100MB + Kubeproxy-100MB + NPD-20MB)

Computation of no. of allowable hollow-nodes:
Max allowed hollow-nodes on the VM (from CPU usage) = (8 - 0.32)/0.09 = ~85
Max allowed hollow-nodes on the VM (from Mem usage) = (30 - 0.55)/0.22 = ~133

Thus, the limiting factor is CPU and we can allow a maximum of
10.6 hollow-nodes/core on the "n1-standard-8" VM.

**Comment by shyamjvs** [comment]
Can we close this issue now that kubemark-scale is working fine?
