### ISSUE TITLE
event.go:198] Server rejected event '&api.Event{TypeMeta:unversioned. 

### ISSUE THREAD

**Issue by keith4743** [kubernetes/kubernetes#39143]
I reinstalled the kubernetes and docker app on one node, and the k8s can not register in...

centos 7
kubernetes 1.2

Dec 22 16:14:31 docker-server03 kubelet: I1222 16:14:31.749973 13349 kubelet.go:1086] Setting node annotation to enable volume controller attach/detach
Dec 22 16:14:31 docker-server03 kubelet: I1222 16:14:31.912775 13349 kubelet.go:1198] Attempting to register node node03.stg-k8s.com
Dec 22 16:14:31 docker-server03 kubelet: E1222 16:14:31.916140 13349 kubelet.go:1222] Unable to register node "node03.stg-k8s.com" with API server: the body of the request was in an unknown format - accepted media types include: application/json, application/yaml

Dec 22 16:14:31 docker-server03 kubelet: E1222 16:14:31.919250 13349 event.go:198] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"node03.stg-k8s.com.149284cdfd0a4f7d", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]api.OwnerReference(nil), Finalizers:[]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Node", Namespace:"", Name:"node03.stg-k8s.com", UID:"node03.stg-k8s.com", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientDisk", Message:"Node node03.stg-k8s.com status is now: NodeHasSufficientDisk", Source:api.EventSource{Component:"kubelet", Host:"node03.stg-k8s.com"}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63617990047, nsec:606787965, loc:(*time.Location)(0x4c8a780)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63617991271, nsec:912700360, loc:(*time.Location)(0x4c8a780)}}, Count:175, Type:"Normal"}': 'the body of the request was in an unknown format - accepted media types include: application/json, application/yaml' (will not retry!)

**Comment by keith4743** [comment]
resolved, the version installed with yum is kube1.3 now, but my cluster is kube1.2~~so, reinstall kube1.2 and it worked.

**Comment by jeunii** [comment]
KeithTt are you saying that the KubeMaster is on v1.3 while the minions are on 1.2 ? Im currently facing a similar issue where I have master and minions on v1.2 . I updated one minion to 1.3 and got the same ERROR as you "accepted media types include: application/json, application/yaml' (will not retry!)"
