### ISSUE TITLE
Eliminate api/conversion.go

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#3914]
Forked from #2306 and #3854. 

api/conversion.go shouldn't exist. We should always be converting to/from some versioned API object.

/cc @thockin @yujuhong @lavalamp

**Comment by thockin** [comment]
I agree in principle.  Currently it holds:

util.Time : externalized copy operator

resource.Quantity : externalized copy operator

A few transforms around ContainerManifest used, eg, in kubelet file reading
code.

**Comment by bgrant0607** [comment]
I'd also be fine with pruning it down.

Kubelet should use pods and otherwise have a Real, versioned API, so the manifest/boundpod transformations should disappear.

**Comment by lavalamp** [comment]
The manifest/boundpod transformations need to stick around as long as the containerVM.

**Comment by bgrant0607** [comment]
It makes no sense to me for those transformations to be in api/conversion.go.

**Comment by smarterclayton** [comment]
This is horribly out of date.  While there is some ugliness in conversion, the gradual use of versioned clients has made this of an issue people have to worry about.

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (168/150 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o8.sgmail.github.com ([167.89.101.199]:46634)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-5c7e-dev=imwiz.com@sgmail.github.com>)
	id 1dGTNT-000Vqe-IF
	for dev@imwiz.com; Thu, 01 Jun 2017 10:55:16 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Ra4ra2N/8eOXrbVfEyKW7UCvkaI=; b=fMNaPDkSynM9D3Qr
	eAeMft2DsKgJpMYMRF8L308DsoOGkZPZFoS/AxjOknnJO+vp3pD0/adAYM8yaM/d
	yHGxQMcrxYiXPWjcTJn52+pdng467n6/GyUTYQe9MODXh5Ydrj893hrYDDlRdsaL
	zwxlCC1KYiTzQm7Z6YAD2f9ay5M=
Received: by filter0504p1mdw1.sendgrid.net with SMTP id filter0504p1mdw1-11764-593046CF-40
        2017-06-01 16:54:39.666368855 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id FZrMwMLXT4-d8skukjw2DA
	for <dev@imwiz.com>; Thu, 01 Jun 2017 16:54:39.628 +0000 (UTC)
Date: Thu, 01 Jun 2017 09:54:39 -0700
