### ISSUE TITLE
Dead code in qos.go?

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#39148]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
No.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
VM running on OpenStack KVM with 8GB RAM.
- **OS** (e.g. from /etc/os-release):
Centos7.0
- **Kernel** (e.g. `uname -a`):
3.10.0-229.el7.x86_64
- **Install tools**:

- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by ravisantoshgudimetla** [comment]
Specifically these are functions: GetQOS, allResources, isResourceGuaranteed, isResourceBestEffort.

**Comment by jayunit100** [comment]
So, are you suggesting these are dead code?
