### ISSUE TITLE
Pods Manifests files starting with . are picked up by Kubelet

### ISSUE THREAD

**Issue by ls-yann-david** [kubernetes/kubernetes#39156]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Repport

**Kubernetes version** (use `kubectl version`):  1.5.1 (Both Server and Client)

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): UBUNTU 16.04
- **Kernel** (e.g. `uname -a`): 4.4.0-47-generic
- **Install tools**: Chef

**What happened**:
Kubelet picks up dot files in --pod-manifest-path causing stuff to breaks by replacing existing pods. 

**What you expected to happen**:
Exclude dot files from being picked up under --pod-manifest-path

**How to reproduce it** (as minimally and precisely as possible):
Take any manifest, copy it as .SOMETHING.conf and kubelet will deploy that new manifest

**Anything else do we need to know**:
From the slack channel it's been identified to be introduce by https://github.com/kubernetes/kubernetes/issues/27137 (by @bensons on Slack)

```
I1222 09:17:26.471779   17570 file.go:156] Reading config file "/etc/kubernetes/manifests/.chef-etcd20161222-18738-1tcrmas.yaml"
```

**Comment by resouer** [comment]
Just sent a simple fix, while still open for discussion.
