### ISSUE TITLE
kubectl tests pass even if a command failed

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#39168]
kubectl tests seem to be passing even if a command fails.

Debug and fix this.

cc @janetkuo

**Comment by nikhiljindal** [comment]
cc @kubernetes/sig-cli-misc

**Comment by ymqytw** [comment]
> kubectl tests seem to be passing even if a command fails.

@nikhiljindal What tests? Unit or e2e or test-cmd.sh? I'm lack of context.

**Comment by nikhiljindal** [comment]
`make test-cmd` which runs `hack/make-rules/test-cmd.sh` which contains all kubectl tests

**Comment by liggitt** [comment]
test-cmd.sh is passing with failing tests and allowing breaking changes to merge

**Comment by liggitt** [comment]
cc @fabianofranz

**Comment by soltysh** [comment]
😭 I know, I can't get to that one... once I'm done with openshift related bugs, I'll get to this one...

**Comment by deads2k** [comment]
In the future, I think a "tests don't run" bug that doesn't have a resolution in few hours should revert the pull that cause the problem asap.  Now we're going to have a very difficult time sorting out all the breaks.

**Comment by liggitt** [comment]
the rewrite in https://github.com/kubernetes/kubernetes/pull/38844 was the cause. it is ignoring errexit from all tests within runTests

**Comment by deads2k** [comment]
> the rewrite in #38844 was the cause. it is ignoring errexit from all tests within runTests

I'd support a deletion all test-cmd updates since the last working commit, stomp of test-cmd, comment out any currently failing test, p0 issue to fix up.

**Comment by pwittrock** [comment]
@jessfraz Would you jump on this?

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/40428 re-enables test-cmd.sh failures... working through the broken tests now

**Comment by fabianofranz** [comment]
tks @liggitt

**Comment by nikhiljindal** [comment]
thanks @liggitt
