### ISSUE TITLE
Flaky TestDefaulting unit test

### ISSUE THREAD

**Issue by lukaszo** [kubernetes/kubernetes#39180]
It looks like the test starts/stops to fail after running make update.

Latest failure: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/39157/pull-kubernetes-bazel/1541295815963780175/
Previous failures: https://github.com/kubernetes/kubernetes/pull/37959#issuecomment-265180618
https://github.com/kubernetes/kubernetes/pull/38614#issuecomment-267585502
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
--- FAIL: TestDefaulting (0.24s)
	defaulting_test.go:153: expected rbac.authorization.k8s.io/v1alpha1, Kind=ClusterRoleBindingList to trigger defaulting due to fuzzing
FAIL
```

Increasing number of iterations fixes the problem for me.

**Comment by kargakis** [comment]
@deads2k this is the issue we were discussing. @lukaszo has opened a fix in https://github.com/kubernetes/kubernetes/pull/39181 but I am not sure about it.

**Comment by islinwb** [comment]
@lukaszo @kargakis  Hi! Any theories on why the number of iterations is set to "300" (not larger). Error occured in our code based on v1.7.3:
`--- FAIL: TestDefaulting (0.60s)
	defaulting_test.go:181: expected /v1, Kind=EndpointsList to trigger defaulting due to fuzzing
FAIL`
It passes after I changed it to 500. The actual iter times is 427. 
Does the actual iter times varies randomly? The actual iter times is 172 when the test is run on two machines with the original v1.7.3 code.
Thanks a lot!

**Comment by lukaszo** [comment]
@islinwb see the comment from the @smarterclayton  https://github.com/kubernetes/kubernetes/pull/39181#issuecomment-269025245

**Comment by islinwb** [comment]
@lukaszo Many thanks!
