### ISSUE TITLE
Add hostNetwork label to container_network_* metrics

### ISSUE THREAD

**Issue by bluecmd** [kubernetes/kubernetes#39198]
**FEATURE REQUEST**

Right now the Kublet has wonderful container network metrics available on :10250/metrics. They look like this:

```
container_network_receive_bytes_total{container_name="POD",id="/docker/071efb9a6f23660fbe2d7c467014047199c43b738377884f70cffa87fb12231d",image="gcr.io/google_containers/pause-amd64:3.0",interface="cali219ebf6ead7",name="k8s_POD.d8dbe16c_kube-apiserver-fohn.cmd.nu_kube-system_554739cd0d280dac79c4164928497f0b_3b46221c",namespace="kube-system",pod_name="kube-apiserver-fohn.cmd.nu"} 1.74892610746e+11
...
container_network_receive_bytes_total{container_name="POD",id="/docker/071efb9a6f23660fbe2d7c467014047199c43b738377884f70cffa87fb12231d",image="gcr.io/google_containers/pause-amd64:3.0",interface="eno1",name="k8s_POD.d8dbe16c_kube-apiserver-fohn.cmd.nu_kube-system_554739cd0d280dac79c4164928497f0b_3b46221c",namespace="kube-system",pod_name="kube-apiserver-fohn.cmd.nu"} 6.77326392398e+11
...
container_network_receive_bytes_total{container_name="POD",id="/docker/0c651e1717ed927a7db581f1eb66d507437f9b7116dec07d806a57729dccfd46",image="gcr.io/google_containers/pause-amd64:3.0",interface="eno1",name="k8s_POD.d8dbe16c_kube-controller-manager-fohn.cmd.nu_kube-system_d7a905765bf317b4333abae612a544f5_19c2dc2b",namespace="kube-system",pod_name="kube-controller-manager-fohn.cmd.nu"} 6.77328972021e+11
...
container_network_receive_bytes_total{container_name="POD",id="/system.slice/var-lib-rkt-pods-run-2adcdbf3\\x2d3225\\x2d4a1c\\x2d9eca\\x2dd699dcd45267-stage1-rootfs-opt-stage2-hyperkube-rootfs-var-lib-docker-containers-af3125411f7a0846409eeafe2fb4c0458e5a90f024d72670090f5c3cf9e65c31-shm.mount",image="gcr.io/google_containers/pause-amd64:3.0",interface="eth0",name="k8s_POD.d8dbe16c_flood-0_media_762f8ca1-c850-11e6-b7c2-ac162d706004_5100aa07",namespace="media",pod_name="flood-0"} 6.08575213e+08
```

I handpicked four metric instances above: two for apiserver, one for kube-controller-manager, and one for a normal pod named "flood-0".

The first three use "hostNetwork: true" which means that the interface counters they export are the same, as can be seen above (look at interface="eno1", slight difference due to ongoing traffic in sampling I assume). The last one is from the pod itself (interface="eth0").

The problem:
When operating on these counters it is up to the end-user to know what pods are sharing interfaces (hostNetwork: true) and which are reporting only for themselves.

Proposed solution(s):
A. Make the containers only take into account the bytes produced by the specific pod, even in the case of hostNetwork: true. Not sure if this is feasible, but would be the best solution.
B. Provide an easy way for users to tell if the pod is using shared interfaces, by for example adding "host_network="1" as a label.

**Comment by nilsher** [comment]
Agreed, running a ceph cluster and the ceph traffic is picked up by the pods running on the hostnetwork so get really incorrect info on how much traffic is produced by pod themself.

**Comment by sfudeus** [comment]
To my knowledge, this issue is still valid and makes it hard to consume those metrics. Most likely it would be feasible to always filter on interface="eth0" when consuming those, but emitting those is not really useful in the first place. 
I have one example where a query for `container_network_receive_bytes_total{pod_name="calico-node-hqnpj"}` does emit 22 metrics (i.e. 4 host interfaces, a tunnel inteface from calico, one relevant eth0 interface and 16 cali* interfaces from other pods on the host.

**Comment by surajssd** [comment]
Yes this is still an issue.

**Comment by Jean-Daniel** [comment]
Still an issue.

>  Most likely it would be feasible to always filter on interface="eth0"

No, as there is no guarantee the host isn't "eth0".
