### ISSUE TITLE
Cannot run Kubernetes 1.5.1 on AWS using get.k8s.io

### ISSUE THREAD

**Issue by gauravjos** [kubernetes/kubernetes#39192]
**This is a...** 

- Bug Report

**Problem:**
Cannot run the kubernetes Cluster v1.5.1  with get.k8s.io on AWS with following  
export KUBE_AWS_ZONE=us-west-2a
export NUM_NODES=1
export MASTER_SIZE=t2.micro
export NODE_SIZE=t2.micro
export AWS_S3_REGION=us-west-2
export KUBE_AWS_INSTANCE_PREFIX=kube1.5.1
export KUBE_OS_DISTRIBUTION=jessie
export MASTER_DISK_SIZE=5
export MASTER_ROOT_DISK_SIZE=8
export NODE_ROOT_DISK_SIZE=8
export AWS_SSH_KEY=$PWD/kube1.5.1.key
export KUBERNETES_PROVIDER=aws; wget -q -O - https://get.k8s.io | bash
export PATH=$PATH:$PWD/kubernetes/client/bin

Kubectl is not working since APIServer container on the k8s master is failing. 

**Page to Update:**
http://kubernetes.io/docs/getting-started-guides/aws/ for changes in kubernetes 1.5.1.

Kubernetes version 1.5.1

**Comment by zmerlynn** [comment]
There's an issue in 1.5.0 and 1.5.1 that prevent AWS from coming up, and we were late catching it. It's fixed in 1.5.2.
