### ISSUE TITLE
kubectl to ssh node

### ISSUE THREAD

**Issue by ddysher** [kubernetes/kubernetes#3920]
While it's possible for k8s admin/users to ssh into nodes from cloudprovider, it is nicer to provide a ssh subcommnd within kubectl. This helps us provide a consistent view of kubernetes cluster.  So instead of
```
gcloud compute ssh instance --zone=us-central1-b
```
or
```
ssh -i blabla user@ip
```
Client can just do:
```
kubectl ssh node NodeName
```
where NodeName is the canonical node resource name in kubernetes, e.g. from `kubectl get node`.

One option is to provide pod id, so
```
kubectl ssh node NodeName -p PodID
```
will ssh to the host where PodID is running.

**Comment by derekwaynecarr** [comment]
Cc / @agoldste

**Comment by bgrant0607** [comment]
See also #1513

**Comment by ncdc** [comment]
@derekwaynecarr this looks more to me like wanting to be able to ssh from an admin's computer to a node in the cluster using a helper/shortcut in kubectl. The work I've been doing on adding the ability to get a shell or run arbitrary commands in containers is addressing a different use case, I think.

**Comment by thockin** [comment]
every time you need to SSH into the nodes there is an issue with kubernetes
overall.  This should be a "break glass in case of fire" situation.

**Comment by ddysher** [comment]
#1513 and #3253 in general, is a separate issue.  This is basically a client thing.

Agree admin should not care about singular node, but I think this is a reasonable use case for an admin, esp for paranoid admin :).  Plus, ssh into nodes doesn't necessary mean an issue within kubernetes; it might as well mean features we don't yet support, for example, analyze app IO patterns, overcommitment, etc.

**Comment by thockin** [comment]
I'm not saying we should disallow SSH, just that we should probably not
invest much in a cross-cloud SSH abstraction

**Comment by llarsson** [comment]
I would like something similar to this, because some tasks require logging in to each node and modifying it. 

One such case is installing GlusterFS on the nodes themselves, as mentioned in [the official GlusterFS example](http://kubernetes.io/v1.0/examples/glusterfs/).

**Comment by pikeas** [comment]
+1, being new to k8s, I'd like to explore my masters and minions, which would be much easier if I could run `kubectl ssh <master or minion>`

**Comment by llarsson** [comment]
Not just for exploration, but those publicly exposed machines need software updates, too!

**Comment by xied75** [comment]
:+1:

**Comment by thockin** [comment]
I understand the desire for one tool to do it all, but ideally nodes are not even part of the conversation.  I just want to be

**Comment by thockin** [comment]
woops!

**Comment by Bretto** [comment]
+1

**Comment by Stephenitis** [comment]
+1

**Comment by bscott** [comment]
+1

**Comment by thockin** [comment]
I really don't think this is something kubectl can do for people - pathologically, kubelet and apiserver may be running in containers, so even doing SSH over our API probably won't land you on a real node.

**Comment by bluesbeyond** [comment]
how could i scp the .docker/config.json to each node when I want to avoid pullimageerror....

**Comment by olalonde** [comment]
fleetctl has this command and is quite useful for debugging:

![screenshot 2016-07-20 13 29 44](https://cloud.githubusercontent.com/assets/416585/17001957/1458963e-4e7e-11e6-961c-a88cf5559044.png)

Would be handy to have even if it's not documented in `kubectl --help`

**Comment by bacongobbler** [comment]
That is because fleet must be running directly on the host with systemd running, and it makes assumptions that there is a `core` user on the host. Essentially the equivalent to `fleetctl ssh my-machine-id` using SSH is 

```
ssh core@$FLEETCTL_TUNNEL
ssh core@my-machine-id
```

Since a kubelet could be running in a container, a `kubectl ssh` may land you in a container (as @thockin mentioned above) which would be useless other than to inspect the kubelet at an OS-level.

I feel like `kubectl exec` solves 80% of the problems admins had when debugging containers (vs. `fleetctl ssh`'ing into the node then `docker exec` into the container). The admin's perspective to hop on a node is already solved by `ssh`, and I don't think kubectl should be an admin tool for managing the kubelets or the cluster itself; just the resources deployed on top of kubernetes.

**Comment by bacongobbler** [comment]
To be clear, I'm not saying that implementing tooling to manage the kubelets/nodes/cluster would be foolish. I'm just proposing that `kubectl` is not the right place to do it. :)

**Comment by karolyi** [comment]
+1

**Comment by integrii** [comment]
👎

**Comment by jessehu** [comment]
+1
