### ISSUE TITLE
"kubectl get storageclass --all-namespaces" produces invalid output

### ISSUE THREAD

**Issue by bluecmd** [kubernetes/kubernetes#39200]
```
[bluecmd-laptop]$ kubectl get storageclass
NAME                TYPE
generic (default)   kubernetes.io/rbd   
[bluecmd-laptop]$ kubectl get storageclass --all-namespaces
NAMESPACE           NAME                TYPE
generic (default)   kubernetes.io/rbd   
```

I'm guessing there is no such thing as namespaces for StorageClass, but when given `--all-namespaces` the `NAMESPACE` column is added has no values, causing the data to be miss-aligned. This caused me quite some confusion until I realized what was going on - I usually use `--all-namespaces` on all my get commands.

**Comment by xingzhou** [comment]
seems like some empty string value issues, let me take a look

**Comment by xingzhou** [comment]
Checked the code, the cause should be method `printStorageClass` in `resource_printer.go` does not print the namespace value when `options.WithNamespace` is enabled. I will add the code&tests and submit a patch later.

**Comment by xingzhou** [comment]
re-checked the code, there is no handler code in method `printStorageClass` in `resource_printer.go` to handle the situation that "options.WithNamespace" is enabled. Besides, storageclass should be non-namespace related resource, we shall print an error message for this case. I'm working on a patch now to fix this.

**Comment by zjj2wry** [comment]
this work well now, so close
```
➜  kubectl git:(master) ✗ ./kubectl get storageclass --all-namespaces 
NAME                  PROVISIONER               AGE
heketi-storageclass   kubernetes.io/glusterfs   57d
➜  kubectl git:(master) ✗ ./kubectl get storageclass                  
NAME                  PROVISIONER               AGE
heketi-storageclass   kubernetes.io/glusterfs   57d
```
