### ISSUE TITLE
Premature iSCSI logout

### ISSUE THREAD

**Issue by CristianPop** [kubernetes/kubernetes#39202]
When multiple pods use different iSCSI volumes from the same target on the same node, DetachDisk prematurely logs out from the target, even though there other active pods using the other volumes from the same target. Additionally, if the OS has been booted using iSCSI as well, this will leave the system unusable.

I've noticed that the prefix returned by extractDeviceAndPrefix does not contain the host plugin directory, as returned by host.GetPluginDir(iscsiPluginName), and therefore getDevicePrefixRefCount always returns 1 as reference count.

I've also noticed that the iSCSI logout command is not limited to the given volume iSCSI interface. 

I would like to submit a patch that addresses these issues.

OS: CentOS Linux release 7.2.1511 (Core)

Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+82450d0", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"not a git tree", BuildDate:"2016-12-20T15:11:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+82450d0", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"not a git tree", BuildDate:"2016-12-20T15:05:19Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by rootfs** [comment]
@CristianPop also see #41041 and #40941. Are you going to create a pull request?

**Comment by CristianPop** [comment]
I've read the issues you've linked and they describe the same problems I've faced and addressed in the fix.

I will create a pull request. The only reason that kept me from doing it already is that I wanted to follow the contributors' guide.
