### ISSUE TITLE
NodePort services not working as expected on AWS, possibly due to IAM ELB permissions

### ISSUE THREAD

**Issue by amitkgupta** [kubernetes/kubernetes#39214]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No, I think it's a bug.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): "NodePort", "AWS", "CreatingLoadBalancerFailed"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report.

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+82450d0", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"not a git tree", BuildDate:"2016-12-14T04:09:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:16:27Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release):

```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

- **Kernel** (e.g. `uname -a`):

```
Linux 4.4.26-k8s #1 SMP Fri Oct 21 05:21:13 UTC 2016 x86_64 GNU/Linux
```

- **Install tools**: Terraform v0.8.1, small [fork](https://github.com/amitkgupta/kops/commit/6e267a3c6bdab17e9eb10e2340e33217135c09cb) of `kops` (and `nodeup`)
- **Others**:
   - [Gist](https://gist.github.com/amitkgupta/d5ff7dfc691c0e55162f9196b61964d2) with details of cluster operations
   - AMI: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21

**What happened**:

Deployed a service of type `NodePort` to my cluster, expecting to be able to reach my service on any of the nodes' public IPs and the given port, but I can't.  There's 1 master and 2 non-master nodes, and no process is even bound to port 30095 except on the master node.  SSH'ing onto the master and curling that port in a variety of ways does nothing (`curl` just hangs).  Curling the `endpoints` associated with the service works fine.  `kubectl describe` on the service suggests there was some error creating a load balancer, but I don't know why it would be doing that.

It's probably important to note that I specifically disabled the IAM role used by the master nodes from being able to do any ELB things.  I don't want developers using my Kubernetes cluster to be able to spin up ELB's in my account, or do anything for that matter that would create AWS resources in my account.

**What you expected to happen**:

See above.

**How to reproduce it** (as minimally and precisely as possible):

See above for information about the environment and the problem.  See below for details about how the problem manifests.

* information about service (commands run from local workstation) -- note `CreatingLoadBalancerFailed` error in output of `kubectl describe service`:

```
$ kubectl get services frontend -oyaml
apiVersion: v1
kind: Service
---SNIP---
  ports:
  - nodePort: 30095
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: guestbook
    tier: frontend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

$ kubectl describe services frontend
Name:			frontend
Namespace:		default
Labels:			app=guestbook
			tier=frontend
Selector:		app=guestbook,tier=frontend
Type:			NodePort
IP:			100.67.10.125
Port:			<unset>	80/TCP
NodePort:		<unset>	30095/TCP
Endpoints:		100.96.1.2:80,100.96.2.2:80,100.96.2.4:80
Session Affinity:	None
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason				Message
  ---------	--------	-----	----			-------------	--------	------				-------
  1h		4m		15	{service-controller }			Warning		CreatingLoadBalancerFailed	(events with common reason combined)
```

* looking for processes bound to port on non-master node:

```
$ netstat -tulpn | grep 30095
# no output
```

* looking for processes bound to port on master node:

```
$ netstat -tulpn | grep 30095
tcp6       0      0 :::30095                :::*                    LISTEN      1540/kube-proxy
```

* attempting to curl the service (just hangs):

```
$ curl localhost:30095
# just hangs
^C

$ curl -g -6 http://[::1]:30095
# just hangs
^C

$ curl -vvvg -6 http://[::1]:30095
* Rebuilt URL to: http://[::1]:30095/
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to ::1 (::1) port 30095 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: [::1]:30095
> Accept: */*
>
# just hangs after that
^C

$ curl 100.67.10.125:30095
# just hangs
^C
```

* curling an endpoint from master node (works, so the pods are running fine):

```
$ curl 100.96.2.4
<html ng-app="redis">
  <head>
---SNIP---
  </body>
</html>
```

**Anything else do we need to know**:

As mentioned, the master and non-master nodes are running on VMs with IAM instance profiles based on IAM policies, none of which allow any ELB actions.  The pods and services were all based on the Guestbook all-in-one example, modified to use `NodePort` services.

Cross-posted:

* StackOverflow: http://stackoverflow.com/questions/41311813/nodeport-services-not-working-as-expected-on-aws-possibly-due-to-iam-elb-permis
* Mailing list: https://groups.google.com/forum/#!topic/kubernetes-dev/JNC_bk1L3iI

**Comment by justinsb** [comment]
The problem is that we don't know if we should _remove_ an existing ELB we created previously.

If you grant read-only permissions for ELB, you should be able to create NodePort services without any trouble, and prevent users from creating ELBs

**Comment by amitkgupta** [comment]
Thanks, I ended up doing that.  I think the referenced PR which was closed would solve the issue too.
