### ISSUE TITLE
when i create a deployment,failed to fit in any node fit failure on node (home-server): PodToleratesNodeTaints

### ISSUE THREAD

**Issue by 928255095** [kubernetes/kubernetes#39220]
pod (java110-registry-520578653-d8n7i) failed to fit in any node fit failure on node (home-server): PodToleratesNodeTaints

please help me

**Comment by resouer** [comment]
Use `kubectl describe node NODE_NAME` to check if any taint is wrongly added to your node.

For taint please reference: http://kubernetes.io/docs/user-guide/kubectl/kubectl_taint/

**Comment by 928255095** [comment]
thank you ,the question resolved
i want to pod run on the master ,but i don't remove the taints

kubectl taint nodes --all dedicated-

it is my careless
