### ISSUE TITLE
Kubernetes CI setup for s390x

### ISSUE THREAD

**Issue by gajju26** [kubernetes/kubernetes#39229]
**Is this a request for help?**: yes

**What keywords did you search in Kubernetes issues before filing this one?** : Kubernetes CI setup 

---

**Kubernetes version** (use `kubectl version`): NA

**Environment**: 
- **Cloud provider or hardware configuration**: NA
- **OS** (e.g. from /etc/os-release):  "Ubuntu" "16.04.1 LTS (Xenial Xerus)"
- **Kernel** (e.g. `uname -a`):  s390x GNU/Linux
- **Install tools**: NA
- **Others**: NA

**What happened**:   I have closed two PRs #36050  and  #37092  for adding s390x support. 

**What you expected to happen**: I need to setup Kubernetes CI setup for s390x. I am looking for some guidelines so that I can setup Kubernetes CI setup for s390x. What are the prerequisites and hardware configuration need to do this job.

**Comment by gajju26** [comment]
@luxas @ixdy  Do we have any link or document which can help me to setup Kubernetes CI for s390x?

**Comment by ixdy** [comment]
@fejta @krzyzacy can you advise?

**Comment by ixdy** [comment]
@kubernetes/test-infra-maintainers

**Comment by krzyzacy** [comment]
Does it want something like what we did with kopeio/azure, where you add your ci job to testgrid so you can monitor it? Or should we somehow make our Jenkins agents support s390x?

**Comment by ixdy** [comment]
I think the former - Google doesn't have any s390x hardware.

**Comment by krzyzacy** [comment]
You can run your test and upload the result to a gcs bucket, then add config like [kopeio](https://github.com/kubernetes/test-infra/blob/master/testgrid/config/config.yaml#L846-L852) to testgrid, then you will be able to monitor your job runs from [testgrid](https://k8s-testgrid.appspot.com/).

**Comment by krzyzacy** [comment]
I would say it does not have to be on jenkins - 
Create your own jobs/foo.sh, make a cronjob which checkouts test-infra and then runs jenkins/bootstrap.py with proper flags should work? @fejta am I correct?

**Comment by gajju26** [comment]
To correct any confusion, I am rephrasing my original post:
We would like to know that Kubernetes CI can be extended to support z system. Please let us know what support will be required from IBM side (we are aware on the H/w support). 
 
We have already completed this activity for cAdvisor.  We think there are two ways to achieve this:
1. We can provide you s390x machines on which we will setup Jenkins slave node to build Kubernetes and you present Jenkins master will manage this node.
2. If the above approach is not possible, then we can setup our own Jenkins server to run Kubernetes CI. In this case you will need to setup github hooks to let our jenkins post build results to Kubernetes github.
 
Please let us know your comments.

**Comment by luxas** [comment]
In either case, I think we should do this with kubeadm and make that deployment the default for s390x, since it's multiarch from the beginning.

**Comment by gajju26** [comment]
Hi Luxas,

I am trying to use kubeadm for extending Kubernetes CI for s390x. While using kubeadm I came to know that the required docker image "gcr.io/google_containers/etcd-s390x:3.0.14" is not published for s390x. I think in Kubernetes we have enabled the code so that etcd image will be pushed to gcr.io.

Regarding CI: I understand using kubeadm we can create a node and using "kubeadm join --token=<token> <master-ip>" we can join Kubernetes CI cluster by providing master-ip.  My question is once s390x cluster node is available for you then how Kubernets CI will be instantiated on this s390x node? I mean Kubernetes master will initiate this by creating a pod using yaml file?

correct me if my understanding is wrong.

**Comment by fejta** [comment]
Yes, the desired end state is that the s390x machines join a kubernetes cluster, and run kubernetes pods.

Our prow deployment monitors github etc for commits/comments/timer events and schedules the appropriate pods to complete the desired testing.

BTW, right now we are in the middle of migrating our jobs to use kubernetes pods. Would either of you two like to help this process? If so contact @krzyzacy @spxtr or I on #sig-testing slack.kubernetes.io and/or file an issue in the test-infra repository.

**Comment by ixdy** [comment]
https://github.com/kubernetes/kubernetes/pull/36050#issuecomment-272007705 has status of the s390x images from a month ago.

Basically, we couldn't build an etcd image for s390x then because the golang version (1.6.3) didn't support s390x. It's now using 1.7.4, so it seems to work, though it looks like etcd v2.2.1 doesn't build:
```
HEAD is now at 75f8282... *: bump to v2.2.1
# github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt
gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt/db.go:85: undefined: maxMapSize
gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt/db.go:85: invalid array bound maxMapSize
done
cp: cannot stat ‘/tmp/tmp.1FhNKQY6BY/etcd’: No such file or directory
cp: cannot stat ‘/tmp/tmp.1FhNKQY6BY/etcdctl’: No such file or directory
cp: cannot stat ‘/tmp/tmp.42RbdWma5q/etcd’: No such file or directory
cp: cannot stat ‘/tmp/tmp.42RbdWma5q/etcdctl’: No such file or directory
```

The rest of the build process gives worrying messages, but I'm guessing this is because the etcd process changed in v3:
```
HEAD is now at fd17c91... version: bump to v2.3.7
cp: cannot stat 'bin/s390x/etcd*': No such file or directory
done
```
```
HEAD is now at 8a37349... version: bump to v3.0.14
cp: cannot stat 'bin/etcd*': No such file or directory
done
```

Anyway, `gcr.io/google_containers/etcd-s390x:3.0.14` has now been pushed.

**Comment by luxas** [comment]
Thanks @ixdy, I think 3.0.14 is the only thing that's required (s390x is new after all, so we don't have to build things were moving away from to it)

Anyway, @ixdy could you tag the image `3.0.14` `3.0.14-kubeadm` as well?
That's the image kubeadm is currently using while waiting for a stable etcd3 tag.

/cc @timothysc @wojtek-t

**Comment by ixdy** [comment]
has anything in source control been adding the `-kubeadm` tags? or has it just been ad hoc?

**Comment by luxas** [comment]
@ixdy Nothing under source control because it was a push that was a once-only push for kubeadm so we could release the stable version of it (and there weren't any other etcd3 images at the time)
However, as soon as we get a source-controlled tag we can rely on for all arches, we'll switch

**Comment by ixdy** [comment]
tagged `gcr.io/google_containers/etcd-s390x:3.0.14-kubeadm`.

**Comment by gajju26** [comment]
@fejta : I would like to help on migrating jobs to use kubernetes pods. I will be a newbie and may need some guidelines for this task.

**Comment by XiLongZheng** [comment]
Looks like the cluster created by `kubeadm init` will need calico image to work together for network? Unfortunately, I didn't find calico image for s390x yet. Is calico a must have?
