### ISSUE TITLE
scheduler: PodFitsHostPorts predicate funcs does not respect HostIP

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#39228]
I create a Pod Pod-A who export a port to host, and specify the HostIP this port to bound with,  then manually scheduled it to Node-A. Since a Node-A could have multiple IP, so I expected other Pod who claim the same port to expose but bind to a different IP can also be scheduled to Node-A. However, `PodFitsHostPorts` just take port into account, without considering the IP. Seems it is a bug?

 @davidopp

**Comment by bjb2010** [comment]
It happened when I want to do the same thing. Does the PodFitsHostPorts only take port into account, without considering the IP?

**Comment by davidopp** [comment]
> Does the PodFitsHostPorts only take port into account, without considering the IP?

IIUC, this issue is a feature request to handle multiple host IPs per node?

**Comment by bjb2010** [comment]
yes，I want to run three pods on one node, and three pods expose the same port.
