### ISSUE TITLE
add windows as kubernetes node (kubenet not found)

### ISSUE THREAD

**Issue by yangshuai93** [kubernetes/kubernetes#39235]
kubelet,apiserver ,controller and scheduler : 1.5

add one windows server 2016 to linux cluster

I followed the guides here: http://kubernetes.io/docs/getting-started-guides/windows/ 
the pod is running , but the network can't connect with other nodes in cluster

**Comment by yangshuai93** [comment]
yes  it is .

**Comment by funky81** [comment]
i'm having this problem also. any suggestions on how to get it work?
