### ISSUE TITLE
Allow creating RBAC RoleBindings w/ SubjectAccessReview

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#39258]
Right now, the only way to create a RoleBinding is if the user creating that RoleBinding already has the role it is attempting to grant. This means that users w/o RBAC permissions have no way to bootstrap anything.

We should support a separate permission check to allow other authorizers to grant RBAC roleBinding creation permissions.

**Comment by deads2k** [comment]
> We should support a separate permission check to allow other authorizers to grant RBAC roleBinding creation permissions.

This is an idea we've kicked around.  I'm ok with it in the abstract, but we should hammer it out before starting an impl.

@liggitt @kubernetes/sig-auth-misc

**Comment by liggitt** [comment]
I think a verb check on the clusterrole or role being bound would make sense.

Straw man: check if the user has permission to perform the "bind" verb on the role or clusterrole.

**Comment by deads2k** [comment]
> Straw man: check if the user has permission to perform the "bind" verb on the role or clusterrole.

I'm ok with this.

**Comment by cjcullen** [comment]
I'm fine with that.

Is "clusterrole" or "role" the right noun? Isn't this "create"-ing a "{cluster}rolebinding"?

A couple possibly related questions:
How do you get permission to delete a rolebinding?
Can you update a rolebinding?

**Comment by liggitt** [comment]
The configured authorizer (ABAC, RBAC, whatever) is used to determine whether you can create/update/delete a rolebinding or clusterrolebinding at all. That works today.

When creating or updating, the rolebinding/clusterrolebinding resthandler is doing an additional check to determine if you are allowed to bind the particular role/clusterrole referenced in the binding. It currently checks that by testing whether you currently have RBAC roles that grant you all the permissions contained in the referenced role/clusterrole. That effectively prevents escalation (you can't grant permissions you don't have), but means that you can't have a user whose only permissions is to bind roles or clusterroles.
