### ISSUE TITLE
kops failures due to RBAC

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#39256]
We had a long run over break where `kops` testing was broken (because I didn't get a change to reeanble submit queue blocking yet). After I fixed that issue, the tests are now failing due to RBAC, very clearly. See [1464](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/1464) and [1465](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/1465). The most likely culprit seems to be the work in #38627, but I'm looking for a quick fix. For refence, `kops` is still in `AlwaysAllow`, and tests *should not* require RBAC yet.

**Comment by liggitt** [comment]
kops is green again, closing this
