### ISSUE TITLE
Invalid bearer token should return 401, not 403

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#39267]
Opening per https://github.com/kubernetes/kubernetes/pull/39266#discussion_r94003866. This error seems to return a 403 in GCE (where this test is passing), but on an `AlwaysAllow` (vs `RBAC,AlwaysAllow`) cluster, it's returning a 401.

**Comment by liggitt** [comment]
@zmerlynn what auth is configured in GCE?

**Comment by zmerlynn** [comment]
I just brought up a cluster at master. Looks like it's `--authorization-mode=RBAC` now.
