### ISSUE TITLE
Kubernetes RC should enhanced ?

### ISSUE THREAD

**Issue by apachemycat** [kubernetes/kubernetes#39262]
When RC reduce Pod replica ,It should first notify Kube-proxy that this Pod instance is in  Dropping status and Kube-proxy should remove it from load balance table so no new request will proxied to this Pod ,then RC waiting 5 minutes  for all existing request finished ,it can gracefully terminate this Pod.

**Comment by MrHohn** [comment]
When the pod is marked terminating, it(as an endpoint) will be removed from the service's endpoints pool on the API Server immediately. kube-proxy will then remove the routing rules once it got the update. This happens fairly fast. 

And what you says could be achieved by not letting the pod terminate(by handling the SIGTERM or adding preStop hook) until the grace period ends. The "Termination of Pods" section on http://kubernetes.io/docs/user-guide/pods/ and http://kubernetes.io/docs/user-guide/container-environment/#container-hooks might be good references.

**Comment by apachemycat** [comment]
Thanks for hint.

**Comment by calebamiles** [comment]
@apachemycat has your issue been resolved? Can this issue be closed?

**Comment by calebamiles** [comment]
Closing this issue @apachemycat. Please re open if your issue has not been addressed or add a comment linking to any additional information that others with a similar question might find useful. Thanks!
