### ISSUE TITLE
How can I rolling update use the restful api ?

### ISSUE THREAD

**Issue by ZPerling** [kubernetes/kubernetes#39261]
How can I rolling update use the restful api ?

**Comment by kargakis** [comment]
You can use Deployments. When a change in the pod template of a Deployment is done, the Deployment controller performs a rolling update.

**Comment by ZPerling** [comment]
@kargakis Thank you . But I'm using rc , because it can ensures that a specified number of pod “replicas” are running at any one time. What should I do

**Comment by krmayankk** [comment]
@ZPerling Deployment can also ensure that a specified number of pod replicas are running at any one time. Deployments under the hood, create ReplicaSets to handle that. Take a look here http://kubernetes.io/docs/user-guide/deployments/

**Comment by ZPerling** [comment]
@kargakis @kargakis I try use PATCH /api/v1/namespaces/{namespace}/replicationcontrollers/{name} to update the rc, 
```
def update_rc():
    data = {
        "spec" : {
            "spec" : {
                "containers" : {
                    "image" : "172.31.14.229:5000/trading/trading-merge:v46"
                }
            }
        }
    }
    post_data = json.dumps(data)
    url = kubernetes_apiserver + "/namespaces/trading/replicationcontrollers/merger"
    req = urllib2.Request(url, post_data)
    req.get_method = lambda: 'PATCH'
    req.add_header("Content-Type","application/json-rpc")
    resp = urllib2.urlopen(req)
    return resp.read()
```
Reponse Error  : HTTP Error 415: Unsupported Media Type

Do you know why, Thank you very much.

**Comment by kargakis** [comment]
ReplicationControllers / ReplicaSets do not run upgrades, you need to switch to Deployments (similar object to a ReplicationController, manages ReplicaSets which are a replacement for ReplicationControllers). Have a look at the link @krmayankk posted above. 

In the error specifically you see you need to remove "-rpc" from the content type header.

**Comment by ZPerling** [comment]
@kargakis @krmayankk Thanks. I switch to Deployments , It is working for me . But I use api update deployment there are still problems . 
Code:
```python
def update_rc():
    data = [{
        "kind" : "Deployment",
        "spec" : {
            "template":{
                "spec" : {
                    "containers" : {
                        "image" : "172.31.14.229:5000/trading/trading-merge:v44"
                    }
                }
            }
        }
    }]
    post_data = json.dumps(data)
    print post_data
    url = "http://xxx:8081/apis/extensions/v1beta1/namespaces/trading/deployments/merger"
    req = urllib2.Request(url, post_data)
    req.get_method = lambda: 'PATCH'
    req.add_header("Content-Type","application/json-patch+json")
    resp = urllib2.urlopen(req)
    return resp.read()
```

 Found error log in api-server access log:
>E1230 15:14:03.622802    1547 errors.go:63] apiserver received an error that is not an unversioned.Status: Unexpected kind: unknown

Request body has been included in the kind of value , Please help me

**Comment by ZPerling** [comment]
@kargakis @krmayankk Thanks. I switch to Deployments , It is working for me . But I use api update deployment there are still problems . 
Code:
```python
def update_rc():
    data = [{
        "kind" : "Deployment",
        "spec" : {
            "template":{
                "spec" : {
                    "containers" : {
                        "image" : "172.31.14.229:5000/trading/trading-merge:v44"
                    }
                }
            }
        }
    }]
    post_data = json.dumps(data)
    print post_data
    url = "http://xxx:8081/apis/extensions/v1beta1/namespaces/trading/deployments/merger"
    req = urllib2.Request(url, post_data)
    req.get_method = lambda: 'PATCH'
    req.add_header("Content-Type","application/json-patch+json")
    resp = urllib2.urlopen(req)
    return resp.read()
```

 Found error log in api-server access log:
>E1230 15:14:03.622802    1547 errors.go:63] apiserver received an error that is not an unversioned.Status: Unexpected kind: unknown

I do not know why  , Please help me

**Comment by kargakis** [comment]
Use application/json for the content-type

**Comment by ZPerling** [comment]
@kargakis  When I use "Content-Type", "application / json" ,the following error occurs
> HTTP Error 415: Unsupported Media Type

**Comment by ZPerling** [comment]
@kargakis   Thanks. My problem is solved。

**Comment by cbatra** [comment]
@ZPerling what was the fix for this?

**Comment by uditalias** [comment]
@ZPerling did you managed to find out?

**Comment by warmchang** [comment]
Try "Content-Type: application/merge-patch+json" or "Content-Type: application/strategic-merge-patch+json".

FYI: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#patch-operations
