### ISSUE TITLE
[Federation] `kubefed init` should also work on clusters without a service load balancer implementation

### ISSUE THREAD

**Issue by moonek** [kubernetes/kubernetes#39271]
**Kubernetes version** (use `kubectl version`):
v1.5.1

**Environment**:
- **Cloud provider or hardware configuration**: Virtaulbox VM in my notePC.
- **OS** (e.g. from /etc/os-release): Ubuntu 14.04.5 LTS
- **Kernel** (e.g. `uname -a`): 3.13.0-101-generic
- **Install tools**: kube-up.sh
- **Others**:

**What happened**:
`kubefed init` is no response.
```
root@vagrant-ubuntu-trusty-64:~# kubefed version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
root@vagrant-ubuntu-trusty-64:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
root@vagrant-ubuntu-trusty-64:~# cat .kube/config
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://172.28.128.31:8080
  name: cluster0
contexts:
- context:
    cluster: cluster0
    user: ubuntu
  name: cluster0
current-context: cluster0
kind: Config
preferences: {}
users:
- name: ubuntu
  user:
    password: SNWdoDxHtWqGZwNG
    username: admin
root@vagrant-ubuntu-trusty-64:~# kubectl config get-contexts
CURRENT   NAME       CLUSTER    AUTHINFO   NAMESPACE
*         cluster0   cluster0   ubuntu
root@vagrant-ubuntu-trusty-64:~# kubectl get po --all-namespaces
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE
kube-system   kube-dns-4101612645-8wj8s               4/4       Running   0          6h
kube-system   kubernetes-dashboard-3543765157-wzd8s   1/1       Running   0          6h
root@vagrant-ubuntu-trusty-64:~# kubefed init fellowship --host-cluster-context=cluster0
```
=> no response and logging about over 10 minutes..
=> after `ctrl-c` that status, i found only "federation-system" namespace and 
"fellowship-apiserver" service.

**What you expected to happen**:
Installation of federation control plane

**How to reproduce it** (as minimally and precisely as possible):
same above

**Anything else do we need to know**:

**Comment by calebamiles** [comment]
Could someone from @kubernetes/sig-federation-misc please help with triage? Thanks!

**Comment by madhusudancs** [comment]
Did your service `fellowship-apiserver` get a load balancer address? Also, do you know whether there exists a load balancer implementation for your cloud provider?

**Comment by moonek** [comment]
All my k8s cluster is running on VirtualBox VMs in my laptop. So I don't have a load balancer.
In this case, is it impossible that use kubefed?

**Comment by emaildanwilson** [comment]
I hit this issue today as well trying to kubefed init against minikube.

**Comment by madhusudancs** [comment]
@moonek yeah, in the current implementation `kubefed` waits for a load balanced address. We need to fix this before going GA.

**Comment by emaildanwilson** [comment]
I managed to work around this with a local edit to kubefed that would set default values for the ip and hostname fields just to see what would happen...  I hit what will be the next issue. The only --dns-provider options for the federation-controller-manager are google-clouddns and aws-route53.

> controllermanager.go:155] Cloud provider could not be initialized: could not init DNS provider "google-clouddns": google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

**Comment by madhusudancs** [comment]
@emaildanwilson there is `coredns` support, in addition to `google-clouddns` and `aws-route53`, now - https://github.com/kubernetes/kubernetes/blob/master/federation/pkg/dnsprovider/providers/coredns/coredns.go#L33

**Comment by emaildanwilson** [comment]
awesome... this doc should get updated then. https://kubernetes.io/docs/admin/federation-controller-manager/

**Comment by marun** [comment]
I ran into this same issue trying to deploy a federation control plane on minikube with kubefed.  I ended up switching to 'oc cluster up' since by default it runs the [external ip allocator](https://docs.openshift.com/container-platform/latest/admin_guide/tcp_ingress_external_ports.html) I wrote.  The controller allocates an ip from a private range to services of type LoadBalancer, and adding a static route for the range allows access from the host.  I wasn't sure if the controller would be useful outside of openshift, but it came in pretty handy in this case so maybe it's worth upstreaming.

**Comment by marun** [comment]
#40536 is the umbrella issue for tracking this and others targeting improvements in non-cloud deployment of the federation control plane.

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by madhusudancs** [comment]
This is already done and is going into v1.6.

Ref: PR #40516.
