### ISSUE TITLE
kubectl port-forward failing to stay alive

### ISSUE THREAD

**Issue by etotheipi** [kubernetes/kubernetes#39289]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  
Bug Report

**Kubernetes version** (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:49:33Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:16:27Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```
(just noticed the version mismatch, I wonder if that's related?)

**Cloud provider or hardware configuration**:  
AWS setup using kops 1.4.4

**What happened**:
I have a `registry:2` pod running inside the AWS k8s cluster, which has a proxy running so it appears to be `localhost:5000` to all the nodes in the cluster.  From my dev machine, I run `kubectl port-forward --namespace kube-system kube-registry-v2-upfi0 5000:5000` and it gives me the expected:

```
Forwarding from 127.0.0.1:5000 -> 5000
Forwarding from [::1]:5000 -> 5000
```

When I retag and push an image from my dev machine via `docker push localhost:5000/imgname`, it starts the upload but eventually freezes.  I  see a bunch of `Handling connection for 5000` messages in the port-forward terminal, and it does move along nicely for many minutes & megabytes.  I haven't timed it, but I'd guess it stops around 5 min.  If I ctrl-c out of the `docker push`, retrying hangs unless I kill the port-forward command to reinitiate.  For instance, here's where it hung last time:

```
$ docker push localhost:5000/imgname
The push refers to a repository [localhost:5000/imgname]
73e59ce703bc: Pushed 
6b1c829e9604: Pushing [==================================================>] 4.608 kB
d71909becc51: Pushing [==================================================>]  5.12 kB
eb81b28d4018: Pushing [=============>                                     ]  71.8 MB/264.9 MB
dc52a5d73a49: Pushing [=======================================>           ] 76.82 MB/98.2 MB
57627ae91f10: Waiting 
9a54167c4ef3: Waiting 
b4a89e95fd3a: Waiting 
bbf22e8718b9: Waiting 
34f91ac4ea19: Waiting 
94ba8f39b781: Waiting 
34e7b85d83e4: Waiting 
# No movement for 10+ min
^C
```

- It **does** work when I push small images.
- It **does** work when I `docker save` the image, `scp` it to one of the nodes, and do a `docker load` and `docker push` from there.  Therefore, the registry and it's proxy daemonset are working properly.

**What you expected to happen**:
I expect the port-forward to stay open and alive long enough to push any amount of data through it.

**How to reproduce it** (as minimally and precisely as possible):
Followed directions for the kube-registry add-on: 

https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry

**Anything else do we need to know**:
Is there some kind of implied size limit or timeout on the port-forward command?  Am I using it in a way not intended?

**Comment by calebamiles** [comment]
Could someone from @kubernetes/sig-node-misc or @kubernetes/sig-network-misc please help triage. Thanks!

**Comment by thockin** [comment]
This is probably not a sig-network issue, per se.  @lavalamp which SIG owns
the API proxy?  You?

**Comment by lavalamp** [comment]
@ncdc knows this stuff.

I think there is a long running operation timeout, possibly in an apiserver command line flag. But I'm pretty sure it'd be longer than 5 minutes by default, more like several hours. The timeout would start ticking from the port forward command, not from the docker push command.
