### ISSUE TITLE
Running kubernetes under LXC containers

### ISSUE THREAD

**Issue by dragoscirjan** [kubernetes/kubernetes#39282]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

kubernetes under LXC 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): I'm starting to think it's both.

I am trying to write a small simple cluster installer for my servers (I'm still at NOOB level), however, the main target was to run the Kubernetes instances under LXC containers.

```shell
#
# Install Master Server
#
QubeStash::Cluster::installBase(){
    QubeStash::Cluster::setupNetwork
    QubeStash::Cluster::setupSshKey

    which apt-get > /dev/null && {
    
        apt-get update
        apt-get install -y apt-transport-https dos2unix curl git lynx make openssh-server openssh-client redir

        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
            cat > /etc/apt/sources.list.d/kubernetes.list <<EOF
deb http://apt.kubernetes.io/ kubernetes-$(lsb_release -c | awk -F' ' '{print $2}') main
EOF

        apt-get update
        touch /.dockerenv
        apt-get install -y docker.io kubelet kubeadm kubectl kubernetes-cni

        return 0;
    }

    # {
    #     # if apt-get fails, fall back to ...
    #     QubeStash::Log::warn "Not using an Ubuntu/apt-get compatible OS. Will try using https://get.k8s.io"  
    #     export KUBERNETES_PROVIDER=vagrant
    #     curl -sS https://get.k8s.io | bash
    # }
}

#
# Install Master Server
#
QubeStash::Cluster::installMaster(){
    QubeStash::Cluster::installBase

    kubeadm init --api-advertise-addresses=$QSTASH_MASTER_IP,127.0.0.1 \
        --token=$QSTASH_MASTER_TOKEN $QSTASH_KUBEADM_PARAMS

    QubeStash::Log::info "Installing Kubernetes Weave ..."
    kubectl apply -f https://git.io/weave-kube

    QubeStash::Log::info "Installing Kubernetes Dashboard ..."
    # https://github.com/kubernetes/dashboard
    kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml

    # curl http://127.0.0.1:8080/ui
    QubeStash::Log::warn "To connect to dasboard, please use:"
    QubeStash::Log::warn "$ kubectl proxy --address=$QSTASH_MASTER_IP --port=8080"
    QubeStash::Log::warn "or, if this doesn\'t work,"
    QubeStash::Log::warn "$ redir --laddr=$QSTASH_MASTER_IP --lport=8080 --caddr=\$(kubectl get services --namespace kube-system | grep kubernetes-dashboard | awk -F ' ' '{print \$2}') --cport=8080"
    QubeStash::Log::warn 
    QubeStash::Log::warn "To connect a future worker to the kubernetes master, please use:"
    QubeStash::Log::warn "$ kubeadm  join --token $QSTASH_MASTER_TOKEN $QSTASH_MASTER_IP"
    echo
    echo 
}

#
# Install Master Server
#
QubeStash::Cluster::installWorker(){
    QubeStash::Cluster::installBase

    kubeadm join --token $QSTASH_MASTER_TOKEN $QSTASH_MASTER_IP
}
```

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**: -
- **OS** (e.g. from /etc/os-release): `Ubuntu Linux 16.04`
- **Kernel** (e.g. `uname -a`): `Linux qstashm 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**: [This script](https://github.com/qubestash/stash), but mainly using apt-get.
- **Others**: kubeadm version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2074+a092d8e0f95f52", GitCommit:"a092d8e0f95f5200f7ae2cba45c75ab42da36537", GitTreeState:"clean", BuildDate:"2016-12-13T17:03:18Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:

Problem occurs because LXC doesn't support modprobe. Obviously containers use the same kernel as the main OS, but do not allow their users to add new kernel modules. Which leads to such thing:

```shell
==> qstashmw1: [preflight] The system verification failed. Printing the output from the verification:
==> qstashmw1: OS: Linux
==> qstashmw1: KERNEL_VERSION: 4.4.0-42-generic
==> qstashmw1: CGROUPS_CPU: enabled
==> qstashmw1: CGROUPS_CPUACCT: enabled
==> qstashmw1: CGROUPS_CPUSET: enabled
==> qstashmw1: CGROUPS_DEVICES: enabled
==> qstashmw1: CGROUPS_FREEZER: enabled
==> qstashmw1: CGROUPS_MEMORY: enabled
==> qstashmw1: DOCKER_VERSION: 1.12.1
==> qstashmw1: DOCKER_GRAPH_DRIVER: aufs
==> qstashmw1: [preflight] Some fatal errors occurred:
==> qstashmw1: 	failed to parse kernel config: unable to load kernel module "configs": output - "modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-42-generic/modules.dep.bin'\nmodprobe: FATAL: Module configs not found in directory /lib/modules/4.4.0-42-generic\n", err - exit status 1
==> qstashmw1: [preflight] If you know what you are doing, you can skip pre-flight checks with `--skip-preflight-checks`
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Both master and worker throw similar errors.

**What you expected to happen**:

Question is simple. Do I have to change the entire architecture, which eventually would lead to a possible Kubernetes change with another cluster tool, or is there a [way](https://www.stgraber.org/2013/12/23/lxc-1-0-some-more-advanced-container-usage/) to modprobe the modules so that the install script won't crash. 

As a note, I don't really understand what `--skip-preflight-checks` does nor do I understand the role of `libkmod` within Kubernetes.

**How to reproduce it** (as minimally and precisely as possible):

Just download my script and run the demo script
```shell
wget -O - https://github.com/qubestash/stash/raw/master/install-lxc.sh | bash
DEBUG_LEVEL=5 /vagrant/q-stash install-master --hostname qstashm
```

**Anything else do we need to know**:

**Comment by ParagDoke** [comment]
Able to get kube packages installed using the following Vagrantfile and script.

```
Vagrant.configure(2) do |config|
  config.ssh.insert_key = false

  # LXC provider specific configuration
  config.vm.provider :lxc do |lxc, override|
    override.vm.box = "hrishikeshdate/xenial64"

    #Change lxc specific settings to host docker containers inside LXC container
    lxc.customize 'aa_profile','unconfined'
    lxc.customize 'cgroup.devices.deny' , nil

    lxc.customize 'cgroup.devices.allow', 'c 10:237 rwm' # loop-control
    lxc.customize 'cgroup.devices.allow', 'b 7:* rwm'    # loop*
    lxc.customize 'cgroup.devices.allow', 'c 10:200 rwm' # tun

    lxc.customize 'cap.drop' , nil
    lxc.customize 'mount.auto', 'proc:rw sys:ro cgroup:ro'
    lxc.customize 'hook.autodev', File.join(  File.dirname(__FILE__) , "createloopbackdevices")
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope       = :machine
    config.cache.auto_detect = true
  end
end

```
And the script:
```

#!/bin/bash
#
# Add loopback devices
#

mknod -m 600 ${LXC_ROOTFS_MOUNT}/dev/loop-control c 10 237

for i in {0..31}
do
  num="$i"
  dev="${LXC_ROOTFS_MOUNT}/dev/loop$num"

  if test -b "$dev"; then
    continue
  else
    mknod -m660 $dev b 7 $num
  fi
done

# Add tun devices
if ! [ -d ${LXC_ROOTFS_MOUNT}/dev/net ];then
 mkdir ${LXC_ROOTFS_MOUNT}/dev/net
fi
if ! [ -c ${LXC_ROOTFS_MOUNT}/dev/net/tun ]; then
 mknod -m 600 ${LXC_ROOTFS_MOUNT}/dev/net/tun c 10 200
# chmod 666 ${LXC_ROOTFS_MOUNT}/dev/net/tun
fi

```

Credits: Hrishikesh Date

**Comment by ParagDoke** [comment]
Install `linux-image-$(uname -r)` before running `kubeadm init` and that error should go away.

**Comment by dragoscirjan** [comment]
Made the suggested changes, which eventually lead to the following config for the LXC container:

```
##############################################
# Container specific configuration (automatically set)
lxc.rootfs = /var/lib/lxc/qstashm/rootfs
lxc.rootfs.backend = dir
lxc.utsname = qstashm

##############################################
# Network configuration (automatically set)
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:bd:f7:20

##############################################
# vagrant-lxc base box specific configuration
# Template used to create this container: /usr/share/lxc/templates/lxc-ubuntu
# Parameters passed to the template: --release wily --arch amd64
# For additional config options, please look at lxc.container.conf(5)

# Common configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf

# settings for systemd with PID 1:
lxc.kmsg = 0
lxc.autodev = 1
# allow unconfined and incomplete
lxc.aa_profile = unconfined
lxc.aa_allow_incomplete = 1

##############################################
# vagrant-lxc container specific configuration
# VAGRANT-BEGIN
lxc.aa_profile=unconfined
lxc.cgroup.devices.deny=
lxc.cgroup.devices.allow=c 10:237 rwm
lxc.cgroup.devices.allow=b 7:* rwm
lxc.cgroup.devices.allow=c 10:200 rwm
lxc.cap.drop=
lxc.mount.auto=proc:rw sys:ro cgroup:ro
lxc.hook.autodev=/opt/qubestash/lxc.createloopbackdevices
lxc.utsname=qstashm
lxc.mount.entry=/sys/fs/pstore sys/fs/pstore none bind,optional 0 0
lxc.mount.entry=tmpfs tmp tmpfs nodev,nosuid,size=2G 0 0
lxc.mount.entry=/opt/qubestash vagrant none bind,create=dir 0 0
lxc.mount.entry=/root/.vagrant.d/cache/hrishikeshdate/xenial64 tmp/vagrant-cache none bind,create=dir 0 0
# VAGRANT-END

And the output is...
```
      lxc-start 20170104104323.930 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1958 - cgroup 'devices.allow' set to 'c 5:2 rwm'
      lxc-start 20170104104323.930 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1958 - cgroup 'devices.allow' set to 'c 136:* rwm'
      lxc-start 20170104104323.930 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1958 - cgroup 'devices.allow' set to 'c 254:0 rm'
      lxc-start 20170104104323.930 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1958 - cgroup 'devices.allow' set to 'c 10:229 rwm'
      lxc-start 20170104104323.930 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1958 - cgroup 'devices.allow' set to 'c 10:200 rwm'
      lxc-start 20170104104323.930 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1958 - cgroup 'devices.allow' set to 'c 1:7 rwm'
      lxc-start 20170104104323.930 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1958 - cgroup 'devices.allow' set to 'c 10:228 rwm'
      lxc-start 20170104104323.930 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1958 - cgroup 'devices.allow' set to 'c 10:232 rwm'
      lxc-start 20170104104323.930 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1958 - cgroup 'devices.allow' set to 'c 10:237 rwm'
      lxc-start 20170104104323.930 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1958 - cgroup 'devices.allow' set to 'b 7:* rwm'var/lib/lxc
      lxc-start 20170104104323.930 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1958 - cgroup 'devices.allow' set to 'c 10:200 rwm'
      lxc-start 20170104104323.930 INFO     lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1962 - cgroup has been setup 'lxcbr0':
      lxc-start 20170104104323.970 DEBUG    lxc_conf - conf.c:lxc_assign_network:3106 - move 'vethKKBT5A'/'(null)' to '30810': . index is '47'
      lxc-start 20170104104323.971 DEBUG    lxc_conf - conf.c:setup_rootfs:1215 - mounted '/var/lib/lxc/qstashm/rootfs' on '/usr/lib/x86_64-linux-gnu/lxc'
      lxc-start 20170104104323.971 INFO     lxc_conf - conf.c:setup_utsname:843 - 'qstashm' hostname has been setups detected.
      lxc-start 20170104104323.982 DEBUG    lxc_conf - conf.c:setup_hw_addr:2146 - mac address '00:16:3e:8c:21:3f' on 'eth0' has been setup set to "1".
      lxc-start 20170104104323.982 DEBUG    lxc_conf - conf.c:setup_netdev:2373 - 'eth0' has been setup
      lxc-start 20170104104323.982 INFO     lxc_conf - conf.c:setup_network:2394 - network has been setup
      lxc-start 20170104104323.982 INFO     lxc_conf - conf.c:mount_autodev:1072 - Mounting container /dev
      lxc-start 20170104104323.982 INFO     lxc_conf - conf.c:mount_autodev:1095 - Mounted tmpfs onto /usr/lib/x86_64-linux-gnu/lxc/dev
      lxc-start 20170104104323.982 INFO     lxc_conf - conf.c:mount_autodev:1113 - Mounted container /dev
      lxc-start 20170104104323.983 ERROR    lxc_utils - utils.c:safe_mount:1746 - Device or resource busy - Failed to mount proc onto /usr/lib/x86_64-linux-gnu/lxc/proc
      lxc-start 20170104104323.983 ERROR    lxc_conf - conf.c:mount_entry:1650 - Device or resource busy - failed to mount 'proc' on '/usr/lib/x86_64-linux-gnu/lxc/proc'
      lxc-start 20170104104323.983 ERROR    lxc_conf - conf.c:lxc_setup:3790 - failed to setup the mount entries for 'qstashm't to 'c 1:3 rwm'
      lxc-start 20170104104323.983 ERROR    lxc_start - start.c:do_start:826 - Failed to setup container "qstashm".s.allow' set to 'c 1:5 rwm'
      lxc-start 20170104104323.983 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
      lxc-start 20170104104323.983 INFO     lxc_conf - conf.c:lxc_delete_network:2926 - Interface "(null)" with index 47 already deleted or existing in different network namespace.
      lxc-start 20170104104324.033 INFO     lxc_conf - conf.c:lxc_delete_network:2961 - Removed interface "vethSAS8ND" from host.o 'c 1:8 rwm'
      lxc-start 20170104104324.033 ERROR    lxc_start - start.c:__lxc_start:1338 - Failed to spawn container "qstashm".
      lxc-start 20170104104324.066 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
      lxc-start 20170104104329.071 ERROR    lxc_start_ui - tools/lxc_start.c:main:360 - The container failed to start.
      lxc-start 20170104104329.071 ERROR    lxc_start_ui - tools/lxc_start.c:main:362 - To get more details, run the container in foreground mode.
      lxc-start 20170104104329.071 ERROR    lxc_start_ui - tools/lxc_start.c:main:364 - Additional information can be obtained by setting the --logfile and --logpriority options.
```

Especially this line:
** lxc-start 20170104104323.983 ERROR    lxc_utils - utils.c:safe_mount:1746 - Device or resource busy - Failed to mount proc onto /usr/lib/x86_64-linux-gnu/lxc/proc**

**Comment by fuzzyhandle** [comment]
Ubuntu released a new image for xenial a few weeks back. 

I am using

Linux hddevbox1 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
You will also need to install aufs-tools package inside lxc is you are using aufs as storage backend. this package provides the auplink command to enable docker to mount rootsfs.

I still don't have a working pod, and the error I see in  some error wrt weave and cni. Still debugging...

**Comment by ParagDoke** [comment]
Btw, fuzzyhandle = Hrishikesh Date
He got it working using flannel (instead of weave) on LXC.
I could get it to work too using flannel.

**Comment by fuzzyhandle** [comment]
Right. flannel works. Having issues with weave.
I am OK with flannel, so going to dump weave and continue using flannel

**Comment by dragoscirjan** [comment]
Can you guys share a complete install script for both master and worker for LXC ?

**Comment by fuzzyhandle** [comment]
@dragoscirjan Kube install steps are very easy. Well documented here
[https://kubernetes.io/docs/getting-started-guides/kubeadm/](url)

What u need is

Host machine - Ubuntu Xenial with kernel => 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Install `aufs-tools` on the host

Inside lxc container install `aufs-tools` and `linux-image-$(uname -r)`. Then install docker and kubernetes packages.

You can also use the Vagrant File posted by @ParagDoke to setup lxc containers.

**Comment by roberthbailey** [comment]
This issue doesn't appear active. Can we close it?
