### ISSUE TITLE
Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached

### ISSUE THREAD

**Issue by mootezbessifi** [kubernetes/kubernetes#39294]
I am trying to set up EFK (elasticsearch, fluentd, kibana) on kubernetes cluster:
1. K8s cluster contains two minions (1.2.4) and one master (1.2.0).
2. nodes of the cluster are 3 CentOS 7 VMs.
 
So i used the following controller and service yaml files:

**fluentd-es.yaml**

https://github.com/kubernetes/kubernetes/blob/release-1.2/cluster/saltbase/salt/fluentd-es/fluentd-es.yaml

**es-controller.yaml, es-service.yaml, kibana-controller.yaml and kibana-service.yaml**

https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch

after running them, i had the following log output and kibana dashboard was unable to show me logs and charts (keep loading for ever like next image).
![screenshot 155](https://cloud.githubusercontent.com/assets/5040743/21538174/3b442a22-cdab-11e6-877b-2877e1a5278e.png).

**fluentd log snapshot:**
![screenshot 156](https://cloud.githubusercontent.com/assets/5040743/21538202/774f6ab8-cdab-11e6-9b24-0b8c6afa6925.png)

![screenshot 157](https://cloud.githubusercontent.com/assets/5040743/21538213/942e113e-cdab-11e6-9728-46a2b84df87a.png)

**elasticsearch log snapshot:**

![screenshot 158](https://cloud.githubusercontent.com/assets/5040743/21538221/a942d262-cdab-11e6-852a-ed535cefeb7f.png)

**kibana log snapshot:**

![screenshot 159](https://cloud.githubusercontent.com/assets/5040743/21538226/b7370d34-cdab-11e6-9003-f8dd5201b06f.png)

May someone tell me exactly was is the problem ?
Thanks in advance

**Comment by mootezbessifi** [comment]
@MrHohn  ant idea about that ?

**Comment by MrHohn** [comment]
Not familiar with this and not sure whom to ping :( @freehan

**Comment by mootezbessifi** [comment]
Thanks for your reply. May be @freehan has an explanation

**Comment by freehan** [comment]
Did you use all the elasticsearch-fluentd yamls from 1.2 release?

**Comment by mootezbessifi** [comment]
Thanks freehan for your quick reaction. I used yamls which i mentioned above. Even more, i tried with es and kibana controller and service yamls of k8s v1.2 branch (https://github.com/kubernetes/kubernetes/tree/release-1.2/cluster/addons/fluentd-elasticsearch) but the same problem occurs

**Comment by freehan** [comment]
I have been out of touch with logging for quite some time. A few things I could think of.


Check if logs arrives in elasticsearch and see if your elasticsearch cluster is in green status. You can verify by using elasticsearch API. 

If the logs are there, then there is a problem between kibana and elasticsearch. 

If not, then it means fluentd agents are not able to send logs to elasticsearch.
fluentd is sending logs to `elasticsearch-logging:9200`. Use `kubectl exec` to login into fluentd pod and check connectivity.

**Comment by mootezbessifi** [comment]
@freehan, What yamls version do I need to use with k8s 1.2 in final case? Or the issue is independent from it?

**Comment by freehan** [comment]
The ones from release-1.2 looks fine. 

https://github.com/kubernetes/kubernetes/tree/release-1.2/cluster/addons/fluentd-elasticsearch

**Comment by mootezbessifi** [comment]
@freehan, es is in green status. This is what is mentioned by kibana . But how can I check if logs arrives to elastic search ?

**Comment by mootezbessifi** [comment]
Thanks but what about fluentd-es.yaml? What is the best file to work with ?

**Comment by freehan** [comment]
https://github.com/kubernetes/kubernetes/blob/release-1.2/cluster/saltbase/salt/fluentd-es/fluentd-es.yaml

**Comment by mootezbessifi** [comment]
Thank you very much. Can you tell me how to check if logs arrives to es!

**Comment by freehan** [comment]
If I remember correctly, there should be only one index in elasticsearch. Check how many documents in that index and see if the count is raising. You can hit the elasticsearch service IP to get to elasticsearch API. Elastciesarch API doc: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html

**Comment by mootezbessifi** [comment]
From inside fluentd pod. I tried to make curl request to elasticsearch-logging:9200 and i get 200 code as response. It seems that fluentd can connect to ES.

**Comment by mootezbessifi** [comment]
@freehan 
Sorry for the delay, but unfortunately fluentd generates, after a while from starting, a huge logs that said:
emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit" tag="kubernetes.var.log.containers.elasticsearch-logging ... and becomes unable to send collected logs to ES.

**Comment by wangzhuzhen** [comment]
hi @mootezbessifi 
“queue size exceeds limit” means your ES cluster can not catch up the speed that fluentd send logs to it. There are two ways can solve this problem: (1) increase the buffer_queue_limit and buffer_chunk_limit to increase buffer size of fluentd output; (2) increase the number of your ES nodes. And the (2) may be the best choice.

**Comment by mootezbessifi** [comment]
@wangzhuzhen thanks a lot for your quick answer.
BTW i have a cluster with 2 CentOS 7 nodes. and an ES cluster with 2 replicas.
i am using kubernetes v1.2.0 on the master and v1.2.4 on the nodes 
i used the following sources:
kibana and ES : 
https://github.com/kubernetes/kubernetes/tree/v1.4.6/cluster/addons/fluentd-elasticsearch
fluentd
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml
i scaled up ES to 4 replicas. but the same problem appears so solution (2) did not work for me.
Concerning the first solution, how can i  increase the buffer_queue_limit and buffer_chunk_limit ?

**Comment by wangzhuzhen** [comment]
hi, @mootezbessifi  
If so, may be the speed that fluentd read log to buffer is too high and the size of your fluentd buffer is not enough.  You can modify your fluentd's config file /etc/td-agent/td-agent.conf to increase buffer size:

<match **>
  @type elasticsearch
  log_level info
  include_tag_key true
  host elasticsearch-logging
  port 9200
  logstash_format true
  buffer_type memory
  flush_interval 10
  # The number of threads to flush the buffer.
  num_threads 4
  # The interval between data flushes for queued chunk.
  queued_chunk_flush_interval 1
  retry_limit 17
  disable_retry_limit false
  retry_wait 1.0
  # Never wait longer than 5 minutes between retries.
  #max_retry_wait
  # Set the chunk limit the same as for fluentd-gcp.
  **buffer_chunk_limit 4M**
  # Cap buffer memory usage to 4MiB/chunk * 256 chunks = 1024 MiB
  **buffer_queue_limit 256**
  # HTTP request timeout
  flush_at_shutdown true
  request_timeout 60
  reload_connections false
  reload_on_failure true
</match>

**Comment by marcofranssen** [comment]
We are facing exactly the same issue. We have a 5 node es cluster. In our case this already happens after taking down fluentd just for 30 minutes. Once you bring it back it seems there is no way back to get it working. All kind of buffer flush issues and read timeouts are happening. Anyone found a solution to this? Or some way for fluentd to forward the logs in a safe way in order to catch up with the logs.

**Comment by iamparamvs** [comment]
Any solution to this issue? It's been a year now.
