### ISSUE TITLE
Tests that depend on multiple nodes being present should have a skip condition to detect that prerequisite

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#39308]
It should be possible to run the suite against a single node cluster (like mini-kube) and tests that cannot run because of certain requirements should skip themselves.  We do this for providers and other feature flag dependent tests, but not for some of the scheduler predicate tests.

In particular, `scheduler_predicates.go` has several that fail on single node tests, including `	`validates that InterPodAntiAffinity is respected if matching 2`.

We should do a pass and add conditions for those.

**Comment by smarterclayton** [comment]
NodeProblemDetector tests require a non-master node - they fail when they should skip.

**Comment by smarterclayton** [comment]
"should test kube-proxy" requires at least two nodes and errors when it should skip.

**Comment by spiffxp** [comment]
/remove-lifecycle stale
I'm not sure whether we now have a single way of describing this pattern or not.  It would be nice if we did.
