### ISSUE TITLE
Digital Ocean block storage

### ISSUE THREAD

**Issue by leshik** [kubernetes/kubernetes#39326]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

Digital Ocean, digitalocean

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST.

**Kubernetes version** (use `kubectl version`):

v1.5.1

**Environment**:
- **Cloud provider or hardware configuration**: Digital Ocean 
- **OS** (e.g. from /etc/os-release): CoreOS 1185.5.0 (MoreOS)
- **Kernel** (e.g. `uname -a`): 4.7.3-coreos-r3
- **Install tools**: manual
- **Others**: Flocker v1.15.0

**What happened**:

Seems that now there is no way to use Digital Ocean block storage as persistent volumes in k8s (cloud provider doesn't exist in `pkg/cloudprovider/providers`). Tried it in conjunction with flocker (with [this dataset plugin](https://github.com/ngrewe/digitalocean_flocker_plugin)) and got:

`Output: mount: special device /flocker/b3beb5d6-0919-47b4-9a05-1f6d9b45eb3c does not exist`.

**What you expected to happen**:

Successful mount of volume.

**How to reproduce it** (as minimally and precisely as possible):

Install flocker as per their manual, install Digital Ocean plugin, then try k8s flocker-web demo application.

**Anything else do we need to know**:

I searched issues and found #34783, but it focuses on cluster initial install rather than storage support.

**Comment by calebamiles** [comment]
Hello @leshik! You may have more luck getting attention on your feature request to [the Kubernetes Dev](https://groups.google.com/forum/#!forum/kubernetes-dev) mailing list. Perhaps @saad-ali could be more helpful in routing your request but it sounds like you would like for a digital ocean [storage provisioner](http://blog.kubernetes.io/2016/10/dynamic-provisioning-and-storage-in-kubernetes.html) to be created and if so the good people in @kubernetes/sig-storage-misc should be able to help you. The meeting times and contact information for the SIG can be found on [their SIG page](https://github.com/kubernetes/community/blob/master/sig-storage/README.md).

**Comment by baldwinSPC** [comment]
@calebamiles  @leshik we're looking at this now.  Ping me on slack if you have questions - 'baldwin' in #kubernetes.

**Comment by klausenbusk** [comment]
One option until there is "native" support is using a flexvolume plugin. I use [rexray](http://rexray.readthedocs.io/en/stable/) and I haven't noticed any major issues.

BTW: Isn't this issue a duplicate of https://github.com/kubernetes/kubernetes/issues/32334 ?

**Comment by nugrahawahyu** [comment]
@klausenbusk can you share link how to setup flexvolume using rexray on digitalocean?

**Comment by klausenbusk** [comment]
/close

I think this is safe to close now. [RexRay](http://rexray.readthedocs.io/) supports [DigitalOcean](http://rexray.readthedocs.io/en/stable/user-guide/storage-providers/digitalocean/) and has a [flexplugin](http://rexray.readthedocs.io/en/stable/user-guide/schedulers/kubernetes/), @StackPointCloud also has a [flexplugin](https://github.com/StackPointCloud/digitalocean-flex-volumes/), lastly a [DigitalOcean provisioner (including a flexplugin)](https://github.com/kubernetes-incubator/external-storage/tree/master/digitalocean) was just added to the kubernetes-incubator external-storage project.
