### ISSUE TITLE
Remove json tags from pkg/api/types.go

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#3933]
Previous discussion in #1004 and #3900.

We should never serialize the internal representation. Removing the json tags would make this clearer.

/cc @thockin

**Comment by bgrant0607** [comment]
The tags are a nuisance and a source of confusion, which is evident in the first couple sentences of #5459. Someone should just do the experiment of removing the tags to see if anything breaks.

**Comment by brendandburns** [comment]
not really a priority for 1.0 though...

--brendan

**Comment by piosz** [comment]
So @brendandburns, @bgrant0607 what is actual priority of this issue? I can do it.

**Comment by brendandburns** [comment]
Low.  Its one of the last things I'd do before v1.0, and I think we could
clearly ship 1.0 without it.  Improving the swagger api doc generation (and
docs in general) is way higher priority, for example.

Brendan

**Comment by bgrant0607** [comment]
@brendandburns This comes up in many API code reviews.

I just did:
```
sed -i 's/ *`json:[^`]*`//' types.go
```

Building and testing now.

**Comment by bgrant0607** [comment]
Failures, most likely due to things using the internal rep. where they should not:
```
--- FAIL: ExampleEmptyConfig (0.00s)
--- FAIL: ExampleOfOptionsConfig (0.00s)
FAIL    github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd/api      0.007s
--- FAIL: TestPrinters (0.00s)
FAIL    github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl   0.077s
--- FAIL: TestExtractFromHTTP (0.01s)
FAIL    github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/config    2.062s
```

**Comment by bgrant0607** [comment]
Kubelet test failure is probably due to a stray use of api.ContainerManifest here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/bdc1981eb5260f7baa456529b0e3cad9198c4ed3/pkg/kubelet/config/http_test.go#L155

**Comment by bgrant0607** [comment]
Since I determined what doesn't work, removed from 1.0 milestone and demoted priority.

**Comment by yujuhong** [comment]
#5632 fixes the Kubelet test.

**Comment by thockin** [comment]
#8294 took a stab at this and failed.

Sadly, the codebase is not ready for this.  Specifically:

1. clientcmd depends on api.TypeMeta (not documented) and the JSON tags therein.  
2. kubectl does a JSON marshal/unmarshal which breaks without the core JSON tags.

There may be more but I gave up.

**Comment by bgrant0607** [comment]
I'm now thinking we should eliminate api/types.go. Discussion here: https://github.com/GoogleCloudPlatform/kubernetes/issues/8190#issuecomment-114139999

**Comment by lavalamp** [comment]
Late to the party-- anything that serializes the internal structs is BROKEN and needs to be fixed. :( :(

**Comment by bgrant0607** [comment]
I completely agree.

My preference is to nuke api/types.go.

**Comment by liggitt** [comment]
We should prioritize this. It is masking issues like https://github.com/kubernetes/kubernetes/issues/23173

**Comment by thockin** [comment]
I just tried to remove these again.  It fails in jsonpath formatting, now.
