### ISSUE TITLE
Many WC processes

### ISSUE THREAD

**Issue by daniel-yavorovich** [kubernetes/kubernetes#39334]
Dear Sira/Madams,

I use Kubernetes v1.4.6 and see many **wc** processes. Some processes are running for a month.

```
# ps aux | grep -c '[wc]'
3790 
# ps auxffww | grep '[wc]' | head -125 | tail -10
root     29274  0.9  0.4 5705996 147268 ?      Ssl  Nov24 505:52 /usr/bin/dockerd -H fd:// --mtu=1472 --bip=10.1.42.1/24
root     29281  0.0  0.0 3388080 20264 ?       Ssl  Nov24   4:53  \_ docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim docker-containerd-shim --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --runtime docker-runc
root     29533  0.0  0.0 282564   936 ?        Sl   Nov24   5:16  |   \_ docker-containerd-shim 43862be3c4f16a0df9258806dff9bb3b4870d72e32b644442d2a57d5c9466a61 /var/run/docker/libcontainerd/43862be3c4f16a0df9258806dff9bb3b4870d72e32b644442d2a57d5c9466a61 docker-runc
root     29549  4.7  0.3 815028 119500 ?       Ssl  Nov24 2536:05  |   |   \_ /hyperkube kubelet --allow-privileged --api-servers=http://localhost:8080 --config=/etc/kubernetes/manifests-multi --cluster-dns=10.0.0.10 --cluster-domain=cluster.local --hostname-override=10.42.233.138 --v=2
root     29585  0.0  0.0 379220 15696 ?        S    Nov24   0:39  |   |       \_ journalctl -k -f
root     32761  0.0  0.0      0     0 ?        Z    Nov26   0:00  |   |       \_ [wc] <defunct>
root      9058  0.0  0.0      0     0 ?        Z    Nov27   0:00  |   |       \_ [wc] <defunct>
root     25592  0.0  0.0      0     0 ?        Z    Nov30   0:00  |   |       \_ [wc] <defunct>
root     12461  0.0  0.0      0     0 ?        Z    Dec01   0:00  |   |       \_ [wc] <defunct>
root     27458  0.0  0.0      0     0 ?        Z    Dec12   0:00  |   |       \_ [wc] <defunct>
```

You can answer what are generated by these processes, and is not this a bug?

Thank you.

**Comment by Typositoire** [comment]
I just restarted Kubelet (after a week) and I had 9000 wc zombies... I run on 1.5.1

**Comment by fraenkel** [comment]
This might be the same as #38894

**Comment by BugRoger** [comment]
It's not necessarily the same cause as in #38894. We're experiencing the same problem but have a full featured GNU find. It is related though.

**Comment by kargakis** [comment]
@kubernetes/sig-node-misc

**Comment by euank** [comment]
The fixes for #38894 should be in master, just not in any release branch.

@calebamiles wanna see about getting the two commits referenced in https://github.com/kubernetes/kubernetes/issues/38894#issuecomment-272909333 into the 1.5 release branch?

**Comment by dashpole** [comment]
The change in cAdvisor: [#1558](https://github.com/google/cadvisor/pull/1558) still needs to be vendored into kubernetes, and cherrypicked to 1.4

**Comment by calebamiles** [comment]
I actually don't know how cAdvisor is vendored into Kubernetes. @dashpole if you ping me on the PR that vendors into Kubernetes I can try and get it cherry picked.

**cc: @euank, @saad-ali**

**Comment by MartinPyka** [comment]
+1 for adding the fix for #38894 into the next release

**Comment by Bregor** [comment]
@daniel-yavorovich, @Typositoire do you use `weave-net`?

**Comment by daniel-yavorovich** [comment]
@Bregor no, I use flannel only.

Thank you.

**Comment by Bregor** [comment]
@daniel-yavorovich ok, thank you.

**Comment by stuszynski** [comment]
We're running on`v1.5.3` and we also have exact `wc` processes leak issue.  After the few days since the last restart of `kubelet`, we have hundreds of defunct `wc` processes with `hyperkube kubelet` as a parent.

```
$ ps ax | grep wc 
31902  0.0  0.0      0     0 ?        Z    10:51   0:00 [wc] <defunct>
32042  0.0  0.0      0     0 ?        Z    11:47   0:00 [wc] <defunct>
...
```

```
$ ps ax | grep wc | wc -l
1038
```

I also found some mentions in `kubelet` log:
```
Mar 14 21:51:19 kubernetes2 hyperkube[16528]: I0314 21:51:19.284652   16528 fs.go:495] killing cmd [find /var/lib/docker/overlay/4ea252565a33e2f5763648f95eeaa44d9d614fdb212b3d442d1915b1cba06393 -xdev -printf .], and cmd [wc -c] due to timeout(2m0s)
```


It looks like it's already solved by this commit: https://github.com/kubernetes/kubernetes/commit/c03ec462fd9599f89ad583679ae4a40b684ab300 (https://github.com/kubernetes/kubernetes/pull/39477 ). But it wasn't backported to v1.5 nor v1.4 yet.

**Comment by dashpole** [comment]
Working on getting it to 1.5, and 1.4 #43113

**Comment by golfreeze** [comment]
I've faced this bug also on v.1.5.3 ,
To fixed it , Shall I need to upgrade kubernetes , Right ?
If "YES" , Could you show the step ?
Thank you.

**Comment by dashpole** [comment]
The fix is in v1.5.6

**Comment by golfreeze** [comment]
Thank you dashpole!!

**Comment by calebamiles** [comment]
@dashpole are you still planning on fixing this for 1.4? Otherwise could probably close this issue.

**Comment by dashpole** [comment]
I am still planning on it.  I ran into a roadblock cherrypicking it to 0.24.2 in the cadvisor branch, but I dont remember what it was... Ill try and do that soon

**Comment by calebamiles** [comment]
Thanks for the update, @dashpole.

**Comment by calebamiles** [comment]
any news, @dashpole?

**Comment by dashpole** [comment]
Oh, sorry.  I dont think ill be able to get to this soon.  For those affected, 1.5 and 1.6 both have the fix for this.  We can probably just close this.

**Comment by euank** [comment]
Monthly reminder; I think this can be closed as fixed in 1.5+

**Comment by varsharaja** [comment]
I am seeing the same issue in 1.5.5. What exactly should I do to fix this? Our kubernetes was installed with the old setup-aws scripts and not with kops.

**Comment by dashpole** [comment]
@varsharaja as I mentioned [here](https://github.com/kubernetes/kubernetes/issues/39334#issuecomment-292561665), upgrading to 1.5.6 will fix this.

**Comment by varsharaja** [comment]
Thank you. Will do.
