### ISSUE TITLE
Apply for GSoC 2017

### ISSUE THREAD

**Issue by starsdeep** [kubernetes/kubernetes#39340]
Hi, I am master student who want to apply to GSOC 2017. After a few months attention to this project and reading some codes of k8s, I notice several features has hang for a very long time, which is not hard to implement actually, such as https://github.com/kubernetes/kubernetes/pull/18262 and https://github.com/kubernetes/kubernetes/issues/1348. I also have some ideas, such as: allow PVC to provision a PV from a Snapshot if k8s is running on a cloud provider. 

 I'd like to pick one of those features up during GSoC. Could you guys apply for GSoC 2017?

The "Org Application Starting Time" is January 19.

**Comment by starsdeep** [comment]
@bgrant0607 @smarterclayton

**Comment by calebamiles** [comment]
Hello @starsdeep, if you would like to request sponsorship for a GSoC project a better forum to coordinate with potential sponsors might be the Kubernetes Community Meeting which is held on Thursdays at 10am PST. You may add an item under "Future TOPICS" on the [agenda](https://docs.google.com/document/d/1VQDIAB0OqiSjIHI8AWMvSdceWhnz56jNpZrLs6o7NJY/edit#). Another possibly good place to ask about GSoC would be in the Contributor Experience Working Group; you may find more information about the Contributor Experience Working Group [at its SIG page](https://github.com/kubernetes/community/blob/master/sig-contribx/README.md) The next meeting looks to be scheduled for Wednesday 11 January at 9:30am PST. Hope to see you there and closing this issue.

**Comment by bgrant0607** [comment]
The last time we asked for volunteer mentors we didn't get enough volunteers to make it worthwhile to pursue.

**Comment by yuraerwqsdxz** [comment]
It has been investigated and confirmed that darkwebsolutions has one of the best customer services in hacking and anti hacking related issues, you can findout more by mailing darkwebsolutions on hackermail, darkwebssolutions on gmail, text or dial 19193076946
