### ISSUE TITLE
Multipathing has to be supported in iscsi plugin.

### ISSUE THREAD

**Issue by humblec** [kubernetes/kubernetes#39345]
iic, most of the iscsi targets provide multipathing using `multiple iscsi target portals` for the same `IQN` , thus multiple paths through initiator connections in each of it. However, kube `iscsi` plugin is not capable of receiving multiple TPs in its volume spec, thus lack this functionality. If iscsi volume spec.target portal can receive an array of `IPs` or `IPs:Port` instead of single value, the mounter can try to login in each path and get the mpath/mpio device created in the kubelet. but this require an API change.   

Any thoughts on this ?

**Comment by humblec** [comment]
@rootfs PTAL.

**Comment by humblec** [comment]
Can multipathed iscsi target can have different Lun numbers.?  iic, its possible eventhough admins wont configure that way. If that is the case, we cannot just change the TP field in volume spec to an array and get this resolved. It need to accommodate  different Lun numbers ..etc .. Any thoughts ?

**Comment by rootfs** [comment]
@fabiand

**Comment by humblec** [comment]
@fabiand Did you get a chance to look at this ?

**Comment by fabiand** [comment]
@humblec No, sadly not.

**Comment by humblec** [comment]
@rootfs @fabiand it looks to me that, multiple TP is good enough to achieve this goal. As long as we are 'logging in' all the available targets ( by a api spec change of TP from string to array)  we should be able to bring the mpath support with iscsi. What do you think?

**Comment by fabiand** [comment]
:+1: I think the change is simple - and I'd have done it the same way, by changing to a list of strings.

**Comment by fortcollins** [comment]
I'm running into issue badly. If you have the cod change or a patch, i will be happy to test it out.

**Comment by humblec** [comment]
Thanks. Let me give a try. 👍

**Comment by fabiand** [comment]
Could this actually be an dupe of #21306 ?

**Comment by humblec** [comment]
@fabiand Thanks,  yes,  this looks to be a duplicate. I tried to bring the multipath support by adding backup portal as discussed in @21306.

**Comment by humblec** [comment]
@fabiand The PR is merged in master and should be available from 1.6 :). Thanks!

**Comment by fabiand** [comment]
Kudos!

**Comment by fabiand** [comment]
Can this bug get closed?
