### ISSUE TITLE
ExternalName service doesn't generate Environment Variables for service discovery

### ISSUE THREAD

**Issue by vendrov** [kubernetes/kubernetes#39356]
Use case:
We would like to use K8S service discovery with external resource such as AWS RDS (DB).
So when when the pods are up they can use K8S generated environment variables for service discovery.

Currently only dns records are created: <svc-name>.<namespace>.svc.local.cluster

**Comment by calebamiles** [comment]
@vendrov could you please update your issue with the sections specified in the template

```
<!-- Thanks for filing an issue! Before hitting the button, please answer these questions.-->

**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):


**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

<!--
If this is a BUG REPORT, please:
  - Fill in as much of the template below as you can.  If you leave out
    information, we can't help you as well.

If this is a FEATURE REQUEST, please:
  - Describe *in detail* the feature/behavior/change you'd like to see.

In both cases, be ready for followup questions, and please respond in a timely
manner.  If we can't reproduce a bug or think a feature already exists, we
might close your issue.  If we're wrong, PLEASE feel free to reopen it and
explain why.
-->

**Kubernetes version** (use `kubectl version`):


**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:


**What happened**:


**What you expected to happen**:


**How to reproduce it** (as minimally and precisely as possible):


**Anything else do we need to know**:

```

If this feature request is scoped only to AWS please signal so that the feature request can be routed to the appropriate team for discussion and prioritization. Thanks!

**Comment by takama** [comment]
The same issue for any service with type `externalName`. k8s v1.5.3

**Comment by johngmyers** [comment]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No


**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): externalname service environment

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

(though it seems like a bug to me)

The externalName of ExternalName services should appear under the SERVICENAME_SERVICE_HOST environment variable in created containers.

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:06Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**: (presuming irrelevant)


**What happened**:

root@debug-f95f68697-2cx2d:/# printenv
HOSTNAME=debug-f95f68697-2cx2d
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.0.0.1
KUBERNETES_PORT=tcp://10.0.0.1:443
PWD=/
HOME=/root
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP=tcp://10.0.0.1:443
TERM=xterm
SHLVL=1
KUBERNETES_SERVICE_PORT=443
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBERNETES_SERVICE_HOST=10.0.0.1
_=/usr/bin/printenv


**What you expected to happen**:

Above should have additionally contained at least:

AUTHSERVICE_SERVICE_HOST=example.com

**How to reproduce it** (as minimally and precisely as possible):

kubectl create service externalname authservice --external-name example.com 
kubectl run -it debug --image debian:stretch

**Anything else do we need to know**:

/reopen
/remove-lifecycle rotten
