### ISSUE TITLE
'sparkDriver' could not bind on port dynamically with hostNetwork: true

### ISSUE THREAD

**Issue by zhanghao94** [kubernetes/kubernetes#39357]
We develop a web UI with jupyter notebook embed, and jupyter notebook is configured with spark kernel to connect to spark.  When we run docker container directly, it works fine with --net host
but when we use kubernetes(1.5.1), we got the following error when creating spark kernel dynamically, and it seems it can't get the port allocated.

17/01/02 10:54:08 [INFO] o.a.t.Main$$anon$1 - Kernel version: 0.2.0.dev1-incubating-SNAPSHOT
17/01/02 10:54:08 [INFO] o.a.t.Main$$anon$1 - Scala version: 2.11.8
17/01/02 10:54:08 [INFO] o.a.t.Main$$anon$1 - ZeroMQ (JeroMQ) version: 3.2.5
17/01/02 10:54:08 [INFO] o.a.t.Main$$anon$1 - Initializing internal actor system
17/01/02 10:54:09 [INFO] o.a.t.Main$$anon$1 - Connection Profile: {
  "stdin_port" : 60191,
  "control_port" : 44317,
  "hb_port" : 45502,
  "shell_port" : 57837,
  "iopub_port" : 33283,
  "ip" : "127.0.0.1",
  "transport" : "tcp",
  "signature_scheme" : "hmac-sha256",
  "key" : "225f592c-effe-4af3-b55d-0f2cafc5f5d8"
}
(Scala,org.apache.toree.kernel.interpreter.scala.ScalaInterpreter@3e2943ab)
(PySpark,org.apache.toree.kernel.interpreter.pyspark.PySparkInterpreter@70dd7e15)
(SparkR,org.apache.toree.kernel.interpreter.sparkr.SparkRInterpreter@4a9f80d3)
(SQL,org.apache.toree.kernel.interpreter.sql.SqlInterpreter@35beb15e)
17/01/02 10:54:11 [WARN] o.a.t.Main$$anon$1 - No external magics provided to PluginManager!
17/01/02 10:54:13 [INFO] o.a.t.Main$$anon$1 - 13 internal plugins loaded
17/01/02 10:54:13 [INFO] o.a.t.Main$$anon$1 - 0 external plugins loaded
17/01/02 10:54:13 [INFO] o.a.t.b.l.StandardComponentInitialization$$anon$1 - Setting deployMode to client
17/01/02 10:54:13 [WARN] o.a.t.b.l.StandardComponentInitialization$$anon$1 - Locked to Scala interpreter with SparkIMain until decoupled!
17/01/02 10:54:13 [WARN] o.a.t.b.l.StandardComponentInitialization$$anon$1 - Unable to control initialization of REPL class server!
17/01/02 10:54:14 [WARN] o.a.h.u.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/01/02 10:54:14 [WARN] o.a.s.u.Utils - Service 'sparkDriver' could not bind on port 0. Attempting port 1.
17/01/02 10:54:14 [WARN] o.a.s.u.Utils - Service 'sparkDriver' could not bind on port 0. Attempting port 1.
17/01/02 10:54:14 [WARN] o.a.s.u.Utils - Service 'sparkDriver' could not bind on port 0. Attempting port 1.
17/01/02 10:54:14 [WARN] o.a.s.u.Utils - Service 'sparkDriver' could not bind on port 0. Attempting port 1.
17/01/02 10:54:14 [WARN] o.a.s.u.Utils - Service 'sparkDriver' could not bind on port 0. Attempting port 1.
17/01/02 10:54:14 [WARN] o.a.s.u.Utils - Service 'sparkDriver' could not bind on port 0. Attempting port 1.
17/01/02 10:54:14 [WARN] o.a.s.u.Utils - Service 'sparkDriver' could not bind on port 0. Attempting port 1.
17/01/02 10:54:14 [WARN] o.a.s.u.Utils - Service 'sparkDriver' could not bind on port 0. Attempting port 1.
17/01/02 10:54:14 [WARN] o.a.s.u.Utils - Service 'sparkDriver' could not bind on port 0. Attempting port 1.
17/01/02 10:54:14 [WARN] o.a.s.u.Utils - Service 'sparkDriver' could not bind on port 0. Attempting port 1.
17/01/02 10:54:14 [WARN] o.a.s.u.Utils - Service 'sparkDriver' could not bind on port 0. Attempting port 1.
17/01/02 10:54:14 [WARN] o.a.s.u.Utils - Service 'sparkDriver' could not bind on port 0. Attempting port 1.
17/01/02 10:54:14 [WARN] o.a.s.u.Utils - Service 'sparkDriver' could not bind on port 0. Attempting port 1.
17/01/02 10:54:14 [WARN] o.a.s.u.Utils - Service 'sparkDriver' could not bind on port 0. Attempting port 1.
17/01/02 10:54:14 [WARN] o.a.s.u.Utils - Service 'sparkDriver' could not bind on port 0. Attempting port 1.
17/01/02 10:54:14 [WARN] o.a.s.u.Utils - Service 'sparkDriver' could not bind on port 0. Attempting port 1.
17/01/02 10:54:14 [ERROR] o.a.s.SparkContext - Error initializing SparkContext.
java.net.BindException: Cannot assign requested address: Service 'sparkDriver' failed after 16 retries! Consider explicitly setting the appropriate port for the service 'sparkDriver' (for example spark.ui.port for SparkUI) to an available port or increasing spark.port.maxRetries.
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:485)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1089)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:430)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:415)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:903)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:198)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:348)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at java.lang.Thread.run(Thread.java:745)
I find some solution to change SPARK_LOCAL_IP to localhost, but it won't work, I have to set SPARK_LOCAL_IP to the read ip of host, so it can connect to spark master remotely.

I have set hostNetwork: true, and check the worker side, it seems --host-network-sources default is '*', I wonder how to exactly match the docker --net host? or allow the port bind?

**Comment by calebamiles** [comment]
Hello @zhanghao94, are you reporting an error with the instructions for the [Spark example](https://github.com/kubernetes/kubernetes/tree/master/examples/spark)? Perhaps @zmerlynn, @elsonrodriguez, or someone from @kubernetes/sig-apps-misc could help you with this issue.

**Comment by zhanghao94** [comment]
Thank you for you reply, our spark is outside in kubernetes network, we built docker image with jupyter kernel, and want to manage it in kubernetes. my understanding is when jupyter kernel in kubenetes want to connect to spark outside, it will allocate some ports dynamically, and communicate with spark bi-direction. so the question might be how to allow dynamic port allocation or set kubenetes exactly the same as docker --net host. Thanks a lot!

**Comment by calebamiles** [comment]
Hello @zhanghao94 and thanks for the clarification. Perhaps the information contained in [this old issue](https://github.com/kubernetes/kubernetes/issues/19171) might be of use to you. If you're still in need of help I would contacting someone from SIG Apps [using their contact information](https://github.com/kubernetes/community/blob/master/sig-apps/README.md). Good luck.

**Comment by foxish** [comment]
/cc 
I can look into this later today.

**Comment by zhanghao94** [comment]
Thanks @calebamiles, the old issue said --allow_privileged=true solve the problem, but I checked this option is true by default now. so it might not solve my issue?

**Comment by calebamiles** [comment]
Was your issue solved @zhanghao94? If so would you be so kind as to close this issue? Thanks!

**Comment by calebamiles** [comment]
Closing this issue due to lack of response
