### ISSUE TITLE
aws: Should set CredentialsChainVerboseErrors

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#39374]
For AWS, we need to set CredentialsChainVerboseErrors when initializing the AWS client lib.  cf https://github.com/kubernetes/kops/issues/605

Otherwise we get an annoying error message (`NoCredentialProviders: no valid providers in chain. Deprecated.`), which is usually interpreted as us having done something wrong.

**Comment by grodrigues3** [comment]
@justinsb can you update the status on this?  Doesn't seem like it should be a 1.6 blocker but add back to the milestone if I got it wrong.
