### ISSUE TITLE
GCI GCE slow failure

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#39377]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/1419 has failed.  https://github.com/kubernetes/kubernetes/pull/39092 just merged and *might* be disruptive, but I can't find any logs in the failing job to help me figure definitively determine it.

I'm particularly interested in the API server logs.

**Comment by ixdy** [comment]
This looks like a GCE infrastructure flake.

If you expand the build log:
```
I0103 10:08:05.418] Starting master and configuring firewalls
W0103 10:08:15.688] Created [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-gci-slow/global/firewalls/bootstrap-e2e-default-internal-master].
I0103 10:08:15.779] NAME                                   NETWORK        SRC_RANGES  RULES                                       SRC_TAGS  TARGET_TAGS
I0103 10:08:15.779] bootstrap-e2e-default-internal-master  bootstrap-e2e  10.0.0.0/8  tcp:1-2379,tcp:2382-65535,udp:1-65535,icmp            bootstrap-e2e-master
W0103 10:08:17.801] ERROR: (gcloud.compute.disks.create) Some requests did not succeed:
W0103 10:08:17.801]  - Internal Error
```

**Comment by ixdy** [comment]
(There are no API server logs because we never started it.)

**Comment by deads2k** [comment]
> (There are no API server logs because we never started it.)

Oh, ok.  I didn't know the order of operations.  Glad to know know I didn't break it. :)
