### ISSUE TITLE
Upgrading node pool causes error in GCE

### ISSUE THREAD

**Issue by montanaflynn** [kubernetes/kubernetes#39385]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:43:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

Google container engine

**What happened**:

I upgraded the node pool from the GCE website and there's now a missing node and an error on the cluster webpage.

**What you expected to happen**:

The nodes to be updated.

**How to reproduce it** (as minimally and precisely as possible):

From GCE cluster page try to update the node-pool from version `1.3.7` to `1.4.7`

**Anything else do we need to know**:

The updates seemed to work, now I have 7 nodes running that have at least been restarted and when running `kubectl describe nodes` shows they have been updated to `1.4.7`. There should be eight though.  Also the webpage still shows them as running `1.3.7`.

Here's the error reported on the webpage https://console.cloud.google.com/kubernetes/clusters/details/us-central1-b/cluster-name?project=project-name-123&authuser=0

```
Status details

cloud-kubernetes::UNKNOWN: nodes "gke-backend-default-pool-a671890f-uxby" not found goroutine 135271945 [running]: google3/cloud/kubernetes/common/errors.newStatus(0xc4000003e7, 0xc42b249200, 0x38, 0x1, 0x10) cloud/kubernetes/common/errors.go:627 +0x22f google3/cloud/kubernetes/common/errors.ToStatus(0x2c38760, 0xc42a9cd000, 0xc42fb82bd0) cloud/kubernetes/common/errors.go:681 +0x1ac google3/cloud/kubernetes/common/errors.Combine(0xc42b73f8f0, 0x1, 0x1, 0x0, 0x1) cloud/kubernetes/common/errors.go:852 +0x12b google3/cloud/kubernetes/common/call.InParallel(0x1, 0xc42ab12900, 0xc428ef1620, 0xc4289e3700, 0x8, 0x8, 0x4, 0x8) cloud/kubernetes/common/call.go:130 +0x608 google3/cloud/kubernetes/server/updater/updater.(*Updater).UpdateNPI(0xc42db30040, 0x7f61ee61d460, 0xc42f2df020, 0xc42a94e340, 0xc42d364000, 0xc439006b60, 0xc428ef1620, 0xc4312c27e0, 0x85, 0xc42c4d6580, ...) cloud/kubernetes/server/updater/updater.go:70 +0x693 google3/cloud/kubernetes/server/deploy.(*Deployer).updateNPI(0xc42b691b00, 0x7f61ee61d460, 0xc42f2df020, 0xc428ef1620, 0x7f61e6929940, 0xc439006af0, 0xc42a94e340, 0xc42d364000, 0xc439006b60, 0xc4312c27e0, ...) cloud/kubernetes/server/deploy.go:1844 +0xdc google3/cloud/kubernetes/server/deploy.(*Deployer).UpdateNodes(0xc42b691b00, 0x7f61ee61d460, 0xc42f2df020, 0xc428ef1620, 0x7f61e6929940, 0xc439006af0, 0xc422189ce0, 0xc42a94e340, 0xc42d67d100, 0xc42c4d6580, ...) cloud/kubernetes/server/deploy.go:1781 +0xb5e google3/cloud/kubernetes/server/server.(*ClusterServer).clusterUpgradeNodesInternal(0xc42b68fb90, 0x7f61ee61d460, 0xc43f73eb40, 0xc428ef1620, 0xc42a94e340, 0xc42d67d100, 0xc422846960, 0x2c80e00, 0xc42db360e0, 0x3, ...) cloud/kubernetes/server/server.go:1206 +0x3e5 google3/cloud/kubernetes/server/server.(*ClusterServer).clusterUpgradeNodes(0xc42b68fb90, 0x7f61ee61d460, 0xc43f73eb40, 0xc428ef1620, 0xc42a94e340, 0xc42d67d100, 0xc422846960, 0x2c80e00, 0xc42db360e0, 0x0, ...) cloud/kubernetes/server/server.go:1077 +0x108 google3/cloud/kubernetes/server/server.(*ClusterServer).clusterUpdate(0xc42b68fb90, 0x7f61ee61d460, 0xc43f73eb40, 0xc428ef1620, 0xc400000002, 0xc42a94e340, 0xc42d67d100, 0xc422846960, 0x2c80e00, 0xc42db360e0, ...) cloud/kubernetes/server/server.go:951 +0x3d4 google3/cloud/kubernetes/server/server.(*ClusterServer).updateClusterInternal(0xc42b68fb90, 0x7f61ee61d460, 0xc43f73eb40, 0xc428ef1620, 0x2c80e00, 0xc42db360e0, 0xc42a94e340, 0xc42d67d100, 0xc422846960, 0xc400000002, ...) cloud/kubernetes/server/server.go:1973 +0xca google3/cloud/kubernetes/server/server.(*ClusterServer).UpdateCluster.func1(0xc428ef1560, 0xc42db36220, 0x2c80e00, 0xc42db360e0, 0xc436e8ac00, 0xc, 0xc400000002, 0xc436ec3550, 0xc42b68fb90, 0x7f61ee61d460, ...) cloud/kubernetes/server/server.go:1965 +0x2fd created by google3/cloud/kubernetes/server/server.(*ClusterServer).UpdateCluster cloud/kubernetes/server/server.go:1967 +0xc44
```

**Comment by calebamiles** [comment]
Can someone from @kubernetes/goog-gke please help with triage. Thanks!

**Comment by roberthbailey** [comment]
@maisem @fabioy

**Comment by maisem** [comment]
@montanaflynn - Do you mind running the upgrade again? It should not alter your existing nodes but will try to repair the missing one.

**Comment by montanaflynn** [comment]
@maisem I tried just now but there is no apparent changes made (node age still reported as 1d old using `kubectl get nodes`)

From https://console.cloud.google.com/kubernetes/clusters/details/us-central1-b/cluster-name?project=project-name-123&authuser=0 under node pools I see:

<img width="485" alt="screen shot 2017-01-04 at 11 58 18 am" src="https://cloud.githubusercontent.com/assets/24260/21657092/94e1cd22-d275-11e6-9395-54ca0fc9fc84.png">

When I try to upgrade it presents the versions, I choose `1.4.7`, the page refreshes, theres a loading icon, it then turns to green and the same error is shown at the top of the page under status details.

<img width="493" alt="screen shot 2017-01-04 at 12 00 58 pm" src="https://cloud.githubusercontent.com/assets/24260/21657071/8507d93c-d275-11e6-8c55-3c34ed1fc1da.png">

**Comment by maisem** [comment]
@montanaflynn - After investigating further this does look like an issue on GKE. I've filed a bug to fix it.

In the mean time the course of action to fix your cluster would be to recreate the "gke-backend-default-pool-a671890f-uxby" VM instance.
You can do that by running the following gcloud command
```shelll
gcloud compute instance-groups managed recreate-instances gke-backend-default-pool-a671890f-grp --zone us-central1-b --instances=gke-backend-default-pool-a671890f-uxby
```

Once this completes, please rerun the upgrade and it should proceed to completion.

**Comment by montanaflynn** [comment]
Thanks @maisem that worked!

**Comment by grodrigues3** [comment]
@montanaflynn sounds like this is fixed.  Closing the issue
