### ISSUE TITLE
Kubefed broken on master

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#39388]
Federation system started via kubefed is broken on master

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2720+8623fdf0b106e1", GitCommit:"8623fdf0b106e1c826cffb2abc20d4e115045b8d", GitTreeState:"clean", BuildDate:"2017-01-03T18:53:22Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2693+85bf256709d4c0", GitCommit:"85bf256709d4c0d56aabe40ee5b0ccf9017aeceb", GitTreeState:"clean", BuildDate:"2017-01-03T16:28:57Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): 
- **Kernel** (e.g. `uname -a`):
- **Install tools**: kube-up.sh
- **Others**:

**What happened**:

As part of - https://github.com/kubernetes/kubernetes/pull/38191 change the api-server options were moved out from genericapiserver package. One of the options moved was  - `ServiceClusterIPRange`  but when using `kubefed` to start a federation plane it still starts with following option:

```
 containers:
  - command:
    - /hyperkube
    - federation-apiserver
    - --bind-address=0.0.0.0
    - --etcd-servers=http://localhost:2379
    - --service-cluster-ip-range=10.0.0.0/16
```

Which obviously results in pod never coming up because that option no longer exists there. 

I am working on fixing it. cc @sttts @madhusudancs

**Comment by madhusudancs** [comment]
Fixed in #39405. Also in https://github.com/kubernetes/kubernetes/pull/39132/files#diff-e7243d86cc50e209d78ce51d57dad48dL420.
