### ISSUE TITLE
After apply flannel.yaml ,the container of kube-dns and dnsmasq restart every 5min

### ISSUE THREAD

**Issue by ok-he** [kubernetes/kubernetes#39397]
[root@0102test1 tar]# kubelet --version
Kubernetes v1.5.1

After I did the 
`kubectl apply -f  https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml`

the container of kube-dns and dnsmasq restart every 5min
and the kube-dns's status is crashLoopBackOff

![image](https://cloud.githubusercontent.com/assets/24426986/21628823/73915f56-d25d-11e6-8daa-7cb487d73269.png)

here is the describe

`[root@0102test1 tar]# kubectl describe pod kube-dns-2924299975-q0zj2 --namespace="kube-system"
Name:		kube-dns-2924299975-q0zj2
Namespace:	kube-system
Node:		0102test2/192.168.115.159
Start Time:	Wed, 04 Jan 2017 08:02:36 +0800
Labels:		component=kube-dns
		k8s-app=kube-dns
		kubernetes.io/cluster-service=true
		name=kube-dns
		pod-template-hash=2924299975
		tier=node
Status:		Running
IP:		10.244.1.4
Controllers:	ReplicaSet/kube-dns-2924299975
Containers:
  kube-dns:
    Container ID:	docker://71e2018ef4a23a20943c2cfccf0d7074e7bef8165ba29b176c4550d8af828307
    Image:		gcr.io/google_containers/kubedns-amd64:1.9
    Image ID:		docker-pullable://hekai/kubedns-amd64@sha256:c12a28611a6883a2879b8f8dae6a7b088082d40262a116be51c8ee0b69cf91e0
    Ports:		10053/UDP, 10053/TCP, 10055/TCP
    Args:
      --domain=cluster.local
      --dns-port=10053
      --config-map=kube-dns
      --v=2
    Limits:
      memory:	170Mi
    Requests:
      cpu:		100m
      memory:		70Mi
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	137
      Started:		Wed, 04 Jan 2017 16:45:47 +0800
      Finished:		Wed, 04 Jan 2017 16:47:26 +0800
    Ready:		False
    Restart Count:	127
    Liveness:		http-get http://:8080/healthz-kubedns delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:		http-get http://:8081/readiness delay=3s timeout=5s period=10s #success=1 #failure=3
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-c3wql (ro)
    Environment Variables:
      PROMETHEUS_PORT:	10055
  dnsmasq:
    Container ID:	docker://d4643a1058ce2061d3f3dce1fcce0235f95561cdbb6c0866c26bc56ea098eb18
    Image:		gcr.io/google_containers/kube-dnsmasq-amd64:1.4
    Image ID:		docker-pullable://hekai/kube-dnsmasq-amd64@sha256:e49f231477ba296992515e5824c3015692227abb8f5c6fa08557d4d83abe8058
    Ports:		53/UDP, 53/TCP
    Args:
      --cache-size=1000
      --no-resolv
      --server=127.0.0.1#10053
      --log-facility=-
    Requests:
      cpu:		150m
      memory:		10Mi
    State:		Running
      Started:		Wed, 04 Jan 2017 16:50:21 +0800
    Last State:		Terminated
      Reason:		Error
      Exit Code:	137
      Started:		Wed, 04 Jan 2017 16:43:30 +0800
      Finished:		Wed, 04 Jan 2017 16:45:06 +0800
    Ready:		True
    Restart Count:	128
    Liveness:		http-get http://:8080/healthz-dnsmasq delay=60s timeout=5s period=10s #success=1 #failure=5
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-c3wql (ro)
    Environment Variables:	<none>
  dnsmasq-metrics:
    Container ID:	docker://486d79d22ad0fc14e0e207c80d56332d7fc5d5c1e1efcd76f45929163aa59155
    Image:		gcr.io/google_containers/dnsmasq-metrics-amd64:1.0
    Image ID:		docker://sha256:1be481164f9d9aa9b0970d065b1715b2211d10cd247219f858deb2e142ba9fa7
    Port:		10054/TCP
    Args:
      --v=2
      --logtostderr
    Requests:
      memory:		10Mi
    State:		Running
      Started:		Wed, 04 Jan 2017 08:05:11 +0800
    Ready:		True
    Restart Count:	0
    Liveness:		http-get http://:10054/metrics delay=60s timeout=5s period=10s #success=1 #failure=5
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-c3wql (ro)
    Environment Variables:	<none>
  healthz:
    Container ID:	docker://92f5d24a19418d4f8da7b07ba4478a589857598a3fb4d05a26b5229a6622e440
    Image:		gcr.io/google_containers/exechealthz-amd64:1.2
    Image ID:		docker://sha256:05a4d40f9f30f62d866ce425a0f388f4c063d732d3da8609c95b8639c8a1b96d
    Port:		8080/TCP
    Args:
      --cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
      --url=/healthz-dnsmasq
      --cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1:10053 >/dev/null
      --url=/healthz-kubedns
      --port=8080
      --quiet
    Limits:
      memory:	50Mi
    Requests:
      cpu:		10m
      memory:		50Mi
    State:		Running
      Started:		Wed, 04 Jan 2017 08:05:12 +0800
    Ready:		True
    Restart Count:	0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-c3wql (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  default-token-c3wql:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-c3wql
QoS Class:	Burstable
Tolerations:	dedicated=master:NoSchedule
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath			Type		Reason		Message
  ---------	--------	-----	----			-------------			--------	------		-------
  8h		5m		128	{kubelet 0102test2}	spec.containers{kube-dns}	Normal		Pulled		Container image "gcr.io/google_containers/kubedns-amd64:1.9" already present on machine
  8h		4m		602	{kubelet 0102test2}					Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "dnsmasq" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=dnsmasq pod=kube-dns-2924299975-q0zj2_kube-system(a9e51ec3-d20f-11e6-9495-000c29beacd6)"

  8h	4m	247	{kubelet 0102test2}	spec.containers{kube-dns}	Normal	Killing		(events with common reason combined)
  8h	1m	101	{kubelet 0102test2}					Warning	FailedSync	Error syncing pod, skipping: [failed to "StartContainer" for "dnsmasq" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=dnsmasq pod=kube-dns-2924299975-q0zj2_kube-system(a9e51ec3-d20f-11e6-9495-000c29beacd6)"
, failed to "StartContainer" for "kube-dns" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kube-dns pod=kube-dns-2924299975-q0zj2_kube-system(a9e51ec3-d20f-11e6-9495-000c29beacd6)"
]
  8h	1m	765	{kubelet 0102test2}		Warning	FailedSync	Error syncing pod, skipping: [failed to "StartContainer" for "kube-dns" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kube-dns pod=kube-dns-2924299975-q0zj2_kube-system(a9e51ec3-d20f-11e6-9495-000c29beacd6)"
, failed to "StartContainer" for "dnsmasq" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=dnsmasq pod=kube-dns-2924299975-q0zj2_kube-system(a9e51ec3-d20f-11e6-9495-000c29beacd6)"
]
  8h	1m	250	{kubelet 0102test2}	spec.containers{dnsmasq}	Normal	Started		(events with common reason combined)
  8h	1m	129	{kubelet 0102test2}	spec.containers{dnsmasq}	Normal	Pulled		Container image "gcr.io/google_containers/kube-dnsmasq-amd64:1.4" already present on machine
  8h	1m	250	{kubelet 0102test2}	spec.containers{dnsmasq}	Normal	Created		(events with common reason combined)
  8h	19s	3056	{kubelet 0102test2}	spec.containers{kube-dns}	Warning	BackOff		Back-off restarting failed docker container
  8h	19s	705	{kubelet 0102test2}					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kube-dns" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kube-dns pod=kube-dns-2924299975-q0zj2_kube-system(a9e51ec3-d20f-11e6-9495-000c29beacd6)"

  8h	8s	265	{kubelet 0102test2}	spec.containers{dnsmasq}	Warning	Unhealthy	Liveness probe failed: HTTP probe failed with statuscode: 503
`

In the log shows kube-dns and dnsmasq   Exit Code:	137
and
spec.containers{dnsmasq}	Warning	Unhealthy	Liveness probe failed: HTTP probe failed with statuscode: 503

and the picture below may be help
![qq 20170104001855](https://cloud.githubusercontent.com/assets/24426986/21628719/7c2e8ab8-d25c-11e6-98d3-71c2ae65a7d1.png)

sorry for my poor english and thanks for your answer.

ps: my master init using the method `kubeadm init --pod-network-cidr=10.244.0.0/16`
0103test1 is the master
0103test2 is the worker

**Comment by zhuqinghua** [comment]
#26245

**Comment by bowei** [comment]
It looks like the IP range used in your flannel configuration intersects with the IP range for the DNS service. I'm guessing that this causes issues with kube-dns. Can you change the subnet used in flannel (10.244.x.x) to something else?

**Comment by ok-he** [comment]
my image is wrong, I'm so fool

my image's id is different from the right id, so I pull the image again and the problem solved.

thanks
