### ISSUE TITLE
GCE cloud: add a kube-specific header to GCE API calls

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#39391]
In tracking an internal issue, it became clear we don't really know which calls are being made on behalf of kubernetes.  We should add a header, even if it is "this was kubernetes".  Better still to have a cluster UUID or something.

**Comment by Sajmani** [comment]
It would also be useful to distinguish between calls made from GKE-managed and user-managed k8s instances.

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
/area platform/gke
since we lack a sig-gcp at the moment
