### ISSUE TITLE
go vet check failed

### ISSUE THREAD

**Issue by YuPengZTE** [kubernetes/kubernetes#39412]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

go vet check
src\github.com\kubernetes\kubernetes\test\integration\evictions\eviction
s_test.go:214: unreachable code
src\github.com\kubernetes\kubernetes\test\integration\evictions\eviction
s_test.go:188: result of fmt.Errorf call not used

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by calebamiles** [comment]
Thanks for submitting this issue @YuPengZTE. I've filed a PR to delete the test. After some brief review I believe the test itself is incorrectly implemented.
