### ISSUE TITLE
How to redirect log output to log_dir when using systemctl to start kube-apiserver?

### ISSUE THREAD

**Issue by yejw5** [kubernetes/kubernetes#39414]
When I start the kube-apiserver in command line by `/usr/bin/kube-apiserver --logtostderr=false --log_dir=/home/kube_apiserver/ --v=4 --etcd-servers=http://127.0.0.1:2379 --insecure-bind-address=0.0.0.0 --port=8080 --allow-privileged=true --service-cluster-ip-range=10.254.0.0/16 --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ResourceQuota`, logs data output to `/home/kube_apiserver/` successfully. And the log files present detailed journal.

But when I add configs to `/etc/kubernetes/apiserver` as following:
```
KUBE_API_ARGS="--log_dir=/home/kube_apiserver/"
KUBE_LOG_LEVEL="--v=4"
KUBE_LOGTOSTDERR="--logtostderr=false"
```
And start service by `systemctl start kube-apiserver`. There is no log data in directory `/home/kube_apiserver/`. And it seems that the service runs with `--logtostderr=true --v=0`. The concise logs output to terminal.

Is this caused by some mistakes in configs of kube-apiserver? Or the wrong use of systemctl?

**Comment by cackharot** [comment]
Have a look at `/etc/systemd/system/kube-apiserver.service` file to find out where it loads the ENV variables from.

**Comment by yejw5** [comment]
In file `/etc/systemd/system/kube-apiserver.service`, the Env is assigned as:
```
[Service]
EnvironmentFile=-/etc/kubernetes/config
EnvironmentFile=-/etc/kubernetes/apiserver
```
And in `/etc/kubernetes/config`, the using variables are set to default values:
```
KUBE_LOGTOSTDERR="--logtostderr=true"
KUBE_LOG_LEVEL="--v=0"
```
The new config parameters added by hand will cover the default values:
```
KUBE_API_ARGS="--log_dir=/home/kube_apiserver/"
KUBE_LOG_LEVEL="--v=4"
KUBE_LOGTOSTDERR="--logtostderr=false"
```
After service `kube-apiserver` started, run command `systemctl status kube-apiserver` and get following message:
```
kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; enabled)
   Active: active (running) since Mon 2017-01-09 14:42:13 CST; 1min 34s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 23944 (kube-apiserver)
   CGroup: /system.slice/kube-apiserver.service
           └─23944 /usr/bin/kube-apiserver --logtostderr=false --v=4 --etcd-servers=http://127.0.0.1:2379 --insecure-bind-address=0.0.0.0 --port=8080 --allow-privileged=true --service-cluster-ip-range=10.254.0.0/16 --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ResourceQuota --log_dir=/var/log/kubernetes/apiserver
```

**Comment by ZhengRongTan** [comment]
same problem . how to fixed?

**Comment by MIBc** [comment]
The yejw5 's reply explain the problem @ZhengRongTan
