### ISSUE TITLE
Add a short and a json output option for kubectl version

### ISSUE THREAD

**Issue by n-rook** [kubernetes/kubernetes#39427]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
"kubectl version", "kubectl version" json

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

**Kubernetes version** (use `kubectl version`):
$ kubectl version --client
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
GKE
- **OS** (e.g. from /etc/os-release):
MacOS 10.12.2

I find it difficult to parse the output of `kubectl version` programmatically. I have to use a YAML parser to do it. I'd prefer to use JSON, or to be given just the string `v1.4.6` and asked to parse it with a regex.

This is obviously a relatively low-priority request.

**Comment by alejandroEsc** [comment]
I wouldnt mind helping out on this, if there are no objections?

**Comment by ReneSaenz** [comment]
@alejandroEsc are you working on this?  If not, I would like to work on it.

**Comment by alejandroEsc** [comment]
@ReneSaenz I plan to, but if i'll keep you posted if i get too delayed.

**Comment by ReneSaenz** [comment]
@alejandroEsc  How can I direct message you?

**Comment by alejandroEsc** [comment]
@ReneSaenz didnt see this till now, felt bad i had not kept up on this so i decided to just push through it. If my email is not available in my profile, please let me know, otherwise jaescobar.cell AT gmail would be the best way to contact me.

**Comment by n-rook** [comment]
Thanks!

**Comment by alejandroEsc** [comment]
@n-rook here is a few samples:

```
./cluster/kubectl.sh version --output json | toJson
{
    "Client Version": {
        "buildDate": "2017-01-13T19:38:11Z",
        "compiler": "gc",
        "gitCommit": "e52615ddd2f80ebf62c5dce82f2b720b8b786223",
        "gitTreeState": "dirty",
        "gitVersion": "v1.6.0-alpha.0.3197+e52615ddd2f80e-dirty",
        "goVersion": "go1.7.4",
        "major": "1",
        "minor": "6+",
        "platform": "darwin/amd64"
    },
    "Server Version": {
        "buildDate": "2017-01-13T19:38:11Z",
        "compiler": "gc",
        "gitCommit": "e52615ddd2f80ebf62c5dce82f2b720b8b786223",
        "gitTreeState": "dirty",
        "gitVersion": "v1.6.0-alpha.0.3197+e52615ddd2f80e-dirty",
        "goVersion": "go1.7.4",
        "major": "1",
        "minor": "6+",
        "platform": "darwin/amd64"
    }
}
```
```
./cluster/kubectl.sh version --output yaml
{v1.6.0-alpha.0.3197+e52615ddd2f80e-dirty v1.6.0-alpha.0.3197+e52615ddd2f80e-dirty}
Client Version:
  buildDate: 2017-01-13T19:38:11Z
  compiler: gc
  gitCommit: e52615ddd2f80ebf62c5dce82f2b720b8b786223
  gitTreeState: dirty
  gitVersion: v1.6.0-alpha.0.3197+e52615ddd2f80e-dirty
  goVersion: go1.7.4
  major: "1"
  minor: 6+
  platform: darwin/amd64
Server Version:
  buildDate: 2017-01-13T19:38:11Z
  compiler: gc
  gitCommit: e52615ddd2f80ebf62c5dce82f2b720b8b786223
  gitTreeState: dirty
  gitVersion: v1.6.0-alpha.0.3197+e52615ddd2f80e-dirty
  goVersion: go1.7.4
  major: "1"
  minor: 6+
  platform: darwin/amd64
```
