### ISSUE TITLE
GKE network load balancers don't get deleted on cluster deletion

### ISSUE THREAD

**Issue by JorritSalverda** [kubernetes/kubernetes#39421]
**FEATURE REQUEST**

When deleting a GKE cluster the GCE network load balancers created for any of the services with type LoadBalancer to get deleted as well.

**Kubernetes version**

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.6.3
", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:43:42Z", GoVersion:"go1.6.3
", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **GKE 1.4.7**:
- **gci image**

**What happened**:
Deleting a GKE cluster with services of type LoadBalancer leaves the network load balancers in place leading to unnecessary costs.

**What you expected to happen**:
That all network load balancers pointing to the cluster get removed as well.

**Comment by cmluciano** [comment]
@kubernetes/goog-gke

**Comment by roberthbailey** [comment]
/remove-lifecycle stale

This is still an issue, so keeping it open.
