### ISSUE TITLE
kops still having a lot a trouble with flakes

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#39436]
kops is currently blocking the merge queue, but there's not a clear pattern of flakes.  Looks like the job has been consistently unreliable for as far back as the test grid history goes: https://k8s-testgrid.appspot.com/google-aws#kops-aws&include-filter-by-regex=%5EOverall%24%7CTest .  Did this recently get made blocking again?

@kubernetes/test-infra-maintainers @kubernetes/rh-cluster-infra @derekwaynecarr

**Comment by eparis** [comment]
last night. by @zmerlynn https://github.com/kubernetes/contrib/pull/2245

**Comment by zmerlynn** [comment]
The noise level has actually increased as 1.6 has gone along, I'm looking into it. (That's hard to see in testgrid because of very consistent full-breaks.)

Please don't remove it from the SQ yet.

**Comment by mikedanese** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/34488/pull-kubernetes-e2e-kops-aws/6900/

**Comment by zmerlynn** [comment]
That looks a lot like https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/39689/pull-kubernetes-e2e-kops-aws/6890/, which looks like AWS is struggling? (@justinsb)

**Comment by deads2k** [comment]
It looks a *lot* cleaner.  I'm closing this now.
