### ISSUE TITLE
Node audit logging

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#39441]
We should have a better story about audit logging on nodes. This is a fairly broad topic that could include:

- Host access (SSH, privileged pods / host volumes / etc, credential changes)
- Kubelet API access
- Pod access (exec / attach / portforward)
- What is running on the node (both in & out of pods)

I think we should treat application (pod) audit logging as a separate topic, with the possible exception of kernel audit logs (e.g. AppArmor violations).

We should have a pluggable way to push or extract the audit logs to a remote location. I'm not sure whether this needs to be a separate system from our current logging pipeline(s) (e.g. fluentd).

API (non-kubelet) audit logging is a separate issue tracked in https://github.com/kubernetes/features/issues/22

@kubernetes/sig-node-misc @kubernetes/sig-auth-misc

**Comment by feiskyer** [comment]
> Google has built something similar for internal use on GKE. I'm certainly open to re-using or open-sourcing some/most/all of that.

Cool. Are there any more details on this?

**Comment by timstclair** [comment]
cc @piosz

**Comment by ericchiang** [comment]
Was wondering if this plays into https://github.com/kubernetes/community/pull/145, which seems to be mostly focused on API server audit logging. Perhaps the kubelet would reuse the plugins mentioned in that proposal?

**Comment by timstclair** [comment]
I think it would make sense for the Kubelet to reuse some of the types (audit event), maybe the filter formats, and the output plugin. A lot of the rest of the proposal is pretty specific to the apiserver architecture.

BTW - I'm only going to be working on the API side for 1.7, so I'm removing this from the milestone unless someone else wants to pick it up.

**Comment by joaquinrinaudo-olx** [comment]
+1 on audit logs. Otherwise a lot of people need to build AMI's (specially for PCI) to harden/setup the nodes.
