### ISSUE TITLE
kubefed init breaks for dev hyperkube image

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#39453]
I ran `kubefed init` after pushing my dev hyperkube image and federation control plane failed to come up.
On closer look, I see the image field as: `gcr.io/google_containers/hyperkube-amd64:v1.6.0-alpha.0.2798+8b2c620b33b9a1-dirty`. It picked the right image version but not the right repository.

cc @madhusudancs @kubernetes/sig-federation-misc

**Comment by madhusudancs** [comment]
@nikhiljindal Did you pass the `--image` flag?

**Comment by nikhiljindal** [comment]
nope. Just simple `kubefed init federation --dns-zone-name="nikhiljindal.com"

**Comment by madhusudancs** [comment]
Please use the flag.

**Comment by nikhiljindal** [comment]
Sorry maybe I didnt explain myself well.

There are 3 possible things that can happen by running `kubefed init` (without the --image flag):
* It always uses the latest release version of hyperkube to start federation control plane
* It uses the dev images from my project if present, else the release images.
* It breaks

I am fine with any of the first 2 (prefer the second), but what is happening right now is the 3rd. It tries to use the images with my dev version from `gcr.io/google_containers` and hence breaks (federation control plane never comes up).

**Comment by madhusudancs** [comment]
@nikhiljindal we have discussed this in the code reviews and elsewhere. `kubefed` trades developer experience for user experience. And so it optimizes for the user experience. `kubefed` defaults to official released image of the version matching the `kubefed` version.

It is none of the three things you have listed here but it is better than all the three.

> It always uses the latest release version of hyperkube to start federation control plane

How do you reliably determine the latest version? Do we have an API for it with the stability promise? What if `kubefed v1.5.1` uses a technique to obtain the latest version that breaks in the future releases. We have no guarantees about the release tooling. They can break.

> It uses the dev images from my project if present, else the release images.

How would `kubefed` know what the project is? Also, what about developers not using GCP? Also, to reemphasize, `kubefed` is about optimizing user experience. Feel free to write a wrapper script to optimize an experience that works for you by setting the image field as you see fit. This is coming to `develop.sh` near you soon.

> It breaks

> I am fine with any of the first 2 (prefer the second), but what is happening right now is the 3rd. It tries to use the images with my dev version from gcr.io/google_containers and hence breaks (federation control plane never comes up).

This is expected. If you are using an unreleased version, which is not the default user's use case, use the `--image` field.

**Comment by madhusudancs** [comment]
@nikhiljindal can we close this?

**Comment by nikhiljindal** [comment]
Yes thanks for the detailed reply!
The point that kubefed uses the images with version of kubefed was not clear to me by reading the kubefed docs. Thanks for explaining it to me.
