### ISSUE TITLE
is there a remote api for delete deployment

### ISSUE THREAD

**Issue by s332401890** [kubernetes/kubernetes#39456]
is there a remote api for delete deployment

i find some info  on http://stackoverflow.com/questions/39416251/kubernetes-rest-api-create-deployment

and  i have try  
[root@centos-master titanbi]# curl -X DELETE http://xxxx:8080/apis/extensions/v1beta1/namespaces/titan/deployments/titanbi
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Success",
  "code": 200
}

but the deployment is not deleted by the api

**Comment by foxish** [comment]
Please post support questions on Stackoverflow.
You can use the same approach as http://stackoverflow.com/a/40919786/759019 to find the associated REST API calls.

**Comment by s332401890** [comment]
ths
