### ISSUE TITLE
k8s with 1.4.0(beta1) or 1.4.5 or 1.5.1 could not support the dynamic volume provisioning

### ISSUE THREAD

**Issue by vklonghml** [kubernetes/kubernetes#39467]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
 FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

and i have also tested the version 1.4.0(beta) and 1.5.1

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:
os:ubuntu14.04

**What happened**:
i create a default storageclass, and create a pvc, but the pvc is in pending status, the storageclass will not create a pv.
**What you expected to happen**:
the pvc created previous could be bounded to a pv which created by the default storageclass

**How to reproduce it** (as minimally and precisely as possible):
1)create a default storageclass, yaml as follows:
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:            
                                                              name: slow
    annotations:
        storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/glusterfs
parameters:
    endpoint: "glusterfs-cluster"
    resturl: "http://162.3.140.205:24007"

2)then, create a pvc, yaml as below:
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: myclaim-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

3)kubectl get pv,pvc -o wide
NAME            STATUS    VOLUME    CAPACITY   ACCESSMODES   AGE
pvc/myclaim-1   Pending                                      21m

**Anything else do we need to know**:

does anybody knows this problem, thank you in advance.

**Comment by gnufied** [comment]
Can you post output of `kubectl describe pvc myclaim-1`?  It just may be your gluster/heketi configuration.

**Comment by vklonghml** [comment]
@gnufied thks for your reply, here are the output:
Name:		myclaim-1
Namespace:	default
Status:		Pending
Volume:		
Labels:		<none>
Capacity:	
Access Modes:

**Comment by vklonghml** [comment]
@gnufied i don't think is the gluster/heketi configuration problem, even the gluster has a  problem, the default storageclass will create a pv, and create a volume, but execute the command "kubectl get event -w", there is no errors about it.
