### ISSUE TITLE
kubefed should allow adding a label to cluster API resource

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#39482]
Came up while discussing https://github.com/kubernetes/kubernetes/issues/29887 with @emaildanwilson .

We need a way to add labels to a cluster API resource while joining it in federation.
Something like:
`kubefed join mycluster1 --labels="region=us-central"`

cc @madhusudancs @kubernetes/sig-federation-misc

**Comment by nikhiljindal** [comment]
Actually we should think hard about this. If we go this path, there are so many more flags we will have to support (essentially one for every field in the Cluster API resource). We can instead say that admins should use kubectl to modify the default cluster resource.
```
$ kubefed join mycluster1
$ kubectl label clusters mycluster1 "region=us-central"
```

**Comment by henriquetruta** [comment]
Is this still valid? Any work on it?

**Comment by quinton-hoole** [comment]
@henriquetruta No work on it that I am aware of.  But yes, it is still valid.  We will need to fix it soon.

**Comment by quinton-hoole** [comment]
Required for federation GA.

**Comment by arthur0** [comment]
I would like work on this.

**Comment by perotinus** [comment]
I agree with @nikhiljindal's second comment: why does this need to be in kubefed join? It's easy enough to use kubectl after the fact to add the labels. If we want to support something like this in kubefed join, it seems like it would be more expedient to allow it to take a template yaml for a cluster.

**Comment by emaildanwilson** [comment]
Yes, I also do not think this is required. The docs I added [here](https://kubernetes.io/docs/tasks/administer-federation/cluster/) show how to label clusters after the fact. I could see this as a nice to have for improving the admin experience. I also think this will naturally be a better experience once we get to using the cluster registry API.

**Comment by arthur0** [comment]
There is any work to do? I think the issue should be closed.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#90.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
