### ISSUE TITLE
GCE Cloud: Service (LoadBalancer) networking breaks when pod is restarted

### ISSUE THREAD

**Issue by crockpotveggies** [kubernetes/kubernetes#39489]
**Kubernetes version** (use `kubectl version`):
```
Server Version: version.Info{
  Major:"1", Minor:"4", 
  GitVersion:"v1.4.7", 
  GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", 
  GitTreeState:"clean", 
  BuildDate:"2016-12-10T04:43:42Z", 
  GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"
}
```

**Environment**:
- **Cloud provider or hardware configuration**: 
Google Cloud
- **OS** (e.g. from /etc/os-release): 
```
BUILD_ID=8820.0.0
NAME="Container-VM Image"
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=55
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Google Container-VM Image"
VERSION=55
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=gci
```
- **Kernel** (e.g. `uname -a`):
```
Linux gke-bernie-cluster-default-pool-b7500cdf-3kr1 4.4.14+ #1 SMP Tue Sep 20 10:32:07 PDT 2016 x86_64 Intel(R) Xeo
n(R) CPU @ 2.50GHz GenuineIntel GNU/Linux
```
- **Install tools**:
none
- **Others**:
none

**What happened**:
We have a replication controller that is responsible for our external REST API. The pod is exposed via a service. When k8s restarts the container, the service fails to redirect traffic to the restarted container. If all pods for an rc fail, the API is no longer externally accessible.

**What you expected to happen**:
The service should automatically redirect traffic to a restarted pod and the process should be seamless.

**How to reproduce it** (as minimally and precisely as possible):
Create a replication controller with one pod that serves as an external REST API. Expose all pods via a service. Force kubernetes to restart the pod. The API will no longer be exposed, even though logs show the pod functioning normally, and networking is broken.

**Anything else do we need to know**:
Here's the configuration for the service that links to the replication controller:

![screen shot 2017-01-05 at 1 21 05 pm](https://cloud.githubusercontent.com/assets/1445295/21697989/da10abc8-d349-11e6-9878-36d5d497963a.png)
![screen shot 2017-01-05 at 1 20 55 pm](https://cloud.githubusercontent.com/assets/1445295/21697992/dd402756-d349-11e6-8ac4-03089e789441.png)

**Comment by MrHohn** [comment]
It seems like kube-proxy didn't work as expected and it stopped to update the new endpoints appeared(the restarted pods). Is there anything worth to notice in kube-proxy's logs?

**Comment by crockpotveggies** [comment]
Looking at kube-proxy.log it appears that k8s simply removes the restarted container endpoint, but never comes back to reinstate it:

Machine 1:
```
I0105 08:00:53.992973       7 proxier.go:588] Removing endpoints for "default/http-api:tcp-80-8000-z2dip"
I0105 14:01:18.811670       7 proxier.go:588] Removing endpoints for "default/http-api:tcp-80-8000-z2dip"
I0105 14:01:19.621385       7 proxier.go:706] Deleting connection tracking state for service IP 10.7.240.10, endpoint IP 10.4.1.40
I0105 14:01:19.708613       7 proxier.go:588] Removing endpoints for "kube-system/default-http-backend:http"
I0105 20:58:21.582695       7 proxier.go:588] Removing endpoints for "default/http-api:tcp-80-8000-z2dip"
```

Machine 2:
```
I0105 08:00:53.813416       7 proxier.go:588] Removing endpoints for "default/http-api:tcp-80-8000-z2dip"
I0105 14:01:18.812301       7 proxier.go:588] Removing endpoints for "default/http-api:tcp-80-8000-z2dip"
I0105 14:01:19.543288       7 proxier.go:706] Deleting connection tracking state for service IP 10.7.240.10, endpoint IP 10.4.1.40
I0105 14:01:19.575148       7 proxier.go:588] Removing endpoints for "kube-system/default-http-backend:http"
I0105 20:58:21.470953       7 proxier.go:588] Removing endpoints for "default/http-api:tcp-80-8000-z2dip"
```

Machine 3:
```
I0105 08:00:53.812812       7 proxier.go:588] Removing endpoints for "default/http-api:tcp-80-8000-z2dip"
I0105 14:01:18.811337       7 proxier.go:588] Removing endpoints for "default/http-api:tcp-80-8000-z2dip"
I0105 14:01:19.510270       7 proxier.go:706] Deleting connection tracking state for service IP 10.7.240.10, endpoint IP 10.4.1.40
I0105 14:01:19.530303       7 proxier.go:588] Removing endpoints for "kube-system/default-http-backend:http"
I0105 20:58:21.470291       7 proxier.go:588] Removing endpoints for "default/http-api:tcp-80-8000-z2dip"
```

All other compute instances look nearly exactly the same.

**Comment by MrHohn** [comment]
Could you try `kubectl get endpoints http-api` and confirm the new pods are in?

**Comment by crockpotveggies** [comment]
Looks like k8s has been aware of the pods for 90 days, perhaps the issue is originating elsewhere?

```
$ kubectl get endpoints http-api

NAME       ENDPOINTS         AGE
http-api   10.4.5.151:8000   90d
```

**Comment by MrHohn** [comment]
And have you tried accessing the service through the internal service IP? To confirm it isn't a problem with the external LoadBalancer?

**Comment by crockpotveggies** [comment]
Let me quickly replicate this pod/r.c./service and force a restart and see if I can indeed force a restart. Will get back to you shortly, and then I'll use your suggestions as a checklist.

**Comment by crockpotveggies** [comment]
Quick update, before I duplicated the production environment I narrowed my attention on the Google Cloud load balancer. I noticed that a health check had not been instated by Kubernetes when it was created. I created one with a frequency of 2 seconds. The load balancer is checking 5 different machines of 24 CPUs each, but typically only one or two has our HTTP API pods.

My *suspicion* is because the default config for the load balancer is to not perform a health check, when a pod restarts the load balancer will automatically blacklist the entire machine. It would explain why in some circumstances we'd see API failure when multiple pods were still up and running. It would also explain why multiple pod failure could go undetected from an external monitor, which is what we've seen in our case.

I'd typically get five alarms a day in the previous configuration. In the last 24 hours since adding the health check, I haven't seen a single alarm.

This could indicate a design issue. I'm debugging and watching this closely.

**Comment by MrHohn** [comment]
I need to think more about it. But a quick note is that the health check would not be needed for a general LoadBalancer type Service, because we put all node IPs as the backends instead of the real backend Pod IPs. When a request is forwarded to either node, it will be re-forwarded to one of the backend Pods. Hence it does not matter whether the Pods run on this node or not.

There is one case the healthcheck will be created automatically for the Google Cloud load balancer(http://kubernetes.io/docs/user-guide/load-balancer/#annotation-to-modify-the-loadbalancer-behavior-for-preservation-of-source-ip), but it seems irrelevant to this issue.

**Comment by crockpotveggies** [comment]
Gotcha, then yes it might trace back to a problem with kubectl-proxy. That would mean that all I discovered was some sort of band-aid that doesn't address the underlying problem.

**Comment by MrHohn** [comment]
One theory for why the health check reduced the alarm rate is that:
- One or more `kube-proxy` on nodes stopped working properly.
- Requests went to these nodes would not be forwarded correctly.
- The health check detected these bad nodes so not more requests were sent to them.

Is there any node stays unhealthy in the health check status?

**Comment by crockpotveggies** [comment]
Looks like there is indeed a problem, see image:

![screen shot 2017-01-06 at 11 43 52 am](https://cloud.githubusercontent.com/assets/1445295/21730635/73c91046-d405-11e6-8e24-7e8bb8093e1c.png)

**Comment by crockpotveggies** [comment]
It's also worth noting that CPU usage on this machine is abysmal, indicating nothing is actually running on this machine but it's being managed by k8s somehow, I can confirm it shows up in the kube dashboard as a node.

![screen shot 2017-01-06 at 11 56 17 am](https://cloud.githubusercontent.com/assets/1445295/21731020/2c0ec2f8-d407-11e6-91ef-fe54c5ff1625.png)

**Comment by crockpotveggies** [comment]
Aha! Found a problem... only 2 containers exist and one of them is a pending kube-proxy pod that has been stagnant for 4 hours:
![screen shot 2017-01-06 at 12 02 30 pm](https://cloud.githubusercontent.com/assets/1445295/21731207/1afac380-d408-11e6-9489-3fb6233781a4.png)

**Comment by MrHohn** [comment]
Glad we found the problem. Do you notice any log(from `kube-proxy` or `kubelet`) or event showing why the kube-proxy stayed in pending?

A quick fix for this would be to kill this kube-proxy pod and let the system recreate it automatically. Or if there is something wrong with this node itself, restart this node may help. But you may want to keep this node for investigation.

**Comment by crockpotveggies** [comment]
On this specific node both kube-proxy log and kubelet logs are empty. Not sure why that is. I'll take a snapshot and then I'll kill it and see if anything changes.

**Comment by crockpotveggies** [comment]
After manually deleting that pod the problem comes back:
```
container "kube-proxy" in pod "kube-proxy-gke-bernie-cluster-default-pool-b7500cdf-mbb5" is waiting to start: trying and failing to pull image
```

**Comment by Random-Liu** [comment]
@crockpotveggies Could you login into the bad node, and run `docker images` to check whether there is kube-proxy image listed?

IIUC, we don't really push the kube-proxy image to gcr and pull it. We create a tarball for the kube-proxy docker image, put the tarball on the node, and use `docker load` to load the image. So kube-proxy image should have already been loaded on each node.

In your case, kubelet is trying to pull kube-proxy image, it may because:
1) There is something wrong with the bootstrap phase, and the kube-proxy image is not properly downloaded.
2) Some one removed the image, may be kubelet may be some one else.

**Comment by crockpotveggies** [comment]
Attempted to run the command and got:
```
docker images
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

I attempted to restart the daemon with known commands, but `docker-machine` and `service docker start` don't seem to work on a GCE node.

**Comment by MrHohn** [comment]
Just to confirm, did you run commands with 'root'(sudo)?

**Comment by crockpotveggies** [comment]
Aha! No I didn't 🌮 
Here's the output
```
REPOSITORY                             TAG                                IMAGE ID            CREATED             SIZE
gcr.io/google_containers/kube-proxy    dce5681a0d470b2efa3e0542b1164c9b   1f6aa6a8c3dc        3 months ago        202.8 MB
gcr.io/google_containers/fluentd-gcp   1.21                               0ef09b1bcfd7        5 months ago        498.4 MB
gcr.io/google_containers/pause-amd64   3.0                                99e59f495ffa        8 months ago        746.9 kB
```

**Comment by crockpotveggies** [comment]
Also worth noting, I cannot delete the node at all from Google Cloud. Even though it's removed from k8s, I cannot delete it from the console, nor does changing node size in GCE remove it.

**Comment by MrHohn** [comment]
Surprise to see the kube-proxy image was already there, not sure how would the image pulling failed. @Random-Liu might have more ideas.

`Even though it's removed from k8s` how did you remove it from k8s? I was thinking about [`kubectl cordon`](http://kubernetes.io/docs/user-guide/kubectl/kubectl_cordon/) but apparently this marks node as unschedulable but not removes them.

**Comment by crockpotveggies** [comment]
I attempted to re-scale but the image didn't remove itself, so I used the Google Container console to execute a manual deletion. Interestingly, it failed but gave no error. For a couple days I could log in and see a failure message in the terminal telling me k8s was out of sync and the node was improperly provisioned. The notice has since disappeared.

**Comment by Random-Liu** [comment]
Then another thing we can check is `cat /etc/kubernetes/manifests/kube-proxy.manifest`.

Check whether the manifest is using the same kube-proxy version with the one located on the node.

**Comment by crockpotveggies** [comment]
Here's the output, all I'm seeing is an image hash, where can I use it to compare?

```
apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
  labels:
    tier: node
    component: kube-proxy
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: gcr.io/google_containers/kube-proxy:dce5681a0d470b2efa3e0542b1164c9b
    resources:
      requests:
        cpu: 100m
    command:
    - /bin/sh
    - -c
    - kube-proxy --master=https://104.154.109.80 --kubeconfig=/var/lib/kube-proxy/kubeconfig --cluster-cidr=10.4.0.0/14 --resource-container="" --v=2 1>>/var/log/kube-proxy.log 2>&1
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
    - mountPath: /var/log
      name: varlog
      readOnly: false
    - mountPath: /var/lib/kube-proxy/kubeconfig
      name: kubeconfig
      readOnly: false
  volumes:
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
  - hostPath:
      path: /var/lib/kube-proxy/kubeconfig
    name: kubeconfig
  - hostPath:
      path: /var/log
    name: varlog
```

**Comment by Random-Liu** [comment]
Hm, alright. It is the same image. Then it's really weird, why kubelet report image pulling error. It should not pull image at all because the image is already on the node.

**Comment by crockpotveggies** [comment]
Hmmm.... looks like k8s self-healed after I set the node size to a number greater than before the node deletion failure. It's no longer failing to pull. I have no explanation.

**Comment by crockpotveggies** [comment]
I'm still experiencing this issue, even after Kubernetes has been updated to latest versions. Here is a screenshot that demonstrates the problem:

![screen shot 2017-02-17 at 12 07 20 pm](https://cloud.githubusercontent.com/assets/1445295/23081486/e0b0ab04-f509-11e6-9fb2-510775ac05cd.png)

Note that the *Running* container in the attached image has `Restarts` at 1. Once a container has been restarted by Kubernetes, it never fully comes back. Instead, the API goes down.

The only way to fix this is a manual delete. So it involves manually deleting the Pod and allowing the replication controller to provision a new one.

**Comment by MrHohn** [comment]
I'm trying to understand the issue. The previous thing we were discussing is kubelet failed to pull image, but the issue seems different now.

Is `http-api-6f68g` the only pod that was effected? And could you post the specific problem you encountered ("the API goes down" is vague)? Is this pod unreachable? Or is the service's clusterIP/external IP unreachable? Or is it non-networking issue (pod is not running correctly)?

**Comment by crockpotveggies** [comment]
Thanks for the quick follow up. I'll try to explain from the beginning. I think we were led astray by the kubelet failing to pull the image.

The core issue is that any time an image fails and Kubernetes restarts that image, the container always fails. The most visible impact occurs on our HTTP API, since that is where our external monitoring systems detect the issue.

However, this actually affects *every* container that is restarted by our system. I don't think I explained that clearly, and also because I was hesitant to make that claim. However, after re-investigating this I can confirm that this is the case.

We have some deployments that only pull from a work queue on a RabbitMQ instance. I realized that when those specific "backend" containers are restarted by Kubernetes, they fail to initialize properly and pull from the work queue. Usually I will get a message in the logs such as `Container has not logged anything yet`.

Is it possible the restart procedure is not properly executing the entrypoint script?

**Comment by crockpotveggies** [comment]
> the container always fails

For clarity sake, I'll be more specific on this. Kubernetes marks the Pod as `Running`. However, the Pod is not actually performing its functions. This is either because it doesn't log any startup messages and presumably didn't execute the startup script, or because it lacks network access (for reasons that I fully do not understand).

**Comment by MrHohn** [comment]
If the restarted pods didn't log any startup messages then I guess it would be more than just networking issue.

+@kubernetes/sig-node-bugs for more node experts.

**Comment by crockpotveggies** [comment]
![screen shot 2017-02-17 at 1 34 19 pm](https://cloud.githubusercontent.com/assets/1445295/23084154/d40eb880-f515-11e6-8b84-b67e70aa8796.png)

In the interest of providing more examples, here is another example where a "backend" pod failed. This pod is a microservice that receives request via internal load balancing.

Note that the pod has been restarted **211** times. That's quite unusual. I'd expect that pod to properly restart. However, when I examine the logs it appears all networking functionality has been severed.

![screen shot 2017-02-17 at 1 34 11 pm](https://cloud.githubusercontent.com/assets/1445295/23084188/055ccdfa-f516-11e6-9041-c4b91c68e770.png)

`Name or service not known`. That would indicate a networking issue.

Our Kubernetes deployment is littered with problems like this. I was first hesitant to say this was happening outside of our HTTP API because Kubernetes was reporting our containers as normally functioning. However, now that I've had some time to hand-check our entire infrastructure, I find this quite odd.

**Comment by MrHohn** [comment]
Ok this seems like networking issue again :(

If a pod crashed it might kept restarting, thus this unfortunate pod got restarted 211 times...

For the error `Name or service not known`, is it an external or in-cluster DNS name? Does the other affected pods have similar name resolving issue?

**Comment by MrHohn** [comment]
Though instead of saying "k8s restarted a pod caused its failure", I will guess "its failure caused k8s restarted it".

**Comment by crockpotveggies** [comment]
I think your description of the failure is accurate. In that specific case, it is making a request to Amazon S3 to access a serialized model. So that would be an external DNS name. 

Another example that operates in an entirely different environment is a backup service for MongoDB. Note that our particular MongoDB instance is set up outside of k8s, though is still running within Google Cloud. The backup service can contact MongoDB, download all available information, but when it tries to upload a serialized backup it fails. There's a troubling graveyard of containers when I check the individual pods (below).

![screen shot 2017-02-17 at 3 04 56 pm](https://cloud.githubusercontent.com/assets/1445295/23086602/c7d51e44-f522-11e6-9292-d7ca33168d8b.png)

And what I see in the logs:
```
2017-02-17T20:05:53.564500098Z WARNING: Retrying failed request: /2017.02.17.200001.gz?uploads ([Errno -2] Name or service not known)
2017-02-17T20:05:53.564593129Z WARNING: Waiting 3 sec...
2017-02-17T20:06:16.567079266Z WARNING: Retrying failed request: /2017.02.17.200001.gz?uploads ([Errno -2] Name or service not known)
2017-02-17T20:06:16.567136557Z WARNING: Waiting 6 sec...
2017-02-17T20:06:42.570020559Z WARNING: Retrying failed request: /2017.02.17.200001.gz?uploads ([Errno -2] Name or service not known)
2017-02-17T20:06:42.570076894Z WARNING: Waiting 9 sec...
2017-02-17T20:07:11.573914876Z WARNING: Retrying failed request: /2017.02.17.200001.gz?uploads ([Errno -2] Name or service not known)
2017-02-17T20:07:11.573983442Z WARNING: Waiting 12 sec...
2017-02-17T20:07:43.577702443Z WARNING: Retrying failed request: /2017.02.17.200001.gz?uploads ([Errno -2] Name or service not known)
2017-02-17T20:07:43.577766096Z WARNING: Waiting 15 sec...
2017-02-17T20:08:18.582256466Z 
2017-02-17T20:08:18.582312745Z !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2017-02-17T20:08:18.582319110Z     An unexpected error has occurred.
2017-02-17T20:08:18.582323699Z   Please report the following lines to:
2017-02-17T20:08:18.582327991Z    s3tools-bugs@lists.sourceforge.net
2017-02-17T20:08:18.582354443Z !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2017-02-17T20:08:18.582359893Z 
2017-02-17T20:08:18.582364066Z Problem: S3RequestError: Request failed for: /2017.02.17.200001.gz?uploads
2017-02-17T20:08:18.582368083Z S3cmd:   1.1.0-beta3
```

**Comment by crockpotveggies** [comment]
I should add that although these particular examples focus on failure of Amazon API resolution, our other containers do not rely on contacting Amazon to successfully run. We see similar issues. I've recently cleaned up a lot of our containers but will provide more examples as they happen. Usually we can see failure within a couple days.

**Comment by crockpotveggies** [comment]
Okay, we just experienced deployment-wide pod failure and I can demonstrate the "no logging" scenario. Below, you can see that all pods across a deployment were suddenly restarted:

![screen shot 2017-02-17 at 7 41 27 pm](https://cloud.githubusercontent.com/assets/1445295/23090052/355d6c66-f549-11e6-89c4-b9084ca972ec.png)

Every single one of these containers displays the same message:

![screen shot 2017-02-17 at 7 41 21 pm](https://cloud.githubusercontent.com/assets/1445295/23090053/3d3d6c60-f549-11e6-9259-b731fddeee78.png)

Once I delete and redeploy all pods, it functions normally again.

**Comment by MrHohn** [comment]
Sorry for the delay :(

For the empty log part, is it possible to be causing by log rotation ([doc](https://kubernetes.io/docs/user-guide/logging/overview/))? Kubernetes performs log rotation daily, if the pods do not log periodically, it seems possible to have similar situation. Because these running pods are still consuming CPU and MEM, it also seems less likely they just stall at there. And you may find useful info in kubelet logs when suspicious pods got restarted if they are in fact broken.

Regarding the failures connecting to external DNS name, the pods seems unable to resolve name when try to upload contents:
```
2017-02-17T20:07:43.577702443Z WARNING: Retrying failed request: /2017.02.17.200001.gz?uploads ([Errno -2] Name or service not known)
```
kube-dns simply forwards external DNS name request to upstream, have you found any suspicious logs in kube-dns? I saw similar issue when kube-dns failed to handle enormous amount of requests, how many kube-dns replicas are you using?

**Comment by MrHohn** [comment]
And is it possible to confirm the external DNS name / external API are functioning when this happens? Either in pods / nodes or outside of k8s?

**Comment by crockpotveggies** [comment]
Thanks for the reply. I ran into a couple problems just trying to access the logs. First, I tried viewing logs for a pod and got the infamous `This container has not logged any messages yet`.

Second while viewing the pods, it looks like there's been a lot of failure activity lately:
![screen shot 2017-02-21 at 12 39 55 pm](https://cloud.githubusercontent.com/assets/1445295/23184043/f98a07de-f832-11e6-952b-c8e3b59e35f7.png)


Note that both pods experienced 3 restarts. It appears whatever is causing these pods to fail is also affecting pods in `kube-system` which I imagine is compounding whatever problem is plaguing us.

**Comment by crockpotveggies** [comment]
> And is it possible to confirm the external DNS name / external API are functioning when this happens? Either in pods / nodes or outside of k8s?

Can you give me a fool-proof command to test this? Preferrably something I can run from my local?

**Comment by crockpotveggies** [comment]
Sorry triple message. I thought I'd add that we do a very high volume of external requests. I wasn't aware that pods were using Kubernetes to make external requests. I've since scaled the number of dns pods from 2 to 4. How do I even know when to scale this? I thought k8s was responsible for handling that?

**Comment by crockpotveggies** [comment]
Okay, this is bad. I restarted all DNS pods, and then I restarted any other Pods that require external DNS functionality. They've all failed.

Logs from kube-dns:
```
2017-02-21T20:41:15.536166176Z I0221 20:41:15.535900       1 server.go:94] Using https://10.7.240.1:443 for kubernetes master, kubernetes API: <nil>
2017-02-21T20:41:15.536943005Z I0221 20:41:15.536833       1 server.go:99] v1.5.0-alpha.0.1651+7dcae5edd84f06-dirty
2017-02-21T20:41:15.536993485Z I0221 20:41:15.536871       1 server.go:101] FLAG: --alsologtostderr="false"
2017-02-21T20:41:15.537003025Z I0221 20:41:15.536885       1 server.go:101] FLAG: --dns-port="10053"
2017-02-21T20:41:15.537010789Z I0221 20:41:15.536892       1 server.go:101] FLAG: --domain="cluster.local."
2017-02-21T20:41:15.537036299Z I0221 20:41:15.536898       1 server.go:101] FLAG: --federations=""
2017-02-21T20:41:15.537044760Z I0221 20:41:15.536915       1 server.go:101] FLAG: --healthz-port="8081"
2017-02-21T20:41:15.537051714Z I0221 20:41:15.536921       1 server.go:101] FLAG: --kube-master-url=""
2017-02-21T20:41:15.537058146Z I0221 20:41:15.536931       1 server.go:101] FLAG: --kubecfg-file=""
2017-02-21T20:41:15.537064273Z I0221 20:41:15.536937       1 server.go:101] FLAG: --log-backtrace-at=":0"
2017-02-21T20:41:15.537082117Z I0221 20:41:15.536948       1 server.go:101] FLAG: --log-dir=""
2017-02-21T20:41:15.537089093Z I0221 20:41:15.536960       1 server.go:101] FLAG: --log-flush-frequency="5s"
2017-02-21T20:41:15.537095491Z I0221 20:41:15.536973       1 server.go:101] FLAG: --logtostderr="true"
2017-02-21T20:41:15.537101636Z I0221 20:41:15.536980       1 server.go:101] FLAG: --stderrthreshold="2"
2017-02-21T20:41:15.537108470Z I0221 20:41:15.536991       1 server.go:101] FLAG: --v="0"
2017-02-21T20:41:15.537115212Z I0221 20:41:15.537001       1 server.go:101] FLAG: --version="false"
2017-02-21T20:41:15.537119836Z I0221 20:41:15.537013       1 server.go:101] FLAG: --vmodule=""
2017-02-21T20:41:15.537247372Z I0221 20:41:15.537117       1 server.go:138] Starting SkyDNS server. Listening on port:10053
2017-02-21T20:41:15.537280144Z I0221 20:41:15.537244       1 server.go:145] skydns: metrics enabled on : /metrics:
2017-02-21T20:41:15.537330967Z I0221 20:41:15.537268       1 dns.go:166] Waiting for service: default/kubernetes
2017-02-21T20:41:15.537382945Z I0221 20:41:15.537334       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
2017-02-21T20:41:15.537398864Z I0221 20:41:15.537359       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
2017-02-21T20:41:15.590672427Z I0221 20:41:15.590481       1 server.go:107] Setting up Healthz Handler(/readiness, /cache) on port :8081
```

They all *look* normal, but we're effectively down right now.

**Comment by crockpotveggies** [comment]
Things are quickly degrading here. After redeploying the DNS pods, each kube-dns instance has restarted 10 times. I just have no clue where to even start understanding these failures. I've never seen anything like this. How can I just restart *everything*?

![screen shot 2017-02-21 at 1 12 02 pm](https://cloud.githubusercontent.com/assets/1445295/23185190/5e3afa18-f837-11e6-8afd-f8443f1d1cbe.png)

**Comment by MrHohn** [comment]
This seems terrible. Can you email me (zihongz@google.com) your project number, zone and cluster name and I could take a look (assuming you are on GKE?)?

Add @bowei in loop.

**Comment by MrHohn** [comment]
> Can you give me a fool-proof command to test this? Preferrably something I can run from my local?

The simple way I think would be `dig YOUR_EXTERNAL_DNS_NAME` on one of the nodes and one of the pods.

> I've since scaled the number of dns pods from 2 to 4. How do I even know when to scale this? I thought k8s was responsible for handling that?

We introduce [dns-horizontal-autoscaler](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns-horizontal-autoscaler) since v1.5 for this purpose. You may have to scale kube-dns by yourself before v1.5.

> I just have no clue where to even start understanding these failures. I've never seen anything like this. How can I just restart everything?

Is there no errors in kube-dns logs? Could you try `kubectl describe` the kube-dns pods and kube-dns ReplicationController?

**Comment by MrHohn** [comment]
> How can I just restart everything?

These isn't a button for restarting everything. Resetting the node instance may trigger anything on that node restarts (like kubelet, kube-proxy), but I don't think it helps here.

**Comment by crockpotveggies** [comment]
Thank you very much for the quick reply. Quickly gathering the info on my
side and will email you shortly.

**Comment by thockin** [comment]
no updates in 3 months - closing
