### ISSUE TITLE
kubectl throwing group is already registered error

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#39494]
I brought up a cluster on HEAD on GCE using cluster/kube-up.sh. The cluster came up fine but running any kubectl command gives me:
```
error: group map[batch:0xc820428070 certificates.k8s.io:0xc8204280e0 componentconfig:0xc820428150 extensions:0xc820428230 policy:0xc8204282a0 rbac.authorization.k8s.io:0xc820428310 federation:0xc820377730 :0xc820377c00 authorization.k8s.io:0xc820377e30 autoscaling:0xc820377ea0 storage.k8s.io:0xc820428380 apps:0xc820377c70 authentication.k8s.io:0xc820377ce0] is already registered
```

cc @kubernetes/sig-cluster-lifecycle-misc kube-up.sh should work, right?

**Comment by nikhiljindal** [comment]
Sorry I had brought up my cluster by running `go run hack/e2e.go -v --up --build` and not cluster/kube-up.sh.

cc @ixdy @spxtr

**Comment by ixdy** [comment]
cc @deads2k ref #39092 and https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-dev/gASoXHp52R8/_7dVtpkoFQAJ

**Comment by ixdy** [comment]
@nikhiljindal what version of `kubectl` are you using?

**Comment by deads2k** [comment]
> @nikhiljindal what version of kubectl are you using?

Yeah, likely a problem with an old `kubectl`  As I recall, kubectl 1.4, was bugged and failed if you had versions other than the hardcoded ones.  Something in TPR.

**Comment by luxas** [comment]
Yes, one can't use kubectl 1.4 with apiserver 1.5, it crashes with that error if you try.

**Comment by nikhiljindal** [comment]
Yes I didnt realise I was using an older version (1.4) of kubectl.
Using the latest version works fine

**Comment by charlfasching** [comment]
Thank You, I also had a cluster running on 1.6.4 and the kubectl client of 1.4, when i downloaded a newer kubectl of 1.6, it worked

**Comment by Paxa** [comment]
Having same issue, downloaded minikube and kubectl today
```
kubectl version 
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"283137936a498aed572ee22af6774b6fb6e9fd94", GitTreeState:"clean", BuildDate:"2016-07-01T19:26:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"dirty", BuildDate:"2017-06-22T04:31:09Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
kubectl cluster-info           
Kubernetes master is running at https://192.168.99.100:8443
error: group map[federation:0xc8203dcfc0 apps:0xc8203dd0a0 batch:0xc8203dd1f0 :0xc8203dd030 authorization.k8s.io:0xc8203dd110 autoscaling:0xc8203dd180 componentconfig:0xc8203dd260 extensions:0xc8203dd2d0 policy:0xc8203dd340 rbac.authorization.k8s.io:0xc8203dd3b0 authentication.k8s.io:0xc8203dd490] is already registered
```

**Comment by IanLewis** [comment]
@Paxa this is exactly the issue. Your kubectl is 1.3. You need to upgrade kubectl to the latest version.

**Comment by yogesh9391** [comment]
I answered for this question at https://stackoverflow.com/questions/44950816/not-able-to-deploy-k8s-pod-when-tried-through-jenkins-job-on-gce/45013094#45013094

**Comment by Paxa** [comment]
@IanLewis I just downloaded latest minikube and kubectl
