### ISSUE TITLE
Update the vendored version of aws-sdk-go

### ISSUE THREAD

**Issue by bjornswift** [kubernetes/kubernetes#39502]
Can the vendored version of aws-sdk-go be upgraded? We're hitting AWS ECR throttling limits on GetAuthorizationToken which should be retried by aws-sdk-go. However, Kubernetes is vendoring an old version of the SDK which has poor retry logic. Newer versions of aws-sdk-go have improved on this, and upgrading to a newer version of the sdk would be great (as we believe that would retry properly and solve the issue).

**Details:** When minions come up they issue a GetAuthorizationToken request in order to authenticate against ECR. This API has strict throttle limits (1 TPS, burst of 50) which AWS is unwilling to increase on an account-by-account bases, see http://docs.aws.amazon.com/AmazonECR/latest/userguide/common-errors.html. As a result, bringing up medium sized clusters (100+) leaves several minions in a state where they cannot authenticate to ECR are are stuck in an image-pull-error state (if they pull images from ECR).

Retries should help, but the vendored aws-sdk-go is old and seems to have poor retry logic. This has been improved in newer releases.

**What keywords did you search in Kubernetes issues before filing this one?** aws-sdk-go aws sdk GetAuthorizationToken

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version**: 1.2.4, but looks like it also applies to `master`

**Environment**:
- **Cloud provider or hardware configuration**: aws
- **OS**: CoreOs 1235.4.0

**What happened**:

Spun up a 150 node cluster in AWS. We use CoreOs's kube-aws.

**What you expected to happen**:

All nodes come up, are able to eventually run GetAuthorizationToken successfully.

**How to reproduce it** (as minimally and precisely as possible):

Deploy a large cluster in AWS. Look for `aws_credentials.go:130] while requesting ECR authorization token ThrottlingException: Rate exceeded` in `journalctl` on minions.

**Comment by bjornswift** [comment]
@kubernetes/sig-aws-misc

**Comment by justinsb** [comment]
@bjornswift we're going to update the AWS SDK in https://github.com/kubernetes/kubernetes/pull/53561 .  But what are the changes in the AWS SDK that improve this situation?

**Comment by bjornswift** [comment]
The vendored version didn't include improvements to the aws-sdk-go's request retry logic. Most AWS SDKs use similar exponential back-off retry policies, but early versions of aws-sdk-go didn't (for some reason). This has since been addressed, and should be included in 1.12.7 which #53561 updates to.

(I can find the relevant commits, if of interest, but this was added to aws-sdk-go ages ago.)

**Comment by justinsb** [comment]
OK I'm just debating if we really should close this issue when we merge >= 1.12.7 or whether we should actually look at the underlying issue.  The version of the AWS SDK we were using before had per-request backoffs, and onto that we layered a per-process backoff layer: https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/retry_handler.go

The reason for that (very heuristic) per-process backoff was that otherwise a process would still DoS an AWS account, when there were a large number of threads issuing requests, or where we were retrying failed requests without an additional backoff.

**Comment by bjornswift** [comment]
Interesting, I don't remember having seen the per-process limits. To be perfectly honest, I'm a little hazy on the details. What I do remember is that the retry logic in the vendored version was really agressive, and would fire three (I think) requests over a short period of time. As a result, if the AWS service was having issues or was throttling requests, in our experience, the client wouldn't space out its retries sufficiently.

We then read through the aws-sdk-go retry policy and logic, and were confused as to why requests were being issued so rapidly, until we realized that kubernetes was vendoring an older version of aws-sdk-go.

So in short, I think the upgrade will satisfy closing this issue _for the purpose of better handling generic aws throttles/500s_.

However, as you correctly point out, the possibly more severe underlying issue related to how Kubernetes authenticates towards ECR. Currently, each node separately reaches out to authenticate, but due to the (hard) service limits of GetAuthorizationToken, this imposes a cluster size ceiling when running on AWS. In contrast, one could avoid this by having a single entity renew the ECR token and distribute it with a secret, similar to https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/. All this said, that might be something best tracked separately?
