### ISSUE TITLE
masters causing route53 rate exceeded/Throttling issue in AWS

### ISSUE THREAD

**Issue by hridyeshpant** [kubernetes/kubernetes#39509]
**Kubernetes version** (use `kubectl version`):

kops version
Version 1.4.4

kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: aws
- **OS** (e.g. from /etc/os-release): amazon linux

**What happened**:
as per
http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html 
>>Five requests per second per AWS account are allowed. If you submit more than five requests per second, Amazon Route 53 returns an HTTP 400 error (Bad request). The response header also includes a Code element with a value of Throttling and a Message element with a value of Rate exceeded.
>>
we set up kubernetes in AWS with having three master using kops http://kubernetes.io/docs/getting-started-guides/kops/.
All three master EC2 instances which makes the R53 API calls which is exceeding the 5API calls per second. Here instance id and API calls per second.
1. i-033a2d4dff5fa39d3    **   Max 3 API Calls/sec
2. i-008dcee283bbc7c5a    **    Max 2.9 API Calls/sec
3. i-099dbb226a9fe25e6    **    Max 2.9 API Calls/sec
All this sources making the API call "ListResourceRecordSets".

Due to this we are continuously getting  Rate exceeded and causing our other deployment failed during route53 operation .After deleting the masters things get normal.
**What you expected to happen**:
Can you suggest what is the best possible solution for this? and how we can prevent this.

**How to reproduce it** (as minimally and precisely as possible):
create multiple master with kops.

Anything else do we need to know?

**Comment by hjacobs** [comment]
@hridyeshpant maybe this should be an issue for kops? DNS controller is part of kops AFAIK: https://github.com/kubernetes/kops/tree/master/dns-controller

BTW: we are using an alternative "DNS Controller" for AWS Route53: https://github.com/zalando-incubator/mate

**Comment by ideahitme** [comment]
@hridyeshpant feel free to take a look at the AWS/GKE DNS controller we are running in our cluster setup (https://github.com/zalando-incubator/mate) 

Mate is only making Route53 API calls in two cases (and not hitting the AWS API limitation):
1. When new service is created - this case is tracked via Kubernetes service monitoring, hence immediate update when service is created
2. Every minute we sync all services (type LoadBalancer) - to synchronise the state, which includes removal/update/creation of AWS RRS. 
Only one instance of mate is running per cluster (via deployment with replicas = 1), though planning to introduce HA mode (with one active master determined via Leader Election).  Hence the chances of hitting the limit are low and can only happen in the cluster with extremely frequent service creations.

**Comment by justinsb** [comment]
Thanks for opening the kops issue.

There are actually two pieces that do DNS in kops, protokube and dns-controller.  I suspect this might be protokube, but I'll take a look and make sure!

In any case, it's a straight bug - no dns controller should be making that many API calls, particularly when nothing is changing :-)

I believe we have plans to merge mate & dns-controller and put it into the incubator, so you won't even have to choose :-)

Any objection to my closing this issue in favor of the kops issue @hridyeshpant ?

**Comment by hridyeshpant** [comment]
Thanks @justinsb .you can close this as i already open issue in kops.
Do you have any workaround on this? i am completely blocked due to this issue and have to disable kubernetes masters.
