### ISSUE TITLE
fail to make quick-release (rsync error)

### ISSUE THREAD

**Issue by xilabao** [kubernetes/kubernetes#39513]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**Kubernetes version** (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2850+4398e1edb00b7c-dirty", GitCommit:"4398e1edb00b7cd00b56abb9673467746063d148", GitTreeState:"dirty", BuildDate:"2017-01-06T09:06:04Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2753+f95362f953b681-dirty", GitCommit:"f95362f953b681b495822e99bb772246312c25f9", GitTreeState:"dirty", BuildDate:"2017-01-04T08:46:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:
```
# make quick-release
+++ [0106 16:59:51] Verifying Prerequisites....
+++ [0106 16:59:52] Building Docker image kube-build:build-9901a0c10c-4-v1.7.4-1
+++ [0106 16:59:56] Syncing sources to container
ERROR: password file must be owned by root when running as root
rsync error: syntax or usage error (code 1) at authenticate.c(200) [sender=3.1.1]
Makefile:361: recipe for target 'quick-release' failed
make: *** [quick-release] Error 1
```
**How to reproduce it** (as minimally and precisely as possible):

the owner of file is not right

**Comment by ixdy** [comment]
Do you need to be building as root?

**Comment by xilabao** [comment]
@ixdy  I get an annoying message when building as normal user: 
 `mv: replace '.make/pkg/generated/gofiles.mk', overriding mode 0644 (rw-r--r--)? ` 
So I run `make quick-release` as root. There will return a error if the outpt build directory is not owned by root when running as root. I think we could use `chown`to fix it.

**Comment by xilabao** [comment]
@ixdy I hope to get some of your suggestions

**Comment by ixdy** [comment]
did you previously build as `root`? you might need to `make clean` before a build as a normal user works again.
