### ISSUE TITLE
Problem with kubernetes and flocker agent-control node connectivity

### ISSUE THREAD

**Issue by Lain92** [kubernetes/kubernetes#39522]
Hello,

This issue is also submitted at https://github.com/ClusterHQ/flocker/issues/2994 but the related component is part of this repository.

I tried to install Flocker with my Kubernetes cluster.
K8s version : 1.5.1
Flocker version : 1.15.0
I have problems similar to this old issue : kubernetes/kubernetes#17651
My nodes are on Centos 7.3.
I'm using VMWare-flocker-plugin to provision the storage. Everything is working as long as it doesn't deal with Kubernetes.
I tried both https://clusterhq.com/2015/12/22/ha-demo-kubernetes-flocker/ demo and https://github.com/vmware/vsphere-flocker-driver installation instructions.

The problem is that kubelet cannot reach the control node because it cannot fetch the environment variables :
FLOCKER_CONTROL_SERVICE_HOST
FLOCKER_CONTROL_SERVICE_PORT
FLOCKER_CONTROL_SERVICE_CA_FILE
FLOCKER_CONTROL_SERVICE_CLIENT_KEY_FILE
FLOCKER_CONTROL_SERVICE_CLIENT_CERT_FILE

I tried every single way to pass these variables :

By setting them as temporary env var with export
By setting them into /etc/.bashrc
By passing them into /etc/systemd/system/kubelet.service file as Environment=
By passing them into /etc/systemd/system/kubelet.service file as EnvironmentFile=/etc/kubernetes/kubelet.env containing all variables
Unfortunately, kubelet/flocker-agent doesn't seem to get these variables.

The datasetUUID for volume with datasetName='volume1' can not be found using flocker: Get https://localhost:4523/v1/configuration/datasets: dial tcp 127.0.0.1:4523: getsockopt: connection refused
This is because the https://github.com/kubernetes/kubernetes/blob/v1.5.1/pkg/volume/flocker/flocker.go
defines default variables as :

const (
	flockerPluginName = "kubernetes.io/flocker"

	defaultHost           = "localhost"
	defaultPort           = 4523
	defaultCACertFile     = "/etc/flocker/cluster.crt"
	defaultClientKeyFile  = "/etc/flocker/apiuser.key"
	defaultClientCertFile = "/etc/flocker/apiuser.crt"
	defaultMountPath      = "/flocker"

	timeoutWaitingForVolume = 2 * time.Minute
	tickerWaitingForVolume  = 5 * time.Second
)

I took the flocker.go module NewClient function from kubernetes/kubernetes github to test it on my machine :

package main

import (
  "fmt"
  "os"
)

func GetEnvAsStringOrFallback(key, defaultValue string) string {
        if v := os.Getenv(key); v != "" {
                return v
        }
        return defaultValue
}

func main() {
        fmt.Println(GetEnvAsStringOrFallback("FLOCKER_CONTROL_SERVICE_HOST", "default"))
}

and I get the variable :

[root@k8s-storage-s3 ~]# go run test.go 
192.168.40.31
I don't know what to do, there is only this problem left for my Kubernetes to work with Flocker.

**Comment by eddytruyen** [comment]
The problem is probably because the kubelet runs in a docker container. You have to pass the env variables to the docker container using -e option of docker run and mount the flocker_ca_dir as a volume using the -v option. You can see how I implemented it for docker-multinode deployment tool at https://github.com/eddytruyen/kube-deploy project and then go to the docker-multinode directory.

A more recent deployment tool called kubeadm runs kubelet natively in centos. So there it is sufficient to define the env variables as you did
