### ISSUE TITLE
Create k8s.io/apimachinery repo

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#39528]
Having multiple copies of the base apimachinery types makes it impossible to cleanly make use of client-go inside of k8s.io/kubernetes and makes it impractical to separate our the genericapiserver.

There is a pull to split out the apimachinery (https://github.com/kubernetes/kubernetes/pull/39475), but it requires updates to gengo (https://github.com/kubernetes/gengo/pull/29) which will only work if there is a target to handle a `go get` of k8s.io/apimachinery.

We need to
 - [x] Create the k8s.io/apimachinery repo (give @lavalamp and me write access)
 - [x] I prime the repo with the result of https://github.com/kubernetes/kubernetes/pull/39475 before it merges
 - [x] We use that starting point to merge https://github.com/kubernetes/gengo/pull/29
 - [x] I update https://github.com/kubernetes/kubernetes/pull/39475 to bump gengo and we merge it.
 - [x] We create a verify script to prevent updates to "mirror" packages in k8s.io/kubernetes
 - [x] and set it up while we transition repos like heapster and client-go. (I might ask @sttts to help with his bash-fu)
 - [x] check that all hack/* script operate on staging/src/apimachinery
 - [x] sync synchronously with client-go via a publish bot

@lavalamp @kubernetes/sig-api-machinery-misc @sttts @smarterclayton

**Comment by lavalamp** [comment]
It'd be nice to have step 5 ready to go so we don't end up with a big mess.

I'd like to have a nice README ready to go before I make this repo, so people will be able to understand its scope. E.g., target users include both client and servers, so nothing specific to one of those should appear in the repo. Where and how to make changes. Stuff like that. The mirroring stuff is confusing enough already...

**Comment by deads2k** [comment]
I'll write one up Monday morning.  Since this in direct support of kube I think we can start it with a branching pattern to match kube and no compatibility guarantees for the foreseeable future.  Those who vendor must know what they're doing, just like they must today.

I can split tests in a different pull and then I ought to be able to include the "no touching" commit in the same pull as the move.  @sttts help wanted with that. I'm likely to do something really ugly with diff-tree, awk, sed, and grep.

**Comment by deads2k** [comment]
Created https://gist.github.com/deads2k/fff58bbb306d9cb073fc7d4aea8e9a14 as a first shot at a README.md.

**Comment by lavalamp** [comment]
I created the repo.

**Comment by sttts** [comment]
@deads2k anything left here?

**Comment by deads2k** [comment]
> @deads2k anything left here?

Getting script set up.

**Comment by smarterclayton** [comment]
Done yet?

**Comment by sttts** [comment]
https://github.com/kubernetes/test-infra/pull/1784 is still open.
