### ISSUE TITLE
Configurable timeouts for AWS

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#39524]
Currently, AWS re-tries every AWS API call several times due to AWS throttling. Timers and number of retries are not configurable. They may be too long for small clusters, which are unlikely to hit API quota and too short for big clusters which would need longer recovery times. 

Would it make sense to make them configurable? I don't have any real user behind this, it's more gut feeling that this may go wrong for large deployments.

If they should be configurable, when the configuration should be? In aws.conf from `--cloud-config=/etc/aws.conf`? Or on API server / controller-manager / kubelet command-line (`--aws-timer-scale=2.0` to double the timers?)

@justinsb, opinions?

**Comment by patrickmcclory** [comment]
@jsafrane - we're seeing something very similar and possibly a little more focused as reported in #39526 

imho there's a core concern about how we're relying on the AWS api for external validation of something that should be checked externally and validated internally -- in our case, the API calls for volumes keep pounding DescribeInstances where a node-level fdisk check would validate attach once we made the call for a volume. do you have a list of api calls you're seeing fail or flood your account?  We're primarily seeing DescribeInstances with some DescribeVolumes being hit by api rate limiting on the AWS side.

**Comment by justinsb** [comment]
So I feel like _requiring_ the user to tweak these settings means we aren't doing a good job, but I also feel that an escape valve is handy for extreme cases.

That said, I worry that we don't know what the knobs should be.  If we are able to move to a coherent caching model (#39647, as you pointed out) then the dials will likely be different.  _Hopefully_ we wouldn't need any dials, but I do think the dials will be different.

I agree, but I don't think we can/should do this yet.

But OTOH ... putting settings into aws.conf feels very low-impact, and we could probably do that even if we thought they were going to be ignored/irrelevant in future.

**Comment by gnufied** [comment]
@justinsb I think coherent caching model currently will only handle - instance, node information unless we start caching output of things like `describeVolume` etc as well. I feel we may be bit far from a caching model which can keep all these different resources fresh and updated. 


cc @kubernetes/sig-storage-misc
