### ISSUE TITLE
KubeDNS on baremetal - will not start

### ISSUE THREAD

**Issue by craigwillis85** [kubernetes/kubernetes#39531]
Hi

I'm trying to setup a baremetal cluster on Vultr.

I have 2 masters and 2 nodes setup, the problem is I'm having a problem with kube-dns.

Having started the service and the deployment, I'm always getting a `CrashLoopBackOff` on the kube-dns pods.

Describing one of the pods below (small snippet):

    Warning	Unhealthy	Readiness probe failed: Get http://10.200.0.55:8081/readiness: dial tcp 10.200.0.55:8081: getsockopt: connection refused

    Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kubedns" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kubedns pod=kube-dns-v20-804846854-41j2v_kube-system(fe117b7a-d42f-11e6-8050-5600004c9418)"

    Warning	Unhealthy	Liveness probe failed: HTTP probe failed with statuscode: 503

    Warning	FailedSync	Error syncing pod, skipping: [failed to "StartContainer" for "dnsmasq" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=dnsmasq pod=kube-dns-v20-804846854-41j2v_kube-system(fe117b7a-d42f-11e6-8050-5600004c9418)

I was following [Kelseys Kubernetes The Hard Way](https://github.com/kelseyhightower/kubernetes-the-hard-way), but this in on baremetal

I'm running 1.5.1 and all my machines are running Ubuntu 6.04

If you need my api-server services or my kubelet service I'm happy to provide them

Thanks

**Comment by cackharot** [comment]
I also faced the same issue when setting up a local baremetal cluster using Ubuntu 14.04. 

My exact issue is when the DNS pods starts it fails to authenticate with the cluster api server using service account token.

In my case I ran the `get-kube.sh` few times as I was initially playing around with it by creating few busybox pods and then moved to install DNS add-on. This messes up the cluster authentication, as it generates the server.cert/key pair every time you setup the cluster which results in the config secrets to become invalid. My solution is to manually delete the *default-token-xxx* secrets in all namespaces and recreate your pods. This should fix any authentication issue.

If your case is not similar to mine, posting the entire log of kube-dns pod would help to diagnose better.

**Comment by kargakis** [comment]
@craigwillis85 can you post the log of the kube-dns pod?

Maybe related to https://github.com/kubernetes/kubeadm/issues/99

**Comment by craigwillis85** [comment]
This is what I did in the end as well.

Deleting the default serviceaccount seemed to work (regenerated the default
secret as well)

**Comment by kargakis** [comment]
@craigwillis85 can this issue be closed now?
