### ISSUE TITLE
AUTH: Admin role cannot GET healthz

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#39532]
**What keywords did you search in Kubernetes issues before filing this one?**: rbac, healthz

---

**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Kubernetes version** (use `kubectl version`):

```console
> ./cluster/kubectl.sh version                        
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2397+1bfd4f0a717151", GitCommit:"1bfd4f0a7171513db69d2344d997df7f34ce9ee0", GitTreeState:"clean", BuildDate:"2017-01-05T23:07:04Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2843+8ef690251641b7", GitCommit:"8ef690251641b7df6749f67abff86fa01c10b070", GitTreeState:"clean", BuildDate:"2017-01-05T20:47:37Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GCE

**What happened**: I manually upgraded a cluster and it hung forever trying to curl /healthz. The response that comes back is 403 (Forbidden).

It seems that the admin role account does not have access to curl /healthz. The same exact bearer token could curl /api and /api/v1.

**What you expected to happen**: I expected to get a 200 (Success) response.

**How to reproduce it** (as minimally and precisely as possible): Turn up a 1.6 cluster and curl healthz.

```console
> curl --insecure -H "Authorization: Bearer <admin token>" --max-time 5 --fail https://<ip address>/healthz
curl: (22) The requested URL returned error: 403 Forbidden
```

**Anything else do we need to know**:

Currently causing failures in suites like https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-gci-latest-1.4-gci-latest-upgrade-cluster-new/

cc @kubernetes/sig-auth-misc @cjcullen @liggitt to help triage

**Comment by liggitt** [comment]
looks upgrade related. need to ensure bootstrap roles/rolebindings are reconciled on upgrade, not just when etcd is empty.
cc @deads2k

**Comment by krousey** [comment]
It's not upgrade related. I just brought up a recent version using kube-up.sh, and it has the same issue. I think I just noticed it on upgrades because it was picking up the latest version.

kube-up.sh does a health check on /api/v1/pods while upgrade.sh does a health check on /healthz.

**Comment by deads2k** [comment]
> might be upgrade-related. need to ensure bootstrap roles/rolebindings are reconciled on upgrade, not just when etcd is empty. cc @deads2k

You're sure we want to?  Annotation based skips?  I'm probably in favor, but at a certain point it starts looking more controller like than post-start-hook like.

**Comment by deads2k** [comment]
> It's not upgrade related. I just brought up a recent version using kube-up.sh, and it has the same issue. I think I just noticed it on upgrades because it was picking up the latest version.
> 
> kube-up.sh does a health check on /api/v1/pods while upgrade.sh does a health check on /healthz.

@liggitt @kubernetes/sig-auth-misc How protected should `/healthz` be by default?  We chose to defend it in openshift, but that makes for some challenges when describing readiness checks inside of a pod.

**Comment by deedubs** [comment]
Definately interested in the answer to @deads2k's question about `/healthz` auth as it pertains to https://github.com/kubernetes/kops/issues/1647

**Comment by deads2k** [comment]
> Definitely interested in the answer to @deads2k's question about /healthz auth as it pertains to kubernetes/kops#1647

We decided to make `/healthz` non-confidential and protect its sub-checks. It returns ok or a list of just names and pass/fail without any details.  It has been added to the system:discovery role.
