### ISSUE TITLE
Cannot list statefulsets.apps at the cluster scope

### ISSUE THREAD

**Issue by enisoc** [kubernetes/kubernetes#39541]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

* `"at the cluster scope"`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2884+25e836010f15b8", GitCommit:"25e836010f15b813caacf9a24850a036e15ed739", GitTreeState:"clean", BuildDate:"2017-01-06T19:41:39Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2884+25e836010f15b8", GitCommit:"25e836010f15b813caacf9a24850a036e15ed739", GitTreeState:"clean", BuildDate:"2017-01-06T19:39:16Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**: `make quick-release && cluster/kube-up.sh`
- **Others**:

**What happened**:

The `kube-controller-manager.log` is constantly flooded with the following error once per second:

```
reflector.go:199] pkg/controller/disruption/disruption.go:330: Failed to list *v1beta1.StatefulSet: User "system:serviceaccount:kube-system:disruption-controller" cannot list statefulsets.apps at the cluster scope. (get statefulsets.apps)
```

**What you expected to happen**:

Log not flooded with error.

**How to reproduce it** (as minimally and precisely as possible):

1.  Start a cluster at the above version.
1.  Check the `kube-controller-manager.log` on master.

**Anything else do we need to know**:

I didn't create any StatefulSets or PDBs. I only created some RCs.

**Comment by enisoc** [comment]
Attn @foxish

**Comment by foxish** [comment]
cc @mwielgus 
This looks related to https://github.com/kubernetes/kubernetes/pull/39454

**Comment by foxish** [comment]
Looks like an authorization issue. It doesn't seem to happen on a local cluster.

From APIServer logs:
```
I0106 20:54:43.107342       5 rbac.go:49] RBAC DENY: user "system:serviceaccount:kube-system:disruption-controller" groups [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] cannot "list" on "statefulsets.apps/"
I0106 20:54:43.107994       5 panics.go:75] GET /apis/apps/v1beta1/statefulsets?resourceVersion=0: (1.049174ms) 403 [[kube-controller-manager/v1.6.0 (linux/amd64) kubernetes/aa75099/system:serviceaccount:kube-system:disruption-controller] [::1]:33302]
```
