### ISSUE TITLE
kubefed init needs to create rolebinding to allow cluster controller to fetch secret

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#39555]
With the latest rbac changes, federation cluster controller is not able to fetch secrets from host cluster for registered clusters.  The exact error is 
`error in fetching secret: User "system:serviceaccount:federation-system:default" cannot get secrets in the namespace "federation-system"`
As a result, registered clusters never turn ready.

Running the following fixed the problem for me:
```
kubectl create rolebinding -n federation-system edit --serviceaccount federation-system:default --clusterrole=admin
```
We should define our own clusterrole rather than using admin.

cc @madhusudancs @kubernetes/sig-federation-misc 
cc @liggitt and @deads2k as fyi

**Comment by deads2k** [comment]
> We should define our own clusterrole rather than using admin.

Yes, that's a good idea.  This post has relevant links for adding bootstrap roles: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-dev/gASoXHp52R8/_7dVtpkoFQAJ

**Comment by madhusudancs** [comment]
Fixed in PR #40392.

**Comment by nikhiljindal** [comment]
I brought up federation by running `NUM_NODES=1 FEDERATION=true E2E_ZONES=\"us-central1-a us-central1-f\" KUBE_UP_AUTOMATIC_CLEANUP=true go run hack/e2e.go --up --federation --deployment=none` and still saw the same problem on HEAD.

That command should ideally be using `kubefed init` so there should not be any difference, but looks like there is.

**Comment by quinton-hoole** [comment]
@nikhiljindal @madhusudancs Has this been resolved yet.  Can it be closed?

**Comment by quinton-hoole** [comment]
Needs to be resolved in order to GA federation.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#91.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
