### ISSUE TITLE
Improve SIG-Scheduling code coverage

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#39559]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):
master (1.6)

**What happened**:
This issue is used to trace code health investigation in preparation for Kubernetes v1.6.  Assuming a goal of **80%** coverage.

The following package are included, coverage reports are based on recent master (SHA 8667d7c4f158ce3e2d117f223e6b4debdfc68ee8):

__Kubernetes__

Package | Coverage | Done | Comments
-------- | ------------- | ------ | ------
pkg/api/validation | 80.1% | √
pkg/kubelet | 55.8% | | #40780
plugin/pkg/admission/admit | 80.0% | √
plugin/pkg/admission/alwayspullimages | 84.6% | √
plugin/pkg/admission/antiaffinity | 94.1% | √
plugin/pkg/admission/deny | 80.0% | √
plugin/pkg/admission/exec | 83.3% | √
plugin/pkg/admission/gc | 72.4% | X | one file, no coverage on negative case
plugin/pkg/admission/initialresources | 80.2% | √
plugin/pkg/admission/limitranger | 89.9% | √
plugin/pkg/admission/namespace/autoprovision | 73.1% |X|one file, no coverage on negative case
plugin/pkg/admission/namespace/exists | 70.4% | X|one file, no coverage on negative case
plugin/pkg/admission/namespace/lifecycle | 79.6% | X|one file, no coverage on negative case
plugin/pkg/admission/persistentvolume/label | 40.2% | X | vendor related
plugin/pkg/admission/podnodeselector | 63.5% | X|one file, no coverage on config read
plugin/pkg/admission/resourcequota | 71.5% | X| no coverage on config read & get/set
plugin/pkg/admission/securitycontext/scdeny | 90.0% | √
plugin/pkg/admission/security/podsecuritypolicy | 77.6% | X| one file, no cover on negative cases
plugin/pkg/admission/storageclass/default | 78.6% | X| one file, no cover on negative cases
plugin/pkg/admission/serviceaccount | 84.8% | √
plugin/pkg/admission/imagepolicy | 84.3% | √
plugin/pkg/scheduler | 73.1% | X| one file, no cover on negative cases
plugin/pkg/scheduler/api/validation | 100.0% | √
plugin/pkg/scheduler/algorithmprovider/defaults | 89.1% | √
plugin/pkg/scheduler/algorithm/predicates | 81.0% | √
plugin/pkg/scheduler/algorithm/priorities | 88.5% | √
plugin/pkg/scheduler/schedulercache | 62.8% | X | no cover for get/set
plugin/pkg/scheduler/factory | 54.1% | X | no cover on pod/node add/update/delete callback

__Node Feature Discovery__:
- [ ] github.com/kubernetes-incubator/node-feature-discovery

**How to generate code coverage reports**

The Makefile supports running the tests with `go build -cover ...` and generating an HTML report with `go tool cover -html ...`. To use it, invoke make as follows:

```
$ make test WHAT=/pkg/in/question KUBE_COVER=y
```

**Comment by resouer** [comment]
@NickrenREN @yuexiao-wang @tanshanshan @du2016 This is a good place to contribute and learn code for staters.

**Comment by liamawhite** [comment]
Im interested in taking on /pkg/api/resource, I'll get working on the PR.

**Comment by timothysc** [comment]
feel free to ping me on the reviews, my only requests are: 

1. Prior to pinging please make certain all the checks are green. 
2. Please do not add any unnecessary dependencies, we are striving to refactor portions of the scheduler to ensure that they can be linked externally.  
3.  Try not to apply the cookie cutter too much.  If there are missing array style tests, please strive to leverage closures vs. code repeat blocks.  

Cheers,
Tim

**Comment by du2016** [comment]
@resouer  i'd like have a try,thank you

**Comment by tanshanshan** [comment]
I wil try it , thanks.

**Comment by resouer** [comment]
Add a test coverage result with `make test WHAT=/pkg/in/question KUBE_COVER=y` would be helpful to reviewers.

**Comment by yuexiao-wang** [comment]
@resouer All right. I will do it. Thanks

**Comment by tanshanshan** [comment]
I have a question about  executing `make test`.

When I use `make test KUBE_COVER=y` , everything is ok , 
but when I use  `make test WHAT=pkg/api/util/ KUBE_COVER=y `  ,  the error is 

> can't load package: package pkg/api/util: cannot find package "pkg/api/util" in any of:
        /usr/local/go/src/pkg/api/util (from $GOROOT)
        /root/empty-check/src/k8s.io/kubernetes/_output/local/go/src/pkg/api/util (from $GOPATH)

My current GOPATH is 

>  /root/empty-check:/usr/local/go-ext-path

I can not find 
`/root/empty-check/src/k8s.io/kubernetes/_output/local/go/src/pkg/api/util `  ,
but there is 
 `/root/empty-check/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/api/util/` .

How to run  `make test`  with specified package?

Thanks.

**Comment by k82cn** [comment]
@tanshanshan 

```
make test WHAT=./pkg/api/util/ KUBE_COVER=y
```

or

```
make test WHAT=k8s.io/kubernetes/pkg/api/util/ KUBE_COVER=y
```

**Comment by tanshanshan** [comment]
@k82cn , it's ok, thank you.

**Comment by timothysc** [comment]
Thanks everyone that contributed to this for 1.6 release!  I'm going to bump 1.7 milestone.

**Comment by k82cn** [comment]
@timothysc , I'm reviewing the coverage of scheduling to make sure this will be finished in 1.7.

BTW, some pkg is not deserved an improvement to me; I'll leave comments for them and let you review them :).

**Comment by Rushit** [comment]
Hi,

I could add some tests here. Is there any priority or should i just pick lowest first?

**Comment by timothysc** [comment]
Priority on code coverage for 1.7 cycle is low and TBH requires re-evaluation.
@k82cn do you have updated #'s?

**Comment by k82cn** [comment]
@timothysc , the coverage number was updated in description:

* X: means the coverage is not 80%, but I'd suggest to keep it as is (added notes to it), e.g. no coverage on get/set is ok
* √: means the coverage is 80% now.

for now, the following three package need helps:

* pkg/api/validation
* plugin/pkg/admission/persistentvolume/label
* github.com/kubernetes-incubator/node-feature-discovery

BTW, I had added a PR (#45331) for `plugin/pkg/scheduler/schedulercache`

@Rushit , maybe you can try `pkg/api/validation`; some functional paths are not covered, although it's close to 80% :).

**Comment by timothysc** [comment]
I'm going to closeout this issue and we can address on a per-PR basis going forwards.  

Thanks to all for the help in this area.
