### ISSUE TITLE
Default Storage Classes can't easily be disabled

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#39561]
PR https://github.com/kubernetes/kubernetes/pull/31617/files introduced default storage classes for 1.6. They are created with cluster addon which can not easily be modified by end users (requires access to the master).

We should improve experience before 1.6 goes out.

CC @kubernetes/sig-storage-misc

**Comment by thockin** [comment]
@mikedanese another call for addon manager to distinguish initial values
from re-asserted values.

**Comment by saad-ali** [comment]
@msau42 can help out with this

**Comment by thockin** [comment]
@mrhohn @mikedanese who among us feels the most ownership of addon
manager?  This is reaching a boiling point.

**Comment by MrHohn** [comment]
As @mikedanese [mentioned before](https://github.com/kubernetes/kubernetes/pull/34639#issuecomment-253858033), it wouldn't be hard to implement an "oneshot" functionality. I also had [a short proposal](https://github.com/kubernetes/kubernetes/pull/34639#issuecomment-253717529) for this.

If we agree this is the proper way to go with, I can also help out. The required work I expect would be putting couple more startup logics into [kube-addon.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/kube-addons.sh) that carefully handle upgrade/restart cases.

**Comment by thockin** [comment]
Other that StorageClass (which I guess an admin *might* want to remove) I
don't think oneshot is what we want.  Maybe we just want to ensure that an
object exists and if it doesn't, create it with a known base-config.  Is
that sufficient?

**Comment by MrHohn** [comment]
Ensure exist sounds good. What about two classes: one that reconcile, the other ensure exist?

**Comment by msau42** [comment]
That sounds acceptable.  We mainly need:

1. A way to be able to change the default-class annotation
2. That change should persist across upgrades

I think it is ok if the deletion case is not supported.  Changing the default-class is sufficient to get the behavior we want.

**Comment by jsafrane** [comment]
@msau42, can I help you in any way? I know very little about addon manager and its internals.

**Comment by msau42** [comment]
Thanks, I plan to coordinate with addon folks to make the change.  It may end up being that all the changes are only in the addon component.
