### ISSUE TITLE
Upgrade on GKE from 1.4.7 to 1.5.1 - Scheduling issues for pods with a persistent volume

### ISSUE THREAD

**Issue by sbadia** [kubernetes/kubernetes#39584]
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GKE
  * master and nodes on `k8s 1.5.1`
  * nodes on `Debian 7.11/3.16.0-4-amd64`

**What happened**:

During the upgrade of our cluster on GKE from 1.4.7 to 1.5.1 some pods with persistent volumes are scheduled twice for a deployment, and one of the twice pods is stuck in `ContainerCreating` state because of a `FailedMount` error (the volume is attached on the other pod…)

```
% kubectl --namespace=int2 describe deployment sentry
Name:			sentry
Namespace:		int2
CreationTimestamp:	Mon, 15 Aug 2016 11:44:23 +0200
Labels:			name=sentry
Selector:		name=sentry
Replicas:		1 updated | 1 total | 0 available | 1 unavailable
StrategyType:		RollingUpdate
MinReadySeconds:	0
RollingUpdateStrategy:	1 max unavailable, 1 max surge
OldReplicaSets:		<none>
NewReplicaSet:		sentry-263511705 (1/1 replicas created)
No events.
```
```
% kubectl --namespace=int2 get ev |grep sentry-263511705-1gxsz
1m         2d          1577      sentry-263511705-1gxsz   Pod                                   Warning   FailedMount               {controller-manager }                         Failed to attach volume "int2-sentry-db" on node "gke-c2-default-pool-40cc47de-8v7r" with: googleapi: Error 400: The disk resource 'int2-sentry-db' is already being used by 'gke-c2-default-pool-40cc47de-7mir'
55s        2d          1476      sentry-263511705-1gxsz   Pod                                   Warning   FailedMount               {kubelet gke-c2-default-pool-40cc47de-8v7r}   Unable to mount volumes for pod "sentry-263511705-1gxsz_int2(4ccd0dd9-d414-11e6-9879-42010af00088)": timeout expired waiting for volumes to attach/mount for pod "sentry-263511705-1gxsz"/"int2". list of unattached/unmounted volumes=[int2-sentry-db]
55s        2d          1476      sentry-263511705-1gxsz   Pod                                   Warning   FailedSync                {kubelet gke-c2-default-pool-40cc47de-8v7r}   Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "sentry-263511705-1gxsz"/"int2". list of unattached/unmounted volumes=[int2-sentry-db]
```
```
% kubectl --namespace=int2 get pods|grep sentry
sentry-263511705-1gxsz                  0/3       ContainerCreating   0          2d
sentry-3304526142-n7d2p                 3/3       Running             1          2d
```

**What you expected to happen**:

A deployment with only a pod should be scheduled only one time at once :)

**How to reproduce it** (as minimally and precisely as possible):

If pod `sentry-263511705-1gxsz` is deleted, another is scheduled, for getting the things to a « normal » order I should delete the deployment entirely, and re-create it.

This issue affect all my pods with a persistent volume attached.

**Anything else do we need to know**:

I'm reachable on slack if needed (@rvrignaud (fitzdsl) or @sbadia)

**Comment by mikekap** [comment]
The `StrategyType: RollingUpdate` can cause more than one pod for this deployment when doing updates. You likely want to change that to `Replace`, or at least change `maxSurge` to 0 - that's what's causing the extra pod. For reference: `Deployment` objects actually create `ReplicaSet` objects which are what create the `Pod` objects - deleting the `ReplicaSet` rather than the `Pod` may do what you want here.

Separately, I'm curious why kubectl isn't showing `OldReplicaSets` for that deployment. That might be the real issue here.

**Comment by sbadia** [comment]
Thanks @mikekap you're right for the strategytype!
Indeed for the `OldReplicatSets`… I leave this issue open ?
