### ISSUE TITLE
[kubeadm] Master role missing after kubelet restarted

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#39581]
Installed by kubeadm, after a master role kubelet is restarted, it's master role (kubeadm.alpha.kubernetes.io/role=master) will lost:

Got
```
Role:			
Labels:			alpha.kubernetes.io/fluentd-ds-ready=true
			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/os=linux
			kubernetes.io/hostname=e2e-ubuntu
```
Expected
```
Role:			master
Labels:			alpha.kubernetes.io/fluentd-ds-ready=true
			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/os=linux
			kubeadm.alpha.kubernetes.io/role=master
			kubernetes.io/hostname=e2e-ubuntu
```

It is due to kubeadm only set master role to node during first deploy.
I will try to work out a patch to fix this.

**Comment by resouer** [comment]
Note: a nice fix would be adding a node label to kubelet, but it relies on: https://github.com/kubernetes/kubernetes/pull/39362

**Comment by luxas** [comment]
Closing this as it's outdated
