### ISSUE TITLE
"go run hack/e2e.go -v --up" isn't spawning etcd3 by default

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#39589]
We should have made etcd3 as the default backend for k8s cluster.
However, I followed the guide on [e2e-tests.md](https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md) and it's still spawning up etcd2 backend. We should change that.

Another question is that I didn't see any option to switch to etcd3. How to do that?

**Comment by hongchaodeng** [comment]
cc @xiang90 @wojtek-t @timothysc

**Comment by hongchaodeng** [comment]
So is ./cluster/kube-up.sh

**Comment by chrislovecnm** [comment]
@hongchaodeng since e2e still runs tests on 1.3 and 1.4, which cannot use etcd3, what do you propose?

**Comment by hongchaodeng** [comment]
@chrislovecnm 
What's the option to enable that in spawning up a cluster? The docs doesn't show:
https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md

**Comment by wojtek-t** [comment]
It seems that I messed one thing up and we are still using etcd2:
https://github.com/kubernetes/kubernetes/blob/master/cluster/common.sh#L722

So I think that currently in our tests we are using:
3.0.14 etcd, but in v2 mode.

I will send out a PR to fix it.

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/40020 should hopefully fix it

**Comment by hongchaodeng** [comment]
Thanks!!! @wojtek-t

**Comment by wojtek-t** [comment]
@hongchaodeng - did you verify that it now works correctly? To be honest I didn't have time to do it yet.

**Comment by hongchaodeng** [comment]
@wojtek-t 
Right. I tried with "./cluster/kube-up.sh", which I used to bootstrap e2e cluster.
Let me try later "go run hack/e2e.go -v --up".

**Comment by hongchaodeng** [comment]
Verified that "go run hack/e2e.go -v --up" also spawns etcd3 backed cluster!
Thanks again! @wojtek-t
