### ISSUE TITLE
[CAfile]Failed to fetch apt pakcages

### ISSUE THREAD

**Issue by DjangoPeng** [kubernetes/kubernetes#39592]
**OS: ubuntu 14.04**
Net: behind proxy.

I'm trying to install Kubernetes 1.5.1 in my ubuntu 14.04 Linux Server, but failed!
I followed the `Install with kubeadm` tutorial, and added apt-key successfully.
But when I run `apt-get update` as root, I faced an error as below:
```
W: Failed to fetch http://apt.kubernetes.io/dists/kubernetes-xenial/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

W: Failed to fetch http://apt.kubernetes.io/dists/kubernetes-xenial/main/binary-i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

E: Some index files failed to download. They have been ignored, or old ones used instead.
```
I checked my apt.conf and source, all is well.  Does anyone has the same issue and solution?

**I think the apt-key of kubernetes may be expired.**

**Comment by RemonSinnema** [comment]
Workaround: add the following to `/etc/apt/apt.conf`:

    Acquire::https::packages.cloud.google.com::Verify-Peer "false";

**Comment by eelyaj** [comment]
I got this issue too. the workaround works, thanks.

**Comment by luxas** [comment]
This seems more like a proxy issue in your env than a Kubernetes issue.
I'm hesitant against turning of CA verification though...

**Comment by DjangoPeng** [comment]
@RemonSinnema @luxas You're right, I fixed it after setting the right proxy. Thanks!

**Comment by DjangoPeng** [comment]
For Centos users: add `sslverify=0` into the kubernetes.repo to avoid the verify issue.

**Comment by SaurabhQA** [comment]
@RemonSinnema  Thanks! The workaround works
