### ISSUE TITLE
Support "kubectl create role" sub-command

### ISSUE THREAD

**Issue by xingzhou** [kubernetes/kubernetes#39596]
Happened to see there is no sub-command like "kubectl create role" for kubectl to create a role object easily from the CLI while testing RBAC.

I'd like to work on providing a patch for the sub-command of role and cluster-role.

Welcome your comments and let me know if anything is wrong.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc @kubernetes/sig-auth-misc

**Comment by deads2k** [comment]
I like the the idea, but I suspect it will be harder that expected.  I would probably start by trying to specify resource group tuples as we do for regular commands.  So `kubectl create role foo --verb=get --resource=rc. --resource=rs.extensions`.

@fabianofranz for other UI suggestions.

**Comment by xingzhou** [comment]
Thanks @deads2k for the suggestion. One other thing I can see right now is "AttributeRestrictions" attribute in Role object, as it can be a complex object. Do you think we need to support this field as an option for `kubectl create role`? I'm thinking this may increase the complexity fo user to use this command.

**Comment by deads2k** [comment]
> Thanks @deads2k for the suggestion. One other thing I can see right now is "AttributeRestrictions" attribute in Role object, as it can be a complex object. Do you think we need to support this field as an option for kubectl create role? I'm thinking this may increase the complexity fo user to use this command.

AttributeRestriction will be removed before beta.  See https://github.com/kubernetes/kubernetes/pull/39625

**Comment by fabianofranz** [comment]
The proposed UI sounds good. Notice you can also have multiple verbs, and resources can also be provided in `type/name` format.

**Comment by xingzhou** [comment]
yes, @fabianofranz, but since some sub-resource like `pod logs`, is defined as `pod/logs`, I'd like to let user input apiGroups, resources and verbs respectively, like:
`kubectl create role --api-group=xxx --resource=xxx --verb=xxx`

Besides, one single Role object can hold multiple Rules(each rule includes a set of verbs, apiGroups and resources), but from the command line aspect, it is hard for user to define multiple Rules, shall we only allow user to create only one Rule in a Role object when using this sub-command?

**Comment by deads2k** [comment]
> Shall we only allow user to create only one Rule in a Role object when using this sub-command?

I'm probably ok with that restriction, but some kind of `kubectl set` command which adds a rule is probably in order.

**Comment by xilabao** [comment]
`kubectl set role/clusterrole` sounds good. I can help to finish it if the work has not started. @deads2k @xingzhou

**Comment by xingzhou** [comment]
I'm not working on the `set` command right now and I've created a new ticket to track the implementation of `kubectl set role`.

**Comment by deads2k** [comment]
> kubectl set role/clusterrole sounds good. I can help to finish it if the work has not started. @deads2k @xingzhou

I'm not working on it either.

**Comment by mattnworb** [comment]
Seems like this was done in #39852 and #41538 and can be closed now, right?

**Comment by xingzhou** [comment]
yeap, closing it.
