### ISSUE TITLE
Federation API server is failing to process requests.

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#39594]
It looks like an `etcd3` compatibility issue from the initial debugging, but I haven't had a chance to do a thorough analysis.

Federation control plane creates an `etcd` container with an `etcd2` image and recent changes announced here https://groups.google.com/forum/#!topic/kubernetes-dev/WMPK5fyOorE might be the reason for the failures.

Were there any changes to generic API server to make this change happen? 

@nikhiljindal @shashidharatd, could one of you please take a look? 

cc @kubernetes/sig-federation-misc @nikhiljindal @shashidharatd @csbell @timothysc

**Comment by shashidharatd** [comment]
Yes @madhusudancs, the upgrade in etcd is causing the issues.
we need to upgrade etcd image to gcr.io/google_containers/etcd:3.0.14-alpha.1 for federation

**Comment by nikhiljindal** [comment]
Why alpha image?
Dont we have a stable etcd:3.0 image?

**Comment by shashidharatd** [comment]
This is the image used in base kubernetes for etcd. Not sure why it is alpha

**Comment by madhusudancs** [comment]
@nikhiljindal 

> Why alpha image?
> Dont we have a stable etcd:3.0 image?

This is the image we use in Kubernetes clusters. I believe this image's release cycle is tied to Kubernetes release cycle, which is also in alpha. 

Also note, etcd 3.0.14 is stable. I believe this our modified version of the image that ships with necessary migration bits.

@kubernetes/sig-scalability-misc, is this correct?

**Comment by timothysc** [comment]
it's not alpha, that was just a tag applied by folks adding the image to gcrio.  

Yes 3.0.14 is the correct version.
