### ISSUE TITLE
Resource quota calculating incorrect under heavy resource creation

### ISSUE THREAD

**Issue by xinxiaogang** [kubernetes/kubernetes#39599]
**Kubernetes version** (use `kubectl version`):
v1.4.5

**What happened**:
I have a 3rd party resource of my CI which works as an umbrella resource. And there is a controller to spin up Jenkins pod based on this CI 3rd party resource object.
To ensure eventually consistency and tolerance, I have retry logic in my controller to re-create RC for my Jenkins if fail last time.
Further more, I have enabled resource quota in my cluster.

Here is the problem:
The log shows resource quota exceeded but when I `kubectl get rc`, there is only little of them.
```
root@1acec8ef5f58:/go# kubectl get resourcequota object-counts -o yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: 2016-12-22T03:30:05Z
  name: object-counts
  namespace: ciaas-qa
  resourceVersion: "116776836"
  selfLink: /api/v1/namespaces/ciaas-qa/resourcequotas/object-counts
  uid: ee6de881-c7f6-11e6-8568-74dbd1808927
spec:
  hard:
    configmaps: "10"
    replicationcontrollers: "100"
    secrets: "20"
    services: "100"
    services.loadbalancers: "100"
    services.nodeports: "0"
status:
  hard:
    configmaps: "10"
    replicationcontrollers: "100"
    secrets: "20"
    services: "100"
    services.loadbalancers: "100"
    services.nodeports: "0"
  used:
    configmaps: "0"
    replicationcontrollers: "100"
    secrets: "1"
    services: "12"
    services.loadbalancers: "12"
    services.nodeports: "0"
```
```
root@1acec8ef5f58:/go# kubectl get rc | wc -l
14
```

This is really confuse to customer.

I know that the mechanism of resource quota calculating is:
- Admission controller to add resource quota before actual storing the object data
- Resource quota controller to reconcile with actual resource number in etcd

But the resource quota calculation is not realtime which is confuse when customer try to get the actual resource number.

So my question is can we find another solution to calculating the resource quota number, say, after PUT into etcd successfully? Or is there any plan to enhance this?

**Comment by zhouhaibing089** [comment]
Put it simply, when the requests come to `ResourceQuota` admission control, there is no guarantee that the resource would be created successfully eventually(for example, the validation part might fail), and in this case, the resource count will be increased, but actually it is not provisioned at last.

There is a time window to reset the usage in controller manager, so at  this time range, the user will see this unexpected behavior. 

cc @derekwaynecarr what's your idea on this?

**Comment by liggitt** [comment]
I don't think there are immediate plans to change this. @derekwaynecarr can confirm and close

**Comment by derekwaynecarr** [comment]
@zhouhaibing089 - i am aware of this problem, but i have not determined the ideal solution.

i had at one time proposed a model like the following: https://github.com/kubernetes/kubernetes/pull/20113

it split used into used + reserved which i think would reduce confusion, but introduce more writes.  i still think there is a benefit to that model discussed in that proposal, but have not had time to resurrect it.
