### ISSUE TITLE
Ignore "codecgen-pkg-1234.generated.go" for bazel or not

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#39595]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

**Kubernetes version** (use `kubectl version`):
master

**What happened**:

One PR for master after `./hack/update-bazel.sh`.

```
diff --git a/pkg/apis/policy/v1beta1/BUILD b/pkg/apis/policy/v1beta1/BUILD
index a50db72..b3e53dd 100644
--- a/pkg/apis/policy/v1beta1/BUILD
+++ b/pkg/apis/policy/v1beta1/BUILD
@@ -10,6 +10,7 @@ load(
 go_library(
     name = "go_default_library",
     srcs = [
+        "codecgen-pkg-1234.generated.go",
         "doc.go",
         "generated.pb.go",
         "register.go",
```

**What you expected to happen**:
No code change after `./hack/update-all.sh` without new PR.

**How to reproduce it** (as minimally and precisely as possible):
`./hack/update-bazel.sh`

**Comment by k82cn** [comment]
@mikedanese , should I create a PR for it? or update `update-bazel.sh` to ignore `codecgen-pkg-1234.generated.go` ?

**Comment by shiywang** [comment]
@k82cn I checkout a new branch, and run `./hack/update-bazel.sh` after commit some code, but I didn't see a any `codecgen-pkg-1234.generated.go` with `git diff`, does this related to some specific code change ?

**Comment by k82cn** [comment]
@shiywang , seems worked with latest code. Close this issue.

**Comment by mikedanese** [comment]
Looks like you ctrl-c'd in the middle of hack/update-codecgen.sh.
