### ISSUE TITLE
AWS: Changing Service Type / Annotation not applied to ELB

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#39593]
k8s 1.4.7, kops, HA, weave, private networking

I changed the guestbook-go example service in two ways, neither of which were reflected in the ELB.  First I added the `service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0` annotation, and the ELB was not changed (that's not terribly surprising IMO).  But I then tried changing it to type NodePort (it was deleted - good) and then back to LoadBalancer ("nothing happened" - no ELB created, no relevant events other than the controller detecting NodePort -> LoadBalancer).  I am pretty sure we have a test for NodePort -> LoadBalancer, so something is unexpected.

**Comment by blakebarnett** [comment]
We are hitting this frequently also.

**Comment by mijdavis2** [comment]
Seeing this as well in 1.9.7. Annotations aren't even being propagated to services at all - I have to manually enter them in the dashboard even though they are defined in the yaml. Ended up with an internet-facing LB due to this which is incredibly annoying and scary considering the security implications.

**Comment by pawelprazak** [comment]
We are seeing this issue in 1.9.7, is there any work being done to fix it?

**Comment by edify42** [comment]
So recreating (delete followed by apply) is the only way for the k8s controller to pick up the changes to SVC annotations?

Annoying as I want to recreate the ELB but don't want to destroy the service entirely as it's used by the Ingress...

**Comment by maxgio92** [comment]
I think that it's a deliberate behaviour; BTW, it still happens on 1.14.9
