### ISSUE TITLE
`pull-kubernetes-node-e2e` and `pull-kubernetes-node-e2e-cri` failing with `Command failed: Permission denied (publickey)` for 1.5 branch

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#39597]
`pull-kubernetes-node-e2e` and `pull-kubernetes-node-e2e-cri` pull request test suites are consistently failing with `Command failed: Permission denied (publickey)` for the `release-1.5` branch.

Example failures:
```
I0107 15:49:20.515] Failure Finished Test Suite on Host 
I0107 15:49:20.516] unable to create gce instance with running docker daemon for image gci-dev-56-8977-0-0.  instance tmp-node-e2e-658c4c79-gci-dev-56-8977-0-0 not running docker daemon - Command failed: Permission denied (publickey).
```

Example failures:
* https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/pull/39549/pull-kubernetes-node-e2e-cri/
* https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/pull/39549/pull-kubernetes-node-e2e/
* https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/pull/39529/pull-kubernetes-node-e2e-cri/
* https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/pull/39529/pull-kubernetes-node-e2e/

@kubernetes/test-infra-maintainers any idea what's going on here? Need help fixing this ASAP since it is blocking merges of cherrypicks to the 1.5 branch.

**Comment by Random-Liu** [comment]
I think this is because we started to use dockerized node e2e. In dockerized node e2e, we use `-e GCE_USER=jenkins` to run the test as user `jenkins`, so as to avoid the `Command failed: Permission denied (publickey)` error.

However, https://github.com/kubernetes/kubernetes/pull/39074 is not in branch 1.5, so node e2e in 1.5 doesn't understand the `GCE_USER` env.

We should cherry-pick https://github.com/kubernetes/kubernetes/pull/39115 and https://github.com/kubernetes/kubernetes/pull/39074 into 1.5 to fix this.

**Comment by Random-Liu** [comment]
Another option to change test-infra side to not run dockerized node e2e against 1.4 and 1.5, as is proposed [here](simply let node-1.4 and node-1.5 jobs not run in docker)

**Comment by krzyzacy** [comment]
I think it has to be cherry-picked to fix `pull-kubernetes-node-e2e` so we can support multiple go version, like what we did earlier for kubekins.

**Comment by Random-Liu** [comment]
@krzyzacy I see. Will send a cherrypick soon.

**Comment by dchen1107** [comment]
I ran into the same issue with 1.4 branch: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/39563/pull-kubernetes-node-e2e/12090/ The fixes should be cherrypicked to 1.4 branch too.

**Comment by jessfraz** [comment]
ah I can cherry-pick

**Comment by jessfraz** [comment]
opened in https://github.com/kubernetes/kubernetes/pull/39634

**Comment by krzyzacy** [comment]
@jessfraz thanks!

**Comment by Random-Liu** [comment]
@jessfraz For 1.4, some manual change is needed. I'm also trying it https://github.com/kubernetes/kubernetes/pull/39632

**Comment by saad-ali** [comment]
Closed with https://github.com/kubernetes/kubernetes/pull/39630 and https://github.com/kubernetes/kubernetes/pull/39632
