### ISSUE TITLE
Kubectl 1.5.1 much slower to execute requests

### ISSUE THREAD

**Issue by Raffo** [kubernetes/kubernetes#39626]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 

````
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0", GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", BuildDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
````

**Environment**:
- **Cloud provider or hardware configuration**: AWS, GKE
- **OS** (e.g. from /etc/os-release): Container Linux by CoreOS stable (1235.5.0) 
- **Kernel** (e.g. `uname -a`): Linux ip-172-31-12-46.eu-central-1.compute.internal 4.7.3-coreos-r2 #1 SMP Sun Jan 8 00:32:25 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz GenuineIntel GNU/Linux

**What happened**:
Kubectl 1.5.1 is much slower. If I try the following command `kubectl get pods --v=9` I can see: 

````
I0109 18:25:44.695300   40723 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.5.1 (darwin/amd64) kubernetes/82450d0" -H "Authorization: Bearer $TOKEN" https://$MY_CLUSTER/api
I0109 18:25:48.129106   40723 round_trippers.go:318] GET https://$MY_CLUSTER/api 200 OK in 3433 milliseconds
I0109 18:25:48.129180   40723 round_trippers.go:324] Response Headers:
I0109 18:25:48.129194   40723 round_trippers.go:327]     Content-Length: 131
I0109 18:25:48.129206   40723 round_trippers.go:327]     Content-Type: application/json
I0109 18:25:48.129217   40723 round_trippers.go:327]     Date: Mon, 09 Jan 2017 17:25:48 GMT
````

But when running the `curl` command I get: 

````
time curl -k -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.5.1 (darwin/amd64) kubernetes/82450d0" -H "Authorization: Bearer $TOKEN" https://$MY_CLUSTER/api
{"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"10.10.10.0"}]}
curl -k -XGET -H "Accept: application/json, */*" -H  -H    0.03s user 0.01s system 5% cpu 0.825 total
````
which is very fast. 

**How to reproduce it** (as minimally and precisely as possible):
I can reproduce it with all clusters I have in AWS when using 1.5.1 (both on client and serveR). I reproduced the same in GKE too. 

I am obviously available to provide more data if needed.

**Comment by hjacobs** [comment]
I don't have this problem with Kubectl 1.5.1, but multiple colleagues report the same "slowness".

**Comment by philk** [comment]
I'm also seeing this.

kubectl 1.5.2
```
I0117 10:49:39.028965   73942 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json" -H "User-Agent: kubectl-1.5.2/v1.5.2 (darwin/amd64) kubernetes/08e0995" -H "Authorization: Bearer [redact]" https://[redact]/api/v1/nodes
I0117 10:49:47.257350   73942 round_trippers.go:318] GET https://[redact]/api/v1/nodes 200 OK in 8228 milliseconds
I0117 10:49:47.257387   73942 round_trippers.go:324] Response Headers:
I0117 10:49:47.257393   73942 round_trippers.go:327]     Content-Type: application/json
I0117 10:49:47.257397   73942 round_trippers.go:327]     Date: Tue, 17 Jan 2017 18:49:47 GMT
I0117 10:49:47.319431   73942 request.go:904] Response Body: [actual json response]
```

kubectl 1.4.6
```
I0117 10:40:15.644083   68072 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl-1.4.6/v1.4.6 (darwin/amd64) kubernetes/e569a27" -H "Authorization: Bearer [redact]" https://[redact]/api/v1/nodes
I0117 10:40:15.680027   68072 round_trippers.go:318] GET https://[redact]/api/v1/nodes 200 OK in 35 milliseconds
I0117 10:40:15.680053   68072 round_trippers.go:324] Response Headers:
I0117 10:40:15.680061   68072 round_trippers.go:327]     Content-Type: application/json
I0117 10:40:15.680067   68072 round_trippers.go:327]     Date: Tue, 17 Jan 2017 18:40:15 GMT
I0117 10:40:15.775953   68072 request.go:908] Response Body: [actual json response]
```

The only difference I see is a bunch of cache stuff at the beginning of the 1.5.x command. Removing the `~/.kube/cache` causes a similar multi-second hang but on an `/api` call:

```
I0117 10:57:43.300426   76533 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl-1.5.2/v1.5.2 (darwin/amd64) kubernetes/08e0995" -H "Authorization: Bearer [redact]" https://[redact]/api
I0117 10:57:50.640742   76533 round_trippers.go:318] GET https://[redact]/api 200 OK in 7340 milliseconds
I0117 10:57:50.640773   76533 round_trippers.go:324] Response Headers:
I0117 10:57:50.640779   76533 round_trippers.go:327]     Content-Type: application/json
I0117 10:57:50.640783   76533 round_trippers.go:327]     Date: Tue, 17 Jan 2017 18:57:50 GMT
I0117 10:57:50.640787   76533 round_trippers.go:327]     Content-Length: 132
I0117 10:57:50.640871   76533 request.go:904] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"10.0.38.98:443"}]}
```

I tried running kubectl from the hyperkube docker image on the same system (well, the docker VM) and it's normal (<1 second response) so it's probably something OSX related.

I set up an SSH tunnel to the insecure port on an api server and that responded at normal speed. So it feels to me like some bad golang / SSL / OSX interaction.

**Comment by Raffo** [comment]
I confirm that it is OS related (OSX) and somehow happens with SSL connections. I tried with insecure option and it is very fast, but clearly this is not an option. I will try to investigate a bit further to understand what is happening now behind the scenes. It might also be related to the Go version used, as 1.5 was compiled with Go 1.7.

**Comment by spzala** [comment]
@Raffo hi, wondering, any update on this? Thanks!

**Comment by Raffo** [comment]
I compiled my own kubectl from sources since my initial report and achieved much better performances. Since some release, I did not notice this problem again. I will close the issue now, please feel free to reopen it in case it is needed.

**Comment by spzala** [comment]
@Raffo very nice. Thanks for the quick reply and closing issue!

**Comment by szhmery** [comment]
hi everybody,
I met this problem too, but my kubectl version is 1.7.4. I have two servers to run "kubectl get pods". They have some kubectl version, one  return 18ms, but another is more than 1000ms.
Does somebody know what's the problem? Thanks!

I0302 02:51:50.711482     544 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json" -H "User-Agent: kubectl/v1.7.4 (linux/amd64) kubernetes/793658f" https://*****:6443/api/v1/namespaces/default/pods
I0302 02:51:50.729110     544 round_trippers.go:405] GET https://***:6443/api/v1/namespaces/default/pods 200 OK in 17 milliseconds
I0302 02:51:50.729137     544 round_trippers.go:411] Response Headers:
I0302 02:51:50.729142     544 round_trippers.go:414]     Content-Type: application/json
I0302 02:51:50.729154     544 round_trippers.go:414]     Date: Fri, 02 Mar 2018 02:51:50 GMT


The bad server:
I0301 10:45:24.061863   26651 round_trippers.go:386] curl -k -v -XGET  -H "User-Agent: kubectl/v1.7.4 (linux/amd64) kubernetes/793658f" -H "Accept: application/json" https://1*****:6443/api/v1/namespaces/default/pods
I0301 10:45:25.464826   26651 round_trippers.go:405] GET https://1*******:6443/api/v1/namespaces/default/pods 200 OK in 1402 milliseconds
I0301 10:45:25.464848   26651 round_trippers.go:411] Response Headers:
I0301 10:45:25.464854   26651 round_trippers.go:414]     Content-Type: application/json
I0301 10:45:25.464860   26651 round_trippers.go:414]     Date: Thu, 01 Mar 2018 18:45:25 GMT

**Comment by suman-ganta** [comment]
I'm running into this problem recently. the server response via curl is just fine. But kubectl takes a lot of time to respond. Anyway to troubleshoot?

kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-2+b35c8f02b79855", GitCommit:"b35c8f02b79855c762b0da3afdc643ba1aef1ca9", GitTreeState:"clean", BuildDate:"2018-06-01T21:03:42Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by Raffo** [comment]
@suman-ganta did you try compiling your own?

**Comment by suman-ganta** [comment]
No, I figured this is caused by the following call - Not sure why it is timing out -
```bash
curl -k https://mymaster:6443/apis/custom.metrics.k8s.io/v1beta1?timeout=32s -H "Authorization: Bearer <token>"

< HTTP/1.1 503 Service Unavailable
< Audit-Id: 4a930c6b-7898-40ca-bf6e-f5cf9e43ffe1
< Date: Wed, 11 Jul 2018 18:33:38 GMT
< Content-Length: 132
< Content-Type: text/plain; charset=utf-8
<
Error: 'net/http: TLS handshake timeout'
```
