### ISSUE TITLE
AWS: Should have a coherent caching model

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#39647]
Nicely summarized by @jsravn here https://github.com/kubernetes/kubernetes/issues/39526#issuecomment-271258500

> I really don't trust any optimisations in the AWS code anymore, as long as calls to AWS remain synchronously triggered from non-AWS code. Regressions keep happening like this one, making AWS usage of k8s unstable. I think the AWS code should move to updating its state of the VPC periodically and asynchronously, then respond to calls with cached data. Then we can strictly control how often AWS calls are made and defend against these sort of problems.

There are a lot of challenges with getting there, but I think we can head in that direction.  It will also benefit all cloudproviders.  I am sure that AWS rate limits are more of a problem than on other cloud providers, but I also think we also see a lot of real-world extreme usage so AWS is also the canary in the coal mine.

I have been tinkering with this for a while.  For example, I was able to implement a cache that would safely cache instanceid -> PrivateDnsName (aka default NodeName).  The strategy was to refresh all instances whenever we saw an "unknown instanceid", thus taking advantage of the fact that DescribeInstances is only one call whether it fetches 1 or 100 instances (ignoring paging).  This also gives us eviction of old instances for free.  But of course this only works because this information is immutable.

The inverse cache likely isn't safe (NodeName -> InstanceId) - and is the much more common call - because in theory we could reuse a NodeName.  But I think this is actually a problem with using NodeName as an identifier in general.  We probably should be using node uuid or similar.

@patrickmcclory also pointed out that cloudtrail now supports notifications, which could allow an edge-triggered model (but I don't have the experience to know if this is reliable / sufficient): http://docs.aws.amazon.com/awscloudtrail/latest/userguide/configure-cloudtrail-to-send-notifications.html

Another thing: we could watch the k8s Nodes, so that we know when a node has launched / is terminated.  In fact, the nodecontroller now does this, and does call into the cloudprovider.  We could use this fact, though I would rather formalize the dependency - either by passing in the node client into the cloudprovider, or by having the nodecontroller post events.

cc @matchstick @saad-ali @chrislovecnm @jsravn @jsafrane @jingxu97

**Comment by gnufied** [comment]
cc @kubernetes/sig-aws-misc @kubernetes/sig-storage-misc

**Comment by hjacobs** [comment]
@justinsb regarding the "edge-triggered model": from my experience CloudTrail has some delay, so I would not go that route.

**Comment by jsafrane** [comment]
> I would rather formalize the dependency - either by passing in the node client into the cloudprovider, or by having the nodecontroller post events

IMO you need to watch for nodes in AWS cloud provider using a kube client, as the cloud provider is initialized on API server (e.g. to fill zone/region labels to PVs) , controller manager and all kubelets. You can use events from the node controller just in controller manager daemon.

**Comment by chrislovecnm** [comment]
We need to possibly do a spike assessing the patterns mentioned here as well:

https://aws.amazon.com/blogs/compute/monitor-cluster-state-with-amazon-ecs-event-stream/

**Comment by chrislovecnm** [comment]
Specifically, we need to determine if there is value to tie AWS cloud provider, and API calls, into the Cloudwatch Event stream.  From that stream, we can pickup events such as EBS mounts and unmounts.  The main design question what is the latency and tolerance around this event service.

**Comment by chrislovecnm** [comment]
One answer that I have received in regards to that question:

> Usually fast, not always so.  I wouldn't rely on it for anything requiring anything beyond eventually available.
