### ISSUE TITLE
busted DRIVERS link on minikube doc

### ISSUE THREAD

**Issue by jmhodges** [kubernetes/kubernetes#39645]
In http://kubernetes.io/docs/getting-started-guides/minikube/#driver-plugins, the link to "DRIVERS" is busted. It links to http://kubernetes.io/docs/getting-started-guides/minikube/DRIVERS.md which redirects to http://kubernetes.io/docs/getting-started-guides/minikube/DRIVERS/ and then 404s.

**Comment by nebril** [comment]
it seems like `DRIVERS.md` wasn't added in this commit: https://github.com/kubernetes/kubernetes.github.io/commit/52b6538acc406dc6b5c54b6b89d0b82c5f25b855

@r2d4 I have no idea what should be in this file, can you help?

**Comment by r2d4** [comment]
This is fixed in the above PR

> The getting started guide was lifted from minikube's README.md on
github and included relative links. They have been updated to point to
the absolute path to the latest release.

**Comment by jmhodges** [comment]
I don't think I'm the right person to figure out what sig this is. 

@r2d4 maybe you know?

**Comment by r2d4** [comment]
This should be fixed now
