### ISSUE TITLE
Federated plane started via kubefed throws No Route to host

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#39642]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

master or 1.5.x 

**Environment**:
- **Cloud provider or hardware configuration**: gce
- **OS** (e.g. from /etc/os-release): 
- **Kernel** (e.g. `uname -a`):
- **Install tools**: kube-up.sh
- **Others**:

**What happened**:

Kubernetes federation plane started via kubefed creates a load balancer between 3 nodes (so basically target pool consists of 3 instances) but the federation-apiserver has only 1 replica running on a particular node and hence every other API interaction with federation plane results in - "104.xxxxxxx. no route to host" error.

**What you expected to happen**:

I would expect it to work.

**How to reproduce it** (as minimally and precisely as possible):

Create a federation plane using kube-up.sh and `kubefed` on GCE.

**Comment by gnufied** [comment]
cc @kubernetes/sig-federation-misc

**Comment by madhusudancs** [comment]
@gnufied a few questions:

1. Is this the only load balanced service for which you are seeing this behavior? 
2. What about in-cluster federation API access, do you see similar behavior?
3. What do you see in your federation controller manager logs?

cc @kubernetes/sig-network-misc

**Comment by gnufied** [comment]
@madhusudancs this is just a test account. I don't have any other load balanced service running in this account.

2 and 3 I need to verify. But I still don't understand why the forwarding-route consists of a target pool of 3 nodes whereas federation-apiserver is running on only one instance. It seems like a oversight?

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by madhusudancs** [comment]
@gnufied could you try running another load balanced service in this cluster?

> 2 and 3 I need to verify. But I still don't understand why the forwarding-route consists of a target pool of 3 nodes whereas federation-apiserver is running on only one instance. It seems like a oversight?

This is how Kubernetes networking works on GCP. The loadbalanced service opens a NodePort on all the nodes in your cluster. GCP Network loadbalancer is then configured to send the traffic to that NodePort on any of the nodes in your cluster. So the traffic can reach any node. Once the traffic hits the node, the kube-proxy on that node has the iptables programmed to route your traffic to the right node where the service backend (pod) is actually running. So even if you have a single pod, GCP Network loadbalancer is configured to send the traffic to all the nodes. That's why you see 3 nodes.

**Comment by thockin** [comment]
@madhusudancs is this an actionable thing for 1.7?

**Comment by madhusudancs** [comment]
@thockin no. We haven't been able to reproduce.

@gnufied Do you still see this problem? If not, can we close this?

**Comment by gnufied** [comment]
@madhusudancs lets close this issue for now. I will reopen this, when I retry federation pieces in awhile.

What sounds like is - the kube-proxy was not routing the request to correct node . I don't know why that would happen. I started this environment via "./cluster/kube-up.sh` .

**Comment by madhusudancs** [comment]
@gnufied I see. Not entirely sure how that would happen. Closing this for now. Please feel free to re-open it if you run into this issue again.
