### ISSUE TITLE
Big route53 accounts may cause dnsprovider to hit rate limits

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#39674]
The route53 dnsprovider doesn't implement filtering.  On Route53, there is a 5 request per second rate limit (per AWS _account_): http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html

With pagination, it is very likely that we will issue more than 5 requests per second just listing resource records for a big zone.

We need to implement filtering.

**Comment by chrislovecnm** [comment]
@justinsb can you provide more details on the code base this is coming from?

**Comment by chrislovecnm** [comment]
cc: @kubernetes/sig-aws-misc

**Comment by justinsb** [comment]
@chrislovecnm  https://github.com/kubernetes/kubernetes/tree/master/federation/pkg/dnsprovider/providers/aws/route53

**Comment by chrislovecnm** [comment]
FYI

Top three API calls that we are getting.  I am uncertain if we are using the PRs on this ticket.

1. ListHostedZonesByName
1. ChangeResourceRecordSet
1. ListResourceRecordSets

**Comment by quinton-hoole** [comment]
I think we need to fix this before GA of federation. Prioritizing accordingly.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#204.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
