### ISSUE TITLE
GCE internal load balancer

### ISSUE THREAD

**Issue by munnerz** [kubernetes/kubernetes#39676]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
* internal loadbalancer
* gce loadbalancer
* loadbalancer annotation internal 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

**Kubernetes version** (use `kubectl version`):
1.5.1

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

Google have added support for internal loadbalancers on GCP. I've managed to find information on AWS and using internal ELBs (via `service.beta.kubernetes.io/aws-load-balancer-internal`), but from issues and looking at the GCE cloud provider it seems there's currently no support for internal google load balancers.

Have I just missed something? I'd be happy to contribute towards this feature if nobody else already is.

**Comment by freehan** [comment]
ref: https://github.com/kubernetes/kubernetes/issues/23791

**Comment by kuroneko25** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/33483?

**Comment by munnerz** [comment]
Yep looks to be. Closing in favour of #33483
