### ISSUE TITLE
Create `kubectl lint` command

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#39699]
There are a number of best practices for creating config files, but they are not enforced by the API.  It would be helpful to have a `kubectl lint` command to check for basic best practices and give warnings

Things to check for
- [ ] Deployments specify max old replicas
- [ ] Deployments specify both selectors and PT.labels (not just the labels)
- [ ] Service ports always have names
- [ ] Configs comment out / remove values for objects managed by other actors (e.g. replicas if managed by HPA) - *do we want to do this*

**Comment by krmayankk** [comment]
may be a vim plugin that catches errors in json or yaml will also help. I find it very hard when creating new configs and have nothing to copy from

**Comment by kargakis** [comment]
> may be a vim plugin that catches errors in json or yaml will also help. I find it very hard when creating new configs and have nothing to copy from

A vim plugin will work only for people who use vim.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by pwittrock** [comment]
@viglesiasce

**Comment by viglesiasce** [comment]
I have started to work on a prototype of this but will be keeping it out of tree for now. Will post back with the repo after I do a bit more cleanup.

**Comment by viglesiasce** [comment]
@jessfraz happy to sync with you to show you where my thinking is leading me ATM.

**Comment by pwittrock** [comment]
@krmayankk I am thinking of another solution for initializing configs.  Something like:

```sh
kubectl create deployment mydeployment --replicas 2 --image nginx --dry-run > mydeployment.yaml
```

**Comment by jessfraz** [comment]
neat @viglesiasce!

**Comment by viglesiasce** [comment]
Okay folks here is a cut at what I was thinking:
https://github.com/viglesiasce/kube-lint

Its mostly oriented towards 2 use cases:

1. Gating a CI/CD pipeline
2. Auditing against running resources

The code is probably not the best since its only my 2nd or 3rd Go project but I'd love some feedback.

**Comment by AdoHe** [comment]
@viglesiasce thanks very much, I would help review this :)

**Comment by kargakis** [comment]
Requirement: `kubectl lint` or whatever it ends up being called should not require a running cluster to work: https://github.com/kubernetes/kubernetes/issues/42601

**Comment by pwittrock** [comment]
@apelisse Vic has started some work on this, but it isn't integrated with kubectl.  This would be a good project to get started on when you are ready.

**Comment by gtcdevop** [comment]
That's a great proposal, it will help developers to avoid some commons mistakes

**Comment by php-coder** [comment]
There are 2 useful projects from @garethr that could be useful:
- https://github.com/garethr/kubeval validates against schema
- https://github.com/garethr/kubetest allows to write custom checks

**Comment by reefbarman** [comment]
/reopen

seeing as a google doesn't give any real options to validating resource yamls in a CI pipeline, I still think this is a feature that is very much needed! We generate the kubernetes yaml files via templating and having someway to test they are generated correctly without having to test them against a cluster will be ideal

**Comment by apelisse** [comment]
> having someway to test they are generated correctly without having to test them against a cluster will be ideal

@reefbarman What's wrong with testing against the actual cluster? is it because you don't want to have a running cluster, or is it because you don't want to have to apply to the cluster (you can use `apply --server-dry-run` when this becomes beta in 1.13)

**Comment by reefbarman** [comment]
Well the main reason is the only cluster we have is minikube running on Dev
machines, but we want to test our yaml files in a ci pipeline which can’t
run minikube

**Comment by garethr** [comment]
@reefbarman mentioned above as well but I think kubeval does what you want. https://github.com/garethr/kubeval.

Here an example of it being used in a CI pipeline (Travis in this case) https://github.com/garethr/helm-travis-testing-example. There is also a handy integration with GitHub in https://github.com/urcomputeringpal/kubevalidator
