### ISSUE TITLE
BUG REPORT: FakeDockerClient will caused memory leak

### ISSUE THREAD

**Issue by fzu-huang** [kubernetes/kubernetes#39717]
When I try to use kubemark to do some perf-tests.I found that some kubemark(hollow-kubelet) will be OOM. Then I kept one kubemark running which I added pprof. 

```
root@k8s-node-perf3-15:/home/log/kubelet98# go tool pprof http://localhost:6060/debug/pprof/heap
Fetching profile from http://localhost:6060/debug/pprof/heap
Saved profile in /root/pprof/pprof.localhost:6060.inuse_objects.inuse_space.006.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) top10
8066.61kB of 8066.61kB total (  100%)
Dropped 392 nodes (cum <= 40.33kB)
Showing top 10 nodes out of 106 (cum >= 512.04kB)
      flat  flat%   sum%        cum   cum%
 2072.09kB 25.69% 25.69%  2072.09kB 25.69%  k8s.io/kubernetes/vendor/github.com/beorn7/perks/quantile.NewTargeted
 1184.27kB 14.68% 40.37%  1184.27kB 14.68%  bytes.makeSlice
 1066.16kB 13.22% 53.59%  1066.16kB 13.22%  k8s.io/kubernetes/pkg/kubelet/dockertools.(*FakeDockerClient).ListContainers
  650.62kB  8.07% 61.65%   650.62kB  8.07%  k8s.io/kubernetes/vendor/github.com/golang/glog.(*syncBuffer).rotateFile
  524.09kB  6.50% 68.15%   524.09kB  6.50%  k8s.io/kubernetes/pkg/runtime.(*Scheme).AddKnownTypes
  516.01kB  6.40% 74.54%   516.01kB  6.40%  k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.newDefaultRegistry
     515kB  6.38% 80.93%      515kB  6.38%  reflect.Value.call
     514kB  6.37% 87.30%  2586.09kB 32.06%  k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.newSummary
  512.31kB  6.35% 93.65%   512.31kB  6.35%  net/http.(*Transport).tryPutIdleConn
  512.04kB  6.35%   100%   512.04kB  6.35%  net/http.(*persistConn).roundTrip
```

We found that `(*FakeDockerClient).ListContainers` use 1066.16kB and the number of `flat` in it is inscreasing. I add some log in this function:

```
var calltime = 0
// ListContainers is a test-spy implementation of DockerInterface.ListContainers.
// It adds an entry "list" to the internal method call record.
func (f *FakeDockerClient) ListContainers(options dockertypes.ContainerListOptions) ([]dockertypes.Container, error) {
	f.Lock()
	defer f.Unlock()
	f.called = append(f.called, calledDetail{name: "list"})
	err := f.popError("list")
	containerList := append([]dockertypes.Container{}, f.RunningContainerList...)
	if options.All {
		// Although the container is not sorted, but the container with the same name should be in order,
		// that is enough for us now.
		// TODO(random-liu): Is a fully sorted array needed?
		containerList = append(containerList, f.ExitedContainerList...)
	}
	calltime++
	glog.Warningf("[HY] f.called: len: %d, size: %d ; cont len: %d, size: %d ; calltime: %d", len(f.called), reflect.TypeOf(f.called).Size(), len(containerList), reflect.TypeOf(containerList).Size(), calltime)
	return containerList, err
}
```
and found that log:
```
2017-01-11 14:27:32.558310 W fake_docker_client.go:273] [HY] f.called: len: 20486, size: 24 ; cont len: 0, size: 24 ; calltime: 19544
2017-01-11 14:27:33.314934 W fake_docker_client.go:273] [HY] f.called: len: 20487, size: 24 ; cont len: 0, size: 24 ; calltime: 19545
2017-01-11 14:27:34.315221 W fake_docker_client.go:273] [HY] f.called: len: 20488, size: 24 ; cont len: 0, size: 24 ; calltime: 19546
```
We saw that the array  `f.called`  won't be released. It is used to record operation of fakedockerclient and only be check in unit test.

I think it be removed or periodically cleaned.

**Comment by Random-Liu** [comment]
Hm, this IS a problem...
Actually, the FakeDockerClient is only for unit test initially. Periodically clean up or something seems to be an overkill to me.

Maybe we should just add an option to disable all call trace, because kubemark never uses it...

**Comment by fzu-huang** [comment]
@Random-Liu   BTW, What about Prometheus?  It also cost a lot of memory.I think there should be a option to disable it,too.

**Comment by yujuhong** [comment]
> Actually, the FakeDockerClient is only for unit test initially. Periodically clean up or something seems to be an overkill to me.

Agreed. `FakeDockerClient` is not designed to be a long-lived object...

> 
> Maybe we should just add an option to disable all call trace in FakeDockerClient, because kubemark never uses it...

Sounds good to me. kubemark should eventually move away from the docker abstraction and use a CRI mock.

**Comment by Random-Liu** [comment]
> kubemark should eventually move away from the docker abstraction and use a CRI mock.

Sounds good to me.

**Comment by gmarek** [comment]
@shyamjvs - is this something that you may be interested in looking into?

**Comment by shyamjvs** [comment]
Sure. I'll look into it.

**Comment by shyamjvs** [comment]
@fzu-huang Thanks for pointing this out.
@gmarek @Random-Liu The only place we currently use a `FakeDockerClient` is in kubemark. So would you suggest just removing this call logging totally (we can add it in the future when someone actually needs it) or make it optional through a bool argument to all constructors for the client?

**Comment by shyamjvs** [comment]
@yujuhong Kubemark (which seems to be the only user of FakeDockerClient on doing a grep in the repo) doesn't use `f.called` array. And the same is also true with other arrays like Created, Started, Stopped, Removed. The whole point of having them was to be able to access history, and if we don't want them, we can just remove the whole history storing logic or just have it as optional. What do you suggest?

```type FakeDockerClient struct {
	sync.Mutex
	Clock                clock.Clock
	RunningContainerList []dockertypes.Container
	ExitedContainerList  []dockertypes.Container
	ContainerMap         map[string]*dockertypes.ContainerJSON
	Image                *dockertypes.ImageInspect
	Images               []dockertypes.Image
	Errors               map[string]error
	called               []calledDetail
	pulled               []string

	// Created, Stopped and Removed all container docker ID
	Created         []string
	Started         []string
	Stopped         []string
	Removed         []string
	VersionInfo     dockertypes.Version
	Information     dockertypes.Info
	ExecInspect     *dockertypes.ContainerExecInspect
	execCmd         []string
	EnableSleep     bool
	ImageHistoryMap map[string][]dockertypes.ImageHistory
}```

**Comment by yujuhong** [comment]
@shyamjvs, have a single option to disable all of them sounds good to me. Since most unit tests do require the history to verify the call, we can enable this option by default, and let kubemark explicitly disable it.

**Comment by Random-Liu** [comment]
@shyamjvs Thanks for picking this up!

**Comment by fzu-huang** [comment]
What about Prometheus? It also used a lot of memory.I think there should be a option to disable it.
