### ISSUE TITLE
Reject updates to addons in kube-system

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#39712]
It is too easy to point this at your foot and pull the trigger. Maybe we can add an admission controller or webhook to reject the update? or perhaps an RBAC webhook to only allow the addon-manager username through?

http://kubernetes.io/docs/admin/admission-controllers/#how-do-i-turn-on-an-admission-control-plug-in, http://kubernetes.io/docs/admin/authorization/, https://github.com/kubernetes/kubernetes/issues/34348

**Comment by liggitt** [comment]
I don't anticipate a hard coded kube-system authorizer. I think the general solution is to run with authorization on and do day to day tasks in namespaces other than kube-system.

**Comment by bprashanth** [comment]
Updates to kube-system are effectively useless, since it's managed by the system, they're always (or should always be) overwritten. Why allow them at all?

**Comment by liggitt** [comment]
> Why allow them at all?

the system manages them via the API, which requires allowing updates via the API

**Comment by bprashanth** [comment]
Oh of course, that's why I suggested rejecting only user updates (maybe via RBAC)

**Comment by liggitt** [comment]
I think that's largely accomplished with the default RBAC policy.
