### ISSUE TITLE
kube-apiserver is not working with etcd2 when enable with client-cert-auth

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/kubernetes#39710]
I did a test to enable etcd client-cert-auth, but then apiserver can not come up, totally. the version I tested is nearly master HEAD branch.

```console
$ etcd --version
etcdctl version 2.2.5
$ etcd --advertise-client-urls=https://master-9419.private.domain.com:2379 
    --listen-client-urls=https://master-9419.private.domain.com:2379 
    --ca-file=/etc/tessdev/pki/ca.crt 
    --cert-file=/etc/tessdev/pki/etcd.crt --key-file=/etc/tessdev/pki/etcd.key
$ /usr/local/bin/kube-apiserver --etcd-servers=https://master-9419.private.domain.com:2379 
    --etcd-cafile=/etc/tessdev/pki/ca.crt 
    --etcd-certfile=/etc/tessdev/pki/kube-apiserver.crt 
    --etcd-keyfile=/etc/tessdev/pki/kube-apiserver.key ..
```

The error message from kube-apiserver:

```
E0111 03:00:53.829193   29597 status.go:62] apiserver received an error that is not an metav1.Status: rpc error: code = 13 desc = transport is closing
…
logging error output: "k8s\x00\n\f\n\x02v1\x12\x06Status\x12F\n\x04\n\x00\x12\x00\x12\aFailure\x1a0rpc error: code = 13 desc = transport is closing\"\x000\xf4\x03\x1a\x00\"\x00"
```

I did a search on etcd issues list, and found this: https://github.com/coreos/etcd/issues/5429, a quote on the comment:

> It's worth clarifying for anyone else that hits this, that you might get this error if you are using a V3 client to connect to a V2-only server.

So it looks like the kube-apiserver has been upgraded to use a v3 etcd client, and in the case that the etcd is serving a v2-only protocol, such error occurs. It should be better to:

1.  it can do a version check, and fallback to use v2 client.
2.  and if that's not reasonable, at least we should print a better message to tell this incompatibility.

If etcd2 has been officially deprecated, I'll close this issue.

cc @xiang90

**Comment by armstrongli** [comment]
please check the option `--storage-backend` in apiserver to make sure the default one is `etcd2` if the etcd cluster is on v2 one.

In the earlier version of kubernetes, `etcd2` is default value. It could be `etcd3` by default

**Comment by chenchun** [comment]
Thanks, setting `--storage-backend=etcd2` works.

**Comment by dolobanko** [comment]
Spent 2 days on this. Thanks.

**Comment by kbmetz** [comment]
Setting --storage-backend=etcd2 worked for me too. Thanks
