### ISSUE TITLE
User "system:anonymous" cannot proxy services in the namespace "default".

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#39722]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): User "system:anonymous" cannot proxy services in the namespace "default".

**Kubernetes version** (use `kubectl version`):
```
~kubectl version --short
Client Version: v1.6.0-alpha.0.2996+add3a08a6d3648
Server Version: v1.6.0-alpha.0.2996+add3a08a6d3648
```

**Environment**:
- **Cloud provider or hardware configuration**: GCE

**What happened**:
Unable to access services via the proxy endpoint.

**What you expected to happen**:
The service to be accessible via /api/v1/proxy/...

**How to reproduce it** (as minimally and precisely as possible):
- Check out sources from HEAD
- make quick-release
- cluster/kube-up.sh

Cannot access any service via the proxy (see kubectl cluster-info for some examples), for example:
```
~ curl -k https://<server>/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
User "system:anonymous" cannot proxy services in the namespace "kube-system".
```
**Anything else do we need to know**:
This is a regression from 1.5.1.

/cc @kubernetes/sig-auth-misc @kubernetes/sig-network-misc

**Comment by deads2k** [comment]
I think `kube-up.sh` now runs RBAC by default.  That means that by default, your cluster won't allow full, unprivileged access any more.  There are some doc pulls in progress to ease the transition here https://github.com/kubernetes/kubernetes.github.io/pull/2169 and here https://github.com/kubernetes/kubernetes.github.io/pull/1858.

Using the insecure port locally, you should be able to add bindings with the instructions described here https://github.com/kubernetes/kubernetes.github.io/pull/2169/files#diff-48e69c0b942ef9dcc93b90046d09f9e6R488

**Comment by cjcullen** [comment]
I think we need to dig deeper into our 1.5->1.6 permissions story.

I agree that the vast permissions granted by ABAC are terrible and we should do whatever we can to push 1.6 users to set up sane permissions w/ RBAC.

But...
We shouldn't break existing functionality on an upgrade to 1.6 (even if that functionality is something awful like "I need some random service account to be able to exec into system pods"). This could either be a bootstrap one-shot on upgrade to mimic ABAC permissions w/ RBAC bindings (hard, not always possible) or a flag that allows ABAC to stay on (easy, but kinda disappointing).

We also should (maybe) provide an option to create new clusters with the pre-1.6 permission model. Many people have workflows of "Create a cluster at whatever version is released, do a bunch of stuff, tear the cluster down." It'd be nice to give them a nice path forward. That might be "figure out the permissions you actually need and add the bindings in your CI script", or it could just be "set this hacky environment variable to keep ABAC until you figure out the right way."

It looks like https://github.com/kubernetes/kubernetes/pull/39537/files may be a step towards providing a smoother transition, so I'm guessing @deads2k and @liggitt and others have probably put some thought into this already and I'm just catching up.

**Comment by thockin** [comment]
I've made similar arguments.  I completely, totally, 100% believe that
moving from "single use mode" to "multi-user" clusters is the right thing
to do, and we should do it ASAP (last year, if possible).  It *is* going to
hurt a LOT of people, and we need to respect that and allow users to
opt-out for quite a while.  We also need REALLY good docs, and error
messages that can be googled along with SEO'ed solutions to those error
messages.

Writing code is easy, rolling it out is hard.

@mml

**Comment by liggitt** [comment]
> We shouldn't break existing functionality on an upgrade to 1.6

For existing clusters moving to 1.6, allowing them to continue to use an existing ABAC policy seems reasonable

Also, having RBAC policy that matches the legacy ABAC policy, but is not loaded by default in new clusters makes sense to me. If someone wants the old unrestricted behavior, we can make that possible, but we want all our CI/E2E tests exercising controllers and components using the scoped roles to make sure they are working correctly.

All that said, I don't think this particular issue is related to RBAC... ABAC wasn't set up to give anonymous users proxy access by default.

**Comment by cjcullen** [comment]
Why would kubectl be authenticating as `system:anonymous` here? That shouldn't have worked before, right?

**Comment by foxish** [comment]
It is curl without a bearer token that's authenticating as system:anonymous.  As I understand it, this is expected. The difference I guess is that previously, it would challenge and allow basic auth. Now, trying to access that same kube-dashboard URL lands me at the error 403 page.

**Comment by liggitt** [comment]
> As I understand it, this is expected. The difference I guess is that previously, it would challenge and allow basic auth.

Ah. If you want unauthenticated users to fail authentication, start your apiserver with `--anonymous-auth=false`.

**Comment by gnufied** [comment]
The user experience is still weird here IMO. I booted a cluster via `./kube-up.sh` and it presents me with those grafana, heapster  urls and there is little or no documentation about how I can access them. 

Just clicking those urls presents me with - "User "system:anonymous" cannot proxy services in the namespace "default"." error.

If kubernetes knows that the grafana, heapster urls that it is printing on terminal at the end of `kube-up.sh` command are inaccessible, it should at very minimum point me to instructions about how to open them. 

I think, we should keep this bug open.

**Comment by foxish** [comment]
From a UX perspective, I think instead of printing those URLs, we should be recommending that `kubectl proxy` be run and then those endpoints be accessed through the local proxy.

**Comment by foxish** [comment]
cc @kubernetes/sig-cli-misc

**Comment by Stono** [comment]
I'm a little lost here, but I do know that this has broken some of the scripts I was using.
For example; one of my pods uses the the api for service discovery:
```
[root@nginx-335291398-8v2tn /]# 
KUBE_TOKEN=$(</var/run/secrets/kubernetes.io/serviceaccount/token)
NAMESPACE=$(</var/run/secrets/kubernetes.io/serviceaccount/namespace)

curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" "https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/$NAMESPACE/endpoints/$LOOKUP_SERVICE_NAME"
User "system:anonymous" cannot get endpoints at the cluster scope.: "No policy matched.\nUnknown user \"system:anonymous\""
```

Can anyone give some advice how to fix/get this working, even if the intermediate fix isn't perfect, as I don't want to have to rollback.

**Comment by liggitt** [comment]
@Stono that is a different issue. Can you run curl in verbose mode and ensure the URL is as expected and you are sending a bearer token header? The error you are seeing indicates the namespace and token are not being read successfully.

**Comment by Stono** [comment]
@liggitt it was end of day human error on my part, apologies and thank you for prompting me to double check my curl!

**Comment by discostur** [comment]
@liggitt i'm facing the same problems but i think you can't change the api-server parameters (anonymous-auth=false) if you run your cluster on GCE (because google is managing the master node for you).

as i wrote in another issue:
https://github.com/kubernetes/dashboard/issues/1728#issuecomment-292953096

> That means i am not able to login to my dashboard. Since k8s v1.6, anonymous authentication is enabled by default. After enabling, the apiserver thinks we didn't provide any login information so we should be anonymous (which is wrong; instead he should provide us a login mask).
I tried to work around with my on premise cluster (where i have access to the apiserver manifest) and started it with the flag --anonymous-auth=false.
>Then i'm able to authenticate via basic auth (dashboard provides me a login mask) but after 1:20 minutes the apiserver restarts, because healthz-checks are failing (because healthz-checks are done via anonymous-requests) ... So this is no solution.
 
So starting the apiserver with the --anonymous-auth=false flag doesn't solve this problem

**Comment by liggitt** [comment]
If you disable anonymous auth, you have to move the health checks to the localhost:8080 port

**Comment by liggitt** [comment]
The best way to access the dashboard if you want to go through the API proxy is to run `kubectl proxy` locally and access http://localhost:8001/ui

**Comment by discostur** [comment]
@liggitt thanks for the tip, will try that as soon as i can ;)

**Comment by jasonbiondo** [comment]
I want to expose it fully on an IP so that I can have Jenkins integrate and build my pipelines.  Is there another way to authenticate jenkins?

**Comment by Stono** [comment]
Why would Jenkins use the UI?
You'd use kubectl?

**Comment by jasonbiondo** [comment]
when we execute  kubectl --namespace=dev apply -f deployment.yaml through jenkins (edited)

error: group map[:0xc8203ccfc0 apps:0xc8203cd030 batch:0xc8203cd180 extensions:0xc8203cd260 federation:0xc8203ccf50 authorization.k8s.io:0xc8203cd0a0 autoscaling:0xc8203cd110 componentconfig:0xc8203cd1f0 policy:0xc8203cd2d0 rbac.authorization.k8s.io:0xc8203cd340 authentication.k8s.io:0xc8203cd420 certificates.k8s.io:0xc8204f6bd0] is already registered

**Comment by Stono** [comment]
Looks unrelated mate...

**Comment by mattnworb** [comment]
> From a UX perspective, I think instead of printing those URLs, we should be recommending that kubectl proxy be run and then those endpoints be accessed through the local proxy.

This gives me the same result, at least with a cluster on GKE created with the `--no-enable-legacy-authorization` flag to `gcloud container clusters create`.

Accessing http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/#!/workload?namespace=default gives me:

> Forbidden (403)
>
> User "system:serviceaccount:kube-system:default" cannot list replicationcontrollers in the namespace "default".: "Unknown user \"system:serviceaccount:kube-system:default\"" (get replicationcontrollers)

Accessing other URLs printed out by `kubectl proxy`, such as the one for Heapster (after replacing the master IP with `http://localhost:8081`) return a 404 Not Found for `http://localhost:8001/api/v1/namespaces/kube-system/services/heapster/proxy/`.

I would have expected that the authentication info in my active context for kubectl was used when accessing anything via `kubectl proxy`. Is that wrong, do I need to pass a token in these URLs?

**Comment by liggitt** [comment]
> Accessing http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/#!/workload?namespace=default gives me:
> 
> Forbidden (403)
> 
> User "system:serviceaccount:kube-system:default" cannot list replicationcontrollers in the namespace "default".: "Unknown user "system:serviceaccount:kube-system:default"" (get replicationcontrollers)

That isn't actually the same result... that message is coming from the dashboard (which you successfully accessed) attempting to make an API call. As of https://github.com/kubernetes/kubernetes/pull/46750, GKE deployments do not give RBAC permissions to the default service account.

**Comment by Siilwyn** [comment]
Spun up a new cluster with Google Container Engine and experiencing the same problem using `kubectl proxy`. Does anybody know a workaround?

**Comment by liggitt** [comment]
> Spun up a new cluster with Google Container Engine and experiencing the same problem using kubectl proxy. Does anybody know a workaround?

Do normal `kubectl` calls (`kubectl get pods`, etc) work properly?

**Comment by Siilwyn** [comment]
@liggitt yes absolutely, everything works fine except from the dashboard. :/

**Comment by drgomesp** [comment]
Same issue here. Anyone has a work around?

**Comment by liggitt** [comment]
I'd suggest following the dashboard instructions for setup and access at https://github.com/kubernetes/dashboard/blob/master/README.md

**Comment by drgomesp** [comment]
I'm using it with Google Cloud Platform and the proxy doesn't seem to work properly.

**Comment by mattnworb** [comment]
@drgomesp the top of the dashboard setup instructions links to https://github.com/kubernetes/dashboard/wiki/Access-control which explains how to set up access control for the dashboard and also explains a bit more why things don’t have access out of the box since 1.7. You can follow the instructions at the bottom to create a ClusterRoleBinding for the dashboard’s service account (heed the warnings too though).

**Comment by dwdraju** [comment]
Having same problem and can't access kubernetes dashboard.

`Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.6-gke.1", GitCommit:"407dbfe965f3de06b332cc22d2eb1ca07fb4d3fb", GitTreeState:"clean", BuildDate:"2017-09-27T21:21:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by korenlev** [comment]
many facing same issue: https://github.com/kubernetes/kubernetes/issues/44275

**Comment by korenlev** [comment]
"I'd suggest following the dashboard instructions for setup and access at https://github.com/kubernetes/dashboard/blob/master/README.md"
so only access to dashboard is from localhost ? what if needed from remote ?

**Comment by liggitt** [comment]
Dashboard documentation now directs users to use `kubectl proxy` and access the dashboard at http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

https://github.com/kubernetes/dashboard/#documentation also links to the various ways to expose the dashboard at https://github.com/kubernetes/dashboard/wiki/Accessing-dashboard

/close

**Comment by 372046933** [comment]
`curl` has `--cacert`, `--cert` and `--key` options that can be leveraged to access the Kubernetes service.

**Comment by Enelar** [comment]
> From a UX perspective, I think instead of printing those URLs, we should be recommending that kubectl proxy be run and then those endpoints be accessed through the local proxy.

@liggitt no, you still cant access any of those resources even if you did proxy. From UX perspective there is several doc sources, but at the end after `kube-up` there nothing much you can do. Firstly i spend 4 hours to custom patch script, so i could spinup gce g1-small + f1-micro-preemtible. then i just keep fighting agains dashbord and everything. i just cant stand it.

Simple question, why does my work machine with root access to everything unable to serve access to dashboard through authenticated `kubectl proxy`?

**Comment by liggitt** [comment]
> why does my work machine with root access to everything unable to serve access to dashboard through authenticated kubectl proxy?

`kubectl proxy` is just a way to get network visibility to the dashboard pod via the apiserver. Once you are able to access the dashboard, the dashboard still needs sufficient permission to access the API to fetch the data to serve you. The currently recommended way to do that is to log into the dashboard with an API token with sufficient permissions. 

> User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list persistentvolumeclaims
is forbidden: User "system:serviceaccount:default:kberezin" cannot list persistentvolumeclaims

That looks like you are not authenticating to the dashboard, and are instead having it use its own credentials to access the API when viewing dashboard pages. 

> kubectl create clusterrolebinding --user {username} {rulename} --clusterrole cluster-admin does the trick, where username probably is: system:serviceaccount:kube-system:kubernetes-dashboard

Granting that permission means that anything with network visibility to the dashboard pod (like other pods) can access cluster-admin permissions via the dashboard.

**Comment by adeelahmadch** [comment]
I also ran into this issue after upgrading from **1.18.16** to **1.19.8** using kops. After upgrade, I was not able to execute **kubectl logs** commands any more  and the rest were working fine.I got the following error;

```
Error Msg: Error from server (Forbidden): Forbidden (user=system:anonymous, verb=get, resource=nodes, subresource=proxy) ( pods/log pod-name)
```

In my case, I have to add the below mentioned lines to fix it. I already had `authorizationMode: Node,RBAC` just incase you are wondering. 

```
kubeAPIServer:
    kubeletClientCertificate: /srv/kubernetes/kubelet-server.crt
    kubeletClientKey: /srv/kubernetes/kubelet-server.key

kubelet:
    anonymousAuth: false
```

To me, it was a surprise as how it was working before in **1.18.16**.
