### ISSUE TITLE
API server returns 500 when issued a Get with invalid label selector

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#39730]
I'm seeing logs like on 1.5 cluster:
```
E0111 09:00:06.466257       5 errors.go:63] apiserver received an error that is not an unversioned.Status: unable to parse requirement: invalid label key "<label key>": name part must be no more than 63 characters; name part must match the regex ([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9] (e.g. 'MyName' or 'my.name' or '123-abc')
I0111 09:00:06.466418       5 handlers.go:162] GET /api/v1/namespaces/jenkins/pods?labelSelector=<label>: (613.07�s) 500
```

We probably should return 400 (or maybe 412?), eventually 418. But certainly not 500.

cc @deads2k @lavalamp @wojtek-t @smarterclayton @kubernetes/sig-api-machinery-misc

**Comment by shyamjvs** [comment]
@gmarek On tried digging this up a little bit and figured out that this is not an issue with the apiserver on the master, but instead with the heapster-apiserver (the one which negotiates request/response serialization with the heapster client on one side and is bound to the master metrics API on the other). The following seems to be the issue:
- The [errToAPIStatus function](https://github.com/kubernetes/heapster/blob/master/vendor/k8s.io/kubernetes/pkg/apiserver/errors.go#L53) inside the heapster apiserver does `status := http.StatusInternalServerError` if the error type is not `statusError`. This is why the response is being logged with 500 (even though it is (most probably) a 400 from the master apiserver).
- The [logStackOnRecover function](https://github.com/kubernetes/heapster/blob/master/vendor/k8s.io/kubernetes/pkg/apiserver/apiserver.go#L193) should do better than just flagging `http.StatusInternalServerError` as the error. Maybe set code to `http.StatusBadRequest` if we know that the request was not matching the negotiated pattern.

cc @piosz @kubernetes/sig-instrumentation-misc

**Comment by lavalamp** [comment]
hm, there should already be an equivalent of that errToAPIStatus function in the generic apiserver library somewhere.

**Comment by gmarek** [comment]
@lavalamp - who should work on this?

**Comment by janetkuo** [comment]
Would love to cherrypick the fix to both 1.4 and 1.5

**Comment by crassirostris** [comment]
What is the status of this issue?

**Comment by gmarek** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by sttts** [comment]
This does not only apply to Get. Working on a (pretty simple) PR.
