### ISSUE TITLE
Federation should enable etcd2 -> etcd3 migration for existing deployments. 

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#39746]
PR #39646 moved the federation's storage from etcd2 to etcd3. However, it just changed the image and made `etcd3` use `etcd2` as the storage backend. We still need to enable `etcd3` as a storage backend and also enable people with existing federation control plane deployments to migrate from `etcd2` to `etcd3`.

Follow up to issue #39594.

cc @kubernetes/sig-federation-misc @nikhiljindal @shashidharatd

**Comment by ethernetdan** [comment]
@madhusudancs Is this blocking for `v1.6`?

**Comment by ethernetdan** [comment]
Too late for v1.6, moving to v1.7. Please change milestone if incorrect.

/cc @kubernetes/release-team

**Comment by madhusudancs** [comment]
@ethernetdan fair enough. I will add a release note explaining the caveat though.

**Comment by madhusudancs** [comment]
Filed a documentation issue to track that here - https://github.com/kubernetes/kubernetes.github.io/issues/2811

**Comment by marun** [comment]
I'm assuming this shouldn't be blocking 1.7.

**Comment by dims** [comment]
@marun @madhusudancs this shouldn't be blocking 1.8 either right?

**Comment by madhusudancs** [comment]
@dims No. Also deferring this to @quinton-hoole and @marun  

/unassign
/assign @quinton-hoole @marun

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#92.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
