### ISSUE TITLE
Deployment status.unavailableReplicas is incorrect

### ISSUE THREAD

**Issue by zihaoyu** [kubernetes/kubernetes#39741]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

#21900
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG Report

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS Stable 1235.5.0
- **Kernel** (e.g. `uname -a`): `4.7.3-coreos-r2 #1 SMP Sun Jan 8 00:32:25 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz GenuineIntel GNU/Linux`
- **Install tools**:
- **Others**:

**What happened**:

Saw this error message in `kube-controller-manager` log
```
E0111 15:59:14.059719   26999 deployment_controller.go:303] Deployment.extensions "concierge" is invalid: status.unavailableReplicas: Invalid value: -12: must be greater than or equal to 0
```

Rollout seems to be stuck at 12 available pods. 

**What you expected to happen**:

Rollout finishes successfully.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by kargakis** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/38299
