### ISSUE TITLE
Node disconnect and re-connect to cluster leads to duplicate pod name and then unexpected results

### ISSUE THREAD

**Issue by nvnobelen** [kubernetes/kubernetes#39744]
BUG REPORT/FEATURE REQUEST

**Environment:**

Kubernetes version: 1.3.5

**Description:**

The following occurred:
* A machine disconnected from the cluster due to a network issue
* Kubernetes rescheduled the pods which where running on this machine, updates LB etc.
* Machine reconnects to the cluster (this was about 5 minutes later).
* Pod now exists twice since the disconnected machine kept the pod alive
* Kubernetes responds with DELETE on the pod killing all pods with the name of the pod.

The end result is a consistent situation (so that is great), however: 
**The (perceived) bug:**

* Both pods where gone, while I would expect to have still 1 pod left with the given name.
* The DELETE was executed with triggering the lifecyle.preStop.

**The possible fix is I think a feature change:**

* On reschedule of a pod due to machine failure, rename the pod so that if the machine which contains the failed pod returns to the cluster, the pod can be re-registered and handled with in a more graceful fashion.

This option has to be optional in the deployment since this method only work reliable on horizontally scaleable pods, and does for example not work great for a database like MariaDB. 

In my opinion the best place would be in spec.strategy with a single new option:
spec.strategy.reschedule=(rename or default current behavior).

**Comment by kargakis** [comment]
@nvnobelen replica sets use generateName to create pods which means that every newly created pod should have a unique name.
