### ISSUE TITLE
docs for federation-controller-manager should indicate that coredns is a valid option

### ISSUE THREAD

**Issue by emaildanwilson** [kubernetes/kubernetes#39749]
https://kubernetes.io/docs/admin/federation-controller-manager/ should indicate that coredns is a valid option for --dns-provider. 

https://github.com/kubernetes/kubernetes/issues/39271#issuecomment-271783981

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#93.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
