### ISSUE TITLE
create k8s.io/apiserver repo

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#39759]
`staging/src/k8s.io/apiserver` has gotten large enough that people are starting to ask about godeping it.  This means we need to hash out the name and create a repo for it, along with a sync script (possibly like this: https://github.com/kubernetes/apimachinery/pull/2

@lavalamp @kubernetes/sig-api-machinery-misc @smarterclayton @liggitt @sttts
@jayunit100 since you asked.
@pmorie since you're going to ask.

**Comment by lavalamp** [comment]
this is formerly the genericapiserver library, right? I think we should make a repo for it, yes.

**Comment by deads2k** [comment]
> this is formerly the genericapiserver library, right? I think we should make a repo for it, yes.

Correct and @sttts and @smarterclayton agree that `k8s.io/apiserver` is a good name.  Once we have the repo, I'd plan to make a cloning script similar to what I opened in kubernetes/apimachinery#2 .

While I'm thinking about it, is there a spot to run that script in a job somewhere?

**Comment by lavalamp** [comment]
Yes, we do have a place where the existing script for the client is running, I can try and find it for you.

Do you have a readme etc all ready to go for apiserver repo? I can make it pretty quick if so.

**Comment by lavalamp** [comment]
See:
https://github.com/kubernetes/contrib/tree/master/mungegithub/publisher/deployment

**Comment by deads2k** [comment]
Yes, I have a readme.md here: https://gist.github.com/deads2k/0f5ec24fda252eb8cc41a72798274e18

**Comment by lavalamp** [comment]
OK. really sorry I didn't get to this today. First thing tomorrow.

**Comment by deads2k** [comment]
@jayunit100 you should be able to godep this now.
