### ISSUE TITLE
Should we detach an  attached cinder volume forcibly before attaching elsewhere

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes/kubernetes#39791]
#39055  #33288

When a cinder volume is attached by one pod, and then another pod uses the same cinder volume (maybe by mistake),if we detach an  attached cinder volume forcibly, the first pod will lose access to the cinder volume unexpected. This may cause some unpredictable problems.  Is my understanding right?

**Comment by codablock** [comment]
@NickrenREN Please check https://github.com/kubernetes/kubernetes/pull/40148#issuecomment-278154269

Forcefully detaching the volume from a node while the old POD is still running/terminating sounds like a bad thing.
