### ISSUE TITLE
Is there a completion package for k8s 1.5？

### ISSUE THREAD

**Issue by keith4743** [kubernetes/kubernetes#39796]
OS：CentOS7.2

I have installed bash-completion and bash-completion-extras, but can not complete command in k8s.

**Comment by cblecker** [comment]
If you mean for the `kubectl` utility, yes.
If you pipe `kubectl bash completion` to a file, and place it in your bash-completion folder.

**Comment by keith4743** [comment]
@cblecker thanx, I have found the guide.

https://kubernetes.io/docs/user-guide/kubectl/kubectl_completion/
