### ISSUE TITLE
Update to new version of SaltStack for GCE

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubernetes#3979]
Right now GCE is locked to the v2014.1.13 version of salt.  There is a new major version (2014.7.1) out that we should look to switch to.  We might want to wait until 2014.7.2 is out (early Feb)

Instructions for updating are sketched out here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/templates/README.md

**Comment by roberthbailey** [comment]
2014.7.2 is now out (http://docs.saltstack.com/en/latest/topics/releases/2014.7.2.html).

**Comment by roberthbailey** [comment]
We are now quite a bit further out of date, as the current release is 2015.8.0 (https://docs.saltstack.com/en/latest/topics/releases/2015.8.0.html). However, there are quite a few efforts underway to reduce / eliminate our dependencies on salt, and we know the bugs in the version that we are currently using. I don't see this being high enough priority for someone to work on it any time soon.
