### ISSUE TITLE
Systems components' logs

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#39800]
Currently several system components running in containers, like scheduler[1] or kube-proxy[2] are logging directly to the `/var/log` directory. Because of that:

* Logging agent configuration is hairy, it should contain manually added records for all components[3]. Introducing new system component require further manual intervention
* Logs from system components are under `gce_instance` resource in Stackdriver Logging, since they're indistinguishable for SD agent from instance logs
* Logging in such fashion is hardly manageable, since it's not coupled with a pod

However, it's not possible to switch to using default container logging mechanisms, due to the following reasons:

* Some system components, like kube-proxy, are exporting multi-line log entries. Currently Docker wraps every line from the container stdout in the separate logging entry, so it has to be put back together in one piece by some entity. At the moment there's only one entity: logging agent. However, it's not clear how to configure a logging agent to ingest e.g. glog multi-line log entries without breaking any other logging formats.
* Test infrastructure collects system components' logs to expose them as artifacts by downloading directly from the node by known name. This behavior should be altered to use `kubectl logs`

[1] https://github.com/kubernetes/kubernetes/blob/release-1.5/cluster/saltbase/salt/kube-scheduler/kube-scheduler.manifest#L50
[2] https://github.com/kubernetes/kubernetes/blob/release-1.5/cluster/saltbase/salt/kube-proxy/kube-proxy.manifest#L63
[3] https://github.com/kubernetes/kubernetes/blob/release-1.5/cluster/addons/fluentd-gcp/fluentd-gcp-image/google-fluentd.conf

CC @kubernetes/sig-instrumentation-misc @repeatedly @tagomoris

**Comment by spiffxp** [comment]
/remove-priority P2
/priority backlog
(I'm not actually sure this is the right priority, just trying to remove the old priority/PN labels)
