### ISSUE TITLE
bazel-build: `/usr/bin/ld: -r and -pie may not be used together`

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#39819]
Running `make bazel-build` on debian stretch, I am getting:

`/usr/bin/ld: -r and -pie may not be used together`

I've found some references to this being because the stretch version of ld sets `-pie` by default (e.g. https://github.com/rumpkernel/rumprun/issues/85 ).  But it isn't clear to me how to address this.

Also, why is bazel using the ld from my system anyway (presuming it is)?  That is not reproducible.

cc @mikedanese 

```
~/code/kubernetes/src/k8s.io/kubernetes  (master) > make bazel-build
INFO: Found 3509 targets...
ERROR: /home/justinsb/code/kubernetes/src/k8s.io/kubernetes/vendor/BUILD:5165:1: Linking vendor/github.com/opencontainers/runc/libcontainer/system_cgo.cgo.dir/gen/_all.o failed: linux-sandbox failed: error executing command /home/justinsb/.cache/bazel/_bazel_justinsb/1f944bd9facab588950182ed33f07ddc/execroot/kubernetes/_bin/linux-sandbox ... (remaining 27 argument(s) skipped).
/usr/bin/ld: -r and -pie may not be used together
collect2: error: ld returned 1 exit status
INFO: Elapsed time: 2.136s, Critical Path: 0.47s
Makefile:486: recipe for target 'bazel-build' failed
make: *** [bazel-build] Error 1
~/code/kubernetes/src/k8s.io/kubernetes  (master) > bazel version
Build label: 0.4.3
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 22 12:31:25 2016 (1482409885)
Build timestamp: 1482409885
Build timestamp as int: 1482409885
```

**Comment by mikedanese** [comment]
@ixdy @spxtr this would be fixed by building in a container.

cc @damienmg

**Comment by justinsb** [comment]
Oh good call @mikedanese ... so I can unblock myself by running in a docker container with e.g. debian jessie.

Is this a bazel bug?  We do download the latest golang, it feels odd to then use the system linker (?)

**Comment by mikedanese** [comment]
It sounds like it might be a bad assumption in either cc_library rule in bazel core or in cgo_codegen from http://github.com/bazelbuild/rules_go

**Comment by damienmg** [comment]
So default toolchain bazel use is the one from the host which is indeed not reproducible. If Kubernetes ship its own toolchain, using --crosstool_top can change it. If not it might be a bug in the rules_go for cgo support.

I wasn't aware of an issue with debian stretch anyhow, I'll start adding the various debian stable to our CI (we test with ubuntu right now)

**Comment by pmbethe09** [comment]
I don't see either -pie or -r in the copts inside http://github.com/bazelbuild/rules_go or the line in the error
https://github.com/kubernetes/kubernetes/blob/master/vendor/BUILD#L5165

So I would guess it has to do with the crosstool configuration?

**Comment by damienmg** [comment]
We will had a test and fix that in Bazel for the incoming release.

**Comment by justinsb** [comment]
Thanks for looking at it!  I don't know if this is helpful at this point, but I ran `bazel build -s //...` and it appears that `-pie` is not explicitly passed (see below); so I believe stetch enables it automatically.  I tried passing `-no-pie` manually to the clinkoptions but didn't have a lot of success.

```
>>>>> # //vendor:github.com/opencontainers/runc/libcontainer/system_cgo.cgo.dir/gen/_cgo_object [action 'Linking vendor/github.com/opencontainers/runc/libcontainer/system_cgo.cgo.dir/gen/_all.o']
(cd /home/justinsb/.cache/bazel/_bazel_justinsb/de9a56b0512424c1ef93d63ccc9fbcec/execroot/kubernetes && \
  exec env - \
  /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-canonical-system-headers -fno-omit-frame-pointer -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -B/usr/bin -B/usr/bin -pass-exit-codes -o bazel-out/local-fastbuild/bin/vendor/github.com/opencontainers/runc/libcontainer/system_cgo.cgo.dir/gen/_all.o -nostdlib -Wl,-r -Wl,-whole-archive bazel-out/local-fastbuild/bin/vendor/github.com/opencontainers/runc/libcontainer/system_cgo.cgo.dir/gen/lib_cgo_lib.lo)
>>>>> # //vendor:github.com/opencontainers/runc/libcontainer/system_cgo.cgo.dir/gen/_cgo_.o [action 'Linking vendor/github.com/opencontainers/runc/libcontainer/system_cgo.cgo.dir/gen/_cgo_.o']
(cd /home/justinsb/.cache/bazel/_bazel_justinsb/de9a56b0512424c1ef93d63ccc9fbcec/execroot/kubernetes && \
  exec env - \
  /usr/bin/gcc -o bazel-out/local-fastbuild/bin/vendor/github.com/opencontainers/runc/libcontainer/system_cgo.cgo.dir/gen/_cgo_.o -Wl,-no-as-needed -B/usr/bin -B/usr/bin -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,-S -Wl,@bazel-out/local-fastbuild/bin/vendor/github.com/opencontainers/runc/libcontainer/system_cgo.cgo.dir/gen/_cgo_.o-2.params)
ERROR: /home/justinsb/k8s/src/k8s.io/kubernetes/vendor/BUILD:3780:1: Linking vendor/github.com/google/cadvisor/utils/cpuload/netlink_cgo.cgo.dir/gen/_all.o failed: linux-sandbox failed: error executing command /home/justinsb/.cache/bazel/_bazel_justinsb/de9a56b0512424c1ef93d63ccc9fbcec/execroot/kubernetes/_bin/linux-sandbox ... (remaining 27 argument(s) skipped).
/usr/bin/ld: -r and -pie may not be used together
collect2: error: ld returned 1 exit status
```

**Comment by ixdy** [comment]
As a side note, I wonder if we should be using our own `--crosstool_top`. We don't have much cgo code, but it seems like this could be a source of confusion in debugging at some point.

**Comment by mikedanese** [comment]
@ixdy we will probably need to maintain a crosstool for our various cross compilation needs anyway.

**Comment by mikedanese** [comment]
This is easily reproduced with:
```dockerfile
FROM debian:stretch

RUN apt-get update
RUN apt-get install -y unzip build-essential openjdk-8-jdk git curl
RUN curl -L -O https://github.com/bazelbuild/bazel/releases/download/0.4.3/bazel-0.4.3-installer-linux-x86_64.sh
RUN bash bazel-0.4.3-installer-linux-x86_64.sh
RUN git clone https://github.com/kubernetes/kubernetes.git /root/kubernetes

WORKDIR /root/kubernetes

CMD bazel build //vendor:github.com/opencontainers/runc/libcontainer/system
```

**Comment by mikedanese** [comment]
I believe I figured it out. As part of the GCC 6 release notes, they mention a new gcc compile time option --enable-default-pie which enables pie by default. Appearantly it's a more secure default.

https://gcc.gnu.org/gcc-6/changes.html

Passing `-no-pie` to the failing GCC command fixes this issue.

**Comment by damienmg** [comment]
Ok I have added a test for debian stretch and we are not hitting that on a standard C++ example, see https://bazel-review.googlesource.com/c/8219/

**Comment by damienmg** [comment]
It fails in a cgo action but the action does not explicitely pass neither -r nor -pie to the linker... Anyhow throwing the ball at rules_go since C++ compilation works ok.

**Comment by mikedanese** [comment]
@damienmg this is caused by gcc 6 on debian which enable -pie by default (whether you pass -pie or not). This is different then gcc-5 behavior. To fix this we need to pass -no-pie explicitly or stop using -r.

**Comment by mikedanese** [comment]
This is tracked in bazelbuild/rules_go#252
