### ISSUE TITLE
List returns nil items field

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#39822]
Behavior of the `items` field for empty lists has changed in 1.5.

With 1.4 (and earlier releases):
```
{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/namespaces/default/pods",
    "resourceVersion": "117"
  },
  "items": []
}
```

With 1.5 and master:
```
{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/namespaces/default/pods",
    "resourceVersion": "25"
  },
  "items":null
}
```

Looks like a re-emergence of https://github.com/kubernetes/kubernetes/issues/2070 / https://github.com/kubernetes/kubernetes/pull/2075

**Comment by liggitt** [comment]
cc @kubernetes/sig-api-machinery-misc @smarterclayton @derekwaynecarr

**Comment by liggitt** [comment]
bisected to https://github.com/kubernetes/kubernetes/commit/4f363f54474bf363f0890c0c899dc331b7b34673#diff-fe6dbe5fa548ea5c031a5be1669a6376L1072

we no longer call meta.SetList(obj, items) while processing a list call, which had the side effect of turning a nil list into an empty list

**Comment by liggitt** [comment]
cc @soltysh @ncdc

**Comment by smarterclayton** [comment]
Probably should have an explicit reflection based "if nil, then set" function.

**Comment by liggitt** [comment]
yup, doing it, adding a test, will open the cherry-pick

**Comment by smarterclayton** [comment]
Explicit at the end of the list return call, not inside EachListItem.

**Comment by lavalamp** [comment]
If this is an important detail, then please make a unit test.
