### ISSUE TITLE
STONITH - path to self healing cluster

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#39828]
I would recommend a design spike on when to Shoot a Node In The Head.

From Wikipedia:

> STONITH ("Shoot The Other Node In The Head" or "Shoot The Offending Node In The Head"), sometimes called STOMITH ("Shoot The Other Member/Machine In The Head"), is a technique for fencing in computer clusters.[1]

> Fencing is the isolation of a failed node so that it does not cause disruption to a computer cluster. As its name suggests, STONITH fences failed nodes by resetting or powering down the failed node.

> Multi-node error-prone contention in a cluster can have catastrophic results, such as if both nodes try writing to a shared storage resource. STONITH provides effective, if rather drastic, protection against these problems.

> References[edit]
Jump up ^ Alan Robertson (2010). ["Resource fencing using STONITH"](ftp://ftp.telecom.uff.br/pub/linux/HA/ResourceFencing_Stonith.pdf) (PDF). IBM Linux Research Center. 

@justinsb and other raised this issue on a call.  I would like to investigate the possibly that all components in K8s have the capability of tagging a node to be cordoned and then possibly drained. 

Off of the top of my head, the following components should be able to do this:

- autoscaler
- k-c-m
- scheduler
- api server (maybe not)
- kubelet
- installer / managers / monitoring such as `kops`, external monitoring, and other tools.

What other patterns have been extremely successful with clustered solutions?

**Comment by chrislovecnm** [comment]
cc @saad-ali 

What sig do you think this would fall under?

**Comment by smarterclayton** [comment]
Please see the pod safety proposal https://github.com/kubernetes/community/blob/master/contributors/design-proposals/pod-safety.md - this is covered under that as "fencing".  Fencers need to ensure resources are irrevocably partitioned before any sort of STONITH is possible.

**Comment by justinsb** [comment]
Aha - here is the issue.  Closing as a dup of https://github.com/kubernetes/kops/issues/2002
