### ISSUE TITLE
Users should be able to delete in a way that respects PodDisruptionBudgets

### ISSUE THREAD

**Issue by maisem** [kubernetes/kubernetes#39824]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**Kubernetes version** (use `kubectl version`): 1.5.1

**What happened**:
"kubectl delete pods" deletes pods backed by a PodDisruptionBudget without using the Eviction subresource.

**What you expected to happen**:
"kubectl delete pods" should prevent deletion of pods that would violate the PDB.

**Comment by foxish** [comment]
I'd expect `kubectl delete` to warn about the fact that we're violating PDB but still allow for a way (--force?) to violate it and delete it anyway.

cc @davidopp @kow3ns @kubernetes/sig-cli-misc @kubernetes/sig-apps-misc

**Comment by maisem** [comment]
@foxish I agree, it should allow a way to forcibly delete the pod.

**Comment by davidopp** [comment]
The reason we added eviction subresource to the API instead of making the DELETE REST operation use PDB was for backward compatibility -- we didn't want to break API clients that expect DELETE to always succeed. So the question is, does "kubectl delete" similarly need backward compatibility? If not, then what you proposed here (have "kubectl delete" use eviction subresource, and add a --force flag that does a real DELETE instead) sounds good. But if we need backward compatibility for "kubectl delete" then we need to do it the other way (leave current "kubectl delete" as-is and add a flag --respect-pdb or something like that, that uses eviction subresource).

https://kubernetes.io/docs/deprecation-policy/
talks about deprecating CLI commands but doesn't seem to say anything about just changing the behavior. Might want to check with @thockin or @bgrant0607

**Comment by kargakis** [comment]
Users would need to opt-in otherwise it's a breaking change.

**Comment by smarterclayton** [comment]
Delete via eviction doesn't sound like normal delete.  It sounds like
soft deletion or something else.

Put another way - as a user, what does deletion mean to me?  Am I
surprised that the pod is deleted?  Probably not.

**Comment by maisem** [comment]
Maybe we should then introduce another command in kubectl. Something like `kubectl evict`?

**Comment by smarterclayton** [comment]
I would certainly expect something like evict much more than delete, for
sure.

**Comment by davidopp** [comment]
Sure, "kubectl evict" sounds fine to me. And actually we had been planning to eventually have an "evict the pod and don't schedule its replacement on the same node" operation, so that could become a command-line option to "kubectl evict"

**Comment by AdoHe** [comment]
`kubectl evict` sounds good to me. I would like `delete` always do a normal deletion and get the object deleted.

**Comment by deimosfr** [comment]
Any news on this topic ? As far as I know, it's not possible to rolling restart a statefulset and as deleting all pods at once is not handled by the PodDisruptionBudget, what is the recommended solution then?

How could we rolling restart a statefulset or deployments with a PodDisruptionBudget ?

**Comment by kow3ns** [comment]
@deimosfr It is possible to perform a rolling update on a StatefulSet as of 1.7. In 1.8 RollingUpdate is the default update strategy for all core workload API objects (Deployment, DaemonSet, ReplicaSet, and StatefulSet). Each of these provides a way to manage the disruptions that the application will tolerate (except for StatefulSet where the controller will only introduce one disruption at a time during a RollingUpdate).

In general, as an application owner, you should configure the workload API object that manages your workload to tolerate the number of disruptions that you desire during turn-up, turn-down, roll-out, and/or roll-back. You should use PDBs to communicate the number of disruptions that your application will tolerate to cluster administrators who may perform disruptive operations (e.g. node maintenance) and be unaware of the availability concerns of your applications. 

As a best practice, during disruptive operations, cluster administrators should cordon and drain nodes (this uses eviction) to respect PDBs.

**Comment by 2rs2ts** [comment]
/remove-lifecycle stale

this is relevant to my interests

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-cli-feature-requests  @kubernetes/sig-apps-feature-requests

**Comment by xguerin** [comment]
Also relevant to my interest. Sequentially deleting pods in a StatefulSet respect the PDB. Batch-delete the pods with their label does not. The documentation does not make such a distinction. What is the proper approach to avoid batch-delete voluntary disruptions?

**Comment by mattnworb** [comment]
@2rs2ts 

> BTW the docs on disruptions say that directly deleting a pod is a voluntary disruption, to which PodDisruptionBudgets apply: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/

I think this section of the document is worded ambiguously - is it attempting to say that these typical application owner actions are all voluntary disruptions, or just listing actions that are application owner actions?

> We call other cases voluntary disruptions. These include both actions initiated by the application owner and those initiated by a Cluster Administrator. Typical application owner actions include:
> 
> - deleting the deployment or other controller that manages the pod
> - updating a deployment's pod template causing a restart
> - directly deleting a pod (e.g. by accident)

**Comment by zhixinwen** [comment]
I agree. The doc gives a false sense that all the voluntary disruptions are constrained by PDB, which should be more clear.

**Comment by Joseph-Irving** [comment]
Yeah that doc could do with some rewording to make it clear what actions obey the PDB, currently it gives example of non voluntary disruptions like hardware failure, node deletion etc but then it seems to imply that something like deleting a deployment is a  voluntary disruption and would therefore obey PDB. 

This doesn't make any sense to me, if I've deleted a deployment I do not expect my pods to stay around.

If people think `kubectl evict` command would be useful it's probably a good idea to create a KEP over at https://github.com/kubernetes/enhancements to help move this forward.

**Comment by krmayankk** [comment]
imo `kubectl delete --respect-pdb` is more intuitive. People know what delete does, and now they want it to respect disruption budgets. evict introduces a new verb which is known to expert api user but probably needs more explaining to kubectl user.

Also am i reading this correctly that StatefulSets doesnt respect PDB ?

**Comment by liggitt** [comment]
Does kubectl drain respect PDB?

**Comment by krmayankk** [comment]
Yes drain respects PDB https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/ @liggitr

**Comment by krmayankk** [comment]
i see that documentation has been fixed to make it clearer that kubectl delete pods wont respect pdb, but is there more needed ?
- should we add kubectl delete pod --respect-pdb like thing 
- do we need kubectl evict 
- what about kubectl delete deployments/statefulsets ?

**Comment by liggitt** [comment]
> * should we add kubectl delete pod --respect-pdb like thing

`delete` is a generic method... I don't think overloading one specific resource to use a different API is a good idea

> do we need kubectl evict

doesn't `kubectl drain` use the eviction endpoint already? what would the behavior of an `evict` command be? if eviction was rejected, would the command succeed or fail?

> what about kubectl delete deployments/statefulsets?

Deletion of a pod-creating controller is intended to remove all pods owned by that controller by default. Preventing cleanup of orphaned pods to avoid "disruption" could result in stuck pods.

**Comment by shacharSilbert** [comment]
/reopen

Any other way I could test that my PDB works if I can't delete pods and see that it doesn't delete?

And the guys here are right, there is a documentation issue where it is understood deleting a pod should take PDB into account.

**Comment by fkaleo** [comment]
> BTW the docs on disruptions say that directly deleting a pod is a voluntary disruption, to which PodDisruptionBudgets apply: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/

Documentation now states:
>     Caution: Not all voluntary disruptions are constrained by Pod Disruption Budgets. For example, deleting deployments or pods bypasses Pod Disruption Budgets.

from https://kubernetes.io/docs/concepts/workloads/pods/disruptions/

**Comment by blackjackyau** [comment]
the documentation today is very confusing still, especially this line (https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#voluntary-and-involuntary-disruptions)

> We call other cases voluntary disruptions. These include both actions initiated by the application owner and those initiated by a Cluster Administrator. Typical application owner actions include:
>- deleting the deployment or other controller that manages the pod
>- updating a deployment's pod template causing a restart
>- directly deleting a pod (e.g. by accident)

And **NONE** of these will respect the PDB constraint

**Comment by Kenneth-Abrams** [comment]
/remove-lifecycle rotten

Deleting pods should respect pod disruption budget. 3 years and this still is not solved.

**Comment by ohads-MSFT** [comment]
> Any other way I could test that my PDB works if I can't delete pods and see that it doesn't delete?
> 
> And the guys here are right, there is a documentation issue where it is understood deleting a pod should take PDB into account.

It looks like a plugin has been created for this purpose exactly: https://github.com/ueokande/kubectl-evict
