### ISSUE TITLE
glusterfs client is outdated in hyperkube image

### ISSUE THREAD

**Issue by robdewit** [kubernetes/kubernetes#39820]
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: bare metal
- **OS** (e.g. from /etc/os-release): slackware
- **Kernel** (e.g. `uname -a`): Linux <node> 4.4.14 #2 SMP Fri Jun 24 13:38:27 CDT 2016 x86_64 Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz GenuineIntel GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
I try to mount glusterfs using a kubernetes install that runs kubelet through hyperkube in a container. Mounting fails at getting the volume from the glusterfs server:

[2017-01-12 15:26:44.719315] E [glusterfsd-mgmt.c:1297:mgmt_getspec_cbk] 0-glusterfs: failed to get the 'volume file' from server
[2017-01-12 15:26:44.719355] E [glusterfsd-mgmt.c:1398:mgmt_getspec_cbk] 0-mgmt: failed to fetch volume file (key:glfs1/brick1)

As the glusterfs server run 3.9.0 and the client software in the hyperkube image is 3.5.2, it seems impossible to mount the volme.

**What you expected to happen**:
I would like the glusterfs volume to be mounted.

**How to reproduce it** (as minimally and precisely as possible):

- Setup glusterfs volume with 3.9.0 version
- Make sure the node can mount it, so network issues are ruled out
- Start Kubernetes 1.5.2 with containerized kubelet using hyperkube.
- Configure glusterfs in Kubernetes like detailed on https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/glusterfs
- Run test-pod, it won't start as it cannot mount the glusterfs volume

Alternative would be to docker exec into the kubelet image and try to mount it by hand. I can ping and connect to glusterfs port, but mounting fails at the getting volume info stage.

**Anything else do we need to know**:
I already added --privileged=true and --device /dev/fuse to the docker startup code to allow kubelet to be able to mount fuse filesystems.

**Comment by robdewit** [comment]
Solved.

Seems the problems were caused by running kubelet with --readonly option. Using strace when mounting a volume I found this out: When glusterfs mounts it needs write access to: (/dev/fuse), /etc, /tmp and /var/log/glusterfs. Once I added the latter two, mounting a glusterfs volume in a pod succeeded.

**Comment by jingxu97** [comment]
@robdewit thank you for reporting this. Please let us know if you have any issue when using glusterfs.
