### ISSUE TITLE
kubectl get all does not list PDBs

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#39830]
`kubectl get all` does not list the PDBs in a cluster.

```
~kubectl get all
NAME      READY     STATUS    RESTARTS   AGE
po/zk-0   1/1       Running   0          2m
po/zk-1   1/1       Running   0          2m
po/zk-2   1/1       Running   0          1m

NAME              CLUSTER-IP   EXTERNAL-IP   PORT(S)             AGE
svc/kubernetes    10.0.0.1     <none>        443/TCP             11m
svc/zk-headless   None         <none>        2888/TCP,3888/TCP   2m

NAME              DESIRED   CURRENT   AGE
statefulsets/zk   3         3         2m
```

```
~ kubectl get poddisruptionbudget
NAME                 MIN-AVAILABLE   ALLOWED-DISRUPTIONS   AGE
cockroachdb-budget   67%             0                     7d
zk-budget            100%            0                     1m
```

Client Version: v1.5.1

**Comment by xiangpengzhao** [comment]
`Pod Disruption Budget` is a kind of policy. It's a namespace admin level resource, so it will not be displayed in `kubectl get all` output. 

See: [Rules for extending special resource alias - "all"](https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#rules-for-extending-special-resource-alias---all)

@bgrant0607 Brian might confirm this and close the issue :)

**Comment by thockin** [comment]
thanks for scrubbing!

**Comment by foxish** [comment]
Thanks @xiangpengzhao!

**Comment by vdm** [comment]
This UX sucks. The documentation should list the exceptions. As in: "... except pdb"
```
$ kubectl get all --help
[..]

  # List all resources with different types.
  kubectl get all
```

Landed here from https://www.google.com/search?q=kubectl+get+all+pdb
