### ISSUE TITLE
Implement `kubectl create autoscaler`

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#39833]
The `kubectl autoscale` command creates and autoscaler, but new creation commands are being standardized as `kubectl create <resource> <name>`.  We should keep the old command, but mirror it either as an alias or new implementation under `kubectl create` so that `kubectl create` is the canonical source for creation commands.

**Comment by xingzhou** [comment]
@pwittrock and @monopole, I'm working on similar command: `kubectl create role`, not sure if you have started the coding now? if not, I can help submit a PR for this command as well.

**Comment by kargakis** [comment]
Is there a plan to deprecate the first generation of generator commands like `expose`, `run`, and `autoscale` in favor of `create` subcommands? Also, I guess if we are going to do this, it will be `kubectl create hpa` since `autoscaler` is not a thing for the kube restmapper.

cc: @kubernetes/sig-cli-misc

**Comment by AdoHe** [comment]
@kargakis I am afraid there is no such plan to deprecate commands like `expose`, `run` as for now. But we do plan to add more create subcommands in 1.6.

**Comment by AdoHe** [comment]
@xingzhou That would be great, I am supposed to do more work about create subcommands, if you already working on `create role`,  I would like to help review.

**Comment by xingzhou** [comment]
@AdoHe, the `create role` PR is [here](https://github.com/kubernetes/kubernetes/pull/39852), welcome your review, thanks

**Comment by xingzhou** [comment]
@AdoHe, as the `kubectl create role/clusterrole` command is finished and merged, I'm going to start this ticket: `kubectl create hpa`. Please let me know if there is anything wrong.
