### ISSUE TITLE
Client ClusterConfig override should be able to totally neglect any inClusterConfig present already

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#39835]
Currently, [NewNonInteractiveDeferredLoadingClientConfig](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/clientcmd/merged_client_builder.go#L53) in the `clientcmd` [package](https://github.com/kubernetes/kubernetes/tree/master/pkg/client/unversioned/clientcmd) returns inClusterConfig if present (which is determined based on [whether there is a service account token available](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/clientcmd/client_config.go#L503)) even though an override config was specified. In most cases this is fine as the config override used by some container anyway points to the same master address as that obtained from in-cluster config (of the container's host node).

However, we require to have this override in kubemark, where we try to run a container for node-problem-detector in a pod (where the pod actually acts as a node in an overlay cluster (on top of the actual cluster) which has its own master called the kubemark master). Here's how the manifest looks like for the [node-problem-detector container](https://github.com/shyamjvs/kubernetes/blob/fix-kubemark-npd/test/kubemark/resources/hollow-node_template.json#L153). And we want the apiserver-override to work for communication with the kubemark master, even though the inClusterConfig exists and points to the real master.

cc @smarterclayton @deads2k @lavalamp @Random-Liu @kubernetes/sig-cli-misc

**Comment by shyamjvs** [comment]
Assigning you @lavalamp as git blame shows you to be the most relevant :)

**Comment by Random-Liu** [comment]
Is there a reason why we always default to in cluster config? Is there a way to disable or override it with something like kubeconfig?

**Comment by smarterclayton** [comment]
It's because originally the code had no way to detect the difference between empty config and no config, and also that kubectl originally *required* that we fall back to in cluster config due to backward compatibility.

**Comment by shyamjvs** [comment]
cc @gmarek

**Comment by shyamjvs** [comment]
Good news, there's a way to solve this problem in kubemark, which is by mouting an empty directory at the location `/var/run/secrets/kubernetes.io/serviceaccount` inside the container thus fooling the container's inClusterConfig logic. Figured it out from this related issue [#16779](https://github.com/kubernetes/kubernetes/issues/16779). And there seems to be an ongoing effort (PR [#37953](https://github.com/kubernetes/kubernetes/pull/37953)) to add an `automountServiceAccountToken *bool` field in ServiceAccount and Pod spec to do it cleanly.

However, I still feel that we should have a way to do this on the client side library also. What do you think @smarterclayton @deads2k ?

**Comment by shyamjvs** [comment]
Ref issues [#39245](https://github.com/kubernetes/kubernetes/issues/39245) and [kubernetes/node-problem-detector/#73](https://github.com/kubernetes/node-problem-detector/issues/73).

**Comment by liggitt** [comment]
If you want to load a specific kubeconfig file and not fallback to in-cluster-config, that's already possible. See https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/bootstrap.go#L149 as an example

**Comment by shyamjvs** [comment]
@liggitt That sounds perfect. Thanks for pointing to this :)
