### ISSUE TITLE
`kubectl taint` produces title-cased keys

### ISSUE THREAD

**Issue by rcoh** [kubernetes/kubernetes#39847]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): taint case lowercase

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Kubernetes version** (use `kubectl version`):
Client: 1.4.3
Server: 1.5.1

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
`kubectl taint nodes <node> egress=disabled:NoSchedule`
`kubectl get node <node> --output yaml`
The annotation was:
```
scheduler.alpha.kubernetes.io/taints: '[{"Key":"egress","Value":"disabled","Effect":"NoSchedule"}]'
```

**What you expected to happen**:
`key` `value` and `effect` should be lower case (kube 1.4 behavior)

**How to reproduce it** (as minimally and precisely as possible):
1. Launch kube 1.5.1 cluster
2. kubectl taint nodes <node> egress=disabled:NoSchedule
vs.
1. Launch kube 1.4.6 cluster
2. kubectl taint nodes <node> egress=disabled:NoSchedule

**Anything else do we need to know**:
* @liggitt 
* Relevant commit: https://github.com/kubernetes/kubernetes/commit/d5afb71cf45b21ff7a9bd8faf325870b54510e64
* Previous state: https://github.com/kubernetes/kubernetes/blob/master/docs/design/taint-toleration-dedicated.md#api

**Comment by liggitt** [comment]
are you sure you have your versions correct? the referenced commit is not in 1.6

**Comment by rcoh** [comment]
Server that displays the expected behavior:
```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"clean", BuildDate:"2016-10-16T06:36:33Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:16:27Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

Server that displays *unexpected* behavior:
```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"clean", BuildDate:"2016-10-16T06:36:33Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by liggitt** [comment]
the annotation is built client-side. are you using a kubectl built from master?
