### ISSUE TITLE
[Federation] Updating a deployment on federation with a failed RS, unbalance the RS counts on underlying clusters.

### ISSUE THREAD

**Issue by ualtinok** [kubernetes/kubernetes#39856]
**Kubernetes version** (use `kubectl version`):
1.5.1

**Environment**:
GKE

**What happened**:
Created a deployment with 6 replicas on federation cluster which has 3 underlying kube clusters. Deployment failed due to crash of container and RS stayed on CrashLoopbackOff status. Tried to re apply federation deployment with updated container version. Federation successfully changed the version and redeployed but with status of:
- cluster1: 6/6
- cluster2: 0/0
- cluster3: 0/0

**What you expected to happen**:
The balance of the RS' should have stayed 2/2 in all 3 of the underlying clusters.

**How to reproduce it** (as minimally and precisely as possible):
Create a federation cluster on top of 3 kubernetes cluster, create a deployment with 6 replicas which has a container that will crash immediately. Try to update to a new version of the container and apply deployment to federation cluster.

**Comment by quinton-hoole** [comment]
We need to verify/fix this before GA.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#94.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
