### ISSUE TITLE
Convert *extensions.Deployment to *v1beta1.Deployment fails (Kubernetes client-go)

### ISSUE THREAD

**Issue by andrejvanderzee** [kubernetes/kubernetes#39864]
With the Kubernetes client-go, how can I use Convert() for *extensions.Deployment to *v1beta1.Deployment? When I run the program below I get this error:

2017/01/12 22:40:42 failed to convert: converting (extensions.Deployment).CreationTimestamp.Time.sec to (v1beta1.Deployment).CreationTimestamp.Time.sec: Cannot set dest. (Tried to deep copy something with unexported fields?)

```package main

import (
	"log"

	_ "k8s.io/client-go/1.4/kubernetes"
	"k8s.io/client-go/1.4/pkg/api"
	"k8s.io/client-go/1.4/pkg/api/v1"
	"k8s.io/client-go/1.4/pkg/runtime"
)

const yaml = `
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: push
`

func main() {

	d := api.Codecs.UniversalDecoder()
	obj, _, err := d.Decode([]byte(yaml), nil, nil)
	if err != nil {
		log.Fatalf("could not decode yaml: %s\n%s", yaml, err)
	}

	src := obj.(*extensions.Deployment)
	s := runtime.NewScheme()
	dst := &v1beta1.Deployment{}
	err = s.Convert(src, dst, 0)
	if err != nil {
		log.Fatalf("failed to convert: %s", err)
	}
}
```

I would expect v1beta1.Convert_extensions_Deployment_To_v1beta1_Deployment() to be called and take care of unexported fields. The function is registered in main_init(), but it is not called by Convert().

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc probably not related to this issue but is client-go using standard generated conversions or does it also take into account custom conversions?

**Comment by andrejvanderzee** [comment]
I think there is a Scheme mixup (either by me or client-go). If I add the generated function myself to the scheme, it works:

`s.AddGeneratedConversionFuncs(v1.Convert_api_Service_To_v1_Service)`

**Comment by deads2k** [comment]
The scheme in client-go is stuck in an in-between state.  The staging-client-go update script isn't verified (we'll need to fix that), so it got left out of a recent refactor.  I've got https://github.com/kubernetes/kubernetes/pull/39807 in progress to try to fix it and re-collapse us.

**Comment by andrejvanderzee** [comment]
@deads2k Thanks for the update. Will this also fix the conversion of ObjectMeta for Deployments? For Services it is done correctly with a custom generated functions for CreationTimestamp.

**Comment by deads2k** [comment]
> @deads2k Thanks for the update. Will this also fix the conversion of ObjectMeta for Deployments? For Services it is done correctly with a custom generated functions for CreationTimestamp.

I'm uncertain.  I don't know for sure that it will be sufficient, but I do suspect that my change is necessary.

**Comment by caesarxuchao** [comment]
I had a PR open for verifying client-go updates: https://github.com/kubernetes/kubernetes/pull/39099.

I'll get it ready soon.

**Comment by deads2k** [comment]
> I had a PR open for verifying client-go updates: #39099.
> 
> I'll get it ready soon.

@caesarxuchao  client-go can't have a verify script enforced in the queue.  It vendors apimachinery.  API machinery is synced based on this script: https://github.com/kubernetes/apimachinery/blob/master/hack/sync-from-kubernetes.sh which happens *after* kube is committed.

Because client-go is also vendored into kube, it builds with the kube level of api machinery.  This means that if you change apimachinery in a way that requires a reaction, you'll end up stuck if you try to enforce a verify script since the API machinery change won't have a commit available to vendor.

**Comment by kargakis** [comment]
/sig apps
/sig api-machinery

@andrejvanderzee still an issue?
