### ISSUE TITLE
go4.org down failing verify-godeps.sh

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#39868]
The submit queue seems to be stuck because we can't download this `go4.org/errorutil`

```
I0113 07:09:42.190] godep v76 (linux/amd64/go1.7.4)
W0113 07:12:44.031] godep: error downloading dep (go4.org/errorutil): unrecognized import path "go4.org/errorutil"
W0113 07:13:04.320] godep: Error downloading some deps. Aborting restore and check.
W0113 07:13:04.322] + godep restore
W0113 07:14:06.435] godep: error downloading dep (go4.org/errorutil): unrecognized import path "go4.org/errorutil"
W0113 07:14:08.773] godep: Error downloading some deps. Aborting restore and check.
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-verify-master/1887

It's been down a while (10 hours since last merge).  Is there any reasonable way to skip that particular godep in the script and unblock our queue until it recovers?

@kubernetes/test-infra-maintainers @kubernetes/rh-cluster-infra @eparis @ncdc

**Comment by deads2k** [comment]
I think https://github.com/appc/spec/pull/682 will resolve the issue after its merged and we bump.

**Comment by euank** [comment]
go4.org hasn't been the most reliable source it looks like. There was also #25979

**Comment by eparis** [comment]
https://github.com/kubernetes/kubernetes/pull/39884 should hopefully get us running again while we work through changing appc/spec and updating out godep...

**Comment by euank** [comment]
go4.org is back up.

@bradfitz, do you have thoughts on the best solution here?
Should go4.org not mandate canonical import paths so packages like this one (which has no other go4 imports) could be sourced from the [github](https://github.com/camlistore/go4/) import path instead?
Should we use a repo-mirror and Is there a convenient way in Go to mirror a set of repos + hijack `godep save` / `go get` to source from that mirror?

**Comment by eparis** [comment]
honestly I think we should abandon go4 altogether. It is a curated collection of other's work. Which is great. But we're only using one of those "others". So I think we should just go to the source instead of having all this indirection.

**Comment by euank** [comment]
@eparis personally I'd love if we could abandon godep and use glide, and then the "workaround" for this would be a trivial `repo: https://github.com:camlistore/go4` to avoid hitting the go4 website.

that would also give us a somewhat-sane way to source from mirrors if we needed to in other cases (like googlecode falling over).

The real problem here isn't that we're not using the soruce of packages; the source of packages vanish too (again, a-la googlecode).
The problem is that our tool, godep, can't decouple import path from download path. The problem is that we don't' automatically mirror all repos we depend on when the dependency is added, and then use that mirror during all future builds.

Moving away from go4 is a bandaid to the insanity that is go's (lack of) package management.

**Comment by ncdc** [comment]
glide has its own set of issues, just as godep does. govendor looks more promising to me, or whatever tool ends up coming out of the official go dependency management spec that's being worked on.

**Comment by bradfitz** [comment]
> honestly I think we should abandon go4 altogether. It is a curated collection of other's work. Which is great. But we're only using one of those "others". So I think we should just go to the source instead of having all this indirection.

@eparis, I don't understand. What are you proposing?

Why doesn't Kubernetes check in its dependencies? Depending on the network seems irresponsible and lazy.

**Comment by euank** [comment]
@bradfitz we do check in our dependencies, but we also verify that the files in the godep folder match the Godeps.json and that no changes from the referenced commits were introduced therein.

**Comment by eparis** [comment]
It also prevents people from manually making changes by hand in `vendor/` which they didn't actually send through the upstream. That used to happen and developers attempted to be expedient, only to have the problem re-emerge the next time someone bumped a vendor'd file.

**Comment by bradfitz** [comment]
Okay, but is that a different CI config/column? Or do any dependency network problems affect your main build? I'd make that build config be an async thing and not block day-to-day development.

My bad for letting go4.org break (new credit card expiration date broke billing), but that shouldn't impact the submit queue.

I'd make the "checked-in-vendor-source-matches-network" validation be its own builder column that you verify is happy before releases, but doesn't block your submit queue.

**Comment by ncdc** [comment]
Good point - why do we have `hack/verify-godeps.sh` as a queue blocker? Can't we just ensure that each PR that touches Godeps.json and/or vendor doesn't break things?

**Comment by eparis** [comment]
Because tests which aren't required don't EVER get fixed. (we do already test things that make changes on a per-PR basis)

**Comment by ncdc** [comment]
I would disagree in this case. The next person to bump a Godep would find it broken (if it were).

**Comment by ixdy** [comment]
@ncdc @eparis for PRs we only run the godep checks if godeps are affected.
For CI we run the godep checks continuously, so that we don't suddenly discover breakages the next time someone touches godeps.

It might be worth pulling out the CI godep checks into a non-blocking build, though.

**Comment by ncdc** [comment]
> It might be worth pulling out the CI godep checks into a non-blocking build, though.

If we do that, I agree @eparis is likely correct that nobody would notice and nobody would fix. I'm suggesting we only ever test godep per PR, if said PR touches it.

**Comment by ixdy** [comment]
@ncdc I'm pretty we do that, but I haven't checked recently.

**Comment by eparis** [comment]
@ncdc I'd feel really sorry for the poor dev that just wants to update a godep and has to deal with 6 months of random breakage from other upstreams :-(

**Comment by ncdc** [comment]
My complaint is actually about transient flakes that result in `hack/verify-godeps.sh` failing, which means the entire queue is blocked. If we could recognize these transient flakes and not block the queue, I would be happy.

**Comment by bradfitz** [comment]
I like the idea of having `hack/verify-godeps.sh` only run if the PR touches a godep file or vendor/** file, but otherwise making it required.

**Comment by eparis** [comment]
@ncdc but when the don't block they don't get fixed. So they are going to build until the poor guy comes along and touches godep. Then he's going to have a bunch of other things he has to do before he can do his job. I get it, we'll live, I just feel sorry for whomever that is.

**Comment by bradfitz** [comment]
@eparis, but what if they only block the queue for PRs that touch that part of the world, but for people hacking outside of the vendor tree or godep file(s), it doesn't ever run or block people?

**Comment by ncdc** [comment]
I don't think it's fair that the community/queue be penalized when there is a flake verifying godeps. If it's a flake (e.g. couldn't connect to host x), there's often nothing we can do until the cause of the flake is resolved externally.
