### ISSUE TITLE
Kubelet won't start > cannot open store: Error

### ISSUE THREAD

**Issue by davidcomeyne** [kubernetes/kubernetes#39866]
Hi all,

I searched Google and a lot of forums for an answer but I can't seem to find one. The problem is that my kubelet on a kubernetes-minion will not start.
$ systemctl start kubelet

I'm not really sure if it is a bug or just some misconfig from my part, but here it is:

**Kubernetes version**:
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**HW config:**
64-bit Intel(R) Xeon(R) CPU E3-1268L v3 @ 2.30GHz
8 vCPU's
32 G RAM
**OS:** CoreOS 1235.4.0
**Kernel:**
Linux arlette06 4.7.3-coreos-r1 #1 SMP Wed Jan 4 03:46:16 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E3-1268L v3 @ 2.30GHz GenuineIntel GNU/Linux

Here is an extract of the journalctl:
```
-- Unit kubelet.service has finished starting up.
-- 
-- The start-up result is done.
Jan 13 12:07:04 arlette06 kubelet-wrapper[25293]: KUBELET_VERSION environment variable is deprecated, please use KUBELET_IMAGE_TAG instead
Jan 13 12:07:04 arlette06 kubelet-wrapper[25293]: + exec /usr/bin/rkt run --trust-keys-from-https --volume etc-kubernetes,kind=host,source=/etc/kubernetes,readOnly=false --volume etc-ssl-certs,kind=host,source=/
Jan 13 12:07:04 arlette06 kubelet-wrapper[25293]: run: cannot open store: Error, off: 0x80, EOF
Jan 13 12:07:04 arlette06 systemd[1]: kubelet.service: Main process exited, code=exited, status=254/n/a
Jan 13 12:07:04 arlette06 systemd[1]: kubelet.service: Unit entered failed state.
Jan 13 12:07:04 arlette06 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jan 13 12:07:05 arlette06 systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
-- Subject: Unit kubelet.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has finished shutting down.
```

Any ideas? And thanks in advance for helping me sort this out...

**Comment by davidcomeyne** [comment]
I wasn't able to solve this, after reinstalling the nodes it worked.

**Comment by johscheuer** [comment]
@davidcomeyne we currently had the same issue:
```bash
cat /etc/os-release 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1520.7.0
VERSION_ID=1520.7.0
BUILD_ID=2017-10-24-0407
PRETTY_NAME="Container Linux by CoreOS 1520.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

```bash
rkt version
rkt Version: 1.28.1
appc Version: 0.8.10
Go Version: go1.7.6
Go OS/Arch: linux/amd64
Features: -TPM +SDJOURNAL
```

The solution was to delete the `/var/lib/rkt/cas/db/ql.db` and restart the process.

**Comment by davidcomeyne** [comment]
Thanks @johscheuer, hopefully this can help others in the future!
