### ISSUE TITLE
Change the RateLimiter interface to provide an error message if CanAccept is not true

### ISSUE THREAD

**Issue by satnam6502** [kubernetes/kubernetes#3987]
@bgrant0607 pointed out that the `CanAccept()` behavior should be to return an error message rather than a bool and then some code can be factored out rather than appear at the call site.
@brendanburns

**Comment by bgrant0607** [comment]
I want to see something like:
```
if err := rl.CanAccept(); err == nil {
...
}
...
fmt.Fprintf(w, "Exceeded rate limit: %v", err)
```
where the error message returned says what the rate/burst limits are (if applicable).

**Comment by satnam6502** [comment]
@jbeda points out:
```
We won't have access to the flags here. Instead, we should ask the rate limiter to describe itself and post that into the response, perhaps?
```

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc
