### ISSUE TITLE
Node Name is not unique; prefer UID to avoid race conditions / facilitate caching?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#39893]
Node Names can be reused.  On AWS with bigger clusters, they can be reused within the space of a few minutes.

There are a few places where we use Node Names, where I believe it would be safer to use a Node UID.  As well as the potential race conditions, use of a non-unique identifier makes caching much harder / more dangerous.

* In the volume controller and cloudprovider calls (I'm looking into this one)
* In the scheduler, I believe we assign a pod to a node using only a node name.  So if a replacement node comes up with the same name and the pod has not been destroyed, it will run on a different node than the scheduler intended.

Is there anything mitigating the scheduler risk, other than timing arguments?  (I do think it is unlikely in practice).

I am thinking about where we have a NodeName, passing a pair (struct) of Name and UID instead.

cc @saad-ali @jingxu97 @gnufied for volumes

Not sure who to cc for scheduler!

**Comment by k82cn** [comment]
Name + UID seems a solution for re-used Node. And it seems we did not unbind Pod from the Node in scheduler; that'll make Pod un-schedulable.

**Comment by davidopp** [comment]
@k82cn I'm pretty sure we do have code that deletes pods from deleted nodes, either in the garbage collector controller or the node controller. @wojtek-t and @gmarek would know for sure. But I think it runs periodically, so if you remove a node's VM and re-create it fast enough with the same name, it's considered the same node. That has some advantages but is probably more confusing than beneficial.

I think @justinsb has a good point here but am interested in @wojtek-t and @gmarek opinion...

**Comment by k82cn** [comment]
thanks :). Yes, those pods are deleted by gc controller at `gcOrphaned`, running periodically every 20 sec.

**Comment by gmarek** [comment]
It only deletes if cloud provider will tell us that the Node is gone. This is done in a polling loop, so if something recreates a Node with the same name very quickly then we'll just assume it's fine, and just put all Pods we think belong there.

That being said, I don't think any reason why using UIDs would be a bad idea in general. I'm only slightly afraid of making the change, as bug in it might have some serious implications.

**Comment by liggitt** [comment]
> That being said, I don't think any reason why using UIDs would be a bad idea in general. I'm only slightly afraid of making the change, as bug in it might have some serious implications.

We reference nodes in the API using name, not uid, which means anything that needs to form this fully-qualified type will be doing node lookups to get the UID (which defeats the purpose of making it detect node deletion/recreation, right?)

**Comment by jingxu97** [comment]
This issue is related to a problem on storage.
When a node is terminated, the volumes attached to that node will be in detached immediately. However, the volume manager on master node will not notice this change and will continue to use the outdated information if the node comes back very soon. 
Because of this issue, we add periodic checking on cloud provider to see whether the volumes are still attached every 5 second by default. But the overhead for this checking is too high especially for AWS cluster.
I think if node UID is used, this issue will not exist.

**Comment by gmarek** [comment]
We may add a NodeUID field to PodSpec, which will take precedence over PodName if set - Kubelet can l watch for NodeName for the time being and just ignore things that have not matching NodeUID set.

**Comment by gmarek** [comment]
Note that I still assume that there can't be two Nodes with the same name and different UIDs in the same time.

**Comment by liggitt** [comment]
> We may add a NodeUID field to PodSpec, which will take precedence over PodName if set - Kubelet can l watch for NodeName for the time being and just ignore things that have not matching NodeUID set.

I'd expect it to further narrow the node match... nodeName AND nodeUID would have to match. Would need to decide what happens to pods in the API that reference a nodeUID that mismatches... probably the same thing that happens to pods referencing a missing nodeName (whatever that is)

**Comment by davidopp** [comment]
> I'd expect it to further narrow the node match... nodeName AND nodeUID would have to match. 

If there is only ever one object with a given name (at a given time) then this doesn't seem necessary. The approach @gmarek suggested sems OK -- use UID if it's provided, otherwise use name. Again, this assumes there is only ever one object with a given name (at a given time), but I think we have to assume that anyway based on how things are stored in etcd.

**Comment by smarterclayton** [comment]
If we need to ensure that all pods are cleaned up before a node is deleted we can do that with graceful deletion and have the gc controller handle that case as a finalizer on the node.

**Comment by davidopp** [comment]
ref/ #38988
