### ISSUE TITLE
planet.kubernetes.io has no content

### ISSUE THREAD

**Issue by fabiand** [kubernetes/kubernetes#39892]
A Kubernetes planetplanet/venus instance would be great.

Are there plans to bring planet.kubernetes.io to life?

**Comment by calebamiles** [comment]
**cc: @kubernetes/sig-docs-misc**

**Comment by fabiand** [comment]
I'd be willing to contribute to get the planet up and rolling

**Comment by mattfarina** [comment]
@fabiand what do you need to get it started? What are you thinking?

**Comment by jberkus** [comment]
I'm not sure which SIG would own a Planet.  I'll ask.

**Comment by fabiand** [comment]
- [ ] Place to put the aggregator (planetplanet)
- [ ] Support on making up the right theme
- [ ] Repo to keep the sources
- [ ] Decide on how the list of feeds is maintained (repo?)

I think that's about it

**Comment by idvoretskyi** [comment]
cc @thockin

**Comment by jberkus** [comment]
Well, the big thing is that we need a SIG or WG to be responsible for post policy and what feeds are in the planet.

**Comment by idvoretskyi** [comment]
I hope, CNCF may support this from the marketing side.

cc @dankohn

**Comment by fabiand** [comment]
In Fedora we have a planet as well - I could look at the policy we have there and see if I can somehow clean it and provide it as input here.

**Comment by idvoretskyi** [comment]
@fabiand good idea
