### ISSUE TITLE
Enhance e2e tests to track CloudProvider's API quotas

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#39909]
CloudProvider APIs can be precious commodity and kubernetes should be a good citizen which doesn't blow up the API quota where it could have been avoided.

To this end - I am thinking we should enhance e2e tests to cover, how many API calls are being made for particular test and set some expectations around that. Obviously creation of certain resources means - we have to retry something repeatedly , so the checks and balances we put in place should take into account of that.

This will ensure that any internal refactoring or redesign still adheres to certain expectations of API quotas.

cc @childsb @saad-ali @justinsb @jsafrane @kubernetes/sig-storage-misc

**Comment by jingxu97** [comment]
@gnufied is there a plan to work on it?
