### ISSUE TITLE
Pod level QoS: Top level qos containers limits are not updated 

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#39913]
Currently when new pod is created, top level QoS containers limits are not updated (e.g. values in `BestEffort/memory.limit_in_bytes`, `/Burstable/memory.limit_in_bytes` etc). 

This blocks features which try to use pod level QoS values to make decision.

I am also thinking caching top level QoS data in container manager, and update the cache every time new pod comes. (so we can re-use these data in kubelet)

Kindly ping @derekwaynecarr, your ideas or plan regarding to this issue are really valued here.

More details: [check this part of code](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/pod_container_manager_linux.go#L86-L94)

**Comment by davidopp** [comment]
cc/ @kubernetes/sig-node-misc

**Comment by vishh** [comment]
@resouer 

1. Let's keep Pod level cgroups discussion to #27204. It is difficult to track many issues on the same topic.
2. We do not plan on updating top level cgroups as of now. Let's first complete and roll out pod level cgroups and the overall cgroup hierarchies. There is no urgent need to update top level cgroups. 

Can we move this discussion back to #27204?

**Comment by resouer** [comment]
@vishh Thanks for reminding. Close this one.
