### ISSUE TITLE
Lack of feature to run interactive mode from private docker image

### ISSUE THREAD

**Issue by linehrr** [kubernetes/kubernetes#39920]
kubectl can create docker secrets and also specify those secrets in deployment or pod in json/yaml file by ```imagePullSecrets: xxx```

however there seems to be no way to run image in interactive mode when image is hosted in private docker repo.
e.g.
```
kubectl run -it --image=<private image> 
```
but ```kubectl run``` does not have option to specify imagePullSecrets.

**Comment by gekart** [comment]
```kubectl run -it --image=<private image> --image-pull-secrets=<secret>```

would be really handy.
