### ISSUE TITLE
failed to run unit test locally

### ISSUE THREAD

**Issue by AdoHe** [kubernetes/kubernetes#39922]
Fyi. I can't use `make test WHAT=pkg/kubectl` to run unit tests locally anymore. @deads2k I believe this has something related with your latest change to `hack/make-rules/test.sh`, ptal.

**Comment by k82cn** [comment]
is the output similar with #39840 ? Would you try PR #39859 ?

**Comment by AdoHe** [comment]
nope, not the same issue.

**Comment by kargakis** [comment]
You need to use relative paths now which is unfortunate. Try `make test WHAT=./pkg/kubectl`

**Comment by k82cn** [comment]
@AdoHe , @kargakis is right; or you can run with full path `make check WHAT=k8s.io/kubernetes/plugin/pkg/scheduler/schedulercache KUBE_COVER=y` .

**Comment by AdoHe** [comment]
Ok, I will try this

**Comment by lavalamp** [comment]
Or you can use `WHAT=./pkg/kubectl`.
