### ISSUE TITLE
It is ambiguous when connect to apiserver with http1.1/http2/spdy3.1.

### ISSUE THREAD

**Issue by choury** [kubernetes/kubernetes#39940]
**Kubernetes version**
kubernetes 1.5.2

When using api of  https, it provies the protocols as follow by npn:
* h2
* http/1.1
* h2-14

And if I request the exec api with http2:

< HTTP/2 400 
< content-type: application/json
< content-length: 167
< date: Mon, 16 Jan 2017 09:27:14 GMT
< 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Upgrade request required",
  "reason": "BadRequest",
  "code": 400
}
It will also failed regardless add header of upgrading to spdy or http2.

I can succeed only if I am using http1.1 and want to upgrade to spdy3.1 while not http2:
> GET /api/v1/namespaces/default/pods/web-0/exec?container=nginx&command=ls HTTP/1.1
> Host: xxx.xxx.xxx
> User-Agent: curl/7.51.0-DEV
> Accept: */*
> Connection: Upgrade
> Upgrade: SPDY/3.1
> 
< HTTP/1.1 101 Switching Protocols
< Connection: Upgrade
< Upgrade: SPDY/3.1
< Date: Mon, 16 Jan 2017 09:33:00 GMT

I think it is ambiguous when someone else want to use this api.

**Comment by smarterclayton** [comment]
Yes, exec only supports upgrading to SPDY or Websockets.

**Comment by choury** [comment]
But it provides a wrong npn protocol list.
