### ISSUE TITLE
Node Label are lost when instances are shutdown

### ISSUE THREAD

**Issue by alfirin** [kubernetes/kubernetes#39941]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
This is a BUG REPORT

**Kubernetes version**:
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS**: Debian GNU/Linux 8 (jessie)
- **Kernel**: `Linux ip-10-48-255-52 4.4.26-k8s #1 SMP Fri Oct 21 05:21:13 UTC 2016 x86_64 GNU/Linux`

**What happened**:
We applied some custom labels with this command: `kubectl label nodes NODE_NAME server-type=server-type-1`.
Then this machine (node) has been shut down.
The auto-scaling group detected that the machine was not here anymore, so it created a new instance (new node).
The new instance didn't have the label anymore.

Before the command `kubectl get nodes --show-labels` returned:
```
...
NODE_NAME  Ready          3d        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t2.medium,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=eu-west-1,failure-domain.beta.kubernetes.io/zone=eu-west-1c,kubernetes.io/hostname=HOST_NAME,server-type=server-type-1
...
```

But after the restart, the command returned:
```
...
NEW_NODE_NAME  Ready          3d        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t2.medium,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=eu-west-1,failure-domain.beta.kubernetes.io/zone=eu-west-1c,kubernetes.io/hostname=NEW_HOST_NAME
...
```

**What you expected to happen**:
When the instance (node) is recreated, we want the same labels that the previous applied to the new instance.

**How to reproduce it** (as minimally and precisely as possible):

1. Put a label to one node of your cluster with: `kubectl label nodes NODE_NAME server-type=server-type-1`
2. Shut down the instance and recreate a new one
3. Do a `kubectl get nodes --show-labels`

**Comment by justinsb** [comment]
Is this with kops?  And when you say "Shut down the instance and recreate a new one", are you forcing it to get the same name?  Without meaning to get too "ship of theseus" - what is it that makes the new instance the same as the old instance?

**Comment by resouer** [comment]
The new node in this case is actually a different node. (and the node name has been changed, right?). Labels will be preserved only if you are registering an existing node.  

But I can see that you are using NODE_NAME. Why do you need this? Why don't just give a name to every node? And re-use this name when re-create the node.

**Comment by alfirin** [comment]
@justinsb I am using kops and I don't see inside kops how to set the name of new machine.
In fact the new instance should be the same, because the auto-scaling group just create a new instance (because the previous one was shutdown).

**Comment by alfirin** [comment]
@resouer Yes it's actually a different node, but replacing the previous shutdown node by auto-scaling group.
So in AWS auto-scaling group (or kops), how do I put some names for my nodes when they are created dynamically ?

**Comment by justinsb** [comment]
I don't understand why you want them to be the same instance.  Can you describe what you're actually trying to do?  And do you know that kops can apply labels based on the instance group: https://github.com/kubernetes/kops/blob/master/docs/labels.md  Does that address the underlying requirement?

**Comment by alfirin** [comment]
@justinsb We to created different instance group.
We just had to shut-down every instances.
Because `kops rolling-update cluster --name <clustername> --yes ` does not apply the labels to the existing nodes.

That was a kops problem.

Thanks a lot for your help guys.

PS I will check or create a new kops issue.
