### ISSUE TITLE
Heapster in Kubemark doesn't work

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#39952]
Similar to issue #39245 .
Heapster seems to talk to the wrong apiserver (the one of the real cluster) instead of the kubemark apiserver.
To fix this, we need to replace the heapster image with a newer one (where this [change](https://github.com/kubernetes/heapster/pull/1468) has been incorporated).
One other (minor) thing is to bind the right role to heapster for RBAC.

cc @kubernetes/sig-scalability-misc @wojtek-t @gmarek

**Comment by wojtek-t** [comment]
I think this must be relatively recent regression. When I filed the issue for NodeProblemDetector, heapster was working fine.

**Comment by wojtek-t** [comment]
Can this: https://github.com/kubernetes/kubernetes/pull/39801 be a reason?

**Comment by shyamjvs** [comment]
This is weird, because I just rebased my master (since I didn't have this change updated in my working tree till now) and now it works. IIUC Given that #39801 was merged only 4 days ago, this should either mean that it wasn't working previously (with "v1.2.0") or someone overwrote a working v1.2.0 image with an image where the `--source` flag doesn't work. Am I going wrong somewhere?

**Comment by shyamjvs** [comment]
And before closing this issue, we also need to fix RBAC for heapster.

**Comment by shyamjvs** [comment]
@deads2k We get many such log statements in the kubemark apiserver:
```
I0117 10:37:26.910620       8 rbac.go:49] RBAC DENY: user "kubelet" groups [system:nodes system:authenticated] cannot "list" on "namespaces./"
I0117 10:37:26.910681       8 panics.go:75] GET /api/v1/namespaces?resourceVersion=0: (280.189<C2><B5>s) 403 [[heapster/v0.0.0 (linux/amd64) kubernetes/$Format] 104.155.134.152:57821]
```
As you can see, we are currently using the same credentials as kubelet for heapster in kubemark, and should actually have a separate role crafted for heapster IIUC.

**Comment by wojtek-t** [comment]
Actually it's not that heapster doesn't work in kubemark. It just cannot list namespaces. All other requests is issues successfully. We should just fix this one.

**Comment by deads2k** [comment]
> Actually it's not that heapster doesn't work in kubemark. It just cannot list namespaces. All other requests is issues successfully. We should just fix this one.

Heapster should be using a separate identity.  That would produce even more log statements initially, but we'll be able to tailor a role.  kubelets can do lots of things that heapster shouldn't do (view all secrets, update node status, etc), so we need a separate role and you need a different identity.

If you can do the identity first, we'll be able to use the RBAC denies to build the correct role.

**Comment by shyamjvs** [comment]
Yes I agree. That is the way how the roles should be crafted. For now, I'm sending a PR which gives heapster the 'cluster-admin' role. But here is the answer to your question @deads2k :
-> heapster should be able to "list" on "nodes", "pods" and "namespaces"

**Comment by shyamjvs** [comment]
Will fix the role for heapster, and not just this but even other components like node-problem-detector, and any other component which faces RBAC DENYs in a later PR.
For now, let me start an umbrella issue for updating roles throughout kubemark that'll keep track of these.
And also another issue for RBAC to add roles for these componenets. SGTY?

**Comment by deads2k** [comment]
> For now, let me start an umbrella issue for updating roles throughout kubemark that'll keep track of these.
> And also another issue for RBAC to add roles for these componenets. SGTY?

I'm ok with that.  Separate identities for clean RBAC denies will make creating the roles a lot easier.  We did that for the GCE tests to get the initial roles.
