### ISSUE TITLE
kubemark consistently failing

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#39959]
kubemark is consistently failing and blocking the SQ.  It looks to have started very recently.

One message is suspicious in the log: `RBAC DENY: user "kubelet" groups [system:nodes system:authenticated] cannot "list" on "endpoints./" cluster-wide`.  That permission is normally granted in the `system:node-proxier`  role, bound by default to the `system:kube-proxy` user.  Is the user different in kubemark?

@kubernetes/test-infra-maintainers

**Comment by deads2k** [comment]
@shyamjvs @gmarek @wojtek-t https://github.com/kubernetes/kubernetes/pull/39349 merged a while back.  Did something else change recently.  Nothing should have been able to merge for kubelet needing the new permission without failing.

**Comment by deads2k** [comment]
Given that its just kubemark, I'm wondering if its something related the fake kubelets and the like that are set up.

**Comment by shyamjvs** [comment]
@deads2k This seems to be because in kubemark the kube-proxy actually uses the same kubeconfig as that of the kubelet. So it pretty much ends up with the same binding as the kubelet (with the role of system:node). Making kube-proxy identify itself as the `system:kube-proxy` user should do the trick.

**Comment by wojtek-t** [comment]
So I took a look and let me clarify one thing - the failures from yesterday are NOT related to RBAC.
So we are basically talking about two failures:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/1699
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/1700

Both of those are actually timeouts.
However, in both cases, the tests finished after ~45 minutes, and then the kubemark + real cluster weren't able to tear down within the next half an hour.

Logs in both failure look pretty much the same, so pasting from the one run:
```
I0116 06:29:10.085] [1m[32mRan 2 of 494 Specs in 1956.335 seconds[0m
I0116 06:29:10.088] [1m[32mSUCCESS![0m -- [32m[1m2 Passed[0m | [91m[1m0 Failed[0m | [33m[1m0 Pending[0m | [36m[1m492 Skipped[0m PASS
I0116 06:29:10.127] 
I0116 06:29:10.127] Ginkgo ran 1 suite in 32m36.682098437s
I0116 06:29:10.127] Test Suite Passed
W0116 06:29:10.228] 2017/01/16 06:29:10 e2e.go:948: Step './hack/ginkgo-e2e.sh --e2e-verify-service-account=false --dump-logs-on-failure=false --ginkgo.focus=\[Feature:Performance\] --gather-resource-usage=true --garbage-collector-enabled=true' finished in 32m37.40031349s
W0116 06:29:10.228] 2017/01/16 06:29:10 e2e.go:948: Step './test/kubemark/run-e2e-tests.sh --ginkgo.focus=\[Feature:Performance\] --gather-resource-usage=true --garbage-collector-enabled=true' finished in 32m39.70214158s
W0116 06:29:10.228] 2017/01/16 06:29:10 e2e.go:946: Running: ./test/kubemark/stop-kubemark.sh
W0116 06:40:43.050] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jenkins-blocking-kubemark/zones/us-central1-f/instances/kubemark-500-kubemark-master].
W0116 06:40:50.649] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jenkins-blocking-kubemark/zones/us-central1-f/disks/kubemark-500-kubemark-master-pd].
W0116 06:40:58.837] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jenkins-blocking-kubemark/regions/us-central1/addresses/kubemark-500-kubemark-master-ip].
W0116 06:41:25.530] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jenkins-blocking-kubemark/global/firewalls/kubemark-500-kubemark-master-https].
W0116 06:41:25.574] 2017/01/16 06:41:25 e2e.go:948: Step './test/kubemark/stop-kubemark.sh' finished in 12m15.439849387s
...
...
I0116 06:44:24.914] Removing etcd replica, name: kubemark-500-master, port: 2379, result: 0
I0116 06:44:25.921] Removing etcd replica, name: kubemark-500-master, port: 4002, result: 0
W0116 06:44:32.124] Updated [https://www.googleapis.com/compute/v1/projects/k8s-jenkins-blocking-kubemark/zones/us-central1-f/instances/kubemark-500-master].
W0116 06:55:38.674] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jenkins-blocking-kubemark/zones/us-central1-f/instances/kubemark-500-master].
W0116 06:55:51.272] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jenkins-blocking-kubemark/global/firewalls/kubemark-500-master-https].
W0116 06:55:57.328] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jenkins-blocking-kubemark/global/firewalls/kubemark-500-minion-all].
...
```

So there are two periods of ~10 minutes each where pretty much nothing was happening. Looking on the logs, it seems that it took ~10 minutes to delete GCE VMs for master machines (kubemark and real cluster).
So to me it seems like the GCE hiccup around that time

And if we substract these 20 minutes from the time execution of these two tests, we get 55m, which is the usual time to run the test.

So the only thing we can do is to consider bumping timeout for the tests. Not sure if this is a good option though...

**Comment by shyamjvs** [comment]
Maybe bumping the timeout might not be a good option (unless the failures happen too often) as it gives us the chance to notice different issues than can cause the tests to timeout.

**Comment by wojtek-t** [comment]
That's why I wrote ```Not sure if this is a good option though...```

**Comment by deads2k** [comment]
closing since this was a flake, not a consistent rbac problem.
