### ISSUE TITLE
Need tests for replicaset pod adoption and release

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#39962]
The merge queue is green with RBAC enabled, and the replicaset controller was missing permission to patch pods until fixed in https://github.com/kubernetes/kubernetes/pull/39961

Pod adoption and release depend on patching pods, which means that there are no merge-queue-blocking tests that test these features.

Given that they are complex and rarely tested manually, we need tests that run as part of the merge queue to ensure they function correctly.

**Comment by fgimenez** [comment]
I'd like to work on this, @liggitt where should the tests be added? I see that there are some patch-related tests for the replicaset controller in https://github.com/kubernetes/kubernetes/blob/master/test/integration/replicaset/replicaset_test.go, and, according to http://submit-queue.k8s.io/#/info, the integration tests are run as part of the merge queue, is that correct?

Thanks!

**Comment by liggitt** [comment]
I think we'd want an e2e test that drives behavior externally on a normal cluster (by creating a replicaset, waiting to observe expected pods, modifies replicaset, waits to observe expected results, etc) . many of the integration tests tend to start up fake servers that don't share much in common with real deployments.

**Comment by fgimenez** [comment]
Ok thanks, on it.

**Comment by kargakis** [comment]
cc: @caesarxuchao @krmayankk
