### ISSUE TITLE
Failed to setup provider config

### ISSUE THREAD

**Issue by juanvallejo** [kubernetes/kubernetes#39973]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
v1.6.0-alpha.0.3307+a29c51c6abf231

**What happened**:
e2e gce test flake

Jan 16 11:38:02.344: Failed to setup provider config: Error building GCE/GKE provider: googleapi: Error 500: Internal Error, internalError

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/39042/pull-kubernetes-e2e-gce-gci/12804/

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/39042/pull-kubernetes-e2e-gce-gci/12804/?log#log

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
/area platform/gce
since we lack a sig-gcp at the moment

/assign
closing because these artifacts are no longer available, please reopen if this happens again
