### ISSUE TITLE
Make go2idl binaries generic

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#39979]
Currently it appears that you have to cargo-cult in your own set of the binaries under `cmd/lib/go2idl`.  It would be much more convenient if these binaries were generic and consumable via `go get` in other projects.  It doesn't appear that this should be especially hard to do; looks like a couple things need to be rippled out into CLI options like names of packages and path to boilerplate header file.

I think I (or someone else from SIG service-catalog) can probably tackle this; creating this issue so:

1.  It doesn't get lost
2.  Someone from @kubernetes/sig-api-machinery-misc can tell us if there's a better way

**Comment by pmorie** [comment]
cc @deads2k @lavalamp

**Comment by smarterclayton** [comment]
For simple things, why would cargo culting those options be bad?  They should *all* support customization of the defaults (set those defaults prior to call flag.Parse).

**Comment by lavalamp** [comment]
I would like these to be fully reusable setting only command line options
but I don't have time to fix them, unfortunately.
