### ISSUE TITLE
"server misbehaving" error /  kube-dns returning  SERVFAIL

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#39980]
I'm not entirely sure what is happening here, but I've seen this error reported in the real world a few times, and could never figure out what it was.  And then today I installed guestbook-go, and deleted the redis-slave service.

The browser then reports this error (in the network view) when fetching `/lrange/guestbook`

```
PANIC: dial tcp: lookup redis-slave on 100.64.0.10:53: server misbehaving
goroutine 3034 [running]:
github.com/codegangsta/negroni.(*Recovery).ServeHTTP.func1(0x7f3e74c77a90, 0xc820284940, 0xc8200acde0)
	/go/src/github.com/codegangsta/negroni/recovery.go:34 +0xe9
panic(0x7a8c60, 0xc8203fa500)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
main.HandleError(0x6e2780, 0xc820439640, 0x7f3e74c77d40, 0xc8203fa500, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/examples/guestbook-go/_src/main.go:71 +0x59
main.ListRangeHandler(0x7f3e74c77a90, 0xc820284940, 0xc820428c40)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/examples/guestbook-go/_src/main.go:38 +0x187
net/http.HandlerFunc.ServeHTTP(0x8a8278, 0x7f3e74c77a90, 0xc820284940, 0xc820428c40)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82000e4b0, 0x7f3e74c77a90, 0xc820284940, 0xc820428c40)
	/go/src/github.com/gorilla/mux/mux.go:103 +0x270
github.com/codegangsta/negroni.Wrap.func1(0x7f3e74c77a90, 0xc820284940, 0xc820428c40, 0xc8204388e0)
	/go/src/github.com/codegangsta/negroni/negroni.go:41 +0x50
github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc8200ace80, 0x7f3e74c77a90, 0xc820284940, 0xc820428c40, 0xc8204388e0)
	/go/src/github.com/codegangsta/negroni/negroni.go:24 +0x44
github.com/codegangsta/negroni.middleware.ServeHTTP(0x7f3e74c76780, 0xc8200ace80, 0xc8200acf00, 0x7f3e74c77a90, 0xc820284940, 0xc820428c40)
	/go/src/github.com/codegangsta/negroni/negroni.go:33 +0xaa
github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7f3e74c77a90, 0xc820284940, 0xc820428c40)
	/go/src/github.com/codegangsta/negroni/negroni.go:33 +0x53
github.com/codegangsta/negroni.(*Static).ServeHTTP(0xc820013aa0, 0x7f3e74c77a90, 0xc820284940, 0xc820428c40, 0xc820438800)
	/go/src/github.com/codegangsta/negroni/static.go:49 +0x2e0
github.com/codegangsta/negroni.middleware.ServeHTTP(0x7f3e74c76758, 0xc820013aa0, 0xc8200acee0, 0x7f3e74c77a90, 0xc820284940, 0xc820428c40)
	/go/src/github.com/codegangsta/negroni/negroni.go:33 +0xaa
github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7f3e74c77a90, 0xc820284940, 0xc820428c40)
	/go/src/github.com/codegangsta/negroni/negroni.go:33 +0x53
github.com/codegangsta/negroni.(*Logger).ServeHTTP(0xc820022080, 0x7f3e74c77a90, 0xc820284940, 0xc820428c40, 0xc8204387c0)
	/go/src/github.com/codegangsta/negroni/logger.go:25 +0x1f4
github.com/codegangsta/negroni.middleware.ServeHTTP(0x7f3e74c76730, 0xc820022080, 0xc8200acec0, 0x7f3e74c77a90, 0xc820284940, 0xc820428c40)
	/go/src/github.com/codegangsta/negroni/negroni.go:33 +0xaa
github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7f3e74c77a90, 0xc820284940, 0xc820428c40)
	/go/src/github.com/codegangsta/negroni/negroni.go:33 +0x53
github.com/codegangsta/negroni.(*Recovery).ServeHTTP(0xc8200acde0, 0x7f3e74c77a90, 0xc820284940, 0xc820428c40, 0xc820438760)
	/go/src/github.com/codegangsta/negroni/recovery.go:45 +0x75
github.com/codegangsta/negroni.middleware.ServeHTTP(0x7f3e74c76708, 0xc8200acde0, 0xc8200acea0, 0x7f3e74c77a90, 0xc820284940, 0xc820428c40)
	/go/src/github.com/codegangsta/negroni/negroni.go:33 +0xaa
github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc820013b00, 0x7f3e74c779f8, 0xc820052340, 0xc820428c40)
	/go/src/github.com/codegangsta/negroni/negroni.go:73 +0x122
net/http.serverHandler.ServeHTTP(0xc82006c500, 0x7f3e74c779f8, 0xc820052340, 0xc820428c40)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820434680)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
```

I would expect to see a more sensible error.

One possible reason:  when I `kubectl exec` into the redis-master pod, and `apt-get install dnsutils`, I can see:

```
dig redis-slave

; <<>> DiG 9.9.5-9+deb8u9-Debian <<>> redis-slave
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 35084
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;redis-slave.                   IN      A

;; Query time: 3 msec
;; SERVER: 100.64.0.10#53(100.64.0.10)
;; WHEN: Tue Jan 17 00:25:23 UTC 2017
;; MSG SIZE  rcvd: 29

```

All the other suffixes from /etc/resolv.conf gives the expected NXDOMAIN

e.g. 

```
dig redis-slave.svc.cluster.local

; <<>> DiG 9.9.5-9+deb8u9-Debian <<>> redis-slave.svc.cluster.local
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 31169
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
```

But I am wondering if, when they all fail to resolve, go "chooses" the SERVFAIL error?

**Comment by jaimemartinez88** [comment]
This happened to me when the DNS couldn't resolve the name. You can see in the error message
 dial tcp: lookup redis-slave on 100.64.0.10:53: server misbehaving

Port 53 is the DNS so it's basically telling you that it couldn't find "redis-slave". For some reason Go likes to say "server misbehaving" instead of a more descriptive error message.

**Comment by bowei** [comment]
@justinsb  -- do you know if the query that is being sent is with the search path or not? It looks from the `dig` command that the SERVFAIL is for a query of `redis-slave.`

**Comment by justinsb** [comment]
It's been a long time, but just re-reading what I wrote, `redis-slave.` => SERVFAIL, queries with any suffix gives NXDOMAIN.  But it looks like go chooses to surface SERVFAIL.

If this isn't what happens any more, or if go changed which error it surfaces, we can close.  This is guestbook-go, so easy to experiment with :-)

**Comment by kailashverma2402** [comment]
I am also getting the same issue : 
Unable to connect to the server: dial tcp: lookup api.dev.abc.ioon x.x.x.x:xx  : server misbehaving

**Comment by zelentsovl** [comment]
I have the same problem. Command kubectl exec gives "Error from server: error dialing backend: dial tcp: lookup kubeworker on x.x.x.x:53: server misbehaving". I've tried to add search domain.com, cluster.local to the network manager config, y.y.y.y kubeworker - to /etc/hosts on all nodes. No success.

**Comment by zelentsovl** [comment]
I've solved the problem! Some details: it's appeared after the cluster was been expanded with 2 new workers. For some reasons Kubernetes could not find them in DNS. The problem has been resolved jyst rebooting kubemaster nodes.

**Comment by GeorgFleig** [comment]
@zelentsovl I also have the same issue every time I add a new node to the cluster. Having to restart the master node is quite annoying but works. I finally found a solution without having to restart. For me it helped to update the `/etc/hosts` file inside the kube-apiserver pod. It seems that this also happens automatically after a node restart.

In my example node1 is the master and node5 the newly added node:
> kubectl --namespace kube-system exec -it kube-apiserver-node1

And inside the pod do

> echo "192.168.0.123 node5 node5.cluster.local" >> /etc/hosts

**Comment by sixcorners** [comment]
I'm using k3s which uses coredns. This error happens to me when I'm running my cluster with ipv6 available and configured on the node.

If I look at the coredns logs I see lots of stuff like
`[ERROR] plugin/errors: 2 www.google.com. A: dial udp [2606:4700:4700::1111]:53: connect: network is unreachable
`

**Comment by jayunit100** [comment]
so, i just saw this and it was i. think because my kubeconfig was corrupted / incomplete. ...
