### ISSUE TITLE
enable kubectl tests with federation apiserver for deployments

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#39985]
#38844 added kubectl tests with federation apiserver, but did not enable them for deployments since they were failing. We need to debug the issue, fix it and then enable the tests for deployments.

Here is the corresponding TODO that needs fixing: https://github.com/kubernetes/kubernetes/blob/f74b4bbbad5463aa35b5d4d769b80db19cf12ee0/hack/make-rules/test-federation-cmd.sh#L77

Related issue for replicasets: https://github.com/kubernetes/kubernetes/issues/39984

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#96.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
