### ISSUE TITLE
enable kubectl tests with federation apiserver for replicasets

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#39984]
https://github.com/kubernetes/kubernetes/pull/38844 added kubectl tests with federation apiserver, but did not enable them for replicasets since they were failing. We need to debug the issue, fix it and then enable the tests for replicasets.

Here is the corresponding TODO that needs fixing: https://github.com/kubernetes/kubernetes/blob/f74b4bbbad5463aa35b5d4d769b80db19cf12ee0/hack/make-rules/test-federation-cmd.sh#L77

Related issue for deployments: https://github.com/kubernetes/kubernetes/issues/39985

cc @kubernetes/sig-federation-bugs

**Comment by StevenYCChou** [comment]
I am interested in working on it. I started by running `make test-cmd`, and basically read codes in [hack/lib](https://github.com/kubernetes/kubernetes/tree/master/hack/lib) & [hack/make-rules](https://github.com/kubernetes/kubernetes/tree/master/hack/make-rules) .

any other suggested lines of code and files to look into?

**Comment by nikhiljindal** [comment]
Thats great. I will recommend start by adding "replicasets" to the line pointed in the description and see what fails (whats the error).

**Comment by perotinus** [comment]
If you're going to take this on, you may want to see the last comment in #39986. I started debugging these tests and found one issue, but ended up moving onto other things before figuring out a good solution.

**Comment by StevenYCChou** [comment]
there are some issues for timeout tests in [hack/mack-rules/test-cmd.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/make-rules/test-cmd.sh) so I decided to comment them out.

however everytime I pull from github, there is random error on my OSX machine (eg: `sort -- V` not found). does the standard test generally run on linux machine?

**Comment by nikhiljindal** [comment]
I know a lot of developers who use Mac for development, so it should work on Mac as well. Feel free to file an issue

**Comment by henriquetruta** [comment]
@nikhiljindal looks like the problem here is that there are no clusters attached to the federation, i.e. we don't join a cluster. Then, the replicaset is never ready, because there is no cluster to put the pods. I ran `kubectl get clusters` and it gave me `No resources found.`

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#95.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
