### ISSUE TITLE
Allow listening on port 22 on GCE

### ISSUE THREAD

**Issue by hach-que** [kubernetes/kubernetes#39988]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

I have a container which accepts incoming traffic on port 22 (it is a Git hosting server).  However, on GCE, all master/slave communication is done over port 22.

I can somewhat work around the issue by SSH'ing onto the node, editing `sshd_config` to set the port to 24 and reloading the service.  However, this breaks `exec` and `logs` commands from `kubectl`.  I'd really prefer to be able to set the SSH port for Kubernetes to use between master/nodes so I can move it away from a port that I need to use in my cluster.

**Comment by MrHohn** [comment]
Hi @hach-que, why not put a NodePort or LoadBalancer type Service with port 22 in between? Don't think it is a good idea to clobbered the port 22 on nodes.

**Comment by hach-que** [comment]
At the moment we have host ports on everything, and it works fine for every service except this one.  We don't want to pay $20 USD extra a month just to redirect one port, and because of GCE's silly per-project pricing on load balancers, we can't take advantage of the $20 USD we're already paying for under-used load balancer capacity in another project.

**Comment by MrHohn** [comment]
cc @kubernetes/sig-network-misc

**Comment by thockin** [comment]
It is highly unlikely that we will move SSH to another port by default, and
even if we did, it's absolutely impossible that it would happen any time
soon.

HostPorts are considered bad form for many reasons, including this.

It seems much more plausible to find a way to share load-balancer across
Services, but even that falls down as we move more towards optimized paths.

I can't speak to your app architecture, but given that this is open source,
you can always DIY.
