### ISSUE TITLE
RBAC enablement in GCE configure-helper scripts

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#39990]
RBAC is enabled by default in the following cluster up scripts:

https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh

https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/container-linux/configure-helper.sh

This issue tracks the follow-up items from https://github.com/kubernetes/kubernetes/pull/39537 ensuring these scripts work for both new and existing clusters, for production and e2e use-cases

1.6 work:
- [x] change cluster/gce/upgrade.sh to detect a legacy abac policy file and populate populate ABAC_AUTHZ_FILE by default - https://github.com/kubernetes/kubernetes/pull/40172
- [x] make bootstrap superuser kubecfg certificate be in the system:masters group https://github.com/kubernetes/kubernetes/pull/39966
- [x] document how to replicate relaxed permissions with RBAC (e.g. `kubectl create clusterrolebinding my-binding --clusterrole=cluster-admin --user=admin --user=kubelet --user=controller-manager --group=system:serviceaccounts`)

1.7 work:
- [x] only load e2e role-bindings for e2e tests, not all kube-up or upgrade scenarios

- GKE work (@cjcullen)
  - [x] ~~in new clusters, include system:nodes group in new bootstrap "kubelet" certificate~~ obsoleted by the node bootstrap flow
  - [x] in upgraded clusters, include legacy abac policy for upgraded clusters
  - [x] ~~in all clusters, bind cluster-admin role to intended superuser~~ obsoleted by the joint GKE webhook authorizer

**Comment by justinsb** [comment]
Are there docs for the RBAC configuration we're aiming for yet?

**Comment by cjcullen** [comment]
Looping @mikedanese for the kubelet cert stuff.

New (1.6) nodes will be in group system:nodes. For clusters upgrading from 1.5->1.6, I think we'd like to have a binding giving the "kubelet" identity the "system:nodes" role, as opposed to just relying on the "keep ABAC around" option.

For the "client" cert. I'd rather we just deprecate that flow on GKE (w/ "keep ABAC around" as the backward compatible option). We began phasing it out in 1.3, and it takes some manual work to use that cert on GKE. For 1.5 users that really want to keep using the "client" certificate, but don't want to keep their cluster running w/ ABAC, they can add an RBAC binding giving it the "system:masters" role before upgrading to RBAC-only. +@roberthbailey

**Comment by cjcullen** [comment]
@liggitt: I know you and @deads2k are gonna hate me for proposing this, but I think we should allow new clusters to still be brought up w/ the <=1.5 ABAC permissions. It feels like the easiest trapdoor for any workflow that we "break" with the transition to RBAC. I'm going to put something together to extend the `if [[ -n "${ABAC_AUTHZ_FILE:-}"` to include generating an ABAC file if one does not exist. Then, GCE users using kube-up.sh can just set `ABAC_AUTHZ_FILE=/srv/kubernetes/abac-authz-policy.jsonl` if they really want the old way, and we will have some equivalent flag on GKE.

**Comment by liggitt** [comment]
> I'm going to put something together to extend the if [[ -n "${ABAC_AUTHZ_FILE:-}" to include generating an ABAC file if one does not exist.

I really don't want to generate ABAC files on new clusters. Why wouldn't we give an option to grant clusterrolebindings that replicated <= 1.5 permissions using RBAC?

**Comment by cjcullen** [comment]
We could do that, but then there isn't as clean of a "get rid of <= 1.5 permissions" switch. We also then have two different styles of legacy mode: the "upgraded to 1.6" version (still has the old ABAC file), and the "new at 1.6 but need legacy perms" (has a few ClusterRoleBindings created).

I agree in principle that generating ABAC is no longer the right way to do things, and we should push users away from it. But I think it muddles the transition story if we support ABAC for the update path but not the new cluster path.

**Comment by mikedanese** [comment]
> include system:nodes group in bootstrap "kubelet" certificate

There's no way to retroactively fix this for old kubelet certs so I'm not sure if this is even useful to do. We are going to need to bind kubelet role to kubelet identity for at least a few releases. I'm working on replacing the "kubelet" global cert with per kubelet certs which should land in 1.6.

**Comment by liggitt** [comment]
The ways to solve that are:
1. Always keep existing policy in place when upgrading
2. Optionally replicate old ABAC policy rules in RBAC when upgrading (done by the deployment mechanism, not in bootstrap bindings). This isn't strictly necessary if the old policy is still present, but can be useful if you're wanting to get rid of ABAC

 we just can't assume "kubelet" is a reserved username in all authentication systems that users will run their kubernetes installations with, so we can't automatically create bindings to it in all installations. GKE, GCE, etc, would have to make that decision, knowing how it had set up users

**Comment by roberthbailey** [comment]
@cjcullen - what's left to do here? Is everything necessary for 1.7 in place?

**Comment by cjcullen** [comment]
>  in new clusters, include system:nodes group in new bootstrap "kubelet" certificate
We couldn't do this for GKE because of the upgrade story: We support old nodes, who only have certificates identifying them as "kubelet", so we have to keep around a binding from "kubelet" to the "system:nodes" role.

>  in upgraded clusters, include legacy abac policy for upgraded clusters
This is done. By default, ABAC policy is preserved on an upgrade. You can call `gcloud container clusters update --no-enable-legacy-authorization my-cluster` to disable the old ABAC policy.

>  in all clusters, bind cluster-admin role to intended superuser
There isn't necessarily a known superuser when a GKE cluster is created. Project-level GCP IAM permissions decide who has superuser permissions in the cluster.

**Comment by cjcullen** [comment]
> only load e2e role-bindings for e2e tests, not all kube-up or upgrade scenarios

The current GCE setup (and GKE) rely on the kubelet binding existing. I thought we had moved that out of a folder called "e2e-rbac-bindings", but I was wrong: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/e2e-rbac-bindings.
I'm not sure what the "todo-remove-grabbag-cluster-admin" binding is doing, but it sounds sloppy that we still have that.

> remove direct grants to kubecfg in kubemark - https://github.com/kubernetes/kubernetes/blob/master/test/kubemark/resources/manifests/addons/kubemark-rbac-bindings/kubecfg-binding.yaml

@liggitt What is the problem with this? Was the thought that if we auto-bound a superuser role, we wouldn't need this?

**Comment by timothysc** [comment]
@liggitt Are we going to get to the rest of your 1.7 checkmarks this cycle or should we shuffle some to 1.8?

**Comment by liggitt** [comment]
I think just the bindings item is getting done in #46750

@cjcullen can regroup the remaining items under 1.8

**Comment by roberthbailey** [comment]
I've moved the issue to the 1.8 milestone so that full resolution won't be considered blocking the 1.7 release.

**Comment by liggitt** [comment]
I think the node bootstrap and ABAC deprecation in 1.8 completes the remaining items. @cjcullen, can you verify and close if so?
