### ISSUE TITLE
Need example for preferredDuringSchedulingIgnoredDuringExecution

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#39994]
There's no example for `preferredDuringSchedulingIgnoredDuringExecution` in any documentation.

Users are tend to re-use existing `requiredDuringSchedulingIgnoredDuringExecution ` example, but unfortunately, preferredDuringSchedulingIgnoredDuringExecution is an array. This leads some confusions, like:  #39934

We need to add examples to clarify this priority.

**Comment by caarlos0** [comment]
@resouer I tried to address that in https://github.com/kubernetes/kubernetes.github.io/issues/3711

**Comment by xiangpengzhao** [comment]
Already fixed in https://github.com/kubernetes/kubernetes.github.io/pull/3631 by @gyliu513 .

/close
