### ISSUE TITLE
Feature request: env_file support

### ISSUE THREAD

**Issue by jpswade** [kubernetes/kubernetes#40001]
I have created .env files for environments for use with docker-compose. It would be useful to have the same support in kubernetes yaml files to avoid having to reformat them.

* See: https://docs.docker.com/compose/env-file/

**Comment by fraenkel** [comment]
Do you mean something like https://github.com/kubernetes/kubernetes/pull/38882 or something else?

**Comment by bgrant0607** [comment]
Dupe of #8800
