### ISSUE TITLE
Environment variables in pod created via valueFrom: show up empty 

### ISSUE THREAD

**Issue by ensonic** [kubernetes/kubernetes#40019]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): dashboard env var pod 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:43:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: gke
- **OS** (e.g. from /etc/os-release): ubuntu trusty

**What happened**:

When creating an env var in the deployment.yml as
```
...
env:
- name: MY_IP
  valueFrom:
    fieldRef:
      fieldPath: status.podIP
```
the work (I can kubectl exec $POD -- printenv | grep MY_IP), but the dashboard shows them as empty.

**Comment by liggitt** [comment]
The values don't get populated in the API definition, only in the runtime environment

**Comment by ensonic** [comment]
Thanks for the quick reply - I think this is confusing, maybe don't show the variables then either? Also is this documented?
