### ISSUE TITLE
Can we remove --minimum-container-ttl-duration, --maximum-dead-containers-per-container, --maximum-dead-containers?

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#40044]
These kubelet flags:
```
	fs.DurationVar(&s.MinimumGCAge.Duration, "minimum-container-ttl-duration", s.MinimumGCAge.Duration, "Minimum age for a finished container before it is garbage collected.  Examples: '300ms', '10s' or '2h45m'")
	fs.MarkDeprecated("minimum-container-ttl-duration", "Use --eviction-hard or --eviction-soft instead. Will be removed in a future version.")
	fs.Int32Var(&s.MaxPerPodContainerCount, "maximum-dead-containers-per-container", s.MaxPerPodContainerCount, "Maximum number of old instances to retain per container.  Each container takes up some disk space.  Default: 1.")
	fs.MarkDeprecated("maximum-dead-containers-per-container", "Use --eviction-hard or --eviction-soft instead. Will be removed in a future version.")
	fs.Int32Var(&s.MaxContainerCount, "maximum-dead-containers", s.MaxContainerCount, "Maximum number of old instances of containers to retain globally.  Each container takes up some disk space. To disable, set to a negative number.  Default: -1.")
	fs.MarkDeprecated("maximum-dead-containers", "Use --eviction-hard or --eviction-soft instead. Will be removed in a future version.")
```
are all marked deprecated, and have been since 1.4.

But IIRC, `--eviction-hard` and `--eviction-soft` only affect eviction of Pods and image GC, not container GC. Is the eviction manager also intended to trigger container GC? Can these safely be removed? At a glance it looks like they are currently used to set up something that deletes dead containers out-of-band from the eviction manager.

/cc @kubernetes/sig-node-misc @derekwaynecarr @dashpole @vishh

**Comment by vishh** [comment]
Yes. They can be removed.

**Comment by derekwaynecarr** [comment]
I think we need to ensure that we have proper defaults identified before removing for all possible storage driver options...  does anyone have operational experience yet relying completely on eviction manager?

**Comment by xiangpengzhao** [comment]
> But IIRC, --eviction-hard and --eviction-soft only affect eviction of Pods and image GC, not container GC. 

@vishh Is this right? If so, I also wonder how can dead containers be GCed? In our PaaS project, users DO want to have dead containers be GCed by setting `maximum-dead-containers`, etc.

cc @derekwaynecarr

**Comment by vishh** [comment]
We need to evict dead containers to free up disk space and drive such
eviction decisions based on disk pressure before removing this flag.

**Comment by xiangpengzhao** [comment]
Thanks @vishh !

**Comment by zhan849** [comment]
@vishh so even we set `minimum-container-ttl-duration`, it's not really effective that eviction manager can tear down container whenever it thinks proper? Which means, container logs can be missing (especially the un-rotated logs) if components say, fluentd is not able to collect them timely?

We intend to write some container log management component that is highly dependent on this `minimum-container-ttl-duration` but it turns out this is not reliable enough

**Comment by vishh** [comment]
Yes. `--minimum-container-ttl-duration` should ideally not be used for log
management. Logging policy is a separate problem by itself which is closely
tied to local storage management.

**Comment by kekoav** [comment]
@vishh can you elaborate on how we can ensure container logs are not cleaned up before fluentd has a chance to see them? The specific use case I'm concerned about is for short-lived Jobs or containers that failed/completed quickly. I don't see a viable replacement for `minimum-container-ttl-duration` (yet).

**Comment by vishh** [comment]
@kekoav that would be a question for @crassirostris. The fact that `minimum-container-ttl-duration` was used for that is an interesting side-effect. Now that kubelet supports evictions, minimum ttl duration is no longer supported. Deprecating it and eventually removing it will better reflect the current state of the system.
If we need an interface between logging agents and kubelet, then that's a new feature and hopefully @crassirostris has a solution for it!

**Comment by crassirostris** [comment]
@vishh Thanks for a heads up on this topic

A solution for the problems is yet to be discussed and agreed in the SIG Intrumentation. Hopefully we'll be able to come with with a decision, aligned with all SIGs involved (at least SIG Intrumentation, SIG Node and SIG Storage) in Q2. Anyways, it seems to be an important topic that will be addressed at least in Q3.

@kekoav There are many problems with the logs collection right now and I don't think there's a quick work-around for all of those problems, so I would suggest waiting for a proper solution in the core kubernetes. Until then, if logs are super-critical right now, I would suggest to take a look at the [alternative ways to export logs](https://kubernetes.io/docs/concepts/cluster-administration/logging#using-a-sidecar-container-with-the-logging-agent). Though most probably, if logging load on the node is not significant (say, less than 100KB/sec of logs), fluentd should be fast enough to pick up logs most of the time (though no official SLOs here yet).

**Comment by warmchang** [comment]
should be closed by https://github.com/kubernetes/kubernetes/pull/53088

**Comment by Nowaker** [comment]
@crassirostris Has anything changed since https://github.com/kubernetes/kubernetes/issues/40044#issuecomment-297114636? Is there The Right Way for log management in Kubernetes today?
