### ISSUE TITLE
Remove APIServerList from the Kubelet

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#40049]
I would remove this right now, as it has been marked deprecated since 1.4. However, as `(len(s.APIServerList) == 0 && !s.RequireKubeConfig)` is the criteria for enabling standalone mode on the Kubelet, a replacement flag needs to be around for two versions before the deprecated flag can be removed. I will post a PR for 1.6 to add the replacement `--standalone` flag (unless @kubernetes/sig-cluster-lifecycle-misc has determined other plans since this was last discussed). The removal of APIServerList can then happen in 1.8.

/cc @mikedanese @errordeveloper 

**Edit:** #40050 accomplishes the removal of --api-servers

**Comment by mtaufen** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/40050

**Comment by liggitt** [comment]
Hmm. Is the default path for --kubeconfig the issue? Seems like if --kubeconfig had no default, it's absence would mean standalone and presence would replace --require-kubeconfig

**Comment by mtaufen** [comment]
The issue is more that an alternative way for specifying standalone mode hasn't been in place for the same period of time that APIServerList has been deprecated, so even though people have been told not to use it, there is really no alternative for enabling standalone mode.

As far as how we provide an alternative, I'd rather be explicit with the setting. It's more clear to users.

**Comment by mikedanese** [comment]
This is related to https://github.com/kubernetes/kubernetes/issues/30515 cc @smarterclayton
