### ISSUE TITLE
CRI in-place upgrade testing

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#40051]
We recommend users to drain the node before upgrade kubelet to use the CRI implementation. However, if user chooses to upgrade kubelet in-place, kubelet should stop (and later remove) old containers and create new ones. We need to add this feature to kubelet, and perform manual upgrade testing. 

/cc @Random-Liu

**Comment by yujuhong** [comment]
We need a way to identify containers managed by < kubelet 1.6 and stop/delete them in dockershim.

Assigning to @Random-Liu since he volunteered (thanks!)

**Comment by Random-Liu** [comment]
Sure. Will work on this!
