### ISSUE TITLE
[OS Load Balancers] Allow Service Annotations to override the settings specified in --cloud-config

### ISSUE THREAD

**Issue by hacktastic** [kubernetes/kubernetes#40054]
As a developer who deploys on a kubernetes-on-openstack private cloud, I would like to be able to specify certain load balancer settings at the Service level rather than the cluster level.

At present, there is no way to specify which Provider a load balancer is created under. You can specify the following settings in the "[LoadBalancer]" section of your --cloud-config file, which will control the settings for ALL Service Loadbalancers on your cluster:

lb-version
subnet-id
floating-network-id
lb-method
create-monitor
monitor-delay
monitor-timeout
monitor-max-retries
manage-security-groups
node-security-group

I propose that we add a set of Service annotations to override some [or all] of these values. This will give developers much more flexibility in how their Services are deployed. 

The annotations should share a common, simple structure that is similar to that of pkg/cloudprovider/providers/aws's annotations:
service.beta.kubernetes.io/openstack-load-balancer-provider
service.beta.kubernetes.io/openstack-load-balancer-subnet-id
service.beta.kubernetes.io/openstack-load-balancer-lb-version
service.beta.kubernetes.io/openstack-load-balancer-floating-network-id
service.beta.kubernetes.io/openstack-load-balancer-lb-method
service.beta.kubernetes.io/openstack-load-balancer-create-monitor
service.beta.kubernetes.io/openstack-load-balancer-monitor-delay
service.beta.kubernetes.io/openstack-load-balancer-monitor-timeout
service.beta.kubernetes.io/openstack-load-balancer-monitor-max-retries
service.beta.kubernetes.io/openstack-load-balancer-manage-security-groups
service.beta.kubernetes.io/openstack-load-balancer-node-security-group

We would only need to insert some small checks into the code to make sure that the Annotations take a higher priority than their corresponding --cloud-config setting.

label:sig/openstack

**Comment by hacktastic** [comment]
label:sig/openstack

**Comment by hacktastic** [comment]
@sig/openstack

**Comment by hacktastic** [comment]
@xsgordon could you please label this with sig/openstack? I'm not sure if I have permission to add labels here.

**Comment by xsgordon** [comment]
I actually don't either, @idvoretskyi can you do the honors?

**Comment by hacktastic** [comment]
Just put in a PR for this: https://github.com/kubernetes/kubernetes/pull/40202
