### ISSUE TITLE
Display wrong imageID in pod yaml while node have same image but pulled from different repos

### ISSUE THREAD

**Issue by chengzhang1016** [kubernetes/kubernetes#40062]
Description of problem: Display wrong imageID in pod yaml while node have same image but pulled from different repos

Version-Release number of selected component (if applicable):
This bug should exist in after kubernetes 1.4, relate trello card: https://trello.com/c/HOWz6ejY

How reproducible:
Always

Steps to Reproduce:
1. Select a schedulabled node and pull image: docker.io/deshuai/hello-pod:latest
```
docker images --digests | grep hello-pod
docker.io/deshuai/hello-pod                                 latest              sha256:90b815d55c95fffafd7b68a997787d0b939cdae1bca785c6f52b5d3ffa70714f   e6a47a29d0e2        7 months ago        204.3 MB
```

2. Create a pod with below yaml file and schedule to the selected node with nodeName, note that the image of pod are same but got from different repo
```
# cat pod-hostname.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-hostname
  labels:
    app: pod-hostname
spec:
  containers:
  - name: hello-pod
    image: docker.io/ocpqe/hello-pod:latest
    ports:
    - containerPort: 80
  nodeName: ip-172-18-6-175.ec2.internal (Selected node in step one)
```

3. Check images info while pod running
```
# docker images --digests | grep hello-pod
docker.io/deshuai/hello-pod                                 latest              sha256:90b815d55c95fffafd7b68a997787d0b939cdae1bca785c6f52b5d3ffa70714f   e6a47a29d0e2        7 months ago        204.3 MB
docker.io/ocpqe/hello-pod                                   latest              sha256:90b815d55c95fffafd7b68a997787d0b939cdae1bca785c6f52b5d3ffa70714f   e6a47a29d0e2        7 months ago        204.3 MB
```
```
# docker inspect e6a47a29d0e2
[
    {
        "Id": "sha256:e6a47a29d0e2749c873134622635a69badbedc98ea23791a2b152663d797c4dc",
        "RepoTags": [
            "docker.io/deshuai/hello-pod:latest",
            "docker.io/ocpqe/hello-pod:latest"
        ],
        "RepoDigests": [
            "docker.io/deshuai/hello-pod@sha256:90b815d55c95fffafd7b68a997787d0b939cdae1bca785c6f52b5d3ffa70714f",
            "docker.io/ocpqe/hello-pod@sha256:90b815d55c95fffafd7b68a997787d0b939cdae1bca785c6f52b5d3ffa70714f"
        ],
```
4. Check imageID in pod yaml file
```
# oc get pod pod-hostname -o yaml | grep imageID
```
Actual results:
4. Check imageID in pod yaml file
```
# oc get pod pod-hostname -o yaml | grep imageID
    imageID: docker-pullable://docker.io/deshuai/hello-pod@sha256:90b815d55c95fffafd7b68a997787d0b939cdae1bca785c6f52b5d3ffa70714f
```
Expected results: 
4. Check imageID in pod yaml file
```
# oc get pod pod-hostname -o yaml | grep imageID
    imageID: docker-pullable://docker.io/ocpqe/hello-pod@sha256:90b815d55c95fffafd7b68a997787d0b939cdae1bca785c6f52b5d3ffa70714f
```
Addition info: 
1. I saw we always use the first RepoDigests in code, do you think we need to improve in here?
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker_manager.go#L428
```
		if len(imgInspectResult.RepoDigests) > 1 {
			glog.V(4).Infof("Container %q had more than one associated RepoDigest (%v), only using the first", containerName, imgInspectResult.RepoDigests)
		}

		if len(imgInspectResult.RepoDigests) > 0 {
			imageID = DockerPullablePrefix + imgInspectResult.RepoDigests[0]
```

**Comment by chengzhang1016** [comment]
@DirectXMan12 Could you help to confirm? Thanks.
@derekwaynecarr @mdshuai

**Comment by resouer** [comment]
Personally I think use the first digest is OK, it does not break things ...

**Comment by DirectXMan12** [comment]
Yeah, this is due to the fact that we can only choose one image ID, so we use the first repo digest.  We could hypothetically have some improved logic here around checking to see if one of the repo digests is "similar" to the pod pull spec and try to use that one, but I'm not sure it's worth the effort here, especially since the SHAs are still the same (which is the more important part, IIRC).  Plus, if docker maintains a stable ordering, always using the first guarantees that the full image ID will be identical between different containers running the same image, instead of just the SHA.

**Comment by chengzhang1016** [comment]
@DirectXMan12 Thanks for your explanation.

**Comment by derekwaynecarr** [comment]
based on @DirectXMan12 explanation, closing.
