### ISSUE TITLE
ReplicaSets not removed, even with revisionHistoryLimit set

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/kubernetes#40068]
We've been seeing replicasets going way above the specified `.spec.revisionHistoryLimit`.

```shell
$ kubectl get rs --selector=component=resque | wc -l
139
$ kubectl get -ojson deploy resque | jq '.spec.revisionHistoryLimit'
5
```

We've removed all these excess replica sets, but they keep coming back. We are aware of https://github.com/kubernetes/kubernetes/issues/23597, that's why we set a default for _all_ deployments that we create.

We use a CD flow to deploy (multiple times per day), so these leaked RS' are growing quite fast, with the current number already reaching 3K replica sets, even after we cleaned most of them up last week:

```shell
$ kubectl get rs --all-namespaces | wc -l
2607
```

We're running on GKE, using Kubernetes version `1.5.1`.

**Comment by kargakis** [comment]
@JeanMertz if you applied `revisionHistoryLimit` after the fact that your deployment (may) have broken, it may not get cleaned up because it's blocked while trying to deploy (see https://github.com/kubernetes/kubernetes/issues/29735). Or are you seeing this issue with net-new deployments where the field is set from scratch? Can you paste logs from the controller manager? (I am not sure how to get those from GKE)

**Comment by JeanMertz** [comment]
@kargakis I'm 95% sure the deployment had `revisionHistoryLimit` set from the first version on (I checked the Git history, and it's there for the first commit, but I can't be sure a version without the field was pushed to Kubernetes before the file was committed).

I don't think I can get to the logs of the controller manager, as those are on the Kubernetes master, which isn't within our control on GKE.

**Comment by JeanMertz** [comment]
Regarding broken deployments: we definitely had some deployments which didn't work due to containers crashing. We fixed those deployments and pushed a new version, which meant another deployment was created.

Reading your linked issue #40081, I understand that this could very well be the situation we're in, in which those types of deployments are leaving behind their replica sets?

**Comment by kargakis** [comment]
> Reading your linked issue #40081, I understand that this could very well be the situation we're in, in which those types of deployments are leaving behind their replica sets?

Yes but those deployments don't use revisionHistoryLimit (it's not set by default for backwards comp reasons). Setting it also after you have hit adler's limit won't help you much. How much exactly is "multiple times per day"? When a deployment rolls out successfully one replica set it immediately deletes all old replica sets it doesn't need and I would be surprised to see a case where it doesn't.

**Comment by kargakis** [comment]
@kubernetes/sig-apps-misc in addition to https://github.com/kubernetes/kubernetes/pull/40081 we may want requeue deployments when a replica set is failed to be cleaned up.  Highly unlikely that the lack of retrying those errors is causing any issues but it would be probably good to solidify it in the deployment controller.

**Comment by JeanMertz** [comment]
@kargakis we're going to clean up all our replica sets again, and leave it like that for a couple of days.

If I understand you correctly, once we clean up old replica sets, and are running a version of Kubernetes which fixes this issue (we are, 1.5.1), we shouldn't be seeing these issues anymore, correct?

Right now, it's still growing though (see my initial post for the delta):

```
$ kubectl get rs --all-namespaces | wc -l
    2839
```

Once we've cleaned up, and things are still growing, we'll report back, and hopefully we can re-open this issue if this is something that isn't fixed yet in one of the PRs for 1.6.

**Comment by kargakis** [comment]
@JeanMertz make sure all of your Deployments are using `revisionHistoryLimit` and you should be fine in 1.6. If you still have this issue by then, let me know.

**Comment by Bekt** [comment]
@JeanMertz any update?

We are having this issue on a brand new cluster (1.5.1) with brand new deployments. How often does the cleaning process happen?

```
$ kubectl version                                                                                                                  
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0", GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", BuildDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```


```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        imagePullPolicy: Always
        ports:
        - name: target
          containerPort: 80
```

```
$ kubectl apply -f my-nginx.yaml
deployment "nginx" created

$ kubectl get deploy
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx     2         2         2            2           51s

$ kubectl get -o json deploy nginx | jq '.spec.revisionHistoryLimit'
2

$ kubectl get rs
NAME              DESIRED   CURRENT   READY     AGE
nginx-696171888   2         2         2         59s

$ kubectl set image deployment/nginx nginx=nginx:1.8.1
deployment "nginx" image updated

$ kubectl set image deployment/nginx nginx=nginx:1.9.7
deployment "nginx" image updated

$ kubectl set image deployment/nginx nginx=nginx:1.9.8
deployment "nginx" image updated

$ kubectl set image deployment/nginx nginx=nginx:1.9.9
deployment "nginx" image updated

$ kubectl set image deployment/nginx nginx=nginx:1.9.10
deployment "nginx" image updated

$ kubectl get rs
NAME               DESIRED   CURRENT   READY     AGE
nginx-127450473    0         0         0         6m
nginx-4085955994   2         2         2         23s
nginx-696171888    0         0         0         7m
nginx-696434032    0         0         0         4m
nginx-777698673    0         0         0         3m
nginx-858963314    0         0         0         1m

$ kubectl get pods -l app=nginx
NAME                     READY     STATUS    RESTARTS   AGE
nginx-4085955994-hlzm1   1/1       Running   0          1m
nginx-4085955994-vjwdr   1/1       Running   0          1m
```

**Comment by Bekt** [comment]
Opened a new issue as a bug report over at #41432.
