### ISSUE TITLE
Create a default StorageClass for vSphere

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#40070]
We'd like to deprecate alpha provisioning in 1.6. In order to make current deployments working after upgrade to 1.6 we need to deploy a default StorageClass as part of installation/upgrade on vSphere so it will automatically provision volumes for PVCs marked with annotation `volume.alpha.kubernetes.io/storage-class` - the annotation will be ignored and default storage class must provision the volume instead.

On GCE and AWS, we use addon manager to install the default storage class, see https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/storage-class. Note that some extra code was needed in AWS and GCE installers to actually put the storage class into addons directory during installation, e.g. https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/container-linux/configure-helper.sh#L1129 

Please make sure that:
* A default StorageClass is deployed during "default" installation.
  * It would be nice if admin could turn this off during installation (e.g.  as `export ENABLE_DEFAULT_STORAGE_CLASS=false` on GCE)
* If any additional manual steps are needed to deploy the default storage class make sure they're documented in appropriate installation guide.

**Comment by jsafrane** [comment]
cc @abithap @abrarshivani

**Comment by kerneltime** [comment]
@jsafrane thanks will look into this.
CC @BaluDontu

**Comment by kerneltime** [comment]
Documentation update for cloud provider https://github.com/kubernetes/kubernetes.github.io/pull/2596
