### ISSUE TITLE
CronJob fails to operate with client-go

### ISSUE THREAD

**Issue by nickschuch** [kubernetes/kubernetes#40074]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

_Operation cannot be fulfilled on jobs.batch_

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Virtualbox
- **OS** (e.g. from /etc/os-release): 16.04.1 LTS (Xenial Xerus)
- **Kernel** (e.g. `uname -a`): Linux local 4.4.0-45-generic
- **Install tools**: Puppet
- **Others**: N/A

**What happened**:

* Jobs never complete, keep creating new pods over and over.
* Log message _jobcontroller.go:272] Error syncing job: Operation cannot be fulfilled on jobs.batch "example-1484738160": the object has been modified; please apply your changes to the latest version and try again_
* Jobs complete if using the example yaml file from https://kubernetes.io/docs/user-guide/cron-jobs/#creating-a-cron-job, but not from code using https://github.com/kubernetes/client-go

**What you expected to happen**:

Jobs to complete, and CronJobs to spawn a new job (normal behaviour).

**How to reproduce it** (as minimally and precisely as possible):

The following example will result in a CronJob + a single Job that never completes and keeps creating new pods.

```go
package main

import (
	"fmt"

	"k8s.io/client-go/rest"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/pkg/api/v1"
	"k8s.io/client-go/pkg/apis/batch/v2alpha1"
)

func main() {
	job := &v2alpha1.CronJob{
		ObjectMeta: v1.ObjectMeta{
			Name: "example",
		},
		Spec: v2alpha1.CronJobSpec{
			Schedule:          "* * * * *",
			ConcurrencyPolicy: v2alpha1.ForbidConcurrent,
			JobTemplate: v2alpha1.JobTemplateSpec{
				Spec: v2alpha1.JobSpec{
					Template: v1.PodTemplateSpec{
						Spec: v1.PodSpec{
							RestartPolicy: "Never",
							Containers: []v1.Container{
								{
									Name:  "cli",
									Image: "busybox",
									Command: []string{
										"/bin/bash",
										"-c",
										"echo 1",
									},
									ImagePullPolicy: "Always",
								},
							},
						},
					},
				},
			},
		},
	}

	config := &rest.Config{
		Host: "http://localhost:8080",
	}

	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		panic(err)
	}

	_, err = clientset.BatchV2alpha1().CronJobs("default").Create(job)
	if err != nil {
		panic(err)
	}

	fmt.Println("Deployed example cronjob")
}
```

You will also see the following logs returned from the controller

```
Error syncing job: Operation cannot be fulfilled on jobs.batch "example-1484738160": the object has been modified; please apply your changes to the latest version and try again
```

**Anything else do we need to know**:

Happy to help, but not sure where to start.

**Comment by nickschuch** [comment]
After some debugging I think I tracked this one down to kubectl injecting the "Namespace" field onto each of the objects all the way down. Meaning that `kubectl` would work, but my raw code had to account for that.

**Comment by Quentin-M** [comment]
@nickschuch Could you please elaborate on the issue/fix? I am seeing something similar on services / statefulsets / other resources after using client-go to patch resources. I also noticed that client-go was patching the namespace in a weird way for cluster scoped resources.
