### ISSUE TITLE
Create a default StorageClass for Azure

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#40071]
We'd like to deprecate alpha provisioning in 1.6. In order to make current deployments working after upgrade to 1.6 we need to deploy a default StorageClass as part of installation/upgrade on Azure so it will automatically provision volumes for PVCs marked with annotation `volume.alpha.kubernetes.io/storage-class` - the annotation will be ignored and default storage class must provision the volume instead.

On GCE and AWS, we use addon manager to install the default storage class, see https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/storage-class. Note that some extra code is probably needed to actually put the storage class into addons directory during installation, e.g. https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/container-linux/configure-helper.sh#L1129 for manual script-based installation on GCE or https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-addons/init.sls#L181 for salt-based installation.

Please make sure that:
* A default StorageClass is deployed during "default" installation.
  * It would be nice if admin could turn this off during installation (e.g.  as `export ENABLE_DEFAULT_STORAGE_CLASS=false` on GCE)
* If any additional manual steps are needed to deploy the default storage class make sure they're documented in appropriate installation guide.

**Comment by jsafrane** [comment]
Assigning to random Microsoft personnel for faster routing to proper person.

**Comment by brendandburns** [comment]
@jsafrane I believe this is fixed, correct? If so, I will close it...

**Comment by jsafrane** [comment]
Yes, it's fixed.
