### ISSUE TITLE
Regular expression for limit validation fails on scientific notation with units

### ISSUE THREAD

**Issue by jwforres** [kubernetes/kubernetes#40085]
kubernetes version v1.5.2

If you use a resource request / limit with scientific notation plus a unit it will fail the regex that is doing validation.

Example of what is being posted:

```
{"kind":"PersistentVolumeClaim","apiVersion":"v1","metadata":{"name":"test","labels":{},"annotations":{"volume.beta.kubernetes.io/storage-class":"ebs"}},"spec":{"resources":{"requests":{"storage":"1e-7Ti"}},"accessModes":["ReadWriteOnce"]}}
```

Error being returned:
```
PersistentVolumeClaim in version "v1" cannot be handled as a PersistentVolumeClaim: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```

You can see clearly in the regular expression that it can't handle scientific notation with a unit.

**Comment by jwforres** [comment]
@smarterclayton @derekwaynecarr 

cc @spadgett

**Comment by smarterclayton** [comment]
Units are not supported on scientific.  We support `1.2e-7`, but not `1.2e-7Ti`.

**Comment by jwforres** [comment]
If I remember correctly the original issue that spawned this was QE putting in 0.0000001 Ti as the limit, and the browser was "helpfully" converting the value portion to scientific.

Sounds like we need to deal with this in the client and not let it send the data in this format?

**Comment by smarterclayton** [comment]
Probably at this point yes, changes to the format are going to be very
complex and not worth it.

On Sun, Jun 18, 2017 at 8:13 PM, Jessica Forrester <notifications@github.com
