### ISSUE TITLE
kubectl get storageclasses --all-namespaces mixes columns

### ISSUE THREAD

**Issue by ankon** [kubernetes/kubernetes#40091]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
- kubectl storageclass
- kubectl storageclasses

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version** (use `kubectl version`):
```sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: minikube v0.15.0
- **OS** (e.g. from /etc/os-release): Fedora release 25 (Twenty Five)
- **Kernel** (e.g. `uname -a`): 4.9.3-200.fc25.x86_64

**What happened**:

```sh
$ kubectl get storageclasses --all-namespaces=true
NAMESPACE        NAME                      TYPE
slow (default)   kubernetes.io/host-path   
```

**What you expected to happen**:
Either an error that namespaces and storageclasses don't mix, or an empty NAMESPACE column, or a missing NAMESPACE column :)

**How to reproduce it** (as minimally and precisely as possible):
1. Define one or more storage classes
2. Run `kubectl get storageclasses --all-namespaces=true`

**Anything else do we need to know**:

Cosmetic issue, I think I've also seen it in some other similar cases but missed to record them :(

**Comment by calebamiles** [comment]
Could someone from @kubernetes/sig-cli-misc or @kubernetes/sig-storage-misc please help triage? thanks!

**Comment by xilabao** [comment]
https://github.com/kubernetes/kubernetes/pull/39265 on the way

**Comment by jeffvance** [comment]
Seems to be fixed in version:
```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0+776c994", GitCommit:"776c994",
GitTreeState:"clean", BuildDate:"2016-11-03T21:47:56Z", GoVersion:"go1.6.1", Compiler:"gc",
Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+",
GitVersion:"v1.6.0-alpha.0.3466+daf2062a8a09b3-dirty",
GitCommit:"daf2062a8a09b3f8b2a4357f698d493eb5bebc8d", GitTreeState:"dirty",
BuildDate:"2017-01-18T17:26:23Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
Eg.
```
$ kcubectl get storageclasses --all-namespaces
NAMESPACE           NAME                   TYPE
default (default)   kubernetes.io/gce-pd   
```

**Comment by xilabao** [comment]
@jeffvance  No, The bug is still exist.

**Comment by jeffvance** [comment]
Isn't "default" the name of the namespace? If not, my apologies.
