### ISSUE TITLE
`build/run.sh make clean` fails

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#40090]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): build/run.sh make clean

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): I am building from the release-1.5 branch

**Environment**: I am building on my Mac
- **Cloud provider or hardware configuration**: none
- **OS** (e.g. from /etc/os-release): MacOS 10.12.2
- **Kernel** (e.g. `uname -a`): `Darwin XXX.ibm.com 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64`
- **Install tools**: none
- **Others**: Docker version 1.12.5, build 7392c3b; 4 GB allocated to the Docker VM

**What happened**:
I read in https://github.com/kubernetes/kubernetes/blob/788804142f1b3323523500c2932f511284b6eae9/build/README.md#key-scripts about using `build/run.sh make`.  It lists some example make targets to use; it _does not_ list any targets to avoid.  So I thought I would start by cleaning up any mess that might be laying around, assuming the usual convention for that works.

```
mjs10:~ mspreitz$ cd $GOPATH

mjs10:go mspreitz$ ls -l src
total 8
drwxr-xr-x   3 mspreitz  staff  102 Aug  4  2015 9fans.net
drwxr-xr-x   4 mspreitz  staff  136 Jul 13  2016 code.google.com
drwxr-xr-x  21 mspreitz  staff  714 Nov 21 09:36 github.com
drwxr-xr-x   3 mspreitz  staff  102 Jan 12 13:54 github.ibm.com
lrwxr-xr-x   1 mspreitz  staff   20 Jan 18 12:54 k8s.io -> github.com/kuberetes

mjs10:go mspreitz$ cd src/github.com/kubernetes/kubernetes

mjs10:kubernetes mspreitz$ git status
On branch release-1.5
Your branch is up-to-date with 'origin/release-1.5'.
nothing to commit, working tree clean

mjs10:kubernetes mspreitz$ git rev-parse HEAD
f0c2af20c13ab25b7fe4eec00fb11d417ef3a31d

mjs10:kubernetes mspreitz$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

mjs10:kubernetes mspreitz$ build/run.sh make clean
+++ [0118 13:01:30] Verifying Prerequisites....
+++ [0118 13:01:30] Using Docker for MacOS
+++ [0118 13:01:31] Building Docker image kube-build:build-789f1328e3-4-v1.7.4-0
+++ [0118 13:02:59] Keeping image kube-build:build-789f1328e3-4-v1.7.4-0
+++ [0118 13:02:59] Creating data container kube-build-data-789f1328e3-4-v1.7.4-0
+++ [0118 13:03:01] Syncing sources to container
+++ [0118 13:03:01] Stopping any currently running rsyncd container
+++ [0118 13:03:01] Starting rsyncd container
+++ [0118 13:03:02] Running rsync
+++ [0118 13:03:08] Stopping any currently running rsyncd container
+++ [0118 13:03:09] Running build command...
+++ [0118 13:03:10] Verifying Prerequisites....
!!! [0118 13:03:10] Can't find 'docker' in PATH, please fix and retry.
!!! [0118 13:03:10] See https://docs.docker.com/installation/#installation for installation instructions.
!!! Error in build/make-clean.sh:151
  'return 1' exited with status 1
Call stack:
  1: build/make-clean.sh:151 main(...)
Exiting with status 1
Makefile:207: recipe for target 'clean' failed
make: *** [clean] Error 1
!!! Error in build/../build/common.sh:523
  '"${docker_cmd[@]}" "${cmd[@]}"' exited with status 2
Call stack:
  1: build/../build/common.sh:523 kube::build::run_build_command_ex(...)
  2: build/../build/common.sh:515 kube::build::run_build_command(...)
  3: build/run.sh:30 main(...)
Exiting with status 1
```

**What you expected to happen**:
I expected that either `build/run.sh make clean` works or that doc would warn me against trying it.  Yes, I later discovered that the doc mentions `build/make-clean.sh` --- after having the above problem.

**How to reproduce it** (as minimally and precisely as possible):
What I showed above is pretty direct and from-scratch.

**Anything else do we need to know**:

**Comment by calebamiles** [comment]
Thanks for submitting your issue @MikeSpreitzer poking around a little bit it seems as if `d91b3200c75a32841dd9aebd3dee2bc785c9dadd` needs to be cherry-picked onto the 1.5 release branch. The error you're seeing I believe comes from inside of the container and should not happen because docker is not required to clean. @saad-ali, how do you feel about making the cherry-pick?

**cc: @ixdy**

**Comment by saad-ali** [comment]
> @saad-ali, how do you feel about making the cherry-pick?

Makes perfect sense. @ixdy can you cherry pick https://github.com/kubernetes/kubernetes/pull/38520 to the `release-1.5` branch? If not, I'll do it.

**Comment by spzala** [comment]
I am wondering, shouldn't this issue be closed automatically as part of fix 41174 where the issue is mentioned? Thanks! 

On a side note, when I run ```build/run.sh make clean``` on a freshly clone repo, I don't see the error related to per-requisite as mentioned in the issue but I see a different error as below. I guess the error on git is about not having git on a newly created container (fbafb161aec4). I am not sure if it's bug or user error.  

```
# docker ps 
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS           
```
```
# build/run.sh make clean
+++ [0927 14:07:01] Verifying Prerequisites....
+++ [0927 14:07:02] Building Docker image kube-build:build-0571f8bd06-5-v1.8.3-2
+++ [0927 14:09:52] Keeping image kube-build:build-0571f8bd06-5-v1.8.3-2
+++ [0927 14:09:52] Creating data container kube-build-data-0571f8bd06-5-v1.8.3-2
+++ [0927 14:09:53] Syncing sources to container
+++ [0927 14:09:53] Stopping any currently running rsyncd container
+++ [0927 14:09:54] Starting rsyncd container
+++ [0927 14:09:54] Running rsync
+++ [0927 14:10:01] Stopping any currently running rsyncd container
+++ [0927 14:10:02] Output from this container will be rsynced out upon completion. Set KUBE_RUN_COPY_OUTPUT=n to disable.
+++ [0927 14:10:02] Running build command...
+++ [0927 14:10:02] Verifying Prerequisites....
fatal: Not a git repository (or any parent up to mount point /go/src/k8s.io/kubernetes)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Makefile:311: recipe for target 'clean' failed
make: *** [clean] Error 128
!!! [0927 14:10:03] Call tree:
!!! [0927 14:10:03]  1: build/../build/common.sh:535 kube::build::run_build_command_ex(...)
!!! [0927 14:10:03]  2: build/run.sh:39 kube::build::run_build_command(...)
!!! Error in build/../build/common.sh:603
  Error in build/../build/common.sh:603. '((i<4-1))' exited with status 2
Call stack:
  1: build/../build/common.sh:603 kube::build::run_build_command_ex(...)
  2: build/../build/common.sh:535 kube::build::run_build_command(...)
  3: build/run.sh:39 main(...)
Exiting with status 1
root@sahdev-VirtualBox:/home/sahdev/go/src/k8s40090/kubernetes# docker ps -a
CONTAINER ID        IMAGE                                    COMMAND                  CREATED              STATUS                          PORTS               NAMES
fbafb161aec4        kube-build:build-0571f8bd06-5-v1.8.3-2   "make clean"             About a minute ago   Exited (2) About a minute ago                       kube-build-0571f8bd06-5-v1.8.3-2
```

**Comment by thockin** [comment]
Seems to work now, though this is a weird pattern.  Just 'make clean' should suffice.
