### ISSUE TITLE
404 on //build:busybox-libc

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#40100]
Seeing this in bazel builds:
```
W0118 19:50:44.988] ERROR: /workspace/k8s.io/kubernetes/build/BUILD:18:1: no such package '@libc_deb//file': Error downloading [http://ftp.us.debian.org/debian/pool/main/g/glibc/libc6_2.19-18+deb8u6_amd64.deb] to /root/.cache/bazel/_bazel_root/e9f728bbd90b3fba632eb31b20e1dacd/external/libc_deb/libc6_2.19-18+deb8u6_amd64.deb: GET returned 404 Not Found and referenced by '//build:busybox-libc'.
W0118 19:50:45.077] ERROR: Analysis of target '//build:busybox-libc' failed; build aborted.
```
@mikedanese is that link supposed to be stable?

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/40097/pull-kubernetes-bazel/1224/

**Comment by spxtr** [comment]
`http://ftp.us.debian.org/debian/pool/main/g/glibc/libc6_2.19-18+deb8u6_amd64.deb` -> `http://ftp.us.debian.org/debian/pool/main/g/glibc/libc6_2.19-18+deb8u7_amd64.deb` fixes it. I'll make a PR.

**Comment by mikedanese** [comment]
This happens when they push a security update.
