### ISSUE TITLE
kubectl apply and edit are broken for TPR

### ISSUE THREAD

**Issue by ymqytw** [kubernetes/kubernetes#40119]
This issue is found when working on #39906. This is a different issue from #39906. It affects all 1.5.x and master.

The error message is
```
error: unable to decode "../pkiobj.json": no kind "Pki" is registered for version "box-pki.com/v1"
```

`kubectl apply` and `edit` are broken for TPR in branch 1.5 and master.
The reason is the function call of [`Decode()`](https://github.com/kubernetes/kubernetes/blob/c1ecedf44d1903b823f5e5274de000b4be09d17c/pkg/kubectl/resource/mapper.go#L52). It fails to decode the data.

**Anything else do we need to know**:
1.4.7 is working, but 1.4.8 is not, because of #39396.
Similar patch #38982 has been introduced in 1.5.2, but both 1.5.1 and 1.5.2 are broken for TPR. `apply` fails without even reaching the code introduced in #38982. 

@liggitt @deads2k @pwittrock @kubernetes/sig-cli-misc

**Comment by edsiper** [comment]
+1

_kubectl apply_ is an unrecognized command:

```
$ kubectl apply -f https://git.io/weave-kube
Error: unknown command "apply"
```

```
# kubectl version
Client Version: version.Info{Major:"0", Minor:"20.1", GitVersion:"v0.20.1", GitCommit:"", GitTreeState:"not a git tree"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean"}
```

**Comment by liggitt** [comment]
You seem to have a custom built version. Where did you obtain your kubectl?

**Comment by edsiper** [comment]
@liggitt 

deb package:

```
ii  kubectl      1.5.1-00     amd64        Kubernetes Command Line Tool
```

repository:

```
deb http://apt.kubernetes.io/ kubernetes-xenial main
```

per instructions from: https://kubernetes.io/docs/getting-started-guides/kubeadm/

**Comment by edsiper** [comment]
my "kubectl apply" issue is solved (my bad), I had an old-local/custom kubectl in /usr/local/bin/ messing up the things.

**Comment by ahakanbaba** [comment]
Thanks @ymqytw  for creating this issue. 
As a first step, I would be interested in adding tests that reproduce these behavior. 
We could add those tests in a disabled way and make sure they run at the end of the fix. 

Would you be interested in that approach ? 
1) Add tests that reproduce the behavior
2) Merge those tests, keep them in a disabled state. Annotate them with this issue.
3) Work on the fixes. 
4) enable the tests

I am playing around with adding some tests that reproduce these behavior. 

Please let me know if you agree/ disagree.

**Comment by ahakanbaba** [comment]
@huggsboson

**Comment by ymqytw** [comment]
@ahakanbaba That sounds reasonable to me. But I'm not sure how to add some disabled tests.
Another way is add the test with fix in the same PR.

>I am playing around with adding some tests that reproduce these behavior.

Please feel free to create a PR for the tests, if you already have some. cc me in that PR. Thanks.

**Comment by bgrant0607** [comment]
@ymqytw Please dedupe this. There are several other issues about apply and edit for TPR.

Apply: https://github.com/kubernetes/kubernetes/issues/29542, https://github.com/kubernetes/kubernetes/issues/39906
Edit: https://github.com/kubernetes/kubernetes/issues/35993

**Comment by liggitt** [comment]
apply is fixed. #35993 covers edit
