### ISSUE TITLE
Upgrade from 1.4 to master hangs

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#40110]
It appears that the API server is no longer able to talk to etcd after an upgrade. See https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-gci-latest-1.4-gci-latest-upgrade-cluster-new/323?log#log for an example.

Interesting bits from api server log:

```console
Flag --address has been deprecated, see --insecure-bind-address instead.
I0118 19:20:12.863023       5 gce.go:292] Using GCE provider config {Global:{TokenURL: TokenBody: ProjectID: NetworkName: NodeTags:[bootstrap-e2e-minion] NodeInstancePrefix:bootstrap-e2e-minion Multizone:false}}
I0118 19:20:12.863122       5 gce.go:332] Using existing Token Source &oauth2.reuseTokenSource{new:google.computeSource{account:""}, mu:sync.Mutex{state:0, sema:0x0}, t:(*oauth2.Token)(nil)}
I0118 19:20:12.870362       5 server.go:173] Initializing deserialization cache size based on 180MB limit
W0118 19:20:12.872125       5 config_selfclient.go:44] Failed to create secure local client, falling back to insecure local connection: failed to find certificate which matches "localhost"
I0118 19:20:12.873151       5 server.go:331] Initializing cache sizes based on 180MB limit
F0118 19:20:12.878547       5 master.go:271] Error building core storage: open /etc/srv/kubernetes/kubeapiserver.cert: no such file or directory
```

**Comment by mml** [comment]
I have debugged a lot of 2.3.7 -> 3.0.14 upgrades and adding `--debug` to every `etcd` invocation helps a ton.  Any chance we can twiddle this knob when we run these tests?  Perhaps via instance metadata?

**Comment by mml** [comment]
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-gci-latest-1.4-gci-latest-upgrade-cluster-new/323/artifacts/bootstrap-e2e-master/etcd.log shows etcd starting, and that 3.0.14 stays running for ~10 hours, and apparently appending to its log.  It looks like someone is talking to it.

The failure modes I saw in testing upgrades were generally that etcd would crash, which is not what we see here.

**Comment by mml** [comment]
One thing just occurred to me.  We should probably have a test suite like these upgrades that simply tries to upgrade etcd without changing the version of k8s.  This would let us isolate etcd failures from failures of other types.

**Comment by wojtek-t** [comment]
@mml - I think there is still one flag fix in the "migration" script that you found but didn't create a PR for. Maybe this is also reason of this failure?

Can you please finish the loop and finally create that PR so that we can have the script in head updated?

**Comment by wojtek-t** [comment]
I'm reopening for verifying if the problem is fixed.

**Comment by mml** [comment]
I have re-built `3.0.14`.  I'll see if I can abort the current run of https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-gci-latest-1.4-gci-latest-upgrade-cluster-new/

**Comment by wojtek-t** [comment]
@mml We are currently using "3.0.14-alpha.1" image. So if you want to try a different image, I think you should update manifest files to the new image. Or rebuild 3.0.14-alpha.1 image :)
[Unless I'm missing something how the test works.]

**Comment by mml** [comment]
D'oh.  Thanks, @wojtek-t.  I just assumed the default tag in the Makefile was correct.

**Comment by mml** [comment]
```
Successfully built a175ef3f30d0
gcloud docker -- push gcr.io/google_containers/etcd-amd64:3.0.14-alpha.1
The push refers to a repository [gcr.io/google_containers/etcd-amd64]
411dda925344: Layer already exists
e77e5832dec3: Layer already exists
38ac8d0f5bb3: Layer already exists
3.0.14-alpha.1: digest: sha256:1c859204dc74680651eec3a027520cba55375cb14ada022a9bec8e07d215579f size: 950
# Backward compatibility. TODO: deprecate this image tag
docker tag gcr.io/google_containers/etcd-amd64:3.0.14-alpha.1 gcr.io/google_containers/etcd:3.0.14-alpha.1
gcloud docker -- push gcr.io/google_containers/etcd:3.0.14-alpha.1
The push refers to a repository [gcr.io/google_containers/etcd]
411dda925344: Layer already exists
e77e5832dec3: Layer already exists
38ac8d0f5bb3: Layer already exists
3.0.14-alpha.1: digest: sha256:1c859204dc74680651eec3a027520cba55375cb14ada022a9bec8e07d215579f size: 950
```

**Comment by wojtek-t** [comment]
Should I be looking into this job:
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-gci-latest-1.4-gci-latest-upgrade-cluster-new/

From the logs that @krousey pasted at the beginning (and which appear in all logs) and seems that the problem is with certificated files, not with etcd itself.
```
F0118 19:20:12.878547       5 master.go:271] Error building core storage: open /etc/srv/kubernetes/kubeapiserver.cert: no such file or directory
```

@jszczepkowski @roberthbailey - did anything change around how certs are handled? Any ideas why those tests may be facing this issue?

**Comment by wojtek-t** [comment]
Actually, looking at the log that is causing it to fail:


I very strongly suspect that the victim of those failures is this PR:
https://github.com/kubernetes/kubernetes/pull/38212

@cjcullen @mikedanese - can you please take a look if the hypothesis sounds reasonable to you?

**Comment by kargakis** [comment]
I have seen something related, probably the same issue. I was testing 1.4.7, persisted the etcd data dir, restarted the cluster on master and wasn't able to access any resources created when the cluster was running in 1.4.7. I was able to see those resources in etcd by using curl directly on etcd.

**Comment by mikedanese** [comment]
Ok, ya this was caused by #38212. I tried to revert and got some nasty conflicts. I'm hoping that https://github.com/kubernetes/kubernetes/pull/40893 will be ready by the EOD and will fix this issue.

**Comment by mml** [comment]
@mikedanese thanks!

**Comment by mml** [comment]
@mikedanese can you confirm that your PR #38212 would have caused the same problem if `master` was running etcd v2?  I'm trying to rule out any interaction with the etcd v3 or our scripts related to it.

**Comment by mikedanese** [comment]
@mml yes, I don't think this problem is etcd related, as far as i can tell right now.

**Comment by roberthbailey** [comment]
@krousey - is this issue still relevant? Or can we close as obsolete?
