### ISSUE TITLE
Regression: kubelet inotify does not detect changed symlink targets

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#40123]
In k8s 1.4, we were able to set up a symlink from `/etc/kubernetes/manifests/etcd.manifest` to a mountpoint (`/mnt/etcd-volume/k8s.io/etcd.manifest`), to ensure that the pod could not be started before the volume was mounted.

k8s 1.5 broke this: the inotify poller does not detect when the volume is mounted, because the inotify watch does not traverse symlinks: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/config/file_linux.go#L58

Also:

* We probably should include `IN_ATTRIB` so that users can touch the file / symlink
* We probably need to move to fsnotify, or create our own fork of inotify, because inotify has been deleted: https://github.com/golang/exp/tree/master/inotify  (It's 300 lines, mostly symbol definitions, we should probably bring it in to k8s)
* I suggest we should probably have a time based poll in addition, to catch anything the inotify misses
* It is unsafe to ignore IN_Q_OVERFLOW, I believe

cc @dchen1107

**Comment by yujuhong** [comment]
> We probably need to move to fsnotify, or create our own fork of inotify, because inotify has been deleted: https://github.com/golang/exp/tree/master/inotify (It's 300 lines, mostly symbol definitions, we should probably bring it in to k8s)

It's probably the best to switch to fsnotify because cadvisor also relies on the deprecated "golang.org/x/exp/inotify" package.

> I suggest we should probably have a time based poll in addition, to catch anything the inotify misses

inotify was added mostly for timely reaction to changes. Additional polling (~minute) sounds good to me.

**Comment by wu8685** [comment]
Adding a polling could fix it and which is how it works before using inotify.
Are you working on this?

**Comment by Random-Liu** [comment]
@wu8685 Nope, I don't think anyone is working this right now. :)

**Comment by wu8685** [comment]
I have committed a PR. PLS take a look
