### ISSUE TITLE
dnsprovider: should return NS records in Zone

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#40122]
We should either expose a per-provider "cheat" interface, or we should expose the NS records in Zone for dnsprovider.   For a use-case, kops wants to validate the NS records are set correctly for self-diagnostics: https://github.com/kubernetes/kops/issues/1508

**Comment by bowei** [comment]
@justinsb is this talking about a cloudprovider interface?

**Comment by justinsb** [comment]
No, the dnsprovider interface: https://github.com/kubernetes/kubernetes/tree/master/federation/pkg/dnsprovider

This is now implemented specifically for route53, if it proves useful (as it seems to) we can extend to the other implementations.  (Or we could just close this now, and add to others as needed)
