### ISSUE TITLE
"kubectl delete pod [uid]" doesn't work

### ISSUE THREAD

**Issue by tianshapjq** [kubernetes/kubernetes#40121]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
delete pod
delete pod uid
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
maybe a bug report: the "kubectl delete pod [uid]" doesn't work.

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+82450d0", GitCommit:"59619aa9d1b0481460e9de029408b3bac82ca5d4", GitTreeState:"dirty", BuildDate:"2017-01-10T00:30:53Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+82450d0", GitCommit:"59619aa9d1b0481460e9de029408b3bac82ca5d4", GitTreeState:"dirty", BuildDate:"2017-01-10T00:26:06Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:
First, use "kubectl get pod [podname] -o yaml" to get the details of the pod, obtaining the uid under metadata.uid. Then use "kubectl delete pod [uid]" to delete the pod, but failed finally. the info showed like this: Error from server (NotFound): pods "8a2ff4bf-dbf8-11e6-818c-4437e63c5ac5" not found.
Did I get the wrong uid?

**What you expected to happen**:
It should delete pod successfully just like using podname.

**How to reproduce it** (as minimally and precisely as possible):
just do like mentioned in "What happened"

**Comment by yujuhong** [comment]
I don't think we provide pod deletion by UID...
/cc @kubernetes/sig-cli-misc

**Comment by tianshapjq** [comment]
If you type "kubectl delete pod -h", there is a piece of specifications describing like this:
# Delete a pod with UID 1234-56-7890-234234-456456.
kubectl delete pod 1234-56-7890-234234-456456
So is this a mistake?

**Comment by yujuhong** [comment]
> So is this a mistake? @yujuhong

I don't know. It could be a feature that I am not aware of. Folks from the @kubernetes/sig-cli-misc will know better.

**Comment by ymqytw** [comment]
>   \# Delete a pod with UID 1234-56-7890-234234-456456.
  kubectl delete pod 1234-56-7890-234234-456456

It seems this help message exists even in v1.0. @fabianofranz @pwittrock Do we support this before?

**Comment by yujuhong** [comment]
AFAIK, apiserver doesn't support operations using the UID as the key. Unless kubectl implement additional logic to map the UID to a (name, namespace) tuple, it'd not be able to do that.

**Comment by fabianofranz** [comment]
Delete by UID is no longer supported, this is an issue with the help text that needs to be adjusted.
