### ISSUE TITLE
Hostport Automatic Assignment In Host Network Mode

### ISSUE THREAD

**Issue by wozhengjl** [kubernetes/kubernetes#40131]
As we know, in mesos/marathon, if port is set as 0, then the framework will randomly assign port to replace 0, the port assignment strategy is based on the available ports resource on the node,
example: if app sets "ports": [0],
the available port resource on node is ["2000-3000"]  the framework will replace the port as:
"ports": [2001].
and set env variable PORT0=2001

However, in k8s there's no automatic hostport assignment strategy, hostport must be specified by the user,  this may result in hostport conflicts. 
example:
rc's replicas is 3, and the hostport is set as 9999,  hostNetwork: true, there's 2 nodes available(port 9999 is not used):
then only 2 but not 3 pods will be created successfully. Is it possible that set the  hostport as 0 and k8s will assign the port automatically, as long as there's no port conflict to ensure 3 pods created. The app can listen the port assigned by k8s to replace 9999.

Hope to get your ACK, Thanks in advance!

**Comment by jiale921** [comment]
I have  the same problem ,did you solve the problem?

**Comment by fatduo** [comment]
@wozhengjl Any update?

**Comment by wujianlin** [comment]
+1， i hope kubernetes can automatically assigned host ports.

**Comment by gyliu513** [comment]
Two question for this:
1) Why use `host Network`? In Docker, there is no need to use hostPort mapping feature when using docker `host Network`.
2) With host port mapping, how to handle the case of pod reschedule to another node? I know you may  have some haproxy outside the Kubernetes cluster, but if the pod was rescheduled to other node, who will tell haproxy the node has been changed?

I also filed another issue here https://github.com/kubernetes/kubernetes/issues/43564 , we can check if they are duplicate, I will close https://github.com/kubernetes/kubernetes/issues/43564 if duplicate with this one.

**Comment by wozhengjl** [comment]
@gyliu513 
Q1:
some services need very high performance and traffic, only host mode can meet the requirement.  No hostPort mapping, auto port is used to avoid port conflicts, as there're many different services, the service will listen env PORT, which is assigned by k8s dynamically. 
Q2:
As for the case pod reschedule to another node, pod should be assigned a new available port for the target node, so I hope the port can distinguish between pods although they belong to the same rc.
How to update haproxy, this is another topic about service discovery. we can use consul for service registry, haproxy or nginx can watch the consul for real-time updates, this is not the bottleneck. 

issue #43564 is similar with this one and the solution but not exactly same, the difference is that:
this issue both port and hostport should be assigned automatically, and they are same;
#43564, only hostport is assigned automatically. 
The solution of these 2 issues should be same!

**Comment by gyliu513** [comment]
>some services need very high performance and traffic, only host mode can meet the requirement. No hostPort mapping, auto port is used to avoid port conflicts, as there're many different services, the service will listen env PORT, which is assigned by k8s dynamically.
How does `auto port` works when using `host mode network`? Can you please show a concrete example here? Some steps and some YAML/JSON template? @wozhengjl

**Comment by gyliu513** [comment]
xref https://github.com/coreos/tectonic-installer/issues/1000

**Comment by gyliu513** [comment]
xref https://github.com/kubernetes/kubernetes/issues/23920

We may need some test for this, seems calico can work with host port now. @wozhengjl

**Comment by gyliu513** [comment]
Related with https://github.com/kubernetes/kubernetes/issues/49792

**Comment by coolmary** [comment]
Excellent Host port Certificates Easy Downloads
