### ISSUE TITLE
Replace adler with fnv throughout the repo

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#40140]
adler when brute-forced turns out to break really fast (https://github.com/kubernetes/kubernetes/issues/29735). There are a couple of places we use it in the repo:
```
plugin/pkg/scheduler/equivalence_cache.go
20:	"hash/adler32"
131:	hash := adler32.New()

pkg/kubelet/container/helpers.go
22:	"hash/adler32"
94:	hash := adler32.New()

pkg/kubelet/dockertools/docker_test.go
22:	"hash/adler32"
122:	hasher := adler32.New()

pkg/util/hash/hash_test.go
21:	"hash/adler32"
66:		hasher1 := adler32.New()
75:			hasher2 := adler32.New()
121:		hasher1 := adler32.New()
122:		hasher2 := adler32.New()
123:		hasher3 := adler32.New()

pkg/util/mount/mount_linux.go
24:	"hash/adler32"
285:	hash := adler32.New()

pkg/controller/deployment/util/hash_test.go
122:		t.Errorf("expected adler to break but it didn't")

pkg/controller/deployment/util/pod_util.go
20:	"hash/adler32"
35:	podTemplateSpecHasher := adler32.New()
42:	podTemplateSpecHasher := adler32.New()

pkg/controller/lookup_cache.go
20:	"hash/adler32"
36:	hash := adler32.New()
```
We should probably replace it with fnv.

I tested fnv and it seems to be slightly more expensive but also a lot more stable than adler: https://github.com/kubernetes/kubernetes/pull/39527

**Comment by resouer** [comment]
Just work out a patch to fix this, please take a look.

**Comment by kargakis** [comment]
@yujuhong assigning this to you since the only place left to use adler is in [kubelet](https://github.com/kubernetes/kubernetes/blob/310ea94b6e0694ab08e3aa6185919be92419e932/pkg/kubelet/container/helpers.go#L111) and it's a legacy helper.

**Comment by yujuhong** [comment]
> @yujuhong assigning this to you since the only place left to use adler is in kubelet and it's a legacy helper.

This was removed in #61995
