### ISSUE TITLE
TestCmdTokenGenerate assumes built binary

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#40155]
go test ./cmd/kubeadm/... fails with:

```
--- FAIL: TestCmdTokenGenerate (0.00s)
	token_test.go:40: 'kubeadm ex token generate' exited uncleanly: error running cluster/kubeadm.sh [ex token generate]; got error fork/exec cluster/kubeadm.sh: no such file or directory, stdout "", stderr ""
```

it appears to be following a "RunCmd" pattern used by e2e tests, but unit tests should not require built binaries

**Comment by luxas** [comment]
@dmmcquay can work on this

**Comment by dmmcquay** [comment]
https://github.com/kubernetes/kubernetes/pull/35144 has a long discussion as to why this is.

These tests only get run when `make test-cmd` gets run, which will produce the needed binary and pass it in as `--kubeadm-path` arg. 

For more information, @pipejakob authored this and should be able to provide more details.

**Comment by pipejakob** [comment]
Yup, the `make test` target explicitly ignores these tests:

https://github.com/kubernetes/kubernetes/blob/master/hack/make-rules/test.sh#L38

and like @dmmcquay said, `make test-cmd` runs this script as part of its target:

https://github.com/kubernetes/kubernetes/blob/master/hack/make-rules/test-kubeadm-cmd.sh
https://github.com/kubernetes/kubernetes/blob/master/Makefile#L258

**Comment by liggitt** [comment]
then the test should have build tags to exclude it from a regular `go test` run of the package

**Comment by luxas** [comment]
@dmmcquay or @pipejakob up for fixing that?

**Comment by dmmcquay** [comment]
@liggitt I thought build tags only works on the OS level or if you added `+build ignore` it would ignore it completely? Wouldnt `+build ignore` break the `make test-cmd` command as well?

**Comment by liggitt** [comment]
> then the test should have build tags to exclude it from a regular go test run of the package

I'd also tolerate skipping the test if the built binary doesn't exist

**Comment by dmmcquay** [comment]
@liggitt I think that is a great solution. I think in #35144 I had initially suggested something like that. 

If everyone is ok with that, I will go ahead and make that change.

**Comment by luxas** [comment]
Sounds good, make that change and we'll see how it turns out. 
I'd really want these tests start working, so +1
