### ISSUE TITLE
Create a node test image with docker v1.12.6

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#40163]
Today, node e2e tests different os image (ubuntu, coreos, gci, debian) and two docker versions: docker 1.10, docker 1.11.2, but we are missing the coverage docker 1.12.x. in the matrix.

Meanwhile Kubernetes docker automated validation pipeline is validating the docker release / release candidate through an "golden" kubernetes releases, not the current developing one and the different configurations. For example, there is no test coverage for CRI and docker 1.12.x.

Here is the rough plan: Adding a 1.12 node image in our node e2e test image list, so that all node e2e tests can run against it. 

cc/ @sig-node-misc@ @Random-Liu @yujuhong

**Comment by yujuhong** [comment]
IIRC, we already have the ubuntu image testing docker 1.12.6

**Comment by dchen1107** [comment]
Yeah, I talked to @Random-Liu last week, but forgot to file the issue. Didn't realize that he was done the work. Please feel free to close the issue.

**Comment by Random-Liu** [comment]
> Meanwhile Kubernetes docker automated validation pipeline is validating the docker release / release candidate through an "golden" kubernetes releases, not the current developing one and the different configurations.

Actually currently automated docker validation is running against Kubernetes HEAD and newest docker release.

> Here is the rough plan: Adding a 1.12 node image in our node e2e test image list, so that all node e2e tests can run against it.

Done. :) https://github.com/kubernetes/kubernetes/pull/39889.
