### ISSUE TITLE
Add test_owners.csv check.

### ISSUE THREAD

**Issue by rmmh** [kubernetes/kubernetes#40185]
test_owners.csv must be properly formed, or else the submit queue will get into a crash loop. #40183

A verify check should be able to handle this.

**Comment by lavalamp** [comment]
@ixdy seems to have left a commit message saying something about disabling https://github.com/kubernetes/kubernetes/blob/master/hack/verify-test-owners.sh?

Also @stts just FYI ;)

**Comment by ixdy** [comment]
The script has been disabled basically since it was created - https://github.com/kubernetes/kubernetes/commit/57a152ca404e739b8d123eeebfb618cb09dd6aa0

**Comment by ixdy** [comment]
(I changed it so we'd stop running the script, which kept printing failures and tricking Gubernator even though it didn't actually fail.)
