### ISSUE TITLE
Upgrading docker 1.13 on nodes causes outbound container traffic to stop working

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#40182]
**Kubernetes version** (use `kubectl version`): v1.4.6, v1.5.1, likely many versions

**Environment**:
- **Cloud provider or hardware configuration**: Azure / Azure Container Service
- **OS** (e.g. from /etc/os-release): Ubuntu Xenial
- **Kernel** (e.g. `uname -a`): latest 16.04-LTS kernel
- **Install tools**: Cloud-Init + hyperkube
- **Others**:

**Configuration Details**:

* `kubelet` runs in a container
* master services run as static manifests
* kube-addon-manager runs as a static manifest
* `kube-proxy` runs in iptables mode via a daemonset

**What happened**:
After upgrading to docker 1.13.0 on the nodes, outbound container traffic stops working

**What you expected to happen**:
Outbound container traffic to work (aka, I can hit the internet and service ips from inside the container)

**How to reproduce it** (as minimally and precisely as possible):
Deploy an ACS Kubernets cluster. If the workaround has rolled out, then force upgrade docker to 1.13 (you'll have to remove a pin we're setting in /etc/apt/preferences.d).

Unclear if this repros on other configurations right now.

**Anything else do we need to know**:

No, I just don't know where/how to best troubleshoot this.

**Comment by kargakis** [comment]
@kubernetes/sig-node-misc

**Comment by dkerwin** [comment]
Can confirm the problem with k8s 1.4.7 & docker 1.13 on debian jessie. kubelet managed by systemd

**Comment by colemickens** [comment]
Since the team @kargakis tagged here is no longer a team... cc: @kubernetes/sig-node-bugs

**Comment by bboreham** [comment]
Docker [changed the default iptables forwarding policy to DROP](https://github.com/docker/docker/pull/28257), which has effects like this.

You can change the policy to ACCEPT (which it was in Docker 1.12 and before) by running:

    sudo iptables -P FORWARD ACCEPT

on every node.  You need to run this in the host network namespace, not inside a pod namespace.

**Comment by david-dumas** [comment]
> sudo iptables -P FORWARD ACCEPT

Tested out and working

**Environment:**
- Cloud provider: AWS
- OS: Ubuntu Server 16.04 LTS
- Kernel: 4.4.0-59
- Kubernetes: 1.5.2
- Docker: 1.13
- Network: VPC with NAT gateway, internet gateway, public & private subnets

**Comment by feiskyer** [comment]
> Docker 1.13 changed the default iptables forwarding policy to DROP, which has effects like this.

Could someone explain why docker defaulting to DROP? Does this mean containers of docker v1.13 can't connect outside by default?

**Comment by bboreham** [comment]
@feiskyer generally the Linux default is to have IP forwarding off.
Docker used to turn it on across the board, which was (a) unnecessary and (b) a security issue.  1.13 removed this issue.

Docker add two specific rules which allow traffic off their bridge, and replies to come back:

```
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
```

CNI providers which do not use the `docker0` bridge need to make similar provision.

**Comment by bboreham** [comment]
@colemickens can you clarify which network plugin you are using - is it `kubenet`?

**Comment by Karimerto** [comment]
This thread sure was a lifesaver, though sadly I found it about 14 hours too late.. I managed to wipe my entire cluster and reinstall everything, with the same issue still persisting. I was about to lose my mind trying to figure out why half of my original cluster was working and the other wasn't. Those which didn't work were installed and added later with docker 1.13, so this explains everything.

Now I've got everything up and running again!

Thanks again for this :+1:

**Comment by jbeda** [comment]
The docker change that caused this: https://github.com/docker/docker/pull/28257

**Comment by colemickens** [comment]
(@bboreham Yes, it was `kubenet`.)

**Comment by jbeda** [comment]
The way that services work with iptables mean that we will be initiating connections in to the bridge.  As such, we need to be more permissive than the `docker0` lines above as we won't already have a connection for incoming connections.  Here is what I had to do (my bridge is called cni0):

```
iptables -A FORWARD -i cni0 -j ACCEPT
iptables -A FORWARD -o cni0 -j ACCEPT
```

**Comment by antoineco** [comment]
It used to be recommended to start Docker with `iptables=false` and `--ip-masq=false` in a Kubernetes deployment, would it be a viable approach to ensure these are effectively disable using a `kubelet` flag?

**Comment by bboreham** [comment]
Personally I would be happier with the minimum required to make Kubernetes work, rather than blanket turning on IP forwarding from anywhere to anywhere.

Also, it seems to me that specifying `--iptables=false` while leaving `--ip-forward` defaulted to `true` is a very obscure way to arrive at your desired result.

**Comment by aaron-trout** [comment]
This also appears to stop NodePort services from working. (Thanks to @bboreham for the workaround!)

**Comment by jbeda** [comment]
sorry -- accidental close

**Comment by dchen1107** [comment]
Supporting docker 1.13.x is not targeted for 1.6 from the node team planning from the day one. 

In 1.6 release, we plan to drop the support for docker 1.9.x, and continue supporting 1.10, 1.11.2 and 1.12.6. Again, each one of docker releases has its own set of bugs / regressions, the node team tries to catch them, workaround them and documented them as known issues for each release. 

Removing this from 1.6 milestone. But welcome to help us debug and fix the issue.

**Comment by david-dumas** [comment]
Reading the current changelog, the latest validated docker version is 1.12.3:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#external-dependency-version-information

This is not up to date ? Where do you check for the supported docker versions otherwise ? @dchen1107

**Comment by yujuhong** [comment]
@david-dumas you were looking at the 1.5 changelog, while @dchen1107 was talking about the upcoming 1.6 release.

**Comment by jimmycuadra** [comment]
Note that this is a problem if someone uses an OS where Docker 1.13+ was installed initially and then they manually downgraded to Docker 1.12 for Kubernetes support. Docker doesn't clean up after itself on downgrade and leaves things in a state that breaks Kubernetes.

**Comment by mbentley** [comment]
If I am understanding this issue fully, instead of doing as recommended [here](https://github.com/kubernetes/kubernetes/issues/40182#issuecomment-276392353) which wouldn't persist, then you can set `net.ipv4.ip_forward=1` in `/etc/sysctl.conf` prior to Docker starting and that should give the desired result.  That should give you the default behavior of `ACCEPT` instead of `DROP` as https://github.com/moby/moby/pull/28257 mentions that it will not change the default behavior if `net.ipv4.ip_forward=1` is already set prior to Docker running.

**Comment by PavelPrischepa** [comment]
> sudo iptables -P FORWARD ACCEPT

@bboreham is there any way to make it persist? It looks like docker overrides it each reboot.

**Comment by PavelPrischepa** [comment]
@mbentley It works but It seems too insecure `iptables -P FORWARD ACCEPT` + `net.ipv4.ip_forward=1`.

**Comment by mbentley** [comment]
Gotcha.  Might be considered a bit of a workaround and I haven't tested it fully but it might be possible to add a `ExecStartPost` directive to the systemd unit file to execute `iptables -P FORWARD ACCEPT` after Docker starts to automatically set it.

**Comment by cmluciano** [comment]
@bboreham Do we think this should be closed with a note to CNI plugins? I agreed that embedding this within kubelet or kubenet may make too many assumptions.

**Comment by cmluciano** [comment]
cc @dcbw @caseydavenport @squeed @dnardo

**Comment by bboreham** [comment]
Not sure whether a "note to CNI plugins" is enough.  For an install at GCP, using the CNI `bridge` plugin, who would read the note?

I could see you making it a _requirement_ on CNI plugins, i.e. create an issue for the `bridge` plugin and write into the Kubernetes documentation that Kubernetes has this requirement on any CNI plugin, if used with Docker 13+.

**Comment by cmluciano** [comment]
The latter was my thinking.

The bridge plugin seems to already do this https://github.com/containernetworking/plugins/blob/master/plugins/main/bridge/bridge.go#L303.

**Comment by luxas** [comment]
Do we have an update on this issue as docker 1.13 is targeted for v1.8 and docker 1.12 is EOL soon (November)? Nothing we have to do in the kubelet is the conclusion, right?

**Comment by yguo0905** [comment]
> Nothing we have to do in the kubelet is the conclusion, right?

Yes, I will let @freehan and @bowei to confirm.

**Comment by dims** [comment]
Could we detect the situation in kubelet and log a warning (to set `iptables -P FORWARD ACCEPT`)?

**Comment by euank** [comment]
@dims I don't think we can properly detect the situation.
There's no general way to look at a CNI plugin and know that it supports doing the right thing.

I also would strongly prefer not recommending that users set `ACCEPT` so broadly since it has security implications.

**Comment by dims** [comment]
@euank Ack. Sounds fair.

**Comment by JensErat** [comment]
Are there already known issues with Docker 17.06, or have there just been no efforts verifying it yet?

**Comment by luxas** [comment]
@JensErat Validating 17.03 is in progress and targeted for v1.8 https://github.com/kubernetes/kubernetes/issues/42926
Which to me implicitely means no validation of 17.06 yet

However, if that's something you'd like to see, sync with the node team and help out :smile:

**Comment by yguo0905** [comment]
> @JensErat Validating 17.03 is in progress and targeted for v1.8 #42926
Which to me implicitely means no validation of 17.06 yet

Yeah, no plan for 17.06 validation in 1.8.

**Comment by euank** [comment]
As i understand it, the solutions are roughly:
1. If you use `docker` for your networking rather than cni, everything still works
1. If you use kubenet or CNI for your networking, then update your plugins

Are there any CNI plugins or network configurations that don't handle this correctly?

Unless there's any specific configurations that are still broken and can be tracked in this issue, I think we can close it.

**Comment by caseydavenport** [comment]
@euank I'm not entirely convinced this is the responsibility of CNI plugins. It's discussed above, and some plugins do include workarounds, but manipulating the host to allow forwarding of traffic feels squarely outside of a CNI plugin's responsibilities as I understand them.

I think we still need a solution for this in Kubernetes. 

CC @tmjd

**Comment by squeed** [comment]
We're adding a "allow this interface" chained plugin in to the CNI repository. It's a clean solution to this problem.

https://github.com/containernetworking/plugins/pull/75

**Comment by digglife** [comment]
@bboreham it works. Thank you!

**Comment by feiskyer** [comment]
@squeed iptables-allow is cool. We should document this clearly when the plugin is ready.

**Comment by sathieu** [comment]
#52569 looks to be the proper fix for this (since v1.9.0-alpha.2).

**Comment by cmluciano** [comment]
closed with https://github.com/kubernetes/kubernetes/pull/52569

**Comment by gtaylor** [comment]
To make this easier for those in the future: this got merged and released in 1.8.4.

**Comment by QiuMike** [comment]
> FORWARD -i docker0 ! -o docker0 -j ACCEPT -A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

this does not make it work even though the packet forward use docker0, because the packet from other node will not be in ctstate RELATED or ESTABLISHED, the first packet will be NEW, and this packet will be drop, so it will never be in ESTABLISHED state

**Comment by christianri** [comment]
I experienced the same issue on Kubernetes with the Calico network stack under Debian Buster.

Checking a lot of configs and parameters, I ended up with getting it to work by changing the policy for the forward rule to ACCEPT. This made it clear that the issue is somewhere around the firewall.

Running iptables -L gave me the following unveiling warning: # Warning: iptables-legacy tables present, use iptables-legacy to see them

The output given by the list command does not contain any Calico rules. Running iptables-legacy -L showed me the Calico rules, so it seems obvious now why it didn't work. So Calico seems to use the legacy interface.

The issue is the change in Debian to iptables-nft in the alternatives, you can check via:

ls -l /etc/alternatives | grep iptables

Doing the following:
```
update-alternatives --set iptables /usr/sbin/iptables-legacy
update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
update-alternatives --set arptables /usr/sbin/arptables-legacy
update-alternatives --set ebtables /usr/sbin/ebtables-legacy
```
Now it works all fine! Thanks to Long at the Kubernetes Slack channel for pointing the route to solving it.
