### ISSUE TITLE
local-up-cluster causes error: You must be logged in to the server (the server has asked for the client to provide credentials)

### ISSUE THREAD

**Issue by ahakanbaba** [kubernetes/kubernetes#40192]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

Searched for:

 is:issue is:open local-up-cluster  error: You must be logged in to the server (the server has asked for the client to provide credentials)  

I did not find anything relevant. 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): 
BUG REPORT 

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.3557+05c2a0825e39be-dirty", GitCommit:"05c2a0825e39beee3de7e7bb1b49d8083ef90d65", GitTreeState:"dirty", BuildDate:"2017-01-20T01:19:49Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.3557+05c2a0825e39be", GitCommit:"05c2a0825e39beee3de7e7bb1b49d8083ef90d65", GitTreeState:"clean", BuildDate:"2017-01-19T18:10:47Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
Local Laptop  Mac OS 10.11.06
- **Cloud provider or hardware configuration**:
VirtualBox Vagrant 
- **OS** (e.g. from /etc/os-release):
centos7.2 in vagrant vm
- **Kernel** (e.g. `uname -a`):
Linux k8s-env 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:

After running hack-local-up-cluster.sh the script prints the following 

```
  export KUBERNETES_PROVIDER=local

  cluster/kubectl.sh config set-cluster local --server=https://localhost:6443 --certificate-authority=/var/run/kubernetes/apiserver.crt
  cluster/kubectl.sh config set-credentials myself --username=admin --password=admin
  cluster/kubectl.sh config set-context local --cluster=local --user=myself
  cluster/kubectl.sh config use-context local
  cluster/kubectl.sh
```

Running these results in an authentication error 

```
[vagrant@k8s-env kubernetes]$
[vagrant@k8s-env kubernetes]$   export KUBERNETES_PROVIDER=local
[vagrant@k8s-env kubernetes]$
[vagrant@k8s-env kubernetes]$   cluster/kubectl.sh config set-cluster local --server=https://localhost:6443 --certificate-authority=/var/run/kubernetes/apiserver.crt
Cluster "local" set.
[vagrant@k8s-env kubernetes]$   cluster/kubectl.sh config set-credentials myself --username=admin --password=admin
User "myself" set.
[vagrant@k8s-env kubernetes]$   cluster/kubectl.sh config set-context local --cluster=local --user=myself
Context "local" set.
[vagrant@k8s-env kubernetes]$   cluster/kubectl.sh config use-context local
Switched to context "local".
[vagrant@k8s-env kubernetes]$   cluster/kubectl.sh cluster-info
error: You must be logged in to the server (the server has asked for the client to provide credentials)
````

**What you expected to happen**:

I would have expected to authenticate with the api server. 

**How to reproduce it** (as minimally and precisely as possible):

Go over the same steps 

**Anything else do we need to know**:

In the problematic case, the ~/.kube/config file looks like the following

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /var/run/kubernetes/apiserver.crt
    server: https://localhost:6443
  name: local
contexts:
- context:
    cluster: local
    user: myself
  name: local
current-context: local
kind: Config
preferences: {}
users:
- name: myself
  user:
    password: admin
    username: admin
```

Setting  ALLOW_ANY_TOKEN is one workaround. 
```
export ALLOW_ANY_TOKEN=true
```
With this env var the cluster/kubectl.sh command can talk to the api server. 

I recommend to start from a clean slate to reproduce the issue. 

Once the authentication succeeds with setting the ALLOW_ANY_TOKEN=true, I have tried to go back and restart the local-up-cluster with  ALLOW_ANY_TOKEN=false again. In the second attempt the authentication SUCCEEDED. So I see the problem only at the first attempt.

**Comment by liggitt** [comment]
the printed instructions need updating. an `/var/run/kubernetes/admin.kubeconfig` is generated by default and populated with the right address and a client cert that gives you superuser access.

**Comment by ahakanbaba** [comment]
Thanks @liggitt 
Thanks for the tip. 

I see your comments in  #40193 probably that will also improve the printed instructions.
