### ISSUE TITLE
Export memory request value via Prometheus metrics

### ISSUE THREAD

**Issue by JorritSalverda** [kubernetes/kubernetes#40214]
**FEATURE REQUEST**

I'd like to be able to see the value for memory request for every container in Prometheus. I can already see memory limit (via `container_spec_memory_limit_bytes`), cpu request (via `container_spec_cpu_shares`) and cpu limit (via `container_spec_cpu_quota`). But memory request seems to be missing.

I'm not sure if the Kubernetes project is the right one to file this issue, it might be a different application that's responsible for exporting this information? cadvisor?

I'm on GKE version 1.5.1 running the GCI image.

**Comment by smarterclayton** [comment]
@DirectXMan12 does metrics / monitoring have a SIG team to @?

**Comment by baracoder** [comment]
I am currently trying to improve utilization of nodes. This would be really helpful.
:+1:

**Comment by DirectXMan12** [comment]
@smarterclayton it would be SIG instrumentation, but it looks like there's no teams.  I'll ping the SIG leads about it.

**Comment by dragondscv** [comment]
Any update on this one? This would be useful.

**Comment by JorritSalverda** [comment]
/remove-lifecycle rotten

Do we perhaps need to create a ticket for cadvisor to include this instead?

**Comment by DirectXMan12** [comment]
we have vague plans to talk about how we want to deal with exposed metrics in sig-instrumentation soon.  That'll be a good place to bring this up.

**Comment by csghuser** [comment]
Any update on this?

**Comment by ehashman** [comment]
I am using `kube_pod_container_resource_requests_memory_bytes` from kube-state-metrics to retrieve this stat.

**Comment by wtan825** [comment]
Any update on this?

**Comment by ehashman** [comment]
I've taken a deeper look at this and found that this is a cadvisor/container runtime issue, not a Kubernetes issue. I don't think it makes sense to try to add these metrics as requested in this ticket, and I'll try to explain why.

cadvisor metrics are registered here, unmodified:

https://github.com/kubernetes/kubernetes/blob/58323cbf4e0efa7be1b43eae04beb0a37494312f/pkg/kubelet/server/server.go#L308-L318

All those `cadvisormetrics.MemoryUsageMetrics` (container metrics for memory) are specified in the upstream cadvisor repo:

https://github.com/google/cadvisor/blob/83240cc997e91ec38fb853c07ff318491bd354cb/metrics/prometheus.go#L324-L417

You'll see that there isn't an available metric in cadvisor corresponding to a memory request. I suspect this has to do with the implementation of memory requests, cgroups, and memory soft limits, which are [basically ignored](https://medium.com/@betz.mark/understanding-resource-limits-in-kubernetes-memory-6b41e9a955f9) from a container runtime perspective (see the bit on soft limits).

Hence, this isn't really something cadvisor can collect; Kubernetes memory requests are not set in/passed along to the container runtime. They only exist as part of your cluster state. Hence, you'll need to run kube-state-metrics and use the `kube_pod_container_resource_requests_memory_bytes` timeseries as I suggested above; it's not possible to export this as part of the default `container_*` metrics.
