### ISSUE TITLE
[FEATURE REQUEST] Environment variables for headless services

### ISSUE THREAD

**Issue by abhishekagarwal87** [kubernetes/kubernetes#40219]
Right now, we use environment variables to discover services with cluster IP. It would be good to have environment variables set up for headless services as well. This way, the pod definition does not need to change if a service consumed by the pod becomes headless.

**Comment by ChrisPenner** [comment]
/reopen
/remove-lifecycle rotten

Any news on this? It seems strange to me that headless services don't get env vars whereas other services do.
