### ISSUE TITLE
Trim long lines in fluentd

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#40212]
There'a a [Stackdriver limits](https://cloud.google.com/logging/quota-policy) on the log entry size.

When fluentd plugin for Stackdriver encounters bulk with the entry which is too big, it drops the whole bulk. There's an option in the upcoming release to drop only those lines, which don't fit in the qouta. However, dropping entries completely doesn't seems like a good idea, especially since such entries usually indicate errors and misconfigurations.

Proposed solution is to configure Stackdrvie fluentd agent to trim long lines by default.

CC @piosz @igorpeshansky

**Comment by piosz** [comment]
Alternative solution is to use [partialSuccess](https://cloud.google.com/logging/docs/api/reference/rest/v2/entries/write#request-body) feature from Stackdriver API (assuming this will be supported in agent code for 1.6), which is the dedicated Stackdriver solution for such situation rather than a kind of hack.

**Comment by igorpeshansky** [comment]
FYI, we plan to enable partialSuccess in the logging agent as part of migration to the V2 logging API.

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by piosz** [comment]
@crassirostris would be great to have it earlier than for 1.7. (in a patch release for example)

cc @fgrzadkowski

**Comment by crassirostris** [comment]
@igorpeshansky Is partial success included in `0.6.0+`?

**Comment by crassirostris** [comment]
Blocked by https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/129

**Comment by igorpeshansky** [comment]
@crassirostris No, partial success didn't make it into the current plugin release.

**Comment by crassirostris** [comment]
Oh, OK, then moving this to the next release

**Comment by crassirostris** [comment]
@igorpeshansky But this seems like a very important thing that should be cherry-picked to 1.6 and 1.7 once available

**Comment by igorpeshansky** [comment]
@crassirostris FYI, https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/129 has been merged, and will be in the next build. We'll notify you when partial success support is completed.

**Comment by crassirostris** [comment]
@igorpeshansky Thanks!

**Comment by dims** [comment]
@crassirostris looks like we'll need to move this out of 1.8 or close it right?

**Comment by crassirostris** [comment]
@dims Whoops, it's actually closed by https://github.com/kubernetes/kubernetes/pull/52289 in 1.8. Thanks for reminding!
