### ISSUE TITLE
"kubectl rollout status" returns error message before rollout finish

### ISSUE THREAD

**Issue by fwynyk** [kubernetes/kubernetes#40224]
When we execute `kubectl rollout status`, we're receiving this error:
```
kubectl rollout status deployment/app --namespace=app
Waiting for rollout to finish: 2 out of 6 new replicas have been updated...
Waiting for rollout to finish: 2 out of 6 new replicas have been updated...

error: timed out waiting for the condition
```
I also tried to put the option `-w`, but it did't change anything.

Since we upgraded to Kubernetes 1.5.2 we're receiving this. In 1.4.6 it works with no problems. I've tried to update `kubectl` and use previous versions too, but seems to be a problem with the cluster, not with `kubectl` command.  

This is a problem for us because Jenkins is using this command to monitor the deployment status, so our builds are crashing in the end. 

We're running the cluster on AWS  with Kops provisioning.

**Comment by kargakis** [comment]
Can you post the yaml of your deployment and involved replica sets when the `rollout status` command exits with the timeout?

**Comment by fwynyk** [comment]
Here they are. But I think I was not clear: this timeout error didn't cause any trouble in the deployment itself. The deployment runs in background with no problems, and the new version works. But we can't monitor (get the health of ) the deployment if the command runs into a timeout. We need to run it more than once to monitor the deploy until it ends, and this situation didn't work in a CI/CD.



[deployment.yml.txt](https://github.com/kubernetes/kubernetes/files/727348/deployment.yml.txt)
[replicaset.yml.txt](https://github.com/kubernetes/kubernetes/files/727349/replicaset.yml.txt)
[getReplicaset.yml.txt](https://github.com/kubernetes/kubernetes/files/727350/getReplicaset.yml.txt)

**Comment by kargakis** [comment]
One replica set (presumably the old one) is missing from your yamls (note that I asked for all involved replica sets), also the deployment yaml is not complete. Can you post the deployment including its status when you hit the timeout (and the other replica set)? Probably irrelevant but it seems that there is an annotation missing from the deployment (the one that denotes its revision). Last, is it possible to paste logs from the controller manager with a verbosity level of 4 when the timeout is hit? How reproducible is the issue?

**Comment by fwynyk** [comment]
The deployment yaml is complete. It's the same yaml file we used to run in the 1.4.6 cluster, and it worked there. 

Here's the output of verbosity level 4:

```
$ kubectl rollout status deployment/app --namespace=app -v4
Waiting for rollout to finish: 4 out of 6 new replicas have been updated...
Waiting for rollout to finish: 5 out of 6 new replicas have been updated...
Waiting for rollout to finish: 5 out of 6 new replicas have been updated...
Waiting for rollout to finish: 2 old replicas are pending termination...
I0124 16:02:14.753283    3195 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
F0124 16:02:14.753919    3195 helpers.go:116] error: timed out waiting for the condition
```

But I took a look in a verbosity level 10 and found this:

```
I0124 16:08:08.809926    3563 round_trippers.go:324] Response Headers:
I0124 16:08:08.809951    3563 round_trippers.go:327]     Content-Type: application/json
I0124 16:08:08.809974    3563 round_trippers.go:327]     Date: Tue, 24 Jan 2017 18:08:08 GMT
I0124 16:09:07.935235    3563 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
F0124 16:09:07.935363    3563 helpers.go:116] error: timed out waiting for the condition
```

It seems a timeout, 60 seconds. I remember in the old stack (1.4.6) that we receive more updates about the rollout status, even if nothing was changed. Now seems that we only receive updates when something changes, like the number of replicas updated. Also, looking at this probelm, I think if we have applications which demands more time to get ready,  this kind of situation will be more frequent.

 If `kubectl rollout status` could have an option to set a status refresh, maybe this problem would be solved.


[new-replicaset.yml.txt](https://github.com/kubernetes/kubernetes/files/727579/new-replicaset.yml.txt)
[old-replicaset.yml.txt](https://github.com/kubernetes/kubernetes/files/727580/old-replicaset.yml.txt)

**Comment by kargakis** [comment]
> The deployment yaml is complete. It's the same yaml file we used to run in the 1.4.6 cluster, and it worked there.

The deployment yaml lacks the status part (deployments created from a yaml file don't contain status - you need to get the yaml back when `rollout status` gets stuck: `kubectl get deployment/app -o yaml`).

> Here's the output of verbosity level 4:

I was asking about the controller manager logs iow. logs from the master and not from kubectl.

Also can you verify that the status of the deployment (.status.availableReplicas) reflects the status of the underlying pods once `rollout status` gets stuck? You should see that .status.availableReplicas equals the ready pods of your app.

**Comment by kargakis** [comment]
Can you also make sure that there is no clock skew between master and other nodes?

**Comment by kargakis** [comment]
@fwynyk since you upgraded from 1.4.6 to 1.5.2 did you by any chance see anything related to https://github.com/kubernetes/kubernetes/issues/40415?

**Comment by kargakis** [comment]
This may also be an issue with watch.Until.

**Comment by kargakis** [comment]
> This may also be an issue with watch.Until.

Most likely. It seems that the watch loop used by `rollout status` [is never supposed to stop](https://github.com/kubernetes/kubernetes/blob/61e7d1ebf1e19023bc48cc573fbbbe20f0f01f0d/pkg/kubectl/cmd/rollout/rollout_status.go#L150).

**Comment by kargakis** [comment]
@kubernetes/sig-cli-bugs

**Comment by ymqytw** [comment]
We use [0 as timeout](https://github.com/kubernetes/kubernetes/blob/9498a1270f54b6f3353ceb70b53a3746e4f952e0/pkg/kubectl/cmd/rollout/rollout_status.go#L152). [It doesn't set up any timeout](https://github.com/kubernetes/kubernetes/blob/9498a1270f54b6f3353ceb70b53a3746e4f952e0/staging/src/k8s.io/apimachinery/pkg/watch/until.go#L44-L50). I don't find out how it [reach the timeout error](https://github.com/kubernetes/kubernetes/blob/9498a1270f54b6f3353ceb70b53a3746e4f952e0/staging/src/k8s.io/apimachinery/pkg/watch/until.go#L81-L82).
@kargakis Any idea? How can we reproduce this?

**Comment by kargakis** [comment]
Not sure how to reproduce, but a wrapper to handle the case would suffice. See https://github.com/kubernetes/kubernetes/pull/33942#issuecomment-285462983

**Comment by ymqytw** [comment]
@fwynyk Do you still have this issue in 1.5.4 release?
Someone has similar issue has been fixed in 1.5.4 https://github.com/kubernetes/kubernetes/issues/41336#issuecomment-285722917

**Comment by coulix** [comment]
I still have the issue on 1.6.2

**Comment by kargakis** [comment]
@kubernetes/sig-cli-bugs @kubernetes/sig-api-machinery-bugs either fix watch.Until or remove

**Comment by sampowers** [comment]
I'm getting this periodically when running my kubectl connection across a stateful firewall, where the connection may be periodically reset if idle for a period.  I don't know what the idle period is.  But I'm getting ready to make a bandaid shell script for our usage of kubectl rollout status.  Just in case that motivates anyone to make watch.Until more robust.

I hope this was useful feedback.  Maybe forcing a connection reset would help in reproducing the issue?

**Comment by kargakis** [comment]
@sampowers would you be interested in working on fixing `rollout status` rather than writting that script? :) Most people (myself included) seem to be fairly busy but we would love to spare review time.

**Comment by keyan** [comment]
I was seeing the same error as OP when using `kubectl` v1.5.6 but upon upgrading to `v1.7.0-beta.2` I'm seeing a different error:

```
Waiting for rollout to finish: 2 out of 4 new replicas have been updated...
error: watch closed before Until timeout
```

This is thrown by [this line](https://github.com/kubernetes/kubernetes/blob/ad4d9657115ba6f499a419f9df2eb2c9d55a92f8/staging/src/k8s.io/apimachinery/pkg/watch/until.go#L68). I'm consistently seeing the error after `kubectl` has executed the `status` command for exactly 10 minutes.

The change I made in #47617 doesn't seem relevant anymore. Initially I thought I was somehow hitting the seemingly impossible select case from the `after` channel. But it is clear to me now that `Until` was failing at the same location in `v1.5.6` except [the error thrown](https://github.com/kubernetes/kubernetes/blob/4b61b4be2e60d4220d6fcf280e36289209a188dd/pkg/watch/until.go#L64) is different.

The issue of timing out after 10 minutes remains the same.

**Comment by mooperd** [comment]
+1

**Comment by skylerto** [comment]
+1

**Comment by hlubek** [comment]
We are having the same issue when checking for deployments in our GitLab / K8s infrastructure:

```
Waiting for rollout to finish: 0 of 1 updated replicas are available...
E1207 11:03:06.765491     137 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 5; INTERNAL_ERROR
error: watch closed before Until timeout
```

**Comment by bryanleekw** [comment]
I am having the same issue
bryanleekw@nb1:/proj/kubernetes$ kubectl rollout status deployment/monitor-scale
Waiting for rollout to finish: 0 of 1 updated replicas are available...
Waiting for rollout to finish: 0 of 1 updated replicas are available...
error: watch closed before Until timeout

my kubectl version is: 
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bryanleekw** [comment]
may I know how can I check rollout status by log files?

**Comment by gavk34** [comment]
Seeing this also
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T20:00:41Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.8-gke.0", GitCommit:"6e5b33a290a99c067003632e0fd6be0ead48b233", GitTreeState:"clean", BuildDate:"2018-02-16T18:26:58Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Sample log output
```
07-Mar-2018 08:04:41	2018/03/07 08:04:41 Waiting for rollout to finish: 0 of 1 updated replicas are available...
07-Mar-2018 08:04:41	Waiting for rollout to finish: 0 of 1 updated replicas are available...
07-Mar-2018 08:04:41	error: watch closed before Until timeout
07-Mar-2018 08:04:41	2018/03/07 08:04:41 Error occurred when running 'apply' command: exit status 1
```

**Comment by creinheimer** [comment]
Same problem here:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.10-rancher1", GitCommit:"66aaf7681d4a74778ffae722d1f0f0f42c80a984", GitTreeState:"clean", BuildDate:"2018-03-20T16:02:56Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

Log output:

```
Waiting for rollout to finish: 1 old replicas are pending termination...
F0329 14:43:18.723237    9889 helpers.go:119] error: watch closed before Until timeout
```

**Comment by tnozicka** [comment]
Fix is here https://github.com/kubernetes/kubernetes/pull/50102

/sig apps

**Comment by supereagle** [comment]
**Meet the same problem：**
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.9", GitCommit:"19fe91923d584c30bd6db5c5a21e9f0d5f742de8", GitTreeState:"clean", BuildDate:"2017-10-19T17:09:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.9", GitCommit:"19fe91923d584c30bd6db5c5a21e9f0d5f742de8", GitTreeState:"clean", BuildDate:"2017-10-19T16:55:06Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
# kubectl rollout status deploy test
Waiting for rollout to finish: 0 out of 2 new replicas have been updated...
Waiting for rollout to finish: 0 out of 2 new replicas have been updated...
error: watch closed before Until timeout
```


**root cause：**
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
  namespace: default
spec:
spec:
  paused: true    # Should be false.
  ...
```

**Solution：**

Set `.spec.paused` as false.

`.spec.paused` is an optional boolean field for pausing and resuming a Deployment. It defaults to false (a Deployment is not paused).

xref: http://kubernetes.kansea.com/docs/user-guide/deployments/#paused

**Comment by guineveresaenger** [comment]
@tnozicka can you update on whether any work is being done on this?
As Code Slush begins this Tuesday, please make sure this issue is labeled as approved for the milestone by then.
https://github.com/kubernetes/sig-release/tree/master/releases/release-1.12#code-slush

**Comment by tnozicka** [comment]
@guineveresaenger there is a PR, https://github.com/kubernetes/kubernetes/pull/67817 linked just above your comment, fixing the issue; in review process, still targeting v1.12

**Comment by guineveresaenger** [comment]
@tnozicka awesome! can you get milestone approval from someone in sig/apps?

**Comment by tnozicka** [comment]
/priority critical-urgent

@guineveresaenger is this for `status/approved-for-milestone`? I though that was effectively canceled on lazy consensus last week here https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-dev/MjyJzhBEgkM/64kNFcIACQAJ

**Comment by guineveresaenger** [comment]
@tnozicka gah, apologies for the noise. You are right. My bad.

**Comment by tnozicka** [comment]
@guineveresaenger np :)

**Comment by ocofaigh** [comment]
Any plans to backport this fix to v1.11?

**Comment by arocki7** [comment]
If you use an AWS Load balancer, you want to increase the timeout value.

**Comment by zyfu90** [comment]
You could add a timeout flag to the kubectl rollout status command.

```
kubectl rollout status deployment/app --namespace=app --timeout=60s
```
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-status-em-

**Comment by arocki7** [comment]
@zyfu90 Even if you add this, the rollout will still fail - because it's the load balancer timeout which kills the watch and not Kubernetes. The error message clearly says that Kubernetes watch failed even before kubectl timeout.

**Comment by Jonnymcc** [comment]
@arocki7 You mean the ELB idle timeout? Which would imply that while running rollout status the connection could be idle for that time? Doesn't the rollout status command poll for the status of the deployment?

**Comment by arocki7** [comment]
@Jonnymcc Unfortunately, `rollout status` didn't do a poll for every few seconds - which is why it fails.

**Comment by hazzyeer** [comment]
Scale up your deployment and apply your deployment and service files, then back to your desired state.
