### ISSUE TITLE
addon: fluentd-elasticsearch, time_format and timezones

### ISSUE THREAD

**Issue by equinox0815** [kubernetes/kubernetes#40226]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): fluentd timezone time_format

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:

Log lines from docker have the wrong timestamp.

**Anything else do we need to know**:

We are building a custom Docker Image for  fluentd/td-agent which is based on your Dockerfile but with some slight changes. One of which is that we set the timezone to something else than UTC. In this case fluentd will produce wrong timestamps for log lines since the [time_format](https://github.com/kubernetes/kubernetes/blob/53b43d6f8f505834b95967c5a8804bf401ad01e7/cluster/addons/fluentd-elasticsearch/fluentd-es-image/td-agent.conf#L116) string only includes a simple Z in the end.

Changing the time_format to ```%Y-%m-%dT%H:%M:%S.%N%Z``` fixed the problem for us.

Of course this is not really a bug in kubernetes but changing the default to the above will probably help others in the future.

**Comment by Crassirostris** [comment]
@equinox0815 Thanks for reporting! It seems to be a bug
