### ISSUE TITLE
joyent triton public cloud cannot start service containers

### ISSUE THREAD

**Issue by joejulian** [kubernetes/kubernetes#40238]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): joyent triton

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

Joyent Triton provides their own docker api to their lx brand container system. This api does not implement any network support at all. By setting `network-plugin=""` I can successfully bring up pod containers, but the service containers pass `container:%v` to network, causing the joyent api to respond with an error.

This changed with https://github.com/kubernetes/kubernetes/commit/244152544ce#diff-e2eefa11d78ba95197ce406772c18c30R2317

Add a switch to override this behavior.

**Kubernetes version** (use `kubectl version`):
version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Joyent Triton
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS
- **Kernel** (e.g. `uname -a`): Linux d1c44610-9e5a-4855-9f54-c27eab561235 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: Manual Install
- **Others**:
$docker_endpoint/version: 
```
{"ApiVersion":"1.21","Arch":"i386","BuildTime":"2016-12-08T06:14:18Z","GitCommit":"8599a55","GoVersion":"node4.6.1","Os":"solaris","Version":"1.9.0"}
```
$docker_endpoint/info: 
```
{"Architecture":"x86_64","Driver":"sdc","DriverStatus":[["SDCAccount","SampleAccount"]],"ExecutionDriver":"sdc-0.4.0","KernelVersion":"3.12.0-1-amd64","LoggingDriver":"json-file","OperatingSystem":"SmartDataCenter","OSType":"linux","Name":"us-sw-1","IndexServerAddress":"https://index.docker.io/v1/","MemoryLimit":true,"SwapLimit":true,"IPv4Forwarding":true,"ID":"baeb1c9e-f518-4bf4-bc18-01b3e0c8406c","Images":13,"Containers":3}
```

**What happened**:
Triton doesn't support any docker api networking options:
```
E0120 18:06:13.647188 2104 pod_workers.go:184] Error syncing pod 83fe05f0-df38-11e6-83c4-90b8d0e7b5d4, skipping: failed to "StartContainer" for "nginx" with RunContainerError: "runContainer: Error response from daemon: (NotImplemented) Container networking is not supported is not implemented (56ea4b66-3df9-4118-992c-dc600aab081d)"
```

**What you expected to happen**:
Since I specifically set `network-plugin=""` I was hoping that would prevent a network field from being passed to the docker api.

**How to reproduce it** (as minimally and precisely as possible):
Manual setup steps at https://github.com/joejulian/kubernetes-the-hard-way/tree/joyent

**Anything else do we need to know**:

**Comment by calebamiles** [comment]
Hello @joejulian, have you been participating in any of the SIG node discussions around the Container Runtime Interface (CRI). Perhaps it makes sense for a native implementation for Triton containers rather than being bound by the Docker API? Are you aiming to get the desired functionality into the Kubernetes 1.6 release? If so I would suggest opening a feature against https://github.com/kubernetes/features before 24 January and looking for a sponsor from @kubernetes/sig-node-misc. I would also suggest attending SIG Node meetings which are Tuesdays at 10:00am PST. If you can commit development resources to the implementation of the feature there's also a much higher chance of it landing. Good luck!

**cc: @dchen1107, @spiffxp**
