### ISSUE TITLE
Allow specifying different backend-protocol for each service port

### ISSUE THREAD

**Issue by TylerRick** [kubernetes/kubernetes#40244]
**What keywords did you search in Kubernetes issues before filing this one?** service.beta.kubernetes.io/aws-load-balancer-backend-protocol, ELB

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report and/or Feature request. Depends on how this is expected to work.

**Kubernetes version** (use `kubectl version`): v1.5.1-rancher1

**Environment**:
- **Cloud provider or hardware configuration**: Amazon EC2
- **OS** (e.g. from /etc/os-release): RancherOS v0.7.1
- **Kernel** (e.g. `uname -a`): 4.4.24-rancher
- **Install tools**: Rancher

**How to reproduce it**:

First, create a service manifest containing:
```
apiVersion: v1
kind: Service
metadata:
  namespace: gitlab
  name: gitlab
  labels:
    name: gitlab
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:...
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
  type: LoadBalancer
  ports:
    - name: ssh
      port: 22
      targetPort: ssh
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: http
  selector:
    name: gitlab
```

and observe that it creates an ELB that shows this under Listeners:

![image](https://cloud.githubusercontent.com/assets/14151/22161428/255223ee-deff-11e6-9e77-2779c3e3dd1e.png)

Note that the *only* port that is given a Load Balancer Protocol of SSL is port 443. The other ports are (apparently) left with a *reasonable default* protocol of TCP.

However, when I add `backend-protocol: http` and change the annotations to:
```
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:...
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
```

**What happened**:

... it changes the protocol of *all* ports, even those that have nothing to do with HTTP and should be left as TCP, like SSH:

![image](https://cloud.githubusercontent.com/assets/14151/22161479/57cbbe3e-deff-11e6-9cd7-796257966fba.png)

But we can't use HTTP for SSH!  And I don't think we can split this into 2 separate services/LoadBalancers because we want to use the same domain name for all the ports...

**What you expected to happen**:

I expect it to only change Load Balancer Protocol to HTTP/HTTPS for ports where that makes sense:

![image](https://cloud.githubusercontent.com/assets/14151/22161540/a563600c-deff-11e6-8823-bb864a6efd9d.png)

(I was able to manually change it to this, but any time I update the service manifest, my manual change will get lost, so that isn't a good solution.)

**How should it know which ports to change the protocol for?**

Ideally, it would let you choose the protocol for each port. Ideally by naming it directly in the ports section... :)
```
spec:
  ports:
    - name: ssh
      port: 22
      targetPort: ssh
      backendProtocol: tcp
    - name: http
      port: 80
      targetPort: http
      backendProtocol: http
    - name: https
      port: 443
      targetPort: http
      backendProtocol: http
```

... but if we're limited to only using annotations, then maybe consider changing `aws-load-balancer-backend-protocol` to accept a JSON object with the mappings, like `{ ssh: 'tcp', http: 'http', https: 'http' }` (If given a string, it could use the same protocol for all ports like it does now.)

This would be similar to how `aws-load-balancer-ssl-ports` lets you only make *some* of your load balancer ports use SSL (#26976/#26268 (Support mixed HTTP/HTTPS ports in ELBs)).

**Other related issues**:

#23880 (Support mixed protocols in service.type=loadbalancer)
#23495 (SSL support for ELB listeners through annotations)
#24978 (annotations for ELB "advanced features")

**Comment by vinayagg** [comment]
This is very confusing. We did some experiments and came up with following rules for mapping of "backend protocols" (aka instance protocols) to Load Balancer protocols
    "https": "https", (certificate is needed)
    "http":  "https", (if certificate is specified front end is https)
    "http":  "http", (if certificate is NOT specified front end is http)
    "ssl":   "ssl", (certificate is needed)
    "tcp":   "ssl", (if port is 443 and SSL annotation is missing)
    "tcp":   "ssl", (if port matches that of annotation: service.beta.kubernetes.io/aws-load-balancer-ssl-ports)
    "tcp":   "tcp", (for all ports which are not mentioned in SSL annotation)

Hope it helps some poor soul out there.

**Comment by dorsegal** [comment]
+1

**Comment by gankit** [comment]
This needs to be documented somewhere. Very confusing :(

**Comment by rafamarangoni** [comment]
+1

**Comment by panchr** [comment]
Is there any update on this? Alternatively, is there a way to "pin down" an ELB port in Kubernetes, to prevent it from updating that port configuration? I need to make sure that one port remains on TCP (i.e. an SSH port) while the rest use HTTP(S).

**Comment by joelhandwell** [comment]
There is 3 types of load balancers in AWS. 
1. Application Load Balancer (ALB) which supports HTTP and HTTPS with SSL cert integration and those 2 are the only available protocols. ALB is for EC2 instances in VPC network.
2. Network Load Balancer (NLB) supporting any TCP but not integrated with SSL cert (for EC2 instances in VPC network)
3. Classic Load Balancer (CLB) for the EC2 instances which is in old generation AWS network (for EC2 instances not in VPC network)

So when using ALB, you cannot use ssh protocol and TCP port 22 seems to be transformed forcefully into HTTP with port 22. And using NLB, you can not integrate with SSL cert. And your instance seems not in classic AWS network so CLB is not applicable here.

**Comment by francesco-beccaria** [comment]
+1
This would be very useful

**Comment by Typositoire** [comment]
+1 indeed!

**Comment by cocotton** [comment]
+1

**Comment by avanier** [comment]
+1 all the things! But this one more than others.

**Comment by paulopez78** [comment]
+1

**Comment by dotanga** [comment]
+1

**Comment by ITBlogger** [comment]
This is still an issue. What's the status on getting this fixed?

**Comment by chenrui333** [comment]
Really would like to see this issue get moved.

**Comment by josselin-c** [comment]
In the mean time, I'm running this script on my cluster to periodically re-configure the ELB:

```
#!/bin/sh
set -e

if [ -z "$ELB" ] || [ -z "$PORT" ]; then
	echo '$ELB and $PORT must be set'
	exit 1
fi

while :; do
	ELB_DESC=$(aws elb describe-load-balancers | jq -r ".LoadBalancerDescriptions[] | select(.LoadBalancerName==\"$ELB\")")
	PORT_LISTENER=$(echo $ELB_DESC | jq -r ".ListenerDescriptions[] | select(.Listener.LoadBalancerPort==$PORT)")
	
	if [ -z "$PORT_LISTENER" ]; then
		echo "PORT $PORT not found in $ELB_DESC"
		exit 1
	fi
	
	PROTOCOL=$(echo $PORT_LISTENER | jq -r '.Listener.Protocol')
	INSTANCE_PROTOCOL=$(echo $PORT_LISTENER | jq -r '.Listener.InstanceProtocol')
	INSTANCE_PORT=$(echo $PORT_LISTENER | jq -r '.Listener.InstancePort')
	
	if [ -z "$PROTOCOL" ] || [ -z "$INSTANCE_PROTOCOL" ] || [ -z "$INSTANCE_PORT" ]; then
	 	echo "Failed to retrieve ELB attribute:"
	 	echo "PROTOCOL: $PROTOCOL"
	 	echo "INSTANCE_PROTOCOL: $INSTANCE_PROTOCOL"
	 	echo "INSTANCE_PORT: $INSTANCE_PORT"
	 	exit 1
	fi
	
	if [ "$PROTOCOL" != "TCP" ] || [ "$INSTANCE_PROTOCOL" != "TCP" ]; then
		echo "Changing port to TCP..."
		aws elb delete-load-balancer-listeners --load-balancer-name $ELB  --load-balancer-ports $PORT
		aws elb create-load-balancer-listeners --load-balancer-name $ELB --listeners "[{ \"Protocol\": \"TCP\", \"LoadBalancerPort\": $PORT, \"InstanceProtocol\": \"TCP\", \"InstancePort\": $INSTANCE_PORT }]"
		echo "Success"
	fi
	sleep 60
done 
```

**Comment by cdenneen** [comment]
+1 

@Naddiseo @duizendnegen Can you explain what alternative options you propose since you are down voting this?

**Comment by duizendnegen** [comment]
My downvote on the +1 topics was not on the issue itself, but to the approach of spamming all participants to this thread with +1, @cdenneen. Github offers the opportunity to subscribe to an issue, and I believe a better way to contribute is to add snippets or stories about how people worked around this, or spend time to solve the root cause of it.

**Comment by saedalavinia** [comment]
Any news on this issue?

**Comment by SumGR** [comment]
> Want to share similar story: We didn't find a way to make same ELB work for both HTTP/S and TCP, so we use separate 2 ones per cluster. One gets all TCP ports (rabbitmq, redis, etc') and other all HTTP/s (and we use ingress for that, not Service type LoadBalancer).

Do you have an example of what your deployments look like? I too just started running into this issue.

**Comment by mandar14** [comment]
> Want to share similar story: We didn't find a way to make same ELB work for both HTTP/S and TCP, so we use separate 2 ones per cluster. One gets all TCP ports (rabbitmq, redis, etc') and other all HTTP/s (and we use ingress for that, not Service type LoadBalancer).

**Comment by thockin** [comment]
So, we used to have `service.alpha.kubernetes.io/app-protocols` which was a per-port map of backend protocol.  That wasn't widely adopted, so we now have `cloud.google.com/app-protocols` in Google's ingress controller.

https://github.com/kubernetes/ingress-gce/blob/c8fd7bfc571b50d71cb68863f162ef8d8951060e/pkg/annotations/service.go

I don't see any reason why we couldn't add a new field to ServicePort to cover this.  We'd need to figure out what values are allowed.  @rramkumar1 @bowei 

Does this impact Endpoints?  @freehan 

Does someone want to write a KEP - this seems relatively constrained...

**Comment by aali28** [comment]
Any update on this issue?

**Comment by thockin** [comment]
I'm going to re-title this since it is not ELB specific

**Comment by happilymarrieddad** [comment]
I want to run all my services with the `http` protocol behind the load balancer but I have 1 service that requires `https`. Is there a way to allow both? Thanks!

I was wondering if there was a way to do this with the `nginx.ingress.kubernetes.io/configuration-snippet`?

Is there a way I can write a rule if a certain subdomain matches then it pushes to a servicePort of 443 otherwise it uses the spec.rules? Basically, my company has a wordpress website that has a cert and has apache included and run under HTTPS inside a docker container and I'm trying to add it to my kubernetes cluster. All my other services are running behind the load balancer under some http port like 3000.

**Comment by TarekAS** [comment]
For Istio users on EKS:
Until this is fixed, here are some possible workarounds: https://github.com/istio/istio/issues/11579#issuecomment-569277030

**Comment by thockin** [comment]
As per https://github.com/kubernetes/kubernetes/issues/40244#issuecomment-510680742, this just needs a small KEP.  It was already added to EndpointSlice, I believe.

@robscott

**Comment by robscott** [comment]
@thockin Just a KEP to add an `AppProtocol` field to Services and Endpoints to match what we have in EndpointSlices? If so, I can write that up.

**Comment by happilymarrieddad** [comment]
Is this still an active Issue? I was wondering if there has been any progress on this. Thanks!

**Comment by lachlanbb** [comment]
+1
For the specific example of having port 53 TCP/UDP with the same service / NLB combo

Currently it errors with
'Cannot create external load balancer with mix protocols'

This should work perfectly fine with the TCP_UDP target group mode with an NLB but when set in the annotation a 'TCP' only group gets created. 

service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "TCP_UDP"
service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
service.beta.kubernetes.io/aws-load-balancer-internal: "true"
service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

I'll look through the blow and try to work out why https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go

**Comment by usernkey** [comment]
We see same issue on AWS EKS 1.14 +1

**Comment by acgray** [comment]
+1

**Comment by EvgeniGordeev** [comment]
The issue still persists on EKS 1.15.9.

**Comment by sureshkvl** [comment]
I am also struck in this issue. How to overcome this?
My requirement is ,  i want both TCP & UDP in aws network load balancer

For TCP,

service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "TCP" 

it works.

For UDP,
 from the existing comments , no support for mix of TCP &UDP 

can we create a separate ingress controller for  UDP alone ??

service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "UDP"

is it valid?

**Comment by 2rs2ts** [comment]
@sureshkvl k8s doesn't support UDP for load balancers; it's hardcoded in. #87549 is tracking that issue

**Comment by antonu17** [comment]
So confusing.

EKS v1.15
Service exposes 2 ports: HTTP (XXXXX) -> POD's 8080 and HTTPS (YYYYY) -> POD's 8443. I want to have the following ELB listeners configuration:

```
Load Balancer Protocol (port) => Instance Protocol (port)
HTTP (80) => HTTP (XXXXX)
HTTPS (443) => HTTPS (YYYYY)
```

```yaml
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:...
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 8443
    - name: http
      port: 80
      targetPort: 8080
```

This creates:
```
Load Balancer Protocol (port) => Instance Protocol (port)
TCP (80) => TCP (XXXXX)
HTTPS (443) => HTTPS (YYYYY)
```
HTTPS listener is correct, but HTTP is TCP (I need exactly HTTP listener because it has different ELB logs format)

Tried to change `service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http`
Then it creates:
```
Load Balancer Protocol (port) => Instance Protocol (port)
HTTPS (443) => HTTP (YYYYY)
HTTP (80) => HTTP (XXXXX)
```
As we see here, the instance protocol for HTTPS listener is HTTP, which is obviously wrong.

Is it even possible to achieve on v1.15?

**Comment by rubenstolk** [comment]
It would be really helpful if this was intelligent enough to figure out that the listener on port 80 should be HTTP and not HTTPS. Or have an annotation to identify each port differently.

**Comment by omerxx** [comment]
Guys, is this something we should be expecting as a feature or should we resort to duplication of load balancers to serve both HTTP and TCP connections?

**Comment by blaggacao** [comment]
https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20191227-app-protocol.md

**Comment by blaggacao** [comment]
Looks like the foundations are implemented: https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20191227-app-protocol.md

**Comment by thockin** [comment]
I think app-protocol covers this now?  If so, we should close the issue...  @robscott

**Comment by robscott** [comment]
Good call, closing this now. Feel free to reopen if there's some use case that we've missed with AppProtocol.

/close
