### ISSUE TITLE
kubectl get -w should work like watch

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#40262]
kubectl get -w prints new changes from watch events in my terminal.
```
$ kc get po -w
NAME                     READY     STATUS              RESTARTS   AGE
nginx-2738591398-5f9kl   0/1       Terminating         0          1m
nginx-2738591398-xh8hv   0/1       ContainerCreating   0          20s
NAME                     READY     STATUS        RESTARTS   AGE
nginx-2738591398-5f9kl   0/1       Terminating   0          2m
nginx-2738591398-5f9kl   0/1       Terminating   0         2m
```
Unfortunately the output above is not helpful at all. I am not sure if the terminating pod actually terminated. I would love for `-w` to work like the `watch` utility - the screen is refreshed with the new output instead of printing changes.

http://linuxcommand.org/man_pages/watch1.html

@fabianofranz @AdoHe @pwittrock for some reason I can't find any cli-related group to reference

**Comment by AdoHe** [comment]
@pwittrock i just found the `sig-cli-misc` group get deleted.

**Comment by ncdc** [comment]
xref #17612

**Comment by AdoHe** [comment]
on my list, will fix this asap.

**Comment by smarterclayton** [comment]
Hrm... I'm a little weirded out by us reimplementing the general watch behavior.  I agree the tabular form is only slightly useful.  I think watch would be more useful as "wait" though.

**Comment by liggitt** [comment]
if it waited for an update, then printed, you could do `watch kubectl get foo/bar -w`

**Comment by ncdc** [comment]
Should we do something like what I suggested here? https://github.com/kubernetes/kubernetes/issues/17612#issuecomment-161734054
