### ISSUE TITLE
kube-apiserver doesn't prompt for authenticating proxy client cert unless client-ca-file is also specified

### ISSUE THREAD

**Issue by vdavidoff** [kubernetes/kubernetes#40278]
See https://groups.google.com/forum/#!topic/kubernetes-sig-auth/d3WWqNe9uQg for full context, but the gist is that in 1.5.x (I tested with both 1.5.1 and 1.5.2) kube-apiserver does not request a client cert unless --client-ca-file was specified, even if one does not want to enable client cert auth, and only wishes to enable authenticating proxy auth (--requestheader-client-ca-file and --requestheader-username-headers, for example).

I was asked to open this issue by @liggitt. He specifically told me to open it against 1.5.x because this is fixed in master (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubeapiserver/options/authentication.go#L300-L321). I am not sure how to tag this issue with a version; apologies if that makes this messy.

Thanks.

**Comment by liggitt** [comment]
fixed in #40301, released in 1.5.3
