### ISSUE TITLE
Support for GCP Load balancer with SSL termination

### ISSUE THREAD

**Issue by posix4e** [kubernetes/kubernetes#40286]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
ssl GCP loadbalancer
---
FEATURE
  - I want to be able to specify a google ssl certificate and have the load balancer use it

**Kubernetes version** (use `kubectl version`):
latest

**Environment**:
GCP

**Comment by thockin** [comment]
Fixed.  annotation "ingress.gcp.kubernetes.io/pre-shared-cert"
