### ISSUE TITLE
cant access k8s guestbook services

### ISSUE THREAD

**Issue by setyoso** [kubernetes/kubernetes#40287]
Hello there, recently i'm installing K8S in CentOS environment. I'm using VirtualBox from Ubuntu 16.04 in my Notebook's OS. So this is the concept :

- Ubuntu 16.04 LTS in Notebook

- VirtualBox 5.1.12
Master Node & Node
Centos 7. 3.10.0-514-2.2.e17.x86_64

I'm following this guide to install CentOS-K8s. (I'm only using 2 nodes from this guide)
https://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/

then i install kubectl and gitkraken in my ubuntu master, so i can deploy remotely k8s services from my ubuntu.

after that, I try to add guestbook example in my K8s environment following this guide.
https://github.com/kubernetes/kubernetes/tree/master/examples/guestbook

and after I add quick start guestbook command :
`kubectl create -f examples/guestbook/all-in-one/guestbook-all-in-one.yaml`

It's started nicely. I run `kubectl get services` :

```
NAME           CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
frontend       10.254.191.170   <none>        80/TCP     3m
kubernetes     10.254.0.1       <none>        443/TCP    5d
redis-master   10.254.146.6    <none>        6379/TCP   3m
redis-slave    10.254.237.76   <none>        6379/TCP   3m
```
Then I run kubectl proxy from ubuntu :

`kubectl proxy --port=8080 &`

`Starting to serve on 127.0.0.1:8080`

but then, I try to access the services (frontend) via browser, but it can't (no response).

`10.254.191.170:80`

I check `kubectl get pods` it's empty

is there any process or step that i was missing?

Thank's before.

---

Additional Information :

`kubectl get nodes`:

```
NAME              STATUS    AGE
centos-minion-1   Ready     5d
centos-minion-2   Ready     5d
```

K8s Ver:
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"86dc49aa137175378ac7fba7751c3d3e7f18e5fc", GitTreeState:"clean", BuildDate:"2016-12-15T16:57:18Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:

Ubuntu Host : Ubuntu 16.04 LTS

Master Node & Nodes:
Virtual Box 5.1.12
CentOS 7
3.10.0-514-2.2.e17.x86_64

**Comment by spzala** [comment]
@setyoso hi, are you still running in the issue? Once you deploy example yml file the ```kubectl get pods``` shouldn't be empty. The ```guestbook-all-in-one.yaml``` has been lately updated and you may want to look at it again. Also, as you noticed you can't access service externally without using NodePort or LoadBalancer with service - here is a good doc link https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-services/ Thanks!

**Comment by spzala** [comment]
Going to try/test issue closing privilege as this issue should be closed, due to lack of info, per triage guideline. @setyoso please feel free to reopen if needed (if I could close it). Thanks!

**Comment by spzala** [comment]
@kargakis :) Thanks!
