### ISSUE TITLE
NetworkUnavailable - NoRouteCreated - On kubernetes 1.3.4 AWS

### ISSUE THREAD

**Issue by erez-rabih** [kubernetes/kubernetes#40307]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
NoRouteCreated AWS
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.3.4

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- **Kernel** (e.g. `uname -a`): Linux ip-172-20-2-50 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**: I tried to add new nodes to the cluster via setting the AWS Auto Scaling Group desired size. The new nodes consistently come up with NetworkUnavailable. When running `kubectl describe node` I get the following:
```
  NetworkUnavailable 	True 	Mon, 01 Jan 0001 00:00:00 +0000 	Mon, 23 Jan 2017 16:32:44 +0000 	NoRouteCreated 			RouteController failed to create a route
```
All other conditions are fine.

**What you expected to happen**: Nodes should join the cluster and reported as healthy and ready to be scheduled pods on.

**How to reproduce it** (as minimally and precisely as possible): :/

**Anything else do we need to know**: We're running ~45 m4.large nodes.
Our master is 2.xlarge size with no suspicious CPU/memory other system metrics.
We're running on Virginia on 4 different availability zones.
The cluster has been running for a few months and only now we've encountered this error.

**Comment by erez-rabih** [comment]
I found out the reason:  It was a routing table entries cap on AWS VPC that prevented the successful creation of routes for new nodes on the cluster.
I asked AWS to raise the cap and the problem was solved.

**Comment by tuliomonteazul** [comment]
Even though increasing the limit is a solution, the root cause may be that old table entries are not being deleted after a cluster autoscale down.
There is a fix for it that may be released soon: https://github.com/kubernetes/kubernetes/issues/47524
