### ISSUE TITLE
[Federation][kubefed] API server in Waiting state fails to attach volume PVC : Used Kubefed tool with K8s 1.5.1 

### ISSUE THREAD

**Issue by csarora** [kubernetes/kubernetes#40306]
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.0", GitCommit:"58b7c16a52c03e4a849874602be42ee71afdcab1", GitTreeState:"clean", BuildDate:"2016-12-12T23:35:54Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu 16.4
- **Kernel** (e.g. `uname -a`):x86_64
- **Install tools**:Kubefed on running kube cluster created with kubeadm init --cloud-provider=aws

**What happened**:
I am trying to get a federated cluster environment up. Using 
kubefed init my-fed --host-cluster-context=awsc1  --dns-zone-name="spot.co.uk" --dns-provider=aws-route53 --request-timeout='12m'

API-Server is not not coming up error :+1: 32m   34s     24      {controller-manager }           Warning **FailedMount     Failed to attach volume "pvc-c331e1f2-e187-11e6-8943-02a31dd1b43f" on node "ip-10-43-0-31" with: error finding instance ip-10-43-0-31: instance not found**

Error on dashboard :
 [SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "my-fed-apiserver-etcd-claim", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "my-fed-apiserver-etcd-claim", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "my-fed-apiserver-etcd-claim", which is unexpected.]
Failed to attach volume "pvc-c331e1f2-e187-11e6-8943-02a31dd1b43f" on node "ip-10-43-0-31" with: error finding instance ip-10-43-0-31: instance not found
Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "my-fed-apiserver-2017329371-1d6ws"/"federation-system". list of unattached/unmounted volumes=[etcddata]

**How to reproduce it** (as minimally and precisely as possible):
Use kubefed on AWS , PVC does not mount to instances

**Comment by nikhiljindal** [comment]
cc @kubernetes/sig-federation-bugs @madhusudancs @irfanurrehman

**Comment by madhusudancs** [comment]
cc @kubernetes/sig-storage-bugs 

@csarora could you please list the nodes - `kubectl get nodes -o yaml`? Also, could you please describe the API server pod, the PVC and the PV?

```shell
$ kubectl describe pod my-fed-apiserver
$ kubectl describe pvc my-fed-apiserver-etcd-claim
$ kubectl describe pv pvc-c331e1f2-e187-11e6-8943-02a31dd1b43f
```

**Comment by csarora** [comment]
@madhusudancs I updated client version to 1.5.2 and redeployed but still same error 
**Error** 
[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "my-fed-apiserver-etcd-claim", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "my-fed-apiserver-etcd-claim", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "my-fed-apiserver-etcd-claim", which is unexpected.]
Failed to attach volume "pvc-91e05dfb-e2fd-11e6-a36b-02bdfd55dff3" on node "ip-10-43-0-30" with: error finding instance ip-10-43-0-30: instance not found

**attaching the files describing nodes/pv etc**

[nodes-fifo.txt](https://github.com/kubernetes/kubernetes/files/729727/nodes-fifo.txt)
[API-server.txt](https://github.com/kubernetes/kubernetes/files/729728/API-server.txt)
[PVC.txt](https://github.com/kubernetes/kubernetes/files/729729/PVC.txt)

root@ip-10-43-0-20:~#  **kubectl describe pvc my-fed-apiserver-etcd-claim --namespace=federation-system**
Name:           my-fed-apiserver-etcd-claim
Namespace:      federation-system
StorageClass:   yes
Status:         Bound
Volume:         pvc-91e05dfb-e2fd-11e6-a36b-02bdfd55dff3
Labels:         app=federated-cluster
Capacity:       10Gi
Access Modes:   RWO
No events.

root@ip-10-43-0-20:~# **kubectl describe pv pvc-91e05dfb-e2fd-11e6-a36b-02bdfd55dff3 --namespace=federation-system**
Name:           pvc-91e05dfb-e2fd-11e6-a36b-02bdfd55dff3
Labels:         failure-domain.beta.kubernetes.io/region=eu-west-1
                failure-domain.beta.kubernetes.io/zone=eu-west-1b
StorageClass:
Status:         Bound
Claim:          federation-system/my-fed-apiserver-etcd-claim
Reclaim Policy: Delete
Access Modes:   RWO
Capacity:       10Gi
Message:
Source:
    Type:       AWSElasticBlockStore (a Persistent Disk resource in AWS)
    VolumeID:   aws://eu-west-1b/vol-0a2019e364e42931e
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
No events.

**Comment by saad-ali** [comment]
@justinsb @chrislovecnm Have you guys had a chance to play with federated clusters in AWS? Looks like attach volume is failing to find the node to attach volume to.

@csarora Can you clarify: was your PV manually created or via Dynamic Provisioning?

CC @jingxu97 @jsafrane

**Comment by madhusudancs** [comment]
@saad-ali @csarora is using kubefed which dynamically provisions the PV. The code is here - https://github.com/kubernetes/kubernetes/blob/master/federation/pkg/kubefed/init/init.go#L399

**Comment by saad-ali** [comment]
Can you verify that the master on which the attach operation is triggered is in the same cluster as the node "ip-10-43-0-31"?

**Comment by csarora** [comment]
@saad-ali @madhusudancs
Yes its dynamic provision PV using kubefed , 
Master is running on private IP : 10.43.0.20 
Minions on 10.43.0.30 & 10.43.0.31

**Comment by csarora** [comment]
any update or workaround to get around this volume issue?

**Comment by madhusudancs** [comment]
@saad-ali is there some other log that @csarora can look into to debug this?

**Comment by saad-ali** [comment]
The `controller-manager` log would be the most interesting one.

Given this error:

```
Failed to attach volume "pvc-91e05dfb-e2fd-11e6-a36b-02bdfd55dff3" on node "ip-10-43-0-30" with: error finding instance ip-10-43-0-30: instance not found
```

And @csarora's statement that the master running the attach/detach controller (10.43.0.20) should be able to see and attach to volumes to that node (10.43.0.30):

```
Yes its dynamic provision PV using kubefed ,
Master is running on private IP : 10.43.0.20
Minions on 10.43.0.30 & 10.43.0.31
```

I think we need someone from sig-aws to help investigate why the attach call would fail like this. @justinsb @jingxu97 @chrislovecnm can any of you help?

**Comment by justinsb** [comment]
This happens if your cluster is not set up correctly.

Please note that kubeadm does not support cloudproviders - I highly recommend using kops instead :-)

**Comment by csarora** [comment]
@justinsb I used kubeadm with cloud provider aws flag & the deployment went fine. all the pods/services in default namespace are running fine with kubeadm , its only federation apiserver thats not coming up. 

One thing i tried using `federation-up` and `deploy.sh` instead of kubefed tool. but that does not work well if cluster is created using kubeadm. 

@madhusudancs Can someone please confirm if federation works for AWS , as i got an error & read some where that supported cloud provider GCE/GKE only? I want to try federation for hybrid cloud like one cluster on AWS and another cluster on-premise.

**Comment by madhusudancs** [comment]
> @madhusudancs Can someone please confirm if federation works for AWS ,

It does work on AWS.

> as i got an error & read some where that supported cloud provider GCE/GKE only?

There are multiple deployment mechanisms and this was the case with one of them. Particularly, deploy.sh scripts described here - https://kubernetes.io/docs/admin/federation/#running-the-federation-control-plane. Even in that case there was a workaround.

> I want to try federation for hybrid cloud like one cluster on AWS and another cluster on-premise.

**Comment by madhusudancs** [comment]
> @justinsb I used kubeadm with cloud provider aws flag & the deployment went fine. all the pods/services in default namespace are running fine with kubeadm , its only federation apiserver thats not coming up.

It might also be worth checking if dynamic provisioning works as expected on your cluster outside the kubefed tool. 

Based on @saad-ali's comment in https://github.com/kubernetes/kubernetes/issues/40306#issuecomment-276231584, it might also be useful to look at your cluster's controller manager logs and share what you find here.

**Comment by justinsb** [comment]
I believe this issue should be moved to the kubeadm repository.

**Comment by csarora** [comment]
@saad-ali  I checked controller manager logs it has a lot of errors , unable to list namespace/cluster/etc etc timeout. Attaching log 
[controller-manager.txt](https://github.com/kubernetes/kubernetes/files/744672/controller-manager.txt)

**Comment by quinton-hoole** [comment]
Closing old bug reports.  Please re-open if you're still seeing this issue.
