### ISSUE TITLE
kubectl apply: managing explicit null values in LastAppliedConfigAnnotation

### ISSUE THREAD

**Issue by andronat** [kubernetes/kubernetes#40305]
Based on @pwittrock comment [here](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35496#-KaimE_T47FL3t8nfsaH), and after PR: #35496.

Saving user defined nulls in LastAppliedConfigAnnotation annotation.

Imagine the case once we support kubectl apply diff

Set field to null
Run apply diff - see changes required
Run apply - make changes
Run apply diff - see changes required - looks like nothing was updated with apply

Want:
Set field to null
Run apply diff - see changes required
Run apply - make changes
Run apply diff - see no changes required

**Comment by spzala** [comment]
@andronat Hi, since it's been long the issue was discussed last and I found a related discussion/fix here https://github.com/kubernetes/kubernetes/pull/40630 - just wondering if that has addressed this issue and we can close this? Thanks!

**Comment by andronat** [comment]
Hello @spzala, yes #40630 solves this. I’m closing it.

**Comment by spzala** [comment]
@andronat  thanks!!
