### ISSUE TITLE
node-pool upgrade reverts reserved ip to ephemeral

### ISSUE THREAD

**Issue by theothermike** [kubernetes/kubernetes#40314]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`): 1.4.7 -> 1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: Google
- **OS** (e.g. from /etc/os-release): Container Engine
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:  After executing an upgrade from 1.4.7 to 1.5.2, all our nodes in the 'default-node' pool lost their static assigned IPs and reverted to ephemeral.  

**What you expected to happen**: For the nodes to retain their reserved IP when the upgrade is complete

**How to reproduce it** (as minimally and precisely as possible): Assign a reserved IP to a node in a node-pool, then execute an upgrade, and watch them revert to ephemeral

**Anything else do we need to know**:

**Comment by spiffxp** [comment]
Is this still an issue with kubernetes today? We're up to 1.10.x now, I don't anticipate upstream support beyond 1.8.x

**Comment by neolit123** [comment]
> Is this still an issue with kubernetes today? We're up to 1.10.x now, I don't anticipate upstream support beyond 1.8.x

indeed, 1.5.x is way outside of the support skew.
@theothermike have you upgraded to a more recent k8s version like 1.10.x or 1.11.x?
closing this issue, so please free to re-open if you have the same problem with more recent versions. :+1: 

/close
