### ISSUE TITLE
Should we move away from verify-flags.txt?

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#40329]
The original commit for `hack/verify-flags/known-flags.txt` claims that the purpose is for preventing flags that have `_` in the flag name. It claims that this list is used to speed up the search so that it is not obtrusive as a pre-commit hook. 

Does anyone actually use the pre-commit hooks anymore? When I joined the project, these already took so long that I almost immediately turned them off.

Can we move flag verification off of relying on known-flags.txt and no longer have to edit that file every time we add/remove a flag?

@kubernetes/test-infra-reviewers what do y'all think of this?

**Comment by smarterclayton** [comment]
This is pretty much irrelevant now.  Recommend we nuke it.
