### ISSUE TITLE
azure: loadbalancers are broken in 1.5.2

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#40332]
**Kubernetes version** (use `kubectl version`): `v1.5.2`

**Environment**:
- **Cloud provider or hardware configuration**: Azure / Azure Container Service
- **OS** (e.g. from /etc/os-release): Xenial
- **Kernel** (e.g. `uname -a`): latest lts
- **Install tools**: kubelet + static manifests
- **Others**: n/a

**What happened**:
I created a Service (type=LoadBalancer). The load balancer did not complete provisioning and security group was not updated, so the LB that is there doesn't work.

**What you expected to happen**:
Azure load balancer is created, external IP field is populated (doesn't show as "Pending")

**How to reproduce it** (as minimally and precisely as possible):
Try it.

**Anything else do we need to know**:
No.

There is an issue opened against the repo that caused this problem: https://github.com/Azure/go-autorest/issues/112

This was reported here: https://github.com/Azure/acs-engine/issues/194#issuecomment-274472969

CC: @codablock @brendandburns

**Comment by codablock** [comment]
@colemickens Should we do a fix that simply sets the 2 properties to nil before a real fixes comes into go-autorest?

**Comment by colemickens** [comment]
@codablock I'd prefer to fix it properly in `go-autorest` but as of yet, it's unclear what the timeframe is. Let me ask for a timeline.

**Comment by codablock** [comment]
I agree that a proper fix in go-autorest would be preferable. But as long as it's not fixed, LBs are broken on k8s>=1.5.2. That's why I would like to do a workaround until the real fix comes in.

**Comment by homotopycolimit** [comment]
Is there a workaround? Is there a way I can manually intervene to make the LoadBalancer work?

**Comment by colemickens** [comment]
No. Not currently, other than building your own copy of `kubernetes` with @codablock's patch applied. I'm testing a more proper fix today or tomorrow - hope to have it in for 1.5.3.
