### ISSUE TITLE
Published k8s service is not available

### ISSUE THREAD

**Issue by PavelPrischepa** [kubernetes/kubernetes#40349]
**BUG REPORT**:

**Kubernetes version**: 1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS**: Debian 8
- **Kernel**: Linux ip-172-31-20-110 3.16.0-4-amd64 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux
- **Docker**: 1.13

**What happened**:
I have single node cluster on AWS. I created k8s service with a published port 31250 and replication controller. But the service doesn't available out of the host machine.

**What you expected to happen**:

The service should be available via 31250 port.

**How to reproduce it**:

Download and install schema.

```
wget https://gist.githubusercontent.com/PavelPrischepa/8638f678c7fe8ed643ec99983bfb7de7/raw/1190981f2395cd142f5874693648a40aafcfe9bc/schema.yml schema.yml
kubectl create -f schema.yml
```

Try to access new service:
`curl https://<Node IP>:31250`

The result should be `HTTP 200 Ok`.

Some debug info from the k8s node:

```
# iptables -L -n -t nat | grep 31250
KUBE-MARK-MASQ  tcp  --  0.0.0.0/0            0.0.0.0/0            /* default/web: */ tcp dpt:31250
KUBE-SVC-BIJGBSD4RZCCZX5R  tcp  --  0.0.0.0/0            0.0.0.0/0            /* default/web: */ tcp dpt:31250
```

```
# netstat -plunt | grep 31250
tcp6       0      0 :::31250                :::*                    LISTEN      534/hyperkube
```

```
# nmap -p 31250 <k8s node public IP>
PORT      STATE    SERVICE
31250/tcp filtered unknown

**Comment by thriqon** [comment]
Having the same problem, seems to be caused by a firewall policy setting of the `FORWARD` chain to `DROP`. Our work-around was to immediately downgrade to 1.12.6 instead.

This seems to be caused by https://github.com/docker/docker/pull/28257 (and to be fair, it is actually documented in the release notes).

**Comment by cmluciano** [comment]
similar to https://github.com/kubernetes/kubernetes/issues/40182

**Comment by bboreham** [comment]
Also related: #39823
