### ISSUE TITLE
Hollow-NPD doesn't work in kubemark when running locally

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#40350]
I was trying to run kubemark on my local cluster. And hollow-NPD completely didn't work:
- it was breaking nodes from the base cluster by making them unready
- it was preventing hollow kubelet and hollow proxy from running

I don't know what is the difference between Jenkins and my local but we should fix it.

**Comment by wojtek-t** [comment]
It seems to be "container-VM"-related. It seems to work on GCI.

We need to verify that the last update of container-VM image didn't break anything.
@kubernetes/sig-node-bugs

**Comment by Random-Liu** [comment]
> it was breaking nodes from the base cluster by making them unready.

IIUC, "base cluster" here means "non-kubemark cluster" or "real cluster", right? If so, how come NPD break the base cluster? NPD doesn't really update the `NodeReady` condition.

**Comment by wojtek-t** [comment]
It seems that it wasn't really NPD, but something bad was happening to kubemark. And my current feeling is that it is the container-VM related issue.

**Comment by shyamjvs** [comment]
Closing this issue since NPD works in kubemark now. For any issues that still come up in kubemark npd, we have issue https://github.com/kubernetes/kubernetes/issues/39245 for tracking.
