### ISSUE TITLE
Clarify error messages when sub-components fail.

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#4036]
Right now, when etcd fails, we just pass that straight up to the client.  We should probably annotate the error so that we understand that it comes from etcd, not from the apiserver.

**Comment by smarterclayton** [comment]
This was fixed in 1.4ish timeframe.

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (176/150 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:36327 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dGTOZ-000WYJ-0R
	for dev@imwiz.com; Thu, 01 Jun 2017 10:56:23 -0600
Date: Thu, 01 Jun 2017 09:56:12 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1496336172;
	bh=AekP46Z+TwZxMvr+UaaFB0VFzfCiG++N8YHt4hDYoxs=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=NosdlD82waAsBZAs3dfk+zXbeTkcfqiCZSL1q4Vj/Svj1syCST7PeoLCLnJ9R6Mvx
	 5GpzgylsloQP2fCWe8qVIjX4xOnEoELI+T/moU8m43br05KAEWrZ8IM3saYUNUd32I
	 of+iiz3QQQsJKr34NVHQokqLU5IFlZu3StG2wO3E=
