### ISSUE TITLE
Approval for splitting apimachinery, apiserver, client-go repos

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#40363]
We're in the process of creating smaller repos for people to vendor in order to create their own API types, their own API servers, and eliminated duplicate packages from client-go.  This results in broad mechanical pulls which will always want approval from top level owners.

@lavalamp @smarterclayton Will you grant approval in advance for pulls making this split to avoid reviewing each one individually?  Looks like maintainers can add the tag, so we ought not have to bug you if you do.

@caesarxuchao @sttts fyi

**Comment by smarterclayton** [comment]
I approve PRs that move packages into pkg/apimachinery under the existing patterns we have established.  Normal review is sufficient for individual merges.

**Comment by smarterclayton** [comment]
Closing, has accomplished purpose.
