### ISSUE TITLE
Heat-OpenStack provider never completes stack creation, times out 

### ISSUE THREAD

**Issue by sc68cal** [kubernetes/kubernetes#40367]
**Kubernetes version** (use `kubectl version`): 
```
(kubernetes)scollins@Sean-Collins-MBPr15 ~/src/k8s/kubernetes ±swift_upload_cache⚡ » kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6+ae4550c", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"not a git tree", BuildDate:"2016-08-30T15:45:50Z", GoVersion:"go1.7", Compiler:"gc", Platform:"darwin/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: OpenStack

**What happened**:

Stack creation times out after 60 minutes

https://gist.github.com/sc68cal/cfdf20664c348156e67ba0969b17172f

Cherry-picking 40e4e0e did not appear to change the outcome

**What you expected to happen**:

Stack creation completes 

**How to reproduce it** (as minimally and precisely as possible):

Follow documentation on https://kubernetes.io/docs/getting-started-guides/openstack-heat/

**Anything else do we need to know**:

**Comment by micmro** [comment]
There seem to be some issue in the setup on the master instance. Can you check the logs on this instance for error (or upload them here for triaging).

One issue with this symptoms I had seen was, that the master can't access the setup files (`kubernetes-server.tar.gz` and `kubernetes-salt.tar.gz`) on swift.

**Comment by sc68cal** [comment]
What logfiles are relevant on the master? Can you provide paths? Thanks.

**Comment by micmro** [comment]
I'd usually check `journalctl -a` and go through all logs from the beginning to see if there is anything suspicious, though this might be quite a few depending on when it stopped. 
To just see only the last e.g. 50 lines with `journalctl -a --lines=50` or only from e.g. the salt-minion service `journalctl -a -u=salt-minion`.

I hope this helps.

**Comment by sc68cal** [comment]
Thanks. I'll re-run the heat-openstack provider and report back

**Comment by xsgordon** [comment]
@idvoretskyi can you label this sig/openstack please?

**Comment by jamiehannaford** [comment]
@sc68cal Did you manage to find any logs for this?

**Comment by sc68cal** [comment]
No, and I've had a job change recently. I will attempt to reproduce in my spare time once I get settled in. Sorry for the delay

**Comment by spzala** [comment]
@sc68cal hi, since it's been many months of this issue was last discussed, if you are okay, can we close it considering lack of information per k8s triage guidelines? Per discussion so far it could be an issue or just one time error or some configuration need. If any active users hits it again I am sure they will open another issue. Thanks!

**Comment by jamiehannaford** [comment]
👍 for closing.

/cc @dims

**Comment by sc68cal** [comment]
>  or just one time error or some configuration need

It was not a one time error. I ran it multiple times, tried multiple different configurations over a period of two weeks before I gave up on it. 

So, feel free to close the issue, however I wonder how well this way of deploying kubernetes is really supported.

**Comment by xsgordon** [comment]
@sc68cal indeed. We have added a note.to the v1.8 release notes deprecating it in preparation for potential removal (https://github.com/kubernetes/features/pull/481). I have had reports that users have run it successfully on v1.7 though.

**Comment by spzala** [comment]
@sc68cal thanks for the quick reply! and @xsgordon thanks much Steve for sharing the deprecation PR and success with the latest version. I believe it's safe to close the issue now. @dims please close it if you think so too. Thanks!!

**Comment by dims** [comment]
/assign

Thanks @spzala @xsgordon @sc68cal
