### ISSUE TITLE
verify-bazel script doesn't play nicely with code to be built for Windows alone

### ISSUE THREAD

**Issue by pires** [kubernetes/kubernetes#40361]
Issue seen in #39373, https://github.com/kubernetes/kubernetes/pull/39373/commits/b55d402185e8bdb93294a1f3ce66c9bba12bbced.

/cc @mikedanese

**Comment by mikedanese** [comment]
What happened? I can't tell from the issue.

**Comment by pires** [comment]
Never mind, the author added the file by hand 😞.
