### ISSUE TITLE
AWS EBS PV storage edge case

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#40375]
We have noticed an issue where you:

1. Create a pod with a 5 GB PV
1. Create an EBS volume in aws - 20 GB
1. Create a PV and PVC in a deployment that lists the AWS id for the EBS volume, the claim is for a 5GB volume - pod b
1.  The docker volume was incorrectly mounted to another 5GB volume on the node, and was not mounted to the aws ebs volume.  The incorrect volume was already mounted to another
1. pod b was mounted to pod a volume
1. pod b was not mounted to the 20GB ebs volume

Version K8s 1.4.7

**Comment by jingxu97** [comment]
@chrislovecnm I am not quite following the steps. Do you still hit this issue?

**Comment by baldwinSPC** [comment]
@chrislovecnm could this be related to #31891 ?

**Comment by chrislovecnm** [comment]
I am closing this out, as I have not seen it lately.
