### ISSUE TITLE
kubectl cli can't create service with arbitrary selector (ex: w/ daemonset)

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#40406]
**Kubernetes version** (use `kubectl version`): v1.5.2

**What happened**:
I wanted to `kubectl expose --name=nginx-ingress --selector 'name=nginx-ingress-lb' ...` but you must specify a type to target, and I couldn't figure out how to target a daemonset or a bunch of pods with an arbitrary selector.

In lieu of that, `kubectl create service clusterip --selector` but `--selector` doesn't exist for `create service`.

**What you expected to happen**:
One of them to be available.

**Comment by calebamiles** [comment]
would someone from @kubernetes/sig-cli-misc help with routing this issue. @deads2k, @lavalamp I couldn't seem to find a GitHub team for API Machinery, could you also help with routing? Thanks!

**Comment by deads2k** [comment]
> In lieu of that, kubectl create service clusterip --selector but --selector doesn't exist for create service.

`kubectl create service` is strictly intended as the simplest possible starting point.  `kubectl set selector` can be used to set a selector for a service and you can pipe from one command to the other if you wish.  You could also issue a patch or run `kubectl edit` for an interactive flow.

@calebamiles in this case, probably @kubernetes/sig-cli-misc

**Comment by colemickens** [comment]
Great, thanks @deads2k. I simply didn't know that `kubectl set selector` even existed. Maybe this is more of a docs bug than anything. Please feel free to close this out, unless you or sig-cli-misc think there's value in leaving this open for a single-command solution.

**Comment by deads2k** [comment]
> Great, thanks @deads2k. I simply didn't know that kubectl set selector even existed. Maybe this is more of a docs bug than anything. Please feel free to close this out, unless you or sig-cli-misc think there's value in leaving this open for a single-command solution.

I think there's value in the commands as they are now. Having a separate `kubectl set selector` command is good for everyone and having very simple `kubectl create` commands makes getting skeleton objects really easy.  Fewer parameters makes starting points less scary and once you have yaml, you're just a `kubectl edit` or patch away from what you want.

**Comment by pwittrock** [comment]
@colemickens FYI, I have a doc out for review that covers this:

https://deploy-preview-2317--kubernetes-io-vnext-staging.netlify.com/docs/concepts/tools/kubectl/object-management-using-commands/#using-set-commands-to-modify-objects-before-creation

https://github.com/kubernetes/kubernetes.github.io/pull/2317

**Comment by aftlabs** [comment]
It can be done here is the example from: [https://deploy-preview-2317--kubernetes-io-vnext-staging.netlify.com/docs/concepts/tools/kubectl/object-management-using-commands/#using-set-commands-to-modify-objects-before-creation](url)

clusterip <myservicename> -o yaml --dry-run | kubectl set selector --local -f - 'environment=qa' -o yaml | kubectl create -f -
