### ISSUE TITLE
Napkin design: bulk-namespace access control and/or RBAC

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#40403]
Note: mostly a brain dump

As we look at some of the requirements we have around RBAC at scale in Kube, three in particular come up often:

1. organizational multi-tenancy - where a large fraction of the cluster is a single organization entity that desires subtenant access (large swathes of namespaces, possibly identified by labels)
2. sparse multi-tenancy - where a user has access to a few scopes (RBAC access to namespaces)
3. scoped integrations - where an integration has access to a percentage of namespaces, resources, or resources within namespaces, such as an ingress controller that is only allowed to see ingresses and secrets that a user has decided to expose to the end user

Our current RBAC scopes are cluster (non-namespaced), namespace, and name.  The RBAC rules for those scopes map directly to the access pattern (`GET /v1/pods` -> `has GET on pods at cluster`).

OpenShift identified early on that we would need to support a sparse multi-tenant model, so we introduced a separate resource (`projects`) which is a virtual resource on top of namespace.  Listing a project queries to an index maintained by a reflector on namespace + roles + rolebindings.  We support a limited form of watch over that index, although it has some gaps.  A user can perform a cluster-scoped `GET /v1/projects` call and see only the namespaces they have the `view` permission on (we do not offer sparse cluster queries on other permission bits).

In order to satisfy the 3 use cases above, we've been considering a few incremental stepping stones:

1. Support label selectors on RBAC roles to offer subset access:
    - grouping namespaces by label selector by organization: `GROUP o=financial CAN GET /namespaces WHERE owner.organization=financial`
    - exposing a limited subset of secrets to an integration for a particular use case: `SERVICEACCOUNT ingress-controller-internal CAN GET /secrets WHERE ingress.controller/consume=internal`
2. Investigate indices and optimizations for converting the RBAC state into bounding set filters on LIST and WATCH
    - the primary challenge is supporting snapshot access - LIST without consistent WATCH is useless
    - today, WATCH does not terminate when ACL is revoked (which we would like to fix)
      - in practice, access to RBAC changes slowly (< 1/hr per user, with lots of bustiness)
      - if we can make LIST + WATCH correct, then we can simply terminate watches when their bounding set changes
      - delta informers already handle bounding set changes on resync
      - we are allowed a grace period to react to RBAC for other reasons, so it's reasonable to coalesce role changes over small (5s-5m) windows
    - sparse bit indices are very reasonable for the likely distribution of RBAC roles (10k namespaces, 10k users, ~500 large organizations, watches proportional to organizations, small number of practical permissions to check) - many of the approaches in the literature are trivial to apply to sets this small
3. Investigate continued optimizations for filtered LISTs in storage and etcd
    - at some point we will switch from eager decoding of stored objects to a lazy model that defers full object decoding (potentially all the way back to clients when versions and encodings are aligned), which leaves room for selective schema decoding (accessing only labels, or decoding only objects that match a name and namespace filter)
      - now that we have unified the underlying common api group, we can do selective decoding of parts of object meta for both JSON and proto (proto by querying the model for the right tags to get at labels), JSON by using something like https://github.com/tidwall/gjson)
    - etcd3 allows us to do MVCC reads on uncompacted history that *should* make it possible to make multiple list calls in sequence for disconnected spans
    - we've discussed materializing label indices into etcd (although this only helps part of the use case)
    - etcd3 does not have (as far as I can see) a way to retrieve multiple ranges in one request - that potentially would help optimize high selectivity cross namespace calls (get all pods in namespaces a1, a2, a5, b16, c30)

Subdividing secret access is becoming increasingly important - we currently can't enable ingress on multi-tenant clusters without significant concerns about escalation.  The more integrations the cluster has, the more the coarse "resource specific" model for ACL runs into limitations.

**Comment by smarterclayton** [comment]
@xiang90 has anyone discussed / requested the ability to perform multiple range retrievals in one request in etcd3?  While we can dispatch multiple requests for low N fetches (get namespace a1, then get b2), being able to say `get range( [/a1/, /a1/\x00), [/b2/, /b2/\x00), ... )` in a single call would make some of the scenarios described above more feasible for higher N.

**Comment by xiang90** [comment]
@smarterclayton If my understanding is correct, it is already possible today in etcd3. You can have N range requests in one Txn to fetch N ranges.

**Comment by xiang90** [comment]
@smarterclayton We need to rework the api/storage API to enable txn though. Then we can unlock more powerful features. /cc @timothysc @hongchaodeng

**Comment by smarterclayton** [comment]
@xiang90 thanks, I misinterpreted the docs on TxnRequest (I was focused on Compare, not RequestOp, which allows Range).  Would the impacts of:

```
TxnRequest {
  500 RangeRequest for 0..50keys
}
```

scale well with N range requests?  Or do you foresee other limitations?

As far as storage api, I think we'd need to carefully understand how the interplay between authz and API would work.  I would prefer a model where the authz layer builds a filter query that can be efficiently implemented (as a first step), such as a field selector for namespace IN X.

**Comment by cjcullen** [comment]
The "scoped integration" piece makes me think of discussions we've had about limiting per-Kubelet access to API objects to only what that Kubelet _needs_. This might not be as easy as a label-selector RBAC rule, but we should open up that discussion as well.

**Comment by timothysc** [comment]
> As far as storage api, I think we'd need to carefully understand how the interplay between authz and API would work. I would prefer a model where the authz layer builds a filter query that can be efficiently implemented (as a first step), such as a field selector for namespace IN X.

So long as the abstraction for filtering is external to the client constructs.  I have to admit I'm left feeling uneasy at the thought of constructing multi-op filters on the fly and ensuring traceability, which tbh were not to good at today.  We're going to need a audit trail.

**Comment by MikeSpreitzer** [comment]
@smarterclayton I need some more clues to understand the "project" concept you mentioned in the opening remark here.  What do you mean by "perform a cluster-scoped `GET /v1/projects` call and see only the namespaces ..."?  Do you mean that GET returns the right namespaces?  That would be an odd thing for a GET of /v1/projects to return.  Or you do mean the get returns things (what things?) found in the right namespaces?  How does this connect to the problem I want to solve, which is to control what happens in API calls to get/list/watch/etc normal things (pods, services, etc --- not projects)?  How does this connect to what is returned from a DNS lookup?

I looked at the README.md of https://github.com/openshift/kube-projects but do not understand it.  I did not see any parameters to the project creation, nor a way to specify any visibility rules for a project.  I do not see examples of how to use a project.  I do not understand the remark "TODO requires https://github.com/openshift/origin/pull/11340".  Do I need OpenShift in order to follow the recipe there, or will plain Kubernetes do?

**Comment by MikeSpreitzer** [comment]
@smarterclayton I suppose that in the enumeration of 3 items in the opening remark here, you meant to end item 3 with a reference to the ingress controller rather than the end user.

I suppose that in the second enumeration of 3 issues, issue 2 was meant to refer to burstiness rather than bustiness.

**Comment by davidopp** [comment]
> Subdividing secret access is becoming increasingly important - we currently can't enable ingress on multi-tenant clusters without significant concerns about escalation.

Can you explain the escalation vulnerability? I assume that a Secret in the "tls" field of the Ingress spec has to be in the same namespace as the Ingress object (since there's no separate namespace specifier). So I don't see how it would be possible for me to have my Ingress read Secrets in someone else's namespace. I guess the vulnerability must be something else.

**Comment by smarterclayton** [comment]
You have to give the ingress controller the ability to read secrets.  Which gives it the ability to do anything in the namespace you granted (and most people just grant blanket secrets).  There's no way for an etcd operator to utilize secrets without also being given effective root access.

**Comment by davidopp** [comment]
Two questions about what you just wrote:

1) If there's one Ingress controller per cluster, I guess it must use a service account that can read all secrets in the cluster. But above you said "You have to give the ingress controller the ability to read secrets. Which gives it the ability to do anything in the namespace you granted (and most people just grant blanket secrets)." Can you clarify? How is it granted permission for just one namespace?

2) If there is one Ingress per namespace, and the Ingress uses the namespace's service account, then I can see that it would only have access to one namespace's secrets. You wrote "Which gives it the ability to do anything in the namespace you granted (and most people just grant blanket secrets)" But can't you configure it to use a different service account, that only has permission to read secrets? (Or are you saying yes you can do that, but in practice people don't -- which would seem like more of a usability issue than a lack of functionality.)

**Comment by smarterclayton** [comment]
> Which gives it the ability to do anything in the namespace you granted (and most people just grant blanket secrets).

If the user grants access to any secret, it can do anything that any service account can do (because service account secrets let you act as the user).  

Anyone wanting to run an ingress controller across multiple namespaces would have to manually grant the ingress controller permission to see its secrets (or just one secret) which would be painful.

For an operator, any operator that creates secrets probably needs to read them - since reading reveals the secret, an operator that wants to create and reference secrets usually asks for "get all secrets".  Of course, if the operator can create pods, then the operator can simply run a pod that references the secret and exfiltrates the data.

**Comment by davidopp** [comment]
@smarterclayton Has there been any more thinking or work on the stuff described in your first message in this issue? 

BTW just for clarification, IIUC the feature requests here (that aren't just performance optimizations) are 

(1) add label selectors to Role and ClusterRole, so that instead of only being able to select a single object (by specifying its name) or all objects, you can specify all objects matching the selector. This allows you to add objects to the set permitted by an RBAC rule without adding or updating RBAC rules -- you just create an object with (or update an object to have) the proper label. Because that label gives someone/something permission to do stuff, there's no security risk if we simply anyone to set that label on the objects they create -- they can only make themselves less secure, not make someone else less secure.

(2) fix "WATCH does not terminate when ACL is revoked"

(3) native/well-integrated support for be able to do LIST/WATCH on "all objects that I have permission for" (of a particular kind, in a particular namespace, etc. things you can already do today)

Is that right?

**Comment by smarterclayton** [comment]
Probably (4) allow users to bulk retrieve items by namespace instead of
making multiple namespace calls.

On Sat, Aug 19, 2017 at 7:08 PM, David Oppenheimer <notifications@github.com

**Comment by MikeSpreitzer** [comment]
This is still very relevant.

Let me add one more bit of functionality, or clarify item (3) (depending on how you view it).  Effective permissions come not only from ABAC and RBAC, but authorization plugins, in-process admission plugins, and admission webhooks.  Consider the case of a kubelet that needs an informer on Pod objects that are placed on the kubelet's Node but not the rest.  Today that could be expressed with a field selector (IDK whether it actually is).  It would be great if RBAC or another authorization mode could distinguish based on the field and label selectors in an operation.  Perhaps also the page size and/or other query parameters.

**Comment by MikeSpreitzer** [comment]
https://github.com/kubernetes/kubernetes/issues/58262#issuecomment-357567574 contains the remark

> Any ACL filtered list operation breaks standard watch semantics

but I do not follow the logic.  Presumably someone who wants filtering in list will want the same filtering in watch; a matched pair of list and watch make a functional informer.  What am I missing?

**Comment by liggitt** [comment]
The ACLs controlling which items are in the returned set are not represented in the resourceVersion, so the handoff between list and watch (or between one watch connection and the next) can become inconsistent if those ACLs change.

**Comment by MikeSpreitzer** [comment]
So I see two approaches to this filtering.  One, which the other posters here seem to assume, is that the filtering is implicitly imposed on each request.  That's nice and convenient, but maybe a little too magic.  The other approach has the client express the filtering while the authorization and admission control approve it.  This has the advantage that there is no invisible modulation of the request semantics.

**Comment by enj** [comment]
> has the client express the filtering

How would the client express that?  For example, how would a client ask for "show me my namespaces."

**Comment by MikeSpreitzer** [comment]
@enj : how are you supposing "my namespaces" is represented?  The earlier discussion suggested labels on the namespace.  So that could be expressed already with a request to get namespace objects restricted by a label selector.

**Comment by enj** [comment]
> @enj : how are you supposing "my namespaces" is represented?

Any namespace I can get via the API directly.  If running `kubectl get ns foo` and `kubectl get ns bar` would give me the namespace data for `foo` and `bar` (with no authorization error), then `kubectl get mynamespaces` would return `foo` and `bar` (`mynamespaces` being some virtual resource).

**Comment by MikeSpreitzer** [comment]
@enj: My question was, how does the system represent which namespaces belong to who?  The earlier discussion suggested it was by a label on the namespace object.  For example, we might imagine a label such as `owner=customer1`.  If that is the technique used, then the filtering can be expressed by the client: `kubectl get namespace -l owner=customer1`.  If kube's authorization framework exposed that label selector, then we could authorize that customer to get that filtered list.

**Comment by enj** [comment]
> My question was, how does the system represent which namespaces belong to who?

A namespace can belong to more than one entity.  Any entity that can `get` the namespace via the API owns it.  The representation is within the authorization policy.

Something like `kubectl get namespace --filter=(if get namespace $name)`.

> The earlier discussion suggested it was by a label on the namespace object.

How would that handle multiple owners?

**Comment by MikeSpreitzer** [comment]
Yes, I understand that in general a given kube API object is accessible by mutliple users (with arbitrary relationships among those users).  I was thinking of multi-tenancy designs in which each tenant owns one or more namespaces --- each such namespace belongs to just one owner.

**Comment by enj** [comment]
> I was thinking of multi-tenancy designs in which each tenant owns one or more namespaces --- each such namespace belongs to just one owner.

A label based approach seems reasonable in this architecture.

> IIRC, OpenShift is like this.

OpenShift's project resource follows the RBAC semantics I described earlier.  It does not perform any operations based on labels.

**Comment by liggitt** [comment]
Thanks for the feature request, but this is unlikely to make progress as an issue. A proposal that works through the design along with the implications of such a change can be opened as a [KEP](https://github.com/kubernetes/enhancements/tree/master/keps#kubernetes-enhancement-proposals-keps).

/close
