### ISSUE TITLE
service accounts: first referenced secret is not always the one mounted

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#40411]
Was experimenting with service account credential rotation and seem to have stumbled on a bug.

**Kubernetes version** (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"4957b090e9a4f6a68b4a40375408fdc74a212260", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

Minikube via KVM.

**What happened**:

Created a service account with multiple referenced secrets (by removing one, having the controller create a fresh one, then adding the first one back).

```
$ kubectl get serviceaccount default -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: 2017-01-25T07:19:31Z
  name: default
  namespace: default
  resourceVersion: "6875"
  selfLink: /api/v1/namespaces/default/serviceaccounts/default
  uid: 9d5d30a1-e2ce-11e6-9df3-92a387533b2d
secrets:
- name: default-token-gk8he
- name: default-token-yuem9
$ kubectl get secrets 
NAME                  TYPE                                  DATA      AGE
default-token-gk8he   kubernetes.io/service-account-token   3         8m
default-token-yuem9   kubernetes.io/service-account-token   3         1h
```

Ran two pods.

```
$ kubectl run my-nginx --image=nginx --replicas=2 --port=80
```

Both mounted different service account secrets.

```
$ kubectl get pods -o json | jq -r '.items[] | "\(.metadata.name) \(.spec.volumes[].name)"'         
my-nginx-379829228-nzps0 default-token-gk8he
my-nginx-379829228-w1wds default-token-yuem9
```

**What you expected to happen**:

Based on the internal comments I expected the first referenced service account to be mounted, not the second.

- https://github.com/kubernetes/kubernetes/blob/v1.5.2/plugin/pkg/admission/serviceaccount/admission.go#L72
- https://github.com/kubernetes/kubernetes/blob/v1.5.2/plugin/pkg/admission/serviceaccount/admission.go#L271

**How to reproduce it** (as minimally and precisely as possible):

See "what happened" section.

cc @kubernetes/sig-auth-bugs 

Please assign to me, I'd like to try and push a fix.

**Comment by deads2k** [comment]
@liggitt related to discussion we had

**Comment by deads2k** [comment]
@ericchiang can you sketch out what you'd like to do?  Recall that this is a problem for more than just the admission plugin.  Anyone trying to get an SA credential will face the issue, even other clients or users trying to get long-lived, revocable tokens for scripts.

**Comment by ericchiang** [comment]
> Recall that this is a problem for more than just the admission plugin.

@deads2k little confused by that statement. This appears to just be an ordering issue in the admission plugin. This block here:

https://github.com/kubernetes/kubernetes/blob/d62fca231e529dad6faa2dc2b1fa0cf89ad09863/plugin/pkg/admission/serviceaccount/admission.go#L296-L317

```go
func (s *serviceAccount) getReferencedServiceAccountToken(serviceAccount *api.ServiceAccount) (string, error) {
	if len(serviceAccount.Secrets) == 0 {
		return "", nil
	}

	tokens, err := s.getServiceAccountTokens(serviceAccount)
	if err != nil {
		return "", err
	}

	references := sets.NewString()
	for _, secret := range serviceAccount.Secrets {
		references.Insert(secret.Name)
	}
	for _, token := range tokens {
		if references.Has(token.Name) {
			return token.Name, nil
		}
	}

	return "", nil
}
```

Looks like it needs to be

```go
func (s *serviceAccount) getReferencedServiceAccountToken(serviceAccount *api.ServiceAccount) (string, error) {
	if len(serviceAccount.Secrets) == 0 {
		return "", nil
	}

	tokens, err := s.getServiceAccountTokens(serviceAccount)
	if err != nil {
		return "", err
	}

	tokens := sets.NewString()
	for _, token := range tokens {
		tokens.Insert(token.Name)
	}
	// Ensure that the valid secret listed first is the one returned for mounting.
	for _, secret := range serviceAccount.Secretes {
		if tokens.Has(secret.Name) {
			return secret.Name, nil
		}
	}

	return "", nil
}
```

**Comment by deads2k** [comment]
> @deads2k little confused by that statement. This appears to just be an ordering issue in the admission plugin. This block here:

How would any other client (which won't have access to the list of keys on the api-server) make the determination about which token to use?

**Comment by ericchiang** [comment]
I'm making the assumption that all of the secret references in a service account point to valid secrets. So if there are multiple tokens referenced, clients could choose anyone and get valid credentials.

**Comment by liggitt** [comment]
@ericchiang's fix looks correct for the particular problem of which one the admission plugin uses
