### ISSUE TITLE
kubectl: cli can't create multiple labels with same key

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#40413]
**Kubernetes version** (use `kubectl version`): v1.5.2

**What happened**:
I wanted to label a bunch of nodes with `role=prow` and `role=build` but I seem to only be able to do so with `kubectl edit`.

**What I tried:**

* `kubectl label node --all role=build role=prow` resulted in only the latter label applying.

* `kubectl label node --all role=build && kubectl label node --all role=prow` results in `'role' already has a value (build), and --overwrite is false ` ... and `--overwrite` does as it's name implies.

* using a comma doesn't work either, it fails the regex: `(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?`

**Comment by liggitt** [comment]
multiple labels with the same key never works, edit will let you submit that, but only one wins when applied

**Comment by natanielmendes** [comment]
There was a question in my CKAD exam related to that... 2 NetworkPolicies already created were given. The question stated that I could not edit the NetworkPolicy. What should I do in order to have label app=db and app=redis in the same pod? 

PS: One network policy had the podSelector with label app=db and the other had the podSelector with label app=redis.

**Comment by nic-hima** [comment]
^ I would also like an answer on this. Ran across a similar problem, different application.

**Comment by felipeschossler** [comment]
I found the same thing @natanielmendes, you found some explanation about this?

**Comment by renejahn** [comment]
Has there been a solution to what @natanielmendes mentioned?

**Comment by pctseng7** [comment]
Following, is there any update or solution?

**Comment by ajeebpeter** [comment]
I have got the same question on my CKAD and killed my time. Ideally the option is change network policy. but that was restricted, . Now I am  curious why a question like that appeared. Is it a mistake? or any solution!!.

**Comment by asabaini** [comment]
same here. Anybody knows the answer to this? I feel like the question might have been posed incorrectly during the test

**Comment by ritssoft** [comment]
+1. Anyone got the answers? For me looks like the question is framed wrong!!

**Comment by jdhanota** [comment]
+1 Is there any answer? I also got the same question in my CKAD exam.

**Comment by jdhanota** [comment]
@ivneetsinghwahi03 - There was only one label available in each network policy.

**Comment by andreapulvirenti** [comment]
Same question here during my CKAD exam, I didn't have a solution for this. Anyone have any idea what's the correct action? 
I'm gonna ask an exam review

**Comment by Laza034** [comment]
Same question here on CKAD. Anyone has any insight?
