### ISSUE TITLE
kubectl warning when using Docker v1.13 on ARM64/Aarch64

### ISSUE THREAD

**Issue by umiddelb** [kubernetes/kubernetes#40431]
**What keywords did you search in Kubernetes issues before filing this one?**:
Docker v1.13

---

**BUG REPORT:**

**Kubernetes version** (use `kubectl version`):
```
ubuntu@c2:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/arm64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
ubuntu@c2:~$ dpkg -l | grep kube
ii  kubeadm                        1.6.0-alpha.0-2074-a092d8e0f95f52-00 arm64        Kubernetes Cluster Bootstrapping Tool
ii  kubectl                        1.5.1-00                             arm64        Kubernetes Command Line Tool
ii  kubelet                        1.5.1-00                             arm64        Kubernetes Node Agent
ii  kubernetes-cni                 0.3.0.1-07a8a2-00                    arm64        Kubernetes CNI
...
ubuntu@c2:~$ sudo kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/arm64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: ODROID-C2, Aarch64
- **OS** (e.g. from /etc/os-release): 16.04.1 LTS (Xenial Xerus)
- **Kernel** (e.g. `uname -a`): 4.10.0-rc5-c2-86591-gfac4d3e
- **Install tools**: see [here](http://blog.hypriot.com/post/setup-kubernetes-raspberry-pi-cluster/)
- **Others**:

**What happened**:
After upgrading from Docker v1.12.3 (distro version 1.12.3-0ubuntu4~16.04.2) to Docker v1.13 (build from source) ` kubeadm init --pod-network-cidr 10.1.1.0/24` refuses to start without `--skip-preflight-checks` enabled:
```
ubuntu@c2:~$ sudo kubeadm init --pod-network-cidr 10.1.1.0/24
[kubeadm] WARNING: kubeadm is in alpha, please do not use it for production clusters.
[preflight] Running pre-flight checks
[preflight] The system verification failed. Printing the output from the verification:
OS: Linux
KERNEL_VERSION: 4.10.0-rc5-c2-86591-gfac4d3e
CONFIG_NAMESPACES: enabled
CONFIG_NET_NS: enabled
CONFIG_PID_NS: enabled
CONFIG_IPC_NS: enabled
CONFIG_UTS_NS: enabled
CONFIG_CGROUPS: enabled
CONFIG_CGROUP_CPUACCT: enabled
CONFIG_CGROUP_DEVICE: enabled
CONFIG_CGROUP_FREEZER: enabled
CONFIG_CGROUP_SCHED: enabled
CONFIG_CPUSETS: enabled
CONFIG_MEMCG: enabled
CONFIG_INET: enabled
CONFIG_EXT4_FS: enabled
CONFIG_PROC_FS: enabled
CONFIG_NETFILTER_XT_TARGET_REDIRECT: enabled (as module)
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled (as module)
CONFIG_OVERLAY_FS: enabled (as module)
CONFIG_AUFS_FS: not set - Required for aufs.
CONFIG_BLK_DEV_DM: enabled (as module)
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
DOCKER_VERSION: 1.13.0
DOCKER_GRAPH_DRIVER: overlay2
[preflight] Some fatal errors occurred:
        unsupported graph driver: overlay2
[preflight] If you know what you are doing, you can skip pre-flight checks with `--skip-preflight-checks`
```

**Anything else do we need to know**:
Beside of this warning, `kubeadm init` starts up nicely, and I'm able to join other nodes as well (using ` sudo kubeadm join --skip-preflight-checks --token=...`)

**Comment by kargakis** [comment]
@kubernetes/kubeadm-maintainers

**Comment by pires** [comment]
Docker 1.13 just got released and we haven't tested it thoroughly.

**Comment by mikedanese** [comment]
http://github.com/kubernetes/kubeadm would be the place to ask for support for latest docker versions. Right now we recommend and test against 1.11.2-0. The warning is legitimate. As they error says, you can choose to ignore the warning by passing --skip-preflight-checks.

**Comment by vielmetti** [comment]
```
[preflight] Some fatal errors occurred:
        unsupported graph driver: overlay2
```
What does this mean? I know that with Docker earlier than 1.13 and with Go earlier than 1.8, there is a known bug in overlay2.  https://github.com/docker/docker/issues/27384

**Comment by pires** [comment]
That means Docker 1.13 won't work with kubeadm for the time being. My suggestion is to pin Docker package version to 1.11.x.

**Comment by umiddelb** [comment]
Where can I find some tests to run against the cluster and check whether Docker 1.13 is OK or not.

**Comment by luxas** [comment]
@vielmetti It's just a warning/check that sig-node hasn't validated the overlay2 driver. 
It'll work just fine if you pass `--skip-preflight-checks` or change driver to overlay which is known to work at least.

**Comment by luxas** [comment]
@umiddelb Just skip the checks and see if it works ;)

**Comment by umiddelb** [comment]
The cluster starts up apparently, are there any health checks / integration tests I can run?

**Comment by vielmetti** [comment]
@umiddelb - I would run tests from https://github.com/dmcgowan/dsdbench and check the storage drivers if I were doing integration testing.

**Comment by vielmetti** [comment]
The "unsupported graph driver" message is at https://github.com/kubernetes/kubernetes/blob/44f00e1019f3a4d667a5b2caa09b76ca19a6347b/test/e2e_node/system/docker_validator.go#L77-L85

Where is the list of supported graph drivers?

**Comment by pires** [comment]
@vielmetti see official Docker documentation at https://docs.docker.com/engine/userguide/storagedriver/selectadriver/#/overlay-vs-overlay2.

**Comment by luxas** [comment]
x-ref: https://github.com/kubernetes/kubernetes/issues/32536

**Comment by umiddelb** [comment]
@vielmetti 

>  I would run tests from https://github.com/dmcgowan/dsdbench and check the storage drivers if I were doing integration testing.

Apparently, the tests doesn't refer to Kubernetes.  I suppose the Docker people should have run these tests (or something similar) before releasing v1.13.

**Comment by pires** [comment]
Another reason why not to use Docker 1.13, https://github.com/kubernetes/kubernetes/issues/40182#issuecomment-276392353. While there's a workaround, jumping to the latest version always breaks something 👎

**Comment by vielmetti** [comment]
@pires I am on a test and development system looking for issues, so the more things that break and get fixed as a result the better. It was reported that no one had the resources to test Docker 1.13 RC with k8s before the Docker release which seems suboptimal. Of course we also have a Go 1.8 release coming up which makes the test matrix even larger. Suggestions?
