### ISSUE TITLE
Make all controllers wait for caches to sync before starting

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#40444]
Follow-up to #40385

We need to make all controllers wait for the caches they rely on to sync before beginning their processing loops.

- [ ] `pkg/controller/volume/attachdetach/attach_detach_controller.go`
- [ ] ...

**Comment by spiffxp** [comment]
/sig scalability
since the original PR was tagged as sig/scability

**Comment by ncdc** [comment]
@deads2k I think we can close this one too?

**Comment by deads2k** [comment]
> @deads2k I think we can close this one too?

yeah I think so.
