### ISSUE TITLE
Bugs in docker 1.11 may stop kubelet from creating containers in the docker-CRI implementation

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#40443]
Forked from #34289.

In some cases, when docker (1.11.2) fails to create a container, it will not release the "name" associated with the container. kubelet can never create a container with the same name again. This phantom container cannot be listed or removed. The only way to release the name is to restart the docker daemon.

```console
$ sudo docker run --name=foo --security-opt=foo:bar busybox
docker: Error response from daemon: Invalid --security-opt 2: "foo:bar".
See 'docker run --help'.
$ sudo docker run --name=foo busybox
docker: Error response from daemon: Conflict. The name "/foo" is already in use by container 3f7fae9d56619c67cf1baa85bab8e649ef344931ccae385b3cec809bf79fe829. You have to remove (or rename) that container to be able to reuse that name..
See 'docker run --help'.
$ sudo docker rm foo   
Error response from daemon: No such container: foo
$ sudo docker rm 3f7fae9d56619c67cf1baa85bab8e649ef344931ccae385b3cec809bf79fe829 
Error response from daemon: No such container: 3f7fae9d56619c67cf1baa85bab8e649ef344931ccae385b3cec809bf79fe829
```

The [deferred cleanup function](https://github.com/docker/docker/blob/v1.11.2/daemon/create.go#L75) relies on the container id lookup, but the id (not the name) [hasn't been registered](https://github.com/docker/docker/blob/v1.11.2/daemon/create.go#L92) at the time of the [failure](https://github.com/docker/docker/blob/v1.11.2/daemon/create.go#L83-L90). This relevant code was refactored in docker 1.12+ and the bug was fixed.

Pre-CRI kubelet embeds a random string into the container name, so it'll always recover in this situation (i.e., no naming conflict). Now kubelet uses deterministic names for containers, this become a problem. The container will never be created. @Random-Liu wrote a script to scan the kubelet-cri-serial build logs and found that about ~7% of the builds ran into this problem.

We've discussed several fixes and decided to add a workaround in the `dockershim` package (note that it's not in kubelet because this is caused by a docker bug)
1. create a container
2. if it fails due to naming conflict, try removing the container
3. if the removal request fails with a "No such container" response, try creating a container with a `_randomstring` suffix appended to the name.
When parsing the name, dockershim will have to check if this suffix exists and trim them before returning to kubelet.

/cc @dchen1107 @kubernetes/sig-node-bugs

**Comment by yujuhong** [comment]
The reliable reproduce was inspired by #40179

**Comment by discordianfish** [comment]
Still seeing this problem with Kubernetes 1.11.2 even though the supposed fix is included.
