### ISSUE TITLE
manifest file edits via vim break k8s due to vim dot files (k8s 1.5.1+)

### ISSUE THREAD

**Issue by lilnate22** [kubernetes/kubernetes#40452]
Following from issues created here:
https://github.com/kubernetes/kubernetes/issues/40109
https://github.com/kubernetes/kubeadm/issues/106
https://github.com/kubernetes/kubernetes/issues/40331

I created 3 k8s clusters, each created via kubeadm (following kubeadm guide + weave cni).
A. 1.5.0
B. 1.6.0-alpha
C. 1.6.0-alpha

I edited each of the 3 clusters `kube-apiserver.json` file in `/etc/kubernetes/manifests` by adding the following valid flag: `--service-node-port-range`

`cluster A` which is pre 1.5.1 was changed via vim, and i saw changes immediately via `kubectl describe po {my-apiserver-po-name} -n kube-system`

`cluster B` which is POST 1.5.1 was changed via nano, and same thing. i see the changes immediately 

`cluster C` was changed via vim, breaks. (same results as above issues). i can wait 15+ mins w/o kube-api not coming up. in order for me to get my `cluster c` back up, i had to break json (in my case i removed a "`,`" from the arg array)

# TO TEST:
create latest k8s cluster, edit any of the manifest files with valid data via vim. observe cluster breaks. edit manifest file via **invalid** data, then re-edit with valid data, observe cluster is running back up.

create latest k8s cluster, edit any of the manfiest file with valid data via nano. observe cluster is fine.

CC: @colemickens @DMXRoid @ericchiang @Lokicity  in case you guys want to solve your issues (or rebut my "fix")

**Comment by colemickens** [comment]
I don't understand the suggested fix. It seems easier to just `systemctl restart kubelet`. The things running will keep on trucking and that's enough to get kubelet to fire up and process the yamls.

**Comment by lilnate22** [comment]
@colemickens  what i found was editing via nano instead of vim seemed to have solved the initial problem, thus my need to even restart kubelet

**Comment by colemickens** [comment]
Avoiding triggering the bug is a good way to avoid it 😄. Anyway, I just meant for your Cluster C, you could've just restarted the `kubelet`. Either way, it's really weird (and clearly a bug) that a swap file is causing kubelet to stop even considering reconciling non-swap file yamls...

**Comment by antoineco** [comment]
@colemickens: the [kubelet documentation page](https://kubernetes.io/docs/admin/kubelet/) states:
> `--pod-manifest-path` (...) Files starting with dots will be ignored.

It is actually not the case:
```
/etc/kubernetes/manifests $ sudo touch .testfile
```
```
/etc/kubernetes/manifests $ journalctl -u kubelet
file_linux.go:107] can't process config file "/etc/kubernetes/manifests/.testfile": /etc/kubernetes/manifests/.testfile: read '', but couldn't parse as pod(Object 'Kind' is missing in 'null').
```
When using an editor with creates temporary dot files like vim this can actually be quite an issue.

**Comment by devonbarrett** [comment]
Encounter the same thing while trying to statically edit the apiserver manifest with vim.

```
kubectl version                                                                                                                                                                    
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

Fixed by removing the swap files and restarting kubelet.

**Comment by ericchiang** [comment]
Seems like this bug is converging to address the same issues as https://github.com/kubernetes/kubernetes/issues/40331. That the kubelet isn't ignoring dot files.

**Comment by ericchiang** [comment]
Fixed in 1.7 https://github.com/kubernetes/kubernetes/pull/45111

/close

**Comment by xiangpengzhao** [comment]
ping @thockin for closing fixed issue.

**Comment by xiangpengzhao** [comment]
ping @yujuhong :)
