### ISSUE TITLE
kubelet does not reregister itself

### ISSUE THREAD

**Issue by Calpicow** [kubernetes/kubernetes#40466]
Using kubelet v1.5.2.

When a node drops out due to timeouts or network connectivity, it is not able to reregister itself. kubelet remains in healthy state, so it causes a silent failure.

Logs are littered with the following error messages:

`Jan 25 09:00:31 kube-minion-onprem-1 kubelet: E0125 09:00:31.734407   14189 kubelet_node_status.go:302] Error updating node status, will retry: no node instance returned for "kube-minion-onprem-1"`

It also causes scheduling issues with pods. It is showing up in pod events even though it is no longer in the node list:

`{default-scheduler} Warning FailedScheduling node 'kube-minion-onprem-1' not found`

**Comment by xiangpengzhao** [comment]
#44577 might fix this.

**Comment by jayunit100** [comment]
Yeah it will @ least give clear continuous backoff status and avoid unpredictable behaviour on large cluster.
