### ISSUE TITLE
kubelet access to API server should be subdivided

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#40476]
In order to obtain the resources needed to run pods, Kubelets currently have broad access to the API:
* read any secret
* read any configmap
* read any persistentvolumeclaim
* create/update any pod and pod status
* create/update any node and node status

To properly secure individual nodes and limit the ability of a particular node to access the cluster, the kubelet should only be allowed to retrieve data from the apiserver for resources associated with it. This essentially means that it is only be able to get pods scheduled to it, along with any related items, such as secrets, configmaps, pvcs, etc. This filtering applies to get/list/watch calls as well.

We will not be able to use the generic policy engine for this, as it’s not possible to express rules for this scenario. Instead, we’ll likely need to create a new authorizer with hard-coded rules. We can make this work by building a ref-counter based summary of referenceable objects based on a watch of a subset of resources.

Authorizer/Admission:
* identify requests from particular nodes (pattern already in place with node TLS bootstrapper, builds a user name the node name can be extracted from)
* build the graph of objects referenced by pods bound to the node
* limit the pods that a node is inherently allowed to create (only static pods, only bound to itself, no secret/pvc/configmap references)

~~New API access patterns needed by the kubelet (only needed if we want to allow list/watch of secrets):~~ moved to https://github.com/kubernetes/community/pull/443
* ~~{list,watch,get} {secrets,configmaps,persistentvolumeclaims,...} used by pods bound to the node~~

**Comment by liggitt** [comment]
cc @kubernetes/sig-auth-feature-requests @kubernetes/sig-node-feature-requests

**Comment by ericchiang** [comment]
Do we have any existing APIs that filter list and watch results like this?

Would it be reasonable to implement restrictions for gets on {secrets, configmaps, persistentvolumeclaim}, and updates on pods, then defer futher restrictions on {list,watch} operations once we figure out filtering? Or do nodes {list,watch} secrets today?

**Comment by deads2k** [comment]
> Or do nodes {list,watch} secrets today?

they do not



> Do we have any existing APIs that filter list and watch results like this?

Yes, label and field selection filters can be applied and they are available (and restrictable) on an http request, so it would be consistent to enforce it with an authorizer.

**Comment by timstclair** [comment]
I'm assuming the motivation here is to prevent a node compromise from being equivalent to a cluster compromise, by limiting the potential damage to only resources scheduled (transitively) to the node. Given this goal, what's to stop an attacker from simply updating a pod spec to reference the resource they want access to? An obvious solution is to prevent the node from posting anything other than status updates, but this would break the implementation of static pods on the node (via mirror pods).

Are there any other motivations to this proposal, or do we need to tackle these issues first?

**Comment by liggitt** [comment]
> Given this goal, what's to stop an attacker from simply updating a pod spec to reference the resource they want access to?

Pod spec is immutable

**Comment by timstclair** [comment]
Cool, good to see this is already in place. Perhaps we should extend the limits to prevent certain volume types as well?

**Comment by thockin** [comment]
Would this allow something like "watch all secrets in all namespaces" to server-side filter and return only secrets on this node?  Or would it be an error, and we would have to set up N individual watches ourself?

**Comment by liggitt** [comment]
> Would this allow something like "watch all secrets in all namespaces" to server-side filter and return only secrets on this node? Or would it be an error, and we would have to set up N individual watches ourself?

The ACL filter would likely need to be more explicit. Adding ACL filtering to existing APIs as-is would be... unexpected. But we would like to figure out a way to make watch possible for scenarios like this.

**Comment by wojtek-t** [comment]
> We'd like to find a way to let nodes watch the secrets they're supposed to have access to instead of making them poll or manage lots of individual watches, but even protecting the existing GET requests based on the node->pod->secret relationship would be an improvement.

I agree. Though, since we would like to change kubelet to actually "list+watch" secrets, configmaps, etc., I'm going to put together a proposal for this part once I'm done with 1.6 work. I will focus more on that part, but this will be strictly related to this one.
And I agree that the request should be "explicitly asking for my secrets" not implicit filtering. I will try to put some proposal together in a week or two.

**Comment by wojtek-t** [comment]
So I created the initial draft of my proposal here: https://github.com/kubernetes/community/pull/443
It still has some TODOs to think about it, and I will work on improving the doc itself more towards end of 1.6, but the high level idea should probably be roughly clear.

**Comment by timstclair** [comment]
Can we dedupe this with https://github.com/kubernetes/features/issues/279 ?

**Comment by liggitt** [comment]
closing in favor of https://github.com/kubernetes/features/issues/279
