### ISSUE TITLE
etcd caching defaults are too much black magic.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#40493]
We've had a number of bouncing reports on the cache in the past being too high (using too much memory), then the cache being too magic.  Computed by node count :/ 

This is to record we should probably make the cacheing objects themselves smarter.  e.g. grow to a threshold and recycle based on time-window and hit-count. 

/cc @wojtek-t @hongchaodeng @kubernetes/sig-scalability-feature-requests @smarterclayton @enj

**Comment by hongchaodeng** [comment]
Just to clarify, you mean the etcd2 helper's cache, i.e. decoding cache, right?

**Comment by timothysc** [comment]
Yes, but the watch cache numbers are kind of magic too.
