### ISSUE TITLE
local-up-cluster.sh: etcd detection has false positives

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#40499]
I had a zombie process, `etcd-operator`, running due to a test on a previous local cluster invocation. Unfortunately the part of the local cluster up script that detects if a previous etcd installation is running got confused by this and refused to proceed until I killed it. (Fortunately it was a zombie and it didn't matter if I killed it.)

Marking as test-infra since the test scripts are the primary consumer of that logic, I believe.

**Comment by alindeman** [comment]
I'll take a stab at this.
