### ISSUE TITLE
kubectl get pod require `-a` even with specific pod-id (when pod failed)

### ISSUE THREAD

**Issue by smondet** [kubernetes/kubernetes#40492]
**Kubernetes version** (use `kubectl version`):

```
 $ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.8", GitCommit:"c5fcb1951afb8150e4574bc234aed957cb586eb0", GitTreeState:"clean", BuildDate:"2017-01-12T02:14:29Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04

**What happened**:

I have a pod `3676380c-18fe-5fc3-94e2-319f27f7988e` that failed.

```
kubectl get -o json pod 3676380c-18fe-5fc3-94e2-319f27f7988e
```

returns nothing

```
kubectl get -o json -a pod 3676380c-18fe-5fc3-94e2-319f27f7988e
```

returns the right thing.

It's a bit silly to require `-a` when a pod id is explicitly given.
I think this started happening recently only on the GKE (or maybe the time needed to “forget” the pod has just become shorter).

**Comment by smarterclayton** [comment]
Fixed in #42216
