### ISSUE TITLE
workqueue: timed work queue: key type is too unique

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#40494]
The TimedWorkQueue object appears to lack a critical feature of the original WorkOueue, namely that similar items are aggregated together. By adding the time member to to the key type, it ensures that (time, item) pairs are unique-- you can add the same item multiple times as long as the time differs. This removes the guarantee that two goroutines wouldn't process the same item at the same time.

**Comment by liggitt** [comment]
@deads2k
Iirc, the timed queue feeds a regular queue, so the guarantee still holds

**Comment by liggitt** [comment]
Sorry, I was thinking of the delaying queue, which does key correctly

**Comment by caesarxuchao** [comment]
I'm going to remove timed workqueue. It's used to gather metrics for queues used in the garbage collector. This feature is supported by a regular workqueue now.
