### ISSUE TITLE
kubectl run with --rm and --expose don't remove service on termination

### ISSUE THREAD

**Issue by tanapoln** [kubernetes/kubernetes#40504]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T07:31:07Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Self-Hosted
- **OS** (e.g. from /etc/os-release): Ubuntu
- **Kernel** (e.g. `uname -a`): Linux 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubeadm
- **Others**:

**What happened**:
I'm create pod with command: `kubectl run go-http-test -it --rm --port 5000 --expose=true --image=tanapolsh/go-http-test --restart=Never`, it also create service for an option `--expose=true` but once I terminate pod, service don't be removed along with pod which cause next execution of the same command would get this error `Error from server (AlreadyExists): services "go-http-test" already exists`

**What you expected to happen**:
kubectl should remove the service on termination.

**How to reproduce it** (as minimally and precisely as possible):
* create pod using `kubectl run go-http-test -it --rm --port 5000 --expose=true --image=tanapolsh/go-http-test --restart=Never` and wait for pod to started
* Press `CTRL + C` and wait for pod is terminated
* run command `kubectl run go-http-test -it --rm --port 5000 --expose=true --image=tanapolsh/go-http-test --restart=Never` again, so you will get error

**Anything else do we need to know**:

**Comment by xiangpengzhao** [comment]
PR is on the way :)
