### ISSUE TITLE
Deployment in version "v1beta1" cannot be handled as a Deployment: [pos 620]: json: expect char '"' but got char '1'

### ISSUE THREAD

**Issue by naisanza** [kubernetes/kubernetes#40510]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): v1.5.1

**Environment**:
- **Cloud provider or hardware configuration**: Local server
- **OS** (e.g. from /etc/os-release): Ubuntu 16.10
- **Kernel** (e.g. `uname -a`): 4.8.0-34-generic
- **Install tools**: [https://kubernetes.io/docs/getting-started-guides/kubeadm/](https://kubernetes.io/docs/getting-started-guides/kubeadm/)
- **Others**: 

**What happened**:
Edited Deployment config in kubernetes/dashboard UI to include [NEO4J_HEAP_MEMORY ](https://neo4j.com/developer/docker-23/)environment variable for [neo4j](https://hub.docker.com/_/neo4j/)

**What you expected to happen**:
ReplicaSet and Pods updated with new config

**How to reproduce it** (as minimally and precisely as possible):
Create new Deployment with out environment variable. Edit the deployment and add the new environment variable

**Anything else do we need to know**:

Error:
![Error](http://i.imgur.com/Un1a5zE.png)

I got the structure and where to add the `NEO4J_HEAP_MEMORY` from here:
![Config structure](http://i.imgur.com/agXld23.png)

And updated it to the existing Deployment:
![Updating existing deployment](http://i.imgur.com/VDm3Da0.png)

**Comment by kargakis** [comment]
@kubernetes/kube-ui-maintainers

**Comment by naisanza** [comment]
@kargakis In afterthought, actually think I should have made this in kubernetes/dashboard instead.

**Comment by kargakis** [comment]
@naisanza yes please move the issue there and close this one

**Comment by naisanza** [comment]
Moved https://github.com/kubernetes/dashboard/issues/1603
