### ISSUE TITLE
Kubeadm should install a default storage class

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#40518]
This is part of proposal https://github.com/kubernetes/community/pull/285.

We need `kubeadm init --cloud-provider=XXX` to look at addon manager files (shipped as kubernetes.tar.gz) and if `cluster/addons/storage-class/XXX/default.yaml` exists, then kubeadm should make sure this file is injected into Kubernetes (but it should not overwrite any existing objects, see https://github.com/kubernetes/kubernetes/issues/39561). Using addon manager would be the best.

**Comment by luxas** [comment]
@jsafrane Please file this issue in kubernetes/kubeadm instead so we get it in our tracking.
Thank you!
