### ISSUE TITLE
hack/local-up-cluster is broken in 1.5.2...

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#40524]
...and there is no easy way to test Kubernetes upgrades with a custom etcd data directory. Using the script from master with old binaries does not work because there are new flags that old binaries don't have. Ideally, I would like a process that would allow me to deploy release binaries, probably by using the same version of the local-up-cluster script to run them. In the short term, fixing local-up-cluster for 1.5.2 would be desirable.

@kubernetes/sig-auth-misc because the breakage seems auth-related
@kubernetes/sig-testing-misc is there an easy way to test locally upgrades?

**Comment by deads2k** [comment]
> @kubernetes/sig-auth-misc because the breakage seems auth-related

`hack/local-up-cluster.sh` really seems to be best effort. There's no CI on it to make sure it works, no consistent topology, and insufficient add-ons to actually produce a working system.  I think that making it reliable would be a significant undertaking and should probably involve narrowing scope and expanding the cluster to be workable.

**Comment by jayunit100** [comment]
the general issue is here  https://github.com/kubernetes/kubernetes/issues/14207  , suggest we use this specifically for the 1.5.2 details....

**Comment by MHBauer** [comment]
If `local-up-cluster` isn't supported, what is? I want to stand up a non-prod version of my changes for long enough to manually test.

**Comment by MHBauer** [comment]
Did #40193 fix this problem?

**Comment by kargakis** [comment]
No, local-up-cluster is broken for 1.5 and it will probably stay as is forever.
