### ISSUE TITLE
Controller manager spending a lot of CPU on Deployments (much less for RS/RC/SVC etc.)

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#40520]
I didn't find this problem being reported, so I apologize for duplicates.

I tried multiple versions of Kubernetes 1.4.x and 1.5.1, and they all exhibit the same behavior.

The problem I have is the k8s controller manager seems to be spending a lot of CPU on periodically maintaining deployments than other k8s object types, e.g., replicasets, replication controllers, service endpoints, etc. In my environment, with 2500 deployments, the controller manager is almost saturating a 8-core CPU machine. This cluster has 25 worker nodes. 

cc @timothysc

**Comment by kargakis** [comment]
The Deployment controller is running upgrades of ReplicaSets which in turn continuously resync Deployments so this doesn't surprise me. We are going to have the same problem with DaemonSets and StatefulSets, or maybe not assuming normal clusters will have many more Deployments than the rest of the workload controllers. It would be nice to see a cpu profile.

cc: @kubernetes/sig-apps-misc @kubernetes/sig-scalability-misc

**Comment by timothysc** [comment]
@huang195 Thanks for reporting, we'll discuss this topic today.

**Comment by huang195** [comment]
@kargakis the cpu profile is pretty uninteresting. It basically shows every 30 seconds or so, controller manager sucks up all the cpu for X number of seconds till it looked over all the Deployments in the cluster, and the cpu would go down to close 0. When the number of deployments is larger, X becomes longer. When we approach 2500 Deployments in the cluster, X comes close to 30 seconds, i.e., saturating CPU.

I'm a bit puzzled at why Deployments (apparently you also mentioned DaemonSets and StatefulSets would have similar problems) would incur so much more overhead than just the plain vanilla replicasets. My understanding is Deployments is only better than replicasets for rolling upgrade as it leaves the server orchestrate the rolling upgrade process. But that's a lot of overhead Deployments have over Replicasets.

**Comment by kargakis** [comment]
Ah so this is because of the frequent relists? This has been pushed in 1.6 back to 24h: https://github.com/kubernetes/kubernetes/pull/38080

**Comment by kargakis** [comment]
> Ah so this is because of the frequent relists? This has been pushed in 1.6 back to 24h: #38080

Actually I don't remember off the top of my head - defaultResync is either 12h or 24h now

**Comment by huang195** [comment]
I'm not sure we're talking about the same issue then as CPU spikes in my experiment certainly were a lot shorter than 12h/24h, and they were more on the order of 30 seconds to 1 minute range.

**Comment by kargakis** [comment]
@huang195 did you test on master?

**Comment by huang195** [comment]
Yes, the cpu utilization of the controller manager on a master node periodically spikes every 30 secs or so, and when there are too many Deployments in the cluster, controller manager saturates the CPU on the master node.

**Comment by kargakis** [comment]
The 30s occurence seems like it's the relist of the controller which was
increased in https://github.com/kubernetes/kubernetes/pull/38080 and it
seems that it should be random between 12h and 24h (
https://github.com/kubernetes/kubernetes/blob/ae1c9a2b25ddc043b2b93d4ef11bacc02d4fd55f/cmd/kube-controller-manager/app/options/options.go#L144
)

**Comment by huang195** [comment]
Is there a good way to check if #38080 is included in the v1.5.1 release?

**Comment by huang195** [comment]
It looks like this is not part of 1.5.1 as that was created on Dec 12, 2016, and this PR was merged on Dec 19. Will have to test out if the problem I'm seeing with deployments still exist in a later release.

**Comment by kargakis** [comment]
So you haven't tested from master :) 1.6.0-alpha.1 is out - give it a shot: https://github.com/kubernetes/kubernetes/releases/tag/v1.6.0-alpha.1

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by kargakis** [comment]
This shouldn;t be an issue in 1.6 - if it still is, please reopen
