### ISSUE TITLE
weird bazel flake

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#40526]
Seeing 
```
I0126 13:47:30.193] Executed 0 out of 410 tests: 410 tests pass.
I0126 13:47:30.194] There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
I0126 13:47:30.194] Kubernetes version missing; not uploading ci artifacts.
W0126 13:47:30.295] cat: bazel-genfiles/version: No such file or directory
E0126 13:47:30.308] Build failed
I0126 13:47:30.308] process 465 exited with code 1 after 4.6m
E0126 13:47:30.308] FAIL: pull-kubernetes-bazel
```
 in bazel https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/40312/pull-kubernetes-bazel/2432/ and https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/40312/pull-kubernetes-bazel/2454/

I don't know what it means

**Comment by spxtr** [comment]
Caused by #40480, thanks for opening the issue. I'll fix.

**Comment by ixdy** [comment]
oh, this is a weird fall-out from #40480. We aren't always building `bazel-genfiles/version` anymore. I guess it was cached for a while and then fell out of the cache.
