### ISSUE TITLE
kubectl-container side car fails to start

### ISSUE THREAD

**Issue by bpulito** [kubernetes/kubernetes#40540]
Is this a BUG REPORT or FEATURE REQUEST? BUG REPORT

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7+92b4f97", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"not a git tree", BuildDate:"2016-12-10T07:35:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: MacBook Pro (Retina, 15-inch, Mid 2015)
- **OS**  OSX Version 10.11.3
- **Kernel** (e.g. `uname -a`): Darwin blpmacbook 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
- **Install tools**: 
- **Others**:

**What happened**:
I tried to create a side car using the instructions from here: 
https://github.com/kubernetes/kubernetes/tree/master/examples/kubectl-container

I'm able to:
- make kubectl
- make container TAG=v1.5.3-beta.0.41 (I also tried latest version in master branch)

When I try to start a POD with the kubectl container I get the following error on startup:

32s	32s	1	{kubelet minikube}	spec.containers{kubectl}		Warning	Failed		Failed to start container with docker id f256982f5c53 with error: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: exec format error"

If I use the image specified in pods.json it works fine. This is the image that works:
gcr.io/google_containers/kubectl:v0.18.0-120-gaeb4ac55ad12b1-dirty

**What you expected to happen**:

I expect the image I built to startup with no errors.

**How to reproduce it** (as minimally and precisely as possible):

Just follow the instructions here:
https://github.com/kubernetes/kubernetes/tree/master/examples/kubectl-container

 and build the latest master branch or the release-1.5 branch.

**Anything else do we need to know**:
nope

**Comment by spzala** [comment]
@bpulito hi, just trying to help out and see if we can close this issue, I tried running this example and it worked well for me - using existing GCR image as provided in pod.json or using my own image using the instructions provided in the readme. I could create pod and also access it. The only difference is I didn't push to GCR but to my own docker hub (as the instruction also says that you can use whatever you want to use). Here is snippet from ```kubectl get po``` , 
```
  - args:
    - proxy
    - -p
    - "8001"
    image: spzala/k8sissuetesting:v1.9.0-alpha.1.1288
    imagePullPolicy: Always
    name: kubectl
```
As you could see I have used current master of v1.9.0. 
Was your pod status was running successfully? How did you try access the pod? Thanks!
