### ISSUE TITLE
get all does not show third party resources or secrets 

### ISSUE THREAD

**Issue by ahakanbaba** [kubernetes/kubernetes#40545]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

Searched for: 
get all secrets 
Did not see duplicated 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT 

**Kubernetes version** (use `kubectl version`):

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:49:33Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:43:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Environment**:
- **Cloud provider or hardware configuration**:
Bare metal Intel 64 bit 

- **OS** (e.g. from /etc/os-release):
Linux
- **Kernel** (e.g. `uname -a`):
Linux compute-master01.dev.box.net 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:

`kubectl get all --namespace=<ns> `  command does not list third party resources and secrets  in its namespace 

**What you expected to happen**:
I expect the `kubectl get all --namespace=<ns> ` to print everything under that namespace 

**How to reproduce it** (as minimally and precisely as possible):

```
# kubectl get all --namespace=sops-dev
NAME      CLUSTER-IP   EXTERNAL-IP   PORT(S)             AGE
svc/app   10.17.6.91   <none>        8216/TCP,9216/TCP   33d
NAME                      READY     STATUS    RESTARTS   AGE
po/sops-274084058-8z7is   3/3       Running   0          2h
po/sops-274084058-rmfo7   3/3       Running   0          2h
```

However that same namespace has Secrets and Third Party Resources (Pki) 

```
# kubectl get Secrets --namespace=sops-dev
NAME                                   TYPE                                  DATA      AGE
default-token-ysb34                    kubernetes.io/service-account-token   3         15d
pki-8   Opaque                                8         1h
[root@compute-master01.dev ~]# kubectl get Pki  --namespace=sops-dev
NAME                                   LABELS    DATA
pki-8   <none>    {"apiVersion":"box-pki.com/v1","data":"ey...
```

**Anything else do we need to know**:

**Comment by foxish** [comment]
cc @kubernetes/sig-cli-bugs

**Comment by liggitt** [comment]
This is working as intended. See https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#rules-for-extending-special-resource-alias---all

**Comment by liggitt** [comment]
The problem is that "delete all" becomes unsafe if secrets, pvcs, and (potentially) ThirdPartyResources are included, and "get all" is confusing if they aren't.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/issues/18023 Is likely to be more successful

**Comment by ahakanbaba** [comment]
Thanks for the response.
