### ISSUE TITLE
aws node name problem - causes e2e failures

### ISSUE THREAD

**Issue by coffeepac** [kubernetes/kubernetes#40555]
**Kubernetes version** (use `kubectl version`): v1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS stable
- **Kernel** (e.g. `uname -a`): 
- **Install tools**: K2 (github.com/samsung-cnct/k2)
- **Others**:

**What happened**:  
attempted to run e2e conformance tests against a v1.5.2 cluster I spun up using our own tool.  received errors for the '[intra-pod](https://github.com/kubernetes/kubernetes/blob/55bee3ad21f025b1416a4e1f10de753f484b66d3/test/e2e/common/networking.go#L33)' networking tests (TCP & HTTP).  Tests were timing out waiting for pods to be created.  Pods could not be created because the pod template in [code](https://github.com/kubernetes/kubernetes/blob/55bee3ad21f025b1416a4e1f10de753f484b66d3/test/e2e/framework/networking_utils.go#L357) has a node selector and there was a disagreement in the node name between the value of 'NAME' from kubectl get nodes and the value of kubernetes.io/hostname.  

kubernetes.io/hostname respects the value of the '--hostname-override' cli switch to kubelet.  We have been setting that to the ip address of the node.  the value of 'NAME', however, does not respect the value '--hostname-override'.  Below is sample output showing this:

> NAME STATUS AGE LABELS 
ip-10-0-113-11.ec2.internal Ready 5h beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=c4.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1c,kubernetes.io/hostname=10.0.113.11

It appears that the AWS cloudprovider requires the node's 'NAME' be the private DNS entry of the node as that's what the cloudprovider uses for [node lookup](https://github.com/kubernetes/kubernetes/blob/55bee3ad21f025b1416a4e1f10de753f484b66d3/pkg/cloudprovider/providers/aws/aws.go#L3239)  I was unable to find any code that enforces this name but I was already pretty deep and kind of didn't want to keep going.

**What you expected to happen**:
I expected e2e conformance tests to pass when using the AWS cloud provider and overriding the hostname of the kubelet.  

**How to reproduce it** (as minimally and precisely as possible):
Spin up a kubernetes clusters in AWS using the AWS cloud provider and use the '--hostname-override' option to be something other than the privateDNS value for the node

**Anything else do we need to know**:
It is also required to not use a custom private domain in a VPC as that will cause AWS to set the hostname to be ip-10-0-0-3.<private DNS values> and the privateDNS needs to be ip-10-0-3.ec2.internal.  This was another thing I had to workaround.

Here's the ticket I did all of my work under:  https://github.com/samsung-cnct/k2/issues/159
Here are the changes I had to make to work around this issue:  https://github.com/samsung-cnct/k2/pull/169

**Comment by calebamiles** [comment]
@justinsb, do you think you could find someone from SIG AWS to help triage this issue? There doesn't seem to be a GitHub team for the SIG so I'm sorry for pinging you directly.

**cc: @chrislovecnm**

**Comment by chrislovecnm** [comment]
Is this still and issue?

**Comment by coffeepac** [comment]
Yes.  We have left our workaround in place but are hitting this issue of 'aws cloud provider ignores `--hostname-override `' in another part of our system.

**Comment by shyamjvs** [comment]
Too old issue (k8s version 1.5).

/close
