### ISSUE TITLE
enable kubectl tests with federation apiserver for secrets

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#40568]
https://github.com/kubernetes/kubernetes/pull/40567 disabled them since `kubectl delete secrets` was flaky.

We need to find and fix the issue and then reenable these tests.

cc @kubernetes/sig-federation-bugs 

Related issues: #39984 and #39985

**Comment by liggitt** [comment]
Probably should be higher priority so it doesn't get dropped

**Comment by nikhiljindal** [comment]
The issue is that we dont wait for the resource to be deleted unless we are using a reaper: https://github.com/kubernetes/kubernetes/blob/dd22743b54f280f41e68f206449a13ca949aca4e/pkg/kubectl/cmd/delete.go#L254.
This breaks for federation since we use finalizers. kubectl should wait for the resource to be deleted.
We should also set OrphanDependents = false. This will have no effect in kubernetes but will enable cascading deletion in federation. Ref https://github.com/kubernetes/kubernetes/issues/38897.

cc @caesarxuchao 

Will send a fix.

**Comment by nikhiljindal** [comment]
Sent https://github.com/kubernetes/kubernetes/pull/40576

**Comment by nikhiljindal** [comment]
Updated #40576 to remove the wait (GET) at the end so it no longer fixes this issue.
Sent https://github.com/kubernetes/kubernetes/pull/40714 to update the test to include a wait which fixes this issue.
