### ISSUE TITLE
Ignoring node xxxx with NetworkUnavailable condition status True

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#40577]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

current master

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04 latest
- **Kernel** (e.g. `uname -a`):
- **Install tools**: custom using blown up configuration

**What happened**:
When I deploy Kubernetes to a single node cluster on GCE with CloudProvider enabled and when I do:

```
~> kubectl get nodes
NAME                    STATUS    AGE       VERSION
hekumar-multizone-bug   Ready     6m        v1.6.0-alpha.0.3971+7a387842598a61
```

But when I create a pod I see following error in scheduler log

```
Ignoring node hekumar-multizone-bug with NetworkUnavailable condition status True
```

This used to work. I agree my deployment is bit weird because I am not using `kube-up.sh` or anything,
I am just running all components of kubernetes manually properly configured to talk to each other. The node has full access to GCE api which is further confirmed by the fact that I can use dynamic provisioning etc.

**What you expected to happen**:

If node is indeed not ready because of Network unavailability, `kubectl get nodes` should not show node as ready. But it looks like something broke recently.

**How to reproduce it** (as minimally and precisely as possible):

Deploy a k8s cluster on a GCE node manually:
1. Copy all kube binaries.
2. start etcd
3. start kube-apiserver, controller, kubelet, scheduler, proxy so as they can talk to each other.
4. schedule a pod

**Comment by justinsb** [comment]
It would be useful to know the full node status as reported by e.g. `kubectl get node hekumar-multizone-bug -oyaml` i.e. is it kubectl that is reporting Ready incorrectly, or is scheduler wrong etc.

**Comment by gnufied** [comment]
This is how full node yaml looks like:

```
apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: 2017-01-27T04:31:24Z
    labels:
      alpha.kubernetes.io/fluentd-ds-ready: "true"
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/instance-type: t1-standard-2
      beta.kubernetes.io/os: linux
      failure-domain.beta.kubernetes.io/region: us-east1
      failure-domain.beta.kubernetes.io/zone: us-east1-d
      kubernetes.io/hostname: foobar-node2
    name: foobar-node2
    namespace: ""
    resourceVersion: "196"
    selfLink: /api/v1/nodesfoobar-node2
    uid: foobar-baz
  spec:
    externalID: "232323232"
    providerID: gce://emacs/us-east1-d/foobar-node2
  status:
    addresses:
    - address: 127.0.0.71
      type: InternalIP
    - address: 127.0.0.1
      type: ExternalIP
    - address: foobar-node2
      type: Hostname
    allocatable:
      alpha.kubernetes.io/nvidia-gpu: "0"
      cpu: "2"
      memory: 7659276Ki
      pods: "110"
    capacity:
      alpha.kubernetes.io/nvidia-gpu: "0"
      cpu: "2"
      memory: 7659276Ki
      pods: "110"
    conditions:
    - lastHeartbeatTime: null
      lastTransitionTime: 2017-01-27T04:31:24Z
      message: Node created without a route
      reason: NoRouteCreated
      status: "True"
      type: NetworkUnavailable
    - lastHeartbeatTime: 2017-01-27T04:33:04Z
      lastTransitionTime: 2017-01-27T04:31:24Z
      message: kubelet has sufficient disk space available
      reason: KubeletHasSufficientDisk
      status: "False"
      type: OutOfDisk
    - lastHeartbeatTime: 2017-01-27T04:33:04Z
      lastTransitionTime: 2017-01-27T04:31:24Z
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: 2017-01-27T04:33:04Z
      lastTransitionTime: 2017-01-27T04:31:24Z
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure
      status: "False"
      type: DiskPressure
    - lastHeartbeatTime: 2017-01-27T04:33:04Z
      lastTransitionTime: 2017-01-27T04:31:24Z
      message: kubelet is posting ready status. AppArmor enabled
      reason: KubeletReady
      status: "True"
      type: Ready
    daemonEndpoints:
      kubeletEndpoint:
        Port: 10250
    nodeInfo:
      architecture: amd64
      bootID: cd4cdb42-50d3-4d94-9822-066f3cb31334
      containerRuntimeVersion: docker://1.12.3
      kernelVersion: 4.4.0-59-generic
      kubeProxyVersion: v1.6.0-alpha.0.3971+7a387842598a61
      kubeletVersion: v1.6.0-alpha.0.3971+7a387842598a61
      machineID: 2274448a4fab1d86d08950efbebf894e
      operatingSystem: linux
```

So indeed network is unavailable because NoRoute has been created, but then may be `kubectl get nodes` should not print the node as ready.

**Comment by justinsb** [comment]
Agreed - this looks like a kubectl issue (I think it's a regression?).  I thought it used to show OutOfDisk at least...

I think the scheduler is correct: the node is not ready.

**Comment by justinsb** [comment]
And hmmm... looks like I'm wrong ... we haven't printed anything but Ready or NotReady there for a long time: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L1527-L1542

**Comment by gnufied** [comment]
cc @kubernetes/sig-network-bugs (looks like only tim is there in that SIG)

**Comment by caseydavenport** [comment]
I saw this the other day as well on v1.6.2. This sounds to me like a kubectl issue - the Node status indicates that it is NotReady but kubectl says something else.

CC @kubernetes/sig-cli-bugs 
/sig cli

**Comment by mengqiy** [comment]
@droot Another `kubectl get` issue that you may be interested.
cc: @pwittrock
