### ISSUE TITLE
Add StatsCollector to provide stats summary

### ISSUE THREAD

**Issue by rjnagal** [kubernetes/kubernetes#4057]
Add a new stats collector component that gather summary of node and pods usage from each node. This information can then be used by components like scheduler and autoscaler.

First version will expose node usage summary for cpu and memory. To start with, summary includes stats for average, maximum, and 90 percentile usage in last minute/hour/day. The stats are precomputed in cAdvisor and routed to the collector through kubelet.

@davidopp @bgrant0607

**Comment by davidopp** [comment]
Sounds great. When Brian described this to me, he said the plan was to publish these as a new API object kind, and then link to the corresponding object from the PodStatus/NodeStatus. This has benefits like allowing us to eventually store the resource updates in a separate etcd instance or whatever. Is this what you're planning to do?

**Comment by rjnagal** [comment]
That is roughly the plan. Although we have not yet settled on actual API object details. 

I'll update them here soon.

**Comment by dchen1107** [comment]
I am closing this one as dup of #12483
