### ISSUE TITLE
Blob storage as a resource

### ISSUE THREAD

**Issue by JonathanFraser** [kubernetes/kubernetes#40570]
This is  feature request for blob storage as a kubernetes resource.  Every cloud vendor has some form of blob storage type and there are some available for on premises stacks as well. The problem is, the each have their own unique API and authentication mechanisms. The request is, to allow kubernetes to shim blob storage in much the same way it does other cloud provisioned resources. This allows user code to be even more decoupled from particular cloud vendors. 

Kubernetes could then provide a standard interface to list,put and get items while taking care of the cloud integration aspects such as vendor specific APIs/authentication requirements.  Blobs stores are inherently multi-access unlike disk backed storage, but they cannot be mounted like network file systems can due to consistency reasons. As a result, blob storage fits in a unique in between point in the storage chain which requires a distinct resource type to access.

**Comment by thockin** [comment]
Kubernetes proper is probably not going to have a blob API.  This is something that can be implemented purely on the published primitives.

@calebamiles has a great idea - you should broach this with @kubernetes/sig-storage-feature-requests
