### ISSUE TITLE
Remove kube-proxy ProxyModeAnnotation

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#40582]
This annotation dates back almost a year.   This is a relatively easy project for someone to contribute.

**Comment by wilkers-steve** [comment]
@thockin I'll work on getting a pull request in tomorrow for this.  Ive been looking at contributing and think this would be a great place to start

**Comment by wilkers-steve** [comment]
@thockin nevermind. Looks like a pull request already exists.  Overlooked the mention due to being on mobile. Cheers

**Comment by thockin** [comment]
We'll file more :)
