### ISSUE TITLE
TimeAdded should be consistently set for all types of Taints.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#40586]
cc @timothysc @davidopp @kevin-wangzefeng @kubernetes/sig-scheduling-bugs

**Comment by davidopp** [comment]
@gmarek Can you explain more specifically? Are you saying we currently set it only for NoExecute, but should instead set it for all taint effects?

**Comment by gmarek** [comment]
Yup. It's not a field which we take actions on, so there's no reason for setting it only for NoExecute taints.

**Comment by kevin-wangzefeng** [comment]
Generally, TimeAdded should be set for all types, and I thought about adding a new admission controller to do this, but there is a time skew issue since apiserver and controller-manager may have different clocks. Not yet come up with better solution.

**Comment by gmarek** [comment]
It'll be only for users information - nothing will take action depending on the field (exactly because of the clock skew). As marked - this is not something urgent, I just think we should either do it before 1.6, or agree to discard it.

**Comment by kevin-wangzefeng** [comment]
Make sense to me.

**Comment by timothysc** [comment]
I've long wondered why google has not enforced some form of ntp as a requirement, tbh, we do.  There will obviously be some drift... but it's not controllable.

**Comment by davidopp** [comment]
@kevin-wangzefeng pointed out we should have "kubectl describe pod" print TimeAdded (as part of printing its taints) when we implement this.
