### ISSUE TITLE
[Federation] Should allow DNSaaS integration to be disabled

### ISSUE THREAD

**Issue by marun** [kubernetes/kubernetes#40616]
Whether the environment is cloud or non-cloud, requiring integration with dnsaas (google dns, route 53) imposes a penalty on the development and testing of features that don't depend on dnsaas.  It should be possible for the control plane to function without a dns provider configured, and ``kubefed`` should allow dnsaas integration to be disabled (e.g. ``--dns-provider=none``).

#40536 is the umbrella issue for tracking this and others targeting improvements in non-cloud deployment of the federation control plane.

cc: @kubernetes/sig-federation-feature-requests

**Comment by madhusudancs** [comment]
Federated Service controller needs a DNS provider for it to be useful. An option is to implement a no-op DNS provider but at the point federated service is not that very useful other than replicating the service object in the underlying clusters. In other words, it is not really a single/unified federated service. It is not useful, then you might as well turn off the controller itself.

That brings me to feature gates that @nikhiljindal is working on and is being tracked in issue #38593. This should allow users to completely turn-off federated services. People who do want federated services on non-cloud environments can either use Google Cloud DNS or AWS Route53, or if they don't want to depend on non-cloud services at all they can use CoreDNS.

Having said all that, there is also a plan to implement private federated services - https://github.com/kubernetes/features/issues/72.

**Comment by marun** [comment]
@madhusudancs It sounds like being able to disable dns is valuable, whether directly or by disabling federated services.   Does it make sense to pursue only the latter if private federated services might benefit from the option to disable directly?

The near-term benefit in either case is to make local development and testing of features other than federated services possible, since dns configuration is currently a blocker for anyone trying to deploy federation outside of gke and aws.  ``kubefed`` doesn't currently configure route53 or google dns for non-cloud (i.e. #40620), and the documentation to configure CoreDNS doesn't exist yet (i.e. #2197).  Even when those gaps are filled, dns configuration won't always be desirable.  Where dns is orthogonal to a feature being developed/tested/evaluated, requiring its configuration would add unnecessary deployment complexity.

**Comment by madhusudancs** [comment]
> @madhusudancs It sounds like being able to disable dns is valuable, whether directly or by disabling federated services. Does it make sense to pursue only the latter if private federated services might benefit from the option to disable directly?

Assuming by "latter" you mean disabling federated services via feature gates, feature gates is going to happen whether we want it for this particular case or not. It is a v1.6 release blocker. We barely dodged that bullet in v1.5. So developers might as well use this for their dev scenarios.

> The near-term benefit in either case is to make local development and testing of features other than federated services possible, since dns configuration is currently a blocker for anyone trying to deploy federation outside of gke and aws. kubefed doesn't currently configure route53 or google dns for non-cloud (i.e. #40620), and the documentation to configure CoreDNS doesn't exist yet (i.e. #2197). Even when those gaps are filled, dns configuration won't always be desirable. Where dns is orthogonal to a feature being developed/tested/evaluated, requiring its configuration would add unnecessary deployment complexity.

I agree. However, it need not necessarily be through yet another flag to `--dns-provider=none`. But some equivalent of it.

**Comment by marun** [comment]
This is already supported via ``kubefed init --dns-provider=``.  I'm not sure if this is good ux, though.  Why isn't ``--dns-provider={none,disabled,etc}`` appropriate?

**Comment by madhusudancs** [comment]
> Why isn't --dns-provider={none,disabled,etc} appropriate?

What's the value it brings to the users over turning off federated services today, other than optimizing for the dev experience? IMO, we shouldn't be optimizing for dev experience over user experience. Every flag that we expose, every choice available to a flag has a cost to it. It is cognitive overload for the users. Unless there is a clear user benefit, we shouldn't be adding those knobs.

**Comment by marun** [comment]
How is ``--dns-provider=`` preferable to something like ``--dns-provider=none``?  This is not about dev experience, it's about error handling to ensure a better user experience.  If a user today accidentally specified an empty dns provider (a bash quoting problem for example) they would end up with a control plane without a service controller.  Requiring an explicit value would make it possible to display an error if an empty value were supplied.

**Comment by madhusudancs** [comment]
> Requiring an explicit value would make it possible to display an error if an empty value were supplied.

If this is about issue #40757 that you just filed, I am not against that. I think that's reasonable.

**Comment by marun** [comment]
Ok, I'll make sure #40757 gets implemented.

To your question of user-facing benefit, the dns provider is the only kube-external dependency of federation today.  Separate from the dev case, which as you say can be accomplished via the opaque passthrough proposed for #40398, what about a deployment that intends to use only private federated services and doesn't want to configure with a dns provider?

**Comment by madhusudancs** [comment]
> To your question of user-facing benefit, the dns provider is the only kube-external dependency of federation today. Separate from the dev case, which as you say can be accomplished via the opaque passthrough proposed by #40398, what about a deployment that intends to use only private federated services (once it is supported) and doesn't want to configure a dns provider?

> Edit: My reading of #40398 suggests that opaque passthrough would be the intended way to support disabling the dns provider for both dev and non-dev use cases. Assuming that is true, how would you like to see the dns provider being disabled at the controller manager? Should it (and not kubefed) accept --dns-provider={disabled,none,etc} or should there be a new flag like --disable-federated-services?

That detail is still TBD. I expect the private federated service design to include that. If that design proposes `--dns-provider={disabled,none,etc}` as the solution to disable DNS integration, then I will be happy with that. I just want  the details to be thoroughly thought through and discussed. We shouldn't just implement it now and scramble through things later because:

1. It doesn't bring much value without private federated services.
2. There are other easy ways to accomplish it given that we don't have private federated services today.

**Comment by marun** [comment]
What other easy ways do you mean?  I misspoke when I said ``--dns-provider=`` would allow things to work (and #40757 would close that loophole anyway).  At present, the controller manager will still fail to start when an empty dns provider is specified due to the services controller erroring out on missing dns configuration.   Unless I'm missing something it will be necessary to allow the controller manager to be configured via a flag (a new one or via ``--dns-provider``) to ensure missing dns configuration does not block startup.

As to private federated services, while it is targeted as 'now' (presumably this release), I see no evidence that work has started.  I don't think simplifying dev should have to wait for something that is not already in progress.  How about supporting an interim flag for the controller manager that can be removed or otherwise reconciled with the mechanism implemented for private federated services before 1.6 is released?

**Comment by madhusudancs** [comment]
> What other easy ways do you mean?

Feature gates. This will let you selectively disable APIs and their associated controllers. That should allow you to disable federated service controller and in turn avoid the controller manager startup failure for your local development.

From this discussion and the other ones, it feels like what you really want is the ability to locally test/debug federation without having to use a cloud DNS provider. If that is indeed the motivation, feature gates will let you do that.

> As to private federated services, while it is targeted as 'now' (presumably this release), I see no evidence that work has started. I don't think simplifying dev should have to wait for something that is not already in progress. How about supporting an interim flag for the controller manager that can be removed or otherwise reconciled with the mechanism implemented for private federated services before 1.6 is released?

Feature gates work is happening right now, as we speak and it is a priority for v1.6. @nikhiljindal is on it. Here is the tracking issue - https://github.com/kubernetes/kubernetes/issues/38593

**Comment by marun** [comment]
Being able to disable federated services is effectively what is required, so closing in favor of #38593.
