### ISSUE TITLE
AWS: Shared resource tags format

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#40611]
This is a discussion issue for implementing shared resource tagging per https://github.com/kubernetes/features/issues/173

## Tag Usage

On review of the AWS code, tags are used:

* Volumes, Instances: I do not think we should share these across clusters.  The cluster "owns" the instance or volume.
* Security Groups: might be nice to share, but they are read/write (for ELBs), so I propose not sharing.
* RouteTables: Only used by kubenet.  Would be nice to share, but they are read/write, so I propose not sharing.  This means sharing a subnet while using kubenet will not be supported (which I think is fine).
* Subnets: We want to share.

## Subnets

We use subnets only to figure out which subnets to attach to an ELB.  An ELB can be internal or public, and we have some heuristics, and we also have two tags `kubernetes.io/role/internal-elb` and `kubernetes.io/role/elb`.

We have the following 3 axes:

* Usage: can a cluster create an ELB and use that subnet
* Ownership: should a cluster delete the subnet when it is deleted
* Internal/External suitable: Is the subnet the right one to use for internal/external ELBs

The current tag is `KubernetesCluster=<clustername>`

I propose a tag that looks like `kubernetes.io/<clustername>=<x>`.  This will allow us to have multiple tags.

* The existing tags & logic should still be recognized, but we should avoid using them in new code / clusters
* Usage rights can be inferred based on the tag existence.  We could have syntax for `x` that implies "no usage",  but I do not think this should be the default. 
* kops (and other tools that use tags) should not delete a subnet unless `x` implies ownership
* `x` can also include the internal/external designation

## Value syntax

Two option for the value syntax:

* we could use JSON, which has the advantage of being easier to evolve
* we could use a simpler comma separate list of strings (or equivalent).

My initial preference is for the simple list of strings, because it is easier to understand and our requirements are not particularly complicated today.  It might be that our requirements are actually more complicated than I think though.

We can recognize JSON easily though, because it will "always" start with `{`.  So we could support both formats.  My preference though is that if we need/want JSON, we should only do JSON.

**Comment by michaelajr** [comment]
I think resources should only be tagged if K8S created them. Things like ELBs should not need to reference tags on subnets since the state store knows about all the zones and subnets. Just use the values there.

**Comment by michaelajr** [comment]
never mind - was just informed that the state store is only used by kops not k8s. So I guess there needs to be a "DO NOT DELETE" tag or something for KOPS if you bring your own subnets. Definitely do not want my subnets deleted if the cluster is torn down.
