### ISSUE TITLE
[Federation][kubefed] Should be possible to disable persistent storage for etcd

### ISSUE THREAD

**Issue by marun** [kubernetes/kubernetes#40617]
Currently ``kubefed init`` creates a PVC for etcd storage in the host cluster and if PV is not configured on the host cluster the control plane api will not be able to start.  While production use of federation requires persistent storage, this should be optional (e.g. ``kubefed init --persistent-storage=false``) when deploying federation for development/testing/evaluation purposes.  Such deployments may not require persistent storage, and may be performed on non-cloud clusters that do not have PV support.

#40536 is the umbrella issue for tracking this and others targeting improvements in non-cloud deployment of the federation control plane.

cc: @kubernetes/sig-federation-bugs

**Comment by shashidharatd** [comment]
if someone else is not working on it, please assign this task to me.

**Comment by madhusudancs** [comment]
@shashidharatd assigned to you.
