### ISSUE TITLE
apiserver panic / crash when trying to exec to a pod

### ISSUE THREAD

**Issue by jsravn** [kubernetes/kubernetes#40615]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
panic apiserver invalid memory address
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.8", GitCommit:"c5fcb1951afb8150e4574bc234aed957cb586eb0", GitTreeState:"clean", BuildDate:"2017-01-12T02:14:29Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
aws

- **OS** (e.g. from /etc/os-release):
 Ubuntu 16.04

- **Kernel** (e.g. `uname -a`):
Linux ip-10-50-193-54 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**:
- **Others**:

**What happened**:
Tried to exec:
    `kubectl --context=dev -n my-ns exec my-pod-1014340268-qiosj -- ls`. 

Got back:
    `Error from server: an error on the server ("") has prevented the request from succeeding`

apiserver logs:
```
E0127 17:20:30.471614       6 apiserver.go:253] recover from panic situation: - runtime error: invalid memory address or nil pointer dereference
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:206
    /usr/local/go/src/runtime/asm_amd64.s:472
    /usr/local/go/src/runtime/panic.go:443
    /usr/local/go/src/runtime/panic.go:62
    /usr/local/go/src/runtime/sigpanic_unix.go:24
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/admission/exec/admission.go:123
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/admission/exec/admission.go:102
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/admission/chain.go:53
    <autogenerated>:12
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:203
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:101
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:272
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120
    /usr/local/go/src/net/http/server.go:1618
    /usr/local/go/src/net/http/server.go:1910
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:476
    /usr/local/go/src/net/http/server.go:1618
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handler_impersonation.go:44
    /usr/local/go/src/net/http/server.go:1618
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/auth/handlers/handlers.go:70
    /usr/local/go/src/net/http/server.go:1618
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101
    /usr/local/go/src/net/http/server.go:1618
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101
    /usr/local/go/src/net/http/server.go:1618
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:161
    /usr/local/go/src/net/http/server.go:1618
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:187
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:113
    /usr/local/go/src/net/http/server.go:1618
    /usr/local/go/src/net/http/server.go:2081
    /usr/local/go/src/net/http/server.go:1472
    /usr/local/go/src/runtime/asm_amd64.s:1998
```

It only seems to happen on this one pod - other pods are fine.

**What you expected to happen**:

`exec` should succeed or at least give a sensible error message.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by jsravn** [comment]
There are no errors on the node with the pod. I also tried kubectl v1.4.8 and same problem.

**Comment by ncdc** [comment]
It looks like your pod that's having the issue has a container with a security context, but privileged appears to be nil. Can you confirm that is the case?

**Comment by jsravn** [comment]
@ncdc Yep that's it. It seems when securityContext is specified without listing privileged, it isn't set correctly to its default of false.

e.g. the pod yaml has:

```
containers:
- securityContext:
    capabilities:
      add:
      - NET_ADMIN
```

Explicitly adding `privileged: false` allows exec to succeed.

**Comment by smarterclayton** [comment]
Ah, this was caused by the kubelet using versioned APIs - @caesarxuchao for his awareness.  Basically any code that depends on nil pointers being set is vulnerable.
