### ISSUE TITLE
SysctlUnsupported

### ISSUE THREAD

**Issue by justinwp** [kubernetes/kubernetes#40627]
**BUG REPORT**

**Kubernetes version** (use `kubectl version`): 1.4.7

**Environment**:
- **Cloud provider or hardware configuration**: Google GKE
- **OS** (e.g. from /etc/os-release):
```
BUILD_ID=8872.47.0
NAME="Container-VM Image"
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=55
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Google Container-VM Image"
VERSION=55
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=gci
```
- **Kernel** (e.g. `uname -a`): 
```
Linux 4.4.21+ #1 SMP Thu Nov 10 21:43:53 PST 2016 x86_64 Intel(
R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
```

- **Install tools**:
- **Others**: 

**What happened**:
I was experimenting with sysctl annotations for ip local port range tuning. I updated the pod metadata through a deployment file. The yaml file validated alright but the sysctl was not supported. Instead of failing on a few pods, thousands of pods were created bringing everything down with it. I had to manually delete the failed pods after updating the spec.

<img width="568" alt="screenshot 2017-01-27 14 10 07" src="https://cloud.githubusercontent.com/assets/3392975/22388087/046f288c-e49c-11e6-934b-3857b9ef8d1d.png">

**What you expected to happen**:
The `SysctlUnsupported` error should not have continually made new pods when others had failed.

**How to reproduce it** (as minimally and precisely as possible):
Use sysctl annotations in a deployment file on a container where it is not supported.

**Anything else do we need to know**:

**Comment by justinwp** [comment]
I deleted the offending replication set and manually deleted the thousands of pods with kubectl.

**Comment by cmluciano** [comment]
cc/ @kubernetes/sig-node-misc

**Comment by yujuhong** [comment]
kubelet "rejects" the pod if sysctl is not supported, and that prompts the replicaset to create more pods.

Another option is to keep the pod pending but not reject it, similar to what kubelet does for apparmor pods.
