### ISSUE TITLE
Cross build script fails on OSX b/c of bad chown args

### ISSUE THREAD

**Issue by xrl** [kubernetes/kubernetes#40629]
**What keywords did you search in Kubernetes issues before filing this one?**: `chown` `build`

**BUG REPORT**

**Kubernetes version** (use `kubectl version`): not relevant to build process

**Environment**: OS X
- **Cloud provider or hardware configuration**: Not relevant
- **OS** (e.g. from /etc/os-release): OS X 10.11.6
- **Kernel** (e.g. `uname -a`): 
- **Install tools**:
- **Others**:

**What happened**: I updated my topic branch against master and issued the cross build commands, it was crashing due to a fault in the `build/common.sh` code related to chown'ing a directory tree.

**What you expected to happen**: Build should have kept going.

**How to reproduce it** (as minimally and precisely as possible):

```
# run.sh updated to set -x
kubernetes xlange$ bash build/run.sh make cross KUBE_FASTBUILD=true ARCH=amd64
+ kube::build::build_image
+ mkdir -p /Users/xlange/code/viasat/workspace/src/k8s.io/kubernetes/_output/images/kube-build:build-d72aef8ab7-4-v1.7.4-1
+ chown -R '1234:3456' 
bad args, exit non-zero
```

**Anything else do we need to know**:

I fixed this with this small diff:

```
$ git diff build/common.sh
diff --git a/build/common.sh b/build/common.sh
index 3fac6f3..08afb8f 100755
--- a/build/common.sh
+++ b/build/common.sh
@@ -19,8 +19,10 @@ set -o errexit
 set -o nounset
 set -o pipefail

-USER_ID=$(id -u)
-GROUP_ID=$(id -g)
+set -x
+
+USER_ID=$(whoami)
+GROUP_ID=$(id -gn)

 DOCKER_OPTS=${DOCKER_OPTS:-""}
 DOCKER=(docker ${DOCKER_OPTS})
@@ -411,7 +413,7 @@ function kube::build::clean() {
 function kube::build::build_image() {
   mkdir -p "${LOCAL_OUTPUT_BUILD_CONTEXT}"
   # Make sure the context directory owned by the right user for syncing sources to container.
-  chown -R ${USER_ID}.${GROUP_ID} "${LOCAL_OUTPUT_BUILD_CONTEXT}"
+  chown -R "${USER_ID}":"${GROUP_ID}" "${LOCAL_OUTPUT_BUILD_CONTEXT}"
```

but I don't know if that will be compatible with other shell environments.

**Comment by fraenkel** [comment]
already merged https://github.com/kubernetes/kubernetes/pull/40554
