### ISSUE TITLE
Ignore 'PullNever' policy for image locality priority. 

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#40639]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug

**Kubernetes version** (use `kubectl version`):
master

**Description**:
There's three different image pull policy here: Never, Always, PullIfNotPresent; the image locality should only consider the containers with PullIfNotPresent policy, there's no different for the other two policy in different node.

**Comment by liggitt** [comment]
a pull is still much cheaper if the image already exists on the node. It consists of contacting the registry, pulling the manifest, and making sure all layers exist locally

**Comment by liggitt** [comment]
And in the pull never case, wouldn't you want to be steered toward a node that already had the image and would succeed?

**Comment by k82cn** [comment]
>a pull is still much cheaper if the image already exists on the node. It consists of contacting the registry, pulling the manifest, and making sure all layers exist locally
Agree; how about an estimation of those manifest? As "big" image may give "incorrect" priority.

>And in the pull never case, wouldn't you want to be steered toward a node that already had the image and would succeed?
Admin should pre-pull necessary images if `never`; image locality did not guarantee the image.

**Comment by liggitt** [comment]
> Agree; how about an estimation of those manifest? As "big" image may give "incorrect" priority.

Image locality comes with a lot of caveats, so these cases don't bother me:
* steer toward a node that had a version of an image over one that didn't (worst case, the node has to re-pull and it is no worse than the node that didn't have the image)
* steer toward a node that had a bigger version of an image over one that has a smaller one (worst case, the node with the bigger image is out of date and has to re-pull the smaller one, which is better than the alternative)

> Admin should pre-pull necessary images if never; image locality did not guarantee the image.

I could maybe buy excluding PullNever from locality weight. @davidopp, your thoughts?

**Comment by k82cn** [comment]
>Image locality comes with a lot of caveats, so these cases don't bother me:
>  *  steer toward a node that had a version of an image over one that didn't (worst case, the node has to re-pull and it is no worse than the node that didn't have the image)
> *   steer toward a node that had a bigger version of an image over one that has a smaller one (worst case, the node with the bigger image is out of date and has to re-pull the smaller one, which is better than the alternative)

regarding the "big", this's the case in my mind: node1 with `image_500m`, node2 with `image_2g`, and a pod with two container:

``` yaml
containers:
- image: image_500m
  policy: pullIfNotPresent
- image: image_2g
  policy: always
```

node1 is better than node2 to me; but it did not consider other factor, e.g. re-used layer of image. I'm also ok to keep current behavior for `Always`, as it's too complex to get exact decision by considering all factors.

**Comment by liggitt** [comment]
in your scenario, does node1 also have image_2g?

**Comment by k82cn** [comment]
nop, node1 only have `image_500m`.

**Comment by liggitt** [comment]
So if image_2g hasn't changed, node2 will be better. If it has, node1 will be better. In the abstract, without more information about how likely image_2g is to change, the system can't reason about which is more likely. 

In many cases, by the time you get to the pod level, pod specs refer to particular image ids, which means that if a node has the image pulled, even a pullalways will consist solely of a registry manifest check.

**Comment by k82cn** [comment]
> So if image_2g hasn't changed, node2 will be better. If it has, node1 will be better. In the abstract, without more information about how likely image_2g is to change, the system can't reason about which is more likely.

Agree, I'm OK to keep current behavior for `Always` (include `Always` for image locality).

**Comment by k82cn** [comment]
> I could maybe buy excluding PullNever from locality weight. @davidopp, your thoughts?

On the same page with you about this policy :)

/cc @davidopp / @wojtek-t , any suggestion?

**Comment by timothysc** [comment]
going back to the original statement: 

> There's three different image pull policy here: Never, Always, PullIfNotPresent; the image locality should only consider the containers with PullIfNotPresent policy, there's no different for the other two policy in different node.

We can't really make suppositions on Never imo, it still needs to be weighted.

**Comment by k82cn** [comment]
> We can't really make suppositions on Never imo, it still needs to be weighted.

If `Never`, kubelet does not pull images; so images's size should not include.
**But** after re-thinking it today, there's no impact on including it or not; because images should be there in all related nodes for `Never`.

I'm going to close it if no more comments.

/cc @liggitt  for the conclusion :).
