### ISSUE TITLE
Unable to delete stale objects with `kubectl apply --prune` when no object passed in.

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#40635]
**What keywords did you search in Kubernetes issues before filing this one?** kubectl apply prune

---

**Is this a BUG REPORT or FEATURE REQUEST?** (FEATURE REQUEST):

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.3823+8444d47627df7d-dirty", GitCommit:"8444d47627df7d120c1641a3fe841480e10cb766", GitTreeState:"dirty", BuildDate:"2017-01-25T01:02:18Z", GoVersion:"go1.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.4057+b3f9be4656fe35-dirty", GitCommit:"b3f9be4656fe35642ea26271476cf79a349008e1", GitTreeState:"dirty", BuildDate:"2017-01-27T17:01:55Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:

I created a bunch of objects with:
```
kubectl apply -f /objects/folder -l test=true
```
I then deleted one of the yaml files in /objects/folder and execute below:
```
$ kubectl apply -f /objects/folder -l test=true --prune
...
pod "jessie2" pruned
...
```
The corresponding object is pruned as expected.
I continue to delete all yaml files in /objects/folder and execute the same command again:
```
$ kubectl apply -f /objects/folder -l test=true --prune
error: no objects passed to apply
```
`kubectl apply --prune` is unable to remove the corresponding objects from the delete files.

**What you expected to happen**:

`kubectl apply --prune` would be able to remove the corresponding objects when all yaml files are deleted.

**How to reproduce it**:

Please see "What happened section" above.

**Comment by MrHohn** [comment]
cc @ymqytw @kubernetes/sig-cli-misc

**Comment by ymqytw** [comment]
Original discussion in PR https://github.com/kubernetes/kubernetes/pull/33075

**Comment by calebamiles** [comment]
Is there someone from @kubernetes/sig-cli-bugs that can help triage this issue and own it? Thanks!


**cc: @mikedanese, @errordeveloper, @lukemarsden**

**Comment by ymqytw** [comment]
cc: @pwittrock @liggitt 
What is the expected behavior?
Should we delete all the resources that matching the labels, even though 0 files passed in (with `-f`) match the labels?

**Comment by liggitt** [comment]
`apply --prune` globally searches for all existing resources and deletes them if they don't exist in the referenced files? that seems really easy to fat-finger a huge deletion.

**Comment by MrHohn** [comment]
I think a sane semantic may be "delete objects that don't exist in this path, but were created by the same user before using `kubectl apply` in the same path".

**Comment by liggitt** [comment]
the creating user is not stored in the API, so that data is not available to make decisions based on. I'm not sure what you mean by "in the same path"

**Comment by MrHohn** [comment]
Yeah that data is not available on apiserver. By "in the same path" I mean this user is manipulating the same set of files --- objects created by `kubectl apply -f /objects/folder` will only be pruned by `kubectl apply -f /objects/folder --prune` if the referenced files are deleted, but not by `kubectl apply -f /other/folder --prune`.

BTW [#33075/comment](https://github.com/kubernetes/kubernetes/pull/35220#issuecomment-255231265) maybe relevant.

**Comment by ymqytw** [comment]
@calebamiles We are not going to fix this in 1.6. We will do that in 1.7
cc: @pwittrock

**Comment by RochesterinNYC** [comment]
Bumping that this issue is one we're interested in. Use case is in https://github.com/kubernetes/kubernetes/issues/57916

**Comment by iahmad-khan** [comment]
Same issue , k8s version 1.12 , client 1.13

the resources matching the label are still there and prune doesnt work.
