### ISSUE TITLE
Node was not removed after failing to respond to checkins for 30mins

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#40649]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

`eviction`, `node eviction`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release): Centos7
- **Kernel** (e.g. `uname -a`): 3.10.0-514.6.1.el7.x86_64
- **Install tools**: Custom, partially self-hosted (control plane only)
- **Others**:

**What happened**:

The node had a hardware issue last night which caused it to placed in a bad state. The kubelet itself was not reachable and events for context deadlines started to pile up for the given worker; however, the worker was never taken out of ready status or drained. 

I have all the default settings for node eviction. 

```
Events:
operation timeout: context deadline exceeded
kubelet worker-00
-
11
2017-01-28T14:31 UTC
2017-01-28T15:01 UTC
```

**What you expected to happen**:

I expected the node to be taken out of ready status and the pods automatically moved to another node in the cluster.

**Comment by calebamiles** [comment]
Could someone from @kubernetes/sig-api-machinery-misc or @kubernetes/sig-node-bugs help triage? Thanks!

**Comment by resouer** [comment]
> The kubelet itself was not reachable and events for context deadlines started to pile up for the given worker

It seems in your case, `kubelet` process is still alive and can reach `kube-apiserver`?  But where reported `operation timeout: context deadline exceeded`? Do you mean `kubectl events` failed?

**Comment by jhorwit2** [comment]
Something in the control plane could not talk to the kubelet (still learning the flow of things), so commands like drain would not work nor could i stop pods on that node. Events started coming in that the node was timing out (the code snippet is a copy paste of the event from the dashboard).
