### ISSUE TITLE
Making kubernetes interface  with contianerd

### ISSUE THREAD

**Issue by whatdhack** [kubernetes/kubernetes#40654]
As far as I understand kubernetes currently interfaces with docker daemon.   It would be good to have it interface with containerd  also .

**Comment by calebamiles** [comment]
Hello @whatdhack! There is a containerd presentation scheduled for the SIG Node meeting [on 31 January 2017](https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit#heading=h.fvqk1u6udxl7) at 10am PST. Any containerd integration would likely be developed with the aid of developers in [SIG Node](https://github.com/kubernetes/community/blob/master/sig-node/README.md). Please join in the discussion in the [SIG Node mailing list](https://groups.google.com/forum/#!topic/kubernetes-sig-node/i7qco_LsXPk); closing this issue in favor of discussion there.

**Comment by whatdhack** [comment]
That is great.  Thanks. What is the definite source for date , time , and connection for SIG Node Meeting ? The  Sig-Node Weekly Meeting Notes ( https://plus.google.com/hangouts/_/google.com/sig-node-meetup ) ?
