### ISSUE TITLE
Deep copy function for unstructured.Unstructured

### ISSUE THREAD

**Issue by ash2k** [kubernetes/kubernetes#40657]
I'm writing a controller that needs to work with objects that have a field of `unstructured.Unstructured` type. It gets those objects from `cache.Store` and I need to make a copy of the object before modifications can be made so a deep copy function for `unstructured.Unstructured` would be very useful. Other deep copy functions I need already exist.

**Comment by calebamiles** [comment]
Could someone from @kubernetes/sig-api-machinery-misc help routing this feature request to an appropriate SIG? @ash2k, have you discussed your request with any [Kubernetes SIGs](https://github.com/kubernetes/community/blob/master/README.md#special-interest-groups-sig)? I'm guessing that [API Machinery](https://github.com/kubernetes/community/blob/master/sig-api-machinery/README.md) might be the right place to ask for direction. Thanks for submitting the feature request!

**Comment by sttts** [comment]
@ash2k please check my branch. Is it what you need?

**Comment by ash2k** [comment]
@sttts Yes, thanks!

**Comment by ash2k** [comment]
This has been implemented as part of #48544. Thanks!
