### ISSUE TITLE
Kubemark-scale continuously failing

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#40670]
kubemark-gce-scale test is failing for quite some runs now, mostly due to density and load test unable to handle scale. Here's what happens:

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/density.go:335
There should be no high-latency requests
Expected
    <int>: 1
not to be >
    <int>: 0
```

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/load.go:84
Expected
    <int>: 1
not to be >
    <int>: 0
```

cc @kubernetes/sig-scalability-misc @wojtek-t @gmarek

**Comment by wojtek-t** [comment]
This is a known issue. And we understand it.

**Comment by shyamjvs** [comment]
I'm sorry. I wrongly interpreted this [comment](https://github.com/kubernetes/kubernetes/issues/39245#issuecomment-274415979) about starting a new issue:)
