### ISSUE TITLE
Azure Update Domain ID visible as k8s node labels

### ISSUE THREAD

**Issue by djsly** [kubernetes/kubernetes#40684]
**FEATURE REQUEST**

Description:

When provisioning k8s nodes in Azure using the `--cloud-provider` flag, we seem to be getting the following labels
```
Labels:            beta.kubernetes.io/arch=amd64
            beta.kubernetes.io/instance-type=Standard_D5_v2
            beta.kubernetes.io/os=linux
            failure-domain.beta.kubernetes.io/region=westus
            failure-domain.beta.kubernetes.io/zone=2
```
We would also need to have the `update-domain` label to allow a better node selection at the application layer. Since the Availability Set covers all of the k8s nodes (or a subset based on hardware differences) the scheduler could in theory schedule pods on the same update domain within the same node pool. While having the scheduler aware of the failure-domain and update-domain would be awesome, we think that on the short term we could use Node Affinity Logic in our application's manifest to leverage the information present as labels. 

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): centOS 7.3
- **Install tools**: InHouse (salt based)

CC:
@colemickens 
@Seb-Solon

**Comment by jdumars** [comment]
Bringing this to SIG-Azure meeting to verify if it is still relevant.

**Comment by djsly** [comment]
Currently we have the luxury of managing the kubelet.service file ourselves, so we augmented it with a ExecPost logic. While this is working right now, an official solution would be preferable as this auto label creation logic did caused us a few issue in the past. 

*kubelet.service*
`ExecStartPost=/etc/kubernetes/azure-label-creator.sh`

*azure-label-creator.sh*
```
#!/bin/bash

{% set http_proxy = salt.pillar.get('kubernetes:kube-system:http_proxy','') -%}
{% if http_proxy != '' -%}
HTTP_PROXY='{{ http_proxy }}'
HTTPS_PROXY='{{ http_proxy }}'
{% set no_proxy = salt.pillar.get('kubernetes:kube-system:no_proxy')|join(",")~",."~salt.cmd.run('dnsdomainname') -%}
NO_PROXY='{{ no_proxy }}'
{% endif -%}

for i in {1..5}
do
   UD=$(curl -s http://169.254.169.254/metadata/v1/InstanceInfo | python -c "import sys, json; print json.load(sys.stdin)['UD']" 2>/dev/null)
   re='^[0-9]+$'
   if ! [[ $UD =~ $re ]] ; then
      echo "error: ($UD) Not a number; retrying" >&2;
      sleep 1
   else
      break
   fi
done

re='^[0-9]+$'
if ! [[ $UD =~ $re ]] ; then
   echo "error: ($UD) Not a number" >&2; exit 1
else
   echo "Update domain was extracted: $UD"
fi

COUNTER=0
MAX_ATTEMPTS=7
node=`hostname -s`
until `kubectl --kubeconfig=/root/.kube/config get node $node 1>&2`; do
   if [ $COUNTER -gt $MAX_ATTEMPTS ]; then
      echo "error: timeout waiting for $node to register"; exit 2
   fi
   sleep $((2**COUNTER + (RANDOM % 10)))
   let COUNTER=COUNTER+1
done
kubectl --kubeconfig=/root/.kube/config label node `hostname -s` cloud.azure.beta.kubernetes.io/ud=$UD --overwrite=true

```

**Comment by khenidak** [comment]
This has stalled for a year now. @jdumars Can we close if we don't have a use case?

@djsly Kubernetes scheduler does not recognize FD/UD, it only understand zones. let us say you have Availability Set (or VMSS) deployed on Azure as agent pool what you will end up is something like this (if you used ud = 5)

node 1: fd1 ud1
node 2: fd2 ud2
node 3: fd3 ud3
node 4: fd1 ud4 
node 5: fd2 ud5
node 6: fd3 ud1
node 7: fd1 ud2
node 8: fd2 ud3
node 9: fd3 ud4
node 10: fd1 ud5

deploying a 3 replicas pod will land it on different FDs. Which will achieve high availability. If you want the highest availability then you will need to go for 5 replica pod

**Comment by djsly** [comment]
You model works as long as you have less then 15 nodes. After that the FD/UD pair starts repeating and you start having risk of having the same FD/UD pair running you X replicas. 
Your 5 replicas could end up on 5 nodes with the same UD.

Node 1: fd1 ud1
Node 11: fd2 ud1
Node 6: fd3 ud1
Node 16: fd1 ud1
Node 21: fd3 ud1

Another Meltdown maintenance window would have brought down all 5 replicas.

We use pod affinity / anti-affinity to augment the scheduler logic based on the UD/FD. the Fd (e.g. zone) is available but the UD isn't. 

So we have to populate it ourselves to ensure that our pods are getting assigned a node that favors a different FD/UD combos in a large cluster.

**Comment by justaugustus** [comment]
@djsly @khenidak -- is this still an active issue?

**Comment by djsly** [comment]
The information should definitely be reported to the scheduler to consume. @brendandburns what is your take on this issue ?

**Comment by justaugustus** [comment]
What's the status of this?
/assign @feiskyer
/kind feature
/lifecycle frozen

**Comment by feiskyer** [comment]
It seems there's no clear use case for update domain. Let's close this issue.

We are working on availability zones support, which is scheduler aware. 

@djsly Please reopen it if you have strong use cases which availability zones doesn't meet.

/close
