### ISSUE TITLE
Azure VM's Tags should be synch as k8s node labels

### ISSUE THREAD

**Issue by djsly** [kubernetes/kubernetes#40686]
**FEATURE REQUEST**

Description:

When provisioning k8s nodes in Azure using the --cloud-provider flag, we seem to be getting the following labels

```
Labels:            beta.kubernetes.io/arch=amd64
            beta.kubernetes.io/instance-type=Standard_D5_v2
            beta.kubernetes.io/os=linux
            failure-domain.beta.kubernetes.io/region=westus
            failure-domain.beta.kubernetes.io/zone=2
```

Since Azure has its own labeling concept at the VM level, called TAGS. It would make sense to have those visible as k8s node labels as well. This would allow the different application to properly use the Azure Tags defined by the Cluster Administrator to assigned their service on specific nodes. 

**Environment:**

*Cloud provider or hardware configuration*: Azure
*OS (e.g. from /etc/os-release)*: centOS 7.3
*Install tools*: InHouse (salt based)

CC:
@colemickens
@Seb-Solon

**Comment by jdumars** [comment]
Bringing this to SIG-Azure meeting to verify if it is still relevant.

**Comment by khenidak** [comment]
This has been stalling for a year now. 

@djsly can we have a use case for this? or else let us put a low pri on it?

**Comment by djsly** [comment]
One Use Case

We have different node pool type in our k8s cluster, We tag the VM in Azure with different metadata. e.g. SSD / tenantID / etc

Those tags are used by billing and the team in charge of breaking down the cost across tenants and other dimensions and we also need to redo the same mapping at the Kubernetes level to enable proper node selectors in our manifest based on Node Labels.

**Comment by djsly** [comment]
@brendandburns seeing that https://github.com/kubernetes/kubernetes/pull/42142 is now closed, do you see any potential way of having this done in either the cloud-provider code ?

**Comment by djsly** [comment]
sorry, I miss used the word `tenantID`. I was referring to the tentant part in multi-tenant. :)

e.g. client1 label for nodes 1 to 10, client2 label for nodes 11-30, etc.  node assignment per users. 

Also, another use case would be the agent pool name.  We create different agent pools with different characteristics. So when we create the agent pools, we can set labels to define their intended usage. 

e.g.: binpack nodes, spreadout nodes, etc which allows us to defined the way pods should be scheduled on them.

**Comment by khenidak** [comment]
But you can do that using your own controls, scripts. The cloud provider is mainly to abstract ARM/Azure specific logic. For this use case i would advise that you byol `bring your own label and label maker`

**Comment by djsly** [comment]
if you guys think that is out of scope. I'm fine with closing this.  

Having to manage a separate process to duplicate the metadata that is configurable at the azure level to make sure that the scheduler is aware sounds like something we should have out of the box.
