### ISSUE TITLE
Setup the infrastructure for integration tests in federation.

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#40705]
Unit tests cannot cover the entire breadth and depth of a feature and hence give limited signals about certain features. While end-to-end tests can test features as a whole, they are both expensive to write and debug and expensive to run them in CI. 

Integration tests help us strike a balance between these two types of tests in many cases. The reason why we haven't written integration tests in federation is due to the lack of infrastructure to write these tests. We need to build the infrastructure to encourage people to write integration tests.

cc @kubernetes/sig-federation-feature-requests @nikhiljindal @shashidharatd

**Comment by nikhiljindal** [comment]
For reference, we do have a federation-apiserver integration test: https://github.com/kubernetes/kubernetes/tree/master/test/integration/federation.
We use it to test which API group versions are enabled.

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by nikhiljindal** [comment]
With https://github.com/kubernetes/kubernetes/issues/42278, we now have a text fixture for federation-apiserver.
https://github.com/kubernetes/kubernetes/pull/42025 is an example PR using that fixture for writing integration tests for secrets.

**Comment by madhusudancs** [comment]
@nikhiljindal that means the issue can be closed? The issue is about setting up the infrastructure which seems to be done.

cc @marun

**Comment by marun** [comment]
@madhusudancs #42278 only added a fixture for the api.  #42025 adds a fixture for a federation - the api and member clusters.  I'm not sure it made sense to close this issue in advance of that merging.

**Comment by madhusudancs** [comment]
@marun Alright, reopening the issue.

**Comment by madhusudancs** [comment]
yAy! Thanks!
