### ISSUE TITLE
Find docker pid correctly for all compatible docker versions

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#40717]
Forked from #39667 

In some settings, kubelet gets the pid of docker and make sure it's moved to the right cgroup. From docker 1.12+, the process name changed from `docker` to `dockerd`. We should be able to handle both names since kubernetes supports docker 1.10-1.12.

/cc @kubernetes/sig-node-bugs

**Comment by feiskyer** [comment]
Is it ok to set `dockerProcessName = "dockerd?"`?

**Comment by yujuhong** [comment]
> Is it ok to set dockerProcessName = "dockerd?"?

No, as I said in the post, we should be able to handle both names.

**Comment by sysradium** [comment]
Well, why does not the `dockerd?` handle both? It does a regexp search underneath anyway ...

**Comment by yujuhong** [comment]
> Well, why does not the dockerd? handle both? It does a regexp search underneath anyway ...

Sorry didn't notice that you changed the PR. I'll comment on the PR soon.
