### ISSUE TITLE
Finalizers do nothing for TPR instances

### ISSUE THREAD

**Issue by ash2k** [kubernetes/kubernetes#40715]
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T07:30:54Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
minikube version: v0.15.0
- **OS** (e.g. from /etc/os-release):
macOS 10.12.3
- **Kernel** (e.g. `uname -a`):
Darwin CLI-1831 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

**What happened**:
Instance of a TPR is deleted even though it has a non-empty "finalizers" field.
Finalizers appear to work for TPRs themselves.

**What you expected to happen**:
Object is not deleted but `deletionTimestamp` is set on it.

**How to reproduce it** (as minimally and precisely as possible):
1. Create a TPR
2. Create an instance of it with non-empty "finalizers" field (might be hard to do via kubectl because of #40119). Use API directly.
3. Delete the instance.

**Anything else do we need to know**:
You may install minikube and clone https://github.com/atlassian/smith finalizers branch. Then run "make minikube-test" to create a "Template" object that will have a finalizer set.

```
$ kubectl get templates template1 -o yaml
apiVersion: smith.atlassian.com/v1
kind: Template
metadata:
  creationTimestamp: 2017-01-30T22:41:22Z
  finalizers:
  - smith.atlassian.com/cleanup
  name: template1
  namespace: default
  resourceVersion: "426352"
  selfLink: /apis/smith.atlassian.com/v1/namespaces/default/templates/template1
  uid: 3962e6ac-e73d-11e6-baf3-ee8d75af8f6e
spec:
  ...
status:
  ...
$ kubectl delete templates template1
template "template1" deleted
$ kubectl get templates template1 -o yaml
Error from server (NotFound): thirdpartyresourcedatas.extensions "template1" not found
```

**Comment by ash2k** [comment]
cc @kubernetes/sig-api-machinery-misc

**Comment by ash2k** [comment]
Same behaviour on 1.6.3 server and 1.6.4 kubectl.

**Comment by enisoc** [comment]
Finalizers are supported on Custom Resources, which are the new version of TPR. Users should migrate to Custom Resource, as TPR is deprecated.
