### ISSUE TITLE
openstack-heat: salt-minion errors because it is started as daemon

### ISSUE THREAD

**Issue by micmro** [kubernetes/kubernetes#40721]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
`openstack`, `Error while bringing up minion` and a few others

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
`v1.5.2`

**Environment**:
- **Cloud provider or hardware configuration**: `OpenStack`
- **OS** (e.g. from /etc/os-release): CentOS
- **Kernel** (e.g. `uname -a`): `Linux kube-stack-master 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**: `openstack-heat` provider

**What happened**:
The _openstack-heat_ provider only installs _salt-minions_, no _salt-master_. The configuration does not take this into account which causes the following issues:

- the _salt minion_ is not able to DNS resolve `salt` (see fist part of error log below)
- the _salt-minion_ is daemonized and fails finding the master (second part of error log below). From my understanding is not required when there is no salt-master, as the setup uses `salt-call` 
anyway (see [gce provider](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/configure-vm.sh#L328-L339) as reference).

```
Jan 31 03:00:04 kube-stack-master salt-minion[9795]: [ERROR   ] DNS lookup of 'salt' failed.
Jan 31 03:00:04 kube-stack-master salt-minion[9795]: [ERROR   ] Master hostname: 'salt' not found. Retrying in 30 seconds
...
Jan 31 02:35:30 kube-stack-master salt-minion[9690]: [ERROR   ] Error while bringing up minion for multi-master. Is master at salt responding?
```

**What you expected to happen**:
Either `salt-minion` should not be daemonized or it should be able to find a master (internally or externally).

Both issues can be solved by adding the non-deamon install flag `-X` in `run-salt.sh`.

The DNS lookup error alone can be fixed by providing a `/etc/salt/minion.d/local.conf` as describer in the [salt-docs](https://docs.saltstack.com/en/latest/topics/tutorials/quickstart.html). 

Will create PR

**How to reproduce it** (as minimally and precisely as possible):
Just use the provider in the standard way:
`KUBERNETES_PROVIDER=openstack-heat ./cluster/kube-up.sh`

**Comment by micmro** [comment]
I'll create a separate PR for the docs if this is correct and #40721 is merged, to reflect that _openstack-heat_ is stand-alone as well.

**Comment by xsgordon** [comment]
/cc @k8s-sig-openstack-bugs 

@idvoretskyi can you add the sig/openstack label please?
