### ISSUE TITLE
Kubernetes components should export metrics in Prometheus format

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#40736]
As agreed in [Kubernetes monitoring architecture](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/monitoring_architecture.md) each Kubernetes component should export its metrics using Prometheus format. The metrics should follow [Instrumentation best practises](https://github.com/kubernetes/community/blob/master/contributors/devel/instrumentation.md).

The list of components:
- [x] api server
- [x] scheduler
- [x] controller manager
- [x] l7-lb-controller https://github.com/kubernetes/ingress/pull/346
- [x] etcd
- [x] cluster autoscaler
- [x] rescheduler https://github.com/kubernetes/contrib/pull/2420
- [x] kubelet
- [x] kube-proxy #42104
- [x] addons
  - [x] dns
  - [x] dashboard
  - [x] heapster
  - [x] l7-default-backend (issue https://github.com/kubernetes/ingress/issues/237)
  - [x] fluentd #41567

**Comment by piosz** [comment]
cc @fabxc @brancz @Crassirostris @fgrzadkowski

**Comment by brancz** [comment]
Not sure about all components and when we should tick them off, but etcd v3 already does exposes them in the way the best practices describe. For the other components we should do some auditing of the existing code base, I know @fabxc already went through a substantial amount of code so might have a good overview of this already.

**Comment by piosz** [comment]
Yeah, probably the majority of components have the handler already. This issue is about identifying those without and extending them.

**Comment by piosz** [comment]
@bprashanth @bowei do kube-proxy, dns, l7-lb-controller and l7-default-backend export metrics in Prometheus format?

**Comment by piosz** [comment]
@bryk does kubernetes dashboard export metrics in Prometheus format?

**Comment by kargakis** [comment]
[Last time](https://github.com/kubernetes/kubernetes/pull/38714#issuecomment-271241712) I was trying to add a new metric to the controller manager, I had no idea where were those metrics exposed. Any pointers would be really appreciated.

**Comment by brancz** [comment]
kube-dns was quite a mess regarding the exposed metrics, however @bowei already did most of the work on improving that. What's confusing is that skydns (vendored by kube-dns) allows exposing metrics but only by having a the `PROMETHEUS_PORT` env variable set and those are not exactly under our control, regarding the instrumentation best practices.

**Comment by piosz** [comment]
@kargakis I can access them by `curl localhost:10252/metrics`.

@brancz thanks for letting me know! I marking DNS as already supported

**Comment by piosz** [comment]
@thockin @kubernetes/sig-network-misc do we expose Prometheus metrics for:
- kube-proxy
- l7-lb-controller
- l7-default-backend

**Comment by cmluciano** [comment]
[Kube proxy metrics issue](https://github.com/kubernetes/kubernetes/issues/9125)

**Comment by smarterclayton** [comment]
Expectation was that all 3 of these *should* expose metrics.

**Comment by bprashanth** [comment]
kube-proxy metrics https://github.com/kubernetes/kubernetes/issues/9125

L7-lb-controller metrics https://github.com/kubernetes/ingress/issues/238, they're per backend currently, the nginx contoller does expose metrics (https://github.com/kubernetes/ingress/pull/36), the gce controller doesn't. 

default-backend: https://github.com/kubernetes/ingress/issues/237

**Comment by piosz** [comment]
All components have appropriate metrics right now.
