### ISSUE TITLE
CRI: test-e2e-node assumes docker

### ISSUE THREAD

**Issue by runcom** [kubernetes/kubernetes#40739]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

both maybe

**Kubernetes version** (use `kubectl version`):

latest master

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

running `make test-e2e-node` assumes docker and starts by pulling images with docker even when the kubelet is configured to use CRI.

**What you expected to happen**:

pre-pull images using the CRI PullImage API directly (or using a knob in the CLI)

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

@mrunalp @feiskyer @jjlakis @vishh

**Comment by pskrzyns** [comment]
cc @Random-Liu

**Comment by yujuhong** [comment]
We don't have code to pre-pull images using CRI runtimes yet. Before we add that, @runcom, you could disable image pre-pulling in the node e2e suite.

**Comment by runcom** [comment]
@yujuhong I can add that code as well using the grpc client we already have if that works for you

**Comment by yujuhong** [comment]
> @yujuhong I can add that code as well using the grpc client we already have if that works for you

Sure. Thanks for offering. I'll assign the issue to you.

**Comment by Random-Liu** [comment]
@runcom Thanks. Please only use grpc client when `container-runtime` is `remote` for not.

We can only use the grpc client by default when after CRI integration is rolled out as default in 1.6.

**Comment by lucab** [comment]
@runcom FYI https://github.com/kubernetes/kubernetes/pull/40525

**Comment by runcom** [comment]
@lucab great, I'll rebase my patch on top of yours to prepull images with CRI

**Comment by lucab** [comment]
@runcom ack, feel free to CC me on the PR and I can give it a run locally with rkt (so far we are running without pre-pulling).

**Comment by runcom** [comment]
closing as https://github.com/kubernetes/kubernetes/issues/40804 has been merged
