### ISSUE TITLE
[OS] Add configuration to disable minion floating IPs

### ISSUE THREAD

**Issue by ccatlett2000** [kubernetes/kubernetes#40737]
Currently, the OpenStack installation method assigns a floating IP to every single worker node. While this is fine for smaller clusters with a good sized IP pool, it can cause issues in environments with high node counts or less IPs available.

An environment variable such as `$ASSIGN_MINIONS_FLOATING_IP` could be use to configure whether or not minions are assigned an IP. It should not disable the floating IP for the master node, as most people will want to use that to communicate with the API server.

**Comment by ccatlett2000** [comment]
cc @k8s-sig-openstack-feature-requests

**Comment by xsgordon** [comment]
@idvoretskyi can you add the sig/openstack label please?

**Comment by xsgordon** [comment]
@ccatlett2000 I assume here you're referring to the openstack-heat kube-up scripts?

**Comment by ccatlett2000** [comment]
@xsgordon Correct

**Comment by dims** [comment]
looks like this was already done.

/close
