### ISSUE TITLE
[Federation][kubefed] --dns-provider should be mandatory without a default

### ISSUE THREAD

**Issue by marun** [kubernetes/kubernetes#40757]
``kubefed`` currently defaults to google dns, which might make sense if only gke/gce were supported.   Since route53 and coredns are options, though, I think it would be preferable to make ``--dns-provider`` a mandatory parameter without a default so the user is forced to choose the provider appropriate for their deployment.

cc: @kubernetes/sig-federation-bugs

**Comment by marun** [comment]
@madhusudancs I think this should be fixed for 1.6, as a precondition for kubefed going to beta.  A command's flags are its API, and ensuring backwards compatibility precludes making a previously optional parameter mandatory since it could break anyone who was previously not providing it (e.g. if a script was automating kubefed).  It's a simple enough fix, let me know what you think.

**Comment by madhusudancs** [comment]
Pasting my comments from Slack:

@marun This particular change/fix is more of a nice to have than a requirement. It is a usability improvement. It is not like things are not going to work without this.
But I agree that flags are like API.
However, beta doesn't mean things are not going to change in incompatible ways. It means, things can change and when that happens, we provide clear instructions on how to move to a new version.
So I don't think it is a requirement for beta graduation.
But having said all that, please feel free to send a PR and ping me.
the change should neither be difficult nor too much work.
I will review the PR.
Particularly given that we already know this is going to break things for people who have scripted kubefed to run Federation on GCP clusters, let's try to get this in.
