### ISSUE TITLE
Failed docker containers are recycled too quickly on the master to see the logs

### ISSUE THREAD

**Issue by jcbsmpsn** [kubernetes/kubernetes#40753]
When making a change to the command line parameters in `/etc/kubernetes/manifests/kube-apiserver.json`, if the parameters aren't just right, the kube-apiserver fails to restart.

The actual problem is that the dead container, and the associated logs, disappear very quickly, so it's difficult to see the logs. As an example, as soon as I change the manifest file to have an incorrect parameter, docker ps -a watches to see how long the container is visible. Within 15-30s, the dead container is gone.

```sh
root@k-a-master:~# while true ; do date ; docker ps -a | grep "kube-apiserver" ; sleep 10 ; done
Tue Jan 31 19:08:20 UTC 2017
81583ddcebdd        gcr.io/jacobsimpson-gke-dev/kube-apiserver-amd64@sha256:89e20ad6125357716e4aa1abc2b40b85e66ac76d59d3128024f4d39416a5692a            "kube-apiserver --v=1"   25 seconds ago       Exited (2) 2 seconds ago                              k8s_kube-apiserver.5b0f77ec_kube-apiserver-k-a-master_kube-system_ca98dd4f5fc2d57332838d5431ca6d72_0a7165aa
c19860bedfcd        gcr.io/google_containers/pause-amd64@sha256:163ac025575b775d1c0f9bf0bdd0f086883171eb475b5068e7defa4ca9e76516                        "/pause"                 26 seconds ago       Exited (0) 2 seconds ago                              k8s_POD.f932fb66_kube-apiserver-k-a-master_kube-system_ca98dd4f5fc2d57332838d5431ca6d72_9de2d588
Tue Jan 31 19:08:30 UTC 2017
81583ddcebdd        gcr.io/jacobsimpson-gke-dev/kube-apiserver-amd64@sha256:89e20ad6125357716e4aa1abc2b40b85e66ac76d59d3128024f4d39416a5692a            "kube-apiserver --v=1"   36 seconds ago       Exited (2) 12 seconds ago                        k8s_kube-apiserver.5b0f77ec_kube-apiserver-k-a-master_kube-system_ca98dd4f5fc2d57332838d5431ca6d72_0a7165aa
c19860bedfcd        gcr.io/google_containers/pause-amd64@sha256:163ac025575b775d1c0f9bf0bdd0f086883171eb475b5068e7defa4ca9e76516                        "/pause"                 37 seconds ago       Exited (0) 12 seconds ago                        k8s_POD.f932fb66_kube-apiserver-k-a-master_kube-system_ca98dd4f5fc2d57332838d5431ca6d72_9de2d588
Tue Jan 31 19:08:41 UTC 2017
81583ddcebdd        gcr.io/jacobsimpson-gke-dev/kube-apiserver-amd64@sha256:89e20ad6125357716e4aa1abc2b40b85e66ac76d59d3128024f4d39416a5692a            "kube-apiserver --v=1"   46 seconds ago      Exited (2) 22 seconds ago                         k8s_kube-apiserver.5b0f77ec_kube-apiserver-k-a-master_kube-system_ca98dd4f5fc2d57332838d5431ca6d72_0a7165aa
c19860bedfcd        gcr.io/google_containers/pause-amd64@sha256:163ac025575b775d1c0f9bf0bdd0f086883171eb475b5068e7defa4ca9e76516                        "/pause"                 47 seconds ago      Exited (0) 22 seconds ago                         k8s_POD.f932fb66_kube-apiserver-k-a-master_kube-system_ca98dd4f5fc2d57332838d5431ca6d72_9de2d588
Tue Jan 31 19:08:51 UTC 2017
81583ddcebdd        gcr.io/jacobsimpson-gke-dev/kube-apiserver-amd64@sha256:89e20ad6125357716e4aa1abc2b40b85e66ac76d59d3128024f4d39416a5692a            "kube-apiserver --v=1"   56 seconds ago      Exited (2) 32 seconds ago                         k8s_kube-apiserver.5b0f77ec_kube-apiserver-k-a-master_kube-system_ca98dd4f5fc2d57332838d5431ca6d72_0a7165aa
c19860bedfcd        gcr.io/google_containers/pause-amd64@sha256:163ac025575b775d1c0f9bf0bdd0f086883171eb475b5068e7defa4ca9e76516                        "/pause"                 57 seconds ago      Exited (0) 32 seconds ago                         k8s_POD.f932fb66_kube-apiserver-k-a-master_kube-system_ca98dd4f5fc2d57332838d5431ca6d72_9de2d588
Tue Jan 31 19:09:01 UTC 2017
Tue Jan 31 19:09:11 UTC 2017
```

The kubelet is running with these parameters:

```sh
root@k-a-master:~# ps -ef | grep "[k]ubelet"
root     26434     1  2 18:40 ?        00:00:52 /usr/bin/kubelet --kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=10.96.0.10 --cluster-domain=cluster.local
root     32281 32261  0 19:08 ?        00:00:00 kube-controller-manager --address=127.0.0.1 --leader-elect --master=127.0.0.1:8080 --cluster-name=kubernetes --root-ca-file=/etc/kubernetes/pki/ca.crt --service-account-private-key-file=/etc/kubernetes/pki/apiserver.key --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt --cluster-signing-key-file=/etc/kubernetes/pki/ca.key --insecure-experimental-approve-all-kubelet-csrs-for-group=kubeadm:kubelet-bootstrap
```

Ideally a dead container would last for at least 10-15 minutes, so it's possible to easily see the logs. The best possible scenario would be if a failed container stayed until 10-15 minutes after it successfully restarts. So, the logs of a dead apiserver would be visible as long as there is no live apiserver.

**Comment by jcbsmpsn** [comment]
cc @mikedanese

**Comment by mikedanese** [comment]
@kubernetes/sig-node-bugs

**Comment by resouer** [comment]
This is just set by kubelet `minimum-container-ttl-duration`, which by default is 1 min.

So you can see after your container exited, it will be GCed after `CREATED` >= 1min. Not `15-30s`. 

Set it to a larger value should fix your issue, see: https://kubernetes.io/docs/admin/garbage-collection/

**Comment by mikedanese** [comment]
> So you can see after your container exited, it will be GCed after CREATED >= 1min. Not 15-30s.

15-30 seconds lines up with what the bug reporter describes if the container was running for 30 seconds before exiting...

Are logs accessible after the container is deleted? 15-30 seconds seems unreasonably aggressive GC frequency on a node without disk pressure.

**Comment by vishh** [comment]
IIUC, Kubelet will remove containers of pods have been evicted or deleted from the apiserver.
By default, it is configured to not GC container at all based on [this defaulting configuration](https://github.com/kubernetes/kubernetes/blob/095f4ef6243b62ead42a26b8ad47ed9ecbdc174c/pkg/apis/componentconfig/v1alpha1/defaults.go#L283).

What version of kubelet are you running? 

@dashpole we need to update  https://kubernetes.io/docs/admin/garbage-collection/ to include eviction manager related changes [mentioned here](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/kubelet-eviction.md#deprecation-of-existing-features)

**Comment by resouer** [comment]
@vishh Aha, I didn't notice the GC doc is outdated. 

But if it's latest version of kubelet, `MaxPerPodContainer` (default to 1) should trigger GC every minute, right. That can't explain why both two exited containers are removed in this case ...
