### ISSUE TITLE
Move the cluster registration/deregistration steps out of the parallel test's from the parallel tests' BeforeEach/AfterEach blocks.

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#40768]
In order to make the tests federation e2e tests dependable and faster, we need to stop registering and deregistering clusters in each tests. At least for the parallel tests, we should move these steps out of the individual test's `BeforeEach/AfterEach` block to federation-up.sh.

This is part of an effort to make the federation e2e tests parallelizable. Issue #40765.

cc @kubernetes/sig-federation-bugs @shashidharatd

**Comment by shashidharatd** [comment]
@madhusudancs, please assign this task to me.

**Comment by madhusudancs** [comment]
@shashidharatd assigned.
