### ISSUE TITLE
Federation test flake

### ISSUE THREAD

**Issue by rkouj** [kubernetes/kubernetes#40772]
Unit/Integration test flakes

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/39883/pull-kubernetes-unit/15760/

Test Failures

k8s.io/kubernetes/federation/pkg/federation-controller/namespace TestNamespaceController 22s
go test -v k8s.io/kubernetes/federation/pkg/federation-controller/namespace -run TestNamespaceController$
0xacdf3d	k8s.io/kubernetes/federation/pkg/federation-controller/util/test.RegisterFakeWatch.func1+0x14d	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/util/test/test_helper.go:155
0x44355e	sync.runtime_notifyListWait+0x12e														/usr/local/go/src/runtime/sema.go:267
0x4da0dd	sync.(*Cond).Wait+0x8d																/usr/local/go/src/sync/cond.go:57
0x5d7add	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop+0xed									/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:407
0x5d3fd0	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*controller).processLoop+0x70								/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:128
0x5e2d51	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*controller).(k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.processLoop)-fm+0x41	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:102
0xab863f	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1+0x6f								/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:96
0xab7f2d	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil+0xbd									/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
0xab7e4a	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until+0x5a										/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
0x5d3d8e	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*controller).Run+0x24e									/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:102
0x5de2b9	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*Reflector).watchHandler+0x1689	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/reflector.go:346
0x5dbf6b	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch+0xe3b	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/reflector.go:317
0x5e35fa	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*Reflector).RunUntil.func1+0x4a	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/reflector.go:198
0xab863f	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1+0x6f	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:96
0xab7f2d	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil+0xbd		/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
0xab7e4a	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until+0x5a			/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
0x5e3aa3	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1+0x3b3	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/reflector.go:266
0x60cc1a	k8s.io/kubernetes/federation/pkg/federation-controller/util.(*DelayingDeliverer).run+0x63a	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/util/delaying_deliverer.go:122
0x6130c7	k8s.io/kubernetes/federation/pkg/federation-controller/util.(*DelayingDeliverer).StartWithHandler.func1+0x157	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/util/delaying_deliverer.go:174
0x4972ad	testing.(*T).Run+0x56d		/usr/local/go/src/testing/testing.go:647
0x49bb99	testing.RunTests.func1+0xb9	/usr/local/go/src/testing/testing.go:793
0x496cc9	testing.tRunner+0xc9		/usr/local/go/src/testing/testing.go:610
0x49868a	testing.RunTests+0x4ba		/usr/local/go/src/testing/testing.go:799
0x49785f	testing.(*M).Run+0x12f		/usr/local/go/src/testing/testing.go:743
0x401428	main.main+0x1b8			k8s.io/kubernetes/federation/pkg/federation-controller/namespace/_test/_testmain.go:54
0x430fec	runtime.main+0x18c		/usr/local/go/src/runtime/proc.go:183
0x4aac2d	k8s.io/kubernetes/federation/pkg/federation-controller/namespace.(*NamespaceController).Run.func1+0x4d	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/namespace/namespace_controller.go:264
0x5d0452	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop+0x92	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/mux.go:201
0xaab3d5	k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartEventWatcher.func1+0xc5	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:228
0xab2e5d	k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).flushDaemon+0x9d	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:879
0x612f56	k8s.io/kubernetes/federation/pkg/federation-controller/util.StartBackoffGC.func1+0x126	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/util/backoff.go:28
0x55162d	runtime/pprof.writeRuntimeProfile+0xbd								/usr/local/go/src/runtime/pprof/pprof.go:614
0x5513c9	runtime/pprof.writeGoroutine+0xc9								/usr/local/go/src/runtime/pprof/pprof.go:576
0x54cc4d	runtime/pprof.(*Profile).WriteTo+0x47d								/usr/local/go/src/runtime/pprof/pprof.go:298
0xacda56	k8s.io/kubernetes/federation/pkg/federation-controller/util/test.CheckObjectFromChan+0x2a6	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/util/test/test_helper.go:257
0x4a8031	k8s.io/kubernetes/federation/pkg/federation-controller/namespace.TestNamespaceController+0x1ae1	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/namespace/namespace_controller_test.go:140
0x496cc9	testing.tRunner+0xc9										/usr/local/go/src/testing/testing.go:610
<autogenerated>:10: 
                        
	Error Trace:	namespace_controller_test.go:140
	
	Error:		Received unexpected error "Failed to get an object from channel"
	
<autogenerated>:10: 
                        
	Error Trace:	namespace_controller_test.go:147
	
	Error:		"map[]" does not contain "A"
	from junit_5cb0d5e1ecc23f62a6096d1036d646a6611481ad_20170131-153501.xml

**Comment by quinton-hoole** [comment]
Closing old bug reports.  Please re-open if you're still seeing this issue.
