### ISSUE TITLE
Watching nodes shows activity when there isn't any

### ISSUE THREAD

**Issue by montanaflynn** [kubernetes/kubernetes#40779]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No, just a bug report.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

"watch", "nodes"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug Report

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Google container engine

**What happened**:

During an update I wanted to watch the nodes so I ran `kubectl get nodes -w` and all the nodes started being printed up even though there status had not changed.

**What you expected to happen**:

Only nodes which have changed status to be printed after the initial nodes show up.

**How to reproduce it** (as minimally and precisely as possible):

Run `kubectl get nodes -w`

**Anything else do we need to know**:

I use `kubectl get pods -w` and `kubectl get services -w` and I think nodes should behave the same way.

**Comment by yujuhong** [comment]
Node status is updated periodically (10s) by the kubelet on the node (similar to a heartbeat), even if the status hasn't changed.

**Comment by liggitt** [comment]
`kubectl get` doesn't show all status fields. the lastHeartbeatTime in the status is frequently updated.
