### ISSUE TITLE
Google Cloud needs to add a firewall rule for LB healthchecks

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#40778]
From GCE email today:

* Current behavior: You are not required to add firewall rules for Network LB health checks today

* Action required: We are introducing three new ranges for health checking: 209.85.152.0/22, 209.85.204.0/22, and 35.191.0.0/16. You need to ensure that your firewall allows traffic from 209.85.152.0/22, 209.85.204.0/22, and 35.191.0.0/16. The health check probes to your backend instances will come from one of these ranges.

We have until Jan 31, 2018 - 1 year.

**Comment by nicksardo** [comment]
/assign

@thockin this issue explains the confusion I had several weeks ago when speaking with @MrHohn and you about L4 health checks. I didn't realize a firewall rule isn't currently required.

**Comment by thockin** [comment]
Is this done now?

**Comment by MrHohn** [comment]
> Is this done now?

Not yet, there is a WIP on #45524.
