### ISSUE TITLE
metav1.Duration formats to `0` or `0s` depending on go version

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#40783]
In go 1.7, the format of time.Duration with a zero value was changed from `0` to `0s`: https://golang.org/doc/go1.7#minor_library_changes

`k8s.io/kubernetes/pkg/apis/meta/v1/Duration` wraps time.Duration, and does not add any additional logic: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/duration.go#L46

Thus if compiled with 1.6, the zero value is `0`, with 1.7 it is `0s`.

I'm not sure of the chronology here and the implications.  When we released it, we built with 1.6, so `0s` is a 1.5 regression, which we should now reverse?  Or we should always output `0s`, because "0 = 0" but "0 seconds != 0 metres".

cc @kubernetes/sig-api-machinery-misc

**Comment by kris-nova** [comment]
While we are at it, we probably ought to keep an eye on 1.8 - the release notes aren't out yet (it's still in beta) but if we start working on this we should double check the new release as well

**Comment by liggitt** [comment]
what APIs is this type used in?

**Comment by liggitt** [comment]
since `time.ParseDuration` handles "0s" correctly in all go versions, I'm not sure whether this would be considered a breakage or not... the value produced by new versions is consumable by old versions, and vice-versa.

**Comment by justinsb** [comment]
AFAICT, only componentconfig, which is thankfully still in alpha!

The most important question: `0` or `0s`? :-)

**Comment by liggitt** [comment]
I'd lean toward `0s`, but could be talked out of it

**Comment by justinsb** [comment]
It does have the advantage of not having to argue with the go team.  I think `0s` is an excellent zero value.

**Comment by smarterclayton** [comment]
We should open an issue that time.Duration must be purged from our public
APIs - I'm pretty sure this won't be the last break.

**Comment by justinsb** [comment]
I didn't find any bare `time.Duration`s - but I agree we should be wary.

The default marshalling is nanoseconds, so I'm guessing everyone will wrap it or define it as an integer number of seconds (see below).  Any wrapper should be careful though!

https://play.golang.org/p/LiLq9Zy6X-

```
package main

import (
	"encoding/json"
	"fmt"
	"time"
)

type A struct {
	DoSomethingEvery time.Duration
}

func main() {
	{
		a := &A{}
		s, _ := json.Marshal(a)
		fmt.Println(string(s))
	}
	{
		a := &A{
			DoSomethingEvery: 1 * time.Second,
		}
		s, _ := json.Marshal(a)
		fmt.Println(string(s))
	}

}
```

```
{"DoSomethingEvery":0}
{"DoSomethingEvery":1000000000}
```

**Comment by kris-nova** [comment]
Regarding your question

> The most important question: `0` or `0s`? :-)

I always err on the side of explicitly defining units of measure.. so `0s` gets my vote :)
