### ISSUE TITLE
Improve code coverage for /pkg/admission

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#40782]
This is a sub issue for #39559

cc @timstclair can you please assign this to me? Thanks.

For more detail, refer to https://docs.google.com/document/d/1Xa3IxMQg7LLqwcb4CV3kyBFlXErzysMOB1XDCW6KQVc/edit

**Comment by gyliu513** [comment]
Improved test code coverage for plugin/pkg/admission/admit https://github.com/kubernetes/kubernetes/pull/41297

**Comment by k82cn** [comment]
/close

act as #41297
