### ISSUE TITLE
Expose/add useful methods on unstructured.Unstructured

### ISSUE THREAD

**Issue by ash2k** [kubernetes/kubernetes#40790]
This is similar to #40657 - It would be really useful to have the following methods exposed:
* Unstructured.setNestedField()
* Unstructured.setNestedSlice()
* Unstructured.setNestedMap()

And the following methods added:
* Unstructured.GetNestedField()
* Unstructured.GetNestedString()
* Unstructured.GetNestedSlice()
* Unstructured.GetNestedMap()
* Unstructured.SetNestedString() - this is a more type-safe and restricted setNestedField(). setNestedField() may still be useful though.

/cc @sttts, @calebamiles Maybe you could label this issue appropriately so relevant people can see it? Thanks in advance!

**Comment by calebamiles** [comment]
how are these labels @ash2k?

**Comment by liggitt** [comment]
Rather than member methods, these seem more like generic helper functions that could operate on an unstructured object

**Comment by ash2k** [comment]
@liggitt what would be the best package to place those helper functions? I'd like to have them as both helper functions and methods if that is ok. Same package or maybe `k8s.io/apimachinery/pkg/conversion/unstructured`?

**Comment by sttts** [comment]
Same package is ok. We usually don't put helpers onto objects as methods. But being in the same package will allow you to keep "Unstructured" out of the function names. So usage shouldn't much uglier than with methods.

**Comment by sttts** [comment]
Oh, please drop the "Get" from the func names. This is a go anti-pattern.
