### ISSUE TITLE
Wrong VM name is retrieved by the vSphere Cloud Provider

### ISSUE THREAD

**Issue by cvauvarin** [kubernetes/kubernetes#40819]
**What keywords did you search in Kubernetes issues before filing this one?**: VMware, vSphere, IP, UUID

---

BUG REPORT. 

**Kubernetes version**:

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0", GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", BuildDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0", GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", BuildDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: VMware vSphere 6.5.0
- **OS** : Debian GNU/Linux 8.7 (jessie)
- **Kernel** :` Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux`
- **Install tools**: Kargo

**What happened**:

Some containers were launched on a node with a name containing the hostname of a different node and the `kubelet_node_status.go` does not retrieve the right node name :

```
Feb  1 18:11:16 k8s.minionpp-01.adm kubelet[1009]: I0201 18:11:16.953239    1060 kubelet_node_status.go:74] Attempting to register node k8s.minionpp-02
Feb  1 18:11:16 k8s.minionpp-01.adm kubelet[1009]: I0201 18:11:16.972697    1060 kubelet_node_status.go:113] Node k8s.minionpp-02 was previously registered
Feb  1 18:11:16 k8s.minionpp-01.adm kubelet[1009]: I0201 18:11:16.972783    1060 kubelet_node_status.go:77] Successfully registered node k8s.minionpp-02
```

Here `k8s.minionpp-02` is retrieved instead of `k8s.minionpp-01`.

When using the VSphere Cloud provider, the node name is retrieved from the `getVMName` function in https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L204. 

Since this PR (https://github.com/kubernetes/kubernetes/pull/27331/files), the node data are retrieved based on the IP address instead of the UUID. The function gets all the IP address and check if one of the IP on any interface matches a VM on vSphere. The problem is that the docker0 interface has the same IP on all the nodes (usually 172.17.0.1) and this IP is referenced into VMware. As this IP may be the first to appear in the [addr list](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L205) it will match the first VM that vSphere gives with the [FindByIp](https://github.com/vmware/govmomi/blob/f9184c1d704efa615d419dd8d1dae1ade94701d1/object/search_index.go#L100) function and this can be any VM running Docker on vSphere. Thus, the provider has a big chance to not get the informations for the VM it is running on, leading to an inconsistent state in the cluster (wrong pod name for example). 

**Anything else we need to know**:

An idea would be to first retrieve the VM name with the [FindByDnsName](https://github.com/vmware/govmomi/blob/f9184c1d704efa615d419dd8d1dae1ade94701d1/object/search_index.go#L59) function and if no results use the IP address (and add an exclusion to not use the `docker0` interface).  What do you think ? If you think this might be the right way to do, we can try to propose the PR.

Thanks for your feedback.

**Comment by robdaemon** [comment]
Wow, this very much is a bug. It was introduced by one of my colleagues here at HPE.

I'll send a PR upstream tomorrow to resolve this. I think it's best to go back to using dmidecode, but maybe someone from VMware (@abrarshivani or @kerneltime ?)

This would still require root access, but I can't think of a better way to get the machine's ID.

**Comment by kerneltime** [comment]
Related issue https://github.com/kubernetes/kubernetes/issues/33114

Will dig in more. For now instead of making it a value determined runtime the deployment framework should have root privileges and can populate it as part of the cloud config post VM creation.

**Comment by MrTrustor** [comment]
@cvauvarin is my colleague. A little more info and a few ideas. I would also support going back to ``FindByUUID``. We may not need dmidecode for getting the UUID. It is available in ``/sys/devices/virtual/dmi/id/product_uuid``. We could also have the following logic:

- Get UUID and use it to get the VM Name with FindByUUID if possible,
- If not, get the hostname and use FindByDNSName,
- If still nothing is found, keep the current logic, excluding docker0 from the interfaces we examine.

However, I agree with @kerneltime that getting this from the cloud config may be the best and most reliable solution.

**Comment by robdaemon** [comment]
I'm working on a patch right now that will do the following:

* Add a VMUUID field to the cloud config
* If VMUUID is not set, will use `/sys/devices/virtual/dmi/id/product_uuid`
* Error out if neither one is available

**Comment by robdaemon** [comment]
PR is #40892 - if someone would like to review :)
