### ISSUE TITLE
kubectl exec fails with connection refused

### ISSUE THREAD

**Issue by screeley44** [kubernetes/kubernetes#40817]
Have a single node cluster (local-up-cluster.sh) on AWS using latest HEAD - start a pod that connects to EFS.  Pod runs, mount works.

Try to exec into the pod:

```
[root@ip-172-18-10-229 nfsvol]# kubectl exec -ti nfs-bb-pod1 /bin/sh
Error from server: error dialing backend: dial tcp 172.18.10.229:10250: getsockopt: connection refused
```

From docker, have no issue exec into the pod
```
[root@ip-172-18-10-229 nfsvol]# docker exec -it bb8c8f39856a /bin/sh
/ # pwd
/
/ # cd /usr/share/busybox/
/usr/share/busybox # ls
test.txt
/usr/share/busybox # 
```

I'm also able to access the node (fqdn or ip) and the pods IP fine with a simple ping.

possibly related to #40459 - as I had to delete the .kube/config to be able to use kubectl

**Comment by ncdc** [comment]
@screeley44 are you still having issues with this?

**Comment by screeley44** [comment]
closing this as have not had an issue quite some time...

**Comment by davecramer** [comment]
I'd like to reopen this. I have the same issue.

**Comment by jingpengw** [comment]
I have this issue in 2020!

**Comment by jingpengw** [comment]
I found that my issue is because the pod was shutdown during my execution!
