### ISSUE TITLE
Support for defining swagger extensions directly in types.go

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#40818]
Background:
kubectl and the Kubernetes reference docs both depend on the swagger.json spec to operate on Kubernetes resources.  The swagger.json lacks important information required by kubectl and the
docs.

Usecase:

- kubectl can identify the patchStrategy and mergeKey for resource fields
- kubectl can identify the columns to print for `kubectl get <type>` on resources
- docs can parse and display the default value for fields
- docs can identify top-level objects

Solution:

Add items to the comment tag: `// +k8s:openapi-gen`

Example:

```
// +k8s:openapi-gen=true,x-kubernetes-get-columns="FIELD_TITLE:field.path",x-kubernetes-describe-columns="FIELD_TITLE:field.path,OTHER_FIELD_TITLE:other.field.path"
type Type struct {
  // +k8s:openapi-gen=x-kubernetes-patch-strategy="merge",x-kubernetes-patch-merge-key="name"
  Field Type `patchStrategy:"merge" patchMergeKey:"name"`
}
```

The long term plan is to remove the `patchStrategy` and `patchMergeKey` struct tags once all code has been updated to use the swagger spec instead.  Until then, comments should be added for the struct tags `patchStrategy` and `patchStrategy`.  Some verification process will need to be written to make sure the struct tags and comments remain in sync.

**Comment by foxish** [comment]
I think this wouldn't fall under sig-apps. 
cc @kubernetes/sig-api-machinery-misc

**Comment by smarterclayton** [comment]
I would not do the columns stuff - we're moving get to the server side.
Top level objects is already available in some form by the client -
specifically the list that we use (should use) to get the swagger doc tells
us what the top level type is (or is that for something like explain).

Merge key, patch strategy, default values all belong as "real" attributes,
although we had not necessarily intended those to be arguments to
k8s:openapi-gen, but actual tags in their own right (like "+optional")

On Wed, Feb 1, 2017 at 3:33 PM, Anirudh Ramanathan <notifications@github.com

**Comment by pwittrock** [comment]
@smarterclayton Thanks

> I would not do the columns stuff - we're moving get to the server side.

Is there a design proposal / eta for this?

> Top level objects is already available in some form by the client -
> specifically the list that we use (should use) to get the swagger doc tells
> us what the top level type is (or is that for something like explain).

This is for generating the docs from swagger.  Right now the list of top level resources for the docs to display is hardcoded in a [config file](https://github.com/kubernetes-incubator/reference-docs/blob/master/gen_open_api/config.yaml).  I would like to move the majority of the metadata out of the config file so that:

1. The same tool can generate reference docs for federated apiservers without writing a custom config.
2. I don't need to manually maintain and update the config for each release - e.g. adding new types

> Merge key, patch strategy, default values all belong as "real" attributes,
> although we had not necessarily intended those to be arguments to
> k8s:openapi-gen, but actual tags in their own right (like "+optional")

I have no strong opinion about this as long as they appear in the swagger so it is possible right tools the can use this data.  @mehdy Can you comment on why openapi-gen vs specific tags?

**Comment by pwittrock** [comment]
Describe in the server makes sense to me.  IIUC, `get -o wide` just prints out a set of columns.  Was the idea that the server would just print out the columns or return a list of column / values or something more complicated?  No need to answer if it is in the issue / proposal already.

**Comment by smarterclayton** [comment]
https://github.com/kubernetes/kubernetes/pull/33900 is the bigger issue
that touches on a rough overview, I can't find my rambling brain dump of
the problem, but get would be rough tabular json, you could also get that
as csv, and describe could be a richer but not quite full structured
key/value structure.

On Feb 1, 2017, at 7:26 PM, Phillip Wittrock <notifications@github.com>
wrote:

Describe in the server makes sense to me. IIUC, get -o wide just prints out
a set of columns. Was the idea that the server would just print out the
columns or return a list of column / values or something more complicated?
No need to answer if it is in the issue / proposal already.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/40818#issuecomment-276828105>,
or mute the thread

**Comment by mbohlool** [comment]
regarding tags, they do not need to be in the same k8s:openapi-gen tag, it can be repeated:

```golang
// +k8s:openapi-gen=true
// +k8s:openapi-gen=x-kubernetes-get-columns:"FIELD_TITLE:field.path"
// +k8s:openapi-gen=x-kubernetes-describe-columns:"FIELD_TITLE:field.path,OTHER_FIELD_TITLE:other.field.path"
type Pod struct {
...
}
```

they can also be separate tags but still general like this:

```golang
// +k8s:openapi-gen=true
// +k8s:openapi-tag:get-columns="FIELD_TITLE:field.path",
// +k8s:openapi-tag:describe-columns="FIELD_TITLE:field.path,OTHER_FIELD_TITLE:other.field.path"
type Pod struct {
...
}
```

The idea is to have a general way to add arbitrary extension to a type so we don't need to change code generator for each specific tag. I have no strong feeling about the format, but I would like it to be general vs tags like +optional. The difference is +optional is a defined tag in OpenAPI (`required`) but extensions does not have any meaning for code generator. They better to be general so generate can pass them without change.

**Comment by smarterclayton** [comment]
No, I mean we should define conventions in our API code that match the
intent (optional) rather than have tons and tons of repeated code that is
setting x-kubernete-describe-columns (or similar)

**Comment by pwittrock** [comment]
@smarterclayton I spent some time thinking about your comments last night.  I think don't think this is mutually exclusive with #33900, and could be complementary.

IMHO this is general metadata associated with the type, and including it in the swagger.json doesn't preclude supporting an api endpoint that pre-parses and formats the data.  However, including it in the swagger  does allow clients using the swagger to take advantage of it.

Following is an example of where the swagger would be useful even if get was in the sever.  A generated Java client could use the display columns for the "toString" method of the resource.

Another use case that @jbeda had mentioned to me was to allow some kubectl commands to operate on directly on local files.  e.g. (strawman) `kubectl get -f <filename> --local` could print the columns.  I don't think we want to do this now, but it is an example of why keeping this object metadata private to the server limits what we can do.

My hope is that this swagger tags solution will also oprove portable to easily work with ThirdPartyResources as well by writing the display-columns as an annotation on the TPR and keeping the same format.

`kubectl describe` is a can of worms, and I would agree that the solution #33900 is capable of providing a richer experience for aggregating information across multiple resource types - e.g. how describing Nodes fetches Pod information.  I still think that the solution is compatible with the richer solution you proposed and there is not much additional cost in doing it.  Howv

What would you think of supporting a set of optional ALPHA extensions for "display-columns" and "describe-columns" allowing any consumers of the swagger to print the objects.  In theory it could also be used by the UI to provide a summary view without having to do separate lookups.  As an ALPHA feature we could try it for supporting sig-service-catalog and revisit it in 1.7.  If we consider it successful, the solution outlined in #33900 could become another consumer of the display-columns tag?

> No, I mean we should define conventions in our API code that match the
> intent (optional) rather than have tons and tons of repeated code that is
> setting x-kubernete-describe-columns (or similar)

I like this approach.  My biggest concern here is being able to get this into 1.6.  Since kubectl supports +/-1 version skew, we need will need to maintain the old logic for at least 1 full release after we add support for the new swagger based logic.  That puts us at > 6 months from now to fully migrate if we don't have any swagger extensions in 1.6.

**Comment by smarterclayton** [comment]
> Another use case that @jbeda had mentioned to me was to allow some kubectl commands to operate on directly on local files. e.g. (strawman) kubectl get -f <filename> --local could print the columns. I don't think we want to do this now, but it is an example of why keeping this object metadata private to the server limits what we can do.

I think that's a nice to have in the long run - but then people will say "why are the columns different when the server prints them from the local print"?  And most of the pod columns in no way can represent the full complexity of what they print with swagger, so the best effort local printing is going to be really, really, really best effort.  Also, local print is a really specialized case - if we just did the generic metadata print that would probably be ok.   So while I agree it's valid, it seems like a lot of work for very little practical value.

> My hope is that this swagger tags solution will also oprove portable to easily work with ThirdPartyResources as well by writing the display-columns as an annotation on the TPR and keeping the same format.

Again, not opposed, just don't want to do two things halfway and then have nothing.  So just biased towards not adding more client complexity in the near term.

> What would you think of supporting a set of optional ALPHA extensions for "display-columns" and "describe-columns" allowing any consumers of the swagger to print the objects

So you want to hack this in for service catalog in 1.6 on TPR?  I feel like that's a lot of hacks - the generic printer stuff at least gives you name and namespace, and I'd rather do nothing in 1.7 for generic client printer rather than jump ahead.  I won't stop you if you want to spend time and effort on it, but it's a lot of specialized work that will then be neglected while we do the server side stuff.

**Comment by mbohlool** [comment]
My intend here was avoiding repeated code for adding each of these tags somewhere (in openapi-gen code or some root level place). Let me distinguish these tags in two categories with respect to OpenAPI code generator:

1. Tags that need some sort of processing that affects OpenAPI spec (e.g. +optional removes the field from `required` OpenAPI field)
2. Tags that need no more processing and will be directly put into OpenAPI spec (e.g. +gvk that we don't have but we can define as a way to define Group/Version/Kind of an object vs register method)

My argument is about the second one. I think patch strategy here falls into this category. The question is only about naming it.

Naming Option 1: +patch-strategy=... This looks cleaner but we need to define an alias somewhere to tell generator this is the same as x-kubernetes-patch-strategy. The alias definition and the tags are in two places. Putting them in the generator code make the code non-generic and we don't want to do that. Putting these aliases somewhere as an argument to the generator begs for bugs as people that look at the type and add this tag to their types need to know (maybe by reading a doc, but who do that) that it needs to pass the alias to the generator. I, in 6 month, will look at a type and see a tag and copy the tag to my type and expect it to work that will not with this option.

Naming Option 2: use something generic for these type of tags. after all generator does not need to do any processing. I suggest +openapi-tag:tag=value that will result in "x-kubernetes-tag: value" in OpenAPI spec. There is no alias defined anywhere and without any code change or alias copying or any knowledge about passing any argument, a tag can be added to OpenAPI spec. The value of these tags and their use cases are outside of the scope of what I am arguing about.

Anyway a solution is better than no solution, I would suggest we continue with Option 2 as Alpha and change it later if we see fit. Adding an aliasing mechanism to this option later should be easy.

**Comment by smarterclayton** [comment]
On patch strategy, I had assumed we'd read the value from what's in the
struct tag, rather than requiring a net new tag?

**Comment by pwittrock** [comment]
The get stuff is less urgent for me as long as we aren't doing even more hacky things to work around the current limitations, and can make a commitment to delivering it in a specific release (sounds like 1.7).

For service catalog there was a plan to fork kubectl, compile the service catalog types into the binary, and provide the fork as a separate binary.  I have some concerns with this approach.  I would rather provide a temporary hack in the code that can provide a consistent user experience from day one and re-implement later vs having users get used to downloading separate binaries for each aggregated apiserver.

I have no plans to do any work for on this for the core Kubernetes types, and can punt on it until the scope of the work is understood to be relatively small and easily upgraded to the server-side get.
