### ISSUE TITLE
lastBaseRuntimeSync confusion.

### ISSUE THREAD

**Issue by hhzguo** [kubernetes/kubernetes#40827]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
current version

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
"container runtime is down"

**How to reproduce it** (as minimally and precisely as possible):
in pkg/kubelet/runtime.go file,(at the end of the file)
func newRuntimeState{
... 
    lastBaseRuntimeSync: time.Time{}

My question is why we set it to 0, this way, we always got  "container runtime is down" error 
when runtimeState.errors is called in kubelet.syncLoop funcdtion.

**Comment by spzala** [comment]
@hhzguo hello, thanks for asking this question but considering the type of question I would recommend to ask on the #kubernetes-dev or per issue triage guidelines any questions/confusions should be asked on the https://stackoverflow.com/questions/tagged/kubernetes It will help to get you answer quickly. So can you please close this issue as it's not really an issue. Once you get an answer and find out that it's indeed a bug, you can always open it again with steps to recreate the bug. Thanks!
