### ISSUE TITLE
kubectl exec gives poor output when command does not exist in container

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#40820]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
HEAD

**Environment**:
- OS 4.9.5-200.fc25.x86_64
- docker 1.12.6

**What happened**:
$ kubectl exec <pod> foobar
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"foobar\\\": executable file not found in $PATH\"\n"

**What you expected to happen**:
env: can't execute 'foobar': No such file or directory in PATH

**How to reproduce it** (as minimally and precisely as possible):
see above, just exec and attempt to run a process that doesnt exist in the container.  the error message should not include the extra gorp as its unhelpful to the user.

**Anything else we need to know**:
nope.

**Comment by xingzhou** [comment]
I'd like to take some investigation on this first.

**Comment by xiangpengzhao** [comment]
/sig cli
Seems like the output is the error from docker API and kubectl just print it directly. We might not be able to only print you mentioned because the error may be various, IMO
