### ISSUE TITLE
Delete many E2E tests

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#40839]
They don't scale, for a variety of reasons:

* E2E tests cannot be intelligently cached by Bazel, so we end up running all of them for every PR regardless of whether they need to run. Unit tests, on the other hand, only run when they need to.
* E2E tests are slow. Most of them take about a minute to run, and there are hundreds of them. Even trivial tests take a long time. We run each test against several environments on each PR, and ever full run takes anywhere from forty minutes to an hour.
* E2E tests tend to be flaky, especially when run in parallel with each other. Because we run them against several environments, the pain is multiplied.

Here's an example:

`[k8s.io] Job should scale a job down` starts a job with parallelism set to 2, waits for two pods to be active, sets parallelism to 1, and waits for only one pod to be active. The e2e test takes [between 1.5 and 2 minutes each run](https://k8s-testgrid.appspot.com/google-gce#gce&include-filter-by-regex=Job+should+scale+a+job+down&graph-metrics=test-duration-minutes). There is a unit test in [pkg/controller/job/jobcontroller_test.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/jobcontroller_test.go) that checks this case (it's the "too many active pods" case, parallelism set to 2, activePods set to 3, expectedDeletions set to 1).

Would anyone object to deleting this e2e test, and why?

@k8s-sig-testing-misc @kubernetes/sig-contributor-experience-proposals

**Comment by spxtr** [comment]
cc @soltysh @erictune for the particular example.

**Comment by soltysh** [comment]
Commented on the linked PR.

**Comment by spxtr** [comment]
@nikhiljindal @kargakis @janetkuo, which deployment e2e tests don't have sufficient unit test coverage?

**Comment by spxtr** [comment]
Discussions in #40944 showed that the worry is that the unit test coverage only hits a single iteration of the controller sync loop, while e2e tests can follow a deployment through an entire process such as a rolling update. We should make it easier to do this kind of testing locally as an integration test.

**Comment by kargakis** [comment]
@spxtr do integration tests use docker?

**Comment by spxtr** [comment]
Some do, and some use etcd as well.

**Comment by spxtr** [comment]
@kargakis check out some of the integration tests in [this file](https://github.com/kubernetes/kubernetes/blob/master/test/integration/replicaset/replicaset_test.go). I think it makes sense to use this type of test instead of all but one or two deployment e2e tests.

**Comment by marun** [comment]
I'm working on enabling integration testing for federation (#40705).  Hopefully this can reduce the amount of federation testing that is done via e2e.
