### ISSUE TITLE
Cannot set flannel public IP in 1.5

### ISSUE THREAD

**Issue by InAnimaTe** [kubernetes/kubernetes#40835]
Wanted to post this here as well for more coverage (posted on the tectonic forum). This has got to be a similar problem for anyone with an internal host utilizing flannel on top of k8s.

### k8s Version 

1.5.2 (tectonic)

### Environment

* 1x Controller Node is VPS with public IPv4 Address (Vultr allows for iPXE endpoints)
* 1x Worker Node (bare-metal) behind NAT address (so interface has internal IP but has to be accessed via external public IP)

### Current Status

My cluster is 3/4 of the way created; Hanging at `Waiting for Kubernetes components.` via a `journalctl`
Presumably, this is because flannel is having a heart attack over the worker node IP.

Pre-1.5, you just needed something like:

```
$ cat /etc/systemd/system/flanneld.service.d/10-custom.conf  
[Service]
Environment="FLANNELD_PUBLIC_IP=1.2.3.4"
```
Now, it seems flannel is running as a DaemonSet, which makes configuring it a bit harder.

#### What I've Tried

I took a look at its yaml config and see that it takes some configuration from (on the host) `/etc/kubernetes/cni/net.d`, but that config seems to be specific to what it provides, not core configuration like `--public-ip`:

```
worker net.d # cat 10-flannel.conf
{
  "name": "cbr0",
  "type": "flannel",
  "delegate": {
    "isDefaultGateway": true
  }
}
```

Additionally, I tried doing an edit on the DaemonSet directly to add the `--public-ip` option to the command using:

```
kubectl edit ds/kube-flannel -n kube-system
```

Unfortunately, I get a `Invalid value: "The edited file failed validation": the server does not allow access to the requested resource` :(

**Is there another way to achieve what I'm trying to do in this new flannel deployment model? Or, what am I doing wrong?**

### Outputs

Some details to show what's going on. Let me know if you'd like more to help diagnose.

```
└[~]> kubectl get ds -n kube-system -o wide
NAME                   DESIRED   CURRENT   READY     NODE-SELECTOR   AGE       CONTAINER(S)               IMAGE(S)                                                                   SELECTOR
checkpoint-installer   1         1         1         master=true     21h       checkpoint-installer       quay.io/coreos/pod-checkpointer:5b585a2d731173713fa6871c436f6c53fa17f754   k8s-app=pod-checkpoint-installer
kube-apiserver         1         1         1         master=true     21h       kube-apiserver             quay.io/coreos/hyperkube:v1.5.2_coreos.1                                   k8s-app=kube-apiserver
kube-flannel           2         2         1         <none>          21h       kube-flannel,install-cni   quay.io/coreos/flannel:v0.7.0-amd64,busybox                                app=flannel,tier=node
kube-proxy             2         2         2         <none>          21h       kube-proxy                 quay.io/coreos/hyperkube:v1.5.2_coreos.1                                   k8s-app=kube-proxy

```

```
└[~]> kubectl get pods -n kube-system        
NAME                                                READY     STATUS              RESTARTS   AGE
checkpoint-installer-9dm3l                          1/1       Running             0          21h
kube-apiserver-wcjnw                                1/1       Running             3          21h
kube-controller-manager-3654003418-vdl6b            0/1       ContainerCreating   0          21h
kube-controller-manager-3654003418-xjmfv            1/1       Running             0          21h
kube-dns-4101612645-rsffh                           0/4       ContainerCreating   0          21h
kube-flannel-2x4j5                                  2/2       Running             0          21h
kube-flannel-rcwps                                  1/2       CrashLoopBackOff    257        21h
kube-proxy-71stj                                    1/1       Running             0          21h
kube-proxy-ddcvb                                    1/1       Running             0          21h
kube-scheduler-850181384-1n4mr                      0/1       ContainerCreating   0          21h
kube-scheduler-850181384-kkcb9                      1/1       Running             0          21h
pod-checkpointer-tectonic-controller-01.arroyo.io   1/1       Running             0          21h

```

```
└[~]> kubectl get ds/kube-flannel -n kube-system -o wide  
NAME           DESIRED   CURRENT   READY     NODE-SELECTOR   AGE       CONTAINER(S)               IMAGE(S)                                      SELECTOR
kube-flannel   2         2         1         <none>          21h       kube-flannel,install-cni   quay.io/coreos/flannel:v0.7.0-amd64,busybox   app=flannel,tier=node

```

**Comment by renoirb** [comment]
Well described. What is the linux kernel version you're using, which kernel modules (flanneld Backend) you have loaded (vxlan)?

**Comment by maxx** [comment]
This could potentially be worked around by adjusting the annotation on the node, but flannel overwrites it on startup.  I raised an issue for this just hours ago:

https://github.com/coreos/flannel/issues/712

I'm not sure what the right approach is exactly, but --public-ip won't work when run with a daemonset.
