### ISSUE TITLE
Add some unit tests for apply on TPR

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes#40841]
Copied from https://github.com/kubernetes/kubernetes/pull/40666#issuecomment-276563996

Initial attempt: #40775

We should at least have the following unit tests:
- create object with unknown group/version (covers TPR creation scenario)
- changing patch of object with unknown group/version (covers TPR apply scenario)
- no-op patch (idempotent apply) object with unknown group/version (covers TPR re-apply scenario)
- changing patch of known object (like deployments) in an unknown version (will need to add the unknown version to the fake discovery doc - see https://github.com/kubernetes/kubernetes/pull/40630/commits/cf74abd892fd61fbfc6967b1814bc911df8fd413#diff-685443e183899c880f3c3150021d7229 as an example) - makes sure kubectl is resilient to future versions of known objects being introduced

**Comment by ymqytw** [comment]
@ahakanbaba This is for you.

**Comment by ahakanbaba** [comment]
Thanks I will follow up with this.

**Comment by ymqytw** [comment]
@ahakanbaba You should be good to go. #40666 merged.

**Comment by ahakanbaba** [comment]
Thanks

**Comment by ahakanbaba** [comment]
@GnawNom This is the issue we can collaborate on. 
I will mention this issue in my PR's so you can also keep track.

**Comment by ahakanbaba** [comment]
@GnawNom I will work on 
no-op patch (idempotent apply) object with unknown group/version (covers TPR re-apply scenario)
first. 
FYI .

**Comment by liggitt** [comment]
These exist now:

https://github.com/kubernetes/kubernetes/blob/bc0e706a0a4f8a67b6e0d0525baac42c198c4f47/hack/make-rules/test-cmd-util.sh#L1731-L1852

/close
