### ISSUE TITLE
CRI: StopPodSandbox relevance

### ISSUE THREAD

**Issue by sameo** [kubernetes/kubernetes#40857]
Looking at the CRI runtime service, I am wondering what `StopPodSandbox` is useful for.
According to the code comments, I understand `StopPodSandbox` main role is to reclaim all pod resources, but then from a `StopPodSandbox` call one can only move to a `RemovePodSandbox` one.

In other words, it seems to me that `StopPodSandbox` is a redundant state machine transition and could be potentially removed if `RemovePodSandbox` would also take care of reclaiming all resources. As a matter of fact, some CRI implementations already assume it should do that.

What am I missing ?

cc @runcom @mrunalp

**Comment by Random-Liu** [comment]
@sameo I think `StopPodSandbox` is to reclaim most pod resources (cpu, memory, networking etc.). However, after that we may still want to keep the sandbox status and logs on the disk for further debugging. And only reclaim the disk `RemovePodSandbox` when there is disk pressure or it is not needed anymore.

**Comment by calebamiles** [comment]
@sameo, has your question been answered? can this issue be closed?

**Comment by resouer** [comment]
also cc @feiskyer

**Comment by feiskyer** [comment]
> @sameo I think StopPodSandbox is to reclaim most pod resources (cpu, memory, networking etc.). However, after that we may still want to keep the sandbox status and logs on the disk for further debugging. And only reclaim the disk RemovePodSandbox when there is disk pressure or it is not needed anymore.

Right. Besides, `RemovePodSandbox()` will also remove all containers belonging to the sandbox, but we want to keep terminated containers for fetching logs, e.g. 

```
  # Return snapshot of previous terminated ruby container logs from pod web-1
  kubectl logs -p -c ruby web-1
```

**Comment by yujuhong** [comment]
@sameo `StopPodSandbox` should release networking resources (among others). As others have mentioned above, kubelet relies on the tombstones (i.e., terminated containers, sandboxes) to keep track of the state of the pod. While doing so, we want to minimize the occupied resources by the podsandbox. This may change (not needed) in the future if kubelet's implementation changes. 

Hope this answers your question. I'm closing the issue, but feel free to re-open it if the answer does not satisfy you.
