### ISSUE TITLE
`kubectl cp` remote-to-local copy loses owner and access permission information

### ISSUE THREAD

**Issue by Corristo** [kubernetes/kubernetes#40869]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kubectl cp

---

**BUG REPORT**

**Kubernetes version** (use `kubectl version`):
Google cloud production environment:
    Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.8", GitCommit:"c5fcb1951afb8150e4574bc234aed957cb586eb0", GitTreeState:"clean", BuildDate:"2017-01-12T02:14:29Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

Local Minikube on laptop:
    Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Tested in Minikube and Google cloud
- **OS** (e.g. from /etc/os-release): 
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- **Kernel** (e.g. `uname -a`):
Linux pc-408 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**What happened**:
When copying files from a remote pod to the local pod or host via
    `kubectl cp <remote-pod>:<some-file> <some-file>`
access permissions and owner information of the file gets lost and its new owner always
is root:root and permissions are as if set by `chmod 644 <some-file>`.

**What you expected to happen**:
I expect the access permissions and the owner to stay the same, which is what happens
when performing a local-to-remote copy.

**How to reproduce it** (as minimally and precisely as possible):
Run the attached bash script as root (needed for `chown`). Make sure
you replace `ubuntu` with an availible image if Ubuntu isn't. Any
image works.

[reproduce_kubectl_cp_issue.txt](https://github.com/kubernetes/kubernetes/files/748161/reproduce_kubectl_cp_issue.txt)

Output of the script above on my machine:

> $ sudo ./reproduce_kubectl_cp_issue.sh 
> pod "test-pod" created
> original file:
> -rwxr-xr-x 1 2345 root 5 Feb  2 16:29 /tmp/test.txt
>
> observe that the copied file still has the correct permissions and owner:
> -rwxr-xr-x 1 2345 root 5 Feb  2 15:29 /test.txt
>
> tar: Removing leading `/' from member names
> and now the permissions and owner information has been lost:
> -rw-r--r-- 1 root root 5 Feb  2 16:29 /tmp/test.txt
>
> pod "test-pod" deleted

**Comment by iTagir** [comment]
Hello!
the reason to that is the way how function copyFromPod and copyToPod are programmed.
copyToProd uses tar utility to untar on the target (pod) thus the permissions and ownership are preserved. copyFromPod also relies on tar utlity to create tarball before copy it locally. 
When it comes to untar the file on the local system though it uses GO function to walk through the tar, create directories and  files, func untarAll(reader io.Reader, destFile, prefix string) error {
Contrary to tar utility this function does not preserve properties of the source file, even more the directories always created with 755, its hard coded.
I'd like to fix that, but I need to understand the best way to that.
Tagir

**Comment by iTagir** [comment]
cc @brendandburns could you please share your thoughts on this? What was the idea behind using tar utility in the pod and a function at local? Do you think that tar dependency should be removed?

**Comment by grodrigues3** [comment]
@pwittrock I'll leave this one up to you as well.

**Comment by mikecico** [comment]
I'd also like to ask about why the tar command is required, and if that dependency can be removed, esp for copying simple files.  It would be good if the commands weren't dependent on utilities being present in the target container.
