### ISSUE TITLE
Test version upgrades in test-update-storage-objects.sh

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#40860]
follow up from https://github.com/kubernetes/kubernetes/pull/35782#discussion_r99113534

we should consider testing:
- ~~Job v1 and v2alpha2~~
- HPA v1 and v2alpha2

**Comment by piosz** [comment]
cc @caesarxuchao @kubernetes/sig-api-machinery-misc

**Comment by soltysh** [comment]
Jobs, should not exists in `batch/v2alpha1`, see https://github.com/kubernetes/kubernetes/issues/37166. So I'm crossing out the job from the initial list.

**Comment by calebamiles** [comment]
@piosz, why is this issue a release blocker?

**cc: @ethernetdan**

**Comment by piosz** [comment]
@caesarxuchao @lavalamp is this issue a release blocker?

**Comment by fgrzadkowski** [comment]
@piosz is it a release blocker?

**Comment by piosz** [comment]
@caesarxuchao @lavalamp should answer the question.

**Comment by caesarxuchao** [comment]
I don't think this is a release blocker. HPA is only stored as v1. The upgrade test need to be there before we store HPA in v2alpha2 (or other version).

**Comment by marun** [comment]
Assuming this shouldn't block 1.7, moving to 1.8.

**Comment by fgrzadkowski** [comment]
@DirectXMan12 can you please confirm https://github.com/kubernetes/kubernetes/issues/40860#issuecomment-284820782

**Comment by DirectXMan12** [comment]
err... so HPA v2alpha2 doesn't currently exist -- v2alpha1 is the only existant "v2" version.  That being said, I agree this probably isn't a blocker, but we should have v1 to v2alpha1 upgrade tests eventually.

**Comment by caesarxuchao** [comment]
The test tests `storage/v1beta1 <-> storage/v1` now, so we do have version update tests.

@DirectXMan12 we can re-title this PR or open another PR for the v1 to v2alpha1 upgrade of HPA, WDYT?

**Comment by DirectXMan12** [comment]
fine by me.

**Comment by caesarxuchao** [comment]
Tracked in #47804. Closing this issue.
