### ISSUE TITLE
Race condition in volume operations

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#40887]
In volume management design, volume operations attach/detach are executed by reconciler running on master, while mount/unmount are executed by reconciler running on node. Because the operations are distributed across master and node, there might be race condition issue among these operations. The most dangerous situation is master is trying to detach while the volume is mounted on node. The cooridination between master and node is through a shared node status stored in API server. Master updates what volumes are attached and node updates what volumes are mounted. The current workflow on master and node is as follows
On master, during detach
1. Mark volume as detached (remove the volume from attachedVolume list) to Node.status in API server
2. Check node status to see whether volume is currently mounted or not. If yes, mark volume as attached back and return. If no, continue to step 3
3. Issue detach request 

On node, during mounting
1. Check volumes in desired state and actual state. Mark volume as mounted (put it into volumeMounted list) to Node.status in API server. Check node status to see whether the volume is attached. If no, return. Otherwise, move to next step
2. Verify the device path and issue mount operation.
Also on node, when a pod is added, its volume information is added to desired state. When node status is updated periodically, the volume that is in either desired state or actual state will be mark as mounted to Node.status. 

From these steps, we can see there are steps to prevent race condition by marking volume status before executing command. But there is still a chance race condition happens as follows
0. master and kubelet put volume into desired state
1. master attach volume and update node status
2. kubelet check volume is attached and update volume as mounted in node status (volume is in desired state).
3. kubelet remove volume from desired state in kubelet (because pod is deleted), node status is updated to remove the volume from volumeMounted list
4. master mark volume as detached and check volume is not mounted
5. kubelet verify the device path, issue mount operation
6. master issue detach operation

The problem is that kubelet might update node status while there is a pending operation which results in a mounting volume is considered not mounted. So when updating node status, kubelet should not only check desired state and actual state, but also volume which is currently in pending operation.

**Comment by calebamiles** [comment]
Can someone from @kubernetes/sig-node-bugs or @kubernetes/sig-storage-bugs please help qualify this issue? Thanks!

**Comment by resouer** [comment]
@calebamiles  I will take a look at this. This is actually a known race but did not show frequently.
