### ISSUE TITLE
Test CRI with docker 1.10 in the node e2e suite

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#40880]
Since we are unsure whether docker 1.10 will continue to be supported in 1.6, we should prepare for the worst case (?) and test.

The prerequisite of this is to support older separator (`:`) for docker security options. Related PR: #40179

/cc @dchen1107 @Random-Liu

**Comment by Random-Liu** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/38164.

**Comment by yujuhong** [comment]
Right. I'll close this one.
