### ISSUE TITLE
Put kubelet into cgroups

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#4089]
Forked from #2884...

Running kubelet as a docker container  is much harder than other daemons since it has to run as root for now. But we still need to monitor its resource usage. We should create cgroups at node startup time for kubelet at the same level of /docker, and ask cAdvisor collect stats. 

cc/ @vishh

**Comment by saad-ali** [comment]
If for #2884 we end up using systemd to launch kubelet as a systemd service--we will get cgroups for free: see [http://0pointer.de/blog/projects/resources.html](http://0pointer.de/blog/projects/resources.html)

**Comment by vishh** [comment]
Thats true. I will be interested in how we end up partitioning the system
resources after switching to systemd.

**Comment by alex-mohr** [comment]
@dchen1107 Dawn, from a keeping-clusters-upgraded perspective, it would seem convenient if we could get a kubelet running by "docker run kubelet:version" with appropriate flags.  Can you elaborate on why that's not feasible?  FWIW, I think @smarterclayton mentioned openshift is running kubelet via docker?

**Comment by zmerlynn** [comment]
In particular, I'm curious if there's already an issue on the root-only requirement. Have we investigated all the various capabilities/etc. that we could try to grant? This seems like a really messy half-way solution where we're not exactly running kubelet in docker and not exactly running it not-in-docker, either, so we might as well just re-write docker?

**Comment by smarterclayton** [comment]
We are, and we're using versioned tags to control rollout of our infra components (but not the kubelet yet).  I can sketch out the basics but --net=host and --priviliged are enough for the kubelet and proxy, but volumes and mounts might cause a problem (even super priv containers have a few gotchas wrt how the mount namespace plays in).

**Comment by vmarmol** [comment]
In cAdvisor we've already run into issues about not being in the host
namespace. We've had to resort to hacks and less accurate data to deal with
it. It's just echoing the concern with mount namespaces @smarterclayton
mentioned. The Kubelet will run into more of these issues as it tracks and
affects the containers more. I'm not sure running the Kubelet inside
namespaces will be feasible long term. I think we'll be happy with a Docker
mode where we could run in all the host namespaces. At that point, I'm not
sure what running in Docker buys us.

**Comment by zmerlynn** [comment]
@vmarmol: It buys us a consistent deployment story across node OS images, yes? I think the route for this bug would have to be more manual (Saltstack?) setup to get everything up, which I know may sound like a minor thorn but is a constant, on-going burden we'll have to pay for each of <N> distros. I admit that I might be missing something, but I think it will be fairly uniform (perhaps) to setup a super-privileged Docker container, and then we'll "merely" be working out the kinks of getting kubelet working in one of those, rather than having to rewrite "setup kubelet in cgroups on every distro".

**Comment by dchen1107** [comment]
We introduced resource only container for all our daemons for 1.0 release already. Close this.
