### ISSUE TITLE
Enable Garbage Collector by default in ReplicaSet and Replication Controllers

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes#40898]
We should remove the boolean and enable garbage collection by default for replica sets and replication controllers.
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replicaset/replica_set.go

I think from my previous PR when setting up controllerRef for ReplicaSet , we came across this.

If you agree @caesarxuchao @kargakis i can fix this. Please assign this issue to me.

**Comment by kargakis** [comment]
Yes, we should!

**Comment by krmayankk** [comment]
thanks , will start working on this tomorrow.
