### ISSUE TITLE
Cannot use local registry on 1.5.2

### ISSUE THREAD

**Issue by garreeoke** [kubernetes/kubernetes#40891]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Kubernetes version** (use `kubectl version`): v1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: aws & gke
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**: kops
- **Others**:

**What happened**: Trying to use private registry.  Setup worked with version 1.4.8, now registry hangs when trying to search or push images to it.  No errors, just hangs.

**What you expected to happen**: Usable as was in version 1.4.8

**How to reproduce it** (as minimally and precisely as possible): 
1. Followed guide from link below.  Not using it as an add-on, installing manually.
2. Execute docker pull localhost:5000/image-name or build an image and try to push it to localhost:5000/image-name.  Both hang.

https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry

**Anything else we need to know**:

**Comment by jayjun** [comment]
@garreeoke For some reason, using `localhost` to find the local Docker registry breaks from Kubernetes 1.5 onwards.

The workaround is to use `127.0.0.1` instead. See deis/workflow#678.
