### ISSUE TITLE
Usability: The event for a failed mount is not designed for humans to read, and may even be harmful

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#40905]
This error message is incredibly common, fairly important for end users to understand, and we have made it so that even the AI people of 2312 will be unable to understand why a configmaps needed its UIDs to be spec named.

```
  1h  1h  9  {kubelet 10.1.2.2}  Warning  FailedMount  MountVolume.SetUp failed for volume "kubernetes.io/configmap/39e819a4-e9ad-11e6-addf-080027893417-config-volume" (spec.Name: "config-volume") pod "39e819a4-e9ad-11e6-addf-080027893417" (UID: "39e819a4-e9ad-11e6-addf-080027893417") with: configmaps "prometheus" not found
```

I'm fairly certain the message should be: `Unable to start pod - the referenced configmap "prometheus" does not exist`

**Comment by msau42** [comment]
I can look into cleaning this up since I am making some changes in this area.  Perhaps the details can be moved to a separate log message.

/assign

**Comment by msau42** [comment]
I'm planning to remove internal volume name and pod info from the event message, and log those details instead.  The event message will still have the failed operation, volume.Spec.Name, and error msg.  

@jeffvance you mentioned that you found the FailedMount msgs useful for debugging.  What do you think of simplifying the event message to be more user friendly, and logging the details separately?

**Comment by jeffvance** [comment]
@msau42 I like the idea! Good error msgs are really important for support people, customers and developers so I'll always vote in favor of improved error messages. In another issue related to mount error msgs I said that I like the `FailedMount` error from ceph-rbd. What I liked about that msg is that is said why the mount failed (_another process held a lock_) rather than something like `mount err 32`.

**Comment by ethernetdan** [comment]
@smarterclayton can this go into 1.7?

**Comment by ncdc** [comment]
Moving to 1.7
