### ISSUE TITLE
minor spelling misstake

### ISSUE THREAD

**Issue by Lallassu** [kubernetes/kubernetes#40916]
2  pkg/controller/volume/persistentvolume/pv_controller.go
 @@ -1430,7 +1430,7 @@ func (ctrl *PersistentVolumeController) scheduleOperation(operationName string,
 		if goroutinemap.IsAlreadyExists(err) {
 			glog.V(4).Infof("operation %q is already running, skipping", operationName)
 		} else {
-			glog.Errorf("error scheduling operaion %q: %v", operationName, err)
+			glog.Errorf("error scheduling operation %q: %v", operationName, err)
 		}
 	}
 }

**Comment by k82cn** [comment]
@Lallassu , are you going to open a pull request for this typo? If not, I can help to create a pull request for that :).

**Comment by Lallassu** [comment]
please do, I'm not a valid contributor yet, according to the docs.
