### ISSUE TITLE
azure provider doesn't seem to handle scale sets

### ISSUE THREAD

**Issue by guoshimin** [kubernetes/kubernetes#40913]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): azure scale sets

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

**Kubernetes version** (use `kubectl version`): 1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: azure
- **OS** (e.g. from /etc/os-release): CoreOS
- **Kernel** (e.g. `uname -a`):
```
Linux k8s-agent-000001 4.7.3-coreos-r2 #1 SMP Tue Jan 31 07:55:24 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz GenuineIntel GNU/Linux
```
- **Install tools**: custom
- **Others**:

**What happened**:
Instances in a scale set can't register themselves as nodes.

**What you expected to happen**:
Instances in a scale set can register themselves.

**How to reproduce it** (as minimally and precisely as possible):
Spin up a scale set and run kubelet on the instances.

**Anything else we need to know**:
Got the following in the log:
```
Feb 03 06:55:51 k8s-agent-000001 kubelet[12410]: E0203 06:55:51.419920   12410 kubelet_node_status.go:70] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
```

**Comment by brendandburns** [comment]
Yeah, this is a known issue. The scale set API is different than the standard VM API, we need to add code for VM Scale Sets in the Azure Cloud Provider.

**Comment by vitorarins** [comment]
@brendandburns thank you for the response. Any idea when is this going to be solved?

**Comment by discordianfish** [comment]
@brendandburns Does the integration support instance in availability sets or only plain VMs in general?

**Comment by discordianfish** [comment]
Never mind, it looks like it's working with VMs in availability sets.

**Comment by sorlov-avito** [comment]
Excuse me. Do we have any progress here?

**Comment by colemickens** [comment]
cc: @jdumars

**Comment by jdumars** [comment]
Bringing up in SIG-Azure meeting to discuss.

**Comment by khenidak** [comment]
The progress on this can be tracker here https://github.com/kubernetes/kubernetes/issues/43287

**Comment by feiskyer** [comment]
@guoshimin  VMSS support is targeted at v1.10. All versions before v1.10 don't support VMSS.

**Comment by feiskyer** [comment]
Please refer #43287 for current progress of VMSS support.
