### ISSUE TITLE
fluentd-gcp container does not send journal logs to cloud-logging (on master branch)

### ISSUE THREAD

**Issue by adityakali** [kubernetes/kubernetes#40936]
Some of the recent changes in HEAD broke the systemd plugin in fluentd-gcp container and as a result, logs from system journal are not uploaded to GCL anymore on GCI/COS. 
(specifically, since PR https://github.com/kubernetes/kubernetes/pull/37681 and PR https://github.com/kubernetes/kubernetes/pull/40017) 

**What happened**:
Because of removal of libsystemd setup inside the fluentd-gcp container, the fluentd systemd plugin stopped working and logs from system journal for various services (like kubelet.service and docker.service) are not sent to cloud-logging anymore.

**What you expected to happen**:
logs from system journal for interesting services are sent to cloud-logging.

**How to reproduce it** (as minimally and precisely as possible):
Start a cluster from master branch (`hack/dev-build-and-up.sh`) on GCP. Look at logs from nodes & master in Cloud Logging Logs Viewer. Docker & Kubelet logs are missing.

**Anything else we need to know**:
* Issue is only on the master branch. Release branches (1.4.x & 1.5.x) does not seem affected.
* The e2e test (`Cluster level logging using GCL should check that logs from containers are ingested in GCL`) does not seem to catch this breakage.

cc/ @piosz @Crassirostris @kubernetes/goog-image @dchen1107

**Comment by piosz** [comment]
We should also extend our e2e tests to cover this regression.

cc @fgrzadkowski

**Comment by calebamiles** [comment]
@piosz, why is this issue a release blocker? Does it affect OSS users or only users on GCE/GKE?


**cc: @ethernetdan**

**Comment by piosz** [comment]
@calebamiles sorry. I was not aware of the definition of release blocker.

**Comment by fgrzadkowski** [comment]
GCE is OSS, so I'm confused.

Anyway, I don't see how this would change anything. If we introduce regression in a component which is released with kubernetes, then we need to fix it before the release. Would you agree @calebamiles ? Am I misinterpreting something?

**Comment by adityakali** [comment]
IMO this is indeed a release blocker.
