### ISSUE TITLE
client-go/fake should return the object it received in create and update instead of returning an empty object

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#40939]
Examples: https://github.com/kubernetes/kubernetes/blob/ab794c612853e6c6dfda63594cb5d74914e7e151/staging/src/k8s.io/client-go/kubernetes/typed/extensions/v1beta1/fake/fake_deployment.go#L49 and https://github.com/kubernetes/kubernetes/blob/ab794c612853e6c6dfda63594cb5d74914e7e151/federation/client/clientset_generated/federation_clientset/typed/extensions/v1beta1/fake/fake_deployment.go#L39.

Here the default return obj passed to `Invokes` is `&v1beta1.Deployment{}`. Why not pass the deployment object that the function received?
One of my unit test is failing which I can fix by adding a reactor that returns the object that it received, but I was expecting it to be handled by default (without needing to act a reactor).
Am I expecting it wrong?

cc @caesarxuchao @kubernetes/sig-api-machinery-misc

**Comment by smarterclayton** [comment]
We generally expect you to add reactions if you are testing return behavior.  The real client does not return the same object you passed in.

**Comment by liggitt** [comment]
Agree about requiring reactors. Returning the same object can actually lead to bugs in tests where the returned object gets mutated, mutates the original object passed in, and makes a comparison between the two meaningless.

**Comment by deads2k** [comment]
> Agree about requiring reactors. Returning the same object can actually lead to bugs in tests where the returned object gets mutated, mutates the original object passed in, and makes a comparison between the two meaningless.

That just means you'd want to deep copy it and maybe default it, not that you wouldn't return it.  I'd want to make this more like a real client, not less.  This feels similar to `Watch` not seeing `Create` for the same fake client.
