### ISSUE TITLE
iSCSI volume plugin does not rescan LUNs

### ISSUE THREAD

**Issue by cdragga** [kubernetes/kubernetes#40941]
**BUG REPORT**

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:  Bare metal
- **OS** (e.g. from /etc/os-release):  CentOS 7; reproduced in Ubuntu 14.0.4.2.
- **Kernel** (e.g. `uname -a`):  Linux centos7 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux; kernel 3.16.0-77-generic

**What happened**:
On a host where an iSCSI LUN from a given target is mounted in a pod, a user who creates a new LUN on the same target and attempts to create a pod that mounts the new LUN will fail to create the pod.  Specifically, depending on the operating system, the pod will hang in the ContainerCreating stage with either a "Could not attach disk: Timeout after 10s" error (CentOS 7) or an error about establishing a session when one already exists (Ubuntu 14).

**What you expected to happen**:
The pod should successfully mount the LUN.

**How to reproduce it** (as minimally and precisely as possible):
Given a working iSCSI target and a single node Kubernetes cluster:

1. Create a LUN on the iSCSI target
2. Create a pod that uses the LUN from step 1 (either natively or through a PV/PVC)
3. Create a new LUN on the iSCSI target (note that the target portal and IQN must be identical).
4. Create a pod that uses the LUN from step 3.

The pod created in step 4 will fail to start.

**Anything else we need to know**:

As far as I can tell, this is due to a bug with the Kubernetes iSCSI implementation.  The AttachDisk() function in pkg/volume/iscsi/iscsi_util.go first checks if the LUN exists in /dev/disk/by-path/; if it doesn't, it attempts to log in to the target and recheck for the LUN's existence (lines 123-138 in the 1.5 branch).  In this case, though, the session already exists, as it was created with the pod in step 2.  In Ubuntu, attempting to log in a second time triggers an error, which gets reported in the pod description.  In CentOS 7, this gets treated as a NOP; however, the new LUN will never become visible, and thus, the pod will fail to start.

This can be solved manually by logging into the host and running `iscsiadm -m session --rescan`.  It should be possible to fix it in Kubernetes by adding a check in AttachDisk() to see if a session already exists for the target portal and IQN and, if so, doing a rescan of the session.

**Comment by calebamiles** [comment]
Could someone from @kubernetes/sig-storage-bugs please help with triage? Thanks!
