### ISSUE TITLE
Move e2e tests involving redis, cassandra, spark, storm, etc to Charts

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#40949]
- Redis should create and stop redis servers
- Storm should create and stop Zookeeper, Nimbus and Storm worker servers
- Spark should start spark master, driver and workers
- Cassandra should create and scale cassandra
- CassandraStatefulSet should create statefulset
- RethinkDB should create and stop rethinkdb servers

k8s contributors will not necessarily have the expertise to fix/maintain these tests and once we setup e2es for charts, they'll be maintained and tested well over in the charts repo.
/cc @pwittrock @kow3ns @viglesiasce

**Comment by kow3ns** [comment]
Also, we could move the manifests that do not use charts to the contrib repo. They might serve as examples for how get started using K8s to deploy a specif type of system. e.g If someone was looking at how to contribute a Riak StatefulSet they might have a look at the Cassandra manifest to get started.

**Comment by chrislovecnm** [comment]
@foxish we have found bugs in core with e2e testing Cassandra in core.  I do not agree that all of the examples should be moved out of the e2e tests.  Also, not everyone is using helm ...

**Comment by jayunit100** [comment]
really all the examples are apps, possibly charts.
