### ISSUE TITLE
RunAsNonRoot should permit images with a non-root USER directive

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#40958]
E.g. an image built from a Dockerfile specifying
```
USER nobody:nobody
```

should be permitted to run with a security context `RunAsNonRoot: true`

/cc @kubernetes/sig-node-bugs

**Comment by liggitt** [comment]
Do we have the ability to resolve symbolic usernames be resolved to the underlying uid so we can be sure someone didn't do something clever with /etc/passwd, /etc/shadow, etc., to make "nobody" actually uid 0?

**Comment by liggitt** [comment]
It's definitely working as designed at the moment because of the symbolic->uid resolution issue

**Comment by liggitt** [comment]
Cc @pweil-

**Comment by pweil-** [comment]
> t's definitely working as designed at the moment because of the symbolic->uid resolution issue

Right, it was intended to only use numeric names because of this.

**Comment by timstclair** [comment]
So not a simple fix, but should still be doable? Is it feasible for the Kubelet to resolve the symbolic user, or will we need to delegate to the CRI runtime? (/cc @yujuhong ). To prevent unaccounted for edge cases, the Kubelet (runtime) should set the uid to the resolved uid in that case (only if RunAsNonRoot is set).

**Comment by yujuhong** [comment]
Right now the [`ImageStatus` in CRI](https://github.com/kubernetes/kubernetes/blob/v1.6.0-alpha.1/pkg/kubelet/api/v1alpha1/runtime/api.proto#L854) simply returns the user/uid specified in the image metadata. It is possible to teach dockershim to check the `/etc/passwd`, etc., in the image rootfs to resolve the mapping, but it seemed to heavy-handed/hacky so we chose not to do it. If there is a need for this, we can revisit the decision.

**Comment by davinkevin** [comment]
This issue has been closed but this could be an important evolution. 

The current implementation force use to define a `USER 65532` directive in our base image to be able to use PSP with `RunAsNonRoot`. Our image are based on `distroless`, so if for some reason the user ID change, we can face issues…

Is there a way to reopen it because the issue is still happening ?
