### ISSUE TITLE
CRI GCE e2e Port forwarding over websockets failed

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#40965]
All port forwarding over websockets tests failed in CRI GCE e2e tests, e.g. [here](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-cri-gce/2415)

- [k8s.io] Port forwarding [k8s.io] With a server listening on 0.0.0.0 should support forwarding over websockets
- [k8s.io] Port forwarding [k8s.io] With a server listening on localhost should support forwarding over websockets

Maybe related with #32880.

cc @yujuhong @kubernetes/sig-node-bugs

**Comment by fraenkel** [comment]
Fix in https://github.com/kubernetes/kubernetes/pull/40951

**Comment by yujuhong** [comment]
Fixed in #40951

**Comment by rpothier** [comment]
Is this expected to work on a local cluster? I'm seeing the port forwarding tests hang with a local cluster.
