### ISSUE TITLE
`kubectl run` supports more options for deployment than `kubectl create deployment`

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#40961]
`kubectl create deployment` and `kubectl run` are both supposed to support the same options for creating a deployment.  `kubectl run` is meant to be a little more discoverable for docker users, but provide the exact same functionality.

We need to bring the 2 in parity.

**Note:**
- Common flags should be factored into a common structure consumed by both
- Business logic should be factored into a common library invoked by both
- `kubectl run` supports jobs, pods, etc so the two are not exactly the same.

Once this is done for deployment, we should do something similar for factoring out job and pod.

cc @kubernetes/sig-cli-bugs 

@karsinkk This seems like a good one to get started on.  @jessfraz will be your point of contact.

@jessfraz Would you shepherd @karsinkk on this issue?

**Comment by liggitt** [comment]
I thought the intent of the create commands was to support a minimal set of options that produce objects that can be further modified, not support every possible option in the object. The run command was considerably less focused, and I don't think the create command intended to replicate it.

**Comment by liggitt** [comment]
See original discussion in the PR establishing the `kubectl create [resource]` pattern https://github.com/kubernetes/kubernetes/pull/16028

cc @deads2k

**Comment by liggitt** [comment]
And https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#create-commands

**Comment by AdoHe** [comment]
>I thought the intent of the create commands was to support a minimal set of options that produce >objects that can be further modified, not support every possible option in the object. The run >command was considerably less focused, and I don't think the create command intended to >replicate it.

I agree. This should be the basic principle.
