### ISSUE TITLE
kubectl UX: make it easy to switch namespaces

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#40968]
The UX for using kubectl with multiple namespaces is harder than it need be, and I don't understand why.

Per https://kubernetes.io/docs/user-guide/namespaces/

`kubectl config set-context $(kubectl config current-context) --namespace=myns`

Can we have `kubectl namespace myname` or similar?

Other ideas:

* `kubectl use ns myns` (and `kubectl use cluster myothercluster`) 
* `kubectl use myothercluster/myns`

I believe OpenShift also calls namespaces projects; we could adopt the same terminology.  They have `kubectl project myns`.

cc @kubernetes/sig-cli-feature-requests

**Comment by smarterclayton** [comment]
I do like "use" or "switch".  The openshift "project" call is overloaded
for both view and set, which can cause confusion (although is convenient
for experienced users).

I agree that we should have a simple command that changes the namespace for
the current context - it's ok for it to be namespace based.

We should think a bit about whether the verb we pick would

a. have any other things to alter for the local user (switch user, switch
cluster, switch context)
b. ever overlap with a use case we might want as a cluster action

**Comment by shiywang** [comment]
I think "switch" is good, vote for "switch", I would like to work on this when I finished `apply subcommand` @pwittrock @ymqytw WDYT?

**Comment by liggitt** [comment]
I prefer use. It connects to the current context selection command (`use-context`), pairs nicely with a resource arg (`use namespace/foo` or `use ns/foo`), and reminds me of selecting a current database (`use database_name`)

If we start by requiring the resource type qualifier (`use namespace/foo` or `use ns/foo`), that leaves the door open for other types of context in the future

**Comment by smarterclayton** [comment]
Would we want to have "use user"?  Cause that doesn't roll off the tongue

On Feb 7, 2017, at 8:54 PM, Jordan Liggitt <notifications@github.com> wrote:

I prefer use. It connects to the current context selection command (
use-context), pairs nicely with a resource arg (use namespace/foo or use
ns/foo), and reminds me of selecting a current database (use database_name)

If we start by requiring the resource type qualifier (use namespace/foo or use
ns/foo), that leaves the door open for other types of context in the future

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/40968#issuecomment-278205277>,
or mute the thread

**Comment by AdoHe** [comment]
>If we start by requiring the resource type qualifier (use namespace/foo or use ns/foo), that leaves >the door open for other types of context in the future

sounds reasonable to me. I think `use` should be more appropriate here.

**Comment by fabianofranz** [comment]
> If we start by requiring the resource type qualifier (use namespace/foo or use ns/foo), that leaves the door open for other types of context in the future

I like it for that specific use case and it feels fluid, but I worry that it might cause confusion when using it for things that are not actual resource types. 

E.g. `use context/stage` or `use cluster/aws`, where `cluster` *is* a resource type in Federation, but that's not what we are referring to here. Maybe part of why it feels odd to me is `use` being a first-level cmd, while `config use` makes it clear what it refers to.

**Comment by smarterclayton** [comment]
We should be careful about overlapping the resource identifier syntax
(resource/name) with things things that are not resources.

Contexts, users, and servers are not resources.  I would be against mixing
the two - and prefer "config use namespace foo", "use namespace foo", or
"config use --namespace=foo", to anything that puts non resources in
resource spots.

On Feb 17, 2017, at 1:39 PM, Fabiano Franz <notifications@github.com> wrote:

If we start by requiring the resource type qualifier (use namespace/foo or
use ns/foo), that leaves the door open for other types of context in the
future

I like it for that specific use case and it feels fluid, but I worry that
it might cause confusion when using it for things that are not actual
resource types.

E.g. use context/stage or use cluster/aws, where cluster *is* a resource
type in Federation, but that's not what we are referring to here. Maybe
part of why it feels odd to me is use being a first-level cmd, while config
use makes it clear what it refers to.

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/40968#issuecomment-280731321>,
or mute the thread

**Comment by AdoHe** [comment]
```
prefer "config use namespace foo", "use namespace foo", or
"config use --namespace=foo", to anything that puts non resources in
resource spots.
```
I prefer this too. We can even use `config use-ns off`. wdyt?

**Comment by smarterclayton** [comment]
That's probably the easiest right now and bypasses the harder agreement on
allocating a new top level verb.  I'm in favor

On Mar 5, 2017, at 9:58 AM, TonyAdo <notifications@github.com> wrote:

prefer "config use namespace foo", "use namespace foo", or
"config use --namespace=foo", to anything that puts non resources in
resource spots.

I prefer this too. We can even use config use-ns off. wdyt?

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/40968#issuecomment-284233308>,
or mute the thread

**Comment by shiywang** [comment]
@smarterclayton @AdoHe  so `config use-ns`  ? if we had a deal on this command name, I would like to implement this feature.

**Comment by smarterclayton** [comment]
I think config `use-ns` is pretty clearly consistent with our other config commands.

**Comment by jbeda** [comment]
Hoisting comment from https://github.com/kubernetes/kubernetes/pull/45466#issuecomment-300534988 here.

> I think it is worthwhile to talk about the name here to be more consistent here.  Why is this `use-ns` vs. `set-namespace`?  Do we have a principled view of use vs. set here?
>
> We should make it clear from the naming that this is a specialization of set-context.  `kubectl config set-context namespace foo`? `kubectl config set-context-namespace foo`?
>
> I hesitate to put "context" in the command name at all here as it is super verbose.  I think the core problem is that no one really understands the context concept at all.  Most people just treat a `kubeconfig` file as the thing and don't view it as a specialized database of cluster/auth/namespace/context.

I 100% agree that this is worth fixing and is a hole.  Some constraints:

* It should be under `kubectl config` as that is where all of the commands for manipulating your config exist.
* We have 3 nouns in that command right now -- clusters, contexts and credentials.  
  * In the kubeconfig file we have users, but in the CLI we call that credentials.
* The current set of commands are incredibly inconsistent.  We have `set` and `unset` that take paths.  But `kubectl config view` doesn't.  The docs instead tell you to use jsonpath.  jsonpath is a slightly different syntax than the syntax used for set/unset.

I'm not sure how to add to this mess without making it worse.

I suggest the command be `kubectl config set-context-namespace <ns>`.  This is verbose but nests well in the rest of the config commands and it is clear that we are modifying the context vs. setting a top level object.  Tab completion will help users that do this a lot.

I also suggest that someone take the task of rationalizing this and making this part of the kubectl UI more self explanatory.  That may mean deprecating the old commands.

**Comment by jbeda** [comment]
Another option would be to make the context name optional on `kubectl config set-context`.  If it isn't specified then just default to the current context.

The behavior in question then becomes: `kubectl config set-context --namespace=ns`.

**Comment by AnthonyWC** [comment]
Is there any reason why it couldn't be `kubectl set ns`?  (well at least that's what i have alias it as..)

**Comment by liggitt** [comment]
the `kubectl set ...` family of commands is oriented at setting a field of an API object. `kubectl config ...` is oriented toward kubeconfig manipulation

**Comment by smarterclayton** [comment]
`kubectl config set-ns` seems more practical, in that 99% of the time the
only thing users are going to change about their current context is the
namespace.  I would expect that to be the #1 command invoked from within
config by far.

**Comment by debianmaster** [comment]
this is a much needed feature!   i like how  `openshift` does  `oc project <projectname>` its hard with k8s

**Comment by Asher256** [comment]
+1

**Comment by jiaqingw** [comment]
gleaming over the comments above, IMHO, why not just use an environment variable such as

KUBECTL_NS=myns kubectl ....

**Comment by shiywang** [comment]
> `kubectl config set-ns` seems more practical, in that 99% of the time the
only thing users are going to change about their current context is the
namespace.  I would expect that to be the #1 command invoked from within
config by far.

sounds good, will continue working on my pr next week.

> I also suggest that someone take the task of rationalizing this and making this part of the kubectl UI more self explanatory. That may mean deprecating the old commands.

I will create an issue for this.

**Comment by lizrice** [comment]
Have you seen [kubectx and kubens](https://github.com/ahmetb/kubectx)?

**Comment by SerialVelocity** [comment]
@shiywang Will there also be an option for "all namespaces" to be the default?

**Comment by cwingrav** [comment]
Completely agree about toggling contexts. While not helpful to the CLI UX, for mac users, I suggest a bit of AppleScript to open a popup that shows the current context and then a menu selector to toggle the context. Hopefully this isn't too off-topic:

This is AppleScript. I activate it via (shift-cmd-x) via FastScripts (set a key combo). Place this AppleScript in this directory: $(HOME)/Library/Scripts/Applications/Terminal).

    use AppleScript version "2.4" -- Yosemite (10.10) or later
    use scripting additions

    do shell script "/usr/local/bin/kubectl config current-context"
    set curcontext to result

    do shell script "/usr/local/bin/kubectl config get-contexts -o name"
    set contexts to paragraphs of result

    choose from list contexts with prompt "Select Context:" with title "K8s Context Selector" default items {curcontext}
    set scriptArguments to item 1 of result

    do shell script "/usr/local/bin/kubectl config use-context " & scriptArguments

    display dialog "Switched to " & scriptArguments buttons {"ok"} default button 1

**Comment by shiywang** [comment]
thanks for all this feedback, will take a look this tomorrow : )

**Comment by kvaps** [comment]
bash aliases can help here:
```
$ alias kubectl='kubectl -n mynamespace'
```

**Comment by dfontenot** [comment]
+1 to @jiaqingw comment about an environment variable

**Comment by pp010** [comment]
Hey, can anyone please suggest how to set a namespace in kubectl. Currently i am using 

> kubectl --namespace=my-namespace get deployments

i have to specify namespace for every command i execute. So is there anyway to set this once for all? Thanks in advance!!

**Comment by christian-posta** [comment]
that really sucks. what happened to @smarterclayton suggestion of `kubectl config set-ns` ?

**Comment by smarterclayton** [comment]
We should really get set-ns in place.  It's just an oversight.

**Comment by debianmaster** [comment]
please make this happen!

**Comment by liggitt** [comment]
> We should really get set-ns in place. It's just an oversight.

or let you pass `--current-context` in lieu of a name to set-context, which would let you set any of the fields in the current context, not just namespace

```
kubectl config set-context --current-context --namespace=some-namespace
kubectl config set-context --current-context --cluster=some-cluster
kubectl config set-context --current-context --user=some-user
```

**Comment by YacheLee** [comment]
By reading the book: https://www.manning.com/books/kubernetes-in-action, I add the alias
`alias kcd='kubectl config set-context $(kubectl config current-context) --namespace '`
Then, every time I switch the namespace by `kcd production`

**Comment by funky81** [comment]
Will this request fullfil by k8s teams?

**Comment by juanvallejo** [comment]
Not sure how much this addresses the initial problem, but the new plugins example repo will add functionality similar to the one being described here: https://github.com/kubernetes/kubernetes/pull/67729

With the sample plugin, you'll be able to point to a new namespace without having to specify the `--namespace` flag in every command, or the need to export an environment var:

```
$ kubectl ns default
namespace changed to "default"

# ensure we are getting resources from that namespace
$ kubectl get pod --template='{{(index .items 0).metadata.namespace}}'
default%
```

**Comment by DanyC97** [comment]
coming from openshift world i am surprised that yet there is no progress on the suggestion made by @smarterclayton . Okay i get we have other tools or new kubectl plugins however it can't beat having s'thing inside the cli ...

**Comment by mxplusb** [comment]
I'd be okay with something like `kubectl config change-namespace <target-ns>`, if that's an option.

**Comment by aakarshg** [comment]
echo the opinion shared by @DanyC97. This feels like a good add to cli without having to depend on other tools or plugins.
