### ISSUE TITLE
 KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT weren't set in pod env

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#40973]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
GKE

**What happened**:

KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT weren't set in pod env.

**What you expected to happen**:

KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT should be set by default in pod.

**How to reproduce it** (as minimally and precisely as possible):

Create in-cluster client in a pod.

This isn't easily reproducible. We encountered this issue when running extensive e2e tests and the logs showed that a pod crashed due to:
```
panic: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
```

**Comment by hongchaodeng** [comment]
@dchen1107 @Random-Liu 
Potential node issue?

**Comment by liggitt** [comment]
cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Seeing this intermittently as you say, in Origin e2e CI. 

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2+43a9be4", GitCommit:"43a9be4", GitTreeState:"clean", BuildDate:"2017-02-07T16:24:34Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by stevekuznetsov** [comment]
@pmorie was thinking this may be symptomatic of the `kubernetes` service not actually starting.

**Comment by stevekuznetsov** [comment]
This is occurring with pretty high incidence in our CI -- is someone from @kubernetes/sig-node-bugs assigned to triage this?

**Comment by resouer** [comment]
@hongchaodeng When generating ENVs for container, there is a known race that kubelet may generate ENV before service is started. 

See this: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L412-L416

May be we should make `client-go` retry for more times?

**Comment by xiang90** [comment]
@resouer 

> May be we should make client-go retry for more times?

I feel this is more like a workaround. This bug should be fixed.

**Comment by calebamiles** [comment]
ping, @kubernetes/sig-node-bugs can we come up with a plan for either fixing the race condition in the kublet or are we planning on changing client-go @kubernetes/sig-api-machinery-misc?

**Comment by shiywang** [comment]
met same problem,  do we have a workaround here ?
```console
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.4.914+b9e8d2aee6d593", GitCommit:"b9e8d2aee6d59330306cb458c1241f5e2578c40b", GitTreeState:"clean", BuildDate:"2017-06-02T04:13:59Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.4.914+b9e8d2aee6d593", GitCommit:"b9e8d2aee6d59330306cb458c1241f5e2578c40b", GitTreeState:"clean", BuildDate:"2017-06-02T04:13:59Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
2017/06/02 04:51:34 util.go:131: Step './hack/e2e-internal/e2e-status.sh' finished in 117.680893ms
2017/06/02 04:51:34 util.go:129: Running: ./hack/ginkgo-e2e.sh --ginkgo.focus=ThirdParty
Setting up for KUBERNETES_PROVIDER="local".
Local doesn't need special preparations for e2e tests
Jun  2 04:51:34.868: INFO: >>> kubeConfig: 
Jun  2 04:51:34.868: INFO: failed to load config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
panic: 
```

**Comment by qiujian16** [comment]
met the same problem, especially when we reboot the master node.

**Comment by StevenACoffman** [comment]
So this is biting us with some regularity, so I assume there is a recommended workaround. Any tips?

It is sometimes problematic to override environment variables in pod definitions as an IP address is expected by some things:
```yaml
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: "kubernetes.default.svc.cluster.local"
        - name: KUBERNETES_SERVICE_PORT
          value: "443"
```
I'm wondering if the IP address is available somewhere else? Downward API volume file? 
Also, it would be great if there was some way to make the env override conditional on it not already existing.

**Comment by stevekuznetsov** [comment]
We worked around this by polling until the `kubernetes` service in namespace `default` was up and running before launching our pods.

**Comment by smarterclayton** [comment]
Re: conditional, we are unlikely to that because we want to move to
explicit service env vars.

What doesn't expect IPs?  Nothing about _HOST promises not to be a
name, so anything in Kube or it's ecosystem should fix assumptions
like that (please help us open bugs for that wherever you've hit
that).

**Comment by cben** [comment]
About API clients: should they use/recommend using `KUBERNETES_SERVICE_HOST` / `KUBERNETES_SERVICE_PORT` env vars, or `kubernetes.default` dns?

Sounds like `kubernetes.default` dns can avoid sensitivity to this issue. (still needs API to be up by the time actual request is made, of course).

https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#accessing-the-api-from-a-pod document only talks of `kubernetes.default` dns.
Sampling some clients, I see they currently use the env vars:
https://github.com/kubernetes/client-go/blob/2f45bcbf57f0cfde510a33e7d94a4c89955ff17b/rest/config.go#L313
https://github.com/kubernetes-client/python-base/blob/a41c44715241552de73361673152f3f0d0bb9bc4/config/incluster_config.py#L21
https://github.com/kubernetes-client/ruby/blob/7f0dce507ca12627dc25501c161d4dc569faa844/kubernetes/lib/kubernetes/config/incluster_config.rb#L22

Coming here from https://github.com/abonas/kubeclient/pull/316 where we're about to recommend `kubernetes.default`, unless told otherwise.

**Comment by cben** [comment]
Another official doc: https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod
Mostly same with different wording; one difference is this doc recommends "`kubernetes` DNS name" rather than `kubernetes.default`.  Does bare `kubernetes` work from pods in a different namespace?
I want to link to one of these docs from kubeclient docs, which one is better?

**Comment by liggitt** [comment]
> Does bare kubernetes work from pods in a different namespace?

No. You should use the most qualified name you can, e.g. `kubernetes.default.svc`

**Comment by thockin** [comment]
I have not heard of this in a long time.  Reopen if we can get a repro...

**Comment by alwell-kevin** [comment]
I am experiencing this issue while attempting to create a kubernetes cluster with eks.

`<user>@User-MBP ~/Desktop/solutions-engineering/jx-sandbox $ jx create cluster eks --cluster-name=cloud-bees-jx-quickstart --skip-installation=true
? Missing required dependencies, deselect to avoid auto installing: eksctl, heptio-authenticator-aws, kubectl, helm
Installing eksctl
Downloading https://github.com/weaveworks/eksctl/releases/download/0.1.32/eksctl_Darwin_amd64.tar.gz to /Users/<user>/.jx/bin/eksctl.tar.gz...
Downloaded /Users/<user>/.jx/bin/eksctl.tar.gz
Installing heptio-authenticator-aws
Downloading https://<region>/1.10.3/2018-06-05/bin/darwin/amd64/heptio-authenticator-aws to /Users/<user>/.jx/bin/heptio-authenticator-aws...
Downloaded /Users/<user>/.jx/bin/heptio-authenticator-aws
Installing kubectl
Downloading https://storage.googleapis.com/kubernetes-release/release/v1.13.2/bin/darwin/amd64/kubectl to /Users/<user>/.jx/bin/kubectl...
Downloaded /Users/<user>/.jx/bin/kubectl
Installing helm
Installing helm secrets plugin`
**WARNING: Failed to retrieve team settings: failed to create the jx client: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined - falling back to default settings...**
`Creating EKS cluster - this can take a while so please be patient...
You can watch progress in the CloudFormation console: https://console.aws.amazon.com/cloudformation/`

Following [this](https://aws.amazon.com/blogs/opensource/continuous-delivery-eks-jenkins-x/) tutorial.

cc: @thockin

**Comment by peter-wangxu** [comment]
met this issue with following versions:
Kubernetes v1.12.3

**Comment by virendrasuryavanshi** [comment]
Getting the same issue:
Kubernetes v1.18.10
