### ISSUE TITLE
kube-proxy failed to record events

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#40979]
**Is this a BUG REPORT or FEATURE REQUEST? (choose one):**
bug

**Kubernetes version (use kubectl version):**
master

**What happened:**

Found error again in latest code:

```
E0203 06:40:04.508992       1 event.go:259] Could not construct reference to: '&v1.ObjectReference{Kind:"Node", Namespace:"", Name:"k8s-master", UID:"k8s-master", APIVersion:"", ResourceVersion:"", FieldPath:""}' due to: 'object does not implement the List interfaces'. Will not report event: 'Normal' 'Starting' 'Starting kube-proxy.'
```

**What you expected to happen:**

No errors

**How to reproduce it (as minimally and precisely as possible):**

```
# ./hack/local-up-cluster.sh
# grep "^E" /tmp/kube-proxy.log  | head
```

cc @kubernetes/sig-network-misc

**Comment by k82cn** [comment]
cc @deads2k / @smarterclayton

**Comment by deads2k** [comment]
Thanks.  Looks like fallout from making client-go authoritative on event recorder.

**Comment by k82cn** [comment]
@deads2k, yes, had created a PR (#40980) for it; could you help to review?
