### ISSUE TITLE
BUG REPORT:  Clean new install on CentOS7x "kubeadm init" won't run without adding --skip-preflight-checks

### ISSUE THREAD

**Issue by ernestgwilsonii** [kubernetes/kubernetes#40987]
BUG REPORT

Clean / new install(s) on CentOS7x "**kubeadm init**" won't run without adding **--skip-preflight-checks**

**Kubernetes version** (use `kubectl version`):
kubectl version
**Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:19:49Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}**
The connection to the server localhost:8080 was refused - did you specify the right host or port?

kubelet --version
**Kubernetes v1.4.1**

**Environment**:
- **Cloud provider or hardware configuration**:
New clean install of Centos7x

- **OS** (e.g. from /etc/os-release):
cat /etc/redhat-release
**CentOS Linux release 7.3.1611 (Core)**

- **Kernel** (e.g. `uname -a`):
uname -a
**Linux VA1EWTKTC02 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux**

**What happened**:
Following official guide here:
https://lukemarsden.github.io/docs/getting-started-guides/kubeadm/
Near the top section of the guide, when using CentOS7x and the command outlined in the guide is:
**kubeadm init --use-kubernetes-version v1.4.0-beta.11**
kubeadm init fails to complete and an error is displayed on screen:
Running pre-flight checks
preflight check errors:
        /etc/kubernetes is not empty

**What you expected to happen**:
kubeadm init
should have completed init without barfing

**How to reproduce it** (as minimally and precisely as possible):
Start with any typical minimal clean CentOS7x OS install.
Follow this official guide:
https://lukemarsden.github.io/docs/getting-started-guides/kubeadm/
Following the guide and **kubeadm init** won't run without adding **--skip-preflight-checks**

Published command in guide:
**kubeadm init --use-kubernetes-version v1.4.0-beta.11**

Results in:
**Running pre-flight checks
preflight check errors:
        /etc/kubernetes is not empty**

**Anything else we need to know**:

**1.)**
This is a clean install, why is an empty "**manifests**" directory being added during yum install?
If the "pre-flight" check is looking to see if anything is in:
/etc/kubernetes
then yup, fail, an empty manifests directory was added during yum install.

 **ll /etc/kubernetes**
total 4
drwxr-xr-x 2 root root 4096 Oct 25 12:33 **manifests**

ll /etc/kubernetes/**manifests**/
total 0

**PROPOSED SOLUTION:**
a.) Don't have an empty manifests directory added during yum install
or
b.) Have kubeadm init ignore empty manifests directory during preflight-checks

**TEMPORARY WORKAROUND:**
Have kubeadm init **skip preflight-checks** via:
**kubeadm init --skip-preflight-checks**

**2.)**
The "guide" says:
kubeadm init **--use-kubernetes-version v1.4.0-beta.11**
REF: https://lukemarsden.github.io/docs/getting-started-guides/kubeadm/
but
yum installs Kubernetes **1.4.1**
so specifying beta **v1.4.0-beta.11**
seems like a bad idea.
In the short term, I went with:
**kubeadm init --skip-preflight-checks**

**Comment by luxas** [comment]
This issue is now obsolete. The issues here have been fixed with newer releases.
