### ISSUE TITLE
BUG REPORT:  Clean new install on CentOS7x "kube-dns" is stuck at status "ContainerCreating"

### ISSUE THREAD

**Issue by ernestgwilsonii** [kubernetes/kubernetes#40988]
BUG REPORT

Clean / new install(s) on CentOS7x **kube-dns** is stuck at status **ContainerCreating**

**Kubernetes version** (use `kubectl version`):
kubectl version
**Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:19:49Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}**
The connection to the server localhost:8080 was refused - did you specify the right host or port?

kubelet --version
**Kubernetes v1.4.1**

**Environment**:
- **Cloud provider or hardware configuration**:
New clean install of Centos7x

- **OS** (e.g. from /etc/os-release):
cat /etc/redhat-release
**CentOS Linux release 7.3.1611 (Core)**

- **Kernel** (e.g. `uname -a`):
uname -a
**Linux VA1EWTKTC02 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux**

**What happened**:
Following official guide here:
https://lukemarsden.github.io/docs/getting-started-guides/kubeadm/
Following the guide, when using CentOS7x, **kube-dns** is stuck at status **ContainerCreating**

**kubectl get pods --all-namespaces -o wide**
NAMESPACE     NAME                                  READY     STATUS              RESTARTS   AGE       IP              NODE
kube-system   dummy-2088944543-hvfbq                1/1       Running             0          1m        10.127.215.21   va1ewtktq01
kube-system   kube-apiserver-va1ewtktq01            1/1       Running             0          1m        10.127.215.21   va1ewtktq01
kube-system   kube-controller-manager-va1ewtktq01   1/1       Running             0          1m        10.127.215.21   va1ewtktq01
kube-system   kube-discovery-982812725-dq2vo        1/1       Running             0          1m        10.127.215.21   va1ewtktq01
kube-system   kube-dns-2247936740-o2fa5             0/3       **ContainerCreating**   0          1m        <none>          va1ewtktq01
kube-system   kube-proxy-amd64-czs6v                1/1       Running             0          35s       10.127.215.22   va1ewtktq02
kube-system   kube-proxy-amd64-ip48d                1/1       Running             0          1m        10.127.215.21   va1ewtktq01
kube-system   kube-proxy-amd64-yoobi                1/1       Running             0          24s       10.127.215.23   va1ewtktq03

**What you expected to happen**:
On a clean install, I'd expect **kube-dns** to come into a **Running** status and **not get stuck** at **ContainerCreating**

**How to reproduce it** (as minimally and precisely as possible):
Start with any typical minimal clean CentOS7x OS install.
Follow this official guide:
https://lukemarsden.github.io/docs/getting-started-guides/kubeadm/
kubeadm init --skip-preflight-checks
then
kubectl get pods --all-namespaces -o wide
then boom kube-dns won't get to status running, instead you get status **ContainerCreating**

**Anything else we need to know**:

Don't know if these commands will help shed any light, but just in case!

**kubectl get svc**
NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   10.0.0.1     <none>        443/TCP   10m

**kubectl get nodes**
NAME          STATUS    AGE
va1ewtktq01   Ready     11m
va1ewtktq02   Ready     10m
va1ewtktq03   Ready     10m

 **kubectl get pods --all-namespaces**
NAMESPACE     NAME                                  READY     STATUS              RESTARTS   AGE
kube-system   dummy-2088944543-hvfbq                1/1       Running             0          12m
kube-system   etcd-va1ewtktq01                      1/1       Running             0          10m
kube-system   kube-apiserver-va1ewtktq01            1/1       Running             0          12m
kube-system   kube-controller-manager-va1ewtktq01   1/1       Running             0          12m
kube-system   kube-discovery-982812725-dq2vo        1/1       Running             0          12m
kube-system   kube-dns-2247936740-o2fa5             0/3       ContainerCreating   0          12m
kube-system   kube-proxy-amd64-czs6v                1/1       Running             0          11m
kube-system   kube-proxy-amd64-ip48d                1/1       Running             0          12m
kube-system   kube-proxy-amd64-yoobi                1/1       Running             0          11m
kube-system   kube-scheduler-va1ewtktq01            1/1       Running             0          10m

**kubectl describe nodes**
Name:                   va1ewtktq01
Labels:                 beta.kubernetes.io/arch=amd64
                        beta.kubernetes.io/os=linux
                        kubeadm.alpha.kubernetes.io/role=master
                        kubernetes.io/hostname=va1ewtktq01
Taints:                 dedicated=master:NoSchedule
CreationTimestamp:      Sun, 05 Feb 2017 19:11:28 +0000
Phase:
Conditions:
  Type                  Status  LastHeartbeatTime                       LastTransitionTime                      Reason                          Message
  ----                  ------  -----------------                       ------------------                      ------                          -------
  OutOfDisk             False   Sun, 05 Feb 2017 19:24:09 +0000         Sun, 05 Feb 2017 19:11:28 +0000         KubeletHasSufficientDisk        kubelet has sufficient disk space available
  MemoryPressure        False   Sun, 05 Feb 2017 19:24:09 +0000         Sun, 05 Feb 2017 19:11:28 +0000         KubeletHasSufficientMemory      kubelet has sufficient memory available
  DiskPressure          False   Sun, 05 Feb 2017 19:24:09 +0000         Sun, 05 Feb 2017 19:11:28 +0000         KubeletHasNoDiskPressure        kubelet has no disk pressure
  Ready                 True    Sun, 05 Feb 2017 19:24:09 +0000         Sun, 05 Feb 2017 19:11:28 +0000         KubeletReady                    kubelet is posting ready status
Addresses:              10.127.215.21,10.127.215.21
Capacity:
 alpha.kubernetes.io/nvidia-gpu:        0
 cpu:                                   4
 memory:                                3878920Ki
 pods:                                  110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:        0
 cpu:                                   4
 memory:                                3878920Ki
 pods:                                  110
System Info:
 Machine ID:                    f9e498f0cd51425089dfba2ffb906a5a
 System UUID:                   422D5742-6E95-801C-DDF6-08F85122D43A
 Boot ID:                       51a71062-f143-437e-a5b7-4df79634c03c
 Kernel Version:                3.10.0-327.18.2.el7.x86_64
 OS Image:                      CentOS Linux 7 (Core)
 Operating System:              linux
 Architecture:                  amd64
 Container Runtime Version:     docker://1.13.0
 Kubelet Version:               v1.4.1
 Kube-Proxy Version:            v1.4.1
ExternalID:                     va1ewtktq01
Non-terminated Pods:            (8 in total)
  Namespace                     Name                                            CPU Requests    CPU Limits      Memory Requests Memory Limits
  ---------                     ----                                            ------------    ----------      --------------- -------------
  kube-system                   dummy-2088944543-hvfbq                          0 (0%)          0 (0%)          0 (0%)          0 (0%)
  kube-system                   etcd-va1ewtktq01                                200m (5%)       0 (0%)          0 (0%)          0 (0%)
  kube-system                   kube-apiserver-va1ewtktq01                      250m (6%)       0 (0%)          0 (0%)          0 (0%)
  kube-system                   kube-controller-manager-va1ewtktq01             200m (5%)       0 (0%)          0 (0%)          0 (0%)
  kube-system                   kube-discovery-982812725-dq2vo                  0 (0%)          0 (0%)          0 (0%)          0 (0%)
  kube-system                   kube-dns-2247936740-o2fa5                       210m (5%)       210m (5%)       390Mi (10%)     390Mi (10%)
  kube-system                   kube-proxy-amd64-ip48d                          0 (0%)          0 (0%)          0 (0%)          0 (0%)
  kube-system                   kube-scheduler-va1ewtktq01                      100m (2%)       0 (0%)          0 (0%)          0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.
  CPU Requests  CPU Limits      Memory Requests Memory Limits
  ------------  ----------      --------------- -------------
  960m (24%)    210m (5%)       390Mi (10%)     390Mi (10%)
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                            -------------   --------        ------                  -------
  13m           13m             1       {kubelet va1ewtktq01}                           Normal          Starting                Starting kubelet.
  13m           12m             24      {kubelet va1ewtktq01}                           Normal          NodeHasSufficientDisk   Node va1ewtktq01 status is now: NodeHasSufficientDisk
  13m           12m             24      {kubelet va1ewtktq01}                           Normal          NodeHasSufficientMemory Node va1ewtktq01 status is now: NodeHasSufficientMemory
  13m           12m             24      {kubelet va1ewtktq01}                           Normal          NodeHasNoDiskPressure   Node va1ewtktq01 status is now: NodeHasNoDiskPressure
  12m           12m             1       {kube-proxy va1ewtktq01}                        Normal          Starting                Starting kube-proxy.

Name:                   va1ewtktq02
Labels:                 beta.kubernetes.io/arch=amd64
                        beta.kubernetes.io/os=linux
                        kubernetes.io/hostname=va1ewtktq02
Taints:                 <none>
CreationTimestamp:      Sun, 05 Feb 2017 19:12:10 +0000
Phase:
Conditions:
  Type                  Status  LastHeartbeatTime                       LastTransitionTime                      Reason                          Message
  ----                  ------  -----------------                       ------------------                      ------                          -------
  OutOfDisk             False   Sun, 05 Feb 2017 19:24:11 +0000         Sun, 05 Feb 2017 19:12:10 +0000         KubeletHasSufficientDisk        kubelet has sufficient disk space available
  MemoryPressure        False   Sun, 05 Feb 2017 19:24:11 +0000         Sun, 05 Feb 2017 19:12:10 +0000         KubeletHasSufficientMemory      kubelet has sufficient memory available
  DiskPressure          False   Sun, 05 Feb 2017 19:24:11 +0000         Sun, 05 Feb 2017 19:12:10 +0000         KubeletHasNoDiskPressure        kubelet has no disk pressure
  Ready                 True    Sun, 05 Feb 2017 19:24:11 +0000         Sun, 05 Feb 2017 19:12:20 +0000         KubeletReady                    kubelet is posting ready status
Addresses:              10.127.215.22,10.127.215.22
Capacity:
 alpha.kubernetes.io/nvidia-gpu:        0
 cpu:                                   4
 memory:                                3878920Ki
 pods:                                  110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:        0
 cpu:                                   4
 memory:                                3878920Ki
 pods:                                  110
System Info:
 Machine ID:                    f9e498f0cd51425089dfba2ffb906a5a
 System UUID:                   422D3C5A-0508-17DD-11D6-D934BA630C09
 Boot ID:                       9142ee0a-9701-4bbc-bcc9-bddb43022ef6
 Kernel Version:                3.10.0-327.18.2.el7.x86_64
 OS Image:                      CentOS Linux 7 (Core)
 Operating System:              linux
 Architecture:                  amd64
 Container Runtime Version:     docker://1.13.0
 Kubelet Version:               v1.4.1
 Kube-Proxy Version:            v1.4.1
ExternalID:                     va1ewtktq02
Non-terminated Pods:            (1 in total)
  Namespace                     Name                            CPU Requests    CPU Limits      Memory Requests Memory Limits
  ---------                     ----                            ------------    ----------      --------------- -------------
  kube-system                   kube-proxy-amd64-czs6v          0 (0%)          0 (0%)          0 (0%)          0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.
  CPU Requests  CPU Limits      Memory Requests Memory Limits
  ------------  ----------      --------------- -------------
  0 (0%)        0 (0%)          0 (0%)          0 (0%)
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                            -------------   --------        ------                  -------
  12m           12m             1       {kubelet va1ewtktq02}                           Normal          Starting                Starting kubelet.
  12m           12m             2       {kubelet va1ewtktq02}                           Normal          NodeHasSufficientDisk   Node va1ewtktq02 status is now: NodeHasSufficientDisk
  12m           12m             2       {kubelet va1ewtktq02}                           Normal          NodeHasSufficientMemory Node va1ewtktq02 status is now: NodeHasSufficientMemory
  12m           12m             2       {kubelet va1ewtktq02}                           Normal          NodeHasNoDiskPressure   Node va1ewtktq02 status is now: NodeHasNoDiskPressure
  11m           11m             1       {kubelet va1ewtktq02}                           Normal          NodeReady               Node va1ewtktq02 status is now: NodeReady
  11m           11m             1       {kube-proxy va1ewtktq02}                        Normal          Starting                Starting kube-proxy.

Name:                   va1ewtktq03
Labels:                 beta.kubernetes.io/arch=amd64
                        beta.kubernetes.io/os=linux
                        kubernetes.io/hostname=va1ewtktq03
Taints:                 <none>
CreationTimestamp:      Sun, 05 Feb 2017 19:12:21 +0000
Phase:
Conditions:
  Type                  Status  LastHeartbeatTime                       LastTransitionTime                      Reason                          Message
  ----                  ------  -----------------                       ------------------                      ------                          -------
  OutOfDisk             False   Sun, 05 Feb 2017 19:24:12 +0000         Sun, 05 Feb 2017 19:12:21 +0000         KubeletHasSufficientDisk        kubelet has sufficient disk space available
  MemoryPressure        False   Sun, 05 Feb 2017 19:24:12 +0000         Sun, 05 Feb 2017 19:12:21 +0000         KubeletHasSufficientMemory      kubelet has sufficient memory available
  DiskPressure          False   Sun, 05 Feb 2017 19:24:12 +0000         Sun, 05 Feb 2017 19:12:21 +0000         KubeletHasNoDiskPressure        kubelet has no disk pressure
  Ready                 True    Sun, 05 Feb 2017 19:24:12 +0000         Sun, 05 Feb 2017 19:12:31 +0000         KubeletReady                    kubelet is posting ready status
Addresses:              10.127.215.23,10.127.215.23
Capacity:
 alpha.kubernetes.io/nvidia-gpu:        0
 cpu:                                   4
 memory:                                3878920Ki
 pods:                                  110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:        0
 cpu:                                   4
 memory:                                3878920Ki
 pods:                                  110
System Info:
 Machine ID:                    f9e498f0cd51425089dfba2ffb906a5a
 System UUID:                   422D0363-5904-4EA0-B94F-79AFAAC0499C
 Boot ID:                       4a965625-f9f2-4a97-a5c1-260234f231a3
 Kernel Version:                3.10.0-327.18.2.el7.x86_64
 OS Image:                      CentOS Linux 7 (Core)
 Operating System:              linux
 Architecture:                  amd64
 Container Runtime Version:     docker://1.13.0
 Kubelet Version:               v1.4.1
 Kube-Proxy Version:            v1.4.1
ExternalID:                     va1ewtktq03
Non-terminated Pods:            (1 in total)
  Namespace                     Name                            CPU Requests    CPU Limits      Memory Requests Memory Limits
  ---------                     ----                            ------------    ----------      --------------- -------------
  kube-system                   kube-proxy-amd64-yoobi          0 (0%)          0 (0%)          0 (0%)          0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.
  CPU Requests  CPU Limits      Memory Requests Memory Limits
  ------------  ----------      --------------- -------------
  0 (0%)        0 (0%)          0 (0%)          0 (0%)
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                            -------------   --------        ------                  -------
  11m           11m             1       {kubelet va1ewtktq03}                           Normal          Starting                Starting kubelet.
  11m           11m             2       {kubelet va1ewtktq03}                           Normal          NodeHasSufficientDisk   Node va1ewtktq03 status is now: NodeHasSufficientDisk
  11m           11m             2       {kubelet va1ewtktq03}                           Normal          NodeHasSufficientMemory Node va1ewtktq03 status is now: NodeHasSufficientMemory
  11m           11m             2       {kubelet va1ewtktq03}                           Normal          NodeHasNoDiskPressure   Node va1ewtktq03 status is now: NodeHasNoDiskPressure
  11m           11m             1       {kubelet va1ewtktq03}                           Normal          NodeReady               Node va1ewtktq03 status is now: NodeReady
  11m           11m             1       {kube-proxy va1ewtktq03}                        Normal          Starting                Starting kube-proxy.

**kubectl -n kube-system describe pod -l name=kube-dns**
Name:           kube-dns-2247936740-o2fa5
Namespace:      kube-system
Node:           va1ewtktq01/10.127.215.21
Start Time:     Sun, 05 Feb 2017 19:11:39 +0000
Labels:         component=kube-dns
                k8s-app=kube-dns
                kubernetes.io/cluster-service=true
                name=kube-dns
                pod-template-hash=2247936740
                tier=node
Status:         Pending
IP:
Controllers:    ReplicaSet/kube-dns-2247936740
Containers:
  kube-dns:
    Container ID:
    Image:              gcr.io/google_containers/kubedns-amd64:1.7
    Image ID:
    Ports:              10053/UDP, 10053/TCP
    Args:
      --domain=cluster.local
      --dns-port=10053
    Limits:
      cpu:      100m
      memory:   170Mi
    Requests:
      cpu:              100m
      memory:           170Mi
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Liveness:           http-get http://:8080/healthz delay=60s timeout=5s period=10s #success=1 #failure=1
    Readiness:          http-get http://:8081/readiness delay=30s timeout=5s period=10s #success=1 #failure=3
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-njr5c (ro)
    Environment Variables:      <none>
  dnsmasq:
    Container ID:
    Image:              gcr.io/google_containers/kube-dnsmasq-amd64:1.3
    Image ID:
    Ports:              53/UDP, 53/TCP
    Args:
      --cache-size=1000
      --no-resolv
      --server=127.0.0.1#10053
    Limits:
      cpu:      100m
      memory:   170Mi
    Requests:
      cpu:              100m
      memory:           170Mi
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-njr5c (ro)
    Environment Variables:      <none>
  healthz:
    Container ID:
    Image:              gcr.io/google_containers/exechealthz-amd64:1.1
    Image ID:
    Port:               8080/TCP
    Args:
      -cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1:53 >/dev/null && nslookup kubernetes.default.svc.cluster.local 127.0.0.1:10053 >/dev/null
      -port=8080
      -quiet
    Limits:
      cpu:      10m
      memory:   50Mi
    Requests:
      cpu:              10m
      memory:           50Mi
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-njr5c (ro)
    Environment Variables:      <none>
Conditions:
  Type          Status
  Initialized   True
  Ready         False
  PodScheduled  True
Volumes:
  default-token-njr5c:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-njr5c
QoS Class:      Guaranteed
Tolerations:    dedicated=master:NoSchedule
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath   Type            Reason          Message
  ---------     --------        -----   ----                    -------------   --------        ------          -------
  13m           13m             1       {default-scheduler }                    Normal          Scheduled       Successfully assigned kube-dns-2247936740-o2fa5 to va1ewtktq01
  13m           0s              823     {kubelet va1ewtktq01}                   Warning         FailedSync      Error syncing pod, skipping: failed to "SetupNetwork" for "kube-dns-2247936740-o2fa5_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kube-dns-2247936740-o2fa5_kube-system(ec19c849-ebd6-11e6-a97c-000c2922d43a)\" using network plugins \"cni\": cni config unintialized; Skipping pod"

**kubectl get ep kube-dns --namespace=kube-system**
NAME       ENDPOINTS   AGE
kube-dns   <none>      14m

**Comment by luxas** [comment]
This is the expected behavior. You should install a networking solution like Weave to finish the set up of your cluster:
```
kubectl apply -f https://git.io/weave-kube-1.6
```
