### ISSUE TITLE
[Federation] Eliminate code duplication across controllers

### ISSUE THREAD

**Issue by marun** [kubernetes/kubernetes#40989]
At present there is lots of code duplication across the controllers that synchronize the member  clusters of a given federation with the desired federated state.  This issue is targeted at refactoring the controllers so they can share as much code as possible with the goal of simplifying testing and maintenance.

The original suggestion was to enable generation of the controllers, but that will be tackled separately if at all.

cc: @kubernetes/sig-federation-misc

**Comment by marun** [comment]
I'm working on this.

**Comment by liggitt** [comment]
Is it possible to use a dynamic client for federation controllers? Ideally, federating a new resource would be as easy as starting a controller and feeding it a group/version/kind (with the possibility for custom overrides for spread policies and fields that should be ignored when checking whether the federated resource was equal to the downstream resource, e.g. clusterIP for services)

**Comment by marun** [comment]
@liggitt Based on a survey of the existing controllers, I've identified 3 types of federation:

 - simple 
   - namespace, secret, configmap and daemonset
   - simple copy to member clusters
 - workload
   - replicaset and deployment
   - involves making cross-cluster scheduling decisions, which requires details of the workloads of member clusters
 - networking
   - ingress and service
   - specialized behavior involving cross-resource coordination and integration with dns

It may be possible to have the simple type of federation applied generically to a new resource, but I don't think that will work for the workload or networking types.

Where can I learn more about how to use a dynamic client?  It would be great if simple federation could be implemented as you're describing.

**Comment by nikhiljindal** [comment]
cc @mwielgus @madhusudancs 

I agree secrets, configmaps and daemonsets federated controller are the simplest. They simply copy the federated resources to underlying clusters. Namespace has special deletion logic.

Federated Informer which is used by all federated controllers except services (WIP to refactor it to use new federated informer) and cluster controller contains most common code to watch underlying clusters and send updates to them.

**Comment by madhusudancs** [comment]
Also note that DaemonSets are simple for now because there is no DaemonSet update yet. It can get a lot more complex when it gets tied into disruption budgets, forgiveness, node lifecycle and other related things (#1574). I would just start with Secrets and ConfigMaps.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#102.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
