### ISSUE TITLE
create a “Best-effort” pod and its oom score not 1000 but -999

### ISSUE THREAD

**Issue by workhardcc** [kubernetes/kubernetes#40990]
Create a deployment as below:

    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        owt: hello
        pdl: com
        app: world
        idc: xg
        add: parameters-48
      name: parameters-48
    spec:
      replicas: 2
      template:
        metadata:
          labels:
            name: parameters-48
        spec:
          containers:
          - name: mofang-web
            image: registry.cc.com/online/mofang:stable
          nodeSelector:
            node:cc

Login to node found the container's pid, then check its oom score:

    cat /proc/21606/oom_adj
    -16
    cat /proc/21606/oom_score
    0
    cat /proc/21606/oom_score_adj
    -999

According user guide page: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-qos.md, this pod should be a "Best-effort" pod, but its OOM_SCORE_ADJ not 1000 but -999.
By the way -999 means won't be oom killed.

**Comment by liggitt** [comment]
cc @derekwaynecarr

**Comment by cmluciano** [comment]
Does nodeSelector affect this at all?

**Comment by workhardcc** [comment]
@cmluciano I take nodeSelector out but the same result. All my node has enough resources.

**Comment by resouer** [comment]
I can't reproduce this on my local env. @workhardcc Are you sure you are checking the right process? How you got the PID of container?

**Comment by workhardcc** [comment]
Yeah, I also doubt about my way. 
1.`kubectl describe pod c-a-k8stest-gz01-4016391935-qcxc9`, get "Container ID"
2.login to node：
```
ps -ef| grep ef487b1d7475f32a142ece400cb53619c62937b8f8386e6071d3f652435ca975 | grep -v grep 
root      7614 13470  0 Jan20 ?        00:00:00 docker-containerd-shim ef487b1d7475f32a142ece400cb53619c62937b8f8386e6071d3f652435ca975 /var/run/docker/libcontainerd/ef487b1d7475f32a142ece400cb53619c62937b8f8386e6071d3f652435ca975 docker-runc
```
7614 is the right pid？

**Comment by resouer** [comment]
No, it's the process id of containerd. Use:

```
docker inspect containerID | grep Pid
```
