### ISSUE TITLE
scheduler extender interface enhancement to send minimal node info on the wire

### ISSUE THREAD

**Issue by sarat-k** [kubernetes/kubernetes#40991]
The current k8s scheduler extender interface is very verbose on the wire. kube-scheduler sends node information of all candidate nodes along with pod spec. The node details are very verbose and take up a lot of bandwidth (esp. if the extender is not running on the same node as kube-scheduler). For a cluster with 100s of nodes, this becomes very cpu intensive to reassemble the TCP payload. The current interface assumes that the extender is completely stateless and sends all the information. However, extenders are more likely to have their own node cache to track all available and allocated resources (outside of what k8s manages) of each node. A backward compatible way of providing this enhancement is needed to optimize the information sent to scheduler extenders. Instead of sending all the node information, sending node name should be enough in this case. A new knob in the extender config is needed to tell kube-scheduler that the extender has capability of caching nodes.

I have some changes, I can send out for review.

cc @ravigadde

**Comment by ravigadde** [comment]
@sarat-k Please go ahead and submit a PR

**Comment by sarat-k** [comment]
PR addressing this - https://github.com/kubernetes/kubernetes/pull/41119
