### ISSUE TITLE
Enhancement for init containers annotation.

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#41004]
After #38382 , the InitContainers feature was promoted go GA; but the beta annotation value will still be respected and overrides the field value. Open this issue to trace the enhancement for initContainer annotation. Sub-tasks in my mind:

- [ ] set defaults for initContainer in annotation (refer to https://github.com/kubernetes/kubernetes/pull/39713#issuecomment-277128214 for the reason of this task)
- [ ] enhance `podutil.SetInitContainersAndStatuses` based on #31026
- [ ] use `podutil.SetInitContainersAndStatuses` in `conversion.go` to avoid duplicated code (avoid code missed before removing annotation and easy to remove when graduate).

**Comment by xiangpengzhao** [comment]
@k82cn as we will remove init containers annotation in #50654, would it be ok to close this issue?
