### ISSUE TITLE
kubeadm reset error

### ISSUE THREAD

**Issue by xilabao** [kubernetes/kubernetes#41001]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.1.395+1df1ad9d34f5dc", GitCommit:"1df1ad9d34f5dce40229ac5d82b1ab94c559d443", GitTreeState:"clean", BuildDate:"2017-02-06T07:11:51Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.1", GitCommit:"424a0e9e827a39c714ee03e1891c43635adabcdc", GitTreeState:"clean", BuildDate:"2017-01-31T02:31:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:
```
# ./cluster/kubeadm.sh reset
[preflight] Running pre-flight checks
[reset] Draining node: "ubuntu"
[reset] Failed to cleanup node: [failed to drain node "ubuntu": exit status 1]
[reset] Stopping the kubelet service
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] Removing kubernetes-managed containers
[reset] Deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/etcd]
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/ca.crt]
```

**Comment by calebamiles** [comment]
@luxas, could you please take a look? Thanks!
