### ISSUE TITLE
MULTIZONE support in AWS is broken (1.5.2)

### ISSUE THREAD

**Issue by unbornchikken** [kubernetes/kubernetes#41010]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): EntityAlreadyExists, IAM Role

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Doing this guide in AWS: https://kubernetes.io/docs/admin/multiple-zones/

On the second step (*Add more nodes in a second zone*) when I try to add minions to another availability zone I get:

```bash
Using subnet CIDR override: 172.20.1.0/24
... Starting cluster in eu-central-1b using provider aws
... calling verify-prereqs
... calling verify-kube-binaries
... calling kube-up
Starting cluster using os distro: jessie
Uploading to Amazon S3
+++ Staging server tars to S3 Storage: bimbo-stuff/devel
upload: ../../../tmp/kubernetes.RoHxUv/s3/bootstrap-script to s3://bimbo-stuff/devel/bootstrap-script
Uploaded server tars:
  SERVER_BINARY_TAR_URL: https://s3-eu-central-1.amazonaws.com/bimbo-stuff/devel/kubernetes-server-linux-amd64.tar.gz
  SALT_TAR_URL: https://s3-eu-central-1.amazonaws.com/bimbo-stuff/devel/kubernetes-salt.tar.gz
  BOOTSTRAP_SCRIPT_URL: https://s3-eu-central-1.amazonaws.com/bimbo-stuff/devel/bootstrap-script
Creating master IAM profile: kubernetes-master-bimbo-kubernetes-vpc
Creating IAM role: kubernetes-master-bimbo-kubernetes-vpc

An error occurred (EntityAlreadyExists) when calling the CreateRole operation: Role with name kubernetes-master-bimbo-kubernetes-vpc already exists.
```

This guy has already reported this issue: https://github.com/kubernetes/kubernetes/issues/39917 but closed it as fixed, but I cannot find the fix in any of the active branches.

**Kubernetes version** (use `kubectl version`): v1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): jessie
- **Kernel** (e.g. `uname -a`): Linux BST-Ubuntu 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubectl
- **Others**:

**What happened**:

kube-up.sh reported an error when I tried to add minions to other zone doing 2nd step (*Add more nodes in a second zone*) of this guide: https://kubernetes.io/docs/admin/multiple-zones/

**What you expected to happen**:

Minions up and going in the other zone.

**How to reproduce it** (as minimally and precisely as possible):

Do your own guide step by step with kubernetes v1.5.2: https://kubernetes.io/docs/admin/multiple-zones/

**Anything else we need to know**:

**Comment by calebamiles** [comment]
@chrislovecnm, could you please help route this issue? Thanks!

**Comment by chrislovecnm** [comment]
@calebamiles kube-up.sh is being depreciated :( Are you using that to install?  I recommend using a tool like kops or coreos' tool.

**Comment by unbornchikken** [comment]
@chrislovecnm I'm just a newcomer who try to get familiar with your platform by doing the guides of your documentation: https://kubernetes.io/docs/admin/multiple-zones/

So my question is, where can I find an *actual* guide about how should I set up a multizone cluster in AWS, please?

Is this guide: https://github.com/kubernetes/kops/blob/master/docs/aws.md
And this command: https://github.com/kubernetes/kops/blob/master/docs/advanced_create.md

actual?

If the answer is yes, then please update your documentation, because it's very misleading right now.

**Comment by chrislovecnm** [comment]
There are multiple tools for an install, and I agree the documentation needs some TLC. 

https://github.com/kubernetes/kops/blob/master/docs/aws.md is one of your best options.  There are others out there as well.

**Comment by unbornchikken** [comment]
Ok, that worked, thanks. Do you wanna add documentation label to this issue, or should I close it for good?

**Comment by chrislovecnm** [comment]
It is in the wrong repo for docs issue.  If you want to add an issue to the https://github.com/kubernetes/kubernetes.github.io that would be awesome!  Otherwise please close

**Comment by calebamiles** [comment]
closing per discussion
