### ISSUE TITLE
Allow Updating StatefulSet's entire PodTemplateSpec

### ISSUE THREAD

**Issue by devnev** [kubernetes/kubernetes#41015]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

statefulset updates

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

feature request

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

Updating the pod annotations on a statefulset is currently not possible: kubectl apply produces an error like:
```
The StatefulSet "statefulset-name-here" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas' are forbidden.
```

To actually change the annotations, the statefulset must be destroyed and recreated. This will lose (to my understanding) the storage claims of the StatefulSet, so is not a clean update mechanism.

Could the entire PodTemplateSpec be made mutable, instead of just the container array?

**Comment by calebamiles** [comment]
Could someone from @kubernetes/sig-api-machinery-misc please help qualify this feature request? Thanks!

**Comment by deads2k** [comment]
> Could someone from @kubernetes/sig-api-machinery-misc please help qualify this feature request? Thanks!

This is for @kubernetes/sig-apps-feature-requests .  API machinery provides mechanisms for individual API owners to decide what should and should not be mutable.

**Comment by kow3ns** [comment]
@devnev You are correct in that the only fields for a StatefulSet that can be updated are replicas and containers [see this](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/validation/validation.go#L101-L123), but deleting a StatefulSet will not cause a cascading delete of the PVCs and PVs generated for the Pods. You can use a non-cascading delete of the StatefulSet to delete only the StatefulSet and not its Pods. You can then recreate the StatefulSet which will  adopt the Pods created by the previous StatefulSet. The newly created StatefulSet will not, however, mutate the adopted Pods to apply the new annotations, you'd still have to manually delete each Pod and let the new StatefulSet recreate it. This approach is also not a "seemless" update and we working toward a better solution  is a priority on our agenda.

**Comment by foxish** [comment]
To add to what @kow3ns said, allowing modification of the template spec without outlining a good update strategy for the pods themselves can lead to situations where pods created after the template spec was changed have totally different properties from those created prior to modification of the spec. It is currently locked down to avoid surprising the user with situations like these.

**Comment by Jan-M** [comment]
While this topic is on updating everything one step in the right direction for us would be to allow the modification of the volume claim template, too. We are currently building a PostgreSQL operator using Patroni and while we are able to resize underlying volumes (AWS ebs, google persistant disks) on the fly there is no way to reflect those changes in the claim template. Therefor new nodes added by scaling would start with too small discs.

Going for pre-provisioning is one option, but then we would basically build something Kubernetes has already solved very nicely. The idea of deleting the statefulset without cascading does not sound great ;)

Adding my fellow colleague for reference: @alexeyklyukin

**Comment by kow3ns** [comment]
@Jan-M We are working on rolling updates to StatefulSet's but atm we are not considering updating the VolumeClaimsTemplate in the first iteration. What would you expect updating a VolumeClaimsTemplate to do?
StatefulSet controller generates PVC from the VolumeClaimsTemplate that are provisioned manually or via the dynamic provisioner of the Cloud Provider plugin for your environment. The PersistentVolumeController will bind the PVCs to the PVs created by the provisioner. I don't think updating the VolumeClaimsTemplate of the StatefulSet and updating all the PVCs so that they are no longer satisfied by their PVs is what you would want. 
I think a better approach would be to allow for dynamic resizing of the volume itself as an out of band, with respect to the StatefulSet controller, operation as proposed in #35941. This won't address the mismatch that occurs when scaling the StatefulSet with previous VolumeClaimsTemplate, but, if you have are writing an operator that is using StatefulSet as a primitive, you could treat the storage in the VolumeClaimsTemplate as a bootstrap, default requirement, and update the underlying volumes to be consistent with a TPR that represents the current desired disk capacity.

**Comment by Jan-M** [comment]
The main concern raised here is that we may run into issues when triggering scaling with an outdated template thus creating a too small PVC triggering a too small PV to be provisioned.

We are also not 100% clear on the impact of a changed template would have on existing nodes right now (this would also include the non-cascaded delete + recreate). We see the risk, similar to what you mention, when we do a rolling termination of pods that the template with a bigger volume specified would block the existing volume claim (+pv) to be reused and reattached to the recreated pod. This would be bad as the old volume (already resized) would contain the data.

In the perfect world I would expect the change to the template to tickle down and trigger a PV resize. But as it contains the word "template" one could also expect nothing to happen and the template only to be applied during scaling (creation of new pods). It is more important to get some assurance on the pod + pvc assignment would be unaffected, as this is a crucial part once the volume contains data (is initialized).

To me it sounds like we should investigate the pre-provisioning option again for our operator.

On the rolling upgrade in general we are def. curious, currently the operator terminates pods after updating the Docker image version (minor PostgreSQL version upgrade). But we do some waiting for Kubernetes labels present that indicate the status of Patroni (application status within the pod).

Thanks for the quick response!

**Comment by kargakis** [comment]
Addressed in https://github.com/kubernetes/community/pull/503

**Comment by kow3ns** [comment]
https://github.com/kubernetes/kubernetes/pull/46669
