### ISSUE TITLE
CDK - known_tokens are wrong when rebooting one of the master randomly

### ISSUE THREAD

**Issue by jonathanmarsaud** [kubernetes/kubernetes#41019]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
Token, secrets, Unable to authenticate the request due to an error: crypto/rsa: verification error

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-17T20:36:07Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-17T20:20:10Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Physical servers (16 cores 32 thrads, 64GB of RAM) for worker at our own datacenter in France, Virtual Machines for K8s management (4vCPU, 8GB of RAM) (masters, lbapi, etcd), and some EC2 instances (t2.medium) for United States workers.
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS
- **Kernel** (e.g. `uname -a`): Linux mth-k8smaster-01 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: Canonical Kubernetes through Juju bundle charms

**What happened**:
After a fresh install of a new cluster through Canonical Kubernetes bundle charm, if I reboot one of my 3 masters, it reboot with a new token secret different from the two others.

**What you expected to happen**:
Those tokens need to be syced among the masters: they aren't right now. I got a new token that it loaded into the k8s object store during turn up and its not agree'ing with what the other masters have which would be why it showed up after reboot, not before.

**How to reproduce it** (as minimally and precisely as possible):
- Bootstrap a CDK with 3 masters / 5 etcd / 5 worker (all other charms scale at default value)
- Do a random reboot of 2 of your masters
- Check /srv/kubernetes/known_tokens.csv on all of them
- They must be different on all your masters now.

-> If you can't reproduce, please try again to reboot some masters again. Sometime it's random. This time it happens at the first reboot immediately after a fresh-install (no extra-operation).

**Anything else we need to know**:
Discussed on IRC #juju@freenode, bug opened at Juju team request :+1:

**Comment by chuckbutler** [comment]
If any bot can, I would like to take this issue and have it assigned to me. I'll have a fix proposed in short order once we have upgrade testing giving me clean results that our HA master's have 1:1 crypto keys across all the units.

**Comment by chuckbutler** [comment]
Change is in the pipeline @jonathanmarsaud   Thanks a bunch for reporting this issue with detailed reproduction instructions. I feel that this patch is a good first step towards resolution. I haven't done a full gambit test of the implications as HA control plane has been on the roadmap but is scheduled for completion at a later date. However with you testing this already, this should bring the masters into a 1:1 state, and resolve the crypto issues you were seeing.

I'm happy to lend additional engineering support to see this run to completion if you find any issues/discrepancies with the proposed fix.
