### ISSUE TITLE
Fire events for services with failed connections

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#4101]
We skip pods when we can't connect to them successfully, we should generate events when this happens.

**Comment by thockin** [comment]
I'm not sure we should generate events - I expect this to happen fairly frequently in a fully loaded cluster.  If every client of every service can cause events to be generated, that's a huge number of events.  It would be nice to detect services with endpoints that do not answer at all, but I am not sure how to do that safely and reliably.

I get the sentiment here, but I think eventing from each kube-proxy is dangerous.

**Comment by bgrant0607** [comment]
I agree with @thockin. Our internal RPC library logs in this case, and it's extremely spammy.

**Comment by brendandburns** [comment]
Closing this, since esp. with the new IP-Tables based proxy this isn't going to happen.
