### ISSUE TITLE
Kubeadm install binaries are missing apt-transport-https

### ISSUE THREAD

**Issue by abuehrle** [kubernetes/kubernetes#41024]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Kubernetes version** (use `kubectl version`):

**Environment**: 
- **Cloud provider or hardware configuration**: Bare Metal/Packet Net
- **OS** (e.g. from /etc/os-release):Ubuntu 16.04
- **Kernel** (e.g. `uname -a`): Kernel: 4.4.0-47-generic
- **Install tools**:
- **Others**:

**What happened**:

Installing Kubernetes binaries and Docker with `kubeadm` on bare metal servers, returning an error:  

```
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
```
kubeadm version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2074+a092d8e0f95f52", GitCommit:"a092d8e0f95f5200f7ae2cba45c75ab42da36537", GitTreeState:"clean", BuildDate:"2016-12-13T17:03:18Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Proposed Solution:**

Installing: 

```apt-get install apt-transport-https```

I've only seen this error lately, a prior install on Digital Ocean did not return the same error. 
@lukemarsden 

**What you expected to happen**:

Expected kubeadm to install the binaries. 

**How to reproduce it** (as minimally and precisely as possible):
run kubeadm on a bare metal server. 

**Anything else we need to know**:

**Comment by calebamiles** [comment]
Could you take a look @luxas? Thanks!

**Comment by luxas** [comment]
Ok, so this is not a bug by itself.
We're using an https repository (`apt.kubernetes.io`) and tbh it's currently expected that you know that using an `https` apt src requires `apt-transport-https`.

Anyway, this is probably something @lukemarsden will/can consider including the next time he takes a pass at the docs.

**Comment by luxas** [comment]
This has been fixed since the bug was filed :+1:
