### ISSUE TITLE
Kube init returns a failed to parse kernel config: error

### ISSUE THREAD

**Issue by abuehrle** [kubernetes/kubernetes#41025]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

kubeadm version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2074+a092d8e0f95f52", GitCommit:"a092d8e0f95f5200f7ae2cba45c75ab42da36537", GitTreeState:"clean", BuildDate:"2016-12-13T17:03:18Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: bare metal/packet.net
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04 
- **Kernel** (e.g. `uname -a`):kernel version: 4.4.0-47-generic #68
- **Install tools**: kubeadm
- **Others**:

**What happened**:

Setting up Kubernetes on bare metal servers (), and when I initialize the master with  ```kube init```  the following error is returned: 

```
failed to parse kernel config: unable to load kernel module "configs": output - "modprobe: FATAL: Module configs not found in directory /lib/modules/4.4.0-47-generic\n", err - exit status 1
```

**Proposed Solution:**
This is fixed by running: 

```apt-get install linux-image-$(uname -r)```

But maybe the missing mods should be added?  @lukemarsden 

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by luxas** [comment]
cc @Random-Liu @dchen1107 @yujuhong 

This is coming from the system verification check, anything we can do about it except for adding it to the docs?

**Comment by calebamiles** [comment]
Could someone from @kubernetes/sig-node-bugs please take a look, thanks!

**Comment by NickrenREN** [comment]
System kernel must contain .ko files first before we exec modprobe commands.  configs modules here does not exist in kernel so we can not load that.  
I do not know what kubernetes can do here

**Comment by Random-Liu** [comment]
System verification tries to look for kernel configuration files in the following location: https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/system/kernel_validator.go#L174-L177.

If not found, it will try to load the configs kernel module and try again.

I created a Ubuntu 16.04 vm, and checked the kernel configuration, it IS there:
```
$ ls /boot/config*
/boot/config-4.4.0-62-generic
```

How about your node? https://github.com/kubernetes/kubernetes/issues/41025#issue-205668793

**Comment by abuehrle** [comment]
It's showing me an older version of the kernel: 

```
ls /boot/config*
/boot/config-4.4.0-47-generic
```

I wondered about this.  As mentioned I had update the kernel manually with ```apt-get install linux-image-$(uname -r)```

does the kernel need to be: ```config-4.4.0-62-generic``` ?

**Comment by Random-Liu** [comment]
> does the kernel need to be: config-4.4.0-62-generic ?

Nope. But the system verification tool needs to find the kernel configuration file and do verification.

System verification run `uname -r` to get the kernel release, and then tried some possible paths including `/boot/config-$(uname -r)`. Once a kernel configuration file is found, it will stop searching and do verification.

> This is fixed by running: `apt-get install linux-image-$(uname -r)`

In your case, it seems that before you run `apt-get install linux-image-$(uname -r)`, there was a mismatch between your kernel release and the kernel configuration under `/boot/`.

> But maybe the missing mods should be added?

The error message `failed to parse kernel config: unable to load kernel module "configs": output - "modprobe: FATAL: Module configs not found in directory /lib/modules/4.4.0-47-generic\n", err - exit status 1` is a red herring.

Actually, system verification just needs to find a kernel configuration file. On coreos and gci, sometimes `configs` module needs to be loaded for the kernel configuration to show up.

**Comment by luxas** [comment]
@Random-Liu So what can the system verification check do if the configs module isn't present?

**Comment by abuehrle** [comment]
@Random-Liu I can work around that in my post until there is an update for this. Thanks for your help!

**Comment by Random-Liu** [comment]
> @Random-Liu So what can the system verification check do if the configs module isn't present?

As long as the kernel configuration file can be found at either of [the paths](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/system/kernel_validator.go#L174-L177), system verification will not try to load the kernel module.

If the configuration file doesn't present, and there is no `configs` module, then for now I don't know where to find kernel configuration. :( System verification check will just error out.

If anyone knows a better solution, please tell me. :)

**Comment by chandrureddy** [comment]
I am trying on s390x platform and I have the same error.

```
>kubeadm init --pod-network-cidr=10.1.0.0/16 
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.6.0
[init] Using Authorization mode: RBAC
[preflight] Running pre-flight checks
[preflight] The system verification failed. Printing the output from the verification:
OS: Linux
KERNEL_VERSION: 4.4.0-59.80.el7_2.ssc_k_1_0.1.s390x
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
DOCKER_VERSION: 1.12.6
DOCKER_GRAPH_DRIVER: btrfs
[preflight] WARNING: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
[preflight] WARNING: socat not found in system path
[preflight] Some fatal errors occurred:
	failed to parse kernel config: unable to load kernel module "configs": output - "modprobe: FATAL: Module configs not found.\n", err - exit status 1
	unsupported graph driver: btrfs

```

Environment:

    Cloud provider or hardware configuration: bare metal/packet.net
    OS (e.g. from /etc/os-release): IBM Linux release 8 (kvmibm1_1_2)
    Kernel (e.g. uname -a): Linux Master-63 4.4.0-59.80.el7_2.ssc_k_1_0.1.s390x #1 SMP Fri Feb 3 15:47:40 EST 2017 s390x s390x s390x GNU/Linux
    Install tools: kubeadm
    Others:

What is equivalent package needs to be installed on Redhat/Fedora flavors ? 
`[as per above solution on Ubuntu : apt-get install linux-image-$(uname -r)]`

**Comment by thomasmodeneis** [comment]
I also got the same issue on `4.4.0-77-generic` and `apt-get install linux-image-$(uname -r)` solved it.

**Comment by luxas** [comment]
Closing this as it's a non-fatal issue and it's easily solvable.
If you reopen, do that in the kubeadm repo.

**Comment by shenshouer** [comment]
Anyone who knows how to solved on CentOS7 with kernel 4.9.0 ?

**Comment by strangelyhuman** [comment]
I was running into the same issue on a CentOS machine running kernel 4.8.7
I realized that the /boot folder was missing a config file for that kernel (the very same config
file that is generated during a kernel configuration)

I was able to solve it by copying the .config file from the kernel source tree and renaming it in
this format- /boot/config-$(uname -r)

**Comment by gengcixi** [comment]
I occur this error on my board. and finally found the /proc/config.gz file not found , need open this config in kernel compile.

**Comment by koala9527** [comment]
My system is  5.4.47-OPENFANS+20200622-v8 , can't apt-get install linux-image-$(uname -r)  ,how to solve it

**Comment by city** [comment]
[ERROR SystemVerification]: failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: FATAL: Module configs not found in directory /lib/modules/4.19.79-1.ph3-esx\\n", 

basically you can see the mismatch here
root@photon-master [ ~ ]# ls /boot/config*
/boot/config-4.19.164-3.ph3-esx
root@photon-master [ ~ ]# uname -r
4.19.79-1.ph3-esx
root@photon-master [ ~ ]#
THEY DONT MATCH
SOLUTION:
root@photon-master [ ~ ]# cd /boot
root@photon-master [ /boot ]# mv config-4.19.164-3.ph3-esx config-4.19.79-1.ph3-esx
