### ISSUE TITLE
Eviction manager evicts innocent pods after cleaning up unused images.

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#41032]
Lately we have customer possibly hitting this issue when there are too many unused images on nodes.

When nodes are under disk pressure (either disck space or inodes), eviction manager will try deleting unused images at first to reclaims disk resource, which is good. However, a common issue we could see is the eviction manager continues to evict innocent pods even if the unused images were deleted and the disk pressure should have been resolved. The eviction manager does not aware of the latest disk status until cadvisor re-sync with it.

Although the evicted pods may get rescheduled /  restarted by their controllers after, this is not optimal.

@dashpole @kubernetes/sig-node-bugs

**Comment by vishh** [comment]
@dashpole is working on a fix for this. @sjenning also had a PR out to
avoid evicting based on old data. I hope one of them can wrap up the fix
for this issue.

**Comment by sjenning** [comment]
This was my PR btw https://github.com/kubernetes/kubernetes/pull/33121

**Comment by dchen1107** [comment]
I talked to Vish and @dashpole on this very topic before. This is known issue. The fundamental issue is that the eviction manager acts too aggressively on the old data. Since disk account today is expensive, we slowly update disk stats. But the eviction manager take the action upon the old / staled data.

**Comment by dchen1107** [comment]
@sjenning we missed your pr for this fix.

**Comment by dchen1107** [comment]
@dashpole's pr https://github.com/kubernetes/kubernetes/pull/42435 addressing this particular issues  were merged a while back. Close this one.

**Comment by MrHohn** [comment]
Thanks for the fix!
