### ISSUE TITLE
Migrate CronJobs to beta

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#41039]
Per popular demand (see the beginning of the discussion: https://github.com/kubernetes/features/issues/19#issuecomment-277130872) and considering that #40932 is going to limit the number of created Jobs sig-apps decided to migrate CronJobs to beta. 

This issue is opened to discuss the following problems that were initially identified:

1. Where the CronJobs should land?
2. Do we want to keep backwards compatibility?

**Ad. 1.**
CronJobs currently live under `batch/v2alpha1`, so the logical move to beta would be to introduce `batch/v2beta` which eventually lead us to `batch/v2`. Unfortunately, the full support for multiversioned API groups is still not perfect.
The alternative we've discussed during sig-apps call (@erictune and I prefer both agree on that one) is to extend the current version, rather than introducing a new one. This approach seems to be the most reasonable approach knowing the state of multiversioned support. Iow. CronJob would migrate to `batch/v1beta1` and eventually to `batch/v1`, when all the GA requirements gathered in https://github.com/kubernetes/features/issues/19 are fulfilled.

@kubernetes/api-approvers @kubernetes/sig-api-machinery-pr-reviews I'd like to hear your opinions on that

**Ad. 2.**
We've kept backwards compatibility when we were renaming from ScheduledJobs to CronJobs, by accepting old resources and converting them on the fly to CronJobs and stored as such. All HTTP actions are supported at both endpoints, iow. under `apis/batch/v2alpha1/namespaces/*/cronjobs` and `apis/batch/v2alpha1/namespaces/*/scheduledjobs`. Given that, we want to keep the `batch/v2alpha1` endpoint available throughout 1.6 release and be dropped in 1.7. ScheduledJobs support will be entirely dropped with this change.

**Action items:**

- [x] remove ScheduledJobs entirely from the code base  - https://github.com/kubernetes/kubernetes/pull/49930
- [x] implement new API version in batch `batch/v1beta1` - https://github.com/kubernetes/kubernetes/pull/41901 and https://github.com/kubernetes/kubernetes/pull/51465
- [ ] inform users about deprecating `batch/v2alpha1`

@kubernetes/sig-apps-misc fyi

**Comment by kargakis** [comment]
I think introducing cleanup policy (`revisionHistoryLimit` in Deployments) and setting a default for it (number of latest jobs to retain) would be valuable to happen alongside graduating CronJobs to beta. Otherwise, the default will need to be set during the next graduation phase which I guess will take some time. We have had this issue with Deployments (https://github.com/kubernetes/kubernetes/issues/23597, https://github.com/kubernetes/kubernetes/issues/29735) and I guess Jobs for CronJobs are going to be created much more frequently than ReplicaSets for Deployments.

**Comment by TamalSaha** [comment]
Is this going to be part of 1.6 release?

**Comment by soltysh** [comment]
@TamalSaha unfrtunatelly this won't make it for 1.6, it'll be 1.7. I've updated the milestone to reflect that.

**Comment by TamalSaha** [comment]
That is sad! :(

**Comment by evmin** [comment]
Yeah. I remember when it was originally planned for 1.3. Waiting since then.

**Comment by soltysh** [comment]
@TamalSaha @evmin I'm very sorry guys, I only have a limited amount of time 😢

**Comment by evmin** [comment]
Looking forward to 1.7!

**Comment by ConorNevin** [comment]
Is this still on track to make 1.7?

**Comment by Zechnophobe** [comment]
Not seeing this in the list for 1.7, Any update on when to expect it?

**Comment by soltysh** [comment]
I'm sorry, but I wasn't able to finish it on time for 1.7 😢 This means at soonest it'll be part of 1.8.

**Comment by trenton42** [comment]
Looking forward to 1.8! Thanks for your work on this @soltysh

**Comment by amalkasubasinghe** [comment]
Can I know a timeline when we can expect Kubernetes 1.8?

**Comment by svaj** [comment]
Rather than asking for a timeline, I'd be more interested in the remaining work to get this into 1.8.  There might be some of us that have some spare cycles to contribute to this goal.

**Comment by numbsafari** [comment]
Unfortunately, I don't have the personal cycles to contribute on this issue. However, if there's a way I could perhaps help sponsor the work to be done so that it gets prioritized and actually in for 1.8, please let me know.

I know everybody's busy, so, not posting this as judgement, but just trying to think how else I can help at this stage.

**Comment by evmin** [comment]
What is the chance that it still gets into 1.8 at the moment? Rough guesstimate is OK.

**Comment by tback** [comment]
https://github.com/kubernetes/kubernetes/pull/41901 seems to be the pull request.

**Comment by soltysh** [comment]
I'm back from my holidays and this is my highest priority for 1.8. I'm currently working on https://github.com/kubernetes/kubernetes/pull/49930 which is a cleaning part of the actual migration happening in https://github.com/kubernetes/kubernetes/pull/41901. I'm hoping to get the PR finished and merged this week, or next at latest.

**Comment by numbsafari** [comment]
Let me know where / what TZ to deliver a pizza!

**Comment by evmin** [comment]
@soltysh - I have been hoping to see this one coming through with the release. Is it just a label issue or something else is required? Just asking...

**Comment by joshrosso** [comment]
@soltysh sorry for additional noise, but also curious as @evmin whether this will miss the 1.8 milestone? 

afaict, all items in 
> implement new API version in batch batch/v1beta1
have been merged. Thanks in advanced!

**Comment by janetkuo** [comment]
This is done?

**Comment by soltysh** [comment]
This is done. One last thing is to update the release notes which is what I'm doing right now. I'll go ahead and close this. 
@janetkuo one final question wrt to deprecation notice, is release note sufficient, or should I also update comments in `types.go` to include that info there?
