### ISSUE TITLE
mysql-wordpress-pd example not claiming created volume as expected on k8s 1.4.7 installed by Kops

### ISSUE THREAD

**Issue by jalbstmeijer** [kubernetes/kubernetes#41046]
**What keywords did you search in Kubernetes issues before filing this one?**:

mysql-wordpress-pd

---

** BUG REPORT: **

**Kubernetes version**:

Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:43:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider**: AWS

Installed with Kops

**What happened**:

Followed the mysql-wordpress-pd example.
Instead of the volumes created where used, new ones got created on volume claim.

**What you expected to happen**:

Created volumes should have been claimed.

**How to reproduce it**:

kubectl create -f local-volumes.yaml
kubectl create -f mysql-deployment.yaml

**Anything else we need to know**:

After adding annotation 'volume.beta.kubernetes.io/storage-class: ""'  in mysql-deployment.yaml made it working as expected.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
  labels:
    app: wordpress
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

**Comment by VsMaX** [comment]
I am having excatly the same issue on GCE/GKE kubernetes 1.6

Kubernetes is creating additional volumes in the cluster. Additionally mysql pod throws exceptions about persistentvolume-claim not being ready despite being ready:

```
SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "mysql-pv-claim", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "mysql-pv-claim", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "mysql-pv-claim", which is unexpected.]
Back-off restarting failed container
```

**Comment by kargakis** [comment]
Please move this to the kubernetes/examples repo.
