### ISSUE TITLE
`kubectl describe` reports wrong unbound PersistentVolumeClaim for pending pod

### ISSUE THREAD

**Issue by rsanders** [kubernetes/kubernetes#41057]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

PersistentVolumeClaim
"SchedulerPredicates failed due to PersistentVolumeClaim is not bound"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

1.5.1

Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T07:30:54Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: bare metal, 3 modes
- **OS** (e.g. from /etc/os-release): CentOS 7.2
- **Kernel** (e.g. `uname -a`): Linux *.cybraics.com 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kismatic 1.2.0
- **Others**: using 1.0.3 of the kubernetes-incubator/nfs-provisioner for testing

**What happened**:

Created a single PersistentVolumeClaim and a single Pod which mounted it. Noted it was stuck pending. Did a `kubectl describe pod` and saw the following message about unbound PersistentVolumeClaims. However, those PVCs are not referenced by this pod!  Instead, it references another PVC which is also unbound.

{default-scheduler }			Warning		FailedScheduling	[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "p8675309-redis-data", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "p8675309-elasticsearch-claim", which is unexpected.]

{default-scheduler }			Warning		FailedScheduling	[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "p8675309-elasticsearch-claim", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "p8675309-redis-data", which is unexpected.]

**What you expected to happen**:

`kubectl describe` should have reported just one unbound:

{default-scheduler }			Warning		FailedScheduling	[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "nfstestclaimrs", which is unexpected.]

**How to reproduce it** (as minimally and precisely as possible):

I assume that having several unbound PVCs in addition to the one the pod is trying to mount might trigger this logging error.

**Anything else we need to know**:

Full describe:

```
Name:		pvc-reader
Namespace:	default
Node:		grav2/10.2.1.63
Start Time:	Mon, 06 Feb 2017 21:29:26 -0500
Labels:		<none>
Status:		Running
IP:		172.16.127.165
Controllers:	<none>
Containers:
  pvc-reader1:
    Container ID:	docker://e02a3861f8b78e6516d3ccbba19d0d485e673176e862ea4ee579ac6a2f87b60a
    Image:		gcr.io/google_containers/busybox:1.24
    Image ID:		docker://sha256:0cb40641836c461bc97c793971d84d758371ed682042457523e4ae701efe7ec9
    Port:		
    Command:
      /bin/sh
    Args:
      -c
      sleep 9999999
    State:		Running
      Started:		Mon, 06 Feb 2017 21:29:28 -0500
    Ready:		True
    Restart Count:	0
    Volume Mounts:
      /mnt from nfs-root (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-qjf53 (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	True 
  PodScheduled 	True 
Volumes:
  nfs-root:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	nfstestclaimrs
    ReadOnly:	false
  default-token-qjf53:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-qjf53
QoS Class:	BestEffort
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath			Type		Reason			Message
  ---------	--------	-----	----			-------------			--------	------			-------
  14m		10m		12	{default-scheduler }					Warning		FailedScheduling	[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "p8675309-redis-data", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "p8675309-elasticsearch-claim", which is unexpected.]
  14m		10m		9	{default-scheduler }					Warning		FailedScheduling	[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "p8675309-elasticsearch-claim", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "p8675309-redis-data", which is unexpected.]
  9m		5m		7	{default-scheduler }					Warning		FailedScheduling	[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "p8675309-elasticsearch-claim", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "p8675309-redis-data", which is unexpected.]
  9m		4m		14	{default-scheduler }					Warning		FailedScheduling	[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "p8675309-redis-data", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "p8675309-elasticsearch-claim", which is unexpected.]

```

**Comment by nkwangleiGIT** [comment]
I tried this on minkube 1.5.2, and not able to recreate this issue, only saw one unbound pvc that was defined in pod template. Can you please upload the templates to create pvc and pod?

**Comment by rsanders** [comment]
We're on k8s 1.8.6 now, but even on 1.6 we no longer observed this.
