### ISSUE TITLE
Document etcd v2->v3 migration procedure

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#41054]
1. We need an action-required section for the rel. notes.
2. We need documentation for admins.

**Comment by resouer** [comment]
Kindly involve @xiang90 @hongchaodeng in.

Is there any existing doc, or should we work out a blog to cover this.

**Comment by calebamiles** [comment]
**cc: @philips**

**Comment by xiang90** [comment]
> We need documentation for admins.

what kind of documentation?

**Comment by ethernetdan** [comment]
@mml can this be closed?

**Comment by ethernetdan** [comment]
Being worked on in kubernetes/kubernetes.github.io#2767

**Comment by mml** [comment]
Here's a concrete piece for the rel notes from @liggitt

> * in the release notes for 1.6, make it clear that action is required related to etcd:
>   * upgrade to etcd3 prior to upgrading to 1.6 OR
>   * explicitly specify `--storage-type=etcd2 --storage-media-type=application/json` when starting the apiserver
>

**Comment by ethernetdan** [comment]
@idvoretskyi ^ could we make sure this makes 1.6 release notes?

**Comment by idvoretskyi** [comment]
@ethernetdan ok.

**Comment by mml** [comment]
This is not done until kubernetes/kubernetes.github.io#2767 merges, at least.

**Comment by ethernetdan** [comment]
@mml @devin-donnelly @wojtek-t can this be done today? this will block the release

**Comment by calebamiles** [comment]
we're waiting on HA upgrade results from @justinsb before finishing the upgrade doc; blocked on that.

**Comment by justinsb** [comment]
My results so far: I've tried a few times and so far it has split-brained every time: https://github.com/kubernetes/kubernetes/issues/43600

Going to keep experimenting, but I'm thinking I might pull the ejection handle on etc3 soon...

**Comment by ethernetdan** [comment]
Docs are finished, related discussion happening in other issues.
