### ISSUE TITLE
Reduce Deployment replicas in e2e tests

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#41063]
Most of the Deployment tests in the [Kubernetes 24-Hour Test Report](http://storage.googleapis.com/kubernetes-test-history/static/index.html) flake because the pods used by the Deployment are not ending up [running after 5 minutes](https://github.com/kubernetes/kubernetes/blob/3527153426581d48804dd0073ab254f209142ade/test/e2e/framework/util.go#L1217) which is the [timeout used for waiting pods to run](https://github.com/kubernetes/kubernetes/blob/3527153426581d48804dd0073ab254f209142ade/test/e2e/framework/util.go#L102)[1]. Funny enough there is a TODO for decreasing that timeout back to 30s. I am opening this issue for tracking the changes needed to drop unecessary replicas in Deployment e2e tests (except for stress-testing, most Deployment-related tests should use 1 replica and a combination of specific strategy parameters) but it would be useful to also discuss why 5m timeouts are not enough for waiting for pods to run.

[1] Look out for "failed to wait for pods running: [timed out waiting for the condition]"

@kubernetes/sig-apps-misc @kubernetes/sig-node-bugs

**Comment by yujuhong** [comment]
In the few deployment tests (#39879) I checked, the test timed out long before 5 minutes. It was mentioned that #31345 (unreliable `watch.Until()`)may be the cause of the misleading timeout errors.

**Comment by kargakis** [comment]
watch.Until was removed but pods never transitioning to ready is still a common issue for deployment-related flakes.

**Comment by ethernetdan** [comment]
@kargakis should we block on this for 1.6?

**Comment by kargakis** [comment]
@ethernetdan not necessary
