### ISSUE TITLE
pod to pod communication is very slow

### ISSUE THREAD

**Issue by sugun999** [kubernetes/kubernetes#41078]
Hi,

I have setup kubernetes on openstack with coreOS and deployed pods under custom namespace.

Everything is working fine. I have scenario where one pod/container need to call method of another pod/container which is also working fine.
But the response time of that method invocation is very slow. I noticed this with quick load test with curl and it freezes for about 4-5sec for every 10-15 requests.
and then it continues.

I checked cpu & memory usage of pods with kubectl and they look OK. 
Noticed this issue after updating to below versions.

Environment:

Kubernetes 1.5.2
CoreOS 1235.9.0

**Comment by cmluciano** [comment]
Can you provide details on the CNI plugin that you are using?

**Comment by sugun999** [comment]
Hi,

Used coreOS flannel overlay networking. When creating /etc/systemd/system/kubelet.service, for  kublet-wrapper,  the parameter --network-plugin= is specified as empty.

Also, system drop-in /etc/systemd/system/docker.service.d/40-flannel.conf, contains only

[Unit]
Requires=flanneld.service
After=flanneld.service

But this doc https://coreos.com/kubernetes/docs/latest/deploy-master.html, says bit different and if I follow that pod_network ip range uses different one 172. xx.xx..xx instead of my own 10.2.0.0/16 and not able to find pod with label.

**Comment by sugun999** [comment]
after disabling ipv6, it works as expected. Hence closing

**Comment by etoews** [comment]
@sugun999  Can you please include what you did to disable IPv6 here? That would be really helpful.

**Comment by vivek-jain-mt** [comment]
Can anyone advise how to disable ipv6? I am also facing extreme slowness randomly.
