### ISSUE TITLE
[Feature Request] Create a version monitor for etcd to validate migration to v3

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#41071]
Since we are moving to etcd v3 in 1.6 release, we need a way to validate the migration from v2 to v3 in existing clusters during rollout.
For this, we need to have a pod running on the master machine which periodically scrapes at least the following information:
- etcd server's binary version
- etcd backend version
- size of data in the v3 backend
- no. of gRPC calls to etcd (as gRPC <=> etcdv3)

The above information should then be exported in prometheus metrics format at some http endpoint, so that any prometheus server can
be served with this data.

cc @fgrzadkowski @wojtek-t @piosz

**Comment by wojtek-t** [comment]
> etcd backend version

This we can't do, because 3.*.* releases can support both v2 and v3 backend at the same time.

That's why the last two are a proxy for that i.e. are supposed to show us what we are doing.

**Comment by shyamjvs** [comment]
@wojtek-t Thanks for clarifying, I was confusing backend version with cluster version :)
And just for clarification, for the no. of gRPC calls, seems like we do not have to include it as part of this version monitor as `etcd_grpc_requests_total` metric is already exposed as a prometheus metric by etcd's /metrics endpoint:
```
etcd_grpc_requests_total{grpc_method="Compact",grpc_service="etcdserverpb.KV"} 3
etcd_grpc_requests_total{grpc_method="LeaseKeepAlive",grpc_service="etcdserverpb.Lease"} 38
etcd_grpc_requests_total{grpc_method="Range",grpc_service="etcdserverpb.KV"} 37822
etcd_grpc_requests_total{grpc_method="Txn",grpc_service="etcdserverpb.KV"} 100204
etcd_grpc_requests_total{grpc_method="Watch",grpc_service="etcdserverpb.Watch"} 39
```

**Comment by wojtek-t** [comment]
@shyamjvs - let's copy this metric for now - it would be much easier to grab all the metrics from one place (i.e. this monitor container) than from two different places.

**Comment by shyamjvs** [comment]
SGTM. Will do it, thanks.

**Comment by piosz** [comment]
cc @brancz @fabxc

**Comment by fabxc** [comment]
As etcd already exposes some of that information, is it necessary to proxy-expose it in the proposed component?
One wants to monitor the etcd instances simultaniously anyway.

> size of data in the v3 backend

That one might be tricky. How should size be measured and to what precision, e.g. number of records vs. bytes on disc.

**Comment by mml** [comment]
Can we substitute the term `API version` for `backend version`?  `API` vs `binary` is very clear, but `backend` is muddy, as evidenced by the first few comments in this issue.

**Comment by shyamjvs** [comment]
@fabxc We want to have all the version-related metrics (some of which are exposed directly by etcd and some of which have to be obtained/computed in other ways) at one place. Hence the proxy'ing. And regarding the size of data in v3, yes it is tricky and we decided to let it go off for now and are actually using the grpc request counts instead as a good proxy for v3 activity. Since for our purpose of validating migration from v2 to v3, this seems a good enough indicator.

**Comment by shyamjvs** [comment]
@mml We are not using the term `backend version` anymore, as there could be data in multiple backend versions at the same time (as pointed out by Wojtek above). Instead we are trying to use metrics like grpc request counts as a proxy for knowing v3 backend status.
