### ISSUE TITLE
pod failed to fit in any node fit failure summary on nodes : PodToleratesNodeTaints (1)

### ISSUE THREAD

**Issue by jerryjung** [kubernetes/kubernetes#41070]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): pod pending

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): kube-aws version v0.9.4-rc.1
**Environment**: aws
- **Cloud provider or hardware configuration**: aws
- **OS** (e.g. from /etc/os-release): Container Linux by CoreOS 1235.9.0 (Ladybug)
- **Kernel** (e.g. `uname -a`): 4.7.3-coreos-r2
- **Install tools**: kube-aws
- **Others**:

**What happened**: pod Pending
<pre>
NAME                                READY     STATUS    RESTARTS   AGE       IP        NODE
jupyter-notebook-4224242491-3gc6g   0/1       Pending   0          17m       <none>
</pre>

**What you expected to happen**: pod Running
<pre>
NAME                                       READY     STATUS    RESTARTS   AGE       IP            NODE
jupyter-notebook-2351894151-7gtj8          1/1       Running   0          1d       
</pre>

**How to reproduce it** (as minimally and precisely as possible): kubectl create -f **.yaml

**Anything else we need to know**: 
describe pod log
<pre>
Name:		jupyter-notebook-4224242491-3gc6g
Namespace:	default
Node:		/
Labels:		component=jupyter-notebook
		pod-template-hash=4224242491
Status:		Pending
IP:
Controllers:	ReplicaSet/jupyter-notebook-4224242491
Containers:
  jupyter:
    Image:	jerryjung/jupyter-notebook:latest
    Port:	8888/TCP
    Command:
      start-notebook.sh
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-4nhvr (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  PodScheduled 	False
Volumes:
  default-token-4nhvr:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-4nhvr
QoS Class:	BestEffort
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  1m		9s		8	{default-scheduler }			Warning		FailedScheduling	pod (jupyter-notebook-4224242491-3gc6g) failed to fit in any node
fit failure summary on nodes : PodToleratesNodeTaints (1)
</pre>

get events log
<pre>
LASTSEEN   FIRSTSEEN   COUNT     NAME                                KIND      SUBOBJECT   TYPE      REASON                    SOURCE                                   MESSAGE
46m        46m         1         ip-10-0-0-87.ec2.internal           Node                  Normal    Starting                  {kubelet ip-10-0-0-87.ec2.internal}      Starting kubelet.
46m        46m         1         ip-10-0-0-87.ec2.internal           Node                  Warning   ImageGCFailed             {kubelet ip-10-0-0-87.ec2.internal}      unable to find data for container /
45m        46m         34        ip-10-0-0-87.ec2.internal           Node                  Normal    NodeHasSufficientDisk     {kubelet ip-10-0-0-87.ec2.internal}      Node ip-10-0-0-87.ec2.internal status is now: NodeHasSufficientDisk
45m        46m         34        ip-10-0-0-87.ec2.internal           Node                  Normal    NodeHasSufficientMemory   {kubelet ip-10-0-0-87.ec2.internal}      Node ip-10-0-0-87.ec2.internal status is now: NodeHasSufficientMemory
45m        46m         34        ip-10-0-0-87.ec2.internal           Node                  Normal    NodeHasNoDiskPressure     {kubelet ip-10-0-0-87.ec2.internal}      Node ip-10-0-0-87.ec2.internal status is now: NodeHasNoDiskPressure
46m        46m         1         ip-10-0-0-87.ec2.internal           Node                  Normal    NodeNotSchedulable        {kubelet ip-10-0-0-87.ec2.internal}      Node ip-10-0-0-87.ec2.internal status is now: NodeNotSchedulable
45m        45m         1         ip-10-0-0-87.ec2.internal           Node                  Normal    Starting                  {kube-proxy ip-10-0-0-87.ec2.internal}   Starting kube-proxy.
45m        45m         1         ip-10-0-0-87.ec2.internal           Node                  Normal    RegisteredNode            {controllermanager }                     Node ip-10-0-0-87.ec2.internal event: Registered Node ip-10-0-0-87.ec2.internal in NodeController
45m        45m         1         ip-10-0-0-87.ec2.internal           Node                  Normal    NodeSchedulable           {kubelet ip-10-0-0-87.ec2.internal}      Node ip-10-0-0-87.ec2.internal status is now: NodeSchedulable
20m        42m         78        jupyter-notebook-2351894151-pnx5w   Pod                   Warning   FailedScheduling          {default-scheduler }                     pod (jupyter-notebook-2351894151-pnx5w) failed to fit in any node
fit failure summary on nodes : PodToleratesNodeTaints (1)
42m       42m       1         jupyter-notebook-2351894151         ReplicaSet             Normal    SuccessfulCreate   {replicaset-controller }   Created pod: jupyter-notebook-2351894151-pnx5w
19m       19m       1         jupyter-notebook-2351894151         ReplicaSet             Normal    SuccessfulDelete   {replicaset-controller }   Deleted pod: jupyter-notebook-2351894151-pnx5w
13s       19m       70        jupyter-notebook-4224242491-3gc6g   Pod                    Warning   FailedScheduling   {default-scheduler }       pod (jupyter-notebook-4224242491-3gc6g) failed to fit in any node
fit failure summary on nodes : PodToleratesNodeTaints (1)
19m       19m       1         jupyter-notebook-4224242491   ReplicaSet             Normal    SuccessfulCreate    {replicaset-controller }   Created pod: jupyter-notebook-4224242491-3gc6g
42m       42m       1         jupyter-notebook              Deployment             Normal    ScalingReplicaSet   {deployment-controller }   Scaled up replica set jupyter-notebook-2351894151 to 1
19m       19m       1         jupyter-notebook              Deployment             Normal    ScalingReplicaSet   {deployment-controller }   Scaled down replica set jupyter-notebook-2351894151 to 0
19m       19m       1         jupyter-notebook              Deployment             Normal    ScalingReplicaSet   {deployment-controller }   Scaled up replica set jupyter-notebook-4224242491 to 1
</pre>

**Comment by resouer** [comment]
Could you please post your pod yaml and `kubectl describe your-node`?

**Comment by alex88** [comment]
Same here
```
pod (redis-595045062-jv9wh) failed to fit in any node fit failure summary on nodes : NoVolumeZoneConflict (3), PodToleratesNodeTaints (1)
```

**Comment by jerryjung** [comment]
@resouer 
pod.yaml
<pre>
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: jupyter-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jupyter-notebook
  template:
    metadata:
      labels:
        component: jupyter-notebook
    spec:
      containers:
        - name: jupyter
          image: jerryjung/jupyter-notebook:latest
          command: ["start-notebook.sh"]
          ports:
            - containerPort: 8888
          resources:
            requests:
              cpu: 100m

---

kind: Service
apiVersion: v1
metadata:
  name: jupyter-notebook
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30088
  selector:
    component: jupyter-notebook
</pre>
describe node
<pre>
Name:			ip-10-0-0-87.ec2.internal
Role:
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/instance-type=m3.medium
			beta.kubernetes.io/os=linux
			failure-domain.beta.kubernetes.io/region=us-east-1
			failure-domain.beta.kubernetes.io/zone=us-east-1c
			kubernetes.io/hostname=ip-10-0-0-87.ec2.internal
Taints:			node.alpha.kubernetes.io/role=master:NoSchedule
CreationTimestamp:	Tue, 07 Feb 2017 22:21:12 +0900
Phase:
Conditions:
  Type			Status	LastHeartbeatTime			LastTransitionTime			Reason				Message
  ----			------	-----------------			------------------			------				-------
  OutOfDisk 		False 	Thu, 09 Feb 2017 10:49:12 +0900 	Tue, 07 Feb 2017 22:21:12 +0900 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  MemoryPressure 	False 	Thu, 09 Feb 2017 10:49:12 +0900 	Tue, 07 Feb 2017 22:21:12 +0900 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  DiskPressure 		False 	Thu, 09 Feb 2017 10:49:12 +0900 	Tue, 07 Feb 2017 22:21:12 +0900 	KubeletHasNoDiskPressure 	kubelet has no disk pressure
  Ready 		True 	Thu, 09 Feb 2017 10:49:12 +0900 	Tue, 07 Feb 2017 22:21:12 +0900 	KubeletReady 			kubelet is posting ready status
Addresses:		10.0.0.87,10.0.0.87,52.87.248.101,ip-10-0-0-87.ec2.internal
Capacity:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					1
 memory:				3857512Ki
 pods:					110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					1
 memory:				3857512Ki
 pods:					110
System Info:
 Machine ID:			16e25f4d8dbe4e219f5011854772e32c
 System UUID:			EC27A0B1-D3D6-86C2-C9D1-28E8A83297FA
 Boot ID:			7f03caa6-f319-41b8-bb52-1a5d27fc3fa2
 Kernel Version:		4.7.3-coreos-r2
 OS Image:			Container Linux by CoreOS 1235.9.0 (Ladybug)
 Operating System:		linux
 Architecture:			amd64
 Container Runtime Version:	docker://1.12.6
 Kubelet Version:		v1.5.2+coreos.0
 Kube-Proxy Version:		v1.5.2+coreos.0
ExternalID:			i-0abe5204ddec3b2d3
Non-terminated Pods:		(4 in total)
  Namespace			Name								CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----								------------	----------	---------------	-------------
  kube-system			kube-apiserver-ip-10-0-0-87.ec2.internal			0 (0%)		0 (0%)		0 (0%)		0 (0%)
  kube-system			kube-controller-manager-ip-10-0-0-87.ec2.internal		200m (20%)	0 (0%)		0 (0%)		0 (0%)
  kube-system			kube-proxy-ip-10-0-0-87.ec2.internal				0 (0%)		0 (0%)		0 (0%)		0 (0%)
  kube-system			kube-scheduler-ip-10-0-0-87.ec2.internal			100m (10%)	0 (0%)		0 (0%)		0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  300m (30%)	0 (0%)		0 (0%)		0 (0%)
No events.
</pre>

**Comment by resouer** [comment]
I can see this is a master so by default it is non-schedulable: `Taints:			node.alpha.kubernetes.io/role=master:NoSchedule`

If you want to deploy containers on this machine, please remove that taint:
```
kubectl taint nodes your-node-name node.alpha.kubernetes.io/role:NoSchedule-
```

**Comment by resouer** [comment]
@alex88  please check if you are facing the same problem.

**Comment by jerryjung** [comment]
@resouer As you informed me, the container was normally create. What is the cause of this?

**Comment by resouer** [comment]
The k8s 1.5 assume it's unsafe to deploy user containers to master. So master will be tainted as NoSchedule by default.

I will close this issue.

**Comment by alex88** [comment]
@resouer Ok so the problem was that I had PVC in an aws az without a running node on it, the only one running on that was the master but obviously it wasn't schedulable.
Thank you

**Comment by madhukar32** [comment]
@resouer I am facing the same problem as well. In my case I have a cluster of 3 nodes (1master + 2 minion )

Kubelet Version:               v1.5.1
Kube-Proxy Version:            v1.5.1

```
FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------   --------        ------                  -------
  3h            20s             665     {default-scheduler }                    Warning         FailedScheduling        pod (test-1012964845-v8915) failed to fit in any node
fit failure summary on nodes : Insufficient pods (2), PodToleratesNodeTaints (1)
```
```
[root@b7s38 ~]# kubectl get nodes
NAME      STATUS         AGE
b7s38     Ready,master   15d
b7s39     Ready          15d
b7s40     Ready          15d
```
```
[root@b7s38 ~]# kubectl describe nodes b7s39
Name:                   b7s39
Role:
Labels:                 beta.kubernetes.io/arch=amd64
                        beta.kubernetes.io/os=linux
                        kubernetes.io/hostname=b7s39
Taints:                 <none>
CreationTimestamp:      Wed, 01 Feb 2017 13:20:56 -0800
Phase:
Conditions:
  Type                  Status  LastHeartbeatTime                       LastTransitionTime                      Reason                          Message
  ----                  ------  -----------------                       ------------------                      ------                          -------
  OutOfDisk             False   Thu, 16 Feb 2017 23:19:19 -0800         Wed, 01 Feb 2017 13:20:56 -0800         KubeletHasSufficientDisk        kubelet has sufficient disk s
pace available
  MemoryPressure        False   Thu, 16 Feb 2017 23:19:19 -0800         Wed, 01 Feb 2017 13:20:56 -0800         KubeletHasSufficientMemory      kubelet has sufficient memory
 available
  DiskPressure          False   Thu, 16 Feb 2017 23:19:19 -0800         Wed, 01 Feb 2017 13:20:56 -0800         KubeletHasNoDiskPressure        kubelet has no disk pressure
  Ready                 True    Thu, 16 Feb 2017 23:19:19 -0800         Wed, 01 Feb 2017 13:21:06 -0800         KubeletReady                    kubelet is posting ready stat
us
Addresses:              10.84.29.39,10.84.29.39,b7s39
Capacity:
 alpha.kubernetes.io/nvidia-gpu:        0
 cpu:                                   32
 memory:                                263940232Ki
 pods:                                  110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:        0
 cpu:                                   32
 memory:                                263940232Ki
 pods:                                  110
System Info:
 Machine ID:                    9f5b3926f15943199a0566a34436b654
 System UUID:                   00000000-0000-0000-0000-002590C623EA
 Boot ID:                       477afff8-bbb1-4342-9cfb-eac0d3e52f97
 Kernel Version:                3.10.0-514.6.1.el7.x86_64
 OS Image:                      CentOS Linux 7 (Core)
 Operating System:              linux
 Architecture:                  amd64
 Container Runtime Version:     docker://1.12.5
 Kubelet Version:               v1.5.1
 Kube-Proxy Version:            v1.5.1
ExternalID:                     b7s39
Non-terminated Pods:            (110 in total)
```
```
[root@b7s38 ~]# kubectl describe nodes b7s40
Name:                   b7s40
Role:
Labels:                 beta.kubernetes.io/arch=amd64
                        beta.kubernetes.io/os=linux
                        kubernetes.io/hostname=b7s40
Taints:                 <none>
CreationTimestamp:      Wed, 01 Feb 2017 13:21:11 -0800
Phase:
Conditions:
  Type                  Status  LastHeartbeatTime                       LastTransitionTime                      Reason                          Message
  ----                  ------  -----------------                       ------------------                      ------                          -------
  OutOfDisk             False   Thu, 16 Feb 2017 23:25:48 -0800         Wed, 01 Feb 2017 13:21:11 -0800         KubeletHasSufficientDisk        kubelet has sufficient disk space available
  MemoryPressure        False   Thu, 16 Feb 2017 23:25:48 -0800         Wed, 01 Feb 2017 13:21:11 -0800         KubeletHasSufficientMemory      kubelet has sufficient memory available
  DiskPressure          False   Thu, 16 Feb 2017 23:25:48 -0800         Wed, 01 Feb 2017 13:21:11 -0800         KubeletHasNoDiskPressure        kubelet has no disk pressure
  Ready                 True    Thu, 16 Feb 2017 23:25:48 -0800         Wed, 01 Feb 2017 13:21:21 -0800         KubeletReady                    kubelet is posting ready status
Addresses:              10.84.29.40,10.84.29.40,b7s40
Capacity:
 alpha.kubernetes.io/nvidia-gpu:        0
 cpu:                                   32
 memory:                                263940232Ki
 pods:                                  110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:        0
 cpu:                                   32
 memory:                                263940232Ki
 pods:                                  110
System Info:
 Machine ID:                    b3890c24a25646eaaf810fb63f95469a
 System UUID:                   00000000-0000-0000-0000-0CC47A188048
 Boot ID:                       aa8720a1-19dc-439c-bee9-bf4ded030b49
 Kernel Version:                3.10.0-514.6.1.el7.x86_64
 OS Image:                      CentOS Linux 7 (Core)
 Operating System:              linux
 Architecture:                  amd64
 Container Runtime Version:     docker://1.12.5
 Kubelet Version:               v1.5.1
 Kube-Proxy Version:            v1.5.1
ExternalID:                     b7s40
Non-terminated Pods:            (110 in total)
```

**Comment by resouer** [comment]
Did you noticed the `Insufficient pods (2)`, have you checked pods capacity is exceeded?

As for `PodToleratesNodeTaint`, what's your pod yaml looks like? Do it has toleration related spec?

**Comment by sylesh687** [comment]
Name:           nginx-701339712-fzhmb
Namespace:      default
Node:           /
Labels:         pod-template-hash=701339712
                run=nginx
Status:         Pending
IP:
Controllers:    ReplicaSet/nginx-701339712
Containers:
  nginx:
    Image:      nginx
    Port:
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-4cldd (ro)
    Environment Variables:      <none>
Conditions:
  Type          Status
  PodScheduled  False
Volumes:
  default-token-4cldd:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-4cldd
QoS Class:      BestEffort
Tolerations:    <none>
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------   --------        ------                  -------
  3m            16s             10      {default-scheduler }                    Warning         FailedScheduling        pod (nginx-701339712-fzhmb) failed to fit in any node
fit failure summary on nodes : PodToleratesNodeTaints (1)
logs (END)

**Comment by kenzhaoyihui** [comment]
Also met this issue. There is no taint to limit the master that not scheduler pod. Anything else ?
Or any ideas?

```
kubectl describe nodes

[root@dhcp-8-213 log]# kubectl describe node
Name:			dhcp-8-213.nay.redhat.com
Role:			master
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/os=linux
			kubeadm.alpha.kubernetes.io/role=master
			kubernetes.io/hostname=dhcp-8-213.nay.redhat.com
Annotations:		scheduler.alpha.kubernetes.io/taints=[{"key":"dedicated","value":"master","effect":"NoSchedule"}]
			volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:			<none>
CreationTimestamp:	Tue, 11 Apr 2017 18:31:35 +0800
Phase:			
Conditions:
  Type			Status	LastHeartbeatTime			LastTransitionTime			Reason				Message
  ----			------	-----------------			------------------			------				-------
  OutOfDisk 		False 	Thu, 13 Apr 2017 19:08:17 +0800 	Tue, 11 Apr 2017 18:31:35 +0800 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  MemoryPressure 	False 	Thu, 13 Apr 2017 19:08:17 +0800 	Tue, 11 Apr 2017 18:31:35 +0800 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  DiskPressure 		False 	Thu, 13 Apr 2017 19:08:17 +0800 	Tue, 11 Apr 2017 18:31:35 +0800 	KubeletHasNoDiskPressure 	kubelet has no disk pressure
  Ready 		True 	Thu, 13 Apr 2017 19:08:17 +0800 	Tue, 11 Apr 2017 18:31:35 +0800 	KubeletReady 			kubelet is posting ready status
Addresses:		10.66.8.213,10.66.8.213,dhcp-8-213.nay.redhat.com
Capacity:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					8
 memory:				8051828Ki
 pods:					110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					8
 memory:				8051828Ki
 pods:					110
System Info:
 Machine ID:			2addedc6b166499fba76caeffcaab48a
 System UUID:			4C4C4544-0036-5910-8037-B5C04F4B5431
 Boot ID:			0782203c-474d-4cc7-b91f-b4a55d389451
 Kernel Version:		4.8.6-300.fc25.x86_64
 OS Image:			Fedora 25 (Workstation Edition)
 Operating System:		linux
 Architecture:			amd64
 Container Runtime Version:	docker://1.12.6
 Kubelet Version:		v1.5.4
 Kube-Proxy Version:		v1.5.4
PodCIDR:			10.244.0.0/24
ExternalID:			dhcp-8-213.nay.redhat.com
Non-terminated Pods:		(10 in total)
  Namespace			Name								CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----								------------	----------	---------------	-------------
  kube-system			dummy-2088944543-vdfzc						0 (0%)		0 (0%)		0 (0%)		0 (0%)
  kube-system			etcd-dhcp-8-213.nay.redhat.com					200m (2%)	0 (0%)		0 (0%)		0 (0%)
  kube-system			kube-apiserver-dhcp-8-213.nay.redhat.com			250m (3%)	0 (0%)		0 (0%)		0 (0%)
  kube-system			kube-controller-manager-dhcp-8-213.nay.redhat.com		200m (2%)	0 (0%)		0 (0%)		0 (0%)
  kube-system			kube-discovery-1769846148-ntch6					0 (0%)		0 (0%)		0 (0%)		0 (0%)
  kube-system			kube-dns-2924299975-zpkzj					260m (3%)	0 (0%)		140Mi (1%)	220Mi (2%)
  kube-system			kube-proxy-0b041						0 (0%)		0 (0%)		0 (0%)		0 (0%)
  kube-system			kube-scheduler-dhcp-8-213.nay.redhat.com			100m (1%)	0 (0%)		0 (0%)		0 (0%)
  kube-system			kubernetes-dashboard-4028012323-pzw8v				0 (0%)		0 (0%)		0 (0%)		0 (0%)
  kube-system			weave-net-gkvkc							20m (0%)	0 (0%)		0 (0%)		0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  1030m (12%)	0 (0%)		140Mi (1%)	220Mi (2%)
Events:		<none>

```

```
itoring-influxdb-957705310-4bphs", UID:"6f8088af-2033-11e7-8de3-18037333af82", APIVersion:"v1", ResourceVersion:"189938", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' pod (monitoring-influxdb-957705310-4bphs) failed to fit in any node
Apr 13 19:10:07 dhcp-8-213 journal: fit failure summary on nodes : PodToleratesNodeTaints (1)
Apr 13 19:10:10 dhcp-8-213 journal: E0413 11:10:10.541787       1 factory.go:583] Error scheduling kube-system monitoring-grafana-3730655072-3gr3h: pod (monitoring-grafana-3730655072-3gr3h) failed to fit in any node
Apr 13 19:10:10 dhcp-8-213 journal: fit failure summary on nodes : PodToleratesNodeTaints (1); retrying
Apr 13 19:10:10 dhcp-8-213 journal: I0413 11:10:10.541891       1 event.go:217] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"monitoring-grafana-3730655072-3gr3h", UID:"754b593c-2033-11e7-8de3-18037333af82", APIVersion:"v1", ResourceVersion:"189968", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' pod (monitoring-grafana-3730655072-3gr3h) failed to fit in any node
Apr 13 19:10:10 dhcp-8-213 journal: fit failure summary on nodes : PodToleratesNodeTaints (1)
Apr 13 19:10:10 dhcp-8-213 audit: NETFILTER_CFG table=filter family=2 entries=38
Apr 13 19:10:10 dhcp-8-213 audit: NETFILTER_CFG table=nat family=2 entries=72
Apr 13 19:10:11 dhcp-8-213 journal: E0413 11:10:11.543395       1 factory.go:583] Error scheduling kube-system monitoring-grafana-3730655072-3gr3h: pod (monitoring-grafana-3730655072-3gr3h) failed to fit in any node
Apr 13 19:10:11 dhcp-8-213 journal: fit failure summary on nodes : PodToleratesNodeTaints (1); retrying
Apr 13 19:10:11 dhcp-8-213 journal: I0413 11:10:11.543481       1 event.go:217] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"monitoring-grafana-3730655072-3gr3h", UID:"754b593c-2033-11e7-8de3-18037333af82", APIVersion:"v1", ResourceVersion:"189968", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' pod (monitoring-grafana-3730655072-3gr3h) failed to fit in any node
Apr 13 19:10:11 dhcp-8-213 journal: fit failure summary on nodes : PodToleratesNodeTaints (1)
Apr 13 19:10:13 dhcp-8-213 journal: E0413 11:10:13.545867       1 factory.go:583] Error scheduling kube-system monitoring-grafana-3730655072-3gr3h: pod (monitoring-grafana-3730655072-3gr3h) failed to fit in any node
Apr 13 19:10:13 dhcp-8-213 journal: fit failure summary on nodes : PodToleratesNodeTaints (1); retrying
Apr 13 19:10:13 dhcp-8-213 journal: I0413 11:10:13.546057       1 event.go:217] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"monitoring-grafana-3730655072-3gr3h", UID:"754b593c-2033-11e7-8de3-18037333af82", APIVersion:"v1", ResourceVersion:"189968", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' pod (monitoring-grafana-3730655072-3gr3h) failed to fit in any node
Apr 13 19:10:13 dhcp-8-213 journal: fit failure summary on nodes : PodToleratesNodeTaints (1)
Apr 13 19:10:15 dhcp-8-213 journal: E0413 11:10:15.811020       1 factory.go:583] Error scheduling kube-system monitoring-influxdb-957705310-4bphs: pod (monitoring-influxdb-957705310-4bphs) failed to fit in any node
Apr 13 19:10:15 dhcp-8-213 journal: fit failure summary on nodes : PodToleratesNodeTaints (1); retrying
Apr 13 19:10:15 dhcp-8-213 journal: I0413 11:10:15.811172       1 event.go:217] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"monitoring-influxdb-957705310-4bphs", UID:"6f8088af-2033-11e7-8de3-18037333af82", APIVersion:"v1", ResourceVersion:"189938", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' pod (monitoring-influxdb-957705310-4bphs) failed to fit in any node
Apr 13 19:10:15 dhcp-8-213 journal: fit failure summary on nodes : PodToleratesNodeTaints (1)
Apr 13 19:10:16 dhcp-8-213 kubelet: I0413 19:10:16.315390   28051 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/a5a2f5e5-1ea3-11e7-8de3-18037333af82-default-token-217fw" (spec.Name: "default-token-217fw") pod "a5a2f5e5-1ea3-11e7-8de3-18037333af82" (UID: "a5a2f5e5-1ea3-11e7-8de3-18037333af82").
```

**Comment by jeffmoss** [comment]
Check your AWS EC2 limits.
