### ISSUE TITLE
NewSelfClientConfig assumes certs are valid for bind IP / localhost

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#41081]
NewSelfClientConfig assumes that the server's TLS certificates will be valid for the bind IP or (in the case of binding to 0.0.0.0) will be valid for localhost.

If there is not a valid certificate for the bind IP or localhost, the client built by NewSelfClientConfig will fail with TLS errors, and the server bootstrap will fail.

**Comment by sttts** [comment]
We can do two things:
- create a self-signed cert in memory just for the loopback connection, if none is valid for the IP and/or localhost
- just accept all SNI server certs from the client.

**Comment by liggitt** [comment]
> create a self-signed cert in memory just for the loopback connection, if none is valid for the IP and/or localhost

we can do this for localhost if needed, though it's a bit weird. the IP case concerns me, since we can't use SNI for that, and can't assume localhost will resolve to a particular interface

> just accept all SNI server certs from the client.

how?

**Comment by sttts** [comment]
I had hoped there is some elegant way for skipping the hostname check. We can make the `tls.Config` of the client to accept our known server SNI certs, but the hostname check will stop the connection. Found some (pretty ugly) way in https://github.com/hashicorp/consul/blob/master/tlsutil/config.go#L253, basically switch to insecure mode and doing the cert check manually. Not sure I want that in kube.

**Comment by liggitt** [comment]
fixed in #41882
