### ISSUE TITLE
Kubelet volume manager doesn't unmount volume

### ISSUE THREAD

**Issue by rootfs** [kubernetes/kubernetes#41096]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Kubelet volume manager doesn't unmount volumes (rbd, iSCSI, etc) that are not controlled by attach-detach-controller. 
**Kubernetes version** (use `kubectl version`):
1.6

**Environment**:
- **Cloud provider or hardware configuration**: local cluster
- **OS** (e.g. from /etc/os-release):  CentOS
- **Kernel** (e.g. `uname -a`): 
- **Install tools**: local-up-cluster.sh with `--keep-terminated-pod-volumes=false` kubelet option 
- **Others**:

**What happened**:
1. create a Pod that uses rbd or iSCSI volume
2. delete pod
3. volume is never unmounted.

**What you expected to happen**:
volume should be unmounted as in 1.4/1.5

**How to reproduce it** (as minimally and precisely as possible):
1. create a Pod that uses rbd or iSCSI volume
2. delete pod
3. volume is never unmounted.

**Anything else we need to know**:

Tracing to DSW populator, the deleted pod's phase is alway `Running`, thus [this condition](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go#L163) is also true, unmount volume is thus never triggered.

@kubernetes/sig-storage-bugs

**Comment by jsafrane** [comment]
> 1. create a Pod that uses rbd or iSCSI volume
> 2. delete pod
> 3. volume is never unmounted.

I can't reproduce it with today's Kubernetes master branch. My iSCSI volume is always unmounted and detached by kubelet with --keep-terminated-pod-volumes=false

**Comment by rootfs** [comment]
works for me now with latest master code. Thanks @jsafrane
