### ISSUE TITLE
Error using fake ClientSet

### ISSUE THREAD

**Issue by dmmcquay** [kubernetes/kubernetes#41091]
**BUG REPORT **:

**Kubernetes version** (use `kubectl version`): dev branch

**What happened**: Trying to use fake.ClientSet in unit tests in kubeadm and am getting an error. 

`./addons_test.go:12: cannot use s (type *"k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/fake".Clientset) as type *clientset.Clientset in argument to getDNSIP`

**What you expected to happen**: Expected to be able to use fake.ClientSet as a fake ClientSet and be able to write unit tests. 

**How to reproduce it** (as minimally and precisely as possible):

```go
package addons

import (
	"fmt"
	"testing"

	"k8s.io/client-go/kubernetes/fake"
)

func TestGetDNSIP(t *testing.T) {
	s := fake.NewSimpleClientset()
	ip, err := getDNSIP(s)
	fmt.Println(ip, err)
}
```

**Comment by pires** [comment]
I believe the problem is in `getDNSIP(s)` that wants a different _clientset_, namely the one in `k8s.io/kubernetes/pkg/client/clientset_generated/clientset`.

Now, what's the solution? Perhaps [adopt client-go in kubeadm](https://github.com/kubernetes/kubeadm/issues/52)?

**Comment by dmmcquay** [comment]
Was not a bug, func wasn't asking for type, not looking for an interface, hence why it failed.
