### ISSUE TITLE
Delete a PVC for a StatelfulSet without deleting the PV causes a loop on VolumeDelete

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kubernetes#41102]
**Kubernetes version** (use `kubectl version`): 1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- **Kernel** (e.g. `uname -a`): 4.4.41-k8s
- **Install tools**: Kops 1.5
- **Others**: Terraform

**What happened**: We had someone install and remove this chart a few times: https://github.com/kubernetes/charts/tree/master/stable/concourse, they deleted the PVCs as documented but this left the PVs in `Released` state and then looped calling `VolumeDelete` and getting `VolumeInUse` with no back-off.

This resulted in ~50k AWS API calls over 24 hours.

**What you expected to happen**: At the very least the calls should have backed-off on failure.

**How to reproduce it** (as minimally and precisely as possible): Delete a PVC for a StatelfulSet without deleting the PV.

cc: @chrislovecnm & @jingxu97

**Comment by blakebarnett** [comment]
Seems like this would at least resolve the back-off, but why is it loopin in the first place?  https://github.com/kubernetes/kubernetes/pull/38339

**Comment by gnufied** [comment]
@blakebarnett yeah I haven't cherry picked this PR to release-1.5 branch. We have noticed similar problem. I will open a PR to cherry pick the commit to 1.5. 

So basically the reason we are looping is - because we expect volume to be detached eventually and then k8s should be able to delete it.

**Comment by kargakis** [comment]
@gnufied can we close this issue now?
