### ISSUE TITLE
Regression in most Kubemark tests

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#41108]
There seems to be a major regression with pretty much all the kubemark CI tests starting from around 12:00 (time as shown on gubernator dashboard).
From the commits around that time, seems like none of the commits in the kubernetes repo affected the code.
However, the following commit in test-infra merged around that time has changed the kubemark job scripts from .sh files to .env files along with doing a bunch of other stuff like setting job timeouts:
https://github.com/kubernetes/test-infra/commit/2d00415b0c4d32930288c6707edb7c5199027def

Even 1.5 branch test is failing, so something is wrong most definitely with test-infra.

cc @k8s-oncall @krzyzacy @wojtek-t @gmarek

**Comment by krzyzacy** [comment]
emmm...

give me 10min take a look before reverting it

**Comment by krzyzacy** [comment]
@shyamjvs I did trigger the job locally while the jenkins job was still running, can it break the project?

**Comment by shyamjvs** [comment]
@krzyacy Well technically, if you try triggering the job locally (assuming you are doing it with exactly the same job config), it should fail if there is already a job running as you'd have conflicts with the machine names at the very least. However, if there's something else that you did, I'd be interested in knowing. :)

**Comment by krzyzacy** [comment]
@shyamjvs Reverted and see if it will recover.

I kicked the same job twice locally and try to figure out what [docker command](https://github.com/kubernetes/test-infra/blob/master/jenkins/dockerized-e2e-runner.sh#L54-L57) is needed for kubemark. I suspect it killed something that was running, but I would expect next runs should recreate the GCP resources.

**Comment by krzyzacy** [comment]
@shyamjvs 

but I feel like `./test/kubemark/stop-kubemark.sh` was triggered twice in a row which causes the failure?

```
W0207 14:26:47.831] 2017/02/07 14:26:47 e2e.go:724: Step 'Ginkgo tests' finished in 1m18.017023818s
W0207 14:26:47.832] 2017/02/07 14:26:47 util.go:98: Step './test/kubemark/run-e2e-tests.sh --ginkgo.focus=\[Feature:Empty\] --gather-resource-usage=true --garbage-collector-enabled=true' finished in 1m20.736238004s
W0207 14:26:47.832] 2017/02/07 14:26:47 util.go:96: Running: ./test/kubemark/stop-kubemark.sh
W0207 14:27:50.319] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-kubemark-1-5/zones/us-central1-f/instances/bootstrap-e2e-kubemark-master].
W0207 14:27:59.118] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-kubemark-1-5/zones/us-central1-f/disks/bootstrap-e2e-kubemark-master-pd].
W0207 14:28:08.871] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-kubemark-1-5/regions/us-central1/addresses/bootstrap-e2e-kubemark-master-ip].
W0207 14:28:43.873] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-kubemark-1-5/global/firewalls/bootstrap-e2e-kubemark-master-https].
W0207 14:28:43.940] 2017/02/07 14:28:43 util.go:98: Step './test/kubemark/stop-kubemark.sh' finished in 1m56.175417799s
W0207 14:28:43.940] 2017/02/07 14:28:43 util.go:96: Running: ./test/kubemark/stop-kubemark.sh
W0207 14:28:44.981] ERROR: (gcloud.compute.instances.delete) Some requests did not succeed:
W0207 14:28:44.982]  - The resource 'projects/k8s-kubemark-1-5/zones/us-central1-f/instances/bootstrap-e2e-kubemark-master' was not found
W0207 14:28:44.982] 
W0207 14:28:45.445] ERROR: (gcloud.compute.disks.delete) Could not fetch resource:
W0207 14:28:45.445]  - The resource 'projects/k8s-kubemark-1-5/zones/us-central1-f/disks/bootstrap-e2e-kubemark-master-pd' was not found
W0207 14:28:45.445] 
W0207 14:28:46.490] ERROR: (gcloud.compute.addresses.delete) Some requests did not succeed:
W0207 14:28:46.491]  - The resource 'projects/k8s-kubemark-1-5/regions/us-central1/addresses/bootstrap-e2e-kubemark-master-ip' was not found
W0207 14:28:46.491] 
W0207 14:28:47.031] ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:
W0207 14:28:47.031]  - The resource 'projects/k8s-kubemark-1-5/global/firewalls/bootstrap-e2e-kubemark-master-https' was not found
W0207 14:28:47.032] 
```

**Comment by krzyzacy** [comment]
nvm, it was always like this...

**Comment by krzyzacy** [comment]
I would say 500-gce is still hanging -> timeout for some reason, someone might want to take a look there.

**Comment by wojtek-t** [comment]
@krzyzacy - now this is hanging because you changed the name of resources and we have quota issues. I will cleanup the project and it should solve the problem.

**Comment by krzyzacy** [comment]
@wojtek-t hummm... not as I notice? (Inside the test things should still be the same? Or it's because I triggered `--test` in e2e.go?)

**Comment by wojtek-t** [comment]
So everything used to be called "kubemark-500-****" and after your changed it was renamed to "bootstrap-***".

**Comment by wojtek-t** [comment]
That said, I'm not saying we should leave it as "kubemark-500-*", but that wasn't "no-op".

**Comment by krzyzacy** [comment]
oh yeah I changed the cluster name (used the default one indeed), my bad, will switch it back in my PR.

**Comment by shyamjvs** [comment]
Closing this issue as tests are back to green after the revert.Thank you @krzyzacy @wojtek-t !
