### ISSUE TITLE
kubernetes-anywhere deployment is failing with vsphere cloud provider if deployment is running behind proxy

### ISSUE THREAD

**Issue by nagavenkatab** [kubernetes/kubernetes#41128]
I am using https://github.com/colemickens/kubernetes-anywhere/blob/master/phase1/vsphere/README.md to deploy kubernetes with vsphere provider.

during make deploy, the deployment is failing on master node with 

INFO     : files: createFilesystemsFiles: createFiles: op(10): [started]  writing file "/etc/kubernetes/manifests/etcd.json"
INFO     : files: createFilesystemsFiles: createFiles: op(10): [finished] writing file "/etc/kubernetes/manifests/etcd.json"
INFO     : files: createFilesystemsFiles: createFiles: op(11): [started]  fetching file "/usr/local/bin/kubectl"
INFO     : files: createFilesystemsFiles: createFiles: op(11): op(12): [started]  GET "https://storage.googleapis.com/kubernetes-release/release/v1.3.4/bin/linux/amd64/kubectl"
CRITICAL : files: createFilesystemsFiles: createFiles: op(11): op(12): [failed]   GET "https://storage.googleapis.com/kubernetes-release/release/v1.3.4/bin/linux/amd64/kubectl": Get https://storage.googleapis.com/kubernetes-release/release/v1.3.4/bin/linux/amd64/kubectl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
CRITICAL : files: createFilesystemsFiles: createFiles: op(11): [failed]   fetching file "/usr/local/bin/kubectl": Get https://storage.googleapis.com/kubernetes-release/release/v1.3.4/bin/linux/amd64/kubectl: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
CRITICAL : files: failed to create files: failed to create files: failed to resolve file "/usr/local/bin/kubectl"

I think the issue is with proxy, Since my setup is running behind proxy, the script inside container on master node is not able to download the kubelet utility.

How can i use my proxy to download the kubelet inside the container.

**Comment by abrarshivani** [comment]
@nagavenkatab Can you please let me know which phase2 ignition container you are using? i.e value of attribute ```installer container (phase2.installer_container)``` in your config file

**Comment by nagavenkatab** [comment]
@abrarshivani I am using "docker.io/colemickens/k8s-ignition:latest"

**Comment by kerneltime** [comment]
@nagavenkatab can you try with the container image specified here.
https://github.com/kubernetes/kubernetes-anywhere/blob/master/phase1/vsphere/README.md

**Comment by nagavenkatab** [comment]
@kerneltime this time the deployment goes fine(till before validation), but the node are not getting registered.
I am seeing the below errors in kubelet logs on all nodes

Feb 11 20:08:28 photon-zv1KbtvMG docker[705]: I0211 20:08:28.646009     735 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Feb 11 20:08:35 photon-zv1KbtvMG docker[705]: E0211 20:08:35.621258     735 file.go:53] Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring
Feb 11 20:08:36 photon-zv1KbtvMG docker[705]: E0211 20:08:36.603456     735 container_manager_linux.go:562] error opening pid file /run/docker/libcontainerd/docker-containerd.pid: open /run/docker/libcontainerd/docker-containerd.pid: no such file or directory
Feb 11 20:08:36 photon-zv1KbtvMG docker[705]: W0211 20:08:36.625580     735 container_manager_linux.go:662] CPUAccounting not enabled for pid: 416
Feb 11 20:08:36 photon-zv1KbtvMG docker[705]: W0211 20:08:36.625643     735 container_manager_linux.go:665] MemoryAccounting not enabled for pid: 416
Feb 11 20:08:36 photon-zv1KbtvMG docker[705]: I0211 20:08:36.625658     735 container_manager_linux.go:372] Discovered runtime cgroups name: /system.slice/docker.service
Feb 11 20:08:38 photon-zv1KbtvMG docker[705]: I0211 20:08:38.664529     735 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Feb 11 20:08:38 photon-zv1KbtvMG docker[705]: I0211 20:08:38.664569     735 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Feb 11 20:08:48 photon-zv1KbtvMG docker[705]: I0211 20:08:48.679711     735 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Feb 11 20:08:48 photon-zv1KbtvMG docker[705]: I0211 20:08:48.681519     735 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Feb 11 20:08:55 photon-zv1KbtvMG docker[705]: E0211 20:08:55.621660     735 file.go:53] Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring
Feb 11 20:08:58 photon-zv1KbtvMG docker[705]: I0211 20:08:58.701405     735 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Feb 11 20:08:58 photon-zv1KbtvMG docker[705]: I0211 20:08:58.701457     735 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Feb 11 20:09:08 photon-zv1KbtvMG docker[705]: I0211 20:09:08.716508     735 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Feb 11 20:09:08 photon-zv1KbtvMG docker[705]: I0211 20:09:08.716563     735 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Feb 11 20:09:15 photon-zv1KbtvMG docker[705]: E0211 20:09:15.622203     735 file.go:53] Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring
Feb 11 20:09:18 photon-zv1KbtvMG docker[705]: I0211 20:09:18.735404     735 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Feb 11 20:09:18 photon-zv1KbtvMG docker[705]: I0211 20:09:18.735457     735 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Feb 11 20:09:28 photon-zv1KbtvMG docker[705]: I0211 20:09:28.749812     735 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Feb 11 20:09:28 photon-zv1KbtvMG docker[705]: I0211 20:09:28.749862     735 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Feb 11 20:09:35 photon-zv1KbtvMG docker[705]: E0211 20:09:35.622541     735 file.go:53] Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring
Feb 11 20:09:38 photon-zv1KbtvMG docker[705]: I0211 20:09:38.763066     735 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Feb 11 20:09:38 photon-zv1KbtvMG docker[705]: I0211 20:09:38.763382     735 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Feb 11 20:09:48 photon-zv1KbtvMG docker[705]: I0211 20:09:48.783210     735 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Feb 11 20:09:48 photon-zv1KbtvMG docker[705]: I0211 20:09:48.783346     735 conversion.go:134] failed to handle multiple devices for container. Skipping Filesystem stats
Feb 11 20:09:55 photon-zv1KbtvMG docker[705]: E0211 20:09:55.623267     735 file.go:53] Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring

root@photon-zv1KbtvMG [ ~ ]# kubectl version
Client Version: version.Info{Major:"0", Minor:"16+", GitVersion:"v0.16.2-dirty", GitCommit:"72a6a948403654c9943920f47bd2ebdece391594", GitTreeState:"dirty"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.8", GitCommit:"c5fcb1951afb8150e4574bc234aed957cb586eb0", GitTreeState:"clean"}
root@photon-zv1KbtvMG [ ~ ]# kubectl get nodes
root@photon-zv1KbtvMG [ ~ ]# kubectl get pods

**Comment by nagavenkatab** [comment]
@kerneltime I redeployed the whole setup, now it is working fine.
Thank a lot for the fix provided with the new image.
