### ISSUE TITLE
non-ExternalName v1.Service cannot be replaced

### ISSUE THREAD

**Issue by exarkun** [kubernetes/kubernetes#41140]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

"service replace", "spec.ClusterIP".  I found https://github.com/kubernetes/kubernetes/issues/25241 and commented there but then realized that was about `kubectl apply` and there is a simpler (more directly relevant) problem with `kubectl replace`.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT!

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:

minikube version: v0.15.0 on Ubuntu 16.10 laptop

- **OS** (e.g. from /etc/os-release):

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.10 (Yakkety Yak)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.10"
VERSION_ID="16.10"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="http://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=yakkety
UBUNTU_CODENAME=yakkety

- **Kernel** (e.g. `uname -a`):

$ uname -a
Linux baryon 4.8.0-37-generic #39-Ubuntu SMP Thu Jan 26 02:27:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**:

minikube

- **Others**:

**What happened**:

I created a service with `kubectl create service clusterip dummy --tcp=1234:4321`.
I retrieved the JSON for that service using `kubectl get -o json service dummy > dummy.json`
I edited the json to delete the `"ClusterIP": "...."` property of the spec.
I attempted to replace the service with `kubectl replace -f dummy.json`.
The replace operation failed with:

```
The Service "dummy" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

**What you expected to happen**:

I expected the replace operation to succeed, essentially as a no-op since nothing about the service description has changed.

**How to reproduce it** (as minimally and precisely as possible):

Steps above in "What happened" section.

**Anything else we need to know**:

@markrwilliams pointed me at https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation.go#L2584-L2588 and suggested one of the conditions there might be the cause of the problem.  To me, those conditions read as "If the service's old type is not ExternalName and the service's new name is not ExternalName and the service's old spec has a non-empty ClusterIP, reject the update as 'immutable field'."

This strikes me as incorrect since no attempt is made to check whether a change is actually being made to the `ClusterIP`.

**Comment by exarkun** [comment]
Probably user error.  The `PUT` is accepted if I actually include the same value for `ClusterIP` instead of leaving it out.

**Comment by redbaron** [comment]
I think it is still a bug, as not specifying `ClusterIP` should have same effect as specifying value which is currently used by a given service
