### ISSUE TITLE
[BUG] Audit all quorum reads

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#41143]
**BUG:**

We found an issue that crop'd up on an upgrade from 1.3.x->1.4.Y where we see a strikingly large increase in iops on the etcd node 4-5x.  On large clusters that do not have sufficient iops this can cause etcd sync and timeout problems, which then manifest into other issues. 

e.g. trigger false leader-election and cluster instability

**Kubernetes version** (use `kubectl version`):
1.4 & 1.5 

**Environment**:
all 

xref: https://github.com/coreos/etcd/issues/7232 

/cc @wojtek-t @kubernetes/sig-scalability-misc @kubernetes/sig-api-machinery-misc  @smarterclayton

**Comment by timothysc** [comment]
@gmarek Do you have a link to the endpoints controller re-write?

**Comment by wojtek-t** [comment]
@timothysc - I meant this PR: https://github.com/kubernetes/kubernetes/pull/41114
It may not be significant change, but potentially may affect something.

**Comment by timothysc** [comment]
@wojtek-t once that lands I can run a quick experiment, it's super easy to detect in etcd-debug-logs.

**Comment by pskrzyns** [comment]
cc @listomin @ss7pro

**Comment by xiang90** [comment]
Just a reminder: if you run etcd3.1+, then quorum read will not hit disk at all: Fast linearized reads (https://coreos.com/blog/etcd-3-1-announcement.html)

**Comment by timothysc** [comment]
@xiang90 v3 mode only though... right?

**Comment by timothysc** [comment]
I'm updating master right now btw.. @wojtek-t I'm going to need a container push por-favor.

**Comment by luxas** [comment]
@timothysc At the same time you're bumping all other tags to 3.1.0 and making the PR to push the new image, please bump https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/images/images.go#L33 as well.

And remember to ping @wojtek-t or whoever is pushing it to push for all architectures

**Comment by wojtek-t** [comment]
@mml @fgrzadkowski 

I'm not convinced we should do to 3.1 in 1.6 release (I'm probably fine with upgrading unit tests to use, it, but I'm not sure about everything else). Obviously we can create an image, but I don't know if it should become a default.

**Comment by timothysc** [comment]
> I'm not convinced we should do to 3.1 in 1.6 release 

Too early to tell until we have testing cycles on it.  

Currently waiting on rkt to push an updated tag on dependency rev matching.

**Comment by luxas** [comment]
> Currently waiting on rkt to push an updated tag on dependency rev matching.

@timothysc They did it seems

**Comment by timothysc** [comment]
They pushed it to master, I want a stable tag.

**Comment by luxas** [comment]
Ah, that can take some time :/ https://github.com/coreos/rkt/milestone/59

**Comment by justinsb** [comment]
Do we know what the underlying issue is?

**Comment by timothysc** [comment]
> Do we know what the underlying issue is? 

In 1.4 folks added an excessive # of quorum reads.  In etcd 2.x - 3.0.y that will force a write to disk.

**Comment by justinsb** [comment]
Right, but is this something we (or even I) could fix?  Do we have a read yet on where those calls are coming from?

**Comment by justinsb** [comment]
In the 1.4 branch, I can't see where we would ever pass Quorum=true to etcd unless you have turned it on with `--etcd-quorum-read=true`  I might be missing something though, because I can't see where we did quorum=true at all in etcd3.

In the 1.5 branch, etcd2 also looks to never switch the Quorum flag, and it continues to default to false AFAICT.  For etcd3, We do set `clientv3.WithSerializable())` on getOps when quorum=false - I am not 100% sure what that means.

Is there another codepath into etcd?

BTW I have no objection to your targeting etcd3.1 instead of etcd3.  But if there's an etcd2 problem, I'd like that we at least figure out what it is & how hard it would be to fix :-)

**Comment by timothysc** [comment]
bumping down priority b/c upstream defaults off, and we will rev to 3.1.x in the 1.7 cycle

**Comment by timothysc** [comment]
With #41427 merged, I'm going to close this.  It would require an etcd server bump and the quorum_read hit will go away.  

/cc @marun
