### ISSUE TITLE
GCE: Specify Image ID in StorageClass for dynamic volume provisioning

### ISSUE THREAD

**Issue by adambom** [kubernetes/kubernetes#41142]
**FEATURE REQUEST?**

I would like to be able to optionally specify an Image ID (for GCE) as part of the volume provisioning parameters for a `StorageClass`. Then any persistent volume claims referencing that storage class could dynamically provision disks based off of that image.

I've taken a stab at an initial implementation, which I will reference here. I may be missing a few things, but happy to make touch-ups as needed.

**Comment by jingxu97** [comment]
@adambom are you still working on the feature? Could you list all the changes you will need for this feature? @41144 seems the first step?
