### ISSUE TITLE
hack/godep-save.sh consumes all memory, fails to actually save

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#41158]
This is on HEAD with a couple commits trying to update a dependency.

When I use `hack/godep-save.sh`, the script slowly consumes all memory (32GB) and panics on OOM.

I can't run `godep save ./...` manually any longer, I believe due to the specially vendored repos.

I've tried with v75 and v79 of `godeps`.

I'm a bit stuck and any suggestions would be appreciated.

**Comment by colemickens** [comment]
Shamelessly and apologetically tagging @thockin for any possible suggestions.

**Comment by colemickens** [comment]
Reset, attempt #2 from scratch, I get this:
```
$ export KPATH=/home/cole/code/colemickens/kubernetes_gopath
$ export DEP=github.com/Azure/azure-sdk-for-go
....
$ godep get $DEP/...
godep: Package (github.com/mattn/go-isatty) not found
```

Even though the package exists... https://github.com/mattn/go-isatty

**Comment by colemickens** [comment]
Same result, even when I purge `Godeps/` and `vendor/` ahead of time.

**Comment by thockin** [comment]
I am OOO until Friday, but I don't have anything non-obvious to offer.
What is OOMing?  godep itself?

**Comment by colemickens** [comment]
(Sorry to disturb vacation, thanks for taking a look!)

Turns out it's because my homedir is symlinked: https://github.com/tools/godep/issues/434
