### ISSUE TITLE
HPA should allow definition of time period to average over for scaling operations

### ISSUE THREAD

**Issue by weaseal** [kubernetes/kubernetes#41159]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no, feature request

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): hpa cpu average

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

With regard to HPA scaling operations, I would like to be able to define a time period over which the HPA should compile an average CPU usage.  Right now it seems to check every 30 seconds and only consider what the CPU usage is at that very moment.  This is problematic with my JVM app as it garbage collects frequently which often coincides with the moment that the HPA checks CPU, causing a sort of jumpy scenario where unnecessary pods are frequently created.

**Kubernetes version** (use `kubectl version`):
1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CentOS 7
- **Kernel** (e.g. `uname -a`): 4.4.47-1.el7.elrepo.x86_64
- **Install tools**: kops
- **Others**: 

**What happened**: HPA is jumpy on my JVM app

**What you expected to happen**: HPA to be more stable / only scale with average CPU is high for a period of time (5 minutes? configurable, hopefully)

**How to reproduce it** (as minimally and precisely as possible): Run a JVM app that likes to do lots of minor GCs and set it to autoscale

**Anything else we need to know**: Pineapple is fantastic on pizza

**Comment by mwielgus** [comment]
cc: @DirectXMan12

**Comment by mwielgus** [comment]
@weaseal HPA calculates average CPU usage over 1 min. What would be your desired average period?

**Comment by weaseal** [comment]
@mwielgus ideally this is configurable in the HPA definition. I think some experimentation would be necessary to find the ideal duration. Also at the time I wrote this ticket, I don't believe 1 minute average was standard. Rather, it appeared to be just taking whatever the CPU value was at the very moment it checked with disregard to any sort of timer period average

**Comment by mwielgus** [comment]
@piosz 
Did we change the way cpu_usage_gauge is calculated? Last time I remember (I coded it :) we did it by transforming 2 cumulative samples gathered at 1 min interval into an average, in Heapster.

**Comment by mwielgus** [comment]
Well the code that transforms cumulative to gauge is still there:

https://github.com/kubernetes/heapster/blob/master/metrics/processors/rate_calculator.go#L62 

So it should work as I explained, unless you changed sampling frequency or monitoring guys modified the code elsewhere...

**Comment by piosz** [comment]
I'm not aware of any related changes within last year.

cc @DirectXMan12 @timstclair

**Comment by piosz** [comment]
@weaseal what is your Heapster configuration? Did you change [metric_resolution](https://github.com/kubernetes/heapster/blob/master/metrics/options/options.go#L70) flag there?

**Comment by weaseal** [comment]
I am attaching the heapster config here.  Let me know if you need anything else


```apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
  labels:
    k8s-addon: monitoring-standalone.addons.k8s.io
    k8s-app: heapster
    kubernetes.io/cluster-service: "true"
    version: v1.2.0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      k8s-app: heapster
      version: v1.2.0
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v1.2.0
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      containers:
        - image: gcr.io/google_containers/heapster:v1.2.0
          name: heapster
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 5
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - /heapster
            - --source=kubernetes.summary_api:''
        - image: gcr.io/google_containers/addon-resizer:1.6
          name: heapster-nanny
          resources:
            limits:
              cpu: 25m
              memory: 50Mi
            requests:
              cpu: 25m
              memory: 50Mi
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --cpu=80m
            - --extra-cpu=0.5m
            - --memory=140Mi
            - --extra-memory=4Mi
            - --threshold=5
            - --deployment=heapster
            - --container=heapster
            - --poll-period=300000
            - --estimator=exponential
---
apiVersion: v1
kind: Service
metadata:
  name: heapster
  namespace: kube-system
  labels:
    k8s-addon: monitoring-standalone.addons.k8s.io
    kubernetes.io/name: "Heapster"
    kubernetes.io/cluster-service: "true"
spec:
  ports:
    - port: 80
      targetPort: 8082
  selector:
    k8s-app: heapster
```

**Comment by piosz** [comment]
With this configuration you use the default 1 minute metric time window.
