### ISSUE TITLE
Kops can't run alpha versions without KOPS_RUN_OBSOLETE_VERSION

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#41152]
A bunch of PRs for the 1.5 branch are blocked because the `pull-kubernetes-e2e-kops-aws` suite keeps failing with `e2e.go:230: Something went wrong: starting e2e cluster: kops configuration failed: exit status 1`.

Looks like the issue is specific to the pull test suite for 1.5--the CI suite [ci-kubernetes-e2e-aws-release-1.5](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-aws-release-1.5) is relatively green.

Failing PRs:
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/40785/pull-kubernetes-e2e-kops-aws/11305/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/40793/pull-kubernetes-e2e-kops-aws/11335/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/40940/pull-kubernetes-e2e-kops-aws/11354/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/40993/pull-kubernetes-e2e-kops-aws/11211/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41118/pull-kubernetes-e2e-kops-aws/11373/

**Comment by saad-ali** [comment]
@kubernetes/test-infra-maintainers can you help with this please.

**Comment by ixdy** [comment]
Doesn't look like a test-infra issue to me; the failure appears to be

```
I0208 07:28:37.312] 
I0208 07:28:37.312] A new kubernetes version is available: 1.5.2
I0208 07:28:37.312] 
I0208 07:28:37.312] This version of kubernetes is no longer supported; upgrading is required
I0208 07:28:37.313] (you can bypass this check by exporting KOPS_RUN_OBSOLETE_VERSION)
I0208 07:28:37.313] 
I0208 07:28:37.313] More information: https://github.com/kubernetes/kops/blob/master/permalinks/upgrade_k8s.md#1.5.2
```

**Comment by ixdy** [comment]
cc @zmerlynn

**Comment by zmerlynn** [comment]
cc @justinsb

**Comment by zmerlynn** [comment]
This looks like it was broken by https://github.com/kubernetes/kops/pull/1790

**Comment by saad-ali** [comment]
CC @justinsb

**Comment by zmerlynn** [comment]
I have a fix, but am having trouble authing to GitHub, of course.

**Comment by justinsb** [comment]
Ah - I think we are not "sorting" a development version correctly..

**Comment by zmerlynn** [comment]
@justinsb: Yeah, I spent a couple minutes looking at the base PR, but it wasn't obvious. Plus it takes a couple hours for a kops PR to work all the way to `kops-aws`, so I'm inclined to duct-tape it for now.

**Comment by zmerlynn** [comment]
It looks like this is resolved. We'll figure out on the `kops` side what the longer resolution is, if there is one.

**Comment by roberthbailey** [comment]
Closing based on @zmerlynn's comment from February 8th. And if this is still an issue, it should be re-opened in the kops repository.
