### ISSUE TITLE
Multi-Master Clusters: Kubelet doesn't close connections immediately if a Master crashes 

### ISSUE THREAD

**Issue by raveeram** [kubernetes/kubernetes#41185]
**Kubernetes version**: v1.5.1

Environment:
- **Cloud provider**: Azure
- **OS**: "Ubuntu 16.04 LTS

We're trying to do some fail-over testing of masters. 
When a master is brought down via a hard stop(eg. VM power off), existing Agent-Kubelet connections to that master hang until they timeout instead of disconnecting. As a result, the Kubelet is not able to post the node's heartbeat and the nodes are marked as "NotReady" by the newly elected controller-manager.

We were able to verify this behavior even in a single master scenario. Should there be a Keepalive from the agent?

Lastly, this behavior doesn't exist when the master is shutdown cleanly.

Some relevant kubelet logs:
**Feb 09 08:09:58** k8s-agentpool1-42247313-1 docker[4557]: E0209 08:09:58.704293    4702 kubelet_node_status.go:302] Error updating node status, will retry: error getting node "k8s-agentpool1-42247313-1": Get https://10.240.255.5:443/api/v1/nodes?fieldSelector=metadata.name%3Dk8s-agentpool1-42247313-1&resourceVersion=0: read tcp 10.240.0.9:55790->10.240.255.5:443: read: connection timed out

**Feb 09 07:53:39** k8s-agentpool1-42247313-1 docker[4557]: I0209 07:53:39.480383    4702 round_trippers.go:296] GET https://10.240.255.5:443/api/v1/nodes?fieldSelector=metadata.name%3Dk8s-agentpool1-42247313-1&resourceVersion=0

@anhowe @colemickens

**Comment by bboreham** [comment]
The description seems odd to me.  One end of a TCP connection can never know what happened if the other end simply went away: the only options are to time out or wait.

Did you mean there should be multiple independent connections, and the connection to the dead master is holding up a conversation to the live one?

**Comment by colemickens** [comment]
>Did you mean there should be multiple independent connections, and the connection to the dead master is holding up a conversation to the live one?

Yes, that's what we're concerned we're seeing. Notice the timestamps on GET request and the timeout. They're 17minutes apart... and during that time there are no other GET watch requests fired, and there are no more attempts to post kubelet status, hence the nodes going unhealthy.

**Comment by raveeram** [comment]
Yes, you'd expect the PUT NodeStatus request to timeout soon enough to attempt it on another master rather than taking 17mins..

**Comment by colemickens** [comment]
Note to self, we should see if there's a flag for changing the watch interval on kubelet to at least short circuit this. Barring this, we need to get Azure LB to terminate TCP connections properly.

**Comment by redbaron** [comment]
What worries me is that Kubelet uses client-go library to connect to API server, which probably means that all other users are affected :(

**Comment by jsravn** [comment]
@bboreham That's true. Which is probably why client-go should be heartbeating at the application layer. E.g. sending a periodic GET to ensure the connection is still alive.

It does enable TCP keepalive though. So this should detect the TCP connection is dead after about 5 minutes. client-go uses a 30s interval/idle time, and on my system it will fail after 9 failed probes.

But I have also seen it take much longer to reconnect - updates being stale by 20 minutes. So I suspect there is something more broken, maybe in client-go rather than at the TCP layer.

**Comment by jsravn** [comment]
@raveeram are you using multi master? Because I suspect that is part of the problem.

**Comment by jejer** [comment]
Same Here

```
[root@bcmt-j-e8dd040b-control-0 ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

kubelet log:

I1026 07:32:29.311318   12723 kubelet_node_status.go:422] Using node IP: "172.16.1.250"
I1026 07:32:29.317160   12723 request.go:991] Request Body: {"status":{"$setElementOrder/conditions":[{"typ
I1026 07:32:29.317208   12723 round_trippers.go:386] curl -k -v -XPATCH  -H "Accept: application/vnd.kubern
I1026 07:32:29.332045   12723 round_trippers.go:405] PATCH https://k8s-apiserver.bcmt.cluster.local:8443/ap
I1026 07:32:29.332055   12723 round_trippers.go:411] Response Headers:
I1026 07:32:29.332058   12723 round_trippers.go:414]     Content-Type: application/vnd.kubernetes.protobuf
I1026 07:32:29.332062   12723 round_trippers.go:414]     Content-Length: 3667
I1026 07:32:29.332065   12723 round_trippers.go:414]     Date: Thu, 26 Oct 2017 07:32:30 GMT
I1026 07:32:29.332210   12723 request.go:989] Response Body:

I1026 07:32:31.332927   12723 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/vnd.kubernetes.protobuf, */*" -H "User-Agent: kubelet/v1.7.4 (linux/amd64) kubernetes/793658f" https://k8s-apiserver.bcmt.cluster.local:8443/api/v1/nodes/bcmt-j-e8dd040b-control-0?resourceVersion=0
I1026 07:32:59.792327   12723 round_trippers.go:386] curl ...
I1026 07:32:59.792619   12723 round_trippers.go:386] curl ...
I1026 07:33:25.796384   12723 round_trippers.go:386] curl ...
==================== ~ 15 mins blocked ====================
E1026 07:48:02.626486   12723 streamwatcher.go:109] Unable to decode an event from the watch stream: read tcp 172.16.1.250:59076->172.16.1.249:8443: read: connection timed out
I1026 07:48:02.627106   12723 round_trippers.go:386] curl ...
E1026 07:48:02.627837   12723 kubelet_node_status.go:357] Error updating node status, will retry: error getting node "bcmt-j-e8dd040b-control-0": Get https://k8s-apiserver.bcmt.cluster.local:8443/api/v1/nodes/bcmt-j-e8dd040b-control-0?resourceVersion=0: read tcp 172.16.1.250:59076->172.16.1.249:8443: read: connection timed out
```

**Comment by jdumars** [comment]
Can @raveeram or @jejer update this issue and let us know if this behavior still happens in > 1.8?

**Comment by jejer** [comment]
reproduced in kubernetes 1.9.2
procedure:
1. check connecting api-server "ss -np|grep kubelet|grep 8443"
2. pause api-server on openstack dashboard
3. watch "ss -np|grep kubelet|grep 8443"

**Comment by workhardcc** [comment]
@jdumars reproduced in kubernetes 1.8.1

**Comment by andyxning** [comment]
Seems like a client-go problem. @caesarxuchao 

Client-go should mark a timeout connection as bad, close it and make a new connection.

**Comment by liggitt** [comment]
consolidating reports of this issue under https://github.com/kubernetes/kubernetes/issues/48638
