### ISSUE TITLE
Can not see output of provision script in real-time when building cluster with vagrant and virtualbox

### ISSUE THREAD

**Issue by bqluan** [kubernetes/kubernetes#41188]
**Kubernetes version**:
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: local cluster with vagrant and virtualbox
- **Install tools**: KUBERNETES_PROVIDER=vagrant ./cluster/kube-up.sh

**What happened**:
When I build a local cluster with vagrant and virtualbox, I can not see the output of provision script in real-time. I can see the output after the script exits. This means if the script takes 1 hour, I can see the output after waiting for 1 hour. Nothing shows while executing the script.

**What you expected to happen**:
I want to see output while the script executes.

**How to reproduce it**:
Download [binary release v1.5.2 ](https://github.com/kubernetes/kubernetes/releases/tag/v1.5.2) and unzip it. Then change to release directory:
```
export KUBERNETES_PROVIDER=vagrant
./cluster/kube-up.sh
```

**Anything else we need to know**:
I find out that if I comment out [this line](https://github.com/kubernetes/kubernetes/blob/release-1.5/Vagrantfile#L230) in Vagrantfile, the problem no longer exists. I think `override` should be used in the following code instead of `config`. Am I right?
```
# Then try vsphere
    config.vm.provider :vsphere do |vsphere, override|
      setvmboxandurl(override, :vsphere)

       #config.vm.hostname = ENV['MASTER_NAME']

       config.ssh.username = ENV['MASTER_USER']
       config.ssh.password = ENV['MASTER_PASSWD']

       # !!! HERE HRER HERE !!!!
       # config.ssh.pty = true
       # !!! HERE HRER HERE !!!!
       config.ssh.insert_key = true
       #config.ssh.private_key_path = '~/.ssh/id_rsa_vsphere'
```

FYI, enabling pty means the output will be parsed before writing to UI, please refer to [this link](https://github.com/mitchellh/vagrant/pull/8195/commits/64d49451ab276717100f2ddf3a3489878bd4d10b).

**Comment by bqluan** [comment]
@kubernetes/sig-cluster-ops-misc

**Comment by liggitt** [comment]
vagrant provider has been removed
/close
