### ISSUE TITLE
fluentd-elasticsearch addon doesn't enforce proper mapping 

### ISSUE THREAD

**Issue by karol-brejna-i** [kubernetes/kubernetes#41204]
I tried to search the issues for "elasticsearch mapping", "elasticsearch mappings", "elasticsearch template' but found nothing similar.

So I fill this BUG REPORT.

**Kubernetes version**:
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- **Kernel**: Linux ip-10-0-0-76 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Others**: The issue is about https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch

**What happened**:
It looks like customized mapping for logs is not working.

fluentd-elasticsearch addon (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch) includes
index template for elasticsearch (https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/es-image/template-k8s-logstash.json) that is placed in config/templates directory of elasticsearch.
This index template is supposed to make sure that when new index is automatically created (when new log documment are received by elasticsearch) proper mapping is given.
For example, the following fragment:

```
  "kubernetes_field" : {
          "match_mapping_type": "string",
          "path_match" : "kubernetes.*",
          "mapping" : {
            "type" : "string",
            "index" : "not_analyzed"
          }
	}
```		  
should make sure that every property of kubernetes field is not analyzed.

As I understand it this mechanism is based on the feature described here:
https://www.elastic.co/guide/en/elasticsearch/reference/1.7/indices-templates.html#config

If you browse through the documetation for higher version of elasticsearch (2.x, 5.x) are missing this information: 
https://www.elastic.co/guide/en/elasticsearch/reference/2.0/indices-templates.html#config

I did an experiment on my local machine, and it turnes out that putting any index template file in config/templates folder doesn't work.

Furthermore: I've checked "pure" k8s cluster set up with fluentd-elastic addon installed.
There are some pods running that produce logs.

The mapping autmatically generated when creating the index is:
```
{
  "logstash-2017.02.08":{
    "mappings":{
      "fluentd":{
        "properties":{
          "@fields":{
            "properties":{
              "body_bytes_sent":{
                "type":"string"
              },
              "http_referrer":{
                "type":"string"
              },
              "http_user_agent":{
                "type":"string"
              },
              "remote_addr":{
                "type":"string"
              },
              "remote_user":{
                "type":"string"
              },
              "request":{
                "type":"string"
              },
              "request_method":{
                "type":"string"
              },
              "request_time":{
                "type":"string"
              },
              "status":{
                "type":"string"
              }
            }
          },
          "@timestamp":{
            "type":"date",
            "format":"strict_date_optional_time||epoch_millis"
          },
          "docker":{
            "properties":{
              "container_id":{
                "type":"string"
              }
            }
          },
          "kubernetes":{
            "properties":{
              "container_name":{
                "type":"string"
              },
              "host":{
                "type":"string"
              },
              "labels":{
                "type":"object"
              },
              "namespace_name":{
                "type":"string"
              },
              "pod_id":{
                "type":"string"
              },
              "pod_name":{
                "type":"string"
              }
            }
          },
          "log":{
            "type":"string"
          },
          "stream":{
            "type":"string"
          },
          "tag":{
            "type":"string"
          }
        }
      }
    }
  }
}
```

All the properites of kubernetes field are analyzed. There is also no mapping for "_default_" type (as the template specifies).

After manually creating an index template (via PUT _template/template_1 rest CALL) 
as defined in (https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/es-image/template-k8s-logstash.json)
and sendint the logs again, the index looks like this:

```

{
  "logstash-2017.02.08":{
    "mappings":{
      "_default_":{
        "dynamic_templates":[
          {
            "kubernetes_labels":{
              "mapping":{
                "type":"object",
                "dynamic_templates":[
                  {
                    "path_match":"*",
                    "mapping":{
                      "index":"not_analyzed",
                      "type":"string"
                    },
                    "match_mapping_type":"string"
                  }
                ]
              },
              "path_match":"kubernetes.labels"
            }
          },
          {
            "kubernetes_field":{
              "mapping":{
                "index":"not_analyzed",
                "type":"string"
              },
              "match_mapping_type":"string",
              "path_match":"kubernetes.*"
            }
          }
        ]
      },
      "fluentd":{
        "dynamic_templates":[
          {
            "kubernetes_labels":{
              "mapping":{
                "type":"object",
                "dynamic_templates":[
                  {
                    "path_match":"*",
                    "mapping":{
                      "index":"not_analyzed",
                      "type":"string"
                    },
                    "match_mapping_type":"string"
                  }
                ]
              },
              "path_match":"kubernetes.labels"
            }
          },
          {
            "kubernetes_field":{
              "mapping":{
                "index":"not_analyzed",
                "type":"string"
              },
              "match_mapping_type":"string",
              "path_match":"kubernetes.*"
            }
          }
        ],
        "properties":{
          "@fields":{
            "properties":{
              "body_bytes_sent":{
                "type":"string"
              },
              "http_referrer":{
                "type":"string"
              },
              "http_user_agent":{
                "type":"string"
              },
              "remote_addr":{
                "type":"string"
              },
              "remote_user":{
                "type":"string"
              },
              "request":{
                "type":"string"
              },
              "request_method":{
                "type":"string"
              },
              "request_time":{
                "type":"string"
              },
              "status":{
                "type":"string"
              }
            }
          },
          "@timestamp":{
            "type":"date",
            "format":"strict_date_optional_time||epoch_millis"
          },
          "docker":{
            "properties":{
              "container_id":{
                "type":"string"
              }
            }
          },
          "kubernetes":{
            "properties":{
              "container_name":{
                "type":"string",
                "index":"not_analyzed"
              },
              "host":{
                "type":"string",
                "index":"not_analyzed"
              },
              "labels":{
                "type":"object"
              },
              "namespace_name":{
                "type":"string",
                "index":"not_analyzed"
              },
              "pod_id":{
                "type":"string",
                "index":"not_analyzed"
              },
              "pod_name":{
                "type":"string",
                "index":"not_analyzed"
              }
            }
          },
          "log":{
            "type":"string"
          },
          "stream":{
            "type":"string"
          },
          "tag":{
            "type":"string"
          }
        }
      }
    }
  }
}
```

"_default_" type mapping is present, kubernetes field has all its properties not_analyzed.
Looks like the template is working now.

**What you expected to happen**:
I expected that elasticsearch index has proper mapping (i.e. all properies of kubernetes fields not analyzed).

**How to reproduce it** (as minimally and precisely as possible):
Install k8s with fluentd-elasticsearch addon installed.
Inspect logstash* indicies mappings. Mappings for 'kubernetes' field properties shoud include 'not_analyzed'.

**Anything else we need to know**:
Probably we are relying on elasticsearch functionality that was deprecated in 2.4 (which is used in the addon now). I suspect index template is not configured in the addon properly.

**Comment by karol-brejna-i** [comment]
@kubernetes/sig-instrumentation-misc

**Comment by karol-brejna-i** [comment]
The mapping template was removed from the codebase some time ago, but the problem of creating a proper mapping in elasticsearch was not solved.
/lifecycle froze

**Comment by discordianfish** [comment]
Apparently nobody has time to maintain these. Can we just remove the addon to not trick people into believing this works/is supported/maintained?
