### ISSUE TITLE
Kubelet should back off restarts of crashlooping containers

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#4121]
See #941 and #2529 for more background. Right now users have a bad experience if they submit a bad container, such as mistyped image name. Kubelet shouldn't restart it in a tight loop. Instead, it should back off.

**Comment by yujuhong** [comment]
We also need to persist restart count in the ContainerStatus. This is not the case now because the field is a snapshot of the number of dead containers lying around on the node, and they could be garbage collected.

**Comment by bgrant0607** [comment]
This is a performance optimization. Persistence is not absolutely required. You could start by accumulating it in memory.

However, it will be persisted by apiserver. We could maintain a delta over the last value sent to apiserver.

**Comment by yujuhong** [comment]
After a little bit of thinking, I am not sure if the accumulated RestartCount since the inception of the pod is what we want or need. If the pod has been running for a long time, the restart count may no longer be relevant to the current status and should not be taken into account for the backoff time.

I propose that we only count the restarts in the past hour (or some other small window).

**Comment by yujuhong** [comment]
@bgrant0607, what do you think?

**Comment by vmarmol** [comment]
A small windows SGTM and is the most likely source of most of the crash-loop problems.

**Comment by bgrant0607** [comment]
Small window sounds fine, since we're just trying to cap the restart rate. One could look at the number of restarts within the window, or how long ago the Nth previous restart was. The window should be sliding, and keep in mind the impact of the backoff on window size / restart count in order to avoid oscillation.

I'd like to avoid adding knobs to control this behavior to the API.

Updating the image name/tag should reset the backoff accounting.

**Comment by davsclaus** [comment]
+1 we see pods being restarted every 2nd issue due some mis configuration or if the image had some other failures.

**Comment by dchen1107** [comment]
Kubelet should also back off when pulling a bad image too.

**Comment by dchen1107** [comment]
#9452 might cause pulling images events generated by kubelet upon a bad image name.
