### ISSUE TITLE
[RFE] Update PodSpec on eviction * 2 of initial request. 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#41228]
Update PodSpec on eviction * 2 of initial request. 

**Kubernetes version** (use `kubectl version`):
master 

**Environment**:
*

**What happened**:
- People are terrible at specifying their resource requests, and can bounce too often

**What you expected to happen**:
- Request * 2 or some EXPR evaluation on bounce.

**How to reproduce it** (as minimally and precisely as possible):
Submit a small request that bounces b/c it's request was too low and it just tried to gobble memory. 

**Anything else we need to know**:
We did a more sophisticated thing in grids years ago, which we labeled as "hunting" 

/cc @kubernetes/sig-node-feature-requests @jayunit100

**Comment by davidopp** [comment]
I believe what you're asking for is Vertical Pod Autoscaling (#10782)
Please close (and add your comments there) if you agree this is a duplicate.

**Comment by timothysc** [comment]
This is a stop gap till the magical unicorn exists.  As of today, bouncing is a real issue.

**Comment by davidopp** [comment]
I think implementing this would use a lot of the same infrastructure as VPA (basically all the same bits except the prediction parts, if you hardcode a policy like 2*previous as you suggested).  So they should at least be considered together IMO.

cc/ @krzysztofgrygiel

**Comment by timothysc** [comment]
TBH scalable community driven metrics based auto-scaling (VPA & HPA) is not something I see happening for several releases at best, given the plethora of solutions and conflicts surrounding them.
