### ISSUE TITLE
Checking and stabilizing CRI builds

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#41225]
We have completed for CRI blockers for the rollout. According to the timeline in [rollout plan](https://docs.google.com/document/d/17QowuJd9BX3puEa47tYtN6yjACz851XCv4rs9RLg1Sc), we will switch the default to CRI implementation next week (2/14).  Before that, we should verify that CRI builds are passing at a rate that is equivalent to its counterparts (gci, non-cri).

Current CRI (cluster e2e) builds: https://k8s-testgrid.appspot.com/google-cri, 
Current CRI (node e2e builds): https://k8s-testgrid.appspot.com/google-node#kubelet-cri-gce-e2e, https://k8s-testgrid.appspot.com/google-node#kubelet-cri-serial-gce-e2e

/cc @dchen1107 @feiskyer

**Comment by yujuhong** [comment]
ci-kubernetes-node-kubelet-cri-serial:
https://k8s-testgrid.appspot.com/google-node#kubelet-cri-serial-gce-e2e
 - #37580: "Validate OOM score adjustments once the node is setup pod infra containers oom-score-adj should be -998 and best effort container's should be 10" 
 - Docker Daemon Network should recover from ip leak
    - There are a few failures, but some of them were caused by namespace deletion problems. Need to take a closer look to confirm it's not CRI-specific.
    - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-cri-serial/80
    - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-cri-serial/78

ci-kubernetes-e2e-cri-gce:
https://k8s-testgrid.appspot.com/google-cri#gce
 - Service should create endpoints for unready pods
     - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-cri-gce/2822
     - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-cri-gce/2802
 - There are a lot of less frequent flakes (exec, exec through http, etc). Need to look further

....More to come.

**Comment by freehan** [comment]
I am investigating `[Service should create endpoints for unready pods]`

**Comment by freehan** [comment]
For `[Service should create endpoints for unready pods]`, the failure symptoms is as follows:

1. RC scale to 0. 
2. Pod (has a PreStop life cycle hook to sleep 600s) should be terminated slowly
3. The test is expecting to reach the slow terminating pod, but the pod is gone.

**Comment by Random-Liu** [comment]
The issue is that we set the default 2 minutes timeout for `ExecSync`, which causes the 600s `PreStop` to be canceled in 2 minutes.

We should change `ExecSync` to respect the timeout passed in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/remote/remote_runtime.go#L284.

Except `ExecSync`, we should also change timeout for:
* PullImage: Image pulling may take quite a long time. We should not set timeout for this. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/remote/remote_image.go#L94 In the underlying runtime, at least for docker we have image pulling progress based timeout, which should be sufficient now.
* RunPodSandbox (StopPodSandbox?): RunPodSandbox is a group of operations now, it may take longer time than before especially during batch creation. We may want to set a longer timeout for it.
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/remote/remote_runtime.go#L76-L112

**Comment by freehan** [comment]
For `[Docker Daemon Network should recover from ip leak]`, I was not able to repro so far. 

I will run `service docker restart` in a loop over the weekend and see if we have any leaked ips.

**Comment by yujuhong** [comment]
The ci-kubernetes-e2e-cri-gce-serial has been pretty flaky compared with the non-CRI builds. One thing I found is that  [Pod Disks should be able to detach from a node which was deleted](https://k8s-testgrid.appspot.com/google-cri#gce-serial&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Pod%5C%20Disks%5C%20should%5C%20be%5C%20able%5C%20to%5C%20detach%5C%20from%5C%20a%5C%20node%5C%20which%5C%20was%5C%20deleted%5C%20%5C%5BSlow%5C%5D%5C%20%5C%5BDisruptive%5C%5D%5C%20%5C%5BVolume%5C%5D) deletes the node instance from GCE (and later the instance will be recreated).

Sometimes the node object in the kube-apiserver will be deleted by the node controller before the new instance comes up, but sometimes it wouldn't. In the latter case, kubelet fails to register itself because it doesn't have the permission to delete the node object.
```
E0210 08:17:26.502964    1382 kubelet_node_status.go:149] Previously node "bootstrap-e2e-minion-group-73vf" had externalID "858871596049287287"; now it is "4152570621079901951"; will delete and recreate.
E0210 08:17:26.508236    1382 kubelet_node_status.go:151] Unable to register node "bootstrap-e2e-minion-group-73vf" with API server: error deleting old node: User "kubelet" cannot delete nodes at the cluster scope. (delete nodes bootstrap-e2e-minion-group-73vf)
```

The node deletion issue has been discussed in #41224

**Comment by yujuhong** [comment]
@freehan, the "Pod should be submitted and removed" test flakes quite frequently.

Example:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/4389
```
0218 21:56:14.854063    1404 helpers.go:210] Cannot find network namespace for the terminated container "b515eea48acab84c4baead7814ef25311942d19784f40c76c6c6ec795685072b"
W0218 21:56:14.863112    1404 docker_sandbox.go:228] NetworkPlugin kubenet failed on the status hook for pod "pod-submit-remove-0f204ad7-f625-11e6-ae7c-0242ac11000b_e2e-tests-pods-kq0g6": Unexpected command output nsenter: cannot open : No such file or directory
I0218 21:56:14.863925    1404 helpers.go:210] Cannot find network namespace for the terminated container "b515eea48acab84c4baead7814ef25311942d19784f40c76c6c6ec795685072b"
I0218 21:56:14.864254    1404 plugins.go:410] Calling network plugin kubenet to tear down pod "pod-submit-remove-0f204ad7-f625-11e6-ae7c-0242ac11000b_e2e-tests-pods-kq0g6"
I0218 21:56:14.866244    1404 helpers.go:210] Cannot find network namespace for the terminated container "b515eea48acab84c4baead7814ef25311942d19784f40c76c6c6ec795685072b"
I0218 21:56:14.866275    1404 kubenet_linux.go:789] Removing e2e-tests-pods-kq0g6/pod-submit-remove-0f204ad7-f625-11e6-ae7c-0242ac11000b from 'kubenet' with CNI 'bridge' plugin and runtime: &{ContainerID:b515eea48acab84c4baead7814ef25311942d19784f40c76c6c6ec795685072b NetNS: IfName:eth0 Args:[]}
I0218 21:56:14.886466    1404 kubenet_linux.go:520] TearDownPod took 21.911817ms for e2e-tests-pods-kq0g6/pod-submit-remove-0f204ad7-f625-11e6-ae7c-0242ac11000b
I0218 21:56:14.906363    1404 status_manager.go:444] Status for pod "pod-submit-remove-0f204ad7-f625-11e6-ae7c-0242ac11000b_e2e-tests-pods-kq0g6(0f216e85-f625-11e6-bda9-42010af00002)" updated successfully: {status:{Phase:Running Conditions:[{Type:Initialized Status:True LastProbeTime:{Time:{sec:0 nsec:0 loc:0x4a82e40}} LastTransitionTime:{Time:{sec:63623051770 nsec:0 loc:0x4a82e40}} Reason: Message:} {Type:Ready Status:False LastProbeTime:{Time:{sec:0 nsec:0 loc:0x4a82e40}} LastTransitionTime:{Time:{sec:63623051774 nsec:0 loc:0x4a82e40}} Reason:ContainersNotReady Message:containers with unready status: [nginx]} {Type:PodScheduled Status:True LastProbeTime:{Time:{sec:0 nsec:0 loc:0x4a82e40}} LastTransitionTime:{Time:{sec:63623051770 nsec:0 loc:0x4a82e40}} Reason: Message:}] Message: Reason: HostIP:10.240.0.6 PodIP: StartTime:0xc4218a97e0 InitContainerStatuses:[] ContainerStatuses:[{Name:nginx State:{Waiting:<nil> Running:<nil> Terminated:0xc421f500e0} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:false RestartCount:0 Image:gcr.io/google_containers/nginx-slim:0.7 ImageID:docker://sha256:a9bfbd3ba7f240fb561895271c875fe21722d30560e56dbf9598ffde1615d4dc ContainerID:docker://a771bb61b82a2b562869cba021d8d14304876310a0741152b6f6dc5314ac5253}] QOSClass:BestEffort} version:4 podName:pod-submit-remove-0f204ad7-f625-11e6-ae7c-0242ac11000b podNamespace:e2e-tests-pods-kq0g6}
```
Should this have been fixed by your PRs or not?

**Comment by freehan** [comment]
As far as the above logs shows, it was working as intended. TearDownPod was able to complete without network namespace. I will try to dig deeper.

**Comment by yujuhong** [comment]
> Example:
> https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/4389

Spoke to @freehan offline. The error messages about network teardown are irrelevant. On the other hand, volumes are not cleaned up properly:
```
I0218 21:56:15.924108    1404 kubelet_pods.go:749] Pod "pod-submit-remove-0f204ad7-f625-11e6-ae7c-0242ac11000b_e2e-tests-pods-kq0g6(0f216e85-f625-11e6-bda9-42010af00002)" is terminated, but some volumes have not been cleaned up
```

/cc @dashpole

**Comment by freehan** [comment]
FYI, the `volumes have not been cleaned up` problem is very easy to reproduce. I just bump into it at HEAD.

Run a deployment, scale up and down. Then some pod will stuck at Termination for a while (~1 min). Then in kubelet logs, it will say `some volumes have not been cleaned up`

The deployment I used has nothing special: 
```
k run hostname --image=gcr.io/google_containers/serve_hostname:v1.4
```

**Comment by yujuhong** [comment]
I am closing issue now that CRI is enabled by default in the builds. We'll handle build failures following the normal procedure.
