### ISSUE TITLE
procfs.PidOf description comment is incorrect

### ISSUE THREAD

**Issue by bboreham** [kubernetes/kubernetes#41247]
The description of `procfs.PidOf` says:

```
// Find process(es) with a specified name (exact match)
```

However the implementation will interpret the name as a regex.  So for example "..." will match any three-letter string. This is not what I understand by "exact match".

https://github.com/kubernetes/kubernetes/blob/e9de1b0221dd8687aba527e682fafc7c33370c09/pkg/util/procfs/procfs_linux.go#L99

**Comment by feiskyer** [comment]
Will open an PR fix this comment
