### ISSUE TITLE
"should serve a basic image on each replica with a private image" consistently failing in large clusters

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#41244]
The "should serve a basic image on each replica with a private image" (for both ReplicaSet and ReplicationController) is consistently failing in large clusters since few days:

last failure:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-large-cluster/63

Looking into events it always happens exactly the same, i.e.:
```
I0209 18:15:37.286] Feb  9 18:15:24.450: INFO: At 2017-02-09 18:10:23 -0800 PST - event for my-hostname-private-14582432-ef36-11e6-b471-0242ac110007-f909q: {kubelet gke-gke-large-cluster-default-pool-1-aacbfbc0-53ld} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "my-hostname-private-14582432-ef36-11e6-b471-0242ac110007" with ErrImagePull: "filesystem layer verification failed for digest sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
```

It seems like a regression from this PR:
https://github.com/kubernetes/kubernetes/pull/40335

I don't yet know what it works significantly more reliably in small clusters...

@kubernetes/sig-node-bugs @ixdy

**Comment by wojtek-t** [comment]
@shyamjvs

**Comment by zmerlynn** [comment]
This should be fixed. (See internal bug 35098482)
