### ISSUE TITLE
Burst Semantics for StatefulSet Pod creation

### ISSUE THREAD

**Issue by kow3ns** [kubernetes/kubernetes#41255]
**FEATURE REQUEST** 
The current behavior of StatefulSet is to not create a successor Pod before all predecessors are Running and Ready. The current implementation will not deadlock if more than one Pod is failed, but it will fail to make progress if a Pod is unhealthy. Specifically, if Pod-0 and Pod-4 are both dead, the current implementation will attempt to resurrect Pod-0, but it will not attempt to resurrect Pod-4 until Pod-0 is Running and Ready. This behavior is generally safe, and it is required for some categories of StatefulSets.

However, for other categories of StatefulSets that are able to form a cluster without respect to the ordering and state of deployed Pods, this behavior is constraining #39363 and can lead to the application becoming unavailable unnecessarily #41012.

It would be useful to be able to specify an annotation that communicates to the StatefulSet controller that it can launch more than one Pod simultaneously. 

```yaml
statefulset.alpha.kubernetes.io/burst=<replicas>
``` 

Where "replicas" represents the maximum number of sequential replicas that the controller will allow to be unavailable at a given time. Constraining the number is useful for applications that need to form a quorum prior to launching further members.

Additionally, the semantics below

```yaml
statefulset.alpha.kubernetes.io/burst=all
``` 

where "all" indicates that the controller should burst up to StatefulSet.Spec.Replicas would be useful for applications that have a uniqueness, but no ordering constraint.

**Comment by kow3ns** [comment]
@smarterclayton I wanted to put StatefulSet burst in as a feature request to aggregate tracking for issues that can be resolved by its implementation.

**Comment by smarterclayton** [comment]
I think we could potentially allow `/burst=replicas` to be handled by the app itself as "initial quorum" as an env var.  That might mean that we only need burst=all.  Thinking about all quorum joiners i'm aware of:

1. Given a known initial quorum size M and an unknown scale size N
2. An individual container can form a quorum by only attempting to join for pods `SET-[0,M)`
3. Pods `SET-[0,M)` disallow joins from `SET-[M,N)` until a quorum is formed
4. Given a quorum, all membership is handled via that change

So M can be an env var safely (as long as people don't change it).  Can you think of a counterexample?

**Comment by kow3ns** [comment]
I can't think of any for which the ENV solution can't be made to work of for which the burst=replicas adds a huge benefit. imo burst=all is the feature that provides the most value. Given that, how about the following semantics.

```yaml
statefulset.alpha.kubernetes.io/burst=true
```
If set to true, it will burst across the entire set, and if set to false, or not present, the current behavior will be adopted. This seems simple enough to implement, and can be extended to handle the replicas case if there is a demand for it in the future. Also, its easier to explain to users and for users to reason about imo.

The one issue that does concern me is the interaction with 

```yaml
pod.alpha.kubernetes.io/initialized=false
```

Currently when the controller encounters a Pod with this annotation it will block deployment at that Pod. 

1. I think that we should ignore this annotation when burst=true, because the user is requesting that we gang schedule all of the Pods across the cluster without respect to readiness checks. These semantics are easy to explain, implement, and understand.

2. Alternatively, it is valuable to be able to block deployment at particular Pod, so we could go with the semantics that we will burst across all Pods until the first time the annotation is encountered, and then stop until the annotation is removed. So if Pod-3 has initialized=false, we will create Pod-0,1,2,3, but Pod-4,5,.. will not be created until initialized=true or until it is removed. I think that the value of these semantics is outweighed by the additional complexity that they introduce. While the implementation is not difficult, it will be more difficult to communicate this behavior to users and for users to reason about it.

**Comment by smarterclayton** [comment]
I think we want to kill that annotation anyway (I thought there was an issue open from one of us on it).

I'd be ok with alpha being burst=true - alpha after all will give us experimentation time on what we need.

**Comment by dhilipkumars** [comment]
+1 for this
```
statefulset.alpha.kubernetes.io/burst=true
```

**Comment by hjacobs** [comment]
I think we are also interested in this feature for our PostgreSQL/[Spilo](https://github.com/zalando/spilo)/[Patroni](https://github.com/zalando/patroni) clusters. /cc @CyberDem0n
