### ISSUE TITLE
kubefed should use the right RBAC API version depending on the host cluster

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#41263]
We made a few changes to RBAC policies in PR #40392 to address the issue described in #39555. RBAC API was in alpha and in Kubernetes 1.6 the API is being promoted to beta. PR #40392 only used the beta API types. This makes kubefed incompatible with pre-1.6 clusters. We should make kubefed 1.6 compatible with previous versions of the cluster. We can use the discovery API to accomplish this.

cc @kubernetes/sig-federation-bugs @shashidharatd @irfanurrehman

**Comment by qiujian16** [comment]
@madhusudancs I would like to create a PR if no one is working on this.

**Comment by irfanurrehman** [comment]
@qiujian16, Thanks for checking. I am already working on this!

**Comment by ethernetdan** [comment]
@madhusudancs @irfanurrehman can this be closed?

**Comment by madhusudancs** [comment]
Yes. PR #41830 fixed this issue.
