### ISSUE TITLE
Federation control plane should use service accounts to communicate with federated clusters

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#41267]
Our initial control plane bootstrap and cluster registration mechanisms just uploaded the credentials of the user who ran the respective scripts to the cluster hosting the federation control plane and used those user credentials to communicate with the registered clusters. Uploading and using a single user's credentials for cluster-wide operations is a bad idea and many people have voiced their concerns about this. While `kubefed` did not cause any regression here, it perpetuated the mistake. 

@nikhiljindal, @erictune and I discussed a bunch of potential solutions:
1. Make each cluster in the federation recognize the public keys of all the clusters in the federation. The public key is part of the key-pair used to mint service account tokens in the respective clusters. This way each cluster can authenticate the token minted by the any other cluster in the federation. With this setup, the federation control plane can use the default service account in its namespace on any host cluster to make calls to the federated clusters.
2. Teach federation control plane how to create its own service accounts and mint its own tokens. Then make all the clusters in the federation recognize federation control plane’s public key. This way federation control plane can make calls to the federated clusters using its own service account and clusters just accept that.
3. Every time a cluster is joined to the federation, create a new service account in the `federation-system` namespace of the cluster being joined. Then wait for the token corresponding to the service account to appear and make that token available to the federation control plane in the host cluster, i.e. make it available as a secret in the host cluster’s `federation-system` namespace by essentially copying the token secret from the joining cluster to the host cluster.

All the three proposed solutions have to deal with key rotations. We don’t have a good story around key rotations even in the single cluster Kubernetes world today. So irrespective of the solution we choose from the above three proposals, we are going to wait for the key rotation support to mature in the Kubernetes land before implementing it in federation. For now we are going to ask the federation administrators to update the keys manually when they change.

The problem with the first two approaches is that the individual cluster’s recognized public key list must be updated each time a cluster is joined to the federation. Since this is done by passing the `--service-account-key-file` flag to the kube-apiserver, kube-apiserver must be restarted to update this flag value. This leads to a poor user experience. And on some installations such as GKE it is impossible to update the flags or restart the API server today. This is even more aggravated in the case of first solution above because the users have to restart all the clusters every time a new cluster is added to the federation. So given these downsides of the first two solutions, we are left with the third.

`kubefed` should implement the solution proposed in (3) above.

cc @kubernetes/sig-federation-bugs @nikhiljindal @liggitt @erictune @irfanurrehman @shashidharatd

**Comment by perotinus** [comment]
I'm currently taking a look at this.

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by nikhiljindal** [comment]
Thanks for the great writeup Madhu.

As discussed today, I see 2 use cases for federation:
* Admin sets up federation and provides it for developers to use. In this case, federation can be considered a system component and using service account sg.
* A developer who has access to multiple clusters can set up federation for his own ease of use. In this case, the developer might not have permission to create new service accounts (he only has access to CRUD deployment, configmaps, etc). He should be able to pass on his credentials for federation to use.

So we should support both the cases. Federation just wants a secret with credentials that it can use. That secret can contain service account token or users credential, both should work.

**Comment by erictune** [comment]
Option 3 works for federation controllers, but it does not work for pod-to-pod communication cross cluster.  

For (1) there are some sub-options:
- option 1A: each cluster produces identities which are scoped to that cluster, but the federated clusters trust each other to provide identities scoped to each cluster.  But a User from cluster A initially has no permissions in cluster B until authorization is added.
- option 1B: all clusters produce identities which are not cluster scoped, and so identity X on cluster A is usable as identity X on cluster B after federation.
