### ISSUE TITLE
kubefed init should generate username/password for admin account and tokens for components

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#41265]
`kubefed init` only generates TLS certs and keys for authentication with the federation API server. It should also generate basic username/password and tokens to make it easier for clients to communicate with the federation API server.

cc @kubernetes/sig-federation-bugs

**Comment by liggitt** [comment]
I'd recommend tokens over basic auth

**Comment by madhusudancs** [comment]
@liggitt is it reasonable to provide support for both with an option to selectively disable them?

**Comment by madhusudancs** [comment]
@perotinus will be working on this issue. He isn't in the assignees list. So I am assigning this to myself as a place holder.
