### ISSUE TITLE
godep restore error

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#41269]
I manually cleaned out my GOPATH and ran:

```
$ godep restore
godep: Dep (k8s.io/heapster/metrics/apis/metrics/v1alpha1) restored, but was unable to load it with error:
        Package (k8s.io/apimachinery/pkg/openapi) not found
godep: Error checking some deps.
```

**Comment by lavalamp** [comment]
@gmarek @deads2k Does one of you understand this?

**Comment by shyamjvs** [comment]
@lavalamp I tried running godep restore starting from a clean slate (new GOPATH with just k8s repo in it) and it worked fine. Checked it with 2 godep versions (v74 and v78) and both seem to work ok. Could you tell the godep version you're using and also if you started out with just the k8s repo inside GOPATH? Also, the package 'k8s.io/apimachinery/pkg/openapi' shouldn't even be fetched as it's not a dependency.

**Comment by caesarxuchao** [comment]
I tried on master (0a124f2d1e217e150244def243ee3c4991095274) godep worked. What's the exact commit you tried godep with?

**Comment by gmarek** [comment]
@lavalamp - I never saw this kind of error in my very limited and very painful history with godeps. My guess would be that you have some issue with apimachinery repo (e.g. it's synced to the master of expected version or sth). Whenever I had any problems I ended up deleting most of the things under `$GOPATH/src` (or temporary moving to some other place if I didn't want to get rid of it), which usually solved all such problems.

**Comment by deads2k** [comment]
@lavalamp heapster introduces cycles into our godep graph which results in craziness as you try to have both heapster and kubernetes in place.  That's the reason we have a lot of empty folders sitting around.

My guess would be that you have a current heapster and an old apimachinery.

**Comment by mbohlool** [comment]
I've tried from a clean state following steps in https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md and I got the same error (many of them):
```bash
$GOPATH/src/k8s.io/kubernetes (master)$ godep restore
godep: Dep (k8s.io/metrics/pkg/apis/custom_metrics) restored, but was unable to load it with error:
        Package (k8s.io/apimachinery/pkg/api/resource) not found
godep: Dep (k8s.io/metrics/pkg/apis/custom_metrics/install) restored, but was unable to load it with error:
        Package (k8s.io/apimachinery/pkg/apimachinery/announced) not found
godep: Dep (k8s.io/metrics/pkg/apis/custom_metrics/v1alpha1) restored, but was unable to load it with error:
        Package (k8s.io/apimachinery/pkg/api/resource) not found
godep: Dep (k8s.io/metrics/pkg/apis/metrics) restored, but was unable to load it with error:
        Package (k8s.io/apimachinery/pkg/apis/meta/v1) not found
godep: Dep (k8s.io/metrics/pkg/apis/metrics/install) restored, but was unable to load it with error:
        Package (k8s.io/apimachinery/pkg/apimachinery/announced) not found
godep: Dep (k8s.io/metrics/pkg/apis/metrics/v1alpha1) restored, but was unable to load it with error:
        Package (k8s.io/apimachinery/pkg/api/resource) not found
godep: Dep (k8s.io/metrics/pkg/client/clientset_generated/clientset) restored, but was unable to load it with error:
        Package (k8s.io/client-go/discovery) not found
godep: Dep (k8s.io/metrics/pkg/client/clientset_generated/clientset/fake) restored, but was unable to load it with error:
        Package (k8s.io/apimachinery/pkg/runtime) not found
godep: Dep (k8s.io/metrics/pkg/client/clientset_generated/clientset/scheme) restored, but was unable to load it with error:
        Package (k8s.io/apimachinery/pkg/apis/meta/v1) not found
godep: Dep (k8s.io/metrics/pkg/client/clientset_generated/clientset/typed/metrics/v1alpha1) restored, but was unable to load it with error:
        Package (k8s.io/apimachinery/pkg/apis/meta/v1) not found
godep: Dep (k8s.io/metrics/pkg/client/clientset_generated/clientset/typed/metrics/v1alpha1/fake) restored, but was unable to load it with error:
        Package (k8s.io/apimachinery/pkg/apis/meta/v1) not found
godep: Dep (k8s.io/metrics/pkg/client/custom_metrics) restored, but was unable to load it with error:
        Package (k8s.io/apimachinery/pkg/api/meta) not found
godep: Dep (k8s.io/metrics/pkg/client/custom_metrics/fake) restored, but was unable to load it with error:
        Package (k8s.io/apimachinery/pkg/labels) not found
godep: Error checking some deps.
```

My go[dep] version:

```
$GOPATH/src/k8s.io/kubernetes (master)$ go version
go version go1.7.3 linux/amd64
$GOPATH/src/k8s.io/kubernetes (master)$ godep version
godep v74 (linux/amd64/go1.6.3)
$GOPATH/src/k8s.io/kubernetes (master)$ 
```

**Comment by mbohlool** [comment]
This is how I made it work:

```
$GOPATH/src/k8s.io/kubernetes (master)$ go get k8s.io/apimachinery/...
go build k8s.io/apimachinery/pkg/runtime/serializer/recognizer/testing: no buildable Go source files in /usr/local/google/home/mehdy/tmp/src/k8s.io/apimachinery/pkg/runtime/serializer/recognizer/testing
$GOPATH/src/k8s.io/kubernetes (master)$ go get k8s.io/client-go/...
$GOPATH/src/k8s.io/kubernetes (master)$ godep restore
$GOPATH/src/k8s.io/kubernetes (master)$
```

I am not sure why it passes for you guys, is it possible that you somehow have `client-go` and `apimachinery` in path somewhere?

**Comment by caesarxuchao** [comment]
Please use hack/godep-restore.sh instead. It takes care of the staging folders.

**Comment by gmarek** [comment]
I think that recommended procedure for working with godeps now is:
- create a brand new, empty directory for your kubernetes code and set the GOPATH accordingly (e.g. `mkdir -p ~/godep_go/src/k8s.io/kuberenetes && export GOPATH=~/godep_go`)
- copy your kubernetes code there
- run `hack/godep-restore.sh`
- do whatever you need.

It worked for me twice recently, so I believe we can close this bug with that.
