### ISSUE TITLE
staging/copy.sh (or my env) seems broken

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#41270]
```
$ staging/copy.sh 
**PLEASE** run "godep restore" before running this script
creating the tmp directory
copying client packages
generating vendor/
moving vendor/k8s.io/kubernetes
cp: cannot stat ‘/usr/local/google/home/dbsmith/code/k2//src/k8s.io/kubernetes/staging/src/k8s.io/_tmp/vendor/k8s.io/kubernetes/*’: No such file or directory
$ git log -n 1
commit b88b31cff495d0feeafaa3d08dd1b3cc93b3434b
```

I also can't run staging/prime-apimachinery.sh, but I'm not sure if I should be able to or not.

(yes, I ran godep restore, hopefully #41269 is not a big deal)

**Comment by caesarxuchao** [comment]
Hmm, maybe it's your godep version. Mine is godep v75 (darwin/amd64/go1.7.4). I tried on master (0a124f2d1e217e150244def243ee3c4991095274) and it worked.
