### ISSUE TITLE
Inter Services communication not working with Kube DNS

### ISSUE THREAD

**Issue by githubvick** [kubernetes/kubernetes#41284]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
Yes

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):  No issues found. Keywords-  kube-dns services communication kubernetes issue
No duplicates
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"87d9d8d7bc5aa35041a8ddfe3d4b367381112f89", GitTreeState:"clean", BuildDate:"2017-01-23T14:15:25Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"87d9d8d7bc5aa35041a8ddfe3d4b367381112f89", GitTreeState:"clean", BuildDate:"2017-01-23T14:15:25Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Virtual Box
- **OS** (e.g. from /etc/os-release): CentOS Linux release 7.3.1611 (Core
- **Kernel** (e.g. `uname -a`):Linux kubemaster 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kube-dns
- **Others**: Flannel

**What happened**:
Services not able to communicate with each other. Coming here as a last resort as no one was able to help out in Slack or in Stackoverflow which made me think that it is a bug. Kindly let me know how to resolve it.

**What you expected to happen**:
Interservice communication should happen properly

**How to reproduce it** (as minimally and precisely as possible):
Detailed explanation provided in the stackoverflow link

http://stackoverflow.com/questions/42148208/kubernetes-service-communication-isse-kubedns

**Anything else we need to know**:

nslookup works with one pod but doesnt in another. 

```
root@webapp:/# nslookup mongoservice
Server:		10.254.0.2
Address:	10.254.0.2#53

Non-authoritative answer:
Name:	mongoservice.default.svc.cluster.local
Address: 10.254.103.104

root@mongodb:/# cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local federated.fds
nameserver 10.254.0.2
nameserver 8.8.8.8
nameserver 8.8.4.4
options ndots:5
root@mongodb:/# 
root@mongodb:/# nslookup kubernetes
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find kubernetes: NXDOMAIN

root@mongodb:/# nslookup kubernetes.default.svc.cluster.local
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find kubernetes.default.svc.cluster.local: NXDOMAIN

```
Think it might be a duplicate of https://github.com/kubernetes/kubernetes/issues/21613 but the difference being that the container that runs on the same node as that of kube-dns works but the container that runs in a different node from that of kube-dns doesn't work.

**Comment by githubvick** [comment]
Since I was using the flannel network, there was an issue with the communication between the pods in the flannel network.

Particularly this part, FLANNEL_OPTIONS="--iface=eth1" to be set as without it, it takes up the default interface and doesn't work. So, added the parameter and it worked. Thanks.

**Comment by vinaytv** [comment]
Can you share output of 
kubectl get networkpolicy
