### ISSUE TITLE
Image updates appear to have broken CI

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#41283]
The following tests suites are failing for the `release-1.5` branch:
* [ci-kubernetes-e2e-gce-slow-release-1.5](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-slow-release-1.5)
  * [Started failing](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-slow-release-1.5?before=2437) when PR https://github.com/kubernetes/kubernetes/pull/40831 was merged.
* [ci-kubernetes-e2e-gke-slow-release-1.5](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-slow-release-1.5)
  * [Started failing](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-slow-release-1.5?before=2466) when PR https://github.com/kubernetes/kubernetes/pull/40321 was merged.
* [ci-kubernetes-e2e-gci-gce-serial-release-1.5](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial-release-1.5)
  * Started failing when PR https://github.com/kubernetes/kubernetes/pull/41218 was merged
* [ci-kubernetes-e2e-gci-gce-reboot-release-1.5](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-reboot-release-1.5)
  * Started failing when https://github.com/kubernetes/kubernetes/pull/41218 was merged.

The following tests suites are failing for the `release-1.4` branch:
* [ci-kubernetes-e2e-gce-slow-release-1.4](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-slow-release-1.4) 
  * [Started failing](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-slow-release-1.4?before=2334) when PR https://github.com/kubernetes/kubernetes/pull/40833 was merged
* [ci-kubernetes-e2e-gke-slow-release-1.4](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-slow-release-1.4)
  * Unclear root cause PR.

These broken tests suites are preventing a go/no-go signal and blocking the 1.4.9 and 1.5.3 releases. Marking this as P0.

CC @jessfraz @dchen1107 @zmerlynn @timstclair @kubernetes/sig-node-bugs

**Comment by jessfraz** [comment]
Ah this one too [ci-kubernetes-e2e-gci-gce-reboot-release-1.4](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-reboot-release-1.4)

**Comment by saad-ali** [comment]
Rolling back the image changes in https://github.com/kubernetes/kubernetes/pull/41370 appears to have fixed this
