### ISSUE TITLE
Please provide release dates in CHANGELOG.md

### ISSUE THREAD

**Issue by mc0e** [kubernetes/kubernetes#41286]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): changelog

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Kubernetes version** (use `kubectl version`): HEAD

**Environment**: n/a
- **Cloud provider or hardware configuration**: n/a
- **OS** (e.g. from /etc/os-release): n/a
- **Kernel** (e.g. `uname -a`): n/a
- **Install tools**: n/a
- **Others**: n/a

**What happened**:  Looked at CHANGELOG.md to see if a feature committed at a known date would be likely to be in my version

**What you expected to happen**: Expected to find dates listed with each release version

**How to reproduce it** (as minimally and precisely as possible): read CHANGELOG.md

**Anything else we need to know**: no

**Comment by shiywang** [comment]
I think add release dates make people get more information about the history of kubernetes. Is there anyone knows how to check the the accurate date of every version release, I would like to add that information if I know how to check that.

**Comment by calebamiles** [comment]
@mc0e, @shiywang I think it would possibly make more sense to link the sections in `CHANGELOG.md`to the corresponding release from [the releases page](https://github.com/kubernetes/kubernetes/releases) which includes the git SHA of the tag as well as when the release was created. The releases page links to `CHANGELOG.md` but not the other way around. I would also rather have GitHub work out time differences between localities rather than choosing an essentially arbitrary timezone like UTC. How does that sound?

**Comment by shiywang** [comment]
@calebamiles thanks for you suggestion, but I still think directly add the release date in `CHANGELOG.md` would be clear at a glance for users, check out those popular projects in github: [angular](https://github.com/angular/angular/blob/master/CHANGELOG.md), [docker](https://github.com/docker/docker/blob/master/CHANGELOG.md), [react](https://github.com/facebook/react/blob/master/CHANGELOG.md)... most of large projects with `CHANGELOG.md` I've ever seen in github have a release date. or do you have any other concern ?

**Comment by mc0e** [comment]
I think the changelog should stand alone without needing exploration of the git metadata.
