### ISSUE TITLE
v1beta1.ReplicaSetList.items is null

### ISSUE THREAD

**Issue by tutman96** [kubernetes/kubernetes#41294]
Kubernetes Server Version: v1.5.2
Client Version: N/A
Environment: GKS

When a ReplicaSetList is queried through `/apis/extensions/v1beta1/namespaces/default/replicasets` and no replica sets exist or none are matched with labelSelector, the results look like this:

```json
{
  "kind": "ReplicaSetList",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "selfLink": "/apis/extensions/v1beta1/namespaces/default/replicasets",
    "resourceVersion": "24198530"
  },
  "items": null
}
```

however, in previous versions (on server v1.4.7 at least), the results would be:

```json
{
  "kind": "ReplicaSetList",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "selfLink": "/apis/extensions/v1beta1/namespaces/default/replicasets",
    "resourceVersion": "24198530"
  },
  "items": []
}
```
(notice the "items" field is empty array vs null)

These results also don't follow the api doc [https://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/#_v1beta1_replicasetlist](https://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/#_v1beta1_replicasetlist) as it says the "items" field is required and is an array of ReplicaSet.

**Comment by liggitt** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/39888

Will be in 1.5.3
