### ISSUE TITLE
federation API not in client-go

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#41302]
The federation objects are not currently in client-go.  I believe this makes it hard/impossible to use federation with client-go.  The challenges I hit:

* you would have to refer to the main kubernetes/kuberentes repo again for the federation objects
* mixing and matching the federation objects from kubernetes/kubernetes is tricky, because for example ClusterSpec has a SecretRef field which is of type `k8s.io/kubernetes/pkg/api/v1.LocalObjectReference`, but in client-go view that is `k8s.io/client-go/pkg/api/v1...` which is different.

I think we need to include the federation objects into client-go.

**Comment by liggitt** [comment]
cc @kubernetes/sig-api-machinery-misc @kubernetes/sig-federation-feature-requests

**Comment by sttts** [comment]
We could blindly copy federation types into client-go as well. But I would very much prefer to start thinking about making client-go more composable to avoid that it becomes our new monolith repo. /cc @deads2k

**Comment by deads2k** [comment]
> We could blindly copy federation types into client-go as well. But I would very much prefer to start thinking about making client-go more composable to avoid that it becomes our new monolith repo. /cc @deads2k

I agree.  We need to think about how different client-go APIs interact and build on top of each other instead of simply producing a copy/paste which can never be extended.  As we get more aggregated API servers like service-catalog and (hopefully) podinjectionpolicy, this becomes even more obvious.

@lavalamp @caesarxuchao

**Comment by lavalamp** [comment]
client-go should not be a grab bag for clients for all APIs. The long term plan here is to have a two-layer client structure.

* client-core contains things like RESTClient, discovery client, dynamic client, transport, informers, etc.
* client-go contains the API types and generated code

Other projects (like federation) can host their own version of the latter.

Additionally I'd like to get to a point where we can generate a client specifically for a user, given their cluster's OpenAPI spec.

**Comment by caesarxuchao** [comment]
I agree with @lavalamp's vision.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#206.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
