### ISSUE TITLE
kubefed init fails

### ISSUE THREAD

**Issue by bruceauyeung** [kubernetes/kubernetes#41305]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug report

**Kubernetes version** (use `kubectl version`):
kubectl , kubefed, kubeadm binary version: compiled from master today
kubectl version:
>\# ./kubectl version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.8rc3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.1", GitCommit:"424a0e9e827a39c714ee03e1891c43635adabcdc", GitTreeState:"clean", BuildDate:"2017-01-31T02:31:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

my cluster is bootstrapped by kubeadm

**Environment**:
- **Cloud provider or hardware configuration**: hardware
- **OS** (e.g. from /etc/os-release): centOS 7.2 64bit
- **Kernel** (e.g. `uname -a`): 
>\# uname -a
Linux vmwarecgsl5.localdomain 3.10.0-327.22.2.el7.x86_64 #1 SMP Fri Nov 4 01:46:03 CST 2016 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**:
- **Others**:

**What happened**:
when i ran `./kubefed  init brucetest --host-cluster-context=kubernetes-admin@kubernetes  --dns-zone-name=example.com --kubeconfig=/etc/kubernetes/admin.conf --image=gcr.io/google_containers/hyperkube-amd64:v1.6.0-alpha.1 --api-server-service-type=NodePort --storage-backend=etcd3 --etcd-persistent-storage=false`, it exited with error message:
>error: context "brucetest" does not exist

**What you expected to happen**:

kubefed initialize a federation control plane successfully

**Comment by bruceauyeung** [comment]
cc @madhusudancs

**Comment by irfanurrehman** [comment]
@bruceauyeung, can u please run it (kubefed init) again with more verbose option (say --v=6) and then take the log.
thanks!

**Comment by bruceauyeung** [comment]
@irfanurrehman @madhusudancs the logs are very huge, so i pasted it here:
http://pastebin.com/raw/7L1BsKF0

**Comment by irfanurrehman** [comment]
@bruceauyeung, there seemed to be an issue in kubefed.
You can please pull the commit in the PR I raised, if you want to verify and confirm before it gets merged.

thanks!

**Comment by bruceauyeung** [comment]
@irfanurrehman after pulled your commit #41410 , the problem i mentioned above is gone. but the init process fall into an indefinite loop:
>I0215 23:45:03.520854    7427 round_trippers.go:417] GET https://:30868/healthz  in 1 milliseconds
I0215 23:45:03.520886    7427 round_trippers.go:423] Response Headers:
I0215 23:45:05.519625    7427 round_trippers.go:398] curl -k -v -XGET  -H "User-Agent: kubefed/v0.0.0 (linux/amd64) kubernetes/$Format" -H "Authorization: Basic YWRtaW46" -H "Accept: application/json, */*" https://:30868/healthz
I0215 23:45:05.520732    7427 round_trippers.go:417] GET https://:30868/healthz  in 1 milliseconds
I0215 23:45:05.520772    7427 round_trippers.go:423] Response Headers:
I0215 23:45:07.519576    7427 round_trippers.go:398] curl -k -v -XGET  -H "Authorization: Basic YWRtaW46" -H "Accept: application/json, */*" -H "User-Agent: kubefed/v0.0.0 (linux/amd64) kubernetes/$Format" https://:30868/healthz
I0215 23:45:07.520427    7427 round_trippers.go:417] GET https://:30868/healthz  in 0 milliseconds
I0215 23:45:07.520452    7427 round_trippers.go:423] Response Headers:
I0215 23:45:09.519252    7427 round_trippers.go:398] curl -k -v -XGET  -H "User-Agent: kubefed/v0.0.0 (linux/amd64) kubernetes/$Format" -H "Accept: application/json, */*" -H "Authorization: Basic YWRtaW46" https://:30868/healthz
I0215 23:45:09.520359    7427 round_trippers.go:417] GET https://:30868/healthz  in 1 milliseconds
I0215 23:45:09.520398    7427 round_trippers.go:423] Response Headers:
I0215 23:45:11.519118    7427 round_trippers.go:398] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubefed/v0.0.0 (linux/amd64) kubernetes/$Format" -H "Authorization: Basic YWRtaW46" https://:30868/healthz
I0215 23:45:11.520242    7427 round_trippers.go:417] GET https://:30868/healthz  in 1 milliseconds
I0215 23:45:11.520280    7427 round_trippers.go:423] Response Headers:
I0215 23:45:13.519684    7427 round_trippers.go:398] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubefed/v0.0.0 (linux/amd64) kubernetes/$Format" -H "Authorization: Basic YWRtaW46" https://:30868/healthz
I0215 23:45:13.520669    7427 round_trippers.go:417] GET https://:30868/healthz  in 0 milliseconds
........ignored


in `journalctl -f` there are some repeated errors i think maybe helpful:
>Feb 15 23:43:17 vmwarecgsl5.localdomain kubelet[2161]: I0215 23:43:17.492136    2161 docker_manager.go:2524] checking backoff for container "controller-manager" in pod "brucetest-controller-manager-3572812626-339xd"
Feb 15 23:43:17 vmwarecgsl5.localdomain kubelet[2161]: I0215 23:43:17.492245    2161 docker_manager.go:2538] Back-off 1m20s restarting failed container=controller-manager pod=brucetest-controller-manager-3572812626-339xd_federation-system(f5134f96-f394-11e6-9819-000c2972045a)
Feb 15 23:43:17 vmwarecgsl5.localdomain kubelet[2161]: E0215 23:43:17.492280    2161 pod_workers.go:184] Error syncing pod f5134f96-f394-11e6-9819-000c2972045a, skipping: failed to "StartContainer" for "controller-manager" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=controller-manager pod=brucetest-controller-manager-3572812626-339xd_federation-system(f5134f96-f394-11e6-9819-000c2972045a)"

and should i file a new issue about this indefinite loop ?

**Comment by madhusudancs** [comment]
@bruceauyeung 

> and should i file a new issue about this indefinite loop ?

Not necessary. It is already being tracked in https://github.com/kubernetes/kubernetes/issues/41127#issuecomment-278883918. @shashidharatd's PR to fix it is in https://github.com/kubernetes/kubernetes/pull/41243.
