### ISSUE TITLE
Kubeadm alpha 1.6.0  CSR stuck

### ISSUE THREAD

**Issue by spacexnice** [kubernetes/kubernetes#41317]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

yes ,   here is the kubeadm join --discovery token://xxxx:xxxxxxxx:ip:port   output.

```
[discovery] Cluster info object received, verifying signature using given token
[discovery] Cluster info signature and contents are valid, will use API endpoints [https://192.168.1.194:6443]
[bootstrap] Trying to connect to endpoint https://192.168.1.194:6443
[bootstrap] Endpoint check failed [failed to connect to "https://192.168.1.194:6443" [the server has asked for the client to provide credentials]]
[bootstrap] Trying to connect to endpoint https://192.168.1.194:6443
[bootstrap] Endpoint check failed [failed to connect to "https://192.168.1.194:6443" [the server has asked for the client to provide credentials]]
[bootstrap] Trying to connect to endpoint https://192.168.1.194:6443
[bootstrap] Endpoint check failed [failed to connect to "https://192.168.1.194:6443" [the server has asked for the client to provide credentials]]
[bootstrap] Trying to connect to endpoint https://192.168.1.194:6443
[bootstrap] Endpoint check failed [failed to connect to "https://192.168.1.194:6443" [the server has asked for the client to provide credentials]]
[bootstrap] Trying to connect to endpoint https://192.168.1.194:6443
[bootstrap] Endpoint check failed [failed to connect to "https://192.168.1.194:6443" [the server has asked for the client to provide credentials]]
```

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):  Ubuntu 16.04.1 
- **Kernel** (e.g. `uname -a`): Linux iZbp183y9yc2ch8w1f3u5jZ 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:  Kubeadm
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by luxas** [comment]
This has been fixed with the v1.6 release
