### ISSUE TITLE
Custom DNS entries for kube-dns

### ISSUE THREAD

**Issue by morallo** [kubernetes/kubernetes#41328]
**Is this a request for help?**: No.

**What keywords did you search in Kubernetes issues before filing this one?**: kube-dns custom dns entry

---

**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

**Kubernetes version** (use `kubectl version`): v1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: baremetal, 
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- **Kernel** (e.g. `uname -a`): 3.16.7
- **Install tools**: [docker-multinode](https://github.com/kubernetes/kube-deploy/tree/master/docker-multinode).

**What happened**: Entries in /etc/hosts of the nodes are not used by kube-dns. There is no way to replicate this custom DNS configuration for the cluster.

**What you expected to happen**: Some way to easily define custom DNS entries used by kube-dns, without deploying an additional DNS server.

**Anything else we need to know**:

Already considered solutions:
- Use a Service without selector and external Endpoint. It won't allow full DNS names and [that won't change for the time being](https://github.com/kubernetes/kubernetes/issues/3752#issuecomment-234753025).
- Deploy an additional DNS server and add it to /etc/resolv.conf in all nodes. This would work, but it's not convenient for quick/testing deployments.
- [Define a ConfigMap with the DNS entries and add them to the dnsmasq /etc/hosts.d](http://stackoverflow.com/a/40595719/4633210). This is possible, but requires modifying kube-dns launch flags (not obvious in automated deployments like [docker-multinode](https://github.com/kubernetes/kube-deploy/pull/226)

Possible solutions:

- Implement a special ConfigMap to declare custom entries on a cluster-wide level and make kube-dns look it up.
- kube-dns imports node's `/etc/hosts` entries, like it does for /etc/resolv.conf. This is not very elegant and doesn't scale, but it replicates a capability currently existing in _non containerized_ system administration.

**Comment by morallo** [comment]
Reading [this](https://groups.google.com/d/msg/kubernetes-users/bXRxKM8WlWM/rk4HG9KOBAAJ), I don't know if this is already in the works.

@thockin could you clarify the status? Thanks!

**Comment by cmluciano** [comment]
This is recently added to kube-dns [here](https://github.com/kubernetes/dns/pull/28/files). It will be configurable through a [config-map](https://github.com/kubernetes/dns/pull/39). This functionality should land in the 1.6 release of Kube.

**Comment by morallo** [comment]
Thank you @cmluciano :-)

**Comment by thockin** [comment]
@bowei

**Comment by bowei** [comment]
@morallo -- it would be great to write up a example of what you are looking for and we can go from there.

* If they are in the cluster.local domain, it might not be a good idea given the potential for name clash.
* If they are in a separate domain (e.g. acme.local.), there is a proposal coming that will allow you to designate optional stub domains that have their own custom name servers. In that case, you can run your own dnsmasq for that domain and it will be incorporated into the namespace.

**Comment by bowei** [comment]
Open the issue on kubernetes/dns, so it will be more visible to the DNS work (kube-dns has been split off into a separate repo)...

**Comment by morallo** [comment]
Thanks all for the replies. 
Follow-up issue in kubernetes/dns: https://github.com/kubernetes/dns/issues/55
