### ISSUE TITLE
Increase in number of "ExceededGracePeriod" errors during eviction tests.

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#41347]
I have noticed 5 inode eviction test runs in the past 3 days that have failed because they evict an extra pod with the message:
`ExceededGracePeriod: Container runtime did not kill the pod within specified grace period.`

I am not sure if it is a coincidence, but they have all been on ubuntu trusty.
Runs:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-flaky/117?log#log
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-flaky/102?log#log
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-flaky/100?log#log
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-flaky/97?log#log
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-flaky/88?log#log

@kubernetes/sig-node-bugs @vishh @derekwaynecarr 

This is a separate issue to #40474, which is also a known reason that we can evict extra pods.

**Comment by dashpole** [comment]
This test has 3 pods: volume and container inode-hog-pods, which are meant to be evicted, and normal-memory-usage-pod, which is not meant to be evicted.
What happens in these runs is that the 'volume-inode-hog-pod' is evicted successfully.  Then the 'container-inode-hog-pod' is unable to be evicted with the error: ExceededGracePeriod, causing the 'normal-memory-usage-pod' to be evicted as well.

What worries me, is that in all 5 runs, not only do we fail to evict a pod and evict an innocent pod, but we then fail to evict the innocent pod as well.  This makes me wonder if this could cause a large number of pods to be evicted when only one eviction is required.

**Comment by dashpole** [comment]
I was debugging a recent case, where I saw the event: "Container runtime did not kill the pod within specified grace period", and saw the following logs:
`I0222 21:48:12.035214    3709 eviction_manager.go:325] eviction manager: pods ranked for eviction: container-inode-hog-pod_e2e-tests-inode-eviction-test-827vc(17eed503-f948-11e6-92ea-42010a80000b), normal-memory-usage-pod_e2e-tests-inode-eviction-test-827vc(1b85d6ef-f948-11e6-92ea-42010a80000b)`
`I0222 21:48:12.035393    3709 kuberuntime_container.go:535] Killing container "docker://9a4c58c575f7656066711faf414e1e4834d9d5013d19656279f36b57f2cf4029" with 30 second grace period`
`I0222 21:48:12.035408    3709 kuberuntime_container.go:547] Killing container {"docker" "9a4c58c575f7656066711faf414e1e4834d9d5013d19656279f36b57f2cf4029"}, but using 0 second grace period override`
`I0222 21:48:12.045321    3709 server.go:691] Event(v1.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-inode-eviction-test-827vc", Name:"container-inode-hog-pod", UID:"17eed503-f948-11e6-92ea-42010a80000b", APIVersion:"v1", ResourceVersion:"111", FieldPath:""}): type: 'Warning' reason: 'Evicted' The node was low on resource: nodefsInodes.`
`I0222 21:48:12.105407    3709 kubelet_pods.go:913] Killing unwanted pod "container-inode-hog-pod"`
`I0222 21:48:12.728640    3709 manager.go:955] Destroyed container: "/BestEffort/pod17eed503-f948-11e6-92ea-42010a80000b/9a4c58c575f7656066711faf414e1e4834d9d5013d19656279f36b57f2cf4029" (aliases:[k8s_container-inode-hog-pod_container-inode-hog-pod_e2e-tests-inode-eviction-test-827vc_17eed503-f948-11e6-92ea-42010a80000b_09a4c58c575f7656066711faf414e1e4834d9d5013d19656279f36b57f2cf4029], namespace: "docker")`
`I0222 21:48:13.316328    3709 handler.go:325] Added event &{/BestEffort/pod17eed503-f948-11e6-92ea-42010a80000b/9a4c58c575f7656066711faf414e1e4834d9d5013d19656279f36b57f2cf4029 2017-02-22 21:48:13.316316652 +0000 UTC containerDeletion {<nil>}}`
`I0222 21:48:12.729215    3709 status_manager.go:444] Status for pod "container-inode-hog-pod_e2e-tests-inode-eviction-test-827vc(17eed503-f948-11e6-92ea-42010a80000b)" updated successfully: {status:{Phase:Failed Conditions:[] Message:The node was low on resource: nodefsInodes. Reason:Evicted HostIP: PodIP: StartTime:0xc421083220 InitContainerStatuses:[] ContainerStatuses:[] QOSClass:} version:4 podName:container-inode-hog-pod podNamespace:e2e-tests-inode-eviction-test-827vc}`
`I0222 21:48:13.316961    3709 kuberuntime_container.go:535] Killing container "docker://9a4c58c575f7656066711faf414e1e4834d9d5013d19656279f36b57f2cf4029" with 30 second grace period`
`I0222 21:48:13.317077    3709 kuberuntime_container.go:554] Container "docker://9a4c58c575f7656066711faf414e1e4834d9d5013d19656279f36b57f2cf4029" exited normally`
`I0222 21:48:13.317893    3709 generic.go:146] GenericPLEG: 17eed503-f948-11e6-92ea-42010a80000b/9a4c58c575f7656066711faf414e1e4834d9d5013d19656279f36b57f2cf4029: running -> exited`
`I0222 21:48:13.832382    3709 server.go:691] Event(v1.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-inode-eviction-test-827vc", Name:"container-inode-hog-pod", UID:"17eed503-f948-11e6-92ea-42010a80000b", APIVersion:"v1", ResourceVersion:"111", FieldPath:"spec.containers{container-inode-hog-pod}"}): type: 'Normal' reason: 'Killing' Killing container with id docker://9a4c58c575f7656066711faf414e1e4834d9d5013d19656279f36b57f2cf4029:Need to kill Pod`
`I0222 21:48:13.835461    3709 plugins.go:410] Calling network plugin kubenet to tear down pod "container-inode-hog-pod_e2e-tests-inode-eviction-test-827vc"`
`I0222 21:48:13.842207    3709 kubenet_linux.go:471] Failed to remove pod IP 10.180.0.2 from shaper: Failed to find cidr: 10.180.0.2/32 on interface: cbr0`
`I0222 21:48:13.881578    3709 kubenet_linux.go:789] Removing e2e-tests-inode-eviction-test-827vc/container-inode-hog-pod from 'kubenet' with CNI 'bridge' plugin and runtime: &{ContainerID:803cbbd3b1f03e7c3beaede1849b5d6d306b19516c688f744de3ca02807f4156 NetNS:/proc/3746/ns/net IfName:eth0 Args:[]}`
`I0222 21:48:13.881943    3709 kuberuntime_manager.go:833] getSandboxIDByPodUID got sandbox IDs ["803cbbd3b1f03e7c3beaede1849b5d6d306b19516c688f744de3ca02807f4156"] for pod "container-inode-hog-pod_e2e-tests-inode-eviction-test-827vc(17eed503-f948-11e6-92ea-42010a80000b)"`
`I0222 21:48:13.881981    3709 kuberuntime_container.go:554] Container "docker://9a4c58c575f7656066711faf414e1e4834d9d5013d19656279f36b57f2cf4029" exited normally`
`W0222 21:48:14.431681    3709 kuberuntime_container.go:436] No ref for container {"docker" "9a4c58c575f7656066711faf414e1e4834d9d5013d19656279f36b57f2cf4029"}`
`I0222 21:48:14.035461    3709 eviction_manager.go:350] eviction manager: pod container-inode-hog-pod_e2e-tests-inode-eviction-test-827vc(17eed503-f948-11e6-92ea-42010a80000b) failed to evict timeout waiting to kill pod`

It appears that during eviction, since we have a grace period of 0, we set the timeout for a response from the runtime to 2 seconds (in pod_workers.go:296), which is timing out, and causing eviction of a pod to fail.

@yujuhong would it make sense to increase this timeout?

**Comment by derekwaynecarr** [comment]
Do we know the typical time to kill?  I guess I would increase a timeout
first if we had a reasonable waiting period in mind.  The current choice
was an initial estimate.

**Comment by dashpole** [comment]
@derekwaynecarr I dont have any metrics.  I would think just over 2 seconds should suffice, as I was seeing flakes in 1/10 inode eviction runs.  I can try and get some more concrete data soon.

**Comment by dashpole** [comment]
I looked at 45 minutes of eviction tests (6 runs), and found that the time this took ranged from 200ms to a max of 2.5s.  I can run a couple more rounds of that, if it would help.  The time taken should depend on whether or not there is another update underway when the SyncPodKill update is performed, which may be the reason for the wide range of times.

**Comment by dashpole** [comment]
Did another 45 minutes (7 runs, this time), and had a max of 3.2 seconds.

**Comment by dashpole** [comment]
Ok, the third (and my final) run had a max of 1.5 seconds.  I propose setting it to 4 seconds for now.  @derekwaynecarr Is there any potential downside of increasing it to 4 seconds?

**Comment by vishh** [comment]
IIRC, the graceperiod for docker is 2 seconds and even that depends on how quickly the kernel responds to process deletion. If a process has a pending IO operation it can get stuck.
I don't think we offer any system wide SLO for pod deletions as of now and so increasing the graceperiod should be OK i think

**Comment by dashpole** [comment]
closing via #42015
