### ISSUE TITLE
Add a configmap manager to cache duplicate configmaps

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#41379]
Clone of https://github.com/kubernetes/kubernetes/issues/19188 for configmaps

A secret manager was added to the kubelet to reduce duplicate requests for secrets (if a secret was used in multiple volumes, pull secrets, and envvars)

The same should be done for configmaps to keep parity between those two objects.

cc @wojtek-t @yujuhong

**Comment by wojtek-t** [comment]
@shyamjvs
