### ISSUE TITLE
Move fluentd images to contrib repo

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#41393]
Fluentd image should not be a part of core Kubernetes. Fluentd configuration should be passed via ConfigMap.

cc @fgrzadkowski @igorpeshansky @qingling128

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by crassirostris** [comment]
It's done actually

**Comment by piosz** [comment]
@crassirostris please attache related PRs

**Comment by crassirostris** [comment]
Removal from the `kubernetes` repo: https://github.com/kubernetes/kubernetes/pull/42127
Moving to the `contrib` repo: https://github.com/kubernetes/contrib/pull/2426

**Comment by piosz** [comment]
@crassirostris thanks!
