### ISSUE TITLE
Deployment should support both Failure Domains and Update Domains

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes#41394]
Feature Request: Deployments should support the concepts of Failure Domains and Update Domains as first class citizens and it should be easy to request those features in the Deployment Spec.

Currently Kubernetes Deployments can spread pods across failure zones using the annotations  `failure-domain.beta.kubernetes.io/zone` on a best effort basis.We can make that a hard requirements by using pod anti affinity which requires some expression. Making pods spread across failure domains on a best effort basis or as a hard requirement should be as simple as flipping a switch in Deployment. We shouldnt have to write a pod anti affinity rule to achieve this. 

Deployments while they support the concept of failure domains, do not have any such understanding of update domains. What that means is that an application can define what set of pods belong to which update domains and when doing a Rolling Update, only pods belonging to a single update domain are brought down at a time. This could potentially in the simplest case using the rack as a update domain, so Deployments spreads pods across racks and while updating only brings down pods per rack at a time. 

We should support both these feature in an easy to use way. 
Looking to see what others think in this area.
@kargakis @janetkuo @brendandburns @smarterclayton @thockin @nikhiljindal

**Comment by thockin** [comment]
This feels like a specific form of topological consideration.  I am finally going to open an issue on that.

**Comment by smarterclayton** [comment]
update domain sounds like something that is part of the deployment strategy and is related to custom deployment strategies, of which we have burned lots of electrons discussing.

We have a large number of deployments today that are not using `failure-domain.beta.kubernetes.io/zone` but instead using custom labels, sometimes with overlapping sets.  Something simple in deployment wouldn't really help those users.

**Comment by smarterclayton** [comment]
PodInjectionPolicy is also relevant for affinity @pmorie @jessfraz

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/issues/41442

**Comment by davidopp** [comment]
Straw man possible solution:

Add two new fields to DeploymentSpec’s rolling update spec:
* topology key
* rolling group axis (straw man values: “x” or “y” -- “x” means take down “maxUnavailable” spread across nodes with the same value of the topology key, while “y” means take down “maxUnavailable” all with the same value of the topology key)

**Comment by bgrant0607** [comment]
See also #4301

**Comment by krmayankk** [comment]
@davidopp thanks for the straw man. I am thinking people often need y axis part. I think in the long run we need a simple configuration parameters which says  the following in the DeploymentSpec/ReplicaSpec
```
faultDomains: 3
updateDomains: 3
maxUnavailablePerUpdateDomain: % or n 
maxUnavailableOverall: % or n
```
and the scheduler generates appropriate labels and pod anti affinity configuration which satisfies those requirements. The user doesn't have to write a pod anti affinity rule to get a spread across fault zones. We could add additional levels of failure zones(rack, chassis, room, etc) and updates zones for the scheduler to look at and make advanced decision.

Here is a possible solution:-
- Introduce additional node labels. (in the long run this should be customizable and may be made hierarchical with some weights specified at different levels)
failure-domain.beta.kubernetes.io/zone
update-domain.beta.kubernetes.io/zone

- add `failureDomains` and `updateDomains` params requested by a Deployment/Replica
- the scheduler divides the set of nodes into #failureDomains unique groups based on `failure-domain.beta.kubernetes.io/zone` labels. When spreading the pods, a pod is placed in a round robin manner , one each into the #failureDomain groups formed above.
- the scheduler divides the set of nodes into #updateDomains unique groups based on `update-domain.beta.kubernetes.io/zone` labels. When bringing down the pods, when doing a Deployment Update,  all pods from a single updateDomain group is brought down first, and when the pods in that updateDomain are all ready, the update proceeds to another group.


I think a lot of these things should be extensible using predicates or other mechanisms but for now, this should be enough. I can create a feature request and proposal doc , if everyone agree with the above. I am also happy to work on this since we need this feature urgently.

**Comment by kargakis** [comment]
Related: https://github.com/kubernetes/kubernetes/issues/4301

**Comment by kargakis** [comment]
I am still not sure why do we need to make this configurable via the Deployment API vs make it the default behavior under the covers as it already happens with placement? If the nodes are already grouped by labels into update and failure domains why can't the scheduler round-robin the pods for the workload controllers by default? We could also switch the workload controllers to use the eviction endpoint and support things like maxUnavailablePerUpdateDomain in the PDB API.

**Comment by davidopp** [comment]
@krmayankk 

It sounds like you want three things, one of which you can already do (though you're asking for auto-generation), one of which just requires having the controllers use the eviction subresource when doing rolling update and having them respond intelligently to being told "no", and one of which probably requires some more work.

Specifically:

You can do the spreading by labeling the nodes and using soft pod anti-affinity with "topologyDomain" set to the label key. You can do it hierarchically with more labels and more anti-affinity rules.

`maxUnavailableOverall` is already available with a vanilla PDB (if the controllers used the eviction subresource and knows to move on to another pod when it is rejected).

`maxUnavailablePerUpdateDomain` is a bit tricky because PDB selector is a selector over pod labels, not over node labels. But I don't think it would be hard to modify PDB to make it possible to specify a node selector in addition to the pod selector ("all pods matching this label selector that are running on nodes that match this node selector (which corresponds to a particular update domain)). I guess you'd want to do % per update domain since you can't be sure exactly how many will be scheduled into an update domain without #40358, and even then I don't think you can be completely sure.

(Note that we don't currently support > 1 PDB covering the same pod, so we'd also need to implement that if you wanted both `maxUnavailableOverall` and `maxUnavailablePerUpdateDomain` -- each pod would presumably be covered by two PDB rules)

cc/ @kubernetes/sig-scheduling-feature-requests

**Comment by krmayankk** [comment]
@bgrant0607  what does this mean to be frozen ?  i intent to write a proposal for this and get a basic version implemented

**Comment by bsalamat** [comment]
> what does this mean to be frozen ? i intent to write a proposal for this and get a basic version implemented

@krmayankk It means that the issue is not going to auto-close. You can go ahead and write your proposal.

**Comment by kargakis** [comment]
A proposal for this is out: https://github.com/kubernetes/community/pull/2045

**Comment by mlococo** [comment]
`maxUnavailablePerUpdateDomain` seems like an odd interface here. Wouldn't one of the common use cases be:

1. A distributed stateful application deployed into 3 failure domains. Let's call them rack1, rack2, and rack3.
2. 5 pods per failure domain.
3. Pods with affinity to nodes based on their physical layout. Maybe rack1 corresponds to availability-zone us-east-1a, rack2 is us-east-1b, and rack3 is us-east-1c.

The stateful application running on these pods is designed to withstand the loss of all nodes in any one rack without causing an availability impact. For example, handling the case where us-east-1a has an networking issue that causes all instances to become unreachable but us-east-1b and us-east-1c are unaffected. Perhaps this is via having replica-sets of 3 nodes, and each replica set has 1 member in each rack... so as long as all nodes in 2 of 3 racks are alive then quorum can be achieved in every replica set.

Does the straw man proposal offer a mechanism for specifying the disruption budget of this common scheme? In this scheme the concern is less about the number of available pods per update domain, and more about the number of update domains that are disrupted at all. We can withstand losing all the pods in any single domain, but losing the right 1 in each of two domains could cause a partial cluster outage.

**Comment by afirth** [comment]
I believe the failure domains are now done with [topologySpreadConstraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) and haven't seen anything about update domains for a few years. Does it make sense to close this issue?

**Comment by afirth** [comment]
/close

feel free to reopen if not resolved by the above solutions
