### ISSUE TITLE
What's the specification of the slave that runs "bazel build" in your jenkins CI ?

### ISSUE THREAD

**Issue by GinFungYJF** [kubernetes/kubernetes#41391]
I find it takes long time to build kubernetes. For some reason, I want to know the specification of the slave that runs bazel-build in the your CI. What's more, why your jenkins runs "bazel clean" before "bazel build" every time?

**Comment by kargakis** [comment]
A question for @kubernetes/sig-testing-misc

**Comment by spxtr** [comment]
We don't use Jenkins to run bazel builds. Instead, they're just run as a kubernetes pod using the `gcr.io/k8s-testimages/bazelbuild` image. The machines themselves are `n1-standard-4`s on GCE.

We only run `bazel clean` before `bazel build` for postsubmits, to ensure that we run all tests.

**Comment by ixdy** [comment]
@spxtr a better way to run all tests is to pass `--nocache_test_results`.

If that's the main reason we do `bazel clean`, we should fix that. :)
