### ISSUE TITLE
DNS is unavailable from container on master node

### ISSUE THREAD

**Issue by Crassirostris** [kubernetes/kubernetes#41415]
Currently, fluentd on master is unable to ingest logs from master node on GCE.

After some investigation it turned out that DNS (10.0.0.10) is unavailable from inside the fluentd container: no host can be resolved, doesn't depend on the fluentd image version. Fluentd container on the minion node works, no problems whatsoever.

Steps to reproduce:

* Spin up a cluster on GCE
* Check fluentd logs on the master node

If cluster is built from 1.5 branch, fluentd on master node works, logs are being ingested.

CC @piosz

**Comment by piosz** [comment]
cc @thockin @bowei @kubernetes/sig-network-bugs

**Comment by bowei** [comment]
This is from HEAD?

**Comment by Crassirostris** [comment]
@bowei From HEAD today, can't say the exact commit

But the problem actually is there for quite some time, for two weeks at least.

**Comment by bowei** [comment]
There are two issues at work here:
1. kube-proxy is not run on the master node, which means service VIPs will not be accessible from the master.
1. fluentd pod that runs on the master uses ClusterFirst, which means the resolv.conf points to the service VIP.

One of those needs to change for the DNS to work.

**Comment by Crassirostris** [comment]
@bowei OK, thanks! I will try to change the dnsPolicy tomorrow to see if it helps

Could you please explain what have changed since 1.5? For what I know, fluentd was moved to DaemonSet, is this the reason?

**Comment by bowei** [comment]
@piosz -- this looks like your change:

```
commit a52637f09f77e1d91bd79b33ddef7ba17542174f
Author: Piotr Szczesniak <pszczesniak@google.com>
Date:   Tue Dec 13 16:14:10 2016 +0100

    Migrated fluentd to daemon set

 cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml | 55 +++++++++++++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 55 insertions(+)
```

**Comment by thockin** [comment]
As far as I know, the master has never run kube-proxy

**Comment by piosz** [comment]
The migration to DS should be unrelated here. We used to have fluentd as manifest pod before.

**Comment by Crassirostris** [comment]
Using `dnsPolicy: Default` didn't help

Is it possible to have the same `resolv.conf` for fluentd on master as the rest of the pods?

**Comment by thockin** [comment]
Define "doesn't work" after this?  /etc/resolv.conf should show whatever
the host machine has.

**Comment by Crassirostris** [comment]
Sorry, my bad, was testing with the wrong setup. Using `dnsPolicy: Default` did indeed help for fluentd with Stackdriver, thanks a lot!
