### ISSUE TITLE
Create an e2e test to check whether system component's logs are ingested

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#41411]
Problem https://github.com/kubernetes/kubernetes/issues/40936 showed, that despite e2e tests for container's logs, we still can encounter regressions for system logs.

We need to establish an e2e test for ingesting system components's logs:

* kubelet
* docker

CC @piosz

**Comment by Crassirostris** [comment]
https://github.com/kubernetes/kubernetes/pull/41172 broke ingesting logs from master and we didn't notice it at once

Test should check that logs are present from all nodes, including master (when possible)

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by spiffxp** [comment]
/sig instrumentation

do you want this in v1.7?

@piosz @fabxc (since you're listed as sig-instrumentation leads at https://github.com/kubernetes/community/tree/master/sig-instrumentation and I can't find a team to ping)

**Comment by crassirostris** [comment]
@spiffxp No

**Comment by crassirostris** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/50904
