### ISSUE TITLE
Run some e2e tests against 2.2.1

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#41422]
There are two reasons for this.

1. We'll be supporting users running 1.6 with 2.2.1 even though we'll encourage and support upgrading to 3.0.
2. There's always the risk that 3.0 won't be ready for 1.6.

The tests listed below currently run 3.0 in v2 mode, but should be switched to bring up clusters running against 2.2.1.  This is not an exhaustive list; it's just what we have right now.  Please also consider where else we should have coverage.

- ci-kubernetes-e2e-gce
- ci-kubernetes-e2e-gci-gce (this one blocks the submit queue)
- Corresponding pull jobs

cc @wojtek-t

**Comment by calebamiles** [comment]
**cc: @ethernetdan**

**Comment by mml** [comment]
@wojtek-t I am having trouble getting clusters to come up running 2.2.1.  Wonder if you've had this problem yet.  I set these two environment variables when I bring up an e2e cluster.

```
         STORAGE_BACKEND=etcd2
         ETCD_VERSION=2.2.1
````

But when I look at the master's kube-env, `STORAGE_BACKEND` is correct, but it doesn't mention `ETCD_VERSION`.  Same thing in the `etcd.manifest` files.  I end up running 3.0.14 in etcd2 mode.  This is at head.

**Comment by wojtek-t** [comment]
Ohh sorry. You need to also set one more env, which is:
```
ETCD_IMAGE=2.2.1
```

The ETCD_VERSION is propagated only to the etcd manifest as "TARGET_VERSION" field (which is consumed by migration script).
However, the image is controlled via the "ETCD_IMAGE" env var.

This was added to allow having images like "3.0.14-alpha.1" (which is obviously not a correct etcd version - that should be "3.0.14").
This should probably be cleaned and those two var should be merged when we say we are no longer going to build alpha images (or add a logic to migration script to get rid of the suffix from values like '3.0.14-alpha.1')

**Comment by mml** [comment]
@wojtek-t I don't need to change the `ETCD_IMAGE`.  I could, but the 3.0.14 image should work, since it contains 2.2.1.  But `ETCD_VERSION` is not getting propagated.

I bring my cluster up like this: 'STORAGE_BACKEND=etcd2 ETCD_VERSION=2.2.1 [...other environment variables...] go run hack/e2e.go -- -v --up'

But this is what I get.

```console
e2e-master ~ # egrep -C1 TARGET_STORAGE\|TARGET_VERSION /etc/kubernetes/manifests/etcd.manifest 
    "env": [
      { "name": "TARGET_STORAGE",
        "value": "etcd2"
      },
      { "name": "TARGET_VERSION",
        "value": "3.0.14"
```

Still looking into it...

**Comment by mml** [comment]
Sigh.  https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-test.sh#L116

I am now setting this other environment variable and it's working.  No idea if this was intended or not.  Either way, it consumed a few hours.  :-1:

**Comment by wojtek-t** [comment]
Should be fixed by https://github.com/kubernetes/test-infra/pull/1900
