### ISSUE TITLE
Deployment ReplicaSets not cleaned up, even with revisionHistoryLimit set

### ISSUE THREAD

**Issue by Bekt** [kubernetes/kubernetes#41432]
**Is this a BUG REPORT or FEATURE REQUEST?** Bug Report

**Kubernetes version**:
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0", GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", BuildDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS 1235.9.0
- **Kernel** (e.g. `uname -a`):
`Linux xx.ec2.internal 4.7.3-coreos-r2 #1 SMP Thu Feb 2 02:26:10 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz GenuineIntel GNU/Linux
`
- **Install tools**: hyperkube
- **Others**:
  * brand new cluster
  * reported before in #40068 (without reproducible steps)

**What happened**:
Create a Deployment with spec.revisionHistoryLimit=2
```
$ kubectl create -f http://pastebin.com/raw/nYyibKXN
$ kubectl get deployment/nginx -o json | jq ".spec.revisionHistoryLimit"
2
```

Trigger a few rollout with `kubectl set image`.

Check how many ReplicatSets there are.
```
$ kubectl get rs -l app=nginx | wc -l
7
```

**What you expected to happen**:
* Number of ReplicaSets to be 2.
* Old ReplicaSets to be cleaned up automatically.

**How to reproduce it** (as minimally and precisely as possible):
```
$ kubectl create -f http://pastebin.com/raw/nYyibKXN

# Create a few rollouts, with ~1min interval, e.g:
$ kubectl set image deployment/nginx nginx=nginx:1.8.1
$ kubectl set image deployment/nginx nginx=nginx:1.9.7
$ kubectl set image deployment/nginx nginx=nginx:1.9.8
$ kubectl set image deployment/nginx nginx=nginx:1.9.9
$ kubectl set image deployment/nginx nginx=nginx:1.9.10
```

**Comment by Bekt** [comment]
Huh, I tested with `v1.5.2+coreos.2` and it's working as expected...

I'm not sure if you guys keep issues open for older versions, feel free to close otherwise.

**Comment by kargakis** [comment]
No, this is fixed in later versions and should even unblock stuck Deployments with hundreds of ReplicaSets in 1.6.
