### ISSUE TITLE
kubelet log lines are dropped at times

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#41435]
While debugging some failures on GCI (COS), a few people have noticed that some log messages that should've been there were missing in the output of `journalctl -u`. 
One very likely cause is that journald rates limits the log messages of individual services and drops messages accordingly.

The configuration is in `/etc/systemd/journald.conf` and by default the limits are set to
```
RateLimitInterval=30s
RateLimitBurst=1000
```

If journald has dropped messages, one can check the log of the journald (`journalctl -u  systemd-journald`) and see messages such as
```
Feb 14 19:59:53 e2e-test-yjhong-minion-group-g3gr systemd-journal[27521]: Suppressed 23 messages from /system.slice/docker.service
Feb 14 19:59:55 e2e-test-yjhong-minion-group-g3gr systemd-journal[27521]: Suppressed 17 messages from /system.slice/kubelet.service
Feb 14 20:00:03 e2e-test-yjhong-minion-group-g3gr systemd-journal[27521]: Suppressed 21 messages from /system.slice/docker.service
Feb 14 20:00:05 e2e-test-yjhong-minion-group-g3gr systemd-journal[27521]: Suppressed 22 messages from /system.slice/kubelet.service
```

Missing log lines makes debugging test failures unnecessarily difficult.  We should check whether the limits are enough for kubelet (e.g., when creating/deleting 100 pods), and if not, whether to adjust the limits or reduce the log noise in general in kubelet. I believe this is less of a problem for production clusters which have lower log verbosity setting, but that needs to be confirmed.

/cc @kubernetes/sig-node-bugs @Random-Liu @dchen1107

**Comment by Random-Liu** [comment]
@yujuhong Thanks for filing the issue and found the cause. I also observed this for many times. This sometimes makes it very hard to debug when important logs are missing.

**Comment by yujuhong** [comment]
> @yujuhong Thanks for filing the issue and found the cause.

Some clarification: I only suspected that this could be the cause, but didn't have time to verify yet :-)

**Comment by smarterclayton** [comment]
We see this all the time.  It can even happen at lower log levels (as derek found out with trace).

**Comment by dchen1107** [comment]
@smarterclayton What is your journaltd configuration? Caused by rate limit?

**Comment by smarterclayton** [comment]
All RHEL and CentOS systems have rate limiting on by default.

**Comment by yujuhong** [comment]
kubelet's log messages increases with the number of pods/containers on the node, and gets worse if there are problems (when you need to debug). I think we do need to clean up the log messages in general, but bumping the limit in journald may not be a bad idea for now?

**Comment by techtonik** [comment]
Is there a diagram showing log message dynamics depending on the k8s operations?
How often it may occur?
Is it possible to dynamically up the limit if a log burst is expected?
Is it possible to warn user through the other channel and show him how many messages were squelched?
Is it possible to maintain own queue of squelched messages in memory an dispatch the, once burst peak is over?

**Comment by orangemi** [comment]
I think this issue should link to https://github.com/moby/moby/issues/31058
