### ISSUE TITLE
Log initiating user with request in kubelet for auditing purposes

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#41443]
Requests are logged into the Kubelet log, but they don't currently include any identifying information. Simply identifying the authenticated user won't be particularly useful since it will all come through the apiserver. Rather, we want to log the user that initially sent the request to the apiserver, which was then forwarded to the kubelet. I believe acting-as attributes fill these requirements in the request, but I'm not sure whether that is currently enabled for apiserver -> kubelet requests.

/cc @liggitt @kubernetes/sig-auth-feature-requests @enisoc

**Comment by liggitt** [comment]
Kubelet authorization isn't as granular as the API server authorization. normal users would not be authorized to hit the Kubelet API directly, so Acting-As  wouldn't work here. I would rather rely on the audit log in the API server to see which users performed which actions
