### ISSUE TITLE
Digital Ocean load balancers / cloud provider

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#41444]
**Environment**:
- **Cloud provider or hardware configuration**: Digital Ocean (unimplemented?)

Digital Ocean has just released their Load Balancer feature to General Availability. 

https://www.digitalocean.com/products/load-balancer/

Now that Block Storage #39326 is also available, I think Digital Ocean should now be a good candidate for a new Cloud Provider implementation.

https://github.com/kubernetes/kubernetes/tree/master/pkg/cloudprovider/providers

Currently it seems no work has begun towards this task. This is obviously a major effort, but I'd be willing to contribute. Hopefully some engineers from Digital Ocean would be willing to contribute as well, as it's their platform we would be adding support for. If nothing else, I think we should flag the appropriate teams and mark this as a "will add eventually" feature.

Also related:

 - #32334
 - #34783

I would argue for closing the old issues and consolidating the Digital Ocean cloud provider notes into one issue.

cc @wardviaene @leshik @justinsb

**Comment by ITPro360** [comment]
Subscribed +1

**Comment by ankitforcode** [comment]
+1

**Comment by cgag** [comment]
Some work on this by @wardviaene: https://github.com/kubernetes/kubernetes/pull/36894

**Comment by paralin** [comment]
Relevant, maybe a blocker:

 - https://github.com/kubernetes/community/pull/128

**Comment by aknuds1** [comment]
I'm interested in this and would be willing to help.

**Comment by baldwinSPC** [comment]
@aknuds1 we're in the middle of coding up the contrib for cloudprovider. once we have a bit more we'll share :)

**Comment by aknuds1** [comment]
@baldwinSPC Thanks for letting me know 🙂

**Comment by baldwinSPC** [comment]
We're in the middle of cleaning up the storage provider code. We'll have something in a few weeks.

**Comment by klausenbusk** [comment]
@baldwinSPC Any update on this?

**Comment by baldwinSPC** [comment]
@klausenbusk We just sent a PR upstream to support DO's block storage in K8S. That was more involved than I anticipated so we're now moving onto the final bits for the LB piece of the puzzle. We chose to support storage first vs load balancing. PR for storage is #50044

**Comment by baldwinSPC** [comment]
cc @odacremolbap so he can track this with the LB work.

**Comment by mmisztal1980** [comment]
any progress on this? This would be huge

**Comment by ITPROMatthew** [comment]
With effort to remove cloudprovider dependencies out of kubernetes core I doubt we will see this.

However there is already support for DigitalOcean Load Balancing using https://github.com/digitalocean/digitalocean-cloud-controller-manager however its still Alpha.

I am successfully using the DO CCM on k8s 1.8.x and seems to be working fairly well. been using it since 1.7.3.

**Comment by baldwinSPC** [comment]
yes, the code @ITPROMatthew references is the go forward code and where we're contributing and working. FlexVolume work can be found here: https://github.com/StackPointCloud/digitalocean-flex-volumes

**Comment by mmisztal1980** [comment]
Thanks guys

**Comment by haukurk** [comment]
+1

**Comment by roysG** [comment]
Any new updates?

**Comment by roysG** [comment]
+1

**Comment by klausenbusk** [comment]
I assume we can close this now? DigitalOcean now provide a cloud-controller https://github.com/digitalocean/digitalocean-cloud-controller-manager + there is a digitalocean block storage provisioner (including a flexplugin): https://github.com/kubernetes-incubator/external-storage/tree/master/digitalocean + [RexRay](http://rexray.readthedocs.io/) supports [DigitalOcean](http://rexray.readthedocs.io/en/stable/user-guide/storage-providers/digitalocean/) and has a [flexplugin](http://rexray.readthedocs.io/en/stable/user-guide/schedulers/kubernetes/), @StackPointCloud also has a [flexplugin](https://github.com/StackPointCloud/digitalocean-flex-volumes/).

**Comment by klausenbusk** [comment]
/close

This is probably never gonna happen. K8s is working on moving all cloud providers out-of-tree and isn't accepting new in-tree cloud providers. DigitalOcean also provide a [out of tree cloud provider](https://github.com/digitalocean/digitalocean-cloud-controller-manager), which update the node with the correct labels and provide load balancer support. For storage there is a [DigitalOcean block storage provisioner](https://github.com/kubernetes-incubator/external-storage/tree/master/digitalocean) besides a few other options [RexRay](http://rexray.readthedocs.io/en/stable/user-guide/storage-providers/digitalocean/), @StackPointCloud [flexplugin](https://github.com/StackPointCloud/digitalocean-flex-volumes/), to name a few.

**Comment by paralin** [comment]
Those things were not in place when the issue was raised.
