### ISSUE TITLE
Processes may be leaked when docker is killed repeatedly in a short time frame

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#41450]
Forked from #37580

*docker version: 1.11.2*
*OS: gci*

If docker gets killed repeated in a short time frame (while kubelet is running and trying to create containers), some container processes may get reparented to PID 1 and continue running, but no longer visible from the docker daemon.

This can be produced by running the `Network should recover from ip leaks` node e2e test.
 - test creates 100 pods with the pause image.
 - test restarts docker (`systemctl restart docker`) 6 times, with 20s interval in between.
 - test completes successfully.
 - Run `ps -C "pause" -f` and see multiple processes running the `pause` command still alive.
 - Run `docker ps` and see no running container.
Running the test a few times (< 3) should reproduce the issue.

EDIT: This issue has been there since the test was first introduced in Nov 2016. We will need to check and see if this is fixed in newer docker versions.

/cc @kubernetes/sig-node-bugs

**Comment by vishh** [comment]
Are these processes still tracked by their respective cgroups?

**Comment by yujuhong** [comment]
> Are these processes still tracked by their respective cgroups?

Didn't check when I still had the node. Should be easy to reproduce and verify though.

**Comment by feiskyer** [comment]
Does docker 1.12 have same problem?

**Comment by yujuhong** [comment]
> Does docker 1.12 have same problem?

Don't know. No one has verified yet.

**Comment by yujuhong** [comment]
Need to verify whether newer docker + COS image has the same issue
