### ISSUE TITLE
Bug in storageClass with pd-gce provider - unable to provision ssd

### ISSUE THREAD

**Issue by pierreozoux** [kubernetes/kubernetes#41468]
I'm using GCE, and I didn't manage to make this storageClass working as expected.

**Kubernetes version** (use `kubectl version`):

```
kubectl version 
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

I'd love to have this working :)

I just tried as @chrislovecnm said to s/pd-ssd/ https://www.googleapis.com/compute/v1/projects/myproject/zones/europe-west1-b/diskTypes/pd-ssd/g, but without success either.

**Environment**:
- **Cloud provider or hardware configuration**: GKE

**What happened**:

Here is my default storage class:
```
kubectl describe storageclass default       
Name:		default
IsDefaultClass:	Yes
Annotations:	kubectl.kubernetes.io/last-applied-configuration={"kind":"StorageClass","apiVersion":"storage.k8s.io/v1beta1","metadata":{"name":"default","creationTimestamp":null,"labels":{"kubernetes.io/cluster-service":"true"},"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"true"}},"provisioner":"kubernetes.io/gce-pd","parameters":{"type":"pd-ssd"}},storageclass.beta.kubernetes.io/is-default-class=true
Provisioner:	kubernetes.io/gce-pd
Parameters:	type=pd-ssd
No events.
```

And if I:
```
helm install --namespace production --set persistence.size=20Gi --set persistence.storageClass=default --name mongo stable/mongodb
```

the actual volume that get provisioned is a `standard` one and not an `ssd`.

**What you expected to happen**:

I would have expected an ssd provisioned.
And actually, it is not just for the default behavior, I can't manage to provision an ssd at all.

**How to reproduce it** (as minimally and precisely as possible):

Create a k8s cluster in GKE, add the default storage class as described, and try to install this mongo using helm.

**Anything else we need to know**:

```
kubectl get pvc --all-namespaces -o yaml && kubectl get storageclass -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.alpha.kubernetes.io/storage-class: default
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
    creationTimestamp: 2017-02-14T12:22:14Z
    name: mongo-mongodb
    namespace: production
    resourceVersion: "436161"
    selfLink: /api/v1/namespaces/production/persistentvolumeclaims/mongo-mongodb
    uid: 37f55d53-f2b0-11e6-8042-42010a8401cd
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    volumeName: pvc-37f55d53-f2b0-11e6-8042-42010a8401cd
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 20Gi
    phase: Bound
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1beta1
  kind: StorageClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"kind":"StorageClass","apiVersion":"storage.k8s.io/v1beta1","metadata":{"name":"default","creationTimestamp":null,"labels":{"kubernetes.io/cluster-service":"true"},"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"true"}},"provisioner":"kubernetes.io/gce-pd","parameters":{"type":"pd-ssd"}}'
      storageclass.beta.kubernetes.io/is-default-class: "true"
    creationTimestamp: 2017-02-15T10:07:22Z
    labels:
      kubernetes.io/cluster-service: "true"
    name: default
    namespace: ""
    resourceVersion: "538817"
    selfLink: /apis/storage.k8s.io/v1beta1/storageclassesdefault
    uid: 8b004255-f366-11e6-8042-42010a8401cd
  parameters:
    type: pd-ssd
  provisioner: kubernetes.io/gce-pd
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
```

Thanks @jsafrane for your kind help! (I also opened a ticket support with GCE, and I linked them here.

**Comment by jsafrane** [comment]
>```
>  kind: PersistentVolumeClaim
>  metadata:
>    annotations:
>      volume.alpha.kubernetes.io/storage-class: default
>```

This enables alpha provisioning, which ignores storage class. Either remove this alpha annotation (and default storage class *should* be automatically used) or use beta annotation: `volume.beta.kubernetes.io/storage-class: default`.

This is hard to spot even for me :-(

**Comment by pierreozoux** [comment]
Arf!

You are good!

And you know what, I thought I was using beta because of:
https://github.com/kubernetes/charts/blob/master/stable/mongodb/templates/pvc.yaml#L7-L11

But, my local version of the helm repo was actually using the "old" version of the mongo helm package - with alpha:
https://github.com/kubernetes/charts/blob/46191a9583b1a4b6e4341504c830b7c4fede9c26/stable/mongodb/templates/pvc.yaml#L7

So I did `helm update` and now it is working as expected!

Amazing, thanks a lot for your help :)
