### ISSUE TITLE
Cannot download kubectl.exe for windows easily!!!!

### ISSUE THREAD

**Issue by jianlianggao** [kubernetes/kubernetes#41463]
Dear guys,

I followed the minikube docs to use the command line in my windows 
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/windows/amd64/kubectl.exe

But I got the error as nosuchkey

Then I found out, I had to hack the xml file at URL http://storage.googleapis.com/kubernetes-release/
to find the release I needed. for example, <Key>release/v0.16.1/bin/windows/amd64/kubectl.exe</Key>
Then I used the combination of the URL and the key
http://storage.googleapis.com/kubernetes-release/release/v0.16.1/bin/windows/amd64/kubectl.exe
to download the .exe file.

Why don't you provide a direct link for Windows users to download kubectl.exe?

Many thanks,
Jianliang

**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by tonglil** [comment]
The download links for (.exe) binaries for each release are in the CHANGELOG, for example for 1.4.9: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#client-binaries

**Comment by kargakis** [comment]
@kubernetes/sig-release-misc

**Comment by sayeduzzamancuet** [comment]
I am still facing this issue, unable to download the exe file from the provided url.

**Comment by dims** [comment]
try https://gcsweb.k8s.io/gcs/kubernetes-release/release/v1.18.0/bin/windows/amd64/
