### ISSUE TITLE
kubelet pod bandwidth shaping not work any more?

### ISSUE THREAD

**Issue by ChenLingPeng** [kubernetes/kubernetes#41471]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
help

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
shaping, bandwidth

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
master

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

Working on network shaping. I found that thers're some discussion on bandwidth control on kubelet and found the implemention in #12513 . But if I'm not missing something, another PR #34906 remove the `reconcileCBR0` function and the kl.shaper now is nil since not initialized. So in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1535 the test is always false and won't shape pod bandwidth.

So the question is right now kubelet will not shaping the pod bandwidth?
Fix me if I'am wrong. thank you.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by caseydavenport** [comment]
@ChenLingPeng the bandwidth shaping feature that you linked to lives on today in the kubenet plugin only.

See here: https://github.com/kubernetes/kubernetes/blob/v1.7.0-alpha.3/pkg/kubelet/network/kubenet/kubenet_linux.go#L371
