### ISSUE TITLE
doc bug: swagger viewer is broken

### ISSUE THREAD

**Issue by skelterjohn** [kubernetes/kubernetes#41483]
https://kubernetes.io/docs/api/ has a link to https://kubernetes.io/kubernetes/third_party/swagger-ui/, and the latter is broken with the message "Can't read from server. It may not have the appropriate access-control-origin settings."

**Comment by ahmetb** [comment]
This UI will be removed soon https://github.com/kubernetes/kubernetes.github.io/issues/2220
