### ISSUE TITLE
[doc] Supported persistent volume provisioner clarification

### ISSUE THREAD

**Issue by bradbeam** [kubernetes/kubernetes#41485]
In the persistent volumes documentation ( https://kubernetes.io/docs/user-guide/persistent-volumes/#provisioner  ), it explicitly calls out aws-ebs and gce-pd as the only supported provisioners:
> During beta, the available provisioner types are kubernetes.io/aws-ebs and kubernetes.io/gce-pd

However, there are examples for openstack/cinder that reference v1beta:
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/storage-class/openstack/default.yaml

Is the documentation still correct or does it need to be updated?

**Comment by xsgordon** [comment]
@idvoretskyi can I get sig/openstack and sig/storage labels here?

**Comment by idvoretskyi** [comment]
@bradbeam it is likely to submit documentation issues to the https://github.com/kubernetes/kubernetes.github.io repo.

**Comment by bradbeam** [comment]
Should I close this one and open a new issue there?

**Comment by idvoretskyi** [comment]
@bradbeam please.

**Comment by msau42** [comment]
docs have been updated
/assign
