### ISSUE TITLE
Extend tests for kubemark presubmit

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#41481]
Today we have two cases, where merging PRs (which passed kubemark presubmit) broke kubemark-500 and kubemark-100. The PRs were:
https://github.com/kubernetes/kubernetes/pull/41378
https://github.com/kubernetes/kubernetes/pull/41285

In both cases we weren't able to start pods - one broke scheduler, the other broke hollow-kubelet.

This should have been caught by our presubmit kubemark tests. But the problem is that the presubmit one is only starting a kubemark cluster and waiting for hollow-nodes to be ready (and not even starting a single pod).

We should extend the test that is running in kubemark presubmit to start a simple 1-pod deployment and wait until it is running.

@yujuhong @liggitt @kubernetes/sig-scalability-bugs

**Comment by timothysc** [comment]
It would be nice to get the latest state on perf during the next sig-scale mtg.

**Comment by gmarek** [comment]
Fixed by #41490
