### ISSUE TITLE
kubemark add-on manager unable to apply rbac bindings

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#41493]
seeing errors in kubemark add-on manager logs applying RBAC permissions:

```
INFO: == Executing apply to spin up new addon resources at 2017-02-15T16:01:15+0000 ==
unable to decode "/etc/kubernetes/addons/kubemark-rbac-bindings/heapster-binding.yaml": no kind "ClusterRoleBinding" is registered for version "rbac.authorization.k8s.io/v1beta1"
unable to decode "/etc/kubernetes/addons/kubemark-rbac-bindings/kubecfg-binding.yaml": no kind "ClusterRoleBinding" is registered for version "rbac.authorization.k8s.io/v1beta1"
unable to decode "/etc/kubernetes/addons/kubemark-rbac-bindings/npd-binding.yaml": no kind "ClusterRoleBinding" is registered for version "rbac.authorization.k8s.io/v1beta1"
WRN: == Failed to execute /usr/local/bin/kubectl  apply --namespace=kube-system -f /etc/kubernetes/addons     --prune=false -l kubernetes.io/cluster-service=true --recursive  at 2017-02-15T16:01:15+0000. 2 tries 
```

do we know what version of kubectl the add-on manager is using?

cc @wojtek-t @shyamjvs

**Comment by liggitt** [comment]
from https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2599/artifacts/kubemark-500-kubemark-master/kube-addon-manager.log

**Comment by liggitt** [comment]
looks like kubemark is using:
image: {{kube_docker_registry}}/kube-addon-manager:v6.1

normal CI is using:
image: gcr.io/google-containers/kube-addon-manager:v6.4-alpha.1

**Comment by wojtek-t** [comment]
@liggitt - thanks for reporting.

@shyamjvs - can you please take care of unifying kubemark with real clusters?

**Comment by shyamjvs** [comment]
These errors start coming from run 2595 (https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2595/artifacts/kubemark-500-kubemark-master/kube-addon-manager.log) and right before that your commit updating rbac apiversion to v1beta1 was merged (https://github.com/kubernetes/kubernetes/commit/0a56830520e29b6a76d3d6fb1d041d8fbecc68fe). Upping the version to 6.4 should fix this. I'll send out the PR for this.
