### ISSUE TITLE
kubemark should replace the fake docker client with a fake CRI client

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#41504]
Kubelet has switched to using the CRI implementation by default, so CRI is the right abstraction for kubemark to use. This will also ensure all unnecessary functions in dockershim (e.g., creating checkpoint files) are properly mocked out.

The CRI fakes are currently in https://github.com/kubernetes/kubernetes/tree/v1.6.0-alpha.2/pkg/kubelet/api/testing
It'll need some work to match what `FakeDockerClient` does today, as well as some plumbing to use this in the hollow node.

/cc @wojtek-t @gmarek @Random-Liu

**Comment by wojtek-t** [comment]
@shyamjvs

**Comment by shyamjvs** [comment]
There is issue https://github.com/kubernetes/kubernetes/issues/41488 where discussion about making hollow node use CRI is happening already. Can we close this issue @yujuhong (unless you intended for something else)?

**Comment by yujuhong** [comment]
#41488 is about getting the FakeDockerClient in kubemark to work properly when CRI is enabled. That's only a short-term solution. kubemark should not be using FakeDockerClient in the future, which is what this issues is about.

**Comment by shyamjvs** [comment]
Ah, I get it now! Thanks for telling this :)

**Comment by shyamjvs** [comment]
@wojtek-t Could you assign a priority to this issue?

**Comment by yujuhong** [comment]
Thanks to @Random-Liu for fixing up the FakeDockerClient in #41524, but the current code is still quite fragile. Copying my own comment from https://github.com/kubernetes/kubernetes/pull/41524#issuecomment-280790000 below:
"we can't mock out the OS interface in dockershim anymore (given that it should not be part of kubelet). This means that hollow nodes will still create directories, checkpoints, and symlinks. The fake docker client has also become more and more complex since it needs to fake more information (log path, labels, etc). More reasons to switch to using a fake CRI client :)"

**Comment by shyamjvs** [comment]
@yujuhong I have a (probably silly) question here. At what level do we want kubemark to mock the container runtime. IIUC we have the following two options:
- Mock stuff at the kubelet's interface and hence we don't have any real RPC requests and the responses are dummy. This would pretty much need no real changes to the current code as the interface has stayed the same anyway (i.e. for both docker and CRI). However, this would be less closely represent real container runtime operations. But then we had the same even before (for docker), so why worry about it?
- Mock stuff inside the CRI shim to respond to all RPC requests from kubelet (without actually doing anything with containers/images though). This would still not represent real operations, however it's better than the previous option as it also accounts for network latency of kubelet <-> CRI shim interactions. Is this change really required from scalability PoV?

**Comment by yujuhong** [comment]
> Mock stuff inside the CRI shim to respond to all RPC requests from kubelet (without actually doing anything with containers/images though). This would still not represent real operations, however it's better than the previous option as it also accounts for network latency of kubelet <-> CRI shim interactions. Is this change really required from scalability PoV?

Ideally, the CRI shim should be run as a separate process, and from kubelet's point of view, it's interacting with the shim. I think mocking at the CRI abstraction level is the right thing to do. Some more points below.
 1. You don't want the kubemark code to change if/when the underlying container runtime changes. Moreover, you don't want to write/use a mock for a shim that's potentially from another repository or running as a separate process.
 2. kubemark now injects artificial latencies in select docker operations, and you can do the same to the CRI mock.
 3. We have separate tests for node performance and scalability (i.e., pod density). I don't think mocking at docker vs. CRI level would *not* have visible impact for cluster scalability.

**Comment by wojtek-t** [comment]
Agree with @yujuhong

**Comment by shyamjvs** [comment]
Sgtm. I'll look into moving kubemark to CRI then.

**Comment by feiskyer** [comment]
Related: #49762 is adding a fake remote runtime service.

**Comment by yujuhong** [comment]
@shyamjvs @wojtek-t is it possible to re-prioritize this, now that we have more container runtime in production?

**Comment by shyamjvs** [comment]
@yujuhong We may be able to give this some free cycles. It'd be useful to have an estimate on how much work this is. Also do you think it'd be easier/faster if someone from sig-node is involved in this?

**Comment by yujuhong** [comment]
I don't think it'd be too much work. The main thing is to port the functionalities that are already in the fake docker client to the fake cri client.

**Comment by wojtek-t** [comment]
I'm reopening it, because the PR fixing is going to be reverted: https://github.com/kubernetes/kubernetes/pull/86425
