### ISSUE TITLE
[kubelet] Delete mirror pods once static pods get evicted

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#41507]
As of mirror pods serve as a "mirror" of the state of static pods on a node. If a static pod gets evicted, the mirror pod will reflect this state change, but is never deleted.
When kubelet restarts it restarts previously evicted static pods and so the old mirror pod is no longer valid.

We need to either delete mirror pods once their respective static pods have been completely removed from the node, or
have kubelet avoid restarting static pods based on the presence of corresponding mirror pods.

The latter would require kubelet to wait for access to API server which will affect bootstrapping scenarios (bootstrapping a master node using static pods)

The former might be a better alternative for now until Kubelet can avoid having multiple simultaneous sources of pods.

cc @dashpole @kubernetes/sig-node-bugs

**Comment by yujuhong** [comment]
@Random-Liu had a WIP PR long ago to move all mirror pod logic to a separate component to handle cases like this. He never had time to finish that PR though...

**Comment by vishh** [comment]
@dchen1107 for finding an owner for this issue

**Comment by yogeshnath** [comment]
I'm still running into the same issue. mirror pods should be deleted once static pods are removed from the node. This is key if you reconfigure etcd or api-server.

**Comment by yujuhong** [comment]
Relevant issues: #17251 #16627
