### ISSUE TITLE
Add StatefulSet to set of controllers that SelectorSpreadPriority spreads

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#41513]
The SelectorSpreadPriority priority functions unfortunately has a hard-coded list of controller types whose pods it tries to spread across nodes. We never updated this list to include StatefulSet.

https://github.com/kubernetes/kubernetes/blob/3dbbd0bdf44cb07fdde85aa392adf99ea7e95939/plugin/pkg/scheduler/algorithm/priorities/selector_spreading.go#L60
needs a "getPodStatefulSets()" function

Longer-term we really need a way to register scheduling-oriented controllers in a single place so we don't have to remember all the different places to update when we add a new controller.

(Theoretically we should also have Job in there...)

@kubernetes/sig-scheduling-feature-requests

**Comment by smarterclayton** [comment]
I thought there was an issue about reading the controller ref, walking to
it generically, and trying to get a selector out of it.  But can't find it
now.

On Wed, Feb 15, 2017 at 3:31 PM, David Oppenheimer <notifications@github.com

**Comment by davidopp** [comment]
Yeah, that's probably a good way to do it long-term. Anyway, I was trying to find something simple as a first project for @bsalamat, and this seemed like a good one, so I think we should do this short-term fix first, and then think about longer-term.

**Comment by smarterclayton** [comment]
I'm ok with it.  Just that we keep having to add new controllers to old
hacks.

On Wed, Feb 15, 2017 at 5:46 PM, David Oppenheimer <notifications@github.com
