### ISSUE TITLE
Docker reports incorrect exit code for containers if the docker service was restarted

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#41516]
To reproduce this, start several containers and restart docker with `sudo systemctl restart docker` or `sudo service docker restart`, depending on the OS distro.
After docker restarts properly, run `docker ps -a`  and see containers were terminated with exit code 0.

```console
$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                      PORTS               NAMES
5039dd309f12        busybox             "/bin/sh -c 'sleep 10"   About a minute ago   Exited (0) 22 seconds ago                       compassionate_mcclintock
83322e7eedcb        busybox             "/bin/sh -c 'sleep 10"   About a minute ago   Exited (0) 22 seconds ago                       distracted_kirch
fd96e1c425df        busybox             "/bin/sh -c 'sleep 10"   About a minute ago   Exited (0) 22 seconds ago                       elegant_goldstine
a255470685c0        busybox             "/bin/sh -c 'sleep 10"   About a minute ago   Exited (0) 22 seconds ago                       serene_bhaskara
c726fe02b915        busybox             "/bin/sh -c 'sleep 10"   About a minute ago   Exited (0) 22 seconds ago                       hungry_boyd
fabf1984c604        busybox             "/bin/sh -c 'sleep 10"   About a minute ago   Exited (0) 22 seconds ago                       romantic_poitras
```

I tested this on three docker versions: 1.10.3, 1.11.2, and 1.12.6. Only docker 1.10.3 correctly reported the 137 exit code.
This issue was claimed to be fixed in https://github.com/docker/docker/issues/26143

**Comment by yujuhong** [comment]
Reported the issue to docker: https://github.com/docker/docker/issues/31262

**Comment by resouer** [comment]
I tested on docker 1.12.1 and saw the same problem, but this seems already fixed in docker 1.13.1:

```
docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                       PORTS               NAMES
4c262cd2e3e4        busybox             "sleep 60000"       30 seconds ago      Exited (137) 6 seconds ago                       modest_bardeen
1b0654cdc36b        busybox             "sleep 60000"       32 seconds ago      Exited (137) 6 seconds ago                       gracious_brattain
```

**Comment by yujuhong** [comment]
@mrunalp, this is the issue I talked to you last time. Have you seen the same issue in openshift?

/cc @derekwaynecarr

**Comment by mrunalp** [comment]
@yujuhong I don't see this issue on Fedora 25 with our docker 1.12.6

**Comment by yujuhong** [comment]
> @yujuhong I don't see this issue on Fedora 25 with our docker 1.12.6

Hmm..Where can I find the list of patches for your docker?

**Comment by mrunalp** [comment]
https://github.com/projectatomic/docker/tree/docker-1.12.6

**Comment by mrunalp** [comment]
We also have similar trees for containerd and runc under projectatomic.

**Comment by Random-Liu** [comment]
FYI, I could still reproduce this in docker `17.03.1-ce`.

https://github.com/docker/docker/issues/31262#issuecomment-291702411

**Comment by Random-Liu** [comment]
Updated that docker/docker#31262 (comment) is a red herring. The issue is actually fixed.

**Comment by warmchang** [comment]
👍
