### ISSUE TITLE
Deployment upgrade test failing

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#41518]
The deployment upgrade tests are failing the upgrade CI tests. Here is a sample:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-latest-upgrade-master/5/

It might not be a deployment issues, but an upgrade issue.

**Comment by kargakis** [comment]
Is this failing consistenly?

**Comment by krousey** [comment]
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-latest-upgrade-master/

Yes. And across 3 other suites as well.

**Comment by krousey** [comment]
Any insight on this now that the debugging logging was added?

**Comment by kargakis** [comment]
There are a couple of values in the PodTemplate that change and the new replica set is considered old after the upgrade but I am still not sure why this should happen:
https://www.diffchecker.com/lHGiHsbi

Will need further investigation - need to print the deployment before and after the upgrade too and maybe add some extra output from the deployment controller.

**Comment by kargakis** [comment]
This also seems like a test problem. Submitting a new PR shortly.

**Comment by kargakis** [comment]
So it seems #41844 fixed this. All the rest of the failures that occur every now and then seem related to the framework.
https://k8s-testgrid.appspot.com/latest-upgrades#gke-master&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Upgrade%5C%20%5C%5BFeature%5C%3AUpgrade%5C%5D%5C%20%5C%5Bk8s%5C.io%5C%5D%5C%20master%5C%20upgrade%5C%20should%5C%20maintain%5C%20a%5C%20functioning%5C%20cluster%5C%20%5C%5BFeature%5C%3AMasterUpgrade%5C%5D
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:61
Error creating Pod
Expected error:
    <*errors.StatusError | 0xc420a90200>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "pods \"pod-configmap-58fde14f-f93c-11e6-86bf-0242ac110002\" is forbidden: not yet ready to handle request",
            Reason: "Forbidden",
            Details: {
                Name: "pod-configmap-58fde14f-f93c-11e6-86bf-0242ac110002",
                Group: "",
                Kind: "pods",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 403,
        },
    }
    pods "pod-configmap-58fde14f-f93c-11e6-86bf-0242ac110002" is forbidden: not yet ready to handle request
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/pods.go:71
```
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:61
Feb 22 13:25:20.079: Could not reach HTTP service through 130.211.215.77:80 after 2s: timed out waiting for the condition
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/service_util.go:669
```

**Comment by kargakis** [comment]
I want to extend the test a bit to make sure the controller-manager processed the Deployment after the cluster upgrade. Unrelated to this issue but letting you @krousey know that another PR is coming along your way:)
