### ISSUE TITLE
After Reboot Kubernetes Service is not uo 

### ISSUE THREAD

**Issue by kashifali94** [kubernetes/kubernetes#41523]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
its a help

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

no i didn't find anything related to this 

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
my service is not running 
**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
i have just restarted the machine and my kubectl service is not up when i run kubectl get node/pod it gives me this 
"The connection to the server localhost:8080 was refused - did you specify the right host or port?
"
**What you expected to happen**:
it should give me the list of pods and nodes

**How to reproduce it** (as minimally and precisely as possible):

just restart the machine
**Anything else we need to know**:

**Comment by kargakis** [comment]
@kubernetes/sig-cluster-lifecycle-misc

**Comment by mikedanese** [comment]
How did you deploy your cluster?

**Comment by mikedanese** [comment]
Closing since no response.
