### ISSUE TITLE
Kubernetes service's endpoints are set to 6443 instead 8080

### ISSUE THREAD

**Issue by aanm** [kubernetes/kubernetes#41529]
It appears that kubernetes service's endpoints are being set with port 6443 even if that was not the port set in the api-server options
```
/usr/bin/kube-apiserver \
  --admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ResourceQuota \
  --advertise-address=192.168.33.11 \
  --allow-privileged=true \
  --apiserver-count=3 \
  --authorization-mode=ABAC \
  --authorization-policy-file=/var/lib/kubernetes/authorization-policy.jsonl \
  --bind-address=0.0.0.0 \
  --enable-swagger-ui=true \
  --insecure-bind-address=0.0.0.0 \
  --etcd-servers=http://192.168.33.11:2379 \
  --service-cluster-ip-range=172.20.0.0/24 \
  --service-node-port-range=30000-32767 \
  --token-auth-file=/var/lib/kubernetes/token.csv \
  --v=2
```
I would expect the kubernets' endpoints would show up with port 8080.
```
{
      "metadata": {
        "name": "kubernetes",
        "namespace": "default",
        "selfLink": "/api/v1/namespaces/default/endpoints/kubernetes",
        "uid": "e15aaaae-f3ed-11e6-8097-080027ef4427",
        "resourceVersion": "3528",
        "creationTimestamp": "2017-02-16T02:16:09Z"
      },
      "subsets": [
        {
          "addresses": [
            {
              "ip": "192.168.33.11"
            }
          ],
          "ports": [
            {
              "name": "https",
              "port": 6443,
              "protocol": "TCP"
            }
          ]
        }
      ]
    },
```

I believe that port comes from [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/master/controller.go#L181) without checking if there is a non-secure port binded.

I'm currently setting this up for a development environment and I'm sure there are plenty reasons to leave it with 6443 so I'm happy with any workaround (ideally an automatic workaround and not manually such as changing the endpoints port)

**Comment by liggitt** [comment]
the default secure port is 6443, and your invocation did not override the default

**Comment by aanm** [comment]
Ok, so it is possible to set the kubernetes service endpoint with the insecure port instead?

**Comment by liggitt** [comment]
If you completely disable the secure port (by setting it to 0), it *may* bind the insecure port to the service (I'm not sure), but I wouldn't recommend operating that way. That doesn't resemble any normal deployment, and it's likely there are things that assume the kubernetes service is TLS
