### ISSUE TITLE
Add `Node` to `kubectl get pods` output.

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#41539]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
```
[root@rhel1 ~]# kubectl get pods
NAME                                       READY     STATUS              RESTARTS   AGE
boiling-panther-mariadb-2320176767-7qvh7   0/1       Pending             0          1d
db1-mariadb-3524196392-jb59x               0/1       Pending             0          1d
dnt-demo-vpn-openvpn-639831085-0ghnp       1/1       Running             156        23h
fdsa-3434843510-d0kg1                      0/1       ImagePullBackOff    0          5h
kube-ops-view-2251972581-8nsnx             1/1       Running             1          1d
kube-ops-view-redis-3314560717-6h9jx       1/1       Running             1          1d
my-deployment-2805775348-52rv9             1/1       Running             4          1d
nginx-deployment-1447934386-cn7vq          1/1       Running             4          1d
nginx-deployment-1447934386-gtccb          1/1       Running             5          32d
nginx-deployment-1447934386-ph64c          1/1       Running             1          1d
nginx-test-2773906747-xdz6k                1/1       Running             5          34d
```
People often need to logon to the pod node to login to the containers of that pod. But now I need to first get the Pod Id and then `kubectl describe pods xxx` to get the `Node`, it is not convenient for end users, and better add `Node` field to the output of `kubectl get pods`.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by vic3lord** [comment]
I think what you need is `kubectl get pods -o wide`

**Comment by gyliu513** [comment]
this would help, thanks @vic3lord
