### ISSUE TITLE
Fluentd image is huge

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#41542]
for example 360MB in version 1.28.2

cc @Crassirostris @igorpeshansky @qingling128

**Comment by Crassirostris** [comment]
The most of the space is consumed by the fluentd package

```
root@0644d5abd591:/# sudo du -sch /* 2>/dev/null | sort -h
0	/dev
0	/proc
0	/sys
4.0K	/boot
4.0K	/home
4.0K	/lib64
4.0K	/media
4.0K	/mnt
4.0K	/srv
4.0K	/tmp
28K	/run
120K	/root
1.3M	/sbin
1.8M	/etc
3.9M	/bin
8.3M	/var
14M	/lib
88M	/usr
279M	/opt
396M	total
```

**Comment by xrl** [comment]
It includes the ruby runtime and requisite gems. It's the cost of running a Ruby process in there.

**Comment by crassirostris** [comment]
@xrl Meanwhile it was reduced to 170MB, as of version 2.0.2, that was the goal of this issue :)

I don't think it can be reduced any more, because it's purely ruby + gems, closing the issue
