### ISSUE TITLE
Deploy a default storage class on GKE

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#41559]
In 1.6 I'd like to remove alpha dynamic provisioning and it's important to have a default storage class that would cause all PVCs with alpha annotation to be provisioned.  See 1.6 feture: https://github.com/kubernetes/features/issues/180

With GKE cluster created by `KUBERNETES_PROVIDER=gke go run hack/e2e.go -v  --up` I cannot see any default storage class:

```shell
$ kubectl get storageclass
No resources found.
```

During installation, just inject https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/storage-class/gce/default.yaml into the API server and that could be it... I don't see any code in Kubernetes that installs GKE master that I could fix.

@saad-ali @msau42, please route to appropriate team.

**Comment by thockin** [comment]
@MrHohn @saad-ali I thought we had all this in by now?

**Comment by MrHohn** [comment]
Addon-manager is ready for creating default storage class. #40108 is out for easily disabling default storage class but it is still under review.

And we might need some GKE internal works for deploying default storage class on GKE as part of the addons.

**Comment by msau42** [comment]
I'll take a look at enabling it for GKE.

**Comment by msau42** [comment]
@jsafrane is this needed for 1.6 GA?  I am in the process of setting up a dev GKE environment for myself, but it is very slow and may take beyond code freeze.  If it's urgent, I can try to find a teammate's cluster to use.

**Comment by thockin** [comment]
We really need this for 1.6, I think

**Comment by jsafrane** [comment]
It's necessary to remove v1alpha1 dynamic provisioning, which is scheduled to 1.6. It *can* slip, I don't thinks anyone really depends on removing it. But sooner is better as it reduces number of supported configurations.

I was able to track `cluster/kube-up.sh` up to `gcloud container clusters create`, which deploys master somewhere in GCE and this step should IMO deploy a default storage class in it. I would start looking at how `--disable-addons=` works - default storage class is just an addon. Also, adding `--disable-addons=DefaultStorageClass` could be nice. I can help if you open-source it :-)

**Comment by msau42** [comment]
I just made the GKE changes, but the next rollout won't be until early next week, so we will miss the 1.6 freeze.

**Comment by thockin** [comment]
The freeze is a freeze on new PRs, really.  If the PR is in-flight and
substantially complete, we generally allow that to happen :)

**Comment by jsafrane** [comment]
I am hesitant to these last-minute changes, I got bitten hard couple of times. Removing alpha can break things, are you sure you can test and fix Kubernetes and/or GKE during test phase? It's not that long. I'd wait for 1.7 here.

**Comment by thockin** [comment]
I think we want SC default in GKE

**Comment by jsafrane** [comment]
> I think we want SC default in GKE

yes, sure, that's good thing to have in 1.6, I meant removal of alpha provisioning in 1.6 which depends on default SC on GKE and I would not rush *that*.

**Comment by thockin** [comment]
Ahh, I am fine but f long grace periods I need API removal, and overlap
here would be good.  I want to see it deleted almost as much as you do :)

**Comment by msau42** [comment]
The GKE change is done and has been pushed to the CI test image repo, so CI tests can use it.  But you won't be able to officially deploy a GKE cluster and use it until the production version moves to 1.6.

**Comment by jsafrane** [comment]
Thanks! I'll remove alpha provisioning in 1.7 then. Can we close this bug?

**Comment by msau42** [comment]
Yes, it can be closed
