### ISSUE TITLE
upgrade cni in vendor to support pass interface info back to runtime

### ISSUE THREAD

**Issue by heartlock** [kubernetes/kubernetes#41552]
It is necessary for vm-based runtime to use cni, like hyper, e.g. May be we can refactor code of [cniNetworkPlugin](https://github.com/kubernetes/kubernetes/tree/master/pkg/kubelet/network/cni) and reuse in all kinds of runtime.

Ref:https://github.com/containernetworking/cni/pull/145 is merged, this refactoring may become possible.

cc @dcbw @caseydavenport

**Comment by resouer** [comment]
Thanks for caring about vm based runtime. 👍 

But you are expected to provide more details about what you plan to change. Then we can figure out if it's possible :)

**Comment by feiskyer** [comment]
Although https://github.com/containernetworking/cni/pull/145 has been merged, we still needs to wait another cni stable release.

@dcbw @thockin Do you have plans of pushing this into kubernetes?

cc  @kubernetes/sig-network-misc

**Comment by freehan** [comment]
I am planning to bump libcni and cni plugins.

**Comment by squeed** [comment]
I have a working branch to do this, but we need CNI v0.5.0 to be released first.

**Comment by feiskyer** [comment]
@squeed There is already a PR for this #41745.

**Comment by feiskyer** [comment]
This PR is not required now. CNI has already been updated to latest version at #42202 and network plugins has been moved to runtimes.
