### ISSUE TITLE
hack/local-up-cluster.sh: line 463: USER: unbound variable

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#41560]
Encountered this error while running `hack/local-up-cluster.sh` on master:

> hack/local-up-cluster.sh: line 463: USER: unbound variable

Should we set `USER` to `root` by default?

cc @sttts @liggitt

**Comment by sttts** [comment]
Why is it empty? Would `$(whoami)` be better?

**Comment by alejandroEsc** [comment]
@sttts @feiskyer seems to expect $(whoami) based on the value of that variable for my machine. I can make that change  if you would like.

**Comment by tonglil** [comment]
Can you keep `$USER` as an option if it is specified?

`whoami` returns a 6 digit numeric value on my machine (corporate provisioned) and that is incompatible with GCI images, as well as error-ing out during e2e provisioning.

**Comment by alejandroEsc** [comment]
@tonglil that is a great idea, so should be defaulting to whoami in the case where it has not been defined.

**Comment by feiskyer** [comment]
> @tonglil that is a great idea, so should be defaulting to whoami in the case where it has not been defined.

OK, will file an PR to fix this.

**Comment by feiskyer** [comment]
Filed PR at #41614. PTAL
