### ISSUE TITLE
How to access Headless service externally

### ISSUE THREAD

**Issue by raghakk** [kubernetes/kubernetes#41565]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

Request for help. NO help was available in troubleshooting.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

access headless service outside the K8 system
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
1.3.8 and 1.4.8

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): ubuntu 14.04
- **Kernel** (e.g. `uname -a`): Linux ubuntu216 4.2.0-27-generic #32~14.04.1-Ubuntu SMP 
- **Install tools**:
- **Others**:

**What happened**:
After creating Zookeeper headset service, how to access it? as nodeport,cluster IP is not created.

**What you expected to happen**:
Need a way to access Zookeeper nodes from external services running outside K8s (kubernetes)

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by xiangpengzhao** [comment]
@kubernetes/sig-network-misc
/kind support

**Comment by caseydavenport** [comment]
> For such Services, a cluster IP is not allocated, kube-proxy does not handle these services, and there is no load balancing or proxying done by the platform for them. How DNS is automatically configured depends on whether the service has selectors defined.

@raghakk IIUC, headless Services will generate entries in kube-dns records based on how you've configured the Service as discussed [in this doc](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services), but I don't think that NodePorts will be allocated for a headless Service.

However, you could still create another Service with `type: NodePort` that selects the Zookeeper pod(s) and exposes them on a NodePort/LB.  Alternatively, you might be able to use [an ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) to route traffic to the correct Service.

**Comment by raghakk** [comment]
Thanks.
I did the same way...added another service.

regards
ragha
