### ISSUE TITLE
[FEATURE REQUEST] Show time of next scheduled job for cronjob

### ISSUE THREAD

**Issue by Dm3Ch** [kubernetes/kubernetes#41568]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

It would be cool if after creating of cronjob it would be possible to see when job for the cronjob will be created.

**Comment by calebamiles** [comment]
Could someone from @kubernetes/sig-apps-feature-requests please help with this feature request? Thanks!

**Comment by cmluciano** [comment]
Do you want something like  NEXT-SCHEDULE in the response from `$ kubectl get cronjob hello`

**Comment by Dm3Ch** [comment]
Yes, something like this will be perfect.

**Comment by smarterclayton** [comment]
SGTM too

**Comment by jamesSampica** [comment]
Viewing the next schedule would help when verifying the cron expression.

**Comment by rHermes** [comment]
Agreed

**Comment by soltysh** [comment]
This was moved over to https://github.com/kubernetes/kubernetes/issues/78564 please comment there.
