### ISSUE TITLE
Idle kubelet keeps writing error logs

### ISSUE THREAD

**Issue by peter-braun** [kubernetes/kubernetes#4159]
I started a new deployment of kubernetes cluster, and I noticed that an idle kubelet, to which no pod has been bound yet, writes the following error log in every second:

    Feb 05 10:27:56 node01 kubelet[3359]: E0205 10:27:56.753081    3359 etcd.go:64] etcd failed to retrieve the value for the key "/registry/nodes/node01/boundpods". Error: 100: Key not found (/registry/nodes/node01) [22]
    Feb 05 10:27:57 node01 kubelet[3359]: E0205 10:27:57.753844    3359 etcd.go:64] etcd failed to retrieve the value for the key "/registry/nodes/node01/boundpods". Error: 100: Key not found (/registry/nodes/node01) [22]
    Feb 05 10:27:58 node01 kubelet[3359]: E0205 10:27:58.754592    3359 etcd.go:64] etcd failed to retrieve the value for the key "/registry/nodes/node01/boundpods". Error: 100: Key not found (/registry/nodes/node01) [22]
    Feb 05 10:27:59 node01 kubelet[3359]: E0205 10:27:59.755346    3359 etcd.go:64] etcd failed to retrieve the value for the key "/registry/nodes/node01/boundpods". Error: 100: Key not found (/registry/nodes/node01) [22]
    Feb 05 10:28:00 node01 kubelet[3359]: E0205 10:28:00.836717    3359 etcd.go:64] etcd failed to retrieve the value for the key "/registry/nodes/node01/boundpods". Error: 100: Key not found (/registry/nodes/node01) [22]
    Feb 05 10:28:01 node01 kubelet[3359]: E0205 10:28:01.837324    3359 etcd.go:64] etcd failed to retrieve the value for the key "/registry/nodes/node01/boundpods". Error: 100: Key not found (/registry/nodes/node01) [22]

After pod is scheduled to the kubelet, it stops writing this error. Then when every pods are unassigned from the kubelet, and it becomes idle again, the above logs do not appear again.

The reason is most probably that the general node information is stored under `/registry/minions/{node name}` in etcd right after setting up the cluster (starting kube-controller-manager with `--machine` option), while information about bound pods is stored under `/registry/nodes/{node name}/boundpods` key when the first pod is scheduled on the given node.

    [root@node00 ~]# curl -L -s http://node00:4001/v2/keys/registry/nodes/node01 | python -mjson.tool
    {
        "action": "get",
        "node": {
            "createdIndex": 26,
            "dir": true,
            "key": "/registry/nodes/node01",
            "modifiedIndex": 26,
            "nodes": [
                {
                    "createdIndex": 26,
                    "key": "/registry/nodes/node01/boundpods",
                    "modifiedIndex": 32,
                    "value": "{\"kind\":\"BoundPods\",\"creationTimestamp\":null,\"resourceVersion\":26,\"apiVersion\":\"v1beta1\",\"host\":\"\",\"items\":[]}"
                }
            ]
        }
    }
    [root@node00 ~]# curl -L -s http://node00:4001/v2/keys/registry/minions/node01 | python -mjson.tool
    {
        "action": "get",
        "node": {
            "createdIndex": 8,
            "key": "/registry/minions/node01",
            "modifiedIndex": 22,
            "value": "{\"kind\":\"Minion\",\"id\":\"node01\",\"uid\":\"6f41fe85-ad09-11e4-b740-5254009cf56f\",\"creationTimestamp\":\"2015-02-05T08:34:36+01:00\",\"resourceVersion\":21,\"apiVersion\":\"v1beta1\",\"hostIP\":\"192.168.1.101\",\"resources\":{\"capacity\":{\"cpu\":\"1\",\"memory\":3221225472}},\"status\":{\"conditions\":[{\"kind\":\"Ready\",\"status\":\"Full\",\"lastTransitionTime\":null}]}}"
        }
    }

I'm using `Kubernetes v0.10.0-dirty`.

The question is why some portion of the node information is stored in `/registry/minions` and other in `/registry/nodes`? Shouldn’t be everything in under a common place?

Somehow relates to issue #3871.

Peter

**Comment by bgrant0607** [comment]
Obsolete.
