### ISSUE TITLE
Featuregate alpha-beta apis.  

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#41592]
Per https://github.com/kubernetes/kubernetes/pull/41215 I'm updating our affinity PR to leverage flag-gates for affinity upon re-generation we get: 

```
client-go has a forbidden dependency:

k8s.io/client-go/pkg/api/v1 imports k8s.io/apiserver/pkg/util/feature
k8s.io/client-go/pkg/features imports k8s.io/apiserver/pkg/features
k8s.io/client-go/pkg/features imports k8s.io/apiserver/pkg/util/feature
```

But we are absolutely going to want this type of capability... My only question is where to put this feature-gates.  Asked on slack... no answer. 

/cc @davidopp @kubernetes/sig-api-machinery-misc

**Comment by timothysc** [comment]
deads2k [3:02 PM] 
@timothysc our cycle protection works. That's good

[3:03]  
@timothysc this is a feature gate for teh kube-apiserver in particular, right?

timothysc [3:03 PM] 
this is to feature gate an api-utility

[3:04]  
so I think the features probably should not be under api-server

deads2k [3:04 PM] 
@timothysc but one that is applicable to the kube-apiserver

[3:04]  
@timothysc apiserver is actually a generic apiserver.  Imagine it as the basis for all other APi server, like servicecatalog

timothysc [3:04 PM] 
no it's for the scheduler.

deads2k [3:05 PM] 
it doesn't make sense for an API package to be making decisions based on its feature gate

timothysc [3:05 PM] 
it's just the dep-graph

deads2k [3:05 PM] 
the API is shared both client and server

timothysc [3:05 PM] 
alpha-beta api feature gate

deads2k [3:05 PM] 
and so if someone on the client tried use this, they'd never be confident that they matched the server

[3:05]  
looks like your helper just needs to move to a different spot

timothysc [3:06 PM] 
well to be clear I can get around it, but I figured folks would want the capability to feature gate an API.. but yes it would affect both.

[3:07]  
my subterfuge is just to shuffle the code so the utility is not in the helpers.

deads2k [3:07 PM] 
yeah, it probably doesn't belong there

timothysc [3:07 PM] 
But I would image that folks would want/need this when going alpha-beta in some cases.

deads2k [3:07 PM] 
because its feature gate dependent and it would end up inconsistent when used from something like the cleint-go users

timothysc [3:07 PM] 
given the annotations->fields issues

deads2k [3:08 PM] 
passing a boolean through would make sense

[3:08]  
that would make the choice explicit, but including it in client-go will produce weird behavior

[3:08]  
including the feature flag in client-go will produce weird behavior

timothysc [3:09 PM] 
k, I'll scuttle and move along then.

**Comment by deads2k** [comment]
The API packages shouldn't rely on feature gates, because client-go relies upon the APIs and the feature-gates won't be used cleanly or reliably by the vast majority of client-go users.

You could pass a boolean instead and keep the helper with the bool in the sig (to make the choice obvious) or move the helper entirely.
