### ISSUE TITLE
Remove StatefulSet Init Annotation

### ISSUE THREAD

**Issue by kow3ns** [kubernetes/kubernetes#41605]
** FEATURE REQUEST** 

The annotation 
```yaml
pod.alpha.kubernetes.io/initialized=bool
```
needs to be deprecated as was decided in the Beta-GA roadmap.
All e2e tests need to be updated to not use this annotation.

**Comment by dhilipkumars** [comment]
Hi @kow3ns I can help with this if no one has picked it up currently.

**Comment by kow3ns** [comment]
@dhilipkumars I think we should wait until we get feedback. It was on the beta roadmap to remove this before GA, and it will need to be either promoted or removed, but we should make sure that people are not using first. Also, be aware, that pretty much all of the e2e testing works off of this annotation so this will require quite a bit of work. @smarterclayton do you know of anyone who is depending on this.

**Comment by dhilipkumars** [comment]
@kow3ns also 1.6 promotes affinity annotation to pod spec, all the examples that uses Affinity should be fixed too.  We could handle that aswell. 

Where is Beta Roadmap for statefulset? Could you link that with this issue?

**Comment by smarterclayton** [comment]
I know a lot of the original petset examples used the annotation, so I
expect a fair amount of cargo culting.

**Comment by enisoc** [comment]
Status:

- [x] Stop using the annotation in e2e tests. (#49251)
- [x] Remove the annotation from apps/v1beta1 and add release-note-action-required. (#49251)
- [x] Remove the annotation from StatefulSet examples. (https://github.com/kubernetes/examples/pull/32)
- [x] Update docs for 1.8. (https://github.com/kubernetes/kubernetes.github.io/pull/4426)
- [ ] Cherrypick e2e test change to release-1.7 branch so skew tests will work.
- [ ] Remove the annotation from apps/v1beta2.
