### ISSUE TITLE
Creating a Secret with a Docker Config with kubectl command is broken

### ISSUE THREAD

**Issue by Miyurz** [kubernetes/kubernetes#41619]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No, its a bug in kubectl.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
.dockercfg, .dockerconfigjson
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
Server version : 1.4.7
Client version:  1.5.2

**Environment**:
- **Cloud provider or hardware configuration**:
AWS
- **OS** (e.g. from /etc/os-release):
jessie
- **Kernel** (e.g. `uname -a`):
4.4.26-k8s
- **Install tools**:

- **Others**:

**What happened**:
Secret created with kubectl command as mentioned in [](https://kubernetes.io/docs/user-guide/images/ )under the section 

> Creating a Secret with a Docker Config

with kubectl command is buggy. The imagepullsecrets created that way doesn't pull images with .dockercfg as the type but if we try to pass it with file with type .dockerconfigjson, it works fine.
**What you expected to happen**:
Both the approaches mentioned in the above link should work.

**How to reproduce it** (as minimally and precisely as possible):
Spin up a cluster with kubectl 1.4.7, create a secret for docker registry from command line and try to pull the image via pod definition with the specified imagepullsecret. make sure this is for some private docker hub registry. 

**Anything else we need to know**:
It works for the second approach when we pass registry via yaml file and specify the type to .dockerconfigjson

**Comment by ahawkins** [comment]
I believe the difference between `.dockercfg` and `.dockerconfigjson` secret types is they're intended for different Docker versions. My guess is this at the heart of the bug: you must use the correct secret type that matches your Docker version.

**Comment by liggitt** [comment]
Correct, those two files have different formats, unfortunately. You cannot use the content of one with the other type.

**Comment by ahawkins** [comment]
@liggitt Makes sense. Do you think there is a UX improvement to be made here? The command in the docs should generate the correct file based on the docker version in the cluster. `.dockercfg` is quite old, thus people using the documented solution may be hitting these issues frequently.

**Comment by liggitt** [comment]
The command is run on client machines that have no idea what docker version is in use. I think either format works (the credentials are parsed and used by the node, not docker), but requires the format to match the specified type. The CLI could validate the content matches the specified type.
