### ISSUE TITLE
Make DaemonSet respect "critical pods annotation" when scheduling

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#41612]
So that DaemonSet can schedule critical pods onto nodes, and kubelet will preempt non-critical pods. #40573 

@kubernetes/sig-apps-feature-requests @erictune @vishh

**Comment by liggitt** [comment]
are we expanding use of this annotation?

**Comment by vishh** [comment]
@liggitt This annotation is a primitive implementation of `priority`. The real use case is that of running `critical system pods (daemons) across all nodes`. 
@janetkuo FYI: The annotation is currently gated by a Feature Gate and we should respect that in DaemonSet controller too.
