### ISSUE TITLE
Archive hollow node logs in (pre-submit) kubemark tests

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#41613]
The logs are currently not uploaded to GCS. Debugging kubemark requires running the test yourself or ssh'ing into a jenkins cluster running kubemark. Can we collect the logs to facilitate debugging?

/cc @wojtek-t @gmarek @shyamjvs

**Comment by gmarek** [comment]
Yes we can - we know that we don't do it. It was an accident at the beginning, but we decided that's a lucky one, as we're not sure how our test env will survive downloading logs from 5000 hollow nodes. I guess we can switch it on for some time.

**Comment by gmarek** [comment]
Ideally it would be turned on by the flag and enabled only in pre-submit kubemark (+ maybe in some of the smaller ones)

**Comment by wojtek-t** [comment]
Yup - this should be pretty simple to switch on. And I agree we should first start with enabling it only for small kubemarks (e.g. <=100 nodes)

**Comment by yujuhong** [comment]
I think it should definitely be enabled for presubmit. The next to consider is the submit queue blocking "ci-kubernetes-kubemark-500-gce" suite, but that depends on how often it fails.

**Comment by wojtek-t** [comment]
+1 for presubmit

The 500-node one is super stable - e.g. all the failures from last week were regressions.

**Comment by yujuhong** [comment]
> The 500-node one is super stable - e.g. all the failures from last week were regressions.

Agreed. Hopefully the presubmit tests will catch most of the regressions from now on.

**Comment by shyamjvs** [comment]
I'll look into enabling the hollow-node logs (both kubelet and proxy) for presubmit and 100-node tests then. Seems like that should suffice for now from above discussion.

**Comment by shyamjvs** [comment]
Closing this issue as hollow-node logs are getting artifacted after PR https://github.com/kubernetes/kubernetes/pull/41800 has been merged.
We can reopen this if we have problems around hollow-node logging in future.
