### ISSUE TITLE
kubelet keeps reporting errors

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#41616]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Using `hack/local-up-cluster.sh` to start a cluster with only one node and found that there are some error logs in kubelet as following:

```
E0217 11:15:39.175803   31536 docker_sandbox.go:370] Failed to list checkpoints: failed to list checkpoint store: open /var/lib/dockershim/sandbox: no such file or directory
E0217 11:15:40.178541   31536 docker_sandbox.go:370] Failed to list checkpoints: failed to list checkpoint store: open /var/lib/dockershim/sandbox: no such file or directory
E0217 11:15:41.181541   31536 docker_sandbox.go:370] Failed to list checkpoints: failed to list checkpoint store: open /var/lib/dockershim/sandbox: no such file or directory
E0217 11:15:42.184452   31536 docker_sandbox.go:370] Failed to list checkpoints: failed to list checkpoint store: open /var/lib/dockershim/sandbox: no such file or directory
E0217 11:15:43.187075   31536 docker_sandbox.go:370] Failed to list checkpoints: failed to list checkpoint store: open /var/lib/dockershim/sandbox: no such file or directory
E0217 11:15:44.191545   31536 docker_sandbox.go:370] Failed to list checkpoints: failed to list checkpoint store: open /var/lib/dockershim/sandbox: no such file or directory
E0217 11:15:45.194913   31536 docker_sandbox.go:370] Failed to list checkpoints: failed to list checkpoint store: open /var/lib/dockershim/sandbox: no such file or directory
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by gyliu513** [comment]
cc @Random-Liu

**Comment by gyliu513** [comment]
Seems caused by my env due to I cannot access gcr due to the proxy failed, will continue to check...

```
root@k8s001:~# docker pull gcr.io/google_containers/pause-amd64:3.0
Error response from daemon: Get https://gcr.io/v1/_ping: dial tcp 64.233.188.82:443: i/o timeout
```

**Comment by Random-Liu** [comment]
@freehan We should create the checkpoint directory when creating the checkpoint store, or else the  list failed error will be quite spammy.

**Comment by freehan** [comment]
Will push a fix soon.
