### ISSUE TITLE
Which Docker version(s) for Kubernetes v1.6.0-alpha.0.2074+a092d8e0f95f52

### ISSUE THREAD

**Issue by noriuky** [kubernetes/kubernetes#41620]
I installed kubernetes v1.6.0-alpha.0.2074+a092d8e0f95f52
i wonder which Docker ver is compatible with this.
Plz there is a place where to find this info, i lost hrs on google without success.
Tnx

**Comment by yujuhong** [comment]
The most tested docker version on GCE with v1.6.0-alpha is 1.11.2. There are also less-extensive testing with docker 1.10.3 and 1.12.6. If you are using other cloud provider/vendor, the answer may change.

**Comment by azimut** [comment]
@yujuhong How can we know the status of testing of kubernetes against different docker versions over time?. Are these tests public?

**Comment by yujuhong** [comment]
You should check the release note (changelog) for the information for each kubernetes release.

For the master branch, sig-node runs node e2e tests for a set of (OS distro, docker version) combinations.
The tests are public and the results are published here: https://k8s-testgrid.appspot.com/google-node#kubelet
The images (OS distro+docker version) used in the suite are listed in https://github.com/kubernetes/kubernetes/blob/release-1.6/test/e2e_node/jenkins/image-config.yaml
