### ISSUE TITLE
fluentd loading from minion can't reached the kubernetes apiserver

### ISSUE THREAD

**Issue by bamb00** [kubernetes/kubernetes#41623]
---

**kubernetes version v1.5.3**

**Environment**:
- **k8 master & minions on AWS**
- **Ubuntu** 
- **1 master, 2 Minions**:

**Fluentd pod load from master is fine but from minions failed with error cannot access kubernetes apiserver:** 
**2017-02-17T06:05:22.362485115Z 2017-02-17 06:05:22 +0000 [info]: adding filter pattern="kubernetes.**" **type="kubernetes_metadata"**
**2017-02-17T06:06:22.708046430Z 2017-02-17 06:06:22 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error="Invalid Kubernetes API v1 endpoint https://apiserver_IP:443/api: Timed out connecting to server"
2017-02-17T15:37:07.401282377Z 2017-02-17 15:37:07 +0000 [info]: process finished code=256
2017-02-17T15:37:07.401307101Z 2017-02-17 15:37:07 +0000 [error]: fluentd main process died unexpectedly. restarting.
2017-02-17T15:37:07.401317662Z 2017-02-17 15:37:07 +0000 [info]: starting fluentd-0.12.31**

**fluentd pod should load successfully from minions**:

**Issue:: Deploy fluentd pod to node running on master and to nodes running on multiple minion**

**secgrp port 443 is open inbound for apiserver**:

**Comment by rootsongjc** [comment]
@bamb00 How do you solve the problem?
Do you change the `td-agent.conf`?
