### ISSUE TITLE
KUBERNETES_PROVIDER is centos,cluster/kube-up.sh don't work, k8s 1.5.2

### ISSUE THREAD

**Issue by strugglingyouth** [kubernetes/kubernetes#41632]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

1.5.2
**Environment**:
- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release): centos 7.2
- **Kernel** (e.g. `uname -a`):  3.10.0-327.10.1.el7
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

my step  is:

#### purpose 

To test 1.5 master HA   [https://kubernetes.io/docs/admin/ha-master-gce/](https://kubernetes.io/docs/admin/ha-master-gce/)

####  1,
    export KUBERNETES_PROVIDER=centos
    
    export KUBE_VERSION=1.5.2

    export ETCD_VERSION=3.0.4

    config the file of  cluster/centos/config-default.sh

and another result is :  

####  2,
    ./kube-up.sh

After completion, no service start

**Comment by Rev1408** [comment]
Hi,

were you able to resolve it, I have same problem.

Thanks!!

**Comment by noxon73** [comment]
Me too...
`export KUBERNETES_PROVIDER=centos; ./get.k8s.sh                                                                                                                                                                      
'kubernetes' directory already exist. Should we skip download step and start to create cluster based on it? [Y]/n

Skipping download step.
Creating a kubernetes on centos...
./cluster/../cluster/../cluster/centos/config-default.sh: line 100: cd: ./cluster/../cluster/../cluster/centos/ca-cert: No such file or directory
... Starting cluster using provider: centos
... calling verify-prereqs
Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
Identity added: /root/.ssh/id_ecdsa (/root/.ssh/id_ecdsa)
... calling verify-kube-binaries
!!! kubectl appears to be broken or missing
Required binaries appear to be missing. Do you wish to download them? [Y/n]

Kubernetes release: v1.6.2
Server: linux/amd64  (to override, set KUBERNETES_SERVER_ARCH)
Client: linux/amd64  (autodetected)

Nothing additional to download.
... calling kube-up
[INFO] make-ca-cert
bash: ./cluster/../cluster/../cluster/centos/../saltbase/salt/generate-cert/make-ca-cert.sh: No such file or directory`

**Comment by byouloh** [comment]
For "make-ca-cert.sh: No such file or directory", I found the following answer:
https://github.com/kubernetes/kubernetes/issues/30751

Suppose you downloaded and untar kubernetes binaries to your_home/kubernetes directory. You can see the kubernetes-salt.tar.gz file in your_home/kubernetes/server directory, after download server binary files. You have to untar kubernetes-salt.tar.gz and copy all the file of saltbase to your_home/kubernetes/cluster.

Then, you can solve your problem, but you will meet new issue,
[INFO] make-ca-cert
chgrp: invalid group: ‘kube-cert’

Currently, I'm working on it (:
