### ISSUE TITLE
e2e flake: Cluster level logging using GCL should check that logs from containers are ingested in GCL

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#41647]
Due to some recent changes (at some point before 16th), fluentd OOMs and e2e test flakes

CC @piosz

**Comment by yujuhong** [comment]
It'd be nice to have the name of the failing tests in the issue to avoid duplicates :-)

**Comment by Crassirostris** [comment]
@yujuhong Absolutely, sorry! Thanks a lot for pointing that out :)

**Comment by dcbw** [comment]
Still getting fluentd oom kills for example https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42748/pull-kubernetes-e2e-gce-gci/21896/

**Comment by crassirostris** [comment]
@dcbw fluentd started to OOM more because kube-proxy started to log more

There's no solution for that so far, I moved fluentd tests to Flaky suite

**Comment by crassirostris** [comment]
@dcbw Since tests are marked flaky, they shouldn't harm you. Are you sure test failed because of fluentd?

**Comment by dcbw** [comment]
@crassirostris you are correct; the test succeeded on retry and there are still fluentd ooms.  Sorry for the false alarm.

**Comment by ethernetdan** [comment]
Sounds like this issue is not release blocking, please correct milestone if this is inaccurate.

**Comment by crassirostris** [comment]
Flakiness fixed by: https://github.com/kubernetes/kubernetes/pull/43441 https://github.com/kubernetes/kubernetes/pull/43294 https://github.com/kubernetes/kubernetes/pull/43574
