### ISSUE TITLE
1.5.2 Performance Issues on AWS

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kubernetes#41640]
**Is this a request for help?** 
No

**What keywords did you search in Kubernetes issues before filing this one?**:
1.5.2, performance

---

**Is this a BUG REPORT or FEATURE REQUEST?**
Bug report 

**Kubernetes version** (use `kubectl version`): 1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Jessie
- **Kernel** (e.g. `uname -a`):  4.4.41-k8s
- **Install tools**: KOPS
- **Others**:

**What happened**:
1.5.2 is nowhere near stable for us, We used to run 1.4.6 and it was rock solid stable but when we upgraded to 1.5.2 we are hitting some performance issues across several services running into our k8s cluster, just to picture it:

![image](https://cloud.githubusercontent.com/assets/285782/23067326/eb5f2d86-f505-11e6-9e4b-9c21a8dfa3ea.png)

![image](https://cloud.githubusercontent.com/assets/285782/23067328/f1454302-f505-11e6-8011-b27f0377e0a1.png)

![image](https://cloud.githubusercontent.com/assets/285782/23067336/fb445104-f505-11e6-8c85-db120f5832c4.png)

As you can see, something seems to have happened at around 02:00 that affected some unrelated services, we have a cluster with 35 nodes. 
This is the second time this happens, from nowhere some routes that returns more data than others starts to get in increasing performance degradation, the first time it happened, I shutted down all nodes and waited for them to recover (I'm using a autoscaling group) and the problem gone but after 3 days it happened again, the first time it happened it was also a degradation that came from nowhere:

![image](https://cloud.githubusercontent.com/assets/285782/23067412/588921dc-f506-11e6-91aa-8ba1d78c99e1.png) 

**What you expected to happen**:
No more performance issues

**How to reproduce it**:
Running a 1.5.2 cluster on AWS for some days in production

**Anything else we need to know**:
We are also hitting some issues in our staging cluster on AWS, we need to reset docker services at some minion nodes from time to time because all pods get stuck in an unresponsive state and only restarting docker helps. Our staging cluster has an intensive pod creation/destroy activity because of CI, we also run 1.5.2 on it.

**Comment by justinsb** [comment]
OTOH, I would guess one of these things:

* kube-controller-manager messing up the routes (seems unlikely).  (Can you confirm you're using kube-net)
* kube-proxy messing up the service -> pod mappings on one or more nodes.  Maybe then your application retries the request, so it still goes through, just with a delay.  This seems fairly likely.
* kube-dns being slow to resolve the service name to the service IP.  Possible.
* maybe something to do with ELB or ingress.  Are they involved in this request though  (this sounds like a request inside the k8s cluster)?

**Comment by felipejfc** [comment]
I'm using Kubenet

**Comment by felipejfc** [comment]
i think that last time it happened I've tried to delete all kube-proxy and kube-dns pods and wait for new ones to start but it didn't help. Only thing that helped was to shutdown all worker nodes and wait for new ones to spin up...

**Comment by justinsb** [comment]
If we can, I think it would be great to try to narrow it down layer by layer.  We hope that at some layer we see the high latency, and then as we remove layers we observe that everything is fast, which helps us figure out the problematic layer:

So the layers

1) The ELB: From your machine or from an EC2 instance to the ELB endpoint
2) From a pod (`kubectl exec -it`) to the kubernetes service name (i.e. eliminating the ELB)
3) From a pod the kubernetes service IP (i.e. eliminating the DNS lookup)
4) From a pod to a pod IP that is part of the service (do `kubectl get endpoints <servicename>` to see the pod endpoints).
5) Directly querying the pod on `http://127.0.0.1:8080` or whatever (i.e. is it the app)

**Comment by felipejfc** [comment]
I've tried to debug it with no success but I have some news, as I've said:

```
Anything else we need to know:
We are also hitting some issues in our staging cluster on AWS, we need to reset docker services at some minion nodes from time to time because all pods get stuck in an unresponsive state and only restarting docker helps. Our staging cluster has an intensive pod creation/destroy activity because of CI, we also run 1.5.2 on it.
```

I just confirmed that restarting docker services in our k8s nodes also solves this strange performance degradation that I reported

**Comment by felipejfc** [comment]
We are still hitting this issue with kubernetes 1.5.4
It seems to be the communication between kubernetes node and external services.
We are seeing increasing response times on selects on our databases when a lot of data is grabbed from them...

**Comment by javapapo** [comment]
similar issues with kubernetes 1.5.3, on top of AWS. I can narrow it down to internal pod to service resolution where pods from app X whentl they try to access service Y ... the http client reports can not find dns entry (y service) .
