### ISSUE TITLE
Test if Daemonsets will drain if they have local storage

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#41643]
Working with `kops` rolling-update I notice that Daemonsets may be drained if they are marked as to ignore, but have local storage.  This issue it to write a unit test to determine if this is correct.

**Comment by kargakis** [comment]
@kubernetes/sig-apps-misc

**Comment by chrislovecnm** [comment]
@kargakis this kind seems to be sig/cli since this is kubectl code.  I missed that information in my bug report.

When a node is drained that is a Daemonset, and has local storage, I am getting warnings / errors.  The output from the drain code is odd, or the filter is incorrect. I have not had time to triage.

**Comment by kargakis** [comment]
> @kargakis this kind seems to be sig/cli since this is kubectl code. I missed that information in my bug report.

sig/apps folks are likely interested. drain code will move at some point in the server but sig/apps folks will continue to be interested ;)
