### ISSUE TITLE
kubectl drain error - Eviction: no kind "Eviction" is registered for version "policy/v1beta1"

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#41656]
This is a what I believe is a bug in the API or kubectl drain.

**Kubernetes version** (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:43:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
```

I am going to test on the latest as well.

**BUG REPORT**

**Environment**:
- **Cloud provider or hardware configuration**: aws built with kops
- **OS** (e.g. from /etc/os-release): debian
- **Kernel** (e.g. `uname -a`): N/A
- **Install tools**: kops
- **Others**:

**What happened**:

```
$ kubectl drain ip-172-20-116-29.ec2.internal --force --delete-local-data --ignore-daemonsets
node "ip-172-20-116-29.ec2.internal" already cordoned
WARNING: Deleting pods not managed by ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet: etcd-server-events-ip-172-20-116-29.ec2.internal, etcd-server-ip-172-20-116-29.ec2.internal, kube-apiserver-ip-172-20-116-29.ec2.internal, kube-controller-manager-ip-172-20-116-29.ec2.internal, kube-proxy-ip-172-20-116-29.ec2.internal, kube-scheduler-ip-172-20-116-29.ec2.internal; Deleting pods with local storage: weave-net-fctl4; Ignoring DaemonSet-managed pods: weave-net-fctl4
WARNING: Deleting pods with local storage: weave-net-fctl4; Ignoring DaemonSet-managed pods: weave-net-fctl4; Deleting pods not managed by ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet: etcd-server-events-ip-172-20-116-29.ec2.internal, etcd-server-ip-172-20-116-29.ec2.internal, kube-apiserver-ip-172-20-116-29.ec2.internal, kube-controller-manager-ip-172-20-116-29.ec2.internal, kube-proxy-ip-172-20-116-29.ec2.internal, kube-scheduler-ip-172-20-116-29.ec2.internal
There are pending pods when an error occurred: error when evicting pod "dns-controller-1528204154-mibl8": Eviction in version "v1beta1" cannot be handled as a Eviction: no kind "Eviction" is registered for version "policy/v1beta1"
pod/dns-controller-1528204154-mibl8
error: error when evicting pod "dns-controller-1528204154-mibl8": Eviction in version "v1beta1" cannot be handled as a Eviction: no kind "Eviction" is registered for version "policy/v1beta1"

**What you expected to happen**:

Node should drain with the dns-controller pod on it.

**How to reproduce it** (as minimally and precisely as possible):

Install this:

```yaml
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: dns-controller-test
  namespace: kube-system
  labels:
    k8s-app: dns-controller-test
    version: v1.5.1
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: dns-controller-test
  template:
    metadata:
      labels:
        k8s-app: dns-controller-test
        version: v1.5.1
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key": "dedicated", "value": "master"}]'
    spec:
      nodeSelector:
        kubernetes.io/role: master
      dnsPolicy: Default  # Don't use cluster DNS (we are likely running before kube-dns)
      hostNetwork: true
      containers:
      - name: dns-controller-test
        image: kope/dns-controller:1.5.1
        command:
          - sh
          - -c
          - "exec tail -f /dev/null"
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
```

Try to drain it ..

**Anything else we need to know**:

Nope

cc: @justinsb @kubernetes/kubectl @kubernetes/sig-node @foxish

**Comment by qiujian16** [comment]
It is because of the version incompatibility between client and server. The client is version 1.5, and it will call Eviction in policy/v1beta1 group. While server is version 1.4, and the Eviction is only in group policy/v1alpha1. You can change your client to version 1.4.

**Comment by chrislovecnm** [comment]
@qiujian16 so what is our policy on backward compatibility?  My thought is that kubectl should support this, and for instance `kubectl get petset` does at least show petsets when using kubectl 1.5.x -> 1.4.x cluster.

**Comment by foxish** [comment]
May be related to https://github.com/kubernetes/kubernetes/issues/40813

**Comment by chrislovecnm** [comment]
@qiujian16 / @foxish see #40813 - yes I believe it is related, but I do not understand how the `SupportEviction` code works.

**Comment by smarterclayton** [comment]
We support a version mismatch between kubectl and apiserver of no more than one version (older clients must be able to work).  However, moving from alpha features to beta features has no compatibility guarantees across releases, and I think that's what defines the problem here.

**Comment by ymqytw** [comment]
> moving from alpha features to beta features has no compatibility guarantees across releases, and I think that's what defines the problem here.

Since we don't support this. Should we close this or remove it from 1.6 milestone?

**Comment by calebamiles** [comment]
Closing per https://github.com/kubernetes/kubernetes/issues/41656#issuecomment-285204745

**Comment by matthiasr** [comment]
It's probably not worth fixing anymore since 1.5 <-> 1.6 won't be affected IIUC, but I wanted to say that I disagree with "no compatibility guarantees" – evictions may be, but `kubectl drain` has been around for a long time, and is broken in a supported combination of versions (newer clients against older api-servers are supported too, I think?). That it's broken because it's trying to use an alpha feature doesn't change that it worked before (using DELETE).
