### ISSUE TITLE
azure_routes: the plugin should back off properly on 429 and other failures

### ISSUE THREAD

**Issue by yangl900** [kubernetes/kubernetes#41671]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): NO

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): Azure route

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
v1.4.6
GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6",

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): Ubuntu
- **Kernel** (e.g. `uname -a`): 4.4.0-62-generic
- **Install tools**: acs-engine
- **Others**:

**What happened**:
When provisioning a cluster with more than 100 nodes, controller manager will hit the default Azure subscription limit of "100 custom defined route per route table". When hitting this limit, the controller manager will keep retrying, eventually hitting Azure Resource Manager write request limit 1200 / hour. Once hitting this limit, Azure returns 429 with a Retry-After header. However the controller manager will continue retrying and maintain a request rate higher than 1200 / hour. Effectively the Azure subscription will maintain a throttling state forever until shutdown master node. This can even block other write operations from Azure portal etc.

**What you expected to happen**:
Route controller should retry with proper backoff, and azure_routes.go should respect the Retry-After header and backoff based on it.

**How to reproduce it** (as minimally and precisely as possible):
1. Provision a cluster with >100 agent node on Azure
2. Wait at least 1 hour
3. kubectl logs kube-controller-manager-k8s-master-XXXX --namespace kube-system --tail 50 to see the failures saying being throttled.

**Anything else we need to know**:

**Comment by yangl900** [comment]
@brendandburns FYI

**Comment by jdumars** [comment]
Closing as stale.  Original submitter can re-open if issue is still valid post 1.8.x
