### ISSUE TITLE
Inability to detect disk space leads to kubelet failing entirely, cadvisor tries things that need root

### ISSUE THREAD

**Issue by bobobo1618** [kubernetes/kubernetes#41686]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):  Disk space, cadvisor

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+5802799", GitCommit:"5802799e56c7fcd1638e5848a13c5f3b0b1479ab", GitTreeState:"not a git tree", BuildDate:"2017-02-18T00:31:14Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+5802799", GitCommit:"5802799e56c7fcd1638e5848a13c5f3b0b1479ab", GitTreeState:"not a git tree", BuildDate:"2017-02-18T00:31:14Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Bare metal
- **OS** (e.g. from /etc/os-release): Arch Linux
- **Kernel** (e.g. `uname -a`): `Linux host 4.9.8-1-ARCH #1 SMP PREEMPT Mon Feb 6 12:59:40 CET 2017 x86_64 GNU/Linux`
- **Install tools**: Built package based on modified [AUR PKGBUILD](https://aur.archlinux.org/packages/kubernetes/) (changed to version `1.6.0-alpha.3`)
- **Others**: Followed the [from scratch guide](https://kubernetes.io/docs/getting-started-guides/scratch/) as close as possible to get set up.

**What happened**:

When starting `kubelet`, it fails to move from `NotReady` to `Ready`. Logs show this sequence repeating indefinitely:

```
Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": unable to find data for container /
Feb 17 22:27:46 host kubelet[3753]: E0217 22:27:46.372891    3753 kubelet.go:1622] Failed to check if disk space is available on the root partition: failed to get fs info for "root": error trying to get filesystem Device for di
r /var/lib/kubelet: err: could not find device with major: 0, minor: 20 in cached partitions map
Feb 17 22:27:50 host kubelet[3753]: I0217 22:27:50.624819    3753 kubelet.go:1705] skipping pod synchronization - [container runtime is down]
Feb 17 22:27:50 host kubelet[3753]: E0217 22:27:50.763895    3753 kubelet.go:2011] Container runtime status is nil
Feb 17 22:27:55 host kubelet[3753]: I0217 22:27:55.625051    3753 kubelet.go:1705] skipping pod synchronization - [container runtime is down]
Feb 17 22:27:55 host kubelet[3753]: E0217 22:27:55.765642    3753 kubelet.go:2011] Container runtime status is nil
```

**What you expected to happen**:

Kubelet to start without issues.

**How to reproduce it** (as minimally and precisely as possible):

I'm not sure what exactly is wrong so it's hard to say. It appears the cadvisor API isn't returning things correctly for some reason? When I try to run the cadvisor binary directly, for some reason it starts attempting to run `zfs` commands (I have ZFS filesystems on my system) despite cadvisor not being run as root. I suspect that since the filesystems mounted to `/var/lib/kubelet` and `/` are both BTRFS that cadvisor is trying to run `btrfs fi show` or something silly like that as well.

**Anything else we need to know**:

I understand the reasoning behind `kubelet` failing when it can't assess free disk space but there should be intelligent fallbacks (like the standard `df`) when cadvisor fails. I'm also curious why `cadvisor` is being used at all given that it seems to be intended for containers and `kubelet` doesn't seem to be intended to run inside them.

**Comment by dchen1107** [comment]
@bobobo1618 From what you posted above, the reason of the node is NotReady is due to runtime is down. What is your runtime? Docker? Can you run node conformance tests to make sure your node meeting the minimal requirements?

**Comment by castrojo** [comment]
/assign

I'm going to close this due to inactivity, reporter, when you have new information please feel free to reopen this bug, thanks!
