### ISSUE TITLE
`kubectl apply ` output in inconsistency

### ISSUE THREAD

**Issue by shiywang** [kubernetes/kubernetes#41690]
assume I have a rc.yaml
``` console
apiVersion: v1
kind: ReplicationController
metadata:
  name: test-rc
  labels:
    name: foo
spec:
  ....
```
when I run `apply` first time to create this resource, like `kubectl apply -f rc.yaml -o yaml`
the output I got is the resource same as live object, with annotations.
```console
apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ReplicationController","metadata":{"annotations":{},"labels":{"name":"foo"}
...
```

but if I change the rc.yaml like change the label  `name: foo`  to `name: bar`  then run 
`kubectl apply -f rc.yaml -o yaml` 
the output I got is still  `name: foo` in annotations. 
```console
apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ReplicationController","metadata":{"annotations":{},"labels":{"name":"foo"},
```
should the last time `-o yaml` output to be live object in server ?

@kubernetes/sig-cli-bugs  @pwittrock @AdoHe

**Comment by liggitt** [comment]
What version of kubectl do you have? Is the label actually changed?

**Comment by shiywang** [comment]
@liggitt I use the latest master version, the label not changed, I think the reason is because first time using apply to create a resource, it invoke [this](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/apply.go#L264):  `info.Refresh(obj, true)`, then `PrintResourceInfoForCommand`, but if we apply to a resource already exist, it doesn't invoke `info.Refresh(obj, true)`, but I'm not sure if it's a bug or we just let it be, if it's a bug, I would like to fix that.

**Comment by liggitt** [comment]
I see what you're saying. Yes, I would expect the output to reflect the latest result from the server of applying the patch.

**Comment by liggitt** [comment]
fixed in #41699

**Comment by liggitt** [comment]
to be clear, when you say "the label not changed", you mean in the output of the `apply` command, right? if you do another `kubectl get` to see the server's version, the label was correctly changed, right?

**Comment by shiywang** [comment]
@liggitt yes
