### ISSUE TITLE
MostRequestedPriority should prefer to not pack nodes to 100%

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#41712]
This was suggested by @matchstick a couple of weeks ago and it makes a lot of sense.

Our "best-fit" scheduling algorithm (["MostRequestedPrioity"](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/priorities/most_requested.go)) is pure best-fit, which ties to pack nodes to 100% in all resource dimensions. But this is actually too aggressive because (1) it's never good to pack a node to 100% because it makes the OS freak out, and (2) we have OOR killers for memory and disk that start evicting pods at < 100% utilization. So MostRequestedPriority shouldn't be targeting 100% (i.e. giving the best score to 100% full), instead it should target something lower, with a large score penalty for exceeding that.

(In theory we could instead change the resource predicate function to not allow packing to 100%, but I think that would be too confusing for users. It's also too conservative, since OOR is based on usage while resource predicate function is based on request.)

Documentation on OOR killers is [here](https://kubernetes.io/docs/admin/out-of-resource/). It looks like the configuration is [here](https://github.com/kubernetes/kubernetes/blob/1fc1e5efb5e5e1f821bfff8e2ef2dc308bfade8a/cmd/kubelet/app/options/options.go#L240) and on the subsequent line.

I think we want there to be some way to configure the "how much less than 100%" threshold (independently for memory and disk, though of course today we don't have disk as a resource). IIRC we don't currently have any scheduler predicate or priority functions that take configuration arguments (this should be verified--I could be wrong), in which case we need to figure out a reasonable way to pass them arguments. In particular, we should make sure the design of #41600 makes it possible to specify arguments to the predicate and priority functions (even if such arguments are independent config options whose name suggests which predicate/priority function they are tied to).

Because OOR is based on usage rather than request, we don't need to target something much lower than 100%, but it should be something lower, and user-configurable.

@kubernetes/sig-scheduling-feature-requests 

cc/ @bsalamat who is working on #41600

**Comment by wanghaoran1988** [comment]
@davidopp Can we add a resource allocatable radio to the node configuration maybe can using a annotation, like a node have a total memory 10G, and  can be allocated  90%  of the total, the the kubelet will report  periodically with the computed value 9G, and the scheduler still use the allocatable value 9G to schedule, this will make the scheduler logic simple.

**Comment by cmluciano** [comment]
@wanghaoran1988 Is that similar to the kube-reserved or system-reserved flags that can be passed to the kubelet?

**Comment by vishh** [comment]
https://github.com/kubernetes/community/pull/348 is relevant here.
Specifically, I'm changing Allocatable to take into account memory reserved
for eviction thresholds.
The effective allocatable will be `Capacity - kube reserved - system
reserved - OOR hard eviction threshold`.

I suspect that by itself should address the concern in this issue.

**Comment by davidopp** [comment]
@vishh Ah, I didn't know allocatable was going to subtract out the memory reserved for eviction thresholds. I think that is a good enough solution; I don't think there's much need to make the "optimal" packing ratio on each machine independently tunable with a scheduler parameter if we have what you described.

I'm going to close this issue.
