### ISSUE TITLE
Make `docker-email` optional when create registry secret

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#41727]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
When I create a docker registry secret, the `docker-email` is also a MUST, I think we should make this parameter as optional as there is no need always put `docker-email` when creating a docker registry secret.

```
kubectl create secret docker-registry regsecret --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by smarterclayton** [comment]
Agree it should not be required

**Comment by AaronFriel** [comment]
Did this change get reverted? I do not see `--docker-email` as optional on stable.

**Comment by apri12** [comment]
I feel that this code should be changed because "--docker-email flag" is no longer required.
https://github.com/kubernetes/kubernetes/commit/50943d17838e60cff07cc8106ae0dddc2b90b067#diff-5cbf8d0bccc129f03f4a6c5eebe29bdcR172

**Comment by 372046933** [comment]
error: flag docker-email is required.
On kubenetes 1.10.3, the above error message still exists

**Comment by JakeKo** [comment]
The `--docker-email` field is still required. This is very frustrating as `docker login` does not require an email but Kubernetes does? Is there a good reason for this?

**Comment by srudin** [comment]
Why is this closed? As far as I can see it is still required?
