### ISSUE TITLE
[Federation] Better usability for kubefed

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/kubernetes#41725]
**kubefed** tool, which is used to deploy a federation control plane:

1 - Does not do a very good job of giving status information to the end user. If the operations take long time it appears to be hung (especially kubefed init).
2 - There is a possibility that the deployed pods of the federation control plane, do not come up successfully, in such a scenario the kubefed init will wait indefinitely. Ideally, there could be a timeout set to override this behavior (Issue #43123).
3 - If some operation fails midway of overall execution, the tool should ideally clean up all of the objects that it creates into host cluster or target cluster before exiting.
4 - There should ideally be a kubefed deinit which can enable removing the federation control plane deployment from the host cluster.
5 - Both kubefed init and kubefed join can create service accounts to access either the underlying cluster or joining clusters; A workaround is needed such that DNS-1123 subdomain naming is not violated while doing this. Refer https://github.com/kubernetes/kubernetes/issues/50888.

**Comment by irfanurrehman** [comment]
cc @madhusudancs @shashidharatd @marun 
you can please add any other usability issue that, you think I have missed here.

**Comment by madhusudancs** [comment]
Agreed with all the above. I think (1) is critical, (2) and (3) are important and (4) is a nice to have.

**Comment by perotinus** [comment]
I'll take a stab a 1).

Is it worth splitting these out into separate issues?

**Comment by madhusudancs** [comment]
@perotinus @irfanurrehman we need to coordinate about who is going to work on what. 

@irfanurrehman have you already started working on 1)? If you haven't started yet, do you mind if @perotinus takes a look?

@perotinus yeah, it makes to sense to file separate issue, but keep this on as an umbrella issue they way it is done here - https://github.com/kubernetes/kubernetes/issues/39986

**Comment by perotinus** [comment]
Thanks @madhusudancs! I found #39004, which is quite similar to 1) above, so I think I'll reference it rather than creating a new issue.

**Comment by madhusudancs** [comment]
@perotinus sure. But note the minor distinction between issue #39004 and 1) here. Issue #39004 is more or less for debugging. 1) here is about surfacing progress information/indicator to the user.

**Comment by irfanurrehman** [comment]
@perotinus you can please go ahead and implement 1) here together with https://github.com/kubernetes/kubernetes/issues/39004.
I would try to handle the rest of them excluding 1). I think they all can be handled in one PR.

**Comment by madhusudancs** [comment]
@irfanurrehman I would really prefer small PRs. It is easy to review them, esp. the follow ups.

**Comment by irfanurrehman** [comment]
@madhusudancs, sure, no problem, Will raise separate PRs.

**Comment by irfanurrehman** [comment]
Some notes about 3) - Please let me know ur comments.

**kubefed Init**
The order of creation of objects into the host cluster in case of init:
1 - namespace
2 - service
3 - secrets
4 - ....

An error in creation of any specific object currently just returns with error, leaving objects created before that behind.
If user tries init again, it will fail as it will find the first object (namespace) already present.
On Error, we can do either of the 2 things: 
1 - roll back by deleting the objects in the reverse order, for example if the step after secrets creation fails, delete secrets, then service then lastly namespace
2 - just delete the namespace (which will remove all objects in it)

I think 2 makes simple sense to implement.
On error in this (deleting the namespace), we provide an option to user to try deinit again manually to try clean up again.
The deinit (4) also implements the same thing.


**kubefed join**
The order of steps is
1 - create a secret with cluster credentials
2 - create cluster object into federation api server
3 - create configmap for kube-dns into the registered cluster

if 1 fails, then we through error and tell user to try again
if 2 fails we rollback 1 and exit with error
if 3 fails, we just exit with error


**kubefed unjoin**
The order of steps is
1 - remove cluster object from federation api server
2 - remove the secret from the host cluster
3 - remove configmap

if 1 fails, then we through error and tell user to try again
if either or 2 or 3 fails, we have option only to through error (with leaked secret and/or configmap)

**Comment by madhusudancs** [comment]
> I think 2 makes simple sense to implement.
> On error in this (deleting the namespace), we provide an option to user to try deinit again manually to try clean up again.
> The deinit (4) also implements the same thing.

This makes sense.

If we dynamically provision a PV, we should also delete the disk created for the PV. It's Ok to just delete the namespace in the first version. Disk deletion can come in a later version.

> kubefed join
> ...
> if 3 fails, we just exit with error

I think we should rollback on any error. Rolling back on one type of error and not on another will be both unexpected and surprising to the users. From a user's perspective, neither the order of the operations of the specific operations matter. They either want to have their join completed or not in case of an error. It will not be a nice experience if it is a transient error and they can't just run the command again.

> kubefed unjoin
> The order of steps is
> 1 - remove cluster object from federation api server
> 2 - remove the secret from the host cluster
> 3 - remove configmap

> if 1 fails, then we through error and tell user to try again
> if either or 2 or 3 fails, we have option only to through error (with leaked secret and/or configmap)

Can we do a delete rollback as well? As in, we get the object and delete it, keep a reference to the objects we retrieved before deletion and put them back if the deletion failed? However, note that this is not bullet proof as well. For example, if we run into an error due to temporarily unreachable clusters then it's not just that the deletion fails, the subsequent rollbacks for creating previous objects fail too. But there isn't much we can do about it. It is better to have rollbacks in place for common scenarios at least.

**Comment by madhusudancs** [comment]
In addition to all these rollback mechanisms, we also need validation on user inputs and fail right at the beginning on invalid inputs. We have this problem today. If a user fails to specify a valid cluster name while joining a cluster, we go ahead and create a secret object but give up on cluster creation leaving that cluster's artifacts in a bad state. This could be avoided by having a pre-flight check. Same applies for `kubefed unjoin` as well.

**Comment by madhusudancs** [comment]
> 2 - There is a possibility that the deployed pods of the federation control plane, do not come up successfully, in such a scenario the kubefed init will wait indefinitely. Ideally, there could be a timeout set to override this behavior.

Created a sub-issue to track this - #43123.

**Comment by irfanurrehman** [comment]
\close 
This issue was moved to kubernetes/federation#7

**Comment by irfanurrehman** [comment]
/close
This issue was moved to kubernetes/federation#7
