### ISSUE TITLE
DaemonSets should have infinite toleration for Unreachable/NotReady NoExecute Taints.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#41738]
When writing DaemonSets we decided that they shouldn't be deleted by NodeController in case of Node problems. Now that we're moving to using taints and taint-based evictions (NC will just taint Nodes and the rest will be done by generic taint-eviction mechanism) we need to add infinite toleration for those taints to DaemonSets to keep this behavior.

cc @davidopp @kevin-wangzefeng @aveshagarwal @fgrzadkowski

**Comment by davidopp** [comment]
Off the top of my head, I think the best way to implement this is to modify the [admission controller that adds default tolerationSeconds](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/defaulttolerationseconds/admission.go), to special-case DaemonSet pods and add infinite tolerationSeconds to them. (See definition of [tolerationSeconds](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L2060) field in the API for how to do this.)

@kevin-wangzefeng do you think you can do this? It should be a simple change.

cc/ @kubernetes/sig-apps-bugs @kubernetes/sig-cluster-lifecycle-bugs 

BTW the feature Marek described will be alpha in 1.6, but nobody will be able to use it (without breaking DaemonSet) unless this request is implemented. So the 1.6 milestone tag is appropriate.

**Comment by smarterclayton** [comment]
Why wouldn't the daemon set controller special case that?

**Comment by davidopp** [comment]
Yeah, I guess that's probably better - have the DaemonSet controller create pods with the toleration.

**Comment by kevin-wangzefeng** [comment]
@davidopp I can do this, and yes, in the DaemonSet controller.
