### ISSUE TITLE
Kubelet livenessProbe always fail in Macvlan/Ipvlan network mode

### ISSUE THREAD

**Issue by oilbeater** [kubernetes/kubernetes#41736]
For both Macvlan and Ipvlan network, the kubelet work in host net namespace can not visit net namespace pod due to this two network mode constrain. All network related livenessProbe (http and tcp) will fail.

Even more if the kubedns runs on apiserver node, they cannot visit each other (since apiserver run in host mode and kubedns in a separate net ns) the domain based service discovery will not work.

Possible solutions are creating another network namespace and put kubelet into it or use the created macvlan nic and config it to replace eth0.  They all need lots of config and error prone, is there any straight forward way to solve this problems?

**Comment by hangyan** [comment]
.......
