### ISSUE TITLE
Make timestamp shorting optional

### ISSUE THREAD

**Issue by krallistic** [kubernetes/kubernetes#41741]
Current output (for example kubectl get events) shortenes all timespamps to a more readable format like 1d. 
Sometimes it would be nice to disable these and see the full timestamp. (The current workarround is to use -o=json, and just look at the json). 

- One Solution would be to introduces a flag which just disables the usage of `ShortHumanDuration`. 
- Another solution would be to make the lenght of shorting flexible. Currently everything is shortened to the largest Unit (eg day for >24h, hour for >60min). An option would be to shorten to the largest X units (eg 1d,13h for x=2; 1d,13h,23m for x=3 etc..) and make x=1 as the default value. 

As shortly discussed on slack with @shiywang. @kubernetes/sig-cli-misc

**Comment by jayunit100** [comment]
Why not a generic unix / go  time stamp formatter  option W default as days?

**Comment by shiywang** [comment]
cc @pwittrock @AdoHe

**Comment by fabianofranz** [comment]
@kubernetes/sig-cli-proposals

**Comment by smarterclayton** [comment]
We already have custom columns for this, don't we?  What does the custom column display when you add it?

**Comment by fabianofranz** [comment]
```
$ oc get events -o custom-columns=TIMESTAMP:.lastTimestamp
TIMESTAMP
2017-02-21T20:49:55Z
```

**Comment by fabianofranz** [comment]
Another idea, we could make the "wide" output format (e.g. `$ kubectl get <resource> -o wide`) always print full timestamps.

**Comment by smarterclayton** [comment]
This is somewhat specialized - I'd prefer to just use custom-columns to
solve this.

**Comment by AdoHe** [comment]
```
This is somewhat specialized - I'd prefer to just use custom-columns to
solve this
```
SGTM. I would like we keep current output, shortenes timespamps are more readable, if user really want to get the full timestamp, use custom-columns.
