### ISSUE TITLE
genericapiserver needs a non-cyclical test for openapi

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#41748]
The existing openapi test for genericapiserver had a cycle in it.  We need a simple test for enablement that doesn't introduce a cycle.  https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/genericapiserver_test.go#L91
 
@mbohlool @sttts

**Comment by mbohlool** [comment]
@deads2k Can you be more specific here? Packages are moving around fast. Do you mean dependency on "k8s.io/client-go/pkg/api"?

**Comment by sttts** [comment]
David was referring to this: https://github.com/kubernetes/kubernetes/pull/41650/files#diff-971804afd53f290777083c93e966213dL53. k8s.io/apiserver must not have dependencies on k8s.io/kubernetes.

**Comment by mbohlool** [comment]
I am trying to understand why this code is here. @sttts I see this commit: https://github.com/kubernetes/kubernetes/commit/cca05af615fe6b6701e2426ad6bfc5142124e87e

I don't see where it moved from. Anyway, the fix does not seem to be simple. As far as I can tell the new repo `apiserver` does not have its own code generators and it just copies generated code from main repo. This works for things like deepcopy but does not work for OpenAPI as we have one single file containing all generated types. Solutions are:

1. Copy the huge generated file to this repo
1. make a separate repo for this generated files.
1. Add codegen mechanism to this repo.
1. Remove the test

I am not fond of any of those solutions right now and want to look for a better one. Any ideas?

**Comment by deads2k** [comment]
> does not have its own code generators and it just copies generated code from main repo. This works for things like deepcopy but does not work for OpenAPI as we have one single file containing all generated types. Solutions are:

It does not copy.  Those generators are running in location.



> I am not fond of any of those solutions right now and want to look for a better one. Any ideas?

Can you simply write a very simple handler to prove that when the openapi value is set we serve it?

**Comment by mbohlool** [comment]
> It does not copy. Those generators are running in location.

You mean they are copied to staging and then generators work on staging folder? What we need here is OpenAPI generator working directly on genericapiserver repo (or its copy in staging, etc.).

> Can you simply write a very simple handler to prove that when the openapi value is set we serve it?

OpenAPI registration needs the definition of all models passes to it by routes. Without those, the generation will fail. I should see if it is possible to pass empty routes to it.

**Comment by sttts** [comment]
> You mean they are copied to staging and then generators work on staging folder?

The kube generators are launched from the kube root with staging/ as the output path. Nothing is copied.

**Comment by mbohlool** [comment]
@sttts That is the problem. The generator may include types defined in staging, but all of them would be in one single file in pkg/generated/...
