### ISSUE TITLE
Event 'source' field selector should be 'source.Component'

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#41743]
Field selector for Events is named `source` even though it points to `source.Component`: https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/event/strategy.go#L104

I have no idea if this have any semantic consequences, but certainly is misleading and should be fixed.

cc @lavalamp @smarterclayton @kubernetes/sig-api-machinery-misc

**Comment by deads2k** [comment]
Looks like that one's a couple years old: https://github.com/kubernetes/kubernetes/commit/e3c019128e5666039270b6c42bae8264b43ca925#diff-c409a8da27ded0d7e571cf2d10b0bdcbR112.  I don't think we can just change it.

**Comment by smarterclayton** [comment]
I think this was a backwards compatibility thing that we didn't remember to fix in v1beta3, and carried over into v1 because it was too late, IIRC.

Can make the godoc better.

**Comment by gmarek** [comment]
It's wrong, but we can't fix it.
/close
