### ISSUE TITLE
kubectl cp appending basename twice and throwing error on fully qualified local filepath

### ISSUE THREAD

**Issue by flylo** [kubernetes/kubernetes#41752]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): "cp"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
```➜  midi-ml git:(exploratory_analysis) ✗ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Cloud provider or hardware configuration**: Google Cloud Platform
- **OS** (e.g. from /etc/os-release):

OS in the container:
```
jovyan@jupyter-server-pod-mg45v:~$ cat /etc/os-release                                                                             
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"                                                                                          
NAME="Debian GNU/Linux"                                                                                                            
VERSION_ID="8"                                                                                                                     
VERSION="8 (jessie)"                                                                                                               
ID=debian                                                                                                                          
HOME_URL="http://www.debian.org/"                                                                                                  
SUPPORT_URL="http://www.debian.org/support"                                                                                        
BUG_REPORT_URL="https://bugs.debian.org/"
```
OS on the local machine:
```
➜  midi-ml git:(exploratory_analysis) ✗ system_profiler SPSoftwareDataType

Software:

    System Software Overview:

      System Version: macOS 10.12.1 (16B2657)
      Kernel Version: Darwin 16.1.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
```
- **Kernel** (e.g. `uname -a`): `Darwin Zacharys-MacBook-Pro.local 16.1.0 Darwin Kernel Version 16.1.0: Wed Oct 19 20:31:56 PDT 2016; root:xnu-3789.21.4~4/RELEASE_X86_64 x86_64`
- **Install tools**:
- **Others**:

**What happened**: When I run the following command, the copy works fine:
`$ kubectl cp notebooks jupyter-server-pod-mg45v:/home/jovyan/persistent_data/midi-ml//`

However, when I run the same command, but with a fully qualified local filepath, it throws an error:
`$ kubectl cp /Users/zacharypustejovsky/midi-ml/notebooks/ jupyter-server-pod-mg45v:/home/jovyan/persistent_data/midi-ml//`

`error: stat /Users/zacharypustejovsky/midi-ml/notebooks/notebooks: no such file or directory`

As you can see, it finds the basename and appends it onto the end of the filepath. Note that the directory i'm in is:

```
$ pwd
/Users/zacharypustejovsky/midi-ml
```

So instead of trying to copy `notebooks`, it's copying `notebooks/notebooks` and thus throwing an error.

**What you expected to happen**: I would expect it not to append the basename to the end of the string twice.

**How to reproduce it** (as minimally and precisely as possible): commands above should reproduce it. Run `kubectl cp` with fully qualified local filepath.

**Anything else we need to know**:

**Comment by fraenkel** [comment]
The problem is how you specified the src path with the ending /. The simple solution would be to just remove any dangling /.
