### ISSUE TITLE
Error "TLS handshake error from" while making API request to HTTPS instance

### ISSUE THREAD

**Issue by mansing2** [kubernetes/kubernetes#41769]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): I have already checked.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): Unable to make REST API request.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): NA

**Kubernetes version** (use `kubectl version`):kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"87d9d8d7bc5aa35041a8ddfe3d4b367381112f89", GitTreeState:"clean", BuildDate:"2017-01-23T14:15:25Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"87d9d8d7bc5aa35041a8ddfe3d4b367381112f89", GitTreeState:"clean", BuildDate:"2017-01-23T14:15:25Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release):Centos
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**: We have configured kubernetes on Centos machine and trying to configure HTTPS (secure) instance, we tried running api server with sudo /usr/bin/kube-apiserver --secure-port=8081 --logtostderr=true --v=0 --etcd-servers=http://127.0.0.1:2379  --address=0.0.0.0 --port=8083 --kubelet-port=10250 --allow-privileged=false --service-cluster-ip-range=10.254.0.0/16 --admission-control=SecurityContextDeny --token-auth-file=/tmp/tokens.csv --client-ca-file=/var/run/kubernetes/ca.crt --tls-private-key-file=/var/run/kubernetes/server.key --tls-cert-file=/var/run/kubernetes/server.crt
I dont find any error after running this command but getting an error after running following CURL command.

curl -X POST -H Content-Type:application/json --cacert ca.crt -H "Authorization: Bearer bcdTOKEN1234" -d @"C:\Users\mansings\Desktop\newpod.json" https://52.51.76.237:8081/api/v1

however it works when I pass http://52.51.76.237:8083/api/v1 (insecure URL)

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by cblecker** [comment]
Can you please provide the output of `kubectl version`, as asked by the issue template?

**Comment by mansing2** [comment]
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"87d9d8d7bc5aa35041a8ddfe3d4b367381112f89", GitTreeState:"clean", BuildDate:"2017-01-23T14:15:25Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"87d9d8d7bc5aa35041a8ddfe3d4b367381112f89", GitTreeState:"clean", BuildDate:"2017-01-23T14:15:25Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by mansing2** [comment]
@cblecker - Do let me know if any more information is needed.

**Comment by ravilr** [comment]
@mansing2 upgrade your curl client and pass --tlsv1.2 option. kube-apiserver only accepts tls-1.2 clients

**Comment by xiangpengzhao** [comment]
@mansing2 do you try what @ravilr commented? I think that answered your question. Can we close this issue?

/sig auth
/cc @thockin
