### ISSUE TITLE
flake: podautoscaler unit test failing

### ISSUE THREAD

**Issue by sjenning** [kubernetes/kubernetes#41768]
Just a few:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41149/pull-kubernetes-unit/18979/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41077/pull-kubernetes-unit/18972/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41714/pull-kubernetes-unit/18970/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/34259/pull-kubernetes-unit/18968/

Many more:
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-unit

Couldn't recreate locally.

**Comment by kargakis** [comment]
k8s.io/kubernetes/pkg/controller/podautoscaler TestScaleUpCMUnreadyLessScale
```
/usr/local/go/src/runtime/panic.go:500 +0x1ae
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/mutation_detector.go:133 +0x54a
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/mutation_detector.go:84 +0x51
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/mutation_detector.go:92 +0x57
```
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41282/pull-kubernetes-unit/19037/#k8siokubernetespkgcontrollerpodautoscaler-testscaleupcmunreadylessscale

**Comment by kargakis** [comment]
Bumping the priority - since yesterday this has been flaking frequently

**Comment by kargakis** [comment]
@piosz @DirectXMan12 not sure if there is a sig and/or Github team for the autoscaler

**Comment by wojtek-t** [comment]
@jszczepkowski @mwielgus

**Comment by wojtek-t** [comment]
@deads2k @smarterclayton - it seems that detector discovered some issue

**Comment by wojtek-t** [comment]
@ncdc

**Comment by ncdc** [comment]
I was on PTO yesterday so I'll be catching up on emails and then I'll look
at this asap. Back online in 1.5 hours.

**Comment by ncdc** [comment]
I'm looking at this now

**Comment by wojtek-t** [comment]
@ncdc - the question I have is - since your PRs enabling it are still not merged, why this is failing? [btw - thanks for looking into it]

**Comment by ncdc** [comment]
@wojtek-t the unit tests run with the cache mutation detector enabled, and have for a while. My PRs are to enable it for e2e tests.

I think this is stemming from https://github.com/kubernetes/kubernetes/pull/41272, which merged yesterday. I think @deads2k or @liggitt mentioned that conversions can mutate the source object?

**Comment by wojtek-t** [comment]
@ncdc - ok thanks for explanation, that makes perfect sense

**Comment by ncdc** [comment]
Yeah this definitely looks like it's from 41272, since it's calling `api.Scheme.UnsafeConvertToVersion`, which doesn't guarantee to be a deep copy.

**Comment by ncdc** [comment]
Reassigning to @DirectXMan12 to fix

**Comment by DirectXMan12** [comment]
whoops, yeah, the conversion mutates things, so we need to call convert to version first.
