### ISSUE TITLE
Regression in all Kubemark tests

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#41776]
There seems to be a regression in all kubemark tests (occasional failure in 5-node tests) starting yesterday night (at around 12:00 Jenkins time).This is blocking the submit queue.

cc @k8s-oncall @wojtek-t @gmarek

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/41774

describes the reason and is the fix

**Comment by shyamjvs** [comment]
Thanks for pointing to it. Will close this issue once the PR is merged.

**Comment by wojtek-t** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/41774
