### ISSUE TITLE
Automatic pod expiration not working

### ISSUE THREAD

**Issue by felixbuenemann** [kubernetes/kubernetes#41787]
According to the docs on [Pod Lifetime](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-lifetime) pods in phase "Succeeded" or "Failed" should be expired by the master:

> In general, Pods do not disappear until someone destroys them. This might be a human or a controller. The only exception to this rule is that **Pods with a phase of Succeeded or Failed for more than some duration (determined by the master) will expire and be automatically destroyed**.

However in reality on K8s v1.4.x (tested up to v1.4.9) completed or erred pods never get removed.

In fact completed one-off pods (`restartPolicy: Never`) from builds of our PaaS running on K8s (Deis Workflow) kept filling up the nodes disks until they ran out of disk space. Only after manually deleting the completed pods, the associated containers were deleted, causing container GC to free disk space.

The above docs also don't have any links to where a pod expiration policy would be configured.

So either the docs on this subject are wrong or Kubernetes is not working as described.

**Comment by smarterclayton** [comment]
The limit is really high by default for pod GC:

```
// Package podgc contains a very simple pod "garbage collector" implementation,
// PodGCController, that runs in the controller manager. If the number of pods
// in terminated phases (right now either Failed or Succeeded) surpasses a
// configurable threshold, the controller will delete pods in terminated state
// until the system reaches the allowed threshold again. The PodGCController
// prioritizes pods to delete by sorting by creation timestamp and deleting the
// oldest objects first. The PodGCController will not delete non-terminated
// pods.
```

**Comment by smarterclayton** [comment]
I think it's 10k pods.

**Comment by felixbuenemann** [comment]
Is there existing documentation how to tune this value?

**Comment by smarterclayton** [comment]
```
$ kube-controller-manager --help
...
      --terminated-pod-gc-threshold int32                                 Number of terminated pods that can exist before the terminated pod garbage collector starts deleting terminated pods. If <= 0, the terminated pod garbage collector is disabled. (default 12500)
```

Might be in the docs.

**Comment by felixbuenemann** [comment]
Thanks @smarterclayton, I'll consult the docs and either close this issue or turn it into a documentation issue.

**Comment by kamarajuPrathi** [comment]
@felixbuenemann did you figure out was that the issue with docs or the did you come to know the configuration for this ?

**Comment by felixbuenemann** [comment]
Read the comment by smarterclayton, it lists the right option.
