### ISSUE TITLE
Solidify UnavailableReplicas field for Deployments

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#41789]
https://github.com/kubernetes/kubernetes/blob/1cb737fb970a65be2b3ff21cbf00196359b56cd3/pkg/apis/extensions/types.go#L323-L325
```go
// Total number of unavailable pods targeted by this deployment.
// +optional
UnavailableReplicas int32
```
This is assuming we count unavailable pods from all **created** pods targeted by a Deployment.
In the controller, we calculate unavailable replicas based on spec.replicas which also includes pods that haven't been created.
https://github.com/kubernetes/kubernetes/blob/1cb737fb970a65be2b3ff21cbf00196359b56cd3/pkg/controller/deployment/sync.go#L594-L595
We either need to fix the controller to use status.replicas instead of spec.replicas and in both cases update the godoc to explain better the intent of the field.
@kubernetes/sig-apps-api-reviews

**Comment by kargakis** [comment]
Punting for 1.7 but I think this is just a api doc change. UnavailableReplicas is fine for meaning the unavailable replicas that either werent created or are simply not available yet, we just need to make this clearer in the api comment.

**Comment by janetkuo** [comment]
Punting for 1.8

**Comment by wanghaoran1988** [comment]
I am volunteered to take this if nobody start working on this

**Comment by kargakis** [comment]
@wanghaoran1988 this is only a doc update - I am going to update the API comments during the 1.8 timeframe.

**Comment by wanghaoran1988** [comment]
@kargakis Cool, thanks for clarification.
