### ISSUE TITLE
Automating federation upgrade tests

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/kubernetes#41791]
This issue is to track all the tasks related to upgrade tests and framework for federation as described in [Kubernetes federation upgrade tests](https://docs.google.com/document/d/1QJg-8I3Ff3ClqLXRHpWXhe4BRaDcdRiuDPPbPHEomsw/edit?usp=sharing)

- [x] Framework for federation upgrade tests
- [ ] CI jobs for federation upgrade
- Individual test cases
  - [ ] Federated Service: @shashidharatd 
  - [ ] Federated ReplicaSets: @madhusudancs 
  - [ ] Federated Deployments: @madhusudancs 
  - [ ] Federated Ingress: @csbell 
  - [x] Federated ConfigMaps: @marun 
  - [x] Federated Secrets: @marun 
  - [x] Federated Daemonsets: @marun

**Comment by shashidharatd** [comment]
cc @madhusudancs @nikhiljindal @kubernetes/sig-federation-pr-reviews

**Comment by madhusudancs** [comment]
@shashidharatd I have added all the API types too. In the community meeting tomorrow let's ask people for help and sign up interested people for individual API types.

cc @csbell

**Comment by marun** [comment]
I think the bulk of this work will be done as part of the controller refactor, since the code to support integration testing can be reused by the upgrade test.  This is already true for the simple types (configmaps, secrets, daemonset) and should also be true for the workload types (replicaset, deployment, jobs) once their refactor is complete.

**Comment by nikhiljindal** [comment]
This was discussed at the previous sig meeting.
@shashidharatd Can you update the status of adding ci jobs for running continuous upgrade testing.

**Comment by quinton-hoole** [comment]
Required for GA of federation.  Prioritized accordingly.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#104.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
