### ISSUE TITLE
Ability to Mount a Persistent Volume as a Raw Device

### ISSUE THREAD

**Issue by raffaelespazzoli** [kubernetes/kubernetes#41792]
This is a request for improvement.

Currently kubernetes will format a volume if it finds it's not formatted and always mount it as a branch of the file system.
There is some software that works better with raw devices, such as Oracle RAC for example.
This request is about allowing kubernetes to mount raw devices. Volumes that would support this should be:

- emptyDir
- persistentVolume whose backing storage is a block device, such as rbd

**Comment by raffaelespazzoli** [comment]
@kubernetes/sig-storage-misc

**Comment by gnufied** [comment]
This looks very much like https://github.com/kubernetes/kubernetes/issues/38606

**Comment by erinboyd** [comment]
I will be added the PR proposal later today for this function. I will link to this PR when I have the number

**Comment by tengqm** [comment]
looks like this issue has been solved although there could be further actions to added more backends for block devices.
