### ISSUE TITLE
NPD doesn't write its logs to file in kubemark

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#41802]
The npd in hollow-nodes doesn't write its logs to a file despite having its command as:

```
"/node-problem-detector",
.....other params....,
"1>>/var/log/npd-$(NODE_NAME).log 2>&1"
```

in hollow-node_template.json. I tried changing it to the following:

```
"/bin/sh",
"-c",
"/node-problem-detector ...params...  (both with and without --logtostderr) 1>>/var/log/npd-$(NODE_NAME).log 2>&1"     (here the logfile is created but nothing is written to it)
```

and that makes the container enter crashloop, without providing any way to access logs (I tried looking into /var/log/npd-$(NODE_NAME).log, tried kubectl logs, tried docker logs on the node and also kubectl describe pod, but none of them could give me any useful logs).

@Random-Liu Any idea how to make npd write to log file in hollow node / why it is failing?

cc @kubernetes/sig-scalability-misc @wojtek-t @gmarek

**Comment by gmarek** [comment]
It probably uses normal glog logic, which is putting log files into `/tmp/<name>.INFO` file.

**Comment by shyamjvs** [comment]
Yes, that's true. I checked that the log file does exist in /tmp, which is where stdout gets redirected to. However I have 2 issues:
- Adding --alsologtostderr and then redirecting stderr by `2>>/var/logs/npd_$(NODE_NAME).log`, seems to let npd start successfully but for some reason the file doesn't get created
- Doing exactly the above, but by running it using `/bin/sh -c /node-problem-detector ....` does create the file (it remains empty though) but the container goes into a crashloop.

Does anyone know how to get around this problem?

**Comment by Random-Liu** [comment]
Running the following command works fine for me:
```
docker run -it -v /var/log:/var/log --entrypoint="sh" gcr.io/google_containers/node-problem-detector:v0.3.0-alpha.0 -c "/node-problem-detector --kernel-monitor=/config/kernel-monitor.json --apiserver-override=http://localhost?inClusterConfig=false --alsologtostderr 1>>/var/log/npd.log 2>&1"
```

1) What npd version are you using?
2) You may want to use `tee` to make sure that the output is also printed so that docker log will still work.

**Comment by shyamjvs** [comment]
The version is the same as above. Discussed offline about this and seems like the problem is with some special character inside the apiserver-override flag. It's fixed by quoting the flag's value. Thanks for helping figure this out @Random-Liu :)

**Comment by Random-Liu** [comment]
> The version is the same as above. Discussed offline about this and seems like the problem is with some special character inside the apiserver-override flag. It's fixed by quoting the flag's value. Thanks for helping figure this out @Random-Liu :)

Np~ Thanks for the fix.
