### ISSUE TITLE
Addon-manager's using released kubectl binary is causing problems

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#41817]
Lately we are getting more problems regarding the released kubectl in addon-manager. The addon-manager may be broken when:
- Deprecating fields in k8s API (#35782, #41587).
- Adding new fields to k8s API and using it on addons (#40382, #38957).

It becomes less meaningful to continuously bumping up addon-manager just because of the older kubectl binary does not support the feature we added ([CHANGELOG](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/CHANGELOG.md)), which already happened couple times in a short period. It also blocked PRs that changed both API and addons with confusing symptoms, which has negative impacts on development velocity.

I deem addon-manager will eventually get rid of kubectl binary and use API client library instead. But if that isn't happen soon enough, one interim solution might be mounting the latest kubectl binary into it to avoid the incompatible issues. (And it would also be a good indicator for the latest kubectl's healthiness.)

Open this issue for discussion :)

@mikedanese @kubernetes/sig-cluster-lifecycle-bugs

**Comment by mikedanese** [comment]
Why are both your examples not validation errors? Does kubectl apply use server side strategic merge patch yet?

**Comment by MrHohn** [comment]
Check the logs a bit and we did hit validation error in the second case:

In the first case: https://github.com/kubernetes/kubernetes/pull/41587#issue-208221299
```
INFO: == Entering periodical apply loop at 2017-02-16T17:33:37+0000 ==
error: error pruning namespaced object extensions/v1beta1, Kind=HorizontalPodAutoscaler: the server could not find the requested resource
WRN: == Failed to execute /usr/local/bin/kubectl  apply --namespace=kube-system -f /etc/kubernetes/addons     --prune=true -l kubernetes.io/cluster-service=true --recursive >/dev/null at 2017-02-16T17:33:38+0000. 2 tries remaining. ==
error: error pruning namespaced object extensions/v1beta1, Kind=HorizontalPodAutoscaler: the server could not find the requested resource
WRN: == Failed to execute /usr/local/bin/kubectl  apply --namespace=kube-system -f /etc/kubernetes/addons     --prune=true -l kubernetes.io/cluster-service=true --recursive >/dev/null at 2017-02-16T17:33:46+0000. 1 tries remaining. ==
error: error pruning namespaced object extensions/v1beta1, Kind=HorizontalPodAutoscaler: the server could not find the requested resource
WRN: == Failed to execute /usr/local/bin/kubectl  apply --namespace=kube-system -f /etc/kubernetes/addons     --prune=true -l kubernetes.io/cluster-service=true --recursive >/dev/null at 2017-02-16T17:33:53+0000. 0 tries remaining. ==
WRN: == Kubernetes addon update completed with errors at 2017-02-16T17:33:58+0000 ==
```

In the second case: https://github.com/kubernetes/kubernetes/pull/38957#issuecomment-281175270:
```
...
for: "/etc/kubernetes/addons/cluster-monitoring/influxdb/heapster-controller.yaml": unable to find api field in struct PodSpec for the json field "tolerations"
error when applying patch:
...
```

Spoke with @mengqiy, got the answer that: For apply, validation will happen once on the client side with the compiled in types. Then server side strategic merge will happen, after which the server side validation will kick in again.

**Comment by MrHohn** [comment]
Labeling sig as bot asked. Free feel to re-label it.

/sig cluster-lifecycle

**Comment by mengqiy** [comment]
To clarify it.
In 1.7 and earlier verion, Kubectl does validation using swagger schema which is returned by the server.
But `apply` need some metadata (mergeKey and patchStrategy) that swagger doesn't provide, so it lookup in baked-in types. This will cause the version skew issue sometimes.
We plan to move to use OpenAPI in 1.8. With OpenAPI, kubectl no longer relies on baked-in types.

**Comment by xmik** [comment]
I've found that we should use:
  * addon-manager v6.1 with k8s v1.5 ([source](https://github.com/kubernetes/kubernetes/issues/43755#issuecomment-289840535))
  * addon-manager v6.4-beta.1 or v6.4-beta.2 with k8s v1.6 ([addon-manager changelog](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/CHANGELOG.md))

I use k8s v1.6.6. When using  addon-manager v6.4-beta.1 or addon-manager v6.4-beta.2, the log messages of addon-manager contain:
```
INFO: == Kubernetes addon reconcile completed at 2017-07-04T12:03:29+0000 ==
error: no objects passed to apply
INFO: == Reconciling with addon-manager label ==
INFO: == Kubernetes addon ensure completed at 2017-07-04T12:03:27+0000 ==
INFO: == Reconciling with deprecated label ==
error: no objects passed to create
INFO: == Kubernetes addon reconcile completed at 2017-07-04T12:02:30+0000 ==
```
When using  addon-manager v6.4, the log messages of addon-manager contain:
```
WRN: == Kubernetes addon update completed with errors at 2017-07-04T12:45:01+0000 ==
error: error pruning namespaced object extensions/v1beta1, Kind=HorizontalPodAutoscaler: the server could not find the requested resource
WRN: == Failed to execute /usr/local/bin/kubectl apply --namespace=kube-system -f /etc/kubernetes/addons --prune=true -l kubernetes.io/cluster-service=true --recursive >/dev/null at 2017-07-04T12:44:56+0000. 0 tries remaining. ==
WRN: == Failed to execute /usr/local/bin/kubectl apply --namespace=kube-system -f /etc/kubernetes/addons --prune=true -l kubernetes.io/cluster-service=true --recursive >/dev/null at 2017-07-04T12:44:50+0000. 1 tries remaining. ==
error: error pruning namespaced object extensions/v1beta1, Kind=HorizontalPodAutoscaler: the server could not find the requested resource
error: error pruning namespaced object extensions/v1beta1, Kind=HorizontalPodAutoscaler: the server could not find the requested resource
WRN: == Failed to execute /usr/local/bin/kubectl apply --namespace=kube-system -f /etc/kubernetes/addons --prune=true -l kubernetes.io/cluster-service=true --recursive >/dev/null at 2017-07-04T12:44:44+0000. 2 tries remaining. ==
INFO: == Entering periodical apply loop at 2017-07-04T12:44:43+0000 ==
```

**Comment by MrHohn** [comment]
@xmik Below error is benign, feel free to ignore:
```
error: no objects passed to apply
```
Could you clarify the addon-manager version for the second type of error you posted? From the changelog doesn't seem like `addon-manager v6.4` is released yet.

**Comment by xmik** [comment]
@MrHohn thanks for noticing that. I thought `addon-manager v6.4` is the latest, even though there is no changelog entry for it. But on google docker registry: https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/kube-addon-manager-amd64 it's written that it was uploaded 1 Feb 2017.

My mistake that I thought `addon-manager v6.4` is the latest, since I've been also using it previously with `k8s v1.5.3`. The only log messages from `addon-manager v6.4` and `k8s v1.5.3` were like:
```
INFO: == Kubernetes addon update completed successfully at 2017-06-13T22:54:18+0000 ==
```

**Comment by MrHohn** [comment]
> My mistake that I thought addon-manager v6.4 is the latest

Sorry for the confusion, it seems like someone (probably me) mistakenly pushed the v6.4 image. Let me check if we could delete that to avoid misleading more users.
