### ISSUE TITLE
make test-cmd failing locally with permission error for dockershim

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#41834]
I am running `make test-cmd` locally which is failing with the following error:

```
error: failed to run Kubelet: failed to create kubelet: failed to listen on "/var/run/dockershim.sock": listen unix /var/run/dockershim.sock: bind: permission denied
```

Is this expected?
Is there a way to change that path?

cc @yujuhong @kubernetes/sig-node-bugs

**Comment by yujuhong** [comment]
`hack/make-rules/test-cmd.sh` starts kubelet as a normal user, which doesn't have the permission to create the socket in `/var/run/dockershim.sock`. I think we can create a new kubelet flag to pass this path. 

/cc @Random-Liu @dchen1107

**Comment by dchen1107** [comment]
From test-cmd.sh at https://github.com/kubernetes/kubernetes/blob/master/hack/make-rules/test-cmd.sh#L17

"# This command checks that the built commands can function together for simple scenarios.  It does not require Docker."

In this case, can we update this not require dockershim.sock? 

On another hand, why test-cmd requires a working Kubelet which does nothing today?

**Comment by nikhiljindal** [comment]
Yes kubectl tests should not really require kubelet. I think it should be fine to remove it if the tests pass without it.
cc @kubernetes/sig-cli-misc who own this I think.

**Comment by yujuhong** [comment]
> Yes kubectl tests should not really require kubelet. I think it should be fine to remove it if the tests pass without it.
> cc @kubernetes/sig-cli-misc who own this I think.

See #41843. It passed locally for me.
