### ISSUE TITLE
[CRI] Some container security context fields can be misleading

### ISSUE THREAD

**Issue by sameo** [kubernetes/kubernetes#41848]
When creating a container through CRI, one can define a complete security context for it. According to the [kubernetes security context documentation](https://kubernetes.io/docs/user-guide/security-context/), the container security context can override the pod one.

By exposing host namespaces settings and privileged flags at the container security context level, we could end up creating container with more host privileges than the ones defined at the pod level.

Should we remove some of the container security context settings to avoid misconfiguring them ?
I think at least the privileged and host namespaces ones should be removed and containers should follow the pod security context for those.

**Comment by sameo** [comment]
cc @yujuhong @runcom @mrunalp

**Comment by liggitt** [comment]
It is intentional that one container can be more privileged than another and that the most specific configuration between the pod and container overrides.

**Comment by sameo** [comment]
@liggitt Allowing different privileges between containers make sense, but it seems to me that containers having higher privileges than the pod they're running in is contradiction with the definition of pods.

**Comment by liggitt** [comment]
The pod's security context is the default the containers get unless they specify something different. The pod level one is not a limiter, but a default to avoid having to specify it multiple times if you want the same options across all containers.

**Comment by sameo** [comment]
@liggitt So you're saying it would be ok to run a container with e.g. host networking namespace access (something that could e.g. mess with the host IP tables) while the pod explicitly set host networking namespace access to `false` ?
I'm candidly asking btw, I thought that by definition the pod isolation and privilege level was a sandbox all containers within that pod could not get out of.

**Comment by liggitt** [comment]
I'm referring to the fields in the kube api that expose settings both at the pod and container level.

**Comment by yujuhong** [comment]
@sameo my previous explanation about CRI to you on slack was not entirely accurate (sorry, bad memory)
See https://github.com/kubernetes/kubernetes/pull/34811#issuecomment-257740741 for how security context is handled in CRI. Basically, kubelet will interprets the security contexts set in the k8s API, and sets the proper fields in each container's security context via CRI. I agree that this is a bit misleading because (network) namespace options are applied per-pod, even though we explicitly set it for each container. 
/cc @feiskyer @timstclair 

As for the k8s API, it doesn't include namespace options, but do allow individual containers to be more privileged than the default pod security context.

**Comment by liggitt** [comment]
flattening the options to a single per-container set of options in CRI seems reasonable to me. the dual-level options in the API are partly for convenience, partly for compatibility as security context evolved

**Comment by sameo** [comment]
@yujuhong Ok, so do we agree about the fact that some pod security context fields should never be overridden by container ones and that right now the CRI allows to do that in some cases (e.g. host networking) ? In which case we should reduce the security context overlap to just the settings containers are allowed to overlap.

**Comment by yujuhong** [comment]
> @yujuhong Ok, so do we agree about the fact that some pod security context fields should never be overridden by container ones and that right now the CRI allows to do that in some cases (e.g. host networking) ? In which case we should reduce the security context overlap to just the settings containers are allowed to overlap.

Yes, that's the first item (1) in https://github.com/kubernetes/kubernetes/pull/34811#issuecomment-257740741
@feiskyer, I remembered you convinced me that folding (1) into (3) would complicate the API, but I think we should revisit this.

**Comment by feiskyer** [comment]
> Ok, so do we agree about the fact that some pod security context fields should never be overridden by container ones and that right now the CRI allows to do that in some cases (e.g. host networking) 

I think CRI is consistent with kubernetes's API in this context. The difference is users should consider the overlap logic in kubernetes API, but CRI doesn't:

> // LinuxSandboxSecurityContext holds linux security configuration that will be
> // applied to a sandbox. Note that:
> // 1) It does not apply to containers in the pods.
> // 2) It may not be applicable to a PodSandbox which does not contain any running
> //    process.

> be ok to run a container with e.g. host networking namespace access (something that could e.g. mess with the host IP tables) while the pod explicitly set host networking namespace access to false

@sameo I don't think this is true.

* In kubernetes API, HostNetwork can be only set in PodSpec, you can't set container to be in HostNetwork while Pod is not. 
* In CRI, although there is Namespace options in both LinuxContainerSecurityContext and LinuxSandboxSecurityContext, they are set always same in kuberuntime.

**Comment by sameo** [comment]
@feiskyer 

> @sameo I don't think this is true.
> *   In kubernetes API, HostNetwork can be only set in PodSpec, you can't set container to be in HostNetwork while Pod is not.

And that makes perfect sense to me.

>  *  In CRI, although there is Namespace options in both LinuxContainerSecurityContext and LinuxSandboxSecurityContext, they are set always same in kuberuntime.

To me, the fact that kuberuntime always set them to be the same shows that `LinuxContainerSecurityContext` is redundant and not needed. From a CRI server implementation perspective, we have to make the implicit assumption that they will always be identical. Simply removing it from the container request would make it explicit.

**Comment by feiskyer** [comment]
> To me, the fact that kuberuntime always set them to be the same shows that LinuxContainerSecurityContext is redundant and not needed. 

Hmm, sorry for the misleading. I didn't mean LinuxContainerSecurityContext is always same with LinuxSandboxSecurityContext, I mean their `HostNetwork` fields are always same. Other fields could be different.
