### ISSUE TITLE
HA master setup suddenly shifted to heavy CPU load on a single master

### ISSUE THREAD

**Issue by jaygorrell** [kubernetes/kubernetes#41853]
**Kubernetes version** (use `kubectl version`):
1.4.6

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Kops Debian Jessie
- **Kernel** (e.g. `uname -a`): 4.4.26-k8s #1 SMP Fri Oct 21 05:21:13 UTC 2016 x86_64 GNU/Linux
- **Install tools**: Kops

**What happened**:
After months of running a 3-master Kops HA setup, one of the masters seemed to take an increased load on the CPU. At the same time, another node had a proportional decrease.

![screenshot 2017-02-21 15 21 00](https://cloud.githubusercontent.com/assets/12174604/23191235/97244806-f86a-11e6-9346-3d763377d89d.png)

Skimming the logs, it did seem that kube-apiserver was much more noisy on the node with heavier CPU load -- in fact, the others were handling some information for daemonsets like Datadog, but none of my actual services (30+).

I checked the pods and nothing was overloaded on that instance -- after trying to individually delete each `kube-system` pod, I tried terminating each master individually. Once it all settled, the problem appeared to persist.

![screenshot 2017-02-21 17 27 42](https://cloud.githubusercontent.com/assets/12174604/23191281/d43b4212-f86a-11e6-969c-ddd2bcb4b303.png)

Since the CPU isn't capped at 100%, I figured I could just scale out of this for now. So I bumped the masters from m4.large to m4.xlarge and things are about half (percent-wise) of the screenshots above, which is what you'd expect. So in terms of pegging the CPU, I'm in the clear but the usage is still much higher than it was for the past 6 months.

**What you expected to happen**:
Load on the masters should not end up in a 80/15/5 distribution, especially suddenly with an unknown cause.

**How to reproduce it** (as minimally and precisely as possible):
Not a clue :(

**Anything else we need to know**:
This cluster has been running for 6 months and gets regular updates, though no updates happened today. In fact, no real changes aside from standard deployments that happen many times per day were going on when this happened.

I have a total of 4 environments but this is the only one to have the problem. The others are already on m4.xlarge masters though.

@justinsb opened kubernetes/kops/issues/1965 in case that's an issue but I doubt that is what's going on here since the first graph shows things were more distributed before the unknown event happened.

**Comment by zhangxiaoyu-zidif** [comment]
1.6.9 
+1
