### ISSUE TITLE
Opaque Integers not rescheduling

### ISSUE THREAD

**Issue by RenaudWasTaken** [kubernetes/kubernetes#41861]
**Is this a request for help?** No

**What keywords did you search in Kubernetes issues before filing this one?** :
- opaque Integer

---
**TLDR**:
Opaque integers do not have the same behaviors as others resources (CPU, ...) when they become available again.

When a pod (which asks for an Opaque Integer) gets scheduled and the resources is not available, it's status ends up in OutOfpod instead of pending. 
Meaning that the scheduler won't try to reschedule it when the resource becomes available

**What happened**:
 ```bash
$ echo '[{"op": "add", "path": "/status/capacity/pod.alpha.kubernetes.io~1opaque-int-resource-bananas", "value": "2"}]' | \
> http PATCH http://localhost:8080/api/v1/nodes/localhost.localdomain/status \
> Content-Type:application/json-patch+json
```

_Note: Pod specs are at the end of the issue_

```bash
$ ./cluster/kubectl.sh create -f ./double-banana.yml
$ ./cluster/kubectl.sh get pods
NAME                READY     STATUS    RESTARTS   AGE
double-banana-pod   1/1       Running   0          3s

$ ./cluster/kubectl.sh create -f ./single-banana.yml
$ ./cluster/kubectl.sh get pods
NAME                READY     STATUS    RESTARTS   AGE
double-banana-pod   1/1       Running                                                    0          23s
single-banana-pod   0/1       OutOfpod.alpha.kubernetes.io/opaque-int-resource-bananas   0          3s

$ ./cluster/kubectl.sh delete -f ./double-banana.yml
$ ./cluster/kubectl.sh get pods
NAME                READY     STATUS                                                     RESTARTS   AGE
single-banana-pod   0/1       OutOfpod.alpha.kubernetes.io/opaque-int-resource-bananas   0          21s
```

**What you expected to happen**:

```bash
$ ./cluster/kubectl.sh create -f ./double-banana.yml
$ ./cluster/kubectl.sh get pods
NAME                READY     STATUS    RESTARTS   AGE
double-banana-pod   1/1       Running   0          3s

$ ./cluster/kubectl.sh create -f ./single-banana.yml
$ ./cluster/kubectl.sh get pods
NAME                READY     STATUS    RESTARTS   AGE
double-banana-pod   1/1       Running                                                    0          23s
single-banana-pod   0/1       Pending   0          3s

$ ./cluster/kubectl.sh delete -f ./double-banana.yml
$ ./cluster/kubectl.sh get pods
NAME                READY     STATUS                                                     RESTARTS   AGE
single-banana-pod   1/1       Running   0          21s
```
---
**Pod Exemple**:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: single-banana-pod
spec:
  containers:
  - image: nginx
    name: single-banana-ctr

    resources:
      requests:
        pod.alpha.kubernetes.io/opaque-int-resource-bananas: 1
```
---
**Environment and version**:

```bash
$ cluster/kubectl.sh version
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.1.335+a564506f7c0fd0", GitCommit:"a564506f7c0fd0693870221a3b811be36461c057", GitTreeState:"clean", BuildDate:"2017-02-16T01:01:50Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.1.335+a564506f7c0fd0", GitCommit:"a564506f7c0fd0693870221a3b811be36461c057", GitTreeState:"clean", BuildDate:"2017-02-16T01:01:50Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

$ cat /etc/os-release                                                                                                                                        NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
UBUNTU_CODENAME=xenial

$ uname -a                                                                                                                                                   
Linux 4.4.0-62-generic #83-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
```
Ran from `./hack/local-up-cluster.sh`

Ping @ConnorDoyle :smile:

**Comment by ConnorDoyle** [comment]
Reproduced this with current master, but unable to reproduce with v1.5.0.

First step, attempting to follow up with a failing e2e test case to trigger the failure. At first look it appears that the existing e2es were insufficient to prevent this regression.

**Comment by kargakis** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by ConnorDoyle** [comment]
Just an update from ongoing investigation -- there seem to be at least two suspicious behaviors at play here.

1. Pods that consume more than the available amount of OIR are wrongly bound by the scheduler.
1. Pods that consume more than the available amount of OIR are (rightly) rejected by Kubelet but (wongly?) end up in the PodFailed phase.

Unsure if (2) above is new behavior or to be expected. It could be that fixing (1) will get us back to the way things worked circa v1.5.

**Comment by ConnorDoyle** [comment]
Current theory is that this broke in PR #36693. Working to get the bugfix accepted in time for 1.6. See #41870.

**Comment by timothysc** [comment]
It's a bug fix so we can accept for a little while.

**Comment by smart2003** [comment]
Is that possible to add the opaque int resource from the worker node? I typed the following command on a worker node. The node was patched, but the opaque int resource is not there.
$ kubectl patch node worker1 --type='json' -p='[{"op": "add", "path": "/status/capacity/pod.alpha.kubernetes.io~1network", "value": "1000"}]'

$ "worker1" patched

$ kubectl get node worker1 -o json | jq .status.capacity
{
  "alpha.kubernetes.io/nvidia-gpu": "0",
  "cpu": "4",
  "memory": "8175036Ki",
  "pods": "110"
}

**Comment by ConnorDoyle** [comment]
@smart2003 there are a couple of patch strategies the kubectl/api support. The one that works in our testing is `application/json-patch+json` (as in the curl command in the issue description here). If that doesn't work for you, would you mind submitting a new issue to track it? This one is closed.

**Comment by smart2003** [comment]
curl command works for me as well. I used this method to add the
opaque-int-resource on the master node. It works well. However, I did not
set it up successfully with the curl command on the worker nodes because of
the security check. The worker needs the authentication such as the
auth-token to access the api-server running on master. Would you mind
telling me how to add the opaque-int-resource via curl on the worker node?
I tried the following one, but did not work. Thanks.

curl --header "Content-Type:application/json-patch+json" \
        --request PATCH \
        --data '[{"op": "add", "path": "/status/capacity/
pod.alpha.kubernetes.io~1network", "value": "1000"}]' \
        http://masterIP:8080/api/v1/nodes/workerIP/status

Regards,
Cong

2017-04-07 17:47 GMT-05:00 Connor Doyle <notifications@github.com>:

**Comment by xiangpengzhao** [comment]
@smart2003 It seems that you missed prefix `opaque-int-resource-` in your command:)

@ConnorDoyle I create a new issue. #44269
