### ISSUE TITLE
Introduce golint into verify tool chain

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#41868]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bugs

**Kubernetes version** (use `kubectl version`):
master

**What happened**:
There's several doc, code style improvement PR recently; it'll be better if we can improve it at the original PR. golint will help to give some advise on comments; so suggest to add it into verify tool chain.

For example, the following is the output of golint for `plugin/pkg/scheduler`:

```
$golint plugin/pkg/scheduler/
plugin/pkg/scheduler/scheduler.go:43:6: exported type PodConditionUpdater should have comment or be unexported
plugin/pkg/scheduler/scheduler.go:53:1: exported method Scheduler.StopEverything should have comment or be unexported
plugin/pkg/scheduler/scheduler.go:57:1: comment on exported type Configurator should be of the form "Configurator ..." (with optional leading article)
plugin/pkg/scheduler/scheduler.go:83:1: comment on exported type Config should be of the form "Config ..." (with optional leading article)
plugin/pkg/scheduler/scheduler.go:143:1: receiver name s should be consistent with previous receiver name sched for Scheduler
plugin/pkg/scheduler/scheduler.go:147:1: receiver name s should be consistent with previous receiver name sched for Scheduler
```

**Comment by cblecker** [comment]
@k82cn --
There is already a golint step to the verify chain, however, packages need to be added to `hack/.linted_packages` to go through that step. I opened #42087 to add `plugin/pkg/scheduler` to it, and correct it's lint errors.

**Comment by k82cn** [comment]
Great, thanks very much :).
