### ISSUE TITLE
Add federation update script to update-all.sh

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#41866]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug

**Kubernetes version** (use `kubectl version`):
master

**What happened**:
The federation doc is not updated accordingly.

**What you expected to happen**:
After running update-all.sh, all doc & generated codes are updates, e.g. https://github.com/kubernetes/kubernetes/pull/41812

**Comment by soltysh** [comment]
@k82cn can you be more specific, which part is missing. We have https://github.com/kubernetes/kubernetes/pull/42068 to address the issue you referenced. Please double check if that addressed your problem, if not provide more concrete information about what's missing.

**Comment by k82cn** [comment]
@soltysh , after `./hack/update-all.sh -a`, I run the following commands for #41770 to generated all required docs.

```
./hack/update-federation-openapi-spec.sh
./hack/update-federation-api-reference-docs.sh
./hack/update-federation-generated-swagger-docs.sh
./hack/update-federation-swagger-spec.sh
```

**Comment by soltysh** [comment]
Looking into [hack/update-all.sh](https://github.com/kubernetes/kubernetes/blob/197bd532a2d6d2fa1c505f0a5c0c3dfd8fdf8d52/hack/update-all.sh#L63) update-federation-openapi-spec.sh is already there. If you add those we need to have accompanying verify-* scripts which will be properly invoked during every PR check.

**Comment by k82cn** [comment]
`./hack/update-federation-swagger-spec.sh` seems not included. Regarding verify-*, open a issue in test-infra?

**Comment by soltysh** [comment]
Nope, it has to be all part of main repo.

**Comment by nikhiljindal** [comment]
I also ran into this while working on https://github.com/kubernetes/kubernetes/pull/45600.

Looks like the following 3 scripts are missing:
verify-federation-api-reference-docs.sh, verify-federation-generated-swagger-docs.sh and verify-federation-swagger-spec.sh.

Sent https://github.com/kubernetes/kubernetes/pull/45694 for adding verify-federation-swagger-spec.sh

cc @mbohlool

**Comment by nikhiljindal** [comment]
Updated that PR to add all the 3 missing verify scripts: https://github.com/kubernetes/kubernetes/pull/45694

**Comment by k82cn** [comment]
@nikhiljindal , great, thanks very much .
