### ISSUE TITLE
Kube-proxy fails to run automcatically on new worker node upon adding to the existing kubernetes cluster

### ISSUE THREAD

**Issue by sugun999** [kubernetes/kubernetes#41871]
Hi,

I have setup kubernetes on coreOS by following this doc and everything is working OK.

https://coreos.com/kubernetes/docs/latest/getting-started.html

After few days, I am trying to add new worker node to the existing cluster as per this doc https://coreos.com/kubernetes/docs/latest/deploy-workers.html

New server is added to the cluster and I am able to see this new node when I run "kubectl get nodes"

But noticed that kube-proxy is not running on this new node eventhough the kube-proxy.yaml file is present at directory /etc/kubernetes/manifests/ and due to that, on deploying the pod to this node, it is unable to communicate with other pods/containers running on already existing worker nodes.

I do see below error in kubelet logs continuously. But "systemctl status docker" shows that docker is running.

E0215 15:12:57.491851 1338 container_manager_linux.go:625] error opening pid file /run/docker/libcontainerd/docker-containerd.pid: open /run/docker/libcontainerd/docker-containerd.pid: no such file or directory

Any ideas, why kube-proxy pod is not running on this new worker node?

**Comment by sugun999** [comment]
Hi,

Anyone has any comments/update on this?

**Comment by vaijab** [comment]
I have seen this happening on v1.5.3. In fact, this is the issue where kubelet does not pick up manifest files once it has started. Sounds like #40331

**Comment by dcbw** [comment]
@sugun999 is this issue a dupe of #40331?

**Comment by kargakis** [comment]
/sig node since it seems duplicate of another node issue
