### ISSUE TITLE
Possible Bug: `kubectl get --export` for singular item omits `namespace`

### ISSUE THREAD

**Issue by c-knowles** [kubernetes/kubernetes#41880]
When exporting using a command of the form `kubectl get <resourceType> <resourceName> -o yaml --namespace=<namespace> --export` the `namespace` is included in the export when `resourceName` is omitted but it is missing when specifying `resourceName`.

Similar to several of the `--export` items such as  https://github.com/kubernetes/kubernetes/issues/28551 and those inside https://github.com/kubernetes/kubernetes/issues/38768. However, I could not find a direct report of this particular issue. Perhaps some overlap with https://github.com/kubernetes/kubernetes/issues/33767 but not sure.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
✗ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-17T20:49:14Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3+coreos.0", GitCommit:"8fc95b64d0fe1608d0f6c788eaad2c004f31e7b7", GitTreeState:"clean", BuildDate:"2017-02-15T19:52:15Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Mac OS, Sierra

**What happened**:

When exporting using a command of the form `kubectl get <resourceType> <resourceName> -o yaml --namespace=<namespace> --export` the `namespace` is included in the export when `resourceName` is omitted but it is missing when specifying `resourceName`.

**What you expected to happen**:

`namespace` should be included in the export even when specifying a `resourceName`.

**How to reproduce it** (as minimally and precisely as possible):

As an example here is this performed in the `kube-system` namespace for deployments and the `kube-dns` deployment, however the same problem occurs for at least services and ingresses plus for all namespaces.

```
✗ kubectl get deployment -o yaml --namespace=kube-system --export | grep namespace   
    namespace: kube-system
    selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/heapster-v1.2.0
                fieldPath: metadata.namespace
    namespace: kube-system
    selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/kube-dns
    namespace: kube-system
    selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/kube-dns-autoscaler
          - --namespace=kube-system

✗ kubectl get deployment kube-dns -o yaml --namespace=kube-system --export | grep namespace
  selfLink: /apis/extensions/v1beta1/namespaces//deployments/kube-dns
```

**Comment by smarterclayton** [comment]
In general, export should always omit namespace.

**Comment by smarterclayton** [comment]
Heh, List doesn't implement export.  That's why.  Export should work on resource lists, but it doesn't.

**Comment by smarterclayton** [comment]
Will fix this as part of server side GET.

**Comment by c-knowles** [comment]
Oh that's why! I didn't realise export doesn't work on lists. The reason I thought it was working is the command is accepted whereas other invalid CLI options are rejected.

Regarding omitting namespaces, I'm using the resulting YAML files to import into a different cluster and need the services to go into the corresponding namespaces. However, I can just update the scripts to store namespace somewhere separately.

**Comment by tony612** [comment]
@smarterclayton  Why not include namespace in the exported result?

**Comment by discordianfish** [comment]
Just ran into this issue. I think get should at least fail with --export on lists until this is supported.

**Comment by liggitt** [comment]
tracking this in the original "finish implementing export" issue - https://github.com/kubernetes/kubernetes/issues/24855

/close
