### ISSUE TITLE
[Cache mutation] panic: cache *v1.HorizontalPodAutoscaler modified

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#41883]
from: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/41486/pull-kubernetes-e2e-gce/19271/artifacts/e2e-gce-agent-pr-34-0-master/kube-controller-manager.log

```
CACHE *v1.HorizontalPodAutoscaler[5] ALTERED!
{"metadata":{"name":"rc-light","namespace":"e2e-tests-horizontal-pod-autoscaling-d6bj7","selfLink":"/apis/autoscaling/v1/namespaces/e2e-tests-horizontal-pod-autoscaling-d6bj7/horizontalpodautoscalers/rc-light","uid":"2d5246ad-f8ea-11e6-9ed7-42010af00002","resourceVersion":"5419","creationTimestamp":"2017-02-22T10:32:14Z"

A: },"spec":{"scaleTargetRef":{"kind":"replicationController","name":"rc-light"},"minReplicas":1,"maxReplicas":2,"targetCPUUtilizationPercentage":50},"status":{"lastScaleTime":"2017-02-22T10:33:16Z","currentReplicas":2,"desiredReplicas":1,"currentCPUUtilizationPercentage":10}}

B: ,"annotations":{"autoscaling.alpha.kubernetes.io/current-metrics":"[{\"type\":\"Resource\",\"resource\":{\"name\":\"cpu\",\"currentAverageUtilization\":10,\"currentAverageValue\":\"20m\"}}]"}},"spec":{"scaleTargetRef":{"kind":"replicationController","name":"rc-light"},"minReplicas":1,"maxReplicas":2,"targetCPUUtilizationPercentage":50},"status":{"lastScaleTime":"2017-02-22T10:33:16Z","currentReplicas":2,"desiredReplicas":1,"currentCPUUtilizationPercentage":10}}


CACHE *v1.HorizontalPodAutoscaler[6] ALTERED!
{"metadata":{"name":"rc-light","namespace":"e2e-tests-horizontal-pod-autoscaling-d6bj7","selfLink":"/apis/autoscaling/v1/namespaces/e2e-tests-horizontal-pod-autoscaling-d6bj7/horizontalpodautoscalers/rc-light","uid":"2d5246ad-f8ea-11e6-9ed7-42010af00002","resourceVersion":"5426","creationTimestamp":"2017-02-22T10:32:14Z"

A: },"spec":{"scaleTargetRef":{"kind":"replicationController","name":"rc-light"},"minReplicas":1,"maxReplicas":2,"targetCPUUtilizationPercentage":50},"status":{"lastScaleTime":"2017-02-22T10:33:16Z","currentReplicas":2,"desiredReplicas":2,"currentCPUUtilizationPercentage":10}}

B: ,"annotations":{"autoscaling.alpha.kubernetes.io/current-metrics":"[{\"type\":\"Resource\",\"resource\":{\"name\":\"cpu\",\"currentAverageUtilization\":10,\"currentAverageValue\":\"20m\"}}]"}},"spec":{"scaleTargetRef":{"kind":"replicationController","name":"rc-light"},"minReplicas":1,"maxReplicas":2,"targetCPUUtilizationPercentage":50},"status":{"lastScaleTime":"2017-02-22T10:33:16Z","currentReplicas":2,"desiredReplicas":2,"currentCPUUtilizationPercentage":10}}


panic: cache *v1.HorizontalPodAutoscaler modified

```

@ncdc @DirectXMan12 
@wojtek-t @gmarek Got one!
@lavalamp mutation detection, someday you'll thank me :)

**Comment by wojtek-t** [comment]
@jszczepkowski @mwielgus

**Comment by ncdc** [comment]
@deads2k yeah, that should be fixed by #41816 which was merged a few minutes ago

**Comment by ncdc** [comment]
I think this is probably safe to close now

**Comment by deads2k** [comment]
Looks like this conversion: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/autoscaling/v1/conversion.go#L138 will mutate the original object in incompatible ways when called down an unsafe conversion path.

@smarterclayton is unsafe the default now?

**Comment by deads2k** [comment]
> I think this is probably safe to close now

I may no longer be a queue blocker, but the conversion is still quite dangerous.

**Comment by ncdc** [comment]
I thought Solly put in the deep copy?

**Comment by deads2k** [comment]
> I thought Solly put in the deep copy?

Not in the conversion itself (which he can't really do).

**Comment by ncdc** [comment]
@deads2k @smarterclayton said yesterday that if you want to ensure conversion doesn't mutate the original object, you have to call `ConvertToVersion`. Do you still foresee an issue?

**Comment by deads2k** [comment]
> @deads2k @smarterclayton said yesterday that if you want to ensure conversion doesn't mutate the original object, you have to call ConvertToVersion. Do you still foresee an issue?

It's unexpected to delete the annotations off the original object.  I'm not sure what I think will break.

**Comment by ncdc** [comment]
It's deleting from `out`, not `in`. What am I missing?

**Comment by deads2k** [comment]
> It's deleting from out, not in. What am I missing?

Annotation is a shallow copy in a "normal" conversion case.  People would normally expect two subsequent calls to conversion (with no mutation on their part) to create the same object twice.  However, this code will not.  The second converted object will be different.

I think that result is very unexpected and I don't think people will be careful to only call conversion once and not lose their converted object.

@liggitt something new to worry about.

**Comment by ncdc** [comment]
@deads2k @smarterclayton said `ConvertToVersion` does a deep copy first.

**Comment by smarterclayton** [comment]
This is fixed now?

**Comment by ncdc** [comment]
I think so but I'll let David chime in too

**Comment by deads2k** [comment]
> This is fixed now?

yes
