### ISSUE TITLE
replace gets conflict error from watch cache

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#41892]
I0222 06:34:25.223] node "node-v1-test" created
W0222 06:34:25.446] Error from server (Conflict): error when replacing "STDIN": Operation cannot be fulfilled on nodes "node-v1-test": the object has been modified; please apply your changes to the latest version and try again
W0222 06:34:25.453] !!! [0222 06:34:25] Call tree:
W0222 06:34:25.455] !!! [0222 06:34:25]  1: /go/src/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh:2853 run_pod_tests(...)
W0222 06:34:25.458] !!! [0222 06:34:25]  2: hack/make-rules/test-cmd.sh:142 runTests(...)
I0222 06:34:25.759] +++ [0222 06:34:25] Clean up complete

@kubernetes/sig-cli-api-reviews

**Comment by deads2k** [comment]
Found in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-unit/19373/ on submit queue.

**Comment by ncdc** [comment]
I've seen this multiple times as well. It is coming from here: https://github.com/kubernetes/kubernetes/blob/7a8c46768841679f1a500691fda84be85bc3a9b5/hack/make-rules/test-cmd-util.sh#L669-L678

**Comment by ncdc** [comment]
I'm not sure what the expectation is with this particular part of the test suite. It creates a node, then immediately tries to run `kubectl replace` on it. Should it always succeed, regardless of conflict?

**Comment by smarterclayton** [comment]
kubectl replace is effectively a "stomp" (all PUTs are stomps from the perspective of the user).  I don't think as a user I expect kubectl replace to fail on conflict up to some reasonable retry limit.

**Comment by ncdc** [comment]
I think this might be happening because the `kubectl replace` call is fighting with the attach/detach reconciler, which is doing a two way merge patch to update the node's status. I'm continuing to investigate.

**Comment by pwittrock** [comment]
@ncdc Assigning to you since you are investigating.

**Comment by pwittrock** [comment]
cc @ymqytw

**Comment by ncdc** [comment]
I've yet to reproduce this locally but I think my analysis is probably correct. `kubectl replace` does not currently retry on conflict. Do we think it should? cc @kubernetes/sig-cli-bugs @fabianofranz @soltysh @deads2k  @liggitt

**Comment by deads2k** [comment]
> kubectl replace does not currently retry on conflict. Do we think it should?

If you want an unconditional update (retry on conflict), then I think you want something different.  Why don't we just create something different to replace on?

**Comment by liggitt** [comment]
from a client's perspective, that *is* an unconditional replace, which is what makes surfacing that error really odd...

**Comment by ncdc** [comment]
There is `--force` but that does a delete followed by a create

**Comment by ncdc** [comment]
@liggitt I'm not clear on the code path that results in the conflict error surfacing. I tried looking at the rest code that handles updates but it wasn't the easiest to follow.

**Comment by ncdc** [comment]
Yeah, that's where I was looking. I am confused about what happens w.r.t. resource version for the updated object (the one supplied to `kubectl replace`) if the input doesn't contain a resource version.

**Comment by liggitt** [comment]
@wojtek-t I think this is the issue:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher.go#L518-L535

The caching storage implements guaranteedupdate and operates on the version retrieved from the watch cache

**Comment by deads2k** [comment]
> The caching storage implements guaranteedupdate and uses the object in the watch cache as the current object

I think I'd expect it to do that, but on a conflict failure, I'd expect it to retry live.  Seems like most of the time, the cache would save us a get.

**Comment by pwittrock** [comment]
@deads2k Can I mark this as non-release-blocker to reduce to noise for the release managers?

**Comment by ncdc** [comment]
@pwittrock I'd say yes

**Comment by pwittrock** [comment]
@ncdc thanks

**Comment by ncdc** [comment]
@liggitt @deads2k @wojtek-t would this work? https://gist.github.com/ncdc/97e2ae9c7d9a8d4d718c8382daf38775

**Comment by wojtek-t** [comment]
Actually, this looks reasonable to me.
I did: https://github.com/kubernetes/kubernetes/pull/42729 that is pretty much solving exactly the same issue, but I think what you're suggesting looks better to me.

**Comment by liggitt** [comment]
this could fix replace, but not patch. the tryUpdate closure in patch captures state, so re-invoking GuaranteedUpdate wouldn't solve anything

**Comment by ncdc** [comment]
Maybe we need a combination of the two approaches?

**Comment by liggitt** [comment]
Maybe. I'm also trying to reason through what this would do in create cases (AlreadyExists errors) and CreateOnUpdate cases

**Comment by wojtek-t** [comment]
Yes - regarding patch, it's a good point. I initially though that second GuaranteedUpdate will "drop the state", but that's not true. So we probably need something like my PR.

> cache contains an object that has actually been deleted

In that case, the correct thing to do is to fail the update. And any update will fail at the etcd level anyway, right?

**Comment by liggitt** [comment]
>> cache contains an object that has actually been deleted
>
> In that case, the correct thing to do is to fail the update. And any update will fail at the etcd level anyway, right?

Update calls that make use of AllowCreateOnUpdate would behave oddly

**Comment by wojtek-t** [comment]
@liggitt - why? This should work correctly. I mean, in GuaranteedUpdate itself, the first loop will wait at etcd level (because the original state will have out-of-date RV), but in the second loop we will have correct "empty" state of object, and it should just work, right?

**Comment by marun** [comment]
This issue is likely related to a recent failure: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/3796/

**Comment by ncdc** [comment]
Potential fix #43152

**Comment by ncdc** [comment]
At least for the replace issue

**Comment by liggitt** [comment]
after further investigation, this doesn't affect unconditional replace

kubectl turns unconditional replaces into conditional ones by pre-fetching the existing object and filling in a resource version. given that behavior of kubectl, the test script is vulnerable to legitimate version conflicts.

however, the watch cache issue also exposes clients to illegitimate version conflicts (a client that updated, then updated again with the RV returned from the first update should not see a conflict, but they do)

**Comment by liggitt** [comment]
reopening to track server-side issue, moving to 1.6.1

**Comment by liggitt** [comment]
still seen in kubectl test in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/43489/pull-kubernetes-unit/23566/
