### ISSUE TITLE
[k8s.io] Kubectl client [k8s.io] Kubectl describe should check if kubectl describe prints relevant information for rc and pods [Conformance]

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#41898]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41821/pull-kubernetes-e2e-gce-gci/18767/

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:797
Feb 22 06:52:17.446: Failed to find 1 current in Replicas:	0 current / 1 desired
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:1567
```

replica set controller maybe?

@kargakis

**Comment by kargakis** [comment]
The rc seems to be updated almost a second after the failure.
```
I0222 14:50:52.836267       5 replication_controller_utils.go:58] Updating replica count for rc: e2e-tests-kubectl-rn8mn/redis-master, replicas 0->1 (need 1), fullyLabeledReplicas 0->1, readyReplicas 0->1, availableReplicas 0->1, sequence No: 1->1
```
Maybe the test needs to retry
https://github.com/kubernetes/kubernetes/blob/2e1271116023d6b98bc8187a642665884387e3b3/test/e2e/kubectl.go#L748

**Comment by kargakis** [comment]
And the real log for the failure is
```
I0222 06:52:14.729] Feb 22 06:50:52.027: INFO: Failed to find 1 current in Replicas:	0 current / 1 desired
```

**Comment by fejta** [comment]
/assign @pwittrock 

`Kubectl describe should check if kubectl describe prints relevant information for rc and pods` flakes PRs at least once a day

The [triage tool](http://go.k8s.io/triage) can filter down to focus on a single test:
* https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=should%20check%20if%20kubectl%20describe%20prints%20relevant%20information%20for%20rc%20and%20pods

**Comment by pwittrock** [comment]
@monopole For when you have some time.

**Comment by spxtr** [comment]
[And again](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/44048/pull-kubernetes-e2e-gce-gci/25492/)

**Comment by pwittrock** [comment]
@ymqytw Reassign to you

**Comment by ymqytw** [comment]
Output of `kubectl describe` has been change in 1.6. That's why upgrade tests are failing.
But I'm not sure why it is not failing 100% from the triage board. @fejta Do you know why?
Output of 1.5 or earlier:
```
mengqiy@mengqiy:~/work$ ./kubectl describe rc samename 
Name:		samename
Namespace:	default
Image(s):	nginx     <=============== this line changed
Selector:	name=test-rc
Labels:		name=test-rc
Replicas:	5 current / 5 desired
Pods Status:	5 Running / 0 Waiting / 0 Succeeded / 0 Failed
No volumes.
Events:
  ...
```

Output in 1.6 or later:
```
Name:		samename
Namespace:	default
Selector:	name=test-rc
Labels:		name=test-rc
Annotations:	<none>
Replicas:	5 current / 5 desired
Pods Status:	5 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:	name=test-rc
  Containers:
   test-rc:
    Image:		nginx   <==========  image moved into pod template
    Port:		
    Environment:	<none>
    Mounts:		<none>
  Volumes:		<none>
Events:
  ...
```

**Comment by ymqytw** [comment]
> The rc seems to be updated almost a second after the failure.

The timeout is [5 minutes](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L105) now. Is it reasonable to give it a little more time? @kargakis

**Comment by kargakis** [comment]
That timeout waits for the pods to run based on the API server. The rc controller is using its own cache so it may lag a bit before it actually updates the rc status. The test needs to retry for some time if the output we get back from describe does not match.

**Comment by kargakis** [comment]
In other word, `checkOutput` should also have its own retries.

**Comment by mengqiy** [comment]
SGTM. Going to send a fix today.

**Comment by fejta** [comment]
FYI, this test continues to flake PRs at least once per day: https://groups.google.com/d/msg/kubernetes-sig-cli/DN56n_qvxrc/TeGbrMz1DgAJ

**Comment by kargakis** [comment]
@fejta should it show up in http://storage.googleapis.com/kubernetes-test-history/static/index.html?

**Comment by kargakis** [comment]
Hm, this seems to fail in the upgrade tests. @mengqiy this failure seems to be related to an image name change as you already pointed out before. Mind finding what changed the test to use that image and fix the image name?
```
I0414 10:19:21.583] Apr 14 10:19:21.582: INFO: stdout: "Name:\t\tredis-master-rmsmk\nNamespace:\te2e-tests-kubectl-5kfds\nNode:\t\tbootstrap-e2e-minion-group-k3r4/10.240.0.4\nStart Time:\tFri, 14 Apr 2017 10:19:19 -0700\nLabels:\t\tapp=redis\n\t\trole=master\nAnnotations:\tkubernetes.io/created-by={\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationController\",\"namespace\":\"e2e-tests-kubectl-5kfds\",\"name\":\"redis-master\",\"uid\":\"7e6bd7ca-2136-11...\nStatus:\t\tRunning\nIP:\t\t10.180.4.12\nControllers:\tReplicationController/redis-master\nContainers:\n  redis-master:\n    Container ID:\tdocker://922b845b0fa91142cbcd0a91f9a0c960c4e09e7b9edb2e19939c0c4cc3344a64\n    Image:\t\tgcr.io/google_containers/redis:e2e\n    Image ID:\t\tdocker://sha256:e5e67996c442f903cda78dd983ea6e94bb4e542950fd2eba666b44cbd303df42\n    Port:\t\t6379/TCP\n    State:\t\tRunning\n      Started:\t\tFri, 14 Apr 2017 10:19:20 -0700\n    Ready:\t\tTrue\n    Restart Count:\t0\n    Environment:\t<none>\n    Mounts:\n      /var/run/secrets/kubernetes.io/serviceaccount from default-token-g5qk7 (ro)\nConditions:\n  Type\t\tStatus\n  Initialized \tTrue \n  Ready \tTrue \n  PodScheduled \tTrue \nVolumes:\n  default-token-g5qk7:\n    Type:\tSecret (a volume populated by a Secret)\n    SecretName:\tdefault-token-g5qk7\n    Optional:\tfalse\nQoS Class:\tBestEffort\nNode-Selectors:\t<none>\nTolerations:\tnode.alpha.kubernetes.io/notReady=:Exists:NoExecute for 300s\n\t\tnode.alpha.kubernetes.io/unreachable=:Exists:NoExecute for 300s\nEvents:\n  FirstSeen\tLastSeen\tCount\tFrom\t\t\t\t\t\tSubObjectPath\t\t\tType\t\tReason\t\tMessage\n  ---------\t--------\t-----\t----\t\t\t\t\t\t-------------\t\t\t--------\t------\t\t-------\n  2s\t\t2s\t\t1\tdefault-scheduler\t\t\t\t\t\t\t\tNormal\t\tScheduled\tSuccessfully assigned redis-master-rmsmk to bootstrap-e2e-minion-group-k3r4\n  2s\t\t2s\t\t1\tkubelet, bootstrap-e2e-minion-group-k3r4\tspec.containers{redis-master}\tNormal\t\tPulled\t\tContainer image \"gcr.io/google_containers/redis:e2e\" already present on machine\n  2s\t\t2s\t\t1\tkubelet, bootstrap-e2e-minion-group-k3r4\tspec.containers{redis-master}\tNormal\t\tCreated\t\tCreated container with id 922b845b0fa91142cbcd0a91f9a0c960c4e09e7b9edb2e19939c0c4cc3344a64\n  1s\t\t1s\t\t1\tkubelet, bootstrap-e2e-minion-group-k3r4\tspec.containers{redis-master}\tNormal\t\tStarted\t\tStarted container with id 922b845b0fa91142cbcd0a91f9a0c960c4e09e7b9edb2e19939c0c4cc3344a64\n"
I0414 10:19:21.583] Apr 14 10:19:21.582: INFO: Running '/workspace/kubernetes_skew/cluster/kubectl.sh --server=https://35.184.67.5 --kubeconfig=/workspace/.kube/config describe rc redis-master --namespace=e2e-tests-kubectl-5kfds'
I0414 10:19:21.779] Apr 14 10:19:21.779: INFO: stderr: ""
I0414 10:19:21.779] Apr 14 10:19:21.779: INFO: stdout: "Name:\t\tredis-master\nNamespace:\te2e-tests-kubectl-5kfds\nSelector:\tapp=redis,role=master\nLabels:\t\tapp=redis\n\t\trole=master\nAnnotations:\t<none>\nReplicas:\t1 current / 1 desired\nPods Status:\t1 Running / 0 Waiting / 0 Succeeded / 0 Failed\nPod Template:\n  Labels:\tapp=redis\n\t\trole=master\n  Containers:\n   redis-master:\n    Image:\t\tgcr.io/google_containers/redis:e2e\n    Port:\t\t6379/TCP\n    Environment:\t<none>\n    Mounts:\t\t<none>\n  Volumes:\t\t<none>\nEvents:\n  FirstSeen\tLastSeen\tCount\tFrom\t\t\tSubObjectPath\tType\t\tReason\t\t\tMessage\n  ---------\t--------\t-----\t----\t\t\t-------------\t--------\t------\t\t\t-------\n  2s\t\t2s\t\t1\treplication-controller\t\t\tNormal\t\tSuccessfulCreate\tCreated pod: redis-master-rmsmk\n"
I0414 10:19:21.780] Apr 14 10:19:21.779: INFO: Failed to find Image(s): in Name:		redis-master
I0414 10:19:21.780] Namespace:	e2e-tests-kubectl-5kfds
I0414 10:19:21.780] Selector:	app=redis,role=master
I0414 10:19:21.780] Labels:		app=redis
I0414 10:19:21.780] 		role=master
I0414 10:19:21.780] Annotations:	<none>
I0414 10:19:21.780] Replicas:	1 current / 1 desired
I0414 10:19:21.780] Pods Status:	1 Running / 0 Waiting / 0 Succeeded / 0 Failed
I0414 10:19:21.780] Pod Template:
I0414 10:19:21.780]   Labels:	app=redis
I0414 10:19:21.781] 		role=master
I0414 10:19:21.781]   Containers:
I0414 10:19:21.781]    redis-master:
I0414 10:19:21.781]     Image:		gcr.io/google_containers/redis:e2e
I0414 10:19:21.781]     Port:		6379/TCP
I0414 10:19:21.781]     Environment:	<none>
I0414 10:19:21.781]     Mounts:		<none>
I0414 10:19:21.781]   Volumes:		<none>
I0414 10:19:21.781] Events:
I0414 10:19:21.781]   FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
I0414 10:19:21.782]   ---------	--------	-----	----			-------------	--------	------			-------
I0414 10:19:21.782]   2s		2s		1	replication-controller			Normal		SuccessfulCreate	Created pod: redis-master-rmsmk
I0414 10:19:21.782] 
```

**Comment by mengqiy** [comment]
It is actually the key name has been changed in the key-value pair, not the value.

As I pointed out in https://github.com/kubernetes/kubernetes/issues/41898#issuecomment-294063237:
before expected key:
```
Image(s):
```
now expected key:
```
Image:
```

**Comment by kargakis** [comment]
Hm, this is unfortunate. These kubectl tests should really be unit tests.

**Comment by fejta** [comment]
@kargakis the 24 hr test history is largely focused on failures right now, and this is highlighting flakes specifically (aka which tests are both passing and failing at the same commit the most often).

Please follow the reports I'm sending to kubernetes-dev and related sigs. Also you can generate this info yourself using [test-infra/experiment/bigquery](https://github.com/kubernetes/test-infra/tree/master/experiment/bigquery)

PS: also try out http://go.k8s.io/triage for finding failures (I'm sending out a separate email highlighting the biggest sources of failure).

PPS: we are in the process of creating infrastructure to automate creating these reports, but automation never works as well as a fellow human asking for attention.

**Comment by mengqiy** [comment]
We still need to patch the release-1.4 and release-1.5 branch to make the upgrade tests passing.
I will send PRs later this week.

**Comment by kargakis** [comment]
We didn't fix https://github.com/kubernetes/kubernetes/issues/41898#issuecomment-294260542

**Comment by mengqiy** [comment]
The change mentioned in https://github.com/kubernetes/kubernetes/issues/41898#issuecomment-294260542 was introduced in 1.6.
The change covers describer and kubectl e2e test.
After discussing with @pwittrock, we think we are not going to backport the changes to 1.4 and 1.5, instead we are going to skip the tests in version skew cases.

**Comment by kargakis** [comment]
@fejta https://github.com/kubernetes/kubernetes/pull/44688 should fix this issue

**Comment by fejta** [comment]
@mengqiy @kargakis looks like the PR is resolved, should we close?

**Comment by mengqiy** [comment]
Please wait until fix to be cherrypick into 1.4.

**Comment by fejta** [comment]
Which PR is this?

**Comment by mengqiy** [comment]
Is there a easy way to cherrypick https://github.com/kubernetes/kubernetes/pull/44688 to 1.4?

**Comment by pwittrock** [comment]
@mengqiy no you need to create a new PR with the target branch of 1.4

**Comment by fejta** [comment]
Ready to close?

**Comment by mengqiy** [comment]
Yup.
/close
