### ISSUE TITLE
[k8s.io] Deployment deployment should support rollback 1m30s

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#41891]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41650/pull-kubernetes-e2e-gce/19306/

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:82
Expected error:
    <*errors.errorString | 0xc420ac3f40>: {
        s: "error waiting for deployment \"test-rollback-deployment\" (got 6 / gcr.io/google_containers/redis:e2e) and new replica set \"test-rollback-deployment-3992250386\" (got 6 / gcr.io/google_containers/redis:e2e) revision and image to match expectation (expected 4 / gcr.io/google_containers/redis:e2e): Deployment \"test-rollback-deployment\" doesn't have the required revision set",
    }
    error waiting for deployment "test-rollback-deployment" (got 6 / gcr.io/google_containers/redis:e2e) and new replica set "test-rollback-deployment-3992250386" (got 6 / gcr.io/google_containers/redis:e2e) revision and image to match expectation (expected 4 / gcr.io/google_containers/redis:e2e): Deployment "test-rollback-deployment" doesn't have the required revision set
not to have occurred
```

@kargakis

**Comment by kargakis** [comment]
@deads2k is this flaking consistently in the merge queue?

**Comment by deads2k** [comment]
> @deads2k is this flaking consistently in the merge queue?

I've seen it (or something else from the deployment controller) several times in the past 24 hours.

**Comment by kargakis** [comment]
Any ideas why nothing deployment-related shows up in http://storage.googleapis.com/kubernetes-test-history/static/index.html?

cc: @kubernetes/test-infra-maintainers

**Comment by kargakis** [comment]
@kubernetes/sig-apps-test-failures

**Comment by spxtr** [comment]
> Any ideas why nothing deployment-related shows up in http://storage.googleapis.com/kubernetes-test-history/static/index.html?

That only shows merge-blocking flakes. Click on one of the jobs to see what tests run in it, such as http://storage.googleapis.com/kubernetes-test-history/static/suite-ci-kubernetes-e2e-gce-flaky.html

**Comment by kargakis** [comment]
Btw there is already an open issue about this test
https://github.com/kubernetes/kubernetes/issues/36703
I would love if the bot would start posting back to the issues again every time a failure occured.

**Comment by kargakis** [comment]
Closing in favor of #36703
