### ISSUE TITLE
Feature: Add number of containers as a resource

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#41895]
Kubernetes supports limiting the number of pods across a node and across the entire system.
However, a single pod can be comprised of an unlimited number of containers. 
The resources at the node level are proportional to containers and not to pods.
Many runtimes are built to run containers and so their resource consumption is tied to containers.
In addition to runtime resource consumption, each container also occupies kernel memory which is currently not isolated.
To further improve isolation at the node level, it will be helpful to limit the total number of containers per node similar to the number of pods. The scheduler will have to respect that limitation.
To prevent abuse, it might be useful to introduce quota for number of containers per namespace too.

cc @kubernetes/sig-node-proposals @kubernetes/sig-scheduling-proposals

**Comment by ConnorDoyle** [comment]
A container can also have an arbitrary number of processes, which maps more closely to the kmem argument. As the next level of granularity would you consider using e.g. ulimit to cap the number of processes per pod/container? If so, does the container limit also make sense to introduce?

**Comment by timothysc** [comment]
ug..

/cc @davidopp @bsalamat

**Comment by davidopp** [comment]
I remember we talked about doing this in Borg but decided it would be very hard to do it with a reasonable user experience. I don't remember why, though. It may have had to do something with the admission/feasibility decision around adding a container to an existing pod (which we don't currently support in Kubernetes, and may never, but should at least be considered, e.g. #37838). 

Maybe @bgrant0607 remembers.

**Comment by bgrant0607** [comment]
@davidopp The reasons this was hard in Borg do not apply to K8s. K8s doesn't support recursive scheduling.

**Comment by vishh** [comment]
@ConnorDoyle let's keep pid cgroups out of this issue. It's debatable whether we should expose pids as a numerical user consumable resource.
I'd like to just tackle containers in this issue.

**Comment by davidopp** [comment]
> K8s doesn't support recursive scheduling.

I know, but I don't remember why it is hard even with recursive scheduling. It seems just like any other resource requirement you'd need to consider.

**Comment by bsalamat** [comment]
Pods have resource limits, if we are concerned about resource usage of containers that are not accounted when resource limits are enforced, wouldn't it be easier if those overheads are reported back to the master and accounted as the resources used by the containers?
For example:
Container's memory usage 1GB.
Runtime memory usage 100GB.
Estimated kernel memory usage 1MB. (This can be an average, fixed number extracted from empirical data.)
Total: 1101MB. This is the actual memory usage, not just 1GB. We can use this total to find the memory usage of a pod and enforce limits.

I am not so sure about making scheduler container-aware. Changing the granularity of scheduling and resource accounting has the risk of introduction of significant complexity.

**Comment by ConnorDoyle** [comment]
@vishh could you explain the impact of not having this feature? Have you seen failures that would have been avoided?

**Comment by vishh** [comment]
@bsalamat it's a bit more complicated.

For example, users might reserve compute resources for their container runtime based on the number of pods that the node is expected to support multiplied by an average number of containers per pod (~2 typically). 
If a few pods land on a node containing 10+ container's each, the resource budget for the runtime would no longer be sufficient.
So in addition to resource consumption per container on the kernel, there is also user space cost per container.
BTW usage from the nodes is not available to the scheduler yet in k8s. 

@ConnorDoyle As of now k8s isn't fully multi-tenant compatible and users are expected to be wary of the workloads they run. This issue is a step towards making k8s multi-tenant safe.

**Comment by davidopp** [comment]
@vishh I didn't fully understand your response to @bsalamat's suggestion. If the extra resources required are linear in the number of containers or pods, it should work for the user to just incorporate them into the scheduling request, right?

BTW after a brief discussion with @bgrant0607 and some Borg folks, we figured out that the reason this was never implemented in Borg. In any event, the key is that if we want "containers as a node-level resource," then for future-proofing purposes we need to figure out what will the user experience be if they want to add containers to a pod (like #37838) but doing so would exceed the max containers per node. To make it usable, we may need to add "max number of containers that will ever live in this Pod" to the PodSpec. At the very least, there should be a pod-level resource for number of containers, to make it analogous to every other resource.

**Comment by vishh** [comment]
@davidopp

> @vishh I didn't fully understand your response to @bsalamat's suggestion. If the extra resources required are linear in the number of containers or pods, it should work for the user to just incorporate them into the scheduling request, right?

The issues is the resources reserved for system daemons are typically static and so unless we let them be unrestricted we cannot let them consume the "extra" container overhead that a user of system automatically adds to a pod's resource requirements.

 > In any event, the key is that if we want "containers as a node-level resource,"

Yeah. That's the main goal of this issue. 

> then for future-proofing purposes we need to figure out what will the user experience be if they want to add containers to a pod

This is useful to consider as well. Addition of containers will have to meet quota as well as existing node level limits (unless creation of a new pod is an option).

**Comment by timothysc** [comment]
Let's enqueue this for discussion at the next SIG meeting.

**Comment by resouer** [comment]
@timothysc Any update to follow up here since next discussion? Do we want this feature?

**Comment by smarterclayton** [comment]
We still want this.  This is an abuse point.

**Comment by bsalamat** [comment]
[We are thinking](https://github.com/kubernetes/kubernetes/issues/51732) about creating a generic resource type good enough to support accounting of "Extended Resources", OIRs, and "Huge Pages", perhaps even other existing resources (memory, cpu, gpu).
With the help of such new resource type, the number of containers can be represented as a scalar resource (no fractional or overcommitment is allowed). Nodes can report the maximum number of containers they can handle, scheduler can enforce it, and we can also define ResourceQuota on it.

**Comment by vishh** [comment]
@bsalamat With that model we may need an admission plugin that will inject "container" resource requests based on number of containers in a pod. In general I agree it's better to introduce the extensible pipeline rather than introducing another explicit resource.

**Comment by bsalamat** [comment]
@vishh I like the idea an admission controller for injecting "containers" to resource requests. If for some reason there is any objections, a library that returns a resource request based on the containers in a pod can be used, but I like the former approach (your suggestion) better.
