### ISSUE TITLE
AWS: kubelet went offline

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#41904]
I saw this in the kubelet logs:

```
Feb 21 01:26:28 ip-172-20-48-152 kubelet[1208]: E0221 01:26:28.803875    1208 kubelet_node_status.go:302] Error updating node status, will retry: failed to get node address from cloud provider: UnknownError: unknown error
Feb 21 01:26:28 ip-172-20-48-152 kubelet[1208]: E0221 01:26:28.818028    1208 kubelet_node_status.go:302] Error updating node status, will retry: failed to get node address from cloud provider: UnknownError: unknown error
Feb 21 01:26:28 ip-172-20-48-152 kubelet[1208]: E0221 01:26:28.820542    1208 kubelet_node_status.go:302] Error updating node status, will retry: failed to get node address from cloud provider: UnknownError: unknown error
Feb 21 01:26:28 ip-172-20-48-152 kubelet[1208]: E0221 01:26:28.836201    1208 kubelet_node_status.go:302] Error updating node status, will retry: failed to get node address from cloud provider: UnknownError: unknown error
Feb 21 01:26:28 ip-172-20-48-152 kubelet[1208]: E0221 01:26:28.868791    1208 kubelet_node_status.go:302] Error updating node status, will retry: failed to get node address from cloud provider: UnknownError: unknown error
```

`curl http://169.254.169.254/latest/meta-data/local-ipv4` and `curl http://169.254.169.254/latest/meta-data/public-ipv4` were working from the host.

describe node showed that it had stopped posting node status:
```
Conditions:
  Type			Status		LastHeartbeatTime			LastTransitionTime			Reason				Message
  ----			------		-----------------			------------------			------				-------
  OutOfDisk 		Unknown 	Tue, 21 Feb 2017 01:24:58 +0000 	Tue, 21 Feb 2017 01:25:41 +0000 	NodeStatusUnknown 		Kubelet stopped posting node status.
  MemoryPressure 	False 		Tue, 21 Feb 2017 01:24:58 +0000 	Sat, 18 Feb 2017 02:13:22 +0000 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  DiskPressure 		False 		Tue, 21 Feb 2017 01:24:58 +0000 	Sat, 18 Feb 2017 02:13:22 +0000 	KubeletHasNoDiskPressure 	kubelet has no disk pressure
  Ready 		Unknown 	Tue, 21 Feb 2017 01:24:58 +0000 	Tue, 21 Feb 2017 01:25:41 +0000 	NodeStatusUnknown 		Kubelet stopped posting node status.
  NetworkUnavailable 	False 		Sat, 18 Feb 2017 02:13:57 +0000 	Sat, 18 Feb 2017 02:13:57 +0000 	RouteCreated 			RouteController created a route
```

tcpdump showed requests to the IAM metadata endpoint, but it showed no requests to the EC2 local-ipv4 / public-ipv4 endpoints.

Restarting kubelet caused it to recover, and we saw requests to the local-ipv4 / public-ipv4 endpoints again.

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by spiffxp** [comment]
@kubernetes/sig-aws-misc do you want this in v1.7? is this the right sig to own this issue?

**Comment by justinsb** [comment]
I added a richer log message in #47399 to help diagnostics.

I'm not sure if this behaviour is wrong actually.  The kubelet goes offline, the node gets evicted etc.

The only challenge is if the metadata service goes down cluster-wide.  We don't want to just shut-down.  When we have sig/cloud we can talk about it there I guess.

**Comment by spiffxp** [comment]
/remove-priority P0
/priority critical-urgent
(I'm not actually sure this is the right priority, just trying to remove the old priority/PN labels)

**Comment by justinsb** [comment]
Thanks @spiffxp - punting to 1.8 as I don't think this behaviour is necessarily wrong, though it is suboptimal if (for some reason) the metadata service went down AWS-wide.

**Comment by spiffxp** [comment]
/close
Taking an educated guess that this isn't going to get fixed given that we've seen no additional reports of this happening here.  Please /reopen if this is still happening
