### ISSUE TITLE
verify-staging-godeps.sh is failing in Jenkins Verification CI

### ISSUE THREAD

**Issue by sjenning** [kubernetes/kubernetes#41909]
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-verify

Few examples:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41833/pull-kubernetes-verify/18764/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41351/pull-kubernetes-verify/18766/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41906/pull-kubernetes-verify/18767/

**Comment by chuckbutler** [comment]
xref #41351 - i'm seeing the same behavior after it had successful verifications this morning.
