### ISSUE TITLE
RFE: Create a shunt for events

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#41907]
**This a FEATURE REQUEST**:

There have been a series of requests over the years to either "offload", or modify events, e.g. changing TTLs etc. 

The purpose of this issue is vet a very simple idea of creating a simple shunt, perhaps a webhook, around events such that it can be piped into a different system.  

/cc @brendandburns @kubernetes/sig-api-machinery-misc @jbeda @fgrzadkowski @kubernetes/sig-scalability-misc

**Comment by justinsb** [comment]
Can I make my traditional suggestion of GRPC, optionally with a golang plugin if you want it to be in-process?  Let me know if I can assist :-)

**Comment by timothysc** [comment]
I'm hoping for light weight simple redirection, where on the other side it could do what-evers.  Webhooks is the lightest thing I can think where it's fire and forget.

**Comment by timothysc** [comment]
@lavalamp If you could comment here it would be much appreciated.  Your comment on slack re: separate api-server seems really heavy weight to me.

**Comment by lavalamp** [comment]
Why is this important?

I see two options:

* A storage plugin type thing, which @justinsb may have an example of.
* A separate apiserver, with completely custom storage or a webhook or whatever you want.

I'm not sure what it would take to convince me that a webhook for events is a good idea in the main apiserver.

**Comment by timothysc** [comment]
>Why is this important?

To allow operators to store and index events for some period of time (months/years), without having such heavy weight solutions.  

It's highly useful to store this information for auditing and debugging purposes too.

**Comment by countspongebob** [comment]
Agree entirely with Tim on the reasons this is important. We've had many discussions at Sig Scaling about the need to separate event stream for performance tuning. There are many systems out there that are highly tuned for exactly this use case, and we should be able to easily use those instead of etcd. Public clouds have good options for this use case as well... would be good to have the option to quickly swap those in.

**Comment by timothysc** [comment]
Closing this, decided to go a different way: https://github.com/heptio/eventrouter

**Comment by ryanwalls** [comment]
@timothysc Perhaps leave this open?  I think it is an important feature request.

**Comment by timothysc** [comment]
Deciding to close, and use auxiliary system

**Comment by timothysc** [comment]
Folks have requested a re-open of this issue.

**Comment by timothysc** [comment]
@kensimon @ncdc In chatting with BrianG, he had stated that a goal of aggregated api-servers is to shard existing objects, which would allow for the customized behavior without having to do things like eventrouter and make it more 1st classed.
