### ISSUE TITLE
[k8s.io] Pods should be submitted and removed [Conformance] 1m42s

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#41902]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41894/pull-kubernetes-e2e-gce/19327/

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/pods.go:262
Failed to observe pod deletion
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/pods.go:251
```

**Comment by yujuhong** [comment]
@dashpole is looking into this.

**Comment by yujuhong** [comment]
Seems like a lot of flakes are caused by the watch issue: #31345 
Maybe we should switch to polling in the test.

**Comment by smarterclayton** [comment]
I'm taking this

**Comment by smarterclayton** [comment]
Opened a fix that will at minimum give us more info, but also increases timeout

**Comment by smarterclayton** [comment]
This is the last failure before my changed merged: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/4717

Still waiting for a post.

**Comment by dchen1107** [comment]
@smarterclayton Do you think https://github.com/kubernetes/kubernetes/pull/42779 is enough to address this issue? Or there are some other pending issues in watching code? Can we close this one?

**Comment by smarterclayton** [comment]
We can close this, the issue is almost certainly the one fixed.
