### ISSUE TITLE
ci-kubernetes-e2e-gci-gke failing with "Failed to list resources (exit status 1)"

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#41917]
The last 4 runs of https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/ have failed on the `ListResources After` and `ListResources Before` steps with `Failed to list resources (exit status 1)`:
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/5061/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/5062/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/5063/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/5064/

The GCE version of this test suite appears to be fine.

This is blocking the submit queue.

CC @kubernetes/test-infra-maintainers @kubernetes/goog-gke

**Comment by krzyzacy** [comment]
Is there a way to see what does /cluster/gce/list-resources.sh output in
the runs... exit status 1 is not very informative

**Comment by ncdc** [comment]
Here is a non-gke failure: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/2974

**Comment by ncdc** [comment]
Given that the last thing output from the listing of resource is:

```
W0222 10:43:46.764] [ firewall-rules ]
W0222 10:43:46.764] ]
```

I would bet that the `GREP_REGEX` defined [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/list-resources.sh#L88) is failing to find a match from [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/list-resources.sh#L90) (see [where it's invoked](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/list-resources.sh#L52))

**Comment by krzyzacy** [comment]
Hummm I ran it locally against `k8s-jkns-e2e-gke-ci` but did not get the same failure

**Comment by krzyzacy** [comment]
@ixdy you might be more familiar with list-resources.sh

**Comment by rmmh** [comment]
This started happening on the 16th and became more regular on the 18th-- @krzyzacy do you think the new janitor code might be exercising this?

More details here: https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=ListResources#aaf8bc1b17d783e3923e

**Comment by rmmh** [comment]
`REGION=us-central1 ZONE=us-central1-a PROJECT=k8s-gci-gke-ingress-1-5 bash list-resources.sh` is giving me exit status 1, let me find which command it is.

**Comment by ixdy** [comment]
Yeah, @ncdc and @rmmh have figured it out. Because of the janitor, we no longer have any default firewall rules in these projects (which might be a bug), and so now the `grep` is failing.

I think in the distant past `gcloud` always printed out a header, even if nothing was found, though it hasn't done that in a long time.

Fix for `list-resources.sh` is to ` || true` the `grep` on L52. We may also want to decide if we should be deleting the default firewalls.

**Comment by rmmh** [comment]
We'll want to cherrypick that to the old branches, too.

**Comment by krzyzacy** [comment]
hummm I'll let it skip default-firewall

**Comment by saad-ali** [comment]
Keeping open until we've verified fix
