### ISSUE TITLE
PetSets no longer supported in favor of StatefulSets

### ISSUE THREAD

**Issue by Dbz** [kubernetes/kubernetes#41926]
I think the humanitarian change of PetSet to StatefulSet is a good one, and StatefulSet as a name makes more sense than PetSet; however, I feel the best software development practice is to not to make an API breaking change (I understand with `v1alpha1` this is debatable) and deprecate the functionality while giving people time to upgrade their configurations. We should also display a deprecated message when applying/creating a PetSet to use a StatefulSet. While this isn't a huge issue for this tiny change, it represents a standard for moving forward. As a codebase/community we should be very cautious when introducing breaking changes and give everyone plenty of time to prepare for them. I sincerely apologize if this was discussed and dismissed earlier, and I am not intending to flame nor cause any sort of controversy nor waste anyone's time (I apologize if this is the case.).

Keyword searches: PetSet StatefulSet
[Relevant Discussion](https://github.com/kubernetes/kubernetes/pull/35663)

FEATURE REQUEST:

Deprecate PetSets (but still allow them to be used) and post a message on apply/create that PetSets are deprecated and will be removed in the next version.

**Kubernetes version** (use `kubectl version`): 
> Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-17T20:48:54Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5+coreos.0", GitCommit:"f70c2e5b2944cb5d622621a706bdec3d8a5a9c5e", GitTreeState:"clean", BuildDate:"2016-10-31T19:16:47Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:

When we updated our kubectl and applied a change to a PetSet, it rejected the PetSet and gave an error. We did not update our server.

**What you expected to happen**:

We expected the PetSet update to be applied to our cluster

**How to reproduce it** (as minimally and precisely as possible):

Apply a PetSet using the latest version of kubectl

**Comment by jaygorrell** [comment]
I believe unsupported name changes are considered fair game for things in the `apps/v1alpha1` API.

**Comment by Dbz** [comment]
I am closing this issue due to the [api documentation](https://kubernetes.io/docs/api/) for _Alpha level_ clearly stating:

> The API may change in incompatible ways in a later software release without notice.
