### ISSUE TITLE
IPoIB for Kubernetes

### ISSUE THREAD

**Issue by saurabhjha1** [kubernetes/kubernetes#41936]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
yes

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
_ipoib, infiniband_
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT (most probably)

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
8 Nodes, 2 infiniband switches (internal networking), 1 ethernet switch (used to access outside world) 
- **OS** (e.g. from /etc/os-release):
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

- **Kernel** (e.g. `uname -a`):
4.4.0-63-generic #84-Ubuntu SMP Wed Feb 1 17:20:32 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**:
kubeadm, kubectl, (as mentioned above)

Docker version 
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   6b644ec
 Built:        Mon, 19 Dec 2016 09:20:48 +1300
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   6b644ec
 Built:        Mon, 19 Dec 2016 09:20:48 +1300
 OS/Arch:      linux/amd64

- **Others**:

**What happened**:
After running `kubeadm init --api-advertise-addresses=<infiniband ip>`

*Error seen through `journalctl -fu kubelet.service`*
_Unexpected command output Device "eth0" does not exist._

When running pods, they remain in pending stage

**What you expected to happen**:
When we use ethernet switch, the pods run smoothly. The problem exists only when using inifiniband

**How to reproduce it** (as minimally and precisely as possible):
see above

**Anything else we need to know**:

**Comment by cmluciano** [comment]
Is this still an issue @saurabhjha1

**Comment by MrConIB** [comment]
Hi saurabhjha1, 

In your Environment notes I see 8 Nodes and 2 infiniband switches but no additional info on type of switches or HCA´s. 
When using Infiniband, are you using SM (Subnet Manager) on at least one of your switches or as a soft installation on one of your compute nodes? 

if not that could be the problem you are experiencing

/Mattias
