### ISSUE TITLE
GCE kube-up doesn't install kube-proxy on the master

### ISSUE THREAD

**Issue by caseydavenport** [kubernetes/kubernetes#41943]
Using the standard `cluster/kube-up.sh` installation script on GCE, it looks like the kube-proxy is installed on every node but not on the master.

This is a problem because even though the master is marked as unschedulable, the DaemonSet controller will still run pods on the master node, and those Pods won't be able to communicate via Kubernetes Services. 

And example would be a DaemonSet which tries to talk to the k8s API, but fails on the master since the `kubernetes.default` Service ClusterIP is not programmed.  Similarly, Pods started on the master via a DaemonSet won't have DNS access.

**Comment by caseydavenport** [comment]
CC @whitlockjc

**Comment by whitlockjc** [comment]
I've started work on this.

**Comment by whitlockjc** [comment]
Here is the current WIP for this: https://github.com/whitlockjc/kubernetes/commit/0d5de94aedf7399e73140173b72418fc14314ec1  My plan is to test the different ways to run `kube-up.sh` tomorrow and ensure that `kube-proxy` is running on master in all cases.  Once I do that, I'll create a PR.  _(Do not let this not being an official PR keep you from looking into the changes.  The only reason I've not created a PR yet is because I've not tested all scenarios yet.)_

**Comment by whitlockjc** [comment]
I realize this didn't address the `debian` nodes, I'll get that sorted shortly.

**Comment by liggitt** [comment]
@mikedanese what was the determination on the Debian scripts?

**Comment by whitlockjc** [comment]
I've updated the commit with the necessary salt changes to fix debian.  I'm testing this now and as soon as it's tested, I'll create a PR.  Thanks to @roberthbailey for pointing me in the right direction.

**Comment by whitlockjc** [comment]
@liggitt Here is the issue in case you want to follow along: https://github.com/kubernetes/kubernetes/pull/41666

**Comment by mikedanese** [comment]
Don't daemonsets obey taints now? Why not just taint the master node?

**Comment by whitlockjc** [comment]
What about static pods?  I can spin up another GCE cluster to see what all is running on master and figure how how they are deployed, daemonsets or static pods.  I do agree that what you're proposing would be much simpler.

**Comment by roberthbailey** [comment]
Many of the pods on the master are launched via static pods (e.g. kube-apiserver, scheduler, controller manager, etc). But I think Mike's point was that for pods that don't *need* to be run via static pods, we can use k8s primitives to run them instead of adding more static pods.

**Comment by whitlockjc** [comment]
I got you.  But knowing what pods are scheduled on master now would help us know if taints alone would be enough and whether that alleviates the need for running `kube-proxy` on master.

**Comment by caseydavenport** [comment]
I think a better fix for this is probably to stop running any pods on the master (except for the host-networked master pods, e.g. apiserver)

CC @dnardo @bowei

**Comment by caseydavenport** [comment]
Perhaps we just need to taint the master? Or remove the labels from the master which allow the DaemonSets like fluentd and Calico to run there.

CC @heschlie

**Comment by caseydavenport** [comment]
The original problem I was encountering has been fixed by https://github.com/kubernetes/kubernetes/pull/54838.

I think the general sentiment is we don't want to run kube-proxy on the master, so users shouldn't run pods there.
