### ISSUE TITLE
kubeadm install document need update for ubuntu 

### ISSUE THREAD

**Issue by netroby** [kubernetes/kubernetes#41960]
```
                                                  
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?

```
I am  configure kube as the guide describe. but got error message
https://kubernetes.io/docs/getting-started-guides/kubeadm/

the kubeadm install document for ubuntu may be add apt-get update && apt-get install -y apt-transport-https before the installation step goes.

**Comment by roidelapluie** [comment]
Looks more a bug in the .deb package

**Comment by netroby** [comment]
Seems it not a deb bug. because ubuntu does not default install with apt-transport-https package. so if we need install from https deb repository. we need run 
```bash
apt install -y apt-transport-https
```

**Comment by netroby** [comment]
see https://github.com/kubernetes/kubernetes.github.io/pull/2606

**Comment by netroby** [comment]
This had been resolved . the upstream document had already update
