### ISSUE TITLE
[Federation] kubefed init add etcd image option.

### ISSUE THREAD

**Issue by mawentao02** [kubernetes/kubernetes#41963]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
v1.6.0-alpha.3 

**Environment**:
- **Cloud provider or hardware configuration**: in our compony baremator system
- **OS** (e.g. from /etc/os-release): Ubuntu 14.04.1 LTS
- **Kernel** (e.g. `uname -a`): 4.2.0-27-generic
- **Install tools**: kubefed init
- **Others**:

**What happened**:

https://github.com/kubernetes/kubernetes/blob/master/federation/pkg/kubefed/init/init.go
line 625 :   Image: "gcr.io/google_containers/etcd:3.0.14-alpha.1".

I think it is a hard core, we can't change this image.
For our environment, we cannot connect google containers image, we just can use our private docker repository. But for kubefed init, it should be able to set etcd image option.

**What you expected to happen**:
kubefed init --etcdimage=''

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by quinton-hoole** [comment]
cc @madhusudancs

**Comment by perotinus** [comment]
I believe this was fixed by #46247.

/close
