### ISSUE TITLE
pod logging broken with journald logging driver

### ISSUE THREAD

**Issue by sjenning** [kubernetes/kubernetes#41996]
Warning starting pod when using the journald docker logging driver
```
kubectl get events
LASTSEEN   FIRSTSEEN   COUNT     NAME        KIND      SUBOBJECT                  TYPE      REASON                    SOURCE                  MESSAGE
5m         5m          1         127.0.0.1   Node                                 Normal    Starting                  kube-proxy, 127.0.0.1   Starting kube-proxy.
5m         5m          1         127.0.0.1   Node                                 Normal    Starting                  kubelet, 127.0.0.1      Starting kubelet.
5m         5m          1         127.0.0.1   Node                                 Warning   ImageGCFailed             kubelet, 127.0.0.1      unable to find data for container /
5m         5m          2         127.0.0.1   Node                                 Normal    NodeHasSufficientDisk     kubelet, 127.0.0.1      Node 127.0.0.1 status is now: NodeHasSufficientDisk
5m         5m          2         127.0.0.1   Node                                 Normal    NodeHasSufficientMemory   kubelet, 127.0.0.1      Node 127.0.0.1 status is now: NodeHasSufficientMemory
5m         5m          2         127.0.0.1   Node                                 Normal    NodeHasNoDiskPressure     kubelet, 127.0.0.1      Node 127.0.0.1 status is now: NodeHasNoDiskPressure
4m         4m          1         127.0.0.1   Node                                 Normal    RegisteredNode            controllermanager       Node 127.0.0.1 event: Registered Node 127.0.0.1 in NodeController
4m         4m          1         127.0.0.1   Node                                 Normal    NodeReady                 kubelet, 127.0.0.1      Node 127.0.0.1 status is now: NodeReady
4m         4m          3         burstable   Pod                                  Warning   FailedScheduling          default-scheduler       no nodes available to schedule pods
4m         4m          1         burstable   Pod                                  Normal    Scheduled                 default-scheduler       Successfully assigned burstable to 127.0.0.1
4m         4m          1         burstable   Pod                                  Normal    SandboxReceived           kubelet, 127.0.0.1      Pod sandbox received, it will be created.
4m         4m          1         burstable   Pod       spec.containers{busybox}   Normal    Pulling                   kubelet, 127.0.0.1      pulling image "busybox"
4m         4m          1         burstable   Pod       spec.containers{busybox}   Normal    Pulled                    kubelet, 127.0.0.1      Successfully pulled image "busybox"
4m         4m          1         burstable   Pod       spec.containers{busybox}   Normal    Created                   kubelet, 127.0.0.1      Created container with id 29d9bd0e8871504f86064188db223253b84f6d344856041d5b6a376e2f946d33
4m         4m          1         burstable   Pod       spec.containers{busybox}   Warning   Failed                    kubelet, 127.0.0.1      Failed to start container with id 29d9bd0e8871504f86064188db223253b84f6d344856041d5b6a376e2f946d33 with error: rpc error: code = 2 desc = failed to create symbolic link "/var/log/pods/63a3b8a3-f9fe-11e6-90b7-7085c20cf2ab/busybox_0.log" to the container log file "" for container "29d9bd0e8871504f86064188db223253b84f6d344856041d5b6a376e2f946d33": symlink  /var/log/pods/63a3b8a3-f9fe-11e6-90b7-7085c20cf2ab/busybox_0.log: no such file or directory
4m         4m          1         burstable   Pod                                  Warning   FailedSync                kubelet, 127.0.0.1      Error syncing pod, skipping: failed to "StartContainer" for "busybox" with rpc error: code = 2 desc = failed to create symbolic link "/var/log/pods/63a3b8a3-f9fe-11e6-90b7-7085c20cf2ab/busybox_0.log" to the container log file "" for container "29d9bd0e8871504f86064188db223253b84f6d344856041d5b6a376e2f946d33": symlink  /var/log/pods/63a3b8a3-f9fe-11e6-90b7-7085c20cf2ab/busybox_0.log: no such file or directory: "Start Container Failed"
```
This breaks container-level logging
```
kubectl logs burstable
failed to open log file "/var/log/pods/63a3b8a3-f9fe-11e6-90b7-7085c20cf2ab/busybox_0.log": open /var/log/pods/63a3b8a3-f9fe-11e6-90b7-7085c20cf2ab/busybox_0.log: no such file or directory
```
@derekwaynecarr

**Comment by sjenning** [comment]
This recent revert removed a check that prevented the warning in the events.
https://github.com/kubernetes/kubernetes/commit/66dec96735715a305b265efa15b8751c74491c1e#diff-c7dd39479fd733354254e70845075db5L220

However, if I add that `realPath != nil` check back, I don't see the warning in the events log but `kubectl logs` still shows a logging error message.

**Comment by ncdc** [comment]
@sjenning I noticed this too but thought it maybe had something to do with my switching from devicemapper to overlay2 in docker.

Do you have a full root cause for this yet?

**Comment by sjenning** [comment]
@ncdc hmm I also run overlay.  Let me move back to devicemapper and see if it goes away.  Just for a data point.

**Comment by sjenning** [comment]
@ncdc i see the warning event and the log error even w/ devicemapper

**Comment by ncdc** [comment]
@sjenning looks like with the CRI enabled, it's going to here? https://github.com/kubernetes/kubernetes/blob/c436671cca6f2ecff3674e64ef219e4fff02b2a3/pkg/kubelet/kuberuntime/kuberuntime_container.go#L683-L692

**Comment by Random-Liu** [comment]
There is another on-going PR for this. https://github.com/kubernetes/kubernetes/pull/38691

**Comment by sjenning** [comment]
Should be noted that #38691 does not fix pod logging with the `journald` driver that worked before the CRI was enabled.  It only prevents the nasty error messages.  Pod logging is still broken with anything other than `json-file`.

**Comment by Random-Liu** [comment]
@sjenning @yujuhong 

I was wondering whether we also have regression for syslog. However, it seems that docker logs only support `json-file` and `journald` now https://docs.docker.com/engine/admin/logging/overview/#/limitations-of-logging-drivers.

So the only regression is that `kubectl logs` doesn't work with journald when CRI is enabled.

Some possible solutions:
* Option 1: Redirect the journald log of each container into the expected CRI log path. Run a goroutine for each container, which use golang docker client to follow the container log and redirect it into the file.
  * Pros: Keep CRI integration clean.
  * Cons: Some extra overhead.
* Option 2: As a quick hack, expose docker information from CRI, and get docker log directly when the runtime is docker, and logging driver is journald.
  * Pros: No overhead.
  * Cons: Break the original purpose of CRI.

I think option 1 is better.

**Comment by sjenning** [comment]
@yujuhong is working on a change (not PR yet to my knowledge) to restore journald pod logging until a proper deprecation plan is made. https://github.com/kubernetes/kubernetes/pull/42009#issuecomment-282849511

**Comment by Random-Liu** [comment]
I tried on gci. It seems that `docker logs` doesn't work for journald in docker v1.11.2.

Docker version:
```
$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.7.4
 Git commit:   4dc5990
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.7.4
 Git commit:   4dc5990
 Built:        
 OS/Arch:      linux/amd64
```

Docker info:
```
$ docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.35+
Operating System: Container-Optimized OS from Google
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.619 GiB
Name: test-logging
ID: ZB5Q:RZR4:WDRY:4JEM:TUL6:JOLR:AB53:TLYE:BJSS:WIT2:GF7K:BDKL
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

Run a docker container:
```
$ docker run busybox ls
bin
dev
etc
home
proc
root
sys
tmp
usr
var
```

Get log from `journalctl`:
```
$ sudo journalctl CONTAINER_ID=4676e9fe17f2
-- Logs begin at Mon 2017-02-27 22:59:45 UTC, end at Tue 2017-02-28 01:42:58 UTC. --
Feb 28 01:42:16 test-logging docker[1487]: bin
Feb 28 01:42:16 test-logging docker[1487]: dev
Feb 28 01:42:16 test-logging docker[1487]: etc
Feb 28 01:42:16 test-logging docker[1487]: home
Feb 28 01:42:16 test-logging docker[1487]: proc
Feb 28 01:42:16 test-logging docker[1487]: root
Feb 28 01:42:16 test-logging docker[1487]: sys
Feb 28 01:42:16 test-logging docker[1487]: tmp
Feb 28 01:42:16 test-logging docker[1487]: usr
Feb 28 01:42:16 test-logging docker[1487]: var
```

Get log from `docker logs`:
```
$ docker logs 4676e9fe17f2
Error response from daemon: configured logging reader does not support reading
```

@kubernetes/sig-node-bugs

**Comment by yujuhong** [comment]
I tried with ubuntu 16.04 + docker 1.12.3, and got the same error message.

**Comment by feiskyer** [comment]
Same issue with docker v1.12.6, reported at https://github.com/docker/docker/issues/31404.

**Comment by Random-Liu** [comment]
@feiskyer For GCI, I think they build docker themselves. For ubuntu, we install docker with `apt-get install docker-engine`.

**Comment by Abhay11** [comment]
> @yujuhong is working on a change (not PR yet to my knowledge) to restore journald pod logging until a proper deprecation plan is made. [#42009 (comment)](https://github.com/kubernetes/kubernetes/pull/42009#issuecomment-282849511)

Does the journald pod logging (`kubectl logs` command) work with v1.18.x? Is there a way to make this work with v1.18.x? I've set up a multinode cluster with docker logging driver as journald and using systemd-journal-gatewayd with pull approach to aggregate historical logs. However, I'm very much interested in being able to tail logs using 'kubectl logs' or, 'kubectl logs -l <applabel> --prefix -f'.
