### ISSUE TITLE
pkg/security/podsecuritypolicy/capabilities/mustrunas_test.go could be improved

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubernetes#41990]
I'm suggesting to do the following improvements to the [pkg/security/podsecuritypolicy/capabilities/mustrunas_test.go](https://github.com/kubernetes/kubernetes/blob/17375fc59fff39135af63bd1750bb07c36ef873b/pkg/security/podsecuritypolicy/capabilities/mustrunas_test.go) file:

- `TestGenerateAdds`: remove unused `requiredDropCaps` member from the struct
- `TestValidateAdds`: remove unused `requiredDropCaps` member from the struct
- `TestValidateDrops`: remove unused `defaultAddCaps` member from the struct
- `TestValidateAdds`, `TestValidateDrops`: instead of using `shouldPass bool` and checking only whether test fails or not, we could check (also) an error message

This refactoring is simple and may be performed by the new contributors (could someone add label `for-new-contributors`?)

**Comment by roidelapluie** [comment]
Here you go.
