### ISSUE TITLE
DaemonSet pods should be scheduled by default scheduler, not DaemonSet controller

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#42002]
DaemonSet controller being its own scheduler has caused lots of confusion. Once we have tolerations and preemption, I think we won't need DaemonSet-specific scheduling logic. See also #42001.

cc/ @kubernetes/sig-scheduling-misc @kubernetes/sig-cluster-lifecycle-misc

**Comment by davidopp** [comment]
cc/ @kubernetes/sig-apps-misc

**Comment by smarterclayton** [comment]
Agree

**Comment by timothysc** [comment]
So the part where @jayunit100 was refactoring portions of the scheduler to be linked externally without causing a dependency train wreck was to support issues like this.

**Comment by davidopp** [comment]
It's much better for DaemonSet to just produce pods like every other controller, and let them be scheduled by the regular scheduler, than to be its own scheduler. There are definitely use cases for linking in scheduler code to a component, but I don't think this is one of them. Even if it were easy to do that, DaemonSet shouldn't be a scheduler.

**Comment by kargakis** [comment]
+1000

Trying to make the DS controller sync with the scheduler feels like a nightmare so far.

**Comment by timothysc** [comment]
@davidopp Totally agree... 
But then daemonset just becomes a special anti-affinity based on node... More of a macro than a primitive, which was my original position in the 1st place.

**Comment by k82cn** [comment]
+1

**Comment by resouer** [comment]
A naive question, what happens if there's no scheduler running? (for example, this DS is used to deploy master components).

**Comment by kargakis** [comment]
Good question, cluster admins can always run one-off pods and bypass the scheduler manually.

**Comment by davidopp** [comment]
This would presumably also fix #35228.

**Comment by timothysc** [comment]
> A naive question, what happens if there's no scheduler running? (for example, this DS is used to deploy master components). 

@mikedanese proposed 1-shot scheduling for boot-strapping ~year ago.

**Comment by kargakis** [comment]
@jbeda @luxas @roberthbailey you guys will be interested in this one

**Comment by luxas** [comment]
Yeah, thanks @kargakis. This was exactly the "fear" @jbeda mentioned.
If we do this, I'd rather have a "bootstrapping mode" that bypasses this (in case this breaks people, we don't know that yet)

**Comment by roberthbailey** [comment]
I not sure I fully understand the bootstrapping concerns. You can always bypass the scheduler if you want (by specifying a node explicitly), so why not start with that for bootstrapping and then pivot into using a DS once the scheduler is running?

**Comment by jayunit100** [comment]
This brings up the question of wether it's possible to protect certain things from being written to the API server by certain unauthirized components in general? I don't know the answer to this question.

**Comment by smarterclayton** [comment]
We can also just add a new core controller that satisfies long running scheduler failures.  However, that's not enough, since you usually need a node, replication controller, and deployment controller in order to run.  Failsafe self-hosted components is really a discussion in itself, and deserves a longer design.  I don't think daemonset should be doing its own scheduling either, especially with sophisticated taints in play.

**Comment by k82cn** [comment]
Not sure why we support bypass the scheduler; scheduler should be the only component to place the pods on Node (static pod is considered to be out of scheduling. Can we update the `Node.allocable` to not include static pod's resource?). 

1. If placing Pod by admin, I doubt whether he knows the detail of cluster to make the "right" decision
1. If placing Pod by external-scheduler, it should be moved to scheduler or an extender/plugin of scheduler
1. If any requirement to scheduler, suggest to enhance scheduler

**Comment by jayunit100** [comment]
Are we all in agreement here that *the scheduler should be the one doing the scheduling* ?

**Comment by k82cn** [comment]
> the scheduler should be the one doing the scheduling in all cases 

IMO: +1 , and it should be one of "kubernetes core". I'd like to see others' comments :).

**Comment by smarterclayton** [comment]
Having the scheduler doing the scheduling means we can take away bind permission from components besides the scheduler, and then introduce openshift's admission controller that requires that permission to modify node name on pods, which then prevents bypassing scheduling for "normal" tenants and makes tolerations a viable security mechanism

**Comment by luxas** [comment]
The primary issue we discussed in sig-cluster-lifecycle was that currently a pod network DS is deployed regardless of Node Ready/NotReady. When we switch to the scheduler this won't happen.

But I think switching to tolerations for reporting Ready/NotReady status will fix that issue

**Comment by timothysc** [comment]
@davidopp enqueue for next sig meeting.

**Comment by davidopp** [comment]
I think it's reasonable to ship by default with "only default scheduler can set NodeName" (assuming there aren't any bootstrapping issues) but I think we need to make it possible for cluster admins to optionally add to the set of components that can set NodeName, so that people can write custom schedulers. (Not all user customizations to the scheduler can be cast into the extender model.)

**Comment by davidopp** [comment]
Any opinions on how to prioritize this? It sounds like everyone agrees it should be done, but is there a strong reason to do it for 1.7 rather than wait until 1.8?

**Comment by jayunit100** [comment]
- The dependencies are spread around, like #40573 (gauranteed admission issue), #22212 (preemption priority scheme), and the highly active google doc https://docs.google.com/document/d/1-H2hnZap7gQivcSU-9j4ZrJ8wE_WwcfOkTeAGjzUyLA/edit# ("Resource scheduling architecture for batch and serving workloads in Kubernetes").
- These don't seem to be solidified yet.
- To make a simple and unambiguous, highly reliable scheduler based daemonset, those issues should be solidified.
- ... So That comfortably moves us out to 1.8 and reduces semantic churn that might happen otherwise . If there is urgency to merge for 1.7, I understand a first pass, but I see the implementation changeing or worse-yet leading to backward incompatible changes that are hard to define that will effect critical running applications.


*Conclusion* = I'd suggest bumping to 1.8 , any objections?  Im not against having it in 1.7, but it seems like the primitives for it are still underway.

**Comment by k82cn** [comment]
no objection to move to 1.8 :).

**Comment by smarterclayton** [comment]
We already have rbac for /bind - the admission controller in openshift
that protects nodeName from being settable by people who can't /bind
is fairly easy to upstream.

**Comment by jayunit100** [comment]
**summary**

During 1.7 we need to:

- [ ] finish adding necessary for primitives that will allow daemonset-ish functionality without DOS in the scheduler #22212 
- [ ] Also make sure gauranteed admission is working #40573

After 1.7: 

- [ ] refine the primitives further to make sure they can be used by the scheduler for Daemonsets.
- [ ] implement daemonset in the scheduler using high prio / gauranteed execution primitives
- [ ] Add default RBAC for bind that can enforce non-subversion of the scheduler.

**Comment by k82cn** [comment]
For now, there're two issues related DaemonSet:

* #46386 Daemonset pods not getting deployed after failing certain number of times
* #45628 DaemonsetController can't feel it when node recovered from outofdisk state

Can we just keep the same behaviour in 1.7 after move to scheduler? e.g. creating Pods with NodeAffinity for all nodes, it'll keep pending if predicates faileds. For rbac & priority schema, it should be after 1.7 :).

**Comment by timothysc** [comment]
>  creating Pods with NodeAffinity for all nodes 

It's just computationally expensive on larger clusters due to the current design of the scheduler.

**Comment by k82cn** [comment]
>> creating Pods with NodeAffinity for all nodes

> It's just computationally expensive on larger clusters due to the current design of the scheduler.

hm .., agree. but if we moved "DaemonSet's scheduling" into scheduler, we will have such issue more or less.

 Another option in my mind is to create Pod for each Nodes by setting `pod.Spec.NodeName`, but kubelet did not fail the job if admin did not pass for DaemonSet Pod; it'll check those Pod periodically or "something" changed. My concern to this option is that: I do not want to ask kubelet to handle DaemonSet Pod specially, and we may reject non-scheduler components to set `pod.Spec.NodeName` by rbac.

**Comment by k82cn** [comment]
Summary the options in my mind to place DaemonSet's Pod by scheduler:

1. DaemonSet start Pod with annotation (e.g. kubernetes.io/config.spread), add a new predicates in scheduler: for spread pod, return false if an existing pod with the same owner
1. DaemonSet start Pod and set `spec.NodeName`, but did not involve scheduler; leverage kubelet to check. For kubelet, if it's DaemonSet's Pod, did not failed it to make it pending
    - two concern: a.) kubelet need to know it's DaemonSet's Pod to skip failure, b.) it can not handle Pod Affinity
1. Leverage NodeAffinity or PodAntiAffinity to make sure one Pod per node
    - the concern is performance
1. Others?

Perfer to Option 1, considering the performance and scheduler's policy. Anyway, all those options need to only start enough Pods for **selected** nodes.

**Comment by kargakis** [comment]
3 seems like the most correct approach - can you elaborate on why perf is a concern?

**Comment by k82cn** [comment]
sure, I'll elaborate perf of `NodeAffinity` firstly; regarding PodAntiAffinity, there maybe several Pods in a node, and we need to check both scheduling Pod and existing Pods which maybe a perf concern.

**Comment by k82cn** [comment]
/assign

I assign to myself to investigate option 3; if any other suggestion, please let me know :).

**Comment by k82cn** [comment]
Create a benchmark for NodeAffinity at #46948 , the Pod number is number of DS * number of node.

For 10 DS on 5000 nodes, we still can not get output after 10m :(.

```
BenchmarkPodMatchesNodeLabels_10DS_50Node-8     	      20	  59364607 ns/op
BenchmarkPodMatchesNodeLabels_10DS_500Node-8    	       1	6280762515 ns/op
BenchmarkPodMatchesNodeLabels_10DS_5000Node-8    	killed after 10m without output
```

**Comment by wanghaoran1988** [comment]
@k82cn @kargakis 
Maybe we can bring the multiple scheduler logic here, my generic thought is different app can be scheduled by it's own scheduler, we can startup another customized  scheduler for DaemonSet, and have a admission controller set the schedulerName for DaemonSet pods, this will decouple the different requirement for scheduling different kind of app/pods.

**Comment by k82cn** [comment]
Did some enhancement that moving out key/value validation in "selector.NewRequirement", for Pod, it should be validated when creating. With the enhancement, it'll take ~160s for 50k Pods on 5k nodes.

```
MacPro:kubernetes klaus$ /usr/local/go/bin/go test -v k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates -bench ^BenchmarkPodMatchesNodeLabels -run ^$ -cpuprofile out.profil
BenchmarkPodMatchesNodeLabels_500Pods_50Nodes-8       	     100	  15199634 ns/op
BenchmarkPodMatchesNodeLabels_5000Pods_500Nodes-8     	       1	1539526320 ns/op
BenchmarkPodMatchesNodeLabels_50000Pods_5000Nodes-8   	       1	162814811916 ns/op
PASS
ok  	k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates	166.096s
```

**Comment by k82cn** [comment]
Here's profile without enhancement, that's helpful :).

```
(pprof) top20 -cum
2.47s of 8.86s total (27.88%)
Dropped 86 nodes (cum <= 0.04s)
Showing top 20 nodes out of 79 (cum >= 1.23s)
      flat  flat%   sum%        cum   cum%
         0     0%     0%      8.67s 97.86%  runtime.goexit
         0     0%     0%      7.70s 86.91%  k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.BenchmarkPodMatchesNodeLabels_5000Pods_500Nodes
         0     0%     0%      7.70s 86.91%  testing.(*B).run1.func1
         0     0%     0%      7.70s 86.91%  testing.(*B).runN
     0.02s  0.23%  0.23%      7.69s 86.79%  k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.benchmarkPodMatchesNodeLabels
     0.04s  0.45%  0.68%      7.67s 86.57%  k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.podMatchesNodeLabels
     0.03s  0.34%  1.02%      7.38s 83.30%  k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.nodeMatchesNodeSelectorTerms
     0.10s  1.13%  2.14%      7.17s 80.93%  k8s.io/kubernetes/pkg/api/v1/helper.NodeSelectorRequirementsAsSelector
     0.04s  0.45%  2.60%      6.03s 68.06%  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/labels.NewRequirement
```

**Comment by timothysc** [comment]
There is no way we're going to land this for 1.7, we're past feature freeze at this point.

**Comment by luxas** [comment]
@timothysc I don't think this is planned for v1.7 either...

**Comment by k82cn** [comment]
me too :). It's not for 1.7 :).

**Comment by k82cn** [comment]
@luxas , @timothysc , @kargakis , @ravisantoshgudimetla there's design doc about the proposal above, based on my understanding; please help to comment it when you have time :).

https://docs.google.com/document/d/10Ch3dhD88mnHYTq9q4jtX3e9e6gpndC78g5Ea6q4JY4/edit?usp=sharing

**Comment by bgrant0607** [comment]
Kubernetes supports [multiple and user-provided schedulers](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/multiple-schedulers.md), the scheduler is pluggable, and the Kubelet is the final arbiter of what pods belong on a node. The default scheduler isn't a policy-enforcement mechanism.

We went through similar discussions regarding the scheduler extension mechanism:
https://github.com/kubernetes/kubernetes/pull/13580

My counterproposal would be to add optional fit checks for constraints, resources, priority, etc. to the /binding API, to support dry run for /binding, and to change DaemonSet to use /binding. DaemonSet needs to be able to figure out how many pods to create and which ones that it expected to schedule cannot schedule. It does not need the scheduler's node prioritization and selection logic, and will need to coordinate pod and node lifecycles.

**Comment by davidopp** [comment]
@bgrant0607 I'm not understanding your argument.

The idea here is to have the DaemonSet controller work just like ReplicaSet, Job, etc.

What kind of policy enforcement do you think is being expected here beyond what is already required to implement the v1 API that people already use with, say, ReplicaSet?

Regarding knowing whether a pod will schedule on a particular node according to the kubelet admission rules, we already have code in other components (like cluster autoscaler) that does this. It seems more efficient to treat this as a library used by components that need this information, and include it in DaemonSet controller, than to have such components guess and do a dry run against /binding.

**Comment by davidopp** [comment]
If someone writes a new scheduler, they would write a similar "library."

**Comment by davidopp** [comment]
To clarify one other thing: Nobody is saying it's not feasible to replace the scheduler or use multiple schedulers. We just expect them to implement the core feasibility rules that kubelet uses in admission. And that includes things like affinity and taints/tolerations. (It may not include everything right now because we haven't had anyone to finish moving this stuff into GeneralPredicates, but that was definitely the intention.)

**Comment by davidopp** [comment]
The one scenario where I can see this proposal not working is if someone replaces the default scheduler with one that implements additional predicate functions that prevent daemons from scheduling on nodes where the default scheduler would allow them to schedule. The current DaemonSet controller architecture allows to force the pod to schedule onto such nodes. I guess that might be a justification for having the DaemonSet controller do its own scheduling. (Running additional schedulers alongside the default scheduler should be OK as long as they don't direct daemon pods to that additional scheduler.)

**Comment by davidopp** [comment]
I made some updates to my earlier comments in this thread, so if you read them by email please check the web version.

**Comment by bgrant0607** [comment]
@davidopp Another question unanswered in the doc is this:

DaemonSet needs to know how many pods are supposed to exist, and how many to consider unavailable. It reports this information in its status, and also uses it to modulate the progress of rolling updates. It's not clear to me how it could do that if it didn't have an implementation of the fit predicates.

Why is it hard to factor the fit predicates into a library, which needs to be done, anyway?

**Comment by davidopp** [comment]
> Why is it hard to factor the fit predicates into a library, which needs to be done, anyway?

It's not hard. We haven't been very systematic about it, for example cluster autoscaler uses its [PredicateChecker](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/simulator/predicates.go#L37) class while DaemonSet, default scheduler, and kubelet use [DefaultPredicates](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemoncontroller.go#L1210) (well DaemonSet used it until the critical pod stuff made it more complicated, but that should go away when we have priority and preemption), but we have been gradually moving in the direction of factoring the fit predicates into a library.

I think the main problem you're raising is that even if a third-party scheduler provided such a library, you'd need to compile it into the components that need to do these "simulations." Having the scheduler implement a dry run mode would avoid this. So what you're suggesting makes sense, even though it's unfortunately from an efficiency perspective.

**Comment by davidopp** [comment]
@wojtek-t wrote (in the doc, but let's use this issue rather than the doc for this particular topic):

> We were talking about implementing "dry-run" mode at some point, but it's also non-trivial now. 
> Currently when default scheduler supports only scheduling one pod at a time, this means that we
> should either change that or those "dry runs" will be blocking real schedulings. The latter sounds really 
> bad to me, the former will be a big task...

Just to make sure we're defining "dry run mode" the same way -- we're talking about running the regular scheduler algorithm on the DaemonSet pod, but the scheduler does not update any cached state and does not send the binding to the master when it's done, yes? Is your concern that too many of these queries will overload the scheduler (assuming we don't try to add additional concurrency to the scheduler)? If so, I suppose we could rate limit the "dry run" requests?

**Comment by wojtek-t** [comment]
@davidopp - yes I think we understand it the same way - for me it is "running scheduling algorithm (in scheduler itself) in the current state without applying any changes to the internal state".

So what I was trying to say is that:
1. currently it's not possible to run multiple "dry-run queries" at the same time (also not simultanously with some other real scheduling)
2. to make this API somehow useful, we would have to enable it
3. rate-limitting will solve a bunch of problems but we need to make sure this exactly what we want (maybe, I don't know now)
4. I don't think dry-run will solve the cluster-autoscaler usecase, because it is running predicates also on artificial nodes it is planning to add for simulation purposes - scheduler won't be able to do it (because there is no such node).

The other thing that I didn't though very carefully is that for the "dry run mode", all the usecases I can think about don't require running priorities - it's only about predicates. If that's the case, we would need a bit of refactoring to support it (though not that much).

**Comment by davidopp** [comment]
Good point about cluster autoscaler; I hadn't thought about that. (You could imagine "dry run" mode allowing you to add nodes, not just a pending pod, but that's starting to get pretty complicated...)

For the others, my point is just that maybe continuing to do sequential scheduling would be OK (mix dry-runs and real scheduling, but never both at the same time, in sequence) if we limit the rate of the dry-run requessts.

**Comment by wojtek-t** [comment]
> For the others, my point is just that maybe continuing to do sequential scheduling would be OK (mix dry-runs and real scheduling, but never both at the same time, in sequence) if we limit the rate of the dry-run requessts.

Maybe - we just need to list the usecases and see if rate-limiting wouldn't make it unusable due to too small number of possible requests.

**Comment by davidopp** [comment]
I'm not sure where we should go with this. If we rely on DaemonSet controller to manage critical system pods (e.g. run kube-proxy on every node), then the system may break if the cluster admin substitutes a scheduler that doesn't schedule the DaemonSet pods as expected. 

I discussed this a little with @timothysc and his perspective (I'll let him elaborate more on it) was that there are many things a cluster admin can do to break things, and they should just make sure that if they use a custom scheduler, it should handle DaemonSet pods correctly. 

I think the "simulation" question (how components that need to "simulate" where pods will schedule should work in a world of replaceable and multiple schedulers) is a good one but should be discussed in a separate issue (#48657) since it applies to more than just DaemonSet. I think that even if we had a perfect solution for "simulation" of scheduler behavior, we might still want DaemonSet to schedule its own pods, so that critical system pods can always rely on being scheduled in a predictable way regardless of what replacement scheduler might be used.

But I'll let @timothysc chime in with his perspective.

(Also, I came across #29276, which is related to this one.)

**Comment by k82cn** [comment]
> I think that even if we had a perfect solution for "simulation" of scheduler behavior, we might still want DaemonSet to schedule its own pods, so that critical system pods can always rely on being scheduled in a predictable way regardless of what replacement scheduler might be used.

So we're going to still let DaemonSet schedule its pods? 

I think the replacement scheduler should handle Pods's attributes well, e.g. mirror pod, critical pods.

**Comment by bsalamat** [comment]
This is a tough one and is hard to say which one is a better approach. If I had to decide, I would still let the main scheduler schedule DaemonSet pods. I agree with @timothysc that admin can do many things to break a system. Even if we let the DaemonSet controller schedule its pods, a substitute scheduler can still break the system badly by, for example, not scheduling ReplicaSet pods. I know that many critical system pods are DaemonSet pods and if they are not scheduled properly the cluster will not function, but the net outcome of a cluster with a broken scheduler that supposed to run, for example, a replicated web service is the same whether DeamonSet pods are scheduled by the DaemonSet controller or not. In both cases, the cluster will not perform what it is supposed to do. So, it is imperative that the substitute scheduler perform all of its expected work correctly and part of the "expectation" can be scheduling DaemonSet pods.

**Comment by davidopp** [comment]
One thing I forgot that @timothysc had suggested was that we could have scheduler conformance tests that verify that a replacement scheduler meets whatever minimum criteria we have. (This is kinda an automated version of #17208.) This is an excellent idea regardless of what we do with DaemonSet. For example it could verify that the scheduler implements the predicates that are built into kubelet admission.

I'm still not sure about DaemonSet. If we decide we want it to use the default scheduler, we may have to implement #48657.

**Comment by k82cn** [comment]
+1 to conformance tests for replacement scheduler

After went through the discussion, I'm also not sure about DaemonSet :). I think it dependents on our expectation to the replacement scheduler, e.g. will replacement scheduler support NodeAffinity?

regarding dry-run, prefer to add some annotations to Pod instead of exposing REST from default-scheduler; it introduce extras dependency between components (we introduce HTTPExtender because Golang does not support dynamic lab)

**Comment by erictune** [comment]
To allow bootstrapping a scheduler pod onto a cluster, there needs to be some type of controller that does not depend on the scheduler itself.    Given that there has to be something that does it, I don't see why DaemonSet can't be that thing.

**Comment by davidopp** [comment]
Bootstrapping was discussed earlier in the thread (though perhaps not thoroughly), see https://github.com/kubernetes/kubernetes/issues/42002#issuecomment-291759682

**Comment by k82cn** [comment]
> To allow bootstrapping a scheduler pod onto a cluster, there needs to be some type of controller that does not depend on the scheduler itself. Given that there has to be something that does it, I don't see why DaemonSet can't be that thing.

If using DaemonSet, we need to enhance DaemonSet to support start only one daemon (scheduler) on a set of nodes (master nodes).

**Comment by luxas** [comment]
That's not necessary, the scheduler is active/passive, so it can be deployed as a DS on all master nodes.

**Comment by k82cn** [comment]
I think it's usually part of master nodes, e.g. 3 scheduler in 5 master nodes, with other add-on, e.g. dashboard.

**Comment by aveshagarwal** [comment]
@k82cn I am not sure if this has been discussed. How will the scenario, where a DS' pod's node selector is updated in an admission plugin like PodNodeSelector, be handled? See this issue https://github.com/kubernetes/kubernetes/issues/51788

**Comment by k82cn** [comment]
@aveshagarwal , nop, I think there's no finial decision for now; maybe we can continue the discuss in 1.9. According to the [sig-apps backlog](https://docs.google.com/spreadsheets/d/1OoQtEFutS8vNhJtFpybBe5bklYkD-9alsaLTwNd_wzA/edit#gid=0), maybe @erictune have some suggestion to move forward :).

**Comment by erictune** [comment]
It is not going to be a good user experience if the daemonSet controller makes one pod for every node, and lets the scheduler decide which ones fit.  Then you end up with a bunch of pending pods, which is confusing to users, and perhaps extra load on the scheduler, and perhaps confusing for cluster auto scalers.

So, somehow, the daemonSet needs to know (modulo race conditions, taints, etc), how many pods to create.

Is there some way that the daemonSet can know which nodes likely match, and make pods for each node, and then still let the scheduler do a final fit check, etc.

Also, isn't scheduler performance going to be poor if it has to deal with a large number of pods with anti-affinity?

What can we do.

(BTW, I no longer thing the bootstrapping use case matters, so ignore this comment: https://github.com/kubernetes/kubernetes/issues/42002#issuecomment-314533980)

**Comment by bsalamat** [comment]
Given all the discussions around this topic, I am fine with letting DaemonSet controller keep its current behavior and schedule DaemonSet pods. As @erictune said, this has the benefit of reducing scheduler and auto-scaler load. It will also provide better guarantees that critical DaemonSet pods will be scheduled in a more predictable manner even in clusters where the default scheduler is replaced by a custom scheduler.
The obvious drawbacks are: 1) the DeamonSet controller needs to keep some of the cluster state in memory, as does scheduler, to check certain scheduling rules with reasonable throughput, 2) despite the fact that scheduler predicates are like a library that can be called by DaemonSet controller, there will be still more work maintaining some of the scheduling logic in both the scheduler and DaemonSet controller. We should especially be careful when adding new predicate functions and make sure they are added to the DaemonSet controller if needed.

**Comment by davidopp** [comment]
Just an observation: if we keep DaemonSet scheduling pods, then we will need to add some of the preemption logic to it  -- getting rid of the "critical pod rescheduler" is one of the motivations for having a general preemption mechanism. I say "some" because it doesn't need to decide which node to preempt on (since it wants to run on every node that meets the other constraints), but it does need to decide the correct minimal set of victims. Also, it is one more component that can delete pods.

**Comment by k82cn** [comment]
> It is not going to be a good user experience if the daemonSet controller makes one pod for every node, and lets the scheduler decide which ones fit. Then you end up with a bunch of pending pods, which is confusing to users, and perhaps extra load on the scheduler, and perhaps confusing for cluster auto scalers.

IMO, as an admin, I'll plan DaemonSet based on "static" setting, for example, I plan to start DaemonSet on 5 nodes (by nodeSelector), and maxUnavailable is 3; if it only start 2 pod because of resource, the rolling upgrade should be pending (it will break my QoS/SLA if terminating the only 2 available pod).

> Also, isn't scheduler performance going to be poor if it has to deal with a large number of pods with anti-affinity?

Maybe NodeAffinity :). Regarding the scheduler performance, I think there're some work we can do to improve it, e.g. https://github.com/kubernetes/kubernetes/issues/42002#issuecomment-306106033 vs https://github.com/kubernetes/kubernetes/issues/42002#issuecomment-306087380


Our doc said k8s support [multiple and user-provided schedulers](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/multiple-schedulers.md) but we did not give a suggestion on how those scheduler work together; there maybe several conflicts if dependent on kubelet.

And will customized scheduler have to handle scheduling features, e.g. Affinity, Taint/Tolerant, preemption? I'm not sure the impact if it does not follow :(.

**Comment by bsalamat** [comment]
As discussed in the mailing lists of sig-scheduling and sig-architecture, the final decision is to keep the current behavior of DaemonSet controller and let it schedule its own pods.

**Comment by davidopp** [comment]
In that case I guess we should close this.

BTW the thread @bsalamat refers to is here:
https://groups.google.com/d/msg/kubernetes-sig-scheduling/kMG7yfONwY4/Nx3abXuNAAAJ
