### ISSUE TITLE
Cut cAdvisor release for Kubernetes 1.6 release

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#42008]
To track the release ...

cc/ @kubernetes/sig-node-feature-requests

**Comment by dchen1107** [comment]
cAdvisor release doc: https://docs.google.com/document/d/102wNLDR9ls5NGRpBIfhQaD53q97DVLfmmuILLUE4AIk/edit

**Comment by dashpole** [comment]
completed via #42899 
/close
