### ISSUE TITLE
Don't silently ignore wrong cloud provider

### ISSUE THREAD

**Issue by bradbeam** [kubernetes/kubernetes#42013]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): cinder

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request
1.5: https://github.com/kubernetes/kubernetes/blob/release-1.5/pkg/volume/util/operationexecutor/operation_executor.go#L790
1.6: https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_generator.go#L387

Silently ignores errors that are thrown when interacting with the volume plugin. Specifically `wrong cloud provider` is ignored which leads to wasted time investigating why things aren't working.

**Kubernetes version** (use `kubectl version`): 1.5.3 / 1.6.0

**Environment**:
- **Cloud provider or hardware configuration**: Openstack
- **OS** (e.g. from /etc/os-release): Ubuntu Xenial
- **Kernel** (e.g. `uname -a`): Linux worker-01 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**: Kargo

**What happened**: Related to https://github.com/kubernetes/kubernetes/issues/34698#issuecomment-264708775, I had missed setting -cloud-provider +  -cloud-config in the kubelet configuration, but had them present in the controller-manager. This allowed the controller manager to provision storage and attach it to the appropriate worker node, however the worker node/kubelet didn't know about it. 

**What you expected to happen**: See log messages indicating that something is misconfigured

**How to reproduce it** (as minimally and precisely as possible): Configure api-server/controller-manager/etc manifests with `--cloud-provider=openstack --cloud-config=/etc/kubernetes/cloud_config` but leave this option out of the kubelet service.

**Comment by jamiehannaford** [comment]
At what point in the code is the `wrong cloud provider` error ignored? Looking at the two files you posted it seems they already handle errors appropriately?
