### ISSUE TITLE
Deleting current context in kubectl doesn't allow you to set a context

### ISSUE THREAD

**Issue by theckman** [kubernetes/kubernetes#42012]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No, this is a bug report.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

* `context was not found`
* `context was not found kubectl`
* `cannot set context`
* `cannot set context kubectl`
* `cannot select context`
* `cannot select context kubectl`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): **BUG REPORT**

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{
  Major:"1", Minor:"5", GitVersion:"v1.5.3",
  GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b",
  GitTreeState:"clean", BuildDate:"2017-02-17T20:48:54Z",
  GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: MacBook Pro Mid-2015
- **OS** (e.g. from /etc/os-release): macOS `10.11.6`
- **Kernel** (e.g. `uname -a`): `Darwin rinzler 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_6`
- **Install tools**: `homebrew`
- **Others**: N/A

**What happened**:
When deleting the context that was my current context, I entered a state where I am seemingly unable to set my context. The `kubectl config get-contexts` shows none as the current:
```
$ kubectl config set-context minikube
Context "minikube" set.
$ kubectl config get-contexts
CURRENT   NAME                   CLUSTER                AUTHINFO               NAMESPACE
          other                  other                  other                              
          minikube               minikube               minikube
```

Also, when trying to take any actions that require a context the following error is presented:
```
Error in configuration: context was not found for specified context: <deleted context name>
```

When viewing the full config (`kubectl config view`) I can see that my selected context is still the one I deleted. 

**What you expected to happen**:
I believe there are two expectations I had:

* `kubectl` should allow me to delete my current context, but not enter an inconsistent state in the process
-or-
* `kubectl` should either provide a warning or disallow removing your current context

**How to reproduce it** (as minimally and precisely as possible):
I believe that you just need a `kubectl` configuration with multiple contexts. I had three before deleting the context that has me unable to set a new context.

* list all `kubectl` contexts to find your current context (`kubectl config get-contexts`)
* delete your current context
* list your current contexts again, and you'll see no contexts are created
* try to set your context with one of the ones that exist (`kubectl config set-context <context that exists>`)
* listing your contexts again will show none being set

**Anything else we need to know**:
* 3 contexts were configured before starting to delete one
  * 2 of them were GKE clusters, automatically set up by the `gcloud` binary
  * 1 is a `minikube` context set up by `minikube`
* the context I deleted was one of the `GKE` contexts

The issue was resolved by manually setting my context by editing `~/.kube/config`.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-bugs

**Comment by smarterclayton** [comment]
I think this is the confusion of `kubectl config set-context` doesn't switch contexts, it lets you set fields on a context. `kubectl config use-context` is what switches contexts.

**Comment by smarterclayton** [comment]
It's technically valid to have no current context, but I agree a warning message like "warning: this removed your active context, use `kubectl config use-context` to select a different one" would go a long way.

**Comment by AdoHe** [comment]
SGTM.
