### ISSUE TITLE
vSphere Cloud Provider: unable to retrieve vm reference from vSphere

### ISSUE THREAD

**Issue by MattMencel** [kubernetes/kubernetes#42026]
BUG REPORT

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-17T20:48:54Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:

VMware 6.0

- **OS** (e.g. from /etc/os-release):

NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.9.0
VERSION_ID=1235.9.0
BUILD_ID=2017-02-02-0235
PRETTY_NAME="Container Linux by CoreOS 1235.9.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

- **Kernel** (e.g. `uname -a`):

Linux tectonic-controller 4.7.3-coreos-r2 #1 SMP Thu Feb 2 02:26:10 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz GenuineIntel GNU/Linux

- **Install tools**:

Matchbox and Tectonic Installer 1.5.2-tectonic.2

**What happened**:

I edited the bootkube asset files prior to deployment so that the apiserver and controller-manager would start with the vsphere cloud-provider.

**What you expected to happen**:

It would connect to vSphere, start the cluster, and I would be able to use dynamic PVs.

**How to reproduce it** (as minimally and precisely as possible):

Deploy using the Tectonic Installer.  Before starting the VMs, edit the ignition files so that the vsphere config deploys to /etc/kubernetes/vsphere/config.

Once controller is booted, and prior to pushing the asset zip file to the controller server, edit the assets/manifests/kube-apiserver.yaml and ...kube-controller-manager.yaml files. Add the hostPath volume mounts for the vsphere config and the cloud-provider and cloud-config settings.

Rezip the assets package and push to the controller using the instructions given by the Tectonic installer.

**Error Reported During Startup of the controller pod**

```
I0224 00:02:25.536730       1 leaderelection.go:247] lock is held by kube-controller-manager-3523772417-n5gsx and has not yet expired
I0224 00:02:28.776702       1 leaderelection.go:247] lock is held by kube-controller-manager-3523772417-n5gsx and has not yet expired
I0224 00:02:32.739514       1 leaderelection.go:188] sucessfully acquired lease kube-system/kube-controller-manager
I0224 00:02:32.741098       1 event.go:217] Event(api.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"kube-controller-manager", UID:"b05ac06e-fa1d-11e6-9d88-0050569a6c37", APIVersion:"v1", ResourceVersion:"5132", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' kube-controller-manager-3523772417-m2pzl became leader
I0224 00:02:32.781487       1 replication_controller.go:219] Starting RC Manager
F0224 00:02:33.080798       1 controllermanager.go:280] Cloud provider could not be initialized: could not init cloud provider "vsphere": unable to retrieve vm reference from vSphere
```

**Comment by kerneltime** [comment]
Can you post the vSphere config? Recent changes in the cloud provider needs UUID to be either accessible or set in the config file. https://github.com/kubernetes/kubernetes/blob/8e13ee01d6fdec17b2d370a7871fb0cd2564ae9a/pkg/cloudprovider/providers/vsphere/vsphere.go#L229
https://kubernetes.io/docs/getting-started-guides/vsphere/#configuring-vsphere-cloud-provider
```        vm-uuid = <VM Instance UUID of virtual machine which can be retrieved from instanceUuid property in VmConfigInfo, or also set as vc.uuid in VMX file. If empty, will be retrieved from sysfs (requires root)>
```

**Comment by kerneltime** [comment]
cc @BaluDontu @abrarshivani @divyenpatel @luomiao

**Comment by kerneltime** [comment]
@MattMencel are you on slack? If you need more help you can either reach out to us on slack

**Comment by MattMencel** [comment]
Did some more experimentation.  Tried adding the vm-uuid setting but it seems to not be supported on my version.

> Mar 02 21:48:01 tectonic-controller kubelet-wrapper[1275]: failed to run Kubelet: could not init cloud provider "vsphere": invalid variable: section "Global" subsection "" variable "vm-uuid"

vsphere.conf
```
[Global]
        user = "USER"
        password = "PASS"
        server = "vcenter"
        port = "443"
        insecure-flag = "true"
        datacenter = "My Datacenter"
        datastore = "Kube01"
        vm-uuid = "421AEC9F-56D2-8279-F9BE-3B89BE0EDFFA"
[Disk]
        scsicontrollertype = pvscsi
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-17T20:48:54Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2+coreos.2", GitCommit:"a94d2e8a306048aa45b3b60635ab44b0f3b25cd1", GitTreeState:"clean", BuildDate:"2017-02-04T02:14:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alekssaul** [comment]
Hi @MattMencel ,

We cut Tectonic 1.5.3-1 today. Docs and release notes should be synced soon and upgrade should be available in Tectonic console under Administration\Cluster Settings soon. 

If you still have the bandwidth to work on it, can you please try to upgrade ? Would be great to confirm if your changes survive the upgrade and if 1.5.3 vSphere cloudprovider configuration works.

**Comment by BaluDontu** [comment]
Over here you are using a kubernetes deployment with v1.5.2. We introduces the vm-uuid change in 1.5.3 version. 

Can you upgrade it to 1.5.3 and check it again.

**Comment by MattMencel** [comment]
I've gotten this working with Aleks' help.  I'll try to get my steps written up and put them in here shortly.

**Comment by MattMencel** [comment]
https://github.com/coreos/tectonic-installer/pull/639
