### ISSUE TITLE
flake: deployment_util_test.go TestFindOldReplicaSets failure

### ISSUE THREAD

**Issue by sjenning** [kubernetes/kubernetes#42021]
`/pkg/controller/deployment/util:go_default_test`

```
--- FAIL: TestFindOldReplicaSets (0.00s)
	deployment_util_test.go:605: In test case "Get old ReplicaSets with two new ReplicaSets, only the oldest new ReplicaSet is seen as new ReplicaSet", expected []*v1beta1.ReplicaSet{(*v1beta1.ReplicaSet)(0xc420204a80), (*v1beta1.ReplicaSet)(0xc420204380)}, got []*v1beta1.ReplicaSet{(*v1beta1.ReplicaSet)(0xc420204380), (*v1beta1.ReplicaSet)(0xc420204a80)}: <nil>
FAIL
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42009/pull-kubernetes-bazel/7072/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42010/pull-kubernetes-bazel/7035/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/38676/pull-kubernetes-bazel/7030/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41351/pull-kubernetes-bazel/7004/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/38924/pull-kubernetes-bazel/6988/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41234/pull-kubernetes-bazel/6982/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/38676/pull-kubernetes-bazel/6962/

**Comment by sjenning** [comment]
This is an ordering issue, the actual slice contains the expected elements, just not in the expected order, which I think doesn't matter for the purposes of passing the test.

**Comment by sjenning** [comment]
Introduced by https://github.com/kubernetes/kubernetes/pull/41851

**Comment by sjenning** [comment]
@janetkuo I see you have a fix already https://github.com/kubernetes/kubernetes/pull/41961

**Comment by janetkuo** [comment]
Fix is merged
