### ISSUE TITLE
kubeadm default microservice demo required much more memory 

### ISSUE THREAD

**Issue by netroby** [kubernetes/kubernetes#42027]
https://kubernetes.io/docs/getting-started-guides/kubeadm/

I tried to install kube cluster as the document guide. but while i tried to deploy microservice demo

```
As an example, install a sample microservices application, a socks shop, to put your cluster through its paces. Note that this demo does only work on amd64. To learn more about the sample microservices app, see the GitHub README.
# kubectl create namespace sock-shop
# kubectl apply -n sock-shop -f "https://github.com/microservices-demo/microservices-demo/blob/master/deploy/kubernetes/complete-demo.yaml?raw=true"
```
The create services was success. but if i have only 1GB memory as the kubeadm said

```bash
Prerequisites

One or more machines running Ubuntu 16.04+, CentOS 7 or HypriotOS v1.0.1+
1GB or more of RAM per machine (any less will leave little room for your apps)
Full network connectivity between all machines in the cluster (public or private network is fine)

```

The system became memory lack. and the load became very high

see my vps load
```bash
 00:22:17 up  9:41,  1 user,  load average: 99.31, 83.56, 63.53

```

I have 4GB memory on vps. but even lack of memory. 
```bash
              total        used        free      shared  buff/cache   available
Mem:           3951        3722          88          36         140          36
Swap:             0           0           0
```

This gave me a feeling.  

Kubernetes so slow. like a old bus.

So why not provided a more light weight microservice demo.

Like a wordpress site ? like a zencart or other demo?

Make kubeadm gettting start feel more amazing and fast.

**Comment by derekwaynecarr** [comment]
it looks like only 1 of the referenced microservices makes any resource requirements in its manifest.  we should ask that they size them.  or we can wait until node allocatable is rolled out this release and then system-reserved/kube-reserved will prevent end-user pods from using all your system memory.
