### ISSUE TITLE
CRI: after enable CRI feature on v1.5, unable to pull image for the sandbox container

### ISSUE THREAD

**Issue by jianzhangbjz** [kubernetes/kubernetes#42040]
Hi,

For test the CRI feature, we added the `--feature-gates=StreamingProxyRedirects=true` flag in apiserver and the `--experimental-cri=true` flag in kubelet. 
But got the errors of pull the image: `gcr.io/google_containers/pause-amd64:3.0`.
The image did exists in my node, so why still to execute `pull image` action? Why not detect the status of the image first before the pull? [code here](https://github.com/kubernetes/kubernetes/blob/release-1.5/pkg/kubelet/dockershim/docker_sandbox.go#L62) Or something else I missed?

```
root@slave2:~# docker images | grep pause
gcr.io/google_containers/pause-amd64                  3.0                                99e59f495ffa        9 months ago        746.9 kB
root@slave2:~# kubectl get pods
NAME      READY     STATUS              RESTARTS   AGE
nginx     0/1       ContainerCreating   0          1h
```
Errors:
```
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  1h		56s		69	{kubelet 9.186.50.250}			Warning		FailedSync	Error syncing pod, skipping: failed to "CreatePodSandbox" for "nginx_default(5192e527-fa5f-11e6-bf58-002186f14711)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx_default(5192e527-fa5f-11e6-bf58-002186f14711)\" failed: rpc error: code = 2 desc = unable to pull image for the sandbox container: Error response from daemon: {\"message\":\"Get https://gcr.io/v1/_ping: dial tcp 74.125.68.82:443: i/o timeout\"}"

  1h	42s	70	{kubelet 9.186.50.250}		Normal	SandboxReceived	Pod sandbox received, it will be created.
```

**Comment by Random-Liu** [comment]
/cc @yujuhong This is a regression.

Previously we use `EnsureImageExists` function in image manager https://github.com/kubernetes/kubernetes/blob/release-1.5/pkg/kubelet/dockertools/docker_manager.go#L1912, which will check local image existence before pulling.

However, the new implementation pulls image directly https://github.com/kubernetes/kubernetes/blob/release-1.5/pkg/kubelet/dockershim/docker_sandbox.go#L62.

I'll send a fix.

@jianzhangbjz Thanks for trying out and reporting the issue!

**Comment by jianzhangbjz** [comment]
@Random-Liu NP, it's my pleasure.

**Comment by reza-ebrahimi** [comment]
@Random-Liu  This feature still not working, previously I've pulled this image into my local, so kubectl tries to pull it from url and fails,

 
![a](https://cloud.githubusercontent.com/assets/11276982/26487780/2482e406-4216-11e7-961a-9319c83d515e.png)

![b](https://cloud.githubusercontent.com/assets/11276982/26487785/28cde998-4216-11e7-9b64-4150e7ee6fa8.png)
![c](https://cloud.githubusercontent.com/assets/11276982/26487788/2d78cf44-4216-11e7-96fa-471b5b2f04bb.png)

**Comment by reza-ebrahimi** [comment]
@reza-ebrahimi test

**Comment by Random-Liu** [comment]
@reza-ebrahimi I don't remember how does minikube works. It seems that they create a VM and run kubelet inside the VM?

Did you download the image inside the vm?

**Comment by reza-ebrahimi** [comment]
@Random-Liu No, I think my problem is docker images context that is located inside VM not the host system.

Thanks...

**Comment by m-bharathkrishna** [comment]
@reza-ebrahimi Am also trying to do the same inside the VM and could not pull. Can you help suggesting what fixed the issue for you?

**Comment by reza-ebrahimi** [comment]
if you run docker pull inside your VM it should just works without any
problem, I assume that there is no problems about internet connection of VM
or any proxy behind your connection inside VM, the problem of myself is I
was tried to pull it to docker's VM not the minikube VM, when you run
"minikube start" it will create a VM and put anything necessary about
kubernetes startup inside it, but when you use "docker pull" in Windows, it
will execute it inside docker's VM not the minikube VM,

a near workaround is change DOCKER_HOST ip address to minikube's VM that
docker daemon is running inside it and pull necessary images inside the
right VM, or just ssh to minikube's VM and use its own docker and pull
images, but consider that you should connect  VM to internet,

I think there is a third workaround here, use windows docker to pull
necessary images and save them as .tar files on your disk and load them
using ssh inside minikube's VM,

docker save <my_image> | ssh -C docker@minikubeVMip docker load

it will your image into the right VM and Kubernetes will actually just
works,


Reza

**Comment by reza-ebrahimi** [comment]
if you run docker pull inside your VM it should just works without any
problem, I assume that there is no problems about internet connection of VM
or any proxy behind your connection inside VM, the problem of myself is I
was tried to pull it to docker's VM not the minikube VM, when you run
"minikube start" it will create a VM and put anything necessary about
kubernetes startup inside it, but when you use "docker pull" in Windows, it
will execute it inside docker's VM not the minikube VM,

a near workaround is change DOCKER_HOST ip address to minikube's VM that
docker daemon is running inside it and pull necessary images inside the
right VM, or just ssh to minikube's VM and use its own docker and pull
images, but consider that you should connect  VM to internet,

I think there is a third workaround here, use windows docker to pull
necessary images and save them as .tar files on your disk and load them
using ssh inside minikube's VM,

`docker save <my_image> | ssh -C docker@minikubeVMip docker load`

it will your image into the right VM and Kubernetes will actually just
works,
