### ISSUE TITLE
hack/update-all.sh is not enough to pass make verify_generated_files

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#42051]
This happened to me in https://github.com/kubernetes/kubernetes/pull/39683.

I've run `hack/update-all.sh` and was hoping that **everything** needed was update. But during checks jenkins invokes `make verify` and that will fail on `make verify_generated_files`. Now running that locally (after all was updated), I'm getting:

```
$ make verify_generated_files 
F0224 15:40:55.035792    8763 main.go:44] Error: Failed executing generator: some packages had errors:
errors in package "k8s.io/kubernetes/pkg/generated/openapi":
output for "openapi/zz_generated.openapi.go" differs; first existing/expected diff: 
  "apps/v1beta1.Deployment\": {\n\t\t\tSchema: spec.Schema{\n\t\t\t\tSchemaProps: spec.SchemaProps{\n\t\t\t\t\tDescript"
  "extensions/v1beta1.Deployment\": {\n\t\t\tSchema: spec.Schema{\n\t\t\t\tSchemaProps: spec.SchemaProps{\n\t\t\t\t\tDe"

Makefile.generated_files:502: recipe for target 'verify_gen_openapi' failed
make[1]: *** [verify_gen_openapi] Error 1
Makefile:467: recipe for target 'verify_generated_files' failed
make: *** [verify_generated_files] Error 2
```

Now the question is what am I supposed to run to have that generated?

@kubernetes/sig-api-machinery-misc ideas?

**Comment by k82cn** [comment]
similar issues with #41866

**Comment by soltysh** [comment]
@mbohlool I was told you can be of help :)

**Comment by soltysh** [comment]
@mbohlool I did more investigation and it looks like the order in which packages are processed is not stable. It can be easily tracked down, if you run `KUBE_VERBOSE=5 DBG_MAKEFILE=1 make generated_files` vs `KUBE_VERBOSE=5 DBG_MAKEFILE=1 make verify_generated_files` on that PR of mine you'll see the order differ and that is causing problems.
