### ISSUE TITLE
Short name for statefulset, statefulsets and thirdpartyresources in CLI

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#42129]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

```
[root@bd002 wordpress]# kubectl get
You must specify the type of resource to get. Valid resource types include:

    * clusters (valid only for federation apiservers)
    * componentstatuses (aka 'cs')
    * configmaps (aka 'cm')
    * daemonsets (aka 'ds')
    * deployments (aka 'deploy')
    * endpoints (aka 'ep')
    * events (aka 'ev')
    * horizontalpodautoscalers (aka 'hpa')
    * ingresses (aka 'ing')
    * jobs
    * limitranges (aka 'limits')
    * namespaces (aka 'ns')
    * networkpolicies
    * nodes (aka 'no')
    * persistentvolumeclaims (aka 'pvc')
    * persistentvolumes (aka 'pv')
    * pods (aka 'po')
    * podsecuritypolicies (aka 'psp')
    * podtemplates
    * replicasets (aka 'rs')
    * replicationcontrollers (aka 'rc')
    * resourcequotas (aka 'quota')
    * secrets
    * serviceaccounts (aka 'sa')
    * services (aka 'svc')
    * statefulsets
    * storageclasses
    * thirdpartyresources
    error: Required resource not specified.
Use "kubectl explain <resource>" for a detailed description of that resource (e.g. kubectl explain pods).
See 'kubectl get -h' for help and examples.
```

The name of `statefulsets`, `storageclasses`, `thirdpartyresources` is too long and it is not convenient to use CLI to operated on those resources, and better have some short names as others.

One proposal is 

```
    * services (aka 'svc')
    * statefulsets  (aka 'ss')
    * storageclasses  (aka 'sc')
    * thirdpartyresources  (aka 'tpr')
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by hjacobs** [comment]
I think the short name for `thirdpartyresources` should be `tpr` as they are usually referred to with "TPR".

**Comment by gyliu513** [comment]
Good comments, thanks @hjacobs , updated the description accordingly. ;-)

**Comment by gyliu513** [comment]
Refer to #42241 & #37099

**Comment by julianvmodesto** [comment]
This is done with https://github.com/kubernetes/kubernetes/pull/45595
