### ISSUE TITLE
Storage Provisioning: False message indicating Volume Provisioning Failed when using external Dynamic Provisioners

### ISSUE THREAD

**Issue by sandaymin123** [kubernetes/kubernetes#42121]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

**Storage Plugin/PV Controller**

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
**BUG**

**Kubernetes version** (use `kubectl version`):
1.5.2

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):ubuntu
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

In testing of an external Dynamic Provisioner, the first message/status is shown is the following. This gives the user the "false sense of failure, while in fact the external provisioner is still "in-progress...processing the request.

_2m 2m 3 {persistentvolume-controller } Normal ExternalProvisioning cannot find provisioner "ubiquity/flex", expecting that a volume for the claim is provisioned either manually or via external software_

The event in question is something that PV_Controller (part of k8s distribution) adds if it can't find an existing pv matching new pvc's requirements. Dynamic provisioner runs as a separate process (outside k8s) and can only add new events -- not change existing events in k8s. Hence we see multiple messages(events)

**What you expected to happen**:
At a minimum, the error message should change to be something more generic when "external" provisioners are utilized and ONLY POST 1 message

(EG. "waiting for external provisioner "foo/test" to provision a volume or creating a volume mannually for the claim)

**How to reproduce it** (as minimally and precisely as possible):
Use the an external provisioner (i.e NFS Example or create a new one...). Observe the first message from PV Controller. Then wait for the Dynamic Provisioner to finish provisioning which will change the status of the PVC to be be BOUND

**Anything else we need to know**:

**Comment by jsafrane** [comment]
@kubernetes/sig-storage-bugs

**Comment by jsafrane** [comment]
The event message can be fixed easily, I am not sure if it's a good idea to sent the event only once. Are events always delivered? Can they get lost? @saad-ali, @thockin.
