### ISSUE TITLE
Federation: "InvalidChangeBatch: Duplicate Resource Record" error while configuring Route53

### ISSUE THREAD

**Issue by crigor** [kubernetes/kubernetes#42131]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

InvalidChangeBatch

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report.

**Kubernetes version** (use `kubectl version`):

1.5.1

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS
- **Kernel** (e.g. `uname -a`): `Linux ip-172-20-4-64 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**: Custom
- **Others**:

**What happened**:

I have 2 clusters in aws, 1 in us-east-1 and 1 in us-east-2. I set up cluster federation using https://github.com/kelseyhightower/kubernetes-cluster-federation as my guide.

I created a replica set with 4 replicas of nginx. 2 ran on each of the 2 regions. All good.

I created a service, the federation controller manager created CNAMES for nginx4.default.federation.svc.us-east-1.federation.com and nginx4.default.federation.svc.us-east-2.federation.com. This looks correct.

Eventually nginx4.default.federation.svc.us-east-1.federation.com was changed to an A record when the endpoints became healthy while nginx4.default.federation.svc.us-east-2.federation.com remained a CNAME.

This is the error from federation-controller-manager 1.5.3 (I also tried 1.5.1).

I0226 07:47:30.273951       1 dns.go:237] Recordset &{0xc421552a80 0xc4202da4d8} already exists.  Ensuring that it is correct.
I0226 07:47:30.273981       1 dns.go:268] nginx4.default.federation.svc.us-east-2a.us-east-2.federation.com.: Healthy endpoints [ae0cf9867fbf611e6954b023f939bc0f-805436699.us-east-2.elb.amazonaws.com ae0cf9867fbf611e6954b023f939bc0f-805436699.us-east-2.elb.amazonaws.com] exist.  Recordset &{0xc421552a80 0xc4202da4d8} exists.  Reconciling.
I0226 07:47:30.301127       1 dns.go:274] Have recordset &{0xc421552a80 0xc4202da4d8}. Need recordset {0xc421553500 0xc420ef8340}
I0226 07:47:30.301156       1 dns.go:282] Existing recordset &{0xc421552a80 0xc4202da4d8} is not equivalent to needed recordset {0xc421553500 0xc420ef8340}, removing existing and adding needed.
I0226 07:47:30.362002       1 service_helper.go:120] Error ensuring DNS Records for service default/nginx4 on cluster additionalzonesftw: InvalidChangeBatch: Duplicate Resource Record: 52.14.105.135
	status code: 400, request id: d35e1156-fbf7-11e6-b1d9-afb55cf95a01

Notice the 2 healthy endpoints are for the same ELB `ae0cf9867fbf611e6954b023f939bc0f-805436699...` Could this be the cause of `InvalidChangeBatch: Duplicate Resource Record`?

**What you expected to happen**:

I expected nginx4.default.federation.svc.us-east-2.federation.com to be an A record instead of CNAME.

**How to reproduce it** (as minimally and precisely as possible):

Set up cluster federation on AWS. Create a replica set. Create a service.

**Anything else we need to know**:

**Comment by shashidharatd** [comment]
related issues  #35637  #36757

**Comment by matt-potter** [comment]
Hi! We see the exact same issue on 1.6.2. Using kubefed to create a federation control plane, and then joining the the host cluster to the federation. Deploy a RS and a Loadbalancer service, and this leads to both the service in the federation cluster context and the service in the host cluster context referencing the same ELB address (is this correct behaviour?). I can see the controller manager detecting the same endpoint multiple times and trying to add entries to a route53 record, which fails as it contains duplicate values: 

I've replaced some of the values in the log, but the LOADBALANCER-***... entries are all the same ELB.

I0503 15:22:50.057373       1 dns.go:225] Recordset &{0xc4215600e0 0xc42048f3d8} already exists.  Ensuring that it is correct.

```
I0503 15:22:50.057403       1 dns.go:256] nginx-fed.default.federated.svc.eu-west-1a.eu-west-1.*******.: Healthy endpoints [LOADBALANCER-***.eu-west-1.elb.amazonaws.com LOADBALANCER-***.eu-west-1.elb.amazonaws.com LOADBALANCER-***.eu-west-1.elb.amazonaws.com] exist.  Recordset &{0xc4215600e0 0xc42048f3d8} exists.  Reconciling.

I0503 15:22:50.135302       1 dns.go:262] Have recordset &{0xc4215600e0 0xc42048f3d8}. Need recordset {0xc4214b6af0 0xc42048f488}

I0503 15:22:50.135343       1 dns.go:270] Existing recordset &{0xc4215600e0 0xc42048f3d8} is not equivalent to needed recordset {0xc4214b6af0 0xc42048f488}, removing existing and adding needed.

I0503 15:22:50.135584       1 route53.go:50] AWS request: route53 ChangeResourceRecordSets

I0503 15:22:50.273914       1 endpoint_helper.go:161] Error ensuring DNS Records: InvalidChangeBatch: Duplicate Resource Record: ***IP ADDRESS***
	status code: 400, request id: 5e8ae720-3014-11e7-94d1-99d1a5bc81fa
```

**Comment by nikhiljindal** [comment]
I do not understand the issue here.
I do not see a scenario where federation will try to create multiple DNS records resolving to same IP address.

> from @matt-potter 
> this leads to both the service in the federation cluster context and the service in the host cluster context referencing the same ELB address (is this correct behaviour?)

I am not too familiar with our type=LoadBalancer service implementation on AWS, but does that create Route53 DNS records?
If yes, then I can see how that can cause a problem if Route53 does not allow creating multiple DNS records resolving to the same IP address.
But then @crigor said DNS worked fine for him in zone `us-east-1`, which should not have happened?

**Comment by matt-potter** [comment]
@nikhiljindal Apologies, I forgot to link in my PR - but this one I submitted and is currently open resolves this issue I believe. It only occurs when a cluster spans multiple availability zones in the same region. https://github.com/kubernetes/kubernetes/pull/45492

**Comment by nikhiljindal** [comment]
Thanks @matt-potter That PR seems to target multi-zone clusters. The original description on this issue talks about single-zoned clusters (2 clusters, one each in `us-east-1` and `us-east-2`).

Can you briefly explain what you think the issue here is? Describe a scenario where federation will try to create multiple DNS records resolving to same IP address.

**Comment by matt-potter** [comment]
@nikhiljindal The implication from the log in the initial issue report from @crigor is that the cluster in us-east-2 does in fact span multiple zones. The output from reads `Healthy endpoints [ae0cf9867fbf611e6954b023f939bc0f-805436699.us-east-2.elb.amazonaws.com ae0cf9867fbf611e6954b023f939bc0f-805436699.us-east-2.elb.amazonaws.com] exist` and that is generated by the getHealthyEndpoints function here: https://github.com/kubernetes/kubernetes/blob/master/federation/pkg/federation-controller/service/dns.go#L224 The only way, as far as I can tell, that you will get duplicate entries in the returned array is if the same ELB (and therefore cluster) spans multiple availability zones. 

Essentially, the federation controller iterates over the endpoints per zone (here https://github.com/kubernetes/kubernetes/blob/master/federation/pkg/federation-controller/service/dns.go#L262), but in a multi zone environment you will get the same ELB address in each zone, resulting in the duplicates in the returned array.

**Comment by quinton-hoole** [comment]
We don't support federation of multi-zone clusters at the moment.  There are several similar issues.  If anyone can present some useful use-cases for federating multi-zone clusters, I will re-prioritize this, otherwise it goes on the backlog as a nice-to-have.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#105.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
