### ISSUE TITLE
Azure Windows Container exposed endpoints are not accessible

### ISSUE THREAD

**Issue by garrardkitchen** [kubernetes/kubernetes#42151]
Hi,

Friday and today I created a Kubernetes container service in Azure targeting windows containers.  Both times the exposed service has not been accessible.  The IP:port combinations show up in the External endpoints column e.g. `kubectl get svc` but when I click on link it fails to find site.  If I exec into each pod (after downloading credentials) and perform an exec and a run powershell curl e.g. `kubectl exec {pod_id} powershell "curl 'http://localhost' -UseBasicParsing"` I get 200 and a valid response.

It runs locally on windows 10 (docker for windows). 

**I'm using all the latest bits.** and have followed all the instructions!

To really strip back everything I have used a basic container that has one html page (base: microsoft/aspnet).

You can see this by using image garrardkitchen/test (exposes port 8001):
```
docker run -p 8001:8001 --name test -d garrardkitchen/test
```
and to get container ip (I'm using windows containers here don't forget) I perform:
```
docker inspect -f "{{ .NetworkSettings.Networks.nat.IPAddress }}" test
```

then load this ip address into the browser and it works as per (you will see **TEST 123!!!**)

Any ideas as to why endpoints are inaccessible?

Warmest regards,

Garrard.

**Comment by vriesmarcel** [comment]
I see almost the same. Only the fist time when I expose a service it works, but any service after this is not accessible from outside. 
Simple steps to reproduce:
kubctl create deployment iis --image=microsoft/iis
kubectl expose iis --port=80 --type=LoadBalancer

now browser tot the port you get when you list the services
this works.
Next create a new deployment, same image other name
expose this with same command, this service will not b accessible

**Comment by colemickens** [comment]
cc: @anhowe @JiangtianLi PTAL

**Comment by JiangtianLi** [comment]
@vriesmarcel I deployed 3 iis services in a row and each of them can be accessed outside the cluster via external IP. Did you use ACS engine to deploy k8s? If so, what is the HEAD in your local repo?
@garrardkitchen Were you able to curl cluster IP or pod IP? One possible cause is Windows firewall public profile.

**Comment by garrardkitchen** [comment]
Hi @JiangtianLi, yes, i couldn't​ reach either. I did check vm firewall and nsg rules. Both ok.

**Comment by mfaizanse** [comment]
@JiangtianLi Just to add here that deploying more services in a row (without deleting the first one) does not causes any issues.

**Comment by vriesmarcel** [comment]
I used the portal to deploy the cluster.
Created a new cluster Friday, same issue. when using expose the services are not available from the public IP

**Comment by JiangtianLi** [comment]
@vriesmarcel What service have you deployed? Is it accessible from Windows node?
@mfaizanse We have fixed the issue of deleting service recently.

**Comment by vriesmarcel** [comment]
Let me check the connectivity on the windows node itself. I only checked from outside of azure (my local machine to the service)

**Comment by feiskyer** [comment]
@garrardkitchen  @vriesmarcel Which version of kubernetes are you deploying? Just checked v1.8 has no such problem.

**Comment by vriesmarcel** [comment]
On latest version it now works

**Comment by jdumars** [comment]
Closing as resolved.
