### ISSUE TITLE
./cluster/kube-up.sh shows certificate issues

### ISSUE THREAD

**Issue by 030** [kubernetes/kubernetes#42150]
```
==> master: ----------
==> master:           ID: /var/lib/kubelet/ca.crt
==> master:     Function: file.managed
==> master:       Result: False
==> master:      Comment: Source file salt://kubelet/ca.crt not found
==> master:      Started: 10:25:50.407399
==> master:     Duration: 0.826 ms
==> master:      Changes:   
==> master: ----------
==> master:           ID: kubelet
==> master:     Function: service.running
==> master:       Result: False
==> master:      Comment: One or more requisite failed: kubelet./var/lib/kubelet/ca.crt
==> master:      Started: 
==> master:     Duration: 
==> master:      Changes:   
==> master: ----------
==> master:           ID: /etc/kubernetes/manifests/kube-apiserver.manifest
==> master:     Function: file.managed
==> master:       Result: False
==> master:      Comment: One or more requisite failed: kubelet.kubelet
==> master:      Started: 
==> master:     Duration: 
==> master:      Changes:
```

**Comment by 030** [comment]
I had to follow the instructions from https://github.com/kubernetes/community/blob/master/contributors/devel/local-cluster/vagrant.md

**Comment by Cytrian** [comment]
Hi, I'm getting the same errors when using the v1.6.4 release of kubernetes.
But it works with the older v1.5.7 release. Which one did you use?
Can you retry it with a newer one?

**Comment by prabhakm** [comment]
I have this issue as well and salt provisioning gets into infinite loop
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
