### ISSUE TITLE
Remove ABAC enable transition flag

### ISSUE THREAD

**Issue by jcbsmpsn** [kubernetes/kubernetes#42198]
An option to write an ABAC configuration file during cluster creation was created as part of 1.6 to allow for an easier user transition experience. That code should be removed when no longer needed.

https://github.com/kubernetes/kubernetes/pull/42197

**Comment by liggitt** [comment]
reverted in b95f5286c15968ccd47f574dbebfe6831d77c404, file is still generated when abac is requested, abac is disabled by default in 1.8
