### ISSUE TITLE
The CNI shim should use a stable network.

### ISSUE THREAD

**Issue by squeed** [kubernetes/kubernetes#42190]
Right now, the CNI network plugin chooses which CNI network (also confusingly referred to as a "plugin") by opening the **alphabetically-first configuration file on disk**. It also rescans for configuration files every 10 seconds.

This is obviously non-optimal. The CNI shim should use a stable network. However, we do have to deal with the fact that the desired configuration file may not exist at startup time.

Therefore, either we should
1) add a new CNI-specific command-line flag, defaulting to the old behavior if not provided.
2) Scan all the available network files and present them as kubernetes networking plugins directly, e.g. a network called "mybridge" is enabled via `--network-plugin=mybridge`

**Comment by squeed** [comment]
cc @freehan @dcbw

**Comment by freehan** [comment]
I feel like this is related to the mutli-network work, which is still in design phase. Say if k8s supports multiple networks, the actual implementation can be decided by the network plugin. 

For CNI network plugin, a k8s network resource can correspond to a cni network config.
Say if k8s have a docker-network network plugin, then a k8s network can match a docker network. 

Does it sounds reasonable?

**Comment by squeed** [comment]
That does indeed sound reasonable, but what's the timeline for multi-network?

We'll need something like this if we move kubenet to a CNI plugin chain.

**Comment by freehan** [comment]
Say if there are a bunch of CNI plugins that cover all bells and whistles of kubenet. We can chain them in one CNI network config and use it with today's CNI network plugin right? 

Why do you think multi-network is the prerequisite for replacing kubenet?

**Comment by squeed** [comment]
For sure! I misspoke - I meant that we need some kind of stable cni network selection algorithm if we move kubenet to CNI.

**Comment by freehan** [comment]
Got you. Without a network selection mechanism, then we basically can only consume one cni network config.

**Comment by squeed** [comment]
Specifically, my proposal would be:

* no `--network-plugin`: current default (kubenet)
*  `--network-plugin=cni`: use current "floating" logic
* `--network-plugin=mybridge`: find CNI network called `mybridge`

This should keep it simple until multinet is further along.

**Comment by freehan** [comment]
Since `--network-plugin` is currently a kubelet flag, there is no good way to update it at run time. Then there is not much difference with cni network plugin reading one cni network config from cni-dir, right?

We just need to be explicit in the document about this assumption, right?

**Comment by caseydavenport** [comment]
/area kubelet

> I meant that we need some kind of stable cni network selection algorithm if we move kubenet to CNI

I think we already meet this requirement, right?  kubelet uses the lexicographically first CNI network config file from disk, which is a deterministic selection algorithm.

> We just need to be explicit in the document about this assumption, right?

Yep.
