### ISSUE TITLE
Make sure users of TPR and apply have a workable solution for 1.5

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#42207]
Prior to k8s 1.5, `kubectl apply` would replace TPRs instead of throwing an error.  In 1.5, how objects were parsed was changed in a way that caused `kubectl apply` to throw an error instead of replacing TPRs.

Some users depend upon kubectl apply being able to update TPRs, and in 1.6 TPR support is formally supported in apply.  We still need a workaround in 1.5 to allow users depending on TPRs being updated by apply to upgrade their clusters to 1.5 without rewriting their deployment infrastructure.

cc @huggsboson

**Comment by liggitt** [comment]
I don't think backporting generic object support to 1.5 kubectl is a good idea. The changes are extensive.

**Comment by ymqytw** [comment]
We want to stop `apply` from failing when apply on TPR by making apply on TPR alway replacing
We are not going to backport generic object support to 1.5.

**Comment by liggitt** [comment]
I consider the previous behavior of silently replacing entire TPR objects a data loss issue. 

Obviously, we'd prefer apply work properly in 1.5, but if we have to choose, I'd take *not* overwriting user data and use `replace` as a workaround until generic support arrives in 1.6 over appearing to successfully apply while actually stomping.

**Comment by huggsboson** [comment]
@ahakanbaba

**Comment by huggsboson** [comment]
so is the proposed work around using kubectl replace on TPR's until we move to 1.6?

**Comment by liggitt** [comment]
> so is the proposed work around using kubectl replace on TPR's until we move to 1.6?

that would be my recommendation, yes.

**Comment by huggsboson** [comment]
This works for us, we'll find a way to hack up our deployment pipeline to make replace work.

**Comment by pwittrock** [comment]
@huggsboson Closing this for now.  Reopen if you are not able to get a workable solution.
