### ISSUE TITLE
Jenkins unit/integration failure

### ISSUE THREAD

**Issue by shouhong** [kubernetes/kubernetes#42219]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): unit/integration

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): N/A

**Environment**: N/A
- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): N/A
- **Kernel** (e.g. `uname -a`): N/A
- **Install tools**: N/A
- **Others**: N/A

**What happened**:
Jenkins unit/integration failed

**What you expected to happen**:
Jenkins unit/integration success

**How to reproduce it** (as minimally and precisely as possible):
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41380/pull-kubernetes-unit/20578/
Errors:
Error: invalid argument "foobar" for --discovery=foobar: unknown discovery scheme
Error: unknown flag: --dicovery

**Anything else we need to know**:
It seems this error was introduced by "kubernetes/cmd/kubeadm/test/cmd/join_test.go". 
Related code in this file:
      var initTest = []struct {
		args     string
		expected bool
	}{
		{"--discovery=foobar", false},
		{"--dicovery=magic", false},
	}

**Comment by shouhong** [comment]
@dmmcquay Hi, Derek, can you please help check this issue? It seems it was introduced by "kubernetes/cmd/kubeadm/test/cmd/join_test.go". Thanks!

**Comment by ncdc** [comment]
@shouhong the actual error is `W0227 19:00:07.913] error: the path "examples/storage/redis/redis-proxy.yaml" does not exist`, which appears to have been introduced by your PR, which deleted that file (https://github.com/kubernetes/kubernetes/pull/41380/files#diff-a73c9be2b7a1d413fe212da30a9a2dcd). Please review and close if you agree.

**Comment by shouhong** [comment]
@ncdc Thanks for your finding. I have updated the PR for this problem and closed this issue.
