### ISSUE TITLE
Some edits can drop users out of kubectl edit

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#42217]
Edit a pod, add:

```
env:
- name: A
  value: 1
- name: B
  value: 2
```

This should give me a validation error, but instead it causes a patch error (value must be a string) and kicks me out.  Very bad.

```
kubectl edit pod/nginx
error: pods "nginx" could not be patched: [pos 371]: json: expect char '"' but got char '1'
You can run `kubectl replace -f /var/folders/zw/j6656mbn1rv4fnqqdggss8h80000gn/T/kubectl-edit-fplln.yaml` to try this update again.
```

**Comment by pwittrock** [comment]
@ymqytw Can you take a look at this?

**Comment by ymqytw** [comment]
Should we quote the number?
```yaml
env:
- name: A
  value: "1"
- name: B
  value: "2"
```

**Comment by pwittrock** [comment]
I wonder if this is related to using UnstructuredObject in edit instead of round tripping through go structs.  I am not sure how the yaml could be converted to json in an unambiguous way without the type schema.

**Comment by pwittrock** [comment]
@smarterclayton I think maybe it shouldn't give a validation error, and instead should just work.

**Comment by ymqytw** [comment]
This is not a regression. Same issue happens in 1.4.9 and 1.5.3.

**Comment by pwittrock** [comment]
@ymqytw Thanks for checking on that.  Lets start thinking about a solution.

**Comment by smarterclayton** [comment]
So I want to move JSON validation to the server side, and we probably want
patch to respond with an an invalid structural error when the types don't
match (it should return 422 Invalid if the patch itself is structurally
unsound).

**Comment by pwittrock** [comment]
@smarterclayton Moving validation to server side sounds like a good general solution.  Do you have  preference for what we do (if anything) for 1.6?

**Comment by smarterclayton** [comment]
I don't know that this is is important enough to fix for 1.6 since it's
fairly complicated to get right.  I don't think the incremental fix helps
enough people to justify the cost.

**Comment by ymqytw** [comment]
Should we remove the 1.6 milestone?

**Comment by smarterclayton** [comment]
I'm fine with that

**Comment by cben** [comment]
see also related #26050

**Comment by spiffxp** [comment]
/remove-priority P1
removing old priority/PN labels, this already has priority/important-soon

**Comment by brianpursley** [comment]
I think this might be fixed now.

Using the steps in the issue description, when I save the changes, it immediately reloads vim with the following message at the top:

```
#
# pods "nginx" was not valid:
# * patch: Invalid value: "map[spec:map[]]": cannot convert int64 to string
#
```

I tried several versions of kubectl back to 1.15.11, so I'm not sure at what point this might have been fixed.

**Comment by soltysh** [comment]
As Brian put it it's working as expected.
/close
