### ISSUE TITLE
Make bind port zero work with kube-apiserver

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#42224]
The generic apiserver can bind to a zero port. The kernel will select a free port to listen to automatically and the apiserver serveSecurely/serveInsecurely logic writes it back to `GenericAPIServer.effectiveInsecurePort`. This can be used in tests to start multiple independent apiservers.

The start-up logic of the kube-apiserver makes this impossible to use because clients are created before the server has actually started to serve and gotten a real port.

**Comment by MHBauer** [comment]
I'd like to have this for the apimachinery reuse. I'd like to give it a zero and be able to get the port after I start the server. I do not understand the issue discussed in the PR, but I accept that it blocks.

**Comment by sttts** [comment]
Fixed by https://github.com/kubernetes/kubernetes/issues/55784.

@MHBauer what do you mean with "for the apimachinery reuse"?
