### ISSUE TITLE
Missing gcr.io/google_containers/kube-discovery-ppc64le docker image

### ISSUE THREAD

**Issue by mkumatag** [kubernetes/kubernetes#42234]
gcr.io/google_containers/kube-discovery-ppc64le docker image is missing because of that kubeadm is not able to bring up the cluster on ppc64le platform. I see image is available for amd64, arm and arm64 platform but missing for ppc64le

**Comment by mkumatag** [comment]
\cc @ixdy @luxas

**Comment by ixdy** [comment]
@luxas should I push this image (and ppc64le and whatever else is missing)? IIUC kube-discovery is going away so I'm not sure what's most correct here.

**Comment by mkumatag** [comment]
@ixdy Can we push this image meanwhile to make it work?

**Comment by luxas** [comment]
@ixdy I think we can just close this issue, you don't need to push (or can't actually).
ppc64le wasn't supported in v1.5 when we used the kube-discovery image. In v1.6 we don't anymore, where ppc64le is supported.

See: https://github.com/kubernetes/kubernetes/pull/42070, https://github.com/kubernetes/kubernetes/pull/41417 and https://github.com/kubernetes/community/blob/master/contributors/design-proposals/bootstrap-discovery.md

@mkumatag If you download/compile kubeadm from HEAD, it should work on ppc64le

**Comment by mkumatag** [comment]
okay..
