### ISSUE TITLE
Docker 1.13 breaks networking

### ISSUE THREAD

**Issue by ash-man** [kubernetes/kubernetes#42243]
Hi, 

I spent few last days fighting with KubeDNS and finally decided to write up here as all my ideas how to solve it were finished. I have also red a lot off stuff related to this issue but even if I did a  lot of changes, adjustements I still have an issue. 

First of all, I'm using kubernetes on CentOS from official packages 1.4

Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"87d9d8d7bc5aa35041a8ddfe3d4b367381112f89", GitTreeState:"clean", BuildDate:"2017-01-23T14:15:25Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"87d9d8d7bc5aa35041a8ddfe3d4b367381112f89", GitTreeState:"clean", BuildDate:"2017-01-23T14:15:25Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

I've configured (I hope properly) all services on master and minions sides. I'm using secure CA/keys for communication between master and nodes and it seems to work properly. I do not see any issues when services kube-apiserver, kube-controller-manager, kube-scheduler start. 

Kubedns, dnsmasq, sidecar are created w/o any issues. Here is output from logs taken from kubedns container
kubectl --namespace=kube-system logs  kube-dns-2408966145-8oz8t -c kubedns
I0228 12:43:27.094834       1 dns.go:49] version: v1.5.2-beta.0+$Format:%h$
I0228 12:43:27.096634       1 server.go:70] Using configuration read from directory: /kube-dns-config%!(EXTRA time.Duration=10s)
I0228 12:43:27.096688       1 server.go:110] FLAG: --alsologtostderr="false"
I0228 12:43:27.096706       1 server.go:110] FLAG: --config-dir="/kube-dns-config"
I0228 12:43:27.096719       1 server.go:110] FLAG: --config-map=""
I0228 12:43:27.096726       1 server.go:110] FLAG: --config-map-namespace="kube-system"
I0228 12:43:27.096732       1 server.go:110] FLAG: --config-period="10s"
I0228 12:43:27.096742       1 server.go:110] FLAG: --dns-bind-address="0.0.0.0"
I0228 12:43:27.096749       1 server.go:110] FLAG: --dns-port="10053"
I0228 12:43:27.096759       1 server.go:110] FLAG: --domain="cluster.local."
I0228 12:43:27.096770       1 server.go:110] FLAG: --federations=""
I0228 12:43:27.096779       1 server.go:110] FLAG: --healthz-port="8081"
I0228 12:43:27.096788       1 server.go:110] FLAG: --initial-sync-timeout="1m0s"
I0228 12:43:27.096796       1 server.go:110] FLAG: --kube-master-url=""
I0228 12:43:27.096808       1 server.go:110] FLAG: --kubecfg-file=""
I0228 12:43:27.096815       1 server.go:110] FLAG: --log-backtrace-at=":0"
I0228 12:43:27.096824       1 server.go:110] FLAG: --log-dir=""
I0228 12:43:27.096832       1 server.go:110] FLAG: --log-flush-frequency="5s"
I0228 12:43:27.096838       1 server.go:110] FLAG: --logtostderr="true"
I0228 12:43:27.096847       1 server.go:110] FLAG: --nameservers=""
I0228 12:43:27.096855       1 server.go:110] FLAG: --stderrthreshold="2"
I0228 12:43:27.096863       1 server.go:110] FLAG: --v="2"
I0228 12:43:27.096871       1 server.go:110] FLAG: --version="false"
I0228 12:43:27.096894       1 server.go:110] FLAG: --vmodule=""
I0228 12:43:27.097036       1 server.go:173] Starting SkyDNS server (0.0.0.0:10053)
I0228 12:43:27.097562       1 server.go:195] Skydns metrics enabled (/metrics:10055)
I0228 12:43:27.097586       1 dns.go:147] Starting endpointsController
I0228 12:43:27.097596       1 dns.go:150] Starting serviceController
I0228 12:43:27.097965       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0228 12:43:27.097995       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0228 12:43:27.399790       1 dns.go:264] New service: kubernetes
I0228 12:43:27.399991       1 dns.go:462] Added SRV record &{Host:kubernetes.default.svc.cluster.local. Port:443 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I0228 12:43:27.400071       1 dns.go:264] New service: kube-dns
I0228 12:43:27.400122       1 dns.go:462] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I0228 12:43:27.400166       1 dns.go:462] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I0228 12:43:27.597864       1 dns.go:171] Initialized services and endpoints from apiserver
I0228 12:43:27.597910       1 server.go:126] Setting up Healthz Handler (/readiness)
I0228 12:43:27.597922       1 server.go:131] Setting up cache handler (/cache)
I0228 12:43:27.597931       1 server.go:117] Status HTTP port 8081

I have also setup --cluster-dns=10.254.0.10 --cluster-domain=cluster.local on kubelet side and these also seem to work properly. 

As you may know I've created busybox to check connectivity and resolver of my kubeDNS and here is a problem: 

# kubectl exec -it busybox -- nslookup busybox
Server:    10.254.0.10
Address 1: 10.254.0.10 kube-dns.kube-system.svc.cluster.local

Name:      busybox
Address 1: 172.30.98.2 busybox

# kubectl exec -it busybox -- nslookup kubernetes
Server:    10.254.0.10
Address 1: 10.254.0.10 kube-dns.kube-system.svc.cluster.local

Name:      kubernetes
Address 1: 10.254.0.1 kubernetes.default.svc.cluster.local

# kubectl exec -it busybox -- nslookup kubernetes.default 
Server:    10.254.0.10
Address 1: 10.254.0.10 kube-dns.kube-system.svc.cluster.local

**nslookup: can't resolve 'kubernetes.default'**

#kubectl exec -it busybox -- cat /etc/resolv.conf 
search default.svc.cluster.local svc.cluster.local cluster.local 
nameserver 10.254.0.10
options ndots:5
`
I'm using latest kubeDNS stuff from here: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns

What is wrong there ? I can deliver additional information. outputs from command if you wish.

**Comment by ash-man** [comment]
When I checked logs from kubedns container I see following information: 

I0228 18:59:48.845792       1 dns.go:264] New service: kubernetes
I0228 18:59:48.845926       1 dns.go:462] Added SRV record &{Host:kubernetes.default.svc.cluster.local. Port:443 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I0228 18:59:48.845972       1 dns.go:264] New service: kube-dns
I0228 18:59:48.846010       1 dns.go:462] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
I0228 18:59:48.846044       1 dns.go:462] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}

which means that services were added to DNS but why when I created new pod (busybox) its IP was not added ? I don't understand ...

**Comment by ash-man** [comment]
More data.  I did few experiments on kubedns container: 

kubectl --namespace=kube-system  exec -ti kube-dns-2408966145-b0uxb -c kubedns -- s
 # ps ux 
PID   USER     TIME   COMMAND
    1 root       0:01 /kube-dns --domain=cluster.local. --dns-port=10053 --config-dir=/kube-dns-config --v=2

Even if I'm on this container (kubedns) I cannot do nslookup for kubernetes: 

# nslookup kubernetes localhost
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

nslookup: can't resolve 'kubernetes': Try again
/ #

**Comment by dberuben** [comment]
@ash-man did you solve the issue ? i have the same issue!

**Comment by dberuben** [comment]
Ok found how to solved the issue!

--> /etc/systemd/system/docker.service.d/docker-options.conf
I removed the iptable option
and its working

**Comment by frankgreco** [comment]
@dberuben this fixed it for me as well! What version of Docker are you running? I'm running 1.13.

**Comment by dberuben** [comment]
@frankgreco same as you!

**Comment by ash-man** [comment]
Guys, I don't have such config file  /etc/systemd/system/docker.service.d/docker-options.conf on any of my cluster nodes & master ...

**Comment by Cocotton** [comment]
@dberuben is using Kargo to deploy its cluster. Are you too?

If not, it might be configured somewhere else, if configured at all.

**Comment by frankgreco** [comment]
@dberuben acutally I take that back. What fixed it for me was setting `iptables -P FORWARD ACCEPT`. I also have `--iptables=false` in my docker config

**Comment by christianri** [comment]
As I stumbled across a similar issue with Calico, and the forwarding accept rule worked too, I would describe a different solution on top:

In my case, I am using Debian Buster and kubernetes with Calico network stack. After many diversions and investigation, it turns out Calico used the `iptables-legacy` interface to create the rules whereas the iptables alternative on Debian Buster is `iptables-nft`. 
Changing this back via:
```
update-alternatives --set iptables /usr/sbin/iptables-legacy
update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
update-alternatives --set arptables /usr/sbin/arptables-legacy
update-alternatives --set ebtables /usr/sbin/ebtables-legacy
```
and restarting the nodes does the trick just fine, as everything now goes through the proper forward chain.
