### ISSUE TITLE
Addition of metrics endpoint to kube-proxy

### ISSUE THREAD

**Issue by alejandroEsc** [kubernetes/kubernetes#42261]
**What keywords did you search in Kubernetes issues before filing this one?**:
kube-proxy, kubeproxy, metrics 

**Is this a request for help?**:  NO

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

I propose the creation of the `/metrics` endpoint to kube-proxy because it would expose metrics that could potentially be helpful to the operators as a tool, as well as make kube-proxy consistent with the other control plane components and so meet expectations. We propose to turn this endpoint on the same way as the other endpoints in kube-proxy: as long as `config.HealthZPort > 0` is satisfied.

**Kubernetes version** (use `kubectl version`): 
`Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.3.14+2519039388b2ac-dirty", GitCommit:"2519039388b2ac6afca701363531d6f50d6b422c", GitTreeState:"dirty", BuildDate:"2017-02-23T17:38:58Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}`

**Comment by cmluciano** [comment]
Should be covered by  #42104
