### ISSUE TITLE
ci-kubernetes-e2e-kops-aws: broken test run

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#42270]
@zmerlynn @smarterclayton any idea what this is about?

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/4821?log#log

W0228 10:09:33.338] 2017/02/28 10:09:33 util.go:96: Running: /workspace/kops get clusters e2e-kops-aws.test-aws.k8s.io
W0228 10:13:34.375] 
W0228 10:13:34.375] error reading state store: error listing s3://k8s-kops-jenkins/: RequestError: send request failed

**Comment by zmerlynn** [comment]
This looks like an S3 flake, given that nothing else seems different (`git log dac0296f0b55a4..c1f84f3aeb3cdc` shows a commit that's irrelevant, and the `kops` version is `git-072c81e` consistently).

And indeed: 
![Uploading Screen Shot 2017-02-28 at 10.40.55 AM.png…]()


cc @justinsb
