### ISSUE TITLE
Completed cronjobs cause never-ending linear CPU increase

### ISSUE THREAD

**Issue by weaseal** [kubernetes/kubernetes#42274]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): cronjob cpu

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Kubernetes version** (use `kubectl version`): 1.5.3

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CentOS Linux 
- **Kernel** (e.g. `uname -a`): Linux $hostname 4.4.52-1.el7.elrepo.x86_64 #1 SMP Sun Feb 26 08:48:14 EST 2017 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**: kops 1.5.1
- **Others**:

**What happened**: I created a Cronjob which runs every 5 minutes.  After 1 day I noticed that my nodes were showing a linear increase in CPU starting from when I created the CronJob.  After I deleted all of the completed cronjobs, the CPU usage dropped significantly.

Sample pictures:

- https://drive.google.com/file/d/0B_Y_m0oONvv8TzA5b2R6T2Z1ZDQ/view?usp=sharing

- https://drive.google.com/file/d/0B_Y_m0oONvv8M3NoVjU0SkF0VVk/view?usp=sharing

**What you expected to happen**: The CPU to not increase due to backlog of completed jobs, or for completed jobs to be cleaned up automatically

**How to reproduce it** (as minimally and precisely as possible):  Create a cron job (mine is just a short bash script), let it run for 24 hours and look at a graph of CPU usage over that period.  Then delete all "Completed" versions of the job and watch CPU drop

**Anything else we need to know**: Organic peanut butter gets too hard to spread after chilling the fridge, but a quick 30 seconds in the microwave fixes that.  Be sure to remove the lid if it's metal.

**Comment by dims** [comment]
@weaseal There were some limits introduced recently in https://github.com/kubernetes/kubernetes/pull/40932 (example SuccessfulJobsHistoryLimit), will that help you? (cc @soltysh)

**Comment by soltysh** [comment]
@dims's suggestion is the best option to address that, when we move CronJobs to beta (hopefully in 1.7) we'll set `.spec.succesfulJobsHistoryLimit` to 3 by default. Until then you need to do it manually. The controller itself needs bit more work, as well, though.

**Comment by enisoc** [comment]
I believe the available limits can address this issue. Setting a default value is tracked in #41039.
