### ISSUE TITLE
Unable to use `kubectl edit` to change service type from NodePort to ClusterIP

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#42282]
**Is this a request for help?**: No.

**What keywords did you search in Kubernetes issues before filing this one?**: 'kubectl edit', 'nodeport', 'change service type'

---

**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Kubernetes version** (use `kubectl version`): On HEAD (commit 81d01a84e0f59fcedd69759f40d1669f5a9d7fda).
```
$ ./kubectl version
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.517+81d01a84e0f59f-dirty", GitCommit:"81d01a84e0f59fcedd69759f40d1669f5a9d7fda", GitTreeState:"dirty", BuildDate:"2017-02-28T21:01:01Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.517+81d01a84e0f59f-dirty", GitCommit:"81d01a84e0f59fcedd69759f40d1669f5a9d7fda", GitTreeState:"dirty", BuildDate:"2017-02-28T20:58:18Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**: Don't think this matter.

**What happened**:
I tried to use `kubectl edit svc` to change a NodePort service to a ClusterIP service in the same way I used before, but failed.

**What you expected to happen**:
Being able to use `kubectl edit svc` to change a NodePort service to a ClusterIP service.

**How to reproduce it**:
Create a service using below YAML file:
```
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  selector:
    run: my-nginx
  ports:
  - port: 80
    protocol: TCP
    nodePort: 31786
  type: NodePort
```
After the service is created, enter `kubectl edit svc my-nginx`, change `type` to ClusterIP and remove the `nodePort` field. Will hit below error:
```
# services "my-nginx" was not valid:
# * spec.ports[0].name: Required value
# * spec.ports[1].name: Required value
# * spec.ports[1].protocol: Required value
# * spec.ports[1].targetPort: Invalid value: 0: must be between 1 and 65535, inclusive
# * spec.ports[0].nodePort: Invalid value: 31786: may not be used when `type` is 'ClusterIP'
```

**Anything else we need to know**:
Could not reproduce it with k8s v1.5.2.

**Comment by MrHohn** [comment]
@ymqytw @kubernetes/sig-cli-bugs

**Comment by MrHohn** [comment]
cc @thockin

**Comment by ymqytw** [comment]
Still working on this. It works for 1.5.3. But not working for HEAD.
Things becomes tricky, since the name is the `mergeKey` for ports, but it could be missing for one single port. 

There are some discussion in https://github.com/kubernetes/kubernetes/issues/39188

**Comment by pwittrock** [comment]
@ymqytw Is this a dup we can close?

**Comment by ymqytw** [comment]
It will be closed by #42489 soon.

**Comment by komorebi-san** [comment]
Have it been solved? I got the same issue.

**Comment by Davidrjx** [comment]
i got the same error, is there anyone having solution?

**Comment by MrHohn** [comment]
I hit a similar error again while trying to modify service type from NodePort to ClusterIP. Opened a new bug on https://github.com/kubernetes/kubectl/issues/221.

**Comment by alexgiuvara** [comment]
You have to delete the service first:
`kubectl delete svc my-nginx`

**Comment by enibache** [comment]
so what gets edited if you delete the svc? weird response...

**Comment by alexgiuvara** [comment]
@enibache good observation! Delete the service and redeploy the correct version
