### ISSUE TITLE
TestAggregatedAPIServer is flaky

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#42289]
#42059 added it, so assigning @deads2k.

Hit the flake here: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42182/pull-kubernetes-unit/20832/

**Comment by deads2k** [comment]
Opened https://github.com/kubernetes/kubernetes/issues/42328 to fix.

**Comment by liggitt** [comment]
hit again:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46796/pull-kubernetes-unit/35343/

**Comment by liggitt** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/47191/pull-kubernetes-unit/35607/

**Comment by ixdy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/47545/pull-kubernetes-unit/36407/#k8siokubernetestestintegrationexamples-testaggregatedapiserver
```
apiserver_test.go:131: failed to listen on 127.0.0.1:38165: listen tcp 127.0.0.1:38165: bind: address already in use
apiserver_test.go:158: timed out waiting for the condition
```

**Comment by ixdy** [comment]
seems like `FindFreeLocalPort` is racy, which is probably a known bug.
