### ISSUE TITLE
Optimization for image locality priority function by caching.

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#42281]
What we are doing currently?

We are currently getting the information from node for images stored on it everytime we are scheduling in 
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/priorities/image_locality.go#L70

What can we do?
If we can add a field in node info just like disk , we may see some performance improvement and cache it we may see some performance improvement.

**Comment by k82cn** [comment]
@ravisantoshgudimetla , what kind of cache would like to add?

**Comment by ravisantoshgudimetla** [comment]
It should be in nodeinfo cache similar to following PR:
https://github.com/kubernetes/kubernetes/pull/20857/files.

**Comment by resouer** [comment]
1. Current image locality is a `priority`, that means scheduler will choose a more suitable node for you but do not guarantee it.

2. Image size used in this priority belongs to nodeInfo which is already a cache of real node, it will be updated automatically by scheduler.

**Comment by k82cn** [comment]
@ravisantoshgudimetla , I did not get time for this PR; can you explain what's different for resouer 's comments?

**Comment by ravisantoshgudimetla** [comment]
@resouer 

>Current image locality is a priority, that means scheduler will choose a more suitable node for you but do not guarantee it.

Agreed, but its present in default.go(it seems there are some priorities registered by default - imagelocality, equal priority and most requested ), which is why I am wondering, if those will be executed every time a new request for schedule comes in.  So, it means every time we are computing the images list present on that node(node.Status.Images). If not, please let me know.

>Image size used in this priority belongs to nodeInfo which is already a cache of real node, it will be updated automatically by scheduler.

I was proposing to add imagenames list to node info cache and btw, where is image size cached, I am currently looking at node_info.go which has NodeInfo struct. Am I missing anything here? As a reference, following is another PR(but again this is related to predicates but very much applicable to priorities as well).

https://github.com/kubernetes/kubernetes/pull/35275/files

**Comment by k82cn** [comment]
> I was proposing to add imagenames list to node info cache and btw, where is image size cached, I am currently looking at node_info.go which has NodeInfo struct.

I think that's not necessary; kubelet will only report the top 50th biggest images, it'll no improvement for the performance; and we also need to keep sync if cached.

**Comment by ravisantoshgudimetla** [comment]
>  kubelet will only report the top 50th biggest images, it'll no improvement for the performance

Interesting, isn't that what kubelet was supposed to for everything that we are caching. If we are caching imagelist, we don't have to run a query against kubelet which needs to get information on the top 50 big images. I mean, if we are caching for status like memory and cpu utilization, which probably are less expensive than getting a list of 50 images and sorting them based on size - shouldn't we cache this as well. I think we may not see too much of performance improvement(?) but  I think if we are doing it for small things like memory and CPU we should do it for images as well. 

Let me know, what you think.

**Comment by k82cn** [comment]
> we don't have to run a query against kubelet which needs to get information on the top 50 big images

The kubelet update Node info; and scheduler get notification. No direct REST API call.

> I think if we are doing it for small things like memory and CPU we should do it for images as well.

Which cache do you mean? My understand is that: the nodeInfo in scheduler is not for performance improvement; it just saves current node status for scheduling.

**Comment by ravisantoshgudimetla** [comment]
> The kubelet update Node info; and scheduler get notification. No direct REST API call.

Thanks for correcting me, I was under impression it gets the information from API Server. I mean, kubelet pushes to API server and scheduler gets the information from it.

> Which cache do you mean? My understand is that: the nodeInfo in scheduler is not for performance improvement; it just saves current node status for scheduling.

I think nodeinfo itself is a cache of real node, so instead of querying the status of node, we can get the information from nodeinfo.

**Comment by k82cn** [comment]
> Thanks for correcting me, I was under impression it gets the information from API Server. I mean, kubelet pushes to API server and scheduler gets the information from it.

Yes, that's right; kubelet update NodeInfo to apiserver.

> I think nodeinfo itself is a cache of real node, so instead of querying the status of node, we can get the information from nodeinfo.

Yes, we can call it cache; but I think it's not for performance improvement. Scheduler does not do scheduling/assignment in addNode/updateNode callback.

**Comment by jayunit100** [comment]
How are we measuring or confirming the performance improvement here ?

**Comment by k82cn** [comment]
prefer to close this one, any comments.

**Comment by ravisantoshgudimetla** [comment]
Sure @k82cn. I will close this for now. I don't have numbers for this yet and I am planning to use scheduler_perf to get some numbers.

**Comment by k82cn** [comment]
Great, scheduler_perf is good tools to get the number :).
