### ISSUE TITLE
verify-staging-client-go.sh continuously failing on release-1.6 branch

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#42290]
The verification tests have been [continuously failing](https://k8s-testgrid.appspot.com/google-unit#verify-1.6) since we enabled them on the release-1.6 branch. It looks like `verify-staging-client-go.sh` is the failing check.
From [a recent log](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-verify-release-1.6/25?log#log):
```
I0228 15:14:44.255]   diff '--ignore-matching-lines=^\s*\"Comment\"' -NauprB -I 'GoVersion.*\|GodepVersion.*' /go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/pkg/version/base.go /go/src/k8s.io/kubernetes/staging/src/k8s.io/_tmp/pkg/version/base.go
I0228 15:14:44.255]   --- /go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/pkg/version/base.go	2017-02-28 14:42:14.828391346 -0800
I0228 15:14:44.255]   +++ /go/src/k8s.io/kubernetes/staging/src/k8s.io/_tmp/pkg/version/base.go	2017-02-28 15:14:32.592488892 -0800
I0228 15:14:44.255]   @@ -39,8 +39,8 @@ var (
I0228 15:14:44.255]    	// them irrelevant. (Next we'll take it out, which may muck with
I0228 15:14:44.255]    	// scripts consuming the kubectl version output - but most of
I0228 15:14:44.256]    	// these should be looking at gitVersion already anyways.)
I0228 15:14:44.256]   -	gitMajor string = "" // major version, always numeric
I0228 15:14:44.256]   -	gitMinor string = "" // minor version, numeric possibly followed by "+"
I0228 15:14:44.256]   +	gitMajor string = "1"  // major version, always numeric
I0228 15:14:44.256]   +	gitMinor string = "6+" // minor version, numeric possibly followed by "+"
I0228 15:14:44.256]    
I0228 15:14:44.256]    	// semantic version, derived by build scripts (see
I0228 15:14:44.256]    	// https://github.com/kubernetes/kubernetes/blob/master/docs/design/versioning.md
I0228 15:14:44.256]   @@ -51,7 +51,7 @@ var (
I0228 15:14:44.256]    	// semantic version is a git hash, but the version itself is no
I0228 15:14:44.257]    	// longer the direct output of "git describe", but a slight
I0228 15:14:44.257]    	// translation to be semver compliant.
I0228 15:14:44.257]   -	gitVersion   string = "v0.0.0-master+$Format:%h$"
I0228 15:14:44.257]   +	gitVersion   string = "v1.6.0-beta.0+$Format:%h$"
I0228 15:14:44.257]    	gitCommit    string = "$Format:%H$"    // sha1 from git, output of $(git rev-parse HEAD)
I0228 15:14:44.257]    	gitTreeState string = "not a git tree" // state of git tree, either "clean" or "dirty"
I0228 15:14:44.257]    
I0228 15:14:44.257]   /go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go is out of date. Please run hack/update-staging-client-go.sh
I0228 15:14:44.270] FAILED   hack/make-rules/../../hack/verify-staging-client-go.sh	147s
```

Does this check need to be fixed? Should we disable this check on release branches? Or is something actually wrong with the release branch?

cc @ethernetdan @enisoc

**Comment by enisoc** [comment]
I don't actually know what this test does. Does this mean `make release` is going to fail, or is it just a CI issue? If so that blocks today's beta cut.

**Comment by ixdy** [comment]
cc @marun

**Comment by caesarxuchao** [comment]
Sent #42292

**Comment by ixdy** [comment]
somehow the most recent `update-all.sh` commit (https://github.com/kubernetes/kubernetes/commit/b877536df3c6f2).

I'm not sure what it did differently vs. the previous times it ran.

**Comment by enisoc** [comment]
@ixdy I cherrypicked the proposed fix from #42300. It didn't work without that.

**Comment by vladimirvivien** [comment]
@enisoc  I am still getting CI errors during `Jenkins Verification` steps for `verify-staging-client-go.sh`.  

when I build https://github.com/kubernetes/kubernetes/pull/38924 locally the scripts copies `staging/src/k8s.io/client-go/_vendor/github.com/pborman/`.  But when I push the PR, the verification always fails because head does not have that vendored package:

```
I0301 11:19:41.712] FAILED   hack/make-rules/../../hack/verify-staging-client-go.sh	145s
```
and

```
I0301 11:20:28.395] FAILED   hack/make-rules/../../hack/verify-staging-godeps.sh	47s
```

I was hoping https://github.com/kubernetes/kubernetes/pull/42326 would fix, but it is still happening. 

Any idea?

**Comment by caesarxuchao** [comment]
@vladimirvivien I don't think client-go depends on `github.com/pborman/uuid`, so the verification script is correct. How did you update staging/client-go? Did you do it by running hack/update-staging-client.sh? Did you rebase your PR to include latest changes on master before you ran the update script?

**Comment by vladimirvivien** [comment]
@caesarxuchao I was using `hack/update-staging-client-go.sh` and that introduced/copied the `pborman/uuid` package.  When the update-all-staging.sh was introduced in HEAD, I got the same result.  If I remove the package, my local build fails.

**Comment by vladimirvivien** [comment]
@caesarxuchao Yes, I have been rebasing consistently trying to get rid of error, but nothing helps so far.  If I remove the dependency, my build fail locally and still doesn't pass the CI check.

**Comment by vladimirvivien** [comment]
Just rebased, removed the github.com/pborman/uudi package, and ran the update script, this is the result:
```
> ./hack/update-all-staging.sh
Running in the silent mode, run with -v if you want to see script logs.
Running in short-circuit mode; run with -a to force all scripts to run.
Updating staging-client-go
Updating staging-godeps
Updating bazel
Update scripts completed successfully
vladimir@work-machine [~/DEV/go/src/k8s.io/kubernetes]
> git status
On branch scaleio-k8s-remove_pborman_dep
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	staging/src/k8s.io/client-go/_vendor/github.com/pborman/
```

**Comment by caesarxuchao** [comment]
Does client-go actually depend on `github.com/pborman/uudi`?

**Comment by sttts** [comment]
```shell
$ git grep "github.com/pborman/uudi"
<empty>
```

**Comment by sttts** [comment]
@vladimirvivien please try to find out which of the client-go packages depend on pborman/uuid. You can use something like this:
```shell
$ go list -f '{{ join .Deps "\n" }}' ./vendor/k8s.io/client-go/<some-directory>/... | sort | uniq
```

**Comment by vladimirvivien** [comment]
@sttts at some point when the staging build was enabled over the weekend a local build pulled a version of `client-go` that had a dependency on `pborman/uuid` package.  I **finally figured out** to delete that client-go and got a clean build without that package dependency.

Thanks.

**Comment by sttts** [comment]
@vladimirvivien where was that faulty client-go? In the GOPATH? Can we do anything to avoid those problems in the future?

**Comment by vladimirvivien** [comment]
@sttts it was in the same dir the kubernetes project.  Not sure when it got pulled down.  I really never used the staging script until earlier this week.  So I was not too familiar with its behavior.  Once I started to research here in this thread and went back and read the README for staging, I suspected that I probably could just delete the client-go directory. 

I personally think that client-go and staging should not be inside kubernetes.  The script to synchronize it should be in client-go and not in kubernetes.  This would remove a bug vector that took me 2.5 days to figure out what's going on.

Thanks for your feedback.

**Comment by sttts** [comment]
With https://github.com/kubernetes/kubernetes/pull/42084 being merged we
have removed on possible error of having another client-go in the GOPATH.
If I understand you right, you were hit by this. So in master this
shouldn't happen anymore.

Best regards,
   Stefan

**Comment by vladimirvivien** [comment]
@sttts awesome, good to know.  I did noticed this morning when I built, client-go was not placed on the GOPATH anymore.  

Thanks.
