### ISSUE TITLE
Kubelet: hack/local-up-cluster.sh failed for remote container runtimes

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#42315]
When setting `CONTAINER_RUNTIME_ENDPOINT` for other container runtime, `hack/local-up-cluster.sh` won't start kubelet correctly because cri is disabled [bd912f50b](https://github.com/kubernetes/kubernetes/commit/bd912f50bae3855082bdcc8368b8a85eefe1e8e8#diff-ed3df710e9af7cd30a185896a60897d9R578):

```
Error: failed to run Kubelet: failed to create kubelet: unsupported container runtime "remote" specified
Error: failed to run Kubelet: failed to create kubelet: unsupported container runtime "remote" specified
```

@ncdc Is there any reason of disabling cri at [bd912f50b](https://github.com/kubernetes/kubernetes/commit/bd912f50bae3855082bdcc8368b8a85eefe1e8e8#diff-ed3df710e9af7cd30a185896a60897d9R578)?

cc @yujuhong @Random-Liu

**Comment by ncdc** [comment]
@feiskyer no, that wasn't supposed to go in. I was testing something and it slipped in accidentally. I'll open a PR to fix.

**Comment by ncdc** [comment]
Ah I see your PR for it. Thanks!
