### ISSUE TITLE
Healthz probe error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.cluster.local'

### ISSUE THREAD

**Issue by mootezbessifi** [kubernetes/kubernetes#42319]
Dear all, 
After deploying the kubernetes cluster v1.4.8 on CentOS7 VMs using kargo, i found out that kubedns pod is not working properly:

`kcsys get pods -o wide`

`NAME                                 READY     STATUS             RESTARTS   AGE       IP              NODE`
`dnsmasq-alv8k                        1/1       Running            2          1d        10.233.86.2     kubemaster`

`dnsmasq-c9y52                        1/1       Running            2          1d        10.233.82.2     kubeminion1`

`dnsmasq-sjouh                        1/1       Running            2          1d        10.233.76.6     kubeminion2`

`kubedns-hxaj7                        2/3       CrashLoopBackOff   339        22h       10.233.76.3     kubeminion2`

# PS : kcsys is an alias of ''kubectl --namespace=kube-system''

Logs for each container (kubedns, dnsmasq) seems OK except healthz container as following:

`2017/03/01 07:24:32 Healthz probe error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.cluster.local'
, at 2017-03-01 07:24:31.740041088 +0000 UTC, error exit status 1
2017/03/01 07:24:42 Healthz probe error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.cluster.local'
, at 2017-03-01 07:24:41.643509613 +0000 UTC, error exit status 1
2017/03/01 07:24:52 Healthz probe error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.cluster.local'
, at 2017-03-01 07:24:51.742370072 +0000 UTC, error exit status 1`

Everything seems running good.

I will be thankful if anyone gives me some help

**Comment by mootezbessifi** [comment]
Sorry but i got some new errors in kubedns container like following:

`E0302 06:30:56.343432       1 reflector.go:199] pkg/dns/dns.go:145: Failed to list *api.Endpoints: Get https://10.233.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout`

`E0302 06:30:56.343574       1 reflector.go:199] pkg/dns/dns.go:148: Failed to list *api.Service: Get https://10.233.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout`

`E0302 06:31:27.344582       1 reflector.go:199] pkg/dns/dns.go:145: Failed to list *api.Endpoints: Get https://10.233.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout`

`E0302 06:31:27.344641       1 reflector.go:199] pkg/dns/dns.go:148: Failed to list *api.Service: Get https://10.233.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout`

`I0302 06:31:32.338838       1 server.go:150] Ignoring signal terminated (can only be terminated by SIGKILL)`

`E0302 06:31:58.345799       1 reflector.go:199] pkg/dns/dns.go:145: Failed to list *api.Endpoints: Get https://10.233.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout`

`E0302 06:31:58.345907       1 reflector.go:199] pkg/dns/dns.go:148: Failed to list *api.Service: Get https://10.233.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout`

**Comment by Tonyzhangl** [comment]
@mootezbessifi  i also met the problem, mabe you can refer to the comments in [http://stackoverflow.com/questions/42525968/kube-dns-can-not-resolve-kubernetes-default-svc-cluster-local](url)
