### ISSUE TITLE
./hack/update-generated-protobuf.sh keep reporting modification in future

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#42329]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

**Kubernetes version** (use `kubectl version`):
master

**What happened**:

It took a real long time to run `./hack/update-generated-protobuf.sh` because of following issues:

```
make[1]: Entering directory '/go/src/k8s.io/kubernetes'
make[1]: Warning: File 'pkg/api/v1' has modification time 2272 s in the future
make[1]: Warning: File 'pkg/api/v1' has modification time 2270 s in the future
make[1]: Warning: File 'pkg/api/v1' has modification time 2268 s in the future
make[1]: Warning: File 'pkg/api/v1' has modification time 2266 s in the future
make[1]: Warning: File 'pkg/api/v1' has modification time 2264 s in the future
```

**Anything else we need to know**:
It works this morning :(.

**Comment by k82cn** [comment]
@kubernetes/test-infra-maintainers , I have to wait for ~2000s to re-run it :(. Any suggestion?

**Comment by ixdy** [comment]
Is your system clock set to something weird?

**Comment by k82cn** [comment]
> Is your system clock set to something weird?

I don-t think so :). It worked fine yesterday morning (China time).

**Comment by k82cn** [comment]
@ixdy , there's the output in my Mac :).


```
macpro:kubernetes klaus$ docker run kube-build:build-b64390be47-5-v1.7.5-2 date
Mon Mar  6 09:39:47 CST 2017
macpro:kubernetes klaus$ date
Mon Mar  6 10:46:09 CST 2017
macpro:kubernetes klaus$
```

**Comment by k82cn** [comment]
It's OK in my ubuntu 16.04 vm :).

**Comment by ixdy** [comment]
That's bizarre. You ran those two `date` commands at the same time?

**Comment by rmmh** [comment]
Are you running an ubuntu VM with source code from your mac mounted? Are you running NTP to synchronize clocks on both?

VM clocks can be confused when paused, and will cause strange problems like this.

**Comment by k82cn** [comment]
> That's bizarre. You ran those two date commands at the same time?

Yes, at the same time.

> Are you running an ubuntu VM with source code from your mac mounted? Are you running NTP to synchronize clocks on both?

The issue is in Mac; it works in Ubuntu 16.04 vm (VM disk).

And I found the `localtime` in local machine was copied into docker; will that the problem?

**Comment by ixdy** [comment]
The `localtime` copy just ensures that the timezone in the container matches your host.

**Comment by k82cn** [comment]
no idea now :(. I'm using `./hack/update-generated-protobuf-dockerizer.sh` now.

**Comment by rmmh** [comment]
Is your VM an hour into the future? Does your Mac or VM clock disagree with https://www.timeanddate.com/time/zones/cst-china ?

**Comment by k82cn** [comment]
@rmmh , no, it's not VM related issue. It works fine in my VM, but does not work in my Mac (physical machine, my laptop).

**Comment by krzyzacy** [comment]
@k82cn can be vpn or proxy related issue that gives a bad modified time?

**Comment by k82cn** [comment]
wow, vpn and proxy, maybe. let me try it without vpn & proxy.

**Comment by krzyzacy** [comment]
coz I know you need those to get the traffic over :-)
