### ISSUE TITLE
StatefulSet upgrade test error when running against pre-1.5 versions of k8s

### ISSUE THREAD

**Issue by skriss** [kubernetes/kubernetes#42348]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:64
Expected error:
    <*errors.StatusError | 0xc420c08c00>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "the server could not find the requested resource",
            Reason: "NotFound",
            Details: {Name: "", Group: "", Kind: "", Causes: nil, RetryAfterSeconds: 0},
            Code: 404,
        },
    }
    the server could not find the requested resource
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/upgrades/statefulset.go:60

See, for example, [this run](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1.4-gci-latest-upgrade-master/655#k8sio-upgrade-featureupgrade-k8sio-master-upgrade-should-maintain-a-functioning-cluster-featuremasterupgrade)

From a quick glance, I believe the issue is that prior to 1.5, StatefulSets were called PetSets, so the API calls in the upgrade test that run against old versions of k8s are incompatible. I could be off-base here though as I'm new to this stuff.

Ref PR #41221

@kow3ns

**Comment by kow3ns** [comment]
@skriss You are correct. This will not work on an upgrade test prior to 1.5 -> 1.6.

**Comment by skriss** [comment]
@kow3ns is there anything that can be done about this? it's creating a lot of noise in the upgrade test jobs.

**Comment by kow3ns** [comment]
@skriss The automated testing was targeted to run from 1.5 - 1.6 and onward. We decided that we would break PetSet during the rename on 1.4 - 1.5. This test is only valid from 1.5 onward. Is there a way to disable tests on a per test basis in the upgrade testing framework?

**Comment by ethernetdan** [comment]
We should figure out how to avoid these false positives but I don't believe this is release blocking.

**Comment by enisoc** [comment]
This appears to be obsolete.
