### ISSUE TITLE
PV controller volume operations are not using any backoff mechanism 

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#42359]
In PV controller, all volumes operations are not going through operation_exectuor like other controller (e.g. reconciler in attach_detach_controller). If an operation fails, the PV controller will not use exponential backoff to reduce the request rate. Controller will try the same operation every 15 second (the default sync period). 

It would be better to use exponential backoff mechanism to reduce the operation request rate and could also avoid the multiple operations on the same volume concurrently.

**Comment by gnufied** [comment]
It should be noted that even in attach_detach controller exponential backing off is disabled even though operations do through operation_executor -  https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/attach_detach_controller.go#L136

Also, I added exponential backoff when deletion fails in pv controller - https://github.com/kubernetes/kubernetes/pull/38339

**Comment by gnufied** [comment]
if we do enable exponential backoff in attach_detach, we will run in this problem - https://github.com/kubernetes/kubernetes/issues/41307 

I closed that bug for now because obviously it is disabled.

**Comment by spiffxp** [comment]
@kubernetes/sig-storage-pr-reviews @kubernetes/release-team @jingxu97 @gnufied We are treating all issues in the v1.6 milestone as blockers.  Does this issue justify blocking the 1.6 kubernetes release?  If yes, can you give an estimate on who will fix this by when?  If no, would you mind kicking this out of the v1.6 milestone?

**Comment by jsafrane** [comment]
I don't think this is 1.6 blocker, shifting

**Comment by jsafrane** [comment]
We need to make sure that binding PVs to PVCs happens in reasonable time if we enable exponential backoff for all operations.

Binding PVs to PVCs is controlled by PVCs only. When an event happens on a PVC (such as the PVC is created), the controller looks for a suitable PV and binds them together. When an event happens on a PV, nothing interesting happens - the controller does **not** look for PVCs that could match this PV. This was deliberately done to simplify the controller, it's already complicated enough. So we need to sweep through unbound PVCs quite often to bind them to newly created PVs.

We could use exponential backoff if we react to PV events and actively look for PVCs that could be satisfied by it, but it's not that simple as it seems.

**Comment by saad-ali** [comment]
> We need to make sure that binding PVs to PVCs happens in reasonable time if we enable exponential backoff for all operations.
>
> Binding PVs to PVCs is controlled by PVCs only. When an event happens on a PVC (such as the PVC is created), the controller looks for a suitable PV and binds them together. When an event happens on a PV, nothing interesting happens - the controller does not look for PVCs that could match this PV. This was deliberately done to simplify the controller, it's already complicated enough. So we need to sweep through unbound PVCs quite often to bind them to newly created PVs.
> 
> We could use exponential backoff if we react to PV events and actively look for PVCs that could be satisfied by it, but it's not that simple as it seems.

Closing this as unnecessary.
