### ISSUE TITLE
[Federation] Joining cluster service account created by kubefed-join has a potentially-non-unique name

### ISSUE THREAD

**Issue by perotinus** [kubernetes/kubernetes#42356]
This is a follow-up to #41267.

Currently, the service account created in a joining cluster by `kubefed join` is named based on the federation name and the host context name. This is not necessarily unique. We should find a more-unique naming scheme for these service accounts.

We may need to store the service account names somewhere where `kubefed unjoin` can find them.

**Comment by quinton-hoole** [comment]
It seems we can use UID's for names, and labels to find them later.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#108.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
