### ISSUE TITLE
[Federation] Joining cluster service accounts roles created by kubefed join are very broad

### ISSUE THREAD

**Issue by perotinus** [kubernetes/kubernetes#42355]
This is a follow-up to #41267.

Currently, the service account created in a joining cluster by `kubefed join` has role-based access to all APIs and all resources in all namespaces. We should determine if there is a tighter reasonable subset, or decide that this is conceptually OK. Making a tighter subset will be a small maintenance burden, and will potentially cause issues if people are trying to use older versions of kubefed with newer versions of the control plane.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#208.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
