### ISSUE TITLE
PV controller keeps deleting disks even they no longer exist

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#42358]
PV controller trigger delete disks when user delete the PVC if policy is PersistentVolumeReclaimDelete. However, in gce implementation, if the disk is no longer exist, the delete is considered failed operation, and controller will try to continue to delete. Need to fix this in release 1.6

**Comment by saad-ali** [comment]
CC @kubernetes/sig-storage-bugs @jsafrane

**Comment by jsafrane** [comment]
It seems @jingxu97 is already working on a patch in https://github.com/kubernetes/kubernetes/pull/42444

**Comment by spiffxp** [comment]
@kubernetes/sig-storage-pr-reviews @jingxu97 @jsafrane Helping out with 1.6 issue triage (https://groups.google.com/forum/#!topic/kubernetes-milestone-burndown/48AFuXnoJZA). Please re-open if you feel this is an inappropriate action.

The linked PR has been merged, assuming this can now be closed.
