### ISSUE TITLE
[Federation] Decide whether or not to reintroduce support for non-RBAC Federated clusters in kubefed join

### ISSUE THREAD

**Issue by perotinus** [kubernetes/kubernetes#42352]
This is a follow-up to #41267.

#42042 removed support in `kubefed join` for clusters that don't support RBAC. Based on a discussion between me, @csbell and @madhusudancs, we need to decide Kubernetes cluster versions Federation will support. If we want to support pre-RBAC clusters, we need to reintroduce the old mechanism, with noisy warnings that the user should update for better security; if not, than this issue can be quickly closed.

**Comment by madhusudancs** [comment]
cc @kubernetes/sig-federation-bugs

**Comment by nikhiljindal** [comment]
Yes we do need to support pre-RBAC clusters.
Generally at most places in kubernetes, we support version skews of atleast one.

**Comment by perotinus** [comment]
Some clarifications based on a chat with @nikhiljindal:

- If #42042 does not go in, there is no problem here
- Once #42042 goes in, in re this feature the FCP will still support all cluster versions that it did in 1.5 (though there may be other changes that would affect this)
- Once #41830 goes in, without fixing this issue, `kubefed join` will support clusters back to 1.4, when RBAC was introduced

**Comment by madhusudancs** [comment]
Also, note PR #41830 won't go in, in its current state. It should include code to handle clusters without RBAC. @irfanurrehman isn't that the plan?

**Comment by madhusudancs** [comment]
Also, there won't be any regressions in `kubefed join` until PR #42042 merges. We will continue uploading admin user credentials and that is supported in all the clusters. The current regression that PR #41830 is trying to address is in `kubefed init` and that same fix can be reused, although in a slightly modified way, in `kubefed join` as well.

**Comment by nikhiljindal** [comment]
Great thanks for clarification!

**Comment by irfanurrehman** [comment]
@madhusudancs ack about the impl for https://github.com/kubernetes/kubernetes/pull/41830
I was under the impression that we support only those clusters now, which support RBAC. Thanks for the clarification. Will update it accordingly.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#107.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
