### ISSUE TITLE
When an e2e test fails, enumerate all cloud provider API calls that failed and why

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#42366]
It would be awesome if the cloud provider had an API to do this for us.  As an example, in #42361 the problem was clear from the logfile once you knew what to look for: `E0301 19:52:56.567418       5 servicecontroller.go:772] Failed to process service. Retrying in 5s: Failed to create load balancer for service e2e-tests-service-upgrade-jt75x/service-test: failed to create forwarding rule a4b2a6798feb511e6bdea42010af0000: googleapi: Error 403: Quota 'FORWARDING_RULES' exceeded. Limit: 15.0, quotaExceeded`, but that could take a lot of time.

Enumerating these failures automatically would make debugging very easy.

@kubernetes/sig-testing-bugs

**Comment by spiffxp** [comment]
/sig testing
I don't think we should own this, sounds like a sig-cloud thing, but they don't exist, so I'll put it here for now to triage off later
