### ISSUE TITLE
podtolerationrestriction admisstion controller unit test need update

### ISSUE THREAD

**Issue by wanghaoran1988** [kubernetes/kubernetes#42372]
This is a follow up issue for https://github.com/kubernetes/kubernetes/pull/30302#discussion_r103616063

**Comment by aveshagarwal** [comment]
I have updated https://github.com/kubernetes/kubernetes/issues/30302 to address this issue.

**Comment by wanghaoran1988** [comment]
Close, issue fixed with that PR.
