### ISSUE TITLE
1.6 to 1.5 master downgrade fails because it can't find $KUBE_HOME/bin/mounter

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#42371]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version** (use `kubectl version`): 1.7.0-alpha... downgraded master to release-1.5

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): Container-Optimized OS
- **Kernel** (e.g. `uname -a`): Linux e2e-test-krousey-master 4.4.21+ #1 SMP Fri Feb 17 15:34:45 PST 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
- **Install tools**: e2e.go

**What happened**:

The master failed to come up. The configuration unit failed because it could not find /home/kubernetes/bin/mounter.

```console
$ sudo systemctl status kube-master-configuration
● kube-master-configuration.service - Configure kubernetes master
   Loaded: loaded (/etc/systemd/system/kube-master-configuration.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2017-03-01 19:51:32 UTC; 8min ago
  Process: 1127 ExecStart=/home/kubernetes/bin/configure-helper.sh (code=exited, status=1/FAILURE)
  Process: 1123 ExecStartPre=/bin/chmod 544 /home/kubernetes/bin/configure-helper.sh (code=exited, status=0/SUCCESS)
 Main PID: 1127 (code=exited, status=1/FAILURE)

Mar 01 19:51:32 e2e-test-krousey-master configure-helper.sh[1127]: Mounting '/dev/disk/by-id/google-master-pd' at '/mnt/disks/master-pd'
Mar 01 19:51:32 e2e-test-krousey-master configure-helper.sh[1127]: Mounted master-pd '/dev/disk/by-id/google-master-pd' at '/mnt/disks/master-pd'
Mar 01 19:51:32 e2e-test-krousey-master useradd[1163]: new group: name=etcd, GID=5001
Mar 01 19:51:32 e2e-test-krousey-master useradd[1163]: new user: name=etcd, UID=5001, GID=5001, home=/var/etcd, shell=/sbin/nologin
Mar 01 19:51:32 e2e-test-krousey-master configure-helper.sh[1127]: useradd: warning: the home directory already exists.
Mar 01 19:51:32 e2e-test-krousey-master configure-helper.sh[1127]: Not copying any file from skel directory into it.
Mar 01 19:51:32 e2e-test-krousey-master configure-helper.sh[1127]: Creating master auth files
Mar 01 19:51:32 e2e-test-krousey-master configure-helper.sh[1127]: Creating kubelet kubeconfig file
Mar 01 19:51:32 e2e-test-krousey-master configure-helper.sh[1127]: overriding kubectl
Mar 01 19:51:32 e2e-test-krousey-master configure-helper.sh[1127]: prewarming mounter
```

```console
$ ls -alF /home/kubernetes/bin 
total 210096
drwxr-xr-x 2 root root      4096 Mar  1 23:37 ./
drwxr-xr-x 7 root root      4096 Mar  1 23:38 ../
-rwxr-xr-x 1 root root   5818944 Sep  6 17:23 bridge*
-rwxr-xr-x 1 root root   3544864 Sep  6 17:23 cnitool*
-r-xr--r-- 1 root root     50018 Mar  1 23:37 configure-helper.sh*
-rwxr-xr-x 1 root root     10064 Mar  1 23:37 configure.sh*
-rwxr-xr-x 1 root root  11433960 Sep  6 17:23 dhcp*
-rwxr-xr-x 1 root root   3611032 Sep  6 17:23 flannel*
-r-xr--r-- 1 root root      2561 Mar  1 23:37 health-monitor.sh*
-rwxr-xr-x 1 root root   3911992 Sep  6 17:23 host-local*
-rwxr-xr-x 1 root root   5208592 Sep  6 17:23 ipvlan*
-rwxr-xr-x 1 root root  50360619 Mar  1 01:19 kubectl*
-rwxr-xr-x 1 root root 108108808 Mar  1 01:18 kubelet*
-rwxr-xr-x 1 root root   4943096 Sep  6 17:23 loopback*
-rwxr-xr-x 1 root root   5234576 Sep  6 17:23 macvlan*
-rwxr-xr-x 1 root root   3329240 Sep  6 17:23 noop*
-rwxr-xr-x 1 root root   5808920 Sep  6 17:23 ptp*
-rwxr-xr-x 1 root root   3721672 Sep  6 17:23 tuning*
```

**What you expected to happen**:

The master to downgrade and come back up.

**How to reproduce it** (as minimally and precisely as possible):

Check out a master branch and run `make quick-release`. Then run `go run ./hack/e2e.go --check_version_skew=false --v=t -up --test --test_args="--ginkgo.focus=\[Feature:ClusterUpgrade\] --upgrade-target=ci/latest-1.5"`

**Comment by krousey** [comment]
cc @roberthbailey

**Comment by krousey** [comment]
This is probably because the upgrade script is running in a 1.7 branch and pulling the configure.sh from there and putting it in the master's metadata.

**Comment by roberthbailey** [comment]
See steps 8 & 10 from the [Manual Upgrade/Downgrade Testing 1.4->1.5](https://docs.google.com/document/d/19Q4AzWLD5jd2FNaPyKy2xdTN4JIGUUpvwDwg0tcBkyc/edit) instructions:

> 8. Downgrade the nodes to 1.4 **using the 1.4 version of the script**
>       a. $ export KUBE_NODE_OS_DISTRIBUTION=STARTING_NODE_OS
>      $ cluster/gce/upgrade.sh -N -o v1.4.6
(repeat: you should use script from 1.4 tag -- you should have checked it out using “git checkout v1.4.6”)

> 10. Downgrade the master to 1.4 **using the 1.4 version of the script**
>      a. $ cluster/gce/upgrade.sh -M v1.4.6
>      (repeat: you should use script from 1.4 tag -- you should have checked it out using “git checkout v1.4.6”)

**Comment by krousey** [comment]
Closing this. It's just a matter of hooking up the e2e framework to be able to use the upgrade script from the second repo in CI suites.
