### ISSUE TITLE
kubectl patch always show not patched

### ISSUE THREAD

**Issue by ymqytw** [kubernetes/kubernetes#42384]
The bug is introduced in https://github.com/kubernetes/kubernetes/pull/38538

The oldData, newData in [line215](https://github.com/kubernetes/kubernetes/blob/01bfbb5fa0462189932b704be32401822a991627/pkg/kubectl/cmd/patch.go#L215) seem always to be the same. So it always showing `not patched`.

After digging a bit, I found that:

- the place where we save the `oldData` may be wrong.
- sometimes oldData and newData are different because of different `resourceVersion`s, even though the patch is `{}`.

cc: @juanvallejo @fabianofranz

**Comment by liggitt** [comment]
cc @deads2k

**Comment by liggitt** [comment]
info.Object is updated by the info.Refresh call. We should compute old data prior to refreshing the info

**Comment by shiywang** [comment]
@ymqytw I think the second bug is because using `-f` read from stream has less infomation when you fetch from server, so `kubectl patch rc test -p '{}' works` but `-f` didn't
