### ISSUE TITLE
Programmatically changing current context in .kube config

### ISSUE THREAD

**Issue by jiefugong** [kubernetes/kubernetes#42383]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**Kubernetes version** (use `kubectl version`):
1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): Ubuntu 16.10
- **Kernel** (e.g. `uname -a`): Linux provisioner-01 4.8.0-32-generic #34-Ubuntu SMP Tue Dec 13 14:30:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**What happened**:
I'm currently trying to use the Kubernetes Python client to change the current context of my cluster -- is there an easy way to do so? I've taken a look at the API but there does not seem to be a straightforward way of doing so.

**Comment by liggitt** [comment]
should this be moved to https://github.com/kubernetes-incubator/client-python?
