### ISSUE TITLE
vSphere: Cannot add disks to more than one scsi adapter (disk count per node > 16)

### ISSUE THREAD

**Issue by kerneltime** [kubernetes/kubernetes#42399]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): v1.4.x v1.5.x v1.6.x master

**Environment**: vSphere based install with vSphere Cloud Provider enabled.
- **Cloud provider or hardware configuration**: vSphere
- **OS** (e.g. from /etc/os-release): NA
- **Kernel** (e.g. `uname -a`):NA
- **Install tools**:kubernetes-anywhere
- **Others**:

**What happened**: vSphere Cloud Provider configures additional SCSI adapters to scale the number of volumes that can be attached to a VM (1 adapter = 16 disks). The code within the cloud provider does not handle this correctly. Additional disks attach successfully to the VM but when k8s verifies the attach status it fails leading to k8s retrying the attach that never succeeds. In addition to this when the SCSI adapter is created for the first time the code does not use it to attach the disk leading to a failed attach disk request to the cloud provider.

**What you expected to happen**: Additional disks should be added to the VM upto the max number supported. 

**How to reproduce it** (as minimally and precisely as possible): Create a single node cluster and create a statefulset with > 16 replicas or have a pod with more than 16 disks.

**Anything else we need to know**:

**Comment by kerneltime** [comment]
A fix for this is coming up..

**Comment by kerneltime** [comment]
cc @robdaemon

**Comment by robdaemon** [comment]
Huh, I wonder if something changed between 1.3 and newer? We had tested up to 40-something volumes on 1.3. There was a fun discussion internally because it would always fail at SCSI ID 7 and I had to explain SCSI to some younger engineers :)
