### ISSUE TITLE
RBAC bootstrap roles should not contain optional cluster addon roles and bindings

### ISSUE THREAD

**Issue by fen4o** [kubernetes/kubernetes#42401]
**Kubernetes version**: HEAD

Right now _optional_ cluster addons (like Heapster and Node Problem Detector etc..) have their ClusterRoles and ClusterRoleBindings automatically created, despite the fact that said addon may not be deployed on the kubernetes cluster. Such addons must align changes in their functionality with kubernetes release cycle, which does not provide easy backward compatibility and may not be required in all cases.

This increases complexity of managing RBAC for addons in [bootstrap policy](https://github.com/kubernetes/kubernetes/blob/c272630b1bc87838cccedd3c04769d2b37b4dc66/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go) and slows the development turnaround cycle both for kubernetes and addon projects.

I find more natural, for example, addonX to have the following files
```
addonX-controller.yaml
addonX-service.yaml
addonX-cluster-rbac.yaml <- needed ClusterRole and ClusterRoleBinding
```
and the end-user may install the addon with kubectl or addonmanager.

@deads2k @liggitt

**Comment by fen4o** [comment]
Related issue #40021

**Comment by deads2k** [comment]
Heapster is effectively non-optional since HPA doesn't function without it, so that definitely stays.

NodeProblemDetector and kube-dns are both kubernetes proper projects (not incubators), for which roles are created, but not bindings.

Nothing stops someone creating an additional role if they need more permissions.  Having "normal" roles for official kubernetes projects seems pretty reasonable.

**Comment by fen4o** [comment]
Thanks for the quick reply

Our usecase right now is that we want to use RBAC for kube 1.5.x and we plan to move to 1.6 once it's stable enough.

The problem is that addons don't provide their needed ClusterRoles in their documentation and one must look either in the source code of the add-on or in the bootstrap policy file (or test data folder).

I guess that a better approach is to improve the documentation of the addons with ClusterRoles (for both alpha and beta RBAC api versions).

What do you think about it?

**Comment by deads2k** [comment]
> I guess that a better approach is to improve the documentation of the addons with ClusterRoles (for both alpha and beta RBAC api versions).
> 
> What do you think about it?

I think that's a good idea.  I think if an add-on provided a beta version of their role, then if someone needed an alpha level for some reason they use `kubectl convert` to manage it themselves.

**Comment by fen4o** [comment]
Great. I'll make some PRs Monday morning.

Closing the issue for now
