### ISSUE TITLE
Create an integration test fixture for kube-apiserver

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#42400]
Similar to the one being added for federation-apiserver in https://github.com/kubernetes/kubernetes/pull/42278.
Once that PR is merged, we can follow the pattern established there to create a similar fixture for kube-apiserver.

cc @marun @sttts

**Comment by sttts** [comment]
@nikhiljindal @marun how does this relate to https://github.com/kubernetes/kubernetes/pull/47252 (second commit)?
