### ISSUE TITLE
Status field means different things for different controllers

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#42410]
status.replicas is used by ReplicaSets, ReplicationControllers, Deployments, DaemonSets (CurrentNumberScheduled), and StatefulSets. For all of the controllers apart from StatefulSets, it means the number of pods that have been created. For StatefulSets, it means the pods that are ready. We should fix this. StatefulSets need all the rest of the status fields anyway - ReadyReplicas, AvailableReplicas, and once updates are done, UpdatedReplicas.

@kubernetes/sig-apps-api-reviews @kow3ns

**Comment by kargakis** [comment]
Ref: https://github.com/kubernetes/kubernetes/issues/37563

**Comment by kargakis** [comment]
Should be addressed in https://github.com/kubernetes/community/pull/503

**Comment by dchen1107** [comment]
This requires API-Change, which should be punt to next release since we are at code freeze stage already. cc/ @erictune

**Comment by kargakis** [comment]
This is fixed in 1.7 - the status.replicas field in statefulsets is aligned with the respective field in the rest of the workload controllers.
