### ISSUE TITLE
Add e2e test for scheduler priorities

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#42439]
Scheduler currently has e2e tests only for prediates (test/e2e/scheduler_predicates.go). We need to add similar e2e tests for priorities.

@sig-scheduling-feature-requests

**Comment by k82cn** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by wanghaoran1988** [comment]
@k82cn Would you mind assign this to me?

**Comment by wanghaoran1988** [comment]
@bsalamat Are you working on this?

**Comment by bsalamat** [comment]
@wanghaoran1988 No, I am not. Please feel free to take it. I will be happy to review PRs.
