### ISSUE TITLE
GCE cloud getInstanceByName and getInstancesByNames might not work efficiently with nodeNamePrefix matching

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#42445]
The function getInstancesByNames in gce.go setup a filter with node name prefix when calling instances.List. However the node name might be truncated and it will not match exactly with the node name prefix. In such case, the filter is set to empty, and all instances will be returned. 

getInstanceByName function is supposed to use instance.Get with the specified name. However, when the cluster is across multiple zones, it will call getInstancesByNames in every zone which cause some unnecessary traffic especially for large cluster.

**Comment by spiffxp** [comment]
@kubernetes/sig-storage-pr-reviews @jingxu97 We are treating all issues in the v1.6 milestone as blockers. Does this issue justify blocking the 1.6 kubernetes release? If yes, can you give an estimate on who will fix this by when? If no, would you mind kicking this out of the v1.6 milestone?

**Comment by jingxu97** [comment]
I think it is not a 1.6 blocker. Move it out to v1.7

**Comment by saad-ali** [comment]
Oh looks like @jingxu97 already fixed this in https://github.com/kubernetes/kubernetes/pull/42452
