### ISSUE TITLE
Log redirect wrapper for system container images

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#42442]
We have a common pattern of system container images that package a single go binary, but rely on a shell command simply to redirect the logs ([rescheduler](https://github.com/kubernetes/contrib/blob/master/rescheduler/Dockerfile), [kube-controller-manager](https://github.com/kubernetes/kubernetes/blob/102f267b6a8012752433737bc473730fc72c12f5/cluster/saltbase/salt/kube-controller-manager/kube-controller-manager.manifest#L116), [kube-apiserver](https://github.com/kubernetes/kubernetes/blob/102f267b6a8012752433737bc473730fc72c12f5/cluster/saltbase/salt/kube-apiserver/kube-apiserver.manifest#L218), etc.). It would be nice to remove the shell dependency for these images (to reduce the attack surface and image management). This could be done making changes to the binaries directly to pass the log destination, but that means the binaries must have write permissions (often root) to the log locations.

I propose instead a simple wrapper program that takes:

- Command & arguments to execute
- File location for output redirection
- (optional) uid & gid to run subcommand as

We could provide this in a scratch based image, and rebase images following this pattern on this.

/cc @ixdy @thockin

**Comment by thockin** [comment]
Or we could just stop logging to disk directly and instead use
stdout/stderr ?  Not sure what the implications would be for things like
kube-proxy...

**Comment by yujuhong** [comment]
> Or we could just stop logging to disk directly and instead use
> stdout/stderr ?  Not sure what the implications would be for things like
> kube-proxy...

One caveat is that we are not able to decouple logs and container lifecycles yet. In some cases (container restart multiple times in a short time frame), kubelet may delete the container (and its logs) before the log get collected. Another thing is that log collection (for e2e and/or GKE master) may need to be changed (now it's easy to grab files in /var/log).

Barring those, I actually like the idea of just output to stdout/stderr.

**Comment by spiffxp** [comment]
/sig instrumentation
because logging

**Comment by crassirostris** [comment]
I would prefer that also: https://github.com/kubernetes/kubernetes/issues/39800

**Comment by yujuhong** [comment]
Let's consolidate the discussion in #39800
