### ISSUE TITLE
ci-kubernetes-cross-build is broken

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#42441]
```
I0302 13:12:41.422] +++ [0302 13:10:35] linux/arm: go build started
I0302 13:12:41.422] # k8s.io/kubernetes/test/e2e_node
I0302 13:12:41.423] test/e2e_node/node_problem_detector.go:395: invalid operation: info.Uptime * int64(time.Second) (mismatched types int32 and int64)
```

from e.g. https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-cross-build/1026/build-log.txt

Appears to come from #41928

Seth is going to work on a fix

cc @Random-Liu @ethernetdan @calebamiles

**Comment by sjenning** [comment]
This could be low level golang's syscall package issue.

Docs show the type as int64 for `Uptime`
https://golang.org/pkg/syscall/#Sysinfo_t

Need to make sure it is the same for all arches

**Comment by ixdy** [comment]
The docs look only somewhat accurate. Following the link to the type definition from that doc, we get to https://golang.org/src/syscall/ztypes_linux_amd64.go?s=9428:9746#L540.

If I change amd64 to [arm](https://golang.org/src/syscall/ztypes_linux_arm.go#L525), we can see that it's `int32` there.

**Comment by Random-Liu** [comment]
Hm...Could we always explicitly cast it to `int64`?

**Comment by sjenning** [comment]
@Random-Liu sounds good to me

**Comment by Random-Liu** [comment]
Sent a PR https://github.com/kubernetes/kubernetes/pull/42443.

Will run cross build locally to verify it.
