### ISSUE TITLE
Job E2E tests failing in upgrade test jobs

### ISSUE THREAD

**Issue by skriss** [kubernetes/kubernetes#42451]
@soltysh directing this at you for now because you're listed as the test owner.

In the upgrade test jobs, most of the Job E2E tests are failing. See, for example:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.4-container_vm-latest-upgrade-cluster/479

The common error message is:
```
Expected error:
    <*errors.StatusError | 0xc8212a9d80>: {
        ErrStatus: {
            TypeMeta: {Kind: "Status", APIVersion: "v1"},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "the server could not find the requested resource",
            Reason: "NotFound",
            Details: {Name: "", Group: "", Kind: "", Causes: nil, RetryAfterSeconds: 0},
            Code: 404,
        },
    }
    the server could not find the requested resource
not to have occurred
```
I'm guessing this is related to renaming and/or moving of Job within the API - but please give me your take on this issue. Thanks!

**Comment by soltysh** [comment]
@skriss it looks like you're running 1.4 e2e tests (see this [createJob](https://github.com/kubernetes/kubernetes/blob/release-1.4/test/e2e/job.go#L264-L266) function) on newer cluster (1.6 at least). Starting since 1.6 we dropped entirely support for Jobs in extensions endpoint (see [this PR](https://github.com/kubernetes/kubernetes/pull/38614)). 

Not sure about your setup but either you will safely ignore these errors (based on what I said above) or you'll pick newer e2e tests for job (at least [from 1.5](https://github.com/kubernetes/kubernetes/blob/release-1.5/test/e2e/job.go#L280-L282)), since they're hitting the currently supported and stable batch endpoint for Jobs.

**Comment by soltysh** [comment]
@skriss I don't think this is a release blocker, either given the explanation above.

**Comment by ethernetdan** [comment]
We should figure out a way to avoid these false positives but agreed not release blocking.

**Comment by soltysh** [comment]
@kubernetes/sig-testing-misc  @kubernetes/sig-api-machinery-misc  what do you think about previous comment, is it doable? How can we achieve this?

**Comment by deads2k** [comment]
> @kubernetes/sig-testing-misc @kubernetes/sig-api-machinery-misc what do you think about previous comment, is it doable? How can we achieve this?

Filtering out false positives?  That will be manual I'm afraid.  The endpoint is gone.  We are starting to push people to choose the "correct" API group now instead of shoving everything into "extensions", so the situation should improve as time goes on.

**Comment by bgrant0607** [comment]
We don't have the mechanism(s) today, but this doesn't need to be manual.

I discuss some ideas for dealing with optional features in the layers doc, and they could apply to deprecated/removed features, also:
https://docs.google.com/document/d/1XkjVm4bOeiVkj-Xt1LgoGiqWsBfNozJ51dyI-ljzt1o/edit#

Or, if we had some notion of which APIs were used by which test and which APIs we expected to work, we could automatically skip tests exercising disabled/removed APIs.

**Comment by soltysh** [comment]
> Or, if we had some notion of which APIs were used by which test and which APIs we expected to work, we could automatically skip tests exercising disabled/removed APIs.

Release notes are a good source for that. I clearly remember stating we are removing extensions/v1beta1.Jobs in my PR comment, see https://github.com/kubernetes/kubernetes/pull/38614, unfortunately that did not happen for the other, but in that case opening an issue is an option.
