### ISSUE TITLE
The "Accelerators" feature should not be turned on if container runtime is not docker

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#42453]
Ref: #42407

The feature relies on docker client being present and will error out if it's not the case. The feature should really be disabled if runtime is not docker.

/cc @kubernetes/sig-node-bugs

**Comment by feiskyer** [comment]
@yujuhong Kubelet already refuses to start if the runtime is not docker (see [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L800)).

**Comment by yujuhong** [comment]
Hm...ok. We can fall back to your PR then
