### ISSUE TITLE
Handle maxUnavailable larger than spec.replicas

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#42479]
We need to gracefully handle the case when a Deployment specifies an absolute value of MaxUnavailable larger than its spec.replicas. I don't think we want to add validation for this, simply collapsing maxUnavailable to spec.replicas would suffice.

@kubernetes/sig-apps-misc

**Comment by wanghaoran1988** [comment]
@kargakis Are you working on this? I am glad to take this if not.

**Comment by kargakis** [comment]
@wanghaoran1988 feel free to work on it
