### ISSUE TITLE
AWS: Support multiple route-tables in kubenet (for private topologies)

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#42487]
jwest on slack explained to me that they have a custom controller which allows kubenet to work with private topologies (i.e. multiple route tables).  It is simply a matter of updating the 3 route tables that match the tag, not bailing out when we see multiple matches.

This might be a little tricky because ideally we would run 3 separate controllers in this case on AWS, but we do have confirmation that if we do this kubenet will work in private topologies.

**Comment by Josh-West-Bose** [comment]
If anybody has questions about what I'm doing with a custom controller, just ask.

**Comment by alexfomin** [comment]
@Josh-West-Bose Could you please provide more details on your custom controller implementation?

**Comment by ApsOps** [comment]
@justinsb I have been facing this issue as well. I have an instancegroup in public subnet and I want to add another instancegroup in private subnet (or at least replace the public instancegroup with a private one).
What is required to accomplish this at this point?

/reopen
