### ISSUE TITLE
cloud-provider openstack: exits immediately without providing --cloud-config

### ISSUE THREAD

**Issue by s-urbaniak** [kubernetes/kubernetes#42483]
**Is this a request for help?** No

**What keywords did you search in Kubernetes issues before filing this one?** openstack controller-manager

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**: OpenStack
- **OS** (e.g. from /etc/os-release): CoreOS stable 1298.5.0
- **Kernel** (e.g. `uname -a`): 4.9.9
- **Install tools**:
- **Others**:

**What happened**:

When starting the controller-manager with `--cloud-provider=openstack` but **without** `--cloud-config` it immediately exits with exit code 255:

```
Mar 03 15:13:15 t460s hyperkube[29753]: F0303 15:13:15.304219   29753 controllermanager.go:280] Cloud provider could not be initialized: could not init cloud provider "openstack": no OpenStack cloud provider config file given
Mar 03 15:13:15 t460s systemd[1]: controller-manager.service: Main process exited, code=exited, status=255/n/a
Mar 03 15:13:15 t460s systemd[1]: controller-manager.service: Unit entered failed state.
Mar 03 15:13:15 t460s systemd[1]: controller-manager.service: Failed with result 'exit-code'.
Mar 03 15:13:15 t460s systemd[1]: controller-manager.service: Service hold-off time over, scheduling restart.
Mar 03 15:13:15 t460s systemd[1]: Stopped Kubernetes Controller Manager.
Mar 03 15:13:15 t460s systemd[1]: controller-manager.service: Start request repeated too quickly.
Mar 03 15:13:15 t460s systemd[1]: Failed to start Kubernetes Controller Manager.
Mar 03 15:13:15 t460s systemd[1]: controller-manager.service: Unit entered failed state.
Mar 03 15:13:15 t460s systemd[1]: controller-manager.service: Failed with result 'exit-code'.
```

Note that when starting the `apiserver` with a similar setup having `--cloud-provider=openstack` set but without any `--cloud-config` it

Also worth mentioning, that this doesn't happen with i.e. `--cloud-provider=aws`.

**What you expected to happen**:

I epect the `controller-manager` to give a warning, but not bail out.

**How to reproduce it** (as minimally and precisely as possible):

Specify `--cloud-provider=openstack` on a working cluster without providing a config.

**Anything else we need to know**:

I am happy to provide a PR to fix the above.

/cc @philips @alexsomesan

**Comment by xsgordon** [comment]
I guess the key for me is, what do you expect `--cloud-provider=openstack` to actually do if there is no configuration? My understanding is we have a number of mandatory values without which we can not interact with the cloud provider, hence if you explicitly ask for the cloud-provider but don't give a config we aren't able to complete the request.
