### ISSUE TITLE
Delete & stop publishing kubernetes-release/release/latest.txt, it is a confused concept

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#42485]
```
gsutil cat gs://kubernetes-release/release/latest.txt
v1.7.0-alpha.0

gs://kubernetes-release/release/v1.7.0-alpha.0/kubernetes.tar.gz.sha1:
    Creation time:          Wed, 22 Feb 2017 05:21:06 GMT
    Update time:            Wed, 22 Feb 2017 05:21:06 GMT
```
It is causing couple of test suites to fail.

cc: @fgrzadkowski @MaciekPytel

**Comment by wojtek-t** [comment]
@k8s-oncall

**Comment by jszczepkowski** [comment]
I've changed the latest release to v1.6.0-beta.1 and rename v1.7.0-alpha.0 directory to v0.0.1.7.0-alpha.0. I hope this should help.

**Comment by mwielgus** [comment]
Same story agian...

**Comment by lavalamp** [comment]
Why is this happening? We should not be fixing this manually if my understanding of it is remotely up to date. @ixdy can you take a look or find someone to look?

**Comment by ixdy** [comment]
I think this is what has always been done - "v1.7.0-alpha.0" is considered "more recent" than any 1.6 (or earlier) branches. `release/stable.txt` points to v1.5.4. `release/latest-1.6.txt` points to `v1.6.0-beta.3` as expected.

**Comment by ixdy** [comment]
I'm not sure what the correct behavior of the `release/latest.txt` file should be. I'll concede that we probably should not have published `v1.7.0-alpha.0`, but let's suppose we cut `v1.5.0-rc.1` this week, thaw the code freeze on master, and then build `v1.7.0-alpha.1` next week. Which should populate `release/latest.txt`?

**Comment by lavalamp** [comment]
Sounds like release/latest.txt is a confused concept that just shouldn't exist.

**Comment by lavalamp** [comment]
Like, maybe a latest-stable is a coherent concept. Maybe we should retcon latest to mean that.

**Comment by ixdy** [comment]
yeah, using `release/latest.txt` and `release/stable.txt` in upgrade tests is also likely to lead to unexpected results. e.g. if a 1.4-1.5 upgrade test uses `release/stable.txt`, it'll be fine for now, but will suddenly upgrade the cluster to 1.6 as soon as 1.6.0 is shipped.

**Comment by ixdy** [comment]
The `release/latest-$VERSION.txt` files have meaning. I'm not sure it's worth fixing `release/latest.txt` - it mostly exists for `ci/latest.txt`.

**Comment by lavalamp** [comment]
I see. We should either have a layer of indirection (`release/current-branches.txt`) or keep a `release/latest.txt`, `release/previous.txt`, and `release/prev-previous.txt` files up to date...

**Comment by lavalamp** [comment]
Or just delete it. :)

**Comment by ixdy** [comment]
I'd probably prefer to just delete the `release/latest.txt` file (and stop generating it, as well), but maybe after 1.6 ships.

Deleting `release/latest.txt` will probably break some things, but nothing *should* be depending on it, so explicit breakage is probably good?

**Comment by lavalamp** [comment]
SGTM. I will retitle this issue and leave it assigned to you :)

**Comment by lavalamp** [comment]
This will give @mwielgus, @jszczepkowski, and @wojtek-t time to change whatever it is they have that depends on this :)

**Comment by ixdy** [comment]
The `ci-kubernetes-e2e-gke-pre-release` and `ci-kubernetes-e2e-gci-gke-pre-release` jobs depend on the `release/latest.txt` file.

These jobs are also ownerless and have been broken for 3 months, so...

**Comment by fgrzadkowski** [comment]
@kubernetes/sig-release-feature-requests
