### ISSUE TITLE
API server cannot find data when switching from etcd2 to etcd3 with custom etcd prefix

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#42505]
1. Start an API server with `--etcd-prefix=foo --storage-backend=etcd2`, populate with data, stop server
2. Migrate etcd2 to etcd3
3. Restart the API server with `--etcd-prefix=foo --storage-backend=etcd3`
4. All data is missing from the API.

The etcd2 client takes the configured prefix and passes it to the etcd client as `path.Join("/"+prefix)`. The etcd3 client simply passes in the configured prefix.

`path.Join("/"+prefix)` is a no-op on the default prefix (`/registry), but can modify custom prefixes that did not start with a slash.

cc @enj @smarterclayton

**Comment by liggitt** [comment]
I think we have to preserve the `path.Join("/"+prefix)` behavior from the etcd2 client setup.

It's a no-op for the default prefix, but requiring a change to a custom prefix when switching from etcd2 to etcd3 is *really* unexpected, especially when the failure mode is that the apiserver starts up as if it's a brand new cluster (including creating default projects, kubernetes service, etc)

**Comment by liggitt** [comment]
cc @kubernetes/sig-api-machinery-misc @lavalamp @timothysc @wojtek-t @xiang90

**Comment by smarterclayton** [comment]
Throwing release blocker on here just so we don't lose it (given data loss potential)

**Comment by wojtek-t** [comment]
@liggitt - thank for debugging and fixing it.
