### ISSUE TITLE
GCE Ingress (GLBC) needs improved federation handling at ingress deletion time

### ISSUE THREAD

**Issue by csbell** [kubernetes/kubernetes#42511]
While GLBC has been coaxed to handle duplicate Ingress objects at creation time, it needs more logic to correctly handle deletion of federated ingresses. Currently, deleting one of the ingress objects outside of  federation will cause the entire ingress to be torn down. Eventually the federated controller re-creates the ingress object but the downtime should be omitted altogether. Possible solutions include some form of adhoc refcounting mechanism or augmenting GLBC to notice that there are more than one relevant forwarding rules attached to an ingress object at deletion time. Details and design to be hashed out still.

**Comment by marun** [comment]
Given that this appears to require considerable work to accomplish, I'm moving to 1.8.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#109.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
