### ISSUE TITLE
Fluentd-gcp CPU usage regression

### ISSUE THREAD

**Issue by Crassirostris** [kubernetes/kubernetes#42515]
In `fluentd-gcp:2.0` CPU usage went up significantly compared to `fluentd-gcp:1.8`

It consumes more than one core even when there's no significant logging load on the node.

Two changes between those version:

* [Monitoring](https://github.com/kubernetes/kubernetes/pull/41567)
* [New base image](https://github.com/kubernetes/kubernetes/pull/41998)

CC @piosz @igorpeshansky @qingling128 @timstclair

**Comment by igorpeshansky** [comment]
Ruby by default is single-core, so anything over that is likely introduced by the [monitoring](https://github.com/kubernetes/kubernetes/pull/41567) changes. But we'd need to investigate to make sure.

**Comment by piosz** [comment]
Can you please disable monitoring and see whether this is the problem?

**Comment by piosz** [comment]
I meant @crassirostris, can you ...

**Comment by crassirostris** [comment]
@piosz Was going to do this, yes

**Comment by crassirostris** [comment]
@piosz Built container manually without prometheus plugin, still consumes 1.7 cpu

**Comment by piosz** [comment]
Can you please find the difference then?

**Comment by crassirostris** [comment]
Used new image with the old configuration ([exactly before the monitoring](https://raw.githubusercontent.com/kubernetes/kubernetes/e8de31623f17d33e2e1b4b93ecab7ab3a7b81c22/cluster/addons/fluentd-gcp/fluentd-gcp-image/fluent.conf)), still 1.7 cores

It seems like a problem with the new image for some reason. @timstclair FYI

**Comment by crassirostris** [comment]
@repeatedly What can consume 1.7 cores with the same configuration on a different machine? How to debug this?

**Comment by repeatedly** [comment]
> What can consume 1.7 cores with the same configuration on a different machine?
> Used new image with the old configuration (exactly before the monitoring), still 1.7 cores

Does this mean all components are same, ruby version, plugins and configuration settings?
What are the differences between old and new image? OS or other parts are also different?

**Comment by crassirostris** [comment]
@repeatedly 

There are at least the following changer

* Ubuntu Trusty -> Debian Jessie
* td-agent package -> manually installed
  * embedded ruby -> ruby 2.1
  * embedded gems -> fixed version gems from Gemfile
  * embedded libjemalloc -> [libjemalloc1 from debian repos](https://packages.debian.org/jessie/libjemalloc1)

I understand that it's a lot of changes and I'm going to narrow the problem down, the main question is where to look and how to debug to speed this process up?

**Comment by piosz** [comment]
If this is not fixed before Monday we will revert #41998.

cc @fgrzadkowski @timstclair @ixdy

**Comment by crassirostris** [comment]
@piosz Only https://github.com/kubernetes/kubernetes/pull/42130 and https://github.com/kubernetes/kubernetes/pull/42126 should be reverted, not https://github.com/kubernetes/kubernetes/pull/41998

**Comment by piosz** [comment]
No, we want to revert migration to the new base image. The changes to extract configuration into env var/config map should preserve. This mean that the revert might not be straightforward.

**Comment by crassirostris** [comment]
@piosz I think our backup option is to switch back to using td-agent package, not reverting whole change, because https://github.com/kubernetes/kubernetes/pull/41998 is also about security and we don't want to revert that

I will check whether that helps

**Comment by timstclair** [comment]
Thanks for investigating this! I have a couple comments:

- The full package diff can be found here: https://github.com/timstclair/kubernetes/commit/3fb704f977875bb4cbb64687b2f6836fbe101cf6
- The first thing I would look at is whether the ruby version makes a difference. I believe td-agent was using 2.3
- The main benefit of https://github.com/kubernetes/kubernetes/pull/41998 is actually _not_ using td-agent, since the td-agent package includes lots of stuff we don't use (e.g. rails). Maybe if we need to fallback we could manually remove those extra packages.

I'll poke around in the container and see if anything jumps out.

**Comment by crassirostris** [comment]
@timstclair Thanks for the comments, they totally make sense. Also, thanks for the diff.

> I'll poke around in the container and see if anything jumps out.

Thanks!

**Comment by timstclair** [comment]
Actually td-agent was using ruby 2.1:
```
$ /opt/td-agent/embedded/bin/ruby --version
ruby 2.1.10p492 (2016-04-01 revision 54464) [x86_64-linux]
```

**Comment by timstclair** [comment]
A manual search through commenting out parts of the config file revealed that removing the systemd config solves the issue:
```
    # Logs from systemd-journal for interesting services.
    <source>
      type systemd
      filters [{ "_SYSTEMD_UNIT": "docker.service" }]
      pos_file /var/log/gcp-journald-docker.pos
      read_from_head true
      tag docker
    </source>
    <source>
      type systemd
      filters [{ "_SYSTEMD_UNIT": "kubelet.service" }]
      pos_file /var/log/gcp-journald-kubelet.pos
      read_from_head true
      tag kubelet
    </source>
```

I'll play around with the systemd libraries and see if I can figure out what's going on here.

**Comment by timstclair** [comment]
Still investigating, but I think this may be a regression in the fluent-plugin-systemd library between version 0.0.5 (old image) and 0.0.7 (new image). I realized the diff I linked above was not in sync with the version that was actually pushed (gcr.io/google-containers/fluentd-gcp:2.0). That diff is here, and accurately reflects the change in the systemd library: https://github.com/timstclair/kubernetes/commit/28abb280536863f261983bc8d89892169956ed29

**Comment by timstclair** [comment]
Confirmed this is a regression in `fluent-plugin-systemd 0.0.7` (0.0.6 does not have the problem). Fortunately 0.0.7 only has a single commit, https://github.com/reevoo/fluent-plugin-systemd/commit/bcbd53ed42b85df5e8ec9b42410bf43a4d0c2683. I'll file an issue on the plugin.

In the meantime, I'll send a PR to pin fluent-plugin-systemd to 0.0.6.

**Comment by crassirostris** [comment]
@timstclair Thanks a huge lot for investigating this!

**Comment by timstclair** [comment]
Reopening to track the version bump.

**Comment by repeatedly** [comment]
Good investigation. Latest systemd plugin uses ` @journal.wait(0)` and it seems to cause busy loop like problem.

**Comment by errm** [comment]
Hi I just released `fluent-plugin-systemd 0.0.8` that should fix this issue.

**Comment by crassirostris** [comment]
@errm Thanks! And thanks to @timstclair who already included it into our image :)

**Comment by errm** [comment]
Yeah thanks @timstclair your too fast for me :)

**Comment by piosz** [comment]
Thank you a lot @timstclair for the investigation.
