### ISSUE TITLE
CachedDiscoveryInterface.Fresh() should return false if it's using cached data

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#42516]
The `DeferredDiscoveryRESTMapper` uses `CachedDiscoveryInterface` (`CDI`) in its methods, if the initial query via `CDI` [fails and `!CDI.Fresh()`](https://github.com/kubernetes/kubernetes/blob/320f7ce6f348a85a9a27e128e0eddee023e7478c/staging/src/k8s.io/client-go/discovery/restmapper.go#L198), the resmapper invalidates the `CDI` and contacts the server directly.

Currently [`CDI.Fresh()`](https://github.com/kubernetes/kubernetes/blob/320f7ce6f348a85a9a27e128e0eddee023e7478c/staging/src/k8s.io/client-go/discovery/discovery_client.go#L55-L56) returns true "if no cached data was used that had been retrieved before the instantiation". I think it should be changed to "returns true if no cached data was used". Because for example, a TPR could be registered after CDI has been instantiated and has retrieved its own cache, then `DeferredDiscoveryRESTMapper` will wrongly return an error saying the TRP doesn't exist.

The current semantic works for kubectl, because each invocation of kubectl instantiates a new CDI. However, it fails if a long running process like the garbage collector tries to use the `DeferredDiscoveryRESTMapper`.

I cannot find the history of this file, I guess it's authored by @deads2k?

**Comment by liggitt** [comment]
What would you expect it to do? You could pair it with a ticking call to Reset() to force refreshing

**Comment by deads2k** [comment]
> I cannot find the history of this file, I guess it's authored by @deads2k?

@sttts actually.

I don't see what a caller to the cachediscoveryrestmapper would do in the case you've described.  It seems like you want  behavior similar to what we built, where you try to refresh your caches on lookup misses.

**Comment by caesarxuchao** [comment]
> where you try to refresh your caches on lookup misses.

Yes, that's what I expected, refreshing on every restmapper lookup miss. The current behavior is different though, the cache if refreshed only if there is a cache miss *[and](https://github.com/kubernetes/kubernetes/blob/320f7ce6f348a85a9a27e128e0eddee023e7478c/staging/src/k8s.io/client-go/discovery/restmapper.go#L198)* the cache is not "[Fresh()](https://github.com/kubernetes/kubernetes/blob/320f7ce6f348a85a9a27e128e0eddee023e7478c/staging/src/k8s.io/client-go/discovery/discovery_client.go#L56)". 

Perhaps we should update the restmapper to always refresh? If that's the case, the title of issue is misleading.

**Comment by liggitt** [comment]
Refresh on max age of cached data and refresh on miss are two normal behaviors that could be built on top of what is there.

**Comment by caesarxuchao** [comment]
@liggitt are you suggesting that i should implements another restmapper that refreshes "on max age of cached data and on cache miss"?

The current DeferredDiscoveryRESTMapper refreshes on max age of cached data, but not on cache miss. Is the the "not refreshing on cache miss" part significant? Who needs this behavior?

**Comment by liggitt** [comment]
If I do `kubectl create -f dir` with a folder that has 10 resources not present on the specified server, I would not expect kubectl to run discovery 10 times. 

If the garbage collection controller has an object with a bad ownerRef to a resource that doesn't exist, I would not expect the garbage controller to rerun discovery every few milliseconds as it backs off retrying handling the ownerRef.

**Comment by caesarxuchao** [comment]
> If I do kubectl create -f dir with a folder that has 10 resources not present on the specified server, I would not expect kubectl to run discovery 10 times.

True. But to be fair this is a rare use case and we never worried about the performance of kubectl or the workload caused by it.

> If the garbage collection controller has an object with a bad ownerRef to a resource that doesn't exist, I would not expect the garbage controller to rerun discovery every few milliseconds as it backs off retrying handling the ownerRef.

I don't agree with this example. The garbage collector should be responsive rather than waiting for the cache to be refreshed periodically, so it should rerun the discovery asap. The hotloop is solved by the ratelimited queue.

**Comment by sttts** [comment]
`CachedDiscoveryInterface`'s heuristic is really only meant for short living rest mappers as in kubectl. I would avoid making this even more complicated for the long-running case. Rather we should think about watchable discovery for 1.7, i.e. turning the discovery endpoints into its own resource with WATCH support.

**Comment by caesarxuchao** [comment]
Ok. I think my initial confusion around `CachedDiscoveryInterface` and `DeferredDiscoveryRESTMapper` is solved. GC is going to use the `DeferredDiscoveryRESTMapper` differently in #42615. Closing this issue.
