### ISSUE TITLE
Declutter history logs

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#4251]
[Following our off-topic conversation with @brendanburns [here](https://github.com/GoogleCloudPlatform/kubernetes/pull/4065#issuecomment-72930871)]

@brendanburns there is a way but both the author of the commit and the guy who merges the commit into the tree (commiter) have to use `git` a bit more and not just the Github UI.

The author has to:
* work on a `feature_branch`

```bash
$ git checkout -b feature_branch
# makes changes, git add, git commit, git push to local branch
```

* rebase changes on top of the current `master`, **IF** his/her local `master` is behind

```bash
$ git checkout master
$ git fetch upstream
$ git merge upstream/master
$ git checkout feature_branch
$ git rebase master
$ git push origin feature_branch -f
```

On the other side, instead of clicking a button, the commiter has to:
* pull `feature_branch` from author's remote repository where the pr is coming from

```bash
$ git checkout -b feature_branch
$ git pull https://github.com/author/repo.git feature_branch
```

* and merge it manually
```bash
$ git checkout master
$ git merge --ff-only feature_branch
$ git push origin master
```

Thanks to @davecgh for sharing this process.

ps. @davecgh mind reviewing that the process I have documented here is correct? Thanks!

**Comment by davecgh** [comment]
I'd always use the `--ff-only` flag if that is your intention.  Otherwise, you'll end up with a merge commit when it's not capable of being fast-forwarded.  The flag intentionally prevents the merge from happening when it's not a fast forward.

**Comment by kargakis** [comment]
So you always use `--ff-only` and in case it fails, you fall back to normal `git merge`. Great, thanks again @davecgh !

**Comment by davecgh** [comment]
No, if it fails, the user need to pull the latest master, rebase their branch on top of it, and force push the branch back to github so the PR is updated.  Then it won't fail.

**Comment by kargakis** [comment]
:+1:

**Comment by kargakis** [comment]
What this issue suggests is unfortunately impossible to happen due to the ratio things get into master.
