### ISSUE TITLE
kubectl should use TPR full name instead of subname

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#42521]
### Problem Statement

Currently, if I register two kinds of TPR that has the same subname, for example:
```
$ kubectl get thirdpartyresource 
NAME                      DESCRIPTION             VERSION(S)
cluster.aws.com           Managed etcd clusters   v1beta1
cluster.etcd.coreos.com   Managed etcd clusters   v1beta1
```

When I use `kubectl get cluster`, it will actually list `cluster.aws.com`. This is misleading and confusing, in some sense, hijacking.

It also causes security concerns. For example, I create:
```
$ kubectl get thirdpartyresource 
pod.aws.com               Managed etcd clusters   v1beta1
```

On GKE 1.5.3, when I `kubectl get pod`, it list `pod.aws.com`:
```
$ kubectl get pod
NAME                   KIND
example-etcd-cluster   Pod.v1beta1.aws.com
```
This is HIJACKING `Pod` kind.

**Comment by xiang90** [comment]
```
$ kubectl get pod
NAME                   KIND
example-etcd-cluster   Pod.v1beta1.aws.com
```

This seems very bad. If someone accidentally creates a TPR with POD kind, it will break all other users suddenly and silently?

**Comment by hongchaodeng** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/42275 always prefers resources in the v1 ungrouped API when there is ambiguity. I could see backporting that to 1.5. 

Creating a TPR is a privileged operation. I'm not sure how someone would accidentally create a TPR.

**Comment by hongchaodeng** [comment]
Hi @liggitt 

Thanks for replying.

> #42275 always prefers resources in the v1 ungrouped API when there is ambiguity.

That's great. But it only solved part of the problem, not all of it. We can't assume people won't create TPR "accidentally". Something like https://github.com/kubernetes/kubernetes/pull/41572 to solve it completely would be preferred.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/41572 wouldn't affect this. TPRs show up in discovery with a group name. We would not prevent a resource named "pods" in another group (since the fully qualified name is unambiguous). This issue is about how kubectl resolves an ambiguous resource name if no group is provided. The agreed on approach is to resolve to v1 resources first, then resolve in order of discovery information published by the server.

**Comment by xiang90** [comment]
> since the fully qualified name is unambiguous

this is great. and we should not prevent from it to be created.

> how kubectl resolves an ambiguous resource name if no group is provided

My question is why should kubectl resolve resource name when there is a conflict and ambiguity. I can see only risk and confusion. Can you explain the reason behind it? I am sure I miss something here.

**Comment by xiang90** [comment]
> Creating a TPR is a privileged operation. I'm not sure how someone would accidentally create a TPR.

I do not think you catch the point. I meant `creating a TPR with a conflict Kind will suddenly break users`. To remove the potential accidents without changing today's behavior, it requires the cluster admin(or admins) to keep track of ALL TPR kinds. So they can never risk to overwrite a kind name. With the growing number of TPR kinds, this task is hard.

**Comment by liggitt** [comment]
Think of it like dns name resolution, where the suffix search order is defined by the cluster administrator. 

resolution order is required for forward compatibility, makes the typical use case more convenient, and allows for fully specified resource references. 

See discussions in 
https://github.com/kubernetes/kubernetes/issues/13929
https://github.com/kubernetes/kubernetes/pull/15874

**Comment by xiang90** [comment]
> where the suffix search order is defined by the cluster administrator.

as an administrator, how should I specify the order explicitly?

**Comment by xiang90** [comment]
@liggitt 

> Think of it like dns name resolution, 

This is different. If I type `etcd`, I will not be direct to etcd.coreos.com nor etcd.k8s.io. I have to type in etcd.io or etcd.k8s.io. The naming itself is not ambiguous. The resolution might be. But it seems to me that here both the naming and resolution mechanisms are not explicitly and controllable.

**Comment by liggitt** [comment]
Position in discovery is controlled by the priority field when registering an APIService (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1alpha1/types.go#L54)

TPR registration does not allow control of priority today. That's one of the aspects of the TPR design that needed to be completed. 


>> Think of it like dns name resolution,
>
> This is different. If I type etcd, I will not be direct to etcd.coreos.com nor etcd.k8s.io. I have to type in etcd.io or etcd.k8s.io.

You will depending on your resolv.conf search paths (see behavior of service dns name resolution within pods)

> But it seems to me that here both the naming and resolution mechanisms are not explicitly and controllable.

They are explicitly defined by server discovery order. TPR discovery order is not controllable today. That will need to be part of the TPR design (added to the list of outstanding capabilities in https://github.com/kubernetes/features/issues/95)

**Comment by xiang90** [comment]
> Position in discovery is controlled by the priority field when registering an APIService (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1alpha1/types.go#L54)

Thanks for sharing this.

> You will depending on your resolv.conf search paths (see behavior of service dns name resolution within pods)

I was not aware of that we can define similar thing in k8s context (the ordering).

>  TPR discovery order is not controllable today. 

I am more care about TPR here. The core API are controlled by k8s developers, so it is less possible to cause confusions and conflicts.

**Comment by smarterclayton** [comment]
There will always be duplicate resource names across groups - that's part of why groups exist.

This is why tpr is really alpha :)

**Comment by xiang90** [comment]
@smarterclayton Right.

My concern is that TPR kind should never overwrite core object by default (the pod example). Also TPR probably do not need auto resolution when there is a conflict. Or we have to provide a global dynamic control over the resolution of all TPRs to cluster admins, which seems to be hard.

**Comment by liggitt** [comment]
To be clear, server side there is no overwriting. The APIs are distinct, the storage is distinct, and you cannot submit a core Pod object to a TPR Pod.mygroup.io API. 

> TPR probably do not need auto resolution when there is a conflict

You do if you want to avoid breaking users that started using the short name of a TPR before a second resource was introduced that made it ambiguous (this is what I meant by forward compatibility)

Imagine you add a TPR foo.group1.io and users start using it as `kubectl get foo`

Now you add a TPR foo.group2.io

You can either allow the cluster admin to specify that group1.io should have priority, or you break all the users that were using `kubectl get foo` with a message that their input is now ambiguous. We chose the former approach for compatibility and convenience (even though there is still work to allow the cluster admin to indicate which TPR should have priority)

Also, as a best practice for maximum portability, when scripting kubectl, you should use the fully qualified resource

**Comment by chancez** [comment]
I think that the above points make sense WRT allowing the admin to control priority of resolution for these things. I like the idea of doing this to allow more ergonomic kubectl usage, etc.

However I do think both kubectl and the apiserver should also provide an configuration option that never allows non-qualified resource kinds to be used. Similar to allowing the admin to assign priority of resolution, I'd like to prevent users from every having the opportunity to use an unqualified name. Id like to remove the possibility that any script they've written could become ambiguous for any reason if possible.

I think if resolution priority is being considered, then at the very least, having additional validators at the API server layer should also be done. I don't see any way in https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1alpha1/types.go#L54 to specify something like this, so where might that live? Essentially, this would make the "Priority" field ignored, and anything unqualified with the group name in kubectl would be rejected by the API as a validation error (if the API server was configured to disallow this).

**Comment by liggitt** [comment]
> anything unqualified with the group name in kubectl would be rejected by the API as a validation error

Nothing unqualified ever hits the API server today… it does not accept ambiguous data. All the resolution happens client side

**Comment by chancez** [comment]
Right, what I'm looking for is a way to configure your API server to tell kubectl that resolution isn't allowed, and results must be qualified, and that if they are not, kubectl should error, rather than performing resolution.

**Comment by liggitt** [comment]
> I think if resolution priority is being considered, then at the very least, having additional validators at the API server layer should also be done

I'm not sure what validation you expect in the API server layer

> I don't see any way in https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1alpha1/types.go#L54 to specify something like this

Those objects are not exposed to end users, they provide information the API server uses to build discovery information presented to end user clients. The priority simply determines the position in the list of API groups

**Comment by chancez** [comment]
I'm just stating what I'd like to see based on what was said above, assuming TPR registration was to eventually allow control of priority:

> You can either allow the cluster admin to specify that group1.io should have priority, ....

Allowing a cluster admin to specify the priority of an API group would be great at some point. But I think there needs to be more than just the ability to define ordering of API group name resolution when it comes to kubectl.

> ... or you break all the users that were using kubectl get foo with a message that their input is now ambiguous.

I would also expect in addition to priority of resolution, I would be able to enforce that kubectl would not except the usage of resource kinds without their API group, unless it's a built in resource. I would like to be able to set a policy that would only allow `kubectl get clusters.etcd` or `kubectl get clusters.elasticsearch` but never just `kubectl get clusters` since that would be ambiguous.

I basically want to take away the potential for there to be ambiguity, since kubectl is heavily used in scripts and automation, it just makes sense to also be able to control things like whether or not it performs "API group resolution" at all.

**Comment by sdminonne** [comment]
cc

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/apiextensions-apiserver/issues/11.

**Comment by nikhita** [comment]
Can someone update the issue title to CRD instead of TPR? Thanks!

**Comment by nikhita** [comment]
This issue was originally for TPRs. For CRDs, we have the opposite problem.

If we use `kubectl get pod`, it will list the native `Pod` and not the CRD `pod`. However, this ends up hijacking the CRD.

I think we should not allow CRDs having names same as native resources. Wdyt?

**Comment by liggitt** [comment]
> I think we should not allow CRDs having names same as native resources. Wdyt?

No, the ability to use the same name in different groups was a key feature of API groups

**Comment by nikhita** [comment]
@liggitt How about establishing a priority?

**Comment by liggitt** [comment]
We already have that: the order listed in discovery, which is what kubectl uses to resolve ambiguous names, and is controlled by priority fields in registered APIService objects.

**Comment by sttts** [comment]
> We already have that: the order listed in discovery, which is what kubectl uses to resolve ambiguous names, and is controlled by priority fields in registered APIService objects.

I noticed in one of my discovery cache files, that we have a strange order right now: apps, extensions, ...., CRD groups, core/v1.

@liggitt do you refer to this order? I would have expected core/v1 first. Is it a bug?

**Comment by liggitt** [comment]
core/v1 is always first, followed by group/version order in `~/.kube/cache/discovery/$host/servergroups.json`

**Comment by sttts** [comment]
It should, but: https://gist.github.com/sttts/5e5a087fb8e7afc69c2ceda20257a45d

```
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5-gke.0", GitCommit:"2c2a807131fa8708abc92f3513fe167126c8cce5", GitTreeState:"clean", BuildDate:"2017-12-19T20:05:45Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

And the same for OpenShift: https://gist.github.com/sttts/c62fe2be4fdc1b31449377b9bf6a47d1

```
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6+a08f5eeb62", GitCommit:"c84beff", GitTreeState:"clean", BuildDate:"2017-11-02T14:28:07Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sttts** [comment]
> core/v1 is always first

Or do you mean we have logic in place that fixes the wrong discovery order for core/v1? Then it's fine.

**Comment by liggitt** [comment]
looks like we pin "v1" first here:
https://github.com/kubernetes/kubernetes/blob/068e1642f63a1a8c48c16c18510e8854a4f4e7c5/staging/src/k8s.io/client-go/discovery/restmapper.go#L41-L47

for consistency, I'd also expect us to do the same here:
https://github.com/kubernetes/kubernetes/blob/068e1642f63a1a8c48c16c18510e8854a4f4e7c5/staging/src/k8s.io/client-go/discovery/discovery_client.go#L125-L153

**Comment by nikhita** [comment]
@liggitt From your comment in https://github.com/kubernetes/kubernetes/issues/42521#issuecomment-284167815:

> TPR registration does not allow control of priority today. That's one of the aspects of the TPR design that needed to be completed.

> They are explicitly defined by server discovery order. TPR discovery order is not controllable today. That will need to be part of the TPR design 

Wdyt about controlling this with another field in the CRD spec?

**Comment by liggitt** [comment]
I probably wouldn't expose that...

**Comment by MrHohn** [comment]
cc @bowei
