### ISSUE TITLE
[Scheduler]Should we respect the initContainers when priority the node?

### ISSUE THREAD

**Issue by wanghaoran1988** [kubernetes/kubernetes#42539]
Should we respect the initContainers when priority the node?
I saw we respect initContainer  when [predicts](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L471) the node,but cannot found  when [priority](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/priorities/balanced_resource_allocation.go#L40) the node ,or I missed something here?

**Comment by wanghaoran1988** [comment]
@timothysc @k82cn

**Comment by k82cn** [comment]
@wanghaoran1988 , I'm not sure whether this's designed behavior, but I'd suggest to keep it for priority: the initContainers will exit after finished its Pod initialization works, it's better to exclude initContainer's request for long term: initContainers exited and real containers started.

for predicts, I think the resource maybe also exhausted for burst Pods as the initContainers are not considered when assumed or added Pods. (burst Pods pattern: start lots of Pods and initContainers take long time to finish.)

The key of those issue is that: the initContainers will exit, and scheduler did not trace Pods's status, e.g. initialized (all initContainers succeed). For now, I'd suggest to keep it as is before we got more feedback from users; cc/ @kubernetes/sig-scheduling-misc for more inputs.

**Comment by smarterclayton** [comment]
We discussed this in the design proposal, but because init containers may
be re-executed at any time on the node, we can't ignore that as a
possibility (otherwise it might cause unintentional evictions).

**Comment by k82cn** [comment]
Do you mean we should handle this in scheduler?
For the case that initContainer required more resources than containers, should  scheduler update resources accordingly when initContainers finished?

**Comment by davidopp** [comment]
Using max(max(init containers), sum(regular containers)) for the resource predicate, as we're doing today, seems like the right thing to do.

As for the original question @wanghaoran1988 asked, whether we should also include it in the resource priority function, I think it's hard to know. Since the pod isn't using the init container resources in steady-state, ignoring init containers as we are doing today is probably fine.

**Comment by wanghaoran1988** [comment]
@davidopp Thanks, sounds reasonable to me. Feel free to close this if you don't think it's  a problem
