### ISSUE TITLE
Controllers sometimes aren't properly started in e2e

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#42532]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-proto/4867/#k8sio-deployment-scaled-rollout-deployment-should-not-block-on-annotation-check

The deployment controller never started, see all the deployment e2e tests fail. Try to search deployment_controller in the controller manager logs, you won't get anything back.

cc: @kubernetes/sig-testing-bugs

**Comment by kargakis** [comment]
Replica set controller never started in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-proto/4867/

**Comment by kargakis** [comment]
A bunch of @kubernetes/sig-apps-test-failures because of this

**Comment by smarterclayton** [comment]
Interesting - is this a deadlock / wedge in shared informers?  @ncdc

**Comment by kargakis** [comment]
@deads2k

**Comment by deads2k** [comment]
> Interesting - is this a deadlock / wedge in shared informers? @ncdc

No.  The only way to get the `controllermanager.go:409] Skipping "replicaset"` message is if the resource is disabled on the API server: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/extensions.go#L59 .

**Comment by deads2k** [comment]
@kargakis did it start after we merged @liggitt's https://github.com/kubernetes/kubernetes/pull/42267?

**Comment by kargakis** [comment]
> @kargakis did it start after we merged @liggitt's #42267?

Doesn't seem like it. Both jobs I linked are from Feb.

**Comment by deads2k** [comment]
> Doesn't seem like it. Both jobs I linked are from Feb.

Oh, maybe that pull fixed it then. We were getting back empty lists of resources with forbidden before and caching them, which made whacky things happen.

**Comment by ncdc** [comment]
It sounds like this is possibly fixed now that 42267 is in?

**Comment by kargakis** [comment]
I hope so

**Comment by liggitt** [comment]
closing based on #42267
