### ISSUE TITLE
[kubelet] ignore keyword "options" define in /etc/resolv.conf, only look for nameserver and search

### ISSUE THREAD

**Issue by pawankkamboj** [kubernetes/kubernetes#42542]
**Kubernetes version**
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
3.10.0-327.36.3.el7.x86_64
CentOS Linux release 7.2.1511 (Core) 

**cluster information**
NAME                                 STATUS    AGE
kube2master1.yatra.com   Ready      41d
kube2node1.yatra.com      Ready      41d
kube2node2.yatra.com     Ready       41d

**kubelet is running with option --resolv-conf to include custmize resolv.conf file** 
root     28235     1  3 09:44 ?        00:00:04 /usr/bin/kubelet --address=0.0.0.0 --port=10250 --pod-infra-container-image=registry.access.redhat.com/rhel7/pod-infrastructure:latest --kubeconfig=/etc/kubernetes/kubeadminconfig --require-kubeconfig=true --pod-manifest-path=/etc/kubernetes/manifests --logtostderr=true --v=0 --allow-privileged=true --resolv-conf=/etc/kube-resolv.conf

**content of /etc/kube-resolv.conf**
options timeout:1
options ndots:5
nameserver 100.64.0.10
nameserver 172.16.1.246
nameserver 172.16.1.247

kubelet remove options define in above /etc/kube-resolv.conf file, it only pickup nameserver and search keyword, does not look for options keyword, it should look for it also.
~]# kubectl exec -t busybox -- cat /etc/resolv.conf 
nameserver 100.64.0.10
nameserver 172.16.1.246
nameserver 172.16.1.247
options ndots:5

** cluster dns is working fine
~]# kubectl get svc
NAME         CLUSTER-IP     EXTERNAL-IP   PORT(S)         AGE
kubernetes   100.64.0.1       <none>         443/TCP            41d
nginx             100.67.5.184   <nodes>       80:30010/TCP   4d

~]# kubectl exec -t busybox -- nslookup nginx.default.svc.kubernetes
Server:    100.64.0.10
Address 1: 100.64.0.10 kube-dns.kube-system.svc.kubernetes

Name:      nginx.default.svc.kubernetes
Address 1: 100.67.5.184 nginx.default.svc.kubernetes

** issue **
since kube-dns only resolv service related svr records but if there an entry which it does not have then it go for next nameservers and there is 5 second timeout between nameserver. although dnsmasq is there for caching records but 5 second timeout is very high for our app setup.
we want to add below options timeout:1 so that if entry o not find in first nameserver it should not wait for 5 second to resolve entry, default is 5 sec in resolv.conf, want to keep only 1 second. I think kubelet should look for options keyword also in resolv.conf file, as of now it is looking for nameserver and search field as define in function parseResolvConf(kubelet_network.go)

207 // parseResolveConf reads a resolv.conf file from the given reader, and parses
208 // it into nameservers and searches, possibly returning an error.
209 // TODO: move to utility package
210 func (kl *Kubelet) parseResolvConf(reader io.Reader) (nameservers []string, searches []string, err error) {
211         file, err := ioutil.ReadAll(reader)
212         if err != nil {
213                 return nil, nil, err
214         }
215 
216         // Lines of the form "nameserver 1.2.3.4" accumulate.
217         nameservers = []string{}
218 
219         // Lines of the form "search example.com" overrule - last one wins.
220         searches = []string{}
221 
222         lines := strings.Split(string(file), "\n")
223         for l := range lines {
224                 trimmed := strings.TrimSpace(lines[l])
225                 if strings.HasPrefix(trimmed, "#") {
226                         continue
227                 }
228                 fields := strings.Fields(trimmed)
229                 if len(fields) == 0 {
230                         continue
231                 }
232                 if fields[0] == "nameserver" {
233                         nameservers = append(nameservers, fields[1:]...)
234                 }
235                 if fields[0] == "search" {
236                         searches = fields[1:]
237                 }
238         }
239 
240         // There used to be code here to scrub DNS for each cloud, but doesn't
241         // make sense anymore since cloudproviders are being factored out.
242         // contact @thockin or @wlan0 for more information
243 
244         return nameservers, searches, nil
245 }

I did not find a way to set timeout 1 second for pods resolv.conf, if anyone have please help.

**Comment by thockin** [comment]
I think we don't parse options to inherit, which is the same as Docker.

@bowei

**Comment by pawankkamboj** [comment]
Is there any other option to customize resolve.conf?

**Comment by jellonek** [comment]
No, there is not any at this point.
But this would be easy to add options passing support.

**Comment by phsiao** [comment]
Would love to see the options passing supported.   It is important in our environment to be able to configure timeout, attempts, and rotate in addition to ndots so our redundant resolvers can be used properly.

**Comment by kpichardie** [comment]
Same here, I have issue in resolving external services due to ndots pretty high, and unfortunately we can't pass options to kubelet. Would be much appreciated.

**Comment by buyID** [comment]
we also want to set timeout 1 second for pods resolv.conf，hope to see support this options.

**Comment by MrHohn** [comment]
Ref the on-going proposal https://github.com/kubernetes/community/pull/1276.

**Comment by thockin** [comment]
Why are you experiencing so many timeouts that this matters?  Timeouts are not normal.

**Comment by phsiao** [comment]
For our use case, we don't use the kube-dns as pod's resolver, and we delegate cluster domain to kube-dns pods.   Each of our datacenter has at least two resolvers, and that allows us to do regular maintenance on the resolver hosts without extended disruptions.   Timeouts is important as that help detect the issue and can rotate to use another resolver while the other one is down for maintenance.

**Comment by matthiasr** [comment]
#54773 only solves this for the dnsPolicy: Default. Should we open a new issue for dnsPolicy: ClusterFirst?

**Comment by phsiao** [comment]
https://github.com/kubernetes/community/pull/1276 Should cover the ClusterFirst or more general use cases.
