### ISSUE TITLE
Add service.ns.svc.cluster.local to resolv.conf search domains in StatefulSet pods

### ISSUE THREAD

**Issue by cap10morgan** [kubernetes/kubernetes#42544]
FEATURE REQUEST:

Pods in StatefulSets should be able resolve their peers via short hostnames. For example, if I create a rabbitmq StatefulSet, I should be able to resolve `rabbitmq-0` from `rabbitmq-1` or any other pod in the StatefulSet.

This could be achieved by adding service.ns.svc.cluster.local to the search domains in `/etc/resolv.conf` (in addition to the ns.svc.cluster.local and others already present).

In the case of RabbitMQ in particular, this would make clustering *much* easier to setup. RabbitMQ clustering requires that node names match the hostname that other cluster members can use to connect to it, and it defaults to `hostname` which returns the short hostname when running the official rabbitmq docker image under k8s. So the nodes are already getting names like `rabbit@rabbitmq-0` and if running `rabbitmqctl join_cluster rabbit@rabbitmq-0` could resolve the `rabbitmq-0` part, it would Just Work™.

But this seems like a nice convenience and logical feature for StatefulSets in general (i.e. not RabbitMQ specific) since there is inherent identity attached to these ordinal hostnames.

I imagine the primary downside is the strict limit on search domains imposed by some resolver libraries. If that means the extra search domain shouldn't be added by default for all StatefulSets, is there some other way to achieve it?

**Comment by thomas-b-jackson** [comment]
I expect statefulsets to behave this way. Would be nice if this fix got combined with a feature that auto-creates the required headless service. That service feels pretty hacky if all you want is in-cluster hostname resolution.

**Comment by EvanMulawski** [comment]
Ran into this issue trying to set up a RabbitMQ cluster on OpenShift. Can't seem to find any workaround. What is the status on this?

**Comment by schaefec** [comment]
Experiencing the exact same issue. Any news about the possibility to add the service name of the statefulset to the search list (as described by cap10morgan)?

**Comment by anlunas** [comment]
+1

**Comment by mattenklicker** [comment]
In case of rabbitmq you can work around this by adding the service name to `cluster_nodes` of your rabbit config and to the `StatefulSet`.
```yaml
env:
  - name: MY_POD_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.name
  - name: RABBITMQ_NODENAME
    value: rabbit@$(MY_POD_NAME).yourservice
```
You prabably must set `RABBITMQ_USE_LONGNAME: true` also.

**Comment by kzila** [comment]
+1
this would be really handy to have

**Comment by urzds** [comment]
This is still interesting to us.

With support for an arbitrary number of search domains now available in glibc, this should also be actually usable:
* https://sourceware.org/bugzilla/show_bug.cgi?id=19569
* https://bugzilla.redhat.com/show_bug.cgi?id=168253
* https://bugzilla.redhat.com/show_bug.cgi?id=677316

/remove-lifecycle stale

**Comment by devurandom** [comment]
Still interesting.

/remove-lifecycle stale

**Comment by herzcthu** [comment]
+1 
It would be nice if we have this features.

**Comment by dkwakkel** [comment]
+1, resulting in less configuration.

**Comment by j4fm** [comment]
+1, this would simplify things for statefulset pod name resolution

**Comment by taumeson** [comment]
Going on four years now, with activity every few months. The default behavior of siblings in a StatefulSet should be to know each other and be able to contact each other. Peer-to-peer networking within clusters is common.

**Comment by eblume** [comment]
This remains a relevant issue, as far as I am aware.

/reopen
/remove-lifecycle rotten

**Comment by MartinEmrich** [comment]
Just got hit by this, too. A clustered service, which expects its peers to be found by their respective hostnames (and also expects itself to be found by the short hostname, so configuring with FQDN was not possible).

A workaround: add the statefulset subdomain name to your DNS search list, e.g.:
````
      dnsConfig:
        searches:
          - mystatefulset.mynamespace.svc.cluster.local
````

Please reopen the issue and disable that pesky fetja-bot... (Or explain the thought behind the decision not to implement it).

**Comment by aojea** [comment]
one issue is that `cluster.local` is the default value for the cluster domain, but is defined by the user and the value is not accessible from the API , thus it can not be easily automated ...

I don't know much about other possible problems

**Comment by MartinEmrich** [comment]
@aojea Yes indeed. In my case I both write the ressources and know the correct domain, but this of course won't work easily with cutting-and-pasting ressource mainfests from Github etc. ...
