### ISSUE TITLE
`kubectl get --watch` eventually just exits

### ISSUE THREAD

**Issue by atombender** [kubernetes/kubernetes#42552]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kubectl, watch, get, exit

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.5.3

**Environment**:
- **Cloud provider or hardware configuration**: Google Cloud Platform, GKE
- **OS** (e.g. from /etc/os-release): Kubernetes: ChromeOS (GKE image). Client: macOS.
- **Kernel** (e.g. `uname -a`): 4.4.21
- **Install tools**:
- **Others**:

**What happened**: `kubectl get pods -w` will eventually just exit with exit status 0 and no message. No network disruption that I know about. No error messages.

**What you expected to happen**: I expected `kubectl` to watch for ever.

**How to reproduce it** (as minimally and precisely as possible): Run `kubectl get pods -w` and wait long enough. (I'm running it again now with a timer to see if there's any concistency here.)

**Anything else we need to know**: It's worth pointing out that it also exits if there's a network blip or I change wifi networks. I think `-w` should follow the user's intention and try to keep watching in the face of temporary, recoverable errors.

**Comment by smarterclayton** [comment]
All watches are terminated by the server after a certain point.  No retries are done today.

**Comment by davidwalter0** [comment]
Should it retry?
--forever | [ --retries=[n|forever] --backoff=[power-of-two,incrementally] ]
Should it report exit and what logger should it report to

**Comment by atombender** [comment]
Given that it's a CLI tool, I suggest that it should retry forever (until ctrl-C). Errors should be emitted to stderr.

**Comment by pwittrock** [comment]
@monopole Its not clear what the right solution is here.

**Comment by kargakis** [comment]
This may also be because of watch.Until

**Comment by BenTheElder** [comment]
What's the recommendation here? cc @seans3

**Comment by cmcarey** [comment]
Yes, imo this is a bug.  
I would expect it to watch until I exit the proc.

/reopen
/remove-lifecycle rotten

**Comment by jonfairbanks** [comment]
Are there any workarounds to keep `--watch` commands running indefinitely?

**Comment by jonfairbanks** [comment]
> Are there any workarounds to keep `--watch` commands running indefinitely?

`while true; do clear && kubectl get hpa --watch && sleep 1; done`

**Comment by soltysh** [comment]
> All watches are terminated by the server after a certain point. No retries are done today.

Above is sufficient answer and I'm not expecting us fixing this. 
/close
