### ISSUE TITLE
Pod stucks in terminating if it has a privileged container but has been scheduled to a node which doesn't allow privilege

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#42568]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): **No**

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): **pod, stuck, terminating**

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
**git clone master and build locally.**
```
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.849+df70b30e59b5da", GitCommit:"df70b30e59b5da98e83fdfa327e1cd107a582ca1", GitTreeState:"clean", BuildDate:"2017-03-06T01:48:01Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.849+df70b30e59b5da", GitCommit:"df70b30e59b5da98e83fdfa327e1cd107a582ca1", GitTreeState:"clean", BuildDate:"2017-03-06T01:48:01Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Cloud provider or hardware configuration**: OpenStack VM
- **OS** (e.g. from /etc/os-release): `PRETTY_NAME="Ubuntu 14.04.4 LTS"`
- **Kernel** (e.g. `uname -a`): 
`Linux xubuntu 3.16.0-73-generic #95~14.04.1-Ubuntu SMP Thu Jun 9 08:00:04 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**:
- **Others**:

**What happened**:
Pod stucks in terminating and the related RC can't be deleted.

**What you expected to happen**:
The RC and Pods can be deleted.

**How to reproduce it** (as minimally and precisely as possible)
- Create a cluster with two nodes, start kube-apiserver with flag `--allow-privileged=true`, start kubelet on one node with `--allow-privileged=true` and the other node without.
- Create a RC as below json file. After creating, the two pods may be scheduled to the two nodes. But the pod, which has been scheduled to the node which doesn't allow privilege, will become `pending` due to `Error validating pod rc-nginx-single-qwffh.default from api, ignoring: spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy`
- Delete the RC. Then the pending pod will stuck in terminating.
```
NAME                    READY     STATUS        RESTARTS   AGE
rc-nginx-single-qwffh   0/1       Terminating   0          2h
```

**Anything else we need to know**:
```
{
  "kind": "ReplicationController",
  "apiVersion": "v1",
  "metadata": {
    "name": "rc-nginx-single"
  },
  "spec": {
     "replicas": 2,
     "selector": {"name": "80-nginx"},
     "template": {
          "metadata": {
              "name": "nginx-template",
              "labels": {"name": "80-nginx"}
          },
          "spec": {
              "containers": [
                  {
                   "name": "nginx-con",
                   "image": "nginx",
                   "securityContext": {
                        "privileged": true
                   },
                   "imagePullPolicy": "IfNotPresent"
                  }
                 ]
          }
      }
   }
}

```

**Comment by xiangpengzhao** [comment]
Another concern is, should we prevent such pods from being scheduled to nodes which don't allow privileged pods? Maybe we can add a new predicate, e.g. `AllowPrivileged` ?
cc @davidopp

**Comment by fzu-huang** [comment]
Shall we use  `nodeSelector` to filter out nodes that have label `allow-privileged=true`?    What we have to do is add an Admission Controller  to add label of node when it registed.

**Comment by davidopp** [comment]
I think the simplest thing to do is to add it to
https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/well_known_labels.go
and then have Kubelet publish it like it does for some of the other labels.

cc/ @kubernetes/sig-node-feature-requests

**Comment by smarterclayton** [comment]
Ugh, I really don't think this is a well-known-label.  This is "hack-for-hack-capability" label.

**Comment by xiangpengzhao** [comment]
If @kubernetes/sig-node-feature-requests think the way @davidopp mentioned is okay, I would like to try to work on it:)

But I still have no idea how to fix current issue :(     Seems kubelet should call API to delete the pod, but it doesn't have chance to do because the pod was scheduled to the node but never created.

**Comment by rootsongjc** [comment]
Kubernetes 1.6.0

**Comment by yujuhong** [comment]
> Error validating pod kube-keepalived-vip-1p62d_default(5d79ccc0-3173-11e7-bfbd-8af1e3a7c5bd) from api, ignoring: spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy

kubelet and apiserver share the same validation library, but the supposedly "cluster-wide policy" (based on the error message) actually varies node by node. I think that's what tripped kubelet and made it think the pod was invalid and should just be ignored. 

One solution is exposing this node information to the control plane (e.g., what @davidopp suggested). Another potential fix for "terminating" pods is that we separate this node-dependent logic out, and let kubelet calls at admission time so that it can delete the pod.

**Comment by xiangpengzhao** [comment]
@yujuhong As per your comment, the validation of `privileged` is a _cluster-wide policy_ for apiserver, but a _node capability_ for kubelet, right? 

and did you mean the below points by "potential fix": 
* separate such validation logic out of the current shared validation library. 
* apiserver checks the cluster-wide support of `privileged` and the other existing validation.
* kubelet checks the other existing validation in [filterInvalidPods](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/config/config.go#L232) --> [ValidatePod](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/config/config.go#L345)
* kubelet checks `privileged` (and other possible node-dependent logic) at admission time

seems like kubelet already checks `privileged` at admission time. 
[canRunPod](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1683)
```
	if !capabilities.Get().AllowPrivileged {
		for _, container := range pod.Spec.Containers {
			if securitycontext.HasPrivilegedRequest(&container) {
				return fmt.Errorf("pod with UID %q specified privileged container, but is disallowed", pod.UID)
			}
		}
		for _, container := range pod.Spec.InitContainers {
			if securitycontext.HasPrivilegedRequest(&container) {
				return fmt.Errorf("pod with UID %q specified privileged init container, but is disallowed", pod.UID)
			}
		}
	}
```

**Comment by yujuhong** [comment]
> seems like kubelet already checks privileged at admission time.

That's during the sync time, not the admission. Either way, kubelet will not run the pod. The difference is whether kubelet should reject the pod (at the admission time), or simply keep the pod pending (checking at the sync time). There has been discussions before that rejecting the pod could cause a new pod be created as a replacement (if the pod is controlled by a replicaset). If this goes on, it could eventually overwhelm the cluster. I am not sure if any conclusion has been reached about handling this situation, but keeping the pod pending should be safe.

It's worth thinking whether this kind of checks belong to admission or validation.
