### ISSUE TITLE
ingress is not supporting for other than http servers

### ISSUE THREAD

**Issue by thaniyarasu** [kubernetes/kubernetes#42562]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

**Kubernetes version** (use `kubectl version`):

1.5.3
**Environment**:
AWS
- **Cloud provider or hardware configuration**: aws
- **OS** (e.g. from /etc/os-release): debian
- **Kernel** (e.g. `uname -a`): 4.4
- **Install tools**: kops
- **Others**:

i have tried to create ingress for a ssh server at 22 , but i can't

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-sshd-ingress
spec:
  backend:
    serviceName: sshd-svc
    servicePort: 22

**What happened**:

ingress is getting created for sshd- server

**What you expected to happen**:

ingress should create end point from where i have to access my ssh server running inside container

**How to reproduce it** (as minimally and precisely as possible):
create a ingress and point to a kubectl ssh service (port 22)

**Anything else we need to know**:

**Comment by calebamiles** [comment]
could someone from @kubernetes/sig-network-bugs or SIG AWS (sorry @justinsb I couldn't find any GitHub teams for SIG AWS to ping) please help with triage? Thanks!

**Comment by thockin** [comment]
SSH is explicitly for HTTP traffic, for now.  You probably want Service with type=LoadBalancer.
