### ISSUE TITLE
Service OpenStack LoadBalancerIP vip/floating-ip

### ISSUE THREAD

**Issue by dbaumgarten** [kubernetes/kubernetes#42574]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
openstack, service ip

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

When creating a Service and supplying a LoadBalancerIP Kubernetes will used this IP for the VIP of the created LoadBalancer. However in 98% of the cases, this is not what we want. The vip-Address is only reachable from within OpenStack. External access to the loadbalancer is only possible using the floating-ip assoziated with the vip. So if the Service should be used from outside the cluster (what is usually the case when creatin a service with LoadBalancer) beeing able to choose the vip-Address is essentialy useless. Beeing able to choose the floating-IP (under which the service is reachable from outside the cluster) is much more usefull.

I see different approaches to this:
1.) Always use the Address supplied via LoadBalancerIP for the floating IP instead of the vip.
2.) Keep LoadBalancerIP as it is and add an annotation with the wanted floating-IP.
3.) Add a parameter to the cloud-config file to choose what we want.
4.) Add an annotation indicating for what LoadBalancerIP should be used. (What should be the default)?

I would go with 1 or 4 (with default IP=floating-IP), as in most cases this is what we want. But it may break current deployments.
If we need something 100% backwards compatible I would go with 2 .

What do you think? Any other ideas?
If we decide what we want, I would be happy to create a PR for this.

Note: It is not possible to choose a specific Address when creating a new floating IP. But we can freely choose from the floating-IPs already present in the tenant. If the wanted address is not present in the tenant we would just throw an error.

This is somehow related to #32924. It is about leaving the vip-Address out of the list of IP-Addresses of the LoadBalancer. For the same reason as here (the VIP is mostly not what we want in an OpenStack-based Kubernetes)

**Kubernetes version** (use `kubectl version`):
Kubernetes: 1.5.1
Kubectl: irrelevant

**Environment**:
- **Cloud provider or hardware configuration**: OpenStack Liberty (LBaaSv1, Keystone v2)
- **OS** (e.g. from /etc/os-release): RHEL 7 (irrelevant)
- **Kernel** (e.g. `uname -a`): irrelevant
- **Install tools**: kubeadm
- **Others**:

**Comment by fdangtran** [comment]
@dbaumgarten, as for me I would rather go with 3: add a cluster-wide option in the OpenStack config file.  Solution 1 is not backward compatible. Solutions 2 and 4 would pollute k8s service api with cloud-provider-specific entities (floating ip, vip) that might not make sense for other cloud providers.  I hardly see a use case where a user wants to set which IPs are exported on a per-service basis.

**Comment by dbaumgarten** [comment]
@fdangtran i also can't see a use case for being able to set the kind of  IP on per-service basis. That might have to to do with the fact, that I can't see a use case for specifying the vip IP manually at all.

I understand that backwards compatibility is a valuable thing to have, but at the current state the LoadBalancerIP field is completely useless for all use cases known to me (I really can't find a reason why anyone would want to set the vip-Address instead of the floating-ip Address). I would think currently it is more bug than feature. And I see little value in staying backwards compatible to a bug. 

I would however be absolutely ok with adding some kind of flag to re-enable the buggy behavior, to support use cases I currently can't see.

This is just my personal opinion. If we decide, that this is not the way to do this, it is absolutely ok for me.

(Note: I found the word "exported" in your answer. Just to prevent miss-communication. This is about the ability to choose which floating-IP address will be used when creating the Loadbalancer (kubectl expose deployment nginx --LoadBalancerIP=10.0.0.42 ...). Which addresses (vip/floating-ip) are shown to the user after creation is the subject of #32924 )

**Comment by dbaumgarten** [comment]
I have another idea: 
What about "guessing" what the user wants to do. In OpenStack you can only choose a specific floating-IP if it already exists in the tenant. This means there are always just a few IP adresses, that could be used as a floating IP for a Loadbalancer and in most cases the IP-ranges for floating IPs and (local) vips do not even overlap (as this would probably introduce routing-problems), so it is pretty clear, what the user wants to do.

This means we could just try to find a floating IP matching the specified LoadBalancerIP. If one exists in the current tenant, the user most probably wanted to use it for the LoadBalancer, so we assign it to the LoadBalancer. If we can't find a matching floatingIP in the tanant, we write a log message about it and try to use the LoadBalancerIP as the IP of the vip.

This solution would be the most intuitive and user-friendly approach and still be backwards-compatible.

**Comment by eviloop** [comment]
Hello @dbaumgarten 

how are you deploying the cluster ?

From what i see here: https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L110

a FIP should be dynamically assigned to the LBaaS as long as the network is configured on the cloud-config

That would also be the behaviour standard with AWS

**Comment by dbaumgarten** [comment]
@eviloop That is right. A floating IP is automatically assigned to the LoadBalancer. The problem is, that it is currently not possible to choose which floating IP should be used for the LoadBalancer.
--LoadBalancerIP just sets the vip-IP, but for reasons mentioned above, this is nearly completely useless. It would be far more usefull if --LoadBalancerIP allowed us to choose one of the existing floating IPs in the tenant for the LoadBalancer.

**Comment by eviloop** [comment]
@dbaumgarten
I am a bit confused. Is the Floating IP being dynamically assigned but not reported as an Endpoint ?

Or would it be a request for the FIP to be not to be dynamically assigned but to have the option to manually assigned it as well?

**Comment by dbaumgarten** [comment]
@eviloop The floating ip is dynamically assigned and correctly reported.

What I would like to have is the possibility to choose an existing floating IP for the LoadBalancer.
Lets say I create a Service using kubectl expose: "kubectl expose deployment nginx --port 80 --type LoadBalancer --LoadBalancerIP=10.1.2.3" In this case I would want, that kubernetes doesn't allocate a new floating IP, but assignes (the already existing) floating IP 10.1.2.3 to the LoadBalancer.
Currently --LoadBalancerIP just lets me choose the vip-Address. It would be more usefull if it would let me choose the floating IP instead.

**Comment by dims** [comment]
@FengyunPan @NickrenREN @anguslees @grahamhayes - thoughts?

**Comment by zetaab** [comment]
this can be closed https://github.com/kubernetes/kubernetes/commit/9bdf2cc0e7523bcb2146fa859759f5865635128e its already there. So annotation exist

**Comment by dbaumgarten** [comment]
Closed, als this is implemented with https://github.com/kubernetes/kubernetes/commit/9bdf2cc0e7523bcb2146fa859759f5865635128e
