### ISSUE TITLE
[minor] Separate getNodeClassificationByLabels so it can be tested.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#42577]
**Kubernetes version** (use `kubectl version`):

master

**What happened**:

The `getNodeClassificationByLabels` functionality is hidden in a large function, and not explicit, testable.

**What you expected to happen**:

The logic of `CalculateAntiAffinityPriority` should read more clearly, with tests for individual filters.

**Comment by jayunit100** [comment]
@ravisantoshgudimetla has a PR for this .

**Comment by ravisantoshgudimetla** [comment]
Few more things include removing limits in entries like https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/priorities/selector_spreading.go#L64.

**Comment by jayunit100** [comment]
yeah, im not sure why the `0,3` thing is there  ? probably good idea to remove

**Comment by ravisantoshgudimetla** [comment]
@jayunit100 Its part of part of PR too.
