### ISSUE TITLE
Rebase hyperkube image on debian-base

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#42589]
https://github.com/kubernetes/kubernetes/pull/41915 adds the `debian-base` container image, which is intended to provide a standard base platform for Kubernetes images that require external dependencies. Advantages of debian base include:

- Our team will maintain & update it (until we have automation in place)
- Smaller footprint: it removes a lot of unecessary files like man pages and i18n packages.
- Smaller attack surface: removes unnecessary dependencies like the init system and some system tools. In practice, most of these aren't exposed, but it does reduce the noise in CVE scans.

In theory this should be as simple as changing the base image, and changing `apt-get` to `clean-install` (e.g. https://github.com/kubernetes/kubernetes/pull/42090), but we need to verify that there weren't any implicit dependencies that were removed (e.g. bash).

/cc @aaronlevy @ixdy 

xref: https://github.com/kubernetes/kubernetes/issues/40955

**Comment by aaronlevy** [comment]
Also cc @colemickens as someone else that has run kubelet via hyperkube container in the past

**Comment by pbx0** [comment]
Kubelet dependancies (and their potential removal) are being tracked in this issue: https://github.com/kubernetes/kubernetes/issues/26093

This would be a good source for determining previously implicit dependancies in the build process.

**Comment by ixdy** [comment]
The hyperkube image is based on debian-base (#48365), which first shipped in 1.8.

Additionally, debian-base is now based on debian stretch (#52744, #56094) which shipped in 1.9.

There are still quite a few extra dependencies installed for the hyperkube image:
https://github.com/kubernetes/kubernetes/blob/c7d52e27c82091c8b5a5739267298abe2063defe/build/debian-hyperkube-base/Dockerfile#L25-L41

but those are all necessary unless we start shipping different "flavors" of hyperkube (or figure out a different way to include only the volume dependencies needed).
