### ISSUE TITLE
"make quick-release" fails on macOS – recipe for target `all` and `cross` failed.

### ISSUE THREAD

**Issue by skofgar** [kubernetes/kubernetes#42599]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
`is:issue is:open quick release recipe all`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
`n/a`

**Environment**:
- **Cloud provider or hardware configuration**: `n/a`
- **OS** (e.g. from /etc/os-release): `macOS 10.12.3`
- **Kernel** (e.g. `uname -a`): 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
- **Install tools**: 
  - Homebrew 1.1.10
  - Homebrew/homebrew-core (git revision 68d65; last commit 2017-03-06)
  - gnu-tar 1.29_1
  - Docker version 17.03.0-ce, build 60ccb22
- **Others**:

**What happened**:
Based on the [Readme](https://github.com/kubernetes/kubernetes#building-kubernetes-for-the-impatient) of the repository, I wanted to try out k8s. I tried to execute following steps:

```
$ git clone https://github.com/kubernetes/kubernetes
$ cd kubernetes
$ make quick-release
```
I was asked, by the make-file script, to install `gnu-tar` via brew: `brew install gnu-tar`, which I did.

When I ran `make quick-release` again it executed for a while until I received this message:
```
+++ [0306 14:08:07] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [0306 14:08:08] Building go targets for darwin/amd64:
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genyaml
    cmd/mungedocs
    cmd/genswaggertypedocs
    cmd/linkcheck
    examples/k8petstore/web-server/src
    federation/cmd/genfeddocs
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
go build k8s.io/kubernetes/federation/cmd/genfeddocs: /usr/local/go/pkg/tool/linux_amd64/link: signal: killed
go build k8s.io/kubernetes/cmd/genman: /usr/local/go/pkg/tool/linux_amd64/link: signal: killed
!!! [0306 14:10:37] Call tree:
!!! [0306 14:10:37]  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:740 kube::golang::build_binaries_for_platform(...)
!!! [0306 14:10:37]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0306 14:10:37] Call tree:
!!! [0306 14:10:37]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0306 14:10:37] Call tree:
!!! [0306 14:10:37]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
Makefile:89: recipe for target 'all' failed
make[1]: *** [all] Error 1
Makefile:389: recipe for target 'cross' failed
make: *** [cross] Error 1
!!! [0306 14:10:38] Call tree:
!!! [0306 14:10:38]  1: build/../build/common.sh:506 kube::build::run_build_command_ex(...)
!!! [0306 14:10:38]  2: build/release.sh:36 kube::build::run_build_command(...)
make: *** [quick-release] Error 1
```

**What you expected to happen**:
To build k8s.

**How to reproduce it** (as minimally and precisely as possible):
Follow the installation steps in the [Readme for the impatient](https://github.com/kubernetes/kubernetes#building-kubernetes-for-the-impatient).

**Anything else we need to know**:
I tried different ways to install k8s. Including installing `kubernetes-cli` in brew.

**Comment by radeksimko** [comment]
I had the exact same problem (based on the log). The `link signal: killed` made me think this may have something to do with resources (un)available for the build - specifically I suspect the process is being killed due to the lack of available memory.

After increasing the allocated memory I watched `docker stats` for real usage an I found the build process is quite memory-hungry (~2.7GB at peak). I ended up with 3GB memory allocated for Docker (previously 2GB) and I was then able to run tests with no further issues.

![screen shot 2017-04-15 at 19 11 13](https://cloud.githubusercontent.com/assets/287584/25065881/506fdd70-220f-11e7-883c-6656928276c9.png)

**Comment by skofgar** [comment]
Oh thanks! I will try it and let you know how it goes.

**Comment by skofgar** [comment]
thanks that solved the issue! 
sorry for the late reply

**Comment by llofberg** [comment]
4GB was not enough to run "make". 8GB did the trick.

**Comment by akutz** [comment]
Hi @llofberg,

Thank you for the comment. I too just tried with 3GiB, then 4. It wasn't until I set Docker to 8GiB that it worked for me as well.
