### ISSUE TITLE
Flaky test: Opaque resources should schedule pods that initially do not fit after enough opaque integer resources are freed

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#42597]
The test failed in both ci-kubernetes-e2e-gci-gce  and ci-kubernetes-e2e-kops-aws: 

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/5096
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/5059

This blocks the submit-queue.

**Comment by dchen1107** [comment]
The culprit pr is https://github.com/kubernetes/kubernetes/pull/41870 which introduces new set of tests and merged recently.

**Comment by dchen1107** [comment]
The breakage caused by pr:#41870   actually breaks two required test suites: ci-kubernetes-e2e-gci-gce & /ci-kubernetes-e2e-kops-aws. Should we revert this for now? @kubernetes/release-team

**Comment by dchen1107** [comment]
Another failure is https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/5097

**Comment by dchen1107** [comment]
one more: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-etcd3/6586

**Comment by ConnorDoyle** [comment]
The fix to OIR and corresponding e2e were submitted as separate commits; do you mind reverting only e402c5d5e50c11af3ecde4fffa509776f0608d03 ?

**Comment by ConnorDoyle** [comment]
cc @timothysc
