### ISSUE TITLE
Feature request: Verify deployement configuration

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#42601]
My repository contains kubernetes deployment configuration, and I would like to check that they are syntactically correct as part of my pre-submit continuous integration. My CI system doesn't have a cluster set-up, so running `kubectl apply -f my-config.yaml --dry-run` doesn't really works. I want to check that the yaml is correct, and that it creates valid kubernetes objects.

Maybe we should have a `check-config` to verify a configuration.

@kubernetes/sig-apps-feature-requests

**Comment by foxish** [comment]
Looks similar to https://github.com/kubernetes/kubernetes/issues/39699

**Comment by foxish** [comment]
cc @kubernetes/sig-cli-feature-requests

**Comment by kargakis** [comment]
> Looks similar to #39699

Agreed. Let's move the discussion there.
