### ISSUE TITLE
Run service controller in federation kubectl tests

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#42607]
Noticed that service controller is not running in our federation kubectl tests. It crashes since no dns-zone is provided.

I fixed that but it still crashes for dns-provider. I tried coredns but could not get that to work.
Will wait for documentation from @shashidharatd. Filing this to track it.

The error I got was: 
```
Cloud provider could not be initialized: could not init DNS provider "coredns": Need to provide at least one DNS Zone
```
I verified that I am passing --zone-name. no dns-provider-config tough.

cc @kubernetes/sig-federation-bugs

**Comment by shashidharatd** [comment]
Hi @nikhiljindal, to start controller-manager with CoreDNS, we need to provide config-file.
config file has below format
```
[Global]
etcd-endpoints = http://127.0.0.1:2379
zones = example.org
```
Also do let me know, how to run these integration test. i could not locate the tests :)

**Comment by nikhiljindal** [comment]
@shashidharatd You can run them by running `make test-cmd` or directly running `./hack/make-rules/test-federation-cmd.sh`. 
Code for running federation controller manager is at https://github.com/kubernetes/kubernetes/blob/ab9b299c3033cfd334c180926aa2931de9628d1f/hack/make-rules/test-federation-cmd.sh#L65. We need to update the flags there to set CoreDNS as the dns provider.

**Comment by groundnuty** [comment]
@shashidharatd I'm trying to run kubefed with kubeadm on ubuntu 16 openstack without loadbalancer. The only choice is coredns. I encountered the issue described here:
~~~
Cloud provider could not be initialized: could not init DNS provider "coredns": Need to provide at least one DNS Zone
~~~
Could you elaborate where should one provider this config file? What config file is it at all?
