### ISSUE TITLE
DNS resolving does not work on windows nodes

### ISSUE THREAD

**Issue by vriesmarcel** [kubernetes/kubernetes#42605]
BUG REPORT
## Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

## Environment**:
Azure ACS with windows agents
**What happened**:
unable to connect from one deployed service to other service based on the documented kubernetes dns name of the deployed service

## repro steps:
Created two services using the following commands:
kubectl create deployment iis --image=microsoft/iis
kubectl expose iis --port:80 --type=LoadBalancer
 service is now available on external network
now I want from in this container to connect to a database using the dns name db.default.svc.cluster.local
so created new service:
kubectl create deployment db --image=marcelv/iisexpress
and expose this internal in the cluster
kubectl create service clusterip db --tcp=1433:1433

now I execute a command in the iis container to see if I can connect to the new db service:
kubectl exec <nameofthepod> cmd.exe
inside container I execute:
nslookup
db.default.svc.cluster.local
this results the ip address I also see when I call the kubectl get services command
but when I want to connect to the dns name on port 1433 it wont resolve the ip adres
if you do
ping db.default.svc.cluster.local
Ping request could not find host db.default.cluster.local. Please check the name and try again.

so with a direct dns query it works, but the implicit name resolving on windows does not work.
I tried to resolve it using 
ipconfig /registerdns
no avail
looking at the DNS cash does not show any entries

So it seems DNS is not fully functional inside the cluster.

## What you expected to happen**:
I expect to be able to connect to the network via DNS  from the pod
I also deployed a .net application that tried to resolve the address
but those fal with a wind32 error network path not found

**Comment by colemickens** [comment]
cc: @anhowe @JiangtianLi PTAL

**Comment by JiangtianLi** [comment]
@vriesmarcel Are you able to ping kubernetes.default.svc.cluster.local? I created and exposed iis service and could ping iis.default.svc.cluster.local from another container. I wasn't able to pull image marcelv/iisexpress just now but db.default.svc.cluster.local can be resolved in ping (I flushed dns cache).

**Comment by vriesmarcel** [comment]
sorry, my bad, the db image name is marcelv/sqlexpress
it exposes port 1433 and runs sql express with already created DB in image. (next step was to map to persistent storage for this)

in the IIS image I am able to ping kubernetes.default.svc.cluster.local and it returns the ip of the dns server, which seems to be what we expect.

in the DB image I am not able to ping kubernetes.default.svc.cluster.local
ip config there shows:
**Windows IP Configuration**

   Host Name . . . . . . . . . . . . : 4f97e7c0eeae
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : piwrovpeof5uboww05ppyodqog.ax.internal.cloudapp.net

Ethernet adapter vEthernet (Container NIC 0e2424db):

   Connection-specific DNS Suffix  . : piwrovpeof5uboww05ppyodqog.ax.internal.cloudapp.net
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #7
   Physical Address. . . . . . . . . : 00-15-5D-2E-17-F6
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::85f7:6cab:7d0c:7002%42(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.29.113.136(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 172.29.112.1
   DNS Servers . . . . . . . . . . . : 10.0.0.10
   NetBIOS over Tcpip. . . . . . . . : Disabled

Ethernet adapter vEthernet (Container NIC b06c8dcc):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #8
   Physical Address. . . . . . . . . : 00-15-5D-34-27-C4
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::e894:8d00:3007:419b%46(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.244.1.149(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :
   DNS Servers . . . . . . . . . . . : 10.0.0.10
   NetBIOS over Tcpip. . . . . . . . : Disabled

**on the iis ipconfig /all produces
Windows IP Configuration**

   Host Name . . . . . . . . . . . . : 083ae25f7bfd
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : piwrovpeof5uboww05ppyodqog.ax.internal.cloudapp.net

Ethernet adapter vEthernet (Container NIC 2f1dadbf):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #5
   Physical Address. . . . . . . . . : 00-15-5D-34-21-CA
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::b910:39e8:93aa:7fa%33(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.244.1.199(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default  Gateway . . . . . . . . . :
   DNS Servers . . . . . . . . . . . : 10.0.0.10
   NetBIOS over Tcpip. . . . . . . . : Disabled

Ethernet adapter vEthernet (Container NIC 533fe3b9):

   Connection-specific DNS Suffix  . : piwrovpeof5uboww05ppyodqog.ax.internal.cloudapp.net
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #6
   Physical Address. . . . . . . . . : 00-15-5D-2E-15-94
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::dd0a:2c7f:cb86:4b21%37(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.29.115.123(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 172.29.112.1
   DNS Servers . . . . . . . . . . . : 10.0.0.10
   NetBIOS over Tcpip. . . . . . . . : Disabled

And I am running on the same node, since the cluster only has one master and one agent.

**Comment by JiangtianLi** [comment]
@vriesmarcel Thanks for the details. I was able to kubectl create marcelv/sqlexpress. In the db container I could ping kubernetes.default.svc.cluster.local. In my other iis container on the same node, ping can resolve db.default.svc.cluster.local name. But there is some other issue to reach db container though, which I am looking into.

So it is better I can access your cluster and take a look there. You can IM me on slack: jiangtianli

**Comment by vriesmarcel** [comment]
no clue how to IM you using slack, I don't have you as a team member ?!? sorry slack noob.
What do you need to get access to the cluster? master endpoint and ssh keys?

**Comment by JiangtianLi** [comment]
@vriesmarcel I have created a team on slack and I can sent you the invitation. Please let me know your email address. I am not an expert on slack so not sure if there is better way.

**Comment by mfaizanse** [comment]
According to the [documentation ](**https://kubernetes.io/docs/admin/dns/**)of kubernetes, if two pods/services are running in a same namespace then they can ping using only the service name like ping foo. But I have tried it and it does not work until I provide the full dns name like foo.default.svc.cluster.local. Any idea about this?

**Comment by colemickens** [comment]
(Why don't you guys just talk in the Kubernetes Slack room?)

**Comment by colemickens** [comment]
(never mind my reply, GitHub comments and email notifications had drifted...)

**Comment by vriesmarcel** [comment]
@JiangtianLi according to our last conversation, you found that the adapter sequence was not ok and therefore dns resolve did not work correct. Where you able to fix this long term in the codebase, so a next release this issue is solved?

@mfaizanse I see the same behavior, I always need to specify fqdn to access the services
