### ISSUE TITLE
User Labels not propagating to kubelet

### ISSUE THREAD

**Issue by RenaudWasTaken** [kubernetes/kubernetes#42606]
**Is this a request for help?**: No

**What keywords did you search in Kubernetes issues before filing this one?** :
- kubelet labels
- labels

**Is this a BUG REPORT or FEATURE REQUEST?**: Bug report
---

**TLDR**:
- Set a label/annotation on a pod
- Create it through kubectl
- The labels / annotations don't appear in the docker labels

**How to reproduce it** (as minimally and precisely as possible):
Sample pod file:
```yaml
apiVersion: v1
kind: Pod
metadata:
    name: hello-nginx
    labels:
        foolabel: "foolabel"
spec:
  containers:
  - image: nginx
    name: hello-nginx-ctr
```

Run the following commands:
```bash
$ ./cluster/kubectl.sh create -f labels.yml
pod "hello-nginx" created

# the cut / sed allows to get the first id displayed by docker ps
$ docker inspect $(docker ps | cut -d ' ' -f 1 | sed -n 2p) | grep foolabel
$ echo $?
1
```

**Anything else we need to know**:
After looking a bit though the code I noticed that kubelet does not seem to receive the labels / annotations set by the users (though it does get some annotations, e.g: annotation.io.kubernetes.container.hash).
 
I'm not sure where to go from here or where those "system defined" annotations are set.

**Environment and version**:

```bash
$ cluster/kubectl.sh version
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.1.335+a564506f7c0fd0", GitCommit:"a564506f7c0fd0693870221a3b811be36461c057", GitTreeState:"clean", BuildDate:"2017-02-16T01:01:50Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.1.335+a564506f7c0fd0", GitCommit:"a564506f7c0fd0693870221a3b811be36461c057", GitTreeState:"clean", BuildDate:"2017-02-16T01:01:50Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

$ cat /etc/os-release                                                                                                                                        NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
UBUNTU_CODENAME=xenial

$ uname -a                                                                                                                                                   
Linux 4.4.0-62-generic #83-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
```
Ran from `./hack/local-up-cluster.sh`

**Comment by yujuhong** [comment]
We don't support propagating kubernetes labels/annotations to docker containers directly. What written as docker container labels are considered implementation details. Is this a feature request?

**Comment by RenaudWasTaken** [comment]
Thanks for taking a look @yujuhong !

>We don't support propagating kubernetes labels/annotations to docker containers directly.

I'm a bit confused here because it looks like the dockershim does exactly that with some kubernetes annotations ?
I can also spot kubernetes annotations passed to this function ?
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/docker_container.go#L46

If this is not a bug then this is a feature request :)
In that case do you mind pointing to me a few files where I could add this feature ?

Thanks !

**Comment by yujuhong** [comment]
@RenaudWasTaken this was raised previously in https://github.com/kubernetes/features/issues/16, but the conclusion was that docker labels were immutable and hence don't map well to k8s labels. Nothing has changed since that discussion, so it's unlikely that the sig-node community will add this feature.

As for the labels you mentioned, they are simply used by kubelet to keep track of the containers -- they are internal implementation details and may change without any notice, i.e., users should not rely on them.

**Comment by RenaudWasTaken** [comment]
Ok thanks !

This makes a lot of sense :) I'll try to look for other approaches !
