### ISSUE TITLE
Turn off Proxy Protocol for specific Backend Ports

### ISSUE THREAD

**Issue by alexw23** [kubernetes/kubernetes#42616]
It appears `service.beta.kubernetes.io/aws-load-balancer-proxy-protocol` turns on proxy protocol support for all backend ports https://github.com/kubernetes/kubernetes/blob/v1.5.3/pkg/cloudprovider/providers/aws/aws.go#L79-L84.

We have a SSH service for gitlab running alongside HTTP and HTTPS. When we use `service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"` SSH does not respond correctly.

We need to be able to specify the ports to enable, i.e. `service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "80,443"`

A temporary fix for now is to run the following command after ELB is created:
```
aws elb set-load-balancer-policies-for-backend-server --load-balancer-name ELB_NAME --instance-port RELEVANT_PORT --policy-names "[]"
```

**Comment by compleatang** [comment]
Just faced same issue. Thanks for logging the fix, as this had me stuck for hours.

**Comment by qrevel** [comment]
Same here, spend half the day searching where the problem came from. I activated PROXY Protocol but OpenSSH doesn't support it.

**Comment by pieterlange** [comment]
/remove-lifecycle stale

This is still an issue, i currently work around it using:
```
ELB_NAME=$(kubectl get svc -n ingress-nginx ingress-nginx -o json | jq -r '.status.loadBalancer.ingress[].hostname' | cut -d- -f1)
for NODEPORT in $(kubectl get svc -n ingress-nginx ingress-nginx -o json | jq '.spec.ports[] | select(.name=="openvpn" or .name=="gitlab-ssh").nodePort'); do
  aws elb set-load-balancer-policies-for-backend-server --load-balancer-name $ELB_NAME --instance-port $NODEPORT --policy-names "[]"
done
```

where `openvpn` and `gitlab-ssh` are named ports in the ingress service that don't support tcp proxyprotocol.

**Comment by david972** [comment]
I got the same issue.
Thank to @pieterlange work around It's work for me.

But it's weird I didn't get this issue before upgrading my controller from 0.9.0-beta.17
So I don't understand the difference.

**Comment by david972** [comment]
@pieterlange 
I missed something.
How can you fix it with strip tcp proxy protocol with NGINX ?

**Comment by pieterlange** [comment]
https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/exposing-tcp-udp-services.md
