### ISSUE TITLE
Pod containers should be recreated after kubelet restarts when some kubelet flags changed

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#42620]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
**No**

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
**kubelet, restart**

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
**BUG REPORT ?**

**Kubernetes version** (use `kubectl version`):
**kubernetes HEAD**
```
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.849+df70b30e59b5da", GitCommit:"df70b30e59b5da98e83fdfa327e1cd107a582ca1", GitTreeState:"clean", BuildDate:"2017-03-06T01:48:01Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.849+df70b30e59b5da", GitCommit:"df70b30e59b5da98e83fdfa327e1cd107a582ca1", GitTreeState:"clean", BuildDate:"2017-03-06T01:48:01Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: OpenStack VM
- **OS** (e.g. from /etc/os-release): `Ubuntu 14.04.4 LTS`
- **Kernel** (e.g. `uname -a`): `Linux xubuntu 3.16.0-73-generic #95~14.04.1-Ubuntu SMP Thu Jun 9 08:00:04 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**: Manually
- **Others**:

**What happened**:
I create a pod and it has been scheduled to a node then it runs. Restart the kubelet with adding flag `--network-plugin=cni`. The pod/containers aren't recreated.

**What you expected to happen**:
If I don't change kubelet flag(s), it's okay and expected not to recreate containers after kubelet restarts. But if I change some key flag, we'd better recreate containers. In this example, I want the pod to attach to network created by cni, but it still use the former default network.

**How to reproduce it** (as minimally and precisely as possible):
Keep a pod running, then restart kubelet by changing `--network-plugin` flag.

**Anything else we need to know**:
If this is designed behavior, there is still another issue:
If restart kubelet with adding flag `--network-plugin=cni`, the IP of existing pod can be kept. But if restart kubelet with omitting flag `--network-plugin=cni`, the pod IP will lost. By describing pod or getting pod -o wide, we can see the pod IP to be none.

**Comment by andrewsykim** [comment]
@xiangpengzhao This would require the kubelet to be aware of its previous state from disk (etcd?) which I would imagine requires lots of refactoring. From my experience, networking config changes in general shouldn't be done live in production anyways, you may want to consider creating a new cluster and federate your existing one with it. Just my two cents.

**Comment by xiangpengzhao** [comment]
Thanks @andrewsykim ! Reasonable:)
