### ISSUE TITLE
Unable to use AzureFile volume on Windows agents

### ISSUE THREAD

**Issue by arnouthoebreckx** [kubernetes/kubernetes#42628]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug ?

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): Windows agents

**What happened**:
Using ACS on Azure, I created a cluster with Windows agents. Now I tried to add shared storage with Azurefile but it never seems to work, I barely find information concerning this aswell. When I describe the pod it always gives unknown for sharename.

![capture](https://cloud.githubusercontent.com/assets/24568583/23647440/225cbfb0-0316-11e7-8801-01a528034644.PNG)

**What you expected to happen**:
It should've just connected the share, I followed the template from [github](https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/azure_file) for this 

**How to reproduce it** (as minimally and precisely as possible):
Make a windows cluster using ACS, trying to deploy using Azurefile volume.

**Anything else we need to know**:
This is my deployment yaml file. 
![capture3](https://cloud.githubusercontent.com/assets/24568583/23647584/ddbdccfe-0316-11e7-9ba9-ce846aba4a81.PNG)

And this is my share structure
![capture2](https://cloud.githubusercontent.com/assets/24568583/23647596/ebebf5d0-0316-11e7-87a6-422b4fec1997.PNG)

**Comment by andyzhangx** [comment]
@xiangpengzhao 
Azure file mount on windows depends on windows 2016 RS3 image, which is about to release around Oct, there is already a PR(https://github.com/kubernetes/kubernetes/pull/52469) for this, I will notify you when it's ready on azure. Thanks.

**Comment by xiangpengzhao** [comment]
@andyzhangx thanks! ping @arnouthoebreckx

**Comment by andyzhangx** [comment]
by deploying k8s cluster using acs-engine v0.9.2 or above, you could use azure file mount on Windows now, you could refer to following link for more detail steps:
https://github.com/andyzhangx/Demo/tree/master/windows/azurefile

**Comment by andyzhangx** [comment]
azure file mount on Windows is avaiable from v1.9.0
/close

**Comment by andyzhangx** [comment]
Just let me know if there is any concern, I am the feature owner of this azure file mount on Windows.
