### ISSUE TITLE
Can't get the mysql-wordpress-pd sample to work... format disks?

### ISSUE THREAD

**Issue by pmsteil** [kubernetes/kubernetes#42621]
I am new to k8s... 

I am trying to follow the sample here:
https://github.com/kubernetes/kubernetes/tree/master/examples/mysql-wordpress-pd

Have modified very little and my pods just crash, they never get to a Ready state.

I think maybe because after I create my new volumes I need to format them.
So I think I need to follow the steps that I finally found here:
http://dev.eventyay.com/docs/installation/gce-kubernetes/

in the section titled: 
Create And Format A Persistent Data Disk For Postgres

Is that correct?

It would be great to add that to the readme as this caused me to waste a lot of time.  If that is not the problem, what do these errors tell you:
http://screencast-o-matic.com/screenshots/u/fObY/1488862496393-59906.png

thanks,
patrick

**Comment by jamiehannaford** [comment]
@pmsteil What's outputted when you run `kubectl logs` against the crashing pods?

**Comment by pmsteil** [comment]
This is what I get:

> sed: -e expression #1, char 59: unterminated `s' command

**Comment by lanwenchang** [comment]
i got same problem with @pmsteil ,  how to fix it?

**Comment by CarwynNelson** [comment]
+1 I am also getting this problem, here is my specific error message:

```
sed: -e expression #1, char 56: unterminated `s' command
```

I am running minikube version `v0.18.0` on OSX `10.12.2` and my docker version string is `Docker version 17.03.0-ce, build 60ccb22`

Any ideas?

**Comment by jamiehannaford** [comment]
@pmsteil @lanwenchang @CarwynNelson I think it's because the password file you provided the secret has a trailing newline. This will cause the `sed` error. Here's how to create the correct file:

```bash
openssl rand -hex 10 | tr -d '\n' > password.txt
```

**Comment by CarwynNelson** [comment]
@jamiehannaford I'll give that a go :) I find it kind of weird that my password file would have a trailing newline though.

I generated it by doing this:

`echo 'secretpassword' > password.txt`

I wouldn't imagine that would cause a newline character to be added to the password file?

**Comment by xiangpengzhao** [comment]
/sig apps
/kind support
As per the discussion, we can close it.
@thockin
