### ISSUE TITLE
Support for connecting to glusterfs with TLS

### ISSUE THREAD

**Issue by sheerun** [kubernetes/kubernetes#42632]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
glusterfs tls

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

Could Kubernetes support connecting to glusterfs cluster with TLS certificate, as described in https://kshlm.in/post/network-encryption-in-glusterfs/? This seems like production-grade feature.

It would be perfect to support both data and management connections.

**Comment by cblecker** [comment]
/remove-lifecycle stale frozen
This needs to be triaged by the sig. If the sig doesn't take it on, then it should be eligible for close.

@kubernetes/sig-storage-feature-requests

**Comment by cblecker** [comment]
/remove-lifecycle stale
/remove-lifecycle frozen
This needs to be triaged by the sig. If the sig doesn't take it on, then it should be eligible for close.

@kubernetes/sig-storage-feature-requests

**Comment by blurpy** [comment]
I would like this feature. Is this never going to happen?

**Comment by amgads** [comment]
Would like to reopen the issue /reopen
This is need. heketi supports tls, but k8s glusterfs csi doesn't and blocking usage

refer to the following issue link https://github.com/heketi/heketi/issues/1467
