### ISSUE TITLE
Patch needs information from GuaranteedUpdate to determine liveness, causes TestPatch flakes

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#42644]
GuaranteedUpdate tries to update with cached data.  Patch needs to know whether its being called with live or stale data to determine the "base" level the patch was issued against.

**Comment by liggitt** [comment]
once we fix this, we should roll back the workaround in https://github.com/kubernetes/kubernetes/issues/42641

**Comment by wojtek-t** [comment]
Instead of doing it in this direction, I would suggest doing it in the opposite direction.

What I mean is that in GuaranteedUpdate itself, we know that:
- the first iteration is using the cache data (potentially stale)
- all further iterations are using the fresh data (just read from etcd)

So we can fix it by ignoring the error from in the first iteration of loop in GuaranteedUpdate. 

WDYT?

**Comment by liggitt** [comment]
GuaranteedUpdate doesn't know what tryUpdate is doing. In the case of patch, the `currObj` passed the first time is saved as a baseline to compute patch conflicts against.

**Comment by wojtek-t** [comment]
Copying from the other thread:

> the interface of the tryUpdate function would also need to be updated to let GuaranteedUpdate tell it whether it is the "first" time tryUpdate is being called (since patch's tryUpdate function takes the currObj the first time it is called as the base to compute conflicts against.

@liggitt - so do you suggest passing the information about whether the object is from cache or not to tryUpdate function?
How patch then should behave based on that? Are you suggesting to "reset" it's state based on that bit of information?
Are there any other places that will use that information, that you are aware of?

**Comment by wojtek-t** [comment]
The fix is out in https://github.com/kubernetes/kubernetes/pull/42729

**Comment by ethernetdan** [comment]
@liggitt @wojtek-t do we want to block 1.6 on this?

**Comment by liggitt** [comment]
I don't think so, but I'd like it fixed asap post-1.6

**Comment by liggitt** [comment]
I think this is the cause of the TestPatch flakes

```
--- FAIL: TestPatch (1.23s)
	basic_test.go:584: unexpected error: unable to find api field in struct Unstructured for the json field "metadata"
```

we're seeing failures looking up strategic patch info from a merge patch call, which means we got a conflict on what should have been a no-op patch

**Comment by sjenning** [comment]
Something has cause these flakes to increase in frequency.  Three in the pass few hours.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/59158/pull-kubernetes-unit/78634/

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/58714/pull-kubernetes-unit/78613/

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/56525/pull-kubernetes-unit/78605/

**Comment by liggitt** [comment]
> Something has cause these flakes to increase in frequency. Three in the pass few hours.

I think it has been intermittent but present for a while... 

https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&test=TestPatch

http://storage.googleapis.com/k8s-metrics/flakes-latest.json shows 40 failures

**Comment by liggitt** [comment]
deflake for TestPatch in https://github.com/kubernetes/kubernetes/pull/59594, same workaround as #42641... when we're doing consecutive overlapping patches on the same object, wait for our first patch to take effect.
