### ISSUE TITLE
Stopping cluster overnight prevents scheduled jobs from running after cluster startup.

### ISSUE THREAD

**Issue by lpreson** [kubernetes/kubernetes#42649]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
CronJob
ScheduledJob
"Too many missed start times to list"
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Kubernetes version** (use `kubectl version`):

**Environment**: 
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CentOS Linux release 7.3.1611 (Core)
- **Kernel** (e.g. `uname -a`):Linux 4.9.11-1.el7.elrepo.x86_64 #1 SMP Sat Feb 18 18:16:50 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: Custom 
- **Others**: 

**What happened**:
Cluster shutdown nightly to reduce costs. On startup the cluster refuses to run jobs.
The controller manager errors with:
E0307 15:40:23.754617       1 controller.go:163] Cannot determine if default/<job name> needs to be started: Too many missed start times to list

**What you expected to happen**:
The cluster will run scheduled jobs after being restored.

**How to reproduce it** (as minimally and precisely as possible):
Set a regular schedule such as `*/1 * * * *` 
Shutdown for 100 scheduled executions of the job (100 minutes).

**Anything else we need to know**:
This seems to be related to:
Function: getRecentUnmetScheduleTimes
v1.4: https://github.com/kubernetes/kubernetes/blob/release-1.4/pkg/controller/scheduledjob/utils.go#L169

**Comment by kargakis** [comment]
@kubernetes/sig-apps-bugs

**Comment by soltysh** [comment]
There was similar problem recently fixed https://github.com/kubernetes/kubernetes/issues/36311, although in this particular use case it's hard to distinguish whether it was down or something else broke, from a controller point of view. I could only suggest tweaking `.spec.startingDeadlineSeconds` for the time.

**Comment by lpreson** [comment]
@soltysh if I set `.spec.startingDeadlineSeconds` to a high number will it trigger once on resume or trigger all missed jobs?

**Comment by soltysh** [comment]
@lpreson up to `.spec.startingDeadlineSeconds` but then again you could try setting `.spec.restartPolicy` to `Forbid`, this way only one will be run at the time. I must admit your use case is far from normal, due to shutting down the cluster, but reasonable for the controller to work stably.

**Comment by lpreson** [comment]
@soltysh This could be a common approach for money saving in the cloud when running non production clusters.

**Comment by kargakis** [comment]
Also reported in https://github.com/kubernetes/kubernetes/issues/45825 - @soltysh @erictune is it something we are targetting to fix in 1.7?

**Comment by soltysh** [comment]
With the current time-frame I'm not sure. I'll be sweeping through my bugs over the next few weeks. I'll see what I can go with.

**Comment by skynardo** [comment]
@lpreson - I was wondering if setting .spec.startingDeadlineSecond and or setting .spec.restartPolicy to Forbid resolved this issue. We have a similar issue with 2 of our non-prod clusters that we shut down each night.

**Comment by mattfarina** [comment]
/remove-lifecycle stale

@skynardo Can you share the version of Kubernetes you are still experiencing this on?

@kow3ns did you know about this one?

**Comment by ApsOps** [comment]
I'm still experiencing this on `v1.8.6`.

**Comment by mludvig** [comment]
I've got the same problem with Minikube 0.25.0 running Kubernetes server 1.9.0 in a VirtualBox on my laptop. When I close the lid and laptop suspends the minikube VM obviously stops and upon resume my scheduled job keeps failing with:

**Cannot determine if job needs to be started: Too many missed start time (> 100). Set or decrease .spec.startingDeadlineSeconds or check clock skew.**

**Comment by soltysh** [comment]
This is due to the hard-coded value of how many missed start times the cronjob controller can handle. It's reasonable to have it configurable, I guess.

**Comment by soltysh** [comment]
Actually I was thinking about it more this morning. Currently if we exceed the [artificial, hardcoded limit](https://github.com/kubernetes/kubernetes/blob/5411352dc67000a2a47bd31d9e42930146319541/pkg/controller/cronjob/utils.go#L166) the cronjob will always error out without any chance to recover the cronjob. Maybe we should error out as we do today and pause the cronjob to prevent it from further erroring out, but at the same time giving the user the ability to restart it. I'd like to hear what others think about such approach.

**Comment by mludvig** [comment]
Some restart button was exactly what I was looking for in the dashboard! Couldn't find a way to do it and had to delete and recreate the job :(
Definitely +1 from me ;)

**Comment by skynardo** [comment]
I would prefer it be configurable. I could then set it > the number of scheduled starts it would have had overnight while our EC2 instances are shut down.  I need something automated. I was thinking about adding a check to my monitoring pod to see if the scheduled job was dead then recreate it.

**Comment by boosty** [comment]
> I would prefer it be configurable

+1

**Comment by gtaylor** [comment]
This just bit us today, too. We had to work around the issue by deleting and re-adding part of our Helm chart on the cluster :(

Would be great to be able to disable/re-enable a CronJob.

**Comment by dzoeteman** [comment]
Not only being able to restart the CronJob would be nice, but also exclude actually suspending a CronJob - in this case, the user has specified he doesn't want the CronJob to be run, so it should be okay to start again on schedule as soon as the user has resumed the CronJob.

**Comment by soltysh** [comment]
> Not only being able to restart the CronJob would be nice, but also exclude actually suspending a CronJob - in this case, the user has specified he doesn't want the CronJob to be run, so it should be okay to start again on schedule as soon as the user has resumed the CronJob.

@dzoeteman suspension is already, see `.spec.suspend` which is `false` by default.

**Comment by gtaylor** [comment]
If I flip a "stuck" CronJob to `spec.suspend` = `true` then back to `false`, do I get un-stuck? Or is the answer for sure "Delete and re-create the CronJob?"

**Comment by soltysh** [comment]
@gtaylor - no idea, you can try. Although I'm worried that if the suspend is on for longer than 100 missed invocation it might suffer the same problem. I appreciate your feedback :)

**Comment by dzoeteman** [comment]
@soltysh yes, it does the same thing on suspend, hence I made my earlier comment :)

**Comment by dharmeshkakadia** [comment]
Can we please get some love on this bug :)
There is no good way to suspend a cron job and resume it. Are there alternatives ?
(I added the comment on https://github.com/kubernetes/kubernetes/issues/45825 and realized it was closed in favor of this, hence commenting here as well)

**Comment by malbanesi-vm-sf** [comment]
Thank you @lpreson for the reference to
> https://github.com/kubernetes/kubernetes/blob/release-1.4/pkg/controller/scheduledjob/utils.go#L169

I could get a cronjob stuck for the last 15 days running again by making the cron schedule *more* restrictive: running once every day. So instead of 100 missed start times there were just 15.

**Comment by soltysh** [comment]
Since fixing this problem will require API changes I doubt it's doable for 1.11. If I can get a volunteer that is interested in implementing this feature for 1.12 I'd be more than happy to help write and review the code. It should be pretty straight forward.

**Comment by soltysh** [comment]
@dharmeshkakadia find me on slack and we can chat. But you should start with familiarizing your self with cronjob [object](https://github.com/kubernetes/kubernetes/blob/cf27c256eab9534cb685bde56ddb88081e136ab2/staging/src/k8s.io/api/batch/v1beta1/types.go) and [controller](https://github.com/kubernetes/kubernetes/tree/cf27c256eab9534cb685bde56ddb88081e136ab2/pkg/controller/cronjob).

**Comment by butenkor** [comment]
I hit similar issue:

`Cannot determine if job needs to be started: Too many missed start time (> 100). Set or decrease .spec.startingDeadlineSeconds or check clock skew.`
even if i do not/never shut down the cluster. Once last job has finished and cronjob reached above state a new job is not triggered/scheduled anymore (even if cronjob is not suspended).

I use following setup for the cronjob:

```
# every 5 minutes
schedule: '*/5 * * * *'
suspend: false
restartPolicy: Never
concurrencyPolicy: Forbid
```

The issue seems that the job was expected to run every 5 minutes but last run took more than 24h which is valid for our scenario as depending on amount of data it has to process it might finish after 2 minutes or also after more than 24h

Taking into account that `concurrencyPolicy: Forbid` is used an additional cronjob setting which will prevent unnecessary re-schedule every 5 minutes (which in turn lead to mentioned issue) might be an option.

For time being i guess increasing both `schedule` frequency as also `startingDeadlineSecond` to something high might workaround the issue?

**Comment by abh** [comment]
@gtaylor 
> If I flip a "stuck" CronJob to spec.suspend = true then back to false, do I get un-stuck? Or is the answer for sure "Delete and re-create the CronJob?"

You have to delete and re-create to get unstuck; or set startingDeadlineSeconds higher than the time since the job was last run. There was the other use case of "if the cluster has been off", too, but I think this is the primary issue -- the suspend is impractical to use because of this.

**Comment by floriantraber** [comment]
We hit the same issue after changing the cron from `@weekly` to `@hourly`.

**Comment by aermakov-zalando** [comment]
@soltysh The current code only handles the last unmet startup anyway, so why the hard-failure on `> 100`? Even if the code is updated to handle all of them, I'd argue that the better way would be to just take the last `N` and ignore the previous failures, perhaps emitting an event about it. This will allow the cronjob to recover without any significant changes to the code, and users wouldn't have to delete and re-create it.

**Comment by chrisxaustin** [comment]
This makes developing within minikube a bit painful if your laptop sleeps overnight.

I have a job that's scheduled to run every 5 minutes to change the state of other pods if their configuration changed, and I don't care if there are any missed jobs, just that it runs roughly on that schedule. Having the job never run again because the laptop was sleeping overnight isn't desirable.

**Comment by Multiply** [comment]
We're also very interested in getting something going on this issue.
It has hit us in various production environments already. The hard limit on 100 schedules is super frustrating, and I'd love for that to be configurable.

Let me know if we can do something, to get some traction on the issue. I'd also love to contribute code if need be.

**Comment by skynardo** [comment]
I ended up changing the schedule for our cronjobs that run in the environments that get shut down nightly so that they only run from 7am to 5pm M-F. This keeps the cronjob from getting into this state where it must be recreated.
Example:
schedule: '*/5 12-22 * * 1-5'

**Comment by diemus** [comment]
i think set the schedule to "0 0 29 2 0" at the same time can solve the problem

**Comment by pnrick** [comment]
@diemus I have tried the way you mentioned on 1.14. no luck.
anyone still working on the issue?

**Comment by diemus** [comment]
@pnrick you need to use updatestatus not update method. update method can not change status

**Comment by pnrick** [comment]
@diemus Thanks! As you suggested, I used updatestatus and it worked like a charm. even on 1.11

**Comment by minhdanh** [comment]
@diemus What do you mean by using updatestatus here? I tried with `kubect edit cronjob` but it doesn't work.

**Comment by diemus** [comment]
@minhdanh i'm talking about using client go. i don't think  kubectl can change this status

**Comment by xrmzju** [comment]
i ran into this problem  fro suspending my cronjob overnight. as @diemus suggested, we should ignore the cronjob that missed to many start times because of artificial suspending. update `LastScheduleTime` in cronjob controller when job is suspended  will be the most simple way to solve this problem. and something like below after [this line](https://github.com/kubernetes/kubernetes/blob/release-1.4/pkg/controller/scheduledjob/controller.go#L157)
```go
		sj.Status.LastScheduleTime = &metav1.Time{Time: time.Now()}
		if _, err := sjc.UpdateStatus(sj); err != nil {
			glog.Infof("Unable to update status for %s (rv = %s): %v", nameForLog, sj.ResourceVersion, err)
		}
		return
```

**Comment by andrewsav-datacom** [comment]
To me it sounds like the solution that @soltysh suggested above fits better. `LastScheduleTime` is the time when "the last time the job was successfully scheduled", and you cannot really update it while the job is suspended and cannot run.

**Comment by tyrken** [comment]
It looks to me and from reading this discussion, the code &  https://github.com/kubernetes/kubernetes/pull/74058 that:

* Cronjobs can be "suspended", via any of spec.suspend=true, K8s master halt (e.g. laptop suspend/cost-saving power-down) or, if spec.concurrencyPolicy==forbid, a single job execution taking a long time.
* If StartingDeadlineSeconds ("SDS") is not set, then when you re-enable (i.e. the conditions above no longer being so) after more than 100 missed job starts you'll be hit by this lock-out bug, as countless people have reported.
* If SDS is set ... everything should work, except:
  * As the controller code only runs every 10 seconds or so, if SDS is also around 10 or lower you may not run at all/intermittently, especially if the ControllerManager is overloaded.
  * If the SDS is set high, you might get an unexpected run.  E.g. If set to run every hour with a 10 minute SDS, if you re-enable at 2:05pm it will run the "missed" 2pm job.
  * If SDS set very high (such that you could get > 100 job starts inside the SDS time) you could get hit by this lockout bug again.

Given that we really ought to be encouraging everyone to just set StartingDeadlineSeconds to something small like 60 seconds, maybe even setting that as a default if the Beta API rules allow such a change, and limit it to a minimum of 15.

Additionally we should reword some of the code comments in the controller that imply it will run the cron job multiple times to catch up (it won't - it will only run the last missed time if within SDS).  If somebody wants that functionality back, not me, then add a new config value, e.g. "spec.missedStartPolicy" of "Skip", "Once", "All"

**Comment by praseodym** [comment]
After hitting #77475, I needed to re-create cronjobs due to this issue. I find this very counter-intuitive: regular Unix cron implementations never try to catch up with missed schedules (vixie-cron) or catch up after a restart with a single run (anacron, fcron).

I would propose that we change the controller to only ever immediately start _one_ job if there is a missed schedule in the last `startingDeadlineSeconds`. If not, the controller should log a message and the cronjob must continue working as if it were never scheduled before (i.e. no catching up and no blocking because some arbitrary number of runs were missed).

This will surprisingly not change the current behaviour of the controller at all, because [it never actually tries to catch up with more than one missed start time](https://github.com/kubernetes/kubernetes/blob/a1f4c2ed21ea008c59934a9c6a06fac3da72f963/pkg/controller/cronjob/cronjob_controller.go#L275-L282), but instead it complains and forever blocks if it cannot list all those missed start times. (There is work going on in #79995 and https://github.com/kubernetes/enhancements/pull/1145 to change this, however.)

I will work on this and submit a patch :slightly_smiling_face: 

/assign @praseodym

**Comment by praseodym** [comment]
I've submitted a PR to remove the 'too many missed start times' behaviour: #81557

**Comment by Multiply** [comment]
/remove-lifecycle stale

This is still an issue for us, although not specifically related to stopping the cluster overnight, but the underlying issue is the same.

**Comment by xinzhang** [comment]
I still have this issue in GKE running 1.13.12. Tried to update concurrencyPolicy and startingDeadlineSeconds (30), but no luck. Have you guys been able to add those and it worked?

**Comment by roobert** [comment]
This is still an issue when running GKE 1.14.10-gke.27.

**Comment by lechen26** [comment]
same as on GKE 1.16.8-gke.15

**Comment by niemyjski** [comment]
Still an issue with AKS (1.16.7)

**Comment by fai555** [comment]
Same on GKE 1.16.9-gke.6

**Comment by Bo0km4n** [comment]
Same issue happen on Kubernetes 1.18.6

**Comment by zentale** [comment]
Another fix for this same thing? https://github.com/kubernetes/kubernetes/pull/89397

**Comment by soltysh** [comment]
This is being fixed in the new controller https://github.com/kubernetes/kubernetes/pull/93370

**Comment by Skybladev2** [comment]
Still experience it with minikube v1.16.0

**Comment by alculquicondor** [comment]
@Skybladev2 did you enable the `CronJobControllerV2` feature gate?

**Comment by soltysh** [comment]
This should now be resolved with the new controller implementation.
/close
