### ISSUE TITLE
Generated release_1_5 clientset should create pods, delete pods, watch pods

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#42646]
Recurring often lately
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42346/pull-kubernetes-e2e-gce-etcd3/21247/

@caesarxuchao

**Comment by yujuhong** [comment]
Ran into this on multiple PRs. Bumped the priority.
E.g., https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42681/pull-kubernetes-e2e-gce-gci/21197/

**Comment by caesarxuchao** [comment]
#42734 is addressing the same issue. I requested the author to fix #42646 as well.

**Comment by caesarxuchao** [comment]
Dup of https://github.com/kubernetes/kubernetes/issues/42724.

**Comment by caesarxuchao** [comment]
Closed by #42833
