### ISSUE TITLE
k8s.io/kubernetes/pkg/api TestRoundTripTypes

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#42651]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42346/pull-kubernetes-unit/21773/

@deads2k

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-test-failures is missing
@kubernetes/sig-api-machinery-misc

**Comment by deads2k** [comment]
Round tripping failures are very rarely the fault of API machinery.  It's normally a flaw in the fuzzer funcs for the API group.  In this case, @kubernetes/sig-auth-bugs
