### ISSUE TITLE
Need Cinder V2 API support

### ISSUE THREAD

**Issue by rootfs** [kubernetes/kubernetes#42658]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
1.6

**Environment**:
- **Cloud provider or hardware configuration**: OpenStack
- **OS** (e.g. from /etc/os-release):RHEL/CentOS
- **Kernel** (e.g. `uname -a`): 3.10
- **Install tools**:
- **Others**:

**What happened**:
On an openstack setup that doesn't enable Cinder V1 API, it is possible to get false negative about disk attachment from this [line](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_volumes.go#L118)

**What you expected to happen**:
Kubernetes should work openstack setups that doesn't rely on Cinder V1 API.

**How to reproduce it** (as minimally and precisely as possible):
always

**Anything else we need to know**:
@kubernetes/sig-openstack-bugs 

Cinder V1 API is deprecated. V2 API SDK is available at [gophercloud](https://github.com/gophercloud/gophercloud/tree/master/openstack/blockstorage/v2/volumes)

**Comment by rootfs** [comment]
@anguslees

**Comment by xsgordon** [comment]
@rootfs have you looked at https://github.com/kubernetes/kubernetes/pull/40423 at all?

@idvoretskyi can you label sig/openstack? Thanks!

**Comment by rootfs** [comment]
@xsgordon thanks!
