### ISSUE TITLE
Are StatefulSets required to preserve PVC on replica recreation?

### ISSUE THREAD

**Issue by TamalSaha** [kubernetes/kubernetes#42677]
Hi, I wanted to ask about some behavior of StatefulSet. Say I have a SS with replica =3 (also uses PV). Now, later I reduce # of replicas to 2. This deleted the  pod-2. Then if I increase the replicas to 3, I see that the original PVC, if exists, will be reused. My question is this behavior required for a StatefulSet? I am not fully sure from reading:   https://github.com/kubernetes/community/blob/master/contributors/design-proposals/stateful-apps.md#managing-lifecycle-of-members

I am trying to write a dynamic hostpath provider for SS that will work with replica > 1 . I am trying to understand if I need to preserve this behavior for SS with hostpath PV provisioner. https://github.com/kubernetes-incubator/external-storage/issues/15 . To preserve this behavior, "scheduler needs a predicate that looks at a pod->PVC->PV node label to determine which node the pod can be scheduled to."

Thanks.

**Comment by TamalSaha** [comment]
cc: @smarterclayton

**Comment by TamalSaha** [comment]
cc: @k8s-sig-scheduling

**Comment by aveshagarwal** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by TamalSaha** [comment]
@kubernetes/sig-apps-feature-requests

**Comment by smarterclayton** [comment]
That behavior is "required" if the user does not delete the PVC.  If the PVC is deleted, the controller will create another one.

**Comment by TamalSaha** [comment]
Found some related previous discussion; https://github.com/kubernetes/kubernetes/issues/9802

**Comment by bgrant0607** [comment]
Looks like question was answered. In the future, for usage questions, please try slack, stackoverflow, or kubernetes-users@googlegroups.com instead of github issues.
