### ISSUE TITLE
Add Pod Deletion Prometheus Metric

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#42673]
With a number of changes to pod deletion going in in 1.6 (#41644, #41095), it is important to expose metrics for monitoring deletion latency.

I plan to expose a pod deletion latency metric in the same way that PodStartLatency is exposed in [kubelet prometheus metrics](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/metrics/metrics.go)

cc @vishh

**Comment by vishh** [comment]
SGTM. AFAIK, we do not collect metrics from *all* test suites. So we might
still not catch *all* timeout issues.

**Comment by dashpole** [comment]
We can take a look at which suites need these metrics after they are added.
