### ISSUE TITLE
Test Memcg Notifications on GCI/COS

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#42676]
Memcg notifications, which have the potential to greatly improve eviction responsiveness was added prior to 1.5: #32577.
However, it appeared that on some images (Specifically CVM), this feature exposed a kernel bug resulting in kernel soft lockups: #37853.
Since 1.5, Memcg has been feature gated, and disabled by default.  However, for images that did not exhibit soft lockups, we should try and re-enable this feature.
My goal is to set a timeline to safely re-enable this feature by 1.7.

I propose:
- [x] create a test serial suite running with memcg notifications enabled: #42499
- [x] create test job
- [x] monitor test suite 
- [x] enable memcg notifications for all testing
- [x] re-enable for GCI if no soft lockup is detected.

cc @dchen1107 @vishh

**Comment by dashpole** [comment]
Test job is [here](https://k8s-testgrid.appspot.com/google-node#kubelet-memcg-serial-gce-e2e), and runs the memory eviction test with --experimental-memcg-notifications=true.

**Comment by derekwaynecarr** [comment]
have you see recurrences?

**Comment by dashpole** [comment]
I have not yet.

**Comment by derekwaynecarr** [comment]
do you have thp enabled or disabled?

**Comment by dchen1107** [comment]
Transparent Hugepage is enabled on COS, but I believe it is only madvise mode, not always. @dashpole you can check it through /sys/kernel/mm/transparent_hugepage/enabled

**Comment by dashpole** [comment]
that file contains:
`always [madvise] never`
So it looks like it is set to madvise mode as dawn said.

**Comment by dashpole** [comment]
Making this functional is now blocked by #51745

**Comment by dashpole** [comment]
This is complete, and is active on all 1.11+ nodes on GKE.  We haven't detected any soft-lockups.
