### ISSUE TITLE
e2e flaky: [k8s.io] Network Partition [Disruptive] [Slow] [k8s.io] [ReplicationController] should eagerly create replacement pod during network partition when termination grace is non-zero

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#42688]
The test is getting very flaky lately due to timeout, and here are the sample failures:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/779

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network_partition.go:363
Expected error:
    <*errors.errorString | 0xc421821820>: {
        s: "Pod name my-hostname-net: Gave up waiting 2m0s for 3 pods to come up",
    }
    Pod name my-hostname-net: Gave up waiting 2m0s for 3 pods to come up
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network_partition.go:356
```

@kubernetes/sig-apps-bugs

**Comment by foxish** [comment]
This was fixed by https://github.com/kubernetes/kubernetes/pull/42596
It is green in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/780 and https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/781

**Comment by foxish** [comment]
cc @enisoc

**Comment by dchen1107** [comment]
Great, thanks!
