### ISSUE TITLE
[k8s.io] Kubectl client [k8s.io] Simple pod should handle in-cluster config failing in version skew tests

### ISSUE THREAD

**Issue by ymqytw** [kubernetes/kubernetes#42697]
[k8s.io] Kubectl client [k8s.io] Simple pod should handle in-cluster config failing in the following tests:
[gce-1.6-master-cvm-kubectl-skew](https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gce-1.6-master-cvm-kubectl-skew&width=80)
[gce-1.6-master-gci-kubectl-skew](https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gce-1.6-master-gci-kubectl-skew&width=80)
API server and kubectl are 1.6 and kubectl is built from HEAD (considered as 1.7)

The test is failing with 2 types:
- [`kubectl not found`](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.6-master-cvm-kubectl-skew/44)
- [unexpected value](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.6-master-cvm-kubectl-skew/25)

cc: @pwittrock @fabianofranz @ethernetdan @calebamiles @shiywang

**Comment by ymqytw** [comment]
Please apply the labels and milestone.

**Comment by fabianofranz** [comment]
On it.

**Comment by ymqytw** [comment]
@fabianofranz The tests are still [failing](https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gce-1.6-master-cvm-kubectl-skew), but with a [different error](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.6-master-cvm-kubectl-skew/151). PTAL

**Comment by fabianofranz** [comment]
@ymqytw yep, sorry about that. Skew are a little hard to simulate locally. Fixed in https://github.com/kubernetes/kubernetes/pull/42901.

**Comment by ymqytw** [comment]
@fabianofranz Thanks for fixing this :)
