### ISSUE TITLE
dockershim: check and enforce minimum docker api version

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#42696]
This mirrors what we do for dockertools.

/cc @dchen1107 @Random-Liu

**Comment by cmluciano** [comment]
Is there a maintained list of docker versions supported ?

**Comment by cmluciano** [comment]
Is this the proper place to check https://github.com/dchen1107/kubernetes-1/blob/master/pkg/kubelet/dockertools/docker_manager.go#L85

**Comment by yujuhong** [comment]
> Is this the proper place to check https://github.com/dchen1107/kubernetes-1/blob/master/pkg/kubelet/dockertools/docker_manager.go#L85

That *was* the proper place to check, but those code are being deprecated. The new one doesn't have a check yet, and that's what this issue is for.

**Comment by feiskyer** [comment]
Let me add the check. /assign
