### ISSUE TITLE
e2e flaky: [k8s.io] SchedulerPredicates [Serial] validates that NodeSelector is respected if not matching [Conformance]

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#42691]
Sample failures: 

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/781

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:236
Expected
    <bool>: false
to equal
    <bool>: true
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:5082
```

@kubernetes/sig-scheduling-bugs

**Comment by wanghaoran1988** [comment]
I just run a e2e test against my cluster, and cannot reproduce that, @bsalamat Do you have any idea about that?

**Comment by bsalamat** [comment]
Failure is probably hard to reproduce. I can see only 2 failures in the past two weeks. Let me try. I will update here if I make any progress.

**Comment by bsalamat** [comment]
I have not been able to reproduce this failure so far. I will still try to reproduce. It is clearly still flaky.

**Comment by timothysc** [comment]
Honestly the best way to try to reproduce is via creating a PR, rarely have I been able to reproduce some of the flake issues on a clean env.  Most of the time it is a timing anomaly caused by a resource strapped environment.

**Comment by bsalamat** [comment]
@timothysc I will create a fake PR to see if we can reproduce, but looking at the code of the test, it seems that there is a reason that this test is flaky. The test (like many other tests) uses waitForScheduler:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/scheduler_predicates.go#L234

waitForScheduler is not doing anything to ensure that scheduler has actually run. It just waits for 10 seconds. In fact there is a TODO there saying that this logic is brittle:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/scheduler_predicates.go#L905

If scheduler does not run in that 10 seconds, the test is going to fail. Given the rarity of the failures, I suspect it might be the cause.

**Comment by bsalamat** [comment]
We see similar occasional failures in other tests that call verifyResult right after waitForScheduler, such as:

[k8s.io] SchedulerPredicates [Serial] validates that NodeAffinity is respected if not matching
[k8s.io] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run [Conformance]

I don't have any evidence that waitForScheduler is causing it, but there is a possibility that it is the root cause. I will check the logs to ensure.

**Comment by timothysc** [comment]
We should use the eventing mechanism that is used in other tests...  

Push it into a generic mechanism, but that's a pretty large change this close to the end. 
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/opaque_resource.go#L242

**Comment by timothysc** [comment]
So here is what I propose: if the there have only been 2 failures in the last two weeks we should hold off and fix it properly in the next cycle.  We should bring all the other scheduling e2es into line as well and possibly subdir off with owners attached so they route to the sig easier.

**Comment by bsalamat** [comment]
I like your proposal. The tests that I checked had failed about a couple of times in two weeks. So, we may want to leave them alone for this release.
Tomorrow, I will try to change predicate tests to use events to see how things go and how much work is there.

**Comment by davidopp** [comment]
Thanks for investigating. It would be good to do something to verify the theory that not waiting long enough is the cause of the flakes -- either increase the waiting time and see if the failure rate goes down, or change at least one of the tests to use events (as you guys have suggested above) and see if the failure rate goes down.

**Comment by bsalamat** [comment]
@davidopp Please see the [PR#42928](https://github.com/kubernetes/kubernetes/pull/42928). In that PR I have changed scheduler_predicates.go to use events.

**Comment by marun** [comment]
@ethernetdan Would it make sense to label the issue as non-release-blocker as well, so it's obvious without clicking on the linked PR?

**Comment by davidopp** [comment]
This is clearly just flaking, so I'm going to move it out of 1.6 milestone.

**Comment by davidopp** [comment]
Sorry, I guess the more correct thing is to leave 1.6 mielstone but mark it "non-release-blocker." Done.

**Comment by timothysc** [comment]
We'll try to get it in, but it's ok if it slips.  @ConnorDoyle has some patches as a pre-req to @bsalamat 's changes.

**Comment by aveshagarwal** [comment]
I think the label priority/critical-urgent should be removed as it does not go with the label non-release-blocker?
