### ISSUE TITLE
KubeGenericRuntimeManager starts up the pod even when dockershim RunPodSandbox returns error

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#42698]
I bumped into this when I am trying to run a pod with hostport on a node where the port is occupied. In this case, kubenet will clean up all network artifacts and return error to dockershim. And dockershim will return error to KubeGenericRuntimeManager. 

But somehow, KubeGenericRuntimeManager lets the pod stay and declare it `Running` but with no ip. This implies that errors returned by network plugins will not cause pod start up failure. 

```
$ k describe pod hostporttest-1751457092-gsnkh
Name:		hostporttest-1751457092-gsnkh
Namespace:	default
Node:		e2e-test-mixia-minion-group-2ztx/10.240.0.4
Start Time:	Tue, 07 Mar 2017 17:46:47 -0800
Labels:		pod-template-hash=1751457092
		run=hostporttest
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"hostporttest-1751457092","uid":"3404cdc2-039c-11e7-878c-42010af0...
		kubernetes.io/limit-ranger=LimitRanger plugin set: cpu request for container hostporttest
Status:		Running
IP:		
Controllers:	ReplicaSet/hostporttest-1751457092
Containers:
  hostporttest:
    Container ID:	docker://1de8ae5594960e65c8044c10c08c9c6dd910c3aaa4d8db79d107c76dc69a682b
    Image:		gcr.io/mixia-cube/serve_hostname:v1.4
    Image ID:		docker://sha256:d94f6f38bd6f57b6d3d79e70f641fdc7be7a7e9389d7bbe2374ad3df922a35bb
    Port:		9376/TCP
    State:		Running
      Started:		Tue, 07 Mar 2017 17:46:51 -0800
    Ready:		True
    Restart Count:	0
    Requests:
      cpu:		100m
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-whmz6 (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	True 
  PodScheduled 	True 
Volumes:
  default-token-whmz6:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-whmz6
    Optional:	false
QoS Class:	Burstable
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From						SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----						-------------	--------	------		-------
  16s		16s		1	default-scheduler						Normal		Scheduled	Successfully assigned hostporttest-1751457092-gsnkh to e2e-test-mixia-minion-group-2ztx
  14s		14s		1	kubelet, e2e-test-mixia-minion-group-2ztx			Warning		FailedSync	Error syncing pod, skipping: failed to "CreatePodSandbox" for "hostporttest-1751457092-gsnkh_default(1792f0bc-03a1-11e7-878c-42010af00002)" with CreatePodSandboxError: "CreatePodSandbox for pod \"hostporttest-1751457092-gsnkh_default(1792f0bc-03a1-11e7-878c-42010af00002)\" failed: rpc error: code = 2 desc = NetworkPlugin kubenet failed to set up pod \"hostporttest-1751457092-gsnkh_default\" network: cannot open hostport 80 for pod hostporttest-1751457092-gsnkh_default: listen tcp :80: bind: address already in use"

  12s	12s	1	kubelet, e2e-test-mixia-minion-group-2ztx	spec.containers{hostporttest}	Normal	Pulled	Container image "gcr.io/mixia-cube/serve_hostname:v1.4" already present on machine
  12s	12s	1	kubelet, e2e-test-mixia-minion-group-2ztx	spec.containers{hostporttest}	Normal	Created	Created container with id 1de8ae5594960e65c8044c10c08c9c6dd910c3aaa4d8db79d107c76dc69a682b
  12s	12s	1	kubelet, e2e-test-mixia-minion-group-2ztx	spec.containers{hostporttest}	Normal	Started	Started container with id 1de8ae5594960e65c8044c10c08c9c6dd910c3aaa4d8db79d107c76dc69a682b
```

**Comment by freehan** [comment]
Grepped kubelet log:
[kubelet.log.zip](https://github.com/kubernetes/kubernetes/files/826384/kubelet.log.zip)

If nobody has bandwidth to look into this, I will come back to this after fixing a more urgent kube-proxy problems. @yujuhong @Random-Liu

**Comment by Random-Liu** [comment]
I believe the problem is that:
* Even though `RunPodSandbox` returns error, the infra container is already started.
* When kubelet does resync, dockershim returns the sandbox is `Ready`, because we don't set the sandbox as `NotReady` when the container networking is not working properly.
* Kubelet thought the sandbox is good.

The problem is that network plugin should tell dockershim that the sandbox is not working properly. Possibly we could do something here https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/docker_sandbox.go#L219-L242.

This seems bad @yujuhong

**Comment by Random-Liu** [comment]
@freehan Is the IP allocation synchronous or asynchronous? Is it ok to say that if there is no IP after we `RunPodSandbox`, there must be something wrong? Is there any other way to distinguish whether a sandbox is working properly or not?

**Comment by yujuhong** [comment]
> The problem is that network plugin should tell dockershim that the sandbox is not working properly.

Two things we can do:
 1. Add mechanism in kubenet to allow checking the status of the podsandbox, so that dockershim will return the status correctly.
 2. Clean up the podsandbox container on error -- either in kuberuntime (StopPodSandbox) or in dockershim. 

dockertools does the cleanup as well.

**Comment by Random-Liu** [comment]
> dockertools does the cleanup as well.

Yeah, I didn't notice that.
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker_manager.go#L2276

> either in kuberuntime (StopPodSandbox) or in dockershim.

This seems more like a runtime implementation detail.

Is 1) easy to do? @freehan  If not, 2) should be good enough now. :)

**Comment by yujuhong** [comment]
@freehan would you be able to work on this?

**Comment by yujuhong** [comment]
@Random-Liu volunteered to fix this. Thanks!
