### ISSUE TITLE
setting for storage resource request or pod container disk size

### ISSUE THREAD

**Issue by sjezewski** [kubernetes/kubernetes#42699]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

storage resource request
container file size limit

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature Request

**Kubernetes version** (use `kubectl version`):
1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: AWS / GKE / Azure

**What happened**:

```
$kubectl run blah --image=ubuntu --replicas=1 --restart=Never --requests=storage=30G
The Pod "blah" is invalid: spec.containers[0].resources.requests[storage]: Invalid value: "storage": must be a standard resource for containers
```

**What you expected to happen**:

The above command to work.

**How to reproduce it** (as minimally and precisely as possible):

```
$kubectl run blah --image=ubuntu --replicas=1 --restart=Never --requests=storage=30G
The Pod "blah" is invalid: spec.containers[0].resources.requests[storage]: Invalid value: "storage": must be a standard resource for containers
```

**The motivation for this request**:

We have users processing very disparate data sets using a large variety of tools. Much of this processing deals with file I/O as an intermediate step. Because we are processing huge data sets (Gb,Tb, Exa, etc) we break this into chunks digestible for each pod on k8s.

However. Each container comes w a 10Gb disk size limit. (If there's a way to up this limit, that would basically be what I'm looking for).

Right now, we poke a hole for a host mount for any file IO that needs to happen. However, that results in a few negative consequences

1) there can be disk contention for this resource (resulting in bad scheduling), and
2) if a pod is evicted, we can't run our cleanup code (as part of the pod) to remove the data written to the host mount and so 'leak' disk usage

That second one in particular can lead to some pathological cases, where an eviction or a few can pile up and lead to disk exhaustion.

Especially considering k8s is moving away from the GC model to the eviction policy model, I'd like to make this not a host path, but just part of the normal container filesystem. Then, k8s could Do The Right Thing and evict (and remove old volumes / etc) as needed.

To do that, I'd need to be able to 

a) set the container filesystem size (for 'correctness' to be able to run these data sets)
b) set a resource request and/or limit on the disk size (to inform k8s how to schedule these jobs)

**Comment by JoeyZwicker** [comment]
+1

**Comment by dwhitena** [comment]
+1

**Comment by calebamiles** [comment]
could someone from @kubernetes/sig-storage-feature-requests please help qualify the request or reroute to the appropriate SIG? Thanks!

**Comment by msau42** [comment]
Could you use emptydir volumes for this purpose?  Currently emptydir volumes are unbounded, but we are looking into adding limits for it as part of kubernetes/community#306

**Comment by msteffen** [comment]
+1. One piece of this report that I'd like to help emphasize is:

>  However. Each container comes w a 10Gb disk size limit. (If there's a way to up this limit, that would basically be what I'm looking for).

The problem with emptyDir is that some kind of janitor process needs to clean it up regularly. While this could be made to work, overriding docker's 10GB-per-container storage limit seems like it might be easier?

**Comment by msau42** [comment]
When the pod gets destroyed, the emptydir directory gets deleted.  Is there any other cleanup you are expecting?

**Comment by msteffen** [comment]
I apologize, I didn't read the docs for emptyVolumes carefully. I think that would work well for us.

**Comment by msau42** [comment]
Cool, let us know if emptydir doesn't work for you.  The only thing I can think of is EmptyDir volumes exist during the lifetime of the pod, so the data in the EmptyDir volume persists across container restarts.  So if you were expecting that the data gets cleaned up every time the container restarts, then EmptyDir would not work.

**Comment by bgrant0607** [comment]
Please see the referenced proposal.

Closing this issue as a duplicate.
