### ISSUE TITLE
Kubelet pod-manifest-path doesn't limit file extensions

### ISSUE THREAD

**Issue by rmb938** [kubernetes/kubernetes#42700]
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:

```
VMWare vCenter with no cloud provider set
```

- **OS** (e.g. from /etc/os-release):

```
CentOS Linux release 7.3.1611 (Core)
```

- **Kernel** (e.g. `uname -a`):

```
Linux kube-master1.v.rmb938.me 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

- **Install tools**:

  * Custom RPMs deployed via Puppet

**What happened**:

Any files that look like valid Pod definitions in the Kubelet `pod-manifest-path` will be consumed without checking extensions. 

**What you expected to happen**:

Kubelet to validate file extensions and only accept files with `*.json, *.yaml and *.yml` extensions.

**How to reproduce it** (as minimally and precisely as possible):

Create a valid Pod definition in `pod-manifest-path` with an invalid extension.

**Comment by calebamiles** [comment]
Thanks for submitting your issue @rmb938, this looks like a feature request to me but perhaps you were thinking that this was a bug? Could someone from @kubernetes/sig-cli-feature-requests please help qualify the request? Thanks!

**Comment by rmb938** [comment]
As a user this seems more like a bug since the behavior is unexpected and not documented anywhere that this is the case, but every project classifies these things differently. It doesn't really matter to me as long as this feature/bug is documented or fixed in some way.

**Comment by ymqytw** [comment]
Node team owns `kubelet`.
@kubernetes/sig-node-feature-requests

**Comment by yujuhong** [comment]
I think this is working as intended. We also have files ending with `.manifest` or other names in the cluster.
Documentation is a while other issue.
