### ISSUE TITLE
DefaultTolerationSeconds admission controller is not working

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#42716]
Default toleration should be applied to newly created Pods. But:
```bash
$ kubectl run test --image=kubernetes/pause
$ kubectl get pod -o json
```
Gives result:
```json
            "spec": {
                "containers": [
                    {
                        "image": "kubernetes/pause",
                        "imagePullPolicy": "Always",
                        "name": "test",
                        "resources": {
                            "requests": {
                                "cpu": "100m"
                            }
                        },
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "File",
                        "volumeMounts": [
                            {
                                "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                                "name": "default-token-x4vbw",
                                "readOnly": true
                            }
                        ]
                    }
                ],
                "dnsPolicy": "ClusterFirst",
                "nodeName": "e2e-test-gmarek-minion-group-9vzb",
                "restartPolicy": "Always",
                "schedulerName": "default-scheduler",
                "securityContext": {},
                "serviceAccount": "default",
                "serviceAccountName": "default",
                "terminationGracePeriodSeconds": 30,
                "volumes": [
                    {
                        "name": "default-token-x4vbw",
                        "secret": {
                            "defaultMode": 420,
                            "secretName": "default-token-x4vbw"
                        }
                    }
                ]
            },
```

Log from the apiserver says:
```
E0308 07:16:37.959599       5 admission.go:71] expected pod but got Pod
```
Which indicates some problems with casting:
```
 69   pod, ok := attributes.GetObject().(*v1.Pod)
 70   if !ok {
 71     glog.Errorf("expected pod but got %s", attributes.GetKind().Kind)
 72     return nil
 73   }
```

This admission controller is using:
```
"k8s.io/kubernetes/pkg/api/v1"
```

Which is probably wrong, as I guess it should be `api/v1/` from client-go. Another example when apimachinery refactoring bites us. cc @deads2k @lavalamp @caesarxuchao @brendandburns 

@kevin-wangzefeng please fix, and verify that it's working.

cc @davidopp

**Comment by kevin-wangzefeng** [comment]
Got it, I'm taking a look.

**Comment by kevin-wangzefeng** [comment]
Just took a look, some functions this admission controller depends in `kubernetes/pkg/api/v1/helpers.go`, i.e. `AddOrUpdateTolerationInPod()` don't exist in `client-go/pkg/api/v1/helpers.go`

@caesarxuchao is there any particular reason that we don't sync these functions?

**Comment by kevin-wangzefeng** [comment]
Nevermind my last reply, I found it.

**Comment by deads2k** [comment]
> Which is probably wrong, as I guess it should be api/v1/ from client-go. Another example when apimachinery refactoring bites us. cc @deads2k @lavalamp @caesarxuchao @brendandburns

I doubt it on both counts.  Admission plugins use internal objects, you so you want to cast using `pkg/api.Pod` and that's code we didn't touch or change.  Looks like it was just broken and test-less.

**Comment by kevin-wangzefeng** [comment]
@deads2k thanks for the reply, I just found the versioned objects don't work in admission controller, will use internal object instead.

**Comment by liggitt** [comment]
The plugin also needs to make sure it's not dealing with a subresource, and I'd expect it to return an error if it gets an object it doesn't recognize, not allow the pod.
