### ISSUE TITLE
Missing gcr.io/google_containers/etcd-ppc64le:3.0.17 image

### ISSUE THREAD

**Issue by mkumatag** [kubernetes/kubernetes#42714]
Latest kubeadm code is looking for 3.0.17 version of gcr.io/google_containers/etcd-ppc64le docker image but is missing. Please push this image to work latest kubeadm properly on ppc64le platform.

**Comment by mkumatag** [comment]
\cc @ixdy @luxas

**Comment by luxas** [comment]
I think @wojtek-t should have pushed it; however I see it isn't pushed and yet has to be...
@ixdy might also be able to chime in if @wojtek-t experienced problems or something...

etcd3.0.17 for s390x should also be pushed

**Comment by ixdy** [comment]
It looks like only the amd64 version of 3.0.17 was pushed. I can push the others.

**Comment by luxas** [comment]
@ixdy Thanks! Only s390x left: https://gcr.io/v2/google-containers/etcd-s390x/tags/list

**Comment by mkumatag** [comment]
Thanks a lot @ixdy @luxas

**Comment by ixdy** [comment]
sorry, got distracted earlier and forgot to finish. pushing now.
