### ISSUE TITLE
Kubelet CNI nsenter failure

### ISSUE THREAD

**Issue by DreadPirateShawn** [kubernetes/kubernetes#42735]
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Bare metal
- **OS** (e.g. from /etc/os-release): Ubuntu precise (12.04.4 LTS)
- **Kernel** (e.g. `uname -a`): 3.13.0-55-generic
- **Install tools**: N/A
- **Others**: N/A

**What happened**:

During an otherwise-normal rollingupdate for a replication controller, we see this error in the logs:

```
E0307 21:43:51.235958    3650 docker_manager.go:373] NetworkPlugin cni failed on the status hook for pod 'foo-r3rg5' - Unexpected command output nsenter: cannot open /proc/5875/ns/net: No such file or directory\n with error: exit status 1
```

**What you expected to happen**:

Expected that successful rollingupdate wouldn't generate error-level logs without an error-level problem -- trying to determine what the error-level problem is.

**How to reproduce it** (as minimally and precisely as possible):

During our prod upgrade of various services, this occurred during 3 out of 70 rollingupdates.

**Anything else we need to know**:

Perhaps this is the same general issue as #25281? But I couldn't find any references to the "Unexpected command output nsenter" variation seen above, thus filing separately.

**Comment by calebamiles** [comment]
Could someone from @kubernetes/sig-node-bugs and @kubernetes/sig-network-bugs please help with triage? Thanks!

**Comment by dchen1107** [comment]
This is a not a 1.6 blocker, and I saw those nsenter error above before which came from a small race window between pod status and cni execution. Remove this from 1.6 milestone.

**Comment by aespinosa** [comment]
This is also happening in v1.6.1 using the kubenet network plugin:


```
docker_sandbox.go:263] NetworkPlugin kubenet failed on the status hook for pod "kubernetes-dashboard-v1.4.0-3sf40_kube-system": Unexpected command output nsenter: cannot open : No such file or directory
 with error: exit status 1
```

**Comment by freehan** [comment]
Is there other symptoms besides the log? Like lost of pod IP or some sort?

IIUC, pod deletion and status check run in seperate go routines. If a pod sandbox just got stopped and status check happened right after that. Status check might failed with this log.

**Comment by aespinosa** [comment]
@freehan I see Pod's IPs still being available.  I can run `kubectl port-forward` on them with no problem.

The problem i'm encountering is that I get 503s when accessing http services through the apiserver's proxy endpoints.

**Comment by freehan** [comment]
do you see this log a lot? or during rolling update?
do you encounter 503s during rolling update? or regularly?

**Comment by aespinosa** [comment]
I see this line a lot regularly. I'm not even using rolling updates.  I just have plain ReplicaSets / ReplicationControllers made. And since there's this kubenet failure, pods are being restarted by the RS/RC.

**Comment by freehan** [comment]
@aespinosa Sounds like your problem is different from the issue here. We need to know more about your setup. Need the output of following command:
`ps aux|grep kubelet`
`ifconfig`
what is your OS distro?

Just to confirm, the pods are able to start. Later they got recreated? Pod IP changed right?

**Comment by aespinosa** [comment]
kubelet:
```
/usr/bin/kubelet --api-servers=https://ip-xxxxxxxxx.ec2.internal --address=0.0.0.0 --port=10250 --healthz-bind-address=0.0.0.0 --allow-privileged=true --enable-debugging-handlers --pod-manifest-path=/etc/kubernetes/manifests --hostname-override=ip-172-xxx-xxx-xxxec2.internal --cloud-provider=aws --network-plugin=kubenet -v=2 --cluster-domain=cluster.local --cluster-dns=10.254.10.10
```

Distro:

No the kubelet dit not restart.

After a while, the pods are running now and able to start.

**Comment by freehan** [comment]
> After a while, the pods are running now and able to start.

Could you elaborate? What is the sequence of symptoms and operations?

**Comment by aespinosa** [comment]
I tried to delete and have the pods be resurrected by the replicaset.  The pod has been created and was allocated a Pod IP successfully.  

However, I still have problems of the proxy endpoints at the master not being able to be served.  I'm using the aws cloud provider and I don't see my route tables being updated either.

**Comment by freehan** [comment]
Are you still able to reproduce the problem related to pod IP?

I am not familiar with aws cloud provider. cc @justinsb

**Comment by aespinosa** [comment]
Thanks for the help @freehan . I figured out that my problem from the controller-manager's logs. It was saying it can't update route tables because of duplicate matching route tables when querying AWS.

**Comment by DreadPirateShawn** [comment]
@freehan So -- ignoring the sidebar issue @aespinosa had, what's the next step here? Is it to fix the small race window between pod status and cni execution?

(I'm not in a rush, just clarifying what to expect.)

**Comment by freehan** [comment]
@DreadPirateShawn 
Besides the error log, is there any problem that stands out?

We need kubelet log to confirm it as a race between kubelet pod status sync and cni network plugin execution. 

cc: @yujuhong

**Comment by yujuhong** [comment]
I am a bit lost in all these discussions. What exactly is the problem (besides the error message in the log) that we are dealing with?

**Comment by vishh** [comment]
I hit (possibly) the same issue. With a cluster from HEAD, kube-system not in host net namespace fails to come up

```
$ k get po -n kube-system | grep -v Running
NAME                                              READY     STATUS                                                                                                                                                                                                                                                                  RESTARTS   AGE
fluentd-gcp-v2.0-0flxx                            0/2       rpc error: code = 2 desc = failed to start container "15e07e324daa0f68793c454d81173c42b9c2e86d41b24236206756f2b55c7633": Error response from daemon: cannot join network of a non running container: 9f2593412ac541240a74ce445344e777b7fdb86c8ebc13520283a5e02f679f2e   528        12h
fluentd-gcp-v2.0-1h18l                            0/2       rpc error: code = 2 desc = failed to start container "a918404ab141350861cf653ed3b0b54924d0c8017316c45a45ab7f754065d521": Error response from daemon: cannot join network of a non running container: 3ac6abfa227e42665dcbe51aae62b97b924b5a9b0d9261529de806d6d627be7f   662        12h
fluentd-gcp-v2.0-5cdrh                            0/2       rpc error: code = 2 desc = failed to start container "68a7b104f66dbd2ad5874a8f89618b5d32af9f5b01e4114a8b750f513adced14": Error response from daemon: cannot join network of a non running container: 968a72050d2d9333837d1cd4dcaa645f5e21efd74e9745082b409803ce8da63e   384        12h
fluentd-gcp-v2.0-q73tm                            0/2       rpc error: code = 2 desc = failed to start container "3910156c8c6e712129bcc60bd8d9ff1c13bdb403cba18b0171a1d3da5ae8f434": Error response from daemon: cannot join network of a non running container: bf4d20fe360d4c1cf25987875e3b45642cd9317d39c51749b15b7d3b4fcbdf33   72         12h
heapster-v1.3.0-2598322454-1trbt                  0/4       rpc error: code = 2 desc = failed to start container "7d831a61aaf12752f790b86a6e004f3e40814670f8aa781eb24532c379cdd53c": Error response from daemon: cannot join network of a non running container: a5122aa07a1f027e1e03733c442d082162e6bd30534e326b1550ac7843e3ce64   424        12h
kube-dns-2473071502-08smf                         0/3       rpc error: code = 2 desc = failed to start container "b443d0ccfb753b32d304bf4ae281b85d8e146f6e9592eb253438e5a12b247f3f": Error response from daemon: cannot join network of a non running container: a4cf42c8f65e913e5cc9edea70ef7721f592adda5510341f508944d71435167d   84         12h
kube-dns-autoscaler-2042644734-6vz7d              0/1       rpc error: code = 2 desc = failed to start container "e0279bdab408ae39ba53abecd111001b06e051fa511d6b77df9a07a727776f31": Error response from daemon: cannot join network of a non running container: 6cb2f4de5dfde918d50e47c85fe15a3a59ea684a8bff307f8839997409738e41   115        12h
kubernetes-dashboard-638781211-v0q5l              0/1       rpc error: code = 2 desc = failed to start container "eea90aeccef3b30feab78d7dda50f93952ae10544032445eb7406555b2345f0f": Error response from daemon: cannot join network of a non running container: 09ab2bd4b25161151f0c26d83af1fb4d968b25e58870c640969bc8d8ee48e802   38         12h
l7-default-backend-1599978672-st6tj               0/1       rpc error: code = 2 desc = failed to start container "274ac2867f40a5275cee5f3959b6e05166d27fab9944f33abe829576f15c7b66": Error response from daemon: cannot join network of a non running container: 24d2dcf060bb7075efeeebf20188f43391e7fdefe2560156b6ea91047954fb28   79         12h
monitoring-influxdb-grafana-v4-mbtgv              0/2       rpc error: code = 2 desc = failed to start container "da19ad4133c194671b85874afd327879bf32ee869ab095160d29990d0377d518": Error response from daemon: cannot join network of a non running container: f613d4805b5d9a681461b203f7140a684baada3229f87668e2ed98494648ab13   74         12h
```

Kubelet logs has the following warning messages, which the infra container being restarted in a loop
```
May 12 16:26:05 e2e-test-vishnuk-minion-group-tjr0 kubelet[1272]: W0512 16:26:05.488409    1272 pod_container_deletor.go:77] Container "2b9990b748a79c5eb711bedb61e7eb0c3767d81692f1d70933216ced7465542a" not found in pod's containers
May 12 16:26:05 e2e-test-vishnuk-minion-group-tjr0 kubelet[1272]: W0512 16:26:05.494757    1272 docker_sandbox.go:285] NetworkPlugin kubenet failed on the status hook for pod "kube-dns-autoscaler-2042644734-6vz7d_kube-system": Cannot find the network namespace, skipping pod network status for container {"docker" "faf66266a7e06c4e1e9f8ff99fb3ac133cd91f488b22747fe1d49e92a27c7108"}
May 12 16:26:05 e2e-test-vishnuk-minion-group-tjr0 kubelet[1272]: W0512 16:26:05.496795    1272 docker_sandbox.go:285] NetworkPlugin kubenet failed on the status hook for pod "kube-dns-autoscaler-2042644734-6vz7d_kube-system": Cannot find the network namespace, skipping pod network status for container {"docker" "1ebeef7ec432f322c949363a937c9647674825fd9a120e5768ee5eacf0c23f75"}
May 12 16:26:05 e2e-test-vishnuk-minion-group-tjr0 kubelet[1272]: W0512 16:26:05.498753    1272 docker_sandbox.go:285] NetworkPlugin kubenet failed on the status hook for pod "kube-dns-autoscaler-2042644734-6vz7d_kube-system": Cannot find the network namespace, skipping pod network status for container {"docker" "a43ca215854a316e46b62c0737539923638262059112336f706da251b86b1149"}
May 12 16:26:05 e2e-test-vishnuk-minion-group-tjr0 kubelet[1272]: W0512 16:26:05.500791    1272 docker_sandbox.go:285] NetworkPlugin kubenet failed on the status hook for pod "kube-dns-autoscaler-2042644734-6vz7d_kube-system": Cannot find the network namespace, skipping pod network status for container {"docker" "d439fb1bf3d99c0438023e3548d6ab5ead3c37f6d4bb9436f0d5ddf3928bdc46"}
May 12 16:26:05 e2e-test-vishnuk-minion-group-tjr0 kubelet[1272]: W0512 16:26:05.502725    1272 docker_sandbox.go:285] NetworkPlugin kubenet failed on the status hook for pod "kube-dns-autoscaler-2042644734-6vz7d_kube-system": Cannot find the network namespace, skipping pod network status for container {"docker" "7ef2d537193d765e9b9dbfb57fab28328e9029f2450ff55aa44015958f705a6c"}
May 12 16:26:05 e2e-test-vishnuk-minion-group-tjr0 kubelet[1272]: W0512 16:26:05.504724    1272 docker_sandbox.go:285] NetworkPlugin kubenet failed on the status hook for pod "kube-dns-autoscaler-2042644734-6vz7d_kube-system": Cannot find the network namespace, skipping pod network status for container {"docker" "b2acb2fae37ebe3a876039fcaeff4236055ea055214a8b17af85e6b472b85e20"}
May 12 16:26:05 e2e-test-vishnuk-minion-group-tjr0 kubelet[1272]: W0512 16:26:05.506781    1272 docker_sandbox.go:285] NetworkPlugin kubenet failed on the status hook for pod "kube-dns-autoscaler-2042644734-6vz7d_kube-system": Cannot find the network namespace, skipping pod network status for container {"docker" "ee915d5a6e2207432f5c379f310be765f6b1f1b40b26a2035ee025c912da9f0c"}
May 12 16:26:05 e2e-test-vishnuk-minion-group-tjr0 kubelet[1272]: W0512 16:26:05.509020    1272 docker_sandbox.go:285] NetworkPlugin kubenet failed on the status hook for pod "kube-dns-autoscaler-2042644734-6vz7d_kube-system": Cannot find the network namespace, skipping pod network status for container {"docker" "33ef9686a51d190adf2883553593f9513dcc88f904ee7b51629018a800408b3e"}
May 12 16:26:05 e2e-test-vishnuk-minion-group-tjr0 kubelet[1272]: I0512 16:26:05.513086    1272 generic.go:343] PLEG: Write status for kube-dns-autoscaler-2042644734-6vz7d/kube-system: &container.PodStatus{ID:"117537e6-36de-11e7-9733-42010af00002", Name:"kube-dns-autoscaler-2042644734-6vz7d", Namespace:"kube-system", IP:"", ContainerStatuses:[]*container.ContainerStatus{(*container.ContainerStatus)(0xc4217e89a0)}, SandboxStatuses:[]*runtime.PodSandboxStatus{(*runtime.PodSandboxStatus)(0xc42254bb80), (*runtime.PodSandboxStatus)(0xc42273c050), (*runtime.PodSandboxStatus)(0xc42273c460), (*runtime.PodSandboxStatus)(0xc42273c910), (*runtime.PodSandboxStatus)(0xc42273cd20), (*runtime.PodSandboxStatus)(0xc42273d180), (*runtime.PodSandboxStatus)(0xc420b86f50), (*runtime.PodSandboxStatus)(0xc42166e320)}} (err: <nil>)
May 12 16:26:05 e2e-test-vishnuk-minion-group-tjr0 kubelet[1272]: W0512 16:26:05.516551    1272 pod_container_deletor.go:77] Container "faf66266a7e06c4e1e9f8ff99fb3ac133cd91f488b22747fe1d49e92a27c7108" not found in pod's containers
```

**Comment by andreychernih** [comment]
Just bumped image versions to 2.1.5 in addons/networking.projectcalico.org/k8s-1.6.yaml manually and it started to work correctly. I see that Calico has been already upgraded to 2.1.5 in master, so we just need to wait for new release.

**Comment by dcbw** [comment]
https://github.com/kubernetes/kubernetes/pull/43879 may help this, though it has been reverted and needs some fixups.

**Comment by thockin** [comment]
Update?

**Comment by hfrog** [comment]
I've seen the same errors in my cluster after turning on RBAC. The reason is default calico.yaml (http://docs.projectcalico.org/v2.2/getting-started/kubernetes/installation/hosted/calico.yaml) lacks of cluster roles and bindings. After applying https://github.com/projectcalico/calico/blob/master/master/getting-started/kubernetes/installation/rbac.yaml all is ok.
Hope this helps

**Comment by saschagrunert** [comment]
I am not sure if this issue is related to RBAC since it also occurs then not using calico but cni networking via flannel. I found out that the `cni` Network interface got some sort of disconnect (via dmesg), then reconnects and after that the nsenter failures occurred.

**Comment by bowei** [comment]
@dchen1107 move to next milestone

Reading through the issue, there seem to be a couple of different intersecting issues going on here, it seems like it needs some more investigation.

**Comment by matchstick** [comment]
This feels like an umbrella issue at this point. It keeps redefining itself.  
@DreadPirateShawn I am moving out of 1.7 if that is inappropriate please have us re-add milestone 1.7.

**Comment by murhum1** [comment]
I'm also getting this every now and then, and *at least* in my case it seems to be related to resource limits. I'm trying to run a pod both with and without a resource limit - every time I specify a memory limit, the pod is stuck at `ContainerCreating`, and every time I comment them out it starts `Running` without a hitch.

Here's some logs from the kubelet trying to run the resource limited pods. I'm running with a kubeadm install + flannel.

    Jun 13 14:43:52 my.server.com kubelet[25154]: with error: exit status 1
    Jun 13 14:43:52 my.server.com kubelet[25154]: W0613 14:43:52.344639   25154 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "scala-test-bqr59_grader": Unexpected command output nsenter: cannot open : No such file or directory
    Jun 13 14:43:52 my.server.com kubelet[25154]: with error: exit status 1
    Jun 13 14:43:52 my.server.com kubelet[25154]: W0613 14:43:52.365529   25154 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "scala-test-bqr59_grader": Unexpected command output nsenter: cannot open : No such file or directory
    Jun 13 14:43:52 my.server.com kubelet[25154]: with error: exit status 1
    Jun 13 14:43:52 my.server.com kubelet[25154]: W0613 14:43:52.387687   25154 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "scala-test-bqr59_grader": Unexpected command output nsenter: cannot open : No such file or directory
   	Jun 13 14:43:52 my.server.com kubelet[25154]: with error: exit status 1
    Jun 13 14:43:52 my.server.com kubelet[25154]: E0613 14:43:52.397966   25154 kubelet_network.go:139] Search Line limits were exceeded, some dns names have been omitted, the applied search line is: grader.svc.cluster.local svc.cluster.local cluster.local org.aalto.fi nbe.aalto.fi becs.hut.fi
    Jun 13 14:43:52 my.server.com kubelet[25154]: W0613 14:43:52.914538   25154 container.go:352] Failed to create summary reader for "/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod6d5940c2_502d_11e7_9b32_005056940720.slice/docker-875a65dd3e3c4e1e6919ce34e4d125699f5e64db8cdd804626a6eac38802b640.scope": none of the resources are being tracked.
    Jun 13 14:43:52 my.server.com kubelet[25154]: E0613 14:43:52.915062   25154 remote_runtime.go:86] RunPodSandbox from runtime service failed: rpc error: code = 2 desc = failed to start sandbox container for pod "scala-test-bqr59": Error response from daemon: {"message":"invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"process_linux.go:286: decoding sync type from init pipe caused \\\\\\\"read parent: connection reset by peer\\\\\\\"\\\"\\n\""}
    Jun 13 14:43:52 my.server.com kubelet[25154]: E0613 14:43:52.915133   25154 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "scala-test-bqr59_grader(6d5940c2-502d-11e7-9b32-005056940720)" failed: rpc error: code = 2 desc = failed to start sandbox container for pod "scala-test-bqr59": Error response from daemon: {"message":"invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"process_linux.go:286: decoding sync type from init pipe caused \\\\\\\"read parent: connection reset by peer\\\\\\\"\\\"\\n\""}

**Comment by yujuhong** [comment]
FWIW, we investigated @vishh's cluster in https://github.com/kubernetes/kubernetes/issues/42735#issuecomment-301159505, and found that it was not relevant to this thread, but forgot to come back and update.

**Comment by DreadPirateShawn** [comment]
@matchstick Yeah, the umbrella drift was unfortunate. In the original reply by @dchen1107 he said the original ticket was due to "a small race window between pod status and cni execution."

Is there a ticket / action item for that particular issue, which I originally reported?

(Or am I misunderstanding, is the original issue inseparable from the other issues people added to the ticket?)
