### ISSUE TITLE
CRI: PodSandbox was restarted in hollow node when running kubemark

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#42736]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-100-gce/1689/

Pod `density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn` has a restart count 1

FYI, all relevant messages about this pod in the kubelet.log:
https://gist.github.com/yujuhong/b1dc4fecfe835944d1cd5c6f67f006ed

From the sync loop timeline, some containers died.
```
12:44:57.602374       9 kubelet.go:1808] SyncLoop (ADD, "api"): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)"
12:44:58.787422       9 kubelet.go:1842] SyncLoop (PLEG): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)", event: &pleg.PodLifecycleEvent{ID:"094859d4-03fd-11e7-81ad-42010af00006", Type:"ContainerDied", Data:"88d185ba4599ed5e"}
12:44:59.791857       9 kubelet.go:1842] SyncLoop (PLEG): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)", event: &pleg.PodLifecycleEvent{ID:"094859d4-03fd-11e7-81ad-42010af00006", Type:"ContainerStarted", Data:"40194345840e54d9"}
12:45:00.971051       9 kubelet.go:1842] SyncLoop (PLEG): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)", event: &pleg.PodLifecycleEvent{ID:"094859d4-03fd-11e7-81ad-42010af00006", Type:"ContainerDied", Data:"40194345840e54d9"}
12:45:00.971110       9 kubelet.go:1842] SyncLoop (PLEG): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)", event: &pleg.PodLifecycleEvent{ID:"094859d4-03fd-11e7-81ad-42010af00006", Type:"ContainerStarted", Data:"40194245840e5326"}
12:45:00.971153       9 kubelet.go:1842] SyncLoop (PLEG): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)", event: &pleg.PodLifecycleEvent{ID:"094859d4-03fd-11e7-81ad-42010af00006", Type:"ContainerStarted", Data:"88d185ba4599ed5e"}
12:49:32.331263       9 kubelet.go:1824] SyncLoop (DELETE, "api"): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)"
12:49:33.104486       9 kubelet.go:1842] SyncLoop (PLEG): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)", event: &pleg.PodLifecycleEvent{ID:"094859d4-03fd-11e7-81ad-42010af00006", Type:"ContainerDied", Data:"40194245840e5326"}
12:49:33.104541       9 kubelet.go:1842] SyncLoop (PLEG): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)", event: &pleg.PodLifecycleEvent{ID:"094859d4-03fd-11e7-81ad-42010af00006", Type:"ContainerDied", Data:"88d185ba4599ed5e"}
12:49:34.118279       9 kubelet.go:1824] SyncLoop (DELETE, "api"): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)"
12:49:34.121374       9 kubelet.go:1818] SyncLoop (REMOVE, "api"): "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)"
```

Check the log again:
```
I0308 12:44:57.908490       9 kuberuntime_manager.go:370] No sandbox for pod "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)" can be found. Need to start a new one
I0308 12:44:57.909301       9 kuberuntime_manager.go:549] computePodContainerChanges got {CreateSandbox:true SandboxID: Attempt:0 ContainersToStart:map[0:Container {Name:density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004 Image:gcr.io/google_containers/pause-amd64:3.0 Command:[] Args:
[] WorkingDir: Ports:[{Name: HostPort:0 ContainerPort:80 Protocol:TCP HostIP:}] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[memory:{i:{value:40265318 scale:0} d:{Dec:<nil>} s:40265318 Format:DecimalSI} cpu:{i:{value:10 scale:-3} d:{Dec:<nil>} s:10m Format:DecimalSI}]} Volu
meMounts:[{Name:default-token-xl0xh ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityConte
xt:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.] ContainersToKeep:map[] ContainersToKill:map[] InitFailed:false InitContainersToKeep:map[]} for pod "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-
1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)"
I0308 12:44:57.909490       9 kuberuntime_manager.go:558] SyncPod received new pod "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)", will create a new sandbox for it
I0308 12:44:57.909521       9 kuberuntime_manager.go:567] Stopping PodSandbox for "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)", will start new one
I0308 12:44:57.909561       9 kuberuntime_manager.go:613] Creating sandbox for pod "density3000-0-d8af0875-03fc-11e7-a59e-0242ac110004-6zvtn_e2e-tests-density-30-1-tprgr(094859d4-03fd-11e7-81ad-42010af00006)"
I0308 12:44:58.017948       9 kuberuntime_gc.go:133] Removing sandbox "88d185ba4599ed5e"
```

The sandbox was GC'd right after it was created. This led to kubelet killing all the containers in the pod since the sandbox needed to be recreated. 

Need to check whether this was caused by the container state emulated by fakedockerclient, or by a real bug.

/cc @feiskyer @Random-Liu

**Comment by yujuhong** [comment]
kuberuntime GC routine has a minAge protection such that it can't GC any pod sandbox that was created no more than 30 seconds ago). This doesn't seem to have be respected from the log. I suspect that the fakedockerclient was not returning a proper timestamp.

**Comment by gmarek** [comment]
@yujuhong - by looking at the logs, can you tell if there's an easy repro?

**Comment by wojtek-t** [comment]
So given that this happens also in non-kubemark suites, it seems like a release blocker to me.

Anyway - @yujuhong - do you think it's releated to number of pod on a node, or it's just that it happens from time to time, and in scalability suites (no matter if it's kubemark or not) we have more of those tries (due to scale)?

**Comment by yujuhong** [comment]
I think the timestamp comparison logic might be wrong in the sandbox garbage collector. 

This would only happen (in my theory) when the the snapshot of all containers/sandboxes on the node are taken when:
 - sandbox is created but not running (started) yet.
 - other containers in the pod haven't not been created.

In this case, the fail-safe (minAge) kicks in, and apparently failed in the tests discussed above. This would more likely to happen when during batch creation of more pods. kubelet would usually heal itself by restarting all container in the pod (which has the undesirable side-effect of killing the user containers of course). I think other tests might not catch this because 1) they don't perform large batch creation, and 2) they don't check the restart count.

**Comment by yujuhong** [comment]
Oh the above comment was completely based on my theory. 

Reproducing this deterministically on a working node may need some hacking in the kubelet code (e.g., inject a long enough sleep after sandbox creation). I will try writing a unit test first to verify the behavior.

**Comment by yujuhong** [comment]
Can't reproduce this in my cluster with artificially injected latency...
Adding more debug information in https://github.com/kubernetes/kubernetes/pull/42751


For people who are interested in checking the logs and identify the victim pod, here are the instructions:
 1. Download the artifacts: E.g., `gsutil cp -r  gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1337 .`
 2. Find the (density) pod with restart count > 0: `grep "Status for" */kubelet.log | grep density | grep -E "RestartCount:([1-9]+)"`

**Comment by feiskyer** [comment]
Didn't reproduce the problem either.

> In this case, the fail-safe (minAge) kicks in, and apparently failed in the tests discussed above. This would more likely to happen when during batch creation of more pods. kubelet would usually heal itself by restarting all container in the pod (which has the undesirable side-effect of killing the user containers of course). I think other tests might not catch this because 1) they don't perform large batch creation, and 2) they don't check the restart count.

I think so. GC can't distinguish just-created sandboxes from failed sandboxes. Especially when the time from sandbox creation to ready is longer than GC's minAge.

I'm wondering should runtime (e.g. dockershim) filter out those created-but-not-ready sandboxes from sandbox list? or introduce another sandbox state `CREATED`  in CRI?

**Comment by yujuhong** [comment]
#42768 has been merged 11 hours ago and scalability suite hasn't flaked since. Will monitor and see if there is any need to reopen.

**Comment by feiskyer** [comment]
> #42768 has been merged 11 hours ago and scalability suite hasn't flaked since. Will monitor and see if there is any need to reopen.

@yujuhong  OK. But because `GC can't distinguish just-created sandboxes from failed sandboxes`, there are still potential problems under big  pressure.

**Comment by yujuhong** [comment]
> @yujuhong OK. But because GC can't distinguish just-created sandboxes from failed sandboxes, there are still potential problems under big pressure.

First, this issue is no longer a release blocker after the fix. Let's open a separate issue to discuss potential improvement, instead of commenting on a closed issue :)  Also, FWIW, we used the same logic in the old docker manager, so this is also not a regression.

**Comment by feiskyer** [comment]
@yujuhong Agreed. Opened #42856 for this.
