### ISSUE TITLE
[Federation] Refactor the parameter lists in kubefed to use parameter-grouping structs

### ISSUE THREAD

**Issue by perotinus** [kubernetes/kubernetes#42743]
The parameter lists in kubefed are getting unwieldy, and making it harder to update and understand them. We should figure out a good set of parameter objects that make it easer to follow the data flow.

I think this can wait until the outstanding kubefed PRs are merged in, in order to avoid a string of rebases.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#116.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
