### ISSUE TITLE
NoExecute taints should not evict static pods

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#42753]
From @gmarek in https://github.com/kubernetes/kubernetes/issues/42685#issuecomment-284987556: "When node is tainted TaintController tries to kill kube-proxy over and over again (and it fails, as this is a manifest Pod): [...] I guess kubelet is just ignoring the request (or sth). Correct solution is to give kube-proxy infinite toleration for NoExecute taints."

(This would involve changing the manifest for every static pod to add tolerations for taints `node.alpha.kubernetes.io/unreachable` and `node.alpha.kubernetes.io/notReady`)

I guess the alternative is to have the taint manager somehow detect that something is a static pod, and not bother to evict it.

cc/ @bowei @freehan @kubernetes/sig-node-feature-requests

**Comment by gmarek** [comment]
IIUC there's no way of detecting if something's a static pod. @yujuhong

**Comment by davidopp** [comment]
Yeah unfortunately that's my understanding too...

**Comment by gmarek** [comment]
Actually I think kube-proxy should tolerate all NoExecute Taints. Not unreachable and not ready ones. It's impossible to delete it, so there's no point in trying.

**Comment by davidopp** [comment]
Not just kube-proxy -- all static pods.

**Comment by gmarek** [comment]
@yujuhong @dchen1107 - do you think that Kubelet would be able to apply them automatically if they're not present? Or do we want to depend on cluster setup tooling to make sure manifests have those?

**Comment by davidopp** [comment]
In the past @dchen1107 has argued strongly she does not want Kubelet to have to distinguish static pods from regular pods. So I think the answer to the first question is going to be no, and the second one yes.

**Comment by gmarek** [comment]
Then I guess cc @kubernetes/sig-cluster-lifecycle-bugs

**Comment by gmarek** [comment]
To be fair, IIUC it does treat static pods differently than ordinary ones. E.g. it doesn't delete them.

**Comment by yujuhong** [comment]
I'm not sure I have the full context ere. Are the static pods being killed or just the mirror pods?
- If it's just mirror pods, there are ways for the controller to distinguish mirror pods and ignore them. 
- If it's the static pods, then I assume we are talking about kubelet's pod admission logic.

**Comment by dchen1107** [comment]
Good catch!

> do you think that Kubelet would be able to apply them automatically if they're not present? Or do we want to depend on cluster setup tooling to make sure manifests have those?

If we really understand all use cases of static pods, and agreed that all static pods should have infinite toleration for NoExecute taints. Then Kubelet can automatically apply this set of annotations to the static pods by default. This is different from critical annotation before since not all static pods are critical ones, there is no way for Kubelet to distinguish which one is critical and not.

**Comment by gmarek** [comment]
I believe we all agree that all static/mirror pods should have infinite toleration for NoExecute taints, as there's no point in trying to delete them. Can we leave setting this to Kubelet and writing this change to the Node team? @dchen1107 @yujuhong

**Comment by davidopp** [comment]
Sorry I was confused in my earlier comment. I think what @dchen1107 and @gmarek are suggesting sounds good. But because we need to get this into 1.6, if the Kubelet change is not simple, maybe it is simpler to just modify the manifest files, and then implement the Kubelet change in 1.7.

**Comment by cmluciano** [comment]
I poked around to see if I could access feasibility form the Kubelet side based on https://github.com/kubernetes/kubernetes/issues/42753#issuecomment-285271706.

There is a function for checking if a pod is static [here](https://github.com/kubernetes/kubernetes/blob/dd22743b54f280f41e68f206449a13ca949aca4e/pkg/kubelet/pod/mirror_client.go#L98-L100). 

I noted also that critical pods are also admitted [here](https://github.com/kubernetes/kubernetes/blob/dd22743b54f280f41e68f206449a13ca949aca4e/pkg/kubelet/pod/mirror_client.go#L93-L96).

I think the logic that adds passes all NoExecute for critical pods is in the DaemonSetController [here](https://github.com/kubernetes/kubernetes/blob/5af81b0955d907256a222e5cbcccfcba0db88b53/pkg/controller/daemon/daemoncontroller.go#L817).

I can try to expand on these patterns and add an e2e if we think this is the right choice.

**Comment by liggitt** [comment]
annotation-based pod source checks are not a pattern we should expand, since they can be spoofed, depending on where the check is done

**Comment by dchen1107** [comment]
Ok I rethink this a little bit more. I think we should handle this in TraintController since it drives the policy.

1) In previous releases, Kubelet already includes two annotations to indicate if a pod is static pod or not: kubernetes.io/config.mirror & kubernetes.io/config.source

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.hash: 69db7082545971586fc1c3552b94af95
    kubernetes.io/config.mirror: 69db7082545971586fc1c3552b94af95                  <==== Mirror with value 
    kubernetes.io/config.seen: 2017-03-09T21:38:56.57831411Z
    kubernetes.io/config.source: file                                                                          <==== Source is file here which indicates this is file-based static pod
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: 2017-03-09T21:39:01Z
  labels:
    component: kube-proxy
...
```

2) If TaintController can easily filter out those mirror pods / static pods with a sample logic as the bellowing: 

```
func mirrorPodFilter(pod api.Pod) (bool) {
        if _, found := pod.ObjectMeta.Annotations[types.ConfigMirrorAnnotationKey]; found {
                return false
        }
        return true
}
```

@davidopp @gmarek @thockin How do you think this approach? I think this is more generic.  

Another way to achieve this is applying this default annotation to the file-based pods right after this line at Kubelet: 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/config/common.go#L74

@liggitt Can you elaborate a little bit more what you mean above?

**Comment by smarterclayton** [comment]
Jordan was indicating that relying on "powerful" annotations that anyone
can set can lead to security challenges.

I actually liked the idea of the kubelet setting taints on static pods -
after all, the kubelet "owns" those pods.

**Comment by davidopp** [comment]
One of the primary motivations of taints and tolerations is to make special rules directly visible. So I am not in favor of just having TaintController silently skip taints on static pods. Taints should only be ignored when there is a corresponding toleration. 

@dchen1107 I wasn't completely clear on your suggestion "Another way to achieve this is applying this default annotation to the file-based pods right after this line at Kubelet." Did you mean "apply this toleration" ?

@smarterclayton I assume you meant "I actually liked the idea of the kubelet setting tolerations on static pods"

Anyway, having Kubelet add the toleration when it creates the pod seems like the best approach IMO.

**Comment by smarterclayton** [comment]
Yes

**Comment by dchen1107** [comment]
@davidopp re: https://github.com/kubernetes/kubernetes/issues/42753#issuecomment-285613463

Yes, the same as the original proposal: https://github.com/kubernetes/kubernetes/issues/42753#issuecomment-285205760

Looks like we are convergent on this. I can quickly send a pr to resolve this.

**Comment by ethernetdan** [comment]
@dchen1107 what's the status of this?
