### ISSUE TITLE
Workload API v1 requirements umbrella issue

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#42752]
I'd like all of the in-flight workload APIs (ReplicaSet, Deployment, StatefulSet, DaemonSet) to advance to v1 together as a group, sometime this year.

Related issues:
* Deployment v1 issue: #20130
* DaemonSet v1 issue: #15310
* StatefulSet beta: #28718
* Eliminate extensions API group: #43214 
* Workload controller design issue umbrella issue: #14961
* Extension patterns: #31571, #39337
* Common patterns: #37563, #42410
* https://github.com/kubernetes/community/wiki/Roadmap:-Deployment
* https://github.com/kubernetes/community/wiki/Roadmap:-ReplicaSet

I'd like to see at least:
* ~~Server-side cascading deletion (GC) by default (e.g., #23252, #40014)~~
* ~~Controller ref (#24946) to provide mutual exclusion even across controller types, but also ensure that orphaning and adoption work as expected~~
* ~~Upgrades/rollouts for DaemonSet and StatefulSet (#28706)~~
* Decide whether to change label/selector defaulting and/or selector update behavior (#34292, #26202, #24888, #14894, ...)
* ~~Decide whether to move forward with templateGeneration (https://github.com/kubernetes/community/pull/384) or with the new hash (https://github.com/kubernetes/community/pull/477, https://github.com/kubernetes/kubernetes/issues/29735)~~
* Decide whether to rename kubectl undo (#25236)
* ~~Decide whether we're going to try to unify storage for ReplicationController and ReplicaSet~~
* ~~DaemonSet and StatefulSet history and rollback~~
* ~~Scale subresource for all controllers for which it makes sense~~
* ~~Deployment overlap annotation cleanup (#43322)~~
* ~~Decide whether/which annotations should be propagated by updates (#37666)~~
* Decide what to do about clock skew (e.g., move minReadySeconds to pod https://github.com/kubernetes/kubernetes/pull/32771#issuecomment-249916983; #29229)
* Documentation completed (e.g., #18465)
* Double-check validation and defaults (e.g., #42479)
* Fix/cleanup taint/toleration support in DaemonSet (#29738), affinity/anti-affinity (#29276), schedulability (#26810), scheduling on master nodes (#29108), durability (#29193), etc.
  * Maybe via DaemonSet use of scheduler (#42002)

Bugs:
* ~~Scaled-down Deployments don't identify old ReplicaSets (#42570)~~

Maybe:
* Finish UnavailableReplicas (#41789)
* ~~Disallow activeDeadlineSeconds (#38684)~~
* Rollout strategy update improvement (#24198, #34292, #35345)
* ConfigMap rollouts (#22368, #31701, #43112, ...)
* Extensible rollout strategies (#14510)
* Make controllers aware of namespace deletion (#38612, #36891)
* Disallow label changes in status updates (#20978)
* Derive DaemonSet pod names from nodes (#41977)
* Coordinate DaemonSet updates with node updates (#42917) -- may need to change semantics of node selector, tolerations, and other scheduling constraints

Desirable, but can probably be done later:
* ~~Implement observedGeneration (#7328)~~
* Quota support (#23360)
* Ensure the controllers generate the desired events, such as events when they can't create pods (#21912)
* Graceful degradation (e.g., #33041, #2529)
* Eliminate special-case hacks for the controllers (e.g., #39687)
* Eliminate Expectations (#22061)
* Performance/scalability improvements (e.g., #17130, #17441, #18972, #34598, #38868, #40271)
* Automatic rollback (#23211)
* Infant mortality detection (#18568)
* Auto-pause (#11505)
* Attach, exec, portforward, proxy (e.g., #21227)
* Status cleanup (#42410)

Definitely should not block v1/GA:
* Factor out common functionality (#37563)
* Support relabeling (#36897)
* Scale down gradually (#23885)
* PodDisruptionBudget completion (#12611)
* Critical pod hack cleanups in favor of general priority/preemption (#22212, #40573)
* Easier image/tag updates (#29097) / image triggers 
* Hooks (#14512)
* Image tag resolution (#1697)
* Bulk quota (#25146)
* In-place updates (#9043)
* Rolling restart (#13488)
* Splitting out the pod template (#170)
* Selector overlap detection (#43321, #19830, #2210)
* Failure-domain awareness (e.g., #4301, #41394)
* Federation support (#37570)
* Service generation (#14956)
* Blue-green deployments (#33462)
* Min/max replica counts (#33843)
* Cron/batch jobs that run on every node (#17182, #36601)

TBD:
* Better history support (#28373)
* Kill specific pods (#36868)
* Deleted controllers in limbo (#24934)

We also should triage related issues that have been filed, though I did a quick triage through deployment and daemonset issues. 

cc @erictune @janetkuo @kow3ns @kargakis @foxish @enisoc @smarterclayton

**Comment by idvoretskyi** [comment]
Thanks for collecting this, Brian.

I would also suggest having an umbrella issue for DaemonSet as a feature under https://github.com/kubernetes/features/issues.

**Comment by bgrant0607** [comment]
While I had thought of DaemonSet as an admin API in the past, and had suggested a different API group (#8190), my current thinking is that it would be simpler for users for it to be in the apps group, as part of the continuum of workload APIs.

**Comment by bgrant0607** [comment]
I put all the workload APIs in the "application layer" (join kubernetes-dev to access):
https://docs.google.com/document/d/1XkjVm4bOeiVkj-Xt1LgoGiqWsBfNozJ51dyI-ljzt1o/edit#

**Comment by bgrant0607** [comment]
Feature issues:
DaemonSet updates: https://github.com/kubernetes/features/issues/124
StatefulSet updates: https://github.com/kubernetes/features/issues/188

**Comment by smarterclayton** [comment]
I think of DaemonSets as apps that tend to be used in one particular
context, so I'm +1 to it being apps.

On Mar 9, 2017, at 8:19 PM, Brian Grant <notifications@github.com> wrote:

Feature issues:
DaemonSet updates: kubernetes/features#124
<https://github.com/kubernetes/features/issues/124>
StatefulSet updates: kubernetes/features#188
<https://github.com/kubernetes/features/issues/188>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/42752#issuecomment-285543797>,
or mute the thread

**Comment by kargakis** [comment]
In my mind an administrative application is still an application so +1 for
apps

**Comment by soltysh** [comment]
👍 for apps, besides cluster administrator can always restrict access to them through RBAC, if needed.

**Comment by bgrant0607** [comment]
I fleshed out the issue description. PTAL. It's especially missing StatefulSet issues.

**Comment by bgrant0607** [comment]
We should also document some more of the common vision and conventions behind the workload APIs, to inform the subsequent roadmap.

I put some things in the system overview:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture.md#cluster-control-plane-aka-master

But we should document additional details, such as:
* It should be possible to manage an application using multiple controller API instances (e.g., multiple Deployments) or to write a third-party controller
* Support declarative rollouts (apply) as well as imperative rollouts (set, rollback)

**Comment by kargakis** [comment]
> Decide what to do about clock skew (e.g., move minReadySeconds to pod #32771 (comment); #29229)

MinReadySeconds proposal is https://github.com/kubernetes/community/pull/478

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-apps-proposals

**Comment by rphillips** [comment]
Are workload APIs still on target for GA in 1.9? Are there any blockers?

**Comment by kow3ns** [comment]
@rphillips 1.9 is still the plan

**Comment by luxas** [comment]
This was fixed in v1.9! Thank you all, great teamwork, mainly driven by SIG Apps :+1:!
