### ISSUE TITLE
Custom Kind via Third Party Resource Not Working Correctly

### ISSUE THREAD

**Issue by frankgreco** [kubernetes/kubernetes#42777]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): **BUG REPORT**

**Kubernetes version** (use `kubectl version`): **v1.5.3**

**Environment**:
- **Cloud provider or hardware configuration**: minikube (Mac OSX)
- **OS** (e.g. from /etc/os-release):
```
NAME=Buildroot
VERSION=2016.08
ID=buildroot
VERSION_ID=2016.08
PRETTY_NAME="Buildroot 2016.08"
```
- **Kernel** (e.g. `uname -a`): 
```Linux minikube 4.7.2 #6 SMP Wed Feb 22 11:18:55 PST 2017 x86_64 GNU/Linux```
- **Install tools**: minikube

**What happened**: (mvp example)
```sh
client$ echo \
--- \
apiVersion: extensions/v1beta1 \
kind: ThirdPartyResource \
metadata: \
  name: foo.bar.io \
description: sample resource \
versions: \
- name: v1 > tpr.yaml
$ kubectl apply -f tpr.yaml
node$ curl 127.0.0.1:8080/apis/bar.io/v1
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "bar.io/v1",
  "resources": [
    {
      "name": "foos",
      "namespaced": true,
      "kind": "Foo"
    }
  ]
}
client$ echo \
--- \
apiVersion: "bar.io/v1" \
kind: Foo \
metadata: \
  name: myname \
  namespace: default \
spec: \
  foo: bar > customKind.yaml
client$ kubectl apply -f customKind.yaml
F0308 20:51:41.992379   32015 helpers.go:107] error validating "customKind.yaml": error validating data: API version "bar.io/v1" isn't supported, only supports API versions ["v1" "metrics/v1alpha1" "extensions/v1beta1" "componentconfig/v1alpha1" "batch/v1" "autoscaling/v1" "authorization.k8s.io/v1beta1"]; if you choose to ignore these errors, turn validation off with --validate=false
```

**What you expected to happen**:
I expect the custom kind to be created succesfully. Note that this is almost exactly the same example as what is in the docs.

**How to reproduce it** (as minimally and precisely as possible):
Follow exactly the step in the `what happened` section

**Comment by liggitt** [comment]
`kubectl apply` does not work with third party resources prior to 1.6

**Comment by liggitt** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/40666

**Comment by frankgreco** [comment]
After ready through #40666, it sounds like there is not way to create a custom kind prior to 1.6 then? This doesn't seem like it would be the case though seeing that TPR is in beta.

**Comment by liggitt** [comment]
You can use kubectl create and replace. TPR is in the extensions API group but never formally graduated to beta.

**Comment by frankgreco** [comment]
seems to still be an issue with `kubectl create`
```sh
client$ kubectl create -f customKind.yaml
error validating "testPolicy.yaml": error validating data: API version "bar.io/v1" isn't supported, only supports API versions ["v1" "metrics/v1alpha1" "extensions/v1beta1" "componentconfig/v1alpha1" "batch/v1" "autoscaling/v1" "authorization.k8s.io/v1beta1"]; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by liggitt** [comment]
You might have stale discovery data cached in your ~/.kube folder (I think it has a ttl of five minutes by default).

**Comment by frankgreco** [comment]
Alright so I deleted my minikube cluster and recreated it. Now initially I created by TPR through the dashboard but I tried to create it via kubectl this time:

```sh
client$ echo \
--- \
apiVersion: extensions/v1beta1 \
kind: ThirdPartyResource \
metadata: \
  name: foo.bar.io \
description: sample resource \
versions: \
- name: v1 > tpr.yaml
$ kubectl create -f tpr.yaml
```

However, this failed **because** with --v=8 it is trying to POST to 
```sh
/apis/extensions/v1beta1/namespaces/default/thirdpartyresources
```
this of course gives a 404 because it's not a valid api path. However, I curled the following myself with the proper body and it worked:

```sh
/apis/extensions/v1beta1/thirdpartyresources
```

I then tried to apply my custom kind, but am still getting the same error as before (validation error).

I guess I can make a pull request to fix the first issue. it should be an easy fix I'd imagine.

**Comment by liggitt** [comment]
what version of kubectl are you using?

**Comment by frankgreco** [comment]
```sh
➜  Desktop kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean"}
```

**Comment by liggitt** [comment]
you need to upgrade kubectl to at least within one version of the apiserver, ideally the same version.

**Comment by frankgreco** [comment]
Of course.. should have started with this. 

After upgrading to v1.5.3. I was apply to successfully create the TPR and create the custom object with `kubectl create`.

 I'll just remember to use create for versions < 1.6 and apply >= 1.6

**Comment by frankgreco** [comment]
Sorry to close/reopen but I just remembered that this is still an issue when creating this via the kubernetes dashboard. It just try to do an apply.

**Comment by liggitt** [comment]
kube dashboard issues can be reported at https://github.com/kubernetes/dashboard
