### ISSUE TITLE
Pod volume/cgroup cleanup logic is faulty

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#42776]
Both cleanup rely on the periodic `syncBatch` in the status manger to trigger the final pod deletion. This is specifically checked in [`if m.needsUpdate(syncedUID, status) || m.couldBeDeleted(uid, status.status) `](https://github.com/kubernetes/kubernetes/blob/v1.7.0-alpha.0/pkg/kubelet/status/status_manager.go#L396
). 

However, `syncBatch` calls `syncPod`, which checks [`if !m.needsUpdate(uid, status)`](https://github.com/kubernetes/kubernetes/blob/v1.7.0-alpha.0/pkg/kubelet/status/status_manager.go#L417), and skip if it's true at the beginning of the function. This means that it will never trigger the final deletion request (unless something else triggers it).

This causes pod deletion to take > 1 minute in many cases, hence a bunch of test flake. 

Ideally, kubelet should not rely on the periodic `syncBatch` to send out deletion request, but at the least, this buggy logic should be fixed.

/cc @kubernetes/sig-node-bugs @dchen1107 @Random-Liu

**Comment by yujuhong** [comment]
There are a lot of fail-safe mechanisms in kubelet for handling pod deletion, therefore the pod was eventually deleted. These mechanisms are not to be relied on for normal pod cleanup. We should have a dedicated pod deletion test to catch a serious regression like this.

**Comment by dashpole** [comment]
Yep, I was seeing this earlier today as well, but didnt have time to fix it.  I am hoping to introduce metrics #42673 and test them with the density test to help uncover regressions in the future.  Agreed that we shouldnt rely on fail-safe mechanisms in the kubelet.

**Comment by dchen1107** [comment]
pr #42779 was merged. Close this one for now.
