### ISSUE TITLE
kubectl should suggest using newer options

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#42787]
This comes from discussion here: https://github.com/kubernetes/kubernetes/pull/42362#issuecomment-285175701. Generally we would like to be able to suggest a user a new functionality is available eg. newer generator for deployments (like in the linked issue) and he should pick if he wants to use new or stay with the old choice. That choice should be recorder not to bother user with the same question next time. Although I imagine having 3 options: yes, no, ask next time.

@kubernetes/sig-cli-feature-requests wdyt
@janetkuo fyi, since this came from you

**Comment by bgrant0607** [comment]
Preferences would be a big win IMO: #10693
