### ISSUE TITLE
PV cannot be deleted if attachable PVC is deleted

### ISSUE THREAD

**Issue by keyingliu** [kubernetes/kubernetes#42784]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.4.5

**Environment**:
- **Cloud provider or hardware configuration**: OpenStack
- **OS** (e.g. from /etc/os-release): Fedora
- **Kernel** (e.g. `uname -a`): 4.5.7
- **Install tools**:
- **Others**: storage backend is cinder

**What happened**:
We found many error logs in controller manger, said `Delete of volume xxx failed`, the PV is in Failed status, and the PV is bound to a PVC that has been deleted. The volume is supposed to be detached when volume unmount is done by attach-detach controller. It seems attach-detach controller lost the event, it causes the PV cannot be deleted because the volume is still in-use (not detached).
It happened often if controller manager leader is switched often

**What you expected to happen**:
We should have a consistent result, if PVC is not detached the PVC object should not deleted.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by xsgordon** [comment]
/cc @k8s-sig-openstack-bugs 

@idvoretskyi can you add the sig/openstack label please, I think this is a known issue though and we just need to link with the other issues/PRs.

**Comment by NickrenREN** [comment]
@keyingliu  Can you provide more logs about PVController and attach-detach controller.
Codes indicate that volume will not be marked as Failed if err is deletedVolumeInUseError:

if vol.IsDeletedVolumeInUse(err) {
			// The plugin needs more time, don't mark the volume as Failed
			// and send Normal event only
			ctrl.eventRecorder.Event(volume, v1.EventTypeNormal, "VolumeDelete", err.Error())
		} else {
			// The plugin failed, mark the volume as Failed and send Warning
			// event
			if _, err := ctrl.updateVolumePhaseWithEvent(volume, v1.VolumeFailed, v1.EventTypeWarning, "VolumeFailedDelete", err.Error()); err != nil {
				glog.V(4).Infof("deleteVolumeOperation [%s]: failed to mark volume as failed: %v", volume.Name, err)
				// Save failed, retry on the next deletion attempt
				return err
			}
		}
