### ISSUE TITLE
kube-dns does not exist. Failed to create kubernetes client

### ISSUE THREAD

**Issue by punkracy** [kubernetes/kubernetes#42785]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

I have similar issue as here:
https://github.com/kubernetes/kubernetes/issues/31910

---
**Kubernetes version** (use `kubectl version`):
`
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"87d9d8d7bc5aa35041a8ddfe3d4b367381112f89", GitTreeState:"clean", BuildDate:"2017-01-23T14:15:25Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"87d9d8d7bc5aa35041a8ddfe3d4b367381112f89", GitTreeState:"clean", BuildDate:"2017-01-23T14:15:25Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
`

**Environment**:
- **Cloud provider or hardware configuration**:
VPS
- **OS** (e.g. from /etc/os-release):
CentOS 7
- **Kernel** (e.g. `uname -a`):
Linux 3.10.0-514.10.2.el7.x86_64
- **Install tools**:
Installed according to
https://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/
- **Others**:
Tried to add dns addon using this:
https://coreos.com/kubernetes/docs/latest/deploy-addons.html
with: DNS_SERVICE_IP = 10.254.0.10

**What happened**:

I installed Kubernetes using official manual:
https://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/
one master, one minion. That went fast and easy. Checked if I have kube dns running:

`
kubectl get pods --namespace=kube-system
`

was empty

After trying add dns addon using following template:
https://coreos.com/kubernetes/docs/latest/deploy-addons.html

I get

`
kubectl get pods --namespace=kube-system
NAME                 READY     STATUS             RESTARTS   AGE
kube-dns-v20-u2kra   1/3       CrashLoopBackOff   508        19h
`

`
kubectl logs kube-dns-v20-u2kra kubedns --namespace=kube-system
F0309 08:20:31.346648       1 server.go:55] Failed to create a kubernetes client: invalid configuration: no configuration has been provided
`

**What you expected to happen**:
KubeDNS should run and be available. Now I am not able to communicate pods between each other using their names.

**How to reproduce it** (as minimally and precisely as possible):
Install k8s on Centos7 using this document:
https://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/

**Anything else we need to know**:

I was able to configure k8s using same doc on Centos7 with kubernetes 1.3 (few weeks before) with firewalld and SELinux running, but without dns as well. I thought that maybe firewalld and SELinux may cause some issues with that so decided to go exactly as documentation states.

**Comment by hoanhdo** [comment]
Hi.
You can try edit yaml file: add --kube-master-url to section args in container kubedns
Example

> - name: kubedns
        image: gcr.io/google_containers/kubedns-amd64:1.8
        resources:
          # TODO: Set memory limits when we've profiled the container for large
          # clusters, then set request = limit to keep this container in
          # guaranteed class. Currently, this container falls into the
          # "burstable" category so the kubelet doesn't backoff from restarting it.
          limits:
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 35Mi
        args:
        # command = "/kube-dns"
        - --domain=cluster.local.
        - --dns-port=10053
        - --kube-master-url=http://172.16.86.162:8080

**Comment by punkracy** [comment]
@hoanhdo thanks that helped to start kube-dns. But still environment does not work as it supposed. Have similar issues as here:
https://github.com/kubernetes/kubernetes/issues/16836

```
kubectl logs kube-dns-v20-rze57 kubedns --namespace=kube-system

I0311 10:27:33.567769       1 server.go:94] Using http://10.10.10.14:8080 for kubernetes master, kubernetes API: v1
I0311 10:27:33.569579       1 server.go:99] v1.5.0-alpha.0.1651+7dcae5edd84f06-dirty
I0311 10:27:33.569596       1 server.go:101] FLAG: --alsologtostderr="false"
I0311 10:27:33.569611       1 server.go:101] FLAG: --dns-port="10053"
I0311 10:27:33.569617       1 server.go:101] FLAG: --domain="cluster.local."
I0311 10:27:33.569621       1 server.go:101] FLAG: --federations=""
I0311 10:27:33.569626       1 server.go:101] FLAG: --healthz-port="8081"
I0311 10:27:33.569629       1 server.go:101] FLAG: --kube-master-url="http://10.10.10.14:8080"
I0311 10:27:33.569634       1 server.go:101] FLAG: --kubecfg-file=""
I0311 10:27:33.569638       1 server.go:101] FLAG: --log-backtrace-at=":0"
I0311 10:27:33.569644       1 server.go:101] FLAG: --log-dir=""
I0311 10:27:33.569648       1 server.go:101] FLAG: --log-flush-frequency="5s"
I0311 10:27:33.569653       1 server.go:101] FLAG: --logtostderr="true"
I0311 10:27:33.569657       1 server.go:101] FLAG: --stderrthreshold="2"
I0311 10:27:33.569661       1 server.go:101] FLAG: --v="0"
I0311 10:27:33.569664       1 server.go:101] FLAG: --version="false"
I0311 10:27:33.569669       1 server.go:101] FLAG: --vmodule=""
I0311 10:27:33.569711       1 server.go:138] Starting SkyDNS server. Listening on port:10053
I0311 10:27:33.569769       1 server.go:145] skydns: metrics enabled on : /metrics:
I0311 10:27:33.569786       1 dns.go:166] Waiting for service: default/kubernetes
I0311 10:27:33.570319       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0311 10:27:33.570330       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0311 10:27:33.577977       1 server.go:107] Setting up Healthz Handler(/readiness, /cache) on port :8081
W0321 07:23:08.263427       1 reflector.go:330] pkg/dns/dns.go:155: watch of *api.Service ended with: too old resource version: 344626 (1281236)
E0321 07:23:08.404841       1 reflector.go:311] pkg/dns/dns.go:154: Failed to watch *api.Endpoints: Get http://10.10.10.14:8080/api/v1/watch/endpoints?resourceVersion=1281239&timeoutSeconds=452: dial tcp 10.10.10.14:8080: getsockopt: connection refused

```

and

```
kubectl exec -ti busybox -- nslookup kubernetes.default
Server:    8.8.8.8
Address 1: 8.8.8.8 google-public-dns-a.google.com

nslookup: can't resolve 'kubernetes.default'
```

ifconfig

```
kubectl exec -ti busybox -- ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:1E:54:02  
          inet addr:172.30.84.2  Bcast:0.0.0.0  Mask:255.255.255.0

```

resolv (here we have a problem I guess) 

```
kubectl exec -ti busybox -- cat /etc/resolv.conf
search local test.services.domain.intra
nameserver 8.8.8.8
nameserver 8.8.4.4
options ndots:5

```

But if I change manually resolv

```
kubectl --namespace=kube-system exec -ti kube-dns-v20-rze57 -c kubedns nslookup kubernetes.default.svc.cluster.local localhost
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      kubernetes.default.svc.cluster.local
Address 1: 10.254.0.1 kubernetes.default.svc.cluster.local`

I have setup in dns-addon   clusterIP: ${DNS_SERVICE_IP}
to 10.254.0.10

```

```
kubectl --namespace=kube-system exec -ti kube-dns-v20-rze57 -c kubedns cat /etc/resolv.conf
nameserver 10.254.0.10
options ndots:5

```

So how to make it work?

**Comment by punkracy** [comment]
After reading more regarding issue I found:
https://github.com/kubernetes/kubernetes/issues/17406#issuecomment-226014284
and
http://stackoverflow.com/questions/37949471/kubernetes-kubelet-says-that-dns-is-not-set-with-missingclusterdns-skydns

I added to kubelet config file

```
# Add your own!
KUBELET_ARGS="--cluster-dns=10.254.0.10 --cluster-domain=cluster.local"
```

and now

```
kubectl exec busybox -- nslookup busybox
Server:    10.254.0.10
Address 1: 10.254.0.10 kube-dns.kube-system.svc.cluster.local

Name:      busybox
Address 1: 172.30.84.2 busybox

```

It is a pity that there is no corresponding manual for this topic for CentOS.
