### ISSUE TITLE
should PodTemplatesGetter be part of public API

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#42789]
It shows up in the [docs](https://godoc.org/k8s.io/client-go/kubernetes/typed/core/v1#PodTemplatesGetter), and actually I can even do `kubectl get podtemplates`, but it returns nothing. Haven't tried creating one... Is this some kind of placeholder for named pod templates?

**Comment by errordeveloper** [comment]
@sttts and I found https://github.com/kubernetes/kubernetes/pull/5012 and https://github.com/kubernetes/kubernetes/issues/170, yet this makes documentation a bit confusing, perhaps we should [unexport it](https://github.com/kubernetes/kubernetes/blob/fc8a37ec86e3a9139882cb4eeecdafc1c0d2d2dd/pkg/api/types.go#L2203-L2203) until it is ready or at least update docs to say it's not really something that one can user right now? ...unless there is a way of using it already?

**Comment by errordeveloper** [comment]
cc @smarterclayton

**Comment by kargakis** [comment]
Assuming we will use PodTemplates for DS/SS history, this should happen eventually.

**Comment by hpejustin** [comment]
BTW, there is a proposal of Template(not pod template), which try to manage topological relations of applications, did it implemented in v1.6? I did not see it yet.

**Comment by smarterclayton** [comment]
The objects exist and can be used.  We don't really have a position on it today.

**Comment by errordeveloper** [comment]
Closing, as it's inconclusive.
