### ISSUE TITLE
kubeadm join  Endpoint check failed  

### ISSUE THREAD

**Issue by jicki** [kubernetes/kubernetes#42791]
[discovery] Created cluster info discovery client, requesting info from "http://10.6.0.52:9898/cluster-info/v1/?token-id=dd3dac"
[discovery] Cluster info object received, verifying signature using given token
[discovery] Cluster info signature and contents are valid, will use API endpoints [https://10.6.0.52:6443]
[bootstrap] Trying to connect to endpoint https://10.6.0.52:6443
[bootstrap] Endpoint check failed [failed to connect to "https://10.6.0.52:6443" [Get https://10.6.0.52:6443/version: x509: certificate has expired or is not yet valid]]
[bootstrap] Trying to connect to endpoint https://10.6.0.52:6443
[bootstrap] Endpoint check failed [failed to connect to "https://10.6.0.52:6443" [Get https://10.6.0.52:6443/version: x509: certificate has expired or is not yet valid]]
[bootstrap] Trying to connect to endpoint https://10.6.0.52:6443
[bootstrap] Endpoint check failed [failed to connect to "https://10.6.0.52:6443" [Get https://10.6.0.52:6443/version: x509: certificate has expired or is not yet valid]]
[bootstrap] Trying to connect to endpoint https://10.6.0.52:6443
[bootstrap] Endpoint check failed [failed to connect to "https://10.6.0.52:6443" [Get https://10.6.0.52:6443/version: x509: certificate has expired or is not yet valid]]
[bootstrap] Trying to connect to endpoint https://10.6.0.52:6443
[bootstrap] Endpoint check failed [failed to connect to "https://10.6.0.52:6443" [Get https://10.6.0.52:6443/version: x509: certificate has expired or is not yet valid]]
[bootstrap] Trying to connect to endpoint https://10.6.0.52:6443
[bootstrap] Endpoint check failed [failed to connect to "https://10.6.0.52:6443" [Get https://10.6.0.52:6443/version: x509: certificate has expired or is not yet valid]]
[bootstrap] Trying to connect to endpoint https://10.6.0.52:6443
[bootstrap] Endpoint check failed [failed to connect to "https://10.6.0.52:6443" [Get https://10.6.0.52:6443/version: x509: certificate has expired or is not yet valid]]

version: 

kubeadm-1.6.0-0.alpha

init  version 1.5.3

node-1  msater 

node-2  join   successfully

node-3 join    successfully

node-4 join  failed

**Comment by erikbgithub** [comment]
having the same issue. Some guidance about how to debug would be nice. That kind of stuff can't even be easily debugged with curl.

**Comment by titanlien** [comment]
I meet the same issue, my solution is using "".
e.g
$ kubeadm join --token="[YOUR TOKEN]" [IP]

**Comment by sfloresk** [comment]
Did you check your NTP settings? The time must be in sync within the cluster. 
If you are not running NTP, install ntpd or chrony and once you have your time synchronized do "kubeadm init" (after "kubeadm reset" if you already have executed that command) to recreate the certs.

**Comment by luxas** [comment]
Agree with @sfloresk, that's probably the issue.

@jicki If that doesn't fix your problem, reopen the issue in the kubeadm repo: https://github.com/kubernetes/kubeadm/issues

**Comment by firmboy** [comment]
@sfloresk Solved my problem
