### ISSUE TITLE
ACS Windows Agents, Services connection lost

### ISSUE THREAD

**Issue by arnouthoebreckx** [kubernetes/kubernetes#42800]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`): 
Client version: 1.5, platform: Windows/amd
Server version 1.5

**Environment**:
- **Cloud provider or hardware configuration**: Azure ACS
- **OS** (e.g. from /etc/os-release): Windows Agents (Windows Server 2016)

**What happened**:
I've noticed that sometimes when I create a new service for a deployment that the LoadBalancer public IP won't reach the server, this is however resolved by rebooting the agents.
When this happens this happens for all my deployments and at the moment only rebooting the agents seems to resolve the issue.

**What you expected to happen**:
Start up service connects to containers without agent reboot

**How to reproduce it** (as minimally and precisely as possible):
Haven't really found a way to reproduce it, it only happened to me twice. First time I think because I created several services linked to the same deployment which might have caused an issue.

Second time was just after I came into work and try start up some test deployments and just didn't work. Since this is just a simple test-environment it doesn't impact anything but I can assume this issue could have a bigger impact on production environments

I personally think that it mostly happens if I expose the same image twice on the same ports. But over different deployments.
**Anything else we need to know**:

- Both agents are Standard_A1_V2 sizes
 - I've created the service from:
   - a yaml file
   - through kubectl expose deployment <-deployment-> ...

Found a very similar issue #42151

**Comment by feiskyer** [comment]
@arnouthoebreckx Did you still encounter the problem? 

> Server version 1.5

Are you deploying a cluster below v1.5.3 version? If so, please upgrade and retry again.

**Comment by jdumars** [comment]
Closing, due to staleness.  Original reporter, feel free to open if this is still happening.
