### ISSUE TITLE
[Federation][e2e] CI tests malform kube-dns federations domain map entry

### ISSUE THREAD

**Issue by csbell** [kubernetes/kubernetes#42809]
Looking at our latest e2e CI [failures](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-federation/2194), they appear to be due to the fact that the "federations value" for kube-dns install a domain with a trailing dot. The trailing period does **not** appear when I bring up the cluster manually with

```
FEDERATIONS_DOMAIN_MAP="e2e-federation=csbell.test-f8n.k8s.io" FEDERATION_DNS_ZONE_NAME="csbell.test-f8n.k8s.io" federation/cluster/federation-up.sh
```

I suspect that somewhere we are reconstructing a FEDERATIONS_DOMAIN_MAP when it is unset and a trailing period gets added there.

```
I0309 05:47:18.123] E0309 13:46:36.944302       1 sync.go:153] Invalid federations value: "test-f8n.k8s.io." not a valid domain name: ["must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)* (e.g. 'example.com')"] (value was "e2e-federation=test-f8n.k8s.io.")
I0309 05:47:18.123] E0309 13:46:36.944340       1 sync.go:134] Invalid configuration for federations, ignoring update: "test-f8n.k8s.io." not a valid domain name: ["must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)* (e.g. 'example.com')"]
```

**Comment by ethernetdan** [comment]
@csbell is this blocking for 1.6?

**Comment by csbell** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/42762
