### ISSUE TITLE
1.6 upgrade testing - [k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality should handle healthy pet restarts during scale

### ISSUE THREAD

**Issue by skriss** [kubernetes/kubernetes#42826]
@derekwaynecarr 

The following test is failing during some of the upgrade tests:

[k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality should handle healthy pet restarts during scale

"StatefulSet pet scaled unexpectedly scaled to 1 -> 2 replicas"

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1.5-container_vm-1.6-upgrade-master/22#k8sio-statefulset-k8sio-basic-statefulset-functionality-should-handle-healthy-pet-restarts-during-scale

This test job is creating a 1.5 cluster, upgrading the master to 1.6, and then running the 1.5 tests to ensure compatibility.

Can you take a look and see if this is an issue for the 1.6 release? Thanks.

**Comment by skriss** [comment]
@derekwaynecarr ping on this

**Comment by kow3ns** [comment]
known flake in 1.5 e2e test side fixed in 1.6 e2e #42367 and  #42429
