### ISSUE TITLE
1.6 upgrade testing - [k8s.io] Kubectl client [k8s.io] Kubectl apply should apply a new configuration to an existing RC

### ISSUE THREAD

**Issue by skriss** [kubernetes/kubernetes#42834]
@pwittrock 

This test is failing in 1.6 upgrade testing. 

The ReplicationController "redis-master" is invalid: spec.template.spec.containers[0].imagePullPolicy: Required value

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.5-gci-1.6-upgrade-master/19#k8sio-kubectl-client-k8sio-kubectl-apply-should-apply-a-new-configuration-to-an-existing-rc

This test is creating a 1.5 cluster, upgrading the master to 1.6, and then running 1.5 E2E tests to ensure compatibility.

Please take a look and determine if this is an issue for 1.6 release. Thanks!

**Comment by liggitt** [comment]
client-side validation strikes again :(

**Comment by skriss** [comment]
@pwittrock ping on this

**Comment by liggitt** [comment]
actually, I think this is likely a dupe of https://github.com/kubernetes/kubernetes/issues/42764

**Comment by liggitt** [comment]
should be fixed by #42944
