### ISSUE TITLE
[Federation] should not delete kube-dns configmap when cluster unjoin

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/kubernetes#42836]
kube-dns configmap should not be deleted as it may impact the functioning of kubedns. Here is recent pr which fix a issue around kube-dns configmap #42757.

In federation, when we unjoin a cluster, we are deleting the kube-dns configmap, which may impact dns functions. here is the link to [kubefed unjoin deleting kube-dns](https://github.com/kubernetes/kubernetes/blob/master/federation/pkg/kubefed/unjoin.go#L195)

cc @madhusudancs, @irfanurrehman @csbell @bowei @kubernetes/sig-federation-bugs

**Comment by madhusudancs** [comment]
Ack. Please send a fix for it. We were removing the ConfigMap because `Federations` was the only supported value. And cleaning it up when the artifact was created by us made sense. Things have changed now, so this needs a fix.
