### ISSUE TITLE
StatefulSet using SSD storage class does not allocate SSD disk

### ISSUE THREAD

**Issue by theothermike** [kubernetes/kubernetes#42844]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): statefulset ssd

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): gci
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**: I am creating a StatefulSet that has a VolumeClaimTemplate that uses a StorageClass which is specified as SSD.  When I check the Disk Type of the dynamically allocated disk in the Disk section of Google Cloud, it shows it as a 'Standard Persistent Disk' rather than 'SSD Persistent Disk'

here is the YAML:

kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd

and for the StatefulSet (modified as example)

File Edit Options Buffers Tools Help
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: example
spec:
  serviceName: "example"
  replicas: 1
  template:
    metadata:
      labels:
        app: example
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      nodeSelector:
        label: example
      terminationGracePeriodSeconds: 10
      containers:
      - name: example
        image: postgres-9.4
        command:
          - "/bin/bash"
          - "-ec"
          - |
            sleep 87600
        volumeMounts:
        - mountPath: /data
          name: data
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: ssd
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

**What you expected to happen**:  For the allocated disk to be an actual SSD

**How to reproduce it** (as minimally and precisely as possible):  create the StorageClass and StatefulSet and inspect the disk type

**Anything else we need to know**:

**Comment by wongma7** [comment]
this is because your statefulset claim template has the alpha annotation "volume.alpha.kubernetes.io/storage-class: ssd" which ignores storage class params and uses some default. Switch to beta and it should work

**Comment by theothermike** [comment]
I am testing this now, will report back shortly

**Comment by theothermike** [comment]
Confirmed, works with the 'beta' notation.  Closing

**Comment by bw2** [comment]
I'm still seeing this issue with 'beta' notation:
```
  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "ssd"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Gi
```

When I deploy it, the pod fails to provision the disk:
```
kubectl describe pods es-data-0
Name:		es-data-0
Namespace:	default
Node:		<none>
Labels:		component=elasticsearch
		deployment=gcloud-dev
		name=es-data
		role=data
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"StatefulSet","namespace":"default","name":"es-data","uid":"0ffe4b30-85d7-11e7-b236-42010a800050","apiVersi...
		kubernetes.io/limit-ranger=LimitRanger plugin set: cpu request for container es-data; cpu request for init container init-sysctl
		pod.beta.kubernetes.io/hostname=es-data-0
		pod.beta.kubernetes.io/subdomain=elasticsearch-data
Status:		Pending
IP:
Created By:	StatefulSet/es-data
Controlled By:	StatefulSet/es-data
Init Containers:
  init-sysctl:
    Image:	busybox
    Port:	<none>
    Command:
      sysctl
      -w
      vm.max_map_count=262144
    Requests:
      cpu:		100m
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-mgtm2 (ro)
Containers:
  es-data:
    Image:	quay.io/pires/docker-elasticsearch-kubernetes:5.5.1
    Port:	9300/TCP
    Requests:
      cpu:	100m
    Environment:
      NAMESPACE:		default (v1:metadata.namespace)
      NODE_NAME:		es-data-0 (v1:metadata.name)
      CLUSTER_NAME:		myesdb
      NODE_MASTER:		false
      NODE_INGEST:		false
      HTTP_ENABLE:		true
      ES_JAVA_OPTS:		-Xms2g -Xmx2g
      ES_PLUGINS_INSTALL:	mapper-size
    Mounts:
      /data from storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-mgtm2 (ro)
Conditions:
  Type		Status
  PodScheduled 	False
Volumes:
  storage:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	storage-es-data-0
    ReadOnly:	false
  default-token-mgtm2:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-mgtm2
    Optional:	false
QoS Class:	Burstable
Node-Selectors:	<none>
Tolerations:	node.alpha.kubernetes.io/notReady:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  1m		36s		3	default-scheduler			Warning		FailedScheduling	[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "storage-es-data-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "storage-es-data-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "storage-es-data-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "storage-es-data-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "storage-es-data-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "storage-es-data-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "storage-es-data-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "storage-es-data-0", which is unexpected.]
```

**Comment by bw2** [comment]
strange.  "standard" storage is now not working also.
