### ISSUE TITLE
swagger.json is missing from API discovery

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes#42841]
OpenAPI v2.0 spec is server on the root of the API server as swagger.json. However this file is missing from the API discovery result. Also the file is not versioned. I propose to add version to the path, e.g. $APISERVER/spec.v2/swagger.json, $APISERVER/spec.v3/openapi.json, etc.

ref: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-sig-api-machinery/3Zsf1eALhDw/-yYLu4vxAwAJ

cc: @bgrant0607 @nikhiljindal @smarterclayton

**Comment by smarterclayton** [comment]
How would the aggregator expose these? @deads2k

**Comment by deads2k** [comment]
@mbohlool Can an openapi spec point to another spec?  That way we could expose a simple unioned root one and have it delegate to the actual API servers for the rest.

**Comment by mbohlool** [comment]
@deads2k short answer is no. The aggregator should request spec from all servers and combine them. There are ways to reference a single model or parameter to an external yaml/json file, but not for the whole spec.

**Comment by deads2k** [comment]
> @deads2k short answer is no. The aggregator should request spec from all servers and combine them. There are ways to reference a single model or parameter to an external yaml/json file, but not for the whole spec.

You don't always include all APIs from a server.  How will you remove the undesired ones?

**Comment by mbohlool** [comment]
@deads2k I am not sure what you mean. the server should provide a spec of APIs that it supports and callable from aggregator.

**Comment by deads2k** [comment]
> @deads2k I am not sure what you mean. the server should provide a spec of APIs that it supports and callable from aggregator.

Say I create server foo and want to support running `kubectl auth can-i`.  This is easy to do today, but means that I expose `authorization.k8s.io`.  This is reasonable because a person working against this server may to use those delegation APIs.  However, when I aggregate the API server, I can choose to only expose groupVersion foo.  Otherwise, `authorization.k8s.io` would conflict with the "real" one.

How are you going to remove the "authorization.k8s.io" from swagger spec provided by server foo?

**Comment by mbohlool** [comment]
Who knows which group-version is exposed? I assume aggregator server knows about group-version it delegate to the other server, right?

**Comment by mbohlool** [comment]
Discussion about aggregation can be continued in #43717. Keeping this issue for API discovery problem.
