### ISSUE TITLE
`kubectl config set-cluster` returns 0 on error

### ISSUE THREAD

**Issue by alexey-medvedchikov** [kubernetes/kubernetes#42852]
**Kubernetes version**:
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:16:27Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- Pod on K8S inside AWS EC2
- (container) Debian GNU/Linux 8 (jessie) amd64 (bare) CentOS Linux 7 (Core)
- Linux shell-1313057207-0uwqj 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 GNU/Linux

**What happened**:
Call to `kubectl config set-cluster` with wrong args shows usage help and return exit code 0

**What you expected to happen**:
command shows usage help and returns exit code != 0

**How to reproduce it** (as minimally and precisely as possible):

```
kubectl run -t -i shell --rm --image=quay.io/gravitational/sync-kubeconfig:0.0.3 --command -- /bin/bash
inside pod> kubectl config set-cluster cluster-default --server https://127.0.0.1:6443 --certificate-authority /var/run/secrets/kubernetes.io/serviceaccount/ca.crt --embed-certs true --kubeconfig /tmp/kubeconfig
```

**Comment by shiywang** [comment]
will open a pr to address that, I think current return value is bool instead of an error handle by `cmdutil.CheckErr`
