### ISSUE TITLE
CRI: PodSandbox may be garbage collected early before it is ready

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#42856]
Forked from https://github.com/kubernetes/kubernetes/issues/42736#issuecomment-285268573. 

Currently, kuberuntime garbage collection can't distinguish just-created sandboxes from failed sandboxes. Especially when the time from sandbox creation to ready is longer than GC's minAge. In such cases, those sandboxes may be garbage collected early before they are ready.

Some ideas of solving this problem:

- runtime (e.g. dockershim) filter out those created-but-not-ready sandboxes from sandbox list
- introduce another sandbox state CREATED in CRI

cc @yujuhong @kubernetes/sig-node-bugs

**Comment by yujuhong** [comment]
> introduce another sandbox state CREATED in CRI

This would still cause problems. If a sandbox stays in the created state forever (e.g., couldn't be started), kubelet will never be able to GC it.

/cc @Random-Liu

**Comment by feiskyer** [comment]
> This would still cause problems. If a sandbox stays in the created state forever (e.g., couldn't be started), kubelet will never be able to GC it.

A detailed process about this idea is

* Split `RunSandbox` into `CreateSandbox` and `StartSandbox`
* Introduce a `SandboxCreated` state of sandbox and runtime should ensure
  * the sandbox is in `SandboxCreated` state after `CreateSandbox` successfully
  * the sandbox is in `SandboxReady` state after `StartSandbox` successfully
  * the sandbox is in `SandboxNotReady` state if `StartSandbox` failed (e.g. exit code is not zero)

**Comment by Random-Liu** [comment]
Can we also always keep the latest pod sandbox? Just like what we do for containers?

**Comment by feiskyer** [comment]
> Can we also always keep the latest pod sandbox? Just like what we do for containers?

SGTM. I think it's a simplest way that what I proposed. 

Filed #43053 for this way.
