### ISSUE TITLE
FailedMount event can be misleading

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#42867]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
FailedMount

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): 
Bug

**Kubernetes version** (use `kubectl version`):
1.4.8

**Environment**:
- **Cloud provider or hardware configuration**: GKE, GCE
- **OS** (e.g. from /etc/os-release): GCI

**What happened**:
The FailedMount event can be misleading to users because it's not clear if the mount eventually succeeded or still failed.  You would have to understand the internals of the system to correctly interpret the message, which is not user friendly.  In this case, the mount did succeed, but the user still sees this failure msg in the events.

```
Events:
  FirstSeen     LastSeen        Count   From                                            SubObjectPath                   Type            Reason          Message
  ---------     --------        -----   ----                                            -------------                   --------        ------          -------
  14m           14m             1       default-scheduler                                                               Normal          Scheduled       Successfully assigned up-test-201-2148660399-lcm4g to gke-repro-test-pool2-b818a09a-hknn
  14m           13m             2       controller-manager                                                              Warning         FailedMount     Failed to attach volume "pvc-fe4ab0cd-0533-11e7-bbce-42010a8000c9" on node "gke-repro-test-pool2-b818a09a-hknn" with: googleapi: Error 400: The disk resource 'gke-repro-test-31027de-pvc-fe4ab0cd-0533-11e7-bbce-42010a8000c9' is already being used by 'gke-repro-test-pool1-fb551a02-4m0n'

```
**What you expected to happen**:
A success event should be generated when a volume successfully attaches and mounts.  Care needs to be taken to make sure we don't flood the event log.  Maybe only have an event when the mount is successful, and not the attach.

**How to reproduce it** (as minimally and precisely as possible):
Create a deployment that uses a GCE PD volume, and move it to different nodes in order to cause the volume to need to be detached and attached to different nodes.

cc @kubernetes/sig-storage-bugs

**Comment by jeffvance** [comment]
@msau42 mount failures are a fairly common reason why some of the volume e2e tests fail. It has been useful to me to see the _FailedMount_ event in the target pod. In the case of ceph-rdb we get a useful error msg:
```
Mar  9 13:26:26.079: INFO: At 2017-03-09 13:19:29 -0800 PST - event for rbd-client: {kubelet jeffvance-e2e-minion-group-3tcz} FailedMount: MountVolume.SetUp failed for volume "kubernetes.io/rbd/1460bbfe-050e-11e7-abc9-42010af00002-rbd-volume-0" (spec.Name: "rbd-volume-0") pod "1460bbfe-050e-11e7-abc9-42010af00002" (UID: "1460bbfe-050e-11e7-abc9-42010af00002") with: rbd: image foo is locked by other nodes
```
but for other plugins, not so helpful:
```
FailedMount: MountVolume.SetUp failed for volume "kubernetes.io/glusterfs/da9e7f35-0510-11e7-abc9-42010af00002-gluster-volume-0" (spec.Name: "gluster-volume-0") pod "da9e7f35-0510-11e7-abc9-42010af00002" (UID: "da9e7f35-0510-11e7-abc9-42010af00002") with: glusterfs: mount failed: mount failed: exit status 1
```
If the mount eventually succeeds is it possible to annotate an earlier event record (not likely), or even know there was a previously recorded mount failure?

**Comment by msau42** [comment]
I'm not sure it's possible to modify an earlier event.  So I think in this case, it would just always trigger a successful mount event, regardless of if it had previously failed.

**Comment by msau42** [comment]
And to clarify, I intend to leave the failed events as is.  I just want to add a success event as well.

**Comment by jeffvance** [comment]
OK, that sounds good to me. Thanks for the clarification.
