### ISSUE TITLE
How to configure kube-system:kube-dns ConfigMap with nameserver and port

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/kubernetes#42868]
@bowei, Thanks for this pr #41826, its really useful.
Is there a way to configure port for the nameserver and how?

it would be really useful, if somebody wants to deploy dns-server in kubernetes as a NodePort service and there could be possibilities where cloud-provider may not be supporting LoadBalancer type service.

We do have a usecase in federation for federating clusters on non-cloud environments.

cc @kubernetes/sig-federation-misc

**Comment by shashidharatd** [comment]
raised this issue in https://github.com/kubernetes/dns repo

**Comment by zoidbergwill** [comment]
Relevant issue in that repo: https://github.com/kubernetes/dns/issues/68
