### ISSUE TITLE
About Godep version v79 or v74?

### ISSUE THREAD

**Issue by luomiao** [kubernetes/kubernetes#42871]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT?

**Kubernetes version** (use `kubectl version`):
1.6

**What happened**:
Current Godeps/Godeps.json file shows:
`"GodepVersion": "v79"`
However the hack/godep-save.sh script has one line: 
`kube::util::ensure_godep_version v74`

When I updated the vendor folder according to the guideline at:
https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md
Godeps/Godeps.json will have a bunch of changes due to the version difference.

Just wondering which version we really should use here?
Updating godep-save.sh, or reverting Godeps.json?

**Comment by cblecker** [comment]
This looks to be fixed on master:
https://github.com/kubernetes/kubernetes/blob/master/Godeps/Godeps.json#L4

**Comment by luomiao** [comment]
Thank you. Closed now.
