### ISSUE TITLE
common cluster component labeling

### ISSUE THREAD

**Issue by brancz** [kubernetes/kubernetes#42887]
To have some consistency in labeling of Kubernetes cluster components it would be good to have a formalized labeling scheme. I have come across this problem when building monitoring solutions that expect the labeling to be `k8s-app: <component-name>`. I adapted this or started the discussion around this in:

- bootkube: [here](https://github.com/kubernetes-incubator/bootkube/pull/230) and [here](https://github.com/kubernetes-incubator/bootkube/pull/179)
- kops: https://github.com/kubernetes/kops/issues/1226

And recently discovered that the rescheduler sort of expects this labeling in a cluster. [I commented](https://github.com/kubernetes/contrib/pull/2420#discussion_r103153127) about it on a rescheduler PR and was directed to open an issue here in this regard. I had it on my to do list until the discussion [came up today with kargo](https://github.com/coreos/kube-prometheus/issues/61#issuecomment-285656955).

So here it is.

I propose that there should be a formalized labeling for Kubernetes cluster component's `Pod` *and* `Service` objects.

Once formalized it is a common ground that we can stand on to make sure all cluster bootstrapping tools setup clusters with common labeling.

I generally don't care about what the actual labels are. But because the informal `k8s-app: <component-name>` is relatively common already, it may be a good candidate. To make sure that they actually are consistent it would be good to also have a list of what that actually means for `<component-name>`.

Thoughts? Something I missed?

If there is no general objection and this is something that is generally viewed as useful, then I'm happy to type up a proposal.

@kubernetes/sig-cluster-lifecycle-feature-requests @bgrant0607

**Comment by philips** [comment]
I think this is directly related to https://github.com/kubernetes/community/issues/300 and the discussion should probably move there or dependent on someone creating the registry. If you can take on the leg work of building the registry process I am happy to help @brancz!

And given the precedent set by node-role.kubernetes.io this should probably be something like: component.kubernetes.io=scheduler.
