### ISSUE TITLE
iSCSI volume is not unmounted when pod terminates

### ISSUE THREAD

**Issue by sykesm** [kubernetes/kubernetes#42889]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): iscsi umount

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

**Kubernetes version** (use `kubectl version`):
`Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.3-beta.0.2+270bbb6cb5f394-dirty", GitCommit:"270bbb6cb5f394be9ce1d82f8495092ad079ee3c", GitTreeState:"dirty", BuildDate:"2017-03-07T08:09:13Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}`

Built from v1.5.3 + cherry-pick of 695e5ddb246498545bc9b04f99ce6be849184b9c

**Environment**:
- **Cloud provider or hardware configuration**: VM running in SoftLayer under XEN. 2 vCPU, 4G RAM
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS (Xenial Xerus)
- **Kernel** (e.g. `uname -a`): `Linux stage-dal09-cr2918e7e7248c41b2a613b85d19fa8cf7-w1 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**:
- **Others**:

**What happened**:
Created two iSCSI PVs and associated claims. Created a pod with volumes that reference those claims.  Once the pod landed on a node, the volumes were mounted by the kubelet and made available to the pod.

When the pod was deleted, the iSCSI volumes were never unmounted and the sessions remained active.

**What you expected to happen**:
I expected the iSCSI volumes to be unmounted and the session to be logged out as the volumes were no longer in-use by the node.  Instead the mounts remained active and the sessions were not logged out.

**How to reproduce it** (as minimally and precisely as possible):
1. Run a containerized kubelet on a node with a properly configured iSCSI initiator.
2. Start a pod that uses PVCs which reference iSCSI PVs
3. Delete the pod and wait for termination.
4. Go to the node and observe that the volumes are still mounted.

**Anything else we need to know**:
We are running a containerized kubelet. The systemd service creates `/var/lib/kubelet`, bind mounts it to itself, and makes it rshared:
```
ExecStartPre=/bin/mkdir -p /var/lib/kubelet
ExecStartPre=/bin/sh -c "/bin/grep /var/lib/kubelet /etc/mtab || mount --bind /var/lib/kubelet /var/lib/kubelet"
ExecStartPre=/bin/mount --make-rshared /var/lib/kubelet
```
and docker run includes `-v /var/lib/kubelet:/var/lib/kubelet:rw,rshared`.

In this configuration, `/proc/mounts` appears to contain duplicate entries for everything under `/var/lib/kubelet`. This symptom has been referenced by issues #30258 and #32336.

Tracing the kubelet, the volume related commands appear to be:

```
execve("/sbin/iscsiadm", ["iscsiadm", "-m", "iface", "-I", "default", "-o", "show"], [/* 3 vars */]) = 0
execve("/sbin/iscsiadm", ["iscsiadm", "-m", "discovery", "-t", "sendtargets", "-p", "10.2.125.18:3260", "-I", "default"], [/* 3 vars */]) = 0
execve("/sbin/iscsiadm", ["iscsiadm", "-m", "node", "-p", "10.2.125.18:3260", "-T", "iqn.1992-08.com.netapp:stmdal0901", "-I", "default", "--login"], [/* 3 vars */]) = 0
execve("/sbin/fsck", ["fsck", "-a", "/dev/disk/by-path/ip-10.2.125.18:3260-iscsi-iqn.1992-08.com.netapp:stmdal0901-lun-174"], [/* 3 vars */]) = 0
execve("/sbin/fsck.ext4", ["fsck.ext4", "-a", "/dev/sdb"], [/* 3 vars */]) = 0
execve("/bin/mount", ["mount", "-o", "defaults", "/dev/disk/by-path/ip-10.2.125.18:3260-iscsi-iqn.1992-08.com.netapp:stmdal0901-lun-174", "/var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.18:3260-iqn.1992-08.com.netapp:stmdal0901-lun-174"], [/* 3 vars */]) = 0
execve("/bin/mount", ["mount", "-o", "bind", "/var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.18:3260-iqn.1992-08.com.netapp:stmdal0901-lun-174", "/var/lib/kubelet/pods/2144304c-04fa-11e7-a20a-e2672a8ee1ce/volumes/kubernetes.io~iscsi/pvc-61c505b2-044e-11e7-a20a-e2672a8ee1ce"], [/* 3 vars */]) = 0
execve("/bin/mount", ["mount", "-o", "remount", "/var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.18:3260-iqn.1992-08.com.netapp:stmdal0901-lun-174", "/var/lib/kubelet/pods/2144304c-04fa-11e7-a20a-e2672a8ee1ce/volumes/kubernetes.io~iscsi/pvc-61c505b2-044e-11e7-a20a-e2672a8ee1ce"], [/* 3 vars */] <unfinished ...>
execve("/bin/umount", ["umount", "/var/lib/kubelet/pods/2144304c-04fa-11e7-a20a-e2672a8ee1ce/volumes/kubernetes.io~iscsi/pvc-61c505b2-044e-11e7-a20a-e2672a8ee1ce"], [/* 3 vars */]) = 0
```
 and
```
execve("/sbin/iscsiadm", ["iscsiadm", "-m", "iface", "-I", "default", "-o", "show"], [/* 3 vars */]) = 0
execve("/sbin/iscsiadm", ["iscsiadm", "-m", "discovery", "-t", "sendtargets", "-p", "10.2.125.132:3260", "-I", "default"], [/* 3 vars */]) = 0
execve("/sbin/iscsiadm", ["iscsiadm", "-m", "node", "-p", "10.2.125.132:3260", "-T", "iqn.1992-08.com.netapp:stfdal0901", "-I", "default", "--login"], [/* 3 vars */]) = 0
execve("/sbin/fsck", ["fsck", "-a", "/dev/disk/by-path/ip-10.2.125.132:3260-iscsi-iqn.1992-08.com.netapp:stfdal0901-lun-161"], [/* 3 vars */]) = 0
execve("/sbin/fsck.ext4", ["fsck.ext4", "-a", "/dev/sda"], [/* 3 vars */]) = 0
execve("/bin/mount", ["mount", "-o", "defaults", "/dev/disk/by-path/ip-10.2.125.132:3260-iscsi-iqn.1992-08.com.netapp:stfdal0901-lun-161", "/var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.132:3260-iqn.1992-08.com.netapp:stfdal0901-lun-161"], [/* 3 vars */]) = 0
execve("/bin/mount", ["mount", "-o", "bind", "/var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.132:3260-iqn.1992-08.com.netapp:stfdal0901-lun-161", "/var/lib/kubelet/pods/2144304c-04fa-11e7-a20a-e2672a8ee1ce/volumes/kubernetes.io~iscsi/pvc-645cb865-044e-11e7-a20a-e2672a8ee1ce"], [/* 3 vars */]) = 0
execve("/bin/mount", ["mount", "-o", "remount", "/var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.132:3260-iqn.1992-08.com.netapp:stfdal0901-lun-161", "/var/lib/kubelet/pods/2144304c-04fa-11e7-a20a-e2672a8ee1ce/volumes/kubernetes.io~iscsi/pvc-645cb865-044e-11e7-a20a-e2672a8ee1ce"], [/* 3 vars */]) = 0
execve("/bin/umount", ["umount", "/var/lib/kubelet/pods/2144304c-04fa-11e7-a20a-e2672a8ee1ce/volumes/kubernetes.io~iscsi/pvc-645cb865-044e-11e7-a20a-e2672a8ee1ce"], [/* 3 vars */]) = 0
```

After the pod has terminated, `/proc/mounts` still contains the following:
```
/dev/sda /var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.132:3260-iqn.1992-08.com.netapp:stfdal0901-lun-161 ext4 rw,relatime,stripe=16,data=ordered 0 0
/dev/sda /var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.132:3260-iqn.1992-08.com.netapp:stfdal0901-lun-161 ext4 rw,relatime,stripe=16,data=ordered 0 0
/dev/sdb /var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.18:3260-iqn.1992-08.com.netapp:stmdal0901-lun-174 ext4 rw,relatime,stripe=16,data=ordered 0 0
/dev/sdb /var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.18:3260-iqn.1992-08.com.netapp:stmdal0901-lun-174 ext4 rw,relatime,stripe=16,data=ordered 0 0
```

Are the duplicate mount entries causing problems?
Is this behavior related to the use of `/dev/disk/by-path` device links in the mount code while the mount table contains `/dev/sdX` devices?

**Comment by sykesm** [comment]
Spent some time with @fraenkel on this today. We instrumented the code in [diskTearDown](https://github.com/kubernetes/kubernetes/blob/2d3008fc56f09c181565f9f27f3076270546de2a/pkg/volume/iscsi/disk_manager.go#L78) to dump the list of mount references that existed when `TearDownAt` was called.

What we saw was that there were 9 references to the volume:
```
diskTearDown: refs []string{
    "/rootfs/var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.18:3260-iqn.1992-08.com.netapp:stmdal0901-lun-174",
    "/rootfs/var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.18:3260-iqn.1992-08.com.netapp:stmdal0901-lun-174",
x   "/rootfs/var/lib/kubelet/pods/b3a2e7eb-080b-11e7-a20a-e2672a8ee1ce/volumes/kubernetes.io~iscsi/pvc-61c505b2-044e-11e7-a20a-e2672a8ee1ce"
x   "/rootfs/var/lib/kubelet/pods/b3a2e7eb-080b-11e7-a20a-e2672a8ee1ce/volumes/kubernetes.io~iscsi/pvc-61c505b2-044e-11e7-a20a-e2672a8ee1ce",
    "/var/lib/docker/aufs/mnt/75db7d702348f23dd158996be1d1ec421dfc1a5b0ff26e1d403173b879c6ac1a/rootfs/var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.18:3260-iqn.1992-08.com.netapp:stmdal0901-lun-174",
    "/var/lib/docker/aufs/mnt/75db7d702348f23dd158996be1d1ec421dfc1a5b0ff26e1d403173b879c6ac1a/rootfs/var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.18:3260-iqn.1992-08.com.netapp:stmdal0901-lun-174",
x   "/var/lib/docker/aufs/mnt/75db7d702348f23dd158996be1d1ec421dfc1a5b0ff26e1d403173b879c6ac1a/rootfs/var/lib/kubelet/pods/b3a2e7eb-080b-11e7-a20a-e2672a8ee1ce/volumes/kubernetes.io~iscsi/pvc-61c505b2-044e-11e7-a20a-e2672a8ee1ce",
x   "/var/lib/docker/aufs/mnt/75db7d702348f23dd158996be1d1ec421dfc1a5b0ff26e1d403173b879c6ac1a/rootfs/var/lib/kubelet/pods/b3a2e7eb-080b-11e7-a20a-e2672a8ee1ce/volumes/kubernetes.io~iscsi/pvc-61c505b2-044e-11e7-a20a-e2672a8ee1ce",
    "/var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.18:3260-iqn.1992-08.com.netapp:stmdal0901-lun-174",
}
```
It looks like the majority of these are due to how containerized kubelets work. In particular, the host root is mounted as `/rootfs` in the container which generates a set of entries in `/proc/mounts` that duplicate the mounts done in `/var/lib/kubelet`.

There are also duplicate entries that appear to be due to the `rshared` mount propagation that's been enabled on `/var/lib/kubelet`.

Then entries marked with an `x` were released when `/var/lib/kubelet/pods/b3a2e7eb-080b-11e7-a20a-e2672a8ee1ce/volumes/kubernetes.io~iscsi/pvc-61c505b2-044e-11e7-a20a-e2672a8ee1ce` is unmounted leaving the following behind:
```
/dev/sdb on /rootfs/var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.18:3260-iqn.1992-08.com.netapp:stmdal0901-lun-174 type ext4 (rw,relatime,stripe=16,data=ordered)
/dev/sdb on /rootfs/var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.18:3260-iqn.1992-08.com.netapp:stmdal0901-lun-174 type ext4 (rw,relatime,stripe=16,data=ordered)
/dev/sdb on /var/lib/docker/aufs/mnt/75db7d702348f23dd158996be1d1ec421dfc1a5b0ff26e1d403173b879c6ac1a/rootfs/var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.18:3260-iqn.1992-08.com.netapp:stmdal0901-lun-174 type ext4 (rw,relatime,stripe=16,data=ordered)
/dev/sdb on /var/lib/docker/aufs/mnt/75db7d702348f23dd158996be1d1ec421dfc1a5b0ff26e1d403173b879c6ac1a/rootfs/var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.18:3260-iqn.1992-08.com.netapp:stmdal0901-lun-174 type ext4 (rw,relatime,stripe=16,data=ordered)
/dev/sdb on /var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.18:3260-iqn.1992-08.com.netapp:stmdal0901-lun-174 type ext4 (rw,relatime,stripe=16,data=ordered)
```
The kubelet is launched with the following:
```
/usr/bin/docker
run
--name=kubelet
--privileged
--userns=host
--network=host
--pid=host
-v /:/rootfs:ro
-v /sys:/sys:ro
-v /dev:/dev
-v /var/run:/var/run
-v /var/lib/kubelet:/var/lib/kubelet:rw,rshared
-v /var/lib/docker:/var/lib/docker
-v /var/log/containers:/var/log/containers
-v /etc/kubernetes:/etc/kubernetes
-v /etc/cni/net.d:/etc/cni/net.d
-v /opt/cni/bin:/opt/cni/bin
-v /etc/iscsi:/etc/iscsi
-v /sbin/iscsiadm:/sbin/iscsiadm
sykesm/hyperkube-amd64:v1.5.3-2
/hyperkube
kubelet
--allow-privileged=true
--api-servers=https://169.55.35.104:28085
--cluster-dns=10.10.10.10
--cluster-domain=cluster.local
--config=/etc/kubernetes/manifests
--kubeconfig=/etc/kubernetes/kubelet-kubeconfig
--v=99
--file-check-frequency=5s
--hostname-override=generated-hostname
--network-plugin=cni
--network-plugin-dir=/etc/cni/net.d
``` 
You can see see the arg that does rshared mount propagation and the mount of `/` to `/rootfs`.

Given all that, it seems like the references that come back from `mount.GetMountRefs` (which, in turn gets the contents of `/proc/mounts`) should be filtered further.

First, to address the `rshared` mount propagation, it seems like duplicate entries should be removed. Second, it seems like the only refs that should be examined are those that are associated with pods and the volume plugins.

Applying that logic to the initial set of mounts, the refs would have been the single, expected entry:
```
 "/var/lib/kubelet/plugins/kubernetes.io/iscsi/10.2.125.18:3260-iqn.1992-08.com.netapp:stmdal0901-lun-174",
```

@kubernetes/sig-storage-bugs Any ideas or guidance?

**Comment by ncdc** [comment]
cc @sjenning who's been looking into this

**Comment by rdxmb** [comment]
Having this problem with nodes running `v1.20.5` on ubuntu 20.04. Pods stay "Terminating", when running `kubectl delete pod --force`, the new pod cannot start on another node, for the iSCSI-mount on the old node stays mounted. 

When running manual `umount` on the old node, the pods start running on the other node.
