### ISSUE TITLE
pvc create fails with rbd backed storage class latest ceph

### ISSUE THREAD

**Issue by liamkell** [kubernetes/kubernetes#42891]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
rbd pvc create 
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
v1.5.3

**Environment**:
- **Cloud provider or hardware configuration**: Hardware
- **OS** (e.g. from /etc/os-release): CoreOs 1298.5.0
- **Kernel** (e.g. `uname -a`): 4.9.9-coreos-r1
- **Install tools**:
- **Others**:

**What happened**:
After setting up a storage class with ceph as backend the create of a pvc failed.

This was with ceph kracken (11.2.0) same sequence works on earlier versions.

The error reported was
```
 FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  17s		3s		2	{persistentvolume-controller }			Warning		ProvisioningFailedFailed to provision volume with StorageClass "fast": invalid option "imageFormat" for volume plugin kubernetes.io/rbd
```
This is related to to the fact that the image format is hard coded in pkg/volume/rbd/rbd_util.go
cf. 

[]string{"create", p.rbdMounter.Image, "--size", volSz, "--pool", p.rbdMounter.Pool, "--id", p.rbdMounter.adminId, "-m", mon, "--key=" + p.rbdMounter.adminSecret, "--image-format", "1"})

with this version of ceph image-format of 1 ha been deprecated

I will look into a patch making the image format an optional attribute.  

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
Create a pvc via storage class with rbd volume plugin backed with ceph based on kracken or later.  

**Anything else we need to know**:

**Comment by drdeimos** [comment]
How you fix it?
