### ISSUE TITLE
node-e2e: Pod deletion tests to node perftest suite

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#42897]
Forked from: https://github.com/kubernetes/kubernetes/pull/42779#issuecomment-285425106

**Comment by dchen1107** [comment]
cc/ @kubernetes/sig-node-bugs  cc/ @dashpole

**Comment by dashpole** [comment]
Thanks Dawn, please assign me!

**Comment by yujuhong** [comment]
I don't think this is done. @dashpole feel free to remove your assignment if you're not working on it.
