### ISSUE TITLE
HTTPS fails within containers

### ISSUE THREAD

**Issue by vmarmol** [kubernetes/kubernetes#4290]
I've been trying to send a GET to an HTTPS endpoint in Kubernetes and it fails with the following error:

```
x509: failed to load system roots and no roots provided
```

Sample Go program that has this, along with its Docker file in this [gist](https://gist.github.com/vmarmol/2610a64f2777fb58dfe9).

This isn't just a Kubernetes issue, it happens on any Docker image. @kelseyhightower has a nice explanation [here](https://medium.com/@kelseyhightower/optimizing-docker-images-for-static-binaries-b5696e26eb07) near the bottom.

Do we have a general recipe for this? @kelseyhightower's example bundles the CAs, but I imagine that's not what we're gonna ask users to do since at the very least they're hard to update. I can imagine plumbing these CA files automatically for the users (unless they already provide one), but that may have some undesired side effects for a small minority of users.

Any thoughts?

**Comment by roberthbailey** [comment]
Kelsey's post says that it fails using the scratch image because that image doesn't have certs bundled. Since you are using the ubuntu image, it seems like you should have a valid certificate file in your container that can be used by your Go program. 

If you open a shell inside your container does /etc/ssl/certs/ca-certificates.crt exist?

**Comment by vmarmol** [comment]
Nope, even on the Ubuntu image it's not there (which one can argue is an omission on their part). It doesn't seem like this is something most images have.

```
vmarmol@m-o2:~/tmp/secure$ docker run -i -t ubuntu ls /etc/ssl
ls: cannot access /etc/ssl: No such file or directory
```

**Comment by dims** [comment]
@vmarmol @roberthbailey - Is there something thing we need to do in kubernetes for this scenario? If not can we close this out please?

**Comment by roberthbailey** [comment]
I'm ok closing this as long as @vmarmol isn't still seeing this issue.

**Comment by techtonik** [comment]
At least the error message should be improved with direction guidelines if upstream is unable to provide images with security certificates by default.
