### ISSUE TITLE
[k8s.io] Daemon set [Serial] Should adopt or recreate existing pods when creating a RollingUpdate DaemonSet with matching or mismatching templateGeneration {Kubernetes e2e suite}

### ISSUE THREAD

**Issue by marun** [kubernetes/kubernetes#42908]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial/772

Failed: [k8s.io] Daemon set [Serial] Should adopt or recreate existing pods when creating a RollingUpdate DaemonSet with matching or mismatching templateGeneration {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_set.go:391
error waiting for daemon pod template generation to be 1
Expected error:
    <*errors.errorString | 0xc420414ff0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_set.go:386
```

cc: @kubernetes/sig-apps-bugs @janetkuo

**Comment by janetkuo** [comment]
Can't reproduce it locally with either a local cluster or GCE cluster. In the failed tests, the last orphan-then-adopt step failed. Maybe it's caused by the race between garbage collector vs. DaemonSet controller ControllerRef adoption (#42639)?

**Comment by janetkuo** [comment]
In the controller manager log for the failed case, saw lots of message:
```
E0310 15:28:39.125452       5 daemoncontroller.go:233] e2e-tests-daemonsets-nt170/daemon-set-new-restart failed with : couldn't get node to daemon pod mapping for daemon set "daemon-set-new-restart": [User "system:serviceaccount:kube-system:daemon-set-controller" cannot patch pods in the namespace "e2e-tests-daemonsets-nt170". (patch pods daemon-set-m8rgk), User "system:serviceaccount:kube-system:daemon-set-controller" cannot patch pods in the namespace "e2e-tests-daemonsets-nt170". (patch pods daemon-set-63ktc), User "system:serviceaccount:kube-system:daemon-set-controller" cannot patch pods in the namespace "e2e-tests-daemonsets-nt170". (patch pods daemon-set-dj32n)]
```

This patch error comes from controller ref manager, which caused DaemonSet controller sync loop to fail.

**Comment by janetkuo** [comment]
Looking at API server log, daemonset controller doesn't have the permission to PATCH:

```
I0310 15:28:36.613242       5 wrap.go:75] PATCH /api/v1/namespaces/e2e-tests-daemonsets-nt170/pods/daemon-set-m8rgk: (680.149µs) 403 [[kube-controller-manager/v0.0.0 (linux/amd64) kubernetes/$Format/system:serviceaccount:kube-system:daemon-set-controller] [::1]:39362]
```

**Comment by caesarxuchao** [comment]
it's because rbac doesn't allow daemonset_controller to patch pod: https://github.com/liggitt/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go#L87

we had a similar issue before: https://github.com/kubernetes/kubernetes/pull/39961

@liggitt i think we need to find a generic way to test what permissions are need by our various controllers.

**Comment by janetkuo** [comment]
cc @enisoc

**Comment by janetkuo** [comment]
We'll need more e2e tests for ControllRef of each controller (deployment, RC, RS, ...), since we didn't catch this elsewhere. We also need some test for RBAC.
