### ISSUE TITLE
kubefed should allow admins to provide credentials to clusters

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#42907]
`kubefed` creates a service account and installs the right RBAC roles to allow access to the required API resources. However, not all the clusters have RBAC authorizer enabled. Therefore we should allow federation/cluster admins to supply their own credentials.

For details, see https://github.com/kubernetes/kubernetes/pull/41830#issuecomment-285378955 and https://github.com/kubernetes/kubernetes/pull/41830#issuecomment-285695300.

cc @liggitt @kubernetes/sig-federation-bugs @perotinus

**Comment by marun** [comment]
@madhusudancs Should this issue be blocking 1.7?

**Comment by madhusudancs** [comment]
@irfanurrehman you had an issue somewhere describing the details of this issue. I am unable to find it though. Can we close this one in favor of your issue that has more details?

**Comment by irfanurrehman** [comment]
@madhusudancs @marun, I think we can close this one in favour of https://github.com/kubernetes/kubernetes/issues/44384.
Also, this has been on a backburner from some time. 
Please, let me also know if this should be given priority.
