### ISSUE TITLE
Kubelet runonce mode doesn't support volumes

### ISSUE THREAD

**Issue by jiosec** [kubernetes/kubernetes#42909]
**Kubernetes version** (use `kubectl version`):
v.1.5.2

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): CoreOS 1235.9.0
- **Kernel** (e.g. `uname -a`): 4.7.3-coreos-r2

**What happened**:
Kubelet with the flag '--runonce' can't bring up the static pods with volumes.

**What you expected to happen**:
runonce mode should support volumes.

**How to reproduce it** (as minimally and precisely as possible):
1. kubelet with '--runonce' flag as a system unit servie
2. A pod requires volumeMounts under /etc/kubernetes/manifests directory, for example, the kube-proxy.

apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: quay.io/coreos/hyperkube:v1.5.2_coreos.0
    command:
    - /hyperkube
    - proxy
    - --kubeconfig=/etc/kubernetes/kubeconfig.yaml
    - --proxy-mode=iptables
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /etc/localtime
        name: timezone
      - mountPath: /etc/ssl/certs
        name: "ssl-certs"
      - mountPath: /etc/kubernetes/kubeconfig.yaml
        name: "kubeconfig"
        readOnly: true
      - mountPath: /etc/kubernetes/ssl
        name: "etc-kube-ssl"
        readOnly: true
  volumes:
    - name: timezone 
      hostPath: 
        path: /etc/localtime 
    - name: "ssl-certs"
      hostPath:
        path: "/usr/share/ca-certificates"
    - name: "kubeconfig"
      hostPath:
        path: "/etc/kubernetes/kubeconfig.yaml"
    - name: "etc-kube-ssl"
      hostPath:
        path: "/etc/kubernetes/ssl"

Get errors like:
Mar 10 11:26:11 aa02.sjc.lab kubelet-wrapper[11337]: Error: failed to run Kubelet: runonce failed: error running pods: [kube-pr
oxy-aa02.sjc.lab_default(893f833a711f731fc1775d8c545f91b3)]
Mar 10 11:26:11 aa02.sjc.lab kubelet-wrapper[11337]: I0310 19:26:11.725331   11337 runonce.go:61] finished processing 1 pods
Mar 10 11:26:11 aa02.sjc.lab kubelet-wrapper[11337]: I0310 19:26:11.725319   11337 runonce.go:94] failed to start pod "kube-pro
xy-aa02.sjc.lab_default(893f833a711f731fc1775d8c545f91b3)": error syncing pod "kube-proxy-aa02.sjc.lab_default(893f833a711f731f
c1775d8c545f91b3)": timeout expired waiting for volumes to attach/mount for pod "default"/"kube-proxy-aa02.sjc.lab". list of un
attached/unmounted volumes=[timezone ssl-certs kubeconfig etc-kube-ssl]

**Anything else we need to know**:
We are trying to bring up kube-proxy first to reach our glusterfs service in k8s. After the gluster volume is mounted successfully on host, we can run kubelet normally to schedule other jobs.

**Comment by JulienBalestra** [comment]
I have the same issue with the v1.5.5 with rkt as container runtime.

Could you tell me what is your container runtime in your setup ?

**Comment by jiosec** [comment]
I'm using rkt for kubelet too.

**Comment by JulienBalestra** [comment]
For me the following setup doesn't works: https://github.com/JulienBalestra/enjoliver/blob/ebc091f7c424d3f51c08dede6d88d16bf2babf60/matchbox/ignition/etcd-member-kubernetes-control-plane.yaml#L325

Without the `--runonce` flag it works.
I need to setup the **kube-apiserver** before running the definitive **kubelet** to avoid several issues in case of reboots / upgrades.

ATM I see the following options:

1. Fix why the volumeManager loop doesn't attach / mount the corresponding volumes
2. Avoid volumes by fetching the secrets with the rkt `eventHandlers`
3. Create init containers for rkt (append to `eventHandlers` ?)
4. Hack the issue by adding a systemd `BindTo` -> running until pods are ready

**Comment by JulienBalestra** [comment]
@jiosec you can use this [script](https://gist.github.com/JulienBalestra/3b783cc8313a8cf7de0615873a2a3731) to recompile hyperkube for making `kubelet --runonce` works with volumes.

PS: You'll need the usual tool-chain for Kubernetes.

**Comment by jiosec** [comment]
Nice. Thanks Julien!

**Comment by spiffxp** [comment]
/sig node
the linked PR is tagged sig/node

**Comment by fanux** [comment]
```
E0820 20:39:46.547172    1347 kubelet.go:1261] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data for container /
F0820 20:39:47.547636    1347 server.go:262] failed to run Kubelet: runonce failed: no pod manifest update after 1s
```
Runonce failed, version v1.11.1
