### ISSUE TITLE
Version skew test are failing for taint

### ISSUE THREAD

**Issue by ymqytw** [kubernetes/kubernetes#42918]
These 2 tests are [failing](https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gce-1.5-1.6-cvm-kubectl-skew). It is casused by moving taints from annotation to API fields in #38957
```
[k8s.io] Kubectl client [k8s.io] Kubectl run default should create an rc or deployment from an image [Conformance]
[k8s.io] Kubectl client [k8s.io] Kubectl run deployment should create a deployment from an image [Conformance]
```
@davidopp Is taint feature alpha in 1.5 and beta in 1.6? 
If it is alpha in 1.5, we can simply skip this test in the skew test. PTAL
cc: @aveshagarwal

**Comment by aveshagarwal** [comment]
@ymqytw yes. and taint changes in 1.6 are compatible with 1.5.

**Comment by davidopp** [comment]
Why do you think the failures are because of moving taints from annotation to API fields?

I looked at the two tests and didn't see anything related to taints.

**Comment by ymqytw** [comment]
@davidopp In this test, master is 1.5 and kubectl is 1.6. New kubectl sends a patch contains a field that the API server doesn't recognize, the API server will drop this unknown field.

**Comment by davidopp** [comment]
These tests appear to be passing consistently recently. Probably one of the bug fixes merged in the past few days fixed this. I'm going to close, but please reopen if I am mis-reading and they are still failing.

**Comment by ymqytw** [comment]
I suspect you are looking at the wrong tests?
The skew tests are not passing.
https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gce-1.5-1.6-cvm-kubectl-skew
https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gce-1.5-1.6-gci-kubectl-skew
It seems I don't have permission to open this issue again. Please open it.

**Comment by davidopp** [comment]
There are two tests failing at the links you pasted, but those are not the tests mentioned in this issue. 

The two tests that are failing there are expected to fail because of the backward incompatible change to how "kubectl taint" works.

**Comment by ymqytw** [comment]
> There are two tests failing at the links you pasted, but those are not the tests mentioned in the top of this issue.

Sorry, I pasted the wrong text in the issue description.

>The two tests that are failing there are expected to fail because of the backward incompatible change to how "kubectl taint" works.

We should skip these 2 taint skew tests for this version. I will file a PR against 1.5 branch to make the skew tests not failing.

**Comment by davidopp** [comment]
> We should skip these 2 taint skew tests for this version. 

Agreed.

> I will file a PR against 1.5 branch to make the skew tests not failing.

Thanks!
