### ISSUE TITLE
Flanneld doesn't come up with Docker 1.12 and Kubernetes doesn't come up with Docker 1.13

### ISSUE THREAD

**Issue by newtonkishore** [kubernetes/kubernetes#42919]
I am using Kubernetes contrib: git clone https://github.com/kubernetes/contrib.git . can this be modified to start with Docker 1.13? Thanks a lot in advance.

Flannel:
journalctl -o cat --unit flanneld
Starting Flanneld overlay address etcd agent...
I0310 12:14:10.553332    1022 main.go:132] Installing signal handlers
I0310 12:14:10.554032    1022 manager.go:136] Determining IP address of default interface
I0310 12:14:10.554443    1022 manager.go:149] Using interface with name eth0 and address 192.168.122.69
I0310 12:14:10.554472    1022 manager.go:166] Defaulting external address to interface address (192.168.122.69)
flanneld.service start operation timed out. Terminating.
I0310 12:15:40.758926    1022 main.go:172] Exiting...
Failed to start Flanneld overlay address etcd agent.
Unit flanneld.service entered failed state.
flanneld.service failed.
flanneld.service holdoff time over, scheduling restart.

Docker:
Started Docker Application Container Engine.
Stopping Docker Application Container Engine...
time="2017-03-10T11:39:32.553767154-08:00" level=info msg="stopping containerd after receiving terminated"
time="2017-03-10T11:39:32.553951007-08:00" level=info msg="Processing signal 'terminated'"
time="2017-03-10T11:39:32.555340662-08:00" level=error msg="libcontainerd: failed to receive event from containerd: rpc error: code = 13 desc = transport is closing"
Stopped Docker Application Container Engine.

This is fixed in 1.13 -> check this [link](https://github.com/docker/docker/issues/28470) .

The Flanneld is starting fine with Docker 1.13, but Kubernetes installation conflicts with Docker 1.13 using ansible. 

ASK [node : CentOS | Install kubernetes node] *********************************
fatal: [192.168.122.120]: FAILED! => {"changed": true, "failed": true, "msg": "Error: docker-ce-selinux conflicts with 2:container-selinux-2.9-4.el7.noarch\nError: docker-ce conflicts with 2:docker-1.12.6-11.el7.centos.x86_64\n", "rc": 1, "results": ["Loaded plugins: fastestmirror, langpacks\nLoading mirror speeds from cached hostfile\n * base: pubmirrors.dal.corespace.com\n * epel: reflector.westga.edu\n * extras: mirrors.sonic.net\n * updates: centos.vwtonline.net\nResolving Dependencies\n--> Running transaction check\n---> Package kubernetes-node.x86_64 0:1.5.2-0.2.gitc55cf2b.el7 will be installed\n--> Processing Dependency: socat for package: kubernetes-node-1.5.2-0.2.gitc55cf2b.el7.x86_64\n--> Processing Dependency: docker for package: kubernetes-node-1.5.2-0.2.gitc55cf2b.el7.x86_64\n--> Processing Dependency: conntrack-tools for package: kubernetes-node-1.5.2-0.2.gitc55cf2b.el7.x86_64\n--> Running transaction check\n---> Package conntrack-tools.x86_64 0:1.4.3-1.el7 will be installed\n--> Processing Dependency: libnetfilter_cttimeout.so.1(LIBNETFILTER_CTTIMEOUT_1.1)(64bit) for package: conntrack-tools-1.4.3-1.el7.x86_64\n--> Processing Dependency: libnetfilter_cttimeout.so.1(LIBNETFILTER_CTTIMEOUT_1.0)(64bit) for package: conntrack-tools-1.4.3-1.el7.x86_64\n--> Processing Dependency: libnetfilter_cthelper.so.0(LIBNETFILTER_CTHELPER_1.0)(64bit) for package: conntrack-tools-1.4.3-1.el7.x86_64\n--> Processing Dependency: libnetfilter_queue.so.1()(64bit) for package: conntrack-tools-1.4.3-1.el7.x86_64\n--> Processing Dependency: libnetfilter_cttimeout.so.1()(64bit) for package: conntrack-tools-1.4.3-1.el7.x86_64\n--> Processing Dependency: libnetfilter_cthelper.so.0()(64bit) for package: conntrack-tools-1.4.3-1.el7.x86_64\n---> Package docker.x86_64 2:1.12.6-11.el7.centos will be installed\n--> Processing Dependency: docker-common = 2:1.12.6-11.el7.centos for package: 2:docker-1.12.6-11.el7.centos.x86_64\n--> Processing Dependency: docker-client = 2:1.12.6-11.el7.centos for package: 2:docker-1.12.6-11.el7.centos.x86_64\n--> Processing Dependency: container-selinux >= 2:2.9-4 for package: 2:docker-1.12.6-11.el7.centos.x86_64\n---> Package socat.x86_64 0:1.7.2.2-5.el7 will be installed\n--> Running transaction check\n---> Package container-selinux.noarch 2:2.9-4.el7 will be installed\n---> Package docker-client.x86_64 2:1.12.6-11.el7.centos will be installed\n---> Package docker-common.x86_64 2:1.12.6-11.el7.centos will be installed\n---> Package libnetfilter_cthelper.x86_64 0:1.0.0-9.el7 will be installed\n---> Package libnetfilter_cttimeout.x86_64 0:1.0.0-6.el7 will be installed\n---> Package libnetfilter_queue.x86_64 0:1.0.2-2.el7 will be installed\n--> Processing Conflict: docker-ce-17.03.0.ce-1.el7.centos.x86_64 conflicts docker\n--> Processing Conflict: docker-ce-17.03.0.ce-1.el7.centos.x86_64 conflicts docker\n--> Processing Conflict: docker-ce-17.03.0.ce-1.el7.centos.x86_64 conflicts docker-io\n--> Processing Conflict: docker-ce-17.03.0.ce-1.el7.centos.x86_64 conflicts docker-io\n--> Processing Conflict: docker-ce-selinux-17.03.0.ce-1.el7.centos.noarch conflicts docker-selinux\n--> Processing Conflict: docker-ce-selinux-17.03.0.ce-1.el7.centos.noarch conflicts docker-selinux\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"]}
	to retry, use: --limit @/home/contrib/ansible/playbooks/deploy-cluster.retry

**Comment by JackyChen255** [comment]
Any update here? I ran into the same issue after following this instruction to install Kubernetes in CentOS 7.2. https://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/

**Comment by newtonkishore** [comment]
The problem was with the flannel version. Flannel version 0.7 wasn't compatible with docker 1.12. I am downgrading my flannel to bring up the kubernetes cluster

**Comment by kargakis** [comment]
Doesn't seem a K8S issue, closing
