### ISSUE TITLE
`[k8s.io] Dynamic provisioning [k8s.io] DynamicProvisioner External should let an external dynamic provisioner create and delete persistent volumes [Slow] [Volume]` test failing

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#42924]
The test `[k8s.io] Dynamic provisioning [k8s.io] DynamicProvisioner External should let an external dynamic provisioner create and delete persistent volumes [Slow] [Volume]` [began failing](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-slow) in GKE between `2017-03-09 18:16 PST` and `2017-03-09 19:03 PST`.

The non-GKE version of this test is still green indicating there is a change on the GKE side that caused this.

The tests fails with:
```
I0310 02:30:15.633] [BeforeEach] [k8s.io] Dynamic provisioning
I0310 02:30:15.633]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/volume_provisioning.go:105
I0310 02:30:15.633] [It] should let an external dynamic provisioner create and delete persistent volumes [Slow] [Volume]
I0310 02:30:15.633]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/volume_provisioning.go:283
I0310 02:30:15.633] Error binding clusterrole/system:persistent-volume-provisioner for "e2e-tests-volume-provisioning-sh7h4" for [{ServiceAccount  default e2e-tests-volume-provisioning-sh7h4}]
```

@msau42 is helping investigate.

CC @calebamiles @pwittrock @kubernetes/sig-storage-bugs

**Comment by msau42** [comment]
The test failed here:

248                         // external dynamic provisioner pods need additional permissions provided by the                      
249                         // persistent-volume-provisioner role                                                                 
250                         framework.BindClusterRole(c.Rbac(), "system:persistent-volume-provisioner", ns,                       
251                                 rbacv1beta1.Subject{Kind: rbacv1beta1.ServiceAccountKind, Namespace: ns, Name: "default"})    
252                                                                                                                               
253                         err := framework.WaitForAuthorizationUpdate(c.AuthorizationV1beta1(),                                 
254                                 serviceaccount.MakeUsername(ns, "default"),                                                   
255                                 "", "get", schema.GroupResource{Group: "storage.k8s.io", Resource: "storageclasses"}, true)   
256                         framework.ExpectNoError(err, "Failed to update authorization: %v", err) 

It is trying to create a special cluster role to run the external provisioner in, but is failing.  It's possible GKE may have locked down what roles are available.  I am working with GKE folks to investigate further.

/assign

**Comment by saad-ali** [comment]
Update from @msau42: `The failing test was affected by some RBAC changes that went into GKE.  With the help of CJ and Erick, the jenkins service account for this test suite was just given "container engine admin" privileges, which should hopefully resolve the issue.`

Test should be green now. Resolving issue.
