### ISSUE TITLE
kube-proxy can not start when using rkt 

### ISSUE THREAD

**Issue by ErwanMAS** [kubernetes/kubernetes#42946]
**Kubernetes version**
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
**RKT version**
```
rkt Version: 1.25.0
appc Version: 0.8.10
Go Version: go1.7.4
Go OS/Arch: linux/amd64
Features: -TPM +SDJOURNAL
```
**Environment**:
- **Cloud provider or hardware configuration**:  Virtualbox 
- **OS** : Ubuntu 16.04.2 LTS
- **Kernel** : `Linux k8-mast 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**What happened**:
kube-proxy can not start .

```
Using iptables Proxier.
Unable to create proxier: can't set sysctl net/ipv4/conf/all/route_localnet: open /proc/sys/net/ipv4/conf/all/route_localnet: read-only file system
```

**Anything else we need to know**:

very similar to https://github.com/coreos/rkt/issues/2751 , but when i edit the  pod for checking  the securitycontext , `privileged` is here .  
```
    securityContext:
      privileged: true
```

**Comment by dcbw** [comment]
@ErwanMAS It seems privileged: true is not sufficient, but that kube-proxy's pod specs may need to mount /proc/sys into the container as well?  Any chance you could try making that change in the kube-proxy pod spec to the volumes + volumeMounts sections to add /proc/sys/?

**Comment by TerraTech** [comment]
@dcbw After upgrading to CoreOS 1353.8.0 and hyperkube-1.6.4_coreos.0, kube-proxy failed to start with the above read-only failure.

Upgraded from: 1353.7.0 and hyperkube-1.6.2_coreos.0

I added the volume mounts:
```
volumeMounts:
...
- mountPath: /proc/sys
  name: "proc-sys"
  readOnly: false
volumes:
...
- name: "proc-sys"
  hostPath:
    path: "/proc/sys"
```
however kube-proxy is still complaining that _/proc/sys_ is read-only.  Also, the pod spec does have _privileged: true_

Is there any other workaround you might suggest?

**Comment by TerraTech** [comment]
@ErwanMAS @dcbw 
I fixed it by adding the following to the kube-proxy pod spec
```
annotations:
  rkt.alpha.kubernetes.io/stage1-name-override: coreos.com/rkt/stage1-fly
```
