### ISSUE TITLE
gpu error

### ISSUE THREAD

**Issue by timchenxiaoyu** [kubernetes/kubernetes#42971]
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVer
sion:"go1.7", Compiler:"gc", Platform:"linux/amd64"}Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVer
sion:"go1.6.1", Compiler:"gc", Platform:"linux/amd64"}

on  centos7 host,
 nvidia-smi
Mon Mar 13 08:50:00 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 0000:00:08.0     Off |                    0 |
| N/A   37C    P0    49W / 250W |      0MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

on ubuntu14.04 container:
 nvidia-smi
Failed to initialize NVML: GPU access blocked by the operating system

maybe eth difference of host and container os,or cuda driver.

**Comment by timchenxiaoyu** [comment]
on cnetos7 host:
 ll /dev/n
net/                network_throughput  nvidia0             nvidia-uvm          nvram               
network_latency     null                nvidiactl           nvidia-uvm-tools

**Comment by cmluciano** [comment]
Is the container running the same version as the host? If there is a mismatch, you could have problems like this.

**Comment by liyubobj** [comment]
You need to expose host GPU driver or install GPU driver into container. In current k8s GPU support, GPU driver volume injection is not supported. Please refer to this proposal: https://github.com/kubernetes/kubernetes/pull/43058

**Comment by timchenxiaoyu** [comment]
I have solve this to upgrade the cuda version,ths all
