### ISSUE TITLE
fluentd-elasticsearch addon: found invalid field tolerations for v1.PodSpec

### ISSUE THREAD

**Issue by quantonganh** [kubernetes/kubernetes#42983]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): "found invalid field tolerations for v1.PodSpec"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-08T02:50:34Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): Mac OS X 10.12.3
- **Kernel** (e.g. `uname -a`): Darwin Kernel Version 16.4.0
- **Install tools**:
- **Others**:

**What happened**:

```
replicationcontroller "elasticsearch-logging-v1" created
service "elasticsearch-logging" created
deployment "kibana-logging" created
service "kibana-logging" created
error: error validating "cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml": error validating data: found invalid field tolerations for v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

**What you expected to happen**:

daemonset "fluentd-es-v1.22" should be created without error.

**How to reproduce it** (as minimally and precisely as possible):

- clone this repo
- then run:

```
kubectl create -f cluster/addons/fluentd-elasticsearch
```

**Comment by crassirostris** [comment]
@quantonganh Fluentd was moved to DaemonSet in 1.6, it is not tested/fully compatible with Kubernetes 1.5

**Comment by kylegato** [comment]
@quantonganh I ran into the same issue, this one appears to work: https://raw.githubusercontent.com/fluent/fluentd-kubernetes-daemonset/master/fluentd-daemonset-elasticsearch.yaml

**Comment by crassirostris** [comment]
@quantonganh  @kylegato Whoops, I think I owe you an apology. Toleration for fluentd is actually unnecessary, because it doesn't work on master anyway. The `DaemonSet` is still only tested and truly compatible with K8s 1.6, but that trouble was my fault. I filed an issue for that: https://github.com/kubernetes/kubernetes/issues/43795

**Comment by albertvaka** [comment]
@crassirostris then the tolerations field should be removed from https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml ?

**Comment by crassirostris** [comment]
@albertvaka Yes. Sorry, was busy with other things, I will make a PR today
