### ISSUE TITLE
How i can change file name in secret tls

### ISSUE THREAD

**Issue by hoanhdo** [kubernetes/kubernetes#42987]
Hi all.
I am running kubernetes-1.5.2-0.2.gitc55cf2b.el7.x86_64
- **VmWare**:
- **OS** : CentOS Linux release 7.2.1511 (Core) 
- **Kernel** : 3.10.0-327.el7.x86_64
I run nginx with ssl and kubenetes secret. But config file nginx in container not match secret.

I run nginx with ssl using secret 
> openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /tmp/nginx.key -out /tmp/nginx.crt -subj "/CN=nginxsvc/O=nginxsvc"
kubectl create secret tls nginxsecret --key /tmp/nginx.key --cert /tmp/nginx.crt

Describe secret : kubectl describe secrets/nginxsecret

> Name:           nginxsecret
Namespace:      default
Labels:         <none>
Annotations:    <none>
Type:   kubernetes.io/tls
Data
====
tls.crt:        1143 bytes
tls.key:        1704 bytes

I see secret file always tls.crt and tls.key??? 
In my nginx container require ssl file
/etc/nginx/ssl

> apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: nginxsecret
      containers:
      - name: nginxhttps
        image: bprashanth/nginxhttps:1.0
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume

After create deployment nginx . this is log 
kubectl logs po/my-nginx-4012356658-j4cv2

> 2017/03/13 09:56:31 [emerg] 1#1: BIO_new_file("/etc/nginx/ssl/nginx.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/nginx.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: [emerg] BIO_new_file("/etc/nginx/ssl/nginx.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/nginx.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)

How i can match secret in container without rebuild container.
Hoan
Thanks.

**Comment by a11smiles** [comment]
you, don't.  You're almost there but realize that the `nginxsecret` is really just a dictionary-like structure.  Instead of using the `tls` flag, create a `generic` cert with the following:

```bash
kubectl create secret generic nginxsecret --from-file=/tmp/nginx.key --from-file=/tmp/nginx.crt
```

Then redeploy your pods:

```bash
kubectl delete deployments,svc my-nginx; kubectl create -f ./nginx-secure-app.yaml
```

**Comment by kargakis** [comment]
Please use stackoverflow, the kubernetes-users mailing list, or slack for support questions.
