### ISSUE TITLE
coredns federation provider should support etcd with TLS

### ISSUE THREAD

**Issue by mattymo** [kubernetes/kubernetes#42995]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

**Kubernetes version** (use `kubectl version`): 1.6.0-beta.1

**Environment**:
- **Cloud provider or hardware configuration**: bare metal
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04 Xenial
- **Kernel** (e.g. `uname -a`): Linux node1 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubefed
- **Others**: N/A

**What happened**:
coredns federation provider uses ETCD as a backend, but it does not support TLS etcd connection options
https://github.com/kubernetes/kubernetes/blob/master/federation/pkg/dnsprovider/providers/coredns/coredns.go#L73

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
It should support options for CertFile, KeyFile, and CAFile.

**Comment by dshulyak** [comment]
@shashidharatd Are you going to work on it in nearest time? I can help probably

**Comment by shashidharatd** [comment]
@dshulyak, I am not working on it right now and haven't started, but was on my list.
So feel free to take it up.

**Comment by quinton-hoole** [comment]
@dshulyak Any progress?

**Comment by dshulyak** [comment]
@quinton-hoole yes, this change is ready to be merged https://github.com/kubernetes/kubernetes/pull/47049
