### ISSUE TITLE
Rename of Container Linux broke kube-up.sh

### ISSUE THREAD

**Issue by canausa** [kubernetes/kubernetes#43013]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): COS ( Container Optimized Image)
- **Kernel** (e.g. `uname -a`):
- **Install tools**: kube-up.sh
- **Others**:

**What happened**: Failed to run on new image of the old Container Optimized

**What you expected to happen**: kube-up.sh to run on COS

**How to reproduce it** (as minimally and precisely as possible):

https://cloud.google.com/container-optimized-os/docs/how-to/run-container-instance#running_a_kubernetes_cluster

**Anything else we need to know**:

Looks like a few variables need update:
https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L26

**Comment by shiywang** [comment]
will take a look
