### ISSUE TITLE
dockershim: clean up corrupted checkpoint properly

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#43021]
The reboot test may cause corrupted checkpoint left on the node. 
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-reboot/5006

This prevents the sandbox from being stopped properly, so kubelet cannot create a new one.

```
I0312 20:24:12.809876    2479 helpers.go:210] Cannot find network namespace for the terminated container "551ad02c183c9b523381c1f774adb104803ec079c8171f0fe59567760769fd78"
I0312 20:24:12.813477    2479 helpers.go:210] Cannot find network namespace for the terminated container "551ad02c183c9b523381c1f774adb104803ec079c8171f0fe59567760769fd78"
I0312 20:24:12.815598    2479 helpers.go:210] Cannot find network namespace for the terminated container "551ad02c183c9b523381c1f774adb104803ec079c8171f0fe59567760769fd78"
I0312 20:24:12.815620    2479 kubenet_linux.go:789] Removing kube-system/npd-v0.3.0-alpha.1-zxnc2 from 'kubenet' with CNI 'bridge' plugin and runtime: &{ContainerID:551ad02c183c9b523381c1f774adb104803ec079c8171f0fe59567760769fd78 NetNS: IfName:eth0 Args:[]}
E0312 20:24:12.822994    2479 docker_checkpoint.go:113] Failed to unmarshal checkpoint "551ad02c183c9b523381c1f774adb104803ec079c8171f0fe59567760769fd78". Checkpoint content: "". ErrMsg: unexpected end of JSON input
E0312 20:24:12.824302    2479 remote_runtime.go:109] StopPodSandbox "551ad02c183c9b523381c1f774adb104803ec079c8171f0fe59567760769fd78" from runtime service failed: rpc error: code = 2 desc = NetworkPlugin kubenet failed to teardown pod "npd-v0.3.0-alpha.1-zxnc2_kube-system" network: checkpoint is corrupted.
E0312 20:24:12.824360    2479 kuberuntime_manager.go:780] Failed to stop sandbox {"docker" "551ad02c183c9b523381c1f774adb104803ec079c8171f0fe59567760769fd78"}
```

One option is to log and remove the corrupted checkpoint, while cleaning up the pod sandbox resources with best effort (i.e., may leak resources). Another option is to *not* clean up, and force a human being to intervene and remove the corrupt checkpoint manually. The proper solution perhaps is to scan the checkpoints at startup (or periodically) and repair/remove corrupt checkpoints. 

/cc @freehan @thockin 
related: #42960

**Comment by ethernetdan** [comment]
@yujuhong @dchen1107 should this block `v1.6`?

**Comment by dchen1107** [comment]
>  The proper solution perhaps is to scan the checkpoints at startup (or periodically) and repair/remove corrupt checkpoints.

If we can scan the checkpoints at startup time, then repair the corrupted checkpoint, which means, we can recover the state from the runtime, why we introduce the checkpoint at the first place? :-) 

@yujuhong I am ok with your idea upon the corrupted checkpoints, removing the bad ones as the workaround. Anyway, Kubelet will fire an event of failedSync with the proper message, some manual intervene (the remedy system) can be fired based on the event to resolve the leak resource issue.

**Comment by dchen1107** [comment]
@ethernetdan I think this shouldn't be the blocker for v1.6, but @yujuhong has an acceptable workaround to address this, and I would like to include that if no one disagreed with that approach.

**Comment by ethernetdan** [comment]
Adding to milestone to track

**Comment by yujuhong** [comment]
Moving this back to 1.6. The checkpoint implementation use `ioutil.WriteFile()`, which does not sync at all. No wonder the checkpoints would be corrupted in the reboot tests. 
I reproduced this issue with a simple go program + reboots on a VM. The problem went away once I forced a `File.Sync`

I will upload a PR to fix this. 

/cc @thockin
