### ISSUE TITLE
GCE 1.5->1.6 upgrade testing: [k8s.io] Monitoring should verify monitoring pods and all cluster nodes are available on influxdb using heapster. 6.10s

### ISSUE THREAD

**Issue by skriss** [kubernetes/kubernetes#43024]
@piosz 

The following E2E test is failing in the GCE 1.5->1.6 upgrade jobs. Please take a look and let me know ASAP if this is a 1.6 blocker or not (I think it may be a flake, but need you to confirm).

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.5-1.6-upgrade-cluster-new/18#k8sio-monitoring-should-verify-monitoring-pods-and-all-cluster-nodes-are-available-on-influxdb-using-heapster

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/monitoring.go:44
Expected error:
    <*errors.errorString | 0xc421d5ef10>: {
        s: "expected to find one replica for RC or deployment with label heapster but got 0",
    }
    expected to find one replica for RC or deployment with label heapster but got 0
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/monitoring.go:290

**Comment by skriss** [comment]
@fabxc can you help get this looked at and triaged ASAP? Thanks.

**Comment by davidopp** [comment]
I pinged @piosz by email. He's really the one who should look at this.

**Comment by piosz** [comment]
I haven't got time to investigate. This seems to be unrelated to monitoring itself, so any help during MTV day would be great. If not I'll try to fix this tomorrow

**Comment by ethernetdan** [comment]
thanks @piosz!

**Comment by jszczepkowski** [comment]
The problem is in e2e/monitoring.go:121, in function `verifyExpectedRcsExistAndGetExpectedPods`. The function is called immediately from `testMonitoringUsingHeapsterInfluxdb`, w/o waiting for system pods (heapster) to start. We should give some time for heapster to become ready, as it takes few minutes after cluster creation.

**Comment by jszczepkowski** [comment]
CC @MaciekPytel

**Comment by piosz** [comment]
@jszczepkowski thanks a lot for investigation!
@MaciekPytel is going to fix it.
