### ISSUE TITLE
Update photon controller go SDK vendor code

### ISSUE THREAD

**Issue by luomiao** [kubernetes/kubernetes#43042]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
1.6

**What happened**:
Latest Photon Controller uses updated photon controller go SDK, which has updated interfaces functions. These updates breaks the current photon controller cloud provider in kubernetes.

**What you expected to happen**:
Photon controller go SDK in kubernetes vendor code should be updated.

**Anything else we need to know**:
I will work on this and submit a PR soon.

**Comment by spiffxp** [comment]
/assign
closing because this was fixed in the linked pr

/close
