### ISSUE TITLE
kubernetes deletes OpenStack LBaaS resources without filtering

### ISSUE THREAD

**Issue by FengyunPan** [kubernetes/kubernetes#43055]
Neutron's API ignores unknown paramaters. When listing pools etc, K8 attempts to filter on "loadBalancerID" which is not a valid filter.
As such, it is ignored by Neutron, and a list of all pools is returned. Then K8 proceeds all the pools. 
For example, EnsureLoadBalancerDeleted() delete all the pools and members.

https://docs.openstack.org/cli-reference/neutron.html#neutron-lbaas-listener-list
https://docs.openstack.org/cli-reference/neutron.html#neutron-lbaas-pool-list

**Comment by FengyunPan** [comment]
https://github.com/kubernetes/kubernetes/pull/43056

**Comment by xsgordon** [comment]
/cc @k8s-sig-openstack-bugs 

@idvoretskyi can you add the sig/openstack label please?
