### ISSUE TITLE
All pods on the unreachable node should be marked as NotReady upon the node turn NotReady AND all pods should be evicted after eviction timeout passes

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#43068]
All pods on the unreachable node should be marked as NotReady upon the node turn NotReady AND all pods should be evicted after eviction timeout passes
This test is not passing on https://k8s-testgrid.appspot.com/release-1.6-all#gci-gke-serial-1.6&width=20

cc @gmarek

**Comment by ethernetdan** [comment]
@foxish @gmarek should this be a release blocker?

**Comment by foxish** [comment]
I suspect not. @gmarek will have more context on this one.

**Comment by davidopp** [comment]
Unfortunately @gmarek is on vacation for two weeks. @wojtek-t I know this isn't code you've worked with much but could you take a look?

**Comment by wojtek-t** [comment]
Hmm - this test shouldn't even be running as part of this suite. It has "[Feature:TaintEviction]" tag. Will look why it is actually running there.

The fact that it doesn't work is "working as indended", because the features is not switched on in controller manager - to switch it on we would need something like:
```
CONTROLLER_MANAGER_TEST_ARGS=--feature-gates=TaintBasedEvictions=true --enable-taint-manager=true
```

in the test job configuration.

**Comment by wojtek-t** [comment]
It generally seems that the set of suites running as part of gci-gke-serial and gci-gke-serial-1.6 are completely different.
Looking into test config.

**Comment by davidopp** [comment]
I had grepped for the string in the issue subject in test/e2e and found it only in the "Network Partition [Disruptive] [Slow]" test, which didn't seem related to the alpha taint stuff @gmarek did.

**Comment by wojtek-t** [comment]
@davidopp - it is related: https://github.com/kubernetes/kubernetes/pull/41133

**Comment by davidopp** [comment]
But this test wasn't added in Marek's taints PR and doesn't check anything related to taints or tolerations, right? It's just testing old node eviction behavior IIUC.
