### ISSUE TITLE
instance not found when using aws cloud-provider 

### ISSUE THREAD

**Issue by chao007** [kubernetes/kubernetes#43063]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1163+5e29e1ee055568-dirty", GitCommit:"5e29e1ee05556800cd2fe0dc5341d5de54b4ab47", GitTreeState:"dirty", BuildDate:"2017-03-14T02:36:44Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1163+5e29e1ee055568-dirty", GitCommit:"5e29e1ee05556800cd2fe0dc5341d5de54b4ab47", GitTreeState:"dirty", BuildDate:"2017-03-14T02:36:44Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
aws
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
hack/local-up-cluster.sh
- **Others**:

**What happened**:
I create a pod using ebs volume, but always get instance not found error message

**What you expected to happen**:
Pod should be running 

**How to reproduce it** (as minimally and precisely as possible):
1.Create pv
[root@ip-172-18-9-70 tmp]# kubectl get pv -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    creationTimestamp: 2017-03-14T05:55:45Z
    labels:
      type: local
    name: ebs1
    namespace: ""
    resourceVersion: "237"
    selfLink: /api/v1/persistentvolumesebs1
    uid: ddc9381a-087a-11e7-982f-0ecb7d4ecce4
  spec:
    accessModes:
    - ReadWriteOnce
    awsElasticBlockStore:
      fsType: ext4
      volumeID: aws://us-east-1d/vol-03b77fc85993fbafe
    capacity:
      storage: 1Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: ebs1
      namespace: default
      resourceVersion: "235"
      uid: e5984444-087a-11e7-982f-0ecb7d4ecce4
    persistentVolumeReclaimPolicy: Retain
  status:
    phase: Bound
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""

2.Create a pvc
[root@ip-172-18-9-70 tmp]# kubectl get pvc ebs1 -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: 2017-03-14T05:55:58Z
  name: ebs1
  namespace: default
  resourceVersion: "239"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/ebs1
  uid: e5984444-087a-11e7-982f-0ecb7d4ecce4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: ebs1
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound

3.Create a pod
[root@ip-172-18-9-70 tmp]# kubectl get pvc ebs1 -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: 2017-03-14T05:55:58Z
  name: ebs1
  namespace: default
  resourceVersion: "239"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/ebs1
  uid: e5984444-087a-11e7-982f-0ecb7d4ecce4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: ebs1
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
[root@ip-172-18-9-70 tmp]# kubectl get pods -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: 2017-03-14T05:56:09Z
    labels:
      name: frontendhttp
    name: mypod1
    namespace: default
    resourceVersion: "253"
    selfLink: /api/v1/namespaces/default/pods/mypod1
    uid: ebfd0a60-087a-11e7-982f-0ecb7d4ecce4
  spec:
    containers:
    - image: aosqe/hello-openshift
      imagePullPolicy: Always
      name: myfrontend
      ports:
      - containerPort: 80
        name: http-server
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /tmp
        name: aws
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-lnswv
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: ip-172-18-9-70.ec2.internal
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.alpha.kubernetes.io/notReady
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.alpha.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: aws
      persistentVolumeClaim:
        claimName: ebs1
    - name: default-token-lnswv
      secret:
        defaultMode: 420
        secretName: default-token-lnswv
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2017-03-14T05:56:09Z
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: 2017-03-14T05:56:09Z
      message: 'containers with unready status: [myfrontend]'
      reason: ContainersNotReady
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: 2017-03-14T05:56:09Z
      status: "True"
      type: PodScheduled
    containerStatuses:
    - image: aosqe/hello-openshift
      imageID: ""
      lastState: {}
      name: myfrontend
      ready: false
      restartCount: 0
      state:
        waiting:
          reason: ContainerCreating
    hostIP: 172.18.9.70
    phase: Pending
    qosClass: BestEffort
    startTime: 2017-03-14T05:56:09Z
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
4.[root@ip-172-18-9-70 tmp]# kubectl describe pods mypod1
Name:		mypod1
Namespace:	default
Node:		ip-172-18-9-70.ec2.internal/172.18.9.70
Start Time:	Tue, 14 Mar 2017 01:56:09 -0400
Labels:		name=frontendhttp
Annotations:	<none>
Status:		Pending
IP:		
Controllers:	<none>
Containers:
  myfrontend:
    Container ID:	
    Image:		aosqe/hello-openshift
    Image ID:		
    Port:		80/TCP
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Environment:	<none>
    Mounts:
      /tmp from aws (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lnswv (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  aws:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	ebs1
    ReadOnly:	false
  default-token-lnswv:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-lnswv
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	node.alpha.kubernetes.io/notReady=:Exists:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable=:Exists:NoExecute for 300s
Events:
  FirstSeen	LastSeen	Count	From					SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----					-------------	--------	------		-------
  17m		17m		1	default-scheduler					Normal		Scheduled	Successfully assigned mypod1 to ip-172-18-9-70.ec2.internal
  17m		1m		16	attachdetach						Warning		FailedMount	Failed to attach volume "ebs1" on node "ip-172-18-9-70.ec2.internal" with: error finding instance ip-172-18-9-70.ec2.internal: instance not found
  15m		10s		8	kubelet, ip-172-18-9-70.ec2.internal			Warning		FailedMount	Unable to mount volumes for pod "mypod1_default(ebfd0a60-087a-11e7-982f-0ecb7d4ecce4)": timeout expired waiting for volumes to attach/mount for pod "default"/"mypod1". list of unattached/unmounted volumes=[aws]
  15m		10s		8	kubelet, ip-172-18-9-70.ec2.internal			Warning		FailedSync	Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"mypod1". list of unattached/unmounted volumes=[aws]

**Anything else we need to know**:
[root@ip-172-18-9-70 tmp]# ps -ef | grep kubelet
root      6084  4443  2 01:55 pts/2    00:02:05 /root/kubernetes/_output/local/bin/linux/amd64/hyperkube apiserver --v=7 --cert-dir=/var/run/kubernetes --client-ca-file=/var/run/kubernetes/client-ca.crt --service-account-key-file=/tmp/kube-serviceaccount.key --service-account-lookup=false --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,SecurityContextDeny,ResourceQuota,DefaultStorageClass,DefaultTolerationSeconds --admission-control-config-file= --bind-address=0.0.0.0 --secure-port=6443 --tls-cert-file=/var/run/kubernetes/serving-kube-apiserver.crt --tls-private-key-file=/var/run/kubernetes/serving-kube-apiserver.key --tls-ca-file=/var/run/kubernetes/server-ca.crt --insecure-bind-address=127.0.0.1 --insecure-port=8080 --kubelet-preferred-address-types=ip-172-18-9-70.ec2.internal --etcd-servers=http://127.0.0.1:2379 --service-cluster-ip-range=10.0.0.0/24 --feature-gates=AllAlpha=true --cloud-provider=aws --cloud-config=/etc/aws.conf --requestheader-username-headers=X-Remote-User --requestheader-group-headers=X-Remote-Group --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-client-ca-file=/var/run/kubernetes/request-header-ca.crt --requestheader-allowed-names=system:auth-proxy --cors-allowed-origins=/127.0.0.1(:[0-9]+)?$,/localhost(:[0-9]+)?$
root      6303  4443  0 01:55 pts/2    00:00:00 sudo -E /root/kubernetes/_output/local/bin/linux/amd64/hyperkube kubelet --enable-cri=true --v=7 --chaos-chance=0.0 --container-runtime=docker --rkt-path= --rkt-stage1-image= --hostname-override=ip-172-18-9-70.ec2.internal --cloud-provider=aws --cloud-config=/etc/aws.conf --address=127.0.0.1 --require-kubeconfig --kubeconfig /var/run/kubernetes/kubelet.kubeconfig --feature-gates=AllAlpha=true --cpu-cfs-quota=true --enable-controller-attach-detach=true --cgroups-per-qos=true --cgroup-driver=systemd --keep-terminated-pod-volumes=true --eviction-hard=memory.available<100Mi --eviction-soft= --eviction-pressure-transition-period=1m --pod-manifest-path=/var/run/kubernetes/static-pods --cluster-dns=8.8.8.8 --port=10250
root      6313  6303  1 01:55 pts/2    00:01:18 /root/kubernetes/_output/local/bin/linux/amd64/hyperkube kubelet --enable-cri=true --v=7 --chaos-chance=0.0 --container-runtime=docker --rkt-path= --rkt-stage1-image= --hostname-override=ip-172-18-9-70.ec2.internal --cloud-provider=aws --cloud-config=/etc/aws.conf --address=127.0.0.1 --require-kubeconfig --kubeconfig /var/run/kubernetes/kubelet.kubeconfig --feature-gates=AllAlpha=true --cpu-cfs-quota=true --enable-controller-attach-detach=true --cgroups-per-qos=true --cgroup-driver=systemd --keep-terminated-pod-volumes=true --eviction-hard=memory.available<100Mi --eviction-soft= --eviction-pressure-transition-period=1m --pod-manifest-path=/var/run/kubernetes/static-pods --cluster-dns=8.8.8.8 --port=10250
root     18739 20526  0 03:38 pts/0    00:00:00 grep --color=auto kubelet

**Comment by gnufied** [comment]
weird looking error. And @chao007 are you sure node `ip-172-18-9-70.ec2.internal` was still available and queriable from API right?

I am trying to create a reproducible bug.

**Comment by gnufied** [comment]
I think this is because of change introduced here - https://github.com/kubernetes/kubernetes/pull/41695/files#diff-07ba008af9c76b0539556ff7fde3105eR3135 

@justinsb The old code allowed "untagged" instances to be found, afaict the new tag selector doesn't include untagged instances. This would be a potentially breaking change.

**Comment by saad-ali** [comment]
Fix is pending merge: https://github.com/kubernetes/kubernetes/pull/43307

**Comment by ponprathip** [comment]
Currently i am getting the same error using minikube .
I have created the required tags in ec2 instance kubernetes.io/cluster/<clusterid> . find the log trace below
==> kube-controller-manager-minikube_kube-system_kube-controller-manager-705ac94b9d40061711839c6d6c1b4cbde1063ff838a6aa9d85345324926355f0.log <==
{"log":"I0508 13:52:36.711862       1 reconciler.go:288] attacherDetacher.AttachVolume started for volume \"pvc-c90f5c9a-7194-11e9-b8d0-069cc4a64dce\" (UniqueName: \"kubernetes.io/aws-ebs/aws://us-west-2a/vol-0252bc09af1974e5f\") from node \"minikube\" \n","stream":"stderr","time":"2019-05-08T13:52:36.712000682Z"}
{"log":"E0508 13:52:36.769042       1 attacher.go:82] Error attaching volume \"aws://us-west-2a/vol-0252bc09af1974e5f\" to node \"minikube\": error finding instance minikube: \"instance not found\"\n","stream":"stderr","time":"2019-05-08T13:52:36.769208492Z"}
{"log":"E0508 13:52:36.769191       1 nestedpendingoperations.go:267] Operation for \"\\\"kubernetes.io/aws-ebs/aws://us-west-2a/vol-0252bc09af1974e5f\\\"\" failed. No retries permitted until 2019-05-08 13:54:38.769156352 +0000 UTC m=+21248.249297058 (durationBeforeRetry 2m2s). Error: \"AttachVolume.Attach failed for volume \\\"pvc-c90f5c9a-7194-11e9-b8d0-069cc4a64dce\\\" (UniqueName: \\\"kubernetes.io/aws-ebs/aws://us-west-2a/vol-0252bc09af1974e5f\\\") from node \\\"minikube\\\" : error finding instance minikube: \\\"instance not found\\\"\"\n","stream":"stderr","time":"2019-05-08T13:52:36.769339321Z"}
{"log":"I0508 13:52:36.769375       1 event.go:209] Event(v1.ObjectReference{Kind:\"Pod\", Namespace:\"default\", Name:\"bdc-6cc7554f95-fjhcr\", UID:\"1375e9e6-7198-11e9-b8d0-069cc4a64dce\", APIVersion:\"v1\", ResourceVersion:\"29589\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedAttachVolume' AttachVolume.Attach failed for volume \"pvc-c90f5c9a-7194-11e9-b8d0-069cc4a64dce\" : error finding instance minikube: \"instance not found\"\n","stream":"stderr","time":"2019-05-08T13:52:36.769474895Z"}
