### ISSUE TITLE
kubelet can panic when trying to determine the pids for a cgroup

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#43074]
When the kubelet is checking for the pids in a cgroup, it checks to ensure a path exists, and then calls `filepath.Walk`. If the path was deleted in between the existence check and the walk, the kubelet can panic because the walk func isn't checking the passed in `err`.

**Comment by ncdc** [comment]
@Random-Liu here's an actual bug report for #42927

**Comment by yujuhong** [comment]
Fixed by #42927

**Comment by ncdc** [comment]
Odd that GitHub didn't pick up the fixes link.
