### ISSUE TITLE
RFE: Explore in-process v3 etcd server

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#43088]
Recent changes to etcd3 have made it easier to embed the etcd server into the executable: https://github.com/coreos/etcd/pull/7496/files

Before that, there was little motivation other then deployment and distribution.  This would allow for an easier deployment model and increased performance for in-process embedding(sans-transport), which may even lead to cache-reduction or elimination.  

The tradeoff here is the apiserver will need to be deployed in 1,3,5. 

As we talk about kubeadm-HA deployments we may want to consider this approach. 

/cc @kubernetes/sig-scalability-feature-requests @kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by wojtek-t** [comment]
Removing milestone - this isn't critical and noone really has capacity for it.
