### ISSUE TITLE
All master upgrade tests skipped

### ISSUE THREAD

**Issue by enisoc** [kubernetes/kubernetes#43102]
**Is this a request for help?**:

No.

**What keywords did you search in Kubernetes issues before filing this one?**:

* AppArmor upgrade
* upgrade test

---

**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release):
  ```
  e2e-test-enisoc-master ~ $ cat /etc/os-release
  BUILD_ID=9000.84.2
  NAME="Container-Optimized OS"
  GOOGLE_CRASH_ID=Lakitu
  VERSION_ID=56
  BUG_REPORT_URL=https://crbug.com/new
  PRETTY_NAME="Container-Optimized OS from Google"
  VERSION=56
  GOOGLE_METRICS_PRODUCT_ID=26
  HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
  ID=cos
  ```
- **Kernel** (e.g. `uname -a`):
  ```
  Linux e2e-test-enisoc-master 4.4.21+ #1 SMP Fri Feb 17 15:34:45 PST 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
  ```
- **Install tools**:
  ```
  go run hack/e2e.go --up
  ```
- **Others**:

**What happened**:

Brought up v1.5.4 e2e test cluster. Ran automated MasterUpgrade tests from HEAD. All tests were skipped with message:

```
S [SKIPPING] [1725.149 seconds]
[k8s.io] Upgrade [Feature:Upgrade]
/usr/local/google/home/enisoc/k8s/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:650
  [k8s.io] master upgrade
  /usr/local/google/home/enisoc/k8s/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:650
    should maintain a functioning cluster [Feature:MasterUpgrade] [It]
    /usr/local/google/home/enisoc/k8s/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:68

    Mar 14 11:19:28.535: Only supported for node OS distro [gci ubuntu] (not debian)

/usr/local/google/home/enisoc/k8s/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:283
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
[...]

Ran 0 of 579 Specs in 1434.858 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 579 Skipped PASS
```

**What you expected to happen**:

The master upgrade tests should run.

**How to reproduce it**:

```sh
git checkout release-1.5
make quick-release
go run hack/e2e.go -v -up

git checkout master
go run hack/e2e.go --check-version-skew=false --v=t --test --test_args="--ginkgo.focus=\[Feature:MasterUpgrade\] --upgrade-target=ci/latest --upgrade-image=gci"
```

**Anything else we need to know**:

It seems that the AppArmor test from #42349 calls `Skip()`, and this skips the entire upgrade test:

https://github.com/kubernetes/kubernetes/blob/b0ce93f9be25c762fd4b746077fcda2aaa5b12bd/test/e2e/upgrades/apparmor.go#L39

**Comment by enisoc** [comment]
@kubernetes/sig-testing-bugs

**Comment by ixdy** [comment]
@kubernetes/sig-node-bugs

**Comment by enisoc** [comment]
Actually I checked and despite the error message text, the master is not debian:

```
e2e-test-enisoc-master ~ $ cat /etc/os-release
BUILD_ID=9000.84.2
NAME="Container-Optimized OS"
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=56
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=56
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
```

**Comment by spxtr** [comment]
cc @krousey

**Comment by krousey** [comment]
Oof. This is actually running a skip in a `BeforeEach`.

**Comment by enisoc** [comment]
I rebuilt `test/e2e/e2e.test` with the following line commented out, and the MasterUpgrade test was no longer skipped:

https://github.com/kubernetes/kubernetes/blob/b0ce93f9be25c762fd4b746077fcda2aaa5b12bd/test/e2e/cluster_upgrade.go#L38

**Comment by enisoc** [comment]
cc @skriss @ethernetdan

**Comment by ethernetdan** [comment]
@enisoc what needs to be changed to fix this?

**Comment by enisoc** [comment]
@ethernetdan I think we could unblock the rest of the upgrade tests if we disable the new AppArmor test by commenting out [this line](https://github.com/kubernetes/kubernetes/blob/b0ce93f9be25c762fd4b746077fcda2aaa5b12bd/test/e2e/cluster_upgrade.go#L38). I don't know what would be the right way to fix it to only skip the AppArmor test if the environment is not compatible.

**Comment by skriss** [comment]
just to be clear this was merged after beta.3 so has not been affecting the release upgrade testing. but obviously this needs to be fixed.

**Comment by enisoc** [comment]
@skriss Which jobs do you mean by the "release upgrade testing"? The problem seems to be affecting jobs such as [ci-kubernetes-e2e-gce-1.5-1.6-upgrade-master](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.5-1.6-upgrade-master/18/?log#log):

```
I0313 22:29:11.739] S [SKIPPING] [1504.857 seconds]
I0313 22:29:11.739] [k8s.io] Upgrade [Feature:Upgrade]
I0313 22:29:11.739] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:650
I0313 22:29:11.740]   [k8s.io] master upgrade
I0313 22:29:11.740]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:650
I0313 22:29:11.740]     should maintain a functioning cluster [Feature:MasterUpgrade] [It]
I0313 22:29:11.740]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:68
I0313 22:29:11.740] 
I0313 22:29:11.740]     Mar 13 22:04:07.873: Only supported for node OS distro [gci ubuntu] (not debian)
I0313 22:29:11.740] 
I0313 22:29:11.740]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:283
I0313 22:29:11.740] ------------------------------
I0313 22:29:11.741] SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSMar 13 22:29:11.739: INFO: Running AfterSuite actions on all node
I0313 22:29:11.741] Mar 13 22:29:11.739: INFO: Running AfterSuite actions on node 1
[...]
I0313 22:29:28.832] Ran 0 of 579 Specs in 1612.266 seconds
I0313 22:29:28.838] SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 579 Skipped PASS
```

Note that this bug is in the e2e test binary, not in the actual Kubernetes release binaries.

**Comment by skriss** [comment]
hmm, seems like only the most recent runs are affected -- not sure I understand the timing there.

**Comment by ixdy** [comment]
@skriss the upgrade tests upgrade to the latest build on the `release-1.6` branch, which will be past beta.3 at this point.

**Comment by krousey** [comment]
It's worth noting that the upgrade and other tests actually do run, Ginkgo just marks the whole step as skipped.

From the same run @enisoc posted logs from:

```
I0313 22:14:22.266] Cluster validation succeeded
I0313 22:14:22.266] == Post-Upgrade Node OS and Kubelet Versions ==
I0313 22:14:22.465] name: "bootstrap-e2e-master", osImage: "Container-Optimized OS from Google", kubeletVersion: "v1.6.0-beta.3.63+5c6a7318a1b093"
I0313 22:14:22.466] name: "bootstrap-e2e-minion-group-0kjn", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.5.5-beta.0.8+76846d53fdb6f3"
I0313 22:14:22.466] name: "bootstrap-e2e-minion-group-gh90", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.5.5-beta.0.8+76846d53fdb6f3"
I0313 22:14:22.466] name: "bootstrap-e2e-minion-group-tgx4", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.5.5-beta.0.8+76846d53fdb6f3"
I0313 22:14:22.474] Mar 13 22:14:22.473: INFO: Checking master version
I0313 22:14:22.492] Mar 13 22:14:22.492: INFO: Master is at version 1.6.0-beta.3.63+5c6a7318a1b093
```

**Comment by skriss** [comment]
+ @timstclair 

Who's got this? Given that it is preventing the upgrade test from reporting results, I think we need to resolve for this release (ASAP).

**Comment by ethernetdan** [comment]
@enisoc are you working on a fix for this?

**Comment by krousey** [comment]
I'm working on a more comprehensive fix than #43158, but that should go in first to stop the bleeding.

**Comment by krousey** [comment]
My fix is actually ready for review now, https://github.com/kubernetes/kubernetes/pull/43089 and includes a StatefulSet version skip that's needed too.

**Comment by krousey** [comment]
https://github.com/kubernetes/kubernetes/pull/43089 has merged. As soon as it makes it to the 1.6 tag, this should be fixed.

**Comment by enisoc** [comment]
I will fast-forward release-1.6 now to pick it up.

**Comment by enisoc** [comment]
This appears to be "fixed" in the sense that the test is now failing rather than being marked as skipped:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.5-1.6-upgrade-master/23/?log#log
```
I0316 16:59:17.927] Summarizing 1 Failure:
I0316 16:59:17.927] 
I0316 16:59:17.927] [Panic!] [k8s.io] Upgrade [Feature:Upgrade] [k8s.io] master upgrade [It] should maintain a functioning cluster [Feature:MasterUpgrade] 
I0316 16:59:17.927] /usr/local/go/src/runtime/asm_amd64.s:479
I0316 16:59:17.927] 
I0316 16:59:17.927] Ran 1 of 581 Specs in 1510.891 seconds
I0316 16:59:17.964] FAIL! -- 0 Passed | 1 Failed | 0 Pending | 580 Skipped --- FAIL: TestE2E (1510.95s)
```

**Comment by krousey** [comment]
@enisoc @ixdy I mentioned this in slack, but fixed by https://github.com/kubernetes/kubernetes/pull/43254. My bad.
