### ISSUE TITLE
Node E2E tests have a stale TestContext.KubeletConfig

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#43111]
TestContext.KubeletConfig is set in a SynchronizedBeforeSuite block (https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/e2e_node_suite_test.go#L162), but this value may be stale if the config is modified by a test.

Tests where TestContext.KubeletConfig is used:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/mirror_pod_test.go#L47
https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/disk_eviction_test.go#L224
https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/pods_container_manager_test.go#L71

/cc @mtaufen @Random-Liu

**Comment by wgahnagl** [comment]
this still needs to be looked at
 
https://cs.k8s.io/?q=TestContext.KubeletConfig&i=nope&files=&excludeFiles=&repos=

**Comment by mtaufen** [comment]
@SergeyKanzhelev FYI wrt Dynamic Kubelet Config deprecation.

**Comment by SergeyKanzhelev** [comment]
/unassign

as I am not working on it now

**Comment by haitch** [comment]
this has been fixed on #117282, let's close this issue.

**Comment by aojea** [comment]
> this has been fixed on #117282, let's close this issue.

/close
