### ISSUE TITLE
why not we change controllers to controller  in the returned result that   `kubectl describe pod xxx`

### ISSUE THREAD

**Issue by zouyee** [kubernetes/kubernetes#43119]
why not we change controllers to controller  in the returned result that   `kubectl describe pod xxx`

kubectl describe po weave-flux-agent-3961180016-65dqt
Name:		weave-flux-agent-3961180016-65dqt
Namespace:	default
Node:		k8s-7/10.134.29.152
Start Time:	Wed, 08 Mar 2017 17:01:12 +0800
Labels:		app=weave-flux
		name=weave-flux-agent
		pod-template-hash=3961180016
		weave-cloud-component=flux
		weave-flux-component=agent
Status:		Running
IP:		10.233.68.5
**Controllers:**	ReplicaSet/weave-flux-agent-3961180016
Containers:

**Comment by adohe** [comment]
@zouyee this could be small UX improve, would you mind helping fixing this?

**Comment by xiangpengzhao** [comment]
Since `Controllers:` has already been modified to `Controlled By:`, it's okay to close this issue.
cc @zouyee @adohe
