### ISSUE TITLE
Some tests using testify/assert expect assertions to fail fast  

### ISSUE THREAD

**Issue by marun** [kubernetes/kubernetes#43121]
While investigating #41419, I noticed that the test panicked after an [assertion for a non-nil pointer had failed](https://github.com/kubernetes/kubernetes/blob/master/federation/pkg/federation-controller/configmap/configmap_controller_test.go#L155).  Looking at the source of testify's [assertion methods](https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/stretchr/testify/assert/assertions.go), I noticed that all of the methods [log an error](https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/stretchr/testify/assert/assertions.go#L185) rather than failing the test immediately.  Since most assertion mechanisms fail fast, it's understandable that test authors wouldn't expect this behavior, and there are many tests in the tree that assume incorrectly that assert will fail fast.

cc: @kubernetes/sig-testing-misc @kubernetes/sig-federation-misc

**Comment by ixdy** [comment]
Go's native `Fail` [doesn't abort execution](https://golang.org/pkg/testing/#B.Fail), requiring you to use `FailNow` instead, but I agree that it's unexpected behavior coming from other languages.

**Comment by MHBauer** [comment]
I did not know that the various `assert` methods are not fast failing. That does surprise me.

Some of the golang testing logging functions do abort. `Error` behaves like `Fail` and `Fatal` behaves like `FailNow`. Similarly, a `Fatal` log in `glog` calls `Exit()`.

**Comment by jayunit100** [comment]
I think Fatal is the convention we use for fail fast in kube, right ?

**Comment by yujuhong** [comment]
You should use `github.com/stretchr/testify/require` if you want to fail the test.

**Comment by nicksardo** [comment]
To shed more light, the `require` [package](https://godoc.org/github.com/stretchr/testify)  "implements the same assertions as the `assert` package but stops test execution when a test fails."
