### ISSUE TITLE
The output of `kubectl get pods -w` is not aligned as before

### ISSUE THREAD

**Issue by tatsuhiro-t** [kubernetes/kubernetes#43126]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-beta.3", GitCommit:"0cd5ed469508e6dfc807ee6681561c845828917e", GitTreeState:"clean", BuildDate:"2017-03-11T04:20:22Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

With kubectl version 1.6.0-beta.3, the output of `kubectl get pods` is not aligned:

```
$ kubectl get pods  -w
NAME                              READY     STATUS    RESTARTS   AGE
kube-controller-manager-core-01   1/1       Running   0          2m
kube-proxy-core-01   1/1       Running   0         2m
kube-proxy-core-02   1/1       Running   0         2m
kube-scheduler-core-01   1/1       Running   0         2m
```

**What you expected to happen**:

With kubectl version 1.5.4, the output is as follows:

```
$ kubectl get pods  -w
NAME                              READY     STATUS    RESTARTS   AGE
kube-controller-manager-core-01   1/1       Running   0          3m
kube-proxy-core-01                1/1       Running   0          3m
kube-proxy-core-02                1/1       Running   0          3m
kube-scheduler-core-01            1/1       Running   0          3m
```

**How to reproduce it** (as minimally and precisely as possible):

Run `kubectl get pods -w` using kubectl version 1.6.0-beta.3.

**Anything else we need to know**:

**Comment by shiywang** [comment]
will take a look

**Comment by bgrant0607** [comment]
@kubernetes/sig-cli-bugs

**Comment by adohe** [comment]
@shiywang any progress on this?

**Comment by shiywang** [comment]
hi, tony, sorry, I haven't look at this problem yet, maybe tomorrow, just really busy recent day, you can take it if you already find the problem, thanks

**Comment by xingzhou** [comment]
Happened to see the same issue on my laptop, @shiywang, I can help fix this issue if you do not have time, thx

**Comment by shiywang** [comment]
@xingzhou thanks, I been really busy this week, go ahead

**Comment by xingzhou** [comment]
@adohe, for this ticket, want to discuss one more thing with you:
at present, for each of the update event, `get` command with `--watch` option will print out a line showing the status change of this event. But this behavior is different with what we saw from the output of linux's `watch` command, which I think is not a very good user experience. For this kind of command, we shall reset all the old output and re-print all the pod's information in the standard output, this will make this command more like a real `watch` command.

do we have any plans on this right now? welcome your ideas on this.

**Comment by shiywang** [comment]
I think both output format has it's advantage, for current output format, user can copy paste the whole information like checking logs, for linux's `watch` command style output which user can stare on only one screen(if it's not too many pods or sth else).

**Comment by adohe** [comment]
@xingzhou yep, we do have plan to do this, and I really like a more linux style `watch` command, you can refer [http://linuxcommand.org/man_pages/watch1.html](http://linuxcommand.org/man_pages/watch1.html) for more detail. Anyway let's just get this fixed at first.

**Comment by lihan** [comment]
https://github.com/kubernetes/kubectl/issues/3
