### ISSUE TITLE
Introduce a kubefed flag to allow time outs

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#43123]
Today `kubefed` waits infinitely for its operations to complete. This is suboptimal. Our tests, for example, take about 15 hours before the overall timeout. Users probably face the same situation. We should introduce a hidden flag to allow time outs in tests for now and then promote it to a real flag and document it.

This is a sub-issue of issue #41725.

cc @kubernetes/sig-federation-feature-requests @csbell

**Comment by irfanurrehman** [comment]
@madhusudancs, does it make more sense to have the default behavior as time out at some time, which can be configured using this flag including some way to define try-forever?

**Comment by madhusudancs** [comment]
Yeah, changing the default to some fixed duration, although a longer one, in the future might be a good idea.

**Comment by irfanurrehman** [comment]
I somehow remember @perotinus taking this up earlier.
@perotinus do u have an open PR for this.. ? (could not find one).

**Comment by perotinus** [comment]
@irfanurrehman I don't think I have an open PR for this in particular, though you are correct that #42296 does add a default timeout for slower init operations. It shouldn't be too hard to make that configurable via flag in a future PR.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#118.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
