### ISSUE TITLE
PVC deletion causes PV status change to "Failed" instead of "Released"

### ISSUE THREAD

**Issue by akgunjal** [kubernetes/kubernetes#43138]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
PV delete status changed to "Failed"

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
**BUG**

**Kubernetes version** (use `kubectl version`):
1.5.3

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
I am using dynamic provisioner to provision my volumes. The create PVC creates the PV internally and binds to PVC. Now when I delete the PVC, the PV should also get deleted.

**What you expected to happen**:
The PVC deletion triggers dynamic provisioner to delete PV. The dynamic provisioner checks if the PV status is "Released" and only then proceeds to delete PV. This works sometimes but occassionally the PV status is "Failed" and hence it fails to delete.

**How to reproduce it** (as minimally and precisely as possible):
Use the an external provisioner (i.e NFS Example or create a new one...). Create PVC and then delete PVC. Check the status of PV immediately upon PVC deletion. The status of PV changes to "Failed". But this is not consistent and sometimes works.

**Anything else we need to know**:

**Comment by akgunjal** [comment]
Subscribing @xingzhou

**Comment by NickrenREN** [comment]
Maybe it is resolved in https://github.com/kubernetes-incubator/external-storage/issues/28
/close

**Comment by akgunjal** [comment]
@NickrenREN : Yes the issue is now resolved.
