### ISSUE TITLE
Upgrading cluster nodes running on GCI to 1.6 fails 

### ISSUE THREAD

**Issue by aleksandra-malinowska** [kubernetes/kubernetes#43139]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-beta.3", GitCommit:"0cd5ed469508e6dfc807ee6681561c845828917e", GitTreeState:"clean", BuildDate:"2017-03-11T04:09:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: gce
- **OS** (e.g. from /etc/os-release): 
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

Upgrading cluster nodes running on GCI to 1.6.0-beta.3 fails with:
cluster/gce/upgrade.sh: line 246: /usr/local/google/home/aleksandram/go/src/k8s.io/kubernetes/cluster/gce/cos/node-helper.sh: No such file or directory

**What you expected to happen**:
Nodes should be upgraded to 1.6 and running on GCI.

**How to reproduce it** (as minimally and precisely as possible):
$ git checkout v1.5.4
$ make clean && make quick-release
$ export KUBE_NODE_OS_DISTRIBUTION=gci
$ cluster/kube-up.sh
$ git checkout release-1.6
$ cluster/gce/upgrade.sh -M v1.6.0-beta.3
$ cluster/gce/upgrade.sh -N v1.6.0-beta.3

**Anything else we need to know**:

Upgrade script uses ID from node's /etc/os-release as a directory name, which is "cos" for GCI. However, "gci" is expected.

Possible solution: substitute "gci" if ID is "cos" (similar to cluster/gce/config-default.sh:53)?

**Comment by mtaufen** [comment]
I think just symlinking cluster/gce/cos to cluster/gce/gci would band-aid this and anything else that makes this mistake for now. We can focus on actually moving the scripts to cluster/gce/cos and reversing the direction of that symlink in 1.7 (minimally invasive changes for now).

**Comment by mtaufen** [comment]
I'll post a PR.

**Comment by mtaufen** [comment]
https://github.com/kubernetes/kubernetes/pull/43184 turns out this is untestable without cutting a release given the way upgrade.sh currently works. So someone will have to test after the PR merges and a beta is cut.
