### ISSUE TITLE
Upgrading nodes to 1.6 (Debian -> GCI) doesn't change OS

### ISSUE THREAD

**Issue by aleksandra-malinowska** [kubernetes/kubernetes#43146]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  BUG REPORT

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Nodes were upgraded to 1.6, but still on Debian.

**What you expected to happen**:
1.6 nodes running on GCI.

**How to reproduce it** (as minimally and precisely as possible):
$ git checkout v1.5.4
$ make clean && make quick-release
$  export KUBE_NODE_OS_DISTRIBUTION=debian
$ cluster/kube-up.sh
$ git checkout release-1.6
$ cluster/gce/upgrade.sh -M  v1.6.0-beta.3
$ export KUBE_NODE_OS_DISTRIBUTION=gci
$ cluster/gce/upgrade.sh -N  v1.6.0-beta.3

== Post-Upgrade Node OS and Kubelet Versions ==
name: "kubernetes-master", osImage: "Container-Optimized OS from Google", kubeletVersion: "v1.6.0-beta.3"
name: "kubernetes-minion-group-2rvw", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.6.0-beta.3"
name: "kubernetes-minion-group-3rkw", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.6.0-beta.3"
name: "kubernetes-minion-group-gtzf", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.6.0-beta.3"

**Anything else we need to know**:

Might be related to "gci" to "cos" name/id change?

**Comment by piosz** [comment]
cc @k8s-mirror-cluster-lifecycle-bugs

**Comment by piosz** [comment]
@ethernetdan this seems to be a release blocker

**Comment by mtaufen** [comment]
Don't you have to do another make quick-release to build the version you intend to upgrade to?

**Comment by mtaufen** [comment]
^^ ignore this I don't think it would cause this specific problem even if true, you've exported the relevant var.

**Comment by mtaufen** [comment]
Ah, I remember this. You need to also pass the -o flag to the upgrade script if you want it to use the os distro specified in KUBE_NODE_OS_DISTRIBUTION. Otherwise it will not change the OS.

**Comment by mtaufen** [comment]
https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/upgrade.sh#L41

**Comment by mtaufen** [comment]
@aleksandra-malinowska Please close this issue if passing -o fixes your problem. Thanks for helping with the upgrade tests :)

**Comment by aleksandra-malinowska** [comment]
It does, closing it now. Thanks!
