### ISSUE TITLE
certificate names for services in kubernetes

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/kubernetes#43142]
The background is, whenever we create a service `foo` in namespace `bar`.

1.  the name `foo` can be referenced by pods in namespace `bar` directly.
2.  the name `foo.bar` can be referenced by pods in other namespaces.

And in case `foo` exposes a https service, the `foo` service needs to present a certificate which has a common name and a list of subject alternate names, then the question arises: 

Should the certificate have all the names: `foo, foo.bar, foo.bar.svc, foo.bar.svc.domain`?

In more words, it seems we have to add all of them if we want all the names are working, however, I am just not convinced that it is a good way to go, because, generally, we have more than one cluster, and `foo` will be deployed in more than one of them, too, so the same name appears in different certificates which does not make much sense.

**Comment by puja108** [comment]
The `domain` part there usually can be the same even in different clusters, in most cases it's just `cluster.local`, but that depends on what tooling and configuration you're using to set the clusters up (or what your ops team or provider sets up for you).

**Comment by zhouhaibing089** [comment]
@puja108 well, it is ok to have the same domain, I am just confused at whether those short names like `foo, foo.bar` should be in the SANs..

**Comment by puja108** [comment]
Yes, most probably you'd need those, if you cannot control a single path on which they get accessed. If you can ensure that only ne (e.g. the FQDN) is used, you could just have that one in there.

My comment above was just that the problem you mention in the end might not be really a problem, if your clusters are similarly set up.

**Comment by zhouhaibing089** [comment]
@puja108 ah, if you are going to deploy a service, elasticsearch for example, don't you feel strange that the name `elasticsearch` be encoded into its certificate? after all, everyone can have an elasticsearch service. :)

**Comment by puja108** [comment]
True, it does feel strange. I'm not too deep into these things, but this should be usual if you're using DNS for internal Service Discovery, right? Not sure how other solutions solve this. But at least you can freely choose the CN and any other DN field like O or OU to distinguish uniquely.

**Comment by zhouhaibing089** [comment]
certificate CN and SAN must be fully qualified name.
