### ISSUE TITLE
kubectl 1.6 Deployment reaper doesn't work against 1.5 cluster

### ISSUE THREAD

**Issue by enisoc** [kubernetes/kubernetes#43159]
**Is this a request for help?**:

No.

**What keywords did you search in Kubernetes issues before filing this one?**:

* kubectl deployment
* deployment reaper
* delete deployment

---

**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.2.1799+355f576c0b24d6", GitCommit:"355f576c0b24d6395d1bbedbb4ba5f13a2821390", GitTreeState:"clean", BuildDate:"2017-03-15T18:54:51Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

Delete Deployment in 1.5 master with 1.6 kubectl. Its ReplicaSets were not deleted.

**What you expected to happen**:

The Deployment's ReplicaSets should be deleted.

**How to reproduce it** (as minimally and precisely as possible):

Use kubectl 1.6 against Kubernetes 1.5 master.

```sh
kubectl run nginx --image=nginx
kubectl delete deployment nginx
kubectl get rs
```

**Anything else we need to know**:

This issue is forked from https://github.com/kubernetes/kubernetes/issues/42738#issuecomment-285158244 because that issue was primarily just about an upgrade test and was mitigated separately.

This happens because the 1.6 code expects Deployments to apply ControllerRef to ReplicaSets they own, but 1.5 does not yet do that. According to #42392, we should maintain compatibility with +/-1 minor version for kubectl skew.

Some options from brainstorming:

1. Have kubectl 1.6 maintain the 1.5 behavior (don't check ControllerRef). It will do the wrong thing in the presence of overlapping selectors (i.e. *the user did something wrong*), both in 1.5 and 1.6 clusters.
2. Have kubectl 1.6 check ControllerRef. It will do the right thing in the presence of overlapping selectors in 1.6 clusters. It will do the wrong thing in 1.5 clusters even with no overlaps present (i.e. *the user did nothing wrong*). [current state at HEAD]
3. Have kubectl 1.6 behave differently based on the cluster version it's talking to. There appears to be no precedent for this in kubectl.
4. Have kubectl 1.6 implement some fallback behavior (perhaps involving created-by annotation?) that would work in both 1.5 and 1.6 clusters.

cc @erictune @janetkuo @kargakis @kubernetes/sig-cli-bugs @kubernetes/sig-apps-bugs

**Comment by kargakis** [comment]
If we end up doing something about this, I would go with 1 as it seems the most sensible thing for now. Low risk plus overlapping selectors are a user error anyway.

**Comment by janetkuo** [comment]
Maybe we can use discovery code in 1.6 kubectl to check server version, and use pre-1.6 or 1.6 reaper based on that?

```go
clientset.Discovery().ServerVersion()
```

**Comment by ymqytw** [comment]
> For option 3, we can use discovery code in 1.6 kubectl to check server version, and use pre-1.6 or 1.6 reaper based on that.

From https://github.com/kubernetes/kubernetes/pull/35647#pullrequestreview-8290820, it may not be safe when there are aggregated API servers

**Comment by janetkuo** [comment]
> From https://github.com/kubernetes/kubernetes/pull/35647#pullrequestreview-8290820, it may not be safe when there are aggregated API servers

Hmm, does that make the discovery code we used in `kubectl run` unsafe too? @soltysh

**Comment by bgrant0607** [comment]
I agree with @kargakis. Kubectl shouldn't be depending on controllerRef.

I don't think we should ever rely on release numbers to infer anything.

**Comment by soltysh** [comment]
> Hmm, does that make the discovery code we used in kubectl run unsafe too? @soltysh

We should be safe, because in `kubectl run` we get the list of resources the server has and do actions based on that, we don't rely on something being present in version x.y.z. Cluster operator can disable certain resources and `kubectl run` will react appropriately to these changes.

**Comment by soltysh** [comment]
👍 for not relying on controllerRef, as well.

**Comment by adohe** [comment]
Generally this is kind of impact we will have when we move more client side logical to server side, with old version kubectl, we will rely on client side to do cascade deletion, but with new version api-server, the garbage component will do this job, keep the newer version kubectl maintain the older behavior is something we need to make sure afaik.

**Comment by enisoc** [comment]
I think we have consensus on Option 1. I will work on reverting kubectl to the 1.5 behavior with respect to ControllerRef.

**Comment by enisoc** [comment]
@pwittrock suggested that I retry the manual repro steps with a freshly built kubectl now that the fix has merged.

It looks good:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.2.1892+4b00d5e42a4bfd", GitCommit:"4b00d5e42a4bfdcecf061b018911cbdeeac1d9f3", GitTreeState:"clean", BuildDate:"2017-03-17T23:07:26Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
$ kubectl run nginx --image=nginx
deployment "nginx" created
$ kubectl get rs
NAME              DESIRED   CURRENT   READY     AGE
nginx-701339712   1         1         1         12s
$ kubectl delete deployment nginx
deployment "nginx" deleted
$ kubectl get rs
No resources found.
```
