### ISSUE TITLE
[Federation] ClustersSynced(clusters [] *federationapi.Clusters) documentation doesn't seem to match the implementation

### ISSUE THREAD

**Issue by perotinus** [kubernetes/kubernetes#43169]
It appears that there is a bit of an impedance mismatch between how the FederatedInformer discusses ClustersSynced(clusters [] *federationapi.Clusters) and the actual implementation of that method. Conceptually, the idea of ClustersSynced(clusters [] *federationapi.Clusters) seems to be to provide an ongoing update of whether the Federated store is synchronized with the underlying clusters' stores. In practice, it does this by checking the HasSynced() method on each of the clusters' informers. HasSynced() only promises to return whether, at some point in the past, the informer was synced, and from the implementation it appears that it does this by checking that the queue has been populated with some Add/Update/Delete operations, or was populated with some Replace operations that completed. Interestingly, if there is an in-flight Add, Update or Delete operation, HasSynced() appears to return true before that operation has completed.

So, ClustersSynced(clusters [] *federationapi.Clusters) doesn't quite provide the depth of information that it implies in its name and its documentation. Note that the ClustersSynced() method on FederationView does note this in the comment.

It may be worth renaming these to HaveClustersBeenSynced() or some such to make it clear that they do not provide information about the current sync state, but only that at some point they were synced (or at some point were slated to be synced, which seems to be the promise that is provided).jk

Someone else may want to look into this code to corroborate these findings.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#119.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
