### ISSUE TITLE
kubectl reporting wrong for taints.

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#43167]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.3.1185+7e37b895d7c1e9-dirty
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.3.1185+7e37b895d7c1e9-dirty"

**What happened**:
Kubectl is always reporting as node <XYZ> is tainted irrespective of operation when used with local cluster.
./kubectl.sh taint nodes XYZ dedicated-

node "XYZ" **tainted**

**What you expected to happen**:
It should have shown exact operation like tainted, untainted modified and overwritten but because of https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/taint.go#L343. it is always returning tainted.

**How to reproduce it** (as minimally and precisely as possible):
./kubectl.sh taint nodes XYZ dedicated-

**Comment by davidopp** [comment]
cc/ @kubernetes/sig-scheduling-bugs

**Comment by aveshagarwal** [comment]
@jayunit100 Regarding https://github.com/kubernetes/kubernetes/pull/43171#issuecomment-290496542
Yes I agree we should provide more clearer output/feedback. But providing something that makes output more confusing than existing is something would be even more concerning.

So as I stated https://github.com/kubernetes/kubernetes/pull/43171#issuecomment-290476080, it would be good to discuss/decide how the output/feedback should like for various operations for one and multi nodes scenarios.

**Comment by jayunit100** [comment]
@davidopp @aveshagarwal I think having > 1 return values is an exponential improvement on what we have now, even if they aren't perfect for all cases.  Rather then a disproportionately long debate over a relatively simple improvement....  How about we Suggest something simple that you're confident it will be easy to agree on,  and we can implement it as a first pass  ?

**Comment by davidopp** [comment]
I think we'd be happy to consider any reasonable PR. I'm not sure why #43614 was closed; I didn't look at it though so I don't know if it solves the problem.

**Comment by davidopp** [comment]
(hit close accidentally)

**Comment by ravisantoshgudimetla** [comment]
@davidopp , I am not sure why #43614 was closed. But I raised a PR which was around 15 days ago(#43171).
