### ISSUE TITLE
Documentation for setting up kube-dns is woefully inadequate.

### ISSUE THREAD

**Issue by mcronce** [kubernetes/kubernetes#43179]
I doubt anybody will get any value out of the template for a documentation issue, but just in case, here it is.

**Kubernetes version**:
`Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-18T10:52:03Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-18T10:52:03Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Cloud provider or hardware configuration**:  On-prem, single box (for now), i5-4570T, 16GB RAM, 256GB SSD setup with LVM.  Docker's devicemapper setup to utilize LVM.
- **OS** (e.g. from /etc/os-release):  `PRETTY_NAME="Fedora 25 (Server Edition)"`
- **Kernel** (e.g. `uname -a`):  Linux virt02.home.quadra-tec.net 4.9.13-201.fc25.x86_64 #1 SMP Tue Mar 7 23:47:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:  I don't know what this means.  `dnf`?
- **Others**:

**What happened**:
I am trying to set up kube-dns.  I've spent two days looking through swathes of Kubernetes docs and Googling, and I am _still_ unable to do so.  I _think_ I've finally arrived at kube-dns being unable to authenticate with kube-apiserver, but there is no documentation about passing any kind of token, credentials, or other secret to the kube-dns pod.  I doubt that hardcoding a secret into my ReplicationController definition file is the way to go.

I'd love to deploy it using the addon manager, but the documentation for that [appears to be build instructions](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/README.md) and doesn't give so much as a _hint_ about deploying it.

**What you expected to happen**:
I expect configuration and usage of these tools to be well-documented.

**How to reproduce it** (as minimally and precisely as possible):
Try to setup Kubernetes on Fedora 25, following the [install guide](https://kubernetes.io/docs/getting-started-guides/fedora/fedora_manual_config/), with kube-dns - the only useful documentation for which I was able to find [on the CoreOS website](https://coreos.com/kubernetes/docs/latest/deploy-addons.html#deploy-the-dns-add-on)

**Anything else we need to know**:
I can include log messages or other information, if desired, but I'm not really here for troubleshooting help, I'm here to report documentation issues.

**Comment by aukan** [comment]
+1

**Comment by fatih** [comment]
I agree that there is zero information about installing kube-dns. Nada. The kube-dns addon has bunch of `.base`, `.sed` files with no explanation how to use and install them.

**Comment by mickael-carl** [comment]
I just hit this as well. When trying to setup kubedns, there is indeed litterally no docs whatsoever, except for that kube-dns addon readme file. A quick set of instructions on how the provided template files need to be modified to end up in a state where kubedns is actually working would be a great improvement.
