### ISSUE TITLE
OIDC: kubectl should allow for custom scopes

### ISSUE THREAD

**Issue by Calpicow** [kubernetes/kubernetes#43172]
When kubectl refreshes tokens, it sets the scope to `openid email profile`. This breaks group-based authentication once the token is renewed.

The scope parameter should be removed when refreshing tokens, allowing the IDP to decide which scope to use (should be the scope the initial token was created with), or allow the scopes be configurable via kubeconfig.

cc: @ericchiang this might be relevant to you

**Comment by ericchiang** [comment]
@Calpicow dup of https://github.com/kubernetes/kubernetes/issues/37875 ?

**Comment by Calpicow** [comment]
Thanks. Closing this one.
