### ISSUE TITLE
cloudprovider.GetLoadBalancerName() should be per-provider

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#43173]
Right now this function tries to be neutral to providers, and as such is probably worse than any of them need.

On GCE, at least, it truncates the UUID unnecessarily.

@kubernetes/sig-network-bugs

**Comment by thockin** [comment]
This is an easy one to fix, I think, and could make a good first contribution.

**Comment by jakon89** [comment]
What about backward compatibility? Shouldn't new version of `GetLoadBalancerName()` (per provider) return old-style names for all existing resources?

For example `gce.UpdateLoadBalancer()` uses `cloudprovider.GetLoadBalancerName()` to get instance of target pool. What will happen if it gets value generated by new implementation?

**Comment by thockin** [comment]
Need to think that through.  Maybe return new and old, see what the impact
on QPS is, maybe store an annotation indicating which is in use, something.

**Comment by thockin** [comment]
You're right that it's not as easy as I implied, sorry.

**Comment by abdasgupta** [comment]
Hi @thockin 
Are we still following this issue? I want to start my contribution in kubernetes. I am interested on this issue. As a solution I can propose if we could use EnsureLoadBalancer() everytime before we call GetLoadBalancerName() for backward compatibility. Is it possible? Anything I am missing?

**Comment by thockin** [comment]
I would probably start by adding an annotation to Services that indicates
the LB name being used.  The compat issue is real, and if you take this
issue on you'll need to consider all the corner cases..


On Wed, Apr 5, 2017 at 12:06 AM, Abhishek Dasgupta <notifications@github.com

**Comment by abdasgupta** [comment]
Sure @thockin,  I would like to take this issue. But before that, how the cloudprovider code is tested? Shall I add more unit tests? Or is there any other way we can test out the corner cases? Appreciate the help.
Thanks!

**Comment by thockin** [comment]
Much of the provider code is tested by e2e on the actual providers.
Sending a PR will allow tests to run on GCP and we can get help on others.

**Comment by abdasgupta** [comment]
Added a PR regarding this : https://github.com/kubernetes/kubernetes/pull/44333

@thockin will you help me to test this? I would remove "[WIP]" once I am satisfied with the PR. Would like to see comments on how to improve this PR.

**Comment by andrewsykim** [comment]
My take on this is to move `cloudprovider.GetLoadBalancerName()` as a provider-specific method, have existing providers use the current naming scheme (service UUID) and once providers go out-of-tree have them deal with transitioning to use better names. Thoughts?

**Comment by andrewsykim** [comment]
This also gives each provider flexibility on how to transition (annotations vs labels, etc)

**Comment by nckturner** [comment]
@andrewsykim that method seems reasonable to me.  It is certainly something we'd like to see customizable!
