### ISSUE TITLE
Should maintain a functioning cluster upgrade step gets stuck

### ISSUE THREAD

**Issue by ethernetdan** [kubernetes/kubernetes#43187]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version** (use `kubectl version`):
Upgrades to 1.6

**What happened**:
When running tests for upgrades to 1.6 the step ` [It] should maintain a functioning cluster [Feature:MasterUpgrade]` blocks until the test-infra job times out and sends an interrupt.

Last line before timing out: `L7 controller failed to delete all cloud resources on time. timed out waiting for the condition`
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1.5-gci-1.6-upgrade-master/27?log#log

**What you expected to happen**:
Should either pass test or timeout failing the test gracefully.

**How to reproduce it** (as minimally and precisely as possible):
Any master test in https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew

**Comment by ethernetdan** [comment]
Last line before timing out: `L7 controller failed to delete all cloud resources on time. timed out waiting for the condition`

**Comment by skriss** [comment]
I believe this is a flake, I saw it once or twice at the beginning of testing but it was not consistent. Note that it seems the underlying cause for master upgrade test jobs timing out is #43228 which I just filed

**Comment by ethernetdan** [comment]
Good to know, thanks @skriss. Moving from milestone.

**Comment by skriss** [comment]
@nicksardo can you take a look at this? I'm not sure why the test job is just hanging immediately after logging "L7 controller failed to delete all cloud resources on time. timed out waiting for the condition". Seems to be happening frequently in the last couple days.

**Comment by skriss** [comment]
@ethernetdan let's wait until @nicksardo looks, he has recently done some work with the ingress tests so might be able to address.

**Comment by nicksardo** [comment]
It's normal for the ingress test to occasionally run for 15-16 minutes.  There's a known race with the ingress resource being deleted before the GLBC is fully running.

I don't know why the test is hanging after that log message.  That message is the final action before returning from `Teardown`.  I pushed a PR a few days ago that changed that `Failf` call to a `Logf` to ignore the fact the GLBC can't cleanup the gce resources, but neither could block the test indefinitely. 

Is it possible any test running for ~16 minutes indirectly causes the whole job to block?

**Comment by ethernetdan** [comment]
I was talking to @ixdy about this the other day and we were thinking that the ingress test exits successfully but theres another test in the MasterUpgrade suite is blocking. 

Could potentially be related to AppArmor tests as they were recently added. This could be checked this by looking to see if this failure occurs on non-GCI runs because the AppArmor tests should be disabled there.

**Comment by skriss** [comment]
@krousey this test run is showing a similar hanging behavior - any idea what could be going on here?

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-latest-upgrade-master/569?log#log

I0317 09:51:19.754] Mar 17 09:51:19.753: INFO: Successfully deleted PD "bootstrap-e2e-bbe49362-0b2f-11e7-abc7-0242ac110003".
W0317 10:56:12.803] 2017/03/17 10:56:12 util.go:132: Interrupt testing after 1h30m0s timeout. Will terminate in another 15m

**Comment by skriss** [comment]
@jszczepkowski 

What i'm seeing in both of the linked logs above is that after the upgrade, the last line logged from the HPA upgrade test is 

INFO: RC res-cons-upgrade: consume 250 millicores in total

And then nothing. @jszczepkowski can you check this out?

**Comment by ethernetdan** [comment]
> I0317 09:51:19.754] Mar 17 09:51:19.753: INFO: Successfully deleted PD "bootstrap-e2e-bbe49362-0b2f-11e7-abc7-0242ac110003".
> W0317 10:56:12.803] 2017/03/17 10:56:12 util.go:132: Interrupt testing after 1h30m0s timeout. Will terminate in another 15m
That timeout is also much lower than the other upgrade tests - not sure if related

**Comment by krousey** [comment]
Other upgrade tests run a serial suite e2e after the upgrade. Upgrades and upgrade tests that succeed or fail without freezing typically finish in about 45-50 minutes.

**Comment by krousey** [comment]
Without the HPA tests, they finish within 30 minutes. HPA has a lot of long timers.

**Comment by skriss** [comment]
Checked a 3rd run, it's the same HPA log pattern. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1.5-gci-1.6-upgrade-master/27?log#log

Seems like autoscaling_utils.go line 147 send is blocking, but I don't see why.

**Comment by skriss** [comment]
@jszczepkowski have you been able to look at this?

**Comment by ethernetdan** [comment]
This seems to be a flake but we should try to address it for 1.6.1 to improve upgrade signal, moving milestones.

**Comment by jszczepkowski** [comment]
@skriss 
Sorry, I missed the first notification.

The problem is in the resource consumer library:
* call to `ConsumeCPU` blocks forever (autoscaling_utils.go:147) as no one is listening on `rc.cpu` channel,
* go-routine `makeConsumeCPURequests()` is not listening on `rc.cpu` channel as it dies calling `sendConsumeCPURequest()` method:
```
I0317 09:44:48.679] Mar 17 09:44:48.678: INFO: URL: {https  <nil> 35.188.30.25 /api/v1/namespaces/e2e-tests-hpa-upgrade-9fphf/services/res-cons-upgrade-ctrl/proxy/ConsumeCPU  false durationSec=30&millicores=10&requestSizeMillicores=20 }
...
I0317 09:44:48.735] Mar 17 09:44:48.735: INFO: Unexpected error occurred: an error on the server ("Error: 'No SSH tunnels currently open. Were the targets able to accept an ssh-key for user \"gke-987d5633a164b5d642be\"?'\nTrying to reach: 'http://10.72.2.10:8080/ConsumeCPU?durationSec=30&millicores=10&requestSizeMillicores=20'") has prevented the request from succeeding (post services res-cons-upgrade-ctrl)
```
* service `res-cons-upgrade-ctrl` seems to be unavailable for a while immediately after upgrade.

The resource consumer library should be fixed by retrying `res-cons-upgrade-ctrl` service calls on errors (methods `sendConsumeCPURequest`, `sendConsumeMemRequest` and `sendConsumeCustomMetric`).

**Comment by jszczepkowski** [comment]
CC @DirectXMan12

**Comment by ethernetdan** [comment]
@skriss @krousey judging from overnight runs I don't think this is fixed

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1.4-gci-1.6-upgrade-master/60

**Comment by ethernetdan** [comment]
Could we change the ordering to at least allow skew to run?

**Comment by skriss** [comment]
@jszczepkowski can you check this out? Looks like most (but not all) master upgrades on GKE failed on this (they were all restarted around 4pm PST yesterday). In the couple that succeeded (e.g. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.5-gci-1.6-upgrade-master/53) it looks like the retry worked correctly.

**Comment by krousey** [comment]
No. If the upgrade doesn't happen first, then the skew doesn't exist.

If there are specific upgrade tests that are causing the issue, we can
disable them if someone tests them by hand.

**Comment by ethernetdan** [comment]
Every master failure had the `No SSH tunnels currently open.` error message in it and all of the successes did not so they are definitely correlated. 

Unless we have other theories on this, I'd say we disable HPA upgrade. 
Can someone put in a PR for this? I can after the community meeting if no one does.

**Comment by ethernetdan** [comment]
Nevermind just put it in.
@skriss & @krousey WDYT?

**Comment by skriss** [comment]
lgtm

**Comment by ethernetdan** [comment]
Looks like the issue with timeouts is resolved but we are still seeing upgrade failures. I'll close this issue and have opened #43610 & #43611 & #43612.
