### ISSUE TITLE
gke-multizone, gke-non-cri tests fail SimplePod, Loadbalancing, PreStop tests

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#43198]
These three tests have been failing since Mar 9 (with 3 passes on Mar 11?!):
* [k8s.io] Kubectl client [k8s.io] Simple pod should handle in-cluster config
* [k8s.io] Loadbalancing: L7 [k8s.io] Nginx should conform to Ingress spec
* [k8s.io] PreStop should call prestop when killing a pod [Conformance]

https://k8s-testgrid.appspot.com/google-non-cri#gke-multizone&width=5&sort-by-failures=

/assign @madhusudancs @justinsb

**Comment by fejta** [comment]
/assign @roberthbailey 

Actually these same jobs are also failing on non-cri-gke:

https://k8s-testgrid.appspot.com/google-non-cri#gke&width=20&sort-by-failures=

**Comment by ethernetdan** [comment]
@roberthbailey PTAL, this is release blocking

**Comment by fejta** [comment]
Here's a go.k8s.io/triage tool link that focuses on these three tests across all jobs:

https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Simple%20pod%20should%20handle%20in-cluster%20config%7CNginx%20should%20conform%20to%20Ingress%20spec%7CPreStop%20should%20call%20prestop%20when%20killing%20a%20pod

It shows that this seems specific to GKE -- 44-298 failures on GKE envs vs 1-3 failures on GCE/AWS

**Comment by roberthbailey** [comment]
I have a possible root cause in gke, investigating further.

**Comment by roberthbailey** [comment]
I need @yujuhong or @Random-Liu to give me owners access to a gcp project so I can fix the underlying issue.

**Comment by yujuhong** [comment]
@roberthbailey I followed your instructions in the email thread and also added you as the owner of both `*-cri*` gke projects. Let me know if there is anything else I should do. Thanks!

**Comment by roberthbailey** [comment]
I re-rand the script and on the latest run we seem to have fixed the three tests that have been broken. There is still one test failing (`Cluster level logging using GCL should check that logs from containers are ingested in GCL`) which needs further investigation.

**Comment by roberthbailey** [comment]
It looks it was a new test added around 3/20 and has never passed in this test suite.

**Comment by roberthbailey** [comment]
The break was from https://github.com/kubernetes/kubernetes/pull/43294 which merged 8 hours ago. It removed the [flaky] text from this test, even though it appears to be permanently broken (not just flaky) on GKE.

**Comment by roberthbailey** [comment]
Since the remaining test is broken on all 1.6 gke test suites (e.g. https://k8s-testgrid.appspot.com/release-1.6-blocking#gke-1.6) I'm going to mark this issue as resolved.
