### ISSUE TITLE
Add back tests for annotation-based affinity

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#43197]
Somehow I overlooked the fact that #41617 did not add back all the tests for annotation-based affinity that were converted to use fields in #37299 and #39478. This is pretty bad because we are supposed to be supporting annotation-based affinity in addition to field-based affinity (that was the reason for #41617).

For e2e this requires setting up a separate Jenkins job that enables annotation-based affinity. (See kubernetes/test-infra#1947 kubernetes/test-infra#2089 kubernetes/test-infra#2187 for an example.)

It would be great if someone could volunteer to do this ASAP. It is a very mechanical change -- just find all the tests that were converted to use fields in #37299 and #39478 but whose annotation-based versions were not added back in #41617, and add back the annotation-based versions of them.

We can separate the task of adding back the tests, and the task of setting up the Jenkins job.

cc/ @rrati @timothysc @kubernetes/sig-scheduling-bugs 

ref/ #42614

**Comment by timothysc** [comment]
@davidopp you mean e2es?  The UTs should have all been updated.  

The reason straight up e2es weren't converted was b/c it leverages the same code.  There was a judicious change to isolate the up-convert to just the scheduler.  

Could you elaborate on what tests you think are missing.

**Comment by davidopp** [comment]
Yes the ones I noticed was the e2e's but I wasn't sure if there were others.

**Comment by k82cn** [comment]
As @timothysc said, the e2e used field, and UT includes both annotation & fields. Anything we need to add back?

**Comment by timothysc** [comment]
> Anything we need to add back?

I don't think so... re:  https://github.com/kubernetes/kubernetes/issues/43197#issuecomment-287065996

**Comment by calebamiles** [comment]
so can this issue be closed @timstclair, @davidopp?

**cc: @ethernetdan, @kubernetes/kubernetes-release-managers**

**Comment by grodrigues3** [comment]
if this is a non release blocker can we remove from the milestone?

**Comment by timothysc** [comment]
Let's leave this open until @davidopp has time to think about it.  In the mean time, I've update the milestone to 1.7.

**Comment by davidopp** [comment]
I wonder if this would have caught the "we shouldn't have removed validation of the affinity annotations" bug in a more obvious way

**Comment by timothysc** [comment]
Well hind-sight is 20-20 on that.  I think we blazed a new trail and exposed some weird testing scenarios I was not aware of.

**Comment by davidopp** [comment]
I just meant maybe this is still worth doing, there might be bugs in the alpha path that we don't know about.

**Comment by k82cn** [comment]
double check the NodeAffinity and InterPodAffintiy, the unit test case for both annotation & fields are there. 

> For e2e this requires setting up a separate Jenkins job that enables annotation-based affinity. (See kubernetes/test-infra#1947 kubernetes/test-infra#2089 kubernetes/test-infra#2187 for an example.)

Agree with timothysc@ that e2e used the same code for both annotation & fields, the only different is to marshal/unmarshal annotation/field. Do you need to add that back?

**Comment by timothysc** [comment]
I'm inclined to close this, and aim to rip out the feature gated alpha work in 1.8

**Comment by timothysc** [comment]
Rip is here - https://github.com/kubernetes/kubernetes/pull/47869 

Closing.
