### ISSUE TITLE
context was not found for specified context: e2e-federation

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#43196]
/assign @madhusudancs 

https://k8s-testgrid.appspot.com/google-federation#soak-gce-test

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e_federation/framework/framework.go:61
Expected error:
    <*errors.errorString | 0xc420adb810>: {
        s: "error creating federation default client config: invalid configuration: [context was not found for specified context: e2e-federation, default cluster has no server defined]",
    }
    error creating federation default client config: invalid configuration: [context was not found for specified context: e2e-federation, default cluster has no server defined]
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e_federation/framework/framework.go:74
```

https://storage.googleapis.com/k8s-gubernator/triage/index.html#64a5376e3c52e64bb4b3
![fed](https://cloud.githubusercontent.com/assets/940341/23983394/1bdde0a8-09d1-11e7-8065-31d15719d134.png)

**Comment by madhusudancs** [comment]
@shashidharatd can you take a look?

**Comment by ethernetdan** [comment]
@shashidharatd what is the status of this?

**Comment by madhusudancs** [comment]
@ethernetdan this is not a 1.6 blocker.

**Comment by shashidharatd** [comment]
i will check and fix this issue soon.

**Comment by shashidharatd** [comment]
This issue is sorted out and fixed by multiple PR's. Here is the status of the CI job. https://k8s-testgrid.appspot.com/cluster-federation#soak-gce-test
We can close this issue.
/close
