### ISSUE TITLE
why  serviceController run nodeSyncLoop every nodeSyncPeriod ？

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#43201]
I think its better if it run like service loop, always run when workingQueue is not empty

**Comment by hpejustin** [comment]
I think you mean why we need two loop(service and node), other than one loop, am i right? According to view, service loop focus on service update(deal with load balancer etc.) and node loop deal with hosts which has relation to service. Two loops can make it much more clear.

**Comment by hzxuzhonghu** [comment]
`go wait.Until(s.nodeSyncLoop, nodeSyncPeriod, wait.NeverStop)
func (s *ServiceController) nodeSyncLoop() {}`

I mean function nodeSyncLoop only run once every nodeSyncPeriod. Not like service run a for loop, which can deal with resource change more rt 

`func (s *ServiceController) worker() {
	for {
		func() {
			key, quit := s.workingQueue.Get()
			if quit {
				return
			}
			defer s.workingQueue.Done(key)
			err := s.syncService(key.(string))
			if err != nil {
				glog.Errorf("Error syncing service: %v", err)
			}
		}()
	}
}`

**Comment by hzxuzhonghu** [comment]
@hpejustin I mean  when  node update,  servcie controller watch this event, but may process this after nodeSyncPeriod  time.  It works like a long poll loop of a period.
