### ISSUE TITLE
empty array fields change to null when storing as protobuf

### ISSUE THREAD

**Issue by cduchesne** [kubernetes/kubernetes#43203]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): subsets null

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Kubernetes version** (use `kubectl version`): 1.6.0 beta3

**Environment**:
- **Cloud provider or hardware configuration**: local environment
- **OS** (e.g. from /etc/os-release): CentOS 7.3
- **Kernel** (e.g. `uname -a`): 3.10.0-514.6.1.el7.x86_64
- **Install tools**: manual
- **Others**:

**What happened**: Starting with Kubernetes 1.6.0 the /api/v1/endpoints endpoint returns subsets as a null value instead of an empty list when there are no values to show.
example from 1.6
```
{
      "metadata": {
        "name": "kube-controller-manager",
        "namespace": "kube-system",
        "selfLink": "/api/v1/namespaces/kube-system/endpoints/kube-controller-manager",
        "uid": "0fa97080-06b3-11e7-86c2-0237b2d87d14",
        "resourceVersion": "536232",
        "creationTimestamp": "2017-03-11T23:32:58Z",
        "annotations": {
          "control-plane.alpha.kubernetes.io/leader": "{\"holderIdentity\":\"k8s\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2017-03-11T23:32:58Z\",\"renewTime\":\"2017-03-16T03:48:58Z\",\"leaderTransitions\":0}"
        }
      },
      "subsets": null
},
```

**What you expected to happen**: In Kubernetes before 1.6, response would show like below:
```
{
    "metadata": {
        "name": "kube-controller-manager",
        "namespace": "kube-system",
        "selfLink": "/api/v1/namespaces/kube-system/endpoints/kube-controller-manager",
        "uid": "39d5f51a-05fb-11e7-be44-0237b2d87d14",
        "resourceVersion": "75186",
        "creationTimestamp": "2017-03-11T01:37:02Z",
        "annotations": {
            "control-plane.alpha.kubernetes.io/leader": "{\"holderIdentity\":\"k8s\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2017-03-11T01:37:02Z\",\"renewTime\":\"2017-03-11T16:26:04Z\",\"leaderTransitions\":0}"
        }
        },
        "subsets": []
}
```

**How to reproduce it** (as minimally and precisely as possible):
Simply hit api endpoint @ http://kube-apiserver:8080/api/v1/endpoints

**Anything else we need to know**:

**Comment by liggitt** [comment]
needs to be triaged for 1.6 in case this is an API breakage

**Comment by liggitt** [comment]
looks like an issue with proto storing `[]` vs `null`

if I start the server with `--storage-media-type=protobuf`, I cannot persist a `subsets: []` (editing and trying to save that always returns null when I refetch the endpoint

if I start the server with `--storage-media-type=application/json`, subsets persist with and return as `[]`

cc @smarterclayton

**Comment by smarterclayton** [comment]
this is easy to fix

**Comment by liggitt** [comment]
These are the array fields that do not set `omitempty`, and currently can distinguish between, store, and return `null` and `[]`:

```
$ find . -name types.go | grep /v | grep -v vendor | xargs grep -E '\[\].*protobuf' | grep -v omitempty | grep -v Items | grep -v client-go | grep -v staging | grep -v '\[\]byte'
./federation/apis/federation/v1beta1/types.go:	ServerAddressByClientCIDRs []ServerAddressByClientCIDR `json:"serverAddressByClientCIDRs" patchStrategy:"merge" patchMergeKey:"clientCIDR" protobuf:"bytes,1,rep,name=serverAddressByClientCIDRs"`
./pkg/api/v1/types.go:	CephMonitors []string `json:"monitors" protobuf:"bytes,1,rep,name=monitors"`
./pkg/api/v1/types.go:	Monitors []string `json:"monitors" protobuf:"bytes,1,rep,name=monitors"`
./pkg/api/v1/types.go:	TargetWWNs []string `json:"targetWWNs" protobuf:"bytes,1,rep,name=targetWWNs"`
./pkg/api/v1/types.go:	Sources []VolumeProjection `json:"sources" protobuf:"bytes,1,rep,name=sources"`
./pkg/api/v1/types.go:	NodeSelectorTerms []NodeSelectorTerm `json:"nodeSelectorTerms" protobuf:"bytes,1,rep,name=nodeSelectorTerms"`
./pkg/api/v1/types.go:	MatchExpressions []NodeSelectorRequirement `json:"matchExpressions" protobuf:"bytes,1,rep,name=matchExpressions"`
./pkg/api/v1/types.go:	Namespaces []string `json:"namespaces" protobuf:"bytes,2,rep,name=namespaces"`
./pkg/api/v1/types.go:	Containers []Container `json:"containers" patchStrategy:"merge" patchMergeKey:"name" protobuf:"bytes,2,rep,name=containers"`
./pkg/api/v1/types.go:	Subsets []EndpointSubset `json:"subsets" protobuf:"bytes,2,rep,name=subsets"`
./pkg/api/v1/types.go:	Names []string `json:"names" protobuf:"bytes,1,rep,name=names"`
./pkg/api/v1/types.go:	Command []string `json:"command" protobuf:"bytes,6,rep,name=command"`
./pkg/api/v1/types.go:	Limits []LimitRangeItem `json:"limits" protobuf:"bytes,1,rep,name=limits"`
./pkg/apis/autoscaling/v2alpha1/types.go:	CurrentMetrics []MetricStatus `json:"currentMetrics" protobuf:"bytes,5,rep,name=currentMetrics"`
./pkg/apis/extensions/v1beta1/types.go:	Paths []HTTPIngressPath `json:"paths" protobuf:"bytes,1,rep,name=paths"`
./pkg/apis/rbac/v1alpha1/types.go:	Verbs []string `json:"verbs" protobuf:"bytes,1,rep,name=verbs"`
./pkg/apis/rbac/v1alpha1/types.go:	Rules []PolicyRule `json:"rules" protobuf:"bytes,2,rep,name=rules"`
./pkg/apis/rbac/v1alpha1/types.go:	Subjects []Subject `json:"subjects" protobuf:"bytes,2,rep,name=subjects"`
./pkg/apis/rbac/v1alpha1/types.go:	Rules []PolicyRule `json:"rules" protobuf:"bytes,2,rep,name=rules"`
./pkg/apis/rbac/v1alpha1/types.go:	Subjects []Subject `json:"subjects" protobuf:"bytes,2,rep,name=subjects"`
./pkg/apis/rbac/v1beta1/types.go:	Verbs []string `json:"verbs" protobuf:"bytes,1,rep,name=verbs"`
./pkg/apis/rbac/v1beta1/types.go:	Rules []PolicyRule `json:"rules" protobuf:"bytes,2,rep,name=rules"`
./pkg/apis/rbac/v1beta1/types.go:	Subjects []Subject `json:"subjects" protobuf:"bytes,2,rep,name=subjects"`
./pkg/apis/rbac/v1beta1/types.go:	Rules []PolicyRule `json:"rules" protobuf:"bytes,2,rep,name=rules"`
./pkg/apis/rbac/v1beta1/types.go:	Subjects []Subject `json:"subjects" protobuf:"bytes,2,rep,name=subjects"`
```

upon switching storage to protobuf, they will store `[]` as `null`, and lose the ability to distinguish between those values presented by clients. unless decoration or defaulting sets a null list to `[]`, json clients will always see null (which can break clients that don't check for null currently, expecting the `[]` value they stored to be honored).

I see these fields that document different behavior for `null` and `[]`:
PodAffinityTerm.Namespaces
NetworkPolicyIngressRule.Ports
NetworkPolicyIngressRule.From

**Comment by liggitt** [comment]
might be related to #42798 (trying to update because nil subsets != [] subsets)

**Comment by liggitt** [comment]
@thockin can you confirm the doc on NetworkPolicyIngressRule.{Ports,From} is incorrect (it says the difference between `null` and `[]` is meaningful, but sets omitempty, so the difference is lost on serialization)?

**Comment by thockin** [comment]
There's an unmerged PR to erase the distinction.  It is my studied opinion that none of our APIs should distinguish between `null` and `[]`.  Go can represent it.  JSON can represent it.  Protobuf can't, and other languages that unmarshal proto and JSON can't.

**Comment by liggitt** [comment]
@davidopp @aveshagarwal @derekwaynecarr as far as I can find, PodAffinityTerm.Namespaces is the only field that documents different behavior for `null` vs `[]`... it was present in 1.5 but not referenced from another type, so I assume it was JSON-serialized in an annotation. The proto encoding in 1.6 will lose that distinction.

Stepping back, I'm actually really unnerved by giving pods the ability to make the scheduler run selections of pods from other (or all) namespaces... we don't let pods do anything else across namespaces today.

**Comment by derekwaynecarr** [comment]
I think we should remove the cross namespace capability for 1.6 on pod affinity term if there is no strong requirement.  If there is a strong requirement the semantic should be to look at a different field rather than overload nil and empty.  @davidopp - can you weigh in?

**Comment by smarterclayton** [comment]
I'd be ok with APIs that want to distinguish being forced to use:

```
type Selector struct {
  Things []MoreThings
}

```
type ThingThatHasSelectors struct {
  Selector *Selector
}
```

Authorization requires this distinction today, so it's already in a form that has to deal with it.

**Comment by smarterclayton** [comment]
It's just not a simple and succinct JSON API, which I care more about than people generating structs in protobuf complaining (the protobuf struct will be correct in our code, it's just not 100% equivalent to the JSON structs, which again, I don't care about)

**Comment by davidopp** [comment]
Regarding use case for pod A selecting on pods outside of A's namespace:
* affinity example: one app per namespace, want to co-locate front-ends and back-ends in the same zone (or node)
* anti-affinity example: coke and pepsi run in separate namespaces and you want a rule that their pods can never share a node
* another anti-affinity example: user X and user Y are in separate namespace, user X discovers that one of their containers gets significant cache interference from one of user's Y containers, so wants to make sure they don't share node

**Comment by davidopp** [comment]
I suppose we could get rid of the "all namespaces" part. Still allow to specify the namespaces, and defaults to "my namespace" but just don't allow "all namespaces."

**Comment by derekwaynecarr** [comment]
@davidopp - we need a way to restrict namespaces other than local namespace either via admission check or some flag.

**Comment by davidopp** [comment]
Can you explain the security concern?

**Comment by davidopp** [comment]
I gave several examples above where you actually want it to work across tenants.

Anti-affinity is one of the core mechanisms for isolating tenants. So you have to be able to refer to other tenants. (That was the coke/pepsi example.)

I'm still not understanding the security issue.

**Comment by derekwaynecarr** [comment]
You assume coke can know about Pepsi.  Your example is more like coke and sprite where both are under the same umbrella corp.  if you don't want coke to know about Pepsi, we can't leak that information.  Make sense?

**Comment by davidopp** [comment]
I'm fine with an admission controller or flag as long as it's not enabled by default.

**Comment by davidopp** [comment]
But we also need to do something about the original problem. Should we just get rid of the "all namespaces" behavior? The irony is that this is actually a way you could place these constraints *without* having to know about the existence of the other tenants (assuming some standard pod label names is used across all tenants)...

**Comment by aveshagarwal** [comment]
I can send a PR for PodAffinitTerm.Namespaces if no one else is doing.

**Comment by smarterclayton** [comment]
I can see valid use cases for avoidance across namespaces.  It's not
"strong" tenancy, but I also don't care about the super strong tenancy
(because noisy neighbors and restricted node sets are the solution for
that).  I care much more about being able to DoS the scheduler by
specifying abusive constraints.

**Comment by davidopp** [comment]
@smarterclayton Can you clarify what concretely you are proposing?

**Comment by smarterclayton** [comment]
I'm slightly disagreeing with Jordan and Derek in that I can see the
utility of cross-namespace that you mentioned, that some forms of
cross-namespace interaction are unavoidable (noisy neighbor, row hammer,
etc), and in the absence of a concrete abuse vector the capability itself
doesn't worry me.  We can always introduce this again later though, so I'm
not opposed to temporarily removing it (make it be impossible to serialize
on the wire by setting `json:"-"`) from 1.6 if we don't think we can limit
the potential abuse on the expense at high scales.

On Thu, Mar 16, 2017 at 7:27 PM, David Oppenheimer <notifications@github.com

**Comment by davidopp** [comment]
@smarterclayton 

IIUC there are two issues

(1) The trick we were using 
```
// nil list means "this pod's namespace," empty list means "all namespaces"
Namespaces []string `json:"namespaces" protobuf:"bytes,2,rep,name=namespaces"`
```
does not work -- cannot distinguish nil from empty. We definitely need a solution to this. One possibility is to get rid of the "empty list" option. But if we don't do that, we need to do something else.

(2) There was objection to allowing cross-namespace references. This can be addressed by rejecting it in validation or using an admission controller. (But this rejection behavior should be disabled by default in upstream.)

 It sounds like you're saying you're not concerned about (2) ?

**Comment by eparis** [comment]
Assuming I'm Coke and want to attack Pepsi, could i somehow use this to prove what node coke's app is on? And then use that information to better attack them? It's just an information leak, but some people don't want proof that others exist...

**Comment by smarterclayton** [comment]
Yes I'm well acquainted with the former.

I'm concerned from performance and DoS.  I'm not as worried about being
able to stalk other tenants (a more nuanced approach would be to allow anti
affinity - aka restraining order - but not affinity - stalker).  I'd like
the ability to disable the parts that are really expensive like all
namespaces, but high namespace count clusters are going to be heavily
impacted from most of these predicates (based on a quick assessment).

I can see substantial value to affinity across namespaces for microservices
set up by different teams.

On Mar 16, 2017, at 7:44 PM, David Oppenheimer <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton>

IIUC there are two issues

(1) The trick we were using

// nil list means "this pod's namespace," empty list means "all namespaces"
Namespaces []string `json:"namespaces" protobuf:"bytes,2,rep,name=namespaces"`

does not work -- cannot distinguish nil from empty. We definitely need a
solution to this. One possibility is to get rid of the "empty list" option.
But if we don't do that, we need to do something else.

(2) There was objection to allowing cross-namespace references. This can be
addressed by rejecting it in validation or using an admission controller.
(But this rejection behavior should be disabled by default in upstream.)

It sounds like you're saying you're not concerned about (2) ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/43203#issuecomment-287225863>,
or mute the thread

**Comment by davidopp** [comment]
cc/ @kubernetes/sig-scheduling-bugs

**Comment by liggitt** [comment]
> I'm fine with an admission controller or flag as long as it's not enabled by default.

I disagree, but I'll spawn a separate issue where we can debate multi-tenancy and defaults.

For 1.6, I see our options for this one field as:

* do the proto-nullable wrapping thing. upside: no functional change. downside: JSON API remains pretty unintuitive.
* add a second field to hold the "all namespaces" meaning. upside: clearer API. downside: last minute field addition, slightly gorpy API.
* allow a special token in the namespaces list to mean "all namespaces", like "*". upside: clearer API. downside: slightly gorpy API (and less discoverable than a standalone field).
* remove the "all namespaces" capability for 1.6 by dropping the special meaning of `[]` (enumerate specific other namespaces, or leave it `null` or `[]` to mean the local namespace). possibly reintroduce via one of the above mechanisms after consideration. upside: side-steps the null/[] issue. downside: drops capability.

**Comment by davidopp** [comment]
Thanks for laying out the options (and for identifying the problem originally), @liggitt !

Since * is not allowed in namespace names, I like the third option the best as the ultimate solution, because it's less subtle than the first one and more compact than the second one. But also since * is not allowed in namespace names, we could drop support in 1.6 (fourth option) and then add support for "*" in 1.7 without breaking backward compatibility, since nobody will be using "*" in that field since it's not a valid namespace name.

**Comment by liggitt** [comment]
adding sig/scheduling for the PodAffinityTerm.Namespaces

adding sig/api-machinery for the broader [] -> null issue

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/43271 has merged, resolving the PodAffinityTerm functional difference. 

@thockin can you confirm the NetworkPolicyIngressRule fields being unable to express `[]` is not a blocker for 1.6? Are there existing network policies that will change meaning if `[]` switches to nil?

For the other fields mentioned above, I think my plan is as follows:

* figure out which ones could not previously be set to null in an API response (for example, endpoints subsets were pinned to non-null values prior to 1.6), and add defaulting to make nil values serialize as empty lists (at least to JSON)
* for fields which could have returned either null or empty lists previously, add a big release note that the values may be either null or [] depending on storage (since clients that didn't handle null correctly were potentially broken on these fields already)

Any objections or better ideas?

**Comment by liggitt** [comment]
Would like @kubernetes/api-reviewers @kubernetes/api-approvers to weigh in on the API implications of https://github.com/kubernetes/kubernetes/issues/43203#issuecomment-287508376

**Comment by liggitt** [comment]
@ethernetdan all the fields referenced in https://github.com/kubernetes/kubernetes/issues/43203#issuecomment-287164295

Fix to make non-omitempty slices output as [] in https://github.com/kubernetes/kubernetes/issues/43422
