### ISSUE TITLE
Impersonating a user does not automatically include the `system:authenticated` group

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#43227]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No 

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

impersonate system:authenticated

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:  baremetal 
- **OS** (e.g. from /etc/os-release): Centos7
- **Kernel** (e.g. `uname -a`): `3.10.0-514.6.1.el7.x86_64`
- **Install tools**: custom
- **Others**:

Using RBAC

**What happened**:

Impersonating a user is not setting `system:authenticated` group which causes impersonate to fail

**What you expected to happen**:

If a user is in the tokens file they and they are impersonated the `system:authenticated` group should be added for authz. 

**How to reproduce it** (as minimally and precisely as possible):

1. Make sure `system:authenticated` group has `view` cluster role
2. Create a test user via token file 
3. Using a user with impersonate access submit a command via kubectl 
   * `kubectl get po --as='<user>'`
That request will fail with 403 response even though the user is in the `system:authenticated` group.

**Anything else we need to know**:

cc @liggitt @deads2k

**Comment by liggitt** [comment]
We can probably be smart and put the authenticated group adder around the result of the impersonation filter. @deads2k, you see any issues with that?

**Comment by deads2k** [comment]
> We can probably be smart and put the authenticated group adder around the result of the impersonation filter. @deads2k, you see any issues with that?

We provide the group field to provide this kind of information.  I'm not sure I would expect my request to the server about a particular user/group tuple to be evaluated for a different user/group tuple.

**Comment by liggitt** [comment]
for impersonation, we already add groups when known (service accounts). doing so for the system:authenticated/system:unauthenticated groups makes sense to me

**Comment by deads2k** [comment]
> for impersonation, we already add groups when known (service accounts). doing so for the system:authenticated/system:unauthenticated groups makes sense to me

Only when the groups aren't specified, right?  If memory serves, that's how we did it downstream where we can make group determination.
