### ISSUE TITLE
Future: Set docker --disable-legacy-registry=true

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#43224]
Support for the v1 protocol to the docker registry was removed in docker version 1.13. At some point we'll presumably want to update our recommended docker version. Our existing version has a --disable-legacy-registry flag which prevents use of the v1 protocol. We should enable this flag in preparation for that eventuality.

**Comment by dchen1107** [comment]
Thanks for filing this!

cc/ @kubernetes/sig-node-feature-requests @danpaik

**Comment by yujuhong** [comment]
I don't think we ever get to this. Is this no longer a concern and we can safely update to v1.13? 
/cc @dchen1107 @abgworral

**Comment by mtaufen** [comment]
I'm not sure how much of an issue this is. 

gcr.io doesn't support the v1 protocol anymore [(link)](https://cloud.google.com/container-registry/docs/support/deprecation-notices#docker_registry_v1_api_and_docker_clients_below_version_16).

Does docker hub still support it? Does anyone still pull images with v1 from private registries?

I feel like we should at least provide notice about this in the release if we're raising the docker version.

**Comment by abgworrall** [comment]
Looks like docker hub deprecated it a while ago ([link](https://blog.docker.com/2015/10/docker-hub-deprecation-1-5/)). Not sure about quay.io; I can't find a deprecation notice anywhere.

**Comment by mtaufen** [comment]
Looks like quay was trying to be backwards-compatible at some point: https://blog.quay.io/quay-enterprise-supports-registry-v2/

Not sure about now.

**Comment by mtaufen** [comment]
@philips does quay still support v1?

**Comment by smarterclayton** [comment]
We still support Docker 1.10 which can be configured for schema 1.  We also
observe a large number of schema1 registries in the wild in use in private
deployments.

**Comment by dchen1107** [comment]
We didn't drop docker 1.10 in this release. Let's re-evaluate this in 1.8 timeframe.
