### ISSUE TITLE
critical pods not being spread properly?

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kubernetes#43245]
**Is this a request for help?** 
No

**What keywords did you search in Kubernetes issues before filing this one?** 
critical pod spread

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
1.5.3

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): debian/jessie
- **Kernel** (e.g. `uname -a`): 4.4.41-k8s
- **Install tools**: Kops v1.5.1
- **Others**: docker 1.12.3

**What happened**:
A single node failed with an issue that looked identical to: https://github.com/kubernetes/kubernetes/issues/42164

It was noted that many of the pods running in the kube-system namespace were running on this single node including: both replicas of kube-dns, kube-dashboard, heapster among a few others.  This effectively means the cluster was completely non-operational for us as we rely on kube-dns.

**What you expected to happen**:
At minimum critical system pods of the same kind should never be scheduled to the same node.  Ideally all pods within the kube-system namespace would be spread as much as possible across the nodes.

**How to reproduce it** (as minimally and precisely as possible):
I'm not certain how it got into this state, the cluster was never resource starved for CPU nor memory.

**Anything else we need to know**:
Is `podAntiAffinity` the right solution here or should the scheduler just handle this as a special case automatically?

**Comment by blakebarnett** [comment]
cc: @justinsb

**Comment by cmluciano** [comment]
@blakebarnett for reproducing, can you provide a bit more context on how many pods and the state of CPU/MEM/DISK on each? Also are you using the default for the scheduler or have you modified predicates/priorities?

**Comment by blakebarnett** [comment]
No modifications to the scheduler.  There were (aside from those that are on all nodes): 
```
1 calico-policy-controller: (not sure, heapster seems unable to collect metrics from it)
2 kube-dns:                 CPU: 2m  MEM: ~24Mi (each), 
1 kube-dns-autoscaler:      CPU: 0m  MEM: 7Mi
1 heapster:                 CPU: 4m  MEM: 51Mi, 
1 kubernetes-dashboard:     CPU: 0m  MEM: 14Mi,
1 konfd:                    CPU: 0m  MEM: 14Mi,
```
from the kube-system namespace on the node that failed.

**Comment by blakebarnett** [comment]
We haven't seen this since 1.6
