### ISSUE TITLE
Convert nvidia-gpu manager to CRI

### ISSUE THREAD

**Issue by cmluciano** [kubernetes/kubernetes#43240]
There are several TODO's in the [nvidia-gpu-manager](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go#L68) for migrating existing code to leverage CRI logic. 

[Hardware Accelerators](https://github.com/kubernetes/features/issues/192) and GPUs will likely change, but we should convert these existing functions in support of #43234 .

**Comment by cmluciano** [comment]
I cannot assign this to myself since I am not an org member, but I am actively working on this

**Comment by liyubobj** [comment]
Yes, we need to replace `dockertools.DockerInterface` to CRI api instead.

**Comment by cmluciano** [comment]
I've been inspecting the usage of Docker within the GPU package. 

The main usage of the docker client is to detect the host devices mounted into the devices with the equivalent of the ``docker inspect`` command. 

I noted that I could potentially use the [PodStatus.ContainerStatus](https://kubernetes.io/docs/api-reference/v1.6/#podstatus-v1-core) from the API, but the Description notes that this just calls docker inspect in the end. 

@yujuhong It seems that there may be a series of changes to go through for inspecting a running container in a CRI-like way. 

In the interim, I can try to switch to the ContainerStatus to migrate away from the dockertools, but it won't close this issue yet.

**Comment by cmluciano** [comment]
cc @liyubobj @seelam ^

**Comment by cmluciano** [comment]
I may have spoke to soon. It seems that [ContainerStatus](https://kubernetes.io/docs/resources-reference/v1.6/#containerstatus-v1-core) may only concern itself with the container lifecycle.

**Comment by yujuhong** [comment]
@cmluciano you are looking at the k8s api, not the CRI api. 
See the `ContainerStatus`in the CRI: https://github.com/kubernetes/kubernetes/blob/v1.6.1/pkg/kubelet/api/v1alpha1/runtime/api.pb.go#L1397

**Comment by cmluciano** [comment]
sigh... one of these day's I'll figure out the proper paths for these things. Thanks for the link.

**Comment by vishh** [comment]
@cmluciano sync with me before you work on this issue. We can use either an internal Pod API which is checkpointed by the CRI or use device cgroups.

**Comment by cmluciano** [comment]
### Notes from discussion with @vishh

- Currently GPUmanager speaks pods but it integrates with an external API that only knows about resources
- GPUmanager should eventually be dissolved into the CM package so it can be checkpointed individually
- Would be great if GPUs were preallocated from admission, then subsequent requests can reference this list

#### Steps for this issue:
- We need to update the GPU logic to leverage the current checkpoints from the CRI
- External API needs to be sure to create the device cgroup hierarchy
- devices.allow can then be populated with the pod level cgroup 

(let me know if I missed something and I will update the steps)

**Comment by vishh** [comment]
Immediate needs:
* GPU manager needs an internal pod API that can represent GPUs (devices) and abstract the CRI. CRI acts as a permanent checkpoint. 

Future:
* GPU manager should move into Container Manager because eventually container manager will handle hardware topology awareness and performance optimizations.
* Container manager should set up device cgroups and let the runtimes allow all devices. GPUs should be added to pod level device cgroups.

**Comment by cmluciano** [comment]
@vishh Are there any more notes that we want to make for the CRI changes that you listed above? I have halted progression on this issue in favor of the f2f discussion.

**Comment by vishh** [comment]
@cmluciano Nope. Can you post how you plan on tackling this problem before spending time implementing it?

**Comment by cmluciano** [comment]
@vishh 

- Enable checkpointing for GPUs 
  - Not sure if we want a physical file that persists similar to #489 
  - Do we want something more specific than calling the CRI checkpoint API?
- Enable whitelisting GPUs per pod sandbox and disallow others from utilizing them
  - Requires CRI device cgroup management

**Comment by vishh** [comment]
cc @jiayingz 

@cmluciano @jiayingz is starting to ramp up in the node + GPU area and I felt this might be a good starter project. If it's OK with you, can we have her tackle this issue?

**Comment by resouer** [comment]
close in favor of https://github.com/kubernetes/kubernetes/issues/54090
