### ISSUE TITLE
Version matching across (kube & apiserver & apimachinery & client-go) = failure. 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#43246]
**This a BUG REPORT ** (choose one):

**Kubernetes version** 
latest master(s) of * 

**What happened**:
Trying to godep save tools leveraging e2e dependencies causes a version hell, across repos that does not resolve, b/c they are not in sync.  

repos: 
k8s.io/client-go
k8s.io/apiserver
k8s.io/apimachinery
k8s.io/kubernetes 

are out of sync.  

**What you expected to happen**:
`godep save ./...` to simply work.  

**How to reproduce it** (as minimally and precisely as possible):
Create a test wrapper similar 
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/e2e_test.go 

Try to `godep save ./...` will never resolve b/c they are out of date and package dep shuffling issues.  

I've figured out a way to hack around it, but it should really not be this hard.  We've made vendoring any inner part of the code base near impossible for anyone who doesn't know the inner workings.  

/cc @gmarek @kubernetes/sig-api-machinery-misc @deads2k

**Comment by smarterclayton** [comment]
What about hack/godep-restore.sh?  Does that work?

On Thu, Mar 16, 2017 at 5:18 PM, Timothy St. Clair <notifications@github.com

**Comment by timothysc** [comment]
nope

**Comment by smarterclayton** [comment]
Weird, it worked for me - the staging gopath seems to work on my machine.

On Thu, Mar 16, 2017 at 7:16 PM, Timothy St. Clair <notifications@github.com

**Comment by timothysc** [comment]
Steps to reproduce: 
1. Start with a clean GOPATH, check out under k8s.io and run ./hack/godep-restore.sh 
2. Create a e2e wrapper, doesn't matter where, that looks something like: 

```
package battery

import (
	"testing"

	"k8s.io/kubernetes/test/e2e"
	"k8s.io/kubernetes/test/e2e/framework"
	_ "k8s.io/kubernetes/test/e2e/scheduling"
)

func init() {
	framework.ViperizeFlags()
}

func TestE2E(t *testing.T) {
	e2e.RunE2ETests(t)
}

```

3. `export GOPATH=$GOPATH:$KPATH/staging`  <- if that is reversed, BOOM goes your computer
4. navigate to your test location and run `godep save ./...`  looks like it worked, wait for it...
5. run `go test -i -c -o battery.test github.com/yaddayadda/pkg/battery` dep fail.  DING, BANG, BLURPT, BLOOP... swearing ensues. 

Now to get around this I go into vendor and copy around folders, but no person outside of someone working on the project would understand what is going on... 

/cc @jbeda

**Comment by sttts** [comment]
> export GOPATH=$GOPATH:$KPATH/staging <- if that is reversed, BOOM goes your computer

It only loops infinitely, godep fun. No boom ;-)

I can reproduce the issue with godep v74 and v79 (latest). The actual issue leading to @timothysc's DING, BANG, BLURPT, BLOOP: the staging dirs are not copied into vendor. Instead we get:

```
{
			"ImportPath": "k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/api/equality",
			"Comment": "v1.7.0-alpha.0-1307-g8abb3ae7b2",
			"Rev": "8abb3ae7b233b5651e2b0d4bb60ebc23edbb5d4b"
		},
```

**Comment by sttts** [comment]
I started to fix this in godep (https://github.com/sttts/godep/commit/3d6ab66a0550070153c1a98a86196fbc5a6a5b5f) but eventually realized that it's the wrong approach. The problem is not that godep is exploding due to nested paths, but the issue is that we put godep into a situation that is unsolvable with the Godeps.json data model:

How should the `ImportPath` look like for the apimachinery+apiserver+client-go packages?

We would need some kind of subdir checkout, that not even git supports.

What we really want or what a user is expecting is that godep save somehow magically switches from the staging dirs to the real repos. You can do that manually by checking out apimachinery+apiserver+client-go into your GOPATH first. Then godep will correctly pick these up and vendor/ them for your battery example. It's basically what we do in the `hack/*-staging-*.sh` scripts.

**Comment by timothysc** [comment]
>What we really want or what a user is expecting is that godep save somehow magically switches from the staging dirs to the real repos. You can do that manually by checking out apimachinery+apiserver+client-go into your GOPATH first. Then godep will correctly pick these up and vendor/ them for your battery example. It's basically what we do in the hack/*-staging-*.sh scripts.

Unless the repos are lock-step in sync via something like git-submodules + enforcement w/tags there will always be issues.  A big part of this is code-hygiene and dependency management.  

I'll work over the course of 1.7 to isolate deps in the e2es, but it's pretty clear this rabbit hole is both deep and wide.

**Comment by timothysc** [comment]
This whole repo-splitting idea needs to be more throughly vetted... imo.

**Comment by sttts** [comment]
Honestly, I don't have a problem to expect more Golang dependency expertise from people vendoring kube itself. Client-go is our lib for 3rdparties. If people depend on kube directly, they either do something outside of the supported area "on their own risk" or our client-go misses something we should expose.

Not sure about your e2e use-case here. Sounds like something where documentation would do. It's not the classical third party "I want to develop against kube" class of use-cases.

**Comment by timothysc** [comment]
> Not sure about your e2e use-case here 

There have been a number of folks wanting to wrap+extend+augment, and openshift does the same thing.  Either way, I think documentation is the most sane path until dependencies can be refactored and isolated.

**Comment by sttts** [comment]
Big question is: where can we document this? In some md file nobody will notice. As a warning in godep-restore.sh?

**Comment by timothysc** [comment]
I think a note on the main page perhaps with a pointer to a script kubedep.sh ?

**Comment by timothysc** [comment]
@sttts  Did you have a preferred location?  I'm thinking front page.

**Comment by sttts** [comment]
Another section below "To start developing Kubernetes": "To start vendoring Kubernetes". With a big warning that for 99% of cases client-go is the better solution.

**Comment by timothysc** [comment]
So here is what I ended up doing for posterity.. 

```
export KPATH=$GOPATH/src/k8s.io/kubernetes
export GOPATH=$GOPATH:$KPATH/staging

$KPATH/hack/generate-bindata.sh
godep save ./...
cp -Lr $KPATH/vendor/k8s.io/api* $KPATH/vendor/k8s.io/client-go ./vendor/k8s.io/
cp $KPATH/test/e2e/generated/bindata.go ./vendor/k8s.io/kubernetes/test/e2e/generated/bindata.go
```

**Comment by timothysc** [comment]
> Do you have the staging repos in Godeps.json after this? 

It has the upstream staging directories as deps, not the repos.  
Local restore works as expected.
