### ISSUE TITLE
OpenApi scheme resource types should say whether they are Namespaced or not

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#43258]
When generating docs and clients, we need to know of an object is namespaced or not.  Currently this is parsed using regex hacks from the operationIds.

**Comment by lavalamp** [comment]
@mbohlool please change the milestone if you're not going to get to this.

**Comment by mbohlool** [comment]
@pwittrock This is actually a simple fix and I can send a PR for it, only question is, if an API works on "All namespaces" (vs no namespaced APIs) is it also considered namespaced?

**Comment by pwittrock** [comment]
@mbohlool I am not sure I understand the difference.  Can you give examples?

**Comment by mbohlool** [comment]
for example is `listCoreV1ConfigMapForAllNamespaces` namespaced?
