### ISSUE TITLE
Extract container runtime-specific flags from kubelet

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#43253]
There are many container runtime (i.e., docker) specific flags (and corresponding fields in `KubeletConfiguration`). We should clean them up. 

Here are some ideas:
 1. Group them together in to a separate struct, e.g., `DockerConfiguration`, which can be persisted to the apiserver as a ComponentConfig (as part of `KubeletConfiguration`).
 2. Add a local `DockerFlags` struct that does not persist to the apiserver at all. @mtaufen also has a PR #40117 that adds a separate `KubeletFlags` struct so that not all flags are mapped to fields in the `KubeletConfiguration`.

Theoretically, the CRI shim may run as a separate process and have no access the the apiserver, and (1) does not work with this model. I am leaning towards to (2), but would like some input from others. Would we want to change runtime-specific configuration dynamically in the future? If so, how can we approach this for standalone shims?

/cc @mtaufen @dchen1107

**Comment by jakon89** [comment]
> Would we want to change runtime-specific configuration dynamically in the future?

Maybe it's worth to discuss this along with https://github.com/kubernetes/kubernetes/pull/29459 on the meeting tomorrow?

**Comment by mtaufen** [comment]
If we are unsure of whether we will ever dynamically change these, we should leave them out of KubeletConfiguration. We can add them back if we need to change them dynamically, but ideally I'd like to get KubeletConfiguration as small as possible and add categories of config back as needed.

We should still define e.g. a DockerConfig type to keep the fields grouped together. This can be part of #40117's KubeletFlags for now.

**Comment by yujuhong** [comment]
#44061 (merged) added a new ContainerRuntimeOptions struct as part of the KubeletFlags that @mtaufen added. The struct should include most (if not all) container-runtime-specific fields/flags. These flags *may* be deprecated and eventually removed in the future when we support setting up the standalone CRI runtime (shim) in the cluster lifecycle tools. 

Please add new runtime-specific flags to `ContainerRuntimeOptions` (and not `KubeletConfig`) directly, *and* think twice before doing so since this may make deprecation harder.
