### ISSUE TITLE
Network Partition test errors on GCE Upgrade Tests

### ISSUE THREAD

**Issue by skriss** [kubernetes/kubernetes#43251]
@foxish 

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.5-1.6-upgrade-cluster/26

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.5-1.6-upgrade-cluster-new/24

The Network Partition tests are largely failing in the GCE Upgrade tests. I had these marked as flakes, but they've failed a lot recently - can you take a look at the failures and confirm that there's not an actual underlying issue?

For context, these tests spin up a 1.5 cluster, upgrade it to 1.6, and then run either 1.5 or 1.6 E2E tests against it, depending on the job.

**Comment by foxish** [comment]
I'll take a look shortly

**Comment by foxish** [comment]
Yeah, I do not think this is a real issue, because the test isn't able to partition the node in the first place. This is likely because of the way the upgrade cluster is set up. Not a blocker.

**Comment by skriss** [comment]
ok, thanks!
