### ISSUE TITLE
Unregistered types should have a group version kind extension in open api

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#43250]
Some of the types such as NodeCondition don't have the gvk extension in the swagger.json.  This makes it impossible to rely on the gvk extension when generating docs or clients.

**Comment by mbohlool** [comment]
do all kinds types gvk? I think the API convention forces `Kind` to be part of a `Group/Version` to form a `gvk`, but not all types are `Kind`.

**Comment by lavalamp** [comment]
Is this still a live issue?

**Comment by mbohlool** [comment]
@pwittrock can you clarify?

**Comment by pwittrock** [comment]
When generating the ref doc for "NodeCondition" type, how do I figure out what the GVK is?

**Comment by mbohlool** [comment]
It does not have gvk in the code. what gvk should it get? the parent type? what if it has more than one parent? multiple gvks? This is something that can be found by inspecting the spec without doing any hack anyway.

**Comment by pwittrock** [comment]
Aren't the Kinds themselves versioned?  They are declared under a group/version.  Couldn't we in theory have 2 versions of PodTemplate embedded in other resource Specs?
