### ISSUE TITLE
GCE Upgrade Test failure - Services should work after restarting apiserver

### ISSUE THREAD

**Issue by skriss** [kubernetes/kubernetes#43252]
@bprashanth 

This test has been failing recently in the GCE 1.5->1.6 upgrade tests. I had it marked as a flake but given the recent failures wanted to double-check to ensure there's not an underlying issue:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.5-1.6-upgrade-cluster/26#k8sio-services-should-work-after-restarting-apiserver-disruptive

This job is spinning up a 1.5 cluster, upgrading to 1.6, then running the 1.5 E2E tests to check for compatibility.

Can you take a look ASAP and ensure this isn't a problem for 1.6? Thanks.

**Comment by kargakis** [comment]
@skriss still an issue?

/sig network

**Comment by skriss** [comment]
This was an issue I filed during the 1.6 release upgrade testing - it can be closed as it's obsolete at this point.
