### ISSUE TITLE
TestSnippetWriter failed when run go cover tesst

### ISSUE THREAD

**Issue by ikaven1024** [kubernetes/kubernetes#43266]
I am using [v1.3.10](https://github.com/kubernetes/kubernetes/tree/v1.3.10), and run cover test with it. And failed in `TestSnippetWriter`
```
--- FAIL: TestSnippetWriter (0.00s)
	snippet_writer_test.go:85: Expected "snippet_writer_test.go:78" but didn't find it in "template: /usr/local/jenkins/workspace/Fsdmdept_PAAS_Kubernetes_Test/_output/local/go/src/k8s.io/kubernetes/cmd/libs/go2idl/generator/snippet_writer_test.go:77:1: unclosed action"
```
log the error gotten in the case is`snippet_writer_test.go:77`, but expected `snippet_writer_test.go:78`.

But it passed when run test without cover.

**Comment by liggitt** [comment]
that test was removed in 1.5. if you look closely, it even apologized for being terrible :)

**Comment by ikaven1024** [comment]
go test cover will change the line? Whether does mechanism of go test cause it?

**Comment by liggitt** [comment]
`go test -cover` rewrites sourcecode internally to insert counters to test line coverage, but that changes the fixed line number
