### ISSUE TITLE
Kubectl skew tests between 1.6 and master are flaking because nodes are tainted in parallel

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#43263]
The kubectl skew tests for master->1.6 and 1.6->master are flaking because `GINKGO_PARALLEL=y` and the `ginkgo.focus` is set to just `Kubectl`. This is a problem because there is a test for taints that is called `"Kubectl taint [Serial]"` that is meant to be run serially and not in parallel, but the current settings don't allow for that. As a result, while some tests are creating pods, the taint test is setting `NoExecute` on the node, and the taint manager kicks out any pods it sees, causing the other tests to fail. The test in question in [here](https://github.com/kubernetes/kubernetes/blob/6cc40678b6988124940f76b780657bfc46e14a7a/test/e2e/kubectl.go#L1412) and it was moved to be a `[Serial]` test in https://github.com/kubernetes/kubernetes/pull/42167.

cc @calebamiles @ethernetdan @fejta @marun @smarterclayton @davidopp

**Comment by liggitt** [comment]
adding to 1.6 to resolve this so our release branch doesn't have flaky CI (which makes signals for point releases really tough)

**Comment by ncdc** [comment]
Example configuration that yields this issue: https://github.com/kubernetes/test-infra/blob/master/jobs/ci-kubernetes-e2e-gce-master-1.6-gci-kubectl-skew.env#L2-L3

**Comment by liggitt** [comment]
would `GINKGO_TEST_ARGS=--ginkgo.focus=Kubectl --ginkgo.skip=\[Serial\]` work?

**Comment by ncdc** [comment]
It wil skip the taint test and get rid of these flakes. But it would never run the taint test...

**Comment by liggitt** [comment]
added in https://github.com/kubernetes/test-infra/pull/2144
cc @ixdy @pwittrock 

> It will skip the taint test and get rid of these flakes. But it would never run the taint test...

second job with `GINKGO_TEST_ARGS="--ginkgo.focus=Kubectl.*\[Serial\]"`?

**Comment by liggitt** [comment]
or make the job not run parallel

**Comment by ncdc** [comment]
Either a second job (times all the variants), or not running in parallel would do it.

**Comment by smarterclayton** [comment]
Second job would be preferred so as not to skip a relevant test but not be terribly slow.  Not strong pref

**Comment by ncdc** [comment]
The current job looks like it takes about 20 minutes to run. I wonder how switching to parallel=n would change the timing.

**Comment by smarterclayton** [comment]
Most kubect tests are fast so parallelism would likely drop the time
significantly.

On Mar 16, 2017, at 10:27 PM, Andy Goldstein <notifications@github.com>
wrote:

The current job looks like it takes about 20 minutes to run. I wonder how
switching to parallel=n would change the timing.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/43263#issuecomment-287249630>,
or mute the thread

**Comment by ncdc** [comment]
@smarterclayton I think you misread what I wrote 😄

**Comment by smarterclayton** [comment]
= so fast - they parallelize well.  If you don't have short tests parallelism doesn't help much because of how ginkgo distributes tests, which is something they just fixed for us.

**Comment by ncdc** [comment]
I tried my hand at fixing this. PTAL at https://github.com/kubernetes/test-infra/pull/2283

**Comment by ethernetdan** [comment]
Keeping open until can be confirmed in skew tests - I'll check later tonight.

**Comment by ethernetdan** [comment]
Looks good!
