### ISSUE TITLE
volume remains mounted after removing pod 

### ISSUE THREAD

**Issue by divyenpatel** [kubernetes/kubernetes#43272]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT 

**Kubernetes version** (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: vsphere
- **OS** (e.g. from /etc/os-release): photon
- **Kernel** (e.g. `uname -a`): Linux node3 4.4.8-esx #1-photon SMP Tue Jun 7 08:04:49 UTC 2016 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
Created pod using following spec.
```
$ cat pod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: goldenpod
spec:
  containers:
  - name: container1
    image: gcr.io/google_containers/busybox:latest
    # Just spin & wait forever
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
    - mountPath: /golden-vmdk
      name: golden-volume
  volumes:
  - name: golden-volume
    # This VMDK volume must already exist.
    vsphereVolume:
      volumePath: "[storage1] kubevols/goldenVolume.vmdk"
      fsType: ext4
```

Verified pod is created successfully and verified volume is mounted on the node.
```
$ kubectl create -f diamondPod.yaml 
pod "diamondpod" created
```

```
$ kubectl get pod
NAME         READY     STATUS    RESTARTS   AGE
diamondpod   1/1       Running   0          10m
```

```
root@node3 [ ~ ]# mount | grep vsphere
/dev/sdb on /var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/[storage1] kubevols/diamond.vmdk type ext4 (rw,relatime,data=ordered)
/dev/sdb on /var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/[storage1] kubevols/diamond.vmdk type ext4 (rw,relatime,data=ordered)
/dev/sdb on /var/lib/kubelet/pods/86932cb4-0aa4-11e7-8d9d-0050568e9714/volumes/kubernetes.io~vsphere-volume/diamond-volume type ext4 (rw,relatime,data=ordered)
/dev/sdb on /var/lib/kubelet/pods/86932cb4-0aa4-11e7-8d9d-0050568e9714/volumes/kubernetes.io~vsphere-volume/diamond-volume type ext4 (rw,relatime,data=ordered)
```

Deleted pod and but volume never got unmounted.

```
$ kubectl get pod
NAME         READY     STATUS        RESTARTS   AGE
diamondpod   1/1       Terminating   0          11m
$ kubectl get pod
No resources found.
```

**What you expected to happen**:
Expecting volumes should be unmounted and disks should be detached from the node.
**This Issue is happening on 1.5.4, issue is not reproducible on 1.5.3**

Expecting to see SyncLoop (REMOVE, \"api\") call and "No ref for pod" in the logs after pod is deleted.

**How to reproduce it** (as minimally and precisely as possible):
Create POD, wait for volume to get mounted, delete pod.

**Anything else we need to know**:
Below are kubelet logs collected before and after deleting pod.

**Before Delete**

{"log":"I0316 23:38:00.070103     704 operation_executor.go:917] MountVolume.SetUp succeeded for volume \"kubernetes.io/secret/970abea5-0aa1-11e7-8d9d-0050568e9714-default-token-486q4\" (spec.Name: \"default-token-486q4\") pod \"970abea5-0aa1-11e7-8d9d-0050568e9714\" (UID: \"970abea5-0aa1-11e7-8d9d-0050568e9714\").\n","stream":"stderr","time":"2017-03-16T23:38:00.071208067Z"}

{"log":"I0316 23:38:00.126499     704 volume_manager.go:367] All volumes are attached and mounted for pod \"kube-proxy-lbndc_kube-system(970abea5-0aa1-11e7-8d9d-0050568e9714)\"\n","stream":"stderr","time":"2017-03-16T23:38:00.126693672Z"}

**After Delete**

{"log":"I0317 00:10:22.163120     704 docker_manager.go:1559] Killing container \"293867b3bb3abc62b04436f90e6fcc649b6ca48fcf2877341f2ad38b8266311d container1 default/diamondpod\" with 30 second grace period\n","stream":"stderr","time":"2017-03-17T00:10:22.163208408Z"}

{"log":"I0317 00:10:52.921712     704 kubelet.go:1816] SyncLoop (PLEG): \"diamondpod_default(86932cb4-0aa4-11e7-8d9d-0050568e9714)\", event: \u0026pleg.PodLifecycleEvent{ID:\"86932cb4-0aa4-11e7-8d9d-0050568e9714\", Type:\"ContainerDied\", 

{"log":"I0317 00:10:52.935527     704 status_manager.go:441] Removing Pod \"diamondpod_default(86932cb4-0aa4-11e7-8d9d-0050568e9714)\" from etcd\n","stream":"stderr","time":"2017-03-17T00:10:52.939922281Z"}

{"log":"I0317 00:10:52.937178     704 config.go:281] Setting pods for source api\n","stream":"stderr","time":"2017-03-17T00:10:52.939982631Z"}
{"log":"I0317 00:10:52.938466     704 kubelet.go:1794] SyncLoop (RECONCILE, \"api\"): \"diamondpod_default(86932cb4-0aa4-11e7-8d9d-0050568e9714)\"\n","stream":"stderr","time":"2017-03-17T00:10:52.939999651Z"}
{"log":"I0317 00:10:53.009786     704 config.go:281] Setting pods for source api\n","stream":"stderr","time":"2017-03-17T00:10:53.010148892Z"}
{"log":"I0317 00:10:53.010308     704 kubelet.go:1797] SyncLoop (DELETE, \"api\"): \"diamondpod_default(86932cb4-0aa4-11e7-8d9d-0050568e9714)\"\n","stream":"stderr","time":"2017-03-17T00:10:53.010479633Z"}
{"log":"I0317 00:10:53.020411     704 round_trippers.go:318] DELETE https://10.20.104.73/api/v1/namespaces/default/pods/diamondpod 200 OK in 84 milliseconds\n","stream":"stderr","time":"2017-03-17T00:10:53.020870832Z"}

{"log":"I0317 00:10:53.020891     704 status_manager.go:443] Pod \"diamondpod_default(86932cb4-0aa4-11e7-8d9d-0050568e9714)\" fully terminated and removed from etcd\n","stream":"stderr","time":"2017-03-17T00:10:53.02207871Z"}

{"log":"I0317 00:11:01.036419     704 status_manager.go:499] Pod status is inconsistent with cached status for pod \"diamondpod_default(86932cb4-0aa4-11e7-8d9d-0050568e9714)\", a reconciliation should be triggered:\n","stream":"stderr","time":"2017-03-17T00:11:01.03653326Z"}

{"log":"I0317 00:11:01.036419     704 status_manager.go:499] Pod status is inconsistent with cached status for pod \"diamondpod_default(86932cb4-0aa4-11e7-8d9d-0050568e9714)\", a reconciliation should be triggered:\n","stream":"stderr","time":"2017-03-17T00:11:01.03653326Z"}
{"log":" {\"phase\":\"Running\",\"conditions\":[{\"type\":\"Initialized\",\"status\":\"True\",\"lastProbeTime\":null,\"lastTransitionTime\":\"2017-03-16T23:59:00Z\"},{\"type\":\"Ready\",\"status\":\"False\",\"lastProbeTime\":null,\"lastTransitionTime\":\"2017-03-17T00:10:5\n","stream":"stderr","time":"2017-03-17T00:11:01.036561707Z"}
{"log":"\n","stream":"stderr","time":"2017-03-17T00:11:01.03657913Z"}

{"log":"A: 2Z\",\"reason\":\"ContainersNotReady\",\"message\":\"containers with unready status: [container1]\"},{\"type\":\"PodScheduled\",\"status\":\"True\",\"lastProbeTime\":null,\"lastTransitionTime\":\"2017-03-16T23:59:00Z\"}],\"hostIP\":\"10.20.105.26\",\"startTime\":\"2017-03-16T23:59:00Z\",\"containerStatuses\":[{\"name\":\"container1\",\"state\":{\"terminated\":{\"exitCode\":137,\"reason\":\"Error\",\"startedAt\":\"2017-03-16T23:59:21Z\",\"finishedAt\":\"2017-03-17T00:10:52Z\",\"containerID\":\"docker://293867b3bb3abc62b04436f90e6fcc649b6ca48fcf2877341f2ad38b8266311d\"}},\"lastState\":{},\"ready\":false,\"restartCount\":0,\"image\":\"gcr.io/google_containers/busybox:latest\",\"imageID\":\"docker://sha256:e7d168d7db455c45f4d0315d89dbd18806df4784f803c3cc99f8a2e250585b5b\",\"containerID\":\"docker://293867b3bb3abc62b04436f90e6fcc649b6ca48fcf2877341f2ad38b8266311d\"}]}\n","stream":"stderr","time":"2017-03-17T00:11:01.03658913Z"}

{"log":"B: 3Z\",\"reason\":\"ContainersNotReady\",\"message\":\"containers with unready status: [container1]\"},{\"type\":\"PodScheduled\",\"status\":\"True\",\"lastProbeTime\":null,\"lastTransitionTime\":\"2017-03-16T23:59:00Z\"}],\"hostIP\":\"10.20.105.26\",\"startTime\":\"2017-03-16T23:59:00Z\",\"containerStatuses\":[{\"name\":\"container1\",\"state\":{\"terminated\":{\"exitCode\":137,\"reason\":\"Error\",\"startedAt\":\"2017-03-16T23:59:21Z\",\"finishedAt\":\"2017-03-17T00:10:52Z\",\"containerID\":\"docker://293867b3bb3abc62b04436f90e6fcc649b6ca48fcf2877341f2ad38b8266311d\"}},\"lastState\":{},\"ready\":false,\"restartCount\":0,\"image\":\"gcr.io/google_containers/busybox:latest\",\"imageID\":\"docker://sha256:e7d168d7db455c45f4d0315d89dbd18806df4784f803c3cc99f8a2e250585b5b\",\"containerID\":\"docker://293867b3bb3abc62b04436f90e6fcc649b6ca48fcf2877341f2ad38b8266311d\"}]}\n","stream":"stderr","time":"2017-03-17T00:11:01.036624343Z"}

{"log":"I0317 00:11:21.039273     704 round_trippers.go:318] GET https://10.20.104.73/api/v1/namespaces/default/pods/diamondpod 404 Not Found in 3 milliseconds\n","stream":"stderr","time":"2017-03-17T00:11:21.039725663Z"}
{"log":"I0317 00:11:21.039300     704 round_trippers.go:324] Response Headers:\n","stream":"stderr","time":"2017-03-17T00:11:21.039760709Z"}
{"log":"I0317 00:11:21.039312     704 round_trippers.go:327]     Content-Type: application/vnd.kubernetes.protobuf\n","stream":"stderr","time":"2017-03-17T00:11:21.039773446Z"}
{"log":"I0317 00:11:21.039333     704 round_trippers.go:327]     Content-Length: 105\n","stream":"stderr","time":"2017-03-17T00:11:21.039787002Z"}
{"log":"I0317 00:11:21.039347     704 round_trippers.go:327]     Date: Fri, 17 Mar 2017 00:11:21 GMT\n","stream":"stderr","time":"2017-03-17T00:11:21.039797269Z"}
{"log":"I0317 00:11:21.039408     704 request.go:903] Response Body:\n","stream":"stderr","time":"2017-03-17T00:11:21.039807196Z"}
{"log":"00000000  6b 38 73 00 0a 0c 0a 02  76 31 12 06 53 74 61 74  |k8s.....v1..Stat|\n","stream":"stderr","time":"2017-03-17T00:11:21.039816602Z"}
{"log":"00000010  75 73 12 51 0a 04 0a 00  12 00 12 07 46 61 69 6c  |us.Q........Fail|\n","stream":"stderr","time":"2017-03-17T00:11:21.039825879Z"}
{"log":"00000020  75 72 65 1a 1b 70 6f 64  73 20 22 64 69 61 6d 6f  |ure..pods \"diamo|\n","stream":"stderr","time":"2017-03-17T00:11:21.039835385Z"}
{"log":"00000030  6e 64 70 6f 64 22 20 6e  6f 74 20 66 6f 75 6e 64  |ndpod\" not found|\n","stream":"stderr","time":"2017-03-17T00:11:21.039845055Z"}
{"log":"00000040  22 08 4e 6f 74 46 6f 75  6e 64 2a 16 0a 0a 64 69  |\".NotFound*...di|\n","stream":"stderr","time":"2017-03-17T00:11:21.039854878Z"}
{"log":"00000050  61 6d 6f 6e 64 70 6f 64  12 00 1a 04 70 6f 64 73  |amondpod....pods|\n","stream":"stderr","time":"2017-03-17T00:11:21.039864572Z"}
{"log":"00000060  28 00 30 94 03 1a 00 22  00                       |(.0....\".|\n","stream":"stderr","time":"2017-03-17T00:11:21.039873812Z"}
{"log":"I0317 00:11:21.039447     704 request.go:996] Response Body: \"k8s\\x00\\n\\f\\n\\x02v1\\x12\\x06Status\\x12Q\\n\\x04\\n\\x00\\x12\\x00\\x12\\aFailure\\x1a\\x1bpods \\\"diamondpod\\\" not found\\\"\\bNotFound*\\x16\\n\\ndiamondpod\\x12\\x00\\x1a\\x04pods(\\x000\\x94\\x03\\x1a\\x00\\\"\\x00\"\n","stream":"stderr","time":"2017-03-17T00:11:21.039883798Z"}
{"log":"I0317 00:11:21.039564     704 status_manager.go:409] Pod \"diamondpod\" (86932cb4-0aa4-11e7-8d9d-0050568e9714) does not exist on the 

CC: @BaluDontu 

Logs
-----
[before-delete.txt](https://github.com/kubernetes/kubernetes/files/849666/before-delete.txt)
[after-delete.txt](https://github.com/kubernetes/kubernetes/files/849669/after-delete.txt)

**Comment by BaluDontu** [comment]
@saad-ali @jingxu97 : We are experiencing problem with detach, can u please take a look at this issue.

**Comment by divyenpatel** [comment]
I used incorrect kubernete-anywhere ignition image.
closing this issue. 

Not able to reproduce this issue with v1.5.4 with correct ignition image - docker.io/cnastorage/k8s-ignition:v1

@tusharnt
