### ISSUE TITLE
Container pods stuck ins tate unknown

### ISSUE THREAD

**Issue by kozikow** [kubernetes/kubernetes#43279]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z",GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z",GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GKE

**What happened**:
Pods are stuck in "Unknown" state. Those pods can't be deleted. Cluster got into this state when I have been submitting many pods at once.

**What you expected to happen**:
I can delete those pods.

**Anything else we need to know**:
Broken pods have following two lines of status (from  "kubectl get pods") that look like this :

```
  43m   43m     4       {kubelet gke-caffe-node-pool-2-c3b69e45-qxtj}                                                                           Warning FailedSync              Errorsyncing pod, skipping: network is not ready: [Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]
  36m   36m     1       {controllermanager }                                                                                                    Normal  NodeControllerEviction  Marking for deletion Pod downloader-21f7208a-f326-4a94-b2a5-80a84ef94aa3-wxzfn from Node gke-caffe-node-pool-2-c3b69e45-qxtj

```

**Comment by kozikow** [comment]
Problem was "solved" when I move the cluster to a new node pool.

**Comment by zouyee** [comment]
kube-state-metrics-deployment-1725944925-z0ltb   1/1       Unknown 
when I exec `kubectl deelte pods kube-state-metrics-deployment-1725944925-z0ltb`,pods can not deleted found by `kubectl get pods`

**Comment by gajus** [comment]
Same here. The only thing that helped on GKE is deleting all the VM instances.

**Comment by SleepyBrett** [comment]
In my experience this means that you have a wedged docker daemon. `kubectl get pods -o wide | grep Unknown` will help you determine which node might be a fault. My general remediation strategy is to not fiddle with docker and just terminate the node.

**Comment by bbhoss** [comment]
I'm also running into this on GKE with preemptible nodes. This is new since the 1.6 upgrade. Describing one of the pods looks like this:
```
Name:				voting-octopus-hlweb-worker-3387348522-v7n70
Namespace:			default
Node:				gke-cluster-1-preemptible-92c49e03-5c3x/10.138.0.6
Start Time:			Thu, 18 May 2017 08:34:23 -0700
Labels:				name=voting-octopus-hlweb-worker
				pod-template-hash=3387348522
Annotations:			kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"voting-octopus-hlweb-worker-3387348522","uid":"5ea11a87-3b5a-11e...
				kubernetes.io/limit-ranger=LimitRanger plugin set: cpu request for container hlweb-worker; cpu request for container hlweb-cron
Status:				Terminating (expires Thu, 18 May 2017 09:40:57 -0700)
Termination Grace Period:	30s
Reason:				NodeLost
Message:			Node gke-cluster-1-preemptible-92c49e03-5c3x which was running pod voting-octopus-hlweb-worker-3387348522-v7n70 is unresponsive
IP:				10.16.1.7
Controllers:			ReplicaSet/voting-octopus-hlweb-worker-3387348522
Containers:
  hlweb-worker:
<snip>
    Port:
    Command:
<snip>
    State:		Running
      Started:		Thu, 18 May 2017 08:36:25 -0700
    Ready:		True
    Restart Count:	0
    Requests:
      cpu:	100m
    Environment:
<snip>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-g3aj6 (ro)
  hlweb-cron:
<snip>
    Port:
    Command:
<snip>
    State:		Running
      Started:		Thu, 18 May 2017 08:37:15 -0700
    Ready:		True
    Restart Count:	0
    Requests:
      cpu:	100m
    Environment:
<snip>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-g3aj6 (ro)
Conditions:
  Type		Status
  Initialized 	True
  Ready 	False
  PodScheduled 	True
Volumes:
  default-token-g3aj6:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-g3aj6
    Optional:	false
QoS Class:	Burstable
Node-Selectors:	<none>
Tolerations:	node.alpha.kubernetes.io/notReady=:Exists:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable=:Exists:NoExecute for 300s
Events:		<none>
```

kubectl get lists these pods as Unknown, while describe lists them as Terminating. kubectl delete says the pod could not be found, with --force or any other option. I need a way to be able to get rid of these, killing all of the nodes is not a valid workaround, and that's the only thing I've found that triggers it.

**Comment by Gallaecio** [comment]
This happened to me a week ago, and it turned out to be because code changed had caused pods of a specific deployment configured to generate 30 replicas were consuming lots of memory each, exhausting the memory of 2 out of 5 nodes, causing those nodes to be unreachable by the master.

**Comment by yolinas** [comment]
Having the same issue here. Anyone found a way to delete the pods with status Unknown?

**Comment by bbhoss** [comment]
The only thing that worked for me was to replace all nodes at once. Through working with the GCP support team, we figured out that the issue was triggered by not having memory limits on the pods, which was causing the oomkiller to run on the servers, sometimes killing processes it shouldn't. Even worse, the scheduler rescheduled these troublesome pods on other nodes, effectually poisoning the entire cluster. This is definitely something that should be prevented, but can at least be mitigated by setting default memory limits and making sure the limits on your pods are not too high.

**Comment by rushtehrani** [comment]
I think https://github.com/kubernetes/kops/pull/2982 and https://github.com/kubernetes/kubernetes/pull/45896 will address this issue in 1.7.  See  https://github.com/kubernetes/kops/pull/2982#issuecomment-315977356 for a more detailed explanation of the issue.

**Comment by ghasabian** [comment]
Use the `kubectl delete pods <unknown pods name> --grace-period=0 --force`

**Comment by alex-dixon** [comment]
Stops showing the pod in `get pods` output but not clear if deletion actually occurs especially given the message received after running `kubectl delete pods <unknown pods name> --grace-period=0 --force`:

`warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.`

**Comment by montanaflynn** [comment]
On google container engine I also got two pods that are stuck in Unknown status:

```
some-api-3121737348-19dj6             1/1       Unknown   0          17h
some-api-3121737348-9r4wv             1/1       Unknown   0          1h
```

The other pods of the same deployment are all Running.

Any commands I could run to help debug?

**Comment by montanaflynn** [comment]
`kubectl logs` hangs until responding with this error:

```
kubectl logs -f some-api-3121737348-19dj6
Error from server: Get https://gke-backend-default-pool-a671890f-sthj:10250/containerLogs/default/some-api-3121737348-19dj6/some-api?follow=true: net/http: TLS handshake timeout
```

`kubectl exec` hangs for quite awhile before I manually killed the process.

**Comment by nestoru** [comment]
I came across this while trying to find out a solution for this problem. The gist of it is below. More explanation of what happened to us at http://thinkinginsoftware.blogspot.com/2017/10/upgrading-kubernetes-container-pods.html.

```
# add temporary access from 0.0.0.0/0 (anywhere) to protected services pods connect to
# check cluster version 
gcloud container clusters list
# switch to the specific project
gcloud container clusters get-credentials my-project-cluster --zone us-east1-b --project my-project
# check available versions
gcloud container get-server-config
# upgrade cluster master. Note that you have to go up one minor version at a time, for example 1.5.7 needs to go up to 1.6.7 before being upgraded to 1.7.2
gcloud container clusters upgrade my-project-cluster --master --cluster-version=1.7.6-gke.1
# upgrade cluster nodes
gcloud container clusters upgrade my-project-cluster --cluster-version=1.7.6
# list instances external IPs
gcloud compute instances list
# remove access from old external pod IPs, add access to the new external IPs using CIDR /32
# remove temporary access from 0.0.0.0/0 (anywhere)
```

**Comment by huseyinyilmaz** [comment]
For people who end up here like me, I wanted to share my solution(for kubernetes v1.10). I ran help for delete pod:
`$ kubectl delete pod --help`
It has following usage example and it worked for me:
```
# Force delete a pod on a dead node
  kubectl delete pod foo --grace-period=0 --force
```

**Comment by TN801465** [comment]
You can restart the kubelet service on the relevant node

**Comment by michaelmeelis** [comment]
I just had this problem as well. I check the nodes with kubectl get pod -o wide | grep Unknown. It showed that the node 2 was the problem. Then I check the node itself and saw that 
CONTAINER-RUNTIME
docker://Unknown
With a describe on the node you can check the events as well and found out that the docker daemon died. I went to azure itself found the vm (the node) and rebooted the system. It solved the issue for me.

**Comment by aswanevelder** [comment]
> Use the `kubectl delete pods <unknown pods name> --grace-period=0 --force`

`kubectl delete pods --all --grace-period=0 --force`

**Comment by Enelar** [comment]
```
kubectl delete -f deployment.yml
kubectl apply -f deployment.yml
```
1 second downtime, but no rogue pods anymore

**Comment by JAlonsoHdz** [comment]
In our case, the pod was running on a node in an aws EC2 instance, the solution was to restart the node and that did the trick.

**Comment by jodevsa** [comment]
> kubectl delete pods --all --grace-period=0 --force


@aswanevelder, the command you posted is not recommended and poses significant risks. It is crucial to thoroughly educate yourself by reading the Kubernetes documentation before suggesting or using such commands. 

I can recommend some tutorials if you'd like.
