### ISSUE TITLE
Data loss when accidentally removing "partition" field

### ISSUE THREAD

**Issue by neelance** [kubernetes/kubernetes#43291]
**Kubernetes version**: 1.5.3

**Environment**:
- **Cloud provider or hardware configuration**: GKE

**What happened**:
I wanted to migrate from directly referencing a GCE disk in the pod spec to using PVs and PVCs. We had already done this for several other disks. This particular disk however had the field "partition: 1" set, which I missed and thus did not add to the PV. What happened is that Kubernetes formatted the disk, thus losing all data.

**What you expected to happen**:
Mounting the disk should fail, since it already has a partition table. It should not be formatted.

**Comment by liggitt** [comment]
cc @kubernetes/sig-storage-bugs

**Comment by rootfs** [comment]
also see of #13212

The disk probe function [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount_linux.go#L398) uses `lsblk -nd`. `-d` skips holder devices or slaves according to [lsblk manpage](https://linux.die.net/man/8/lsblk), thus no partition is probed.


```text
-d, --nodeps
              Do  not  print  holder  devices  or  slaves.  For example, lsblk
              --nodeps /dev/sda prints information about the sda device only.
```

**Comment by jsafrane** [comment]
Dup of #13212

**Comment by jsafrane** [comment]
And fix is here: #43378. Please check that the reported event is understandable.

**Comment by neelance** [comment]
I've seen #13212. Maybe they are the same, but I wasn't sure. From a user perspective I only see the `partition` field.

**Comment by msau42** [comment]
This should be fixed.  Please reopen if you still see an issue

/close
