### ISSUE TITLE
Static pod not being stopped when removing manifest

### ISSUE THREAD

**Issue by kanor1306** [kubernetes/kubernetes#43292]
**Is this a request for help?** No

**What keywords did you search in Kubernetes issues before filing this one?** static-pod, etcd, remove, delete

---

**Is this a BUG REPORT or FEATURE REQUEST?** BUG REPORT

**Kubernetes version** : v1.5.1

**Environment**:
Two independent clusters, same configuration and hardware. Only difference, cluster A uses a single node etcd cluster deployed in the master. Cluster B uses an external multinode etcd cluster. 
- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release):  CentOS 7.2
- **Kernel** (e.g. `uname -a`): 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: Puppet
- **Others**: etcd3

**What happened**: In cluster B (external multinode) when moving the manifest of a static pod out of the folder where kubelet watches, the static pod keeps running. If you delete it with kubectl, it is recreated. If you look in etcd the pod is not removed. Only way to make the static pod stop: 
- move the manifest file out of the static pods folder
- remove the entry of the pod from etcd
- kill the docker container with docker stop/docker rm.  

In cluster A (etcd in the master): moving the manifest out of the static pods folder will stop the pod.

**What you expected to happen**: moving the manifest out of the static pods folder will stop the pod.

**How to reproduce it** (as minimally and precisely as possible):
In my case, having an external etcd, and moving the static pod manifest out of the static pod folders will reproduce the issue. Both cluster are created by using a custom script based in the guide Kubernetes from scratch.

**Comment by xwisen** [comment]
When use `kubelet` alone, I got the same problem. My steps are as follows:
```shell
[root@csv-dcosstorage10 manifests]# mv etcd.yaml ../
[root@csv-dcosstorage10 manifests]# docker ps
CONTAINER ID        IMAGE                                                                                         COMMAND                  CREATED             STATUS              PORTS               NAMES
6e69523cf673        reg.dnt/coreos/etcd@sha256:054f37c560ae9449c8b31451f1058b3f92de95c2c4934c285d4b49b07bf3b2e2   "/bin/sh -c '/usr/loc"   20 seconds ago      Up 20 seconds                           k8s_etcd-container_etcd-server-csv-dcosstorage10_system_c8e9ab092fe0f8d6770f466f8041af0a_3
047f3325adfb        reg.dnt/google_containers/pause:3.0                                                           "/pause"                 5 minutes ago       Up 5 minutes                            k8s_POD_etcd-server-csv-dcosstorage10_system_c8e9ab092fe0f8d6770f466f8041af0a_0
[root@csv-dcosstorage10 manifests]# date -R
Tue, 25 Apr 2017 09:48:19 +0800
[root@csv-dcosstorage10 manifests]# ls -lh
total 0
[root@csv-dcosstorage10 manifests]# ps -axf | grep kubelet
10586 pts/0    S+     0:00  |       \_ grep --color=auto kubelet
 6331 ?        Ssl    0:11 /usr/local/bin/kubelet --register-schedulable=false --allow-privileged=true --logtostderr=true --address=0.0.0.0 --port=10250 --cluster-dns=10.0.1.1 --cluster-domain=cluster.local --pod-infra-container-image=reg.dnt/google_containers/pause:3.0 --api-servers=http://127.0.0.1:8080 --pod-manifest-path=/data/kubernetes/manifests
[root@csv-dcosstorage10 manifests]# pwd
/data/kubernetes/manifests
[root@csv-dcosstorage10 manifests]# date -R
Tue, 25 Apr 2017 09:52:32 +0800
[root@csv-dcosstorage10 manifests]# docker ps | grep etcd
6e69523cf673        reg.dnt/coreos/etcd@sha256:054f37c560ae9449c8b31451f1058b3f92de95c2c4934c285d4b49b07bf3b2e2   "/bin/sh -c '/usr/loc"   6 minutes ago       Up 6 minutes                            k8s_etcd-container_etcd-server-csv-dcosstorage10_system_c8e9ab092fe0f8d6770f466f8041af0a_3
047f3325adfb        reg.dnt/google_containers/pause:3.0                                                           "/pause"                 11 minutes ago      Up 11 minutes                           k8s_POD_etcd-server-csv-dcosstorage10_system_c8e9ab092fe0f8d6770f466f8041af0a_0
[root@csv-dcosstorage10 manifests]# date -R
Tue, 25 Apr 2017 09:53:11 +0800
```
kubelet/docker/os version:
```shell
[root@csv-dcosstorage10 manifests]# kubelet --version
Kubernetes v1.6.1
[root@csv-dcosstorage10 manifests]# docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64
[root@csv-dcosstorage10 manifests]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by xiang90** [comment]
I hit the same problem.

**Comment by xiang90** [comment]
I dig into it a little bit.

So in my case, once the kubelet cannot contact api server it wont kill the removed static pod. It keeps on trying to contact api server to update the mirror pod information. 

once api server is up, kubelet will kill the static pod eventually.

**Comment by relaxdiego** [comment]
I've observed that this bug is not present in v1.8.7 but came back in v1.9.2

**Comment by yifan-gu** [comment]
Hitting the issue again in 1.9.3
