### ISSUE TITLE
Watch one object by name?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#43299]
I'm trying to figure out how to do a watch on a single-object, by name.

client-go has `Watch` which takes `ListOptions` which can filter by label, but not by name.  Is there a magic label which matches the name?

I had a look at kubectl (`kubectl get pod <name> --watch --v=8`), which does a GET on `/api/v1/namespaces/<ns>/pods/<name>` followed by a GET on `/api/v1/watch/namespaces/<ns>/pods/<name>?resourceVersion=0`.  Cool, but..

* This method does not seem to be exposed by client-go?
* resourceVersion = 0, because kubectl did a get, not a list, so I think kubectl is not quite right here (?) (I also don't see a resourceVersion in the first reply.)

**Comment by liggitt** [comment]
watch with a field selector of `metadata.name=<name>`:

```
/api/v1/watch/namespaces/<ns>/pods?fieldSelector=metadata.name%3D<name>
```

**Comment by liggitt** [comment]
also, as of https://github.com/kubernetes/kubernetes/pull/41722 that's the method kubectl uses

**Comment by justinsb** [comment]
Thank you @liggitt  - two steps ahead as always :-)

**Comment by liggitt** [comment]
(btw, the client library will do this for you, but if you're building the URL manually, watch out for names containing special characters... see https://github.com/kubernetes/kubernetes/pull/28112 for fieldSelector escaping and server-side handling)

**Comment by inoam** [comment]
> watch with a field selector like this:
> 
> ```
> opts := metav1.ListOptions{
>   FieldSelector: fields.OneTermEqualSelector(api.ObjectNameField, podName).String(),
> }
> kubeClient.Core().Pods("myns").Watch(opts)
> ```
> 
> which issues a watch of
> 
> ```
> /api/v1/namespaces/<ns>/pods?watch=true&fieldSelector=metadata.name%3D<escaped name>
> ```

Well, that helped me as well when using informer with tweakList (no examples in documentation). 
Let's push it a bit: can I watch single resource, when only some of it's fileds changed? for example I want to get notified only in case some label on specific pod has changed? (sure I can do it on client code...)

**Comment by liggitt** [comment]
> can I watch single resource, when only some of it's fileds changed? for example I want to get notified only in case some label on specific pod has changed? (sure I can do it on client code...)

No, watches are for the entire object.

**Comment by s3rj1k** [comment]
This deserves to be in official docs, thanks @liggitt

**Comment by liggitt** [comment]
You *can* watch a single object with a metadata.name field selector. You cannot watch just one field within the object, the watch covers the whole object.
