### ISSUE TITLE
VM name has overwritten nodeName after enabling cloud provider

### ISSUE THREAD

**Issue by childsb** [kubernetes/kubernetes#43318]
Have master and node enable vsphere cloud provider, then restart the services. When the node service is restarted, the node name is overwritten with vSphere's VM names.

**Comment by tusharnt** [comment]
CC @BaluDontu , @divyenpatel

**Comment by wongma7** [comment]
We've determined this is not a bug, so this can be closed.

However we'd like to know the 'official' recommendation wrt instance VM 'name-ability' and organization? I'm guessing tags? https://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.vsphere.vcenterhost.doc%2FGUID-379F40D3-8CD6-449E-89CB-79C4E2683221.html

**Comment by spiffxp** [comment]
/assign
closing per above comment
