### ISSUE TITLE
Scheduling policy 

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#43317]
In https://github.com/kubernetes/kubernetes/pull/43271#issuecomment-287398475 @derekwaynecarr said "i would like @kubernetes/sig-scheduling-misc to start thinking about a PodSchedulingPolicy object that I could use to provide more granular control where its needed. So if I do not want to let pods in namespace A stalk pods in namespace B, I should be able to control that via policy. For example, I do not want to let users stalk any of the kube-system components (scheduler, etc.) unless I entitle them to do that action."

I think we need to define "stalk" a bit more specifically, but we do already have a [scheduler policy object](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/api/v1/types.go) that is read from disk; @bsalamat is in the process of changing it to be taken from a ConfigMap (#41600). I assume we could just add whatever you have in mind to this scheduler config object?

cc/ @kubernetes/sig-scheduling-feature-requests @bsalamat @liggitt

**Comment by timothysc** [comment]
Why wouldn't this be an admission control policy?  Am I missing something?

**Comment by bsalamat** [comment]
+1 to Tim's point. Wouldn't this be an admission policy?

**Comment by davidopp** [comment]
That's a good point. I think the feature request needs some clarification, but probably you're right that an admission controler is the right way to implement this.

**Comment by bsalamat** [comment]
As discussed above, this can be done via admission policy. Alternatively, one can have ResourceQuota per namespace (and soon per priority per namespace) that can address the requested feature. I think we can close this issue.
