### ISSUE TITLE
Clean up pre-ControllerRef compatibility logic

### ISSUE THREAD

**Issue by enisoc** [kubernetes/kubernetes#43323]
As of 1.6, most workload controllers respect [ControllerRef](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/controller-ref.md) to avoid interfering with each other. However, kubectl 1.6 still had to support talking to a 1.5 server, so client-side compatibility logic was introduced in #43114 and #43239.

According to the [version skew guidelines](https://github.com/kubernetes/community/blob/854e9518703851ec79e26a47d46a0c70d829fe37/contributors/design-proposals/versioning.md#supported-releases-and-component-skew), we no longer need to support talking to 1.5 servers as of the **v1.7** milestone. At that time, the added compatibility functions (ending in `V15`) can be removed and replaced with calls to the normal 1.6+ functions (without the suffix).

**Comment by kargakis** [comment]
@kubernetes/sig-apps-misc

**Comment by wanghaoran1988** [comment]
@kargakis I can take this

**Comment by kargakis** [comment]
@wanghaoran1988 @enisoc self-assigned this so you may want to sync with him before starting any work.

**Comment by enisoc** [comment]
@wanghaoran1988 You are welcome to take this if you want. I'd be happy to review related PRs.

**Comment by wanghaoran1988** [comment]
@enisoc Thanks, working on that now.
