### ISSUE TITLE
StatefulSetHasDesiredReplicas condition should check ObservedGeneration

### ISSUE THREAD

**Issue by enisoc** [kubernetes/kubernetes#43325]
StatefulSet now [updates ObservedGeneration](https://github.com/kubernetes/kubernetes/pull/42429) as of 1.6. That means the TODO on [StatefulSetHasDesiredReplicas](https://github.com/kubernetes/kubernetes/blob/072e68f0a6da90f22333a96273e0107db3b2a1b8/pkg/client/unversioned/conditions.go#L82) can be fixed in 1.7. We could not fix it in 1.6 because that code is used by kubectl, which must work against servers that are one minor version ahead of or behind the client.

**Comment by wanghaoran1988** [comment]
I am volunteered to take this job if no one start working on this.

**Comment by enisoc** [comment]
@wanghaoran1988 I don't think anyone's working on it, so you are welcome to take it. Feel free to tag me as a reviewer. Thanks!
