### ISSUE TITLE
Restore ability to specify "all namespaces" in podAffinityTerm.namespaces

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#43320]
#43271 by @liggitt removed the ability to specify "all namespaces" in `podAffinityTerm.namespaces` because it was relying on distinguishing between empty and nil list which doesn't really work. We should decide if we want to add this feature back, and if so, how to do it. @liggitt mentioned the overall options here: https://github.com/kubernetes/kubernetes/issues/43203#issuecomment-287237992

Personally I think special-casing `*` is the simplest and most obvious-to-the-user thing to do. I started a PR to do it (#43278) before @liggitt had done his PR, and if you ignore the parts that are duplicates of what @liggitt's PR did, you can see that it only requires a few lines of code (plus some additional tests, which we really should have had all along).

This would be for 1.7.

@kubernetes/sig-scheduling-feature-requests

**Comment by timothysc** [comment]
+1 for *... are we punting this out to 1.6?

**Comment by wanghaoran1988** [comment]
@davidopp Are you still working on this? If not I can help here. :)

**Comment by davidopp** [comment]
I'm not working on it. Feel free to send a PR to implement it. Feel free to take anything that is useful from the PR that I had started (#43278).

**Comment by timothysc** [comment]
Closed #43525
