### ISSUE TITLE
API server cannot parse query parameter propagationPolicy sent with a delete request

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#43329]
https://github.com/kubernetes/kubernetes/pull/35806 makes API server accepts DeleteOptions as a query parameter, but APIserver cannot parse `?propagationPolicy=orphan`, which is a new field added in 1.6.
```bash
s$ curl -X DELETE http://localhost:8080/api/v1/namespaces/default/replicationcontrollers/redis?propagationPolicy=Orphan
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "converting (url.Values).[]string.[]string to (v1.DeleteOptions).*v1.DeletionPropagation.v1.DeletionPropagation: couldn't copy '[]string' into 'v1.DeletionPropagation'; didn't understand types",
  "code": 500
}
```
Probably it's a bug in the parameterCodec.

cc @lavalamp @smarterclayton @bdbauer

**Comment by caesarxuchao** [comment]
IMO this is not a 1.6 release blocker

**Comment by liggitt** [comment]
does this apply to all DeleteOptions fields? does a 1.5 server handle the orphanDependents field sent by https://github.com/kubernetes/kubernetes/pull/40576 correctly?

**Comment by caesarxuchao** [comment]
No, `?orphanDependents=true` is handled correctly by the apiserver built from head.

And for #40576, because our generated clients still encode DeleteOptions as body, so they are not affected.

**Comment by dims** [comment]
@caesarxuchao @liggitt - we can close this one right?

**Comment by lostllama** [comment]
@caesarxuchao @liggitt @dims 

Why was this closed?

I'm using a Kubernetes 1.9 cluster and this is still an issue. If I pass propagationPolicy as part of the query string (as per the documentation), I still receive the same error message.  If I pass a DeleteOptions object with the propagationPolicy within, it works.

**Comment by caesarxuchao** [comment]
@lostllama what documentation were you referring to? Is it the openapi doc?

I don't know if we can just deprecate the support of query parameters for DELETE. I understand it's a breaking change, but it has been broken for a year.

**Comment by lavalamp** [comment]
Everything in delete needs to be moved to query parameters (unfortunately)
as it is apparently non-standard to have a body in a delete request.

**Comment by caesarxuchao** [comment]
cc @roycaihw

**Comment by lostllama** [comment]
@caesarxuchao The DELETE operation [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#-strong-write-operations-strong--37) states that propagationPolicy is a query parameter.

**Comment by matti** [comment]
GKE default version is still 1.9.7
