### ISSUE TITLE
Create kubectl reaper version skew test

### ISSUE THREAD

**Issue by enisoc** [kubernetes/kubernetes#43324]
We found a version skew issue with Deployment reaper in #43159, but it was only incidentally inferred while investigating a [failure to detect created ReplicaSets](https://github.com/kubernetes/kubernetes/issues/42738#issuecomment-285158244).

We should create an explicit version skew test that would have caught such reaper issues automatically.

**Comment by wanghaoran1988** [comment]
@enisoc Would you like point me how to add this skew test? I found we have [DeleteDepoyment](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/deployment.go#L66) e2e test, just add this to the jenkins job? but how to? thanks.

**Comment by enisoc** [comment]
@wanghaoran1988 I don't know how yet. :) This was a TODO suggested by @pwittrock. He may have some pointers?

**Comment by crimsonfaith91** [comment]
I never wrote a skew test before. Will the steps below appropriate for creating the version skew test?

1. introduce 2 helper functions in [util.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go):
- `SkipUnlessKubectlVersionEquals()` for `kubectl v1.6`
- `SkipUnlessServerVersionEquals()` for `cluster v1.5`

2. write a function named `testDeleteDeploymentVersionSkew` that is similar to [this function]:(https://github.com/kubernetes/kubernetes/blob/master/test/e2e/workload/deployment.go#L248)
- verify deployment, all replicasets, and all pods are deleted
- both kubectl and server versions are arguments for the function

Referring to the [test grid](http://k8s-testgrid.appspot.com/1.6-1.7-kubectl-skew#gce-1-7-1.6-cvm), step 1 may be unnecessary. Any feedback?

**Comment by janetkuo** [comment]
@crimsonfaith91 

Take `[k8s.io] Kubectl client [k8s.io] Kubectl rolling-update should support rolling-update to same image [Conformance]` in http://k8s-testgrid.appspot.com/1.6-1.7-kubectl-skew#gce-1-7-1.6-cvm for example -- it is running 1.6 kubectl and 1.6 kubectl e2e test (https://github.com/kubernetes/kubernetes/blob/release-1.6/test/e2e/kubectl.go#L1217-L1251) against 1.7 server. 

The first step is to add a kubectl reaper e2e test under test/e2e/kubectl.go. Then include this test in the skew test list (maybe need to add or modify test jobs in https://github.com/kubernetes/test-infra). 

You don't need `SkipUnlessKubectlVersionEquals`, `SkipUnlessServerVersionEquals` or `testDeleteDeploymentVersionSkew`.

**Comment by kow3ns** [comment]
We should fix this by removing the reapers altogether
