### ISSUE TITLE
Clean up Deployment overlap annotation code

### ISSUE THREAD

**Issue by enisoc** [kubernetes/kubernetes#43322]
The Deployment overlap annotation (`deployment.kubernetes.io/error-selector-overlapping-with`) is no longer populated nor used by 1.6+ on the server side. However, in #43239 we maintained knowledge of the annotation for 1.6 clients in case they talk to pre-1.6 servers. That PR also adds code to clean up the annotation whenever it's found in 1.6+ clusters, so that pre-1.6 clients don't see it and make the wrong assumptions.

The code handling this annotation should be removed when all the following conditions are met:
* We no longer support a 1.5.x client talking to the latest server version.
* We no longer support upgrading the server directly from 1.5.x to the latest version.

The soonest milestone that meets both conditions according to the [versioning guidelines](https://github.com/kubernetes/community/blob/854e9518703851ec79e26a47d46a0c70d829fe37/contributors/design-proposals/versioning.md) is **v1.8**. This issue should be moved to that milestone once it exists.

**Comment by janetkuo** [comment]
TODOs:

- [ ] deployment controller: pkg/controller/deployment/deployment_controller.go
- [ ] deployment util: pkg/controller/deployment/util/deployment_util.go
- [ ] deployment reaper: pkg/kubectl/stop.go
- [ ] deployment describer: pkg/printers/internalversion/describe.go

**Comment by wanghaoran1988** [comment]
I can help on this

**Comment by janetkuo** [comment]
@wanghaoran1988 thanks, feel free to send patches
