### ISSUE TITLE
Feature request: Allow controlling HPA scale-down rate

### ISSUE THREAD

**Issue by f-w** [kubernetes/kubernetes#43350]
I deployed an Elasticsearch cluster to an on-premise Openshift v1.3. The pods use local ephemeral *EmptyDir* volume for storage because I found performance is unacceptable with GlusterFS backed persistent volume. An [ES engineering blog](https://www.elastic.co/blog/performance-considerations-elasticsearch-indexing) also advised against using network share. 

To prevent data loss for this type of shared nothing stateful app cluster, there is a node reduction rate tolerance cap. For example, if ES shard replica is 1 (i.e. 1 extra copy of each shard for a total of 2 copies. ES ensures copies reside on separate nodes), then if 2 or more pods are brought down quickly without leaving adequate recovery window in between for the cluster to rebalance data, partial data loss will likely to occur.

During a rolling deployment, I am able to control pod killing rate with 3 configs - *maxUnavailable*, *maxSurge* and pod readinessProbe's *timeoutSeconds*. I would like to enable HPA for this cluster but found HPA doesn’t honor these settings and there is no other way to control the reduction rate.

**Comment by kargakis** [comment]
The reduction rate is controlled more tightly in StatefulSets in comparison to Deployments so you probably want to have a look at sts[1]. HPA simply updates the scale in the underlying controller (Deployment, StatefulSets, ...) so I don't think there is anything that can be done at that level. cc: @kubernetes/sig-apps-misc 

[1] https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

**Comment by smarterclayton** [comment]
Generally you would set a terminationGracePeriodSeconds on a pod that is at least as long as you expect a move to take (5-10m) and then register a preStop hook for your pod that starts the rebalance / waits for it to complete, then returns.  The process does not receive SIGTERM under after preStop returns.

**Comment by f-w** [comment]
Thanks all for inputs.
I'll wait for sts available in our OS env and give a shot.
preStop hook gives more accurate timing control and it's something I can try now. But having to write app-specific script is usually an overkill as opposed to toggling a app-agnostic setting.

**Comment by f-w** [comment]
@smarterclayton, customizing terminationGracePeriodSeconds  and preStop works like a charm.

**Comment by kargakis** [comment]
It would  be great to get this documented:
https://github.com/kubernetes/kubernetes.github.io/issues/3502
