### ISSUE TITLE
The CRI dockershim doesn't support ClusterFirstWithHostNet

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#43352]
**Kubernetes version** (use `kubectl version`):

HEAD (~v1.6.0-beta.4)

**Environment**: any
**What happened**:

I want to use ClusterFirstWithHostNet which was implemented in https://github.com/kubernetes/kubernetes/pull/29378, but only dockertools (legacy/non-CRI) was updated to support this feature.

The CRI dockershim should be modified to support this rewriting the resolv.conf file of Pods with HostNetwork=true as well.

This is a bug in v1.6, I hope it can be prioritized to be fixed in v1.6.1, since it's blocking me from using CRI. Since CRI is enabled by default, it's expected that it should have feature parity with the earlier implementation.

@kubernetes/sig-node-bugs @freehan @yujuhong @feiskyer @vefimova @bowei @thockin

**Comment by cmluciano** [comment]
Related #43234

**Comment by thockin** [comment]
@vefimova - I guess I didn't realize these crossed paths.  Do you have time
to take a look?

**Comment by feiskyer** [comment]
Will take a look

**Comment by thockin** [comment]
Thanks!  Ping me directly on this.

**Comment by feiskyer** [comment]
@thockin Filed #43368 for supporting it in CRI.
