### ISSUE TITLE
15 second timeout for etcd migrate-if-needed.sh upgrade seems optimistic

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#43362]
We currently have the following liveness probe for etcd:

```
"livenessProbe": {
      "httpGet": {
        "host": "127.0.0.1",
        "port": {{ port }},
        "path": "/health"
      },
      "initialDelaySeconds": 15,
      "timeoutSeconds": 15
    },
```

https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/etcd/etcd.manifest#L67-L68

15 seconds (or is it 30?) for an upgrade of etcd seems very optimistic, particularly as we go through a few versions along the way.  On a brand new, empty etcd cluster it took 7 seconds.

I'm guessing that the time taken is proportional to the amount of data in etcd.  What is the biggest etcd cluster we have tested and did the liveness probe trigger - and if so, what happened? :-)

AFAICT, the liveness probe times have not been updated after we added `migrate-if-needed.sh`.

**Comment by ethernetdan** [comment]
@mml any thoughts?

**Comment by mml** [comment]
Our worst case measurements using large mock clusters (with a lot of nodes, pods, and deployments) were about 27s to upgrade and 34s to downgrade.  Both seem too short for the container to have been killed and respawned, so I'm guessing this all happens within a single run of the container.

**Comment by ethernetdan** [comment]
Since @mml is confident, I think this can be closed
