### ISSUE TITLE
Got  error "Too many EBS volumes attached to node" when create pod using ebs volume

### ISSUE THREAD

**Issue by chao007** [kubernetes/kubernetes#43367]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1369+ae6a5d2bf34c14-dirty", GitCommit:"ae6a5d2bf34c14f7d00c853660972a721eb02f61", GitTreeState:"dirty", BuildDate:"2017-03-20T02:20:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1369+ae6a5d2bf34c14-dirty", GitCommit:"ae6a5d2bf34c14f7d00c853660972a721eb02f61", GitTreeState:"dirty", BuildDate:"2017-03-20T02:20:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
aws
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
hack/local-up-cluster.sh
- **Others**:

**What happened**:
After k8s env is ready, I create 50 pods using ebs volume, then I Ctrl-c to terminate the k8s env and restart a new one, and create one pod using ebs volume, bug got error "Too many EBS volumes attached to node "
**What you expected to happen**:
Pod using ebs volume is running

**How to reproduce it** (as minimally and precisely as possible):
1.Create 50 pods using ebs volume
2.Ctrl-c the script local-up-cluster.sh
3. Re-run the script local-up-cluster.sh
4. Create one pod using ebs volume
5. Pod is not running
[root@ip-172-18-9-70 ebstest]# kubectl create -f pod1.yaml 
pod "mypod1" created
[root@ip-172-18-9-70 ebstest]# kubectl get pods
NAME      READY     STATUS              RESTARTS   AGE
mypod1    0/1       ContainerCreating   0          6s
[root@ip-172-18-9-70 ebstest]# kubectl describe pods mypod1
Name:		mypod1
Namespace:	default
Node:		ip-172-18-9-70.ec2.internal/172.18.9.70
Start Time:	Mon, 20 Mar 2017 02:16:48 -0400
Labels:		name=frontendhttp
Annotations:	<none>
Status:		Pending
IP:		
Controllers:	<none>
Containers:
  myfrontend:
    Container ID:	
    Image:		aosqe/hello-openshift
    Image ID:		
    Port:		80/TCP
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Environment:	<none>
    Mounts:
      /tmp from aws (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-10b6n (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  aws:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	ebs1
    ReadOnly:	false
  default-token-10b6n:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-10b6n
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	node.alpha.kubernetes.io/notReady=:Exists:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable=:Exists:NoExecute for 300s
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  16s		16s		1	default-scheduler			Normal		Scheduled	Successfully assigned mypod1 to ip-172-18-9-70.ec2.internal
  16s		6s		5	attachdetach				Warning		FailedMount	Failed to attach volume "ebs1" on node "ip-172-18-9-70.ec2.internal" with: Too many EBS volumes attached to node ip-172-18-9-70.ec2.internal.

**Anything else we need to know**:
Some log from /tmp/kube-controller-manager.log
I0320 02:17:56.160238    4894 reconciler.go:205] Attempting to start AttachVolume for volume "kubernetes.io/aws-ebs/aws://us-east-1d/vol-015ceb5cf1537b360" to node "ip-172-18-9-70.ec2.internal"
I0320 02:17:56.260434    4894 reconciler.go:205] Attempting to start AttachVolume for volume "kubernetes.io/aws-ebs/aws://us-east-1d/vol-015ceb5cf1537b360" to node "ip-172-18-9-70.ec2.internal"
W0320 02:17:56.348210    4894 aws.go:1270] Could not assign a mount device.  mappings=map[bo:vol-0d0ce0c64b953cb9e cg:vol-09c0337a9c78294b9 ct:vol-0ae25d773ebf16393 cz:vol-06eed5ca4e1507ded dd:vol-004cb7f1649b487e5 bc:vol-0380cbb29b95a54b8 do:vol-012ea38e2e2889361 dq:vol-0ef33ffb9ca436a63 bw:vol-0b4ad887fa1427993 bl:vol-001df7fc90178d17a bz:vol-011ae80746df45e2f b:vol-07c62ed06dfb371d3 da:vol-0d7b41751b7a4bc2e dm:vol-0728d55582793c0cf ds:vol-0cb0b7886e6d8f397 ce:vol-064d84e87ad589235 de:vol-0d9c0de4b57138191 bn:vol-0840e61b9caf5fee7 cd:vol-0efc82e6e37e1eb49 br:vol-0e5dfc8d5718ef0ed bv:vol-047f6eeebf117ac54 ck:vol-0193e24b3acd32fe4 ch:vol-00f054ad6be4527aa cw:vol-0555194da16b796b0 dg:vol-0cc2c6b2108451e98 dl:vol-01e6cdec6593ef08a dr:vol-0e5bc76145bcdfa2c bj:vol-0715f6b30c4a9a2db cs:vol-063b3412d8d6730bb dc:vol-099463cf09e4a7b14 dk:vol-09847ca3a05803eb0 ba:vol-0f976055b81fbc6e2 bq:vol-0b65f6a9baea7abbf cf:vol-0bacdc3b65985b656 cy:vol-013ed298b13fc1221 di:vol-00481a88ec0d1d096 bf:vol-0627a389c030e7804 ci:vol-0dc59c9d402d75998 dw:vol-09f6b645f8562c09b bb:vol-09383fb93df0b6460 bt:vol-0cdf3664e6fc9fcfe cj:vol-08d943869e72d10d0 cr:vol-00095ddceae1a96ed cv:vol-0ae052d3788deb58b dn:vol-01936afe5d3fe9376 be:vol-0968ba86dd4fa87b8 bu:vol-0b459bcbc9466bf6b ca:vol-05ab9f2bcafa78fc4 cm:vol-03358e66623c2acf8 dh:vol-0ebfa135d6b48cd4b bk:vol-0c4dbaca88d8b9e1e bx:vol-07e235395fdac7865 bg:vol-0a5ce9181020ef3e5 cb:vol-0032ddc577882f9d7 cc:vol-06901a5b1df02efc7 a1:vol-0ebaae0f583ce9d56 du:vol-06c1749e928a6698d dx:vol-0af89b77ecb4def3e bh:vol-00ec4245a81855526 cp:vol-046c4b8de43e949e8 cq:vol-05879fe719091fafe df:vol-0c92655d71d747a55 dt:vol-037f319b176154d20 dv:vol-0c81ff4514a4fc367 dp:vol-0ead6ce8409c37004 cx:vol-02ca744b213d16363 cl:vol-032178acfe34b1f4e cn:vol-0cfd132118ce37582 co:vol-0b1c686b9ff8eb9e9 bi:vol-06f9146d89494a33a bm:vol-069274e869cf05075 bs:vol-0488c610cb7c297ce bp:vol-09996441eaba44815 by:vol-04bf60f2a1a560b0e db:vol-0be00ef6c65fb1615 dj:vol-00ceee6d1e493b4ef bd:vol-0107e601c861588a9 cu:vol-049880ef3fe038d4e], error: no devices are available
E0320 02:17:56.348275    4894 attacher.go:73] Error attaching volume "aws://us-east-1d/vol-015ceb5cf1537b360": Too many EBS volumes attached to node ip-172-18-9-70.ec2.internal.
E0320 02:17:56.348329    4894 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/aws-ebs/aws://us-east-1d/vol-015ceb5cf1537b360\"" failed. No retries permitted until 2017-03-20 02:19:00.348309059 -0400 EDT (durationBeforeRetry 1m4s). Error: Failed to attach volume "ebs1" on node "ip-172-18-9-70.ec2.internal" with: Too many EBS volumes attached to node ip-172-18-9-70.ec2.internal.
I0320 02:17:56.348523    4894 round_trippers.go:395] PATCH https://localhost:6443/api/v1/namespaces/default/events/mypod1.14ad829070609e39
I0320 02:17:56.348513    4894 event.go:217] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"mypod1", UID:"ccb6e390-0d34-11e7-8caa-0ecb7d4ecce4", APIVersion:"v1", ResourceVersion:"294", FieldPath:""}): type: 'Warning' reason: 'FailedMount' Failed to attach volume "ebs1" on node "ip-172-18-9-70.ec2.internal" with: Too many EBS volumes attached to node ip-172-18-9-70.ec2.internal.

**Comment by chao007** [comment]
I also restart the node instance then lauch the k8s env, it does not work

**Comment by ntfrnzn** [comment]
This is apparently expected behavior, but perhaps not well documented
https://github.com/kubernetes/kubernetes/blob/a2c7eb275443a5afea4052094a07daf627e4a724/pkg/cloudprovider/providers/aws/aws.go#L182

**Comment by jingxu97** [comment]
@chao007, I am not sure the workflow you described. I assume when you create 50 pods with ebs volume, your cluster was already up. "Ctrl-c the script local-up-cluster.sh" will this stop the cluster?
Also could you check with "kubectl get pods" to see whether all the pods still exist? You need to delete those pods to release the volume resources.
