### ISSUE TITLE
etcd2 -> 3 upgrade: do we need to go read-only for multi-master?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#43364]
The CoreOS blog for kubernetes upgrades stated that we should put a HA cluster into read-only mode before doing the upgrade: https://coreos.com/blog/migrating-applications-etcd-v3.html

But the upgrade docs do not reference this: https://coreos.com/etcd/docs/latest/upgrades/upgrade_3_0.html

Can we confirm that we do not need to go read-only during a etcd2 -> etcd3 upgrade, and that we have e2e test coverage that writing to a HA cluster during an etcd2 -> etcd3 upgrade is not problematic?

**Comment by ethernetdan** [comment]
@hongchaodeng @xiang90 any thoughts?

**Comment by hongchaodeng** [comment]
> Can we confirm that we do not need to go read-only during a etcd2 -> etcd3 upgrade

No, as long as it's offline. More detailed steps: shutdown your etcd server, migrate the data, and then restart.

**Comment by justinsb** [comment]
Once we shut down the etcd cluster though, the apiserver is read-only?

It sounds like you're saying that it is not safe to write to an etcd HA cluster during the etcd2 -> etcd3 procedure, and so that there is no option where we do not take an outage on the API.

What do our e2e tests do for testing of HA etcd2 -> etcd3 migration cc @kubernetes/sig-testing-misc ?

**Comment by mml** [comment]
@justinsb To my knowledge, there are no e2e etcd tests covering an HA setup.  See https://k8s-testgrid.appspot.com/etcd-upgrades

**Comment by ethernetdan** [comment]
@mml are we blocking the release for this?

**Comment by mml** [comment]
@ethernetdan Yes.  I think we need clear instructions for HA users, too.  The current kubernetes/kubernetes.github.io#2767 should cover non-HA users.

When @justinsb has done an upgrade of a k8s cluster running on HA etcd, we will add a paragraph or two describing the process.

**Comment by ethernetdan** [comment]
Issue has been documented, discussion of HA upgrade in #43600
