### ISSUE TITLE
Cluster Deployment Issue with OpenStack Heat (salt://kubelet/ca.crt not found)

### ISSUE THREAD

**Issue by magreiner** [kubernetes/kubernetes#43389]
**Kubernetes version** (use `kubectl version`):
Kubernetes release: v1.6.0-beta.3 (same behavior with the previous releases)

**Environment**:
- **Cloud provider or hardware configuration**:
  OpenStack Heat

- **OS** (e.g. from /etc/os-release):
  Ubuntu 16.04.2 LTS (client machine)

- **Kernel** (e.g. `uname -a`):
  Linux control 4.4.0-36-generic 

**What happened**:
I'm trying to deploy a kubernetes cluster on OpenStack (kube-up.sh), using the official tutorial (https://kubernetes.io/docs/getting-started-guides/openstack-heat/).

Unfortunately I'm not able connect to kubernetes-master. 
I've checked the logs (/var/log/salt/minion) and the salt-minion reports the error: 

```
2017-03-20 15:51:17,783 [salt.loaded.int.states.file][WARNING ][9745] State for file: /var/log/kube-apiserver.log - Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, yet 'replace' was set to 'True'. As there is no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily.
2017-03-20 15:51:17,784 [salt.loaded.int.states.file][WARNING ][9745] State for file: /var/log/kube-apiserver-audit.log - Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, yet 'replace' was set to 'True'. As there is no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily.

2017-03-20 15:51:53,249 [salt.state       ][ERROR   ][9745] Source file salt://kubelet/ca.crt not found

2017-03-20 15:51:53,263 [salt.loaded.int.states.file][WARNING ][9745] State for file: /var/log/kube-controller-manager.log - Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, yet 'replace' was set to 'True'. As there is no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily.
2017-03-20 15:51:53,272 [salt.loaded.int.states.file][WARNING ][9745] State for file: /var/log/kube-scheduler.log - Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, yet 'replace' was set to 'True'. As there is no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily.
2017-03-20 15:51:58,981 [py.warnings      ][WARNING ][10939] /usr/lib/python2.7/site-packages/salt/states/cmd.py:1044: DeprecationWarning: The legacy user/group arguments are deprecated. Replace them with runas. These arguments will be removed in Salt Oxygen.

```
The salt directory /srv/salt/kubelet/ has no ca.crt, so i tried to use the ca.crt from directory /srv/kubernetes/ and salt works, but the service /usr/local/bin/kubelet report an authentication error with openstack (error: failed to run Kubelet: could not init cloud provider "openstack": Authentication failed).

**How to reproduce it** (as minimally and precisely as possible):
```
source DemoProjekt-openrc.sh # containing the credentials for OpenStack
export EXTERNAL_NETWORK="External"
export CREATE_IMAGE=false
export IMAGE_ID=cf47efb4-046e-4a01-9efa-0e5edfde4f1d
export KUBERNETES_PROVIDER=openstack-heat; ./cluster/kube-up.sh
ubuntu@control:~/kubernetes$ ./cluster/kube-up.sh
... Starting cluster using provider: openstack-heat
... calling verify-prereqs
swift client installed
glance client installed
nova client installed
heat client installed
openstack client installed
... calling verify-kube-binaries
... calling kube-up
kube-up for provider openstack-heat
[INFO] Execute commands to create Kubernetes cluster
[INFO] Uploading kubernetes-server-linux-amd64.tar.gz
kubernetes-server.tar.gz
[INFO] Uploading kubernetes-salt.tar.gz
kubernetes-salt.tar.gz
/usr/local/lib/python2.7/dist-packages/novaclient/client.py:278: UserWarning: The 'tenant_id' argument is deprecated in Ocata and its use may result in errors in future releases. As 'project_id' is provided, the 'tenant_id' argument will be ignored.
  warnings.warn(msg)
[INFO] Key pair already exists
Stack not found: kube-stack
[INFO] Create stack kube-stack
+---------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| Field               | Value                                                                                                                                   |
+---------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| id                  | 628f4d30-45ce-45b1-bb80-87cbd1fa4732                                                                                                    |
| stack_name          | kube-stack                                                                                                                              |
| description         | Kubernetes cluster with one master and one or more worker nodes (as specified by the number_of_minions parameter, which defaults to 3). |
|                     |                                                                                                                                         |
| creation_time       | 2017-03-20T15:48:26                                                                                                                     |
| updated_time        | None                                                                                                                                    |
| stack_status        | CREATE_IN_PROGRESS                                                                                                                      |
| stack_status_reason |                                                                                                                                         |
+---------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
... calling validate-cluster
Cluster status CREATE_IN_PROGRESS
Cluster status CREATE_IN_PROGRESS
Cluster status CREATE_IN_PROGRESS
Cluster status CREATE_IN_PROGRESS
Cluster status CREATE_IN_PROGRESS
Cluster status CREATE_IN_PROGRESS
Cluster status CREATE_IN_PROGRESS
Cluster status CREATE_IN_PROGRESS
Cluster status CREATE_IN_PROGRESS
Cluster status CREATE_IN_PROGRESS
Cluster status CREATE_COMPLETE
/usr/local/lib/python2.7/dist-packages/novaclient/client.py:278: UserWarning: The 'tenant_id' argument is deprecated in Ocata and its use may result in errors in future releases. As 'project_id' is provided, the 'tenant_id' argument will be ignored.
  warnings.warn(msg)
Cluster "openstack-kube-stack" set.
User "openstack-kube-stack" set.
Context "openstack-kube-stack" set.
Switched to context "openstack-kube-stack".
Wrote config for openstack-kube-stack to /home/ubuntu/.kube/config
Done, listing cluster services:

The connection to the server xxx.xxx.7.114 was refused - did you specify the right host or port?
```

**Anything else we need to know**:
```
The cloud config inside the cluster is correct:
[minion@kube-stack-master ~]$ cat /srv/kubernetes/openstack.conf
[Global]
auth-url=https://openstack:13000/v2.0
username=name
password=password
region=regionOne
tenant-name=DemoProjekt
domain-name=
[LoadBalancer]
lb-version=
subnet-id=a5222d9b-8f31-4b75-8c59-007ea336a6a3
floating-network-id=613a4a6f-f7a0-4a55-7aa7-bffd5d01a915
[Route]
router-id=c950e702-eb37-49c4-a11d-bad0633a4626
```

**Comment by xsgordon** [comment]
/cc @k8s-sig-openstack-bugs 

@idvoretskyi can you add the sig/openstack label please - this relates to the openstack-heat kube-up provider.

**Comment by jistr** [comment]
I have the same issue with Vagrant, using vagrant-libvirt provider. I ran `./cluster/kube-up.sh` from `release-1.6` branch. These are the exports i'm using:

    export PATH=${PATH}:/home/kube/kubernetes/third_party/etcd:/home/kube/kubernetes/_output/release-stage/client/linux-amd64/kubernetes/client/bin
    export KUBERNETES_PROVIDER=vagrant
    export VAGRANT_DEFAULT_PROVIDER=libvirt
    export KUBERNETES_VAGRANT_USE_NFS=true
    export NUM_NODES=4
    export KUBERNETES_MASTER_MEMORY=3072
    export KUBERNETES_NODE_MEMORY=5120
    export EXTRA_DOCKER_OPTS='--insecure-registry 192.168.0.0/16'

And here's a snippet from the salt output on the master node with Vagrant:

    ==> master: ----------
    ==> master:           ID: /var/lib/kubelet/ca.crt
    ==> master:     Function: file.managed
    ==> master:       Result: False
    ==> master:      Comment: Source file salt://kubelet/ca.crt not found
    ==> master:      Started: 12:03:04.383536
    ==> master:     Duration: 1.25 ms
    ==> master:      Changes:   
    ==> master: ----------
    ==> master:           ID: kubelet
    ==> master:     Function: service.running
    ==> master:       Result: False
    ==> master:      Comment: One or more requisite failed: kubelet./var/lib/kubelet/ca.crt
    ==> master:      Started: 
    ==> master:     Duration: 
    ==> master:      Changes:   
    ==> master: ----------
    ==> master:           ID: /etc/kubernetes/manifests/kube-apiserver.manifest
    ==> master:     Function: file.managed
    ==> master:       Result: False
    ==> master:      Comment: One or more requisite failed: kubelet.kubelet
    ==> master:      Started: 
    ==> master:     Duration: 
    ==> master:      Changes:   
    ==> master: ----------

**Comment by jistr** [comment]
Before `./cluster/kube-up.sh` i ran `make quick-release` from the same branch (release 1.6).

**Comment by seanmccully** [comment]
Ditto on the Openstack Heat,


```
----------
          ID: /var/lib/kubelet/ca.crt
    Function: file.managed
      Result: False
     Comment: Source file salt://kubelet/ca.crt not found
     Started: 05:13:06.308351
    Duration: 1.203 ms
     Changes:   
----------
          ID: kubelet
    Function: service.running
      Result: False
     Comment: One or more requisite failed: kubelet./var/lib/kubelet/ca.crt
     Changes:   
----------
          ID: /etc/kubernetes/manifests/kube-apiserver.manifest
    Function: file.managed
      Result: False
     Comment: One or more requisite failed: kubelet.kubelet
     Changes:   
----------
          ID: stop_kube-apiserver
    Function: service.dead
        Name: kube-apiserver
      Result: True
     Comment: The named service kube-apiserver is not available
     Started: 05:13:06.313764
    Duration: 15.715 ms
     Changes:   
----------
          ID: /etc/kubernetes/manifests/kube-controller-manager.manifest
    Function: file.managed
      Result: False
     Comment: One or more requisite failed: kubelet.kubelet
     Changes:   
----------
          ID: /var/log/kube-controller-manager.log
    Function: file.managed
      Result: True
     Comment: File /var/log/kube-controller-manager.log exists with proper permissions. No changes made.
     Started: 05:13:06.330779
    Duration: 1.786 ms
     Changes:   
----------
          ID: stop-legacy-kube_controller_manager
    Function: service.dead
        Name: kube-controller-manager
      Result: True
     Comment: The named service kube-controller-manager is not available
     Started: 05:13:06.332723
    Duration: 11.258 ms
     Changes:   
----------
          ID: /etc/kubernetes/manifests/kube-scheduler.manifest
    Function: file.managed
      Result: False
     Comment: One or more requisite failed: kubelet.kubelet
     Changes:   

```

**Comment by leseb** [comment]
+1 on vagrant + libvirt, the step "Validating master" hangs forever.

**Comment by michalmedvecky** [comment]
+1 :(

**Comment by lachgil** [comment]
+1 for vargrant + libvirt

**Comment by ferdinand-swoboda** [comment]
+1 on Openstack Heat

**Comment by codevulture** [comment]
Kubernetes had problems with Master version with vagrant in starting services but i checked to deploy with lower version v1.5.7 and works fine with that.

1) First i copied cert from /srv/kubernetes/ca.crt to /var/lib/kubelet/ca.crt
>May 23 10:18:17 kubernetes-master systemd[1]: Starting Kubernetes Kubelet Server...
May 23 10:18:17 kubernetes-master kubelet[3824]: I0523 10:18:17.668130    3824 feature_gate.go:144] feature gates: map[]
May 23 10:18:17 kubernetes-master kubelet[3824]: W0523 10:18:17.668554    3824 server.go:469] No API client: no api servers specified
May 23 10:18:17 kubernetes-master kubelet[3824]: error: failed to run Kubelet: unable to load client CA file /var/lib/kubelet/ca.crt: open /var/lib/ku
May 23 10:18:17 kubernetes-master systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE

this corrected the above error.

2) Once Kubelet got the problem corrected it ran into another problem which i think was related to (https://github.com/kubernetes/kubernetes/issues/43815):
> May 23 11:21:02 kubernetes-master systemd[1]: Started Kubernetes Kubelet Server.
May 23 11:21:02 kubernetes-master systemd[1]: Starting Kubernetes Kubelet Server...
May 23 11:21:03 kubernetes-master kubelet[12549]: I0523 11:21:03.282260   12549 feature_gate.go:144] feature gates: map[]
May 23 11:21:03 kubernetes-master kubelet[12549]: W0523 11:21:03.283023   12549 server.go:469] No API client: no api servers specified
May 23 11:21:03 kubernetes-master kubelet[12549]: I0523 11:21:03.283942   12549 docker.go:364] Connecting to docker on unix:///var/run/docker.sock
May 23 11:21:03 kubernetes-master kubelet[12549]: I0523 11:21:03.283989   12549 docker.go:384] Start docker client with request timeout=2m0s
May 23 11:21:03 kubernetes-master kubelet[12549]: W0523 11:21:03.331683   12549 cni.go:157] Unable to update cni config: No networks found in /etc/cni/net.d
May 23 11:21:03 kubernetes-master kubelet[12549]: error: failed to run Kubelet: no client provided, cannot use webhook authorization
May 23 11:21:03 kubernetes-master systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
May 23 11:21:03 kubernetes-master systemd[1]: kubelet.service: Unit entered failed state.
May 23 11:21:03 kubernetes-master systemd[1]: kubelet.service: Failed with result 'exit-code'.

Command from which i  checked: `sudo journalctl -u kubelet.service`
I think there is more to be explored.

**Comment by snowball77** [comment]
I have both issues too on OpenStack, ca.crt on wrong place and then no client provided....

**Comment by snowball77** [comment]
I digged into the issue a bit more (and found a lot more issues with the openstack provider). This one is related due to a mismatch in assumptions. The general saltstack assumes that we have a salt server running on the master which then serves the ca.crt file to the salt minions. However, this does not apply to the openstack provider which does not use a salt server at all. Therefore, we need to find another way to distribute the ca.crt file to the kubernetes nodes. Any ideas how to do this? I used manual scp copies at the moment, but this is not an option for automation...

**Comment by delfer** [comment]
ca.crt bug can be fixed with
``
echo '      ca_cert_bundle_path: "/srv/kubernetes/ca.crt"' >> cluster/openstack-heat/kubernetes-heat/fragments/configure-salt.yaml
``
But after appears:

> server.go:496] No API client: no api servers specified
> ...
> error: failed to run Kubelet: no client provided, cannot use webhook authorization

Conclusion:
- magnum not working...
- kube_up not working...

**Comment by snowball77** [comment]
I got this one also after fixing the ca.crt issue (any more issues more afterwards). You can fix this one by removing the webauth part from the kubelet if it is on the master node. You need to patch this in default in the kubelet folder in saltbase. Alternatively, you may want to include the master node in the cluster, in this case you have to add an --api-server to the master kubelet.

After resolving this I had quite some struggle with the pod network. This requires in latest kubenetes releases the use of the kubelet network and CNI provider. If you like, I could try to share my patches to get it all working.

**Comment by urzds** [comment]
> If you like, I could try to share my patches to get it all working.

Would be great to see those. Maybe they could be merged upstream?

**Comment by rjbwtr** [comment]
We're also attempting to do the same following the same documentation and have encountered this issue. Using 1.5.7 isn't an option for us because we only support v3 of the keystone API.

It's a bit of a shame to have fallen at the first hurdle!

**Comment by snowball77** [comment]
Sorry for the delay, I was quite busy the last days. I have created a fork of the kubernetes code at https://github.com/ISTE-RSS/kubernetes and pushed my adjustments to it. This config works for me and I hope you can at least learn from it by looking at my changes. But it will not work out of the box for you (see next paragraph).

I made several adjustments. In particular, I am not using tokens but instead I push all certificates to the nodes using the Swift store. However, this is a manual process so far. It expects a "pki.tgz" file in the Swift store that contains ca, api server and other certificates. This file gets downloaded and extracted on all nodes. I manually created and packed them so far. However, you still have to turn of kubelet <-> API server verification as the kubelets on the node do not have node specific certificates. To secure our cluster, I push node specific certificates in a post processing step external to the provider and activate the verification then.

Overall, I think the provider for openstack heap is quite broken and has been declared deprecated now (as I saw when merging my files). 

I was thinking of using the openstack heat template from the current openstack provider (which is a nice way of bringing the VMs on openstack up IMHO) and combine it with the latest kubeadm to come up with a new provider. I do not see other activities at the moment to better support openstack. Most focus is on AWS or GCE - however this is not an option for us.

**Comment by dims** [comment]
sig-openstack has decided to deprecate the Heat based support

https://github.com/kubernetes/website/pull/5670

thanks,
Dims

/close
