### ISSUE TITLE
Cluster downgrade should maintain a functioning cluster

### ISSUE THREAD

**Issue by ethernetdan** [kubernetes/kubernetes#43393]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version**:
v1.6 -> v1.5

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS**: CVM + GCI

**What happened**:
Error message during downgrade:
```
Mar 20 08:55:27.247: Failed to allocated static ip e2e-tests-ingress-upgrade-4sfn3-static-ip: googleapi: Error 403: Quota 'STATIC_ADDRESSES' exceeded. Limit: 7.0, quotaExceeded
```
Seems like infrastructure or test issue.

**How to reproduce it** (as minimally and precisely as possible):
[CVM Downgrade](https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gce-1.6-1.5-downgrade-cluster)
[GCI Downgrade](https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gke-gci-1.6-gci-1.5-downgrade-cluster)

**Comment by grodrigues3** [comment]
@ethernetdan are you working on this?  let me know if you need help assigning

**Comment by ethernetdan** [comment]
@grodrigues3 I'm not - that would be great

**Comment by grodrigues3** [comment]
/assign @fejta 

Is this a test infra issue?

**Comment by fejta** [comment]
/unassign
/assign @ixdy 

This is not a test infra issue -- this is an error from GCE saying too many IPs are consumed.

This is either because one or more tests leak IP address and/or the project's static ip quota is insufficient to handle test throughput.

**Comment by ixdy** [comment]
The tests were failing a lot, leaking IP addresses faster than the janitor could clean up.

I've cleaned up the projects manually for now, and they should stop failing so quickly.
