### ISSUE TITLE
Replace reflect.DeepEqual with Semantic.DeepEqual in controller registries

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#43402]
Forked from #43337

Consider switching to `Semantic.DeepEqual` since we can't distinguish between `null` and `[]` in protobuf.

cc @kubernetes/sig-apps-misc @kargakis

**Comment by jayunit100** [comment]
Agree with this, and the fuzzer stuff is so confusing.  As I recall another part of making this stuff less cumbersome is adding the right logging to unit tests when equivalence options fail, which isn't really possible with deepequal.go

**Comment by shiywang** [comment]
@janetkuo I would like to take a look on this, could you assign this to me ?

**Comment by janetkuo** [comment]
Eventually we want to use semantic merge (server side apply) to compare, instead of DeepEqual.
