### ISSUE TITLE
Role/ClusterRole creation doesn't cross authorizers nicely

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#43409]
In order to create an RBAC role, I need to have all of the permissions that exist in the role, *through RBAC*. It doesn't matter If I have all the permissions through another authorizer.

On GKE, for example, if I want to use my Google identity to create a role, I first have to create an RBAC RoleBinding giving myself the `cluster-admin` role, even if I am the owner of the project that has the GKE cluster.

We should authorize role creation in a way that allows "super users" from other authorizers to use RBAC.

**Comment by liggitt** [comment]
Cc @kubernetes/sig-auth-feature-requests

**Comment by ericchiang** [comment]
Another check like this? https://github.com/kubernetes/kubernetes/pull/39383

**Comment by cjcullen** [comment]
I was thinking something similar to that.

Strawman:
To see if a user should be able to create/update a clusterRole:
Check "clusterRoleBindings" "bind" on the root of the cluster.
To see if a user should be able to create/update a role:
Check "roleBindings" "bind" on the whole namespace.

If you can bind to any existing role/clusterRole, then you can create/update roles/clusterRoles.

I think this is reasonable if you assume there is always a superuser role in every context. It might fall over if you consider a namespace that only has some low privilege roles that you are now able to escalate.

**Comment by G-Harmon** [comment]
@dnardo I guess you ran into this today.

**Comment by Blasterdick** [comment]
Might be useful for GKE users [cluster role binding & principalEmail](https://github.com/coreos/prometheus-operator/issues/357#issuecomment-363498455).

**Comment by ensonic** [comment]
Any chance this can be backported in to older releases? Alternatively is there a workaround to give all IAM project owners the cluster-admin role (on GKE)?
