### ISSUE TITLE
Kubernetes installation conflicts with docker-ce-17.03.0

### ISSUE THREAD

**Issue by JackyChen255** [kubernetes/kubernetes#43400]
I can't install kubernetes in CentOS following this installation guide (link).

1: Flannel and docker service can't start after default installation By default above installation will install Docker 1.12, but flannel and docker service can't start. ● flanneld.service - Flanneld overlay address etcd agent Loaded: loaded (/usr/lib/systemd/system/flanneld.service; enabled; vendor preset: disabled) Active: activating (start) since Mon 2017-03-20 11:24:45 EDT; 27s ago Main PID: 31572 (flanneld) CGroup: /system.slice/flanneld.service └─31572 /usr/bin/flanneld -etcd-endpoints=http://127.0.0.1:2379 -etcd-prefix=/atomic.io/network

Mar 20 11:25:00 JackKubeNode1 flanneld-start[31572]: E0320 11:25:00.259468 31572 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured Mar 20 11:25:01 JackKubeNode1 flanneld-start[31572]: E0320 11:25:01.265559 31572 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured Mar 20 11:25:02 JackKubeNode1 flanneld-start[31572]: E0320 11:25:02.592586 31572 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured Mar 20 11:25:03 JackKubeNode1 flanneld-start[31572]: E0320 11:25:03.677965 31572 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured Mar 20 11:25:04 JackKubeNode1 flanneld-start[31572]: E0320 11:25:04.719815 31572 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured Mar 20 11:25:05 JackKubeNode1 flanneld-start[31572]: E0320 11:25:05.820301 31572 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured Mar 20 11:25:09 JackKubeNode1 flanneld-start[31572]: E0320 11:25:09.016167 31572 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured Mar 20 11:25:10 JackKubeNode1 flanneld-start[31572]: E0320 11:25:10.021494 31572 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured Mar 20 11:25:11 JackKubeNode1 flanneld-start[31572]: E0320 11:25:11.022784 31572 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured Mar 20 11:25:12 JackKubeNode1 flanneld-start[31572]: E0320 11:25:12.238389 31572 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured Mar 20 11:25:13 JackKubeNode1 flanneld-start[31572]: E0320 11:25:13.513397 31572 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured A dependency job for docker.service failed. See 'journalctl -xe' for details. Created symlink from /etc/systemd/system/multi-user.target.wants/docker.service to /usr/lib/systemd/system/docker.service. ● docker.service - Docker Application Container Engine Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled) Drop-In: /usr/lib/systemd/system/docker.service.d └─flannel.conf Active: inactive (dead) since Mon 2017-03-20 11:25:16 EDT; 1min 29s ago Docs: http://docs.docker.com Main PID: 30412 (code=exited, status=0/SUCCESS)

Mar 20 11:18:32 JackKubeNode1 dockerd-current[30412]: time="2017-03-20T11:18:32.059329808-04:00" level=info msg="Daemon has completed initialization" Mar 20 11:18:32 JackKubeNode1 dockerd-current[30412]: time="2017-03-20T11:18:32.059499814-04:00" level=info msg="Docker daemon" commit="96d83a5/1.12.6" graphdriver=devicemapper version=1.12.6 Mar 20 11:18:33 JackKubeNode1 dockerd-current[30412]: time="2017-03-20T11:18:33.169919003-04:00" level=info msg="API listen on /var/run/docker.sock" Mar 20 11:18:33 JackKubeNode1 systemd1: Started Docker Application Container Engine. Mar 20 11:25:15 JackKubeNode1 systemd1: Stopping Docker Application Container Engine... Mar 20 11:25:15 JackKubeNode1 dockerd-current[30412]: time="2017-03-20T11:25:15.912002109-04:00" level=info msg="Processing signal 'terminated'" Mar 20 11:25:16 JackKubeNode1 dockerd-current[30412]: time="2017-03-20T11:25:15.982882827-04:00" level=info msg="stopping containerd after receiving terminated" Mar 20 11:25:16 JackKubeNode1 dockerd-current[30412]: time="2017-03-20T11:25:16.352579523-04:00" level=error msg="libcontainerd: failed to receive event from containerd: rpc error: code = 13 desc = transport is closing" Mar 20 11:26:42 JackKubeNode1 systemd1: Dependency failed for Docker Application Container Engine. Mar 20 11:26:42 JackKubeNode1 systemd1: Job docker.service/start failed with result 'dependency'.

2: It is said in link above issue is fixed in docker 1.13. So I manually install docker first then install kubernetes. But docker-ce-17.03 was installed, then there was conflicts between kubernetes and docker-ce-17.03 during kubernetes dependency resolves. How to work it around? Processing Conflict: docker-ce-17.03.0.ce-1.el7.centos.x86_64 conflicts docker\n-Processing Conflict: docker-ce-17.03.0.ce-1.el7.centos.x86_64 conflicts docker\n-Processing Conflict: docker-ce-17.03.0.ce-1.el7.centos.x86_64 conflicts docker-io Processing Conflict: docker-ce-17.03.0.ce-1.el7.centos.x86_64 conflicts docker-io Processing Conflict: docker-ce-selinux-17.03.0.ce-1.el7.centos.noarch conflicts docker-selinux Processing Conflict: docker-ce-selinux-17.03.0.ce-1.el7.centos.noarch conflicts docker-selinux

3: Recently Docker renamed docker-VERSION as docker-ce-VERSION, and looks like kubernetes doesn't accept new name docker-ce-VERSION. Here is a fix([link]([https://github.com/kubernetes/kubernetes/pull/42425])) to start kubernetes services with docker-ce. But any work around way to fix installation issue?

**Comment by JackyChen255** [comment]
#42425 a fix(link) to start kubernetes services with docker-ce. But any work around way to fix kubernetes  installation issue?

**Comment by JackyChen255** [comment]
The first issue is probably my local network issue. Kubernetes can be installed with Docker 1.12 now. But Kubernetes still can't installed with docker-ce-17.03. Reopen it

**Comment by dmmcquay** [comment]
@JackyChen255 the current max validated version of docker by sig-node is docker 1.12. As they verify more, the max validated version will change.

**Comment by gtirloni** [comment]
For reference, the [CHANGELOG](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#external-dependency-version-information) has more information on this topic.

**Comment by cmluciano** [comment]
related https://github.com/kubernetes/kubernetes/issues/40182

**Comment by jboero** [comment]
Certified or not, if you want to play with this at your own risk the workaround is below.  Make sure to satisfy any missing dependencies manually first:

sudo dnf download kubernetes-node kubernetes
sudo rpm -ivh --nodeps kube*

Works for me.

**Comment by gtirloni** [comment]
I have recently used Docker 17.03 without issues with CentOS 7.4.

/close
