### ISSUE TITLE
Add node e2e test for static pod change.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#43423]
Now we already have some mirror pod node e2e test.
https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/mirror_pod_test.go

However, one expected behavior is that after any part of pod spec is changed, kubelet should restart the whole pod. We don't have a node e2e test for this.

We should create a pod, change the pod spec, and check kubelet endpoint to check whether the static pod is recreated with different uid.

/cc @yujuhong @kubernetes/sig-node-bugs

**Comment by yujuhong** [comment]
> We should create a pod, change the pod spec, and check kubelet endpoint to check whether the static pod is recreated with different uid.

Alternatively, we can check the hash annotation, container IDs, etc., from the status of the mirror pod.

**Comment by fromanirh** [comment]
let me see if I can help here: will review the existing tests and, if still relevant (the original issue is from 2017!) I'll file a PR implementing the suggested test.

**Comment by fromanirh** [comment]
It seems to me this test https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/mirror_pod_test.go#L69 covers the issue tracked here. Can we close this issue then?

**Comment by ehashman** [comment]
/close

We have coverage for this.
