### ISSUE TITLE
AdmissionControllers: DefaultTolerationSeconds added after ResourceQuota

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#43426]
cluster/gce/config-default.sh has this:

```
# If we included ResourceQuota, we should keep it at the end of the list to prevent incrementing quota usage prematurely.
ADMISSION_CONTROL=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds
```

AFAICT, DefaultTolerationSeconds cannot actually throw, but we should:

* Move the order of AdmissionController initialization to prevent someone adding an unsafe admission controller later
* Change `AddOrUpdateTolerationInPod` to not return error, if it will in fact never return an error

**Comment by liggitt** [comment]
yes, resource quota should always be at the end

**Comment by liggitt** [comment]
added in https://github.com/kubernetes/kubernetes/pull/41815
opened #43427 to restore resource quota to the end of the chain

**Comment by liggitt** [comment]
cc @derekwaynecarr @davidopp

**Comment by k82cn** [comment]
> Change AddOrUpdateTolerationInPod to not return error, if it will in fact never return an error

Addressed at #42964

**Comment by aveshagarwal** [comment]
So both issues in the report are addressed in the following PRs: 
https://github.com/kubernetes/kubernetes/pull/43427 by @liggitt  and milestone set to 1.6.
 https://github.com/kubernetes/kubernetes/pull/42964  by @k82cn and milestone set to 1.7 so do we want to get it in 1.6?

**Comment by k82cn** [comment]
> #42964 by @k82cn and milestone set to 1.7 so do we want to get it in 1.6?

It's not release blocker; but I prefer to get it in 1.6 :).
