### ISSUE TITLE
install RBAC api in federation-apiserver

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/kubernetes#43433]
RBAC has been in beta since v1.6, and I think we should enable this apigroup in federation-apiserver, too.

Per this document: https://docs.google.com/document/d/1O2SEr_TDtgXzndh5lHPuAZmT-haylB9NaBRSo4DsUdk/edit#, RBAC was not enabled due to that it was still alpha at that time.

cc @nikhiljindal

**Comment by nikhiljindal** [comment]
Yes we do want to support RBAC with federation.

cc @kubernetes/sig-federation-feature-requests

**Comment by quinton-hoole** [comment]
As per my comments in [the doc](https://docs.google.com/document/d/1h3ULIc65gzv-9i-Pi6akBC_rt9QlNtHDqKCIc06gVV8/edit#heading=h.kcboafgydmlo), I think that there are two separate questions here:

1. Do we want to support RBAC on Federated API objects (e.g. "is Alice allowed to create Federated ReplicaSets in namespace X?". I think that the answer is yes, but not in v1.7.
2. Do we want to Federate RBAC? (e.g. "reliably propagate this RBAC rule/user/whatever to all or a subset of federated clusters"). Again, I think that the answer is yes, but not in v1.7.

**Comment by nikhiljindal** [comment]
Yes for both.
If someone is willing to work on it then I dont mind getting it in 1.7 as well (as alpha, disabled by default)

**Comment by ericchiang** [comment]
A note from the auth side. The credentials that federation uses to talk to the underlying cluster with will need the powers that encompass the roles and bindings it creates. E.g. you want to create a rolebinding that grants a user "admin", the federation control plane will need at least "admin" in that context. Setups will either need to give federation a lot of power on the underlying cluster, or have federation only be able to manage a small subset of roles.

I could see this feature being extremely useful for managing pod API access. I'd probably not recommend using it to manage user access.

cc @kubernetes/sig-auth-feature-requests

**Comment by deads2k** [comment]
> E.g. you want to create a rolebinding that grants a user "admin", the federation control plane will need at least "admin" in that context.

We also check the `bind` verb on the role or clusterrole being bound to allow more narrow permissions.  Obviously it would allow an escalation path, but it helps limit some classes of bugs.

**Comment by smarterclayton** [comment]
The current thought is that federation should be able to grant roles on the underlying cluster, but that's still being discussed.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#120.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
