### ISSUE TITLE
Panic and crash after using TPRs

### ISSUE THREAD

**Issue by ash2k** [kubernetes/kubernetes#43430]
**Kubernetes version** (use `kubectl version`):
minikube version: v0.17.1

Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
Macbook Laptop
- **OS** (e.g. from /etc/os-release):
macOS
- **Kernel** (e.g. `uname -a`):
Darwin CLI-1831 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
- **Install tools**:
minikube 0.17.1
- **Others**:

**What happened**:
```
Mar 10 04:38:29 minikube localkube[6130]: I0310 04:38:29.225590    6130 event.go:217] Event(api.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"kube-controller-manager", UID:"058a3ee0-045d-11e7-b4a1-da027787b657", APIVersion:"v1", ResourceVersion:"40892", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' minikube became leader
Mar 10 04:38:29 minikube localkube[6130]: I0310 04:38:29.227438    6130 replication_controller.go:219] Starting RC Manager
Mar 10 04:38:29 minikube localkube[6130]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 10 04:38:29 minikube localkube[6130]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xdecd8d]
Mar 10 04:38:29 minikube localkube[6130]: goroutine 1551 [running]:
Mar 10 04:38:29 minikube localkube[6130]: panic(0x3592cc0, 0xc420018030)
Mar 10 04:38:29 minikube localkube[6130]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
Mar 10 04:38:29 minikube localkube[6130]: k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/apimachinery/registered.(*APIRegistrationManager).RESTMapper(0xc420158910, 0x0, 0x0, 0x0, 0xc42106330c, 0x2)
Mar 10 04:38:29 minikube localkube[6130]:         /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/apimachinery/registered/registered.go:313 +0x24d
Mar 10 04:38:29 minikube localkube[6130]: k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/apimachinery/registered.(*APIRegistrationManager).RESTMapper-fm(0x0, 0x0, 0x0, 0x0, 0x0)
Mar 10 04:38:29 minikube localkube[6130]:         /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/apimachinery/registered/registered.go:106 +0x48
Mar 10 04:38:29 minikube localkube[6130]: k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.StartControllers(0xc420422a00, 0xc420ee4000, 0x675a7c0, 0xc420ee4000, 0x675a7c0, 0xc420ee4000, 0xc421cd5f20, 0x6756300, 0xc420d52540, 0x3b81477, ...)
Mar 10 04:38:29 minikube localkube[6130]:         /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:367 +0x1996
Mar 10 04:38:29 minikube localkube[6130]: k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func2(0xc421cd5f20)
Mar 10 04:38:29 minikube localkube[6130]:         /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:180 +0xc4
Mar 10 04:38:29 minikube localkube[6130]: created by k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/leaderelection.(*LeaderElector).Run
Mar 10 04:38:29 minikube localkube[6130]:         /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go:150 +0x97
Mar 10 04:38:29 minikube systemd[1]: localkube.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 10 04:38:29 minikube systemd[1]: localkube.service: Unit entered failed state.
Mar 10 04:38:29 minikube systemd[1]: localkube.service: Failed with result 'exit-code'.
Mar 10 04:38:32 minikube systemd[1]: localkube.service: Service hold-off time over, scheduling restart.
Mar 10 04:38:32 minikube systemd[1]: Stopped Localkube.
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
- install minikube and start it
- clone https://github.com/atlassian/smith
- run `make minikube-test` couple of times
- `minikube stop` && `minikube start`

Watch logs for panics.

Should be doable against real cluster too, haven't tested.

**Anything else we need to know**:
This is a copy of https://github.com/kubernetes/minikube/issues/1090 which is not getting any attention - I probably should have reported it here, not there. See it for more details and logs.

**Comment by liggitt** [comment]
adding to the milestone for triage

**Comment by deads2k** [comment]
> adding to the milestone for triage

Even if it's in 1.6, it also existed in 1.5.  I don't think it should block 1.6.

**Comment by deads2k** [comment]
@ash2k does minikube try to launch a single go process which contains both the kube-apiserver and the kube-controller-manager?  That appears to be the most likely way for something like this to happen.  Kube isn't very well structured to do that given the accidental interaction via the global API registry which kube only tests in separate processes.

**Comment by deads2k** [comment]
Yeah, that looks like what is being done here: https://github.com/kubernetes/minikube/blob/69c85e98288361cd84d6d023b4a61b6829efb8c6/cmd/localkube/cmd/start.go#L109-L114 and here https://github.com/kubernetes/minikube/blob/ceb25dfd43a1c9d4ab6e11fdc34fa4333cab4626/pkg/localkube/apiserver.go#L61 .

I don't think this is a kube problem.  It looks like a wiring problem for someone vendoring kube.  Removing milestone.

**Comment by ash2k** [comment]
@deads2k Thanks for looking into it! Sorry, I have no idea how minikube works internally. If Kubernetes is not affected by this issue then it is not that bad. I was afraid to try my code on our real cluster and preventing it from starting up next time. However this is a serious inconvenience for minikube users.

**Comment by xiang90** [comment]
> Even if it's in 1.6, it also existed in 1.5. I don't think it should block 1.6.

I do not follow this logic. Why we do not need to fix this if the bug also exists for 1.5?

**Comment by liggitt** [comment]
A crasher in 1.5.3 by definition is not a release blocker (since it already exists in a released version).

**Comment by donspaulding** [comment]
Can I ask whether this is something likely to be fixed as a bugfix in the k8s 1.5.X and 1.6.X branches?  If not, do I understand the suggestion above by @deads2k to be that minikube needs to run separate processes for those two goroutines and then all should work in both 1.5 and 1.6?

**Comment by enisoc** [comment]
@donspaulding I agree with your interpretation of https://github.com/kubernetes/kubernetes/issues/43430#issuecomment-288184931. The suggestion seems to be that this should not occur in a real k8s cluster. Do you happen to have a small reproduction case that I could try out? The one in the original post above seems to point to a live, moving repo.

**Comment by donspaulding** [comment]
I think the smallest repro case I've seen so far is the one @r2d4 put together in [this comment on minikube issue #1252](https://github.com/kubernetes/minikube/issues/1252#issuecomment-295370860).

**Comment by r2d4** [comment]
I think this comes from https://github.com/kubernetes/kubernetes/issues/44507, also https://github.com/kubernetes/kubernetes/issues/39816

TPRs never get registered with RegisterGroup (should it?), and the garbage collector controller as well as the namespace controller both use static RESTMapping, rather than a dynamic one.  The versions get enabled and registered, but the group does not get registered causing the panic here: 

https://github.com/kubernetes/apimachinery/blob/master/pkg/apimachinery/registered/registered.go#L285

When I registered the group TPR, the panics disappear, however the garbage collector complains since it doesn't know how to garbage collect the TPR.  Right now the garbage collector supresses some TPR https://github.com/kubernetes/kubernetes/pull/42862

Not super familiar with this part of k8s so feel free to correct me or point me in the right direction.

**Comment by enisoc** [comment]
FYI I couldn't reproduce this in a full cluster (without minikube) on GCE with a method similar to https://github.com/kubernetes/minikube/issues/1252#issuecomment-295370860. I brought up the cluster, created the TPR, then "upgraded" the master to the same version, which removes and recreates the master VM while keeping the data volume intact.

The TPR is still there, and I don't see any panics. This seems to support the hypothesis that the crash only occurs because of the unusual way minikube combines multiple processes.

@r2d4 Does it make sense to you that your proposed fix would be unnecessary for the full cluster case? Or is there something else I should try to reproduce?

**Comment by r2d4** [comment]
I wasn't able to reproduce it on a local non-minikube cluster either.  The full cluster case does run into a similar issue, but is specifically ignoring the error here https://github.com/kubernetes/kubernetes/pull/42862.  I don't think that the proposed PR is much different, but I understand if we want to keep it out of upstream.

**Comment by liggitt** [comment]
#42862 has to deal with unknown restmappings because it is looking them up based on user input which could be completely bogus. 

The proposed PR for this issue is masking inconsistently registered internal groups and versions for TPR objects. We should fix the inconsistency by removing the version registration, not mask it (per @deads2k's comment)

**Comment by r2d4** [comment]
Thanks for the clarification.  I'll update the PR to remove the version registration.

**Comment by ash2k** [comment]
This does not happen with Custom Resources in 1.8 so on one hand this could be closed. On the other hand though the discussion suggests (I don't fully understand the details) that there is/are some other bug(s) in the code that lead to the panic. If someone understands the issue better, please comment/close it. Perhaps the title should be updated.

**Comment by nikhita** [comment]
This looks like a minikube issue as @deads2k mentioned in https://github.com/kubernetes/kubernetes/issues/43430#issuecomment-288187335.

Closing since this does not affect CustomResources. Please reopen if you face this issue.

/close
