### ISSUE TITLE
Mirror pod creation error is unnecessarily logged by Kubelet

### ISSUE THREAD

**Issue by Levovar** [kubernetes/kubernetes#43445]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Both? More of a bug IMO

**Kubernetes version** (use `kubectl version`):

> kubectl version
> Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

(though based on the code I think the issue is there in all versions)

**What happened**:
Kubelet constantly produces the following error log:

> : Pod "kube-proxy-crf-sb-1" is invalid: spec.containers[0].securityContext.privileged: Forbidden: disallowed by policy

**What you expected to happen**:
Kubelet does not constantly produce the above error log, when it is not justified (see below for cluster setup)

**How to reproduce it** (as minimally and precisely as possible):
1. Start kubelet with --allow-privileged=true
2. Bring-up the cluster components as static pods (API server and kube-proxy included)
3. Configure API server with --allow-privileged=false
4. Observe the logs periodically written by kubelet as it continuously tries to create a privileged mirror pod (kube-proxy) 

**Anything else we need to know**:
AFAIK kube-proxy needs to be privileged in order to provision iptables rules, therefore kubelet was started as indicated above. However, this does not mean I want to allow the same privileges for all pods within my cluster, therefore I imposed a stricter rule on my API server.
I think this is a valid cluster configuration, so we should:
- be able to selectively turn off this unnecessary logging for mirror pods
- or at least add an exception specifically for kube-proxy

**Comment by gyliu513** [comment]
/assign 

I will check this one
