### ISSUE TITLE
kubeapi-load-balancer endpoint not reconfigured on failure

### ISSUE THREAD

**Issue by jacekn** [kubernetes/kubernetes#43448]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): "load-balancer ha", "kubeapi-load-balancer"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):

````
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
````

**Environment**:
- **Cloud provider or hardware configuration**: OpenStack
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.2 LTS
- **Kernel** (e.g. `uname -a`): 4.4.0-66-generic
- **Install tools**: juju
- **Others**:

**What happened**:

I add 2nd kubeapi-load-balancer unit using "juju add-unit kubeapi-load-balancer" command. When it completed I shut down the original one. I wanted to achieve active/passive HA. I left it for around 10 minutes to give juju hooks time to run. Then I tried:

    kubectl get nodes

but it failed with:

    Unable to connect to the server: dial tcp 10.25.61.27:443: getsockopt: no route to host

**What you expected to happen**:

I expected hooks to reconfigure things to point at alive api load balancer

**How to reproduce it** (as minimally and precisely as possible):

In a juju deployed k8s environment:
````
juju add-unit kubeapi-load-balancer
# wait for it to complete
# manually shut down original kubeapi-load-balancer unit
# wait for 10min to ensure hooks execute
kubectl get nodes
````

**Anything else we need to know**:

**Comment by chuckbutler** [comment]
@jacekn This was filed some time ago, do you recall of the kubectl command was executed from a remote unit or from your workstation? I would expect the old load balancer being taken offline to yield in a broken configuration because the endpoint vanished unless you were using a floating ip for that loadbalancer.

**Comment by jacekn** [comment]
@chuckbutler it was broken from both kubernetes-worker units and from my workstation.

I'm fairly sure the problem is indeed changing IP address.
You can't fix it on client workstations but k8s charms should certainly ensure that config on disk is always correct so that users can re-download it.

**Comment by wwwtyro** [comment]
@tvansteenburgh I was able to repro this.
