### ISSUE TITLE
Cluster level logging using GCL should check that logs from containers are ingested in GCL failed in gke-large-cluster suite

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#43442]
This failed here:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-large-cluster/90

What I'm seeing in logs is:
```
I0320 19:00:34.003] Mar 20 18:49:15.272: INFO: Failed to get response from GCL due to googleapi: Error 429: Insufficient tokens for quota 'ReadGroup' and limit 'CLIENT_PROJECT-100s' of service 'logging.googleapis.com' for consumer 'project_number:661044217466'., rateLimitExceeded, retrying
I0320 19:00:34.004] Mar 20 18:49:25.283: INFO: Failed to get response from GCL due to googleapi: Error 429: Insufficient tokens for quota 'ReadGroup' and limit 'CLIENT_PROJECT-100s' of service 'logging.googleapis.com' for consumer 'project_number:661044217466'., rateLimitExceeded, retrying
...
```

It seems to me that it is some configuration issue, but we should fix it.

**Comment by crassirostris** [comment]
There are couple of tests running in the background in the flaky suite that create logging load and then check the number of log entries that made it.

Stackdirver has a hard limit on the number of entries per read request: 1000. According to [the policy](https://cloud.google.com/logging/quota-policy), It also has a hard limit of 10 requests per second, however it seems like not a most accurate information, since in logs it's actually 100s limit. Also I did a quick check and got `Insufficient tokens for quota 'ReadGroup'` response after much less than 1k requests

Continue looking into it

/cc @piosz @igorpeshansky

**Comment by crassirostris** [comment]
I took a look at the quotas in the API Manager and it seems that Stackdriver Quota Policy is actually wrong, real limit is 100 requests per 100 seconds and you cannot bump it.

**Comment by marun** [comment]
@crassirostris @wojtek-t I'm assuming this shouldn't be blocking 1.6.  Feel free to revert my milestone change if you disagree.

**Comment by piosz** [comment]
@marun agree

**Comment by wojtek-t** [comment]
Yup - it's not strictly related to OSS.

@crassirostris - btw, it failed again today:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-large-cluster/91

**Comment by wojtek-t** [comment]
And one more:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-large-cluster/92

**Comment by crassirostris** [comment]
@wojtek-t I hope it will be resolved today

**Comment by crassirostris** [comment]
Also: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce/5860

**Comment by crassirostris** [comment]
Turns out there's another problem: cluster doesn't have fluentd running and logging test fails with the following message:

```
node gke-gke-large-cluster-default-pool-0-1ad56571-0118 doesn't have fluentd instance
```

**Comment by crassirostris** [comment]
WAI, GKE problem, should be fixed by the end of Monday

**Comment by crassirostris** [comment]
Issue fixed
