### ISSUE TITLE
Cluster IP update is not carried to federation-controller

### ISSUE THREAD

**Issue by henriquetruta** [kubernetes/kubernetes#43455]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report 

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: GCE (federation control plane) + Cluser on-prem

**What happened**:
I had a federation running, with the control plane at GCE and a local on-prem cluster, running in a VM. Then, I had to change the port my local api-server was running. I've updated the cluster file and ran `kubetl --context=federation apply -f cluster.yaml`. The object was properly updated but the `federation-controller-manager` started to fail, because it was still trying to reach in the old port.

**What you expected to happen**:
`federation-controller-manager` to be refreshed at some point, updating the cluster port. I had to delete and recreate the local cluster

**How to reproduce it** (as minimally and precisely as possible):
Create a federation on GCE, join another cluster and change some cluster information. In my case I needed to change the port, so I updated the cluster object.

**Anything else we need to know**:
How I made my federation setup: https://github.com/henriquetruta/hybrid-k8s-federation/

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#121.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
