### ISSUE TITLE
PodSecurityPolicy admission plugin authorizes incorrectly

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#43459]
A PodSecurityPolicy admission plugin vulnerability allows users to make use of any PodSecurityPolicy object, even ones they are not authorized to use.

CVE: Pending

* Fixed in [v1.5.5](https://github.com/kubernetes/kubernetes/releases/tag/v1.5.5) in https://github.com/kubernetes/kubernetes/commit/7fef0a4f6a44ea36f166c39fdade5324eff2dd5e
* Fixed in release-1.5 branch in https://github.com/kubernetes/kubernetes/pull/43491
* Fixed in master in https://github.com/kubernetes/kubernetes/pull/43489

**Who is affected?**
Only Kubernetes 1.5.0-1.5.4 installations that do _all_ of the following:
* Enable the PodSecurityPolicy API (which is not enabled by default):
      `--runtime-config=extensions/v1beta1/podsecuritypolicy=true`
* Enable the PodSecurityPolicy admission plugin (which is not enabled by default):
      `--admission-control=...,PodSecurityPolicy,...`
* Use authorization to limit users' ability to use specific PodSecurityPolicy objects

**What is the impact?**
A user that is authorized to create pods can make use of any existing PodSecurityPolicy, even ones they are not authorized to use.

**How can I mitigate this prior to installing 1.5.5?**
1. Export existing PodSecurityPolicy objects:
      `kubectl get podsecuritypolicies -o yaml > psp.yaml`

2. Review and delete any PodSecurityPolicy objects you do not want all pod-creating users to be able to use (NOTE: Privileged users that were making use of those policies will also lose access to those policies). For example:
      `kubectl delete podsecuritypolicies/my-privileged-policy`

3. After upgrading to 1.5.5, re-create the exported PodSecurityPolicy objects:
      `kubectl create -f psp.yaml`

**Comment by cjcullen** [comment]
Kubeadm and GKE do not allow enabling PodSecurityPolicy in 1.5, so are not affected by this.

Kube-up.sh and kops do not enable PodSecurityPolicy by default. A modified kube-up.sh or kops deployment could have enabled it.

**Comment by Estherbdf** [comment]
Could you please give a example show how an attacker can create a pod without serviceaccount?

**Comment by PushkarJ** [comment]
/label official-cve-feed

(Related to https://github.com/kubernetes/sig-security/issues/1)
