### ISSUE TITLE
[GKE] Ingress should conform to Ingress spec

### ISSUE THREAD

**Issue by ethernetdan** [kubernetes/kubernetes#43466]
The [1.6 GKE Ingress Tests
](https://k8s-testgrid.appspot.com/release-1.6-all#gci-gke-ingress-1.6) started failing yesterday. This looks like an infra issue.

[Error: ](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-ingress-release-1.6/700)
```
Mar 21 01:24:23.063: Ingress failed to acquire an IP address within 15m0s
```

@kubernetes/test-infra-maintainers

**Comment by krzyzacy** [comment]
`event for echomap: {loadbalancer-controller } GCE :Quota: googleapi: Error 403: Quota 'BACKEND_SERVICES' exceeded. Limit: 5.0, quotaExceeded`

Is this test using more than 5 backend services?

**Comment by krzyzacy** [comment]
I think https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-ingress-release-1.6/680/ is a bad run maybe screwed up something there. I can wipe the project, but guess I'll leave it there for someone want to take a look.

**Comment by krzyzacy** [comment]
janitor has cleaned it up, the job is green now.

/close
