### ISSUE TITLE
1.6 upgrade testing - [k8s.io] Kubectl client [k8s.io] Kubectl describe should check if kubectl describe prints relevant information for rc and pods [Conformance]

### ISSUE THREAD

**Issue by skriss** [kubernetes/kubernetes#43464]
This test is still failing -- looks like now due to a minor change from "Image(s)" to "Image" (see PR 42283) -- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.5-1.6-upgrade-master/28#k8sio-kubectl-client-k8sio-kubectl-describe-should-check-if-kubectl-describe-prints-relevant-information-for-rc-and-pods-conformance

cc @smarterclayton

**Comment by smarterclayton** [comment]
The test in 1.5 will need to be changed if it's using the 1.6 kubectl.  However... is the test supposed to be using the 1.6 kubectl?

**Comment by monopole** [comment]
This is still a problem in the 1.6 -> 1.7 tests.

**Comment by monopole** [comment]
See also https://github.com/kubernetes/kubernetes/issues/44563

**Comment by pwittrock** [comment]
@smarterclayton reassigned to @mengqiy

**Comment by mengqiy** [comment]
1.6->1.7 upgrade test failing because of changes in https://github.com/kubernetes/kubernetes/pull/42849.
Will send a PR soon to skip this test in 1.6 branch when running with a 1.7 kubectl.

**Comment by monopole** [comment]
@mengqiy Thanks!

Now passing in [gce-upgrade-master](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gce-upgrade-master&sort-by-failures=)

However, still failing in [gke-cvm-upgrade-master](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-upgrade-master&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Kubectl%5C%20client%5C%20%5C%5Bk8s%5C.io%5C%5D%5C%20Kubectl%5C%20describe%5C%20should%5C%20check%5C%20if%5C%20kubectl%5C%20describe%5C%20prints%5C%20relevant%5C%20information%5C%20for%5C%20rc%5C%20and%5C%20pods%5C%20%5C%5BConformance%5C%5D) ---  [gubernator](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-6-cvm-1-7-upgrade-master/33#k8sio-kubectl-client-k8sio-kubectl-describe-should-check-if-kubectl-describe-prints-relevant-information-for-rc-and-pods-conformance)

**Comment by mengqiy** [comment]
@monopole 
It seems both of them start to pass in 06/21.
I think we can close this issue.

**Comment by dchen1107** [comment]
Close it. Thanks!
