### ISSUE TITLE
It would be nice to have a kubectl get pods --all-the-pods-i-can-get

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#43478]
I don't have a clue how this would work. But I've heard this request a couple times now, so maybe somebody else has some magical idea.

Maybe if we limited it to `--all-authorized-namespaces` or something, we could do an initial GET namespaces, followed by a bunch of GET pods that silently drop all the 403s. That would require the caller to have namespaces.get on the cluster, which may also be asking too much.

**Comment by ericchiang** [comment]
> That would require the caller to have namespaces.get on the cluster, which may also be asking too much.

I remember a comment that openshift did a filtering of namespaces, so listing all namespaces returned a filtered list of the namespaces you had access to. Don't remember how that worked out for them though.

**Comment by liggitt** [comment]
See https://github.com/openshift/kube-projects for the ACL filtered virtual resource on top of namespaces

**Comment by liggitt** [comment]
I think this should probably collapse to https://github.com/kubernetes/kubernetes/issues/40403... API patterns for accessing some (but not all) namespaces

**Comment by cjcullen** [comment]
I think that SGTM.
