### ISSUE TITLE
Prevent users from deleting pods serving live traffic

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#43487]
Problem:
Users today can run `kubectl delete rs` that does cascading deletion by default and hence will also end up deleting all the pods, even though they might have been serving live traffic.
The problem is even more severe in the case of federation since the deletion impacts multiple clusters and can cause global outages.

One possible solution:
When user creates an ingress (or service) targeting an rs, we should add a finalizer to the backend pods for that ingress to ensure that they cant be deleted unless the ingress is deleted.
Once user deletes the ingress, they can go ahead and delete the rs.

cc @quinton-hoole @bgrant0607 @kubernetes/sig-federation-feature-requests

**Comment by nikhiljindal** [comment]
We will need to introduce this functionality in a backward compatible way i.e we cant change the existing ingress implementation to do this. Users today expect to delete rs before deleting the ingress and we should not break that.

What we can do is if users add a particular annotation to their ingress, then that prevents deleting the corresponding rs before the ingress (i.e users have to explicitly opt in to this).

Since federation is still new, we can update federation to add that annotation to federated ingressed by default.

**Comment by liggitt** [comment]
isn't this working as designed? graceful deletion allows pods time to finish serving requests

**Comment by kargakis** [comment]
We already have mechanisms for avoiding outages (maxUnavailable in Deployments/DaemonSets, PDB). Why aren't those enough?

**Comment by nikhiljindal** [comment]
Sorry for not being clear, this is to prevent outages by developer running `kubectl delete rs` or `kubectl delete deployment`. maxUnavailable will not help in that case.

Graceful deletion will help so that existing requests will be handled gracefully but not for future requests.

This is helpful in the scenario when developer thought that the rs or deployment is not serving traffic and hence deleted it, but actually it was serving user traffic. Also helpful when `kubectl delete` command is run unintentionally - causing an outage.


A service or ingress for the rs or deployment shows an intent of receiving traffic for those pods, which we can use to detect a potential outage.

**Comment by kargakis** [comment]
Isn't this a more general problem related to any kind of mutation? For example, by scaling up a stateful app I could still cause an outage. Or by pushing bad config, although in this case, correctly configured controllers may incur only partial unavailability.

**Comment by smarterclayton** [comment]
The solution is to not let people delete.  99% of production use cases don't involve deletion.  99% of dev / test / first time user use cases do.  kubectl allowing you to delete things is bad in production.

This is what deletion protection was intended to solve, as well as various UI improvements that require special action to delete anything.  Services, ingress, secrets, etc.

**Comment by nikhiljindal** [comment]
> Isn't this a more general problem related to any kind of mutation? For example, by scaling up a stateful app I could still cause an outage. Or by pushing bad config, although in this case, correctly configured controllers may incur only partial unavailability.

I agree that there are other scenarios that can cause outages and the proposed mechanism does not solve all of them. But I think its still valuable since it solves a particular scenario.
Am open to any other potential solutions. 

> The solution is to not let people delete. 99% of production use cases don't involve deletion. 99% of dev / test / first time user use cases do. kubectl allowing you to delete things is bad in production.

Yes its not as common as other operations, but resources do need to be deleted. Outages in staging are bad as well :)

> 
> This is what deletion protection was intended to solve, as well as various UI improvements that require special action to delete anything. Services, ingress, secrets, etc.

@smarterclayton By deletion protection, do you mean RBAC and restricted access for DELETE operation or is there something else as well?

**Comment by smarterclayton** [comment]
Delete protection was an annotation on the resource that the CLI or
web UI would respect that requires you to confirm deletion.  It would
start client only and apply to all clients.

A second level would be requiring higher permissions to delete in some
namespaces, but that is not likely to solve the real problem.

A third level might be "lock" for human driven operations in a namespace.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#122.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close

**Comment by caleb15** [comment]
@kubernetes/sig-multicluster-misc why was this issue labeled only for multicluster? It seems like it would also apply to just a single cluster.
