### ISSUE TITLE
Remove ETCD env vars from the master upgrade process when they're not needed

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#43486]
In https://github.com/kubernetes/kubernetes/pull/43481, I added some env vars to the master upgrade routine so that we could optionally specify ETCD configuration settings that allow us to downgrade to 1.5. We should remove this by 1.8 if it's no longer needed.

**Comment by dims** [comment]
@krousey, Do we really need to block 1.8 for this issue?

**Comment by krousey** [comment]
No we do not. This is cleanup. Sorry this slipped of my radar for this release. It can be bumped.
