### ISSUE TITLE
Revisit kubectl template language

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#4348]
`kubectl -h config view` says 
```
  -t, --template="": Template string or path to template file to use when -o=template or -o=templatefile.
```
but it doesn't say what the template language is.

**Comment by erictune** [comment]
I think it is go package "text/template" but that is not going to be obvious to everyone.

**Comment by brendandburns** [comment]
Yeah, template is the go template language, which is decidedly hard to use.

We should definitely document this lineage and add some examples (and
consider using something more intuitive as well...)

Brendan

**Comment by roberthbailey** [comment]
+1 for something better than forcing text/template on our users.

**Comment by bgrant0607** [comment]
We shouldn't be exposing the Go representation, even for the versioned API types. Whatever templates we expose, if any, should be in terms of the json field names/paths.

What we really need is a Go implementation of [jq](http://stedolan.github.io/jq/). However, jq at least is [C code](https://github.com/stedolan/jq), so we could just invoke it via [cgo](https://golang.org/cmd/cgo/), though I know some people have reservations about that. In this case, it seems worth it, IMO.

That would also open the door to use of jq functionality elsewhere in kubectl.

**Comment by deads2k** [comment]
I'm not familiar with jq, but since we serialize lists of objects with a name element instead of serialize maps, we need to be sure that it is possible to reference particular elements of the logical map.  One example we have today is referencing pieces of a .kubeconfig file.  Referencing a map-like element of a list by key looks like this in the go template format: 
```
{{if $currContext := (index . "current-context")}}{{range .clusters}}{{ if eq .name $currContext }}{{ .cluster.server }}{{end}}{{end}}{{end}}
```

That pulls out the server property from a cluster object contained in a clusters map with a key==current-context (`clusters."$current-context".server`).  It's difficult to read (and to write), but it's possible.  It would be good to keep the capability and even better if it were easier in the new template format.

**Comment by bgrant0607** [comment]
A jq example is here: https://github.com/GoogleCloudPlatform/kubernetes/issues/4889#issuecomment-77976473.
`.desiredState.manifest.containers[] | select(.name=="nginx")`

**Comment by brendandburns** [comment]
Let's not use cgo I think it will be a portability problem...

However, reimplementing similar syntax using go reflection shouldn't be too
bad, and is likely what we should do.

Brendan

**Comment by thockin** [comment]
Agree - this might be a good gsoc project or something we could "hire out"

**Comment by eparis** [comment]
I'm not going to argue.  I hacked this little junk together because of how darn unreadable the golang templates conditionals are....   https://github.com/eparis/readable-golang-template

**Comment by daizuozhuo** [comment]
hi all!  I am going to participate gsoc this summer. From the previous discussion, it seems that the we need a readable template language, so we want a go version of jq instead of invoke it from cgo. Am I understand correctly? I think I can do it.

**Comment by bgrant0607** [comment]
@daizuozhuo Yes, you have the right idea. The current template language refers to Go objects from the internal implementation, or at least a way to select out specific fields from json. We need a template language for formatting kubectl output that refers to fields in terms of their versioned json field names, that works well for our API idioms (e.g., needs a convenient way to select list items by value of a struct field of a list member), that's implemented in Go, and that ideally would feel familiar to users (i.e., it wouldn't be something totally custom for kubectl).

I haven't yet looked at alternatives other than jq. Jsonpath could be a possibility.

**Comment by daizuozhuo** [comment]
OK, I see. So I will look inside this feature to figure out what I should do, and then submit the proposal.

**Comment by erictune** [comment]
just noticed that `docker inspect -f` uses golang templates too.

**Comment by daizuozhuo** [comment]
@bgrant0607 I have submitted my [proposal](https://docs.google.com/document/d/14QkxGQ-4D9I0Qwqi0k0lHLax4jfUc-kt8akFsj8svyQ/edit?usp=sharing). Since implementing all features of jq may overload for this summer, I select the most useful part of them so that we can use it immediately. Of course, I will add more features if time is permitted. Do you have any suggestions? By the way, how to find a mentor?

**Comment by ghodss** [comment]
@daizuozhuo Cool proposal! While you're iterating on it, you might want to turn on "Commenting only" permissions on your proposal document for anyone with the link so people can comment directly on the proposal itself.

If we're going to reimplement jq, it would be great to mimic their syntax exactly (perhaps even reuse their tests?), but one extension that would be nice to add is to use a syntax style more similar to JSONPath's for selecting a list element based on a map key. So instead of just `.desiredState.manifest.containers[] | select(.name=="nginx")` which is supported by jq today, also supporting something like `.desiredState.manifest.containers[@name==nginx]`. Best case of all would be to get that support backported into jq itself as well. :)

**Comment by daizuozhuo** [comment]
@ghodss Thanks!!! The syntax you mentioned is really nice! Putting filter inside bracket makes it more straightforward. This is a different selection method from pipe so we may add it as a new feature. This makes it more like a language rather than a json processor as jq.

**Comment by daizuozhuo** [comment]
Thanks for accepting my proposal! Who will be my mentor?

**Comment by bgrant0607** [comment]
@daizuozhuo Sorry for not getting back to you sooner. We're in a crunch for our 1.0 milestone. @brendandburns volunteered to mentor. 

Could you copy the language-design part of the proposal into this issue?

Also, I'm inclined to introduce this as a new output format, not necessarily removing the existing template functionality, at least for now.

**Comment by daizuozhuo** [comment]
@brendandburns how do I contact you?
Yes, I just provide one more option for output format. The proposal design part is like this:

1. The expression surrounded by single quote ' will be evaluated.
template: hello 'jq'
input: {jq: "world"}
output: hello world

2. nested key selection
expression: '.a.b'
input: {a: {b: 42}}
output: 42

3. array index and range selection
expression: '.[2:4]'
input: ["a", "b", "c", "d"]
output: ["c", "d"]

4. pipeline
expression: '.[] | .name'
input: [{"name":"JSON", "good":true}, {"name":"XML", "good":false}]
output: “JSON" "XML"

5. array construction
expression '[.user, .projects[]]'
input: {"user":"stedolan", "projects": ["jq", "wikiflow"]}
output: ["stedolan", "jq", “wikiflow"]

6. Dictionary construction
expression: '{.user: .titles}'
input: {"user":"stedolan","titles":["JQ Primer", "More JQ"]}
output: {"stedolan": ["JQ Primer", "More JQ”]}

7. Conditionals and comparisons
expression: 
	'if . == 0 then "zero" elif . == 1 then "one" else "many" end'
input: 2
output: “many”

**Comment by brendandburns** [comment]
@daizuozhuo you can send me mail @ bburns [at] google.com

Sorry for the delay!

**Comment by brendandburns** [comment]
Personally, I'd prefer the JSONPath syntax rather than the jq syntax.  I find JSONPath to be more concise and more readable.  You can see a comparison here:

https://github.com/stedolan/jq/wiki/For-JSONPath-users

**Comment by brendandburns** [comment]
Check out https://github.com/yasuyuky/jsonpath for the start of a golang impl.

**Comment by bgrant0607** [comment]
One of the primary considerations is how easy it is to select a field of a struct in a keyed list (search for patchMergeKey in pkg/api/v1beta3/types.go).
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api-conventions.md#lists-of-named-subobjects-preferred-over-maps

**Comment by smarterclayton** [comment]
I tend to lean towards an existing syntax rather than inventing a new one, especially when it comes to implementing it in other languages for clients that must be aware of it.

**Comment by bgrant0607** [comment]
@smarterclayton Does jsonpath count as an existing syntax?

**Comment by smarterclayton** [comment]
Yes, even though I think it's strictly less elegant as a syntax than jq allows.

**Comment by eparis** [comment]
I won't pretend to have a strong opinion. But if we want something incredibly complex the golang template language should work. I sorta feel like this is for human read-ability and consume-ability, and the one web page @brendandburns listed makes me feel like JSONPath beat jq on that front...

**Comment by smarterclayton** [comment]
I'm fine with JSONPath - the elegance is on some of the deeper semantics.

**Comment by daizuozhuo** [comment]
So we have reach the agreement that we will use jsonpath instead of jq. I will make another pull request.

**Comment by bgrant0607** [comment]
See PR #9296

**Comment by daizuozhuo** [comment]
The jsonpath template has already done. Please see PR #9296 . In addition to the original jsonpath function, I add range and expression union function. It's a superset of jsonpath.

**Comment by bgrant0607** [comment]
I believe this is done.
