### ISSUE TITLE
use glusterfs mount data of postgresql in k8s 

### ISSUE THREAD

**Issue by 13567370952** [kubernetes/kubernetes#43503]
i use glusterfs mount data of mysql in k8s  is sucess.
but i use glusterfs mount data of  postgresql in k8s  is sucess.
i'm sure the dataPath is right. i am try to enter to the container to fin the data is on /var/lib/posqtgresql/9.3/main . how can i do?
the test yaml is 
apiVersion: v1
kind: ReplicationController
metadata:
  name: database-node1
spec:
  replicas: 1
  template: 
    metadata:
      name: database-node1
      labels:
        name: database
        node: node1
    spec:
      containers:
        -
          name: database-node1
          image: postgresql-9.3:v1(while postgresql)
          image: mysql-5.5:v1(while mysql)
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/lib(while postgresql)
              mountPath: /var/lib/mysql(whilemysql)
              name: yshen 
      volumes:
        - glusterfs:
            endpoints: glusterfs-cluster
            path: test01 
          name: yshen
---
apiVersion: v1
kind: Service
metadata:
  name: database-node1-service
  labels:
    name: database
    node: node1
spec:
  type: NodePort  
  ports:
    - port: 5432
  selector:
    name: database
    node: node1

the glusterfs volume is show 
the mysql
root@glusterfs1:~/data/test01# ls
ibdata1  ib_logfile0  ib_logfile1  mopaas_mysql  mysql  performance_schema
the postgresql
root@glusterfs1:~/data/test01# ls
postgresql
root@glusterfs1:~/data/test01# cd postgresql/
root@glusterfs1:~/data/test01/postgresql# ls

**Comment by kargakis** [comment]
Please ask in stackoverflow or the kubernetes-users mailing list.
