### ISSUE TITLE
Limit retries for a (Cron)Job

### ISSUE THREAD

**Issue by CallMeFoxie** [kubernetes/kubernetes#43512]
Hi,
as of right now there's no easy way (or at least I have not found any?) how to specify how many times a (Cron)Job can be retried before it is skipped for this run. We have got:

Job.spec.activeDeadlineSeconds

however from the docs:
 The job will have status with reason: DeadlineExceeded. No more pods will be created, and existing pods will be deleted.
which implies that the running ones will be killed as well.
That seems to be actually true only sometimes - the pods sometimes survive the killing, sometimes get killed (seems random? I have not managed to find anything useful in logs/events for this). And the job is marked with DeadlineExceeded as expected.

It would be nice if we could set, for example, "try 5 attempts then give up until the next run".

Or am I mis-understanding the activeDeadlineSeconds option? Will it not kill the running pod? In that case it should not set DeadlineExceeded flag.

Ashley

**Comment by cmluciano** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by kargakis** [comment]
@kubernetes/sig-apps-misc

**Comment by soltysh** [comment]
I'm hoping if we address #30243 this issue should be solved as well.

**Comment by soltysh** [comment]
This is solved in https://github.com/kubernetes/kubernetes/pull/48075 and https://github.com/kubernetes/kubernetes/pull/51153 which introduces job failure policy. Since cronjob contains jobtemplate, which in turns has a full jobspec you should be able to use it directly in a cronjob.
