### ISSUE TITLE
Clarify "Schedulable resources and eviction policies" in Best Practices documentation

### ISSUE THREAD

**Issue by vdavidoff** [kubernetes/kubernetes#43528]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
"system-reserved"
"Schedulable resources and eviction policies"
"covered by the eviction threshold"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Documentation (I realize that's neither of the choices above)

**Kubernetes version** (use `kubectl version`):
1.5.3

---

The "[Schedulable resources and eviction policies](https://kubernetes.io/docs/concepts/cluster-administration/out-of-resource/#schedulable-resources-and-eviction-policies)" section of the Cluster Administration guide provides an example that is very difficult to make sense of. Apologies if I'm just having a particularly difficult time with it, but I suspect others do to.

The crux is that it's unclear why the value provided to `system-reserved` should cover the eviction threshold. I have come at this a few ways and although I *think* I can come up with a reason why it's smarter to do it this way, I can't come up with a reason why it makes the technical implications any different than not covering the eviction threshold.

That is to say in the example - without trying to get too far into my understanding of this section - kubelet will start evicting pods whenever the total system memory free falls below 500Mi. Whether that's because `system-reserved` was set to 1.5Gi, the system used over 1Gi, and the rest of the system memory was consumed by other processes, or because `system-reserved` was set to 1Gi, the system is using that much, and the rest of the system memory was consumed by other processes, the implications are the same - the node will report a MemoryPressure condition and kubelet will evict pods, producing a gap between the amount of memory the node reports as available for scheduling and the amount it can actually utilized (in this case up to, 500Mi).

If my understanding is correct, I think that means that in addition to this section not being as clear as it could be, the statement "or the system is using more than 500Mi" should actually read "or the system is using more than 1Gi", but I realize that suggestion may just further illustrate that I don't understand what this section is trying to tell me.

I'd be happy to rewrite this section to make it more clear if anyone who can explain to me what it's trying to communicate would rather not rewrite it themselves.

Thanks.

**Comment by vishh** [comment]
cc @steveperry-53 This is closely related to your resources documentation effort. @vdavidoff can you work with @steveperry-53 on improving documentation?

**Comment by vdavidoff** [comment]
I'm glad to help, I just need to find a second to review the current state of things to see if they differ from my original report. Either way, I probably need someone who understands what I found confusing to confirm what is meant to be communicated there.

**Comment by vishh** [comment]
> The crux is that it's unclear why the value provided to system-reserved should cover the eviction threshold. 

Our intention is to not hard limit system daemons by default. Since evicting system daemons will most likely cause a node to become unavailable or unresponsive, we decided to let system daemons burst by default and instead evict pods even if system daemons use more than what they are configured to use.
Example:
`Capacity = 1Gi, system-reserved+kube-reserved=100Mi`. Pods can use a sum total of `900Mi`.
In this case, if system daemons (processes running outside of pods) are consuming more than `100Mi` of memory, then pods will start getting evicted.
If pods consume more than `900Mi` they will get evicted.

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/kubelet-eviction.md

**Comment by vdavidoff** [comment]
Thanks Vish. I think I now better understand my confusion.

When one sets `system-reserved`, the amount of memory actually reserved for the system's _full time_ use is `system-reserved` minus the hard eviction threshold. Another way to think of this is as though the node's total memory is being decreased by the hard eviction threshold, though the memory actually exists to be used as a buffer during memory pressure to hopefully allow kubelet to evict pods and free memory before the system OOMKiller does so, potentially killing system daemons.

e.g. A 10Gi node with `system-reserved` 1Gi and hard eviction of 500Mi will actually result in only 500Mi reserved for the system, because kubelet is going to work to ensure the 500Mi hard eviction threshold is always free. Therefore to actually reserve 1Gi for the system in this case, `system-reserved` must be 1.5Gi.

I think I was initially confused because I was thinking that `system-reserved` meant that total amount would be available for the system, which taken along with a hard eviction threshold, would mean the amount of memory reported as allocatable would be higher than reality by the hard eviction threshold amount. i.e. `system-reserved` doesn't really simply mean `system-reserved` in the case of a hard eviction threshold being set.

If you can confirm that this understanding is correct, I can think about how I might amend the Out of Resource documentation to make it more clear. Or maybe I'll just decide I am dense and this just took a while for me to get my head around.
