### ISSUE TITLE
kubelet fails to start when --cloud-provider=aws in a heavily populated VPC

### ISSUE THREAD

**Issue by andrewmyhre** [kubernetes/kubernetes#43524]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Kubernetes version** (use `kubectl version`): 1.5.3

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): ubuntu 14.04.5 LTS
- **Kernel** (e.g. `uname -a`): Linux 3.13.0-110-generic x86_64
- **Install tools**:
- **Others**:

**What happened**:
When ```--cloud-provider=aws``` is set on kubelet the following appears in logs:
```
I0322 15:42:12.601109   26590 aws.go:749] Building AWS cloudprovider
I0322 15:42:12.601346   26590 aws.go:703] Zone not specified in configuration file; querying AWS metadata service
error: failed to run Kubelet: could not init cloud provider "aws": error finding instance i-0361dc426667618be: error listing AWS instances: RequestError: send request failed
caused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp 54.239.29.8:443: i/o timeout
```
kubelet then exits. Our VPC containers 4000+ instances and an unfiltered called to describe-instances will time out. 

**What you expected to happen**: kubelet to start.

**How to reproduce it** (as minimally and precisely as possible): have thousands of EC2 instances running in your VPC and start kubelet with ```--cloud-provider=aws```

**Anything else we need to know**:
Could a filter be provided to limit the scope of the api call? Why does kubelet need to look up every single instance in the VPC?

**Comment by keir-rex** [comment]
Seeing this too after updating a the cloud-config, and launch configuration subsequently the AWS launch configuration for minion nodes, the only change was adding `--log-opt`s to dockerd:

From:
`Environment="DOCKER_OPTS=--storage-driver=overlay --iptables=false --ip-masq=false"`
To:
`Environment="DOCKER_OPTS=--storage-driver=overlay --iptables=false --ip-masq=false --log-opt max-size=500m --log-opt max-file=75"`

Have you found a solution to this?

**Comment by keir-rex** [comment]
Update: this was caused in my case by a typo the kubelet unit of our cloud_config which snuck past code-review:

```
-        --volume container,kind=host,source=/var/
-
-        /containers,readOnly=false \
+        --volume container,kind=host,source=/var/containers,readOnly=false \
```
