### ISSUE TITLE
Deployment fails with multiple containers with resource limits

### ISSUE THREAD

**Issue by martincalvert** [kubernetes/kubernetes#43530]
Kubernetes version 1.5.3
Environment: GKE & Minikube

**What happened**: When adding resource requests/limits to multiple containers inside a pod the  
error `unable to parse quantity's suffix` is tossed.

**What you expected to happen**: Allow the same syntax for multi container pods as kubernetes does for single container pods.

**How to reproduce it** (as minimally and precisely as possible):
`kubectl apply -f test_deployment.yaml`

_test_deployment.yaml_
```apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cms-api
  labels:
    chart: cms-0.1.39
  annotations:
    "helm/created": "1490203189"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cms
        tier: cms-api
    spec:
      containers:
        - name: cms
          image: nginx:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 1200mi
              cpu: 200m
            limits:
              memory: 2000Mi
              cpu: "1"
          ports:
            - containerPort: 3000
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 1200mi
              cpu: 200m
            limits:
              memory: 2000Mi
              cpu: "1"
          ports:
            - containerPort: 80
```

**Comment by martincalvert** [comment]
Closed my error

**Comment by Devying** [comment]
How did you solve the problem?

**Comment by Devying** [comment]
查看参数是否正确，比如命名空间是否存在，内存Mi是不是写成了mi

**Comment by dsutphin** [comment]
I found this on Google while trying to fix the same problem. For me the cause was not using the right case for the memory limit. 
Using "Mi" instead of "mi" fixed it for me.

**Comment by amritbrartech** [comment]
This helped

**Comment by BenjamenMeyer** [comment]
wow...ran into the same thing; such an non-obvious error with very little context too.

@dsutphin thanks - that did it for me too once I knew what to look for
