### ISSUE TITLE
Clear Upgrade Signal

### ISSUE THREAD

**Issue by ethernetdan** [kubernetes/kubernetes#43535]
We need a clear and passing upgrade signal for 1.6 in order to release. Currently several jobs are routinely timing out.

In order to release we need:
* [x] All upgrade tests to finish without timing out
* [ ] Out of the last 3 test runs each test should have passed twice
* [x] Total number of unexpected failed tests is fewer than 15%

**Comment by calebamiles** [comment]
cc: @davidopp

**Comment by ethernetdan** [comment]
Update: We are going to need more builds to meet the 3 run consecutive run minimum but I think we are on the right trajectory. The slow pace of master jobs makes it harder to get good runs plus lack of history to due to the time out issue.

## needs 3 consecutive passes
- gce-1.5-1.6-upgrade-cluster
- gce-1.5-1.6-upgrade-master
- gke-container_vm-1.4-gci-1.6-upgrade-cluster-new
- gke-container_vm-1.5-container_vm-1.6-upgrade-cluster
- gke-container_vm-1.5-container_vm-1.6-upgrade-master
- gke-container_vm-1.5-gci-1.6-upgrade-master
- gke-gci-1.4-container_vm-1.6-upgrade-master
- gke-gci-1.5-container_vm-1.6-upgrade-cluster
- gke-gci-1.5-container_vm-1.6-upgrade-master

## Has had 3 consecutive passes
- gce-1.5-1.6-upgrade-cluster-new: **43, 44, 45**
	- Caveats: failures in suite existed in 1.5; node resource tracking

- gke-container_vm-1.4-container_vm-1.6-upgrade-cluster: **104, 105, 106**
	- Caveats: expected deployments, affinity, and job deprecation

- gke-container_vm-1.4-container_vm-1.6-upgrade-cluster-new: **71, 73, 74**
	- Caveats: build 72 terminated by user; known and later fixed autoscaling failure

- gke-container_vm-1.4-container_vm-1.6-upgrade-master: **62, 63, 64**
	- Caveats: expected 1.4 deprecations

- gke-container_vm-1.4-gci-1.6-upgrade-cluster: **93, 94, 95**
	- Caveats: expected 1.4 deprecations; node resource tracking

- gke-container_vm-1.4-gci-1.6-upgrade-master: **70, 71, 72**
	- Caveats: expected 1.4 deprecations

- gke-container_vm-1.5-container_vm-1.6-upgrade-cluster: **67, 68, 69**
	- Caveats: Alpha affinity, known StatefulSet test issue, kubectl describe change

- gke-container_vm-1.5-gci-1.6-upgrade-cluster: **63, 64, 65**
	- Caveats: Alpha affinity, known StatefulSet test issue, 1.5 deployments issue, kubectl describe change

- gke-container_vm-1.5-gci-1.6-upgrade-cluster-new: **78, 79, 80**
	- Caveats: Node resource tracking

- gke-gci-1.4-container_vm-1.6-upgrade-cluster: **91, 92, 93**
	- Caveats: expected 1.4 deprecations, kubectl describe change, rescheduler test issue

- gke-gci-1.4-container_vm-1.6-upgrade-cluster-new: **67, 68, 69**
	- Caveats: fixed logging regression

- gke-gci-1.4-gci-1.6-upgrade-cluster: **106, 107, 108**
	- Caveats: expected 1.4 deprecations, kubectl describe change, rescheduler test issue

- gke-gci-1.5-gci-1.6-upgrade-cluster: **35, 36, 37**
	- Caveats: Resource tracking, expected StatefulSet issue

- gke-gci-1.4-gci-1.6-upgrade-cluster-new: **69, 70, 71**
	- Caveats: Node resource tracking

- gke-gci-1.4-gci-1.6-upgrade-master: **66, 67, 68**
	- Caveats: expected 1.4 deprecations, kubectl describe change, rescheduler test issue

- gke-gci-1.5-container_vm-1.6-upgrade-cluster-new: **69, 77, 78**
	- Caveats: 70-76 failed due to bug with RC release logic

- gke-gci-1.5-gci-1.6-upgrade-cluster-new: **76, 77, 78**
	- Caveats: Node resource tracking

- gke-gci-1.5-gci-1.6-upgrade-master: **50, 51, 52**
	- Caveats: Alpha affinity, known StatefulSet test issue, 1.5 deployments issue, kubectl describe change

**Comment by ethernetdan** [comment]
Update: a few more suites down, due to the infrequency of the master runs we may have to impose a tolerance of 1 flake per 3 runs.

## needs 3 consecutive passes
- gce-1.5-1.6-upgrade-cluster
- gce-1.5-1.6-upgrade-master
- gke-container_vm-1.4-gci-1.6-upgrade-cluster-new
- gke-container_vm-1.5-container_vm-1.6-upgrade-master
- gke-container_vm-1.5-gci-1.6-upgrade-master
- gke-gci-1.5-container_vm-1.6-upgrade-master

## Has had 3 consecutive passes
- gke-gci-1.4-container_vm-1.6-upgrade-master: **75, 76, 77**
	- Caveats: expected 1.4 deprecations, kubectl describe change, rescheduler test issue
- gke-container_vm-1.5-container_vm-1.6-upgrade-cluster: **67, 68, 69**
	- Caveats: Alpha affinity, known StatefulSet test issue, 1.5 deployments issue, kubectl describe change
- gke-gci-1.5-container_vm-1.6-upgrade-cluster: **57, 58, 59**
	- Caveats: Alpha affinity, known StatefulSet test issue, 1.5 deployments issue, kubectl describe change

**Comment by grodrigues3** [comment]
Any updates?

**Comment by ethernetdan** [comment]
I think we'll tolerate a flake every 3 runs for master and cluster, there will always be trouble running tests from previous versions the way they are configured. I really would like to see 3 runs out of the new but I'd tolerate a well known flake.

**Comment by ethernetdan** [comment]
Update: all new suites look good, all clusters except one below look good. Still several masters not there yet. I'm going to start allowing 1 flake per 3 runs for the next sweep.

## needs 3 consecutive passes
- gce-1.5-1.6-upgrade-cluster
- gce-1.5-1.6-upgrade-master
- gke-container_vm-1.5-container_vm-1.6-upgrade-master
- gke-container_vm-1.5-gci-1.6-upgrade-master
- gke-gci-1.5-container_vm-1.6-upgrade-master

## Has had 3 consecutive passes
- gke-container_vm-1.4-gci-1.6-upgrade-cluster-new: **81, 82, 83**

**Comment by ethernetdan** [comment]
The rest look reasonable given forgiving a flake per 3 runs so I'm going to close this. It's too bad we don't meet the 3 flake build SLA but given the nature of running tests from previous versions this may be expected. We should try in the future to figure out how to get more jobs in either through getting test time down or running parallel upgrades.
