### ISSUE TITLE
Proposal: Just Allow Health Check /healthz without authentification in Kube-apiserver

### ISSUE THREAD

**Issue by jfpucheu** [kubernetes/kubernetes#43540]
**What happened**:

When HTTPS is enable on the cluster and HTTP disable loadbalancer for API-server can't access /healthz whitout passing basic-auth or certificate. Loadbalancer can't pass auth or certificate.

**My Proposal**:

Juste Expose  page /healthz without authentification in http for healthcheck without exposins all APIs in http.

**Comment by jayunit100** [comment]
cc @liggitt might have another opinion on this though :)

**Comment by liggitt** [comment]
already done in https://github.com/kubernetes/kubernetes/pull/41821

**Comment by liggitt** [comment]
misread... this is proposing leaving the http port active serving only healthz info?

**Comment by jfpucheu** [comment]
exactly or add a specific port for healtz un http

**Comment by justinsb** [comment]
So what is the healthz endpoint / recommended liveness check for a secure setup (RBAC, kubeadm discovery not enabled, insecure port disabled)?

`curl https://127.0.0.1/healthz` is returning a 401 for me.

**Comment by unixwitch** [comment]
This would be useful for GCE's Network Load Balancer, which can't do https healthchecks.

**Comment by mikedanese** [comment]
This seems like an info leak by default. It would be better to allow this by authorizing "system:unathenticated" to access the /healthz endpoint through RBAC.

**Comment by mabushey** [comment]
@mikedanese  > It would be better to allow this by authorizing "system:unathenticated" to access the /healthz endpoint through RBAC.

Sounds great, how would a person go about implementing this?
