### ISSUE TITLE
Integration tests are failing if they run in parallel.

### ISSUE THREAD

**Issue by mkumatag** [kubernetes/kubernetes#43556]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** BUG

**Kubernetes version** (use `kubectl version`):

latest master branch
$ git rev-parse HEAD
e3f6f14bf0d1af6abbd20e48335089e9a681193f
$

**Environment**:
- **Cloud provider or hardware configuration**: Virtual machine
- **OS** (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`):
Linux localhost 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:
CPU - 2, Memory - 4GB

$ go version
go version go1.7.5 linux/amd64

**What happened**:
Integration tests are failing.

**What you expected to happen**:
Expecting integration tests all run fine without any errors.

**How to reproduce it** (as minimally and precisely as possible):
1. clone latest code from master branch.
2. Run integration tests as 
`$ make test-integration KUBE_GOFLAGS="-v"`

I see following tests are failing:

```
=== RUN   TestRBAC
I0323 05:24:56.407091    8526 services.go:35] Network range for service cluster IPs is unspecified. Defaulting to 10.0.0.0/24.
I0323 05:24:56.407112    8526 master.go:177] Node port range unspecified. Defaulting to 30000-32767.
W0323 05:24:57.309032    8526 storage_extensions.go:127] third party resource sync failed: Get http://127.0.0.1:37405/apis/extensions/v1beta1/thirdpartyresources: dial tcp 127.0.0.1:37405: getsockopt: connection refused
E0323 05:24:57.337710    8526 controller.go:162] unable to sync kubernetes service: Post http://127.0.0.1:37405/api/v1/namespaces: dial tcp 127.0.0.1:37405: getsockopt: connection refused
W0323 05:24:57.544464    8526 storage_extensions.go:127] third party resource sync failed: Get http://127.0.0.1:36972/apis/extensions/v1beta1/thirdpartyresources: dial tcp 127.0.0.1:36972: getsockopt: connection refused
....
....
k8s.io/kubernetes/vendor/github.com/golang/glog.stacks(0x49a2500, 0xc400000000, 0x57, 0x242)
	/root/k8s_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:766 +0xa5
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).output(0x4981ae0, 0xc400000003, 0xc420170240, 0x4511433, 0xf, 0x10d, 0x0)
	/root/k8s_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:717 +0x337
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).printDepth(0x4981ae0, 0xc400000003, 0x1, 0xc4308714e8, 0x1, 0x1)
	/root/k8s_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:646 +0x126
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).print(0x4981ae0, 0xc400000003, 0xc4308714e8, 0x1, 0x1)
	/root/k8s_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:637 +0x5a
k8s.io/kubernetes/vendor/github.com/golang/glog.Fatal(0xc4308714e8, 0x1, 0x1)
	/root/k8s_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:1125 +0x53
k8s.io/kubernetes/test/integration/framework.startMasterOrDie(0xc42397bb80, 0x0, 0x0, 0x0, 0xc430015501, 0xc427c68c70)
	/root/k8s_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/framework/master_utils.go:269 +0xa56
k8s.io/kubernetes/test/integration/framework.RunAMaster(0xc42397bb80, 0xc427c68c70, 0x49a2828)
	/root/k8s_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/framework/master_utils.go:476 +0x50
k8s.io/kubernetes/test/integration/auth.TestRBAC(0xc42d2cc0c0)
	/root/k8s_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/auth/rbac_test.go:420 +0xe66
testing.tRunner(0xc42d2cc0c0, 0x34aafb0)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec
FAIL	k8s.io/kubernetes/test/integration/auth	62.352s
```

```
--- PASS: TestMultiWatch (0.00s)
=== RUN   TestSelfLinkOnNamespace
I0323 05:24:56.889267    8556 services.go:35] Network range for service cluster IPs is unspecified. Defaulting to 10.0.0.0/24.
I0323 05:24:56.889309    8556 master.go:177] Node port range unspecified. Defaulting to 30000-32767.
W0323 05:25:00.418337    8556 storage_extensions.go:127] third party resource sync failed: Get http://127.0.0.1:33431/apis/extensions/v1beta1/thirdpartyresources: dial tcp 127.0.0.1:33431: getsockopt: connection refused
....
.....
k8s.io/kubernetes/vendor/github.com/golang/glog.stacks(0x49a3a00, 0xc400000000, 0x57, 0x25f)
	/root/k8s_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:766 +0xa5
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).output(0x4982fc0, 0xc400000003, 0xc4209989c0, 0x45118ab, 0xf, 0x10d, 0x0)
	/root/k8s_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:717 +0x337
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).printDepth(0x4982fc0, 0xc400000003, 0x1, 0xc4276edbd0, 0x1, 0x1)
	/root/k8s_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:646 +0x126
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).print(0x4982fc0, 0xc400000003, 0xc4276edbd0, 0x1, 0x1)
	/root/k8s_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:637 +0x5a
k8s.io/kubernetes/vendor/github.com/golang/glog.Fatal(0xc4276edbd0, 0x1, 0x1)
	/root/k8s_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:1125 +0x53
k8s.io/kubernetes/test/integration/framework.startMasterOrDie(0xc427b4d600, 0x0, 0x0, 0x0, 0x66, 0x3)
	/root/k8s_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/framework/master_utils.go:269 +0xa56
k8s.io/kubernetes/test/integration/framework.RunAMaster(0xc427b4d600, 0x4b6200, 0x4718e18)
	/root/k8s_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/framework/master_utils.go:476 +0x50
k8s.io/kubernetes/test/integration/client.TestSelfLinkOnNamespace(0xc427aaaa80)
	/root/k8s_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/client/client_test.go:827 +0x3f
testing.tRunner(0xc427aaaa80, 0x34a8970)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec
FAIL	k8s.io/kubernetes/test/integration/client	53.829s
```
**Anything else we need to know**:

In above failure what I've observed is both the tests are failed at same timestamp around `05:25:00` and I see tests are running parallel, I suspect something is wrong while these tests in parallel.

Note : I ran these tests serially by hacking test script with option `-p 1` and everything works fine.

Complete test logs can be found @ https://gist.github.com/mkumatag/37e18d2ee76730defedb1c918739561f

**Comment by xiangpengzhao** [comment]
@deads2k Would you help please? Thanks!

**Comment by deads2k** [comment]
> @deads2k Would you help please? Thanks!

Given that the integration tests all share a single etcd, I don't think these will ever be successfully run in parallel in the current structure.

**Comment by xiangpengzhao** [comment]
@deads2k Do you mean `make test-integration` doesn't run in parallel by default, right? If it doesn't, then it should run successfully. But it doesn't. I also encounter this issue. Any clue from the failure?

```
W0323 05:24:57.544464    8526 storage_extensions.go:127] third party resource sync failed: Get http://127.0.0.1:36972/apis/extensions/v1beta1/thirdpartyresources: dial tcp 127.0.0.1:36972: getsockopt: connection refused
```

**Comment by deads2k** [comment]
> Any clue from the failure?

Nothing leaps out.  Any indication that the server wasn't able to start serving?

**Comment by xiangpengzhao** [comment]
I'm not at office now so that I can't get more info. But I remember that seems I use docker (all right, moby) v1.13, maybe it's due to it changes the default FORWARD policy to DROP ?

**Comment by xiangpengzhao** [comment]
I run `iptables -P FORWARD ACCEPT` to enable forward but integration tests still fail. I'm totally confused.

**Comment by xiangpengzhao** [comment]
@MikeSpreitzer

**Comment by MikeSpreitzer** [comment]
I have not investigated the concurrency question in my own flailing yet.  I will see what I can see.  I do not even know where to find the logs from the apiservers under test.

BTW, https://github.com/kubernetes/community/blob/master/contributors/devel/development.md#go says that master requires go 1.8.1, if I understand correctly.  I myself have tried with go 1.8.1 on my Mac and go 1.8.3 in an Ubuntu VM.  The Ubuntu VM had more successes.

**Comment by MikeSpreitzer** [comment]
My first attempt with an Ubuntu VM gave it 5 GB of memory and 4 CPUs, and there were a lot of failures.  I am trying again with 6 GB of memory and 2 CPUs; so far all the tests are passing, but there are error messages even so.

Where does one hack in that `-p 1`?

**Comment by mkumatag** [comment]
Now with the latest upstream code you can invoke by `make test-integration GOFLAGS="-p 1"`

**Comment by MikeSpreitzer** [comment]
Can I mix `GOFLAGS` and `KUBE_FLAGS` or do I have to put all in one?

**Comment by xiangpengzhao** [comment]
Successful at last! The way @mkumatag provided works for me. Thanks Manjunath ! :+1: 

```
+++ [0603 11:00:22] Running tests without code coverage
ok  	k8s.io/kubernetes/test/integration/apiserver	5.448s
....
ok  	k8s.io/kubernetes/test/integration/volume	488.960s
ok  	k8s.io/kubernetes/vendor/k8s.io/kube-apiextensions-server/test/integration	45.744s
+++ [0603 11:38:58] Cleaning up etcd
+++ [0603 11:38:58] Integration test cleanup complete
```

It costs more than half an hour to complete the tests. I think it must be more than that w/o `GOFLAGS="-p 1"`. I still don't know what causes the flake. It might has something to do with the memory as is shown in Mike's attempt.

@MikeSpreitzer Mike, do you try this way?

**Comment by xiangpengzhao** [comment]
>Are GOFLAGS and KUBE_GOFLAGS interchangeable now? Can I split flags among the two, or do I have to put all in one?

After viewing the build/test scripts, I think `GOFLAGS` is exposed for developers and `KUBE_GOFLAGS` is used inside the scripts. So we'd better only use `GOFLAGS` when we run `make foo`, IMO.

@thockin Could you please confirm this? Thanks!

**Comment by thockin** [comment]
Truth: I have no idea why KUBE_GLOFLAGS exists.  I have a TODO to remove
it, one day when I get enough time.

**Comment by MikeSpreitzer** [comment]
So, getting back to the original point, I too am able to make the integration test suite claim complete success by using `-v -p 1`.  But I see many errors reported.  Should I be alarmed by them?  There is a complete typescript in https://gist.github.com/MikeSpreitzer/31e2855c714246a21c543b09f1cec3fc .  This was from a VM with 6 GB of memory and 2 vCPUs running Ubuntu 16.04 and go 1.8.3.  It took half an hour.

More to the point: must the integration tests be run with `-p 1`?  If so, then why is that not the default?

**Comment by xiangpengzhao** [comment]
@kubernetes/sig-testing-misc

**Comment by xiangpengzhao** [comment]
@kubernetes/sig-testing-misc
Oops, seems like the bot doesn't want to trigger a notification for me here. It works OK at https://github.com/kubernetes/kubernetes/issues/46359#issuecomment-306022569.
