### ISSUE TITLE
What's the intention to expose PodTemplate as an api object?

### ISSUE THREAD

**Issue by xinxiaogang** [kubernetes/kubernetes#43552]
I found that there is an object `PodTemplate` registered in apiserver which we can use as other kube objects.

From the struct definition, `PodTemplate` contains `PodTemplateSpec` just as other workload objects, such as rc. But I do not find any usage of `PodTemplate` object from either doc or code. And rc/ps/ss does not have any reference to `PodTemplate` actually.

So I want to understand:
- What's the intention to expose `PodTemplate` object from apiserver?
- Is this object a legacy one which will be retired in the future?

**Comment by kargakis** [comment]
@kubernetes/sig-apps-misc

**Comment by lukaszo** [comment]
Here you can read how it was created https://github.com/kubernetes/kubernetes/issues/170
