### ISSUE TITLE
cAdvisor container_network_* metrics are coming with container_name="POD" instead of container_name="real name of container"

### ISSUE THREAD

**Issue by natalia-k** [kubernetes/kubernetes#43560]
BUG REPORT:

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:  physical
- **OS** (e.g. from /etc/os-release): on-premise
- **Kernel** (e.g. `uname -a`):  Linux 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: 
- **Others**:

**What happened**:
The following 8 container_network* metrics are coming from cAdvisor with container_name="POD" instead of container_name="real name of container":

container_network_receive_bytes_total{container_name="POD"}
container_network_receive_errors_total{container_name="POD"}
container_network_receive_packets_dropped_total{container_name="POD"}
container_network_receive_packets_total{container_name="POD"}
container_network_transmit_bytes_total{container_name="POD"}
container_network_transmit_errors_total{container_name="POD"}
container_network_transmit_packets_dropped_total{container_name="POD"}
container_network_transmit_packets_total{container_name="POD"}

**What you expected to happen**:
the same like other container_* metrics , for example:  container_memory_usage_bytes{container_name="kubedns"....}

**How to reproduce it** (as minimally and precisely as possible):
see them under https://<node ip>:10250/metrics

**Anything else we need to know**:
Thanks!

**Comment by xiangpengzhao** [comment]
Seems they are metrics of infra container with name something like `k8s_POD.639b2af2_foo-web-315473031-e40e2_foobar_a369ace2-5fa9-11e6-b10f-c81f66e5e84d_851a97fd`

**Comment by natalia-k** [comment]
right, and with container_name="POD" but it should be with container_name="kubedns" (for example) like all other metrics (container_memory_usage_bytes,...)

**Comment by mkumatag** [comment]
Basically this container_name value comes form label called `io.kubernetes.container.name` which is POD in this case.

I just deployed nginx image for testing, what I see is for all the metrics except network there are 2 entries which is one for pause container and one for app container(nginx).

IMO network metrics are exposed only for POD container because only POD container does have network and app container will share the data from POD. So IMHO this is works as design.

**Comment by natalia-k** [comment]
@mkumatag  
Thanks a lot for the explanations! it's clear for me now and you are right.

But will possible/more easy to alert based on cAdvisor metrics if cAdvisor will export pod labels for container metrics (https://github.com/kubernetes/kubernetes/issues/32326),
hope it will implemented ever

Thanks for your help!
Natalia

**Comment by spiffxp** [comment]
/sig instrumentation
because metrics
/sig networking
because they're all network metrics

**Comment by spiffxp** [comment]
/sig network
because they're all network metrics
