### ISSUE TITLE
HPA policy event need some enhancement

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#43565]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
When I define a HPA policy and trigger the HPA policy works, I often get some event log such as `Computed the desired num of replicas: 22 (avgCPUutil: 54, current replicas: 4)`, and my feeling for this event is that the HPA is going to scale up my deployment from 4 to 22 replicas.

But we already have some policy to guard this to avoid some ping-pong scale-up/scale-down as here https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L59-L61

```
func calculateScaleUpLimit(currentReplicas int32) int32 {
	return int32(math.Max(scaleUpLimitFactor*float64(currentReplicas), scaleUpLimitMinimum))
}
```

I think that we should also update the event log a bit to reflect the **real** scale-up/scale-down number.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by jayunit100** [comment]
Makes sense; please paste what you'd like to see in the Event message just for concreteness ....

**Comment by gyliu513** [comment]
Thanks @jayunit100 , how about the following:

```
Computed the desired num of replicas: 22 (avgCPUutil: 54, current replicas: 4) based on HPA policy
Computed the desired num of replicas: 4 (avgCPUutil: 54, current replicas: 4) based on scale limit factor
```

I also have one question for 

```
func calculateScaleUpLimit(currentReplicas int32) int32 {
	return int32(math.Max(scaleUpLimitFactor*float64(currentReplicas), scaleUpLimitMinimum))
}
```
The above `calculateScaleUpLimit` is getting the `max` of the two, so the `scaleUpLimitFactor*float64(currentReplicas)` can be a big value if `currentReplicas` is big, such  as if the `currentReplicas` is 1000, then HPA will scale up to 2000? Does this will cause some issue for such scale up?

**Comment by DirectXMan12** [comment]
This is, at least, partially covered by the HPA status conditions work in Kubernetes 1.7.  Among other things, we have a condition indicating that the scaling has hit scaling cap, and why.

**Comment by gyliu513** [comment]
Good to know, will try to check this and to see if this can be closed later. Thanks @DirectXMan12
