### ISSUE TITLE
using network plugins \"cni\": cni config unintialized;

### ISSUE THREAD

**Issue by fedya** [kubernetes/kubernetes#43567]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5", GitCommit:"894ff23729bbc0055907dd3a496afb725396adda", GitTreeState:"clean", BuildDate:"2017-03-22T00:17:51Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/arm64"}

**Environment**:
root@android-qemu:~# uname -a
Linux android-qemu.local.lan 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:31:00 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux

# kubeadm version
kubeadm version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2074+a092d8e0f95f52", GitCommit:"a092d8e0f95f5200f7ae2cba45c75ab42da36537", GitTreeState:"clean", BuildDate:"2016-12-13T17:03:18Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/arm64"}

- **Cloud provider or hardware configuration**:
Cavium. THUNDERX hardware

- **OS** (e.g. from /etc/os-release):
VERSION="16.04.2 LTS (Xenial Xerus)"
- **Kernel** (e.g. `uname -a`):
Linux android-qemu.local.lan 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:31:00 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux

- **Install tools**:

from http://apt.kubernetes.io/ kubernetes-xenial main

- **Others**:

**What happened**:
kubeadm init

root@android-qemu:~# kubectl get pods --all-namespaces
NAMESPACE     NAME                                             READY     STATUS              RESTARTS   AGE
kube-system   dummy-3142566829-7n3zs                           1/1       Running             0          9m
kube-system   etcd-android-pok.local.lan                      1/1       Running             0          9m
kube-system   kube-apiserver-android-pok.lan            1/1       Running             0          7m
kube-system   kube-controller-manager-pok.local.lan   1/1       Running             0          7m
kube-system   kube-discovery-1882371488-7x47c                  1/1       Running             0          9m
kube-system   kube-dns-1562134285-sbdbv                        0/4       ContainerCreating   0          9m
kube-system   kube-proxy-t8371                                 1/1       Running             0          9m
kube-system   kube-scheduler-pok.local.lan            1/1       Running             0          8m

and kube-dns service can't start
journalctl -xn 200 -u kubelet -l
show me such things
![spectacle tj8266](https://cloud.githubusercontent.com/assets/598477/24247953/828b486e-0fde-11e7-97d6-d868e95fe6b8.png)
![spectacle tj8424](https://cloud.githubusercontent.com/assets/598477/24248059/eb9cbacc-0fde-11e7-9715-81cfe3d7889b.png)

I tried flannel network with same results

**What you expected to happen**:

kube-dns working as expected

**Comment by cmluciano** [comment]
@sig-network-bugs

**Comment by fedya** [comment]
Same for 1.6.1

```
Apr 19 11:09:02 android-qemu kubelet[14379]: W0419 11:09:02.554385   14379 cni.go:157] Unable to update cni config: No networks found in /etc/cni/net.d
Apr 19 11:09:02 android-qemu kubelet[14379]: E0419 11:09:02.554677   14379 kubelet.go:2067] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is
Apr 19 11:09:07 android-qemu kubelet[14379]: W0419 11:09:07.556716   14379 cni.go:157] Unable to update cni config: No networks found in /etc/cni/net.d
Apr 19 11:09:07 android-qemu kubelet[14379]: E0419 11:09:07.557007   14379 kubelet.go:2067] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is
Apr 19 11:09:10 android-qemu kubelet[14379]: I0419 11:09:10.261784   14379 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/configmap/2e5601e4-24ec-11e7-81e3-70106fb9eb43-kube-p
Apr 19 11:09:10 android-qemu kubelet[14379]: I0419 11:09:10.261833   14379 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/2e5601e4-24ec-11e7-81e3-70106fb9eb43-kube-prox
Apr 19 11:09:12 android-qemu kubelet[14379]: W0419 11:09:12.558946   14379 cni.go:157] Unable to update cni config: No networks found in /etc/cni/net.d
```

**Comment by fedya** [comment]
When i copied 10-flannel.conf from working deployment i got this

`Plugin cni failed on the status hook for pod "kube-dns-2286869516-hd2lg_kube-system": Unexpected command output nsenter: cannot open : No such file or director`

**Comment by xiangpengzhao** [comment]
As for `nsenter`, you should have it in your $PATH.
See https://github.com/jpetazzo/nsenter

**Comment by dcbw** [comment]
I think kubeadm should be setting up networking here, if it's not using kubenet?  i think this is a configuration issue that's not really related to sig/network.

**Comment by netroby** [comment]
kubeadm can not setup the master node, due to the fuck cni missing error report.

cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d

**Comment by netroby** [comment]
If the kube master node not setup. the network pod can not apply by kubectl apply ,

```
[root@scw-4df604 ~]# mkdir -p $HOME/.kube
[root@scw-4df604 ~]#   sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
[root@scw-4df604 ~]#   sudo chown $(id -u):$(id -g) $HOME/.kube/config
[root@scw-4df604 ~]# 
[root@scw-4df604 ~]# kubectl get po
The connection to the server 10.8.189.15:6443 was refused - did you specify the right host or port?

```

**Comment by Docker-Image-Templates** [comment]
Hi everyone, I am trying to get up and running kubernetes cluster on Linux CentOs v7.3 | Docker 1.12.6 | kubeadm v1.7.3 following installing guide in https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/, but I still getting errors that were reported in previous versions of kubeadm/kubelet like: kubeadm stuck on waiting to control plane to become ready, etc. I can see from kubelet logs that docker cni network is uninitialised and kubelet cannot reach HTTPS API Server on Port 6443. I gladly appreciate any hints how to resolve this. Thanks in advance

`cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d`
`message:docker: network plugin is not ready: cni config uninitialized`

**Comment by ashish-billore** [comment]
I am seeing the exact same error with kubeadm, where it is struck forever at:

`[apiclient] Created API client, waiting for the control plane to become ready
`
In the "journalctl -r -u kubelet" I see these lines over and over:

`Aug 31 16:34:41 k8smaster1 kubelet[8876]: E0831 16:34:41.499982    8876 kubelet.go:2136] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 31 16:34:41 k8smaster1 kubelet[8876]: W0831 16:34:41.499746    8876 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d `

Version details are:
`kubeadm version: &version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Kubectl version: Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

OS Details are:
  Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
  Kernel: Linux 3.10.0-514.el7.x86_64
  Architecture: x86-64
`
Any help is very much appreciated!

**Comment by eko** [comment]
Hello,

For information, I had this issue: Kubernetes introduces RBAC since v1.6, we need to create correspond Service Account, RBAC rules and flannel daemonset so that kubelet can communicate with api server correctly.

You have to run:

```
$ kubectl create -f https://raw.githubusercontent.com/coreos/flannel/v0.9.0/Documentation/kube-flannel.yml
```

I hope it helps.

**Comment by luxas** [comment]
This message occurs when there is no network plugin installed. Just apply a network plugin (like `kubectl apply -f https://git.io/weave-kube-1.6`) like described as the second step in the official setup guide, and things will work. RBAC rules are needed as @eko pointed out as well

**Comment by mcqj** [comment]
@luxas What and where is the official setup guide? Thanks

**Comment by pradheba-rangarajan** [comment]
> Hello,
> 
> For information, I had this issue: Kubernetes introduces RBAC since v1.6, we need to create correspond Service Account, RBAC rules and flannel daemonset so that kubelet can communicate with api server correctly.
> 
> You have to run:
> 
> ```
> $ kubectl create -f https://raw.githubusercontent.com/coreos/flannel/v0.9.0/Documentation/kube-flannel.yml
> ```
> I hope it helps.

Thank you very much! Worked like a charm

**Comment by ZW007** [comment]
> This message occurs when there is no network plugin installed. Just apply a network plugin (like `kubectl apply -f https://git.io/weave-kube-1.6`) like described as the second step in the official setup guide, and things will work. RBAC rules are needed as @eko pointed out as well

I have already done: `sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml ` on the master node after `kubeadm init` . This is a must step that every tutorial gives. 

I have worker node connected to the cluster, but its status is not ready. @luxas @pradheba-rangarajan @eko 
![image](https://user-images.githubusercontent.com/45562036/123890613-1edcd500-d91d-11eb-9961-e0b75ef3064d.png)

![image](https://user-images.githubusercontent.com/45562036/123890590-171d3080-d91d-11eb-9998-efb5f9c57d7f.png)

**Comment by neolit123** [comment]
instead of flannel try a different CNI plugin like WeaveNet or Calico.
