### ISSUE TITLE
Allow `kubectl port-forward` to use "services"

### ISSUE THREAD

**Issue by akram** [kubernetes/kubernetes#43570]
`kubectl port-forward` should give the ability to forward trafic to a service not only a pod.

This is convenient for developer/debugging purposes and especially for non HTTP/SNI protocols that cannot use routes and that we don't want to expose through nodePort.

Implementation could be done using the /proxy url to send trafic to the service, and netcat/socat to handle it through a local port.

It may require to add an additional flag --service=service-name or use the svc/<svc_name> syntax

**Comment by liggitt** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by shahidhk** [comment]
Duplicate of #15180
