### ISSUE TITLE
Re-enable Horizontal Pod Autoscaler upgrade tests

### ISSUE THREAD

**Issue by ethernetdan** [kubernetes/kubernetes#43579]
During the 1.6 release it was determined that the [Horizontal Pod Autoscaler (HPA) upgrade test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/upgrades/horizontal_pod_autoscalers.go) was causing upgrade jobs to timeout.

We should try to determine the root cause, fix the issue, and [re-enable when possible](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/cluster_upgrade.go).

**Comment by ethernetdan** [comment]
Related:  #43187

**Comment by krousey** [comment]
Also, HPA will need manual upgrade testing. @jszczepkowski

**Comment by krousey** [comment]
cc @skriss

**Comment by krousey** [comment]
@jszczepkowski Who is doing the manual upgrade test since this has now been removed?

**Comment by krousey** [comment]
cc @enisoc

**Comment by anhowe** [comment]
created #43638 to track manual upgrade

**Comment by jszczepkowski** [comment]
The test was re-enabled.
