### ISSUE TITLE
Downgrade testing for Deployments hangs

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#43584]
The downgrade script hangs when downgrading a 1.6 cluster.

**Comment by ethernetdan** [comment]
@pwittrock is this the same as https://github.com/kubernetes/kubernetes/issues/43470#issuecomment-288845358?

**Comment by janetkuo** [comment]
@ethernetdan yes it is

**Comment by anhowe** [comment]
@ethernetdan @pwittrock - may we close this as a duplicate and known issue

**Comment by ethernetdan** [comment]
sgtm
