### ISSUE TITLE
cidr_set does not support IPv6

### ISSUE THREAD

**Issue by rpothier** [kubernetes/kubernetes#43588]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
latest master

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
On code inspection it was found that the function newCIDRSet()
is converting all IP addresses to IPv4 with To4()

**What you expected to happen**:
This should support IPv4 and IPv6

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by danehans** [comment]
https://github.com/kubernetes/kubernetes/issues/1443
