### ISSUE TITLE
kubenet: remove code forcing bridge MAC address

### ISSUE THREAD

**Issue by dcbw** [kubernetes/kubernetes#43583]
A while back code (https://github.com/containernetworking/cni/pull/254) was added to CNI's 'bridge' plugin to ensure a consistent bridge MAC address based on the IP address given to the bridge.  This means we can effectively revert some of https://github.com/kubernetes/kubernetes/issues/30783 because that functionality is now handled by CNI.

**Comment by xiangpengzhao** [comment]
Reverted in #43661 .
