### ISSUE TITLE
Patch applies defaults from other group

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#43589]
I am creating a deployment in the extensions group and when I do a `kubectl edit` or `kubectl patch`, the defaults from the apps group are applied. Normal updates work fine (tried `kubectl scale`).
http://pastebin.com/CsNGsZxK
Note the additional `progressDeadlineSeconds` and `revisionHistoryLimit` fields

cc: @kubernetes/sig-api-machinery-misc @soltysh

**Comment by liggitt** [comment]
can you run this with high verbosity? Prior to https://github.com/kubernetes/kubernetes/pull/43553 merging, that will run against the apps group
```
kc patch deploy busy -p '{"spec":{"minReadySeconds":20}}'
```

**Comment by kargakis** [comment]
http://pastebin.com/FCmyQKSx

**Comment by liggitt** [comment]
yeah, you're submitting the patch to `deployment.apps`:
```
I0323 16:53:38.702858   26178 request.go:991] Request Body: {"spec":{"minReadySeconds":20}}
I0323 16:53:38.703158   26178 round_trippers.go:398] curl -k -v -XPATCH  -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: kubectl/v1.7.0 (linux/amd64) kubernetes/8b0e832" -H "Accept: application/json" https://localhost:6443/apis/apps/v1beta1/namespaces/default/deployments/busy
I0323 16:53:38.707339   26178 round_trippers.go:417] PATCH https://localhost:6443/apis/apps/v1beta1/namespaces/default/deployments/busy 200 OK in 4 milliseconds
```

**Comment by kargakis** [comment]
Works fine on HEAD
