### ISSUE TITLE
Make it possible to build kubernetes without cgo

### ISSUE THREAD

**Issue by copumpkin** [kubernetes/kubernetes#43580]
**Is this a request for help?**: Nope

**What keywords did you search in Kubernetes issues before filing this one?**: cgo, CGO_ENABLED

---

**Is this a BUG REPORT or FEATURE REQUEST?**: Feature request

This feature request started on the minikube issue tracker, but basically it greatly complicates the build process to use cgo, since in the minikube case at least we need to run Docker to produce localkube and Docker isn't always available. At least one of the reasons we need cgo to build today is that the vendored version of `go-systemd` in here is older, and a more recent version more cleanly separates out the parts of the library that require native libraries from the parts that can be written in pure Go.

So anyway, I think a lot of the build would get a lot easier and cleaner if we could use the native Go cross-compilation support instead of having to hack around cgo and native toolchains

Here's the minikube issue for context: 
https://github.com/kubernetes/minikube/issues/1238#issuecomment-288812315

cc @r2d4 @aaron-prindle @dlorenc

**Comment by ncdc** [comment]
FYI #41262 bumps go-systemd so you can compile without cgo.

**Comment by copumpkin** [comment]
@ncdc do you know if `go-systemd` is the only thing forcing cgo right now?

**Comment by ncdc** [comment]
@copumpkin there were some other dependencies previously but I believe I got all of them fixed. https://github.com/kubernetes/kubernetes/pull/38631 was another one but it merged a while ago.

**Comment by copumpkin** [comment]
Oh, nice! This will be very cool for minikube (and probably anyone who wants to build k8s!)

**Comment by kargakis** [comment]
@ncdc can we close this issue now?

**Comment by ncdc** [comment]
@kargakis let's wait and see what @copumpkin reports

**Comment by copumpkin** [comment]
Oh sorry, missed the updates. Should the build scripts disable cgo so we don't accidentally get cgo dependencies creeping in again?

**Comment by ncdc** [comment]
I don't think we want it disabled entirely, given that some portions use it
(kubelet/cadvisor).

**Comment by copumpkin** [comment]
Oh, perhaps I'm misunderstanding then. My goal with this ticket was to be able to build whichever parts of k8s were needed in minikube's localkube without cgo. Isn't kubelet the main upstream component of localkube? My hope was to eliminate the need for cgo there.

If there are still things that need cgo in the build, it seems worthwhile to try to enumerate them and understand if the dependency is fundamental or incidental (as the the `go-systemd` one ended up being).
