### ISSUE TITLE
[Federation] Make sure that all documentation about Federated services explains that you need to own the relevant domain name

### ISSUE THREAD

**Issue by perotinus** [kubernetes/kubernetes#43599]
We should make sure that all documentation about Federated services/setting up DNS for Federation explains that you must own the domain name. We do mention this in our documentation, but it's an easy thing to miss and it can be very tricky to diagnose if you don't know that you need to do it.

It may be worth noting as well that, if you don't care about access from the public Internet and your provider supports it, you can use private DNS zones.

**Comment by perotinus** [comment]
cc @madhusudancs

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#124.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
