### ISSUE TITLE
Race condition between PV getting deleted and a new pvc requested

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#43592]
There appears to be a race condition when user deletes a PVC that dynamically creates PV and there is a pod in pending state because a PVC that it uses is in pending state because no 'free' PV is available.

In that case, the  PVC gets deleted and PVC that wants a 'free' PV gets bound to dynamically allocated PV but code appears to try and delete that PV anyways.

In that case dynamically allocated PV enters "Failed" state with following error:

```
    ReadOnly:   false
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                            -------------   --------        ------                  -------
  12m           12m             1       {persistentvolume-controller }                  Warning         VolumeFailedDelete      Delete of volume "pvc-7f13ffcb-1010-11e7-90e8-0e7a84f7b108" failed: error deleting EBS volumes: VolumeInUse: Volume vol-08d0c910a13d2b375 is currently attached to i-09ca42267120a32dd
                status code: 400, request id: 
```

**Comment by gnufied** [comment]
cc @jsafrane @kubernetes/sig-storage-bugs

**Comment by NickrenREN** [comment]
findByClaim() should find PV which phase is Available ?

**Comment by jsafrane** [comment]
@gnufied, can you please describe more in detail what are the PVs and PVCs that lead to this bug? Especially, how many PVCs are involved?

PV that is dynamically provisioned for a PVC can never be used by any other PVC, see https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go#L1324
Is this assumption broken?

**Comment by gnufied** [comment]
okay, I need to look bit deeper. But I *do* need to provide more details:

First thing is - this happened in openshift-3.4.1.10 not with latest kubernetes release. 

Secondly - I was using `oc new-app` feature which automatically creates a PVC.  I am going to close this and investigate this from openshift perspective. Sorry for the noise.
