### ISSUE TITLE
[Federation] Print out namespace on each line during Federation E2E tests

### ISSUE THREAD

**Issue by perotinus** [kubernetes/kubernetes#43596]
Now that the Federation E2E tests are running in parallel, the logs from the control manager and the API server are very difficult to understand because of the number of interleaved operations. We should add the namespace (or, more specifically, the five-character unique suffix that we add to the namespace template we use for tests) to each of the log statements so that we can grep through the logs and make it easier to follow what's going on.

In theory, we may be able to do this in the Federation version of the test framework library that does logging.

cc @csbell @nikhiljindal

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#123.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
