### ISSUE TITLE
[Bug] threadSafeMap: the obj has already been removed， but index is still in it

### ISSUE THREAD

**Issue by shenlanse** [kubernetes/kubernetes#43605]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):    
BUG

---

**Kubernetes version** (use `kubectl version`):    
k8s1.3.5. still exist in 1.6

---

**What happened**:    

when exec threadSafeMap.Index func, the returned items contain nil object. That is to say, index is in threadSafeMap but the corresponding has already been deleted.

---

**What you expected to happen**:     
when object is deleted from threadSafeMap, **all its index** must be deleted.

---

**How to reproduce it** (as minimally and precisely as possible):  

Suppose we init threadSafeMap with two indexers: **indexFunc1 and indexFunc2**.

Obviously, **indexFunc may return error** if the object has something wrong or some other reasons.

when we add an object, will first add the object to threadSafeMap.items, then compute the index and add the index into threadSafe.indices.

```
func (c *threadSafeMap) Add(key string, obj interface{}) {
	c.lock.Lock()
	defer c.lock.Unlock()
	oldObject := c.items[key]
	c.items[key] = obj
	c.updateIndices(oldObject, obj, key)
}

func (c *threadSafeMap) updateIndices(oldObj interface{}, newObj interface{}, key string) error {
	// if we got an old object, we need to remove it before we add it again
	if oldObj != nil {
		c.deleteFromIndices(oldObj, key)
	}
	for name, indexFunc := range c.indexers {
		indexValues, err := indexFunc(newObj)
		if err != nil {
			return
		}
		index := c.indices[name]
		if index == nil {
			index = Index{}
			c.indices[name] = index
		}

		for _, indexValue := range indexValues {
			set := index[indexValue]
			if set == nil {
				set = sets.String{}
				index[indexValue] = set
			}
			set.Insert(key)
		}
	}
	return nil
}
```

when we delete the object, will first delete the index from indices, then delete it from threadSafeMap.items.

```
func (c *threadSafeMap) Delete(key string) {
	c.lock.Lock()
	defer c.lock.Unlock()
	if obj, exists := c.items[key]; exists {
		c.deleteFromIndices(obj, key)
		delete(c.items, key)
	}
}
```

Suppose **IndexFunc1(object) return error and indexFunc2(object) works well**. I think this circumstance is absolutely possible to happen.

Also we know that **the order to exec  indexFunc is not decided.** Feature of iterating map.

```
	for name, indexFunc := range c.indexers {
		indexValues, err := indexFunc(newObj)
		if err != nil {
			return
		}
		... ...
	}
```

When we add object, suppose **first exec indexFunc2, and then exec indexFunc1**.  So the index of indexFunc2 is added to indices. But the index of indexFunc1 is not added, because indexFunc1(obj) return err.

Then we delete the object, suppose **first exec indexFunc1**. It will return error and IndexFunc2 has no chance to run. So the corresponding index indexFunc2(obj) can't be removed. But then the object is removed from items.

This problem may result in subtle problems.
For example, when we exec threadSafeMap.Index( ) func ，the returned list may include nil object.

---

**Anything else we need to know**

The reason is that index is still is threadSafeMap but the corresponding object has already been removed.

We must clear all corresponding indexs when delete object.

And the reason why index is not deleted is that when for-range map, the order is not decided.

---

**Comment by shenlanse** [comment]
Who can help me? Do i miss something important or misunderstand it ?
@davidopp @lavalamp

**Comment by k82cn** [comment]
@shenlanse , can you share a unit test to show it? I'd like to help on it.

**Comment by shenlanse** [comment]
Thank you for your help. I think i have decribed the condition resulting in the bug indetail. Be simple, because the order of exec indexFunc is random when update indices, and some function don't care the error returned, the obj is deleted but corresponding indices is still in it.  
**NOTE: the obj is deleted but corresponding indices is still in it**
So when we  run index func, the returned list may contain nil object. Because when get obj from threadsafemap with indice,  not care whether the obj exist in this map. Then nil object added.

**Comment by shenlanse** [comment]
@timothysc  @erictune .  I am sure this problem exists. And i think we can find a better way to deal with it.

**Comment by spiffxp** [comment]
/sig api-machinery
threadSafeMap is in client-go

**Comment by ash2k** [comment]
Opened a PR with a fix.

**Comment by zhouhaibing089** [comment]
@shenlanse In my understanding, `IndexFunc` should be deterministic, could you elaborate more how the IndexFunc implemented? If an object can not be called on this `IndexFunc`, then the question is, how could it exist in `Indices` at the first beginning?

**Comment by shenlanse** [comment]
@zhouhaibing089  threadSafeStore should tolerate some bad conditions and deal with it gracefully, instead  generating strange and confusing phenomenon.

ThreadSafeStore can contain mutiple index funcs. If one of them is not implemented very well, or one of objects we pass to it has something wrong,  STRANGE AND CONFUSING phenomenon happens, see what I said above.

**Comment by zhouhaibing089** [comment]
> If one of them is not implemented very well, or one of objects we pass to it has something wrong

That's the point I would like to know more, the `IndexFunc` call on an object should succeed or fail unconditionally(deterministic).

**Comment by shenlanse** [comment]
@zhouhaibing089  wechat 908910016

**Comment by ash2k** [comment]
I also think index function must be a pure function. See my comment on the pr https://github.com/kubernetes/kubernetes/pull/50555#issuecomment-322757517
