### ISSUE TITLE
[Deployment] revisionHistoryLimit cannot be remove or update to nil if it is created with a specific value

### ISSUE THREAD

**Issue by wanghaoran1988** [kubernetes/kubernetes#43613]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1432+4862989d6169b5-dirty", GitCommit:"4862989d6169b524701aface4bb5e3cea7e419f2", GitTreeState:"dirty", BuildDate:"2017-03-22T08:08:20Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1432+4862989d6169b5-dirty", GitCommit:"4862989d6169b524701aface4bb5e3cea7e419f2", GitTreeState:"dirty", BuildDate:"2017-03-22T08:02:13Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:GCE
- **OS** (e.g. from /etc/os-release):
BUILD_ID=9000.84.2
NAME="Container-Optimized OS"
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=56
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=56
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
- **Kernel** (e.g. `uname -a`):
Linux e2e-test-haoran-master 4.4.21+ #1 SMP Fri Feb 17 15:34:45 PST 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
- **Install tools**:kops

**What happened**:
spec.revisionHistoryLimit cannot updated back to nil, or remove if you set the spec to a specific NO.

**What you expected to happen**:
We can update to nil or can remove the spec.revisionHistoryLimit field to let the default value work

**How to reproduce it** (as minimally and precisely as possible):
1. Create a deployment
kubectl create -f http://k8s.io/docs/tutorials/stateless-application/deployment.yaml
2. Update the deployment set spec.revisionHistoryLimit : 2
3. Update the deployment set spec.revisionHistoryLimit : nil or remove that field
4. Check the revisionHistoryLimit field

**Comment by kargakis** [comment]
Works fine, make sure you are using HEAD and you have cleaned up the discovery docs
rm -rf .kube/cache
