### ISSUE TITLE
expected pod "" success error during upgrade

### ISSUE THREAD

**Issue by ethernetdan** [kubernetes/kubernetes#43610]
During upgrades an error is encountered:
```
Expected error:
    <*errors.errorString | 0xc420bfef60>: {
        s: "expected pod \"\" success: <nil>",
    }
    expected pod "" success: <nil>
not to have occurred
```
Error from: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.5-1.6-upgrade-master/36

Other failures:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.5-container_vm-1.6-upgrade-master/51

/cc @skriss @krousey

**Comment by liggitt** [comment]
requires https://github.com/kubernetes/test-infra/pull/2330

**Comment by ethernetdan** [comment]
@liggitt I'm wondering if there might be an additional issue here, looks like we have been having [similar failures](http://storage.googleapis.com/k8s-gubernator/triage/index.html?text=s%3A%20%22expected%20pod%20#882f68fd678e76ae3137) for a while now with the etcd upgrade tests.

**Comment by krousey** [comment]
This is a storage flake combined with incorrect logging. This is the pv
upgrade test's test pod failing to start because mounting the pv failed.

**Comment by ethernetdan** [comment]
Not blocking under @krousey's guidance

**Comment by krousey** [comment]
https://github.com/kubernetes/kubernetes/pull/43641 Aims to improve the logging of this error, not fix it.
