### ISSUE TITLE
Failing to get logs during upgrade

### ISSUE THREAD

**Issue by ethernetdan** [kubernetes/kubernetes#43611]
Upgrade fails with:
```
Expected error:
    <*errors.errorString | 0xc420eb1400>: {
        s: "failed to get logs from pod-configmap-515024c8-101a-11e7-b5da-0242ac110008 for configmap-volume-test: an error on the server (\"unknown\") has prevented the request from succeeding (get pods pod-configmap-515024c8-101a-11e7-b5da-0242ac110008)",
    }
    failed to get logs from pod-configmap-515024c8-101a-11e7-b5da-0242ac110008 for configmap-volume-test: an error on the server ("unknown") has prevented the request from succeeding (get pods pod-configmap-515024c8-101a-11e7-b5da-0242ac110008)
not to have occurred
```
Error from: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1.4-gci-1.6-upgrade-master/62

Related failures:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1.4-container_vm-1.6-upgrade-master/69
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.4-gci-1.6-upgrade-master/69

**Comment by liggitt** [comment]
requires https://github.com/kubernetes/test-infra/pull/2330

**Comment by ethernetdan** [comment]
Looks like [these failures](http://storage.googleapis.com/k8s-gubernator/triage/index.html?text=failed%20to%20get%20logs%20from#8811541c43f138d7e064) are pretty isolated to upgrade tests.

**Comment by ethernetdan** [comment]
Also we didn't start seeing this until the ABAC default change merged so I think @liggitt's change might help

**Comment by liggitt** [comment]
it will definitely help with the jobs mentioned in the description of https://github.com/kubernetes/test-infra/pull/2330

**Comment by ncdc** [comment]
I haven't looked at the logs, so sorry if this is just noise, but the symptom (couldn't get logs b/c pod doesn't exist) looks very similar to what happened when the kubectl taint e2e tests were running in parallel instead of serial.

**Comment by krousey** [comment]
Judging by the comment https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L2245 and digging into the history https://github.com/kubernetes/kubernetes/commit/0efe5e7872dddfa817f90dfc4ca666c6d63469c1#diff-8349006db2c242fd7424e1dfb3295840R339 , this used to be wrapped in a retry loop. It was removed in https://github.com/kubernetes/kubernetes/commit/f9a2c07c2007531d35af33931af114fd90540af3 PR https://github.com/kubernetes/kubernetes/pull/31829

**Comment by liggitt** [comment]
it looks like this is limited to gke jobs in the upgrade tests. since getting pod logs depends on master->node communications, which would be affected by the SSH tunnels issue (https://github.com/kubernetes/kubernetes/issues/43612)

**Comment by ethernetdan** [comment]
Not blocking under @krousey's guidance
