### ISSUE TITLE
Provision/deprovision non-mountable storage

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#43628]
Scenario:  I want to stamp out many instances of a microservice.  Each microservice instance is a collection of objects (service(s), deployment(s), pod(s) etc).  Also, each instance needs some object storage.

Object storage is storage that you access via code rather than the filesystem.  Examples are: AWS s3, GCS, Minio, Rados+Radosgw, etc.

What if Kubernetes had a Kind that represented  an allocation of Object storage:
- When you create the object it allocates object storage.   You can ask for an amount if you want.
- When you delete the object it frees the object storage (according to some policy).
- When you want to consume it from a pod, you can.  Except instead of mounting a volume, I just need to get the bucket name and credentials for accessing that bucket somewhere my program can find it.

@saad-ali pointed out that this could pretty much be done already using a PVCs and PVs and a custom provisioner.  Instead of mounting the Object Storage as a file system, the mounter could just mount the auto-selected bucket-name and API credentials in an appropriate place.  This could be a flex volume, or maybe we could create volume types for each of the various object storage systems.

**Comment by erictune** [comment]
@matchstick 
@kubernetes/sig-storage-feature-requests

**Comment by erictune** [comment]
@kelseyhightower

**Comment by saad-ali** [comment]
To expand on this, a possible quick and dirty way to achive this:
* We could create an [external provisioner](https://github.com/kubernetes-incubator/external-storage#external-provisioners) that creates and delete object storage.
* A storage class can then be created pointing to this provisioner.
* Then when a PVC is created the external provisioner is triggered to create the storage.
* After the storage is provisioned, the provisioner has to create a PV object to represent that storage. This is the part that is a little iffy. It could create a PV referencing a Flex volume with a custom driver.
* When the PVC is referenced by a pod, it will be treated like a Flex volume plugin, and the "mount" step of the custom Flex driver can just obtain and mount the credentials into the container (and nothing else).

**Comment by saad-ali** [comment]
CC @kubernetes/sig-storage-feature-requests

**Comment by thockin** [comment]
I'm not sure I buy the overloading of PV/PVC, and I am not sure this should be a builtin Kind - this seems like a good use for TPR, at least initially?

**Comment by smarterclayton** [comment]
I'd prefer a tpr and a secret to deliver a path, in combo with pod preset.  Object storage really isn't a volume - it's a set of credentials pointin to a service, which is what podpreset solves.

**Comment by smarterclayton** [comment]
@pmorie @jessfraz re podpreset

**Comment by bgrant0607** [comment]
This is a service catalog use case IMO.

**Comment by bgrant0607** [comment]
I also don't buy overloading PV/PVC, if the result isn't a filesystem mounted into a pod.
