### ISSUE TITLE
Provide a way to add entries to /etc/hosts

### ISSUE THREAD

**Issue by klausenbusk** [kubernetes/kubernetes#43632]
**Is this a request for help?**
No

**What keywords did you search in Kubernetes issues before filing this one?**

Ingress, hosts and /etc/hosts
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

There have already been a few issues regarding modifying `/etc/hosts`: https://github.com/kubernetes/kubernetes/issues/20079, https://github.com/kubernetes/kubernetes/issues/12337.

But both have a different use-case.

First some information before I explain my use-case. I have a pod which run a web app (nginx container + php-fpm container) and it available over multiple sub domains. I want request to the exposed sub-/domains (ex. foobar.com) to go directly to the local webserver instant of going the long way (Cloudflare -> Ingress Controller -> Node -> Container).
There is 2 reason behind this:
1. It is faster/reduce overhead.
2. Some of our app code call the exposed domains, and need to hit the same server, as the request oriented from (the code write to some tmp file, and other PHP code need to read that tmp file, when it get a request. Bad design: properly).

cc @thockin 

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4+coreos.0", GitCommit:"97c11b097b1a2b194f1eddca8ce5468fcc83331c", GitTreeState:"clean", BuildDate:"2017-03-08T23:54:21Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
DigitalOcean, CoreOS.

**Comment by thockin** [comment]
I'm not sure I understand the use case, especially the 2nd.  This is the case of a pod talking to itself via the public hostname?  Why not just use localhost?

**Comment by klausenbusk** [comment]
> This is the case of a pod talking to itself via the public hostname?

Public hostname == ingress `Host`.
Yes, without going through the load balancer, some of the PHP also require "sticky" sessions and then it is just easier if the exposed domains just point to localhost.

> Why not just use localhost?

That require extra logic in the app code and when the app code expose multiple sub-/domains, then it is just easier adding the domain to /etc/hosts.

**Comment by thockin** [comment]
Do you know all the hostnames at pod startup time, or can they possibly be added later?  I guess I am not against this idea in principle, I just have a nagging suspicion it will blow in all the corner cases.

I guess we could look at a community implementation, if someone did one.  I don't think that we have time on our side right now to drive it.

@bowei @dchen1107

**Comment by klausenbusk** [comment]
> Do you know all the hostnames at pod startup time, or can they possibly be added later?

I currently have a `docker-entrypoint.sh` script like this: https://gist.github.com/klausenbusk/7426c125bea4bd378f9d39c3421ecce9 ,  which "extract" the hostnames from the nginx config at container startup, it also configure `nginx` to forward some request internally (we don't expose all domains externally).

**Comment by bowei** [comment]
@klausenbusk -- I'm not sure about your particular use case as the host name extraction logic seems to be quite complex (parsing of the nginx config).

The two things I do see that are useful:

* Ability for a ConfigMap to be written out as a single file into the container instead of injecting it as a directory of files. This would solve a lot of problems where a piece of the container configuration needs to be trivially changed. I'm fairly certain this is already file, I can't seem to find the issue.
* Inheritance of host entries from the outer node.

**Comment by rickypai** [comment]
I think the use-case beyond `externalName` service is if the hosts need to be loopback or needs to be configured per pod.

I tried to understand how `/etc/hosts` is controlled by kubelet, and it seems like this feature would not be hard to implement. I'm willing to spend some time on this.

in terms of implementation:

from my reading, host mount is done by `makeHostsMount` inside `kubelet_pods.go`, and the content of the hosts file is controlled by `ensureHostsFile` the methods that call them all have access to the pod object.

it seems like we can add a field to PodSpec (can be done as an Pod-level alpha annotation to start):

```yaml
etcHosts:
  - "127.0.0.1 local1.service"
  - "127.0.0.1 local2.service"
  - "127.0.0.1 local3.service"
```

or if we want something more explicit:
```yaml
etcHosts:
- hostname: local1.service
  ip: 127.0.0.1
- hostname: local2.service
  ip: 127.0.0.1
- hostname: local3.service
  ip: 127.0.0.1
```

that can be read into `makeHostsMount` and `ensureHostsFile`, which then mounts as `/etc/hosts` to the Pod.

**Comment by rickypai** [comment]
Let me know if ^ makes sense. If so, I can make a formal proposal in https://github.com/kubernetes/features/#when-to-create-a-new-feature-issue or just a PR, whichever is appropriate.

@thockin

**Comment by thockin** [comment]
I don't think this warrants a proposal or feature.  I would argue for the more expliciti form of the API, but hostnames has to be plural, and IP has to be the mergeKey.

@dchen1107 or @yujuhong - any objections?  Consider from a CRI point of view?

**Comment by chrw** [comment]
For me, this solves my problems. http://blog.kubernetes.io/2017/04/configuring-private-dns-zones-upstream-nameservers-kubernetes.html

**Comment by rickypai** [comment]
so the struct would be something like `map[net.IP][]string` where the keys are IP addresses, and strings are hostnames.

I presume this field would live under PodSpec. is `etcHosts` the name we want to surface? `additionalEtcHosts`?

the content would be:

```yaml
etcHosts:
- hostnames:
  - local1.service
  - local2.service
  ip: 127.0.0.1
- hostnames:
  - local3.service
  ip: 127.0.0.1
- hostnames:
  - remote4.service
  ip: 123.45.67.89
```

which after some merging would look like: (the go struct represented in yaml)

```yaml
127.0.0.1:
  - local1.service
  - local2.service
  - local3.service
123.45.67.89:
  - remote4.service
```

and the `/etc/hosts` output could either look like:

```
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
172.26.24.135	pod-name

# Additional Pod-specified hosts
127.0.0.1 local1.service local2.service local3.service
123.45.67.89 remote4.service
```

or

```
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
172.26.24.135	pod-name

# Additional Pod-specified hosts
127.0.0.1 local1.service
127.0.0.1 local2.service
127.0.0.1 local3.service
123.45.67.89 remote4.service
```

I think the latter is better since it's one line per entry, and seems to follow existing convention in `ensureHostsFile`.

**Comment by klausenbusk** [comment]
> Let me know if ^ makes sense.

Your proposal can definitely work for my use-case, although I would love if I could configure it from a init container, but this could work. Keep up the good work :)

**Comment by thockin** [comment]
I wouldn't try to massage it into a map, just:

```
type HostMapping struct {
  IP string
  Names []string
}
```


On Tue, Apr 11, 2017 at 12:59 AM, Kristian Klausen <notifications@github.com

**Comment by rickypai** [comment]
So you'd be passing in `[]HostMapping` into `ensureHostsFile`. That makes sense.

This might be a stretch, but what about different types of IPs that might not be present at the time the configuration is written? like for example the host's IP, pod's IP, or even some service IP.

**Comment by yujuhong** [comment]
> I don't think this warrants a proposal or feature. I would argue for the more expliciti form of the API, but hostnames has to be plural, and IP has to be the mergeKey.
> 
> @dchen1107 or @yujuhong - any objections? Consider from a CRI point of view?

This is currently handled completely by kubelet, so it wouldn't be an issue for CRI. 
kubelet doesn't mount `/etc/hosts` if the pod is using the host network, so this would either need to be changed, or validation should reject the pod if this is not allowed. 

> This might be a stretch, but what about different types of IPs that might not be present at the time the configuration is written? like for example the host's IP, pod's IP, or even some service IP.

If you need to dynamically change the file after the container starts, I think @bowei's suggestion of trying to make ConfigMap work would be better.

**Comment by rickypai** [comment]
I think validation to reject the option if the pod is using the host network makes sense.

`ConfigMap` is still a static file though. And if you inject a file that replaces `/etc/hosts`, what are you going to do with existing dynamic hostnames that are added by kubelet? https://github.com/kubernetes/kubernetes/blob/2899f47bc86695ac8093c66cef2cc02d55c6a23d/pkg/kubelet/kubelet_pods.go#L221-L225

**Comment by dchen1107** [comment]
I don't have any concern from CRI perspective, and the proposal look fine to me from the high level. 

>what about different types of IPs that might not be present at the time the configuration is written? like for example the host's IP, pod's IP, or even some service IP.

 But can I request not stretching the feature to support dynamic changes? Pod can be deleted, and re-created, thus the pod's IP might be changed. Currently we only allow container image being updated in PodSpec. Unless we allow updating the new field, let's call it etcHost for now, in PodSpec, it won't work. Even we allow that field being updated, I think that is overkill.

**Comment by rickypai** [comment]
the field in PodSpec won't be dynamic. I imagine something like this:

```golang
type HostMapping struct {
  IP IPSource
  Names []string
}

type IPSource {
  Type IPSourceType
  IPString string
}

type IPSourceType string

const(
  IPSourceTypeStatic = "Static"
  IPSourceTypePodIP = "PodIP"
)
```


validation ensures that `IPString` is only present if type is `Static`.

then IP is gathered at Pod creation time. In kubelet's `ensureHostsFile`:

```golang
func hostMappingIP(podIP, hostMapping) string {
    switch(hostMapping.Type) {
    case IPSourceTypeStatic:
      return hostMapping.IPString
    case IPSourceTypePodIP:
      return podIP
    }
}

func ensureHostsFile(fileName, hostIP, hostName, hostDomainName string, hostMappings []HostMapping) error {
  // omitted

  for _, hostMapping := range hostMappings {
    ip := hostMappingIP(hostIP, hostMapping)
    for _, hostname := hostMapping.Names {
      buffer.WriteString(
        fmt.Sprintf("%s\t%s\n", ip, hostname)
      )
    }
  }
}
```

**Comment by thockin** [comment]
Why do you need pod IP?  Why not use 127.0.0.1 ?

**Comment by rickypai** [comment]
The use-case that i'm more interested in is support for nodeIP, but I'm using podIP as an example because it's easier to illustrate with current code. But yes I agree with you that pod IP might not make sense since you have access to localhost already.

**Comment by rickypai** [comment]
sorry for the scope-creep. I'm just afraid using IP as a string field makes it hard to add support for other IP sources should that ever be an option.

but it's probably premature right now. for now, I'll just proceed with:
```golang
type PodSpec struct {
  // omitted
  HostMappings []HostMapping
}

type HostMapping struct {
  IP IPSource
  Names []string
}

type IPSource {
  Type IPSourceType
  IPString string
}

type IPSourceType string

const(
  IPSourceTypeStatic = "Static"
)
```

**Comment by thockin** [comment]
Given that we have a way to get node IP through downward API, why do we
need that here?

**Comment by rickypai** [comment]
Ideally, if the applications running inside the containers have flexible ways to configure dependent hostnames like through environment variables, then downward API would be sufficient. We can probably extend the argument that the whole support for `/etc/hosts` is moot if applications supported flexible injection of dependent hostnames.

The problem is many applications don't provide this level of flexibility. Hostnames are often hard-coded inside config files and the client libraries themselves.

Outside of Kubernetes, I might use a script to manage `/etc/hosts` and expect nothing else to change the file; while it is possible that I use an init container to do the same modification to `/etc/hosts`, since the mounting of `/etc/hosts` happens whenever a container is restarted, I risk the file being changed and my application not being able to connect to its dependent services.

This creates much headache migrating applications from a more lenient environment to Kubernetes, which is what we've been facing. I think support `/etc/hosts` is the right direction and is why I'm willing to commit time to make it happen.

**Comment by thockin** [comment]
We have another issue open for "node-local Services" which sounds like what
you want.  I am not a big fan of the expansion of host mappings like this.
I'd rather go all the way and give nodes a static link-local address or
else solve node-local services.

@bowei

**Comment by rickypai** [comment]
Thanks for all the feedback @thockin.

I'm well aware of node-local services, but it seems like progress on the proposal https://github.com/kubernetes/kubernetes/pull/28637 is stalled. I believe node-local services would be the proper way to address the use case I described, especially with the "locality" concept you described in https://github.com/kubernetes/kubernetes/pull/28637/files#r94002246 that can be expanded beyond the node.

However, in lieu of node-local services, `/etc/hosts` with references to the node IP might be a quick way to address the use case. Other tickets describing the need for node-level sidecars also proposed either using node-local services or `/etc/hosts`: https://github.com/kubernetes/kubernetes/issues/25961 https://github.com/kubernetes/kubernetes/issues/15169

I also understand this complicates the interface a little bit more, but it would really benefit cluster operators.

If you still think this is inappropriate, then I can proceed with this interface next week:

```golang
type PodSpec struct {
  // omitted
  HostMappings []HostMapping
}

type HostMapping struct {
  net.IP
  Names []string
}
```

**Comment by kargakis** [comment]
I don't have a strong opinion on this topic but it seems that it should be addressed as part of https://github.com/kubernetes/kubernetes/pull/28637. @therc what is the status of the proposal?

**Comment by yujuhong** [comment]
> However, in lieu of node-local services, /etc/hosts with references to the node IP might be a quick way to address the use case. Other tickets describing the need for node-level sidecars also proposed either using node-local services or /etc/hosts: #25961 #15169

I am not familiar with the node-local services and its progress, but if this can satisfy the use cases, I'd suggest that not adding new fields to the pod API for a quick workaround.

**Comment by rickypai** [comment]
I feel the original proposal got digressed due to the my zealous talk of node IP support. Allow me to clarify:

`/etc/hosts` serves several use cases:
1. overriding external hostname with a specific IP. i.e. if I want to say mock out an external hostname like `foo.com`
2. overriding a hostname with localhost. i.e. if I want to override `foo` to point to `127.0.0.1`
3. if we allow dynamic injection of nodeIPs, it can be an easy way for pods to talk to nodes in absence of node-local services.

only the third use-case is relevant to node-local services.

**Comment by thockin** [comment]
I understand the third case, but I'd like to consider other options to
solve that, first.  I think the rest is uncontentious.

**Comment by rickypai** [comment]
Thanks. I'll get the changes up this week. There'll likely be three changes:

1. add tests for existing hosts file content (there's no tests currently) #44572 
2. API change for `HostMappings` on `PodSpec`
3. logic to use `HostMappings` in `ensureHostsFile`

Is there any possibility to cherry-pick those back in 1.6? Or would this have to wait for 1.7?

**Comment by yujuhong** [comment]
> Is there any possibility to cherry-pick those back in 1.6? Or would this have to wait for 1.7?

AFAIK, we don't cherrypick features.

**Comment by rickypai** [comment]
https://github.com/kubernetes/kubernetes/pull/44641 has been created for the API change

**Comment by yujuhong** [comment]
> I understand the third case, but I'd like to consider other options to
> solve that, first.  I think the rest is uncontentious.

@thockin, just to clarify, are you in favor of adding HostMappings to the API?

**Comment by thockin** [comment]
I am neutral on it.  It's come up often enough that i believe the problem
is real.  The API doesn't seem harmful to me, what do you think?  You're
the guardian of CRI...

**Comment by thockin** [comment]
Also the name is terrible - help?  HostAliases?  DNSAliases?

**Comment by rickypai** [comment]
I'm up for `HostAliases`. `DNSAliases` might accidentally imply that it's actually interfacing with kube-dns.

**Comment by yujuhong** [comment]
I am neutral but just wanted to make sure there are no obvious, alternative ways to achieve this. BTW, the proposed solution changes the k8s API, but not CRI :)

On the other hand, if we support this on the k8s API level, we should discourage users from modifying this file directly. For example, #44473 reported a bug where users modify `/etc/hosts` in the init containers, and later found that kubelet overwrites it.

**Comment by thockin** [comment]
We should definitely discourage modifying that, but we should perhaps
respect it if a user provided a volume mount.

Thoughts on name?

**Comment by yujuhong** [comment]
I am terrible at naming...
I agree that having DNS in the name can be misleading. `HostAliases` sounds ok. 
`HostnameIPMapping` might be more direct?

**Comment by thockin** [comment]
I'd go for brevity when possible.  HostAliases ?

**Comment by rickypai** [comment]
I'm updating the PR to use `HostAliases`. thanks for the suggestion

**Comment by rickypai** [comment]
Just posted the last PR to enable this feature: https://github.com/kubernetes/kubernetes/pull/45148

**Comment by yujuhong** [comment]
@rickypai could you add a node e2e test for this feature?

**Comment by thockin** [comment]
Do we need e2e?  Every e2e is a liability, and slows down test runs - e2e
is needed if we can't cover in unit or integration.

**Comment by yujuhong** [comment]
Unit tests are great to ensure the individual functions work correctly, but so far it's not sufficient to prevent regression in our codebase from my experiences. Since this is a new addition/feature to the API, I'd prefer having a corresponding node e2e test.

Integration test can be sufficient, but I've not had any pleasant experience debugging integration tests. Maybe that has changed already?

**Comment by thockin** [comment]
no, integrtaion tests are under-serviced tech-wise.

**Comment by yujuhong** [comment]
> no, integrtaion tests are under-serviced tech-wise.

@thockin does a simple node e2e test sound good to you?

**Comment by thockin** [comment]
SGTM

**Comment by hongchaodeng** [comment]
I saw that the HostAlias's comment:
```
This is only valid for non-hostNetwork pods.
```
I'm wondering why it couldn't work to hostNetwork pods? And how does a hostNework pod initialize its /etc/hosts file?

**Comment by thockin** [comment]
@rickypai Are we still missing a test for this?  I'd hate to have to kick it out of the 1.7 release for lack of tests..

**Comment by rickypai** [comment]
yes we are still missing a test. what's the deadline for 1.7 release? sorry i was on PTO and dropped the ball

**Comment by rickypai** [comment]
@hongchaodeng hostNetwork pods uses the host's `/etc/hosts` file, while only non-hostNetwork pods have `/etc/hosts` managed by kubelet

**Comment by yujuhong** [comment]
> @hongchaodeng hostNetwork pods uses the host's /etc/hosts file, while only non-hostNetwork pods have /etc/hosts managed by kubelet. because kubelet does not manage the file when using hostNetwork, kubelet can't write additional entries from hostAliases.

Just chatted @hongchaodeng on slack, for containers using the host network, docker actually makes a copy of "/etc/hosts" on the host for each of them. I think kubelet can potentially support HostAliases for hostnetwork pods by copying and mounting the file. Not sure if there are be other concerns though.

**Comment by rickypai** [comment]
@yujuhong if you make the change to make kublet copy and manage `/etc/hosts` for hostNetwork  pods, I can make the change for HostAliases.

one concern: currently, the `/etc/hosts` logic includes [writing the hostnames of Pod](https://github.com/kubernetes/kubernetes/blob/99a8f7c3031fc288ac2229f9d3e94bceaa0529fb/pkg/kubelet/kubelet_pods.go#L232-L236), including [custom hostnames and subdomains](https://github.com/kubernetes/kubernetes/blob/99a8f7c3031fc288ac2229f9d3e94bceaa0529fb/pkg/kubelet/kubelet_pods.go#L264-L292) from `PodSpec.Hostname` and `PodSpec.Subdomain`. Should this be allowed? if not, there should probably be validation disallowing those field when hostNetwork is used. there currently isn't any unless I read the code wrong.

**Comment by rickypai** [comment]
added node e2e test: #46385

**Comment by thockin** [comment]
THANKS!

**Comment by hongchaodeng** [comment]
> I think kubelet can potentially support HostAliases for hostNetwork pods by copying and mounting the file.

That would be a great feature!

Currently we have pods using hostNetwork and using init containers to restore some host mappings -- basically `cat xxx >> /etc/hosts` . With HostAliases feature it would be fantastic fit!

**Comment by hongchaodeng** [comment]
>  including custom hostnames and subdomains from PodSpec.Hostname and PodSpec.Subdomain. Should this be allowed? if not, there should probably be validation disallowing those field when hostNetwork is used.

We are using `PodSpec.Hostname` and `PodSpec.Subdomain` for hostNetwork pods.

**Comment by hongchaodeng** [comment]
> hostNetwork pods uses the host's /etc/hosts file, while only non-hostNetwork pods have /etc/hosts managed by kubelet. because kubelet does not manage the file when using hostNetwork, kubelet can't write additional entries from hostAliases.

@rickypai 
This is something I don't understand in the code:
https://github.com/kubernetes/kubernetes/blob/99a8f7c3031fc288ac2229f9d3e94bceaa0529fb/pkg/kubelet/kubelet_pods.go#L117

It seems that it is still mounting "/etc/hosts" for hostnetwork pods if `pod.Spec.SecurityContext == nil`. Does that mean kubelet is still managing it?

**Comment by hongchaodeng** [comment]
One of our current assumptions is that kubelet will mount a shared /etc/hosts (which is not node's) for all containers within a pod in hostNetwork mode. Which seems to be the codepath in the code linked above. Is this holding true?

**Comment by yujuhong** [comment]
@hongchaodeng I checked the git history and that was just an artifact caused by switching from internal to v1 API objects.

The original code is:
```
mountEtcHostsFile := (pod.Spec.SecurityContext == nil || !pod.Spec.SecurityContext.HostNetwork) && len(pod.Status.PodIP) > 0
```
In the internal API, `HostNetwork` is a field in `Pod.Spec.SecurityContext`, so you can see why `SecurityContext` had to be non-nil.
In the v1 API, `HostNetwork` is a field in the pod spec: `Pod.Spec.HostNetwork`. When switching all code to use the versioned (v1) objects, this got lost in translation.

I believe the apiserver sets the default pod SecurityContext, so it should never be nil.
I'll send a PR to remove the redundant check.

**Comment by hongchaodeng** [comment]
@yujuhong 
Thanks for looking into that.

Currently even with hostNetwork pods, it will have mounts for `/etc/hosts`. Checking within the pod:
```
$ docker exec -ti xxxx sh
/ # mount
/dev/sda1 on /etc/resolv.conf type ext4 (rw,nosuid,nodev,relatime,commit=30,data=ordered)
/dev/sda1 on /etc/hostname type ext4 (rw,nosuid,nodev,relatime,commit=30,data=ordered)
/dev/sda1 on /etc/hosts type ext4 (rw,nosuid,nodev,relatime,commit=30,data=ordered)
```
If the check is removed, what would happen on the shared mount of /etc/hosts ?
My concern and question is about the guarantee here. Is there still a copy of `/etc/hosts` which is shared and mounted for all containers within a pod?

**Comment by yujuhong** [comment]
> Currently even with hostNetwork pods, it will have mounts for /etc/hosts. Checking within the pod:

Removing the check itself won't affect anything since securitycontext should always be non-nil.

That mount for hostnetowrk pods was added by docker (not by kubelet) so it should be one per container, and not shared by containers within a pod. I didn't try it myself, but it should be easy to verify.

**Comment by hongchaodeng** [comment]
> That mount for hostnetowrk pods was added by docker (not by kubelet) so it should be one per container, and not shared by containers within a pod.

Tried and verified that `/etc/hosts` was shared between containers within a pod for k8s 1.6.4 .

**Comment by hongchaodeng** [comment]
Also verified that modifying `/etc/hosts` for a hostNetwork pod did not change the file on the node.

**Comment by yujuhong** [comment]
> Tried and verified that /etc/hosts was shared between containers within a pod for k8s 1.6.4 .

Then docker did the right thing and use the same file for containers sharing the same network namespace :-)

**Comment by hongchaodeng** [comment]
> sharing the same network namespace :-)

That makes sense.

**Comment by hongchaodeng** [comment]
@rickypai 
Will HostAlias support for HostNetwork pod happen in 1.7 ?

**Comment by rickypai** [comment]
I'm trying to get https://github.com/kubernetes/kubernetes/pull/46385 in so it can make the 1.7 release deadline. help reviewing the PR would be great.

**Comment by rickypai** [comment]
> Also verified that modifying /etc/hosts for a hostNetwork pod did not change the file on the node.

in a multi-container hostNetwork pod, what happens when you change the file, then restart one of the containers? in non-hostNetwork pod, it would revert the changes to `/etc/hosts`

**Comment by rickypai** [comment]
anyways, i'm also in favor of kubelet managing the file even for hostNetwork pods. that way, we can use features like hostAliases, and also then we don't depend on the container runtime to dictate the behavior. it's not clear whether running rktnetes with hostNetwork pod would yield the same result

**Comment by thockin** [comment]
Is this a dup of https://github.com/kubernetes/kubernetes/issues/39792 ?  How are they different?

**Comment by rickypai** [comment]
HostAlias is useful to provide local overrides for a particular Pod, but it seems like #39792 would want the alternative DNS name of a service accessible for all Pods.

**Comment by rickypai** [comment]
re: documentation, i'm thinking either adding notes about HostAliases in https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/ or as a separate page under "Services, Load Balancing, and Networking"

**Comment by hongchaodeng** [comment]
@rickypai 
Is there any issue created for supporting HostAlias in hostnetwork mode?

**Comment by rickypai** [comment]
I can write up what I think will be needed to support HostAlias in hostNetwork pods

**Comment by rickypai** [comment]
This is now in 1.7: https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/

**Comment by rickypai** [comment]
filed issues to follow up with HostNetwork support:

https://github.com/kubernetes/kubernetes/issues/48397
https://github.com/kubernetes/kubernetes/issues/48398

**Comment by luispabon** [comment]
Thank you for this feature.

Our use case is different. On an nginx/php-fpm set up where our local dev is via docker-compose yet we're deploying into kubernetes, we can use the exact same nginx config on both environments.

**Comment by rickypai** [comment]
@luispabon the discrepancy between dev/prod would probably cause problems beyond just difference in networking setup. have you considered using [minikube](https://kubernetes.io/docs/getting-started-guides/minikube/) to have parity between the two environments?

**Comment by luispabon** [comment]
We have, and found it way too cumbersome for local development. 

In contrast, docker-compose is a lot easier, more concise, and we have yet to find any environment-y issues caused by difference between these two, except for this one issue we fortunately have a workaround for (HOSTALIASES).

We use the exact same base container images for development as well as builds. From the point of view of the services themselves, there's no difference at all being run on one environment or the other - they talk to each other via HTTP or queues.

**Comment by rickypai** [comment]
that's unfortunate. I guess minikube does have overhead since you have to run it inside a VM on your mac machines.

But since all components are written in go and cross-compiled in darwin, I wonder if you could setup your own etcd (homebrew has this), then your own kubelet. Docker you can run Docker on Mac, then just have kubelet talk to the local docker socket.

This sounds like it would work with lower resource overhead than minikube since you don't to run in a VM.

Either way, I'm glad HostAlias is able to address your problem. I just wish you didn't have to deal with this discrepancy in the first place.
