### ISSUE TITLE
kube-apiserver --storage-backend defaults to etcd3  and hangs if connecting to etcd2 cluster

### ISSUE THREAD

**Issue by ozdanborne** [kubernetes/kubernetes#43634]
I just spent a lot of time debugging this so I figured I'd raise, if anything just to help the next guy googling why his upgrade from k8s-1.5 to k8s-1.6 isn't working. But k8s maintainers feel free to close this if there's no action needed here.

It looks like kube-apiserver for k8s 1.6 now defaults to `--storage-backend=etcd3`. When in this mode, kube-apiserver hangs on its requests to an _etcdv2_ server and doesn't provide much information on the nature of the issue. I saw the following kube-apiserver logs:
```
9462 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:70: Failed to list *api.Secret: Get http://localhost:8080/api/v1/secrets?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
```

```
k8s-master kube-apiserver[9462]: E0324 19:05:29.593771    9462 storage_rbac.go:140] unable to initialize clusterroles: the server cannot complete the requested operation at this time, try again later (get clusterroles.rbac.authorization.k8s.io)
```

```
storage_extensions.go:127] third party resource sync failed: the server cannot complete the requested operation at this time, try again later (get thirdpartyresources.extensions)
reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:70: Failed to list *api.Secret: the server cannot complete the requested operation at this time, try again later (get secrets)
9462 storage_rbac.go:140] unable to initialize clusterroles: the server cannot complete the requested operation at this time, try again later (get clusterroles.rbac.authorization.k8s.io)
```

`kubectl` requests simply hung, even though the apiserver was responding:
```
 curl localhost:8080/version
{
  "major": "1",
  "minor": "6+",
  "gitVersion": "v1.6.0-beta.4",
  "gitCommit": "b202120be3a97e5f8a5e20da51d0b6f5a1eebd31",
  "gitTreeState": "clean",
  "buildDate": "2017-03-17T17:42:22Z",
  "goVersion": "go1.7.5",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

and there was no indication of any issues in the etcd logs.

Manually setting to `--storage-backend=etcd2` resolved my issue.

**Comment by djosborne** [comment]
Note this was with coreos which by default ships with etcdv2 so all CoreOs users will now need to specify this flag.

**Comment by bcwaldon** [comment]
This bit me, too. It would help if the error messages emitted in the logs were more specific, as they currently make think there is a connectivity issue between the apiserver and etcd.

**Comment by matalo33** [comment]
GAHH THIS!!!! 

Please don't let kube-apiserver silently fail if it tries to speak etcd3 to an etcd2 cluster. I only discovered this was the cause of my issues by accident because another ticket got me thinking this might be the reason.

https://github.com/kubernetes/kubernetes/issues/12089

**Comment by tsn77130** [comment]
same problem for me, thanks for your opened issue, indeed apiserver message isn't very explicit

**Comment by guillelb** [comment]
Thank you a lot!  This was my problem too.

**Comment by 4a4c** [comment]
thanks for posting; was having the same issue on a cluster that I upgraded to 1.6.x on but had not rev'd etcd to v3 yet.

**Comment by pranabsharma** [comment]
I too had the same issue with v 1.6, after setting --storage-backend=etcd2 as written above by @ozdanborne resolved the issue.

**Comment by maulik887** [comment]
Thank you, same thing happened with me. This information solved it.

**Comment by billmilligan** [comment]
I hate to ask the stupid question, but adding"--storage-backend=etcd2" where exactly?  This is a problem for me just trying to run kubeadm init, and I don't see any option like that being accepted by kubeadm.

**Comment by xiangpengzhao** [comment]
`storage-backend` is one of the flags of kube-apiserver.
```
kube-apiserver -h
--storage-backend string    The storage backend for persistence. Options: 'etcd3' (default), 'etcd2'.
```

**Comment by xiangpengzhao** [comment]
Oh, sorry. I misread. Did you mean where to set `--storage-backend=etcd2` for kubeadm?

**Comment by billmilligan** [comment]
yes, that's exactly what I need ... kubeadm kicks off apiserver, and does so with etc3 settings.  I need to flip that somehow.

**Comment by billmilligan** [comment]
... at least, that's my current theory for why apiserver dies a minute or two after starting

**Comment by floriankammermann** [comment]
Couldn't find the issue with my logoutput. Got to the issue, after figuring out myself, over the API doc what the problem is.

Just for completion my failure log for this issue:

```
I0807 08:53:13.051248   26771 naming_controller.go:284] Starting NamingConditionController
E0807 08:53:16.206535   26771 status.go:62] apiserver received an error that is not an metav1.Status: rpc error: code = 13 desc = transport is closing
I0807 08:53:16.207188   26771 wrap.go:42] POST /api/v1/namespaces: (284.007903ms) 500
goroutine 84798 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc45100aaf0, 0x1f4)
```
```
logging error output: "k8s\x00\n\f\n\x02v1\x12\x06Status\x12F\n\x04\n\x00\x12\x00\x12\aFailure\x1a0rpc error: code = 13 desc = transport is closing\"\x000\xf4\x03\x1a\x00\"\x00"
 [[kube-apiserver/v1.7.2 (linux/amd64) kubernetes/922a86c] 127.0.0.1:54322]
E0807 08:53:16.362784   26771 client_ca_hook.go:78] rpc error: code = 13 desc = transport is closing
E0807 08:53:16.717060   26771 status.go:62] apiserver received an error that is not an metav1.Status: rpc error: code = 13 desc = transport: write tcp 192.168.2.12:47562->192.168.3.2:2379: write: connection reset by peer
I0807 08:53:16.717378   26771 wrap.go:42] POST /api/v1/namespaces: (800.375µs) 500
```

**Comment by matalo33** [comment]
/remove-lifecycle stale

I'd like a maintainer to accept or close this if possible, instead of just letting it go stale

**Comment by dims** [comment]
if we ever want to add a ping/status test for etcd3 ... http://paste.openstack.org/show/720249/
