### ISSUE TITLE
Use SCSI reservations for exclusive iSCSI access

### ISSUE THREAD

**Issue by fabiand** [kubernetes/kubernetes#43639]
Does it make sense to use SCSI reservations to prevent concurrent access to the same iSCSI target?

This works around the fact that it's currently a duty of the plugin or provider to enforce the access patterns.

**Comment by rootfs** [comment]
It is possible to do it but I need to know if there is any mechanism to reliably read reservation status so that no  deadlock will occur if the node that holds the reservation crashes before releasing the reservation.

**Comment by fabiand** [comment]
I guess this could be one piece of #12338 - adding more guarantees to iSCSI volumes.

The interesting bit here is that it would also cover the block storage aspects.

**Comment by rootfs** [comment]
moving discussion to #12338 as @fabiand suggested.
/close
