### ISSUE TITLE
Make kubectl.go images faster / squashed .

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#43631]
**Kubernetes version** (use `kubectl version`):

master

**What happened**:

Pulling the redis image takes a while, like 30 seconds in GCE.    This might be leading to periodic timeouts in tests like `--ginkgo.focus="should check if kubectl describe print"`.  

```
gcr.io/google_containers/redis               e2e                 e5e67996c442        2 years ago         418.9 MB
```

**What you expected to happen**:

Tests shouldn't depend on large images that take a potentially long time to pull.

** proposed fix **

to reduce flakiness we can increase the replica count on this test to 2 or make the redis image we use smaller (or not use redis at all and just use a simpler smaller image)

**Comment by jayunit100** [comment]
cc @kubernetes/sig-testing-misc @kubernetes/sig-testing-bugs  (considering this as a bug since we shouldnt need a 500MG image just to test kubectl :))

**Comment by rmmh** [comment]
This should be as simple as changing the current `test/images/pets/redis/Dockerfile` to use alpine and install redis, instead of basing it off debian, installing gcc, and compiling redis from source :-)

The image should be ~10MB.
