### ISSUE TITLE
[Storage] Add support for persistent local storage

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#43640]
Based on kubernetes/community#306

This issue is meant to track work items and help collaboration between the community on adding support for persistent local storage.

Note: Priority of these features can change based on the number of collaborators.

Alpha user guide is [here](https://github.com/kubernetes-incubator/external-storage/blob/master/local-volume/README.md)

Individual task tracking is available in the sig storage planning [spreadsheet](https://docs.google.com/spreadsheets/d/1t4z5DYKjX2ZDlkTpCnp18icRAQqOE85C1T1r2gqJVck)

**Comment by msau42** [comment]
cc @kubernetes/sig-storage-feature-requests @kubernetes/sig-scheduling-feature-requests @kubernetes/sig-apps-feature-requests

**Comment by jeffvance** [comment]
@msau42 I will help with the e2e tests.

**Comment by saad-ali** [comment]
Moving to 1.8. @msau42 could you update the status on the original comment.

**Comment by sky-big** [comment]
Hi, I concern about V1.8(Prototype and design scheduler and PVC binding integration)feature,So I want to ask What time the kubernetes 1.8 publish?-_-

**Comment by msau42** [comment]
I updated the list with the 1.8 plan.

**Comment by msau42** [comment]
We started tracking individual task items in the sig storage planning [spreadsheet](https://docs.google.com/spreadsheets/d/1t4z5DYKjX2ZDlkTpCnp18icRAQqOE85C1T1r2gqJVck/).

I'm closing this tracker issue as it's difficult to keep both of them in sync.  We'll open up issues for each PR in the future releases.
