### ISSUE TITLE
[Federation] Service Controller DNS handling is broken

### ISSUE THREAD

**Issue by csbell** [kubernetes/kubernetes#43646]
This has surfaced in Ingress and Service e2e tests that manipulate DNS entries. The service controller queries the managed dns entry, thinks that the CNAME doesn't exist and adds a new one. However, clouddns says (through a 409) that the entry already exists. Error message aside, the control flow within the service controller's endpoint_helper prevents a service from being deleted.

It's unclear at this point whether there's a race condition. I doubt it given the amount of logging that happens showing that there is no concurrent CNAME entry being created.

cc @shashidharatd Have you seen this in your refactoring?

```
I0324 13:26:29.743] I0324 20:20:47.452653       1 dns.go:191] No recordsets found for DNS name "federated-service.e2e-tests-federated-service-r4281.e2e-federation.svc.us-central1-b.us-central1.test-f8n.k8s.io.".  Need to add either A records (if we have healthy endpoints), or a CNAME record to "federated-service.e2e-tests-federated-service-r4281.e2e-federation.svc.us-central1.test-f8n.k8s.io."
I0324 13:26:29.743] I0324 20:20:47.452694       1 dns.go:193] There are no healthy endpoint addresses at level "federated-service.e2e-tests-federated-service-r4281.e2e-federation.svc.us-central1-b.us-central1.test-f8n.k8s.io.", so CNAME to "federated-service.e2e-tests-federated-service-r4281.e2e-federation.svc.us-central1.test-f8n.k8s.io.", if provided
I0324 13:26:29.743] I0324 20:20:47.452713       1 dns.go:195] Creating CNAME to "federated-service.e2e-tests-federated-service-r4281.e2e-federation.svc.us-central1.test-f8n.k8s.io." for "federated-service.e2e-tests-federated-service-r4281.e2e-federation.svc.us-central1-b.us-central1.test-f8n.k8s.io."
I0324 13:26:29.743] I0324 20:20:47.452735       1 dns.go:197] Adding recordset <(clouddns) "federated-service.e2e-tests-federated-service-r4281.e2e-federation.svc.us-central1-b.us-central1.test-f8n.k8s.io." type=CNAME rrdatas=["federated-service.e2e-tests-federated-service-r4281.e2e-federation.svc.us-central1.test-f8n.k8s.io."] ttl=180>
I0324 13:26:29.743] I0324 20:20:47.500162       1 endpoint_helper.go:182] Error ensuring DNS Records: googleapi: Error 409: The resource 'entity.change.additions[0]' named 'federated-service.e2e-tests-federated-service-r4281.e2e-federation.svc.us-central1-b.us-central1.test-f8n.k8s.io. (CNAME)' already exists, alreadyExists
```

**Comment by shashidharatd** [comment]
Hi @csbell, 
I used CoreDNS for most of my testing for service controller refactoring and i did not notice these errors.
my local test environment is slightly different than the CI environment. i would do more tests on this issue using CoreDNS and would confirm, if it is an issue also in coredns or just google-clouddns.

**Comment by quinton-hoole** [comment]
@csbell If you're not still working on this, please unassign yourself and we'll try to find someone else.  Thanks.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#125.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
