### ISSUE TITLE
Write an API conventions test

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#43658]
To catch as many violations of API conventions as we can automatically.

https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md

cc @kubernetes/sig-api-machinery-misc (hmm, no feature-requests team)

**Comment by oomichi** [comment]
How about adding checks for API conventions at https://github.com/kubernetes/kubernetes/blob/33584929ff2a5b7a86ec6bea00063932e4505c8b/staging/src/k8s.io/client-go/transport/round_trippers.go#L410 ?
At the place, we can access both API request and response and the violation check implementation is possible, I feel.

**Comment by bgrant0607** [comment]
@mbohlool Is there another issue for the API linter?

/remove-lifecycle stale

**Comment by mbohlool** [comment]
yes: https://github.com/kubernetes/kubernetes/issues/44005

I am closing this one as it is a duplicate.
