### ISSUE TITLE
Write a kubectl conventions test

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#43657]
To catch violations of as many conventions as we can automatically.

https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md

cc @kubernetes/sig-cli-feature-requests

**Comment by fabianofranz** [comment]
+1, we already have [a mechanism](https://github.com/kubernetes/kubernetes/blob/master/hack/verify-cli-conventions.sh) that runs on `make verify` intended to do that, but just [a couple things](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/sanity/cmd_sanity.go#L66-L94) are checked atm (sanity of long description and examples).

**Comment by kargakis** [comment]
We can create an interface that commands should implement.
```go
type KubectlCommand interface {
   Complete(f *cmdutil.Factory, cmd *cobra.Command, args []string, out io.Writer) error
   Validate() error
   Run() error
}
```
https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#command-implementation-conventions

**Comment by shiywang** [comment]
sounds good, @fabianofranz @kargakis is there anything I could help here ?

**Comment by adohe** [comment]
```
We can create an interface that commands should implement.
```
SGTM. And quite a long way to move towards this direction, but I really would like to step forward in the next phase.
