### ISSUE TITLE
1.6 upgrade script silently performs irreversible change to storage type

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#43669]
When running the ./cluster/gce/upgrade.sh script it silently will update the STORAGE_MEDIA_TYPE.  This change is irreversible.  Subsequently downgrading to 1.5.5 using the ./cluster/gce/upgrade.sh script will cause the apiserver to be unable to come back up. 

# Steps to reproduce
- Download kubernetes 1.5.5 tar, extract and cd into the directory
- run cluster/get-kube-binaries.sh
- run cluster/kube-up.sh
- Download the `v1.6.0-rc.1` release tar, extract, and cd into the directory
- run cluster/get-kube-binaries.sh
- **Note:** make sure the following env variables have not been explicitly set`TARGET_STORAGE, ETCD_IMAGE, TARGET_VERSION,STORAGE_MEDIA_TYPE` 
- run `./cluster/gce/upgrade.sh -M v1.6.0-rc.1`
- run  `./cluster/gce/upgrade.sh -N -o v1.6.0-rc.1` to upgrade the nodes
- run  `./cluster/gce/upgrade.sh -N -o v1.5.5` to downgrade the nodes
- run  `./cluster/gce/upgrade.sh -M v1.5.5` to downgrade the master
  - This is where the script just hung forever waiting for the master to come back up
  - sshing into the master and viewing the master logs showed that it was having trouble connecting to etcd
  - sshing into the master and viewing the etcd logs showed that it had some issues

**Comment by pwittrock** [comment]
cc @smarterclayton @justinsb @bgrant0607

**Comment by justinsb** [comment]
I put up a proposed "really backup this time" PR for the release notes here: https://github.com/kubernetes/features/pull/234

**Comment by ethernetdan** [comment]
I'm thinking we also add to the script a prompt about the breaking change and pointing to docs as well as a flag to override to prompt for CI to use.

**Comment by davidopp** [comment]
@wojtek-t

**Comment by ethernetdan** [comment]
Added #43681 to give a prompt before upgrading.

**Comment by liggitt** [comment]
fixed in release-1.6 branch by #43720
