### ISSUE TITLE
In-cluster config for kubectl cannot be disabled/overriden

### ISSUE THREAD

**Issue by jimmycuadra** [kubernetes/kubernetes#43662]
I have an app running in a pod that shells out to kubectl. A kubeconfig file with credentials for four different clusters is included in the pod. However, kubectl always detects that it's being run from inside a cluster and uses the pod's cluster's apiserver instead of the credentials I'm explicitly passing it. I've tried various things to disable this detection and make it use the configuration I'm supplying, but it always uses the in-cluster configuration settings, which results in not only submitting to the wrong cluster, but this error being returned for many resources being applied:

```
the namespace from the provided object "foo" does not match the namespace "bar". You must pass '--namespace=foo' to perform this operation.
```

where "foo" refers to the resource I'm trying to create with `kubectl apply` (the namespace of the resource is in the input file) and "bar" is the namespace of the pod shelling out to kubectl. Running the exact same command locally works, because kubectl is not overriding what I pass it with in-cluster configuration.

Specifically, the command being run is:

```
kubectl --kubeconfig /path/to/.kube/config --context my-context apply -f resources.yml
```

I can't find any documentation on how to disable in-cluster config. I looked through the code of the Go client to try to figure out how it's choosing to do this. I tried various things to disable it, including:

* Setting the `KUBERNETES_SERVICE_HOST` environment variable to an empty string, due to this: https://github.com/kubernetes/client-go/blob/49948ae0ca8eb31d632fbf346e25ee0eb6762d5b/tools/clientcmd/client_config.go#L505. But Kubernetes overrides my setting and fills in the environment variable like normal.
* Mounting an empty volume to /var/run/secrets/kubernetes.io/serviceaccount to try to prevent Kubernetes from mounting the service account files, but it mounts them anyway, overriding my explicit mount.
* Setting the `KUBECONFIG` environment variable to the path of the file I want it to use. It has no effect.

This is kubectl 1.5.x running in a Kubernetes 1.5 cluster. Notably, using kubectl 1.4.x does _not_ exhibit this behavior in the same Kubernetes 1.5 cluster. kubectl 1.4 works as expected.

**Comment by ravilr** [comment]
dup of https://github.com/kubernetes/kubernetes/issues/39897
cc @fabianofranz @pwittrock if this needs to be cherrypick'ed to 1.5.

**Comment by jimmycuadra** [comment]
Seems it was already suggested that the fix should be cherrypicked in [the original report](https://github.com/kubernetes/kubernetes/issues/38834#issuecomment-267709706). :{

**Comment by fabianofranz** [comment]
ptal @smarterclayton

**Comment by chrisleck** [comment]
This appears to still be broken in 1.6.0.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/commit/d1d20e5340d427b7a6a4c022c37f4cecb36ce52b#diff-47197a425491d7fcfa69115333533db9R140 falls through to the in-cluster-config namespace unless the mergedClientConfig.Namespace() indicates the namespace was overridden.

https://github.com/kubernetes/kubernetes/commit/ffa764d60bd4e7768401a25e95eb77a0d7c9ddc0#diff-c320a2254d827d227c3a3322f9b06c59R223 only indicates it was overridden if an explicit `--namespace` flag was passed. Specifying an explicit namespace in the current context does not count as overriding, apparently.

**Comment by liggitt** [comment]
The following all override the in-cluster config as expected on master:

--kubeconfig flag (server and credentials take effect, namespace does not)
$KUBECONFIG envvar (server and credentials take effect, namespace does not)
--server flag
--token flag
--namespace flag

The only issue I am seeing is overriding the in-cluster-config namespace from the namespace specified in a kubeconfig file via --kubeconfig or $KUBECONFIG

**Comment by chrisleck** [comment]
Yes - that matches what I'm seeing.  Specifying `--context` isn't enough.  I also have to specify `--namespace` in order for the override to work, which is a regression from 1.4.* behavior.

**Comment by jimmycuadra** [comment]
This is still broken as of 1.6.2 and has just become a big priority for my team, as it breaks our deployment automation. See my comment here: https://github.com/kubernetes/kubernetes/pull/44877#issuecomment-299584930
