### ISSUE TITLE
Updated kubelet to use client-go

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#43670]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
feature request

**Kubernetes version** (use `kubectl version`):
master branch

**What happened**:
According to discussion at https://github.com/kubernetes/client-go/issues/136  , we'd like to upgrade `kubelet` & `scheduler` to use client-go after lister, informer is ready.

/cc @caesarxuchao @deads2k

**Comment by k82cn** [comment]
@deads2k , not sure the progress of list/informer in client-go; I'd like to create PRs for this issue when they're ready :).

**Comment by ncdc** [comment]
@k82cn listers and informers should be ok in client-go master afaik. There may be one more update to master that's needed, but it's close if not already there.

**Comment by k82cn** [comment]
@ncdc , great; let me try to update kubelet accordingly :).

**Comment by krmayankk** [comment]
Couple questions:-
- is client-go generated off of objects and structs in kubernetes repo or is it the other way around ?
- When we say kubelet and other internal kubernetes components would also use client-go which sits outside of the repo, i get the feeling that kubernetes resource types and structs would live somewhere outside the kubernetes repo. Both client-go and kubernetes repo would depend on this external repo(of kubernetes resource types and objects) to make this work or at least this is how it should be designed. 
 How off am i in my understanding :-)
- what is clientset_generated ?

**Comment by deads2k** [comment]
client-go is a copy, paste, sed manipulation of files from the kubernetes repo.

There was a proposal to move the types and even a pull, but it didn't go anywhere.  https://github.com/kubernetes/kubernetes/issues/41629 and https://github.com/kubernetes/kubernetes/pull/41747.

I think the first iteration of splitting out the kubelet and scheduler would simply switch them to the client-go copy of the types.

**Comment by jcbsmpsn** [comment]
@k82cn Are you working on this? I'm interested in using the result.

**Comment by k82cn** [comment]
@jcbsmpsn , please go ahead; I separate this issue into two: one for kubelet and one for scheduler.

**Comment by k82cn** [comment]
xref #44188

**Comment by k82cn** [comment]
@jcbsmpsn , are you going to do this one?

**Comment by jcbsmpsn** [comment]
I started on this one a little while ago, but got hung up waiting for another change to go through so I can proceed. Taking a look at it again now.

**Comment by jcbsmpsn** [comment]
Have a bunch of changes in a branch but it's not compiling yet. Paused waiting for some migration changes from @caesarxuchao

**Comment by jcbsmpsn** [comment]
The necessary changes won't land in 1.7.

**Comment by jcbsmpsn** [comment]
In progress: https://github.com/kubernetes/kubernetes/pull/48231

**Comment by caesarxuchao** [comment]
closed by #48231
