### ISSUE TITLE
Possible to replace disk underlying a persistent volume claim if using Storage Class?

### ISSUE THREAD

**Issue by jiefugong** [kubernetes/kubernetes#43672]
**Is this a request for help?**
yes

I am currently working on a deployment that is using the StorageClass to specify the creation of GCE persistent disks. One feature we would like is to be able to replace a pod's underlying disk with a prior snapshot that might have been created of it (it seems that while this example is specific to GCE this would be common amongst most providers), but I am not sure if this is possible with a Storage Class for dynamic provisioning.

The approach I am thinking of taking right now includes deleting the PVC entirely, make a snapshot of the disk, delete the original, and make a new PVC to claim the disk -- would there be a better method than this?

**Comment by msau42** [comment]
@jingxu97 and @tsmetana are working on a snapshot feature.  Maybe this use case can fit in.

**Comment by jingxu97** [comment]
@jiefugong We are working on a snapshot proposal https://github.com/kubernetes-incubator/external-storage/pull/197
It allows user to create snapshot and manage snapshot API object through kubernetes. Then user can restore/create volume with PVC/PC from snapshot too.
Please let us know any feedback for the proposal.

**Comment by jingxu97** [comment]
@jiefugong We are currently working and testing on a restore volume from snapshot workflow. Please see the issue #59642 for more details. Thanks!
