### ISSUE TITLE
Node status not updating latest metadata for re-registration.

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#43678]
Is this a BUG REPORT or FEATURE REQUEST? (choose one):

BUG REPORT

Kubernetes version (use kubectl version):

master

Environment:

Any

What happened:

When using the kubelet's register-node option and restarting a kubelet, looks like the reconciliation is happening for only few annotations in case of re-registration:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status.go#L133

What you expected to happen:

We expect the node to have all the updated information. As an example, we  re-registered node with different taints and taints are not getting overwritten.

How to reproduce it (as minimally and precisely as possible):
Register the node twice, to see if the taint is getting updated.

./kubelet --api_servers=http://192.168.150.7:8080 --v=2 --enable_server --allow-privileged --register-node=true --register-with-taints=dec1=asdasasdas:NoSchedule
./kubelet --api_servers=http://192.168.150.7:8080 --v=2 --enable_server --allow-privileged --register-node=true --register-with-taints=dec=asdasasdas:NoSchedule

Refer #43332

**Comment by ravisantoshgudimetla** [comment]
cc @jayunit100

**Comment by ncdc** [comment]
@ravisantoshgudimetla this is how it's currently coded and I would not call it a bug. Once a node has registered, any registration-time metadata such as taints, labels, and so on are not updated.

See also: https://github.com/kubernetes/kubernetes/issues/28051, https://github.com/kubernetes/kubernetes/pull/29459.

**Comment by ravisantoshgudimetla** [comment]
@ncdc Thanks for the information. I will go through them.

**Comment by jayunit100** [comment]
Even if this is desired behavior, If register-with-taints is a no-op, at least the flag should be documented as such or an error message should come through?

**Comment by ncdc** [comment]
But you've already registered the node.

**Comment by jayunit100** [comment]
Sure, so if registration is not happening then the flag is being incorrectly included, so it's usage should be an error , not silent ignore.

**Comment by ncdc** [comment]
I would assume that typically you'd want to use the same flags to start the kubelet every time, in which case, I think this is appropriate, and I don't think an error is justified. A warning, maybe, but not an error.

I'm not sure it's worth the effort right now to "fix" this, as the plan is to move away from using flags for configuration (https://github.com/kubernetes/kubernetes/pull/29459).

**Comment by jayunit100** [comment]
So, if we agree it's worth a warning then we agree it's a low priority UX bug I think.

**Comment by jayunit100** [comment]
we should clear up the flags on this #43992

**Comment by resouer** [comment]
Should have been fixed in #46254
