### ISSUE TITLE
kube_up.sh download issue

### ISSUE THREAD

**Issue by TheFausap** [kubernetes/kubernetes#43686]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): latest from github

**Environment**:
- **Cloud provider or hardware configuration**: ubuntu local machines
- **OS** (e.g. from /etc/os-release): ubuntu 16.04
- **Kernel** (e.g. `uname -a`): Linux ubuntuL1 4.8.0-22-generic #24-Ubuntu SMP Sat Oct 8 09:15:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: 
- **Others**:

**What happened**:
running KUBERNETES_PROVIDER=ubuntu ./kube-up.sh from $HOME/kubernetes/cluster fails to download packages. 

**What you expected to happen**:
Downloading the needed packages.

**How to reproduce it** (as minimally and precisely as possible):
git clone <kubernets_repo>
export KUBE_VERSION=1.2.0
export FLANNEL_VERSION=0.5.0
export ETCD_VERSION=2.2.0
editing ubuntu/config-default.sh with the username and nodes where to install
KUBERNETES_PROVIDER=ubuntu ./kube-up.sh

**Anything else we need to know**:
those above are the instructions on the site https://kubernetes.io/docs/getting-started-guides/ubuntu/manual/

the typo is in the instructions, because KUBE_VERSION env variable needs a "v" before the version number.

**Comment by dolftax** [comment]
Just chiming in. Use `kops` - https://github.com/kubernetes/kops. kube-*.sh scripts are deprecated.

**Comment by castrojo** [comment]
/close

Closing, please use kops or another AWS tool as the kube- scripts have been deprecated since 1.6, thanks!
