### ISSUE TITLE
When using Azure provider, not able to expose a service using UDP protocol

### ISSUE THREAD

**Issue by vjrantal** [kubernetes/kubernetes#43683]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

Searched for `azure`, `udp` and `loadbalancer`.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

On my development machine, I have:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5", GitCommit:"894ff23729bbc0055907dd3a496afb725396adda", GitTreeState:"clean", BuildDate:"2017-03-22T00:23:49Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

On the master node:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:

Azure provider and a cluster created as instructed at https://docs.microsoft.com/en-us/azure/container-service/container-service-kubernetes-walkthrough#create-your-kubernetes-cluster.

- **OS** (e.g. from /etc/os-release):

Master running on `Ubuntu 16.04 LTS`.

- **Kernel** (e.g. `uname -a`):

```
azureuser@k8s-master-5F5DD1EA-0:~$ uname -a
Linux k8s-master-5F5DD1EA-0 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

- **Install tools**:

- **Others**:

**What happened**:

I was not able to expose a service via UDP protocol and LoadBalancer type using a command like:

```
kubectl expose deployments cf-helloworld-server --port=5683 --protocol=UDP --type=LoadBalancer
```

**What you expected to happen**:

After waiting long enough, I should be able to run `kubectl get services` and see the public IP address of the service. Also, I should be able to issue UDP traffic that reaches the code running in the container.

**How to reproduce it** (as minimally and precisely as possible):

* Create cluster as instructed at https://docs.microsoft.com/en-us/azure/container-service/container-service-kubernetes-walkthrough#create-your-kubernetes-cluster
* Run following commands:

```
$ kubectl run cf-helloworld-server --image vjrantal/cf-helloworld-server
$ kubectl expose deployments cf-helloworld-server --port=5683 --protocol=UDP --type=LoadBalancer
$ watch 'kubectl get services'
```

Observe that the public IP address is never appearing for this service.

**Anything else we need to know**:

Same steps results in an end-to-end working environment in Google Cloud Platform.

An end-to-end test can be performed as below and expectation is that a response is returned:

```
$ npm install -g coap-cli
$ coap get coap://<EXTERNAL-IP>:5683
```

**Comment by vjrantal** [comment]
As further details on the topic, when exposing the service over UDP in Google Cloud Platform, the load balancer is configured without a health probe:

<img width="578" alt="screen shot 2017-03-27 at 9 39 08" src="https://cloud.githubusercontent.com/assets/207474/24343882/6a8b5d1c-12d1-11e7-9356-2760b695baa0.png">

However, in Azure, I believe it is not possible to create load balancing rules without an associated health probe:

<img width="535" alt="screen shot 2017-03-27 at 9 37 49" src="https://cloud.githubusercontent.com/assets/207474/24343901/8b1ba5b4-12d1-11e7-8e00-7904aff582e3.png">

Also, UDP endpoints can't directly act as health probe endpoints since there are no acknowledgments.

After reading https://github.com/kubernetes/community/blob/master/contributors/design-proposals/external-lb-source-ip-preservation.md I was thinking at least these 3 options might be possible ways to configure the load balancer in Azure:

1. With UDP services, create a health probe that uses the TCP port of the `kube-proxy`.
2. Allow setting a TCP endpoint for the health probe during the expose command so that it is possible within the code running in the container to accept TCP sockets and that way indicate healthiness.
3. A variation to 2. is that no new parameters would be used during the expose, but it would be implicit (i.e., documented somewhere) that the container should accept TCP sockets in the same port used for the UDP traffic and the load balancer health probe would be configured with the same port as the UDP load balancing rule.

**Comment by brusMX** [comment]
cc @colemickens @khenidak
