### ISSUE TITLE
Lack of support for upgrade of HA master in upgrade.sh script.

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#43688]
Script `upgrade.sh` does not support upgrade of clusters with HA master setup.

**Comment by jszczepkowski** [comment]
CC @fgrzadkowski @wojtek-t

**Comment by jszczepkowski** [comment]
PR #43700 does not allow to run upgrade scripts on cluster with HA masters.

The upgrade scenario for HA clusters from 1.5 to 1.6 may be the following:
1. remove all master replicas but one,
2. run master upgrade,
3. add master replicas again.

**Comment by fgrzadkowski** [comment]
I haven't reviewed the PR yet, but the scenario you are proposing defeats the purpose of HA master! I think it's ok to say we do not support HA master upgrades yet, but we should document how this can be done manually and fix this properly later by adding support in upgrade.sh

**Comment by fgrzadkowski** [comment]
@wojtek-t @roberthbailey

**Comment by roberthbailey** [comment]
It's too late to add this in for 1.6.0, but we should consider backporting a fix so that users can update an HA master to 1.6.x in the near future. We should also put in a big warning in the release notes warning users not to try and upgrade if they deployed an HA master using kube-up.sh.

**Comment by roberthbailey** [comment]
@wojtek-t

**Comment by neolit123** [comment]
/remove-lifecycle frozen
/sig cloud-provider
/area provider/gcp

changing with ownership of "cluster/gce/upgrade.sh"
