### ISSUE TITLE
Add `NODE` field to `kubectl get pods` without `-owide`

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#43680]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
master

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
If I want to get pod node info, I have to add option of `-owide`, as most of the time, people want to get the `node` info of the pod for some troubleshooting, also printing out the `node` info can give more info for cluster admin where the pod is running.

The proposal is adding `NODE` field to the output of `kubectl get pods` without `-owide` option.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by shiywang** [comment]
cc @adohe @pwittrock @fabianofranz wdyt ?

**Comment by voyalab** [comment]
@gyliu513 Could you please add what you expected to happen ?

**Comment by gyliu513** [comment]
What I want is `kubectl get pods` can print out the `NODE` field by default without `-owide` option. The `NODE` info is a very important info for debugging and troubleshooting, I think this can make life easier for people using `kubectl` command. @voyalab

**Comment by liggitt** [comment]
Node names can be long. Including in wide output doesn't seem unreasonable

**Comment by gyliu513** [comment]
@liggitt does `kubectl` limit the length of the output? Only adding `NODE` seems does not impact much as for most cases the `NODE` is not that long.

**Comment by liggitt** [comment]
Ideally, where the pod is running makes no difference to the end user. The node info could be interesting for a cluster admin, but the other info about the pod seems more important

**Comment by gyliu513** [comment]
The end user sometimes may also need to debug the specified container, and what the end user need to do is get the pod NODE and logon to that node, then user `docker logs` to check what is wrong with the container, as sometimes the `kubectl logs` and `docker logs` may have different output.

**Comment by kargakis** [comment]
Most users are not going to care.

**Comment by gyliu513** [comment]
Just feel it is not convenient to always input `-owide` to get `NODE` info, I have no comments to close this issue if you all think this does not mean much. Thanks!

**Comment by kargakis** [comment]
@bgrant0607 are kubectl preferences (https://github.com/kubernetes/kubernetes/issues/10693) meant to handle cases where users want different defaults for their flags?

**Comment by James-QiuHaoran** [comment]
You can get the pod-node information by doing this:

```
kubectl get pod -o=custom-columns=NODE:.spec.nodeName,NAME:.metadata.name -n your_namespace
```
