### ISSUE TITLE
Unknown admission plugin: DefaultTolerationSeconds

### ISSUE THREAD

**Issue by niyanchun** [kubernetes/kubernetes#43693]
I install Kubernetes on Ubuntu 14.04, and I `git clone` the master branch, in kubernetes/cluster/ubuntu/config-default.sh, there is a config:

```
export ADMISSION_CONTROL=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,ResourceQuota
```

but kube-apiserver doesn't know `DefaultTolerationSeconds`.

**Comment by liggitt** [comment]
@niyanchun how did you install Kubernetes? The `DefaultTolerationSeconds` admission plugin referenced in the master version of the install scripts does not exist in the 1.5.x version

**Comment by liggitt** [comment]
not a blocker, CI is testing this plugin

**Comment by niyanchun** [comment]
@liggitt  I installed Kubernetes following this manual: https://kubernetes.io/docs/getting-started-guides/ubuntu/manual/,  and  add v1.5.5 to the $KUBE_ROOT/version file (#39224).  I commented the `DefaultTolerationSeconds` and installed successfully.

**Comment by liggitt** [comment]
I would recommend using the scripts from the [v1.5.5](https://github.com/kubernetes/kubernetes/releases/tag/v1.5.5) tag to accompany the v1.5.5 you have installed. Master scripts include features that do not exist yet in a released version.
