### ISSUE TITLE
Mock KubeProxy at the IPtables level in kubemark

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#43701]
Currently in Kubemark we are mokcing the whole "proxier" to be no-op. With that, we are missing a lot of things that kube-proxy is in fact doing.

We should mock KubeProxy at the "IPtables" layer:
- use the real kube-proxy code as it is
- only pass some "no-op" implementation of IPTables to it

We should be much close to its realistic behavior then.

@gmarek @shyamjvs

**Comment by wojtek-t** [comment]
@shyamjvs - if you have some free cycles, can you start looking into it?

**Comment by shyamjvs** [comment]
Sure, I definitely can look into it. However it might have to wait till I return from my vacation that starts soon (maybe this week if you think it wouldn't take much work). Also could you tell what priority this has?

**Comment by wojtek-t** [comment]
> However it might have to wait till I return from my vacation that starts soon 

That's fine - I filed it to not forget about it.

> Also could you tell what priority this has?

It will be pretty important if we want to have more-realistic kube-proxy in kubemark. So I would say something like P1.
