### ISSUE TITLE
E2e test failure on AWS 1.5.3 deployd with Juju 

### ISSUE THREAD

**Issue by ktsakalozos** [kubernetes/kubernetes#43707]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Kubernetes version** (use `kubectl version`): 1.5.3

**Environment**:
- **Cloud provider or hardware configuration**: AWS deployed with Juju
- **OS** (e.g. from /etc/os-release): 16.04.2 LTS (Xenial Xerus)
- **Kernel** (e.g. `uname -a`): 4.4.0-66-generic
- **Install tools**: Juju
- **Others**:

**What happened**:
Deployed kubernetes on aws run kubernetes-e2e and got two tests failing:
http://pastebin.ubuntu.com/24261115/

**What you expected to happen**:
No tests to fail

**How to reproduce it** (as minimally and precisely as possible):
Deploy kubernetes and run the e2e tests

**Anything else we need to know**:
The error logs looked like this: http://pastebin.ubuntu.com/24260807/
Tracing this down to the master: http://pastebin.ubuntu.com/24261240/
It seems that there is some auth issue. Is this expected/fixed on newer versions?

Thank you

**Comment by chuckbutler** [comment]
This is stale and will expire when 1.7 lands. @ktsakalozos would you be OK closing this issue as we're dropping support for 1.5 with the next release of the charms.

**Comment by ktsakalozos** [comment]
Yes, closing this since 1.7 release is so close. Thank you.
