### ISSUE TITLE
Change error handling path from GetAPIGroupResources

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#43706]
Callers to `staging/src/k8s.io/client-go/discovery/restmapper.go.GetAPIGroupResources` should be updated to handle both a return value and an error.  In most cases, it is better to tolerate an error and continue as best as possible instead of failing.

This becomes more important with API aggregation since API servers will be able to fail individually.

@cheftako

**Comment by lavalamp** [comment]
I don't think this blocks the release. File as a known issue.
