### ISSUE TITLE
Kubelet fails when run inside container

### ISSUE THREAD

**Issue by ivan4th** [kubernetes/kubernetes#43704]
There's a problem with running kubelet in containers (k8s version v1.6.0-rc.1). I'm trying to start a cluster using [kubeadm-dind-cluster](https://github.com/Mirantis/kubeadm-dind-cluster) and kubelet fails to start any containers. `kubeadm-dind-cluster` creates a cluster where the nodes are represented by containers. The problem occurs when using Mac docker of the following version:

```
Version 17.03.0-ce-mac2 (15657)
Channel: beta
32de842512

Kernel version: 4.9.12-moby
```

There's the following diagnostics in kubelet log:
```
Mar 27 08:13:20 kube-master hyperkube[571]: I0327 08:13:20.817136     571 kubelet.go:1158] Container garbage collection succeeded
Mar 27 08:13:20 kube-master hyperkube[571]: E0327 08:13:20.823647     571 kubelet.go:1246] Failed to start ContainerManager failed to initialise top level QOS containers: root container /kubepods doesn't exist
```

`kubeadm-dind-cluster` works on Ubuntu 16.04.2 (kernel 4.4.0-57-generic)
On Fedora 25 with kernel 4.8.6-300.fc25.x86_64 there are some problems with DIND script + k8s 1.6, but this "/kubepods" problem doesn't occur either.

@errordeveloper has similar problems with [kxd](https://github.com/errordeveloper/kxd) which doesn't use DIND, he will provide more details in the comments shortly.

I suspected that #41234 was the culprit but turns out that kubelet starts just fine when I check out 9b4a8f746449aabc1b9083d7987fec55a89464f2

Currently bisecting.

In order to reproduce it on Mac:
```
wget https://cdn.rawgit.com/Mirantis/kubeadm-dind-cluster/master/fixed/dind-cluster-v1.6.sh
chmod +x dind-cluster-v1.6.sh
./dind-cluster-v1.6.sh up
```

After `kubeadm init` hangs, enter `kube-master` container and inspect kubelet log:
```
journalctl -xe -u kubelet.service
```

**Comment by errordeveloper** [comment]
I am also seeing this on Docker for Mac stable (same 4.9.12 kernel), and my setup doesn't use `systemd` and only mounts Docker socket from the hosts, i.e. not Docker-in-Docker.

To reproduce:
```
git clone --branch kube-1.6 https://github.com/errordeveloper/kxd
cd kxd
make && ./start.sh
```

**Comment by derekwaynecarr** [comment]
the kubelet needs rw access to host /sys/fs/cgroup in 1.6 in order to use the node allocatable and per pod cgroup support.

**Comment by errordeveloper** [comment]
So I think we have found a work around now,  adding `--cgroups-per-qos=false --enforce-node-allocatable=""` solves the problem.

> the kubelet needs rw access to host /sys/fs/cgroup in 1.6 in order to use the node allocatable and per pod cgroup support.

@derekwaynecarr I already have `-v /sys:/sys:rw -v /sys/fs/cgroup:/sys/fs/cgroup:rw`, or is that not enough or somehow not the right thing?

**Comment by errordeveloper** [comment]
I've tested kernel version 4.9 and same Docker version 17.03-ce on a Debian VM, and had been able `dind-cluster-v1.6.sh` worked there, so this is somehow specific to Docker for Mac.
Given there exists a work around, this doesn't look like a release-blocking bug, nevertheless it is still a bug, and I find all the documentation and flags names etc really hard to grasp, clearly it's not a kind of a feature that's been designed for end-users... So I'm worried if someone gets exposed to it, will sendup very very unhappy and confused.

**Comment by CallMeFoxie** [comment]
Seeing this on Debian Jessie as well:
# docker version
 Version:      1.12.6
 API version:  1.24
overlay2 fs
RHEL7.2 kernel (3.10.0 with backported overlay2 driver)

adding --cgroups-per-qos=false --enforce-node-allocatable="" seems to have fixed it as well here.

**Comment by errordeveloper** [comment]
So is this a Debian machine with a RHEL kernel or, perhaps, you've not
pasted the right info here?

**Comment by CallMeFoxie** [comment]
Yes it is a Debian machine with a RHEL kernel.

**Comment by errordeveloper** [comment]
@CallMeFoxie ok, I just never heard of anyone with such configuration before, but I'm sure you have all the good reasons for doing that. So in release#306 it's been mentioned that `--cgroup-driver=systemd` is another working solution for RHEL, which is probably better and it's just that the auto detection code is somehow not doing the right thing.

**Comment by CallMeFoxie** [comment]
Seems that is not the case for us, adding `--cgroup-driver=systemd` leads into error: 
`failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "systemd" is different from docker cgroup driver: "cgroupfs"`
and setting the driver to cgropufs leads to the forementioned error.

**Comment by derekwaynecarr** [comment]
If you are running a kubelet in a container on docker for Mac, and you were getting the error about failed to create QoS containers this should have been fixed by https://github.com/kubernetes/kubernetes/pull/45515 the issue was docker vm for some reason has openrc cgroup

**Comment by CallMeFoxie** [comment]
This may fix our use case as well as we were using OpenVZ branded kernel on some test nodes apparently which adds vz cgroup :) will try later today.

**Comment by CallMeFoxie** [comment]
Yep, having extra cgroups seems to cause this at least in our case :) Thanks for finding it!

**Comment by kornface13** [comment]
I'm having this same issue on 1.6.2 on CentOS.  Not running kubelet as a pod.  Kernel is 4.11.1-1.el7.elrepo.x86_64.  

Specifying --cgroups-per-qos=false --enforce-node-allocatable= in my kubelet config has solved the problem and lets the kubelet become ready again.

**Comment by lmdaly** [comment]
Is there any other fix for this other than enabling the -cgroups-per-qos=false --enforce-node-allocatable= flags in kubelet? I am experimenting and need the cgroups-per-qos flag enabled.

I am on Centos 7 with a kernel 4.11 running Kubernetes master branch on baremetal

**Comment by gjw0317** [comment]
I'm having this same issue when I update kubernetes cluster from v1.4.7 to v1.6.4 or just use v1.6.4 to install.
CentOS 7.2 & 7.3
Kernel 4.11
Storage Driver: overlay2
Docker: 1.12.3 & 1.13.1

This issue has not been encountered while using the devicemapper.

**Comment by derekwaynecarr** [comment]
@gjw0317 - can you list the set of cgroups you have enabled?

this is actually fixed via https://github.com/kubernetes/kubernetes/pull/45515

please ensure that "cpu", "cpuacct", "cpuset", "memory", "hugetlb", "systemd" are the only ones that kubelet is now looking at.  the previous cause of this issue was having an additonal cgroup enabled unknown to the undelrying runc libraries.
