### ISSUE TITLE
Cluster autoscaler scales up too much

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#43709]
On some occasions Cluster Autoscaler may scale up the cluster two times. This results in growing the cluster too large. The size gets back to normal soon but the user will be forced to pay for the unneeded node for 10min/1h, depending on the cloud provider. 

cc: @MaciekPytel @fgrzadkowski @ethernetdan @enisoc

**Comment by bgrant0607** [comment]
@mwielgus Please provide more information.

**Comment by mwielgus** [comment]
@bgrant0607
Imagine that you have just created a pod that cannot be scheduled. CA expands one of the migs to accommodate it. Just when the node arrives there is a brief moment when the pod is still pending (scheduler didn't retry it yet) but the node is available. Scale up is over. Pod is pending. So we might try to scale up again, which would be incorrect. To protect against such situations we run a simulated scheduling on all nodes. If any node can accommodate any of the pending pods then the pod is not pending and should not trigger a scale up. 

After a scale up we create "virtual" nodes inside CA so that we don't scale up again for the same pods. Once the node arrives its virtual placeholder is deleted. 

And, if I'm correct, we have a bug here. A node with node condition ready=true but with non ready network is considered as fully started but broken. Its virtual placeholder is gone so we trigger scale up again. Seconds later the network arrives and the scale up appears to be non-needed.

I'm testing right now a 10 line fix for this issue. After the fix is merged  I would like to bump CA version in 1.6 as having the old code would impact all of the current CA users on GCE and GKE (and possibly on other cloud providers too).

**Comment by liggitt** [comment]
is this a regression in cluster autoscaler for 1.6, or did the same behavior exist in 1.5?

**Comment by mwielgus** [comment]
It is a regression. Doesn't happen always (depends on the network setup timings) but when it does it is quite confusing.
