### ISSUE TITLE
openapi/swagger needs to be summarized across the cluster

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#43717]
The `kube-apiserver` now includes the aggregator and the default openapi information is accessible via delegation, but we should really be building it based on the specific group versions being aggregated by the aggregator.

This is not as simple as just including all the available API groups from a given server, since a server can reasonably host more GroupVersions than are exposed.  Common reasons for doing this would be servers that can handle delegated authentication or authorization checks.  This would be common for someone plugging in a new webhook (only aggregate the kube-apiserver check, but the kube-apiserver could delegate out) or cases where the aggregated API server wants to support operations like `kubectl auth can-i`.

Client-side validation will not function well for aggregated API servers until this work.

@mbohlool @kubernetes/sig-api-machinery-misc

**Comment by mbohlool** [comment]
Aggregator API server knows what Group/Version each of the aggregated servers serve, so it should be able to filter only those from the OpenAPI spec of the aggregated servers.
