### ISSUE TITLE
set --proxy-client-cert-file and --proxy-client-key-file for kube-up.sh

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#43716]
The `kube-apiserver` needs a proxy client certificate for the aggregated API servers to trust in order to effectively proxy authentication.  `kubeadm` already has the cert/key pairs required and https://github.com/kubernetes/kubernetes/pull/43715 wires them together.

We need similar wiring for `kube-up.sh` so that our e2e tests can test the authentication and authorization flows.

@cheftako @kubernetes/sig-api-machinery-misc

**Comment by liggitt** [comment]
cc @mikedanese, same concept as `api->kubelet` for `api->extension api server`

**Comment by roberthbailey** [comment]
Is anyone driving this for 1.7?

**Comment by deads2k** [comment]
> Is anyone driving this for 1.7?

@cheftako do you have a pull for this?

**Comment by cheftako** [comment]
pull/47094

**Comment by dchen1107** [comment]
I re-open this issue since I reverted https://github.com/kubernetes/kubernetes/pull/47094
