### ISSUE TITLE
publish sample-apiserver image for testing

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#43714]
We need an API server image we can use to create a pod and run in e2e tests.

The `kube-apiserver` now hosts the aggregator in front.  We are capable of running e2e tests on it, but we need an image to test with.  As a simple starting point, we could use the `wardle` group hosted by the `k8s.io/sample-apiserver`, but we need an image published to use it.

@cheftako @kubernetes/sig-api-machinery-misc

**Comment by marun** [comment]
@deads2k Given there's been no update for weeks, I'm assuming this shouldn't be blocking 1.7

**Comment by deads2k** [comment]
> @deads2k Given there's been no update for weeks, I'm assuming this shouldn't be blocking 1.7

Yes, it's prereq slipped :(

**Comment by cheftako** [comment]
I am working on getting apiserver-builder to generate something like an
ideal API server image. I would suggest we use that for as the e2e test
image. It allows us to test both the aggregator and that the tooling we are
building to help customers generate apiservers.

**Comment by deads2k** [comment]
> I am working on getting apiserver-builder to generate something like an
> ideal API server image. I would suggest we use that for as the e2e test
> image. It allows us to test both the aggregator and that the tooling we are
> building to help customers generate apiservers.

The sample-apiserver has been around a while.  Is there a reason not to make use of it now for testing right away?  Nothing prevents us from adding additional tests later on.
