### ISSUE TITLE
How to read client IP addresses from HTTPS requests behind Kubernetes services? 

### ISSUE THREAD

**Issue by niuchp** [kubernetes/kubernetes#43729]
First of all introduce my cluster environment:
kubernetes-1.5.1
docker-1.12

I met a problem: I want to get the application of real client IP address, use the ingress of way of the HTTP service can get real IP, but HTTPS service I don't know what I should use the way to get real client IP address.
thanks for any helps

**Comment by hjacobs** [comment]
Usually the load balancer (e.g. AWS ELBv2/ALB when using https://github.com/zalando-incubator/kube-ingress-aws-controller) will add a special `X-Forwarded-For` header with the original client IP. Your application needs to read the IP from this header.

See https://en.wikipedia.org/wiki/X-Forwarded-For

**Comment by niuchp** [comment]
@hjacobs Thanks for your reply. My kubernetes is deployed on a physical server, not in Cloud, in this case, how should i do?Ingress can be implemented?

**Comment by niuchp** [comment]
This problem is solved. 
1.Use the ingress proxy backend https service.Like:https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/ssl-services
2.Modify the configuration file server.xml in tomcat,
```
                <Valve className="org.apache.catalina.valves.AccessLogValve" directory="${carbon.home}/repository/logs"
                       prefix="http_access_" suffix=".log"
                       pattern="**%{X-Forwarded-For}**i %l %u %t %r %s %b %D %{User-Agent}i" resolveHosts="false"/>
```

**Comment by hjacobs** [comment]
@niuchp there is a better solution for Tomcat: use the `RemoteIPValve` for proxy (LB) support: https://go.utah.edu/docs/config/valve.html#Remote_IP_Valve

**Comment by sanjaydash** [comment]
Client usually requests ingress gateway IP  to reach the kuberneetes Cluster . Once we get the IP of the client using X-forwarded-for header, 
How the Kubernetes pod can exchange greetings with the client ? . because the client only knows Ingress IP not the pod IP.
