### ISSUE TITLE
"Unable to get uid from job ... in namespace ..." log spam

### ISSUE THREAD

**Issue by ankon** [kubernetes/kubernetes#43739]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): "unable to get uid from job", review titles of all open/closed issues in this project in the result.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
~~~~
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
~~~~

**Environment**:
- **Cloud provider or hardware configuration**: minikube on Linux

**What happened**:
I have a couple of jobs defined, which execute once and then are done for good. Recently I looked into a suspicious high CPU usage by my minikube VM, and noticed that it is logging something like this for every job:
~~~~
Mar 28 08:40:31 minikube localkube[17880]: E0328 08:40:31.241671   17880 utils.go:91] Unable to get uid from job JOB-NAME in namespace NAMESPACE
~~~~

This happens every 10s.

**What you expected to happen**: No such log messages.

**How to reproduce it** (as minimally and precisely as possible):
From reading through the code: Deploy a job (not a cronjob).

**Anything else we need to know**:
I've looked through the code that logs this message, and it seems that this is part of the scheduledjobs logic. I'm seriously wondering why it is looking at these jobs in the way it does, rather than searching for the jobs it needs based on the names scheduled jobs and some label-magic. It also feels wrong to have these checks happen continuously, as this smells like it would get slower and slower the more jobs I have (both scheduled and non-scheduled).

**Comment by bcorijn** [comment]
Seeing this in my logs as well. I had an issue some weeks ago that caused my master to become very slow to respond and often time-out. Figured out it was because of a CronJob that had been running every few minutes for several days without any clean-up, leaving some 3500 old jobs/pods around. I didn't check the kube-controller-manager logs back then, but wondering if this wouldn't be related?

**Comment by soltysh** [comment]
The error is silenced in https://github.com/kubernetes/kubernetes/commit/0cf4744e755.
