### ISSUE TITLE
decent documentation for fresh admins

### ISSUE THREAD

**Issue by jeroenjacobs1205** [kubernetes/kubernetes#43743]
I'm trying to setup a new cluster from scratch, but I find the lack of decent documentation disturbing. It seems most suggestions fall into one of those categories:

- use a hosted solution: this is a no-go for my project. We need to admin this ourselves
- use a deploy script (kubeadm, kargo): also a no-go. Most projects don't really explain how the security is configured, or why it is configured in that way.
- kubernetes from scratch: the only thing that resembles a getting started guide for new administrators, but it doesn't go into much detail why that particular security configuration was chosen and what other options are available.
- the reference documentation: these only contain a one-liner explaining the commandline options. That's enough to configure kubernetes.

So, what am I missing here? I want to get a good overview of all the possible setups and implications of a particular setup, but I can't find it anywhere.

**Comment by dixudx** [comment]
You can refer to [Getting Started Guides](https://kubernetes.io/docs/getting-started-guides/).

**Comment by jeroenjacobs1205** [comment]
To give an actual example on where the documentation fails me. Let's say I have 3 API servers running which ssl key should be used to for serviceaccount verification. This what the documentation tells me:

--service-account-key-file : File containing PEM-encoded x509 RSA or ECDSA private or public keys, used to verify ServiceAccount tokens. If unspecified, --tls-private-key-file is used. The specified file can contain multiple keys, and the flag can be specified multiple times with different files.

If each api server uses it's own ssl key, how does this work? Or do I need to specify a CA keyfile when using multiple api servers?  Are service-accounts shared between different api servers, or has every api server it's own serrvice account token? The documentation barely touches this subject.

**Comment by jeroenjacobs1205** [comment]
Seems I'm not the only one: https://github.com/kubernetes/kubernetes/issues/11000

**Comment by hjacobs** [comment]
@jeroenjacobs1205 I feel your pain. There is no good overview of cluster provisioning and all implications (there are many different ways to do things). I created a doc to share how we run Kubernetes on AWS: http://kubernetes-on-aws.readthedocs.io/en/latest/admin-guide/kubernetes-in-production.html + slides https://www.slideshare.net/try_except_/kubernetes-on-aws-at-europes-leading-online-fashion-platform

**Comment by luxas** [comment]
/sig cluster-lifecycle

@kubernetes/sig-cluster-lifecycle-feature-requests We should indeed document the differences between these solutions better.

@jeroenjacobs1205 I think kubeadm should be pretty secure with v1.6. You might be interested in reading https://github.com/kubernetes/kubeadm/pull/156 as well

**Comment by luxas** [comment]
cc @kubernetes/sig-auth-feature-requests as well

**Comment by luxas** [comment]
/remove-lifecycle stale
cc @kubernetes/sig-cluster-lifecycle-feature-requests @kubernetes/sig-docs-maintainers @errordeveloper 
We're gonna try to work on this in the v1.10 timeframe

**Comment by luxas** [comment]
But this issue maybe should be migrated to kubernetes/website...

**Comment by hjacobs** [comment]
/remove-lifecycle rotten 

This topic is too important to just become "stale".

Quote from [Kubernetes Application survey](https://docs.google.com/spreadsheets/d/12ilRCly2eHKPuicv1P_BD6z__PXAqpiaR-tDYe2eudE/edit#gid=840936477):

> 
I wish that more kubernetes developers would spend more time running production kubernetes clusters. It is not an easy task to keep up with the rapid pace of change.

**Comment by ahmetb** [comment]
I think this work requires someone to take initiative and drive the work (on kubernetes/website repo).

The documentation now supports multiple personas ([example](https://kubernetes.io/docs/home/?path=users&persona=cluster-operator&level=foundational)) and "Cluster Admin" is one of them.

I recommend figuring out a workgroup and tracking this at kubernetes/website repository.
