### ISSUE TITLE
Incorrect memory calculation for Burstable QoS level cgroups

### ISSUE THREAD

**Issue by qwang1** [kubernetes/kubernetes#43748]
**What keywords did you search in Kubernetes issues before filing this one?** :
QoS/cgroup

**Is this a BUG REPORT or FEATURE REQUEST?**:
It's a BUG REPORT

**Kubernetes version**:
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1144+33c455271e586f", GitCommit:"33c455271e586f267f1d52272b32f69da729ae2a", GitTreeState:"clean", BuildDate:"2017-03-14T07:16:11Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1144+33c455271e586f", GitCommit:"33c455271e586f267f1d52272b32f69da729ae2a", GitTreeState:"clean", BuildDate:"2017-03-14T07:16:11Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: An all-in-one environment on AWS
- **OS** : Red Hat Enterprise Linux Server 7.3 (Maipo)
- **Kernel** : 3.10.0-327.22.2.el7.x86_64
- **Install tools**: hack/local-up-cluster.sh

**What happened**:
I used the following method to calculate memory.limit_in_bytes for the Burstable and BestEffort QoS level cgroups:

    Guaranteed limit matches root cgroup at is not set by this code
    Burstable limit is NodeAllocatable - Guaranteed reserve
    BestEffort limit is NodeAllocatable - Guaranteed reserve - Burstable reserve

Compared the results with cgroup, I found in fact calculation for QoS level cgroup is:
Burstable memory.limit_in_bytes = **NodeCapacity** - {(summation of memory requests of `Guaranteed` pods)*(reservePercent / 100)}, not **NodeAllocatable**

**How to reproduce it** (as minimally and precisely as possible):
```
1. Enable QoS level cgroup (--cgroups-per-qos=true, --experimental-qos-reserved=memory=100%)
# ps aux | grep kubelet
root     11888  0.0  0.0 193356  2800 pts/0    S+   06:19   0:00 sudo -E /data/src/kubernetes/_output/local/bin/linux/amd64/hyperkube kubelet --experimental-qos-reserved=memory=100% --enable-cri=true --v=3 --chaos-chance=0.0 --container-runtime=docker --rkt-path= --rkt-stage1-image= --hostname-override=127.0.0.1 --cloud-provider= --cloud-config= --address=127.0.0.1 --require-kubeconfig --kubeconfig /var/run/kubernetes/kubelet.kubeconfig --feature-gates=AllAlpha=true --cpu-cfs-quota=true --enable-controller-attach-detach=true --cgroups-per-qos=true --cgroup-driver=systemd --keep-terminated-pod-volumes=true --eviction-hard=memory.available<100Mi --eviction-soft= --eviction-pressure-transition-period=1m --pod-manifest-path=/var/run/kubernetes/static-pods --cluster-dns=8.8.8.8 --port=10250
root     11897  5.8  0.7 600364 61228 pts/0    Sl+  06:19   0:00 /data/src/kubernetes/_output/local/bin/linux/amd64/hyperkube kubelet --experimental-qos-reserved=memory=100% --enable-cri=true --v=3 --chaos-chance=0.0 --container-runtime=docker --rkt-path= --rkt-stage1-image= --hostname-override=127.0.0.1 --cloud-provider= --cloud-config= --address=127.0.0.1 --require-kubeconfig --kubeconfig /var/run/kubernetes/kubelet.kubeconfig --feature-gates=AllAlpha=true --cpu-cfs-quota=true --enable-controller-attach-detach=true --cgroups-per-qos=true --cgroup-driver=systemd --keep-terminated-pod-volumes=true --eviction-hard=memory.available<100Mi --eviction-soft= --eviction-pressure-transition-period=1m --pod-manifest-path=/var/run/kubernetes/static-pods --cluster-dns=8.8.8.8 --port=10250
root     12435  0.0  0.0 112648   960 pts/2    S+   06:19   0:00 grep --color=auto kubelet

2. Node description
Capacity:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					2
 memory:				7747768Ki
 pods:					110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					2
 memory:				7645368Ki
 pods:					110
System Info:
 Machine ID:			f9370ed252a14f73b014c1301a9b6d1b
 System UUID:			EC221954-173A-FA06-C46F-EC7839FE551A
 Boot ID:			d1f9bbcb-82da-46d7-9f67-3ff471b22bef
 Kernel Version:		3.10.0-327.22.2.el7.x86_64
 OS Image:			Red Hat Enterprise Linux Server 7.3 (Maipo)
 Operating System:		linux
 Architecture:			amd64
 Container Runtime Version:	docker://1.12.6
 Kubelet Version:		v1.7.0-alpha.0.1144+33c455271e586f
 Kube-Proxy Version:		v1.7.0-alpha.0.1144+33c455271e586f
ExternalID:			127.0.0.1
Non-terminated Pods:		(6 in total)
  Namespace			Name				CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----				------------	----------	---------------	-------------
  qwangkube			pod-onecontainer-be		0 (0%)		0 (0%)		0 (0%)		0 (0%)
  qwangkube			pod-onecontainer-bu		300m (15%)	400m (20%)	300Mi (4%)	400Mi (5%)
  qwangkube			pod-onecontainer-g		600m (30%)	600m (30%)	600Mi (8%)	600Mi (8%)
  qwangkube			pod-twocontainers-be		0 (0%)		0 (0%)		0 (0%)		0 (0%)
  qwangkube			pod-twocontainers-bu		50m (2%)	500m (25%)	50Mi (0%)	500Mi (6%)
  qwangkube			pod-twocontainers-g		300m (15%)	300m (15%)	300Mi (4%)	300Mi (4%)

# cat /sys/fs/cgroup/memory/kubepods.slice/kubepods-pod*.slice/memory.limit_in_bytes 
629145600        [=600Mi]
314572800        [=300Mi]

# cat /sys/fs/cgroup/memory/kubepods.slice/kubepods-burstable.slice/memory.limit_in_bytes 
6989996032          [7747768Ki-(629145600+314572800)=6989996032]

# cat /sys/fs/cgroup/memory/kubepods.slice/kubepods-besteffort.slice/memory.limit_in_bytes 
6622994432
```

**What you expected to happen**:

Given --experimental-qos-reserved=memory=100%
```
BU=7645368Ki-(629145600+314572800)*100%=6885138432
# cat /sys/fs/cgroup/memory/kubepods.slice/kubepods-burstable.slice/memory.limit_in_bytes 
should be 6885138432

BE=6885138432-(50Mi+300Mi)*100%=6518136832
# cat /sys/fs/cgroup/memory/kubepods.slice/kubepods-besteffort.slice/memory.limit_in_bytes 
should be 6518136832
```

**Anything else we need to know**:
As document  [pod-resource-management.md](https://github.com/derekwaynecarr/community/blob/5f8f6132dc9c62ed7ef86a0e437542099ecd2283/contributors/design-proposals/pod-resource-management.md) said,
`BestEffort memory.limit_in_bytes = Burstable memory.limit_in_bytes - sum(Burstable(pods[].containers[].resource.requests))` , not limits.

**Comment by ncdc** [comment]
cc @derekwaynecarr @sjenning @vishh

**Comment by sjenning** [comment]
We are using `getNodeAllocatableAbsolute()` in `qos_container_manager.go` to get the node allocatable value
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/node_container_manager.go#L152

This code seems to indicate that if `KubeReserved` and `SystemReserved` are not specified, capacity will equal allocatable.  However, the allocatable value reported in the Node resource is different from capacity.

So there is a disconnect here.

**Comment by sjenning** [comment]
The source of the discrepancy is a difference between `getNodeAllocatableAbsolute()` and `GetNodeAllocatableReservation()`.

`GetNodeAllocatableReservation()` takes into account the hard eviction threshold where `getNodeAllocatableAbsolute()` does not/

**Comment by derekwaynecarr** [comment]
@sjenning -- correct, the verification needs to account for eviction threshold configuration (assuming it was 250Mi here)?

**Comment by derekwaynecarr** [comment]
the values will differ based on the setting of `experimental-allocatable-ignore-eviction` flag in kubelet.

When set to 'true', Hard Eviction Thresholds will be ignored while calculating Node Allocatable. See https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md for more details. [default=false]

**Comment by vishh** [comment]
I feel this is WAI. https://github.com/kubernetes/kubernetes/issues/43748#issuecomment-289801219 is correct.

**Comment by sjenning** [comment]
@qwang1 so we have determined that this is somewhat confusing but working as intended

You can take two different paths with the test:

- Easiest is to just add `--experimental-allocatable-ignore-eviction=true` to the kubelet.  Then your test will work.
- Slightly more work, and maybe a different test all together, is to set the hard memory eviction threshold with `--eviction-hard=memory.available<500Mi`, then subtract 500Mi from `Allocatable` to get the value that `getNodeAllocatableAbsolute()` produces for use in the reserve calculation.

/close

**Comment by qwang1** [comment]
@sjenning Capacity-Allocatable=eviction-hard，thank you very much.
