### ISSUE TITLE
kubernetes-master juju layer should allow RBAC configuration

### ISSUE THREAD

**Issue by jacekn** [kubernetes/kubernetes#43756]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): none, I read layer source code instead to confirm this was not currently possible

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

There should be a way to mange RBAC rules in the kubernetes-master charm in a juju way. I think set of rbac actions might work as a solution.

**Anything else we need to know**:

Main bug for access control: https://github.com/kubernetes/kubernetes/issues/43572

**Comment by wwwtyro** [comment]
@tvansteenburgh This is on our roadmap.
