### ISSUE TITLE
kubectl describe psp should describe all fields

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubernetes#43757]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

describe psp 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1487+a845e3e936e91c-dirty", GitCommit:"a845e3e936e91cd14c4c5b462631233716d5839b", GitTreeState:"dirty", BuildDate:"2017-03-27T14:04:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1487+a845e3e936e91c-dirty", GitCommit:"a845e3e936e91cd14c4c5b462631233716d5839b", GitTreeState:"dirty", BuildDate:"2017-03-27T14:04:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

Doesn't matter.

**What happened**:
`kubectl describe psp <name>` doesn't show PSP's fields:
```console
$ kubectl describe psp restricted
Name:		restricted
Namespace:	
Labels:		<none>
Events:		<none>
```

**What you expected to happen**:
All PSP fields should be shown.

**How to reproduce it** (as minimally and precisely as possible):
1. `PSP_ADMISSION=true ALLOW_PRIVILEGED=true ALLOW_SECURITY_CONTEXT=true ALLOW_ANY_TOKEN=true ENABLE_RBAC=true RUNTIME_CONFIG="extensions/v1beta1=true,extensions/v1beta1/podsecuritypolicy=true" hack/local-up-cluster.sh`
2. `kubectl describe psp restricted`

**Comment by php-coder** [comment]
@pweil- If you're agree with that than I (or @roidelapluie? :) ) could implement it.

**Comment by pweil-** [comment]
@php-coder yes, improve the describer.  Look at the scc describer for formatting.

**Comment by kargakis** [comment]
@pweil- any ideas which SIG should own PSP?

**Comment by php-coder** [comment]
@kargakis In this case it should be sig-cli

/sig cli

**Comment by pweil-** [comment]
@kargakis yeah, this is cli related.  I'd go with sig-auth for actual behavior.
