### ISSUE TITLE
Allow kubernetes-master layer to trust external CA

### ISSUE THREAD

**Issue by jacekn** [kubernetes/kubernetes#43754]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): none, I read layer source code instead to confirm this was not currently possible

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE_REQUEST

This is related to https://github.com/kubernetes/kubernetes/issues/43572. It would be good for the kubernetes-master layer (or etcd layer?) to allow operators to add external CA to the file --client-ca-file points at.

I'm not sure what's the best place to do that but maybe we should add new option to the etcd juju layer?

According to https://github.com/kubernetes/kubernetes/issues/2895 CA file can be a bundle, this could make it easier

**Comment by wwwtyro** [comment]
@tvansteenburgh This will probably be resolved by the cloudinit docs we're likely going to add for the layer-docker issue.
