### ISSUE TITLE
kubectl version output isn't human readable

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubernetes#43750]
I was confused by the `kubectl version` that looks like more as machine readable rather than as human readable.
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1487+a845e3e936e91c-dirty", GitCommit:"a845e3e936e91cd14c4c5b462631233716d5839b", GitTreeState:"dirty", BuildDate:"2017-03-27T14:04:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1487+a845e3e936e91c-dirty", GitCommit:"a845e3e936e91cd14c4c5b462631233716d5839b", GitTreeState:"dirty", BuildDate:"2017-03-27T14:04:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
I feel that UX could be better if it will be written in multiple lines and without curly braces/quotes:
```
Client Version: 1.7+
    Git Version: v1.7.0-alpha.0.1487+a845e3e936e91c-dirty
    Git Commit: a845e3e936e91c
    Build Date: 2017-03-27T14:04:25Z
    Go Version: go1.7.4
    Platform: linux/amd64

Server Version: 1.7+
    Git Version: v1.7.0-alpha.0.1487+a845e3e936e91c-dirty
    Git Commit: a845e3e936e91c
    Build Date: 2017-03-27T14:04:25Z
    Go Version: go1.7.4
    Platform: linux/amd64
```

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by kargakis** [comment]
Agreed on this one, we should pretty-print this output.

**Comment by shiywang** [comment]
@php-coder I would like to change that tomorrow if you are not working on it.

**Comment by php-coder** [comment]
@shiywang I'm not working on it, so feel free to provide a PR. But I wouldn't do anything untill we get approval from @kubernetes/sig-cli-misc

**Comment by ncdc** [comment]
cc @kubernetes/sig-testing-misc, don't some of the tests rely on this output?

**Comment by spxtr** [comment]
They probably do. There should be a `kubectl version -o=json` option or something that we can use in test infra.

**Comment by alejandroEsc** [comment]
please have a look at:
https://github.com/kubernetes/kubernetes/pull/39858
and related issue:
https://github.com/kubernetes/kubernetes/issues/39427

The above is approved and had an lgtm labeled, but removed by the bot because of testing.

**Comment by shiywang** [comment]
@kargakis  I think we can close this ?

**Comment by php-coder** [comment]
@shiywang I don't see that it was fixed. Does the output of `kubectl version` was improved?

**Comment by gtirloni** [comment]
@php-coder kubectl now has a `--output` option which lets you select between YAML or JSON.

However, I believe this is reversed. The more human-friendly output is hidden behind an option and the machine-friendly output is the default. I believe it should be the opposite.

**Comment by Culip** [comment]
I agree, that minor feature would be great. An obvious workaround is to use `kubectl version | tr ',' '\n'`.  You can also make an alias for your shells.
