### ISSUE TITLE
Kubernetes Cluster for Travis

### ISSUE THREAD

**Issue by cheld** [kubernetes/kubernetes#43759]
In Dashboard we used hyperkube-container to execute click tests during travis build. Since version 1.6 hyperkube-container is not working any longer (because of small issues which could be fixed easily). Currently, we start the hyperkube-container with a gulp task and concurrently compile and lint the source-code.

kubeadm does not seem like a good choice to integrate into the build script in such a way as it requires sudo and is not intended to be used like this.

So, does anyone has a good proposal how to replace hyperkube-container? Or should we fix?

**Comment by cheld** [comment]
https://github.com/kubernetes/dashboard/issues/1710

**Comment by luxas** [comment]
kubeadm should work well for this task.
Also see @ivan4th's project: https://github.com/Mirantis/kubeadm-dind-cluster

I think we discussed this in an other thread, closing as a duplicate

**Comment by cheld** [comment]
Thanks for closing.
