### ISSUE TITLE
PodSecurityPolicy: consider removing omitempty from the fields to improve UX

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubernetes#43751]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

omitempty

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1487+a845e3e936e91c-dirty", GitCommit:"a845e3e936e91cd14c4c5b462631233716d5839b", GitTreeState:"dirty", BuildDate:"2017-03-27T14:04:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1487+a845e3e936e91c-dirty", GitCommit:"a845e3e936e91cd14c4c5b462631233716d5839b", GitTreeState:"dirty", BuildDate:"2017-03-27T14:04:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

Doesn't matter.

**What happened**:

When I'm getting PSP in YAML format (`kubectl get psp <name> -o yaml`) I don't see all the fields because some of them have default values and are omitted.

The same happens when I'm trying to edit PSP (`kubectl edit psp <name>`). In the later case it looks even more mysterious because after editing field and changing its value to `false`, on next edit this field will disappear.

**What you expected to happen**:

I expect to see all the fields with their values even if they have default values.

**How to reproduce it** (as minimally and precisely as possible):

1. `PSP_ADMISSION=true ALLOW_PRIVILEGED=true ALLOW_SECURITY_CONTEXT=true ALLOW_ANY_TOKEN=true ENABLE_RBAC=true RUNTIME_CONFIG="extensions/v1beta1=true,extensions/v1beta1/podsecuritypolicy=true" hack/local-up-cluster.sh`
2. `kubectl get psp restricted -o yaml`

**Comment by php-coder** [comment]
CC @pweil-

**Comment by pweil-** [comment]
while I agree that it looks nicer to show these fields it is inline with the [api conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#optional-vs-required) to have omitempty here because there is a default value making the field optional

**Comment by php-coder** [comment]
API convention doc uses `bool` type as an example for required fields and PSP has boolean fields too. So, maybe these fields isn't optional because they're not a pointers to boolean?

**Comment by pweil-** [comment]
> So, maybe these fields isn't optional because they're not a pointers to boolean

Right.  They don't need to distinguish from the unset and default value so they aren't pointers (the infamous troolean) and therefore do not require the user to set a value when submitting the object.

**Comment by kargakis** [comment]
> troolean

lmao
