### ISSUE TITLE
Kubelet failed to get node info following network unreachable for Kubernetes master

### ISSUE THREAD

**Issue by activeshadow** [kubernetes/kubernetes#43768]
**What keywords did you search in Kubernetes issues before filing this one?**: "Kubelet failed to get node info"

That search turned up two open issues: #41850 and #35238. However, both of those seem to have to do with errors regarding the cloud provider. We do not use a cloud provider (we're seeing these errors on nodes running outside of a cloud provider).

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): **BUG REPORT**

**Kubernetes version** (use `kubectl version`): kubelet version `v1.4.7+coreos.0`

**Environment**:
- **Cloud provider or hardware configuration**: Physical HW, 4-core, 8G RAM
- **OS** (e.g. from /etc/os-release): CoreOS Container Linux Stable
- **Kernel** (e.g. `uname -a`): Linux minion 4.9.9-coreos-r1 #1 SMP Tue Mar 14 21:09:42 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz GenuineIntel GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:

When `kubelet` starts, there are times when it cannot connect to the Kubernetes master because the network is unreachable, and continues to fail even after the network is actually reachable.

**What you expected to happen**:

I expected the `kubelet` to eventually be able to make a connection to the Kubernetes master once the network is reachable.

**How to reproduce it** (as minimally and precisely as possible):

Unsure. It does not happen consistently.

**Anything else we need to know**:

In the Systemd service unit for the `kubelet` service (via the cloud-config) I specify `Requires=network-online.target` and `After=network-online.target`, but this doesn't seem to make a difference.

I've posted some anonymized Journal logs for the `kubelet` service at [this gist](https://gist.github.com/activeshadow/c41aca55e0a9b42899ddc5950513a581). The Journal logs on the actual host continue to log `Kubelet failed to get node info` as time goes on, even after the routable network to the Kubernetes master is indeed reachable.

**Comment by dixudx** [comment]
@activeshadow You can try to append below content in `kubelet.service`.

```
[Install]
WantedBy=network-online.target
```

**Comment by activeshadow** [comment]
@dixudx will that do anything if I already have `Requires=network-online.target` in the `[Install]` section?

**Comment by dixudx** [comment]
@activeshadow  `Requires=network-online.target` means when `kubelet` gets activated, `network-online.target` will be activated as well. So this will not guarantee that when network is online, `kubelet` will be notified to start up.

However, `WantedBy=network-online.target` will try to start `kubelet` when network is reachable. Here `WantedBy` is preferred, instead of `RequiredBy`.

**Comment by activeshadow** [comment]
@dixudx ah hah... got it. Good to know! I will try it out ASAP.

So do I *only* need `WantedBy=network-online.target` or do I still need `After=network-online.target` as well?

**Comment by dixudx** [comment]
Only `WantedBy=network-online.target` will work.

**Comment by activeshadow** [comment]
Sorry @dixudx, what I meant to ask was do I still need `Requires` and `After` in the `[Unit]` section? I know this is more of a systemd question and less of a Kubernetes question...

**Comment by dixudx** [comment]
Actually in this scenario, only `WantedBy=network-online.target` is needed.

**Comment by activeshadow** [comment]
Great, I'll try it out and report back here ASAP. Thanks again @dixudx!

**Comment by activeshadow** [comment]
@dixudx OK so I tested this approach and it didn't seem to work. Here's how I tested:

1. Logged into CoreOS Container Linux locally (using `coreos.autologin=tty1`)
2. Edited the kubelet systemd service unit in the cloud-config, removing `Requires` and `After` from the `[Unit]` section and adding `WantedBy=network-online.target` to the `[Install]` section.
3. Disconnected the network cable
4. Rebooted the host and logged back in locally

At this point, there's no network connection due to the disconnected network cable. Running `systemctl status network-online.target` shows loaded, but inactive (dead). Running `systemctl status kubelet` shows active, and the kubelet logs show it not being able to connect to the K8s master. I would have expected kubelet.service to be in a loaded, but inactive (dead) state like network-online.target.

Just to test, I went back to my old config (`Requires` and `After` in the `[Unit]` section, no `WantedBy` in the `[Install]` section) and redid the test above. To my surprise, it worked as I had expected the above to work. After a reboot w/ no network connected, both network-online.target and kubelet.service were in a loaded, but inactive (dead) state. Once I plugged the network cable back in and it was configured via DHCP, both network-online.target and kubelet.service became active and the kubelet started up correctly.

This is actually unfortunate, because I'm now back at square one, and even worse, what I thought was the issue causing my kubelet connectivity to fail (kubelet starting before the network comes up) doesn't seem to be the case (or I just can't reproduce it).

Is there a scenario where the network is configured but the kubelet still can't reach the destination network (race condition perhaps)? Is there a reason why the kubelet application itself doesn't try to reconnect when a connection fails? I'm assuming it doesn't try to reconnect only because the kubelet logs can be showing `destination network unreachable` even when the network is configured and I can get out w/ `curl`, and once I restart kubelet.service the logs show successful connections.

**Comment by dixudx** [comment]
`WantedBy=network-online.target` will guarantee that when `network-online` gets activated, `kubelet` will be activated as well. However `kubelet` will always try to reconnect the apiserver and never stops until external intervention or internal errors.

If you want to a stronger relation between `network-online` and `kubelet`, you can try `RequiredBy=network-online.target` (a stronger version of `WantedBy`).

**Comment by activeshadow** [comment]
@dixudx I had also tried `RequiredBy` but that didn't change anything.

So I get what you're saying about how `WantedBy=network-online.target` will guarantee that when `network-online` gets activated, `kubelet` will be activated as well, but does it also guarantee that `kubelet` will *not* get activated *until* `network-online` is activated? What I really need is for `kubelet` to not get started until after `network-online` is active. `WantedBy` doesn't seem to do that, but having `Requires` and `After` in the `[Install]` section does seem to do that. So I guess I'll just stick with that, which is what I had originally.

Regarding the `kubelet` always trying to reconnect, I guess what I'm seeing happen is the `kubelet` tries to connect before the network is up and reports a `network is unreachable` error. It then continues to try to connect. But... even once the network is finally connected and routable, the `kubelet` continues to report the `network is unreachable` error and eventually starts to just report `Kubelet failed to get node info` over and over again.

Just not sure why this is... but it ends up leaving some of my nodes in a `NotReady` state. Sometimes a reboot fixes it, sometimes multiple reboots are required. Sometimes I have to remotely access the nodes and restart the `kubelet` service w/ `systemd`, which always fixes the problem as long as the network is routable, which makes me think there's some sort of race condition going on at boot, even with the `Requires` and `After` settings in place.

**Comment by activeshadow** [comment]
OK, so it looks like this isn't a network issue... see my [comment here](https://github.com/kubernetes/kubernetes/issues/35238#issuecomment-291044095).
