### ISSUE TITLE
--reconcile-cidr no longer available in k8s 1.6

### ISSUE THREAD

**Issue by tonylambiris** [kubernetes/kubernetes#43765]
What are the recommended flags for instantiating a stand-alone cluster using the kubenet plugin now that `--reconcile-cidr` has been removed from kubelet?

Thanks in advance.

**Comment by dchen1107** [comment]
Yes, the flag was deprecated for more than 2 releases, and removed from 1.6 Kubelet. Here is the related release-notes (https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v160)
```
The following deprecated kubelet flags are removed: --config, --auth-path, --resource-container, --system-container, --reconcile-cidr
```

**Comment by dchen1107** [comment]
btw, this flag has no effect since 1.5 release, especially you are using kubenet. Closing the issue for now. Please re-open it if you disagree it.

**Comment by tonylambiris** [comment]
I've been building tagged releases until v1.5.5-beta.0 until trying v1.6.0-beta.0, and what I can tell you is passing it to kubelet allowed services to be reached without any other special configuration except passing in `--pod-cidr=` as well.

**Comment by tonylambiris** [comment]
@dchen1107 Also I'm not a collaborator so I can't re-open this.
