### ISSUE TITLE
Table of kubernetes/examples/ Readme broken

### ISSUE THREAD

**Issue by VivekBhat** [kubernetes/kubernetes#43763]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

If this is a BUG REPORT, please:
  - The table in the readme for /examples is broken. 

**What happened**:
  - The table in the readme for /examples is broken. 

**How to reproduce it** (as minimally and precisely as possible):
  - Readme.md can be updated

**Comment by calebamiles** [comment]
Closing this issue as https://github.com/kubernetes/kubernetes/pull/43761 has merged.
