### ISSUE TITLE
fluentd.log not included in log rotation

### ISSUE THREAD

**Issue by bismarck** [kubernetes/kubernetes#43772]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): fluentd, logrotate

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.5.4

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- **Kernel** (e.g. `uname -a`): 4.4.41-k8s #1 SMP Mon Jan 9 15:34:39 UTC 2017 x86_64 GNU/Linux
- **Install tools**: kops
- **Others**:

**What happened**:
fluentd is writing its log to /var/log/fluentd.log which is causing disk to fill

**What you expected to happen**:
/var/log/fluentd.log should be added to node-level log rotation when cluster addon is installed

**How to reproduce it** (as minimally and precisely as possible):
Install fluentd-elasticsearch addon from https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch

**Anything else we need to know**:

**Comment by crassirostris** [comment]
@xiangpengzhao Thanks! On cos, it's included [automatically](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L169), but for the salt-based deployments that's indeed a bug, I'll fix it shortly
