### ISSUE TITLE
DaemonSet Creation/editing: Can't Set ".spec.template.spec.affinity"

### ISSUE THREAD

**Issue by waldman** [kubernetes/kubernetes#43785]
**Kubernetes version** (use `kubectl version`): 
Client: 1.5.4
Server: 1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): 
```PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/" 
```
- **Kernel** (e.g. `uname -a`): `Linux ip-10-249-41-68 4.4.41-k8s #1 SMP Mon Jan 9 15:34:39 UTC 2017 x86_64 GNU/Linux`
- **Install tools**: Kops
- **Others**:

**What happened**:
Im trying to run a DaemonSet only on worker nodes and not on master nodes. In order to do so I set the following on a DaemonSet configuration (as per https://kubernetes.io/docs/admin/daemons/#running-pods-on-only-some-nodes):
```    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
             matchExpressions:
             - key: kubernetes.io/role
               operator: NotIn
               values:
               - master
```

Once trying to create the resource, I got the following error message:
```error: error validating "kube-system/bundle-nginx-ingress-controller.yaml": error validating data: found invalid field affinity for v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false```

**What you expected to happen**:
I was expecting that the DaemonSet would be created with the proper affinity settings and that the pods would not be scheduled/ran on the master nodes.

**How to reproduce it** (as minimally and precisely as possible):
Try to create the following DaemonSet: 
```apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-ingress-controller
  namespace: kube-system
spec:
  template:
    metadata:
      namespace: kube-system
      labels:
        name: nginx-ingress-controller
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
             matchExpressions:
             - key: kubernetes.io/role
               operator: NotIn
               values:
               - master
      terminationGracePeriodSeconds: 60
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.8.1
        name: nginx-ingress-controller
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10249
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 80
        - containerPort: 443
        args:
        - /nginx-ingress-controller
        - --default-backend-service=kube-system/default-http-backend
```

On my clusters I have the following label set on the master nodes:
`kubernetes.io/role=master`

Thanks a lot and please feel free to ask for more details! :)

**Comment by dixudx** [comment]
The Kubernetes server (aka apiserver) you are using is `1.5.2`, which has not enabled `v1.Affinity`. You can visit [extensions_v1beta1.json](https://github.com/kubernetes/kubernetes/blob/v1.5.2/api/swagger-spec/extensions_v1beta1.json#L8027) for details.

The affinity/anti-affinity feature is currently in beta. You can try it after upgrading your apiserver version to `v1.6.0+`.

**Comment by kargakis** [comment]
You can still use affinity/anti-affinity features in 1.5 in the form of annotations.
@kubernetes/sig-docs-maintainers how can I access 1.5 docs?

**Comment by dixudx** [comment]
You can find the doc on [alpha-features-affinity-and-anti-affinity](https://github.com/kubernetes/kubernetes.github.io/blob/release-1.5/docs/user-guide/node-selection/index.md#alpha-features-affinity-and-anti-affinity). For examples, please visit [pod-with-node-affinity.yaml](https://github.com/kubernetes/kubernetes.github.io/blob/release-1.5/docs/user-guide/node-selection/pod-with-node-affinity.yaml).

**Comment by waldman** [comment]
I followed the example on: [pod-with-node-affinity.yaml](https://github.com/kubernetes/kubernetes.github.io/blob/release-1.5/docs/user-guide/node-selection/pod-with-node-affinity.yaml) and it worked as a charm. 

As this is apparently an unsupported feature of my K8s version, I'm closing the Issue. :(
