### ISSUE TITLE
Using assertions and require for sig-scheduling

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#43788]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

Using assert and require from https://github.com/kubernetes/kubernetes/tree/master/vendor/github.com/stretchr/testify can help us reduce the number of lines of code that we use for statements like err!=nil etc. Also, we can have negative test cases which can improve our code coverage using require. Some other SIG's have started using them.

**Comment by k82cn** [comment]
any example on improvement?

**Comment by ravisantoshgudimetla** [comment]
So, the documentation at https://github.com/stretchr/testify points out couple of things:

-There are may be scenarios where we want to fail the test. In golang, we do it through Fatal(which we are not using in most of our test cases). We can use require from testify package which solves this.
-Instead of checking for output and error, we can have a simple assert like: 
  assert.Equal(123, 123, "they should be equal"), assert.Nil(object) etc.

**Comment by jayunit100** [comment]
- agree w/ rgudi that it might be a minor improvement to the overall readability  .  
- but its also low priority, so we should flag it as p5 or whatever 
- probably a good help-wanted issue for new contributors or something.

**Comment by k82cn** [comment]
@jayunit100 , is there preferred test tools in k8s community? it seems more than one test tools here.

**Comment by adshmh** [comment]
Hi, if no one is working on this, I can submit a PR.

**Comment by ronaldpetty** [comment]
@ravisantoshgudimetla this still looking for a body?  I am happy to take a look if this is still desired.

**Comment by k82cn** [comment]
I think no one is working on this, but please send email to sig-scheduling mail list to confirm whether it's necessary?

**Comment by lichen2013** [comment]
Not everything is fixed, just partially fix I believe.

/reopen

**Comment by k82cn** [comment]
just help to reopen it :).

**Comment by wwsean08** [comment]
Seeing as nobody appears to be working on this I began working on it today and have a few of the files done, hope to have a pull request up soon of all of the scheduler tests being updated to use asserts.

**Comment by adshmh** [comment]
Could you please also note the PR I created for this and review if possible?
https://github.com/kubernetes/kubernetes/pull/52809

**Comment by misterikkit** [comment]
Anyone looking for more test cleanup work may be interested in #63267
