### ISSUE TITLE
Error while Initializing your master in kubernetes 1.6

### ISSUE THREAD

**Issue by Venkat-Sudharsanam** [kubernetes/kubernetes#43808]
Hi,

Im using Kubernetes latest version, 1.6
OS is Ubuntu 16.04

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
Im using the below tutorial

https://kubernetes.io/docs/getting-started-guides/kubeadm/

When i start Initializing your master, i got stuck with the below error

```
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.6.0
[init] Using Authorization mode: RBAC
[preflight] Running pre-flight checks
[preflight] Starting the kubelet service
[certificates] Generated CA certificate and key.
[certificates] Generated API server certificate and key.
[certificates] API Server serving cert is signed for DNS names [kubeadm-master kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 10.138.0.4]
[certificates] Generated API server kubelet client certificate and key.
[certificates] Generated service account token signing key and public key.
[certificates] Generated front-proxy CA certificate and key.
[certificates] Generated front-proxy client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/scheduler.conf"
[apiclient] Created API client, waiting for the control plane to become ready
[apiclient] All control plane components are healthy after 16.772251 seconds
[apiclient] Waiting for at least one node to register and become ready
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
```

Kindly help

**Comment by Scukerman** [comment]
+1 same here
**OS:** Ubuntu 16.04

**$ kubeadm version:**
```
kubeadm version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
**$ kubectl version:**
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
**$ kubelet --version:**
```
Kubernetes v1.6.0
```

**$ apt policy kubernetes-cni:**
```
kubernetes-cni:
  Installed: 0.5.1-00
  Candidate: 0.5.1-00
  Version table:
 *** 0.5.1-00 500
        500 http://apt.kubernetes.io kubernetes-xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

**$ journalctl -u kubelet:**
```
...
W0329 14:13:25.210489   17741 cni.go:157] Unable to update cni config: No networks found in /etc/cni/net.d
E0329 14:13:25.210703   17741 kubelet.go:2067] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
...
```

**Comment by stevenbower** [comment]
+1 having the same problem... at kubecon.. wondering if its an issue with the network here... debugging..

**Comment by stefan-gruettner** [comment]
+1 I'm facing the exact same issue.

Ubuntu 16.04.2 LTS

`kubeadm version
kubeadm version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by kristiandrucker** [comment]
Me too. The same as @stefan-gruettner

**Comment by stevenbower** [comment]
everyone on this ticket so far at kubecon?

**Comment by arthur0** [comment]
+1 Same Issue. Same config above.

**Comment by kristiandrucker** [comment]
Going to try to install 1.5.4 kubeadm, kubelet, kubeapi and then do apt upgrade to get latest version. It might work.

**Comment by stevenbower** [comment]
#41892 might be related i'm seeing this in my controller logs

```

I0329 14:40:12.683792       1 attach_detach_controller.go:223] Starting Attach Detach Controller
E0329 14:40:12.701671       1 actual_state_of_world.go:461] Failed to set statusUpdateNeeded to needed true because nodeName="n1"  does not exist
E0329 14:40:12.701706       1 actual_state_of_world.go:475] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true because nodeName="n1"  does not exist
I0329 14:40:12.749976       1 nodecontroller.go:633] Initializing eviction metric for zone:
W0329 14:40:12.750377       1 nodecontroller.go:956] Missing timestamp for Node n1. Assuming now as a timestamp.
I0329 14:40:12.750496       1 nodecontroller.go:822] NodeController detected that all Nodes are not-Ready. Entering master disruption mode.
I0329 14:40:12.766974       1 taint_controller.go:180] Starting NoExecuteTaintManager
I0329 14:40:12.776070       1 event.go:217] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"n1", UID:"15ab6a53-148d-11e7-a1c1-02ed55e681b9", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node n1 event: Registered Node n1 in NodeController
I0329 14:40:12.794223       1 disruption.go:277] Sending events to api server.
```

**Comment by cromark** [comment]
same issues
fyi @stevenbower .. not at i'm not at kubecon

**Comment by Scukerman** [comment]
It seems like it is kubeadm bug coz I found this: https://github.com/kubernetes/kubeadm/issues/212

**Comment by zuqiang** [comment]
same problem

**Comment by grodrigues3** [comment]
Looks related to #43815

**Comment by overip** [comment]
Same problem, same configuration. The only difference in my configuration is that I am running Ubuntu 16.04 Server on AWS. Could please someone of the kubernetes developer restore the old packages until you worked out the issue? This is a pretty big problem that does not allow to use k8s at all.

**Comment by mikedanese** [comment]
Dup of https://github.com/kubernetes/kubernetes/issues/43815

**Comment by samlinux** [comment]
Same problem, same configuration on a DigitalOcean droplet!

**Comment by Anson2048** [comment]
Same problem

**Comment by kristiandrucker** [comment]
@samlinux @Anson2048 check out this issue. https://github.com/kubernetes/kubernetes/issues/43815

**Comment by samlinux** [comment]
thanks I'm not sure what to do now? Could you lead me to the right solution?

**Comment by samlinux** [comment]
If I try to install the pod network with

kubectl apply -f http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/hosted/kubeadm/calico.yaml

the result is:
The connection to the server localhost:8080 was refused - did you specify the right host or port?

Any hints are appreciated

**Comment by Scukerman** [comment]
@samlinux, follow the guide: https://kubernetes.io/docs/getting-started-guides/kubeadm/
You missed this step:
```
Your Kubernetes master has initialized successfully!

To start using your cluster, you need to run (as a regular user):

  sudo cp /etc/kubernetes/admin.conf $HOME/
  sudo chown $(id -u):$(id -g) $HOME/admin.conf
  export KUBECONFIG=$HOME/admin.conf

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  http://kubernetes.io/docs/admin/addons/

You can now join any number of machines by running the following on each node
as root:

  kubeadm join --token <token> <master-ip>:<master-port>
```

**Comment by Venkat-Sudharsanam** [comment]
hi guys i need a help, actually i was in holiday. could any help me out what is the issue i'm facing and how it can be solved?
i checked 43815, but too many comments and didn't get it. So how to rectify the issue i'm facing?

**Comment by vdrizheruk** [comment]
Hi guys,

I have the same problem:

[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.6.0
[init] Using Authorization mode: RBAC
[preflight] Running pre-flight checks
[preflight] Starting the kubelet service
[certificates] Generated CA certificate and key.
[certificates] Generated API server certificate and key.
[certificates] API Server serving cert is signed for DNS names [kubeadm-master kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 10.138.0.4]
[certificates] Generated API server kubelet client certificate and key.
[certificates] Generated service account token signing key and public key.
[certificates] Generated front-proxy CA certificate and key.
[certificates] Generated front-proxy client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/scheduler.conf"
[apiclient] Created API client, waiting for the control plane to become ready
[apiclient] All control plane components are healthy after 16.772251 seconds
[apiclient] Waiting for at least one node to register and become ready
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet
[apiclient] First node has registered, but is not ready yet


I see that after kubeadm init.

My Environment: Ubuntu Server 16.04.2.

Is it possible to install previous version like 1.5.x ? If yes - how ?

**Comment by nomad-007** [comment]
Some problem Ubuntu 16.04.2 baremetal
kubeadm version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by nicky-lenaers** [comment]
Same issue on GKE. Any updates on this?

**Comment by arthur0** [comment]
@nomad-007 
I haven't any problem with Ubuntu 16.04.2 bare metal (kubeadm version 1.6.1)
I used Flannel as the overlay network.
You can view step-by-step here: https://asciinema.org/a/bfdhf5l56d4ovec9sv5gvko9e

**Comment by Scukerman** [comment]
@vdrizheruk, @nomad-007 you have to use kubernetes version >= `v1.6.1` via `--kubernetes-version` flag

**Comment by nicky-lenaers** [comment]
@Scukerman I don't see where I can use the flag `--kubernetes-version`. For creation clusters on Google Cloud there is a option for `--cluster-version=x.x.x.`. But `1.6.1` is not part of the [supported versions](https://cloud.google.com/container-engine/release-notes#supported_kubernetes_versions).

I currently use:
```sh
gcloud container clusters create my-cluster --zone=europe-west1-b --machine-type=f1-micro --num-nodes=3 --cluster-version=1.6.0
```

Note that also the `gcloud beta ...` command does not support `--kubernetes-version` flag. @Scukerman Could you clearify where to use the flag on cluster creation?

Thanks!

**Comment by Scukerman** [comment]
@nicky-lenaers this issue related to kubeadm. So I don't know if it fits your situation.
