### ISSUE TITLE
GOOGLE_APPLICATION_CREDENTIALS are sometimes not set 

### ISSUE THREAD

**Issue by joelharkes** [kubernetes/kubernetes#43801]
BUG REPORT 
In google cloud random pods sometimes have env key `GOOGLE_APPLICATION_CREDENTIALS` not set. (Using gcloud logging in AspNetCore).

Master version: 1.5.4
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:

> System.InvalidOperationException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

env variable `GOOGLE_APPLICATION_CREDENTIALS` is not set in pod 

**What you expected to happen**:

This should always be in pod, maybe it happens on kubernetes startup but it seems not the case, it seems to happen randomly.

**How to reproduce it** (as minimally and precisely as possible):

randomly add AspNetCore build images to kubernetes which log to Gcloud.

**Anything else we need to know**:

It seems very random when it happens. Some pods crash because it happens on startup, for other pods it happens only on kestrel requests so the requests fails because of this. but the pods keeps running.

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
/area platform/gce
since we lack a sig-gcp at the moment
