### ISSUE TITLE
SecurityContextDeny Admission Controller could be refactored

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubernetes#43812]
I found that [`SecurityContextDeny`](https://github.com/kubernetes/kubernetes/blob/72207db4552db94929fb760cca6373c1bd57a0ac/plugin/pkg/admission/securitycontext/scdeny/admission.go) could be improved:
- stale comment on `Admit()` function can be fixed (should also mention SupplementalGroups and FSGroup fields)
- we can extract function for checking `PodSecurityContext`
- we can extract function for checking `SecurityContext`

After extracting functions `Admit()` method will be shorter and easy to read, without duplicated code and verbose details.

CC @pweil-

**Comment by jetuuuu** [comment]
I'm going to prepare a fix for this.

**Comment by antoniaklja** [comment]
is it still valid? I see that a lot has changed.

cc @php-coder

**Comment by php-coder** [comment]
@antoniaklja I believe that it's invalid now because no one will accept PR: https://github.com/kubernetes/kubernetes/pull/45718#issuecomment-303722170
