### ISSUE TITLE
API server etcd preflight check swallows connection error

### ISSUE THREAD

**Issue by alexbrand** [kubernetes/kubernetes#43827]
Starting with v1.6.0, the API server has an etcd preflight check to make sure that it is able to connect to the etcd cluster.

Currently, if there is an issue connecting to etcd, the error is not being displayed to the user. Instead, a generic error message is being logged.

In order to improve usability and diagnosability, these connectivity errors should be logged so that the user can know exactly what is causing the preflight to fail.

I am happy to provide a PR once we agree on a path forward.

**Comment by jagosan** [comment]
/sig api-machinery

+1 for the idea.  In bug-scrub/triage session and this seems to be stale and not actionable as is. Proposal for how to move forward?
