### ISSUE TITLE
[Kubelet] Use objects from the external client consistently

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#43821]
Kubelet codebase is still using the internal client library which is resulting is a mess when re-using kubelet libraries across modules. We should either use the external client library everywhere or (better) define an internal pod object for kubelet and all its internal modules, including volume plugins, and use the internal version consistently.
If we do not address this soon enough, the codebase will become very confusing for contributors. 

cc @kubernetes/sig-node-feature-requests

**Comment by spiffxp** [comment]
/remove-priority P1
/priority important-soon
(I'm not actually sure this is the right priority, just trying to remove the old priority/PN labels)
