### ISSUE TITLE
kubeadm should allow custom manifests as part of initialization

### ISSUE THREAD

**Issue by kensimon** [kubernetes/kubernetes#43826]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

(TL;DR: if kubeadm supported `--initialization-manfest=path/to/network-plugin.yaml`, we wouldn't need to skip waiting for nodes to be ready like in https://github.com/kubernetes/kubernetes/pull/43824)

#43815 is tracking an issue with kubeadm where it doesn't proceed with cluster initialization because the nodes don't have working CNI configuration.

But the typical workflow encouraged by kubeadm is to first use `kubeadm init` to initialize your master, _then_ use `kubectl apply -f` to apply a valid CNI plugin like calico or weave after init has finished.

A workaround in https://github.com/kubernetes/kubernetes/pull/43824 was proposed that has kubeadm skip waiting for nodes to be ready, if and only if they're not ready due to a lack of CNI configuration.  This is obviously not ideal, because we're not doing a test "dummy" deployment, etc.

This could be fixed if kubeadm itself was responsible for configuring your networking plugin.  There's a few ways we could accomplish this:

1. Teach kubeadm about all the various network plugins out there and bake their configs into the binary
2. Accept a `--network-plugin-manifest"` option to kubeadm that lets you specify a URL or file to a network plugin
3. Accept arbitrary manifests (not just network plugins) as part of initialization, something like `--initialization-manifest`, and let users figure out that they need to specify a valid network provider's YAML/URL as the value for that, if they're relying on something like a DaemonSet for CNI configuration
4. Some other option, potentially involving the new phases feature?  (I'm being a bit hand-wavey here.)

Option 3 is probably the easiest to do now, and can be generally useful for more than just network providers, as DaemonSets may become more and more popular for configuring nodes.

**Comment by mikedanese** [comment]
Please use https://github.com/kubernetes/kubeadm for kubeadm issues.
