### ISSUE TITLE
Hundreds of pods with status "MatchNodeSelector"

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#43846]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**: 
- **Cloud provider or hardware configuration**: `OpenStack VM`
- **OS** (e.g. from /etc/os-release): `14.04.4 LTS, Trusty Tahr`
- **Kernel** (e.g. `uname -a`):`Linux xubuntu 3.16.0-73-generic #95~14.04.1-Ubuntu SMP Thu Jun 9 08:00:04 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**: `Manually`
- **Others**:

**What happened**:
Create a RC with replicas=1 and both "scheduler.alpha.kubernetes.io/affinity" and "nodeName" configured in the template but the two fields conflict, i.e., the node with nodeName doesn't fit the affinity. ~~After the RC being created, `kubectl get pods` shows there are hundreds of pods with status "MatchNodeSelector", and pods continue to be deleted and created.~~

_After the RC being created, `kubectl get pods` shows there are many pods with status "MatchNodeSelector", and the number of such pods keeps on growing. The newest pod's STATUS is shown as `Pending` and then changes to `MatchNodeSelector`. If the RC is deleted, these pods then disappears finally._

On one of our prod env with this issue, there were hundreds of such pods.

On my test env, I reproduce the issue, there are such pods:
```
NAME                    READY     STATUS              RESTARTS   AGE
rc-nginx-single-0h4ss   0/1       MatchNodeSelector   0          2s
rc-nginx-single-4sj7w   0/1       MatchNodeSelector   0          3s
rc-nginx-single-c4thp   0/1       MatchNodeSelector   0          9s
rc-nginx-single-f4rwr   0/1       Pending             0          1s
rc-nginx-single-fdw7d   0/1       MatchNodeSelector   0          4s
rc-nginx-single-n9r5c   0/1       MatchNodeSelector   0          6s
rc-nginx-single-tzmq8   0/1       MatchNodeSelector   0          3s
rc-nginx-single-xc4h5   0/1       MatchNodeSelector   0          4s
rc-nginx-single-zv9g0   0/1       MatchNodeSelector   0          2s
```

**What you expected to happen**:
RC stop to create a pod if such fields conflict,
or
Kube ignores affinity and nodeSeletor if nodeName is specified.

**How to reproduce it** (as minimally and precisely as possible):
Create such a RC as below (note that there is a node with nodeName in cluster)
kubectl get pods

**Anything else we need to know**:
```json
{
  "kind": "ReplicationController",
  "apiVersion": "v1",
  "metadata": {
    "name": "rc-nginx-single"
  },
  "spec": {
     "replicas": 1,
     "selector": {"name": "my-nginx"},
     "template": {
          "metadata": {
              "name": "nginx-template",
              "labels": {"name": "my-nginx"},
              "annotations": {
                "scheduler.alpha.kubernetes.io/affinity": "{\"nodeAffinity\": {\"requiredDuringSchedulingIgnoredDuringExecution\": {\"nodeSelectorTerms\": [{\"matchExpressions\": [{\"key\": \"app\", \"operator\": \"In\", \"values\": [\"test\"]}]}]}}}"
              }
          },
          "spec": {
              "nodeName": "192.168.1.220",
              "containers": [
                  {
                   "name": "nginx",
                   "image": "nginx",
                   "imagePullPolicy": "IfNotPresent"
                  }
                 ]
          }
      }
   }
}
```

**Comment by xiangpengzhao** [comment]
We might just ignore `podMatchesNodeLabels` in `PodSelectorMatches` if nodeName specified like [this](https://github.com/xiangpengzhao/kubernetes/commit/0b5ef7551acb76ec435a3c025140a1d060d4a155).

or, we should validate node conflict before RC creating a pod.

I tested both ways at v1.5.1 and they work well. I prefer the latter and will create a PR. Discussion is welcome.

**Comment by xiangpengzhao** [comment]
Dug into this issue again and found some clues.

>~~After the RC being created, kubectl get pods shows there are hundreds of pods with status "MatchNodeSelector", and pods continue to be deleted and created.~~

That pods continuing to be deleted and created was because I set improper values of some flags such as node-monitor-grace-period. In this case, node is not stable. Its status is monitored as ready and not-ready repeatedly by node controller. When it's monitored as not-ready, its pods are evicted.

After setting the value of those flags to default, the node status becomes stable. In this case, what I see is as below.
>After the RC being created, kubectl get pods shows there are many pods with status "MatchNodeSelector", and the number of such pods keeps on growing. The newest pod's STATUS is shown as Pending and then changes to MatchNodeSelector. If the RC is deleted, these pods then disappears finally.

The steps in code are mainly as below:
- Replication controller creates a new pod with conflicting nodeName and nodeAffinity spec. [CreatePodsWithControllerRef](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller.go#L465)
- kubelet watches and gets this pod directly without scheduler processing it because its nodeName is specified.
- kubelet handles pod additions. HandlePodAdditions will check if we can admit the pod.
 [canAdmitPod](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1966-L1970)
- In the admit process, [Admit](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/lifecycle/predicate.go#L52) will check if [PodSelectorMatches](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L657). In this issue, the admit fails.
- HandlePodAdditions rejects the pod. [rejectPod](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1966-L1970)
- In the rejectPod process, it invokes SetPodStatus and set pod Phase as [Failed](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1687).  **Note that the pod is not deleted here.**
- Replication controller finds that there is too few replicas and then creates a new pod. The new pod has the same fate. **Note that replication controller doesn't delete the preceding pod here**
- Then as we see, there are more and more failed pods.

I also test below cases:
- Solve the conflicting of nodeName and nodeAffinity by label the node to fit nodeAffinity, then a newly created pod will be successfully admitted and become running. But those failed pods still exist.
- Delete the replication controller, all failed pods will be deleted by garbage collector.

According to discussion in https://github.com/kubernetes/kubernetes/pull/43847, I have a solution but it may be not perfect. Will create a new PR to let folks review.

**Comment by xiangpengzhao** [comment]
cc @bsalamat @davidopp @deads2k @k82cn @kargakis

**Comment by davidopp** [comment]
As discussed in https://github.com/kubernetes/kubernetes/pull/43847/files#r109515252, I think the best solution is to have the controller notice that the pods it is creating keep getting rejected by kubelet with a "reason" that indicates kubelet admission failed, and rate limit creation of subsequent pods (until they start succeeding, at which time it would stop the rate limiting).

**Comment by kargakis** [comment]
@kubernetes/sig-apps-misc

**Comment by xiangpengzhao** [comment]
@davidopp Thanks David !
I'm not familiar with the mechanism of rate limiter. I create a PR #44608 but it seems like somewhat different from your suggested solution. I tested it, it can create a new pod in one sync; delete that failed pod in next sync and (may) trigger a rate limiter; create a new pod in the third sync; delete... repeatedly. 
Hope for you folks' further review. Thanks very much!

**Comment by kargakis** [comment]
There is some overlap between this issue and perma-failed deployments cc: @smarterclayton @mfojtik

**Comment by kargakis** [comment]
Related issues: https://github.com/kubernetes/kubernetes/issues/33041 https://github.com/kubernetes/kubernetes/issues/2529
