### ISSUE TITLE
kube-apiserver 1.6 can not write to etcd v2.3.1 (which is auto-downloaded during kube-up)

### ISSUE THREAD

**Issue by scottxusayhi** [kubernetes/kubernetes#43849]
kube-apiserver failed to start due to error write data to etcd v2.3.1 (connection reset)

Manually replace the etcd binary with v3.1.5 one solves the problem.

Note that the etcd 2.3.1 is auto selected and downloaded when I do KUBERNETES_PROVIDER=ubuntu ./kube-up.sh

**Kubernetes version** (use `kubectl version`):
1.6.0

**Environment**:
- **Cloud provider or hardware configuration**: Bare Metal
- **OS** (e.g. from /etc/os-release): Ubuntu 14.04
- **Kernel** (e.g. `uname -a`): 3.16.0-30
- **Install tools**: kube-up.sh
- **Others**:

**Comment by Scukerman** [comment]
My kube-apiserver (clustered up via kubeadm 1.6 using kubernetes 1.6) also can't write anything into etcd (3.0.17, default manifest for kubeadm).

I do `etcdctl ls /` and see nothing.

**Comment by nilsher** [comment]
I have the same problem with kubernetes 1.6 and etcd 3.0.17. I can see that the registry has been written to etcd's WAL files. But /registry can not be found when doing etcdctl ls /.

**Comment by luxas** [comment]
@Scukerman That's because the `etcdctl` tool defaults to using the V2 API. kubeadm v1.6+ uses the v3 API. Set `ETCDCTL_API=3` when using `etcdctl`.

@scottxusayhi The cluster/ubuntu kube-up.sh solution has been removed. Please use Canonical's Juju Charms solution or kubeadm instead
