### ISSUE TITLE
HardPodAffinitySymmetricWeight should be in scheduler policy config, not in KubeSchedulerConfiguration

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#43845]
(@bgrant0607 noticed this)

HardPodAffinitySymmetricWeight should be in the [scheduler policy config](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/api/v1/types.go), not in KubeSchedulerConfiguration

If/when fixing this, we need to be careful to do it in a backward-compatilble way.

@bsalamat @kubernetes/sig-scheduling-bugs

**Comment by k82cn** [comment]
Do you mean `PredicatePolicy`? It seems scheduler policy config's args can not passed to FitPredicates; it need to update related interface.

For the `backward-compatilble`: mark `HardPodAffinitySymmetricWeight` to be deprecated and set scheduler policy config to HardPodAffinitySymmetricWeight if policy config is empty.

**Comment by wanghaoran1988** [comment]
@k82cn Are you working on this? if no, I can take it.

**Comment by k82cn** [comment]
@wanghaoran1988 , nop; please go ahead.

**Comment by k82cn** [comment]
@bgrant0607 /@davidopp /@timothysc /@bsalamat  , When reviewing the PR, there's one question on `HardPodAffinitySymmetricWeight`: the default value of `HardPodAffinitySymmetricWeight` is 1,
which means the weight (1) will always add to priorities if term matched ([here](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/priorities/interpod_affinity.go#L163)), does it our expectation? And the user has to set it to 0 to disable it. IMO, the default value of `HardPodAffinitySymmetricWeight` should be 0.

**Comment by davidopp** [comment]
The value 1 (instead of 0) was chosen so that if you say A must run with B, there is an automatic preference that B should run with A. This seems like reasonable behavior.

**Comment by k82cn** [comment]
Thanks very much; reasonable case to me. But it seems we can not disable it: if set to 0, the default funcs will set it to default (1); similar result to un-set. Anyway, no user complain this now :).
