### ISSUE TITLE
Speed up pod watch by not create map

### ISSUE THREAD

**Issue by HardySimpson** [kubernetes/kubernetes#43843]
**Help reduce the watch CPU cost**:

Most CPU cost in apiserver's watch is on this [code](https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/pod/strategy.go#L190) with pprof test result

```
func PodToSelectableFields(pod *api.Pod) fields.Set {
	// The purpose of allocation with a given number of elements is to reduce
	// amount of allocations needed to create the fields.Set. If you add any
	// field here or the number of object-meta related fields changes, this should
	// be adjusted.
	podSpecificFieldsSet := make(fields.Set, 5)
	podSpecificFieldsSet["spec.nodeName"] = pod.Spec.NodeName
	podSpecificFieldsSet["spec.restartPolicy"] = string(pod.Spec.RestartPolicy)
	podSpecificFieldsSet["status.phase"] = string(pod.Status.Phase)
	return generic.AddObjectMetaFieldsSet(podSpecificFieldsSet, &pod.ObjectMeta, true)
}

```

As `make(fields.Set, 5)` is actually make a map, which is quite slow because there is memory allocation in it. And every time when pod had status change, it will go through this code and make watch slow.

The main way of avoid this cost is focus on the nodeName, if there is only a NodeName selector, don't call PodToSelectableFields and simply compare the pod's nodeName.

we have test that it could save about 20% CPU apiserver cost on over 2000 node in density test.

**Comment by HardySimpson** [comment]
@kubernetes/sig-scalability-pr-reviews

**Comment by timothysc** [comment]
@HardySimpson Could you submit a PR along with the benchmark test you used to perform your experiment?

**Comment by HardySimpson** [comment]
@timothysc yes, I have submit the PR and had some problems, still working on it.

**Comment by wojtek-t** [comment]
@HardySimpson - I'm not sure which release you were running your experiments on, but it was actually already fixed (not the way you suggested, but in more generic way).
It's more-or-less this PR that fixed it: https://github.com/kubernetes/kubernetes/pull/36889

To clarify, all the watches in the system (for a given resource) are served from apiserver watchcache. That said, with that PR we are computing all the selectable fields once for each pod and then reuse it to compute whether it matches or not a given selector.

To be honest, I don't see PodToSelectableFields method at all in our profiles now (though I agree it was significant part of it in the past). So closing as obsolete.

**Comment by HardySimpson** [comment]
@wojtek-t OK for close. If I can find other profile result in further will post it.
