### ISSUE TITLE
Failed to start ContainerManager failed to initialise top level QOS containers

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kubernetes#43856]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-1+c0b74ebf3ce26e-dirty", GitCommit:"c0b74ebf3ce26e46b5397ffb5ce71cd02f951130", GitTreeState:"dirty", BuildDate:"2017-03-30T08:19:21Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: openstack
- **OS** (e.g. from /etc/os-release): NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
- **Kernel** (e.g. `uname -a`): Linux kube-dev-master-2-0 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: ansible
- **Others**:

**What happened**: When creating new cluster with kubernetes 1.6.0 always two of three masters are going to notready state.

kubectl get nodes
NAME                  STATUS     AGE       VERSION
kube-dev-master-1-0   Ready      2m        v1.6.0
kube-dev-master-1-1   NotReady   2m        v1.6.0
kube-dev-master-2-0   NotReady   2m        v1.6.0
kube-dev-node-1-0     Ready      1m        v1.6.0
kube-dev-node-2-0     Ready      1m        v1.6.0

log files from kubelet is spamming:
Mar 30 15:20:44 centos7 kubelet: I0330 12:20:44.297149    8724 kubelet.go:1752] skipping pod synchronization - [Failed to start ContainerManager failed to initialise top level QOS containers: failed to create top level Burstable QOS cgroup : Unit kubepods-burstable.slice already exists.]

**What you expected to happen**: I except that masters should join to cluster

**How to reproduce it** (as minimally and precisely as possible): kubelet args

ExecStart=/usr/bin/kubelet \
  --kubeconfig=/tmp/kubeconfig \
  --require-kubeconfig \
  --register-node=true \
  --hostname-override=kube-dev-master-2-0 \
  --allow-privileged=true \
  --cgroup-driver=systemd \
  --cluster-dns=10.254.0.253 \
  --cluster-domain=cluster.local \
  --pod-manifest-path=/etc/kubernetes/manifests \
  --v=4 \
  --cloud-provider=openstack \
  --cloud-config=/etc/kubernetes/cloud-config

**After restart of machines everything is working normally, but restart of machine after installation was not needed before 1.6.0**

**Comment by youngdev** [comment]
Seeing the same issue on Red Hat Enterprise Linux Server 7.3
Kernel: 3.10.0-514.10.2.el7.x86_64    (Same as OP, so I'm suspecting the kernel might have something to do with it)

A reboot of the machine however seem to fix it.

**Comment by rootsongjc** [comment]
+1 Same issue on **CentOS 7.2.1511**
```
Apr 01 14:24:08 sz-pg-oam-docker-test-001.tendcloud.com kubelet[103932]: I0401 14:24:08.359839  103932 kubelet.go:1752] skipping pod synchronization - [Failed to start ContainerManager failed to initialise top level QOS containers: failed to create top level Burstable QOS cgroup : Unit kubepods-burstable.slice already exists.]
```

**Comment by xialonglee** [comment]
+1 This issue occasionally appears in CentOS 7.2
and a reboot could fix it.
It never happens in kubernetes v1.5.
Seems this message
```
 kubelet[9752]: I0410 08:04:30.122802    9752 kubelet.go:1752] skipping pod synchronization - [Failed to start ContainerManager failed to initialise top level QOS containers: failed to create top level Burstable QOS cgroup : Unit kubepods-burstable.slice already exists.]
```

are printed from the codes which imported from #41833 , so I tag you @sjenning @vishh @derekwaynecarr and sorry for troubling.

**Comment by sjenning** [comment]
Yes, I've seen this before if the kubelet doesn't clean up completely.

QoS level cgroups were enabled by default in 1.6 which explains why this may have not been observed earlier.

The QoS cgroups are created as transient systemd slices when using the systemd cgroup driver.  If those slices already exist, then container manager currently has a issue with that.

As I recall, a workaround that doesn't involve rebooting is `systemctl stop kubepods-burstable.slice`.  I believe this deletes the slice and allows the kubelet to recreate it.

@derekwaynecarr can we add code to check if the QoS level slices are already running and just move along in that case?

**Comment by vishh** [comment]
@sjenning AFAIK, the cgroups driver is idempotent around QoS cgroup creation. Systemd driver should behave the same way.

**Comment by derekwaynecarr** [comment]
@sjenning -- yes, we should have an exist check.

**Comment by sjenning** [comment]
Seems like this check for the cgroup already exists
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/qos_container_manager_linux.go#L108

So something is off here.  The absence of the cgroup does not imply the absence of the transient systemd slice apparently.

**Comment by derekwaynecarr** [comment]
@zetaab @youngdev @rootsongjc @xialonglee -- can you let me know the version of systemd used on the machines that have the problem (i.e. rpm -qa | grep systemd)  thanks!

**Comment by xialonglee** [comment]
@derekwaynecarr 
```
-bash-4.2# rpm -qa | grep systemd
systemd-sysv-219-30.el7.x86_64
systemd-219-30.el7.x86_64
systemd-libs-219-30.el7.x86_64
oci-systemd-hook-0.1.4-4.git41491a3.el7.x86_64
```
And sometimes i got log from kubelet
`Unit kubepods-besteffort.slice already exists`
which is different from `Unit kubepods-burstable.slice already exists`, it can't solved through 
`systemctl stop kubepods-besteffort.slice`, only a reboot can fix it.

I am not sure but when I 
1. deploy a HA(multi-masters) k8s-cluster, 
2. Kubelet on node run several static pods,
3. Uninstall k8s-cluster (delete all service files, like kubelet.service )
4. Reset systemd manager (systemctl daemon-reload, reset-failed, daemon-reexec)`

and reinstall k8s-cluster again, in this sistuation, it seems `kubepods-* already exists` problems more likely to happen.

**Comment by youngdev** [comment]
You are really looking for anything kubepod*.slice to stop which is how I resolved my issue:

Try this:

for i in $(/usr/bin/systemctl list-unit-files --no-legend --no-pager -l | grep --color=never -o .*.slice | grep kubepod);do systemctl stop $i;done

**Comment by xialonglee** [comment]
@youngdev 
Your method could solve the problem in many cases. But I face up a situation today: 
```
skipping pod synchronization - [Failed to start ContainerManager Unit kubepods.slice already exists.]
```
and 
```
systemctl list-unit-files --no-legend --no-pager -l | grep --color=never -o .*.slice
-.slice
machine.slice
system.slice
user.slice
```
so you can not stop any service start with prefix `kubepods` and the problem could not be solved.

I decide add kubelet args with `--cgroups-per-qos=false --enforce-node-allocatable=` to disabled qos enhance feature till this problem solved.

**Comment by ReSearchITEng** [comment]
Thanks @youngdev, after stopping all the node registered successfully.
I can confirm the issue is most likely due to reinstalling the kube* few times.

**Comment by xialonglee** [comment]
I think I might find the reason which cause the problem.
I check my docker configuration and find that `native.cgroupdriver=systemd ` was assigned to docker init args.
Disabled that arg of docker, all things run well.

**Comment by ReSearchITEng** [comment]
@rootsongjc - instead of changing the docker service file to fit kubelet, ain't better to fix the kubelet?

FYI, for a fully working k8s 1.6.1 with flannel, one may take/look at the kubeadm ansible playbooks.
Tested on Centos/RHEL. Preparations started for Debian based also (e.g. Ubuntu), but there might needs some refining.

https://github.com/ReSearchITEng/kubeadm-playbook/blob/master/README.md

PS: work based on sjenning/kubeadm-playbook - Many thanks @sjenning

**Comment by rootsongjc** [comment]
@ReSearchITEng I have no further good solution by now. Two method works:
- Reboot
- delete the `--native.cgroupdriver=systemd` in your **docker.service** file
Maybe you can try this as @youngdev  mentioned above
```
for i in $(systemctl list-unit-files --no-legend --no-pager -l | grep --color=never -o .*.slice | grep kubepod);
do systemctl stop $i;
done
```

**Comment by ReSearchITEng** [comment]
@rootsongjc the ansible code provided in the link above (kubeadm-playbook), it does both things:
1. updates the kubelet.service by adding "--native.cgroupdriver=systemd"  (this way it will match the default/existing docker.service)
2. it has also the systemctl stop *.slice implemented.

I am testing it very often, it works perfectly.

**Comment by jfpucheu** [comment]
Hello,

I got the same problem in CentOS Linux release 7.3.1611 (Core).

My workaround is to add:

ExecStopPost=/bin/bash -c "for i in $(systemctl list-unit-files --no-legend --no-pager -l | grep --color=never -o .*.slice | grep kubepod); do systemctl stop $i; done"

in /etc/systemd/system/kubelet.service.d/kubelet.conf

Jeff

**Comment by derekwaynecarr** [comment]
I debugged this further today.

I apologize for being dense on this issue.

I had previously fixed this in opencontainers/runc here:
see: https://github.com/opencontainers/runc/pull/1124

But the code we vendor in kube is missing this fix:
https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go#L285

It should be a simple godep update.

Apologies to all.

@sjenning -- any chance you can bump the godep and get a cherry pick?

**Comment by derekwaynecarr** [comment]
@sjenning -- i started a pr locally to bump the dep, but ran out of time today.  if you can bump today, that is fine, otherwise i will finish tomorrow.

**Comment by derekwaynecarr** [comment]
for reference, pulling master from opencontainer/runc does not merge cleanly, so when i wrap this tomorrow, i am going to try and pull https://github.com/opencontainers/runc/tree/v1.0.0-rc3 which appears to map cleaner.

**Comment by sjenning** [comment]
@derekwaynecarr attempting now

**Comment by sjenning** [comment]
Why you do this to me?!! :disappointed: 
https://github.com/opencontainers/runc/pull/1375

```
pkg/kubelet/cm/cgroup_manager_linux.go:323: cannot use *resourceConfig.Memory (type int64) as type uint64 in assignment
pkg/kubelet/cm/cgroup_manager_linux.go:326: cannot use *resourceConfig.CpuShares (type int64) as type uint64 in assignment
pkg/kubelet/cm/cgroup_manager_linux.go:332: cannot use *resourceConfig.CpuPeriod (type int64) as type uint64 in assignment
pkg/kubelet/cm/container_manager_linux.go:416: cannot use memoryLimit (type int64) as type uint64 in field value
pkg/kubelet/cm/container_manager_linux.go:417: constant -1 overflows uint64
```

**Comment by djsly** [comment]
Was this cherry-picked in 1.6 ? I can't seem to find any trace of it. Getting hit by this issue on centOS 7.3, fresh OS, fresh install of 1.6.6.

**Comment by sjenning** [comment]
@djsly it looks like 1.6 was using the same runc version as 1.7 before this PR.  I should be able to pick it if it gets approved.

@derekwaynecarr @vishh what do you think?

**Comment by djsly** [comment]
@sjenning that would be appreciated!  currently our automated pipeline is failing with a 50% rate due to this issue.

**Comment by ReSearchITEng** [comment]
I faced this and other issues. I have collected solutions for all of them under: https://github.com/ReSearchITEng/kubeadm-playbook/blob/master/reset.yml 

e.g. :
For this defect #43856 :
```
for i in $(/usr/bin/systemctl list-unit-files --no-legend --no-pager -l | grep --color=never -o kube.*\.slice );do echo $i; systemctl stop $i ; done
```
For defect: #39557 :
```
rm -rf /var/lib/cni/ /var/lib/kubelet/* /etc/cni/ ; ip link delete cni0 ; ip link delete flannel.1; ip link delete weave
```

**Comment by trunet** [comment]
@djsly did you manage to make this works?

I'm also running 1.7 with --cgroup-driver=systemd on RHEL 7.3 and during kubelet restart needed to pick new certificates every week, it fails and show "NotReady" on the node list.

the slice delete also didn't work. my only option is stop kubelet, stop docker, start docker, remove all stopped containers and start kubelet again, than it starts ok.

**Comment by djsly** [comment]
Try 1.6.7. They cherry picked the fix.  I haven't seen the issue after upgrading.

**Comment by trunet** [comment]
Unfortunately I can't because we're using some 1.7 new features. Will this fix be ported to 1.7?

**Comment by djsly** [comment]
hummI guess you might be getting affected by a new issue ? 

https://github.com/kubernetes/kubernetes/commit/a92007b43c939e2b4c1d72ee92be269074962437

Looks like 1.7.0 was the first branch to receive the runc bump.  1.6 was cherry picked after.

**Comment by trunet** [comment]
hmmm... interesting. I think this is a new bug. I will open a new issue about it

**Comment by jbunce** [comment]
Deploying via Kubespray I ran into a similar problem: https://github.com/kubernetes-incubator/kubespray/issues/1207#issuecomment-326297881

**Comment by mjaow** [comment]
@xialonglee  
you can try `systemctl -a --no-legend --no-pager -l | grep --color=never -o .*.slice|grep kube` and stop all slice display.

**Comment by qinzhao168** [comment]
3月 29 22:52:08 k8s-116 kubelet[28613]: F0329 22:52:08.775687   28613 kubelet.go:1359] Failed to start ContainerManager failed to initialize top level QOS containers: failed to update top level Burstable QOS cgroup : failed to set supported cgroup subsystems for cgroup [kubepods burstable]: Failed to find subsystem mount for required subsystem: pids


reboot can slove

**Comment by Icedroid** [comment]
centos 7.2 + kubernetes 1.14.6 + docker 18.09 has the save issue.
```
Sep 28 11:40:57 master1 kubelet: F0928 11:40:57.333277   29142 kubelet.go:1359] Failed to start ContainerManager failed to initialize top level QOS containers: failed to update top level Burstable QOS cgroup : failed to set supported cgroup subsystems for cgroup [kubepods burstable]: Failed to find subsystem mount for required subsystem: pids
Sep 28 11:40:57 master1 systemd: kubelet.service: main process exited, code=exited, status=255/n/a
Sep 28 11:40:57 master1 systemd: Unit kubelet.service entered failed state.
Sep 28 11:40:57 master1 systemd: kubelet.service failed.
```

reboot can slove

**Comment by freshman411** [comment]
> @ReSearchITEng I have no further good solution by now.
> These two method works for me:
> 
> * Reboot
> * add the `--native.cgroupdriver=systemd` in your **docker.service** file, make sure it is the same with `kubelet cgroup driver`.
>   Maybe you can try this as @youngdev  mentioned above
> 
> ```
> for i in $(systemctl list-unit-files --no-legend --no-pager -l | grep --color=never -o .*.slice | grep kubepod);
> do systemctl stop $i;
> done
> ```

我升级内核后问题解决了
