### ISSUE TITLE
Hundreds of pause containers running in the same pod

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#43851]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:'OpenStack VM'
- **OS** (e.g. from /etc/os-release):`14.04.4 LTS, Trusty Tahr`
- **Kernel** (e.g. `uname -a`):`Linux xubuntu 3.16.0-73-generic #95~14.04.1-Ubuntu SMP Thu Jun 9 08:00:04 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**:`Manually`
- **Others**:

**What happened**:
There are hundreds of pause containers running in the same pod.
```
CONTAINER ID        IMAGE                                      COMMAND             CREATED                  STATUS                  PORTS               NAMES
c08b72a73e83        gcr.io/google_containers/pause-amd64:3.0   "/pause"            Less than a second ago   Up Less than a second                       k8s_POD.d8dbe16c_rc-nginx-single-9ptd9_default_cb399fca-1523-11e7-ae68-fa163e09f30e_05fa7820
edb56312438b        gcr.io/google_containers/pause-amd64:3.0   "/pause"            2 seconds ago            Up 1 second                                 k8s_POD.d8dbe16c_rc-nginx-single-9ptd9_default_cb399fca-1523-11e7-ae68-fa163e09f30e_d791a4e0
3101a11067b0        gcr.io/google_containers/pause-amd64:3.0   "/pause"            4 seconds ago            Up 3 seconds                                k8s_POD.d8dbe16c_rc-nginx-single-9ptd9_default_cb399fca-1523-11e7-ae68-fa163e09f30e_585b96f4
3c416fa67746        gcr.io/google_containers/pause-amd64:3.0   "/pause"            6 seconds ago            Up 5 seconds                                k8s_POD.d8dbe16c_rc-nginx-single-9ptd9_default_cb399fca-1523-11e7-ae68-fa163e09f30e_a6be5223
f60ec5fe060b        gcr.io/google_containers/pause-amd64:3.0   "/pause"            8 seconds ago            Up 8 seconds                                k8s_POD.d8dbe16c_rc-nginx-single-9ptd9_default_cb399fca-1523-11e7-ae68-fa163e09f30e_874040ec
eabba571dfb5        gcr.io/google_containers/pause-amd64:3.0   "/pause"            10 seconds ago           Up 10 seconds                               k8s_POD.d8dbe16c_rc-nginx-single-9ptd9_default_cb399fca-1523-11e7-ae68-fa163e09f30e_d7895b4f
bb7e93a580d8        gcr.io/google_containers/pause-amd64:3.0   "/pause"            13 seconds ago           Up 12 seconds                               k8s_POD.d8dbe16c_rc-nginx-single-9ptd9_default_cb399fca-1523-11e7-ae68-fa163e09f30e_b8efe2a5
be9403cb6a7d        gcr.io/google_containers/pause-amd64:3.0   "/pause"            14 seconds ago           Up 13 seconds  
```

**What you expected to happen**:
Only one pause container running in a pod.

**How to reproduce it** (as minimally and precisely as possible):
https://github.com/kubernetes/kubernetes/blob/v1.5.1/pkg/kubelet/dockertools/docker_manager.go#L446
Set err to be a non-nil value here to simulate a race condition happening.
```go
			ip, err = dm.determineContainerIP(podNamespace, podName, iResult)
			// Kubelet doesn't handle the network error scenario
			if err != nil {
				status.State = kubecontainer.ContainerStateUnknown
				status.Message = fmt.Sprintf("Network error: %#v", err)
			}
```

**Anything else we need to know**:
On our prod env,  there is a "thick" CNI plugin which may cost seconds to SetUpPod. In such case, a [race condition](https://github.com/kubernetes/kubernetes/issues/25281#issuecomment-217591358) will cause pause status to be set to `ContainerStateUnknown` ([setting](https://github.com/kubernetes/kubernetes/blob/v1.5.1/pkg/kubelet/dockertools/docker_manager.go#L449)). The pod is recreated but its pause container will not be killed because it's not [running status](https://github.com/kubernetes/kubernetes/blob/v1.5.1/pkg/kubelet/dockertools/docker_manager.go#L2136). Then pod is going on being created again and again without pause container being killed.

**Comment by xiangpengzhao** [comment]
ref #29148 #30137 #30147 https://github.com/kubernetes/kubernetes/issues/25281#issuecomment-217591358

**Comment by yujuhong** [comment]
@xiangpengzhao the race condition should be fine because the kubelet will make sure it gets the latest state before syncing again. Unless your `SetUpPod` returns prematurely without setting up everything properly. This would cause kubelet to think that the infra container is defective and proceed to create another one.
