### ISSUE TITLE
Ability to rename namespace

### ISSUE THREAD

**Issue by whitecolor** [kubernetes/kubernetes#43867]
**Is this a FEATURE REQUEST?** 

I believe it is not possible now, but could be probably useful. Ability to rename (change symbolic name of) namespaces).

**Comment by bgrant0607** [comment]
@whitecolor This would be pretty hard, so I can't see us doing it.

**Comment by sasacocic** [comment]
what about now? Anything change?

**Comment by zakthan** [comment]
it would be very nice because deleting namespaces and recreating them you need to fix RBAC again

**Comment by darthenik** [comment]
Still nothing?

**Comment by sgandon** [comment]
indeed that would be nice to be able to pre-populate a namespace with some existing pods and just rename it whenever you need it in order to avoid the startup time of all the pods. 
This would be very usefull in a multitenant environment.

**Comment by rashmisingh85** [comment]
Is there any work around to rename the workspace other than deleting the existing one and creating new ?

**Comment by Macrame** [comment]
I hope to rename the namespace as it is very hard to delete the namespace and recreate all the pods especially them created by `cephadm`. Recreating pod will case much disagreeables.

**Comment by alitoufighi** [comment]
Closing an issue because "it is pretty hard" doesn't seem a way to face with issues to me.
I came to a situation where I need to recreate all resources on a namespace on another and deleting the other one, i.e. simply renaming it. It would be very useful if implemented.

**Comment by tobias-huebner** [comment]
#google where everything is possible

**Comment by fzyzcjy** [comment]
Months and years have passed... Is there any updates?

**Comment by skorobogatydmitry** [comment]
In my case, all resources in a given namespace was managed by helm + TF.
Keep your IaaC ;)

**Comment by Jayaram059** [comment]
any further thoughts to rename the namespace ?

**Comment by iinfotech006** [comment]
This would be a very important feature, we shouldn't have to destroy an entire namespace because of a little mistake in naming. Incase of installing nginx ingress with helm, you have to destroy the entire cluster if you made a mistake. Too bad

**Comment by mirusky** [comment]
What about now ? Have any updates ?

**Comment by pcgeek86** [comment]
My team installed a Helm Chart into a namespace, and started collecting data. Later on, I realized that the namespace did not have the desired name, but we cannot rename the namespace. This will create lots of extra work for us to have to destroy the Helm release, and install the new Helm release into a different namespace, while retaining all of our data.

**Comment by agonzalezm** [comment]
+1 this is would be very useful

**Comment by iamrahul127** [comment]
Please provide renaming of namespace feature
