### ISSUE TITLE
Not able to get kubelet-1.5.4 with kubeadm1.6. today

### ISSUE THREAD

**Issue by TapasBhattacharjee** [kubernetes/kubernetes#43869]
Due to a recent problem with kubelet-1.6, I had to revert back to kubelet-1.5.4 yesterday. When today I am trying to get kubelet-1.4.5 it is getting installed.  Now if I try to install kubeadm it is overriding kubele with the latest version of kubelet. Now if I uninstall the latest kubelet it is uninstalling the kubeadm. I don't remember seeing the same problem yesterday.

All the workaround given to latest kubeadm to work with latest kubelet is not working for me in CentOS 7.3. kubeadm is a big mess now. 

Is there a way to get only 
kubelet 1.5.4
kubernetes-1.6.0
kubeadm-1.6.0
I am using yum install -y kubelet-1.5.4 kubeadm-1.6.0 kubernetes-cni-0.5.1

**Comment by bostone** [comment]
I'm trying to do the same with v 1.5.4 and it seems that the only version of kubeadm that is available is 1.6.0 that is broken. Why was the earlier version(s) removed? Anyone can comment?

**Comment by TapasBhattacharjee** [comment]
I went ahead with manual installation this time with yum -y install etcd kubernetes flannel which works for me. I will wait for a fix on kubeadm and continue with manually configured cluster. The following link is a great resource for manual cluster deployment on CentOS:
http://khmel.org/?p=1080

**Comment by luxas** [comment]
/sig cluster-lifecycle

@TapasBhattacharjee kubeadm v1.6.4 works well. You should run the same version of kubeadm and kubelet (v1.6).

If you still experience this issue, please reopen this issue in the kubeadm repo https://github.com/kubernetes/kubeadm/issues
