### ISSUE TITLE
Could not find endpoints for service "kubelet" in namespace "kube-system". DNS records will be created once endpoints show up

### ISSUE THREAD

**Issue by JasonCrash** [kubernetes/kubernetes#43860]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
kubelet,  Could not find endpoints

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
No duplicates found.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Not a FEATURE REQUEST. Not sure if it is a BUG REPORT .

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.1-dirty", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"dirty", BuildDate:"2017-01-10T15:08:08Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/s390x"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.1-dirty", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"dirty", BuildDate:"2017-01-10T15:08:08Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/s390x"}

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04 (Xenial Xerus)"
- **Kernel** (e.g. `uname -a`): 
Linux baas-work01 4.4.0-13-generic #29-Ubuntu SMP Fri Mar 11 19:30:41 UTC 2016 s390x s390x s390x GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:

When I deployed alertmanager, grafana, kube-state-metrics, node-exporter, prometheus and prometheus-operator with kubernetes. My grafana and alertmanager could not get the pod's info. When I looked into the logs of kube-dns. I found the following message.

I0330 13:57:04.378884 1 dns.go:264] New service: node-exporter
I0330 13:57:04.378887 1 dns.go:548] Could not find endpoints for service "node-exporter" in namespace "monitoring". DNS records will be created once endpoints show up.
I0330 14:02:04.379680 1 dns.go:264] New service: kubelet
I0330 14:02:04.379687 1 dns.go:548] Could not find endpoints for service "kubelet" in namespace "kube-system". DNS records will be created once endpoints show up.

I tried "kubectl get ep --all-namespaces" , node-exporter and kubelet can not be seen either.
So I want to ask why kubelet and node-exporter failed to be added into endpoints list. How to fix it.

**What you expected to happen**:
I have another environment works well with same configuration and the two services are shown in end point list. The message in kube-dns are not found.

**How to reproduce it** (as minimally and precisely as possible):
Not Sure how to reproduce since I have a environment works well with same configuration.

**Anything else we need to know**:

**Comment by priyankadive** [comment]
we are facing same issue on azure cluster .

**Comment by RiaanLab** [comment]
Same here on K8S version 1.6.13 on a bare metal Debian 8 install.
