### ISSUE TITLE
Admission Controller: Enhance PodPreset to inject containers and init containers

### ISSUE THREAD

**Issue by andraxylia** [kubernetes/kubernetes#43874]
This is a feature request to add support in PodPreset for injecting containers and init containers.

Usecase: as a cluster admin, I need the ability to to inject an init container and a proxy sidecar container into a pod, to enable Istio microservices mesh functionality:
https://github.com/istio/istio

kubernetes/features#162
kubernetes/community#254
kubernetes/community#132

**Comment by therc** [comment]
Another use case: I want a PodPreset to add optionally an init container that fetches gdb/pprof and/or symbols before running the main container (which of course will have hooks to detect if the additional binaries/directories are present and act accordingly).

**Comment by ddysher** [comment]
Use case: before kubernetes supports logging volume, one option to collect log file is to add a fluentd side car container.

**Comment by mikecico** [comment]
Use case: Need to make a BCI jar and proxy agent available to containers via sidecar and shared volume, without modifying the target service containers.

**Comment by skurunji85** [comment]
This feature is exactly what i was looking for my work. I want to inject init container into POD spec based on some other setting during deployment. Can anyone tell me where to look to find the status of this feature.

**Comment by andraxylia** [comment]
We wanted to use this feature in Istio (istio.io), but we ended up using admission controllers (initializer and now dynamic webhooks).

I am afraid nobody is working on it.

**Comment by skurunji85** [comment]
Thanks andraxylia! I will look into admission controllers.

**Comment by scottrigby** [comment]
I don't want to change the lifecycle tag on #55410 so I'm linking to it from this direction.

**Comment by Alger7w** [comment]
So I should write and deploy webhook callback services for every functionality I want to inject into a Pod ?

**Comment by timothysc** [comment]
Please use mutating web-hooks for this type of behavior - 

https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/ 
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#admission-webhooks
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook

**Comment by mikecico** [comment]
It does seem like a natural fit.  Is there a reason why this shouldn't be allowed from a PodPreset?

**Comment by iwilltry42** [comment]
This project might be interesting for you: https://github.com/tumblr/k8s-sidecar-injector
I admit, that using PodPresets for this would be even better, but I think this also does a good job :+1:

**Comment by rcreasey** [comment]
I, too, would be interested in seeing this be possible in a PodPreset.

/reopen
/remove-lifecycle rotten
