### ISSUE TITLE
Rename register priority function2 in scheduler

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#43875]
Register priority function has Fixme suggesting to rename the function name(https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/plugins.go#L62). This is a small clean up task.

**Comment by k82cn** [comment]
If changed to `PriorityFunctionFactory2`, all "old" `PriorityFunctionFactory` need to split into map & reduce.
