### ISSUE TITLE
High EC2 DescribeInstance call volume: 1.2M calls a day

### ISSUE THREAD

**Issue by rickypai** [kubernetes/kubernetes#43873]
**BUG REPORT**:

Kubernetes is calling EC2 `DescribeInstance` too much, hitting rate limits. We currently have two Kubernetes clusters, prod and test. Both are running in HA with 3 masters each. Prod has about 30 minions while test has 3.

Our internal logging shows that the clusters are calling `DescribeInstance` 1.2M times a day. `Chef-KubernetesMasterProd`, `Chef-KubernetesMasterTest` are names of IAM roles for masters on each cluster:
![image](https://cloud.githubusercontent.com/assets/1469579/24526107/aeaf29d8-1551-11e7-8910-07f3856f725d.png)
The call volume is master only.

Since the call volumes between prod and test cluster are very similiar despite size of the cluster, this leads me to believe that the volume is not correlated to the size of the respective Kubernetes cluster, but possibly with the number of EC2 instances in the AWS account.

My reading of several code references in the AWS cloudprovider show that `describeInstances` is used in a few places uncached. Particularly, [`getCandidateZonesForDynamicVolume`](https://github.com/kubernetes/kubernetes/blob/a68c783dc8909a8b673bc8e4cbd045797bba98e8/pkg/cloudprovider/providers/aws/aws.go#L1098) use of `describeInstances` look particularly expensive. However, we only have have one use of PV in the cluster, and it hasn't been recreated for a while.

Other code paths and https://github.com/kubernetes/kubernetes/issues/31061 point to use of route tables and ELB-related concerns. But currently, we don't use any ELBs and currently don't have Route53 integration turned on as we are not yet in VPC. In fact, the master IAM roles are not whitelisted to read Route53.

It seems like the fix should be either trying to pinpoint the source of the call, then making it less expensive, or make a blanket cache on all `describeInstances` calls. Either way, we are open to provide help and additional information. We have a test cluster we can conduct tests on.

cc @justinsb 

**Additional information**:

**Kubernetes version** (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5", GitCommit:"894ff23729bbc0055907dd3a496afb725396adda", GitTreeState:"clean", BuildDate:"2017-03-23T16:14:43Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS EC2 non-VPC
- **OS** (e.g. from /etc/os-release):
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

- **Kernel** (e.g. `uname -a`):

```
$ uname -a
Linux i-0ac85a2fde6795696 4.4.0-38-generic #57~14.04.1-Ubuntu SMP Tue Sep 6 17:20:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

- **Install tools**: Cluster is provisioned manually (created pre-kops) with Chef recipes.

**Comment by hjacobs** [comment]
Yes, we are also running into AWS rate limits ([Zalando's Kubernetes on AWS](https://www.slideshare.net/try_except_/kubernetes-on-aws-at-europes-leading-online-fashion-platform)), there is a similar issue about AWS rate limits and caching: #39647

**Comment by chrislovecnm** [comment]
Is it the masters that are making the calls? Did you set the new flag on k-c-m?

**Comment by chrislovecnm** [comment]
I am on my phone, so I cannot look up the flag, but there is a k-c-m flag to adjust the interval for disk checks. It was introduced in 1.4.9 or 8

**Comment by rickypai** [comment]
`--pvclaimbinder-sync-period` on the controller-manager? that would make sense. will give it a try when I head to work tomorrow. thanks a ton!

**Comment by rickypai** [comment]
also yes. the call volume is master only. I'll add that information to the ticket.

**Comment by gnufied** [comment]
It is called `--attach-detach-reconcile-sync-period` which can be configured to higher number. 

Also we have made a number of fixes in 1.6 to improve api usage for aws.

**Comment by rickypai** [comment]
thank you. i will give that a try

**Comment by rickypai** [comment]
`--attach-detach-reconcile-sync-period` didn't actually fix our issue, but 1.6 have made it significantly better:

![pasted image at 2017_04_07 14_45](https://cloud.githubusercontent.com/assets/1469579/24885235/2d5fa88a-1e02-11e7-8ef3-3dfa0cb96b0d.png)

**Comment by rickypai** [comment]
thank you @chrislovecnm and @gnufied!

**Comment by chrislovecnm** [comment]
Can u share numbers with 1.5 vs 1.6?

**Comment by rickypai** [comment]
I'll pull the numbers and share those

**Comment by rickypai** [comment]
it seems like I misread my own graph... the call volume to `DescribeInstances` was about 1.6M/week and 200k/day before the upgrade.

After the upgrade, it's about 1.5k/day.

sorry for the delay.
