### ISSUE TITLE
No /registry written to etcd in kubernetes 1.6

### ISSUE THREAD

**Issue by nilsher** [kubernetes/kubernetes#43893]
Hello,
am working on an installation of kubernetes and upgraded to kubernetes 1.6 however after the upgrade(fresh install) I found that no data is written to etcd. "etcdctl ls /" do not show the registry.

I looked in the wal logs of etcd and I can see that there exists /registry entries there.
However calico and flannel entires are found when doing "etcdctl ls /".

I have tried this with kubernetes 1.6 and tried etcd(3.0.17 and 3.1.5).

kubectl get componentstatuses returns that all is ok.

Running on bare metal with my own ansible setup.
Kernel: 4.4.0-66-generic #87-Ubuntu

Have been reported in #43849 but seem the original issue is different there.

**Comment by nilsher** [comment]
I switched to --storage-backend=etcd2 on kube-apiserver and then the registry is created in etcd.
However I run etcd3 server.

**Comment by wojtek-t** [comment]
"etcdctl ls" doesn't work in etcd in v2 mode.

You should try something like:
```
ETCDCTL_API=3 etcdctl get ...
```

**Comment by nilsher** [comment]
etcd v3 does not support ls

*solved*
