### ISSUE TITLE
ResourceUsageGatherer in scalability tests is not working.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#43908]
Some time ago we noticed that we're not getting data anymore and filed #42045 expecting it was an RBAC issue. RBAC has been fixed, but we still don't get resource usage data, which suggests that the regression is somewhere else.

@kubernetes/sig-scalability-bugs @wojtek-t @shyamjvs

**Comment by shyamjvs** [comment]
Seems like we do have the resource usages available now:
- https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scalability/2216/artifacts/ResourceUsageSummary_density_2017-05-08T11:05:12-07:00.json (100-node gce)
- https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/410/artifacts/ResourceUsageSummary_density_2017-05-07T07:53:58-07:00.json (2k-node kubemark)

Was it something else you intended or the issue has been fixed?
