### ISSUE TITLE
 resource quota  can not be deleted after the  namespace has beed deleted

### ISSUE THREAD

**Issue by zouyee** [kubernetes/kubernetes#43901]
result like that:
```
[root@k8s-3 ~]# kubectl get resourcequota -n 123
NAME      AGE
123       35m
[root@k8s-3 ~]# kubectl delete resourcequota 123 -n 123
Error from server (NotFound): namespaces "123" not found
```

gc would not delete these resources.

**Kubernetes version** (use `kubectl version`):

1.5.2

**What happened**:

 resource quota  can not be delete after the  namespace has beed deleted

MY inspection:
delete resource quota which namespace has been deleted

**Comment by k82cn** [comment]
The "resourcequota" should be deleted when namespace deleted. Any steps on deleting namespace but resourcequota is NOT deleted

**Comment by zhouhaibing089** [comment]
@zouyee are you still seeing those data in etcd?

**Comment by zouyee** [comment]
etcd could not found those data,I think the reason lies in the cache
