### ISSUE TITLE
Multi-label CNAME record does not work via ExternalName Service

### ISSUE THREAD

**Issue by janosi** [kubernetes/kubernetes#43907]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): externalname

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Private PC
- **OS** (e.g. from /etc/os-release): NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- **Kernel** (e.g. `uname -a`): Linux centos-master 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**: I wanted to create an ExternalName Service with this descriptor
```
{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "myservice.namespace"
    },
    "spec": {
        "ports": [
            {
                "protocol": "TCP",
                "port": 6379,
                "targetPort": 6379
            }
        ],
        "type": "ExternalName",
        "externalName": "service.namespace2.svc.cluster.local"
    }
}
```
I got the following error message:
`The Service "myservice.namespace" is invalid: metadata.name: Invalid value: "myservice.namespace": must match the regex [a-z]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or 'abc-123')`

**What you expected to happen**:
I expected to have support for multi-label CNAME records, as per the value of "name".

**How to reproduce it** (as minimally and precisely as possible):
It is easy, just try to create ExternalName Service with multi-label  name.

**Anything else we need to know**:
Please let me know if you need more information.

**Comment by xiangpengzhao** [comment]
Currently a valid service name is in DNS1035Label format, i.e., `[a-z]([-a-z0-9]*[a-z0-9])?`
If we change the format, it might break something. Not sure about this.

/cc @smarterclayton 
/sig api-machinery
/sig network

**Comment by smarterclayton** [comment]
Names are not allowed to have dots in them.  We would not support this in general given design of services.
