### ISSUE TITLE
Autoscaling: accept min-nodes value of 0

### ISSUE THREAD

**Issue by fredrik955** [kubernetes/kubernetes#43911]
**FEATURE REQUEST**

It would be convenient to accept `min-nodes` to be equal to `0` for autoscaling on node-pools.
If you want to run a resource-intensive batch process now and then this will save a lot of costs.

**Comment by hjacobs** [comment]
@fredrik955 node autoscaling is not part of Kubernetes core, what autoscaler do you use? There are two options I know:

* https://github.com/kubernetes/contrib/tree/master/cluster-autoscaler
* https://github.com/hjacobs/kube-aws-autoscaler

**Comment by fredrik955** [comment]
@hjacobs That was unknown for me. I am using the first one.

**Comment by hjacobs** [comment]
@fredrik955 so I guess it makes sense to create an issue in the respective repo :smile:

**Comment by mwielgus** [comment]
For 1.7 we will have autoscaling for GCE. https://github.com/kubernetes/autoscaler/issues/43
For AWS we need community contribution https://github.com/kubernetes/autoscaler/issues/132
Azure support will come once we get https://github.com/kubernetes/autoscaler/issues/133 fixed.

Closing as duplicate/fixed.
