### ISSUE TITLE
Pods get the same IP address

### ISSUE THREAD

**Issue by pizzarabe** [kubernetes/kubernetes#43910]
**BUG REPORT**

I noticed that some of my pods crashed after restarting several nodes. The reason was always a failed probe. E.g. `Liveness probe failed: Get http://10.1.22.18:9090/: dial tcp 10.1.22.18:9090`

After checking the pods I found some of them with the exact same IP address like other pods 
For example my dashboard:
```

$ ./kubectl get pod -o wide --all-namespaces
default         busybox-3674381263-1xm2c                   1/1       Running            0          4m        10.1.22.18      10.169.1.136
...
kube-system     kubernetes-dashboard-2668982082-tbtt9      0/1       CrashLoopBackOff   6          4h        10.1.22.18      10.169.1.136
```

I found 10 pods with the exact same IP address (full list: https://gist.github.com/pizzarabe/4a15d626e5626fd85eee5d12f8c0108b )

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5", GitCommit:"894ff23729bbc0055907dd3a496afb725396adda", GitTreeState:"clean", BuildDate:"2017-03-22T00:23:49Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5+coreos.0", GitCommit:"e2cd7718ba844e874a68aa13f8f5bb0728b415bb", GitTreeState:"clean", BuildDate:"2017-03-22T01:59:35Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
Bare-Metal on ESXi
- **OS** (e.g. from /etc/os-release):
`CoreOS 1298.5.0`
- **Kernel** (e.g. `uname -a`):
`Linux alien1 4.9.9-coreos-r1 #1 SMP Tue Feb 28 00:06:10 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz GenuineIntel GNU/Linux`
- **Others**:
I am using flannel to get a overlay network (with vxlan) and calico for network policy

**How to reproduce it** (as minimally and precisely as possible):

I have no idea how to reproduce that... I found https://github.com/openshift/origin/issues/13543 (Openshift uses k8s, correct?)

**Comment by brenix** [comment]
We had this issue too and were able to resolve it by ensuring `/var/lib/cni` was persisted across kubelet restarts.

For example, we added the following to our `kubelet.service` systemd unit to first create a directory on the host:
`ExecStartPre=/usr/bin/mkdir -p /var/lib/cni`

and then we added the following mount to the `RKT_RUN_ARGS` or `RKT_OPTS`:
```
--volume=var-lib-cni,kind=host,source=/var/lib/cni --mount volume=var-lib-cni,target=/var/lib/cni
```

After restarting the host, we are no longer seeing duplicate IPs

**Comment by pizzarabe** [comment]
@brenix Thanks! This resolved my Problem :)

I will close that, bc it does not seems like a k8s issue.
@emptywee opened a pull to fix that issue in CoreOS (thanks for that)
