### ISSUE TITLE
Use nodeinfo cache for getting node's taints information instead of computing it everytime.

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#43912]
We are computing the taints on node from node spec, every time in taints_tolerations at

https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/priorities/taint_toleration.go#L71

Instead we can use node info cache's taints field for faster lookup.

https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/schedulercache/node_info.go#L53

**Comment by jayunit100** [comment]
@ravisantoshgudimetla my usual comment measure twice + cut once :), can we demonstrate the performance hit here, or is there another issue that summarizes this defect?

**Comment by ravisantoshgudimetla** [comment]
#35117 - This is the one, I was refering to.

**Comment by jayunit100** [comment]
How are we  measuring or confirming the performance improvement  here ?
