### ISSUE TITLE
Failed to pull image with "x509: certificate signed by unknown authority" error

### ISSUE THREAD

**Issue by rushilpaul** [kubernetes/kubernetes#43924]
**BUG REPORT**

**Kubernetes version** :

Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS**: CentOS Linux 7
- **Kernel**: Linux kubernetes-master-3302 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**What happened**:
I used the below command to create a POD:
`kubectl create --insecure-skip-tls-verify -f monitorms-rc.yml`
I get this `monitorms-mmqhm                0/1       ImagePullBackOff`

and upon running
  `kubectl describe pod monitorms-mmqhm --namespace=sample`
It said `Warning		Failed		Failed to pull image "10.78.0.228:5000/monitorms": Error response from daemon: {"message":"Get https://10.78.0.228:5000/v1/_ping: x509: certificate signed by unknown authority"}`

There is no certificate mentioned anywhere in my deployment configuration anywhere.

10.78.0.228 is running a private insecured docker registry.
Should Kubernetes not ignore the server certificate with that --insecure-skip-tls-verify flag ?

**Comment by rushilpaul** [comment]
I have asked the question here: http://stackoverflow.com/q/43150437/969784

**Comment by nkaravias** [comment]
Your CA needs to get added in your local trust store even if you're using --skip-tls-verify.

**Comment by dixudx** [comment]
@rushilpaul 
* First `--insecure-skip-tls-verify` is not a valid argument for `kubectl create`;
* Actually `x509 error` is on `docker` side. The daemon failed to pull image from that insecure registry. You can refer to [insecure docker registry](https://docs.docker.com/registry/insecure/) on how to trust/skip the registry security.

**Comment by rushilpaul** [comment]
@dixudx I forgot to mention it. I installed the server certificate globally on this kubernetes master node and then restarted the docker service. After that I am successfully able to manually pull that image using `docker pull 10.78.0.228:5000/monitorms`

So I'm still confused about why I'm getting that error, if it coming from docker side.

**Comment by rushilpaul** [comment]
@dixudx Also, the kubernetes help text lists `--insecure-skip-tls-verify` as one of the "global" options and says that it can be passed to any Kubernetes command

**Comment by supereagle** [comment]
`--insecure-skip-tls-verify` just skips the server's certificate verification, not docker registry, so it can not solve the problem. The error is from Docker daemon while pulling image.

> I installed the server certificate globally on this kubernetes master node and then restarted the docker service running on it. 

Maybe you should try the command `docker pull 10.78.0.228:5000/monitorms` on the k8s nodes which hold the pod, not the k8s master.

**Comment by liggitt** [comment]
That is a valid arg to `kubectl create` but just controls trust between kubectl and the API server

The pull error is between the node and the docker registry. The node either needs to trust the certificate or treat that registry as an untrusted registry (which makes the node tolerate TLS verification errors)

**Comment by rushilpaul** [comment]
@supereagle I am going to add the insecure registry option to the docker configuration file on the k8s nodes. Hopefully that should do the trick

**Comment by pompomJuice** [comment]
You would think that this is solved by now. 

**CA Certificates**

Actual recorded cases of preventing unauthorized access : **ZERO**
Amount of countless of developer time wasted because of noobs that don't integrate CA certs into their systems properly: **millions of man hours.**

Morel of the story. Ditch CA certs. Such a ballache every time you have try to get tooling to work together. Nobody knows how it works. Nobody. Not even kubernetes.

**Comment by ReSearchITEng** [comment]
should anyone face it while using directly the gcr.io, one possible situation is that CA certificates on your machine are too old.
```console
docker pull gcr.io/google_containers/kube-apiserver-amd64:v1.7.2
Trying to pull repository gcr.io/google_containers/kube-apiserver-amd64 ...
Get https://gcr.io/v1/_ping: x509: certificate signed by unknown authority '
```
solution that worked for me on RH/CentOS:
```console
yum check-update ca-certificates; (($?==100)) && yum update ca-certificates || yum reinstall ca-certificates
update-ca-trust extract
```

**Comment by liggitt** [comment]
cc @kubernetes/sig-node-bugs for image pulling issue

if you go to the node in question and try `curl -v https://gcr.io/v1/_ping`, do you see a successful response?

**Comment by srossross-tableau** [comment]
Any update on this issue? this is hitting us now.

**Comment by pompomJuice** [comment]
@srossross-tableau 

As far as I remember this was a docker issue, not a kubernetes one. Docker does not use linux's ca certs. Nobody knows why. 

You have to install those certs manually so that docker can use them:

I thought this was a docker issue not a kubernetes one:

`/etc/docker/certs.d/mydomain.com/ca.crt`

**Comment by srossross** [comment]
@pompomJuice, could this be a minikube image issue. I am not able to even curl this site

```sh
minikube ssh -- curl -I https://storage.googleapis.com
curl: (60) SSL certificate problem: self signed certificate in certificate chain
```

```sh
$minikube logs
...
Nov 08 18:19:06 minikube localkube[3032]: E1108 18:19:06.788101    3032 remote_image.go:108] PullImage "gcr.io/google_containers/heapster:v1.3.0" from image service failed: rpc error: code = 2 desc = error pulling image configuration: Get https://storage.googleapis.com/artifacts.google-containers.appspot.com/containers/images/sha256:f9d33bedfed3f1533f734a73718c15976fbd37f04f383087f35e5ebd91b18d1e: x509: certificate signed by unknown authority
..
```

**Comment by pompomJuice** [comment]
Exactly my point. That curl error is just plain wrong. It is telling you that you have the certificates but they are self signed. I find that highly unlikely. 

That means that that error message is just plain wrong. This connects with my previous point that almost nobody implements this stuff correctly.

**Comment by Nick-Harvey** [comment]
I'm running into the same issue. Certs are from digicert, kubernetes cluster running in GCE, certs installed through the host and put in /etc/docker/certs.d/, and still x509 error. 

Docker logs:
`TLS handshake error from XXXXXXXXXX: remote error: tls: bad certificate`


Kub version:
`Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`

host: 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by pompomJuice** [comment]
Paste the entire folder name in '/etc/docker/certs.d/' please.

It should work if **all** your nodes have that cert installed.

**Comment by Nick-Harvey** [comment]
root@kubernetes-minion-group-96k7:/etc/docker/certs.d/"foo.bar.com":5000# ll
total 16
drwxr-xr-x 2 root root 4096 Dec  2 20:43 ./
drwxr-xr-x 3 root root 4096 Dec  2 20:07 ../
-rw-r--r-- 1 root root 3332 Dec  2 20:23 domain.crt
-rw-r--r-- 1 root root 1675 Dec  2 20:43 domain.key

So far only one node in the cluster :)

**Comment by pompomJuice** [comment]
Change those to ca.crt and ca.key

**Comment by Nick-Harvey** [comment]
Changed them to ca.crt and ca.key both in the directory, as well as updated the files called out in the secret . I restarted docker service on the node and redeployed the pods and still, same error.

**Comment by pompomJuice** [comment]
I made a mistake, the one should be **client.key** not **ca.key**.

It should work. 

Double check by trying to start the image manually on the box.

**Comment by Nick-Harvey** [comment]
That didn't seem to work either :( same error

**Comment by pompomJuice** [comment]
What happens when you try to start the docker container manually from command line?

**Comment by Nick-Harvey** [comment]
should I use kubectl run on one of the nodes or docker run? docker run, the container starts but I get connection refused. If I use kubctl, `error: failed to discover supported resources: an error on the server ("") has prevented the request from succeeding`

If I used kubectl on my local machine that's leveraging kubectl proxy, the container starts but I get the following: 
 http: server gave HTTP response to HTTPS client

kubectl command: kubectl run --image=registry:2 devreg-test2 --port=5000 --env="DOMAIN=cluster, REGISTRY_HTTP_ADDR=0.0.0.0:5000, REGISTRY_HTTP_TLS_CERTIFICATE=/certs/ca.crt, REGISTRY_HTTP_TLS_KEY=/certs/client.key" --expose=true

**Comment by pompomJuice** [comment]
Try the following. 

Make your own docker registry. Use gitlab for this it is free.

Host some images on it on http. Try to start a pod with this image. Then verify that the docker you are looking at is in fact running that pod. If it is then you know you have the correct node.

Then like before `docker run` and explain to me what you mean by connection refused.

**Comment by www44** [comment]
working solution for pulling docker image from Artifactory (certificate is selfsigned):
- put all used ca certs in /usr/local/share/ca-certificates
- run update-ca-certificates
- restart docker daemon (sudo service docker restart)

**Comment by clns** [comment]
> should anyone face it while using directly the gcr.io, one possible situation is that CA certificates on your machine are too old.
> 
> ```
> docker pull gcr.io/google_containers/kube-apiserver-amd64:v1.7.2
> Trying to pull repository gcr.io/google_containers/kube-apiserver-amd64 ...
> Get https://gcr.io/v1/_ping: x509: certificate signed by unknown authority '
> ```
> 
> solution that worked for me on RH/CentOS:
> 
> ```
> yum check-update ca-certificates; (($?==100)) && yum update ca-certificates || yum reinstall ca-certificates
> update-ca-trust extract
> ```

This actually worked for me.

**Comment by tmiklas** [comment]
I run kubernetes on RancherOS as part of Rancher 2.x setup and have private registry that is not internet facing, so I have to use self-signed certificate on it, resulting in x509 error. I read this thread and few others and the solved the issue - sharing in case it may help someone, if not directly then by suggesting possible path. 

This worked for me - http://www.ctrl-alt-del.cc/2018/11/solution-rancher-2-k8s-private-registry.html

**Comment by Alcasser** [comment]
> You would think that this is solved by now.
> 
> **CA Certificates**
> 
> Actual recorded cases of preventing unauthorized access : **ZERO**
> Amount of countless of developer time wasted because of noobs that don't integrate CA certs into their tooling properly: **gasmillions of man hours.**
> 
> Moral of the story. Ditch CA certs. Such a ballache every time you have try to get tooling to work together. Nobody knows how it works. Nobody. Not even kubernetes. Software that use it never work. In the end you just copy all the certs to every machine and your toaster just so you don't get that god damn **x509: certificate signed by unknown authority** bullshit error every bloody time you try to do any tooling.
> 
> Now I have to go and drill right to the core of this fucking cluster to get those certs installed, because kubernetes's secrets for handling docker is just plain useless. Who gives a shit of configuring a base64 representation of a username and password when the x509 will stop you anyway. I will tell you. Nobody.
> 
> Just use the money that would have been spent trying to get the bloody CA certs to work and hire a henchman with an axe that [cut the hardlines](https://www.youtube.com/watch?v=K8HPJiGktio) when the hacker comes. Fuck this CA certs it's not security if it does not let authorized people in because the entire field is just one giant BUG that will JAM your tooling.

I cry everytime.

**Comment by MrAmbiG** [comment]
2020 and still the same issue. 
private harbor registry.
docker pull works with no problem.
ls /etc/docker/certs.d/registry.myharbor.com/ shows up the certificate.
kubernetes fails to pull images with imagepullbackoff error.
It is 3 years and kubernetes still has this issue. Very disappointing.

**Comment by MrAmbiG** [comment]
***Solved***
1. Make sure you are able to do a `docker pull IMAGENAME` from the machine where you are running the deployments (yaml files, helm packages etc.,)
2. On all the kubernetes nodes make sure the following is present `/etc/docker/certs.d/my-private-registry.com/my-private-registry.com.crt`

**Comment by armourshield** [comment]
I am working in my local dev environment
```
    OS:
       Ubuntu (bionic) 18.0.4 LTS    
    Minikube Version:
       v1.11.0
    Docker Version:
       19.03.10
```

I am using Jfrog Container Registry as registry to my minikube. I am able do the following:

 1. docker login localhost:443 | or | ip-add:443
 2. docker push ip-add:443/docker-local/test:latest
 3. docker pull ip-add:443/docker-local/test:latest

I have configured Jfrog Container Registry to run behind Nginx Reverse Proxy listening on port 443. Created self-signed certs and Jfrog is using these certs.

Configured docker to use the self-signed certs as follows.

 1. Create certs, copy it to /usr/local/share/ca-certificates/
 2. sudo update-ca-certificates
 3. copy the certificate to /etc/docker/cert.d/192.168.0.114:443/ca.crt
 4. restarted the docker, just be sure

Configure K8 to use the docker login secret by .yaml file as following:

 1. base64 encode ~/.docker/config.json
 2. use it in the following template
 ```
apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: awesomeapps
data:
  .dockerconfigjson: UmVhbGx5IHJlYWxseSByZWVlZWVlZWVlZWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGxsbGx5eXl5eXl5eXl5eXl5eXl5eXl5eSBsbGxsbGxsbGxsbGxsbG9vb29vb29vb29vb29vb29vb29vb29vb29vb25ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubmdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2cgYXV0aCBrZXlzCg==
type: kubernetes.io/dockerconfigjson
```

In the deployment.yaml, I use ImagePullSecrets and the name flag.

Now after all this setup where the docker pull is working on terminal, I get error on the pods saying x509 IP Sans.

I went through lot of documentation and K8 issues, replicated the step of https://github.com/kubernetes/kubernetes/issues/43924#issuecomment-631533150

replicated the steps didn't work out. Can anyone let me know what I am doing wrong? and how can I correct it.

**Comment by matt-palmer-tfs** [comment]
I am also having the same issues, but on EKS in this case. I am using a daemonset to deploy a privileged workload to attempt the fixes above on all nodes to solve this problem (images are on a private signed registry).

**Comment by davehouser1** [comment]
Same issue.

I don't understand what I am missing.
We have a private registry, and a private openssl CA.
I  followed all instructions [here](https://docs.docker.com/registry/insecure/)
Mainly the following
- Created certs for each master and nodes. Included SAN fields for short host name and FQDN. Included SAN for IP address.
- Move the private, public, and root ca's files to specific /etc/docker/my-private.registry.domain.name/
- Made sure they were named accordingly. 
- Uploaded the root ca cert to the Ubuntu store location and updated.

Same error every time `x509: certificate signed by unknown authority`

Does docker check the SAN fields? How do I get more log output then just `x509: certificate signed by unknown authority`

**Comment by sxt26** [comment]
for x509: certificate signed by unknown authority

https://gitlab.com/stirumala/kubernetes/-/blob/main/findings.txt

**Comment by unixoff** [comment]
Don't forget to execute after changes
```
systemctl restart docker
systemctl restart containerd
```

**Comment by phomlish** [comment]
@unixoff THANKS.

I did this a gazzilion times:
```
systemctl restart docker
```

when I did this it worked:
```
systemctl restart docker
systemctl restart containerd
```

**Comment by minhhungit** [comment]
These commands work for me, run them on all nodes include master node

```
sudo cp /opt/certs/registry.crt /usr/local/share/ca-certificates/docker-registry.crt
sudo update-ca-certificates

sudo systemctl restart docker
sudo systemctl restart containerd
```

Ref: https://docs.docker.com/registry/insecure/#docker-still-complains-about-the-certificate-when-using-authentication

**Comment by ben-yacine** [comment]
> sudo systemctl restart containerd

I have passed more than one day to figure out why it's not working even after following all the steps i found. But restarting the containred was the last thing to do for it to work. Thanks for sharing.

**Comment by valkiriaaquatica** [comment]
Just in case someone has this problem, check first which kubernetes distribution you are running, is not the same solution for RKE2, Openshift... or old versions who run docker nistead of containerd, minikube... For example for RKE2 is this. https://docs.k3s.io/installation/private-registry
