### ISSUE TITLE
Disable unsecured localhost in all testing

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#43932]
We should eventually disable unsecured localhost for all of our tests. This should turn up instances where unsecured localhost is used. Then we should write a test that tries to use unsecured localhost and is expected to fail, so we get a signal if it is ever re-enabled. 

wrt https://github.com/kubernetes/kubernetes/pull/40050#discussion_r104735453

also #43931

**Comment by liggitt** [comment]
yes, getting to this stage will ensure any addon used in a test env is capable of working against a secured server

**Comment by PrasadG193** [comment]
I would like to work on this if this is still relevant.

**Comment by mtaufen** [comment]
I don't believe we've made any progress on it. @liggitt can correct me if I'm wrong about that.
Try disabling the insecure ports and see what happens.

**Comment by liggitt** [comment]
Some progress, but not a lot. I know @dekkagaijin is working on switching some of the stragglers to use client config and speak to the secured port.

**Comment by dekkagaijin** [comment]
As of https://github.com/kubernetes/kubernetes/pull/77447, `-gce` test API servers have their insecure port disabled.

**Comment by liggitt** [comment]
great, didn't realize we were so close

**Comment by dekkagaijin** [comment]
It might just be kubemark that still spins up an API server with the insecure port enabled

**Comment by dekkagaijin** [comment]
Longstanding work item! I M P A C T!
/cc @mwwolters

**Comment by tallclair** [comment]
What work remains here?

**Comment by liggitt** [comment]
support for unsecured localhost was removed in #95856 in 1.20

/close
