### ISSUE TITLE
Symlink in writable volume overwritten

### ISSUE THREAD

**Issue by bitmage** [kubernetes/kubernetes#43938]
If I mount a secret as a volume in `/etc/secrets`, then symlink a file from another volume during my startup command, the symlink gets removed sometime during the container startup lifecycle.

This is sort of strange and inconvenient, and results in additional steps and symlinking in order to combine secrets volumes that need to end up in the same destination.

Please see [reproduceable configuration here](https://github.com/bitmage/kube-volume-symlink).

In response to request by @thockin in https://github.com/kubernetes/kubernetes/issues/19764#issuecomment-290610816

**Comment by thockin** [comment]
@saadali @pmorie - this SHOULD work, right?
