### ISSUE TITLE
NodePort service will hang if no pod behind the service

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#43944]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
master

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
1) Create a deployment with a NodePort service and the service works well.
```
[root@bd002 ~]# kubectl get svc
NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)        AGE
kubernetes   10.0.0.1     <none>        443/TCP        17d
my-nginx     10.0.0.227   <nodes>       80:32589/TCP   5d
[root@bd002 ~]# kubectl get deploy
NAME       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
my-nginx   1         1         1            1           5d
[root@bd002 ~]# curl bd002:32589
my-nginx-1427292677-cs58x-v1
```
2. Scale down the deployment pod number to 0
```
[root@bd002 ~]# kubectl scale --replicas=0 deploy/my-nginx
deployment "my-nginx" scaled
[root@bd002 ~]# kubectl get deploy
NAME       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
my-nginx   0         0         0            0           5d
```
3. Query the service again, it will hang.
```
[root@bd002 ~]# curl bd002:32589

```

**What you expected to happen**:
The service should return 404 as there is no pod available.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by justinsb** [comment]
NodePort is a layer 4 concept (TCP).  If you want a 404, that is Layer 7 (HTTP).  You should probably be using ingress.

**Comment by gyliu513** [comment]
Thanks @justinsb , but the problem is that when query the service if there is no pod behind, then the service will hang, do you have any suggestions/comments for this? I think at least the service should not hang here.

**Comment by cblecker** [comment]
@gyliu513 As NodePort is a layer 4 networking concept, a hang/timeout when there is nothing available to answer the request is expected. As @justinsb mentions, if you need a layer 7 application level response, then something like an ingress would be better.

**Comment by gyliu513** [comment]
I see, thanks @justinsb @cblecker
