### ISSUE TITLE
using network plugins “cni”: cni config unintialized; Skipping pod

### ISSUE THREAD

**Issue by xilu0** [kubernetes/kubernetes#43957]
hi,
      I created the kubernetes cluster 1.6.0 by using kubeadm kubeadm init.
I am getting error messages in /var/log/messages.
**ubelet: W0402 05:41:21.534772   20797 cni.go:157] Unable to update cni config: No networks found in /etc/cni/net.d
 kubelet: E0402 05:41:21.534946   20797 kubelet.go:2067] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized**
**The DNS pod is failing:**
`kube-system   kube-dns-2247936740-j5rtc        0/3       ContainerCreating   21         1h`
I was in accordance with the official documents;
[](https://kubernetes.io/docs/getting-started-guides/kubeadm/)
what can i do?
Please help me!

**Comment by yujuhong** [comment]
See #43815. Closing this as a duplicate.
