### ISSUE TITLE
Make the kubeadm on the release-1.6 a little bit more stable

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#43950]
~~I think we should push kubeadm `1.6.1-beta.0.5+d8a384c1c5e35d-00` to the stable branch of the deb/rpm packages for now (that includes https://github.com/kubernetes/kubernetes/pull/43835#issuecomment-290531847), but consider renaming it `1.6.0` or something temporarily this week until v1.6.1 is released.~~

~~Why rename? Because v1.6.1-beta.0 > v1.6.1 in debs, which is stupid in this context
Why promote an "unstable" version? So we can fix the other issues we're seeing on master, have some time to test HEAD of release-1.6 while still patching most of the users meanwhile this week before v1.6.1 is actually released.~~

What issues are we seeing currently that maybe should be fixed on the release-1.6 branch?
 - https://github.com/kubernetes/kubernetes/pull/43835 broke self-hosting, ref: https://github.com/kubernetes/kubernetes/pull/43835#issuecomment-290531847, https://github.com/kubernetes/kubernetes/issues/43949
 - It would be preferable to clean up `/var/lib/dockershim` correctly: https://github.com/kubernetes/kubernetes/pull/43917
 - `kubeadm reset` is broken when the docker service is disabled

@mikedanese @jbeda @yujuhong @lukemarsden @pipejakob

**Comment by liggitt** [comment]
Renaming releases is a little crazy making when it comes to support questions

**Comment by civik** [comment]
Still seeing:

`Apr  3 22:11:04 ttck8infc1001 kubelet: error: failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is different from docker cgroup driver: "systemd"`

On a Cent7 install.

**Comment by luxas** [comment]
@liggitt agree, that was just the last resort we could take to if not releasing v1.6.1 directly (which we did, and that made half of this issue obsolete)

Now updated to current status

**Comment by luxas** [comment]
This was fixed with v1.6.2
