### ISSUE TITLE
ebtables filtering rules to filter out arp spoofing

### ISSUE THREAD

**Issue by ravilr** [kubernetes/kubernetes#43953]
kubernetes clusters using shared linux bridge networking(docker, flannel, kubenet?) for connecting the containers with in the same host are prone to cross-container man-in-the-middle attacks through arp spoofing/poisoning.
here is an issue reported against lxc: https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/1548497

I'm not sure whether this falls in the realm of CNI network plugins or kubernetes. But, it would be a nice step towards a secure multi-tenant cluster to enable ebtables filtering rules by kubelet sync loop to disallow ethernet traffic out of the container with MAC/ip address that was not assigned to the container.

@thockin @smarterclayton

**Comment by thockin** [comment]
I think this should fall into CNI

@dcbw @freehan

**Comment by dcbw** [comment]
@thockin @ravilr I'd agree, it should be an option for the CNI 'bridge' plugin to do this.

**Comment by thockin** [comment]
Another option that has come up a couple times was to fix the parts of the
system that rely on this.  E.g. add services as local addresses in pod
netns.  I am sure it would break SOMETHING, but maybe it would be net
simpler?

**Comment by manjotpahwa1** [comment]
@jingax10
