### ISSUE TITLE
Support incremental scale for deployment 

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#43954]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
The `kubectl scale` only support the following scale but no incremental scale.

```
  Examples:
  # Scale a replicaset named 'foo' to 3.
  kubectl scale --replicas=3 rs/foo

  # Scale a resource identified by type and name specified in "foo.yaml" to 3.
  kubectl scale --replicas=3 -f foo.yaml

  # If the deployment named mysql's current size is 2, scale mysql to 3.
  kubectl scale --current-replicas=2 --replicas=3 deployment/mysql

  # Scale multiple replication controllers.
  kubectl scale --replicas=5 rc/foo rc/bar rc/baz

  # Scale job named 'cron' to 3.
  kubectl scale --replicas=3 job/cron
```

It is better introduce the following to support incremental scale.
```
# Scale a replicaset by increasing 1 for rs named 'foo'.
kubectl scale --replicas-increment=1 rs/foo
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by adohe** [comment]
```
kubectl scale --current-replicas=2 --replicas=3 deployment/mysql
```
kind of like this. @kargakis wdyt?

**Comment by kargakis** [comment]
@gyliu513 can you elaborate on what are you trying to achieve with incremental scaling? Usually you want to scale up/down based on some metrics. HPA and custom metrics may be something that interests you.
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

**Comment by gyliu513** [comment]
@kargakis @adohe What I want here is a `incremental  scale` but not as current behavior. Currently, we can only specify the expected scale number but not the `incremental number`.

I have such as scenario: In some cases, the workload in a cluster is expectable, so that the end user want to use a cron job to scale up the application, such as increase by two pods each hour etc, make sense?

**Comment by gyliu513** [comment]
cc @kubernetes/sig-autoscaling-feature-requests @kubernetes/sig-autoscaling-misc

**Comment by DirectXMan12** [comment]
So, what you actually want is just a quick way from `kubectl` to increase the scale by one?  Perhaps we should have the equivalent of `kubectl get scale` so this is easier to implement outside of kubectl? 

@kubernetes/sig-cli-misc do we have any store around exposing more generic access to subresources?

**Comment by pwittrock** [comment]
Why not use `kubetctl get` with [json path](https://kubernetes.io/docs/tasks/kubectl/list-all-running-container-images/) to pull out the current replica count and increment the value?

**Comment by DirectXMan12** [comment]
can we `kubectl get` the scale subresource?  It would be nice to do this generically -- that's what the scale subresource is for.  Nothing says that replicas will be in the same place on all scalable resources.

**Comment by adohe** [comment]
@DirectXMan12 I am afraid we cannot do this now.

**Comment by pwittrock** [comment]
@DirectXMan12 There is an issue for creating `kubectl view` commands for exactly this sort of thing.  LMK if you would be interested in picking it up.

**Comment by smarterclayton** [comment]
We should also support `kubectl get --subresource scale` eventually.  But
not today.

On Wed, Apr 12, 2017 at 12:44 PM, Phillip Wittrock <notifications@github.com

**Comment by gyliu513** [comment]
Some questions:

1) `kubectl get scale`, does this mean that we are going to introduce many `scale` objects/resources and `hpa` is just one of them?

2) How does the `kubectl get scale` help for this `incremental scale`?

**Comment by DirectXMan12** [comment]
> does this mean that we are going to introduce many scale objects/resources and hpa is just one of them

`/scale` is actually a subresource on the scalable resources themselves, like deployments and replicationcontrollers.  It's not on the HPA.  The HPA makes use of `/scale` as does the `kubectl scale` command.

> How does the kubectl get scale help for this incremental scale?

If I'm understanding you correctly, you want an operation like `scale++`, which actually is `scale = scale + 1`.  Right now, there's no way to get the scale easily across different objects from the cluster (which is what the `/scale` subresource is supposed to be for).  If you do, you could do something like:

```bash
SCALE=$(kubectl get scale deploy/foobar)
kubectl scale deploy/foobar --replicas=((SCALE+1))
```

**Comment by DirectXMan12** [comment]
@pwittrock maybe at some point.  Not right at the moment ;-)

**Comment by shiywang** [comment]
@DirectXMan12 @pwittrock  I would like to take a look at this, but currently just some jobs in hand, maybe next week.
