### ISSUE TITLE
kubelet 1.6 looks for CNI binaries in wrong path

### ISSUE THREAD

**Issue by r0bj** [kubernetes/kubernetes#43967]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: bare-metal
- **OS** (e.g. from /etc/os-release): Ubuntu 14.04
- **Kernel** (e.g. `uname -a`):  Linux dev-k8s-controller-p1 4.4.0-53-generic #74~14.04.1-Ubuntu SMP Fri Dec 2 03:43:31 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: chef cookbook
- **Others**: Docker 1.12.6, calico 2.1

CNI binaries:
```
/opt/cni/bin/
├── calico
├── calico-ipam
├── flannel
├── host-local
└── loopback
```

kubelet config:
```
 /usr/bin/kubelet \
    --register-schedulable=false \
    --pod-manifest-path=/etc/kubernetes/manifests \
    --node-labels=k8s-role=k8s-controller \
    --allow-privileged=true \
    --api-servers=https://dev.kubernetes-controller.service.consul:6443 \
    --cloud-provider= \
    --cluster-dns=10.223.0.10 \
    --cluster-domain=cluster.local \
    --container-runtime=docker \
    --docker=unix:///var/run/docker.sock \
    --network-plugin=cni \
    --network-plugin-dir=/etc/cni/net.d \
    --kubeconfig=/var/lib/kubelet/kubeconfig \
    --serialize-image-pulls=false \
    --tls-cert-file=/var/lib/kubernetes/kubelet-cert.pem \
    --tls-private-key-file=/var/lib/kubernetes/kubelet-key.pem \
    --v=2
```

**What happened**:
When trying to run pod error message is generated:
```
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----				-------------	--------	------		-------
  9m		9m		1	kubelet, dev-k8s-controller-p1			Warning		FailedSync	Error syncing pod, skipping: failed to "CreatePodSandbox" for "fluentd-node-agent-kbrw4_kube-system(9813fecc-17df-11e7-9c75-5254009ef6db)" with CreatePodSandboxError: "CreatePodSandbox for pod \"fluentd-node-agent-kbrw4_kube-system(9813fecc-17df-11e7-9c75-5254009ef6db)\" failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod \"fluentd-node-agent-kbrw4_kube-system\" network: failed to find plugin \"loopback\" in path [/opt/loopback/bin /etc/cni/net.d]"

  9m	2s	45	kubelet, dev-k8s-controller-p1		Normal	SandboxChanged	Pod sandbox changed, it will be killed and re-created.
  9m	2s	45	kubelet, dev-k8s-controller-p1		Warning	FailedSync	Error syncing pod, skipping: failed to "KillPodSandbox" for "9813fecc-17df-11e7-9c75-5254009ef6db" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"fluentd-node-agent-kbrw4_kube-system\" network: failed to find plugin \"calico\" in path [/etc/cni/net.d /opt/calico/bin]"
```

So it seems that kubelet is trying to find CNI binaries in paths:
- /opt/loopback/bin
- /etc/cni/net.d
- /opt/calico/bin

But it should look at `/opt/cni/bin` since this is the default valur for `--cni-bin-dir` parameter.

**What you expected to happen**:
Pod starts.

**How to reproduce it** (as minimally and precisely as possible):
Run pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
```

with kubelet 1.6 and CNI binaries in those path (default for calico):
```
/opt/cni/bin/
├── calico
├── calico-ipam
├── flannel
├── host-local
└── loopback
```

**Anything else we need to know**:
After copy `/opt/cni` to `/opt/calico` and `/opt/loopback` pod starts fine.

**Comment by xilu0** [comment]
@r0bj Good, very helpful to me

**Comment by supereagle** [comment]
When set `--network-plugin-dir` and not set `--cni-bin-dir`, default path of CNI binaries `/opt/cni/bin` will not take effect, the path specified by `--network-plugin-dir` will be used instead.

We should use `--cni-conf-dir` and `--cni-bin-dir` instead of `--network-plugin-dir` if use CNI plugin.

**Comment by freehan** [comment]
I will push a PR to deprecate the `--network-plugin-dir` flag. It is confusing. Closing this issue.

**Comment by bboreham** [comment]
> I will push a PR to deprecate the --network-plugin-dir flag. It is confusing. Closing this issue.

Was that #43995?  It was closed without merging.

I agree `--network-plugin-dir` should be deprecated.

**Comment by supereagle** [comment]
I think #43995 is needed before `--network-plugin-dir` is removed. 

The `--network-plugin-dir` flag is still not deprecated, I will send a PR to deprecate it.
