### ISSUE TITLE
SNI documentation is backwards for (certs,keys) and for (certs, keys:domains)

### ISSUE THREAD

**Issue by deitch** [kubernetes/kubernetes#43961]
**Is this a request for help?** No

**What keywords did you search in Kubernetes issues before filing this one?**  SNI Cert Key order

---

**Is this a BUG REPORT or FEATURE REQUEST?** Bug Report

**Kubernetes version** 1.6

**Environment**: (irrelevant but still)
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS 1298.7.0
- **Kernel** (e.g. `uname -a`): 4.9.16-coreos-r1
- **Install tools**: downloaded and installed k8s directly

**What happened**: According to the api server docs at https://kubernetes.io/docs/admin/kube-apiserver/ (and still consistent in latest source):

```
      --tls-sni-cert-key namedCertKey                           A pair of x509 certificate and private key file paths, optionally suffixed with a list of domain patterns which are fully qualified domain names, possibly with prefixed wildcard segments. If no domain patterns are provided, the names of the certificate are extracted. Non-wildcard matches trump over wildcard matches, explicit domain patterns trump over extracted names. For multiple key/certificate pairs, use the --tls-sni-cert-key multiple times. Examples: "example.key,example.crt" or "*.foo.com,foo.com:foo.key,foo.crt". (default [])
```

The examples all show the key _before_ the certificate file, and it is called "multiple key/certificate pairs". However, the API server actually requires the key _after_ the certificate per https://github.com/kubernetes/kubernetes/blob/3843108081bf3444ac638d41c3546916fdc2af86/staging/src/k8s.io/apiserver/pkg/util/flag/namedcertkey_flag.go#L58

**Anything else we need to know**:

Quite confusing. Please update the docs to be correct.

**Comment by liggitt** [comment]
@sttts

**Comment by deitch** [comment]
Updated the title. It also is backwards for the `:`-separated order of domains vs cert-key pairs.

According to https://github.com/kubernetes/kubernetes/blob/e2c0bf3fcae754201e7e89be8b825eb142a36907/staging/src/k8s.io/apiserver/pkg/util/flag/namedcertkey_flag.go#L46 , the keycert is `cs[0]` and the domains are `cs[1]`, but the docs say "suffixed" followed by examples of the domain _before_ the keycert pair::

```
      --tls-sni-cert-key namedCertKey                           A pair of x509 certificate and private key file paths, optionally suffixed with a list of domain patterns which are fully qualified domain names, possibly with prefixed wildcard segments. If no domain patterns are provided, the names of the certificate are extracted. Non-wildcard matches trump over wildcard matches, explicit domain patterns trump over extracted names. For multiple key/certificate pairs, use the --tls-sni-cert-key multiple times. Examples: "example.key,example.crt" or "*.foo.com,foo.com:foo.key,foo.crt". (default [])
```
