### ISSUE TITLE
[proposal] kubectl port-forward listen on custom address

### ISSUE THREAD

**Issue by goblain** [kubernetes/kubernetes#43962]
Implementing this proposal that will solve issues raised in https://github.com/kubernetes/kubernetes/issues/36152 and https://github.com/kubernetes/kubernetes/issues/29678. In short: allow binding on addresses other then currently supported `127.0.0.1` and `::1`

The idea is to implement a new method `NewOnAddress` in pkg/client/unversioned/portforward/portforward.go that will add an address parameter, and refactor `New` as a wrapper on the `NewOnAddress` pointing to "localhost" address.

The `NewOnAddress` would work as `New` did previously (that is calling `listenOnPortAndAddress`) with a difference of setting the new PortForwarder private variable `address` that can take string representations of IPv4, IPv6, "localhost" or nil. Then `listenOnPort` will be changed in a way that if IPv4 or IPv6 is provided in `PortForwarder.address`, the address given wil be the only one used (if it is a valid one). If value "localhost" or nil is passed, it will behave exactly as it does now - listening on `127.0.0.1` and `[::1]`.

pkg/kubectl/cmd/portforward.go will be modified to call `NewOnAddress` method instead of `New` with new option address provided by `-a` or `--address` flag on `kubectl port-forward` command and passed via a new string variable `Address` in updated PortForwardOptions type.

**Comment by goblain** [comment]
@kubernetes/sig-cli-proposals

**Comment by cblecker** [comment]
@kubernetes/sig-cli-misc

**Comment by fabianofranz** [comment]
The CLI part of the proposal looks fine to me, being concise with `kubectl proxy`. Adding @kubernetes/sig-api-machinery-misc for the client-go bits.

**Comment by CMajeri** [comment]
Hi,
I'd be pretty interested in this feature. Is someone currently working on it? @goblain's explanations are spot-on and I could apply them if noone else feels like it.

**Comment by goblain** [comment]
https://github.com/kubernetes/kubernetes/pull/46517 has implementation (needs a rebase after all that time) but it was put on hold due to feedback from @smarterclayton . No idea if the blocking work was completed so awaiting for confirmation before I invest time in the rebase/refactor.

**Comment by CMajeri** [comment]
I have no idea how I missed that PR, I'll follow that.

Thanks for the work too, it would really be a nice feature to have!

**Comment by chadnickbok** [comment]
@goblain The work has been completed:
https://github.com/kubernetes/kubernetes/pull/33684

And implemented in the java client at least:
https://github.com/kubernetes-client/java/pull/91

Its frustrating that this very reasonable change was blocked because "other stuff is happening" - other stuff is always happening, and not being able to control the binding address is ridiculous.

**Comment by stefanasseg** [comment]
+1

**Comment by gopinatht** [comment]
+1

**Comment by goblain** [comment]
well, I've stopped rebasing the https://github.com/kubernetes/kubernetes/pull/46517 pull request cause it seems there is no will to merge it in foreseeable future.

**Comment by vladimirvivien** [comment]
@goblain are you planning to keep pushing for this to get merged ? I think this is still needed.  Just ran into that issue.

**Comment by goblain** [comment]
the decision to go with this is way above me, so I am unable to influence this further. Seems like there simply is no will to merge this into upstream in near future

**Comment by pentaphobe** [comment]
+1 here too

Has anyone worked out a reliable workaround in the meantime?

**Comment by Baykonur** [comment]
+1. Till this is implemented or merged, ssh tunneling can be used on a (yet another) separate terminal (assuming port 8000 is not used on any interface on the host and assuming `kubectl post-forward a-pod 8888:8080` executed before):
`sudo ssh -N -L 0.0.0.0:8000:localhost:8888 userID@host`

and then go to your web-browser and type: http://host:8000

**Comment by Jeeppler** [comment]
+1 need this feature as well.

**Comment by bgopalakrishnan1986** [comment]
+1 need the feature ASAP

**Comment by tristanveness** [comment]
I ran into this issue myself today. Made me very sad *sniffle*. Especially considering `kubectl proxy` has all the bells and whistles already :(
```
      --accept-hosts='^localhost$,^127\.0\.0\.1$,^\[::1\]$': Regular expression for hosts that the proxy should accept.
      --address='127.0.0.1': The IP address on which to serve on.
```

To workaround this feature not yet being implemented/merged... you can port-forward your already port-forwarded port using `socat` in another terminal...

```socat tcp-listen:9222,fork tcp:127.0.0.1:9223```

^ where e.g. 127.0.0.1:9223 is the interface:port `kubectl port-forward` opened locally on 127.0.0.1 and `9222` is the port you want to open on all interfaces (0.0.0.0)

**Comment by jwatte** [comment]
I ran into this, too. kube-proxy does the right thing, why not kube-port-forward?
My use case is "I run a linux VM where I run all the kubectl commands (affecting a cluster hosted in AWS,) and the VM lives inside a Windows host where I run my web browser."
When I want to spin up a new pod in the cluster, and test it out locally without exposing a service to other pods, nor a public address on the cluster, not being able to bind to 0.0.0.0 on my VM is highly inconvenient!

**Comment by bw2** [comment]
Another slight variation on the work-arounds described above using ssh tunnels. 

In my case, I'm running minikube with an http web service deployed on NodePort 30003. 
I can make it accessible externally on port 80 by running:
```
sudo ssh -v -i ~/.ssh/id_rsa -N -L 0.0.0.0:80:localhost:30003 ${USER}@$(hostname)
```

**Comment by wjoel** [comment]
Looks like there is finally some progress on https://github.com/kubernetes/kubernetes/pull/46517 again, thanks @goblain for all your efforts.
