### ISSUE TITLE
Kubelet 1.6 do not change hairpin mode to 1

### ISSUE THREAD

**Issue by yoks** [kubernetes/kubernetes#43966]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Cisco B Series Baremetal
- **OS** (e.g. from /etc/os-release): Centos 7.2
- **Kernel** (e.g. `uname -a`): 4.10.6-1.el7.elrepo.x86_64
- **Install tools**: kubeadm 1.6.1 (beta)
- **Others**: Docker 1.12.6, Flannel networking (same problem with Weave)

**What happened**:
Pods unable to access itself via service ip, after trubleshoting i found what kubelet cannot setup hairping mode for interfaces e.g.:
```bash
for d in /sys/devices/virtual/net/cni0/brif/veth*/hairpin_mode; do echo "$d = $(cat $d)"; done
/sys/devices/virtual/net/cni0/brif/veth4bfbfe74/hairpin_mode = 0
/sys/devices/virtual/net/cni0/brif/vethfc2a18c5/hairpin_mode = 0
```

If i downgrade kubelet to 1.5.6
```bash
for d in /sys/devices/virtual/net/cni0/brif/veth*/hairpin_mode; do echo "$d = $(cat $d)"; done
/sys/devices/virtual/net/cni0/brif/veth4bfbfe74/hairpin_mode = 1
/sys/devices/virtual/net/cni0/brif/vethfc2a18c5/hairpin_mode = 1
```
And pod now can access itself via service ip. 

**What you expected to happen**:
Pods should be able to access itself on service IP via hairpin

**How to reproduce it** (as minimally and precisely as possible):
Kubelet 1.6, CNI network and `--hairpin-mode=hairpin-veth`

**Anything else we need to know**:
Can be ralated to #42314, but i do not see `Hairpin setup failed` errors.

**Comment by cmluciano** [comment]
Was this a fresh install or were the nodes drained and then upgraded?

**Comment by yoks** [comment]
@cmluciano fresh installation.

**Comment by freehan** [comment]
Looks like a CNI/CRI related bug. 

@dnardo

**Comment by dnardo** [comment]
@yoks  Can you show me the CNI conf.  The reason I ask is because if this was using the CNI "bridge" plugin it appears that it requires the "hairpinMode": "true" in the conf.  I don't think we are setting hairpin if the network plugin is set to cni, since we may be delegating that to the CNI plugin.

**Comment by yoks** [comment]
@dnardo 
```
{
  "name": "cbr0",
  "type": "flannel",
  "delegate": {
    "isDefaultGateway": true
  }
}
```

**Comment by yoks** [comment]
After i added "hairpinMode": "true", it seems kubelet set hairpin mode to 1.
```
for d in /sys/devices/virtual/net/cni0/brif/veth*/hairpin_mode; do echo "$d = $(cat $d)"; done
/sys/devices/virtual/net/cni0/brif/veth93ec0dbf/hairpin_mode = 0
/sys/devices/virtual/net/cni0/brif/vethc067ee9b/hairpin_mode = 1
```

Not sure why 1 of the devices is still 0, but everything seems to work as intended.

**Comment by dnardo** [comment]
Interesting, I'm of two minds on this.  I think long term we want to delegate any network setup to the CNI plugin including the hairpining.  We probably  want to deprecate the hairpin flag in the kubelet eventually which will most likely happen once we deprecate kubenet in favor of CNI.   On the other hand I feel like the hairpin flag should continue to work regardless in the short term.

While hairpin is done for the bridge plugin it's not been done for every plugin, however,  looking at the flannel code I see that it does in fact delegate to the "bridge" plugin so I'm thinking that invocation of the bridge plugin with the hairpin set to true actually made that work.
