### ISSUE TITLE
TestTcpHealthChecker unit test fails for Go 1.8 ppc64le on master branch

### ISSUE THREAD

**Issue by vaibhavsood** [kubernetes/kubernetes#43970]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
TestTcpHealthChecker, pkg/probe/tcp

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Kubernetes version** (use `kubectl version`):
1.6

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
SLES 12
- **Kernel** (e.g. `uname -a`):
Linux 3.12.28-4-default ppc64le
- **Install tools**:
- **Others**:

**What happened**:
make test WHAT="./pkg/probe/tcp"
Running tests for APIVersion: v1,apps/v1beta1,authentication.k8s.io/v1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1,authorization.k8s.io/v1beta1,autoscaling/v1,autoscaling/v2alpha1,batch/v1,batch/v2alpha1,certificates.k8s.io/v1beta1,extensions/v1beta1,imagepolicy.k8s.io/v1alpha1,policy/v1beta1,rbac.authorization.k8s.io/v1beta1,rbac.authorization.k8s.io/v1alpha1,settings.k8s.io/v1alpha1,storage.k8s.io/v1beta1,storage.k8s.io/v1,federation/v1beta1
+++ [0403 10:39:08] Running tests without code coverage
--- FAIL: TestTcpHealthChecker (0.00s)
        tcp_test.go:86: #1: expected output=one of []string{"unknown port", "Servname not supported for ai_socktype", "nodename nor servname provided, or not known", "dial tcp: invalid port"}, get=dial tcp: address -1: invalid port
FAIL
FAIL    k8s.io/kubernetes/pkg/probe/tcp 0.004s
Makefile:164: recipe for target 'test' failed
make: *** [test] Error 1

**What you expected to happen**:
Test case passes

**How to reproduce it** (as minimally and precisely as possible):
make test WHAT="./pkg/probe/tcp"

**Anything else we need to know**:

Found similar issue: https://github.com/kubernetes/kubernetes/issues/15952

But the PR fix is for pkg/probe/http

**Comment by Pensu** [comment]
Hi,

Can you try adding 

``` "dial tcp: address -1: invalid port", ```

instead of 

``` "dial tcp: invalid port", ```

at line 72 in pkg/probe/tcp/tcp_test.go.

**Comment by vaibhavsood** [comment]
Yes, this fixes it on SLES as well, thanks

**Comment by kargakis** [comment]
@kubernetes/sig-node-test-failures

**Comment by cmluciano** [comment]
@vaibhavsood Does this still need a fix?
