### ISSUE TITLE
Handling cycles in requiredDuringScheduling PodAffinity

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#43971]
@gmarek and @wojtek-t brought up two related issues with the current implementation of requiredDuringScheduling PodAffinity.

1) If pod A has requiredDuringScheduling affinity for pod B, and pod B has requiredDuringScheduling affinity for pod A, then neither will ever schedule. (More generally any time there is a cycle, none of the pods in the cycle will schedule.) We fixed this (in a hacky way) for the case of A having affinity for other pods from the same collection as A (see [here](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L1175)), so you can write rules like "put all the pods from collection A in the same zone" without having the first pod block forever, but we didn't consider the cases of multiple mutually dependent collections.

2) Even if we fix (1), i.e. implement a similar workaround for cycles as we did for same-collection, if you use topologyKey == node because you want to "pair up" two or more pods, when you add new nodes they won't go onto the new nodes. You would need the workaround to trigger each time you add a new node, not just to get the first pod to schedule.

These issues don't apply to pod anti-affinity, only pod affinity.

My opinion:

I can understand that people might want the "pair up" behavior described in (2), but I don't think we should contort the semantics of pod affinity to provide it. If you write a rule that pods from collection A can only run on nodes that are already running a pod from B, and pods from collection B can only run on nodes that are already running a pod from A, and somehow one pod from A and one pod from B are running (on the same node, of course), then when you add more nodes I don't think there's any reason to think new a pod from A or B will schedule there. (Same argument if the topologyKey is zone instead of node and you add a new zone.) I think getting the *first* pod to schedule (what's described in (1)), while it also violates a strict interpretation of the semantics of the rule, is more reasonable because without that, nothing can schedule at all.

However, I'm not sure we should do either (1) or (2), as there are reasonable workarounds. One option is to put all the containers that need to run together on the same node into the same pod. When you add new nodes, replicas of the pod (and therefore the set of containers) can schedule onto the new node. Another option is to put the requiredDuringScheduling in only one direction (BTW when you put requiredDuringScheduling pod affinity in one direction, the scheduler implicitly adds a preferredDuringScheduling pod affinity in the opposite direction). (In the case of a cycle of depenencies, just make sure at least one edge is preferredDuringScheduling, not requiredDuringScheduling.) Add requiredDuringScheduling anti-affinity if you want to make sure the pods don't run on the same node (or zone or whatever).I think this is probably "good enough" for addressing (1) and (2).

Happy to hear other people's opinions.

cc/ @kevin-wangzefeng @kubernetes/sig-scheduling-feature-requests

**Comment by wojtek-t** [comment]
I think that detecting cycles in general would be overkill - this would be pretty difficult to do and would really complicate the code and I don't think it's worth it.
If we decide that we don't want to detect cycles, detecting pairs would be super misleading to users in my opinion (why we detect cycles of length 2 and not longer ones)?

That said, if you create a cycle of requiredDuringScheduling (in particular cycle of size 2 (= pair)), that fact that nothing will never schedule is also pretty bad experience.

So in my personal opinion, if we decide not solve neither (1) or (2), I think what we should do is:
- document it clearly in pod-affinity documentation as a not supported scenario (with suggestions how to workaround it, as @davidopp described above)

I was also thinking about rejecting it at the validation level, but it seems quite hard (well, if we do validation only on pod level, that's probably doable, but if you create two deployments that will be creating pods with requireDuringScheduling cycle, then rejecting pods will result in dosing system, as ReplicaSetController would be recreating them all the time. So we would need to also validate a bunch of other objects in the system, which again sounds like an overkill.
