### ISSUE TITLE
1.6.0 kubelet doesn't work with 1.5.2 apiserver

### ISSUE THREAD

**Issue by CallMeFoxie** [kubernetes/kubernetes#43976]
Hi,
I've updated our test instance of kubelet/kubectl and hyperkube apiserver+scheduler+controller from 1.5.2 to 1.6.0 on one of three HA nodes and none of the pods on the host node came up because of (kubelet log, same in the kubectl events/describe pod):
W0403 09:33:16.378869  113540 config.go:361] Pod[5] (dashboard-cvd3m_kube-system(63446b97-0e11-11e7-a2de-842b2bfe82f1)) from api failed validation, ignoring: [spec.containers[0].terminationMessagePolicy: Required value: must be 'File' or 'FallbackToLogsOnError', spec.containers[1].terminationMessagePolicy: Required value: must be 'File' or 'FallbackToLogsOnError']

kubectl get pod dashboard-... -o yaml however shows:
Conditions:
  Type        Status
  Initialized     True
  Ready     True
  PodScheduled     True
which makes it look like it is running (while it is not).

tried deleting this pod so that RC picks it up again, but now it is stuck in Terminating stage and won't move (no further logs in kubelet/events).

Looking at the kubectl get pods dashboard-... -o yaml I can clearly see:
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
in all the containers of that POD on **this** apiserver node.

Then I re-tried to kubectl delete pod dashboard-... --force with no luck so I added --grace-period=0 which finally got rid of it.

The solution was to update all three apiserver nodes to 1.6.0 (the local balancer always picks a random one to connect to) before anything would come up. 

**It seems that new 1.6.0 kubelet cannot create pods with older 1.5.2/1.5.4 (and possibly other 1.5.x and older as well - did not try all of them) apiservers running as it expects an unknown value.**

**Updating apiservers first and then kubelets seems to work fine.**

**Kubernetes version**
> Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-29T09:26:59Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.2-dirty", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"dirty", BuildDate:"2017-01-13T13:03:39Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

(the -dirty is because I had locally applied patch that I sent and got pulled into 1.6)

I did not manage to find a note about this on release notes page :)

** Proposed solution **
Either make it backwards compatible (use default value for older kubelets) or notify admins on release page.

Ashley

**Comment by liggitt** [comment]
Newer kubelets on older apiservers are not a supported configuration. See https://github.com/kubernetes/community/blob/master/contributors/design-proposals/versioning.md#supported-releases-and-component-skew

**Comment by CallMeFoxie** [comment]
I see, thanks!

This should be mentioned in the changelog rather than hidden in another repo and design proposals :) I'd say though.

**Comment by CallMeFoxie** [comment]
/close

this issue is not relevant anymore and is documented
