### ISSUE TITLE
Couldn't find network status for {namespace}/{pod_name} through plugin: invalid network status for

### ISSUE THREAD

**Issue by vdavidoff** [kubernetes/kubernetes#43988]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
NO

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
"invalid network status for"
"Couldn't find network status for"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
1.6.0

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
- **Kernel** (e.g. `uname -a`):
Linux HOSTNAME_REDACTED 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
After upgrading a cluster from 1.5.3 to 1.6.0, I see errors like the following in kubelet's log:
`/var/log/upstart/kubelet.log:W0403 15:38:19.584738   25905 docker_sandbox.go:263] Couldn't find network status for default/prometheus-node-exporter-2n784 through plugin: invalid network status for`

**What you expected to happen**:
* For this error to not be generated if it's a false positive
* For the underlying bug to be fixed if this is a real error but it's a bug in kubelet/kubernetes (and not some environmental trigger)
* For the error message to be more useful in the case the error is legitimate

**How to reproduce it** (as minimally and precisely as possible):
Upgrade a cluster from 1.5.3 to 1.6.0 and watch kubelet's logs.

**Anything else we need to know**:
I am using a hyperkube image that I built from kubernetes source, and the compiled kubelet binary downloaded from the kubernetes project. This is the same way I deployed 1.5.3 and previous versions.

I am using flanneld as an overlay network and not configuring any CNI networking / network-plugin options to kubelet.

I tracked this error message down to the following code.

pkg/kubelet/dockershim/docker_sandbox.go
```
229 // getIPFromPlugin interrogates the network plugin for an IP.
230 func (ds *dockerService) getIPFromPlugin(sandbox *dockertypes.ContainerJSON) (string, error) {
231     metadata, err := parseSandboxName(sandbox.Name)
232     if err != nil {
233         return "", err
234     }
235     msg := fmt.Sprintf("Couldn't find network status for %s/%s through plugin", metadata.Namespace, metadata.Name)
236     cID := kubecontainer.BuildContainerID(runtimeName, sandbox.ID)
237     networkStatus, err := ds.network.GetPodNetworkStatus(metadata.Namespace, metadata.Name, cID)
238     if err != nil {
239         // This might be a sandbox that somehow ended up without a default
240         // interface (eth0). We can't distinguish this from a more serious
241         // error, so callers should probably treat it as non-fatal.
242         return "", err
243     }
244     if networkStatus == nil {
245         return "", fmt.Errorf("%v: invalid network status for", msg)
246     }
247     return networkStatus.IP.String(), nil
248 }
249 
250 // getIP returns the ip given the output of `docker inspect` on a pod sandbox,
251 // first interrogating any registered plugins, then simply trusting the ip
252 // in the sandbox itself. We look for an ipv4 address before ipv6.
253 func (ds *dockerService) getIP(sandbox *dockertypes.ContainerJSON) (string, error) {
254     if sandbox.NetworkSettings == nil {
255         return "", nil
256     }
257     if sharesHostNetwork(sandbox) {
258         // For sandboxes using host network, the shim is not responsible for
259         // reporting the IP.
260         return "", nil
261     }
262     if IP, err := ds.getIPFromPlugin(sandbox); err != nil {
263         glog.Warningf("%v", err)
264     } else if IP != "" {
265         return IP, nil
266     }
267     // TODO: trusting the docker ip is not a great idea. However docker uses
268     // eth0 by default and so does CNI, so if we find a docker IP here, we
269     // conclude that the plugin must have failed setup, or forgotten its ip.
270     // This is not a sensible assumption for plugins across the board, but if
271     // a plugin doesn't want this behavior, it can throw an error.
272     if sandbox.NetworkSettings.IPAddress != "" {
273         return sandbox.NetworkSettings.IPAddress, nil
274     }
275     return sandbox.NetworkSettings.GlobalIPv6Address, nil
276 }
```

pkg/kubelet/network/kubenet/kubenet_linux.go
```
541 // TODO: Use the addToNetwork function to obtain the IP of the Pod. That will assume idempotent ADD call to the plugin.
542 // Also fix the runtime's call to Status function to be done only in the case that the IP is lost, no need to do periodic calls
543 func (plugin *kubenetNetworkPlugin) GetPodNetworkStatus(namespace string, name string, id kubecontainer.ContainerID) (*network.PodNetworkStatus, error) {
544     plugin.mu.Lock()
545     defer plugin.mu.Unlock()
546     // Assuming the ip of pod does not change. Try to retrieve ip from kubenet map first.
547     if podIP, ok := plugin.podIPs[id]; ok {
548         return &network.PodNetworkStatus{IP: net.ParseIP(podIP)}, nil
549     }
550 
551     netnsPath, err := plugin.host.GetNetNS(id.ID)
552     if err != nil {
553         return nil, fmt.Errorf("Kubenet failed to retrieve network namespace path: %v", err)
554     }
555     ip, err := network.GetPodIP(plugin.execer, plugin.nsenterPath, netnsPath, network.DefaultInterfaceName)
556     if err != nil {
557         return nil, err
558     }
559 
560     plugin.podIPs[id] = ip.String()
561     return &network.PodNetworkStatus{IP: ip}, nil
562 }
```

As suggested by the code, I'm only getting these errors for containers that don't use hostNetwork. If I run `docker inspect` on the containers that are mentioned in the error messages, the values in the `NetworkSettings` section are empty, but I'm not sure that's relevant.

```
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": null,
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {}
        }
```

**Comment by phagunbaya** [comment]
experiencing same issue.

**Comment by loxo33** [comment]
We are experiencing the same issue.

**Comment by freehan** [comment]
IIUC, you are using `cni` network plugin with flannel, not `kubenet`. Right?

**Comment by freehan** [comment]
cni network plugin retrieves ip using this logic: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/plugins.go#L279

Can you try to do the same manually with `nsenter` and `ifconfig`?

**Comment by vdavidoff** [comment]
Frankly, CNI networking and other related network plugins confuse me a great deal. I'm not setting any CNI or network plugin related options for kubelet, kube-apiserver, or anything else, as far as I am aware. Based on the following messages in kubelet's log, I think this means I'm using a default/no-op CNI implementation, but I don't understand the implications of that:
```
Docker cri networking managed by kubernetes.io/no-op
Calling network plugin kubernetes.io/no-op to set up pod
Unable to update cni config: No networks found in /etc/cni/net.d
Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
```

What I can tell you for sure is that I'm deploying flannel which is talking to the same etcd cluster as kube-apiserver and friends, but only because the cluster is already there so it makes sense to use it. Other than that commonality, I don't think there's anything that's integrating flannel into kubernetes things. I'm then configuring docker with `--bip` assigning it the .1 address of the /24 that flannel has chosen for the `flannel.1` interface.

So, unless I'm just tragically confused, I think kubernetes doesn't know anything about my pod networking or overlay networking, other than inspecting containers once they're running. And I know that's working in general, because I have no issues with pod networking.

To specifically address your question about `nsenter`, the following appears to do the right thing for a running pod (not one that is generating the reported log messages). Note that I arbitrarily chose the argument to `--net` here, and although I believe this simulates the argument that'd be used by kubelet, I am not 100% certain.
```
$ sudo nsenter --net=/proc/745/ns/net -F -- ip -o -4 addr show  dev eth0 scope global
201: eth0    inet 172.16.39.4/24 scope global eth0\       valid_lft forever preferred_lft forever
```

I believe the `--net` argument is correct based on this:
# pkg/kubelet/dockershim/helpers.go
```
206 func getNetworkNamespace(c *dockertypes.ContainerJSON) string {
207     if c.State.Pid == 0 {
208         // Docker reports pid 0 for an exited container. We can't use it to
209         // check the network namespace, so return an empty string instead.
210         glog.V(4).Infof("Cannot find network namespace for the terminated container %q", c.ID)
211         return ""
212     }
213     return fmt.Sprintf(dockerNetNSFmt, c.State.Pid)
214 }
```

However, I don't see how that could work for containers that aren't running, and maybe that's exactly what the issue is?

**Comment by freehan** [comment]
I need to know more about your network setup. Looks like you are using flannel with docker default networking. `kubernetes.io/no-op` just skips networking setup for pods.

To confirm, can you paste the result of `ps aux | grep kubelet`?

If you are using no-op, the current logic is to only retrieve IP from `docker inspect`. I think we should also try to retrieve IP thru `nsenter` by best effort.

**Comment by vdavidoff** [comment]
From the running kubelet process, broken into lines for readability
```
/usr/bin/kubelet
-v=4
--require-kubeconfig
--cluster-dns=192.168.0.2
--cluster-domain=cluster.local
--allow-privileged=false
--system-reserved=cpu=0.5
--eviction-minimum-reclaim=memory.available=0M,nodefs.available=10G,nodefs.inodesFree=7500
--eviction-soft=nodefs.available<5G,nodefs.inodesFree<7500
--eviction-soft-grace-period=nodefs.available=5m,nodefs.inodesFree=5m
--eviction-max-pod-grace-period=120
--eviction-hard=memory.available<600M
--image-gc-high-threshold=100
--node-labels k8s-master=true
--pod-infra-container-image {REDACTED}/pause-amd64:v3.0
--kubeconfig /etc/kubernetes/kubelet.kubeconfig
--pod-manifest-path /etc/kubernetes/manifests
--hostname-override {REDACTED}
```

Also note that as mentioned above, the `NetworkSettings` section of `docker inspect` does not report an IP address.

**Comment by freehan** [comment]
Yeah. This is what I suspected. Network plugin is not specified. Hence no-op is used. Kubelet do not manage pod networking. 

In this case, kubelet assumes that native docker networking is used. Hence it only tries to retrieve network status thru `docker inspect`. But in your case, it looks like docker is not aware of the network setup. Hence leaving the `invalid network status` error. Kubelet should also try to retrieve pod IP thru nsenter. 

Just curious, what is calling flannel to setup networking?

**Comment by vdavidoff** [comment]
As far as I understand it, nothing is calling flannel. When flannel starts on a node for the first time, it talks to etcd to find the cluster's flannel configuration. That includes a /16 from which it allocates itself a /24, and assigns that network address (`a.b.c.0/24`) to the `flannel.1` interface. This also includes the instruction that flannel should use VXLAN for routing to other flannel agents.

Docker is then restarted with its `--bip` argument specifying the `a.b.c.1/24` address on the flannel /24. If any containers were already running, we restart them too to ensure they get an IP from the newly assigned subnet.

From there the specifics get fuzzy for me, but it seems that docker understands it should assign pod IPs from `a.b.c.0/24` starting from `.2`, then the rest just works because Kubernetes is able to determine the pod IPs by talking to docker (at least for the most important things, it seems, i.e. what this ticket is about doesn't appear to be breaking things, but maybe it is...), and IP routing for flannel works because flannel pokes the kernel's native VXLAN bits so that routing between the flannel subnets gets encapsulated and sent to the correct flannel VXLAN agent. Exactly how the VXLAN kernel parts and routing works is not clear to me, but I believe that's the gist.

FWIW, the way I'm setting this up is the way the official Kubernetes "from scratch" guide for Debian originally guided me. And as far as I know, it's working totally fine. If it at all seems screwy, I'd be interested in your feedback.

**Comment by freehan** [comment]
I think it is a setup problem related to docker and flannel. Maybe the doc you are referring to is not up to date. Could you share the link?

Could you confirm your docker0 bridge has been updated to use `a.b.c.1/24`? Check the result of `ifconfig docker0`. If not, then try to delete docker0 bridge and restart docker daemon.

Another thing to try is just `docker run` some container and see if they get the ip address from `a.b.c.1/24` and it is reflected in `docker inspect`.

**Comment by yujuhong** [comment]
@vdavidoff, does your cluster function properly? If it is, I think the error messages are just red herrings. 
 - From the code, dockershim assumes a network plugin is used. Even though it'll fall back to inspect the container network setting, it'd still log an error.
 - You should inspect the podsandbox container (not the application container) to see its network settings.

E.g., 
```console
$ sudo docker ps
141759939fa3        7141d7c33b64                               "/bin/sh -c '/run.sh "   About an hour ago    Up About an hour                        k8s_fluentd-gcp_fluentd-gcp-v2.0-4p10g_kube-system_1fa88335-1fbe-11e7-ac5f-42010af00002_0
6fa3a8d0578d        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 About an hour ago    Up About an hour                        k8s_POD_fluentd-gcp-v2.0-4p10g_kube-system_1fa88335-1fbe-11e7-ac5f-42010af00002_0
```
`docker ps` shows two containers for the fluentd pod. The first one is the application container running fluentd. The second one with a `k8s_POD_` prefix in its name is the podsandbox container (a.k.a infra container) with the network settings. Only the `k8s_POD_*` containers will have non-nil NetworkSettings. 

One easy way to check this is to run `kubectl describe pod <pod_name>` to see if the correct IP address is populated.

**Comment by vdavidoff** [comment]
@freehan the docker bridge is right. Everything appears to be functioning properly with regard to networking. Pod to pod communication, ingress from outside the cluster, node to node, cluster IP services, etc. I have no existing networking issues to my knowledge. I don't usually use `docker run` but it does what I'd expect - assigns an IP to the container from the /24 on the docker0 interface, which is numbered with the .1 address from the flannel.1 interface.

@yujuhong Yeah, as stated above, as far as I can tell, which includes quite a bit of functionality flexing, the cluster behaves fine. Your suggestion to check the sandbox pod appears right on the money - the container running the pod's primary app - the one kubelet is complaining about - shows nothing for network information (the section is there, but the values for the fields are empty or effectively empty). But the same for the pod's sandbox container does show network information.

```
W0412 01:00:17.328566    5227 docker_sandbox.go:263] Couldn't find network status for default/prometheus-node-exporter-csqdk through plugin: invalid network status for

$ sudo docker ps | grep prometheus-node-exporter-csqdk
4da891b017df        REDACTED/node-exporter@sha256:b0913d4794da8a891fa6459b31a597f03572403a8e4f88ea0440154e78aed025                 "/bin/node_exporte..."   7 days ago          Up 7 days                               k8s_prometheus-node-exporter_prometheus-node-exporter-csqdk_default_84750e5c-1a29-11e7-adbf-00163e215c33_0
daefde8a188c        REDACTED/pause-amd64:v3.0                                                                                      "/pause"                 7 days ago          Up 7 days                               k8s_POD_prometheus-node-exporter-csqdk_default_84750e5c-1a29-11e7-adbf-00163e215c33_0

$ sudo docker inspect 4da891b017df -f '{{.NetworkSettings.Networks.bridge}}'
<no value>

$ sudo docker inspect daefde8a188c -f '{{.NetworkSettings.Networks.bridge}}'
{<nil> [] [] 2505df3706fae63c263c5c2e93f6250cf06a2b5e7fdc6df2fbe2c74da10d5469 538bff4be2aae5d656bb42e250b6c9854697544594fce2be3e1427c75d87bc93 172.16.35.1 172.16.35.2 24   0 02:42:ac:10:23:02}
```

**Comment by yujuhong** [comment]
@vdavidoff @freehan ok, this looks like a log clarity issue. The code can check whether a network a plugin is configured, and only complain (i.e., log the error message) if there exists a plugin.

**Comment by zihaoyu** [comment]
We have basically the same setup as @vdavidoff : 

- Flannel on CoreOS. Flannel gets a subnet from etcd, writes CIDR to properties file
- dockerd starts with `--bip` CIDR from flannel properties file
- No CNI plugin or kubenet or anything for kubelet

We saw the same logs in `kubelet` logs:
```
W0429 03:21:28.658370    3252 docker_sandbox.go:263] Couldn't find network status for production/mypod-544180576-3d9hz through plugin: invalid network status for
```

However, we also saw massive pods being killed by kubelet:
```
# kubectl describe pod <podname>
  14m	14m	1	kubelet, ip-10-72-21-43.us-west-2.compute.internal	spec.containers{mysvc}	Normal	Killing		Killing container with id docker://9ba866931c13c11a45afe1555d5f0f08a352780f3458973c7888dccc2192f610:Need to kill Pod
```

This caused disruption and brief service outage. Please advise.

**Comment by jmccarty3** [comment]
I have a very similar setup as @vdavidoff and have experienced issues seemingly related.  The cluster will operate just fine for several hours (12+). After the given time the kubelet seems to begin to kill pods which then throw them into a crash loop.

I see kubelet logs such as:

> kubelet[11970]: W0502 23:54:57.361378   11970 docker_sandbox.go:263] Couldn't find network status for kube-system/kube-dns-gvz2h through plugin: invalid network status for

(Note that is the full line. Nothing comes after the 'for')

And events such as 

>  SandboxChanged    Pod sandbox changed, it will be killed

Once in this state, the kubelet is unable to restart any pods. However, if the kubelet process is restarted everything self-corrects.

**Comment by yujuhong** [comment]
@zihaoyu @jmccarty3 I think the "invalid network status" is just a red herring. If any of you can paste the kubelet logs, that'd help.

**Comment by stensonb** [comment]
Here are my kubelet logs, showing the same error @jmccarty3 reports: https://gist.github.com/stensonb/3f6db27eb0ba031463d63cad8360f780

It looks like the container with id `dadd21ea-2b61-11e7-87ae-e63e85527c63` demonstrates the issue...search for that in the gist.

Also, this line:

```
April 27th 2017, 10:32:05.000	W0427 17:32:05.507065    2267 docker_sandbox.go:263] Couldn't find network status for techops-prod/cyanite-493774351-tb456 through plugin: invalid network status for
```

**Comment by jmastr** [comment]
For me it seems to have something to do with flannel v0.7.0 and Kubernetes v1.6.x. My Kubelet starts to act weird, when the rkt garbage collection starts, either reproducible with `sudo rkt gc` or  automatically like:
```
kubelet[16200]: I0524 08:24:29.761684 16200 qos_container_manager_linux.go:285] [ContainerManager]: Updated QoS cgroup configuration
...
systemd[1]: Starting Garbage Collection for rkt...
rkt[14743]: gc: moving pod "17942a27-cb9f-4152-ab95-fc3bd128639b" to garbage
rkt[14743]: gc: pod "17942a27-cb9f-4152-ab95-fc3bd128639b" not removed: still within grace period (24h0m0s)
systemd[1]: Started Garbage Collection for rkt.
systemd-timesyncd[623]: Network configuration changed, trying to establish connection.
systemd-timesyncd[623]: Synchronized to time server 78.47.226.8:123 (2.coreos.pool.ntp.org).
kubelet[16200]: I0524 08:25:28.998438 16200 container_manager_linux.go:397] [ContainerManager]: Discovered runtime cgroups name: /system.slice/docker
.service
kubelet[16200]: I0524 08:25:29.762683 16200 qos_container_manager_linux.go:302] [ContainerManager]: Failed to update QoS cgroup configuration
...
```

There are indications that v0.7.1 solves some Kubernetes related issues, see: https://github.com/coreos/flannel/pull/690, but since it is currently not shipped with the CoreOS version I use, I just downgraded to v1.5.x again.

**Comment by ichekrygin** [comment]
Running `kubelet` with `--enable-cri=false` seems to work around this issue.

**Comment by jmastr** [comment]
FYI here you find a nice workaround, that I am currently testing: https://github.com/coreos/bugs/issues/1965

**Comment by dev-e** [comment]
Maybe this will help: [https://github.com/coreos/flannel/issues/427](url)

**Comment by jsravn** [comment]
Is anyone else also seeing messages like
```
Sep 28 07:57:54 ip-10-50-97-190 start-kubelet.sh[1748]: E0928 07:57:54.064121    1748 remote_runtime.go:163] ListPodSandbox with filter "nil" from runtime service failed: rpc error: code = 4 desc = context deadline exceeded
Sep 28 07:57:54 ip-10-50-97-190 start-kubelet.sh[1748]: E0928 07:57:54.064194    1748 kuberuntime_sandbox.go:185] ListPodSandbox failed: rpc error: code = 4 desc = context deadline exceeded
Sep 28 07:57:54 ip-10-50-97-190 start-kubelet.sh[1748]: E0928 07:57:54.064209    1748 generic.go:198] GenericPLEG: Unable to retrieve pods: rpc error: code = 4 desc = context deadline exceeded
```
when this happens? Looks like some bug in dockershim.

**Comment by zihaoyu** [comment]
Just an update, we have switched to Calico CNI with k8s v1.7.6. The errors have disappeared.

In v1.7 `--enable-cri` is always `true` I believe.
