### ISSUE TITLE
Building Cassandra Docker image fails

### ISSUE THREAD

**Issue by ksr1** [kubernetes/kubernetes#43980]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Kubernetes version** (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS
- **Kernel** (e.g. `uname -a`): Linux 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
Building Cassandra Docker image fails with:

Processing triggers for libc-bin (2.23-0ubuntu5) ...
W: --force-yes is deprecated, use one of the options starting with --allow instead.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c set -e && echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections   && apt-get update && apt-get -qq -y --force-yes install --no-install-recommends 	openjdk-8-jre-headless 	libjemalloc1 	localepurge 	wget &&   mirror_url=$( wget -q -O - http://www.apache.org/dyn/closer.cgi/cassandra/         | sed -n 's#.*href="\(http://ftp.[^"]*\)".*#\1#p'         | head -n 1     )     && wget -q -O - ${mirror_url}/${CASSANDRA_VERSION}/apache-cassandra-${CASSANDRA_VERSION}-bin.tar.gz         | tar -xzf - -C /usr/local     && wget -q -O - https://github.com/Yelp/dumb-init/releases/download/v${DI_VERSION}/dumb-init_${DI_VERSION}_amd64 > /sbin/dumb-init     && echo "$DI_SHA  /sbin/dumb-init" | sha256sum -c -     && chmod +x /sbin/dumb-init     && chmod +x /ready-probe.sh     && mkdir -p /cassandra_data/data     && mkdir -p /etc/cassandra     && mv /logback.xml /cassandra.yaml /jvm.options /etc/cassandra/     && mv /usr/local/apache-cassandra-${CASSANDRA_VERSION}/conf/cassandra-env.sh /etc/cassandra/     && adduser --disabled-password --no-create-home --gecos '' --disabled-login cassandra     && chown cassandra: /ready-probe.sh     && if [ -n "$DEV_CONTAINER" ]; then apt-get -y --no-install-recommends install python; else rm -rf  $CASSANDRA_HOME/pylib; fi     && apt-get -y purge wget localepurge     && apt-get autoremove     && apt-get clean     && rm -rf         $CASSANDRA_HOME/*.txt         $CASSANDRA_HOME/doc         $CASSANDRA_HOME/javadoc         $CASSANDRA_HOME/tools/*.yaml         $CASSANDRA_HOME/tools/bin/*.bat         $CASSANDRA_HOME/bin/*.bat 	doc 	man 	info 	locale 	common-licenses 	~/.bashrc         /var/lib/apt/lists/*         /var/log/*         /var/cache/debconf/*         /etc/systemd         /lib/lsb         /lib/udev         /usr/share/doc/         /usr/share/doc-base/         /usr/share/man/         /tmp/*         /usr/lib/jvm/java-8-openjdk-amd64/jre/plugin         /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/javaws         /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/jjs         /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/orbd         /usr/lib/jvm/java-8-openjdk-amd64/bin/pack200         /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/policytool         /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/rmid         /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/rmiregistry         /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/servertool         /usr/lib/jvm/java-8-openjdk-amd64/bin/tnameserv         /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/unpack200         /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/javaws.jar         /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/deploy*         /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/desktop         /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/*javafx*         /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/*jfx*         /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libdecora_sse.so         /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libprism_*.so         /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libfxplugins.so         /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libglass.so         /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libgstreamer-lite.so         /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjavafx*.so         /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjfx*.so         /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jfxrt.jar         /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/nashorn.jar         /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/oblique-fonts         /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/plugin.jar 	/usr/lib/jvm/java-8-openjdk-amd64/man' returned a non-zero code: 2

**What you expected to happen**:
Successful build of Cassandra Docker image 

**How to reproduce it** (as minimally and precisely as possible):
Build the Docker image using the Docker file 

**Anything else we need to know**:

**Comment by nmnellis** [comment]
Were you able to find a fix for this?

**Comment by jagosan** [comment]
Bug scrub decision to close as no new activity and not actionable.

**Comment by kejau** [comment]
Its still a recurring bug
