### ISSUE TITLE
How to put test results on k8s-testgrid?

### ISSUE THREAD

**Issue by Pensu** [kubernetes/kubernetes#43989]
Hi,

We at IBM have been running test cases on k8s on ppc64le architecture. We have been able to achieve 100 percent coverage on unit and integration tests and more than 90 percent coverage on conformance tests. I see that there are a lot of test results available at www.k8s-testgrid.appspot.com. It would be nice to showcase out results there, is there any documents available that I need to follow to publish the results in testgrid? Or is there anyone who can help me with this?

TIA.

**Comment by ncdc** [comment]
cc @kubernetes/sig-testing-misc @spxtr @ixdy

**Comment by ixdy** [comment]
I'd say to [look at this doc](https://github.com/kubernetes/test-infra/blob/master/docs/federated_testing.md), but it's out of date - you can open a PR to add results to testgrid yourself. Details are in [this doc](https://github.com/kubernetes/test-infra/blob/master/testgrid/config/README.md).

**Comment by Pensu** [comment]
@ixdy Thanks for that. I understand I need to buy a gcs storage. Any idea how much storage would be optimal?

**Comment by ixdy** [comment]
Storage usage will probably vary based on how frequently you run tests and how long you keep test results around.

I think we have a 90d TTL on the `gs://kubernetes-jenkins` bucket; looking at one test job:
```
$ gsutil du -sh gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gce
127.79 GiB  gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gce
```

I'm not sure about usage patterns, so I'm not sure if nearline would actually cost less than regular. I would avoid coldline storage.

**Comment by fejta** [comment]
You typically pay for the amount of gcs you use each month. 

You say you can run unit, integration and conformance tests. How large are the resulting junit.xml files? What other data do you want to include with each run?

How many times per day do you want to run these tests?

How many days of historical results do you want to maintain (I think testgrid defaults to showing one week)?

This should let you compute how much storage you will use. 

You can configure object lifecycle on a gcs bucket to automatically delete any objects over N days old.

**Comment by fejta** [comment]
PS: please `/assign` issues that require attention. 
/assign

**Comment by fejta** [comment]
PPS: this is very exciting and will love to add your results to testgrid asap!!!

**Comment by Pensu** [comment]
@fejta Hi, I am running tests, but not able to see any junit.xml file, where can I find it?

**Comment by fejta** [comment]
Will you be more explicit about running tests? What tests are you running? How are you running them? What are you expecting to happen and what is actually happening? Where are you expecting to find the junit.xml files?

**Comment by Pensu** [comment]
@fejta I am running unit tests using "make test", integration tests using "make test-integration", and in e2e tests, I am mostly running only Conformance tests, using " GINKGO_PARALLEL=y go run hack/e2e.go -- -v --test --test_args="--ginkgo.focus=\[Conformance\] --ginkgo.skip=\[Serial\]"  "

Now, as I understand I need junit.xml files that can be read by test-grid to display the results. The expectation here is to start simply by just displaying the results as to which ones are passing and which one are failing, with green and red respectively. 

Let me know, if you need any more information. Sorry, if I am acting like a newbie, but this is quite new and complicated for me, and I would really appreciate whatever guidance I can get from here. TIA.

**Comment by ixdy** [comment]
The various test suites don't automatically generate junit XML files, no.

For unit/integration tests, you'll either need to use Bazel, or you can set `KUBE_JUNIT_REPORT_DIR` with `make test` or `make test-integration`, which will save the junit XML files in the place specified.
(You may also want to set `KUBE_KEEP_VERBOSE_TEST_OUTPUT=y` to save all stdout into a `.stdout` file.)

For the e2e tests, you'll need to set `E2E_REPORT_DIR`. It's different because it came first. :(

**Comment by Pensu** [comment]
@fejta Hi, I have been able to generate junit files and I have bought google storage and have created a gcs bucket. I understand, I need to add my bucket here: https://github.com/kubernetes/test-infra/blob/master/testgrid/config/config.yaml, but I am not able to get the gcs prefix. Any idea how can I get that? Or what should be the next step?

cc: @ixdy

**Comment by ixdy** [comment]
I'm not sure what you mean by "not able to get the gcs prefix". Where are you uploading your test results?

**Comment by rmmh** [comment]
gcs_prefix is just the path without gs:// -- "kubernetes-jenkins/logs/ci-kubernetes-e2e-gce" means the directory "gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gce".

**Comment by Pensu** [comment]
@ixdy @rmmh So, I have created a project name kubernetes-ppc64le, and it has gcs bucket named ibm-ppc64le, that has the junit xml files, so for me the prefix would be: "kubernetes-ppc64le/ibm-ppc64le"? Or do I need to put in the particular format?

**Comment by rmmh** [comment]
No, GCS buckets are in a global namespace not associated with the project.

> Test results are stored in gs://$JENKINS_GCS_LOGS_PATH/$JOB_NAME/$BUILD_NUMBER. Every run should upload started.json, finished.json, and build-log.txt, and can optionally upload JUnit XML to the artifacts/ directory.

If you upload the 3rd run of a job to gs://ibm-kubernetes/logs/volume-e2e/3 with started.json, finished.json, build-log.txt, and artifacts/junit*.xml, then the prefix in the testgrid config would be ibm-kubernetes/logs/volume-e2e.

**Comment by Pensu** [comment]
@rmmh I tried doing that, but when I trying to create a bucket, it says that I need to select a project mandatorily. Did you face anything like this?

**Comment by Pensu** [comment]
Closing this issue as ppc64le test results are published on testgrid.
