### ISSUE TITLE
etcd timeout causing helm release fail in k8s 1.6.0

### ISSUE THREAD

**Issue by eduardobaitello** [kubernetes/kubernetes#43984]
I've been using **Kubernetes v1.5.1** for running a microservices-based system, using helm to deploy all templates for my application, which consists of at least 15 pods running with different docker images.
At the beginning of helm install, during docker images downloads and containers creations, I am experiencing a high load average due to disk waiting (%wa). At this time, the system logs return serveral etcd "timed out" messages like these bellow:

```
kube-scheduler: E0331 17:12:39.183817   14958 leaderelection.go:261] Failed to update lock: client: etcd cluster is unavailable or misconfigured
etcd: sync duration of 6.708192315s, expected less than 1s
etcd: got unexpected response error (etcdserver: request timed out)
kube-apiserver: E0331 17:13:16.115108    2834 errors.go:63] apiserver received an error that is not an unversioned.Status: client: etcd cluster is unavailable or misconfigured
```

Despite the messages, the deploy ends successfully with helm creating the release correctly. This is OK.

I recently installed **Kubernetes v1.6.0** in a fresh install for tests. This time, using the same helm version, when the first "timed out" message comes out, the helm release fails instantly:

```
helm install CHART --name=RELEASENAME --wait --timeout 9999
Error: release RELEASENAME failed: etcdserver: request timed out
```

The system logs are quite similar to those of the old version:

```
kube-scheduler: E0330 15:15:33.110012   18868 leaderelection.go:263] Failed to update lock: etcdserver: request timed out
etcd: sync duration of 3.654239675s, expected less than 1s
etcd: timed out waiting for read index response
kube-apiserver: E0330 15:15:33.109560    2918 status.go:62] apiserver received an error that is not an metav1.Status: etcdserver: request timed out
```

Somehow the message is now handled by helm as an critical error that fails the release. However, the deploy continues running in background after the error, creating all the desired pods, as in the first case.
High load average is expected, as well the "timed out" messages, but the helm release could not fail since in fact the deployment ends successfully.
Is there a way to deal with messages like in the first case? Is this behavior expected, a bug or am I missing something?

_In both cases:
etcd version: 3.1.0
Helm version: 2.2.3
OS: CentOS Linux release 7.3.1611 (Core) 
3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux_

**Comment by alita91** [comment]
Hello Eduard,

I hit this issue on Kubernetes 1.16 and helm 2.14.2, while deploying metrics-server:

```
[centos@k8s-master-worker ~]$ helm history metrics-server -o yaml
- appVersion: "1.0"
  chart: metrics-server-0.1.3
  description: 'Release "metrics-server" failed: etcdserver: request timed out'
  revision: 1
  status: FAILED
  updated: Wed Mar 25 13:10:24 2020
```

Is there a good practice to make helm resilient to failure, like retry the API call after some time?

Thanks
