### ISSUE TITLE
reboot taints

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#43992]
FEATURE REQUEST

**What happened**:

Reboots to compute nodes automatically start pods.

**What you expected to happen**:

I would like to be able to specify a set of taints that automatically get applied to a node if it reboots so pods don't automatically reschedule on the node when it comes back from a reboot.

These taints can be removed (until next reboot) by a daemonset running on the node that does sanity checks to ensure the node is ready for workloads.

**Comment by dln** [comment]
Can this not be accomplished with the kubelet `--register-with-taints` flag in 1.6?

**Comment by kfox1111** [comment]
Interesting. I was unaware of the feature. I'll take a closer look. Thanks for the tip.

Reading the --help, it looks like its tied up in node registration, which I'm not sure will have the desired effect if the node is already registered, simply rebooting. but it could work...

**Comment by jayunit100** [comment]
@ravisantoshgudimetla Can you update `options.go` "register-node", to describe wether or not data (like taints) may get erased when using `--register` ?  Its not clear on wether or not its gauranteed to be idempotent  WRT to taints and labels ?

**Comment by ravisantoshgudimetla** [comment]
@kfox1111 So, --register-with-taints is a no-op if --register-node is false. This is available in documentation

**Comment by kfox1111** [comment]
Ok. So then we'd need a new feature, that probably shares a lot of code with the other feature.

**Comment by ravisantoshgudimetla** [comment]
There are changes that can accomodate this. For example, #29459 can handle this, if I not I made a hacking version some time back through which you update(Its like deleting the node entry and re-creating with all metadata again). I guess, the best bet would be to wait till the above PR takes some shape.

**Comment by jagosan** [comment]
@kfox1111 - suggest closing this initial discussion and continuing as part of the proposal.  Any reason not to do that?

**Comment by kfox1111** [comment]
@jagosan As part of which proposal? #29459? #43678?

Thanks,
Kevin

**Comment by kargakis** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by sonicaj** [comment]
@jagosan did we ended up adding support for this ? If yes, can you please point me to the direction where I could find some more information about it. I have same exact use case as of @kfox1111. Thank you

**Comment by kfox1111** [comment]
/reopen
/remove-lifecycle rotten

still relevant I think.

**Comment by ChiefyG-Admin** [comment]
https://apps.apple.com/us/app/snagajob-jobs-hiring-now/id333188676
