### ISSUE TITLE
Kubelet on Windows has many errors and exceptions

### ISSUE THREAD

**Issue by anhowe** [kubernetes/kubernetes#43993]
The Windows Kubelet logs show many errors and exceptions from Kubelet because the Windows environment is different.

SO article shows these common errors:
http://stackoverflow.com/questions/43148284/azure-k8s-windows-cluster-internal-error-missing-stats-for-root-container

E0331 16:53:48.527868     900 eviction_manager.go:205] eviction manager: unexpected err: Missing stats for root container
E0331 16:53:55.757082     900 kubelet.go:1634] Failed to check if disk space is available for the runtime: could not determine capacity for "runtime" fs. Info: {Usage:0 Capacity:0 Available:0 Timestamp:2017-03-31 16:53:55.7570827 +0000 GMT}
E0331 16:53:55.757082     900 kubelet.go:1642] Failed to check if disk space is available on the root partition: could not determine capacity for "root" fs. Info: {Usage:0 Capacity:0 Available:0 Timestamp:2017-03-31 16:53:55.7570827 +0000 G
E0331 16:54:04.462246     900 handler.go:246] HTTP InternalServerError serving /stats/summary: Internal Error: Missing stats for root container
 
This issue is resolved once all common errors have disappeared from the first 5 minutes of startup.

**Comment by fohnwind** [comment]
Hi，I have this issue on Windows Server 2016 with docker 17.06.1-ee-1 and Kubelet v1.7.3.
Is there any solution so far? 
Thanks

**Comment by jdumars** [comment]
This will be discussed in an upcoming SIG-Azure meeting.

**Comment by cmeiklejohn** [comment]
Was there any resolution to this issue?  I'm also experiencing the following error, which is preventing container deployment.

```
Failed to check if disk space is available for the runtime: could not determine capacity
```
