### ISSUE TITLE
Resource-dependent pod presets

### ISSUE THREAD

**Issue by therc** [kubernetes/kubernetes#44001]
I was going to propose a new API resource and admission controller, but it turns out that the new [pod preset object](https://github.com/kubernetes/features/issues/162) has great overlap with my ideas, so I reworked them in order to merge the two.

The new policy object lets Pods which use specific runtime resources to abstract away some of their details and defer them until creation time. For example, a Pod using GPU resources might need to access low-level libraries that are inherently host-specific (sometimes kernel-specific, even). Currently, such host volume mounts are not very portable, as different hosts might run different Linux distributions. The problem is thus better tackled at the cluster and namespace level.

Full details at:

https://github.com/therc/community/blob/resource-dependent-pod-preset/contributors/design-proposals/resource-dependent-pod-preset.md

**Comment by pmorie** [comment]
@therc you can actually already inject volumes and volume mounts with `PodPreset` - does that give you what you want?

**Comment by therc** [comment]
I mention that in the "Alternatives" section:

An obvious alternative would use a plain PodPreset and forcing users to add a new label (use-gpu?) on top of the existing GPU resource requests/limits. Such an approach works, but is obviously error-prone and will lead to a proliferation across the Kubernetes user base of similar, but not identical labels.

**Comment by derekwaynecarr** [comment]
@therc - do you plan to open a PR for resource-aware-pod-preset?  have you attended the resource management workgroup meetings?  we have spent a lot of time discussing gpu requirements generally (see meetings and agenda here: https://docs.google.com/document/d/1j3vrG6BgE0hUDs2e-1ZUegKN4W4Adb1B6oJ6j-4kyPU/edit#)

**Comment by therc** [comment]
@derekwaynecarr Yes, I'm going to open a PR next. I was in the conversations at Kubecon and have talked to Vish extensively about the node implications, but had to skip the most recent conversations. I also missed the form about the in-person summit next week, but can probably make it to RDU if it's still happening and there's room for me.

**Comment by bgrant0607** [comment]
vaguely related: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/metadata-policy.md

**Comment by bgrant0607** [comment]
cc @erictune @pwittrock

**Comment by therc** [comment]
I tweaked the language and added a few mentions on how this might integrate with Helm. This is now PR https://github.com/kubernetes/community/pull/506

**Comment by fabiand** [comment]
Also vaguely related to this proposal: This proposal relies on the available resources of a node.
IIUIC currently only cpu, memory, storage, and nvidia gpus, and they are hrad-coded inside the kube codebase.

Does this really scale on the long run? Is it planned that additional resources will be exposed as node resources (in that place where the others mentioned above are defined)?
If this mechanism described in this PR should be valuable, then we do need to think about how additional different resources can be exposed.
In that sense I wonder if it makes sense to have somehow the ability to set those available resources by a 3rd party. I.e an extra daemon. To decouple the presence of resources from the kubelet.
But this otoh then sounds much like labels.

Thus why did I raise my points? he mechanism described in this PR is good, but the mechanism to expose resources does not seem to be well suited. Thus the broader usefulness of this PR is limited. IMHO.

**Comment by fabiand** [comment]
Alright, with OIR kubernetes/features#76 this makes much more sense.
