### ISSUE TITLE
Make sure that performance dashboards work.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#44003]
Now we have several performance tests:
* https://github.com/kubernetes/kubernetes/blob/master/test/e2e/kubelet_perf.go
* https://github.com/kubernetes/kubernetes/blob/master/test/e2e/perf/density.go
* https://github.com/kubernetes/kubernetes/blob/master/test/e2e/perf/load.go
* https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/resource_usage_test.go
* https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/density_test.go

All of them are using https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/perf_util.go, and printing the benchmark metrics into the test result directly.

http://perf-dash.k8s.io/ and http://node-perf-dash.k8s.io/ parse the test output, get the benchmark metrics and generate the performance dashboard.

However, both dashboards are broken now, because:
1) All job names were changed in a recent test-infra refactoring, e.g. `kubernetes-e2e-gce-scalability` => `ci-kubernetes-e2e-gce-scalability`. However, the configuration in the dashboard is not changed https://github.com/kubernetes/contrib/blob/master/perfdash/config.go and https://github.com/kubernetes/contrib/blob/master/node-perf-dash/node-perf-dash-deployment.yaml.
2) Each line of test log is prefixed with an extra timestamp now, which breaks the log parsing logic, e.g. https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scalability/1677/build-log.txt.

The whole logic is so brittle. We should generate a dedicated file for performance metrics, and let the dashboard consume the metrics file.

@dchen1107 @ixdy @krzyzacy @gmarek @wojtek-t 
/cc @kubernetes/sig-scalability-misc @kubernetes/sig-node-bugs

**Comment by ixdy** [comment]
In particular, there's a variable set for all CI e2e runs that tells you where to put files - `framework.TestContext.ReportDir`. Any files saved there will be automatically uploaded to GCS.

(This variable is empty by default, so you'd need to handle that case appropriately.)

**Comment by wojtek-t** [comment]
I think there is already some issue for it (though I couldn't find it now).
@shyamjvs wanted to look into it (but now he is on vacation)

**Comment by jeremyeder** [comment]
@sjug @mffiedler

**Comment by shyamjvs** [comment]
@gmarek is working on it now.

**Comment by Random-Liu** [comment]
Is this fixed? Both performance dashboards are still not working.

**Comment by gmarek** [comment]
Oh sorry - the storing data part is done (at least on our side). At least for our data. Perf-dash was broken consciously, as we didn't redirect it to read dedicated files (we don't have people to do it sadly:/). I'm reopening the bug with a different title.

@wojtek-t @shyamjvs

**Comment by vishh** [comment]
cc @derekwaynecarr

**Comment by gmarek** [comment]
From our side (perfdash.k8s.io) everything's fine.

**Comment by yguo0905** [comment]
http://node-perf-dash.k8s.io has been fixed. This can be closed.

**Comment by derekwaynecarr** [comment]
agreed, its working for me as well.

**Comment by yujuhong** [comment]
Thanks @yguo0905 for fixing this!

**Comment by gmarek** [comment]
Perfect. Thanks a lot @yguo0905!
