### ISSUE TITLE
Federated tests should retry NodePort allocation

### ISSUE THREAD

**Issue by csbell** [kubernetes/kubernetes#44018]
In order to support running tests in parallel, we added randomized NodePort selection.  There appears to be some evidence that this is not sufficient and is causing e2e test flakes:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-federation/2510

```
I0331 20:31:25.848] I0401 03:24:49.018147       1 servicecontroller.go:580] Service 'e2e-tests-federated-ingress-fpnqr/federated-ingress-service' is not found in cluster federation-e2e-gce-us-central1-a, trying to create new
I0331 20:31:25.849] I0401 03:24:49.025434       1 servicecontroller.go:587] Failed to create Service "federated-ingress-service" is invalid: spec.ports[0].nodePort: Invalid value: 32589: provided port is already allocated
```

**Comment by cedriclam** [comment]
Hi, 
As a need contributor, I'm interesting of solving this issue.

I already check the current code, and propose to retry the service creation until success or all possible ports (between FederatedSvcNodePortFirst and FederatedSvcNodePortLast) have been tried.

If this approach is fine for you, I can submit a PR soon.

**Comment by madhusudancs** [comment]
How do you plan to check if the NodePorts are available? In our presubmit test environment, tests run across many instances of federation control planes in parallel, but share the same underlying clusters. So this approach might be viable depending on how and where you plan to check for these used NodePorts.

**Comment by cedriclam** [comment]
my approach for getting an available port is a "Dummy" approach: create a list of possible available port, get one of them randomly, then try to create the Service. If Service creation failed. try to use another possible available port, until service creation success or all possible available ports have been tested.

**Comment by madhusudancs** [comment]
Sounds reasonable to me. Go for it.

A couple of caveats: 
1. No need to create a real list, you could just use the range boundaries. 
2. Be careful about service creation failure. You need to check if the service shard creation failed in the underlying clusters and rollback all those shards before retrying.

**Comment by cedriclam** [comment]
@madhusudancs thanks for the caveats, I will do soon a PR.

**Comment by uiansol** [comment]
Hi, 
@cedriclam what is the state of this issue?
Is @madhusudancs working in this issues with the others issues related to e2e tests?

**Comment by madhusudancs** [comment]
@uiansol, @cedriclam has a PR to fix this issue - https://github.com/kubernetes/kubernetes/pull/45186
