### ISSUE TITLE
Volume mounted config maps are not accessible via exec process.

### ISSUE THREAD

**Issue by anandkumarpatel** [kubernetes/kubernetes#44012]
**Is this a request for help?** 
Not

**What keywords did you search in Kubernetes issues before filing this one?** 
config map not showing during exec

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT 

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T19:15:41Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
AWS, using latest stable `kops` `Version 1.5.3` with no modification. 

- **OS** (e.g. from /etc/os-release):
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- **Kernel** (e.g. `uname -a`):
```
Linux ip-10-4-33-33 4.4.41-k8s #1 SMP Mon Jan 9 15:34:39 UTC 2017 x86_64 GNU/Linux
```

**What happened**:
mounted `config maps` are not visible when `docker exec -it` into a container and navigating to the directory

**What you expected to happen**:
I am able to see the files mounted via `config map`

**How to reproduce it** (as minimally and precisely as possible):
Create a `deployment` and a `config map` with files. Mount the `config map` as a volume in the `deployment`

**Anything else we need to know**:
```
root@ip-10-4-33-33:/home/admin# docker inspect 45abded5c1f7
...
            {
                "Source": "/var/lib/kubelet/pods/d723fe86-15a1-11e7-a4ca-029f962170f3/volumes/kubernetes.io~configmap/ingress-proxy-sites-enabled-config",
                "Destination": "/etc/nginx/sites-enabled",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
```
files exist on host
```
root@ip-10-4-33-33:/home/admin# ls /var/lib/kubelet/pods/d723fe86-15a1-11e7-a4ca-029f962170f3/volumes/kubernetes.io~configmap/ingress-proxy-sites-enabled-config
api.conf  apisock.conf    drake.conf  egret.conf    eru.conf  optimus.conf    registry.conf  status.conf  user-pixel.conf
```
folder missing when running exec
```
root@ip-10-4-33-33:/home/admin# docker exec -it 45abded5c1f7 bash -c "ls /etc/nginx/sites-enabled"
ls: cannot access /etc/nginx/sites-enabled: No such file or director
```
But I know nginx is picking up those files since it is working correctly

**Comment by jagosan** [comment]
@anandkumarpatel perhaps a docker issue? trying to triage and not sure quite what to do with this one..  any suspicion you can share?

**Comment by kargakis** [comment]
@kubernetes/sig-storage-bugs @kubernetes/sig-node-bugs

**Comment by anandkumarpatel** [comment]
Don't have any suspicions at the moment. It's strange that the original process can access these files but not an exec process...
