### ISSUE TITLE
TestMetricsDuGetCapacity unit test fails on SLES 12 Go 1.8 ppc64le on master branch

### ISSUE THREAD

**Issue by vaibhavsood** [kubernetes/kubernetes#44022]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
TestMetricsDuGetCapacity
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
master branch (tip)

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
SLES 12
- **Kernel** (e.g. `uname -a`):
Linux pts00449-vm23 3.12.28-4-default #1 SMP Thu Sep 25 17:02:34 UTC 2014 (9879bd4) ppc64le ppc64le ppc64le GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
make test WHAT="./pkg/volume"
Running tests for APIVersion: v1,apps/v1beta1,authentication.k8s.io/v1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1,authorization.k8s.io/v1beta1,autoscaling/v1,autoscaling/v2alpha1,batch/v1,batch/v2alpha1,certificates.k8s.io/v1beta1,extensions/v1beta1,imagepolicy.k8s.io/v1alpha1,policy/v1beta1,rbac.authorization.k8s.io/v1beta1,rbac.authorization.k8s.io/v1alpha1,settings.k8s.io/v1alpha1,storage.k8s.io/v1beta1,storage.k8s.io/v1,federation/v1beta1
+++ [0404 11:22:46] Running tests without code coverage
--- FAIL: TestMetricsDuGetCapacity (0.01s)
        metrics_du_test.go:73: Unexpected Used for directory with file.  Expected 4096, got 65536.
FAIL
FAIL    k8s.io/kubernetes/pkg/volume    0.137s
Makefile:164: recipe for target 'test' failed
make: *** [test] Error 1

Test case failed
**What you expected to happen**:
Test case should pass

**How to reproduce it** (as minimally and precisely as possible):
make test WHAT="./pkg/volume"

**Anything else we need to know**:
Found this similar issue: https://github.com/kubernetes/kubernetes/issues/20028
However the values returned are different, see this string "Expected 4096, got 65536"

**Comment by Pensu** [comment]
Hi,

I am able to run that tests:

```
# make test WHAT="./pkg/volume"
Running tests for APIVersion: v1,apps/v1beta1,authentication.k8s.io/v1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1,authorization.k8s.io/v1beta1,autoscaling/v1,autoscaling/v2alpha1,batch/v1,batch/v2alpha1,certificates.k8s.io/v1beta1,extensions/v1beta1,imagepolicy.k8s.io/v1alpha1,policy/v1beta1,rbac.authorization.k8s.io/v1beta1,rbac.authorization.k8s.io/v1alpha1,settings.k8s.io/v1alpha1,storage.k8s.io/v1beta1,storage.k8s.io/v1,federation/v1beta1
+++ [0418 05:16:27] Running tests without code coverage
ok  	k8s.io/kubernetes/pkg/volume	0.129s
```

I am running RHEL ppc64le, latest k8s with go1.8, probably something specific to do with SLES?

**Comment by vaibhavsood** [comment]
I still get the error on SLES, updated the code to latest and using go1.8, maybe it is SLES (or my machine?) specific

#20028 talks about /tmp space, not sure if its related..

**Comment by vaibhavsood** [comment]
Hi @Pensu ,

Some investigation into this i found that the issue is due to the hardcoding on line 32 in ./pkg/volume/metrics_du_test.go

(similar from comments here: https://github.com/kubernetes/kubernetes/pull/18580#discussion-diff-47389629)

I changed it to remove the hardcoding (patch attached) and the test case passes on SLES as well, i am not sure if the patch is appropriate so requesting you to review it as appropriate


[metrics_du_test.txt](https://github.com/kubernetes/kubernetes/files/973139/metrics_du_test.txt)

**Comment by abdasgupta** [comment]
Hi Vaibhav,
Have you raised any PR on it? If raised, reviewing would be easier.
There is one thing I noticed:
```if e, a := (expectedEmptyDirUsage.Value() + getExpectedBlockSize(tmpDir)), actual.Used.Value(); e != a {```

In the above code, you are comparing actual used value with total of empty directory usage and expected block size. When you create a new file like "f1 created here with only "Hello World", it consumes 4K in Ubuntu/RHEL. This size is same as for an empty directory. What is this size in SLES? So, either you hardcode this value(conditional for SLES) or call getExpectedBlockSize() on f1 file path instead of tmpDir.

**Comment by vaibhavsood** [comment]
Hi @abdasgupta,

I have created the PR for the patch as suggested.. https://github.com/kubernetes/kubernetes/pull/46342


I have also changed the original patch slightly to use getExpectedBlockSize() on f1 file path instead of tmpDir as you suggested as that I think would be the right way to do it..

Thanks!
Vaibhav
