### ISSUE TITLE
TestNestedObject unit test fails on SLES 12 Go 1.8 on ppc64le on master branch

### ISSUE THREAD

**Issue by vaibhavsood** [kubernetes/kubernetes#44023]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
TestNestedObject, EmbeddedTest.Object
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
master branch 

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
SLES 12
- **Kernel** (e.g. `uname -a`):
Linux pts00449-vm23 3.12.28-4-default #1 SMP Thu Sep 25 17:02:34 UTC 2014 (9879bd4) ppc64le ppc64le ppc64le GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
make test WHAT="./vendor/k8s.io/apimachinery/pkg/runtime"
Running tests for APIVersion: v1,apps/v1beta1,authentication.k8s.io/v1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1,authorization.k8s.io/v1beta1,autoscaling/v1,autoscaling/v2alpha1,batch/v1,batch/v2alpha1,certificates.k8s.io/v1beta1,extensions/v1beta1,imagepolicy.k8s.io/v1alpha1,policy/v1beta1,rbac.authorization.k8s.io/v1beta1,rbac.authorization.k8s.io/v1alpha1,settings.k8s.io/v1alpha1,storage.k8s.io/v1beta1,storage.k8s.io/v1,federation/v1beta1
+++ [0404 11:28:47] Running tests without code coverage
--- FAIL: TestNestedObject (0.00s)
        embedded_test.go:200: Wire format is:
                {"apiVersion":"test.group/v1test","kind":"EmbeddedTest","id":"outer","object":{"apiVersion":"test.group/v1test","kind":"EmbeddedTest","id":"inner","object":null,"emptyObject":null},"emptyObject":null}

        embedded_test.go:244: Unexpected decode error json: cannot unmarshal object into Go struct field EmbeddedTest.Object of type runtime.Object
FAIL
FAIL    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime        0.092s
Makefile:164: recipe for target 'test' failed
make: *** [test] Error 1

Test case failed
**What you expected to happen**:
Test case should pass

**How to reproduce it** (as minimally and precisely as possible):
make test WHAT="./vendor/k8s.io/apimachinery/pkg/runtime"

**Anything else we need to know**:

**Comment by Pensu** [comment]
Hi,

Try adding "ContainsAny" in place of "Contains" at line no: 243 in staging/src/k8s.io/apimachinery/pkg/runtime/embedded_test.go. It should work.

**Comment by vaibhavsood** [comment]
Yes, this fixes it on SLES as well, thanks

**Comment by jagosan** [comment]
@vaibhavsood - has this change been upstreamed?

**Comment by vaibhavsood** [comment]
Yes, this is no longer a issue on the latest code base
