### ISSUE TITLE
Labels value: relax restrictions ?

### ISSUE THREAD

**Issue by MatMaul** [kubernetes/kubernetes#44045]
Would it be possible to relax the restrictions on the labels value ?

In our cloud the default availability zone is "-", and the OpenStack provider is putting this info into a label. The Kubelet then fails to register to the apiserver when validating the node descriptor.

Are these restrictions needed (to easily store them for example) or is it by spec only and could be relaxed ?
I am talking values here, not the label names.

If not, would you accept a patch that would ignore zone labels coming from a provider that don't match the regexp ?

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-feature-requests
