### ISSUE TITLE
Deleting a deployment doesn't delete the pods

### ISSUE THREAD

**Issue by vascofg** [kubernetes/kubernetes#44046]
**BUG REPORT**:

**Kubernetes version**: 1.6.1

**Environment**:
- **Hardware configuration**: 2 identical machines, with i7-2600K CPUs and 4GB RAM.
- **OS**: CentOS 7
- **Kernel**: 3.10.0-514.10.2.el7.x86_64
- **Install tools**: KubeADM

**What happened**:
Deleting a deployment via the API with the DeleteOptions settings `orphanDependants: false` or `propagationPolicy: Background` deletes the Deployment and the replica set but NOT the pods.
Deleting it with the DeleteOptions setting `propagationPolicy: Foreground` works as intended.

**What you expected to happen**:
The replica set deletion should propagate to the pods. I've read that the garbage collection should work for Deployments in 1.6.

**How to reproduce it**:

```
kubectl create -f https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/master/docs/concepts/workloads/controllers/nginx-deployment.yaml
curl -X DELETE localhost:8001/apis/extensions/v1beta1/namespaces/default/deployments/nginx-deployment -d '{"kind":"DeleteOptions","apiVersion":"v1","propagationPolicy":"Background"}' -H "Content-Type: application/json"
```

**Anything else we need to know**:
I am using the [Python Client](https://github.com/kubernetes-incubator/client-python/) and at the moment it only supports the orphanDependants option, since it's still at api version 1.5.

**Comment by kargakis** [comment]
cc: @caesarxuchao @krmayankk @enisoc

**Comment by caesarxuchao** [comment]
We discussed the problem in https://github.com/kubernetes/kubeadm/issues/149#issuecomment-278578812.

I'll change the GC to make sure it's cascading.

**Comment by caesarxuchao** [comment]
Sent #44058

**Comment by vascofg** [comment]
Any progress on this?

**Comment by caesarxuchao** [comment]
Still trying to figure out a sane fix: https://github.com/kubernetes/kubernetes/pull/44058#issuecomment-292682540

**Comment by fieryvova** [comment]
I've encountered the same issue. My pods are still running even though I deleted the deployment.

**Comment by kargakis** [comment]
@caesarxuchao lets come up with a fix for 1.7. This should work from the first time we introduced cascading deletion in Deployments.

**Comment by caesarxuchao** [comment]
@kargakis Yes, we should. Do you have any comments on https://github.com/kubernetes/kubernetes/pull/44058#issuecomment-292682540?

**Comment by kargakis** [comment]
@caesarxuchao replied. Let's move this forward. If the fix is small, I am going to backport it to 1.6.

**Comment by dchen1107** [comment]
Offline discussion with @janetkuo, we punt this to v1.8.

**Comment by caesarxuchao** [comment]
Discussed with @dchen1107, if we can get the PR https://github.com/kubernetes/kubernetes/pull/45764 fixed soon, it can still go in 1.7. It's a real bug fix.

**Comment by kargakis** [comment]
Yes, we need to fix this for 1.7 and also backport to 1.6.

**Comment by marun** [comment]
@liggitt Should this be targeting 1.7?

**Comment by liggitt** [comment]
yes, the fix in #45764 is going to cause us data issues we don't want

**Comment by marun** [comment]
@kargakis Are you working on this? What's the timeline to resolution?

**Comment by dchen1107** [comment]
Based on @liggitt above comment,  looks like #45764 actually introduced a new regression. Am I right?

**Comment by caesarxuchao** [comment]
In https://github.com/kubernetes/kubernetes/pull/44058, I reverted what's introduced in #45764.

**Comment by janetkuo** [comment]
@marun - @caesarxuchao is working on it

**Comment by dchen1107** [comment]
I approved this for 1.7 based on @liggitt's comment at https://github.com/kubernetes/kubernetes/issues/44046#issuecomment-310748733. I should revert #45764, but are we ok with @caesarxuchao's #44058 since it also introducing a new behavior. I will leave @kubernetes/sig-apps-bugs to decide.

**Comment by liggitt** [comment]
> @dchen1107:
> I should revert #45764, but are we ok with @caesarxuchao's #44058 since it also introducing a new behavior.

#44058 replaces #45764 with a fix that addresses this issue systemically. While this bug did exist in 1.6.x, more things rely on GC in 1.7 than in 1.6, and without that fix, GC leaves more resources vulnerable to unintentional orphaning.

> I will leave @kubernetes/sig-apps-bugs to decide.

Since the issue is actually with general GC behavior, @kubernetes/sig-api-machinery-bugs should weigh in.
