### ISSUE TITLE
[kube-apiserver] [kube-controller-manager] Flags involving certs & keys are confusing

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#44052]
It's extremely difficult to understand the various certs, keys, CAs, etc from the command line flag names and help strings.

Work items:
1. Make a doc, disambiguate all the various keys, clarify which aspects of the key (pub, priv, ca, cert, cert bundle) is needed and why.
2. Define a flag naming scheme that is consistent, e.g., `-<name>-{private-key|public-key|ca|cert|bundle}`
3. Change code, keep existing flag names for backwards compatibility, but deprecate them.
4. (2+ releases later) remove old flag names.

**Comment by lavalamp** [comment]
@cjcullen @liggitt @deads2k

**Comment by deads2k** [comment]
Making names consistent seems reasonable to me.

Do we take a specific CA (not a bundle) anywhere?  Seems like that should be changed.
