### ISSUE TITLE
Race condition with `ControllerClientBuilder` + `TokensController` + custom token controller

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#44054]
Currently it is possible to have the following race condition:

1. You have a custom token controller that acts on secrets when SAs are created (like the `TokensController`)
2. `ControllerClientBuilder` is used to build a SA for some controller
3. Both `TokensController` and the custom token controller create secrets for the SA
4. `ControllerClientBuilder` sees the secret for the SA, and starts the controller it was building
5. Both `TokensController` and the custom token controller try to update the SA and conflict
6. `TokensController` fails the update, and decides to delete the secret because of the conflict
7. The controller built by `ControllerClientBuilder` is now broken because its secret was deleted

It should be possible to fix the `TokensController` so that it is reentrant and does not try to delete secrets on conflict errors.

cc @liggitt @deads2k 

Seen in https://github.com/openshift/origin/pull/13579#issuecomment-291219349

**Comment by liggitt** [comment]
Keeping open to track client builder improvements

**Comment by liggitt** [comment]
Actually, client transport refresh is covered by https://github.com/kubernetes/kubernetes/issues/4672
