### ISSUE TITLE
kubernetes doesn't see any data from etcd after upgrade

### ISSUE THREAD

**Issue by tiukhtinvladimir** [kubernetes/kubernetes#44050]
Hello! My issue looks like a bug, but it's possible I'm doing something wrong. I was upgrading from 1.4.9 to 1.6.0. Downloaded binaries and restarted kube-apiserver with the same parameters. But 1.4.9 can see any configuration from etcd like pods, deployments etc. 1.6.0 can't.

**Environment**:
- self-hosted from binaries
- debian 9
- systemd supervisored

**Comment by dims** [comment]
@tiukhtinvladimir Please see https://kubernetes.io/docs/admin/upgrade-1-6/

**Comment by tiukhtinvladimir** [comment]
@dims thank you for the quick response. Ye,  I know it, but I have never used etcd v2 - started from etcd v3. Are there any etcd migrations I should perform? Rolled back 1.4.9 for the moment. Don't understand why 1.6.0 doesn't see any entries in etcd

**Comment by liggitt** [comment]
are you using a custom `--etcd-prefix`?

**Comment by tiukhtinvladimir** [comment]
Hello @liggitt! No, I am not using this option, so as default it should be /registry. And I am able to retrieve data with 'etcdctl ls /registry'. kube-apiserver 1.4.9 also can, but not 1.6.0 for some reason we want to find out

**Comment by tiukhtinvladimir** [comment]
Closing issue, sorry for disturbing - was my fault
