### ISSUE TITLE
Implement IPVS-based in-cluster service load balancing

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#44063]
At KubeCon Europe in Berlin last week I presented some work we've done at Huawei scaling Kubernetes in-cluster load balancing to 50,000+ services and beyond, the challenges associated with doing this using the current iptables approach, and what we've achieved using an alternative IPVS-based approach.  iptables is designed for firewalling, and based on in-kernel rule lists, while IPVS is designed for load balancing and based on in-kernel hash tables.  IPVS also supports more sophisticated load balancing algorithms than iptables (least load, least conns, locality, weighted) as well as other useful features (e.g. health checking, retries etc).

After the presentation, there was strong support (a.k.a. a riot :-)  ) for us to open source this work, which we are happy to do.  We can use this issue to track that.

For those who were not able to be there, here is the video:

https://youtu.be/c7d_kD2eH4w

And the slides:

https://docs.google.com/presentation/d/1BaIAywY2qqeHtyGZtlyAp89JIZs59MZLKcFLxKE6LyM/edit?usp=sharing

We will follow up on this with a more formal design proposal, and a set of PR's, but in summary we added a about 680 lines of code to the existing 12,000 lines of kube-proxy (~5%), and added a third mode flag to it's command-line (mode=IPVS, to the existing mode=userspace and mode=iptables).
Performance improvement of load balancer updates is dramatic (update latency reduced from hours per rule to 2ms per rule). Network latency and variability also reduced dramatically for large numbers of services.
 
@kubernetes/sig-network-feature-requests 
@kubernetes/sig-scalability-feature-requests 
@thockin 
@wojtek-t

**Comment by gyliu513** [comment]
Even though Kubernetes 1.6 support 5000 nodes, but the kube-proxy with iptables is actually a bottleneck to scale the cluster to 5000 nodes. One example is that with `NodePort` service in a 5000 node cluster, if I have 2000 services and each services have 10 pods, this will cause 20000 iptable records on each worker node, and this can make the kernel pretty busy. Using IPVS-based in-cluster service load balancing can help a lot for such case.

**Comment by ravilr** [comment]
@quinton-hoole is your implementation using IPVS in nat mode or Direct routing mode?

**Comment by haibinxie** [comment]
@ravilr it's NAT mode.

**Comment by timothysc** [comment]
gr8 work, the iptables issues has been a problem for a while. 

re: flow based scheduling, happy to help get the firmament scheduler in place.  ;-) 
/cc @kubernetes/sig-scheduling-feature-requests

**Comment by resouer** [comment]
@timothysc  I paid attention to firmament for a period of time, but not quite get it's value adding to kubernetes. Would you mind to explain what problem flow based scheduling can solve in current Kubernetes scheduler?

**Comment by timothysc** [comment]
@resouer speed at scale and rescheduling. 

From @quinton-hoole 's talk, linked above, it looks like huawei has been prototyping this.

**Comment by quinton-hoole** [comment]
@resouer @timothysc Yes, I can confirm that we're working on a Firmament scheduler, and will upstream it as soon as it's in good enough shape.  We might have an initial implementation in the next few weeks.

**Comment by deepak-vij** [comment]
Hi folks, we are currently working on implementing Firmament Scheduler as part of K8S scheduling environment. We will create a new separate issue to track the progress and provide updates etc. thanks.

**Comment by sureshvis** [comment]
@quinton-hoole thanks for sharing.  Waiting to see the design proposal. 

In term of Healthcheck, every worker doing health check across all pods to keep the table upto date?,   how are you planning to handle this @scale ?

**Comment by quinton-hoole** [comment]
cc @haibinxie

**Comment by quinton-hoole** [comment]
To be clear, @haibinxie did all the hard work here.  Please direct questions to him.

**Comment by MikeSpreitzer** [comment]
IPVS only deals with IP, not transport protocols, right?  A k8s service can include a port transformation.  A Service object has a potential distinction between `port` and `targetPort` in the items in the `spec.ports` list.  And an Endpoints also has a `ports.port` field in items in the `subsets` list.  Can your implementation handle this generality, and if not, what happens when the user asks for it?

**Comment by haibinxie** [comment]
@MikeSpreitzer Port transformation is well supported.

**Comment by thockin** [comment]
Note that even with IPVS, NodePorts, firewalls, and so on still have to be
handled and the obvious place to handle much of it is iptables.

**Comment by thockin** [comment]
Port mapping is handled in NAT mode (called masquerade by IPVS, sadly).  As an optimization, a future followup could enable direct-return mode for environments that support it for services that do not do remapping.  We'd have to add service IPs as local addresses in pods, which we may want to do anyway.

**Comment by thockin** [comment]
Last comment for the record here, though I have said it elsewhere.

I am very much in favor of an IPVS implementation.  We have somewhat more than JUST load-balancing in our iptables (session affinity, firewalls, hairpin-masquerade tricks), but I believe those can all be overcome.

We also have been asked, several times, to add support for port ranges to Services, up to and including a whole IP.  The obvious way to add this would also support remapping, though it is not at all clear how NodePorts would work. IPVS, as far as I know, has no facility for exposing ranges of ports.

**Comment by ChenLingPeng** [comment]
In IPVS mode, we have to add all the service address to host device like lo or ethx, am I right?

**Comment by thockin** [comment]
You only have to add it as an address in direct-return mode.  You should
also be able to simply add it to the local table, rather than actually
assign it as an interface address.

**Comment by ChenLingPeng** [comment]
Hi @thockin , in #17470 it shows that the `ip addr add` is needed in IPVS nat mode. I try the test script that skip the `ip addr add 10.9.8.7/32 dev eth0` step. It can't work. I also found that you said `We have to assign the VIP to some interface in the root NS.`

Another question, here we have containerA in hostA and containerB in hostB, now in my environment I can visit containerB in containerA via IPVS nat mode using vip directing to containerB, but how is it possible to visit from hostA to containerB via IPVS nat mode using vip?

**Comment by thockin** [comment]
On Mon, Apr 10, 2017 at 7:04 PM, Lingpeng Chen <notifications@github.com> wrote:
>
> Hi @thockin , in #17470 it shows that the ip addr add is needed in IPVS nat mode. I try the test script that skip the ip addr add 10.9.8.7/32 dev eth0 step. It can't work. I also found that you said We have to assign the VIP to some interface in the root NS.

ipvs alone doesn't define a route to that IP, so when you access it,
it goes out the default route.  You need the client to know how to
reach the IP.  Not sure how to do it for a whole range.

> Another question, here we have containerA in hostA and containerB in hostB, now in my environment I can visit containerB in containerA via IPVS nat mode using vip directing to containerB, but how is it possible to visit from hostA to containerB via IPVS nat mode using vip?

I don't know what might be wrong - all the research I did was in that bug...

**Comment by chenchun** [comment]
I found a way to implement both VIP service or nodeport via ipvs full-nat support according to http://archive.linuxvirtualserver.org/html/lvs-devel/2010-07/msg00033.html .

```
# In addition to IPVS dnat configure, you have to use iptables to do SNAT to a source IP which is reachable from container IP.
iptables -t nat -A POSTROUTING -m ipvs --vaddr $node_ip --vport 8888 -j MASQUERADE

# Enable ipvs conntrack as well to make SNAT works.
echo 1 > /proc/sys/net/ipv4/vs/conntrack
```

**Comment by haibinxie** [comment]
@ChenLingPeng we create an dummy interface and assign all vips to it.

**Comment by quinton-hoole** [comment]
Continuing to link other related conversations to this one, so that we can hopefully agree on and produce a working IPVS load balancing kube-proxy implementation sooner rather than later.

Thread in sig-networking mailing list: [IPVS backend in kube-proxy](https://groups.google.com/forum/#!topic/kubernetes-sig-network/59HG9SlypBc)

**Comment by quinton-hoole** [comment]
Wow!  I tried to skim-read most of the threads I could find on the topic of IPVS-based in-cluster service load balancing" (including those buried in other related threads, like the many on iptables-based load balancing).  While I cannot for one moment claim to have a clear picture in my head of exactly where we stand on all of the various problems, solutions etc, I can suggest that what we seem to need is some sort of explicit matrix of test cases (e.g. (cloud=AWS, GCE, ..) x (service_type=NodePort, LoadBalancer,...) x (client_type=Pod, external-to-cluster,...) x (container_network=Flannel, Weave,...) ) so that we can start ticking off what's solved and tested, and what remains.  Initially we could start with manual tests, and automate them over time.

@haibinxie Sound sensible?  It's not yet clear to me how much of this matrix has already been tested for the implementation proposed in this issue.

@kubernetes/sig-network-misc @thockin Does such a test matrix, or moral equivalent already exist for e.g. testing the iptables kube-proxy implementation?  If so, perhaps we could, erm, 'leverage' that.

My apologies for diving in trying to help here without having been actively involved in SIG-networking in the past, and I hope my input here is net-positive rather than just adding to the noise due to my lack of historical context.  It seems like we've had so many runs at this problem in the past that have ended up incomplete for a variety of reasons, so it would be really great to drive this one to completion for once and for all, if it is indeed feasible.  I'm happy to help with this.

**Comment by freehan** [comment]
Please feel free to test your implementation with existing e2e tests.

Most of the service related tests is as follows:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/service.go
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/networking.go

**Comment by haibinxie** [comment]
@quinton-hoole it was tested over flannel, most of the functionalities are covered includes nodePort, externalIP and various source-dest traffic such as container-to-container (same host and cross host), host-to-container (same host and cross host) etc.  

I do agree that various plugin and cloud providers (AWS, GCE) may work differently, we need to test them to make sure they all work.

**Comment by murali-reddy** [comment]
@haibinxie How is the reverse path traffic from pod to client is handled? Do you use SNAT? I had some challenges to getting IPVS service proxy to work with network policies. Pleasee see my observations in #17470

**Comment by thockin** [comment]
If you pass the existing e2e tests, you're doing pretty well.

**Comment by m1093782566** [comment]
@quinton-hoole @haibinxie Do you have plan to support Full NAT mode?

**Comment by haibinxie** [comment]
@murali-reddy @m1093782566 there is a patch to apply for enabling full NAT mode. that will impact the network policy if you rely on source ip.

**Comment by ChenLingPeng** [comment]
@haibinxie So is there any problems we should care if we have thousands VIP in dummy interface?

**Comment by haibinxie** [comment]
@ChenLingPeng not i am aware of

**Comment by wojtek-t** [comment]
> If you pass the existing e2e tests, you're doing pretty well.

Yes - that's definitely true. If you implementation is passing all existing e2e tests, in my opinion we can merge this implementation.

**Comment by timothysc** [comment]
I'll wait till the PR comes in but we might want to have a dual building similar to what was done with etcd.

**Comment by warmchang** [comment]
Nice job!

**Comment by haibinxie** [comment]
Hi All, I put together a proposal for the alpha version of IPVS implementation hoping to get into kubernetes 1.7. need your feedback.

https://docs.google.com/document/d/1YEBWR4EWeCEWwxufXzRM0e82l_lYYzIXQiSayGaVQ8M/edit?usp=sharing

@kubernetes/sig-network-feature-requests
@kubernetes/sig-scalability-feature-requests
@thockin 
@wojtek-t

**Comment by dhilipkumars** [comment]
FYI
if docker accepts this PR, we may be able to loose seesaw (libnl.so) dependency.  https://github.com/docker/libnetwork/pull/1770

**Comment by gyliu513** [comment]
Does the [kube-router](https://github.com/cloudnativelabs/kube-router) can help this?

**Comment by thockin** [comment]
Have we seen code for this yet?  At this point, there's simply no way it is
making v1.7, but I'd love to queue up something here for v1.8

**Comment by quinton-hoole** [comment]
Code is done and going through final e2e testing. The plan is to get it
into v1.8.

**Comment by thockin** [comment]
But nobody has seen it yet?  Publish early and often.  You *know* there's
going to be a lot of feedback - get that code out now now now.  Don't sit
on it.  Don't polish it.  PUBLISH.  Or risk that it doesn't get merged
because of the depth of feedback, or that someone else implements it while
you're busy polishing.

We have a fairly robust e2e suite.  You should be able to just boot with
this enabled and if it passes e2e, that's a strong signal.

**Comment by dujun1990** [comment]
@thockin @quinton-hoole 

Initial PR #46580 is already sent out.

**Comment by dhilipkumars** [comment]
@thockin originally we were relying on seesaw library and had a plan of updating it to a pure go implementation as phase 2 (probably in 1.8).  Because of the complexities introduced by libnl.so dependencies last week we decided to move away from `seesaw`.    Docker's libnetwork had a good set of ipvs apis but was missing GETXXX() methods.  We quicky contributed to libnetwork and that got merged 3 days ago.   Now we have vendored libnetwork.  PTAL.

**Comment by m1093782566** [comment]
IPVS-based kube-proxy is in beta phase now.

**Comment by chrishiestand** [comment]
With this issue closed as stale, is there a better issue to follow progress of adding ipvs scheduling algorithms to individual kubernetes services? I couldn't find another issue that explicitly covers this part of the ipvs roadmap.

**Comment by arzarif** [comment]
@chrishiestand 

It's mentioned [here](https://kubernetes.io/blog/2018/07/09/ipvs-based-in-cluster-load-balancing-deep-dive/) as a future possibility, but like you, I haven't been able to find an issue where this is being actively discussed/worked on. Does anyone know whether there's ongoing work to make service-specific load-balancing algorithms possible?
