### ISSUE TITLE
GPU detection should poll

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#44080]
The new Accelerators=true feature-gate enables auto-detection of GPUs.  But I believe it does not detect hot-plugged GPUs; kubelet must be restarted for the GPUs to be detected and reported in the Node.  At least I believe that is the case.

What I'm actually doing here is not hot-plugging the device, but rather starting kubelet and at the same time starting the nvidia driver installation.  About 5-10 minutes later the nvidia driver is ready and the devices appear, but kubelet does not auto-detect them.

(If there is a better way to install the nvidia drivers, that would be great to know as well)

cc @vishh

**Comment by cmluciano** [comment]
It looks like we note this once [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go#L80). 

This is initiated [here](https://github.com/kubernetes/kubernetes/blob/4d8ffb23effecb470f13004ddfb6d4aefa10e129/pkg/kubelet/kubelet.go#L1222)

And then I *think* that these modules are synced once [here](https://github.com/kubernetes/kubernetes/blob/4d8ffb23effecb470f13004ddfb6d4aefa10e129/pkg/kubelet/kubelet.go#L1249-L1252)

**Comment by vishh** [comment]
@justinsb nvidia driver installation requires a reboot and so even if you install the drivers after starting the kubelet, the restart would result in kubelet working correctly.

**Comment by vishh** [comment]
I think it would be useful to support hot-plugs too, but I'm hoping that will be a new feature instead of a bug in the current implementation.

**Comment by justinsb** [comment]
AFAICT @vishh you do _not_ need to reboot to install the nvidia driver.  You can see the WIP docker image I'm using to install the nvidia drivers here: https://github.com/kubernetes/kops/pull/2298/files

What technique are you using to install the nvidia drivers?  It might be that mine is broken (subtly or otherwise!)

**Comment by vishh** [comment]
@justinsb you are correct. The [GCE instructions](https://cloud.google.com/compute/docs/gpus/add-gpus#verify-driver-install) are missing a modprobe I think. 

This is an issue and I think we should fix it in a patch release. @cmluciano want to pick this up?

**Comment by cmluciano** [comment]
I'd be delighted.

**Comment by cmluciano** [comment]
@justinsb I looked at your PR and noted your comment on nvidia-uvm needing that modprobe. Apparently this is just a "thing" and I even found this in the [mesos gpu isolator](https://github.com/apache/mesos/blob/master/src/slave/containerizer/mesos/isolators/gpu/isolator.cpp#L162-L171).

Pooling makes sense since GPUs are more susceptible to issues under stress. What do we think is an acceptable period to poll at?

**Comment by vishh** [comment]
Kubelet cannot handle changes to capacity over time. So support for
hot-plugging will be tedious. We can start with a one shot discovery that
is run in a loop until it succeeds. We can retry every minute.

Kubelet can identify the number of nvidia GPUs on a node by reading
`/proc/bus/pci/devices` and looking for devices with vendor ID `10de`. Once
it knows the number of GPUs, kubelet can retry GPU device discovery logic
until all the required number of character device files exist. Essentially
it's all or nothing.

**Comment by cmluciano** [comment]
I have an implementation working locally that reads the procfile and determines the expected # of GPUs to be found in /dev. 

I am now considering the retry logic but I'm concerned with blocking the startup of the Kubelet until the drivers/kube modules are initialized.  

It seems that Kops hooks will make the install of drivers happen in parallel but for those taking a serial installation approach, we may hang indefinitely awaiting driver installation.

**Comment by vishh** [comment]
I don't think we should retry in the kubelet startup path. Instead we
should keep retrying in the background and fail any GPU allocation calls
until discovery is completed.

**Comment by flx42** [comment]
> The GCE instructions are missing a modprobe I think.

No I think they are fine, you only need to call `nvidia-modprobe` when you use containers.

**Comment by vishh** [comment]
> No I think they are fine, you only need to call nvidia-modprobe when you use containers.

Is this currently handled by `nvidia-docker`?

**Comment by flx42** [comment]
@vishh Yes. We used to call `nvidia-modprobe -u -c=0` only when `/dev/nvidia-uvm` was not present, but we know call it every single time (making `nvidia-modprobe` a dependency) because there were issues with the previous approach:
https://github.com/NVIDIA/nvidia-docker/commit/16a7d7da6467d7e772dd04e1f28d4786dccb73c9

**Comment by vishh** [comment]
The assumption that `nvidia-docker` will be used in k8s deployments is
currently not valid. That's why I felt the GCE instructions are not valid
and that it should include an explicit `modprobe`.

**Comment by flx42** [comment]
I know, but the GCE instructions are not only for containers/Kubernetes, right?
If you launch any CUDA code outside of a container, `nvidia_uvm` will be loaded automatically.
A call to `nvidia-modprobe` wouldn't hurt, but you will also need to do that when restarting the instance.

**Comment by vishh** [comment]
> I know, but the GCE instructions are not only for containers/Kubernetes,
right?

Totally! I wonder how/why including a modprobe in that list would hurt.

> If you launch any CUDA code outside of a container, nvidia_uvm will be
loaded automatically.

Glad to know this.

> A call to nvidia-modprobe wouldn't hurt, but you will also need to do
that when restarting the instance.

Just to clarify, k8s is not attempting to invent a new packaging scheme for
nvidia drivers. Don't the existing packaging scripts (deb, rpm, etc) handle
modprobe on reboots?

**Comment by flx42** [comment]
> Don't the existing packaging scripts (deb, rpm, etc) handle modprobe on reboots?

You mean through udev rules? It depends.
With a driver install through a 'NVIDIA-Linux-x86_64-${VERSION}.run` script, it won't be the case.
Actually, you can't even assume that **any** device in `/dev/` will be created, even if the driver is loaded.

**Comment by vishh** [comment]
@flx42 
>You mean through udev rules? It depends.

Yes.

> Actually, you can't even assume that any device in /dev/ will be created, even if the driver is loaded.

Hmm. Is there some documentation around setting up Nvidia drivers?

**Comment by flx42** [comment]
> Hmm. Is there some documentation around setting up Nvidia drivers?

http://docs.nvidia.com/cuda/cuda-installation-guide-linux/#axzz4eGJHmY51

Particularly, you might be interested by this script:
http://docs.nvidia.com/cuda/cuda-installation-guide-linux/#runfile-verifications
(But it's a bit hacky, it's better to use nvidia-modprobe when you can).

On a ubuntu machine, I recommend simply using those 3 lines:
```
sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
sudo sh -c 'echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/cuda.list'
sudo apt-get update && sudo apt-get install -y --no-install-recommends linux-headers-generic dkms cuda-drivers
```
This will install the right udev rules. Unfortunately, we can't assume everyone will use this method.

**Comment by vishh** [comment]
@flx42 I'm working on providing a generic framework for installing nvidia drivers across distros using a DaemonSet. I think we can hide some of this complexity there and have most k8s users follow this recommended method. I would love to collaborate with you on that if you can afford some time.

**Comment by flx42** [comment]
I won't be able next week (unless you're also attending DockerCon?). I might be able to help later.

I think it's going to be challenging to have a truly cross-distro method, some users will use `.run` files, other will use the official packages. CoreOS Container Linux is particularly [complicated](https://github.com/Clarifai/coreos-nvidia)

**Comment by cmluciano** [comment]
I think we agreed that this feature is not possible since GPU machines require a reboot. I'm closing for now, but can re-open later.

**Comment by vishh** [comment]
It's still not clear if reboots are necessary for driver installation. Is
there any documentation from Nvidia requiring reboots tfor jus tdriver
installation and not hot plugging?

**Comment by cmluciano** [comment]
I have not found explicit documentation yet, just notes that you should. I know my laptop requires a reboot when I swap out driver versions, but I don't know what happens if you don't. @flx42 can you point us to any docs on this?

**Comment by flx42** [comment]
From the official [CUDA documentation](http://docs.nvidia.com/cuda/cuda-installation-guide-linux/#runfile-installation):
> 6. Reboot the system to reload the graphical interface.

The instructions are also valid for headless nodes.

When you install the driver using the Ubuntu deb package:
```
*****************************************************************************                                                                                                                                                                                                  
*** Reboot your computer and verify that the NVIDIA graphics driver can   ***                                                                                                                                                                                                  
*** be loaded.                                                            ***                                                                                                                                                                                                  
*****************************************************************************     
```

**Comment by vishh** [comment]
cc @Amey-D

**Comment by cmluciano** [comment]
Apologies, I meant to only close my PR, not the issue.

**Comment by spiffxp** [comment]
/remove-priority P1
/priority important-soon
(I'm not actually sure this is the right priority, just trying to remove the old priority/PN labels)
