### ISSUE TITLE
Infrastore for Kubernetes

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#44095]
Internally at Google Infrastore is a repository of data about Google infrastructure, which drastically improved debugging experience for Borg users and became a foundation of a number of systems like Autopilot or Sigma. It was described in [Borg paper](https://static.googleusercontent.com/media/research.google.com/pl//pubs/archive/43438.pdf):
```
Borg records all job submissions and task events, as well
as detailed per-task resource usage information in Infrastore,
a scalable read-only data store with an interactive SQL-like
interface via Dremel [61]. This data is used for usage-based
charging, debugging job and system failures, and long-term
capacity planning. It also provided the data for the Google
cluster workload trace [80].
```

We want to build a similar system for Kubernetes project.

**Comment by piosz** [comment]
cc @davidopp @fgrzadkowski @kgrygiel @smarterclayton

The plan is to start discussions about the shape a requirements for the project in Q2 and then start design and implementation in Q3.

Related issues: #36304, #10782, #4432, #3692.

**Comment by smarterclayton** [comment]
@soltysh for intersection with audit, @kubernetes/sig-api-machinery-misc for intersection with admission

**Comment by fgrzadkowski** [comment]
Should we file an issue in kubernetes/features repo?

**Comment by piosz** [comment]
How about starting with just brainstorming here and once we know what we want to do I'll file an issue in features repo?

**Comment by soltysh** [comment]
@piosz @fgrzadkowski can you have a look at https://github.com/kubernetes/features/issues/22 and https://github.com/kubernetes/community/pull/145 and comment what we should add in your opinion in audit to help you get what you need?

**Comment by smarterclayton** [comment]
Audit isn't really infrastore, although audit is a source of info that should be correlateable into something like infrastore.

**Comment by fgrzadkowski** [comment]
+1 to what @smarterclayton said. Infrastore would contain information like what pods run and when and for how long. Or how many endpoints a given service had.
