### ISSUE TITLE
StatefulSet pods lack name label

### ISSUE THREAD

**Issue by brmakana** [kubernetes/kubernetes#44103]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5+coreos.0", GitCommit:"e2cd7718ba844e874a68aa13f8f5bb0728b415bb", GitTreeState:"clean", BuildDate:"2017-03-22T01:59:35Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Container Linux by CoreOS stable (1298.7.0)
- **Kernel** (e.g. `uname -a`): Linux ip-10-0-38-22 4.9.16-coreos-r1 #1 SMP Fri Mar 31 02:07:42 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz GenuineIntel GNU/Linux
- **Install tools**: 
- **Others**:

**What happened**:
When you deploy non-statefulset pods, they will be given a label called "name" with the pod name. However, with StatefulSets, pods do not have a name label. This means you can't write Services that use a selector based on the 'name' label. 

You can of course put labels in the StatefulSet definition, but those won't be unique per pod. Example - I can deploy a StatefulSet of Kafka pods, add a label "app=kafka", but each pod has that label and it's not unique. 

**What you expected to happen**:
Pods deployed from a StatefulSet should have a 'name' label with the name of the pod (the name that you see when you do kubectl get pods)

**How to reproduce it** (as minimally and precisely as possible):
1. Create a StatefulSet
2. kubectl describe pods <the pod> 
3. Notice the lack of a 'name' label 

**Anything else we need to know**:
An example of when this is needed would be deploying something where each pod needs to be individually reachable. Kafka is a good example: you want to have stateful storage and identity for the brokers, but you also need to be able to reach each one, which means you need a service per pod. 

Currently I have not found a way to automatically have a Service associated with a StatefulSet pod via labels; I've had to manually tag the StatefulSet pods to take advantage of Selectors.

**Comment by kargakis** [comment]
@brmakana which component adds name labels by default?

cc: @kubernetes/sig-apps-feature-requests

**Comment by kow3ns** [comment]
@brmakana This sounds more like a feature request than a bug report. I have a few questions, and I'd like to understand your use case better.

1. How are you standing up a service per pod?
     1. Are you manually creating each service? 
     1. How does this interact with scaling?
1. Are you trying to solve the problem of having a unique, public network identity for each Pod? If so, I think this issue is captured [here](https://github.com/kubernetes/kubernetes/issues/28660) and there is an open proposal [here](https://github.com/kubernetes/community/pull/446). If this is the case you should consider contributing to the discussion there instead of opening a new issue.

**Comment by brmakana** [comment]
@kargakis Sorry, I'm new to k8s and am not familiar with the internals. 

@kow3ns Sure if you think this should be a feature I can change. It felt like a bug though, because 'kubectl get pods', etc makes it seem like the StatefulSet pods are like any other pods and have the 'name' label (otherwise, how does kubectl know what to print for 'name') when they're slightly different. 

Right now to work around this, I manually label each pod after the StatefulSet starts up to allow a Service per pod. Not the best as it's manual. 

For #2, that does seem pretty similar (I want each pod to be publicly accessible). However the suggestions seem to be rather more complicated than I'd expect - if the StatefulSet pods had a "name" label like other pods, that seems like the shortest putt.

**Comment by rideswitch** [comment]
I have the same question.  I am using statefulsets for redis because I need stable names so that I can cluster the containers.  I have redis-0.redis .. redis-n.redis.  The problem is that since statefulsets use a headless service (obviously in this case named 'redis'), I don't see a way to address these from outside (Cluster-ip is None).  So my idea was to create a regular service for each one of them after they already exist.  The problem is that there is no identifying label on a per pod basis with which to select and form a service.  I would have hoped that there was a label like name=redis-0 .. name=redis-n.  What is the "normal" way to handle addressing a statefulset container from outside the cluster (where we would have normally used a non-headless service)?

**Comment by brmakana** [comment]
Has anyone else had a look at this? How are folks normally targeting services to statefulset pods right now?

**Comment by leoxlin** [comment]
+1 on this issue. 

We are looking to use statefulsets for zookeeper and hdfs namenodes but want to use a clusterIP service per pod. It is to select an individual pod from the statefulset right now due to the lack of a name label or sort.

**Comment by ashokkkannan** [comment]
+1 
We are using statefulsets for kafka. For accessing kafka from outside they need to talk to a particular pod and hence there is a requirement to create service per pod

**Comment by carsonoid** [comment]
+1
We need this for kafka as well

**Comment by kylefransham** [comment]
A workaround for this issue:

You can use [initContainers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers) to start a container that contains kubectl that dynamically labels the pod with the hostname. Then you can define services that use your selector. 

For example, a statefulset with an init container looks like:

 ```---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: my-stflset
  labels: 
    app: my-stflset
spec:
  replicas: 2
  serviceName:my-stflset-headless
  template:
    metadata:
      labels:
        app: my-stflset
    spec:
      initContainers:
      - name: label-set
        command: ["/usr/local/bin/kubectl label pods ${HOSTNAME} set-component=${HOSTNAME}"]
        image: my.private.registry/k8s/kubectl
      containers:
      - name: my-stflset
        image: my.private.registry/k8s/my-stflset
        ports:
        - name: client
          containerPort: 32000
```
 
and the service to target the individual pods in the service is something like: 

```
---
apiVersion: v1
kind: Service
metadata: 
  name: my-stflset-0
  labels: 
    app: my-stflset-0
spec:
  type: NodePort
  ports:
  - name: client
    port: 30000
  selector:
    set-component:my-stflset-0
```

Then even if the pod restarts, it'll get applied with the same label and the service will pick it up. 

Note: I did this in a separate namespace and had to create a service account and clusterrolebinding for it to work... Not sure if that's necessary in the default namespace, but my spec is included below in case it helps anyone out: 

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: my-stflset
  name: my-stflset
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: my-stflset
  labels:
    k8s-app: my-stflset
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: my-stflset
  namespace: test
```

**Comment by AleiHanami** [comment]
@kylefransham 
got this error in k8s 1.6.4, using the [k8s-kubectl](https://hub.docker.com/r/lachlanevenson/k8s-kubectl/) image:
```bash
Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"exec /usr/local/bin/kubectl\": stat exec /usr/local/bin/kubectl: no such file or directory".
``` 
and I solved this by changing command to 
```yaml
command:
        - sh
        - '-c'
        - '/usr/local/bin/kubectl label pod ${HOSTNAME} set-component=${HOSTNAME}'
``` 
then it works like a charm, Thank you for the solution!

**Comment by lghinet** [comment]
hello, 
@AleiHanami can you share your solution please ? 
do you have 3 kafka brokers and 3 services with NodePort each pointing to one pod ? 

how does your advertised.listeneres looks like ?
thanks

**Comment by AleiHanami** [comment]
@lghinet 
I've not ported my Kafka cluster to k8s yet. In my case I run SolrCloud on K8s, and the hostname is 'solrcloud-{ordinal}' (which is exactly the service name for each pod of the SolrCloud statefulset). then, for outside accessing, I use the Nginx Ingress Controller to route the traffic according to the domain name 'solrcloud-{ordinal}'
But, AFAIK, Kafka use TCP, use [keepalived](https://github.com/kubernetes/contrib/tree/master/keepalived-vip) to set up VIP for each Kafka service is a possible solution, and I will try this when we port Kafka cluster to k8s.

**Comment by asktomsk** [comment]
Currently you can use ExternalName Service to achieve it. Not too convenient thou (you need to have headless service to for DNS)

```apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    app: myapp
spec:
  type: ExternalName
  externalName: pod-1.mypodsvc.default.svc.cluster.local
```

**Comment by outkaj** [comment]
@kylefransham thanks for the idea! is it possible to do some sort of wildcard for the service or does your solution require the creation of a separate service for each pod? ideally, i would like to do something like: 

```
---
apiVersion: v1
kind: Service
metadata: 
  name: my-stflset-*
  labels: 
    app: my-stflset-*
spec:
  type: NodePort
  ports:
  - name: client
    port: 30000
  selector:
    set-component:my-stflset-*
```

**Comment by franshamk** [comment]
@outkaj I always manually defined a separate service for each pod in advance. 

As a wild idea,  you could implement some sort of dynamic solution by using the initContainer to start the service also.  You'll have to wildcard the port too, since different services can't share the same client port.

**Comment by 11xor6** [comment]
To anyone coming to this issue and looking for a solution this [article](https://itnext.io/exposing-statefulsets-in-kubernetes-698730fb92a1) provides a good solution since the addition of the `statefulset.kubernetes.io/pod-name` label.
