### ISSUE TITLE
E2E Volume tags should not include [Feature:Volumes] || [Disruptive]

### ISSUE THREAD

**Issue by copejon** [kubernetes/kubernetes#44112]
@jeffvance @msau42

The `[Volume]` tags that span all volume tests in E2E are useful for spanning an array a storage test suites.  However, this point is defeated by the fact that they include `[Disruptive]` and `[Feature]` tests.  This creates a default test set that is guaranteed to have failures (Features) and likely to have to have flakes (Disruptive side effects).

Excluding `[Volume]` from those test sets is probably the easiest solution but could also hide these non-standard volume tests from devs who want to run them all.

I'd like to get your input on this before making any changes.  Should we remove the tag from non-standard tests?  Or should we look at a more complicated tagging scheme for volume tests?

**Comment by copejon** [comment]
@msau42 It's possible to manually do this, though it's not be immediately obvious if you expect all tests to pass e.g.
`--ginkgo.focus="\[Volume\] --ginkgo.skip="[Feature:.*]|\[Disruptive\]"`

I like the idea of a Volume superset with subsets.  It might look something like
`[Volume:Disruptive]`
`[Volume:Feature]`
`[Volume]`

Though this will lengthen describe line a bit.

**Comment by msau42** [comment]
Another thing to consider is that moving towards putting all the e2e tests under component directories could help reduce the need for a separate [Volume] tag.  Although there would still be an issue with how to handle multi-component tests.

**Comment by jeffvance** [comment]
@msau42 ... and all volume tests minus (feature + disruptive).
I *believe* the main (only?) value of "[Volume]"  is as a target for `--gingko.focus` used primarily by developers. Do you know if CI uses `focus=[Volume]`?
If CI does not focus on [Volume] then I am in favor of this pr
If CI does use focus on [Volume] then I like Michelle's suggestion. The tags could be:
```
[Volume]  // *all* Volume tests as we have today
[Volume:-Feature]
[Volume:-Disruptive]
[Volume:-Feature+Disruptive]
```
I'm trying to figure out if a regexp with negative lookahead will work for `focus=`...
@kubernetes/sig-testing-misc @saad-ali

**Comment by msau42** [comment]
CI does not use the [Volume] tag.  It's just meant as a convenience for storage developers to run all the volume-related tests if they're changing some common code.

**Comment by jeffvance** [comment]
FWIW this grep finds all [Volume] tests that are not [Feature:Volumes]:
`grep -R -P '(?!\[Feature:Volumes\])\[Volume\]' test`

**Comment by msau42** [comment]
I would prefer that the tags not be mutually exclusive, and developers can decide at their discretion what tags to skip.  It adds some extra burden if you want to add/remove a tag, and then remember that you have to add/remove the [Volume] tag also.

**Comment by jeffvance** [comment]
Today we can do:
` --ginkgo.focus='[Volume] --ginkgo.skip='[Feature:Volumes]|[Disruptive]'`

**Comment by copejon** [comment]
Okay, so it sounds like the preferred pattern would be to tag all storage tests with `[Volume]` and let devs make use of the `--ginkgo.skip` to weed out disruptive and feature.

**Comment by jeffvance** [comment]
@copejon I think so...

**Comment by copejon** [comment]
Cool, this sounds fine.  Will close the issue.
