### ISSUE TITLE
Add node e2e test for security context

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#44118]
We have e2e tests for security context but it is not enabled anywhere currently (#16456).

We should also add security contexts to node e2e tests and enabled by default for all PRs (https://github.com/kubernetes/kubernetes/pull/44097#issuecomment-291923300). 

- [x] hostPid #44119
- [x] hostNetwork #45004
- [x] hostIPC #45006
- [x] Capabilities
- [x] Privileged #48857
- [x] ReadOnlyRootFilesystem #48858
- [x] SupplementalGroups/FSGroup
- [x] RunAsUser/RunAsNonRoot
- [x] Seccomp
- [x] SELinuxOptions

cc @kubernetes/sig-node-pr-reviews

**Comment by dchen1107** [comment]
Thanks for introducing those tests. Move this to 1.8 for more test coverage.

**Comment by feiskyer** [comment]
Not completed yet, move to v1.9.

**Comment by swatisehgal** [comment]
/triage accepted
/priority important-long-term
/area kubelet

@

**Comment by swatisehgal** [comment]
@feiskyer Are you still working on this or we need to identify a new assignee?

**Comment by saschagrunert** [comment]
I think this one can be closed.
