### ISSUE TITLE
Make strategic merge patch versioned

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes#44123]
Make strategic merge patch versioned.
Two options about how to use this:
1) Client discovers the patch versions that server supported. Then client chooses the latest version that both support.
2) Client sends the latest patch version. The server rejects the new patch (maybe returns 400). The client falls back to the earlier version.

We only support 1 version skew. So we only need to maintain 2 versions of patch logic.

Version skew between client and server that one supports version, one doesn't support.
- client w/ version vs server w/o version: old server rejects the new versioned patch new client sent. Then the client sends an old patch w/o version.
- client w/o version vs server w/ version: server process an old patch using its old logic.

It is not clear where should the version info lives. Maybe in header? If so how can the old server w/o version reject the new patch w/ version?

cc: @pwittrock @liggitt

**Comment by liggitt** [comment]
> Make strategic merge patch versioned.

This adds another dimension of versioning to an aspect of the API that is already quite complex... what problem is this trying to solve?

> We only support 1 version skew

One version skew for kubectl, but not for arbitrary clients. I would not expect an API request that worked in 1.5 to stop working in 1.7

**Comment by ymqytw** [comment]
We usually struggles with how to fix issues with strategic merge patch and not break backward compatibility.
I thought versioning patch will help to mitigate this pain. But this actually may cause more difficulty in maintaining the APIs. Versioning patch may not be a good approach.

cc: @lavalamp 

Also see: https://github.com/kubernetes/kubernetes/issues/44111#issuecomment-292380663

**Comment by pwittrock** [comment]
@liggitt 

@ymqytw and I talked a bit about how to maintain version compatibility yesterday and are going to write a doc and I would love to get your feedback on (once published).  One consequence of maintaining compatibility with unversioned APIs is that it limits the ways that we can change the API and results in a less aesthetically pleasing protocol definition.  Despite that, I agree with you that it is the simpler way to go, and we can revisit the PATCH schema / protocol in strategicmerge v2.0

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-feature-requests
