### ISSUE TITLE
Flaky SchedulerPriorities e2e 

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#44127]
Failed: [k8s.io] SchedulerPriorities [Serial] Pod should be schedule to node that don't match the PodAntiAffinity terms {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:308
Expected
    <string>: gke-bootstrap-e2e-default-pool-816be1af-vglg
not to equal
    <string>: gke-bootstrap-e2e-default-pool-816be1af-vglg
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:307
```

Failed: [k8s.io] SchedulerPriorities [Serial] Pods should be scheduled to low resource use rate node {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:108
Expected
    <string>: gke-bootstrap-e2e-default-pool-816be1af-vglg
to equal
    <string>: gke-bootstrap-e2e-default-pool-816be1af-z1fs
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:107
```

**Comment by k82cn** [comment]
xref #37898

**Comment by timothysc** [comment]
Where possible we should leverage the canonical results.  I find these automated bot results to be worthless.. 

xref: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=SchedulerPriorities

**Comment by wanghaoran1988** [comment]
Sorry to see this late, priorities e2e test is harder than predicates now, they will interfere each other with all the priority function enable, but I am glad the bobby is working on the dynamic change of the policy file, I think we'd better to test each priority function individually with only that function only enabled,  and I will update the tests after #43892 get in.

**Comment by bsalamat** [comment]
@wanghaoran1988 #43892 is in. Can you work on this issue now? It looks like our scheduler priority tests are failing rather frequently.

**Comment by wanghaoran1988** [comment]
@bsalamat Yeah, I am working on that, I cannot reproduce this on my 3 node cluster on GCE after I run really a long time, I will try the new way from today.

**Comment by k82cn** [comment]
@wanghaoran1988 , I think you can create a WIP PR with some instrument code to see what happen's in CI environment.

**Comment by wanghaoran1988** [comment]
@k82cn Good suggest! Will have a try.

**Comment by k82cn** [comment]
> @k82cn Good suggest! Will have a try.

Just a kindly reminder, please limit the re-try count; it'll increase the workload of CI environment which should avoid as much as possible :).

**Comment by wanghaoran1988** [comment]
@k82cn Would you mind point me how can I trigger these e2e test cases one by one? I will appreciate.

**Comment by k82cn** [comment]
I think you can find the command from some failed PRs :).

Do you have any clue here? I suggest not to debug by CI environment.

**Comment by wanghaoran1988** [comment]
@k82cn No, I'd prefer to revert that commit, and instead , use changing  policy configmap for the test, but I need our e2e testing cluster scheduler using configMap by default.

**Comment by bsalamat** [comment]
@wanghaoran1988 Given the frequency of failures, especially [`[k8s.io] SchedulerPriorities [Serial] Pods created by ReplicationController should spread to different node`](https://k8s-testgrid.appspot.com/google-gce#gci-gce-serial), you should be able to reproduce the failure in [e2e tests](https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md). You need to set the environment variable `GINKGO_UNTIL_IT_FAIL=true` to run the test repeatedly until it fails.
I just sent[ a PR](https://github.com/kubernetes/community/pull/526) to add the information to the e2e instructions.

**Comment by k82cn** [comment]
@wanghaoran1988 , my suggestion is to try Bobby's comments before changing it to policy ConfigMap.

**Comment by dchen1107** [comment]
@davidopp I am assigning this to you because those tests failed roughly 75% at: https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial since day one it was introduced to the kubernetes. 

We are planning to cut 1.7 alpha-3, and this is one of the blocker issues for triage. On another hand, I noticed that SchedulerPriorities test suites were newly introduced, and are they testing against the new features for 1.7, or just simply for increasing our test coverage? Thanks!

@kubernetes/kubernetes-release-managers @kubernetes/sig-scheduling-bugs

**Comment by k82cn** [comment]
here is the fix: https://github.com/kubernetes/kubernetes/pull/44309

**Comment by k82cn** [comment]
@dchen1107  it is added for code coverage :)

**Comment by davidopp** [comment]
@bsalamat could you please verify that #44309 has fixed this problem, and close this issue once you have verified?

**Comment by bsalamat** [comment]
I tried HEAD and made sure that #44309 is included, but after several successful runs of the test, my setup goes into the state that connection to the master fails with errors similar to the one below. I tried reaching to master from the same workstation running the tests. I had connectivity issues as well.

Unexpected error listing nodes: Get https://130.211.230.74/api/v1/nodes?fieldSelector=spec.unschedulable%3Dfalse&resourceVersion=0: dial tcp 130.211.230.74:443: getsockopt: connection timed out

This happens while running the following test:
`go run hack/e2e.go -- -v --test --test_args="--ginkgo.focus=SchedulerPriorities\s\[Serial\]\sPod\sshould\sbe\sschedule\sto\snode\sthat\sdon't"`

**Comment by davidopp** [comment]
> We are planning to cut 1.7 alpha-3, and this is one of the blocker issues for triage. On another hand, I noticed that SchedulerPriorities test suites were newly introduced, and are they testing against the new features for 1.7, or just simply for increasing our test coverage? Thanks!

This was a refactoring of the existing tests, not new test for 1.7.

@bsalamat Can you look into exactly what is failing, and decide if this should be a blocker? (Let's assume #44309 did not fix the problem -- should this be a blocker?)

**Comment by wanghaoran1988** [comment]
@davidopp That PR was trying to fix the most failed scenario for "Pods created by ReplicationController should spread to different node", seems it worked. I am also looking into this one, and I already run the case half hour, but it never failed, still looking at this now.

**Comment by wanghaoran1988** [comment]
> Unexpected error listing nodes: Get https://130.211.230.74/api/v1/nodes?fieldSelector=spec.unschedulable%3Dfalse&resourceVersion=0: dial tcp 130.211.230.74:443: getsockopt: connection timed out

Met the  same problem with the testing client and cluster both on the GCE cloud, but always pass if I run the testing code inside my internal network , with cluster on the GCE side.

**Comment by timothysc** [comment]
Last 2 runs look green and one is still running.

**Comment by dchen1107** [comment]
Thanks everyone for helping on this issue. We are going to cut 1.7 alpha-3 shortly based on current test results. Thanks!

**Comment by bsalamat** [comment]
The failure that I am observing is not necessarily a test failure. Every time that the test actually ran, it passed, but the problem is that after several execution of the test, the master becomes unreachable, which is a bit odd. I will take another look today.

**Comment by k82cn** [comment]
#44309 was merged, close this issue.
