### ISSUE TITLE
kubelet unable to parse docker version "17.04.0-ce"

### ISSUE THREAD

**Issue by opsnull** [kubernetes/kubernetes#44140]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

Unable to parse docker version

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

# docker version
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      linux/amd64
 Experimental: false

**What happened**:

I found some error messages in kubelet log liking:
kubelet[51799]: E0406 16:24:23.966622   51799 container_manager_linux.go:90] Unable to parse docker version "17.04.0-ce": illegal zero-prefixed version component "04" in "17.04.0-ce"

**What you expected to happen**:

kublet can parse docker version "17.04.0-ce"

**How to reproduce it** (as minimally and precisely as possible):

Install kubelet with docker version 17.04.0-ce

**Anything else we need to know**:

**Comment by supereagle** [comment]
Docker has change its release strategy and versioning scheme from [v17.03.0-ce-rc1](https://github.com/docker/docker/releases/tag/v17.03.0-ce-rc1). We need to update the version match regexp to satisfy the new docker versions.

**Comment by traceypooh** [comment]
+1

**Comment by Random-Liu** [comment]
Actually, Kubernetes only supports docker version 1.10.x, 1.11.x and 1.12.x.

We don't recommend user to use version higher or lower than that range because we don't have enough test coverage on that.

As for docker new version schema, I'm fine to change the code to tolerant new version schema.
