### ISSUE TITLE
Make sure that controllers are not adopting children that are marked for deletion

### ISSUE THREAD

**Issue by lukaszo** [kubernetes/kubernetes#44144]
This is a fork from https://github.com/kubernetes/kubernetes/pull/43077#issuecomment-292108152

I think title is self explanatory. 

ping @kubernetes/sig-apps-misc

**Comment by lukaszo** [comment]
It looks like adding a check to the `ClaimPods` function should be enough. I will provide a fix

**Comment by kargakis** [comment]
Still needs to be fixed for ReplicaSets and Jobs

**Comment by lukaszo** [comment]
@kargakis I added check to method `claimObject` which is used by `claimPods` and `ClaimReplicaSets` so I think only jobs are left

**Comment by lukaszo** [comment]
Hmm, job controller is also using `ClaimPods` am I missing something?

**Comment by kargakis** [comment]
What is the cronjob controller using?

**Comment by lukaszo** [comment]
ah, cronjob controller is using it's own mechanism. Patch is on the way

**Comment by kargakis** [comment]
https://github.com/kubernetes/kubernetes/pull/44150#issuecomment-296759646

@enisoc thanks for the clarification

**Comment by lukaszo** [comment]
OK :)
