### ISSUE TITLE
kubelet ignores CN when SAN are present in api server tls certificate

### ISSUE THREAD

**Issue by deitch** [kubernetes/kubernetes#44151]
**Is this a request for help?** No

**What keywords did you search in Kubernetes issues before filing this one?** kubelet tls cn 

---

**Is this a BUG REPORT or FEATURE REQUEST?** Bug

**Kubernetes version** (use `kubectl version`): 1.6.1

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS 1298.7.0
- **Kernel** (e.g. `uname -a`): 4.9.16-coreos-r1
- **Install tools**: Manual
- **Others**:

**What happened**: API server has a certificate signed by a local CA. The certificate CN is the internal AWS ELB for the server, which matches the `server` key in kubeconfig. The SAN include `127.0.0.1`, the private IP of the given API server, the public ELB, a public DNS name, etc.

kubelet gives an error that the certificate is not valid for the given name.

I can fix it by assigning the CN as also part of the SAN, which is silly, but works. It should respect a hostname that is in the CN _or_ SAN.

**How to reproduce it** (as minimally and precisely as possible):

1. Create a private key and CSR. In the CSR, set CN to hostname by which a kubelet will access the API server. Add SAN options to include at least `127.0.0.1`, perhaps the API server's IP, but *not* the CN hostname.
2. Sign cert.
3. Start API server with that cert as option `--tls-cert-file <cert>`
4. Start kubelet on another node, with the hostname as `server` key in kubeconfig
5. See errors.

For additional data, here is a kubelet error message:

```
Apr 06 09:21:02 ip-10-50-22-57.ec2.internal kubelet[3279]: E0406 09:21:02.285833    3279 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://internal-kubernetes-internal-api-avi-test-899249568.us-east-1.elb.amazonaws.com/api/v1/pods?fieldSelector=spec.nodeName%3Dip-10-50-22-57.ec2.internal&resourceVersion=0: x509: certificate is valid for kubernetes-api-avi-test-509247236.us-east-1.elb.amazonaws.com, ks.infra.test.cloud.<hidden>.com, not internal-kubernetes-internal-api-avi-test-899249568.us-east-1.elb.amazonaws.com
```

Subset of openssl output of examining the cert:

```
        Subject: C=US, ST=__, L=____, O=___, OU=____, CN=internal-kubernetes-internal-api-avi-test-899249568.us-east-1.elb.amazonaws.com
...
            X509v3 Subject Alternative Name:
                DNS:kubernetes-api-avi-test-509247236.us-east-1.elb.amazonaws.com, DNS:ks.infra.test.cloud.<hidden>.com, IP Address:127.0.0.1, IP Address:10.50.22.72
```

And from kubeconfig:

```yml
apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /var/lib/kubernetes/ca.pem
    server: https://internal-kubernetes-internal-api-avi-test-899249568.us-east-1.elb.amazonaws.com
  name: kubernetes
```

Entirely possible I messed up creating the CSR, but it looks right.

**Comment by liggitt** [comment]
Per RFC6125, the CN should only be consulted when there are no DNS or IP SANs: https://tools.ietf.org/html/rfc6125#section-6.4.4

The golang TLS stack follows this RFC when verifying serving cert hostnames: https://golang.org/src/crypto/x509/verify.go?s=13379:13431#L456

**Comment by deitch** [comment]
Dang, @liggitt you got me on that one. Never noticed that in the RFC, so I guess the golang implementation is correct. Given how CN is interpreted commonly, I think that was not the wisest way for the RFC to go, but so be it.

You beat me to it, I was about to close the issue. Thanks.
