### ISSUE TITLE
DaemonSet updates in 1.7

### ISSUE THREAD

**Issue by lukaszo** [kubernetes/kubernetes#44155]
This issue will track DaemonSet update related work in k8s 1.7 release.

Tasks to do:
- [x] DaemonSet history (#45924)
- [x] `kubectl rollout` commands: history, undo (#46144)
- [x] `kubectl delete` should kill all histories when DS is deleted cascadingly, and should orphan histories when DS is deleted non-cascadingly

Maybe to do:
- [ ] pause update
- [ ] versioned DaemonSet (https://github.com/kubernetes/kubernetes/issues/42917)

Feature https://github.com/kubernetes/features/issues/124

cc @janetkuo @kargakis

**Comment by dchen1107** [comment]
Offline discussion with @janetkuo, checked the boxes with done items, and punt the rest to v1.8.

cc/ @erictune

**Comment by lukaszo** [comment]
The issue was for 1.7 release so I'm closing it.
