### ISSUE TITLE
Consider deprecating etcd2

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#44156]
In order to start adopting etcd3 features that are not supported by etcd2, etcd2 support needs to be deprecated and removed.  This issue will track progress towards deprecating etcd2.  Per our [deprecation policy](https://kubernetes.io/docs/home/deprecation-policy/), once the deprecation is announced a 1 year clock will begin, and after that year the next release can remove support for etcd2.

Steps:

- [ ] Verify & document recommended manual upgrade procedure on the kubernetes website
- [ ] Document automated upgrade procedure on the kubernetes website, that takes the same approach as at least one of the manual upgrade options.  (HA upgrades need not keep the API server online during the upgrade).
- [ ] Ensure automated upgrade procedure is under e2e upgrade/downgrade testing.  Because our existing upgrade / downgrade tests are intended to capture API upgrade failures, the scenarios are likely different.  Blocking scenarios:
  - [ ] Ensure upgrade/downgrade happens at a random point during a randomized disruptive test run, to get some coverage of different object states.
  - [ ] Scenario with separate events etcd cluster
  - [ ] Scenario with combined events etcd cluster
  - [ ] Scenario with single node etcd cluster
  - [ ] Scenario with 3 node etcd cluster
  - [ ] Scenario with 3 node etcd cluster, where 1 node is offline, but then rejoins after some time of API operation including writes.  Ideally we then have a previously healthy go offline.
  - [ ] Scenario with 5 node etcd cluster, where 3 nodes are degraded, and verify that upgrade is blocked.  (Need not be stress tested - hopefully!)
  - [ ] Scenario where a UAS has written a large number of keys and big values into the cluster, such that the etcd database is "big" (> 1GB?)
  - [ ] (Optional) Etcd chaos monkey scenario, which may allow us to cover some of the above statistically
  - [ ] (Optional) Create a testgrid tab
- [ ] Consider some success metric on the upgrade tests to be a release-blocker - e.g. no data loss (maybe events data loss is tolerable?); > 100 test runs per scenario; 99% success rate overall, no failures attributable to etcd upgrade/downgrade.
- [ ] Announce deprecation of etcd2 in a release which has passed the success metric.
- [ ] (Optional) Provide collateral to get users enthusiastic about the move, and publicly publish the benchmarks that demonstrated this was a necessary action.
- [ ] Log a warning when etcd2 is in use.
- [ ] (Optional) Surface a warning more prominently, for example in component status or events.
- [ ] (Optional) Collect metrics or do a survey to quantify the number of users using etcd2 and the upgrade rate.
- [ ] (Optional) In the first release after the 1 year deprecation, require an additional flag to be passed, to give users a "last chance"
- [ ] Remove support for etcd2 :fireworks: 

(These are the minimal steps off-the-top of my head; please comment with scenarios/steps I have missed)

**Comment by spiffxp** [comment]
/sig architecture
adding per discussion at sig-architecture meeting today, sig-architecture will own the broader deprecation policies of this project as part of its charter, and delegate/coordinate with appropriate sigs to implement

**Comment by mhausenblas** [comment]
@spiffxp made some good points on kubernetes-dev@ around the deprecation policy (or the lack of action around it so far). Now, looking at what @justinsb put together, above ad the recent discussion we had in /sig cluster-lifecycle I'm more than happy to contribute to this topic, using Justin's suggestions above as a starting point. My motivation is [ReShifter](http://reshifter.info).

**Comment by lavalamp** [comment]
I am adding a note to the 1.9 release notes that etcd2 is deprecated. I have not looked at the list in the OP exhaustively; I do not believe we are committing to those items just by deprecating.

**Comment by bgrant0607** [comment]
Email thread from Julyu: https://groups.google.com/forum/#!topic/kubernetes-dev/DoOl77xjpDA

**Comment by warmchang** [comment]
👍
