### ISSUE TITLE
expose a statefulset's serviceName in the valueFrom/fieldRef

### ISSUE THREAD

**Issue by nstott** [kubernetes/kubernetes#44158]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

serviceName fieldref 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
This is a Feature Request

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.3-2+1d386fe0658e91", GitCommit:"1d386fe0658e9100150d11b4f076c5b3a8997293", GitTreeState:"clean", BuildDate:"2017-03-29T08:12:10Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

--

I am currently able to get data into a pods environment via the fieldref, fieldpath, like this:
`{"name": "NAMESPACE", "valueFrom": {"fieldRef": {"fieldPath": "metadata.namespace", "apiVersion": "v1"}}`

for pods that are created from a stateful set, I want to be able to put the stateful set servicename into the pod in the same fashion
i.e. something like:
`{"name": "SERVICENAME", "valueFrom": {"fieldRef": {"fieldPath": "spec.serviceName", "apiVersion": "v1"}}},`

When I'm building a stateful service I want a pod to be able to work with the hostnames of the other pods in the stateful set, 
i.e. if I'm on 
db-0.servicename.default
I want to be able to do things with db-1.servicename.default, etc.
I want to be able to build lists of peers without having to resort to playing regex games on the pods hostname

**Comment by kargakis** [comment]
@kubernetes/sig-apps-feature-requests
