### ISSUE TITLE
Allow pods to opt out of mutation via PodPresets

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#44161]
`PodPreset` can make changes in a pod's spec that can have security implications, especially if the pod runs with elevated permissions or capabilities.  It should be possible to annotate a pod to indicate that that pod should not be manipulated by `PodPreset`.

**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): PodPreset

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature request

**Kubernetes version** (use `kubectl version`):

1.6

**Environment**:

Any cluster

**Comment by liggitt** [comment]
I don't think we'd want a magic annotation, but something that surfaces and works with the existing selector-based exclusion

**Comment by pmorie** [comment]
@liggit, I like where you and @derekwaynecarr landed on this while I was out.

**Comment by bgrant0607** [comment]
@pmorie Please categorize every issue you file under an appropriate SIG.
