### ISSUE TITLE
kubectl apply fails on create AlreadyExists even though the command was apply

### ISSUE THREAD

**Issue by deitch** [kubernetes/kubernetes#44165]
**Is this a request for help?** No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kubectl apply creating upsert

---

**Is this a BUG REPORT or FEATURE REQUEST?**  Bug (I think)

**Kubernetes version** (use `kubectl version`): 1.6.1

**Environment**: 
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS 1298.7.0
- **Kernel** (e.g. `uname -a`): 4.9.16-coreos-r1
- **Install tools**: downloaded and installed k8s directly
- **Others**:

**What happened**: When doing `kubectl apply -f <url>` on multiple master nodes, some fail as if `kubectl create` instead of `apply`

As I understand it, `kubectl apply` is an upsert, "create of exists else update". I have a cloud-init run on all master nodes to instantiate my cluster. It installs networking via `kubectl apply -f https://git.io/weave-kube-1.6`. Of course, this runs on all master nodes.

In order to avoid an error (and thus failing out the cloudinit script), it specifically does `kubectl apply` instead of `kubectl create`. Yet I get errors:

```
Apr 06 13:42:16 ip-10-50-22-238.ec2.internal bash[1112]: clusterrole "weave-net" configured
Apr 06 13:42:20 ip-10-50-22-238.ec2.internal bash[1112]: Error from server (AlreadyExists): error when creating "https://git.io/weave-kube-1.6": serviceaccounts "weave-net" already exists
Apr 06 13:42:20 ip-10-50-22-238.ec2.internal bash[1112]: Error from server (AlreadyExists): error when creating "https://git.io/weave-kube-1.6": clusterrolebindings.rbac.authorization.k8s.io "weave-net" already exists
Apr 06 13:42:20 ip-10-50-22-238.ec2.internal bash[1112]: Error from server (AlreadyExists): error when creating "https://git.io/weave-kube-1.6": daemonsets.extensions "weave-net" already exists
```

Notice that it errors out with `AlreadyExists`, but only for `clusterrolebbinding`, `daemonset` and `serviceaccount`. The `clusterrole` responds with the correct `configured` for a resource that already exists, but fails with the `creating` for the others.

I will wrap around it catching the fail, but it would be better if this just worked.

I suspect a race condition. Two or three of the nodes try to run at the same time. One of them creates the `clusterrole` so the other sees it and applies, but two of them check if the other elements exist at the same time, only one submits the correct create command, following which the other tries and fails.

I guess the real question is, is `apply` logic of "check if exists update else create" applied at the server API level, or at the kubectl cli level? If the latter, this explanation makes sense.

**What you expected to happen**:

`kubectl apply` should upsert, essentially making no change and returning with an exit code of 0.

**Comment by liggitt** [comment]
it is applied client-side. if it checks, the object does not exist, attempts to create, and gets an AlreadyExists error, I suppose it needs to restart the process since there is no guarantee the new object created in the meantime matches the manifest that was requested to be applied

**Comment by liggitt** [comment]
cc @kubernetes/sig-cli-bugs

**Comment by deitch** [comment]
> it is applied client-side

So sounds like my understanding of it as a timing issue is likely correct. Ah well. In the meantime, I added a wrap around it to catch and retry, so it can handle a few failures. Since I only am starting 3 master nodes, 3 retries with a 10 second backoff should be far more than enough to handle it.

Still and all, it probably is right to have the upsert logic handled server side?

Thanks @liggitt

**Comment by adohe** [comment]
@liggitt @deitch this is definitely client side behavior. `kubectl apply` will first check whether obj exists, if not then try to do create logical. But it cannot avoid other client create the same object meantime, for such situation(`AlreadyExists` error), kubectl should fallback to do normal patch logcial, since there is no guarantee the new object created in the meantime matches the manifest that was requested to be applied. wdyt?

**Comment by deitch** [comment]
@adohe so the upsert activity really isn't a kube-apiserver capability (well, controller-manager, but whatever), but a kubectl capability that just does "check if exists: if yes, update; if not, create."

> kubectl should fallback to do normal patch logcial, since there is no guarantee the new object created in the meantime matches the manifest that was requested to be applied

Yes.

Ideally, I think you would want that upsert logic in the server, so kubectl (i.e. a rest API call) can just do a simple `apply` call. In the meantime, though, yes, a kubectl-side: "check if exists: if yes, update; if not, try to create, but trap `AlreadyExists` error, and then fall back to update."

Come to think of it, would it not be simpler if _every_ `apply` just did, "create; if it fails with `AlreadyExists` error, then update"?

**Comment by adohe** [comment]
@deitch we did plan to move `apply` to server-side :)

**Comment by deitch** [comment]
> we did plan to move apply to server-side

@adohe Thinner client, simpler logic, complexity on the server instead of client? I cannot imagine why...  :-)

Of course, you still will need the same logic, since two threads of the server could handle it at the same time.

**Comment by adohe** [comment]
will fix this before this weekend.

**Comment by deitch** [comment]
@adohe was this fixed? Which version?

Thanks

**Comment by deitch** [comment]
@adohe any update?

**Comment by plombardi89** [comment]
@adohe did you ever fix this? Still seeing this issue in server 1.7.2 and client 1.8.4

**Comment by openstacker** [comment]
I can reproduce this with v1.9.3 when creating 3 masters at the same time, just FYI.

**Comment by mariusgrigoriu** [comment]
This issue poses challenges to those who run `kubectl apply` in their deployment pipelines.

**Comment by epa095** [comment]
This is definitely still an issue, /reopen

**Comment by deitch** [comment]
Is there any way to disable the rotten closure bot on this issue?

**Comment by diegom626** [comment]
any update on this?
/reopen

**Comment by svanschalkwyk** [comment]
Please reopen this issue.
V 1.18.0

**Comment by hjkatz** [comment]
/reopen

Please bot, stop closing this issue if it still exists.

**Comment by hjkatz** [comment]
@deitch Would you do the honors? 😆 Every 30 days!

**Comment by deitch** [comment]
I am honoured @hjkatz 😄

**Comment by zhangguanzhang** [comment]
samy issue on:
```
$ kubectl get node 
NAME          STATUS   ROLES         AGE   VERSION
10.xx.xx.37   Ready    master,node   35m   v1.27.16
10.xx.xx.45   Ready    master,node   35m   v1.27.16
10.xx.xx.46   Ready    master,node   35m   v1.27.16
```

```
"cmd": ["kubectl", "--kubeconfig=/etc/kubernetes/cluster1/.kube/config", "apply", "-f", "/tmp/mysql-svc.yaml"], 
"delta": "0:00:00.649216", "end": "2025-01-07 11:16:24.104712", 
"msg": "non-zero return code", "rc": 1, "start": "2025-01-07 11:16:23.455496", 
"stderr": "Error from server (AlreadyExists): error when creating \"/tmp/mysql-svc.yaml\": services \" test-database\" already exists\nError from server (AlreadyExists): error when creating \"/tmp/mysql-svc.yaml\": endpoints \" test-database\" already exists",
 "stderr_lines": ["Error from server (AlreadyExists): error when creating \"/tmp/mysql-svc.yaml\": services \" test-database\" already exists", "Error from server (AlreadyExists): error when creating \"/tmp/mysql-svc.yaml\": endpoints \" test-database\" already exists"], "stdout": "", "stdout_lines": []}
```

**Comment by c4tz** [comment]
[Quote:](https://github.com/kubernetes/kubernetes/issues/44165#issuecomment-294841470) 
> will fix this before this weekend.

Whew, I wish I also had (almost) 7 year long weekends. 

Jokes aside, this is still an issue and can be easily reproduced using the following script:

```bash
#!/bin/bash

kubectl delete ns test-ns || true

kubectl create ns test-ns --dry-run=client -o yaml | kubectl apply -f - &
kubectl create ns test-ns --dry-run=client -o yaml | kubectl apply -f - &
kubectl create ns test-ns --dry-run=client -o yaml | kubectl apply -f - &
```
which results in:
```
Error from server (NotFound): namespaces "test-ns" not found
namespace/test-ns created
Error from server (AlreadyExists): error when creating "STDIN": namespaces "test-ns" already exists
Error from server (AlreadyExists): error when creating "STDIN": namespaces "test-ns" already exists
```

My use-case are several CI jobs running at the same time which each are supposed to deploy a different Helm release, but in the same namespace. (Because the NS needs to be labeled as well, I need to run `kubectl` and can't use Helm's `--create-namespace`.)

If the check would happen on the server-side, this probably wouldn't be a problem.
