### ISSUE TITLE
PV upgrade test is failing at master

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#44168]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-latest-upgrade-cluster/1106

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:123
Expected success, but got an error:
    <*errors.errorString | 0xc4203f7ad0>: {
        s: "pod ran to completion",
    }
    pod ran to completion
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/pv_util.go:691
```

This is upgrading from the latest 1.6 branch to master.

**Comment by krousey** [comment]
@msau42 If you're not the right person to look into this, please find someone who can.

**Comment by msau42** [comment]
PR #42667 changed the MakePod() call to CreatePod() instead, which I don't think is correct because TestContainerOutput() will already create the pod.  @divyenpatel what was the reason for changing it?

**Comment by msau42** [comment]
Hmmm although it looks like the upgrade test was failing even before then, so maybe that's just a red herring.

**Comment by msau42** [comment]
Actually the test started failing consistently with the same pv_util signature after 3/31, which coincides with the change to call CreatePod().  So I think yes, that is the reason for the latest failures.  I will work on a change to move it back to MakePod().

However, the upgrade test in general has been failing for a while.  But the signatures have been different.  Here's the signature before 3/31: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-latest-upgrade-cluster/926

**Comment by divyenpatel** [comment]
@msau42 we updated MakePod to allow passing multiple claims to pod spec. As part of review comment I addressed this change.

 in the previous code, pod spec has MountPath for volume set to : "/mnt", in the new code we set the mount path to "/mnt/volume1"
