### ISSUE TITLE
Allow compression of json response body using Accept-Encoding header

### ISSUE THREAD

**Issue by ilackarms** [kubernetes/kubernetes#44164]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): 
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): 
compression, gzip, response, json

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): 
Feature Request

JSON payload returned by Kubernetes can be very large on `GET` requests when there are a lot of managed resources in the cluster.

Currently it is not possible to specify that large response bodies should be compressed via request headers.

Specifying the `Accept-Encoding` header on a `GET` request should cause the k8s apiserver to respond with response Body compressed with the given encoding sceme (e..g gzip, bzip2, etc.)

**Comment by ilackarms** [comment]
#45666 adds this feature

**Comment by deads2k** [comment]
@ilackarms link your pull and tag me when have it open so we can be sure it makes 1.7

**Comment by ilackarms** [comment]
gating issue #46963
