### ISSUE TITLE
Roundtrip conversion tests fail after adding defaults

### ISSUE THREAD

**Issue by khenidak** [kubernetes/kubernetes#44177]
**What happened**:
Jenkins Bazel test (among other fail when type defaulting is used). 

**What you expected to happen**:
Success for Jenkins Bazel test & successful test using ./hack/run.sh make test 

**How to reproduce it** (as minimally and precisely as possible):
This PR https://github.com/kubernetes/kubernetes/pull/41950 CI/CD fails because of an issue in roundtrip-ing. This verification will become successful if type defaulting code is removed specifically this if-statement https://github.com/khenidak/kubernetes/blob/6e151a595210cf8659d496149c9bca2c53e0157f/pkg/api/v1/defaults.go#L265 

The error produced by the verification test  is consistent and can be found here https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41950/pull-kubernetes-bazel/12522/ 

**Anything else we need to know**:
all logs for multiple attempts to work around that can be found in the PR page.

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-bugs @mikedanese

**Comment by mikedanese** [comment]
This doesn't have to do with bazel:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41950/pull-kubernetes-unit/25417/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41950/pull-kubernetes-bazel/12522/


Same error for both.

This is a common obstacle that people hit when writing conversion tests. When adding defaults, you need to add a custom fuzzer for the conversion tests to pass.

**Comment by liggitt** [comment]
> When adding defaults, you often need to add a custom fuzzer for the conversion tests to pass.

that is correct
/close
