### ISSUE TITLE
unable to retrive registry from etcd-3.0.4 

### ISSUE THREAD

**Issue by divyenpatel** [kubernetes/kubernetes#44175]
**Is this a request for help?**:
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
etcd-3.0.4

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
# kubectl version                                                          
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: vsphere
- **OS** (e.g. from /etc/os-release): photon
- **Kernel** (e.g. `uname -a`): Linux master 4.4.8-esx
- **Install tools**:
- **Others**:

**What happened**:
etcd-3.0.4 does not list registry
cluster is healthy. able to create pod, delete pod, pv and pvc.
after we delete pod, disk never gets detached from the node vm.

**etcd-3.0.4**
Deployed Kubernetes Cluster v5.3.1 release using etcd-3.0.4
Able to create a pod, pv, pvc but when pod is deleted, disk is not getting detached from the node.

```
# etcdctl --endpoints="127.0.0.1:2379" cluster-health
member 8e9e05c52164694d is healthy: got healthy result from http://127.0.0.1:2379
cluster is healthy
```

```
# etcdctl --endpoints="127.0.0.1:2379" ls registry
Error:  100: Key not found (/registry) [3]
```

**etcd-2.2.1**
When same Kubernetes Cluster v5.3.1 is deployed using etcd-2.2.1, upon deleting pod, disk is getting detached from the node. We are also able list registry.

```
# etcdctl --endpoints="127.0.0.1:2379" cluster-health
member ce2a822cea30bfca is healthy: got healthy result from http://127.0.0.1:2379
cluster is healthy
```

```
# etcdctl --endpoints="127.0.0.1:2379" ls registry
/registry/events
/registry/daemonsets
/registry/storageclasses
/registry/clusterrolebindings
/registry/services
/registry/pods
/registry/controllers
/registry/ranges
/registry/namespaces
/registry/serviceaccounts
/registry/secrets
/registry/replicasets
/registry/clusterroles
/registry/minions
/registry/deployments
/registry/persistentvolumeclaims
/registry/persistentvolumes
```

**What you expected to happen**:
registry should be created and retrieved from etcd

**How to reproduce it** (as minimally and precisely as possible):
deploy kubernetes cluster using etcd-3.0.4, create pod with pv, and delete pod, pv should be detached from the node vm.

**Anything else we need to know**:

Logs:
**etcd-3.0.4**
[etcd-3.0.4.txt](https://github.com/kubernetes/kubernetes/files/903691/etcd-3.0.4.txt)
[api-server-etcd-3.0.4.txt](https://github.com/kubernetes/kubernetes/files/903692/api-server-etcd-3.0.4.txt)
[controller-3.0.4.txt](https://github.com/kubernetes/kubernetes/files/903693/controller-3.0.4.txt)

**etcd-2.2.1**
[etcd-2.2.1.txt](https://github.com/kubernetes/kubernetes/files/903694/etcd-2.2.1.txt)
[api-server-etcd-2.2.1.txt](https://github.com/kubernetes/kubernetes/files/903695/api-server-etcd-2.2.1.txt)
[controller-2.2.1.txt](https://github.com/kubernetes/kubernetes/files/903696/controller-2.2.1.txt)

@tusharnt @BaluDontu @abrarshivani

**Comment by ncdc** [comment]
etcd v3 has a different way you have to use etcdctl. You have to set an environment variable to read etcd in v3 mode: `export ETCDCTL_API=3`.

I'd recommend you read https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/interacting_v3.md for more details.

Hope this helps!

**Comment by divyenpatel** [comment]
Thanks @ncdc 
Actually we changed our ignition image to use `etcd 2.2.1`, from `etcd:3.0.4`
https://github.com/kubernetes/kubernetes-anywhere/pull/374/files

Actual problem is, with etcd:3.0.4, we observed volumes were not getting detached from the node after pod is deleted. and kubernetes version when deployed using etcd 2.2.1, volumes got detached after pod is deleted.

https://github.com/kubernetes/kubernetes/issues/43272

does this environment variable needs to be set on the node VMs or Kubernetes takes care of this?

**Comment by ncdc** [comment]
@divyenpatel `ETCDCTL_API=3` is only applicable to running the `etcdctl` command-line tool. Kubernetes has a different place where you configure if you want it to talk to etcd using the v2 or v3 API.

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by peterwillcn** [comment]
ETCDCTL_API=3 etcdctl --endpoints=http://localhost:2379 get / --prefix --keys-only
