### ISSUE TITLE
Cannot connect to service of it's own from inside pod on kubernetes 1.6

### ISSUE THREAD

**Issue by phagunbaya** [kubernetes/kubernetes#44187]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
kubernetes service discovery
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.6.0

**Environment**:
- **Cloud provider or hardware configuration**: Bare metal
- **OS** (e.g. from /etc/os-release): CentOS 7.3
- **Kernel** (e.g. `uname -a`): Linux c4n1 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubeadm
- **Others**:

**What happened**:
I created service and deployment for my web service. Now from inside the pod I'm trying to connect to it's own service name and port. It gets times out after few minutes.  This works perfectly fine on kubenetes v1.5.x but not v1.6. I'm using weave network plugin. Also, I'm able to connect with other services perfectly fine on v1.6.

**What you expected to happen**:
I should be able to connect to the service (of it's own) from inside pod.

**How to reproduce it** (as minimally and precisely as possible):
Create a small web app (Deployment), create a service for it (NodePort). From the same pod do `curl -c http://<service-name>:<port>`. It get's timed out.

**Anything else we need to know**:
cat /etc/resolv.conf
```
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
```

cat /etc/hosts
```
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
10.32.0.7	falkonry-kafka-56017906-9qlg3
```

Connecting to kafka service from other container
```
    root@falkonry-redis-0:/data# curl -v http://falkonry-kafka:9092          
    * About to connect() to falkonry-kafka port 9092 (#0)
    *   Trying 10.99.232.10...
    * connected
    * Connected to falkonry-kafka (10.99.232.10) port 9092 (#0)
    > GET / HTTP/1.1
    > User-Agent: curl/7.26.0
    > Host: falkonry-kafka:9092
    > Accept: */*
    > 
    * additional stuff not fine transfer.c:1037: 0 0
    * Recv failure: Connection reset by peer
    * Closing connection #0
    curl: (56) Recv failure: Connection reset by peer
```
Connecting to kafka service from inside kafka container (Request never finishes)
```
    root@falkonry-kafka-56017906-9qlg3:/# curl -v http://falkonry-kafka:9092
    * Rebuilt URL to: http://falkonry-kafka:9092/
    * Hostname was NOT found in DNS cache
    *   Trying 10.99.232.10...
    ^C
```

Attaching cluster dump
[clusterdump.txt](https://github.com/kubernetes/kubernetes/files/904224/clusterdump.txt)

**Comment by phagunbaya** [comment]
iptables-save output

    # Generated by iptables-save v1.4.21 on Fri Apr  7 12:16:32 2017
    *nat
    :PREROUTING ACCEPT [1:60]
    :INPUT ACCEPT [0:0]
    :OUTPUT ACCEPT [12:720]
    :POSTROUTING ACCEPT [16:1038]
    :DOCKER - [0:0]
    :KUBE-MARK-DROP - [0:0]
    :KUBE-MARK-MASQ - [0:0]
    :KUBE-NODEPORTS - [0:0]
    :KUBE-POSTROUTING - [0:0]
    :KUBE-SEP-4QD2LE2R2TODS2YV - [0:0]
    :KUBE-SEP-6K3WNWFYOAH5UDZ7 - [0:0]
    :KUBE-SEP-AR5TRSQMIM2F553H - [0:0]
    :KUBE-SEP-BIZOCAOAPTCX4WBC - [0:0]
    :KUBE-SEP-F7NTE7AMKDKNWUUF - [0:0]
    :KUBE-SEP-FV6ZZ4EMBZMV4DQ5 - [0:0]
    :KUBE-SEP-HVHMJPRJS2UA65HH - [0:0]
    :KUBE-SEP-IBDVBYXSRD6MIAGE - [0:0]
    :KUBE-SEP-KDTJFZVKN4ESIN24 - [0:0]
    :KUBE-SEP-KNER6ASWBX763QL7 - [0:0]
    :KUBE-SEP-NGQUCFCRE45KSL73 - [0:0]
    :KUBE-SEP-NYKTVPUDBMHXGWAX - [0:0]
    :KUBE-SEP-QLLLKZOFDP244LAS - [0:0]
    :KUBE-SEP-RBQF4CU7COIZTWDJ - [0:0]
    :KUBE-SEP-SX34LAYKH37CF5LT - [0:0]
    :KUBE-SEP-SZZ7MOWKTWUFXIJT - [0:0]
    :KUBE-SEP-TZPDA6OWOVPRIIUZ - [0:0]
    :KUBE-SEP-UJJNLSZU6HL4F5UO - [0:0]
    :KUBE-SEP-W4RNB3VXXTJ3LGHB - [0:0]
    :KUBE-SEP-YYIR7TZA6ZBQSUSF - [0:0]
    :KUBE-SERVICES - [0:0]
    :KUBE-SVC-BL55CP3MKKB53NTC - [0:0]
    :KUBE-SVC-BV4E552EX2CNKPCU - [0:0]
    :KUBE-SVC-BYB5G3MHEBYVN43P - [0:0]
    :KUBE-SVC-C64CQIO6Z225CXIH - [0:0]
    :KUBE-SVC-CAVFOYOJQPPKKFSK - [0:0]
    :KUBE-SVC-DM7TKUYSW7TW345O - [0:0]
    :KUBE-SVC-ERIFXISQEP7F7OF4 - [0:0]
    :KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
    :KUBE-SVC-NTZIAVXWXJCS7DKZ - [0:0]
    :KUBE-SVC-PJO6V2NNIUDO2DKL - [0:0]
    :KUBE-SVC-QIJ4ARI55YRJ76JG - [0:0]
    :KUBE-SVC-QQGUGJWMO5HSN6XL - [0:0]
    :KUBE-SVC-RVQUD6RAXHQPQF3I - [0:0]
    :KUBE-SVC-SZGELJVIQ5IRMA57 - [0:0]
    :KUBE-SVC-TCOU7JCQXEZGVUNU - [0:0]
    :KUBE-SVC-U6PKKNLWPXOUUWIP - [0:0]
    :KUBE-SVC-XGPIXF43F4GLZBG7 - [0:0]
    :KUBE-SVC-Y4IVC7EWPWRMUFRE - [0:0]
    :WEAVE - [0:0]
    -A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
    -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
    -A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
    -A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
    -A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
    -A POSTROUTING -s 172.17.50.0/24 ! -o docker0 -j MASQUERADE
    -A POSTROUTING -j WEAVE
    -A DOCKER -i docker0 -j RETURN
    -A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
    -A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
    -A KUBE-NODEPORTS -p tcp -m comment --comment "default/falkonry-merlin:merlin-web" -m tcp --dport 30061 -j KUBE-MARK-MASQ
    -A KUBE-NODEPORTS -p tcp -m comment --comment "default/falkonry-merlin:merlin-web" -m tcp --dport 30061 -j KUBE-SVC-SZGELJVIQ5IRMA57
    -A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE
    -A KUBE-SEP-4QD2LE2R2TODS2YV -s 10.44.0.6/32 -m comment --comment "default/falkonry-spark-master:rest" -j KUBE-MARK-MASQ
    -A KUBE-SEP-4QD2LE2R2TODS2YV -p tcp -m comment --comment "default/falkonry-spark-master:rest" -m tcp -j DNAT --to-destination 10.44.0.6:6066
    -A KUBE-SEP-6K3WNWFYOAH5UDZ7 -s 10.32.0.4/32 -m comment --comment "default/falkonry-kafka:kafka" -j KUBE-MARK-MASQ
    -A KUBE-SEP-6K3WNWFYOAH5UDZ7 -p tcp -m comment --comment "default/falkonry-kafka:kafka" -m tcp -j DNAT --to-destination 10.32.0.4:9092
    -A KUBE-SEP-AR5TRSQMIM2F553H -s 10.24.10.4/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
    -A KUBE-SEP-AR5TRSQMIM2F553H -p tcp -m comment --comment "default/kubernetes:https" -m recent --set --name KUBE-SEP-AR5TRSQMIM2F553H --mask 255.255.255.255 --rsource -m tcp -j DNAT --to-destination 10.24.10.4:6443
    -A KUBE-SEP-BIZOCAOAPTCX4WBC -s 10.44.0.3/32 -m comment --comment "default/falkonry-merlin:merlin-web" -j KUBE-MARK-MASQ
    -A KUBE-SEP-BIZOCAOAPTCX4WBC -p tcp -m comment --comment "default/falkonry-merlin:merlin-web" -m tcp -j DNAT --to-destination 10.44.0.3:8080
    -A KUBE-SEP-F7NTE7AMKDKNWUUF -s 10.42.0.3/32 -m comment --comment "default/falkonry-riactor:riactor-http" -j KUBE-MARK-MASQ
    -A KUBE-SEP-F7NTE7AMKDKNWUUF -p tcp -m comment --comment "default/falkonry-riactor:riactor-http" -m tcp -j DNAT --to-destination 10.42.0.3:8000
    -A KUBE-SEP-FV6ZZ4EMBZMV4DQ5 -s 10.32.0.10/32 -m comment --comment "default/falkonry-redis:redis-cli" -j KUBE-MARK-MASQ
    -A KUBE-SEP-FV6ZZ4EMBZMV4DQ5 -p tcp -m comment --comment "default/falkonry-redis:redis-cli" -m tcp -j DNAT --to-destination 10.32.0.10:6379
    -A KUBE-SEP-HVHMJPRJS2UA65HH -s 10.32.0.7/32 -m comment --comment "default/falkonry-hadoop:namenode-ui" -j KUBE-MARK-MASQ
    -A KUBE-SEP-HVHMJPRJS2UA65HH -p tcp -m comment --comment "default/falkonry-hadoop:namenode-ui" -m tcp -j DNAT --to-destination 10.32.0.7:50070
    -A KUBE-SEP-IBDVBYXSRD6MIAGE -s 10.44.0.5/32 -m comment --comment "default/falkonry-riactor:riactor-http" -j KUBE-MARK-MASQ
    -A KUBE-SEP-IBDVBYXSRD6MIAGE -p tcp -m comment --comment "default/falkonry-riactor:riactor-http" -m tcp -j DNAT --to-destination 10.44.0.5:8000
    -A KUBE-SEP-KDTJFZVKN4ESIN24 -s 10.32.0.7/32 -m comment --comment "default/falkonry-hadoop:datanode" -j KUBE-MARK-MASQ
    -A KUBE-SEP-KDTJFZVKN4ESIN24 -p tcp -m comment --comment "default/falkonry-hadoop:datanode" -m tcp -j DNAT --to-destination 10.32.0.7:50010
    -A KUBE-SEP-KNER6ASWBX763QL7 -s 10.32.0.7/32 -m comment --comment "default/falkonry-hadoop:datanode-ui" -j KUBE-MARK-MASQ
    -A KUBE-SEP-KNER6ASWBX763QL7 -p tcp -m comment --comment "default/falkonry-hadoop:datanode-ui" -m tcp -j DNAT --to-destination 10.32.0.7:50075
    -A KUBE-SEP-NGQUCFCRE45KSL73 -s 10.44.0.6/32 -m comment --comment "default/falkonry-spark-master:webui" -j KUBE-MARK-MASQ
    -A KUBE-SEP-NGQUCFCRE45KSL73 -p tcp -m comment --comment "default/falkonry-spark-master:webui" -m tcp -j DNAT --to-destination 10.44.0.6:8080
    -A KUBE-SEP-NYKTVPUDBMHXGWAX -s 10.44.0.6/32 -m comment --comment "default/falkonry-spark-master:akka" -j KUBE-MARK-MASQ
    -A KUBE-SEP-NYKTVPUDBMHXGWAX -p tcp -m comment --comment "default/falkonry-spark-master:akka" -m tcp -j DNAT --to-destination 10.44.0.6:7077
    -A KUBE-SEP-QLLLKZOFDP244LAS -s 10.42.0.1/32 -m comment --comment "default/falkonry-connector:http" -j KUBE-MARK-MASQ
    -A KUBE-SEP-QLLLKZOFDP244LAS -p tcp -m comment --comment "default/falkonry-connector:http" -m tcp -j DNAT --to-destination 10.42.0.1:8001
    -A KUBE-SEP-RBQF4CU7COIZTWDJ -s 10.32.0.6/32 -m comment --comment "default/falkonry-zookeeper:zookeeper" -j KUBE-MARK-MASQ
    -A KUBE-SEP-RBQF4CU7COIZTWDJ -p tcp -m comment --comment "default/falkonry-zookeeper:zookeeper" -m tcp -j DNAT --to-destination 10.32.0.6:2181
    -A KUBE-SEP-SX34LAYKH37CF5LT -s 10.42.0.2/32 -m comment --comment "default/falkonry-merlin:merlin-web" -j KUBE-MARK-MASQ
    -A KUBE-SEP-SX34LAYKH37CF5LT -p tcp -m comment --comment "default/falkonry-merlin:merlin-web" -m tcp -j DNAT --to-destination 10.42.0.2:8080
    -A KUBE-SEP-SZZ7MOWKTWUFXIJT -s 10.32.0.2/32 -m comment --comment "kube-system/kube-dns:dns" -j KUBE-MARK-MASQ
    -A KUBE-SEP-SZZ7MOWKTWUFXIJT -p udp -m comment --comment "kube-system/kube-dns:dns" -m udp -j DNAT --to-destination 10.32.0.2:53
    -A KUBE-SEP-TZPDA6OWOVPRIIUZ -s 10.32.0.3/32 -m comment --comment "default/falkonry-riactor:riactor-http" -j KUBE-MARK-MASQ
    -A KUBE-SEP-TZPDA6OWOVPRIIUZ -p tcp -m comment --comment "default/falkonry-riactor:riactor-http" -m tcp -j DNAT --to-destination 10.32.0.3:8000
    -A KUBE-SEP-UJJNLSZU6HL4F5UO -s 10.32.0.2/32 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-MARK-MASQ
    -A KUBE-SEP-UJJNLSZU6HL4F5UO -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp" -m tcp -j DNAT --to-destination 10.32.0.2:53
    -A KUBE-SEP-W4RNB3VXXTJ3LGHB -s 10.32.0.8/32 -m comment --comment "default/falkonry-mongo:mongo-http" -j KUBE-MARK-MASQ
    -A KUBE-SEP-W4RNB3VXXTJ3LGHB -p tcp -m comment --comment "default/falkonry-mongo:mongo-http" -m tcp -j DNAT --to-destination 10.32.0.8:27017
    -A KUBE-SEP-YYIR7TZA6ZBQSUSF -s 10.32.0.7/32 -m comment --comment "default/falkonry-hadoop:namenode" -j KUBE-MARK-MASQ
    -A KUBE-SEP-YYIR7TZA6ZBQSUSF -p tcp -m comment --comment "default/falkonry-hadoop:namenode" -m tcp -j DNAT --to-destination 10.32.0.7:8020
    -A KUBE-SERVICES -d 10.103.204.121/32 -p tcp -m comment --comment "default/falkonry-spark-master:akka cluster IP" -m tcp --dport 7077 -j KUBE-SVC-CAVFOYOJQPPKKFSK
    -A KUBE-SERVICES -d 10.111.87.193/32 -p tcp -m comment --comment "default/falkonryagent:agent-web cluster IP" -m tcp --dport 9090 -j KUBE-SVC-QQGUGJWMO5HSN6XL
    -A KUBE-SERVICES -d 10.96.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
    -A KUBE-SERVICES -d 10.107.140.112/32 -p tcp -m comment --comment "default/falkonry-zookeeper:zookeeper cluster IP" -m tcp --dport 2181 -j KUBE-SVC-BYB5G3MHEBYVN43P
    -A KUBE-SERVICES -d 10.106.78.154/32 -p tcp -m comment --comment "default/falkonry-hadoop:datanode cluster IP" -m tcp --dport 50010 -j KUBE-SVC-NTZIAVXWXJCS7DKZ
    -A KUBE-SERVICES -d 10.106.78.154/32 -p tcp -m comment --comment "default/falkonry-hadoop:datanode-ui cluster IP" -m tcp --dport 50075 -j KUBE-SVC-BL55CP3MKKB53NTC
    -A KUBE-SERVICES -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
    -A KUBE-SERVICES -d 10.111.174.212/32 -p tcp -m comment --comment "default/falkonry-merlin:merlin-web cluster IP" -m tcp --dport 8080 -j KUBE-SVC-SZGELJVIQ5IRMA57
    -A KUBE-SERVICES -d 10.103.204.121/32 -p tcp -m comment --comment "default/falkonry-spark-master:rest cluster IP" -m tcp --dport 6066 -j KUBE-SVC-DM7TKUYSW7TW345O
    -A KUBE-SERVICES -d 10.103.204.121/32 -p tcp -m comment --comment "default/falkonry-spark-master:webui cluster IP" -m tcp --dport 8080 -j KUBE-SVC-QIJ4ARI55YRJ76JG
    -A KUBE-SERVICES -d 10.106.78.154/32 -p tcp -m comment --comment "default/falkonry-hadoop:namenode cluster IP" -m tcp --dport 9000 -j KUBE-SVC-BV4E552EX2CNKPCU
    -A KUBE-SERVICES -d 10.106.78.154/32 -p tcp -m comment --comment "default/falkonry-hadoop:namenode-ui cluster IP" -m tcp --dport 50070 -j KUBE-SVC-U6PKKNLWPXOUUWIP
    -A KUBE-SERVICES -d 10.98.38.82/32 -p tcp -m comment --comment "default/falkonry-mongo:mongo-http cluster IP" -m tcp --dport 27017 -j KUBE-SVC-Y4IVC7EWPWRMUFRE
    -A KUBE-SERVICES -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
    -A KUBE-SERVICES -d 10.96.90.91/32 -p tcp -m comment --comment "default/falkonry-redis:redis-cli cluster IP" -m tcp --dport 6379 -j KUBE-SVC-PJO6V2NNIUDO2DKL
    -A KUBE-SERVICES -d 10.99.232.10/32 -p tcp -m comment --comment "default/falkonry-kafka:kafka cluster IP" -m tcp --dport 9092 -j KUBE-SVC-XGPIXF43F4GLZBG7
    -A KUBE-SERVICES -d 10.100.203.65/32 -p tcp -m comment --comment "default/falkonry-riactor:riactor-http cluster IP" -m tcp --dport 8000 -j KUBE-SVC-C64CQIO6Z225CXIH
    -A KUBE-SERVICES -d 10.110.120.177/32 -p tcp -m comment --comment "default/falkonry-connector:http cluster IP" -m tcp --dport 8001 -j KUBE-SVC-RVQUD6RAXHQPQF3I
    -A KUBE-SERVICES -m comment --comment "kubernetes service nodeports; NOTE: this must be the last rule in this chain" -m addrtype --dst-type LOCAL -j KUBE-NODEPORTS
    -A KUBE-SVC-BL55CP3MKKB53NTC -m comment --comment "default/falkonry-hadoop:datanode-ui" -j KUBE-SEP-KNER6ASWBX763QL7
    -A KUBE-SVC-BV4E552EX2CNKPCU -m comment --comment "default/falkonry-hadoop:namenode" -j KUBE-SEP-YYIR7TZA6ZBQSUSF
    -A KUBE-SVC-BYB5G3MHEBYVN43P -m comment --comment "default/falkonry-zookeeper:zookeeper" -j KUBE-SEP-RBQF4CU7COIZTWDJ
    -A KUBE-SVC-C64CQIO6Z225CXIH -m comment --comment "default/falkonry-riactor:riactor-http" -m statistic --mode random --probability 0.33332999982 -j KUBE-SEP-TZPDA6OWOVPRIIUZ
    -A KUBE-SVC-C64CQIO6Z225CXIH -m comment --comment "default/falkonry-riactor:riactor-http" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-F7NTE7AMKDKNWUUF
    -A KUBE-SVC-C64CQIO6Z225CXIH -m comment --comment "default/falkonry-riactor:riactor-http" -j KUBE-SEP-IBDVBYXSRD6MIAGE
    -A KUBE-SVC-CAVFOYOJQPPKKFSK -m comment --comment "default/falkonry-spark-master:akka" -j KUBE-SEP-NYKTVPUDBMHXGWAX
    -A KUBE-SVC-DM7TKUYSW7TW345O -m comment --comment "default/falkonry-spark-master:rest" -j KUBE-SEP-4QD2LE2R2TODS2YV
    -A KUBE-SVC-ERIFXISQEP7F7OF4 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-SEP-UJJNLSZU6HL4F5UO
    -A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m recent --rcheck --seconds 10800 --reap --name KUBE-SEP-AR5TRSQMIM2F553H --mask 255.255.255.255 --rsource -j KUBE-SEP-AR5TRSQMIM2F553H
    -A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -j KUBE-SEP-AR5TRSQMIM2F553H
    -A KUBE-SVC-NTZIAVXWXJCS7DKZ -m comment --comment "default/falkonry-hadoop:datanode" -j KUBE-SEP-KDTJFZVKN4ESIN24
    -A KUBE-SVC-PJO6V2NNIUDO2DKL -m comment --comment "default/falkonry-redis:redis-cli" -j KUBE-SEP-FV6ZZ4EMBZMV4DQ5
    -A KUBE-SVC-QIJ4ARI55YRJ76JG -m comment --comment "default/falkonry-spark-master:webui" -j KUBE-SEP-NGQUCFCRE45KSL73
    -A KUBE-SVC-RVQUD6RAXHQPQF3I -m comment --comment "default/falkonry-connector:http" -j KUBE-SEP-QLLLKZOFDP244LAS
    -A KUBE-SVC-SZGELJVIQ5IRMA57 -m comment --comment "default/falkonry-merlin:merlin-web" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-SX34LAYKH37CF5LT
    -A KUBE-SVC-SZGELJVIQ5IRMA57 -m comment --comment "default/falkonry-merlin:merlin-web" -j KUBE-SEP-BIZOCAOAPTCX4WBC
    -A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns" -j KUBE-SEP-SZZ7MOWKTWUFXIJT
    -A KUBE-SVC-U6PKKNLWPXOUUWIP -m comment --comment "default/falkonry-hadoop:namenode-ui" -j KUBE-SEP-HVHMJPRJS2UA65HH
    -A KUBE-SVC-XGPIXF43F4GLZBG7 -m comment --comment "default/falkonry-kafka:kafka" -j KUBE-SEP-6K3WNWFYOAH5UDZ7
    -A KUBE-SVC-Y4IVC7EWPWRMUFRE -m comment --comment "default/falkonry-mongo:mongo-http" -j KUBE-SEP-W4RNB3VXXTJ3LGHB
    -A WEAVE -s 10.32.0.0/12 -d 224.0.0.0/4 -j RETURN
    -A WEAVE ! -s 10.32.0.0/12 -d 10.32.0.0/12 -j MASQUERADE
    -A WEAVE -s 10.32.0.0/12 ! -d 10.32.0.0/12 -j MASQUERADE
    COMMIT
    # Completed on Fri Apr  7 12:16:32 2017
    # Generated by iptables-save v1.4.21 on Fri Apr  7 12:16:32 2017
    *filter
    :INPUT ACCEPT [741:270665]
    :FORWARD ACCEPT [0:0]
    :OUTPUT ACCEPT [727:337487]
    :DOCKER - [0:0]
    :DOCKER-ISOLATION - [0:0]
    :KUBE-FIREWALL - [0:0]
    :KUBE-SERVICES - [0:0]
    :WEAVE-NPC - [0:0]
    :WEAVE-NPC-DEFAULT - [0:0]
    :WEAVE-NPC-INGRESS - [0:0]
    -A INPUT -j KUBE-FIREWALL
    -A INPUT -d 172.17.50.1/32 -i docker0 -p tcp -m tcp --dport 6783 -j DROP
    -A INPUT -d 172.17.50.1/32 -i docker0 -p udp -m udp --dport 6783 -j DROP
    -A INPUT -d 172.17.50.1/32 -i docker0 -p udp -m udp --dport 6784 -j DROP
    -A INPUT -i docker0 -p udp -m udp --dport 53 -j ACCEPT
    -A INPUT -i docker0 -p tcp -m tcp --dport 53 -j ACCEPT
    -A FORWARD -i docker0 -o weave -j DROP
    -A FORWARD -j DOCKER-ISOLATION
    -A FORWARD -o docker0 -j DOCKER
    -A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    -A FORWARD -i docker0 ! -o docker0 -j ACCEPT
    -A FORWARD -i docker0 -o docker0 -j ACCEPT
    -A FORWARD -o weave -j WEAVE-NPC
    -A FORWARD -o weave -m state --state NEW -j NFLOG --nflog-group 86
    -A FORWARD -o weave -j DROP
    -A FORWARD -i weave ! -o weave -j ACCEPT
    -A FORWARD -o weave -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    -A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
    -A OUTPUT -j KUBE-FIREWALL
    -A DOCKER-ISOLATION -j RETURN
    -A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
    -A KUBE-SERVICES -d 10.111.87.193/32 -p tcp -m comment --comment "default/falkonryagent:agent-web has no endpoints" -m tcp --dport 9090 -j REJECT --reject-with icmp-port-unreachable
    -A WEAVE-NPC -m state --state RELATED,ESTABLISHED -j ACCEPT
    -A WEAVE-NPC -d 224.0.0.0/4 -j ACCEPT
    -A WEAVE-NPC -m state --state NEW -j WEAVE-NPC-DEFAULT
    -A WEAVE-NPC -m state --state NEW -j WEAVE-NPC-INGRESS
    -A WEAVE-NPC-DEFAULT -m set --match-set weave-k?Z;25^M}|1s7P3|H9i;*;MhG dst -j ACCEPT
    -A WEAVE-NPC-DEFAULT -m set --match-set weave-4vtqMI<kx/2]jD%_c0S%thO%V dst -j ACCEPT
    -A WEAVE-NPC-DEFAULT -m set --match-set weave-iuZcey(5DeXbzgRFs8Szo]<@p dst -j ACCEPT
    COMMIT
    # Completed on Fri Apr  7 12:16:32 2017

Kube-proxy logs

    I0406 19:42:35.453335       1 server.go:225] Using iptables Proxier.
    W0406 19:42:35.559100       1 proxier.go:309] clusterCIDR not specified, unable to distinguish between internal and external traffic
    I0406 19:42:35.559155       1 server.go:249] Tearing down userspace rules.
    I0406 19:42:35.711702       1 conntrack.go:81] Set sysctl 'net/netfilter/nf_conntrack_max' to 524288
    I0406 19:42:35.712557       1 conntrack.go:66] Setting conntrack hashsize to 131072
    I0406 19:42:35.713879       1 conntrack.go:81] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
    I0406 19:42:35.713949       1 conntrack.go:81] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600

**Comment by kargakis** [comment]
@kubernetes/sig-network-bugs

**Comment by phagunbaya** [comment]
To reproduce after deploying service and rc check the logs of `kafka` container
RC :

```
kind: "ReplicationController"
apiVersion: "v1"
metadata:
  name: "staging-kafka"
  labels:
    phase: "staging"
    function: "kafka"
spec:
  replicas: 1
  selector:
    name: "staging-kafka"
  template:
    metadata:
      labels:
        name: "staging-kafka"
        phase: "staging"
        function: "kafka"
    spec:
      containers:
        - name: "zookeeper"
          image: "docker.io/confluentinc/cp-zookeeper:3.1.1"
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
          ports:
            -
              containerPort: 2181
              protocol: "TCP"
          env:
            - name: "ZOOKEEPER_CLIENT_PORT"
              value: "2181"
          volumeMounts:
            -
              name: "stable-kafka-01"
              mountPath: "/var/lib/zookeeper/data"
              subPath: zookeeper-data
            -
              name: "stable-kafka-01"
              mountPath: "/var/lib/zookeeper/log"
              subPath: zookeeper-log
          imagePullPolicy: "Always"
        - name: "kafka"
          image: "docker.io/confluentinc/cp-kafka:3.1.1"
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
          ports:
            -
              containerPort: 9092
              protocol: "TCP"
          env:
            - name: "KAFKA_ZOOKEEPER_CONNECT"
              value: "staging-kafka:2181"
            - name: "KAFKA_ADVERTISED_LISTENERS"
              value: "PLAINTEXT://staging-kafka:9092"
          imagePullPolicy: "Always"
      restartPolicy: "Always"
```

Service:
```
kind: "Service"
apiVersion: "v1"
metadata:
  name: "staging-kafka"
  labels:
    phase: "staging"
    function: "kafka"
spec:
  ports:
    - name: "zookeeper"
      port: 2181
      targetPort: 2181
    - name: "broker"
      port: 9092
      targetPort: 9092
  selector:
    name: "staging-kafka"
```

**Comment by MrHohn** [comment]
Could you check if the kubelet on nodes are using `--hairpin-mode` flag?
```
--hairpin-mode string   How should the kubelet setup hairpin NAT. This allows endpoints of a Service to loadbalance back to themselves if they should try to access their own Service. Valid values are "promiscuous-bridge", "hairpin-veth" and "none". (default "promiscuous-bridge")
```

cc @freehan

**Comment by MrHohn** [comment]
Maybe related to #43966.

**Comment by eviloop** [comment]
Hello,
 I believe this issue is currently affecting the use K8S Addon for monitoring on 1.6.x

https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/cluster-monitoring

This is due to Grafana using a Service to contact Influx which is running on the same Pod on a different port

Changing the Grafana connection to localhost solves the issue.
All other applications have no issue connecting to the service.

I have no explicit --hairpin-mode configuration, therefore is using the default value.

**Comment by DocValerian** [comment]
Also this issue: #42314 may be related to this topic

**Comment by MrHohn** [comment]
cc @dnardo

**Comment by eviloop** [comment]
Additional notes:

hairping mode is reporting 0 - the wrong value
I see no nsenter errors - it does fallback to hairpin-veth

I have tried with default weave-net 1.9.4  and i have tried adding 
```
{
    "name": "weave-net",
    "type": "weave",
    "delegate": { "hairpinMode" : true }
}
```
Maybe i have a typo or the cni config wrong ? I kubectl exec into weave and double checked that the file is there

**Comment by caseydavenport** [comment]
I think this is a symptom of this issue: https://github.com/kubernetes/kubernetes/issues/45790

In v1.6, kubernetes no longer configures hairpin mode.  According to that thread this should now be configured by the 3rd-party CNI plugin in use.

CC @bboreham

**Comment by bboreham** [comment]
Just to be explicit: 1.6 has two implementations (CRI and non-CRI) and it's the CRI one that doesn't set hairpin when using CNI. CRI is the default but you can select the other with `--enable-cri=false`

1.7 will remove the non-CRI choice. 

For Weave Net specifically we will add the hairpin setting at https://github.com/weaveworks/weave/pull/2971

**Comment by caseydavenport** [comment]
I think this can be closed since it's covered in #45790.

/assign

**Comment by liggitt** [comment]
Typically newer issues are closed in favor of older ones :)

**Comment by caseydavenport** [comment]
> Typically newer issues are closed in favor of older ones :)

d'oh, sorry.
