### ISSUE TITLE
API server accepts invalid ThirdPartyResources with missing `kind`

### ISSUE THREAD

**Issue by paultiplady** [kubernetes/kubernetes#44182]
**Is this a request for help?** 
No

**What keywords did you search in Kubernetes issues before filing this one?** 
"Object 'Kind' is missing"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): cos
- **Kernel** (e.g. `uname -a`): `Linux gke-build-pool-1-d6aee0ac-hfrl 4.4.21+ #1 SMP Fri Feb 17 15:34:45 PST 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux`
- **Install tools**: GKE
- **Others**:

**What happened**:
Creating a ThirdPartyResource using the REST API directly, without passing a `kind` in the JSON gives a success response, and produces an object which cannot be retrieved over the API.

Instead of retrieving the object, the error `error: Object 'Kind' is missing in <data>` is returned.

**What you expected to happen**:
Either the TPR should be rejected if the JSON is invalid, or the subsequently created object should be readable.

**How to reproduce it** (as minimally and precisely as possible):

Create this TPR:
```
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "A specification of a Let's Encrypt Certificate to manage."
metadata:
  name: "certificate.stable.k8s.psg.io"
versions:
  - name: v1
```

and then submit this JSON:

Broken:
```
# curl -X POST -d '{"metadata": {"namespace": "default", "name": "broken-cert"}, "email": "admin@example.com", "domain": "example.com", "provider": "googlecloud", "secretName": "example.com"}' http://localhost:8001/apis/stable.k8s.psg.io/v1/namespaces/default/certificates/ -H 'Content-type: application/json'
# kubectl get certificates broken-cert
error: Object 'Kind' is missing in '{"domain":"example.com","email":"admin@example.com","metadata":{"name":"broken-cert","namespace":"default","selfLink":"/apis/stable.k8s.psg.io/v1/namespaces/default/certificates/broken-cert","uid":"592579bb-1b12-11e7-bbc0-42010a80000b","resourceVersion":"26694804","creationTimestamp":"2017-04-06T21:45:27Z"},"provider":"googlecloud","secretName":"example.com"}
```

Working:
```
# curl -X POST -d '{"kind": "Certificate", "metadata": {"namespace": "default", "name": "working-cert"}, "email": "admin@example.com", "domain": "example.com", "provider": "googlecloud", "secretName": "example.com"}' http://localhost:8001/apis/stable.k8s.psg.io/v1/namespaces/default/certificates/ -H 'Content-type: application/json'
# kubectl get certificates working-cert
NAME           KIND
working-cert   Certificate
```
(Note the only difference in the working case is specifying the `"kind": "Certificate"`)

**Comment by xingzhou** [comment]
I'd like to take a look at this

**Comment by enisoc** [comment]
The deprecated TPR API has been removed in master (#48152). This doesn't appear to be a regression, so we will recommend upgrading to CRD in 1.7+ rather than backporting a fix to TPR. CRD does not suffer from this problem; the server side rejects objects with a missing or incorrect Kind.
