### ISSUE TITLE
Updated scheduler to use client-go

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#44188]
**Is this a BUG REPORT or FEATURE REQUEST? (choose one)**:
feature request

**Kubernetes version (use kubectl version)**:
master branch

**What happened**:
According to discussion at kubernetes/client-go#136 , we'd like to upgrade `scheduler` to use client-go after lister, informer is ready.

**Comment by deads2k** [comment]
This is a good idea.  @k82cn are you actively working on it?  If so, I can assign you.

**Comment by k82cn** [comment]
:). sure, I'll handle this.

/assign

**Comment by k82cn** [comment]
Slack with caesarxuchao@ , we'd like to move this into 1.8 as this dependent on some client-go enhancement in 1.7 (https://github.com/kubernetes/kubernetes/pull/44784).

**Comment by k82cn** [comment]
priority/important-longterm
