### ISSUE TITLE
kubectl logs more consistent behavior with pending nodes

### ISSUE THREAD

**Issue by 8enmann** [kubernetes/kubernetes#44190]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
"kubectl logs"
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

```
zagreb rlftw$ kubectl get pod rlftw170330-205352m0
NAME                   READY     STATUS    RESTARTS   AGE
rlftw170330-205352m0   0/1       Pending   0          55s
zagreb rlftw$ kubectl logs -f rlftw170330-205352m0
zagreb rlftw$
```
but:
```
zagreb rlftw$ kubectl get pod rlftw170330-205124w03
NAME                    READY     STATUS              RESTARTS   AGE
rlftw170330-205124w03   0/1       ContainerCreating   0          6m
zagreb rlftw$ kubectl logs -f rlftw170330-205124w03
Error from server (BadRequest): container "main" in pod "rlftw170330-205124w03" is waiting to start: ContainerCreating
```
* 1 choice: when -f is specified, wait until the pod appears. When not specified, return an error
* 2 choice: return an error always

**Kubernetes version** (use `kubectl version`):
```
k version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-22T10:12:27Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
Azure cluster
- **OS** (e.g. from /etc/os-release):
Mac OSX
- **Kernel** (e.g. `uname -a`):
uname -a
Darwin Benjamins-MacBook-Pro.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
- **Install tools**:
- **Others**:

**What happened**:
`kubectl logs` gives error for some Pod statuses (`ContainerCreating`) but fails silently for others (`Pending`)

**What you expected to happen**:
If `Pending`, wait for pod to come up (preferable if `-f`) or return similar error as `ContainerCreating`

**How to reproduce it** (as minimally and precisely as possible):
Create a pod that takes a long time to come up, then run `kubectl logs -f $POD_NAME`.

**Anything else we need to know**:

**Comment by supereagle** [comment]
@8enmann  Could you describe this issue in more detail? What is your expection?

**Comment by 8enmann** [comment]
Sorry, my description was accidentally in the commented out section of the form. Fixed!

**Comment by 8enmann** [comment]
@supereagle any ideas?

**Comment by 8enmann** [comment]
Ping

**Comment by supereagle** [comment]
@8enmann  Sorry for late response, I'm a little busy recently. I will take a look at this issue tomorrow.

**Comment by supereagle** [comment]
I think `kubectl logs -f` needs to report error for unready pod status, such as `ContainerCreating` and `Pending`. No error for `Pending` pods may mislead the users to think that there is no output for the pods, and ignore the unready status. An enhancement is needed here.

Kindly ping @liggitt

**Comment by spiffxp** [comment]
/sig cli
/sig api-machinery
Not sure which sig is more appropriate here
