### ISSUE TITLE
Dynamically Provisioned RBD Volumes Fail to Delete

### ISSUE THREAD

**Issue by ikaven1024** [kubernetes/kubernetes#44206]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): Volume has no class annotation

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  BUG REPORT

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
I' am using v1.6.1. I created a PVC with StorageClass, and a PV is provisoned. But when i delete pvc, the pv is fail to delete, reporting: 
```
VolumeFailedDeleteFailed to create deleter for volume "pvc-0949509f-1b90-11e7-bcf6-fa163e5a8a0a": Volume has no class annotation
```
in the pv, there is no annotations:`volume.beta.kubernetes.io/storage-class`
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/rbd
  creationTimestamp: 2017-04-07T12:45:10Z
  name: pvc-0949509f-1b90-11e7-bcf6-fa163e5a8a0a
  resourceVersion: "1430661"
  selfLink: /api/v1/persistentvolumespvc-0949509f-1b90-11e7-bcf6-fa163e5a8a0a
  uid: 0991f917-1b90-11e7-bcf6-fa163e5a8a0a
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: myclaim
    namespace: default
    resourceVersion: "1430476"
    uid: 0949509f-1b90-11e7-bcf6-fa163e5a8a0a
  persistentVolumeReclaimPolicy: Delete
  rbd:
    image: kubernetes-dynamic-pvc-094c6ffa-1b90-11e7-afec-fa163e5a8a0a
    keyring: /etc/ceph/keyring
    monitors:
    - 10.33.46.2
    - 10.33.46.3
    - 10.33.46.4
    pool: rbd
    secretRef:
      name: ceph-secret
    user: admin
  storageClassName: large
status:
  message: 'Failed to create deleter for volume "pvc-0949509f-1b90-11e7-bcf6-fa163e5a8a0a":
    Volume has no class annotation'
  phase: Failed
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
my PVC is like
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: large
```
and StorageClass is
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: large
provisioner: kubernetes.io/rbd
parameters:
  monitors: 10.33.46.2,10.33.46.3,10.33.46.4
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: internal
  pool: rbd
  userId: admin
  userSecretName: ceph-secret
```

**Anything else we need to know**:

**Comment by NickrenREN** [comment]
same to #43929
