### ISSUE TITLE
Secrets folder is mounted but empty (Service account and ordinary secrets)

### ISSUE THREAD

**Issue by anteyk** [kubernetes/kubernetes#44200]
Hi Team.
My secret's folder on pods is always empty. There are many of such issues, but they not strictly corresponds to my, or I didn't found proper issue. Here is info about my setup
```
kubectl describe serviceaccounts
Name:           default
Namespace:      default
Labels:         <none>
Image pull secrets:     <none>
Mountable secrets:      default-token-2k6t8
Tokens:                 default-token-2k6t8

kubectl get secrets
NAME                  TYPE                                  DATA      AGE
db-user-pass          Opaque                                2         33m
default-token-2k6t8   kubernetes.io/service-account-token   3         36d
```

kubectl describe secret shows that default-token-2k6t8 contains 3 files (ca.crt, namespace, token)
on kubelet folder exist and contains files
```
 ls /var/lib/kubelet/pods/d5944022-1b61-11e7-9b45-0cc47a7351d4/volumes/kubernetes.io~secret/default-token-2k6t8/
ca.crt  namespace  token

```
in kubelet.log I see 
`I0407 10:27:54.406390   13509 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/d5944022-1b61-11e7-9b45-0cc47a7351d4-default-token-2k6t8
`
which is repeated every ~30 seconds
mount inside pod (it has only one container) returns
`/dev/sda2 on /run/secrets/kubernetes.io/serviceaccount type ext4 (ro,relatime,data=ordered)
`
but folder /run/secrets/kubernetes.io/serviceaccount is empty.
Also I tried to create custom secret and mount it to pod, but with no luck.

My OS is Oracle Linux Server release 6.9. Docker is installed from https://yum.dockerproject.org/repo/main/oraclelinux/6/
SELinux is disabled
Docker version
```
Client:
Version: 1.12.3
API version: 1.24
Go version: go1.6.3
Git commit: 6b644ec
Built:
OS/Arch: linux/amd64
Server:
Version: 1.12.3
API version: 1.24
Go version: go1.6.3
Git commit: 6b644ec
Built:
OS/Arch: linux/amd64
```
Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
EDIT
Just forget to mention, that config map mounts successfully and contains all provided files

**Comment by anteyk** [comment]
Bump... am I'm missing something or it's a real trouble?

**Comment by liggitt** [comment]
do you see this issue with all secret volume mounts?

cc @kubernetes/sig-storage-bugs @pmorie @ncdc

**Comment by ncdc** [comment]
What kernel version do you have? It may be too old / have bugs re mounts.

**Comment by anteyk** [comment]
Hi team, sorry for delay.
Kernel version is 
```
# uname -mrs
Linux 4.1.12-61.1.33.el6uek.x86_64 x86_64
```

**Comment by jstoja** [comment]
Hi @anteyk,

Do you still have the issue? Have you tried with a more recent version of Kubernetes?
I'm not kernel expert, but `4.1.12` seem quite old, having a more recent version might help too.

**Comment by anteyk** [comment]
Hi, @jstoja 
We switched to ubuntu 16.04 and other version of kubernetes
`Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
`
and there all things goes fine.

**Comment by jstoja** [comment]
I tried to reproduce too and didn't run into this issue with recent versions of Kubernetes.
I think this is closable until someone can report it with reproducible steps.

**Comment by zl4bv** [comment]
Seeing this with all secret mounts - other mounts working as expected.

```
$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
$ uname -mrs
Linux 4.4.0-97-generic x86_64
```

I also experienced the issue with a previous install of Docker on the same host:

```
$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64
```

My steps to reproduce on a single host install (development setup):

```
$ cp /etc/cni/net.d/10-mynet.conf $HOME/10-mynet.conf
$ kubeadm reset
$ cp $HOME/10-mynet.conf /etc/cni/net.d/10-mynet.conf
$ kubeadm init
```

**Comment by zl4bv** [comment]
My issue appears to have been the result of the MountFlags configuration set by an old installation of Docker. By applying the change in https://github.com/moby/moby/pull/22806 I have resolved this issue on the node described in my previous comment.
