### ISSUE TITLE
[Proposal] Make scale up/down forbidden time configurable

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#44202]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Nowerdays, the autoscaler hard-code the scale up/down forbidden time here https://github.com/kubernetes/kubernetes/blob/release-1.6/pkg/controller/podautoscaler/horizontal.go#L97-L98

```
var downscaleForbiddenWindow = 5 * time.Minute
var upscaleForbiddenWindow = 3 * time.Minute
```

It is more reasonable to make this configurable in HPA policy config as different deployment may have different request for those times.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by gyliu513** [comment]
ping @kubernetes/sig-autoscaling-misc  @kubernetes/sig-autoscaling-feature-requests can anyone show some comments for this? Hope we can have this in 1.7

**Comment by fgrzadkowski** [comment]
We had a similar discussion https://github.com/kubernetes/kubernetes/pull/32408. Adding this to HPA policy would expose internals of the algorithm. However as explained in the other thread we should fix underlying issues that this code is trying to workaround.

CC-ing @DirectXMan12 and @mwielgus who were involved in the original discussions.

**Comment by gyliu513** [comment]
Why adding this would expose internals of the algorithm? In OpenStack Heat, we already adding a parameter such as `cooldown` to do the similar work https://github.com/openstack/heat-templates/blob/master/contrib/rackspace/RackspaceAutoScale.yaml#L40

**Comment by gyliu513** [comment]
Thanks @fgrzadkowski , the #32408 does help a lot.

**Comment by fgrzadkowski** [comment]
On a high level, because we should not need this knob at all and detect it automatically. Details of this reasoning in the other issue.
