### ISSUE TITLE
Pod eviction on nodefsInodes has no GC feature.

### ISSUE THREAD

**Issue by Juanchimienti** [kubernetes/kubernetes#44208]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

nodefsInodes, 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Google Compute engine
- **OS** (e.g. from /etc/os-release): 
BUILD_ID=8872.47.0
NAME="Container-VM Image"
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=55
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Google Container-VM Image"
VERSION=55
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=gci

- **Kernel** (e.g. `uname -a`):
Linux ******** 4.4.21+ #1 SMP Thu Nov 10 21:43:53 PST 2016 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux

- **Install tools**:
- **Others**:

**What happened**:
One of our nodes started evicting pods with the alert: "Attempting to reclaim nodefsInodes"

**What you expected to happen**:
I would expect that the GC would delete old images when nodefsInode pass a thresshold before starting the eviction.

**How to reproduce it** (as minimally and precisely as possible):
I do not know exactly how to reproduce it but I assume that it has to do with docker images wich generate lots of files, perhaps because of too many layers 

**Anything else we need to know**:

**Comment by dashpole** [comment]
Can you see if your kubelet logs contain `[imageGCManager]: Removing image`... or `eviction manager: able to reduce nodefsInodes pressure without evicting pods.`
The kubelet should attempt to delete unused images before evicting pods.  Let me know if that is not the case.  If you are actively running containers that have a large number of layers, then those cannot be deleted without evicting the pod first, since those images are still in use.

**Comment by Juanchimienti** [comment]
I am not able to reproduce the problem, Now is doing as you say once it reach 95% inodes the kubelet starts deleting old images.
