### ISSUE TITLE
kubeadm not able to bootstrap a cluster with v1.7.0-alpha.1

### ISSUE THREAD

**Issue by klinakuf** [kubernetes/kubernetes#44205]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**v1.6.2-beta.0** (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.1", GitCommit:"176eb0e509a255dd520de135cda31096f8796be5", GitTreeState:"clean", BuildDate:"2017-04-06T20:00:18Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
`

**Environment**: 
- **Cloud provider or hardware configuration**: private cloud provider
- **OS** (e.g. from /etc/os-release): ubuntu-16.04-amd64
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

I tried to bootstrap a cluster with kubeadm init using --kubernetes-version=1.7.0-alpha.1 but it does not work. Nodes remain in a NotReady state. 

The kubedns are not able to start (0/3) with FailedScheduling event fired. 

I am able to join a node but it appears NotReady. The weave-net in the node is not able to start due to "the server does not allow access to the requested resource"

**Comment by liggitt** [comment]
thanks for the issue report. please open kubeadm-related issues against https://github.com/kubernetes/kubeadm/issues/

**Comment by luxas** [comment]
@klinakuf Please reopen in the kubeadm repo, closing this now...
