### ISSUE TITLE
Cannot use v1.5 api in kubernetes 1.6.1

### ISSUE THREAD

**Issue by dorry-terryli** [kubernetes/kubernetes#44201]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **OS** (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```

- **Kernel** (e.g. `uname -a`):
`Linux terry-desktop 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**What happened**:
I found the kubeadm only have version 1.6.1 and required kubectl >= 1.6.0 and kubelet >= 1.6.0. But I need to use kube v1.5 api for some reason. And I cannot downgrade the kubeadm version.Can i use v1.5 kube api in kubernetes 1.6.1?

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by Demonsthere** [comment]
If i understand you correctly you want to spawn a cluster of version 1.5.x on the 1.6 binaries?
If so just add this flag to `kubeadm init`:
`--kubernetes-version string               Choose a specific Kubernetes version for the control plane (default "v1.6.0")`

**Comment by luxas** [comment]
@dorry-terryli It's correct that you can't spin up a v1.5 master with v1.6 kubeadm. You may be able to downgrade kubeadm to do that though.

Anyway, it's working as expected. If you still think it's an issue, please reopen in the kubeadm repo...
