### ISSUE TITLE
[Feature Request] LXD local method does not appear to have minikube service my-service equivalent

### ISSUE THREAD

**Issue by xamox** [kubernetes/kubernetes#44218]
I've installed k8s locally for testing using the LXD method outlined here:
https://kubernetes.io/docs/getting-started-guides/ubuntu/local/

Everything works fine, except for the fact when I want to test my services there doesn't appear to be an external IP when I expose it with `kubectl expose`.  With minikube I just had to do a `minikube service my-service` and it will return an IP with a mapped port that exposes the load balancer.

`Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"283137936a498aed572ee22af6774b6fb6e9fd94", GitTreeState:"clean", BuildDate:"2016-07-01T19:26:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
`

**Comment by kargakis** [comment]
@marcoceppi

**Comment by jagosan** [comment]
/sig network
.. as a starting point.  please update with correct sig if mis-labeled.
