### ISSUE TITLE
Basic StatefulSet functionality [StatefulSetBasic] should provide basic identity is flaky

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#44229]
/assign @bprashanth @lavalamp @erictune 

`Basic StatefulSet functionality [StatefulSetBasic] should provide basic identity is flaky` flakes in PR jobs more than once per day

The [triage tool](http://go.k8s.io/triage) can filter down to searching for results for a single test:
* https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=should%20provide%20basic%20identity

**Comment by fejta** [comment]
This test continues to flake PRs at least once per day: https://groups.google.com/d/msg/kubernetes-sig-cli/DN56n_qvxrc/TeGbrMz1DgAJ

**Comment by mml** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/44513/pull-kubernetes-e2e-gce-non-cri/7686/#k8sio-statefulset-k8sio-basic-statefulset-functionality-statefulsetbasic-should-provide-basic-identity

**Comment by kow3ns** [comment]
looking at it
