### ISSUE TITLE
Downward API volume should update labels on modification flakes at least once per day

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#44226]
/assign @timothysc @dchen1107 @matchstick 

See https://github.com/kubernetes/test-infra/blob/master/experiment/bigquery/flakes-latest.json

`Downward API volume should update labels on modification` flakes at least once per day in the following job:
* gce-container-vm: https://k8s-testgrid.appspot.com/google-gce#gce-container-vm&width=5&sort-by-failures=

[Triage dashboard](http://go.k8s.io/triage) can filter down to just this job, which shows it fails around every other hour:
* https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Downward%20API%20volume%20should%20update%20labels%20on%20modification

**Comment by fejta** [comment]
Note this is still flaking around once per day in `pull-kubernetes-e2e-gce`

Assigning sig owners:
/assign @derekwaynecarr @dchen1107 

Assigning test owner:
/assign @timothysc 

Timothy if you do not want to own this test please update [`test_owners.csv`](https://github.com/kubernetes/kubernetes/blob/master/test/test_owners.csv#L112) with the new owner and then reassign the issue to that person.

126 out of 173 failures [this week](https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=Downward%20API%20volume%20should%20update%20labels%20on%20modification) were failing to find `key="value3"`.

**Comment by ncdc** [comment]
This appears to happen because the kubelet is unable to unmount the current downward api mount (it typically gets a device or resource busy error). We have yet to determine the cause.

**Comment by ncdc** [comment]
cc @pmorie @sjenning

**Comment by ncdc** [comment]
xref #44227, these will most likely have the same root cause, I would think
