### ISSUE TITLE
kubeadm not respecting the --apiserver-advertise-address flag

### ISSUE THREAD

**Issue by cpo** [kubernetes/kubernetes#44220]
**Is this a request for help?** no

**What keywords did you search in Kubernetes issues before filing this one?** apiserver-advertise-address

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT?

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
Hetzner VPS (one for master and one for worker)
The funky part is that the interfaces do NOT report the external IP address but some type of virtual IP address. The machine IS reachable through the external IP however.
- **OS** (e.g. from /etc/os-release):
Ubuntu 16.10 (up-to-date)
- **Kernel** (e.g. `uname -a`):
`Linux kubem 4.8.0-45-generic #48-Ubuntu SMP Fri Mar 24 11:46:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**:
Apt
- **Others**:
Ansible

**What happened**:
I installed the master with the following flags:

`kubeadm init --pod-network-cidr 10.244.0.0/16 --apiserver-cert-extra-sans kubem,[EXTERNAL-IP-ADDRESS] --apiserver-advertise-address [EXTERNAL-IP-ADDRESS] --token [RUBBED OUT]`

**What you expected to happen**:
That the configs of kubernetes which were created by kubeadm contained the [EXTERNAL-IP-ADDRESS] instead of the virtual network IP, allowing the worker to join it in a normal fashion, but instead the configs contained:

(example)
```
root@kubem /etc/kubernetes # grep -R 172.31.1.100 .
./manifests/kube-apiserver.yaml:    - --advertise-address=172.31.1.100
./scheduler.conf:    server: https://172.31.1.100:6443
./kubelet.conf:    server: https://172.31.1.100:6443
./controller-manager.conf:    server: https://172.31.1.100:6443
./admin.conf:    server: https://172.31.1.100:6443
```

It should be obvious that the 172.xxxx ip address is the address reported by the network interface and not the public ip address. The worker cannot join because it will have the wrong address advertised to itself by the master.

```
root@kubem /etc/kubernetes # ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.31.1.100  netmask 255.255.255.0  broadcast 172.31.1.255
        inet6 [RUBBED OUT]  prefixlen 64  scopeid 0x20<link>
        inet6 [RUBBED OUT]  prefixlen 64  scopeid 0x0<global>
        ether [RUBBED OUT]  txqueuelen 1000  (Ethernet)
        RX packets 882971  bytes 363105353 (363.1 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 988150  bytes 172957217 (172.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 22475941  bytes 4690058246 (4.6 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 22475941  bytes 4690058246 (4.6 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**How to reproduce it** (as minimally and precisely as possible):
Take a machine with an adapter IP different than the external IP, run kubeadm with --apiserver-advertise-address, kubeadm will create config files with the internal IP address.

**Anything else we need to know**:
Ansible rocks, kubernetes too (when I get it running, that is) :-)

**Comment by jamiehannaford** [comment]
That's odd. The only reason AFAIK why kubeadm would revert to the host interface is if the provided IPv4 is unspecified (`0.0.0.0`) or a loopback (`127.0.0.1`). Would you mind specifying the IPv4 you used, or a similar one?

**Comment by cpo** [comment]
Ok, so I feel a bit stupid now: The Ansible script used the wrong variable (effectively passing in the hostname instead of the IP address). Additional testing showed that now all the configs contain the correct IP address and the worker node is able to connect.

Maybe it is a good idea to not accept invalid IP addresses and throw some error. But for now it seems to work! 

Thanks and regards,

Chris

**Comment by jamiehannaford** [comment]
What type of value was Ansible providing, a random string? The behaviour is to use a default if a missing value is provided. I'm personally not sure what extra value advanced validation logic would provide.

Would you mind closing the issue if you're happy to? Glad you sorted it! :)

**Comment by cpo** [comment]
In this case "kubem" (the hostname for this master).

Thanks!
