### ISSUE TITLE
Projected should update labels on modification flakes at least once per day

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#44227]
/assign @xiang90 @saad-ali @matchstick 

See https://github.com/kubernetes/test-infra/blob/master/experiment/bigquery/flakes-latest.json

The `Projected should update labels on modification` flakes once a day in 1 job:
* gci-gce-etcd3: https://k8s-testgrid.appspot.com/google-gce#gci-gce-etcd3&width=5&sort-by-failures=

The [triage dashboard](http://go.k8s.io/triage) can filter down to just this test, which shows it fails somewhere every other hour:
* https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Projected%20should%20update%20labels%20on%20modification

**Comment by saad-ali** [comment]
Related to https://github.com/kubernetes/kubernetes/issues/29633?

@yifan-gu or @ivan4th can you take a look.

**Comment by ncdc** [comment]
xref #44226, these will most likely have the same root cause, I would think

**Comment by ivan4th** [comment]
From quick glance the problem described in #29633 did not go away, so it may be indeed the reason. I've posted an updated description as a comment for #29633 (made it point to proper lines in current master)

**Comment by ncdc** [comment]
I don't think 29633 is related to this. The current failures are device or
resource busy errors failing to unmount the old volume, if I'm not
mistaken.

**Comment by ncdc** [comment]
@ivan4th hmm maybe you're right. I just checked one failure at random and couldn't find a device or resource busy error in the log.
