### ISSUE TITLE
Services should preserve source pod IP for traffic thru service cluster IP flakes

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#44225]
/assign @Random-Liu @matchstick 

See https://github.com/kubernetes/test-infra/blob/master/experiment/bigquery/flakes-latest.json

Testgrid shows this flakes more than once per day in two jobs:
* gce-proto: https://k8s-testgrid.appspot.com/google-gce#gce-proto&width=5&sort-by-failures=
* non-cri-gce: https://k8s-testgrid.appspot.com/google-non-cri#gce&width=20&sort-by-failures=

You can filter go.k8s.io/triage down to just this test, which shows it fails about once per hour:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Services%20should%20preserve%20source%20pod%20IP%20for%20traffic%20thru%20service%20cluster%20IP

**Comment by MrHohn** [comment]
Flakes are introduced by commit dea98cbdd0576f54c5b481285a6974f5aa24b7f5:
```
wait for pod "kube-proxy-mode-detector" to disappear
Expected success, but got an error:
    <*errors.errorString | 0xc420450fd0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the conditio
```

**Comment by MrHohn** [comment]
Update: Bump up pod deletion time seems have reduced a big portion of failures.
The remaining cases doesn't seems to be related to this test itself.
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=source%20pod%20ip

**Comment by MrHohn** [comment]
Closing per above comment.

/close
