### ISSUE TITLE
kubelet pod start latency is NaN

### ISSUE THREAD

**Issue by gp1105739** [kubernetes/kubernetes#44233]
I am using <node-IP>:10255/metrics to scrape kubelet_pod_start_latency but it is always like the following:

# HELP kubelet_pod_start_latency_microseconds Latency in microseconds for a single pod to go from pending to running. Broken down by podname.
# TYPE kubelet_pod_start_latency_microseconds summary
kubelet_pod_start_latency_microseconds{quantile="0.5"} NaN
kubelet_pod_start_latency_microseconds{quantile="0.9"} NaN
kubelet_pod_start_latency_microseconds{quantile="0.99"} NaN
kubelet_pod_start_latency_microseconds_sum 2.37294556e+08
kubelet_pod_start_latency_microseconds_count 198

Why is it always showing NaN?

**Comment by ncdc** [comment]
See https://github.com/prometheus/prometheus/issues/860

**Comment by kargakis** [comment]
@kubernetes/sig-node-bugs
