### ISSUE TITLE
kubectl patch node Opaque Integer Resource doesn't take effect

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#44269]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
HEAD

**Environment**: May have nothing to do with env
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
`kubectl patch node 192.168.1.220 --type='json' -p='[{"op": "add", "path": "/status/capacity/pod.alpha.kubernetes.io~1opaque-int-resource-bananas", "value": "555"}]'`

This command doesn't take effect. The result is `node "192.168.1.220" not patched`

**What you expected to happen**:
The OIR has been patched to the node capacity.

**How to reproduce it** (as minimally and precisely as possible):
exec above command.

**Anything else we need to know**:
ref https://github.com/kubernetes/kubernetes/issues/41861#issuecomment-292668454

Below two ways work:
```
curl --header "Content-Type:application/json-patch+json" \
--request PATCH \
--data '[{"op": "add", "path": "/status/capacity/pod.alpha.kubernetes.io~1opaque-int-resource-bananas", "value": "555"}]' \
http://192.168.1.225:8080/api/v1/nodes/192.168.1.220/status
```

```
echo '[{"op": "add", "path": "/status/capacity/pod.alpha.kubernetes.io~1opaque-int-resource-bananas", "value": "555"}]' | \
http PATCH http://localhost:8080/api/v1/nodes/192.168.1.220/status \
Content-Type:application/json-patch+json
```

**Comment by xiangpengzhao** [comment]
cc @ConnorDoyle @smart2003

**Comment by smart2003** [comment]
I can add the opaque-int-resource on the master node via patching the http://localhost:8080/api/v1/nodes/192.168.1.220/status. While, it does not work on worker node when the security check is set. masterIP:8080 is not accessible without authentication.

**Comment by xiangpengzhao** [comment]
@smart2003 Do you mean you can add OIR by `kubectl patch node` command? Does the command you run like this?
```
kubectl patch node 192.168.1.220 --type='json' -p='[{"op": "add", "path": "/status/capacity/pod.alpha.kubernetes.io~1opaque-int-resource-bananas", "value": "555"}]'
```

I cannot add OIR by this command.

**Comment by smart2003** [comment]
@xiangpengzhao I can not either. I also add the OIR via curl on the master node. While, it does not work for me on the worker node which can not access the api-server without authentication.

**Comment by xiangpengzhao** [comment]
update:

Use the HEAD code, current result of `kubectl patch node` is:
`The result is node "192.168.1.220" patched` (former result is `not patched`)

Though with the new result, I still can't see the OIR in node capacity neither by `kubectl describe node` nor `kubectl get node -o json`
