### ISSUE TITLE
Remove the request of running critical pods in kube-system namespace

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#44262]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Currently, based on https://kubernetes.io/docs/concepts/cluster-administration/guaranteed-scheduling-critical-addon-pods/ , if I want to create some `critical pods`, then I must create those pods in `kube-system` namespace, otherwise, I cannot create `critical pods`.

**What you expected to happen**:
I think we should remove the limitation of `critical pods must running in kube-system namespace`. For some cases, the customer may already have their own namespaces and they want to run some critical pods in their own namespace.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by piosz** [comment]
This works as intended. Rescheduler was a solution for problem with Kubernetes components running in user space and we strongly discourage users from using it. The proper priority/preemption support is coming in 1.7 (?).

cc @davidopp

**Comment by gyliu513** [comment]
Good to know, but what is the reason that we want to limit the `critical pod` preemption limited to kubernetes components? @piosz

**Comment by piosz** [comment]
There is no stable api, no guarantee that it scales and no integration with Pod Disruption Budget. Also once the proper priority/preemption is introduced we will drop support for Rescheduler without any grace period.

**Comment by gyliu513** [comment]
I see, thanks @piosz
