### ISSUE TITLE
NetworkPluginNotReady

### ISSUE THREAD

**Issue by nicky-lenaers** [kubernetes/kubernetes#44273]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): "NetworkPluginNotReady", "" 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): **BUG REPORT**

**Kubernetes version** (use `kubectl version`): 1.6.0

**Environment**:
- **Cloud provider or hardware configuration**:
Google Cloud Container Engine
- **OS** (e.g. from /etc/os-release):
```sh
UILD_ID=9000.84.2
NAME="Container-Optimized OS"
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=56
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=56
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
```
- **Kernel** (e.g. `uname -a`):
```sh
Linux gke-nite-www-container-c-default-pool-e3fceabe-0rns 4.4.21+ #1 SMP Fri Feb 17 15:34:45 PST 2017 x86_64 Intel(
R) Xeon(R) CPU @ 2.60GHz GenuineIntel GNU/Linux
```
- **Install tools**:
- **Others**:

**What happened**:
When creating a Kubernetes deployment to my GKE cluster using `kubectl create -f deployment.json` I open de kubernetes dashboard using `kubectl proxy`, and it gives me the following Error under `Deployments` and `Replica Sets`:
```sh
Error syncing pod, skipping: network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]
```

**What you expected to happen**:
Successful creation of deployment.

**How to reproduce it** (as minimally and precisely as possible):
1 Create a GKE Cluster with the following details:
```sh
gcloud container clusters create test-cluster --zone=europe-west1-b --machine-type=f1-micro --num-nodes=3 --cluster-version=1.6.0
```
2. Connect to the cluster using:
```sh
gcloud container clusters get-credentials test-cluster \
    --zone europe-west1-b --project nite-www
```
3. Create a Deployment
```sh
kubectl create -f deployment.json
```
Deployment file (you'll need a public image such as `nginx`):
```sh
{
	"apiVersion": "extensions/v1beta1",
	"kind": "Deployment",
	"metadata": {
		"name": "test-deployment"
	},
	"spec": {
		"replicas": 3,
		"revisionHistoryLimit": 10,
		"minReadySeconds": 60,
		"template": {
			"metadata": {
				"labels": {
					"app": "test-deployment"
				}
			},
			"spec": {
				"containers": [
					{
						"image": "nginx",
						"name": "test-container",
						"ports": [
							{
								"containerPort": 8000
							}
						]
					}
				]
			}
		}
	}
}

```

**Anything else we need to know**:
Nope, that's it.

**Comment by nicky-lenaers** [comment]
As an addition to this issue:

I spent many hours trying to find the root cause of this problem. I ended up creating a test cluster without specifying the `--machine-type` flag, which in GKE defaults to `n1-standard-1`. As I rolled out my depoyment, I noticed the errors disappeared.

In the above issue description, I specified the `--machine-type=f1-micro`, so my belief is that is has to do with insufficient memory and/or disk usage needed for e.g. image pulling.

Hope this helps debugging!

**Comment by cehoffman** [comment]
Add verification to this that I tried to run 3 separate pods totaling about 50-60mb of used RAM and ran into this continually occurring pod network failure. The running services were not stable and would constantly fail and restart despite there being 300Mb of system memory unused in the cluster over 3 machines.

Adding a new pool of machines based on the `n1-standard-1` type and decomissioning the `f1-micro` machines resolved the problem.

**Comment by whitecolor** [comment]
I have this eror mongodb pod (not replica set, not stateful set): `Error syncing pod, skipping: network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR`

Cluster on GCE 2 g1micro. This seem to happen when I try to restore database to this server remotely. What can be the reason?

**Comment by zetaab** [comment]
I have this same issue in 4x highcpu-4 machines
```
kubectl get pods
NAME                         READY     STATUS             RESTARTS   AGE
es-client-2882000496-sdwdl   0/1       CrashLoopBackOff   9          22m
es-client-2882000496-zlh1q   1/1       Running            0          22m
es-data-0                    0/1       CrashLoopBackOff   9          22m
es-data-1                    1/1       Running            0          21m
es-data-2                    1/1       Running            0          13m
es-master-1484843648-4qlc1   1/1       Running            9          22m
es-master-1484843648-grq9c   1/1       Running            8          22m
es-master-1484843648-rpbtw   1/1       Running            0          22m
postgres-0                   1/1       Running            0          22m
rabbitmq-0                   1/1       Running            0          13m
rabbitmq-1                   1/1       Running            0          13m
rabbitmq-2                   1/1       Running            0          12m
redis-0                      1/1       Running            0          22m
web-2803407845-06333         1/1       Running            0          6m
web-2803407845-5z14f         1/1       Running            0          1m
web-2803407845-7mt2h         1/1       Running            0          1m
web-2803407845-hpg4v         1/1       Running            0          1m
web-2803407845-v77j0         1/1       Running            0          6m
worker-2792318356-vb1tf      1/1       Running            0          22m
```

some pods working, some does not. Going to crashloopbackoff because of network ready

**Comment by milla** [comment]
I have the same issue

**Comment by kilianc** [comment]
Same

**Comment by noam-fairfly** [comment]
Same

**Comment by ami-fairfly** [comment]
Happening to us on AWS as well

**Comment by whitecolor** [comment]
In my case, different errors including this one came with node failure and were caused by lack of resources on the cluster for existing workloads.

**Comment by nicky-lenaers** [comment]
@whitecolor This is inline with my initial encounters:

> I spent many hours trying to find the root cause of this problem. I ended up creating a test cluster without specifying the --machine-type flag, which in GKE defaults to n1-standard-1. As I rolled out my depoyment, I noticed the errors disappeared.

> In the above issue description, I specified the --machine-type=f1-micro, so my belief is that is has to do with insufficient memory and/or disk usage needed for e.g. image pulling.

Is more resources the only option here?

**Comment by spxtr** [comment]
Saw this on GKE with a noticeably sluggish `n1-standard-1`.

**Comment by whitecolor** [comment]
> Is more resources the only option here?

If in described cases the is an error is just **a consequence** and not the cause of node failure and the cause is a lack of memory/resources, then yes.

**Comment by chy168** [comment]
I encounter this issue ```n1-highmem-4```  on ```GKE```, too. It happened on one of nodes.
PS. the cluster has run for 90+ days. it didn't happen till yesterday.

**Comment by whitecolor** [comment]
It's just invasion of robots.

**Comment by guoshimin** [comment]
Also seeing this on GKE. Started happening to nodes that had been working fine up to that point.

**Comment by ThomasWo** [comment]
I've had this issue on GKE over the last week (most recently less than 30 minutes ago).  One pod will eat a bunch of resources in a burst, which seems to cause this issue on _existing_ pods.  I've been chasing my tail trying to figure it out, especially as resource limits on the offending pod only reduced the occurrence of the issue, didn't outright fixed it.

**Comment by lawrencejones** [comment]
Seeing this in GKE. The bug is definitely not gone!

/reopen

**Comment by agnnn** [comment]
Happening on GKE again.

**Comment by thedodd** [comment]
Also seeing this issue on GKE as of `1.10.2-gke.3`.

**Comment by frankh** [comment]
This just happened to me on AWS, cluster created using `kops`

Kubernetes version 1.10.3

**Comment by MrSaints** [comment]
This has been occurring sporadically for me since upgrading to 1.10.2 on GKE (running f1-micro instances).

**Comment by kszarek** [comment]
The issue also occurs on GKE 1.10.6-gke.2 with n1-standard-1 preemptible nodes

**Comment by arianitu** [comment]
I'm also running into this, is this just a resource issue, do I need to add more nodes?

**Comment by iArtur** [comment]
I am having the same problem. But in my case, the pods stayed stucked with ContainerCreating status. Changing the machine type does not work. Anyone has any clue?

**Comment by mandrean** [comment]
Same. GKE v1.10.6-gke.2 with n1-standard-1 preemtible nodes running COS.

```
  Warning  NetworkNotReady         14m                kubelet, gke-main-cluster-main-pool-33b017f6-q409  network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]
```

**Comment by pablojmarti** [comment]
I am also running into this same issue

**Comment by mkurzeja** [comment]
Same for me, started to happen quite often lately.

``` 
Type     Reason           Age                From                                             Message
  ----     ------           ----               ----                                             -------
  Warning  NetworkNotReady  49m (x3 over 49m)  kubelet, gke-project-default-pool-xxx  network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]
```


Running on n1-standard-2

**Comment by atulabhi** [comment]
I encounter this issue n1-standard-4 on GKE 1.8.7-gke.1, too. It happened on one of nodes.
PS. the cluster has run for  185d+ days. it didn't happen till yesterday.

**Comment by logTom** [comment]
Same here on gke Master-Version 1.11.2-gke.15:
network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]

**Comment by ptemmer** [comment]
Same here.

Using GKE cluster on 1.11.2-gke.18 using 3 preemptible n1-standard-8 instances vpc-native with alias IPs.
Being out of resources is not an option here; the cluster has in total 24cpu's with 90GB of memory. My deployment is using 7GB at most.

**Comment by gsf** [comment]
These errors may arise in 1.11.x on GKE due to this issue:
https://issuetracker.google.com/issues/119820482

**Comment by agolomoodysaada** [comment]
Experiencing this on Azure AKS v1.11.3
`network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR`

**Comment by orkenstein** [comment]
Same here

**Comment by nakabonne** [comment]
Also facing this issue on GKE:
```
version: 1.11.7-gke.12
machine type: f1-micro
image type: Ubuntu
num nodes: 3
disk size: 10GB
```

**Comment by curiouscod3** [comment]
Kubenet does not have netConfig. This is most likely due to lack of PodCIDR

**Comment by kigawas** [comment]
Same bug on GKE with kubernetes version 1.11.8-gke.6. Fixed after upgraded to 1.12.7-gke.10.

**Comment by rokerkony** [comment]
/reopen
it seems many more people have a problem with this

We have the same problem (`Kubenet does not have netConfig. This is most likely due to lack of PodCIDR`) on
- GKE with k8s version 1.11.8-gke.6

**Comment by sunnykrGupta** [comment]
```
Node version:    1.12.7-gke.10 
```
reason:NetworkPluginNotReady 
message:docker: network plugin is not ready: 
Kubenet does not have netConfig. This is most likely due to lack of PodCIDR

**Comment by AntoninBeaufort** [comment]
Same problem on 1.13.7-gke.8

**Comment by geekflyer** [comment]
@AntoninBeaufort I opened a corresponding issue on the Google/GCP issuetracker https://issuetracker.google.com/issues/138394882

**Comment by Sanjanare** [comment]
@geekflyer any luck ?

**Comment by ThomasWo** [comment]
@geekflyer that issue was closed as duplicate for a non-public issue.  Have you had any progress towards a fix?

**Comment by geekflyer** [comment]
@Sanjanare @ThomasWo Yes, 1.13.7-gke.15 and higher now contain a fix for this. It's also mentioned as a fix in the release notes: https://cloud.google.com/kubernetes-engine/docs/release-notes .

**Comment by amadav** [comment]
Any option/work-around for guys on AWS? Is it something related to the pod specification or kubelet configuration, that can we changed?

**Comment by iArtur** [comment]
For my expirience, this error is caused by a lack of internet connection on the cluster.

**Comment by Felihong** [comment]
Also seeing this on `1.14.9-gke.23`.

**Comment by fabio-rigato** [comment]
any news ? same error

**Comment by limbuu** [comment]
We are using v1.13.12-gke.25 kubernetes version in production and facing the same issue.

**Comment by vbatuev** [comment]
`1.15.11-gke.5 ` has this issue too.

**Comment by mitter1989** [comment]
facing this on 1.14.10-gke.36

**Comment by glittershark** [comment]
seeing this on 1.15.9-gke.24

**Comment by soygalla** [comment]
just happened to me on 1.15.12-gke.2

**Comment by glittershark** [comment]
wonder if that works

**Comment by glittershark** [comment]
hmm, guess not

**Comment by Ashwin-ks** [comment]
this happens in "1.14.10-gke.42" version as well.

**Comment by vcorr** [comment]
Just ran into this with 1.14.10-gke.42

**Comment by rafi-greenberg** [comment]
+1 on  1.14.10-gke.42

**Comment by engineerakki** [comment]
Getting this on 1.18.17-gke.700 on pods running on preemptive nodepools.
