### ISSUE TITLE
etcd v2 to v3 migration data verification

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/kubernetes#44276]
Reading etcd migration docs [1] and the script [2] that carries the migration/upgrade, I don't see anything verifying the v2 data are correctly migrated/transformed into v3 data. What is the proper way to do it? After checking both v2 and v3 data all the keys from v2 are present in v3, with all key values identical. Is it enough to check for every non-directory v2 key if it is present in v3 data and then compare v2 key value with the corresponding v3 key value? Anything else that needs to be checked?

[1] https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/admin/etcd_upgrade.md
[2] https://github.com/kubernetes/kubernetes/blob/master/cluster/images/etcd/attachlease/attachlease.go

**Comment by ingvagabund** [comment]
@mml @justinsb @xiang90 @hongchaodeng

**Comment by hongchaodeng** [comment]
As far as I konw, v2 and v3 should have the same set of keys (excl. dir in v2), and each key should have the same value, created revision, modified revision.

**Comment by roberthbailey** [comment]
@wojtek-t or @mml may be able to help answer this question.
