### ISSUE TITLE
kubectl describe node should show OIR requests/limits for Non-terminated Pods

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#44271]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):
HEAD

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
A pod requesting OIR(Opaque Integer Resource) is scheduled to a node, but there is no info about OIR for Non-terminated Pods.

```
Non-terminated Pods:		(1 in total)
  Namespace			Name				CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----				------------	----------	---------------	-------------
  default			rc-nginx-single1-f01k7		0 (0%)		0 (0%)		0 (0%)		0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  0 (0%)	0 (0%)		0 (0%)		0 (0%)
```

**What you expected to happen**:
It would be better if `kubectl describe node` shows OIR requests/limits for Non-terminated Pods, and OIR percentage in `Allocated resources`.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

cc @ConnorDoyle

**Comment by xiangpengzhao** [comment]
@ConnorDoyle I created three issues(#https://github.com/kubernetes/kubernetes/issues/44269, #https://github.com/kubernetes/kubernetes/issues/44270 and this one) associated with OIR. Is that OK to create them separately ? I think it would be clear to describe them in different issues. 

If these issues make sense, I will try to work on them. Of course, if you or other folks have already been working on them or having ideas about them, it would be better:)

**Comment by zhouhaibing089** [comment]
Bother to ask: what is OIR?

**Comment by xiangpengzhao** [comment]
@zhouhaibing089 Thanks for asking. I edited to be clear.

**Comment by xiangpengzhao** [comment]
GPU is also not shown currently. Have to determine if GPU and OIR are really needed to show for nonterminal pods.

**Comment by xiangpengzhao** [comment]
PR https://github.com/kubernetes/kubernetes/pull/46079 is waiting for approval.
