### ISSUE TITLE
feature request: server-side filtering of `kubectl logs`

### ISSUE THREAD

**Issue by majewsky** [kubernetes/kubernetes#44272]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): `logs grep label:area/kubectl`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

---

Container logs can get very long, especially if it's some sort of API that logs every request to it. When the connection between my workstation and the k8s cluster is slow or flaky, it can take a long time to do something like `kubectl logs $pod_name | grep ERROR`. Can we add some basic server-side filtering here? I would imagine something like `kubectl logs $pod_name --match-string=ERROR`, which only sends matching lines to the client, thus appearing much more snappy over a slow network.

**Comment by zhouhaibing089** [comment]
FYI: `kubectl logs --since=1h <pod>` and `kubectl logs --tail=20 <pod>` should help.

**Comment by majewsky** [comment]
Yes, it does. Unless you explicitly want to see logs from a longer timeframe, just filtered by some pattern. I expect that the next suggestion will be to use log shipping to some external system. We have one available as well, but I find that `kubectl logs` could still be a bit user-friendlier out of the box. I'll leave it to the maintainers to decide if they see this suggestion as in scope for K8s.
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 10.04.17, 17:25, zhouhaibing089 <notifications@github.com> schrieb:
FYI: kubectl logs --since=1h <pod> and kubectl logs --tail=20 <pod> should help.

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by dhempy** [comment]
+1

**Comment by machship-mm** [comment]
+1

**Comment by lavalamp** [comment]
/remove-sig api-machinery

The logs subresource is an escape hatch, not a thing api machinery encourages or supports. IMO it should be moved to another component, where anything desired could be done. I'm not in favor of adding this filtering to kube-apiserver. If someone wants to work on re-routing this call such that it doesn't pass through apiserver, I'm happy to brainstorm about the design.

I think many or most people, when they need this sort of thing, use a log aggregator, e.g. stackdriver on GKE.

I consider the /logs subresource to be owned by sig node (not sure if they agree):

/sig node

**Comment by alexvicegrab** [comment]
U stale, I still care
