### ISSUE TITLE
federation: alpha APIs should be disabled by default

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#44291]
Forked from https://github.com/kubernetes/kubernetes/issues/38593.

Now that we have flags to disable specific APIs (https://github.com/kubernetes/kubernetes/issues/38593), we should use them to disable alpha APIs by default.

cc @kubernetes/sig-federation-bugs

**Comment by quinton-hoole** [comment]
@nikhiljindal Are you still working on this?  If you're not likely to get to it in the forseeable future, please unassign yourself and we will try to find another owner.  Thanks.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#126.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
