### ISSUE TITLE
NFS mount point on both k8s node and pod remain after PVC is deleted

### ISSUE THREAD

**Issue by mtanino** [kubernetes/kubernetes#44297]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

- NFS
- Persistent Volume
- Persistent Volume Claim
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

$ kubectl.sh version
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.2099+dbcfdb378d3818-dirty", GitCommit:"dbcfdb378d3818652f5abdebfacb9908788cf559", GitTreeState:"dirty", BuildDate:"2017-04-05T20:42:55Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.2099+dbcfdb378d3818-dirty", GitCommit:"dbcfdb378d3818652f5abdebfacb9908788cf559", GitTreeState:"dirty", BuildDate:"2017-04-05T20:42:55Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- OS (e.g. from /etc/os-release): Fedora 25
- Kernel (e.g. uname -a): Linux localhost 4.9.10-200.fc25.x86_64 #1 SMP Wed Feb 15 23:28:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: hack/local-up-cluster.sh

**What happened**:

When I delete a PVC using NFS plugin which is still attached to a Pod,
 - The volume was scrubbed by recycler pod(if policy of PV is recycle)
 - The PVC was deleted and the status of PV was changed to "Available"
   (unbounded from the PVC)

However, after deleting PVC, the NFS mount point was still exist on the Kubernetes node which the Pod was deployed and also the mount point could be seen from inside the Pod.
And also if other Pod reuses the PV, then both old Pod and new Pod could access same NFS mount point.

Note: After deleting all Pods, the NFS mount point was unmounted from the K8s node.

**What you expected to happen**:
NFS mount point was unmounted from the K8s node and also a Pod when PVC is deleted.

**How to reproduce it** (as minimally and precisely as possible):
- Create a PV, then bound the PV to PVC.
- Create a Pod with bounded PVC
- Delete the PVC without deleting the Pod.

**Anything else we need to know**:

**Comment by mtanino** [comment]
CC @kubernetes/sig-storage-bugs

**Comment by saad-ali** [comment]
This is by design. The mount/unmount logic is controlled by creation/deletion of the pod not the PVC. Arguably we should prevent the deletion of a PVC that is referenced by an active pod. But not super high priority,

CC @kubernetes/sig-storage-bugs

**Comment by mtanino** [comment]
@saad-ali 

Thank you for your comment.

Yes, I saw the mount/unmount logic is issued during pod creation/deletion instead of during the PVC creation. I suppose mount should be called at Pod creation time but unmount would be called by both Pod deletion and PVC deletion. 
But I'm not sure if we can unmount a volume from online container. Is this the reason of current design?

Thanks.

**Comment by saad-ali** [comment]
Unmounting a volume before terminating the pod/container can cause bad things to happen (data loss!). So we want to avoid that. Therefore, I'd suggest preventing the deletion of a PVC that is referenced by an active pod as the only change, if any.

**Comment by mtanino** [comment]
@saad-ali 

I understand the policy behind of this design. In this case, I think preventing the deletion of a PVC is a appropriate solution to prevent this problem too.
Thank you for your quick response.

**Comment by jingxu97** [comment]
I created an issue to track this #45143

**Comment by jsafrane** [comment]
IMO this fixed by PVCProtection feature in 1.9.
/close

**Comment by mtanino** [comment]
@jsafrane 
Cool. I confirmed that PVC is prevented to delete if Pod is using it.
