### ISSUE TITLE
What is the correct pronunciation of Kubernetes in English?

### ISSUE THREAD

**Issue by Musikolo** [kubernetes/kubernetes#44308]
Hi guys,

This is a simple question, that for some reason, I was unable to find an answer for in the internet.

**What is the correct pronunciation of _Kubernetes_ in English?**

I think it would be nice to add it in your [README.md](https://github.com/kubernetes/kubernetes/blob/master/README.md) file too.

Thank you!

**Comment by kargakis** [comment]
@kubernetes/sig-contributor-experience-misc

**Comment by jessfraz** [comment]
I'm going to take a swing at this and say "koob-er-net-ees"

**Comment by idvoretskyi** [comment]
https://twitter.com/francesc/status/487412202932936704?lang=en

**Comment by jessfraz** [comment]
Winner is @campoy :P

**Comment by pigmej** [comment]
so according to that twitt it's `koo-ber-nay'-tace` ;-)

**Comment by campoy** [comment]
You can even hear a recording [here](http://ht.salemweb.net/bst/lexicons/greek-mp3/2942g.mp3)

**Comment by georginagi** [comment]
If one wants to be true to the Greek pronunciation Kubernetes or (κυβερνήτης)  sounds like ki-ver-ni:-tis. That recording is definitely not correct but I guess the community has already embraced the koob-er-net-ees pronunciation which sounds cool as well tbh

**Comment by Maverick-Crank-GRey** [comment]
Let's ask all involved people give their own voices. Literally ;)
https://forvo.com/word/kubernetes

Non-english speakers are welcome too.

**Comment by chaidas** [comment]
For whoever wants to show off linguistically:
The (simplified) phonetic pronunciation of the original Greek word (Κυβερνήτης) is **kee-ver-NEE-tees**

**Comment by x89** [comment]
@chaidas unfortunately I think nobody would have a clue what I was on about if I said that!

Interesting trivia though. :)

**Comment by Kitanotori** [comment]
Correct pronounciation for Kubernetes/κυβερνήτης:  
 https://forvo.com/search/%CE%BA%CF%85%CE%B2%CE%B5%CF%81%CE%BD%CE%AE%CF%84%CE%B7%CF%82/el/

I assume @chaidas is native Greek speaker, so would you say that's correct?

**Comment by chaidas** [comment]
@Kitanotori yup, that's exactly it!

**Comment by bgrant0607** [comment]
Jess is close. I think most people pronounce it koob-er-net-eez. Anyway, this is not the right repo. This belongs in kubernetes.github.io.

**Comment by yanhan569046480** [comment]
['Kubernetes]?

**Comment by yongfa365** [comment]
/kubɚ’nɛtɪs/

**Comment by yemanaung** [comment]
https://github.com/yemanaung
