### ISSUE TITLE
Pods with hostNetwork=true cannot be removed (and generate errors) when using CNI

### ISSUE THREAD

**Issue by readams** [kubernetes/kubernetes#44307]
**Kubernetes version** (use `kubectl version`):
1.6.2 built from 1.6 branch at 85b9c963272248c0b88d06664e88eb3ef1645dfb

**Environment**:
- **Cloud provider or hardware configuration**: bare metal
- **OS** (e.g. from /etc/os-release): Ubuntu xenial
- **Kernel** (e.g. `uname -a`): Linux fab7-compute-1 4.4.0-70-generic #91-Ubuntu SMP Wed Mar 22 12:47:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubeadm
- **Others**:

**What happened**:
When using CNI, kubelet gets confused when pods have hostNetwork=true.
Kubelet displays errors such as:

    StopPodSandbox "3fa9fc1247bed768521abe54f730a71a7412f17e8026975902e99f56ea4fd73c" from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "kube-proxy-cts6b_kube-system" network: CNI failed to retrieve network namespace path: Error: No such container: 3fa9fc1247bed768521abe54f730a71a7412f17e8026975902e99f56ea4fd73c

Deleting these pods will result in the pod hung in the Terminating state.

It appears that the tear down does not notice that CNI should not be invoked when hostNetwork=true but attempts to do so anyway.

**How to reproduce it** (as minimally and precisely as possible):
Create a pod, daemonset, or deployment with hostNetwork set to true in pod spec.

**Comment by yujuhong** [comment]
@freehan could you help verify if there is a bug? Thanks!

**Comment by freehan** [comment]
https://github.com/kubernetes/kubernetes/pull/43879 should be able to fix this

**Comment by readams** [comment]
I cherry picked the fix from #43879 to test and it does improve the situation but it looks like all pods are stuck in the terminating state not just host network pods and still are after the change.

    Apr 11 17:06:30 fab7-compute-2 kubelet[21409]: W0411 17:06:30.334637   21409 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "kube-dns-3913472980-7hbvp_kube-system": CNI failed to retrieve network namespace path: Cannot find network namespace for the terminated container "360c4c3fb9c55945834d58586feaa31517ee8cb8339fae1b9d9f882a518f3b52"
    Apr 11 17:06:30 fab7-compute-2 kubelet[21409]: E0411 17:06:30.334973   21409 kuberuntime_manager.go:844] PodSandboxStatus of sandbox "360c4c3fb9c55945834d58586feaa31517ee8cb8339fae1b9d9f882a518f3b52" for pod "kube-dns-3913472980-7hbvp_kube-system(edaa404e-1ef7-11e7-94d4-84b261c2790e)" error: rpc error: code = 2 desc = Cannot find network namespace for the terminated container "360c4c3fb9c55945834d58586feaa31517ee8cb8339fae1b9d9f882a518f3b52"
    Apr 11 17:06:30 fab7-compute-2 kubelet[21409]: E0411 17:06:30.335056   21409 generic.go:239] PLEG: Ignoring events for pod kube-dns-3913472980-7hbvp/kube-system: rpc error: code = 2 desc = Cannot find network namespace for the terminated container "360c4c3fb9c55945834d58586feaa31517ee8cb8339fae1b9d9f882a518f3b52"
    Apr 11 17:06:30 fab7-compute-2 kubelet[21409]: W0411 17:06:30.340054   21409 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "kube-dns-3913472980-7hbvp_kube-system": CNI failed to retrieve network namespace path: Cannot find network namespace for the terminated container "360c4c3fb9c55945834d58586feaa31517ee8cb8339fae1b9d9f882a518f3b52"
    Apr 11 17:06:30 fab7-compute-2 kubelet[21409]: E0411 17:06:30.340285   21409 kuberuntime_manager.go:844] PodSandboxStatus of sandbox "360c4c3fb9c55945834d58586feaa31517ee8cb8339fae1b9d9f882a518f3b52" for pod "kube-dns-3913472980-7hbvp_kube-system(edaa404e-1ef7-11e7-94d4-84b261c2790e)" error: rpc error: code = 2 desc = Cannot find network namespace for the terminated container "360c4c3fb9c55945834d58586feaa31517ee8cb8339fae1b9d9f882a518f3b52"

**Comment by dcbw** [comment]
@readams and I debugged some on slack and found this PR fixes the original error and allows his case to get further, but there are some volume bugs that were still blocking pod removal.

**Comment by readams** [comment]
I've tested this on 1.6.2 now and this appears to be fixed.

**Comment by bboreham** [comment]
We are getting reports of this still happening with 1.6.2 - why is kubelet even trying to run the CNI plugin on a hostNetwork pod?

**Comment by bboreham** [comment]
NetworkPlugin cni failed to teardown pod \"weave-net-cf1zw_kube-system\" network: unable to release IP address: dial tcp 127.0.0.1:6784: getsockopt: connection refused"


Kubernetes can't tear down the old pod because the network daemon isn't running, but the network daemon isn't running because Kubernetes won't restart the pod until it can tear down the old one, and the pod **is** the network daemon.

**Comment by freehan** [comment]
@bboreham 
We introduce the dockershim checkpointing in 1.6. For each pod sandbox, we maintain a checkpoint. If the containers are gone, then the information from the checkpoint will be used to tear down. However, we did not checkpoint if pod is in host network or not. Hence triggering network plugin for tear down for all. This assumes that the CNI plugin will not return any error if the input CNI_NETNS is empty. And cni plugin will just do a best effort idempotent clean up.

**Comment by Bregor** [comment]
@freehan example from @bboreham was run on k8s-1.6.2

**Comment by bboreham** [comment]
@freehan ok I understand why it got that way, but basically you force the plugin to never error on DEL. We have made this change now. 

To clean up something that was never allocated, in a condition when the data store is unavailable, is an extreme interpretation of "best effort".

**Comment by freehan** [comment]
@bboreham 
>  basically you force the plugin to never error on DEL

never error on DEL with emtpy NETNS. 

This is why I really want CNI spec to lock it down, so that runtimes and cni plugins have clear boundary. 

What I really want is idempotent ADD/DEL operations. On top of that, it would be great if CNI spec require plugins to only take CONTAINERID and network config for DEL. Otherwise, runtime has to maintain states which is not reliable. (For instance, CNI DEL succeed and runtime crashes. Runtime did not clean up checkpoint and retry DEL later.)

**Comment by readams** [comment]
The real solution to this would be to invert the CNI model completely.  Remove ADD/DEL operations and change to work on a sync model.  Runtime should keep a query-able representation of the current desired state and network plugins would be in charge of converging toward that state with a feedback loop.

**Comment by bboreham** [comment]
> never error on DEL with emtpy NETNS

Did you mean "never error on DEL _because of_ empty NETNS"? I would agree with that. But there are a host of errors where it doesn't seem right to swallow them and say "this is fine". For example:

- json is malformed
- containerid is blank
- kernel is returning EACCESS when I try to do something

**Comment by bboreham** [comment]
@readams that's orthogonal to the problem under discussion, which is that Kubernetes has not maintained enough of the desired state. (specifically the host-network flag)

**Comment by freehan** [comment]
> which is that Kubernetes has not maintained enough of the desired state. (specifically the host-network flag)

True. I am just saying that maintaining the desired state does not solve the whole problem. kubelet still triggers multiple DELs in some cases. The cni plugin has to return Success if there is nothing to delete. Otherwise, kubelet cannot proceed.

**Comment by bboreham** [comment]
This issue was never about multiple DELs. It is about hostNetwork pods.

**Comment by WIZARD-CXY** [comment]
tested using 1.6.4 still seeing this issue....

**Comment by dcbw** [comment]
https://github.com/kubernetes/kubernetes/pull/43879 got reverted, so this issue will be a problem again.

**Comment by dcbw** [comment]
> True. I am just saying that maintaining the desired state does not solve the whole problem. kubelet still triggers multiple DELs in some cases. The cni plugin has to return Success if there is nothing to delete. Otherwise, kubelet cannot proceed.

I'm of the opinion that kubelet should do the right thing and not call DEL when either (a) DEL is already in progress, or (b) DEL has already been called.  Kubelet has to be responsible for it's own operations, it can't punt this off to network plugins that really have nothing to do with kubelet.

*something* has to keep state.  Either that's kubelet, through the apiserver or the checkpoints, or it's the network plugins.  And not all network plugins are smart.  When we spin kubenet out to a CNI chain, what's going to keep state there, if network plugins need to keep state?  Nothing...  DEL should be best-effort, but we gotta make kubelet better behaved here too...

**Comment by thockin** [comment]
Any update on this?

**Comment by redbaron** [comment]
I believe those who have issued are running non CNI version 0.3.x compliant plugins. Spec clearly says:

> Plugins should generally complete a DEL action without error even if some resources are missing.

So it is very much likely not a Kubernetes problem

**Comment by thockin** [comment]
Should we close this?  @dcbw?

**Comment by bboreham** [comment]
@redbaron calling CNI on a hostNetwork pod is clearly wrong. It's quite a leap from there to "if some resources are missing".

**Comment by readams** [comment]
Originally what I was seeing was that it wouldn't actually even call CNI since it was hostNetwork, but it would get mad that it couldn't.  That is, it would try to find a network namespace to pass to CNI and fail there, so it didn't matter what the CNI plugin behavior was since it never actually invoked the plugin.  It just failed anyway.

**Comment by bowei** [comment]
@dcbw close if no longer relevant

**Comment by matchstick** [comment]
@dcbw We are getting close to 1.7 and this bug does not appear to be worth holding the release for. If you feel it is, please comment as such. Otherwise we can move it to next-candidate and then address in a patch release.

**Comment by caseydavenport** [comment]
IIUC, the outcome of this is that CNI plugins which implement older versions of the spec won't work with host-networked pods.  This is surely something we want to fix, but I don't think it's release blocking and can go into a 1.7 patch release.

**Comment by bboreham** [comment]
This is an issue with all released versions of 1.6; I don't understand why you would consider it a blocker to release 1.7.0.

**Comment by bowei** [comment]
@dchen1107  -- can we take this off of the 1.7.0 milestone?

**Comment by bboreham** [comment]
For the record, I believe the real problem was fixed by #47850
