### ISSUE TITLE
kubectl apply does not work with creating custom TPR object

### ISSUE THREAD

**Issue by metral** [kubernetes/kubernetes#44305]
**Kubernetes version** (use `kubectl version`): 1.5.5

**Environment**:
- **Cloud provider or hardware configuration**: Tectonic + AWS
- **OS** (e.g. from /etc/os-release): CoreOS Stable 1298.7.0
- **Kernel** (e.g. `uname -a`): 4.9.16-coreos-r1

**What happened**: `kubectl apply` against an instantiation of a custom TPR does not work. Attemping to do so reports:

`error: unable to decode "/tmp/cron2.yaml": no kind "CronTab" is registered for version "stable.example.com/v1"` 

(using the examples in https://kubernetes.io/docs/concepts/ecosystem/thirdpartyresource)

However, a `kubectl create` on the TPR object works. My hunch is that its an issue around defaulting / missing fields when using `kubectl apply` against TPR's.

**What you expected to happen**: For `kubectl apply` to work, not just `kubectl create`

**How to reproduce it** (as minimally and precisely as possible):

```
$ tee /tmp/cron1.yaml << EOF
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
metadata:
  name: cron-tab.stable.example.com
description: "A specification of a Pod to run on a cron style schedule"
versions:
- name: v1
EOF

$ tee /tmp/cron2.yaml << EOF
apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: my-new-cron-object
cronSpec: "* * * * /5"
image: my-awesome-cron-image
EOF

$ kubectl apply -f /tmp/cron1.yaml
thirdpartyresource "cron-tab.stable.example.com" created

$ kubectl apply -f /tmp/cron2.yaml
error: unable to decode "/tmp/cron2.yaml": no kind "CronTab" is registered for version "stable.example.com/v1"

however, when we try with kubectl create on the TPR object we get:

$ kubectl create -f /tmp/cron2.yaml
crontab "my-new-cron-object" created
```

**Anything else we need to know**:

Randomly, there are intervals of multiple seconds long (5-10+ ??) where the custom TPR doesn't exist in the system right away when trying to instantiate an object. This could just be due to syncing / how the system natively operates, but nevertheless, worth calling out.

**Comment by liggitt** [comment]
The 10 second delay is a known issue, tracked in https://github.com/kubernetes/features/issues/95

Apply is known not to work with TPR in 1.5. This was fixed in kubectl 1.6 in https://github.com/kubernetes/kubernetes/pull/40666
