### ISSUE TITLE
kube-proxy health check still return 200 OK even if endpoints don't exist on node anymore

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#44311]
One of the ESIPP e2e tests is currently broken on HEAD: https://k8s-testgrid.appspot.com/google-gce#gce-alpha-features

Failures all follow below pattern:
- Create an OnlyLocal Loadbalancer Service
- Create a backend pod on node1
- Test only node1 responses 200 OK for health check
- Delete this backend pod and create another pod on node2
- Test only node2 responses 200 OK for health check
- node1 still responses 200 OK --- test fails

Took a look at the codes, found the bug is that kube-proxy health check does not refresh local endpoints count when local endpoints don't exist anymore ([codes](https://github.com/kubernetes/kubernetes/blob/859b97b5512e2518e098cccfb1bdff93435e2cdf/pkg/proxy/healthcheck/healthcheck.go#L216-L229)).

@thockin @freehan

**Comment by thockin** [comment]
Thanks zihong.  I think I have it, simple case of insufficient testing.

**Comment by nleib** [comment]
in what version of Kubernetes was this fixed? I saw it in 1.6.1 and at 1.7 alpha

**Comment by MrHohn** [comment]
Hi @nleib, this fix is in v1.6.2 and v1.7.0-alpha.2.
