### ISSUE TITLE
Overriding Total Cpu capacity. I.e., support cpu overcommit

### ISSUE THREAD

**Issue by andyxning** [kubernetes/kubernetes#44328]
Currently, it seems that kubelet get cpu and memory capacity programtically and there is no way to override the it. This is difficult when we need to customize the cpu and memory capacity to do some test.

**Comment by andyxning** [comment]
It turns out that kubelet get node cpu and memory capacity from cadvisor. So, I have make a PR to [cadvisor #1638](https://github.com/google/cadvisor/pull/1638) adding this functionality.

After is has been merged in cadvisor. I will make a another PR to kubernetes to update cadvisor dependency. :)

**Comment by dashpole** [comment]
Can you give me an example of what you are trying to test?

**Comment by andyxning** [comment]
@dashpole 

We have a new CPU series(40 cores[hyperthread]) and before take it to production widely we want to test its performance under production load. So we want to add it to a Kubernetes cluster to let it run some service. However, normally kubelet will register `CPU allocatable` with `CPU capacit(runtime.NumCPU) - kube reserved - system reserved). With this settings, we can just make node load to about 10 with 70% CPU has been allocated to user pods. 

In order to stress the node further, we just want to overcommit the CPU resource, for example, make a node with 40cores(hyperthread) registered with 80cores in order to stress the cpu to test its performance.

**Comment by dashpole** [comment]
I believe the current defaults for kube reserved and system reserved are 0, so CPU allocatable should be the entire capacity of the node.  If you want to schedule more pods on the node to increase utilization and stress the node, you could run pods that do not have CPU requests or limits set, allowing you to schedule as many such pods as you want to the node.  You should be able to easily achieve 100% utilization this way without faking the cpu capacity.  Of course, this could have detrimental effects on the kubelet, as it will be under CPU pressure.  But thats the intention, I guess.

**Comment by andyxning** [comment]
As just for stress test about CPU, i agree with your method as it's more easy and straightforward. :)
Besides setting not CPU requests and limits for user pod, we still need to add more weight for that pod to get more traffic.

We have a Paas system to do service upgrade and setting CPU request and limit. It will be difficult for us to maintain the cluster with a unified way by utilizing @dashpole 's method wi . 

With adding `cpu_capacity_override` and `memory_capacity_override`, i can only think about one reason to do so. Maybe we need it in some other situations. :)

**Comment by Random-Liu** [comment]
I also agree that what @dashpole suggested is the best solution now.

Overriding the capacity may be useful in some other use cases, but it seems too tricky to add these flags just for overcommitting test.

A better abstraction is to add `overcommit_factor` in NodeSpec. But I don't think we could do that anytime soon.

**Comment by hectorj2f** [comment]
We are facing a kind of related issue where the kubelet isn't cgroup aware. For us, the memory and cpu capacities are not realistic. The Kubelet is running in a specific cgroup with a mem/cpu limitation. However, the kubelet's memory capacity is the one available in the host, and not the specified in the cgroup where it runs. 

Do you know if there is any way of enforcing the capacity seen by the kubelet ?

**Comment by andyxning** [comment]
> Do you know if there is any way of enforcing the capacity seen by the kubelet ?

Data is extracted from cAdvisor. So i think it is cAdvisor that extract node capacity from `/proc` or something else which is irrelevant with cgroups. But as for your use case, i think it is right that kubelet post node capacity of node to apiserver.

**Comment by andyxning** [comment]
> A better abstraction is to add overcommit_factor in NodeSpec. But I don't think we could do that anytime soon.

@Random-Liu How about we add a `cpu_overcommit_factor` to cAdvisor. It is the source of the authoritative data. Kubelet just read the data and update it to the node spec. As for now, it is only make sense to overcommit cpu which is a compresable resource compared with memory.

/cc @dashpole @kubernetes/sig-node-pr-reviews

**Comment by dashpole** [comment]
How would this work with CPU pinning?  I am also not entirely sure if the current way we do cpu cgroup management would function properly with a mocked number of CPU cores.
It is easy to overcommit nodes with the current primitives we have available.  Setting request.CPU less than expected CPU usage for a pod allows over-committing a node's CPU without any of these changes.
How is the above insufficient for your use-case?

**Comment by andyxning** [comment]
@dashpole Thanks for your explaination. 
> Setting request.CPU less than expected CPU usage for a pod allows over-committing a node's CPU without any of these changes.

If we want to make the pod's qos guranteed, this seems not an option.

> I am also not entirely sure if the current way we do cpu cgroup management would function properly with a mocked number of CPU cores.

Any clues kubelet or cpu cgroup management does not work with a mocked number of CPU cores.

**Comment by dashpole** [comment]
> If we want to make the pod's qos guranteed, this seems not an option.

I think this is at the heart of the issue.  Pods cannot be both Guaranteed, and overcommitted.  The very nature of being overcommitted means that if all pods use up to their limits, they would not all fit.  If this is the case, then they cannot be "guaranteed" access to those resources.

I agree that the current mechanism to overcommit pods is not currently convenient.  For example, I could overcommit all of my pods by lowering each of their requests by 30%.  However, if I want to lower them by another 10%, then I have to change all of their requests again.  One possible implementation of something like `cpu_allocation_ratio` in kubernetes would simply set `cpu_request=cpu_allocation_ratio * expected_cpu_usage`.  You may be able to implement this with [initializers](https://kubernetes.io/docs/admin/extensible-admission-controllers/#what-are-initializers), by setting only `limits` on your pods, and having the initializer fill in requests as some fraction of those limits.

**Comment by andyxning** [comment]
@dashpole Thanks for your suggestion. Will investigate initializers later.

**Comment by haosdent** [comment]
@andyxning I submit a draft pull request. No sure if it match your requirements or not. Could you help to try it?

**Comment by julienlau** [comment]
Hi,

I think this issue is still relevant ! please /reopen


This would be very helpful to improve cpu utilisation on Kubernetes cluster used as compute plane for example for Spark.
As explained in this Spark ticket, with Spark there is an assumption made that when you request N cores for parallel compute, that N cores would be 100% used.
In this way, Spark automatically cpu limits and cpu requests equal to N.
This is very inefficient, since most workload also do IO and are using effectively not more than 50% cpu usage.

https://issues.apache.org/jira/browse/SPARK-32744

From my experience as consultant on numerous projects, I see a lot of Kubernetes cluster used as Spark backend having really low CPU / memory real usage.

If we could set overcommit factors for memory and cpu on nodes spec that would be a very elegant and convenient way to improve resources usage.
