### ISSUE TITLE
e2e tests are failing on s390x

### ISSUE THREAD

**Issue by gajju26** [kubernetes/kubernetes#44325]
**Is this a request for help?**: yes

**What keywords did you search in Kubernetes issues before filing this one?** :  How to run e2e tests on a platform other than AMD64 

---

**Kubernetes version** (use `kubectl version`): 1.6.1

**Environment**: 
- **Cloud provider or hardware configuration**: NA
- **OS** (e.g. from /etc/os-release):  "Ubuntu" "16.04.1 LTS (Xenial Xerus)"
- **Kernel** (e.g. `uname -a`):  s390x GNU/Linux
- **Install tools**: NA
- **Others**: NA

**What happened**:   I have to run e2e tests on s390x platform 

**What you expected to happen**:  For implementing CI on s390x I was trying to run e2e tests on s390x platform. But most of the tests are failing due to Kubernetes download docker images of AMD64 architecture. Is there any flag or configuration file where I can make a change and run the e2e tests for s390x?

**Comment by mkumatag** [comment]
you should watch this - https://github.com/kubernetes/features/issues/288

**Comment by gajju26** [comment]
Hi Manjunath,

I have gone through the link that you have mentioned. My understanding is described below:
As per the link, it is expected that the e2e tests will fail for the architectures arm, arm64, ppc64le, s390x and windows because required docker test images are not available yet due to lack of manifest list. 
If my understanding is right then how other architecture are trying to implement Kubernetes CI/running e2e tests on their respective architectures?

**Comment by mkumatag** [comment]
It fails because we haven't ported those test images for any other platform other than amd64.. Work on progress to make those tests images for all other architecture like arm, arm64, ppc64le, s390x..

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc

**Comment by duane-ibm** [comment]
@mkumatag I am looking to implement a CI for Kubernetes on s390x. Are the test images for s390x available and will the e2e tests now pass on s390x?

**Comment by mkumatag** [comment]
@duane-ibm, not all test images are ported for s390x platform. You can check all ported images for s390x platform [here](https://console.cloud.google.com/gcr/images/kubernetes-e2e-test-images/GLOBAL) with s390x postfix and you can work on porting missing images. The reason behind not porting them all is because I faced issues while building those images with qemu static binary.

**Comment by mkumatag** [comment]
@duane-ibm any work is happening with respect to port missing e2e test images?

**Comment by rajula96reddy** [comment]
Hey! I was wondering, what is the status on building these missing images for s390x?

**Comment by duane-ibm** [comment]
Hey, I did not try the e2e tests.
Although I tried to execute the bootstrap.py jenkins script to run pull-kubernetes-unit jenkins job.
The images required for this job were as below:
```
- gcr.io/google-containers/pause:2.0
- gcr.io/google-containers/pause:latest
- gcr.io/google-containers/nginx:test-cmd
- gcr.io/google-containers/perl
- gcr.io/google_containers/serve_hostname
- gcr.io/k8s-testimages/kubekins-test:1.11
- gcr.io/google_samples/gb-frontend:v3
- gcr.io/google_samples/gb-frontend:v4
- gcr.io/google-containers/nginx:1.7.9
- gcr.io/google_containers/nginx-slim:0.7
- gcr.io/google_containers/nginx-slim:0.8
```
