### ISSUE TITLE
clear up confusion between labels and taints

### ISSUE THREAD

**Issue by jeroenjacobs1205** [kubernetes/kubernetes#44335]
I don't quite understand the difference between taints and labels in k8s. For example: the kubeadm says:

> 
> By default, your cluster will not schedule pods on the master for security reasons. If you want to be able to schedule pods on the master, e.g. a single-machine Kubernetes cluster for development, run:
> kubectl taint nodes --all node-role.kubernetes.io/master-
> 

however, when I do a "kubectl describe node <master>", I don't see that taint

> Labels:                 beta.kubernetes.io/arch=amd64
>                        beta.kubernetes.io/os=linux
>                        kubernetes.io/hostname=dev-kubeadm-002
>                        node-role.kubernetes.io/master=

So taints is the same as labels, or not? 

This is the default master node setup by kubeadm btw, running 1.6.1

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc for the missing taints from `kubectl describe`

@jeroenjacobs1205 taints is an actual field in the node spec as opposed to label which is included in the metadata of every Kube object. Read more about taints in https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#taints-and-tolerations-beta-feature

**Comment by jeroenjacobs1205** [comment]
@kargakis : My confusion originates from the fact that the kubeadm mentions it's a taint, while "describe" lists it as a label. Does that mean the kubeadm documentation is incorrect?

**Comment by kargakis** [comment]
@jeroenjacobs1205 the node has probably both, a label and a taint with the same key. You can confirm by inspecting the output of `kubectl get no NAME -o yaml`

**Comment by adohe** [comment]
this would be not correct, taint != labels.

**Comment by xiaoping378** [comment]
```
kubectl get node <your_node_name> -o template --template={{.spec.taints}}
```
show the taints filed
