### ISSUE TITLE
Can't access services in k8s 1.6.1

### ISSUE THREAD

**Issue by Demonsthere** [kubernetes/kubernetes#44334]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
yes, but also a possible bug

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
nslookup, service

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Cloud provider or hardware configuration**: Private Datacenter, VMs made by OpenNebula
- **OS** (e.g. from /etc/os-release): `NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial`
- **Kernel** (e.g. `uname -a`): `Linux qubu-master 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**: kubeadm
- **Others**:

**What happened**:
After installing a clean cluster with kubeadm and spawning a test deployment and exposing it, i can curl only to the pods that are running on the master node (from which i curl). I can't access the pods from slaves. 
Moreover I can see the problem with nslookup: 
```bash
root@qubu-master:~# kubectl exec -ti busybox-3620006311-d7r9b -- nslookup kubernetes.default
Server:    10.96.0.10
Address 1: 10.96.0.10

nslookup: can't resolve 'kubernetes.default'
```

However, the dns deployment is running fine, without any error or warning in the logs. 
As my SDN i am using Weave, with the current 1.6 settings from 
https://git.io/weave-kube-1.6

**What you expected to happen**:
I am able to access my pods as in the 1.5 releases

**How to reproduce it** (as minimally and precisely as possible):

```bash
kubectl run whoami --image=emilevauge/whoami --replicas=5
kubectl expose deploy whoami --port=80 --type=LoadBalancer
```
**Anything else we need to know**:
I suspect that the reason is in the RBAC, and that I am not allowed to access the pods from my other machine (however i can run and exec into puds there). But I have no idea how to debug the issue if it is related to RBAC.

**Comment by liggitt** [comment]
can you include the logs from the kube-dns and weave pods?

**Comment by CodeJuan** [comment]
So

**Comment by Demonsthere** [comment]
Update:
Thanks for the interest, but i think i have managed to fix it. The problem was, that for the 1.6.0 release and the deadlock in `kubeadm init` i have removed the `Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"` line from the systemd config. After restoring it in 1.6.1 it works well.

**Comment by liggitt** [comment]
Great, thanks

**Comment by bamb00** [comment]
Is that normal? removing the "Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"" in order to access to the pods after installing 1.6.1.

I've also run into this problem accessing the pods usingkubectl.
