### ISSUE TITLE
'object does not implement the List interfaces' when logging readiness probe failure

### ISSUE THREAD

**Issue by readams** [kubernetes/kubernetes#44348]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
1.6 tree at 85b9c963272248c0b88d06664e88eb3ef1645dfb

**Environment**:
- **Cloud provider or hardware configuration**: bare metal
- **OS** (e.g. from /etc/os-release): Ubuntu xenial
- **Kernel** (e.g. `uname -a`): Linux fab7-compute-2 4.4.0-70-generic #91-Ubuntu SMP Wed Mar 22 12:47:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubeadm

**What happened**:
This gets logged

    event.go:259] Could not construct reference to: '&v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-dns-3913472980-72wvm", UID:"cac03227-1edc-11e7-ac00-84b261c2790e", APIVersion:"v1", ResourceVersion:"554", FieldPath:"spec.containers{kubedns}"}' due to: 'object does not implement the List interfaces'. Will not report event: 'Warning' 'Unhealthy' 'Readiness probe failed: Get http://10.1.0.130:8081/readiness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)'

**What you expected to happen**:
Should log correctly

**How to reproduce it** (as minimally and precisely as possible):
Create pod that fails readiness probe

**Comment by ncdc** [comment]
cc @deads2k, not sure if this is related to your changes

**Comment by deads2k** [comment]
> cc @deads2k, not sure if this is related to your changes

I don't think so.  I didn't change the identification of `ListAccessor` or `Accessor` which are being used there.

**Comment by malagant** [comment]
I always get the same message. What does this exactly mean?

**Comment by dimpavloff** [comment]
We're also seeing this on 1.6.1
```Apr 20 09:24:10 ip-<redacted>[1236]: E0420 09:24:10.090956    1236 event.go:259] Could not construct reference to: '&v1.ObjectReference{Kind:"Pod", Namespace:"dev", Name:"<redacted>", UID:"e90b671c-25aa-11e7-a503-02dce56162cb", APIVersion:"v1", ResourceVersion:"97559141", FieldPath:"spec.containers{<redacted>}"}' due to: 'object does not implement the List interfaces'. Will not report event: 'Warning' 'Unhealthy' 'Readiness probe failed: HTTP probe failed with statuscode: 500'
```

**Comment by alkar** [comment]
Seeing this in `1.6.2` as well

**Comment by nsidhaye** [comment]
How we can come to know which release this is fixed? 

I am using 1.6.6 still I can see this issue.

Thanks in Advance.
