### ISSUE TITLE
make logs -t and alias for logs --tail ... and allow no argument

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#44347]
Most of the time I use logs I use `--tail 1 -f` to see what is going on now and not get spammed by everything that ever happened ... it would be great to not have to spell that out and also have a default argument of 10 so I could do: `kubectl logs foo -tf`

**Comment by kargakis** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by adohe** [comment]
@grosser one point I want to clarify, default argument of 10 is only used when a selector is specified, when you use logs with single pod(or single container), the default value may not be ok.

**Comment by adohe** [comment]
also please take a look at [docker logs](https://docs.docker.com/engine/reference/commandline/logs/).

**Comment by grosser** [comment]
"--timestamps, -t" ... so to follow docker it should be a shorthand for
timestamps :(
