### ISSUE TITLE
ci-kubernetes-e2e-gce-federation-serial suite is broken 

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#44354]
This suite is broken just because of one test - `[k8s.io] Federation apiserver [Feature:Federation] Cluster objects [Serial] should be created and deleted successfully`. This is broken because we join the clusters to federation while bringing up e2e federation control plane and we try to repeat the same operation in the test. 

The simplest fix is to use a different name for the cluster object.

**Comment by fejta** [comment]
https://github.com/kubernetes/test-infra/issues/2453

**Comment by spiffxp** [comment]
/remove-priority P1
/priority important-longterm
(I'm not actually sure this is the right priority, just trying to remove the old priority/PN labels)

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#127.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
