### ISSUE TITLE
Validation should reject empty TopologyKey when !utilfeature.DefaultFeatureGate.Enabled(features.AffinityInAnnotations) 

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#44360]
Validation should reject empty TopologyKey when !utilfeature.DefaultFeatureGate.Enabled(features.AffinityInAnnotations) 

We overlooked this in #41195

Relevant validation section to modify is here:
https://github.com/kubernetes/kubernetes/blob/98a4c6ba7f879a6c608575291566c910c0b50ef4/pkg/api/validation/validation.go#L2222

Note that the current "allowEmptyTopologyKey" in the validation code is totally unrelated, and is enforcing that you can only have empty topology key with preferred scheduling, not required scheduling. We shouldn't change that.

(https://github.com/kubernetes/kubernetes/blob/e58d3dbf062e9e75c3517a26310fbfc98cf9167c/plugin/pkg/scheduler/algorithm/priorities/util/topologies.go#L81 is the function where the topologyKey is used)

@aveshagarwal do you think you could fix this? Should be easy.

cc/ @wojtek-t  @kubernetes/sig-scheduling-bugs

**Comment by aveshagarwal** [comment]
@davidopp sure. will look into it soon.
