### ISSUE TITLE
kubectl exec command hangs on exit if command starts a background process

### ISSUE THREAD

**Issue by bw2** [kubernetes/kubernetes#44371]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

kubectl exec hangs background

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):  MacOSX v10.11.6 (15G1421)
- **Kernel** (e.g. `uname -a`): Darwin wmd2b-dec 15.6.0 Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64 x86_64
- **Install tools**: 
- **Others**:

**What happened**:

I have a script that contains one line:
```
sleep 1000 & 
```
and I run it with `kubectl exec <pod> -- /my-script.sh`

**What you expected to happen**:

I was expecting it to exit immediately since the sleep command runs in the background, but instead it hangs until the sleep command exits. 
It doesn't matter whether I put #!/bin/bash or #!/bin/sh at the top.

**How to reproduce it** (as minimally and precisely as possible):

Also, I can reproduce this issue by just running

`kubectl exec -it <pod> bash`
and then manually running `sleep 1000 & ` (which runs in the background as expected).  
However, if I then run `exit`, it hangs.  
If I kill the sleep process before exiting, it exits without hanging.
Also, if I instead run `nohup sleep 1000 & `, it also exits without hanging.

**Comment by bw2** [comment]
Looking into this further, the current behavior makes sense, but is confusing because I am able to launch several background commands in my entrpoint.sh script, and can see their output in kubectl logs.  I'd like to be able to start a script using kubectl exec that acts similarly to docker CMD or ENTRYPOINT, but I guess it makes sense that the entrypoint shell gets special treatment (in terms of its stdout being connected to docker logs, etc.). 

Assuming I'm understanding this correctly, would it be possible / make sense for `kubectl exec` commands to be executed using the same shell as was started for the ENTRYPOINT command ? 
(that way the background process' behavior would be the same). 
Alternatively, is there some way to after-the-fact "reparent" commands started with exec so that they become children of that original shell?

**Comment by liggitt** [comment]
cc @ncdc

**Comment by ncdc** [comment]
I see this exact same behavior with `docker run` and `docker exec`. I don't know there's anything we can do here.

cc @mrunalp any ideas?

**Comment by mrunalp** [comment]
Can you try with nohup sleep &

**Comment by spiffxp** [comment]
/sig cli
/sig api-machinery
I'm not sure which sig is more appropriate to own here

**Comment by ncdc** [comment]
Assuming the `nohup` suggestions works, I propose we close this. @bw2 have you been able to try nohupping?

**Comment by bw2** [comment]
nohup does work. Thanks.

**Comment by shrey-rajvanshi** [comment]
nohup doesn't work for me. Even with `nohup sleep 1000 &`, kubectl exec hangs, waiting for the background process to complete. Any other ideas?

**Comment by tanglrHello** [comment]
nohup doens't work for me, but redirect stdout and stderr for the background process worked.
That is:
sleep 3 >/dev/null 2>&1 &
