### ISSUE TITLE
Reduce memory allocation at runtime of scheduler cache

### ISSUE THREAD

**Issue by HardySimpson** [kubernetes/kubernetes#44383]
Just a simple optimization, 

```
func (cache *schedulerCache) List(selector labels.Selector) ([]*v1.Pod, error) {
	cache.mu.Lock()
	defer cache.mu.Unlock()
	var pods []*v1.Pod
	for _, info := range cache.nodes {
		for _, pod := range info.pods {
			if selector.Matches(labels.Set(pod.Labels)) {
				pods = append(pods, pod)
			}
		}
	}
	return pods, nil
}
```

when Pod's number is large, the append will cause many memory allocation, to reduce it I raise a PR

https://github.com/kubernetes/kubernetes/pull/44261

**Comment by HardySimpson** [comment]
@kubernetes/sig-scalability-pr-reviews

**Comment by jayunit100** [comment]
Thanks for noting this possible improvement, please see  https://github.com/kubernetes/community/blob/master/contributors/devel/development.md#is-this-a-performance-improvement-  thanks !
