### ISSUE TITLE
[Federation] How should kubefed handle cluster access

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/kubernetes#44384]
This issue is a follow up to https://github.com/kubernetes/kubernetes/issues/41267
Perhaps an umbrella issue is needed to group all the related ones.

Prior to release 1.6 kubefed used to upload the credentials provided by the user in kubeconfig for all operations. With issue https://github.com/kubernetes/kubernetes/issues/41267, the intention was to use service accounts (possibly different ones) to access clusters and also for the communication within federation control plane(controller manager to api server).
Now there are multiple questions that need answers (and solutions to possible problems).

1. Who sets up these service accounts?
	We tried setting this up automatically while bootstrapping control place in kubefed init (https://github.com/kubernetes/kubernetes/pull/40392), but ran into problems with older clusters which do not use the authorizer as RBAC.
	We then further tried to guess if the cluster uses the RBAC authorizer by checking if the cluster exposes the RBAC api and tried using the right API version also, but again ran into problems (https://github.com/kubernetes/kubernetes/issues/42559), because the cluster might not be using the RBAC as the authorizer plugin using ```--authorization-mode=RBAC```.
	Apperantly, and for genuine security reasons, there is no direct way of guessing what authorizer is being used by the cluster.
2. Does federation handle the cluster skew and to what extent?
	Apart from the previous questions/problems, there is an added problem of older clusters. RBAC as authorizer was itself introduced in 1.4. Further service account as a feature might itself not be there in even older clusters.
	Do we need to support a vast range of cluster version skew (which might not be a good idea). If that is the case, we might need to choose using credentials as is, or through service accounts (depending on availability of features).
3. As a security scenario, the admin user (who is bootstrapping control plane and registering clusters) might want to use different credentials then the one he is accessing the clusters with currently (mostly admin).
	Kubefed uploaded the same credentials as in the kubeconfig under use to access the clusters, (as of now for joining clusters).

Based on discussion with @liggitt, @madhusudancs and @perotinus, the suggestions to handle some of the above problems are as below.

1. Kubefed cannot guess which authorizer is used. It however can have a default behaviour and some additional paths with users.

- Assumes the clusters to be using RBAC, and if no other detail (as suggested next with  ```--use-service-account```) is specified, it tries to set up the right service account and needed roles as a default. We also suggest RBAC as the preferred usage in documentation.
- Also provides an alternative option to use the pre-setup service account to be used (additional argument --use-service-account) in both init and join, which can override this behaviour. If the user intends to use a different authoriser then RBAC, they will need to use this mechanism.
- As an alternative path, user can override the default behaviour to using just the access credentials (for example by specifying ```--use-credentials-only```) (and ```--use-credential-kubeconfig=``` if a different set of access credentials need to be uploaded).
	
Which option to use as the default path, is open for suggestions.

2. As listed in 1, its best to keep the cluster skew to as less as possible, there are bigger problems to address in this scope and discussed here https://github.com/kubernetes/kubernetes/issues/44160.

3. As listed in the 3rd option in the solution to 1 above.

Some additional pointers are:

- Kubefed can still discover the RBAC api versions when using the path of creating SA and roles.
- In case some advanced features are needed k8s exposes access review apis https://kubernetes.io/docs/admin/authorization/#checking-api-access

**Comment by irfanurrehman** [comment]
cc @kubernetes/sig-federation-misc @kubernetes/sig-federation-bugs

**Comment by irfanurrehman** [comment]
@madhusudancs @perotinus, please add if I have missed something.

**Comment by perotinus** [comment]
That's a great summary. Thanks @irfanurrehman! The only thing I can think to add is that adding support for checking API access for the credentials is a step above nice-to-have, since we can't guarantee that the RBAC credentials (or the user-provided credentials, for that matter) will work properly, and having a just-created Federation not work because the credentials are invalid is a pretty poor experience if you have to debug it yourself.

I'd assume that the default path would be to attempt to create a service account and configure it with RBAC.

**Comment by madhusudancs** [comment]
@irfanurrehman thanks for the great summary. I think service account with right RBAC roles should be the default path.

I don't think RBAC API version discovery is required. We should just check for RBAC v1beta1 and if it doesn't exist we should fail the pre-flight check.

Also, I am not entirely sure if it is worth supporting both `--use-credentials-only` and `--use-credential-kubeconfig=`. Latter should be sufficient and we can call it `--use-credentials=`. What do you think?

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#210.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
