### ISSUE TITLE
Feature Request for launching a kubemark cluster onto a pre-existing kubernetes cluster

### ISSUE THREAD

**Issue by rthallisey** [kubernetes/kubernetes#44393]
After setting up my infrastructure and deploying Kubernetes on it, I would like to deploy a kubemark cluster on my pre-existing Kubernetes cluster for scale testing.

The goal is to use the existing kubemark start scripts, but to add an new provider that fills in the required fields for kubemark to land on the pre-existing cluster.

**Comment by jayunit100** [comment]
Specifically we want this for doing things like running kubemark against openshift, and so on.  CC @smarterclayton @jeremyeder .

**Comment by kargakis** [comment]
@kubernetes/sig-testing-feature-requests
