### ISSUE TITLE
kubernetes-worker Juju charm: "pause" action can't succeed in default configuration

### ISSUE THREAD

**Issue by fghaas** [kubernetes/kubernetes#44392]
**Is this a request for help?**
No

**What keywords did you search in Kubernetes issues before filing this one?** 
`kubernetes-worker` `charm`

**Is this a BUG REPORT or FEATURE REQUEST?** 
Bug Report

**Kubernetes version**
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-23T22:48:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-23T22:28:16Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Libvirt VMs
- **OS**: Ubuntu 16.04
- **Kernel**: 4.4.0-21-generic
- **Install tools**: Juju 2.1.2-xenial-amd64, `cs:~containers/kubernetes-worker-14`

**What happened**:
`juju run-action kubernetes-worker/0 pause` leads to immediate action failure. This action runs `kubectl drain` for the node that `kubernetes-worker/0` is deployed to, which is bound to fail:
```
kubectl drain daisy
node "daisy" cordoned
error: pods with local storage (use --delete-local-data to override): monitoring-influxdb-grafana-v4-6218d
```
This leaves the node in a cordoned, undrained state.

**What you expected to happen**:
One of three options:
- The `pause` action should come with a parameter enabling `kubectl drain --delete-local-data`, _or_
- CDK should not be deploying `monitoring-influxdb-grafana` (if other options are available), _or_
- CDK should automatically reconfigure `monitoring-influxdb-grafana` to run off a Ceph RBD volume if `kubernetes-master` is linked to `ceph-mon`.

**How to reproduce it** (as minimally and precisely as possible):
- Deploy CDK.
- Run `juju run-action kubernetes-worker/0 pause` and note the action UUID
- Run `juju show-action-status` on that UUID
- Observe the action's failed state:
```
actions:
- id: ac1875a0-319b-47c1-8f18-52b02b313bb2
  status: failed
  unit: kubernetes-worker/0
```

**Comment by chuckbutler** [comment]
@fghaas Good find on this one. I had taken a stab at this before but i've since lost the PR and didn't track it to completion. 

I'll circle back on this one this week and add a force option to pass --delete-local-data for the immediate resolve, and evaluate the suggestions for a more robust solution moving forward.

**Comment by fghaas** [comment]
@chuckbutler Got it, thanks for the update!

**Comment by chuckbutler** [comment]
@fghaas fix is committed and will go with our next release, projected next Thursday. It won't succeed by default as wildly deleting data is something the user should be concerned about and make the call. But the charm action now has the appropriate flags and better-documented action description.

```
juju actions --format=yaml --schema kubernetes-worker
```

**Comment by fghaas** [comment]
@chuckbutler Thanks! And I do agree about the cautious default.
