### ISSUE TITLE
hack/e2e.go -build hangs with older versions of docker

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#4439]
When running hack/e2e.go -build with docker 1.0.1 installed, the calls to "docker run" hang waiting for stdin to be closed. Pressing enter or ^D will allow the scripts to continue. It seems this hang started occurring after #4226.

After upgrading to docker 1.5.0, the scripts no longer hang.

Should there be a version check in hack/e2e.go (or somewhere else reasonable, maybe build/common.sh) to verify that the docker installation is new enough? (What does "new enough" even mean?)

**Comment by dims** [comment]
@ixdy Is there still something we need to do? (since the issue is very old)

**Comment by ixdy** [comment]
I think supporting versions of docker that old is pretty unrealistic. :)
