### ISSUE TITLE
kubectl rollout status does not work well with affinity/pending pods

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#44395]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: baremetal
- **OS** (e.g. from /etc/os-release): centos7/ol7
- **Kernel** (e.g. `uname -a`): depends on box
- **Install tools**: custom
- **Others**:

**What happened**:

I have a pod with the following anti-affinity rule
```
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: k8s-app
                operator: In
                values:
                - kube-controller-manager
            topologyKey: kubernetes.io/hostname
```

I have 3 nodes where this pod can deploy to and run 3 replicas. So 1 pod per node. 

When i first applied the change to the manifest the current state of the cluster was:
```
kb get po -l k8s-app=kube-controller-manager -o wide
NAME                                       READY     STATUS        RESTARTS   AGE       IP         
kube-controller-manager-1756656909-36srf   1/1       Running       0          12d       10.5.57.4   
kube-controller-manager-1756656909-rrkvj   0/1       Terminating   0          12d       <none>    
kube-controller-manager-1756656909-wdmkg   1/1       Running       0          12d       10.5.62.4 
kube-controller-manager-889084721-drbkh    0/1       Pending       0          9s        <none>
kube-controller-manager-889084721-sn6xg    0/1       Pending       0          9s        <none>
```

Which is what I expected. The rollout status at the same time though showed: 
```
kb rollout status deploy/kube-controller-manager
Waiting for rollout to finish: 2 out of 3 new replicas have been updated...
```

2 out of the 3 replicas had not been updated successfully. They were still in a pending state as you can see above. 

This continued one, until rollout status said the rolling out was done

`deployment "kube-controller-manager" successfully rolled out`

However, the actual status of the rollout was:

```
kb get po -l k8s-app=kube-controller-manager -o wide
NAME                                      READY     STATUS    RESTARTS   AGE       IP         
kube-controller-manager-889084721-8ppdm   1/1       Running   0          1m        10.5.57.4   
kube-controller-manager-889084721-drbkh   0/1       Pending   0          1m        <none>
kube-controller-manager-889084721-sn6xg   1/1       Running   0          1m        10.5.14.6   
```

**What you expected to happen**:

I expect kubectl to understand that pending does not mean it was successfully applied. That last pending pod could have failed; however, automated deployment scripts that depend on rollout status would have thought everything was OK. 

**How to reproduce it** (as minimally and precisely as possible):

Apply an update to a pod that uses anti-affinity to limit the number of pods per node and limit the number of nodes to the same as replicas. 

**Anything else we need to know**:

**Comment by kargakis** [comment]
What is the maxUnavailable value of your Deployment? If it's 1, then 2 out of 3 means complete.

**Comment by kargakis** [comment]
Affinity or anti-affinity rules don't matter btw

**Comment by kargakis** [comment]
> 2 out of the 3 replicas had not been updated successfully. They were still in a pending state as you can see above.

Updated does not mean running.

**Comment by kargakis** [comment]
@janetkuo @kubernetes/sig-cli-misc  I think we should add a flag in `rollout status` that would bypass maxUnavailable and return when all pods are available (old behavior). Thoughts?

**Comment by kargakis** [comment]
Or maybe we need to document better MaxUnavailable.

**Comment by jhorwit2** [comment]
maxUnavailable was 0. 

Is this how the deployment controller works also? I.e. if my last pod failed for the progress deadline time would the deployment still pass?

**Comment by jhorwit2** [comment]
To answer my own question, it appears it does use maxUnavailable. [Link](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/util/deployment_util.go#L842)

updated docs would be nice. It doesnt say anything about it in the docs [here](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#max-unavailable) about this functionality. 

I and others I work with, assumed that was purely for down pods during the upgrade, but the upgrade still wasn't complete until every pod was updated.

**Comment by kargakis** [comment]
> I and others I work with, assumed that was purely for down pods during the upgrade, but the upgrade still wasn't complete until every pod was updated.

@jhorwit2 every pod in the upgrade is required to be updated ([see here](https://github.com/kubernetes/kubernetes/blob/eccba3b6d00345422e45829a29eab9b6fc29c1a2/pkg/controller/deployment/util/deployment_util.go#L845)). Even in your example, the last pod is updated (but not running). If you want to wait for all pods to be running for the upgrade to be complete, you can use maxUnavailable=0. If you were using maxUnavailable=0 and rollout status exited prior to all pods coming up then that's a bug (and next time you hit it, please post the output of `kubectl get deploy NAME -o yaml` redacting any stuff you don't want in the output).

@smarterclayton @janetkuo @bgrant0607 any thoughts on when a rollout should be considered complete wrt maxUnavailable? We switched `rollout status` recently to respect maxUnavailable but we may want to reconsider if that's the right approach.

**Comment by jhorwit2** [comment]
@kargakis The most confusing part to me about this is that progress deadline is handled differently. You can [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/util/deployment_util.go#L864) that it doesn't take into account maxUnavailable. We consider a deployment complete when it can no longer possibly fail and that's not how `rollout status` works.

**Comment by kargakis** [comment]
ProgressDeadlineSeconds is using the same helper [here](https://github.com/kubernetes/kubernetes/blob/1ee8f2f543e2cc6c56821eb8f1504d12ee7b169c/pkg/controller/deployment/progress.go#L97). Agreed that it is confusing and at the very least we need to document this better.

**Comment by kargakis** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/44672 that restores "Complete" to mean "All pods need to be available". Wrt the term "available", I have a proposal that is switching it to "stable" [here](https://github.com/kubernetes/community/pull/478).
