### ISSUE TITLE
Break Kubelet into separate project

### ISSUE THREAD

**Issue by michaelneale** [kubernetes/kubernetes#444]
Does it make any sense to extract the "pod" code into a place that could potentially be combined with docker itself (I say potentially, as the docker project may prefer to leave this out - as a 3rd party tool). 

The need to stand up 3 containers for a single app is pretty common - for example - discourse has a setup that stands up a few containers to run their app on a single node: https://github.com/discourse/discourse_docker

The pod concept (at least some of it) may be able to be separated - avoiding a proliferation of formats/tricks to do essentially the same thing.

**Comment by bgrant0607** [comment]
Due to the difficulties this would create for build and test, we've decided that breaking our code into multiple projects will not happen before we reach our 1.0 milestone.

**Comment by proppy** [comment]
+1 to split the `runPod` logic and the `PodSpec` from `pkg/kubelet` and `pkg/api/v1beta3`, it would make written some small tool like [podlet](https://gist.github.com/proppy/04f1270e015c0179b2d4) trivial.
