### ISSUE TITLE
Fix ci-kubernetes-soak-gce-federation-test

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#44402]
Moving this discussion from https://github.com/kubernetes/test-infra/issues/2457. 

This job is broken due to problems in the corresponding deploy job. It has been in this state for a while due to test-infra issues and @shashidharatd has been tirelessly working on it. This issue is to track the progress towards making the soak test work.

Ref: https://github.com/kubernetes/test-infra/issues/2457

**Comment by madhusudancs** [comment]
> @shashidharatd option 3 is to block the federation-deploy job from running while the federation-build job is running. That is a 1-line fix.

How do we accomplish that?

**Comment by madhusudancs** [comment]
cc @ixdy

**Comment by ixdy** [comment]
The soak/deploy jobs already mutually block on each other (see [here](https://github.com/kubernetes/test-infra/blob/8e64a2e7a3f81721b1ef62484ba28c15f45cdbcd/jenkins/job-configs/kubernetes-jenkins/bootstrap-ci-soak.yaml#L19-L20) and [here](https://github.com/kubernetes/test-infra/blob/8e64a2e7a3f81721b1ef62484ba28c15f45cdbcd/jenkins/job-configs/kubernetes-jenkins/bootstrap-ci-soak.yaml#L72-L83)).

We'd need to refactor the template to allow specifying multiple blocker jobs, and then just add the build job as a blocker. (Maybe also make the build job block on the deploy job.)

So not quite 1 line, but close.

**Comment by madhusudancs** [comment]
@ixdy makes sense, thanks!

**Comment by shashidharatd** [comment]
@ixdy, 
 Please correct me if my understanding is incorrect.
adding blocker job to a job will only make the job wait until the blocker job is run right?
(All the federation deploy jobs except soak ones have a reverse trigger set to federation build job, and its not the blocker but the trigger)

Our situation in federation soak jobs is like below:
1. federation-soak-build job runs daily say at 11:00 P.M and publishes a release to `ci/latest` and also push hyperkube image to gcr.io registry of the project.
2. federation-soak-deploy job runs everyday at 12:00 P.M and uses the `ci/latest` to pull the hyperkube image for federation init.

there is no link between the build and deploy jobs. Between build and deploy jobs if there are any other non-federation builds they also publish the release to 'ci/latest', so when federation soak deploy job tries to pull the hyperkube image based on that version it fails to find it.

**Comment by ixdy** [comment]
@shashidharatd setting a blocker job provides mutual exclusion. we have the deploy and soak test jobs set as mutually blocking so we don't try to redeploy a cluster while running tests, nor run tests while deploying a cluster.

I'm a little confused by non-federation builds pushing to `ci/latest`. It looks like the deploy job is configured to read from the `kubernetes-release-federation` bucket, not `kubernetes-release-dev`, so I wouldn't expect any non-federation builds to be overriding the `ci/latest` file in that bucket.

**Comment by shashidharatd** [comment]
Thanks @ixdy for clarifying.
I feel even though we are specifying `kubernetes-federation-release` in soak deploy job, it is still using `kubernetes-release-dev`. Something is broken here.
below are the lines from from federation-soak-deploy job:
```
W0413 00:05:50.040] 2017/04/13 00:05:50 util.go:194: Running: gsutil cat gs://kubernetes-release-dev/ci/latest.txt
W0413 00:05:51.082] 2017/04/13 00:05:51 util.go:196: Step 'gsutil cat gs://kubernetes-release-dev/ci/latest.txt' finished in 1.041515679s
W0413 00:05:51.082] 2017/04/13 00:05:51 extract.go:229: U=https://storage.googleapis.com/kubernetes-release-dev/ci R=v1.7.0-alpha.1.374+e4752d612a9a33 get-kube.sh
```

**Comment by ixdy** [comment]
aha, there we go. It looks like a bug in kubetest.

The `ci-kubernetes-soak-gce-federation-deploy` job (along with several other federation jobs) overrides `KUBE_GCS_RELEASE_BUCKET` and `KUBE_GCS_DEV_RELEASE_BUCKET` to `kubernetes-federation-release`.

Before https://github.com/kubernetes/test-infra/pull/1657, we'd look at `gs://$KUBE_GCS_DEV_RELEASE_BUCKET/ci/latest.txt` for the version. But with the change, we now [always look](https://github.com/kubernetes/test-infra/blob/cdf740a7199a087083c97b7c797ca1298b1a2f34/kubetest/extract.go#L246) in `kubernetes-release-dev`, which is the wrong behavior for federation.

@fejta should we add a flag to kubetest to allow this override?

**Comment by fejta** [comment]
Does the issue for fixing this job exist in the main repo yet?

Why is the right behavior for federation builds to go in their own bucket, with their own parallel CI system?

**Comment by fejta** [comment]
If we need this seems like the best way to do it is to make `--extract=E` aware of this scenario.

We could update `case gcs` in `extract.go` to do `setReleaseFromGcs` instead of `getKube` when the `gs://` path ends in `.txt`. 

I prefer we do not add a flag for this. 

But really--why do we create official CI builds that don't support/include federation?

**Comment by madhusudancs** [comment]
> Why is the right behavior for federation builds to go in their own bucket, with their own parallel CI system?

There is not really a good reason. When we were creating these jobs, it felt like the separation would help us in debugging. I haven't seen things play out that way in reality ever. We could just use the regular release bucket.

However, I don't think regular kubernetes build jobs build and push hyperkube image which is required for federation (@ixdy correct me if I am wrong). So we still need a separate job or enable building hyperkube image in regular kubernetes build jobs.

**Comment by fejta** [comment]
Upgrading the regular build jobs to always do a federation build sgtm

**Comment by shashidharatd** [comment]
just a small concern, if we are doing federation build for all build jobs.
is there some sort of cleanup for gcr.io registry images which we push to the project or are they gonna be there forever until manual cleanup?
if we are cleaning up old hyperkube images manually, then we might need to track all the build-jobs and their projects to do regular cleanup.

**Comment by ixdy** [comment]
I don't think there's any built-in cleanup right now. It is an issue we need to figure out, since we want to start building/pushing all of the images we use fairly regularly in CI.

I think a reasonable compromise for now is to push the images to somewhere besides `gcr.io/google-containers` and not worry about cleaning up.

**Comment by shashidharatd** [comment]
The difference between a `regular build job` and a `federation build job` is that federation additionally pushes the hyperkube image to registry after the release tar is uploaded to GCS.
Now if we introduce pushing the image to registry in all regular build, it would be an overhead for those builds. all the problems associated with building hyperkube image will start showing up in all build jobs.

Here is one example where the hyperkube image build was broken. #44749

@fejta @ixdy @madhusudancs. is the plan of pushing hyperkube image in all regular build still ok?

**Comment by shashidharatd** [comment]
please refer to the comments in #44751

**Comment by shashidharatd** [comment]
@madhusudancs, alternatively is it possible to build and push the hyperkube image to registry in `federation deploy` job? and then go for deploying federation control plane. we can eliminate the need for `federation build` jobs.

**Comment by madhusudancs** [comment]
@shashidharatd it should be possible. We do this in PR tests already. However, we are going to spend time running these builds in the test job which makes them slower and I am not sure about that. 

Shouldn't things like #44749 happening in all the builds a good thing? Federation should not be the only victim of such issues. 

I wonder if we should merge the build + deploy job only for soak tests where `deploy` time really doesn't matter that much.

**Comment by shashidharatd** [comment]
federation soak jobs are working fine now. we can close this issue now.
/close
