### ISSUE TITLE
Re-organize the changelog so that related releases are close together

### ISSUE THREAD

**Issue by exarkun** [kubernetes/kubernetes#44400]
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md (linked from <https://kubernetes.io/docs/home/> in the left sidebar as "Release Notes") would be easier to read if different release lines didn't have their notes randomly interspersed.

My use case for reading the ChangeLog is to find out everything announce-worthy that changed between two points on a single release line.  So, for example, I want to see all the changes between 1.5.1 and 1.5.4.  That's harder to do when there are entries for 1.4.9 and 1.6.0.alpha3 mixed in with the entries for 1.5.2, 1.5.3, and 1.5.4.

**Comment by xiangpengzhao** [comment]
To be clear, the current release notes aren't randomly interspersed. They are sorted by the date when they are released. But I 100% agree with your use case. That's more readable.

cc @enisoc

**Comment by kargakis** [comment]
@kubernetes/sig-release-misc

**Comment by xiangpengzhao** [comment]
Already re-organized.
/close
