### ISSUE TITLE
Deprecate created-by annotation, in favor of ControllerRef

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#44407]
TODOs:

* [x] `kubectl describe` list of controllers for an object.
* [x] `kubectl drain` Pod filtering.
* [x] Classifying failed Pods in e2e test framework.
* [x] CronJob grouping Jobs by owner/creator.
* [ ] Announce deprecation of created-by annotation in the release note

@erictune @enisoc @kow3ns @foxish @kargakis @kubernetes/sig-apps-feature-requests

**Comment by enisoc** [comment]
The uses I found in my last search were:

* [x] `kubectl describe` list of controllers for an object.
* [ ] `kubectl drain` Pod filtering.
* [ ] Classifying failed Pods in e2e test framework.
* [ ] CronJob grouping Jobs by owner/creator.

**Comment by foxish** [comment]
@crimsonfaith91 PTAL

**Comment by crimsonfaith91** [comment]
i will work on this. :)
/assign

**Comment by enisoc** [comment]
Keep in mind that for each case that currently uses created-by, we will need to analyze and justify whether it actually makes sense for it to be switched to ControllerRef. I didn't do a full analysis yet; I only searched for the cases that we need to analyze. In some cases like CronJob, we may also need to consider what happens during cluster upgrade/downgrade if we decide to make the switch.

Feel free to tag me as a reviewer for work on this issue. Thanks for taking it on!

**Comment by crimsonfaith91** [comment]
@enisoc Definitely! I will spend some time going over the codebase for `pod`, `cronjob`, and others to analyze the effect. I will sync with you sometime next week. :)

**Comment by crimsonfaith91** [comment]
I have looked at the codes, and is working on sending out a PR. Below are my understanding and thoughts for tasks to be done for this issue:
(1) kubectl drain Pod filtering: annotation is used to obtain pod's controller. We can substitute it with ControllerRef.
(2) classifying failed Pods in e2e test framework: annotation is used to determine whether the pod is being controlled by a controller. We can test whether there is a controller for the pod using another way.
(3) cronJob grouping Jobs by owner/creator: annotation is used to obtain parent UID of a job and obtain job from cronjob template. After discussing with @janetkuo , the annotation should be removed only for obtaining a job's parent UID. I still have to look at controller manager codes to check what happens during cluster upgrade/downgrade as pointed out by @enisoc .

I will send out a PR sometime this week to check whether i am on the right direction. Feel free to give feedback. Thanks! :)
@foxish

**Comment by janetkuo** [comment]
This is fixed

**Comment by enisoc** [comment]
Do we actually want to stop setting the annotation at some point? If so, we should reopen this until we ensure there is an announcement of the deprecation (i.e. release note) and a tracking issue to actually do the removal, targeted at the proper milestone.

**Comment by enisoc** [comment]
After discussing with @erictune we think the next steps for this are:

- [ ] Remove any remaining uses of the annotation in satellite k8s repos.
- [ ] Look for any uses of the annotation in other GitHub repos to see if anyone in the wild has discovered its existence.
- [ ] Email kubernetes-dev@googlegroups.com to explain why we want to deprecate it (controllerRef is more useful because it's up-to-date; the annotation isn't documented, well-defined, nor consistently applied, and is an ongoing burden to maintain; it was only meant for internal uses which have now changed to controllerRef) and ask if anyone has reason to keep it.
- [ ] Seek guidance on whether annotations without alpha/beta labels have to follow the same deprecation policy as GA fields.

**Comment by philips** [comment]
FWIW, kubernetes-dev was emailed last week, no comments so far. https://groups.google.com/forum/#!topic/kubernetes-dev/juMOsdaCml0

**Comment by crimsonfaith91** [comment]
@philips Yes. I have sent another email to `kubernetes-users@googlegroups.com` around an hour ago to solicit opinions.

**Comment by enisoc** [comment]
@crimsonfaith91 Can we close this now?

**Comment by crimsonfaith91** [comment]
Yes! For future reference, perhaps we can change the task list comment above: https://github.com/kubernetes/kubernetes/issues/44407#issuecomment-318765753
Perhaps we can have a strikethrough for item(2) and a tick for item(4).
For item(2), we discussed in sprint planning meeting that we would not do it (correct me if i am wrong), so i think a strikethrough is better than a tick.
