### ISSUE TITLE
Windows kubectl sends full path as User-Agent

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#44419]
It looks like kubectl uses path.Base instead of filepath.Base, and the former does not work correctly when the OS uses a path separator besides ‘/’.  This only affects kubectl on Windows, AFAICT.

We should patch kubectl and also modify kube-apiserver to discard this information when contacted by old clients.  We should also cherry pick this onto 1.6, 1.5, and 1.4.

@monopole has a fix for kubectl, and I have a fix for kube-apiserver.

**Comment by mml** [comment]
I have cherry picks in process for the kube-apiserver part: #44575 #44585 #44586 

I couldn't easily get the kubectl fix to pick onto 1.6.  Hopefully @monopole has better luck.

**Comment by mml** [comment]
(Re-opening until the fixes are backported and released.)

**Comment by mml** [comment]
The kubectl fix is now on 1.6 (#44622).

**Comment by kargakis** [comment]
Seems fixed - @mml please reopen if there is anything left
