### ISSUE TITLE
Timeout waiting for the condition during V1Job tests

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#44410]
Triage history cluster: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=v1job#63a36434077ff31ae29e

Note that the triage history page's filters at the top allow you to focus on specific jobs or tests

73 different tests across 115 jobs are failing in this pattern.

The apps part of this issue is:
1) `V1Job should fail a job` in upgrades from 1.4 - #44602 

Previous things:
1) `NFSv3 should be mountable for NFSv3` in `gke-staging` and `gke-prod` https://github.com/kubernetes/kubernetes/issues/44695
2) `Services should only allow access from service loadbalancer source ranges` in `kops-aws-slow` https://github.com/kubernetes/kubernetes/issues/44514

**Comment by lavalamp** [comment]
Job is apps, not api machinery

**Comment by soltysh** [comment]
> V1Job should fail a job in upgrades from 1.4 example

@fejta based on description and logs (`should fail a job [Slow]`) you're running [1.4 version](https://github.com/kubernetes/kubernetes/blob/release-1.4/test/e2e/batch_v1_jobs.go#L191-L202) of this test, the problem was identified in [1.5 and fixed](https://github.com/kubernetes/kubernetes/blob/release-1.5/test/e2e/batch_v1_jobs.go#L191-L214) do you want me to backport [that fix](https://github.com/kubernetes/kubernetes/commit/393d551332e1b8546f5fa6ee475406e5552fd2f9) to 1.4?

**Comment by fejta** [comment]
Yes please, or delete the 1.4 tests :smiling_imp:

**Comment by soltysh** [comment]
I don't like removing tests, so I've opened https://github.com/kubernetes/kubernetes/pull/44602.

**Comment by bowei** [comment]
@justinsb @kubernetes/sig-aws-misc -- could someone with more AWS experience take a look at the failure "Services should only allow access from service loadbalancer source ranges in kops-aws-slow example" to see if this is a generic failure or one specific to the environment?

**Comment by dcbw** [comment]
> Services should only allow access from service loadbalancer source ranges in kops-aws-slow example

I did try to look into this, but couldn't get very far.  The AWS LoadBalancer gets created:

`I0412 18:20:14.492568       5 aws.go:2776] Loadbalancer aaaf457fe1fac11e7a92706ccb8c2b1b (e2e-tests-services-6c18d/lb-sourcerange) has DNS name aaaf457fe1fac11e7a92706ccb8c2b1b-1987870637.us-west-2.elb.amazonaws.com`

but the jenkins job starts calling wget at `11:22:34.325` and checks 62 times in the next 75ms (until `11:22:34.410`) before giving up.  WTH? 62 times in 75ms?  Do we really expect everything to be set up that quickly, especially if we have to talk to the AWS API?

networking_utils.go does this:

`	err := wait.PollImmediate(Poll, 2*time.Minute, func() (bool, error) {`

where Poll is 2*time.Second.  So I'm mystified why the condition function is getting called every 1ms or so.

**Comment by chrislovecnm** [comment]
cc @zmerlynn and @justinsb any ideas on the dns stuff? I have seen that odd error before when dns is misconfigured, but it may be something else.  I do not know the specifics of the Jenkins machine setup, only that this URL is a full public resolvable URL.  Please reach out if you need assistance debugging.

**Comment by justinsb** [comment]
The "bad address" means DNS resolution failed.

When an ELB is created, the DNS name is known, but it might not resolve for a few minutes.  So the test should wait for a few minutes, at least on AWS.  It looks like we wait 2 minutes, which feels very tight to the time I expect it to take.  Going to check if something changed recently in our tests.

**Comment by justinsb** [comment]
Broke out #44965 for LB timeout, hopefully fixed (apply correct timeout) by #44696

**Comment by dcbw** [comment]
> The "bad address" means DNS resolution failed.

@justinb hmm.  Usually if you pass a bad address you'll get:

`wget: unable to resolve host address ‘adsfasdfasf.com’`

and when I checked I couldn't find "bad address" or EFAULT anywhere in wget sources.  Nor does gethostbyname(2) say it returns EFAULT as an error.  But I can only assume DNS failure is what this means, not sure what else it would be.

> When an ELB is created, the DNS name is known, but it might not resolve for a few minutes. So the test should wait for a few minutes, at least on AWS. It looks like we wait 2 minutes, which feels very tight to the time I expect it to take. Going to check if something changed recently in our tests.

Good to know.  Thanks for pushing it forward!

**Comment by fejta** [comment]
Reducing this to just the V1Job problem, migrating the other parts to other issues:
* networking: https://github.com/kubernetes/kubernetes/issues/44695
* storage: https://github.com/kubernetes/kubernetes/issues/44514

**Comment by fejta** [comment]
This remains unresolved. Expectations:
* This work should interrupt and take priority over other activity while it is assigned to you.
* Expectation for sig leads is to identify someone to fix the issue, `/assign` them and `/unassign` yourself.
* Expectation for assignees are to investigate the issue and either a) resolve it or b) `/assign` it to a more appropriate person and b) `/unassign` yourself.


Per experiment assigning apps issues to a single person on workloads in a round robin fashion, 
/assign @foxish 
Please identify the correct person to fix this issue, `/assign` that person and `/unassign` yourself.

**Comment by fejta** [comment]
FYI looks like this is stuck in code review https://github.com/kubernetes/kubernetes/pull/44602

**Comment by soltysh** [comment]
@fejta I'm willing to say we should just merge this as is, this is a straight cherry-pick of a fix applied already to a latter version.

**Comment by janetkuo** [comment]
Just LGTM'ed the PR. It needs approval from 1.4 release manager

**Comment by fejta** [comment]
Thanks so much @soltysh and @janetkuo. The go.k8s.io/oncall page shows a link to the release managers.

**Comment by soltysh** [comment]
I've added cherry-pick approval label, @pwittrock was ok with the fix (stated that in one of earlier comments in the PR). So we can get this out of list.

**Comment by soltysh** [comment]
https://github.com/kubernetes/kubernetes/pull/44602 merged so I'm closing this.

**Comment by fejta** [comment]
Yay! Thank you so much!

And if you look there are zero hits of this cluster after 4a today: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=v1job#63a36434077ff31ae29e
