### ISSUE TITLE
Create OWNERS files for all subdirs of kubernetes/

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#44420]
/assign @smarterclayton @lavalamp @dchen1107 @thockin @brendandburns @jbeda 
/cc @grodrigues3 

Please ensure that every sub directory of / contains an owners file.

The following sub directories do not define them:
```
k8s.io/kubernetes$ for i in $(ls | grep -v -E '^_'); do if [[ ! -d $i ]]; then continue; elif [[ -e $i/OWNERS ]]; then continue; fi; echo MISSING OWNERS: $i; done
MISSING OWNERS: api
MISSING OWNERS: Godeps
MISSING OWNERS: hooks
MISSING OWNERS: staging
MISSING OWNERS: third_party
MISSING OWNERS: translations
MISSING OWNERS: vendor
```

The result of this is that any PR which changes anything in api, Godeps, staging, vendor, etc will always get assigned to one of you for both the review and approval.

**Comment by grodrigues3** [comment]
I recall someone also mentioning that certain files or dirs may not need approvers files.  If that would help, we can add that functionality (i've already started the work)

**Comment by jbeda** [comment]
staging and api should be easy to find owners for.

@bburns may have ideas for translations.

The big one is Godeps, third_party, vendor.  Those are just grunt work.  And figuring out criteria for approving is hard as they are a lot of code and it is unclear that things are tested well or automatically.  (I'm thinking things like libraries for accessing cloud APIs).

Having a dedicated team/process there might help.

**Comment by smarterclayton** [comment]
I'll open some proposals for staging and API.

**Comment by thockin** [comment]
Godep in particular needs to be watched for things like licenses, which I have mostly been doing.

**Comment by fejta** [comment]
Thanks Clayton for the staging and api additions!

How about if we pick two of you at random and shove them in as owners for each of the remaining directories?

**Comment by cblecker** [comment]
What's left:
```
MISSING OWNERS: Godeps
MISSING OWNERS: third_party
MISSING OWNERS: translations
MISSING OWNERS: vendor
```

translations: the kubectl specific translations is being handled by sig-cli, but the rest of the files like README and test have been handled and approved mostly by @brendandburns.
third_party: this is a tricky mix of stuff like forked code.. mostly handled by the likes of @thockin, @lavalamp, or @smarterclayton for approvals.
Godep/vendor: These could probably be solved by having a process to follow, and then delegating to a team in OWNERS_ALIASES for both folders.

**Comment by cblecker** [comment]
Still relevant.
/remove-lifecycle stale
