### ISSUE TITLE
sort -V not available in OSX; which breaks etcd version check

### ISSUE THREAD

**Issue by StevenYCChou** [kubernetes/kubernetes#44425]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
sort, etcd
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.1.363+32600927d97414-dirty", GitCommit:"32600927d97414795a6355f3cac23806d59e9cdd", GitTreeState:"dirty", BuildDate:"2017-04-12T22:49:52Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
```
**Environment**:
- **Cloud provider or hardware configuration**:
OSX as client laptop 
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
when I run `make test-cmd`, it fails on `sort`.
```
make test-cmd
+++ [0412 21:49:09] Running kubectl tests for federation-apiserver
sort: invalid option -- V
Try `sort --help' for more information.
/Users/ycchou/go/src/k8s.io/kubernetes/hack/make-rules/../../third_party/etcd:/Users/ycchou/go/src/k8s.io/kubernetes/_output/local/bin/darwin/amd64:/Applications/Postgres93.app/Contents/MacOS/bin:.git/safe/../../bin:/Users/ycchou/.bin:/usr/local/sbin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/apache-maven-3.3.1/bin:/Users/ycchou/.rvm/gems/ruby-2.2.1/bin:/Users/ycchou/.rvm/gems/ruby-2.2.1@global/bin:/Users/ycchou/.rvm/rubies/ruby-2.2.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/TeX/texbin:/Users/ycchou/.rvm/bin:/usr/local/Cellar/ec2-api-tools/1.6.12.0/libexec/bin:/usr/local/Cellar/ec2-ami-tools/1.4.0.9/libexec/bin:/usr/local/share/storm/bin:/usr/texbin:/usr/local/share/scala/bin:/usr/local/share/sbt/bin:/Users/ycchou/go/bin
sort: invalid option -- V
Try `sort --help' for more information.

etcd version 3.0.17 or greater required.

You can use 'hack/install-etcd.sh' to install a copy in third_party/.
```

**What you expected to happen**:
no failure version check in OSX environment.

**How to reproduce it** (as minimally and precisely as possible):
in OSX environment:
1. comment out [other two tests](https://github.com/kubernetes/kubernetes/blob/2634f57f7f48ac1ae0388e906d32855d79bd1de8/Makefile#L268-L269) to run `hack/make-rules/test-federation-cmd.sh` only
2. run `make test-cmd` and see it fails.

**Anything else we need to know**:
code can be found in https://github.com/kubernetes/kubernetes/blob/36d244f0843e83e8c14a2ccd309a94715c93b57c/hack/lib/etcd.sh#L39
and 
https://github.com/kubernetes/kubernetes/blob/36d244f0843e83e8c14a2ccd309a94715c93b57c/hack/lib/etcd.sh#L44

**Comment by ncdc** [comment]
See https://github.com/kubernetes/kubernetes/pull/44396

**Comment by liggitt** [comment]
fixed in https://github.com/kubernetes/kubernetes/pull/44396
