### ISSUE TITLE
Missing V1FinalizerName constructor generated by Swagger Codegen

### ISSUE THREAD

**Issue by Fuzzo** [kubernetes/kubernetes#44433]
**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.6.1
- **Cloud provider or hardware configuration**: VM on SoftLayer
- **OS** (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- **Kernel** (e.g. `uname -a`): 3.10.0-514.10.2.el7.x86_64
- **Swagger Codegen**: 2.2.2

This is a Bug Report

**Problem:**
The Swagger Codegen 2.2.2, used to create a Java/Jersey2 client, does not provide a String constructor for the class `V1FinalizerName`.

The execution of the following code snippet:

```
// client object init
Apiv1Api v1 = new Apiv1Api(client);
V1NamespaceList nsList = v1.listNamespace("true", null, null, null, null, null);
for (V1Namespace ns : nsList.getItems()) {
    System.out.println(ns.getMetadata().getName());
}
```

cause at runtime the error:
`com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class com.vts.k8s.swagger.client.model.V1FinalizerName] from String value ('kubernetes'); no single-String constructor/factory method`

**Workaround:**
Add this to the generated `V1FinalizerName `class:

```
public V1FinalizerName(String s) {
}
```

**Proposed Solution:**
Fix the API definitions to have the String constructor in class `V1FinalizerName `using Swagger Codegen.

**Comment by qq690388648** [comment]
Let me think...

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc
