### ISSUE TITLE
pod status should be pending instead of failed when all gpus are used.

### ISSUE THREAD

**Issue by pineking** [kubernetes/kubernetes#44438]
I use kubernetes with version `v1.7.0-alpha.0.1714+2169beed2344f2`, and enable flag ` --feature-gates=Accelerators=true` to use GPU running deep learning experiments.

**What happened**:
when all GPUs in the cluster are used, 
I run the command `kubectl create -f xxx.yaml` to request 1 gpu with `alpha.kubernetes.io/nvidia-gpu: 1` in yaml file, the Pod status shows `outofalpha.kubernetes.io/nvidia-gpu`

**What you expected to happen**:
when all GPUs in the cluster are used, If create a new Pod to request 1 GPU with `alpha.kubernetes.io/nvidia-gpu: 1` in YAML file, the Pod status shows `Pending`, so the Pod can continue to run when the GPUs are available.

@vishh @cmluciano

**Comment by cmluciano** [comment]
Does the pod continue to hang indefinitely even when the resources are freed?

**Comment by pineking** [comment]
@cmluciano yes, the pod is still hanging when the GPUs are available.
Actually, the status of pod is failed (expect to be pending) when it shows the message `outofalpha.kubernetes.io/nvidia-gpu`
so It can not run again when the GPUs are freed.

```
Start Time:     Fri, 14 Apr 2017 09:46:09 +0800
Labels:         <none>
Annotations:    <none>
Status:         Failed
Reason:         OutOfalpha.kubernetes.io/nvidia-gpu
Message:        Pod Node didn't have enough resource: alpha.kubernetes.io/nvidia-gpu, requested: 1, used: 4, capacity: 4
```

**Comment by cmluciano** [comment]
cc @vishh i thought we had e2e tests that were testing this, but I'm not sure if they are running yet

**Comment by pineking** [comment]
@cmluciano I found the reason.
The status of pod is failed with the reason of `OutOfalpha.kubernetes.io/nvidia-gpu` if there is a `nodeName: xxxx` in YAML file when there is not free GPU left on this node, which means that there are not enough GPUs to running the pod on node xxxx.
The status of pod is pending as expected if we remove the line `nodeName: xxxx` from the yaml file.
so, this issue can be closed.
