### ISSUE TITLE
[FR] Update netlink vendor package ?

### ISSUE THREAD

**Issue by thechile** [kubernetes/kubernetes#44430]
**FEATURE REQUEST**

Hi 

Is there any plans to update the [github.com/vishvananda/netlink](https://github.com/vishvananda/netlink/) vendor package to newer version ? I would like to use the [LinkSetAlias](https://github.com/vishvananda/netlink/blob/master/link_linux.go#L242) that was added in recent version to tag/alias the veth interfaces on node and in pod namespace for easier identification and troubleshooting. 

Thank you.

**Comment by kargakis** [comment]
@kubernetes/sig-network-misc

**Comment by thockin** [comment]
Can you write a proposal about what you want to do?  Just a short
explanation of how it fits into the system?

On Wed, Apr 12, 2017 at 8:04 PM, Scott McGillivray <notifications@github.com
