### ISSUE TITLE
CRI: exec/attach requests don't let you disable stdout or stderr

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#44448]
I'm working on rebasing OpenShift on top of Kubernetes 1.6 and I just noticed that if you try to exec/attach to a pod, the CRI protobuf messages for AttachRequest and ExecRequest only allow you to specify stdin and tty. You are not able to specify stdout or stderr. The handlers for serving exec and attach streaming requests force stdout to true, and stderr to true when not using a tty. Is there a reason that stdout and stderr are hard-coded and not optional?

I'm able to work around this by saying I "want" stdout and stderr, and sending their data to `ioutil.Discard`, but I don't think that's a good long-term solution. I believe this is a regression and we should restore the ability to selectively enable both stdout and stderr.

Thoughts?

@yujuhong @dchen1107 @vishh @Random-Liu @timstclair @smarterclayton @derekwaynecarr @liggitt @sttts @kubernetes/sig-node-bugs

**Comment by derekwaynecarr** [comment]
it sounds like an unintended regression.  i agree it would be good to selectively enable.

**Comment by timstclair** [comment]
I can't remember what the original reasoning for this decision was, but it was a conscious decision. I may have only been looking at kubectl usage at the time. Also note that there are restrictions in the server for which combination of parameters can be specified: https://github.com/kubernetes/kubernetes/blob/d2733394ca664e4e536d0f8e27bf7edbbb53dec0/pkg/kubelet/server/remotecommand/httpstream.go#L60

Out of curiosity, what is your usecase for dropping stderr and stdout?

**Comment by ncdc** [comment]
re parameter combinations, I'm definitely familiar, but that won't be an issue as we will be passing in stdin.

Our flow is a user does `oc start-build ... --from-dir=x` which streams the contents of dir x to the container's stdin, and assuming the transfer is successful, the http handler returns an OpenShift `api.Build` object. Once the container receives stdin, it tries to perform a build. The user can view the status of the build via `oc get build` and they can also see the logs from the build via `oc logs`. Given the way this works, there's no need for stdout or stderr here.

**Comment by yujuhong** [comment]
I don't think adding this would be an issue (@timstclair, correct me if I am wrong).

On the other hand, we don't have test coverage for kubelet endpoints (which are not versioned) other than kubectl tests. If this is an important feature for openshift, @ncdc maybe you can help add a test? :-)

**Comment by ncdc** [comment]
I can work on a test but I doubt I'll have time until next week at this point. But I'd be happy to do it.

**Comment by vishh** [comment]
Just curious, other than the technical implementation regression aspect of
this issue, does it hurt to have stdout and stderr set by default? IIUC, in
the oc build use case, stdout/stderr is ignored.

From an API standpoint, is it really a regression to have stdout/stderr set
by default except if `kubectl run` or `kubectl attach` attempts to attach
even if interactive mode is disabled?

**Comment by liggitt** [comment]
I think it blocks unless you consume the data, right?

**Comment by ncdc** [comment]
No, the issue isn't blocking re consumption. The problem is that as a client, I send an options struct that says "I only want stdin", so I only create a spdy stream for stdin (plus the always-present general-purpose error stream). By having the server default stdout and stderr, it's expecting the client to create streams for stdin, stdout, and stderr. This mismatch results in the server waiting for 30 seconds (stream creation timeout) for all the streams it is expecting (error, stdin, stdout, stderr). The client only creates 2: error, stdin. After 30 seconds, the server gives up.

So this is definitely a regression.

**Comment by dchen1107** [comment]
I think this is a regression, and we should introduce back the ability to selectively enable both stdout and stderr. @ncdc How urgent this is? Can we live with the workaround and fix it in 1.7? Or we need a patch?

**Comment by ncdc** [comment]
Not urgent

**Comment by liggitt** [comment]
the defaulting for pod exec and attach objects seems wrong as well:
```
func SetDefaults_PodExecOptions(obj *PodExecOptions) {
	obj.Stdout = true
	obj.Stderr = true
}
func SetDefaults_PodAttachOptions(obj *PodAttachOptions) {
	obj.Stdout = true
	obj.Stderr = true
}
```
