### ISSUE TITLE
`getOneTimeResourceUsageOnNode` e2e/framwork function no longer works

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#44442]
I guess it got deprecated. We should clean up all test logic that depends on deprecated-and-no-longer-used cadvisor v1 api.

@kubernetes/sig-node-feature-requests

**Comment by yujuhong** [comment]
The function should switch to using the /stats/summary endpoint.

**Comment by gmarek** [comment]
Yup, I did just that in #44453. Do you know if any other tests might have stopped working?

**Comment by yujuhong** [comment]
@gmarek is this still relevant?
Only `resource_usage_gatherer.go` uses this function

**Comment by gmarek** [comment]
It probably still doesn't work, but I believe we moved away from it. I'll just close the issue.
