### ISSUE TITLE
Kubelet does not restart static manifest pods correctly in 1.6

### ISSUE THREAD

**Issue by dwradcliffe** [kubernetes/kubernetes#44450]
**Is this a request for help?** No

**What keywords did you search in Kubernetes issues before filing this one?** static manifest

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Bare metal and reproduced in Vagrant
- **OS** (e.g. from /etc/os-release): `Ubuntu 16.04.2 LTS`
- **Kernel** (e.g. `uname -a`): `Linux ubuntu-xenial 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**: custom scratch install and reproduced with kubeadm
- **Others**: Calico for networking. Used http://docs.projectcalico.org/v2.1/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml (Also able to reproduce without calico)

**What happened**:
Modified one of the static manifest files in `/etc/kubernetes/manifests/`. The kubelet killed the running pod and did NOT create a new pod. (waited 30 minutes, still no pod) 

**What you expected to happen**:
Kubelet should have killed the pod and started a new one.

**How to reproduce it** (as minimally and precisely as possible):
Started with single node, vanilla Ubuntu Xenial, installed kubernetes via kubeadm, nothing special.
Modify `/etc/kubernetes/manifests/kube-controller-manager.yaml`, for example change the logging level or even just whitespace at the end of the file.
Observe the kubelet kill the controller manager pod, and does not restart it.

**Anything else we need to know**:
If I remove the file from the directory, and then replace the file, kubelet will start it up.

Kubelet logs from the period where I updated the file: https://gist.github.com/dwradcliffe/797d7e8406b0cac5e0e433b456ea1af7

**Comment by yujuhong** [comment]
Did you modify the yaml file using an editor (e.g., vim)? If the editor creates a temporary file in the same directory, kubelet can get confused and thinking that's a new pod (with the same name & namespace). When the temporary file gets removed, kubelet'd inadvertently delete the pod from its cache. Since kubelet relies on inotify for changes, if it doesn't get notified for any new changes from the original yaml file, it'd forever ignore the pod.

There is an issue open to add periodic listing in addition to inotify (introduced in 1.5). This would make sure kubelet *eventually* recover from the situation. I can't find the issue, but there is another one for inotify: #40123. Another fix is to make sure kubelet ignore such known temporary files (it already ignores files starting with `.`).

In general, don't edit the file directly. Copy the file to another place, edit, and copy it back to the manifests directory.

**Comment by andrewsykim** [comment]
I'm seeing a similar problem except I never edited the file, might be fit for a separate issue

**Comment by dwradcliffe** [comment]
Yes I was using vim, and this explanation makes sense. Would be nice if it was smart about it. Would a PR to ignore the vim temp file be acceptable @yujuhong?

**Comment by yujuhong** [comment]
> Yes I was using vim, and this explanation makes sense. Would be nice if it was smart about it. Would a PR to ignore the vim temp file be acceptable @yujuhong?

@dwradcliffe I think it's reasonable. I doubt if anyone uses those file names on purpose.

**Comment by dwradcliffe** [comment]
The dot ignore should have covered the vim temp file too, but it doesn't work because the filename passed in is the absolute filename including the path. So the first character is not a dot.

```
Apr 28 16:05:51 ubuntu-xenial kubelet[4676]: E0428 16:05:51.753616    4676 file_linux.go:113] can't process config file "/etc/kubernetes/manifests/.kube-scheduler.yaml.swp": /etc/kubernetes/manifests/.kube-scheduler.yaml.swp: read 'b0VIM 7.4
Apr 28 16:05:51 ubuntu-xenial kubelet[4676]: E0428 16:05:51.754323    4676 file_linux.go:113] can't process config file "/etc/kubernetes/manifests/.kube-scheduler.yaml.swx": open /etc/kubernetes/manifests/.kube-scheduler.yaml.swx: no such file or directory
Apr 28 16:05:51 ubuntu-xenial kubelet[4676]: E0428 16:05:51.754484    4676 file_linux.go:113] can't process config file "/etc/kubernetes/manifests/.kube-scheduler.yaml.swp": /etc/kubernetes/manifests/.kube-scheduler.yaml.swp: read 'b0VIM 7.4
Apr 28 16:05:51 ubuntu-xenial kubelet[4676]: E0428 16:05:51.754520    4676 file_linux.go:113] can't process config file "/etc/kubernetes/manifests/.kube-scheduler.yaml.swp": /etc/kubernetes/manifests/.kube-scheduler.yaml.swp: read 'b0VIM 7.4
Apr 28 16:05:55 ubuntu-xenial kubelet[4676]: E0428 16:05:55.763534    4676 file_linux.go:113] can't process config file "/etc/kubernetes/manifests/.kube-scheduler.yaml.swp": /etc/kubernetes/manifests/.kube-scheduler.yaml.swp: read 'b0VIM 7.4
```

I'll try to submit a PR fix.

**Comment by dwradcliffe** [comment]
PR submitted https://github.com/kubernetes/kubernetes/issues/45111

**Comment by wavezhang** [comment]
fixed?

**Comment by BruceShenC** [comment]
How to work around? I coudn't start api server when using kubeadm to deploy k8s. Thanks!
