### ISSUE TITLE
Refactoring: consolidate volume util files 

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#44460]
I see:

pkg/volume/util.go
pkg/volume/util/util.go
pkg/volume/util/volumehelper/volumehelper.go

Can we consolidate them all into one?  Or better document what each file is supposed to encompass?

cc @kubernetes/sig-storage-misc

**Comment by badboot** [comment]
FYI, as is often the case, these util methods are encompassing a lot of different functionality.

pkg/volume/util.go - a lot of the POD volume lifecycle (Create/Update/Delete) and associated recycling functionality is added. It looks like a lot of functionality that 'should' be somewhere like volume.go, if that wasn't basically just definitions. 

There are also a number of methods I would call as more clearly 'normal' util methods (RoundUpSize).

pkg/volume/util/util.go -  Looks like mostly code to mount/unmount and utilities that serve that (like checking for file existence, extracting secrets, etc.)

pkg/volume/volumehelper/volumehelper.go - Looks like volume specific functionality, which I am not quite clear on the difference related to the mount functionality. I need to do more research there.

It is definitely a bit confusing what the relationship is here, but there also seems to be quite a bit of overlap.

**Comment by badboot** [comment]
pkg/volume/volumehelper/volumehelper.go, specifically does seem to align with volume plug-in support, which the other utility classes don't. (and doesn't have as much intermixing)

**Comment by jsafrane** [comment]
Feel free to reshuffle the functions into one util directory (or file), there is no smart idea behind the current directory structure. Was `volumehelper` created to break an import cycle? I don't remember any more.

**Comment by msau42** [comment]
I think this is still worth doing. @badboot did you still want to work on it?

**Comment by wackxu** [comment]
@msau42 @jsafrane I want to help do this. After looking at the code, I want to split those file into three parts: common utils, recyclerclient, VolumePathHandler. I will commit my pr asap

**Comment by msau42** [comment]
This has been fixed

/close
