### ISSUE TITLE
API: analyze all "IP" fields and decide if hostname is valid

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#4447]
In some places we expect an IP where a hostname might suffice.  We should make a pass over the API and decide for each case and document/test it properly.  As per #1300 the "must be IP" fields can self-document as net.IP.  The hostname-or-IP fields we can think about decoding tricks.

**Comment by girishkalele** [comment]
I guess this one is still open - #11838 was closed in favor of https://github.com/kubernetes/kubernetes/issues/13748 but that one is also still open.

To summarize my understanding, if an EndpointsAddress entry is added to a service endpoint that  contains a string IP or hostname field, we respond with CNAME records ?
Can CNAME and A records be mixed in a response ? i.e. if the service has both IP and hostname endpoints, can we serve a mixed CNAME and A record response ?

**Comment by thockin** [comment]
#13748 will be worked on by @rata.

You can not mix CNAME and A records, and in fact you can not even have
multiple CNAME records.

Neither of those are what  this one is about, though.  This is about
auditing the API and documenting when a field *must* be an IP (and
adding/tightening validation and tests in those cases) vs when a field may
be an IP or a hostname (and adding/loosening validation and tests in those
cases).

**Comment by kargakis** [comment]
@kubernetes/sig-network-misc
