### ISSUE TITLE
throughput of apiserver

### ISSUE THREAD

**Issue by gp1105739** [kubernetes/kubernetes#44471]
I create a benchmark that sends a batch of "get pods" command to cluster and find that apiserver can only handle 23 command/sec. I want to know if there is any flag can be used to increase the throughput and which part in apiserver is the bottleneck in this case. Thank you.

**Comment by jayunit100** [comment]
`--max-inflight-requests=`

Please close and move to stackoverflow, this is not a real issue but rather a request for help...

**Comment by gp1105739** [comment]
Ohh I see. But it seems that --max-inflight-requests= still doesn't unbottleneck it.
