### ISSUE TITLE
use cephfs-fuse in pv pvc

### ISSUE THREAD

**Issue by bigfreeZhou** [kubernetes/kubernetes#44486]
I found when i use pv/pvc to mount cephfs in pod, k8s use kernel driver to mount cephfs, is there anyway to use cephfs-fuse to mount, thank you.

**Comment by rootfs** [comment]
cephfs fuse doesn't support secret yet, it is not supported at this moment.

**Comment by kargakis** [comment]
Please use our support channels for these kinds of questions

https://groups.google.com/forum/#!forum/kubernetes-users
http://stackoverflow.com/questions/tagged/kubernetes

**Comment by kargakis** [comment]
Or maybe this is a feature request? @kubernetes/sig-storage-feature-requests

**Comment by thockin** [comment]
Until upstream Ceph has it, no need to have this here.

**Comment by rochaporto** [comment]
What exactly is missing in upstream ceph? We use the cephfs fuse client and the secret goes in the config as usual - would be nice to get an option to use the fuse client instead of the kernel one (see #46636 ).

**Comment by kfox1111** [comment]
what is missing? I use fuse cephfs with secrets today.  Would really like to use k8s to manage the pv's rather then resorting to using hostpath.

**Comment by kfox1111** [comment]
looking at the bug filed here: http://tracker.ceph.com/issues/20851, it looks like the desire is to pass the secret in via cli args? That can be a security risk as it shows up in various other places like 'ps ax'. Couldn't a temporary file or some other mechanism be used instead?

**Comment by zhangxiaoyu-zidif** [comment]
@kfox1111 
Agreed.

**Comment by rootfs** [comment]
@kfox1111 You can hide the original keyring by overriding the args, e.g. like how sshpass does.

**Comment by kfox1111** [comment]
its still kind of ugly as there is a period of time, although rather short where it is accessible to outside parties.  The temporary file route is already supported by the client, today I think. So its more secure (slightly), and doesn't need any changes to the ceph code base (preferable for backwards compatibility).

**Comment by rootfs** [comment]
The temporary keyring isn't that secure: if not cleaned, the keyring is exposed. Admittedly, rbd volume has the same issue, but we are going to move away from that model.

**Comment by kfox1111** [comment]
What about a named pipe? pass the keyring info straight through?
