### ISSUE TITLE
federation: federation-controller-manager is restarted during init

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/kubernetes#44490]
After bringing up federation control plane, most of the time we do see that federation-controller-manager pod is restarted like below:
```
root@s70553-HP-EliteBook-840-G2:~/gopath/src/k8s.io/kubernetes# kubectl --namespace=federation-system get pods
NAME                                            READY     STATUS    RESTARTS   AGE
federation-apiserver-832758761-z1k2p            2/2       Running   0          54s
federation-controller-manager-105127570-15bpq   1/1       Running   1          54s
```
Although there is no issues afterwards, this is just causing few seconds delay in federation-controller-manager becoming operational.

cc @kubernetes/sig-federation-bugs

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#128.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
