### ISSUE TITLE
Garbage collector should support non-core APIs

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#44507]
Currently the garbage collector does not handle non-core APIs, like the APIs created via Thirdparty Resource or via the aggregated apiserver.

To support the non-core APIs, Garbage collector needs to:
* dynamically adjust the resources it watches for ([here](https://github.com/kubernetes/kubernetes/blob/v1.6.1/pkg/controller/garbagecollector/garbagecollector.go#L98))
* use a dynamic RESTMapper when translating Kind to Resourse ([here](https://github.com/kubernetes/kubernetes/blob/v1.6.1/pkg/controller/garbagecollector/operations.go#L37))

**Comment by krmayankk** [comment]
@caesarxuchao is this the issue tracking garbage collection for TPR ?

**Comment by ngtuna** [comment]
Same question with @krmayankk This would be really helpful if GC can support TPR :-)

**Comment by nikhita** [comment]
There is a PR (in progress) with a fix here: https://github.com/kubernetes/kubernetes/pull/46000.

**Comment by ngtuna** [comment]
Thanks @nikhita

**Comment by caesarxuchao** [comment]
https://github.com/kubernetes/kubernetes/pull/47665 is addressing the issue.

**Comment by lavalamp** [comment]
Looks like @ironcladlou finished off what I started and this is done. Thanks!!
