### ISSUE TITLE
Deployment tests on 1.4 GKE upgrade suites fail

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#44508]
https://storage.googleapis.com/k8s-gubernator/triage/index.html#19be14db86cdc1fad53e

Fails 3 builds and 30 tests every hour.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1.4-gci-latest-upgrade-master/788

https://k8s-testgrid.appspot.com/google-gke-latest-upgrade#Summary

/assign @liggitt @michelleN @mattfarina 

FYI one way to solve this is to just delete these jobs: https://github.com/kubernetes/test-infra/pull/2489

**Comment by liggitt** [comment]
Seems like this should be assigned to someone under sig-apps with access to GKE

@kubernetes/sig-apps-test-failures @janetkuo @enisoc

**Comment by fejta** [comment]
@liggitt is this the same thing as https://github.com/kubernetes/test-infra/pull/2410?

**Comment by liggitt** [comment]
Not the same. That issue and those tests were specific to kubectl, which has a smaller supported skew policy (one minor version) than kubelet/master (two minor versions)

**Comment by janetkuo** [comment]
Most of Deployment test failed at the cleanup step -- deleting a Deployment and immediately checking if it's gone (expected get deployment returns an error). 

The DELETE operation of a Deployment is now different. It becomes asynchronous and thus caused the failure. 

Shall we just update the 1.4 test to wait for things to be deleted, instead of checking immediately?

**Comment by kargakis** [comment]
I thought we already addressed those as part of https://github.com/kubernetes/kubernetes/issues/42449.

**Comment by janetkuo** [comment]
I think we only fixed 1.5 (by updating 1.5 reaper)

**Comment by liggitt** [comment]
If tests from a previous version had to be changed to pass against the 1.6 API, does that mean we changed the API contract?

**Comment by kargakis** [comment]
Or we poorly planned the tests in our previous versions.

**Comment by janetkuo** [comment]
> does that mean we changed the API contract?

I think so. It's caused by DELETE becoming asynchronous

**Comment by janetkuo** [comment]
Filed #45259

**Comment by janetkuo** [comment]
#45259 was lgtm'ed and pending approval from 1.4 release manager

**Comment by janetkuo** [comment]
Fixed now
