### ISSUE TITLE
Dependency on new namespace not resolved properly on kubectl apply/create

### ISSUE THREAD

**Issue by everett-toews** [kubernetes/kubernetes#44511]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T23:37:53Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"dirty", BuildDate:"2017-04-07T20:46:46Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

```bash
$ minikube version
minikube version: v0.18.0
```

**What happened**:

```bash
$ kubectl apply -f .
namespace "test" created
service "mongo" created
Error from server (NotFound): error when creating "deploy.yaml": namespaces "test" not found
```

**What you expected to happen**:

```bash
$ kubectl apply -f .
namespace "test" created
service "mongo" created
deployment "mongo" created
```

**How to reproduce it** (as minimally and precisely as possible):

```bash
minikube start

mkdir mongo

cat << EOF > mongo/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
EOF

cat << EOF > mongo/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: mongo
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: mongo
  selector:
    name: mongo
EOF

cat << EOF > mongo/deploy.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: test
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:2.6
        ports:
          - name: mongo
            containerPort: 27017
        volumeMounts:
        - name: data-mongo
          mountPath: /data/db
      volumes:
      - name: data-mongo
        hostPath:
          path: /data/mongo
EOF

cd mongo

kubectl apply -f .
```

**Anything else we need to know**:

One could say, just put all of your resources into an "all in one" type manifest. For a trivial example like this, that might be doable but for more complex resources those "all in one" type manifests get very unwieldy. 

One could say, just concatenate all of your manifests on the fly with something like

```bash
cat namespace.yaml <(echo "---") service.yaml <(echo "---") deploy.yaml | kubectl apply -f -
```

To that I say, we shouldn't have to resort to such bash hackery to get the job done.

Also, this is not an endorsement for using NoSQL databases. It just happens to be the example I had on hand. 😄

**Comment by liggitt** [comment]
create the namespace before running `apply`, or sort your input files to put hard dependencies first.

**Comment by everett-toews** [comment]
@liggitt Are you saying that this problem is impossible to solve?

If so, that's unfortunate. If not, please consider reopening this issue.

Both of those options are workarounds and make for a crummy UX. And if you're working with third-party tooling and can't control how/when `apply` is invoked, the workarounds are even worse. I was hoping for a better UX than that (if it's possible).

Perhaps others from @kubernetes/sig-cli-bugs would care to offer an opinion.

**Comment by julianvmodesto** [comment]
Another vote for this issue from me since it's related to wg-app-def.

This problem is similar to Services, which can be addressed w/ explicit service links https://github.com/kubernetes/kubernetes/issues/16448, but in the case of Namespaces, these should probably just be applied first in any bulk `kubectl apply -f [--recursive]` (https://github.com/kubernetes/kubernetes/issues/24649, https://github.com/kubernetes/kubernetes/issues/1905).

**Comment by RochesterinNYC** [comment]
Came across this as well today. Although, in my case, some resources were correctly created in the namespace while one failed out.

```bash
$ kubectl apply -R -f .
configmap "ip-masq-agent" created
namespace "main-system" created
[...]
deployment "something-in-main-system" created
[...]
Error from server (NotFound): error when creating "generated-resources/main-system-environment-configmap.yaml": namespaces "main-system" not found
$ kubectl get namespaces
NAME             STATUS    AGE
default          Active    2m
main-system   Active    28s
$ kubectl create -f generated-resources/main-system-environment-configmap.yaml
configmap "main-system-environment" created
```
(The `something-in-main-system` deployment is successfully deployed to the `main-system` namespace but the `main-system-environment` ConfigMap fails during the initial `kubectl apply -R -f .`).

**Comment by whereismyjetpack** [comment]
I have a very similar issue, 
```
namespace "reboot-coordinator" created
daemonset "container-linux-update-agent" created
clusterrole "reboot-coordinator" created
clusterrolebinding "reboot-coordinator" created
Error from server (NotFound): error when creating "STDIN": namespaces "reboot-coordinator" not found
```
This is from piping the output of another process ala `cat foo | kubectl apply -f -`

**Comment by KyronSr** [comment]
Necroing a very old issue but I hit this same issue today and had to google around to find that it is "working as intended"  I'm certain somebody forgot the principle of least surprise?
