### ISSUE TITLE
Job, Disruption, CronJob, StatefulSet tests fail in upgrade suites

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#44515]
Failure cluster: https://storage.googleapis.com/k8s-gubernator/triage/index.html#f074df9484809efe97f4
Testgrid: https://k8s-testgrid.appspot.com/google-gke-latest-upgrade#gci-1.4-gci-latest-upgrade-master&sort-by-failures=

Failure rates:
* Job - 350/week
* DisruptionController - 50/week
* StatefulSet - 50/week
* CronJob - 36/week

Possibly related: https://github.com/kubernetes/kubernetes/issues/44508

Also note that these tests are mostly failing in suites we intend to delete next week, so approving the PRs in https://github.com/kubernetes/test-infra/issues/2453 is one way to deal with these failures.

/assign @michelleN @mattfarina @janetkuo @erictune

**Comment by kargakis** [comment]
> Possibly related: #44508

No, this is unrelated.

@kubernetes/sig-apps-test-failures

**Comment by kow3ns** [comment]
@fejta The automated upgrade testing for StatefulSet can not possibly pass against a cluster that doesn't have StatefulSet as an API object. This was not a requirement, and thus it was never designed to do so. I'm not sure exactly what you expect to be done here.

**Comment by fejta** [comment]
Expectation is that if we bother to run a suite that the suite passes. 

Possible options:
* fix the test to pass in all suites,
* remove the test from suites it shouldn't run in,
* Remove pointless suites that can't pass or
* Remove this pointless test that can't pass.

**Comment by soltysh** [comment]
> CronJob - 36/week

Weird, there was no cronjobs in 1.4, and scheduledjobs are disabled in cluster < 1.5, see logs:
```
I0412 16:05:15.199]  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduledjob.go:192
I0412 16:05:15.199] 
I0412 16:05:15.199]  Apr 12 16:05:09.617: Not supported for server versions after "1.5.0"
```

Looking into the jobs failure...

**Comment by soltysh** [comment]
For jobs, they are failing b/c [1.4's job.go](https://github.com/kubernetes/kubernetes/blob/release-1.4/test/e2e/job.go#L264-L266) is hitting `extensions/v1beta1` endpoint, which was removed in 1.6 (https://github.com/kubernetes/kubernetes/pull/38614) so these failures are expected.

**Comment by fejta** [comment]
no recent hits
/close
