### ISSUE TITLE
Label selector not supported in kubectl taint

### ISSUE THREAD

**Issue by nimeshksingh** [kubernetes/kubernetes#44522]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): taint, selector

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): MacOS client, linux server
- **Kernel** (e.g. `uname -a`):
- **Install tools**:gcloud
- **Others**:

**What happened**:
I tried to kubectl taint some nodes using a label selector:
kubectl taint nodes -l dedicated=foo dedicated=foo:PreferNoSchedule

and got the error:
error: at least one resource name must be specified since 'all' parameter is not set

**What you expected to happen**:
Those nodes would be tainted with dedicated=foo:PreferNoSchedule.  Trying to use --all along with the selector is also not supported.

**How to reproduce it** (as minimally and precisely as possible):
kubectl taint nodes -l <any label selector> dedicated=foo:PreferNoSchedule

**Anything else we need to know**:

**Comment by jayunit100** [comment]
can you post the output of

kubectl taint nodes -l myLabel=X dedicated=foo:PreferNoSchedule 

(((And first of course Make sure that myLabel is on the cluster ....)))

**Comment by nimeshksingh** [comment]
Would you like me to explicitly use the label "myLabel"?  Otherwise that's the command and output I posted in "What happened" above.  (I had set a label dedicated=foo ahead of time on two nodes.)

**Comment by jayunit100** [comment]
Ah ok so the taint k/v is the exact same as the label k/v, that makes the example tricky to parse but I agree I guess it should work? I can try to reproduce this....

**Comment by nimeshksingh** [comment]
Yup, the same k/v.  (I wanted both labels and taints to determine this set of nodes, and it seemed like it would be confusing to have different k/v's for each.  I kinda thought this would be the common case...)

**Comment by jayunit100** [comment]
Ah , yeah i see it to ... 
```
➜  kubernetes git:(ef2edcc) cluster/kubectl.sh taint nodes --selector='myLabel=x' dedicated=foo:PreferNoSchedule
error: at least one resource name must be specified since 'all' parameter is not set
```
Even though clearly, the selector exists. 
```
➜  kubernetes git:(ef2edcc) cluster/kubectl.sh get nodes --selector='myLabel=x'
NAME        STATUS    AGE       VERSION
127.0.0.1   Ready     3d        v1.7.0-alpha.1.413+ef2edcc94ef07f
```

**Comment by jayunit100** [comment]
@ravisantoshgudimetla Is the taint expert on our team.  

ravi can you look at pkg/kubect/cmd/taint.go, this logic might be shadowing the label selector, such that its impossible to use labels to select the  nodes you're trying to  taint.


```
	// retrieves resource and taint args from args
	// also checks args to verify that all resources are specified before taints
	taintArgs := []string{}
	metTaintArg := false
	for _, s := range args {
		isTaint := strings.Contains(s, "=") || strings.HasSuffix(s, "-")
		switch {
		case !metTaintArg && isTaint:
			metTaintArg = true
			fallthrough
		case metTaintArg && isTaint:
			taintArgs = append(taintArgs, s)
		case !metTaintArg && !isTaint:
			o.resources = append(o.resources, s)
		case metTaintArg && !isTaint:
			return fmt.Errorf("all resources must be specified before taint changes: %s", s)
		}
	}
```

**Comment by jayunit100** [comment]
will cc scheduling-bugs once rg confirms that this is a problem.  i think it is.

**Comment by ravisantoshgudimetla** [comment]
It seems the line  https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/taint.go#L236 is the culprit. Here we are checking for resources if they are > 2, the resources allowed are node,nodes,no so if it needs it has to be > 1 and this check is already available at https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/taint.go#L218. So, I guess its safe to remove that. I tested that functionality after removing this and it fixed the issue. I will submit a PR for this unless someone has objections.
