### ISSUE TITLE
Volume's attachments is None when volume's status is 'attaching'

### ISSUE THREAD

**Issue by FengyunPan** [kubernetes/kubernetes#44536]
### **What happened**:
The event of pod:
---
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  22s		22s		1	{default-scheduler }			Normal		Scheduled	Successfully assigned test2 to da-kk73n6cdy4-0-z5nbegh6ltn6-kube-minion-gka5gie7czuk
  20s		20s		1	{controller-manager }			Warning		FailedMount	Failed to attach volume "v2222222222222" on node "da-kk73n6cdy4-0-z5nbegh6ltn6-kube-minion-gka5gie7czuk" with: volume 09c678bf-2f86-41b1-85c6-92d366a612b9 is not attached to 8574841d-caf1-4283-b27c-0aa926fea5ee
  17s		17s		1	{controller-manager }			Warning		FailedMount	Failed to attach volume "v2222222222222" on node "da-kk73n6cdy4-0-z5nbegh6ltn6-kube-minion-gka5gie7czuk" with: Expected HTTP response code [200] when accessing [POST http://172.20.0.2:8774/v2/035bf9cd68ad41dfa7d57e2a7b9691ca/servers/8574841d-caf1-4283-b27c-0aa926fea5ee/os-volume_attachments], but got 400 instead
{"badRequest": {"message": "Invalid volume: volume '09c678bf-2f86-41b1-85c6-92d366a612b9' status must be 'available'. Currently in 'in-use'", "code": 400}}
  3s	3s	1	{kubelet da-kk73n6cdy4-0-z5nbegh6ltn6-kube-minion-gka5gie7czuk}	spec.containers{busybox}	Normal	Pulled	Container image "172.100.200.208/google_containers/busybox:latest" already present on machine
----
And the log of controllermanager:
----
I0416 03:28:27.392876       1 attacher.go:96] Attach operation successful: volume "7d26405d-2355-4f0a-954e-ae970deba3c2" attached to node "8574841d-caf1-4283-b27c-0aa926fea5ee".
I0416 03:28:27.688517       1 attacher.go:105] Attach volume "7d26405d-2355-4f0a-954e-ae970deba3c2" to instance "8574841d-caf1-4283-b27c-0aa926fea5ee" failed with volume 7d26405d-2355-4f0a-954e-ae970deba3c2 is not attached to 8574841d-caf1-4283-b27c-0aa926fea5ee
----
----
I0416 03:28:28.273078       1 reconciler.go:202] Started AttachVolume for volume "kubernetes.io/cinder/7d26405d-2355-4f0a-954e-ae970deba3c2" to node "da-kk73n6cdy4-0-z5nbegh6ltn6-kube-minion-gka5gie7czuk"
E0416 03:28:31.077823       1 openstack_volumes.go:66] Failed to attach 7d26405d-2355-4f0a-954e-ae970deba3c2 volume to 8574841d-caf1-4283-b27c-0aa926fea5ee compute
I0416 03:28:31.078355       1 attacher.go:98] Attach volume "7d26405d-2355-4f0a-954e-ae970deba3c2" to instance "8574841d-caf1-4283-b27c-0aa926fea5ee" failed with Expected HTTP response code [200] when accessing [POST http://172.20.0.2:8774/v2/035bf9cd68ad41dfa7d57e2a7b9691ca/servers/8574841d-caf1-4283-b27c-0aa926fea5ee/os-volume_attachments], but got 400 instead
{"badRequest": {"message": "Invalid volume: volume '7d26405d-2355-4f0a-954e-ae970deba3c2' status must be 'available'. Currently in 'in-use'", "code": 400}}
----
**What you expected to happen**:
no "Failed xxx" message.
 
**How to reproduce it** (as minimally and precisely as possible):
create a pod which attach a cinder volume

**Anything else we need to know**:
Volume's attachments is None after nova attach volume to vm 
[root@node-1 ~]#  cinder show e3c597d0-f48c-4e60-ad04-56955999aa4b 
+---------------------------------------+--------------------------------------+
|                Property               |                Value                 |
+---------------------------------------+--------------------------------------+
|              attachments              |                  []                  |
|           availability_zone           |                 nova                 |
|                bootable               |                false                 |
|          consistencygroup_id          |                 None                 |
|               created_at              |      2017-04-16T05:32:48.000000      |
|              description              |                 None                 |
|               encrypted               |                False                 |
|                   id                  | e3c597d0-f48c-4e60-ad04-56955999aa4b |
|                metadata               |                  {}                  |
|            migration_status           |                 None                 |
|              multiattach              |                False                 |
|                  name                 |                  p1                  |
|         os-vol-host-attr:host         |           cinder@ceph#ceph           |
|     os-vol-mig-status-attr:migstat    |                 None                 |
|     os-vol-mig-status-attr:name_id    |                 None                 |
|      os-vol-tenant-attr:tenant_id     |   035bf9cd68ad41dfa7d57e2a7b9691ca   |
|   os-volume-replication:driver_data   |                 None                 |
| os-volume-replication:extended_status |                 None                 |
|           replication_status          |               disabled               |
|                  size                 |                  1                   |
|              snapshot_id              |                 None                 |
|              source_volid             |                 None                 |
|                 status                |              available               |
|                user_id                |   9be887b61d794482bee9af2306440418   |
|              volume_type              |                 None                 |
+---------------------------------------+--------------------------------------+
[root@node-1 ~]#  nova volume-attach 8574841d-caf1-4283-b27c-0aa926fea5ee e3c597d0-f48c-4e60-ad04-56955999aa4b; cinder show e3c597d0-f48c-4e60-ad04-56955999aa4b
+----------+--------------------------------------+
| Property | Value                                |
+----------+--------------------------------------+
| device   | /dev/vdi                             |
| id       | e3c597d0-f48c-4e60-ad04-56955999aa4b |
| serverId | 8574841d-caf1-4283-b27c-0aa926fea5ee |
| volumeId | e3c597d0-f48c-4e60-ad04-56955999aa4b |
+----------+--------------------------------------+
+---------------------------------------+--------------------------------------+
|                Property               |                Value                 |
+---------------------------------------+--------------------------------------+
|              attachments              |                  []                  |
|           availability_zone           |                 nova                 |
|                bootable               |                false                 |
|          consistencygroup_id          |                 None                 |
|               created_at              |      2017-04-16T05:32:48.000000      |
|              description              |                 None                 |
|               encrypted               |                False                 |
|                   id                  | e3c597d0-f48c-4e60-ad04-56955999aa4b |
|                metadata               |                  {}                  |
|            migration_status           |                 None                 |
|              multiattach              |                False                 |
|                  name                 |                  p1                  |
|         os-vol-host-attr:host         |           cinder@ceph#ceph           |
|     os-vol-mig-status-attr:migstat    |                 None                 |
|     os-vol-mig-status-attr:name_id    |                 None                 |
|      os-vol-tenant-attr:tenant_id     |   035bf9cd68ad41dfa7d57e2a7b9691ca   |
|   os-volume-replication:driver_data   |                 None                 |
| os-volume-replication:extended_status |                 None                 |
|           replication_status          |               disabled               |
|                  size                 |                  1                   |
|              snapshot_id              |                 None                 |
|              source_volid             |                 None                 |
|                 status                |              attaching               |
|                user_id                |   9be887b61d794482bee9af2306440418   |
|              volume_type              |                 None                 |
+---------------------------------------+--------------------------------------+
[root@node-1 ~]#  cinder show e3c597d0-f48c-4e60-ad04-56955999aa4b  
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                Property               |                                                                                                                                  Value                                                                                                                                  |
+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|              attachments              | [{u'server_id': u'8574841d-caf1-4283-b27c-0aa926fea5ee', u'attachment_id': u'e5bde9f2-8651-4ab9-a828-5c54405ae5bd', u'host_name': None, u'volume_id': u'e3c597d0-f48c-4e60-ad04-56955999aa4b', u'device': u'/dev/vdi', u'id': u'e3c597d0-f48c-4e60-ad04-56955999aa4b'}] |

-------------------------
I get the attachments of volume twice, the first value is diffrent from the second value.
when the status of volume is 'attaching', the attachments of volume is "".

**Comment by xsgordon** [comment]
/cc @k8s-sig-openstack-bugs @k8s-mirror-storage-bugs 

@idvoretskyi can we get the sig/openstack and sig/storage labels here?
