### ISSUE TITLE
Resource Quota doesn't persist/return GenerateName

### ISSUE THREAD

**Issue by radeksimko** [kubernetes/kubernetes#44539]
**Kubernetes version** (use `kubectl version`): Latest

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T23:37:53Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.2604+b22a298009ec79", GitCommit:"b22a298009ec79e7f681ac2ae8070bbcc6fffcd1", GitTreeState:"clean", BuildDate:"2017-04-15T18:41:18Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

It's likely a bug in the API affecting all environments, but I found this while interacting with GKE.

**What happened**:

After submitting new resource quota with generated name, the resource quota was (correctly) created, but then it didn't return the `generateName` attribute back from the API.

**What you expected to happen**:

Persist & return the `generateName` attribute from the API for any Resource Quota which has this attribute set.

**How to reproduce it** (as minimally and precisely as possible):

**`rq.yaml`**
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  generateName: "myprefix-"
spec:
  hard:
    cpu: "20"
    memory: 1Gi
    pods: "10"
    replicationcontrollers: "20"
    resourcequotas: "1"
    services: "5"
```
```sh
$ kubectl create -f rq.yaml
resourcequota "myprefix-hq2v4" created
$ kubectl get resourcequota myprefix-hq2v4 -o=yaml
```
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: 2017-04-16T10:15:09Z
  name: myprefix-hq2v4
  namespace: default
  resourceVersion: "88928"
  selfLink: /api/v1/namespaces/default/resourcequotas/myprefix-hq2v4
  uid: 92598458-228d-11e7-b6c1-42010a800002
spec:
  hard:
    cpu: "20"
    memory: 1Gi
    pods: "10"
    replicationcontrollers: "20"
    resourcequotas: "1"
    services: "5"
status:
  hard:
    cpu: "20"
    memory: 1Gi
    pods: "10"
    replicationcontrollers: "20"
    resourcequotas: "1"
    services: "5"
  used:
    cpu: "0"
    memory: "0"
    pods: "0"
    replicationcontrollers: "0"
    resourcequotas: "1"
    services: "1"
```

Here's also a repro case in a form of a failing E2E test:
https://github.com/kubernetes/kubernetes/commit/246233597d4f9499a25914ed8fe17335cb56d9aa

```
• Failure [25.529 seconds]
[k8s.io] ResourceQuota
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:656
  should create a ResourceQuota and return generated name. [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/resource_quota.go:559

  Expected
      <string>:
  to equal
      <string>: test-quota-with-prefix-

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/resource_quota.go:558
```

**Anything else we need to know**:

I checked other resources, specifically Config Map & Pod and they both seem to persist and return the `generateName` attribute, so I'm assuming this behaviour is not by design.

**Comment by xingzhou** [comment]
The same behavior in `kubectl edit`, I can take some investigation first.

**Comment by liggitt** [comment]
the generateName is not significant after the initial creation.

**Comment by radeksimko** [comment]
@liggitt It is apparently significant for many other resources - at least significant enough that it's persisted & returned back from the API, unlike for resource quota. This is at the very least inconsistent behaviour.

I'm working on [K8S provider](https://www.terraform.io/docs/providers/kubernetes/) for [Terraform](https://github.com/hashicorp/terraform) and this is causing us some troubles there.

As Terraform is responsible for the full lifecycle of the resource (which may potentially include recreation from scratch) it's very useful (if not necessary) to know exactly how the resource was created initially. Terraform also has the ability to import existing resources which were created prior to their codification and knowing the difference between generated name and a static one is certainly useful in that context.

There's a difference between between recreating resource which has a static name (we'd recreate it under the exact same name) and generated one (we'd recreate it under a new generated name).

I hope the context & explanation make some sense.

----

I'm certainly not suggesting this is a top priority bug, but I insist it is a bug worth fixing.

I'm also willing send a PR with bugfix, but I'm unfamiliar with the codebase, so I'd appreciate some pointers to where (roughly) this is likely going to need to be fixed.

**Comment by liggitt** [comment]
Any solution that is expecting to apply idempotent create operations should not use generateName...

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by mbohlool** [comment]
Look like this is not api-machinery but we also don't think this is a bug. generatedName is a hint for creating the object. After the object is created, name is the source of the truth.

**Comment by radeksimko** [comment]
@mbohlool I would disagree. As I mentioned above all other resources do persist this field, so either these are buggy or resource quota is. It's certainly not consistent, hence I believe it's a bug.

Do you mind reopening this issue, please?

**Comment by mbohlool** [comment]
OK. I can re-open the issue. But this is not api-machinery for sure. We do not control the content of the API. Please find the right sig to take care of this.

**Comment by smarterclayton** [comment]
Quota is split between sig-node and sig-api-machinery and sig-scheduling.
I don't really care who fixes it, but it's definitely inconsistent for it
to be persisted differently.

**Comment by radeksimko** [comment]
To my knowledge this is still a bug that is worth fixing.

I do understand the motivation behind closing stale feature requests, but bugs should not be forgotten about, IMO?

/remove-lifecycle rotten

**Comment by liggitt** [comment]
fixed in https://github.com/kubernetes/kubernetes/pull/70035
