### ISSUE TITLE
how to update  pod-template-hash label of a replicaset?

### ISSUE THREAD

**Issue by frozenxia** [kubernetes/kubernetes#44538]
I want to update the pod-template-hash label of a specific replicaset created by deployment, is it possible ? if so ,then how ?

**Comment by kargakis** [comment]
Why do you want to do that? You shouldn't mutate ReplicaSets managed by Deployments.

**Comment by takahser** [comment]
I was reading the docs on kubernetes deployments [1] and understand, that all pods that are created from the same template will be labeled with the same `pod-template-hash`.

I'm interested to know more about how this happens:

- who will add the labels: the deployment or the replica set?
- why does changing the deployment template and using the `kubectl apply` command not change the `pod-template-hash`, but deleting and creating the deployment does?
- what function is used to generate the hash from the template?

Additional info: I played around and figured out, that deleting a deployment and creating it again using `kubectl create -f config.yaml` will result in the same hash value for the same deployment. When I change the `config.yaml` (I simple added a label for testing), delete the deployment and create it again, a new hash value is generated. When reverting the changes and using `kubectl apply -f config.yaml`, the hash value wouldn't be changed. Finally, when deleting and creating the deployment again (using the original config) it fill generate the original hash again.

[1] https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

**Comment by kargakis** [comment]
@takahser thanks for your detailed comment, I have opened https://github.com/kubernetes/kubernetes.github.io/issues/3569 where I am going to address all of your questions.

**Comment by akostadinov** [comment]
The question is how does one know which `ReplicaSets` are owned by a particular `Deployment`. Sure one can generate pod template hash but seems like hashing function can change over time.

Given a `Deployment` how would I find out the last/current ReplicaSet associated with it?

**Comment by janetkuo** [comment]
@akostadinov you can find a Deployment's ReplicaSets from `kubectl describe deploy/<name>` or `kubectl get rs -l <key>=<value>` (use the Deployment's label selector to filter by labels). 

If you want to find the current RS, look for the one with the same value of annotation `deployment.kubernetes.io/revision` as the Deployment. 

Why do you want to find the current RS? If you just want to check the rollout status of a Deployment, checking its [status.conditions](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#deployment-status) should be enough.

**Comment by akostadinov** [comment]
Thanks a lot, @janetkuo ! It is for testing purposes. Also can be useful in scripts to find out orphaned replica sets.

**Comment by kargakis** [comment]
> The question is how does one know which ReplicaSets are owned by a particular Deployment. 

@akostadinov ReplicaSets owned by Deployments have owner references in their metadata since 1.6 I think.

**Comment by kargakis** [comment]
The only way you can identify an orphaned ReplicaSet at the moment is to observe that it 1. has no owner reference, 2. has a pod-template-hash label.
