### ISSUE TITLE
Don't skip TLS verification in Vagrant provision-utils

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#44542]
Especially given that it's using token auth.

https://github.com/kubernetes/kubernetes/blob/b09b20b5987510ac183eb35dde0b658cc36947af/cluster/vagrant/provision-utils.sh#L181
https://github.com/kubernetes/kubernetes/blob/b09b20b5987510ac183eb35dde0b658cc36947af/cluster/vagrant/provision-utils.sh#L206

**Comment by zhouhaibing089** [comment]
token auth itself is not related with TLS stuff, if `insecure-skip-tls-verify` is false, then we need to supply the `certificate-authority-data` which presents the CA.

**Comment by liggitt** [comment]
skipping TLS verification is worse when using token auth, since a mitm attack could steal the credentials. =

**Comment by zhouhaibing089** [comment]
ah, ok, I see the point now.

**Comment by jagosan** [comment]
@mtaufen please add sig label. Thanks!
