### ISSUE TITLE
Complete help for kubectl top command when heapster is not in kube-system namespace

### ISSUE THREAD

**Issue by kartoch** [kubernetes/kubernetes#44540]
**Is this a request for help?**: No

**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

After switching heapster from kube-admin to monitoring namespace:

```
$ kubectl top node
Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)
$ kubectl top pod
Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)
```

Using `--namespace` does not work either:

```
$ kubectl top pod --namespace=monitoring
W0416 17:58:15.174555    1159 top_pod.go:190] Metrics not available for pod monitoring/grafana-2017641066-rlq7c, age: 26m33.174541702s
error: Metrics not available for pod monitoring/grafana-2017641066-rlq7c, age: 26m33.174541702s
$ kubectl top node --namespace=monitoring                                                                         [17:58:36]
Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)
```

**Kubernetes version**: 1.6.1
**Environment**:
- **Cloud provider or hardware configuration**: bare-metal
- **OS** : ubuntu 16.04
- **Kernel** : Linux vps343998 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubeadm 1.6.1

**Comment by kartoch** [comment]
After investigation, it exists several options not documented in help command of `kubectl top`, as described in the source code here: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/top_node.go#L53

Maybe add this flags to the help description ?

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by vielmetti** [comment]
I think this can be closed, since `kubectl top node --help` provides the requested information.

**Comment by so0k** [comment]
in my case it was version mismatch between kubectl client and api server (I had a newer client)

using the correct version of the client solved the error mentioned (for those who got here after searching google for the error message)

**Comment by abushoeb** [comment]
Hey, I'm using k8 1.7 and running hepaster. When I run $ kubectl top nodes --heapster-namespace=kube-system, it shows me "error: metrics not available yet". Any clue for tackling the error?

**Comment by abushoeb** [comment]
@xmik thanks for the help. Is there a way to get GPU usage information?

**Comment by lenhattan86** [comment]
I got the same issue with Kubernetes 1.11 & latest Heapster.

$kubectl top pod --namespace=kube-system
W0813 13:48:08.426536   27831 top_pod.go:263] Metrics not available for pod kube-system/calico-node-8d5d4, age: 38m1.426522624s
error: Metrics not available for pod kube-system/calico-node-8d5d4, age: 38m1.426522624s

**Comment by Zwordi** [comment]
Hi,
I have the same behavior even if heapster is on the kube-system namespaces.
What i don't understand it's why even if it's an deprecated project replace by metrics-server do we still need to find an heapster service on the cluster...

Regards,

**Comment by gdoctor** [comment]
Any update from anyone in the metrics-server community? Heapster is deprecated as mentioned above, yet the metrics-server commands are still asking for a heapster server. @DirectXMan12 @piosz

**Comment by s1113950** [comment]
When `error: metrics not available yet` happened to me it ended up being an error with the metrics deployment itself. I did a `kubectl get pods -n kube-system`, found the metrics pod and a `kubectl describe pod...` helped me diagnose why the deployment wouldn't work. 

I had to patch this default metrics-server deployment:
https://raw.githubusercontent.com/kubernetes/kops/master/addons/metrics-server/v1.8.x.yaml
with these changes:
```
containers:
        - name: metrics-server
          image: gcr.io/google_containers/metrics-server-amd64:v0.3.0
          imagePullPolicy: Always
          command:
            - /metrics-server
            - --kubelet-preferred-address-types=InternalIP
            # - --source=kubernetes.summary_api:''
```
And that got things working for me.

**Comment by DirectXMan12** [comment]
@gdoctor these days, the only reason it should ask about Heapster is if the resource metrics API isn't available.  The `kubectl top` logic prefers using the resource metrics API, but will fall back to Heapster if it isn't present (to give people time to upgrade clusters and clients), which means if neither are working, you'll see an error about Heapster.

@s1113950 that kops manifest appears to be out of date/not actually tests.  v0.3.0 changed how the options are specified, so it makes sense that you needed to make that change.  Please file an issue with the kops repository.

**Comment by shaikkhaja5628** [comment]
Hi All
I am facing the same issue on with kubectl top pod command with above 1.10 version also
root@:/home# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

Getting the below error:
Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)

can anyone help me out this

**Comment by Armax** [comment]
> Hi All
> I am facing the same issue on with kubectl top pod command with above 1.10 version also
> root@:/home# kubectl version
> Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
> 
> Getting the below error:
> Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)
> 
> can anyone help me out this

Same problem here, using kubernetes 1.11 on digitalocean

**Comment by talishte** [comment]
Same problem using kubernetes v1.12.2

**Comment by DirectXMan12** [comment]
please make sure you've deployed metrics-server and have the `metrics.k8s.io` API correctly registered (check `kubectl get apiservices`)

**Comment by jorge-fans** [comment]
I know this `--kubelet-insecure-tls` will make it work. but is important to note that this is useful in test clusters with self-signed Kubelet serving certificates but is not recommended for production usage

**Comment by kainwei** [comment]
For me, the problem is I didn't install the metric server and installing metric server is worked for me:

$ git clone https://github.com/kodekloudhub/kubernetes-metrics-server.git
$ kubectl create -f kubernetes-metrics-server/

reference from : https://stackoverflow.com/questions/52860209/kubernetes-1-11-could-not-find-heapster-for-metrics

hope it can helps.

**Comment by bbhupati** [comment]
Thanks lot Kaniwei, its worked for me

**Comment by diegoxro** [comment]
> 
> 
> For me, the problem is I didn't install the metric server and installing metric server is worked for me:
> 
> `$ git clone https://github.com/kodekloudhub/kubernetes-metrics-server.git`
> `$ kubectl create -f kubernetes-metrics-server/`
> 
> reference from : https://stackoverflow.com/questions/52860209/kubernetes-1-11-could-not-find-heapster-for-metrics
> 
> hope it can helps.

this was the only solution for me thanks

**Comment by alexsandro-xpt** [comment]
I have same issue in Digital Ocean.

**Comment by josejayesh** [comment]
@alexsandro-xpt  have you tried installing metric server as suggested by @kainwei , It worked for me

**Comment by jerryzhyliu** [comment]
**Still have the issue...** 

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

[root@k8smaster ~]# kubectl create -f kubernetes-metrics-server/
clusterrole.rbac.authorization.k8s.io/system:aggregated-metrics-reader created
clusterrolebinding.rbac.authorization.k8s.io/metrics-server:system:auth-delegator created
rolebinding.rbac.authorization.k8s.io/metrics-server-auth-reader created
apiservice.apiregistration.k8s.io/v1beta1.metrics.k8s.io created
serviceaccount/metrics-server created
deployment.apps/metrics-server created
service/metrics-server created
clusterrole.rbac.authorization.k8s.io/system:metrics-server created
clusterrolebinding.rbac.authorization.k8s.io/system:metrics-server created
[root@k8smaster ~]# kubectl top nodes
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)
[root@k8smaster ~]# kubectl top pods
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get pods.metrics.k8s.io)
