### ISSUE TITLE
can not find livenessprobe result in podstatus or get livenessprobe result by kubelet rest api.

### ISSUE THREAD

**Issue by helinbo2015** [kubernetes/kubernetes#44546]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

by the [task example](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#defining-a-liveness-command), i made a livenessprobe exercise.   
and the result as expected in the following:   
- the unhealthy container is killed and restarted.  
- a liveness probe failed event produced.  

in my system, i want to check the pod's healthy status(liveness probe result) before i can send specfic request to the app in the pod. if the pod's status is healthy,  i can send specific request. and if unhealthy, i will not send request.  
**so how can i get the liveness probe result?**  
Anybody can  help me. Thanks a lot.

**Kubernetes version** (use `kubectl version`): 1.6.1

**Environment**:
- **Cloud provider or hardware configuration**: Openstack env
- **OS** (e.g. from /etc/os-release): ubuntu 14.04
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**Comment by kargakis** [comment]
@kubernetes/sig-node-feature-requests

**Comment by resouer** [comment]
Just curious why monitoring pod status is not enough? I mean, pod will transfer to RUNNING unless liveness probe success I think.

**Comment by yujuhong** [comment]
I think you can use readiness probe for this purpose. The container will not be ready if it fails. 
Closing this issue due to age. If you have more specific request, feel free to elaborate and reopen the issue.

**Comment by cpoole** [comment]
I would like to re-open this as well. In our case we have pods that will boot up and be in an initialization state but not yet be ready.

This initialization state can take up to a minute or more. I'd our controllers to be aware if the pod has successfully started and is passing liveness checks so that it can start modifying external resources. It would be beneficial to distinguish between liveness and readiness
