### ISSUE TITLE
Influxdb is using 1 core on 4 core cluster

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#4455]
For a clean, empty cluster with 4 1-core nodes, 1 core (i.e. 1 machine cpu-wise) is used by influxdb. This is really high! It is particularly bad if a container is scheduled on that node.

**Comment by thockin** [comment]
@vishh

**Comment by vishh** [comment]
To mitigate this issue, you can place resource restriction on InfluxDB
container or disable monitoring. The reason why default limits don't exist
is because, InfluxDB's performance is very poor when it is restricted to
less than a core and the default machine size for Kubernetes on GCE is 1
core VM.
Let me know if I can help you place resource restrictions or disable
monitoring.

**Comment by thockin** [comment]
It burns a whole core continuously?  Yikes.

**Comment by rroopreddy** [comment]
Same thing here, on a 2-core machine influxDB uses 1.25 cores consistently. 
![2015-10-12 at 5 56 17 pm](https://cloud.githubusercontent.com/assets/523806/10446744/d742a128-7132-11e5-9b79-7a812d71323a.png)

**Comment by vishh** [comment]
You can place resource limits on InfluxDB.

**Comment by derekwaynecarr** [comment]
@rroopreddy - the limits are enforced if you start the kubelet with the ```--cpu-cfs-quota``` flag to true.  it is disabled by default on the GCE provider.  I am aware of no other means to enforce limits on that environment.

**Comment by vishh** [comment]
Ah yes! If you place cpu limits the usage should drop under contention. BTW
to get good performance out of InfluxDB, you should give it at-least 4
cores and 8GB. If you are running a test cluster, you can disable
monitoring completely.

**Comment by rroopreddy** [comment]
Seems like pods are killed and only some restarted on machine where influxDB running. See StackOverflow [here](http://stackoverflow.com/questions/33068639/kubernetes-pods-some-die-after-running-for-a-day)

I noticed that these pods are on machine where *influxdb* is running (this process has high cpu usage). **There were 5 pods before and only 2 new ones with replication controller came back  now** (fluentd-elasticsearch, spark-worker-controller) other 3 pods - influxdb and 2 directly run ones did not

I can disable monitoring however would be good to know what happened on this node. Where would I look for this info in logs?

**Comment by vishh** [comment]
On Wed, Oct 14, 2015 at 8:02 AM, Ravindar Reddy <notifications@github.com>
wrote:

> Seems like pods are killed and only some restarted on machine where
> influxDB running. See StackOverflow here
> <http://stackoverflow.com/questions/33068639/kubernetes-pods-some-die-after-running-for-a-day>
>
> I noticed that these pods are on machine where *influxdb* is running
> (this process has high cpu usage). *There were 5 pods before and only 2
> new ones with replication controller came back now*
> (fluentd-elasticsearch, spark-worker-controller) other 3 pods - influxdb
> and 2 directly run ones did not
>
Pods are not immortal. Unless you set an appropriate restart policy, pods
will disappear.
Replication Controllers are meant to handle this situation. When a new pod
is created to replace a dead pod, the new pod can either be scheduled on
the same node or on a different node.

> I can disable monitoring however would be good to know what happened on
> this node. Where would I look for this info in logs?
>
You can set env `ENABLE_CLUSTER_MONITORING=none` while running
 `kube-up.sh` to disable monitoring.
Instead on an existing cluster, you can try running the following commands
on the master:
`kubectl delete -f /etc/kubernetes/addons/cluster_monitoring/influxdb/`
`mv /etc/kubernetes/addons/cluster_monitoring /tmp`

**Comment by rroopreddy** [comment]
Documentation says "If RestartPolicy is not set, the default value is Always". In this case RestartPolicy is not explicitly set, should it not have started automatically?

**Comment by vishh** [comment]
Can you post the output of `kubectl describe pods --all-namespaces`? If
those pods were not deleted, it should show up in the output.

**Comment by rroopreddy** [comment]
Hi @vishh - using kubectl.sh and "--all-namespaces" is not an option. However, I dumped the details of one of the pod that died which **I have to restart manually*. Please notice the **'restartPolicy: Always** as default without me specifying it. When it dies there is no trace that it was running before

>>./cluster/kubectl.sh get pods -l name=spark-driver -o yaml


        apiVersion: v1
        items:
        - apiVersion: v1
          kind: Pod
          metadata:
            creationTimestamp: 2015-10-14T18:39:55Z
            labels:
              name: spark-driver
            name: spark-driver
            namespace: default
            resourceVersion: "87783"
            selfLink: /api/v1/namespaces/default/pods/spark-driver
            uid: f6b0b62c-72a2-11e5-b454-02d83ada7bd1
          spec:
            containers:
            - image: test/spark-driver
              imagePullPolicy: IfNotPresent
              name: spark-driver
              resources:
                limits:
                  cpu: 300m
              terminationMessagePath: /dev/termination-log
              volumeMounts:
              - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
                name: default-token-62wew
                readOnly: true
            dnsPolicy: ClusterFirst
            imagePullSecrets:
            - name: dockerhubkey
            nodeName: ip-xxx-xx-x-xx.us-west-2.compute.internal
            restartPolicy: Always
            serviceAccount: default
            serviceAccountName: default
            volumes:
            - name: default-token-62wew
              secret:
                secretName: default-token-62wew
          status:
            conditions:
            - status: "True"
              type: Ready
            containerStatuses:
            - containerID: docker://9b72caf4301e8833e4e5829af456fdc852e84a13d326ad10ccb25226cebeb5f0
              image: test/spark-driver
              imageID: docker://33203d0d79fbe3f6b3fcbee79b34ebdbb7974ea1050d87f41c096a8ec8effab2
              lastState: {}
              name: spark-driver
              ready: true
              restartCount: 0
              state:
                running:
                  startedAt: 2015-10-14T18:39:55Z
            hostIP: 172.20.0.15
            phase: Running
            podIP: 10.244.0.9
            startTime: 2015-10-14T18:39:55Z
        kind: List
        metadata: {}

**Comment by vishh** [comment]
I'd recommend creating a separate issue for the pod restart behavior. I'd
be curious to see the output of describe when the pod dies (and never
restarts) again.

**Comment by antoineco** [comment]
@vishh: The default CPU limits set for the monitoring add-on are not realistic in general. These defaults should be increased or better determined when `kube-up` is invoked.

The CPU usage of the components involved in monitoring a cluster running 50 pods on 4 nodes is presented below.

---

**InfluxDB** (300 mC) - idle at 600% :exclamation: 

<img src="https://cloud.githubusercontent.com/assets/3299086/11956460/a3d3ca78-a8ba-11e5-8ed3-68775916ef29.png" height="200">

---

**Heapster** (100 mC) - idle at 70%

<img src="https://cloud.githubusercontent.com/assets/3299086/11956577/93f98f42-a8bb-11e5-85fc-539c9ee3924b.png" height="200">

---

This is a different subject but the same holds true for memory limits. The default value of 200Mi for InfluxDB is too low. 500-600Mi should be a more decent default, from what I've observed over these last 4 months running k8s.

**Comment by vishh** [comment]
For v1.1, heapster limits were dynamically updated based on cluster size.
AFAIK, there is an issue open to update resource limits even after cluster
bootup, for example when nodes are added or removed.

**Comment by antoineco** [comment]
Heapter's **memory** limit is determined automatically, the CPU limit is always 100m. This value is OK, but 100m CPU (and 200Mi memory) for InfluxDB is wildly unrealistic, which was the original topic of this issue.

**Comment by vishh** [comment]
@antoineco: What is the size of your cluster?

**Comment by antoineco** [comment]
> 50 pods on 4 nodes

**Comment by antoineco** [comment]
See my proposal #19020
