### ISSUE TITLE
components (e.g. kubelet) can wedge for multiple minutes in certain load-balancer scenarios

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#44557]
We have a setup with a load balancer sitting in front of the apiservers. We noticed that if one of the apiservers goes down, it's possible for the kubelet (or other components) to get stuck trying to talk to the apiserver. In this particular case, the kubelet was trying to send a status update, and because it got stuck, the node controller marked the node NotReady for about 15 minutes, until presumably the load balancer gave up and closed the connection, allowing another attempt to go through.

I'm guessing this is what happened:

1. apiserver X goes down
1. load balancer is configured to wait N seconds before it takes the backend out of rotation
1. kubelet connects to load balancer to set node status update before N seconds have elapsed
1. load balancer attempts to proxy the kubelet's request to apiserver X
1. kubelet's request hangs:

```
goroutine 449 [select, 3 minutes]:
net/http.(*persistConn).roundTrip(0xc421dadb00, 0xc421ab7960, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:1840 +0x93b
net/http.(*Transport).RoundTrip(0xc4202b2e10, 0xc4229313b0, 0xa, 0xc420c7bdc0, 0x39)
        /usr/lib/golang/src/net/http/transport.go:380 +0x4ee
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/transport.(*userAgentRoundTripper).RoundTrip(0xc420a99ec0, 0xc4229313b0, 0xc420a99ec0, 0x0, 0x0)
        /builddir/build/BUILD/atomic-openshift-git-0.81b9a4a/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/transport/round_trippers.go:92 +0x10c
net/http.send(0xc422930ff0, 0x69bbde0, 0xc420a99ec0, 0x0, 0x0, 0x0, 0x8, 0xc421d705a8, 0x4137c8)
        /usr/lib/golang/src/net/http/client.go:256 +0x15f
net/http.(*Client).send(0xc4204212f0, 0xc422930ff0, 0x0, 0x0, 0x0, 0xc421d705a8, 0x0, 0x1)
        /usr/lib/golang/src/net/http/client.go:146 +0x102
net/http.(*Client).doFollowingRedirects(0xc4204212f0, 0xc422930ff0, 0x48b9b68, 0x3, 0x1, 0x0)
        /usr/lib/golang/src/net/http/client.go:528 +0x5e5
net/http.(*Client).Do(0xc4204212f0, 0xc422930ff0, 0x0, 0x5d, 0x69a51e0)
        /usr/lib/golang/src/net/http/client.go:187 +0x11d
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/restclient.(*Request).request(0xc421a47ba0, 0xc422d07b08, 0x0, 0x0)
        /builddir/build/BUILD/atomic-openshift-git-0.81b9a4a/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/restclient/request.go:809 +0x24d
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/restclient.(*Request).Do(0xc421a47ba0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /builddir/build/BUILD/atomic-openshift-git-0.81b9a4a/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/restclient/request.go:870 +0xb7
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/core/unversioned.(*nodes).UpdateStatus(0xc421d70580, 0xc421600000, 0xc421d70580, 0x0, 0x0)
        /builddir/build/BUILD/atomic-openshift-git-0.81b9a4a/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/core/unversioned/node.go:86 +0x13b
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).tryUpdateNodeStatus(0xc420c98a00, 0xc421e0eee8, 0x2)
        /builddir/build/BUILD/atomic-openshift-git-0.81b9a4a/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:366 +0x172
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).updateNodeStatus(0xc420c98a00, 0x4d5570, 0xc421e0ee60)
        /builddir/build/BUILD/atomic-openshift-git-0.81b9a4a/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:323 +0x48
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncNodeStatus(0xc420c98a00)
        /builddir/build/BUILD/atomic-openshift-git-0.81b9a4a/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:315 +0x4e
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).(github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet.syncNodeStatus)-fm()
        /builddir/build/BUILD/atomic-openshift-git-0.81b9a4a/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1173 +0x2a
```

We are working with to try to update the load balancer configuration so it doesn't have to wait for all the various timeouts to expire on all the hops before trying another backend....

However, I wonder if it would make sense to consider setting `ResponseHeaderTimeout` in the `http.Transport` instances we use so we could short-circuit situations such as this one. @liggitt pointed out that in the past we may have had some operations where the response headers weren't written until the first byte of the response, which could take a while (e.g. container logs, which I think has been fixed). If we decide to set `ResponseHeaderTimeout` to something non-zero, we'll need to make sure that all long-running requests write at least something early to avoid timing out waiting for response headers.

WDYT?

cc @kubernetes/sig-api-machinery-misc @kubernetes/sig-node-bugs @smarterclayton @sttts @deads2k @lavalamp @caesarxuchao @dchen1107 @yujuhong @derekwaynecarr @marun @kubernetes/rh-cluster-infra @timothysc @wojtek-t @gmarek @thockin

**Comment by timothysc** [comment]
Does the LB have a health check enabled for the endpoint?  This should take it out of the list servers and break the connections.    http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-healthchecks.html

**Comment by ncdc** [comment]
@timothysc it's not an ELB, but yes. We're working on fixing the configuration of the LB, but I wanted to open this issue as well to see if we wanted to tackle this from within the Kubernetes code too.

**Comment by timothysc** [comment]
https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/

**Comment by thockin** [comment]
Having timeout-and-retry loops in the client seems pretty
straightforward,no?

On Mon, Apr 17, 2017 at 8:25 AM, Timothy St. Clair <notifications@github.com

**Comment by ncdc** [comment]
@thockin I'm hoping it will be. The current issue is that we're getting stuck inside `net/http`, but if we used a context WithTimeout or set the appropriate `net/http` timeout variables correctly, it should be relatively straightforward.

**Comment by sjenning** [comment]
Any movement on this?

It seems that we should definitely be setting this timeout below the node controller's grace period such that the kubelet has at least one chance to reestablish a connection with the master before it gets marked as NotReady by the node controller, right?

So between kubelet `node-status-update-frequency` (default 10s) and node controller `node-monitor-grace-period duration` (default 40s).  It is a somewhat tight window.

**Comment by mml** [comment]
@ncdc is this substantially different than #48638?  Can this be closed?

**Comment by ncdc** [comment]
It's the same. 48638 should have been closed as a dupe of this.
