### ISSUE TITLE
kubeadm init  Stuck at Temporarily unable to list nodes (will retry) on Centos 7

### ISSUE THREAD

**Issue by rachit1arora** [kubernetes/kubernetes#44551]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

This issue is related to https://github.com/kubernetes/kubernetes/issues/33729
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

kubeadm version
kubeadm version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
VM , 4 Core , 16 GB Ram
- **OS** (e.g. from /etc/os-release):
cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
- **Kernel** (e.g. `uname -a`):
uname -a
Linux  3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
kubeadm
- **Others**:

**What happened**:
If i try to do 
kubeadm init

This keep looping around "[apiclient] Temporarily unable to list nodes (will retry) "

[certificates] Generated API server kubelet client certificate and key.
[certificates] Generated service account token signing key and public key.
[certificates] Generated front-proxy CA certificate and key.
[certificates] Generated front-proxy client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/scheduler.conf"
[apiclient] Created API client, waiting for the control plane to become ready
[apiclient] All control plane components are healthy after 17.599812 seconds
[apiclient] Waiting for at least one node to register
[apiclient] Temporarily unable to list nodes (will retry)
[apiclient] Temporarily unable to list nodes (will retry)
[apiclient] Temporarily unable to list nodes (will retry)

**What you expected to happen**:
The command should have succeeded thereby downloading and installing the cluster database and “control plane” components

**How to reproduce it** (as minimally and precisely as possible):
Follow http://kubernetes.io/docs/getting-started-guides/kubeadm/ to install kubernetes

**Anything else we need to know**:

**Comment by Dmitry1987** [comment]
same same!  tried kubeadm 1.6.1, with this config, and the token from previous old cluster:

```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: v1.6.1
cloudProvider: aws
api:
  advertiseAddress: 172.18.204.59
apiServerCertSANs:
 - localhost
 - 127.0.0.1
 - kubernetes-production.example.com
 - kubernetes-production.example.local
 - 172.18.204.59
authorizationMode: RBAC
etcd:
  endpoints:
  - http://etcd-production.example.local:2379
apiServerExtraArgs:
  insecure-bind-address: 0.0.0.0
controllerManagerExtraArgs:
  allocate-node-cidrs: "false"
  configure-cloud-routes: "false"
token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
  podSubnet: 10.244.0.0/16

```

migrated etcd to v3 successfully, I see all my keys.. but "kubeadm init" with this config, gets stuck on  
```
[apiclient] Temporarily unable to list nodes (will retry)
```

and the logs say:

```
docker logs 214db2814f4f
I0417 16:14:45.874253       1 aws.go:758] Building AWS cloudprovider
I0417 16:14:45.874311       1 aws.go:721] Zone not specified in configuration file; querying AWS metadata service
E0417 16:14:46.092939       1 tags.go:94] Tag "KubernetesCluster" nor "kubernetes.io/cluster/..." not found; Kubernetes may behave unexpectedly.
I0417 16:14:46.092962       1 tags.go:78] AWS cloud - no clusterID filtering
E0417 16:14:46.366031       1 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:70: Failed to list *api.ServiceAccount: Get https://localhost:6443/api/v1/serviceaccounts?resourceVersion=0: dial tcp [::1]:6443: getsockopt: connection refused
E0417 16:14:46.366195       1 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:70: Failed to list *storage.StorageClass: Get https://localhost:6443/apis/storage.k8s.io/v1beta1/storageclasses?resourceVersion=0: dial tcp [::1]:6443: getsockopt: connection refused
E0417 16:14:46.366268       1 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:70: Failed to list *rbac.Role: Get https://localhost:6443/apis/rbac.authorization.k8s.io/v1beta1/roles?resourceVersion=0: dial tcp [::1]:6443: getsockopt: connection refused
E0417 16:14:46.366390       1 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:70: Failed to list *api.LimitRange: Get https://localhost:6443/api/v1/limitranges?resourceVersion=0: dial tcp [::1]:6443: getsockopt: connection refused
E0417 16:14:46.366463       1 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:70: Failed to list *api.ResourceQuota: Get https://localhost:6443/api/v1/resourcequotas?resourceVersion=0: dial tcp [::1]:6443: getsockopt: connection refused
E0417 16:14:46.366517       1 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:70: Failed to list *api.Secret: Get https://localhost:6443/api/v1/secrets?resourceVersion=0: dial tcp [::1]:6443: getsockopt: connection refused
E0417 16:14:46.366566       1 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:70: Failed to list *api.Namespace: Get https://localhost:6443/api/v1/namespaces?resourceVersion=0: dial tcp [::1]:6443: getsockopt: connection refused
E0417 16:14:46.366668       1 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:70: Failed to list *rbac.RoleBinding: Get https://localhost:6443/apis/rbac.authorization.k8s.io/v1beta1/rolebindings?resourceVersion=0: dial tcp [::1]:6443: getsockopt: connection refused
E0417 16:14:46.366736       1 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:70: Failed to list *rbac.ClusterRole: Get https://localhost:6443/apis/rbac.authorization.k8s.io/v1beta1/clusterroles?resourceVersion=0: dial tcp [::1]:6443: getsockopt: connection refused
E0417 16:14:46.366790       1 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:70: Failed to list *rbac.ClusterRoleBinding: Get https://localhost:6443/apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings?resourceVersion=0: dial tcp [::1]:6443: getsockopt: connection refused
[restful] 2017/04/17 16:14:46 log.go:30: [restful/swagger] listing is available at https://172.18.204.59:6443/swaggerapi/
[restful] 2017/04/17 16:14:46 log.go:30: [restful/swagger] https://172.18.204.59:6443/swaggerui/ is mapped to folder /swagger-ui/
I0417 16:14:46.600560       1 serve.go:79] Serving securely on 0.0.0.0:6443
I0417 16:14:46.794097       1 logs.go:41] http: TLS handshake error from 172.18.204.91:58312: read tcp 172.18.204.59:6443->172.18.204.91:58312: read: connection reset by peer
I0417 16:14:46.799846       1 logs.go:41] http: TLS handshake error from 172.18.204.91:58310: read tcp 172.18.204.59:6443->172.18.204.91:58310: read: connection reset by peer

```

maybe someone solved this already?  (totally weird - that this is out of the box behavior, of kubeadm 1.6.1, with almost same settings that worked with 1.5.4)

**Comment by kargakis** [comment]
@kubernetes/sig-cluster-lifecycle-misc

**Comment by roberthbailey** [comment]
Please close this issue and re-open in the [kubeadm repository](https://github.com/kubernetes/kubeadm)

**Comment by luxas** [comment]
@rachit1arora Please reopen in the kubeadm repo, closing for now
