### ISSUE TITLE
Fix chronically failing upgrade test suites

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#44563]
wrt https://github.com/kubernetes/test-infra/issues/2453 https://github.com/kubernetes/test-infra/pull/2489 https://github.com/kubernetes/test-infra/pull/2487

I think a lot of the upgrade test suites would start passing if we fixed:

[k8s.io] Kubectl client [k8s.io] Kubectl describe should check if kubectl describe prints relevant information for rc and pods [Conformance]
[k8s.io] Kubectl client [k8s.io] Kubectl taint should remove all the taints with the same key off a node
[k8s.io] Kubectl client [k8s.io] Kubectl taint should update the taint on a node
[k8s.io] Upgrade [Feature:Upgrade] [k8s.io] cluster upgrade should maintain a functioning cluster [Feature:ClusterUpgrade]
Which seem to be the common failures: https://k8s-testgrid.appspot.com/upgrades-gce-cvm-and-gci#Summary

Let's please try this first before deleting these jobs.

I don't have a lot of cycles right now, but if I can't fix these myself I will try to find someone who can in the next month.

**Comment by fejta** [comment]
Note that the requirement to keep these jobs is to get them passing by the end of April.
