### ISSUE TITLE
GKE creates fluentd-gcp pods when loggingService:none

### ISSUE THREAD

**Issue by erikgrinaker** [kubernetes/kubernetes#44581]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): fluentd-gcp beta.kubernetes.io/fluentd-ds-ready

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.6.1

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): Container-Optimized OS from Google
- **Kernel** (e.g. `uname -a`): 4.4.21+
- **Install tools**:
- **Others**:

**What happened**:

Cluster initially created without Google Cloud logging, confirmed by:

```
$ gcloud container clusters describe kubernetes01-eu-w1 | grep loggingService
loggingService: none
```

With 1.5.3, this prevented fluentd pods from being created. After upgrading to 1.6.1, GKE now creates a `fluentd-gcp-v2.0` daemonset.

```
$ kubectl get daemonsets fluentd-gcp-v2.0
NAME               DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE-SELECTOR                              AGE
fluentd-gcp-v2.0           3         3         0         3            0           beta.kubernetes.io/fluentd-ds-ready=true   21m
```

This is because the 1.6.1 nodes get the label `beta.kubernetes.io/fluentd-ds-ready=true` regardless of `loggingService`.

**What you expected to happen**:

No `fluentd-gcp` pods to be created, or the label `beta.kubernetes.io/fluentd-ds-ready=true` not to be applied, when `loggingService: none`.

**How to reproduce it** (as minimally and precisely as possible):

```
$ gcloud container clusters create --cluster-version 1.6.1 --no-enable-cloud-logging --num-nodes 1 test

$ kubectl -n kube-system get daemonsets fluentd-gcp-v2.0
NAME               DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE-SELECTOR                              AGE
fluentd-gcp-v2.0   1         1         1         1            1           beta.kubernetes.io/fluentd-ds-ready=true   49s
```

**Anything else we need to know**:

I believe @piosz is working on this.

**Comment by piosz** [comment]
@erikgrinaker thanks for reporting. I'll take a look.

cc @roberthbailey @fabioy @crassirostris @jlowdermilk

**Comment by piosz** [comment]
cc @fgrzadkowski

**Comment by roberthbailey** [comment]
@erikgrinaker - thanks for the bug report. We've been able to root cause and should have a fix available soon.

**Comment by erikgrinaker** [comment]
Great stuff, thanks guys!

**Comment by wjkohnen** [comment]
cc @jayme-github @tback

**Comment by jshearer** [comment]
@roberthbailey Any update on this?

**Comment by piosz** [comment]
This is already fixed and being rolled out. ETA early next week. This already works in some zones, for example `us-east1-d`.  You can verify this by:
```
gcloud container clusters create --cluster-version 1.6.1 --no-enable-cloud-logging --num-nodes 1 --zone us-east1-d test
```

**Comment by atombender** [comment]
@piosz Out of interest, will there ever be a `gcloud container clusters update --logging-service=none` for clusters that have already been created with logging enabled?

**Comment by piosz** [comment]
@atombender yes. The motivation behind migrating fluentd to ds was to add possibility to manage it including enabling/disabling. It's coming soon.

**Comment by atombender** [comment]
@piosz Awesome, thanks.

**Comment by roberthbailey** [comment]
The fix is part of this week's GKE. See release https://cloud.google.com/container-engine/release-notes#april_26_2017

You can tell if it's in the zone you care about by running `gcloud container get-server-config --zone=ZONE` and see if 1.6.2 is listed in the `validMasterVersions` field in the output.

**Comment by roberthbailey** [comment]
Ah, forgot to reload the page and it looks like @piosz beat me to it. :)

**Comment by wjkohnen** [comment]
I've tested this on us-east1-d and it works. 

Today I've tested this on europe-west1-d and it does not work. There is still the `beta.kubernetes.io/fluentd-ds-ready=true` label despite `loggingService: none` and the fluentd-gcp daemon sets get created.

**Comment by crassirostris** [comment]
@wjkohnen It will start working today by the EOD PT or by the EOD PT on Monday. Sorry for the inconvenience

**Comment by wjkohnen** [comment]
Thanks! I don't know what EOD PT means, but Monday sounds good to me.

**Comment by crassirostris** [comment]
@wjkohnen Sorry, end of day pacific time :D
