### ISSUE TITLE
kubectl shows 0y (incorrect rounding)

### ISSUE THREAD

**Issue by krallistic** [kubernetes/kubernetes#44599]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
 kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5", GitCommit:"894ff23729bbc0055907dd3a496afb725396adda", GitTreeState:"clean", BuildDate:"2017-03-22T00:23:49Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5", GitCommit:"894ff23729bbc0055907dd3a496afb725396adda", GitTreeState:"clean", BuildDate:"2017-03-22T00:17:51Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:
kubectl get namespace $NS
NAME      STATUS    AGE
$NS      Active    0y
Show 0y,  a 
 kubectl get namespace $NS-o=yaml
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: 2016-04-18T07:37:18Z
shows that its almost a year old now.

**What you expected to happen**:
Show 1y or 12m, 0y is a bit confusing.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by xingzhou** [comment]
let me take a look at it

**Comment by xingzhou** [comment]
A tiny issue in the printers, fixing it now
