### ISSUE TITLE
Protobuf serialization does not distinguish between `[]` and `null`

### ISSUE THREAD

**Issue by siggy** [kubernetes/kubernetes#44593]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): Not a request for help. Observed undocumented change in 1.6.1 api.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): endpoints subsets api

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release):

```
BUILD_ID=9000.104.0
NAME="Container-Optimized OS"
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=56
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=56
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
```

- **Kernel** (e.g. `uname -a`):
```
Linux gke-alpha-default-pool-3f2b4945-188b 4.4.21+ #1 SMP Wed Apr 5 14:40:46 PDT 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
```
- **Install tools**:
- **Others**:
1.6.1 alpha cluster set up with:
```
gcloud alpha container clusters create alpha --cluster-version 1.6.1 --zone us-central1-b --enable-kubernetes-alpha
```

**What happened**:

Observed API change in 1.6.1. `api/v1/namespaces/{namespace}/endpoints` returns `null` for `.items[].subsets`. 1.6.0 returns `[]`

**What you expected to happen**:

Expect 1.6.1 to match 1.6.0, and return `[]`

**How to reproduce it** (as minimally and precisely as possible):

## 1.6.0

```bash
$ kubectl -n=kube-system get ep kube-controller-manager -o jsonpath='{.subsets}'
[]

$ kubectl -n=kube-system get ep -o jsonpath='{.items[?(@.metadata.name=="kube-controller-manager")].subsets}'
[]
```

## 1.6.1

```bash
$ kubectl -n=kube-system get ep kube-controller-manager -o jsonpath='{.subsets}'
[]

$ kubectl -n=kube-system get ep -o jsonpath='{.items[?(@.metadata.name=="kube-controller-manager")].subsets}'
<nil> # <---- BOOM
```

**Anything else we need to know**:

Original bug reported as an exception in linkerd:
https://github.com/linkerd/linkerd/issues/1219

**Comment by liggitt** [comment]
nothing related to this changed between 1.6.0 and 1.6.1:

https://github.com/kubernetes/kubernetes/compare/v1.6.0...v1.6.1

**Comment by liggitt** [comment]
the issue with null lists was fixed by https://github.com/kubernetes/kubernetes/pull/43422, but I'm seeing different behavior between a list and an individual item.

**Comment by liggitt** [comment]
xref https://github.com/kubernetes/kubernetes/issues/46733

**Comment by liggitt** [comment]
copied from https://github.com/kubernetes/kubernetes/pull/45294#issuecomment-307833935:

> The more I work on this, the more concerned I get with trying to fixup data our storage layer is dropping.
>
> Compressing null -> [] is just as much of an API breakage as [] -> null, it just happens to cause fewer problems in clients that don't do null checks.
>
> 1.6 was released with this behavior half-exposed already (listing objects doesn't apply the null->[] hack), and the world didn't explode. I'm inclined to document a breaking change in 1.7 that null and [] are considered equivalent, unless otherwise noted on a particular field, and remove that hack for 1.8, instead of this monster PR.
