### ISSUE TITLE
GCL test started failing again in gke-large

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#44609]
This is the first run that failed (all subsequent also failed):
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-large-cluster/117

It might be related to changes @piosz were doing.

```
I0417 18:29:10.628] [91m[1m• Failure [9.011 seconds][0m
I0417 18:29:10.628] [k8s.io] Cluster level logging using GCL
I0417 18:29:10.628] [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:656[0m
I0417 18:29:10.628]   [91m[1mshould check that logs from containers are ingested in GCL [It][0m
I0417 18:29:10.628]   [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster-logging/sd.go:63[0m
I0417 18:29:10.629] 
I0417 18:29:10.629]   [91mFluentd deployed incorrectly
I0417 18:29:10.629]   Expected error:
I0417 18:29:10.629]       <*errors.errorString | 0xc4227ce5d0>: {
I0417 18:29:10.629]           s: "node gke-gke-large-cluster-default-pool-0-82e2e705-9p7h doesn't have fluentd instance",
I0417 18:29:10.629]       }
I0417 18:29:10.629]       node gke-gke-large-cluster-default-pool-0-82e2e705-9p7h doesn't have fluentd instance
I0417 18:29:10.629]   not to have occurred[0m
I0417 18:29:10.629] 
I0417 18:29:10.629]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster-logging/sd.go:46
```

**Comment by crassirostris** [comment]
@wojtek-t From the latest run:

```
Fluentd deployed incorrectly
Expected error:
    <*errors.errorString | 0xc420da5590>: {
        s: "node gke-gke-large-cluster-default-pool-0-2ad17596-fx5b doesn't have fluentd instance",
    }
    node gke-gke-large-cluster-default-pool-0-2ad17596-fx5b doesn't have fluentd instance
not to have occurred
```

In the controller_manager:

```
failed to place pod on "gke-gke-large-cluster-default-pool-0-2ad17596-fx5b": Node didn't have enough resource: cpu, requested: 100, used: 980, capacity: 1000
```

**Comment by crassirostris** [comment]
It seems that DNS does not allow fluentd to be scheduled on the node

@piosz @dchen1107 @davidopp Can we use critical pod annotation on fluentd to fix this problem? I remember @dchen1107 was against it. Or should we wait for the proper priorities?

**Comment by wojtek-t** [comment]
so it seems that the problem is scheduling too many dns-es on a single node so that then fluentd doesn't fit the resources there

I think that doing for fluentd what we are currently doing with dns or heapster anyway sounds good to me (it's not introducing the new mechanism, it's reusing the existing one, though we all agree it's far from perfect - but the change will be extremely minimal and local).
But I would like to confirm with @dchen1107 and @davidopp too.

**Comment by davidopp** [comment]
fluentd already runs as a critical pod
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml#L23
so I thought kubelet preemption for DaemonSet (#42028 / #40952) should ensure it gets scheduled?

Of course if the node can't fit all of the critical pods then you're out of luck.

**Comment by crassirostris** [comment]
Whoops, sorry, forgot that it was re-instantiated

Then it's a valid problem: in large clusters logs from some nodes can be not exported. I ofc can always remove this constraint from the tests, but are there any ideas how to tackle this?

/cc @fgrzadkowski

**Comment by wojtek-t** [comment]
@crassirostris - I wouldn't say this is a problem of large cluster. This is a problem of number of critical pods in the system (which is currently correlated with the cluster size, but doesn't necessary have to be).

But the root cause of this issue is that once the node is created, in large clusters it may take quite a long time before this node is actually schedulable, because the node is not schedulable until the route for it is not created (in gce/gke). That said, when we are creating a large cluster, it quickly has a lot of nodes, but only very small percentage of those is actually schedulable.
So this results in a bunch of DNS pods to be scheduled on a single node.

That said, as long as we aren't super fast from registering a node to the moment when it is schedulable, we should try to workaround differently.

One possibly is to add anti-affinity (or host port) to DNS pods to ensure that there is no more than one such pod on a given node. But at least in theory, you may want to have more DNS pods in the cluster than the number of nodes, and this would make it impossible.

Another possibility is to scale the number of DNS pods not based on number of total nodes in the cluster, but based on number of schedulable nodes in the cluster. That wouldn't be a big change, and I think it would solve this problem.
@bowei @thockin - WDYT^^

**Comment by piosz** [comment]
There are also 2 other possible (future) solutions for the problem:
- rescheduler migrates some DNS pods to optimize its spread
- priority/preemptions features takes into account kind of the creator of pods and a critical ds (which can run only on one particular node) has higher priority than a critical deployment (which can run on any node).

**Comment by wojtek-t** [comment]
I agree, but:
1. I'm not sure it makes sense to introduce new features to current rescheduler, which we are going to eliminate anyway (and replace with some other kind of rescheduler)
2. That is the ideal solution, but it will take in my opinion at least 2 quarters to get there, and we need something sooner.

**Comment by piosz** [comment]
I meant potential long term solutions.

1. I meant the new rescheduler being designed.

**Comment by wojtek-t** [comment]
This is still not fixed.

**Comment by bowei** [comment]
Is anti-affinity strict (e.g. can never schedule together) or is it a best-effort? If this is best effort, it seems to be the right thing to do to improve resilience wrt to node failure.

There were some people in the community that wanted to add it to the pod spec, but it never made it to the finish line.

**Comment by wojtek-t** [comment]
I think we still don't have any anti-affinity (neither strict nor preferred). I'm a bit pesimistic about this, because anti-affinity doesn't scale for now...

What I started thinking about (and what should be pretty small change and may work good enough) is to actually scale not based on number of nodes, but based on number of __Ready__ nodes.
@bowei - WDYT?

**Comment by bowei** [comment]
It seems reasonable (ready nodes), but how does that help with the pathological case of all kube-dns pods being placed on a single node and crowding out another critical pod?

**Comment by wojtek-t** [comment]
@bowei - it won't help with all the cases. 
But I think it should solve the problem we are observing here. The problem here is that we are spinning up 2000-node cluster (or any other large one). And initially all nodes are registered, but only few of them are schedulable, because other don't yet have routes created. So we are creating all DNS replicas, but squeezing them only on those schedulable nodes.

**Comment by bowei** [comment]
Ah right, makes sense.

**Comment by wojtek-t** [comment]
So actually, I shouldn't say that based on number "Ready" nodes, but instead based on number of "Schedulable" nodes.

**Comment by bowei** [comment]
hmm -- it seems like that is already the case?

see https://github.com/kubernetes-incubator/cluster-proportional-autoscaler/blob/master/pkg/autoscaler/k8sclient/k8sclient.go

```
	// GetClusterStatus counts schedulable nodes and cores in the cluster
	GetClusterStatus() (clusterStatus *ClusterStatus, err error)
```

**Comment by wojtek-t** [comment]
There is one issue with this (we are suffering this in many different place, e.g. autoscaler).
The problem is that "schedulable" field doesn't really mean that the Node is really schedulable - it only means that it sometime can be schedulable.

In scheduler we additionally check if:
- node is ready:
- node doesn't have "NodeOutOfDisk" condition
- node doesn't have "NodeNetworkUnavailable" condition
- node doesn't have "spec.Unschedulable" field set
The code checking it is here:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L511

We should duplicate the same logic in the cluster-proportional-autoscaler code.

**Comment by piosz** [comment]
cc @mwielgus

**Comment by piosz** [comment]
Closing as obsolete. Please reopen in case of any problems.
