### ISSUE TITLE
kubelet panic `invalid memory address or nil pointer dereference` using `kubeadm init` with vsphere cloud-provider

### ISSUE THREAD

**Issue by sdurrheimer** [kubernetes/kubernetes#44603]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

`BUG REPORT`

**Kubernetes version** (use `kubectl version`):

`v1.6.1`

**Environment**:
- **Cloud provider or hardware configuration**: 
4 VMs via ESXI 6.5 on a single physical server
- **OS** (e.g. from /etc/os-release): 
Ubuntu 16.04.2
- **Kernel** (e.g. `uname -a`): 
`Linux kube-master-1 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**: 
kubeadm `1.6.1-00`
- **Others**:
docker `1.12.6`

**What happened**:

When bootstraping a new cluster with `kubeadm v1.6.1` and the `vsphere` cloud-provider, the `kubelet` cant' start because of the following `invalid memory address or nil pointer dereference` panic error.

```
Apr 18 10:33:09 kube-master-1 kubelet[14075]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 18 10:33:09 kube-master-1 kubelet[14075]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x120cd37]
Apr 18 10:33:09 kube-master-1 kubelet[14075]: goroutine 1 [running]:
Apr 18 10:33:09 kube-master-1 kubelet[14075]: panic(0x2d9d660, 0xc420010040)
Apr 18 10:33:09 kube-master-1 kubelet[14075]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
Apr 18 10:33:09 kube-master-1 kubelet[14075]: k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere.getVMName(0xc42034d440, 0xc420745d90, 0x0, 0x0, 0x0, 0x0)
Apr 18 10:33:09 kube-master-1 kubelet[14075]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vsphere.go:255 +0x6a7
Apr 18 10:33:09 kube-master-1 kubelet[14075]: k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere.newVSphere(0xc4203bdfe8, 0x4, 0xc420270aa0, 0x14, 0xc420396400, 0xd, 0xc420396608, 0x3, 0x1, 0xc420396b40, ...)
Apr 18 10:33:09 kube-master-1 kubelet[14075]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vsphere.go:285 +0x15b
Apr 18 10:33:09 kube-master-1 kubelet[14075]: k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere.init.1.func1(0x4d38520, 0xc420026708, 0x7ffdd2920d33, 0x7, 0xc420296cc8, 0xc4208a9201)
Apr 18 10:33:09 kube-master-1 kubelet[14075]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vsphere.go:204 +0xa8
Apr 18 10:33:09 kube-master-1 kubelet[14075]: k8s.io/kubernetes/pkg/cloudprovider.GetCloudProvider(0x7ffdd2920d33, 0x7, 0x4d38520, 0xc420026708, 0x0, 0x0, 0x0, 0x0)
Apr 18 10:33:09 kube-master-1 kubelet[14075]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/plugins.go:87 +0xda
Apr 18 10:33:09 kube-master-1 kubelet[14075]: k8s.io/kubernetes/pkg/cloudprovider.InitCloudProvider(0x7ffdd2920d33, 0x7, 0x7ffdd2920d4a, 0x1c, 0x0, 0x0, 0x0, 0x0)
Apr 18 10:33:09 kube-master-1 kubelet[14075]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/plugins.go:119 +0x141
Apr 18 10:33:09 kube-master-1 kubelet[14075]: k8s.io/kubernetes/cmd/kubelet/app.run(0xc420953800, 0x0, 0xc4208a9ec0, 0x456eb0)
Apr 18 10:33:09 kube-master-1 kubelet[14075]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:424 +0x1567
Apr 18 10:33:09 kube-master-1 kubelet[14075]: k8s.io/kubernetes/cmd/kubelet/app.Run(0xc420953800, 0x0, 0x22, 0xc4203bd640)
Apr 18 10:33:09 kube-master-1 kubelet[14075]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:285 +0x39
Apr 18 10:33:09 kube-master-1 kubelet[14075]: main.main()
Apr 18 10:33:09 kube-master-1 kubelet[14075]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go:48 +0x92
```

Moreover, it is not possible to specify the [VMName](https://github.com/kubernetes/kubernetes/blob/67f2a7cc00931cf9df909e6665ab9ece4b8497b3/pkg/cloudprovider/providers/vsphere/vsphere.go#L137) manually in the cloud-provider config file because of the following error:

```
Apr 18 10:30:39 kube-master-1 kubelet[13962]: error: failed to run Kubelet: could not init cloud provider "vsphere": invalid variable: section "Global" subsection "" variable "vm-name"
```

**What you expected to happen**:

My `v1.6.1` kubernetes cluster initialized on my master node with `vsphere` cloud-provider enabled.

**How to reproduce it** (as minimally and precisely as possible):

*/etc/systemd/system/kubelet.service.d/10-kubeadm.conf*

```
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
Environment="KUBELET_EXTRA_ARGS=--cloud-provider=vsphere --cloud-config=/etc/kubernetes/cloud-config"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_EXTRA_ARGS
```

*/etc/kubernetes/cloud-config*

```
[Global]
        user = kube
        password = {PASSWORD}
        server = {ESXI-IP}
        port = 443
        insecure-flag = 1
        datacenter = ha-datacenter
        datastore = datastore-ssd-2
        working-dir =
[Disk]
    scsicontrollertype = pvscsi
```

*/etc/kubernetes/kubeadm.conf*

```
kind: MasterConfiguration
apiVersion: kubeadm.k8s.io/v1alpha1
cloudProvider: vsphere
```

*kubeadm init*
```
root@kube-master-1:/etc/kubernetes# kubeadm init --skip-preflight-checks --config=/etc/kubernetes/kubeadm.conf --apiserver-advertise-address 192.168.0.10 --kubernetes-version v1.6.1 --token {TOKEN}
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.6.0
[init] Using Authorization mode: RBAC
[init] WARNING: For cloudprovider integrations to work --cloud-provider must be set for all kubelets in the cluster.
	(/etc/systemd/system/kubelet.service.d/10-kubeadm.conf should be edited for this purpose)
[preflight] Skipping pre-flight checks
[preflight] Starting the kubelet service
[certificates] Generated CA certificate and key.
[certificates] Generated API server certificate and key.
[certificates] API Server serving cert is signed for DNS names [kube-master-1 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 {PUBLIC-IP}]
[certificates] Generated API server kubelet client certificate and key.
[certificates] Generated service account token signing key and public key.
[certificates] Generated front-proxy CA certificate and key.
[certificates] Generated front-proxy client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/scheduler.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/controller-manager.conf"
[apiclient] Created API client, waiting for the control plane to become ready
...
```

**Anything else we need to know**:

Each VM has 2 network interfaces, one with a public IP (requirement of `online.net` when doing virtualisation on a single physical server) and one with a private IP.

*/etc/docker/daemon.json*

```json
{
    "ip-masq": false, 
    "iptables": false, 
    "live-restore": true, 
    "log-level": "warn", 
    "log-opts": {
        "max-file": "10", 
        "max-size": "100m"
    }, 
    "storage-driver": "overlay2"
}
```

**Comment by xiangpengzhao** [comment]
1.6.1 doesn't support `vm-name` yet, so you got this error:
```
Apr 18 10:30:39 kube-master-1 kubelet[13962]: error: failed to run Kubelet: could not init cloud provider "vsphere": invalid variable: section "Global" subsection "" variable "vm-name"
```

But I find that there is no `vm-name` field in your `/etc/kubernetes/cloud-config` file. That's strange. Where did you configure `vm-name`?

Once kubelet gets the error above, it will fail to run.

**Comment by sdurrheimer** [comment]
@xiangpengzhao I didn't put the `vm-name` in my example because it was just a try to get around the main issue.

**Comment by xiangpengzhao** [comment]
As for the panic, it seems like because the below reason:
The code panics [here](https://github.com/kubernetes/kubernetes/blob/v1.6.1/pkg/cloudprovider/providers/vsphere/vsphere.go#L255): 
```
err = s.Properties(ctx, svm.Reference(), []string{"name"}, &vm)
```

The `svm` is from [here](https://github.com/kubernetes/kubernetes/blob/v1.6.1/pkg/cloudprovider/providers/vsphere/vsphere.go#L249):
```
svm, err := s.FindByUuid(ctx, dc, strings.ToLower(strings.TrimSpace(vmUUID)), true, nil)
```

Dig into [FindByUuid](https://github.com/kubernetes/kubernetes/blob/v1.6.1/vendor/github.com/vmware/govmomi/object/search_index.go#L159-L161), we can find that it may return a nil `svm`:
```
	if res.Returnval == nil {
		return nil, nil
	}
```

A nil `svm` will lead to the panic.

cc @BaluDontu

**Comment by xiangpengzhao** [comment]
@sdurrheimer :)

Don't know when and why the Returnval is nil. @BaluDontu may know more about this :)

**Comment by xiangpengzhao** [comment]
I will give a quick fix to avoid the panic.

**Comment by divyenpatel** [comment]
@xiangpengzhao 

if vmuuid is not specified in the config file, we retrieve the vm uuid at https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L231

we have observed with ubuntu 16.04 incorrect uuid is present in /sys/devices/virtual/dmi/id/product_uuid
with incorrect uuid, you may not be getting VM ref. Is it the issue?


can you verify VM UUID using power cli.

**Result on Ubuntu 16.04**
```
PS /Users/divyenp> Get-VM myvmname  | %{(Get-View $_.Id).config.uuid}                                                                     
421aa2bc-bd52-40df-5e3a-e6cb427fc031
```
```
root@nodes:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
root@nodes:~# cat /sys/devices/virtual/dmi/id/product_uuid
BCA21A42-52BD-DF40-5E3A-E6CB427FC031
root@nodes:~#
```
**Result on Photon OS VM**

```
PS /Users/divyenp> Get-VM coredns.ova  | %{(Get-View $_.Id).config.uuid}                                                                
421aed4f-ea8b-c0c6-f250-b5e257c694e7
```
```
root@photon-zv1KbtvMG [ ~ ]# cat /sys/devices/virtual/dmi/id/product_uuid 
421AED4F-EA8B-C0C6-F250-B5E257C694E7
root@photon-zv1KbtvMG [ ~ ]#
```

@abrarshivani @tusharnt

**Comment by BaluDontu** [comment]
Since you are retrieving incorrect UUID, for the FindByUUID method if no managed entities corresponding to the vm-uuid is found, null is returned. #44661 addresses this fix.

However to overcome the problem, you can specify the correct vm-uuid in the vsphere.conf and it will read the vm reference form this UUID and it will all work fine.

**Comment by xiangpengzhao** [comment]
@divyenpatel @BaluDontu Thanks for explanation! @sdurrheimer Could you please verify this on your env?

>Since you are retrieving incorrect UUID, for the FindByUUID method if no managed entities corresponding to the vm-uuid is found, null is returned.

Since no managed entity is found in this case, should we return error here? So that `getVMName` can catch the error. @BaluDontu 

```go
	if res.Returnval == nil {
		return nil, nil
	}
```

**Comment by sdurrheimer** [comment]
@divyenpatel oh yes, thanks for the information, that was totally the issue.

**Comment by divyenpatel** [comment]
We are in the process of fixing the way we fetch vmuuid. we will be parsing the serial number from `/sys/class/dmi/id/product_serial` which is seems tobe matching with the vmuuid we want.

**Comment by yoshz** [comment]
I have this issue still on CentOS 7.3 with kube-controller-manager. I am running Kubernetes 1.6.4 installed using kubeadm.

@divyenpatel I have used your tip to convert product_serial to the right uuid using this script:
`cat /sys/class/dmi/id/product_serial | sed -e 's/^VMware-//' -e 's/-/ /' | awk '{ print toupper($1$2$3$4 "-" $5$6 "-" $7$8 "-" $9$10 "-" $11$12$13$14$15$16) }'`

This solves the invalid memory pointer error above, but it now fails to register the master node. But that is probably a different issue not related to this issue.

**Comment by divyenpatel** [comment]
> but it now fails to register the master node.

@yoshz We can help debugging the issue. Can you create an issue at https://github.com/vmware/kubernetes/issues

please provide kubelet logs.

**Comment by yoshz** [comment]
I manually enabled vsphere cloud provider after kubeadm init which solved the problem. I am happy!
Thanks for your help!
