### ISSUE TITLE
API Aggregation should not depend on the full network stack

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#44619]
In particular, some master environments don't include kube-dns and/or kube-proxy. API aggregation should work in these environments.

**Comment by liggitt** [comment]
I would not want the aggregator to reimplement service IP/endpoint logic

**Comment by liggitt** [comment]
cc @kubernetes/sig-api-machinery-misc

**Comment by liggitt** [comment]
in particular, as services gain more functionality around load balancing between backing pods, etc, I would want the aggregator to get those benefits for free, not have to chance kube-proxy implementations.

**Comment by deads2k** [comment]
> kube-dns is no longer required (the service IP is hit instead). I would not want the aggregator to reimplement service IP/endpoint logic. Expecting kube-proxy seems reasonable to me.

I agree.  I made a similar comment for similar reasons on the pull here: https://github.com/kubernetes/kubernetes/pull/44742#issuecomment-296226357 .
