### ISSUE TITLE
KubeProxy is sometimes consumes 0.7 CPU on 100 Node clusters when doing nothing

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#44613]
We turned on resource gatherer again, and as it was expected our scalability suite started to fail. This time the biggest culprit is kube-proxy, which sometimes has abnormally high CPU usage in 99th percentile in the Density test. Density does not use services at all, so by itself it doesn't stress kube-proxy, but we do run Load test in the same suite, which puts a quite heavy load on it.

We measure usage in the Density test only, so there's nothing new going on, but it's possible that kube-proxy is doing some residual work, which is left over from the Load test, as the failures happen only when Density is run as a second test. In kubemark clusters we don't observe this behavior (load drops pretty much instantly), so it's possible that it's related to some non-mocked-out iptables magic that kube-proxy does.

E.g. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1870

@kubernetes/sig-scalability-misc @wojtek-t @thockin @freehan

**Comment by timothysc** [comment]
This isn't new, there are literally 5-6 issues surrounding this.  

There is a bunch of batching PRs that were pushed out of 1.6 that should come back in scope.

/cc @dcbw

**Comment by wojtek-t** [comment]
A bunch of preparing PRs were already merged. There are few more in-progress, with culmination that will come with: https://github.com/kubernetes/kubernetes/pull/41030

I think that we should let those tests fail for few more days until those PRs are merged and revisit it then.

**Comment by timothysc** [comment]
fwiw iptables is still unscalable, and competition is moving onto IPVS and BPF/XDP 

https://twitter.com/search?q=%23DockerCon&src=tyah

**Comment by timothysc** [comment]
Even if you batch window update, it's still no match for the other approaches.

**Comment by gmarek** [comment]
I'm very far from networking expert, but doesn't IPVS lack of D/SNAT make it harder for us?

**Comment by thockin** [comment]
Batching is in.  We understand that other answers are better.  This answer exists, for now.
