### ISSUE TITLE
k8s does not deleting pv within pvc

### ISSUE THREAD

**Issue by pkutishch** [kubernetes/kubernetes#44610]
**This is a BUG REPORT**:

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-beta.3", GitCommit:"0cd5ed469508e6dfc807ee6681561c845828917e", GitTreeState:"clean", BuildDate:"2017-03-11T04:20:22Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Bare-metal**:
- **OS** (e.g. from /etc/os-release):
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1325.2.0
VERSION_ID=1325.2.0
BUILD_ID=2017-02-28-2239
PRETTY_NAME="Container Linux by CoreOS 1325.2.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
- **Kernel** (e.g. `uname -a`):
Linux server29 4.9.9-coreos-r1 #1 SMP Tue Feb 28 22:27:48 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz GenuineIntel GNU/Linux
- **Install tools**:
hyperkube
- **Others**:

**What happened**:
When you run
kubectl delete pvc <name>, PVC is going to be removed and PV appears in "Failed" state with reason

Message:	Volume has no class annotation

**What you expected to happen**:
As before i tested this functionality in 1.4
PV should be removed and volume should be deleted from GlusterFS/Heketi as well. 

**How to reproduce it** (as minimally and precisely as possible):
Create storageclass for your glusterfs deployment. 
for example:
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://127.0.0.1:8081"
  clusterid: "630372ccdc720a92c681fb928f27b53f"

Submit pvc: 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

and then remove it using kubectl delete pvc myclaim

**Comment by msau42** [comment]
What does "kubectl describe pv" show?

cc @kubernetes/sig-storage-bugs

**Comment by pkutishch** [comment]
@msau42 
erver29 ~ # kubectl describe pv pvc-91c4d530-2432-11e7-85c9-002590e72b34
Name:		pvc-91c4d530-2432-11e7-85c9-002590e72b34
Labels:		<none>
Annotations:	pv.beta.kubernetes.io/gid=2020
		pv.kubernetes.io/bound-by-controller=yes
		pv.kubernetes.io/provisioned-by=kubernetes.io/glusterfs
StorageClass:	regular
Status:		Failed
Claim:		default/myclaim
Reclaim Policy:	Delete
Access Modes:	RWX
Capacity:	10Gi
Message:	Volume has no class annotation
Source:
    Type:		Glusterfs (a Glusterfs mount on the host that shares a pod's lifetime)
    EndpointsName:	glusterfs-dynamic-myclaim
    Path:		vol_c2c1cd9b55dda182df1cb9644497a950
    ReadOnly:		false
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  25s		25s		1	persistentvolume-controller			Warning		VolumeFailedDelete	Volume has no class annotation

I think this happened because in 1.6 storageClass definition was thrown from annotations to separated field, but removal process still searching for annotations. As per my view, maybe you have different reason of that.

**Comment by wongma7** [comment]
your assessment is right, it was looking for annotation and ignoring field. the fix will be in v1.6.2 https://github.com/kubernetes/kubernetes/pull/44035

**Comment by pkutishch** [comment]
@wongma7 many thanks for your reply. Is there any date when you expecting 1.6.2 to be released?

**Comment by wongma7** [comment]
@pkutishch oops I read it wrong...that's just the cut, it could be anywhere from today to two weeks from today :(

**Comment by pkutishch** [comment]
@wongma7 Many thanks, can see that 1.6.2 has been release, will check this bug and update you with result. 
Thanks

**Comment by saad-ali** [comment]
CC @kubernetes/sig-storage-bugs 

Please reopen if bug still exists.

**Comment by pkutishch** [comment]
Yeah, bug solved. Many thank you guys for working on this.
