### ISSUE TITLE
healthz successfull checks shouldn't update resourceVersion

### ISSUE THREAD

**Issue by henriquetruta** [kubernetes/kubernetes#44624]
commands like `kubectl get nodes -w` and `kubectl get cluster -w` have a bad output of watch, since the resourceVersion is incremented everytime healthz is successfully checked. This doesn't happen with other resources like pods and services. 

Related issue: https://github.com/kubernetes/kubernetes/issues/37842

**Comment by liggitt** [comment]
node status updates that bump the timestamp in a condition increment the resourceVersion. this is working as designed

**Comment by henriquetruta** [comment]
@liggitt thanks for the input. So, what about clusters? Should we close #37842 too?
