### ISSUE TITLE
federation: Support creating resources only in federation control plane

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#44631]
Filing this to converge the same discussion from multiple places.

Problem: Today, when a resource in created in federation, it is automatically spread to all underlying clusters.
https://github.com/kubernetes/kubernetes/issues/29887 is for restricting the clusters to which a federation resource is spread.

There is also a use case to not spread the resource to underlying clusters at all (keep it in federation control plane only). Ref https://github.com/kubernetes/kubernetes/issues/41673, https://github.com/kubernetes/kubernetes/issues/44283.

We have 2 options:
* Use the cluster selector proposal (that is intended to restrict the clusters where federation resource is spread) to also restricting the resource to federation control plane only. This can be done by choosing a cluster label selector `federation.kubernetes.io/federation-control-plane=true`. None of the clusters will have this label and hence the resource will remain in federation control plane.
* Use an explicit way (annotion for now, field later) to indicate federation-only.

I think we all agree to use 1 atleast for now. Once we have a more concrete path from annotation to field for our federation specific fields, we can look at this again.

Documenting this here to make sure everyone is on the same page.

cc @kubernetes/sig-federation-feature-requests

**Comment by madhusudancs** [comment]
If we are sticking to option 1), which is what we are doing right now, I propose we also add an admission controller to federation API server to disallow `federation.kubernetes.io/federation-control-plane=true` on `Cluster` objects.

**Comment by nikhiljindal** [comment]
Yes we can do that

**Comment by shashidharatd** [comment]
@madhusudancs, why would we need an admission controller to disallow `federation.kubernetes.io/federation-control-plane=true` on `Cluster` objects? Am i missing something here?
- By default none of the objects will have this label. am i right?
- Even if the label exist on `Cluster` object, how does it matter? `Cluster` objects are supposed only for federation right? They are not propogated to federated clusters.

**Comment by madhusudancs** [comment]
@shashidharatd  The [cluster selector proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/federation-clusterselector.md) as it stands leaves out this important detail. (Or may be I can't read it, so please point me to it). Selectors on individual objects work, only when there are labels that complement these selectors. These labels are defined on the `Cluster` API objects. Or in other words, cluster selectors select clusters whose `Cluster` API objects have matching labels. 

Now, what prevents someone from adding `federation.kubernetes.io/federation-control-plane=true` to these `Cluster` API objects? Not preventing it defeats the purpose of this special label. So the idea is to prevent it by enforcing it in an admission controller.

> Even if the label exist on Cluster object, how does it matter? Cluster objects are supposed only for federation right? They are not propogated to federated clusters.

Correct, cluster objects are not propagated to the underlying clusters. But what does the cluster selector select on?

cc @emaildanwilson

**Comment by shashidharatd** [comment]
Thanks @madhusudancs for clarifying. it is clear to me now.

**Comment by perotinus** [comment]
Will this get in for 1.7? The current design for federated deployments requires being able to have ReplicaSets in the control plane that aren't propagated.

**Comment by quinton-hoole** [comment]
Ooh, apologies for not paying attention.

1. I think we may need two types cluster different types of cluster
selectors, one to target the primary object(s), and another to specify the
targets and weights if the primary object is federated.

2. I think I favor federated deployments which create deployments in each
cluster (not replica sets). I thought I mentioned that in the design doc a
while ago, but perhaps I didn't.

More when I'm not on a phone :-)

Q

**Comment by quinton-hoole** [comment]
OK, I reread the design doc and code for Federated Deployments to make sure I was not confused:

https://docs.google.com/document/d/1Vi_CKah8oR5ByPp8BlgUD0SoINMD1SE0iMQf_2BKlpw/edit#
https://github.com/kubernetes/kubernetes/blob/master/test/e2e_federation/deployment.go#L84

They do create Deployments in the underlying clusters, and not ReplicaSets in the federation or the underlying clusters directly.
  
So @perotinus I'd like to clarify your comment above:

"The current design for federated deployments requires being able to have ReplicaSets in the control plane that aren't propagated."

Could you explain what you mean here?

**Comment by perotinus** [comment]
Apologies I wasn't clear! @mwielgus has a design proposal in-flight that he intends to merge into the community repo that describes how to allow federated Deployments to support updates and rollbacks. That proposal describes a "shadow ReplicaSet" that lives only in the control plane and is used to keep track of that state necessary to roll back a federated Deployment, used as a repository for information about the deployment that is necessary in order to do a rollback.

The doc describing this in more detail is https://github.com/mwielgus/community/blob/d7651487409214e60123766382779bafc0aeb72b/contributors/design-proposals/federated-deployment.md.

**Comment by quinton-hoole** [comment]
And further, regarding the [cluster selector proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/federation-clusterselector.md) that got merged recently, I have some pretty serious concerns about it (Wow! I was really not paying attention for the first couple of months of this year, and I apologise for that).

My concerns are primarily:

1. How are cluster weights handled?  The doc waves hands a bit about how cluster selectors and replica set preferences are separate concepts and independent of each other, but in practise I don't think that this works out well at all (try it with a simple example ).
2. How can clusters (or more generally, subsets of objects) be selected for read operations?  We need to be able to e.g. list ConfigMaps across a subset of clusters etc.  It seems that this feature needs to harmonize with the object creation cluster selectors being contemplated here.

@nikhiljindal @emaildanwilson @derekwaynecarr Can we take a second pass over the  [cluster selector proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/federation-clusterselector.md) and resolve these two issues please?

My apologies for chirping in so late.  I completely missed that thread the first time around.

**Comment by quinton-hoole** [comment]
@perotinus Aah, thanks.  That clarifies my confusion.  I'll take a look at the design regarding rollbacks.  cc @kevin-wangzefeng who is also looking into that right now.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#129.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
