### ISSUE TITLE
Invalid Content-Type text/plain on responses returned from APIServer

### ISSUE THREAD

**Issue by ilackarms** [kubernetes/kubernetes#44646]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
build-25c2f56967-5-v1.7.5-3

**Environment**:
- **Cloud provider or hardware configuration**: Laptop (bare metal)
- **OS** (e.g. from /etc/os-release): Fedora 26
- **Kernel** (e.g. `uname -a`): Linux localhost.localdomain 4.11.0-0.rc6.git0.1.fc26.x86_64 #1 SMP Mon Apr 10 19:45:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: make && hack/local-cluster-up.sh -o _output/bin

**What happened**:
built from  fb3353c and ran with local-cluster-up.sh

All `kubectl` commands gave the following error: `serializer for text/plain; charset=utf-8 doesn't existserializer for text/plain; charset=utf-8 doesn't exist`

Running `kubectl ... -v 8` showed the output: https://paste.fedoraproject.org/paste/Npp5QOqHiOXe07lpMkdXQV5M1UNdIGYhyRLivL9gydE=/ 

**What you expected to happen**:
for `kubectl` commands to work, and Content-type to show `application/json`

**How to reproduce it** (as minimally and precisely as possible):
```
#from fb3353c:
make && hack/local-cluster-up.sh -o _output/bin
#in another session
kubectl proxy
```

**Comment by ilackarms** [comment]
ccing @liggitt

**Comment by liggitt** [comment]
I see the text plain content type, but not kubectl errors

**Comment by ilackarms** [comment]
i was using the wrong version of kubectl. updated to new and i'm not getting an error any longer.

**Comment by liggitt** [comment]
Text/plain coming back from the server is still an issue

**Comment by liggitt** [comment]
cc @deads2k @kubernetes/sig-api-machinery-bugs

**Comment by deads2k** [comment]
> Text/plain coming back from the server is still an issue

I'm not seeing `text/plain` against head and the pastebin is gone.  Did you reproduce?

**Comment by liggitt** [comment]
I did last week. Insecure and secured port behaved differently

**Comment by kargakis** [comment]
You can reproduce this using `oc` against a Kubernetes cluster built from HEAD

**Comment by danielqsj** [comment]
Hi all, I think we could use `responsewriters.WriteObjectNegotiated()` write Content-type correctly.
I have made a PR for fix this.
