### ISSUE TITLE
Rename NetworkPolicy fields to convey "to" and "from"

### ISSUE THREAD

**Issue by Q-Lee** [kubernetes/kubernetes#44643]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

**Kubernetes version** (use `kubectl version`): API v1beta1

Networking traditionally refers to "sources" and "destinations". Acceptable alternatives are "to" and "from".

The NetworkPolicySpec names the destination selector "podSelector", and the source is "Ingress[].From". Since "ToPodSelector" sounds kind of weird, can we call these "DestinationPodSelector" and "Ingress[].Source" when in the v1 API? I found our current naming scheme quite confusing.

**Comment by thockin** [comment]
I don't think we want to rename fields between beta and GA, but I'll open it to @kubernetes/sig-network-feature-requests and @danwinship @caseydavenport and other implementors...

**Comment by caseydavenport** [comment]
Yeah, I don't think we want to change naming between the versions.  Perhaps we need better documentation about the different selectors?

I think the current naming is more flexible.  For example, if we ever decide we want to support egress policy in NetworkPolicy then renaming `Spec.PodSelector` to `Spec. DestinationPodSelector ` drastically changes how that would need to be represented, and the semantics available to us.

**Comment by danwinship** [comment]
I feel like it's pretty late to be changing things. And the SIG has generally been pretty against making changes relative to the v1beta1 API anyway. Plus what Casey said. We can try to document this better though.
