### ISSUE TITLE
"requested an external service, but no cloud provider supplied" error when creating a guestbook service

### ISSUE THREAD

**Issue by abonas** [kubernetes/kubernetes#4464]
Using a local dev setup (hack local cluster), creating a guestbook service from this json:
https://github.com/GoogleCloudPlatform/kubernetes/blob/b01126322b826a15db06f6eeefeeb56dc06db7af/examples/guestbook-go/guestbook-service.json

it fails with "requested an external service, but no cloud provider supplied"
it will be better if:
1. basic examples will work in dev setup
2. the message will explain what should be changed in the json (which attribute is missing) in order to make it work/which values should be assigned.

**Comment by naemono** [comment]
It turns out that the '--cloud_provider=vagrant' is what's needed to be provided to begin to get around this issue.

Mine is set in /etc/default/kube-apiserver

```
root@localhost:/etc/default# cat kube-apiserver
# Kube-Apiserver Upstart and SysVinit configuration file

# Customize kube-apiserver binary location
# KUBE_APISERVER="/opt/bin/kube-apiserver"

# Use KUBE_APISERVER_OPTS to modify the start/restart options
KUBE_APISERVER_OPTS="--address=127.0.0.1 \
--port=8080 \
--etcd_servers=http://127.0.0.1:4001 \
--logtostderr=true \
--portal_net=11.1.1.0/24 \
--cloud_provider=vagrant \
--v=10"

# Add more envionrment settings used by kube-apiserver here
```
But that just leads you to this, which is pretty self explanatory
```
vagrant@localhost /opt/kubernetes/examples/guestbook $ sudo /opt/bin/kubectl create -f frontend-service.json
F0227 18:36:47.952113   27270 create.go:83] the cloud provider does not support external TCP load balancers.
```

**Comment by abonas** [comment]
@naemono not everyone is working with the vagrant setup.

**Comment by derekwaynecarr** [comment]
If an example requires external load balancer, it's no longer an example that you should expect to work across all providers.  I don't see an issue here in code, but we should update the documentation to state that a step is only supported if a feature is provided.

**Comment by derekwaynecarr** [comment]
There are a number of things that become very provider specific, and at best, we should state in the documentation what provider a specific example was tested against.

**Comment by abonas** [comment]
@derekwaynecarr, I'd expect to have at least one example that would work with the setup built from source. and I agree that each example should state where it should and shouldn't work.

**Comment by scuxiayiqian** [comment]
I got the same fail message "requested an external service, but no cloud provider supplied" when I try to create the front end service. And I really expect to see an example that will not require external load balancer too.

**Comment by bprashanth** [comment]
It should still work, you just don't have the load balancer. You should be able to `./cluster/kubectl.sh get pods` and curl the IP of one of your frontend pods (wait till they go from `Pending` to `Running`) to see the guestbook html; `kubectl.sh get rc` and `kubectl.sh get servcies` should work too. I believe there's language in the README regarding the GCE loadbalancer: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/guestbook/README.md

A more basic localhost example might help you with the concept of pods: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/locally.md

**Comment by scuxiayiqian** [comment]
@bprashanth , I ran the ``curl <pod IP>`` on my slave host, it returned me the guestbook html. I am also able to get ``kubectl get pods``, ``kubectl get rc`` and ``kubectl get services`` work, following the [Guestbook guide](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/guestbook/README.md). Thank you very much!

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (186/150 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:54425)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-5c7e-dev=imwiz.com@sgmail.github.com>)
	id 1dGTRh-0000e5-Bl
	for dev@imwiz.com; Thu, 01 Jun 2017 10:59:40 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Gqdjv7r6Btc/j1Fwa1636fr+EVs=; b=g3ebF5l5bgLfqYqn
	EbKGZBd4wYLs6ni3WX14Bqiv2cF4S5tNycYUccgp3wdwwml3XH+yR/pIdb3bKdmU
	sZC/wWMs6MoBVdv65BupcWQvQXpq8vpUGZr+J25tR1BNGxXXifHlED4NwuPVBhOq
	Cp7pRaN9JRSv4BHmvyLT3U0fJaE=
Received: by filter0826p1mdw1.sendgrid.net with SMTP id filter0826p1mdw1-26186-593047E7-2F
        2017-06-01 16:59:19.55298296 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id xY2WROcUR-CMy6BxXYshJA
	for <dev@imwiz.com>; Thu, 01 Jun 2017 16:59:19.503 +0000 (UTC)
Date: Thu, 01 Jun 2017 09:59:19 -0700
