### ISSUE TITLE
We need an AWS volume stress test

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#44656]
We have had a lot of reported & real issues with AWS volumes.  We need a stress test so we can have confidence both in the existing code and in any fixes we merge.

@kubernetes/sig-testing-misc is there a GCE test we can adapt?  The ideal end goal in my mind would have a lot of volume operations happening concurrently with disruptive operations (restarting kubelets, kube-controller-managers, nodes, apiservers etc).

cc @gnufied @jingxu97

**Comment by copejon** [comment]
As a starting point, I would recommend looking through https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/ for adaptable tests.  For kubelet restarts specifically, 
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/persistent_volumes-disruptive.go
might be a useful template.

Some of these suites have been written with GCE in mind but `e2e/framework/` might have some AWS specific helper functions for disk handling.  Most, however, are agnostic to the underlying storage provider.  They achieve this by spinning up an NFS server pod.  Through either plugin or persistent volume, this pod's NFS share is consumed by a client pod, on which actual testing is performed.

**Comment by copejon** [comment]
cc @jeffvance

**Comment by gnufied** [comment]
For stress tests I am thinking of simply creating 30 pods (using deployments) and bringing them up and down and hoping it works. @justinsb did you had anything else in mind for stress tests?

**Comment by copejon** [comment]
That should be relatively easy.  See https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/volume_provisioning.go#L492.  The pattern creates 100 PVs but could easily be made to create Pods instead.

**Comment by justinsb** [comment]
We have a multivolume stateful set test which I proposed a while ago, which could be made pretty similar to that.  https://github.com/kubernetes/kubernetes/pull/41180  and https://github.com/kubernetes/test-infra/pull/2402

The disruption is where I think it gets interesting.  But anything would be a good start @gnufied  :-)
