### ISSUE TITLE
[Deployment]When replicas=1 the deployment status is not correct with "progressDeadlineSeconds" fieled setup

### ISSUE THREAD

**Issue by wanghaoran1988** [kubernetes/kubernetes#44657]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1902+7543bac56342fd", GitCommit:"7543bac56342fddaaadcfe555ad500a19dabf611", GitTreeState:"clean", BuildDate:"2017-04-13T08:50:28Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1902+7543bac56342fd", GitCommit:"7543bac56342fddaaadcfe555ad500a19dabf611", GitTreeState:"clean", BuildDate:"2017-04-13T08:50:28Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
When the replicas=1, the deployment's Progressing status always 'True' even the deployment failed, and the `progressDeadlineSeconds` perma does not work.

**What you expected to happen**:
After the progressDeadlineSeconds, no matter what's the replica size is, after the seconds, we should have a perma result, succeed or failed.
**How to reproduce it** (as minimally and precisely as possible):
1. Create deployment with image not exist, and set `progressDeadlineSeconds: 30`
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: hello-openshift
    spec:
      progressDeadlineSeconds: 30
      replicas: 1
      template:
        metadata:
          labels:
            app: hello-openshift
        spec:
          containers:
          - name: hello-openshift
            image: openshift/hello-openshift:123
            resources:
              limits:
                cpu: 120m
                memory: 250Mi
              requests:
                cpu: 60m
                memory: 250Mi
            ports:
            - containerPort: 80
2. kc get deployment/hello-openshift -o yaml 
........
status:
  conditions:
  - lastTransitionTime: 2017-04-17T08:14:21Z
    lastUpdateTime: 2017-04-17T08:14:21Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2017-04-17T08:14:21Z
    lastUpdateTime: 2017-04-17T08:14:21Z
    message: Replica set "hello-openshift-4237999559" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1

$kc get po 
NAME                               READY     STATUS             RESTARTS   AGE
hello-openshift-4237999559-8fxv3   0/1       ImagePullBackOff   0          3m

**Comment by wanghaoran1988** [comment]
@kargakis @janetkuo

**Comment by wanghaoran1988** [comment]
I am happy working on that, but I need some time to get familiar with the logic.

**Comment by kargakis** [comment]
You use a maxUnavailable value that allows the deployment full unavailability, that's why the status says that it's successful.

**Comment by wanghaoran1988** [comment]
@kargakis  Progressing condition is always True
```
status: "True"
type: Progressing
```

**Comment by kargakis** [comment]
That's because you are not requiring any pod to be available during the upgrade. This works as designed but we may want to revisit.

**Comment by wanghaoran1988** [comment]
Yes, as you said, I am not requiring any pod to be available, but if the upgrade failed within the `progressDeadlineSeconds`, we need fail the upgrade, right?

**Comment by kargakis** [comment]
We don't fail upgrades in Deployments.

**Comment by kargakis** [comment]
Also the upgrade didn't fail since you are not requiring any availability.

**Comment by wanghaoran1988** [comment]
@kargakis Thanks for your patient explain, will close this,not a bug.
