### ISSUE TITLE
Having API doc generated for CRD endpoint

### ISSUE THREAD

**Issue by ngtuna** [kubernetes/kubernetes#44660]
**Feature request**
I would like to see a way to generate API doc automatically for my CRD endpoint (example.k8s.io), then I can easily develop my app to interact with it.

**Kubernetes version** (use `kubectl version`):
v1.6.0

**Environment**:
minikube

**What happened**:
There is a `swagger.json` for k8s api doc out there but no support for cd endpoints

**What you expected to happen**:
If we can generate api doc for cdr endpoints automatically that would be awesome.

**Comment by liggitt** [comment]
c.f. kubernetes/features#95

**Comment by sttts** [comment]
Related discussion https://github.com/kubernetes/kubernetes/pull/55472
