### ISSUE TITLE
Migrate from github.com/docker/engine-api to github.com/docker/api

### ISSUE THREAD

**Issue by gaocegege** [kubernetes/kubernetes#44664]
**FEATURE REQUEST**

https://github.com/docker/engine-api/ has been deprecated 7 months ago, could we migrate to https://github.com/moby/moby/tree/master/api/types?

**What you expected to happen**:

Replace dockertypes and other imports from github.com/docker/engine-api to github.com/docker/api

**Comment by Random-Liu** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/34308.

**Comment by gaocegege** [comment]
Sorry for the dup :(
