### ISSUE TITLE
1.6.1 The connection to the server localhost:8080 was refused

### ISSUE THREAD

**Issue by fedya** [kubernetes/kubernetes#44665]
**Kubernetes version v1.6.1**

**Environment**:
- **arm64 cavium thunder x**:
- **Ubuntu 16.04.2 LTS**
- **4.4.0-72-generic**

**What happened**:
init kubernetes with
`kubeadm init --kubernetes-version=v1.6.1 --pod-network-cidr=10.244.0.0/16
`than tried
`kubectl taint nodes --all  node-role.kubernetes.io/master-
`and got this
`The connection to the server localhost:8080 was refused - did you specify the right host or port?
`

or this
```
# kubectl apply -f https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

or

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/arm64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

```

**Comment by csarora** [comment]
did you run below commands after kubeadm init

To start using your cluster, you need to run (as a regular user):

  sudo cp /etc/kubernetes/admin.conf $HOME/
  sudo chown $(id -u):$(id -g) $HOME/admin.conf
  export KUBECONFIG=$HOME/admin.conf

**Comment by sharif786** [comment]
Great..thanks.. it worked ..

**Comment by GoodFaithParadigm8** [comment]
Reproduce the same error when doing a tutorial from Udacity called Scalable Microservices with Kubernetes https://classroom.udacity.com/courses/ud615, at the point of Using Kubernetes, Part 3 of Lesson.

Launch a Single Instance:

`kubectl run nginx --image=nginx:1.10.0`

Error:

`Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.`

How I resolved the Error:

Login to Google Cloud Platform

Navigate to Container Engine Google Cloud Platform, Container Engine

Click CONNECT on Cluster

Use login Credentials to access Cluster [NAME] in your Teminal

Proceeded With Work!!!

**Comment by lithint** [comment]
on trying the command 
kubectl run --image=nginx nginx-app --port=80 --env="DOMAIN=cluster"


I am getting the following error.. what will be the reason

_The connection to the server localhost:8080 was refused - did you specify the right host or port?_

**Comment by pathakg** [comment]
solution from @csarora worked for me

**Comment by Venky8800** [comment]
Hi 
I'm getting this error can any one help me on this error: 
kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/arm64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

@csarora
csarora commented on Apr 19

did you run below commands after kubeadm init

To start using your cluster, you need to run (as a regular user):

sudo cp /etc/kubernetes/admin.conf $HOME/
sudo chown $(id -u):$(id -g) $HOME/admin.conf
export KUBECONFIG=$HOME/admin.conf
fedya closed this on Apr 19
@sharif786
sharif786 commented on May 5

Great..thanks.. it worked ..
@GoodFaithParadigm8
GoodFaithParadigm8 commented 29 days ago

Reproduce the same error when doing a tutorial from Udacity called Scalable Microservices with Kubernetes https://classroom.udacity.com/courses/ud615, at the point of Using Kubernetes, Part 3 of Lesson.

Launch a Single Instance:

kubectl run nginx --image=nginx:1.10.0

Error:

Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.

How I resolved the Error:

Login to Google Cloud Platform

Navigate to Container Engine Google Cloud Platform, Container Engine

Click CONNECT on Cluster

Use login Credentials to access Cluster [NAME] in your Teminal

Proceeded With Work!!!
@lithint
lithint commented 7 days ago

on trying the command
kubectl run --image=nginx nginx-app --port=80 --env="DOMAIN=cluster"

I am getting the following error.. what will be the reason

The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by Rukeith** [comment]
I didn't have `admin.conf`  
Did I miss something?

**Comment by jeffhoffman13** [comment]
admin.conf must come out of thin air.

DC/OS works much better out of the box this is as painful as any cloud console. YUCK!

**Comment by i7clock** [comment]
until 1.8 kubelet.conf worked for me @Rukeith @jeffhoffman13 
now this is missing for some reason...

**Comment by shaunlmason** [comment]
I'm having this issue after installing via gcloud on Travis CI.

**Comment by kensupermen** [comment]
I having this issue. I can't find `admin.conf`

**Comment by kopollo** [comment]
[http://localhost:8080/-](http://localhost.support:8080/-)

**Comment by MSKPV** [comment]
I can't find admin.conf what to do now plz help me

**Comment by igelkotten** [comment]
@kensupermen @MSKPV @Rukeith 

The admin.conf is generated when you run the init command and not the join command.

**Comment by italojs** [comment]
try run with ```sudo``` permission mode
 ```sudo kubectl....```

**Comment by igelkotten** [comment]
@italojs as I said... The admin.conf is generated when you run the init command and **not** the join command, atleast when i messed with it. You can type as much sudo you want. Joining a cluster wont generate the admin.conf.

**Comment by dipeshm01** [comment]
create .kube folder and a symlink on it to the directory which has the yaml files and pem file (k8s related)  and right smylink inside the .kube folder to right yml file - that should solve the problem...

**Comment by yassermog** [comment]
if you are using minikube then try 
$ minikube delete 
then 
$ minikube start

**Comment by glaceroy** [comment]
Hello All. Need your help. I have installed kubectl and minikube on my MAC but both are not working.

When I run minikube start I get an error "Segmentation fault: 11"

When I run kubectl get nodes I get an error "The connection to the server localhost:8080 was refused - did you specify the right host or port?"

Please can you help me fix this issue

**Comment by onlymuxia** [comment]
> did you run below commands after kubeadm init
> 
> To start using your cluster, you need to run (as a regular user):
> 
> sudo cp /etc/kubernetes/admin.conf $HOME/
> sudo chown $(id -u):$(id -g) $HOME/admin.conf
> export KUBECONFIG=$HOME/admin.conf

Thanks,it worked!

**Comment by venkatareddychalla** [comment]
please help me while installing node i am getting this error
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by prabhakarsultane** [comment]
There is a configuration issue, if you have setup kubernetes using root and trying to execute kubectl command from the different user then this error will occur.
To resolved this issue run simply below command
root@devops:~# cp -r .kube/ /home/ubuntu/

root@devops:~# chown -R ubuntu:ubuntu /home/ubuntu/.kube

root@devops:~# su ubuntu

root@devops:~# kubectl get pod -o wide

NAME READY STATUS RESTARTS AGE IP NODE NOMINATED NODE
cron 1/1 Running 0 2h 10.244.0.97 devops

**Comment by BRFord88** [comment]
To those that can't find admin.conf, hopefully this is relevant to your flavor of Linux, but I typically use:
> updatedb
> locate admin.conf
I was able to find the file this way, hope it helps you as well!

**Comment by cottrell** [comment]
> did you run below commands after kubeadm init
> 
> To start using your cluster, you need to run (as a regular user):
> 
> sudo cp /etc/kubernetes/admin.conf $HOME/
> sudo chown $(id -u):$(id -g) $HOME/admin.conf
> export KUBECONFIG=$HOME/admin.conf

This should be moved into the docs no? MIssing in the setup AFAIK

**Comment by levindoneto** [comment]
> did you run below commands after kubeadm init
> 
> To start using your cluster, you need to run (as a regular user):
> 
> sudo cp /etc/kubernetes/admin.conf $HOME/
> sudo chown $(id -u):$(id -g) $HOME/admin.conf
> export KUBECONFIG=$HOME/admin.conf

This worked, thanks 💯 

I executed these commands right after the following one for generating the certificates and token for adding nodes to this master later on:
```
kubeadm init --pod-network-cidr=10.244.0.0/16  --apiserver-advertise-address $MASTER_IP
```

**Comment by AdelBouridah** [comment]
> did you run below commands after kubeadm init
> 
> To start using your cluster, you need to run (as a regular user):
> 
> sudo cp /etc/kubernetes/admin.conf $HOME/
> sudo chown $(id -u):$(id -g) $HOME/admin.conf
> export KUBECONFIG=$HOME/admin.conf

It seem to be a very intersing track to take to get the connection non refused to the master. It may be added to some root manual. thinks

**Comment by csgcp** [comment]
I got this error on `kubectl get all` because there was no cluster created. After creating a cluster with `gcloud container clusters create` the error went away and the kubectl command worked.

**Comment by mpursley** [comment]
> [http://localhost:8080/](http://localhost.support/:8080)

@kopollo

http://localhost:8080/ -> http://localhost.support/:8080  ???

This looks like spam/fishing?  Can someone remove this comment?

**Comment by coderLinJ5945** [comment]
I used the k8s cluster installed by rancher, but I did not install kubeadm, how can I generate admin.conf?

**Comment by renjithkm86** [comment]
> did you run below commands after kubeadm init
> 
> To start using your cluster, you need to run (as a regular user):
> 
> sudo cp /etc/kubernetes/admin.conf $HOME/
> sudo chown $(id -u):$(id -g) $HOME/admin.conf
> export KUBECONFIG=$HOME/admin.conf

Thanks! That fixed my issue

**Comment by SunHarvey** [comment]
Because  slave node missing configuration file  “config”
Solution
master:
    mkdir -p $HOME/.kube
    cp -i /etc/kubernetes/admin.conf  $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube.conf
slave :
Copy files from remote master node ， and rename to config
    mkdir -p $HOME/.kube/
    scp root@matet:/etc/kubernetes/admin.conf   $HOME/.kube/config

**Comment by awsdevopro** [comment]
If you're using minikube, then you need to start the minikube and then it will be alright. 

$ minikube start

Once it's up and running, check the kubectl version

$ kubectl version 

Hope this helps

**Comment by xingzhefeng** [comment]
> cp /etc/kubernetes/admin.conf
cp /etc/kubernetes/admin.conf /root/.kube/config

**Comment by jonsys** [comment]
This issue was that I was using root account, switched back to regular user and executed the command which fixed my issue.

**Comment by soccerdroid** [comment]
If you are creating a cluster with more than 1 node (using kubeadm, k8s, ...) @SunHarvey solution works.

**Comment by g2github** [comment]
Someone might want to correct this page that directs the install user to check the kubectl install directly... https://kubernetes.io/docs/tasks/tools/install-kubectl/

**Comment by adarshaJha** [comment]
> did you run below commands after kubeadm init
> 
> To start using your cluster, you need to run (as a regular user):
> 
> sudo cp /etc/kubernetes/admin.conf $HOME/
> sudo chown $(id -u):$(id -g) $HOME/admin.conf
> export KUBECONFIG=$HOME/admin.conf

it is still showing the same error when i run` kubectl version`

**Comment by atiffarrukh** [comment]
If you are trying to run it on a VM then
1. delete the current minikube profile by running `minikube delete`
2. start minikube again with flags `minikube start --vm-driver=none`

**Comment by tianrenz2** [comment]
Try to check your /etc/kubernetes/manifests/kube-apiserver.yaml and see if "insecure-port" is set to 8080, in my case that's the reason.

**Comment by nightswimmings** [comment]
This happened to me because of my .kube/config file having wrong indentations

**Comment by ahmedgdoma** [comment]
> For example, if you are intending to run a Kubernetes cluster on your laptop (locally), you will need a tool like Minikube to be installed first and then re-run the commands stated above.

[kube documentation about this issue](https://kubernetes.io/docs/tasks/tools/install-kubectl/#verifying-kubectl-configuration)

**Comment by nimmnisanthosh** [comment]
> did you run below commands after kubeadm init
> 
> To start using your cluster, you need to run (as a regular user):
> 
> sudo cp /etc/kubernetes/admin.conf $HOME/
> sudo chown $(id -u):$(id -g) $HOME/admin.conf
> export KUBECONFIG=$HOME/admin.conf

it worked thanks

**Comment by andkhong** [comment]
What's the solution to this? I'm I get 

`chown: cannot access '/home/travis/.kube/config': No such file or directory` on Travis when following the instructions listed above...

**Comment by renukamanavalan** [comment]
I am running kubelet in standalone mode.
I manually created my  /var/lib/config.yaml
```
$ cat /var/lib/kubelet/config.yaml
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
    anonymous:
        enabled: true
    webhook:
        enabled: false
authorization:
    mode: AlwaysAllow
clusterDNS:
    - 127.0.0.53
clusterDomain: cluster.local
fileCheckFrequency: 20s
httpCheckFrequency: 20s
staticPodPath: /etc/kubernetes/manifests
enable-controller-attach-detach:
    - "false"

```
Manually created my static pod file and put it in staticPodPath.
It created the pods as expected.

I did not run "kubeadm init". There is no API server either. Hence no "admin.conf".

Running any kubelet command fails with `"The connection to the server localhost:8080 was refused"`.

But I need to create secrets, that is required to pull image from registry. 

Any tips on how I could accomplish this?

**Comment by rohitkumr** [comment]
> did you run below commands after kubeadm init
> 
> To start using your cluster, you need to run (as a regular user):
> 
> sudo cp /etc/kubernetes/admin.conf $HOME/
> sudo chown $(id -u):$(id -g) $HOME/admin.conf
> export KUBECONFIG=$HOME/admin.conf

I am getting this error 
sudo cp /etc/kubernetes/admin.conf $HOME/
sudo: error while loading shared libraries: libpam.so.0: cannot open shared object file: No such file or directory

**Comment by kertak90** [comment]
before execute your first command (kubectl get pods)
initialize kubectl(execute this comand)
sudo kubeadm init --pod-network-cidr=10.244.0.0/16

**Comment by yurmuki** [comment]
May be we need to run: minikube start
I had the same error "The connection to the server localhost:8080 was refused - did you specify the right host or port?"

<pre>root@book:/home/user# su - user
<font color="#4E9A06"><b>user@book</b></font>:<font color="#3465A4"><b>~</b></font>$ kubectl version -o json
{
  &quot;clientVersion&quot;: {
    &quot;major&quot;: &quot;1&quot;,
    &quot;minor&quot;: &quot;19&quot;,
    &quot;gitVersion&quot;: &quot;v1.19.2&quot;,
    &quot;gitCommit&quot;: &quot;f5743093fd1c663cb0cbc89748f730662345d44d&quot;,
    &quot;gitTreeState&quot;: &quot;clean&quot;,
    &quot;buildDate&quot;: &quot;2020-09-16T13:41:02Z&quot;,
    &quot;goVersion&quot;: &quot;go1.15&quot;,
    &quot;compiler&quot;: &quot;gc&quot;,
    &quot;platform&quot;: &quot;linux/amd64&quot;
  }
}
The connection to the server localhost:8080 was refused - did you specify the right host or port?


<font color="#4E9A06"><b>user@book</b></font>:<font color="#3465A4"><b>~</b></font>$ minikube start
😄  minikube v1.13.1 on Ubuntu 20.04
✨  Automatically selected the virtualbox driver
💿  Downloading VM boot image ...
    &gt; minikube-v1.13.1.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    &gt; minikube-v1.13.1.iso: 173.91 MiB / 173.91 MiB  100.00% 2.41 MiB p/s 1m12s
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.19.2 preload ...
    &gt; preloaded-images-k8s-v6-v1.19.2-docker-overlay2-amd64.tar.lz4: 486.36 MiB
🔥  Creating virtualbox VM (CPUs=2, Memory=3900MB, Disk=20000MB) ...
🔥  Deleting &quot;minikube&quot; in virtualbox ...
🤦  StartHost failed, but will try again: creating host: create: creating: /usr/bin/VBoxManage storagectl minikube --name SATA --add sata --hostiocache on failed:
VBoxManage: error: Storage controller named &apos;SATA&apos; already exists
VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: &quot;AddStorageController(Bstr(pszCtl).raw(), StorageBus_SATA, ctl.asOutParam())&quot; at line 1078 of file VBoxManageStorageController.cpp

🔥  Creating virtualbox VM (CPUs=2, Memory=3900MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.19.2 on Docker 19.03.12 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use &quot;minikube&quot; by default


<font color="#4E9A06"><b>user@book</b></font>:<font color="#3465A4"><b>~</b></font>$ kubectl version -o json
{
  &quot;clientVersion&quot;: {
    &quot;major&quot;: &quot;1&quot;,
    &quot;minor&quot;: &quot;19&quot;,
    &quot;gitVersion&quot;: &quot;v1.19.2&quot;,
    &quot;gitCommit&quot;: &quot;f5743093fd1c663cb0cbc89748f730662345d44d&quot;,
    &quot;gitTreeState&quot;: &quot;clean&quot;,
    &quot;buildDate&quot;: &quot;2020-09-16T13:41:02Z&quot;,
    &quot;goVersion&quot;: &quot;go1.15&quot;,
    &quot;compiler&quot;: &quot;gc&quot;,
    &quot;platform&quot;: &quot;linux/amd64&quot;
  },
  &quot;serverVersion&quot;: {
    &quot;major&quot;: &quot;1&quot;,
    &quot;minor&quot;: &quot;19&quot;,
    &quot;gitVersion&quot;: &quot;v1.19.2&quot;,
    &quot;gitCommit&quot;: &quot;f5743093fd1c663cb0cbc89748f730662345d44d&quot;,
    &quot;gitTreeState&quot;: &quot;clean&quot;,
    &quot;buildDate&quot;: &quot;2020-09-16T13:32:58Z&quot;,
    &quot;goVersion&quot;: &quot;go1.15&quot;,
    &quot;compiler&quot;: &quot;gc&quot;,
    &quot;platform&quot;: &quot;linux/amd64&quot;
  }
}
</pre>

**Comment by sreekanthadari** [comment]
> Great..thanks.. it worked ..

Thanks a lot, it worked for me aswell.

**Comment by mirekphd** [comment]
Threads like these are the reason why StackOverflow was invented...
