### ISSUE TITLE
1.6.1 setup on baremetal using rkt

### ISSUE THREAD

**Issue by dragoschiplink** [kubernetes/kubernetes#44663]
Hello,

Is there an example of running v1.6.1 on a baremetal Container Linux cluster using rkt as a runtime?

coreos-kubernetes is not updated :(

Is there any flags to setup for 1.6.1?

Regards.

Dragos

**Comment by JulienBalestra** [comment]
@dragoschiplink the needed flags are:
```
go/src/k8s.io/kubernetes/_output/bin/kubelet \
--network-plugin=cni \
--cni-bin-dir=/opt/bin/cni \
--cni-conf-dir=/etc/rkt/net.d \
--cloud-provider="" \
--enable-cri=false  \
--container-runtime=rkt \
--rkt-path=/usr/bin/rkt 
```
You can have a look to https://github.com/JulienBalestra/enjoliver

We use it at [blablacar](https://blablacar.com) in our baremetal datacenters.
Hope it helps !

**Comment by dragoschiplink** [comment]
Thanks!
