### ISSUE TITLE
GKE 1.5->1.6 upgrades fail basic StatefulSet functionality

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#44684]
Triage cluster: https://storage.googleapis.com/k8s-gubernator/triage/index.html#8f880cf0e42bc2e51142

Example testgrid dashboard: https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gke-container_vm-1.5-container_vm-1.6-upgrade-master&width=20&sort-by-failures=

Test owner: [undefined](https://github.com/kubernetes/kubernetes/blob/master/test/test_owners.csv)
Sig owner: [undefined](https://github.com/kubernetes/kubernetes/blob/master/test/test_owners.csv)

/assign @michelleN @mattfarina 

Failures look similar to:
```
node is not ready: &Node{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:n1-standard-1-gci-beta-56-9000-80-0-b1b01d6d,GenerateName:,Namespace:,SelfLink:/api/v1/nodesn1-standard-1-gci-beta-56-9000-80-0-b1b01d6d,UID:5a4f4781-2482-11e7-a60e-42010a80000b,ResourceVersion:59,Generation:0,CreationTimestamp:2017-04-18 21:59:53 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{beta.kubernetes.io/arch: amd64,beta.kubernetes.io/os: linux,kubernetes.io/hostname: n1-standard-1-gci-beta-56-9000-80-0-b1b01d6d,},Annotations:map[string]string{volumes.kubernetes.io/controller-managed-attach-detach: true,},OwnerReferences:[],Finalizers:[],ClusterName:,},Spec:NodeSpec{PodCIDR:,ExternalID:n1-standard-1-gci-beta-56-9000-80-0-b1b01d6d,ProviderID:gce:////8814967683446158800,Unschedulable:false,Taints:[],},Status:NodeStatus{Capacity:ResourceList{cpu: {{1 0} {<nil>} 1 DecimalSI},memory: {{3879407616 0} {<nil>} 3788484Ki BinarySI},pods: {{110 0} {<nil>} 110 DecimalSI},},Allocatable:ResourceList{cpu: {{1 0} {<nil>} 1 DecimalSI},memory: {{3617263616 0} {<nil>} 3532484Ki BinarySI},pods: {{110 0} {<nil>} 110 DecimalSI},},Phase:,Conditions:[{OutOfDisk False 2017-04-18 22:01:44 +0000 UTC 2017-04-18 21:59:53 +0000 UTC KubeletHasSufficientDisk kubelet has sufficient disk space available} {MemoryPressure False 2017-04-18 22:01:44 +0000 UTC 2017-04-18 21:59:53 +0000 UTC KubeletHasSufficientMemory kubelet has sufficient memory available} {DiskPressure False 2017-04-18 22:01:44 +0000 UTC 2017-04-18 21:59:53 +0000 UTC KubeletHasNoDiskPressure kubelet has no disk pressure} {Ready False 2017-04-18 22:01:44 +0000 UTC 2017-04-18 21:59:53 +0000 UTC KubeletNotReady could not locate kubenet required CNI plugins [bridge host-local loopback] at "/opt/cni/bin" or ""}],Addresses:[{LegacyHostIP 10.128.0.11} {InternalIP 10.128.0.11} {Hostname n1-standard-1-gci-beta-56-9000-80-0-b1b01d6d}],DaemonEndpoints:NodeDaemonEndpoints{KubeletEndpoint:DaemonEndpoint{Port:10250,},},NodeInfo:NodeSystemInfo{MachineID:1e6aca224f18cdf31fa0e0f838965c0c,SystemUUID:1E6ACA22-4F18-CDF3-1FA0-E0F838965C0C,BootID:34f162f2-c95b-4842-8084-56a472e1dcf2,KernelVersion:4.4.21+,OSImage:Container-Optimized OS from Google,ContainerRuntimeVersion:docker://1.11.2,KubeletVersion:v1.7.0-alpha.1.604+66776bebb027d7-dirty,KubeProxyVersion:v1.7.0-alpha.1.604+66776bebb027d7-dirty,OperatingSystem:linux,Architecture:amd64,},Images:[{[gcr.io/google_containers/node-problem-detector:v0.3.0] 290407887} {[gcr.io/google_containers/volume-nfs:0.8] 247146979} {[gcr.io/google_containers/volume-gluster:0.2] 212127750} {[gcr.io/google_containers/nginx-slim:0.7] 86838142} {[google/cadvisor:latest] 57318360} {[gcr.io/google_containers/hostexec:1.2] 13185747} {[gcr.io/google_containers/netexec:1.7] 8016035} {[gcr.io/google_containers/netexec:1.5] 7358440} {[gcr.io/google_containers/netexec:1.4] 7293444} {[gcr.io/google_containers/serve_hostname:v1.4] 6222101} {[gcr.io/google-containers/stress:v1] 5494760} {[gcr.io/google_containers/test-webserver:e2e] 4534272} {[gcr.io/google_containers/liveness:e2e] 4387474} {[gcr.io/google_containers/eptest:0.1] 2970692} {[gcr.io/google_containers/mounttest:0.8] 1450761} {[gcr.io/google_containers/mounttest-user:0.5] 1450761} {[gcr.io/google_containers/busybox@sha256:4bdd623e848417d96127e16037743f0cd8b528c026e9175e22a84f639eca58ff gcr.io/google_containers/busybox:1.24] 1113554} {[gcr.io/google_containers/pause-amd64:3.0] 746888}],VolumesInUse:[],VolumesAttached:[],},}
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/e2e_node_suite_test.go:226
```

**Comment by fejta** [comment]
This remains unresolved. Expectations:
* This work should interrupt and take priority over other activity while it is assigned to you.
* Expectation for sig leads is to identify someone to fix the issue, `/assign` them and `/unassign` yourself.
* Expectation for assignees are to investigate the issue and either a) resolve it or b) `/assign` it to a more appropriate person and b) `/unassign` yourself.

**sig owners failed to respond within a week*
/unassign @michelleN @mattfarina 

Per experiment assigning apps issues to a single person on workloads in a round robin fashion, 
/assign @enisoc
Please identify the correct person to fix this issue, `/assign` that person and `/unassign` yourself.

**Comment by enisoc** [comment]
Sending to one of the owners of StatefulSet.

/assign @kow3ns 
/unassign

**Comment by smarterclayton** [comment]
@kargakis @foxish in case one of us gets to it tomorrow

**Comment by kow3ns** [comment]
The test infrastructure appears to be broken in general. There are clustered test failures across the grid [for example](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-container_vm-1.5-container_vm-1.6-upgrade-master/461). The StatefulSet one, which is intermittent, will be resolved when we cherry pick  #44730 into 1.6.

**Comment by kow3ns** [comment]
@kubernetes/test-infra-maintainers I can probably help with issue from the comment above but first we need to fix quota limits 

> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:75
Apr 27 17:52:31.645: Failed to allocated static ip e2e-tests-ingress-upgrade-1pxjn-static-ip: googleapi: Error 403: Quota 'STATIC_ADDRESSES' exceeded. Limit: 7.0, quotaExceeded
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/ingress_utils.go:732

**Comment by fejta** [comment]
Which project needs more quota?

**Comment by fejta** [comment]
@rmmh triage cluster seems gone so I'm closing the issue (maybe the #45113 fixed things??)
