### ISSUE TITLE
kubeadm must pull from the gcr?

### ISSUE THREAD

**Issue by xuchenhao001** [kubernetes/kubernetes#44694]
**Is this a request for help?** 
Yes

**What keywords did you search in Kubernetes issues before filing this one?** 
`kubeadm init`, Created API client,

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

There is a limitation in China. We cannot access gcr.io, but nether kubeadm nor Minikube cannot deploy locally.
I have loaded all required images into docker (after download from dockerhub or somewhere else), but kubeadm still try to connect to gcr.io. I think it's better to set an argument for offline. 

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: bare metal
- **OS** (e.g. from /etc/os-release): ubuntu 16.04 LTS
- **Kernel** (e.g. `uname -a`): Linux ubuntu 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubeadm
- **Others**: 

**What happened**:
`kubeadm init` hang up at
[apiclient] Created API client, waiting for the control plane to become ready

and `journalctl -f -u docker` :
Get https://gcr.io/v1/_ping: dial tcp 108.177.97.82:443: i/o timeout

and `docker images`:
> docker images
REPOSITORY                                               TAG                 IMAGE ID            CREATED             SIZE
gcr.io/google-containers/kube-proxy-amd64                v1.6.0              746d1460005f        3 weeks ago         109.2 MB
gcr.io/google-containers/kube-controller-manager-amd64   v1.6.0              dc78cc207023        3 weeks ago         132.7 MB
gcr.io/google-containers/kube-apiserver-amd64            v1.6.0              6a29f77d1186        3 weeks ago         150.5 MB
gcr.io/google-containers/kube-scheduler-amd64            v1.6.0              dc03ae0150c9        3 weeks ago         76.75 MB
gcr.io/google_containers/k8s-dns-sidecar-amd64           1.14.1              fc5e302d8309        7 weeks ago         44.52 MB
gcr.io/google_containers/k8s-dns-kube-dns-amd64          1.14.1              f8363dbf447b        7 weeks ago         52.36 MB
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64     1.14.1              1091847716ec        7 weeks ago         44.85 MB
gcr.io/google-containers/etcd-amd64                      3.0.17              243830dae7dd        7 weeks ago         168.9 MB
gcr.io/google-containers/pause-amd64                     3.0                 99e59f495ffa        11 months ago       746.9 kB

**What you expected to happen**:
kubeadm init successfully

**How to reproduce it** (as minimally and precisely as possible):
Load all images into docker and `kubeadm init` in China or offline

**Anything else we need to know**:

**Comment by dunjut** [comment]
You can run `<k8s-dir>/cluster/get-kube-binaries.sh` to download client and server binaries.

After that, use `docker load -i kube-xx.tar` to load images.

**Comment by russellballestrini** [comment]
I'm working on standing up a kubernetes cluster in China and running into similar issues.

I'm about to try using this ENV var:

```
KUBE_REPO_PREFIX	gcr.io/google_containers	The image prefix for all images that are used.
```

Reference: https://kubernetes.io/docs/admin/kubeadm/

daocloud.io

**Comment by kargakis** [comment]
@kubernetes/sig-cluster-lifecycle-misc

**Comment by roberthbailey** [comment]
Please close this issue and re-open in the [kubeadm repository](https://github.com/kubernetes/kubeadm)

**Comment by imriss** [comment]
Could you please post the link to the issue that was re-opened in the [kubeadm repository](https://github.com/kubernetes/kubeadm)? Thanks.

**Comment by luxas** [comment]
If there doesn't exist one @imriss, please create one. Quick tip, if you're using kubeadm v1.8 (preferable), you can set `.imageRepository` in the config file and images will be pulled from there.
See also: https://kubernetes.io/docs/admin/kubeadm/

**Comment by xuchenhao001** [comment]
@imriss Thanks for your attention!
Now I'm using kubeadm 1.8 offline init by this command after manually load all of the images into docker:
```
$ kubeadm init --kubernetes-version v1.8.0  --pod-network-cidr=10.244.0.0/16
```
The offline images are:
```
gcr.io/google_containers/etcd-amd64:3.0.17
quay.io/coreos/flannel:v0.8.0-amd64
gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.5
gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.5
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.5
gcr.io/google_containers/kube-apiserver-amd64:v1.8.0
gcr.io/google_containers/kube-controller-manager-amd64:v1.8.0
gcr.io/google_containers/kube-proxy-amd64:v1.8.0
gcr.io/google_containers/kube-scheduler-amd64:v1.8.0
gcr.io/google_containers/pause-amd64:3.0

# Optional
gcr.io/google_containers/kubernetes-dashboard-amd64:v1.7.1
```
That's just for k8s 1.8.0, with pod network `flannel v0.8.0`.
:smile:

**Comment by imriss** [comment]
Thanks @xuchenhao001 and @luxas :)
