### ISSUE TITLE
"make test" causes incoming network connections prompts on macOS

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes#44690]
I am using Mac OS X 10.12.4 Sierra and when I run `make test` on master, I get these network prompts (Firewall:On):

> ![image](https://cloud.githubusercontent.com/assets/159209/25205572/2488aa32-2518-11e7-850e-3e9e9a03507b.png)

This does not interrupt the tests as they keep succeeding even when you _Deny_.
 
As far as I know, this happens when an application starts listening for connections on all interfaces instead of a particular interface or localhost (127.0.0.1).

**Comment by fejta** [comment]
/remove-sig testing
Looks like these are pkg/proxy, which I believe is @kubernetes/sig-network-misc

**Comment by smarterclayton** [comment]
These are actually caused by the unit tests (go unit tests) starting an http server.  We launch an etcd server in some of them, although that typically uses the unix domain socket.

**Comment by ahmetb** [comment]
We can close this if it's not high priority enough to support `make test` on macOS. It's unfortunate macOS doesn't allow suppressing these pop-ups (and they're per-binary based to whitelist, which is nearly impossible with test binaries).

**Comment by smarterclayton** [comment]
I haven't seen this happen locally.  Is this the latest patch release?

**Comment by ahmetb** [comment]
It was `master` branch at the time of opening the issue.

**Comment by smarterclayton** [comment]
I mean the latest patch release of Mac
