### ISSUE TITLE
Clean up garbage logs we print out in large tests

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#44707]
We currently print out a lot of garbage that takes ever 3/4 of test logs and makes it annoying to read. Stuff that should be minimized:
- `get nodes` output from the beginning of the tests
- waiting for prepuller to finish shouldn't log status of every single one of them ever X seconds, only aggregates
- netcheck should print out results to separate file in TestContext.ReportDir, instead of main log file
- performance test results metrics, should use 'Summary' (e2e/framework one) interface, so it'd be automatically printed to separate file.

@kubernetes/sig-scalability-misc @wojtek-t @shyamjvs

**Comment by wojtek-t** [comment]
If we would split 1. `get nodes` 2. netcheck result
to separate files, that would solve most of our problems.

And that should be pretty simple to do, I think.

**Comment by wojtek-t** [comment]
@kubernetes/test-infra-maintainers

**Comment by gmarek** [comment]
Get nodes and netcheck results are no longer in logs.

**Comment by wojtek-t** [comment]
I removed a bit more in #44761 

Also to clarify, get nodes is removed in the code, but i think we need to push some new image for testing or sth like that.

**Comment by fejta** [comment]
Changes in kuberneres/kuberneres do not require a new image. 

Kubetest changes do though.

**Comment by wojtek-t** [comment]
@gmarek - is this fixed now? Can we close this? If not what is remaining?

**Comment by gmarek** [comment]
I think it's done.
