### ISSUE TITLE
kubelet reports wrong IP address

### ISSUE THREAD

**Issue by dunjut** [kubernetes/kubernetes#44702]
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: VirtualBox
- **OS** (e.g. from /etc/os-release): Ubuntu:14.04
- **Kernel** (e.g. `uname -a`): 3.16.0-30-generic
- **Install tools**: Manually installed. etcd and kubelet run on host, other components run in container.
- **Others**:

**What happened**:
In my kubernetes cluster, each node is a virtualbox vm with two NICs, eth0 for NAT and eth1 for Host-Local communicating.

kubectl get pod --all-namespaces -o wide shows

![image](https://cloud.githubusercontent.com/assets/3380642/25217908/4392efa0-25db-11e7-97bb-e93b0952f20a.png)

We can see k8s-3 and k8s-4 reports correct IPs while k8s-2 doesn't.

**What you expected to happen**:
k8s-2 should have IP address 192.168.99.202.
I've tried to add --bind-address=192.168.99.202 in k8s-2's kube-proxy.yaml but it just don't work.

**How to reproduce it** (as minimally and precisely as possible):
I just install the cluster normally, but k8s-2 behaves differently to k8s-3 and k8s-4. It's really hard to say 'how to reproduce it'.

**Anything else we need to know**:

**Comment by freehan** [comment]
Does `kube-proxy-k8s-2` run in host network?
Where is the ip 10.0.2.15 come from? the container bridge?

**Comment by dunjut** [comment]
@freehan `kube-proxy-k8s-2` runs on node with two NICs, `eth0` for NAT (which is where ip 10.0.2.15 come from) and `eth1` for host-only network.

**Comment by freehan** [comment]
do the nodes running `kube-proxy-k8s-3` and `kube-proxy-k8s-4` has 2 NICs?

what does `docker inspect` for the kube-proxys looks like?

**Comment by dunjut** [comment]
1) Yes, Both `k8s-3` and `k8s-4` have 2 NICs, same as `k8s-2`.

2) `docker inspect kube-proxy-k8s-2` [result](https://gist.github.com/dunjut/b19bb0ff668e636774e43891d0e99760)

`docker inspect kube-proxy-k8s-3` [result](https://gist.github.com/dunjut/c52b8ff58c10fdcf2def2502b722fac3)

**Comment by freehan** [comment]
Okay. I think kubelet is not able to obtain the node IP address correctly. It may get confused for 2 NICs cases.

Can you post the output of `kubectl get node {NODE} -o yaml` for 2 nodes? 1 running `kube-proxy-k8s-2` and 1 running `kube-proxy-k8s-3`? Just to confirm

**Comment by dunjut** [comment]
* `kubectl get node k8s-2 -o yaml` [https://gist.github.com/dunjut/4161277c75269814dd64eab11f9d7735](result)

* `kubectl get node k8s-3 -o yaml` [https://gist.github.com/dunjut/d6e85eb62f8943f2d6da7c05537cfca7](result)

**Comment by freehan** [comment]
Yeah. As I suspected, node `k8s-2` takes 10.0.2.15 as the internal IP. Hence kube-proxy gets it. 

@dunjut Is this causing other problems?

cc: @yujuhong

**Comment by yujuhong** [comment]
kubelet uses the [IP address reported by the cloud provider](https://github.com/kubernetes/kubernetes/blob/v1.6.2/pkg/kubelet/kubelet_node_status.go#L394) if it exists, or the first non-loopback ipv4 address ([code here](https://github.com/kubernetes/kubernetes/blob/v1.6.2/pkg/kubelet/kubelet_node_status.go#L440)) if there is no cloud provider. In addition, it could be overwritten by kubelet flags. 

You might want to check if there are any differences in your nodes.

**Comment by dcbw** [comment]
@dunjut so given all this info, the issue is in how kubelet finds its own IP address, not about kube-proxy.  So --bind-address won't really work, because that's a kube-proxy option and the proxy is running in a pod that already has the wrong address.

If you're not using a cloud provider, try modifying the kubelet command-line options to pass "--node-ip=<desired node IP>" or setting the NodeIP configuration in the kubelet config yaml file.

**Comment by dunjut** [comment]
Thanks. Problem solved by passing `--node-ip=` to kubelet.
