### ISSUE TITLE
Can't add windows node to kubernetes cluster

### ISSUE THREAD

**Issue by renerchen** [kubernetes/kubernetes#44705]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
1.5.3

**What happened**:
I can't add windows node to kubernetes cluster.
** Description**
Now, I deploy on kubernets master on a linux node, the start config of master components is following:

/opt/bin/kube-scheduler --logtostderr=true --master=127.0.0.1:8080
/opt/bin/kube-apiserver --insecure-bind-address=0.0.0.0 --insecure-port=8080 --etcd-servers=http://127.0.0.1:4001 --logtostderr=true --service-cluster-ip-range=192.168.3.0/24 --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota --service-node-port-range=30000-32767 --advertise-address=10.183.201.66 --allow-privileged=true --client-ca-file=/srv/kubernetes/ca.crt --tls-cert-file=/srv/kubernetes/server.cert --tls-private-key-file=/srv/kubernetes/server.key
/opt/bin/kube-controller-manager --master=127.0.0.1:8080 --root-ca-file=/srv/kubernetes/ca.crt --service-account-private-key-file=/srv/kubernetes/server.key --logtostderr=true

Then, I start kublet on a windows node with the command:
.\kubelet.exe --hostname-override=10.141.38.252 --pod-infra-container-image=apprenda/pause --resolv-conf= --api-servers=http://10.183.201.66:8080 --cluster-dns=192.168.3.10

The error is :
PS C:\k> .\kubelet.exe --hostname-override=10.141.38.252 --pod-infra-container-image=apprenda/pause --resolv-conf= --api-servers=http://10.183.201.66:8080 --cluster-dns=192.168.3.10
Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
I0420 14:52:48.238468 816 feature_gate.go:189] feature gates: map[]
W0420 14:52:48.252143 816 server.go:605] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: GetFileAttributesEx /var/lib/kubelet/kubeconfig: The system cannot find the file specified.. Using default client config instead.
I0420 14:52:48.253120 816 docker.go:376] Start docker client with request timeout=2m0s
E0420 14:52:48.254093 816 cni.go:163] error updating cni config: No networks found in /etc/cni/net.d
E0420 14:52:48.255069 816 server.go:459] Kubelet needs to run as uid 0. It is being run as -1
W0420 14:52:48.255069 816 server.go:469] setting OOM scores is unsupported in this build
I0420 14:52:48.255069 816 kubelet.go:252] Watching apiserver
W0420 14:52:48.258980 816 iptables.go:143] Error checking iptables version, assuming version at least 1.4.11: executable file not found in %PATH%
W0420 14:52:48.258980 816 kubelet_network.go:69] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
I0420 14:52:48.259986 816 kubelet.go:477] Hairpin mode set to "hairpin-veth"
W0420 14:52:48.262884 816 plugins.go:210] can't set sysctl net/bridge/bridge-nf-call-iptables: open /proc/sys/net/bridge/bridge-nf-call-iptables: The system cannot find the path specified.
I0420 14:52:48.270695 816 docker_manager.go:256] Setting dockerRoot to C:\ProgramData\docker
I0420 14:52:48.270695 816 docker_manager.go:259] Setting cgroupDriver to
E0420 14:52:48.271671 816 server.go:730] Cannot read keys quota in /proc/sys/kernel/keys/root_maxkeys
E0420 14:52:48.271671 816 kubelet.go:1145] Image garbage collection failed: invalid capacity 0 on device "" at mount point ""
E0420 14:52:48.271671 816 server.go:746] Cannot read keys bytes in /proc/sys/kernel/keys/root_maxbytes
I0420 14:52:48.271671 816 server.go:770] Started kubelet v1.5.3
I0420 14:52:48.272642 816 server.go:123] Starting to listen on 0.0.0.0:10250
I0420 14:52:48.272642 816 kubelet_node_status.go:204] Setting node annotation to enable volume controller attach/detach
E0420 14:52:48.275579 816 kubelet.go:1634] Failed to check if disk space is available for the runtime: could not determine capacity for "runtime" fs. Info: {Usage:0 Capacity:0 Available:0 Timestamp:2017-04-20 14:52:48.2755797 +0800 CST}
E0420 14:52:48.276560 816 kubelet.go:1642] Failed to check if disk space is available on the root partition: could not determine capacity for "root" fs. Info: {Usage:0 Capacity:0 Available:0 Timestamp:2017-04-20 14:52:48.27656 +0800 CST}
I0420 14:52:48.276560 816 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
I0420 14:52:48.276560 816 status_manager.go:129] Starting to sync pod status with apiserver
I0420 14:52:48.276560 816 volume_manager.go:242] Starting Kubelet Volume Manager
I0420 14:52:48.276560 816 kubelet.go:1714] Starting kubelet main sync loop.
I0420 14:52:48.276560 816 kubelet.go:1725] skipping pod synchronization - [container runtime is down]
E0420 14:52:48.277532 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:52:48.280467 816 kubelet_network.go:274] Failed to ensure that nat chain KUBE-MARK-DROP exists: error creating chain "KUBE-MARK-DROP": executable file not found in %PATH%:
I0420 14:52:48.377144 816 kubelet_node_status.go:204] Setting node annotation to enable volume controller attach/detach
E0420 14:52:48.378118 816 kubelet.go:1634] Failed to check if disk space is available for the runtime: could not determine capacity for "runtime" fs. Info: {Usage:0 Capacity:0 Available:0 Timestamp:2017-04-20 14:52:48.2755797 +0800 CST}
E0420 14:52:48.378118 816 kubelet.go:1642] Failed to check if disk space is available on the root partition: could not determine capacity for "root" fs. Info: {Usage:0 Capacity:0 Available:0 Timestamp:2017-04-20 14:52:48.27656 +0800 CST}
I0420 14:52:48.378118 816 kubelet_node_status.go:74] Attempting to register node 10.141.38.252
E0420 14:52:58.278771 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:53:12.369956 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:53:22.370221 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:53:32.370483 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:53:42.370745 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:53:48.284967 816 kubelet_network.go:274] Failed to ensure that nat chain KUBE-MARK-DROP exists: error creating chain "KUBE-MARK-DROP": executable file not found in %PATH%:
E0420 14:53:52.371012 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:54:02.373220 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:54:12.373484 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:54:22.373745 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:54:32.374003 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:54:42.374268 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:54:48.290436 816 kubelet_network.go:274] Failed to ensure that nat chain KUBE-MARK-DROP exists: error creating chain "KUBE-MARK-DROP": executable file not found in %PATH%:
E0420 14:54:52.374529 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:55:02.374795 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:55:12.377003 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:55:22.377265 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:55:32.377535 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:55:42.379744 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:55:48.295915 816 kubelet_network.go:274] Failed to ensure that nat chain KUBE-MARK-DROP exists: error creating chain "KUBE-MARK-DROP": executable file not found in %PATH%:
E0420 14:55:52.380006 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:56:02.380265 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:56:12.380527 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:56:22.380788 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:56:32.381050 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:56:42.382798 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:56:48.303036 816 kubelet_network.go:274] Failed to ensure that nat chain KUBE-MARK-DROP exists: error creating chain "KUBE-MARK-DROP": executable file not found in %PATH%:
E0420 14:56:52.383204 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:57:03.228216 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:57:13.228419 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:57:23.228425 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:57:33.228429 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:57:43.228434 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:57:48.280193 816 kubelet.go:1145] Image garbage collection failed: invalid capacity 0 on device "" at mount point ""
E0420 14:57:53.225506 816 kubelet_network.go:274] Failed to ensure that nat chain KUBE-MARK-DROP exists: error creating chain "KUBE-MARK-DROP": executable file not found in %PATH%:
E0420 14:57:53.228435 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:58:03.231377 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:58:13.233330 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:58:23.233400 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:58:33.233471 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:58:43.233537 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:58:53.228725 816 kubelet_network.go:274] Failed to ensure that nat chain KUBE-MARK-DROP exists: error creating chain "KUBE-MARK-DROP": executable file not found in %PATH%:
E0420 14:58:53.233611 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:59:03.234660 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:59:13.235699 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found
E0420 14:59:23.235765 816 eviction_manager.go:205] eviction manager: unexpected err: failed GetNode: node '10.141.38.252' not found

How to fix it?

**Comment by renerchen** [comment]
@smarterclayton @brendandburns @wojtek-t Do you know why？

**Comment by kargakis** [comment]
@kubernetes/sig-node-bugs

**Comment by feiskyer** [comment]
@renerchen Could you remove "--hostname-override" from kubelet config and try again? Override hostname may cause problems on some cases.

**Comment by rjmorse** [comment]
This issue should likely be closed for staleness.

**Comment by feiskyer** [comment]
closed based on https://github.com/kubernetes/kubernetes/issues/44705#issuecomment-361113428
