### ISSUE TITLE
Allow `--all-namespaces=true` for `kubectl delete`

### ISSUE THREAD

**Issue by cilerler** [kubernetes/kubernetes#44718]
**FEATURE REQUEST**

Not be able to use line below

```
kubectl delete services,deployments -l app=app1 --all-namespaces 
```

forces us to do this

```
kubectl delete services,deployments -l app=app1 --namespace=ns1
---
kubectl delete services,deployments -l app=app1 --namespace=ns2
---
kubectl delete services,deployments -l app=app1 --namespace=ns3
```

I would go to 20 but I believe you get the idea 😉 

**Kubernetes version**
Client v1.5.4
Server v1.6.1

**Comment by liggitt** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by liggitt** [comment]
deletion across all namespaces can be really destructive... since we can't prompt or warn, this makes it easy to fat-finger a cluster destroying action

**Comment by cilerler** [comment]
I hear you, however since it will be an optional feature we should be fine.  😎

**Comment by liggitt** [comment]
> since it will be an optional feature we should be fine. 😎

until tab-completion makes someone who meant to do --all delete everything in their cluster :-/

**Comment by smarterclayton** [comment]
Yeah, I'm fairly sure this should require an additional confirmation.
Delete in general is too powerful by default.

**Comment by xiangpengzhao** [comment]
Users might prefer `--namespace=ns1, ns2, ns3` to `--all-namespaces` for delete command. Take care of your `kube-system` :)

BTW, do we support such format `--namespace=ns1, ns2, ns3` now?

**Comment by cilerler** [comment]
@xiangpengzhao nope

**Comment by bgrant0607** [comment]
Dupe of #18282
