### ISSUE TITLE
hostPath containing mounts do not update as they change on the host

### ISSUE THREAD

**Issue by keegancsmith** [kubernetes/kubernetes#44713]
**Kubernetes version**: 
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS**: Container-Optimized OS
- **Kernel**: 4.4.21+

**What happened**: https://github.com/keegancsmith/kubernetes-disk-exporter/blob/master/disk-exporter.yaml#L44 uses a `hostPath` of `/var/lib/kubelet/plugins/kubernetes.io/gce-pd/mounts`. It monitors the disk usage of each mount and exposes prometheus metrics for them. When the pod starts up, it has a valid mapping of all the mounted volumes. However, as time goes on and volumes on the node are mounted and unmounted, the volumes visible to `kubernetes-disk-exporter` remains static.

**What you expected to happen**: As the nodes volumes mounted under `/var/lib/kubelet/plugins/kubernetes.io/gce-pd/mounts` change, they should be updated in the `kubernetes-disk-exporter` hostPath to the same directory.

**How to reproduce it** (as minimally and precisely as possible): 
* Deploy https://github.com/keegancsmith/kubernetes-disk-exporter/blob/master/disk-exporter.yaml
* Visit `http://pod:9200/metrics` and observe metrics related to disk usage
* Deploy a pod with a mounted persistent GCE volume
* Revisit `http://pod:9200/metrics` for the pod on the same node as above. Observe it does not reflect disk usage.

**Anything else we need to know**:

I have debugged the reason to the above mentioned, rather than a bug in the kubernetes-disk-exporter code. Issue in kubernetes-disk-exporter repo https://github.com/keegancsmith/kubernetes-disk-exporter/issues/1

**Comment by wongma7** [comment]
This has to do with mount propagation. I don't believe kubernetes does anything special to ensure docker volume bindings have a given propagation setting so the propagation setting for the hostPath volume binding depends what the setting is for Docker on the host. I'm guessing it's (r)private right now, you are observing that it recursively bind mounts all binds at the beginning but new mount events on the host at /var/lib/kubelet/plugins/kubernetes.io/gce-pd/mounts won't be propagated to the pod.

Don't have a solution to offer, will let somebody more familiar with mount propagation and such do that...

**Comment by saad-ali** [comment]
+1 to what @wongma7. This is something that has been considered, see https://github.com/kubernetes/community/blob/master/contributors/design-proposals/propagation.md and discussion in https://github.com/kubernetes/community/pull/193/files

**Comment by keegancsmith** [comment]
@wongma7 thank you that makes a lot of sense. @saad-ali thanks for the linkage to further information.

**Comment by champsaurav** [comment]
@keegancsmith let me know if you got any solution for this? As per my understanding cadvisor doesn't give pv stats. 

But what can be done is running disk stats collector code in daemonsets. The code also check for the directories in the mount point and also in df -h output. If both are not equal it will kill the service running as process id 1 from code. As doing this will restart the pod and mount will get updated properly, so that will get the correct metrics of disk usage.

Note: This is only helpful when  pods using persistent volume don't crash too often. so daemonsets pods will only restart when a volume is removed or added in host path.

**Comment by jqmichael** [comment]
[mount-propagation](https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation)
> HostToContainer - This volume mount will receive all subsequent mounts that are mounted to this volume or any of its subdirectories.
> 
> In other words, if the host mounts anything inside the volume mount, the container will see it mounted there.

> Similarly, if any Pod with Bidirectional mount propagation to the same volume mounts anything there, the container with HostToContainer mount propagation will see it.
> 
> This mode is equal to rslave mount propagation as described in the [Linux kernel documentation](https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt)
