### ISSUE TITLE
Concurrent map writes errors in dns.go

### ISSUE THREAD

**Issue by etiennetremel** [kubernetes/kubernetes#44711]
**BUG REPORT**

There is a bug in the `pkg/dns.go` file causing the kubedns container to throw `concurrent map writes` error. We need to use safe concurrent Read/Write operations for maps.

I'm using the following container:
```eu.gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.1```

The full _kube-dns logs_ is available here: https://gist.github.com/etiennetremel/622e14bc77375c8f3d256901896439cb

**Kubernetes version**:

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

Cluster running on GKE with following environment:

```
Capacity:
 cpu:		4
 memory:	26711244Ki
 pods:		110
Allocatable:
 cpu:		4
 memory:	26711244Ki
 pods:		110
System Info:
 Kernel Version:		4.4.21+
 OS Image:			Container-Optimized OS from Google
 Operating System:		linux
 Architecture:			amd64
 Container Runtime Version:	docker://1.11.2
 Kubelet Version:		v1.6.1
 Kube-Proxy Version:		v1.6.1
PodCIDR:			10.248.21.0/24
```

**Comment by liggitt** [comment]
thanks for the issue report, but please file it against https://github.com/kubernetes/dns/

**Comment by liggitt** [comment]
cc @MrHohn

**Comment by MrHohn** [comment]
cc @bowei

**Comment by MrHohn** [comment]
Seems like the root cause is https://github.com/kubernetes/dns/blob/master/pkg/dns/dns.go#L504.
