### ISSUE TITLE
Describers should be able to print objects from somewhere besides the server

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#4471]
Generation and templating (and user review) both benefit from being able to describe objects on disk.  Our describer implementations should probably expose a method DescribeObject(...) that can be invoked to display a single item of that type (with or without making API calls to the server, but probably without).

**Comment by thockin** [comment]
Is "describe" actually useful without the server to make related joins?

**Comment by smarterclayton** [comment]
Yes - purely to see what you're going to be creating seeing the pod template visualized is really important.  We can always make people read JSON, but i think that's not all.

----- Original Message -----
