### ISSUE TITLE
Kubdns Deployment Is Deleted After 8 Minutes

### ISSUE THREAD

**Issue by spirrello** [kubernetes/kubernetes#44724]
**Kubernetes version**
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
Centos 7
- **Kernel**
Linux at4d-lvk8s01 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
Ansible

**What happened**:
When I run the deployment for Kubedns it launches successfully however, at exactly after 8 minutes of uptime, it is deleted.  When it is running it works fine in resolving dns requests..

**What you expected to happen**:
To stay running.

**How to reproduce it** (as minimally and precisely as possible):
I run the deployment for kubedns and this happens every time.

**Anything else we need to know**:
I have three masters and two nodes.  The logs from the controller-manager and pods are attached as well as the deployment fils.
[controller-logs.txt](https://github.com/kubernetes/kubernetes/files/943507/controller-logs.txt)
[pod-logs.txt](https://github.com/kubernetes/kubernetes/files/943510/pod-logs.txt)

[kubedns-deployment.txt](https://github.com/kubernetes/kubernetes/files/943527/kubedns-deployment.txt)
[kubedns-service.txt](https://github.com/kubernetes/kubernetes/files/943528/kubedns-service.txt)

**Comment by spirrello** [comment]
Starting to see the same behavior with other deployments.

Apr 20 17:52:19 acme-lvk8s01 kube-controller-manager[912]: I0420 17:52:19.959555     912 event.go:217] Event(api.ObjectReference{Kind:"Deployment", Namespace:"kube-system", Name:"monitoring-influxdb", UID:"198a7c61-25f2-11e7-afbe-90b8d0f6559c", APIVersion:"extensions", ResourceVersion:"302467", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set monitoring-influxdb-957705310 to 1
Apr 20 17:52:20 acme-lvk8s01 kube-controller-manager[912]: I0420 17:52:20.023682     912 event.go:217] Event(api.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"monitoring-influxdb-957705310", UID:"19908a65-25f2-11e7-afbe-90b8d0f6559c", APIVersion:"extensions", ResourceVersion:"302468", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: monitoring-influxdb-957705310-v040r
Apr 20 17:52:20 acme-lvk8s01 kube-controller-manager[912]: I0420 17:52:20.065652     912 deployment_controller.go:298] Error syncing deployment kube-system/monitoring-influxdb: Operation cannot be fulfilled on deployments.extensions "monitoring-influxdb": the object has been modified; please apply your changes to the latest version and try again
Apr 20 17:53:04 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:04.109330     912 event.go:217] Event(api.ObjectReference{Kind:"Deployment", Namespace:"kube-system", Name:"monitoring-grafana", UID:"19036105-25f2-11e7-afbe-90b8d0f6559c", APIVersion:"extensions", ResourceVersion:"302617", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled down replica set monitoring-grafana-3730655072 to 0
Apr 20 17:53:04 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:04.112338     912 replica_set.go:512] Too many "kube-system"/"monitoring-grafana-3730655072" replicas, need 0, deleting 1
Apr 20 17:53:04 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:04.112432     912 controller_utils.go:523] Controller monitoring-grafana-3730655072 deleting pod kube-system/monitoring-grafana-3730655072-dh3w2
Apr 20 17:53:04 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:04.183506     912 deployment_controller.go:298] Error syncing deployment kube-system/monitoring-grafana: Operation cannot be fulfilled on deployments.extensions "monitoring-grafana": the object has been modified; please apply your changes to the latest version and try again
Apr 20 17:53:04 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:04.189311     912 event.go:217] Event(api.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"monitoring-grafana-3730655072", UID:"1909dcad-25f2-11e7-afbe-90b8d0f6559c", APIVersion:"extensions", ResourceVersion:"302618", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: monitoring-grafana-3730655072-dh3w2
Apr 20 17:53:07 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:07.363250     912 deployment_controller.go:322] Deployment has been deleted kube-system/monitoring-grafana
Apr 20 17:53:07 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:07.516582     912 event.go:217] Event(api.ObjectReference{Kind:"Deployment", Namespace:"kube-system", Name:"heapster", UID:"193d5ccd-25f2-11e7-afbe-90b8d0f6559c", APIVersion:"extensions", ResourceVersion:"302638", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled down replica set heapster-564189836 to 0
Apr 20 17:53:07 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:07.519887     912 replica_set.go:512] Too many "kube-system"/"heapster-564189836" replicas, need 0, deleting 1
Apr 20 17:53:07 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:07.519972     912 controller_utils.go:523] Controller heapster-564189836 deleting pod kube-system/heapster-564189836-kx8s8
Apr 20 17:53:07 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:07.796523     912 event.go:217] Event(api.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"heapster-564189836", UID:"19441673-25f2-11e7-afbe-90b8d0f6559c", APIVersion:"extensions", ResourceVersion:"302639", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: heapster-564189836-kx8s8
Apr 20 17:53:10 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:10.591805     912 deployment_controller.go:322] Deployment has been deleted kube-system/heapster
Apr 20 17:53:10 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:10.901795     912 event.go:217] Event(api.ObjectReference{Kind:"Deployment", Namespace:"kube-system", Name:"monitoring-influxdb", UID:"198a7c61-25f2-11e7-afbe-90b8d0f6559c", APIVersion:"extensions", ResourceVersion:"302667", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled down replica set monitoring-influxdb-957705310 to 0
Apr 20 17:53:10 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:10.906522     912 replica_set.go:512] Too many "kube-system"/"monitoring-influxdb-957705310" replicas, need 0, deleting 1
Apr 20 17:53:10 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:10.906702     912 controller_utils.go:523] Controller monitoring-influxdb-957705310 deleting pod kube-system/monitoring-influxdb-957705310-v040r
Apr 20 17:53:10 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:10.949805     912 event.go:217] Event(api.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"monitoring-influxdb-957705310", UID:"19908a65-25f2-11e7-afbe-90b8d0f6559c", APIVersion:"extensions", ResourceVersion:"302668", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: monitoring-influxdb-957705310-v040r
Apr 20 17:53:13 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:13.944831     912 deployment_controller.go:322] Deployment has been deleted kube-system/monitoring-influxdb
Apr 20 17:53:17 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:17.936141     912 event.go:217] Event(api.ObjectReference{Kind:"Deployment", Namespace:"kube-system", Name:"monitoring-grafana", UID:"3c0e3cb3-25f2-11e7-afbe-90b8d0f6559c", APIVersion:"extensions", ResourceVersion:"302698", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set monitoring-grafana-3730655072 to 1
Apr 20 17:53:17 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:17.940420     912 replica_set.go:479] Too few "kube-system"/"monitoring-grafana-3730655072" replicas, need 1, creating 1
Apr 20 17:53:18 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:18.017559     912 deployment_controller.go:298] Error syncing deployment kube-system/monitoring-grafana: Operation cannot be fulfilled on deployments.extensions "monitoring-grafana": the object has been modified; please apply your changes to the latest version and try again
Apr 20 17:53:18 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:18.151619     912 event.go:217] Event(api.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"monitoring-grafana-3730655072", UID:"3c148186-25f2-11e7-afbe-90b8d0f6559c", APIVersion:"extensions", ResourceVersion:"302699", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: monitoring-grafana-3730655072-5qk2x
Apr 20 17:53:18 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:18.511829     912 event.go:217] Event(api.ObjectReference{Kind:"Deployment", Namespace:"kube-system", Name:"heapster", UID:"3c5dc053-25f2-11e7-afbe-90b8d0f6559c", APIVersion:"extensions", ResourceVersion:"302712", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set heapster-564189836 to 1
Apr 20 17:53:18 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:18.515876     912 replica_set.go:479] Too few "kube-system"/"heapster-564189836" replicas, need 1, creating 1
Apr 20 17:53:18 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:18.599194     912 event.go:217] Event(api.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"heapster-564189836", UID:"3c6aaefe-25f2-11e7-afbe-90b8d0f6559c", APIVersion:"extensions", ResourceVersion:"302714", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: heapster-564189836-sc7h6
Apr 20 17:53:18 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:18.668673     912 deployment_controller.go:298] Error syncing deployment kube-system/heapster: Operation cannot be fulfilled on deployments.extensions "heapster": the object has been modified; please apply your changes to the latest version and try again
Apr 20 17:53:19 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:19.200328     912 replica_set.go:479] Too few "kube-system"/"monitoring-influxdb-957705310" replicas, need 1, creating 1
Apr 20 17:53:19 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:19.205759     912 event.go:217] Event(api.ObjectReference{Kind:"Deployment", Namespace:"kube-system", Name:"monitoring-influxdb", UID:"3ca9d425-25f2-11e7-afbe-90b8d0f6559c", APIVersion:"extensions", ResourceVersion:"302735", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set monitoring-influxdb-957705310 to 1
Apr 20 17:53:19 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:19.272126     912 event.go:217] Event(api.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"monitoring-influxdb-957705310", UID:"3cb3c12e-25f2-11e7-afbe-90b8d0f6559c", APIVersion:"extensions", ResourceVersion:"302736", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: monitoring-influxdb-957705310-f61jh
Apr 20 17:53:19 acme-lvk8s01 kube-controller-manager[912]: I0420 17:53:19.283908     912 deployment_controller.go:298] Error syncing deployment kube-system/monitoring-influxdb: Operation cannot be fulfilled on deployments.extensions "monitoring-influxdb": the object has been modified; please apply your changes to the latest version and try again
Apr 20 17:58:05 acme-lvk8s01 kube-controller-manager[912]: W0420 17:58:05.353726     912 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [302460/302320]) [303459]

**Comment by spirrello** [comment]
Had to comment out the following line in the deployment file as I'm not using the add on manager.

kubernetes.io/cluster-service: "true"

**Comment by shisy** [comment]
This link may be your problems answer:
https://stackoverflow.com/questions/43527712/kubernetes-1-5-4-kube-dns-getting-deleted/44406604#44406604
