### ISSUE TITLE
Incident response process for critically flawed releases

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubernetes#44739]
**Is this a BUG REPORT or FEATURE REQUEST?**:

PROCESS/DOCUMENTATION REQUEST

**Description**:

At the release of Kubernetes 1.6.0, the `kubeadm` tool had a [showstopping flaw](https://github.com/kubernetes/kubernetes/issues/43815) that caused every user who tried to initialize a cluster to face a hung process. The GitHub issue contained a noisy mixture of duplicate reports of the bug, users suggesting workarounds, some developers tracking the short-term fix efforts, and others discussing the correct long-term fix. It was [criticized](https://github.com/kubernetes/kubernetes/issues/43815#issuecomment-291262557) for having very low signal/noise for any of these audiences and for Kubernetes having no public announcement to the community about the known bug or an estimated fix timeline. Additionally, communication was fractured between [multiple](https://github.com/kubernetes/kubeadm/issues/212) GitHub [issues](https://github.com/kubernetes/kubernetes/issues/43815) and Slack channels, with no indication of the authoritative source for updates.

In the event that this kind of situation occurs again, it would be great if we put some forethought into the correct way to proceed in the face of panic, and have a playbook for managing our communication. These are the kinds of things I would expect such a document to cover:

- What is the criteria for engaging this process (e.g. X% of estimated users impacted)?
- Who should be engaged within the organization?
- Where should a proactive user announcement (if any) be sent to?
- We should always identify the authoritative source for updates on the status of the bug and its fix, and link/close new issues that duplicate it.
  - Should we create different GitHub issues for different target audiences of the same bug (user reports, workarounds, status of official fix...)?
- Incorporate other useful policies like GoLang's [NoMeToo](https://github.com/golang/go/wiki/NoMeToo) to aggressively remove noise.

This is one of the proposed action items from the [kubeadm 1.6.0 postmortem](https://docs.google.com/document/d/1o-wJ39O8eqBxOCHgu0MGmgH4EdojzI3WlrsV3TVwhe0/edit?usp=sharing).

@kubernetes/sig-cluster-lifecycle-feature-requests
@kubernetes/kubernetes-pm

**Comment by dmmcquay** [comment]
I think this is a great idea.

We should add this issue to be discussed during the next SIG-cluster-lifecycle meeting.

**Comment by saad-ali** [comment]
Thanks for the proposal. Can you please open this issue under https://github.com/kubernetes/community/issues instead. kubernetes/kubernetes issues track actual code issues.

**Comment by pipejakob** [comment]
https://github.com/kubernetes/community/issues/564 created.
