### ISSUE TITLE
Federation should use namespace scoped service accounts to talk to underlying clusters

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#44743]
Background: Federation today uses a single identity to send all its requests to a cluster. This requires that single identity to have the authorization to do everything that federation is being used for.
For ex: if 2 teams are using federation to federate resources in 2 namespaces, they need to create a service account for federation that has CRUD access to both namespaces. This single service account becomes more powerful then the service accounts of each teams (which have access to only a single namespace). This is not good.

Solution:
A way to fix this is by updating federation to accept multiple service accounts (one per namespace) instead of only a single one. Federation will then use the corresponding service account while sending requests in that namespace.

Things I need to figure out:
* How will create federated namespace work?
* How to give federation access to service accounts? Pass the token? Does deleting the service account revoke it?
* Are SA's namespaced by default?
* Does editor on namespace include authorization to CRUD SA in that ns?

Filing this early while I figure out the details to get any high level feedback early.

cc @kubernetes/sig-auth-misc @kubernetes/sig-federation-feature-requests @erictune @smarterclayton @liggitt

**Comment by ericchiang** [comment]
I drew up some RBAC roles yesterday in attempt to limit the federated credentials to a couple namespaces: https://gist.github.com/ericchiang/dfdfcf092c4c66ff9215b217e19ed5a7

I don't think it's strictly necessary to support multiple service accounts. You should be able to create one then give it access to the target namespaces.

Maybe that's relevant to this conversation?

**Comment by nikhiljindal** [comment]
Who will create this service account that has access to both the namespaces?
If a team has access to only one namespace, can they create a service account that has access to more than that namespace?

**Comment by liggitt** [comment]
If they have the ability to grant access to a service account at all, they could do so for a single service account across both namespaces.

**Comment by nikhiljindal** [comment]
Yes you are right. I still need to grant access to the service account after creating it. I assumed creating an SA in a namespace gives that SA access to the namespace it is in by default. But as you said thats not true.

**Comment by nikhiljindal** [comment]
@ericchiang Realized that restricting the federation credentials to specific namespaces wont work (controllers assume that they have access to all namespaces). Filed https://github.com/kubernetes/kubernetes/issues/45189 to fix that.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#211.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
