### ISSUE TITLE
Start kubelet with --registrer-with-taints can't set taints for the node

### ISSUE THREAD

**Issue by likunbyl** [kubernetes/kubernetes#44758]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+coreos.0", GitCommit:"9212f77ed8c169a0afa02e58dce87913c6387b3e", GitTreeState:"clean", BuildDate:"2017-04-04T00:32:53Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+coreos.0", GitCommit:"9212f77ed8c169a0afa02e58dce87913c6387b3e", GitTreeState:"clean", BuildDate:"2017-04-04T00:32:53Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Baremental
- **OS** (e.g. from /etc/os-release): coreos 1298.7.0
- **Kernel** (e.g. `uname -a`): 4.9.16-coreos-r1

**What happened**:
start kubelet with --register-with-taints="dedicated=master:NoSchedule", can't see taint be configured.

kubectl describe node
Taints:                 \<none\>

**What you expected to happen**:
Taints should be configured.

**Anything else we need to know**:

After add taint with 'kubectl taint node' command, I can see taints configured:

kubectl describe node 
Taints:                 dedicated=master:NoSchedule

**Comment by ravisantoshgudimetla** [comment]
@likunbyl , we need to set register-node for --register-with-taints option. The **documentation(https://kubernetes.io/docs/admin/kubelet/) ** says following:
--register-with-taints []api.Taint   Register the node with the given list of taints (comma seperated "<key>=<value>:<effect>"). *No-op if register-node is false*. 

Please let us know, if that does not work out.

**Comment by likunbyl** [comment]
Ok, since my node has been registered before, taint can't be registered again. After I deleted this node from cluster, then restarted the node, taint added successfully. thank everyone.
