### ISSUE TITLE
Kubectl should allow `kubectl delete service,rc <name>`

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#4475]
For when you have service / rc / other things with the same name.

**Comment by bgrant0607** [comment]
Encountered this in examples I wrote for the user guide. Would have certainly been useful.

**Comment by timothysc** [comment]
cc @jwforres, @timothysc

**Comment by jwforres** [comment]
@fabianofranz

**Comment by feihujiang** [comment]
@smarterclayton @bgrant0607 Is there anyone to work on this? If not, I'd like to work on this.

**Comment by jwforres** [comment]
Is the plan to delete the ones that it does find and show an error for any that it doesn't?  As opposed to an all or nothing approach.

**Comment by bgrant0607** [comment]
@feihujiang Thanks. Nobody is working on this as far as I know.

@jwforres Yes, that's how kubectl is intended to behave in general
