### ISSUE TITLE
Periodical errors of dockerd and kubelet: "No such container"

### ISSUE THREAD

**Issue by silentred** [kubernetes/kubernetes#44752]
**Kubernetes version** :
```
kubeadm version
kubeadm version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

- **OS** (e.g. from /etc/os-release):

```
cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

- **Kernel** (e.g. `uname -a`):

Linux iZ2ze8ctk2q17u029a8wcoZ 4.4.0-63-generic #84-Ubuntu SMP Wed Feb 1 17:20:32 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**What happened**:
errors keep appending to /var/log/syslog file, such as
```
Apr 21 13:22:11 iZ2ze8ctk2q17u029a8wcoZ dockerd[28877]: time="2017-04-21T13:22:11.648408804+08:00" level=error msg="Handler for GET /v1.24/containers/f2fdf1320870ed5050e232bb70c51a4061c1891af19f6019e1a16952513b9025/json returned error: No such container: f2fdf1320870ed5050e232bb70c51a4061c1891af19f6019e1a16952513b9025"

Apr 21 13:22:11 iZ2ze8ctk2q17u029a8wcoZ kubelet[9278]: E0421 13:22:11.639028    9278 kuberuntime_gc.go:138] Failed to stop sandbox "eb0ad262eae8c35745db431dac0c875c9f490b09edd11d381f0cfab53b533026" before removing: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "kube-apiserver-iz2ze8ctk2q17u029a8wcoz_kube-system" network: CNI failed to retrieve network namespace path: Error: No such container: eb0ad262eae8c35745db431dac0c875c9f490b09edd11d381f0cfab53b533026

Apr 21 13:22:11 iZ2ze8ctk2q17u029a8wcoZ kubelet[9278]: E0421 13:22:11.640389    9278 docker_sandbox.go:205] Failed to stop sandbox "ed4b844966bb727e3de6e89665d7133cc6d30f969a6f5c785572ea275773390f": Error response from daemon: {"message":"No such container: ed4b844966bb727e3de6e89665d7133cc6d30f969a6f5c785572ea275773390f"}

Apr 21 13:22:11 iZ2ze8ctk2q17u029a8wcoZ kubelet[9278]: E0421 13:22:11.640519    9278 remote_runtime.go:109] StopPodSandbox "ed4b844966bb727e3de6e89665d7133cc6d30f969a6f5c785572ea275773390f" from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "calico-node-fw6dq_kube-system" network: CNI failed to retrieve network namespace path: Error: No such container: ed4b844966bb727e3de6e89665d7133cc6d30f969a6f5c785572ea275773390f
```

**How to reproduce it** (as minimally and precisely as possible):

use kubeadm v1.6.1 to setup a cluster with calico network.
I thought it was because of the legacy etcd data. But I see `kubeadm reset` clear the etcd data directory. So I cannot figure out why it is happening.

**Comment by shettyg** [comment]
I see the same error too.

**Comment by supereagle** [comment]
They are not actual errors and can be ignored, [here](https://github.com/kubernetes/kubernetes/issues/38979#issuecomment-268340625) is the detailed explation. You can have a try on the method in the cadvisor [PR 1627](https://github.com/google/cadvisor/pull/1627).

**Comment by silentred** [comment]
Thanks @supereagle , I will close this issue.

**Comment by bboreham** [comment]
The logging in #38979 is totally different to the logging in this issue.  They are unrelated.

Here, kubelet is trying to clean up a dead container, but since it is already dead it gets errors and logs them.  This logging is harmless, but if you get a lot of this you may wish to investigate why those containers/pods are dying.

**Comment by ChipmunkV** [comment]
> The error actually disappeared for me once I installed the latest version of CNI (0.5.2)

@shettyg, is there a deb package with 0.5.2 CNI?

I am getting the same errors, but the networking is actually broken in some places: some services are unreachable and I see that the iptables rules for them are in fact incorrect. (using bridge network plugin)
