### ISSUE TITLE
Filtering resources by structured data (e.g., annotations, fields)

### ISSUE THREAD

**Issue by TomasTomecek** [kubernetes/kubernetes#4476]
As I'm looking at implementation of labels right now, it is just a [plain key-value store](https://github.com/GoogleCloudPlatform/kubernetes/blob/b3b092b41a95994e5f93bca80652567ce63fa41b/pkg/api/meta/meta.go#L276). Would it be possible to extend labels so the values could contain any structured data (slices, maps,...)? This kind of structured data could then be easily queried by some [json query framework](http://stackoverflow.com/questions/777455/is-there-a-query-language-for-json).

The scenario I'm trying to cover is that I would store names and versions of packages I have in pods and then I would do a query: give me all the pods which have package X in version Y (so I can update those).

Does it make sense or is there a better place to store structured data within kubernetes?

**Comment by thockin** [comment]
Label values are not currently validated in any way, though that might
change.  They are not really intended to carry structured data and the
expressions one can perform on labels are intentionally very simple.

You can store arbitrary stuff in the annotations field, but that is not
really queryable by our selector infrastructure (e.g. won't be indexed).

I'm not sure what you mean by package X, version Y - there isn't really a
concept of packages - just containers.

**Comment by smarterclayton** [comment]
Although someone could implement an annotation indexer on the side if necessary.

**Comment by TomasTomecek** [comment]
To generalize the use case: I have a pod which performs some job. Once it's finished, I need to store results (json) somewhere. Therefore my question really is: are kubernetes suitable for storing structured data (which needs to be query-able: e.g. give me all the pods which satisfy condition `label["key"]["key2"]  > 256`) or is this a job for separate service (postgresql/etcd/mongo/...)?

**Comment by thockin** [comment]
You have two different issues here:

On Wed, Feb 18, 2015 at 7:31 AM, Tomas <notifications@github.com> wrote:
>
> To generalize the use case: I have a pod which performs some job. Once it's finished, I need to store results (json) somewhere.

Results are not really appropriate to store in the API object
representing a job.  Results can be unbounded in size, for example.
That said, something like a return code or simple termination message
is probably legitimate.  We have not spent a lot of time on features
around "jobs that complete" yet.  We've mostly focused on perpetual
serving jobs.

> Therefore my question really is: are kubernetes suitable for storing structured data (which needs to be query-able: e.g. give me all the pods which satisfy condition label["key"]["key2"] > 256) or is this a job for separate service (postgresql/etcd/mongo/...)?

Label selectors can/will support very simple expressions -
exactly-equal, not-equal, in-set, not-in-set.  These facilitate fast
indexing and solve the "identifying marks" cases pretty well.  There
are currently no plans for inequalities, sub-key-structure,
substrings, etc.

**Comment by smarterclayton** [comment]
I think the case of storage for data:

1. You can store metadata in annotations.  It should be small
2. Medium to larger sized data (10-100k) could potentially be passed through the API and stored as part of resources that were designed for it (i.e. Secrets)
3. Larger data should be stored in object storage or something that is like object storage (GET / PUT chunks of data).  You could use/abuse etcd for it, but those sorts of data are really intended for something else.

----- Original Message -----
> You have two different issues here:
>

**Comment by bgrant0607** [comment]
#1503 is relevant.

**Comment by TomasTomecek** [comment]
@smarterclayton Not sure what you mean with point 2) where do resources have stored data?

@thockin I agree with your first point (and am a bit sad after reading second point). In my case, the results are in tenths of kilobytes at most.

I guess then my use case doesn't fit into kubernetes philosophy. Now. It would be nice if you could leave this open in case something's gonna change in future.

**Comment by smarterclayton** [comment]
It is not unreasonable that certain types of Kube resources persist medium to large size data for end users.  Secrets are an example of this, as well as potentially a Kube resource that exposes a simple key value passthrough to Etcd for the purpose of storing config or other small reusable bits in a cluster.  However, those are very targeted use cases, and it's up to each resource type to decide whether it's appropriate for it to start large amounts of data.

In the case of things like builds, storing a medium amount of data with the resource as the *result* might be ok, but the more things that builds need to track, the less likely it is that that data should be stored on the resource, as opposed to in an object store and references kept.

**Comment by erictune** [comment]
FWIW, "secrets" was just merged and it could be abused to do this.
We can provide per-namespace quotas on the number and total size of such
objects, and let cluster admins set things how they want.

**Comment by thockin** [comment]
Trying to be more helpful :)

Storing results is really an app problem, better suited to storage than the
core API objects.  That said, we offer something you might find useful:
 termination messages.  Look at this JSON

```
{
        "id": "thockin-term-msg",
        "kind": "Pod",
        "apiVersion": "v1beta1",
        "desiredState": {
                "manifest": {
                        "version": "v1beta1",
                        "id": "thockin-term-msg",
                        "restartPolicy": { "never": {} },
                        "containers": [{
                                "name": "ctr",
                                "image": "busybox",
                                "command": [ "sh", "-c", "echo hi >
/dev/termination-log" ]
                        }]
                }
        }
}
```

When I run that pod it arrives in the "succeeded" status.  Now if I
`kubectl get -o json pod thockin-term-msg` I see:

```
{
    "kind": "Pod",
    "id": "thockin-term-msg",
    "uid": "6d92f22d-b880-11e4-88a7-42010af07484",
    "creationTimestamp": "2015-02-19T21:44:06Z",
    "selfLink": "/api/v1beta1/pods/thockin-term-msg?namespace=default",
    "resourceVersion": 1900,
    "apiVersion": "v1beta1",
    "namespace": "default",
    "desiredState": {
        "manifest": {
            "version": "v1beta2",
            "id": "",
            "volumes": null,
            "containers": [
                {
                    "name": "ctr",
                    "image": "busybox",
                    "command": [
                        "sh",
                        "-c",
                        "echo hi \u003e /dev/termination-log"
                    ],
                    "resources": {},
                    "terminationMessagePath": "/dev/termination-log",
                    "imagePullPolicy": "PullIfNotPresent",
                    "capabilities": {}
                }
            ],
            "restartPolicy": {
                "never": {}
            },
            "dnsPolicy": "ClusterFirst"
        }
    },
    "currentState": {
        "manifest": {
            "version": "",
            "id": "",
            "volumes": null,
            "containers": null,
            "restartPolicy": {}
        },
        "status": "Succeeded",
        "Condition": [
            {
                "kind": "Ready",
                "status": "None"
            }
        ],
        "host": "kubernetes-minion-oboq.c.thockin-dev.internal",
        "hostIP": "146.148.72.105",
        "podIP": "10.244.1.7",
        "info": {
            "POD": {
                "state": {
                    "running": {
                        "startedAt": "2015-02-19T21:44:07Z"
                    }
                },
                "ready": false,
                "restartCount": 0,
                "podIP": "10.244.1.7",
                "image": "kubernetes/pause:latest",
                "imageID":
"docker://6c4579af347b649857e915521132f15a06186d73faa62145e3eeeb6be0e97c27",
                "containerID":
"docker://b2d5699ccba1e6e3068042e3ff6c047f1fff90b7df370b34c940fa5b112c4a95"
            },
            "ctr": {
                "state": {
                    "termination": {
                        "exitCode": 0,
                        "message": "hi\n",
                        "startedAt": "2015-02-19T21:44:08Z",
                        "finishedAt": "2015-02-19T21:44:08Z"
                    }
                },
                "ready": false,
                "restartCount": 0,
                "image": "busybox",
                "imageID":
"docker://4986bf8c15363d1c5d15512d5266f8777bfba4974ac56e3270e7760f6f0a8125",
                "containerID":
"docker://881c9bfbfe18d5bced2f61888642aba08da2e56e8a53b506a3e8480a2792f334"
            }
        }
    }
}
```

more precisely:

```
{
    "kind": "Pod",
    "id": "thockin-term-msg",
    // ... stuff ...
    "currentState": {
        // ... stuff ...
        "status": "Succeeded",
        // ... stuff ...
        "info": {
            // ... stuff ...
            "ctr": {
                "state": {
                    "termination": {
                        "exitCode": 0,
                        "message": "hi\n",
                        // ... stuff ...
                    }
                },
                // ... stuff ...
            }
        }
    }
}
```

Now you can run your own query for all pods, filter as you want, and look
at the termination.message

Is that useful?

**Comment by smarterclayton** [comment]
We improved termination messages a bit, and in general have no plans to implement this directly in the near term.

**Comment by shivasuri** [comment]
Hi, I am trying to get the default storage class programatically. I see here that I can't index by the `storageclass.kubernetes.io/is-default-class` annotation; is there some other way to get the default one?
