### ISSUE TITLE
Cannot attach gdbserver to process through kubectl

### ISSUE THREAD

**Issue by vglazkov** [kubernetes/kubernetes#44765]
Hello,

I have an issue with attaching gdbserver to process inside the pod. I'm able to successfully attach gdbserver to process on my local machine, but the same operation fails when I'm trying to do that through kubectl with pod, running inside my cluster. On my local machine I have the following workflow:

- run gdb

- `target remote | docker exec -i CONTAINER gdbserver - --attach PID`

- `set sysroot /path/to/local/binary`

- Ready to debug

When I'm trying to do the same operation in the cluster I replace my step two with the following command:
`target remote | kubectl exec -i POD -- gdbserver - --attach PID` and this returns me :

> Cannot attach to lwp 7: Operation not permitted (1) Exiting Remote connection closed

I believe this problem is related to some sort of permissions problem, because as I mentioned this workflow works perfectly fine with pure Docker. 

Kubernetes version:

> version:Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"clean", BuildDate:"2017-03-28T13:36:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

Cloud provider: Google, GKE
OS: Debian GNU/Linux VERSION="8 (jessie)"
Kernel: Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
Install tools: Google Cloud SDK 152.0.0
Others: GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1

What happened: cannot attach gdbserver to process 
What you expected to happen: be able to successfully attach gdbserver to process
How to reproduce it: create simple image based debian 8 jessie, install inside it gdbserver, run some process, and then try the following command:` kubectl exec -i POD -- gdbserver - --attach PID`

**Comment by suyogbarve** [comment]
@vglazkov I have verified that this is working perfectly fine with 

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

Can you please try to upgrade your GKE env to 1.6.2 and recheck?

**Comment by suyogbarve** [comment]
@saad-ali assign this to me

**Comment by xiangpengzhao** [comment]
/assign @suyogbarve 

If bot doesn't allow me to assign, @thockin assigns please :)

**Comment by thockin** [comment]
@suyogbarve I can't assign it to you since you're not in the org.  Don't let that stop you though!

**Comment by suyogbarve** [comment]
@vglazkov I have verified that this is working perfectly fine with

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

Can you please try to upgrade your GKE env to 1.6.2 and recheck?

**Comment by thockin** [comment]
preemptive close - please reopen if still exists
