### ISSUE TITLE
fieldRef docs wrongfully claim to support metadata.labels and metadata.annotations

### ISSUE THREAD

**Issue by rfalke** [kubernetes/kubernetes#44762]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

fieldref

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0+776c994", GitCommit:"a9e9cf3", GitTreeState:"clean", BuildDate:"2017-01-24T15:12:46Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2+43a9be4", GitCommit:"43a9be4", GitTreeState:"clean", BuildDate:"2017-04-13T11:14:20Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:

EC2 instance

- **OS** (e.g. from /etc/os-release):

Red Hat Enterprise Linux Server 7.3 (Maipo)

- **Kernel** (e.g. `uname -a`):

Linux 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**:
- **Others**:

**What happened**:

```
$ cat test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: env-not-usable
  labels:
    mykey: myvalue
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SOME_LABEL
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels
  restartPolicy: Never
$ kubectl create -f test.yaml
The Pod "env-not-usable" is invalid: spec.containers[0].env[0].valueFrom.fieldRef.fieldPath: Unsupported value: "metadata.labels": supported values: metadata.name, metadata.namespace, spec.nodeName, spec.serviceAccountName, status.podIP
$
```

**What you expected to happen**:

I expect the above to work since the API docu claims this is supported.

```
curl -k https://localhost:8443/swaggerapi/api/v1
....
   "v1.EnvVarSource": {
    "id": "v1.EnvVarSource",
    "description": "EnvVarSource represents a source for the value of an EnvVar.",
    "properties": {
     "fieldRef": {
      "$ref": "v1.ObjectFieldSelector",
      "description": "Selects a field of the pod: supports metadata.name, metadata.namespace, metadata.labels, metadata.annotations, spec.nodeName, spec.serviceAccountName, status.podIP."
     },
...
```

It mentions metadata.labels and metadata.annotations as supported.

**How to reproduce it** (as minimally and precisely as possible):

See above

**Anything else we need to know**:

I know that this feature is not supported. See https://github.com/kubernetes/kubernetes/issues/19367

The is more a bug report about the docu which claims falsely that the feature is supported.

**Comment by xiangpengzhao** [comment]
See also #43222
