### ISSUE TITLE
[Azure] Support setting the DNS name label for public IPs created by ingress controllers 

### ISSUE THREAD

**Issue by rocketraman** [kubernetes/kubernetes#44775]
**What keywords did you search in Kubernetes issues before filing this one?** ingress controller dns name

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

When deploying an ingress controller on Azure, Kubernetes helpfully creates a public IP address.

It would be useful to set the "DNS name label" of the created IP address based on an annotation in the Deployment. CNAMEs can then be used to point to this Azure DNS name, resulting in a (more) stable DNS configuration if the ingress controller is deleted and recreated.

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.2
- **Kernel** (e.g. `uname -a`): Linux k8s-master-30143214-0 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: -
- **Others**: -

Downstream issue https://github.com/Azure/acs-engine/issues/517

**Comment by cmluciano** [comment]
@kubernetes/sig-azure-misc
