### ISSUE TITLE
The unit test TestRunInitMasterChecks in cmd/kubeadm/app/preflight fails 

### ISSUE THREAD

**Issue by rpothier** [kubernetes/kubernetes#44783]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT 

**Kubernetes version** (use `kubectl version`):
latest master 

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
CentOS Linux release 7.3.1611 (Core)

- **Kernel** (e.g. `uname -a`):
Linux oscorehost64 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
On a fresh install of CentOS, loaded kubernetes and ran Unit Tests.
TestRunInitMasterChecks in cmd/kubeadm/app/preflight fails consistently

[preflight] WARNING: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
[preflight] WARNING: ebtables not found in system path
[preflight] WARNING: socat not found in system path
--- FAIL: TestRunInitMasterChecks (0.41s)
        checks_test.go:196: failed RunInitMasterChecks:
                        expected: false
                          actual: false
[preflight] WARNING: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
[preflight] WARNING: ebtables not found in system path
[preflight] WARNING: socat not found in system path
--- FAIL: TestRunJoinNodeChecks (0.38s)
        checks_test.go:219: failed RunJoinNodeChecks:
                        expected: false
                          actual: false
FAIL
FAIL    k8s.io/kubernetes/cmd/kubeadm/app/preflight     1.868s

it seems this test is looking for files in /var/lib/kubelet, if no files exist, the test fails.
As a workaround, any file can be added in this directory

Also, note it shows
                       expected: false
                          actual: false
This is not a clear error message, as it seems the actual matched the expected.

**What you expected to happen**:
Unit Tests should pass.
Unit tests should not be dependent on the file system or what may have been
run in the past.

**How to reproduce it** (as minimally and precisely as possible):

Run Unit Tests on on a new system, following the procedure in
https://github.com/kubernetes/community/blob/master/contributors/devel/development.md

**Anything else we need to know**:

**Comment by luxas** [comment]
This unit test is working now at least...
