### ISSUE TITLE
Definition of v1beta1 HTTPIngressPath.path is unclear

### ISSUE THREAD

**Issue by unixwitch** [kubernetes/kubernetes#44799]
**Is this a request for help?**: No
**What keywords did you search in Kubernetes issues before filing this one?**: "Ingress", "Ingress path".

---

**Is this a BUG REPORT or FEATURE REQUEST?**: Neither.
**Kubernetes version** (use `kubectl version`): N/A (any)
**Environment**:
- **Cloud provider or hardware configuration**: N/A (any)
- **OS** (e.g. from /etc/os-release): N/A (any)
- **Kernel** (e.g. `uname -a`): N/A (any)
- **Install tools**: N/A (any)
- **Others**: N/A (any)

**What happened**:
While implementing an Ingress controller, I read the API documentation for v1beta1.HTTPIngressPath.  I found the definition for the "path" element to be insufficiently well specified to allow implementation of an Ingress controller.

Problem 1: the specification says "Paths must begin with a /".  Does this imply the regular expression should be anchored at the start of the request URL?  For example, say the request path is `/foo/bar` and the ingress path is `/bar`.  Normally the regular expression `/bar` should match `/foo/bar`, but the implication here is that `/bar` should be treated as `^/bar`, and therefore not match.  If this is the intention, it should be stated explicitly.  If not, there seems to be no reason to require the path to begin with a `/` (for example, `\.jpg$` could be a valid path).

Problem 2: the specification does not say whether overlapping paths are allowed, and if they are, how they should be handled.  For example, if two paths are defined, one for `^/foo` and one for `^/foo/bar`, where should the request URL `/foo/bar/baz` be routed?  Is it valid to have two ingresses, one for `^/` and one for `^/foo`, or should the default ingress always be specified without a path?

**What you expected to happen**:
I expected the definition of "name" to be better specified than it actually was.

**How to reproduce it** (as minimally and precisely as possible):
Read the documentation for v1beta1.HTTPIngressPath, at https://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/#_v1beta1_httpingresspath.

**Anything else we need to know**:

**Comment by kargakis** [comment]
@kubernetes/sig-network-misc

**Comment by nicksardo** [comment]
Dupe of https://github.com/kubernetes/ingress/issues/555 and originally https://github.com/kubernetes/contrib/issues/885

/close
