### ISSUE TITLE
Flakes: deleting the Namespace of a PVC and Pod causes the successful detach of Persistent Disk

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#44790]
/assign @saad-ali @childsb 

The `[k8s.io] PersistentVolumes:GCEPD [Volume] should test that deleting the Namespace of a PVC and Pod causes the successful detach of Persistent Disk` test flakes presubmit testing in PRs six times per week

The https://go.k8s.io/triage site can focus on just this test: [link](https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=should%20test%20that%20deleting%20the%20Namespace%20of%20a%20PVC%20and%20Pod%20causes%20the%20successful%20detach%20of%20Persistent%20Disk)

Which shows that 83 out of 85 errors match this pattern:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-gce.go:163
Expected error:
    <*errors.errorString | 0xc42043c110>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-gce.go:159
```

**Comment by fejta** [comment]
Previous attempt to address this flake: https://github.com/kubernetes/kubernetes/pull/43336

**Comment by saad-ali** [comment]
CC @kubernetes/sig-storage-bugs

**Comment by saad-ali** [comment]
Took a quick look at a failed test:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-multizone/7562#undefined

The [log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-multizone/7562/build-log.txt) indicates:
```
I0417 16:55:59.711] Apr 17 16:55:28.552: INFO: At 2017-04-17 16:50:29 -0700 PDT - event for pvc-tester-4n05g: {attachdetach } FailedMount: Failed to attach volume "gce-sp27h" on node "gke-bootstrap-e2e-default-pool-529696d1-xkck" with: GCE persistent disk not found: diskName="bootstrap-e2e-9e6db111-23c8-11e7-80b8-0242ac110004" zone="us-central1-b"
I0417 16:55:59.711] Apr 17 16:55:28.552: INFO: At 2017-04-17 16:52:28 -0700 PDT - event for pvc-tester-4n05g: {kubelet gke-bootstrap-e2e-default-pool-529696d1-xkck} FailedMount: Unable to mount volumes for pod "pvc-tester-4n05g_e2e-tests-pv-gbggn(a273c7c1-23c8-11e7-b241-42010af00017)": timeout expired waiting for volumes to attach/mount for pod "e2e-tests-pv-gbggn"/"pvc-tester-4n05g". list of unattached/unmounted volumes=[volume1]
```

`GCE persistent disk not found`. @jingxu97 or @msau42 and @jeffvance can you help investigate.

**Comment by saad-ali** [comment]
CC @copejon

**Comment by msau42** [comment]
The failure in the GKE multizone test suite is probably due to the GKE issue I fixed last week.

**Comment by copejon** [comment]
@saad-ali Will dig into this.

**Comment by fejta** [comment]
Expectations:
* This work should interrupt and take priority over other activity while it is assigned to you.
* Expectation for sig leads is to identify someone to fix the issue, `/assign` them and `/unassign` yourself.
* Expectation for assignees are to investigate the issue and either a) resolve it or b) `/assign` it to a more appropriate person and b) `/unassign` yourself.

**Comment by msau42** [comment]
I repeatedly ran this test on my e2e cluster since 7pm last night, and it has not failed yet.  Seems like it fails more frequently in the PR env instead of the CI env, so may need to look into differences between the two. 

The test is failing during the deletion of the namespace.  It seems like there are still some resources not getting deleted.  I'm trying to dig deeper in the logs to see if I can find what resources are not getting cleaned up.

**Comment by msau42** [comment]
Here's one failed [test](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/44868/pull-kubernetes-e2e-gce-etcd3/27655/):
From the API server [logs](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/44868/pull-kubernetes-e2e-gce-etcd3/27655/artifacts/e2e-gce-agent-pr-99-0-master/kube-apiserver.log)

1. The initial namespace deletion request from the e2e test:
I0427 23:23:29.005646       5 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-pv-cx3bh: (4.744775ms) 200 [[e2e.test/v1.7.0 (linux/amd64) kubernetes/477f2a2] 104.197.101.155:49513]  

2. Namespace controller triggers deletion on all the objects in the namespace:
I0427 23:24:37.008075       5 wrap.go:42] DELETE /apis/apps/v1beta1/namespaces/e2e-tests-pv-cx3bh/statefulsets: (91.176059ms) 200 [[kube-controller-manager/v1.7.0 (linux/amd64) kubernetes/477f2a2/system:serviceaccount:kube-system:namespace-controller] [::1]:58426]
I0427 23:24:37.087455       5 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-pv-cx3bh/resourcequotas: (7.608267ms) 200 [[kube-controller-manager/v1.7.0 (linux/amd64) kubernetes/477f2a2/system:serviceaccount:kube-system:namespace-controller] [::1]:58426]

etc ... 

3. Object gets finally deleted by controller
I0427 23:26:30.539057       5 wrap.go:42] DELETE /apis/apps/v1beta1/namespaces/e2e-tests-pv-cx3bh/statefulsets: (87.184389ms) 200 [[kube-controller-manager/v1.7.0 (linux/amd64) kubernetes/477f2a2/system:serv    iceaccount:kube-system:namespace-controller] [::1]:58426]
I0427 23:26:30.983825       5 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-pv-cx3bh/resourcequotas: (21.517822ms) 200 [[kube-controller-manager/v1.7.0 (linux/amd64) kubernetes/477f2a2/system:serviceaccoun    t:kube-system:namespace-controller] [::1]:58426]

etc ...

4. Namespace deletion finished
I0427 23:26:31.533518       5 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-pv-cx3bh: (16.58598ms) 200 [[kube-controller-manager/v1.7.0 (linux/amd64) kubernetes/477f2a2/system:serviceaccount:kube-system:namespace-controller] [::1]:58426]  

5. E2E test cleanup tries to delete it again:
I0427 23:26:31.972576       5 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-pv-cx3bh: (9.104808ms) 404 [[e2e.test/v1.7.0 (linux/amd64) kubernetes/477f2a2] 104.197.101.155:49513]  <= This is the e2e test failure cleanup

Total time to delete > 3 mins


Here's a successful [run](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/44868/pull-kubernetes-e2e-gce-etcd3/27667/):
[Logs](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/44868/pull-kubernetes-e2e-gce-etcd3/27667/artifacts/e2e-gce-agent-pr-94-0-master/kube-apiserver.log):
1. Initial deletion request
I0428 00:45:14.642312       5 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-pv-c4t8j: (11.208829ms) 200 [[e2e.test/v1.7.0 (linux/amd64) kubernetes/6907fb6] 104.197.153.246:46020]
2. Controller starts object deletions
I0428 00:45:46.292211       5 wrap.go:42] DELETE /apis/apps/v1beta1/namespaces/e2e-tests-pv-c4t8j/deployments: (33.104152ms) 200 [[kube-controller-manager/v1.7.0 (linux/amd64) kubernetes/6907fb6/system:servi    ceaccount:kube-system:namespace-controller] [::1]:55942]
I0428 00:45:46.420195       5 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-pv-c4t8j/podtemplates: (3.447937ms) 200 [[kube-controller-manager/v1.7.0 (linux/amd64) kubernetes/6907fb6/system:serviceaccount:k    ube-system:namespace-controller] [::1]:55942]

etc ...

3. Object gets finally deleted by controller
I0428 00:46:17.295433       5 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-pv-c4t8j/podtemplates: (10.679029ms) 200 [[kube-controller-manager/v1.7.0 (linux/amd64) kubernetes/6907fb6/system:serviceaccount:    kube-system:namespace-controller] [::1]:55942]
I0428 00:46:20.309259       5 wrap.go:42] DELETE /apis/extensions/v1beta1/namespaces/e2e-tests-pv-c4t8j/deployments: (6.130617ms) 200 [[kube-controller-manager/v1.7.0 (linux/amd64) kubernetes/6907fb6/system:    serviceaccount:kube-system:namespace-controller] [::1]:55942]

etc ...

4. Namespace deletion is finished
I0428 00:46:21.753061       5 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-pv-c4t8j: (21.10359ms) 200 [[kube-controller-manager/v1.7.0 (linux/amd64) kubernetes/6907fb6/system:serviceaccount:kube-system:na    mespace-controller] [::1]:55942]
5. E2E test cleanup
I0428 00:46:32.992219       5 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-pv-c4t8j: (1.436939ms) 404 [[e2e.test/v1.7.0 (linux/amd64) kubernetes/6907fb6] 104.197.153.246:46020]

Total time to delete ~1 minute

Comparing the bad and good runs, these were some supicious areas:
1. In the bad run, the period between 1) and 2) was > 1 minute, whereas in the good run it was 30 seconds
2. In the bad run, the period between 2) and 3) was ~2 minutes, whereas in the good run it was ~20 seconds.

The slowness in the bad run seems systematic, I did not find any one object that was taking a particularly long time to delete, all of them seemed to be taking longer compared to the good run. 

I'm not sure where to dig down further to find the cause of the general slowness.  I don't know if this is expected, and we should just increase the timeout?  The test framework seems to have a default timeout of 5 minutes, whereas this volume test timeout is only 3 minutes.

**Comment by jeffvance** [comment]
@msau42 Great analysis! Since no singular event stands out as taking too much time how about, in the name of expediency, just changing the timeout to 5m?

**Comment by jingxu97** [comment]
The delay of ns deleteion might related to this PR #29051 and #29262.
#29262 is still open.

**Comment by msau42** [comment]
Those two issues do not seem to impact the deletion of the namespace itself, so I don't think fixing those will solve this issue.

**Comment by jingxu97** [comment]
But I think delaying the deletion of a pod will affect the time to delete the namespace.
