### ISSUE TITLE
Deprecate NodeLegacyHostIP in 1.7

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#44807]
Finish the remaining work of https://github.com/kubernetes/kubernetes/pull/36095.

#36095 made sure all cloudproviders set at least one of NodeInternalIP or NodeExternalIP, so none of them rely on NodeLegacyHostIP. Because we only support version skew less than 2 minor between master and node, we can remove the NodeLegacyHostIP field now.

@NickrenREN is interested to work on this.

cc @liggitt who reviewed #36095

**Comment by NickrenREN** [comment]
Thanks @caesarxuchao , i will send a pr to do it

**Comment by kargakis** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/44830
