### ISSUE TITLE
kubectl scale has no --all flag, yet it suggests it to me

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#44800]
```
$ kc scale rs --replicas=1
error: resource(s) were provided, but no name, label selector, or --all flag specified
$ kc scale rs --all --replicas=1
Error: unknown flag: --all
```
@kubernetes/sig-cli-bugs

**Comment by shiywang** [comment]
For `allowEmptySelector == true` like  `get` `describe` it will never goes that `resource(s) were provided, but... ` prompt.
For `allowEmptySeclector == o.all` or `allowEmptySeclector == flase` or similair, we add a new builder function to check if this command support `--all` flag, then add a bool var `selectAllFlagEnable` 
@kargakis @kubernetes/sig-cli-feature-requests wdyt ?

**Comment by kargakis** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/51021 - thanks @zjj2wry!

**Comment by zjj2wry** [comment]
@kargakis 😊
