### ISSUE TITLE
firewalld.service is dead, but the iptables rules work，that's why?

### ISSUE THREAD

**Issue by fanhaozzu** [kubernetes/kubernetes#44816]
os:  centos7

systemctl status firewalld：
 ●firewalld.service - firewalld - dynamic firewall daemon
Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
Active: inactive (dead)
systemctl status iptables:
 ●iptables.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

But I find the iptables rules works, That's why? who can explain this

**Comment by remonlam** [comment]
Because iptables can run without firewalld.
`systemctl status iptables`

**Comment by fanhaozzu** [comment]
systemctl status iptables:

 iptables.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
@remonlam

**Comment by remonlam** [comment]
Just run "iptables -L" to display the iptables rules.

**Comment by fanhaozzu** [comment]
iptables -L:

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
felix-INPUT  all  --  anywhere             anywhere            
KUBE-FIREWALL  all  --  anywhere             anywhere            

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
felix-FORWARD  all  --  anywhere             anywhere            
DOCKER-ISOLATION  all  --  anywhere             anywhere            
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
felix-OUTPUT  all  --  anywhere             anywhere            
KUBE-FIREWALL  all  --  anywhere             anywhere            
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */

Chain DOCKER (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:dynamid
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:etlservicemgr
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:cslistener
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:8090

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain KUBE-FIREWALL (2 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere             /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000

Chain KUBE-SERVICES (1 references)
target     prot opt source               destination         
REJECT     tcp  --  anywhere             10.11.142.63         /* aaaa2/testpower:testpower-1 has no endpoints */ tcp dpt:webcache reject-with icmp-port-unreachable
REJECT     tcp  --  anywhere             10.1.226.159         /* aaaa2/waaa:waaa-1 has no endpoints */ tcp dpt:http reject-with icmp-port-unreachable
REJECT     tcp  --  anywhere             10.10.79.86          /* admin/sonar:sonar-1 has no endpoints */ tcp dpt:webcache reject-with icmp-port-unreachable
REJECT     tcp  --  anywhere             10.15.219.44         /* admin/tomcat:tomcat-1 has no endpoints */ tcp dpt:webcache reject-with icmp-port-unreachable

**Comment by fanhaozzu** [comment]
it confused me that the rules can work when iptables.service is dead and firewalld.service is dead.

**Comment by fanhaozzu** [comment]
@remonlam

**Comment by fanhaozzu** [comment]
@danwinship 
@thockin 
@nebril

**Comment by thockin** [comment]
I don't understand - is something not working?

**Comment by xiangpengzhao** [comment]
@fanhaozzu Did you mean that the iptables rules still take effect even when both iptables.service and firewalld.service are dead? I wonder how you confirmed that the iptables rules still work in this case. But anyway, this is not a bug of K8S. Asking this question on StackOverflow might be a better way.

**Comment by danwinship** [comment]
iptables is built into the kernel. firewalld is a daemon for managing iptables rules, and iptables.service is a set of shell script for storing iptables rules in a fixed location on disk and reloading them as needed. Neither service is actually necessary to the functioning of iptables, they're just higher-level abstractions on top of it.

**Comment by fanhaozzu** [comment]
@danwinship
thank you

**Comment by chesire0myles** [comment]
@danwinship Seriously, thank you ;)
