### ISSUE TITLE
Print pod name in kubectl logs when using label selector

### ISSUE THREAD

**Issue by nvartolomei** [kubernetes/kubernetes#44812]
Add `kubectl logs` flag to include pod name on each line in log output. Similar to `docker-compose logs`. Ideally behind a flag.

<img width="1130" src="https://cloud.githubusercontent.com/assets/543193/25313290/5dc6c3e6-2834-11e7-880e-3e0bf902a533.png">

**Comment by kargakis** [comment]
@kubernetes/sig-cli-feature-requests @kubernetes/sig-api-machinery-misc

**Comment by smarterclayton** [comment]
Is there a capsule design for label selected pods for logs?

**Comment by adohe** [comment]
imho, no such capsule design, should we add one for this? @smarterclayton

**Comment by nvartolomei** [comment]
What does "capsule design" mean?

**Comment by timothysc** [comment]
Just wondering why we couldn't do something very general like pass a formatting modifier string as a flag to other CLI commands too similar to server side queries but more general.  

xref: http://research.cs.wisc.edu/htcondor/manual/current/condor_status.html see -format

**Comment by mbohlool** [comment]
This does seem like a feature request for kubectl. If it needs a feature from server, please file a separate issue.

**Comment by smarterclayton** [comment]
The API server would potentially need to support multiple streams of logs coming back from a pod, depending on the implementation.

**Comment by Nowaker** [comment]
This would be really helpful. A flag like `--pod-names` would play well with existing option `--timestamps`. CC @kubernetes/sig-cli-feature-requests

**Comment by Nowaker** [comment]
Could someone from @kubernetes/sig-cli-feature-requests take a look at this and comment, please? Thanks!

**Comment by captain-kark** [comment]
Hopefully this helps someone, I've only tested it very briefly on darwin/BSD.

```bash
function kublogs {
  __label_args=${@:1:2}
  __logs_args=${@:3}
  kubectl get po $__label_args -o name | cut -d / -f 2 | xargs -I{} bash -c 'sed -E "s/([0-9]{5})([0-9]+)?Z/\1Z $1/" <(kubectl logs $1 --timestamps ${@:2})' echo {} $__logs_args
}
```

```bash
kublogs -l app=my-deployment --since 1h -c some-container
```

It will print the timestamp first, but will be run against each pod individually. Pipe through `sort` to merge all pod logs together in the order they happened in the cluster.

**Comment by Nowaker** [comment]
Can't live without https://github.com/johanhaleby/kubetail. Simple syntax, colored output (different color per pod).

**Comment by muvster** [comment]
Now available in the form of `--prefix`: https://github.com/kubernetes/kubernetes/pull/76471
