### ISSUE TITLE
kernel panic when building etcd docker image.

### ISSUE THREAD

**Issue by mohamed-eldafrawi** [kubernetes/kubernetes#44811]
**BUG REPORT**

**Kubernetes version**:

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**: Linux
- **Cloud provider or hardware configuration**: libvirt VM
- **OS** : Ubuntu 16.04.2 LTS
- **Kernel**: 4.4.0-72-generic
- **Docker Version**:
  Client:
    Version:      17.03.1-ce
    API version:  1.27
    Go version:   go1.7.5
    Git commit:   c6d412e
    Built:        Mon Mar 27 17:14:09 2017
    OS/Arch:      linux/amd64

  Server:
    Version:      17.03.1-ce
    API version:  1.27 (minimum version 1.12)
    Go version:   go1.7.5
    Git commit:   c6d412e
    Built:        Mon Mar 27 17:14:09 2017
    OS/Arch:      linux/amd64
    Experimental: false

**What happened**:
Error in building etcd docker image.

**What you expected to happen**:
build etcd docker image.

**How to reproduce it**

cd kubernetes/cluster/images/etcd; make

**Anything else we need to know**:

**Error trace:**
\# Copy the content in this dir to the temp dir,
\# without copying the subdirectories.
find ./ -maxdepth 1 -type f | xargs cp -t /tmp/tmp.smibMJfU3u
\# Compile attachlease
docker run -it -v /usr/local/src/kubernetes/cluster/images/etcd/../../../:/go/src/k8s.io/kubernetes -v /tmp/tmp.smibMJfU3u:/build -e GOARCH=amd64 golang:1.7.5 \
	/bin/bash -c "CGO_ENABLED=0 go build -o /build/attachlease k8s.io/kubernetes/cluster/images/etcd/attachlease"
src/k8s.io/kubernetes/cluster/images/etcd/attachlease/attachlease.go:24:2: cannot find package "github.com/coreos/etcd/clientv3" in any of:
	/usr/local/go/src/github.com/coreos/etcd/clientv3 (from $GOROOT)
	/go/src/github.com/coreos/etcd/clientv3 (from $GOPATH)
src/k8s.io/kubernetes/cluster/images/etcd/attachlease/attachlease.go:25:2: cannot find package "github.com/golang/glog" in any of:
	/usr/local/go/src/github.com/golang/glog (from $GOROOT)
	/go/src/github.com/golang/glog (from $GOPATH)
src/k8s.io/kubernetes/cluster/images/etcd/attachlease/attachlease.go:26:2: cannot find package "golang.org/x/net/context" in any of:
	/usr/local/go/src/golang.org/x/net/context (from $GOROOT)
	/go/src/golang.org/x/net/context (from $GOPATH)
Makefile:57: recipe for target 'build' failed
make: *** [build] Error 1

**syslog error trace:**
kernel: [ 3546.325359] aufs au_opts_verify:1597:dockerd[1078]: dirperm1 breaks the protection by the permission bits on the lower branch
kernel: [ 3546.455895] aufs au_opts_verify:1597:dockerd[1078]: dirperm1 breaks the protection by the permission bits on the lower branch
 systemd-udevd[6844]: Could not generate persistent MAC address for vethddbfb97: No such file or directory
systemd-udevd[6846]: Could not generate persistent MAC address for veth30bc249: No such file or directory
kernel: [ 3546.572826] aufs au_opts_verify:1597:dockerd[1078]: dirperm1 breaks the protection by the permission bits on the lower branch
kernel: [ 3546.574085] device veth30bc249 entered promiscuous mode
kernel: [ 3546.574129] IPv6: ADDRCONF(NETDEV_UP): veth30bc249: link is not ready
kernel: [ 3546.892049] eth0: renamed from vethddbfb97
kernel: [ 3546.903898] IPv6: ADDRCONF(NETDEV_CHANGE): veth30bc249: link becomes ready
kernel: [ 3546.903937] docker0: port 1(veth30bc249) entered forwarding state
kernel: [ 3546.903942] docker0: port 1(veth30bc249) entered forwarding state
kernel: [ 3547.137766] vethddbfb97: renamed from eth0
kernel: [ 3547.180415] docker0: port 1(veth30bc249) entered disabled state
kernel: [ 3547.234698] docker0: port 1(veth30bc249) entered disabled state
kernel: [ 3547.235147] device veth30bc249 left promiscuous mode
kernel: [ 3547.235149] docker0: port 1(veth30bc249) entered disabled state

**Comment by kargakis** [comment]
@kubernetes/sig-release-misc

**Comment by cleanerx** [comment]
I have the same problem:
I found the docker image run did not forward the http/https proxy variables potentially set so got cannot download things. Adding
` -e https_proxy=$(HTTPS_PROXY) -e http_proxy=$(HTTP_PROXY)`
to the docker run commands helped getting out.
Unfortunately the docker run command does not seem to get the dependency

Manually fetching the dependency within the docker container 
go get github.com/coreos/etcd/clientv3
`github.com/coreos/etcd/clientv3/client.go:344: cannot use c.tokenCred (type *authTokenCredential) as type credentials.PerRPCCredentials in argument to grpc.WithPerRPCCredentials:
        *authTokenCredential does not implement credentials.PerRPCCredentials (wrong type for GetRequestMetadata method)
`
This error is listed in https://github.com/coreos/etcd/issues/8530
So it seems I should be pulling a tag here but I don't know which one.
It seems the the attachlease and rollback are always compiled and only the etcd image may be used as binary if amd64 is being used.
