### ISSUE TITLE
x.509 Issues with kube-apiserver with saltbase installation on v1.6.2

### ISSUE THREAD

**Issue by benjigoldberg** [kubernetes/kubernetes#44822]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
v1.6.2

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel** (e.g. `uname -a`):
```
Linux ip-10-20-102-89 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
- **Install tools**:
Terraform and Saltbase. Saltbase is taken from this repo.
- **Others**:

**What happened**:
I’m trying to setup k8s on aws for the first time. I’m use the saltbase installation method. Everything is going pretty smoothly with the exception of getting the kube-apiserver started. The kubelet starts on the master and starts the kube-apiserver but it repetitively fails to start with the following:
```
I0423 21:29:42.268353       5 aws.go:762] Building AWS cloudprovider
I0423 21:29:42.268393       5 aws.go:725] Zone not specified in configuration file; querying AWS metadata service
error setting the external host value: "aws" cloud provider could not be initialized: could not init cloud provider "aws": error finding instance i-00a8c3f8a58272ee8: error listing AWS instances: RequestError: send request failed
caused by: Post https://ec2.us-west-2.amazonaws.com/: x509: failed to load system roots and no roots provided

```
Its failing with the aws go library trying to describe instances. The machine this is running on has the correct IAMs permissions and is able to use the aws cli to `DescribeInstances` just fine.

This machine also has OpenSSL, curl, and ca-certificates installed. From what I can tell from the generated kube-apiserver manifest, just about _any_ location that could contain a ca is mounted into this container. I've been stumped on this one for a few days. I certainly wouldn't rule out user error, but I'm out of ideas with regards to what I should try next.

**What you expected to happen**:
kube-apiserver would start up and be able to describe instances

**How to reproduce it** (as minimally and precisely as possible):
Stand up a virgin centos7 machine in AWS, install salt on the machine, and then run `salt '*' state.apply`

**Anything else we need to know**:
Can't think of anything!

**Comment by benjigoldberg** [comment]
Ok, I did more digging on this issue and I think I've found the problem. The salt definition for kube-apiserver.manifest mounts a number of cert directories from the host into the container, but does not mount `/etc/pki/ca-trust/extracted/pem/` which is where the ca certs are stored on CentOS 7. [Golang defines the directories in which it looks for certificates in the linked file](https://golang.org/src/crypto/x509/root_linux.go). While CentOS does present certs in other directories (such as `/etc/ssl/certs/`, `/etc/pki/tls`, etc the certs in those directories are symlinked back to `/etc/pki/ca-trust/extracted/pem/`. I'm not entirely sure why, but go refuses to use those symlinked files within the container (it could also be related to the way docker mounts the files?). To fix the issue, I mounted `/etc/pki/ca-trust/extracted/pem/` directly into the container and the apiserver was able to boot successfully.

I would be happy to update the [saltbase definition of kube-apiserver.manifest](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-apiserver/kube-apiserver.manifest#L254) to include the mount for CentOS 7 certs. As per the contribution guidelines, I will wait to submit a patch until this issue has been accepted.

**Comment by benjigoldberg** [comment]
Bump, have a patch that fixes this issue in my forked repo. Waiting to submit until acknowledgement of this issue!

**Comment by bradenwright** [comment]
Any updates?  It would be nice to move forward on this.

**Comment by kargakis** [comment]
@kubernetes/sig-cluster-lifecycle-misc

**Comment by roberthbailey** [comment]
We'd welcome a patch to fix this.

**Comment by roberthbailey** [comment]
The salt configuration was removed in #58248.

/close
