### ISSUE TITLE
ability to schedule resource installations without a running cluster

### ISSUE THREAD

**Issue by multi-io** [kubernetes/kubernetes#44820]
I'd like to have a documented way to schedule the installation or configuration of arbitrary  resources in a K8s cluster without the API being available, conceptually similar to the kubelet `--pod-manifest-path` (`/etc/kubernetes/manifests`), but not restricted to just pods or just a specific node.

This would useful e.g. during an automated/CM cluster setup, where the API comes up asynchronously and may not be ready for several minutes. Currently you'd have to loop in the client until the API is up and then issue the necessary create/apply commands.

My best guess is that etcd would be the right place for something like this (provided the etcd cluster itself is brought up quickly/synchronously), but maybe a filesystem path on a master node would be easier or cleaner.

I guess I could try putting the manifest JSONs where k8s itself stores the resource definitions in etcd, e.g. under `/registry/services/specs/`, but that's undocumented at best it seems.

**Comment by liggitt** [comment]
I don't think we want to increase the number of paths speaking directly to etcd. Looping and waiting for the API seems like a reasonable approach.

**Comment by k82cn** [comment]
Agree with @liggitt , it's better to only access ETCD by apiserver; looping and waiting for the API seems reasonable to me. Other components in k8s does like this (looping & waiting).

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by mbohlool** [comment]
Writing directly to etcd is not a good idea. I am going to close this. If you have a design for this, please share the it and re-open the issue.
