### ISSUE TITLE
nslookup not working with flannel as network: nameserver 10.96.0.10

### ISSUE THREAD

**Issue by ajayapte** [kubernetes/kubernetes#44833]
My issue is that nslookup via busybox always shows nameserver as 10.96.0.10.  That's what busybox resolve.conf has.  I am not even running my pods on 10.* cidr.  The 10.* range is used by my kub nodes provisioned in the cloud.  Any nslookup from busybox fails and as expected any nslookup from any pod fails with same error.  I'm wondering where this 10.96.0.10 is coming from. 

root@2kub-0:~/install# kubectl exec -ti busybox -- nslookup kubernetes.default
Server:    10.96.0.10
Address 1: 10.96.0.10

nslookup: can't resolve 'kubernetes.default'

root@2kub-0:~/install# kubectl exec busybox cat /etc/resolv.conf
nameserver 10.96.0.10  ===> I would have expected this to be ip of kube-dns pod endpoint
search default.svc.cluster.local svc.cluster.local cluster.local 10.0.80.11 10.0.80.12
options ndots:5

Note that 10.0.80.11 or 12 are nameservers of the kub nodes. 

My setup - 
I am using server version 1.6.0 (client 1.6.1).  I use flannel as network addon.  Currently I am just using 1 node set up via kubeadm. 

I had to do a couple of workarounds to get this working - 
1) Manually create /run/flannel/subnet.env since that does not seem to get created in 1.6.  It got created in 1.5 so I copied from there
2) ran kube-flannel-rbak.yml as explained in another workaround.

I have dns and flannel pods running  with above setup without errors.
I do not use default cidr in flannel for network/services.  My kubeadm commans is - 
kubeadm init --pod-network-cidr 172.10.0.0/16 --service-cidr 172.16.0.0/12
I also changed kube-flannel yaml to use pod-network-cidr value.

Since 10.* address space is used by cloud provider I am using 172 for all of kub.  I am not sure where this 10.96.0.10 nameserver is getting inserted from and why. I  would have assumed that when a pod comes up it will get kube-dns endpoint as the nameserver.  The search path has my node's nameservers in it.

**Comment by MrHohn** [comment]
DNS nameserver for Pods with "dnsPolicy=ClusterFirst" is inserted through `--cluster-dns` flag on kubelet:
```
--cluster-dns stringSlice    Comma-separated list of DNS server IP address.  This value is used for containers DNS server in case of Pods with "dnsPolicy=ClusterFirst". Note: all DNS servers appearing in the list MUST serve the same set of records otherwise name resolution within the cluster may not work correctly. There is no guarantee as to which DNS server may be contacted for name resolution.
```

**Comment by ajayapte** [comment]
How do I pass this information when I am using kumeadm?  I already have deployed single node master.  I see that /etc/systemd/system/kubelet.service.d/10-kubeadm.conf has 
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"

I suppose that's the one that needs to be changed to the ip of kube-dns pod.  At what point does this need to happen in the kubeadm based deployment phase?  I did - 
kubeadm init --pod-network-cidr 172.10.0.0/16 --service-cidr 172.16.0.0/12
followed by
kubectl apply -f kube-flannel.yml

If I do it now, how do I restart the node?

**Comment by MrHohn** [comment]
I think [#33881-comment](https://github.com/kubernetes/kubernetes/issues/33881#issuecomment-251065019) answered your question :)

**Comment by ajayapte** [comment]
Perfect.  Thanks a bunch.  Comment in 33881 solved the problem.  I am going to close this one.  I have already added comments in 33881 about this and have asked that the proposed fix be put in kubeadm.  Thanks again for your help.
