### ISSUE TITLE
Pod antiaffinity not working with Deployment/Replication Controller

### ISSUE THREAD

**Issue by komalkshah** [kubernetes/kubernetes#44843]
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
EC2 instance used as bare-metal machine. Size: Large Storage: 100 GB
- **OS** (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
- **Kernel** (e.g. `uname -a`):
x86_64 GNU/Linux
- **Install tools**:
yum
- **Others**:
 

**What happened**:
I have a 3-node Kubernetes cluster setup using kubeadm. I am trying to setup a sample ngnix application such that only one Pod will be scheduled on one Node. I have used anti-affinity rule to achieve the same. Following is the yaml fie for the same:

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        scheduler.alpha.kubernetes.io/affinity: |
            {
              "podAntiAffinity": {
                "requiredDuringSchedulingIgnoredDuringExecution": [{
                  "labelSelector": {
                    "matchExpressions": [{
                      "key": "app",
                      "operator": "In",
                      "values": ["nginx"]
                    }]
                  },
                  "topologyKey": "kubernetes.io/hostname"
                }]
              }
            }
    spec:
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx-slim:0.8
        ports:
        - containerPort: 80

I expect each Pod to go on a different Node. It works for the first time this yaml is deployed. Post that **if I delete any of the Pod, the new Pod which comes up does not necessarily follow the anti-affinity rule**. At time multiple pods comes up on the same node which is not expected with "requiredDuringSchedulingIgnoredDuringExecution" especially when I have 3 different nodes.

**Anything else we need to know**:
**This same thing works as expected with StatefulSets**.  I tried deleting multiple pods at the same time with this and this still works. 
I am using following yaml for the same:

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        scheduler.alpha.kubernetes.io/affinity: >
            {
              "podAntiAffinity": {
                "requiredDuringSchedulingIgnoredDuringExecution": [{
                  "labelSelector": {
                    "matchExpressions": [{
                      "key": "app",
                      "operator": "In",
                      "values": ["nginx"]
                    }]
                  },
                  "topologyKey": "kubernetes.io/hostname"
                }]
              }
            }
    spec:
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web

I understand that the Stateful set works is that the pods as scheduled in serial manner.
I want to get this rule work for Stateless deployments as well (Deployment, ReplicationController). Can someone please help me with this? If this is a known defect is there any workaround for the same?

**Comment by komalkshah** [comment]
@ xiangpengzhao DaemonSet does not suit my requirement. Nginx is just an example I am trying. I am actually running a Cassandra cluster and hence need StatefulSets.
WRT the ticket you mentioned, I am not running 1.5.4 version of Kubernetes, will it still apply to my setup?

**Comment by komalkshah** [comment]
@xiangpengzhao I changed the syntax to include affinity in the pod spec as per #44128   and it worked. Hence closing this bug.
Just to summarise the following yaml for deployment with anti-affinity works:
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx-slim:0.8
        ports:
        - containerPort: 80

**Comment by xiangpengzhao** [comment]
@komalkshah Cool! 

But I'm still a bit confused about why affinity in annotations works with StatefulSets as you mentioned. I don't think the affinity feature versions are different for different controllers. 

@davidopp Would you please provide some explanation? Thanks!

**Comment by komalkshah** [comment]
@xiangpengzhao it so happened that the Nginx deployment with Statefulset was showing the expected behaviour (one pod per node) even without the anti-affinity rule (I verified this after Deployment anti-affinity rule worked). So the anti-affinity rule was actually not getting applied by placing it in annotation even for statefulsets but I didnt realised that as the results were as expected.
So it was my bad.
 I changed the yaml definition for StatefulSet as well. Heres the same:
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx
            topologyKey: kubernetes.io/hostname
      containers:
        - name: nginx
          image: gcr.io/google_containers/nginx-slim:0.8
          ports:
          - containerPort: 80
            name: web
```

**Comment by xiangpengzhao** [comment]
@komalkshah Great! :smile:

**Comment by nielsonsantana** [comment]
I tried your exemple of `Deployment` @komalkshah but only worked when I use `operator: NotIn`.
When use `NotIn` operator, kubernetes only launch the pods in the same number of nodes. If there more replicates than nodes, then the deployment will be pending until the number of nodes be created.
