### ISSUE TITLE
cluster/ubuntu not available

### ISSUE THREAD

**Issue by ajit-drag** [kubernetes/kubernetes#44841]
Hi, 
I am following https://kubernetes.io/docs/getting-started-guides/ubuntu/manual/. So I took the latest git pull from `git clone --depth 1 https://github.com/kubernetes/kubernetes.git`. The problem is I am not able to find `cluster/ubuntu/`.

**Comment by xiangpengzhao** [comment]
This deployment is deprecated and the guide has not been updated. See: #44344 

@mikedanese @resouer

**Comment by ajit-drag** [comment]
If the above deployment is deprecated what you suggest for installation on ubuntu servers ?

**Comment by xiangpengzhao** [comment]
@ajit-drag you can try kubeadm. See: https://kubernetes.io/docs/getting-started-guides/kubeadm/

**Comment by ajit-drag** [comment]
But according to above link is only for Ubuntu 16.04+, I want a solution for ubuntu 14.04+. Will above installation work for ubuntu 14.04?

**Comment by xiangpengzhao** [comment]
cc @mikedanese
