### ISSUE TITLE
Wrong cgroup-driver set on kubelet with centos SaltBase installation

### ISSUE THREAD

**Issue by benjigoldberg** [kubernetes/kubernetes#44852]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`): v1.6.2

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel** (e.g. `uname -a`):
`Linux k8s-master 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**:
Terraform and the Saltbase installer from this repository
- **Others**:

**What happened**:
When installing on CentOS7 via salt, the cgroup driver is not set, which defaults to setting the cgroup root to `docker`, which is incorrect. Like debian, the `--cgroup-driver` should be set to `systemd` on CentOS7.

**What you expected to happen**:
`--cgroup-driver` should be set to `systemd`

**How to reproduce it** (as minimally and precisely as possible):
standup a CentOS7 machine and attempt to provision a salt master.

**Anything else we need to know**:
Happy to submit a patch to fix this issue as per the contributing guidelines if this issue is accepted.

**Comment by benjigoldberg** [comment]
Bump, have a patch that fixes this issue in my forked repo. Waiting to submit until acknowledgement of this issue!

**Comment by kargakis** [comment]
@kubernetes/sig-cluster-lifecycle-misc

**Comment by roberthbailey** [comment]
We'd welcome a patch to fix this.
