### ISSUE TITLE
client-go enhancement for kube-scheduler.

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#44851]
**Kubernetes version** (use `kubectl version`):
master branch

**What happened**:
When creating PR for #44188 , it found some required packages/funcs are missed; open this issues to trace/handle related issues.

**What you expected to happen**:
All required packages/funcs by kube-scheduler are here in client-go.

**Comment by k82cn** [comment]
- [ ] "features " is missed:
In https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/schedulercache/reconcile_affinity.go#L23 , it use `features. AffinityInAnnotations`; but client-go seems not update features accordingly.

- [ ] "v1.helper" missed: there's ` ./staging/src/k8s.io/client-go/pkg/api/helper` which return `api.*`; in kube-scheduler, we're using `v1.*`.

**Comment by deads2k** [comment]
I think the feature flag should be set by the command line options, not by something in the client.

Can you provide a link to where the helper functions are currently used?  We have had to duplicate some in the past.

**Comment by k82cn** [comment]
> I think the feature flag should be set by the command line options, not by something in the client.

The name of features is used; e.g. `features.AffinityInAnnotations` at https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go#L75

> Can you provide a link to where the helper functions are currently used? We have had to duplicate some in the past.

`IsOpaqueIntResourceName` is used; https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/helper/helpers.go#L34
