### ISSUE TITLE
RFE: Option allow components(sched+cm) to lock on ConfigMaps on startup

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#44857]
**FEATURE REQUEST**:
Provide an input option to controller manager and scheduler to lock on user specified ConfigMaps vs. Endpoints to remove the known scalability, and security issues that exist. 

**Kubernetes version** :
1.7+

**Environment**:
All 

/cc @kubernetes/sig-cluster-lifecycle-feature-requests @kubernetes/sig-scheduling-feature-requests

**Comment by bsalamat** [comment]
Could you please provide a bit more details about the existing issues or reference them?

**Comment by timothysc** [comment]
@bsalamat https://docs.google.com/document/d/1lH9OKkFZMSqXCApmSXemEDuy9qlINdm5MfWWGrK3JYc/edit#

**Comment by mikedanese** [comment]
I'm ok with this.

**Comment by mikedanese** [comment]
I'm ok with this but not sure if it's considered a breaking change if we do this by default.

**Comment by timothysc** [comment]
@mikedanese I was going to opt-in at 1st.

**Comment by timothysc** [comment]
@mikedanese or @ncdc is there a root issue for starting components from componentconfig, and is there a timeframe on it?  

HA updated story is to componentconfig->configmap + lock on configmap.

**Comment by timothysc** [comment]
I'll have a PR up today.

**Comment by ncdc** [comment]
@timothysc it's maybe https://github.com/kubernetes/features/issues/115, although that doesn't really have any details in it. This is probably a better link despite its age: https://github.com/kubernetes/kubernetes/issues/12245.

**Comment by timothysc** [comment]
Forgot to update this issue.  @mikedanese put up his grand unified field theory on ComponentConfigs ;-) 

https://docs.google.com/document/d/1arP4T9Qkp2SovlJZ_y790sBeiWXDO6SG10pZ_UUU-Lc/edit#heading=h.xgjl2srtytjt
