### ISSUE TITLE
Saltbase installer does not generate a ca.crt for the kubelet

### ISSUE THREAD

**Issue by benjigoldberg** [kubernetes/kubernetes#44855]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`): v1.6.2

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel** (e.g. `uname -a`):
`Linux k8s-master 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**:
Terraform and Saltbase from this repository
- **Others**:

**What happened**:
The kubernetes salt installer from this repository expects a ca.crt to be present in `/srv/salt/kubelet` but does not use the salt cert generator to create and place the ca.crt.

**What you expected to happen**:
Salt should detect if no `ca.crt` is present and then proceed to use the cert generator in the saltbase directory to create a ca crt.

**How to reproduce it** (as minimally and precisely as possible):
Stand up a salt master and then provision a kubernetes master slave. Provisioning will fail because the kubelet tasks cant be completed.

**Anything else we need to know**:
I am happy to submit a patch for this issue as per your contributing guidelines if this issue is accepted.

**Comment by kargakis** [comment]
@kubernetes/sig-cluster-lifecycle-misc

**Comment by roberthbailey** [comment]
The ca.crt file must match between the master and the nodes. Salt expects the ca.crt file to be delivered out of band so that it can match. If each kubelet generated it's own ca.crt file then it would be impossible to establish secure communication between the kubelet and the apiserver.

**Comment by benjigoldberg** [comment]
@roberthbailey Yep that makes perfect sense. Back when I filed this I didn't quite grasp how this works. Thank you for the response and clarification. I will close this out.
