### ISSUE TITLE
kubectl get nodes -w output is updated every few seconds instead of only on changes

### ISSUE THREAD

**Issue by rata** [kubernetes/kubernetes#44879]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kubectl node watch

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Debian
- **Kernel** (e.g. `uname -a`):
- **Install tools**: kops
- **Others**:

**What happened**:
`kubectl get nodes -w` updates every few seconds with nodes already listed that didn't change their state. 

**What you expected to happen**:
List all nodes and only add extra output on changes, like `kubectl get pods -w` work.

**How to reproduce it** (as minimally and precisely as possible):
`kubectl get nodes -w`

**Anything else we need to know**:
It happens with kubectl 1.2 in a 1.2 cluster too. So, probably this is a long standing bug.

**Comment by liggitt** [comment]
Nodes actually do change every few seconds. They report status back and update their status timestamp, which results in watch events coming back
