### ISSUE TITLE
Feature Ask: Azure Cloud DNS Provider

### ISSUE THREAD

**Issue by jpoon** [kubernetes/kubernetes#44874]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T23:37:30Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.2
- **Kernel** (e.g. `uname -a`): Linux k8s-master-30143214-0 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: ACS
- **Others**:

As of 1.6, the current DNS providers are [AWS (Route53), CoreDNS, Google, (CloudDNS)](https://github.com/kubernetes/kubernetes/tree/master/federation/pkg/dnsprovider/providers). The ask is to implement a DNS provider for Azure.

cc @xtophs @colemickens

**Comment by spzala** [comment]
area/dns

**Comment by spzala** [comment]
sig/network

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#130.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
