### ISSUE TITLE
Add service labels to iptables rule comment

### ISSUE THREAD

**Issue by frankgreco** [kubernetes/kubernetes#44889]
this is a **FEATURE REQUEST**

currently, when the kube-proxy creates an iptables rule, it write a `proxyServiceMap` in the comments. An example of this is as follows (where `proxyServiceMap` is "default/kanali:app-port"):

```sh
-A KUBE-SEP-FD2E3TSMHWTXH2RF -s 172.17.0.4/32 -m comment --comment "default/kanali:app-port" -j KUBE-MARK-MASQ
```

It would be nice if, as part of the `proxyServiceMap` or as another comment that is written with an iptables rule, the service labels were written out as comments (perhaps a comma-delimited list).

**But why?**
For layer 7 routing, looking at iptables rules is almost enough to configure an upstream proxy without needing the api server at all. However, for advanced routing (including canary), labels on services are extensively used. If service labels were included in the iptables rule comments, complex layer 7 routing could happen without needing a highly available api server.

The change needed for this is minimal and I believe lives solely within [this file](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go).

I don't mind implementing this, just want to see what the community thinks.

**Comment by pfremm** [comment]
I would also like this change.

**Comment by frankgreco** [comment]
thinking about this some more, if a service is updated (the labels change), the iptables rule would have to be updated

**Comment by dcbw** [comment]
My initial feeling is that the proxy should not be doing this since it effectively creates a parallel API outside of the apiserver that would need to be guaranteed and maintained.  @thockin what do you think?

**Comment by thockin** [comment]
Agree with @dcbw.  Sorry.
