### ISSUE TITLE
CRI: Different behavior for ContainerStatus, PodSandboxStatus and ImageStatus.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#44885]
The behavior when requested id doesn't exist is not defined clearly in CRI.

Currently, we define that `ImageStatus` should return `nil, nil` when requested image doesn't exist ([see](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/v1alpha1/runtime/api.proto#L83-L86)), and kubelet is relying on this behavior now ([see](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_image.go#L89-L91)).

However, we haven't clearly defined the behavior of `PodSandboxStatus` and `ContainerStatus`. Currently, they return error when requested sandbox/container doesn't exist, and kubelet is also relying on this behavior.

Not super urgent, just track the issue here.
@yujuhong @feiskyer /cc @kubernetes/sig-node-api-reviews

**Comment by feiskyer** [comment]
Added #44904 for clarifying the behavior.
