### ISSUE TITLE
Better error handling around kubelet stats api endpoints

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#4489]
The current classification of exceptions in the kubelet /stats pipeline is a little vague, leading confusing http error codes in innocuous situations (eg: the pod is up and the container hasn't started yet results in a 500). It would be nice to plumb errors up from the various dockert/cadvisor clients as they occur, and return the right error codes. 

This is a spinoff from #4127

**Comment by vishh** [comment]
I did some cleanup for the /containerLogs endpoint while working on #3391. It is possible to generalize #4373 for all REST endpoints.

**Comment by dchen1107** [comment]
@vissh I assigned this to you since you are doing some work related to /stats already based on our offline discussion earlier.

**Comment by vishh** [comment]
The stats API plumbing has changed a lot since this issue was filed. Closing this issue now. We can re-open if we have any issues with the new pipeline.
