### ISSUE TITLE
[RBAC] got a message: User "" cannot list pods at the cluster scope.

### ISSUE THREAD

**Issue by xiaoxi1989** [kubernetes/kubernetes#44894]
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.3", GitCommit:"5802799e56c7fcd1638e5848a13c5f3b0b1479ab", GitTreeState:"clean", BuildDate:"2017-04-24T09:32:46Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.3", GitCommit:"5802799e56c7fcd1638e5848a13c5f3b0b1479ab", GitTreeState:"clean", BuildDate:"2017-04-24T09:34:47Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:hardware configuration
- **OS** (e.g. from /etc/os-release):Centos7.2
- **Kernel** (e.g. `uname -a`):Linux cxxtest 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
I start kubernetes with RBAC:
nohup kube-apiserver --logtostderr=true --v=0 \
               --etcd-servers=http://10.211.55.3:2379 \
               --insecure-bind-address=0.0.0.0 \
               --bind-address=0.0.0.0 \
               --allow_privileged=true --service-cluster-ip-range=10.10.0.0/16 \
               --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ResourceQuota,ServiceAccount \
               --log-dir=/var/log/kubernetes  \
               --tls-cert-file=/root/ssl/server.pem \
               --tls-private-key-file=/root/ssl/server-key.pem \
               --service-account-key-file=/root/ssl/server-key.pem \
               --client-ca-file=/root/ssl/ca.pem \
               --authorization-mode=RBAC > /var/log/kubernetes/apiserver 2>&1 &

nohup kube-controller-manager --logtostderr=true --v=0 \
                        --address=10.211.55.3 --cluster-name=cxx \
                        --log-dir=/var/log/kubernetes \
                        --service_account_private_key_file=/root/ssl/server-key.pem \
                        --root-ca-file=/root/ssl/ca.pem \
                        --master=https://10.211.55.3:6443 \
                        --kubeconfig=/root/ssl/kubeconfig > /var/log/kubernetes/controller-manager 2>&1 &

nohup kube-scheduler --logtostderr=true \
                     --v=0 \
                     --master=https://10.211.55.3:6443 \
                     --address=10.211.55.3 \
                     --kubeconfig=/root/ssl/kubeconfig > /var/log/kubernetes/kube-scheduler 2>&1  &

nohup kubelet --logtostderr=true --v=0 \
        --api-servers=https://10.211.55.3:6443 \
        --address=10.211.55.3 \
        --hostname-override=10.211.55.3 \
        --allow_privileged=true \
        --pod-infra-container-image=pod-infrastructure:0.1 \
        --enable-server=true \
        --cluster_dns=10.10.10.10 --cluster_domain=cxx.com \
        --kubeconfig=/root/ssl/kubeconfig > /var/log/kubernetes/kubelet 2>&1 &

nohup kube-proxy --logtostderr=true --v=0 \
                 --master=https://10.211.55.3:6443 \
                 --kubeconfig=/root/ssl/kubeconfig  > /var/log/kubernetes/proxy 2>&1  &

**What you expected to happen**:
I want to get pod list,but get:
[root@cxxtest ~]# kubectl get pod
Error from server (Forbidden): User "cxxtest" cannot list pods in the namespace "default". (get pods)

How can i change my ClusterRole to admin or something wrong opeartion?

**Comment by danielqsj** [comment]
You can follow this guide [RBAC](https://kubernetes.io/docs/admin/authorization/rbac/).

**Example**:
Grant the admin ClusterRole to a user named “bob” in the namespace “acme”:
`kubectl create rolebinding bob-admin-binding --clusterrole=admin --user=bob --namespace=acme`

**Comment by xiaoxi1989** [comment]
@danielqsj  
this command:kubectl create rolebinding bob-admin-binding --clusterrole=admin --user=bob --namespace=acme only can exec not in  RBAC mode?

kubectl create rolebinding cxxtest-admin-binding --clusterrole=admin --user=cxxtest --namespace=kube-system
Error from server (Forbidden): User "cxxtest" cannot create rolebindings.rbac.authorization.k8s.io in the namespace "kube-system". (post rolebindings.rbac.authorization.k8s.io)

**Comment by danielqsj** [comment]
Notice this:  [Privilege Escalation Prevention and Bootstrapping](https://kubernetes.io/docs/admin/authorization/rbac/#privilege-escalation-prevention-and-bootstrapping)

**Comment by liggitt** [comment]
What user does your `/root/ssl/kubeconfig` file identify you as to the api server?

You can create the initial clusterrolebindings against the unsecured port (`kubectl create clusterrolebinding ... --server=http://localhost:8080`) or with a user in the `system:masters` group.

**Comment by xiaoxi1989** [comment]
@danielqsj  @liggitt 
I've solved it,thanks a lot。

**Comment by isansahoo** [comment]
@xiaoxi1989 : how did you solve it?

**Comment by rafaeltovarw** [comment]
kubectl create rolebinding admin --clusterrole=admin --user=NAME_ERROR_USER --namespace=default

**Comment by xiaoxi1989** [comment]
@sicklife  sorry，it just current-context configuration error.  
This is just a test cluster. It has been uninstalled.

sorry...
