### ISSUE TITLE
Clean up edit and refactor edit

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes#44905]
Fix comments left in https://github.com/kubernetes/kubernetes/pull/39404.
Make other necessary refactor changes to `edit` to make it easier for `edit last-applied`.

**Comment by kargakis** [comment]
We can proceed with this now that edit has been made re-usable.

**Comment by kargakis** [comment]
Oh well, I was thinking of a different issue https://github.com/kubernetes/kubernetes/issues/38761 - this is done.
