### ISSUE TITLE
Federated Ingress fails at high loads

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#44907]
I filed an issue with some debugging information and details in the Ingress repo -  https://github.com/kubernetes/ingress/issues/645. I am also filing it to here to track federated ingress flakiness. This is critical and is blocking us from making federation presubmits "required" for all PRs.

@csbell assigning it to you for triaging.

/assign @csbell 

/priority failing-test

/sig federation

cc @kubernetes/sig-federation-bugs

**Comment by madhusudancs** [comment]
https://github.com/kubernetes/ingress/issues/645 was mostly about surfacing the hidden errors and turned out that was not sufficient to debug the issue.  It also turns out https://github.com/kubernetes/ingress/pull/652 wasn't sufficient to fix the underlying issue. 


@nicksardo has a new hypothesis that explains the reason behind this bug at high loads pretty well. I am just writing down his hypothesis here. 


Let's assume that we have 3 federated clusters and a Federated Ingress object `foo.` The current design of the Federated Ingress controller picks one of the 3 clusters as the leader cluster and propagates the Ingress object `foo`, to this leader cluster. It then depends on the Cluster Ingress controller (GLBC) in the leader cluster to allocate GCP L7 resources and update the status/annotations on leader cluster's version of `foo`. Federated Ingress controller then copies that status/annotations to the Federated Ingress object and propagates that to the remaining clusters.


GLBC, on the other hand, garbage collects (GCs) the GCP resources that aren't used anymore. GLBC runs the GC cycle at the end of every sync loop. Since there are 3 clusters in federation with independent GLBCs that share the same Ingress UID, they operate on the same set of GCP L7 resources. 


At high loads, sync loops run often and hence also GC resources frequently. Since we elect a leader cluster and wait for the GCP resources to be created by that cluster's controller, the controllers in other clusters that don't know anything about the Ingress associated with these GCP resources yet try to GC those resources. This leads to a deadlock where the leader cluster never succeeds in creating the load balancer as the resources get garbage collected by the other clusters.

@nicksardo has proposed a two-pronged approach to solve this problem

1. In GLBC, move the GC cycle out of the sync loop and instead run it periodically, once every 10 or 15 minutes.
2. Dramatically simplify Federated Ingress controller by eliminating the leader election logic and just propagating Ingress resources to all the underlying clusters simultaneously. This works because all the Ingress controllers in the underlying clusters create GCP resources using the same name since they share the same UID and these create operations are idempotent. Even if there are propagation or processing delays in one of the clusters, they should all eventually reach a stable state. Only caveat is to ensure that the ingress UID configmaps are synced across the clusters before the first Ingress object is propagated to the clusters.

This has a nice side effect in that this makes Federated Ingress controller look similar to other federated controllers.

cc @csbell

**Comment by quinton-hoole** [comment]
@madhusudancs @csbell @nicksardo 

1. As far as I recall the cluster's GLBC's only share the same UID because the Federated Ingress Controller chooses one of their UID's (via the described leader election), and propagates it to the other clusters, hence I don't think that 2 above works?
2. Why not just fix the GLBC garbage collection logic.  It seems that's the root cause of the problem (i.e. GLBC deletes LB's that are still in use by other clusters).  Can you make GLBC aware that other clusters are still using the LB, and hence prevent it from garbage collecting it? That seems both simple and effective.

Or am I missing something here?

**Comment by madhusudancs** [comment]
> As far as I recall the cluster's GLBC's only share the same UID because the Federated Ingress Controller chooses one of their UID's (via the described leader election), and propagates it to the other clusters, hence I don't think that 2 above works?

Federated Ingress unifies the UIDs using a leader election logic. My fault, I should have probably clarified that. UID unification will still continue to use the same logic. But that logic is not required for syncing Ingress objects and that's not required. Once the UIDs are unified, Ingress objects can be propagated.

> Why not just fix the GLBC garbage collection logic. It seems that's the root cause of the problem (i.e. GLBC deletes LB's that are still in use by other clusters). Can you make GLBC aware that other clusters are still using the LB, and hence prevent it from garbage collecting it? That seems both simple and effective.

We have talked about this and @csbell has some ideas around ref-counting but it is not clear how to implement that using the current GCP APIs, esp. we do not know if it possible to do concurrency control of L7 resources. As a side note: GCS allows such concurrency control on the storage buckets and objects.

**Comment by madhusudancs** [comment]
> Can you make GLBC aware that other clusters are still using the LB, and hence prevent it from garbage collecting it? That seems both simple and effective.

@quinton-hoole also, any ideas around how to make that possible are welcome.

**Comment by nicksardo** [comment]
1. A UID will still be chosen and propagated to the other clusters - that's unavoidable. But this can happen well before any ingress objects are created. The UID is also being moved to the service controller so GCP internal and L7 LBs can share instance groups. 

2.  Making the GLBC aware of other clusters would probably mean adding state to configmap or doing something really ugly like putting state in resource Description fields. In my opinion, it's simpler to program the GLBC to handle existing resources and add cluster-specific backends where necessary.

**Comment by quinton-hoole** [comment]
@madhusudancs @csbell @nicksardo 
Yes, a few ideas:

1. I don't know what you mean by "concurrency control of L7 resources" but I think at most all you need is optimistic concurrency (e.g. version ID's, like in Kubernetes), to prevent two API clients (in this case GLBC's) from trampling on each other.
2. Beyond that, I think it might be even easier than that, potentially.  Each GLBC can see what IP's are behind the LB.  If only it's own clusters IP's are there, then no other cluster is using the LB, and it can be deleted. You will need to do something to avoid the obvious race condition there, but that seems doable (e.g. using a lock resource on the GCE API).

**Comment by quinton-hoole** [comment]
@nicksardo @madhusudancs @csbell It's probably worth having an in-person discussion about this, as I really don't understand all the above arguments, and it will probably be quicker to resolve this with a quick discussion.  Call me any time on my cell if you need to.

**Comment by madhusudancs** [comment]
> I don't know what you mean by "concurrency control of L7 resources" but I think at most all you need is optimistic concurrency (e.g. version ID's, like in Kubernetes), to prevent two API clients (in this case GLBC's) from trampling on each other.

That's what I mean. What are those version ID's that could be compared-and-swapped using GCP APIs?

 > Beyond that, I think it might be even easier than that, potentially. Each GLBC can see what IP's are behind the LB. If only it's own clusters IP's are there, then no other cluster is using the LB, and it can be deleted. You will need to do something to avoid the obvious race condition there, but that seems doable (e.g. using a lock resource on the GCE API).

I am not entirely sure what you mean here. Also, not sure what you mean by using a lock resource. Where would that be stored?

**Comment by nicksardo** [comment]
@quinton-hoole 
The ingress GC logic will be changing and get smarter - that's a given. Given that there are 7 different types of resources and the introduction of the service-controller sharing resources with the GLBC (same region), these changes may or may not be trivial. The first priority will be to decrease the frequency of GC - it's achievable and most likely make this a non-issue.

My second point is that we're not sure we need to let a single GLBC create LB resources before others.  If federated ingress sends out the object to all clusters, n-1 clusters could fail on the first sync, but be fine on the next. This task is not necessary to make federated ingress stable, sorry if it came off that way.

**Comment by marun** [comment]
@madhusudancs Should this issue be blocking 1.7?

**Comment by csbell** [comment]
No.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#131.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
