### ISSUE TITLE
[Question] Write to secret volume from pod

### ISSUE THREAD

**Issue by Dm3Ch** [kubernetes/kubernetes#44917]
Hello!
Is it possible to write to the secret volume from pod?

 I'd like to store my ssl certs in secret, but I'm using Let's Encrypt certs and I need to re-issue them every 3 month, I thought I can make a cronjob, to update certs with certbot, but i can't find how could I mount secret volume for write.

**Comment by liggitt** [comment]
writing to the local volume won't persist the changes... you'd probably want to write the updated cert back to the secret.

**Comment by Dm3Ch** [comment]
@liggitt Thank you for answer. How could I write updated cert back to the secret(from pod)?

**Comment by liggitt** [comment]
the process responsible for renewing the certificate would need write access to the API. How you grant that depends on the authorization mode your cluster is using. With RBAC authorization, granting the `edit` or `admin` role in the namespace would give sufficient permission to read/write secrets
