### ISSUE TITLE
cidr_set bitmap should be compressed

### ISSUE THREAD

**Issue by rpothier** [kubernetes/kubernetes#44918]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
latest

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
cidr_set.go in pkg/controller/node currently uses a bitmap to track the subnets allocated.
The current allocation logic assumes a small allocation range. This bitmap could grow very large with the introduction of IPv6.
The v6 code in cidr_set.go currently limits the difference between the cluster mask size and subnet mask size to 16. This restriction could be removed if the bitmap was compressed.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by smarterclayton** [comment]
We should also support the same compression on other bit masks at the same time.  We use random allocation for many of the spaces which leads to sparse masks.

**Comment by smarterclayton** [comment]
We should replace the current form with http://roaringbitmap.org/about/, but we'll need to record the version change somehow.

**Comment by kargakis** [comment]
@kubernetes/sig-network-misc

**Comment by aojea** [comment]
/reopen

This imposes limitations on IPv6 for the node mask that can be used
https://github.com/kubernetes/kubernetes/pull/79993

**Comment by bowei** [comment]
It would be good to clarify where the scalability issue lies -- it may be in memory and w/ the serialized format that is stored on disk; would need different strategy for each.

**Comment by aojea** [comment]
> It would be good to clarify where the scalability issue lies -- it may be in memory and w/ the serialized format that is stored on disk; would need different strategy for each.

Right, I'm trying to understand the problem first.
This change (if needed) most sure will need a KEP, as Lubomir just suggested in the PR I'm using to test the related changes.

**Comment by aojea** [comment]
After being discussed in the KEP https://github.com/kubernetes/enhancements/pull/1534 current size seems enough, we can always revisit if we start to see limitations on the address size.

**Comment by BenTheElder** [comment]
/reopen
https://github.com/kubernetes/kubernetes/issues/94029 ?

**Comment by aojea** [comment]
> /reopen
> #94029 ?

I had a working implementation with compressed bitmaps here #86620, but I think that there are better ideas in https://github.com/kubernetes/enhancements/pull/1881#issuecomment-672135245

**Comment by aojea** [comment]
> > /reopen
> > #94029 ?
> 
> I had a working implementation with compressed bitmaps here #86620, but I think that there are better ideas in [kubernetes/enhancements#1881 (comment)](https://github.com/kubernetes/enhancements/pull/1881#issuecomment-672135245)

/close
this is not the right fix, will be better if we can move away from the allocators
