### ISSUE TITLE
Hook for "remove for good" on DaemonSet

### ISSUE THREAD

**Issue by bboreham** [kubernetes/kubernetes#44911]
**FEATURE REQUEST**

Some software, designed to work with Kubernetes, installs itself on every node via a DaemonSet, creating some side-effects on each node that a user would like to clear down when finished using that software.
An example is [Weave Net](https://www.weave.works/documentation/net-latest-kube-addon/), which I work on, but there are several others.

When it comes to uninstalling, I can see a few choices:
 * Clear things down on pod delete. If the pod deletion is just for an upgrade, or perhaps a temporary scheduling condition, this is unnecessarily disruptive.
 * Clear things down via some additional software, outside of Kubernetes. This is extra work for the user to source and load onto machines.
 * Code up some sort of remote signal sent to each pod warning that the next delete is final. This has all kinds of race conditions and bad user experience.

My preferred idea at present is if the pod can be told on deletion whether this is for just one pod or for the entire DaemonSet.

Any other ideas?

**Comment by dunjut** [comment]
Maybe install a script on host node which periodically watches if the CNI pod is still there, after some reasonable continuous times of CNI pod lost, the script does the clean-up work.

**Comment by bboreham** [comment]
@dunjut how are you suggesting that script gets onto each node?

**Comment by dunjut** [comment]
@bboreham Perhaps mounting the host's cron-job scripts directory into CNI pod, then we can put a job there. Just like `Calico` utilizes a dedicated installation container which mounts necessary host paths.

**Comment by lukaszo** [comment]
There is a proposal for running a defer pods https://github.com/kubernetes/community/pull/483 It may help here.

**Comment by bboreham** [comment]
Thanks; after following the links I think this issue is really a duplicate of #35183 so will close this.
