### ISSUE TITLE
Node failed to enter NotReady state during flaky suites

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#44933]
/assign @saad-ali @childsb 

This is a top source of failure for this week.

Triage failure cluster: https://storage.googleapis.com/k8s-gubernator/triage/index.html#eba1ba01921bf541729e

Example failure text:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-disruptive.go:152
Apr 17 17:21:42.996: Node bootstrap-e2e-minion-group-4fzg failed to enter NotReady state
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-disruptive.go:242
```

Example job: https://k8s-testgrid.appspot.com/google-gce#gci-gce-flaky

Expectations: as a top source of failure this issue should interrupt assignees until the issue is closed. sig leads should `/assign` an appropriate owner and `/unassign` themselves.

**Comment by wongma7** [comment]
`I0426 11:55:31.106] Apr 26 11:55:31.105: INFO: ssh jenkins@104.198.176.115:22: stderr:    "sudo: /etc/init.d/kubelet: command not found\n"`\\

kubelet never gets restarted and so never enters NotReady. Are we not installing the salt stuff on test clusters anymore? I'm not familiar with how that works at all. What's the proper way to restart kubelet here?

**Comment by copejon** [comment]
@fejta I've got a PR for submitted and going through review iterations.

**Comment by fejta** [comment]
Thanks for the update!
