### ISSUE TITLE
Make "kubectl drain" use taint instead of Unschedulable

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#44944]
kubectl drain: Place NoSchedule taint, then do evictions as today
kubectl uncordon: Remove the taint

ref/ #25320

@kubernetes/sig-scheduling-feature-requests 
cc/ @mml

**Comment by ravisantoshgudimetla** [comment]
@davidopp I can work on this, if no one else has started.

**Comment by thockin** [comment]
Does this deprecate the Unschedulable field?

**Comment by davidopp** [comment]
Define "deprecate"...

I don't think we can get rid of Unschedulable until we do a v2 of the API. Too many people are using it. Marking it "deprecated" seems fine though, to try to push people towards using NoSchedule taints instead.

**Comment by davidopp** [comment]
@ravisantoshgudimetla I don't have the bandwidth to review it for 1.7, but if @mml has time to review it then it's fine for you to implement it.

**Comment by thockin** [comment]
"deprecate" here means "tell people it is going away eventually, and to use
taints instead".  Deprecation policy is clear that this is a long, slow
process, but if we want to ever get rid of it, start now.

On Thu, Apr 27, 2017 at 1:41 AM, David Oppenheimer <notifications@github.com

**Comment by davidopp** [comment]
Yes, that's reasonable.

**Comment by ravisantoshgudimetla** [comment]
@davidopp Ok, I was under the impression that this is needed for 1.7, if not I can circle back to this later.

**Comment by ravisantoshgudimetla** [comment]
@davidopp @mml 

So, I have started working on this and the way I want to implement this:

For drain:
- Check for list of taints available on the node and if one the taints have a `NoSchedule` effect, no taints would be added to it.
- If not, add a taint which has `NoScheule` effect.

Uncordon would be exact opposite operation.

I am a bit concerned about effect part. Please let me know WYT.

**Comment by davidopp** [comment]
I think just adding a NoSchedule taint (and opposite for uncordon) is sufficient -- no need to check whether there are already taints on the node. (Unless I'm missing some corner case you have in mind?)

The trickier part is making sure this doesn't break the current users of cordon, since Unschedulable is unfortunately not the exact same thing as a NoSchedule taint.

ref/ #42001

cc/ @kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by luxas** [comment]
> The trickier part is making sure this doesn't break the current users of cordon, since Unschedulable is unfortunately not the exact same thing as a NoSchedule taint.

@davidopp I think I have an idea, but can you elaborate on the edge cases?

**Comment by ravisantoshgudimetla** [comment]
@davidopp 
> The trickier part is making sure this doesn't break the current users of cordon, since Unschedulable is unfortunately not the exact same thing as a NoSchedule taint.

So, the way I want to do it - I will update both unSchedulable field and NoSchedule taint for cordon and uncordon with a comment mentioning that unSchedulable will be eventually deprecated. Would it cause any problem, looking at the code, it seems drain is mostly a client side functionality(no code in server for it), so we should be good.

>  no need to check whether there are already taints on the node. (Unless I'm missing some corner case you have in mind?)

Its not an edge-case as such but I am thinking of - why to add a NoSchedule taint if one already exists.

**Comment by aveshagarwal** [comment]
>Its not an edge-case as such but I am thinking of - why to add a NoSchedule taint if one already exists.

You can not use an existing NoSchedule taint on a node, because that means there are pods that tolerate it and can be scheduled. And that means it wouldn't work as Unschedulable.

I think we should have a standard NoSchedule taint for such drain cases and make sure during validation that no pod is allowed to have any toleration tolerating this standard NoSchedule to ensure it works as Unschedulable.

**Comment by ravisantoshgudimetla** [comment]
> You can not use an existing NoSchedule taint on a node, because that means there are pods that tolerate it and can be scheduled. And that means it wouldn't work as Unschedulable.

Thanks for the input @aveshagarwal but should we care about that scenario? The user explicitly wants his/her pod to be placed on node that has NoSchedule taint. AFAIU even now DaemonSet controller don't respect the unSchedulable field and  as a result could schedule pods onto nodes that are being drained.

> I think we should have a standard NoSchedule taint for such drain cases and make sure during validation that no pod is allowed to have any toleration tolerating this standard NoSchedule to ensure it works as Unschedulable.

Isn't that against the concept of taints and tolerations? We are creating a taint which will have no toleration.

**Comment by aveshagarwal** [comment]
> Thanks for the input @aveshagarwal but should we care about that scenario? The user explicitly wants his/her pod to be placed on node that has NoSchedule taint. AFAIU even now daemonSet controller doesn't respect the unSchedulable field and as a result could schedule pods onto nodes that are being drained.

i did not say we should not use NoSchedule taint. i said we should not use an existing NoSchedule taint on a node as a signal for Unschedulable.

> Isn't that against the concept of taints and tolerations? 

I dont think so.

**Comment by davidopp** [comment]
At the sig-scheduling meeting today we realized it is not possible to implement this in a backward-compatible way because we allow pods to tolerate wildcard taint, so controllers that generate pods that tolerate wildcard taint would have their pods no longer be drain-able after upgrading the master.

(I think that in the absence of wildcard taint, it would be OK to implement this.)

I think we should close this issue. In the v2 API we could theoretically get rid of wildcard toleration and then it would be OK to implement this. (Users who want to opt in to being able to schedule onto machines that are draining could do so, e.g. maybe a very short-running batch job.)

**Comment by wking** [comment]
Something similar [landed][1] in #61161, although that PR didn't touch kubectl.  There's some discussion [here][2] about accepting the possibility of pods which tolerate the unscedulable taint.

[1]: https://github.com/kubernetes/kubernetes/pull/61161#event-1526141050
[2]: https://github.com/kubernetes/kubernetes/pull/61161/files#r174927986
