### ISSUE TITLE
Make conditions displaying of different object consistent in 'kubectl describe' command

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#44948]
Found that many objects in the current [describe.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/internalversion/describe.go) don't have consistent fields of their conditions be printed.  e.g.

pod:
```
w.Write(LEVEL_0, "Conditions:\n  Type\tStatus\n")
```

node:
```
w.Write(LEVEL_0, "Conditions:\n  Type\tStatus\tLastHeartbeatTime\tLastTransitionTime\tReason\tMessage\n")
```

deployment:
```
w.Write(LEVEL_0, "Conditions:\n  Type\tStatus\tReason\n")
```

We should make them display consistent fields. Either printing all of the fields of each object conditions , or printing some same selected fields, e.g. `Type Status Reason Message` might be okay.

We might also want to display conditions for other objects, whose conditions are not displayed currently yet.

I'll work on this after we decide which way we want to display conditions.

ref: https://github.com/kubernetes/kubernetes/pull/44710

@soltysh @smarterclayton

**Comment by soltysh** [comment]
@kubernetes/sig-cli-bugs fyi

**Comment by soltysh** [comment]
@xiangpengzhao go ahead and open a PR and ping me in it.

**Comment by xiangpengzhao** [comment]
OK. Will do.

**Comment by kargakis** [comment]
The conditions will differ between resources .. They already do. Having all of them be the same will be hard.

**Comment by kargakis** [comment]
Also I don't think this is a bug

**Comment by xiangpengzhao** [comment]
Yeah they are different. How about display all of the fields of its conditions for each resource?

**Comment by smarterclayton** [comment]
Some of that info isn't always relevant.  If we print too much info,
we risk making it hard for users to understand what is going on.
Describe doesn't have to show everything, but it should show enough
for a user to know there is an action needed.

**Comment by xiangpengzhao** [comment]
From a user's perspective, when something doesn't happen as expected, the sequence of getting info or debugging might be as below:

- `kubectl get foo`
- `kubectl get foo -o wide`
- `kubectl describe foo`
- `kubectl get foo -o json`
- vi log
- dig into code

Yes we should give necessary but not verbose info in each step. As for describe, what info to display is just perfect? Users might be confused by that why resource `foo` has conditions but `bar` doesn't.

**Comment by kargakis** [comment]
> As for describe, what info to display is just perfect?

Timestamps and messages which tend to be verbose may be omitted.
