### ISSUE TITLE
Network becomes unavailable on terminating pods

### ISSUE THREAD

**Issue by kirs** [kubernetes/kubernetes#44956]
**What keywords did you search in Kubernetes issues before filing this one?**: terminationGracePeriodSeconds, termination, network.

---

**Is this a BUG REPORT or FEATURE REQUEST?**: Bug report

**Kubernetes version**: 1.6.0

**Environment**:
- **Cloud provider or hardware configuration**: GCP and minikube
- **OS**: `Alpine Linux v3.4`
- **Kernel**: Linux 4.7.2

**What happened**:

Pod in "Terminating" state loses network connection two minutes after it was scheduled for termination, while still performing the work in the container. The bug prevents a pod from gracefully finishing the work.

**What you expected to happen**:

Terminating pod should gracefully finish the work with network being available according to `terminationGracePeriodSeconds`.

**How to reproduce it** (as minimally and precisely as possible):

Run a pod that does something like:

```ruby
require 'net/http'
loop do
  Net::HTTP.get_response('google.com', '/')
  sleep 1
end
```

For convenience I pushed the script to the docker hub (`kirshatrov/sleep-with-signals:v2`).

Create the pod with longer terminationGracePeriodSeconds policy:

```
apiVersion: v1
kind: Pod
metadata:
  name: gracefully-terminating-pod
spec:
  containers:
  - name: app
    image: kirshatrov/sleep-with-signals:v2
  terminationGracePeriodSeconds: 1500
```

Delete the pod (`kubectl delete pod gracefully-terminating-pod`) and watch the logs.

After two minutes the network will go down and the app will crash with:

```
Failed to open TCP connection to google.com:80 (getaddrinfo: Try again) (SocketError)
```

**Anything else we need to know**:

This happens both in GCP and Minikube on Kubernetes 1.6.0.
The kind of work we're performing in the containers is not safely interruptible and we'd like to use longer termination timeout (`terminationGracePeriodSeconds`) to allow the pod to finish the work before it's killed. This networking issue prevents us from relying on `terminationGracePeriodSeconds`.

cc @ibawt @Sirupsen @dwradcliffe @dturn

**Comment by kirs** [comment]
When trying to inspect the terminating pod that's gracefully shutting down:

```
$ kubectl exec gracefully-terminating-pod echo hello -i -t --namespace kirs-testing
rpc error: code = 2 desc = "oci runtime error: exec failed: lstat /proc/25368/ns/ipc: no such file or directory"
```

At the same time I can see the container when I run `docker ps` on the kubelet host. It looks like kubelet tries to tear down the container ignoring that it can be still within graceful termination period.

**Comment by Random-Liu** [comment]
This is a regression in CRI integration in 1.6.

We have a 2 minutes timeout for `StopContainer` in CRI client. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/remote/remote_runtime.go#L212
This causes `StopContainer` to exceed timeout if the grace period specified by user is longer than 2 minutes.

In our kube docker client, we changed the timeout based on the timeout specified by caller https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/kube_docker_client.go#L162

We should do the same in CRI client. Will send a PR to fix this and cherrypick to 1.6.

@kirs Thanks for reporting the issue, will fix this soon.

**Comment by dchen1107** [comment]
@kirs thanks for reporting the issue, and we are going to include the fix in 1.6.3.

cc/ @kubernetes/kubernetes-release-managers

**Comment by kirs** [comment]
Thanks for a quick reply!

**Comment by kirs** [comment]
🎉 🎉 🎉

**Comment by kirs** [comment]
What's the timeline for 1.6.3 release?
