### ISSUE TITLE
API discovery docs do not provide ETag information for clients

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#44957]
We implemented "re-discovery" if the resource name doesn't match one we know:

```
kubectl get posd  # <-- triggers full rediscovery
```

1. Unfortunately, this means that having a typo here will now always take >2-5s to resolve (if you're on a slow connection, it could be minutes).
2. If you typo twice in a row, you download all discovery docs twice (the odds of this actually helping are almost zero)
3. We don't have etag or "if not modified" checks on these resources... so the user has to download them every time and they are not small
4. We get rate limited by the client (throttled client side) when we download these - which means when you have lots of groups we get even slower.

We need to be smarter, this is very annoying even when latency is 0.

**Comment by smarterclayton** [comment]
@kubernetes/sig-cli-bugs

**Comment by liggitt** [comment]
cc @kubernetes/sig-api-machinery-feature-requests

**Comment by sttts** [comment]
5. We have one discovery request per api group. It could be one, with **one** eTag.
