### ISSUE TITLE
RFE: Enumerate the list of issues with shadow pooling (kubernetes all the way down)

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#44958]
I've harped on the fact that most other systems allow you to run the multiple deployments under them. 

Think running 1...N kubernetes clusters on kubernetes, which could in turn host their own kubernetes clusters. (Turtles all the way down).   In grids of yore, we called this shadow pooling, and it was the primary way we vetted deployments before rolling them into production.  It has an assortment of other benefits as well, namely ease of upgrades and support for letting operators experiment on multiple versions.  

The biggest issues that I was aware of when I first started asking these questions was: Why can't we do this?  At the time there were a number of problems mostly related to docker, but we have not revisited. 

I'd like to revisit this question and start to enumerate the exact list of known issues folks have here.

/cc @kubernetes/sig-node-feature-requests  @kubernetes/sig-cluster-lifecycle-feature-requests @ConnorDoyle

**Comment by timothysc** [comment]
@dchen1107 as you are both the release manager and sig-node lead, I think fixing this would go a looong way towards folks having the ability to test release candidates on their own clusters.

**Comment by davidopp** [comment]
Is this a dup of #246?

**Comment by timothysc** [comment]
246 is too old, and should be scrapped imo. 
The purpose of this is to come up with an "up to date list."

**Comment by luxas** [comment]
@timothysc Should we close this or keep it open?
