### ISSUE TITLE
gke-staging suite is failing during logging soak test

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#44977]
Here's one instance.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-staging/2498

I0426 10:41:36.139] [k8s.io] Rescheduler [Serial]
I0426 10:41:36.140] [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:826[0m
I0426 10:41:36.140]   should ensure that critical pod is scheduled in case there is no resources available
I0426 10:41:36.140]   [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/rescheduler.go:69[0m
I0426 10:41:36.140] [90m------------------------------[0m
I0426 10:41:36.140] [36mS[0m
I0426 10:41:36.140] [90m------------------------------[0m
I0426 10:41:36.140] [0m[k8s.io] Logging soak [Performance] [Slow] [Disruptive][0m 
I0426 10:41:36.140]   [1mshould survive logging 1KB every 1s seconds, for a duration of 2m0s, scaling up to 1 pods per node[0m
I0426 10:41:36.140]   [37m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/logging_soak.go:82[0m
I0426 10:41:36.140] [BeforeEach] [k8s.io] Logging soak [Performance] [Slow] [Disruptive]
I0426 10:41:36.141]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:141
I0426 10:41:36.141] [1mSTEP[0m: Creating a kubernetes client
I0426 10:41:36.141] Apr 26 10:41:36.139: INFO: >>> kubeConfig: /workspace/.kube/config
I0426 10:41:36.141] 
I0426 10:41:36.145] [1mSTEP[0m: Building a namespace api object
I0426 10:41:36.176] [1mSTEP[0m: Waiting for a default service account to be provisioned in namespace
I0426 10:41:36.180] [It] should survive logging 1KB every 1s seconds, for a duration of 2m0s, scaling up to 1 pods per node

...

I0426 10:43:36.887] Apr 26 10:43:36.865: INFO: Found 2 / 3
I0426 10:43:36.887] Apr 26 10:43:36.865: INFO: WaitFor completed with timeout 2m0s.  Pods found = 2 out of 3
I0426 10:43:36.887] Apr 26 10:43:36.865: INFO: Error in wait... timed out waiting for the condition
I0426 10:43:36.888] panic: 
I0426 10:43:36.888] Your test failed.
I0426 10:43:36.888] Ginkgo panics to prevent subsequent assertions from running.
I0426 10:43:36.888] Normally Ginkgo rescues this panic so you shouldn't see it.
I0426 10:43:36.888] 
I0426 10:43:36.888] But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
I0426 10:43:36.888] To circumvent this, you should call
I0426 10:43:36.888] 
I0426 10:43:36.889] 	defer GinkgoRecover()
I0426 10:43:36.889] 
I0426 10:43:36.889] at the top of the goroutine that caused this panic.
I0426 10:43:36.889] 
I0426 10:43:36.889] 
I0426 10:43:36.889] goroutine 14787 [running]:
I0426 10:43:36.889] panic(0x256eb80, 0xc422f81390)
I0426 10:43:36.890] 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
I0426 10:43:36.890] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo.Fail(0xc421de3090, 0x49, 0xc421dcfcd0, 0x1, 0x1)
I0426 10:43:36.890] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:247 +0x114
I0426 10:43:36.890] k8s.io/kubernetes/test/e2e/framework.Failf(0x2a1137f, 0x13, 0xc421dcfdb0, 0x1, 0x1)
I0426 10:43:36.890] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:281 +0x140
I0426 10:43:36.890] k8s.io/kubernetes/test/e2e.RunLogPodsWithSleepOf(0xc420387110, 0x3b9aca00, 0xc4215b0031, 0x5, 0x1bf08eb000)
I0426 10:43:36.891] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/logging_soak.go:133 +0x679
I0426 10:43:36.891] k8s.io/kubernetes/test/e2e.glob..func59.2.1(0xc4219e1fe8, 0xc420387110, 0x3b9aca00, 0x1bf08eb000, 0xc4215b0020)
I0426 10:43:36.891] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/logging_soak.go:73 +0x1c2
I0426 10:43:36.891] created by k8s.io/kubernetes/test/e2e.glob..func59.2
I0426 10:43:36.891] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/logging_soak.go:76 +0x12b
I0426 10:43:37.161] 
I0426 10:43:37.161] Ginkgo ran 1 suite in 5h16m38.279656943s
I0426 10:43:37.161] Test Suite Failed

cc @fejta @kubernetes/sig-scheduling-bugs

**Comment by piosz** [comment]
cc @jayunit100

**Comment by msau42** [comment]
The last few runs seem to be ok, so maybe it's not an issue anymore?
https://k8s-testgrid.appspot.com/google-gke-staging#gke-staging

**Comment by crassirostris** [comment]
No occurrences last two weeks, closing as obsolete
