### ISSUE TITLE
CRI: Why do we need PodSandboxStatus.Linux.Namespaces.Network?

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#44972]
Now, in CRI we expose the network namespace in `PodSandboxStatus`, but kubelet is not using it.

Actually, now only network plugin needs the network namespace, but the network logic is moved down to runtime.

There seems to be no reason to keep this field except for debugging

@yujuhong @feiskyer 
@kubernetes/sig-node-api-reviews

**Comment by feiskyer** [comment]
I think we can keep this for debugging, and add a log in kubelet. 

@Random-Liu Does these fields help for debugging containerd integration?

**Comment by yujuhong** [comment]
I am in favor of removing the network namespace field from CRI since runtime owns the network piece completely.

/cc @thockin @freehan

**Comment by freehan** [comment]
> I am in favor of removing the network namespace field from CRI since runtime owns the network piece completely.

SGTM

**Comment by Random-Liu** [comment]
@yujuhong SGTM. I found that field is useless when implementing containerd integration. Then how about I send a PR to remove it?

**Comment by feiskyer** [comment]
OK. I will send a PR to remove it.
