### ISSUE TITLE
settings API group should have a PodPresetTemplate type

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#44971]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

---

In SIG service-catalog, we have plans for controllers to create `PodPreset` resources as part of their work.  Currently, there is no `PodPresetTemplateSpec` resource that would allow APIs to be constructed that express requirements for a pod preset spec to be created as well as `ObjectMeta` fields like labels and annotations.

Proposed type:

```go
type PodPresetTemplateSpec struct {
  metav1.ObjectMeta

  Spec PodPresetSpec
}
```

**Comment by derekwaynecarr** [comment]
I would clarify that the "We" in this scenario is the service-catalog.
