### ISSUE TITLE
e2e tests for cloud-controller-manager

### ISSUE THREAD

**Issue by wlan0** [kubernetes/kubernetes#44975]
The cloud-controller-manager is almost complete now, but does not have e2e tests for it to go to beta.

**Comment by wlan0** [comment]
@luxas, can you assign this to me pls?

**Comment by luxas** [comment]
@wlan0 Done!

cc @thockin @rrati @roberthbailey

**Comment by grodrigues3** [comment]
@kubernetes/sig-testing-misc

**Comment by fejta** [comment]
This is more appropriate for sig-scheduling or whoever owns the cloud-controller-manager, not sig-testing

**Comment by wlan0** [comment]
Well I'm writing the test, and building the cloud-controller-manager. This is going into the sig-cluster-ops SIG I think. @luxas?

**Comment by luxas** [comment]
sig-cluster-lifecycle last time we talked ;)
Yeah, SGTM.

@fejta Of course not! That wasn't our intention ;) Don't know why the bot tagged this with sig/testing. However, it may be beneficial that you know about this effort anyway.

**Comment by fejta** [comment]
Agreed, thanks for the heads up :)

**Comment by luxas** [comment]
And if there was a sig-cloud (which @thockin talked briefly about in another thread), this work would belong to that sig

**Comment by roberthbailey** [comment]
@wlan0 is this going to make it for 1.7 or should we bump the milestone to 1.8?

**Comment by wlan0** [comment]
Hey @roberthbailey Sorry, I don't have the bandwidth right now, it has to be bumped up to 1.8

**Comment by luxas** [comment]
ok @wlan0 thanks for confirming

**Comment by roberthbailey** [comment]
@wlan0 - is this going to make 1.8 or should we punt to 1.9?

**Comment by wlan0** [comment]
@roberthbailey Still working on it. We should target 1.9.

**Comment by dims** [comment]
@wlan0 punt to 1.10?

**Comment by jberkus** [comment]
Howdy, this issue is now stale.  It will be automatically removed from 1.10 on Monday at Code Freeze.  If there's work going on, and you don't want that to happen, please update the issue, thanks!

**Comment by jberkus** [comment]
Never mind the bot, since this issue is Stale, and we no longer need it to test the munger, we're removing it from the milestone.
