### ISSUE TITLE
PodSecurityPolicy and PersistentVolumes

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#44982]
In today's implementation, PodSecurityPolicy only limits volume types are directly specified in the pod.  Do we also want to support PersistentVolumeSource types?

If the main purpose is to just limit HostPath volumes, then it is mostly ok as HostPath cannot be used as a PV for in a cluster with more than one node.  But if want to limit other types, then it may be worth expanding the policy to PVs.

cc @kubernetes/sig-storage-feature-requests @kubernetes/sig-node-feature-requests

**Comment by smarterclayton** [comment]
We deliberately don't limit PVC because admins / admin processes are
assumed to vet those.  A namespace user can't lie about being able to
reference a PV if they don't have access to them.  PSP defends against
namespace users escalating their level of access.

**Comment by msau42** [comment]
How do admins restrict what namespaces can bind to non-namespaced PVs?

**Comment by kargakis** [comment]
@kubernetes/sig-storage-feature-requests @php-coder

**Comment by liggitt** [comment]
You can completely prevent PVC usage using PSPs by ommitting persistent volume claims from the set of allowed volume types.
