### ISSUE TITLE
ReplicaSet Controller not aware of annotation changes

### ISSUE THREAD

**Issue by qwe5456** [kubernetes/kubernetes#44999]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): deployment, replicaset, cache, annotation
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.5.6

**Environment**:
- **Cloud provider or hardware configuration**: OpenStack
- **OS** (e.g. from /etc/os-release): Ubuntu 14.04

**What happened**:
If one of the controllers adds an annotation to an replicaset, the replicaset controller's `updateRS()` function will not be able to notice the change. But if user changes the annotation via kubectl, the replicaset controller will notice the change.

**How to reproduce it** (as minimally and precisely as possible):
Will update later.

**Comment by kargakis** [comment]
> If one of the controllers adds an annotation to an replicaset, the replicaset controller's updateRS() function will not be able to notice the change.

Why?

**Comment by qwe5456** [comment]
Hi @kargakis , thank you for your reply.

I did some more investigation and found this issue might be caused by the adoption of shared informers. 
According to the [controller's development instruction](https://github.com/kubernetes/community/blob/master/contributors/devel/controllers.md), all the controllers share the same cache now. 

I have been working on v1.0 for a long time and just moved on to v1.5.0, so the different behavior surprised me. Now I think this might not be an issue since it is by design.

**Comment by kargakis** [comment]
@qwe5456 can you explain more the "If one of the controllers adds an annotation to an replicaset" part? What do you mean by "controller"? If that controller is using the API to update the ReplicaSet, the ReplicaSet controller should see the update eventually.
