### ISSUE TITLE
PodCIDR different than Flanned subnets

### ISSUE THREAD

**Issue by jfpucheu** [kubernetes/kubernetes#45001]
Hello, 

i don't know if it is normal the PodCIDR display on nodes are different than Flanneld subnets.
This is not blocking pods takes IP in flanneld CIDR.

**Kubernetes version** (use `kubectl version`):
v1.5.5 & v1.6.*

**Environment**:
- **Cloud provider or hardware configuration**: openstack
- **OS** (e.g. from /etc/os-release): Centos 7.3
- **Kernel** (e.g. `uname -a`):  3.10.0-514.el7.x86_64
- **Others**:
flannel-0.7.0-1.el7.x86_64
kubernetes-cni-0.3.0.1-0.07a8a2.x86_64

**What happened**:

The PodCIDR display by kubectl from nodes are differents than the real subnets Used by flannel on nodes.

etcdctl ls /kube/network/subnets
/kube/network/subnets/172.12.1.0-24
/kube/network/subnets/172.12.98.0-24
/kube/network/subnets/172.12.67.0-24
/kube/network/subnets/172.12.49.0-24
/kube/network/subnets/172.12.2.0-24
/kube/network/subnets/172.12.33.0-24

kubectl describe nodes | grep PodCIDR
PodCIDR:			172.12.1.0/24
PodCIDR:			172.12.6.0/24
PodCIDR:			172.12.0.0/24
PodCIDR:			172.12.4.0/24
PodCIDR:			172.12.5.0/24
PodCIDR:			172.12.3.0/24

**What you expected to happen**:

The PodCIDR display by kubernetes should be the same as flannel ones.

**How to reproduce it** (as minimally and precisely as possible):

install kubernetes with flannel

**Anything else we need to know**:

**Comment by danielqsj** [comment]
+1
Why PodCIDR is allocated by controller-manager instead of being reported by kubelet periodically?

**Comment by thockin** [comment]
see #57130
