### ISSUE TITLE
Multiple ways to create REST client

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#45019]
client-go is a mess. Not that it's very surprising or revealing, but I was playing with adding traces to K8s and had to modify client. When you try to do that you end up with looking at numerous functions like `RESTClientFor`, `NewRESTClient`, `UnversionedRESTClientFor` and who knows what else. Do we really need all of them? Can't we just have one that takes (maybe modified) config and does everything that's necessary?

cc @k8s-mirror-api-machinery-feature-rqusts @caesarxuchao

**Comment by caesarxuchao** [comment]
It looks like we should make `NewRESTClient` private and try to remove `UnversionedRESTClientFor`

**Comment by k82cn** [comment]
+1

**Comment by frankgreco** [comment]
shouldn't this issue be opened in the [client-go](https://github.com/kubernetes/client-go) repo?

**Comment by dims** [comment]
@k82cn @gmarek can we please drop the 1.8 milestone on this issue?
