### ISSUE TITLE
Large dockerd memory leak when streaming kubelet logs

### ISSUE THREAD

**Issue by jsravn** [kubernetes/kubernetes#45026]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
memory leaks docker 1.12 kubelet logs
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
1.4.8

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.2
- **Kernel** (e.g. `uname -a`): Linux ip-10-10-10-10 4.8.0-49-generic #52~16.04.1-Ubuntu SMP Thu Apr 20 10:55:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**: docker 1.12

**What happened**:
Noticed some of our dockerd processes using several gigs of RSS, worse case was over 6Gi.

**What you expected to happen**:
dockerd shouldn't use more than about 100Mi.

**How to reproduce it** (as minimally and precisely as possible):
Stream logs from kubelet api, ideally for a heavily loaded server with lots of logs. Disconnect client abruptly so that kubelet gets a TCP reset.

**Anything else we need to know**:

The follow log appears in kubelet logs when it happens (sanitised for internal names):
```
I0426 10:18:08.757103    2560 server.go:967] GET /containerLogs/my-ns/my-service-267577793-602b7/my-service?follow=true: (224.989
63ms) 400
goroutine 3089119 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc82214e150, 0x190)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:219 +0xa3
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc82214e150, 0x190)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:198 +0x2b
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteHeader(0xc820a39320, 0x190)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:200 +0x41
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteErrorString(0xc820a39320, 0x190, 0xc820a39980, 0x52, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:180 +0x11a
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteError(0xc820a39320, 0x190, 0x7fea4eccc1c0, 0xc824155680, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:165 +0x8d
k8s.io/kubernetes/pkg/kubelet/server.(*Server).getContainerLogs(0xc8207ec0f0, 0xc823bc11d0, 0xc820a39320)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:499 +0x14e9
k8s.io/kubernetes/pkg/kubelet/server.(*Server).(k8s.io/kubernetes/pkg/kubelet/server.getContainerLogs)-fm(0xc823bc11d0, 0xc820a39320)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:352 +0x34
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc820c30120, 0x7fea4ed59220, 0xc82214e150, 0xc821da10a0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:272 +0xf30
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x7fea4ed59220, 0xc
82214e150, 0xc821da10a0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc8208bbb00, 0x7fea4ed59220, 0xc82214e150, 0xc821da10a0)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc8201e2090, 0x7fea4ed59220, 0xc82214e150, 0xc821da10a0)
        /usr/local/go/src/net/http/server.go:1910 +0x17d
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc820c30120, 0x7fea4ed59220, 0xc82214e150, 0xc821da10a0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:287 +0x43
k8s.io/kubernetes/pkg/kubelet/server.(*Server).ServeHTTP(0xc8207ec050, 0x7fea4ed59220, 0xc82214e150, 0xc821da10a0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:966 +0x138
net/http.serverHandler.ServeHTTP(0xc820a24e00, 0x7fea4ed591e8, 0xc823be88f0, 0xc821da10a0)
        /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8216fd400)
        /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2137 +0x44e
logging error output: "write tcp 10.10.10.1:10250->10.10.10.2:49428: write: connection reset by peer"
```

In this case we're using kubectl so apiserver is making the connection.

Each time this message appears in the kubelet logs, dockerd memory usage goes up quite drastically. It's almost like kubelet isn't closing something properly to docker, and then docker doesn't free up the related memory. It's also most likely a function of the size of logs involved, since we don't see this in lightly loaded environments.

It's probably a bug in docker that it doesn't free up the allocations, but kubelet should take care to close things properly if it's not already doing so.

**Comment by jsravn** [comment]
I'm not having much luck reproducing this, unfortunately. But the few nodes with large dockerd increases all had the above error messages when the increases happened (at 1m resolution). I'll have to keep monitoring and see what happens.

**Comment by jsravn** [comment]
Ok, I was able to reproduce to an extent but not as much as I saw. Running heavy logs while several kubectl streamers, I was able to expand the dockerd memory footprint from about 80Mi to 180Mi over about 10 minutes. After killing the apiserver that memory never seems to get reclaimed. It could be a lot of things though - it may just be the GC being overly greedy. Maybe some sort of throttling of log rate is in order though, or shared buffers (it seems like every kubectl logs I do increases the dockerd's memory footprint).

**Comment by kargakis** [comment]
@kubernetes/sig-node-bugs

**Comment by yujuhong** [comment]
Closing since 1.4.8 is no longer supported. Please open a new issue if the problem manifests in a newer version.

**Comment by jsravn** [comment]
Still happens in kube 1.8, on docker 1.12. I haven't been able to pinpoint the problem though. Our workaround is to just restart docker (with live-restore) when approaching some memory limit.
