### ISSUE TITLE
Consolidate or make explicit the logic for the node_status and node_controller, to make code more explicit and status logs more obvious to users.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#45029]
# Feature request 

Goal: Incrementally improve the transparency and simplicity of the node's logging of status updates and communication with the apiserver,

- for context, in #44577 we discussed that the timings in the node retries are coupled intentionally to behaviour of other components in the system, for example, the node controller.... but that PR may or may not move forward... 
- In any case, we can follow up here with a more subtle improvement that doesn't change the explicit timings, but does consolidate logic / logging /readability of the behaviour.

Problem: 

- The node checks in several times consecutively for registration.  This is a nonstandard and awkward communication pattern, hard to understand when looking at logs in failure scenarios.
- Does a non exponential retry for registration.  So likely it just fails 5 times in a row in most cases.
- syncNodeStatus is essentially a heartbeat function, and that heartbeat pattern should be exposed to other parts of the code that rely on it - such as the nodeController.  right now, the dependency is implicit.

Solution: 

- At the very least, we should unify the logic between the kubelet heartbeat and the node controller in *one place*, i.e something like `struct NodeHeartbeatConfig {}` or something (can't think of a good name for it right now.  That heartbeat can be used to make coupling explicit, rather then implicit , between controller vs node timings.
- At best, we should make the heartbeat more configurable and easy to log, with better metrics, and configurable exponential backoff.
- Better yet, do both :).  

Lets see what we can agree on, im happy just implementing the first bullet if thats acceptable.  cc @kubernetes/sig-node-proposals ...

**Comment by jayunit100** [comment]
The #44577 PR was a first pass at ideas, lets make the plan more explicit in here, and move forward with an implementation that is conservative enough to agree on.  @dchen1107 @gmarek @yujuhong .

**Comment by gmarek** [comment]
@jayunit100 - what's the user's problem you're trying to solve?

**Comment by jayunit100** [comment]
From the user perspective, none of this is relevant :), hopefully they never have to dive into kubelet logs.

**Comment by jayunit100** [comment]
Per gmarek's comment, I've collated a  few concrete issues we can / should tackle as part of this: 

- https://github.com/kubernetes/kubernetes/issues/42796 Take a look at how much logging spam is required to ascertain the behaviour.
- https://github.com/kubernetes/kubernetes/issues/41916 " kubelet did not pick up on the daemon being down."
- https://github.com/kubernetes/kubernetes/issues/33491 controller manager detachment "I'm not sure how this happens yet,"

**Comment by davidopp** [comment]
I think maybe what @gmarek was getting at was that we should have a good justification before we start making changes, since it generates a lot of review work, can introduce new bugs, etc. But yeah, breaking it down into small, easily-reviewable pieces can mitigate some of the risk.

**Comment by jayunit100** [comment]
Ack, gmarek/davidopp: First series of improvements will be no-ops - then we can debate the thorny subject of backoffs which is largely subjective.
