### ISSUE TITLE
Flag --gather-metrics-at-teardown isn't working for kubemark

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#45038]
We recently tried to enable e2e metrics gathering for our 100-node kubemark test (https://github.com/kubernetes/test-infra/pull/2587), but seems like it's not working (ref: http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-100-gce/2464/artifacts/):
```
I0427 06:40:05.651] [1mSTEP[0m: Gathering metrics
I0427 06:40:05.651] W0427 06:40:05.558134    9446 metrics_grabber.go:74] Master node is not registered. Grabbing metrics from Scheduler and ControllerManager is disabled.
I0427 06:40:15.953] Apr 27 06:40:15.952: INFO: MetricsGrabber failed grab metrics. Skipping metrics gathering.
```

The reason could be due to using the wrong client, viz. talking with real master instead of kubemark master, but need to verify it.

cc @wojtek-t @gmarek

**Comment by gmarek** [comment]
Yup. Known issue.

**Comment by gmarek** [comment]
Thanks for fixing this!
