### ISSUE TITLE
SELinux support for LocalVolumes

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#45054]
Once #44897 is in, SELinux support for LocalVolumes should be added.  Tests should also be written.

@kubernetes/sig-storage-feature-requests

**Comment by ddysher** [comment]
I'll take a look

**Comment by ddysher** [comment]
After a bit of research, here's what I found (no prior experience with SELinux)

In [this](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/pod-security-context.md) and [this](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/selinux.md) proposal, SELinux support is moved out of volume plugin and handled centrally in kubelet. All we can do (as a volume plugin writer) is to tell kubelet whether we support SELinux or not. If not, then nothing happens; if we do, then kubelet will simply relabel the volume when mounting, using ":Z" mount option found in docker.

In SELinux enabled cluster, if user doesn't supply seLinuxOptions, then only the first container in a Pod will be able to access a volume.  To share volume, user needs to supply seLinuxOptions with same label.  Therefore, to share local volume across different containers and pods, there's nothing significant we can do apart from turning on SELinux support option. It is user's responsibility to make sure context is correct.

 @msau42, also @pmorie ?

**Comment by msau42** [comment]
Ok awesome.  Should we still add some e2es?

**Comment by ddysher** [comment]
Theoretically, we don't need to add more tests as it is processed in kubelet and already covered in security context tests [here](https://github.com/kubernetes/kubernetes/blob/316876060ace20dc7230824cd284eeb1a621fa9c/test/e2e/security_context.go#L144).  But this test uses emptydir or hostpath, so for completeness, we can add one once we have local volume support.
