### ISSUE TITLE
running more than 200 instances on AWS breaks ELB LoadBalancers

### ISSUE THREAD

**Issue by rodawg** [kubernetes/kubernetes#45050]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No. By the way, the troubleshooting link above gives a 404. 

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

I searched for: `filterlimitexceeded`, `aws 200 nodes`.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS VPC
- **OS** (e.g. from /etc/os-release): CentOS 7
- **Kernel** (e.g. `uname -a`): `Linux ip-172-24-130-171 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**: Based off of the Kubernetes Github [saltbase](https://github.com/kubernetes/kubernetes/tree/master/cluster/saltbase)

**What happened**:

I increased my EC2 node count from 193 to 211 nodes in the cluster, including 3 master nodes.

As new minion nodes registered with the master nodes, I saw these messages in the `kube-controller-manager` logs:

```
I0426 14:01:38.762788       6 servicecontroller.go:640] Detected change in list of current cluster nodes. New node set: [<LESS THAN 200 IP ADRESSES CUT FOR BREVITY>]
I0426 14:01:39.867171       6 aws.go:3204] Caching instances for map[<LESS THAN 200 IP ADRESSES CUT FOR BREVITY>]
I0426 14:01:40.229331       6 aws_loadbalancer.go:410] Instances added to load-balancer <AWS-ELB-ID>
I0426 14:01:41.097669       6 aws.go:3172] Returning cached instances for map[]
I0426 14:01:42.407771       6 servicecontroller.go:648] Successfully updated 28 out of 28 load balancers to direct traffic to the updated set of nodes
```

The logs shortly after show the following message (I removed the list **200** of IP addresses):

```
I0426 14:21:52.491594       6 aws.go:3195] Failed to describe instances map[<200+ IP ADRESSES CUT FOR BREVITY>]
E0426 14:21:52.527573       6 servicecontroller.go:663] External error while updating load balancer: error listing AWS instances: FilterLimitExceeded: The maximum number of filter values specified on a single call is 200
        status code: 400, request id: .
... more of the same ...
I0426 14:36:59.085949       6 servicecontroller.go:648] Successfully updated 23 out of 28 load balancers to direct traffic to the updated set of nodes
```
These error messages continue for a while as new minions registered with the master nodes and everything looked fine for about 4 hours (apart from the `FilterLimitExceeded` errors continuing in the logs).

I then updated the manifests one at a time on each master for the `kube-apiserver`, `kube-controller-manager`, and `kube-scheduler` to modify the cpu and memory limits and resources. `kubelet` restarted them immediately.

The startup logs look normal from what I can tell, until here:

```
I0426 18:10:32.511555       6 servicecontroller.go:285] Ensuring LB for service default/dashboard
I0426 18:10:32.511810       6 aws.go:2505] EnsureLoadBalancer(kubernetes, default, dashboard, us-east-1, , [{ TCP 80 {0 3000 } 32723}], [<200+ IP ADRESSES CUT FOR BREVITY>], map[service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout:60 service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled:true service.beta.kubernetes.io/aws-load-balancer-internal:0.0.0.0/0 service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled:true service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout:60])
I0426 18:10:32.588765       6 aws.go:3195] Failed to describe instances map[<200+ IP ADRESSES CUT FOR BREVITY>]
E0426 18:10:32.588995       6 servicecontroller.go:760] Failed to process service. Retrying in 1m20s: Failed to create load balancer for service default/dashboard: error listing AWS instances: FilterLimitExceeded: The maximum number of filter values specified on a single call is 200
        status code: 400, request id: 
```

The same continues for a few different AWS ELBs, none of which work from this point on because they no longer have any minions registered.

I removed all but 199 minions at which point things looked normal:

```
I0426 22:33:03.699605       6 servicecontroller.go:640] Detected change in list of current cluster nodes. New node set: [<LESS THAN 200 IP ADRESSES CUT FOR BREVITY>]
I0426 22:33:04.575034       6 aws.go:3204] Caching instances for map[<LESS THAN 200 IP ADRESSES CUT FOR BREVITY>]
I0426 22:33:04.699348       6 aws_loadbalancer.go:421] Instances removed from load-balancer <AWS-ELB-ID>
I0426 22:33:05.260161       6 aws.go:2954] Adding rule for traffic from the load balancer (sg-XXXXXX) to instances (sg-XXXXXX)
I0426 22:33:05.342123       6 aws.go:2028] Existing security group ingress: sg-XXXXXX [{
<SECGRP_INFO>
}]
I0426 22:33:05.342299       6 aws.go:1930] Comparing sg-AAAAAA to sg-BBBBBB
I0426 22:33:05.342316       6 aws.go:1930] Comparing sg-AAAAAA to sg-CCCCCC
I0426 22:33:05.342359       6 aws.go:2056] Adding security group ingress: sg-BBBBBB [{
  IpProtocol: "-1",
  UserIdGroupPairs: [{
      GroupId: "sg-AAAAAA"
    }]
}]
...
I0426 22:33:06.882652       6 servicecontroller.go:648] Successfully updated 28 out of 28 load balancers to direct traffic to the updated set of nodes
```

**What you expected to happen**:

I expected the Kubernetes AWS code to support more than 200 instances when using the DescribeInstances call to the EC2 API.
 
**How to reproduce it** (as minimally and precisely as possible):

On a Kubernetes cluster running on AWS:
- set up a Kubernetes Service of `type: LoadBalancer`
- increase the total node count to a number greater than 200
- verify that the `FilterLimitExceeded` messes show up
- cycle restart through all of your `kube-apiserver`, `kube-controller-manager`, and `kube-scheduler`
- verify that the AWS ELB created above has no healthy nodes behind it

**Anything else we need to know**:

**Comment by rodawg** [comment]
I have a clarification to the bug report -- the minions attached to the AWS ELB were not marked `Unhealthy`, they were de-registered from the ELB.

This caused a site outage for us because the AWS ELB handling traffic was public facing. It also took down several other internal facing ELBs.

**Comment by justinsb** [comment]
I propose we keep this instance for ELBs, and use 47516 for the equivalent EBS problem.

They may turn out to have the same solution, but I think ELB's usage of the instance information is sufficiently different that they may not.
