### ISSUE TITLE
Refactoring taints logic to reduce sprawl across components.

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#45060]
As a follow-up on the discussion that we had on #43171 and sig-scheduling meeting, I wish to consolidate the points that were raised there wrt taints logic sprawl in kubectl.

- Some functions like reorganizeTaints in taints.go in pkg/kubectl/cmd/ need to moved to another location(either api/helpers.go or new TaintController pkg) - @gmarek, @timothysc 
- Refactor the testing suite to reflect the new changes.

Those are specific to the kubectl. 

/cc @timothysc @gmarek @aveshagarwal @k82cn @adohe @jayunit100

Please add other files if you happen(ned) to work or if you know.

**Comment by gmarek** [comment]
Any idea which sig should be responsible for this? I don't have any...

**Comment by timothysc** [comment]
I'd ideally like to see the utility libraries pushed under the scheduler subdir and just call-outs and consolidation in the other locations.

**Comment by ravisantoshgudimetla** [comment]
> I'd ideally like to see the utility libraries pushed under the scheduler subdir and just call-outs and consolidation in the other locations.

Makes sense @timothysc. I will put up a minimal PR sometime next week.

**Comment by gmarek** [comment]
I'm not convinced that it's should be under scheduler. There's other kinds of taints, i.e. 'NoExecute' ones, which have nothing to do with scheduler. Plus I don't like the idea of controllers depending on scheduler directory. Maybe we can just make a 'taint' subdir in `pkg/api` or even in `pkg`?

**Comment by k82cn** [comment]
> Maybe we can just make a 'taint' subdir in pkg/api or even in pkg?

+1 on `pkg/api`; and it's better for `client-go` to include it for all related components.

/cc @lavalamp

**Comment by ravisantoshgudimetla** [comment]
I have been looking at the structure of code-base. Would it make sense to add fn's in pkg/util/taints.go. Following are the reasons that I have in my mind for this proposal.

- In pkg/api taints.go there is a TODO which states that they don't want helper functions in that package.
- Existing fn's already seemed to have used to them like parseTaints in kubectl/cmd/taints.go.

**Comment by gmarek** [comment]
I think this is the first precedent of many to come, so we might as well spend some time to figure out where similar things should land in the future. @kubernetes/sig-api-machinery-api-reviews is probably the best ones to decide. `pkg/util` makes sense, though I think that `pkg/api` is also fine (despite the comment), as those functions will be useful for other projects that use Taints (and other objects like them in the future)

**Comment by gmarek** [comment]
Ping @k8s-mirror-api-machinery-pr-reviews

**Comment by ravisantoshgudimetla** [comment]
I am not able to mention any of sig's as I am not a member yet. I have tried pinging sig-api on slack regarding the issue. No response till now. So, I am planning to get started on moving the functions to pkg/util, unless someone has an objection.
