### ISSUE TITLE
Do not release resource(image) when using rbd storageclass.

### ISSUE THREAD

**Issue by haoyixin** [kubernetes/kubernetes#45067]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): ceph, rbd, storageclass, pvc, pv

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T22:51:55Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- **Kernel** (e.g. `uname -a`):
Linux XXX 3.10.0-327.36.3.el7.v3.4.1.XXX.x86_64 #1 SMP Mon Oct 31 16:16:32 CST 2016 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**:
- **Others**:

**What happened**:
I create a storageclass of rbd, then create a pvc claim for it. After seconds, I got a 'kubernetes-dynamic-pvc-XXX' in my pool on my ceph cluster. Until now, everything is right.

I found that a pv was create by k8s:
```
kubectl get pv pvc-XXX -o yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/rbd
  creationTimestamp: 2017-04-28T02:43:29Z
  name: pvc-XXX
  resourceVersion: "116741"
  selfLink: /api/v1/persistentvolumespvc-XXX
  uid: XXX
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: claim1
    namespace: kube-system
    resourceVersion: "116739"
    uid: XXX
  persistentVolumeReclaimPolicy: Delete
  rbd:
    image: kubernetes-dynamic-pvc-XXX
    keyring: /etc/ceph/keyring
    monitors:
    - XXX
    - XXX
    - XXX
    pool: XXX
    secretRef:
      name: ceph-secret-admin
    user: search
  storageClassName: ceph-rbd
status:
  phase: Bound
```
I deleted it from k8s cluster, then I got:
```
> kubectl describe pvc claim1

Name:		claim1
Namespace:	kube-system
StorageClass:	ceph-rbd
Status:		Lost
Volume:		pvc-XXX
Labels:		<none>
Annotations:	kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"claim1","namespace":"kube-system"},"spec":{"accessModes":["ReadW...
		pv.kubernetes.io/bind-completed=yes
		pv.kubernetes.io/bound-by-controller=yes
		volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/rbd
Capacity:	0
Access Modes:
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  1m		1m		1	persistentvolume-controller			Normal		ProvisioningSucceeded	Successfully provisioned volume pvc-XXX using kubernetes.io/rbd
  20s		20s		1	persistentvolume-controller			Warning		ClaimLost		Bound claim has lost its PersistentVolume. Data on the volume is lost!
```

Then I check my ceph pool, I found that the image wasn't deleted. Later, I deleted that pvc, but the image is still in my pool.

(BTW: If I didn't delete pv and just delete pvc, the image in my pool would be deleted correctly.)

RELATED LOG FROM controller manager (ONLY ONE):
```
I0428 02:55:37.871535       1 rbd.go:320] successfully created rbd image "kubernetes-dynamic-pvc-XXX"
``` 

RELATED K8S OBJECT BELOW
```
> kubectl get secret ceph-secret-admin -o yaml

apiVersion: v1
data:
  key: XXX
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"key":"XXX"},"kind":"Secret","metadata":{"annotations":{},"name":"ceph-secret-admin","namespace":"kube-system"},"type":"kubernetes.io/rbd"}
  creationTimestamp: 2017-04-27T11:14:57Z
  name: ceph-secret-admin
  namespace: kube-system
  resourceVersion: "43406"
  selfLink: /api/v1/namespaces/kube-system/secrets/ceph-secret-admin
  uid: XXX
type: kubernetes.io/rbd
```
```
> kubectl get storageclass ceph-rbd -o yaml

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"ceph-rbd","namespace":""},"parameters":{"adminId":"search","adminSecretName":"ceph-secret-admin","adminSecretNamespace":"kube-system","monitors":"XXX,XXX,XXX","pool":"k8s_pool","userId":"search","userSecretName":"ceph-secret-admin"},"provisioner":"kubernetes.io/rbd"}
  creationTimestamp: 2017-04-27T11:15:19Z
  name: ceph-rbd
  resourceVersion: "36369"
  selfLink: /apis/storage.k8s.io/v1/storageclassesceph-rbd
  uid: XXX
parameters:
  adminId: search
  adminSecretName: ceph-secret-admin
  adminSecretNamespace: kube-system
  monitors: XXX
  pool: XXX
  userId: XXX
  userSecretName: ceph-secret-admin
provisioner: kubernetes.io/rbd
```
```
> kubectl get pvc claim1 -o yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"claim1","namespace":"kube-system"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"3Gi"}},"storageClassName":"ceph-rbd"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/rbd
  creationTimestamp: 2017-04-28T02:55:37Z
  name: claim1
  namespace: kube-system
  resourceVersion: "117836"
  selfLink: /api/v1/namespaces/kube-system/persistentvolumeclaims/claim1
  uid: XXX
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: ceph-rbd
  volumeName: pvc-XXX
status:
  phase: Lost
```
**What you expected to happen**:
Intuitively, in production env, if a pv in use of pvc, it shouldn't be deleted.
(BTW, even if I can delete it, the resource should be released. And, a new pv should be recreated.)

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by jingxu97** [comment]
cc @kubernetes/sig-storage-bugs

**Comment by rootfs** [comment]
If you delete a PV directly, it won't trigger PV controller to unbind the PV from the PVC and storage backend to remove the image. You need to delete the PVC to delete the rbd image.
