### ISSUE TITLE
[kube-dns RBAC] Default ClusterRole is insufficient

### ISSUE THREAD

**Issue by eugene-chow** [kubernetes/kubernetes#45084]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kubedns kube-dns RBAC 1.6

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.6.2

**Environment**:
- **Cloud provider or hardware configuration**: Bare metal
- **OS** (e.g. from /etc/os-release): CoreOS 1235.6.0
- **Kernel** (e.g. `uname -a`): 4.7.3-coreos-r2
- **Install tools**: Custom
- **Others**: -

**What happened**:
kube-dns couldn't perform a GET on the kubernetes service in the default namespace. As a result kube-dns never becomes ready.
```
I0428 08:24:37.492029       1 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kube-dns/v1.6.0 (linux/amd64) kubernetes/3872cb9" -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrdWJlLWRucy10b2tlbi13NXFnYyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJrdWJlLWRucyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjhhYjM5MWQ1LTJiZGMtMTFlNy1hMjkxLTUyNTQwMDlmMmJmYiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTprdWJlLWRucyJ9.wJu8TyeEZefM1sEpyclJ-pun0EMj6sgezZBzhRQDsB7j5nzGDp8MlpIZM1vCHaqkVydy29yX7FjVsEth7m-Co8z7suLmABpqSXh7xChzucfoWHNhbw23nYA3n97pE_4LIwhIYehyjwbsWI24xE25VWeKtFBcNNPwm3me6Hm_LZ9R102lAOVZoGOWERiPlnSeLV699cT8PzzD90grDd9JfYt_TWuT77cCppOAx65iN5l4S19log-65iaRcY8hEg7Arse8P3b9M_8qZdrBEmPzKywvdG7-WtAItnzKouQkfJGGD6HFYO40FHJoPv3jP6C-iXFA2jRNqXXpIFvh1lAPrQ" https://10.3.0.1:443/api/v1/namespaces/default/services/kubernetes
I0428 08:24:37.507574       1 round_trippers.go:318] GET https://10.3.0.1:443/api/v1/namespaces/default/services/kubernetes 403 Forbidden in 15 milliseconds
I0428 08:24:37.507642       1 round_trippers.go:324] Response Headers:
I0428 08:24:37.507682       1 round_trippers.go:327]     X-Content-Type-Options: nosniff
I0428 08:24:37.507690       1 round_trippers.go:327]     Content-Length: 97
I0428 08:24:37.507696       1 round_trippers.go:327]     Date: Fri, 28 Apr 2017 08:24:37 GMT
I0428 08:24:37.507703       1 round_trippers.go:327]     Content-Type: text/plain
I0428 08:24:37.507751       1 request.go:904] Response Body: User "system:serviceaccount:kube-system:kube-dns" cannot get services in the namespace "default".
I0428 08:24:37.507780       1 request.go:995] Response Body: "User \"system:serviceaccount:kube-system:kube-dns\" cannot get services in the namespace \"default\"."
I0428 08:24:37.507854       1 dns.go:176] Ignoring error while waiting for service default/kubernetes: the server does not allow access to the requested resource (get services kubernetes). Sleeping 1s before retrying.
```

**What you expected to happen**:
No error.

**How to reproduce it** (as minimally and precisely as possible):
1. Setup k8s with RBAC enabled
1. Install kube-dns

**Anything else we need to know**:
To fix this, I added the `get` verb to kube-dns' ClusterRole. If this is the correct behaviour, I'll do a PR.

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: system:kube-dns
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - get
  - list
  - watch
```

**Comment by cmluciano** [comment]
@eugene-chow that makes sense to me. Please submit a PR when you get a chance.

**Comment by liggitt** [comment]
What version of dns are you running? The current version is tested with that role and works fine

**Comment by liggitt** [comment]
(That said, adding get permission on resources it can already list/watch is fine)

**Comment by MrHohn** [comment]
kube-dns stops using kubernetes service as ready signal since #35449, which is not released until v1.6. kube-dns released with v1.5 or before will require "get" permission.

**Comment by MrHohn** [comment]
cc @bowei

**Comment by eugene-chow** [comment]
@liggitt It says 1.6.0-alpha. The image is `gcr.io/google_containers/kubedns-amd64:1.9`
```
/ # /kube-dns --version
Kubernetes v1.6.0-alpha.0.680+3872cb93abf948-dirty
```

**Comment by liggitt** [comment]
Yeah 1.6.0-alpha.0 is pre-1.5

The current image version 1.14.1, I think

**Comment by eugene-chow** [comment]
Thanks! I presume this is a non-issue then.
