### ISSUE TITLE
pod should be deleted once preStop Hooks finished executing. 

### ISSUE THREAD

**Issue by dhilipkumars** [kubernetes/kubernetes#45140]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): prestop hooks

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version** (use `kubectl version`): master tip

**Environment**:
- **Cloud provider or hardware configuration**: dind-kubernetes
- **OS** (e.g. from /etc/os-release): ubuntu
- **Kernel** (e.g. `uname -a`): 4.4.0-72-generic
- **Install tools**: dind
- **Others**:

**What happened**:
Consider the below pod spec, which has a preStop hook that will run only for 2 seconds, but the termination grace period is configured for 10 seconds.
```
cat lifeCycleDemo.yaml
#LifeCycle Demo
apiVersion: v1
kind: Pod
metadata:
  name: lc-demo
  annotations:
    pod.beta.kubernetes.io/init-containers: '[
       {
         "name": "write-it",
         "image": "bash",
         "command": ["/usr/local/bin/bash", "-c", "echo started > /config/test.file"],
         "volumeMounts": [
            {
               "name": "config",
               "mountPath": "/config"
            }
         ]
       }
    ]'
spec:
  terminationGracePeriodSeconds: 10
  containers:
  - name: prestop
    image: bash
    command: [ "/usr/local/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 1; echo Prestop1:`date`;  cat /config/test.file; done;" ]
    volumeMounts:
      - name: config
        mountPath: /config
    lifecycle:
      preStop:
        exec:
          command: ["/usr/local/bin/bash","-c", "echo preExitHook_executing > /config/test.file; sleep 2; echo preExithook_finished > /config/test.file"]
  volumes:
      - name: config
        emptyDir: {}
```
Prestop hook will write 'executing' when its executing and 'finished' just before it finishes its execution to `/config/test.file`.  The main pod will simply print the content of the file.
**What you expected to happen**:
When we attach to the pod's logs, here is the output
```
k logs -f lc-demo
Prestop1:Sat Apr 29 03:58:59 UTC 2017
started
Prestop1:Sat Apr 29 03:59:00 UTC 2017
started
Prestop1:Sat Apr 29 03:59:01 UTC 2017
preExitHook_executing
Prestop1:Sat Apr 29 03:59:02 UTC 2017
preExitHook_executing
Prestop1:Sat Apr 29 03:59:03 UTC 2017
preExithook_finished
Prestop1:Sat Apr 29 03:59:04 UTC 2017
preExithook_finished
Prestop1:Sat Apr 29 03:59:05 UTC 2017
preExithook_finished
Prestop1:Sat Apr 29 03:59:06 UTC 2017
preExithook_finished
Prestop1:Sat Apr 29 03:59:07 UTC 2017
preExithook_finished
Prestop1:Sat Apr 29 03:59:08 UTC 2017
preExithook_finished
Prestop1:Sat Apr 29 03:59:09 UTC 2017
preExithook_finished
Prestop1:Sat Apr 29 03:59:10 UTC 2017
preExithook_finished
```

As you can see the prestop hook had completed executing 8 seconds before, but the pod is still kept alive until its original termination graceperiod.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
For scenarios where the termination grace period will be hard to predict before hand, a user might assign a very large value, but once the clean-up/wrap step is completed the POD should get deleted.  It should not wait for the whole term greace period.  Is it a bug or was it intentially designed like this?

**Comment by dhilipkumars** [comment]
@erictune @smarterclayton @kow3ns @kargakis  
This was the issue i was talking about in the app-sig meeting last time.  
Could someone please copy sig-app-lifecycle and sig-node for this bug please?

**Comment by dhilipkumars** [comment]
CC: https://github.com/kubernetes/community/pull/483

**Comment by kargakis** [comment]
@kubernetes/sig-node-bugs

**Comment by kasperbe** [comment]
I've been messing around with this issue, trying to prove it using a test.
I tried modifying the HTTPGet-PreStop test, adding an init container, using a bash container, all the things that @dhilipkumars described, however I cannot reproduce this using a unit test.

I can however following the instructions provided reproduce this quite easily. 
I was thinking to do another round of this using integration or e2e tests... Does anyone have any suggestions as to how we can prove this bug?

**Comment by dhilipkumars** [comment]
@kasperbe 
First, we need to get the attention of sig-node team to see if they agree to this as a bug before attempting to fix this.  This change in behavior might potentially break existing applications. 

The best way to test it (or add a test) should either be via integration suite or e2e rather than unit testing. 

cc @kubernetes/sig-node-bugs @kubernetes/sig-node-pr-reviews

**Comment by prathameshd9** [comment]
Hi. I am not sure if this is still relevant but I was wondering if the two cases are included where either "pod terminates right after preStop completes" or " a way to terminate pod somehow after preStop exits so it does not wait for gracePeriod to finish" ??
