### ISSUE TITLE
APIService Conditions should be set by the APIService controller

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#45145]
**Kubernetes version** (use `kubectl version`):

HEAD

https://github.com/kubernetes/kubernetes/pull/43301 merged recently, and contained the API types for the Conditions an API Service can have.

These Conditions aren't used yet, but should/will be fixed in follow-up PRs.

The primary use-case for them AFAIU is to indicate whether:
a) The APIService Service is reachable and can be relied upon
b) The APIService was able to claim the API group it tried to claim

Implementing this is necessary for beta and v1.7 since currently you can blow up your client (`kubectl`) if you create an APIService with `priority=100` and a name that lexographically sorts high and is unreachable.

If that happens (it has happened to me quite a few times), kubectl will try to connect to the APIService that doesn't exist forever, and it will block any other operation (for example with the `v1.` group).

I know one shouldn't set `priority=100` but I've seen a few examples of that already, and we're only in the beginning of the usage of AA.

cc @kubernetes/sig-api-machinery-feature-requests @kubernetes/sig-api-machinery-bugs

**Comment by luxas** [comment]
PR uploaded: https://github.com/kubernetes/kubernetes/pull/45432 :+1:

**Comment by luxas** [comment]
Did this get completely fixed with https://github.com/kubernetes/kubernetes/pull/45432 @deads2k?
In that case, we can close this ;)

**Comment by deads2k** [comment]
> Did this get completely fixed with #45432 @deads2k?
> In that case, we can close this ;)

yes
