### ISSUE TITLE
Add a `kubectl set serviceaccount` command

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#45147]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):

HEAD

Now that RBAC is going to GA, using ServiceAccounts is getting more and more important.
Still a lot of users run their apps/addons/whatever in the `default` SA.

In order for the admin to be able to change ServiceAccount easily after an application has been installed (which supposedly is crashlooping due to insufficient privs), a `kubectl set serviceaccount/sa` command could exist.

I know I can do this:
```
kubectl patch deploy <name> -p '{"spec":{"template":{"spec":{"serviceAccountName":"<sa>"}}}}'
```

but for new users to Kubernetes, it's non-obvious.

Proposed command:
```
kubectl set [serviceaccount|sa] [deployment|rc|rs|pod] [name] [serviceaccount]
```

Tracking issue: https://github.com/kubernetes/kubernetes/issues/21648

WDYT? @kubernetes/sig-cli-feature-requests @kubernetes/sig-auth-feature-requests @jbeda @janetkuo @adohe @smarterclayton @pwittrock 

This would be a good way for a new contributor to get aquainted with the code by contributing this feature.

**Comment by chandanmad** [comment]
Is anyone working on this? If not I would like to take this up.

**Comment by luxas** [comment]
@chandanmad Nobody is working on this. I would be super happy if you could contribute this feature.
Be aware of that there isn't consensus around this proposal yet (I proposed it yesterday, saturday, so people haven't had time to catch up on it)

However, I do think that this is in line with [the rest of the proposal](https://github.com/kubernetes/kubernetes/issues/21648#issuecomment-250881311), so feel free to start working on this if you want to ;)
Also, don't hesitate to ask for help if you don't know how to get started and we'll help out!

Thanks!

**Comment by deads2k** [comment]
I'm in favor of this command.  @fabianofranz ?

**Comment by chandanmad** [comment]
Thanks, I will start working on this.

**Comment by pwittrock** [comment]
Is the SA on a Pod mutable or immutable?

What about DaemonSet and StatefulSet?  Do those have SA as well?

Is there a way to do this so that it dynamically supports anything with a PodTemplate?  Maybe this should be done as a subresource that can be dynamically discovered by kubectl using the discovery service.

**Comment by pwittrock** [comment]
Maybe helpful:

[contributing instructions](https://github.com/kubernetes/community/blob/master/sig-cli/CONTRIBUTING.md)
[feature proposal template](https://raw.githubusercontent.com/kubernetes/community/master/contributors/design-proposals/sig-cli/template.md)

**Comment by liggitt** [comment]
Pod is immutable. All the other objects (with the exception of stateful set) are mutable.

**Comment by liggitt** [comment]
That pattern is the same for all the things that set aspects of a pod spec (except image, which is also mutable in pods)

**Comment by kargakis** [comment]
> Pod is immutable. All the other objects (with the exception of stateful set) are mutable.

Statefulsets are going to loosen their validation soon I expect.

**Comment by adohe** [comment]
This sounds good to me. @chandanmad just go ahead, I will help review this. Thanks ~

**Comment by chandanmad** [comment]
The outout of this command kubectl get rc/nginx-controller -o=yaml , has service acccount at the following path 'spec.template.spec.serviceAccountName' , and the corresponding pod has service account at 'spec.serviceAccountName'. Both refer to the 'serviceAccountName' field of PodSpec struct but can be made to be different by patching the ReplicationController resource.


How does ReplicationController and Pod use serviceAccountName differently?
Shouldn't the ReplicationControllerSpec have a serviceAccountName field?

**Comment by adohe** [comment]
@kargakis ptal, I think you are more familiar with ReplicationController implementation than me.

**Comment by liggitt** [comment]
> How does ReplicationController and Pod use serviceAccountName differently?
> Shouldn't the ReplicationControllerSpec have a serviceAccountName field?

ReplicationController contains a pod spec object, which contains a serviceAccountName.

**Comment by chandanmad** [comment]
Hi @adohe , how to go about writing e2e test cases for this. My development is mostly complete.

**Comment by luxas** [comment]
@chandanmad I wouldn't mind if you posted the PR now and then we'd see what e2e test makes sense to have. In order to move forward...

**Comment by chandanmad** [comment]
@luxas what are the next steps?
