### ISSUE TITLE
scheduler and controller-manager shows that bind: address already in use

### ISSUE THREAD

**Issue by xiechengsheng** [kubernetes/kubernetes#45155]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
yes

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
Keywords: bind: address already in use
Here is the similar issue: [port clash between kube-controller-manager and kube-scheduler](https://github.com/kubernetes/kubernetes/issues/13264)
The author thought there were some gremlins in his server earlier, but I installed the k8s master's components on a **brand new** machine.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.5-1+c87db499932d9c", GitCommit:"c87db499932d9ca7ba43f7195c8f213261184396", GitTreeState:"clean", BuildDate:"2017-04-30T05:16:17Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.5-1+c87db499932d9c", GitCommit:"c87db499932d9ca7ba43f7195c8f213261184396", GitTreeState:"clean", BuildDate:"2017-04-30T05:16:17Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**: 1 linux/amd64 master + 5 linux/amd64 nodes
- **Cloud provider or hardware configuration**: 6 virtual machines(memory: 4GB, CPU: 4 cores, disk: 40GB)
- **OS** (e.g. from /etc/os-release): CentOS 7.2 (master) / CentOS 7.2 (node)
- **Kernel** (e.g. `uname -a`):3.10.0
- **Install tools**: install the K8S by building the source codes

**What happened**:
```
$ /usr/bin/kube-scheduler --master=http://localhost:8080  --v=0
F0430 16:03:24.876670    3099 server.go:114] listen tcp 0.0.0.0:10251: bind: address already in use
```
```
$ /usr/bin/kube-controller-manager --master=http://localhost:8080  --v=0
F0430 16:04:18.153073    3120 controllermanager.go:157] listen tcp 0.0.0.0:10252: bind: address already in use
```
The port usage is:
```
$ netstat -tunlp | grep 10251
tcp6       0      0 :::10251                :::*                    LISTEN      2977/kube-scheduler
```
```
$ netstat -tunlp | grep 10252
tcp6       0      0 :::10252                :::*                    LISTEN      748/kube-controller 
```
the scheduler and controller-manager's status:
```
# systemctl status kube-scheduler.service
......
Active: active (running) since Sun 2017-04-30 15:59:45 CST
```
```
# systemctl status kube-controller-manager.service
......
active (running) since Sun 2017-04-30 15:18:33 CST
```
But when I stopped the scheduler service or controller-service, the port conflict messages disappeared：
```
# systemctl stop kube-scheduler.service
# systemctl stop kube-controller-manager.service
```

**What you expected to happen**:
The debug log shouldn't show the port conflict messages...But how to solve it...

**How to reproduce it** (as minimally and precisely as possible):
1. install the K8S master components by building the source codes.
2. run the above kubectl commands

**Comment by xiangpengzhao** [comment]
All the info you provided shows that kube-scheduler and kube-controller-manager have already been running as system services and binding 10251 & 10252. In such case, if you ran them in shell with the commands you provided, they would definitely fail with port conflict.

**Comment by xiangpengzhao** [comment]
There is no gremlin in your server. Don't worry, brother:)

**Comment by xiechengsheng** [comment]
@xiangpengzhao Thanks~ I see. But how can I print the scheduler debug logs to the stdout? I want to midify the scheduler's source codes, so I **try to print some information to the stdout rather than to the log files** and use the commands to see the information:
```
/usr/bin/kube-scheduler --master=http://localhost:8080  --v=4
```
But in this case, the stdout just prints the port conflicts message and shows nothing about my debug logs...I think **it is the port conficts message that causes trouble**. And do you have any idea about printing the debug logs to the stdout?

**Comment by xiangpengzhao** [comment]
If you want to run scheduler manually using the binary you compiled, you HAVE to stop the already running kube-scheduler.service, otherwise port will conflict.  (as you mentioned `But when I stopped the scheduler service or controller-service, the port conflict messages disappeared`) That means the running kube-scheduler has already bound 10251. You cannot run another kube-scheduler which will try to bind 10251 again.

You can set `--logtostderr=true` flag if you want the log to be printed to stdout.

**Comment by xiechengsheng** [comment]
@xiangpengzhao 
1. Wonderful, it works~ But the stdout later shows the message:
```
769 leaderelection.go:247] lock is held by node1 and has not yet expired
```
2. And if I want to print the debug logs to the stdout the second time, the stdout will just show the lock message and won't show my debug logs...
3. By the way, everything will work well if I print the debug logs to the log file...
4. So finally I still choose the log file to debug... That seems to be more stable... 
5. Thanks~

**Comment by xiangpengzhao** [comment]
@xiechengsheng Great! Using log file is a better way:)

**Comment by kargakis** [comment]
Use one of the support channels for these kinds of questions
