### ISSUE TITLE
The --cloud-provider flag should be mandatory for the cloud-controller-manager

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#45156]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

HEAD+https://github.com/kubernetes/kubernetes/pull/44258

When the `cloud-controller-manager` is deployed without the `--cloud-provider` flag it segfaults.
The cloud-controller-manager should just make the cloudprovider flag mandatory and crashloop without it to fix this.

Otherwise we'd have to check for `if cnc.cloud != nil {` everytime we use it, which would be tedious and error-prone.

cc @wlan0 @thockin @roberthbailey

**Comment by luxas** [comment]
@wlan0 seems like I can't assign you this issue, but you'll fix this, right?

**Comment by xiangpengzhao** [comment]
What if users run K8S in local servers without cloud provider?

**Comment by luxas** [comment]
@xiangpengzhao This won't affect normal users at all. Kubernetes can still be run on on-prem/bare-metal/cloud or whatever.

This is solely about factoring out the built-in cloudprovider code out of the kubernetes core repo (this repo).
It's a multistep process outlined in detail here: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cloud-provider-refactoring.md

This issue is saying that the cloud-controller-manager, whose only goal is to run cloud services, should consider the `--cloud-provider` flag mandatory.

cc @rrati as well

**Comment by xiangpengzhao** [comment]
Thanks Lucas for explanation! What I thought was kube-controller-manager:)

**Comment by wlan0** [comment]
Thanks for reporting this @luxas - I've added a commit in this PR (https://github.com/kubernetes/kubernetes/issues/44258) itself to fix this.
