### ISSUE TITLE
Cannot create a container on an appropriate node (with kubectl run)

### ISSUE THREAD

**Issue by parjong** [kubernetes/kubernetes#45153]
**Kubernetes version** (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: 1 linux/amd64 master + 2 linux/arm nodes 
- **OS** (e.g. from /etc/os-release): ubuntu 16.04 (master) / hypriotOS 1.4.0 (node)

**What happened**:

When running ``kubectl run armhf --image=armv7/armhf-ubuntu --rm -it -- /bin/bash``, the scheduler attempts to create a container on linux/amd64 master instead of linux/arm node

**What you expected to happen**:

I would like to crate a container on linux/arm node instead of linux/amd64 node. 

**How to reproduce it** (as minimally and precisely as possible):

 - initialize a master with ``kubeadm init`` 
 - initialize a node with ``kubeadm join``
    - kube-proxy-arm image should be pulled and taged as kube-proxy-amd64 before running ``kubeadm join``
 - run the above kubectl command

**Comment by xiangpengzhao** [comment]
If you want to create a regular pod and let it be scheduled to a linux/arm node (suppose it has label `arch=arm`), you can try this:
```
kubectl run armhf --image=armv7/armhf-ubuntu --restart=Never --overrides='{ "apiVersion": "v1", "spec": { "nodeSelector": { "arch": "arm" } } }' --rm -it -- /bin/bash
```

I don't have your image, but I simply try nginx with below command, it works.
```
kubectl run nginx --image=nginx --restart=Never --overrides='{ "apiVersion": "v1", "spec": { "nodeSelector": { "arch": "arm" } } }' --rm -it
```

Not sure how to specify `--overrides` when `--restart` is "OnFailure" or "Always". Maybe it's not complicated.

**Comment by xiangpengzhao** [comment]
@adohe Any other suggestions?

**Comment by xiangpengzhao** [comment]
Oops :sweat_smile:

**Comment by kargakis** [comment]
This can also be `kubectl run -o yaml --dry-run | kubectl set affinity [OPTIONS] - | kc apply -f -` assuming we have `set affinity` at some point.

**Comment by parjong** [comment]
@xiangpengzhao Thank you for answer. ``kubectl run armhf --image=armv7/armhf-ubuntu --restart=Never --overrides='{ "apiVersion": "v1", "spec": { "nodeSelector": { "beta.kubernetes.io/arch": "arm" } } }' --rm -it -- /bin/bash`` works well!
