### ISSUE TITLE
PersistentVolume:NFS tests in Core CI

### ISSUE THREAD

**Issue by copejon** [kubernetes/kubernetes#45172]
PR #45101 _Mark PersistentVolumes as [Feature:Volumes]_ adds the `Feature` tag to NFS backed PV tests "so that we know that we need a cloud provider that supports volumes to run this test." As a local cluster created by `local-up-cluster.sh` is not tested in CI, is it actually appropriate to use `Feature` here?  Given that the core CI environments _do_ support these tests, my understanding is that this tag is misplaced.

The issue with applying this tag is these tests will no long appear in the CI test grid, which we track for flakes.  Without this, our team is unable to track and improve these test sets.

cc @eparis @saad-ali @jeffvance @dims 

Eric:  I can see _some_ feature suites in the test grid, but not all.  Are only select `Feature`'s tested?  And are flakes in non-test grid `Feature`s reported?

**Comment by jeffvance** [comment]
cc @kubernetes/sig-storage-misc @kubernetes/sig-testing-bugs

**Comment by msau42** [comment]
I guess if you don't have NFS configured on your local machine, then these tests will fail.  Can you detect if NFS is installed and skip the test otherwise?

**Comment by msau42** [comment]
To clarify, what I think should be done is:
1. NFS tests need to check if NFS Is installed.  If not, skip the test
2. Remove the [Features:Volumes] tag from the test.

I don't think whether it can always run on a local cluster should be a criteria for inclusion in the standard CI.  That's what the [Conformance] tag is supposed to be for.  But the test should be skipped if the environment cannot run it.

**Comment by copejon** [comment]
Okay, I'll take a stab at detecting NFS support.

**Comment by copejon** [comment]
In testing against a hyperkube cluster built by `local-up-cluster.sh`, I'm unable to produce errors mentioned in the PR above.  All PersistentVolumes:NFS tests pass without issue.

@dims Can you provide some details about your test environment? Which OS?  Is NFS installed / running?  Do you have log data for the errors?

**Comment by copejon** [comment]
@msau42 Rethinking testing for NFS:  I'm not sure that this is something we want to do WRT e2e.  NFS is a supported feature of the core CI; it's baked into the GCI and debian images off which hosts are built.  Testing for it assumes that the hosts could be incorrectly configured, which is something we may not want to hide by skipping the tests.

**Comment by msau42** [comment]
I am fine with requiring it for GCI and debian images, but I don't think we should require it for all environments (conformance).  Perhaps we should just skip the NFS tests for the local environment.  Not sure if anyone is developing and testing NFS locally.

**Comment by dims** [comment]
@copejon : it's running on the OpenStack CI system. I may have gotten past the problem with some iptables rules, if i see it again, will holler. Thanks.

**Comment by copejon** [comment]
@dims Sounds good, thanks!

**Comment by jeffvance** [comment]
@msau42 Jon and I discussed this a bit and are thinking:  it seems reasonable that a person deploying local *and* running e2e volume tests *and* seeing an error about the nfs-server pod not being created or nfs-client pods not mounting would either not run that test or would setup nfs locally. Are we missing something here? Thanks.

**Comment by msau42** [comment]
Yes, I think the main concern here is that you may not be explicitly running volume tests.  In this case, it looks like it's just a CI system that is running all tests.  So I guess it's mostly a question to @dims.  Do you want NFS to be included as part of OpenStack CI?  At least for GCE CI, we definitely want NFS tests in.

I think there's a broader issue how to structure the volume tests to be able to handle the varying environments and managing that test matrix.  But maybe in the short term, we should just skip the NFS tests except for GCE, GKE, and any other provider that wants to support it.
