### ISSUE TITLE
Separate packages for kubelet and kubectl

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#45178]
**FEATURE REQUEST**  
 
As a kubernetes developer, I'd like it if the kubelet functionality  was separated into different packages, so as not to create large dependency debt if it is imported externally.

Overall there are roughly 10x more top level go files found in these classes then in the other typical top level packages in kuberentes... details below.

*** DETAILS *** 
Several utilities are not importable without importing the entire `pkg/kubelet`, this makes it hard to externalize constants. 

```
➜  kubernetes git:(explicit_heartbeat) ✗ ls pkg/kubelet  | grep go  | wc -l
      34
```

This is quite large, compared with other top level packages, these two are pretty big:
```
kubectl      55 top level go files
kubelet 34 top level go files
```

Fortunately, the rest of the packages are much more modularized, out of the 30 top level packages, the average # of top level files is around 6 or so...  with the max # being 16 .  So, kubectl and kubelet are really the only folders that desperately need package triagings.

**Environment**

master

**Comment by jayunit100** [comment]
@kubernetes/sig-node-feature-requests @kubernetes/sig-cli-feature-requests

**Comment by yujuhong** [comment]
Last time @pmorie split `kubelet.go` into multiple `kubelet_*.go` files, as the first step to a more modular kubelet. I don't think anyone has picked up the work after that.

**Comment by pwittrock** [comment]
@jayunit100 

Is this something you are looking to pickup?

**Comment by jayunit100** [comment]
Sure ill grab it.

**Comment by jayunit100** [comment]
For completion 

- [ ] kubelet: cleanup `policies` related to heartbeat/policy packages into a subpackage ( #45303 ).
- [ ] kubelet: clean up other top level files in respective packages. (1 or 2 PRs)
- [ ] kubeCTL: clean up all the imports (1 or 2 PRs)

**Comment by adohe** [comment]
I would like to help with kubectl related clean up. Also this should be part of job that we need to finish when we decouple kubectl from the core repo [https://github.com/kubernetes/community/pull/598](https://github.com/kubernetes/community/pull/598)

**Comment by jayunit100** [comment]
Thanks @adohe.  @sjug is going to handle the kubelet part.  maybe you can handle the kubectl part, and then this issue will be covered.
