### ISSUE TITLE
Allow kubelet to set HTTP Keep-Alive client header for apiserver connections

### ISSUE THREAD

**Issue by jfoy** [kubernetes/kubernetes#45174]
**Is this a request for help?**: No
**What keywords did you search in Kubernetes issues before filing this one?**: keep-alive kubelet

---
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request for bug work-around :-)

See #41916 for background on the bug behavior; also #43516 and kubernetes-incubator/kube-aws#598 . In a nutshell:
- kubelets frequently access the apiserver via an AWS ELB load balancer
- ELB IP addresses change over time; only the DNS address is guaranteed stable with a 60s TTL
- Once removed from DNS, ELB IPs continue to serve traffic for up to 7 days before they are terminated
- kubelets appear to maintain persistent connections to retired ELB IP addresses long after they are removed from DNS
- When the retired ELB interface is finally terminated, the kubelet maintains the apiserver connection in a half-closed state up to a 900s timeout, causing all affected nodes to transition to NodeNotReady (see #45126 for one consequence).

---
kubelet config options to set its client HTTP Keep-Alive header would give cluster admins a cleaner mechanism to allow connections to migrate across this kind of scaling event. To set `Keep-Alive: timeout=60, max=100` this might look like `--apiserver-http-max-requests=100 --apiserver-http-timeout=60`.

**Comment by jsravn** [comment]
This header only applies to http/1.0, kubelet uses http/1.1. It really just needs to ping the apiserver periodically to ensure the watch is still active.

**Comment by jfoy** [comment]
Oh, that didn't match my understanding of the header under http/1.1 based on https://tools.ietf.org/html/rfc2068#section-19.7.1.1 . If I understand correctly, there isn't a watch involved here at all, but the kubelet's channel to send updates to the apiserver -- which is exactly what failed here. Am I missing something?

**Comment by jsravn** [comment]
@jfoy that section looks like it's talking about backwards compatibility w/ http/1.0.

In the original issue w/ NodeNotReady, you're right kubelet should be sending updates. For whatever reason kubelet didn't detect that that receiving end was down. I swapped out the ELB for DNS, which seems to have fixed NodeNotReady for me, but now I'm getting stale updates.

**Comment by kargakis** [comment]
@kubernetes/sig-node-feature-requests @kubernetes/sig-api-machinery-feature-requests

**Comment by mbohlool** [comment]
@jfoy do you have a code or test that we can confirm the proposed fix will be good.
