### ISSUE TITLE
k8s.io/kubernetes/pkg/kubectl/cmd/util/openapi TestOpenapi 0.00s

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#45170]
k8s.io/kubernetes/pkg/kubectl/cmd/util/openapi TestOpenapi 0.00s

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45167/pull-kubernetes-unit/28488/

What's weird is that it appear to be passing near as I can tell: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/45167/pull-kubernetes-unit/28488/artifacts/junit_a9308e5199d66c4eb1553a4ec233c5882b1bfb35_20170501-081912.stdout

**Comment by spxtr** [comment]
[raw xml isn't helpful](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/45167/pull-kubernetes-unit/28488/artifacts/junit_a9308e5199d66c4eb1553a4ec233c5882b1bfb35_20170501-081912.xml)
```xml
<testsuite tests="1" failures="1" time="26.700" name="k8s.io/kubernetes/pkg/kubectl/cmd/util/openapi">
    <properties>
        <property name="go.version" value="go1.8.1"/>
    </properties>
    <testcase classname="openapi" name="TestOpenapi" time="0.000">
        <failure message="Failed" type=""/>
    </testcase>
</testsuite>
```

**Comment by mbohlool** [comment]
Is this still failing or it was a one time failure?

**Comment by deads2k** [comment]
> @deads2k Is this still failing or it was a one time failure?

I haven't looked lately.
