### ISSUE TITLE
Should be able to restrict federation to specific namespaces

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#45189]
Came up while discussing with @marun that federation controllers assume that they have access to all namespaces and watch resources on all namespaces ([example](https://github.com/kubernetes/kubernetes/blob/0df02517254bc59d26086bd350a5e457e1961933/federation/pkg/federation-controller/deployment/deploymentcontroller.go#L131))

It should be possible to restrict federation to only specific namespaces.

One way to do this would be to update the controllers to first list all namespaces in federation control plane and then watch resources in those namespaces. Open to other suggestions.

cc @kubernetes/sig-federation-misc @marun

**Comment by csbell** [comment]
Are we forced to go down a pessimistic route here? IOW, if we say that federation can only watch *some* namespaces, will we ever be able to use NamespacesAll?

**Comment by ericchiang** [comment]
> IOW, if we say that federation can only watch some namespaces, will we ever be able to use NamespacesAll?

I think it's important that federation doesn't assume it has full access to the underlying clusters. Particularly for things like the secrets controller, I don't want to have to give the federated control plane the ability to dump all the secrets in all my clusters to use federation.

**Comment by marun** [comment]
Is it necessary to restrict federation to only specific namespaces?  Or can a list/watch for a given type return only resources that a user has permission for?  For example, if a federation service account has access to namespace 'foo' on member clusters, but not 'bar', would a list/watch of secrets need to be restricted to namespace 'foo' to avoid a permission error or would it automatically return only resources from namespace 'foo'?

**Comment by liggitt** [comment]
> can a list/watch for a given type return only resources that a user has permission for?

Implicit ACL-filtered watch is not supported today, and is not likely to be added.

> For example, if a federation service account has access to namespace 'foo' on member clusters, but not 'bar', would a list/watch of secrets need to be restricted to namespace 'foo' to avoid a permission error or would it automatically return only resources from namespace 'foo'?

It would need to be restricted to namespace foo

**Comment by luxas** [comment]
cc @luxas @timothysc @jbeda

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#212.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
