### ISSUE TITLE
Adding a scheduler extender requires duplicating the full scheduler policy config

### ISSUE THREAD

**Issue by jkinkead** [kubernetes/kubernetes#45188]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No, although I might be misreading some code.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
scheduler extender

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature request.

From what I can tell by reading [the initialization code](https://github.com/kubernetes/kubernetes/blob/1c315c64bacb18f4748ba718026b431a67a31cbe/plugin/pkg/scheduler/factory/factory.go#L309-L342), a scheduler with a policy configuration specified must fully-specify *all* predicates and priority functions that the scheduler should run with.

It would be vastly more convenient if the policy configuration could specify an existing algorithm (e.g. `DefaultProvider`) instead of the full policy behavior.

If fully-extending this feature, it would also be nice to be able to extend existing algorithms, perhaps by listing predicates & priority functions to add or remove.

**Comment by kargakis** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by resouer** [comment]
@jkinkead Yes, the current design is you need to specify all predicates/priorities you need.

Personally I think it's reasonable, though not urgent.

@wojtek-t WDYT? (Note it's also a compatibility breaking feature request).

**Comment by davidopp** [comment]
Agree it's reasonable not urgent and we need to think about how to do it in a backward-compatible way.

**Comment by quinton-hoole** [comment]
FYI, there are some parallel discussions happening around potentially using a policy language to define and implement policy-based scheduling.  That might result in an alternative and perhaps more general solution to this problem.  cc @tsandall who might want to comment further.

**Comment by ravigadde** [comment]
@jkinkead The extender config does not specify predicates/priorities, it does require a custom scheduler policy to be defined. So yes its an artifact of that.

https://github.com/kubernetes/kubernetes/blob/master/examples/scheduler-policy-config-with-extender.json

**Comment by bsalamat** [comment]
This issue is addressed by [this recent PR](https://github.com/kubernetes/kubernetes/pull/59363).
