### ISSUE TITLE
Support federation specific fields in API

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#45193]
This has come up many times.

Some options we have discussed:
* federation should define its own API rather than using kubernetes's API
* Try to generalize the federation fields so that they make sense to be added to kubernetes API
* Add an extension object that can be binded to a kubernetes object. The extension object will contain federation specific fields.

cc @kubernetes/sig-federation-feature-requests

**Comment by nikhiljindal** [comment]
@perotinus is going to update his doc with more details: https://docs.google.com/document/d/1s0Tb3rtK0UTG7aMtA4jDus_8DV4B0KkGCSITL2vQunA

**Comment by quinton-hoole** [comment]
Interesting.  I was completely unaware of this doc.  There is a parallel one being worked on here:

[Kubernetes Multi-cluster Spec and Status Use Cases and Potential API Approaches](https://docs.google.com/document/d/1gIiLpr4aHPHAAto3p1eQQ3Z6FJ8-i2kMnla4BfNa-z8/edit#heading=h.ce4mz1hiyhph).

Based on a cursory read they seem to be heading in approximately the same direction.  I'll try to unite them.

cc @marun @derekwaynecarr @pmorie

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#134.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
