### ISSUE TITLE
multizone suites are failing to start clusters

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#45198]
Failure cluster: https://storage.googleapis.com/k8s-gubernator/triage/index.html#ea6679417165f10786e6
Example run: 
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-multizone/6060#teardown-previous
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-ha-master/5666#teardown-previous

/assign @madhusudancs

**Comment by madhusudancs** [comment]
/assign @justinsb 

@justinsb could you please take a look? GCE multizone teardown is failing. You are the resident expert ;-)

**Comment by fejta** [comment]
This is part of https://github.com/kubernetes/kubernetes/issues/45198

**Comment by fejta** [comment]
Ping! Can we close this one?

**Comment by fejta** [comment]
If you aren't working on this... will you please `/unassign` yourself?
If you are working on this... will you post an update?

**Comment by madhusudancs** [comment]
I am not working on it, but I will keep myself assigned until I draw @justinsb's attention.

**Comment by justinsb** [comment]
So there's a root problem here:  kube-up should be in maintenance mode, yet it is still being changed.

Then there are a few problems:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-ha-master/5821

The cluster comes up; it can reach the pods, but then:
```
W0509 03:30:00.479] 2017/05/09 03:30:00 util.go:131: Step './hack/e2e-internal/e2e-up.sh' finished in 4m59.397924222s
W0509 03:30:00.480] 2017/05/09 03:30:00 util.go:198: Running: ./cluster/kubectl.sh --match-server-version=false get nodes -oyaml
W0509 03:30:10.687] Unable to connect to the server: net/http: TLS handshake timeout
W0509 03:30:10.689] 2017/05/09 03:30:10 util.go:200: Step './cluster/kubectl.sh --match-server-version=false get nodes -oyaml' finished in 10.267517578s
```

That suggests not all the masters are up (yet).  Do we have a health check on the API load balancer in GCE?

5820 looked like the same thing.

I have no idea what happened here: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-ha-master/5819/build-log.txt  I would guess a race with a cleanup process?  It did look like it ran _immediately_ after 5818 - perhaps it saw its own shadow.  i.e. the teardown was not fully complete.

The 5819 / 5818 pattern seems to be the case for 5818, 5817, 5816, 5815, 5814, 5813, 5812, 5811, 5810, 5809, 5808, 5807, 5806, 5805, 5804, 5803, 5802, 5801, 5800

My understanding of the problem there is that:

- It sees the project `gcloud compute --project=kubernetes-ha-master project-info describe` (?)
- It decides to run `e2e-down.sh`
- The cluster is not up, so kube-down fails.  It's trying to connect to `localhost:8080` anyway, so it might be that the cluster is just not configured.
- I hypothesize that the `kubernetes-ha-master` project is not deleted, and the cycle continues.


Given this, I think the correct course of action is to continue moving past kube-up.  Can I get some help getting GCE running with kops multizone?
