### ISSUE TITLE
cmd/integration tests should produce junit results

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#45196]
/assign @pwittrock @mengqiy 
@kubernetes/sig-cli-misc 

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5306?log#log
artifacts link shows that the `make test-cmd` command does not produce junit results: http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-test-go/5306/artifacts/

This prevents us from displaying on testgrid what is happening: https://k8s-testgrid.appspot.com/google-unit#test-go

**Comment by mengqiy** [comment]
Paste some links from @foxish that may be helpful:
https://github.com/kubernetes/test-infra/issues/1887#issuecomment-280186471
https://github.com/kubernetes/charts/blob/f8102d476d18d520ed0be599d0b6fd3f1b603481/test/helm-test/main.go#L33-L87

I will revisit this later this quarter.

**Comment by mengqiy** [comment]
@fejta Why the junit output in https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.6-master-cvm-kubectl-skew/5288/artifacts/junit_03.xml is not picked up by https://k8s-testgrid.appspot.com/sig-cli#gce-1.6-master-cvm-kubectl-skew? 
I'm expecting something similar to https://k8s-testgrid.appspot.com/sig-cli#gce-1.6

**Comment by fejta** [comment]
Look at the testgrid config for that job. What is the filter regex? Which row do you expect it to match?

**Comment by mengqiy** [comment]
NVM. Figured it out with the help of @krzyzacy.

**Comment by mengqiy** [comment]
I need to make the cmd-test, which is completely shell script, generate junit result. Do we have a handy tool to wrap shell script test cases and generate xml?

**Comment by krzyzacy** [comment]
@ixdy the bash master might have some fancy tools :-)

**Comment by ixdy** [comment]
We used to use [shell2junit](https://github.com/manolo/shell2junit) ([forked in our tree](https://github.com/kubernetes/kubernetes/tree/master/third_party/forked/shell2junit)) with e2e-runner.sh before we converted it into Go.

An old example from when we used it is here: https://github.com/kubernetes/test-infra/blob/b72c1687c3b71a44bf9953447670fb566ed53f5e/jenkins/e2e-image/e2e-runner.sh#L58-L82

**Comment by ixdy** [comment]
Updating the helpers in `hack/lib/test.sh` to use shell2junit will probably get us a long way there. FYI CI sets the environment variable `KUBE_JUNIT_REPORT_DIR` to a directory where tests can save junit files for the gotest-based unit/integration tests, so we could probably use something similar here.
