### ISSUE TITLE
patch tests shouldn't depend on client-go/pkg/api

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#45209]
This [test file](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest_test.go) tests if apiserver handles strategicMergePatch correctly. It uses client-go/pkg/api.Scheme as converter, defaulter etc, and it assumes the client-go/pkg/api.Scheme knows the internal types, which is true for now, but in fact, client-go shouldn't import the internal types and the entire client-go/pkg/api package will be removed soon.

This test should use kubernetes/pkg/api.Scheme, which is used in production. However, using kubernetes/pkg/api.Scheme creates circular dependency so it's not an option either.

@deads2k @sttts @liggitt do you have a suggestion on how to remove the dependency?

**Comment by deads2k** [comment]
You could create your own local scheme.

**Comment by sttts** [comment]
@deads2k compare the linked PR, not green yet, but implements that.

**Comment by deads2k** [comment]
> @deads2k compare the linked PR, not green yet, but implements that.

Ah, great minds :)
