### ISSUE TITLE
StatefulSet tests need to be updated for 1.6 annotations

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#45202]
e.g. https://github.com/kubernetes/kubernetes/blob/master/test/e2e/testing-manifests/statefulset/zookeeper/statefulset.yaml#L13

As @kow3ns pointed out here https://github.com/kubernetes/kubernetes/pull/41180#discussion_r114213102: 
> If you are targeting >= 1.6 you should be using the fields instead of the annotations.

**Comment by kargakis** [comment]
@kubernetes/sig-apps-misc

**Comment by enisoc** [comment]
This appears to have been duped by #45405 and fixed by #45447.
