### ISSUE TITLE
no need to close eventCh channel in threshold_notifier_linux.go

### ISSUE THREAD

**Issue by yaxinlx** [kubernetes/kubernetes#45215]
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/threshold_notifier_linux.go#L114

close it may make kubelet crash, though the possibility is small.
keep it open is just ok.
And to avoid getThresholdEvents blocked for ever, stopCh should be passed in it.

```golang
func getThresholdEvents(eventfd int, eventCh chan<- int, stopCh <-chan struct{}) {
	for {
		buf := make([]byte, 8)
		_, err := syscall.Read(eventfd, buf)
		if err != nil {
			return
		}
		
		select {
		case eventCh <- 0:
		case <-stopCh:
			return
		}
	}
}
```

**Comment by erictune** [comment]
@kubernetes/sig-node-bugs

**Comment by erictune** [comment]
Thanks for the PR!
