### ISSUE TITLE
metrics API shouldn't depend on client-go/pkg/api

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#45210]
client-go/pkg/api will be removed in a coming refactor. Internal types (i.e, pkg/api/types.go) will only exist in k8s.io/kubernetes.

However, the [internal metrics API](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/metrics/pkg/apis) depends on api.ResourceList and api.ObjectReference. @DirectXMan12 why does the metrics API need an internal version? Can we just remove the internal version? If not, can we copy the definition of api.ResourceList and api.ObjectReference to k8s.io/metrics?

**Comment by DirectXMan12** [comment]
I figured the internal metrics API should use an internal version of other API objects.  Is that not the case?  What's the recommended pattern for cross-API-group usage, if any?

**Comment by caesarxuchao** [comment]
It is. But does the metrics API need an internal version?

**Comment by arthur0** [comment]
Can I work on this?

**Comment by caesarxuchao** [comment]
I think the "where shoudl internal types should live" question is not specific to metrics.

Only external types should be vendored. If a vendoring repo needs to use the internal types, it should define its own copy that suits its needs. For example, apiserver and kubectl should have different copies of the internal types. 

I submitted PRs that's going to make code generation tools work in case internal types and external types are in different location, so the code-gen won't be a blocker.

**Comment by DirectXMan12** [comment]
(P.S. feel free to assign this to me if you want)

**Comment by caesarxuchao** [comment]
@DirectXMan12 https://github.com/kubernetes/kubernetes/issues/44065 is depending on it. I might just remove the internal types of metrics and send a PR to you. Let me know if you have other ideas :)

**Comment by caesarxuchao** [comment]
Sent #45306

**Comment by DirectXMan12** [comment]
I'd much rather copy some of the used types in instead, instead of just removing the internal metrics types.  `k8s.io/metrics` is intended to be consumed by both clients and API servers, so we can't just remove the ability to do conversions.

**Comment by caesarxuchao** [comment]
Closed by https://github.com/kubernetes/kubernetes/pull/45384
