### ISSUE TITLE
kubectl set image --local is not really local

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#45223]
```
kubectl set image --local -f busybox.yaml busybox=busybox:1.26 -o yaml
error: unable to connect to a server to handle "deployments": Get https://127.0.0.1:8443/api: dial tcp 127.0.0.1:8443: getsockopt: connection refused
```
It tries to contact the api server for the discovery docs and fails because no api server is running. Could `kubectl` first look in its local cache if it's passed --local?

@kubernetes/sig-cli-bugs

**Comment by adohe** [comment]
I think `local` here has similar meaning as `dry-run`, it will not contact api-server to do real patch, but it will fetch the resource from api-server. What you mean look in it's local cache? to find the resource in local cache? I think you have specified the resource in your command line.

**Comment by suyogbarve** [comment]
@adohe Use of --local flag should completely eliminate communication with api-server
I have sent a PR https://github.com/kubernetes/kubernetes/pull/45285 which should fix this issue
