### ISSUE TITLE
Scheduler schedules pod to node which has not enough resources

### ISSUE THREAD

**Issue by shenlanse** [kubernetes/kubernetes#45220]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):    
maybe a bug or a point we can improve

---

**Kubernetes version** (use `kubectl version`):    
k8s1.3.5. I think it still exist in 1.6

---

**What happened**:    
when **restart** kube-scheduler component, kube-scheduler schedules pod to node which has not enough resources. So this pod is set Falied **by kubelet**.

---

**What you expected to happen**:    
we don't want to schedule pod to node which has not enough resources, and i think we had better deal with this question in kube-scheduler instead of in kubelet(**Predicate Again**).

---

**How to reproduce it** (as minimally and precisely as possible):  

Firstly, restart kube-scheduler.    

A Pod that needs scheduling. Newly created or Created before scheduler shutdown.  

And scheduledPod cache **has not been completely synced**. So some nodes may be thought has enough resources. (if scheduledPod cache is synced completely, these nodes may have not enough resources for new pod)    

Now schduler is scheduling this pod. Scheduler may schedule pod to nodes which have not enough resources. However scheduler thinks target node has enough resources.

When corresponding kubelet watchs this schedule event, it re-runs Predicate Func and finds that this node doesn't have enough resources.

---

**Anything else we need to know**:

I think we shoud **add HasSynced func** for ScheduledPod cache in kube-scheduler. Until ScheduledPod cache syncs completely, start the work of scheduling pod.

**Comment by shenlanse** [comment]
@timothysc @brendandburns

**Comment by k82cn** [comment]
@kubernetes/sig-scheduling-misc 

Used to meeting similar issue; not sure why we did not have sync when scheduler start up.

**Comment by erictune** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by timothysc** [comment]
> I think it still exist in 1.6 

@shenlanse did you verify?

**Comment by shenlanse** [comment]
Honestly, i didn't reproduce the bug in 1.6. But I have read the code of 1.6, think this problem still exists in logic.

**Comment by wanghaoran1988** [comment]
I see that we start a gorutine of the scheduledPodPopulator `go f.scheduledPodPopulator.Run(f.StopEverything)`, but we never wait the queue sysc, maybe we need wait  until `f.scheduledPodPopulator.HasSynced()` return true ?
here is the code:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L455

**Comment by davidopp** [comment]
@wojtek-t @bsalamat
