### ISSUE TITLE
container.resources.{limits,requests} fields are not documented in the API/explain

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes#45249]
**Kubernetes version**: v1.6.2

**What happened**: The fields of `container.resources.limits` and c `container.resources.requests` are not documented in `kubectl explain` output or the API Reference documentation.

https://kubernetes.io/docs/api-reference/v1.6/#resourcerequirements-v1-core As it can be seen here. The `limits` and `requests` are rendered as untyped _object_ and they do not have any fields defined:

> ![image](https://cloud.githubusercontent.com/assets/159209/25642379/3f1be752-2f4e-11e7-86a8-c268bb9398d8.png)

**What you expected to happen**: Expected to see types for these resource requirement specifications that have things like `cpu`, `memory` as fields.

**How to reproduce it** (as minimally and precisely as possible):

```
$ kubectl explain pods.spec.containers.resources.limits
FIELD: limits <object>

DESCRIPTION:
     Limits describes the maximum amount of compute resources allowed. More
     info: http://kubernetes.io/docs/user-guide/compute-resources/
```

Gives same output for 
- `kubectl explain pods.spec.containers.resources.cpu` or
- `kubectl explain pods.spec.containers.resources.limits.asdfadsfadsads`

**Comment by xiangpengzhao** [comment]
It might be because [Limits and Requests](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1484) are [ResourceList](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L2972) type. ResourceList is a map `type ResourceList map[ResourceName]resource.Quantity`. I think generator cannot resolve it.

**Comment by ahmetb** [comment]
@xiangpengzhao I understand now. Thanks.

If someone else can verify this is indeed the case (or point to another example that `object` is the resolved type for all maps) we can just close this.

However if there’s anything we can do to make it better, we should probably do it. At this point I am not sure why this is a map instead of a typed struct. If you know anyone who might have context on resource request API, feel free to cc them.

**Comment by xiangpengzhao** [comment]
@smarterclayton or @vishh might give a more reasonable explanation.

**Comment by vishh** [comment]
A `map` was adequate at the beginning of the project (pre 1.0). Given that the current API will stay as-is for quite some time, identifying a means to handle `map` fields will be useful.

**Comment by erictune** [comment]
@mbohlool  could we generate docs for "well known keys" of a map that is acting like a struct, please?

**Comment by smarterclayton** [comment]
We can just document the supported fields on the Godoc of Limits field?

**Comment by ahmetb** [comment]
Just in `pkg/api/types.go`, there are 15 fields of type `ResourceList` (=`map[ResourceName]resource.Quantity`). The ones I described above (ResourceRequirements.{Limits,Requests}) are only 2 of them.

Which of the following routes is more preferable?

1. document what fields are accepted to all 15 fields (and possibly to all usages of ResourceList type fields in other types.go files)
2. document what fields are accepted  only on `type ResourceRequirements` where the container Limits/Requests are specified (that's probably where most users see this vague _object_ type)

**Comment by mbohlool** [comment]
> @mbohlool could we generate docs for "well known keys" of a map that is acting like a struct, please?

The docs generated from OpenAPI spec. The openAPI spec indicated that:

```json
"io.k8s.api.core.v1.LimitRangeSpec": {
    "description": "LimitRangeSpec defines a min/max usage limit for resources that match on kind.",
    "required": [
     "limits"
    ],
    "properties": {
     "limits": {
      "description": "Limits is the list of LimitRangeItem objects that are enforced.",
      "type": "array",
      "items": {
       "$ref": "#/definitions/io.k8s.api.core.v1.LimitRangeItem"
      }
     }
    }
   },
```

and

```json
"io.k8s.apimachinery.pkg.api.resource.Quantity": {
    "type": "string"
   },
```

That means if we fix doc generator (cc @pwittrock) it would be shown as "map[string]Quantity" or "map[string]string". Is that better in any way? If we want more than that, we need special support for doc generator in OpenAPI spec (extensions?!) but that would also result in adding something before all those 15 instances so maybe just documenting the keys in all instances' comment is the way to go.
