### ISSUE TITLE
federation: flake in deleting federated service during kubectl tests

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/kubernetes#45264]
kubectl tests for federation is flaking in pre-submit tests. 

Here is one such failure. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/44987/pull-kubernetes-unit/28480/?log#log

We need to fix this with priority as pre-submit tests are affected by this issue.
After high level analysis and discussion with @nikhiljindal, it looks like identical issue which happened for secrets.

cc @nikhiljindal @kubernetes/sig-federation-bugs

**Comment by nikhiljindal** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/45265
