### ISSUE TITLE
kubectl log <pod> should use last running container

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#4526]
If container is crash looping kubectl log <pod> will return the following error:

$ kubectl log <pod>
[...]
Internal Error: container "<container>" is not ready.

This makes it very difficult to debug problematic containers/pods. Instead it should use the last running container.

**Comment by cjcullen** [comment]
A user on StackOverflow is annoyed by this as well: http://stackoverflow.com/questions/29151042/how-to-docker-attach-to-a-container-google-cloud-platform-kubernetes

**Comment by derekwaynecarr** [comment]
Related: https://github.com/GoogleCloudPlatform/kubernetes/issues/4640

**Comment by smarterclayton** [comment]
This sounds like a regression - this used to work

**Comment by smarterclayton** [comment]
Nm

**Comment by sils1297** [comment]
Are there any workarounds to get those logs in the meantime?

**Comment by smarterclayton** [comment]
--previous

In general, I'm not sure being told the pod is not ready is useful.  I think the default client behavior should be changed to always show the most recent logs available, even if from the API we preserve backwards compat by introducing a new flag/option to control this.

This is on my top usability hitlist - a new user to the platform is the most likely to get into a crashloop, and least likely to understand the arbitrary distinction between previous and current.  They just need to see the logs.

**Comment by smarterclayton** [comment]
I think this should be candidate for 1.2 because it is in the critical path of every user who has a failing pod (which is almost always insufficient config, or something directly user addressable).

**Comment by smarterclayton** [comment]
Fixing this.
