### ISSUE TITLE
Etcd error messages such as "unexpected end of JSON input" are not helpful

### ISSUE THREAD

**Issue by stefwalter** [kubernetes/kubernetes#4527]
When performing a long poll watch request for changes, and no changes are listed before the request times out ... I get the following error:

```
$ curl 'http://localhost:8080/api/v1beta3/watch/services?resourceVersion=4444444'
{"type":"ERROR","object":{"kind":"Status","apiVersion":"v1beta3","metadata":{"selfLink":"/api/v1beta3/services"},"status":"Failure","message":"unexpected end of JSON input"}}
```

**Comment by stefwalter** [comment]
This is with v0.10.0

**Comment by stefwalter** [comment]
Note this takes 5 minutes (the long poll timeout) before the error appears (and curl exits). The long timeout is not unexpected.

**Comment by doublerr** [comment]
Is this the standard etcd watch timeout?

**Comment by stefwalter** [comment]
Yes, both etcd and kube-apiserver have a watch timeout. However I don't think it's correct to return an "ERROR" with "unexpected end of JSON input" when that happens.

**Comment by bgrant0607** [comment]
The message is from etcd. It's only legal to pass a previously returned resourceVersion. Do a GET on /services, and use the resourceVersion returned in a subsequent watch.

**Comment by lavalamp** [comment]
Is "4444444" just something random you typed in? If so, do what Brian says.

... But it's still weird that it failed only after five minutes.

**Comment by bgrant0607** [comment]
We shouldn't pass such unhelpful etcd error messages directly back to the user. We should provide our own error messages that make sense in the context of the attempted operation.

**Comment by stefwalter** [comment]
> We shouldn't pass such unhelpful etcd error messages directly back to the user

Makes sense.

@lavalamp For what it's worth, even when using a valid resourceVersion, I still get this message:

```
$ V=$(curl -s 'http://localhost:8080/api/v1beta3/services' | grep resourceVersion | tr -c -d '0-9\n' | sort -nr | head -n 1)
$ curl "http://localhost:8080/api/v1beta3/watch/services?resourceVersion=$V"
{"type":"ERROR","object":{"kind":"Status","apiVersion":"v1beta3","metadata":{"selfLink":"/api/v1beta3/services"},"status":"Failure","message":"unexpected end of JSON input"}}
```

**Comment by bgrant0607** [comment]
@nikhiljindal Will this fixed be fixed by your PR?

**Comment by bgrant0607** [comment]
@krousey Looks like another timeout issue. Watch shouldn't be subject to the 5-minute timeout, either.

**Comment by bgrant0607** [comment]
@kubernetes/sig-api-machinery Is this obsolete or still relevant?

**Comment by wojtek-t** [comment]
I think it's obsolete.

**Comment by smarterclayton** [comment]
I have not seen this in a long time.
