### ISSUE TITLE
The GeneralPLEG's parameter  plegRelistPeriod is too long in some Certain scenes ?

### ISSUE THREAD

**Issue by yan234280533** [kubernetes/kubernetes#45278]
The GeneralPLEG's parameter  plegRelistPeriod is too long in some Certain scenes. 
Now the plegRelistPeriod  is  set as 1s, is too long in some  certain scenes  such as Serverless.
Can it set much more short , like 100ms ?

**Comment by yujuhong** [comment]
> Now the plegRelistPeriod is set as 1s, is too long in some certain scenes such as Serverless.

@yan234280533 why is it too long? Could you explain your use case more so we can discuss whether this would actually help? There are many factors affecting kubelet's "responsiveness", tuning one parameter without an analysis may hinder other use cases (and very likely not achieve what you want). For example, frequent container listing (e.g., `docker ps`) calls may overwhelm the container runtime if it's already under heavy load.

**Comment by yan234280533** [comment]
@yujuhong 
In  fact, We use kubernetes to provide Serverless service. End-to-end time cost  of  deploy an  pod is about 2s. We find that as the  plegRelistPeriod  is set as 1s, it cost 800ms to report the status from kubelet to apiserver. So we try to  reedit the plegRelistPeriod   to 100ms , which can short the cost of eport the status from kubelet to apiserver to 200ms.

**Comment by erictune** [comment]
@kubernetes/sig-node-feature-requests

**Comment by resouer** [comment]
@yan234280533 as yuju said, frequently PLEG request will create heavy burden to runtime side, while status report is affected by many factors.

Another question is why 800ms -> 200ms change make a lot sense to you? It seems users should not even aware the difference (it's only 600ms).

**Comment by yan234280533** [comment]
@resouer  I know that will create  heavy burden to runtime side. But it surely sense the 600ms latency in some scenario. So can it transform to be an parameter make it  more flexible.

**Comment by resouer** [comment]
@yan234280533 Then it would be great if you can send a PR and ask sig-node to review it.

**Comment by yan234280533** [comment]
@resouer Thank you a billion,  I will  send a PR as soon as possible.
