### ISSUE TITLE
Flake of pkg/kubectl/cmd/util/openapi.TestOpenapi

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#45279]
TestOpenapi failed frequently in recently CI runs, e.g. [here](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41766/pull-kubernetes-unit/28845/#k8siokubernetespkgkubectlcmdutilopenapi-testopenapi)

```
k8s.io/kubernetes/pkg/kubectl/cmd/util/openapi TestOpenapi 0.00s
go test -v k8s.io/kubernetes/pkg/kubectl/cmd/util/openapi -run TestOpenapi$
```

cc/ @pwittrock @kubernetes/sig-cli-bugs

**Comment by jwforres** [comment]
Also seen in https://github.com/kubernetes/kubernetes/pull/45305 

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45305/pull-kubernetes-unit/28905/?log#k8siokubernetespkgkubectlcmdutilopenapi-testopenapi

**Comment by yujuhong** [comment]
I ran into this twice with my PR

**Comment by pwittrock** [comment]
Maybe this is a bug in the test infrastructure?

> I0503 13:25:54.182] ok  	k8s.io/kubernetes/pkg/kubectl/cmd/util/openapi	27.720s

**Comment by pwittrock** [comment]
This [one](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/45305/pull-kubernetes-unit/28905/build-log.txt) too

> I0503 03:34:24.458] ok  	k8s.io/kubernetes/pkg/kubectl/cmd/util/openapi	25.932s

**Comment by pwittrock** [comment]
Looks like the test is hitting [this](https://github.com/jstemmer/go-junit-report/issues/31)

The openapi test isn't failing, some other test is failing, but it missreports.

**Comment by pwittrock** [comment]
Example:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/5375?log#log

**Comment by pwittrock** [comment]
@jwforres 

FYI:

```sh
I0503 13:42:34.713] test-cmd-util.sh:2066: FAIL!
I0503 13:42:34.713] Get services {{range.items}}{{.metadata.name}}:{{end}}
I0503 13:42:34.713]   Expected: kubernetes:
I0503 13:42:34.714]   Got:      kubernetes:service-v1-test:
I0503 13:42:34.714] (B
I0503 13:42:34.714] 51 /go/src/k8s.io/kubernetes/hack/lib/test.sh
I0503 13:42:34.714] (B
I0503 13:42:34.735] +++ [0503 13:42:34] Clean up complete
I0503 13:42:34.736] Makefile:268: recipe for target 'test-cmd' failed
W0503 13:42:34.837] !!! [0503 13:42:34] Call tree:
W0503 13:42:34.837] !!! [0503 13:42:34]  1: /go/src/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh:2066 kube::test::get_object_assert(...)
W0503 13:42:34.837] !!! [0503 13:42:34]  2: /go/src/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh:3304 run_service_tests(...)
W0503 13:42:34.837] !!! [0503 13:42:34]  3: hack/make-rules/test-federation-cmd.sh:98 runTests(...)
W0503 13:42:34.837] make: *** [test-cmd] Error 1
W0503 13:42:35.900] Traceback (most recent call l
```

**Comment by pwittrock** [comment]
Re opening this just to fix the missreporting
