### ISSUE TITLE
Use kubemark to test k8s performance but get: !!! Error in ./hack/ginkgo-e2e.sh:117

### ISSUE THREAD

**Issue by xiechengsheng** [kubernetes/kubernetes#45288]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
yes

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
Keywords: kubemark, Error in ./hack/ginkgo-e2e.sh:117

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-dirty", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"dirty", BuildDate:"2017-05-02T14:51:27Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-dirty", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"dirty", BuildDate:"2017-05-02T14:51:27Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**: 1 linux/amd64 master(VM)
- **Cloud provider or hardware configuration**: memory: 4GB, CPU: 4 cores, disk: 40GB
- **OS** (e.g. from /etc/os-release): CentOS 7.2
- **Kernel** (e.g. `uname -a`): 3.10.0
- **Install tools**: install the K8S by building the source codes

**What happened**:
I want to use kubemark to test k8s scheduler's performance, but when I used the command:
```
go run hack/e2e.go -v -test  --test_args="--host=http://${master_ip}:8080 --ginkgo.focus=\[Feature:Performance\]" >>log.txt
```
there was an error... Here is the message: 
```
2017/05/03 19:30:49 e2e.go:76: Calling kubetest -v -test --test_args=--host=http://192.168.3.89:8080 --ginkgo.focus=\[Feature:Performance\]...
2017/05/03 19:30:49 util.go:129: Running: ./cluster/kubectl.sh version --match-server-version=false
2017/05/03 19:30:49 util.go:131: Step './cluster/kubectl.sh version --match-server-version=false' finished in 169.142999ms
2017/05/03 19:30:49 util.go:129: Running: ./hack/e2e-internal/e2e-status.sh
Local doesn't need special preparations for e2e tests
2017/05/03 19:30:49 util.go:131: Step './hack/e2e-internal/e2e-status.sh' finished in 171.348895ms
2017/05/03 19:30:49 util.go:129: Running: ./hack/ginkgo-e2e.sh --host=http://192.168.3.89:8080 --ginkgo.focus=\[Feature:Performance\]
Local doesn't need special preparations for e2e tests
!!! Error in ./hack/ginkgo-e2e.sh:117
  Error in ./hack/ginkgo-e2e.sh:117. '"${ginkgo}" "${ginkgo_args[@]:+${ginkgo_args[@]}}" "${e2e_test}" -- "${auth_config[@]:+${auth_config[@]}}" --ginkgo.flakeAttempts="${FLAKE_ATTEMPTS}" --host="${KUBE_MASTER_URL}" --provider="${KUBERNETES_PROVIDER}" --gce-project="${PROJECT:-}" --gce-zone="${ZONE:-}" --gke-cluster="${CLUSTER_NAME:-}" --kube-master="${KUBE_MASTER:-}" --cluster-tag="${CLUSTER_ID:-}" --repo-root="${KUBE_ROOT}" --node-instance-group="${NODE_INSTANCE_GROUP:-}" --prefix="${KUBE_GCE_INSTANCE_PREFIX:-e2e}" --network="${KUBE_GCE_NETWORK:-${KUBE_GKE_NETWORK:-e2e}}" --federated-kube-context="${FEDERATION_KUBE_CONTEXT:-e2e-federation}" ${KUBE_CONTAINER_RUNTIME:+"--container-runtime=${KUBE_CONTAINER_RUNTIME}"} ${MASTER_OS_DISTRIBUTION:+"--master-os-distro=${MASTER_OS_DISTRIBUTION}"} ${NODE_OS_DISTRIBUTION:+"--node-os-distro=${NODE_OS_DISTRIBUTION}"} ${NUM_NODES:+"--num-nodes=${NUM_NODES}"} ${E2E_CLEAN_START:+"--clean-start=true"} ${E2E_MIN_STARTUP_PODS:+"--minStartupPods=${E2E_MIN_STARTUP_PODS}"} ${E2E_REPORT_DIR:+"--report-dir=${E2E_REPORT_DIR}"} ${E2E_REPORT_PREFIX:+"--report-prefix=${E2E_REPORT_PREFIX}"} "${@:-}"' exited with status 1
Call stack:
  1: ./hack/ginkgo-e2e.sh:117 main(...)
Exiting with status 1
2017/05/03 19:35:10 util.go:131: Step './hack/ginkgo-e2e.sh --host=http://192.168.3.89:8080 --ginkgo.focus=\[Feature:Performance\]' finished in 4m20.793094077s
2017/05/03 19:35:10 main.go:193: Something went wrong: encountered 1 errors: [error during ./hack/ginkgo-e2e.sh --host=http://192.168.3.89:8080 --ginkgo.focus=\[Feature:Performance\]: exit status 1]
2017/05/03 19:35:10 e2e.go:78: err: exit status 1
exit status 1
```
And here is the log file:
```
  /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:188
^[[90m------------------------------^[[0m
May  3 22:22:47.074: INFO: Running AfterSuite actions on node 1


^[[91m^[[1mSummarizing 2 Failures:^[[0m

^[[91m^[[1m[Fail] ^[[0m^[[90m[k8s.io] Load capacity ^[[0m^[[91m^[[1m[BeforeEach] [Feature:Performance] should be able to handle 30 pods per node { ReplicationController} with 0 secrets and 0 daemons ^[[0m
^[[37m/root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:188^[[0m

^[[91m^[[1m[Fail] ^[[0m^[[90m[k8s.io] Density ^[[0m^[[91m^[[1m[BeforeEach] [Feature:Performance] should allow starting 30 pods per node using { ReplicationController} with 0 secrets and 0 daemons ^[[0m
^[[37m/root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:188^[[0m

^[[1m^[[91mRan 2 of 588 Specs in 260.196 seconds^[[0m
^[[1m^[[91mFAIL!^[[0m -- ^[[32m^[[1m0 Passed^[[0m | ^[[91m^[[1m2 Failed^[[0m | ^[[33m^[[1m0 Pending^[[0m | ^[[36m^[[1m586 Skipped^[[0m --- FAIL: TestE2E (260.23s)
FAIL

Ginkgo ran 1 suite in 4m20.719641311s
Test Suite Failed
```
And the kube-apiserver's ERROR log seemed to show nothing about the error. 

**What you expected to happen**:
The kubemark works well on my machine...

**How to reproduce it** (as minimally and precisely as possible):
1. get K8S source code
2. use the commands/scripts: 
```
cd $GOPATH/src/k8s.io/kubernetes
go get -u github.com/jteeuwen/go-bindata/...
./hack/generate-bindata.sh
make WHAT='test/e2e/e2e.test'
make ginkgo
export KUBECTL_PATH=/usr/bin/kubectl
export KUBERNETES_PROVIDER=local
kubectl config view -o yaml >> /root/.kube/config
go run hack/e2e.go -v -test  --test_args="--host=http://${master_ip}:8080 --ginkgo.focus=\[Feature:Performance\]" >>log.txt
```

**Anything else we need to know**:
Is there an official document that can help us to build the kubemark environment in detail?

**Comment by wojtek-t** [comment]
I guess the problem is that we shouldn't run tests in kubemark the way you were running.
@shyamjvs - can you please take a quick look and if I'm right provide the correct commads?

**Comment by shyamjvs** [comment]
@xiechengsheng There seem to be at least 2 things wrong with the way you are running the test:
- You have set the `KUBERNETES_PROVIDER=local` which would break things inside hack/ginkgo-e2e.sh (which is called from kubetest, which is called from hack/e2e.go) that uses it for sourcing the right config files for kubemark. So it is expected to be set as `kubemark` instead. The recommended way of running e2e tests is using [test/kubemark/run-e2e-tests.sh] (https://github.com/kubernetes/kubernetes/blob/master/test/kubemark/run-e2e-tests.sh) script.
- Before running hack/e2e.go, you need to set some env vars like MASTER_NAME, MASTER_IP, etc to tell some of the downstream scripts about who/where the master is. And again run-e2e-tests.sh should take care about this for you.

However, there are a few things you might need to do (and I'm happy to help you with any issues here) to make run-e2e-tests.sh work.
- First of all, you need to set CLOUD_PROVIDER to 'local' so that [cloud-provider-config.sh](https://github.com/kubernetes/kubernetes/blob/master/test/kubemark/cloud-provider-config.sh) which is sourced by run-e2e-tests.sh, picks it up.
- You need to add 2 files `cluster/local/util.sh` and `cluster/kubemark/local/config-default.sh` as they would be tried to be sourced based on the value of CLOUD_PROVIDER inside cluster/kubemark/util.sh (ref: https://github.com/kubernetes/kubernetes/blob/master/cluster/kubemark/util.sh#L19-L20). IIRC, the first one pretty much needs to define just a function detect-master() and you can see it's example for gce [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L355). The second one needs to set the required env vars that I mentioned above.

Once you do the above, it would really be a clean way to run the e2e tests. All you need to do is:
- export the right env vars for your kubemark cluster (or just hardcode them inside `cluster/kubemark/local/config-default.sh` file)
- `./test/kubemark/run-e2e-tests.sh --ginkgo.focus=[Feature:Performance]`

**Comment by shyamjvs** [comment]
FYI, there's an ongoing PR (https://github.com/kubernetes/kubernetes/pull/44394) for this use case, of being able to run e2e tests on an on-prem kubemark cluster. It also enables creating/deleting a kubemark cluster given a pre-existing kubemark master, but you can use it for just running e2e tests.

**Comment by xiechengsheng** [comment]
@shyamjvs @erictune @wojtek-t Thanks for the replies, I'll try to run e2e tests at local~

**Comment by stormltf** [comment]
i also has this problem. @wojtek-t @shyamjvs 
after read this the kumark guide，can not run kubemark at local.
https://github.com/kubernetes/community/blob/master/contributors/devel/kubemark-guide.md

as @shyamjvs 's step, cluster/kubemark/local/config-default.sh this file what was must be set?

**Comment by stormltf** [comment]
@xiechengsheng your email or weixin or qq?

**Comment by xiechengsheng** [comment]
@stormltf 
1. According to this blog [Kubemark: Performance Test Tool for Your Kubernetes Cluster](https://supereagle.github.io/2017/03/09/kubemark/), the author solved the problem by generating cert file for apiserver and controller-manager. And I have tried this, and it took me about **an hour** to simulate the scheduling process, then the timeout error occurred, and the log showed the scheduler had successfully scheduled **just 90 pods**. It seems to be too slow...
2. My qq: 1262851591

**Comment by shyamjvs** [comment]
Hi @stormltf , I guess you are asking what are the variables that must be provided through the config-default.sh file. I don't know the exact set of the variables that need to be defined, but pretty much any variable that is for identifying the kubemark master and size of cluster (used for e2e tests). IMO shouldn't be too many such variables (maybe 5-6). To begin with, I'd say the following:
```
MASTER_IP="<ip of your master>"
MASTER_NAME="<name of your master VM (for SSH)>"
NUM_NODES="<no. of hollow nodes>"
CLUSTER_IP_RANGE="10.224.0.0/11 or some other private CIDR maybe"   (for giving IPs to pods during e2e tests)
SERVICE_CLUSTER_IP_RANGE="10.0.0.0/16" (for giving IPs to pods during e2e tests)
```

There might be more that you discover after running, and it would be great if you can comment below about them.
@xiechengsheng Could you make the e2e tests run?

**Comment by xiechengsheng** [comment]
@shyamjvs Yes, the e2e tests run well in my cluster. But when I used kubemark, a timeout error occurred.

**Comment by shyamjvs** [comment]
@xiechengsheng Could you give some more information about what exactly timed out and provide some logs?

**Comment by xiechengsheng** [comment]
The timeout error has been solved, it occurred because of my wrong config... But another error occurred, here is the log: 
```
  [91mExpected error:
      <*errors.errorString | 0xc4202e81d0>: {
          s: "too high pod startup latency 50th percentile: 5.962233306s",
      }
      too high pod startup latency 50th percentile: 5.962233306s
  not to have occurred[0m
```
It seems that the fake pod's startup latency is too high, I'll try it in the physical machine cluster.

**Comment by shyamjvs** [comment]
@xiechengsheng Did you retry running the e2e test? If you are still failing, it might be worth checking the CPU/memory usage of the kubemark pods and size of your nodes. Also it might be the network is slow between master and nodes. It'd be great if you can tell what configuration you've started your cluster with (no. of nodes and hollow-nodes, size of nodes, size of kubemark master). And you could also try checking the status/conditions on the hollow-node pods.

**Comment by xiechengsheng** [comment]
@shyamjvs Sorry for my late reply, I have solved the problem by generating cert file for apiserver and controller-manager.
