### ISSUE TITLE
bazel version stamping is somewhat broken

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#45298]
Using a client based on https://github.com/kubernetes/kubernetes/pull/45248:

```shell
$ make clean
$ bazel clean
$ make bazel-release
...
$ cluster/kube-up.sh
...
$ bazel-bin/cmd/kubectl/kubectl version
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.2.630+e231d4280ba82c", GitCommit:"e231d4280ba82ca16317a3adb019c1b48db1263f", GitTreeState:"clean", BuildDate:"2017-05-03T17:37:42Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
```

Oddly:
```shell
$ bazel-bin/cmd/kube-apiserver/kube-apiserver --version
Kubernetes v1.7.0-alpha.2.630+e231d4280ba82c
```
but also
```shell
$ strings bazel-bin/cmd/kube-apiserver/kube-apiserver | grep "not a git tree"
missing clientmissing listermsg_sent_totalmust be uniqueneed more datanil elem type!no digits readno host in URIno module datano such devicenoBuiltInTypesnot a git treenot authorizednot in ranges [...]
```

I thought this used to work at some point in the past.

/cc @spxtr @mikedanese

**Comment by ixdy** [comment]
oh, this is #40813; we need something similar to #42623 for bazel.

**Comment by ixdy** [comment]
though the go rules only support a single `linkstamp` package right now.

**Comment by ixdy** [comment]
yeah, confirmed the bad version info is coming from `vendor/k8s.io/client-go/pkg/version`.
I don't understand why the api server is using that, though. @caesarxuchao @adohe @deads2k @liggitt

**Comment by ixdy** [comment]
cc @sttts 
Is there a way to avoid having two `pkg/version/base.go`s?

**Comment by sttts** [comment]
@ixdy in the apiserver we could default to fake values and instantiate the /version endpoint with real values in kube-apiserver. But then client-go's version is still broken. Anybody else using the client-go version? Do we actually need that anywhere? /cc @caesarxuchao

**Comment by liggitt** [comment]
> Anybody else using the client-go version? Do we actually need that anywhere?

kubectl uses it for current version for user-agent, etc

**Comment by sttts** [comment]
kubectl could technically use the kube version. Anything that speaks against that?

**Comment by ixdy** [comment]
cc @thockin

**Comment by ixdy** [comment]
/assign

The bazel go rules now support stamping multiple packages, so I'm working on getting that set up.
