### ISSUE TITLE
Kubemark: ReplicationController reports "hollow-node" is invalid 

### ISSUE THREAD

**Issue by gamename** [kubernetes/kubernetes#45290]
**This a request for help *and* a bug** 

**What keywords did you search in Kubernetes issues before filing this one?** 
"hollow-node"

---

**This a BUG REPORT** (choose one):

**Kubernetes version** (use `kubectl version`):
```$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"clean", BuildDate:"2017-03-28T13:36:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
GCP

- **OS** (e.g. from /etc/os-release):
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12.4
BuildVersion:   16E195

- **Kernel** (e.g. `uname -a`):
```
Darwin tennismbp.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64 i386 MacBookPro13,3 Darwin
```
- **Install tools**:
- **Others**:

**What happened**:
- When running `test/kubemark/start-kubemark.sh`, the following error occurs:
```
<snip>
Created and uploaded the kubemark hollow-node image to docker registry.
namespace "kubemark" created
configmap "node-configmap" created
secret "kubeconfig" created
replicationcontroller "heapster-v1.3.0" created
---> The ReplicationController "hollow-node" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value
!!! [0503 10:22:38] Call tree:
!!! [0503 10:22:38]  1: test/kubemark/start-kubemark.sh:384 create-kube-hollow-node-resources(...)
!!! Error in test/kubemark/start-kubemark.sh:206
  Error in test/kubemark/start-kubemark.sh:206. '((i<3-1))' exited with status 1
Call stack:
  1: test/kubemark/start-kubemark.sh:206 create-kube-hollow-node-resources(...)
  2: test/kubemark/start-kubemark.sh:384 main(...)
Exiting with status 1
```

**What you expected to happen**:
The hollow-node(s) should have been created

**How to reproduce it** (as minimally and precisely as possible):
1 - Clone a copy of kubernetes 
2 - `make quick-release`
3 - `test/kubemark/start-kubemark.sh`

**Anything else we need to know**:

**Comment by xiangpengzhao** [comment]
See: #38542

@k82cn @smarterclayton

**Comment by xiangpengzhao** [comment]
cc @gmarek

**Comment by wojtek-t** [comment]
@shyamjvs 

Strange - we are running kubemark continuously and it is passing ...

**Comment by gamename** [comment]
I found the problem.  The cluster wasn't configured properly.  Somehow, that translated into hollow-node being invalid.

I created a new cluster and it worked.

I did `./cluster/kube-up.sh` and *then* tried `test/start-kubemark.sh`.  That worked.
