### ISSUE TITLE
kubectl should be able to base64 decode secrets

### ISSUE THREAD

**Issue by daniel-ac-martin** [kubernetes/kubernetes#45293]
Currently if one wants to view secrets stored in k8s they must follow the process described here: https://kubernetes.io/docs/concepts/configuration/secret/#decoding-a-secret

This involves copy&pasting. It seems to me that kubectl could provide a more helpful interface to base64 decrypt the users on behalf of the user saving them the trouble.

**Comment by ericchiang** [comment]
The kubelet does decode secrets before exposing them to the pod.

**Comment by grodrigues3** [comment]
/kind feature

@kubernetes/sig-cli-feature-requests

**Comment by erictune** [comment]
Yes, though this is low priority since we mostly don't want end users to view these once they get into the system.

**Comment by neverfox** [comment]
Why can't that be an API permissions issue? I mean, if I really want to see it, I can just launch a pod to tell me.

**Comment by ericchiang** [comment]
I've update the issue title with what I understand as the request. To the best of my understanding this is just a request for us to avoid the need to pipe into base64 when inspecting secrets.

**Comment by glb** [comment]
I'd like to help with this; if people have thoughts on how it should work I'd be interested to hear them.

**Comment by glb** [comment]
@daniel-ac-martin I would like to try to make this work before it rots.
cc @seans3 @mengqiy 

Any guidance on a preferred implementation?

**Comment by glb** [comment]
What do you think about adding support for [Sprig](https://github.com/Masterminds/sprig) functions in templates? This would allow someone to use the existing `TemplatePrinter` and a template that uses the `b64dec` function -- or a wide variety of other interesting functions as a side effect.

I believe (but have not yet tested) that the following might be sufficient to enable the requested behaviour (plus the change to the dependencies list, of course): 
```diff
diff --git a/pkg/printers/template.go b/pkg/printers/template.go
index c54c511a20..f1f76ea71c 100644
--- a/pkg/printers/template.go
+++ b/pkg/printers/template.go
@@ -22,6 +22,8 @@ import (
        "io"
        "text/template"
 
+       "github.com/Masterminds/sprig"
+
        "k8s.io/apimachinery/pkg/runtime"
 )
 
@@ -34,6 +36,7 @@ type TemplatePrinter struct {
 func NewTemplatePrinter(tmpl []byte) (*TemplatePrinter, error) {
        t, err := template.New("output").
                Funcs(template.FuncMap{"exists": exists}).
+               Funcs(sprig.FuncMap()).
                Parse(string(tmpl))
        if err != nil {
                return nil, err
```

**Comment by daniel-ac-martin** [comment]
Hi @glb,

I suppose my thoughts on this issue have changed a little since I wrote it. The situation isn't quite as bad as I described as it is possible to decode a secret in one go without then need to copy and paste. i.e.
```bash
kubectl get secret YOUR_SECRET -o jsonpath --template '{.data.YOUR_INNER_SECRET}' | base64 -d
```

That said, that is a bit of a mouthful. Also, it might be nice to more easily 'work' with individual secrets and set them as well as get them. Should a user really need to pull down an entire group of secrets and edit a file just to be able to update a single password? For example something like this might be possible:
```bash
$ kubectl get secret YOUR_SECRET YOUR_INNER_SECRET
[DECODED VALUE PRINTED OUT]
$ kubectl set secret YOUR_SECRET YOUR_INNER_SECRET NEW_DECODED_VALUE
```

What do people think?

PS: Should this have been an issue on [kubectl] instead?
PPS: I think some of the ugliness of this comes from configmaps being very similar to secrets except for the base64 encoding. Have there been any thoughts around bringing them into line? If memory serves, it might actually be nicer, due to YAML syntax-shenanigans, if configmaps were base64 encoded too.)

[kubectl]: https://github.com/kubernetes/kubectl

**Comment by glb** [comment]
Hi @daniel-ac-martin ... yes, I was thinking that it would be handy to be able to do something like:

```sh
kubectl get secret YOUR_SECRET -o go-template='{{ .data.YOUR_INNER_SECRET | b64dec }}'
```

which is essentially the same as what you did without the overhead of the base64 process, or embed the information in a larger template like

```sh
kubectl get secret SECRET -o go-template='Your secret is: {{ .data.INNER_SECRET | b64dec }}'
```

or in theory be able to use any of the other Sprig functions if someone found them useful. I think that having the Sprig methods available for generic `go-template` formatting would just be useful on its own, really.

On the topic of a `kubectl get secret YOUR_SECRET YOUR_INNER_SECRET` or a `kubectl set secret YOUR_SECRET YOUR_INNER_SECRET NEW_DECODED_VALUE`, that seems pretty cool. There seem to be quite a lot of options for `kubectl create secret` that I think people might expect to see mirrored in a `kubectl set secret` if it were to exist. Thoughts?

Unrelated ... can just anyone tell the bot that this issue is getting some attention?

**Comment by glb** [comment]
It's also come to my attention that `base64 -D` works great on MacOS but on Linux it's `base64 -d`, so if someone, say, has a Helm chart where the notes tell the user to retrieve the secret data using one or the other of these, it won't work on the other one.

```kubectl get secret SECRET INNER_SECRET``` would clearly be a simpler experience for the user than ```kubectl get secret SECRET -o go-template='{{ .data.INNER_SECRET | b64dec }}'```

Hmm... thinking further: does does the `kubectl get secret SECRET INNER_SECRET` conflict with the documentation in `kubectl`? ```
kubectl get (TYPE [NAME | -l label] | TYPE/NAME ...)
```

**Comment by AgentME** [comment]
Small tip: you can use `base64 --decode` which works on both Linux and Mac.

**Comment by glb** [comment]
Thank you @AgentME!

**Comment by glb** [comment]
Update: I've looked at the huge amount of additional code that would be imported as a result of importing sprig and decided to go with a much smaller change instead, which is simply to implement a `b64dec` template function using `base64.StdEncoding.DecodeString`. See PR with code and test.

**Comment by glb** [comment]
@daniel-ac-martin @ericchiang please see the linked PR which addresses the original issue in a minimal fashion -- it simply provides a `b64dec` template function. It has passed all the tests and needs review; if it's good enough to solve the original problem I'm happy to squash the commits and can hope to get it merged.

As far as solving @daniel-ac-martin's evolved description of the problem, I'm not sure where to start or if you really want me to go in that direction. Would you consider taking this change and splitting the additional work for being able to get / set the contents of an individual key in a secret into a separate issue? If you have any guidance on what you'd like to see with that I'd be happy to take a look, but it might be out of my current grasp.
