### ISSUE TITLE
API coverage statistics

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#4529]
We need a way to figure out how much of our API is covered by our e2e tests. @brendanburns suggested this was possible with log scraping today. We also need a way to get it back to the test harness itself so that we can report on it. (Per-test? Per-run?)

**Comment by brendandburns** [comment]
I started writing an api proxy that can also collect this info, its just a
question of plugging it in...

Brendan

**Comment by zmerlynn** [comment]
Where is it?
