### ISSUE TITLE
breakup the certificates controller

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#45302]
The signer and approver should be distinct controllers.

@pipejakob @jcbsmpsn

**Comment by erictune** [comment]
Bug scrub says: Please apply sig label and assignee so that we have metadata for future bug analysis.

**Comment by ericchiang** [comment]
@mikedanese is this issue also to address the comments brought up in https://github.com/kubernetes/kubernetes/pull/45059 about the scope of the CSR approver? E.g. if the approver should handle follow up requests for the serving cert?

**Comment by mikedanese** [comment]
@ericchiang have you seen https://github.com/kubernetes/kubernetes/issues/45030?

**Comment by ericchiang** [comment]
@mikedanese ah that's what I'm looking for, thanks.

**Comment by liggitt** [comment]
fixed in #45514
