### ISSUE TITLE
Do not use annotation for pod affinity

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#45318]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
master

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Check https://github.com/kubernetes/kubernetes/blob/master/examples/cockroachdb/cockroachdb-statefulset.yaml#L80-L96 , it is still using `scheduler.alpha.kubernetes.io/affinity`, we should move it to `PodSpec`.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by ethernetdan** [comment]
@gyliu513 probably will want to move the init container also to the PodSpec

**Comment by gyliu513** [comment]
I think the init container still depend on annotations https://kubernetes.io/docs/concepts/workloads/pods/init-containers/ , can I specify in `PodSpec`? @ethernetdan

**Comment by xiangpengzhao** [comment]
@gyliu513 FYI

[CHANGELOG](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#pod)

>Init containers have graduated to GA and now appear as a field. The beta annotation value will still be respected and overrides the field value. (#38382, @hodovska)

**Comment by xiangpengzhao** [comment]
Seems like that the doc should be updated.
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

@hodovska @smarterclayton

**Comment by gyliu513** [comment]
Thanks @xiaopengzhao I filed an issue here https://github.com/kubernetes/kubernetes.github.io/issues/3649

**Comment by gyliu513** [comment]
@ethernetdan @a-robinson What about merge this first and then handle init-container in a separate PR?

**Comment by a-robinson** [comment]
Sounds good to me, thanks.
