### ISSUE TITLE
[Proposal]Add support to delete specified pods when scaling a deployment

### ISSUE THREAD

**Issue by hex108** [kubernetes/kubernetes#45339]
We've used kubernetes for a long time. There are some cases that we want/need to delete specific pods when scaling a deployment to smaller replicas, e.g.

* Case 1: we want to delete deployment A's pods on node N and do not affect deployment B's pods on the same node(node N).

* Case 2: we register deployment A's pods' ip to a load balancer. Then we remove some pods' ip from the load balancer for some reason. Now we want to delete those pods.

**Problem**
The problem is that RS controller might delete pods that are not what we want when scaling.

**Our solution**
Label those pods(that we want delete) with a label(e.g. POD_TO_DELETE=TRUE). When RS controller delete pods, it will sort pods with some algorithm(ActivePods.Less() at `pkg/controller/controller_utils.go`), we could change the algorithm to make pods with the label to be deleted first.

Operations to delete specific pods are very easy:
1. Label them using `kubectl label pod pod-XXX POD_TO_DELETE=TRUE`
2. Scale the deployment to a smaller replicas

**Comment by kargakis** [comment]
@kubernetes/sig-apps-feature-requests 

This has also been mentioned in https://docs.google.com/document/d/1-H2hnZap7gQivcSU-9j4ZrJ8wE_WwcfOkTeAGjzUyLA

cc: @bgrant0607 @jbeda @mfojtik @tnozicka

**Comment by hex108** [comment]
@kargakis Thanks, it seems I do not have permission to see it :( , I just applied.

**Comment by erictune** [comment]
@foxish if we had this I guess Spark could use deployments?

**Comment by davidopp** [comment]
@hex108 the doc is shared with a number of SIG mailing lists already, but I also shared with kubernetes-dev so you should be able to view it if you join kubernetes-dev

evictionCost is mentioned briefly in the doc, but the main issue for this particular feature is #4301 and I think this is probably a duplicate and should be closed (add your requirements to that issue).

**Comment by kargakis** [comment]
@hex108 moved your cases in https://github.com/kubernetes/kubernetes/issues/4301#issuecomment-299411273, feel free to leave additional comments there.
