### ISSUE TITLE
Pod cgroup removed(process killed) before containers stopped, cause cni gets empty network namespace when TearDownPod

### ISSUE THREAD

**Issue by liaoyw** [kubernetes/kubernetes#45334]
**What keywords did you search in Kubernetes issues before filing this one?** 
cgroup removed
May be related to https://github.com/kubernetes/kubernetes/pull/42585,  https://github.com/kubernetes/kubernetes/pull/42893, since it's merged,  start this new issue

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
**Also tried 1.6.1/1.6.2, same result**

**Environment**:
- **Cloud provider or hardware configuration**: bare metal
- **OS** (e.g. from /etc/os-release): CentOS Linux release 7.3.1611 (Core)
- **Kernel** (e.g. `uname -a`): Linux  3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: use simple shell to run
- **Others**:

**What happened**:
Pod cgroup removed before containers stopped, container exited before StopPodSandbox, then cni teardownPod without pod infra-container network namespace.
Our custum cni plugin need network namespace to release ip, thus cause ip leak.

**What you expected to happen**:
Stop Pod before pod cgroup get removed

**How to reproduce it** (as minimally and precisely as possible):
kubectl run mydeploy --image=$some-image --overrides='{"spec": {"template": {"spec": { "nodeSelector": {"kubernetes.io/hostname": "some-node"}}}}}'

kubectl scale deploy mydeploy --replicas=60 && kubectl scale deploy mydeploy --replicas=0
**about 3/60 will occour.**

**Anything else we need to know**:
some logs
pod: redis-2083849560-8rhdt
infra-container pause pid: 60380
```
I0428 10:00:05.959103  237187 kubelet.go:1884] SyncLoop (housekeeping)
I0428 10:00:05.973612  237187 kubelet_pods.go:891] Killing unwanted pod "redis-2083849560-fp4qr"
--> I0428 10:00:05.973640  237187 kubelet_pods.go:891] Killing unwanted pod "redis-2083849560-8rhdt"
I0428 10:00:05.973657  237187 kubelet_pods.go:891] Killing unwanted pod "redis-2083849560-057gf"
I0428 10:00:05.978369  237187 kuberuntime_container.go:535] Killing container "docker://0200887ef9f1f825d47dc73aa6434e3fbbc34ce92688e97682b539e095c5152a" with 30 second grace period
I0428 10:00:05.979644  237187 kuberuntime_container.go:535] Killing container "docker://511e6647df544230dee70823799f187a9232295b5151853235261be886ca8013" with 30 second grace period
I0428 10:00:05.979898  237187 kuberuntime_container.go:535] Killing container "docker://19e294e5df7d92679550499feccb1a126d5c17d1834de813c7adc821ebf0861a" with 30 second grace period
----> I0428 10:00:05.983415  237187 kubelet_pods.go:1549] Orphaned pod "61f4acd9-2bb6-11e7-b7e6-4846fb87c97d" found, removing pod cgroups
I0428 10:00:05.983462  237187 kubelet_pods.go:1543] Orphaned pod "61f4c765-2bb6-11e7-b7e6-4846fb87c97d" found, but volumes not yet removed.  Reducing cpu to minimum
I0428 10:00:05.983563  237187 kubelet_pods.go:1543] Orphaned pod "61f4afdd-2bb6-11e7-b7e6-4846fb87c97d" found, but volumes not yet removed.  Reducing cpu to minimum
I0428 10:00:05.983638  237187 kubelet_pods.go:1543] Orphaned pod "6224f690-2bb6-11e7-b7e6-4846fb87c97d" found, but volumes not yet removed.  Reducing cpu to minimum
I0428 10:00:05.983727  237187 kubelet_pods.go:1543] Orphaned pod "622c971b-2bb6-11e7-b7e6-4846fb87c97d" found, but volumes not yet removed.  Reducing cpu to minimum
I0428 10:00:05.983808  237187 kubelet_pods.go:1543] Orphaned pod "6261ff4e-2bb6-11e7-b7e6-4846fb87c97d" found, but volumes not yet removed.  Reducing cpu to minimum
I0428 10:00:05.983884  237187 kubelet_pods.go:1543] Orphaned pod "623bd8d0-2bb6-11e7-b7e6-4846fb87c97d" found, but volumes not yet removed.  Reducing cpu to minimum
I0428 10:00:05.983994  237187 kubelet_pods.go:1543] Orphaned pod "61f4c3e6-2bb6-11e7-b7e6-4846fb87c97d" found, but volumes not yet removed.  Reducing cpu to minimum
I0428 10:00:05.984077  237187 kubelet_pods.go:1543] Orphaned pod "61f4c6a9-2bb6-11e7-b7e6-4846fb87c97d" found, but volumes not yet removed.  Reducing cpu to minimum
I0428 10:00:05.984152  237187 kubelet_pods.go:1543] Orphaned pod "61f73fe8-2bb6-11e7-b7e6-4846fb87c97d" found, but volumes not yet removed.  Reducing cpu to minimum
I0428 10:00:05.984228  237187 kubelet_pods.go:1543] Orphaned pod "62437aaa-2bb6-11e7-b7e6-4846fb87c97d" found, but volumes not yet removed.  Reducing cpu to minimum
--> I0428 10:00:05.988102  237187 pod_container_manager_linux.go:140] Attempt to kill process with pid: 60380
I0428 10:00:05.988140  237187 pod_container_manager_linux.go:140] Attempt to kill process with pid: 60685
I0428 10:00:05.988162  237187 pod_container_manager_linux.go:140] Attempt to kill process with pid: 60707
I0428 10:00:05.988191  237187 pod_container_manager_linux.go:147] successfully killed all unwanted processes.
I0428 10:00:05.988916  237187 config.go:101] Looking for [api], have seen map[api:{}]
I0428 10:00:06.014510  237187 desired_state_of_world_populator.go:132] Skipping findAndRemoveDeletedPods(). Not permitted until 2017-04-28 10:00:06.210006609 +0800 CST (getPodStatusRetryDuration 2s).
I0428 10:00:06.053788  237187 eviction_manager.go:197] eviction manager: synchronize housekeeping
I0428 10:00:06.062781  237187 kuberuntime_container.go:554] Container "docker://511e6647df544230dee70823799f187a9232295b5151853235261be886ca8013" exited normally
I0428 10:00:06.062863  237187 server.go:345] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"redis-2083849560-8rhdt", UID:"61f4acd9-2bb6-11e7-b7e6-4846fb87c97d", APIVersion:"v1", ResourceVersion:"9671675", FieldPath:"spec.containers{redis}"}): type: 'Normal' reason: 'Killing' Killing container with id docker://511e6647df544230dee70823799f187a9232295b5151853235261be886ca8013:Need to kill Pod
I0428 10:00:06.067325  237187 helpers.go:210] Cannot find network namespace for the terminated container "6f7efcc7c7b2ea5c5bbb3a8255c12b084abe3d7212731323421f74d131b01351"
W0428 10:00:06.079068  237187 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "redis-2083849560-8rhdt_default": Unexpected command output nsenter: cannot open : No such file or directory
 with error: exit status 1
I0428 10:00:06.079103  237187 helpers.go:210] Cannot find network namespace for the terminated container "6f7efcc7c7b2ea5c5bbb3a8255c12b084abe3d7212731323421f74d131b01351"
--> I0428 10:00:06.079141  237187 plugins.go:410] Calling network plugin cni to tear down pod "redis-2083849560-8rhdt_default"
I0428 10:00:06.080362  237187 helpers.go:210] Cannot find network namespace for the terminated container "6f7efcc7c7b2ea5c5bbb3a8255c12b084abe3d7212731323421f74d131b01351"
```

**Comment by erictune** [comment]
@kubernetes/sig-node-bugs

**Comment by vishh** [comment]
@Random-Liu @yujuhong what's the lifecycle of a pod with CRI? Is pod deletion at the CRI level happening asynchronously?

**Comment by yujuhong** [comment]
> @Random-Liu @yujuhong what's the lifecycle of a pod with CRI? Is pod deletion at the CRI level happening asynchronously?

No. it's pretty much the same as before.

**Comment by phsiao** [comment]
We are experiencing similar issue with our CNI dhcp plugin, where the infra-container is terminated while CNI plugin is still processing ADD.  The teardown part of it will also fail because the netns is missing.  Not sure if it is a new issue in 1.6, can verify if needed.

**Comment by bboreham** [comment]
> Our custum cni plugin need network namespace to release ip, thus cause ip leak.

@liaoyw sadly this is is a bug in your CNI plugin, after the [CNI spec](https://github.com/containernetworking/cni/blob/master/SPEC.md#network-configuration-list-error-handling) was updated to include these words:

>  an IPAM plugin should generally release an IP allocation and return success even if the container network namespace no longer exists

See also #43488

**Comment by liaoyw** [comment]
@bboreham  thanks for the info. 
We've refactored our cni plugin.
