### ISSUE TITLE
x509 auth: Multiple groups are not supported when using certificates generated by cfssl

### ISSUE THREAD

**Issue by alexbrand** [kubernetes/kubernetes#45353]
**Keywords**: x509 authentication certificates cfssl

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): `v1.6.2`

**What happened**: When using x509 authentication with a certificate that has multiple organizations in the Subject, the first organization is used as the user's group, but the rest are dropped.

**What you expected to happen**: If a certificate has multiple organizations, the authenticated user should have multiple groups in their UserInfo.

**How to reproduce it** (as minimally and precisely as possible):
I have nailed this down to an [issue](https://github.com/golang/go/issues/12342) with `go1.7` (maybe earlier versions as well) and certificates generated with `cfssl`. @ericchiang has ran into this in the past: https://github.com/kubernetes-incubator/bootkube/issues/338. Full repro steps (and sample cfssl cert) are detailed here: https://github.com/apprenda/kismatic/issues/530#issuecomment-299185580

Given that it is an issue with go's stdlib, we can't really do anything at this point, other than upgrading the go version used for building kubernetes. Other than that, it might be worth adding a unit test if one doesn't exist yet.

**Comment by ericchiang** [comment]
cc @kubernetes/sig-auth-bugs

**Comment by liggitt** [comment]
certs with multiple organizations can work (there's a unit test at https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509_test.go#L577) but it depends on how the RDN of the cert is constructed.

**Comment by alexbrand** [comment]
Got it. I think it's mainly an issue with `cfssl` generating certs with misconstructed RDNs.

**Comment by liggitt** [comment]
partly the way cfssl constructs them, partly the way go flattens the multi-dimensional RDN (which they changed in 1.8)

**Comment by erictune** [comment]
@alexbrand closing since I think it is not a Kube problem.  Please complain if it should not be closed.
