### ISSUE TITLE
User "system:serviceaccount:kube-system:kube-proxy" cannot list services at the cluster scope

### ISSUE THREAD

**Issue by rafagsiqueira** [kubernetes/kubernetes#45359]
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T22:51:55Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- **Kernel** (e.g. `uname -a`): Linux node1 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubeadm
- **Others**:
Nodes in differente Azure regions.
**What happened**:
kube-proxy logs are showing User "system:serviceaccount:kube-system:kube-proxy" cannot list services at the cluster scope.

**What you expected to happen**:
No errors in kube-proxy logs

**How to reproduce it** (as minimally and precisely as possible):
kubectl -n kube-system logs <kube-proxy pod>

**Anything else we need to know**:
Executing the following command eliminates the error from the logs.
`kubectl create rolebinding kube-proxy-list --clusterrole=view --serviceaccount=kube-system:kube-proxy --namespace=kube-system`

**Comment by liggitt** [comment]
kubeadm is setting up the binding to the `system:node-proxier` role for that service account here:

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/apiconfig/clusterroles.go#L160

@luxas @andrewrynhard can you take a look?

**Comment by rafagsiqueira** [comment]
If it helps, this was my full kubeadm init command:
`kubeadm init --apiserver-advertise-address 52.170.213.130 --apiserver-cert-extra-sans=master.digify.com.br,node1.digify.com.br --pod-network-cidr=10.244.0.0/16`

**Comment by liggitt** [comment]
what does `kubectl get clusterrolebindings kubeadm:node-proxier -o yaml` show?

**Comment by liggitt** [comment]
and did you remove any clusterrolebindings after running kubeadm init?

**Comment by rafagsiqueira** [comment]
`apiVersion: rbac.authorization.k8s.io/v1beta1`
`kind: ClusterRoleBinding`
`metadata:`
`  creationTimestamp: 2017-05-04T17:38:38Z`
`  name: kubeadm:node-proxier`
`  resourceVersion: "97"`
`  selfLink: /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindingskubeadm%3Anode-proxier`
`  uid: 81f688d7-30f0-11e7-9d74-000d3a1b1785`
`roleRef:`
`  apiGroup: rbac.authorization.k8s.io`
`  kind: ClusterRole`
`  name: system:node-proxier`
`subjects:`
`- kind: ServiceAccount`
`  name: kube-proxy`
`  namespace: kube-system`

And no, I did not remove any clusterrolebindings.

**Comment by rafagsiqueira** [comment]
I have recreated the cluster afterwards and the problem did not happen again. Since I can't reproduce it, will close this.

**Comment by liggitt** [comment]
creating a rolebinding would not have removed that error, since it does not grant permission to list things at the cluster scope.

there is a period of time at cluster start during which RBAC is initializing where requests are denied. it is likely the logging happened during that time period.

**Comment by rafagsiqueira** [comment]
Sorry for my misunderstanding. I ran into this log errors while trying to solve a 404 error when trying to kubectl log or kubectl exec any pod that is not running on the master node. Will open another issue for this.
