### ISSUE TITLE
Add `kubectl set affinity` command

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#45357]
The affinity fields are nesting a bunch of levels deep making it really hard to hand-craft a JSON/YAML file with configured affinity for a controller that this command is warranted.

@kubernetes/sig-scheduling-misc @kubernetes/sig-cli-misc

**Comment by gyliu513** [comment]
When using `kubectl set affinity`, the pods for the deployment should already be running, so how to make the updated affinity take effect?

**Comment by kargakis** [comment]
@gyliu513 once the {Deployment,DaemonSet,StatefulSet} PodTemplateSpec is updated, a new rollout kicks off - old pods are deleted, new pods are created. This could also work for ReplicaSets but you would have to manually kill the old Pods for the new Pods to be scheduled using the new affinity rules.

**Comment by gyliu513** [comment]
@kargakis I see, so this is a `special update for affinity`. Can you please show more detail for how to define the command? i.e. the subcommand, help etc?

**Comment by timothysc** [comment]
Umm this would lead to more confusion imo.  
This is a YAML problem not a control flow or spec problem. 

/cc @hausdorff

**Comment by kargakis** [comment]
@gyliu513 you mean how would I use it? I was envisioning something like
```
kubectl set affinity --pod --required --operator=In app=test deploy/foo
```
Or something along those lines. I am not married to the subcommand name, if there are no mutually exclusive flags between pod and node affinity then I would prefer a single command, otherwise separate commands for each type of affinity make sense.

**Comment by jbeda** [comment]
I don't think it is sustainable to have a command for every tunable in every object. And it is strange that it is here but not on `kubectl run`. I understand the pain, but if yaml is too hard to edit that is the problem we should be tackling. Or have a plan to update everything. 

Perhaps, in the meantime, use `kubectl patch`?

**Comment by kargakis** [comment]
We should stop adding stuff in `kubectl run` (look at the help text) and I can't see why using `kubectl patch` is any different from hand-crafting JSON/YAML files, it's just ... more scriptable than using an editor.

**Comment by kargakis** [comment]
Probably dupe of https://github.com/kubernetes/kubernetes/issues/7296

**Comment by davidopp** [comment]
Yeah I think affinity is too complex to fashion a reasonable way to express it on the command line.

**Comment by kargakis** [comment]
I am not sure if editing YAML or piping to sed is any less complex from a UX perspective. Closing in favor of #7296
