### ISSUE TITLE
--register-with-taints not tainting my controller nodes

### ISSUE THREAD

**Issue by mccormd** [kubernetes/kubernetes#45361]
BUG REPORT

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release):  CoreOS / 1353.7.0
- **Kernel** (e.g. `uname -a`): Linux ip-10-20-14-132.eu-west-1.compute.internal 4.9.24-coreos #1 SMP Wed Apr 26 21:44:23 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux
- **Install tools**: cloud-config, custom build
- **Others**:

**What happened**:
I created a systemd unit to start the kubelet on my master hosts with these options...

~~~
[Unit]
Description=Kubernetes Kubelet
Requires=docker.service

[Service]
ExecStart=/usr/bin/docker run --rm \
 --name kubelet \
 --volume=/:/rootfs:ro \
 --volume=/sys:/sys:ro \
 --volume=/dev:/dev \
 --volume=/var/lib/docker/:/var/lib/docker:rw \
 --volume=/var/lib/kubelet/:/var/lib/kubelet:shared \
 --volume=/etc:/etc:rw \
 --volume=/var/run:/var/run:rw \
 --net=host --pid=host --privileged=true \
 gcr.io/google_containers/hyperkube:v1.6.2 \
 /hyperkube kubelet \
  --node-labels="type=controller" \
  --register-with-taints=node-role.kubernetes.io/master=true:NoSchedule \
  --hostname-override=10.20.14.132 \
  --register-node=true \
  --containerized \
  --pod-manifest-path=/etc/kubernetes/manifests \
  --allow-privileged=true \
  --network-plugin=cni \
  --cni-conf-dir=/etc/cni/net.d \
  --cni-bin-dir=/opt/cni/bin \
  --cluster-dns=192.168.0.10 \
  --cluster-domain=cluster.local \
  --v=4 \
  --require-kubeconfig=true \
  --kubeconfig=/etc/kubernetes/node-kubeconfig.yaml \
  --tls-cert-file=/etc/kubernetes/ssl/kubelet.pem \
  --tls-private-key-file=/etc/kubernetes/ssl/kubelet-key.pem \
  --volume-plugin-dir=/etc/kubernetes/vol-plugins \
  --cloud-config=/etc/kubernetes/cloud_config \
  --cloud-provider=aws
TimeoutStartSec=900s
Restart=always
RestartSec=10s
[Install]
WantedBy=multi-user.target
~~~

I'm expecting the node to automatically register (--register-node=true) with a taint (--register-with-taints=node-role.kubernetes.io/master=true:NoSchedule) but when I examine my master node I can't see a taint and non system pods are being scheduled to it.

~~~
$ kubectl describe node ip-10-20-14-132.eu-west-1.compute.internal
Name:			ip-10-20-14-132.eu-west-1.compute.internal
Role:			
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/instance-type=t2.large
			beta.kubernetes.io/os=linux
			failure-domain.beta.kubernetes.io/region=eu-west-1
			failure-domain.beta.kubernetes.io/zone=eu-west-1c
			kubernetes.io/hostname=10.20.14.132
			type=controller
Annotations:		flannel.alpha.coreos.com/backend-data={"VtepMAC":"7e:40:99:f7:7a:01"}
			flannel.alpha.coreos.com/backend-type=vxlan
			flannel.alpha.coreos.com/kube-subnet-manager=true
			flannel.alpha.coreos.com/public-ip=10.20.14.132
			node.alpha.kubernetes.io/ttl=0
			volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:			<none>
CreationTimestamp:	Thu, 04 May 2017 08:43:10 +0000
~~~

**What you expected to happen**:

The master should be registered with the taint: node-role.kubernetes.io/master=true:NoSchedule

**How to reproduce it** (as minimally and precisely as possible):
Create a kubelet process using the service above, observe if it gets tainted.

**Anything else we need to know**:

**Comment by luxas** [comment]
@mikedanese PTAL

I think I can confirm this issue, I'm pretty sure I hit this as well this morning...

**Comment by aveshagarwal** [comment]
@luxas as we discussed on slack, its an issue with kubeadm. 

To double check, I also verified locally on cluster by adding --register-with-taints flag to kubelet and the node got registered with the provided taint as expected.

**Comment by luxas** [comment]
@aveshagarwal Sorry, seems like there were two different issues. Mine was kubeadm-specific (fixed here: https://github.com/kubernetes/kubernetes/pull/45376), but after reading this in more detail, it isn't set up with kubeadm.

@aveshagarwal Can you please revisit this issue? Sorry for the confusion

**Comment by erictune** [comment]
by the way, luxas, you could do `/assign @aveshagarwal`

**Comment by mccormd** [comment]
Hi - just to confirm - I'm not using kubeadm.

**Comment by aveshagarwal** [comment]
I tested it yesterday with latest master HEAD and it worked as expected. I am going to try 1.6.2 today the same way in container as @mccormd did.

**Comment by luxas** [comment]
Oops, @aveshagarwal was already assigned :)

**Comment by aveshagarwal** [comment]
I just tested both containerized and non-containerized versions on latest 1.6 branch and both worked correctly.  I just had to remove and tweak some flags for kubelet as I am running in a local cluster settings. Here is what I get and it shows the taint assigned to the node:

```
Name:			10.20.14.132
Role:			
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/os=linux
			kubernetes.io/hostname=10.20.14.132
			type=controller
Annotations:		node.alpha.kubernetes.io/ttl=0
			volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:			node-role.kubernetes.io/master=true:NoSchedule
CreationTimestamp:	Fri, 05 May 2017 11:38:32 -0400
Phase:			
```
Here is the script I used to run kubelet inside a container:

```
#!/bin/sh

/usr/bin/docker run --rm \
 --name kubelet \
 --volume=/:/rootfs:ro \
 --volume=/sys:/sys:ro \
 --volume=/dev:/dev \
 --volume=/var/lib/docker/:/var/lib/docker:rw \
 --volume=/var/lib/kubelet/:/var/lib/kubelet:shared \
 --volume=/etc:/etc:rw \
 --volume=/var/run:/var/run:rw \
 --net=host --pid=host --privileged=true \
 gcr.io/google_containers/hyperkube:v1.6.2 \
 /hyperkube kubelet \
  --node-labels="type=controller" \
  --register-with-taints=node-role.kubernetes.io/master=true:NoSchedule \
  --hostname-override=10.20.14.132 \
  --register-node=true \
  --containerized \
  --allow-privileged=true \
  --cgroup-driver=systemd \
  --cluster-dns=192.168.0.10 \
  --cluster-domain=cluster.local \
  --v=4 \
  --require-kubeconfig=true \
  --kubeconfig=/var/run/kubernetes/kubelet.kubeconfig \
  --tls-cert-file=/var/run/kubernetes/kubelet.crt \
  --tls-private-key-file=/var/run/kubernetes/kubelet.key
```

@mccormd Are you sure that your node was not already registered? Could you try following things if possible: 1) stop the node  2) remove the node from the cluster 3) restart the node  and see if it gets taint now?  Also could you share your kubelet and apiserver logs to see what is going on?

**Comment by aveshagarwal** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by jayunit100** [comment]
Yeah , this sounds like the node was already registered . please confirm what avesh asked....

Otherwise register-with-taints semantics can be misleading.  We might want to revisit how we handle the "already registered but not tainted " register-with-taints behavior at some point , but maybe the dynamic kubelet config will solve that for us...

**Comment by mikedanese** [comment]
@mccormd this looks like a dupe of https://github.com/coreos/flannel/issues/667 which is a problem with flannel (I notice your flannel annotations). It's fixed in the newest release of flannel.

**Comment by mccormd** [comment]
Hi, apologies for the delay in trying this out - I can confirm it was the flannel bug and the newest version of flannel (7.1) resolved the problem for me.  Many thanks!

**Comment by alecb-stripe** [comment]
@jayunit100 

> Otherwise register-with-taints semantics can be misleading. We might want to revisit how we handle the "already registered but not tainted " register-with-taints behavior at some point

Is this behavior documented somewhere? I.e., that starting the kubelet with `--register-with-taints` will be a no-op if the node object already exists in the API (e.g., on a host reboot).
