### ISSUE TITLE
system:discovery cluster role should include the "/" nonResourceURL

### ISSUE THREAD

**Issue by luksa** [kubernetes/kubernetes#45366]
**What keywords did you search in Kubernetes issues before filing this one?** 
- system:discovery
- nonResourceURLs

---
**Problem description**
Shouldn't the system:discovery cluster role also allow listing the API server's root URL? It allows URLs like `/api`, `/apis`, `/healthz`, but not `/`, which would help in discovering API endpoints.

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"dirty", BuildDate:"2017-04-07T20:43:50Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: minikube with RBAC enabled

**What happened**:
```
$ curl https://$(minikube ip):8443/ -k
User "system:anonymous" cannot get  at the cluster scope.

$ curl https://$(minikube ip):8443/api -k
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "10.0.2.15:8443"
    }
  ]
}
```

**What you expected to happen**:
```
$ curl https://$(minikube ip):8443/ -k
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/apps",
    "/apis/apps/v1beta1",
    "/apis/authentication.k8s.io",
    "/apis/authentication.k8s.io/v1",
    "/apis/authentication.k8s.io/v1beta1",
    "/apis/authorization.k8s.io",
    "/apis/authorization.k8s.io/v1",
    "/apis/authorization.k8s.io/v1beta1",
    "/apis/autoscaling",
    "/apis/autoscaling/v1",
    "/apis/autoscaling/v2alpha1",
    "/apis/batch",
    "/apis/batch/v1",
    "/apis/batch/v2alpha1",
    "/apis/certificates.k8s.io",
    "/apis/certificates.k8s.io/v1beta1",
    "/apis/extensions",
    "/apis/extensions/v1beta1",
    "/apis/policy",
    "/apis/policy/v1beta1",
    "/apis/rbac.authorization.k8s.io",
    "/apis/rbac.authorization.k8s.io/v1alpha1",
    "/apis/rbac.authorization.k8s.io/v1beta1",
    "/apis/settings.k8s.io",
    "/apis/settings.k8s.io/v1alpha1",
    "/apis/storage.k8s.io",
    "/apis/storage.k8s.io/v1",
    "/apis/storage.k8s.io/v1beta1",
    "/healthz",
    "/healthz/ping",
    "/healthz/poststarthook/bootstrap-controller",
    "/healthz/poststarthook/ca-registration",
    "/healthz/poststarthook/extensions/third-party-resources",
    "/healthz/poststarthook/rbac/bootstrap-roles",
    "/logs",
    "/metrics",
    "/swaggerapi/",
    "/ui/",
    "/version"
  ]
}
```

**Comment by liggitt** [comment]
cc @kubernetes/sig-auth-misc

**Comment by ericchiang** [comment]
I think the original motivation for system:discovery is so when you run `kubectl version` against a cluster without credentials you get something useful. But since system:discovery is tied to system:unauthenticated, I'd really prefer we lock it down as much as possible. It's surprising when people can do stuff without needing credentials.

Does this break some tools or is this just a nice to have?

**Comment by luksa** [comment]
It's just a nice to have. If someone wants to explore the API (or, for example, see if they can talk to the API server from within a pod), they usually start by  curling `/`. Right now, the response leads them to believe they can't do anything without being authenticated and authorized, which isn't really true. 

I understand the security aspect of locking down everything as much as possible, but the information returned at `/`is nothing that you can't google around for. 

I'm fine if you reject the change, just wanted to make you aware of the discrepancy.

**Comment by liggitt** [comment]
I'd prefer to limit the allowed urls to ones with concrete use cases
