### ISSUE TITLE
Think about requiring special privileges for setting some tolerations

### ISSUE THREAD

**Issue by SleepyBrett** [kubernetes/kubernetes#45367]
- Describe *in detail* the feature/behavior/change you'd like to see.
Since 1.6 daemonsets now respect node taints. This makes running a self-hosted kubernetes problematic as kube-proxy/flannel etc are all scheduled by daemonsets. In a very stable environment where you know all the node taints you use and can add those to all the daemonsets ahead of time this isn't much of an issue. However we add and remove tainted node pools to our cluster semi-frequently and having to patch all the daemonsets to do that is disruptive.

I'd like to propose the ability to specify a wildcard toleration something like:
```
scheduler.alpha.kubernetes.io/tolerations: '[{"key":"dedicate", "value":"*"}]'
```

**Kubernetes version** (use `kubectl version`):
1.6.1

**Environment**:
- **Cloud provider or hardware configuration**:
AWS

- **OS** (e.g. from /etc/os-release):
ContainerLinux

- **Kernel** (e.g. `uname -a`):
N/A

- **Install tools**:
Private bootstrap

**What happened**:
None of my tainted nodes join the cluster successfully anymore because my daemonsets no longer schedule to all nodes.

**What you expected to happen**:
I'd expect there would be a way to tolerate any taint.

**Comment by SleepyBrett** [comment]
it was suggested the the following might work, it does not seem to:
`scheduler.alpha.kubernetes.io/tolerations: '[{"operator":"Exists"}]'`

**Comment by aveshagarwal** [comment]
@SleepyBrett it is kind of alluded in the documentation here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/ 

see this line: `As a special case, an empty key with operator Exists matches all keys and all values. Also as a special case, empty effect matches all effects.`

In general, it would be good to have some sort of restriction to not allow someone with not special privileges to set this kind of "tolerate everything" tolerations IMO.

**Comment by aveshagarwal** [comment]
@kubernetes/sig-scheduling-misc

**Comment by davidopp** [comment]
I'm going to re-title this issue since the original request is already implemented, as @SleepyBrett noticed.

**Comment by k82cn** [comment]
> In general, it would be good to have some sort of restriction to not allow someone with not special privileges to set this kind of "tolerate everything" tolerations IMO.

As a object (e.g. Pod) owner, I can decide which taint is tolerated; but some taints maybe not really tolerated. So privilege is an option for that.
