### ISSUE TITLE
feature suggestion: kubectl describe service should show pod names

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#45373]
It is easier to mess up the selectors on a service, than it is to diagnose that it has gone wrong.

If `kubectl describe service` showed the pod names for endpoints (not just the pod IPs), I think it would be as easy to diagnose as it is mess up :-)

Could probably add this, but wanted to see if there was any objection / reason why not etc before doing so.  cc @kubernetes/sig-cli-feature-requests

**Comment by erictune** [comment]
@kubernetes/sig-cli-feature-requests 
@pwittrock
