### ISSUE TITLE
Update docker/distribution

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/kubernetes#45377]
There is a bug around k8s use of Docker distribution that's trickling into helm development.

_&TLDR;_ K8s uses revision _cd27f179f2c10c5d300e6d09025b538c475b0d51_ of github.com/docker/distribution (a commit between releases). When helm development scripts try to install this package on Windows it runs into the bug https://github.com/docker/distribution/issues/1690 that has already been fixed. A simple fix could be to use a newer version of docker distribution... possibly a release version rather than in development commit.

For details on helm see https://github.com/kubernetes/helm/issues/2396

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Windows 10
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
An error occurred when installing helm dependencies. It was trying to install a dependency of k8s to the version k8s uses. The error can be seen at https://github.com/kubernetes/helm/issues/2396

**What you expected to happen**:
Installing helm dependencies to work without error.

**How to reproduce it** (as minimally and precisely as possible):
On Microsoft Windows under windows (not a Linux VM or windows linux subsystem) checkout helm, install glide, and run `glide install --strip-vendor`.

**Anything else we need to know**:
Updating to a newer revision of Docker distribution in k8s will enable helm to do the same which will fix the issue.

**Comment by erictune** [comment]
/assign @dchen1107 
@kubernetes/sig-node-bugs

**Comment by erictune** [comment]
@mattfarina which K8s installer are you using to create your cluster? Is this a request for all installers to use the newer version?

**Comment by mattfarina** [comment]
The request is to update the vendored version of the dependency to a newer release that does not contain the issue. See https://github.com/kubernetes/kubernetes/blob/d23c73687a54bc645f59ad3f66c9ad731fda60a6/Godeps/Godeps.json#L825 (this is the tip of master when I grabbed it).

**Comment by yujuhong** [comment]
Is this still needed?

**Comment by mattfarina** [comment]
Kubernetes now has a newer (though unreleased version) of docker/distribution. I think we can close this now.
