### ISSUE TITLE
saltbase/salt/generate-cert/make-ca-cert.sh: No such file or directory

### ISSUE THREAD

**Issue by ffelicissimo** [kubernetes/kubernetes#45371]
Hi,
I'm trying to install the kubernetes cluster using **ubuntu 16.0.4 server** using the kubernetes.io documentation below link:

**Https://kubernetes.io/docs/getting-started-guides/ubuntu/manual/**

fernando@s500lxkubernetes01:~/kubernetes/cluster$ DEBUG=true KUBERNETES_PROVIDER=ubuntu ./kube-up.sh
... Starting cluster using provider: ubuntu
... calling verify-prereqs
Identity added: /home/fernando/.ssh/id_rsa (/home/fernando/.ssh/id_rsa)
... calling verify-kube-binaries
!!! kubectl appears to be broken or missing
Required binaries appear to be missing. Do you wish to download them? [Y/n]
Y
Kubernetes release: 1.6.1
Server: linux/amd64  (to override, set KUBERNETES_SERVER_ARCH)
Client: linux/amd64  (autodetected)

Nothing additional to download.
... calling kube-up
~/kubernetes/cluster/ubuntu ~/kubernetes/cluster
Prepare flannel 0.7.0 release ...
Prepare etcd 3.0.17 release ...
Prepare kubernetes 1.6.1 release ...
Done! All your binaries locate in kubernetes/cluster/ubuntu/binaries directory
~/kubernetes/cluster

Deploying master and node on machine 10.31.0.231
saltbase/salt/generate-cert/make-ca-cert.sh: No such file or directory
easy-rsa.tar.gz                                                                                    100%   42KB  42.4KB/s   00:00    
config-default.sh                                                                                  100% 6317     6.2KB/s   00:00    
util.sh                                                                                            100%   29KB  29.0KB/s   00:00    
kube-proxy.conf                                                                                    100%  688     0.7KB/s   00:00    
kubelet.conf                                                                                       100%  645     0.6KB/s   00:00    
kube-proxy                                                                                         100% 2233     2.2KB/s   00:00    
kubelet                                                                                            100% 2158     2.1KB/s   00:00    
etcd.conf                                                                                          100%  707     0.7KB/s   00:00    
kube-scheduler.conf                                                                                100%  682     0.7KB/s   00:00    
kube-apiserver.conf                                                                                100%  682     0.7KB/s   00:00    
kube-controller-manager.conf                                                                       100%  761     0.7KB/s   00:00    
kube-apiserver                                                                                     100% 2358     2.3KB/s   00:00    
etcd                                                                                               100% 2073     2.0KB/s   00:00    
kube-scheduler                                                                                     100% 2360     2.3KB/s   00:00    
kube-controller-manager                                                                            100% 2672     2.6KB/s   00:00    
reconfDocker.sh                                                                                    100% 2183     2.1KB/s   00:00    
kube-apiserver                                                                                     100%  142MB 142.5MB/s   00:01    
etcdctl                                                                                            100%   18MB  17.6MB/s   00:00    
etcd                                                                                               100%   19MB  19.3MB/s   00:00    
flanneld                                                                                           100%   64MB  64.3MB/s   00:01    
kube-scheduler                                                                                     100%   72MB  72.1MB/s   00:00    
kube-controller-manager                                                                            100%  126MB 125.5MB/s   00:01    
kube-proxy                                                                                         100%   61MB  61.1MB/s   00:01    
kubelet                                                                                            100%  132MB 132.2MB/s   00:01    
flanneld                                                                                           100%   64MB  64.3MB/s   00:00    

After executing kub-up.sh it returns me the following error **"saltbase / salt / generate-cert / make-ca-cert.sh: No such file or directory"** and does not finish the installation and configuration of kubernetes, you can help out?

tks,

**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by erictune** [comment]
Ubuntu maintainers: @Crazykev  @resouer @xlgao-zju
