### ISSUE TITLE
Pod attach volume timeout using scaleio2 in kubernetes1.6

### ISSUE THREAD

**Issue by James-Dao** [kubernetes/kubernetes#45399]
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: bare mental,  2 core 2G
- **OS** (e.g. from /etc/os-release): centos 7.2
- **Kernel** (e.g. `uname -a`): 3.10.0-327.el7.x86_64
- **Install tools**: scaleio2
- **Others**:

**What happened**:
1. create secret and storageclass successfully
2. create persistentvolumeclaims successfully, and i can see a volume created successfully on scaleio, and but mapped, it is expected.
3. I create pod with persistentvolumeclaims which is based on persistentvolumeclaims, i can see the volume is attached on one node with "fdisk -l" and scaleio also says it is mapped to on sdc.

 Pod event says :MountVolume.SetUp failed for volume "kubernetes.io/scaleio/beeefcfd-3163-11e7-9abf-005056a3fdbf-pvc-561b808a-3163-11e7-9abf-005056a3fdbf" (spec.Name: "pvc-561b808a-3163-11e7-9abf-005056a3fdbf") pod "beeefcfd-3163-11e7-9abf-005056a3fdbf" (UID: "beeefcfd-3163-11e7-9abf-005056a3fdbf") with: volume attach timeout
Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"pod-sio-small". list of unattached/unmounted volumes=[test-data]

**What you expected to happen**:
I expect pod can run and mount the volume successfully.  

**How to reproduce it** (as minimally and precisely as possible):
create StorageClass, PersistentVolumeClaim, Pod
File: sc.yaml

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sio-small
provisioner: kubernetes.io/scaleio
parameters:
  gateway: https://192.168.2.76:443/api
  system: test
  protectionDomain: default
  storagePool: defaultSP
  storageMode: ThinProvisioned
  secretRef: sio-secret
  fsType: ext4

kubectl --kubeconfig /etc/kubernetes/admin.conf create -f ./sc.yaml

File sc-pvc.yaml

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sio-small
  annotations:
      volume.beta.kubernetes.io/storage-class: sio-small
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

kubectl --kubeconfig /etc/kubernetes/admin.conf create -f ./sc-pvc.yaml

File pod-sc-pvc.yaml

kind: Pod
apiVersion: v1
metadata:
  name: pod-sio-small
spec:
  containers:
    - name: pod-sio-small-container
      image: nginx
      volumeMounts:
      - mountPath: /test
        name: test-data
  volumes:
    - name: test-data
      persistentVolumeClaim:
        claimName: pvc-sio-small

kubectl --kubeconfig /etc/kubernetes/admin.conf create -f ./pod-sc-pvc.yaml

kubectl --kubeconfig /etc/kubernetes/admin.conf describe po pod-sio-small

**Anything else we need to know**:
controller manager logs says : 
W0505 07:11:49.782385       1 reflector.go:323] k8s.io/kubernetes/pkg/controller/garbagecollector/graph_builder.go:192: watch of <nil> ended with: etcdserver: mvcc: required revision has been compacted
E0505 07:14:50.804000       1 sio_client.go:300] scaleio: drv_cfg --query_guid failed: fork/exec /opt/emc/scaleio/sdc/bin/drv_cfg: no such file or directory
E0505 07:14:50.804019       1 sio_mgr.go:216] scaleio: failed to get instanceID: fork/exec /opt/emc/scaleio/sdc/bin/drv_cfg: no such file or directory
E0505 07:14:50.804030       1 sio_volume.go:222] scaleio: failed to delete volume sio-e8e5e41b316011e7b3fb00505: fork/exec /opt/emc/scaleio/sdc/bin/drv_cfg: no such file or directory
E0505 07:14:50.807897       1 goroutinemap.go:164] Operation for "delete-pvc-e8e46e13-3160-11e7-9abf-005056a3fdbf[e9112f51-3160-11e7-9abf-005056a3fdbf]" failed. No retries permitted until 2017-05-05 07:14:51.30787453 +0000 UTC (durationBeforeRetry 500ms). Error: fork/exec /opt/emc/scaleio/sdc/bin/drv_cfg: no such file or directory
E0505 07:14:55.049115       1 sio_client.go:300] scaleio: drv_cfg --query_guid failed: fork/exec /opt/emc/scaleio/sdc/bin/drv_cfg: no such file or directory
E0505 07:14:55.049139       1 sio_mgr.go:216] scaleio: failed to get instanceID: fork/exec /opt/emc/scaleio/sdc/bin/drv_cfg: no such file or directory
E0505 07:14:55.049149       1 sio_volume.go:222] scaleio: failed to delete volume sio-e8e5e41b316011e7b3fb00505: fork/exec /opt/emc/scaleio/sdc/bin/drv_cfg: no such file or directory
E0505 07:14:55.049182       1 goroutinemap.go:164] Operation for "delete-pvc-e8e46e13-3160-11e7-9abf-005056a3fdbf[e9112f51-3160-11e7-9abf-005056a3fdbf]" failed. No retries permitted until 2017-05-05 07:14:56.049159522 +0000 UTC (durationBeforeRetry 1s). Error: fork/exec /opt/emc/scaleio/sdc/bin/drv_cfg: no such file or directory
W0505 07:21:00.799008       1 reflector.go:323] k8s.io/kubernetes/pkg/controller/garbagecollector/graph_builder.go:192: watch of <nil> ended with: etcdserver: mvcc: required revision has been compacted
W0505 07:36:53.854667       1 reflector.go:323] k8s.io/kubernetes/pkg/controller/garbagecollector/graph_builder.go:192: watch of <nil> ended with: etcdserver: mvcc: required revision has been compacted
W0505 07:46:41.932645       1 reflector.go:323] k8s.io/kubernetes/pkg/controller/garbagecollector/graph_builder.go:192: watch of <nil> ended with: etcdserver: mvcc: required revision has been compacted

but i can see "/opt/emc/scaleio/sdc/bin/drv_cfg" on all nodes.

**Comment by James-Dao** [comment]
Pod event on Kubernets Dashboard  says:

MountVolume.SetUp failed for volume "kubernetes.io/scaleio/beeefcfd-3163-11e7-9abf-005056a3fdbf-pvc-561b808a-3163-11e7-9abf-005056a3fdbf" (spec.Name: "pvc-561b808a-3163-11e7-9abf-005056a3fdbf") pod "beeefcfd-3163-11e7-9abf-005056a3fdbf" (UID: "beeefcfd-3163-11e7-9abf-005056a3fdbf") with: exit status 1


Pod on Kubernets Dashboard says: 
MountVolume.SetUp failed for volume "kubernetes.io/scaleio/beeefcfd-3163-11e7-9abf-005056a3fdbf-pvc-561b808a-3163-11e7-9abf-005056a3fdbf" (spec.Name: "pvc-561b808a-3163-11e7-9abf-005056a3fdbf") pod "beeefcfd-3163-11e7-9abf-005056a3fdbf" (UID: "beeefcfd-3163-11e7-9abf-005056a3fdbf") with: volume attach timeout
Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"pod-sio-small". list of unattached/unmounted volumes=[test-data]

**Comment by James-Dao** [comment]
Pod on Kubernets Dashboard says:
MountVolume.SetUp failed for volume "kubernetes.io/scaleio/beeefcfd-3163-11e7-9abf-005056a3fdbf-pvc-561b808a-3163-11e7-9abf-005056a3fdbf" (spec.Name: "pvc-561b808a-3163-11e7-9abf-005056a3fdbf") pod "beeefcfd-3163-11e7-9abf-005056a3fdbf" (UID: "beeefcfd-3163-11e7-9abf-005056a3fdbf") with: volume attach timeout
Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"pod-sio-small". list of unattached/unmounted volumes=[test-data]


Pod event on Kubernets Dashboard says:

Successfully assigned pod-sio-small to 192-168-1-154

MountVolume.SetUp failed for volume "kubernetes.io/scaleio/beeefcfd-3163-11e7-9abf-005056a3fdbf-pvc-561b808a-3163-11e7-9abf-005056a3fdbf" (spec.Name: "pvc-561b808a-3163-11e7-9abf-005056a3fdbf") pod "beeefcfd-3163-11e7-9abf-005056a3fdbf" (UID: "beeefcfd-3163-11e7-9abf-005056a3fdbf") with: volume attach timeout

MountVolume.SetUp failed for volume "kubernetes.io/scaleio/beeefcfd-3163-11e7-9abf-005056a3fdbf-pvc-561b808a-3163-11e7-9abf-005056a3fdbf" (spec.Name: "pvc-561b808a-3163-11e7-9abf-005056a3fdbf") pod "beeefcfd-3163-11e7-9abf-005056a3fdbf" (UID: "beeefcfd-3163-11e7-9abf-005056a3fdbf") with: exit status 1

Unable to mount volumes for pod "pod-sio-small_default(beeefcfd-3163-11e7-9abf-005056a3fdbf)": timeout expired waiting for volumes to attach/mount for pod "default"/"pod-sio-small". list of unattached/unmounted volumes=[test-data]

Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"pod-sio-small". list of unattached/unmounted volumes=[test-data]

**Comment by James-Dao** [comment]
kubelet logs on the node:

5月 05 16:10:16 192-168-1-154 kubelet[25348]: Mounting arguments:  /var/lib/kubelet/pods/beeefcfd-3163-11e7-9abf-005056a3fdbf/volumes/kubernetes.io~scaleio/pvc-561b808a-3163-11e7-9abf-005056a3fdbf ext4 [rw defaults]
5月 05 16:10:16 192-168-1-154 kubelet[25348]: Output: mount: can't find /var/lib/kubelet/pods/beeefcfd-3163-11e7-9abf-005056a3fdbf/volumes/kubernetes.io~scaleio/pvc-561b808a-3163-11e7-9abf-005056a3fdbf in /etc/fstab
5月 05 16:10:16 192-168-1-154 kubelet[25348]: E0505 16:10:16.011119   25348 mount_linux.go:408] Could not determine if disk "" is formatted (exit status 1)
5月 05 16:10:16 192-168-1-154 kubelet[25348]: E0505 16:10:16.011151   25348 sio_volume.go:134] scaleio: mount operation failed during setup: exit status 1
5月 05 16:10:16 192-168-1-154 kubelet[25348]: E0505 16:10:16.011282   25348 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/scaleio/beeefcfd-3163-11e7-9abf-005056a3fdbf-pvc-561b808a-3163-11e7-9abf-005056a3fdbf\" (\"beeefcfd-3163-11e7-9abf-005056a3fdbf\")" failed. No retries permitted until 2017-05-05 16:12:16.011248779 +0800 CST (durationBeforeRetry 2m0s). Error: MountVolume.SetUp failed for volume "kubernetes.io/scaleio/beeefcfd-3163-11e7-9abf-005056a3fdbf-pvc-561b808a-3163-11e7-9abf-005056a3fdbf" (spec.Name: "pvc-561b808a-3163-11e7-9abf-005056a3fdbf") pod "beeefcfd-3163-11e7-9abf-005056a3fdbf" (UID: "beeefcfd-3163-11e7-9abf-005056a3fdbf") with: exit status 1

**Comment by kargakis** [comment]
@kubernetes/sig-storage-bugs

**Comment by rootfs** [comment]
@vladimirvivien

**Comment by vladimirvivien** [comment]
@James-Dao 
It appears your node does not have required SDC software installed (or at least the `drv_cfg` binary is not placed in the standard expected location) as indicated by the error log:

```
E0505 07:14:50.804030 1 sio_volume.go:222] scaleio: failed to delete volume sio-e8e5e41b316011e7b3fb00505: fork/exec /opt/emc/scaleio/sdc/bin/drv_cfg: no such file or directory
```
Because the SDC binary is not found on your node, it's causing many other errors

```
E0505 07:14:50.804000 1 sio_client.go:300] scaleio: drv_cfg --query_guid failed: fork/exec /opt/emc/scaleio/sdc/bin/drv_cfg: no such file or directory
E0505 07:14:50.804019 1 sio_mgr.go:216] scaleio: failed to get instanceID: fork/exec 
```

I would recommend `closing` this issue since it is related to ScaleIO environment setup and not Kubernetes.

@rootfs thanks for tagging my name so this can get handled!

**Comment by vladimirvivien** [comment]
@rootfs please close issue as I am unable to do so.  This is a ScaleIO setup issue by the user.

**Comment by jsafrane** [comment]
/close
stupid bot...

**Comment by vladimirvivien** [comment]
@jsafrane lol... thanks for fighting with bot and getting this closed!
