### ISSUE TITLE
Flaky unit test of kubectl

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#45393]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug

**Kubernetes version** (use `kubectl version`):
master branch

**What happened**:

I had seen several similar flaky tests as following, although the PR only change other components. Not sure who's working on it :).

```
Test Failures

k8s.io/kubernetes/pkg/kubectl/cmd/util/openapi TestOpenapi 0.00s
go test -v k8s.io/kubernetes/pkg/kubectl/cmd/util/openapi -run TestOpenapi$
from junit_a9308e5199d66c4eb1553a4ec233c5882b1bfb35_20170504-063126.xml
```

Refer to following link for more info: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45349/pull-kubernetes-unit/29026/

@kubernetes/sig-cli-bugs  ??

**Comment by shiywang** [comment]
Is this dup of https://github.com/kubernetes/kubernetes/issues/45279 ?

**Comment by k82cn** [comment]
> Is this a dup of #45279 ?

Yes, I think so.
