### ISSUE TITLE
hack/update-staging-client-go.sh is pretty much impossible to use

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#45416]
Or I don't know how to do that. It basically demands that I have some obscure list of dependencies in some obscure concrete revisions. I'm already 20 minutes in trying to make it happy and I still can't see the end of it. Can we make it run as a container in a clean repo, so that it can just download whatever it wants, generate what it's asked for and be done with it?

@kubernetes/sig-api-machinery-feature-requests @caesarxuchao

**Comment by liggitt** [comment]
running hack/godep-restore.sh first works for me

**Comment by gmarek** [comment]
Fair point - I'll send a PR that will make the script print this out.

**Comment by xiangpengzhao** [comment]
yeah, running `hack/verify-staging-client-go.sh` first and it tells me to run `hack/godep-restore.sh`, running it and then running `hack/update-staging-client-go.sh` makes my life better.

**Comment by gmarek** [comment]
Right. I just assumed that "Run godep restore" actually means "go get", as usual when updating godeps, not `hack/godep-restore.sh`.

**Comment by gmarek** [comment]
Oh, and I see it's already fixed on the head, so I just was unlucky to had to run it on 1.6 branch.
