### ISSUE TITLE
API version "extensions/v1beta1" isn't supported, only supports API versions ["v1"]

### ISSUE THREAD

**Issue by aelmehra** [kubernetes/kubernetes#45428]
When I try to run kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard-no-rbac.yaml I receive the following error:

API version "extensions/v1beta1" in "https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard-no-rbac.yaml" isn't supported, only supports API versions ["v1"]

kubectl version
Client Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-alpha.0.1464+2bfa9a1f98147c", GitCommit:"2bfa9a1f98147cfdc2e9f4cf50e2c430518d91eb", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-alpha.0.1464+2bfa9a1f98147c", GitCommit:"2bfa9a1f98147cfdc2e9f4cf50e2c430518d91eb", GitTreeState:"clean"}

I am Running Kubernets on a CentOS VM

**Comment by xiangpengzhao** [comment]
I think it's because your kubernetes version is too old...The latest release is 1.6.x
