### ISSUE TITLE
Deployments seems to be not considered to be namesapced (v1.3.5)

### ISSUE THREAD

**Issue by senyan** [kubernetes/kubernetes#45424]
**Kubernetes version** (use `kubectl version`):
1.3.5

**What happened**:

I am using a admin namespace account try to deploy a pod but got the following error:
I0505 12:11:41.735369   47483 round_trippers.go:318] GET https://<hostname>/apis/extensions/v1beta1/namespaces/prod/deployments 403 Forbidden in 1 milliseconds
This seems indicates a get not works. 
kubectl get deployment is not working also. 

My policyfile has:
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user": "admin", "namespace": "prod", "resource": "*", "apigroup": "*", "nonResourcePath": "*"}}

Note that I can deploy other resource types such as ``Secret`` without any problem.

**Comment by senyan** [comment]
To me this is more like a bug and not sure if get fixed in later versions.

**Comment by senyan** [comment]
Turns out to be it is something in my key signing not works correctly.

**Comment by kargakis** [comment]
Doesn't seem like an issue, closing
