### ISSUE TITLE
Errors with swagger generated code

### ISSUE THREAD

**Issue by quasiben** [kubernetes/kubernetes#45420]
In HEAD for release-1.5 (and i think in master as well) the generated code from `v1.json` I believe has some issues with `Content-type` headers.  I think the issue comes down to the function

```python
def select_header_content_type(self, content_types):
    """
    Returns `Content-Type` based on an array of content_types provided.

    :param content_types: List of content-types.
    :return: Content-Type (e.g. application/json).
    """
    if not content_types:
        return 'application/json'

    content_types = list(map(lambda x: x.lower(), content_types))

    if 'application/json' in content_types:
        return 'application/json'
    else:
        return content_types[0]
```

Throughout the code headers are set like the following:

> self.api_client.select_header_content_type(['*/*'])

And this in turn leads to `[...'Content-Type': '*/*'}]`.  My understanding is that this becomes a problem when the code finals reaches `rest.py` and various header inspection routes traffic, none which is for `*/*`.  

There are also issues in the `request` function in `rest.py`.  Namely, the error which shows up:

> swagger_client/rest.py", line 145, in request
        if query_params:
    UnboundLocalError: local variable 'r' referenced before assignment

The actual error is obfuscated (in this case */* is not valid) but the POST doesn't succeed and `r` is not assigned

**Kubernetes version** (use `1.5.1`):

**Environment**:
- **Ubuntu 16.04**:

**What happened**:
Unable to create a namespace

**How to reproduce it** (as minimally and precisely as possible):
```
wget https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/swagger-spec/v1.json
swagger-codegen generate -i v1.json -l python
```

calling `create_namespace` with valid V1Namespace object

**Comment by bliuredhat** [comment]
+1, The same question for me

**Comment by quasiben** [comment]
In the mean time, i've patched `rest.py` with the following:

```python
if headers.get('Content-Type') == '*/*':
    headers['Content-Type'] = 'application/json'

```

**Comment by mml** [comment]
/assign @mbohlool 

@quasiben Can you please re-open this issue in the python-client repo?  Thanks.

**Comment by mbohlool** [comment]
This issue belong to github.com/kubernetes-incubator/client-python repo.

Also, This is an old issue and I believe it is fixed now in swagger codegen and new release of the python client. I am going to close this. Please re-open an issue in the repo if you are still facing this problem.
