### ISSUE TITLE
KUBE_API_ARGS should be trimmed

### ISSUE THREAD

**Issue by screeley44** [kubernetes/kubernetes#4544]
Was trying to enable v1beta3 on the apiserver and had an extra space that I didn't notice.  This space caused the enablement of v1beta3 to fail and would not show in http://<master>:8080/api - if it's easy enough to do, that arguement maybe should be trimmed

**Comment by screeley44** [comment]
forgot to add this in previous comment:

KUBE_API_ARGS="--runtime_config=api/v1beta3 "   <-- notice the space after v1beta3

**Comment by yujuhong** [comment]
@screeley44, it'd be nice if you can submit a PR for this :)

**Comment by screeley44** [comment]
@yujuhong - I'm pretty new to this is there a link to submit PR's (I thought that the way I reported this was a PR).

**Comment by yujuhong** [comment]
PR means a pull request, asking to merge commits into the repository.

If you would like to contribute to kubernetes, you can fork the repository and upload your changes to your own repository. Then, you can create a pull request asking for code review. The process is similar to contributing to open source projects on github.
https://guides.github.com/activities/contributing-to-open-source

**Comment by screeley44** [comment]
@yujuhong - ah, thanks for the clarification, I might give that a try, would be a good learning experience

**Comment by screeley44** [comment]
old issue, closing
