### ISSUE TITLE
What should be used for sharing the volume of StatefulSet between its pods: NFS ou etcd?

### ISSUE THREAD

**Issue by mappedinn** [kubernetes/kubernetes#45451]
I want to deploy a high performance (multi node) database. To do that, StatefulSet will be used.
So, what should be used for sharing the content of the database between the pods of the StatefulSet application? `NFS` could do the work? or `etcd`? 

Thanks,

**Comment by mtanino** [comment]
Hi, This is issue tracker and is not a place to send an open question.
If you need a help to build Kubernetes environment, you need to ask at slack channels or mailing list mentioned in the following troubleshooting page.
https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/

As you mentioned NFS is shared storage and also Gluster and ScaleIO are software defined shared storage. Statefulset requires persistent volume and these shared storages are listed in the following persistent volume list. So I thinks you can choose from them.
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#types-of-persistent-volumes

ETCD is just a key/value store which is used in Kubernetes, it's not a storage.

Thanks,

**Comment by kargakis** [comment]
You can also direct support question in the kubernetes-users mailing list or stackoverflow

https://groups.google.com/forum/#!forum/kubernetes-users
http://stackoverflow.com/questions/tagged/kubernetes

**Comment by mappedinn** [comment]
Sorry for disturbing...
