### ISSUE TITLE
storage-backend should be consistent across all servers

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#45457]
apiserver has storage-backend default to etcd2.  In 1.6, we're hoping to use UAS for additional API functionality, and for new servers the default has been changed to etcd3.

This is bad UX; it ends up where we have to know the default version of etcd in place at the time when the server project was first created (etcd2, 3, 4, 5...).  Not passing any argument will result in a different backend assumption for apiserver than for a UAS.

We should either make etcd2 the default everywhere, or simply make specifying storage-backend mandatory (we could deprecate defaulting of the storage-backend, in our normal process).

**Comment by justinsb** [comment]
cc @pwittrock as I think you're the rare unicorn that does both UX and UAS

**Comment by jagosan** [comment]
/sig api-machinery
/kind enhancement

@justinsb - bug scrub effort trying to categorize.  please add sig label when possible.

**Comment by justinsb** [comment]
Putting in to 1.7 as I believe once we've shipped, the ship has sailed.

**Comment by pwittrock** [comment]
Yeah this is a really bad UX since there is no notification if the wrong default is chosen, requests just hang with interesting log messages.  Can we detect the storage version of storage system we are talking to, and default to that?

**Comment by lavalamp** [comment]
The default etcd container stores a file indicating the etcd version.

User apiservers should NOT be talking directly to the main cluster etcd, and if they are, the admin ought to know exactly what they are doing.

However I think I agree that we should not have changed the default of this flag. I am not sure if changing it back makes this better or twice as bad.

**Comment by justinsb** [comment]
> User apiservers should NOT be talking directly to the main cluster etcd, and if they are, the admin ought to know exactly what they are doing.

@lavalamp  Perhaps this is a separate issue, but this is contrary to what I was told when I proposed having a command that could dump from etcd into our API format.  Did this change?   Why?  This seems not-entirely-real-world-realistic, and likely to push people towards bigger user apiservers than we would otherwise want...

**Comment by lavalamp** [comment]
@justinsb No, this hasn't changed, sorry if I was unclear. UAS IMO should use TPR/CRD (or similar item) for storage.

**Comment by lavalamp** [comment]
I think we decided that the cure is worse than the disease. I like your suggestion of just making the flag mandatory.

**Comment by mml** [comment]
@justinsb is this still relevant?
