### ISSUE TITLE
SharedInformer.Run() should wait for all spawned goroutines to stop

### ISSUE THREAD

**Issue by ash2k** [kubernetes/kubernetes#45454]
This is an improvement/change request.

**What happened**:
`sharedIndexInformer.Run(stopCh <-chan struct{})` (k8s.io/client-go/tools/cache/shared_informer.go) calls `sharedProcessor.run()` and `controller.Run()` which spawn 2 goroutines for each attached listener and 1 goroutine. When `stopCh` is closed, `sharedIndexInformer.Run` returns, not waiting for all goroutines to finish.

**What you expected to happen**:
It'd be great if `SharedInformer.Run()` method waited for all goroutines to finish.
Currently it is hard to write deterministic tests and code that dynamically starts/stops informers and adds listeners.

p.s. Also there is a slight inconsistency in naming - for example `Reflector.Run` / `RunUntil`, `sharedProcessor.run()` start goroutines and return, while other `Run` methods block. Would be great to have `Start` methods that start goroutines (like e.g. informer factories) and return and `Run` methods that block.

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by deads2k** [comment]
If the refactor isn't excessively large, we could entertain it this release.  If it is large, finding a reviewer may take a while.

I don't anticipate this rising to the top of our list.

**Comment by ash2k** [comment]
@deads2k please see the PR. I'm happy to iterate on it if I'm doing something dumb there :)
