### ISSUE TITLE
Pods cant access ServiceIPs/DNS in a fresh setup with kubeadm on ubuntu 16.04

### ISSUE THREAD

**Issue by ZachGoldberg** [kubernetes/kubernetes#45459]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
Yes, I have looked at and followed https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/ and https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/#does-the-service-work-by-ip to no avail

**What keywords did you search in Kubernetes issues before filing this one?** 
---
kubernetes dns failure, kubernetes pods cant acces service IP

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:  Bare Metal via OVH
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Kernel** (e.g. `uname -a`): Linux k8s-06.elenty.com 4.9.0-040900-generic #201612111631 SMP Sun Dec 11 21:33:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: Kubeadm
- **Others**: Flannel

**What happened**:

Kube DNS is running
```
[root@k8s-06 ~]$ kubectl get po --all-namespaces | grep dns
kube-system   kube-dns-3913472980-170fr                   3/3       Running   12         47m
```

Kube DNS has a service IP
```
[root@k8s-06 ~]$ kubectl get svc kube-dns -n kube-system
NAME       CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
kube-dns   10.96.0.10   <none>        53/UDP,53/TCP   46m
```
Kube DNS works from the node itself
```
[root@k8s-06 ~]$ dig google.com @10.96.0.10 +short
216.58.217.174
```
Kube DNS works inside a normal ubuntu docker container
```
[root@k8s-06 ~]$ docker run -ti ubuntu:latest
root@601fa1fe4dfe:/#  apt update && apt install dnsutils
root@601fa1fe4dfe:/# dig google.com @10.96.0.10 +short
216.58.217.174
```
Kube DNS fails inside a pod 
```
[root@k8s-06 ~]$ kubectl describe po kube-dns-3913472980-170fr -n kube-system | grep IP
IP:		10.244.0.11
[root@k8s-06 ~]$ cat ubuntu.yaml
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: default
spec:
  containers:
  - image: ubuntu
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
[root@k8s-06 ~]$ kubectl create -f ubuntu.yaml 
[root@k8s-06 ~]$ kubectl exec -ti ubuntu bash
root@ubuntu:/# apt update && apt install -y dnsutils
0% [Connecting to archive.ubuntu.com] [Connecting to security.ubuntu.com]^C
<hangs>
root@ubuntu:/# cat /etc/resolv.conf 
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local ovh.net
options ndots:5
root@ubuntu:/# echo "nameserver 8.8.8.8" > /etc/resolv.conf
root@ubuntu:/# apt update && apt install dnsutils
<works> … <snip>
root@ubuntu:/# dig google.com @10.244.0.11 +short
216.58.217.174
root@ubuntu:/# dig google.com @10.96.0.10 +short 
<hangs>
```

Iptables output:
```
[root@k8s-06 ~]$ iptables-save | grep dns
-A KUBE-SEP-A7YQ4MY4TZII3JTK -s 10.244.0.11/32 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-MARK-MASQ
-A KUBE-SEP-A7YQ4MY4TZII3JTK -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp" -m tcp -j DNAT --to-destination 10.244.0.11:53
-A KUBE-SEP-VR6VIIG2A6524KLY -s 10.244.0.11/32 -m comment --comment "kube-system/kube-dns:dns" -j KUBE-MARK-MASQ
-A KUBE-SEP-VR6VIIG2A6524KLY -p udp -m comment --comment "kube-system/kube-dns:dns" -m udp -j DNAT --to-destination 10.244.0.11:53
-A KUBE-SERVICES ! -s 10.244.0.0/16 -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SERVICES ! -s 10.244.0.0/16 -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
-A KUBE-SVC-ERIFXISQEP7F7OF4 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-SEP-A7YQ4MY4TZII3JTK
-A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns" -j KUBE-SEP-VR6VIIG2A6524KLY
```

**What you expected to happen**:
This command (ubuntu is a pod) should not hang:
```root@ubuntu:/# dig google.com @10.96.0.10 +short 
<hangs>
```

**How to reproduce it** (as minimally and precisely as possible):
We are setting up kubenertes via kubeadm inside some ansible scripts and can reproduce the issue everytime.  We setup a cluster basically with these steps:
1. install docker from apt and kubernetes from the ppa http://apt.kubernetes.io/ 
2. Run kube-adm specifiying the token, apiserver-advertise-address and pod-network-cidr on the command line
3. Setup flannel from the flannel github page
4. Run the above commands, note the inability to access the service IP

**Anything else we need to know**:
I'm on slack as @zachg in the kubernetes group, feel free to ping me there for realtime back and fourth if that's better than here on github.

**Comment by ipedrazas** [comment]
I'm seeing the same problem in one of my clusters. Which version of Docker are you running?

**Comment by ZachGoldberg** [comment]
```[root@k8s-06 ~]$ docker --version
Docker version 1.12.6, build 78d1802
```

I'm skeptical that it's dockers fault, given that the networking works in a "regular" docker container but doesn't work inside a k8s pod.  I've been wrong before though...

**Comment by jagosan** [comment]
/sig onprem
May not be exactly right, but bug-scrub trying to direct to sigs and this is the best we can come up with...

**Comment by tacy** [comment]
@ZachGoldberg - Kubedns to external dns server need to SNAT, can you share your all nat rules?

**Comment by ZachGoldberg** [comment]
@tacy  can you post the exact command you'd like me to run?  And do you want me to run this in the container or on the node?

**Comment by tacy** [comment]
@ZachGoldberg  Run `iptables -t nat -S` in the node

**Comment by ZachGoldberg** [comment]
Thanks @tacy !  
`iptables -L -t nat
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */
DOCKER     all  --  anywhere            !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
KUBE-POSTROUTING  all  --  anywhere             anywhere             /* kubernetes postrouting rules */
MASQUERADE  all  --  172.17.0.0/16        anywhere            
RETURN     all  --  10.244.0.0/16        10.244.0.0/16       
MASQUERADE  all  --  10.244.0.0/16       !base-address.mcast.net/4 
MASQUERADE  all  -- !10.244.0.0/16        10.244.0.0/16       

Chain DOCKER (2 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain KUBE-MARK-DROP (0 references)
target     prot opt source               destination         
MARK       all  --  anywhere             anywhere             MARK or 0x8000

Chain KUBE-MARK-MASQ (32 references)
target     prot opt source               destination         
MARK       all  --  anywhere             anywhere             MARK or 0x4000

Chain KUBE-NODEPORTS (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  tcp  --  anywhere             anywhere             /* default/riak:protobuf */ tcp dpt:31331
KUBE-SVC-2RBVAYP4HQ2ZOLBX  tcp  --  anywhere             anywhere             /* default/riak:protobuf */ tcp dpt:31331
KUBE-MARK-MASQ  tcp  --  anywhere             anywhere             /* default/testpythonapp:http */ tcp dpt:32088
KUBE-SVC-AMY7B7PZ6WBITGQV  tcp  --  anywhere             anywhere             /* default/testpythonapp:http */ tcp dpt:32088
KUBE-MARK-MASQ  tcp  --  anywhere             anywhere             /* kube-system/kubernetes-dashboard: */ tcp dpt:31822
KUBE-SVC-XGLOHA7QRQ3V22RZ  tcp  --  anywhere             anywhere             /* kube-system/kubernetes-dashboard: */ tcp dpt:31822
KUBE-MARK-MASQ  tcp  --  anywhere             anywhere             /* default/riak:http */ tcp dpt:31710
KUBE-SVC-3ORCTUNYKQ5T4B7C  tcp  --  anywhere             anywhere             /* default/riak:http */ tcp dpt:31710

Chain KUBE-POSTROUTING (1 references)
target     prot opt source               destination         
MASQUERADE  all  --  anywhere             anywhere             /* kubernetes service traffic requiring SNAT */ mark match 0x4000/0x4000

Chain KUBE-SEP-232DQYSHL5HNRYWJ (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.0.7           anywhere             /* kube-system/kube-dns:dns */
DNAT       udp  --  anywhere             anywhere             /* kube-system/kube-dns:dns */ udp to:10.244.0.7:53

Chain KUBE-SEP-2A2QXTEHN656WZVO (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.0.3           anywhere             /* default/riak:http */
DNAT       tcp  --  anywhere             anywhere             /* default/riak:http */ tcp to:10.244.0.3:8098

Chain KUBE-SEP-3LTFWCBDVGHRETKJ (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.0.15          anywhere             /* default/testpythonapp:http */
DNAT       tcp  --  anywhere             anywhere             /* default/testpythonapp:http */ tcp to:10.244.0.15:9000

Chain KUBE-SEP-7TWNYGBHMSXIVXTR (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.0.3           anywhere             /* default/riak:protobuf */
DNAT       tcp  --  anywhere             anywhere             /* default/riak:protobuf */ tcp to:10.244.0.3:8087

Chain KUBE-SEP-A4UL7OUXQPUR7Y7Q (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.0.7           anywhere             /* kube-system/kube-dns:dns-tcp */
DNAT       tcp  --  anywhere             anywhere             /* kube-system/kube-dns:dns-tcp */ tcp to:10.244.0.7:53

Chain KUBE-SEP-A6IGXAN2QDM5SF3E (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.0.16          anywhere             /* default/redis-sentinel: */
DNAT       tcp  --  anywhere             anywhere             /* default/redis-sentinel: */ tcp to:10.244.0.16:26379

Chain KUBE-SEP-ADW3T76PIFB42LT5 (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.0.8           anywhere             /* kube-system/heapster: */
DNAT       tcp  --  anywhere             anywhere             /* kube-system/heapster: */ tcp to:10.244.0.8:8082

Chain KUBE-SEP-D5E3CNQLU3XDZHMZ (2 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.0.0.101           anywhere             /* default/kubernetes:https */
DNAT       tcp  --  anywhere             anywhere             /* default/kubernetes:https */ recent: SET name: KUBE-SEP-D5E3CNQLU3XDZHMZ side: source mask: 255.255.255.255 tcp to:10.0.0.101:6443

Chain KUBE-SEP-DQJVL74SX4CEATOZ (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.0.5           anywhere             /* kube-system/monitoring-influxdb: */
DNAT       tcp  --  anywhere             anywhere             /* kube-system/monitoring-influxdb: */ tcp to:10.244.0.5:8086

Chain KUBE-SEP-IXRCUOUQT2U65IRM (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.0.4           anywhere             /* default/kube-state-metrics:metrics */
DNAT       tcp  --  anywhere             anywhere             /* default/kube-state-metrics:metrics */ tcp to:10.244.0.4:8080

Chain KUBE-SEP-OGTLLHFW6IV2QUSB (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.0.10          anywhere             /* kube-system/monitoring-grafana: */
DNAT       tcp  --  anywhere             anywhere             /* kube-system/monitoring-grafana: */ tcp to:10.244.0.10:3000

Chain KUBE-SEP-OKOQMKLX3J7AFKCH (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.0.3           anywhere             /* default/riak-discovery:transport */
DNAT       tcp  --  anywhere             anywhere             /* default/riak-discovery:transport */ tcp to:10.244.0.3:8098

Chain KUBE-SEP-SRNWXY3QBOE5W2K4 (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.0.14          anywhere             /* default/rabbitmq-etcd: */
DNAT       tcp  --  anywhere             anywhere             /* default/rabbitmq-etcd: */ tcp to:10.244.0.14:4001

Chain KUBE-SEP-WIBNWXTPAZY43XOS (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.0.6           anywhere             /* kube-system/kubernetes-dashboard: */
DNAT       tcp  --  anywhere             anywhere             /* kube-system/kubernetes-dashboard: */ tcp to:10.244.0.6:9090

Chain KUBE-SERVICES (2 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  udp  -- !10.244.0.0/16        10.96.0.10           /* kube-system/kube-dns:dns cluster IP */ udp dpt:domain
KUBE-SVC-TCOU7JCQXEZGVUNU  udp  --  anywhere             10.96.0.10           /* kube-system/kube-dns:dns cluster IP */ udp dpt:domain
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.99.129.82         /* default/riak-discovery:transport cluster IP */ tcp dpt:8098
KUBE-SVC-33ZW7GZRDQKLTKSC  tcp  --  anywhere             10.99.129.82         /* default/riak-discovery:transport cluster IP */ tcp dpt:8098
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.103.194.105       /* kube-system/heapster: cluster IP */ tcp dpt:http
KUBE-SVC-BJM46V3U5RZHCFRZ  tcp  --  anywhere             10.103.194.105       /* kube-system/heapster: cluster IP */ tcp dpt:http
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.100.5.188         /* kube-system/monitoring-grafana: cluster IP */ tcp dpt:http
KUBE-SVC-JRXTEHDDTAFMSEAS  tcp  --  anywhere             10.100.5.188         /* kube-system/monitoring-grafana: cluster IP */ tcp dpt:http
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.107.227.146       /* default/redis-sentinel: cluster IP */ tcp dpt:26379
KUBE-SVC-J5D76RSJYK6KBPWI  tcp  --  anywhere             10.107.227.146       /* default/redis-sentinel: cluster IP */ tcp dpt:26379
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.96.0.1            /* default/kubernetes:https cluster IP */ tcp dpt:https
KUBE-SVC-NPX46M4PTMTKRN6Y  tcp  --  anywhere             10.96.0.1            /* default/kubernetes:https cluster IP */ tcp dpt:https
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.108.121.37        /* default/riak:protobuf cluster IP */ tcp dpt:8087
KUBE-SVC-2RBVAYP4HQ2ZOLBX  tcp  --  anywhere             10.108.121.37        /* default/riak:protobuf cluster IP */ tcp dpt:8087
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.110.186.18        /* default/rabbitmq-etcd: cluster IP */ tcp dpt:4001
KUBE-SVC-O2QHNCFU2OQOOISM  tcp  --  anywhere             10.110.186.18        /* default/rabbitmq-etcd: cluster IP */ tcp dpt:4001
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.105.104.192       /* default/testpythonapp:http cluster IP */ tcp dpt:9000
KUBE-SVC-AMY7B7PZ6WBITGQV  tcp  --  anywhere             10.105.104.192       /* default/testpythonapp:http cluster IP */ tcp dpt:9000
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.106.158.98        /* kube-system/monitoring-influxdb: cluster IP */ tcp dpt:8086
KUBE-SVC-Q6XJQ2I55QTBQCWT  tcp  --  anywhere             10.106.158.98        /* kube-system/monitoring-influxdb: cluster IP */ tcp dpt:8086
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.111.88.94         /* kube-system/kubernetes-dashboard: cluster IP */ tcp dpt:http
KUBE-SVC-XGLOHA7QRQ3V22RZ  tcp  --  anywhere             10.111.88.94         /* kube-system/kubernetes-dashboard: cluster IP */ tcp dpt:http
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.96.0.10           /* kube-system/kube-dns:dns-tcp cluster IP */ tcp dpt:domain
KUBE-SVC-ERIFXISQEP7F7OF4  tcp  --  anywhere             10.96.0.10           /* kube-system/kube-dns:dns-tcp cluster IP */ tcp dpt:domain
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.104.92.20         /* default/kube-state-metrics:metrics cluster IP */ tcp dpt:http-alt
KUBE-SVC-NS7QLRE56ZFFGLS6  tcp  --  anywhere             10.104.92.20         /* default/kube-state-metrics:metrics cluster IP */ tcp dpt:http-alt
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.108.121.37        /* default/riak:http cluster IP */ tcp dpt:8098
KUBE-SVC-3ORCTUNYKQ5T4B7C  tcp  --  anywhere             10.108.121.37        /* default/riak:http cluster IP */ tcp dpt:8098
KUBE-NODEPORTS  all  --  anywhere             anywhere             /* kubernetes service nodeports; NOTE: this must be the last rule in this chain */ ADDRTYPE match dst-type LOCAL

Chain KUBE-SVC-2RBVAYP4HQ2ZOLBX (2 references)
target     prot opt source               destination         
KUBE-SEP-7TWNYGBHMSXIVXTR  all  --  anywhere             anywhere             /* default/riak:protobuf */

Chain KUBE-SVC-33ZW7GZRDQKLTKSC (1 references)
target     prot opt source               destination         
KUBE-SEP-OKOQMKLX3J7AFKCH  all  --  anywhere             anywhere             /* default/riak-discovery:transport */

Chain KUBE-SVC-3ORCTUNYKQ5T4B7C (2 references)
target     prot opt source               destination         
KUBE-SEP-2A2QXTEHN656WZVO  all  --  anywhere             anywhere             /* default/riak:http */

Chain KUBE-SVC-AMY7B7PZ6WBITGQV (2 references)
target     prot opt source               destination         
KUBE-SEP-3LTFWCBDVGHRETKJ  all  --  anywhere             anywhere             /* default/testpythonapp:http */

Chain KUBE-SVC-BJM46V3U5RZHCFRZ (1 references)
target     prot opt source               destination         
KUBE-SEP-ADW3T76PIFB42LT5  all  --  anywhere             anywhere             /* kube-system/heapster: */

Chain KUBE-SVC-ERIFXISQEP7F7OF4 (1 references)
target     prot opt source               destination         
KUBE-SEP-A4UL7OUXQPUR7Y7Q  all  --  anywhere             anywhere             /* kube-system/kube-dns:dns-tcp */

Chain KUBE-SVC-J5D76RSJYK6KBPWI (1 references)
target     prot opt source               destination         
KUBE-SEP-A6IGXAN2QDM5SF3E  all  --  anywhere             anywhere             /* default/redis-sentinel: */

Chain KUBE-SVC-JRXTEHDDTAFMSEAS (1 references)
target     prot opt source               destination         
KUBE-SEP-OGTLLHFW6IV2QUSB  all  --  anywhere             anywhere             /* kube-system/monitoring-grafana: */

Chain KUBE-SVC-NPX46M4PTMTKRN6Y (1 references)
target     prot opt source               destination         
KUBE-SEP-D5E3CNQLU3XDZHMZ  all  --  anywhere             anywhere             /* default/kubernetes:https */ recent: CHECK seconds: 10800 reap name: KUBE-SEP-D5E3CNQLU3XDZHMZ side: source mask: 255.255.255.255
KUBE-SEP-D5E3CNQLU3XDZHMZ  all  --  anywhere             anywhere             /* default/kubernetes:https */

Chain KUBE-SVC-NS7QLRE56ZFFGLS6 (1 references)
target     prot opt source               destination         
KUBE-SEP-IXRCUOUQT2U65IRM  all  --  anywhere             anywhere             /* default/kube-state-metrics:metrics */

Chain KUBE-SVC-O2QHNCFU2OQOOISM (1 references)
target     prot opt source               destination         
KUBE-SEP-SRNWXY3QBOE5W2K4  all  --  anywhere             anywhere             /* default/rabbitmq-etcd: */

Chain KUBE-SVC-Q6XJQ2I55QTBQCWT (1 references)
target     prot opt source               destination         
KUBE-SEP-DQJVL74SX4CEATOZ  all  --  anywhere             anywhere             /* kube-system/monitoring-influxdb: */

Chain KUBE-SVC-TCOU7JCQXEZGVUNU (1 references)
target     prot opt source               destination         
KUBE-SEP-232DQYSHL5HNRYWJ  all  --  anywhere             anywhere             /* kube-system/kube-dns:dns */

Chain KUBE-SVC-XGLOHA7QRQ3V22RZ (2 references)
target     prot opt source               destination         
KUBE-SEP-WIBNWXTPAZY43XOS  all  --  anywhere             anywhere             /* kube-system/kubernetes-dashboard: */
`

**Comment by tacy** [comment]
@ZachGoldberg  You can try add masq rule for kubedns by run command 'iptables -t nat -I POSTROUTING -s 10.244.0.7 -p udp --dport 53 -j MASQUERADE`

**Comment by ZachGoldberg** [comment]
Sweet!!  Progress!   I think that may have fixed it... 

```root@ubuntu:/# nslookup kubernetes.default
Server:		10.96.0.10
Address:	10.96.0.10#53

Non-authoritative answer:
Name:	kubernetes.default.svc.cluster.local
Address: 10.96.0.1
```

Any thoughts on why the rule isn't there automatically?

**Comment by tacy** [comment]
I guess that you need set ip-masq for the flanneld running.

Related to: https://github.com/coreos/flannel/blob/master/Documentation/configuration.md

**Comment by dcbw** [comment]
@ZachGoldberg does setting ip-masq for flannel fix the issue for you?

**Comment by ZachGoldberg** [comment]
@dcbw The replication steps I have provided in this ticket no longer reproduce the issue (aka DNS seems to work).  However my application is still barfing that it can't connect to the hostname.  I'm still debugging now to understand if that's just the problem with my application, or if it's a networking issue with k8s.

**Comment by ZachGoldberg** [comment]
Is there any world in which the ipmasq fix would work for pods on nodes other than the master (where DNS is) but not on pods residing on the master itself?  

I'm seeing some behavior in one of our services which would be explained by that being the case.  I don't yet have hard evidence, still trying to produce that, but whilst I'm banging my head against the wall on the pods that wont come up on the master node I figure'd I would ask and see what the k8s-braintrust thinks.

**Comment by luxas** [comment]
@ZachGoldberg If you think this issue is specific to kubeadm, please reopen in kubernetes/kubeadm. If this is a flannel issue, please move the issue there...
Also this might be related to https://github.com/kubernetes/kubeadm/issues/273?

**Comment by luxas** [comment]
@ZachGoldberg From reading this thread closely, I think this is an issue with flannel.
Basically the request to `10.96.0.10` isn't ever delivered through the overlay network, so no resolving can take place. That also explains why `dig google.com` doesn't work, kube depends on the network to be properly set up and uses kube-dns to provide the IP for that domain as well (but asks 8.8.8.8 or the like for that information internally).

Sorry, but I think this is purely a "flannel doesn't ip-masq things for you" than an issue with kubeadm. You can try to reproduce this using Weave to see if flannel is the bottleneck here.
Reopen if you disagree.

**Comment by Bengrunt** [comment]
Hi there,

For the sake of other people like me stumbling on this issue when trying to deal with the same symptoms on their own fresh kubernetes install.

So I used kubeadm to deploy kubernetes on a single node with flannel. The pods couldn't resolve DNS or even ping it. Upgrading the flannel daemonset to the [fresh 0.9.1 version](https://github.com/coreos/flannel/releases/tag/v0.9.1) seems to fix an iptables related issue. It did the trick for me.

**Comment by zatricky** [comment]
In case it is relevant, symptoms like this also occur if docker is adding its own iptables rules where kube should be managing the rules.

To disable that behaviour, set the "iptables" option to false in your docker config / service unit.

**Comment by amitvashist7** [comment]
It seems like issue still persists with the latest version of kuberneters. 

root@master:~# kubectl get nodes
NAME       STATUS    ROLES     AGE       VERSION
master     Ready     master    1h        v1.10.4
worker01   Ready     <none>    1h        v1.10.4
worker02   Ready     <none>    1h        v1.10.4
root@master:~#


root@master:~# kubectl get pods --all-namespaces
NAMESPACE     NAME                             READY     STATUS    RESTARTS   AGE
default       busybox                          1/1       Running   0          5m
kube-system   canal-8kq57                      3/3       Running   4          1h
kube-system   canal-fl84x                      3/3       Running   3          1h
kube-system   canal-kz6hr                      3/3       Running   3          1h
kube-system   etcd-master                      1/1       Running   1          1h
kube-system   kube-apiserver-master            1/1       Running   3          1h
kube-system   kube-controller-manager-master   1/1       Running   1          1h
kube-system   kube-dns-86f4d74b45-6kvls        3/3       Running   3          1h
kube-system   kube-proxy-7x925                 1/1       Running   1          1h
kube-system   kube-proxy-rdfz8                 1/1       Running   1          1h
kube-system   kube-proxy-vdcfw                 1/1       Running   1          1h
kube-system   kube-scheduler-master            1/1       Running   1          1h
root@master:~#


Kube DNS is running

root@master:~#  kubectl describe po kube-dns-86f4d74b45-6kvls -n kube-system | grep IP
Annotations:    cni.projectcalico.org/podIP=192.168.0.3/32
IP:             192.168.0.3
root@master:~#


Kube DNS has a service IP

root@master:~# kubectl get svc kube-dns -n kube-system
NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
kube-dns   ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP   1h
root@master:~#


Iptables output:

root@master:~#  iptables-save | grep dns
-A KUBE-SEP-4TCKAEJ6POVEFPVW -s 192.168.0.3/32 -m comment --comment "kube-system/kube-dns:dns" -j KUBE-MARK-MASQ
-A KUBE-SEP-4TCKAEJ6POVEFPVW -p udp -m comment --comment "kube-system/kube-dns:dns" -m udp -j DNAT --to-destination 192.168.0.3:53
-A KUBE-SEP-KPHYKKPVMB473Z76 -s 192.168.0.3/32 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-MARK-MASQ
-A KUBE-SEP-KPHYKKPVMB473Z76 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp" -m tcp -j DNAT --to-destination 192.168.0.3:53
-A KUBE-SERVICES ! -s 192.168.0.0/16 -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SERVICES ! -s 192.168.0.0/16 -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
-A KUBE-SVC-ERIFXISQEP7F7OF4 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-SEP-KPHYKKPVMB473Z76
-A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns" -j KUBE-SEP-4TCKAEJ6POVEFPVW
root@master:~#


Pod DNS Output:

root@master:~# kubectl run -i --tty busybox --image=busybox --restart=Never -- sh
If you don't see a command prompt, try pressing enter.
/ #
/ # nslookup default.svc.cluster.local
Server:    10.96.0.10
Address 1: 10.96.0.10
nslookup: can't resolve 'default.svc.cluster.local'

/ # nslookup kubernetes.default
Server:    10.96.0.10
Address 1: 10.96.0.10
nslookup: can't resolve 'kubernetes.default'
/ #

**Comment by ducttapecoder-vt** [comment]
@zatricky Is that on the master, worker, or both?

**Comment by zatricky** [comment]
@ducttapecoder-vt It was both. But also that was a long time ago.
