### ISSUE TITLE
kubectl delete parses cascade incorrectly

### ISSUE THREAD

**Issue by chrisseto** [kubernetes/kubernetes#45461]
**BUG REPORT**

**Kubernetes version**:
```golang
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T23:37:53Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- ~~**Cloud provider or hardware configuration**:~~
- **OS**: macOS 10.12.4
- **Kernel**: Darwin Kernel Version 16.5.0
- ~~**Install tools**~~:
- ~~**Others**~~:

**What happened**:
When running `kubectl delete statefullset NAME --cascade false` the cascade flag is ignored.

**What you expected to happen**:
Either cascade be set to false or an error to be raised.

**How to reproduce it**:
Run `kubectl delete statefulset NAME --cascade false`

**Anything else we need to know**:
The [documentation for deleting statefullsets](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#deleting-statefulsets) uses the same command with an `=`.
This is the first situation I've seen where using an `=` matters.

I realize this may not be an issue with kubectl itself, but the severity is much higher for the kube community.

**Comment by xiangpengzhao** [comment]
This might be by design or an issue of pflag. What I see is that:

- if a flag has a shorthand, you can use it both with or without `=`.
- if a flag doesn't have a shorthand, you can only use it with `=`.

For example:

`--output` has a shorthand `-o`.
```
# kubectl get svc --all-namespaces=true
NAMESPACE   NAME         CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
default     kubernetes   192.168.3.1   <none>        443/TCP   14d
#
# kubectl get svc --all-namespaces=true -o wide
NAMESPACE   NAME         CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE       SELECTOR
default     kubernetes   192.168.3.1   <none>        443/TCP   14d       <none>
# 
# kubectl get svc --all-namespaces=true --output wide
NAMESPACE   NAME         CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE       SELECTOR
default     kubernetes   192.168.3.1   <none>        443/TCP   14d       <none>
# 
# kubectl get svc --all-namespaces=true --output=wide
NAMESPACE   NAME         CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE       SELECTOR
default     kubernetes   192.168.3.1   <none>        443/TCP   14d       <none>
```

`--all-namespaces` doesn't have a shorthand.
```
# kubectl get svc --all-namespaces true
error: a resource cannot be retrieved by name across all namespaces
# 
# kubectl get svc --all-namespaces=true
NAMESPACE   NAME         CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
default     kubernetes   192.168.3.1   <none>        443/TCP   14d
```

cc @adohe

**Comment by suyogbarve** [comment]
@eparis @fabianofranz 
updated version of pflag also resolves this issue. It supports both --long-flag=true and -l true

**Comment by kargakis** [comment]
Note that --cascade=false wasn't working correctly until recently for `delete` and that should be fixed by https://github.com/kubernetes/kubernetes/pull/45661

**Comment by suyogbarve** [comment]
@kargakis if you can assign it to me, I will track and update after https://github.com/spf13/pflag/pull/130 is available

**Comment by eparis** [comment]
I do not believe a change to pflag is going to 'fix' anything here. Bool flags simply can not take a space.  (Not flag with a NoOptDefVal can take a space)

The only fix I can think here is that the command should fail if args contains a word it doesn't understand. In this case 'false' is parsed as an arg....

**Comment by suyogbarve** [comment]
@eparis : thanks; I made some misinterpretations, below tests confirms what you said
 
go run ./45461/booltest.go echo --c1=false -b=false xxxxx
value of b1 flag:  false
value of c1 flag:  false
Print args: xxxxx

go run ./45461/booltest.go echo --c1 false -b false xxxxx
value of b1 flag:  true
value of c1 flag:  true
Print args: false false xxxxx

**Comment by suyogbarve** [comment]
@eparis : Looks like it is not possible to come up with generic solution for this
>create-things --z-approach false a b
While expected behavior would be to create "a" and "b" ( following NOT z-approach)
Result will be creation of "a" , "b" and "false" (following z-approach)
since a, b .... are just random values it is hard determine if "false" is yet another value.

flag with NoOptDefVal is causing ambiguity in such scenarios.
