### ISSUE TITLE
Shall we add resource kernel-memory limit ？

### ISSUE THREAD

**Issue by fzu-huang** [kubernetes/kubernetes#45476]
We see kernel memory cgroup is not setting, which means `default` to `No Account` in kubernetes, Limit kernel memory will be useful when many containers are running on one machine. New process will be prevented to create when kernel memory usage is too high.

There are description about kernel memory in cgroup doc:

Because the "kmem" counter is fed to the main user counter, kernel memory can
never be limited completely independently of user memory. Say "U" is the user
limit, and "K" the kernel limit. There are three possible ways limits can be
set:

    U != 0, K = unlimited:
    This is the standard memcg limitation mechanism already present before kmem
    accounting. Kernel memory is completely ignored.

    U != 0, K < U:
    Kernel memory is a subset of the user memory. This setup is useful in
    deployments where the total amount of memory per-cgroup is overcommited.
    Overcommiting kernel memory limits is definitely not recommended, since the
    box can still run out of non-reclaimable memory.
    In this case, the admin could set up K so that the sum of all groups is
    never greater than the total memory, and freely set U at the cost of his
    QoS.
    WARNING: In the current implementation, memory reclaim will NOT be
    triggered for a cgroup when it hits K while staying below U, which makes
    this setup impractical.

    U != 0, K >= U:
    Since kmem charges will also be fed to the user counter and reclaim will be
    triggered for the cgroup for both kinds of memory. This setup gives the
    admin a unified view of memory, and it is also useful for people who just
    want to track kernel memory usage.

**Comment by cmluciano** [comment]
@kubernetes/sig-node-feature-requests

**Comment by vishh** [comment]
Not in the near future. Limiting kernel memory can introduce failure modes that are not yet well understood. To begin with, I think we should add support for monitoring kernel memory usage.

**Comment by aermakov-zalando** [comment]
Considering that kernel memory usage is not limited or tracked in any way, a slowloris-like attack on one of the applications could use much more memory than was provisioned for it just with the socket buffers. Moreover, even if `limits.memory` is set, it won't result in an OOM kill of the offending application, but a random eviction of other applications. Is there a suggested way of protecting against this?

**Comment by zq-david-wang** [comment]
Limiting kernel memory usage may help preventing a rouge process spawn  way too many threads causing the host out of resources
