### ISSUE TITLE
Add a chaos monkey test.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#4548]
From what I grok in the kube-controller-manager there are a series of time based loops to check different aspects of the system (Node Health, Replication Controllers, and Quota).  

Ideally a chaos monkey test would kill nodes and evaluate time to recover, and death spiral avoidance.

**Comment by derekwaynecarr** [comment]
kill api-server, etcd or actual nodes?

**Comment by derekwaynecarr** [comment]
This is why we need to make sure kube-apiserver has a restart policy in systemd unit files if it doesn't already.

Same with etcd.

**Comment by jayunit100** [comment]
By definition of *chaos monkey* i think this sort of test should support killing anything, and should maybe default to something as simple as just killing containers.

**Comment by jayunit100** [comment]
Actually - take that back - maybe this test should simply cause chaos which is only possible by launching a kubernetes workflow.  its outside the scope of kubernetes to build a generic chaos monkey.

**Comment by timothysc** [comment]
Umm this is still outstanding, I don't believe this is done.

**Comment by fejta** [comment]
Thanks for reopening!

Multiple quarters elapsed without anyone making progress. I closed this class of bug because I want to bring attention to the ones that are still interesting to fix.

I removed the test-infra tag because it is about adding test coverage.

**Comment by timothysc** [comment]
Closing this as there are a bunch of ecosystem tools that do this now-a-days.  

Thank you internetz!!
