### ISSUE TITLE
kubectl: insecure-skip-tls-verify doesn't work when using an http proxy

### ISSUE THREAD

**Issue by fschuh** [kubernetes/kubernetes#45486]
---

**BUG REPORT**

**Kubernetes version** (use `kubectl version`): tested on both 1.6.2 and 1.5.3

**Environment**:
- **Cloud provider or hardware configuration**: Cluster is on Amazon AWS, kubectl is running on Docker-Toolbox in Windows (Docker version 17.04.0-ce)
- **OS** (e.g. from /etc/os-release): Alpine Linux 3.5
- **Kernel** (e.g. `uname -a`): Linux 46c5dc4c327e 4.4.66-boot2docker #1 SMP Fri May 5 20:44:25 UTC 2017 x86_64 Linux

**What happened**:
We have an HTTP proxy that has a whitelist of CAs, and won't accept self-signed certificates.
When using kubectl through this proxy to connect to our AWS cluster, it fails even though we set `insecure-skip-tls-verify` to true in our kubeconfig file.

`kubectl version` had the following output:

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc",
Platform:"linux/amd64"}
Error from server (InternalError): an error on the server ("ssl_server_cert_untrusted_issuer: Your request contacted a host which presented a certificate signed by an untrusted issuer.") has prevented the request from
succeeding
```

**What you expected to happen**:
kubectl should connect to our cluster successfully.

**How to reproduce it** (as minimally and precisely as possible):
- Set your `HTTP_PROXY` environment variable to the address of your proxy
- Set `insecure-skip-tls-verify` to true in your cluster entry in kubeconfig (and remove the certificate-authority-data field)
- Call `kubectl version`

**Anything else we need to know**:
If we don't use a proxy, kubectl connects to our cluster as expected.
This is the output of `kubectl version` without a proxy:
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc",
Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc",
Platform:"linux/amd64"}
```

If instead we try to use our self-signed certificate to connect to our cluster using this proxy (with `insecure-skip-tls-verify` set to false), this is the output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc",
Platform:"linux/amd64"}
Unable to connect to the server: x509: certificate signed by unknown authority
```

It would be nice if kubectl had a flag to ignore the error returned by the proxy and still proceed to connect to the cluster (such feature exists in many http libraries like libcurl).

**Comment by b0rey** [comment]
The same problem

**Comment by bcaton85** [comment]
Was there any update on this? Currently having the same issue.

**Comment by jiridanek** [comment]
@bcaton85 This worked in October 2019, according to

* https://github.com/kubernetes/kubectl/issues/743

and it works for me now in 2024.

Best to try again, and if anything breaks, open a new issue and write down precise versions of components there.
