### ISSUE TITLE
Determine the mutability story for PodPreset

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#45499]
Currently the `PodPreset` resource is immutable. It cannot be altered (except for things like labels and annotations, like any other k8s resource) once it is created. This was a trade-off we made to:

1.    Avoid thinking through the complexities of updating such an object
2.    Avoid backing ourselves into backward compatibility expectations we would regret in the future

I think it should be mutable at some point in the future. There are a number of entanglements with basically every controller that creates pods that will need to be figured out:

1.    What are the user's expectations when they create a replicaset and then create a pod preset that matches that replica set's pod template's labels?
2.    Same as (1) for replication controller, deployment (the biggest challenge, probably), stateful set, jobs, cron, etc.

I think for the time being, the answer should be, if you want to change a part of a binding, delete that binding, and recreate it in the state you want it to be in. You'll be responsible for ensuring that your controllers recreate pods if they need to. I realize this is not a great experience - which is part of why this resource is alpha right now :)

I would expect as a user that when I updated a `PodPreset` that pods managed by a `Deployment` would be redeployed.  In OpenShift, we have a notion of deployment triggers that will result in a new deployment occurring.  The linkage between PodPresets and deployments is a good candidate to be represented by a deployment.  There are similarities here to the problem of redeploying when a configmap or secret referenced by a deployment changes (see #43112 and https://github.com/kubernetes/kubernetes/pull/31701)

**Comment by pmorie** [comment]
See: https://github.com/kubernetes/kubernetes/issues/45499

**Comment by k82cn** [comment]
it seems more about controllers instead of scheduler :).

/cc @kubernetes/sig-cluster-lifecycle-feature-requests
