### ISSUE TITLE
Remove cyclic deps

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#45498]
Currently we have cyclic deps of:
- Heapster
- metrics API.

cc @lavalamp @DirectXMan12 

ref #45176

**Comment by DirectXMan12** [comment]
Heapster should be solvable by switching the legacy API files to use the type definitions from the non-legacy API directories in `k8s.io/metrics`.

Solving the cyclic deps for the metrics API is already in progress between me and @caesarxuchao (see https://github.com/kubernetes/kubernetes/pull/45384 and a few others).

**Comment by caesarxuchao** [comment]
I have some local changes that moved some heapster packages to the third_party/forked to avoid the cycle. I'll share more soon.

**Comment by caesarxuchao** [comment]
@piosz i moved https://github.com/kubernetes/kubernetes/blob/master/vendor/k8s.io/heapster/metrics/apis/metrics/v1alpha1/types.go to third_party/forked, do you think that's acceptable?

I'm working on move all k8s API types to a separate repo. We also want to get rid of staging/ and develop in the repos. After these two are done, we can then vendor heapster in the normal way. At that time, if there is a change in k8s API that break heapster, we need to propagate the changes in 3 steps:
1. make the breaking change to the k8s API in the repo k8s.io/api
2. fix heapster, update the vendored version of k8s.io/api in heapster
3. fix kubernetes, update the vendored version of k8s.io/api and k8s.io/heapster in kubernetes.

**Comment by DirectXMan12** [comment]
Ideally, we shouldn't be vendoring Heapster at all.  Assuming people feel the aggregator is ready, in 1.7, we should just get rid of the legacy client entirely, and use Heapster in API server mode (so the types come from `k8s.io/metrics`), and go through the aggregator.

**Comment by caesarxuchao** [comment]
@lavalamp @cheftako regarding running heapster and metrics via the aggregator ^

**Comment by piosz** [comment]
@caesarxuchao thanks for handling this.

I'm working on introducing metrics-server https://github.com/kubernetes/features/issues/271 in 1.7 which will be a replacement for Heapster serving the mentioned API. The metrics-server will be available via the aggregator.

Instead of moving Heapster to third_party/forked, we can use this deps https://github.com/kubernetes/metrics/blob/master/pkg/apis/metrics/v1alpha1/types.go.

**Comment by caesarxuchao** [comment]
Ah, Right. I noted they are both called metrics and both are v1alpha1 but never bothered to check if they are the same thing.

**Comment by piosz** [comment]
AFAIR this was just copy/paste. @DirectXMan12 to confirm

**Comment by DirectXMan12** [comment]
Yeah, they're effectively copy-paste.  The version in `k8s.io/metrics` contains updated protobuf annotations, etc, but they should be JSON-compatible.

**Comment by liggitt** [comment]
is this resolved?

**Comment by piosz** [comment]
Yes. The API is defined in staging directory.
