### ISSUE TITLE
Centralize api resource path construction logic

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#4549]
I notice that people are building URL paths in multiple places, and that our URLs have gotten more complex (namespace is optional except when it's not) and will get even more complex soon (maybe you can add /status at the end).

Therefore, instead of passing name and namespace around and causing a bunch of logic about namespaces to be repeated in many places, I'd like one piece of code that knows how to construct our URL paths.

Conceptually, we'd then pass around a group of attributes (name, namespace, uid, resource name, ?more?) to identify an object. In practice we could use something like this:

```go
type ObjectPath struct {
  Namespace string // must be "" or != "" depending on Resource
  Name string
  UID api.UID // when implemented
  Resource string
  StatusOnly bool // maybe?
}

// returns true if o has enough fields set to construct a path
func (o ObjectPath) IsCompletelySpecified() bool {}

// constructs a url path
func (o ObjectPath) Path() (string, error) {}

// parses a path (this code already exists in pkg/apiserver/handlers.go)
func ParsePath(path string) (ObjectPath, error) {}
```

And then in our client package we should stop taking "name" and instead take one of these objects. And then we can lose the "Namespacers".

Then we can test this code in one place.

Thoughts?

@smarterclayton @derekwaynecarr @quinton-hoole-google @erictune

**Comment by bgrant0607** [comment]
ObjectPath looks a lot like ObjectReference.

**Comment by smarterclayton** [comment]
----- Original Message -----
> I notice that people are building URL paths in multiple places, and that our
> URLs have gotten more complex (namespace is optional except when it's not)
> and will get even more complex soon (maybe you can add /status at the end).
> 
> Therefore, instead of passing name and namespace around and causing a bunch
> of logic about namespaces to be repeated in many places, I'd like one piece
> of code that knows how to construct our URL paths.
> 
> Conceptually, we'd then pass around a group of attributes (name, namespace,
> uid, resource name, ?more?) to identify an object. In practice we could use
> something like this:
> 
> ```go
> type ObjectPath struct {
>   Namespace string // must be "" or != "" depending on Resource
>   Name string
>   UID api.UID // when implemented
>   Resource string
>   StatusOnly bool // maybe?

Status is just one example, "SubResource" or "SubPath" is the generic.  How do we build a URL to a proxy or watch?  We'd need "Prefix" or "VerbPath" as well.

> }
> 
> // returns true if o has enough fields set to construct a path
> func (o ObjectPath) IsCompletelySpecified() bool {}
> 
> // constructs a url path
> func (o ObjectPath) Path() (string, error) {}
> 
> // parses a path (this code already exists in pkg/apiserver/handlers.go)
> func ParsePath(path string) (ObjectPath, error) {}
> ```
> 
> And then in our client package we should stop taking "name" and instead take
> one of these objects. And then we can lose the "Namespacers".

Hrm - the assumption is the client already knows Resource and SubResource (depending on the method you're going to invoke).  So namespace is required, UID is optional, and name is required.  Doesn't seem like that simplifies client logic much to take an object vs namespace/name until we have UID (and shouldn't UID be a different call anyway?)  We probably also have to consider how we'd retrieve a historical version - that's going to include the ResourceVersion.

Where would we construct that object and pass it around?  Getting it from an event referenc?  I can definitely agree the generic reference -> lookup is relevant.

**Comment by smarterclayton** [comment]
Maybe we just need to have ObjectReference -> link and Object -> ObjectReference?  RESTMapper can do bits of this (its what does kind to resource).

I think sub resource is a special case, where generally self links will never have sub resources, instead its' a verb variant on an object (you want to GET the Status sub resource of Pod Foo in namespace Bar)

----- Original Message -----

**Comment by derekwaynecarr** [comment]
I think if we are building links on server whatever we do must be RESTMapper aware.

I guess I look at this the other way and wonder what area is manually building links that should be using a client.Interface instead?  I would prefer we push client.interface usage in those areas first.

**Comment by derekwaynecarr** [comment]
@lavalamp can we just move offenders to take client.Interface?  What areas are you seeing bad behavior that most bug you?

**Comment by lavalamp** [comment]
Hm, maybe the path generation already exists, too: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/resthandler.go#L52

**Comment by lavalamp** [comment]
I think this is better than it was when I started the issue, and probably not bad enough to justify extensive changes at the moment.
