### ISSUE TITLE
Kubelet fail when openstack certificate is expired

### ISSUE THREAD

**Issue by vasartori** [kubernetes/kubernetes#45502]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`): v1.5.7

**Environment**:
- **Cloud provider or hardware configuration**: openstack
- **OS** (e.g. from /etc/os-release): Container Linux by CoreOS 1353.7.0
- **Kernel** (e.g. `uname -a`): 4.9.24-coreos
- **Install tools**:
- **Others**:

**What happened**: When the api certificate  (nova, keystone....) of Openstack comes invalid (eg. expired, revoked) Kubelet fail, and the node status are "NotReady"
Kubelet logs:

May 08 13:46:37 kubernetes-development-master-1 kubelet[10978]: W0508 13:46:37.520984   10978 openstack_instances.go:75] Failed to find compute flavors: Get https://nova.br-xxx.xxx.xxx.xxx:8774/v2/40c28cc7a85b4dba9608ecc1bcdb5f06/flavors/detail: x509: certificate has expired or is not yet valid

**What you expected to happen**:
Kubelet checks if the requested resource really needs to use openstack API.

**How to reproduce it** (as minimally and precisely as possible):
Put a invalid certificate on nova;
Try schedule a simple pod (who don't use openstack API)

**Anything else we need to know**:

**Comment by idvoretskyi** [comment]
cc @kubernetes/sig-openstack-bugs

**Comment by dims** [comment]
I'd say failing early is a feature and reduces heart burn trying to hunt for a warning in the logs later. no? :)
