### ISSUE TITLE
Document etcd supported versions and supported transitions (matrix?)

### ISSUE THREAD

**Issue by caseydavenport** [kubernetes/kubernetes#45506]
**Kubernetes version** (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Vagrant
- **OS** (e.g. from /etc/os-release): CoreOS
- **Kernel** (e.g. `uname -a`):
```
Linux k8s-master 4.7.3-coreos-r2 #1 SMP Sun Jan 8 00:32:25 UTC 2017 x86_64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz GenuineIntel GNU/Linux
```

**What happened**:

I deleted a Namespace and did not receive a DELETED event.

**What you expected to happen**:

I would expect and event with `"type": "DELETED"` indicating the deletion of the Namespace.

**How to reproduce it** (as minimally and precisely as possible):

1) Watch the API:
```
curl http://172.18.18.101:8080/api/v1/namespaces?watch=true
```

2) Create a new namespace:
```
kubectl create ns test-ns
```

and see the following (expected) events:

```
{"type":"ADDED","object":{"kind":"Namespace","apiVersion":"v1","metadata":{"name":"test-ns","selfLink":"/api/v1/namespacestest-ns","uid":"cb91df4b-341b-11e7-b75f-080027699053","resourceVersion":"2412","creationTimestamp":"2017-05-08T18:26:04Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}}
```

3) Delete the namespace
```
kubectl delete ns test-ns
```

Two MODIFIED type events are produced, but no DELETED event
```
{"type":"MODIFIED","object":{"kind":"Namespace","apiVersion":"v1","metadata":{"name":"test-ns","selfLink":"/api/v1/namespacestest-ns","uid":"cb91df4b-341b-11e7-b75f-080027699053","resourceVersion":"2513","creationTimestamp":"2017-05-08T18:26:04Z","deletionTimestamp":"2017-05-08T18:27:21Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Terminating"}}}
{"type":"MODIFIED","object":{"kind":"Namespace","apiVersion":"v1","metadata":{"name":"test-ns","selfLink":"/api/v1/namespacestest-ns","uid":"cb91df4b-341b-11e7-b75f-080027699053","resourceVersion":"2526","creationTimestamp":"2017-05-08T18:26:04Z","deletionTimestamp":"2017-05-08T18:27:21Z"},"spec":{},"status":{"phase":"Terminating"}}}
```

4) Re-create a Namespace with the same name:
```
kubectl create ns test-ns
```

This time, no ADDED event is generated, only a MODIFIED

```
{"type":"MODIFIED","object":{"kind":"Namespace","apiVersion":"v1","metadata":{"name":"test-ns","selfLink":"/api/v1/namespacestest-ns","uid":"2eef8952-341c-11e7-b75f-080027699053","resourceVersion":"2636","creationTimestamp":"2017-05-08T18:28:50Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}}
```

**Anything else we need to know**:

This appears to be a regression in behavior from the Kubernetes v1.5.x series.  The above set of commands produces the following output when running on k8s v1.5:

```
{"type":"ADDED","object":{"kind":"Namespace","apiVersion":"v1","metadata":{"name":"test-ns","selfLink":"/api/v1/namespacestest-ns","uid":"a8582fb1-341c-11e7-ade2-080027699053","resourceVersion":"109","creationTimestamp":"2017-05-08T18:32:14Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}}
{"type":"MODIFIED","object":{"kind":"Namespace","apiVersion":"v1","metadata":{"name":"test-ns","selfLink":"/api/v1/namespacestest-ns","uid":"a8582fb1-341c-11e7-ade2-080027699053","resourceVersion":"121","creationTimestamp":"2017-05-08T18:32:14Z","deletionTimestamp":"2017-05-08T18:32:21Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Terminating"}}}
{"type":"MODIFIED","object":{"kind":"Namespace","apiVersion":"v1","metadata":{"name":"test-ns","selfLink":"/api/v1/namespacestest-ns","uid":"a8582fb1-341c-11e7-ade2-080027699053","resourceVersion":"131","creationTimestamp":"2017-05-08T18:32:14Z","deletionTimestamp":"2017-05-08T18:32:21Z"},"spec":{},"status":{"phase":"Terminating"}}}
{"type":"DELETED","object":{"kind":"Namespace","apiVersion":"v1","metadata":{"name":"test-ns","selfLink":"/api/v1/namespacestest-ns","uid":"a8582fb1-341c-11e7-ade2-080027699053","resourceVersion":"132","creationTimestamp":"2017-05-08T18:32:14Z","deletionTimestamp":"2017-05-08T18:32:21Z"},"spec":{},"status":{"phase":"Terminating"}}}
{"type":"ADDED","object":{"kind":"Namespace","apiVersion":"v1","metadata":{"name":"test-ns","selfLink":"/api/v1/namespacestest-ns","uid":"b30cce84-341c-11e7-ade2-080027699053","resourceVersion":"150","creationTimestamp":"2017-05-08T18:32:32Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}}
```

On 1.6 this appears to be affecting all api groups / types that I've tried (Pods, Namespaces, NetworkPolicy, Deployments)

**Comment by freehan** [comment]
@caesarxuchao @lavalamp

**Comment by shettyg** [comment]
The behavior for me was that a 'kubectl get pods' would show nothing after a pod delete event, but you would not get the DELETED event. 

If you restart kube-apiserver, the DELETED event would then come.  So there is something wonky going on.

The problem went away for me after upgrading the CNI plugin to 0.5.2 and starting kubelet with --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin/.

Also, restarted my etcd v3 cluster.

Since this bug is with namespaces, it is likely that it has really nothing to do with CNI.

**Comment by caesarxuchao** [comment]
How long had you waited for the DELETE? After you sent a deletion request, a controller is going to delete all the objects in that namespace before deleting the namespace itself, so the deletion could take long time.

**Comment by caseydavenport** [comment]
@caesarxuchao I waited until the Namespace no longer showed up in `kubectl get ns`, plus a bit more.

Additionally, I'm seeing this issue with other types which don't have that behavior (e.g. Deployments)

**Comment by caesarxuchao** [comment]
Deployments will go through a garbage collection of its replcasets and pods before gets deleted, so they are similar.

But i agree that the DELETE event should had arrived if the ns or deployment no longer showed up in `kubectl get`.

**Comment by caseydavenport** [comment]
Yep I mis-spoke on my first comment and edited to reflect - I tested this with a simple Pod as well, and NetworkPolicy.

**Comment by caseydavenport** [comment]
@shettyg I'll see if I can reproduce anything from those steps.  I haven't yet dug into any logs, so hopefully I can find something.

FWIW I was running this apiserver against an etcdv2 cluster.

This feels like a pretty serious bug to me in that any controllers which use DELETED events will stop functioning as expected.

**Comment by liggitt** [comment]
Given that many many controllers use deleted events, I am surprised by this

**Comment by caseydavenport** [comment]
I've taken a look at the apiserver logs and noticed that each time I delete an object (in this case a Service) I see the following error logs produced:

```
May 08 22:00:10 k8s-master kube-apiserver[1506]: E0508 22:00:10.522203    1506 reflector.go:363] k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.go:215: expected type *api.Service, but watch event object had type <nil>
May 08 22:00:10 k8s-master kube-apiserver[1506]: E0508 22:00:10.524191    1506 reflector.go:363] k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.go:215: expected type *api.Endpoints, but watch event object had type <nil>
```

I've also verified that the kube-proxy thinks that deleted Services still exist, despite not being able to query them via kubectl.

**Comment by caseydavenport** [comment]
> Given that many many controllers that are exercised by e2e tests use deleted events, I am surprised by this

I was also surprised, but then wondered how many of the e2e tests actually check that DELETE was executed on properly.  For example, kube-proxy could leave iptables rules around for a long time after a Service deletion and you might just not notice because new Services continue to work despite the old iptables rules lying around, and nothing in the tests is asserting that the old Service stopped working.

**Comment by xiangpengzhao** [comment]
FYI, in the below issue, created event was missing.

#26911

>When watching events in global namespace (/v1/events?watch=true) no create event is received for new namespaces. Subsequent events for resources created in these new namespaces are received correctly.

@caseydavenport @jimmidyson

**Comment by liggitt** [comment]
`/v1/events?watch=true` is watching the Event object... creating a new namespace doesn't record Event objects.

**Comment by liggitt** [comment]
I cannot recreate with etcd2 or etcd3 on v1.6.2. Following the steps above, I see:

```
{"type":"ADDED","object":{"kind":"Namespace","apiVersion":"v1","metadata":{"name":"foo","selfLink":"/api/v1/namespacesfoo","uid":"c384bdd5-34c6-11e7-9133-acbc32c1ca87","resourceVersion":"96","creationTimestamp":"2017-05-09T14:49:54Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}}
{"type":"MODIFIED","object":{"kind":"Namespace","apiVersion":"v1","metadata":{"name":"foo","selfLink":"/api/v1/namespacesfoo","uid":"c384bdd5-34c6-11e7-9133-acbc32c1ca87","resourceVersion":"104","creationTimestamp":"2017-05-09T14:49:54Z","deletionTimestamp":"2017-05-09T14:49:57Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Terminating"}}}
{"type":"MODIFIED","object":{"kind":"Namespace","apiVersion":"v1","metadata":{"name":"foo","selfLink":"/api/v1/namespacesfoo","uid":"c384bdd5-34c6-11e7-9133-acbc32c1ca87","resourceVersion":"109","creationTimestamp":"2017-05-09T14:49:54Z","deletionTimestamp":"2017-05-09T14:49:57Z"},"spec":{},"status":{"phase":"Terminating"}}}
{"type":"DELETED","object":{"kind":"Namespace","apiVersion":"v1","metadata":{"name":"foo","selfLink":"/api/v1/namespacesfoo","uid":"c384bdd5-34c6-11e7-9133-acbc32c1ca87","resourceVersion":"110","creationTimestamp":"2017-05-09T14:49:54Z","deletionTimestamp":"2017-05-09T14:49:57Z"},"spec":{},"status":{"phase":"Terminating"}}}
```

**Comment by liggitt** [comment]
@caseydavenport can you provide your full apiserver invocation, including all flags/options?

**Comment by caseydavenport** [comment]
@liggitt I'm starting it as a systemd unit with the following options:

```
ExecStart=/opt/bin/kube-apiserver \
        --allow-privileged=true \
        --etcd-servers=http://$private_ipv4:2379 \
        --runtime-config=extensions/v1beta1=true,extensions/v1beta1/networkpolicies=true \
        --insecure-bind-address=0.0.0.0 \
        --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota \
        --advertise-address=$private_ipv4 \
        --service-cluster-ip-range=10.100.0.0/24 \
        --logtostderr=true
```

**Comment by liggitt** [comment]
if you're running kube1.6 against an etcd2 server, don't you need to specify --storage-backend=etcd2?

**Comment by liggitt** [comment]
> The behavior for me was that a 'kubectl get pods' would show nothing after a pod delete, but you would not get the DELETED event for the watcher.

@shettyg it is possible the pod was not yet deleted... `kubectl get` hides terminated but not deleted pods by default:
```
--show-all=false: When printing, show all resources (default hide terminated pods.)
```

**Comment by caseydavenport** [comment]
@liggitt welp.  I think the missing `--storage-backend=etcd2` option was causing the problem.

Initial tests show that I get the expected events after adding that flag.  Interesting that I didn't see this issue manifest itself: https://github.com/kubernetes/kubernetes/issues/43634

Seems like in general the apiserver isn't doing a great job of reporting that it's misconfigured in these scenarios.

**Comment by liggitt** [comment]
what specific version of etcd2 are you running against? when I try to run a 1.6.2 server against 2.3.7 without specifying the storage backend, the server doesn't come up at all.

**Comment by caseydavenport** [comment]
@liggitt so, oddly enough I think the etcd cluster version in the scripts I was using has changed without me realizing, so my earlier comment about etcdv2 is no longer correct.

```
$ curl http://localhost:2379/version
{"etcdserver":"3.0.10","etcdcluster":"3.0.0"}
```

That said, I've verified a few times now that in the cluster I'm using the `--storage-backend=etcd2` option makes the difference.

**Comment by liggitt** [comment]
interesting, looks like etcd 3.0.11 added the ability to the v3 API to get the previous version of an etcd value on deletion (https://github.com/coreos/etcd/pull/5880)

the v2 etcd API obtained the previous value a different way

that means that the v3 etcd API with etcd 3.0.10 or earlier will fail to send deletion events (the `expected type *api.Service, but watch event object had type <nil>` error you saw)

**Comment by liggitt** [comment]
that means the etcd3 storage backend client should do a hard check to make sure we meet the minimum etcd version requirements, or the cluster will be in a really bad state.

**Comment by liggitt** [comment]
`kube::etcd::validate` in the kube utility scripts currently requires the minimum version to be 3.0.17... not sure what the requirement is based on though

**Comment by liggitt** [comment]
@hongchaodeng @wojtek-t @mml can you look at documenting/enforcing the minimum etcd3 server version?

**Comment by hongchaodeng** [comment]
Original issue: https://github.com/kubernetes/kubernetes/issues/33653

Needs etcd version >= 3.0.12

**Comment by hongchaodeng** [comment]
Isn't there any compatibility matrix between components?

**Comment by liggitt** [comment]
I couldn't easily find one, and it seems like the etcd3 client that kubernetes sets up should ensure it is able to work properly

**Comment by hongchaodeng** [comment]
I agree that it should be ensured.
It's already a mistake that no such check existed during that version upgrade.
A remedy we could do is to provide a compatibility matrix so that there is some guide for users to follow.

**Comment by lavalamp** [comment]
Is this the same as the error @smarterclayton found where we broke the delete message on filtered watches?

**Comment by hongchaodeng** [comment]
To extend the topic, is there any plan to upgrade to etcd 3.1 as minimum version? The PrevValue feature was backported from 3.1 branch anyway.

**Comment by liggitt** [comment]
> Is this the same as the error @smarterclayton found where we broke

No, this is us depending on a feature that only exists in 3.0.12 and up

**Comment by mml** [comment]
We should document which versions we support and which transitions between versions are automatically supported.  I'll re-purpose this issue to clarify that.

**Comment by liggitt** [comment]
I think we need to do more than document... a cluster can actually start against etcd 3.0.10 just well enough to start using it, and then exhibits really odd failure modes when deletion events aren't delivered properly. c.f. https://github.com/kubernetes/kubernetes/issues/46652

**Comment by mml** [comment]
As long as there a flag to disable any fancy version-compatibility-checking
behavior, I guess that's OK.  Alternatively, is there a way to interrogate
etcd about capabilities instead of version numbers?

In either case, developers and admins need a way to disable or tweak
anything that will try to use baked-in smarts to fail to start.

**Comment by lavalamp** [comment]
Kicking this out of the milestone because it is not clear what is actionable here.

**Comment by imkin** [comment]
@wenjiaswe yes w.r.t kubernetes this will help the compatibility information.

**Comment by justaugustus** [comment]
/sig api-machinery
ping @kubernetes/sig-api-machinery-feature-requests

**Comment by justaugustus** [comment]
/remove-lifecycle frozen

Also assigning Joe:
/assign @jpbetz

**Comment by ptabor** [comment]
I don't know the past, but in terms of Kubernetees supported versions, 
   etcd-{3.1-3.5} should be compatible with k8s 1.12+ in data-plane. 

etcd-3.0 didn't supported prevKV setting on Watch requests that modern api-servers depend on AFAIK.

**Comment by pacoxu** [comment]
information from kubeadm code:

https://github.com/kubernetes/kubernetes/blob/ba0817b746ad55eabcf8d6f0395bffa0cfc55af9/cmd/kubeadm/app/constants/constants.go#L451-L463

https://github.com/kubernetes/kubernetes/blob/ba0817b746ad55eabcf8d6f0395bffa0cfc55af9/cmd/kubeadm/app/constants/constants.go#L289-L290

**Comment by oldthreefeng** [comment]
using externel etcd 3.1.11 on k8s v1.12.  during upgrade. we had upgrade my k8s cluster to v1.18.8 { 1.14.9-> 1.16.9-> 1.18.8}
i dont find a obvious problem.  so , should I upgrade the etcd version to "3.4.3-0", I'm not sure to do it well。 @pacoxu 
```
$ etcd_v3 version
etcdctl version: 3.1.11
API version: 3.1

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8", GitCommit:"d2f5a0f", GitTreeState:"", BuildDate:"2020-11-17T03:28:04Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8", GitCommit:"5959bcb", GitTreeState:"", BuildDate:"2021-03-11T11:16:47Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by pacoxu** [comment]
@oldthreefeng  From the kubeadm code, the min version is 3.2.18(indicates minimum external etcd version which kubeadm supports) and 3.4.3-0 is the default that kubeadm uses. This is just a suggestion from kubeadm that you may refer to make a decision.
https://github.com/kubernetes/kubernetes/blob/v1.18.8/cmd/kubeadm/app/constants/constants.go#L266-L270

**Comment by justaugustus** [comment]
cc: @kubernetes/sig-api-machinery-feature-requests @kubernetes/release-engineering

**Comment by neolit123** [comment]
not sure why we keep this open still given we have https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml
which gives you a preferred etcd client/server version per k8s release (branch) in machine readable format?

**Comment by BenTheElder** [comment]
/remove-sig testing
(documenting this does not require any input from testing, and it appears to be already documented anyhow, supported version is a question for api-machinery)
