### ISSUE TITLE
Temporary kube-apiextensions-server directions

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#45510]
Once https://github.com/kubernetes/kubernetes/issues/45277 is resolved (before the end of 1.7), the `kube-apiextensions-server` will be embedded into the `kube-apiserver` so this is only temporary.

1.  run `hack/local-up-cluster.sh` - this gets the `kube-apiserver` (with aggregator) ready and available
1. `make WHAT=vendor/k8s.io/kube-apiextensions-server/ && vendor/k8s.io/kube-apiextensions-server/hack/build-image.sh` - this creates the image for the `kube-apiextensions-server` since it isn't published.
1. `export KUBECONFIG=/var/run/kubernetes/admin.kubeconfig` - give yourself cluster-admin powers
1. `kubectl create ns kube-apiextensions` - creates a namespace for the `kube-apiextensions-server` pod
1. `kubectl create -f vendor/k8s.io/kube-apiextensions-server/artifacts/example/` - creates the resources (permissions, RC, service, apiservice, etc) for the `kube-apiextensions-server`.  This won't be necessary once we're embedded.
1. `kubectl create -f vendor/k8s.io/kube-apiextensions-server/artifacts/customresource-01/noxu-resource-definition.yaml` - create a `CustomResource`Definition
1. `kubectl create -f vendor/k8s.io/kube-apiextensions-server/artifacts/customresource-01/noxu-apiservice.yaml` - create the `APIService` for `mygroup.example.com`.  This won't be necessary once we're embedded.
1. `kubectl get noxus` - proof that the resource type exists
1. `kubectl create -f vendor/k8s.io/kube-apiextensions-server/artifacts/customresource-01/noxu.yaml` - create an instance.
1. `kubectl get noxus` - proof that the resource instance exists

@enisoc this is a way for you to install the server and experiment with an in progress implementation to plan the detailed migration path.
@kubernetes/sig-api-machinery-misc for anyone wanting to play with it early.  Many pieces are not complete, but basic CRUD runs.

**Comment by deads2k** [comment]
@adohe here are some instructions that ought to let you play with the customresources now.  I checked the basic crud and `kubectl annotate` commands and they seem to work.

**Comment by adohe** [comment]
@deads2k cool 👍 I have just started to play with customresources.

**Comment by enisoc** [comment]
FYI this is working for me, after updating `noxu-resource-definition.yaml` to use `kind: CustomResourceDefinition`. Time to play!

**Comment by enisoc** [comment]
Now that https://github.com/kubernetes/kubernetes/pull/46055 has merged, I've verified that these temporary directions are no longer needed. Steps 6 and 9 work out-of-the-box on HEAD now.
