### ISSUE TITLE
(Vsphere) volume teardown fails when running containerized kubelet and volume path has space

### ISSUE THREAD

**Issue by wongma7** [kubernetes/kubernetes#45516]
nsenter_mounter.go mistakenly determines that a mount point is not a mount point if the mount point path contains a space. It will then try & fail to delete the mount point instead of unmounting it first. 

The output of findmnt is parsed by splitting it into space-separated fields. Normally "target" is the first field but if it contains a space, it is truncated. Example, note the space in "[ose3-vmware] kubevols" in the path

May 08 16:07:35 mawong atomic-openshift-node[32763]: I0508 16:07:35.592837     353 nsenter_mount.go:196] IsLikelyNotMountPoint findmnt output for path /var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/vsphere-volume/mounts/[ose3-vmware] kubevols/kubernetes-dynamic-pvc-e46bca08-3431-11e7-abad-005056a5d7df.vmdk: /var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/vsphere-volume/mounts/[ose3-vmware]:
May 08 16:07:35 mawong atomic-openshift-node[32763]: I0508 16:07:35.592853     353 nsenter_mount.go:202] IsLikelyNotMountPoint: /var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/vsphere-volume/mounts/[ose3-vmware] kubevols/kubernetes-dynamic-pvc-e46bca08-3431-11e7-abad-005056a5d7df.vmdk is not a mount point

The vsphere cloudprovider doesn't insert the space there deliberately or anything, it's done by the library:
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L1299
https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/vmware/govmomi/object/datastore_path.go#L64

So I'll try to make nsenter-mount.go parsing of findmnt a bit smarter, though it looks like the code is quite fragile.

https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/nsenter_mount.go#L194

**Comment by wongma7** [comment]
@kubernetes/sig-storage-bugs

**Comment by divyenpatel** [comment]
@BaluDontu @tusharnt

**Comment by wongma7** [comment]
fixed by https://github.com/kubernetes/kubernetes/issues/49106
