### ISSUE TITLE
Introduce a flag to gate if using openapi in kubectl

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes#45519]
We are trying to use OpenAPI in kubectl in 2 aspects:
- Using OpenAPI for kubectl validation in stead of using swagger, since we are deprecating swagger 1.2(ref: #38637 and #44589) (even though client-side validation will be removed in 1-2 releases #39434)
- Using OpenAPI for calculating the strategic merge patch (apply and edit) instead of using baked-in types. This will solve a lot of version skew issues when patching.

We will introduce --enable-openapi, default to false. I'm open to other namings.
If the user set it to false or kubectl fails to fetch openapi from the server, kubectl will use swagger and baked-in types.

The kubectl commands doing validation including:
- rollingupdate
- edit
- apply
- replace
- create
- convert

**Comment by mengqiy** [comment]
cc: @pwittrock @liggitt

**Comment by mengqiy** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by shiywang** [comment]
@mengqiy Aren't we already have a `--openapi-validation=true` flag ?

**Comment by zjj2wry** [comment]
```
admindeMacBook-Pro-2:kubectl admin$ kubectl create -f svc.yaml 
W0906 16:39:20.326822   18847 factory_object_mapping.go:418] Failed to download OpenAPI (the server could not find the requested resource), falling back to swagger
service "hello-node" created
```
this warnning info can just show when special -v flag?

**Comment by shiywang** [comment]
@mengqiy Is there the right way to output log here: https://github.com/kubernetes/kubernetes/blob/332b681bd1d961e2cee16bca10784088a8d308f1/pkg/kubectl/cmd/util/factory_object_mapping.go#L418 ?

**Comment by mengqiy** [comment]
We actually don't need this issue any more. Closing...

But this is a question for you @apelisse
