### ISSUE TITLE
Regression in gce-scalability density test

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#45512]
As you can see, density test in our gce 100-node clusters has been constantly failing for many days now: https://k8s-testgrid.appspot.com/google-gce#gce-scalability
And in about 50-60% of these cases, the sole reason seems to be OOM'ing of L7 loadbalancer:
```
Container l7-lb-controller-v0.9.3-e2e-scalability-master/l7-lb-controller is using 62.90625/60 MB of memory
not to have occurred
```
It was bumped up to version 0.9.3 from 0.9.2 in commit https://github.com/kubernetes/kubernetes/commit/71ca925b05ba987e20c48ac0b83c19fea1bdb9aa and that seems to be the cause.
Maybe we should consider reverting this PR? (cc @nicksardo)

Could this be something related to the go1.8 upgrade which happened around the same time? (ref https://github.com/kubernetes/kubernetes/issues/45216)
And besides loadbalancer, we have kube-proxy OOM'ing too in the other 40% of the cases, but that seems to be an older issue (https://github.com/kubernetes/kubernetes/issues/44613).

cc @k8s-mirror-scalability-bugs @wojtek-t @gmarek

**Comment by nicksardo** [comment]
Looking at one of the glbc logs (https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scalability/2064/artifacts/e2e-scalability-master/glbc.log), I see that the controller is only watching resources - it's not doing a single ingress/GCE operation. Between 0.9.2 and 0.9.3, the controller was migrated to the `client-go` library and built with 1.8.1. The previous version was built with 1.8. I spoke with @caesarxuchao, and he doesn't see a reason why the library change would cause this. 

Rather than trial-and-erroring a new version with go1.7.5, could we bump the [mem constraint](https://github.com/kubernetes/kubernetes/blob/d264cdf312eb01bbfa97f3bfcbc65f4550ae6382/test/e2e/perf/density.go#L149) to 100Mi?

**Comment by gmarek** [comment]
Actually we know that go 1.8 is causing problems: #45216. Can we make an experiment and check if going back to 1.7 would solve it?

**Comment by wojtek-t** [comment]
@shyamjvs - let's clarify one thing: those components are not OOMing - we have some artificial limits that we think should be met, but it has nothing to do with limits that are used for OOMing

Regarding go 1.8.1 - we know it's using more CPU, but we don't have any evidence for memory.

**Comment by shyamjvs** [comment]
@wojtek-t Thanks for the clarification. I've confused exceeding the expected limit to be some form of OOM'ing.

So just to clarify, which option are we choosing?
- Build the image with go1.7
- Reverting back to 0.9.2
- Increasing the mem constraint

**Comment by wojtek-t** [comment]
Did we confirm that using go1.7 fixes the problem? This is the first step to do in my opinion.
For now we don't know if this is even go-related.

**Comment by nicksardo** [comment]
Do we collect memory stats on tests that have passed? If you were to run this test with a 1.7 image, would it tell you anything more than it used less than 60MB?

**Comment by nicksardo** [comment]
Between 0.9.2 and 0.9.3, the binary increased in size from 33MB to 43MB. Via git bisecting, seems that it happened when we updated dependencies (https://github.com/kubernetes/ingress/commit/88a27512349828274dadd0deb528ac9589b80cd0).  If the memory usage was 50+MB already at load, conceivably the binary size could push it over the limit. 

@bowei agrees that it's reasonable to bump the limit.

**Comment by bowei** [comment]
Do we have a policy around how much memory the controllers _should_ take up? It is a centralized component so there will be at most one copy running for the entire cluster.

It looks to me like the 60 MB was derived empirically by seeing the memory consumption of the GLBC pod at the time. It stands to reason that memory usage would creep up as we add more features to the controller...

**Comment by wojtek-t** [comment]
> Do we have a policy around how much memory the controllers should take up? It is a centralized component so there will be at most one copy running for the entire cluster.

I don't think we have. But generally, for all components running on the master machine (which I think is the case for glbc, right?) we should track it very carefully, to avoid increasing size of those.

> It looks to me like the 60 MB was derived empirically by seeing the memory consumption of the GLBC pod at the time. It stands to reason that memory usage would creep up as we add more features to the controller...

That is fine - if you believe that the increase is expected, the we should bump it. We have those limits mostly to detect situations when some resource usage increases without any good reason.

If you believe that this increase is expected, then we can bump your constraints in tests.

**Comment by nicksardo** [comment]
> We have those limits mostly to detect situations when some resource usage increases without any good reason.
Reiterating my question - are we logging anywhere the max mem used of components in passed tests?

**Comment by wojtek-t** [comment]
> Reiterating my question - are we logging anywhere the max mem used of components in passed tests?

For each run we are logging the value which we are then checking against those thresholds. So yes - we should be able to get those numbers from previous runs.

**Comment by wojtek-t** [comment]
@nicksardo - sorry for delay. I just checked it and before bump it was using ~50-52MB. Now it's using around 62-63MB. 
Is it an expected bump between 0.9.2 and 0.9.3 versions? If so, I will bump the thresholds in our tests.

**Comment by shyamjvs** [comment]
Ok, we at least have ~50-60% of the runs green now. But kube-proxy is still causing the remaining failures.

**Comment by wojtek-t** [comment]
This is a separate problem we understand and we are working on it.
