### ISSUE TITLE
[Federation] Ingress should detect NodePort mistaches

### ISSUE THREAD

**Issue by csbell** [kubernetes/kubernetes#45520]
The documentation for federated ingress [here](https://kubernetes.io/docs/tasks/administer-federation/ingress/#adding-backend-services-and-pods) says:

> Note that in order for your federated ingress to work correctly on Google Cloud, the node ports of all of the underlying cluster-local services need to be identical. If you’re using a federated service this is easy to do. Simply pick a node port that is not already being used in any of your clusters, and add that to the spec of your federated service. If you do not specify a node port for your federated service, each cluster will choose it’s own node port for its cluster-local shard of the service, and these will probably end up being different, which is not what you want.

For services with non-matching nodeports, we should be generating events for mismatching NodePorts instead of following through with the ingress creation.

**Comment by marun** [comment]
@csbell Should this be blocking 1.7?

**Comment by csbell** [comment]
No, it's a "nice to have", won't make it.

**Comment by quinton-hoole** [comment]
There are two ways to make this better:

1. Make the federation control plane smart enough to select an unused nodeport across all clusters.
2. Until the above is in place, fail attempts to create federated services with unspecified nodeports.

I think that the workaround above is good enough for GA.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#135.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
