### ISSUE TITLE
Fix unit tests for autoregister_controller.go reliable

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#45538]
The unit tests described here https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-aggregator/pkg/controllers/autoregister/autoregister_controller_test.go are really hard to read and they've been flaking.  A pattern based on indexers like this https://github.com/kubernetes/kubernetes/pull/45432/files#diff-4c8b74b3f2b85a47ccb791ccb88eddceR106 is easier to understand.

I would suggest writing a new unit test file and once the coverage is consistent, just deleting the old one.

We need coverage for:
 1. ignoring APIServices that aren't auto managed when they are mutated
 1. create an APIService in response to AddAPIServiceToSync
 1. delete an APIService in response to RemoveAPIServiceToSync
 1. duplicate RemoveAPIServiceToSync don't panic
 1. duplicate AddAPIServiceToSync don't panic
 1. AddAPIServiceToSync an APIService, then having the user take ownership (remove `AutoRegisterManagedLabel` annotation), then RemoveAPIServiceToSync should not touch the APIService
 1. creating an APIService with the `AutoRegisterManagedLabel` when no such service has been AddAPIServiceToSync, should result in APIService deletion
 1. AddAPIServiceToSync an APIService, then modify the APIService.  The APIService should be stomped back to the AddAPIServiceToSync value.

**Comment by shiywang** [comment]
hi, @deads2k , about follow the indexers pattern to refactor `autoregister_controlloer_test.go`,  so I using a `cache.NewIndexer`  to replace previous  `fakeWatch` and  `informers.NewSharedInformerFactory`,  but I'm not sure should I also remove `Workqueue` ?  here is my code(not finished yet) : https://github.com/kubernetes/kubernetes/pull/45864

is that right ? should I start goroutinue and using Workqueue
