### ISSUE TITLE
controller-manager (in 1.5.5) partially ignores --use-service-account-credentials

### ISSUE THREAD

**Issue by krallistic** [kubernetes/kubernetes#45541]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5", GitCommit:"894ff23729bbc0055907dd3a496afb725396adda", GitTreeState:"clean", BuildDate:"2017-03-22T00:23:49Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5", GitCommit:"894ff23729bbc0055907dd3a496afb725396adda", GitTreeState:"clean", BuildDate:"2017-03-22T00:17:51Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

This is fixed in 1.6.X due to a refactoring.

**Environment**:
- **Cloud provider or hardware configuration**: Bare Metal
- **OS** (e.g. from /etc/os-release): SLES
- **Kernel** (e.g. `uname -a`): Linux 4.4.49-92.14
- **Install tools**:
- **Others**:

**What happened**:
A `kubectl get sa  --namespace=kube-system`
NAME                     SECRETS   AGE
default                  1         2h
replication-controller   1         2h
Only shows the replications-controller service account.

**What you expected to happen**:
Multiple service accounts for every controller.

**How to reproduce it** (as minimally and precisely as possible):
Use k8s 1.5.5, start controller-manager with `--use-service-account-credentials` and do  `kubectl get sa  --namespace=kube-system`

**Anything else we need to know**:
As far i can reproduce the controller-manager use the clientBuilder for communication. In https://github.com/kubernetes/kubernetes/blob/v1.5.5/cmd/kube-controller-manager/app/controllermanager.go#L170 the `rootClientBuilder ` and the `clientBuilder` get created. 
https://github.com/kubernetes/kubernetes/blob/v1.5.5/cmd/kube-controller-manager/app/controllermanager.go#L224 Then references the wrong client builder (`rootClientBuilder`) instead of `clientBuilder` which is set when `--use-service-account-credentials`  is active.

This is fixed in 1.6.X due to a refactoring.

**Comment by deads2k** [comment]
This is a good find and a frustrating bug, but we don't have the roles available in 1.5 if we were to fix it in the 1.5.x stream.  We would close the hole, but then anyone who had the flag set would end up stuck in a place where their controllers wouldn't work until they found a way to harvest and convert roles that are only present in 1.6.

I don't think we should close the hole in 1.5.

**Comment by krallistic** [comment]
I didnt though about the other side, that fixing the issue has the possibility to break installations with a patch release. I agree that would be terrible and unforeseen for user.

Since the Issue is fixed with 1.6 (due to a refactoring) iam gonna close this issue.
