### ISSUE TITLE
Problem with apiserver metrics for request counts of "LIST" api calls

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#45566]
It seems like the apiserver is not properly updating the `apiserver_request_count` metric for "LIST" api calls.

---------------------------------------------------

I created a new k8s cluster, ssh'ed to the master to obtain the count of `LIST pods` requests coming from kubectl using `curl localhost:8080/metrics | grep "apiserver_request_count{client=\"kubectl" | grep "resource=\"pods\",verb=\"LIST\""`, and got the following result:

```
apiserver_request_count{client="kubectl/v1.6.0 (linux/amd64) kubernetes/$Format",code="200",contentType="application/json",resource="pods",verb="LIST"} 18
```

Then I made a few `kubectl get pods` requests and rechecked the value of the count after a while. And it stayed the same as above.

-----------------------------------------------------

However `GET pods` seems to be rightly reporting the values.
Result of running `curl localhost:8080/metrics | grep "apiserver_request_count{client=\"kubectl" | grep "resource=\"pods\",verb=\"GET\""` was:

```
apiserver_request_count{client="kubectl/v1.7.0 (linux/amd64) kubernetes/c083871",code="404",contentType="application/json",resource="pods",verb="GET"} 7
```

Then I made precisely 4 `kubectl get pod yolo` requests and it seemed to update fine:

```
apiserver_request_count{client="kubectl/v1.7.0 (linux/amd64) kubernetes/c083871",code="404",contentType="application/json",resource="pods",verb="GET"} 11
```

-----------------------------------------------------

This problem seems to be there for other list requests too and we need to fix this.
I'll look deeper into it.

cc @kubernetes/sig-scalability-misc @wojtek-t @gmarek

**Comment by shyamjvs** [comment]
Just noticed something interesting! The LIST requests are actually being counted as WATCH requests for some reason. I've called `kubectl get pods` 5 times and they got counted as watch requests:

```
apiserver_request_count{client="kubectl/v1.7.0 (linux/amd64) kubernetes/c083871",code="200",contentType="application/json",resource="pods",verb="WATCH"} 39
```

changed to

```
apiserver_request_count{client="kubectl/v1.7.0 (linux/amd64) kubernetes/c083871",code="200",contentType="application/json",resource="pods",verb="WATCH"} 44
```

Are LIST requests converted to WATCH requests (by kubectl or admission controller) which are closed as soon as we get the first response?
Or maybe we are wrongly entering this 'if' statement -> https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go#L106.
I'll continue looking into it tomorrow,

**Comment by wojtek-t** [comment]
No - they are definitely not converted - it has to be a problem at the monitoring level somewhere.

@kubernetes/sig-api-machinery-bugs

**Comment by shyamjvs** [comment]
On running apiserver with this line https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go#L107 modified to `verb = "SWAGWATCH-" + request.QueryParameter("watch")` I noticed that all my list api calls were being reported under the verb `SWAGWATCH-true` showing that somehow `watch=true` parameter is being included in the request url.

However the actual request received by apiserver seems to be the right one (`GET /api/v1/namespaces/default/pods: (1.533686ms) 200 [[kubectl/v1.7.0 (linux/amd64) kubernetes/3fbfafd] 104.132.162.75:47659]`) and it also serves the right response. So something in the instrumentation code seems to wrongly modify the request while updating metric.

**Comment by wojtek-t** [comment]
@shyamjvs - any update on it?

**Comment by shyamjvs** [comment]
Not yet, I'll look into it today or tomorrow. Currently working on creating a CI job for benchmark.

**Comment by shyamjvs** [comment]
(Problem is [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go#L107)
After some experiments, turns out the reason is because the 'verb' variable inside the RouteFunction object is kind of a static variable, taken during registering of the handler function.
Because it is a non-local variable of the RouteFunction (obtained from the outer function `InstrumentRouteFunc`) it needs to be stored as a pointer inside the function's context.
So any change to it, like in the case of a watch call, reflects in the subsequent calls.

Will send out a PR to fix this.

**Comment by wojtek-t** [comment]
Great debugging. Thanks.
