### ISSUE TITLE
[BUG] endpoint controller wrongly deletes HA used endpoints

### ISSUE THREAD

**Issue by shenlanse** [kubernetes/kubernetes#45585]
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):    
BUG  OR   Do i miss something important?

---

**Kubernetes version** (use `kubectl version`):    
k8s 1.3.5. still exists in 1.6.2

---

**What happened**:  
HA of kube-controller-manager and kube-scheduler is achieved by create endpoint and update it periodically.    
However, endpoint controller deletes **endpoints without corresponding services** which is implemented in checkLeftoverEndpoints func:    

```
func (e *EndpointController) Run(workers int, stopCh <-chan struct{}) {
	defer utilruntime.HandleCrash()
	defer e.queue.ShutDown()

	if !cache.WaitForCacheSync(stopCh, e.podsSynced, e.servicesSynced) {
		utilruntime.HandleError(fmt.Errorf("timed out waiting for caches to sync"))
		return
	}

	for i := 0; i < workers; i++ {
		go wait.Until(e.worker, time.Second, stopCh)
	}
	go func() {
		defer utilruntime.HandleCrash()
		time.Sleep(5 * time.Minute) // give time for our cache to fill
		e.checkLeftoverEndpoints()
	}()

	<-stopCh
}

func (e *EndpointController) checkLeftoverEndpoints() {
	list, err := e.client.Core().Endpoints(metav1.NamespaceAll).List(metav1.ListOptions{})
	if err != nil {
		utilruntime.HandleError(fmt.Errorf("Unable to list endpoints (%v); orphaned endpoints will not be cleaned up. (They're pretty harmless, but you can restart this component if you want another attempt made.)", err))
		return
	}
	for i := range list.Items {
		ep := &list.Items[i]
		key, err := keyFunc(ep)
		if err != nil {
			utilruntime.HandleError(fmt.Errorf("Unable to get key for endpoint %#v", ep))
			continue
		}
		e.queue.Add(key)
	}
}


```

**That will result in leader transition.**

---

**What you expected to happen**:    

checkLeftoverEndpoints func shouldn't delete endpoints used by LeaderElection.

---

**How to reproduce it** (as minimally and precisely as possible):    
turn on LeaderElection for kube-controller-manager and kube-scheduler. After five minutes, endpoint controller will delete orphan endpoints.

---

**Anything else we need to know**:    
we can add some logic in checkLeftoverEndpoints, for example, not add endpoint in kube-system namespace to queue.

---

**Comment by shenlanse** [comment]
@mikedanese @timothysc

**Comment by mikedanese** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/45478

**Comment by shenlanse** [comment]
Thanks
