### ISSUE TITLE
kubectl logs does not work with --kubelet-preferred-address-types=InternalIP

### ISSUE THREAD

**Issue by tatsuhiro-t** [kubernetes/kubernetes#45583]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: vagrant
- **OS** (e.g. from /etc/os-release): coreos 1353.7.0
- **Kernel** (e.g. `uname -a`): 
- **Install tools**:
- **Others**:

**What happened**:

Run apiserver with --kubelet-preferred-address-types=InternalIP.
The address of worker node is filled as follows:

```
    addresses:
    - address: 10.0.2.15
      type: LegacyHostIP
    - address: 10.0.2.15
      type: InternalIP
    - address: core-02
      type: Hostname
```

`kubectl logs kube-proxy-core-02` gives the following error:

Error from server (NotFound): the server could not find the requested resource ( pods/log kube-proxy-core-02)

It works if --kubelet-preferred-address-types=InternalIP is not used.

**What you expected to happen**:

`kubectl logs kube-proxy-core-02` should get kube proxy log.

**How to reproduce it** (as minimally and precisely as possible):

Run apiserver with --kubelet-preferred-address-types=InternalIP.
And then do `kubectl logs` to the pods running on one of worker nodes.

**Anything else we need to know**:

**Comment by liggitt** [comment]
What is your network topology? Do your apiservers have network visibility to your kubelet's internal IP?

**Comment by tatsuhiro-t** [comment]
I use flannel via CNI.  I'm not sure apiserver can see that particular address because there is no logging for that, but the IP can be reached from host machine, and also if --kubelet-preferred-address-types, everything works fine.  Sorry if this does not answer your question.

Here is a simple reproduction step.  git clone https://github.com/coreos/coreos-kubernetes/ and, apply the following patch.
Then run `vagrant up` under multi-node/vagrant.

```patch
diff --git a/multi-node/generic/controller-install.sh b/multi-node/generic/controller-install.sh
index 4849eec..4dc8c15 100644
--- a/multi-node/generic/controller-install.sh
+++ b/multi-node/generic/controller-install.sh
@@ -270,6 +270,7 @@ spec:
     - --service-account-key-file=/etc/kubernetes/ssl/apiserver-key.pem
     - --runtime-config=extensions/v1beta1/networkpolicies=true
     - --anonymous-auth=false
+    - --kubelet-preferred-address-types=InternalIP,ExternalIP,LegacyHostIP
     livenessProbe:
       httpGet:
         host: 127.0.0.1
diff --git a/multi-node/generic/worker-install.sh b/multi-node/generic/worker-install.sh
index 060b721..e4ebe4b 100644
--- a/multi-node/generic/worker-install.sh
+++ b/multi-node/generic/worker-install.sh
@@ -98,7 +98,6 @@ ExecStart=/usr/lib/coreos/kubelet-wrapper \
   --register-node=true \
   --allow-privileged=true \
   --pod-manifest-path=/etc/kubernetes/manifests \
-  --hostname-override=${ADVERTISE_IP} \
   --cluster_dns=${DNS_SERVICE_IP} \
   --cluster_domain=cluster.local \
   --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml \
diff --git a/multi-node/vagrant/Vagrantfile b/multi-node/vagrant/Vagrantfile
index feabf95..a379ded 100644
--- a/multi-node/vagrant/Vagrantfile
+++ b/multi-node/vagrant/Vagrantfile
@@ -8,7 +8,7 @@ require 'yaml'
 
 Vagrant.require_version ">= 1.6.0"
 
-$update_channel = "alpha"
+$update_channel = "stable"
 $controller_count = 1
 $controller_vm_memory = 1024
 $worker_count = 1
```

Try to see the log of pod which is running on worker node using `kubectl logs`.  In my case, it displays something like: Error from server (NotFound): the server could not find the requested resource ( pods/log kube-proxy-w1)

**Comment by tatsuhiro-t** [comment]
I have another setup of Kubernetes cluster which uses OpenStack as cloud provider.  --kubelet-preferred-address-types works fine there.  So I guess that this may be vagrant specific.
BTW, I found that apiserver does not use hostname for TLS server authentication if   --kubelet-preferred-address-types is used even if type=Hostname exists under .status.addresses.  It is not directly related to this issue, but is it expected behaviour?

**Comment by liggitt** [comment]
> It is not directly related to this issue, but is it expected behaviour?

Correct. The apiserver uses the preferred addresses in order until it finds a recorded address of that type in the node status, then connects to that address, expecting a valid TLS cert for that address

**Comment by tatsuhiro-t** [comment]
Thank you for prompt answer.   Do you think it is useful to use Hostname for TLS cert validation even when the other address type is used?  Are there any plan to make it happen?

**Comment by liggitt** [comment]
`--kubelet-preferred-address-types` allows you to specify the priority order for kubelet-reported addresses. It defaults to prefer the kubelet-reported hostname before using the kubelet-reported IP. 

It sounds like your API server cannot resolve the kubelet's internal IP, but can resolve the kubelet-reported hostname. That's not necessarily a bug... are you expecting your apiserver to have visibility to that IP? Is it running in a container? What happens if you curl that IP from within that container?

**Comment by tatsuhiro-t** [comment]
I expect that apiserver can connect to worker's kubelet via internal IP.
apiserver runs as Kubernetes pod.  kubelet runs via rkt (through kubelet-wrapper from coreos).

I found very interesting thing.  The internal IP address of worker node shown in `kubectl get nodes` is actually bound to the node itself, just like a localhost.  The worker node's addresses are as follows:

```yaml
  status:
    addresses:
    - address: 10.0.2.15
      type: LegacyHostIP
    - address: 10.0.2.15
      type: InternalIP
    - address: w1
      type: Hostname
```

So InternalIP is 10.0.2.15.  When I issue `curl -k https://10.0.2.15:10250/logs/containers/` on master node, it shows the pods which are running on the master node (I also run the same command inside apiserver pod using openssl s_client, and it works).
When I issue the same command on worker node, it shows the pods which are running on the worker node.
This means that apiserver correctly uses InternalIP address.  The issue is the registered IP address of worker node is not correct.

**Comment by tatsuhiro-t** [comment]
I checked the master and worker nodes's interface addresses.  Their eth0 have the same address 10.0.2.15, and I think this caused this issue.
Since my OpenStack deployment does not cause this issue, and it is vagrant specific issue, and not apiserver issue, I'll close this issue.  Thank you for kindly help.

**Comment by orzroa** [comment]
Yes, it's a vagrant specific issue. The correct IP should be assigned to kubelet in that situation.
Following instructions works for me( from https://linuxacademy.com/community/posts/show/topic/29447-pod-is-not-found-eventhough-pod-status-is-up-and-running-why , thanks Will B  ):

open /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
Find a line under [Service] that has "KUBELET_EXTRA_ARGS=". If that line doesn't exist, just add it. Add a flag there called --node-ip=<private ip of the worker node>. Each worker node should have it's private ip for that flag. It will look something like this:
Environment="KUBELET_EXTRA_ARGS=--node-ip=<worker node private ip>"

Then restart kubelet on each worker:
systemctl daemon-reload
systemctl restart kubelet
