### ISSUE TITLE
it is so long ,when I use kubectl exec

### ISSUE THREAD

**Issue by smile-lin** [kubernetes/kubernetes#45584]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by smile-lin** [comment]
when I use kubectl exec somethink ,it is now:
![image](https://cloud.githubusercontent.com/assets/28584936/25894810/f50e47fa-35af-11e7-80d4-c377c81ddd30.png)

**Comment by smile-lin** [comment]
when I use kubectl exec,It is now
![image](https://cloud.githubusercontent.com/assets/28584936/25894920/53f43df6-35b0-11e7-8768-d7e6dd232df4.png)

**Comment by krousey** [comment]
It is unclear what this is about. I'm going to close it. If you can provide more information, feel free to open another issue and fill out the issue template with as much information as possible to help us understand your issue better.
