### ISSUE TITLE
Add scheduler debug tools 

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#45598]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
feature request

**Kubernetes version** (use `kubectl version`):
master branch

**What you expected to happen**:

When investigating #45237, we'd like to get more debug information from scheduler; but unfortunately, no much info here :(.

So I'd like to build a tools to replay scheduler with more information, e.g. print input/output of each predicates/priority, print each items of scheduler cache. This tools will dump information from apiserver, call predicates/priority but did not bind pods.

/cc @kubernetes/sig-scheduling-feature-requests

**Comment by davidopp** [comment]
Is this related to #3138?

**Comment by k82cn** [comment]
yes. I think so, this maybe simpler to dump pod/node ... info from apiserver; anyway, I'll the discussion to  #3138 .

**Comment by jayunit100** [comment]
Do we want logs or metrics or both? I prefer more metrics if possible .

**Comment by jayunit100** [comment]
For example, I'm thinking if we counted how many predicates/priorities failed or errored on all nodes in our metrics, then we might see spikes (like for resource not available) that correlate to other time series data.  Is that part of this issue @k82cn ? Would love to have them.

**Comment by k82cn** [comment]
nop :), I want to build a scheduler simulator, not a monitor. For example, I'd better to replay it locally to debug with some online data (access apiserver or dump from apiserver/etcd).

**Comment by timothysc** [comment]
@k82cn you can do that from etcd snapshots, and filling full of fake nodes like the scheduler_perf tests.

**Comment by k82cn** [comment]
hm, the original idea is to connect to apiserver and get all objects (no fake objects), e.g. Pods, Nodes, and run this scheduler simulator in local, it'll 

1. check whether scheduler got the correct data: in  #45237, it's recovered after restarting **apiserver** but restarting scheduler does **NOT** work
2. check whether scheduler handled those data correctly with more logs, e.g. print input/output of each predicates & priorities, dump every objects in cache (will not modify scheduler's code, import them as lib)
3. as a simulator, does not do any update to apiserver, e.g. do not call `bind` to apiserver

@timothysc /  @jayunit100 , does this make sense to you ?

**Comment by bsalamat** [comment]
@k82cn I like your idea of creating a simulator, but I guess what @timothysc said is valid and in fact may be the same thing that you have in mind. Tim said that you can take a snapshot of etcd and run your simulator with fake nodes. The nodes in your simulators have to be fake, but from scheduler's point of view they look like real nodes. They have the same characteristics and the same free resources of the cluster nodes at the time that the snapshot was taken, but they don't actually exist anywhere.

**Comment by k82cn** [comment]
> They have the same characteristics and the same free resources of the cluster nodes at the time that the snapshot was taken, but they don't actually exist anywhere.

Great, it's the same thing :).
