### ISSUE TITLE
The GCE cloudprovider's functions and assumptions should be documented

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#45594]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

DOCS REQUEST

@bowei I'm trying out the cloud-controller-manager on top of kubeadm in line with proposal https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cloud-provider-refactoring.md

But the assumptions the GCE cloudprovider makes are non-obvious, for example setting some tags somewhere on a node for being able to create LB Services.

I already had @jlowdermilk help me a little on Slack, but currently the whole cloudprovider stuff is kind of a black box and I'd want us to change that.

@jbeda did a doc like this for AWS already and I'd like to make that a pattern across cloudproviders, document these in a centralized manner and eventually move these out of repo when we have everything cleared out.

@wlan0, @thockin @roberthbailey and myself are driving the cloudprovider refactoring.

@bowei As mentioned on Slack, I'll assign the GCE parts of this issue to you.

**Comment by bowei** [comment]
@luxas -- do you have a link to @jbeda's doc? or is the documentation inline with the cloud provider code

**Comment by luxas** [comment]
@bowei currently a google doc, but I'm planning to centralize these docs as we get more providers documented: https://docs.google.com/document/d/17d4qinC_HnIwrK0GHnRlD1FKkTNdN__VO4TH9-EzbIY/edit

@idvoretskyi Who can do this for openstack?

**Comment by jagosan** [comment]
/sig cluster-lifecycle
note:  discussion in bug-scrub that there ought to be a sig-cloud but in the interim, adding to cluster-lifecycle.

**Comment by luxas** [comment]
ping @bowei

**Comment by thockin** [comment]
@nicksardo, since he's deep inside that code,too.

**Comment by neolit123** [comment]
> /sig cluster-lifecycle
> note: discussion in bug-scrub that there ought to be a sig-cloud but in the interim, adding to cluster-lifecycle.

untagging sig-cluster-lifecycle, until further notice.
this feels like a documentation issue around:
https://github.com/kubernetes/legacy-cloud-providers/tree/master/gce

/area provider/gcp
/sig cluster-lifecycle
