### ISSUE TITLE
When a worker leaves a cluster, pods on the worker should be automatically cleaned up

### ISSUE THREAD

**Issue by arunmk** [kubernetes/kubernetes#45632]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
kubeadm 1.6 garbage collect pods
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Centos 7.2
- **Kernel** (e.g. `uname -a`): 3.10.0-327.3.1.el7.x86_64
- **Install tools**: yum, rpm
- **Others**:

**What happened**:
In kubeadm 1.5, when a worker left the cluster using 'kubeadm reset', the pods running on the worker would be cleaned up and would not appear on the master in a 'kubectl get pods -o wide' listing. In kubeadm 1.6.1 they appear with a NodeLost or Unknown state. In a cluster where nodes scale elastically we will get into a state where there are many of these and this state will be very noisy. Could we get back the old behavior with a switch or in some other manner?

**What you expected to happen**:
The pods which are on the reset worker node should vanish fairly quickly.

**How to reproduce it** (as minimally and precisely as possible):
Create a cluster with two nodes, kubeadm init on master, kubeadm join on worker, start some pods which will also be scheduled on worker, then kubeadm reset the worker. Then look at 'kubectl get pods -o wide' on the master.

**Anything else we need to know**:
This is on kubeadm 1.6.1

**Comment by luxas** [comment]
@arunmk Please open an issue in the kubeadm repo instead of here.
To quickly answer your question, there were some authorization concerns which keeping that behavior very hard. For now, you should just run `kubectl drain <node> [flags]` before running `kubeadm reset`
