### ISSUE TITLE
Kubernetes 1.3.0 supports which version heapster garafana influxdb images

### ISSUE THREAD

**Issue by karunakar1122v** [kubernetes/kubernetes#45655]

**Comment by karunakar1122v** [comment]
Please update me ASAP on this.

**Comment by erictune** [comment]
You are welcome to look at the 1.3 branch on github and look in the cluster/addons directory

**Comment by karunakar1122v** [comment]
In addons directory Heapster and InfluxDB and Grafana yaml file not found.Can you please let me know where I can find.

**Comment by kargakis** [comment]
@karunakar1122v this is an issue tracker for k8s development - for support questions, please use stackoverflow or the kubernetes-users mailing list

http://stackoverflow.com/questions/tagged/kubernetes
https://groups.google.com/forum/#!forum/kubernetes-users
