### ISSUE TITLE
configmap "cluster-info" already exsited

### ISSUE THREAD

**Issue by huangjiasingle** [kubernetes/kubernetes#45668]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
configmap "cluster-info" already exsited
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
client: v1.6.2
server: v1.6.2

**Environment**:
- **Cloud provider or hardware configuration**: 
hardware configuration

- **OS** (e.g. from /etc/os-release): 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- **Kernel** (e.g. `uname -a`):
Linux a 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**:
kubeadm

- **Others**:

**What happened**:
1. kubeadm init --config=$HOME/kubeadm-config.yaml
2. kubeadm reset
3. kubeadm init --config=$HOME/kubeadm-config.yaml
   pruduce the error msg: configmap "cluster-info" already existed

**What you expected to happen**:
when i exec kubeadm reset , the kubeadm should delete the configmap named "cluster-info" from etcd-V3 

**How to reproduce it** (as minimally and precisely as possible):
1. kubeadm init --config=$HOME/kubeadm-config.yaml
2. kubeadm reset
3. kubeadm init --config=$HOME/kubeadm-config.yaml

**Anything else we need to know**:

**Comment by huangjiasingle** [comment]
@gnufied @ncdc @willb is this a bug?

**Comment by ncdc** [comment]
I have not used kubeadm before. cc @luxas @timothysc to see if they know.

**Comment by luxas** [comment]
Are you using external etcd?

**Comment by huangjiasingle** [comment]
@luxas yes , l use the external etcd cluster,  l think the kubeadm reset should delete the all resouce from the external etcd cluster.

**Comment by kargakis** [comment]
Please move this issue in the kubeadm repo

**Comment by luxas** [comment]
Closing as @huangjiasingle will reopen this in the kubernetes/kubeadm repo
