### ISSUE TITLE
NodePort to pod routing issue

### ISSUE THREAD

**Issue by dsilvius** [kubernetes/kubernetes#45662]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
It is but the issue is not covered. 

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): pod routing , kube-proxy routing  issue 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
1.4.7

**Environment**:

Cluster on ubuntu 14.04 VMs with 3.13.0-107-generic kernel, using flannel 0.5.5, etcd 2.3.1, kube_version 1.4.7. Kube-proxy is using iptables.
Installed with kube-up.

All the pods expose the same port and are http servers. The services are used through nodePort from outside the cluster. 

**What happened**:
Usually in high load or after cluster  changes ( addition/removal of minions) requests to a nodePort  are sometimes replied by pods of another  service. 

**What you expected to happen**:

The routing should be consistent. Requests should  not be mixed  between services. 

**How to reproduce it** (as minimally and precisely as possible):

Have  a consistent stream of request to a  service, delete a node the restart a service, some of the responses should be from a different service. 

**Anything else we need to know**:

**Comment by MrHohn** [comment]
/sig network

Did you re-use the nodePort on different services? Or is the "another service" completely irrelevant? This may happen if kube-proxy on nodes were not able to update stale rules soon enough.

**Comment by dsilvius** [comment]
The  nodePorts are not reused and are fairly static ( some services may change the nodePorts, it is done only on demand, and never happened when this issue  occured ).

**Comment by jojimt** [comment]
`Usually in high load or after cluster changes ( addition/removal of minions) requests to a nodePort are sometimes replied by pods of another service.`

How did you make this determination? Could you provide some logs?
