### ISSUE TITLE
vSphere disk that controller says is attached is not actually attached

### ISSUE THREAD

**Issue by wongma7** [kubernetes/kubernetes#45679]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): vsphere disk attach detach controller kubelet mount

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): kubernetes v1.5.2+43a9be4 (openshift v3.5.5.13)

**Environment**:
- **Cloud provider or hardware configuration**: vsphere
- **OS** (e.g. from /etc/os-release): RHEL Server 7.3
- **Kernel** (e.g. `uname -a`): 3.10.0-514.el7.x86_64
- **Install tools**:
- **Others**:

**What happened**:
Created a storage class, PVC, and pod using the PVC. Pod got scheduled to a node, then:

The attach detach controller on master reported that it succeeded in attaching the disk to the node and returned a device path. The disk can be seen under the node VM's info in the vSphere web UI. However, when the node tries to mount the device, it finds that the device path does not actually exist (because it doesn't):

>May 11 00:46:02 node1.c.vsphere.local atomic-openshift-node[6160]: E0511 00:46:02.945067    6220 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/vsphere-volume/[datastore1] kubevols/kubernetes-dynamic-pvc-1616e018-3541-11e7-9c55-0050569fb058.vmdk\"" failed. No retries permitted until 2017-05-11 00:48:02.945024277 +0800 CST (durationBeforeRetry 2m0s). Error: MountVolume.WaitForAttach failed for volume "kubernetes.io/vsphere-volume/[datastore1] kubevols/kubernetes-dynamic-pvc-1616e018-3541-11e7-9c55-0050569fb058.vmdk" (spec.Name: "pvc-1616e018-3541-11e7-9c55-0050569fb058") pod "1d943175-3541-11e7-9c55-0050569fb058" (UID: "1d943175-3541-11e7-9c55-0050569fb058") with: Could not find attached VMDK "[datastore1] kubevols/kubernetes-dynamic-pvc-1616e018-3541-11e7-9c55-0050569fb058.vmdk". Timeout waiting for mount paths to be created.

The pod is then stuck ContainerCreating

**What you expected to happen**:
Pod can enter Running state with the disk mounted.

**How to reproduce it** (as minimally and precisely as possible):
(It's only reproducible on one particular cluster with containerized kubelet and controller-manager. This was *not* reproducible on an identical cluster with the same containerized kubelet & controller-manager setup and the same version of kubernetes, on a different vSphere server,)

Steps to Reproduce:
1. Create a StorageClass
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: vsphere
provisioner: kubernetes.io/vsphere-volume

2. Create a PVC
{
  "kind": "PersistentVolumeClaim",
  "apiVersion": "v1",
  "metadata": {
    "name": "vsphere",
    "annotations": {
        "volume.beta.kubernetes.io/storage-class": "vsphere"
    }
  },
  "spec": {
    "accessModes": [
      "ReadWriteOnce"
    ],
    "resources": {
      "requests": {
        "storage": "1Gi"
      }
    }
  }
}

3. Once PVC is bound, create a Pod
oc get pvc
NAME      STATUS    VOLUME                                     CAPACITY   ACCESSMODES   AGE
vsphere   Bound     pvc-9baba382-0ed0-11e7-8a82-0050569fb058   1Gi        RWO           48m

{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "name": "vsphere",
        "labels": {
            "name": "vsphere"
        }
    },
    "spec": {
        "containers": [{
            "name": "vsphere",
            "image": "aosqe/hello-openshift",
            "imagePullPolicy": "IfNotPresent",
            "volumeMounts": [{
                "mountPath": "/mnt/vsphere",
                "name": "vsphere"
            }]
        }],
       "securityContext": {
            "fsGroup": 123456,
            "supplementalGroups": [111,112,113],
            "seLinuxOptions": {
                 "level": "s0"
            }
       },
        "volumes": [{
            "name": "vsphere",
            "persistentVolumeClaim": {
                "claimName": "vsphere"
            }
        }]
    }
}
4. Pod is stuck ContainerCreating

**Anything else we need to know**:
- Not reproducible on an identical cluster on a different vSphere server
- Not reproducible on a non-containerized cluster on the same vSphere server.

**Comment by imkin** [comment]
@divyenpatel @BaluDontu

**Comment by divyenpatel** [comment]
@wongma7 looks like you are missing disk.EnableUUID = "TRUE" on the node VM.
Can you confirm? Can you enable UUID on the VM as mentioned in the https://kubernetes.io/docs/getting-started-guides/vsphere/ and retry?

@tusharnt

**Comment by jhou1** [comment]
@divyenpatel @wongma7 Having `disk.EnableUUID = "TRUE"` on the node VM fixes the problem, thank you.

**Comment by wongma7** [comment]
Thanks for quick response!
