### ISSUE TITLE
SchedulerPredicates failing tests that upgrade to 1.6

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#45675]
Failure cluster: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=SchedulerPredicates#c2701aacb94858f60ca9

Testgrid: https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gce-1.5-1.6-upgrade-cluster&include-filter-by-regex=SchedulerPredicates

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:461
Not scheduled Pods: []api.Pod(nil)
Expected
    <int>: 0
to equal
    <int>: 1
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:930
```

/assign @gmarek @davidopp @timothysc 
@kubernetes/sig-scheduling-test-failures

**Comment by gmarek** [comment]
It is expected. Taint tests are failing, as we made (conscious) non-backward compatible change, when we moved taints from annotations to fields. It's not expected to work, and we communicated clearly about this. @fejta - are you fine with a fix being disabling Taint-based tests in this suite?

**Comment by fejta** [comment]
Certainly, sounds great!

**Comment by gmarek** [comment]
Yup - this is exactly what I planned to do:)

**Comment by gmarek** [comment]
@fejta - I tried doing kubernetes/test-infra#2742, but judging from test-grid it didn't turn off those tests. Can you tell me how to pass argument to this job?

This suite generally looks extremely sketchy, as it runs ALL our tests (including all performance tests, all flaky tests, all disruptive tests, all serial tests), and if I were to guess all of them are run in parallel. In other words - there's absolutely no way that this suite will pass. Please fix those issues before filing any issues for owners of single tests. @ixdy @kubernetes/test-infra-maintainers

**Comment by fejta** [comment]
/unassign @ixdy @fejta 
/assign @gmarek 

Please take a look at the triage failure cluster: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=SchedulerPredicates#c2701aacb94858f60ca9

The failure cluster shows that there are 4 SchedulerPredicate tests in 19 jobs with this failure.

Looks like [your PR](https://github.com/kubernetes/test-infra/pull/2742) modified the [gke-container_vm-1.4-gci-1.6-upgrade-cluster](https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gke-container_vm-1.4-gci-1.6-upgrade-cluster&sort-by-failures=) job to skip two of the four failing tests.

So 2 or the 4 failing tests are now skipped in 1 or the 19 jobs where it is failing.

If you do not want this suite to run all your tests, then please configure it to run the tests you do want it to run. The test-infra team does not have the expertise necessary to determine what tests are necessary to validate your features.

**Comment by gmarek** [comment]
@fejta - I was checking if that's the way to do it, and it seems that it is. The problem is that it's a miracle that any tests in those suites are actually passing - we are running all tests whatsoever ignoring even `Feature` tags (not to mention 'Serial', 'Disruptive' or 'Flaky', which shouldn't be run in the same suite as tests of different kind, especially not in parallel). There's no point in fixing single test failures if the whole suite is terribly missconfigured. I don't know what the plan is, but @ixdy set it up, so I guess he's the right person to fix it.

**Comment by gmarek** [comment]
I won't be fixing tests that quite likely shouldn't be running in this suite in the first place (they're serial tests).

**Comment by fejta** [comment]
/unassign

I am not writing features in kubernetes and therefore I have nothing I need to validate.

**Comment by davidopp** [comment]
@bsalamat can you take a look at this?

**Comment by gmarek** [comment]
This generally involves looking at upgrade/skew tests and making sure we're running correct set of tests. I don't know what's the definition of 'correct set of tests' is, but I guess previous/current release tzar might.

**Comment by bsalamat** [comment]
@davidopp I can take a look if it is not urgent. I will be very busy in the next one week or so to prepare PRs for before the code freeze for 1.7. I can take a look after that.

**Comment by davidopp** [comment]
OK, thanks.

**Comment by ixdy** [comment]
/assign @bsalamat 
/unassign

We [set a default skip string](https://github.com/kubernetes/kubernetes/blob/ee9bab111196565288705e44a9000d6f7bad8d87/test/e2e/e2e.go#L281-L283) of `\[Flaky\]|\[Feature:.+\]`, but that's overridden if you specify your own `--ginkgo.skip` setting. You'll need to add `\[Flaky\]|\[Feature:.+\]|` to yours to retain the same behavior.

**Comment by gmarek** [comment]
@ixdy - what's with disruptive and serial? Are we run those tests serially and if we do can all tests handle disruptive tests running just before them?

**Comment by gmarek** [comment]
Also - I don't think that hardcoding filters is a good pattern - it makes it way harder to understand which tests will run, if you don't know about this logic.

**Comment by bsalamat** [comment]
ref/ #47767 

These tests are expected to fail. According to @monopole we are going to ignore and remove 1.5 -> X upgrade tests.
