### ISSUE TITLE
L7 GCE should create ingress with given static-ip broken in 3 1.6 suites

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#45671]
Failure cluster: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=should%20create%20ingress#171d3d9981699b3a3a86

Testgrid: https://k8s-testgrid.appspot.com/release-1.6-all#gci-gke-ingress-1.6 (note that this is only one job)

Clicking the "changes" button suggests this is related to #45068 
https://github.com/kubernetes/kubernetes/compare/9d68760c3...8118c50c0

Example error:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/ingress.go:140
Expected error:
    <*errors.errorString | 0xc4214e04d0>: {
        s: "incorrect source ranges [130.211.0.0/22 35.191.0.0/16], expected [130.211.0.0/22]: found differences: map[35.191.0.0/16:{}]",
    }
    incorrect source ranges [130.211.0.0/22 35.191.0.0/16], expected [130.211.0.0/22]: found differences: map[35.191.0.0/16:{}]
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/ingress.go:129
```

@kubernetes/sig-network-test-failures 
/assign @bowei @nicksardo

**Comment by bowei** [comment]
Looks like this is due to the recent change that added another GCP range to the list of allowed LBs

**Comment by nicksardo** [comment]
Tests are passing now. 
/close
