### ISSUE TITLE
Examples suites do not pass ClusterDNS, Cassandra, CassandraStatefulSet and Hazelcast tests

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#45677]
Failure cluster: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Example
Testgrid: https://k8s-testgrid.appspot.com/google-gci#examples

ClusterDNS, Cassandra, CassandraStatefulSet and Hazelcast examples do not work

@kubernetes/sig-apps-test-failures 
/assign @michelleN @mattfarina

**Comment by foxish** [comment]
Looking into this. 
/cc @chrislovecnm

**Comment by chrislovecnm** [comment]
Is this stuff moving to examples?

**Comment by marun** [comment]
Who's working on ClusterDNS, Cassandra, and Hazelcast?  I'm not sure why this should block 1.7 if nobody is available to do the work.

**Comment by chrislovecnm** [comment]
This should not be in the milestone, this code is moving to examples.

**Comment by marun** [comment]
@chrislovecnm Ok thank you, moving to 1.7.

**Comment by fejta** [comment]
/close
no recnet hits
