### ISSUE TITLE
In CLI - more useful prompt after "kubectl proxy"

### ISSUE THREAD

**Issue by SpencerReynolds18** [kubernetes/kubernetes#45689]
Feature Request
@kubernetes/sig-cli-feature-requests

When running ```kubectl proxy``` in the CLI, I receive the response ```Starting to serve on 127.0.0.1:8001```. When I copy and paste that into the browser I get a list of paths. 

The path that I am typically most interested in is the path to the UI. In user testing, I have seen new Kubernetes users, who would like to see the UI, stumble at this point. 

If the response to ```kubectl proxy``` was modified to the following, fewer users would get tripped up trying to access the dashboard ui: 
```Starting to serve on 127.0.0.1:8001``` 
```View the dashboard UI at http://127.0.0.1:8001/ui```

**Comment by suyogbarve** [comment]
@SpencerReynolds18 : 127.0.0.1:8001 also serves lots of other useful endpoints which gets listed as soon as you hit http://127.0.0.1:8001.
I feel showing a message for dashboard might actually prevent new users from exploring all the possibilities. After a user reads "Starting to serve on 127.0.0.1:8001", their first reaction is to go and see what all is available, and /ui option along with other endpoints is easy to follow.

**Comment by suyogbarve** [comment]
@SpencerReynolds18 : thought? Please close this ticket if you are convinced.
