### ISSUE TITLE
Flaky: Kubectl expose should create services for rc on gce

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#45705]
Flaked 6 times this week in the blocking `pull-kubernetes-e2e-gce-etce3` suite.

6 failure clusters: https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&test=Kubectl%20expose%20should%20create%20services%20for%20rc

I suspect the most likely source of flakiness is the [namespace deletion timeout cluster](https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&test=Kubectl%20expose%20should%20create%20services%20for%20rc#5fa23bec4d68cc56bbca):
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:127
May 10 19:55:13.652: Couldn't delete ns: "e2e-tests-kubectl-00plg": namespace e2e-tests-kubectl-00plg was not deleted with limit: timed out waiting for the condition, namespaced content other than pods remain (&errors.errorString{s:"namespace e2e-tests-kubectl-00plg was not deleted with limit: timed out waiting for the condition, namespaced content other than pods remain"})
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:279
```

@kubernetes/sig-api-machinery-test-failures 
/kind flake

Assigning to sig-api-machinery per namespace timeout:
/assign @lavalamp @deads2k 
Please `/assign` someone to investigate and `/unassign` yourself.
If there is a more appropriate sig please `/sig-remove api-machinery` and `/sig better-sig`

**Comment by jagosan** [comment]
/unassign @deads2k @lavalamp (whom expect are full-on, heads-down on other things)
/assign @cheftako who has slightly better chances. 
Leaving @derekwaynecarr.

**Comment by smarterclayton** [comment]
Adding debug info into https://github.com/kubernetes/kubernetes/pull/42975 to get more signal.

**Comment by jagosan** [comment]
/unassign @deads2k @lavalamp
/assign @cheftako 
Hm.  Didn't work.  Trying again.
