### ISSUE TITLE
kubelet had better to obtain type and size of storage in detail.

### ISSUE THREAD

**Issue by knightXun** [kubernetes/kubernetes#45700]
kubelet should get rough storage resource infomation.we should obtain type and size of storage in detail.
In that way,Kubernetes can do better in Pod scheduler, and end-user will avoid mistake when they lable nodes.
 Thx all.

**Comment by knightXun** [comment]
@smarterclayton

**Comment by jagosan** [comment]
Hi @knightXun, thanks for jumping in.  Trying to work through open issues and this is tricky to triage.  Please add some more detail to make more actionable.  
/sig node
