### ISSUE TITLE
spec.selector.matchExpressions for Deployment/ReplicaSet not working properly

### ISSUE THREAD

**Issue by p-bakker** [kubernetes/kubernetes#45725]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): matchExpressions

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.6.0

**Environment**:
- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release): Windows 10
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**: MiniKube  v0.18.0

**What happened**:
Created a Deployment with the following selector spec:

> ...
> spec:
>    replicas: 3
>    selector:
>      matchLabels:
>          run: myapp
>      matchExpressions:
>       - {key: exclude, operator: NotIn, values: [true]}
> ...

The 3 replica pods start up nicely. 
Then added a label 'exclude=true' to one of the pods. 
A new pod automatically got created since the pod with the label doesn't match the selector used for the Deployment/ReplicaSet. 

The Dashboard/WebUI now shows 4/3 under Pods running for both the Deployment and ReplicaSets. 

**What you expected to happen**:
Everything described under **What happened** should happen, except that I expected 3/3 under the Pods column in the Dashboard/WebUI for the Deployment/ReplicaSet.

So it seems like the selector of the Deployment/ReplicaSet still matches the pod with the added 'exclude=true' label, even though adding the label triggered the adding of a new pod

**How to reproduce it** (as minimally and precisely as possible):
Follow the process described under **What happened**

**Anything else we need to know**:
If I alter the value of the 'run' label on the same pod, the Dashboard/WebUI for Deployments/ReplicaSet DOES start showing 3/3 in the Pods column

**Comment by soltysh** [comment]
@kargakis @tnozicka @kubernetes/sig-apps-bugs

**Comment by kargakis** [comment]
@p-bakker this seems to me like a dashboard issue. Mind moving this issue in the dashboard repo? https://github.com/kubernetes/dashboard/issues

**Comment by p-bakker** [comment]
Mmm, never though about it just being a display issue in the Dashboard :-) Good to know, just validated it with kubectl get deployment xxx/kubectl get replicaset xxxx-yyyy and those command indeed just report 3

I'll move the case, tnx
