### ISSUE TITLE
Tries to attach already attached EBS Volume (AWS)

### ISSUE THREAD

**Issue by MartinEmrich** [kubernetes/kubernetes#45726]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
Yes, but feels more like a bug...

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
aws, ebs

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
More of a Bug report

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Amazon EC2
- **OS** (e.g. from /etc/os-release): 
- **Kernel** (e.g. `uname -a`): 
admin@ip-172-20-57-219:~$ uname -a
Linux ip-172-20-57-219 4.4.41-k8s #1 SMP Mon Jan 9 15:34:39 UTC 2017 x86_64 GNU/Linux
admin@ip-172-20-57-219:~$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
- **Install tools**: kops Version 1.5.3 (git-46364f6)
- **Others**:

**What happened**:

I am new to Kubernetes, and try to learn hands-on by setting up a Wordpress with this tutorial: https://github.com/kubernetes/kubernetes/tree/master/examples/mysql-wordpress-pd

My Kubernetes cluster runs on Amazon EC2, set up via kops. I ended up with a little cluster (1 master, 2 nodes). Then I started with the tutorial, but I use Amazon EBS volumes for persistent storage.

In the first attempt, I created the EBS volumes manually, and then wondered why Kubernetes created new ones, until I learned about StorageClasses and Dynamic Perstistent Volumes. Indeed I seem to have a default StorageClass using aws-ebs (surely set up by kops).

The tutorial consists of two pods: One for a MySQL database, and one for Wordpress. The first pod (MySQL) starts fine.

But the second (Wordpress) pod ends up in the state "CrashLoopBackOff". Using "kubectl describe", I found this:

Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------   --------        ------                  -------
  10s           10s             2       default-scheduler                       Warning         FailedScheduling        [SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "wp-pv-claim", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "wp-pv-claim", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "wp-pv-claim", which is unexpected.]
  9s            9s              1       default-scheduler                       Normal          Scheduled               Successfully assigned wordpress-4130225953-hgn4h to ip-172-20-58-86.eu-west-1.compute.internal
  9s            8s              2       controller-manager                      Warning         FailedMount             Failed to attach volume "pvc-b859ae60-358c-11e7-b405-02bae99411f4" on node "ip-172-20-58-86.eu-west-1.compute.internal" with: Error attaching EBS volume "vol-07bb1f4adb5fb9a96" to instance "i-0d12a00064527321a": IncorrectState: vol-07bb1f4adb5fb9a96 is not 'available'.
                status code: 400, request id:

Apparently, it fails to mount the automatically provisioned volume to the node. But I checked the node via the AWS Console, and the volume is already attached.

**What you expected to happen**:

To use an existing PV or create a new one, and attach it to the pod

**How to reproduce it** (as minimally and precisely as possible):

* Install k8s cluster using kops on AWS
* Follow the wordpress example linked above, except using AWS EBS instead of GCE/Local Disk (as dynamic PVs are available, creating own ones beforehand seems to be unnecessary)

**Anything else we need to know**:

**Comment by aliakhtar** [comment]
I'm encountering the same issue with Kubernetes on AWS.

1) Created a StatefulSet for a Cassandra install, with a persistent volume:
```

volumeMounts:
        - name: cassandra-data
          mountPath: /cassandra_data

volumeClaimTemplates:
  - metadata:
      name: cassandra-data
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 30Gi
```

Full yaml:  https://gist.github.com/aliakhtar/1ad7db485366c09cd60e0d4af5299393

2) Tried to create the stateful set using `kubectl create -f cassandra.yaml`

3) The pods are created, but it looks like the EBS volumes are not mounted, running `kubectl describe po cassandra-0` gives:

```

Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  12m		12m		3	default-scheduler			Warning		FailedScheduling	[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", which is unexpected.]
  12m		12m		1	default-scheduler			Normal		Scheduled		Successfully assigned cassandra-0 to ip-172-20-41-131.ec2.internal
  12m		12m		1	attachdetach				Warning		FailedMount		Failed to attach volume "pvc-bd822597-4184-11e7-bbe9-12af326a3f02" on node "ip-172-20-41-131.ec2.internal" with: Error attaching EBS volume "vol-03a1ceea1043b0d9b" to instance "i-0a03ed3caca065e64": IncorrectState: vol-03a1ceea1043b0d9b is not 'available'.
		status code: 400, request id: e055cfcd-9c89-43f8-8cd1-996437bef912
  12m		12m	1	attachdetach		Warning	FailedMount	Failed to attach volume "pvc-bd822597-4184-11e7-bbe9-12af326a3f02" on node "ip-172-20-41-131.ec2.internal" with: Error attaching EBS volume "vol-03a1ceea1043b0d9b" to instance "i-0a03ed3caca065e64": IncorrectState: vol-03a1ceea1043b0d9b is not 'available'.
		status code: 400, request id: a5c3cd3d-1579-4105-b68c-1ef6b6841220
  11m		11m	1	kubelet, ip-172-20-41-131.ec2.internal	spec.containers{cassandra}	Normal	Pulling	pulling image "gcr.io/google-samples/cassandra:v11"
  11m		11m	1	kubelet, ip-172-20-41-131.ec2.internal	spec.containers{cassandra}	Normal	Pulled	Successfully pulled image "gcr.io/google-samples/cassandra:v11"
  11m		11m	1	kubelet, ip-172-20-41-131.ec2.internal	spec.containers{cassandra}	Normal	Created	Created container with id 0ea720a7bec14006d811d10a6aef861696518e15a9b098663dd94ccab79c653a
  11m		11m	1	kubelet, ip-172-20-41-131.ec2.internal	spec.containers{cassandra}	Normal	Started	Started container with id 0ea720a7bec14006d811d10a6aef861696518e15a9b098663dd94ccab79c653a

```

My versions:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by neverfox** [comment]
Same here, following [this example](https://wesmorgan.svbtle.com/rabbitmq-cluster-on-kubernetes-with-statefulsets).

```
Name:		rabbitmq-0
Namespace:	staging
Node:		ip-172-20-126-237.ec2.internal/172.20.126.237
Start Time:	Wed, 07 Jun 2017 10:15:34 -0400
Labels:		app=rabbitmq
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"StatefulSet","namespace":"staging","name":"rabbitmq","uid":"c149944f-4b8b-11e7-8275-12097edfb84a","apiVers...
		pod.beta.kubernetes.io/hostname=rabbitmq-0
		pod.beta.kubernetes.io/subdomain=rabbitmq
Status:		Pending
IP:
Controllers:	StatefulSet/rabbitmq
Containers:
  rabbitmq:
    Container ID:
    Image:		rabbitmq:3.6.10-management-alpine
    Image ID:
    Port:		5672/TCP
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Requests:
      memory:	1Gi
    Environment:
      RABBITMQ_ERLANG_COOKIE:	<set to the key 'erlang-cookie' in secret 'rabbitmq'>	Optional: false
    Mounts:
      /var/lib/rabbitmq from rabbitmq (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-rxtcs (ro)
Conditions:
  Type		Status
  Initialized 	True
  Ready 	False
  PodScheduled 	True
Volumes:
  rabbitmq:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	rabbitmq-rabbitmq-0
    ReadOnly:	false
  default-token-rxtcs:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-rxtcs
    Optional:	false
QoS Class:	Burstable
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  7m		7m		2	default-scheduler			Warning		FailedScheduling	[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "rabbitmq-rabbitmq-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "rabbitmq-rabbitmq-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "rabbitmq-rabbitmq-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "rabbitmq-rabbitmq-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "rabbitmq-rabbitmq-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "rabbitmq-rabbitmq-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "rabbitmq-rabbitmq-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "rabbitmq-rabbitmq-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "rabbitmq-rabbitmq-0", which is unexpected.]
  7m		7m		1	default-scheduler			Normal		Scheduled		Successfully assigned rabbitmq-0 to ip-172-20-126-237.ec2.internal
  7m		7m		1	attachdetach				Warning		FailedMount		Failed to attach volume "pvc-c14e5aea-4b8b-11e7-be95-0279e74aff78" on node "ip-172-20-126-237.ec2.internal" with: Error attaching EBS volume "vol-00cf0321247d9db97" to instance "i-06ec1087edf595ca8": IncorrectState: vol-00cf0321247d9db97 is not 'available'.
		status code: 400, request id: 5e3f3090-6c78-4cfc-857a-3652cc0108b4
  7m		7m	1	attachdetach		Warning	FailedMount	Failed to attach volume "pvc-c14e5aea-4b8b-11e7-be95-0279e74aff78" on node "ip-172-20-126-237.ec2.internal" with: Error attaching EBS volume "vol-00cf0321247d9db97" to instance "i-06ec1087edf595ca8": IncorrectState: vol-00cf0321247d9db97 is not 'available'.
		status code: 400, request id: 4ff7cabb-a1e0-4df7-ae00-71d3f3705ae1
  5m		5m	1	kubelet, ip-172-20-126-237.ec2.internal		Warning	FailedMount	Unable to mount volumes for pod "rabbitmq-0_staging(c14f95ac-4b8b-11e7-be95-0279e74aff78)": timeout expired waiting for volumes to attach/mount for pod "staging"/"rabbitmq-0". list of unattached/unmounted volumes=[rabbitmq default-token-rxtcs]
  5m		5m	1	kubelet, ip-172-20-126-237.ec2.internal		Warning	FailedSync	Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "staging"/"rabbitmq-0". list of unattached/unmounted volumes=[rabbitmq default-token-rxtcs]
```

A few observations:
* The PV *is* actually created:
```
Name:		pvc-c14e5aea-4b8b-11e7-be95-0279e74aff78
Labels:		failure-domain.beta.kubernetes.io/region=us-east-1
		failure-domain.beta.kubernetes.io/zone=us-east-1c
Annotations:	kubernetes.io/createdby=aws-ebs-dynamic-provisioner
		pv.kubernetes.io/bound-by-controller=yes
		pv.kubernetes.io/provisioned-by=kubernetes.io/aws-ebs
StorageClass:	gp2
Status:		Bound
Claim:		staging/rabbitmq-rabbitmq-0
Reclaim Policy:	Delete
Access Modes:	RWO
Capacity:	1Gi
Message:
Source:
    Type:	AWSElasticBlockStore (a Persistent Disk resource in AWS)
    VolumeID:	aws://us-east-1c/vol-00cf0321247d9db97
    FSType:	ext4
    Partition:	0
    ReadOnly:	false
Events:		<none>
```
* A PVC *is* created:
```
Name:		rabbitmq-rabbitmq-0
Namespace:	staging
StorageClass:	gp2
Status:		Bound
Volume:		pvc-c14e5aea-4b8b-11e7-be95-0279e74aff78
Labels:		app=rabbitmq
Annotations:	pv.kubernetes.io/bind-completed=yes
		pv.kubernetes.io/bound-by-controller=yes
		volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/aws-ebs
Capacity:	1Gi
Access Modes:	RWO
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  13m		13m		1	persistentvolume-controller			Normal		ProvisioningSucceeded	Successfully provisioned volume pvc-c14e5aea-4b8b-11e7-be95-0279e74aff78 using kubernetes.io/aws-ebs
```
* The volume *is* actually attached to the node in question. I can confirm this through the AWS console. So it's almost as if K8S isn't aware of it's own actions and assumes the volume is already in use.
* The stateful set does not tear itself down gracefully after this happens. When I delete it, the stuck pod goes from ContainerCreating to Terminating and just gets stuck there. I force delete the pod. Then I delete the PVC (which is normal, since they aren't supposed to be deleted with the set), but the PV (set to Dtelete reclaim policy) never deletes itself, even though it gets marked as "Released".

**Comment by neverfox** [comment]
Interestingly, the redis example here is able to stand up successfully even though the same errors appear in the describes. I wonder if it could be because it uses an init container and that somehow creates enough delay.

**Comment by neverfox** [comment]
@aliakhtar I don't think you can assume that. It's possible, even likely, that everything is working fine but that the error isn't reflecting reality. If you describe the pod, it should tell you whether it's using the claim and AWS should be able to tell you if the volume is in-use.

**Comment by tuannvm** [comment]
same issue happened with me:

* I use persistent volume for my deployment (deployed via helm) --> deployment successful --> pods was scheduled to node #1 --> the EBS volume was mounted to the same node

* But when pod was rescheduled to node #2, kubernetes didn't know how to `unmount` the volume from the node #1 and mount into node #2 ---> it must be done manually (`manually` detach volume from node #1, waiting for k8s pick up and `automatically` mount to node #2)

See logs:
```
38s		36s		3	controller-manager			Warning		FailedMount	Failed to attach volume "pvc-112233445566778899" on node "ip-1-1-1-1.us-east-1.compute.internal" with: Error attaching EBS volume "vol-112233445566778899" to instance "i-112233445566778899": VolumeInUse: vol-112233445566778899 is already attached to an instance
```

**Comment by snoby** [comment]
So this use to work in 1.5.4 of kubernetes, when i did the upgrade to 1.6.1 and > is when I started to see the issue.  I use kops to do the deployment.

**Comment by addisonbair** [comment]
I am seeing the same issue trying to stand up a postgres pod within a deployment using dynamic EBS provisioning. 

The initial provisioning and attachment appears to work without issue, but when the pod is removed (and automatically recreated within the deployment), the storage class does not appear to re-attach the same EBS volume successfully.

**Comment by hmesha** [comment]
Hi all,

I'm seeing the same issue on OpenShift Online V3 Pro. Is there a workaround or fix for this issue?

Thanks,
-Hany

**Comment by screeley44** [comment]
I'm experiencing same issue on latest dirty build version 1.9.Alpha...have there been any workarounds or ideas about this yet?

**Comment by owenmorgan** [comment]
also seeing this.. its bad.

**Comment by staylor89** [comment]
Not sure if this helps, but when this happens to us we the EBS volumes stuck in an 'attaching' state.
https://aws.amazon.com/premiumsupport/knowledge-center/ebs-stuck-attaching/

**Comment by mattcamp** [comment]
Any updates on this one?

I'm also seeing the same thing... info and logs [here](https://github.com/kubernetes/kubernetes/issues/49926#issuecomment-346611460)

#49926

**Comment by lvicentesanchez** [comment]
Having this problem too... check my comments on #49926

**Comment by RobertDiebels** [comment]
Getting the same issue.

- Dynamic provisioning of AWS EBS 10Gi with a PVC. (Succeeds)
- Volume is attached to the same AWS instance the pod is running on. (Succeeds)
- Kubernetes tries to attach the volume to the AWS instance it is already attached to. (Fails)

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs 
/cc @gnufied

**Comment by gnufied** [comment]
Assigning for myself for further investigation.

/assign

**Comment by leakingtapan** [comment]
@gnufied are you still working on this?

**Comment by gnufied** [comment]
@leakingtapan nope. feel free to take a look.
