### ISSUE TITLE
Can we have SSL: for AWS ELB Health Check Target?

### ISSUE THREAD

**Issue by weitenghuang** [kubernetes/kubernetes#45746]
**Is this a request for help?** : No

**What keywords did you search in Kubernetes issues before filing this one?**: AWS loadbalancer elb healthcheck

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T22:51:55Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2+coreos.0", GitCommit:"79fee581ce4a35b7791fdd92e0fc97e02ef1d5c0", GitTreeState:"clean", BuildDate:"2017-04-19T23:13:34Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
AWS

- **OS** (e.g. from /etc/os-release):
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.7.0
VERSION_ID=1353.7.0
BUILD_ID=2017-04-26-2154
PRETTY_NAME="Container Linux by CoreOS 1353.7.0 (Ladybug)"

- **Kernel** (e.g. `uname -a`):
Linux ip-172-16-10-12.us-west-2.compute.internal 4.9.24-coreos #1 SMP Wed Apr 26 21:44:23 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz GenuineIntel GNU/Linux

- **Install tools**:
CoreOS kubelet-wrapper

- **Others**:
n/a

**What happened**:
AWS ELB health check **target** seems to be `TCP:` only.
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws_loadbalancer.go#L343
When backend pod is serving in SSL and ELB health check uses `TCP:`, pod container will report error logs `http: TLS handshake error from <ip>:<port>: EOF` 

**What you expected to happen**:
Can we have `SSL:` as target when we use `service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "ssl"`?

**How to reproduce it** (as minimally and precisely as possible):
n/a

**Anything else we need to know**:
n/a

**Comment by FrederikNS** [comment]
This is bugging us as well. We have many TLS encrypted endpoints running in our cluster, and many of those log an error whenever they receive a non-TLS connection from the AWS ELB. This results in huge amounts of log-spam.

It would be really nice if it was possible to configure the healthcheck protocol on the loadbalancers.

**Comment by davidblewett** [comment]
This is still an issue; I see regular errors in our logs from attempts to connect to the port not using TLS.

**Comment by thessem** [comment]
I am commenting with a Me Too to try and prevent this from being considered "stale" since this is a feature I would like.

**Comment by dannolan** [comment]
I too would like this feature as we get a tonne of logspam :)

**Comment by psyhomb** [comment]
Is there anything new on this, cause I have same issue on my side?

**Comment by ottoyiu** [comment]
This function is the culprit as it does not deal with the case where you want the protocol to be TCP and backend protocol to be SSL.

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L3153

**Comment by jharrington22** [comment]
Hi we would also be interested in an annotation that allowed us to modify the TCP health check to a HTTP health check with a different "ping path". Currently these TCP checks generate a lot of log spam which we could modify the application to omit however are also hitting a "ping path" that ensures the application is responding and not just listing on the configured port would be preferred. Is there any update on possibility of having this added? Thanks!

**Comment by dhawal55** [comment]
+1

**Comment by andyday** [comment]
+1

**Comment by ms4720** [comment]
+1

**Comment by wallnerryan** [comment]
+1

**Comment by maazghani** [comment]
+1

**Comment by 2rs2ts** [comment]
Hey folks, I've created a PR for this. Please take a look. https://github.com/kubernetes/kubernetes/pull/70309
