### ISSUE TITLE
[Federation] Running Federation E2E tests locally with multiple clusters fails if the user's context is not set to the E2E test host cluster context

### ISSUE THREAD

**Issue by perotinus** [kubernetes/kubernetes#45751]
I was running into an issue running the Federation e2e tests with >1 cluster: when starting to run the tests, the test script would fail to list the nodes in the cluster hosting the federation with an "x509 invalid certificate" error. It worked fine with one cluster, however. @madhusudancs and I debugged this, and realized that the e2e script was using my local context to try to interact with the host cluster's API server. Because my E2E_ZONES environment variable had the clusters in "host non-host" order, the scripts to bring up the clusters would set the context to "non-host" on my machine, which meant that the script was using the wrong credentials to access the host cluster. I was able to fix this by setting my context to "host".

Ideally, the scripts should not be affected by the local kubecontext state in this way, and should always use the correct credentials regardless of the state of the local kubecontext.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#137.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
