### ISSUE TITLE
update-staging-godeps.sh should not depend on local Go version

### ISSUE THREAD

**Issue by enisoc** [kubernetes/kubernetes#45757]
In https://github.com/kubernetes/kubernetes/pull/45752 it was discovered that `update-staging-godeps.sh` generates different output depending on your local Go version, rather than pinning the Go version inside a Docker build container.

This makes it dangerous to run `update-all.sh` on a release branch, since you may have a different Go version installed than the one on which the release branch is based.

CC @caesarxuchao @sttts

**Comment by cblecker** [comment]
So I think the reason we're seeing this in the staging repos, but not the core repo is this line:
https://github.com/kubernetes/kubernetes/blob/3294200dc8e4e0600bedb512699a054fe3616797/hack/update-staging-godeps.sh#L67

We blow away the Godeps directory each time we to a godep save. I'm not sure that's strictly necessary.

Long term, if we're sticking with godep, doing those operations in a docker container may be a decent solution to this and other issues noted here: https://github.com/kubernetes/kubernetes/issues/44873

**Comment by sttts** [comment]
The removal of vendor/ is necessary because a) godep-save isn't very reliable with an existing vendor/ b) we want to be sure that we can always start fresh without a vendor/ dir.

I agree with the docker suggestion. Would be happy to review a PR implementing this :)

**Comment by ixdy** [comment]
This is assigned to me currently, but I'm happy to let anyone else take a stab at it. :)

**Comment by cblecker** [comment]
/assign
I'm taking a stab at this. Will likely post a WIP to get feedback soon.
