### ISSUE TITLE
codegen can produce package aliases that fail verification

### ISSUE THREAD

**Issue by whitlockjc** [kubernetes/kubernetes#45754]
While working on #45564, I ran into an issue where `./hack/verify-pkg-names.sh` was failing on generated code.  What is happening is whenever you have two separate packages with the same name, codegen will attempt to create a unique alias by walking up the package hierarchy and concatenating the directory names with a `_`.  **But** this ends up causing a verification failure because `_` _"breaks go conventions"_:

```
Binary file pkg/apis/admission/v1alpha1/zz_generated.conversion.go matches
!!! Some package aliases break go conventions.
To fix these errors, do not use capitalized or underlined characters
in pkg aliases. Refer to https://blog.golang.org/package-names for more info.
```

For example, in my PR `pkg/apis/admission/v1alpha1/zz_generated.conversion.go` ends up with `pkg_admission` as a package alias due to both `k8s.io/apiserver/pkg/admission` and `k8s.io/kubernetes/pkg/apis/admission`.

I didn't have time to look into this much further than finding [where in this might be happening](https://github.com/kubernetes/kubernetes/blob/master/vendor/k8s.io/gengo/generator/import_tracker.go#L38).

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by mml** [comment]
@whitlockjc is this still happening?

**Comment by whitlockjc** [comment]
I've not tested.  I can try this again.

**Comment by sttts** [comment]
I believe it can.

**Comment by sttts** [comment]
We disabled golint in all those packages.
