### ISSUE TITLE
[Feature request] Run Job tasks sequentially

### ISSUE THREAD

**Issue by Congelli501** [kubernetes/kubernetes#45759]
**FEATURE REQUEST**

It would be nice to create a single Job with multiple pods, that would run sequentially

That could be:
 - Perform a database backup
 - Apply default data to a database
 - Migrate some data
 - Perform another backup

Each tack must be run sequentially as they depend / are meaningless if ran in parallel or out of order.
The list of task form a single job that can be scheduled via a CronJob.

Questions:
Once a sub-job is completed, should it be restarted ?
(eg: if apply default data is successful and migration fails, only migration & last backup are re-scheduled).

An implementation could be:
 - multiple pod in a single job (already supported) that runs in sequential order
 - Job containing Jobs

The second implementation could be better:
 - Jobs already handle a completion flag
 - Could help creating complex Jobs, with part running in parallel

Gitlab CI files describe such possibilities. It can be interesting as a format: https://about.gitlab.com/2016/07/29/the-basics-of-gitlab-ci/

**Kubernetes version** v1.5.6

**Environment**:
- **Cloud provider or hardware configuration**: Dedicated servers
- **OS**: Ubuntu 16.04
- **Kernel**: 4.4.0-77-generic (stock)
- **Install tools**: kubeadm

**Comment by kargakis** [comment]
@kubernetes/sig-apps-feature-requests

**Comment by foxish** [comment]
@kow3ns @soltysh @janetkuo, this seems like a request to support DAG scheduling in jobs.

**Comment by mattfarina** [comment]
I could imagine, after looking at sequential, you get into fan-in/out and other patterns. This reminds me of [brigade](https://brigade.sh) and what you can do with that.

**Comment by soltysh** [comment]
> @kow3ns @soltysh @janetkuo, this seems like a request to support DAG scheduling in jobs. PTAL

Agreed, and we clearly stated that we don't want to include any DAG support in core k8s.

**Comment by kow3ns** [comment]
@soltysh argee
/close

**Comment by jaygorrell** [comment]
For anyone else coming here form a Google search - initContainer can handle most of this already.
