### ISSUE TITLE
Encode k8s version in node conformance test image name

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/kubernetes#45760]
Each version of k8s should have its corresponding node conformance test, which includes the tests and the validations required by that version. The latest node conformance test image is `gcr.io/google_container/node-test:0.2`. The name and the tag do not clearly indicate which k8s version the test is for.

We could encode the k8s version into the image name to make this clear. For example, `gcr.io/google_container/node-test-k8s-1.7:0.1` is the test for k8s v1.7.

**Comment by yguo0905** [comment]
@Random-Liu @dchen1107

**Comment by kargakis** [comment]
No @kubernetes/sig-node-misc group yet

**Comment by kargakis** [comment]
@kubernetes/sig-node-proposals
