### ISSUE TITLE
DaemonSet FailedPlacement events fire when they shouldn't

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#45780]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

DaemonSet FailedPlacement

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:38:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release): OL7.3
- **Kernel** (e.g. `uname -a`): 4.1.12-94.2.1.el7uek.x86_64
- **Install tools**:
- **Others**:

**What happened**:

I have a DaemonSet that is only deployed to a subset of nodes in the cluster based on a `nodeSelector`. I'm seeing events fired with reason `FailedPlacement` for the daemonset pods on nodes that do not fit the selector. 

```
Reason: FailedPlacement
Message: failed to place pod on "<node>": Node didn't have enough resource: memory, requested: 9768534016, used: 8361345024, capacity: 14944219136
```

**What you expected to happen**:

These events should never fire because they do not meet the node selectors in the pod spec. 

**How to reproduce it** (as minimally and precisely as possible):

Create a cluster with different sized nodes. E.g. smaller masters than workers. Then deploy the daemonset only to the workers. You will see events triggered for the master nodes that don't meet the requirements. 

**Anything else we need to know**:

**Comment by xiangpengzhao** [comment]
DaemonSet controller will run predicates to check if node should run daemon pod. In the progress of predicates, it will check if pod fits resources first before other predicates such as PodSelectorMatches. If PodFitsResources fails, it will throw the error in this issue and return without checking other predicates.

/cc @davidopp @kargakis

**Comment by lukaszo** [comment]
I think this bug appeared when critical pods were introduced and order of checking predicates changed. 
The event is useless for daemonsets in current situation :/ I'm not sure if there is a clean way to fix it.

**Comment by kargakis** [comment]
@kubernetes/sig-apps-bugs @kubernetes/sig-node-bugs @kubernetes/sig-scheduling-bugs

**Comment by jhorwit2** [comment]
@lukaszo I feel like a clean solution would be to look at the predicate reasons twice. The first time you look at the `PredicateFailureError` reasons and keep track if any are not intentional. If all of the reasons are intentional then skip checking the `InsufficientResourceError` reasons.

**Comment by lukaszo** [comment]
@jhorwit2 actually just changing order of checks in GeneralPredicates may just work. I'm testing the fix now.

**Comment by lukaszo** [comment]
Ok, GeneralPredicates returns all reasons. Error that pod doesn't match the node is also returned but because it's "intentional" there is no event for it.
The event "Node didn't have enough resource" should be sent only when there are no other "intentional" reasons.

**Comment by gyliu513** [comment]
Seems we are not doing `EssentialPredicates` to check `nodeSelector`:  https://github.com/kubernetes/kubernetes/blob/fb3353c769b8344aad86a1bf34b6c2936f28d306/pkg/controller/daemon/daemoncontroller.go#L981-L987

Not clear why only have `EssentialPredicates` for only `CritialPod` but not other pods.

**Comment by k82cn** [comment]
> The event "Node didn't have enough resource" should be sent only when there are no other "intentional" reasons.

Yes, I think maybe we need to check reason list twice: `NodeSelector` check is in tail of predicate list.

**Comment by gyliu513** [comment]
@lukaszo any PR for this?

**Comment by lukaszo** [comment]
@gyliu513 I will have some time to work on it next week. If you have a spare time you can create a PR.
