### ISSUE TITLE
pull-kubernetes-federation-e2e-gce flake: PR #45781

### ISSUE THREAD

**Issue by robertojrojas** [kubernetes/kubernetes#45795]
Test pull-kubernetes-federation-e2e-gce for PR #45781  is failing. 

`Test name:` pull-kubernetes-federation-e2e-gce	
`Commit link:` e790df2	
`Details:` https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45781/pull-kubernetes-federation-e2e-gce/4590/
`Command:` @k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by madhusudancs** [comment]
cc @MrHohn

**Comment by cblecker** [comment]
Details on the types of failures and frequency: https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&job=pull-kubernetes-federation-e2e-gce

In the last two days in particular, the following tests have been timing out:
- [k8s.io] Federated Services [Feature:Federation] with clusters Federated Service should create and update matching services in underlying clusters
- [k8s.io] Federated Services [Feature:Federation] with clusters DNS should be able to discover a federated service
- [k8s.io] Federated Services [Feature:Federation] with clusters Federated Service should recreate service shard in underlying clusters when service shard is deleted

cc: @kubernetes/sig-federation-misc

**Comment by madhusudancs** [comment]
@cblecker Thanks. And yes we are aware of it. @shashidharatd is working on a fix - PR #45798.

**Comment by robertojrojas** [comment]
Hi @madhusudancs I'm trying to find out how to follow up on this.
Will there be some sort of notification for the PRs affected this?

**Comment by cblecker** [comment]
@robertojrojas I just re-queue that test on your PR. note that the test isn't blocking, so your PR can be reviewed/merged without this test passing.

**Comment by robertojrojas** [comment]
@cblecker good to know. Thanks!

**Comment by cblecker** [comment]
Reopening to have an issue to track this. This was thought to be resolved, and was made blocking in https://github.com/kubernetes/test-infra/pull/2792. There's still something up, and it was reverted in https://github.com/kubernetes/test-infra/pull/2807. I believe sig-federation is going to look at this more next week in order to figure out a more permanent solution to this.

**Comment by madhusudancs** [comment]
Closing this in favor of issue #45978 which has linked runs which more accurately describe the problem.
