### ISSUE TITLE
Fair-share cpu time resources

### ISSUE THREAD

**Issue by Baschdl** [kubernetes/kubernetes#45819]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
quota, time (week), cpu time

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

We would like to see a feature where it is possible to specify quotas like cpu time/running time in the cluster. Currently one can only set a specific amount of cpus, memory etc.

The goal is to achieve some setting like the fair-share option with the slum scheduler:
"Instead, the fair-share factor serves to prioritize queued jobs such that those jobs charging accounts that are under-serviced are scheduled first, while jobs charging accounts that are over-serviced are scheduled when the machine would otherwise go idle."
[https://slurm.schedmd.com/priority_multifactor.html#fairshare](https://slurm.schedmd.com/priority_multifactor.html#fairshare)

**Comment by cmluciano** [comment]
May be related to https://github.com/kubernetes/community/pull/604 and preemption work

**Comment by davidopp** [comment]
This seems related to #36716
Would be interested in you feedback on the design doc we have here: https://docs.google.com/document/d/1-H2hnZap7gQivcSU-9j4ZrJ8wE_WwcfOkTeAGjzUyLA/edit

**Comment by Baschdl** [comment]
If you are interested in my feedback could you please make the document viewable without a google account?

**Comment by davidopp** [comment]
You don't need a Google account to view it but you do need to join the [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev) mailing list. Sorry for not mentioning that.

**Comment by Baschdl** [comment]
@davidopp Is this still the correct Google Docs? Or is https://docs.google.com/document/d/1X_-46p7mLsnflAPnLR4kMAwr-E1NoJEZVMlmo7M7uX0/edit#heading=h.xcaxtapqevok the relevant one?
