### ISSUE TITLE
CLI-based discovery of resources

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#45829]
I can discover what API Groups are present on my cluster using `kubectl api-versions`.
However, I cannot find out what Kinds are in each Group.

If I knew what kinds there were, then I could do `kubectl get $KIND` or `kubectl explain $KIND`.

Top-down exploration will become more important as there are more TPRs and AAs being installed into clusters.

The request here is to have a command that tells the kinds inside a specific api-version.

**Comment by erictune** [comment]
@mbohlool we talked about this the other day.

**Comment by liggitt** [comment]
duplicate of https://github.com/kubernetes/kubernetes/issues/42932, I think

**Comment by liggitt** [comment]
yup, with implementation in progress in https://github.com/kubernetes/kubernetes/pull/42873
