### ISSUE TITLE
Juju guide url cannot be used(404 Error) 

### ISSUE THREAD

**Issue by iordaniordanov** [kubernetes/kubernetes#45820]
Hey guys just tried opening https://kubernetes.io/docs/getting-started-guides/juju/ found [here](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/juju.md) but it resulted in 404 error

Thanks :)

**Comment by xiangpengzhao** [comment]
Current link for `Setting up Kubernetes with Juju` is https://kubernetes.io/docs/getting-started-guides/ubuntu/installation/

**Comment by iordaniordanov** [comment]
Ok, thanks :)

**Comment by erictune** [comment]
Send a PR?

**Comment by erictune** [comment]
Thanks, @xiangpengzhao for finding answer.

**Comment by xiangpengzhao** [comment]
Okay, will send a PR to update the link on that redirect page.
