### ISSUE TITLE
federation soak tests are timing out

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#45837]
triage failure cluster: https://storage.googleapis.com/k8s-gubernator/triage/index.html#4df909ae403747031437

Failing 8 tests in 3 jobs.

@kubernetes/sig-federation-test-failures 
/assign @quinton-hoole @csbell

**Comment by csbell** [comment]
The soak tests are going to fail until we bring back up a cluster that includes #45798. @madhusudancs can you comment on how to re-start the clusters in the soak tests?

**Comment by madhusudancs** [comment]
@csbell needs poking Jenkins, which I have done now.

@shashidharatd I think we should just delete the federation soak build job. It is confusing right now. I was looking at the `build` job which was failing and realized a few minutes later that we build in the `deploy` job now.

**Comment by shashidharatd** [comment]
@madhusudancs, i have already raised the PR to delete federation soak build job. it is assigned to you. PTAL https://github.com/kubernetes/test-infra/pull/2663

**Comment by shashidharatd** [comment]
federation soak tests are back on track https://k8s-testgrid.appspot.com/cluster-federation#soak-gce-test . this issue can be closed now.

**Comment by fejta** [comment]
Thanks! Note you can close issues with the `/close` command
