### ISSUE TITLE
aws slow suite fails service tests

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#45841]
testgrid: https://k8s-testgrid.appspot.com/google-aws#kops-aws-slow
failure cluster: https://storage.googleapis.com/k8s-gubernator/triage/index.html#aee02e0442d98d20850b

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1243
Expected error:
    <*errors.errorString | 0xc4201e86e0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/networking_utils.go:612
```

@kubernetes/sig-apps-test-failures 
/assign @michelleN @mattfarina @prydonius 
/cc @justinsb

**Comment by kargakis** [comment]
@fejta why is this sig/apps? I thought services were @kubernetes/sig-network-test-failures ?

**Comment by fejta** [comment]
Sure, thanks for clarifying!

/remove-sig apps
/unassign @michelleN @mattfarina @prydonius 
/assign @thockin @dcbw @caseydavenport

**Comment by cmluciano** [comment]
Possible dupe of #43340 ?

**Comment by thockin** [comment]
Looks like dup
