### ISSUE TITLE
Downgrade 1.6 to 1.5 suite leaks ip addresses

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#45842]
failure cluster: https://storage.googleapis.com/k8s-gubernator/triage/index.html#8cd80568009d1085aaf5
testgrid: https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gce-1.6-1.5-downgrade-cluster

Example failure text
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:160
May  7 19:42:57.567: Failed to allocated static ip e2e-tests-ingress-upgrade-c34m5-static-ip: googleapi: Error 403: Quota 'STATIC_ADDRESSES' exceeded. Limit: 15.0, quotaExceeded
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/ingress_utils.go:732
```

@kubernetes/sig-network-test-failures 
/assign @thockin @caseydavenport @dcbw

**Comment by thockin** [comment]
I need the `gcloud compute addresses describe` for each of the IPs in this project - which GCP project is it?

**Comment by fejta** [comment]
You can find this information from the job definition or a build result.

For now each job is pinned to a specific project. You can determine which job is pinned by opening the `test-infra/jobs/JOB_NAME.env` file for that job and then look for the `PROJECT=whatever` line which tells you the project.

If you have a gubernator build result then click on `build log` and then `expand skipped lines` then look for a line like `I0517 11:17:34.431] PROJECT=whatever` which tells you the project

So the two jobs flagged by the triage failure cluster:
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.6-1.5-downgrade-cluster/2896
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1.6-gci-1.5-downgrade-cluster/1788

Which shows that the two projects are:
* `I0516 08:43:04.852] PROJECT=k8s-gce-dg-1-6-1-5-dwngr-clu`
* `I0515 07:36:57.562] PROJECT=k8s-gke-dg-g1-6-g1-5-dwngr-clu`

**Comment by thockin** [comment]
All leaked IPs seem to be from test/e2e/upgrades/ingress.go - "ingress-upgrade".

None of them are "in use" by anything.

No lingering ForwardingRules or TargetProxies or BackendServices.

Some lingering certificates (e.g. k8s-ssl-e2e-tests-ingress-upgrade-793tb-static-ip--c108c2b16fb0) all for example.ciom

Tagging @nicksardo as most familiar with ingress and GLBC code, which would be responsible for cleaning these up.

**Comment by nicksardo** [comment]
I hardened the cleanup code back in March https://github.com/kubernetes/kubernetes/pull/42555; however, it could still leak static addresses until Kris wrote https://github.com/kubernetes/kubernetes/pull/44104. @krousey, should we cherry pick that to 1.6?

**Comment by krousey** [comment]
@nicksardo Yes. Could you handle that? I'm going on vacation soon and wouldn't be able to shepherd the cherry pick for long.

**Comment by nicksardo** [comment]
No problem @krousey!

**Comment by nicksardo** [comment]
I'd like this test to run with this cherry pick for a little bit before clearing the leaked certs/addresses. I'll clean it up tomorrow morning.

**Comment by nicksardo** [comment]
Cherry pick was delayed a day, but finally in the submit queue; I'll post again after cleaning resources tomorrow.

**Comment by nicksardo** [comment]
The good news is that `Teardown()` is now being called when `Setup()` fails. 

The bad news is that the test failed shortly after getting an ingress up:
```log
I0519 10:22:44.921] == Calling rolling-update for bootstrap-e2e-minion-group. ==
I0519 10:22:45.405] == FAILED to start rolling-update: ==
I0519 10:22:45.405] ERROR: (gcloud.alpha.compute.rolling-updates.start) HTTPError 412: There already exists an update in a non-terminal state.
```
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.6-1.5-downgrade-cluster/3079/build-log.txt

Looks like the failure in the disruption prevents the chaosmonkey semaphore from closing `StopCh` https://github.com/kubernetes/kubernetes/blob/8fd414537b5143ab039cb910590237cabf4af783/test/e2e/chaosmonkey/chaosmonkey.go#L102 which stalls tests from finishing the `Test()` call and performing `TearDown()`
With @krousey on PTO, is there anybody else that can tackle this case?

Also, who knows the most about this disruption test?

**Comment by ixdy** [comment]
looks like @ihmccreery wrote chaosmonkey, though that was a year ago.

is there a way to move the `Setup` and `Teardown` calls to ginkgo's `beforeEach` / `afterEach`, rather than calling them in `Test()`?

I guess the semaphore stuff makes this tricker. I don't really understand how this all works.

**Comment by nicksardo** [comment]
I believe we have two options. 
1) Add an `error` return all disruptions; `chaosmonkey.Do()` handles the error gracefully and surfaces it out. Cluster upgrades (and other chaosmonkey consumers) can assert no error occured.
2) Put this [section](https://github.com/kubernetes/kubernetes/blob/8e07e61a43d108353d642f49810a0c6ca071f297/test/e2e/chaosmonkey/chaosmonkey.go#L104-L108) in a deferred func.

**Comment by nicksardo** [comment]
Same as before, I'll cherrypick #46293 to 1.6 and check that Teardown is called when disruption fails.

According to #32466, it seems that the rolling upgrade sometimes "wedges". I'll run the following after I'm sure we won't leak static IPs. 
`gcloud alpha compute rolling-updates cancel 5375816b-5999-4050-b04a-3c3b1b562f64`

**Comment by nicksardo** [comment]
Looking at https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.6-1.5-downgrade-cluster/3307/build-log.txt
Teardown is now being called after disruption failure, so there should be no more leaked static addresses. I've now cleared the wedged update, and hopefully we'll see some passing tests. 
/close
