### ISSUE TITLE
"hack/update-all.sh" output doesn't pass "make validate" for generated federation content

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes#45853]
With #45694 we now have verify-*.sh scripts around federation generated code/swagger/docs ran as part of `make validate`.

However these steps updating the generated federation content are not listed in `hack/update-all.sh`. Therefore the output of `hack/update-all.sh` is no longer passing the `make validate` if federation-related content is updated. 

/assign @nikhiljindal

**Comment by nikhiljindal** [comment]
aah thanks for pointing that out.
Fixing in https://github.com/kubernetes/kubernetes/pull/45861

**Comment by ahmetb** [comment]
@nikhiljindal thanks.
