### ISSUE TITLE
apiextensions-server: de registering and re-registering CustomResource resurrects previous instances

### ISSUE THREAD

**Issue by sdminonne** [kubernetes/kubernetes#45878]
**What happened**:
de registering and re-registering CustomResource resurrects previous instances

**What you expected to happen**:
Not having old instance again

**How to reproduce it** (as minimally and precisely as possible):
#45768

**Comment by sdminonne** [comment]
@deads2k
@stts FYI

**Comment by deads2k** [comment]
@sdminonne This is because we don't yet have a finalizer in place.  Can we get the test working as much as it can without the finalizer so we don't slip backwards?

**Comment by sdminonne** [comment]
@deads2k  sorry for the noise then, I'm going to modify the test adding a `DELETE` of the `foo` resource before deregistration. Tell me if you have a better idea or disagree.

**Comment by deads2k** [comment]
> @deads2k sorry for the noise then, I'm going to modify the test adding a DELETE of the foo resource before deregistration. Tell me if you have a better idea or disagree.

Not noise at all.  Great that it was noticed
