### ISSUE TITLE
KubeProxy should expose more standard handlers

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#45876]
Currently kube-proxy exposes only: `/healthz' handler.
I would also like it to expose:
- '/metrics' (with standard prometheus metrics)
- '/debug/pprof/...` for profiling (probably hidden behind some flag; in other components we have `--profiling` flag for this purpose)

@freehan @thockin - I think that we can expose them using the same http server we are using for healthz purpose. WDYT?

**Comment by wojtek-t** [comment]
If we agree that this should be done using the same http server, we should probably rename it from "healthcheck" into something else - though I don't have a good name for it.

**Comment by wojtek-t** [comment]
Now I see that there are already two http servers (one for healthz and one for healthchecks). But I guess we shouldn't touch healthchecks here.

We should just somehow merge it with healthz.

**Comment by MrHohn** [comment]
Note that kube-proxy now holds more than two http servers:
- Metrics server
- Healthz server
- Local traffic healthcheck servers

/healthz is held on a different port from /metrics since #44968, so you are actually adding handlers to the Metrics server :)

**Comment by wojtek-t** [comment]
Yeah - I was adding next comments to it once I was going through related part of kube-proxy code.
I think that sounds most reasonable, because those profile handlers are most related to metrics.
