### ISSUE TITLE
Custom FlexVolume no longer working after 1.6.3 update

### ISSUE THREAD

**Issue by davidmccormick** [kubernetes/kubernetes#45887]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): Yes and no, the behavior of the flex volume interface has changed between 1.5 and 1.6 and I'm struggling to understand/change my implementation.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): flex volume, VerifyControllerAttachedVolume, isattached, getvolumename 

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT / DOCUMENTATION_ISSUE?

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:38:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:38:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.7.0
VERSION_ID=1353.7.0
BUILD_ID=2017-04-26-2154
PRETTY_NAME="Container Linux by CoreOS 1353.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"

- **Kernel** (e.g. `uname -a`):
Linux ip-10-20-14-151.eu-west-1.compute.internal 4.9.24-coreos #1 SMP Wed Apr 26 21:44:23 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux

- **Install tools**:
Custom Implementation

**What happened**:

My flex volume, "bounded-local", mounted a local sparse file which can also automatically be bind-mounted to another location to be picked up for log collection by Splunk or Fluentd etc..  It doesn't need devices and so in the previous working implementation on 1.5 the attach and dettach operations were left "Not Supported" and only init, mount and umount were used.

Testing the 1.6 upgrade I have found that my plugin as implemented no longer works and emits this error;

E0516 12:13:26.313138   10531 desired_state_of_world_populator.go:272] Failed to add volume "logging" (specName: "logging") for pod "bfd94f2d-397e-11e7-9952-06d9bc92ad18" to desiredStateOfWorld. err=failed to GetUniqueVolumeNameFromSpec for volumeSpec "logging" using volume plugin "zopa.com/bounded-local" err=failed to GetVolumeName from volumePlugin for volumeSpec "logging" err=invalid character 'I' looking for beginning of value

This has led me to implement getvolumename and produce a random name (because a unique name is not possible to be derived from the "json opts"

~~~
getvolumename() {
  UUID=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 64 ; echo '')

  log "{\"status\": \"Success\", \"volumeName\":\"${UUID}\"}"
  exit 0
}
~~~

I have also tried implementing stub functions for these plugin hooks that I don't really require: - 

~~~
attach() {
  log "{\"status\": \"Success\", \"attached\":true, \"device\": \"/dev/bounded-local\"}"
  exit 0
}

isattached() {
  log "{\"status\": \"Success\", \"attached\":true}"
  exit 0
}

waitforattach() {
  log "{\"status\": \"Success\", \"device\": \"/dev/bounded-local\"}"
  exit
}

detach() {
  log "{\"status\": \"Success\"}"
  exit 0
}
~~~

The full code is here https://github.com/davidmccormick/bounded-local-controller/blob/1.6_upgrades/bounded-local 

Now I am stuck with this error message:

E0516 11:22:04.276796   23422 nestedpendingoperations.go:262] Operation for "\"zopa.com/bounded-local/VJEyExr7D3abk6o5xcOBZySqJL9pOd7pYIwnHmXaTLf6k2p0rXvjGSaVMH8FBN44\"" failed. No retries permitted until 2017-05-16 11:22:04.776776935 +0000 UTC (durationBeforeRetry 500ms). Error: Volume "zopa.com/bounded-local/VJEyExr7D3abk6o5xcOBZySqJL9pOd7pYIwnHmXaTLf6k2p0rXvjGSaVMH8FBN44" (spec.Name: "logging") pod "c319829f-397e-11e7-9952-06d9bc92ad18" (UID: "c319829f-397e-11e7-9952-06d9bc92ad18") has not yet been added to the list of VolumesInUse in the node's volume status

**What you expected to happen**:

I'm looking for help to implement a simple flexvolume that doesn't really need to do any attaching or dettaching  - just mounts and unmounts.  I'm not sure what I need to do in order to keep the kubelet on the happy path and run my mount and unmount functions.

**How to reproduce it** (as minimally and precisely as possible):

Add the file /etc/kubernetes/vol-plugins/zopa.com~bounded-local/bounded-local from https://github.com/davidmccormick/bounded-local-controller/blob/1.6_upgrades/bounded-local

run the kubelet with: 

~~~
[Unit]
Description=Kubernetes Kubelet
Requires=pre-kubelet.service

[Service]
ExecStartPre=-/usr/bin/docker stop kubelet
ExecStartPre=-/usr/bin/docker rm kubelet
ExecStartPre=/usr/bin/docker run --rm \
  -v /opt/bin:/hostbin:rw \
  gcr.io/google_containers/hyperkube:v1.6.3 \
    bash -c "cp -p /hyperkube /hostbin/kubectl"
ExecStart=/usr/bin/docker run --rm \
 --name kubelet \
 --volume=/:/rootfs:ro \
 --volume=/sys:/sys:ro \
 --volume=/dev:/dev \
 --volume=/var/lib/docker/:/var/lib/docker:rw \
 --volume=/var/lib/kubelet/:/var/lib/kubelet:shared \
 --volume=/etc:/etc:rw \
 --volume=/var/run:/var/run:rw \
 --net=host --pid=host --privileged=true \
 gcr.io/google_containers/hyperkube:v1.6.3 \
 /hyperkube kubelet \
  --node-labels="type=worker,ingress=true" \
  --hostname-override=10.20.13.194 \
  --register-node=true \
  --containerized \
  --cgroup-driver=systemd \
  --pod-manifest-path=/etc/kubernetes/manifests \
  --allow-privileged=true \
  --network-plugin=cni \
  --cni-conf-dir=/etc/cni/net.d \
  --cni-bin-dir=/opt/cni/bin \
  --cluster-dns=192.168.0.10 \
  --cluster-domain=cluster.local \
  --v=256 \
  --require-kubeconfig=true \
  --kubeconfig=/etc/kubernetes/node-kubeconfig.yaml \
  --tls-cert-file=/etc/kubernetes/ssl/kubelet.pem \
  --tls-private-key-file=/etc/kubernetes/ssl/kubelet-key.pem \
  --volume-plugin-dir=/etc/kubernetes/vol-plugins \
  --cloud-config=/etc/kubernetes/cloud_config \
  --cloud-provider=aws
ExecStop=/usr/bin/docker stop kubelet
 
TimeoutStartSec=0
Restart=always
RestartSec=10s

[Install]
WantedBy=multi-user.target
~~~

Here is a podspec for a test pod which creates a random log file within the flex volume: -

~~~
apiVersion: v1
kind: Pod
metadata:
  name: logging-test1
  annotations:
    launched_as: part_of_voltest
  labels:
    k8s-app: random_logger
    voltestpod: "true"
spec:
  containers:
  - name: logtest1
    image: davidmccormick/random_log_generator
    volumeMounts:
    - name: logging
      mountPath: /logs
  volumes:
  - name: logging
    flexVolume:
      driver: zopa.com/bounded-local
      fsType: ext4
      options:
        size: "4096"
        cleanupDelay: "60"
        logCollectCopy: "true"
  - name: podinfo
    downwardAPI:
      items:
        - path: namespace
          fieldRef:
            fieldPath: metadata.namespace
        - path: podname
          fieldRef:
            fieldPath: metadata.name
        - path: labels
          fieldRef:
            fieldPath: metadata.labels
        - path: annotations
          fieldRef:
            fieldPath: metadata.annotations
~~~

**Anything else we need to know**:

I appreciate that Flexvolume is in Alpha and therefore likely to change often - I'm happy to update as required, but I'm finding it hard from the documentation as it stands to understand how the new functions work and what needs to happen to be "added to the list of VolumesInUse in the node's volume status"

Thanks 

Dave

**Comment by davidmccormick** [comment]
I'm confused by this log message: -

~~~
I0517 08:08:26.941936   29988 reconciler.go:207] Attempting to start VerifyControllerAttachedVolume for volume "zopa.com/bounded-local/QWeoVayH6QmbGX3JGS9M254TYlm3FnqtZqpCcZwr4OITBXOZRD87t0ACxWX8zQtN" (spec.Name: "logging") pod "c319829f-397e-11e7-9952-06d9bc92ad18" (UID: "c319829f-397e-11e7-9952-06d9bc92ad18")
~~~

I'm not running with "--enable-controller-attach-detach" ...

**Comment by davidmccormick** [comment]
Hmm it looks like the volume reconciler decides whether to run VerifyControllerAttachedVolume or not.

~~~
		if cache.IsVolumeNotAttachedError(err) {
			if rc.controllerAttachDetachEnabled || !volumeToMount.PluginIsAttachable {
				// Volume is not attached (or doesn't implement attacher), kubelet attach is disabled, wait
				// for controller to finish attaching volume.
~~~

It must be hitting this branch of code otherwise it would be logging "Attempting to start AttachVolume for volume" instead.

So if the plugin is not attachable then it must be controller attached?  My flexvolume does not need to be attached AT ALL - it only needs to be mounted or unmounted.

Even so, I thought I had implemented attach in my flexvolume and so it should be trying to run my attach and isattached functions!  https://github.com/davidmccormick/bounded-local-controller/blob/1.6_upgrades/bounded-local

**Comment by davidmccormick** [comment]
ok, think I got a bit further.  I didn't realize that `--enable-controller-attach-detach` is enabled by default on the kubelet.  I've now made sure that my updated plugin implementation is also deployed to the masters and included in the kube-controller-manager with `--flex-volume-plugin-dir`

I simplified the flexvolume with only mount/unmount/init and return "Not Supported" for anything else by default.   I now have a new error...

~~~
E0517 13:38:20.566710    7018 desired_state_of_world_populator.go:272] Failed to add volume "logging" (specName: "logging") for pod "1754714c-3b06-11e7-a55a-0acfd37d3a6c" to desiredStateOfWorld. err=failed to get Plugin from volumeSpec for volume "logging" err=no volume plugin matched
~~~

**Comment by davidmccormick** [comment]
Not sure about the message above but only just spotted that the mount and unmount commands have changed!  I'll re-test this tomorrow morning and see if I can't get any further.

**Comment by davidmccormick** [comment]
Maybe it doesn't like my getvolumename which generates a random name?  I would dearly like to use the pod_id in order to be able to create a unique volume-name based on it and the volume spec name: e.g.

bounded-local-logging-76ef544a-3be5-11e7-a102-02373e508e82

That way if the name is run on the controller and the kubelet they would come up with the same global unique name of the volume.  Perhaps a pod_uid field could always been added to the json_opts?

**Comment by chakri-nelluri** [comment]
@davidmccormick getvolumename is broken in 1.6. Please refer to #44737 for workaround. @liggitt has a PR #39488 to pass the pod information to the plugin. Let me ping him and revive it.

**Comment by davidmccormick** [comment]
Hi

I've put things back as close to the 'nfs' implementation as I can get so now it is very simple and only implements, 'init', 'mount' and 'umount'.  https://raw.githubusercontent.com/davidmccormick/bounded-local-controller/1.6_upgrades/bounded-local

When I try and create one of these volumes I now get this error in the kubernetes events..

Events:
  FirstSeen	LastSeen	Count	From							SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----							-------------	--------	------		-------
  52m		52m		1	default-scheduler							Normal		Scheduled	Successfully assigned chainsaw-1555351988-bmqlv to ip-10-20-14-109.eu-west-1.compute.internal
  50m		1m		23	kubelet, ip-10-20-14-109.eu-west-1.compute.internal			Warning		FailedMount	Unable to mount volumes for pod "chainsaw-1555351988-bmqlv_playground(93244933-3c75-11e7-8315-0a36ad0d2312)": timeout expired waiting for volumes to attach/mount for pod "playground"/"chainsaw-1555351988-bmqlv". list of unattached/unmounted volumes=[logging]
  50m		1m		23	kubelet, ip-10-20-14-109.eu-west-1.compute.internal			Warning		FailedSync	Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "playground"/"chainsaw-1555351988-bmqlv". list of unattached/unmounted volumes=[logging]


On the kubelet (with logging increased I see): -

~~~
I0519 09:28:53.596147   14106 desired_state_of_world_populator.go:279] Added volume "logging" (volSpec="logging") for pod "93243f16-3c75-11e7-8315-0a36ad0d2312" to desired state.
I0519 09:28:53.597128   14106 reconciler.go:207] Attempting to start VerifyControllerAttachedVolume for volume "zopa.com/bounded-local/logging" (spec.Name: "logging") pod "93243f16-3c75-11e7-8315-0a36ad0d2312" (UID: "93243f16-3c75-11e7-8315-0a36ad0d2312")
I0519 09:28:53.597163   14106 reconciler.go:231] VerifyControllerAttachedVolume operation started for volume "zopa.com/bounded-local/logging" (spec.Name: "logging") pod "93243f16-3c75-11e7-8315-0a36ad0d2312" (UID: "93243f16-3c75-11e7-8315-0a36ad0d2312")
I0519 09:28:53.597193   14106 config.go:101] Looking for [api file], have seen map[file:{} api:{}]
E0519 09:28:53.597358   14106 nestedpendingoperations.go:262] Operation for "\"zopa.com/bounded-local/logging\"" failed. No retries permitted until 2017-05-19 09:28:54.097342525 +0000 UTC (durationBeforeRetry 500ms). Error: Volume "zopa.com/bounded-local/logging" (spec.Name: "logging") pod "93243f16-3c75-11e7-8315-0a36ad0d2312" (UID: "93243f16-3c75-11e7-8315-0a36ad0d2312") has not yet been added to the list of VolumesInUse in the node's volume status
~~~

This is my issue, my volume is not attachable and yet the controller is asked to confirm it has been attached and the kubelet never tries to mount my volume.

On the kube-controller-manager I do see these logs: -

~~~
I0519 09:28:59.259830       1 reconciler.go:201] Volume "zopa.com/bounded-local/logging"/Node "ip-10-20-13-173.eu-west-1.compute.internal" is attached--touching.
I0519 09:28:59.259897       1 reconciler.go:201] Volume "zopa.com/bounded-local/logging"/Node "ip-10-20-14-109.eu-west-1.compute.internal" is attached--touching.
I0519 09:28:59.360038       1 reconciler.go:201] Volume "zopa.com/bounded-local/logging"/Node "ip-10-20-13-173.eu-west-1.compute.internal" is attached--touching.
~~~

Can you help - I can't even see 'mount' being called!?

**Comment by chakri-nelluri** [comment]
@davidmccormick Are you still seeing the issue? I saw your message on slack you got it working after fixing your driver. These logs are typically a result of misconfigured attach-detach-controller. I will check and see if I can improve these logs to reflect the actual misconfiguration.

**Comment by davidmccormick** [comment]
Hi
This is now working for me - I had introduced problem when I changed mount to expect 3 arguments thinking I needed to support attach/detach and then didn't reduce it back to 2 again when I reverted to mount/unmount only (which was preferable).

So I still see lots of errors on the attach/dettach but it then goes on the mount the volume , e.g.

~~~
E0522 09:44:59.577753    7900 nestedpendingoperations.go:262] Operation for "\"zopa.com/bounded-local/logging\"" failed. No retries permitted until 2017-05-22 09:45:00.0777355 +0000 UTC (durationBeforeRetry 500ms). Error: Volume "zopa.com/bounded-local/logging" (spec.Name: "logging") pod "52026872-3ed3-11e7-9bee-0a33a06e86e2" (UID: "52026872-3ed3-11e7-9bee-0a33a06e86e2") has not yet been added to the list of VolumesInUse in the node's volume status
I0522 09:45:00.079189    7900 reconciler.go:231] VerifyControllerAttachedVolume operation started for volume "zopa.com/bounded-local/logging" (spec.Name: "logging") pod "52026872-3ed3-11e7-9bee-0a33a06e86e2" (UID: "52026872-3ed3-11e7-9bee-0a33a06e86e2")
E0522 09:45:00.080012    7900 nestedpendingoperations.go:262] Operation for "\"zopa.com/bounded-local/logging\"" failed. No retries permitted until 2017-05-22 09:45:01.079993732 +0000 UTC (durationBeforeRetry 1s). Error: Volume "zopa.com/bounded-local/logging" (spec.Name: "logging") pod "52026872-3ed3-11e7-9bee-0a33a06e86e2" (UID: "52026872-3ed3-11e7-9bee-0a33a06e86e2") has not yet been added to the list of VolumesInUse in the node's volume status
~~~

This is improved if I change the default "Not Supported" response to a log and exit 0 - can I safely do this?  Change: -

~~~
case "$op" in
  init)
    init $*
    ;;
  mount)
    domount $*
    ;;
  unmount)
    unmount $*
    ;;
  *)
    err "{ \"status\": \"Not supported\" }"
    exit 1
esac
~~~

to

~~~
case "$op" in
  init)
    init $*
    ;;
  mount)
    domount $*
    ;;
  unmount)
    unmount $*
    ;;
  *)
    log "{ \"status\": \"Not supported\" }"
    exit 0
esac
~~~

Thanks for your help!

**Comment by chakri-nelluri** [comment]
Yes you can do that. Feel free to ping me if you still see any issues.

**Comment by paalkr** [comment]
Hi Guys

I'm facing the exact same issue as @davidmccormick trying to run the k8s cifs plugin located at https://github.com/sigma/cifs_k8s_plugin in my 1.6.2. cluster. Any ideas what needed to be done to get the plugin going?

I have tried to contact the dev without success.

Thanks in advance, and sorry for "hijacking" the  thread ;)

**Comment by fvigotti** [comment]
I've created a fixed version of the flex cifs plugin, you can find it here : https://github.com/fvigotti/cifs_k8s_plugin , I'm sorry to not have time to make it good looking and more featured .. but it is tested and works for my k8s  1.6.3 :) have a nice day

**Comment by chakri-nelluri** [comment]
Thanks guys. Glad it worked.

@paalkr The best way is to reach me is on Slack @nelcyguy.
I try it to keep it almost a live support for flex issues just to make sure the transition is smooth, but sometimes get dragged away from my seat.

**Comment by paalkr** [comment]
@fvigotti , Tanks a lot!

I will try it out a soon as I'm back in office week.

**Comment by chakri-nelluri** [comment]
@davidmccormick is it ok to close this issue?

**Comment by davidmccormick** [comment]
All ok for me now, thanks very much!

**Comment by paalkr** [comment]
@chakri-nelluri , thanks for the dedicated support. I will reach out to you on slack if I'm facing any issues with the cifs plugin put together by  @fvigotti

**Comment by paalkr** [comment]
@chakri-nelluri and @fvigotti , sorry to continue on a closed issue ;)
I still does not get the cifs plugin to run. I posted a message on slack https://kubernetes.slack.com/archives/C09NXKJKA/p1495988103021947 but I'm not sure if the will ever reach you guys. 

Basically I still get the same errors
```
May 28 16:12:32 ip-10-1-44-51.eu-west-1.compute.internal kubelet-wrapper[2444]: W0528 16:12:32.388728    2444 plugin-defaults.go:32] flexVolume driver fvigotti/cifs: using default GetVolumeName for volume 0xe06360
May 28 16:13:34 ip-10-1-44-51.eu-west-1.compute.internal kubelet-wrapper[2444]: I0528 16:13:34.643122    2444 reconciler.go:231] VerifyControllerAttachedVolume operation started for volume "fvigotti/cifs/mapcache" (spec.Name: "mapcache") pod "e7628c95-43be-11e7-b1be-06b155227fa6" (UID: "e7628c95-43be-11e7-b1be-06b155227fa6")
May 28 16:13:34 ip-10-1-44-51.eu-west-1.compute.internal kubelet-wrapper[2444]: E0528 16:13:34.646765    2444 nestedpendingoperations.go:262] Operation for "\"fvigotti/cifs/mapcache\"" failed. No retries permitted until 2017-05-28 16:15:34.646748979 +0000 UTC (durationBeforeRetry 2m0s). Error: Volume "fvigotti/cifs/mapcache" (spec.Name: "mapcache") pod "e7628c95-43be-11e7-b1be-06b155227fa6" (UID: "e7628c95-43be-11e7-b1be-06b155227fa6") is not yet attached according to node status
May 28 16:14:32 ip-10-1-44-51.eu-west-1.compute.internal kubelet-wrapper[2444]: E0528 16:14:32.355597    2444 kubelet.go:1549] Unable to mount volumes for pod "geocachebasisutm33euref89-1376089412-gwx2p_default(e7628c95-43be-11e7-b1be-06b155227fa6)": timeout expired waiting for volumes to attach/mount for pod "default"/"geocachebasisutm33euref89-1376089412-gwx2p". list of unattached/unmounted volumes=[mapcache]; skipping pod
May 28 16:14:32 ip-10-1-44-51.eu-west-1.compute.internal kubelet-wrapper[2444]: E0528 16:14:32.355644    2444 pod_workers.go:182] Error syncing pod e7628c95-43be-11e7-b1be-06b155227fa6 ("geocachebasisutm33euref89-1376089412-gwx2p_default(e7628c95-43be-11e7-b1be-06b155227fa6)"), skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"geocachebasisutm33euref89-1376089412-gwx2p". list of unattached/unmounted volumes=[mapcache]
```

**Comment by paalkr** [comment]
I did came a little longer this time, but there are still some errors in the log. Complaining about the returned json object from the cifs mounting code.

```
May 28 18:31:46 ip-10-1-44-245.eu-west-1.compute.internal kubelet-wrapper[2395]: I0528 18:31:46.845266    2395 operation_generator.go:492] Entering MountVolume.WaitForAttach for volume "fvigotti/cifs/mapcache" (spec.Name: "mapcache") pod "3a112ec3-43d2-11e7-bbad-06b1a5c2d29c" (UID: "3a112ec3-43d2-11e7-bbad-06b1a5c2d29c") DevicePath: ""
May 28 18:31:46 ip-10-1-44-245.eu-west-1.compute.internal kubelet-wrapper[2395]: W0528 18:31:46.845345    2395 attacher-defaults.go:42] flexVolume driver fvigotti/cifs: using default WaitForAttach for volume 0xe06360, device
May 28 18:31:46 ip-10-1-44-245.eu-west-1.compute.internal kubelet-wrapper[2395]: I0528 18:31:46.845359    2395 operation_generator.go:512] MountVolume.WaitForAttach succeeded for volume "fvigotti/cifs/mapcache" (spec.Name: "mapcache") pod "3a112ec3-43d2-11e7-bbad-06b1a5c2d29c" (UID: "3a112ec3-43d2-11e7-bbad-06b1a5c2d29c").
May 28 18:31:46 ip-10-1-44-245.eu-west-1.compute.internal kubelet-wrapper[2395]: W0528 18:31:46.845372    2395 attacher-defaults.go:48] flexVolume driver fvigotti/cifs: using default GetDeviceMountPath for volume 0xe06360, mountsDir /var/lib/kubelet/plugins/kubernetes.io/flexvolume/fvigotti/cifs/mounts
May 28 18:31:46 ip-10-1-44-245.eu-west-1.compute.internal kubelet-wrapper[2395]: W0528 18:31:46.845387    2395 plugin-defaults.go:32] flexVolume driver fvigotti/cifs: using default GetVolumeName for volume 0xe06360
May 28 18:31:46 ip-10-1-44-245.eu-west-1.compute.internal kubelet-wrapper[2395]: I0528 18:31:46.845424    2395 operation_generator.go:551] MountVolume.MountDevice succeeded for volume "fvigotti/cifs/mapcache" (spec.Name: "mapcache") pod "3a112ec3-43d2-11e7-bbad-06b1a5c2d29c" (UID: "3a112ec3-43d2-11e7-bbad-06b1a5c2d29c") device mount path "/var/lib/kubelet/plugins/kubernetes.io/flexvolume/fvigotti/cifs/mounts/mapcache"
May 28 18:31:46 ip-10-1-44-245.eu-west-1.compute.internal kubelet-wrapper[2395]: E0528 18:31:46.896189    2395 driver-call.go:212] Failed to unmarshal output for command: mount, output: , error: unexpected end of JSON input
May 28 18:31:46 ip-10-1-44-245.eu-west-1.compute.internal kubelet-wrapper[2395]: E0528 18:31:46.896281    2395 nestedpendingoperations.go:262] Operation for "\"fvigotti/cifs/mapcache\"" failed. No retries permitted until 2017-05-28 18:33:46.896260553 +0000 UTC (durationBeforeRetry 2m0s). Error: MountVolume.SetUp failed for volume "fvigotti/cifs/mapcache" (spec.Name: "mapcache") pod "3a112ec3-43d2-11e7-bbad-06b1a5c2d29c" (UID: "3a112ec3-43d2-11e7-bbad-06b1a5c2d29c") with: unexpected end of JSON input
```

**Comment by chakri-nelluri** [comment]
@paalkr This typically happens when the plugin is not echoing valid output. Please check your plugin output.
Ping me on slack @nelcyguy if you are still facing issues.

**Comment by shrinandj** [comment]
I am a bit confused about the exact workaround (also based on bug-[44737](https://github.com/kubernetes/kubernetes/issues/44737)).

Ideally, I would also like to only implement init, mount and unmount. To do that, should I do the following:

1. Start kubelets with --enable-controller-attach-detach=false.
2. Do not implement the getvolumename call-out. Does this mean that if the volume-plugin is invoked with  getvolumename option, it should error out (exit status 1)?

**Comment by chakri-nelluri** [comment]
@shrinandj Yes. Exit out with exit status 1 and ```{"status": "Not supported"}``` on stderr/stdout.

**Comment by shrinandj** [comment]
Thanks @chakri-nelluri .. Are you sure about exit 1? I tried the `{"status": "Not supported"}` and exit status 0 and it worked fine. 

https://gist.github.com/shrinandj/d78801a0d88dd5a47384ef64ed19a92c

**Comment by chakri-nelluri** [comment]
@shrinandj Both exit status will work fine

**Comment by chakri-nelluri** [comment]
Closing this as there is no specific issue here.
/close
