### ISSUE TITLE
Unable to mount RWX volume to multiple pods

### ISSUE THREAD

**Issue by golyalpha** [kubernetes/kubernetes#45900]
BUG REPORT

**Kubernetes version**: Whatever OpenShift currently uses

**Environment**:
RHCloud
OpenShift US East 1

**What happened**:
I am unable to mount an RWX volume to multiple pods (results in problems during deployment)

**What you expected to happen**:
Mount RWX volume to multiple pods without any problems

**How to reproduce it**:
Create an RWX volume
Create a PHP webapp (I'm using my fork of SysCrack as the source)
Add storage mount to the deployment controller (mount path: /opt/app-root/src/data)
Deploy
Deploy again (after the initial deployment finishes)

**Anything else we need to know**:
I have health checks (liveness and readiness) turned on, and have switched from Rolling to Recreate deployment strategy because of this error, it still appears sometimes in the events though.

**Comment by kargakis** [comment]
Open this issue in Openshift first and once we identify whether it's a Kubernetes issue or not, we can re-open this accordingly.

https://github.com/openshift/origin/issues
