### ISSUE TITLE
IPv6 support for hexCIDR()

### ISSUE THREAD

**Issue by pmichali** [kubernetes/kubernetes#45906]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): hexCIDR and CIDR

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): latest on master

**Environment**:
- **Cloud provider or hardware configuration**: Bare-metal, 3 node config using KubeAdm
- **OS** (e.g. from /etc/os-release): CentOS 7
- **Kernel** (e.g. `uname -a`): Linux devstack-77 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: KubeAdm
- **Others**:

**What happened**:
Investigating the code, hexCIDR() expects the CIDR passed to be for an IPv4 address and doesn't support an IPv6 CIDR.

**What you expected to happen**:
Support either IPv4 or IPv6 CIDRs.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
Will be working on a solution for this. Note: In some of the call paths, a PodIP string is used and passed in as a CIDR with a "/32" appended. At some point, this would need to be updated as well, to use "/128" if an IPv6 PodIP was used.

**Comment by pmichali** [comment]
I see there is an asciiCIDR() method too that needs addressing.

**Comment by pmichali** [comment]
One question I have...
Can the callers (bandwidth?) of the function work with an IPv6 based hex CIDR?

In the future, if we support pod IPs that are IPv6 addresses, and we modify the code to add /128 vs /32, as is done currently, this would create an IPv6 based hex CIDR.

**Comment by dcbw** [comment]
The only caller is currently the ingress/egress shaping function in kubelet.  That code also needs to be updated for IPv6.  For example, kubelet_network.go assumes IPv4 when adding CIDRs to the shaper list.

**Comment by pmichali** [comment]
@dcbw Agree.I wanted to separate this out, partly to make the change smaller, but also, when I looked at the callers (this shaping functionality) I wasn't sure if it would support IPv6. I looked a bit at the "tc" command and saw some notes that indicate that it doesn't support IPv6 yet. Is that still accurate?

Would it be ok to tackle that separately?
