### ISSUE TITLE
Flaky e2e suites with "Not ready nodes"

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#45917]
https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=Not%20ready%20nodes

Here's one sample:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-ci-master/7117

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:129
May 16 08:25:54.781: All nodes should be ready after test, Not ready nodes: ", gke-bootstrap-e2e-default-pool-50e8a0eb-xbrm"
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:349
```

**Comment by jagosan** [comment]
@fejta - any way to gather information on transient infrastructure failures?

**Comment by fejta** [comment]
Click `build-log` in the sample for the test output. Also click `artifacts` and browse through the files uploaded to gcs, which contains whatever https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump.sh collected

**Comment by msau42** [comment]
I'm looking at this test run that failed on gce, so that I can also see the master logs:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-etcd2-release-1.6/3087

From the master node controller:
I0518 11:22:14.670583       5 nodecontroller.go:1007] node bootstrap-e2e-minion-group-8g91 hasn't been updated for 40.004822832s. Last ready condition is: {Type:Ready Status:True LastHeartbeatTime:2017-05-18 11:21:33 +0000 UTC LastTransitionTime:2017-05-18 11:16:07 +0000 UTC Reason:KubeletReady Message:kubelet is posting ready status. WARNING: CPU hardcapping unsupported}

From the kubelet.log around that time, it looks like kubelet died and failed to restart because of docker failure:
I0518 11:21:29.451042    3591 prober.go:113] Readiness probe for "echoheaders-xrb5r_e2e-tests-ingress-8jgh7(1371c0b9-3bbc-11e7-852e-42010af00002):echoheaders" succeeded
I0518 11:21:29.564640    3591 eviction_manager.go:197] eviction manager: synchronize housekeeping
W0518 11:21:29.567470    3591 conversion.go:110] Could not get instant cpu stats: different number of cpus

<--- kubelet dies here

...
I0518 11:22:12.679496    2533 docker.go:364] Connecting to docker on unix:///var/run/docker.sock
I0518 11:22:12.679521    2533 docker.go:384] Start docker client with request timeout=2m0s
E0518 11:22:18.705272    2533 kube_docker_client.go:97] failed to retrieve docker version: An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/version: read unix @->/var/run/docker.sock: read: connection reset by peer
W0518 11:22:18.705350    2533 kube_docker_client.go:98] Using empty version for docker client, this may sometimes cause compatibility issue.
...
W0518 11:22:18.732334    2533 manager.go:147] Unable to connect to Docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?
W0518 11:22:18.732637    2533 manager.go:151] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused

From docker.log, docker also died and failed to restart:
time="2017-05-18T11:22:09.297713535Z" level=debug msg="Failed to load layer sha256:03fa889b4a87d703b21efcf2583575507db6852be575a0c07b766e77097daadd: failed to get diff id for sha256:03fa889b4a87d703b21efcf2583575507db6852be575a0c07b766e77097daadd: invalid checksum digest format" 
...
time="2017-05-18T11:22:18.690938457Z" level=fatal msg="Error starting daemon: layer does not exist" 

Can someone from the node team debug further?  I can help try to find the tests that were running right before this and see if any of them did anything suspicious.

**Comment by mtaufen** [comment]
```
error: failed to run Kubelet: failed to create kubelet: failed to get docker version: Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
shows up 39 times at the end of the Kubelet log on `gke-bootstrap-e2e-default-pool-50e8a0eb-xbrm` (from the [example](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-ci-master/7117/artifacts/gke-bootstrap-e2e-default-pool-50e8a0eb-xbrm/kubelet.log) @msau42  linked), so I'd definitely suspect that docker crashed.

**Comment by mtaufen** [comment]
@msau42 is this still happening or can we close this issue?

**Comment by msau42** [comment]
Yes, I think so.  Here is one that failed yesterday with the similar "Unable to connect to Docker" signature.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-etcd2-release-1-6/185
