### ISSUE TITLE
Add windows support in the docker-CRI implementation (pkg/kubelet/dockershim)

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#45927]
The legacy non-CRI implementation in the dockertools has been removed from the codebase. [Changes](https://github.com/kubernetes/kubernetes/blob/v1.6.3/pkg/kubelet/dockertools/docker_manager_windows.go) previously introduced to the dockertools package need to be ported to the new docker-CRI implementation (`pkg/kubelet/dockershim`). The port should be relatively straightforward, but manual testing is required given that there is no CI builds (or are there?).

@kubernetes/sig-windows-bugs 
@dchen1107

**Comment by pires** [comment]
No, there are no CI builds.

**Comment by yujuhong** [comment]
The 1.7 code freeze is imminent. Let me know if you need some pointers to the new code.

/cc @michmike

**Comment by yujuhong** [comment]
Applied all the necessary labels based on the new policy. 

This is needed to not cause a regression for windows support in 1.7. It's a bug, not a feature. 
@karataliu is currently working on a subsequent PRs, but the main one (#46089) has been merged.

**Comment by yujuhong** [comment]
> @karataliu is currently working on a subsequent PRs, but the main one (#46089) has been merged.

@karataliu, could you confirm that you're working on the following fixes since this issue is in the 1.7 milestone? Thanks!

**Comment by karataliu** [comment]
@yujuhong Yeah, just sent the PR 46744,. It's almost aligned with v1.6 dockertools implementation now.
Also previous windows support limitations such as single container per pod still persist. Please check the PR for detail. Thanks

**Comment by dchen1107** [comment]
I think all required prs are merged, should we close this one for 1.7 now?
