### ISSUE TITLE
FR: New kubectl command `kubectl debug`

### ISSUE THREAD

**Issue by verb** [kubernetes/kubernetes#45922]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

SIG Node is working on new functionality (feature: kubernetes/features#277 , proposal: #35584) to execute a "Debug Container" in the context of a running pod for the purposes of troubleshooting. This issue is to discuss changes needed to kubectl to surface this feature.

We're aiming for an alpha release in 1.7 that includes basic functionality. As written, the proposal in #35584 calls for a new command, `kubectl debug`, that resembles `kubectl exec`. An example run is:

```
% kubectl debug -it --image alpine $POD -c $DEBUG_CONTAINER_NAME -- sh
/ # ps x
PID   USER     TIME   COMMAND
    1 root       0:00 /pause
   13 root       0:00 /app
   26 root       0:00 sh
   32 root       0:00 ps x
/ #
```

Ideally we could have reasonable defaults so that the minimum command would be something like:
```
% kubectl debug -it
Defaulting container name to debug.
/ # 
```

One departure from `kubectl exec` is that `kubectl debug` supports reattaching to a running Debug Container with a command like `kubectl debug --reattach $POD $CONTAINER_NAME`

Options for the command would resemble:
```
Execute a Debug Container in a Pod.

Options:
  -c, --container='': Name of container to create. If omitted, the default "debug" will be used.
  -i, --stdin=false: Pass stdin to the container
  -m, --image='': Container Image to use when creating debug container. If omitted, the cluster default is used.
  -t, --tty=false: Stdin is a TTY

Usage:
  kubectl debug POD [-m IMAGE ] [-c CONTAINER] -- COMMAND [args...] [options]
```

Since this is an alpha feature it might be nice to be able to hide it in kubectl unless alpha features are enabled. It will return an error on clusters with alpha features disabled (the default).

/cc @pwittrock

**Comment by pwittrock** [comment]
How are we going to hide this?  I can think of a couple ways:

- put it under and `alpha` subcommand as is done in gcloud
- only expose it if a `--alpha` flag is provided

FYI, code freeze for 1.7 is a week from tomorrow, so this will need to be fully reviewed, approved and have all checks passing by then to make it into 1.7.

You probably want to send an MVP for review ASAP, so follow up later with anything that is non-trivial to implement and not part of the MVP.

**Comment by verb** [comment]
ack, thanks. Will dig into which is easier and create an MVP ASAP.

**Comment by verb** [comment]
Thinking about this a little bit more, it would be nice to integrate the same feature gates used with the rest of kubernetes into kubectl. I was going to add a flag to set feature gates, but this has a couple of downsides:

1. As a flag the feature gates wouldn't be able to influence behavior of other flags, and kubectl has plenty of complexity prior to flag parsing.
2. It would be nice if enabling alpha features was more persistent than a flag (which isn't a concern for the other long running daemons).

I settled on an environment variable as a decent way to do this. Using this, `kubectl debug` would be hidden and inaccessible without the alpha feature enabled by an environment variable.

**Comment by verb** [comment]
@aaron-prindle is interested in working on this.

/assign @verb

**Comment by t3hmrman** [comment]
Hey I just ran into this, I'm running `cri-containerd`(+`containerd`), and the direct `docker exec` hack of course doesn't work for me. I'm on k8s `v1.9.2` actually but instead of enabling the experimental debug option, I just went with adding my own little alpine container:

```
      - name: debug
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "sleep 100000000"]
```

And then `kubectl apply -f pod.yaml` and watch get spun up then go in. **This helped in my case since I was trying to be "amongst" the other containers to observe them**, but obviously wouldn't help you if you absolutely needed to get into the one specific container as root...

**Comment by t3hmrman** [comment]
Seems like this would be a good fit for a [`kubectl` plugin](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/)

**Comment by verb** [comment]
@t3hmrman oh that's neat, I didn't know about the plugins, I don't think they were around when I first added `kubectl alpha` to support this sort of thing. Thanks for the heads up, I'll dig into the plugins docs.

/remove-lifecycle stale

**Comment by t3hmrman** [comment]
@verb I'm also think they weren't -- I'm not sure when kubectl plugins became a thing, but I'm really hoping other operators will use them instead of building their own CLI tools. 

Currently I avoid operators that introduce their own CLI tools to manage resources (so for a concrete example, [zalando/patroni](https://github.com/zalando/patroni) over [CrunchyData/postgres-operator](https://github.com/CrunchyData/postgres-operator))

**Comment by verb** [comment]
Reopening now that #59416 has merged.

/reopen

**Comment by verb** [comment]
Working on this for 1.18.

/remove-lifecycle stale
