### ISSUE TITLE
Expose Informer constructors in generated clientsets

### ISSUE THREAD

**Issue by ash2k** [kubernetes/kubernetes#45939]
This is a feature request.

I'd like to reuse methods like [newDeploymentInformer()](https://github.com/kubernetes/kubernetes/blob/b844f7d4a4018beb664a9f0b075d83f717a631ab/staging/src/k8s.io/client-go/informers/apps/v1beta1/deployment.go#L44) but they are private at the moment.
The use case: I need to construct Informers for a specific namespace (or a set of namespaces) and instead of reusing this code I have to duplicate it many times (per object Kind). Would be awesome if Informers generator is updated to expose an additional method that does the same but also takes a namespace name as an argument. Seems to be no risk and a trivial change.
I'm more than happy to make the change myself if some guidance is provided :)

EDIT: additional details about the use case: I want to be able to limit [Smith](https://github.com/atlassian/smith) to only work with a single namespace because it may be run in a restricted environment where it only has permissions to work within a single namespace. That is a real use case: we have a cluster where a user (a team) gets very limited permissions - can only do things within their own namespace. However such team should be able to use tools like Smith.

I had to copy-paste and modify lots of code for informers I need - see https://github.com/atlassian/smith/pull/58/files#diff-e2db373b7d288a95d41535cb69e73f7d

**Comment by ncdc** [comment]
@ash2k could you expand a bit on your use case please?

**Comment by ash2k** [comment]
@ncdc @deads2k updated the first comment with more details.

**Comment by deads2k** [comment]
I'm not opposed per-se, but I think that resolving the, "show me foos in the namespaces I can see" is more like what you want.

**Comment by ash2k** [comment]
@deads2k is there a way to do this already? i.e. can a client watch only a list of specific/allowed namespaces? The list of allowed namespaces my change over time.

**Comment by deads2k** [comment]
> I'm not opposed per-se, but I think that resolving the, "show me foos in the namespaces I can see" is more like what you want.

No.  It's a "someday" idea.  Something that everybody wants, but no one has stepped up to solve in an efficient way.

**Comment by ash2k** [comment]
Another use case that just came up - I'd like to run independent integration tests concurrently, each of them in a separate namespace. Each test creates (and later deletes) a namespace with a random name for itself, then creates/updates/watches objects within this namespace so should be safe to run concurrently.
