### ISSUE TITLE
Containers of pod keep restarting while a infra container is created with future timestamp

### ISSUE THREAD

**Issue by xowind** [kubernetes/kubernetes#45942]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kill infra restart kubelet label:area/kubelet 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version** (use `kubectl version`): Kubernetes v1.5.5-beta.0.70+f2c05afaf3cbb3

**Environment**:
- **Cloud provider or hardware configuration**: bare-metal
- **OS** (e.g. from /etc/os-release): None
- **Kernel** (e.g. `uname -a`): RHEL 3.10.0-514.6.1.el7
- **Install tools**: None
- **Others**: None

**What happened**:
- Containers of pod keep restarting
- logs of kubelet:
```
I0516 17:31:48.799245   14548 docker_manager.go:1951] Syncing Pod "heapster-v1-5xjq3_kube-system(bd08f527-3952-11e7-97ec-fefcfe2b5340)": &api.Pod{.............}
I0516 17:31:48.799422   14548 docker_manager.go:1970] Need to restart pod infra container for "heapster-v1-5xjq3_kube-system(bd08f527-3952-11e7-97ec-fefcfe2b5340)" because it is not found
I0516 17:31:48.799448   14548 docker_manager.go:2015] Container {.............} is dead, but RestartPolicy says that we should restart it.
I0516 17:31:48.799462   14548 docker_manager.go:2109] Got container changes for pod "heapster-v1-5xjq3_kube-system(bd08f527-3952-11e7-97ec-fefcfe2b5340)": {.............} is dead, but RestartPolicy says that we should restart it.] ContainersToKeep:map[]}
I0516 17:31:48.799487   14548 docker_manager.go:2118] Killing Infra Container for "heapster-v1-5xjq3_kube-system(bd08f527-3952-11e7-97ec-fefcfe2b5340)", will start new one
```

**What you expected to happen**:
- everything goes fine

**How to reproduce it** (as minimally and precisely as possible):
- start kubelet and run some pods of daemonset
- change the date to one days ago and then reboot

after reboot, pods will restart peroidly

**Anything else we need to know**:

**Comment by yujuhong** [comment]
kubelet looks at the most recently created containers to determine the state of the pod, and it got fooled because the older containers had more newer timestamps.
I don't think we coded kubelet to handle changing system time. As a workaround, you can manually remove all those exited containers using docker. kubelet would then create fresh containers for you.

**Comment by xowind** [comment]
@yujuhong  thanks,  of course, It will work, if i clean the future containers on my own.
but, i also wish kubelet could do the clean , so that, I can change time of node without any serious error occurred.

**Comment by yujuhong** [comment]
@xowind that's just one thing that could go wrong. Other components might have issues too, but I can't be sure. I think supporting this is pretty low in terms of priority.

**Comment by xiangpengzhao** [comment]
Agreed with @yujuhong . I remembered that I once encountered issue after I changed system time. Not sure which components were effected, but I couldn't delete pods. These pods all got stuck.
