### ISSUE TITLE
kube proxy in proxy-based network redirects weirdly

### ISSUE THREAD

**Issue by erikbgithub** [kubernetes/kubernetes#45956]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): Nope

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): I talked to the dashboard guys in kubernetes/dashboard#1858 and they suggested to open a bug for that.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:38:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: VMWare running on my Win10 laptop
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Kernel** (e.g. `uname -a`): `Linux ubuntu 4.8.0-51-generic #54~16.04.1-Ubuntu SMP Wed Apr 26 16:00:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

- **Install tools**: what does that mean? kubeadm?
- **Others**: what others?

**What happened**:
I started kubernetes-dashboard service as guided by their readme. Then I used the shell command `kubectl proxy` which starts to serve on `localhost:8001`

Now when I open in a browser `localhost:8001/ui` it takes a loooong time, then it opens the following path `http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/` and gives my my network proxy's error message page. If I open `http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/` then I get a json response from the api server. Only with adding `proxy` this weird behaviour happens. But this is done by kube-proxy, afaik.

**What you expected to happen**: That it would open the dashboard as provided by the kubernetes-service.

**How to reproduce it** (as minimally and precisely as possible): see "What happened"

**Anything else we need to know**: My laptop runs in my company's network which has a proxy at "http://proxy:8080". In ubuntu `http_proxy`, `https_proxy`, and the same in big letters, is set to this proxy. There is also an `no_proxy` environment var set to different things including `localhost` and `127.0.0.1`. All of these are set in `/etc/environment` and in `/etc/systemd/system/docker.service.d/http-proxy.conf` as `[Service]` `Environment=` lines.

**Comment by dcbw** [comment]
Does the page load quickly if you open a browser and enter "127.0.0.1:8001/ui" instead of "localhost"?

Also, what are the contents of your `/etc/hosts` file?

**Comment by erikbgithub** [comment]
```
$ cat /etc/hosts
127.0.0.1	localhost
127.0.1.1	ubuntu

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

Same responsetime for localhost and 127.0.0.1.

The long time is probably from the network proxy, who purposefully waits for security reasons before answering requests he doesn't like.

I remembered that I can get more infos from the kubectl proxy via  `-v=9`:
```
I0519 09:29:01.954755    8862 proxy_server.go:91] /ui/ matched ^.*
I0519 09:29:01.954978    8862 proxy_server.go:91] localhost matched ^localhost$
I0519 09:29:01.955006    8862 proxy_server.go:130] Filter accepting GET /ui/ localhost
I0519 09:29:01.955204    8862 round_trippers.go:398] curl -k -v -XGET  -H "X-Forwarded-For: 127.0.0.1" -H "Upgrade-Insecure-Requests: 1" -H "User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" -H "Accept-Language: en-US,en;q=0.5" -H "Accept-Encoding: gzip, deflate" https://<host-eth0-ip>:6443/ui/
I0519 09:29:01.956465    8862 round_trippers.go:417] GET https://<host-eth0-ip>:6443/ui/ 307 Temporary Redirect in 1 milliseconds
I0519 09:29:01.956658    8862 round_trippers.go:423] Response Headers:
I0519 09:29:01.956699    8862 round_trippers.go:426]     Date: Fri, 19 May 2017 07:29:01 GMT
I0519 09:29:01.956736    8862 round_trippers.go:426]     Location: /api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy
I0519 09:29:01.956771    8862 round_trippers.go:426]     Content-Type: text/html; charset=utf-8
I0519 09:29:01.956795    8862 round_trippers.go:426]     Content-Length: 102
I0519 09:29:02.005895    8862 proxy_server.go:91] /api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/ matched ^.*
I0519 09:29:02.005929    8862 proxy_server.go:91] localhost matched ^localhost$
I0519 09:29:02.005965    8862 proxy_server.go:130] Filter accepting GET /api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/ localhost
I0519 09:29:02.006023    8862 round_trippers.go:398] curl -k -v -XGET  -H "Upgrade-Insecure-Requests: 1" -H "User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" -H "Accept-Language: en-US,en;q=0.5" -H "Accept-Encoding: gzip, deflate" -H "X-Forwarded-For: 127.0.0.1" https://<host-eth0-ip>:6443/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/
I0519 09:30:17.016216    8862 round_trippers.go:417] GET https://<host-eth0-ip>:6443/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/ 503 Service Unavailable in 75010 milliseconds
I0519 09:30:17.016263    8862 round_trippers.go:423] Response Headers:
I0519 09:30:17.016271    8862 round_trippers.go:426]     Pragma: no-cache
I0519 09:30:17.016276    8862 round_trippers.go:426]     Date: Fri, 19 May 2017 07:30:17 GMT
I0519 09:30:17.016281    8862 round_trippers.go:426]     Cache-Control: no-cache
I0519 09:30:17.016286    8862 round_trippers.go:426]     Content-Type: text/html; charset=utf-8
```

Don't know if it helps.

**Comment by wildfire-you** [comment]
Exactly the same issue with my k8s 1.6.4 based in a proxy network. The kubectl proxy shows that the request is proxied even i set the no_proxy.

I0606 10:58:42.160365   22927 round_trippers.go:417] GET https://10.1.0.11:443/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/ 504 Gateway Timeout in 155553 milliseconds
I0606 10:58:42.160401   22927 round_trippers.go:423] Response Headers:
I0606 10:58:42.160410   22927 round_trippers.go:426]     Mime-Version: 1.0
I0606 10:58:42.160417   22927 round_trippers.go:426]     Via: 1.1 proxy-1.xxxx.com:80
I0606 10:58:42.160422   22927 round_trippers.go:426]     Content-Length: 2219
I0606 10:58:42.160428   22927 round_trippers.go:426]     Content-Type: text/html
I0606 10:58:42.160434   22927 round_trippers.go:426]     Date: Tue, 06 Jun 2017 14:58:45 GMT

**Comment by wildfire-you** [comment]
Apparently, the issue disappeared when i use non-proxy mode by importing all docker images in my private registry.

**Comment by erikbgithub** [comment]
@wildfire-you You mean you took the proxy config out of the docker environment after pulling the images and then `kubectl proxy` behaves correctly? Or did you change your system environment? It's not specific enough. Sadly there isn't "The Proxy Mode" (tm). There are lot of places you can configure proxy settings, and your tools may or may not use one of them.

**Comment by erikbgithub** [comment]
@dcbw are there any updates on the issue from your side?

**Comment by wildfire-you** [comment]
@erikbgithub 
Here is the details: 
**"Proxy Mode":** 
i use the following env variables follow the kubeadm reference: https://kubernetes.io/docs/admin/kubeadm/

export PROXY_PORT=8080
export PROXY_IP=10.18.17.16
export http_proxy=http://$PROXY_IP:$PROXY_PORT
export HTTP_PROXY=$http_proxy
export https_proxy=$http_proxy
export HTTPS_PROXY=$http_proxy
export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com,example.com,10.18.17.16"

Nothing new. 

**Non-proxy mode**

So after i confirmed that it's the bug (i don't check the source codes though), i had to build my own registry within lab. and use the following env:

   export KUBE_REPO_PREFIX=gateway.wildfire.cc:5000/google_containers \
            KUBE_HYPERKUBE_IMAGE=gateway.wildfire.cc:5000/google-containers/hyperkube-amd64:v1.6.4 \
            KUBE_DISCOVERY_IMAGE=gateway.wildfire.cc:5000/google-containers/kube-discovery-amd64:1.0 \
            KUBE_ETCD_IMAGE=gateway.wildfire.cc:5000/google_containers/etcd-amd64:3.0.4

Everything works fine now.

**Comment by justinsb** [comment]
cc @kubernetes/sig-cli-bugs

**Comment by PLoic** [comment]
@erikbgithub @dcbw I try with the 1.7.1 version and I had the same behavior

**Comment by dhague** [comment]
I have the same pain with 1.7.3, as installed by kubeadm. Tried with Calico & Weavenet - same problem with both. Happens regardless of whether I go directly to the node via HTTPS or whether I use kubectl proxy locally - in each case the upstream proxy returns an error like "The following error was encountered while trying to retrieve the URL: http://localhost:8001/ - Access Denied".

It looks like the kube-proxy is directing traffic to the upstream proxy based on the address in the user's browser, which is wrong twice: (1) it is ignoring the no_proxy environment variable, and (2) it shouldn't be sending anything to the host in the browser's address bar, because with `kubectl proxy` that will be the user's own machine.
