### ISSUE TITLE
salt manifests for kube components breaks graceful termination

### ISSUE THREAD

**Issue by jsravn** [kubernetes/kubernetes#45959]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Kubernetes version** (use `kubectl version`):
1.6.3

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
All of the salt scripts bundled in kubernetes (for example, https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-apiserver/kube-apiserver.manifest) start up the component in a broken way. They use `/bin/sh -c` which means the shell will intercept all signals. So these daemons are not gracefully shutdown when the pod is stopped.

This causes serious problems since when apiserver is killed abruptly it doesn't seem to close watches correctly. This was observed in https://github.com/kubernetes/kubernetes/issues/41916 for example.

**What you expected to happen**:

Running `/bin/sh -c` is incorrect. It should run the binary directly. Otherwise, it needs to perform an `exec` so the binary correctly replaces the shell script process.

**How to reproduce it** (as minimally and precisely as possible):
Run kube-apiserver inside a container with `/bin/sh -c` and try to stop it. You can't - eventually docker will force kill it.

**Anything else we need to know**:

**Comment by kargakis** [comment]
@kubernetes/sig-cluster-lifecycle-misc

**Comment by roberthbailey** [comment]
It looks like we changed from running the binaries directly to using `/bin/sh -c` in https://github.com/kubernetes/kubernetes/pull/7316 (from @ArtfulCoder) a few years ago to enable us to capture logs. 

@dchen1107 or @lavalamp may recall why we had to use a shell since they reviewed that PR.
