### ISSUE TITLE
Make cpu limits and requests scalable to accommodate difference in node chip architecture

### ISSUE THREAD

**Issue by benmathews** [kubernetes/kubernetes#45967]
Pods are allowed to specify a [request and limit for cpu](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/). Our cluster though is composed of multiple classes of cpus. I think this has to be a very common problem as it makes little sense to replace every node when new chip architecture comes out. Replacement is always going to be a phased process.

What 100 millicore will accomplish on one chipset is far different than on another. Specifically, our cluster is composed of Dell R620 and R630 servers. The R630 servers are roughly 2.5 times as fast as the R620s. So when specifying the request CPU amount, if we specify CPU with the R630s in mind, a pod that ended up on the R620s won't have enough resources. And vice-versa, specifying CPU with the R620s in mind will waste capacity when scheduled on the R630s.

I propose that the nodes have a scaling factor assigned to them. When a pod is scheduled on a node, the CPU request and limit would be multiplied by the scaling factor. In our case, the R630s would have a factor of 1 and the R620s would be 2.5. So a pod that requested 100 millicore would get that on the R630 and get 250 millicore on the R620.

**Comment by resouer** [comment]
@davidopp This is a interesting use case, do you think it's reasonable?

**Comment by davidopp** [comment]
Yes, this is a legitimate issue. I guess the nodes would report normalized CPU in the capacity/allocatable, and limit/request would be expressed in terms of normalized CPU. Then when the pod arrives at the kubelet, kubelet would convert normalized CPU to real CPU. In a cluster where people aren't using the feature, the normalized CPU would == the real CPU. The scheduler doesn't need to know about the conversion factors.

Rolling this out is a bit tricky though.

cc/ @vishh @thockin

**Comment by benmathews** [comment]
Vertical scaling isn't relevant in my use case. These are bare metal, on-premises nodes. 

I'm not sure what cpu pinning or hardware topology have to do with the issue either.

**Comment by davidopp** [comment]
> Vertical scaling isn't relevant in my use case. These are bare metal, on-premises nodes.

Vish is referring to vertical pod scaling, so it will work on-prem. (Dynamically adjusts resource request based on recent usage.)

> I'm not sure what cpu pinning or hardware topology have to do with the issue either.

I think Vish was just listing things he thinks are higher priority than what you are asking for; I don't think they solve your problem.

Personally I think what you're asking for is pretty reasonable and not super-hard to implement.

And I realized rollout should not be a problem as long as the normalized capacity/allocatable go in new fields. We cold roll it out similar to how we rolled out allocatable.

**Comment by vishh** [comment]
Sorry if I was not clear. What I'm suggesting is that there are a few more features that will add immediate value to a broad user base that I would like the community to focus on.

The issue of CPU cycles scaling is relevant in large clusters where machines get upgraded periodically. If kubernetes were to provide such a functionality, I'd prefer it working off the box across most modern and popular CPUs. This is not an easy task.
For now, I'd recommend running a FUSE filesystem that overrides `/proc/cpuinfo` with an appropriate CPU core count, or (preferred), use node labels to include the CPU hardware architecture and have pods that are CPU latency sensitive choose specific archiitectures.
We will be adding a new concept of `resourceClasses` and we can make cpu architecture a portable part of `CPU` resource type with that.

**Comment by benmathews** [comment]
@ashokponkumar This is still a valid issue in my mind. I just got tired of marking it not stale. If you want to work on it, I'd love to reopen it and have some progress made on it.

**Comment by ashokponkumar** [comment]
Yes, @benmathews. I agree. I was looking into a similar situation. Will probably explore it offline, and then once I have a concrete proposal will come back and request you to reopen.
