### ISSUE TITLE
HPA cannot get cpu info

### ISSUE THREAD

**Issue by lyz-code** [kubernetes/kubernetes#45961]
**Kubernetes version**:

    Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** :  PRETTY_NAME="Debian GNU/Linux 8 (jessie)"

- **Kernel**:  Linux ip-************* 4.4.41-k8s #1 SMP Mon Jan 9 15:34:39 UTC 2017 x86_64 GNU/Linux

**What happened**:

HPA doesn't autoscale due to `<unknown>` CPU

**What you expected to happen**:

HPA to scale

**How to reproduce it** (as minimally and precisely as possible):

Follow the [docs walkthrough](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/)

    # kubectl run php-apache --image=gcr.io/google_containers/hpa-example --requests=cpu=200m --expose --port=80
    # kubectl autoscale deployment php-apache --cpu-percent=50 --min=1 --max=10

**Anything else we need to know**:

More information of the process:

As is of V1 and not custom metrics I guess it's not the same as [this issue](https://github.com/kubernetes/kubernetes/issues/45581)

    # kubectl run php-apache --image=gcr.io/google_containers/hpa-example --requests=cpu=200m --expose --port=80
    service "php-apache" created
    deployment "php-apache" created

With this trace in the controller-log:

    I0517 12:48:32.338309       5 event.go:217] Event(api.ObjectReference{Kind:"Deployment", Namespace:"default", Name:"php-apache", UID:"22367ba1-3aff-11e7-adea-02eb61d566f9", APIVersion:"extensions", ResourceVersion:"2104061", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set php-apache-3815965786 to 1
    I0517 12:48:32.340626       5 replica_set.go:479] Too few "default"/"php-apache-3815965786" replicas, need 1, creating 1
    I0517 12:48:32.362854       5 deployment_controller.go:298] Error syncing deployment default/php-apache: Operation cannot be fulfilled on deployments.extensions "php-apache": the object has been modified; please apply your changes to the latest version and try again
    I0517 12:48:32.374723       5 event.go:217] Event(api.ObjectReference{Kind:"ReplicaSet", Namespace:"default", Name:"php-apache-3815965786", UID:"2238932c-3aff-11e7-91f9-0ad67bfb8763", APIVersion:"extensions", ResourceVersion:"2104062", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: php-apache-3815965786-h4d9l
    I0517 12:48:32.394514       5 deployment_controller.go:298] Error syncing deployment default/php-apache: Operation cannot be fulfilled on deployments.extensions "php-apache": the object has been modified; please apply your changes to the latest version and try again
    I0517 12:48:32.642073       5 servicecontroller.go:305] Not persisting unchanged LoadBalancerStatus to registry.

This is the yaml of the template:

    # kubectl get deployment php-apache -o yaml
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      annotations:
        deployment.kubernetes.io/revision: "1"
      creationTimestamp: 2017-05-17T12:48:32Z
      generation: 1
      labels:
        run: php-apache
      name: php-apache
      namespace: default
      resourceVersion: "2104081"
      selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/php-apache
      uid: 22367ba1-3aff-11e7-adea-02eb61d566f9
    spec:
      replicas: 1
      selector:
        matchLabels:
          run: php-apache
      strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
        type: RollingUpdate
      template:
        metadata:
          creationTimestamp: null
          labels:
            run: php-apache
        spec:
          containers:
          - image: gcr.io/google_containers/hpa-example
            imagePullPolicy: Always
            name: php-apache
            ports:
            - containerPort: 80
              protocol: TCP
            resources:
              requests:
                cpu: 200m
            terminationMessagePath: /dev/termination-log
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 30
    status:
      availableReplicas: 1
      conditions:
      - lastTransitionTime: 2017-05-17T12:48:32Z
        lastUpdateTime: 2017-05-17T12:48:32Z
        message: Deployment has minimum availability.
        reason: MinimumReplicasAvailable
        status: "True"
        type: Available
      observedGeneration: 1
      replicas: 1
      updatedReplicas: 1

I was able to create the hpa without problems

    # kubectl autoscale deployment php-apache --cpu-percent=50 --min=1 --max=10
    deployment "php-apache" autoscaled

    # kubectl get hpa php-apache -o yaml
    apiVersion: autoscaling/v1
    kind: HorizontalPodAutoscaler
    metadata:
      creationTimestamp: 2017-05-17T13:05:34Z
      name: php-apache
      namespace: default
      resourceVersion: "2105863"
      selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/php-apache
      uid: 834882f8-3b01-11e7-adea-02eb61d566f9
    spec:
      maxReplicas: 10
      minReplicas: 1
      scaleTargetRef:
        apiVersion: extensions/v1beta1
        kind: Deployment
        name: php-apache
      targetCPUUtilizationPercentage: 50
    status:
      currentReplicas: 0
      desiredReplicas: 0

The last command gave no trace in the log

    # kubectl get hpa
    NAME                   REFERENCE                         TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
    php-apache             Deployment/php-apache             <unknown> / 50%   1         10        0          1h

The pod is alive:

    # kubectl describe pod php-apache-3815965786-w7cnr
    Name:		php-apache-3815965786-w7cnr
    Namespace:	default
    Node:		***********************
    Start Time:	Wed, 17 May 2017 13:17:57 +0200
    Labels:		pod-template-hash=3815965786
        run=php-apache
    Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"php-apache-3815965786","uid":"7adbadd9-3af2-11e7-91f9-0ad67bfb87...
        kubernetes.io/limit-ranger=LimitRanger plugin set: memory request for container php-apache; cpu, memory limit for container php-apache
    Status:		Running
    IP:		**************
    Controllers:	ReplicaSet/php-apache-3815965786
    Containers:
      php-apache:
        Container ID:	docker://f1bf3e8bba200a255432d48876779c26b95f9dc5ba75a70b046163cf635cd91f
        Image:		gcr.io/google_containers/hpa-example
        Image ID:		docker-pullable://gcr.io/google_containers/hpa-example@sha256:581697a37f0e136db86d6b30392f0db40ce99c8248a7044c770012f4e8491544
        Port:		80/TCP
        State:		Running
          Started:		Wed, 17 May 2017 13:18:34 +0200
        Ready:		True
        Restart Count:	0
        Limits:
          cpu:	1
          memory:	1024M
        Requests:
          cpu:		200m
          memory:		256M
        Environment:	<none>
        Mounts:
          /var/run/secrets/kubernetes.io/serviceaccount from default-token-r3p1w (ro)
    Conditions:
      Type		Status
      Initialized 	True
      Ready 	True
      PodScheduled 	True
    Volumes:
      default-token-r3p1w:
        Type:	Secret (a volume populated by a Secret)
        SecretName:	default-token-r3p1w
        Optional:	false
    QoS Class:	Burstable
    Node-Selectors:	<none>
    Tolerations:	<none>
    Events:		<none>

But the hpa is unable to get the information of the CPU:

    # kubectl describe hpa php-apache
    Name:							php-apache
    Namespace:						default
    Labels:							<none>
    Annotations:						<none>
    CreationTimestamp:					Wed, 17 May 2017 13:18:06 +0200
    Reference:						Deployment/php-apache
    Metrics:						( current / target )
      resource cpu on pods  (as a percentage of request):	<unknown> / 50%
    Min replicas:						1
    Max replicas:						10
    Events:							<none>

Nevertheless, you can get CPU stats from Heapster service cluster IP, you can see the stats in the dashboard and they are being collected by influxdb and grafana:

    # kubectl exec busyboxplus -- curl http://100.96.7.2:8082/api/v1/model/namespaces/default/pods/php-apache-3815965786-w7cnr/metrics/cpu-usage
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
    100   737  100   737    0     0   275k      0 --:--:-- --:--:-- --:--:--  359k
    {
      "metrics": [
       {
        "timestamp": "2017-05-17T12:39:00Z",
        "value": 0
       },
       {
        "timestamp": "2017-05-17T12:40:00Z",
        "value": 0
       },
       {
        "timestamp": "2017-05-17T12:41:00Z",
        "value": 0
       },
       {
        "timestamp": "2017-05-17T12:42:00Z",
        "value": 0
       },
       {
        "timestamp": "2017-05-17T12:43:00Z",
        "value": 0
       },
       {
        "timestamp": "2017-05-17T12:44:00Z",
        "value": 0
       },
       {
        "timestamp": "2017-05-17T12:45:00Z",
        "value": 0
       },
       {
        "timestamp": "2017-05-17T12:46:00Z",
        "value": 0
       },
       {
        "timestamp": "2017-05-17T12:47:00Z",
        "value": 0
       },
       {
        "timestamp": "2017-05-17T12:48:00Z",
        "value": 0
       }
      ],
      "latestTimestamp": "2017-05-17T12:48:00Z"

The difference between the rest of questions regarding this topic is that I get Events <none>.

The logs of the heapster (started with `--v=4` as indicated [here](https://github.com/openshift/origin/issues/6293)) show no errors.

The answer given [here](http://stackoverflow.com/questions/38127763/kubernetes-hpa-not-working-failed-to-unmarshall-heapster-response) pointing to [the openshift bug](https://github.com/openshift/origin/issues/6293) doesn't work as I'm able to execute the same curl to heapster in every node or master.

I've also tried with other deployments setting the resources in the deployment, checking that they are set up in the pods.

Any idea?

**Comment by cmluciano** [comment]
cc @kubernetes/sig-apps-bugs

**Comment by davidopp** [comment]
@kubernetes/sig-autoscaling-bugs

**Comment by fgrzadkowski** [comment]
@mwielgus Please debug or reassign to someone in the team?

**Comment by lyz-code** [comment]
I've checked in other cluster I have deployed also through kops and it works. Here are the differences between the clusters:

## HPA working cluster
* 1 master, 4 nodes
* Networking: kubenet
```yaml
  networking:
    kubenet: {}
```

* Topology: public
```yaml
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

## HPA **not** working cluster
* 3 masters, 4 nodes
* Networking: canal
```yaml
  networking:
    canal: {}
```

* Topology: private
```yaml
  topology:
    bastion:
      bastionPublicName: bastion.**********************
    dns:
      type: Public
    masters: private
    nodes: private
```

I've also tried to execute the curl command from the kube-controller-manager with success, from what I've read the controller-manager queries the heapster service but I don't know how it does it.

Another thing I've seen is that it doesn't resolve the dns `heapster` don't know if it's the correct behavior

```bash
# Works
curl http://100.68.23.252/api/v1/model/namespaces/default/pods/php-apache-3815965786-w7cnr/metrics/cpu-usage
# Doesn't Work
curl http://heapster/api/v1/model/namespaces/default/pods/php-apache-3815965786-w7cnr/metrics/cpu-usage
```

Here is the description of the service
```yaml
Name:			heapster
Namespace:		kube-system
Labels:			kubernetes.io/cluster-service=true
			kubernetes.io/name=Heapster
			task=monitoring
Annotations:		<none>
Selector:		k8s-app=heapster
Type:			ClusterIP
IP:			100.68.23.252
Port:			<unset>	80/TCP
Endpoints:		100.96.7.2:8082
Session Affinity:	None
Events:			<none>
```

Also here is the configuration of the Canal daemonset

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"DaemonSet","apiVersion":"extensions/v1beta1","metadata":{"name":"canal","namespace":"kube-system","creationTimestamp":null,"labels":{"k8s-app":"canal"}},"spec":{"selector":{"matchLabels":{"k8s-app":"canal"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"k8s-app":"canal"},"annotations":{"scheduler.alpha.kubernetes.io/critical-pod":"","scheduler.alpha.kubernetes.io/tolerations":"[{\"key\":
      \"dedicated\", \"value\": \"master\", \"effect\": \"NoSchedule\" },\n {\"key\":\"CriticalAddonsOnly\",
      \"operator\":\"Exists\"}]\n"}},"spec":{"volumes":[{"name":"lib-modules","hostPath":{"path":"/lib/modules"}},{"name":"var-run-calico","hostPath":{"path":"/var/run/calico"}},{"name":"cni-bin-dir","hostPath":{"path":"/opt/cni/bin"}},{"name":"cni-net-dir","hostPath":{"path":"/etc/cni/net.d"}},{"name":"run","hostPath":{"path":"/run"}},{"name":"flannel-cfg","configMap":{"name":"canal-config"}}],"containers":[{"name":"calico-node","image":"calico/node:v1.0.2","env":[{"name":"DATASTORE_TYPE","value":"kubernetes"},{"name":"FELIX_LOGSEVERITYSYS","value":"info"},{"name":"CALICO_NETWORKING_BACKEND","value":"none"},{"name":"CALICO_DISABLE_FILE_LOGGING","value":"true"},{"name":"IP"},{"name":"HOSTNAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}}],"resources":{"requests":{"cpu":"10m"}},"volumeMounts":[{"name":"lib-modules","readOnly":true,"mountPath":"/lib/modules"},{"name":"var-run-calico","mountPath":"/var/run/calico"}],"securityContext":{"privileged":true}},{"name":"install-cni","image":"calico/cni:v1.5.6","command":["/install-cni.sh"],"env":[{"name":"CNI_NETWORK_CONFIG","valueFrom":{"configMapKeyRef":{"name":"canal-config","key":"cni_network_config"}}},{"name":"KUBERNETES_NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}}],"resources":{"requests":{"cpu":"10m"}},"volumeMounts":[{"name":"cni-bin-dir","mountPath":"/host/opt/cni/bin"},{"name":"cni-net-dir","mountPath":"/host/etc/cni/net.d"}]},{"name":"kube-flannel","image":"quay.io/coreos/flannel:v0.7.0","command":["/opt/bin/flanneld","--ip-masq","--kube-subnet-mgr"],"env":[{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"FLANNELD_IFACE","valueFrom":{"configMapKeyRef":{"name":"canal-config","key":"canal_iface"}}},{"name":"FLANNELD_IP_MASQ","valueFrom":{"configMapKeyRef":{"name":"canal-config","key":"masquerade"}}}],"resources":{"requests":{"cpu":"10m"}},"volumeMounts":[{"name":"run","mountPath":"/run"},{"name":"flannel-cfg","mountPath":"/etc/kube-flannel/"}],"securityContext":{"privileged":true}}],"hostNetwork":true}}},"status":{"currentNumberScheduled":0,"numberMisscheduled":0,"desiredNumberScheduled":0,"numberReady":0}}'
  creationTimestamp: 2017-04-12T08:35:17Z
  generation: 2
  labels:
    k8s-app: canal
  name: canal
  namespace: kube-system
  resourceVersion: "1107372"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/daemonsets/canal
  uid: f4d1b25b-1f5a-11e7-9565-0aac9b51609b
spec:
  selector:
    matchLabels:
      k8s-app: canal
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        scheduler.alpha.kubernetes.io/tolerations: |
          [{"key": "dedicated", "value": "master", "effect": "NoSchedule" },
           {"key":"CriticalAddonsOnly", "operator":"Exists"}]
      creationTimestamp: null
      labels:
        k8s-app: canal
    spec:
      containers:
      - env:
        - name: DATASTORE_TYPE
          value: kubernetes
        - name: FELIX_LOGSEVERITYSYS
          value: info
        - name: CALICO_NETWORKING_BACKEND
          value: none
        - name: CALICO_DISABLE_FILE_LOGGING
          value: "true"
        - name: IP
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
          value: ACCEPT
        image: calico/node:v1.0.2
        imagePullPolicy: IfNotPresent
        name: calico-node
        resources:
          requests:
            cpu: 10m
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /var/run/calico
          name: var-run-calico
      - command:
        - /install-cni.sh
        env:
        - name: CNI_NETWORK_CONFIG
          valueFrom:
            configMapKeyRef:
              key: cni_network_config
              name: canal-config
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: calico/cni:v1.5.6
        imagePullPolicy: IfNotPresent
        name: install-cni
        resources:
          requests:
            cpu: 10m
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          name: cni-bin-dir
        - mountPath: /host/etc/cni/net.d
          name: cni-net-dir
      - command:
        - /opt/bin/flanneld
        - --ip-masq
        - --kube-subnet-mgr
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: FLANNELD_IFACE
          valueFrom:
            configMapKeyRef:
              key: canal_iface
              name: canal-config
        - name: FLANNELD_IP_MASQ
          valueFrom:
            configMapKeyRef:
              key: masquerade
              name: canal-config
        image: quay.io/coreos/flannel:v0.7.0
        imagePullPolicy: IfNotPresent
        name: kube-flannel
        resources:
          requests:
            cpu: 10m
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /run
          name: run
        - mountPath: /etc/kube-flannel/
          name: flannel-cfg
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /lib/modules
        name: lib-modules
      - hostPath:
          path: /var/run/calico
        name: var-run-calico
      - hostPath:
          path: /opt/cni/bin
        name: cni-bin-dir
      - hostPath:
          path: /etc/cni/net.d
        name: cni-net-dir
      - hostPath:
          path: /run
        name: run
      - configMap:
          defaultMode: 420
          name: canal-config
        name: flannel-cfg
status:
  currentNumberScheduled: 7
  desiredNumberScheduled: 7
  numberMisscheduled: 0
  numberReady: 7
```

**Comment by DirectXMan12** [comment]
Are there any relevant controller manager logs from the HPA controller, or events on the HPA object?

Since the change to making this work was a networking fix, if I had to guess, someone's not quite talking correctly to another component.  The metrics client in Kubernetes 1.5 uses the API server service proxy to talk to Heapster, so you'll need to make sure the master can contact pods.

**Comment by lyz-code** [comment]
Here is everything in the controller manager logs:

```
W0522 00:21:31.568626       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2940146/2939312]) [2941145]
W0522 00:35:39.573149       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2941990/2941147]) [2942989]
W0522 00:49:42.578290       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2943823/2942991]) [2944822]
W0522 00:57:56.582306       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2944899/2944825]) [2945898]
W0522 01:13:31.587290       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2946931/2945901]) [2947930]
W0522 01:22:30.591300       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2948107/2947935]) [2949106]
W0522 01:39:31.596244       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2950324/2949107]) [2951323]
W0522 01:52:44.600475       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2952051/2951329]) [2953050]
W0522 02:08:39.605333       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2954130/2953055]) [2955129]
W0522 02:16:54.609182       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2955203/2955131]) [2956202]
W0522 02:26:40.612827       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2956481/2956208]) [2957480]
W0522 02:37:48.619510       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2957933/2957485]) [2958932]
W0522 02:45:59.623577       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2959002/2958938]) [2960001]
W0522 02:55:08.630330       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2960198/2960006]) [2961197]
W0522 03:08:18.635238       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2961917/2961199]) [2962916]
W0522 03:19:25.640118       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2963366/2962919]) [2964365]
W0522 03:32:04.644774       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2965020/2964366]) [2966019]
W0522 03:48:03.649958       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2967103/2966021]) [2968102]
W0522 04:00:55.661420       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2968783/2968106]) [2969782]
W0522 04:10:35.665493       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2970043/2969785]) [2971042]
W0522 04:24:59.671145       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2971921/2971044]) [2972920]
W0522 04:34:27.705806       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2973157/2972924]) [2974156]
W0522 04:43:16.709667       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2974309/2974160]) [2975308]
W0522 04:52:50.713613       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2975557/2975312]) [2976556]
W0522 05:05:08.731137       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2977164/2976560]) [2978163]
W0522 05:13:30.739386       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2978258/2978166]) [2979257]
W0522 05:22:23.743334       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2979416/2979259]) [2980415]
W0522 05:31:25.747289       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2980596/2980419]) [2981595]
W0522 05:40:59.751196       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2981844/2981598]) [2982843]
W0522 05:55:27.756095       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2983732/2982845]) [2984731]
W0522 06:05:08.760114       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2984998/2984735]) [2985997]
W0522 06:13:06.766282       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2986036/2985998]) [2987035]
W0522 06:27:08.771905       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2987869/2987040]) [2988868]
W0522 06:36:59.776240       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2989155/2988872]) [2990154]
W0522 06:45:01.780754       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2990204/2990156]) [2991203]
W0522 06:55:00.785302       5 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2991508/2991208]) [2992507]
```

All the HPA shows `Events:    <none>`

About the master being able to connect to the pods. The test I made is to wget from the controller-manager to one of the pods, If there is a more precise test please let me know:

```bash
/tmp # wget 100.96.8.6:8080/health
Connecting to 100.96.8.6:8080 (100.96.8.6:8080)
health               100% |**********************************************|   970   0:00:00 ETA
/tmp # cat health 
{"description":"Spring Cloud Eureka Discovery Client","status":"UP","discoveryComposite":{"description":"Spring Cloud Eureka Discovery Client","status":"UP","discoveryClient":{"description":"Spring Cloud Eureka Discovery Client","status":"UP","services":["******","*******","*******","eureka-server","zuul","config-server","*******","*********","*******"]},"eureka":{"description":"Remote status from Eureka server","status":"UP","applications":{"********":3,"********":2,"*********":1,"EUREKA-SERVER":2,"ZUUL":2,"CONFIG-SERVER":2,"*******":1,"**********":1,"***********":2}}},"diskSpace":{"status":"UP","total":7916150784,"free":1433214976,"threshold":10485760},"refreshScope":{"status":"UP"},"configServer":{"status":"UP","propertySources":["configClient","https://*******.git#pro","https://*************.git/********#pro"]},"hystrix":{"status":"UP"}}/tmp
```

Thank you for helping me debug this :)

**Comment by DirectXMan12** [comment]
Wait, what log level are you running at?  That's all that's in your controller manager logs?  Can you bump up the log level on the controller manager to `--v=4` or `--v=6`?  You should then see regular messages from the HPA controller.

> If there is a more precise test please let me know

`curl $MASTER_IP/api/v1/namespaces/kube-system/services/heapster/proxy/apis/metrics/v1alpha1/nodes` is what the HPA controller does.

**Comment by lyz-code** [comment]
I'm trying to raise the verbosity of the kube-controller-manager from --v=2 to --v=4, but I don't see the deployment/replicaset/replicacontroler/daemonset/job of the kube-controller-manager, but if I delete the pod to recreate with a modified yaml it gets recreated. I've also tried getting into the pod,
killing the process and launching it with --v=4 but obviously the pod gets killed.... So any hint on how to raise the verbosity?

**Comment by lyz-code** [comment]
From inside the controller pod (which doesn't have curl) I can verify that it's arriving to the api server, but the pod doesn't have the openssl installed therefore I get no result

```bash
/tmp # wget https://***master-1-ip***/api/v1/namespaces/kube-system/services/heapster/proxy/apis/me
trics/v1alpha1/nodes --no-check-certificate
Connecting to ***master-1-ip*** (***master-1-ip***:443)
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer
```

From the master instance host of that pod I can do the same query for the 3 master IPs with the  unauthorized result:

```bash
admin@ip-***master-1-ip***:/tmp$ wget https://***master-1-ip***/api/v1/namespaces/kube-system/services/heapster/proxy/apis/metrics/v1alpha1/nodes --no-check-certificate
--2017-05-24 10:42:47--  https://***master-1-ip***/api/v1/namespaces/kube-system/services/heapster/proxy/apis/metrics/v1alpha1/nodes
Connecting to ***master-1-ip***:443... connected.
WARNING: The certificate of ‘***master-1-ip***’ is not trusted.
WARNING: The certificate of ‘***master-1-ip***’ hasn't got a known issuer.
The certificate's owner does not match hostname ‘***master-1-ip***’
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
admin@ip-***master-1-ip***:/tmp$ wget https://***master-2-ip***/api/v1/namespaces/kube-system/services/heapster/proxy/apis/metrics/v1alpha1/nodes --no-check-certificate
--2017-05-24 10:43:33--  https://***master-2-ip***/api/v1/namespaces/kube-system/services/heapster/proxy/apis/metrics/v1alpha1/nodes
Connecting to ***master-2-ip***:443... connected.
WARNING: The certificate of ‘***master-2-ip***’ is not trusted.
WARNING: The certificate of ‘***master-2-ip***’ hasn't got a known issuer.
The certificate's owner does not match hostname ‘***master-2-ip***’
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
```

**Comment by lyz-code** [comment]
Redeploying the same cluster in the same infrastructure with the same configuration... worked

(╯°□°)╯ ┻━┻

**Comment by aabed** [comment]
Seeing the same problem

**Comment by padgyx** [comment]
You should install heapster to get the metrics for resource cpu:

```
Events:
  Type     Reason                        Age              From                       Message
  ----     ------                        ----             ----                       -------
  Warning  FailedGetResourceMetric       5m (x2 over 6m)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: no metrics returned from heapster
  Warning  FailedComputeMetricsReplicas  5m (x2 over 6m)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from heapster
  Normal   SuccessfulRescale             5m               horizontal-pod-autoscaler  New size: 4; reason: cpu resource utilization (percentage of request) above target
  Normal   SuccessfulRescale             1m               horizontal-pod-autoscaler  New size: 8; reason: cpu resource utilization (percentage of request) above target
```

**Comment by caarlos0** [comment]
for me, only a few HPA are not working... very weird...
