### ISSUE TITLE
Federation service configured NodePort can not be used for service discovery cross cluster with coredns in 1.6

### ISSUE THREAD

**Issue by James-Dao** [kubernetes/kubernetes#45963]
Kubernetes version (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

Environment:

Cloud provider or hardware configuration: no cloud provider ,just bare mental
OS (e.g. from /etc/os-release): centos 7.2
Kernel (e.g. uname -a): 3.10.0-327.el7.x86_64
Install tools: coredns
Others:
What happened:
In office data center, there is no cloud provider , just run on bare mental,  federation service configured NodePort can not be create in the etcd which is used for federation controller manager and coredns, so coredns container logs always says skydns2 not found, so the service discovery cross cluster can not complete. 

What you expected to happen:
I expect federation service configured NodePort can be used for service discovery cross cluster and data center.

**Comment by James-Dao** [comment]
The ServiceType of Federation Service must be LoadBalance?

**Comment by shashidharatd** [comment]
Yes currently we support only LoadBalancer type of services for federation(cross-cluster) service discovery.
