### ISSUE TITLE
401/403 apiserver errors do not return 'Status' objects

### ISSUE THREAD

**Issue by ankon** [kubernetes/kubernetes#45970]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): "status forbidden unauthorized"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Kubernetes version** (use `kubectl version`):

Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: minikube 0.18.0 / kubernetes 1.5.3
- **OS** (e.g. from /etc/os-release): 
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

I'm trying to query the API server and am getting unexpected results like `Forbidden: "/apis"` when not providing (enough) credentials.

**What you expected to happen**:

According to https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#http-status-codes I expected the server to return a Status object with status = 'Failure' and code = 403/401.

**How to reproduce it** (as minimally and precisely as possible):

`curl -k API-SERVER-URL/apis`

**Anything else we need to know**:

I'm writing a client library, and want to handle errors properly, so any additional help/information or insights into the why of this behavior are very welcome as well :)

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by smarterclayton** [comment]
@deads2k knows why this happens

**Comment by sttts** [comment]
The reason is probably here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/errors.go#L46

**Comment by sttts** [comment]
We have quite a number of error code paths which do not write Status object, not only "forbidden". It's mostly a matter of wiring through the context and serializer.

**Comment by shiywang** [comment]
@sttts I would like to take a look at this, so all I need to do is complete those Status objects right ?

**Comment by sttts** [comment]
@shiywang yes. It's mostly a plumbing problem. You need a request context and a serializer at those place. We do not wire through them consequently though. I am doing similar work right now for auditing, i.e. getting the context to a number of places: https://github.com/kubernetes/kubernetes/pull/45766/commits/aadccb3b6fe9f5fa4d9d9e8ce0283621b72f70a4.
