### ISSUE TITLE
Architectural changes for scheduler perf

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#45973]
As  part of  #44770, we started re-architecting scheduler perf but retracted to have backwards compatibility. In order to have robust scheduler performance and scale testing, we need to ensure complex scenarios like multiple combinations of predicates and priorities are tested.

The problem with current scheduler perf is that we are defining strategies where choose predefined subset of given nodes and pods to have the priority or predicate and we are generating either a podlist or node list at the end of it because of which we are not able to add multiple predicates or priorities to same node or pod at a time. So, in order to avoid this, we recommend to have a podSpec and nodeSpec being mutated so as to include multiple predicates and priorities. Only a subset of pods or nodes from given number of nodes or pods are going to have them. 

In a way, this becomes a binomial distribution where a node or pod is going to have all the predicates and priorities to be evaluated or none.

**Comment by gmarek** [comment]
I'm fine with any changes, as long as we'll end up with the same-ish API as cluster loader.

**Comment by jayunit100** [comment]
Go ahead and attach a PR and let's make sure its orthogonal to the other improvements we're making so we can progress in parallel.

**Comment by gmarek** [comment]
@sjug

**Comment by sjug** [comment]
@gmarek I'll review it with Jay, no worries
