### ISSUE TITLE
pull-kubernetes-federation-e2e-gce is flaky

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#45978]
from @nikhita on https://github.com/kubernetes/test-infra/issues/2787

I keep hitting this flake: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45721/pull-kubernetes-federation-e2e-gce/5138/. Noticed that most of the recently updated PRs are failing on this one. See also: kubernetes/kubernetes#42072.

I mentioned this in the sig-testing channel as well and wasn't sure if I should be mentioning in the above issue or create a new one in this repo but thought it would be better to document it here. :)

@kubernetes/sig-federation-test-failures 
/kind flake

**Comment by csbell** [comment]
The clusters have been re-cycled (jenkins job re-build) and test runs are
passing as of ~10:10 PDT. We'll have to figure out why the base clusters
timed out.

**Comment by madhusudancs** [comment]
This was an infrastructure issue. @shashidharatd and @irfanurrehman who were around when this happened both noticed this but they did not have access to Jenkins to manually trigger a new run. We will prioritize moving the federation presubmit deploy job from Jenkins to prow. 

Filed an issue here - https://github.com/kubernetes/test-infra/issues/2791

**Comment by foxish** [comment]
The same issue appears to be happening again with https://github.com/kubernetes/kubernetes/pull/46071 and https://github.com/kubernetes/kubernetes/pull/46071

**Comment by madhusudancs** [comment]
Thanks! We are debugging this. We have made federation presubmits non-blocking for now. You should be able to merge PRs without that job passing.

**Comment by kargakis** [comment]
Can't seem to get past this flake in https://github.com/kubernetes/kubernetes/pull/46169

**Comment by kargakis** [comment]
Ok, just saw @madhusudancs's comment and it seems that the PR is in the queue, sorry for the noise

**Comment by xiao-zhou** [comment]
My PR hit this flaky test as well https://github.com/kubernetes/kubernetes/pull/46213

**Comment by pmichali** [comment]
In my PR [#46138](https://github.com/kubernetes/kubernetes/pull/46138), I see this fail **and** pull-kubernetes-kubemark-e2e-gce and pull-kubernetesnode-e2e. Not sure if flakes should be generated for the other two tests.

**Comment by ncdc** [comment]
@pmichali as we discussed on slack, the other 2 failures were most likely related to changes in your PR itself and not actual flakes.

**Comment by pmichali** [comment]
Corrected the other two issues with my latest commit on #46138, but still see this issue.

**Comment by janetkuo** [comment]
Is it flaky or broken? I haven't seen it pass

**Comment by perotinus** [comment]
It's flaky: https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-federation-e2e-gce

There was a fix yesterday for one issue that was causing flakiness, but it appears that it was not comprehensive. We're looking into this.

**Comment by perotinus** [comment]
This appears to have been fixed by recycling the clusters: the issue that was fixed earlier was merged in on May 25, after the daily cluster recycling. So, some clusters were left in a bad state because of previous failures. Once the clusters were recycled on the morning of the 26th, the tests stopped being flaky.

**Comment by caesarxuchao** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45184/pull-kubernetes-federation-e2e-gce/8189/

**Comment by caesarxuchao** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46500/pull-kubernetes-federation-e2e-gce/8463/

**Comment by caesarxuchao** [comment]
I'm reopening the issue. @madhusudancs could you take a look? Since the error message is `error during ./federation/cluster/federation-up.sh: exit status 255`, so it might be a test-infra issue.

**Comment by madhusudancs** [comment]
@caesarxuchao this test ran when we had just fixed the test infra issue and redeploying things. You shouldn't see this problem if you re-run the test now.

**Comment by caesarxuchao** [comment]
Thanks. Closing.

**Comment by pmichali** [comment]
@madhusudancs I still see this issue (I think it is this) on #46138 and #46874. Can you please advise?

**Comment by sttts** [comment]
Here is a recent log: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46138/pull-kubernetes-federation-e2e-gce/13815/

**Comment by pmichali** [comment]
I see a few other people have the same log messages as what I see. The failure seems consistently occurring (I tried retest 2x).

**Comment by mattmoyer** [comment]
There's another recent string of failures for this: https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-federation/?

For example, the most recent: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-federation/5221/
```
W0713 15:10:55.034] 2017/07/13 15:10:54 main.go:191: Something went wrong: error starting federation: error during ./federation/cluster/federation-up.sh: exit status 124
W0713 15:10:
```

**Comment by csbell** [comment]
Looking into it.

**Comment by perotinus** [comment]
I believe this has been addressed.
