### ISSUE TITLE
Implement a library/tool for processing and transforming the etcd state

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#45974]
It may be useful to build some kind of library for working with the etcd databases from Kubernetes masters. If you build such a library it can be useful for lots of applications, such as removing sensitive information before sharing the state for debugging by a third party, repairing corrupted/buggy state, creating artificial workloads for benchmarking, etc. It would let you do these operations directly in terms of API objects (rather than just the raw protos used as the key values).

cc/ @sig-api-machinery-feature-requests @wojtek-t @gmarek @crassirostris

**Comment by wojtek-t** [comment]
@xiang90 @hongchaodeng

**Comment by grodrigues3** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by erictune** [comment]
btw, David, We are trying to use SIG in favor of Area labels.

**Comment by mml** [comment]
@ddurgadas FYI @jpbetz has been working on a tool for this.

**Comment by xiang90** [comment]
@mml  @jpbetz 

@hongchaodeng and me will be happy to review the code. ping us when the tool is ready for a review. thank you!

**Comment by jpbetz** [comment]
@hongchaodeng We've got an early version of this db inspection tool. I've sent you, @xiang90  and @heyitsanthony invites to the repo.

I'll submit the repo as a kubernetes incubator project shortly. Are any of you interested in being listed as a contributor as part of the incubator project creation request? (It's helpful to have engineers from more than just one company on project requests)

**Comment by xiang90** [comment]
@jpbetz thanks. will take a look shortly.

**Comment by jpbetz** [comment]
@hongchaodeng, @xiang90, @heyitsanthony,

Thanks for the reviews! I'll be applying the feedback today.

Are any of you interested in being listed as an owner for Kubernetes incubator proposal purposes? For a small project like this the time commitment will be very small to negligible. I plan to send out the proposal Monday.

**Comment by davidopp** [comment]
https://groups.google.com/d/msg/kubernetes-dev/xl1iqh9vHbY/DByARJDIAQAJ
