### ISSUE TITLE
Phased, or partial, rolling deployments

### ISSUE THREAD

**Issue by ae6rt** [kubernetes/kubernetes#46003]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

```
Partial rolling deployments in kubernetes
```

**Feature request**

As a cluster operator, I would like the ability to control the number of updated pods that are deployed during a Deployment rolling update.  For example, if the number of replicas in a Deployment is 3, and I call for a rolling deployment to the next version of my application, I would like some way to tell the Deployment to update only one pod to the new application version, then pause until further notice.  At this point I ask my QA engineers to test the updated pod.  When QA signs off, I ask the deployment controller to update the other 2 pods in the Deployment to the new version.

cc @janetkuo at Tim Hockin's suggestion.

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by janetkuo** [comment]
Please see issue #11505 where we discussed similar feature request. At this moment you'll need to use multiple deployments to achieve this. Feel free to comment in that issue about your thoughts or suggestions. 

Closing this as dup of #11505. Please reopen it if #11505 doesn't fully cover your request.

**Comment by thockin** [comment]
I knew there had to be an issue for this already :)
