### ISSUE TITLE
CUDA_VISIBLE_DEVICES not set, no way to tell which devices were reserved

### ISSUE THREAD

**Issue by 8enmann** [kubernetes/kubernetes#46007]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
yes

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
CUDA_VISIBLE_DEVICES

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T22:51:55Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Cloud provider or hardware configuration**:
Baremetal
- **OS** (e.g. from /etc/os-release):
```
AME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
```
- **Kernel** (e.g. `uname -a`):
Node:
```
4.4.0-75-generic #96~14.04.1-Ubuntu SMP Thu Apr 20 11:06:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
Pod:
```
Linux busybox2 4.4.0-75-generic #96~14.04.1-Ubuntu SMP Thu Apr 20 11:06:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- **Install tools**:
- **Others**:

**What happened**:
On my pod I set a resource limit of 2 gpus (new 1.6 feature). When I ssh into the node (which has 8 gpus total) and inspect the docker container, I see that only two devices were chosen and attached (correct behavior), but I don't see how to determine which devices these were. From inside the pod, all 8 devices appear in /dev/nvidia{0..8}. Below I included my pod yml and node yml.

I also tried dumping the environment and don't see anything 
```
kubectl exec busybox2 -- bash -c "xargs --null --max-args=1 < /proc/1/environ"
```

Tried to schedule the following pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox2
spec:
  containers:
  - image: [ubuntu 14.04]
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /usr/local/nvidia
      name: nvidia
    - mountPath: /usr/local/cuda
      name: cuda
    - mountPath: /usr/lib/x86_64-linux-gnu/mesa
      name: lib
    command:
      - sleep
      - "3600"
    name: busybox
    resources:
      limits:
        alpha.kubernetes.io/nvidia-gpu: 2
  volumes:
  - hostPath:
      path: /usr/local/nvidia
    name: nvidia
  - hostPath:
      path: /usr/local/cuda
    name: cuda
  - hostPath:
      path: /usr/lib/x86_64-linux-gnu
    name: lib
  restartPolicy: Never

```
on this node:
```
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: 2017-05-16T18:58:04Z
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/hostname: [host]
    openai.org/gpu-count: "8"
    openai.org/gpu-type: 1080ti
  name: [host]
  resourceVersion: "162166"
  selfLink: /api/v1/nodes[host]
  uid: 975a9d20-3a69-11e7-a320-fcaa14ea6d82
status:
 ...
  allocatable:
    alpha.kubernetes.io/nvidia-gpu: "8"
    cpu: "40"
    memory: 263939800Ki
    pods: "28"
  capacity:
    alpha.kubernetes.io/nvidia-gpu: "8"
    cpu: "40"
    memory: 264042200Ki
    pods: "28"
  conditions:
  - lastHeartbeatTime: 2017-05-17T20:41:16Z
    lastTransitionTime: 2017-05-16T18:58:04Z
    message: kubelet has sufficient disk space available
    reason: KubeletHasSufficientDisk
    status: "False"
    type: OutOfDisk
  - lastHeartbeatTime: 2017-05-17T20:41:16Z
    lastTransitionTime: 2017-05-16T18:58:04Z
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: 2017-05-17T20:41:16Z
    lastTransitionTime: 2017-05-16T18:58:04Z
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: 2017-05-17T20:41:16Z
    lastTransitionTime: 2017-05-16T18:58:04Z
    message: kubelet is posting ready status. AppArmor enabled
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
  ....
    -   nodeInfo:
    architecture: amd64
    bootID: fe667c90-b764-4a56-a817-518555e893bf
    containerRuntimeVersion: docker://1.12.6
    kernelVersion: 4.4.0-75-generic
    kubeProxyVersion: v1.6.2
    kubeletVersion: v1.6.2
    machineID: 9cae6c159be1b1271f87c4075910b9a5
    operatingSystem: linux
    osImage: Ubuntu 14.04.5 LTS
    systemUUID: 00000000-0000-0000-0000-AC1F6B206ED8
```

**What you expected to happen**:
I expected either CUDA_VISIBLE_DEVICES to be set or only a subset of devices to appear in /dev/nvidia*

**How to reproduce it** (as minimally and precisely as possible):
See above.

**Anything else we need to know**:

**Comment by cmluciano** [comment]
This is related to https://github.com/kubernetes/kubernetes/issues/43240. We currently check devices in use on the node via a docker inspect on all of the running containers. 

We are considering a checkpoint mechanism for better bookkeeping. We also will whitelist only select devices that the pod need so that you do not see all devices w/i your container.

cc @vishh

**Comment by vishh** [comment]
Setting a pod to be `privileged` will result in all devices on the node from being exposed to pods. This is a docker thing. I wonder what it takes to run CUDA pods in non privileged mode.
@cmluciano will you be able to triage and fix this issue in v1.7?

**Comment by cmluciano** [comment]
Yep, I'll take it

**Comment by 8enmann** [comment]
@vishh is the workaround not to use privileged containers? But I thought we need that to access the CUDA libraries on the host. Or is there no workaround and must wait for 1.7?

**Comment by cmluciano** [comment]
Summary from SIG Node chat:

- Privileged containers are needed for those libraries as you mentioned
- Workarounds include creating a PV with libraries and then mounting these into the host
- Advanced solution is a sort of volume injection system (similar to the PV solution) and mounting it automatically to pods requesting GPUs

**Comment by 8enmann** [comment]
I tried the workaround of removing the `securityContext` and that worked (only the requested number of devices were visible to the pod). However I realized that we also need security context to mount `/dev/shm` for MPI to work properly. Or is there a more granular way to mount that?

**Comment by seelam** [comment]
you should be able to mount `/dev/shm`, are you not able to do it?

**Comment by 8enmann** [comment]
Oh, I guess the comment in the code was wrong. I just tried it and it worked!

**Comment by cmluciano** [comment]
@8enmann sweet. Does this mean that we just need to update our docs to remove that context? Are you able to run CUDA jobs properly under a non-privileged pod?

**Comment by 8enmann** [comment]
Yes, using the library PV mounted into the host 🎉

**Comment by cmluciano** [comment]
How are you leveraging cuda if you still cannot mount ```/usr/lib/nvidia-367``` ?

**Comment by 8enmann** [comment]
The contents of `/usr/lib/nvidia...` are in in my special directory, with cuda drivers owned by `nvidia-docker`

**Comment by cmluciano** [comment]
Ok. So this confirms that a permissions flip will work @vishh . I'm not sure if we want to just document this for now, or make a code change.

**Comment by vishh** [comment]
Sounds like an installation issue to me. Better to document it. WDYT?

**Comment by cmluciano** [comment]
Yes I will mention this case. I do wonder if even though all are seen, will the application still only use the device specifically mounted into it. 

I do see that it seems the mount is owned by root on my laptop

```
ls -la /usr/lib/nvidia-375
total 120536
drwxr-xr-x   6 root root     4096 May 17 11:14 .
drwxr-xr-x 168 root root    12288 May 19 16:19 ..
-rw-r--r--   1 root root      356 Mar 22 12:53 alternate-install-present
-rw-r--r--   1 root root        0 Mar 22 12:54 alt_ld.so.conf
drwxr-xr-x   2 root root     4096 May 17 11:14 bin
-rw-r--r--   1 root root       42 Mar 22 12:54 ld.so.conf
lrwxrwxrwx   1 root root       23 Mar 22 12:54 libEGL_nvidia.so.0 -> libEGL_nvidia.so.375.51
-rw-r--r--   1 root root  1079344 Mar 22 13:25 libEGL_nvidia.so.375.51
lrwxrwxrwx   1 root root       11 Mar 22 12:54 libEGL.so -> libEGL.so.1
-rw-r--r--   1 root root    77264 Mar 22 11:54 libEGL.so.1
```

It makes sense that you may need to copy them. 

I think a note about this in the docs is useful, and then we should strongly consider some sort of auto-mounting mechanism for 1.8.

**Comment by cmluciano** [comment]
related https://github.com/kubernetes/kubernetes/issues/30378

**Comment by cmluciano** [comment]
I documented this in https://github.com/kubernetes/kubernetes.github.io/pull/3870. I think this can be closed since I placed a note in the GPU epic about a volume concept. WDYT @vishh ?

**Comment by vishh** [comment]
SGTM
