### ISSUE TITLE
No scale subresource for StatefulSets

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/kubernetes#46005]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
update using patch
scaleSimple

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Kubernetes version** (use `kubectl version`): v1.6.3 for both client and server

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): 
```
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
VERSION_ID="14.04"
```
- **Kernel** (e.g. `uname -a`): ```Linux 4.4.0-75-generic #96~14.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux```
- **Install tools**: N/A
- **Others**: N/A

**What happened**:
Current implementation uses Put instead of Patch when running `kubectl scale`, which may result in validation errors when running client and server of **different** versions. We currently round-trip the entire spec from the YAML file to change number of replicas. Instead, we can use Patch and change only the `replicas` field.

**What you expected to happen**:
Use Patch when scaling replicas.

**How to reproduce it** (as minimally and precisely as possible):
N/A

**Anything else we need to know**:
I will work on this. :)

**Comment by crimsonfaith91** [comment]
@foxish PTAL - I am not sure whether I describe the issue correctly. Thanks!

**Comment by foxish** [comment]
I think the issue here is not that Update() should change, because it serves other purposes also. I'd expect the scaler to use patch instead of update.

**Comment by smarterclayton** [comment]
PATCH is more expensive on the server side than PUT if the conflict rate is low.  On the server, we should already be doing the optimal behavior.

**Comment by foxish** [comment]
@smarterclayton The fact that we use PUT and round-trip the entire spec seems to cause issues like https://github.com/kubernetes/kubernetes/issues/45287. We narrowed down the issue in #45287 to the `initContainers` field which should ideally also be mutable in addition to `spec.containers` and `spec.replicas`.

**Comment by crimsonfaith91** [comment]
@janetkuo there is a discussion about changing kubectl scale to patch replicas instead of using PUT. what's your thought about this issue?

**Comment by janetkuo** [comment]
We should use `/scale` endpoint. Looks like statefulset doesn't have /scale yet, but rs, rc, and deployments all have /scale endpoints. 
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/apps/rest/storage_apps.go
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/extensions/rest/storage_extensions.go
