### ISSUE TITLE
kubefed init with nodeport should allow setting the port 

### ISSUE THREAD

**Issue by ktsakalozos** [kubernetes/kubernetes#46021]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Kubernetes version** (use `kubectl version`): 1.6.2

**Environment**:
- **Cloud provider or hardware configuration**: AWS using Juju
- **OS** (e.g. from /etc/os-release): Ubuntu Xenial
- **Kernel** (e.g. `uname -a`): 4.4.0-59-generic
- **Install tools**: Juju
- **Others**:

**What happened**: kubefed init entered a infinite loop health checking the federation api service  

**What you expected to happen**: kubefed to exit with a success code

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

When doing a kubefed init on a cluster setup using VMs on aws (using Juju in my case) the worker nodes have two IPs: one that is visible to the internet and one internal visible only to VMs within aws. In my case for example the VM on aws hosting the kubernetes-worker node had external IP in the 54.174.73.1/24 subnet and it also had an internal IP in the 172.31.60.1/24 subnet. 

Using a client machine outside aws to bootstrap federation:
```
kubefed init federation --host-cluster-context=juju-context --dns-provider="coredns" --dns-zone-name="juju-fed.com." --etcd-persistent-storage=false --api-server-service-type="NodePort" -v 9 --dns-provider-config=coredns-provider.conf
```
I got the kubefed client stuck on doing a health check against the clouds internal subnet  https://172.31.60.XXX:31860/healthz . To address this I can use the `--api-server-advertise-address` flag and pass the external IP of any kubernetes-worker node. With this flag kubeconfig file gets updated with the right endpoint for the federation-apiserver. However, apart from the `--api-server-advert` I should also be able to specify the desired port the service will be listening on. I have to make sure that port is opened on the aws routing/firewall prior to issuing `kubefed init`. In the example above, kubefed init will try to reach https://54.174.73.XXX:31860/healthz, port 31860 is randomly assigned and is not reachable. I should be able to first open the port 31860 on aws and then do a `kubefed init` with `--api-server-service-type="NodePort"` and port pinned to 31860.

**Comment by madhusudancs** [comment]
@ktsakalozos is there a reason why you are not using the default load balanced service on AWS?

**Comment by ktsakalozos** [comment]
@madhusudancs I am using Juju to stay cloud agnostic. AWS just happened to be where I deployed this time. Juju just grabs machines (virtual or physical) from wherever you have resources from. In effect this your cluster is more like an on-prem than anything else. How would the default load balanced service work?

**Comment by madhusudancs** [comment]
@ktsakalozos got it.
