### ISSUE TITLE
Summarizing scores in generic_scheduler done sequentially

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#46027]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): 

generic_scheduling
scheduler
scoring

---

**Is this a BUG REPORT or FEATURE REQUEST?** : FEATURE REQUEST

in `/kubernetes/plugin/pkg/scheduler/core/generic_scheduler.go`  the function `PrioritizeNodes` Prioritizes the nodes, but at some point (line 374) : 

```go
for i := range nodes {
		result = append(result, schedulerapi.HostPriority{Host: nodes[i].Name, Score: 0})
		for j := range priorityConfigs {
			result[i].Score += results[j][i].Score * priorityConfigs[j].Weight
		}
	}

```
Summarizing all scores is done sequentially, maybe we should consider parallelizing it using wq ?

**Comment by resouer** [comment]
Does this improve performance? Seems not too much help?

**Comment by yastij** [comment]
if you want i can submit a fix + benchmark on a high number of nodes by sunday

**Comment by resouer** [comment]
Yes, please send a benchmark.

**Comment by wojtek-t** [comment]
I think this won't improve much. There are a bunch of places that would benefit more from.

**Comment by yastij** [comment]
indeed, maybe we should remove the TODO then.

**Comment by wojtek-t** [comment]
I'm fine with removing TODO.

**Comment by yastij** [comment]
submitting PR after WR then.
