### ISSUE TITLE
Service Accounts are not shipping with the cluster addons for Heapster, FluentD, or the Kubernetes Dashboard when using RBAC

### ISSUE THREAD

**Issue by chuckbutler** [kubernetes/kubernetes#46054]
**Kubernetes version** (use `kubectl version`):
Anything > 1.6.1 with RBAC enabled

**Environment**: 
- **Cloud provider or hardware configuration**: ALL
- **OS** (e.g. from /etc/os-release): N/A
- **Kernel** (e.g. `uname -a`): N/A
- **Install tools**: N/A

**What happened**:

When deploying system components, in this particular instance I'm looking into the defaults for Canonical Kubernetes

- Heapster
- FluentD
- Kubernetes Dashboard

They all default to the default service account in the `kube-system` namespace. The default kube-system service account does not have very permissive capabilities, thus causing the system components to fail when querying for the resources required to make them function.

 The way I see it is there are vectors to solve this, ranging from pragmatic but less secure; to secure but non-obvious.

- Give a `system:masters` role to a service account

This has the obvious drawback of being a glaring hole in the security model and does not follow least privilege access. It's a super-user for the cluster running in kube-system for any workload that doesn't declare a service account.

- Create default role bindings for service accounts scoped to the permissions declared by ClusterRoles for the components documented in the [RBAC system table](https://kubernetes.io/docs/admin/authorization/rbac/#other-component-roles) and attach those to service accounts that should be declared in the addon's manifest.

This seems like the better path forward as its using ClusterRoles that K8's itself will keep in alignment with the required privs during upgrades. This also means cluster operators will need to ensure their addon manifests/versions match the respective version of kubernetes in which it was released against (or a close version respectively)

**How to reproduce it** (as minimally and precisely as possible):
Deploy Kubernetes >= 1.6.1
Enable the rbac feature flag on kube-apiserver
Deploy the addons: heapster, kube-dashboard, fluentd

**Anything else we need to know**:

I'm opening this ticket to start the conversation around this effort and discover if anyone is or has worked on this before I submit a PR. Additionally, I don't imagine that I'm first in this domain to have found this issue, after speaking to @liggitt about this we loosely agreed that this should be a straightforward fix and should ship with the manifests. I'm open to discussion around why this might be a bad idea (perhaps for clusters not using RBAC?)

**Comment by c-knowles** [comment]
I was looking at a bit of this during some work on [kube-aws](https://github.com/kubernetes-incubator/kube-aws). The dashboard works out of the box using the default kube-aws RBAC but it is quite permissive. I couldn't find much information on the expected setup for RBAC + dashboard + OIDC. I have `kubectl` CLI access using the OIDC all working fine and now attempting to allow users access to the dashboard and have their access permissions mirror those bound to against their user in RBAC.

I saw from a few comments like https://github.com/kubernetes/kubernetes/issues/39722#issuecomment-299653458 that indicate using `kubectl proxy` is the expected access method. That's fine for us but to allow a user dashboard access using this method I had to add read access for the resource `services/proxy` which in turn allows them access to a lot more than their original permissions. I've been trying to figure out a more restrictive set of permissions but not much luck so far.

**Comment by liggitt** [comment]
`kubectl proxy` is only the expected access method until the dashboard supports per-user authentication (uses user credentials to access the API, so the dashboard is only as powerful as the user accessing it), at which point it could be exposed via ingress and accessed directly.

**Comment by liggitt** [comment]
> That's fine for us but to allow a user dashboard access using this method I had to add read access for the resource services/proxy which in turn allows them access to a lot more than their original permissions.

Any way you access the dashboard today allows a user to access a lot more than their original permissions.

**Comment by chuckbutler** [comment]
Yeah this is consistent with my findings as well, you pretty much have to be scoped with a very permissive set of roles in order to interface with the dashboard. Seems like an earmark issue for the kube-dashboard project.

**Comment by chuckbutler** [comment]
Linking this with an issue that was surfaced during digging around about dashboard permissions. This is loosely related. https://github.com/kubernetes/dashboard/issues/574#issuecomment-282360783

**Comment by liggitt** [comment]
the add-on manifests for these now define service accounts
