### ISSUE TITLE
HA-Kubernetes mangles data when running mixed apiserver versions (upgrades)

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#46073]
We saw an interesting edge case during a user's 1.5 -> 1.6 upgrade.  The installation tool (kops) did `kubectl apply` with a 1.6 manifest, but the 1.6 specific fields were removed from the deployment at some stage - in particular the tolerations.

The `kubectl.kubernetes.io/last-applied-configuration` reflected the 1.6 fields, but the toleration fields were missing from the spec itself.

I hypothesize that a 1.5 kube-controller-manager was the leader, and it did e.g. an UpdateStatus at some stage during the update.

How can we prevent this happening?  The ideas I've had are that we could either report the lowest API version across the cluster, or we could use a protobuf unknown-fields approach so that we don't mangle extra fields.  Neither of those are great options.

**Comment by justinsb** [comment]
cc @k8s-mirror-api-machinery-bugs

**Comment by erictune** [comment]
Justin, can you please add a sig label.  We are trying to standarize on sig rather than area labels.  Or if there no identifiable SIG for it, say so.

**Comment by justinsb** [comment]
Sorry @erictune  - fixed!

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by bgrant0607** [comment]
Apply is kubectl.

**Comment by bgrant0607** [comment]
And I consider this a feature request rather than a bug. 

cc @kubernetes/sig-api-machinery-feature-requests @kubernetes/sig-cli-feature-requests

**Comment by bgrant0607** [comment]
This is basically a manifestation of the problem discussed in #4855. 

New fields shouldn't be exposed until all components are upgraded and there is no risk of rollback. 

We can't store unknown fields for reasons discussed in #30819.

However, all components, but especially kubelet, really should be using patch to write status.

**Comment by mml** [comment]
@justinsb Looking forward to seeing a design doc for this when it's ready.
/sig archictecture

**Comment by justinsb** [comment]
@mml I think sig-apimachinery should own this; it's too fundamental an issue I believe.

**Comment by liggitt** [comment]
fyi, with the guidance in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md#alpha-field-in-existing-api-version (and the sweeps done in https://github.com/kubernetes/kubernetes/issues/72169 and https://github.com/kubernetes/kubernetes/issues/72651), n-1 skew among API servers will no longer drop data from fields supported in version `n`
