### ISSUE TITLE
netwowork problem  when install an kubelet in the master node with flannel

### ISSUE THREAD

**Issue by berlinsaint** [kubernetes/kubernetes#46077]
master env:
in the master i install an kubelet so the master can become  also  a slavor node. 
flannel kube-proxy etcd are all installed in the master ip 172.31.10.44.
docker version: 17.03
k8s version 1.6.3
flannel version 7.1
etcd version 3.+
master get flannel ip subnet is : 172.30.88.1/24 
![image](https://cloud.githubusercontent.com/assets/10629930/26232165/cf4eef6e-3c86-11e7-96ec-e4083f9d4580.png)

the ohter node ip 172.31.10.45 have the save verison  docker ， flannel ，K8S
and get flannel ip subnet is : 172.30.68.1/24
![image](https://cloud.githubusercontent.com/assets/10629930/26232400/8bae912c-3c88-11e7-9a67-9ea641c8f563.png)

now  i have a my-nginx ,and has 2 rcs;
![image](https://cloud.githubusercontent.com/assets/10629930/26232419/b10490de-3c88-11e7-8a15-34ad7c2a0817.png)
in the slaver:
   i did ping 172.30.88.1 , it's ok 88.1 is master flannel gateway;
   i did ping 172.30.88.4 that the my-nginx it it‘s ok

![image](https://cloud.githubusercontent.com/assets/10629930/26234163/3624cdf4-3c95-11e7-9638-fb2fdac887fc.png)
however in the master:
 i did ping 172.30.68.1 it’s ok and  68.1 is node flannel gateway
 then i did ping 172.30.68.2 ,not ok , very strange
![image](https://cloud.githubusercontent.com/assets/10629930/26234241/c3979392-3c95-11e7-81ee-58e821f056c1.png)

i have doubt that if it's the problem with iptables. i did itables -F , -X , Z ,not use.

please help me  and tell me that if this methd(install kubelet within master) leads to the problem.
or if it is a bug?

**Comment by dixudx** [comment]
@berlinsaint I reproduced on my environment. It works well. Please check the statup arguments and make sure that all are well configured.

**Comment by berlinsaint** [comment]
nop  i thinks it was the problem of  3.13. ubuntu 14.04 kernel. i sovle it by upgrade kernel

**Comment by cmluciano** [comment]
@berlinsaint Can we close this issue?

**Comment by berlinsaint** [comment]
@cmluciano  yes i can close it ,but i want to know if there did exists the problem with ubuntu 14.04 ,and kerner version :`Linux i-40C8C8F5 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`
i don't find the any more  explanations abuut it and some other people encountered this problem too.

**Comment by 573009114** [comment]
I also have this problem
