### ISSUE TITLE
Hpa for custom metrics

### ISSUE THREAD

**Issue by bonowang** [kubernetes/kubernetes#46072]
When the HPA support for custom metrics will be the stable version? i check the 1.7,it is still in alpha. any roadmap for it?

**Comment by xiangpengzhao** [comment]
The tracking issue is https://github.com/kubernetes/features/issues/117

/cc @DirectXMan12

**Comment by bonowang** [comment]
> The tracking issue is kubernetes/features#117
Thanks

**Comment by DirectXMan12** [comment]
The plan is to try for beta in 1.8, once we get some custom metrics adapters out and in the wild (like https://github.com/directxman12/k8s-prometheus-adapter).
