### ISSUE TITLE
[e2e test] Why `should check kube-proxy urls` case always assume proxy mode is iptables?

### ISSUE THREAD

**Issue by dujun1990** [kubernetes/kubernetes#46078]
**What?**

When I run e2e test in my local machine with kube-proxy running in **userspace** mode. I find test case:

"should check kube-proxy urls" in `test/e2e/networking.go` will try to hit `/proxyMode` and assume it is **iptables** mode by default. see https://github.com/kubernetes/kubernetes/blob/master/test/e2e/networking.go#L86

If it's not easy to pass in kube-proxy mode in e2e test framework, I wonder why check proxy mode and hard code it to be **iptables**?

**Comment by cmluciano** [comment]
@dujun1990 Are you looking for the equivalent test in the userspace proxy?

**Comment by dujun1990** [comment]
@cmluciano In fact, I am working on implementing ipvs kube-proxy and running e2e test for my implementation, see #44063 

I think it's ok that e2e test iptables kube-proxy by default. However, hard code iptables in e2e test case will fail any other implementations?

**Comment by m1093782566** [comment]
It's fixed now. Thanks all!
