### ISSUE TITLE
[e2e test] Networking IPerf failed due to invalid `bandwidth` string with newline

### ISSUE THREAD

**Issue by dujun1990** [kubernetes/kubernetes#46083]
**WHAT**: **Bug report**. 

See the error log below,

```
• Failure [100.294 seconds]
[k8s.io] Networking IPerf [Experimental] [Slow] [Feature:Networking-Performance]
/home/dujun/goproject/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:695
  should transfer ~ 1GB onto the service endpoint 1 servers (maximum of 1 clients) [It]
  /home/dujun/goproject/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/networking_perf.go:154

  May 19 15:48:52.070: Failed parsing value bandwidth port from the string '1176527324
  ' as an integer
```

I assume the output of iperf in my test environment has an extra newline in the value of `bandwidth`, that is 
```
'1176527324
' 
```

What about trim the newline in the returned value before parsing it as an integer? Especially change this line https://github.com/kubernetes/kubernetes/blob/master/test/e2e/util_iperf.go#L100

Like,

```
rawValue = strings.Replace(rawValue, "\n", "", -1)
value, err := strconv.ParseInt(rawValue, 10, 64)
```

**Comment by dujun1990** [comment]
If it's a bug, may I send a PR to fix this?

**Comment by cmluciano** [comment]
@dujun1990 Of course. It would be best to also have a commit that adds an e2e test to replicate this issue. It is hard to tell if this is environment specific and it's odd that this has not popped up before.

**Comment by sstarcher** [comment]
I see this on an aws/coreos setup

**Comment by cmluciano** [comment]
@dujun1990 @m1093782566 Are you still working on this? Looks like the PR was closed.

**Comment by m1093782566** [comment]
@cmluciano 

Yes, I am still working on it.

**Comment by dujun1990** [comment]
@sstarcher Please refer #46581

Do think this PR can fix this issue?

**Comment by bzub** [comment]
I'm seeing this also, running a [kubeadm-dind-cluster](https://github.com/Mirantis/kubeadm-dind-cluster) in a Travis CI Ubuntu Trusty VM.

**Comment by sstarcher** [comment]
@dujun1990 I never dug into the issue so I don't know.
