### ISSUE TITLE
kubelet gets in an endless loop when initializeModules failed

### ISSUE THREAD

**Issue by looloochen** [kubernetes/kubernetes#46086]
In our k8s cluster, a node's status is NotReady, and we checked the kubelet's log, that repeated "skipping pod synchronization" every 5 minutes:

```
May 10 16:20:07 localhost kubelet: I0510 16:20:07.315290   20965 kubelet.go:2237] skipping pod synchronization - [Kubelet failed to get node info.] 
May 10 16:20:12 localhost kubelet: I0510 16:20:12.317233   20965 kubelet.go:2237] skipping pod synchronization - [Kubelet failed to get node info.] 
May 10 16:20:17 localhost kubelet: I0510 16:20:17.317374   20965 kubelet.go:2237] skipping pod synchronization - [Kubelet failed to get node info.] 
```
```
func (kl *Kubelet) syncLoop(updates <-chan kubetypes.PodUpdate, handler SyncHandler) {
	glog.Info("Starting kubelet main sync loop.")
	// The resyncTicker wakes up kubelet to checks if there are any pod workers
	// that need to be sync'd. A one-second period is sufficient because the
	// sync interval is defaulted to 10s.
	syncTicker := time.NewTicker(time.Second)
	defer syncTicker.Stop()
	housekeepingTicker := time.NewTicker(housekeepingPeriod)
	defer housekeepingTicker.Stop()
	plegCh := kl.pleg.Watch()
	for {
		if rs := kl.runtimeState.errors(); len(rs) != 0 {
			glog.Infof("skipping pod synchronization - %v", rs)
			time.Sleep(5 * time.Second)
			continue
		}
		if !kl.syncLoopIteration(updates, handler, syncTicker.C, housekeepingTicker.C, plegCh) {
			break
		}
	}
}
```
I found the code where printing those logs, in the syscLoop function. if runtimeState has error, kubelet will get into endless loop, and will print "skipping pod synchronization" every five minutes.

In our case, the node got an error when startup, in the function initializeModules, which called our cloud provider to get node info, because the call returned an error, kubelet set the error to runtimeState, and ran syscLoop next, going to endless loop.
```
if err := kl.initializeModules(); err != nil {
		kl.recorder.Eventf(kl.nodeRef, api.EventTypeWarning, events.KubeletSetupFailed, err.Error())
		glog.Error(err)
		kl.runtimeState.setInitError(err)
	}
```

I think there is a problem here:
Startup function "initializeModules" encountered an error like "failed get node info", which is rarely, kubelet should exit its process and it will be restarted by systemd successfully.
Restarting kubelet is more reaonable than printing error log in the endless loop, Restarting event can be mornitored easily, but the admin can hardly detect the endless loop.

**Comment by cmluciano** [comment]
@kubernetes/sig-node-bugs
