### ISSUE TITLE
Azure file doesn't work in Azure China

### ISSUE THREAD

**Issue by comzyh** [kubernetes/kubernetes#46081]
**Is this a request for help?** 
NO

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

kubernetes, azure file, chinacloudapi

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

 BUG REPORT

**Kubernetes version** (use `kubectl version`):
master

**Environment**:
- **Cloud provider or hardware configuration**: azure.cn
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Kernel** (e.g. `uname -a`): 
- **Install tools**:
- **Others**:

**What happened**:
We try to mount azure file to pod, and get the following error
> Output: mount error: could not resolve address for foo .file.core.windows.net: Unknown error

That is because azure china's storage DNS suffix is `core.chinacloudapi.cn` rather than `core.windows.net`

**What you expected to happen**:
Kubernetes should provide some method to let user specify storage dns suffix, so we can use Azure file volume 

**How to reproduce it** (as minimally and precisely as possible):

Any Azure cluster in china can reproduce it.

**Anything else we need to know**:
kubernetes has hard coded `core.windows.net` in https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/azure_file/azure_file.go#L210

#12904  shows a relative issue

**Comment by comzyh** [comment]
@rootfs  could you help confirm this?

**Comment by xiangpengzhao** [comment]
One possible way is configuring DNS suffix via annotations of PV. If @rootfs thinks this way okay, I'd like to create a PR to fix it.

**Comment by rootfs** [comment]
@xialonglee @comzyh azure file was implemented without using resource group or azure cloud provider. The endpoint can be found at https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/Azure/go-autorest/autorest/azure/environments.go#L82

One fix is to use azure cloud provider and choose the file service endpoint from azure environment as I did in blob service [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_blob.go#L73). Let me know if you can help.

**Comment by xiangpengzhao** [comment]
@rootfs I'm not familiar with azure cloud provider and volume codes. I'd like to try to dig into it to see if I can fix as the way you suggested.
