### ISSUE TITLE
fieldSizeTooLarge 'resource.hostRules' / 'resource.pathMatchers' on ingress

### ISSUE THREAD

**Issue by hach-que** [kubernetes/kubernetes#46098]
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T09:42:05Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): n/a
- **Kernel** (e.g. `uname -a`): n/a
- **Install tools**: n/a
- **Others**: n/a

**What happened**:
Applied ingress and saw in the logs:

```
  22m   2m      9       loadbalancer-controller         Warning UrlMap  googleapi: Error 413: Value for field 'resource.hostRules' is too large: maximum size 50 element(s); actual size 53.
More details:
Reason: fieldSizeTooLarge, Message: Value for field 'resource.hostRules' is too large: maximum size 50 element(s); actual size 53.
Reason: fieldSizeTooLarge, Message: Value for field 'resource.pathMatchers' is too large: maximum size 50 element(s); actual size 53.
```

**What you expected to happen**:
The ingress should support >50 path matching rules.

**How to reproduce it** (as minimally and precisely as possible):
Have an ingress with >50 host matching rules.

**Anything else we need to know**:
This limit doesn't appear to be documented anywhere.

**Comment by hach-que** [comment]
This is actively preventing us from deploying out new services, and I can't see any viable workaround (since this is hosted on Google Container Engine, there's no way for us to use the Nginx ingress controller instead).

**Comment by cmluciano** [comment]
@kubernetes/goog-gke

**Comment by roberthbailey** [comment]
@bowei @MrHohn

**Comment by MrHohn** [comment]
@nicksardo should have more insight.

**Comment by nicksardo** [comment]
This is an existing limitation with the URLMap resource. 50 is indeed the max. I recommend filing a feature request at https://cloud.google.com/support/docs/issue-trackers.

/close

**Comment by hach-que** [comment]
Reported on the Cloud Load Balancer bug tracker: https://issuetracker.google.com/issues/38465625
