### ISSUE TITLE
Admission does not populate object name on create

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#46107]
The admission attributes given to admission plugins do not populate object name on create.

This means that admission plugins must do `attr.GetObject().(*api.MyType).Name` themselves.

Since the object is available, the name in the admission attributes should be populated if available.

**Comment by liggitt** [comment]
The default namer used by admission just reuses the request info parsed from the URL, which would not contain the name in create API calls. Would need to implement a different namer that looked at the passed object.

**Comment by timstclair** [comment]
Do `authorizer.Attributes` have the same issue?

**Comment by liggitt** [comment]
Yes, that's what this is referring to.

**Comment by liggitt** [comment]
You have access to the incoming object in attributes.GetObject(), which a plugin can cast (or use meta.accessor) to extract the name, but that's not happening when building the attributes.

**Comment by nikhita** [comment]
There is a PR open: https://github.com/kubernetes/kubernetes/pull/53185.

/remove-lifecycle stale

**Comment by nikhita** [comment]
/reopen
/remove-lifecycle rotten

There is a PR open: https://github.com/kubernetes/kubernetes/pull/53185

**Comment by seh** [comment]
Testing this in Kubernetes version 1.16.0, I find that this problem persists: For pods created by the _Job_ controller, the `admission/v1beta1.AdmissionRequest` field "Name" is empty. Given that #53185 contributed a release note to this effect for version 1.16.0, it sounds like we _thought_ this was fixed in that release.

@liggit, can we reopen this issue?

**Comment by liggitt** [comment]
does the job controller set the name field, or use generateName?

**Comment by seh** [comment]
It uses the latter, per [`controller.GetPodFromTemplate`](https://sourcegraph.com/github.com/kubernetes/kubernetes@master/-/blob/pkg/controller/controller_utils.go#L542:6).

**Comment by liggitt** [comment]
the name is only passed to admission when it is actually set in the object. generateName is used to populate name *after* the mutation phase, before the validation phase

**Comment by seh** [comment]
I had a workaround in my mutating Webhook for a while that digs down into the object's "metadata.name" field when the admission request's "Name" field is empty, and I thought that it found that field populated. Let me run a few tests to see if I had that wrong.

**Comment by seh** [comment]
Further testing confirms that the "metadata.name" field isn't populated yet for pods when presented to the mutating Webhook. I noticed that other objects with _Jobs_ (made by a _CronJob_) and _ReplicaSets_ (made by a _Deployment_) *do* have their names populated at this point, even though those names _appear_ to be generated similarly. Why is that?

**Comment by seh** [comment]
Ah, I see that the _Deployment_ controller is not using `ObjectMeta.GenerateName` when creating _ReplicaSets_. It [constructs the name from the pod template hash](https://sourcegraph.com/github.com/kubernetes/kubernetes@bd89dc462c4fced99eac966d244c9b031aa56df4/-/blob/pkg/controller/deployment/sync.go#L197).

**Comment by liggitt** [comment]
the name is populated from generateName in BeforeCreate:

https://github.com/kubernetes/kubernetes/blob/d647ddbd755faf07169599a625faf302ffc34458/staging/src/k8s.io/apiserver/pkg/registry/rest/create.go#L74-L93

that is called after mutating admission, before validating admission

>  I see that the Deployment controller is not using ObjectMeta.GenerateName when creating ReplicaSets. It constructs the name from the pod template hash.

Correct, some controllers manage the names of their created objects themselves rather than delegating to the API server to generate the name

**Comment by seh** [comment]
Thanks for setting me straight on this. I'll adjust my code to publish the `ObjectMeta.GenerateName` value in cases where there's no name yet. This is for instrumentation coming from my Webhook; it doesn't change the correctness of its admission-focused behavior.
