### ISSUE TITLE
Re-created nodes are not provisioned

### ISSUE THREAD

**Issue by ddysher** [kubernetes/kubernetes#4610]
I have four nodes in my GCE cluster
```
NAME                                                 LABELS              STATUS
kubernetes-minion-3wsr.c.lucid-walker-725.internal   <none>              Ready
kubernetes-minion-7yx6.c.lucid-walker-725.internal   <none>              Ready
kubernetes-minion-eatx.c.lucid-walker-725.internal   <none>              Ready
kubernetes-minion-kvgz.c.lucid-walker-725.internal   <none>              Ready
```
Delete the first two from GCE console, after a while, they are re-created by MIG.  nodecontroller picks it up and re-created them in k8s, but they remain NotReady, which means kubelet is not responding.
```
NAME                                                 LABELS              STATUS
kubernetes-minion-3wsr.c.lucid-walker-725.internal   <none>              NotReady
kubernetes-minion-7yx6.c.lucid-walker-725.internal   <none>              NotReady
kubernetes-minion-eatx.c.lucid-walker-725.internal   <none>              Ready
kubernetes-minion-kvgz.c.lucid-walker-725.internal   <none>              Ready
```

NotReady node is not useful.  Reference PR #4164

@fbalejko @cjcullen

**Comment by tkulczynski** [comment]
Yes, I agree all the features of MIG are not yet usable for K8s clusters.
I'll work towards fully supporting resizes (and node recreations). For now note there are two things still done instance by instance in the kube-up command: setting ip-range metadata and creating routes (routes persist recreations, if the new node has the same name the previous one had, but metadata is always lost). I'm planning to move that part to nodecontroller.

**Comment by lavalamp** [comment]
Furthermore, once MIG recreates one of your nodes, kube-push.sh will never work on your cluster again: it always thinks your cluster is broken because of the one node having not been provisioned.

**Comment by wojtek-t** [comment]
cc @jszczepkowski @gmarek

**Comment by alex-mohr** [comment]
Might work now, need to test and verify?

**Comment by gmarek** [comment]
@alex-mohr @bgrant0607 @lavalamp - is this still a thing?

**Comment by roberthbailey** [comment]
My guess is no, but we need someone to run a quick test. Any volunteers?

**Comment by lavalamp** [comment]
I believe the resize e2e test should cover this case? If that's passing, we can probably close this.

**Comment by bgrant0607** [comment]
Supposedly clusters are scalable, so closing.
cc @jszczepkowski
