### ISSUE TITLE
Collect kubemark master logs even if start-kubemark script fails

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#46109]
We recently had 2 flaky runs (2825, 2826) in our kubemark-100 CI test and the problem was in kubemark apiserver failing to become healthy and the test timed out.
And since we don't currently collect kubemark master logs if the test fails during start-kubemark.sh step, we have no idea why it failed.

cc @wojtek-t @gmarek

**Comment by wojtek-t** [comment]
@kubernetes/test-infra-maintainers
