### ISSUE TITLE
Running kube-proxy in a container breaks iptables locking

### ISSUE THREAD

**Issue by bboreham** [kubernetes/kubernetes#46103]
**BUG REPORT**

**Kubernetes version**
1.6.2

**Environment**:
- **Install tools**: `kubeadm`

**What happened**:
The code in `k8s.io/kubernetes/pkg/util/iptables/iptables.go` takes care to supply the `-w` flag so it will wait on a lock to avoid interference between multiple processes modifying the table.
If you read the `iptables` source you discover it does this by creating a file `/run/xtables.lock`.
However, when `kube-proxy` is running in a container, `/run` is in a local filesystem, so it is not able to lock against processes running on the host or in other containers.

And before you decide that the answer is to mount `/run` from the host, look at all the issues around leaking netns, e.g. github.com/moby/moby/issues/32090

Credit @mikebryant for pointing this out to me.
Credit @squeed for pointing out locking functionality was added to `iptables-restore` a few months back https://git.netfilter.org/iptables/commit/?id=999eaa241212d3952ddff39a99d0d55a74e3639e

**Comment by squeed** [comment]
Ironically, this is caused by the move to file-based locking. Previously, iptables would lock by reserving an abstract unix socket, which is tied to the network namespace.

https://git.netfilter.org/iptables/commit/?id=aa562a660d1555b13cffbac1e744033e91f82707

**Comment by dcbw** [comment]
Some discussion also in https://github.com/kubernetes/kubernetes/pull/44895#issuecomment-297147179 and following comments.

**Comment by mikebryant** [comment]
I experimented with this: https://github.com/kubernetes/kubernetes/pull/44895#issuecomment-298810440
but it didn't work on CoreOS, as the host wasn't using a version of iptables that used the file lock yet.
Just ended up creating a directory call /run/xtables.lock

**Comment by bboreham** [comment]
I guess I should file this as an issue against kubeadm and any of the other sources of kube-proxy container config.

**Comment by cmluciano** [comment]
@kubernetes/sig-network-bugs

**Comment by thockin** [comment]
Should we leave this open (waiting for ... ?)

**Comment by luxas** [comment]
@thockin Waiting for https://github.com/kubernetes/kubernetes/issues/46372 I guess... (which I'm reviewing now)

**Comment by cmluciano** [comment]
i think this should not be marked as complete until the kubeadm fixes are in.

**Comment by cmluciano** [comment]
/close

fix in https://github.com/kubernetes/kubernetes/pull/46372
