### ISSUE TITLE
The verson of cAdvisor built-in to the kubelet does not support zfs.

### ISSUE THREAD

**Issue by carsonoid** [kubernetes/kubernetes#46115]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): zfs zfsStorageDriver

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.6.3

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu
- **Kernel** (e.g. `uname -a`): 4.4.0-53-generic
- **Install tools**: Custom
- **Others**:

**What happened**:

When using ZFS for docker storage, the kubelet will constantly spam messages like:

```
May 19 17:03:26 ip-172-30-6-75 kubelet[29891]: I0519 17:03:26.652968   29891 container.go:469] Failed to update stats for container "/kubepods/besteffort/pod98818b024fc9facec9f8ee660ec80c53/88a5e8a322a4f00b6413b7adb476a14076c9a52a6738656345d59cee8d664047": unable to determine device info for dir: : stat failed on  with error: no such file or directory, continuing to push stats
May 19 17:03:42 ip-172-30-6-75 kubelet[29891]: I0519 17:03:42.486967   29891 container.go:469] Failed to update stats for container "/kubepods/burstable/pod77c58f1d38172c1216ecb94e82bb5cb1/3b6f9961161ef22f9ceedffdedaf477d75096616797d37112709fc3b63bd2d64": unable to determine device info for dir: : stat failed on  with error: no such file or directory, continuing to push stats
May 19 17:03:50 ip-172-30-6-75 kubelet[29891]: I0519 17:03:50.109429   29891 container.go:469] Failed to update stats for container "/kubepods/burstable/podc67c05f87dcdb595ae78bd01328329e9/db30382a04cd1659fb65085059c93643813155069010cc38cfb795be5b9fb37c": unable to determine device info for dir: : stat failed on  with error: no such file or directory, continuing to push stats
May 19 17:03:50 ip-172-30-6-75 kubelet[29891]: I0519 17:03:50.679914   29891 container.go:469] Failed to update stats for container "/kubepods/burstable/poda4fa953b8274909d5852539c981e797a/a06bc99a9781b23bc9342d31717bd6301f484d45803d172ea872b7336903bd22": unable to determine device info for dir: : stat failed on  with error: no such file or directory, continuing to push stats
May 19 17:03:53 ip-172-30-6-75 kubelet[29891]: I0519 17:03:53.630803   29891 container.go:469] Failed to update stats for container "/kubepods/burstable/poda4fa953b8274909d5852539c981e797a/c611ee7832be42533872f9d0132a2126559385422cbfe14d92c10ffa47fbdc13": unable to determine device info for dir: : stat failed on  with error: no such file or directory, continuing to push stats
May 19 17:03:56 ip-172-30-6-75 kubelet[29891]: I0519 17:03:56.727740   29891 container.go:469] Failed to update stats for container "/kubepods/burstable/podc04f713c02419048c7d55fdbd4e19c39/5d07dd09cafead044a34164f3868f31c50524bc6afa6b56dd7042a8f0867b324": unable to determine device info for dir: : stat failed on  with error: no such file or directory, continuing to push stats
```

**What you expected to happen**:

Newer versions of cAdvisor support zfs: https://github.com/google/cadvisor/blob/e14ee9be3506d260847d263e26a3e9e27f83ad96/container/docker/handler.go#L417

The kubelet should either upgrade it's built-in cAdvisor or support running cadvisor out-of-band so a newer version can be used.

**How to reproduce it** (as minimally and precisely as possible):

Run kubelet on a host where docker is using zfs

**Anything else we need to know**:

**Comment by kargakis** [comment]
@kubernetes/sig-node-feature-requests

**Comment by dashpole** [comment]
kubernetes v1.6 is tied cAdvisor v0.25.  I plan to cut cAdvisor v0.26.0 in the next week, and will include that in kubernetes v1.7.  I do not plan to cherrypick zfs support into the 1.6 branch

**Comment by carsonoid** [comment]
@dashpole what about allowing cAdvisor to be run separately?

**Comment by dashpole** [comment]
We have considered that in the past, but found that there is not a large enough benefit to justify putting in the work to break the two up.  In order to manage validation of kubernetes with cAdvisor, we would likely have to tie each version of kubernetes to a version of cAdvisor anyways, so it wouldn't really help your situation here.

**Comment by carsonoid** [comment]
Ok thanks for your time. It looks like I'll just have to wait for 1.7 to get disk stats and stop the spam "error" messages from the kubelet. Not a problem.
