### ISSUE TITLE
[Federation] Replacing deployment definition does not evenly distribute replicas across clusters

### ISSUE THREAD

**Issue by ajwootto** [kubernetes/kubernetes#46119]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): federation, deployment, replace

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`): 1.6.2

**Environment**:
- **Cloud provider or hardware configuration**: GCP/GKE

**What happened**:
With a three cluster federation and a deployment with 16 replicas, replacing the deployment using
`kubectl replace -f deployment.yaml` 
results in all the updated pods going to one cluster rather than being evenly distributed.

**What you expected to happen**:
The pods should be evenly distributed (especially given the fact that they were correct before the replace operation)

**How to reproduce it** (as minimally and precisely as possible):
1) Create a deployment resource in the federation control plane (which is managing multiple underlying clusters)
2) Scale the deployment (mine is set to 16). Pods should then be evenly distributed, between 4-6 in each cluster
3) Replace the deployment with an updated version (new image, etc.) using 
`kubectl replace -f deployment.yaml`
4) Watching the list of pods in each cluster, I see the pods starting to be replaced correctly, but at some point the newly updated running pods will all get terminated in two of the clusters and everything will be moved to the third cluster.

**Anything else we need to know**:

Full deployment spec:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 16
  template: # create pods using pod definition in this template
    metadata:
      annotations:
        federation.kubernetes.io/deployment-preferences: |
          {
            "rebalance": true,
            "clusters": {
              "us-central": {
                  "minReplicas": 3
              },
              "eu-west": {
                  "minReplicas": 3
              },
              "asia-se": {
                  "minReplicas": 3
              }
            }
          }
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: gcr.io/myimage
          ports:
          - containerPort: 8000
          env:
            - name: GO_ENV
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: GO_ENV
            - name: REDIS_CLUSTER
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: user_redis 
            - name: DISABLE_REDIS
              value: "false"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
```

Despite the federation annotation that should require a minimum of 3 pods (and allow rebalancing) the state remains incorrect with no hosted pods in two of the clusters.

If I scale the replicas down to zero using 
`kubectl scale --replicas 0 deployment users`
and wait long enough for all the user pods to be killed, then scale back up to 16, they will be correctly distributed between the three clusters. Thusfar I've had to do this every time I update the image for the deployment.

**Comment by perotinus** [comment]
Does this happen consistently? Would you happen to have a log from the Federation controller manager? It may have more details about what's going on.

You can get this log by first finding the controller manager pod (`kubectl get pods --namespace=<your_federation_system_namespace> --context=<host_cluster_context>`) and running `kubectl logs <cm_pod_name> --namespace=<your_federation_system_namespace> --context=<host_cluster_context>`).

**Comment by ajwootto** [comment]
It happens consistently, every time I do a replacement, and it seems that all of the pods always get sent to the same cluster. There isn't much of interest in the controller log, it basically just says:
```
I0525 17:02:06.341069       1 deploymentcontroller.go:595] Updating users in us-central
I0525 17:02:06.341101       1 deploymentcontroller.go:595] Updating users in asia-se
I0525 17:06:12.730444       1 deploymentcontroller.go:595] Updating users in eu-west
```
I've managed to get the annotation for minimum replicas partially working (turns out I had it in the wrong part of the yaml), but this also seems to come with its own problem. When I have a configuration like:
```
annotations:
    federation.kubernetes.io/deployment-preferences: |
      {
        "rebalance": true,
        "clusters": {
          "us-central": {
              "minReplicas": 3
          },
          "eu-west": {
              "maxReplicas": 0
          },
          "asia-se": {
              "maxReplicas": 0
          }
        }
      }
```
And the # of replicas for the deployment set at 6, I only end up with three pods total, all in the us cluster. It seems like the system is treating the minReplicas directive as a max or something.

**Comment by bspradling8** [comment]
I'm noticing the same behavior that everything is dumped into the same cluster as a replacement. I did a quick test of the annotations to see if I could get a workaround by: ```annotations:
    federation.kubernetes.io/deployment-preferences: |
      {
        "rebalance": true,
        "clusters": {
          "us-central": {
              "minReplicas": 3
          },
          "eu-west": {
              "minReplicas": 3
          },``` and even then I noticed that the existing pods weren't getting rebalanced correctly.

**Comment by bspradling8** [comment]
@ajwootto have you found a workaround for this?

**Comment by ajwootto** [comment]
@bspradling8 Right now I've just been using the min annotations to force each cluster to have at least 3 pods. Problem at the moment is that it seems there can never be more than the min number in the annotation. I'm going to start playing with autoscaling soon as well, so we'll see if it remains a problem.

**Comment by bspradling8** [comment]
@ajwootto Gotcha, I'll be interested to see how autoscaling affects this. I just got the annotations working as you just described this morning. Turns out I had them in the wrong spot as well :)

**Comment by perotinus** [comment]
@ajwootto @bspradling8 I believe that I have a workaround for the second problem (the one that occurred when you had the annotation in the right place): add a `"weight": 1` entry under each of the `minReplicas` and `maxReplicas` entries, and you should get enough replicas in each cluster:

annotations:
    federation.kubernetes.io/deployment-preferences: |
      {
        "rebalance": true,
        "clusters": {
          "us-central": {
              "minReplicas": 3,
              "weight": 1
          },
          "eu-west": {
              "maxReplicas": 0,
              "weight": 1
          },
          "asia-se": {
              "maxReplicas": 0,
              "weight": 1
          }
        }
      }

**Comment by perotinus** [comment]
I believe I understand the reason for the first failure as well. The federated deployment controller watches pods in the underlying cluster to get information that it uses to determine capacity and schedule pods. When a deployment is being updated to a new image, it creates a new replica set for the new pods and scales down the old replica set. For some reason, it looks like the federated deployment controller is taking the pods that are being spun down into account in its calculations for scheduling, which causes it to think that the first cluster that it happens to process for scheduling has more replicas than it should. Depending on when exactly the scheduling occurs, the first cluster processed can steal some or all of the replicas from others. Since rebalance is false by default, when the first cluster is given the replicas, it keeps them until the deployment is scaled down and back up.

For now, the workaround is as you've described: scale down to 0 then scale back up. This is not a reasonable workaround for a production environment, though, so we need to determine the right way to fix this.

**Comment by kishorekumark** [comment]
Same issue observed with version, even with "weight:1 "
{code}
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:46:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
{code}

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#139.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
