### ISSUE TITLE
Increase the unit test coverage of pkg/kubelet/kuberuntime

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#46123]
We've already seen a couple of bugs (#45977, #46121) caused by kuberuntime not populating the fields correctly. This is the type of bug that could easily be caught by unit tests. 
We should improve the test coverage of this package.

/cc @feiskyer @Random-Liu

**Comment by Random-Liu** [comment]
Agree. And this is also why we need to add so many unit test in cri-containerd @xlgao-zju @mikebrow :)

**Comment by feiskyer** [comment]
+1.

**Comment by k82cn** [comment]
There's an issue for scheduling code coverage at #39559; I think we can open similar issue in kubelet, like this :).

**Comment by k82cn** [comment]
xref #40780

**Comment by enxebre** [comment]
I'm happy to work on this, I'll have a look if no one else is looking at it
