### ISSUE TITLE
federation: Updating service type is not propagated to clusters

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#46137]
Steps to repro:
* Create a federated service of type "ClusterIP".
* Verify that the service is created in all clusters
* Update the federated service to be of type "LoadBalancer"

Expected:
* Services in all underlying clusters is updated to be of type LoadBalancer.

Actual:
* No change to cluster services.

No new event was created as well.

cc @shashidharatd @kubernetes/sig-federation-bugs

**Comment by nikhiljindal** [comment]
I am running an older version of federation control plane. So dont have the latest service controller refactor changes.

@shashidharatd Is this something that might have been fixed by the latest changes?

**Comment by shashidharatd** [comment]
yes @nikhiljindal, These type of issues won't happen in latest code. Its taken care.

**Comment by nikhiljindal** [comment]
Great, @shashidharatd!
Were you able to verify by trying it out?

Feel free to close the issue once you have had a change to verify.

**Comment by shashidharatd** [comment]
Here is the e2e test case to verify if update is propagated to federated clusters.
https://github.com/kubernetes/kubernetes/commit/a152b9919a35e3078a4ad58f67b34e7a31557a4b

/close
