### ISSUE TITLE
[Federation] Document permissions that the Federation control plane requires in joined clusters

### ISSUE THREAD

**Issue by perotinus** [kubernetes/kubernetes#46131]
We need to document what permissions the Federation control plane needs in order to correctly function. After #42042 `kubefed` will create a service account that has very broad permissions, but we should document what are the tightest permissions necessary in order for the FCP to run.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#140.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
