### ISSUE TITLE
APIServer cannot run as a non-root pod

### ISSUE THREAD

**Issue by diegs** [kubernetes/kubernetes#46148]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): "setcap", "apiserver root", "securityContext"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): v1.6.4

**Environment**:
- **Cloud provider or hardware configuration**: gce, aws
- **OS** (e.g. from /etc/os-release): Container Linux by CoreOS 1353.7.0 (Ladybug)
- **Kernel** (e.g. `uname -a`): Linux localhost 4.9.24-coreos #1 SMP Wed Apr 26 21:44:23 UTC 2017 x86_64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz GenuineIntel GNU/Linux
- **Install tools**: bootkube
- **Others**:

**What happened**:

When setting the `runAsNonRoot: true` in the `securityContext` of an apiserver, the container is unable to bind port 443 because it does not have the `CAP_NET_BIND_SERVICE` capability.

**What you expected to happen**:

Users can (and should) be able to run the apiserver using `runAsNonRoot: true`.

**How to reproduce it** (as minimally and precisely as possible):

Add the following to the container spec for an apiserver;
```
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
```

**Anything else we need to know**:

Docker has an issue where specifying a capability for the user that runs the container does not propagate to system namespaces. In the case of the apiserver, this means that adding  `add: [CAP_NET_BIND_SERVICE]` in the securityContext to the apiserver container does actually allow the apiserver to bind to privileged ports when `hostNetwork: true`, which is typical when running an apiserver pod.

A workaround that we have tested successfully is to set the capability on the `hyperkube` binary directly: https://github.com/diegs/kubernetes/commit/c1d0a1c9dc87c96de684cd093e7c5586c57e3aa2

cc: @aaronlevy @philips

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc @kubernetes/sig-cluster-lifecycle-misc

**Comment by php-coder** [comment]
> Docker has an issue where specifying a capability for the user that runs the container does not propagate to system namespaces

Could you provide a link to this issue, please?

> In the case of the apiserver, this means that adding add: [CAP_NET_BIND_SERVICE] in the securityContext to the apiserver container does actually allow the apiserver to bind to privileged ports when hostNetwork: true

Probably, I misunderstood you, but are you suggesting to add a workaround for a docker bug to Kubernetes?

**Comment by philips** [comment]
@php-coder This is the Docker issue: https://github.com/moby/moby/issues/8460#issuecomment-258706298

**Comment by diegs** [comment]
> Probably, I misunderstood you, but are you suggesting to add a workaround for a docker bug to Kubernetes?

@php-coder Yes, we would need to invoke `setcap` on the hyperkube binary itself to grant it `CAP_NET_BIND_SERVICE`. Simply adding `CAP_NET_BIND_SERVICE` as a capability in the security context does not have the desired effect, due to the issue @philips mentioned in the previous comment.

**Comment by diegs** [comment]
Update: unfortunately my first fix (https://github.com/diegs/kubernetes/commit/c1d0a1c9dc87c96de684cd093e7c5586c57e3aa2) does not work, due to https://github.com/moby/moby/issues/20435.

A fix that does work is https://github.com/coreos/kubernetes/commit/85e2941baf3bc43d004a27e918044911d52766eb. Unfortunately this adds another Docker layer and increases the size of the binary significantly (https://github.com/coreos/kubernetes/issues/137).

**Comment by timothysc** [comment]
> When setting the runAsNonRoot: true in the securityContext of an apiserver, the container is unable to bind port 443 because it does not have the CAP_NET_BIND_SERVICE capability.

This is known, and escape hatch is 6443 isn't it... What am I missing?

**Comment by kargakis** [comment]
> This is known, and escape hatch is 6443 isn't it... What am I missing?

If we run the api server on a high port like 6443, should we close this issue? Maybe an integration test to prove that the api server can run as a non-root pod?

**Comment by diegs** [comment]
I'm fine to close this. It's fairly self-evident that running as 6443 does not require root.

**Comment by luxas** [comment]
Integration test and documentation for this sounds good

**Comment by neolit123** [comment]
as mentioned, 6443 can be used.
this is the default port that kubeadm uses and this is documented in a number of locations @ k8s.io.

/close
