### ISSUE TITLE
Clarify semantics of watch operations

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#46173]
We should clarify the watch.Interface in terms of what guarantees exist (and do not exist) on the notifications.  Specifically https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/watch/watch.go#L34-L37

Given re-connection logic on the client, and the aggregation of watches on the server, and federation of etcd with different servers for different prefixes (e.g. events & non-events) and API aggregation, I believe we guarantee:

* No ordering guarantees across different key values
* On a particular key, events will be delivered to the channel in order
* Multiple datastore modifications may result in a single MODIFIED event
* Multiple datastore modifications followed by a delete may result in a single DELETED event
* A datastore creation followed by multiple datastore modifications may result in a single CREATED event
* A datastore creation, optional series of datastore modifications, and datastore deletion may result in no events

Is that correct and approximately accurate?  If so, I'll PR to watch.go (if that's the right place).

**Comment by justinsb** [comment]
cc @k8s-mirror-api-machinery-misc

**Comment by caesarxuchao** [comment]
cc @jpbetz
