### ISSUE TITLE
updateCIDRAllocation should use PATCH to apply changes

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#46215]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

updateCIDRAllocation
CIDR
node_controller

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

in `kubernetes/pkg/controller/node/range_allocator.go` we have `updateCIDRAllocation(data nodeAndCIDR)` assign CIDR to the node and then updates the API server.
except that the update is done through this : 

```go
		node.Spec.PodCIDR = data.cidr.String()
		if _, err := r.client.Core().Nodes().Update(node); err != nil {
			glog.Errorf("Failed while updating Node.Spec.PodCIDR (%d retries left): %v", podCIDRUpdateRetry-rep-1, err)
		} else {
			break
		}
```
the update uses a put under the hood, shouldn't we use 
```go 
Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Node, err error)
```
that is provided by the `NodeInterface` ? cc @gmarek

**Comment by gmarek** [comment]
Yes, we probably should do that. Thanks for volunteering:)

**Comment by yastij** [comment]
NP, will be submitting PR tomorrow after WR. :)
