### ISSUE TITLE
why so many flake this weekend and Jenkins job name changed ?

### ISSUE THREAD

**Issue by shiywang** [kubernetes/kubernetes#46226]
In this pr: https://github.com/kubernetes/kubernetes/pull/45864,  Jenkins verification job failed, but there are another two jobs pull-kubernetes-bazel , pull-kubernetes-verify passed, do we change the jenkins job name ? 
@kubernetes/sig-testing-bugs

**Comment by ixdy** [comment]
Yes, we are changing the GitHub context names to match the job names. That should be unrelated to the flakiness, though.

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/pull/2811 for the context-renames, but agreed, shouldn't have anything to do with random jobs flaking

**Comment by shiywang** [comment]
@spiffxp @ixdy thanks, I'll close this issues but still lots of `pull-kubernetes-federation-e2e-gce` tests failed
