### ISSUE TITLE
node-controller: Unit test flake in TestUpdateNodeWithMultiplePods

### ISSUE THREAD

**Issue by rpothier** [kubernetes/kubernetes#46222]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT
**Kubernetes version** (use `kubectl version`):
This is on latest master, as of May 18

**Environment**:

CentOS vm running on a Mac

- **Cloud provider or hardware configuration**:
Hardware is MacBook Pro 

- **OS** (e.g. from /etc/os-release):
[root@localhost kubernetes]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- **Kernel** (e.g. `uname -a`):
[root@localhost kubernetes]# uname -a
Linux localhost.localdomain 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**:
- **Others**:

**What happened**:
Running unit tests am seeing consistent failures: 
--- FAIL: TestUpdateNodeWithMultiplePods (2.59s)
        taint_controller_test.go:485: Starting testcase "Pods with different toleration times are evicted appropriately"
        taint_controller_test.go:511: Sleeping for 499.999814ms
        taint_controller_test.go:520: Found not-delete action with verb list. Ignoring.
        taint_controller_test.go:531: Failed to deleted pod pod1 after 0
        taint_controller_test.go:537: Found not-delete action with verb list. Ignoring.
        taint_controller_test.go:511: Sleeping for 971.277715ms
        taint_controller_test.go:551: Pod pod1 was deleted even though it shouldn't have
        taint_controller_test.go:485: Starting testcase "Evict all pods not maching all taints instantly"
        taint_controller_test.go:511: Sleeping for 499.999855ms
        taint_controller_test.go:520: Found not-delete action with verb list. Ignoring.
        taint_controller_test.go:531: Failed to deleted pod pod1 after 0
        taint_controller_test.go:520: Found not-delete action with verb list. Ignoring.
        taint_controller_test.go:531: Failed to deleted pod pod2 after 1
        taint_controller_test.go:520: Found not-delete action with verb list. Ignoring.
        taint_controller_test.go:531: Failed to deleted pod pod3 after 2
        taint_controller_test.go:537: Found not-delete action with verb list. Ignoring.
FAIL
FAIL    k8s.io/kubernetes/pkg/controller/node   37.401s

**What you expected to happen**:
ut should pass

**How to reproduce it** (as minimally and precisely as possible):
Running UT in a CentOS vm on a Mac

**Anything else we need to know**:

**Comment by resouer** [comment]
Did you enable `--race` to run this test?

**Comment by rpothier** [comment]
No, just - make test
This is the only failure I see.
Integration tests also pass.

**Comment by oomichi** [comment]
I also am still facing this issue with a single operation of this unit test like

$ make test WHAT=k8s.io/kubernetes/pkg/controller/node/scheduler
[..]
--- FAIL: TestUpdateNodeWithMultiplePods (2.59s)
        taint_controller_test.go:485: Starting testcase "Pods with different toleration times are evicted appropriately"
        taint_controller_test.go:511: Sleeping for 499.999795ms
        taint_controller_test.go:520: Found not-delete action with verb list. Ignoring.
        taint_controller_test.go:537: Found not-delete action with verb list. Ignoring.
        taint_controller_test.go:511: Sleeping for 578.997144ms
        taint_controller_test.go:531: Failed to deleted pod pod2 after 0
        taint_controller_test.go:485: Starting testcase "Evict all pods not maching all taints instantly"
        taint_controller_test.go:511: Sleeping for 499.999913ms
        taint_controller_test.go:520: Found not-delete action with verb list. Ignoring.
        taint_controller_test.go:520: Found not-delete action with verb list. Ignoring.
        taint_controller_test.go:520: Found not-delete action with verb list. Ignoring.
        taint_controller_test.go:537: Found not-delete action with verb list. Ignoring.
FAIL
FAIL    k8s.io/kubernetes/pkg/controller/node/scheduler 30.371s
Makefile:182: recipe for target 'test' failed
make: *** [test] Error 1
oomichi@devstack:~/dev/kubernetes/kubernetes$ git checkout -f
Your branch is up-to-date with 'origin/master'.

**Comment by oomichi** [comment]
The above my comment comes from virtualbox env on Windows PC.
After the above comment, I tried to do this on physical machine and this failure seems to depend on env performance.
