### ISSUE TITLE
Support node selectors for node, drain, taint and apply to new nodes

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes#46231]
Similar to #25625, Kubernetes needs to support enforcing of node taint/drain/cordon commands through a selector continuously applied to the nodes on the server-side. Currently the way to apply these commands to a set of nodes is to get nodes and iterate on the client-side. This will not work for the scenario where cluster autoscaler is continuously adding/removing new nodes.

It should be possible to cordon or apply other scheduling constraints to a set of _existing_ nodes matching the selector(s), as well as the _new_ nodes that will be added in the future, matching the selector(s).

For example:

    kubectl cordon --selector cloud.google.com/gke-nodepool=old-node-pool
    
    kubectl taint nodes -l cloud.google.com/gke-nodepool=new-node-pool key1=value1:NoSchedule

**Comment by ahmetb** [comment]
Let me know if I should move this to `kubernetes/features` repository.

**Comment by davidopp** [comment]
ref/ #25625

@kubernetes/sig-cluster-lifecycle-feature-requests 
@kubernetes/sig-scheduling-feature-requests

**Comment by ravisantoshgudimetla** [comment]
#44740 - solved the taint part @ahmetb. I can work on drain as well once I am done with other drain PRs.

/sig cli

**Comment by xiang90** [comment]
@ravisantoshgudimetla 

i do not understand how #44740 solves the server-side enhancement issue. also why do we add this to sig-cli?

/cc @ahmetb

**Comment by ahmetb** [comment]
I think it's primarily sig-scheduling but sig-cli should be involved as setting server-side taints would be done through kubectl, I assume.

**Comment by ncmans** [comment]
This is not resolved yet. Should I open a new issue for this?
