### ISSUE TITLE
/proc/sys/fs/inotify/max_user_watches is too low

### ISSUE THREAD

**Issue by hubt** [kubernetes/kubernetes#46230]
**Is this a request for help?** 
No

**What keywords did you search in Kubernetes issues before filing this one?**
max_user_watches
#32526

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
AWS Kops
- **OS** (e.g. from /etc/os-release):
Debian/jessie
- **Kernel** (e.g. `uname -a`):
Linux ip-172-21-0-25 4.4.26-k8s #1 SMP Fri Oct 21 05:21:13 UTC 2016 x86_64 GNU/Linux

```sysctl -a | grep fs.inotify.max_user_watches
fs.inotify.max_user_watches = 8192
```
**What happened**:
Many node.js applications use file watches on many directories to detect when to reload the application dynamically. Running out of file watches will result in `ENOSPC` errors.

**What you expected to happen**:
No ENOSPC errors.

**How to reproduce it** (as minimally and precisely as possible):
In any pod, do this:
```
sudo apt-get install -y inotify-tools
for i in `seq 1 10000`; do mkdir $i ; done
inotifywait *
Setting up watches.
Failed to watch 8215; upper limit on inotify watches reached!
Please increase the amount of inotify watches allowed per user via `/proc/sys/fs/inotify/max_user_watches'.
```

**Anything else we need to know**:
temporary fix is to 
```
sudo sysctl fs.inotify.max_user_watches=524288
```
permanent fix is to
```
echo "fs.inotify.max_user_watches=524288" >> /etc/sysctl.conf
```

Raising the limit to 128k+ would usually solve the problem. The exact number would be up for discussion.

**Comment by pierreozoux** [comment]
I think this issue is not really related to k8s in itself but more the underlying OS it is running on.
As you use kops, it would be more appropriate to fix the issue there.

I actually just opened an issue related to that:
https://github.com/kubernetes/kops/issues/2709

**Comment by pierreozoux** [comment]
@hubt could you close the issue please?

**Comment by hubt** [comment]
ok

**Comment by Ekwav** [comment]
B
