### ISSUE TITLE
Enforce consistent naming of kubectl generators

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#46237]
For context see: https://github.com/kubernetes/kubernetes/blob/c0920f75cf75432554ffb3f5eaed0f26598899c3/pkg/kubectl/cmd/util/factory_client_access.go#L457-L485

Generators are used by folks using kubectl to enforce a certain behavior which is guaranteed to be backward compatible.
Different generators use different conventions for naming, some of which are:

```
1. resource/<version of generator>
2. resource/<API Version>
3. <kubectl-command>/<group-name>.<API Version>
4. ...many more
```
We should converge these to adopt standardized nomenclature.

cc @bgrant0607 @pwittrock @kubernetes/sig-cli-misc

**Comment by adohe** [comment]
From the generator interface definition, it is used to create API objects, so how about `api_object/api_version` format? @kubernetes/sig-cli-misc

**Comment by kargakis** [comment]
@adohe what if we have two generators for the same GVK but with different defaults?
