### ISSUE TITLE
Upgrade Test for PDB Max Unavailable

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/kubernetes#46250]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
N/A
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): misc

**Kubernetes version** (use `kubectl version`): N/A

**Environment**: N/A
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Helping @foxish to write upgrade test for the PDB max unavailable feature.

**What you expected to happen**:
Had an upgrade test covering the feature.

**How to reproduce it** (as minimally and precisely as possible):
N/A

**Anything else we need to know**:
I will work on this.

**Comment by pwittrock** [comment]
@foxish I don't think we need to label this in the v1.7 milestone, since it doesn't need to be tracked by the release team.

**Comment by pwittrock** [comment]
Removed from the milestone.  Feel free to add back if there is a compelling reason to do so.
