### ISSUE TITLE
Feature: Allow user to add extra tags to any AWS resource created by the cluster

### ISSUE THREAD

**Issue by jescarri** [kubernetes/kubernetes#46257]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): aws tag

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request.

**Kubernetes version** (use `kubectl version`):
````
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3+coreos.0", GitCommit:"8fc95b64d0fe1608d0f6c788eaad2c004f31e7b7", GitTreeState:"clean", BuildDate:"2017-02-15T19:52:15Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
````

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Container Linux by CoreOS stable (1353.7.0)
- **Kernel** (e.g. `uname -a`): Linux  4.9.24-coreos #1 SMP Wed Apr 26 21:44:23 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux
- **Install tools**: Tectonic Installer
- **Others**:

**What you expected to happen**:
Users should be able to specify extra tags for any aws resource created by the cluster, 
AWS resources should have the cluster added tags and user defined.

**How to reproduce it** (as minimally and precisely as possible):
Create a pvc, there is no way to specify extra tags.

**Anything else we need to know**:
There is a PR for ELB https://github.com/kubernetes/community/pull/404 that partially fix this issue.

**Comment by philips** [comment]
The PR that fixes the issue is here: https://github.com/kubernetes/kubernetes/pull/45932

cc @lpabon

**Comment by jescarri** [comment]
@philips is there a way to extend the pr to ebs volumes as well?

**Comment by lpabon** [comment]
@jescarri @philips I can create another PR which adds that to #45932

**Comment by lpabon** [comment]
Actually, I may be wrong, but the ebs volumes are created from a PVC/PV. I would have to investigate the scope of that work.

**Comment by jescarri** [comment]
Any update on this issue?
does the annotation `volume.beta.kubernetes.io/aws-ebs-additional-resource-tags` makes sense?
