### ISSUE TITLE
can not build k8s component binaries without symbol table and debug info

### ISSUE THREAD

**Issue by bruceauyeung** [kubernetes/kubernetes#46274]
i try to build kubernetes components without symbol table and debug info. so i run
`make quick-release GOLDFLAGS="-s -w"`

but k8s conponent binary size is not reduced.

If i understand Makefile correctly,the previous command should work

codesnippets from Makefile
>KUBE_GOFLAGS := $(GOFLAGS)
KUBE_GOLDFLAGS := $(GOLDFLAGS)
KUBE_GOGCFLAGS = $(GOGCFLAGS)
>
>\# Extra options for the release or quick-release options:
>KUBE_RELEASE_RUN_TESTS := $(KUBE_RELEASE_RUN_TESTS) 
>KUBE_FASTBUILD := $(KUBE_FASTBUILD)
>
>\# This controls the verbosity of the build.  Higher numbers mean more output.
>KUBE_VERBOSE ?= 1
>
>define ALL_HELP_INFO
>\# Build code.
>\#
>\# Args:
>\#   WHAT: Directory names to build.  If any of these directories has a 'main'
>\#     package, the build will produce executable files under $(OUT_DIR)/go/bin.
>\#     If not specified, "everything" will be built.
>\#   GOFLAGS: Extra flags to pass to 'go' when building.
>\#   GOLDFLAGS: Extra linking flags passed to 'go' when building.
>\#   GOGCFLAGS: Additional go compile flags passed to 'go' when building.
>\#
>\# Example:
>\#   make
>\#   make all
>\#   make all WHAT=cmd/kubelet GOFLAGS=-v
>\#   make all GOGCFLAGS="-N -l"
>\#     Note: Use the -N -l options to disable compiler optimizations an inlining.
>\#           Using these build options allows you to subsequently use source
>\#           debugging tools like delve.
>

**Comment by xiangpengzhao** [comment]
I tried `make GOLDFLAGS="-s -w"`, it works expected. I have a quick view of make scripts, it seems like `make quick-release` doesn't respect `GOLDFLAGS`. 

@thockin would you please confirm this? Thanks!

**Comment by thockin** [comment]
PRs welcome!
