### ISSUE TITLE
kubelet and kube-proxy fail to reload certificates when they are updated

### ISSUE THREAD

**Issue by Spindel** [kubernetes/kubernetes#46287]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): tls certificate reload

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-25T14:48:12Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+coreos.0", GitCommit:"9212f77ed8c169a0afa02e58dce87913c6387b3e", GitTreeState:"clean", BuildDate:"2017-04-04T00:32:53Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

```

**Environment**:
- **Cloud provider or hardware configuration**:
Digital Ocean / custom setup
- **OS** (e.g. from /etc/os-release):
coreos VERSION=1353.7.0

- **Kernel** (e.g. `uname -a`):
Linux coreos01.kub.do.modio.se 4.9.24-coreos #1 SMP Wed Apr 26 21:44:23 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz GenuineIntel GNU/Linux

- **Install tools**:
Ansible / CoreOS getting started guide

- **Others**:

**What happened**:
We came up to our scheduled update of TLS client certificate,  TLS certs were updated properly, but kubelet and kube-proxy keep the old Certs in memory.  This causes them to fail when communicating with APIserver.

**What you expected to happen**:
kubelet & kube proxy should reload the certificates from disk. 

**How to reproduce it** (as minimally and precisely as possible):
Generate a cert with a short lifetime, set up your cluster, wait a while, and then replace the cert with a longer lived one.

**Anything else we need to know**:
We're attempting to run with short lived client certificates. This has shown some issues with how kubernetes handles it, and will likely cause others to have hard to debug problems in the future.

**Comment by alkar** [comment]
Experiencing the same issue.
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-12T00:44:36Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1+coreos.0", GitCommit:"59359d9fdce74738ac9a672d2f31e9a346c5cece", GitTreeState:"clean", BuildDate:"2017-10-12T21:53:13Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by FarhadF** [comment]
Experiencing the same issue, Just tried to replace the certificates with new one.
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by FarhadF** [comment]
My work around:
1. Replace certificates with new ones
2. change systemd service execstart to one liner:
```
ExecStart=/usr/bin/kubelet   --kubeconfig=/etc/kubelet/kubeconfig   --allow-privileged=true   --cluster-dns=10.96.0.10   --cluster-domain=cluster.local   --container-runtime=docker   --docker=unix:///var/run/docker.sock   --network-plugin=cni   --serialize-image-pulls=false   --tls-cert-file=/etc/kubernetes/k2.pem   --tls-private-key-file=/etc/kubernetes/k2-key.pem   --cni-conf-dir=/etc/cni/net.d   --cni-bin-dir=/opt/cni/bin   --v=2
```
I was using \ to have multi lines, you can even use your oneline at terminal for fast verification.
3. `systemctl daemon-reload`
4. `openssl s_client -connect <nodename>:10250 -showcerts`
you should see cert chain and no selfsigned errors:
```
Certificate chain
 0 s:/CN=k2
   i:/CN=kube-ca
Server certificate
subject=/CN=k2
issuer=/CN=kube-ca
```

**Comment by george-angel** [comment]
Can someone please re-open this issue? Its quiet a significant one for us. We currently need trello cards with due time set a year ahead with a reminder to restart kube-proxy.

**Comment by george-angel** [comment]
Ping

**Comment by riking** [comment]
Is this a duplicate of #4672 ?

**Comment by george-angel** [comment]
It can be considered a subset, depending on how https://github.com/kubernetes/kubernetes/issues/4672 unfolds, currently its very broad.

**Comment by jayunit100** [comment]
hmm, hot reload for kube proxy i think wont be supported ? long issue around this...

**Comment by jayunit100** [comment]
im pretty sure this is a "wont fix" for the existing kube-proxy because, allowing hot-reload can potenitally break people who *expect* that config changes *will not* result in a reload of configuration.... can someone confirm or deny this ?

**Comment by jayunit100** [comment]
ive added an agenda item to https://docs.google.com/document/d/1_w77-zG_Xj0zYvEMfQZTQ-wPP4kXkpGD8smVtW_qqWM/edit to decide on how to handle hot reload issues, theres lots of them i.e. https://github.com/kubernetes/kubernetes/issues/57144

**Comment by neolit123** [comment]
/sig network node
as per the offending component owners.

**Comment by kfox1111** [comment]
What is the status of this with respect to kubelet? How do people refresh their certificates with an external ca without restarting kubelet?

**Comment by george-angel** [comment]
We restart kubelet and some other components daily (thats how often we refresh certificates), using a systemd timer. Not elegant, but works.

**Comment by thockin** [comment]
Maybe we can big-hammer this?  If the file changes, `os.Exit()` - it's clumsy but it should work?

Help Wanted

**Comment by dcbw** [comment]
Kubelet already has facility to watch files, it does that for the static pods file; see pkg/kubelet/config/file.go and friends. It's not very well encapsulated since it looks like it's supposed to be generic ("NewSourceFile watches a config file for changes.") but the code is fairly static pods specific (`updates <- kubetypes.PodUpdate{Pods: pods, Op: kubetypes.SET, Source: kubetypes.FileSource}`).

But it could be fairly easily genericized to just return an event when some other config file changes, whereupon kubelet could just exit.

**Comment by aojea** [comment]
Kubelet docs https://kubernetes.io/docs/tasks/tls/certificate-rotation/#enabling-client-certificate-rotation

**Comment by jayunit100** [comment]
The root cause as I recall was that there was a bug in the fs notify library of golang that causes the kube proxy config map to not be updated on disks 

Then we got into a debate about wether the kube proxy should hot reload at all ... as that was another tricky thing to determine.... so we kinda just stopped worrying about this.

**Comment by kfox1111** [comment]
Would still be a very useful feature when used along with automation such as acme/spire to get the certs and they would have short lifespans.

**Comment by shaneutt** [comment]
@kfox1111 I noticed you removed the stale from this issue and I was just curious: are you interested in working on this and helping to move it forward?

**Comment by kfox1111** [comment]
I'd really like to see it fixed. I may not be the right person to do it though. Is there someone more familiar with Kubelets code base that we could find?

**Comment by kfox1111** [comment]
Semi related, I'm also interested in seeing if either this mechanism or direct integration with spire is possible for the certs.

**Comment by shaneutt** [comment]
Gotcha! Well I don't know of anyone _right this moment_ that has the bandwidth/priority to take this one on (thus why it's been continually going stale), but if you think you might have some time to spare I would encourage you to not worry about being a kubelet or kube-proxy expert. Reach out to the community (Slack, Zooms) and let them know you're trying to learn how to get this one fixed: I expect you'll find the community can provide some level of assistance (even if they themselves might not have the bandwidth/priority to take the whole thing on).

**Comment by shaneutt** [comment]
While we're still open to someone with capacity taking this one on, since it's been some time without anyone who can it seems the previous lifecycle was accurate:

/lifecycle rotten

If you're interested in picking this one up, let us know and we will support you!

**Comment by kfox1111** [comment]
It hasn't risen to the top of the todo list yet especially since it needs so much searching out for help and its not clear who can do so to me. (sig-auth, sig-node, sig-cluster-lifecycle, other?)

If we could identify some developers with knowledge of roughly what needs to be done, to which places, that would go a long way.

**Comment by shaneutt** [comment]
Is it something you'd like to put on the agenda for our next SIG Network meeting and come talk about it with us so we can start figuring it out?

**Comment by aojea** [comment]
@kfox1111 can you expand more on how are you doing today to update the certificates in kube-proxy? also to know how do you deploy kube-proxy, are you using a daemonset?
It will be useful to understand better your workflow to come up with the best solution

**Comment by kfox1111** [comment]
@shaneutt https://docs.google.com/document/d/1_w77-zG_Xj0zYvEMfQZTQ-wPP4kXkpGD8smVtW_qqWM/edit  Mar 28 at 9am pst? I think I can make that, if so.

@aojea I'm not yet doing anything but deploying with kubeadm. Ideally though, I'd like to be able to use a spire chain of trust for the cluster, attesting with either tpms on bare metal, or a cloud based node attestor for vms. They have already done a lot of the heavy lifting. We just need a machanism to get the certs from spire to k8s.

This would have some big benefits:
 * much shorter lived certificates, rolled automatically (hours or days)
 * node attestation. Rather then an initial bootstrap join token like thing, stronger mechanisms like tpms can be used to prove identity. No need to ssh in (how do you validate ssh host sig?) and copy join material from control plane to node. It can be automatic and safe.
 * periodic reattestation. On certificate refresh, continued poof of identity can be done. For example, handshaking with the tpm again to ensure it is still on the same node.
 * kubeadm has had a long standing issue with kubelet server certs being self signed. The same mechanism can be used to give kubelet (and maybe some other services) proper certificates in a validatable chain of trust.

**Comment by kfox1111** [comment]
Was referred to sig-auth from sig-network on this issue.

**Comment by aojea** [comment]
@enj we were discussing this issue today in sig network and our understanding was that this is related about how client-go load the certificates so we are moving this to sig auth

/sig auth

**Comment by kfox1111** [comment]
client-go is 1/2 of the issue.

The server being able to use updated certificates without restart is also important and does not use client-go.

**Comment by stlaz** [comment]
per triage:
Someone from the auth team should have a look and see what the issue is based on the comments in the issue. The original comment does not explain which exact certificates are not being reloaded.

**Comment by george-angel** [comment]
1. Is `tlsCertFile` as part of `KubeletConfiguration`. We set this to 7d TTL and refresh daily. Kubelet needs to be restarted to use the new certificate.
2. `clientCAFile` as part of:

```
authentication:
  x509:
    clientCAFile: "/etc/kubernetes/ssl/ca.pem"
```

config in the same `KubeletConfiguration` file. This has 1 - 2 yr validity for us, and again Kubelet (and kube-proxy) need a restart to use this.

**Comment by kfox1111** [comment]
Still an issue. Please reopen

**Comment by zhangweikop** [comment]
> client-go is 1/2 of the issue.
> 
> The server being able to use updated certificates without restart is also important and does not use client-go.

Yes.
Recent change in kubelet  [124574](https://github.com/kubernetes/kubernetes/pull/124574) intended to resolve the second half.

**Comment by kfox1111** [comment]
Awesome. :)

Does it do the CA's too or just the client/server certs?

**Comment by zhangweikop** [comment]
> Awesome. :)
> 
> Does it do the CA's too or just the client/server certs?

Not CA. Only certs.

From what I know for kubelet:
Both the [server tls config](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L1171) and client-go tls config doesn't do **CA File** dynamic reload as of today
