### ISSUE TITLE
tests: please update pkg/kubelet/server TestServeExecInContainer and TestServeAttachContainer for Go1.9

### ISSUE THREAD

**Issue by odeke-em** [kubernetes/kubernetes#46282]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
TestServeExecInContainer
response location

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
* BUG REPORT

**Kubernetes version** (use `kubectl version`):
Kubernetes at commit 8bee44b65f2fbf170f70c535b5ec1b3cbfad44b6
Sorry, I haven't installed kubectl, I was just wandering around the code

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
OS X
- **Kernel** (e.g. `uname -a`):
Darwin Emmanuels-MacBook-Pro-2.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
- **Install tools**:
Installed from source
- **Others**:

**What happened**:
Tests:
*  TestServeExecInContainer
*  TestServeAttachContainer
fail as of Go tip https://github.com/golang/go/commit/6a6c792eef55eded7fb3165a330ec2b239b83960 which will be part of Go1.9

**What you expected to happen**:
Those tests to pass

**How to reproduce it** (as minimally and precisely as possible):
Run tests:
*  TestServeExecInContainer
*  TestServeAttachContainer

**Anything else we need to know**:
The tests seem to be adapted to an old/buggy behavior of Go's http.ServeMux not forwarding along
the query string during redirects as per https://github.com/golang/go/issues/17841.
The bug in Go has since been fixed by CL https://golang.org/cl/43779 and I got this failure when running `make test` in Kubernetes
in particular
```
server_test.go:1327: 7: response location: expected http://localhost:12345/exec, got http://localhost:12345/exec?ignore=1&command=ls&command=-a&output=1
```
or in detail
```shell
E0523 04:03:05.187580   89629 server.go:244] Authorization error (user=test, verb=, resource=, subresource=)%!(EXTRA *errors.errorString=Failed)
E0523 04:03:05.318837   89629 server.go:656] you must specify at least 1 of stdin, stdout, stderr
--- FAIL: TestServeExecInContainer (0.03s)
	server_test.go:1327: 7: response location: expected http://localhost:12345/exec, got http://localhost:12345/exec?ignore=1&command=ls&command=-a&output=1
E0523 04:03:05.351045   89629 server.go:618] you must specify at least 1 of stdin, stdout, stderr
--- FAIL: TestServeAttachContainer (0.03s)
	server_test.go:1327: 7: response location: expected http://localhost:12345/attach, got http://localhost:12345/attach?ignore=1&output=1
E0523 04:03:05.528501   89629 server.go:730] query parameter "port" cannot be empty
E0523 04:03:05.530809   89629 server.go:730] unable to parse "abc" as a port: strconv.ParseUint: parsing "abc": invalid syntax
E0523 04:03:05.532914   89629 server.go:730] unable to parse "-1" as a port: strconv.ParseUint: parsing "-1": invalid syntax
E0523 04:03:05.534807   89629 server.go:730] unable to parse "65536" as a port: strconv.ParseUint: parsing "65536": value out of range
E0523 04:03:05.536912   89629 server.go:730] port "0" must be > 0
```
or
<img width="1174" alt="screen shot 2017-05-23 at 4 14 28 am" src="https://cloud.githubusercontent.com/assets/4898263/26350283/df5b5604-3f6f-11e7-8b27-555c03d586b8.png">

Prior to that CL, the test passes
```shell
ok  	k8s.io/kubernetes/pkg/kubelet/server	0.525s
```

I am also going to add a small memo to the Go project's bug tracker that that fix broke things here, just to keep vigilant.

**Comment by cmluciano** [comment]
@kubernetes/sig-testing-misc

**Comment by cmluciano** [comment]
@kubernetes/sig-node-misc

**Comment by ixdy** [comment]
cc @kubernetes/sig-node-bugs

**Comment by yujuhong** [comment]
Go 1.9 upgrade is already done.
