### ISSUE TITLE
[cli] Proposal: make kubectl exec --stdin and --tty default to true

### ISSUE THREAD

**Issue by olalonde** [kubernetes/kubernetes#46300]
It seems that, much more often than not, I use the `-it` flag with kubectl exec, e.g. `kubectl exec -it somepodname bash`. A Google for `kubectl exec` also seems to indicate that `kubectl exec` is overwhelmingly used with `-it`.

Therefore, I'd like to propose that we make those flags (`-i/--stdin` and `-t/--tty`) true by default, with the option of disabling them (instead of the other way around). Plus, the main use case for `kubectl exec` without `-it` is usually scripting, which is done by more advanced users who would more likely know about those flags.

The two main drawbacks of this proposal are that it would be a breaking change and would make `kubectl exec` a bit more different from `docker exec`.

Anyways, food for thought...

**Comment by adohe** [comment]
@olalonde IIRC the default value in `docker exec` is false. [docker exec](https://docs.docker.com/engine/reference/commandline/exec)

**Comment by olalonde** [comment]
@adohe right, which I noted in my drawbacks list.

**Comment by liggitt** [comment]
breaking compatibility for this reason would not be acceptable
