### ISSUE TITLE
Node E2E ssh calls should have timeout.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#46310]
SSH calls without timeout have caused some trouble. The most recent one is that in node e2e, we ssh into the instance and run `docker version` to check whether the instance is ready or not.

However, once docker hungs, `docker version` will never return, and the framework will also hung forever. After the test timed out, it seems that the framework didn't cleanup the VM because it still hung on the ssh command.

We should add timeout to ssh calls to avoid this kind of problem.

/cc @kubernetes/sig-node-bugs

**Comment by PengTaoWW** [comment]
@Random-Liu I would like to take a look at it if no one is working on this.

**Comment by PengTaoWW** [comment]
@Random-Liu look like https://github.com/kubernetes/kubernetes/pull/23843 fixed it

**Comment by yujuhong** [comment]
@PengTaoWW, I don't think node e2e uses the ssh package fixed in #23843

**Comment by PengTaoWW** [comment]
@yujuhong  If nobody is working in this case . i can take it . The next step is I submit a PR  or  you  assign to me ?

**Comment by PengTaoWW** [comment]
@Random-Liu If nobody is working in this case . i can take it . The next step is I submit a PR or you assign to me ?
@yujuhong is this right？I'm a newcomer, and I'm not quite sure about the steps here.

**Comment by ibrasho** [comment]
@Random-Liu I'd assume switching to the `pkg/ssh` implementation is the best solution here. Otherwise, it would be complicated to implement timeout handling (and killing the remote hung process) using `exec`.

**Comment by themanifold** [comment]
I'm considering taking this on, @Random-Liu and @kubernetes/sig-node-bugs do you think @ibrasho is right that we switch over to `pkg/ssh`?
