### ISSUE TITLE
Execution retry and timeout of lifecycle hooks

### ISSUE THREAD

**Issue by PengTaoWW** [kubernetes/kubernetes#46321]
I have an improvement on Kubernetes, in our production environment, run perstop hook when removing pod, but no matter how quickly the result of this pod is removed, my improvement is that when Perstop fails, it will retry until the execution succeeds, or the timeout is removed. I have implemented a version of this feature myself. if there's a problem with my improvement, please let me know, thank you.

ps： https://github.com/kubernetes/community/issues/653

**Comment by PengTaoWW** [comment]
https://github.com/kubernetes/kubernetes/pull/46409/files
if any one want this feature, can email me or see this patch, most code are generated. you just need kubernetes/api/ , kuberentes/pkg/api/types.go , kubernetes/pkg/api/v1/types_swagger_doc_generated.go, 
kubernetes/pkg/api/v1/types.go
and run kubernetes/hack/update-codecgen.sh,
kubernetes/hack/update-generated-protobuf.sh
then you use it

**Comment by PengTaoWW** [comment]
@xiangpengzhao https://github.com/kubernetes/kubernetes/pull/46426  cleancode version

**Comment by tacy** [comment]
@PengTaoWW  - Could you retry in the prestop hook

**Comment by PengTaoWW** [comment]
In the Prestop design, it is executed only once, 2 seconds after the removal of the container, in our production environment, in the killing of containers before the need for a long time to detect traffic disappeared. Then the process of executing the delete container. So, in terms of semantics, we need Prestop hooks to notify upstream load balancing to stop sending traffic to the container. Then the second action needs to be Retryuntilhook to check if the traffic has been deleted. Using a Prestophook can solve the problem. But for us, the semantics are not clear enough, and it is inconsistent with Prestop's design.

在 2017-05-26 11:49:46，"tacy" <notifications@github.com> 写道：


@PengTaoWW - Could you retry in the prestop hook
