### ISSUE TITLE
Pod lost connection to glusterfs volumes after kubelet restarts

### ISSUE THREAD

**Issue by hiscal2015** [kubernetes/kubernetes#46331]
Hi, all

I'm running Kubernetes 1.5.4, all components are docker (In Rancher environment). I have a few pods running with glusterfs volumes, if I restart kubelet container, then all of my applications stop working because they lost connection to glusterfs volumes. Can anyone tell me how to fix it? Thanks a lot.

```
5/24/2017 4:42:31 PMW0524 08:42:31.473548    8074 prober.go:98] No ref for container "docker://b2ce06bef0f26015c7955828bf9c2974c7536d640294a72190ef88a372425812" (devops-grafana-2716347886-lvp2z_default(dc712587-405a-11e7-a8e8-02855b10b453):devops-grafana)
5/24/2017 4:42:41 PMW0524 08:42:41.473603    8074 prober.go:98] No ref for container "docker://b2ce06bef0f26015c7955828bf9c2974c7536d640294a72190ef88a372425812" (devops-grafana-2716347886-lvp2z_default(dc712587-405a-11e7-a8e8-02855b10b453):devops-grafana)
5/24/2017 4:42:51 PMW0524 08:42:51.473546    8074 prober.go:98] No ref for container "docker://b2ce06bef0f26015c7955828bf9c2974c7536d640294a72190ef88a372425812" (devops-grafana-2716347886-lvp2z_default(dc712587-405a-11e7-a8e8-02855b10b453):devops-grafana)
5/24/2017 4:43:01 PMW0524 08:43:01.473630    8074 prober.go:98] No ref for container "docker://b2ce06bef0f26015c7955828bf9c2974c7536d640294a72190ef88a372425812" (devops-grafana-2716347886-lvp2z_default(dc712587-405a-11e7-a8e8-02855b10b453):devops-grafana)
5/24/2017 4:43:02 PME0524 08:43:02.378672    8074 glusterfs.go:122] glusterfs: failed to get endpoints storage-volume[an empty namespace may not be set when a resource name is provided]
5/24/2017 4:43:02 PME0524 08:43:02.378729    8074 reconciler.go:433] Could not construct volume information: MountVolume.NewMounter failed for volume "kubernetes.io/glusterfs/dc712587-405a-11e7-a8e8-02855b10b453-storage-volume" (spec.Name: "storage-volume") pod "dc712587-405a-11e7-a8e8-02855b10b453" (UID: "dc712587-405a-11e7-a8e8-02855b10b453") with: an empty namespace may not be set when a resource name is provided
5/24/2017 4:43:03 PME0524 08:43:03.128967    8074 kubelet.go:1522] Unable to mount volumes for pod "devops-grafana-2716347886-lvp2z_default(dc712587-405a-11e7-a8e8-02855b10b453)": timeout expired waiting for volumes to attach/mount for pod "default"/"devops-grafana-2716347886-lvp2z". list of unattached/unmounted volumes=[storage-volume]; skipping pod
5/24/2017 4:43:03 PME0524 08:43:03.129005    8074 pod_workers.go:184] Error syncing pod dc712587-405a-11e7-a8e8-02855b10b453, skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"devops-grafana-2716347886-lvp2z". list of unattached/unmounted volumes=[storage-volume]
5/24/2017 4:43:03 PMI0524 08:43:03.981518    8074 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/dc712587-405a-11e7-a8e8-02855b10b453-default-token-jh2t1" (spec.Name: "default-token-jh2t1") pod "dc712587-405a-11e7-a8e8-02855b10b453" (UID: "dc712587-405a-11e7-a8e8-02855b10b453").
5/24/2017 4:43:04 PMI0524 08:43:04.181435    8074 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/dc712587-405a-11e7-a8e8-02855b10b453-ldapcacert-volume" (spec.Name: "ldapcacert-volume") pod "dc712587-405a-11e7-a8e8-02855b10b453" (UID: "dc712587-405a-11e7-a8e8-02855b10b453").
5/24/2017 4:43:04 PMI0524 08:43:04.588684    8074 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/configmap/dc712587-405a-11e7-a8e8-02855b10b453-config-volume" (spec.Name: "config-volume") pod "dc712587-405a-11e7-a8e8-02855b10b453" (UID: "dc712587-405a-11e7-a8e8-02855b10b453").
5/24/2017 4:43:11 PME0524 08:43:11.581567    8074 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/glusterfs/dc712587-405a-11e7-a8e8-02855b10b453-storage-volume\" (\"dc712587-405a-11e7-a8e8-02855b10b453\")" failed. No retries permitted until 2017-05-24 08:45:11.581541056 +0000 UTC (durationBeforeRetry 2m0s). Error: MountVolume.SetUp failed for volume "kubernetes.io/glusterfs/dc712587-405a-11e7-a8e8-02855b10b453-storage-volume" (spec.Name: "storage-volume") pod "dc712587-405a-11e7-a8e8-02855b10b453" (UID: "dc712587-405a-11e7-a8e8-02855b10b453") with: stat /var/lib/kubelet/pods/dc712587-405a-11e7-a8e8-02855b10b453/volumes/kubernetes.io~glusterfs/storage-volume: transport endpoint is not connected
5/24/2017 4:45:03 PME0524 08:45:03.482138    8074 kubelet.go:1522] Unable to mount volumes for pod "devops-grafana-2716347886-lvp2z_default(dc712587-405a-11e7-a8e8-02855b10b453)": timeout expired waiting for volumes to attach/mount for pod "default"/"devops-grafana-2716347886-lvp2z". list of unattached/unmounted volumes=[storage-volume]; skipping pod
5/24/2017 4:45:03 PME0524 08:45:03.482166    8074 pod_workers.go:184] Error syncing pod dc712587-405a-11e7-a8e8-02855b10b453, skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"devops-grafana-2716347886-lvp2z". list of unattached/unmounted volumes=[storage-volume]
5/24/2017 4:45:03 PMI0524 08:45:03.981207    8074 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/dc712587-405a-11e7-a8e8-02855b10b453-ldapcacert-volume" (spec.Name: "ldapcacert-volume") pod "dc712587-405a-11e7-a8e8-02855b10b453" (UID: "dc712587-405a-11e7-a8e8-02855b10b453").
5/24/2017 4:45:04 PMI0524 08:45:04.382213    8074 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/configmap/dc712587-405a-11e7-a8e8-02855b10b453-config-volume" (spec.Name: "config-volume") pod "dc712587-405a-11e7-a8e8-02855b10b453" (UID: "dc712587-405a-11e7-a8e8-02855b10b453").
5/24/2017 4:45:04 PMI0524 08:45:04.581562    8074 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/dc712587-405a-11e7-a8e8-02855b10b453-default-token-jh2t1" (spec.Name: "default-token-jh2t1") pod "dc712587-405a-11e7-a8e8-02855b10b453" (UID: "dc712587-405a-11e7-a8e8-02855b10b453").
5/24/2017 4:45:11 PME0524 08:45:11.781435    8074 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/glusterfs/dc712587-405a-11e7-a8e8-02855b10b453-storage-volume\" (\"dc712587-405a-11e7-a8e8-02855b10b453\")" failed. No retries permitted until 2017-05-24 08:47:11.781402628 +0000 UTC (durationBeforeRetry 2m0s). Error: MountVolume.SetUp failed for volume "kubernetes.io/glusterfs/dc712587-405a-11e7-a8e8-02855b10b453-storage-volume" (spec.Name: "storage-volume") pod "dc712587-405a-11e7-a8e8-02855b10b453" (UID: "dc712587-405a-11e7-a8e8-02855b10b453") with: stat /var/lib/kubelet/pods/dc712587-405a-11e7-a8e8-02855b10b453/volumes/kubernetes.io~glusterfs/storage-volume: transport endpoint is not connected
5/24/2017 4:46:02 PME0524 08:46:02.578710    8074 glusterfs.go:122] glusterfs: failed to get endpoints storage-volume[an empty namespace may not be set when a resource name is provided]
5/24/2017 4:46:02 PME0524 08:46:02.578760    8074 reconciler.go:433] Could not construct volume information: MountVolume.NewMounter failed for volume "kubernetes.io/glusterfs/dc712587-405a-11e7-a8e8-02855b10b453-storage-volume" (spec.Name: "storage-volume") pod "dc712587-405a-11e7-a8e8-02855b10b453" (UID: "dc712587-405a-11e7-a8e8-02855b10b453") with: an empty namespace may not be set when a resource name is provided
5/24/2017 4:47:03 PME0524 08:47:03.761514    8074 kubelet.go:1522] Unable to mount volumes for pod "devops-grafana-2716347886-lvp2z_default(dc712587-405a-11e7-a8e8-02855b10b453)": timeout expired waiting for volumes to attach/mount for pod "default"/"devops-grafana-2716347886-lvp2z". list of unattached/unmounted volumes=[storage-volume]; skipping pod
5/24/2017 4:47:03 PME0524 08:47:03.761539    8074 pod_workers.go:184] Error syncing pod dc712587-405a-11e7-a8e8-02855b10b453, skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"devops-grafana-2716347886-lvp2z". list of unattached/unmounted volumes=[storage-volume]
5/24/2017 4:47:04 PMI0524 08:47:04.381551    8074 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/dc712587-405a-11e7-a8e8-02855b10b453-default-token-jh2t1" (spec.Name: "default-token-jh2t1") pod "dc712587-405a-11e7-a8e8-02855b10b453" (UID: "dc712587-405a-11e7-a8e8-02855b10b453").
5/24/2017 4:47:04 PMI0524 08:47:04.581770    8074 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/dc712587-405a-11e7-a8e8-02855b10b453-ldapcacert-volume" (spec.Name: "ldapcacert-volume") pod "dc712587-405a-11e7-a8e8-02855b10b453" (UID: "dc712587-405a-11e7-a8e8-02855b10b453").
5/24/2017 4:47:04 PMI0524 08:47:04.982160    8074 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/configmap/dc712587-405a-11e7-a8e8-02855b10b453-config-volume" (spec.Name: "config-volume") pod "dc712587-405a-11e7-a8e8-02855b10b453" (UID: "dc712587-405a-11e7-a8e8-02855b10b453").
5/24/2017 4:47:12 PME0524 08:47:12.182109    8074 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/glusterfs/dc712587-405a-11e7-a8e8-02855b10b453-storage-volume\" (\"dc712587-405a-11e7-a8e8-02855b10b453\")" failed. No retries permitted until 2017-05-24 08:49:12.182086454 +0000 UTC (durationBeforeRetry 2m0s). Error: MountVolume.SetUp failed for volume "kubernetes.io/glusterfs/dc712587-405a-11e7-a8e8-02855b10b453-storage-volume" (spec.Name: "storage-volume") pod "dc712587-405a-11e7-a8e8-02855b10b453" (UID: "dc712587-405a-11e7-a8e8-02855b10b453") with: stat /var/lib/kubelet/pods/dc712587-405a-11e7-a8e8-02855b10b453/volumes/kubernetes.io~glusterfs/storage-volume: transport endpoint is not connected
```

**Comment by hiscal2015** [comment]
I tested it again, here're steps we can reproduce the issue:

Deploy one pod with glusterfs volume, check it is running
Restart kubelet container
Kubelet container lost connection to glusterfs immediately
[2017-05-26 12:15:28.167691] I [MSGID: 115036] [server.c:559:server_rpc_notify] 0-devops-grafana-dev-server: disconnecting connection from devserver02-6802-2017/05/26-12:13:06:422784-devops-grafana-dev-client-0-0-0
[2017-05-26 12:15:28.168330] I [MSGID: 101055] [client_t.c:436:gf_client_unref] 0-devops-grafana-dev-server: Shutting down connection devserver02-6802-2017/05/26-12:13:06:422784-devops-grafana-dev-client-0-0-0
After kubelet container restarted and running, glusterfs volumes kept disconnected
Lots of "Orphaned pod" logs in kubelet
5/26/2017 8:37:39 PME0526 12:37:39.270244    3124 glusterfs.go:122] glusterfs: failed to get endpoints storage-volume[an empty namespace may not be set when a resource name is provided]
5/26/2017 8:37:39 PME0526 12:37:39.270273    3124 reconciler.go:433] Could not construct volume information: MountVolume.NewMounter failed for volume "kubernetes.io/glusterfs/17533d60-40f3-11e7-a650-025501aae3f8-storage-volume" (spec.Name: "storage-volume") pod "17533d60-40f3-11e7-a650-025501aae3f8" (UID: "17533d60-40f3-11e7-a650-025501aae3f8") with: an empty namespace may not be set when a resource name is provided
5/26/2017 8:37:39 PME0526 12:37:39.270376    3124 glusterfs.go:122] glusterfs: failed to get endpoints devops-grafana-pv[an empty namespace may not be set when a resource name is provided]
5/26/2017 8:37:39 PME0526 12:37:39.270392    3124 reconciler.go:433] Could not construct volume information: MountVolume.NewMounter failed for volume "kubernetes.io/glusterfs/abed2f1d-420c-11e7-a650-025501aae3f8-devops-grafana-pv" (spec.Name: "devops-grafana-pv") pod "abed2f1d-420c-11e7-a650-025501aae3f8" (UID: "abed2f1d-420c-11e7-a650-025501aae3f8") with: an empty namespace may not be set when a resource name is provided
5/26/2017 8:37:40 PME0526 12:37:40.057305    3124 kubelet_volumes.go:110] Orphaned pod "17533d60-40f3-11e7-a650-025501aae3f8" found, but error <nil> occured during reading volume dir from disk
5/26/2017 8:37:42 PME0526 12:37:42.057529    3124 kubelet_volumes.go:110] Orphaned pod "17533d60-40f3-11e7-a650-025501aae3f8" found, but error <nil> occured during reading volume dir from disk
5/26/2017 8:37:44 PME0526 12:37:44.059675    3124 kubelet_volumes.go:110] Orphaned pod "17533d60-40f3-11e7-a650-025501aae3f8" found, but error <nil> occured during reading volume dir from disk
5/26/2017 8:37:46 PME0526 12:37:46.058979    3124 kubelet_volumes.go:110] Orphaned pod "17533d60-40f3-11e7-a650-025501aae3f8" found, but error <nil> occured during reading volume dir from disk
5/26/2017 8:37:48 PME0526 12:37:48.057180    3124 kubelet_volumes.go:110] Orphaned pod "17533d60-40f3-11e7-a650-025501aae3f8" found, but error <nil> occured during reading volume dir from disk
5/26/2017 8:37:50 PME0526 12:37:50.059245    3124 kubelet_volumes.go:110] Orphaned pod "17533d60-40f3-11e7-a650-025501aae3f8" found, but error <nil> occured during reading volume dir from disk
5/26/2017 8:37:52 PME0526 12:37:52.058785    3124 kubelet_volumes.go:110] Orphaned pod "17533d60-40f3-11e7-a650-025501aae3f8" found, but error <nil> occured during reading volume dir from disk
5/26/2017 8:37:54 PME0526 12:37:54.057093    3124 kubelet_volumes.go:110] Orphaned pod "17533d60-40f3-11e7-a650-025501aae3f8" found, but error <nil> occured during reading volume dir from disk
5/26/2017 8:37:56 PME0526 12:37:56.056936    3124 kubelet_volumes.go:110] Orphaned pod "17533d60-40f3-11e7-a650-0

**Comment by rahulinux** [comment]
Any update on this issue ?

**Comment by hiscal2015** [comment]
seems no one working on this...

**Comment by aga20** [comment]
Hello. 
As I see this is an old thread but I have a workaround for this. I want to know the root cause but in an another thread no one try to find/solve it. 
Before you stop the kubelet container check the ps axuf | grep gluster command output. As you can see there are some gluster client processes. This issue can happen because when you stop the kubelet container these processes stopped but the gluster volumes still mounted under the /var/lib/kubelet/pods/<ID>/volumes/kubernetes.io~glusterfs/<gfs-volname>. When the kubelet start and check the mounts from him pov the mounts are ok/everything is ok so let's start the pod. But inside the pod the volume's connection is lost because the gluster processes stopped and kubelet don't start them again. 
So before I start the kubelet I give unmount command for the mountpoints what I mentioned above. In this case the kubelet can start the processes again and mountpoints will work again.

**Comment by humblec** [comment]
Refer# https://github.com/kubernetes/kubernetes/pull/55796

**Comment by Jevi06** [comment]
> Hello.
> As I see this is an old thread but I have a workaround for this. I want to know the root cause but in an another thread no one try to find/solve it.
> Before you stop the kubelet container check the ps axuf | grep gluster command output. As you can see there are some gluster client processes. This issue can happen because when you stop the kubelet container these processes stopped but the gluster volumes still mounted under the /var/lib/kubelet/pods//volumes/kubernetes.io~glusterfs/. When the kubelet start and check the mounts from him pov the mounts are ok/everything is ok so let's start the pod. But inside the pod the volume's connection is lost because the gluster processes stopped and kubelet don't start them again.
> So before I start the kubelet I give unmount command for the mountpoints what I mentioned above. In this case the kubelet can start the processes again and mountpoints will work again.

Thanks for your explain,I want to consult you how to do the opertion ----'unmount for the mountponts' automatically ,is there a way to config it to pod manifest ?
