### ISSUE TITLE
Attach_detach_controller does not taking action.

### ISSUE THREAD

**Issue by james-poole** [kubernetes/kubernetes#46338]
Hello all,
We are running an openshift cluster with ceph rbd's mounted into running pods. When a node unexpectedly drops out of the cluster and doesn't return, rbd locks are left behind causing these pods to fail to deploy to any other node before manual intervention is taken to remove said locks. We found the attach_detach_controller kubernetes component and have activated it by adding the appropriate annotation to the nodes-config.yaml and restarting. I can see from the logs on the nodes we are testing on that it has been activated. Steps we followed to enable are here:
openshift/openshift-docs@da5ae70

#### Version
OS - CentOS 7
Kernel - 3.10.0-514.10.2.el7.x86_64
openshift v1.5.0
kubernetes v1.5.2+43a9be4
etcd 3.1.0

#### Steps To Reproduce

1)    Set up project, deployment configuration and ceph pvc. We pinned said test project to two nodes in our cluster using node-selector on the namespace.

2)    Apply settings above to the nodes the project is set to run on and the masters.

3)    Spin up pod, take out node by stopping and masking origin-node and docker services and restarting.

4)    Watch rbd locks on image and see that lock is not removed from image automatically.

#### Current Result

Pod gets stuck redeploying with errors in events advising unable to mount pod as there is a lock on the image. The following status in ceph for the image being tested:

blacklist - listed 0 entries
Watchers: none
Locks:
There is 1 exclusive lock on this image.
Locker ID Address
client.4442 kubelet_lock_magic_[redacted] [redacted]

#### Expected Result

The problem node blacklisted from io, rbd lock to be automatically removed after a few minutes when node does not return to the cluster and the pod spin up successfully.
Additional Information

According to the documentation indications are that the controller is active, from /var/log/messages on the active master for all nodes in the cluster:

May 23 09:51:45 master-[redacted] origin-master-controllers: I0523 09:51:45.661129 3143672 attach_detach_controller.go:540] processVolumesInUse for node "[redacted]"

On the nodes where the annotation has been activated:
May 22 16:36:27 node-[redacted] origin-node: I0522 16:36:27.139905 1629689 kubelet_node_status.go:227] Setting node annotation to enable volume controller attach/detach

**Comment by tuminoid** [comment]
We're hitting this too. Using k8s 1.6.4, RHEL 7.3, etcd 3.1.7.
