### ISSUE TITLE
Possible causes for NodeControllerEviction

### ISSUE THREAD

**Issue by carlosmkb** [kubernetes/kubernetes#46340]
**Kubernetes version** : v1.5.3

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04 LTS
- **Kernel** (e.g. `uname -a`): 4.4.0-72-generic
- **Install tools**: acs-engine used to deploy the cluster (1 master, 2 nodes)
- **Others**: calico used as network policy, custom Pod CIDR (10.11.0.0/16)

Sometime happens a NodeControllerEviciton either in master or nodes, marking for deletion all the pods on that machine.
I search for a cause in journalctl -u kubelet, kube-controller-manager, syslog, but I only find the NodeControllerEviction ocurring and not the cause of that.
I check too the Node Conditions and the "Last transition time" is the same that eviction time, but I checked all the machines and all have enough disk space ...
In all of ocurrences of NodeControllerEviction, the machine became ready an healthy again after approximately 10 minutes.

What are the possible causes for the NodeControllerEviciton or where I can check the reason for that?

Thanks in advance!

**Comment by ZongqiangZhang** [comment]
**Kubernetes version** : v1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: bare metal Intel Xeon
- **OS** (e.g. from /etc/os-release): CentOS 7.0
- **Kernel** (e.g. uname -a): 3.10.0-123.13.2.el7.x86_64
- **Install tools**: docker v1.12.6
- **Others**:

I hit the problem too after I replace /usr/bin/kubelet with a new binary file. The detailed process is:
```
  systemctl stop kubelet
  cp kubelet /usr/bin/kubelet
  systemctl restart kubelet
```
Then, I found some pods turn to ContainerCreating or CrashLoopBackOff status, and logs show  NodeControllerEviciton, Unknown device, UnmountVolume, etc.

**Comment by edevil** [comment]
This seems related to https://github.com/kubernetes/kubernetes/issues/43516. I think the Azure API sometimes does not respond, or takes a long time to do it, and all hell breaks loose. For example, here is a recent log:

```
I0529 16:26:44.095749       1 event.go:217] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"master-1-vm", UID:"f08a3d0e-d0e7-11e6-8def-000d3a27013b", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeNotReady' Node master-1-vm status is now: NodeNotReady
E0529 16:27:14.242314       1 nodecontroller.go:748] Error determining if node master-1-vm exists in cloud: compute.VirtualMachinesClient#Get: Failure sending request: StatusCode=0 -- Original Error: Get https://management.azure.com/subscriptions/.../resourceGroups/borgbrpx/providers/Microsoft.Compute/virtualMachines/master-1-vm?api-version=2016-03-30: dial tcp 13.81.110.74:443: i/o timeout
E0529 16:27:48.991516       1 nodecontroller.go:748] Error determining if node master-1-vm exists in cloud: compute.VirtualMachinesClient#Get: Failure sending request: StatusCode=0 -- Original Error: Get https://management.azure.com/subscriptions/.../resourceGroups/borgbrpx/providers/Microsoft.Compute/virtualMachines/master-1-vm?api-version=2016-03-30: dial tcp 13.81.110.74:443: i/o timeout
I0529 16:27:53.992210       1 event.go:217] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"master-1-vm", UID:"f08a3d0e-d0e7-11e6-8def-000d3a27013b", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'DeletingAllPods' Node master-1-vm event: Deleting all Pods from Node master-1-vm.
```

I've been trying to add extra logging to the Azure cloud provider, #45540, but no one has answered yet.

**Comment by rushabhnagda11** [comment]
Facing the exact same issue, better filing it against acs-engine?

**Comment by jdumars** [comment]
Closing as stale.  @carlosmkb please feel free to re-open if still relevant to > 1.8.x
