### ISSUE TITLE
Not all daemonset Pods getting updated with RollingUpdate

### ISSUE THREAD

**Issue by mikkeloscar** [kubernetes/kubernetes#46355]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): daemonset, update, updatedNumberScheduled

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3+coreos.0", GitCommit:"70bc0937018d89b0d529d428eed8c444d8e7729a", GitTreeState:"clean", BuildDate:"2017-05-11T18:15:57Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): 
- **Kernel** (e.g. `uname -a`):
- **Install tools**: https://github.com/zalando-incubator/kubernetes-on-aws
- **Others**:

**What happened**:

Only subset of pods of a daemonset gets updated when applying a new version.

status of the daemonset many hours after applying a new version.
```
status:
  currentNumberScheduled: 9
  desiredNumberScheduled: 9
  numberAvailable: 9
  numberMisscheduled: 0
  numberReady: 9
  observedGeneration: 20
  updatedNumberScheduled: 4
```
This is the manifest we applied: https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/skipper/daemonset.yaml

This was the change: https://github.com/zalando-incubator/kubernetes-on-aws/commit/9d4e44d1e81f420cdb0949c4a7186ef228256825

**What you expected to happen**:

Expected that all pods of a daemonset would be updated to the latest version.

**How to reproduce it** (as minimally and precisely as possible):

Not sure. Out of 25 clusters we currently see the issue in 14 of them.

**Anything else we need to know**:

Output from kubectl describe daemonset:

```
$ kubectl --namespace kube-system describe daemonset skipper-ingress
Name:		skipper-ingress
Selector:	application=skipper-ingress
Node-Selector:	<none>
Labels:		application=skipper-ingress
		component=ingress
		version=v0.9.37
Annotations:	kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"extensions/v1beta1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"application":"skipper-ingress","component":"ingress","ver...
Desired Number of Nodes Scheduled: 9
Current Number of Nodes Scheduled: 9
Number of Nodes Scheduled with Up-to-date Pods: 4
Number of Nodes Scheduled with Available Pods: 9
Number of Nodes Misscheduled: 0
Pods Status:	9 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:	application=skipper-ingress
		component=ingress
		daemonset.kubernetes.io/podTemplateHash=3334413878
		version=v0.9.37
  Annotations:	scheduler.alpha.kubernetes.io/critical-pod=
  Containers:
   skipper-ingress:
    Image:	registry.opensource.zalan.do/teapot/skipper:v0.9.37
    Port:	9999/TCP
    Args:
      skipper
      -application-log-level=DEBUG
      -kubernetes
      -kubernetes-in-cluster
      -address=:9999
      -proxy-preserve-host
      -serve-host-metrics
    Limits:
      cpu:	200m
      memory:	200Mi
    Requests:
      cpu:		25m
      memory:		25Mi
    Environment:	<none>
    Mounts:		<none>
  Volumes:		<none>
Events:			<none>
```

I tried to look in the controller-manager logs for any hints on what could be wrong, but I didn't really find anything useful, I'm also not completely sure what to look for. Any pointers would be helpful.

**Comment by mikkeloscar** [comment]
So it turns out we were still running the old [daemonupgrader](https://github.com/Mirantis/k8s-daemonupgradecontroller) in some clusters which was conflicting with the core daemon controller. After deleting the daemonupgrader and restarting the old daemonset pods it's no longer happening.

**Comment by lukaszo** [comment]
@mikkeloscar ah, thx for pointing this out. I will close the daemonupgrader project.
