### ISSUE TITLE
Kubelet incorrectly reports selfLinks of pods started from manifests

### ISSUE THREAD

**Issue by number101010** [kubernetes/kubernetes#46357]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

selflink
kubelet selflink
default selflink
manifest selflink

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
admin@node:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T10:00:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T09:42:05Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:  AWS
- **OS**: Debian GNU/Linux 8 (jessie) 
- **Kernel**: Linux ip-10-150-109-115 4.4.41-k8s #1 SMP Mon Jan 9 15:34:39 UTC 2017 x86_64 GNU/Linux
- **Install tools**:  kops 1.5.3
- **Others**:

**What happened**:
When running `curl http://localhost:10255/pods` the selfLink for pods started from manifests were incorrect.

Example:   `/api/v1/pods/namespaces/kube-scheduler/kube-system`

**What you expected to happen**:

To receive a correct selfLink:

Example:   `/api/v1/namespaces/kube-system/pods/kube-scheduler`

**How to reproduce it** (as minimally and precisely as possible):

I believe simply using a pod manifest to start a pod will cause this issue as kubelet seems to rely on defaults when starting pods from manifests.

**Anything else we need to know**:

I believe the below linked line needs to be corrected:

https://github.com/kubernetes/kubernetes/blob/abd92fab1e8c1b638178d58efab7a09509a053c7/pkg/kubelet/config/common.go#L96

**Comment by xiangpengzhao** [comment]
/assign

I reproduced it. Will fix. Thanks @number101010 for reporting!
