### ISSUE TITLE
Contributor Experience Demo Test Issue

### ISSUE THREAD

**Issue by XC-Test** [kubernetes/kubernetes#46359]
**IGNORE THIS ISSUE.  THIS IS FOR A 05/24 Community DEMO**

**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):  

Bugfix (don't file support issues here!)

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
lots of stuff
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG-REPORT

**Kubernetes version** (use `kubectl version`):  

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**: 

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by XC-Test** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by XC-Test** [comment]
Just testing this functionality for a ContribX demo tomorrow.  Ignore/unsub from this issue

**Comment by xiangpengzhao** [comment]
How about also showing commands contributors can use in their PRs?

**Comment by XC-Test** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by xiangpengzhao** [comment]
@kubernetes/sig-testing-misc
This is a test, sorry for bothering.

**Comment by xiangpengzhao** [comment]
It's ok to close for now :)
/close
