### ISSUE TITLE
kubectl drain should print progress when it is attempting evictions

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#46361]
The current experience around `kubectl drain` when the eviction is forbidden by a PDB is that it simply hangs and reports no status back to the user. We should improve this so that we at least print the operation we're trying to do, to give the user some idea of progress.

/cc @kubernetes/sig-cli-feature-requests

**Comment by xingzhou** [comment]
yes, I'd like to take a look at this for now

**Comment by suyogbarve** [comment]
@xingzhou I have sent #46612 can you please review.
