### ISSUE TITLE
Add `kubectl config merge` command

### ISSUE THREAD

**Issue by henriquetruta** [kubernetes/kubernetes#46381]
`gcloud`/GKE has an efficient way of getting credentials from somewhere by using the `get-credentials` command that automatically merges the content of a remote cluster in a local kubeconfig file. We want to have something similar in k8s. A first approach would be having two kubeconfig files locally and being able to merge the content of one into the other without needing to do manual copy/paste.
 
We could have a command that looks like:
 `kubectl config merge <source> <target>`
 
Where the `target` file defaults to `~/.kube/config` and `source` would be some kubeconfig file that the user wants to have its entries (users, contexts and clusters) copied to the `target` file.
 
If there is no name conflict, i.e., the entries in `source` don’t exist in `target`, the output is quite straightforward. However, if there is some conflict, we need to decide on how to approach. Do anything and inform the user? Rename them in target? Copy only those with no conflict? Have this options as parameters (`--ignore, --rename, --abort-if-conflict`, etc)
I suggest having for now, for the sake of simplicity doing anything and informing the user. The others can me made in follow-up issues

**Comment by henriquetruta** [comment]
@nikhiljindal @madhusudancs can you take a look?

**Comment by superbrothers** [comment]
Can `kubectl config view` meet your requirements?
```
# use multiple kubeconfig files at the same time and view merged config
$ KUBECONFIG=~/.kube/config:~/.kube/kubconfig2 kubectl config view
```
https://kubernetes.io/docs/user-guide/kubectl-cheatsheet/

**Comment by madhusudancs** [comment]
`kubectl config view` might not work as is as it redacts certificate data. `kubectl config view --flatten` might, but I have never tried that with multiple kubeconfigs. 

cc @kubernetes/sig-cli-feature-requests

**Comment by shiywang** [comment]
@madhusudancs @superbrothers 
`KUBECONFIG=~/.kube/config:~/config kubectl config view --flatten` works, but I think adding this `kubectl config merge` is also ok, I can implement this since I'm working on another `kubectl config` subcommand
cc @kubernetes/sig-cli-feature-requests

**Comment by madhusudancs** [comment]
@shiywang it is up to SIG-CLI to decide.

**Comment by shiywang** [comment]
@madhusudancs sure, we'll wait for @kubernetes/sig-cli-maintainers to decide.

**Comment by henriquetruta** [comment]
@shiywang thanks! I've already started to implement it here

**Comment by bgrant0607** [comment]
See also #9298, #10693, #20605, #30395

**Comment by epcim** [comment]
[**@superbrothers**](https://github.com/superbrothers) commented on [May 25, 2017, 7:27 AM GMT+2](https://github.com/kubernetes/kubernetes/issues/46381#issuecomment-303926031 "2017-05-25T05:27:10Z - Replied by Github Reply Comments"):
> Can `kubectl config view` meet your requirements?
> 
>     # use multiple kubeconfig files at the same time and view merged config
>     $ KUBECONFIG=~/.kube/config:~/.kube/kubconfig2 kubectl config view
> 
> [https://kubernetes.io/docs/user-guide/kubectl-cheatsheet/](https://kubernetes.io/docs/user-guide/kubectl-cheatsheet/)

works, except the fact your yaml config starts with `---` :-1:

**Comment by HighwayofLife** [comment]
@epcim 

```
KUBECONFIG=~/.kube/config:~/.kube/kubconfig2 kubectl config view --flatten > ~/.kube/config
```

Does not have a yaml config starting with `---`, however, it still works even when yaml starts with that separator.

**Comment by anthonydahanne** [comment]
> KUBECONFIG=~/.kube/config:~/.kube/kubconfig2 kubectl config view --flatten > ~/.kube/config

well, that almost worked for me, except that... only partial content was copied ! (writing while reading seemed to have messed up the final output !)
I had better luck with a temporary file : 

```KUBECONFIG=~/.kube/config:~/.kube/kubconfig2  kubectl config view --flatten > mergedkub && mv mergedkub ~/.kube/config```

**Comment by liggitt** [comment]
> There is a problem that KUBECONFIG does not understands special chars like ~ (home dir path) so use full path. for example:
> 
> KUBECONFIG=/home/serra/.kube/config:/home/serra/.kube/config.baremetal kubectl config view --flatten > /home/serra/.kube/config

Most shells expand that for you:

```
$ more ~/k1
apiVersion: v1
clusters:
- cluster:
    server: https://1.1.1.1
  name: cluster1
contexts:
- context:
    cluster: cluster1
    user: user1
  name: context1
current-context: context1
kind: Config
preferences: {}
users:
- name: user1

$ more ~/k2
apiVersion: v1
clusters:
- cluster:
    server: https://2.2.2.2
  name: cluster2
contexts:
- context:
    cluster: cluster2
    user: user2
  name: context2
current-context: context2
kind: Config
preferences: {}
users:
- name: user2

$ KUBECONFIG=~/k1:~/k2 kubectl config view
apiVersion: v1
clusters:
- cluster:
    server: https://1.1.1.1
  name: cluster1
- cluster:
    server: https://2.2.2.2
  name: cluster2
contexts:
- context:
    cluster: cluster1
    user: user1
  name: context1
- context:
    cluster: cluster2
    user: user2
  name: context2
current-context: context1
kind: Config
preferences: {}
users:
- name: user1
  user: {}
- name: user2
  user: {}
```

**Comment by MichaelSp** [comment]
My little bash script based on https://github.com/kubernetes/kubernetes/issues/46381#issuecomment-379860786
```bash
# ~/.bashrc

function kmerge() {
  KUBECONFIG=~/.kube/config:$1 kubectl config view --flatten > ~/.kube/mergedkub && mv ~/.kube/mergedkub ~/.kube/config
}
```

**Comment by drewwells** [comment]
`kubectl config merge` would be easier to remember. First class support would be nice even though the workaround is clever

**Comment by eroji** [comment]
This does not seem to work if you have the same user but different token for the user for different clusters. The `kubectl config view --flatten` will only keep the user and token for the first one it encounters, which defeats the purpose of trying to merge it in the first place.

**Comment by phillycheeze** [comment]
Can this be re-opened? The workaround is nice, but a built-in supported command would be way better.

**Comment by richstokes** [comment]
Running into the same issue as above: The kubectl config view --flatten will only keep the user and token for the first one it encounters, which defeats the purpose of trying to merge it in the first place.

This is really annoying since its best practice to use unique tokens, but this command is truncating them when trying to merge multiple accounts/contexts into one file.

**Comment by liggitt** [comment]
> The kubectl config view --flatten will only keep the user and token for the first one it encounters, which defeats the purpose of trying to merge it in the first place.

It keeps all uniquely named users/clusters. If you have user stanzas with the same name, keeping all of them would make the resulting file ambiguous.

**Comment by richstokes** [comment]
So how can you merge multiple files that have the same username but different tokens?

**Comment by liggitt** [comment]
> So how can you merge multiple files that have the same username but different tokens?

you cannot; those are effectively the same user stanza, and can only have a single bearer token

**Comment by richstokes** [comment]
So if you run multiple clusters you should use a different/unique username on each? Very unintuitive.

**Comment by liggitt** [comment]
If you want to merge them into a single kubeconfig, yes

**Comment by didil** [comment]
as a note for others who are looking for an option to do this, there is now a tool to achieve this, also available as a krew plugin https://github.com/corneliusweig/konfig
