### ISSUE TITLE
After upgrade to master branch from 1.6, test ([k8s.io] DNS should provide DNS for pods for Hostname and Subdomain Annotation) consistently fail 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#46393]
https://k8s-testgrid.appspot.com/1.6-master-upgrade#gke-cvm-gci-upgrade-master

```
[k8s.io] DNS should provide DNS for pods for Hostname and Subdomain Annotation 1m13s
go run hack/e2e.go -v -test --test_args='--ginkgo.focus=DNS\sshould\sprovide\sDNS\sfor\spods\sfor\sHostname\sand\sSubdomain\sAnnotation$'
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns.go:448
Expected error:
    <*errors.errorString | 0xc4203f3180>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns.go:230from junit_01.xml
```
@monopole 
@kubernetes/kubernetes-release-managers

**Comment by dchen1107** [comment]
cc/ @bowei

**Comment by MrHohn** [comment]
Apparently this test consistently fails because of #44137, which removes support for hostname/subdomain annotation and update e2e test to use the dedicated Hostname/Subdomain fields in PodSpec at the same time.

This testsuite upgrades master to a newer version (1.7) and runs the old e2e test (1.6), which still uses annotation. The updated master simply ignores the annotations so this test consistently fails.

Another test "DNS should provide DNS for the cluster" failed for the same reason.

**Comment by MrHohn** [comment]
Shouldn't we continue supporting beta annotations for one more release before removing it from codes?

cc @thockin

**Comment by thockin** [comment]
Those annotations pre-dated 1.6, but were not removed from tests.  We need
to do a better job of deprecating things like this.  If we have to revert
the annotations support, we can, but really 1.6 should not have been
testing them.

**Comment by MrHohn** [comment]
> Those annotations pre-dated 1.6, but were not removed from tests.  We need
to do a better job of deprecating things like this.  If we have to revert
the annotations support, we can, but really 1.6 should not have been
testing them.

Yeah we should have updated the e2e tests long time ago...Probably we could update the e2e tests in 1.6 branch to use PodSpec instead?

**Comment by thockin** [comment]
*I* think that is OK.

Dawn?

**Comment by MrHohn** [comment]
Sent #46452, it is a tiny change.

**Comment by dchen1107** [comment]
SGTM,  thanks!

**Comment by MrHohn** [comment]
/assign

As a reminder, #46452 needs re-LGTM :)

**Comment by MrHohn** [comment]
Test is passing after #46452 went in. Closing this issue.

/close
