### ISSUE TITLE
How to set the Pod field in v1.ObjectReference struct?

### ISSUE THREAD

**Issue by jianzhangbjz** [kubernetes/kubernetes#46402]
Hey Guys,

As the title, I need to set a Pod field on [scheduler.go](https://github.com/kubernetes/kubernetes/blob/release-1.6/plugin/pkg/scheduler/scheduler.go#L195) when binding pod to node.
I walk through the related code, as the following shows, and find the `FieldPath` of `ObjectReference`.
```go
		b := &v1.Binding{
			ObjectMeta: metav1.ObjectMeta{Namespace: pod.Namespace, Name: pod.Name},
			Target: v1.ObjectReference{
				Kind: "Node",
				Name: dest,
			},
		}
```
So, I add the `FieldPath` as the below, but it didn't take effect. Something else I missed? Or some docs?
```go
		b := &v1.Binding{
			ObjectMeta: metav1.ObjectMeta{Namespace: pod.Namespace, Name: pod.Name},
			Target: v1.ObjectReference{
				Kind: "Node",
				Name: dest,
                                FieldPath: "spec.PodSpec.xxx{xxx}"
			},
		}
```

**Comment by xiangpengzhao** [comment]
/sig scheduling

@davidopp @k82cn

**Comment by dixudx** [comment]
@jianzhangbjz You also need to modify [function in pkg/registry/core/pod/storage/storage.go#L128-L140](https://github.com/kubernetes/kubernetes/blob/release-1.6/pkg/registry/core/pod/storage/storage.go#L128-L140) accordingly. Currently only `Name`, `Target.Name` and `Annotations` are used. So you have to modify related functions to utilize your added attribute `Target.FieldPath`.

**Comment by jianzhangbjz** [comment]
@dixudx Great! :+1: Thanks a lot! I will have a try. :)

**Comment by k82cn** [comment]
@jianzhangbjz , would you share the case that setting a Pod field when binding?

**Comment by jianzhangbjz** [comment]
@k82cn Hmm... it's just our special requirements that assigning GPU devices, I think for average users, they needn't.

**Comment by k82cn** [comment]
ok, np; if we want to create a PR, suggest to share the case :).

**Comment by jianzhangbjz** [comment]
Yeah... but our case is a special scenario although I also would like to submit a PR.

**Comment by k82cn** [comment]
np, please share the case in PR. IMO, the PR reviewer will ask similar question, because this's a common components.
