### ISSUE TITLE
Need a way to deprecate kube feature gates

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#46404]
From #45857.

We were trying to remove _ExternalTrafficLocalOnly_ from kube feature gates as that feature is going to GA in v1.7 and we don't want users to disable it. Though removing that entry breaks the deprecation policy, which says flags have to have a deprecation window.

As what https://github.com/kubernetes/kubernetes/pull/45857#discussion_r117538180 suggests, we should have a proper way to deprecate feature gates. Open this issue for further discussion.

@kubernetes/sig-api-machinery-feature-requests 
cc @thockin @caesarxuchao

**Comment by timstclair** [comment]
I propose:

1. Update the feature gate `prerelease` (?) to `GA`
2. Remove references to the feature gate in the code (i.e. feature gate doesn't do anything)
3. If a launched (GA) feature is explicitly disabled, show a warning that it doesn't do anything, and that the feature will be removed in a future release
4. After N releases in GA, delete the feature gate (N = 2?)

Is this compatible with the flag deprecation policy?

**Comment by thockin** [comment]
We also should not show GA flags in the help text.  They need to be
announced in release notes.  6 months later they can be removed.  The rest
SGTM

**Comment by nikhita** [comment]
/remove-lifecycle stale

/cc @liggitt 
because iirc you had written some of the feature gate docs

**Comment by SergeyKanzhelev** [comment]
Just stumbled across, 

/remove-lifecycle frozen
/close

there is a way to lock the feature gate now introduced here: https://github.com/kubernetes/kubernetes/pull/72382
