### ISSUE TITLE
Add support to GPU e2e tests for Ubuntu

### ISSUE THREAD

**Issue by cmluciano** [kubernetes/kubernetes#46445]
Follow-up from #46311.

We need to install the nvidia-drivers for the test-infra Ubuntu machines. Ideally we would leverage a daemonset for this, but I've had trouble determining the supported methods for this use-case.

**Comment by cmluciano** [comment]
cc @vishh Can you link some of the Canonical folks for their feedback?

**Comment by mindprince** [comment]
Why was this closed?

**Comment by ScorpioCPH** [comment]
@cmluciano @vishh 

Hi, is this issue fixed?
I want to try GPU e2e tests on Ubuntu, but it seems there is no doc/code on github.
