### ISSUE TITLE
Github source code archives are not immutable (?)

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#46443]
We hit an interesting thing in kops, because of the use of `%h` in kubernetes source code here https://github.com/kubernetes/kubernetes/blob/master/pkg/version/base.go#L54, which we vendor:
https://github.com/kubernetes/kops/issues/2630#issuecomment-304044522

It appears that on a github release, the tarball is expanded dynamically.  At some stage git/github changed behaviour on the length of abbreviated shas (or maybe we hit a threshold on repo size in kops).

But presumably the same applies to kubernetes itself, and so the tar.gz files uploaded to github are not immutable, and will likely change in the future.

I don't know if this has any practical consequence for kubernetes/kubernetes - e.g. whether we are signing the kubernetes tar.gz release files.  brew doesn't like it, so it is possible that a kubectl build-from-source recipe broke, for example (?).

Proposed solutions we've come up with so far:

* Upload our own tarball
* Use %H and hope there are no other non-repeatable fields
* Document (likely in this issue) that the tarballs are not release artifacts

**Comment by cblecker** [comment]
For kubectl in homebrew, it's built off tag/revision as we then validate the generated binary matches the `gitCommit` (which is `%H`) on stable:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubernetes-cli.rb

We don't end up using the auto-generated source archive github creates for anything, I don't believe. All the release artifacts for k/k are in the [CHANGELOG](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#downloads-for-v164). This is an interesting find, however.

**Comment by ilovezfs** [comment]
@cblecker it did break `kubernetes-cli@1.3`, though.
