### ISSUE TITLE
[Federation] Requirement & Design of Federated ResourceQuota

### ISSUE THREAD

**Issue by weijinxu** [kubernetes/kubernetes#46464]
This issue is created to track the development of federated resource quota.
The design document was updated [here](https://docs.google.com/document/d/1F97GRKJyd0yRS4BNTl38304_DmCX1-O2zbWYRm0FUlE).

cc @kubernetes/sig-cluster-federation
@derekwaynecarr

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#16.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
