### ISSUE TITLE
ip-masq-agent does not set resources

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#46474]
We should know how much CPU and memory it needs. I am guessing that 0.01 CPU and 16 MB of RAM is probably enough?  Could leave it burstable...

@dnardo @mtaufen

**Comment by mtaufen** [comment]
I think that should be plenty. I'd still like to profile it over time, but I haven't had time to do that yet.

**Comment by thockin** [comment]
RSS appears to under 5 MB on my test machine.
