### ISSUE TITLE
It should be possible to inject Context into client-go API call

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#46503]
This is necessary for making our client library traceable (Ref #26507, see also #45962), and generally allowing passing context through client library is a good pattern.

@kubernetes/sig-api-machinery-feature-requests

**Comment by shiywang** [comment]
I would like to take a look if it's not in a hurry

**Comment by mbohlool** [comment]
Can you explain the use-case here? Why would you want to inject context and why you can't use generated/existing context?

**Comment by gmarek** [comment]
Sure - all modern tracing libraries for go use context to pass span context between binaries. Also ideologically context should represent one whole 'action' in the system.

**Comment by bhs** [comment]
Regardless of OpenTracing (though @gmarek is right on the money with his assertions along those lines), if it's not possible to pass the Go `Context` across process boundaries, it will also be impossible to do cross-process tracing without either (a) adding a second Context-like parameter (which seems a little crazy) or (b) adding context information to the application-level data (which also seems a little crazy).

I am far from a k8s implementation expert, but do `@bhs` me if there's a desire for additional, um, "context" (bad pun!) about the tracing angle.

PS: if there's a problem here, experience suggests it will be a lot less painful to solve it sooner rather than later.

**Comment by maleck13** [comment]
Would it also be fair to say that if you could pass in a context to the client calls, then if you were using the client in the scope of a web request, for instance, and that request was cancelled that cancellation could then be propagated allowing the client to stop any currently executing request?

**Comment by gmarek** [comment]
Yeah - pretty much all best practices I know of say to pass context in such cases.

@mbohlool - are you convinced?

**Comment by mbohlool** [comment]
Make sense to me but I feel better if @caesarxuchao take a look here and confirm this too.

One thing we should be careful about is we have a map from a request to context in our code (I don't remember where it was exactly but it shouldn't be hard to find). If we inject a context, we need to make sure we update the map somehow to reflect the change.

**Comment by smarterclayton** [comment]
client-go should receive context for Request via the RESTClient methods.  However, you're going to change the signature of all client methods, so it's likely to be fairly invasive.  Needs a proposal.

**Comment by caesarxuchao** [comment]
It makes sense to me, too. Looking forward to a proposal.

**Comment by maleck13** [comment]
Is anyone assigned to the proposal, If not I can look at taking it on (note it may take a little time). Is there any existing doc on creating a proposal?

**Comment by ggaaooppeenngg** [comment]
@maleck13  I guess [here](https://github.com/kubernetes/community/tree/master/contributors/design-proposals), but not well    documented.

**Comment by smarterclayton** [comment]
You'll want to try to articulate the "why", propose the specific interface
changes to the clients (or several variants if there are tradeoffs), and
show a few examples of how the context would be used in different cases.

**Comment by maleck13** [comment]
Ok great. @ggaaooppeenngg thanks for the link I will take a look at some of those for inspiration. Then I will put something together

**Comment by maleck13** [comment]
First pass here
https://github.com/kubernetes/community/pull/1166

**Comment by gmarek** [comment]
@tedsuo 

/remove-lifecycle stale
/lifecycle frozen
