### ISSUE TITLE
Would like `ClusterCIDR` to be fetchable by pods.

### ISSUE THREAD

**Issue by bboreham** [kubernetes/kubernetes#46508]
**FEATURE REQUEST**

Currently, `kube-proxy` and `kube-controller-manager` each have a command-line parameter `--cluster-cidr`, described as "CIDR range of pods in the cluster".  There is no API to fetch this parameter.

I work on a network add-on, Weave Net, which would benefit from being able to see this value.  Currently we have our own setting for the range of IP addresses to give to pods, and it is frustrating to receive issue reports caused by the values being out of sync.

Could we have `ClusterCIDR` as a top-level value on the cluster, which is then read by `kube-proxy` and `kube-controller-manager` and anyone else who wants it?

And/or supply it via the downward API.

**Comment by luxas** [comment]
Related I guess: https://github.com/kubernetes/community/pull/662

**Comment by MikeSpreitzer** [comment]
I work on BYOIP and explicit networks, so am no fan of having a configured `--cluster-cidr` --- I would rather see its usage decrease (eventually to zero) rather than increase.  What would it take for Weave Net to flourish in such a setting?

**Comment by bboreham** [comment]
@MikeSpreitzer it flourishes pretty well 🙂 But there are three independent settings at present, so let me take them one by one:

Weave Net has a CIDR: it allocates IP addresses to pods within that range, and it creates a route for that CIDR inside each pod (the whole Weave network is one hop at L3).  As far as I can think, BYOIP would replace the first but not the second - we need to know how to route to other pods.

kube-proxy has a `--cluster-cidr` option.  If it is not set, two things happen, that occasionally impact users:
1. kube-proxy issues a log message<sup>*</sup>.  Often, people who have a networking problem find this message, conclude this is the reason for their problem, and add the flag.  If they do not set it to a value which matches Weave Net's range, things get worse.
2. kube-proxy causes SNAT on all traffic from a pod implementing a service to a service VIP.  This in turn makes it impossible (within the Weave Net implementation) to write a NetworkPolicy specific to that source pod.

kube-controller-manager also has a `--cluster-cidr` argument; we do not care about this one. However it is commonly used in conjunction with `--allocate-node-cidrs`, which will set up routes which will cause random network disruption if you are using an overlay network.

 *: <sub>"clusterCIDR not specified, unable to distinguish between internal and external traffic"</sub>

**Comment by johnbelamaric** [comment]
See related https://github.com/kubernetes/kubernetes/issues/25533

**Comment by fasaxc** [comment]
Still an issue (and affects other networking plugins, such as Calico).

**Comment by errordeveloper** [comment]
@fasaxc I'd like to help with this, do you have any thoughts on how this could be solved?

**Comment by errordeveloper** [comment]
@thockin said in https://github.com/kubernetes/kubernetes/issues/25533#issuecomment-218801614:
> this is one of the things I want in the per-cluster configmap

I believe he is referring to ComponentConfig, and there has been significant progress on this, and I `kube-proxy` and `kube-controller-manager` have both implemented ComponentConfig.

https://github.com/kubernetes/kubernetes/blob/f072871b07a6d40c1c4a8f4a10b84116e5f43703/pkg/apis/componentconfig/types.go#L163-L363



https://github.com/kubernetes/kubernetes/blob/f072871b07a6d40c1c4a8f4a10b84116e5f43703/pkg/proxy/apis/kubeproxyconfig/types.go#L97-L153

More specifically:

https://github.com/kubernetes/kubernetes/blob/f072871b07a6d40c1c4a8f4a10b84116e5f43703/pkg/apis/componentconfig/types.go#L302-L303

https://github.com/kubernetes/kubernetes/blob/f072871b07a6d40c1c4a8f4a10b84116e5f43703/pkg/proxy/apis/kubeproxyconfig/types.go#L121-L124

**Comment by bboreham** [comment]
/remove-lifecycle rotten

this is still an issue for users of Weave Net.

**Comment by caseydavenport** [comment]
The ComponentConfig work looks promising and is probably enough to close this issue once it's beta/GA, though it's still somewhat awkward that this value would need to be configured in two locations (both for the controller manager and the kube-proxy).

**Comment by shufanhao** [comment]
Any update for it, I also want to know cluster cidr value from k8s api. So that do not need pass this value by env.

**Comment by granttigera** [comment]
bumping for an update if this is available via the api in alpha or beta currently.

**Comment by lorenzo-david** [comment]
Any updates on this one?

**Comment by generals-space** [comment]
I don't think they will make a new API for this. 

I have searched the output of `kubectl cluster-info dump` and found the `--cluster-cidr`(and `--service-cluster-ip-range`) field. 

Maybe we can just get the `controller-manager` or `apiserver` Pod resource in our pods, and find the `--cluster-cidr` and `--service-cluster-ip-range` in their `.spec.containers.command` block.

**Comment by lorenzo-david** [comment]
Thanks @generals-space for the response and the workaround.

I'm totally new to all these component, but I tried to make sense of the various resources I've read online. Here's my write-up after some research - thanks in advance for correcting it in case I'm getting it wrong!

If I understand @errordeveloper's [comment](https://github.com/kubernetes/kubernetes/issues/46508#issuecomment-365356111) correctly, it's currently possible to retrieve these information form the ComponentConfig API. 
ComponentConfig is the component that enables dynamic kubernetes system configuration and it's reachable through the Kubernetes API.

As per [today](https://github.com/kubernetes/enhancements/issues/784) it looks like `kube-proxy`'s ComponentConfig is still in v1alpha1. And I guess the same applies for the `kube-controller-manager`.

As per the [api-versioning](https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-versioning), alpha APIs are disabled by default and it's not advised for production deployments.

Therefore, if one wants to programmatically fetch the ClusterCIDR, one needs either to enable alpha API or to wait for the beta graduation of ComponentConfig API of `kube-proxy` and `kube-controller-manager`.

**Comment by jayunit100** [comment]
for folks reading this... yeah , so i dug into it and looks like  kube-proxy’s configmap actually stores the cluster cidr.  so…. thats the source of truth i guess (or parsing the output from the kcm

**Comment by caseydavenport** [comment]
> so i dug into it and looks like kube-proxy’s configmap actually stores the cluster cidr. so…. thats the source of truth i guess

I wouldn't rely on the kube-proxy's configmap as the source of truth in the generic case, although depending on your cluster it might work. A few downsides to that:

- It's not strictly required. Possible to run a cluster without this field set.
- Some platforms make this CIDR larger than the cidr used for pod IP addresses (it doesn't have the same semantic as the field on the controller manager)

The ultimate issue here in my opinion is that there is no real source of truth for the pod network CIDR. The source of truth is whoever wrote the config (e.g., the user who passed the pod-network-cidr arg to kubeadm, or equivalent for other tools).

**Comment by jayunit100** [comment]
ok, yeah so , let me make sure i get this right: 
- cluster-cidr isnt available through anything in the api
- service-cluster-ip-range isnt available either through anything in the api
- we dont have any plans to make these available in the api
- nobody is working on this actively 
- for now the best thing you can do is *make sure* that your kubeadm startup parameters etc are stored, somewhere, so you can reuse them as needed.

ill add this to the sig-network agenda for today, just so that we can have a doc page, at least, that explains this.

**Comment by dcbw** [comment]
I'd love to see what this value would actually be used for, outside of core Kube components and the network plugin itself.

**Comment by bboreham** [comment]
Hopefully it’s clear that my original request was for a network plugin (daemon).

**Comment by johnbelamaric** [comment]
For DNS, it would allow construction of the correct reverse zones in the cluster DNS without the possibility of accidental mismatch.

**Comment by errordeveloper** [comment]
In Cluster API and multiple installers this is one of the key input parameters, it would generally make sense to make it accessible at runtime, so that it can be checked uniformly in various environments. I am pretty sure there are service mesh use-cases also.

**Comment by thockin** [comment]
As Casey mentioned: this is hard because it's not guaranteed to exist.

- Some clusters don't use this at all (if their net config does not need it)
- Some clusters have multiple smaller CIDRs rather than a single large CIDR
- Some clusters can add/remove CIDRs at runtime

Now, it may be that your specific daemon won't work in some or all of those models.  We're lacking as proper IPAM API to describe them all.

**Comment by johnbelamaric** [comment]
Yes, that's the real ask (a proper IPAM API).

**Comment by errordeveloper** [comment]
I think it would good to also ask if this should be part of a broader network configuration API.

Aside from being able to find out what CIDRs are being used for pods and services, I think it would be very useful to be able to tell at least a name of the network provider. Of course, beyond that it would also be nice to tell if e.g. there are pods in `kube-system` or some other namespace that are responsible for the network. Happy to elaborate on use-cases, if there is no general objection to this, but it's something I've been thinking of for a while, it seems reasonable to bring for discussion, if we are to add some APIs.

**Comment by thockin** [comment]
No objections, per se, but even "which network provider" can vary from node
to node, as long as the transport is compatible.

**Comment by bboreham** [comment]
There is a KEP ["Removing Knowledge of pod cluster CIDR from iptables rules"](https://github.com/kubernetes/enhancements/blob/92b15c84dc9ece1e843896a441a1c453421f5038/keps/sig-network/20191104-iptables-no-cluster-cidr.md), implemented by #87748 et seq.
I think it can address part of this issue, in that kube-proxy can now do its job without the CIDR.
(Feels like it strengthens the need for "a broader network configuration API" though)

**Comment by aojea** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/57130

**Comment by thockin** [comment]
Yeah node.spec.podCIDR is another symptom of the lack of an IPAM API.

**Comment by bridgetkromhout** [comment]
Discussed at sig-network meeting on March 18, 2021.

**Comment by errordeveloper** [comment]
@bridgetkromhout I can see from the notes that it was discussed, but little info was logged... any chance someone could summarise the SIGs verdict, fi something was indeed decided?

**Comment by thockin** [comment]
No decision.

There's some work that feels like it could be adjacent - allowing
multi-CIDR for per-node IPAM, which pretty much demands an API to
expose the CIDRs available.  If we do that, this issue gets solved for
free EXCEPT...

in-cluster IPAM is *not* used everywhere, so an open question remains
- is this new API required (net-new for cloud providers) or optional,
and if optional, does that satisfy this request?

**Comment by bboreham** [comment]
An optional API would satisfy my original request, so long as, where available, it matches what `kube-proxy` and/or `kube-controller-manager` are using.

In my use-case Kubernetes shouldn't be doing IPAM.

**Comment by thockin** [comment]
OK.  Let's consider https://github.com/kubernetes/enhancements/issues/2593 the PoR fix to this.
