### ISSUE TITLE
The replica sets won't deleted after a deployment be deleted

### ISSUE THREAD

**Issue by gjw0317** [kubernetes/kubernetes#46504]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

ReplicaSet

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.7-beta.0", GitCommit:"fd8fac83034df346529c6e11aabceea2db48d663", GitTreeState:"clean", BuildDate:"2016-11-16T02:07:21Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.7-beta.0", GitCommit:"fd8fac83034df346529c6e11aabceea2db48d663", GitTreeState:"clean", BuildDate:"2016-11-16T02:02:36Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
```
# cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.3 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"
```
- **Kernel** (e.g. `uname -a`):
```# uname -a
Linux l-33-26 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```
- **Install tools**:
- **Others**:
I have already tried on both etcdctl 2.2.1 and 3.0.17
```
# etcdctl --version
etcdctl version 2.2.1
```

**What happened**:
The replica sets won't deleted after a deployment be deleted. The number is all zero.
```
# kubectl get rs
NAME                                 DESIRED   CURRENT   READY     AGE
dmo-m2-deploy-594970131              1         1         1         35m
dmo-update-etcd1-deploy-1825371083   0         0         0         33m
dmo-update-etcd2-deploy-1965028295   0         0         0         27m
```

**What you expected to happen**:
There is no replica sets remains after a deployment be deleted.

**How to reproduce it** (as minimally and precisely as possible):

Create a deployment, then delete it, it's better to do an upgrade operation.

**Anything else we need to know**:
After a deployment be deleted, the rs of old versions would be deleted first, then a new rs would be created.

**Comment by kargakis** [comment]
Should be fixed in 1.7 and also the latest minor version of 1.6 

cc: @caesarxuchao
