### ISSUE TITLE
Need validation for ObjectReferences

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#4651]
We could at least validate the name and namespace are structurally valid.

**Comment by ddysher** [comment]
Some related discussion here https://github.com/GoogleCloudPlatform/kubernetes/pull/4396#discussion_r24871235, originates from event namespace.  reference object is essentially not versioned and not converted to internal, so the validation is likely to suffer from version skew.

**Comment by gmarek** [comment]
Can someone provide an update on this issue? Do we want to add even simple validation for references in events, or did we dropped this idea? If we do, then I guess this is also blocked on decision if Nodes will be namespaced or not as in https://github.com/GoogleCloudPlatform/kubernetes/pull/4396#issuecomment-77305656.

@bgrant0607

**Comment by bgrant0607** [comment]
There is an apiVersion in ObjectReference. Is it not being used?

I'm more concerned about new uses of ObjectReference, such as in Binding, Endpoint, ReplicationController, etc. than in Event.

I don't think Node namespacing will happen soon, if ever.

**Comment by gmarek** [comment]
OK, so do we have any idea for nontrivial validation of ObjectReference, short of requiring namespace or not depending on the Kind? Is FieldPath design is done, or is it still pending?

**Comment by bgrant0607** [comment]
Demoting priority of this for now unless someone can point to a specific problem they've encountered due to lack of validation.

**Comment by gmarek** [comment]
@thockin - as you're the one who opened this issue: do you agree that it's not in v1.0 milestone?

**Comment by thockin** [comment]
Demote is fine, I just file them as I find them

**Comment by smarterclayton** [comment]
We may want validation in the future, but in practice object references are sparsely and loosely used (most common is in events).  Closing due to age and general lack of strong interest in doing anything more here in the near term.
