### ISSUE TITLE
Federated Ingress sets inconsistent Balancing Modes in GCE

### ISSUE THREAD

**Issue by dgpc** [kubernetes/kubernetes#46526]
**Environment**:
GKE

**Kubernetes version**:

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

$ kubefed version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:

Create an Ingress in a Federation `kubectl apply -f my-api-server.yaml --context=my-federation`.

Ingress Controller creates a Google Cloud HTTP(S) Load Balancer and backend service, with an instance group for each cluster in the Federation.

One instance group has `Balancing mode: Max RPS: 1`, the other instance group has `Balancing mode: Max CPU: 80%`.

**What you expected to happen**:

I expect both instance groups to have the same Balancing Mode.

If I try manually changing the second group to `Balancing mode: Max RPS 1`, after a while it gets changed back (presumably by the Ingress Controller).

**How to reproduce it** (as minimally and precisely as possible):

 - Create two GKE clusters.
 - Start a trivial NodePort service in each cluster.
 - Create an Ingress targeting that service via the federation control plane.

**Anything else we need to know**:

The comment in this code:
https://github.com/kubernetes/ingress/blob/master/controllers/gce/backends/backends.go#L68:L73
Seems to imply it's OK to set the Max RPS to 1, but from the HTTP(S) LB documentation, it sounds like traffic will be sent to the region nearest the frontend the user is connecting to that still has capacity, with Max RPS = 1, no region will still "have capacity", so it's unclear what the traffic behavior will be, will it round robin across all regions? Or still send all traffic to the closest region by latency? What about when the service is overloaded?

In the longer term:
It would be preferable to have the Ingress controller adopt a max-rate-per-instance from the Deployment (perhaps an annotation on the deployment) to determined the capacity of each instance group, similar to the way the Backend's Health Check is adopted from the ReadinessProbe. This would allow us to do actual capacity planning / load testing, and have traffic cascade to the next-nearest region before becoming overloaded.

**Comment by csbell** [comment]
Yes, what you are running into now is what was fixed (and backported into 1.6.4). It is chronicled here: https://github.com/kubernetes/ingress/pull/652

**Comment by dgpc** [comment]
@csbell thanks for that!

Any thoughts on my last paragraph re: being able to specify the MaxRatePerInstance as something other than `1`?

**Comment by dgpc** [comment]
Updated to 1.6.4 and confirmed both clusters get mode=rate, max_rps=1.

I'll open a separate issue about increasing max RPS.
