### ISSUE TITLE
cross e2e flake: constant 100000000000 overflows int

### ISSUE THREAD

**Issue by danwinship** [kubernetes/kubernetes#46520]
seen twice in a row in pull-kubernetes-cross:

I0526 09:09:56.008] test/e2e_node/summary_test.go:138: constant 100000000000 overflows int

This looks like #33761 but that was fixed long ago, and the file doesn't seem to have changed lately, so maybe this is a change to the cross compile environment?

**Comment by danwinship** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/39164/pull-kubernetes-cross/2710/

**Comment by danwinship** [comment]
This seems to be failing reliably

**Comment by cblecker** [comment]
I think https://github.com/kubernetes/kubernetes/pull/46521 is to fix this issue

**Comment by luxas** [comment]
Yes #46521 will fix this.

Thanks for reporting @danwinship!

**Comment by dchen1107** [comment]
PR #46521 to fix this issue was merged. Close the issue.
