### ISSUE TITLE
Cleanup the replaceKeys and setElementOrder code in strategic merge patch

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes#46543]
Comments in replaceKeys:
- https://github.com/kubernetes/kubernetes/pull/44597#discussion_r118761893
- https://github.com/kubernetes/kubernetes/pull/44597#discussion_r118767233
- https://github.com/kubernetes/kubernetes/pull/44597#pullrequestreview-40597721

Comments in setElementOrder:
https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/45980#-KlQrynxqa6fwPdcLbeh
https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/45980#-KlQsAHkxPOz_MIUFler
https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/45980#-KlQn7QltA-Wkwh6Q_aN

These comments are all about code style and refactoring.

**Comment by grodrigues3** [comment]
@mengqiy can you please add sig labels to issues you create?

/sig api-machinery

**Comment by caesarxuchao** [comment]
Can we close this issue @mengqiy

**Comment by mengqiy** [comment]
Probably not. Please leave it open. I will address it when I have some cycles.
