### ISSUE TITLE
Help with cryptic deployment problem

### ISSUE THREAD

**Issue by dlsniper** [kubernetes/kubernetes#46569]
**Kubernetes version** (use `kubectl version`):
1.6.2

**Environment**:
- **Cloud provider or hardware configuration**:
GKE
- **OS** (e.g. from /etc/os-release):
ContainerOS
- **Kernel** (e.g. `uname -a`):
🤷‍♂️ 
- **Install tools**:
🤷‍♂️ 
- **Others**:
🤷‍♂️ 

**What happened**:
I'm trying to deploy a project in GKE but I'm getting this error
```
Error from server (Forbidden): User "circleci@gophers-slack-bot.iam.gserviceaccount.com" cannot get deployments.extensions in the namespace "gopher-slack-bot".: "No policy matched.\nRequired \"container.deployments.get\" permission." (get deployments.extensions gopher-slack-bot)
```

Trying to run ` kubectl create sa circleci@gophers-slack-bot.iam.gserviceaccount.com ` results in:

```
The ServiceAccount "circleci@gophers-slack-bot.iam.gserviceaccount.com" is invalid: metadata.name: Invalid value: "circleci@gophers-slack-bot.iam.gserviceaccount.com": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**What you expected to happen**:
Everything to work

**How to reproduce it** (as minimally and precisely as possible):
https://github.com/gopheracademy/gopher

**Anything else we need to know**:
None of the documentation on the Internet explain how to deploy a project in GKE using k8s 1.6+

**Comment by xiangpengzhao** [comment]
@  is an invalid character in Name.

/kind support

**Comment by dlsniper** [comment]
@xiangpengzhao thanks for the reply. But then how can I make this work with GKE?
I've followed every tutorial that I could find, none of them explains how to create a role that allows a CI system to update a deployment in k8s. Am I missing something?

**Comment by xiangpengzhao** [comment]
I'm not sure whether there is a best practice on this or not. @liggit might help?

However, please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

**Comment by dlsniper** [comment]
@xiangpengzhao but the error is coming from k8s and I don't understand how to fix it and the documentation is not helpful either. Shouldn't this be kept open so that others that have similar issues see the problem and the team sees the issue and maybe add more documentation around roles and groups and an example of usage for k8s and gke / other deployments that have this solved?

**Comment by dlsniper** [comment]
Not to mention that this worked perfectly before K8s 1.6 upgrade, which means that the upgrade introduced the problem without a way for users to understand the changes done in 1.6 compared to previous versions in order to fix this.

**Comment by xiangpengzhao** [comment]
SGTM:)

**Comment by dlsniper** [comment]
I've posted the question on [stackoverflow](https://stackoverflow.com/questions/44221785/how-to-deploy-an-application-in-gke-from-a-public-ci-server) as advised. Thank you.

**Comment by kargakis** [comment]
Closing in favor of the stackoverflow question
