### ISSUE TITLE
cloud-controller-manager can't mount ebs in a pod when using dynamic provisioning 

### ISSUE THREAD

**Issue by jeremywu0127** [kubernetes/kubernetes#46564]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): NO

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): aws ebs pvc cloud-controller-manager

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** :1.6.3

**Environment**:
- **Cloud provider or hardware configuration**: aws
- **OS** :centos 7
- **Kernel**:3.10.0-514.16.1.el7.x86_64
- **Install tools**: k8s components from binary executable file
- **Others**: none

**What happened**:
I started the `kube-controller-manager` without cloud provider configuration,  and ran the `cloud-controller-manager` to take over, while when I create a service with `type: LoadBalancer`, the `cloud-controller-manager` cant create a elb and works fine, but when I try to create a pvc,  the pvc is always pending, and logs like
```
error finding provisioning plugin for claim default/ebs-pvc-volume: no volume plugin matched
```
then I stop the `cloud-controller-manager` and restart the `kube-controller-manager` with cloud provider configuration, then the pvc can create and the ebs attached into a pod automatically
**What you expected to happen**:
the `kube-controller-manager` start without any cloud provider configuration and the `cloud-controller-manager` take over the  responsibility and can handle all of the operation(e.g. elb、ebs...)  

**How to reproduce it** (as minimally and precisely as possible):
the `kube-controller-manager` started  without cloud provider configuration, then start the `cloud-controller-manager` , after that , create a pvc of ebs, then create a pod which try to mount the ebs 

**Anything else we need to know**:
none

**Comment by luxas** [comment]
ping @wlan0

**Comment by wlan0** [comment]
@jeremyeder @luxas The CCM will not host any volume specific controllers at this point. This is the reason ebs volumes are not getting attached/mounted.

We are waiting for CSI, and that will provide the plugin mechanisms for attaching/mounting volumes. In the interim, we decided not to add volume controllers because of its complexity, and because it adds unnecessary tech debt since the old controllers will be phased out in favor of new CSI controllers.

**Comment by luxas** [comment]
@wlan0 So in the meantime one can run a new (separate) controller-manager instance with `--cloud-provider aws --controllers attachdetach`?

**Comment by wlan0** [comment]
@luxas in the meantime, one can run a separate kube-controller-manager instance with `--cloud-provider aws --controllers attachdetach,persistentvolume`

**Comment by luxas** [comment]
@wlan0 Cool, could you document that at the kubernetes site?

**Comment by wlan0** [comment]
of course.

**Comment by jeremywu0127** [comment]
does the `ccm`  document update?  so the `CSI` controller will take over the responsibility to create/attach/deattach ebs?
