### ISSUE TITLE
github.com/opencontainers/runc/libcontainer/selinux moved to github.com/opencontainers/selinux/go-selinux

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#46586]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): NO

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): libcontainer/selinux, selinux

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): master

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
I tried building the latest code with some private tools.  I had a problem because `pkg/util/selinux/selinux_linux.go` imports `github.com/opencontainers/runc/libcontainer/selinux` but that does not exist any more.  See https://github.com/opencontainers/runc/pull/1365/files .  It appears the correct reference is now to github.com/opencontainers/selinux/go-selinux .

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by MikeSpreitzer** [comment]
It gets worse.  github.com/opencontainers/runc/libcontainer/label also has moved, to github.com/opencontainers/selinux/go-selinux/label

**Comment by jagosan** [comment]
/sig release 
? Kind of a stretch - open to other suggestions for sig routing...
