### ISSUE TITLE
Azure API problems cause cloud provider to fail and delete all pods

### ISSUE THREAD

**Issue by edevil** [kubernetes/kubernetes#46602]
**Is this a request for help?**:
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

azure cloudprovider api nodestatus

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T20:41:24Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2+coreos.0", GitCommit:"79fee581ce4a35b7791fdd92e0fc97e02ef1d5c0", GitTreeState:"clean", BuildDate:"2017-04-19T23:13:34Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): Container Linux by CoreOS 1353.7.0 (Ladybug)
- **Kernel** (e.g. `uname -a`): Linux master-1-vm 4.9.24-coreos 1 SMP Wed Apr 26 21:44:23 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz GenuineIntel GNU/Linux
- **Install tools**: own

**What happened**:

When the Azure API does not respond, lots of problems happen that affect the stability of an otherwise healthy Kubernetes cluster. Namely:

- The kubelet freezes while waiting for the Azure API to return and stops reporting the node status. Hence, the controller manager eventually deletes all pods of that node. Related issue and PR: #43516, #45540, #46340 
- The controller manager also reacts badly to errors from the API. Example:
```
I0529 16:26:44.095749       1 event.go:217] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"master-1-vm", UID:"f08a3d0e-d0e7-11e6-8def-000d3a27013b", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeNotReady' Node master-1-vm status is now: NodeNotReady
E0529 16:27:14.242314       1 nodecontroller.go:748] Error determining if node master-1-vm exists in cloud: compute.VirtualMachinesClient#Get: Failure sending request: StatusCode=0 -- Original Error: Get https://management.azure.com/subscriptions/.../resourceGroups/borgbrpx/providers/Microsoft.Compute/virtualMachines/master-1-vm?api-version=2016-03-30: dial tcp 13.81.110.74:443: i/o timeout
E0529 16:27:48.991516       1 nodecontroller.go:748] Error determining if node master-1-vm exists in cloud: compute.VirtualMachinesClient#Get: Failure sending request: StatusCode=0 -- Original Error: Get https://management.azure.com/subscriptions/.../resourceGroups/borgbrpx/providers/Microsoft.Compute/virtualMachines/master-1-vm?api-version=2016-03-30: dial tcp 13.81.110.74:443: i/o timeout
I0529 16:27:53.992210       1 event.go:217] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"master-1-vm", UID:"f08a3d0e-d0e7-11e6-8def-000d3a27013b", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'DeletingAllPods' Node master-1-vm event: Deleting all Pods from Node master-1-vm.
```

**What you expected to happen**:

Better timeouts and error handling in order not to break a cluster that is healthy.

**How to reproduce it** (as minimally and precisely as possible):

Block the traffic to the Azure API.

**Comment by rgomesf** [comment]
Hi.

We also have the same problem. Hoping for a fix for this. Our clusters area really unstable because of this :(

**Comment by edevil** [comment]
Error example:
```
Jul 31 10:48:37 node-1-vm kubelet-wrapper[2373]: W0731 10:48:37.440566    2373 kubelet_node_status.go:899] Failed to set some node status fields: failed to get node address from cloud provider: network.InterfacesClient#Get: Failure sending request: StatusCode=0 -- Original Error: Get https://management.azure.com/subscriptions/xxx/resourceGroups/kuberneteslabs/providers/Microsoft.Network/networkInterfaces/node-1-nic?api-version=2016-09-01: read tcp 10.0.3.11:40440->13.81.110.74:443: read: connection timed out
```

**Comment by jdumars** [comment]
Closing as stale.  @edevil if this is still relevant, please feel free to re-open and bring this to the SIG-Azure meeting for discussion.
