### ISSUE TITLE
Unable to call services through the nodeport from different nodes

### ISSUE THREAD

**Issue by yasassri** [kubernetes/kubernetes#46611]
**Is this a request for help?** No

**What keywords did you search in Kubernetes issues before filing this one?** NodePort

---

**Is this a BUG REPORT or FEATURE REQUEST?** BUG REPOR

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4+coreos.0", GitCommit:"8996efde382d88f0baef1f015ae801488fcad8c4", GitTreeState:"clean", BuildDate:"2017-05-19T21:11:20Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: OpenStack
- **OS** (e.g. from /etc/os-release): CoreOS
- **Kernel** (e.g. `uname -a`): Linux k8s-node-1.novalocal 4.9.24-coreos #1 SMP Wed Apr 26 21:44:23 UTC 2017 x86_64 Intel Xeon E312xx (Sandy Bridge) GenuineIntel GNU/Linux
- **Install tools**: Used Kargo to deploy, Terraform to provision and ansible to deploy
- **Others**: N/A

**What happened**: I have created two clusters one manually and one with Kargo artifacts, but in both clusters, I'm unable to connect to the nodePort from different Nodes. I can only connect to the nodePort only when I call the node which hosts the actual pod. 

**What you expected to happen**: Service should be reachable from any node through the nodePort.

**How to reproduce it** (as minimally and precisely as possible):  Deploy a cluster with Kargo artifacts. Deploy a service, and try to invoke it through the nodePort. 

**Anything else we need to know**: I can provide you any additional information if required. Kindly proide any commands I should execute to get the information since I'm new to this domain.

**Comment by yasassri** [comment]
This is possibly a DNS issue, I follwed  https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/ but could not get following to work
`kubectl exec -ti busybox -- nslookup kubernetes.default
`
I also did everything listed in the above link to debug the issue, but everything seems to work properly.

**Comment by yasassri** [comment]
Update: This happens when using calico. The issue is not there when using flannel.

**Comment by qiujian16** [comment]
@yasassri are you able to access pod by pod ip instead of service IP? are all your hosts in the same subnet? you may need to enable ipip in calico if the hosts are not in the same subnet.

**Comment by James-Dao** [comment]
I have the same issue when using k8s 1.6.0/1.6.6 with calico 2.1/2.2 .
