### ISSUE TITLE
Expose vendorCNIDirPrefix for cni plugins

### ISSUE THREAD

**Issue by abhinavdahiya** [kubernetes/kubernetes#46610]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): YES

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): cni vendor, vendordirprefix

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**What you expect to happen**:
CNI plugins are loaded with `""` vendorCNIDirPrefix (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/cni/cni.go#L91)

It would be great if it was exposed as a flag in kubelet.

Use Case:
hyperkube runs kubelet in a container and cni plugin's vendorDir needs to be mounted at boot. It would allow a custom path to be used for cni plugin's vendorDir ex. `/cni_plugins/opt/*/bin`.

/cc: @aaronlevy

**Comment by caseydavenport** [comment]
@abhinavdahiya for your use case, is there a reason you can't use `--cni-bin-dir=/cni_plugins/opt/cni/bin`?

Kubernetes only supports a single plugin, so I don't see what supporting individual vendor directories buys us.
