### ISSUE TITLE
kubectl --validate should use openapi

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#46622]
We've had openapi available for several releases.  We should switch `kubectl --validate` to use openapi instead of swagger and then retire swagger.  This allows the CLI to use the same information used to generate our clients (good for  @kubernetes/sig-cli-misc ) and reduces the maintenance load for the apiserver (good for @kubernetes/sig-api-machinery-misc)

**Comment by mbohlool** [comment]
dup https://github.com/kubernetes/kubernetes/issues/38637
