### ISSUE TITLE
Drop extensions.NetworkPolicy

### ISSUE THREAD

**Issue by danwinship** [kubernetes/kubernetes#46626]
After #39164 we now have two separate "internal" NetworkPolicy objects: extensions.NetworkPolicy, and networking.NetworkPolicy. Additionally, there are two separate packages under pkg/registry (pkg/registry/extensions/networkpolicy and pkg/registry/network/networkpolicy), two sets of kubectl printers/describers, and some handwritten conversions in pkg/apis/extensions/v1beta1 and pkg/apis/networking/v1.

It ought to be possible to get rid of this duplication, without changing the externally-visible API.

**Comment by thockin** [comment]
I removed the should-be-totally-unnecessary code for NP from
pkg/apis/extensions - leaving it in pkg/apis/extensions/v1beta1

It compiles.

I can POST a networking/v1 object, and it is stored in etcd as
extensions/v1beta1 - yay!

I can NOT POST an extensions/v1beta1 object.


```
$ cat /tmp/netpol.yaml
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: my-netpol
spec:
  podSelector: {}

$ kubectl create -f /tmp/netpol.yaml
error: error validating "/tmp/netpol.yaml": error validating data: couldn't
find type: v1beta1.NetworkPolicy; if you choose to ignore these errors,
turn validation off with --validate=false

$ kubectl create -f /tmp/netpol.yaml --validate=false
error: unable to recognize "/tmp/netpol.yaml": no matches for extensions/,
Kind=NetworkPolicy
```

Looking up that 2nd error, I get to staging/src/
k8s.io/apimachinery/pkg/api/meta/multirestmapper.go, where I see things
like:

```
return nil, &NoKindMatchError{PartialKind: gk.WithVersion("")}
```

...and I am lost

https://github.com/kubernetes/kubernetes/compare/master...thockin:pr-39164-plus?expand=1

At this point, I am stopping my investigation.  I don't have time to crawl
around.  If the worst problem we have is duplicated code, I guess I will
live.  It does feel like this should be possible.

**Comment by thockin** [comment]
Worst case is we do this after 1.7 cuts
