### ISSUE TITLE
Validating expected Event numbers for damoncontroller test

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#46629]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Now the [daemoncontrol test  do not include verify for daemonset event number](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemoncontroller_test.go#L274), we should add this check in the unit test.

such as 
```
func validateSyncDaemonSets(t *testing.T, fakePodControl *fakePodControl, expectedCreates, expectedDeletes int, expectedEvents int) {
```

/cc @wojtek-t

**Comment by kargakis** [comment]
@kubernetes/sig-apps-misc
