### ISSUE TITLE
Write e2e tests for the BootstrapSigner, TokenCleaner and BootstrapTokenAuthenticator

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#46634]
The title says it all. @jbeda knows what to do :smile:
Required for graduating [Bootstrap Tokens](https://github.com/kubernetes/community/pull/628) to beta in v1.8

**Comment by wanghaoran1988** [comment]
@jbeda Are you already start working on this? if not, I am volunteered to take this as a good start to understanding this feature.

**Comment by luxas** [comment]
@wanghaoran1988 That sounds absoultely awesome!!!
@jbeda has too much things going on at the moment, so this would be a perfect contribution :+1:

@wanghaoran1988 Let me know if you need any help.
Links to proposal: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/bootstrap-discovery.md
and https://github.com/kubernetes/community/pull/628

**Comment by wanghaoran1988** [comment]
@luxas Thanks for point me the proposal, will ping you if needed:)

**Comment by luxas** [comment]
This is fixed thanks to @wanghaoran1988 :tada:!
