### ISSUE TITLE
Resource quota support for GPU resource

### ISSUE THREAD

**Issue by gurvindersingh** [kubernetes/kubernetes#46639]
**Kubernetes version** (use `kubectl version`):
1.6.4 for both server and client

**Environment**:
- **Cloud provider or hardware configuration**: GKE and On premise
- **OS** (e.g. from /etc/os-release): Debian Jessie and Ubuntu 16.04
- **Kernel** (e.g. `uname -a`): 4.4.0-78 (ubuntu)
- **Install tools**: Managed service for GKE, Ansible for on premise

**What happened**:
When I define a resource quota limit with GPU resources in it to limit the number of GPU allocated to a namespace as  

```apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: test
spec:
  hard:
    requests.cpu: "12"
    requests.memory: 8Gi
    requests.alpha.kubernetes.io/nvidia-gpu: "1"
    limits.cpu: "12"
    limits.memory: 8Gi
    limits.alpha.kubernetes.io/nvidia-gpu: "1"
    configmaps: "100"
    services: "100"
    secrets: "100"
```

It creates the `quota` object without any warning. But when I try to run any deployment in that namespace, I get the error as
 `Warning   FailedCreate   replicaset-controller   Error creating: pods "tensorflow-3620546736-" is forbidden: status unknown for quota: quota`. 
This error goes away if I remove the GPU from resource quota. Also looking at the [docs](https://kubernetes.io/docs/concepts/policy/resource-quotas/) it seems GPU is not supported for quota. 

**What you expected to happen**:
I expect that in the above quota case, user will be able to run workload in `test` namespace with 1 GPU at max.

**How to reproduce it** (as minimally and precisely as possible):
Apply the above quota to a namespace and try to deploy any deployment with or without GPU, you will see the error.

**Comment by cmluciano** [comment]
@kubernetes/sig-apps-bugs @kubernetes/sig-node-bugs

**Comment by vishh** [comment]
Nvidia GPUs is currently in `alpha` phase. Quota, defaulting, etc. will be handled as part of `beta`. The API will change from alpha to beta and so quota objects will not be portable even if they were to support GPUs today.

**Comment by gurvindersingh** [comment]
@vishh I think its not only for GPU but in general quota resource should support [opaque resource](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#opaque-integer-resources-alpha-feature). As it is supported by accounting/scheduling in kubelet/scheduler. So it should be possible to limit the amount of those resource in the cluster per namespace.

**Comment by vishh** [comment]
@gurvindersingh We are planning on replacing the current opaque integer resource model with a more extensible one. That's one of the reasons why opaque integer resources are still in `alpha`. Expect a proposal on the new APIs with quota integration in the next couple of months.

**Comment by derekwaynecarr** [comment]
+1 to everything that @vishh stated.  i generally avoid quota on alpha resources at this time.

**Comment by gurvindersingh** [comment]
@vishh @derekwaynecarr That is understandable, I look forward to have the `beta`version of opaque resources with support for quota included. I assume that it will be target for 1.8

**Comment by gurvindersingh** [comment]
@vishh @cmluciano any update on this to get quota applied on GPU resources.

**Comment by cmluciano** [comment]
@gurvindersingh This will likely not land in a release until 1.9 (release date in December).

**Comment by vishh** [comment]
This may take longer than v1.9. I'd like to introduce an extensible resources pipeline before adding quota for extended resources. The Resource type `alpha.kubernetes.io/nvidia-gpu` will be removed in v1.9 in favor of a new resource type.

**Comment by gurvindersingh** [comment]
thanks guys for the update, wonder if there is any workaround for the near term if possible.

**Comment by vishh** [comment]
Run a custom quota controller? Initializers can be used to achieve that for
example.

**Comment by jianzhangbjz** [comment]
@cmluciano @vishh For present, I think we should validate the `alpha.kubernetes.io/nvidia-gpu` resource type. If the `ResourceQuota` contain it, create fail. Do you think so? If not, I will close this #51618

**Comment by vishh** [comment]
I don't think we want to add quota for an alpha resource.

**Comment by jianzhangbjz** [comment]
@vishh Sure, as the above description, 

>It creates the quota object without any warning.  

So, this PR will only stop the alpha resource from creating quota. Pop-up a warning, like this:
```command
root@slave2:/home/zhangjian/testK8s# kubectl create -f resourcequota.yaml 
The ResourceQuota "quota" is invalid: 
* spec.hard[limits.alpha.kubernetes.io/nvidia-gpu]: Invalid value: "limits.alpha.kubernetes.io/nvidia-gpu": must be a standard resource for quota
* spec.hard[requests.alpha.kubernetes.io/nvidia-gpu]: Invalid value: "requests.alpha.kubernetes.io/nvidia-gpu": must be a standard resource for quota
```
