### ISSUE TITLE
[Issue or Feature Request] Azure: don't using control plane to retrieve nodes status

### ISSUE THREAD

**Issue by rjtsdl** [kubernetes/kubernetes#46632]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):
No

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
Azure, AAD, nodestatus, API

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: 
Azure
- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
- **Kernel** (e.g. `uname -a`):
Linux k8s-master-C99BC558-0 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
ACS (Azure Container Service)
- **Others**:

**What happened**:
When AAD down, or not working in someway, an existing kuberenetes cluster provisioned through ACS (Azure Container Service) will failed to retrieve node status. This is because, Kuberentes implementation in azure to get node status is through Azure control plane or azure api. 

**What you expected to happen**:
The expected behavior is not to use Azure control plane or azure api to retrieve node status.

**How to reproduce it** (as minimally and precisely as possible):
Here is what repro’ed.
 
// Create a deployment with 4 replicas
azureuser@k8s-master-C99BC558-0:~$ kubectl run nginx --image=nginx --replicas=4
deployment "nginx" created

azureuser@k8s-master-C99BC558-0:~$ kubectl get po
NAME                    READY     STATUS              RESTARTS   AGE
nginx-701339712-642f6   0/1       ContainerCreating   0          5s
nginx-701339712-nk62g   0/1       ContainerCreating   0          5s
nginx-701339712-pkp2x   0/1       ContainerCreating   0          5s
nginx-701339712-z3qt4   0/1       ContainerCreating   0          5s

azureuser@k8s-master-C99BC558-0:~$ kubectl get no
NAME                    STATUS                     AGE
k8s-agent-c99bc558-0    Ready                      8m
k8s-agent-c99bc558-1    Ready                      8m
k8s-agent-c99bc558-2    Ready                      7m
k8s-master-c99bc558-0   Ready,SchedulingDisabled   8m
 
// delete the service principal, to simulate AAD failure
bash-4.3# az ad sp delete --id e451bcf5-41b7-4bbf-bd9e-f45225535c74
 
// After a while, I guess when the accessToken get expired, and failed to refresh due to service principal already removed.
azureuser@k8s-master-C99BC558-0:~$ while true; do kubectl get no; sleep 20; done
NAME                    STATUS                        AGE
k8s-agent-c99bc558-0    **NotReady**                      1h
k8s-agent-c99bc558-1    **NotReady**                      1h
k8s-agent-c99bc558-2    **NotReady**                      1h
k8s-master-c99bc558-0   **NotReady**,SchedulingDisabled   1h
 
// The pods still showing healthy.
azureuser@k8s-master-C99BC558-0:~$ kubectl get po
NAME                    READY     STATUS    RESTARTS   AGE
nginx-701339712-642f6   1/1       Running   0          1h
nginx-701339712-nk62g   1/1       Running   0          1h
nginx-701339712-pkp2x   1/1       Running   0          1h
nginx-701339712-z3qt4   1/1       Running   0          1h

**Anything else we need to know**:
I found another issue, which describes different problem. However, the request is the same, to block azure api when try to get node status. #46602 

Add more thought, I noticed Azure IMDS just get public previewed. It could be potentially served as data plane of Azure. May worth considering.
https://azure.microsoft.com/en-us/blog/announcing-public-preview-of-azure-instance-metadata-service/

**Comment by xiangpengzhao** [comment]
/area platform/azure
@justinsb

**Comment by justinsb** [comment]
/sig azure

(woo-hoo)

**Comment by xiangpengzhao** [comment]
Justin, seems like we don't have a label named `sig/azure`, so the bot will not respect `/sig azure`...

https://github.com/kubernetes/kubernetes/labels

**Comment by justinsb** [comment]
boo-hoo then!

I expect it's still getting spun up..  cc @colemickens (?)

**Comment by xiangpengzhao** [comment]
Yeah, but it just pretends that nothing happened :smile:

**Comment by jdumars** [comment]
Closing as stale based on work for #48243 - feel free to re-open if this work needs to be restarted.
