### ISSUE TITLE
Cut cAdvisor release for Kubernetes 1.7 release

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#46658]
To track the release ...

cc/ @kubernetes/sig-node-feature-requests

**Comment by dchen1107** [comment]
There is at least one feature I am expecting from the new release of cAdvisor: Overlay2 support.

**Comment by dashpole** [comment]
cAdvisor version bump #46816 went in yesterday, and all tests appear to be green.
/close
