### ISSUE TITLE
Default ServiceAccount and Token not created when a namespace is re-created.

### ISSUE THREAD

**Issue by matthewceroni** [kubernetes/kubernetes#46652]
**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z",GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4+coreos.0", GitCommit:"8996efde382d88f0baef1f015ae801488fcad8c4", GitTreeState:"clean", BuildDate:"2017-05-19T21:11:20Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:

- **Cloud provider or hardware configuration**:

Running in AWS US West Oregon

- **OS** (e.g. from /etc/os-release):

NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.7.0
VERSION_ID=1353.7.0
BUILD_ID=2017-04-26-2154
PRETTY_NAME="Container Linux by CoreOS 1353.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"

- **Kernel** (e.g. `uname -a`):

Linux ip-10-68-2-11.us-west-2.compute.internal 4.9.24-coreos #1 SMP Wed Apr 26 21:44:23 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux

**What happened**:

If I create a namespace (ie: my-namespace), a default service account and token is created (can be seen via kubectl get serviceaccount/secrets). If you delete the namespace and at a later date re-create the same namespace, the default token is not re-created.

Upon deploying PODs into this namespace they all stay in PENDING as it complains that it can not mount default-token-XXXXX (as it doesn't exist). 

**What you expected to happen**:

I would expect that when the namespace is created again, the default token would be re-generated.

**How to reproduce it** (as minimally and precisely as possible):

Fairly easy to re-produce. Simply create a namespace. Verify that the default token is present via kubectl get secrets.

Then delete that namespace (kubectl delete namespace NAME).

Re-create the namespace and verify that no default token is present via kubectl get serviceaccount/secrets. 

The system still seems to know the name of what the default-token should be (as it tries to mount that in PODs you try to run in that namespace) but it doesn't exist as far as get secrets is concerned.

**Comment by liggitt** [comment]
Can you check the controller manager logs? I'm unable to recreate this

**Comment by liggitt** [comment]
Also, what version of etcd are you running with? Versions <= 3.0.10 do not send deletion events with all the info required by kube 1.6.x. Minimum supported version of etcd3 is 3.0.12, I think

**Comment by liggitt** [comment]
See discussion in https://github.com/kubernetes/kubernetes/issues/45506

**Comment by matthewceroni** [comment]
I am running etcd 3.0.10.

**Comment by matthewceroni** [comment]
I also followed the discussion in the above referenced issue and was able to see the namespace termination event.

**Comment by matthewceroni** [comment]
Re-deployed using 1.6.2 but issue persists. Going to keep walking back the versions to see where the issue goes away. Will also try deploying using etcd2.

One issue I did possibly find is that I have HA for the API Servers. In the controller logs I saw a message about resetting Endpoint Kubernetes. Upon Googling I saw a reference to setting --apiserver-count for the API server. I have never set this. Not sure if it is required and could possibly be causing this issue.

**Comment by liggitt** [comment]
using a version of etcd < 3.0.11 with etcd3 mode will not work (again, see discussion in #45506):
* deletion events will not be delivered from the API properly
* if you look in the apiserver log you will see error messages like `storage/cacher.go:215: expected type *api.Namespace, but watch event object had type <nil>`
* things that depend on deletion events (like controllers that maintain local caches kept up to date by watch events) will get really really confused, and delete/recreate cases will not trigger creation handlers properly

**Comment by matthewceroni** [comment]
Sorry, my dyslexia kicked in. I read that as use a version <= 3.0.10. 

Ok, I will upgrade that and see where I stand. 

Thanks

**Comment by matthewceroni** [comment]
That appears to have fixed the issue. Upgraded to 3.1.8 and now when I create, delete and create a namespace the SA and default-token secret are re-created.

Much appreciated. Thanks
