### ISSUE TITLE
Segregating pod traffic and master traffic on the node

### ISSUE THREAD

**Issue by pravisankar** [kubernetes/kubernetes#46664]
We are trying to address a use case (real customer) where all the masters and nodes in the cluster has at least 2 network interfaces. We want all the pod traffic (pod <-> pod) to go through one network interface and management/master traffic (master <-> node) on other network interface.

Note: This is different from supporting multiple pod IP addresses https://github.com/kubernetes/kubernetes/issues/27398

Solution I was thinking: 
- Take desired node IP/interface for pod and master traffic as node configuration options.
- Pod traffic on desired interface is achieved by setting the node status address (`nodeIP` config).
- Node to master traffic on desired interface is achieved by adding an ip route rule on the node (done by the network plugin)
- Master to node traffic:

  Currently k8s master uses `NodeConnectionInfoGetter` (kubelet_client.go) to fetch node IP for communication. `NodeConnectionInfoGetter` only takes predefined `v1.NodeAddressType` as preferred node addresses.
  
  Approach-1: Using annotations
      
     - On the node, after kubelet creates the node object, add a new annotation on the node object that hints which node IP to be used by master.
     - Change `NodeConnectionInfoGetter.GetConnectionInfo()` to check this new annotation before looking at preferred node address types.
     
       Downside of this approach is that we need to maintain this patch external to k8s and need to resync during every k8s rebase.
       
  Approach-2: Hacky solution
  
     - Use `v1.NodeInternalIP` node address type for pod traffic and `v1.NodeLegacyHostIP` for master to node traffic.
     
       This is fragile as these address types are intended for other use cases.
       
  Approach-3: Add new node address type in k8s if feasible
  
     - This gives first class support but not sure if sig-net community thinks this use case is generic enough or not.

What do you think? Any feedback/ideas are appreciated.

**Comment by pravisankar** [comment]
cc: @kubernetes/sig-network

**Comment by pravisankar** [comment]
cc: @knobunc @dcbw @danwinship @rajatchopra

**Comment by danwinship** [comment]
> cc: @kubernetes/sig-network

It's @kubernetes/sig-network-misc now.

It seems like since pod-to-pod traffic is something the network plugin does (possibly via black magic for all kubernetes knows), and master-to-node traffic is something that actually happens in core, then that means master-to-node is the more "primitive" use case and so that's what should be associated with the `NodeInternalIP` address. (And it would be the "pod-to-pod traffic" IP that would need something new defined for it.)

> Approach-3: Add new node address type in k8s if feasible
> 
> - This gives first class support but not sure if sig-net community thinks this use case is generic enough or not.

That makes the most sense to me, but yeah, maybe it's not generic enough. OTOH, it's not like NodeAddressTypes are a limited resource, and the existing internal-vs-external split is already something which is specific to certain types of clusters.

**Comment by diogo-reis** [comment]
I also have the same need in a bare-metal environment, put Pod traffic on one network and traffic management (API) on another network. Anyone have any idea how I can do this on 2 separate networks?

**Comment by liggitt** [comment]
if we want to specify a separate address specifically for pod traffic, I'd expect a new address type, not annotations or overloading existing types

**Comment by dcbw** [comment]
@liggitt one problem with a new node address type is that it may leak to the API something that the API shouldn't necessarily have knowledge of, or something things watching the API can't do anything about.

For example, kubelet grabs the node IP from node.Status.Addresses and shoves that into Pod.Status.HostIP.  If the pod's data plane is on a different network and the node also has a different IP address on that pod data plane network, the API is now wrong.

But even if the API was able to get the right address and put that into HostIP, there's no guarantee that anything that consumes the API and reads Pod.Status.HostIP has the capability to access that data plane network.

**Comment by pravisankar** [comment]
@dcbw @liggitt 
I agree that adding new node address type for data plane/pod network may break other components which are not aware of this API change. For example, plugins like scheduler may want to look at current number of pods on a particular node by fetching all the pods and then applying the filter pod.Status.HostIP == node.Status.Addresses[0].Address. This could be wrong if scheduler is not aware of new node address type or pod.Status.HostIP is overwritten after pod creation to achieve data plane segregation.

What about having new node address type for control plane (master <-> node traffic) ?

Currently master uses kubelet client to connect to node. Kubelet client picks node address from configured PreferredAddressTypes (list of supported node address types). If we allow users to optionally use new control plane node address type as the first address in kubelet client's PreferredAddressTypes, then this enables master to connect to node on an interface other than node's data plane interface.

**Comment by danwinship** [comment]
> For example, kubelet grabs the node IP from node.Status.Addresses and shoves that into Pod.Status.HostIP. If the pod's data plane is on a different network and the node also has a different IP address on that pod data plane network, the API is now wrong.

I can't tell if you're saying "the kubelet might mistakenly assign the node's control plane IP to HostIP and that would be wrong" or "the kubelet might mistakenly assign the node's dataplane IP to HostIP and that would be wrong", but if we define a new node address type, we can also just clarify that the kubelet is/is not supposed to use that type for PodStatus.HostIP.

**Comment by m1093782566** [comment]
There is a survey related to this issue, check https://goo.gl/forms/xyfDoX62mPh0NCDG2

**Comment by danwinship** [comment]
@m1093782566 I think you added that comment to the wrong bug?
