### ISSUE TITLE
Aggregator should work with Dialer/SSHTunneler

### ISSUE THREAD

**Issue by cheftako** [kubernetes/kubernetes#46679]
**Kubernetes version** (use `kubectl version`): 1.7

**Environment**:
- **Cloud provider or hardware configuration**: GKE

Aggregator should function with the Dialer/SSHTunneler code. This would allow it to function in an environment such as GKE where there is a firewall between the master cluster and the user cluster. To do this the master needs to connect to the user-apiserver over the appropriate dialer which uses the configured SSH tunnel.

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by cheftako** [comment]
#46680
