### ISSUE TITLE
Cluster fails to properly start due to CPU limit impacting dns controller

### ISSUE THREAD

**Issue by cesartl** [kubernetes/kubernetes#46693]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

dns controller cpu limit

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1"
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2"
```

**Environment**:
- **Cloud provider or hardware configuration**: `AWS`
- **OS** (e.g. from /etc/os-release): `Debian GNU/Linux`
- **Kernel** (e.g. `uname -a`): `Linux ip-172-20-62-232 4.4.41-k8s #1 SMP Mon Jan 9 15:34:39 UTC 2017 x86_64 GNU/Linux`
- **Install tools**: `kops`
- **Others**:
Master and slaves are `t2.medium` instances

**What happened**:
We have a k8s cluster running on AWS, we have 3 slaves and one master. At night we turn off all the instances and they get started in the morning. Because the IP addresses (public and private) of the master do changes, the dns controller needs to update them in `Route 53`.

Sometimes dns controller fails to start, which means the entry in `Route 53` do not get updated and the the slave instances fail to register themselves. After investigation it turns out that the dns controller pod fails to start due to cpu restrictions. On the master there were too many pods running and there was no space left  for the dns controller.

Would there be a way to make sure dns controller always run on the master node? Or do I need a bigger instance for the master node?

**What you expected to happen**:
Dns controller should always run so that the slave nodes can always register themselves to the master node

**How to reproduce it** (as minimally and precisely as possible):
I don't know, this doesn't happen every time.

**Anything else we need to know**:

**Comment by gyliu513** [comment]
@cesartl two options for this:

1) Remove cpu and memory limit from your deployment/pod YAML template.

2) Use `nodeSelector`, you can add a tag on master nodes such as `role=master`, then you can use `nodeSelector` in Pod/Deployment YAML template to specify running the dns server on nodes with label `role=master`. You can refer to https://kubernetes.io/docs/concepts/configuration/assign-pod-node/ to get more detail.

**Comment by cesartl** [comment]
Hi @gyliu513,

sure these would work.

Shouldn't it work out of the box though? The DNS controller is not a pod I created, but comes installed with `kops`.

**Comment by gyliu513** [comment]
@cesartl which option are you using? 1) or 2)? I think that the `kops` may need some update.

@swarnap it seems not a network issue but kops deployment YAML template issue ;-)

**Comment by cesartl** [comment]
@gyliu513 

The `dns-controller` already has a node selector:

```
nodeSelector:
        kubernetes.io/role: master
```

I did 1) to remove the restriction on the `dns-controller`

**Comment by gyliu513** [comment]
OK, then I think you may either file an issue in `kops` project or move this issue to `kops` project to fix this issue, @cesartl

**Comment by cesartl** [comment]
yes that makes sense. How can I move this issue into a different project?

**Comment by gyliu513** [comment]
Issue moved to [kubernetes/kops #2667](https://github.com/kubernetes/kops/issues/2667) via [**ZenHub**](https://www.zenhub.com/)

**Comment by gyliu513** [comment]
I moved it for you, you may want to have [Zenhub](https://www.zenhub.com/) installed as a plugin for Github, just have a try ;-)

**Comment by cesartl** [comment]
Thanks @gyliu513. should we close this issue if we have another one open in kops?

**Comment by gyliu513** [comment]
yes, just close this directly ;-) @cesartl
