### ISSUE TITLE
No nodes resources in local cluster.

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#46691]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug

**Kubernetes version** (use `kubectl version`):
```
[root@ib15b13 kubernetes]# kc version
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.4.835+77a8c258391f30", GitCommit:"77a8c258391f30bb1d99c8eef0aba79218eaa445", GitTreeState:"clean", BuildDate:"2017-05-31T07:16:40Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.4.835+77a8c258391f30", GitCommit:"77a8c258391f30bb1d99c8eef0aba79218eaa445", GitTreeState:"clean", BuildDate:"2017-05-31T07:16:40Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): RHE 7.2
- **Kernel** (e.g. `uname -a`): `Linux ib15b13.eng.platformlab.ibm.com 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux`

**What happened**:
The node resource is empty when start local cluster by `./hack/local-up-cluster.sh`.

**What you expected to happen**:
There's one node in this local cluster.

**How to reproduce it** (as minimally and precisely as possible):

```
./hack/local-up-cluster.sh
kubectl get nodes
```

**Comment by k82cn** [comment]
Just check the script/code, it seems kubelet will not register until dynamic config is there (`local-up-cluster.sh` enabled all alpha features by default).

**Comment by wanghaoran1988** [comment]
I met same problem

**Comment by wanghaoran1988** [comment]
@k82cn What do you mean "dynamic config" ?

**Comment by k82cn** [comment]
I think there's a PR that make kubelet can update configuration dynamically, similar to what we had in scheduler. But did not find PR :(. I'm checking the code.

**Comment by k82cn** [comment]
Should be this one: #29459

/cc @mtaufen 
/sig node

**Comment by mtaufen** [comment]
@k82cn that shouldn't be the case. As long as you can get a client and a nodeName you should be able to register. What specific error are you seeing that suggests it's dynamic config?

Also why does local-up-cluster enable all alpha features by default? That seems wrong to me.

**Comment by wanghaoran1988** [comment]
Not sure why, but it really does:
`FEATURE_GATES=${FEATURE_GATES:-"AllAlpha=true"}`

**Comment by wanghaoran1988** [comment]
@k82cn @mtaufen I think this should be caused by https://github.com/kubernetes/kubernetes/pull/45059

/cc @liggitt @jcbsmpsn

**Comment by k82cn** [comment]
@mtaufen , sorry for the disturbing :).

Regarding all alpha features, I prefer to enable is by default:  local-up-cluster is a kind of test environment for developer, enabling all alpha features maybe helpful to catch up potential feature interactions.

**Comment by liggitt** [comment]
I would not expect all alpha features on by default in local up cluster

**Comment by mtaufen** [comment]
Neither would I. Developers, by default, shouldn't have to wonder if bugs are their fault or if they come from unstable alpha components. Users, by default, shouldn't have to deal with unstable alpha features either.

**Comment by k82cn** [comment]
@liggitt / @mtaufen , got that; alpha components is unstable, do NOT cover everything for it.

**Comment by shiywang** [comment]
met same problem
