### ISSUE TITLE
log symlink not updated after "docker rm"

### ISSUE THREAD

**Issue by mryan43** [kubernetes/kubernetes#46692]
**Is this a request for help?** : no

**What keywords did you search in Kubernetes issues before filing this one?** :
`docker rm log symlink`
`log symlink`
`file exists: "Start Container Failed"`

---

**Is this a BUG REPORT or FEATURE REQUEST?** : BUG REPORT

**Kubernetes version** 
v1.6.3

**Environment**:
- **Cloud provider or hardware configuration**: Bare metal
- **OS** : Ubuntu 14.04
- **Kernel** : 4.2.0-42-generic
- **Others**: Docker 17.05.0-ce

**What happened**:
When deleting kubelet managed containers on a docker host (using `docker rm -f`), kubelet fails to sync the pod with the following error : 
```
pod_workers.go:182] Error syncing pod 1456e04c-45d5-11e7-9e8f-8efbac9a033c ("sq-ci-index-821397182-w6l5m_default(1456e04c-45d5-11e7-9e8f-8efbac9a033c)"), skipping: failed to "StartContainer" for "sq-ci-index" with rpc error: code = 2 
desc = failed to create symbolic link "/var/log/pods/1456e04c-45d5-11e7-9e8f-8efbac9a033c/sq-ci-index_0.log" to the container log file "/var/lib/docker/containers/c54782580a41d3223148f9a88612cf490065e0c474e9aa87927e810ebda41e63/c54782580a41d3223148f9a88612cf490065e0c474e9aa87927e810ebda41e63-json.log" for container "c54782580a41d3223148f9a88612cf490065e0c474e9aa87927e810ebda41e63": 
symlink /var/lib/docker/containers/c54782580a41d3223148f9a88612cf490065e0c474e9aa87927e810ebda41e63/c54782580a41d3223148f9a88612cf490065e0c474e9aa87927e810ebda41e63-json.log /var/log/pods/1456e04c-45d5-11e7-9e8f-8efbac9a033c/sq-ci-index_0.log: file exists: "Start Container Failed"
```
The symlink in /var/log/pods is broken and `kubectl logs` returns 
```
failed to open log file "/var/log/pods/1456e04c-45d5-11e7-9e8f-8efbac9a033c/sq-ci-index_0.log": open /var/log/pods/1456e04c-45d5-11e7-9e8f-8efbac9a033c/sq-ci-index_0.log: no such file or directory
```
Despte the `Start Container Failed` error, the container is properly started and everything works fine except for the kube log features.

**What you expected to happen**:
The symlink should be updated to point to the newly created container. And there should be no error in kubectl logs.

**How to reproduce it** (as minimally and precisely as possible):
From a minion with running kubelet-managed docker containers, run `docker ps -aq | xargs docker rm -f`. Try to get the logs of a pod running on this docker host with `kubectl logs`

**Comment by mryan43** [comment]
https://github.com/kubernetes/kubernetes/blob/20ec8912d096e6cf0daabb3268dc8e73af743ebf/pkg/kubelet/dockershim/docker_container.go#L230

I'm guessing the file at "path" should be deleted if it exists before attempting the ds.os.Symlink(realPath, path).

**Comment by yujuhong** [comment]
> When deleting kubelet managed containers on a docker host (using docker rm -f), kubelet fails to sync the pod with the following error :

Deleting kubelet-managed containers is not encouraged because kubelet (still) relies on the information provided by them. Why do you want to remove them manually?

**Comment by mryan43** [comment]
My cluster is used mostly for CI, that means Jenkins masters and fungible slaves.

I'm sharing the docker hosts with my cluster users (not secure at all I know... but it's just too practical to let CI builds use docker that way...)

So I have a nightly cleanup script that deletes all containers on my docker hosts to cleanup any eventual container leaked by build jobs. This also helps us reduce the impacts of Jenkins masters memory leaks issues with groovy pipelines.

I've now changed this script to only delete pods that do not have a k8s pod ID label, so I'm good for now.., However I still think kubelet's behavior is not adapted as this situation may happen for other reasons.

**Comment by ukn** [comment]
I face the same issue in the following scenario:

A node running pods is rebooted and marked as _NotReady_.
Once it's up and _Ready_ all pods start successfully but have log symlinks broken due to already existing link to an old container.

**Comment by dhawal55** [comment]
@ukn I'm running into the same issue. Very annoying. There is a similar issue: https://github.com/kubernetes/kubernetes/issues/45911 but doesn't look like anyone is working on it yet.
