### ISSUE TITLE
Accessible client for CustomResourceDefinitions (TPR successor)

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#46702]
With 1.7 we have the apiextensions apiserver integrated into kube-apiserver and CustomRresourceDefinitions are the official successor of ThirdPartyResources. To allow people to use them, we have to offer consumable api types and a consumable client.

**Problem:** right now `k8s.io/kube-apiextensions-server` only lives in staging. We do not sync it into its own repo on Github. People have to vendor the whole kube to get access to it.

Possible solutions:

1. we add `k8s.io/kube-apiextensions-server` to the sync bot and make that the package to import for thirdparty users
2. or we move the CRD types into `k8s.io/api` after this change is finished after the 1.7 freeze and then create an authorative client in client-go.

As a direct follow-up I would like to see a ported ThirdPartyResource->CustomResourceDefinition example in client-go for 1.7. Option (1) makes this impossible without cyclic repo imports (not package imports! technically on the Go level it's not an issue). With (1) we then should better get rid of the TPR example in client-go and only put a pointer README.md telling that the example lives in `k8s.io/kube-apiextensions-server` now. For those reasons, I think (2) is the better way. At the end, `k8s.io/kube-apiextensions-server` is only an implementation detail. For the user CRDs are offered by the kube-apiserver.

xref: https://github.com/kubernetes/features/issues/95

TODO:
- [x] get https://github.com/kubernetes/kubernetes/pull/46775 merge to rename to k8s.io/apiextensions-apiserver
- [x] add k8s.io/apiextensions-apiserver to the repo sync bot https://github.com/kubernetes/test-infra/pull/2978
- [x] create k8s.io/apiextensions-apiserver
- [x] add CRD client-go example: https://github.com/kubernetes/kubernetes/pull/47050
- [x] add k8s.io/apiextensions-apiserver to k8s.io golang metadata https://github.com/kubernetes/k8s.io/pull/61

**Comment by sttts** [comment]
Note: for api aggregation the situation is similar, but less urgent because probably not many want to programmatically create APIServices.

**Comment by deads2k** [comment]
> we add k8s.io/kube-apiextensions-server to the sync bot and make that the package to import for thirdparty users

We should do this.



> or we move the CRD types into k8s.io/api after this change is finished after the 1.7 freeze and then create an authorative client in client-go.

We should not do this.  We've long said that clients should be buildable without access to the original types and that a client could include whatever API types it wants.  Now its time to prove it.  We want a client that spans groups and repos.

**Comment by caesarxuchao** [comment]
> clients should be buildable without access to the original types 

Does this mean client not importing the types? How can this work?

**Comment by deads2k** [comment]
> Does this mean client not importing the types? How can this work?

To be honest, I'm not certain, but I've heard the pitch many times: "build your own client based on the openapi spec" and it's what we expect every other language to do.

**Comment by caesarxuchao** [comment]
I don't think we should leave CRD out of k8s.io/api just to prove client could be generated across repos. I think it depends on if CRD is regarded as a core API type.

**Comment by deads2k** [comment]
> I don't think we should leave CRD out of k8s.io/api just to prove client could be generated across repos. I think it depends on if CRD is regarded as a core API type.

It's not inaccessible at the moment, it just lives in a different repo that can be vendored separately.  I'd really hate to see "no special cases", become "special cases because it was expedient".

The two client libraries can coexist and that will actually be the case for any other client library that gets created today.

**Comment by caesarxuchao** [comment]
It looks like kube-apiextensions-server is an end user apiserver that serves CRD? If that's the case, i agree with @deads2k that CRD should live in this repo.

**Comment by sttts** [comment]
> kube-apiextensions-server is an end user apiserver that serves CRD

Yes, it is. It happens to be also embedded into kube-apiserver for convenience, but the functionality has no connection to kube (we could remove the kube- prefix for that reason, should we? @deads2k).

**Comment by deads2k** [comment]
> Yes, it is. It happens to be also embedded into kube-apiserver for convenience, but the functionality has no connection to kube (we could remove the kube- prefix for that reason, should we? @deads2k).

No strong feeling if @caesarxuchao agrees, but decide now-ish. :)

**Comment by sttts** [comment]
Renaming PR is here: https://github.com/kubernetes/kubernetes/pull/46775

This will be rebased when the other apiextensions-apiserver PRs are merged.

**Comment by ericchiang** [comment]
I'm a little confused with the client story. Will the CRD client be pre-generated or will users have to generate those clients? I understand that's the long term goal for client-go, but wasn't aware that that had materialized yet.

**Comment by sttts** [comment]
@ericchiang the client is here: https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kube-apiextensions-server/pkg/client/clientset/clientset. The staging repo will be published soon in analogy to client-go and others.

**Comment by caesarxuchao** [comment]
I verified that kube-apiextensions-server doesn't depend on client-go/kubernetes, the type-specific part of client-go. In the future, we plan to divide client-go to two repos: the base part and the type-specific part. The type-specific part of client-go can import kube-apiextensions-server and support CRD without dependency cycle.

**Comment by lavalamp** [comment]
IMO it should be called customresource-apiserver, not [kube-]apiextensions-apiserver. The latter is easily confused with the extensions api group.

**Comment by lavalamp** [comment]
The potential for having multiple client repos is sort of the goal of the client org arrangement proposal that the sig agreed on, but I'm not sure how far along that road we got.

**Comment by deads2k** [comment]
> IMO it should be called customresource-apiserver, not [kube-]apiextensions-apiserver. The latter is easily confused with the extensions api group.

apiextensions.k8s.io is a group name that would easily host the resource for describing generic UAS storage.  The two use-cases are similar but distinct.  See reasons here: https://github.com/kubernetes/kubernetes/issues/46351

**Comment by lavalamp** [comment]
design doc: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/csi-client-structure-proposal.md#clients-for-api-extensions

**Comment by marun** [comment]
According to @deads2k this is waiting on https://github.com/kubernetes/k8s.io/pull/61 being pushed.

**Comment by marun** [comment]
@deads2k @lavalamp Any update on this?

**Comment by ixdy** [comment]
I pushed this last week. Sorry, should've updated on the PR as well.
