### ISSUE TITLE
shallow of pods shouldn't be done on syncService

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#46703]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): No.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

in `kubernetes/pkg/controller/endpoint/endpoints_controller.go` we have `syncService ` that perform unnecessary shallow copy on pods (`line 343`) : 

- we get the pods from the cache i think
- we do not mutate the pods (i.e only reading values)

so we can avoid this deepCopy i think.

**Comment by yastij** [comment]
@wojtek-t - can you confirm please ?  (there's some TODO there also i think)

**Comment by ncdc** [comment]
That's actually a shallow copy

**Comment by yastij** [comment]
@ncdc - I'm sorry i was thinking about another issue, while filing this one. I will update the issue, Thanks.
