### ISSUE TITLE
Kubernetes installation on centos 7

### ISSUE THREAD

**Issue by naina-emmanuel** [kubernetes/kubernetes#46710]
I am installing kubernetes manually on centos 7 following link https://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/ but when I install docker following https://docs.docker.com/engine/installation/linux/centos/#install-using-the-repository it does not allow me to install docker, saying docker isn't available. I am using centos7 minimal.

[root@localhost ~]# sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
Loaded plugins: fastestmirror
adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
Could not fetch/save url https://download.docker.com/linux/centos/docker-ce.repo to file /etc/yum.repos.d/docker-ce.repo: [Errno 14] curl#60 - "Peer's Certificate has expired."
[root@localhost ~]# sudo yum install docker-ce
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile

base: mirrors.nayatel.com
extras: mirrors.nayatel.com
updates: mirrors.nayatel.com
No package docker-ce available.
Error: Nothing to do
[root@localhost ~]#

**Comment by xiangpengzhao** [comment]
@naina-emmanuel In fact, this is not an issue of Kubernetes. It's a request for support for docker. I recommend you re-post this question at https://stackoverflow.com/questions/tagged/docker. You might get a quick response there, which should solve your problem.

/kind support
/area docker
/cc @thockin

**Comment by xiangpengzhao** [comment]
BTW, you might want to have a try this: https://docs.docker.com/engine/installation/linux/centos/#install-from-a-package

**Comment by naina-emmanuel** [comment]
Okie thank you
