### ISSUE TITLE
Add IPv6 Support to Kubelet Unit Tests

### ISSUE THREAD

**Issue by danehans** [kubernetes/kubernetes#46712]
The Kubelet unit tests currently use a fake node bound to IPv4-only semantics. For example, in kubelet_test.go:
```
testKubeletHostname = "127.0.0.1"
testKubeletHostIP   = "127.0.0.1"
```
Unit tests create a new test kubelet that uses the above constants to populate hostname and IP address fields of the fake node.

I am part of a sig-network working group responsible for adding IPv6 features to Kubernetes. In support of PR #45551, I am interested in expanding Kubelet test coverage to include IPv6.

I was thinking of updating the `newTestKubeletWithImageList` function to A) Create a slice of two kubelets, one using IPv4 settings and another using IPv6 settings B) Returning a slice of type `TestKubelet` and C) Updating all unit tests that call the `newTestKubeletWithImageList` or the `newTestKubelet` functions to work with the `TestKubelet` slice.

I am looking for guidance on the best way to add IPv6 to existing test cases. Your feedback is greatly appreciated.

**Comment by bckcntryskr** [comment]
a newby hack here, the following is the IPv6 equivalent:
testKubeletHostname = "::1"
testKubeletHostIP   = "::1"

**Comment by danehans** [comment]
@bckcntryskr that is correct. However, the kubelet unit tests need to cover v4 and v6 instances of a kubelet. I am finalizing a PR that implements the approach I described above.
