### ISSUE TITLE
--local flag fails on kubectl commands that deal with unstructured objects

### ISSUE THREAD

**Issue by juanvallejo** [kubernetes/kubernetes#46722]
Without a connection to an api server, executing a command such as `kubectl patch --local ...` will fail with the error `The connection to the server <server> was refused - did you specify the right host or port?`
This is because commands such as patch make use of the discovery client to map resources. A way to get around this would be to just default to using `api.Registry.RESTMapper()` if `--local` is passed, however that will cause the command to fail when dealing with thirdpartyresources.

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.2.5607+f0962765a73741-dirty", GitCommit:"f0962765a7374172625847c84630d3b522ea728f", GitTreeState:"dirty", BuildDate:"2017-05-31T19:29:55Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
```
cc @deads2k

**Comment by mml** [comment]
cc @pwittrock @caesarxuchao
