### ISSUE TITLE
'fluentd-elasticsearch'  image was not updated.

### ISSUE THREAD

**Issue by st4nson** [kubernetes/kubernetes#46720]
**Is this a request for help?**: No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): fluentd-elasticsearch 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**What happened**:
`gcr.io/google_containers/fluentd-elasticsearch:1.23` image still have old version of plugins installed.
ie.
- fluent-plugin-elasticsearch 1.5.0
- fluent-plugin-kubernetes_metadata 0.24.0

**What you expected to happen**:
`gcr.io/google_containers/fluentd-elasticsearch:1.23` image should have updated plugins. 
ie.
- fluent-plugin-elasticsearch 1.9.5
- fluent-plugin-kubernetes_metadata 0.27.0

This was applied in https://github.com/kubernetes/kubernetes/pull/46596

**How to reproduce it** (as minimally and precisely as possible):
```bash
docker pull gcr.io/google_containers/fluentd-elasticsearch:1.23
docker run -it --rm --entrypoint bash gcr.io/google_containers/fluentd-elasticsearch:1.23 -- td-agent-gem list | grep fluent
```
Old versions of plugins will be visible there.

**Anything else we need to know**:
-

**Comment by st4nson** [comment]
@crassirostris @coffeepac could You take a look ?

**Comment by crassirostris** [comment]
@st4nson Sorry, I forgot to build the newer image and this one was pushed some time ago by mistake. Done:

```
$ docker run -it --rm --entrypoint bash gcr.io/google_containers/fluentd-elasticsearch:1.23 -- td-agent-gem list | grep fluent
fluent-logger (0.7.1)
fluent-mixin-config-placeholders (0.4.0)
fluent-mixin-plaintextformatter (0.2.6)
fluent-plugin-elasticsearch (1.9.5)
fluent-plugin-kafka (0.5.5)
fluent-plugin-kubernetes_metadata_filter (0.27.0)
fluent-plugin-mongo (0.8.0)
fluent-plugin-rewrite-tag-filter (1.5.5)
fluent-plugin-s3 (0.8.2)
fluent-plugin-scribe (0.10.14)
fluent-plugin-td (0.10.29)
fluent-plugin-td-monitoring (0.2.2)
fluent-plugin-webhdfs (0.4.2)
fluentd (0.12.35)
fluentd-ui (0.4.4)
```

**Comment by st4nson** [comment]
@crassirostris thanks for fast response!
