### ISSUE TITLE
Restructure AuthProvider interface

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#46728]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): AuthProvider

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

The current AuthProvider interface lets plugins implement a "WrapTransport" method, but existing plugins are really only using it to fetch bearer tokens. It is hard to reason about authorization header priorities when the WrapTransport could potentially use or clobber any of them. We should migrate the existing plugins to an interface explicit about being for Bearer tokens.

**Comment by cjcullen** [comment]
@ericchiang @wanghaoran1988

**Comment by pwittrock** [comment]
@cjcullen can you close this or move out of the milestone?

**Comment by ericchiang** [comment]
Removing milestone. If someone wants to pick this up we can add it back for 1.9.
