### ISSUE TITLE
v1.7.x known issues / FAQ accumulator

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#46733]
Please link to this issue or comment on this issue with known errata for the 1.7.x release. This follows what we have done for prior releases.

We will be populating the "Known Issues" section of 1.7.0 and above release notes based on this issue

cc/ @kubernetes/kubernetes-release-managers

**Comment by mikebryant** [comment]
The 1.7 controller-manager has a significant regression in openstack: #47651 / #47602

**Comment by julia-stripe** [comment]
The 1.7 scheduler has a regression where pods can get stuck in the 'Pending' state forever: https://github.com/kubernetes/kubernetes/issues/49314
