### ISSUE TITLE
Add certificate rotation support to dynamic kubelet config loader

### ISSUE THREAD

**Issue by jcbsmpsn** [kubernetes/kubernetes#46730]
Looks like the dynamic kubelet config loader is the only other user of CreateAPIServerClientConfig (today). This issue is to plumb the cert-rotating-enabled client to the background process responsible for monitoring config

Evolution of https://github.com/kubernetes/kubernetes/pull/41912

**Comment by liggitt** [comment]
need to ensure we don't have multiple client cert rotating processes running

**Comment by trunet** [comment]
hello... just a question, what about if we have an external CA that issue certificates automatically and put them on the machine. kubelet is using the certificates trough arguments, and we need to rotate them. a systemctl restart kubelet works but isn't the best approach, can we have an API call or kill -SIGHUP or something to manually force a "reload" of certificates?
