### ISSUE TITLE
gce-multizone test has been broken since may 25

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#46737]
https://k8s-testgrid.appspot.com/google-gce#gce-multizone&width=5

Commits that might have broken it https://github.com/kubernetes/kubernetes/compare/079020f55...749ac27e9

* https://github.com/kubernetes/kubernetes/pull/45003
* https://github.com/kubernetes/kubernetes/pull/45932 (AWS ELB tagging)
* https://github.com/kubernetes/kubernetes/pull/46146 (unit test change only)
* https://github.com/kubernetes/kubernetes/pull/46127
* https://github.com/kubernetes/kubernetes/pull/45518 (Portworx volume driver change)

API server logs from those tests are printing a lot of stack traces. e.g. https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-multizone/7095/artifacts/bootstrap-e2e-gce-mz-master/kube-apiserver.log

cc/ @kubernetes/kubernetes-release-managers

**Comment by justinsb** [comment]
There is also the "none of the above" option - they seem to be failing due to DNS lookup failures

`dial tcp: lookup bootstrap-e2e-gce-mz-minion-group-k8jv on 169.254.169.254:53: no such host'\nTrying to reach: 'https://bootstrap-e2e-gce-mz-minion-group-k8jv:10250/stats/?timeout=5m0s`

**Comment by thockin** [comment]
Yep, they need to use FQDNs

**Comment by justinsb** [comment]
Ah - is this only for cross-AZ?  Is this caused by a change in GCE node naming / lookup behaviour - 
 aka the infamous NodeName != hostname bug :-)

If so, in kops we change the order of address resolution so that it prefers using the internal IP as found in the Node object, so in theory the Node Name does not matter.  https://github.com/kubernetes/kops/blob/db5e435c55a581ac8e94aedc8d106dc666fff839/pkg/model/components/apiserver.go#L56-L74

**Comment by bowei** [comment]
It looks to be passing now with the exception of: `[k8s.io] Firewall rule should have correct firewall rules for e2e cluster`

Does anyone know what was changed? @dchen1107

**Comment by MrHohn** [comment]
Logs from the failing firewall test:
```
I0602 08:29:07.640] Jun  2 08:28:53.558: INFO: Failed to get instance tags for bootstrap-e2e-gce-mz-minion-group-87c3: googleapi: Error 404: The resource 'projects/k8s-jkns-e2e-gce-ubelite/zones/us-central1-a/instances/bootstrap-e2e-gce-mz-minion-group-87c3' was not found, notFound
```

**Comment by MrHohn** [comment]
Opened #46894 to track the failing firewall test separately.
