### ISSUE TITLE
Refactoring kubectl config commands

### ISSUE THREAD

**Issue by arthur0** [kubernetes/kubernetes#46735]
Refactoring of the `kubectl config` commands according to the [kubectl command implementation conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#command-implementation-conventions).

Making the existent `kubectl config` [commands](https://github.com/kubernetes/kubernetes/tree/master/pkg/kubectl/cmd/config) aligned with the conventions increases the code readability, also prevents that the new commands being developed without the pattern, making them easier to the maintaining and review.

e.g. The command [kubectl create authinfo](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/config/create_authinfo.go)

* Dont follow the pattern [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/config/create_authinfo.go#L108-L113)

* The functions [run](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/config/create_authinfo.go#L133), [validate](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/config/create_authinfo.go#L265) and [complete](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/config/create_authinfo.go#L241) should be lowercase

Another point is the name of files, the `kubectl config set-credentials` command is implemented by `create_authinfo.go` and I'm not sure if `set_credentials.go` would be a better name.  

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new)

**Comment by dixudx** [comment]
/assign @dixudx

I would like to work on this if there is a consensus on the above description.
