### ISSUE TITLE
kube-proxy: add option to forcibly disconnect existing TCP clients on service updates

### ISSUE THREAD

**Issue by glennslaven** [kubernetes/kubernetes#46753]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): connection close service change pod 

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-05-09T23:22:45Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: minikube  v0.19.0
- **OS** (e.g. from /etc/os-release):
```
NAME=Buildroot
VERSION=2016.08
ID=buildroot
VERSION_ID=2016.08
PRETTY_NAME="Buildroot 2016.08"
```
- **Kernel** (e.g. `uname -a`): `Linux minikube 4.7.2 #1 SMP Fri Apr 7 10:38:40 PDT 2017 x86_64 GNU/Linux`

**What happened**:
A pod (pod A) is proxying http connections to a second pod (pod B) via a service.  Modifying the selector on the service points it at a new pod (pod C) to allow for blue/green deployments.  The software in pod A maintains a tcp connection to pod B despite the fact that the service has changed and any new connections will be established to pod C.  The existing connections will not be closed until the idle timeout expires (which with decent traffic may be some time even if it is set to a small value).

**What you expected to happen**:
When the service selector is changed, it should not be possible for data to be sent to the previously selected pod(s) via any open tcp connections. All data should go to the new pod(s) as soon as the service is updated.

**How to reproduce it** (as minimally and precisely as possible):
Apply [this yaml](https://gist.github.com/glennslaven/dd04678116180a833b516238b5616549) which will create 2 nginx pods and a pod that opens a telnet connection to pod origin1 via the service `upstream`.  Every second it will issue a HTTP GET.  

Then edit the `upstream` service selector to `origin2`.  If you check the logs on the `origin1` pod you will see that the requests continue to go there rather than to `origin2`.

**Anything else we need to know**:
A similar issue has been raised in #38456 (Point 3 under "Problems with kube-proxy" regarding connection draining)

**Comment by glennslaven** [comment]
@kubernetes/sig-network-misc

**Comment by bowei** [comment]
The current behavior is intentional to allow for existing sessions to terminate as some clients do not handle mid-session termination of TCP connections very gracefully. Do you want the option to have kube-proxy to drop existing connections immediately after service update?

We do something like this for UDP by wiping out the conntrack entry so the old packets are rejected.

**Comment by ivan-section-io** [comment]
We've got clients that will not self-release connections, but can handle mid-session termination of TCP connections gracefully.
I think the option (at a service level?) would be very helpful.

**Comment by thockin** [comment]
This is working as intended.  I'm not sure we want to offer a knob to
change this.  Every knob has to justify itself, and nobody else has asked
for this.  Happy to leave it open and collect feedback...

**Comment by bowei** [comment]
@glennslaven: It would be good to retitle the issue "kube-proxy: add option to forcibly disconnect existing TCP clients on service updates" or something to effect so the issue is more discoverable.

**Comment by jstangroome** [comment]
A common example would be an `nginx` Pod using an `upstream foo { server my-service.my-namespace; keepalive 1; }` configuration.

Nginx will hold that TCP connection to its upstream service open indefinitely, even if completely idle. It depends on the remote server to close the connection. If the remote server closes the connection mid-request, nginx will recover/retry in a large number of cases.

If the Service is being used to switch between blue/green deployments of the Pods, the Pods from the previous deployment would need to be stopped to cause Nginx's connections to close and be re-established with the new Pods. I feel that a workflow that requires the previous deployment's Pods to be stopped would be re-introducing risk that the blue/green deployment model aims to mitigate.

**Comment by glennslaven** [comment]
@thockin I appreciate that, and I agree there needs to be a good reason to add options. 

Just to state the reason we'd like it clearly: to effect a blue/green style deployment with a proxy like nginx that will hang on to a keepalive connection until the upstream service tells it to let go (or it dies) we can't just update the k8s service. We also must implement some container level messaging either to the proxy container to get it to reset its connections (assuming it has a way of doing that) or to the now unwanted upstream to get it to signal the proxy to close its connections.

Either that or we need to delete the previous upstream pod, but that assumes it is not being used by other services either.

**Comment by thockin** [comment]
Another consideration is whether we believe that every implementation of
services could actually support such a change.  Our iptables is just one.
There's an IPVS one out for review, an nftables one in devel, and an ebpf
one coming eventually.  There is/was one in Contiv and in OpenContrail.

**Comment by r7vme** [comment]
I've described similar situation [here](https://github.com/kubernetes/kubernetes/issues/47201#issuecomment-349714240)

Just wondering, why tcp keep-alive does not work at this case (when service endpoint died)?

We have use case with k8s client (which uses [tcp keep-alive](https://github.com/kubernetes/client-go/blob/master/transport/cache.go#L69-L70)) and still connection can stay in ESTABLISHED state for a while.

Any idea for workaround?

**Comment by bowei** [comment]
@r7vme can you post your TCP keepalive settings (what are the timeouts?) and a tcpdump trace of what happens when the service endpoint dies.

**Comment by r7vme** [comment]
@bowei 

> can you post your TCP keepalive settings (what are the timeouts?) 

30 sec probe interval and 30 sec idle timeout. I'm using [k8s client go](https://github.com/giantswarm/kvm-operator-node-controller/blob/master/controller.go#L294-L302). Which by default afaik has [timeouts 30 sec for interval and timeout](https://github.com/kubernetes/client-go/blob/v4.0.0/transport/cache.go#L72-L75). Here is where it implemented in [Go](https://github.com/golang/go/blob/release-branch.go1.9/src/net/tcpsockopt_unix.go#L15-L25).

> tcpdump trace of what happens when the service endpoint dies.

I did only one test and see that RST was sent and connection was dropped. I'm going to retest few more times.

Dead socket is `172.31.53.156:443`.

Successful tcp reset test - [logs](https://gist.github.com/r7vme/691898af40526bf8571f5b42b7a446bc)

I'm continue testing to reproduce problem.

**Comment by r7vme** [comment]
Unsuccessful test tcp stuck for 16 minutes - [logs](https://gist.github.com/r7vme/c1dc59c54ced7c2f8d2e22e94460539f)

**Comment by r7vme** [comment]
I observe that TCP keepalive probes does not help, because k8s client tries to send data periodically and connection becomes non-idle. TCP keepalive by default needs 9 unsuccessful proves to kill connection this means it need in total 4m30sec to kill connection if it was idle for 30sec. So i should have my app idle (on http level) for at least 5min (which is definitely not the case.)

But except situation above i also sometimes see:
- RST was sent from recipient (like [here](https://gist.github.com/r7vme/691898af40526bf8571f5b42b7a446bc))
- ICMP host unreachable from gateway - this is layer below, so it does not really help with TCP.
