### ISSUE TITLE
Allow --runtime-config to be set using juju charms

### ISSUE THREAD

**Issue by jacekn** [kubernetes/kubernetes#46778]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): juju

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Description**:

Currently there is no way to set --runtime-config value when kubernetes is deployed using juju charms.  I need to use CronJob resources and official documentation says I need this option set:
`--runtime-config=batch/v2alpha1=true`

Could support for setting that and other flags be added?

**Comment by xiangpengzhao** [comment]
As a workaround, you can manually set `--runtime-config=batch/v2alpha1=true` on apiserver after the cluster is deployed and then restart apiserver. Note that you also need to restart controller-manager. See:https://kubernetes.io/docs/concepts/overview/kubernetes-api/ "Enabling API groups"
