### ISSUE TITLE
juju charms should allow OpenStack volumes configuration

### ISSUE THREAD

**Issue by jacekn** [kubernetes/kubernetes#46781]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): juju

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Description**:

Kubernetes can consume OpenStack Cinder volumes:
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#openstack-cinder

But currently there is no way to configure it when kubernetes is deployed using juju charms.

Could you please add support for configuring OpenStack Cinder volumes to the juju charms?

**Comment by chuckbutler** [comment]
@jacekn help me scope this. Is this bug stating that its impossible or it's just a manual process?

**Comment by jacekn** [comment]
@chuckbutler it's impossible, from what I found I need to set those options:
`--cloud-provider=openstack --cloud-config=<creds_file> options`

**Comment by xsgordon** [comment]
I'm not sure anyone in sig-openstack actively works on the Juju charms... Thus far the SIG's scope has primarily been `cluster/openstack-heat` and `pkgs/cloudprovider/providers/openstack`.

@castrojo, @chuckbutler, @marcoceppi, and @mbruzek are listed as the OWNERS for the Juju charms.

/cc @k8s-sig-openstack-feature-requests

**Comment by dims** [comment]
Looks like there is no interest from juju folks. so we won't be fixing this anytime soon

/close

**Comment by marcoceppi** [comment]
We've recently enabled `--cloud-provider` for other clouds - not sure how this slipped through our radar, but it's something we'd like to enable

/cc @tvansteenburgh
