### ISSUE TITLE
"kubectl get networkpolicies", etc, return new apiVersion instead of old

### ISSUE THREAD

**Issue by danwinship** [kubernetes/kubernetes#46788]
In #39164 @liggitt said:

> the new networking.k8s.io group should be appearing after extensions in discovery, and the old extensions group should be preferred, but it is not (networking.k8s.io is preferred if no group is specified using kubectl). 
> @deads2k, same root issue as #46322?

Although #46322 is about a single API group with two versions, as opposed to a resource type with versions in two different API groups like here, so that might be something different. (networking's VersionPreferenceOrder only has a single element.)

I don't know how big a deal this is... @liggitt?

@thockin FYI, forgot to file this with the other to-do bugs before

**Comment by liggitt** [comment]
it's important because we want kubectl to continue to prefer extensions networkpolicies, since that's what previous versions know how to pretty-print. should be addressed with the fix to #46322

**Comment by deads2k** [comment]
I will address the discovery order problem before 1.7 ships.

**Comment by bowei** [comment]
@deads2k is there a PR associated with this?

**Comment by matchstick** [comment]
@deads2k You commented that this was going to be addressed for 1.7 . Any update? Do you need help? The deadline is getting close. 
@kubernetes/sig-network-misc 
@liggitt Can this slip to a patch fix?

**Comment by liggitt** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/46800

I don't think we can ship as-is

**Comment by aanm** [comment]
What about this https://github.com/kubernetes/kubernetes/pull/46951?

**Comment by danwinship** [comment]
@aanm that's unrelated; kubectl is able to fetch either type ("kubectl get networkpolicies.extensions" will return v1beta1 objects); this is just about it having the wrong default.

**Comment by liggitt** [comment]
Fixed by #46800
