### ISSUE TITLE
[OIDC] Email Verified

### ISSUE THREAD

**Issue by curtisallen** [kubernetes/kubernetes#46806]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

**Kubernetes version** (use `kubectl version`): 1.6.2

The API server will reject OIDC tokens with a claim `email_verfied = false`, the logic to do so is [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc.go#L255-L257)

My IDP (Okta) issues tokens with `email_verfied = false`, I want to enable unverified email address to access k8s APIs. Could we add a configuration option allowing users with unverified email address access to k8s? 

cc:/ @ericchiang

**Comment by curtisallen** [comment]
cc: @kubernetes/sig-auth-pr-reviews

**Comment by ericchiang** [comment]
I'm against this. Can you elaborate on why this would ever be something you'd want to enable? Does Okta never return email_verified = true?

**Comment by liggitt** [comment]
Agree, if the provider explicitly has not verified the user has control of that email address, it is not an appropriate claim to use as the username

**Comment by curtisallen** [comment]
@ericchiang My current client uses Active Directory to provision users and email address, [Okta](https://www.okta.com/) is setup as downstream sync of AD data, therefore every user provisioned in Okta has `email_verfied = false` claims. I suspect this is true with any OP that isn't the system of record. Reading the OIDC spec https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

> True if the End-User's e-mail address has been verified; otherwise false. When this Claim Value is true, this means that the OP took affirmative steps to ensure that this e-mail address was controlled by the End-User at the time the verification was performed. The means by which an e-mail address is verified is context-specific, and dependent upon the trust framework or contractual agreements within which the parties are operating.

Even if an email address is verified the context is specific to the OP.

**Comment by curtisallen** [comment]
Thanks for taking a look @ericchiang and @liggitt 
This issue seems like an analog to the `insecure-skip-tls-verify`option, OPs may or may not provide the `email_verfied = true` claim. I would think the k8s cluster administrator should have to option of disabling this check. I agree that the default functionality should check for the existence of `email_verfied == true`. 
The OIDC spec states
> The means by which an e-mail address is verified is context-specific, and dependent upon the trust framework or contractual agreements within which the parties are operating.

Without providing an option to disable the check k8s is making assumptions about the trust framework that are not within its purview. (my 2 cents)

**Comment by ericchiang** [comment]
@curtisallen we intentionally do not provide an insecure-skip-tls-verify and this discussion parallels that thinking.

I think there are a ton of nobs that users would like to see for this plugin. Multiple audiences, customizable prefixing, and dealing with difference concepts of groups are common ones. I don't know how much of that lives in core kube.

**Comment by curtisallen** [comment]
Yeah, I'd agree, would be nice If I could apply my own OIDC module configuration, without having to change k8s core source.

**Comment by liggitt** [comment]
> would be nice If I could apply my own OIDC module configuration, without having to change k8s core source

you could provide a webhook authenticator that processes OIDC tokens differently if desired
