### ISSUE TITLE
Unstructured.OwnerReferences are not round-tripped properly

### ISSUE THREAD

**Issue by ash2k** [kubernetes/kubernetes#46817]
**Kubernetes version**
Code from master.

**What happened**:
`Unstructured.GetOwnerReferences()` does not return `Controller` and `BlockOwnerDeletion` fields after they are set to non-nil values using `Unstructured.SetOwnerReferences()`.

**How to reproduce it** (as minimally and precisely as possible):
See PR #46683

**Comment by deads2k** [comment]
This is a good find and I don't think I saw the notification come through :(
