### ISSUE TITLE
Add a label "sig/ui"

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#46832]
We have [SIG UI](https://github.com/kubernetes/community/blob/master/sig-ui/README.md), but there isn't a label `sig/ui` in the k/k repo. There is only `area/ui`. Do we need to add a label `sig/ui` or rename `area/ui` to `sig/ui`?

@spiffxp @bryk @danielromlein

**Comment by xiangpengzhao** [comment]
/sig ui
:smiley:

**Comment by bryk** [comment]
I just added it. Fixed?

**Comment by xiangpengzhao** [comment]
Yeah. BTW, the page https://github.com/kubernetes/community/blob/master/sig-ui/README.md has a bad md format. It also should be fixed.

**Comment by cblecker** [comment]
@xiangpengzhao Feel free to send a PR to fix :)

**Comment by xiangpengzhao** [comment]
@cblecker As Piotr is the owner, I thought let him fix:) If it's Okay, I will do. Thanks Christoph!

**Comment by cblecker** [comment]
anyone can contribute to the kubernetes/community repo too :) the PR would be reviewed like any other (usually the sig-lead for that sig would review)

**Comment by xiangpengzhao** [comment]
Okay:)

**Comment by bryk** [comment]
Yep @xiangpengzhao, just fix things when you can. That's just faster :)

**Comment by spiffxp** [comment]
FWIW this lead me to open #46978
