### ISSUE TITLE
[Feature Request] spread pods of a deployment by custom node label(e.g IDC/Carrier/Operator)

### ISSUE THREAD

**Issue by jmzwcn** [kubernetes/kubernetes#46837]
Add a deploymentAntiAffinity(similar to [ServiceAntiAffinity](https://github.com/kubernetes/kubernetes/blob/749ac27e9a608296a169a62b158181440cbddb19/plugin/pkg/scheduler/algorithm/priorities/selector_spreading.go#L194)), so that we could spread pods of a deployment by custom node label(e.g IDC/Carrier/Operator).

For more detail, please refer to #46568

**Comment by k82cn** [comment]
@jmzwcn , can you share why PodAntiAffinity can not meet your requirements?
If it's similar or the same requirement, prefer to continue the discussion at #46568. I have @ kubernetes/sig-scheduling-feature-requests in that issue to get scheduling sig's awareness :).

**Comment by jmzwcn** [comment]
Maybe it could resolve our issue, But I feel it is not a best solution.

**Comment by vikaschoudhary16** [comment]
@jmzwcn will not it work if something like `TopologyKey: "IDC"` is used in the podAntiAffinity term as explained [here](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/podaffinity.md#anti-affinity) ?
Looks like this functionality is implemented as well and [non-node topology key is allowed](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/priorities/util/topologies.go#L53)
