### ISSUE TITLE
Minor improvements to builds on Mac OS X

### ISSUE THREAD

**Issue by sidharta-s** [kubernetes/kubernetes#4683]
There are couple of minor things when building on Mac OS X that could be fixed :

1. make release : Run $(boot2docker shellinit) automatically when applicable ? i.e when the boot2docker VM has already been started. The build exits at this point if boot2docker env has not be setup even if the VM is running/available.
2. make clean : Attempts to connect to a docker daemon when docker is installed but isn't being used with the current build ( e.g when building with hack/build-go.sh ).   

Is mixing and matching hack/build-go.sh with 'make clean' a supported mechanism? This seems to indicate that it is : https://github.com/GoogleCloudPlatform/kubernetes/issues/1959 . 

I could submit a PR for that ensures that the docker env is setup correctly for 'make release' and 'make clean'. I am not sure how to handle the mixed case of 'hack/build-go.sh' and docker installed + 'make clean'

**Comment by MHBauer** [comment]
This issue is obsoleted by the move to using `docker-machine`.
