### ISSUE TITLE
Add an e2e test measuring the time it takes for HPA and CA to scale up after load increase

### ISSUE THREAD

**Issue by wasylkowski** [kubernetes/kubernetes#46847]
Currently the time it takes for HPA and CA to scale up after load increase is not measured at all, and this can lead to regressions that will be missed. This issue is about adding an e2e test that will prevent such regressions.

@wojtek-t @fgrzadkowski

**Comment by fgrzadkowski** [comment]
@kubernetes/sig-autoscaling-feature-requests

**Comment by wasylkowski** [comment]
@fgrzadkowski Filip, can you reopen? I cannot do this myself, and this issue is clearly not closed yet.

**Comment by wasylkowski** [comment]
Thanks Wojtek!
