### ISSUE TITLE
Pod type should use runtimeapi.PodSandbox for sandoxing environment instead of container slice

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#46840]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

Podsandbox
runtime
sandbox

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

in `kubernetes/pkg/kubelet/container/runtime.go` we provide pod type that use containers slice as Podsandbox, we should replace it with runtimeapi.PodSandbox as states the TODO that we have : https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/runtime.go#L187

this will need to make some changes

cc @yujuhong

**Comment by yastij** [comment]
@yujuhong - auditing code right now, spotted around 13 usages that needs refactoring with this one.

**Comment by yastij** [comment]
@Random-Liu just had the time to look back to this one, are you okay with this ?

**Comment by yujuhong** [comment]
I believe more places in kubelet need to be changed to be PodSandbox-aware. This would be easier once we remove the rktnetes integration, which does not use PodSandbox at all.

**Comment by yastij** [comment]
@yujuhong - Indeed there's bunch of places where changes should happen. Any issue that tracks rktnetes removal ?

**Comment by yujuhong** [comment]
FYI: https://github.com/kubernetes/kubernetes/issues/53601

**Comment by yastij** [comment]
@yujuhong - I'll keep this one open and waiting for #53601

**Comment by yastij** [comment]
@yujuhong - should we close this ?
