### ISSUE TITLE
flake: pull-kubernetes-federation-e2e-gce dial tcp ./federation/cluster/federation-up.sh failed

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/kubernetes#46859]
In federation pre-submit tests `pull-kubernetes-federation-e2e-gce`, we are seeing a class of failures in which the k8s cluster api server is failing to respond and timing out. 
```
I0602 04:54:42.507] +++ [0602 04:54:42] Image: "gcr.io/k8s-jkns-pr-bldr-e2e-gce-fdrtn/hyperkube-amd64:v1.8.0-alpha.0.2_40f0365408936e"
W0602 04:55:12.600] I0602 04:55:12.599537    3490 cached_discovery.go:126] skipped caching discovery info due to Get https://35.188.205.233/api: dial tcp 35.188.205.233:443: i/o timeout
W0602 04:55:12.600] F0602 04:55:12.599926    3490 helpers.go:120] error: Couldn't get clientset to create RBAC roles in the host cluster: Get https://35.188.205.233/api: dial tcp 35.188.205.233:443: i/o timeout
W0602 04:55:12.605] 2017/06/02 04:55:12 util.go:131: Step './federation/cluster/federation-up.sh' finished in 30.265002761s
```
Once the k8s cluster reaches this condition all builds starts to fail and we need to recycle the k8s clusters to restore.
Also its interesting that it has links to load balancer service.

The first failure we see actually times out waiting for creating LoadBalancer type service. [8344](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46716/pull-kubernetes-federation-e2e-gce/8344/)
Subsequently all the build fails with above mentioned error messages. (8351 onwards)

This pattern is observed consistently now.

cc @madhusudancs @csbell @kubernetes/sig-federation-bugs

**Comment by shashidharatd** [comment]
The root cause for this type of failures was that there was a janitor process which used to cleanup k8s clusters every few hours. This was rectified in test-infra by excluding the `k8s-jkns-pr-bldr-e2e-gce-fdrtn` project which host the k8s clusters for federation pre-submits.

Ref: https://github.com/kubernetes/test-infra/pull/2947

/cc @madhusudancs @krzyzacy @csbell 
/close

**Comment by krzyzacy** [comment]
Hummm, it's merged Friday afternoon, but how did this affect federation job afterwards?

**Comment by shashidharatd** [comment]
@krzyzacy, i think this issue is older than Friday afternoon. `2017-06-02 15:07 IST`, probably PDT time is `2017-06-02 02:37 PDT`

**Comment by krzyzacy** [comment]
Oh nvm, I saw the presubmit is screwed again, thought some damage was done over the weekend again :-)
