### ISSUE TITLE
kops cannot test v1.8.x kubernetes builds

### ISSUE THREAD

**Issue by tnozicka** [kubernetes/kubernetes#46853]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46500/pull-kubernetes-e2e-kops-aws/28678/

**Comment by Q-Lee** [comment]
Is this sig aws or cluster life-cycle?
/sig aws

**Comment by liggitt** [comment]
kops is failing because it doesn't recognize kubernetes tags 1.8.x, which exist since the 1.7 branch was cut last night

see https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/util/versions.go#L27

**Comment by justinsb** [comment]
Thanks for the heads up @liggitt - on it now!
