### ISSUE TITLE
kube-controller-manager controllers are skipped

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#46871]
Edit: see next comment ( https://github.com/kubernetes/kubernetes/issues/46871#issuecomment-305866515) for kube-controller-manager likely root-cause

We're seeing some e2e failures where the scheduler gets the lock, but then stops logging.

Bad: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/46700/pull-kubernetes-e2e-kops-aws/28741/artifacts/ec2-54-183-154-56.us-west-1.compute.amazonaws.com/kube-scheduler.log

Good: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/46866/pull-kubernetes-e2e-kops-aws/28742/artifacts/ec2-52-91-114-144.compute-1.amazonaws.com/kube-scheduler.log

This is the cause of at least some of https://github.com/kubernetes/kubernetes/issues/46370

**Comment by justinsb** [comment]
OK, it looks like actually kube-controller-manager is not creating pods (AFAICT).  I saw this in the log:

```
I0602 16:59:42.235530       5 controller_utils.go:973] Waiting for caches to sync for TTL controller
I0602 16:59:42.277404       5 controllermanager.go:452] Started "replicationcontroller"
I0602 16:59:42.277424       5 controllermanager.go:442] Starting "deployment"
W0602 16:59:42.277435       5 controllermanager.go:449] Skipping "deployment"
I0602 16:59:42.277450       5 controllermanager.go:442] Starting "replicaset"
W0602 16:59:42.277460       5 controllermanager.go:449] Skipping "replicaset"
I0602 16:59:42.277469       5 controllermanager.go:442] Starting "csrsigning"
I0602 16:59:42.277553       5 replication_controller.go:151] Starting RC controller
I0602 16:59:42.277571       5 controller_utils.go:973] Waiting for caches to sync for RC controller
I0602 16:59:42.324247       5 controllermanager.go:452] Started "csrsigning"
```

`W0602 16:59:42.277435       5 controllermanager.go:449] Skipping "deployment"` looks like root cause, and does not appear in the "good" run.

**Comment by justinsb** [comment]
The two test runs, as much for my records:

Good: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46866/pull-kubernetes-e2e-kops-aws/28742/
Bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46700/pull-kubernetes-e2e-kops-aws/28741/

**Comment by justinsb** [comment]
Looking at the code, I'm wondering if this could be a race with resource registration:

```

func startDeploymentController(ctx ControllerContext) (bool, error) {
	if !ctx.AvailableResources[schema.GroupVersionResource{Group: "extensions", Version: "v1beta1", Resource: "deployments"}] {
		return false, nil
	}
	go deployment.NewDeploymentController(
		ctx.InformerFactory.Extensions().V1beta1().Deployments(),
		ctx.InformerFactory.Extensions().V1beta1().ReplicaSets(),
		ctx.InformerFactory.Core().V1().Pods(),
		ctx.ClientBuilder.ClientOrDie("deployment-controller"),
	).Run(int(ctx.Options.ConcurrentDeploymentSyncs), ctx.Stop)
	return true, nil
}
```

That's the only way this can return false, which is when "Skipping" is logged:

```
started, err := initFn(ctx)
		if err != nil {
			glog.Errorf("Error starting %q", controllerName)
			return err
		}
		if !started {
			glog.Warningf("Skipping %q", controllerName)
			continue
		}
```

Is that even possible cc @k8s-mirror-api-machinery-bugs ?  Any hints / other ideas if not?

cc @dchen1107 as I know you want to be kept in the loop on this investigation.

**Comment by justinsb** [comment]
Ah ... it is definitely _something_ to do with registration, because this also appears:

```
E0602 16:59:42.130865       5 graph_builder.go:204] no matches for {networking.k8s.io v1 networkpolicies}. If {networking.k8s.io v1 networkpolicies} is a non-core resource (e.g. thirdparty resource, custom resource from aggregated apiserver), please note that the garbage collector doesn't support non-core resources yet. Once they are supported, object with ownerReferences referring non-existing non-core objects will be deleted by the garbage collector.
E0602 16:59:42.145775       5 graph_builder.go:204] no matches for {admissionregistration.k8s.io v1alpha1 initializerconfigurations}. If {admissionregistration.k8s.io v1alpha1 initializerconfigurations} is a non-core resource (e.g. thirdparty resource, custom resource from aggregated apiserver), please note that the garbage collector doesn't support non-core resources yet. Once they are supported, object with ownerReferences referring non-existing non-core objects will be deleted by the garbage collector.
E0602 16:59:42.145928       5 graph_builder.go:204] no matches for {admissionregistration.k8s.io v1alpha1 externaladmissionhookconfigurations}. If {admissionregistration.k8s.io v1alpha1 externaladmissionhookconfigurations} is a non-core resource (e.g. thirdparty resource, custom resource from aggregated apiserver), please note that the garbage collector doesn't support non-core resources yet. Once they are supported, object with ownerReferences referring non-existing non-core objects will be deleted by the garbage collector.
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/46700/pull-kubernetes-e2e-kops-aws/28741/artifacts/ec2-54-183-154-56.us-west-1.compute.amazonaws.com/kube-controller-manager.log

**Comment by dchen1107** [comment]
cc/ @erictune I don't know the deployment belongs to which sig (marked with sig/apps for now), I guess you are interested in this issue.  

@janetkuo

**Comment by kargakis** [comment]
cc: @deads2k

**Comment by deads2k** [comment]
@justinsb Do you have an interlock between seeing `/healthz` report "ok" before pointing the `kube-controller-manager` at it?  I'd kind of expect something like the readiness checks for a service.  This incomplete discovery information could be the result of incomplete autoregistration.

**Comment by justinsb** [comment]
I don't believe we do, no.  apiserver will come up on localhost and k-c-m talks to it directly.  There's no kube-proxy (hence no health checks) involved, for example.

Do you have an example of how such an interlock is implemented elsewhere?  I'm happy to implement it in kops, though I'm not sure whether this would affect others also.

**Comment by deads2k** [comment]
> Do you have an example of how such an interlock is implemented elsewhere? I'm happy to implement it in kops, though I'm not sure whether this would affect others also.

local-up-cluster does a simple check: https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh#L534 .  I'm not necessarily opposed to adding a check in the kube-controller-manager, but it seems like a more general problem.  `/healthz` is how the API server indicates health.  I don't think it should deny requests by default because that could make debugging bad conditions really hard.

**Comment by justinsb** [comment]
I guess we could add it as an initializer in the kcm pod.  I am a little lost as to how gce isn't hitting this also, because I don't see that readiness check.  One gotcha is that apiserver could crash in between /healthz and the resource scan.

Which makes me wonder: Is kcm is making an assumption that the set of resources is fixed, and is that assumption no longer valid?   So if kcm sees that a resource is not registered, perhaps it should retry periodically.

Proposed next steps:

* Figure out if GCE is doing an interlock, or if the timing is just different so this is happening less often / never by "luck".
* Decide on the approach to fix if GCE doesn't have a magic bullet.  A /healthz wait is simple, and would fix it in practice, but would need a release note and this would trip people up in the real world that aren't using one of the installers.  We could build that /healthz wait into kcm, which would obviate    the need for a release note.  Or we could retry on missing-resources in kcm.


Thanks @deads2k for explaining what's going on here, BTW.

**Comment by justinsb** [comment]
One possible explanation\: we always run kcm with leader election, even in single master configurations, and my guess is that means we get to the apiserver faster (no kubelet backoff).  Which I guess would imply we would see this more in HA configurations also, if that is the significant difference.

**Comment by deads2k** [comment]
> Which makes me wonder: Is kcm is making an assumption that the set of resources is fixed, and is that assumption no longer valid? So if kcm sees that a resource is not registered, perhaps it should retry periodically.

The list hasn't been fixed since TPRs were introduced many releases ago.  The code that does the resource checks has comments about updating to handle changing lists of resources, but the work was never done.

I would propose a slightly different fix.  If we separated controllers into binaries associated with an API group, the absence of the group could simply crashloop a pod running the controllers. That way its easier to answer the question of "which controllers are actually working".

**Comment by justinsb** [comment]
I don't disagree that splitting up k-c-m is a good long-term fix.  We do also need a fix for 1.7, because it is much more likely than it was in 1.6, at least according to the flake rate for the kops e2e (*).  I agree that waiting for /healthz would be adequate, but we should decide an approach asap and get it into testing.

* I am assuming that the majority of the increase in the kops flakes are due to this.  There were flakes before - for example if we hit AWS quota or rate limits, we are likely to flake.  Manual inspection of failures has shown this problem in all the k-c-m logs, but my sampling is limited.  I think test-infra might have some magic to bulk-query k-c-m logs and find the problem if we need that information.

**Comment by justinsb** [comment]
The "moral equivalent" of separating into separate binaries which kubelet would restart is presumably that k-c-m would not skip controllers, but would rather have them in separate goroutines that loop (with backoff) until they were registered (which might never happen).

**Comment by deads2k** [comment]
This change happened in 1.6. When did you start seeing the increase?

**Comment by justinsb** [comment]
Anecdotally, post-1.6, or the past month; see e.g. https://github.com/kubernetes/kubernetes/issues/46370.

A more precise answer would require some of that test-infra grep magic.

**Comment by deads2k** [comment]
Hmmm... That actually got added here: https://github.com/kubernetes/kubernetes/pull/15427

**Comment by justinsb** [comment]
Right, but I believe we accept that we have a race here without something like the interlock (?).  I suspect the reason that we're hitting the race will be subtle - e.g. we've made k-c-m a little faster after acquiring the lock, or the apiserver starts the http listener sooner, or resource registration takes a little longer.

**Comment by liggitt** [comment]
@deads2k is this fixed?

**Comment by deads2k** [comment]
Yes

**Comment by mml** [comment]
What was the fix?

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/46985
