### ISSUE TITLE
RBAC DENY messages are spammy with podsecuritypolicies

### ISSUE THREAD

**Issue by Q-Lee** [kubernetes/kubernetes#46877]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**: the psp admission controller iterates through applicable psps for both the user and the service account. This leads to *at least* one RBAC DENY message for each pod.

**What you expected to happen**: "RBAC DENY" should be a more meaningful message

**How to reproduce it** (as minimally and precisely as possible): enable psp w/rbac

**Comment by liggitt** [comment]
closing in favor of https://github.com/kubernetes/kubernetes/issues/55821
