### ISSUE TITLE
Audit false sharing on structs

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#46888]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): No.

---

We should audit code to explore any false sharing on our structs.

Solution on extreme cases is to use padding to avoid false sharing.

**Comment by jagosan** [comment]
tough one to apply a sig label.  basically performance enhancement yes?  applying scalability for lack of better option. 

/sig scalability

**Comment by yastij** [comment]
@jagosan - sig/scalability is the right one. I will use this issue to track down progress.

**Comment by yastij** [comment]
ping @wojtek-t @jagosan, Just had the time to start this one. I can't profile de whole structs on k8s, which areas do you think we should start with ? To me apiserver and kubelet are perfect candidates ? In particular I'm thinking about structs that have mutex and are surrounded with other heavy structs.

also ping @thockin do you think that this audit is relevent ?
