### ISSUE TITLE
FlexVolume unable to mount plugins that do not require an attach.

### ISSUE THREAD

**Issue by verult** [kubernetes/kubernetes#46882]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): "flexVolume", "flex volume"

---
Kubernetes version: 1.7
Component/Area: Storage
Affected modules: Flex volume

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-beta.0-dirty", GitCommit:"e3db58e39a3ff1012efdf646c727278b82299c5e", GitTreeState:"dirty", BuildDate:"2017-06-02T20:10:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-beta.0-dirty", GitCommit:"e3db58e39a3ff1012efdf646c727278b82299c5e", GitTreeState:"dirty", BuildDate:"2017-06-02T20:08:05Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**: When kubelet has --enable-controller-attach-detach=false, it's unable to mount the example NFS FlexVolume plugin. Would expect this to happen for all FlexVolume plugins with no "attach" implemented.

**What you expected to happen**: Mount occurs successfully.

**How to reproduce it** (as minimally and precisely as possible): Load the FlexVolume NFS plugin as normal, start kubelet with --enable-controller-attach-detach=false, and start a pod that attempts to mount the NFS volume through FlexVolume.

**Anything else we need to know**:
kubelet.log is filled with the following:
```
W0602 20:35:32.520097    8160 attacher-defaults.go:36] flexVolume driver nfs: using default Attach for volume 0x214e310, host kubernetes-minion-group-1wsv
I0602 20:35:32.620336    8160 reconciler.go:232] operationExecutor.AttachVolume started for volume "test" (UniqueName: "nfs/10.244.2.6~exports") pod "nginx-nfs" (UID: "c8cb9763-47d1-11e7-816d-42010a800002") 
```

**Comment by verult** [comment]
When "attach" is not implemented by the plugin, the FlexVolume default attach method returns an empty devicePath (signaling an attach didn't occur) and nil error. 
https://github.com/kubernetes/kubernetes/blob/release-1.7/pkg/volume/flexvolume/attacher-defaults.go#L37

But inside OperationGenerator's attach function, when there is no error and devicePath is empty, the volume doesn't get marked as attached.
https://github.com/kubernetes/kubernetes/blob/release-1.7/pkg/volume/util/operationexecutor/operation_generator.go#L269

So the VolumeManager's reconciler continuously attempts to reattach without any success, and it can't proceed to mount the volume.

**Comment by dims** [comment]
@verult So what's the suggestion here on how to handle this situation?

**Comment by chakri-nelluri** [comment]
@verult @dims.. It seems to work fine with 1.6 code base. Nothing changed AFAIK in this area for 1.7. Checking with @verult on slack to get more details

**Comment by verult** [comment]
The devicePath == "" check in operation generator was introduced in this PR post 1.6:
https://github.com/kubernetes/kubernetes/pull/44537

I'm trying to understand the intention of this change and thinking about a good way to get around it for FlexVolume, but one possibility is to have FlexVolume's default attacher return a special error, which is then caught by the Attach method in operation generator signaling the volume is "attached", allowing mounting to proceed.

**Comment by verult** [comment]
I can take a look and propose a PR fix.

/assign @verult

**Comment by msau42** [comment]
Is `--enable-controller-attach-detach=false` the default setting?

**Comment by verult** [comment]
@msau42 No it defaults to true.
https://github.com/kubernetes/kubernetes/blob/62435edeff9076829ecc2cfe8aa783a89a31700f/pkg/apis/componentconfig/v1alpha1/defaults.go#L244

I haven't verified if this is an issue with `--enable-controller-attach-detach=true`

**Comment by msau42** [comment]
Why do we need to set it to false?

**Comment by verult** [comment]
I use this to simplify FlexVolume testing by dropping the plugin into a single node rather than multiple. If it were set to true, the drivers need to be dropped in master as well.

Since the operation generator code is shared between VolumeManager and AttachDetachController, I suspect this would also be an issue if it were set to true.

**Comment by verult** [comment]
The main issue is that when Attacher.Attach() returns "", nil, it's very ambiguous. Not only does this carry no information about the intention, it also means different things for different volume plugins. For Cinder, it means the attach is pending. For FlexVolume, it means the user plugin doesn't implement attach.

Two potential solutions:
1) Add a "status" return value.
2) Enforce that we can't have (devicePath, err) == ("", nil), and use different error types to disambiguate.

**Comment by gnufied** [comment]
I have proposed in past to remove/deprecate `--enable-controller-attach-detach` flag, because master-controller has been default for awhile now.

Moreover, there are many  other issues that exist if user chooses to set this flag to false (for example - no error events get logged to pod on attach/detach failure IIRC).  kubelet side attach/detach receives little to no testing.

**Comment by msau42** [comment]
Can you try with the default settings, so that we can eliminate some variables?  Even for GKE, where you can't drop plugins in the master, flex still should work as long as the plugin doesn't need to attach/detach.

**Comment by saad-ali** [comment]
PR https://github.com/kubernetes/kubernetes/pull/44537 introduced this check:

```GO
func (og *operationGenerator) GenerateAttachVolumeFunc(
...
	return func() error {
...
		} else if devicePath == "" {
			// do nothing and get device path next time.
			return nil
		}
```

This is changed a fundamental behavior of the attacher and I do not see a strong justification for doing so. Having all attach methods silently succeed if `devicePath` is empty *is not ok*.

@FengyunPan could you please provide justification. Otherwise I propose reverting that change.

**Comment by msau42** [comment]
As an alternative to #44537, can we do a similar method in #46182 to wait for the pending operation to complete?

**Comment by FengyunPan** [comment]
@saad-ali @msau42 @verult I am sorry for that, I will do a similar method in #46182 to wait for the pending operation to complete soon.

**Comment by saad-ali** [comment]
Thanks for jumping on it quickly!
