### ISSUE TITLE
Cannot access kubernetes dashboard UI 

### ISSUE THREAD

**Issue by montanaflynn** [kubernetes/kubernetes#46892]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

EOF, dashboard, ui

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.4-gke.0", GitCommit:"b8463befa7d1cdc2eba7452b7608a31f4087e79d", GitTreeState:"clean", BuildDate:"2017-05-22T18:58:26Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

I ran:

```
$ kubectl proxy
Starting to serve on 127.0.0.1:8001
```

Then visited http://127.0.0.1:8001/ui which redirected to  http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/#!/workload?namespace=default 

This displayed the following error:

```
error_outline Service Unavailable (503)

Error: 'EOF'
Trying to reach: 'http://10.12.6.4:9090/api/v1/workload/default?itemsPerPage=10&page=1'
```

**What you expected to happen**:

To see the kubernetes dashboard UI.

**How to reproduce it** (as minimally and precisely as possible):

Run `kubectl proxy` then go to http://127.0.0.1:8001/ui/

**Anything else we need to know**:

Nothing I can think of.

**Comment by montanaflynn** [comment]
Made an issue on the dashboard repo as well in case it belonged there: https://github.com/kubernetes/dashboard/issues/2011

**Comment by liggitt** [comment]
yes, the dashboard repo is the correct place
