### ISSUE TITLE
No validation of envFrom in pod.spec.containers

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#46908]
Scenario:

```
$ cat badpod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: invalid-config-env
spec:
  containers:
  - name: hello-pod
    image: docker.io/ocpqe/hello-pod:latest
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
    - name: duplicate_key
      value: FROM_ENV
    - name: expansion
      value: $(REPLACE_ME)
    envFrom:
    - configMapRef:
        name: $%^&*#
$ kubectl create -f badpod.yaml
```

Expected results:

pod would not be created as pod.spec.containers[0].envFrom.configMapRef.name is invalid

Actual results:

pod is created.

Turns out we are not doing any validation of envFrom in container spec today.

**Comment by derekwaynecarr** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by smarterclayton** [comment]
I don't know that we can tighten without failing pods.

**Comment by fraenkel** [comment]
The validation code exists, but there was no wiring done from validateContainers.

**Comment by derekwaynecarr** [comment]
Pods fail on kubelet already.  So those pods were not doing much already.  We had a BZ on this.

**Comment by smarterclayton** [comment]
Fail how - fail to even start, or fail to get the input?
