### ISSUE TITLE
Add parallelism field in JobStatus to reflect the real running pods of a Job

### ISSUE THREAD

**Issue by wanghaoran1988** [kubernetes/kubernetes#46905]
**Is this a request for help?** : Yes

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): job

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
 FEATURE REQUEST

**Detail**:

The Job resource can set `parallelism` to  specifies the maximum desired number of pods the job should run at any given time, we need set the field in JobStatus spec to show how many pods are running at the current time.

**Comment by k82cn** [comment]
Does it `Job.Status.Active`?

**Comment by wanghaoran1988** [comment]
@k82cn Thanks, I must missed that.

**Comment by kargakis** [comment]
Cool
