### ISSUE TITLE
When apiserver is unavailable, kubelet cannot restart containers that set env using configMapKeyRef

### ISSUE THREAD

**Issue by jfoy** [kubernetes/kubernetes#46920]
**Is this a request for help?**: No

**What keywords did you search in Kubernetes issues before filing this one?**: configmap environment kubelet 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Kubernetes version** (use `kubectl version`): 1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS 1235.9.0
- **Kernel** (e.g. `uname -a`): 4.7.3-coreos-r2
- **Install tools**: custom CloudFormation

**What happened**: Due to operator error, we catastrophically lost the apiserver/etcd control plane for a cluster serving production traffic. We expected that individual kubelets would maintain the set of running containers for pods on their nodes based on the cluster's last desired state. For the most part, this worked as expected.

However, when containers crashed in pods that had set environment values using `configMapKeyRef`, kubelet logs reported `failed to StartContainer` because it was unable to re-retrieve the referenced ConfigMap from the apiserver. Containers that referenced ConfigMaps using volume mounts did not suffer from this failure, since the mounted snapshot of the ConfigMap was stored on the node disk under `/var/lib/kubelet/pods/$POD/volumes/kubernetes.io~configmap`.

**What you expected to happen**: When a pod is created on a node, the complete resources required for kubelet to (re)start its containers should be staged on the node. I would expect access to the off-box control plane be required only to report and discover cluster state changes. 

**How to reproduce it** (as minimally and precisely as possible):
1. Create a pod with a container definition that sets an environment variable using `valueFrom: { configMapKeyRef: {...} }`.
1. Once the pod is running on a node, disable access to the apiserver from that node (for example, set the apiserver hostname in /etc/hosts to an unreachable address).
1. Assuming a Docker container runtime, use `docker ps` to identify the application container started for the pod by kubelet, then `docker stop` that container. Kubelet should fail to start a replacement container.

**Comment by jfoy** [comment]
@kubernetes/sig-node-misc

**Comment by dims** [comment]
cc @jbeda -Joe,  just saw your tweet and remembered this issue (https://twitter.com/jbeda/status/872500237079764992)

**Comment by jfoy** [comment]
As far as I know, this is still a live problem.

/remove-lifecycle stale

**Comment by jfoy** [comment]
I'm unable to repro this issue under k8s 1.21.2 but I also don't find any explicit mention of a fix in the changelog.
