### ISSUE TITLE
Move Deployment cleanup at the end of a rollout

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#46932]
We moved the RS cleanup at the start of a rollout to unblock users who were getting blocked by hash collisions. Now that the hashing collision avoidance mechanism is in place, we can restore the cleanup to run at the end of a rollout.

Essentially, we need to revert https://github.com/kubernetes/kubernetes/pull/40081.

**Comment by kargakis** [comment]
@kubernetes/sig-apps-misc

**Comment by krmayankk** [comment]
@kargakis is there a plan to get  rid of the hashing altogether ?

**Comment by janetkuo** [comment]
@krmayankk No, hash is required for generating idempotent ReplicaSet names and unique labels
