### ISSUE TITLE
DaemonsetController can't feel it when node has more resources, e.g. other Pod exits

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#46935]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
master branch

**What happened**:
This's a follow up of #45628, there's a case that: a node does not have enough cpu or memory resource to create the pod of ds, later I delete pods on it, and it satisfy the request now, but the ds controller could not feel it.

**Comment by k82cn** [comment]
One option is similar with `addNode`, get all DS and check it; the performance is a concern: pod deletion is more frequent than node addition.

I'm thinking to handle it by #42002; let scheduler help to place the Pod when there's enough resource.

**Comment by kargakis** [comment]
@kubernetes/sig-apps-bugs @kubernetes/sig-scheduling-bugs

**Comment by janetkuo** [comment]
We'd love to see this fixed in 1.8. It's unlikely we'll have #42002 done in 1.8, so @k82cn would you be willing to fix it with the naive solution first?

**Comment by k82cn** [comment]
@janetkuo , sure, np. let's fix it before #42002.

**Comment by lukaszo** [comment]
I've always thought that there is some kind of periodic resync which checks all daemons and should handle this issue. It's even mentioned in some code comments.
Does it even work? Or how does it work?

**Comment by enisoc** [comment]
@lukaszo wrote:
> I've always thought that there is some kind of periodic resync [...]

I thought so too, but as far as I can tell, the default period is 12 hours and the randomized value could be up to 2x that, so we can't really rely on it for this kind of problem.

https://github.com/kubernetes/kubernetes/blob/b66be98174fb0257619c218f51246511d6160beb/cmd/kube-controller-manager/app/options/options.go#L84

**Comment by k82cn** [comment]
@lukaszo , @enisoc  , I think this's for reflector sync. In DaemonSet, there are `runWorker`s running to sync up DaemonSet; but it's triggered by event, e.g. AddNode, DaemonSet's Pod deleted. If any misunderstanding, please correct me :).

**Comment by enisoc** [comment]
As far as I can tell, the `min-resync-period` flag (default 12hrs) ends up being used as the `defaultEventHandlerResyncPeriod`, which is the resync period you get if you use `AddEventHandler()` (like [DaemonSet](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemoncontroller.go?utf8=%E2%9C%93#L150) does) instead of `AddEventHandlerWithResyncPeriod()` (like [StatefulSet](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/statefulset/stateful_set.go?utf8=%E2%9C%93#L121) does).

So I think this explains why DaemonSet does not appear to resync. It's using the default period which is a random value between 12h and 24h.

**Comment by kargakis** [comment]
Eventually, statefulsets should also be pushed to use AddEventHandler. We don't want controller loops to depend on tight resync intervals. The resource handlers on secondary caches are paramount for complementing the resync logic of the main controllers, eg. once a Node has more resources (status change on the Node?), a watch event in the secondary (node) cache of the DS controller should trigger a resync of all the DaemonSets that want to run on that node.

**Comment by k82cn** [comment]
> once a Node has more resources (status change on the Node?)

nop, it dependents on pod's event (e.g. add, update, delete) :(. It avoid too many info in Node object. In scheduler, it cache those info in `schedulercache`; and uses those info by `PodFitResource` predicate.

In DaemonSet's `deletePod` handler, we only care about the DS pod and enqueue DS; if other pod in Node is deleted, DS controller will not do anything.
