### ISSUE TITLE
Consider moving rollback out of the Deployment controller

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#46934]
Currently, in order for a Deployment to rollback:
i. a user needs to set `d.spec.rollbackTo.revision`
ii. the controller notices the populated rollback spec and it updates the pod template of the deployment plus it cleans up the `rollbackTo` field.

Step ii. is breaking the declarative model for the Deployment API. We should consider dropping `rollbackTo` from the spec and instead either 1. make the `deployments/{name}/rollback` endpoint perform the rollback or 2. have the rollback endpoint simply return a dry-run of the rolled back Deployment which then clients can PUT.

If we do 1. we need an option for dry-run, 2. is what we do in OpenShift.

@kubernetes/sig-apps-api-reviews 

ps. sparked by the decision to have rollback client-side initially for DaemonSets and StatefulSets.

**Comment by krmayankk** [comment]
how would automatic rollback work in either of these options ?

**Comment by kargakis** [comment]
@krmayankk automatic rollback is a different issue and shouldn't be affected by this one.

**Comment by kargakis** [comment]
Worth noting user confusion: https://github.com/kubernetes/kubernetes/issues/47238#issuecomment-308256151

**Comment by janetkuo** [comment]
Server side rollback isn't implement yet in StatefulSet and DaemonSet. The design of deployment rollback will eventually be consistent with other controllers. We should have a decision before GA.

**Comment by janetkuo** [comment]
Current plan:

* Deprecate this field in extensions/v1beta1 Deployment
* We won't support /rollback endpoint for apps/v1beta2 Deployment 
  * We will add an `deprecated.rollback.to=<revision>` annotation (tentative name) for conversion between apps/v1beta2 and extensions/v1beta1 Deployment
* Deployment controller will continue supporting rollback behavior for backward compatibility

**Comment by krmayankk** [comment]
@janetkuo which option are we going with for rollback as proposed by @kargakis

**Comment by bgrant0607** [comment]
I am in favor of moving rollback out of the Deployment controller and out of the DeploymentSpec. I'm not in favor of moving it to the apiserver. It can be done in an external controller. I just approved #49340.

**Comment by kargakis** [comment]
@janetkuo I guess this falls through to 1.9?

**Comment by kow3ns** [comment]
@janetkou do we want to keep this open until deprecation is complete?
