### ISSUE TITLE
deletePod handler in the deployment controller should not set owner refs

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#46933]
IMO it feels like a bad practice to have mutating resource handlers. The deletePod handler is used for queueing a Recreate deployment once it has no pods running. It should merely look at the ReplicaSets that have owner refs as opposed to using dc.getReplicaSetsForDeployment. The orphaning/adoption dance is already happening inside the reconcilation loop.

@kubernetes/sig-apps-misc

**Comment by boingram** [comment]
I'd like to work on this

**Comment by kargakis** [comment]
@boingram feel free to grab it. I can't assign the issue to you so I'll add myself; ping me on the PR when you have one.
