### ISSUE TITLE
Additional StatefulSet update e2e testing

### ISSUE THREAD

**Issue by kow3ns** [kubernetes/kubernetes#46942]
StatefulSet requires additional e2e testing

1. Rollback to a specific version
2. Kill Pods during update and rollback and ensure they are created at the correct revision
3. The above, but in the partitioned case

**Comment by kow3ns** [comment]
@kubernetes/sig-apps-misc

**Comment by kow3ns** [comment]
\assign kow3ns

**Comment by marun** [comment]
Assuming this shouldn't block 1.7, moving to 1.8.

**Comment by kow3ns** [comment]
@marun this goes in 1.7 the PR is issued.

**Comment by smarterclayton** [comment]
I think it's important to have this in 1.7 to give us signal on SS (which are important enough to end users now that breaking them is probably a release blocker)

**Comment by danpaik** [comment]
Ok, I'll work on getting this moved to 1.7.

**Comment by grodrigues3** [comment]
@dchen1107 this is additional e2e testing for StatefulSets.  Verifying that it's okay to go in during code freeze?
