### ISSUE TITLE
Add gating to API Compression handler 

### ISSUE THREAD

**Issue by ilackarms** [kubernetes/kubernetes#46963]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

PR #45666 adds gzip and flate compression to GET and LIST requests on API Objects. This issue is a feature request to add a feature gate to opt out of compression. (https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go#L117)

**Comment by lavalamp** [comment]
Is this important for 1.7? Why? Is there an exception filed?
