### ISSUE TITLE
apiserver etcd v3 client does not close connections to dead etcd node

### ISSUE THREAD

**Issue by macpoint** [kubernetes/kubernetes#46964]
Hi,

running 1.6.4 on etcd 3.0.17 in the following setup:

- 3 etcd nodes (bootstrapped according to the [clustering guide](https://coreos.com/etcd/docs/latest/op-guide/clustering.html))
- 9 kubernetes cluster nodes all of them running kube-apiserver (--apiserver-count=9) with --bind-address to local kube-apiserver instance. All instances pointing to the same etcd cluster (--etcd-servers=http://IP1:4001,http://IP2:4001,http://IP3:4001)

I tried to simulate 1 etcd node crash by simply turing off one of the machines. Result:
- timeouts running kubectl (get nodes, get pods) commands
- lots of these error messages in kube-apiserver logs: "status.go:62] apiserver received an error that is not an metav1.Status: http: Handler timeout"
- ETCD correctly reports unhealthy node, but healthy cluster

Inspecting netstat shows lots of ESTABLISHED connections to the dead etcd server, port 4001 - these connections are cleared only by restarting the kube-apiserver(s).

Workarounds:
- Switching back to etcd 2.2.1 and using --storage-backend=etcd2 ... ESTABLISHED connections are cleared within several seconds
- Leaving etcd 3.0.17 and using --storage-backend=etcd2 ... ESTABLISHED connections are cleared within several seconds

In both above cases kubectl shows expected results. The dead node is evicted (NotReady), other nodes & pods are in tact.

I noticed that [etcd v2](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd2.go) client contains TCP KeepAlive timeout, while [etcd v3](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go) client does not. Could this be related to the described scenario?

**Kubernetes version** 
`Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **OS**:
NAME="Oracle Linux Server"
VERSION="6.7"
ID="ol"
VERSION_ID="6.7"
PRETTY_NAME="Oracle Linux Server 6.7"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:6:7"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"
ORACLE_BUGZILLA_PRODUCT="Oracle Linux 6"
ORACLE_BUGZILLA_PRODUCT_VERSION=6.7
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=6.7
- **Kernel** 
`Linux ngi-test-mgmt 4.1.12-94.3.4.el6uek.x86_64 #2 SMP Mon May 15 14:10:25 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by xiangpengzhao** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by sakshamsharma** [comment]
This seems to depend on an issue with etcd, there is no option for a KeepAlive I believe. I've sent a PR, can fix this once that gets merged.

[PR on etcd](https://github.com/coreos/etcd/pull/8199)

**Comment by sakshamsharma** [comment]
The mentioned PR has been merged. We may need to wait for an etcd release / update the dependency on etcd for us to be able to fix this in Kubernetes.

**Comment by sakshamsharma** [comment]
Had a look at the current CHANGELOG on etcd. The fix for this issue is in master, and will be released in etcd-3.3.0.

Here is the [changelog](https://github.com/coreos/etcd/blob/master/CHANGELOG.md) which shows the fix has been merged into the [pre-release 3.3.0-rc.0](https://github.com/coreos/etcd/blob/master/CHANGELOG.md#v330-rc0-2017-12-20).

Kubernetes is currently on 3.1.10 it appears (according to [this PR](https://github.com/kubernetes/kubernetes/pull/49572)) and upgrade to 3.2.10 seems underway [here](https://github.com/kubernetes/kubernetes/issues/56438).
