### ISSUE TITLE
StatefulSet Partitioned strategy vs parameterized Roll out strategy 

### ISSUE THREAD

**Issue by kow3ns** [kubernetes/kubernetes#46975]
Prior to 1.7 release we should decide on keeping the PartitionedStatefulSetStrategy documented in the design for StatefulSet update, or, instead, adding an optional ordinal parameter to the RollingUpdateStatefulSetStrategy. The deviation is described below.

```golang
// StatefulSetUpdateStrategy indicates the strategy that the StatefulSet
// controller will use to perform updates. It includes any additional parameters
// necessary to perform the update for the indicated strategy.
type StatefulSetUpdateStrategy struct {
	// Type indicates the type of the StatefulSetUpdateStrategy.
	Type StatefulSetUpdateStrategyType `json:"type,omitempty" protobuf:"bytes,1,opt,name=type,casttype=StatefulSetStrategyType"`
	// Partition is used to communicate the optional ordinal at which to partition
	// the StatefulSet when Type is RollingUpdateStatefulSetStrategyType. This
	// value may only be set when the Type is RollingUpdateStatefulSetStrategyType,
	// and it must be nil otherwise.
	Partition *RollingUpdatePartition `json:"partition,omitempty" protobuf:"bytes,2,opt,name=partition"`
}

// RollingUpdatePartition is used to indicate a partition in the StatefulSet during a Rolling Update.
type RollingUpdatePartition struct {
	// Ordinal indicates the ordinal at which the StatefulSet should be
	// partitioned. All Pods with an ordinal greater than or equal to partition will receive the update.
	Ordinal int32 `json:"ordinal" protobuf:"varint,1,opt,name=ordinal"`
}
```

**Comment by kow3ns** [comment]
@kubernetes/sig-apps-api-reviews 
@kargakis 
@smarterclayton 
@janetkuo

**Comment by smarterclayton** [comment]
I'd probably lean (based on other conversations with @kargakis around how we would leverage partition from higher level controllers) towards including it in rolling.  I like having tools that let someone find the knobs close at hand for both manual update and higher level primitives.

**Comment by kargakis** [comment]
I see more pros than cons for having this as an option in rollingUpdate. Summarizing comments from elsewhere:

1. Validation is going to be easier - having a separate strategy pushes a burden to clients for crafting patches.
2. Adding new strategies will be easier in the future; with a separate strategy, we'll likely need to duplicate the strategies (xStrategy + xPartitionedStrategy). Makes 1. even harder.
3. In the next API version we are going to default the strategy type to RollingUpdate. It will be more convenient for higher-level orchestrators to simply manipulate the ordinal option as opposed to needing to change the strategy to Partitioned if users want to take over the rollout process of a StatefulSet. Will be harder because of 1.

**Comment by kargakis** [comment]
cc: @tnozicka @mfojtik

**Comment by kow3ns** [comment]
I have no objection to the modification. Are we agreed modification proposed in the comment above is sufficient?

**Comment by kargakis** [comment]
Structure looks fine, I would suggest `rollingUpdate` instead of `partition` for the field name since it's consistent with D/DS and it allows us to add more rolling parameters in the future.

**Comment by kow3ns** [comment]
Think of what the manifest will look like though
```yaml
updateStrategy:
  type: RollingUpdate
  partition:
     ordinal: <ordinal>
```

In the case where no partition is specified it looks like

```yaml
updateStrategy:
  type: RollingUpdate
```

Can you give me a sample of what you are proposing?

**Comment by kargakis** [comment]
```yaml
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
     ordinal: <ordinal>
```
I don't feel strong but it's consistent with the rest controllers.

**Comment by mfojtik** [comment]
+1 for consistency

**Comment by kow3ns** [comment]
```yaml
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    partitionl: <ordinal>
```
?

**Comment by kargakis** [comment]
SGTM
