### ISSUE TITLE
federation: errors in cleaning the load balancers in federation e2e tests.

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/kubernetes#46976]
In federation tests, if we observe the build logs. we see cleaning up LoadBalancer from cloud provider seems not working.
```
I0605 06:12:31.969] Jun  5 05:57:11.859: INFO: Failed to delete cloud provider resources for service "federated-service" in namespace "e2e-tests-federated-service-86x1k", in cluster "federation-e2e-gce-us-central1-a": error getting cluster ID a7b70c85e49ee11e7aa3042010a80000: GCECloud.ClusterID is not ready. Call Initialize() before using.
I0605 06:12:31.969] Jun  5 05:57:13.859: INFO: Failed to delete cloud provider resources for service "federated-service" in namespace "e2e-tests-federated-service-86x1k", in cluster "federation-e2e-gce-us-central1-a": error getting cluster ID a7b70c85e49ee11e7aa3042010a80000: GCECloud.ClusterID is not ready. Call Initialize() before using.
```
It has 2 effects:
- delays the tests by waiting to delete but always returns error. so we waste like 5 minutes.
- maybe we are leaking the LoadBalancer in the project.

@madhusudancs @kubernetes/sig-federation-bugs

**Comment by shashidharatd** [comment]
we can see these errors in every build. but just for reference here are some build logs
- https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-federation/4195/build-log.txt
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45666/pull-kubernetes-federation-e2e-gce/8943/?log#log

**Comment by MrHohn** [comment]
cc @nicksardo

**Comment by MrHohn** [comment]
All the errors in logs are `GCECloud.ClusterID is not ready. Call Initialize() before using`. It doesn't necessarily indicate we are leaking resource, just now we must have clusterID initialized before calling EnsureLoadBalancerDeleted().

Would be better to not call this function directly in e2e test :)

**Comment by nicksardo** [comment]
Federation cleanup should use the same implementation as non-federated e2e test:
https://github.com/kubernetes/kubernetes/blob/3837d9519190069c44a453c145869e1fced52f23/test/e2e/framework/service_util.go#L1303-L1313

**Comment by shashidharatd** [comment]
@nicksardo,  `CleanupServiceGCEResources` function looks like only specific to GCE. in future we would run the e2e tests in AWS too. it would be better to use generic functions if any.

**Comment by shashidharatd** [comment]
@MrHohn, using [EnsureLoadBalancerResourcesDeleted()](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L4651) is working for us. here is the test logs https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46979/pull-kubernetes-federation-e2e-gce/9252/

**Comment by MrHohn** [comment]
@shashidharatd EnsureLoadBalancerResourcesDeleted() actually cleans up nothing, it only lists forwarding rules and probably logging :)
