### ISSUE TITLE
GLBC controller is accessing the API through the insecure port

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#46983]
The GLBC controller is accessing the insecure port on the master, which means it skips authentication. This is an issue for audit logging, as it shows up as `user="system:insecured"` rather than a proper service account identity.

To fix this, the pod should be configured with a service account identity, and the `--running-in-cluster` flag should be set to true so that the kubernetes client is configured to use the service account.

/cc @kubernetes/sig-auth-bugs

**Comment by nicksardo** [comment]
This will likely surface in a 1.7 patch.

**Comment by marun** [comment]
Assuming this should not be blocking 1.7.

**Comment by nicksardo** [comment]
Correct. Thank you @marun

**Comment by liggitt** [comment]
@nicksardo any progress on this or should this move to 1.9 ?

**Comment by nicksardo** [comment]
Can move to 1.9 @liggitt

**Comment by ericchiang** [comment]
/remove-lifecycle rotten
/lifecycle frozen 

The manifest in `cluster/gce/manifests/glbc.manifests` still needs updating.

**Comment by nicksardo** [comment]
Needs a lot more than that.

**Comment by tallclair** [comment]
/assign @dekkagaijin 

Is this already fixed?

**Comment by dekkagaijin** [comment]
Yup, fixed
