### ISSUE TITLE
Losing kubemark master logs if failing in e2e tests

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#46980]
We've been losing the kubemark master logs for almost all the last few runs of kubemark-scale in case of failure during `run-e2e-tests.sh` step.
For eg:
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/455/artifacts/
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/454/artifacts/
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/444/artifacts/
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/441/artifacts/ (440, 439, 438, ...)

We seem to have some regression(s) (https://github.com/kubernetes/kubernetes/issues/46851) and missing logs hurts.
The AfterSuite action in e2e framework should dump the logs after running the suite (ref: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/e2e.go#L270) even if it failed, and IIRC that was the case before. But now it just seems to run stop-kubemark.sh right after failing e2e tests. It runs DumpClusterLogs later but that gets logs from the base cluster.

cc @kubernetes/test-infra-maintainers @fejta @wojtek-t @gmarek

**Comment by shyamjvs** [comment]
@kubernetes/sig-testing-bugs

**Comment by gmarek** [comment]
@spxtr @fejta - do you think someone from test-infra may take a look?

**Comment by shyamjvs** [comment]
I believe this issue has been resolved now, with kubemark master logs available even during test failures. IIRC it is due to a bunch of my kubetest changes around kubemark testing.

We can reopen if we see this again.
