### ISSUE TITLE
Federation: kubectl rollout status with Federated Deployment 

### ISSUE THREAD

**Issue by bspradling8** [kubernetes/kubernetes#46994]
It looks like currently with Federated Deployments, the federated API server will get stuck at waiting with 0 out of `n`. I can only assume that this occurs because the federationa API server knows about the deployment and how many replicas there should be but isn't the one responsible for running the pods therefore stuck at 0. Is there a plan to support this functionality in Federated Deployments?

**Comment by bspradling8** [comment]
@kubernetes/sig-federation-misc

**Comment by perotinus** [comment]
@bspradling8 There was a design in-flight to better support rollbacks in Federation, though I don't think it would exactly fix your issue (https://github.com/mwielgus/community/blob/d7651487409214e60123766382779bafc0aeb72b/contributors/design-proposals/federated-deployment.md)

Having better support for Federated deployment status has been something we've wanted to do for some time, but we haven't yet coalesced around a strategy for how to report that status back to the user. In the case of rollouts, we may be able to do something, but I don't believe that anyone has thought specifically about providing this status for the rollout command.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#18.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
