### ISSUE TITLE
kubelet fails to admit containers with valid securitycontexts

### ISSUE THREAD

**Issue by Q-Lee** [kubernetes/kubernetes#46996]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kubelet securitycontext

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.7.0-beta/1.8.0 (HEAD)

**Environment**:
- **Cloud provider or hardware configuration**: gce
- **OS** (e.g. from /etc/os-release): gci
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**: docker runtime (rkt seems to have a different code path, but I haven't checked it)

**What happened**: containers could not run as root when "RunAsNonRoot=false"

**What you expected to happen**: containers could run as root

**How to reproduce it** (as minimally and precisely as possible): add a securitycontext to a container, don't set privileged, do set RunAsNonRoot, use an image that runs as root. The PodSecurityPolicy admission controller will always set a securitycontext if it's not specified, and cause this to be hit more often.

**Anything else we need to know**: The bug is in the checks here:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/security_context.go#L73

I have a fix in https://github.com/kubernetes/kubernetes/pull/46064 but that going in depends on an extension being granted. We may want to fix the bug regardless.

**Comment by yujuhong** [comment]
I'll send a fix shortly.
