### ISSUE TITLE
Swagger represents all maps as type "any"

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#4700]
"labels": "v1beta3.ObjectMeta.labels",

Not sure what that means...

**Comment by bgrant0607** [comment]
cc @nikhiljindal

**Comment by bgrant0607** [comment]
All maps currently show as type "any", which I think was done as a workaround for undefined custom types (#2971).

**Comment by wing328** [comment]
FYI. In the future, when the spec is upgraded to 2.0, the map can be documented using `additionalProperties`, e.g. string to model mapping
```
{
  "type": "object",
  "additionalProperties": {
    "$ref": "#/definitions/ComplexModel"
  }
}
```
Ref: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#model-with-mapdictionary-properties

**Comment by wing328** [comment]
@thockin @nikhiljindal Before the spec gets upgraded to OpenAPI/Swagger spec 2.0, can we replace `"type": "any"` with `"type": "object"` for the time being so as to avoid compilation error related to missing model "Any" ?

**Comment by nikhiljindal** [comment]
Does "type": "object" have any special meaning?
I think we chose "type":"any" arbitrarily to represent custom types.
It should be fine to change it.

**Comment by wing328** [comment]
`"type": "object"` means arbitrary JSON.

**Comment by nikhiljindal** [comment]
https://github.com/emicklei/go-restful/pull/270 replaces "any" by "object".
Thanks @wing328

**Comment by mbohlool** [comment]
Maps are represented correctly in swagger 2.0/OpenAPI now.
