### ISSUE TITLE
Add `CriticalAddonsOnly` toleration for both npd and fluentd.

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#47015]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
master

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Currently, the YAML template for both npd and fluentd service do not have `CriticalAddonsOnly` toleration, this may cause the daemonset cannot be started on a node if it is already selected to run `critical pods`, it is better to add `CriticalAddonsOnly` toleration for both npd and fluentd so as to make sure those daemonset can run on the nodes even if it is for `critical pod`.

All other daemonset in kubernetes also have such tolerations.

**What you expected to happen**:
Should add `CriticalAddonsOnly` toleration for both npd and fluentd.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by kargakis** [comment]
@kubernetes/sig-cluster-lifecycle-misc

**Comment by luxas** [comment]
@gyliu513 You sent PRs to fix this, right?
Can this be closed now?

**Comment by gyliu513** [comment]
@luxas the PR was not committed yet, can you help lgtm and approve it? https://github.com/kubernetes/kubernetes/pull/46748
