### ISSUE TITLE
Need e2e tests for flex volume

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#47010]
Flex volumes keeps breaking every release.  We need some basic tests and add it to the alpha features suite.

**Comment by liggitt** [comment]
@derekwaynecarr

**Comment by wongma7** [comment]
@verult have you made any progress on this? Am looking to help work on

**Comment by verult** [comment]
@wongma7 I haven't had a chance to work on this unfortunately. It would be awesome if you could look into it, thank you!
