### ISSUE TITLE
Question: support scheduling Pods according to node resources change in real-time

### ISSUE THREAD

**Issue by jianzhangbjz** [kubernetes/kubernetes#47025]
Hey guys,

AFAIK,  the `kubelet` reports the status/resources of node at a regular interval(default 10s).
Although the `cadvisor` could aware the resource utilization in real-time, but not involved in the scheduling, right? So, this is an issue, why not support scheduling Pods according to node resources change in real-time? Or I misunderstood?

**Comment by k82cn** [comment]
please also cc @bsalamat  :)

Here's my understand: 1. there's a time-windows between bind & node status update, so scheduler cache (assumed) those Pods; 2. we prefer to keep Node object as small as possible

**Comment by bsalamat** [comment]
@jianzhangbjz Scheduler does resource accounting and record keeping in real-time on its own side and does not rely on Kubelet periodic reports to update its records. Scheduler updates the total amount of resources requested on a node as soon as it assigns a pod to a node. Scheduler uses this updated records to make scheduling decisions.

**Comment by jianzhangbjz** [comment]
@k82cn @bsalamat Thanks! But, if we release some resources(like delete pods), the scheduler cache how to update in real-time? AFAIK, the delete action don't involve the scheduler, right? Or something else I missed?

**Comment by k82cn** [comment]
If pod is deleted, scheduler will get DELETE notification from apiserver and update cache accordingly.

**Comment by jianzhangbjz** [comment]
@k82cn Thanks for your patience to answer. From the scheduler logs, I didn't find the notification, maybe need to config `scheduler --v=10` to catch the notification or I need to read the related code. I will have a try. :)
kube-apiserver.INFO:
```
I0607 08:32:49.872422   95154 wrap.go:75] DELETE /api/v1/namespaces/default/pods/gpu-allocation-topology-3938612321-jhhfk: (13.221411ms) 200 [[kube-controller-manager/v1.6.0 (linux/ppc64le) kubernetes      /$Format/replicaset-controller] 9.2.133.181:57816]
I0607 08:32:49.873927   95154 wrap.go:75] PUT /apis/extensions/v1beta1/namespaces/default/deployments/gpu-allocation-topology/status: (607.993碌s) 409 [[kube-controller-manager/v1.6.0 (linux/ppc64le)       ubernetes/$Format/deployment-controller] 9.2.133.181:57760]
```
kubelet.INFO:
```
I0607 08:32:49.744017   95277 generic.go:182] GenericPLEG: Relisting
I0607 08:32:49.872599   95277 config.go:294] Setting pods for source api
I0607 08:32:49.873078   95277 kubelet.go:1825] SyncLoop (DELETE, "api"): "gpu-allocation-topology-3938612321-jhhfk_default(1d9740d8-4b60-11e7-a9a2-98be945cf704)"
```
kube-scheduler.INFO:
```
I0607 08:32:48.197147   95205 leaderelection.go:204] succesfully renewed lease kube-system/kube-scheduler
I0607 08:32:50.200256   95205 leaderelection.go:204] succesfully renewed lease kube-system/kube-scheduler
```

**Comment by k82cn** [comment]
Please refer to this code https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L154 , and check the log if necessary. This code handled running Pods, for the pending Pods, it will be removed from client-go's cache.

**Comment by jianzhangbjz** [comment]
@k82cn Thanks a lot. :)

**Comment by resouer** [comment]
Close this since already been properly answered.
