### ISSUE TITLE
pull-kubernetes-federation-e2e-gce: federation-up.sh fails due to failing to pull image

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/kubernetes#47032]
A new issue is introduced in pull-kubernetes-federation-e2e-gce, [build-9117](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46979/pull-kubernetes-federation-e2e-gce/9117/?log#log) onwards, where in the failure message is as below
```
W0605 21:18:36.221] Error from server (BadRequest): container "apiserver" in pod "e2e-f8n-agent-pr-93-0-apiserver-2905553699-lg7b8" is waiting to start: trying and failing to pull image
```
After analyzing, i find that the image which is built and pushed is different than the one used for bringing up federation.
What caused this change is yet to be ascertained. most probably the introduction of `KUBERNETES_RELEASE` env variable in the pull job by test-infra.

/cc @kubernetes/sig-federation-bugs

**Comment by shashidharatd** [comment]
Analyzed further and find that the extract strategy for pull-kubernetes-federation-e2e-gce was changed to `ci/latest` from `local` which is causing the issue. This PR in test-infra introduced the issue. pull-kubernetes-federation-e2e-gce

/cc @fejta, @madhusudancs @krzyzacy

**Comment by quinton-hoole** [comment]
Closing as #2977 has merged and been demonstrated to fix this issue.
