### ISSUE TITLE
Register unversioned types in each scheme

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#47030]
We have moved to non-global schema in a number of places in 1.6 and 1.7. It is easy to forget registering the unversioned types like `metav1.Status`, leading to encoding errors in error cases.

The registration of the unversioned types should be automatic as for the `*Options` types, i.e. in `metav1. AddToGroupVersion`.

**Comment by dims** [comment]
@sttts do we need to close out this issue? (since referenced PR has merged)

**Comment by sttts** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/46112
