### ISSUE TITLE
Azure cloud provider needs exponential backoff capability to mitigate query quota overshoot in the Azure Resource Manager API

### ISSUE THREAD

**Issue by jdumars** [kubernetes/kubernetes#47048]
**NOTE**: This issue is being filed as the upstream version of [Azure/acs-engine#635](https://github.com/Azure/acs-engine/issues/635) to meet the new requirement of correlation between a 1.7 milestone item ([pull request 46660](https://github.com/kubernetes/kubernetes/pull/46660)) and an issue.  The SIG label for this should be sig-azure once created.  

**Issue summary:**
The calls from the Kubernetes control plane and nodes to Azure Resource Manager in larger clusters can exhaust the account limit of API calls to ARM, which in turn affects all of the resources in the group.  This is a P0 impact on our ACS customers that hit the threshold.

**The fix:**
Implement a tunable backoff and rate limiting capability for ARM calls in the Azure cloud provider code.  See: [pull request 46660](https://github.com/kubernetes/kubernetes/pull/46660)

cc: @idvoretskyi 
cc: @brendandburns

**Comment by jdumars** [comment]
@idvoretskyi

**Comment by idvoretskyi** [comment]
Hi @jdumars.

I've proactively created the sig/azure label and manually labeled this item.
