### ISSUE TITLE
kubectl prints durations rounded down; can mislead

### ISSUE THREAD

**Issue by bboreham** [kubernetes/kubernetes#47047]
**BUG REPORT**

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:
The timestamps reported by `kubectl` are rounded down, e.g. 47 hours is reported as "1d".

**What you expected to happen**:
Round to nearest, i.e. 47 hours displays as "2d"

**How to reproduce it** (as minimally and precisely as possible):
```
$ kubectl run foo --image=gcr.io/google_containers/pause-amd64:3.0; sleep 110; kubectl get pods 
deployment "foo" created
NAME                       READY     STATUS    RESTARTS   AGE
foo-2655446836-7xk2l       1/1       Running   0          1m
```
After 110 seconds we are told the pod is 1 minute old.

**Anything else we need to know**:
Believe it is [this code](https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/common.go#L24-L41)

**Comment by shiywang** [comment]
similar to this https://github.com/kubernetes/kubernetes/issues/41741, and currently everything is shortened to the largest unit

**Comment by xiangpengzhao** [comment]
I remember in one PR review I suggested to fix this but sadly my comment was ignored. IMO, we can show `AGE` with two units, e.g. `1m50s`, `3h45m`, `5d19h`, etc. That would be more accurate.

**Comment by smarterclayton** [comment]
We should certainly try to be within 5% or so of the actual value.
