### ISSUE TITLE
Federated sync controller e2e tests are chosen and run at random

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#47059]
We occasionally see a mismatch between the sync controller e2e tests that are run and their titles. Since Ginkgo is a declarative framework and these e2es are setup in an imperative fashion using for-loops, we initially thought this was just a test title issue due to the mismatch between the idioms.

But yesterday while debugging Federated DaemonSet e2e failures, we noticed that it is not just the titles that go out of sync from the tests, but the tests themselves always don't do what they are expected to. The behavior is somewhat random. For example take this CI test run: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-federation/4207?log#log.

The titles for 3 sync controller tests have the right object names, i.e. "configmap", "daemonsets" and "secrets", but all the three instances are testing secrets instead of testing the the respective objects.

/sig federation

/assign @marun @madhusudancs 

cc @shashidharatd @perotinus @csbell @nikhiljindal

**Comment by csbell** [comment]
On Tue, Jun 6, 2017 at 10:25 AM, Madhusudan.C.S <notifications@github.com>
wrote:
>
> The titles for 3 sync controller tests have the right object names, i.e.
> "configmap", "daemonsets" and "secrets", but all the three instances are
> testing secrets instead of testing the the respective objects.
>
Three secret runs in a row would definitely allow a daemonset regression to
slip in. :-/

**Comment by csbell** [comment]
Fixed by #47061
