### ISSUE TITLE
Stackdriver Logging e2e tests are implemented incorrectly

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#47069]
Read method from the Stackdriver Logging API, used in these tests is slow (O(1) QPS), sequential and quotas for this API is low, b/c the method was not designed to use with automated tools. Instead, recommended way for using Stackdriver Logging API is creating a PubSub sink and then reading from the PubSub topic, this way tests will be much faster and there will be no issues with quotas.

Related issue: https://github.com/kubernetes/kubernetes/issues/43442

**Comment by marun** [comment]
@crassirostris Should this be blocking 1.7?

**Comment by crassirostris** [comment]
@marun Should be fixed very soon
