### ISSUE TITLE
HPA controller sends unecessary updates

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/kubernetes#47077]
**BUG**: the HPA controller submits updates every update interval, even if nothing has changed.  In clusters with large numbers of HPAs, as well as clusters with smaller HPA sync periods, this can cause an unnecessarily high volume of writes.

The HPA controller should only send updates if it actually has a change to the HPA status object.

**Comment by DirectXMan12** [comment]
cc @kubernetes/sig-autoscaling-bugs @derekwaynecarr

**Comment by fgrzadkowski** [comment]
@DirectXMan12 Aren't we always updating 'observedGeneration' field?

**Comment by DirectXMan12** [comment]
@fgrzadkowski we don't actually seem to do anything with that field.  There's nothing in the HPA controller about it.
