### ISSUE TITLE
PodSecurityPolicy ignores and overwrites RunAsNonRoot

### ISSUE THREAD

**Issue by Q-Lee** [kubernetes/kubernetes#47071]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): PodSecurityPolicy RunAsNonRoot

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.7.0-beta, 1.8.0 (HEAD)

**Environment**: Enable PodSecurityPolicy
- **Cloud provider or hardware configuration**: gce, probably any
- **OS** (e.g. from /etc/os-release): gci
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**: The PSP admission controller ignores the specified RunAsNonRoot, and overwrites it.

**What you expected to happen**: the admission controller is not supposed to overwrite user specified fields in the podsecuritycontext and securitycontext.

**How to reproduce it** (as minimally and precisely as possible): enable psp, and create a pod with [only] RunAsNonRoot=false specified in a securitycontext.

**Anything else we need to know**:

**Comment by Q-Lee** [comment]
@liggitt there are actually 2 bugs here.

user/nonroot.go fails to properly restrict this field when matching against a PSP, which is a latent bug as long as we overwrite the value anyway.

provider.go overwrites the user-supplied setting for the securitycontext/podsecuritycontext. I suspect the best fix will be to use the API's deep copy function. We are also doing a couple other sketchy things: assigning the "copy" built-in as a variable, and creating an "sc" shadow variable.

**Comment by Q-Lee** [comment]
I have a half fix in #46064 but we should probably fix it in a separate PR, because we may want to patch 1.6.

**Comment by liggitt** [comment]
the effect is that PSP can overly restrict a pod that wanted to run as root, but expressed that as `runAsNonRoot: false` instead of `runAsUser: 0`

since the workaround is easy (set `runAsUser: 0` in your pod if you want to run as root), I don't anticipate backporting the fix.

**Comment by Q-Lee** [comment]
SGTM. I'll try and get the unit tests in after the GKE summit (on friday).
