### ISSUE TITLE
'kubectl get' output does not have columns aligned properly.

### ISSUE THREAD

**Issue by droot** [kubernetes/kubernetes#47093]
---
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.7.alpha (pre-releases)

**What happened**:
'kubectl get' output does not have columns aligned properly. This got introduced as part of this change PR #40848 

**What you expected to happen**:
Output of kubectl get should have all the columns aligned as in previous releases.

**How to reproduce it** (as minimally and precisely as possible):
Run 'kubectl get' with multiple rows in the output on 1.7 prereleases

**Anything else we need to know**:
There is PR #47013 which fixes this.

**Comment by mengqiy** [comment]
Closing in favor of #47013.
/close
