### ISSUE TITLE
[FEATURE]: non-namespace-scoped TPR data support

### ISSUE THREAD

**Issue by ChenLingPeng** [kubernetes/kubernetes#47100]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
TPR, non-namespace-scoped

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

---

After create a kind of TPR, this new kind resource is namespace-scoped, I think we should also support cluster-scoped new kind of TPR.

Case: 
I want to write some configuration in cluster so that new admission plugin can read and work as configured(note that this admission plugin not care about namespace). I can't use ConfigMap since it is namespace-scoped, but I think TPR may has the chance to make that possible if I could create a cluster-scoped TPR data.

Now plan-B is that write this configuration to special namespace ConfigMap like kube-system/default, but ugly...

**Comment by liggitt** [comment]
I'd expect that as an evolution of custom resources (https://github.com/kubernetes/features/issues/95)

**Comment by ncdc** [comment]
TPRs are being deprecated in favor of CRDs, and CRDs support both namespace and cluster scoped resources. @deads2k is it appropriate to close this?

**Comment by deads2k** [comment]
> TPRs are being deprecated in favor of CRDs, and CRDs support both namespace and cluster scoped resources. @deads2k is it appropriate to close this?

Yes.  Completed in 1.7 using CRD.
