### ISSUE TITLE
Expose secrets to containers in environment variables

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#4710]
Now that #4126 and #4514 have landed, it should be possible to expose secrets to containers as environment variables.  While this is arguably not the optimal way to consume secrets, it will be important to users taking their first steps into a cloud environment, and we should offer this feature to enable a good experience for users who need it.  For what it's worth, we consider this to be an important use-case for users of [OpenShift](https://github.com/openshift/origin).

Let's start with getting all the requirements and challenges on the table:

1.  How should this be modeled in the API?
2.  What limits are reasonable to place on secrets exposed to containers this way?  For example, there are different upper limits on aspects of environment variables on different platforms.
3.  Secrets are not static but environment variables are.  Should the consuming containers be restarted when a secret value changes?
4.  Should environment variables containing secrets be exposed via `docker inspect`*?
5.  Environment variables that contain secrets should not be captured by `docker commit`*

*Applies to future equivalencies in other supported container runtimes

On all aspects of the problem mentioned above, we should take into account possible cross-cuts with:

1.  Pass pod info to container (#560)
2.  Dynamic configuration (#1553)
3.  Sundry other things collected under the downward/upward API aggregator (#386)

**Comment by pmorie** [comment]
@erictune @bgrant0607 @thockin @smarterclayton @csrwng

**Comment by smarterclayton** [comment]
One option is an environment file option to the container that reads/sources a file from the volumes prior to container start.  Or, alternatively, enable this from a pre start hook.  I think we want to avoid ways of scraping data from disk that aren't file based (no "extract this var from this file").  It's also worth asking how prestart hooks could use secret volume data to generate config files.

I would recommend framing this in terms of the existing use cases described in the security proposals to find one really compelling scenario.  I agree this needs to take into account the other issues.

**Comment by erictune** [comment]
I'm not yet seeing the use case for environment variables.   They have some terrible properties, which @pmorie does list above.

First, not all users have stringent security requirements.  For some users, having access to the namespace in which the pod is created means that it is probably okay for you to see the secret.  So, for those users, they don't need to use the /secrets type.  They can just put it in the image.  

Second, it seems like in many cases, there is a chance to wrap the program that needs the environment variable in some shell script which can read a file from a secrets volume and stick the contents into an env var.

**Comment by pmorie** [comment]
@erictune @smarterclayton I've been thinking about the read-from-file wrapper.  I'm not quite sure what the API should be, but it might be something we could do in conjunction with volumes.  As a random thought, maybe if you want to consume secrets as env vars, you could have an 'env' attribute on a `SecretVolumeSource` that made the volume plugin generate a single env file.

**Comment by pmorie** [comment]
@erictune A number of images expect to use environment variables; a random sample:

1. https://github.com/tutumcloud/tutum-docker-mysql
2. https://registry.hub.docker.com/_/postgres/
3. Images that use [conjur](http://www.conjur.net/) to manage secrets

I think these fall under the use-case defined in the security docs for using images from the community and having them work.

**Comment by pmorie** [comment]
I was thinking about this today and had some more specific ideas I will probably start prototyping.  Today it would be possible to:

1.  Create a secret with a key, `env`, which contained a base64-encoded env file.
2.  Consume that secret in a volume and mount it into a container at `/etc/secret-volume`
3.  Source `/etc/secret-volume/env` in the container's command

I don't actually think that the above is a bad way to do it, but the experience can be a little better.  Taking it a step further, what about:

1.  Make it possible to configure a `SecretVolumeSource` to generate an environment file from a `Secret`
2.  Add a finalizer that rewrites the command to source the env files from secret volumes

**Comment by pmorie** [comment]
Will add example shortly

**Comment by pmorie** [comment]
@csrwng Any thoughts on the above?

**Comment by pmorie** [comment]
Example of current way it can be done **today**:

Secret:

```json
{
  "apiVersion": "v1beta2",
  "kind": "Secret",
  "id": "test-secret",
  "data": {
    "environment-file": "TVlTUUxfVVNFUk5BTUU9dXNlcg0KTVlTUUxfUEFTU1dPUkQ9bm90YXNlY3JldA0KTVlTUUxfREJfTkFNRT1hcHBkYg==",
  }
}
```

The `environment-file` secret contains the following data:

    MYSQL_USERNAME=user
    MYSQL_PASSWORD=notasecret
    MYSQL_DB_NAME=appdb

Pod:

```json
{
  "id": "secret-test-pod",
  "kind": "Pod",
  "apiVersion":"v1beta2",
  "labels": {
    "name": "hello-openshift"
  },
  "desiredState": {
    "manifest": {
      "version": "v1beta1",
      "id": "secret-test-pod",
      "containers": [{
        "name": "app-container",
        "image": "someapp",
        "command": [ "bash", "-c", "source /etc/secret-volume/environment-file && app start" ],
        "volumeMounts": [{
          "name": "secret-volume",
          "mountPath": "/etc/secret-volume",
          "readOnly": true
        }]
      }],
      "volumes": [{
        "name": "secret-volume",
        "source": {
          "secret": {
            "target": {
              "kind": "Secret",
              "namespace": "test",
              "name": "test-secret"
            }
          }
        }
      }]
    }
  }
}
```

I think a better experience would be:

```json
{
  "apiVersion": "v1beta2",
  "kind": "Secret",
  "id": "test-secret",
  "data": {
    "mysql-username": "dXNlcg==",
    "mysql-password": "bm90YXNlY3JldA====",
    "mysql-db-name": "YXBwZGI=",
  }
}
```

```json
{
  "id": "secret-test-pod",
  "kind": "Pod",
  "apiVersion":"v1beta2",
  "labels": {
    "name": "hello-openshift"
  },
  "desiredState": {
    "manifest": {
      "version": "v1beta1",
      "id": "secret-test-pod",
      "containers": [{
        "name": "app-container",
        "image": "someapp",
        "command": [ "bash", "-c", "app start" ],
        "volumeMounts": [{
          "name": "secret-volume",
          "mountPath": "/etc/secret-volume",
          "readOnly": true
        }]
      }],
      "volumes": [{
        "name": "secret-volume",
        "source": {
          "secret": {
            "target": {
              "kind": "Secret",
              "namespace": "test",
              "name": "test-secret"
            },
            "env": {
              "filename": "environment-file",
            },
          }
        }
      }]
    }
  }
}
```

Which would result in a file equivalent to the one in the example above being generated at
`/etc/secret-volume/environment-file`.  The volume plugin would be extended to handle generation of
this file.  The finalizer would mutate the command to source the generated environment file.

Another use-case @liggitt brought up is that the `SecretVolumeSource` could allow users to specify
adaptations of secret data keys into environment variable names.

**Comment by csrwng** [comment]
@pmorie - how would the finalizer determine that a pod is not "finalized" and that it needs to update the run command, or for that matter the scheduler know that the pod can't be scheduled without being finalized?

**Comment by smarterclayton** [comment]
This is a separate discussion that is still unresolved - Brian and I sketched up a few solutions but I don't think there's a clear answer yet.

**Comment by pmorie** [comment]
@csrwng Good question.  Since there are a lot of questions around finalizers still I think for now we can generate the env file in the manner I described above and the user will need to include the bits about sourcing in their command.  We can add finalization in the future.

**Comment by csrwng** [comment]
SGTM - I like the idea of the SecretVolumeSource, it's more consumable.

**Comment by pmorie** [comment]
Thought about this some more today and I'm going to prototype the following:

```go
// SecretVolumeSource adapts a Secret into a VolumeSource.
//
// The contents of the target Secret's Data field will be presented in a volume
// as files using the keys in the Data field as the file names.
type SecretVolumeSource struct {
	// Reference to a Secret
	Target ObjectReference `json:"target"`

	// EnvAdaptations adapts the secret into an environment file
	EnvAdaptations *SecretEnv `json:"env"`
	// FUTURE: fine-grained control of files
	// FileAdaptations *SecretFiles `json:"files"`
}

// SecretEnv adapts secret data into an environment file.  The keys in the
// secret data are converted from DNS_SUBDOMAIN into environment variable
// names by upper casing and subsituting the '_' character for '-' and '.'.
type SecretEnv struct {
	// Path is the path of the environment file to generate.
	Path string `json:"path"`

	// Adaptations is a list of adaptations to apply to the
	// names of environment variables superceding the normal
	// algorithm.
	Adaptations []StringAdaptation `json:"adaptations,omitempty"`
}

// StringAdaptation specifies a mapping from
type StringAdaptation struct {
	Key string `json:"key"`
	To  string `json:"to"`
}
```

In the first iteration the user will need to source the generated file manually in the command.

**Comment by pmorie** [comment]
@erictune @smarterclayton @csrwng

**Comment by ironcladlou** [comment]
Command wrapping seems to come with its own concerns. The plugin would be making assumptions about at least:

1. The specific shell in use by the container entrypoint (e.g. bash)
  1. The use of (or desire to use) a shell at all by the container
2. The availability of a shell on PATH in the container image, or
3. The availability of a shell at an absolute path within the container image

**Comment by pmorie** [comment]
@ironcladlou That would be the finalizer, not the plugin, but yeah, I agree that those are concerns to think through

**Comment by liggitt** [comment]
@pmorie another use of envvars I just thought of is the filename of a secret being in an envvar, e.g. `KUBECONFIG` or `CURL_CA_BUNDLE`

**Comment by pmorie** [comment]
@liggit do you want it automatically when secrets are exposed via the
volume plugin?

**Comment by pmorie** [comment]
@liggitt

**Comment by liggitt** [comment]
dunno... if the goal is to set an envvar the container is already looking for, then I assume some adaptation would be needed in the pod spec.

Ways I see a pod spec consuming secrets:
* Put secret `A` into file `/path/to/secretfile`
* Put secret `B` into a file somewhere and put that filename in envvar `$SECRET_FILE`
* Put secret `C` into envvar `$SECRET_VALUE`

**Comment by csrwng** [comment]
@liggitt - for the case where you want the env var to point to a secret file... couldn't you just set that in advance?

**Comment by pmorie** [comment]
I had thought the same thing @csrwng, I'm still trying to decide if there's merit to generating it.

**Comment by liggitt** [comment]
mmm.. suppose so. that would be a combination of a regular env var and the "Put secret A into file /path/to/secretfile" case. that's probably fine

**Comment by thockin** [comment]
I didn't follow this whole thread in enough detail, but I want to throw out
a few things.

1) I am against most or all forms of command wrapping.  There's precious
little you can assume about user containers - may not have a shell, may not
be a shell you like, etc.

2) Every tmpfs mount has a cost to the kernel ( a few 10s of KB if I
recall) and real impact on other things - for example kubelet scans
/proc/mounts.  If/when we get to per-pod tmpfs mounts, we should try to
think about how not to abuse that.  Consider making the secrets volume
handle more than one secret at a time?

3) I'm naturally predisposed against env vars, this conversation has not
helped :)

**Comment by pmorie** [comment]
@thockin responses below:

1.  Re: command wrapping, good point re: shell.
2.  Re: per-pod tmpfs mounts, I would say that plugins should share a single per-pod mount amongst all volumes
3.  But is it nature or nurture?

**Comment by bgrant0607** [comment]
Re. "wrapping": replacing the entrypoint + exec would give us pre-start hooks. We could mount a specialized Go binary into the container at an obscure path for this. OTOH, there's no ETA from Docker for that capability.

**Comment by bgrant0607** [comment]
Re. how to expose this in the API: We now have EnvVarSource. We could create a secret source, with an alternate implementation of how the secret is injected (compared to other env vars).

**Comment by pmorie** [comment]
I had thought about doing that @bgrant0607 but i think there are sundry
issues w/ secrets as envs in general. Will try to find time to articulate
them tomorrow.

**Comment by bgrant0607** [comment]
I would like to expose configuration data (#1553, #6477) as environment variables, which should be less problematic than secrets. It would have the same level of privacy as env vars put directly into a PodSpec. API-wise, it should look similar to secrets.

**Comment by dasch** [comment]
I know there may be issues with using env vars for secrets, but nonetheless it's a very common pattern that people have come to expect:

1. Many existing and widely used Docker images allow configuration through env vars, including passwords.
2. Dev/prod parity is a lot easier using env vars rather than having a wrapper script that needs to figure out whether to parse secrets from a mounted volume.

If the goal of Kubernetes is to make using containers easier, then env vars is part of that.

**Comment by smarterclayton** [comment]
Now that the downward API is in place, substituting secret values into env
vars is not difficult.

On Sep 7, 2015, at 10:06 AM, Daniel Schierbeck <notifications@github.com>
wrote:

I know there may be issues with using env vars for secrets, but nonetheless
it's a very common pattern that people have come to expect:

   1. Many existing and widely used Docker images allow configuration
   through env vars, including passwords.
   2. Dev/prod parity is a lot easier using env vars rather than having a
   wrapper script that needs to figure out whether to parse secrets from a
   mounted volume.

If the goal of Kubernetes is to make using containers easier, then env vars
is part of that.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/4710#issuecomment-138306869>
.

**Comment by liggitt** [comment]
> Now that the downward API is in place, substituting secret values into env vars is not difficult.

I didn't think downward API handled cross-object data transfer (from secrets into pod envvars, etc)

**Comment by smarterclayton** [comment]
It doesn't today, but it is a generic mechanism for transforming resource
data relevant to the pod and its related resources into the container in a
controllable and versionable way.

I would see it looking like:

```
      env:
        - name: MY_SECRET_VALUE
          valueFrom:
            fieldRef:
              kind: Secret
              name: mysecret
              fieldPath: spec.data.password
```


On Tue, Sep 8, 2015 at 11:45 AM, Jordan Liggitt <notifications@github.com>
wrote:

> Now that the downward API is in place, substituting secret values into env
> vars is not difficult.
>
> I didn't think downward API handled cross-object data transfer (from
> secrets into pod envvars, etc)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/4710#issuecomment-138604943>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
It doesn't today, but it is a generic mechanism for transforming resource
data relevant to the pod and its related resources into the container in a
controllable and versionable way.

I would see it looking like:

```
      env:
        - name: MY_SECRET_VALUE
          valueFrom:
            fieldRef:
              kind: Secret
              name: mysecret
              fieldPath: spec.data.password
```

**Comment by paralin** [comment]
Suggesting this be revisited regarding DaemonSets being implemented. With something like a NewRelic system monitor daemon, it would be nice to use the official Docker image, but that requires having a secret in an env variable. Passing the secret in as a Kubernetes secret and attaching it to the container an an env variable would be excellent.

**Comment by resouer** [comment]
+1 need this.  Could we just ship a `env from file` feature in pod?

**Comment by mhausenblas** [comment]
+1 indeed!

**Comment by leonfs** [comment]
+1. It would be great to set environment variables from a file in a Pod. Docker already support this feature with property --env-file. This feature mixed with secrets makes a powerful combination. 

http://docs.docker.com/v1.8/reference/commandline/run/

At the moment I'm having to use a quirky modification to the command:
command: ["/bin/sh", "-ac", ". /var/my-environment-file; /app/myapp"]

**Comment by wernight** [comment]
+1

Most Docker (official and not) images that allow an optional password, implement this via environment variables ([mysql](https://hub.docker.com/_/mysql/), [postgres](https://hub.docker.com/_/postgres/), [ipython/scipyserver](https://hub.docker.com/r/ipython/scipyserver/)...). So there is a use case.

It's possible to wrap but having a helper would be very helpful.

If there is a greater security risk compared to volume, or just different risks, those could go in the documentation.

**Comment by MichielDeMey** [comment]
+1 What @leonfs said. Docker supports loading environmental variables through an `env` file which should be extremely useful for storing sensitive data.

Would it be possible to expose that functionality to Kubernetes also?

**Comment by bgrant0607** [comment]
Since access to the Docker daemon is equivalent to root on the machine, exposing secrets through Docker doesn't seem to increase risk significantly.

Another request:
http://stackoverflow.com/questions/33703012/kubernetes-secrets-files-to-environment-variables

Support for env files generally is #8800.

**Comment by liggitt** [comment]
I think the risks of env files as opposed to secret volumes were around things like logging of `docker inspect` output, and capturing of values in layers when building a docker image

**Comment by bgrant0607** [comment]
This seems no worse than doing it through Docker directly, and it can be avoided by not exposing the secrets as environment variables.

I think we should support this, but document the risks. We can mitigate the risks over time with an improved mechanism.

**Comment by tomkukral** [comment]
We would also really appreciate env files since we usually need to share same credentials in many containers in a pod (db, app, bacula-backup).

Describing security concerns in doc is imho sufficient to mitigate security issues.

**Comment by liggitt** [comment]
> what would prevent such a user from looking into the secret pod to grab the info he needs?

Passwords, key values, etc, showing up in log files is less than ideal... not everything dealing with the log may treat it as confidential, and the data could persist long after the pod and tmpfs volume are safely removed.

> Describing security concerns in doc is imho sufficient to mitigate security issues.

Perhaps, though allowing secret data to be used in that way strongly implies it has been done in a secure way. "It was documented to be insecure" is small comfort if the user didn't notice that documentation.

**Comment by smarterclayton** [comment]
Since a user can work around this in a non optimal way anyway, protecting
users from themselves can probably be taken too far.  It's better for users
to use secrets to inject them into env (or files) than it is for them to
just use env from the start.  So I'm slightly in favor of allowing secrets
-> env via downward API to at least ensure the secrets aren't in the API
objects.

On Nov 16, 2015, at 10:52 PM, Jordan Liggitt <notifications@github.com>
wrote:

what would prevent such a user from looking into the secret pod to grab the
info he needs?

Passwords, key values, etc, showing up in log files is less than ideal...
not everything dealing with the log may treat it as confidential, and the
data could persist long after the pod and tmpfs volume are safely removed.

Describing security concerns in doc is imho sufficient to mitigate security
issues.

Perhaps, though allowing secret data to be used in that way strongly
implies it has been done in a secure way. "It was documented to be
insecure" is small comfort if the user didn't notice that documentation.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/4710#issuecomment-157260604>
.

**Comment by thockin** [comment]
> +1. It would be great to set environment variables from a file in a Pod. Docker already support this feature with property --env-file. This feature mixed with secrets makes a powerful combination.

Unless I am gravely mistaken, Docker's env-file is evaluated OUTSIDE
the pod.  Having it read from inside the pod is actually a LOT more
interesting, but as far as I can tell that is NOT what is happening.

**Comment by thockin** [comment]
That said, I see no reason not to support secrets -> env, with the
documentum that secrets -> volume is strictly better in every way.

**Comment by mhausenblas** [comment]
+1 to what @thockin said:

> no reason not to support secrets -> env, with the documentum that secrets -> volume is strictly better in every way.

In my experience, even when suggesting or providing [good practices](https://mesosphere.com/blog/2015/11/12/sharing-secret-data-in-kubernetes/) it's still a challenge for certain folks to follow along, oftentimes leading to bad outcomes such as people baking secrets into images because they struggle to use a Kubernetes Secret.

**Comment by resouer** [comment]
So it is `preStart` hook being expected in this place?

**Comment by thockin** [comment]
I think this is as simple as adding a new field in `EnvVarSource`

**Comment by smarterclayton** [comment]
As described in https://github.com/kubernetes/kubernetes/issues/4710#issuecomment-138609451

**Comment by e72575f3** [comment]
Is there currently a way to set ENV variables or do I have to hardcode secrets into my source code?

**Comment by pmorie** [comment]
@e72575f3 Are you looking for simple env var control, or populating them with kubernetes secrets, which is the topic of this issue?

**Comment by e72575f3** [comment]
@pmorie Thanks! With the current secrets functionality I have to read the secrets in from files, correct? My legacy code expects them as ENV vars, is there another way to set ENV vars for containers? Then it would be less overhead to change the code, if not then so be it :)

**Comment by thockin** [comment]
Wrap your binary in a shell script that does `export X=$(cat /env/x);
export Y=$(cat /env/Y); my_binary --flag` - you can always solve problems
with a level of indirection. :)

**Comment by resouer** [comment]
@pmorie  Do we have plan/proposal of cross object downwardAPI nnow? If not, we have to treat secret separately like : 
```
	            runtimeVal, err = kl.secretFieldSelectorRuntimeValue(envVar.ValueFrom.FieldRef.FieldPath, secret)
			} else {
				runtimeVal, err = kl.podFieldSelectorRuntimeValue(envVar.ValueFrom.FieldRef, pod)
			}
```

**Comment by glerchundi** [comment]
any chance to cherrypick this into 1.1 branch?

**Comment by thockin** [comment]
sorry, we don't cherry pick features like this

**Comment by clarelewis73** [comment]
I was wondering...

If I created a Java microservice and wanted to use secrets to store passwords. From the operations side of DevOps, how would I change this password without changing the base code? I.e. how would I expose this from k8s to my Java app? Is there a program in fabric8? or is there anything else?

Any help would be great thanks!

**Comment by wernight** [comment]
Secrets are exposed as files by default. You can also expose them as environment variables (just check that you can access them through your Java stack). However if you change them, you'll need to restart the Pod for the changes to get picked up.
