### ISSUE TITLE
Update json name of Pod 'DeprecatedServiceAccount'

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#47101]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug

**Kubernetes version** (use `kubectl version`):
master branch

**What happened**:
The json name of `v1.Pod.DeprecatedServiceAccount` is still `serviceAccount`; we should either update the API reference to `serviceAccount`, or update json/protobuf to `deprecatedServiceAccount`

**Comment by liggitt** [comment]
renaming serialized fields to "deprecated" is not how we deprecate them. the rename would drop any existing data, and break any old clients setting the field, so there is not much point to it.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/44900 actually removes the field, which is what I expected

**Comment by k82cn** [comment]
Great ! thanks :).
