### ISSUE TITLE
host path volumes allow backsteps, PSP allowedHostPaths only guard prefix

### ISSUE THREAD

**Issue by xilabao** [kubernetes/kubernetes#47107]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.184+3837d951919006", GitCommit:"3837d9519190069c44a453c145869e1fced52f23", GitTreeState:"clean", BuildDate:"2017-06-07T06:07:10Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.184+3837d951919006", GitCommit:"3837d9519190069c44a453c145869e1fced52f23", GitTreeState:"clean", BuildDate:"2017-06-07T06:07:10Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:
configure podsecuritypolicy
```
spec:
  allowedHostPaths:
  - /tmp/foo/
```
configure pod
```
  volumes:
      - name: app-logs
        hostPath:
          path: /tmp/foo/../../
```
**What you expected to happen**: 
pod can visit the whole filesystem.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by liggitt** [comment]
@kubernetes/sig-storage-bugs for hostpath mounting of backstep paths

**Comment by liggitt** [comment]
hostPath whitelist is new in 1.7, so there's no exposure for previous releases

**Comment by liggitt** [comment]
I would actually expect the volume plugin on the node to fail when asked to mount this path... minimal enforcement in the API is tricky since the OS can differ between the apiserver and the node

options are:
1. tighten volumesource validation in the API to prevent backsteps (would have to enforce both windows and unix formats)
2. update node volume plugin to refuse to mount paths that include backsteps (the node knows its own OS at that point)

**Comment by saad-ali** [comment]
/assign @jhorwit2

xref https://github.com/kubernetes/kubernetes/pull/43946 - Original PR introducing the feature.

@jhorwit2 can you please take a look and work on a fix?

**Comment by liggitt** [comment]
PSP whitelists paths, but I think the backstep issue belongs to the hostpath volume plugin

**Comment by jhorwit2** [comment]
@saad-ali sure

**Comment by jhorwit2** [comment]
I *think* the check would need to go [in this method](https://github.com/kubernetes/kubernetes/blob/c13d8917c2f3b38ef2d8307f67c9704265f345a8/pkg/kubelet/kuberuntime/kuberuntime_container.go#L134)

I'm not really sure if that's the only place. It seems rkt copies most of that logic?

**Comment by jhorwit2** [comment]
I also just noticed that container VolumeMount's has SubPath that could also allow `..`. 

It seems the best place to validate this would be [here](https://github.com/kubernetes/kubernetes/blob/c13d8917c2f3b38ef2d8307f67c9704265f345a8/pkg/kubelet/kubelet_pods.go#L147), which appears to be where the logic is to setup a host volume. If I'm thinking about this right, it should be sufficient to do a check that the `hostPath == filepath.Clean(hostPath)`.

Thoughts?

**Comment by liggitt** [comment]
I thought host path was specifically dealt with in https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/host_path/host_path.go#L101

**Comment by jhorwit2** [comment]
@liggitt the code I linked uses that object [here](https://github.com/kubernetes/kubernetes/blob/c13d8917c2f3b38ef2d8307f67c9704265f345a8/pkg/kubelet/kubelet_pods.go#L136). From what I can tell that mounter only handles provisioning PersistentVolume's. It also doesn't handle subpath's.

**Comment by liggitt** [comment]
@jhorwit2 @kubernetes/sig-storage-misc should weigh in, but mounter should be used for both PV and Pod volume sources

**Comment by liggitt** [comment]
also, I thought everything in a container's VolumeMount was from the container's point of view, so /../ traversal there would just affect where in the container the volume showed up

**Comment by liggitt** [comment]
(but someone from the storage team should verify that understanding)

**Comment by jhorwit2** [comment]
My understanding is that `subPath` on the [VolumeMount](https://kubernetes.io/docs/api-reference/v1.6/#volumemount-v1-core) is added to the host volume's path. The host mount used to create the container to the container is `path.Join(hostPath, subPath)` [(seen here)](https://github.com/kubernetes/kubernetes/blob/c13d8917c2f3b38ef2d8307f67c9704265f345a8/pkg/kubelet/kubelet_pods.go#L147)

That way you could have 1 host volume for `/foo` then have container A use `/foo/a` and container B use `/foo/b`. `mountPath` is the path mounted in the container.

**Comment by liggitt** [comment]
Looks like validation prevents that, but assumes the apiserver and node OS match

https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation.go#L1706

https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation.go#L944

**Comment by liggitt** [comment]
I think I'd expect validateHostPathVolumeSource to perform the same sort of validation (no `..` segments, according to the API server OS), and *also* enforce that at the node, so that if there's a mismatch in OS, it gets caught

**Comment by jhorwit2** [comment]
That sounds reasonable to me. Once someone from sig-storage weighs in I'd be glad to submit a PR.

**Comment by saad-ali** [comment]
> I think I'd expect validateHostPathVolumeSource to perform the same sort of validation (no .. segments, according to the API server OS), and also enforce that at the node, so that if there's a mismatch in OS, it gets caught

Doing `filepath.Clean(...)` in `validateHostPathVolumeSource(...)` makes sense to me.

However, my only question is about this statement:

> and also enforce that at the node, so that if there's a mismatch in OS, it gets caught

Once it gets accepted by the API server, when does node call `pkg/api/validation/validation.go:validateHostPathVolumeSource(...)`?

**Comment by liggitt** [comment]
> Doing filepath.Clean(...) in validateHostPathVolumeSource(...) makes sense to me.

You mean make sure the path passed in is identical to the result of calling filepath.Clean()?

> Once it gets accepted by the API server, when does node call pkg/api/validation/validation.go:validateHostPathVolumeSource(...)?

I would expect the check on hostpath paths in SetUp for the hostpath volume plugin and on VolumeMount.SubPath fields in makeMounts

**Comment by saad-ali** [comment]
> You mean make sure the path passed in is identical to the result of calling filepath.Clean()?

Yes.

> I would expect the check on hostpath paths in SetUp for the hostpath volume plugin and on VolumeMount.SubPath fields in makeMounts

Ack. Yep this approach makes sense to me. @jhorwit2,  :+1: from sig-storage -- go for it.

CC @kubernetes/sig-storage-bugs
