### ISSUE TITLE
.yaml files containing non-YAML markup should have proper file extension

### ISSUE THREAD

**Issue by cdxOo** [kubernetes/kubernetes#47112]
There are files in [cluster/addons/cluster-monitoring](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/cluster-monitoring) that contain non-YAML markup but have the '.yaml' file extension, like [this one](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/google/heapster-controller.yaml). By the looks of it theese are SLS files that use Jinja. I would suggest replacing the extension of those files with an extension that reflects their contents better.

**Comment by dmathieu** [comment]
It seems this issue was fixed in 0d39648775c0a5ab2bb99754f9181c51adc29544, and can be closed.
