### ISSUE TITLE
#issues in upgrading  1.5.x to 1.6.x version

### ISSUE THREAD

**Issue by fthamp** [kubernetes/kubernetes#47120]
Upgraded the master components(apiserver,controller,scheduler,kubectl) followed by worker components(kubelet,kube-proxy,kubectl)
 from 1.5.7 to 1.6.0. On master upgrade the existing pods had change in state and the worker upgrade resulted in  deletion of all containers in worker nodes.

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
kubelet
kube-api server

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

 Seen a bug reported 1.6.0 kubelet doesn't work with 1.5.2 apiserver  #43976  , is in open state. 

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
The upgrade was tried from kubernetes version 1.5.2 to 1.6.0
1.5.7 to 1.6.0,

**Environment**:
- **Cloud provider or hardware configuration**:Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-59-generic x86_64)
- **OS** (e.g. from /etc/os-release):Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-59-generic x86_64)
- **Kernel** (e.g. `uname -a`):
- **Install tools**:Kubernetes version: 1.5.7 Etcd Version: 3.1.0
 Docker version 1.13.1
- **Others**:

**What happened**:
 The pods,ds,containers in the workers get deleted at the instant, kubelet 1.6.0 comes up.
- There was sync issues between kube-apiserver 1.6.0 and kubelet 1.5.7
- Pods created on the upgraded workers remain in pending state.

**What you expected to happen**:
Pods , RCs, DS running in kubernetes 1.5.7 should  remain unaffected during and after upgrade.

**How to reproduce it** (as minimally and precisely as possible):
Bring up a kubernetes cluster with 3 Masters and 5 workers in 1.5.7 version .Upgrade all the master components  to 1.6.0. Followed by worker upgrade.
 After two seconds of kubelet restart, the containers will be deleted completely.
**Anything else we need to know**:
Jun  6 07:10:49 localhost kubelet[7317]: I0606 07:10:49.694485    7317 server.go:869] Started kubelet v1.6.0
Jun  6 07:10:49 localhost kubelet[7317]: E0606 07:10:49.694546    7317 kubelet.go:1165] Image garbage collection failed: unable to 
find data for container /
Jun  6 07:10:49 localhost kubelet[7317]: I0606 07:10:49.695265    7317 server.go:127] Starting to listen on 0.0.0.0:10250
Jun  6 07:10:49 localhost kubelet[7317]: I0606 07:10:49.699224    7317 server.go:294] Adding debug handlers to kubelet server.
Jun  6 07:10:49 localhost kubelet[7317]: I0606 07:10:49.699953    7317 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
Jun  6 07:10:49 localhost kubelet[7317]: I0606 07:10:49.699986    7317 status_manager.go:140] Starting to sync pod status with apiserver
Jun  6 07:10:49 localhost kubelet[7317]: I0606 07:10:49.699994    7317 volume_manager.go:248] Starting Kubelet Volume Manager
Jun  6 07:10:49 localhost kubelet[7317]: I0606 07:10:49.700013    7317 kubelet.go:1741] Starting kubelet main sync loop.
Jun  6 07:10:49 localhost kubelet[7317]: I0606 07:10:49.700049    7317 kubelet.go:1752] skipping pod synchronization - [container runtime is down PLEG is not 
healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s]
Jun  6 07:10:49 localhost kubelet[7317]: W0606 07:10:49.728943    7317 docker_sandbox.go:263] failed to parse the sandbox name 
"k8s_POD.5005e29e_ds-l65ml_default_2db1c87f-4aa7-11e7-8971-1402ec08c562_8cdcc4ac": strconv.ParseUint: parsing "8cdcc4ac": invalid syntax
Jun  6 07:10:49 localhost kubelet[7317]: I0606 07:10:49.765472    7317 factory.go:309] Registering Docker factory
Jun  6 07:10:49 localhost kubelet[7317]: W0606 07:10:49.765508    7317 manager.go:247] Registration of the rkt container factory failed: 
unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
Jun  6 07:10:49 localhost kubelet[7317]: I0606 07:10:49.765518    7317 factory.go:54] Registering systemd factory
Jun  6 07:10:49 localhost kubelet[7317]: I0606 07:10:49.765855    7317 factory.go:86] Registering Raw factory
Jun  6 07:10:49 localhost kubelet[7317]: I0606 07:10:49.766178    7317 manager.go:1106] Started watching for new ooms in manager
Jun  6 07:10:49 localhost kubelet[7317]: I0606 07:10:49.767940    7317 oomparser.go:185] oomparser using systemd
Jun  6 07:10:49 localhost kubelet[7317]: I0606 07:10:49.768729    7317 manager.go:288] Starting recovery of all containers
Jun  6 07:10:49 localhost kubelet[7317]: I0606 07:10:49.800268    7317 kubelet_node_status.go:230] Setting node annotation to
 enable volume controller attach/detach
Jun  6 07:10:49 localhost kubelet[7317]: I0606 07:10:49.802315    7317 kubelet_node_status.go:77] Attempting to register node 192.168.14.89
Jun  6 07:10:49 localhost kubelet[7317]: I0606 07:10:49.812002    7317 kubelet_node_status.go:80] Successfully registered node 192.168.14.89
Jun  6 07:10:49 localhost kubelet[7317]: I0606 07:10:49.978892    7317 manager.go:293] Recovery completed
Jun  6 07:10:55 localhost kubelet[7317]: W0606 07:10:55.842851    7317 kuberuntime_container.go:436] No ref for container 
{"docker" "d5993d9662aec84f17a9f47979bf903f1e84ace64304a379e2cea23de6b9ab77"}
Jun  6 07:10:55 localhost kubelet[7317]: W0606 07:10:55.875471    7317 kuberuntime_container.go:436] No ref for container
 {"docker" "b9731272a0c895373d39f50928d8841dc58963a74364826f07c9792ea514c521"}
Jun  6 07:10:55 localhost kubelet[7317]: W0606 07:10:55.906520    7317 kuberuntime_container.go:436] No ref for container
 {"docker" "d16b713ed63a186f1b5338b710caec11365ecb782483f166d7c2bda668ae2a5b"}
Jun  6 07:10:57 localhost dockerd[17771]: time="2017-06-06T07:10:57.732619989-04:00" level=info msg="Container 2af8409291c69163d5aa7259da1d557d0678d037c56b4972bdf56607b38ce239 failed to exit within 2 seconds of signal 15 - using the force"
Jun  6 07:10:57 localhost dockerd[17771]: time="2017-06-06T07:10:57.732803087-04:00" level=info msg="Container 78a82dac5752ea4a2387f21aa5da3c58bfa9b36efb7db476ed61612ffa1efddf failed to exit within 2 seconds of signal 15 - using the force"
Jun  6 07:10:57 localhost dockerd[17771]: time="2017-06-06T07:10:57.732846051-04:00" level=info msg="Container d6e1280ee5b77d26d60163c294d89a6ff1e34a4028d5936de5c0bb588d52d131 failed to exit within 2 seconds of signal 15 - using the force"
Jun  6 07:10:57 localhost kubelet[7317]: W0606 07:10:57.873033    7317 kuberuntime_container.go:436] No ref for container 
{"docker" "2af8409291c69163d5aa7259da1d557d0678d037c56b4972bdf56607b38ce239"}
Jun  6 07:10:57 localhost kubelet[7317]: W0606 07:10:57.916013    7317 kuberuntime_container.go:436] No ref for container 
{"docker" "78a82dac5752ea4a2387f21aa5da3c58bfa9b36efb7db476ed61612ffa1efddf"}
Jun  6 07:10:57 localhost kubelet[7317]: E0606 07:10:57.919241    7317 cni.go:275] Error deleting network: failed to find plugin "multus" in path [/etc/cni/net.d /opt/multus/bin]
Jun  6 07:10:57 localhost kubelet[7317]: W0606 07:10:57.955150    7317 kuberuntime_container.go:436] No ref for container 
{"docker" "d6e1280ee5b77d26d60163c294d89a6ff1e34a4028d5936de5c0bb588d52d131"}
Jun  6 07:10:57 localhost kubelet[7317]: W0606 07:10:57.957627    7317 docker_sandbox.go:263] failed to parse the sandbox name "k8s_POD.5005e29e_ds-l65ml_default_2db1c87f-4aa7-11e7-8971-1402ec08c562_8cdcc4ac": strconv.ParseUint: parsing "8cdcc4ac": invalid syntax
Jun  6 07:10:57 localhost kubelet[7317]: W0606 07:10:57.967295    7317 docker_sandbox.go:263] failed to parse the sandbox name "k8s_POD.5005e29e_ds-l65ml_default_2db1c87f-4aa7-11e7-8971-1402ec08c562_8cdcc4ac": strconv.ParseUint: parsing "8cdcc4ac": invalid syntax

**Comment by ravilr** [comment]
@fthamp did you read the 1.6 release CHANGELOG : https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#node-components

> The Docker-CRI implementation is enabled by default.
It is not compatible with containers created by older Kubelets. It is recommended to drain your node before upgrade. If you choose to perform an in-place upgrade, the Kubelet will automatically restart all Kubernetes-managed containers on the node.

**Comment by fthamp** [comment]
@ravilr Here the issue is that the  kubernetes-managed containers on the node gets removed completely.Its more like a deletion operation than restart hence the query.

**Comment by roffe** [comment]
@fthamp Have you done the ETCD v2 to v3 migration? 1.6 uses v3 as default and afaik 1.5.x used v2 as standard.

I had the same problem when i upgraded as i totally oversaw that point and when 1.6 came up it started to delete everything as the ETCD v3 datastore was empty and kubernetes saw it as a new cluster.

https://coreos.com/blog/migrating-applications-etcd-v3.html

You will most likely have to take the etcd cluster offline and do the migration as none i've talked to so far has had a ETCD loadbalancer that allows them to put ETCD in "read only" mode to do the migration "online"

**Comment by galal-hussein** [comment]
I am having similar issue when upgrading from 1.5.4 to 1.6.4, the infra containers are deleted immediately after the upgrade,  the kubelet logs shows the following:
```
{"log":"I0615 14:00:19.453050   31089 docker_manager.go:2040] Found pod infra container for \"nginx-restart_default(1421c2ae-51d2-11e7-bf9d-02d4922e7c85)\"\n","stream":"stderr","time":"2017-06-15T14:00:19.453627631Z"}
{"log":"I0615 14:00:19.453092   31089 docker_manager.go:2051] Need to restart pod infra container for \"nginx-restart_default(1421c2ae-51d2-11e7-bf9d-02d4922e7c85)\" because it is changed\n","stream":"stderr","time":"2017-06-15T14:00:19.453639119Z"}
```
however the infra container used is the same in 1.5 and 1.6  `gcr.io/google_containers/pause-amd64:3.0` , also i disabled docker-cri.

**Comment by roffe** [comment]
@galal-hussein Have you taken precautions to ensure you your not switching etcd  datastore as well with the upgrade? Elsewise basicly when you upgrade the api servers, scheduler & controller will see a empty datastore and start deleting everything on your nodes once the controlplane comes back

**Comment by roffe** [comment]
1.5 used default etcd V2 api, in 1.6 it's V3 now which is a completly different datastore in ETCD. you have to manually convert the data and insert into the V3 datastore for K8S to be able to keep running on the data or force the API server to use V2 & Json instead of the new V3 & protobuff

**Comment by galal-hussein** [comment]
@roffe yes i made sure to still use etcd v2, i passed the following to the kube-apiserver "--storage-backend=etcd2 --storage-media-type=application/json", also the behavior is that the pods are restarting not deleted.

**Comment by xiangpengzhao** [comment]
/close
This issue is no longer valid.
