### ISSUE TITLE
RFE: Have RBAC inject new field in ObjectMeta on author/source of last update

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#47126]
**Is this a FEATURE REQUEST?**:

It is useful to know who was the last person/component that updated a resource for many reasons:
  
- idempotent behavior on automation that deploys @kubernetes/sig-cluster-lifecycle-feature-requests 
- debugging / blame , "Who/what jacked my YAML?!?!?!" 
... 

/cc @kubernetes/sig-auth-feature-requests 

xref: https://github.com/kubernetes/kubernetes/pull/47081

**Comment by smarterclayton** [comment]
Dupe of https://github.com/kubernetes/kubernetes/issues/13306

**Comment by smarterclayton** [comment]
Well, not dupe, but equiv.

**Comment by timothysc** [comment]
Yup, closing.
