### ISSUE TITLE
XFS volumes are unsupported on GCE using the Container-Optimized OS

### ISSUE THREAD

**Issue by markpeterfejes** [kubernetes/kubernetes#47125]
**Is this a request for help?** Partly

**What keywords did you search in Kubernetes issues before filing this one?** xfs gce gci cos mount

---

**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Kubernetes version**: 1.6.4

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): Container-Optimized OS v57 (Build ID: 9202.64.0)
- **Kernel** (e.g. `uname -a`): Linux
- **Install tools**:
- **Others**:

**What happened**: The node failed to mount an XFS PV on GCE using the COS image. With the Container-vm image everything was fine after I installed xfsprogs.

**What you expected to happen**: The node should mount the xfs volume on COS too.

**How to reproduce it**: Try to create an XFS persistent volume in gcloud, then mount it into a pod. 

**Anything else we need to know**: I'm not sure that this is the right place to post this issue. If not, please could you point me to the right direction?  I know that this is an issue with the COS itself rather than k8s.

**Comment by YouriT** [comment]
I'm running into the same issue. But I filed a ticket on the support when they gently asked us to move out of container-vm. Let's see.

**Comment by YouriT** [comment]
I made a quick test and the underlying OS (COS) doesn't know at all XFS apparently. Therefore, I'm not sure whether kubernetes can do anything about it...

Here is what I tested:
- Created a new cluster with COS nodes
- Created a disk
- Attached it to a debian machine
- Created a partition
- Formatted the partition: `mkfs.xfs /dev/sdc1`
=> OK
- Detached and attached de disk to the new COS node
- mount /dev/disk/by-id/scsi-0Google_PersistentDisk_persistent-disk-1-part1 test
=> mount: unknown filesystem type ‘xfs’

So I'd guess their COS image would need to support XFS before we can have it working on k8s.

**Comment by markpeterfejes** [comment]
That is indeed what is going on. Thats why I wrote that I am aware that this is not a kubernetes issue. I hoped that someone can point me to the proper issue tracker.

**Comment by YouriT** [comment]
Thought you were looking for confirmation. I have no clue where to ask that unfortunately. AFAIK their COS source is not open yet. There is still Chromium OS repo but I'm not sure it's the best place to ask.

**Comment by markpeterfejes** [comment]
Feature Request filed! 
https://issuetracker.google.com/issues/62613829

**Comment by YouriT** [comment]
Do you have any workaround to get COS work with XFS in the meantime we get news from them?

I wonder how many people are face that same issue...

**Comment by markpeterfejes** [comment]
I haven't found a workaround unfortunately. What I did was switching to the container-vm image, then creating a startup script what install xfsprogs.

**Comment by YouriT** [comment]
Yup doing the same, DaemonSet with startup script works like a charm. I really don't like this inability of personalising the underlying node, containers ok but still if something is missing we need to be able to tweak the underlying.

**Comment by vdm** [comment]
workaround: using xfsprogs installed as daemonset on container-vm nodes. https://medium.com/@allanlei/mounting-xfs-on-gke-adcf9bd0f212

**Comment by YouriT** [comment]
@vdm the problem is to go back to COS as container-vm has been deprecated and will be removed in September. Hence this is not an option.

**Comment by msau42** [comment]
@markpeterfejes  @YouriT there are no plans in the near future to support xfs on COS.  However, you can now specify ubuntu as a node image type in GKE (beta).

**Comment by allanlei** [comment]
[Packages installed](https://storage.googleapis.com/ubuntu-os-gke-cloud/ubuntu-xenial-amd64-gke-20170420.1.manifest) in the beta Ubuntu images that @msau42 is referencing contain `xfsprogs 4.3.0`.

**Comment by msau42** [comment]
Please use the Ubuntu node image for your xfs needs.

/close
