### ISSUE TITLE
[e2e failures] initializers should dynamically register and apply initializers to pods

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#47133]
Observed consistently for the last few e2e-gci-gke-serial runs.

/cc @kubernetes/sig-api-machinery-bugs 

cc @kubernetes/kubernetes-release-managers

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/extension/initializers.go:206
Expected error:
    <*errors.StatusError | 0xc4214a1980>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "the server could not find the requested resource (post initializerconfigurations.admissionregistration.k8s.io)",
            Reason: "NotFound",
            Details: {
                Name: "",
                Group: "admissionregistration.k8s.io",
                Kind: "initializerconfigurations",
                UID: "",
                Causes: [
                    {
                        Type: "UnexpectedServerResponse",
                        Message: "404 page not found",
                        Field: "",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
    the server could not find the requested resource (post initializerconfigurations.admissionregistration.k8s.io)
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/extension/initializers.go:130
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-serial/1510#k8sio-initializers-should-dynamically-register-and-apply-initializers-to-pods-serial
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-serial/1509#k8sio-initializers-should-dynamically-register-and-apply-initializers-to-pods-serial
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-serial/1511#k8sio-initializers-should-dynamically-register-and-apply-initializers-to-pods-serial

**Comment by caesarxuchao** [comment]
Looks like the admissionregistration.k8s.io group is not turned on

**Comment by caesarxuchao** [comment]
cc @smarterclayton

**Comment by smarterclayton** [comment]
I'll gate it on the group being enabled, I'm currently debugging a separate issue.

**Comment by smarterclayton** [comment]
Added a skip

**Comment by dchen1107** [comment]
@smarterclayton I currently assign it to you, please delegate to the engineer in sig-apimachinery. Thanks!.
