### ISSUE TITLE
CCM and Kubelet both write addresses on node object

### ISSUE THREAD

**Issue by wlan0** [kubernetes/kubernetes#47155]
When running a kubernetes cluster with Cloud Controller Manager, the node object does not get any addresses other than the internal IP address and Hostname.

After debugging @ublubu and I found that both CCM and kubelet race to set the node address. The kubelet is supposed to back off from setting node address when the cloudprovider is set to external. 

This is where kubelet sets node address - https://github.com/kubernetes/kubernetes/blob/b8c9ee8abb387de7d6e0e910538bd53057c77d0f/pkg/kubelet/kubelet_node_status.go#L968

(Kubelet is not supposed to set it, a condition for this check needs to be added)

This is where CCM sets node address - https://github.com/kubernetes/kubernetes/blob/b8c9ee8abb387de7d6e0e910538bd53057c77d0f/pkg/controller/cloud/nodecontroller.go#L192

**Comment by wlan0** [comment]
@ublubu

**Comment by thockin** [comment]
Fix should target 1.7.1

**Comment by marun** [comment]
@thockin If this should be blocking 1.7, please label with 'approved-for-milestone'.
