### ISSUE TITLE
kubefed init errors if namespace already exists

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#47159]
**Is this a BUG REPORT or FEATURE REQUEST?**
BUG

**What happened**:

```
$ kubectl create ns federation-system
$ kubefed init my-fed --dns-provider=google-clouddns \
        --federation-system-namespace="federation-system" \
        --etcd-persistent-storage=false
Error from server (AlreadyExists): namespaces "federation-system" already exists
```

**What you expected to happen**:
I expected the command to not error if the namespace already existed.
kubefed should only create a namespace if it doesnt already exist, otherwise just use the one i gave.

**How to reproduce it** (as minimally and precisely as possible):
see above

**Anything else we need to know**:
nope

**Comment by derekwaynecarr** [comment]
cc @marun @kubernetes/sig-federation-bugs

**Comment by marun** [comment]
@madhusudancs Should this be blocking 1.7?

**Comment by quinton-hoole** [comment]
@marun No, I don't think it should.  Bumping to v1.8.

**Comment by arthur0** [comment]
Can I work on it?

**Comment by walteraa** [comment]
The same happens when trying to join in a federation. There are some RBAC(e.g.: `serviceaccount` and `clusterrolebinding`) which are happening the same issue. Should the `kubefed join` command rollback/clean-up all changes when isn't possible to join in a federation?

**Comment by madhusudancs** [comment]
@walteraa It should. It's tracked in the issue here - https://github.com/kubernetes/kubernetes/issues/41725.

**Comment by walteraa** [comment]
Thanks @madhusudancs

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#19.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
