### ISSUE TITLE
feature request: add kubectl top --sort flag

### ISSUE THREAD

**Issue by zjj2wry** [kubernetes/kubernetes#47163]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.2-dirty", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"dirty", BuildDate:"2017-05-02T10:28:22Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
kubectl top pod need a flag --sort.
now:
```
admindeMacBook-Pro:kubectl admin$ kubectl --kubeconfig=kubectl.kubeconfig top pod
NAME                                                           CPU(cores)   MEMORY(bytes)   
cauth-v0.0.5-2463911897-165m8                                  34m          10Mi            
hadoop-journalnode-2                                           13m          362Mi           
kubernetes-admin-mongo-v3.0.5-fix-permission-742023179-kgqdg   5m           44Mi            
hodor-v0.0.5-3204531036-fqb0q                                  23m          64Mi            
test-1440672787-kvx8h                                          0m           1Mi
elasticsearch-logging-v1-psc43                                 2m           2406Mi   
```

**What you expected to happen**:
--sort=memory:
```
admindeMacBook-Pro:kubectl admin$ kubectl --kubeconfig=kubectl.kubeconfig top pod --sort=memory
NAME                                                           CPU(cores)   MEMORY(bytes)   
elasticsearch-logging-v1-psc43                                 2m           2406Mi   
hadoop-journalnode-2                                           13m          362Mi     
hodor-v0.0.5-3204531036-fqb0q                                  23m          64Mi          
kubernetes-admin-mongo-v3.0.5-fix-permission-742023179-kgqdg   5m           44Mi            
cauth-v0.0.5-2463911897-165m8                                  34m          10Mi                
test-1440672787-kvx8h                                          0m           1Mi
```
--sort=cpu:
```
admindeMacBook-Pro:kubectl admin$ kubectl --kubeconfig=kubectl.kubeconfig top pod --sort=cpu
NAME                                                           CPU(cores)   MEMORY(bytes)   
cauth-v0.0.5-2463911897-165m8                                  34m          10Mi     
hodor-v0.0.5-3204531036-fqb0q                                  23m          64Mi         
hadoop-journalnode-2                                           13m          362Mi     
kubernetes-admin-mongo-v3.0.5-fix-permission-742023179-kgqdg   5m           44Mi      
elasticsearch-logging-v1-psc43                                 2m           2406Mi              
test-1440672787-kvx8h                                          0m           1Mi
```

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by odeke-em** [comment]
In case this feature request is accepted, I've started something at https://github.com/orijtech/kubernetes/tree/top-prod-add-sorting. I'll implement the tests tomorrow when free then perhaps submit a PR here when ready.

**Comment by zjj2wry** [comment]
@odeke-em i create a pr [#47231](https://github.com/kubernetes/kubernetes/pull/47231) sort by name. i read your code implements for kubectl top pod --sort, but maybe top node alse need. maybe ** o.Printer = metricsutil.NewTopCmdPrinter(out, o.sortby) ** update to ** o.Printer = metricsutil.NewTopCmdPrinter(out, o.sortby) ** better and implements sort feature in ** TopCmdPrinter ** .so you need not write it double?

**Comment by odeke-em** [comment]
@zjj2wry oh cool, please feel to implement the rest of the sort by memory and cpu as I have started. I was just getting more familiar with Kubernetes code, and also it is almost 4AM here so I'll look at it when I wake up.

**Comment by zjj2wry** [comment]
@odeke-em good night ~

**Comment by odeke-em** [comment]
`maybe o.Printer = metricsutil.NewTopCmdPrinter(out) update to o.Printer = metricsutil.NewTopCmdPrinter(out, o.sortby) better and implements sort feature in TopCmdPrinter. 
`
Initially I thought of that first, but then that breaks the signature and API of metricsutil. Also on what attributes shall we able to sort on? NodeMetrics? Containers? I'll also take a look later.

`
@odeke-em good night ~
`
Thank you @zjj2wry, have a great day!

**Comment by dkirrane** [comment]
Any update on this?
