### ISSUE TITLE
Openstack support missing from PersistentVolumeLabel Admission Controller

### ISSUE THREAD

**Issue by stuart-warren** [kubernetes/kubernetes#47168]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

`openstack PersistentVolumeLabel`

FEATURE REQUEST

Kubernetes doesn't currently support Openstack for PersistentVolumeLabel Admission Controller as seen here: https://github.com/kubernetes/kubernetes/blob/822e29dd3ce90421c099f6bec7f476c419c3211e/plugin/pkg/admission/persistentvolume/label/admission.go

Openstack Mitaka appears to disable cross AZ volume mounting by default and without any method to avoid pods starting in different AZs to their volumes, a lot of our StatefulSets never start due to not being able to mount their volume.

Have a PR in progress to get this working.

Understand that we are moving to the cloud-controller-manager and may reimplement when that is complete.

**Comment by stuart-warren** [comment]
@kubernetes/sig-openstack

**Comment by zetaab** [comment]
this is fixed already in https://github.com/kubernetes/kubernetes/pull/44798 after that PR statefulsets will always add zone label to persistentvolume. In other words: it cannot happen anymore that volume is in zone-1 and pod is executed in zone-2.

**Comment by dims** [comment]
looks like this was taken care of. please reopen if necessary.

/close
