### ISSUE TITLE
get the patch from edit command

### ISSUE THREAD

**Issue by xilabao** [kubernetes/kubernetes#47173]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.184+3837d951919006", GitCommit:"3837d9519190069c44a453c145869e1fced52f23", GitTreeState:"clean", BuildDate:"2017-06-07T06:07:10Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.184+3837d951919006", GitCommit:"3837d9519190069c44a453c145869e1fced52f23", GitTreeState:"clean", BuildDate:"2017-06-07T06:07:10Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
use `--out-patch` to get the patch from edit command

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

ref to #46091

**Comment by xiangpengzhao** [comment]
/sig cli

IMO, we'd better post this issue to [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new), as the issue template says..
