### ISSUE TITLE
e2e test the Node Authorizer

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#47174]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

TESTING REQUEST

Spawned from: https://github.com/kubernetes/kubernetes/pull/46879
It would be nice with some e2e tests for the Node Authorizer so consumers of it (kubeadm, GCE, GKE, etc.) could easily make sure it's enabled and working, just by editing `ginkgo.focus` when running e2e's.

I wrote a quick bash script of what it could do:

```bash
if [[ $(kubectl version 2>&1 | grep "Client" | grep 'Minor:"7') == "" ]]; then
	echo "kubectl v1.7.0-beta.0 or higher is required"
	exit 1
fi

export KUBECONFIG=/etc/kubernetes/admin.conf
IMPERSONATE="--as system:node:thegopher --as-group system:nodes"

printf "TESTING: Getting a non-existent secret should exit with the Forbidden error, not a NotFound error] "
([[ $(kubectl ${IMPERSONATE} get secret foo 2>&1 | grep "Forbidden") != "" ]] && printf "PASSED!\n") || printf "FAILED!\n"

printf "TESTING: Getting an existent secret should exit with the Forbidden error] "
([[ $(kubectl ${IMPERSONATE} get secret $(kubectl get secret | grep token | awk '{print $1}') 2>&1 | grep "Forbidden") != "" ]] && printf "PASSED!\n") || printf "FAILED!\n"

printf "TESTING: Getting a secret for a workload the node has access to should succeed] "
kubectl ${IMPERSONATE} -n kube-system get secrets $(kubectl -n kube-system get secret | grep kube-proxy | awk '{print $1}') 1>/dev/null 2>/dev/null
([[ $? == 0 ]] && printf "PASSED!\n") || printf "FAILED!\n"

printf "TESTING: A node shouldn't be able to create an other node] "
echo '{"apiVersion":"v1","kind":"Node","metadata":{"name":"foo"}}' | kubectl delete -f - 1>/dev/null 2>/dev/null
echo '{"apiVersion":"v1","kind":"Node","metadata":{"name":"foo"}}' | kubectl ${IMPERSONATE} --validate=false create -f - 1>/dev/null 2>/dev/null
([[ $? == 1 ]] && printf "PASSED!\n") || printf "FAILED!\n"
```

The bash script above is in no way comprehensive enough, but on the other hand it took  ~5mins to write :)

For now (1.7), we might use something like this bash script in our kubeadm e2e CI job to make sure the Node Authorizer/Admission plugin is enabled correctly.

cc @kubernetes/sig-cluster-lifecycle-feature-requests @kubernetes/sig-auth-feature-requests

**Comment by luxas** [comment]
@liggitt was assigned for triaging this... Does such an e2e test already exist somewhere?

@ericchiang said that he could take this on if not...

**Comment by liggitt** [comment]
no negative e2e test exists (make sure things the Node authorizer disallows fail)

negative integration tests exist at https://github.com/kubernetes/kubernetes/blob/master/test/integration/auth/node_test.go#L213

negative e2e tests for this will be tricky, since you'll need node credentials and a specific authz and admission config.

**Comment by luxas** [comment]
@liggitt See the above bash script, I was able to do it purely from kubectl by impersonating the group and node user...
If we feature-gate this e2e test, we can run it for the deployments that actually have unique node credentials

**Comment by luxas** [comment]
cc @wanghaoran1988 this maybe could be a good task for you... :)

**Comment by wanghaoran1988** [comment]
@luxas Cool, thanks for point me this.

**Comment by luxas** [comment]
You basically only have to implement these `kubectl` commands as an e2e test initially (by impersonating a node in the cluster). Then when that's done, we can check if there are more than these four cases that needs to be verified.

This should go under a separate `Feature:NodeAuthorizer` and be enabled in deployments (like kubeadm) where nodes have unique credentials.

**Comment by wanghaoran1988** [comment]
@luxas, I didn't find a way to simulate a node credential, do you have any good idea ? after reading the integration testing code, I fell it's enough the guarantee the quality, WDYT?
