### ISSUE TITLE
Deprecated '--runonce' of kubelet

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#47184]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
enhancement/cleanup

**Kubernetes version** (use `kubectl version`):
master branch for 1.8

**Description**:
According to the TODO at (https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go#L63), it's better to deprecate `--runonce` of kubelet.

**Comment by yujuhong** [comment]
I think this needs to reach a broader audience since I'm not sure who's using the runonce mode.

/cc @kubernetes/sig-node-bugs

**Comment by k82cn** [comment]
not remove, just deprecated it :).

**Comment by dchen1107** [comment]
@k82cn, looks like we missed 1.8 milestone for this.  I am ok to remove this feature completely from node / kubelet, but before we are doing it, could you  please start a discussion thread with both kuberentes-dev@ and kubernetes-users@ first? Thanks!

cc/ @bgrant0607

**Comment by dchen1107** [comment]
cc/ @kubernetes/sig-node-proposals @kubernetes/sig-node-api-reviews

**Comment by mtaufen** [comment]
@JulienBalestra why can't you just launch the initial Kubelet with `--manifest-path`, `--kubeconfig`, and `--hostname-override`? Isn't it possible to preconfigure the necessary details?

**Comment by fanux** [comment]
We need runonce to init etcd cluster as static pod, then using kubeadm to init master.
