### ISSUE TITLE
Remove the deprecated serviceAccount field in podSpec

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes#47198]
Remove the deprecated [`serviceAccount`](https://github.com/kubernetes/kubernetes/blob/502be9f90634c37f1078cd9f2621ce44acb0303e/pkg/api/v1/types.go#L2399) field in podSpec.
This field has been deprecated at least since July 2015, see [PR] (https://github.com/kubernetes/kubernetes/pull/11389/files#diff-e58c0c0709cf6f8a3b00aef6069b66b7R881).

It causes issue like https://github.com/kubernetes/kubectl/issues/23#issuecomment-306611422.

@kubernetes/sig-api-machinery-api-reviews

**Comment by k82cn** [comment]
/close

Handled at https://github.com/kubernetes/kubernetes/pull/44900
