### ISSUE TITLE
Run GPU e2e tests as part of PRs

### ISSUE THREAD

**Issue by mindprince** [kubernetes/kubernetes#47192]
We should do this after 1.7.

xref https://github.com/kubernetes/kubernetes/pull/46644#issuecomment-307170512

/sig testing

cc @vishh

**Comment by cmluciano** [comment]
Is this the task that needs completed -

 Add support to Ubuntu e2e test-infra #46445

**Comment by mindprince** [comment]
That is different, this is about running GPU tests as part of PR pre-submit tests. Right now we skip them because they are "[Serial]".

**Comment by cmluciano** [comment]
I can work on this issue in conjunction with #46445. Is this issue just a matter of adding GPU tests to a different suite or are there more subtasks?

**Comment by cmluciano** [comment]
@mindprince Anymore progress on this?

**Comment by mindprince** [comment]
Thanks for the reminder. I just submitted an internal request for quota to run these tests. Once that is approved, I will add a PR in test-infra to run GPU tests on all k/k PRs. It will be non-blocking initially and then become blocking later on.

**Comment by cmluciano** [comment]
Awesome, thanks!
