### ISSUE TITLE
alpha-features suite is failing to up the cluster

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#47208]
https://k8s-testgrid.appspot.com/release-master-blocking#gce-alpha-features

kubelet log:
```
I0608 22:07:02.816799    3527 server.go:782] GET /healthz: (33.024Âµs) 200 [[curl/7.26.0] 127.0.0.1:46972]
I0608 22:07:12.825056    3527 server.go:782] GET /healthz: (21.665Âµs) 200 [[curl/7.26.0] 127.0.0.1:46975]
I0608 22:07:22.832097    3527 server.go:782] GET /healthz: (23.923Âµs) 200 [[curl/7.26.0] 127.0.0.1:46977]
I0608 22:07:31.849611    3527 server.go:242] Checking API server for new Kubelet configuration.
I0608 22:07:31.856407    3527 server.go:251] Did not find a configuration for this Kubelet via API server: cloud provider was nil, and attempt to use hostname to find config resulted in: configmaps "kubelet-bootstrap-e2e-minion-group-282x" not found
```

@thockin since it might be "cloud provider"
@mtaufen since it might relate to kubelet config

cc @dchen1107 @caesarxuchao

**Comment by thockin** [comment]
@wlan0 ?

**Comment by wlan0** [comment]
@thockin On first look, I can't tell if this is CCM related or not. 

@krzyzacy Thanks for opening the issue. Do you have a set of steps I could use to reproduce this?

**Comment by krzyzacy** [comment]
One of the full log is at https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-alpha-features/11202?log#log

Test arg is
`kubetest -v --dump=/workspace/_artifacts --check-leaked-resources --test '--test_args=--ginkgo.focus=\[Feature:(PetSet|DynamicKubeletConfig|Audit)\]|ScheduledJob' --up --down --deployment=bash --timeout=180m --extract=ci/latest`

I haven't tried locally yet, or it can be GCP project related issue.

**Comment by mikedanese** [comment]
Fixed by: https://github.com/kubernetes/kubernetes/pull/46884

**Comment by ericchiang** [comment]
Updates https://github.com/kubernetes/kubernetes/issues/47283
