### ISSUE TITLE
Don't allow backsteps in local volume plugin

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#47207]
**Kubernetes version** (use `kubectl version`): 1.7

Similar to #47107, we need to check for backsteps in the path ("/foo/bar/../../../baz") for the local volume.  It should be checked in the API validation, and also at mount time.

**Comment by msau42** [comment]
@ddysher, would you be able to look at this?

**Comment by msau42** [comment]
To clarify, I don't think this is critical to fix in 1.7 (for local volumes).  Only the adminstrator can create local PVs, so the paths they export are under their control.

**Comment by ddysher** [comment]
sure, i'll take a look after external provisioner work.

**Comment by liggitt** [comment]
if you want to change API validation, you should do it before 1.7 releases, since the field is new. Changing validation on a released field is much harder

**Comment by dchen1107** [comment]
Approved this for 1.7 release based on the conversation with @liggitt and the engineers from @kubernetes/sig-storage-misc
