### ISSUE TITLE
Agent(clients) showing tcp connection established to api server, but actually doing nothing

### ISSUE THREAD

**Issue by noah8713** [kubernetes/kubernetes#47201]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):
Yes
**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
TCP-connection from client to api server stale.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Not sure

**Kubernetes version** (use `kubectl version`):

kube 1.6 dev branch before 1.6 was released
Ubuntu 14.04
etcd 3.0.13
kernel 3.13.0-76-generic
cores 40
**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Agent(clients) showing tcp connection established to api server, but actually doing nothing.
In our current simulations of up-to 1000 agents talking to kube api server, we found some of the agents during flappy network were just hanging and doing nothing. Checking the logs also shows no errors. Even on network restore, the connection is still established. However, when a resource is updated, details are not received to the agents until we explicitly restart the agent that will establish a new tcp connection on a new port. So one of the suspicion is the tcp connection is stale and even-though established, client cannot get the resource updates. Is it a known issue? Also can we have some settings changed with default timeouts and tcp keep alive?

![tcp-error](https://user-images.githubusercontent.com/6869538/26952905-54d28ad0-4c5c-11e7-9024-51b529ca96d5.JPG)

**What you expected to happen**:
When the network is restored, the updated resource should be received to the agents. We don't have to explicitely restart the agent service to establish a new tcp connection.

**How to reproduce it** (as minimally and precisely as possible):
Agent(client) hangs when there is some network latency and on network restore, client shows connection established but actually not getting the heartbeat/updates from api

**Anything else we need to know**:

**Comment by noah8713** [comment]
cc @kubernetes/sig-release-misc @kubernetes/sig-testing-misc

**Comment by noah8713** [comment]
cc @liggitt

**Comment by justinsb** [comment]
Is there a load balancer in the picture here?

**Comment by noah8713** [comment]
yes apiservers are running behind a vip

**Comment by noah8713** [comment]
@justinsb

**Comment by noah8713** [comment]
@kubernetes/sig-network-misc @kubernetes/sig-node-bugs

**Comment by noah8713** [comment]
@kubernets/sig-apiserver

**Comment by noah8713** [comment]
@cblecker

**Comment by cblecker** [comment]
@noah8713: You've assigned this to yourself. Are you actually taking action on it?

/remove-sig release testing

**Comment by noah8713** [comment]
@cblecker no I am not taking any action. Guess wrong bot call.

**Comment by cblecker** [comment]
/unassign
I'm not the right person to assign this to. The sigs will have to review and triage.

**Comment by noah8713** [comment]
@fejta please help comment on the same. We need a fix for the same. :(

**Comment by noah8713** [comment]
@kubernetes/sig-network-misc

**Comment by bowei** [comment]
This doesn't seem like a sig-node issue.

I think this would fall under how the API server behaves with long-lived client connections, so the API machinery sig may be relevant.

You can try setting a blanket TCP keepalive for the entire host and see if that changes the behavior of the client/server interaction.

**Comment by noah8713** [comment]
@bowei I will enable the TCP keep alive at F5 and keep you posted after one more round of test. Thanks for suggestions.

**Comment by r7vme** [comment]
We see the same behaviour even with internal connections.

### Context:
We are using ephemeral masters (only etcd data preserved). Master can die at any time, immediately orchestrator will create new one with same etcd volume.

### Observations:
We are seeing ESTABLISHED TCP connections to k8s services e.g. `172.31.0.1` from kube-proxy and other services. But in reality this connection is dead, because master did not send any RST (because VM can disappear immediately).

### Workaround:
As author of this ticket we need to restart services (in our case, kube-proxy and [calico-node](https://github.com/projectcalico/calico/issues/1420)) to establish connections to new master/internal services.

#### Configuration:
k8s 1.8.1
Calico 2.6.2
kube-proxy uses iptables driver

I also found related [issue](https://github.com/kubernetes/kubernetes/issues/46753). I'm not sure if it's really issue or not. But my main question, why built-in *linux tcp keepalive* does not drop such connections?

#### P.S.
 For external load balancer (haproxy) we were able to solve this with following configuration:
```
    timeout client          30s
    timeout client-fin      30s
    timeout tunnel          1h
    timeout server          30s
```
