### ISSUE TITLE
Remove mesos cloud provider from Kubernetes

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#47205]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
The test always failed

```
E0609 06:23:50.423023    3407 standalone.go:180] Get http://localhost:5050/state: dial tcp 127.0.0.1:5050: getsockopt: connection refused
E0609 06:23:50.423293    3407 standalone.go:180] Get http://localhost:5050/state: dial tcp 127.0.0.1:5050: getsockopt: connection refused
E0609 06:23:50.436346    3407 standalone.go:180] Get http://localhost:5050/state: dial tcp 127.0.0.1:5050: getsockopt: connection refused
E0609 06:23:50.425510    3407 standalone.go:180] Get http://localhost:5050/state: dial tcp 127.0.0.1:5050: getsockopt: connection refused
E0609 06:23:50.437932    3407 standalone.go:180] Get http://localhost:5050/state: dial tcp 127.0.0.1:5050: getsockopt: connection refused
E0609 06:23:50.439931    3407 standalone.go:180] Get http://localhost:5050/state: dial tcp 127.0.0.1:5050: getsockopt: connection refused
E0609 06:23:50.446500    3407 standalone.go:180] Get http://localhost:5050/state: dial tcp 127.0.0.1:5050: getsockopt: connection refused
--- FAIL: Test_ExternalID (0.85s)
	mesos_test.go:275: ExternalID should not be able to resolve "mesos3.internal.example.org.fail"
FAIL
```

And seems we can remove it from repo now as there is no `mesos` label or area now https://github.com/kubernetes/kubernetes/pull/46824

I can do the cleanup if it is not needed @k82cn 

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by k82cn** [comment]
sure, please continue the work at xref ##34924 , there's some discussion here.

**Comment by gyliu513** [comment]
Currently, I only want to clean up the mesos related cloud provider here @k82cn

**Comment by k82cn** [comment]
yes, cleanup is sub-items of #34924 ; try to avoid multiple issues for discussion.

**Comment by kargakis** [comment]
@kubernetes/sig-cluster-lifecycle-misc
