### ISSUE TITLE
federation-1.7 job fail to up cluster

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#47209]
https://k8s-testgrid.appspot.com/release-1.7-blocking#gce-federation-release-1-7

Seems some quota issue? @madhusudancs 
```
W0608 21:58:34.547] Attempt 5 failed to create static ip prow-us-central1-f-master-ip. Retrying.
W0608 21:59:20.867] ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
W0608 21:59:20.868]  - Quota 'STATIC_ADDRESSES' exceeded. Limit: 2.0
W0608 21:59:20.868] 
W0608 21:59:21.546] Failed to create static ip prow-us-central1-f-master-ip 
```

cc @dchen1107 @caesarxuchao

**Comment by dchen1107** [comment]
cc/ @kubernetes/sig-federation-misc @csbell

**Comment by madhusudancs** [comment]
I have asked for a quota increase. It usually takes about a day.

**Comment by marun** [comment]
@madhusudancs If the quota increase has increased, please close.

**Comment by krzyzacy** [comment]
https://k8s-testgrid.appspot.com/release-1.7-blocking#gce-federation-release-1-7
looks happy
/close
