### ISSUE TITLE
[e2e flakes] ci-kubernetes-e2e-gke-reboot - at least one node failed to reboot in the time given

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#47219]
ci-kubernetes-e2e-gke-reboot has been flaking for the last couple of days.

https://k8s-testgrid.appspot.com/release-master-blocking#gke-reboot

Seeing a lot of errors that look like:

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:122
Jun  8 18:43:57.650: Test failed; at least one node failed to reboot in the time given.
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:168
```

Also the logs are saying something about failing to pull images:

> I0608 18:33:48.649] Jun  8 18:33:48.608: INFO: event for kube-dns-2836479273-b44kg: {kubelet gke-bootstrap-e2e-default-pool-44cef888-1bwq} Failed: Failed to pull image "gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.2": rpc error: code = 2 desc = failed to register layer: rename /var/lib/docker/image/aufs/layerdb/tmp/layer-969822486 /var/lib/docker/image/aufs/layerdb/sha256/60ab55d3379d47c1ba6b6225d59d10e1f52096ee9d5c816e42c635ccc57a5a2b: directory not empty
> I0608 18:33:48.649] Jun  8 18:33:48.608: INFO: event for kube-dns-2836479273-b44kg: {kubelet gke-bootstrap-e2e-default-pool-44cef888-1bwq} Failed: Failed to pull image "gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.2": rpc error: code = 2 desc = failed to register layer: rename /var/lib/docker/image/aufs/layerdb/tmp/layer-099381612 /var/lib/docker/image/aufs/layerdb/sha256/7cbcbac42c44c6c38559e5df3a494f44987333c8023a40fec48df2fce1fc146b: directory not empty
> I0608 18:33:48.649] Jun  8 18:33:48.608: INFO: event for kube-dns-2836479273-b44kg: {kubelet gke-bootstrap-e2e-default-pool-44cef888-1bwq} Failed: Failed to pull image "gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.2": rpc error: code = 2 desc = failed to register layer: rename 

Last three failures:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-reboot/5335
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-reboot/5334
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-reboot/5333

cc @kubernetes/kubernetes-release-managers @dchen1107

**Comment by MrHohn** [comment]
xref the corrupted docker image layer issue discussed before: https://github.com/kubernetes/kubernetes/issues/43549#issuecomment-288886891

**Comment by dchen1107** [comment]
@ajitak & @fabioy I am assigned this to you since you are the owner of NPD for 1.7 release. Like what we discussed before, we can configure NPD to capture those kind of docker image corruption issues. Also update the reboots test to ignore this kind of problem. In a real production, the remedy is removing those bad images on the node, so NPD signal is important.

**Comment by Random-Liu** [comment]
@dchen1107 @ajitak So we should parse docker log to detect the problem, right?

**Comment by marun** [comment]
@ajitak What's the status on this?  Will merging the npd fix resolve this issue?

**Comment by ajitak** [comment]
@marun 
- I have added NPD config which will generate an event for docker image corruption. This is merged.
- One PR for using this config in kubernetes is open.
- I am working on another PR which will use generated event mention above in e2e reboot test and don't fail test for docker image corruption.
