### ISSUE TITLE
GPU e2es are failing

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#47216]
GPU e2es are failing since yesterday (6/8) - https://k8s-testgrid.appspot.com/google-gce#gce-gpu

The only GPU related PR that merged yesterday is https://github.com/kubernetes/kubernetes/pull/46087

cc @dchen1107 @mindprince

**Comment by mindprince** [comment]
We had one successful run which included that commit: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-gpu/402

**Comment by vishh** [comment]
I built a cluster from HEAD and ran the e2es locally and they are passing.

**Comment by vishh** [comment]
That's odd. I'd like to understand why the test flaked? @mindprince can you look at the failed test logs to see if there are any clues?

**Comment by mindprince** [comment]
So, the regression is caused by https://github.com/kubernetes/kubernetes/pull/46744.

Tests pass when run with:
```
$ git checkout d16d64f62078eb419a0bf9c2d5b843176a63d1b9
```

They fail when run with:
```
$ git checkout 69a9759d90339e8d9623d71bf4032c3819879872
```

This the difference between the two commits:
```
$ git log d16d64f62078eb419a0bf9c2d5b843176a63d1b9...69a9759d90339e8d9623d71bf4032c3819879872 --oneline
69a9759d90 (HEAD) Merge pull request #46744 from karataliu/wincri4
5936e81b2e Add determinePodIPBySandboxID.
6d07fc2f44 Add updateCreateConfig.
9c2309b7cb Add os dependent getSecurityOpts helper method.
33c34f0ae4 Upgrade go-winio package to v0.4.2, supporting go v1.8 .
```

Looks like the nvidia GPU devices are no longer being attached to the docker containers after the changes introduced by #46744.

But why are node e2e's still passing?
There is a bug in them which causes them to pass incorrectly. Sent PR #47321 to fix that.

**Comment by vishh** [comment]
> Looks like the nvidia GPU devices are no longer being attached to the docker containers after the changes introduced by #46744.

#46744 seems to be an important feature. Can you try to identify the bug it introduced instead of attempting to revert it? 
FYI: The relevant device injection logic is [here](https://github.com/kubernetes/kubernetes/pull/46744/files#diff-c7dd39479fd733354254e70845075db5R142). 
In case you did not know, you can use a local cluster for testing and development of GPU support @mindprince 

@dchen1107 This issue needs to be fixed for v1.7.

**Comment by karataliu** [comment]
Seems moving resource assignment after updateCreateConfig will do the fix.
https://github.com/kubernetes/kubernetes/pull/46744/files#diff-c7dd39479fd733354254e70845075db5R150

Resources got new value there but was then replaced:
https://github.com/kubernetes/kubernetes/pull/46744/files#diff-7a64798a1c76fb0f489279744c106b36R55

I'll try prepare a PR.

**Comment by mindprince** [comment]
This can be closed now, the tests are green: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-gpu/462

**Comment by vishh** [comment]
Yay!!!.
