### ISSUE TITLE
role/rolebinding doesn't support export function

### ISSUE THREAD

**Issue by xilabao** [kubernetes/kubernetes#47228]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.184+3837d951919006-dirty", GitCommit:"3837d9519190069c44a453c145869e1fced52f23", GitTreeState:"dirty", BuildDate:"2017-06-09T07:04:29Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.184+3837d951919006-dirty", GitCommit:"3837d9519190069c44a453c145869e1fced52f23", GitTreeState:"dirty", BuildDate:"2017-06-09T07:18:31Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:
```
# ./cluster/kubectl.sh get clusterrole admin --export -o yaml
Error from server (BadRequest): export of "clusterroles" is not supported
```

**What you expected to happen**:
no error

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

ref to #47229

**Comment by liggitt** [comment]
/close 

will track in https://github.com/kubernetes/kubernetes/issues/24855
