### ISSUE TITLE
StatefulSet cannot be remove without image

### ISSUE THREAD

**Issue by liqlin2015** [kubernetes/kubernetes#47233]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

StatefulSet, delete, failure
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
v1.6.1

**Environment**:
- **Cloud provider or hardware configuration**: amd64
- **OS** (e.g. from /etc/os-release): ubuntu 16.04
- **Kernel** (e.g. `uname -a`):  Linux 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: ansible
- **Others**:

**What happened**:
I can create a StatefulSet without image. While Kubernetes shall check these required field.

```
# kubectl get statefulsets
NAME                    DESIRED   CURRENT   AGE
111                     2         0         14m
222                     2         0         9m
# kubectl get statefulsets 222 -o yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  creationTimestamp: 2017-06-09T08:56:13Z
  deletionGracePeriodSeconds: 0
  deletionTimestamp: 2017-06-09T09:00:55Z
  finalizers:
  - orphan
  generation: 2
  labels:
    app: "222"
  name: "222"
  namespace: default
  resourceVersion: "37772"
  selfLink: /apis/apps/v1beta1/namespaces/default/statefulsets/222
  uid: 7d8fac7f-4cf1-11e7-8011-fa163e09afbd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "222"
  serviceName: sdf
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      creationTimestamp: null
      labels:
        app: "222"
    spec:
      containers:
      - imagePullPolicy: IfNotPresent
        name: ""
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  observedGeneration: 2
  replicas: 0
```

Then I want to delete this fault StatefulSet

Use `kubectl`
```
# kubectl delete statefulset 222
error: Scaling the resource failed with: StatefulSet.apps "222" is invalid: spec.template.containers[0].image: Required value; Current resource version 37772
```

Use API
```
# curl -vvv --request DELETE http://127.0.0.1:8888/apis/apps/v1beta1/namespaces/default/statefulsets/222
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8888 (#0)
> DELETE /apis/apps/v1beta1/namespaces/default/statefulsets/222 HTTP/1.1
> Host: 127.0.0.1:8888
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Fri, 09 Jun 2017 09:14:50 GMT
< Content-Length: 1446
<
{
  "kind": "StatefulSet",
  "apiVersion": "apps/v1beta1",
  "metadata": {
    "name": "222",
    "namespace": "default",
    "selfLink": "/apis/apps/v1beta1/namespaces/default/statefulsets/222",
    "uid": "7d8fac7f-4cf1-11e7-8011-fa163e09afbd",
    "resourceVersion": "39081",
    "generation": 2,
    "creationTimestamp": "2017-06-09T08:56:13Z",
    "deletionTimestamp": "2017-06-09T09:14:50Z",
    "deletionGracePeriodSeconds": 0,
    "labels": {
      "app": "222"
    },
    "finalizers": [
      "orphan"
    ]
  },
  "spec": {
    "replicas": 2,
    "selector": {
      "matchLabels": {
        "app": "222"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "app": "222"
        },
        "annotations": {
          "pod.alpha.kubernetes.io/initialized": "true"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "",
            "resources": {},
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "IfNotPresent"
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "securityContext": {},
        "schedulerName": "default-scheduler"
      }
    },
    "serviceName": "sdf"
  },
  "status": {
    "observedGeneration": 2,
    "replicas": 0
  }
* Connection #0 to host 127.0.0.1 left intact
}
```

Check again
```
# kubectl get statefulsets
NAME                    DESIRED   CURRENT   AGE
111                     2         0         23m
222                     2         0         19m
```

**What you expected to happen**:
1. StatefulSet without image shall not be created.
2. User should always be able to delete a fault StatefulSet.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by gyliu513** [comment]
/sig apps
/assign

I will check this one

**Comment by kargakis** [comment]
@kubernetes/sig-apps-bugs

**Comment by gyliu513** [comment]
This is because `podSpec` was not validated https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/validation/validation.go#L55-L58 in statefulset.

**Comment by k82cn** [comment]
/sig api-machinery

It's ignored because no volumes in containers of statefulset; one option is to create a new validation func that pass PVC to check.

**Comment by gyliu513** [comment]
The comments already give a solution here:

```
                // TODO: Add validation for PodSpec, currently this will check volumes, which we know will
		// fail. We should really check that the union of the given volumes and volumeClaims match
		// volume mounts in the containers.
		// allErrs = append(allErrs, apivalidation.ValidatePodTemplateSpec(template, fldPath)...)
```

I'm now checking if there is a good way to get the `metadata.name` from the `volumeClaimTemplates`, @bprashanth I saw that you add the comments, it would be great if you can show some comments of how to get the `metadata.name` here. Thanks.

**Comment by liqlin2015** [comment]
What about the case that user always can (forcefully) delete a fault StatefulSet in whatever circumstances.

**Comment by gyliu513** [comment]
@liqlin2015 in general, if the ss can be created successfully, then it can always be deleted. For your case that you can not delete the ss, it is because when create ss, there is no check for `PodSpec`, if I add this checking back, then we can always delete any ss.

Currently for your case, you can edit the ss first by adding `image` and delete the ss. Once this issue is fixed, then you can always delete ss.

**Comment by k82cn** [comment]
@liqlin2015 , I'm not sure whether we handle deleting well for such a "damage" object; if we fixed validation, it should be OK then.

Currently, as gyliu513@ said, please add image as workaround.

**Comment by kow3ns** [comment]
The resolution to the root cause of this is #50340. Delete should just delete. It shouldn't retrieve the object and scale it down. #60619 should fix the validation. We should do both of these to resolve issues like this.
/close
