### ISSUE TITLE
pods in unknown state are not reallocated

### ISSUE THREAD

**Issue by guillelb** [kubernetes/kubernetes#47230]
- Linux k8sBetaMaster3 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
- Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

Yesterday, one of the host in the cluster entered in a failed state, their PODs was in **unknown** status, but kubernetes did not launch any new replica until, hours later, I rebooted the host machine:

**StatefulSets**
```
NAMESPACE   NAME          DESIRED   CURRENT   AGE
default     app-1         1         0         15h
```

Do I need to explicitly indicate something to do that?

@kubernetes/sig-node-misc

**Comment by k82cn** [comment]
/sig apps

@guillelb , it seems StatefulSets related, right?

**Comment by k82cn** [comment]
@ guillelb , how about the pods? what's the out put of `kubectl get pods`?

**Comment by k82cn** [comment]
@guillelb , how about the pods? what's the out put of kubectl get pods?

**Comment by guillelb** [comment]
In that moment, the STATUS was **unknown** for the pod in the failed machine.

`default       app1          0/1       Unknown   0          15h        172.24.96.0      k8sbetamaster3`

The CPU was in 100% of usage, I hoped that the failed PODs were relocated in a miss-function state.

**Comment by crimsonfaith91** [comment]
@guillelb If the pod is a statefulset pod, it is expected to have the pods in `Unknown` status and no new replicas are launched.

A statefulset pod running on an unreachable node enters the `Unknown` or `Terminating` state after a timeout. The new replicas can be created by forcing deletion of the pods with `Unknown` status. After the pods are deleted, statefulset controller will create replacement pods with same identity. You can force delete a pod via `kubectl delete pods <pod> --grace-period=0 --force`. 

Detailed explanation can be found here: https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/

**Comment by foxish** [comment]
To add to @crimsonfaith91's comment, this is one of the guarantees provided by statefulset. If you want different behavior in the face of node failure/unreachable, the other controllers may be a better choice. 
See also: https://stackoverflow.com/questions/41499985/statefulset-pods-stuck-in-unknown-state/41500381#41500381

**Comment by guillelb** [comment]
Thank you @crimsonfaith91, that was the problem.

**Comment by crimsonfaith91** [comment]
You are welcome! :)
