### ISSUE TITLE
API Authentication Success status

### ISSUE THREAD

**Issue by petervo** [kubernetes/kubernetes#47247]
If anonymous access is turned on (default as of 1.6), as far as I can tell it is not currently possible to determine if authentication headers that were passed along succeeded and were used or if the system as defaulted back to system:anonymous.

This makes for bad UI for tools that want to give feedback to end users if the given credentials worked or not such as the proposed ```kubectl login``` command. (https://github.com/kubernetes/community/blob/master/contributors/design-proposals/kubectl-login.md)

I almost feel like system:anonymous should be reserved for requests that did not present any credentials at all as part of the request. If the request had an Authorization header or used a client cert and those credentials did not validate then we should return a 401 and fail the request. 

But I'm assuming that was already discussed and there are reasons that we chose not to do that. If that's the case then are other options that could be added to make this work.

There have been several proposals that I've found that would resolve this but none seem to have gotten enough traction.

There is #30829 which would have added headers that would have allowed checking if the auth succeeded. That was closed for lack of activity. There is #30784 which would add a whoami endpoint, but judging from the comments seems unlikely to get in.

Another suggestion I had was to add the user data back to to SubjectAccessReviewStatus so that SelfSubjectAccessReview requests can report back what was actually used to check for access. That would allow a check to see if the creds passed were actually used or if we defaulted back to system:anonymous.

**Comment by petervo** [comment]
Let's see if i got this right.

@kubernetes/sig-auth-misc
/sig sig-auth

**Comment by ericchiang** [comment]
Some credentials do result in 401. For example https://github.com/kubernetes/kubernetes/pull/47196

What credentials are you using that are dropping back to the anonymous user?

**Comment by enj** [comment]
As far as I can tell the anonymous authenticator is always unioned using `NewFailOnError`, meaning that you should only be the anonymous if the other earlier authenticator chain did not error.

```go
if c.Anonymous {
	authenticator = unionauth.NewFailOnError(authenticator, anonymous.NewAuthenticator())
}
```

**Comment by petervo** [comment]
I've seen this with basic auth, using --basic-auth-file and  --authorization-mode=RBAC. I assumed it was similar with others but didn't test.

```curl -k -u bad:pw https://example.kube.domain/api/v1/nodes```

Returns 403 instead of 401

**Comment by liggitt** [comment]
when I run with --basic-auth-file=... and --authorization-mode=RBAC, I get:

```
$ curl -k -u foo:bar https://localhost:6443/api/v1/nodes -v
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 6443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: kubernetes.default
* Server auth using Basic with user 'foo'
> GET /api/v1/nodes HTTP/1.1
> Host: localhost:6443
> Authorization: Basic Zm9vOmJhcg==
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Content-Type: text/plain; charset=utf-8
* Authentication problem. Ignoring this.
< Www-Authenticate: Basic realm="kubernetes-master"
< X-Content-Type-Options: nosniff
< Date: Fri, 09 Jun 2017 16:32:31 GMT
< Content-Length: 13
< 
Unauthorized
```

**Comment by liggitt** [comment]
same for a bad bearer token:

```
$ curl -k -H "Authorization: Bearer bad" https://localhost:6443/api/v1/nodes -v
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 6443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: kubernetes.default
> GET /api/v1/nodes HTTP/1.1
> Host: localhost:6443
> User-Agent: curl/7.51.0
> Accept: */*
> Authorization: Bearer bad
> 
< HTTP/1.1 401 Unauthorized
< Content-Type: text/plain; charset=utf-8
< Www-Authenticate: Basic realm="kubernetes-master"
< X-Content-Type-Options: nosniff
< Date: Fri, 09 Jun 2017 16:34:48 GMT
< Content-Length: 13
< 
Unauthorized
```

**Comment by petervo** [comment]
This is on image: gcr.io/google_containers/kube-apiserver-amd64:v1.6.4

```
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-allowed-names=front-proxy-client
    - --experimental-bootstrap-token-auth=true
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --insecure-port=8080
    - --insecure-bind-address=0.0.0.0
    - --basic-auth-file=/etc/kubernetes/passwd
    - --storage-backend=etcd3
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --secure-port=6443
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,Persistee
ntVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds
    - --allow-privileged=true
    - --requestheader-username-headers=X-Remote-User
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client..
crt
    - --experimental-bootstrap-token-auth=true
    - --service-cluster-ip-range=10.96.0.0/12
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --authorization-mode=RBAC
    - --advertise-address=10.111.114.23
    - --etcd-servers=http://127.0.0.1:2379
```    

curl -vv -k -u foo:bar https://10.96.0.1/api/v1/nodes

```
* About to connect() to 10.96.0.1 port 443 (#0)
*   Trying 10.96.0.1...
* Connected to 10.96.0.1 (10.96.0.1) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate not found (nickname not specified)
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=kube-apiserver
* 	start date: Jun 09 08:45:22 2017 GMT
* 	expire date: Jun 09 08:45:22 2018 GMT
* 	common name: kube-apiserver
* 	issuer: CN=kubernetes
* Server auth using Basic with user 'foo'
> GET /api/v1/nodes HTTP/1.1
> Authorization: Basic Zm9vOmJhcg==
> User-Agent: curl/7.29.0
> Host: 10.96.0.1
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Content-Type: text/plain
< X-Content-Type-Options: nosniff
< Date: Fri, 09 Jun 2017 16:36:52 GMT
< Content-Length: 63
< 
* Connection #0 to host 10.96.0.1 left intact
User "system:anonymous" cannot list nodes at the cluster scope.

```

Bad bearer token does give me a 401

@liggitt, see anything there that differs from your setup? Or is this a bug fixed on master?

**Comment by ericchiang** [comment]
The password file always returns `nil, false, nil` so it should be returning a 403[1]. Because it can potentially be unioned with other password based auth-N plugins, just looking at the password file plugin this seems correct.

[1] https://github.com/kubernetes/kubernetes/blob/3a5df705fe2af3031262a322f90689a7f212062d/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/password/passwordfile/passwordfile.go#L81-L90

**Comment by liggitt** [comment]
looks like the basic auth method was made consistent with bearer tokens in https://github.com/kubernetes/kubernetes/pull/41775

**Comment by petervo** [comment]
@liggitt tx. Sorry for the noise.
