### ISSUE TITLE
syncDaemonSet should retrieve nodeList once and pass it to other functions

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#47243]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

DaemonSetsController
syncDaemonSet
cache
dsLister

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

in `kubernetes/pkg/controller/daemon/daemoncontroller.go` we have several calls to functions that lists again and again nodes, these functions are : 

on `update.go` 
 ```go
func (dsc *DaemonSetsController) getUnavailableNumbers(ds *extensions.DaemonSet, nodeToDaemonPods map[string][]*v1.Pod) (int, int, error)
```

and on `daemoncontroller.go`

```go
func (dsc *DaemonSetsController) updateDaemonSetStatus(ds *extensions.DaemonSet)
```

```go
func (dsc *DaemonSetsController) manage(ds *extensions.DaemonSet) (string, error) 
```

we should factour out the node list and pass it through function to avoid unnecessary computations

**Comment by kargakis** [comment]
@kubernetes/sig-apps-misc

**Comment by enisoc** [comment]
I did this in #42173 and had to revert it in https://github.com/kubernetes/kubernetes/pull/42173/commits/fac372d0905defdd32e25da1bdeb446dce15bf9c because DaemonSet depends on the re-list within a single sync. It's possible to fix this, but it would require modifying DaemonSet to not take multiple actions per sync.

**Comment by yastij** [comment]
@enisoc - but would we benefit from an action per sync ? Are you working on it ?

**Comment by enisoc** [comment]
I think the benefit might be code that's easier to reason about and is more consistent with other controllers. It would be a refactor that shouldn't change external behavior much. In particular, it wouldn't really let us decrease the number of times the node list is retrieved (which is probably from a cache anyway) since we would immediately requeue and do another sync to trigger the next phase of action.

I don't have plans to work on it, but I agree it's a worthy goal if someone is interested in doing the refactor.

**Comment by yastij** [comment]
@enisoc - will submit a PR next week then.

**Comment by yastij** [comment]
@enisoc - sorry for the delay, was caught by some issues on docker.

by requeue, we mean use the `queue workqueue.RateLimitingInterface` after each action of update/manage and return, the sync is trigerred automatically ?

Thanks !

**Comment by enisoc** [comment]
Yes, it would basically be like you said - after taking an action, add yourself back to the queue and return success.

However, the tricky part will be making sure that the overall behavior is still correct after switching to this pattern. You may need to refactor some of the controller logic.

I don't know enough about DaemonSet to know what issues you might run into, but perhaps @janetkuo can comment.

**Comment by janetkuo** [comment]
@yastij feel free to assign me as reviewer of your PR with the command `/assign @janetkuo`

**Comment by yastij** [comment]
@janetkuo - i'll assign you as reviewer as soon as it's done.

Thanks !

**Comment by yastij** [comment]
@janetkuo - do we count updateDaemonSetStatus as an action ? or just update and manage

**Comment by yastij** [comment]
@janetkuo - this one is still a WIP. Should we wait until #48190 is merged ?

**Comment by enisoc** [comment]
Updating status shouldn't count as an action. You'll often want to update your status to indicate the state of the world that you (the controller) saw when you decided to take an action. So each action is usually accompanied by a status update as well.

I don't think you need to wait for #48190 to continue working on this. There is a reasonable chance that you won't have conflicts given the part of the code that's touching.

**Comment by yastij** [comment]
@enisoc - yes that's what i assumed. since #48190 is not a blocker, I'll clean up a bit and submit the PR by tomorrow.
