### ISSUE TITLE
Initializers for non-domain API groups

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#47240]
At https://github.com/kubernetes/kubernetes/blob/80a53d52fd32c49a5facb34453b6d1cd1d868434/pkg/apis/admissionregistration/validation/validation.go#L48-L48 at least 2 dots are required in the api group strings of an `InitializersConfiguration`. Is this intentional? It stops you from installing initializer controllers for groups like `batch` or `apps`.

**Comment by smarterclayton** [comment]
That's a bug in api groups - the rule is only for the initializer name.  Without a fix here you can't use initializers on deployments or jobs.

**Comment by smarterclayton** [comment]
@kubernetes/sig-api-machinery-pr-reviews I think this is required for 1.7 if we want initializers to be usable for deployments or jobs.

**Comment by caesarxuchao** [comment]
```golang
	if len(strings.Split(initializer.Name, ".")) < 3 {
		allErrors = append(allErrors, field.Invalid(fldPath.Child("name"), initializer.Name, "should be a domain with at least two dots"))
	}
```

@sttts the code you pasted is verifying the initializer.Name, not the group name, so there is no bug. Did i miss something?

**Comment by sttts** [comment]
@caesarxuchao you are right. in my example I had assume the name is related to the group name, but it isn't. Closing.
