### ISSUE TITLE
Kubectl apply should change the env variables order as per the new order

### ISSUE THREAD

**Issue by kumudt** [kubernetes/kubernetes#47248]
**Kubernetes version** (use `kubectl version`): 1.6.4

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.2 LTS
- **Kernel** (e.g. `uname -a`): 4.4.0-1013-aws
- **Install tools**: Kops

**What happened**:
I was trying to reference one env variable inside other in a deployment as per this [doc](https://kubernetes.io/docs/resources-reference/v1.6/#envvar-v1-core). The first variable is set using Downward API and the next one references the first one. The order was appropriate. These changes I made to the existing deployment and used kubectl apply to update my environment. The first variable which will set from the Downward API is moved to the end of the env variables list in the deployment. As a result, the variable which is referencing this is not able to resolve the value of the first variable. I had to delete the deployment and recreate it to make this work.

**What you expected to happen**:

When I did kubectl apply on the existing deployment, the variables order should be as per the new file.

**How to reproduce it** (as minimally and precisely as possible):
* Create a deployment with some env variables.
* Add a new env variable which uses Downward API to the top of the env variable list.
* Reference that env variable inside some other existing env variable defined below that.
* Use kubectl apply to update the deployment.
* Use kubectl get deployment -o yaml to check the env variables order. You can see that the variable defined at the top is now at the bottom of the variable list.

**Comment by mengqiy** [comment]
dup of https://github.com/kubernetes/kubernetes/issues/40373.
Should have be fixed in 1.7 by #45980

**Comment by kumudt** [comment]
Great. Thanks!
Closing this issue.
