### ISSUE TITLE
`Container Image` should not be marked as optional in v1 api

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#47244]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L1661-L1662

```
// A single application container that you want to run within a pod.
type Container struct {
	// Name of the container specified as a DNS_LABEL.
	// Each container in a pod must have a unique name (DNS_LABEL).
	// Cannot be updated.
	Name string `json:"name" protobuf:"bytes,1,opt,name=name"`
	// Docker image name.
	// More info: https://kubernetes.io/docs/concepts/containers/images
	// +optional
	Image string `json:"image,omitempty" protobuf:"bytes,2,opt,name=image"`
....
}
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by gyliu513** [comment]
@kubernetes/sig-api-machinery-bugs 
/assign

**Comment by bgrant0607** [comment]
For the record, this issue was incorrect. The image field was deliberately optional, and this was a non-backward-compatible change to the API.

https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md#on-compatibility
https://github.com/kubernetes/kubernetes/issues/8702#issuecomment-105707367
https://github.com/kubernetes/kubernetes/issues/1697#issuecomment-202631815
