### ISSUE TITLE
iSCSI iSER mounting does use glob path for mount utilities

### ISSUE THREAD

**Issue by Thoro** [kubernetes/kubernetes#47253]
**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-beta.1", GitCommit:"dfaba882698e26a47fb769be45fe5c048a9fe4ad", GitTreeState:"not a git tree", BuildDate:"2017-06-08T13:08:32Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:38:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Bare-Metal, HP SE316M, 2x X5675, 144GB, iSCSI/RDMA/iSer
- **OS**: CentOS 7
- **Kernel**: Linux at-host-18 4.9.31 #1 SMP Wed Jun 7 22:40:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: 
- **Others**:

**What happened**:
I want to mount a iSCSI volume via iSER (RDMA over Infiniband) in this case the iSCSI iface is "iser" and not tcp, therefore the glob path for device mount is selected (iscsi_util.go:215), which then is passed to the fsck and mount commands without globbing the path (e.g. calling filepath.Glob)

Therefore the iSCSI volume is not mounted and the pod cannot be started.

**Logs**:
```
Jun  9 16:59:35 at-host-18 kernel: sd 5:0:0:0: alua: supports implicit and explicit TPGS
Jun  9 16:59:35 at-host-18 kernel: sd 5:0:0:0: alua: device naa.600140581cc879dd8a646fb9d818e1cf port group 0 rel port 1
Jun  9 16:59:35 at-host-18 kernel: sd 5:0:0:0: alua: port group 00 state A non-preferred supports TOlUSNA
Jun  9 16:59:35 at-host-18 kernel: sd 5:0:0:0: alua: supports implicit and explicit TPGS
Jun  9 16:59:35 at-host-18 kernel: sd 5:0:0:0: alua: device naa.600140581cc879dd8a646fb9d818e1cf port group 0 rel port 1
Jun  9 16:59:35 at-host-18 kernel: sd 5:0:0:0: alua: port group 00 state A non-preferred supports TOlUSNA
Jun  9 16:59:35 at-host-18 kubelet: I0609 16:59:35.354226   18204 mount_linux.go:347] `fsck` error fsck from util-linux 2.23.2
Jun  9 16:59:35 at-host-18 kubelet: fsck.ext2: No such file or directory while trying to open /dev/disk/by-path/pci-*-ip-10.0.13.3:3260-iscsi-iqn.2017-01.at.cf-it.at-storage-01-lun-0
Jun  9 16:59:35 at-host-18 kubelet: Possibly non-existent device?
Jun  9 16:59:35 at-host-18 kubelet: E0609 16:59:35.358239   18204 mount_linux.go:122] Mount failed: exit status 32
Jun  9 16:59:35 at-host-18 kubelet: Mounting command: mount
Jun  9 16:59:35 at-host-18 kubelet: Mounting arguments: /dev/disk/by-path/pci-*-ip-10.0.13.3:3260-iscsi-iqn.2017-01.at.cf-it.at-storage-01-lun-0 /var/lib/kubelet/plugins/kubernetes.io/iscsi/iface-iser/10.0.13.3:3260-iqn.2017-01.at.cf-it.at-storage-01-lun-0 ext4 [defaults]
Jun  9 16:59:35 at-host-18 kubelet: Output: mount: special device /dev/disk/by-path/pci-*-ip-10.0.13.3:3260-iscsi-iqn.2017-01.at.cf-it.at-storage-01-lun-0 does not exist
Jun  9 16:59:35 at-host-18 kubelet: E0609 16:59:35.362929   18204 mount_linux.go:406] Could not determine if disk "/dev/disk/by-path/pci-*-ip-10.0.13.3:3260-iscsi-iqn.2017-01.at.cf-it.at-storage-01-lun-0" is formatted (exit status 1)
Jun  9 16:59:35 at-host-18 kubelet: E0609 16:59:35.362987   18204 iscsi_util.go:301] iscsi: failed to mount iscsi volume /dev/disk/by-path/pci-*-ip-10.0.13.3:3260-iscsi-iqn.2017-01.at.cf-it.at-storage-01-lun-0 [ext4] to /var/lib/kubelet/plugins/kubernetes.io/iscsi/iface-iser/10.0.13.3:3260-iqn.2017-01.at.cf-it.at-storage-01-lun-0, error exit status 1
Jun  9 16:59:35 at-host-18 kubelet: E0609 16:59:35.363008   18204 disk_manager.go:51] failed to attach disk
Jun  9 16:59:35 at-host-18 kubelet: E0609 16:59:35.363022   18204 iscsi.go:247] iscsi: failed to setup
```

**What you expected to happen**:
To successfully mount the volume.

**How to reproduce it** (as minimally and precisely as possible):
Setup an iSCSI via RDMA (iSER) environment without multipath and try to mount a volume for a pod.

**Anything else we need to know**:
I believe it's just needed to add the globbing at line 259 like so:

devicePaths = append(devicePaths, filepath.Glob(devicePath))

As I'm not a go programmer and have no experience with it, probably somebody could create a commit which I would gladly test!

**Comment by mtanino** [comment]
@Thoro

I'll take a look.

**Comment by Thoro** [comment]
@mtanino on a local build that fixed the issue:
```
    glog.V(4).Infof("iscsi: devicepath (%s) exists", devicePath)

    fpath, _ := filepath.Glob(devicePath)
    if fpath != nil {
       devicePaths = append(devicePaths, fpath[0])
    }
```

(e.g. it compiles)

**Comment by mtanino** [comment]
@Thoro 
I don't want to add filepath.Glob to that general path because that line is also executed "tcp" case.
I'm considering the fix below. Pretty similar.

```
func waitForPathToExistInternal(devicePath string, maxRetries int, deviceTransport string, osStat StatFunc, filepathGlob GlobFunc) (bool, string) {
	for i := 0; i < maxRetries; i++ {
		var err error
		if deviceTransport == "tcp" {
			_, err = osStat(devicePath)
		} else {
			fpath, _ := filepathGlob(devicePath)
			if fpath == nil {
				err = os.ErrNotExist
			}
			// There might be a case that fpath contains multiple device paths if
			// multiple PCI devices connect to same iscsi target. We handle this
			// case at subsequent logic. Pick up only first path here.
			devicePath = fpath[0]
		}
```

**Comment by Thoro** [comment]
@mtanino does that work from a go specific point? is that devicePath passed by reference? (from general c/c++/php/node/c# knowledge I would say that this would have no effect on the devicePath variable .. )

**Comment by mtanino** [comment]
@Thoro
Can we suppose that filepath.Glob(devicePath) always only return one device path if transport is "tcp"?

**Comment by mtanino** [comment]
@Thoro 
>>does that work from a go specific point? is that devicePath passed by reference? (from general c/c++/php/node/c# knowledge I would say that this would have no effect on the devicePath variable .. )

Thank you for above comment. I updated the logic.
Could you confirm the fix on the PR?

**Comment by Thoro** [comment]
@mtanino Pretty sure that tcp transport will always only have one path - and it will exist (there's no glob in the check path)
