### ISSUE TITLE
Calico needs updating in kube-up

### ISSUE THREAD

**Issue by caseydavenport** [kubernetes/kubernetes#47269]
**Kubernetes version** (use `kubectl version`):
master

**Environment**:
- **Cloud provider or hardware configuration**: GCE using kube-up
- **OS** (e.g. from /etc/os-release): GCI
- **Install tools**: kube-up

**What happened**:

Kubernetes apiserver is not able to keep up with Pod / NetworkPolicy watches when running a large cluster using Calico.

Additionally, Calico is still using its own MASQUERADE implementation, while the kube-up scripts have been modified to now deploy the ip-masq-agent.  

**What you expected to happen**:

- Calico should use the [typha](https://github.com/projectcalico/typha) fanout service for efficient api access.  
- calico/node resource requests should be sized based on the cluster size.
- Calico should use the ip-masq-agent for MASQUERADE.

**Anything else we need to know**:

Fix is in PR #47188

**Comment by bowei** [comment]
Bug fix for fixing scalability issues with the network policy provider.

/approve
