### ISSUE TITLE
Need to set hostname for container but not in YAML spec.

### ISSUE THREAD

**Issue by choppsv1** [kubernetes/kubernetes#47268]
FEATURE REQUEST

We have a somewhat non-typical use of k8s. We aren't using scaling but we are deploying applications. We create multiple network interfaces for said apps in each pod (using custom CNI module). We need to assign a fixed hostname in a given container based on which k8s cluster it is running on.

Since I have my own custom CNI I tried setting tthe hostname there (nsenter --uts); however, it doesn't take as CNI is run on the "pause" container and the real container does not inherit the hostname from it. I even used the "hostnamepath" value from docker inspect to change the /etc/hostname value, but that too is ignored by the real container.

I need a way to set this value, and we can't do it in the YAML for the deployment b/c that needs to be generic and work everywhere.

I would love to hear of a way of doing this, so far though I haven't found one.

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-beta.0", GitCommit:"e3db58e39a3ff1012efdf646c727278b82299c5e", GitTreeState:"clean", BuildDate:"2017-06-02T05:20:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-beta.0", GitCommit:"e3db58e39a3ff1012efdf646c727278b82299c5e", GitTreeState:"clean", BuildDate:"2017-06-02T05:00:07Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
Custom server environment.

- **OS** (e.g. from /etc/os-release):
VERSION="16.04.2 LTS (Xenial Xerus)"

- **Kernel** (e.g. `uname -a`):
Linux xxxx 4.10.0-22-generic #24~16.04.1-Ubuntu SMP Tue May 23 17:03:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by choppsv1** [comment]
@kubernetes/sig-network

**Comment by jagosan** [comment]
/sig network

@choppsv1 - thanks for mentioning groups, this will trigger notifications correctly.  just adding sig for labeling (see bot command above for future reference).

**Comment by mlowery** [comment]
@choppsv1: We have a somewhat similar use case in that the hostname depends on where the pod lands. In our case, we're running Kubernetes 1.6 (where `spec.hostname` can be set after pod is admitted). So we have a custom controller that watches pods and sets `spec.hostname`. (This will need to change as I think 1.8 now prevents `spec.hostname` from being set after pod admission.) But let's ignore that for now.

The key to this solution (works for us at least) is to not start any containers until `spec.hostname` is set. To do that, we used a custom "soft admit handler" in kubelet that simply returns an error if `spec.hostname` is not set. And when it ultimately is set, the soft admit handler then returns `nil`, then the `pause` container is created, and then the process continues as normal. Here's the [code](https://github.com/kubernetes/kubernetes/compare/release-1.6...mlowery:hostname-soft-handler2?expand=1).

**Comment by choppsv1** [comment]
@mlowery Very interesting, unfortunately we're running close to the latest releases and currently we're on 1.8.2, so it sounds like this won't work for us.

**Comment by thockin** [comment]
I don't understand what "based on where it lands" means.

Can you simply run a privileged init container and set the hostname that way?  Or do you expect it to propagate to DNS?

**Comment by choppsv1** [comment]
I edited the text to tried to clarify this, it now reads "based on which k8s cluster it is running on." That text is really not that important though. The key is that I need to set the hostname during CNI initialization and I can't. Doing this during CNI when I actually assing the IP addresses that the hostname maps to seems like the obvious place, right?

I believe your suggestion is that I can work around not being able to do this by adding an init container to every manifest/pod in the system (including future ones) that sets the hostname? That might work which is good, but it's definitely a work-around, this is infrastructure stuff and applications shouldn't need to worry about it, I think.

**Comment by choppsv1** [comment]
BTW, we've worked around this for now by using manifest templates and substituting the value for hostname in the manifest.

**Comment by mlowery** [comment]
@thockin:

> I don't understand what "based on where it lands" means.

In my case, I meant that the hostname depended on which node the pod was scheduled to. Furthermore, DNS records were handled not via kube-dns but via another custom controller that created the records, along with `dnsPolicy: Default` on the pod. With a proper `search` in `/etc/resolv.conf` and an unfortunate edit to `/etc/hosts` (removing the pod IP line) (see #57039), we got `hostname -f` to use a nameserver-based resolution. This is a long-winded way of stating that I had no expectations of DNS records.

I'm not very familiar with the differences in the levels of control one has with CNI vs. init container but if it doesn't work for CNI, why would it work for init container? To be clear, I have tested neither.

@choppsv1:

Regarding a "manifest template," is this some feature of Kubernetes or are you simply saying that you somehow "pre-schedule" such that the hostname is known at pod creation time?

**Comment by choppsv1** [comment]
@mlowery We are running our pod manifests through envsubst prior handing them to k8s. I don't believe there's any k8s template or variable substitution mechanism currently, although simple envsubst/bash-like variable substitution would be a great addition. So we specify the hostname in the manifest using a using a pod-specific suffix and a variable prefix (e.g., hostname: "${PREFIX}-cassandra"). The prefix is set based on which cluster the manifest is applied on. Again this is all done before k8s is given the manifest.

What I'd prefer to be able to do is assign the hostname inside the CNI plugin (which has all this info) and leave it out of the manifest altogether.

**Comment by Xtigyro** [comment]
@choppsv1 Could you please reopen the issue?

**Comment by Xtigyro** [comment]
> /reopen

@choppsv1 Thank you!
