### ISSUE TITLE
AWS getInstancesByNodeNames is broken for large clusters

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#47271]
From CloudTrail logs:

```
    "errorMessage": "The maximum number of filter values specified on a single call is 200",
```

This affects both load balancer and volume features that rely on `getInstancesByNodeNames` 

cc @justinsb

**Comment by gnufied** [comment]
We can workaround this somewhat by implementing batching of describeInstance calls by N number of nodes at a time.

**Comment by justinsb** [comment]
We should do caching.

**Comment by rodawg** [comment]
Isn't this a duplicate?

https://github.com/kubernetes/kubernetes/issues/45050

**Comment by justinsb** [comment]
It is @rodawg  - sorry we didn't observe your prior report!

**Comment by rodawg** [comment]
No worries, just trying to get a handle on this issue!

**Comment by justinsb** [comment]
As I mentioned here https://github.com/kubernetes/kubernetes/issues/45050#issuecomment-308451376 , I propose we keep this issue for EBS and #45050 for ELBs, as I think they may well turn out to have different solutions.

**Comment by marun** [comment]
@justinsb Is there more work remaining for this issue pending for 1.7?

**Comment by justinsb** [comment]
We believe this is fixed.  Closing.

**Comment by justinsb** [comment]
(By #47516)
