### ISSUE TITLE
Need to bump GLBC version in manifest

### ISSUE THREAD

**Issue by nicksardo** [kubernetes/kubernetes#47273]
There are multiple bugs in GLBC v0.9.3 which have been fixed in tip of master.  The glbc.manifest file needs to get the latest version before 1.7.0 release.

**Comment by bowei** [comment]
@nicksardo is waiting to see if bug fix is possible before the final freeze before cutting the update

**Comment by bowei** [comment]
@nicksardo freeze is wednesday, I would update the manifest sooner rather than wait.
