### ISSUE TITLE
[GCE] Some system pods are not marked critical

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#47277]
@cheftako and @bsalamat brought to my attention that a number of our system pods are not marked critical.  As the critical pod annotations are enabled in GCE, it is important that we are intentional about which pods are marked critical.  Looking through my local cluster created today, I see the following kube-system pods that are NOT marked critical:

etcd-empty-dir-cleanup-kubernetes-master (static)
etcd-server-events-kubernetes-master (static)
etcd-server-kubernetes-master (static)
event-exporter-v0.1.0-947590526-h897n (non-static)
kube-addon-manager-kubernetes-master (static)
kube-apiserver-kubernetes-master (static)
kube-controller-manager-kubernetes-master (static)
kube-scheduler-kubernetes-master (static)
l7-default-backend-4019876529-14krg (non-static)
l7-lb-controller-v0.9.3-kubernetes-master (static)
monitoring-influxdb-grafana-v4-2dv01 (non-static)
rescheduler-v0.3.0-kubernetes-master (static)

I am not sure who the owner of each of these is, and some (especially non-static) may not need to be marked critical.
**Static pods that are not marked critical can be evicted or preempted, and will never be rescheduled**, so we should almost definitely mark static system pods as critical, and should at least consider marking the non-static ones as critical.

cc @davidopp @dchen1107 @vishh @piosz for people who might know who the owners of each of these pods are.

**Comment by dashpole** [comment]
It is also worth noting that with the addition of the NPD, the total CPU requests on the master exceed 1 CPU.  We should probably change the default master size on GCE to 2 cpu machines, or lower the requests of some pods on the master.

**Comment by vishh** [comment]
As a side effect of this, a daemonset with critical pods will render the master unstable permanently in GCE.

**Comment by dchen1107** [comment]
@dashpole I am fine to mark all static kube-system pods as the critical ones for now, but not comfortable for all kube-system pods.

**Comment by dchen1107** [comment]
Even for static pods on master node, I wouldn't accept #47356 as is unless someone publish the stats on  sum(all static pods on the master node's request). Also we should make sure our e2e master node is bigger enough to run those static & critical pods by default. Please note that once those static pods marked as critical, Kubelet would blindly admit them and stop evicting them. 
Had offline chat with @davidopp and @bsalamat on this topic, and @bsalamat is going to figure out this.

**Comment by bsalamat** [comment]
Looks like we are running out of CPU on the master in a default deployment of a small cluster. I brought up a small cluster with 3 minions and a larger master node than usual. [Here](https://docs.google.com/a/google.com/spreadsheets/d/111HzcMGQj4VVPLy3_aIz7rw_E_-zCavOtThgNCNSuvM/edit?usp=sharing) you can see the pods and their resource requests on the master node.
I would suggest reducing CPU requests for some of the pods to make sure our total remains under 1 CPU request.
This will probably solve part of the problem in hand, but running daemonsets may still cause issues as daemonset controller does not do resource checks and may schedule more pods on the master. Once we mark all the important static pods on the master as critical, a daemonset won't break the master, but the daemonset pods will probably be rejected/evicted by the kubelet.

**Comment by piosz** [comment]
event-exporter-v0.1.0-947590526-h897n
monitoring-influxdb-grafana-v4-2dv01
are not marked as critical by design

cc @crassirostris

**Comment by marun** [comment]
Any update on this?  I would expect more activity if this should continue blocking 1.7.

**Comment by roberthbailey** [comment]
https://github.com/kubernetes/kubernetes/pull/47356 is ready to go and is 4th is the submit queue.

**Comment by davidopp** [comment]
I updated @bsalamat's spreadsheet by adding a second tab that shows request and limit for all pods on master and nodes, as observed on a default cluster built from HEAD that I brought up using kube-up.sh on GCE yesterday. It also indicates for each whether it is a critical pod, and the allocatable of master and nodes.
