### ISSUE TITLE
[e2e fail] gce-alpha-features is completely broken for months

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#47283]
both gce-alpha-features and gci-gce-alpha-features have been broken for more than a month:

https://k8s-testgrid.appspot.com/release-master-blocking#gce-alpha-features 
https://k8s-testgrid.appspot.com/release-master-blocking#gci-gce-alpha-features

I checked the test configuration, and found they are still running some staled tests. For example, PetSet and ScheduledJob

```
W0609 16:33:35.155] +(/workspace/e2e-runner.sh:93): main(): [[ -n --ginkgo.focus=\[Feature:(PetSet|DynamicKubeletConfig|Audit)\]|ScheduledJob ]]
W0609 16:33:35.155] +(/workspace/e2e-runner.sh:94): main(): e2e_go_args+=(--test_args="${GINKGO_TEST_ARGS}")
```

On another hand, Audit is important feature for 1.7, and those tests are still valid. I am going to clean the test infra for this. cc/ @timstclair @kubernetes/kubernetes-release-managers @ericchiang

**Comment by liggitt** [comment]
I see things like this in the master log:

```
I0613 12:38:33.129418       5 rbac.go:114] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "list" resource "pods" cluster-wide
I0613 12:38:33.129475       5 wrap.go:42] GET /api/v1/pods?fieldSelector=spec.nodeName%3Dbootstrap-e2e-master&resourceVersion=0: (157.399Âµs) 403 [[kubelet/v1.8.0 (linux/amd64) kubernetes/5d2dbb5] 
```

It seems the kubelet is not set up to authenticate to the API? I'm not familiar with this e2e setup, @timstclair do you know what scripts set up this env?

**Comment by timstclair** [comment]
This cluster is brought up with the `AllAlpha=true` flag. I suspect this is related to the kubelet certificate rotation.

**Comment by liggitt** [comment]
many alpha features require additional setup or have external requirements... I'm not surprised "blindly turn on all alpha features" doesn't work well, generally.

**Comment by marun** [comment]
If this should be blocking 1.7, please label with 'approved-for-milestone'.

**Comment by liggitt** [comment]
Jobs are green again
