### ISSUE TITLE
Investigate on how to decouple containers' lifecycle from daemon

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#4729]
Today kubelet relies on docker daemon to control the lifecycle of a container; when docker daemon is restarted, all running containers have to be restarted. This is not acceptable behavior for many services, especially high-availability ones since docker daemon could  be crash, or upgraded. We need to figure out how to fix such issue if docker couldn't. 

We talked about this offline many times, and file this issue  to ensure we don't forget about this. cc/ @thockin

**Comment by rjnagal** [comment]
@dchen1107 Is this meant to track a solution in docker, or a workaround in kubelet? A possible kubelet workaround would be to add a task manager that does image pulls and interfaces directly with libcontainer. Are there other lighter weight alternatives?  Not sure if maintaining a task management layer is feasible for P1 timeframe.

**Comment by dchen1107** [comment]
This is not part of v1 roadmap.

**Comment by dims** [comment]
Guess we get this for free with containerd from Docker 1.11? https://blog.docker.com/2016/04/docker-containerd-integration/

Can we close this bug?
