### ISSUE TITLE
Control plane images aren't pushed for {arm,arm64,ppc64le,s390x} on release

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#47307]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`): HEAD

Since v1.7.0-alpha.3, control plane images are only pushed for amd64.
Compare: https://gcr.io/v2/google_containers/kube-apiserver-amd64/tags/list to https://gcr.io/v2/google_containers/kube-apiserver-arm/tags/list

_This is a release-blocker and should be fixed ASAP._

I guess the actual regression code-wise happened in test infra.

cc @kubernetes/kubernetes-release-managers @kubernetes/sig-testing-bugs @kubernetes/sig-release-bugs @ixdy

**Comment by ixdy** [comment]
also cc @caesarxuchao

**Comment by ixdy** [comment]
Still looking, but #45391 "Only tag release containers if the name is different." makes me suspicious.

**Comment by ixdy** [comment]
oh, this is a bug introduced by #44981. fix should be easy.

**Comment by luxas** [comment]
@spiffxp I can open a new issue as well to track what I added sig-testing for but I want us to set up the required testing to make sure this never happens again

**Comment by spiffxp** [comment]
@luxas the removal was under the guise of "sig testing doesn't control the cutting of bits", if there are tests that need to be put in place to ensure all the right things are cut/released, I would expect sig-release to track that

**Comment by luxas** [comment]
@spiffxp Sounds good

**Comment by ixdy** [comment]
Details about the exact bug and the fix are in #47359.

The reason we didn't notice this sooner is that anago only [warns](https://github.com/kubernetes/release/blob/d3f5437c6f14ea6e8cfeb6df8e196499720b4c3a/lib/releaselib.sh#L831) if the required image doesn't exist - it does so because we don't support all arches for all release versions, and we didn't want to hard-code a list of expected versions into the release repo.

(Also, anago automatically [tags the legacy name](https://github.com/kubernetes/release/blob/d3f5437c6f14ea6e8cfeb6df8e196499720b4c3a/lib/releaselib.sh#L839-L840), so we were still pushing the legacy versions - we were only dropping the non-amd64 images with this bug.)

**Comment by caesarxuchao** [comment]
Can we add a `common::askyorn` after the warns? Otherwise even is the user of anago sees the warning, there's nothing he can do about it.

**Comment by david-mcmahon** [comment]
Anago is moving toward being less interactive.  If any checks need to be done, they should be done at build time.  1) Determine what should be built 2) Stop right there if the build fails for whatever reason.

Adding redundant checks comes with the cost of maintaining hardcoded lists in multiple places.  
The push step (and release infra in general) should be agnostic and just push what was built.

**Comment by caesarxuchao** [comment]
> Stop right there if the build fails for whatever reason.

But in this issue, the build was successful, but some images were removed due to the bug.

What i'm concerned with is that when building beta.2 this Wednesday, if a similar problem happens, i won't be able to stop anago from pushing the incomplete image sets.

**Comment by luxas** [comment]
I'm reopening this unless we are really sure that it actually works...

**Comment by luxas** [comment]
> The reason we didn't notice this sooner is that anago only warns if the required image doesn't exist - it does so because we don't support all arches for all release versions, and we didn't want to hard-code a list of expected versions into the release repo.

> (Also, anago automatically tags the legacy name, so we were still pushing the legacy versions - we were only dropping the non-amd64 images with this bug.)

@ixdy How can we create the testing required to stop this from happening again?

**Comment by caesarxuchao** [comment]
I'm doing a dry run today.

**Comment by ixdy** [comment]
@luxas anago could have some sort of sanity checking, though I'm not sure how we'd do that without maintaining hardcoded lists, as @david-mcmahon notes.
I guess the "real" fix is having some automated testing somewhere to consume the non-x86 docker images.

**Comment by caesarxuchao** [comment]
After anago dry run, i saw these images on my machine, so it looks fixed.
```
gcr.io/kubernetes-release-test/hyperkube-ppc64le                  v1.7.0-beta.2                 a5a6e9b1dc5d        4 minutes ago       623.9 MB
gcr.io/kubernetes-release-test/hyperkube-s390x                    v1.7.0-beta.2                 b6f0b2986425        11 minutes ago      631.2 MB
gcr.io/kubernetes-release-test/hyperkube-arm64                    v1.7.0-beta.2                 ac852b146605        18 minutes ago      604.1 MB
gcr.io/kubernetes-release-test/hyperkube-arm                      v1.7.0-beta.2                 728f9bc09882        25 minutes ago      568.5 MB
gcr.io/kubernetes-release-test/hyperkube-amd64                    v1.7.0-beta.2                 74668d3512ca        34 minutes ago      614.3 MB
gcr.io/kubernetes-release-test/kube-controller-manager-ppc64le    v1.7.0-beta.2                 6d08ebd8fc45        41 minutes ago      138.2 MB
gcr.io/kubernetes-release-test/kube-proxy-ppc64le                 v1.7.0-beta.2                 a05eda65342e        41 minutes ago      123.7 MB
gcr.io/kubernetes-release-test/kube-apiserver-ppc64le             v1.7.0-beta.2                 c509b14db987        41 minutes ago      181.2 MB
gcr.io/kubernetes-release-test/cloud-controller-manager-ppc64le   v1.7.0-beta.2                 209b59378af8        41 minutes ago      125.9 MB
gcr.io/kubernetes-release-test/kube-scheduler-ppc64le             v1.7.0-beta.2                 d942adfcd5a7        41 minutes ago      79.45 MB
gcr.io/kubernetes-release-test/kube-aggregator-ppc64le            v1.7.0-beta.2                 a3af627af02b        41 minutes ago      61.48 MB
gcr.io/kubernetes-release-test/kube-proxy-s390x                   v1.7.0-beta.2                 8b45b636331c        43 minutes ago      125.4 MB
gcr.io/kubernetes-release-test/kube-apiserver-s390x               v1.7.0-beta.2                 531225741d30        43 minutes ago      185.4 MB
gcr.io/kubernetes-release-test/kube-scheduler-s390x               v1.7.0-beta.2                 c977206ee609        43 minutes ago      81.58 MB
gcr.io/kubernetes-release-test/kube-controller-manager-s390x      v1.7.0-beta.2                 05da58748587        43 minutes ago      142.2 MB
gcr.io/kubernetes-release-test/cloud-controller-manager-s390x     v1.7.0-beta.2                 8e0ccd03b455        43 minutes ago      129.6 MB
gcr.io/kubernetes-release-test/kube-aggregator-s390x              v1.7.0-beta.2                 73718b2d6533        43 minutes ago      63.15 MB
gcr.io/kubernetes-release-test/cloud-controller-manager-arm64     v1.7.0-beta.2                 0cf3f123f07e        45 minutes ago      124.7 MB
gcr.io/kubernetes-release-test/kube-controller-manager-arm64      v1.7.0-beta.2                 4130f8590138        45 minutes ago      136.9 MB
gcr.io/kubernetes-release-test/kube-proxy-arm64                   v1.7.0-beta.2                 a604b8533f27        45 minutes ago      116.2 MB
gcr.io/kubernetes-release-test/kube-apiserver-arm64               v1.7.0-beta.2                 6f0b4e96bdee        45 minutes ago      184.6 MB
gcr.io/kubernetes-release-test/kube-aggregator-arm64              v1.7.0-beta.2                 1a315666ff00        45 minutes ago      60.11 MB
gcr.io/kubernetes-release-test/kube-scheduler-arm64               v1.7.0-beta.2                 820de2f33723        45 minutes ago      78.02 MB
gcr.io/kubernetes-release-test/kube-proxy-arm                     v1.7.0-beta.2                 b73ffb4954b8        47 minutes ago      100.9 MB
gcr.io/kubernetes-release-test/kube-apiserver-arm                 v1.7.0-beta.2                 e4d95a963b5a        47 minutes ago      169.5 MB
gcr.io/kubernetes-release-test/kube-aggregator-arm                v1.7.0-beta.2                 e03b37a2d46f        47 minutes ago      54.19 MB
gcr.io/kubernetes-release-test/kube-controller-manager-arm        v1.7.0-beta.2                 14fc6b1da81a        47 minutes ago      121.9 MB
gcr.io/kubernetes-release-test/kube-scheduler-arm                 v1.7.0-beta.2                 9ceaa641360d        47 minutes ago      69.96 MB
gcr.io/kubernetes-release-test/cloud-controller-manager-arm       v1.7.0-beta.2                 31691e2116ed        47 minutes ago      110.9 MB
gcr.io/kubernetes-release-test/kube-proxy-amd64                   v1.7.0-beta.2                 2ebfcf8f0f41        49 minutes ago      114.3 MB
gcr.io/kubernetes-release-test/kube-proxy                         v1.7.0-beta.2                 2ebfcf8f0f41        49 minutes ago      114.3 MB
gcr.io/kubernetes-release-test/kube-apiserver-amd64               v1.7.0-beta.2                 82cbfc22e2f7        49 minutes ago      185.1 MB
gcr.io/kubernetes-release-test/kube-apiserver                     v1.7.0-beta.2                 82cbfc22e2f7        49 minutes ago      185.1 MB
gcr.io/kubernetes-release-test/kube-controller-manager-amd64      v1.7.0-beta.2                 9c90996d7bd5        49 minutes ago      136.9 MB
gcr.io/kubernetes-release-test/kube-controller-manager            v1.7.0-beta.2                 9c90996d7bd5        49 minutes ago      136.9 MB
gcr.io/kubernetes-release-test/cloud-controller-manager-amd64     v1.7.0-beta.2                 4f91cd3d3e8a        49 minutes ago      124.3 MB
gcr.io/kubernetes-release-test/cloud-controller-manager           v1.7.0-beta.2                 4f91cd3d3e8a        49 minutes ago      124.3 MB
gcr.io/kubernetes-release-test/kube-aggregator-amd64              v1.7.0-beta.2                 df9a8479abe3        49 minutes ago      59.12 MB
gcr.io/kubernetes-release-test/kube-aggregator                    v1.7.0-beta.2                 df9a8479abe3        49 minutes ago      59.12 MB
gcr.io/kubernetes-release-test/kube-scheduler-amd64               v1.7.0-beta.2                 7f15bf38b895        49 minutes ago      77.12 MB
gcr.io/kubernetes-release-test/kube-scheduler                     v1.7.0-beta.2                 7f15bf38b895        49 minutes ago      77.12 MB
```

**Comment by luxas** [comment]
Thanks @ixdy and @caesarxuchao :tada:!
