### ISSUE TITLE
Support the `cloudprovider.Instances` interface for CloudStack

### ISSUE THREAD

**Issue by svanharmelen** [kubernetes/kubernetes#47303]
I would be nice if the CloudStack cloudprovider would support the `cloudprovider.Instances` interface.

**Comment by spiffxp** [comment]
@thockin @mikedanese since you two were active on the linked PR, just an FYI that I'm arbitrarily tagging this with your respective sigs (as gleaned from looking at github team membership); really this seems like another mark in the "sig-cloud" column
/sig network
/sig cluster-lifecycle
