### ISSUE TITLE
Scheduler performance enhancement

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#47318]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

/kind enhancement

**Kubernetes version** (use `kubectl version`):
master branch

**Description**:
During the discussion at #42002, we found that there's room for scheduler performance improvement, e.g. NodeAffinity predicates took much time (>10m) for 50k pods in 5k nodes, but it'll take 160s after tiny enhancement.

So we'd like to open this issue to trace scheduler performance enhancement.

/cc @davidopp , @timothysc , @gmarek , @wojtek-t

**Comment by k82cn** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by gmarek** [comment]
IIUC a blocker for this are NodeConditions that block scheduling.

**Comment by k82cn** [comment]
yes, NodeConditions is a blocker for DaemonSet, I'm also learning kubelet and try to contribute.

For this issue,  #42002 is only a trigger :). The enhancement will help on performance, so the scalability.

**Comment by gmarek** [comment]
Yup. Thanks for the change - I really want to review it, but I need to deal with performance regressions in 1.7 first...

**Comment by k82cn** [comment]
sure, np; 1.7 first :).

**Comment by jayunit100** [comment]
Yup and without loss of generality all predicates and priorities should be easy to combine and simulate tests in... 

I think ravi has added affinity benchmarks or is working to add them into scheduler_perf , and we are merging all that I guess in 1.8.   If that work is stil moving forward at Red Hat then this will be extremely easy to accurately measure .

**Comment by bsalamat** [comment]
Just wanted to update the issue with the final decision which is to let DaemonSet controller schedule its own pods. That said, we still need to work on improving scheduler's performance.

**Comment by k82cn** [comment]
@bsalamat , I had update the description of this issue for all scheduler performance enhancement (not only for 42002).

xref #54189
