### ISSUE TITLE
issue on arm64: no endpoints,code:503

### ISSUE THREAD

**Issue by whbo158** [kubernetes/kubernetes#47324]
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/arm64"}

**Environment**:
- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- **Kernel** (e.g. `uname -a`):
Linux node4 4.11.0-rc6-next-20170411-00286-gcc55807 #0 SMP PREEMPT Mon Jun 5 18:56:20 CST 2017 aarch64 aarch64 aarch64 GNU/Linux

**What happened**:
I want to use kube-deploy/master.sh to setup master on ARM64, but I encountered the error when visiting $myip:8080/ui:
 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
My branch is 2017-2-7 (c8d6fbfc…)
by the way, It can work on X86-amd64 platform by using the same steps to install.

**Anything else we need to know**:
# 1. kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY     STATUS             RESTARTS   AGE
kube-system   k8s-master-10.193.20.23                 4/4       Running            51         12m
kube-system   k8s-proxy-v1-9n9l7                      1/1       Running            0          13m
kube-system   kube-addon-manager-10.193.20.23         2/2       Running            4          13m
kube-system   kube-dns-3365905565-m4cpk               2/4       CrashLoopBackOff   19         13m
kube-system   kubernetes-dashboard-1416335539-dcf40   0/1       CrashLoopBackOff   6          13m

# 2. kubectl describe pods kube-dns-3365905565-m4cpk --namespace=kube-system
Name:		kube-dns-3365905565-m4cpk
Namespace:	kube-system
Node:		10.193.20.23/10.193.20.23
Start Time:	Fri, 16 Jun 2017 14:01:13 +0800
Labels:		k8s-app=kube-dns
		pod-template-hash=3365905565
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"kube-dns-3365905565","uid":"32fde5d2-5259-11e7-adb6-6805ca36...
		scheduler.alpha.kubernetes.io/critical-pod=
		scheduler.alpha.kubernetes.io/tolerations=[{"key":"CriticalAddonsOnly", "operator":"Exists"}]
Status:		Running
IP:		10.1.5.3
Controllers:	ReplicaSet/kube-dns-3365905565
Containers:
  kubedns:
    Container ID:	docker://4261276702d2ce5d24e63926518200489c98fb94c86f5645f2f50ef763f7aa74
    Image:		gcr.io/google_containers/kubedns-arm64:1.9
    Image ID:		docker-pullable://gcr.io/google_containers/kubedns-arm64@sha256:3c78a2c5b9b86c5aeacf9f5967f206dcf1e64362f3e7f274c1c078c954ecae38
    Ports:		10053/UDP, 10053/TCP, 10055/TCP
    Args:
      --domain=cluster.local.
      --dns-port=10053
      --config-map=kube-dns
      --v=0
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	137
      Started:		Fri, 16 Jun 2017 14:13:46 +0800
      Finished:		Fri, 16 Jun 2017 14:15:23 +0800
    Ready:		False
    Restart Count:	6
    Limits:
      memory:	170Mi
    Requests:
      cpu:	100m
      memory:	70Mi
    Liveness:	http-get http://:8080/healthz-kubedns delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:	http-get http://:8081/readiness delay=3s timeout=5s period=10s #success=1 #failure=3
    Environment:
      PROMETHEUS_PORT:	10055
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xv2t6 (ro)
  dnsmasq:
    Container ID:	docker://ef30d99d93cd320a1e1de808f8416a66effc4341c836b3432539f94fb86f3108
    Image:		gcr.io/google_containers/kube-dnsmasq-arm64:1.4
    Image ID:		docker-pullable://gcr.io/google_containers/kube-dnsmasq-arm64@sha256:dff5f9e2a521816aa314d469fd8ef961270fe43b4a74bab490385942103f3728
    Ports:		53/UDP, 53/TCP
    Args:
      --cache-size=1000
      --no-resolv
      --server=127.0.0.1#10053
      --log-facility=-
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	137
      Started:		Fri, 16 Jun 2017 14:14:36 +0800
      Finished:		Fri, 16 Jun 2017 14:16:13 +0800
    Ready:		False
    Restart Count:	6
    Requests:
      cpu:		150m
      memory:		10Mi
    Liveness:		http-get http://:8080/healthz-dnsmasq delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xv2t6 (ro)
  dnsmasq-metrics:
    Container ID:	docker://4d4df8348d45f84a3831fd205c39b60aa4a07bfa7065c72e4de9caa2277c9039
    Image:		gcr.io/google_containers/dnsmasq-metrics-arm64:1.0
    Image ID:		docker-pullable://gcr.io/google_containers/dnsmasq-metrics-arm64@sha256:fc0e8b676a26ed0056b8c68611b74b9b5f3f00c608e5b11ef1608484ce55dd9a
    Port:		10054/TCP
    Args:
      --v=2
      --logtostderr
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		ContainerCannotRun
      Exit Code:	128
      Started:		Fri, 16 Jun 2017 14:13:00 +0800
      Finished:		Fri, 16 Jun 2017 14:13:00 +0800
    Ready:		False
    Restart Count:	7
    Requests:
      memory:		10Mi
    Liveness:		http-get http://:10054/metrics delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xv2t6 (ro)
  healthz:
    Container ID:	docker://af618e7561483e7738677a3a9c06ae2927a3819ca85c434d61c12f91c754205d
    Image:		gcr.io/google_containers/exechealthz-arm64:1.2
    Image ID:		docker-pullable://gcr.io/google_containers/exechealthz-arm64@sha256:e8300fde6c36b454cc00b5fffc96d6985622db4d8eb42a9f98f24873e9535b5c
    Port:		8080/TCP
    Args:
      --cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
      --url=/healthz-dnsmasq
      --cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1:10053 >/dev/null
      --url=/healthz-kubedns
      --port=8080
      --quiet
    State:		Running
      Started:		Fri, 16 Jun 2017 14:01:49 +0800
    Ready:		True
    Restart Count:	0
    Limits:
      memory:	50Mi
    Requests:
      cpu:		10m
      memory:		50Mi
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xv2t6 (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  default-token-xv2t6:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-xv2t6
    Optional:	false
QoS Class:	Burstable
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath				Type		Reason		Message
  ---------	--------	-----	----			-------------				--------	------		-------
  16m		16m		1	default-scheduler						Normal		Scheduled	Successfully assigned kube-dns-3365905565-m4cpk to 10.193.20.23
  15m		15m		1	kubelet, 10.193.20.23	spec.containers{kubedns}		Normal		Created		Created container with docker id 5f33cfdc73b8; Security:[seccomp=unconfined]
  15m		15m		1	kubelet, 10.193.20.23	spec.containers{kubedns}		Normal		Started		Started container with docker id 5f33cfdc73b8
  15m		15m		1	kubelet, 10.193.20.23	spec.containers{dnsmasq}		Normal		Started		Started container with docker id 34dbfaa5d2cb
  15m		15m		1	kubelet, 10.193.20.23	spec.containers{dnsmasq}		Normal		Created		Created container with docker id 34dbfaa5d2cb; Security:[seccomp=unconfined]
  15m		15m		1	kubelet, 10.193.20.23	spec.containers{healthz}		Normal		Pulled		Container image "gcr.io/google_containers/exechealthz-arm64:1.2" already present on machine
  15m		15m		1	kubelet, 10.193.20.23	spec.containers{dnsmasq-metrics}	Normal		Created		Created container with docker id 0f538ded9eaa; Security:[seccomp=unconfined]
  15m		15m		1	kubelet, 10.193.20.23	spec.containers{dnsmasq-metrics}	Warning		Failed		Failed to start container with docker id 0f538ded9eaa with error: Error response from daemon: {"message":"linux spec user: unable to find group nobody: no matching entries in group file"}
  15m		15m		1	kubelet, 10.193.20.23	spec.containers{healthz}		Normal		Created		Created container with docker id af618e756148; Security:[seccomp=unconfined]
  15m		15m		1	kubelet, 10.193.20.23	spec.containers{healthz}		Normal		Started		Started container with docker id af618e756148
  15m		15m		1	kubelet, 10.193.20.23	spec.containers{dnsmasq-metrics}	Warning		Failed		Failed to start container with docker id ba6bfaa6138e with error: Error response from daemon: {"message":"linux spec user: unable to find group nobody: no matching entries in group file"}
  15m		15m		1	kubelet, 10.193.20.23	spec.containers{dnsmasq-metrics}	Normal		Created		Created container with docker id ba6bfaa6138e; Security:[seccomp=unconfined]
  15m		15m		2	kubelet, 10.193.20.23						Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "dnsmasq-metrics" with CrashLoopBackOff: "Back-off 10s restarting failed container=dnsmasq-metrics pod=kube-dns-3365905565-m4cpk_kube-system(33636ec0-5259-11e7-adb6-6805ca369d7f)"

  15m	15m	1	kubelet, 10.193.20.23	spec.containers{dnsmasq-metrics}	Normal	Created		Created container with docker id 4c685e27cc1c; Security:[seccomp=unconfined]
  15m	15m	1	kubelet, 10.193.20.23	spec.containers{dnsmasq-metrics}	Warning	Failed		Failed to start container with docker id 4c685e27cc1c with error: Error response from daemon: {"message":"linux spec user: unable to find group nobody: no matching entries in group file"}
  14m	14m	1	kubelet, 10.193.20.23						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "dnsmasq-metrics" with CrashLoopBackOff: "Back-off 20s restarting failed container=dnsmasq-metrics pod=kube-dns-3365905565-m4cpk_kube-system(33636ec0-5259-11e7-adb6-6805ca369d7f)"

  14m	14m	1	kubelet, 10.193.20.23	spec.containers{dnsmasq-metrics}	Normal	Created		Created container with docker id 54962cb1f8b1; Security:[seccomp=unconfined]
  14m	14m	1	kubelet, 10.193.20.23	spec.containers{dnsmasq-metrics}	Warning	Failed		Failed to start container with docker id 54962cb1f8b1 with error: Error response from daemon: {"message":"linux spec user: unable to find group nobody: no matching entries in group file"}
  14m	14m	3	kubelet, 10.193.20.23						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "dnsmasq-metrics" with CrashLoopBackOff: "Back-off 40s restarting failed container=dnsmasq-metrics pod=kube-dns-3365905565-m4cpk_kube-system(33636ec0-5259-11e7-adb6-6805ca369d7f)"

#  3. kubectl describe pods kubernetes-dashboard-1416335539-dcf40 --namespace=kube-system
Name:		kubernetes-dashboard-1416335539-dcf40
Namespace:	kube-system
Node:		10.193.20.23/10.193.20.23
Start Time:	Fri, 16 Jun 2017 14:01:09 +0800
Labels:		k8s-app=kubernetes-dashboard
		pod-template-hash=1416335539
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"kubernetes-dashboard-1416335539","uid":"31bf6a24-5259-11e7-a...
		scheduler.alpha.kubernetes.io/critical-pod=
		scheduler.alpha.kubernetes.io/tolerations=[{"key":"CriticalAddonsOnly", "operator":"Exists"}]
Status:		Running
IP:		10.1.5.2
Controllers:	ReplicaSet/kubernetes-dashboard-1416335539
Containers:
  kubernetes-dashboard:
    Container ID:	docker://e699e5591f12bd43a07d83dcbe771f61a46e4c3a617dd649c845ae8d9fab4552
    Image:		gcr.io/google_containers/kubernetes-dashboard-arm64:v1.5.0
    Image ID:		docker-pullable://gcr.io/google_containers/kubernetes-dashboard-arm64@sha256:559d58ef0d8e9dbe78f80060401b97d6262462318c0b8e071937a73896ea1d3d
    Port:		9090/TCP
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	1
      Started:		Fri, 16 Jun 2017 14:16:11 +0800
      Finished:		Fri, 16 Jun 2017 14:16:42 +0800
    Ready:		False
    Restart Count:	7
    Limits:
      cpu:	100m
      memory:	50Mi
    Requests:
      cpu:		100m
      memory:		50Mi
    Liveness:		http-get http://:9090/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xv2t6 (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  default-token-xv2t6:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-xv2t6
    Optional:	false
QoS Class:	Guaranteed
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath				Type		Reason		Message
  ---------	--------	-----	----			-------------				--------	------		-------
  18m		18m		1	default-scheduler						Normal		Scheduled	Successfully assigned kubernetes-dashboard-1416335539-dcf40 to 10.193.20.23
  17m		17m		1	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Normal		Created		Created container with docker id 9390496e28cc; Security:[seccomp=unconfined]
  17m		17m		1	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Normal		Started		Started container with docker id 9390496e28cc
  17m		17m		1	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Normal		Created		Created container with docker id 90fc78a46624; Security:[seccomp=unconfined]
  17m		17m		1	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Normal		Started		Started container with docker id 90fc78a46624
  16m		16m		2	kubelet, 10.193.20.23						Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 10s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-1416335539-dcf40_kube-system(31c4c230-5259-11e7-adb6-6805ca369d7f)"

  16m	16m	1	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Normal	Created		Created container with docker id 67cd9d128d30; Security:[seccomp=unconfined]
  16m	16m	1	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Normal	Started		Started container with docker id 67cd9d128d30
  15m	15m	3	kubelet, 10.193.20.23						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 20s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-1416335539-dcf40_kube-system(31c4c230-5259-11e7-adb6-6805ca369d7f)"

  15m	15m	1	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Normal	Created		Created container with docker id 73a446633068; Security:[seccomp=unconfined]
  15m	15m	1	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Normal	Started		Started container with docker id 73a446633068
  17m	14m	3	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Warning	Unhealthy	Liveness probe failed: Get http://10.1.5.2:9090/: dial tcp 10.1.5.2:9090: getsockopt: connection refused
  14m	14m	1	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Normal	Killing		Killing container with docker id 73a446633068: pod "kubernetes-dashboard-1416335539-dcf40_kube-system(31c4c230-5259-11e7-adb6-6805ca369d7f)" container "kubernetes-dashboard" is unhealthy, it will be killed and re-created.
  14m	14m	1	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Normal	Created		Created container with docker id 258b6cb7accb; Security:[seccomp=unconfined]
  14m	14m	1	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Normal	Started		Started container with docker id 258b6cb7accb
  13m	12m	7	kubelet, 10.193.20.23						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-1416335539-dcf40_kube-system(31c4c230-5259-11e7-adb6-6805ca369d7f)"

  12m	12m	1	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Normal	Created		Created container with docker id 965d3cb6f3a7; Security:[seccomp=unconfined]
  12m	12m	1	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Normal	Started		Started container with docker id 965d3cb6f3a7
  11m	9m	13	kubelet, 10.193.20.23						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-1416335539-dcf40_kube-system(31c4c230-5259-11e7-adb6-6805ca369d7f)"

  8m	8m	1	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Normal	Created		Created container with docker id 16a180e49772; Security:[seccomp=unconfined]
  8m	8m	1	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Normal	Started		Started container with docker id 16a180e49772
  17m	3m	8	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Normal	Pulled		Container image "gcr.io/google_containers/kubernetes-dashboard-arm64:v1.5.0" already present on machine
  3m	3m	1	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Normal	Created		Created container with docker id e699e5591f12; Security:[seccomp=unconfined]
  3m	3m	1	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Normal	Started		Started container with docker id e699e5591f12
  8m	2s	37	kubelet, 10.193.20.23						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kubernetes-dashboard pod=kubernetes-dashboard-1416335539-dcf40_kube-system(31c4c230-5259-11e7-adb6-6805ca369d7f)"

  16m	2s	62	kubelet, 10.193.20.23	spec.containers{kubernetes-dashboard}	Warning	BackOff	Back-off restarting failed docker container

# 4. kubectl get all --all-namespaces
NAMESPACE     NAME                                       READY     STATUS             RESTARTS   AGE
kube-system   po/k8s-master-10.193.20.34                 4/4       Running            51         18m
kube-system   po/k8s-proxy-v1-9n9l7                      1/1       Running            0          19m
kube-system   po/kube-addon-manager-10.193.20.34         2/2       Running            4          18m
kube-system   po/kube-dns-3365905565-m4cpk               2/4       CrashLoopBackOff   22         19m
kube-system   po/kubernetes-dashboard-1416335539-dcf40   0/1       CrashLoopBackOff   7          19m

NAMESPACE     NAME                       CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
default       svc/kubernetes             10.0.0.1     <none>        443/TCP         19m
kube-system   svc/kube-dns               10.0.0.10    <none>        53/UDP,53/TCP   19m
kube-system   svc/kubernetes-dashboard   10.0.0.95    <none>        80/TCP          19m

NAMESPACE     NAME                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   deploy/kube-dns               1         1         1            0           19m
kube-system   deploy/kubernetes-dashboard   1         1         1            0           19m

NAMESPACE     NAME                                 DESIRED   CURRENT   READY     AGE
kube-system   rs/kube-dns-3365905565               1         1         0         19m
kube-system   rs/kubernetes-dashboard-1416335539   1         1         0         19m

**Comment by xiangpengzhao** [comment]
Could you please edit markdown format of the issue description? It's not so readable.

The container `kubernetes-dashboard` exit with code 1. What's the log of it?

**Comment by whbo158** [comment]
@xiangpengzhao hi xiangpeng, thanks for attention, I have updated the log above, thanks!

**Comment by xiangpengzhao** [comment]
Notice that your kube-dns exited with code 137, I doubt that it was killed due to OOM. The memory limits is 170Mi. Try to configure it a larger value and see if it can succeed.

**Comment by whbo158** [comment]
@xiangpengzhao I have changed 170Mi to 370Mi, but it yet can't work, the error is also 137.  Should I change some configurations on ARM platform?

**Comment by xiangpengzhao** [comment]
Does your system encounter memory pressure? This also might OOMKill your container.

/remove-sig network
/remove-sig storage
/sig node
/cc @vishh

**Comment by whbo158** [comment]
@xiangpengzhao I have no memory pressure, the memory is 4GB that same to x86.   By taking the same step, it can work on x86.
