### ISSUE TITLE
Add ca-certificates.crt to the control plane images

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#47338]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Kubernetes version** (use `kubectl version`): HEAD

Currently, ca-certificates isn't included in the kube-(apiserver|controller-manager|scheduler) images.
However, ca-certificates are often used in production scenarios (for example on AWS and GCE where the controller-manager/apiserver might contact other servers via HTTPS)

The "solution" to this problem has been to host-mount `/etc/ssl/certs` to the container, but this is sub-optimal.

I propose to include `ca-certificates.crt` in the server images as the default. Most scenarios won't be affected as it's overridden by the hostPath mount. It will help in the scenarios where there isn't such a mount.

While writing this, I can't come up with a scenario where adding ca-certificates will break the deployment.
Instead, it will make installing kubernetes easier (and remove the need for unnecessary host-mounts)

@kubernetes/sig-release-feature-requests @kubernetes/sig-testing-feature-requests  @liggitt @david-mcmahon @thockin @spxtr @ixdy @piosz @DirectXMan12 @deads2k @kubernetes/sig-cluster-lifecycle-feature-requests 

I can make a quick PR for this for inclusion in v1.7 if you like.

**Comment by mikedanese** [comment]
We should not do this. We should use the host ssl certificates like we already do in kubeadm and other deployments. If we need to add paths that's ok. Baking certificates raises some serious security concerns. Why is this urgent? We have never done this before.

**Comment by liggitt** [comment]
I agree we shouldn't take on curating a trusted root cert bundle

**Comment by smarterclayton** [comment]
I will note that pod presets and flex volumes are a good way for an operator to mandate and enforce this, but it is almost always a very core role in security administration infrastructure, rather than something we can dictate.

We eventually want to enable cluster administrators to control this on their own, but not our choice.

**Comment by luxas** [comment]
Ok, wanted to check whether this was a thing we could think of endorsing.
I'm fine with the current state as-is as well if we don't want to take on such a role.

Eventually this will be solved anyway with moving cloud providers out of core I guess...
