### ISSUE TITLE
K8s Presubmit Fixes

### ISSUE THREAD

**Issue by alexandercampbell** [kubernetes/kubernetes#47349]
This is a prioritized list of fixes I want work on for the Kubernetes presubmit process, split into two categories. These issues are so closely connected that it makes sense to keep them in a single issue and consolidate discussion.

### User-Friendly Build & Update Scripts
 - [ ] Build and update scripts run in ~~Docker containers~~ some kind of hermetic environment. They do not rely on the local environment for tooling or services (e.g. etcd).
 - [ ] Build and update scripts can be cleanly interrupted with ^C.
 - [ ] Build and update scripts print only human-friendly information.
 - [ ] Build scripts only build teststale and go-bindata once.
 - [ ] All update scripts complete in <10 seconds.

### Better Developer Presubmit Onboarding

 - [ ] Developer documentation explains how to accurately test individual packages with Bazel. (no stale code)
 - [ ] Developer documentation under the kubernetes/community repo explains our presubmit process.
 - [ ] Documentation generated from the code (largely unused) has been deleted. Developers use godoc when they want to refer to code-based documentation.

Feedback welcome.

FYI @pwittrock

**Comment by cblecker** [comment]
@kubernetes/sig-contributor-experience-misc

**Comment by cblecker** [comment]
also @thockin as he was talking about these scripts on the mailing list

**Comment by cblecker** [comment]
should also link https://github.com/kubernetes/kubernetes/pull/46193 which is to put the staging godep script into a docker container

**Comment by alexandercampbell** [comment]
I have [a branch](https://github.com/kubernetes/kubernetes/compare/master...alexandercampbell:build-and-test-with-docker?diff=unified) with a Docker container that runs `make test`. That's about as far as I got; I ran into issues with `make test-integration` since those tests depend on spinning up Docker containers of their own and I didn't want to nest Docker.

**Comment by apelisse** [comment]
cc @ixdy @spxtr

**Comment by alexandercampbell** [comment]
@cblecker thanks pointing me to that issue! I searched for related issues but I forgot to look for PRs.
Are there any other overlapping issues I've missed?

**Comment by apelisse** [comment]
> I have a branch with a Docker container that runs make test

I wonder if we want to invest in that effort, while we have `make bazel-test`? Maybe that applies to the whole issue overall, are we interested in adding, improving, maintaining additional "scripts" rather than use bazel? Or is this something different?

**Comment by cblecker** [comment]
I think the key for that first point is "They do not rely on the local environment for tooling or services (e.g. etcd).". I personally don't care if it's docker or otherwise.

**Comment by cblecker** [comment]
Link to related `kubernetes-dev` thread: https://groups.google.com/d/msg/kubernetes-dev/5rVmSJqCq-U/tyN8OVRjBgAJ

**Comment by alexandercampbell** [comment]
@cblecker good calls, updated.
@apelisse (discussed irl too) my goal is only to create a useful presubmit. Bazel, Docker, whatever.

**Comment by ixdy** [comment]
A lot of this is #8830 - if we don't check in generated code, most of the update-* scripts probably go away.

I think you might be able to use `build/run.sh` to run `make test` inside the cross-build docker image today. (At least the [build README suggests you can](https://github.com/kubernetes/kubernetes/tree/23cd9d7b05b1ef7ef5073ccc7cbeaf09771c8a43/build#key-scripts).) That's how we've dockerized a few of the update scripts already (e.g. `update-generated-protobuf.sh`, `update-generated-runtime.sh`).

**Comment by alexandercampbell** [comment]
@ixdy thanks for the links; those are very helpful. I will experiment with the `build/build-image` ecosystem.

> if we don't check in generated code, most of the update-* scripts probably go away.

The update scripts will remain as part of the standard build process, no?

My goal is only to establish a useful & discoverable presubmit. Perhaps we could get 80% of the way there with docs, e.g. updating the [local verifications section](https://github.com/kubernetes/community/blob/8dbec90eaa8247cdb228c1809bd04dd40b5c283c/contributors/devel/pull-requests.md#run-local-verifications) of `devel/pull-requests.md`. That will probably be my first step.

**Comment by kargakis** [comment]
Agreed with @ixdy, we should first try to eliminate generated code.

**Comment by BenTheElder** [comment]
FWIW all of the presubmits run in docker containers in the CI presubmits (kubernetes pods actually) so the first point is definitely workable..
