### ISSUE TITLE
Connection hangs if accessing service while pod is not ready

### ISSUE THREAD

**Issue by juanjoDiaz** [kubernetes/kubernetes#47340]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
kubernetes, service, readiness, pods, hold, hang, connection, etc.
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`): 1.6

**Environment**:
- **Cloud provider or hardware configuration**: Minikube
- **OS** (e.g. from /etc/os-release): MacOs
- **Kernel** (e.g. `uname -a`):
- **Install tools**: Minikube
- **Others**:

**What happened**:
If trying to connect to the service before its pods are ready (according to its readiness probe), the connection hangs forever, even once the pod move to a ready state. If I retry to connect after the pod is ready it works just fine. 

**What you expected to happen**:
If the pod is not ready, the service should either fail (since there is no pods to take the request) or hold the connection until there is a pod and then return the response. But not just hold forever.

**How to reproduce it** (as minimally and precisely as possible):
Set up a nodePort service that targets one pod running a NGINX hello world container and configure a readiness probe with an `initialDelaySeconds ` of 30 seconds.
Try to connect to the service before the 30 seconds.
The connection is hold forever, even once the 30 seconds pass and the pod moves to a ready state.
Retry to connect after the pod is ready and it will works just fine. 

**Anything else we need to know**:

**Comment by ls-yann-david** [comment]
I do run into the same issue, I see that there's an iptables rule that should reject traffic when no pods are availables, but it never get applied/used.

**Comment by thockin** [comment]
Dup of #48719
