### ISSUE TITLE
Leaderelection for the controller manager is broken when using RBAC and --use-service-account-credentials

### ISSUE THREAD

**Issue by hanikesn** [kubernetes/kubernetes#47354]
**Kubernetes version** (use `kubectl version`): 1.6.2

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release):  Debian GNU/Linux 8 (jessie)
- **Kernel** (e.g. `uname -a`): 3.16.0-4-amd64
- **Install tools**: Custom

**What happened**:
After migrating from ABAC to RBAC the kube-controller-manager failed to elect a leader:
Using the `system:kube-controller-manager` user and `--leader-elect=true` as well as `--use-service-account-credentials`

```kube-controller-manager[32600]: E0612 16:32:46.542305   32600 leaderelection.go:229] error retrieving resource lock kube-system/kube-controller-manager: User "system:kube-controller-manager" cannot get endpoints in the namespace "kube-system".: "No policy matched." (get endpoints kube-controller-manager)```

**Comment by ericchiang** [comment]
/cc @kubernetes/sig-auth-bugs 

The RBAC bootstrap roles and bindings should enable this.[1] Did you have existing RBAC roles and bindings before switching to RBAC? I think the API server will only apply these if no cluster roles exist.

[1] https://github.com/kubernetes/kubernetes/blob/v1.6.2/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml#L458-L465

**Comment by liggitt** [comment]
Is this error only during the initial API server startup, or does it persist in a steady state? As the API server is started for the first time, it will provision the boostrap roles and bindings. If the controller manager attempts to fetch an endpoint while that process is happening, it will be denied. Once the API server completes initialization, it would be allowed.

> Did you have existing RBAC roles and bindings before switching to RBAC? I think the API server will only apply these if no cluster roles exist.

No, they are added/updated even if existing roles/bindings exist.

**Comment by hanikesn** [comment]
RBAC roles have been provisioned for a while before. But it seems like this was related to the restarting order of apiserver, controller-manager and changing user assignment via tokens. So it's a false alarm. Sorry for the noise.
