### ISSUE TITLE
Move kubernetes code generating docs etc to a new repo

### ISSUE THREAD

**Issue by spzala** [kubernetes/kubernetes#47361]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
docs, generated docs, generated
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
1.7 dev cycle

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
The docs has been moved to kubernetes.github.io for around a year now. The Kubernetes docs directory still exist, ideally we should have all the docs under kubernetes.github.io. As part of recent discussion and work, static content of docs directory has been removed but we couldn't remove generated docs. The following PRs are related to the related work and discussion,
https://github.com/kubernetes/kubernetes/pull/46348
https://github.com/kubernetes/kubernetes/pull/46813
kubernetes/kubernetes.github.io#3996

**What you expected to happen**:
Find a good way to remove generated code, and remove them along with docs directory.

**How to reproduce it** (as minimally and precisely as possible):
Refer to the docs and discussion in above mentioned PRs.

**Anything else we need to know**:

**Comment by spzala** [comment]
/cc @thockin @cblecker @ahmetb @chenopis @mikedanese - opened this issue for the work on removing generated doc. I had a discussion with @duglin and we thought that may a good idea is to move code which generates docs to a new repo. I believe we can then use this repo in the kubernetes.github.io  to and keep generated code there. @duglin also mentioned about discussion on generated code other than docs that also needs to be handled. We propose a new 'github repo' for the existing code responsible for generating code/docs. If that sounds like a reasonable approach, I have bandwidth and willingness to work on it. Thanks!!

**Comment by ahmetb** [comment]
@spzala Feel free to swing by SIG-Docs meeting tomorrow (2017-06-13 10:30am PST) to discuss an execution plan.

**Comment by spzala** [comment]
@ahmetb cool, thanks!!

**Comment by kargakis** [comment]
Dupe of https://github.com/kubernetes/kubernetes/issues/26205?

**Comment by spzala** [comment]
@kargakis good point, I think somewhat but the proposed solution here can apply to both. This issue is created based on recent discussion and some changes that are merged. Adding @lavalamp for discussion.

**Comment by duglin** [comment]
To be clear, the placement of the code that generates the code/docs can live anywhere (either in its current spot or in a new repo - which ever makes the most sense), but the main idea behind the separate repo was to host the "generated code" itself outside of the current repo.  For example, let's say the code/docs generation stuff continues live in, say, k8s/k8s but we don't check-in the generated stuff into k8s/k8s.  Instead, as things get merged into "master" a jenkins job could get kicked off which will run the code/docs generations stuff and check **that** into a new repo.  This allows for the output to be hosted outside of the originating repo (so we avoid all of the issues with checking in code) but its still available (in a timely fashion) for use by whoever needs it.

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc folks need to weigh in. How do you guys feel about cross-repo testing at this point?

**Comment by spzala** [comment]
I have changed the issue title a bit to make its scope broader as I described in PR and as @duglin mentioned.

**Comment by jaredbhatti** [comment]
@pwittrock  @chenopis 

If Phillip (original writer of the doc generation scripts) and Andrew Chen (docs lead for 1.7) are ok with this, then I say go for it :)

**Comment by spzala** [comment]
@chenopis @pwittrock hello, just a gentle reminder on what are your thoughts for the next step :-) Are we good at removing docs directory (and all it's references, and that we don't need to generate the docs any more) per discussion above? If so, I can work on making those changes. Thanks!

**Comment by chenopis** [comment]
@spzala Currently, the autogenerated docs for kubectl and kubeadm are first generated in the kubernetes/kubernetes repo, then imported into kubernetes/kubernetes.github.io. So, we do still need the autogeneration process. But can that be moved to the kubectl and kubeadm repos or directly in kubernetes/kubernetes.github.io?

**Comment by spzala** [comment]
@chenopis Thanks Andrew!! OK, let me dig more and understand about the doc code that possibly needs to be moved, and get back with more on it. One of the ideas was to move this code into its own repo (a new repo for doc and other code that are responsible for generating content along with the generated content). Also, as I was thinking about moving code to a different, just thought if https://github.com/kubernetes/gengo is a right place? Thanks!

**Comment by spzala** [comment]
@chenopis Hi, I have opened this PR to remove some of the docs content that I thought should be deleted as they are only pointing to Community repo https://github.com/kubernetes/kubernetes/pull/48119 Can you please take a look? The remaining docs is what I believe we need to keep and think about moving as we are discussing. Thanks!!

**Comment by spzala** [comment]
Hi guys, @cblecker @chenopis a gentle reminder on on-going discussion of having a separate repo.. any thoughts? There is a related discussion going on in service-catalog project https://github.com/kubernetes-incubator/service-catalog/issues/453 that such a separation would be helpful. Thanks!

**Comment by cblecker** [comment]
I'd be okay with separating it out, but it depends on if it's worth the level of effort. much of the docs and man pages are built directly based off the code in k/k, and at least if they're all in the same repo we can easily run CI on them. It's tougher to run cross repo CI to ensure things are updated, but not impossible. This may also naturally go away as we split things up.

I'd talk to sig-cli for kubectl and sig-cluster-lifecycle for kubeadm and ensure their longer term vision for where the actual code will live aligns with what you're trying to do.

**Comment by spzala** [comment]
@cblecker thanks much!! You mentioned about splitting things up, is there a splitting plan already out somewhere that can be reviewed or it's more like in verbal discussion? Thanks!

**Comment by cblecker** [comment]
There's been a number of mentions of it in the community meeting and on the dev lists. For example, this was a recent thread on it from sig-cli: https://groups.google.com/d/msg/kubernetes-dev/DyvuR2SzREU/q16gul3oAwAJ

**Comment by spzala** [comment]
@cblecker thanks!!

**Comment by chenopis** [comment]
FYI, we now have a more general purpose import script [`/update-import-docs/update-imported-docs.go`](https://github.com/kubernetes/website/tree/master/update-imported-docs) now, so `kubectl` or `kubeadm` can be moved to any kubernetes repo and we can still import them.
