### ISSUE TITLE
event spam causes excessive apiserver traffic and frequent snapshots

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#47366]
**Is this a BUG REPORT or FEATURE REQUEST?**
BUG

**Kubernetes version** (use `kubectl version`):
kubernetes/master

**Environment**:
n/a

**What happened**:
events were co-located in api server etcd

the controller-manager and node are spamming the node for different reasons and driving an excessive amount of traffic to our api-server.  this caused etcd snapshots to occur every 13s even with a 20k snapshot interval set.

the controller-manager can produce this problem in a simple manner by defining quota to 1 pod, and creating a replica-set whose target is 1000.  the replica set is burst in steps of 500 and each failed create is sent as a unique event.  in a short period of time, you get ~1300 PATCH event requests.  over enough replica-sets, this adds up.

the node is also prone to spam the server in the event of SyncFailed events.  for example, we had a pod that was in crash loop backoff for 3ds, and we got 21k FailedSync events.  over enough pods, this adds up.

**What you expected to happen**:
The event recorder should protect against spam like this.
The replication controller should attempt burst in stages (1, 2, 3, 5, ...).

**How to reproduce it** (as minimally and precisely as possible):

```
$ curl metric | grep apiserver_request_latencies_summary_count | grep events
apiserver_request_latencies_summary_count{resource="events",subresource="",verb="PATCH"} 11
apiserver_request_latencies_summary_count{resource="events",subresource="",verb="POST"} 33
$ kubectl create quota quota --hard=pods=1
$ kubectl run nginx --image=nginx --replicas=100
... wait a minute ...
$ curl metric | grep apiserver_request_latencies_summary_count | grep events
apiserver_request_latencies_summary_count{resource="events",subresource="",verb="PATCH"} 1300
```

I have a patch prepared that adds client side spam protection in the event recorder.

```
apiserver_request_latencies_summary_count{resource="events",subresource="",verb="PATCH"} 20
```

**Anything else we need to know**:
nope.

**Comment by lavalamp** [comment]
This is not a regression, though, right?

**Comment by derekwaynecarr** [comment]
@lavalamp -- i think it was made worse when we added new container events and moved to the CRI. i have a couple prs open to try and mitigate the problem.

**Comment by derekwaynecarr** [comment]
@lavalamp this is a production problem for us right now on larger clusters, so i would like both to make 1.7:

https://github.com/kubernetes/kubernetes/issues/47367
https://github.com/kubernetes/kubernetes/issues/47462

i am not sure how many people were running 300+ node clusters with larger sets of unhealthy pods to know if it is or is not a regression.  for us its a critical problem.

**Comment by derekwaynecarr** [comment]
i am moving this to sig-node as its a kubelet problem primarily.

moving this to sig-node, and labeling 1.7

**Comment by dchen1107** [comment]
Please see my comments at: https://github.com/kubernetes/kubernetes/pull/47367#issuecomment-308576236

**Comment by marun** [comment]
If this should be blocking 1.7, please label with 'approved-for-milestone'.  If not, move to 1.8.

**Comment by marun** [comment]
Given that the resolving pr was moved to 1.8, I'm updating the issue to match.
