### ISSUE TITLE
Make cluster level logs easier to access using a cluster log browser pod

### ISSUE THREAD

**Issue by satnam6502** [kubernetes/kubernetes#4736]
It might be very useful to have a pod that presents a web-based interface for browsing the logs of current and recent pods. This would work by fetching the logs from Elasticsearch (or Cloud Logging) and cross referencing them with information in the masdter, etcd, events etc. This could be very valuable for debugging run once pods, end to end tests as well as for general log access.

If we decide this is a P1 priority I would be keen to start working on this ASAP.
@derekwaynecarr @smarterclayton @brendandburns

**Comment by rjnagal** [comment]
@satnam6502 Marked it as P2 till we decide about making it a P1.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is desirable.
