### ISSUE TITLE
Failing test: [k8s.io] [Feature:GPU] run Nvidia GPU tests on Container Optimized OS only

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#47363]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-gpu-1-7/23

@vishh could you take a look?

**Comment by caesarxuchao** [comment]
@vishh could you apply the sig label?

**Comment by caesarxuchao** [comment]
Applying the 1.7 milestone because gpu tests are part of 1.7 blocking tests: https://k8s-testgrid.appspot.com/release-1.7-blocking#gce-gpu-1-7

**Comment by vishh** [comment]
@mindprince is looking into it. This is a dup of https://github.com/kubernetes/kubernetes/issues/47216
