### ISSUE TITLE
We should invert hack/.linted_packages

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#47370]
In researching #15863, I stumbled upon this behavior of `verify-golint`. Here's how it works, please correct me if I'm wrong:

* If I open a PR with a new package that passes golint, `verify-golint` will fail because I need to add it to `hack/.linted_packages`.
* If I open a PR with a new package that fails golint, `verify-golint` does not complain.

There are over 700 packages in the repo that silently fail golint. I propose we invert the whole scheme, so that we instead have a file that contains packages that fail golint. Then...

* If I open a PR with a new package that passes golint, `verify-golint` will pass.
* If I open a PR with a new package that fails golint or breaks a previously-passing package, `verify-golint` will fail until I add that package to the list. This explicitly signals to the reviewer that I'm doing something potentially bad.

In the long run we should look into having a bot automatically comment with fmt/lint/vet failures, but for now this should be an improvement.

cc @jessfraz @krousey @kubernetes/sig-contributor-experience-proposals

**Comment by cblecker** [comment]
I'm on the fence about this. I totally see your point of view, and agree with it mostly. The one part that gives me pause is (from https://github.com/golang/lint#purpose):
> The suggestions made by golint are exactly that: suggestions. Golint is not perfect, and has both false positives and false negatives. Do not treat its output as a gold standard. We will not be adding pragmas or other knobs to suppress specific warnings, so do not expect or require code to be completely "lint-free". In short, this tool is not, and will never be, trustworthy enough for its suggestions to be enforced automatically, for example as part of a build process.

It would perhaps be a negative experience to have a weird golint suggestion that you're not expecting on new code.. and a new bar of either making code conform or adding it to the linted exemptions file by default. Granted, that is perhaps desirable.. it's just something we should give some thought.

**Comment by spxtr** [comment]
I agree, and that's why I would rather have the bot make lint comments but allow merging over it.

I just think that the current behavior is worse than nothing, since it silently allows bad code through but actively annoys people trying to add in passing code.

**Comment by krousey** [comment]
golint is meant to serve as a warning that something might not be style
compliant. I think it's perfectly valid to say that if you disagree with
what it says about your code, you should acknowledge that by opting out.

I agree that the best option is to explicitly surface them as comments
during the review and not block the build, but this is a better option
until we get that.
