### ISSUE TITLE
Test Failure: Proxy version v1 should proxy through a service and a pod [Conformance]

### ISSUE THREAD

**Issue by monopole** [kubernetes/kubernetes#47374]
[jenkins log](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-6-cvm-1-7-upgrade-cluster/7#k8sio-proxy-version-v1-should-proxy-through-a-service-and-a-pod-conformance)

[testgrid history](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-upgrade-cluster&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Proxy%5C%20version%5C%20v1%5C%20should%5C%20proxy%5C%20through%5C%20a%5C%20service%5C%20and%5C%20a%5C%20pod%5C%20%5C%5BConformance%5C%5D)

Many errors like
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/proxy.go:274
0 (0; 50.670625ms): path /api/v1/namespaces/e2e-tests-proxy-khc04/services/https:proxy-service-2z7k4:tlsportname2/proxy/ gave status error: {TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink: ResourceVersion:} Status:Failure Message:an error on the server ("Error: 'tls: failed to parse certificate from server: x509: RSA key missing NULL parameters'\nTrying to reach: 'https://10.52.0.167:462/'") has prevented the request from succeeding Reason:InternalError Details:&StatusDetails{Name:,Group:,Kind:,Causes:[{UnexpectedServerResponse Error: 'tls: failed to parse certificate from server: x509: RSA key missing NULL parameters'

/sig network

**Comment by monopole** [comment]
/assign @bowei 

This test has been failing since creation.  Deprecated behavior?

**Comment by liggitt** [comment]
Isn't that the issue with keys generated with a previous version of go?

**Comment by monopole** [comment]
/assign @liggitt 

Can you find out and close the issue please?  We have dozens of blocking failures like this, and i'm working through a triage of new ones.

**Comment by liggitt** [comment]
This is an issue with go1.8 (which k8s 1.7 is built with) trying to verify test certs from a previous version of go.

see https://github.com/kubernetes/kubernetes/issues/38228#issuecomment-280213655

fixed in
https://github.com/kubernetes/kubernetes/pull/44638
https://github.com/kubernetes/kubernetes/pull/44679

what environment is this test in, and is it running an old version of the porter image?

cc @ixdy

**Comment by ixdy** [comment]
ah, I bet we need to cherrypick #44679 to k8s 1.5 and 1.6.

**Comment by ixdy** [comment]
(some variants of the upgrade test suites use tests from the old version, i.e. 1.5 or 1.6.)

**Comment by bowei** [comment]
Did the cert fix this problem? This is not a sig-network related problem.

**Comment by liggitt** [comment]
looks like the last test run was green

**Comment by liggitt** [comment]
went green in build 32 on commit 2c5b5714e on 6/20

**Comment by monopole** [comment]
/reopen

Thanks so much for your effort here - it did go green in [gke-cvm-upgrade-cluster](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-upgrade-cluster&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Proxy%5C%20version%5C%20v1%5C%20should%5C%20proxy%5C%20through%5C%20a%5C%20service%5C%20and%5C%20a%5C%20pod%5C%20%5C%5BConformance%5C%5D) but it's still red in [gke-gci-1-5-cvm-1-7-upgrade-cluster](https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-gci-1-5-cvm-1-7-upgrade-cluster&sort-by-failures=)

And sadly a bunch of other _Proxy version v1_ tests, e.g. [Proxy version v1 should proxy logs on node [Conformance]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1-5-cvm-1-7-upgrade-cluster/20#k8sio-proxy-version-v1-should-proxy-logs-on-node-conformance) have gone red.  This latter is probably a distinct issue, as a ton of others have gone red too.  

But [gke-gci-1-5-cvm-1-7-upgrade-cluster](https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-gci-1-5-cvm-1-7-upgrade-cluster&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Proxy%5C%20version%5C%20v1%5C%20should%5C%20proxy%5C%20through%5C%20a%5C%20service%5C%20and%5C%20a%5C%20pod%5C%20%5C%5BConformance%5C%5D) has been red since June 16

**Comment by monopole** [comment]
OK, let's ignore the 1.5 -> 1.7 failures.
