### ISSUE TITLE
Test Failure: Basic StatefulSet functionality [StatefulSetBasic] Scaling down before scale up is finished should wait

### ISSUE THREAD

**Issue by monopole** [kubernetes/kubernetes#47376]
Test: Basic StatefulSet functionality [StatefulSetBasic] Scaling down before scale up is finished should wait until current pod will be running and ready before it will be removed

[jenkins log](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-6-cvm-1-7-upgrade-cluster/7#k8sio-statefulset-k8sio-basic-statefulset-functionality-statefulsetbasic-scaling-down-before-scale-up-is-finished-should-wait-until-current-pod-will-be-running-and-ready-before-it-will-be-removed)  (search for test string)

[history](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-6-cvm-1-7-upgrade-cluster/)

/sig scalability
/assign @lavalamp

**Comment by kow3ns** [comment]
@monopole The semantics of the API changed between 1.6 and 1.7. The 1.6 tests will break against a 1.7 drop due to StatefulSetStatus being updated to conform to DaemonSetStatus and DeploymentStatus. The 1.7 version of e2e seems stable against a 1.7 cluster and the 1.6 e2e should work against a 1.6 cluster.

**Comment by monopole** [comment]
@kow3ns This failure is part of ci-kubernetes-e2e-gke-cvm-1-6-cvm-1-7-upgrade-cluster, meant to ensure that things continue to work properly during an upgrade when a skew is unavoidable.   My understanding is that stuff should work with a delta of one in the minor version number.  

So is this test a good test that is failing (and hence blocks the 1.7 release), or a bad test that should not exist?

**Comment by kow3ns** [comment]
@monopole same as https://github.com/kubernetes/kubernetes/issues/47378#issuecomment-308225074

**Comment by crimsonfaith91** [comment]
The test was removed in statefulset update PR: https://github.com/kubernetes/kubernetes/pull/46669/files#diff-d6cf821393f7e9ea6770d35ab5749d4dL286

Not sure whether we should skip it when testing against v1.7 cluster.

**Comment by monopole** [comment]
Still have failures.  E.g. this in [gke-gci-16-17-upgrade-master](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1-6-gci-1-7-upgrade-master/35#k8sio-statefulset-k8sio-basic-statefulset-functionality-statefulsetbasic-scaling-down-before-scale-up-is-finished-should-wait-until-current-pod-will-be-running-and-ready-before-it-will-be-removed)

We need a fix or disable here as in #47378, thanks!

**Comment by crimsonfaith91** [comment]
@monopole I will sync with kow3ns offline to determine whether a fix or a skip works best here.

**Comment by dchen1107** [comment]
@kow3ns you comment at https://github.com/kubernetes/kubernetes/issues/47376#issuecomment-308167729
sounds like a backward compatibility issue. Is there any concern? Should we document this in release-notes?

**Comment by crimsonfaith91** [comment]
as discussed in the burndown meeting, we will document the change in release-notes.

**Comment by crimsonfaith91** [comment]
As discussed offline with @Kow3ns, the test will be removed.

**Comment by dchen1107** [comment]
The pr was merged and cherrypick pr is also merged. Close the issue.
