### ISSUE TITLE
test failure: cluster 1.6->1.7 upgrade should maintain a functioning cluster [Feature:ClusterUpgrade]

### ISSUE THREAD

**Issue by monopole** [kubernetes/kubernetes#47379]
cluster upgrade should maintain a functioning cluster [Feature:ClusterUpgrade]

connection refused in version check

[job failure](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-6-cvm-1-7-upgrade-cluster/7#k8sio-upgrade-featureupgrade-k8sio-cluster-upgrade-should-maintain-a-functioning-cluster-featureclusterupgrade)

[history](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-upgrade-cluster&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Upgrade%5C%20%5C%5BFeature%5C%3AUpgrade%5C%5D%5C%20%5C%5Bk8s%5C.io%5C%5D%5C%20cluster%5C%20upgrade%5C%20should%5C%20maintain%5C%20a%5C%20functioning%5C%20cluster%5C%20%5C%5BFeature%5C%3AClusterUpgrade%5C%5D)

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:122
Expected error:
    <*errors.errorString | 0xc4201ca640>: {
        s: "CheckMasterVersion() couldn't get the master version: Get https://35.188.215.192/version: dial tcp 35.188.215.192:443: getsockopt: connection refused",
    }
    CheckMasterVersion() couldn't get the master version: Get https://35.188.215.192/version: dial tcp 35.188.215.192:443: getsockopt: connection refused
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:108
```

/sig networking
/assign @bowei 

See also #44563

**Comment by dchen1107** [comment]
I took a quickly look at the failures, the root cause is actually the master node is not ready. The following error msg indicates why master is not ready:
```
I0615 16:11:10.154] Jun 15 16:11:10.154: INFO: Condition Ready of node bootstrap-e2e-master is false instead of true. Reason: KubeletNotReady, message: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR
I0615 16:11:12.154] Jun 15 16:11:12.154: INFO: Condition Ready of node bootstrap-e2e-master is false instead of true. Reason: KubeletNotReady, message: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR
I0615 16:11:14.152] Jun 15 16:11:14.151: INFO: Condition Ready of node bootstrap-e2e-master is false instead of true. Reason: KubeletNotReady, message: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR
I0615 16:11:14.158] Jun 15 16:11:14.158: INFO: Condition Ready of node bootstrap-e2e-master is false instead of true. Reason: KubeletNotReady, message: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR
I0615 16:11:14.160] Jun 15 16:11:14.158: INFO: All nodes should be ready after test, Not ready nodes: ", bootstrap-e2e-master"
```

It is indeed a network related issue.

**Comment by dchen1107** [comment]
@bowei I am re-assigning this back to you, please delegate. Thanks!

cc/ @kubernetes/kubernetes-release-managers @monopole @kubernetes/sig-network-misc

**Comment by bowei** [comment]
@dnardo @freehan this looks like a CNI related, can you guys take a look?

**Comment by dnardo** [comment]
One thing I see happening at least in the GCE tests (Because it has the master log, but the GKE tests do not)

I0614 04:25:10.354526       5 range_allocator.go:98] Node bootstrap-e2e-minion-group-2cz0 has CIDR 10.180.1.0/24, occupying it in CIDR map
E0614 04:25:10.354547       5 controllermanager.go:429] Error starting "node"
F0614 04:25:10.354554       5 controllermanager.go:178] error starting controllers: failed to mark cidr as occupied: cidr 10.180.1.0/24 is out the range of cluster cidr 10.100.0.0/14

I see that the test has:
cluster/gce/config-test.sh:CLUSTER_IP_RANGE="${CLUSTER_IP_RANGE:-10.100.0.0/14}"

And this for the the pod cidr:
test/e2e_node/conformance/run_test.sh:pod_cidr=10.180.0.0/24
test/e2e_node/services/kubelet.go:              "--pod-cidr", "10.180.0.0/24", // Assign a fixed CIDR to the node because there is no node controller.

Is the above 10.100.0.0/14 supposed to be 10.180/14 ?  10.100/14 is only going to give 10.100 to 10.103 which isn't within the cluster cidr range.

**Comment by dnardo** [comment]
I think I have an idea what happened here.  It looks like this PR changed the cluster CIDR from 10.180/14 to 10.100/14
https://github.com/kubernetes/kubernetes/commit/0e6af317a8567271231487b2e3463236b5c9b6dd

However I see the the e2e node test assumes the pod cider is 10.180.0/24
Here:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/services/kubelet.go#L140

And Here:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/conformance/run_test.sh#L153

Since I believe we need to keep the 10.100/14 probably the right thing to do now is to fix the e2e node test to pick a pod cidr within 10.100/14

**Comment by monopole** [comment]
This was green on 6-15, if green again today i'll close this.

Thanks for your attention @dnardo !

**Comment by dchen1107** [comment]
#47631 should be the one fixing the issue. I will leave this open, until all UpgradeTest on GCE 1.6->1.7 are green. Thanks!

**Comment by dchen1107** [comment]
Ok, I thought we still have the issue on this, and assign this to myself. It turns out the test is still running with the old build for the upgrade test. Will continue monitoring this. cc/ @monopole

**Comment by roberthbailey** [comment]
@krousey fyi

**Comment by dchen1107** [comment]
After #47631 was merged, the master is up and ready, but the upgrade is still marked as failed. I looked into it this morning, and found controller_manager was running into the crashloop after master was upgraded due to the following error:

```
I0619 15:35:05.078773       5 range_allocator.go:70] Sending events to api server.
I0619 15:35:05.078914       5 range_allocator.go:94] Node bootstrap-e2e-master has no CIDR, ignoring
I0619 15:35:05.078931       5 range_allocator.go:98] Node bootstrap-e2e-minion-group-1s08 has CIDR 10.180.0.0/24, occupying it in CIDR map
E0619 15:35:05.078964       5 controllermanager.go:432] Error starting "node"
F0619 15:35:05.078976       5 controllermanager.go:181] error starting controllers: failed to mark cidr as occupied: cidr 10.180.0.0/24 is out the range of cluster cidr 10.100.0.0/14
```

I believe the issue is that we changed validation test in #47631 at https://github.com/kubernetes/kubernetes/pull/47631/files#diff-fb1c11977eba66e7c7c906ab04583f1dL7817 which breaks the backward compatibility with 1.6 nodes. cc/ @bowei @dnardo WDYT?

**Comment by dchen1107** [comment]
Had a quick discussion with network team @kubernetes/sig-network-misc. The quick fix can be putting all nodes' cidr back 10.180.0.0/24, instead of 10.100.0.0/14 to stop the upgrade craziness. @dnardo is working on this, and running the upgrade tests locally. Meanwhile, @dnardo is going to discuss with @bowei on the next steps on how to rollout the feature which depends on the new ip range: 10.100.0.0/14

**Comment by dnardo** [comment]
I think the problem now is that we have one version using 10.180.x. (1.6) and one using 10.100x.x. (1.7)  And when we upgrade happens the cluster was created with 10.180 but then we upgrade we want 10.100.
Can we just set the env var CLUSTER_IP_RANGE  to 10.100 in the test so that the 1.6 cluster comes up with the right range?

**Comment by dnardo** [comment]
In particular I think we could just change this file?
https://github.com/kubernetes/test-infra/blob/master/jobs/ci-kubernetes-e2e-gce-1-6-1-7-upgrade-master.env#L7

To include the CLUSTER_IP_RANGE.

**Comment by dchen1107** [comment]
@dnardo What you suggested should work theoretically. But since both branches hard-coded with two different ip range in some files, instead of respecting CLUSTER_IP_RANGE env variable, it won't work now. 

Since the failure are limited to our tests only, and upgrade test itself relies on the previous branch's latest build, not the real release, we decided to cherry pick @bowei's fix to 1.6 branch. I closed my revert prs.

**Comment by bowei** [comment]
Cherrypicking the required changes to 1.6, 1.5:
* https://github.com/kubernetes/kubernetes/pull/47741
* https://github.com/kubernetes/kubernetes/pull/47742

**Comment by dchen1107** [comment]
@bowei besides cherrypicking #47741, I believe we also need cherrypick https://github.com/kubernetes/kubernetes/pull/47631/files which changes the API validation code.

**Comment by bowei** [comment]
https://github.com/kubernetes/kubernetes/pull/47751

**Comment by monopole** [comment]
Thanks, looking forward to a green run :)

Latest failure (in 1.6 -> 17 upgrade tests) is as in opening comment:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:115
Expected error:
    <*errors.errorString | 0xc42017ee00>: {
        s: "CheckMasterVersion() couldn't get the master version: Get https://104.154.204.209/version: dial tcp 104.154.204.209:443: getsockopt: connection refused",
    }
    CheckMasterVersion() couldn't get the master version: Get https://104.154.204.209/version: dial tcp 104.154.204.209:443: getsockopt: connection refused
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:110
```

**Comment by dchen1107** [comment]
After cherrypicking those ip_range changes to 1.6 branch, now the master node is successfully upgraded to 1.7, and still accepted nodes running 1.6. The kube-controller-manager is not in crashloop anymore. 

The below is the output by running kubectl get nodes on the master node with https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1-6-1-7-upgrade-cluster/54/
```
bootstrap-e2e-master log # kubectl get nodes
NAME                              STATUS                     AGE       VERSION
bootstrap-e2e-master              Ready,SchedulingDisabled   2h        v1.7.0-beta.2.120+c8cd7f318aea33
bootstrap-e2e-minion-group-bmmt   Ready                      2h        v1.6.7-beta.0.6+0e27ae09f693e1
bootstrap-e2e-minion-group-btk1   Ready                      42m       v1.6.7-beta.0.6+0e27ae09f693e1
bootstrap-e2e-minion-group-mjr8   Ready                      2h        v1.6.7-beta.0.6+0e27ae09f693e1
```

**Comment by dchen1107** [comment]
Also all kube-system pods are running successfully after master is upgraded:

```
bootstrap-e2e-master log # kubectl get pods --namespace=kube-system
NAME                                           READY     STATUS    RESTARTS   AGE
etcd-empty-dir-cleanup-bootstrap-e2e-master    1/1       Running   0          3h
etcd-server-bootstrap-e2e-master               1/1       Running   0          3h
etcd-server-events-bootstrap-e2e-master        1/1       Running   0          3h
event-exporter-v0.1.0-2428992396-20c89         2/2       Running   0          20m
fluentd-gcp-v2.0-mvk6s                         2/2       Running   4          2h
fluentd-gcp-v2.0-ssbr4                         2/2       Running   2          1h
fluentd-gcp-v2.0-xwvb6                         2/2       Running   0          16m
fluentd-gcp-v2.0-zdkxq                         2/2       Running   0          3h
heapster-v1.3.0-1514755676-s76gd               4/4       Running   8          3h
kube-addon-manager-bootstrap-e2e-master        1/1       Running   0          3h
kube-apiserver-bootstrap-e2e-master            1/1       Running   2          3h
kube-controller-manager-bootstrap-e2e-master   1/1       Running   3          3h
kube-dns-1759312207-lfd0g                      3/3       Running   3          1h
kube-dns-1759312207-mdvfr                      3/3       Running   0          20m
kube-dns-autoscaler-300991650-jglxn            1/1       Running   0          20m
kube-proxy-bootstrap-e2e-minion-group-564g     1/1       Running   0          16m
kube-proxy-bootstrap-e2e-minion-group-btk1     1/1       Running   1          1h
kube-proxy-bootstrap-e2e-minion-group-mjr8     1/1       Running   2          3h
kube-scheduler-bootstrap-e2e-master            1/1       Running   2          3h
kubernetes-dashboard-1971317102-vg7kw          1/1       Running   1          1h
l7-default-backend-1044750973-ftdx0            1/1       Running   1          1h
l7-lb-controller-v0.9.5-bootstrap-e2e-master   1/1       Running   1          3h
monitoring-influxdb-grafana-v4-2246d           2/2       Running   0          20m
npd-v0.4.0-0g561                               1/1       Running   0          2h
npd-v0.4.0-g7bvr                               1/1       Running   1          1h
npd-v0.4.0-lrshn                               1/1       Running   2          3h
npd-v0.4.0-vrwtz                               1/1       Running   0          16m
rescheduler-v0.3.0-bootstrap-e2e-master        1/1       Running   0          3h
```

**Comment by dchen1107** [comment]
Testing is still running, but I noticed that the cluster upgrade failed in the log at https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1-6-1-7-upgrade-cluster/54/

```
I0620 00:43:28.375]     Expected error:
I0620 00:43:28.375]         <*errors.errorString | 0xc420a06080>: {
I0620 00:43:28.376]             s: "error running /workspace/kubernetes_skew/cluster/gce/upgrade.sh [-M v1.7.0-beta.2.120+c8cd7f318aea33]; got error exit status 1, stdout \"== Pre-Upgrade Node OS and Kubelet Versions ==\\nname: \\\"bootstrap-e2e-master\\\", osImage: \\\"Container-Optimized OS from Google\\\", kubeletVersion: \\\"v1.6.7-beta.0.6+0e27ae09f693e1\\\"\\nname: \\\"bootstrap-e2e-minion-group-0gsp\\\", osImage: \\\"Debian GNU/Linux 7 (wheezy)\\\", kubeletVersion: \\\"v1.6.7-beta.0.6+0e27ae09f693e1\\\"\\nname: \\\"bootstrap-e2e-minion-group-bmmt\\\", osImage: \\\"Debian GNU/Linux 7 (wheezy)\\\", kubeletVersion: \\\"v1.6.7-beta.0.6+0e27ae09f693e1\\\"\\nname: \\\"bootstrap-e2e-minion-group-mjr8\\\", osImage: \\\"Debian GNU/Linux 7 (wheezy)\\\", kubeletVersion: \\\"v1.6.7-beta.0.6+0e27ae09f693e1\\\"\\n== Upgrading master to 'https://storage.googleapis.com/kubernetes-release-dev/ci/v1.7.0-beta.2.120+c8cd7f318aea33/kubernetes-server-linux-amd64.tar.gz'. Do not interrupt, deleting master instance. ==\\n== Upgrading master environment variables. ==\\nNAME                  ZONE           MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP    STATUS\\nbootstrap-e2e-master  us-central1-f  n1-standard-1               10.240.0.2   35.188.148.37  RUNNING\\n== Waiting for new master to respond to API requests ==\\n........................................== Done ==\\n== Validating cluster post-upgrade ==\\nValidating gce cluster, MULTIZONE=\\n\\x1b[0;33mWaiting for 4 ready nodes. 3 ready nodes, 4 registered. Retrying.\\x1b[0m\\n\\x1b[0;33mWaiting for 4 ready nodes. 3 ready nodes, 4 registered. Retrying.\\x1b[0m\\nFound 4 node(s).\\nNAME                              STATUS                     AGE       VERSION\\nbootstrap-e2e-master              Ready,SchedulingDisabled   1m        v1.7.0-beta.2.120+c8cd7f318aea33\\nbootstrap-e2e-minion-group-0gsp   Ready                      14m       v1.6.7-beta.0.6+0e27ae09f693e1\\nbootstrap-e2e-minion-group-bmmt   Ready                      14m       v1.6.7-beta.0.6+0e27ae09f693e1\\nbootstrap-e2e-minion-group-mjr8   Ready                      14m       v1.6.7-beta.0.6+0e27ae09f693e1\\n\\x1b[0;33mCluster not working yet.\\x1b[0m\\nValidate output:\\n\", stderr \"Project: gce-up-c1-3-g1-4-up-clu\\nZone: us-central1-f\\nINSTANCE_GROUPS=bootstrap-e2e-minion-group\\nNODE_NAMES=bootstrap-e2e-minion-group-0gsp bootstrap-e2e-minion-group-bmmt bootstrap-e2e-minion-group-mjr8\\nTrying to find master named 'bootstrap-e2e-master'\\nLooking for address 'bootstrap-e2e-master-ip'\\nUsing master: bootstrap-e2e-master (external IP: 35.188.148.37)\\nDeleted [https://www.googleapis.com/compute/v1/projects/gce-up-c1-3-g1-4-up-clu/zones/us-central1-f/instances/bootstrap-e2e-master].\\nWARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#pdperformance.\\nCreated [https://www.googleapis.com/compute/v1/projects/gce-up-c1-3-g1-4-up-clu/zones/us-central1-f/instances/bootstrap-e2e-master].\\nProject: gce-up-c1-3-g1-4-up-clu\\nZone: us-central1-f\\nThe connection to the server 35.188.148.37 was refused - did you specify the right host or port?\\n(kubectl failed, will retry 2 times)\\nThe connection to the server 35.188.148.37 was refused - did you specify the right host or port?\\n(kubectl failed, will retry 1 times)\\nThe connection to the server 35.188.148.37 was refused - did you specify the right host or port?\\n('kubectl get nodes' failed, giving up)\\nThe connection to the server 35.188.148.37 was refused - did you specify the right host or port?\\n(kubectl failed, will retry 2 times)\\nThe connection to the server 35.188.148.37 was refused - did you specify the right host or port?\\n(kubectl failed, will retry 1 times)\\nThe connection to the server 35.188.148.37 was refused - did you specify the right host or port?\\n('kubectl get nodes' failed, giving up)\\nThe connection to the server 35.188.148.37 was refused - did you specify the right host or port?\\n(kubectl failed, will retry 2 times)\\nThe connection to the server 35.188.148.37 was refused - did you specify the right host or port?\\n(kubectl failed, will retry 1 times)\\nThe connection to the server 35.188.148.37 was refused - did you specify the right host or port?\\n('kubectl get componentstatuses -o template --template={{range .items}}{{with index .conditions 0}}{{.type}}:{{.status}}{{end}}{{\\\"\\\\n\\\"}}{{end}}' failed, giving up)\\nThe connection to the server 35.188.148.37 was refused - did you specify the right host or port?\\n(kubectl failed, will retry 2 times)\\nThe connection to the server 35.188.148.37 was refused - did you specify the right host or port?\\n(kubectl failed, will retry 1 times)\\nThe connection to the server 35.188.148.37 was refused - did you specify the right host or port?\\n('kubectl get cs' failed, giving up)\\n\"",
I0620 00:43:28.376]         }
```

From above comment at https://github.com/kubernetes/kubernetes/issues/47379#issuecomment-309629694, one can see that 
1) now master node are up and ready, vs. notready in pre-54 runs
2) kube-controller-manager is running for 3 hour, not in crashloop in pre-54 runs
kube-controller-manager-bootstrap-e2e-master   1/1       Running   3          3h
3) kubectl cs returns ok without error. There is no 'kubectl get nodes' failure, no kubect get cs failure. Above error / failure is red-herring, and looks like an autograde test infra issue. cc/ @krousey

**Comment by krousey** [comment]
It looks like `kubectl get cs` failed from the e2e test. I don't doubt that it worked from the master, but that's not where the e2e is running. I suspect an auth issue. When the suite finishes, we can confirm by looking at the api server log for component status access from the kubectl user agent.

**Comment by dchen1107** [comment]
I checked kube-apiserver.log, there is no failure from the kubectl user agent, especially right before test claimed UpgradeMaster is failed, /componentstatus from kubectl is ok:

I0620 00:23:45.112117       5 wrap.go:42] GET /api/v1/componentstatuses: (757.782364ms) 200 [[kubectl/v1.7.0 (linux/amd64) kubernetes/c8cd7f3] 35.188.93.146:47332]

In test log: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1-6-1-7-upgrade-cluster/54/, before previous /componentstatuses call, master is upgraded successfully, and all work-nodes are ready:

```
I0620 00:23:42.613] Found 4 node(s).
I0620 00:23:43.957] NAME                              STATUS                     AGE       VERSION
I0620 00:23:43.957] bootstrap-e2e-master              Ready,SchedulingDisabled   1m        v1.7.0-beta.2.120+c8cd7f318aea33
I0620 00:23:43.958] bootstrap-e2e-minion-group-0gsp   Ready                      14m       v1.6.7-beta.0.6+0e27ae09f693e1
I0620 00:23:43.958] bootstrap-e2e-minion-group-bmmt   Ready                      14m       v1.6.7-beta.0.6+0e27ae09f693e1
I0620 00:23:43.958] bootstrap-e2e-minion-group-mjr8   Ready                      14m       v1.6.7-beta.0.6+0e27ae09f693e1
```
But upgrade.sh still complaint cluster is not working:

```
I0620 00:23:45.152] Cluster not working yet.
I0620 00:24:16.101] The connection to the server 35.188.148.37 was refused - did you specify the right host or port?
I0620 00:24:16.105] (kubectl failed, will retry 2 times)
I0620 00:24:17.689] The connection to the server 35.188.148.37 was refused - did you specify the right host or port?
I0620 00:24:17.694] (kubectl failed, will retry 1 times)
I0620 00:24:18.902] The connection to the server 35.188.148.37 was refused - did you specify the right host or port?
I0620 00:24:18.906] ('kubectl get componentstatuses -o template --template={{range .items}}{{with index .conditions 0}}{{.type}}:{{.status}}{{end}}{{"\n"}}{{end}}' failed, giving up)
I0620 00:24:18.911] Validate output:
I0620 00:24:19.501] The connection to the server 35.188.148.37 was refused - did you specify the right host or port?
I0620 00:24:19.504] (kubectl failed, will retry 2 times)
I0620 00:24:20.784] The connection to the server 35.188.148.37 was refused - did you specify the right host or port?
I0620 00:24:20.787] (kubectl failed, will retry 1 times)
I0620 00:24:22.039] The connection to the server 35.188.148.37 was refused - did you specify the right host or port?
I0620 00:24:22.043] ('kubectl get cs' failed, giving up)
```
But there is no retry with kubectl get cs which should be called multiple times in validate-cluster.sh. @caesarxuchao and I checked validate-cluster.sh and think there is a problem in the code. The weirdness is that validation-cluster.sh hasn't been touched for a year. Something underneath triggers this change? @caesarxuchao is sending a quick fix.

**Comment by dchen1107** [comment]
Ok, I have more data to say that upgrade.sh (along with validation_cluster.sh) is really buggy. 
Without any change, the new run of
both master and nodes are successfully upgraded to 1.7 in a new run: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1-6-1-7-upgrade-cluster/55?log#log

```
I0620 10:54:17.484] == Finished upgrading nodes to v1.7.0-beta.2.120+c8cd7f318aea33. ==
I0620 10:54:17.484] == Validating cluster post-upgrade ==
I0620 10:54:17.519] Validating gce cluster, MULTIZONE=
I0620 10:54:17.520] Project: gce-up-c1-3-g1-4-up-clu
I0620 10:54:17.520] Zone: us-central1-f
I0620 10:54:18.571] Found 4 node(s).
I0620 10:54:18.774] NAME                              STATUS                     AGE       VERSION
I0620 10:54:18.774] bootstrap-e2e-master              Ready,SchedulingDisabled   13m       v1.7.0-beta.2.120+c8cd7f318aea33
I0620 10:54:18.774] bootstrap-e2e-minion-group-4jm4   Ready                      8m        v1.7.0-beta.2.120+c8cd7f318aea33
I0620 10:54:18.774] bootstrap-e2e-minion-group-gw1d   Ready                      4m        v1.7.0-beta.2.120+c8cd7f318aea33
I0620 10:54:18.774] bootstrap-e2e-minion-group-km98   Ready                      23s       v1.7.0-beta.2.120+c8cd7f318aea33
I0620 10:54:19.486] Validate output:
I0620 10:54:20.191] NAME                 STATUS    MESSAGE              ERROR
I0620 10:54:20.191] controller-manager   Healthy   ok                   
I0620 10:54:20.191] scheduler            Healthy   ok                   
I0620 10:54:20.191] etcd-0               Healthy   {"health": "true"}   
I0620 10:54:20.191] etcd-1               Healthy   {"health": "true"}   
I0620 10:54:20.195] Cluster validation succeeded
I0620 10:54:20.195] == Post-Upgrade Node OS and Kubelet Versions ==
I0620 10:54:20.395] name: "bootstrap-e2e-master", osImage: "Container-Optimized OS from Google", kubeletVersion: "v1.7.0-beta.2.120+c8cd7f318aea33"
I0620 10:54:20.395] name: "bootstrap-e2e-minion-group-4jm4", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.7.0-beta.2.120+c8cd7f318aea33"
I0620 10:54:20.395] name: "bootstrap-e2e-minion-group-gw1d", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.7.0-beta.2.120+c8cd7f318aea33"
I0620 10:54:20.395] name: "bootstrap-e2e-minion-group-km98", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.7.0-beta.2.120+c8cd7f318aea33"
```

**Comment by monopole** [comment]
This guy is flakey: [gubernator](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-6-cvm-1-7-upgrade-cluster-new/32#k8sio-upgrade-featureupgrade-k8sio-cluster-upgrade-should-maintain-a-functioning-cluster-featureclusterupgrade), [history](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-upgrade-cluster-new&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Upgrade%5C%20%5C%5BFeature%5C%3AUpgrade%5C%5D%5C%20%5C%5Bk8s%5C.io%5C%5D%5C%20cluster%5C%20upgrade%5C%20should%5C%20maintain%5C%20a%5C%20functioning%5C%20cluster%5C%20%5C%5BFeature%5C%3AClusterUpgrade%5C%5D)

Most recent failure about 11pm yesterday, still waiting for another run.
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:115
Expected error:
    <*errors.errorString | 0xc4202923c0>: {
        s: "CheckMasterVersion() couldn't get the master version: Get https://35.192.68.63/version: dial tcp 35.192.68.63:443: getsockopt: connection refused",
    }
    CheckMasterVersion() couldn't get the master version: Get https://35.192.68.63/version: dial tcp 35.192.68.63:443: getsockopt: connection refused
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:110
```

Since the test is still failing, this issue should not have been closed - but the bot did it and don't have the authority to re-open.

@bowei we're skipping some tests because of known API skew failures.  Do you want to mark this test as a skip?

**Comment by bowei** [comment]
Let's mark this as flakey and skip it.

**Comment by dchen1107** [comment]
@bowei we cannot skip this because it is does the real upgrade. If master upgrade failed, the test is red; if the node upgrade failed, the test is red. Sometimes, the script is flaky at the end, the test is red even the entire cluster is upgraded successfully.

But we should skip this from 1.5->1.7 upgrade test suites since we only care about kubectl skews tests. There is no need to upgrade node from 1.5->1.7.

**Comment by monopole** [comment]
So we're going to ignore this in the 15->1.7 tests.

Focus on the __1.6->1.7__ tests.

Seeing new red in these (after some green)

[gce-upgrade-cluster](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gce-upgrade-cluster&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Upgrade%5C%20%5C%5BFeature%5C%3AUpgrade%5C%5D%5C%20%5C%5Bk8s%5C.io%5C%5D%5C%20cluster%5C%20upgrade%5C%20should%5C%20maintain%5C%20a%5C%20functioning%5C%20cluster%5C%20%5C%5BFeature%5C%3AClusterUpgrade%5C%5D)
[gke-cvm-upgrade-cluster-new](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-upgrade-cluster-new&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Upgrade%5C%20%5C%5BFeature%5C%3AUpgrade%5C%5D%5C%20%5C%5Bk8s%5C.io%5C%5D%5C%20cluster%5C%20upgrade%5C%20should%5C%20maintain%5C%20a%5C%20functioning%5C%20cluster%5C%20%5C%5BFeature%5C%3AClusterUpgrade%5C%5D)
[gke-gci-upgrade-cluster-new](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-gci-upgrade-cluster-new&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Upgrade%5C%20%5C%5BFeature%5C%3AUpgrade%5C%5D%5C%20%5C%5Bk8s%5C.io%5C%5D%5C%20cluster%5C%20upgrade%5C%20should%5C%20maintain%5C%20a%5C%20functioning%5C%20cluster%5C%20%5C%5BFeature%5C%3AClusterUpgrade%5C%5D)

These guys remained green:

[gce-upgrade-cluster-new](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gce-upgrade-cluster-new&sort-by-failures=)
[gke-cvm-upgrade-cluster](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-upgrade-cluster&sort-by-failures=)

**Comment by bowei** [comment]
Is this related the aggregation API server ready issue?

**Comment by marun** [comment]
@monopole What's the status of this issue?  Should it continue blocking 1.7?  If not, please remove the 'approved-for-milestone' label.

**Comment by bowei** [comment]
@monopole is on PTO 

@dchen1107

**Comment by dchen1107** [comment]
After we fixed the subnetwork issue, now upgrade are fine:
https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gce-upgrade-master&include-filter-by-regex=-upgrade

There is failure for ingress https://github.com/kubernetes/kubernetes/issues/48239. And the engineer indicates it is caused by the infrastructure underneath.

**Comment by dchen1107** [comment]
I remove this as the release blocker.

**Comment by mbohlool** [comment]
This is failing in gce-1.7-master-upgrade-master: example job: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/214

I will apply release blocker and urgency to this. Please advice if it is not the case.

**Comment by krousey** [comment]
@mbohlool This did occur there, but it doesn't seem to occur often (hasn't happened in that suite since). The major issue with the suite that you linked is the panic you fixed yesterday.
