### ISSUE TITLE
#44784 changes openapi model names

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#47372]
#44784 changes the openapi model names from "io.k8s.kubernetes..." to "io.k8s.api...". We need to investigate if it breaks backward compatibility.

**Comment by mbohlool** [comment]
Yes, it does break backward compatibility. There are two options (Both possible with a post processing function hook available in OpenAPI generator config():

1. Rename models to keep backward compatibility.
2. Keep new names and add a redirect from old names to new names for all model names. If we chose this, we need to keep this for at least one version (and clear message of deprecation).

I favor second one.

**Comment by mml** [comment]
ping @mbohlool

**Comment by mbohlool** [comment]
@caesarxuchao The other PR is rather large, would you give me a little more specific renames that needs to happen here? is it ALL "io.k8s.kubernetes..." to "io.k8s.api..." models?

**Comment by caesarxuchao** [comment]
In 1.7 openapi pod spec, you have pod definition with id "io.k8s.kubernetes.pkg.api.v1.Pod".
In mater, the id is "io.k8s.api.core.v1.pod".
That's because we have moved types:
* from `k8s.io/kubernetes/pkg/apis/<group>/<version>` to `k8s.io/api/<group>/<version>`
* from `k8s.io/kubernetes/pkg/api/v1` to `k8s.io/api/core/v1`

I don't know if we should keep the IDs unchanged.

**Comment by liggitt** [comment]
@kubernetes/api-reviewers are OpenAPI model names considered part of our API compatibility or just the serialized *content* of an API object? Requiring OpenAPI model names to never change means we completely lose the ability to refactor API types, even in ways that preserve serialized content perfectly.

**Comment by mbohlool** [comment]
I don't think we want to require them to not change, generated client libraries use these names as Model's class name so I think we should apply one release cycle deprecation policy to them. I would also like to know @kubernetes/api-reviewers opinion on this and if we don't have a deprecation policy for this, I would like to propose it.

**Comment by liggitt** [comment]
> one release cycle deprecation policy to them

mixing a statically generated client with live use of an openapi schema in such a way that the names of the openapi models become part of the API guarantee seems like an unnecessarily brittle thing to promote

**Comment by mbohlool** [comment]
The statically generated client does not care about model names when it talks to different versions of the cluster. When we do generate a new client for 1.8 for example, model names will change and users of the client that wants to upgrade to the new client, cannot do that until they fix all their class names. Giving them one release cycle to fix their classes but still being able to use the new features of the client is my motivation for the proposal.
