### ISSUE TITLE
Split automated upgrade tests into their own results.

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#47371]
When the upgrade tests were automated, they had to be put in a single Ginkgo test to properly coordinate the steps. We should split out the individual upgrade tests so that we don't have to manually triage to see which test failed.

**Comment by dchen1107** [comment]
Approve this for 1.7 milestone:  According to @monopole, the upgrade test lead for 1.7 release: This feature will improve the way in which upgrade tests appear on the dashboard, making it easier to triage failures. No risk for the release itself.
