### ISSUE TITLE
Add e2e tests for testing GPUs on GKE

### ISSUE THREAD

**Issue by mindprince** [kubernetes/kubernetes#47388]
xref: #44107

/sig node
/area test

**Comment by mindprince** [comment]
I am working on this.

**Comment by cmluciano** [comment]
@mindprince Can you update this with the types of tests that you are adding? Is this similar to https://github.com/kubernetes/kubernetes/issues/46356 ?

**Comment by mindprince** [comment]
No, this is for running the existing GPU e2e tests on GKE which are currently running on only GCE.

**Comment by marun** [comment]
The referenced PRs appear to have merged, closing.
