### ISSUE TITLE
Update images before 1.7 release

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#47386]
A number of addon images have CVEs that have been fixed in the upstream base images.
We should update these images before the final 1.7 release.

cc @timstclair

**Comment by ixdy** [comment]
@kubernetes/sig-release-misc

**Comment by luxas** [comment]
cc @luxas

**Comment by ixdy** [comment]
The new `debian-base-amd64` image appears to have removed `libcap.so.2`. I'm not sure if this was expected, but it caused at least fluentd to stop working on COS (#47600). This might also affect kubeproxy, which uses `debian-iptables-amd64` (a derivative of `debian-base`).

**Comment by ixdy** [comment]
also the metadata-proxy, prometheus-to-sd, the fluentd-event-exporter, and ip-masq-agent.

**Comment by luxas** [comment]
@ixdy anything more to do for this issue?

**Comment by ixdy** [comment]
yes, I need to get https://github.com/kubernetes/contrib/pull/2640 merged and update those images again. I also need to bump a few other images.

**Comment by ixdy** [comment]
#47877 should be the last update needed.
