### ISSUE TITLE
AWS provider: NodeNames are not unique if not filtered by state

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#47404]
In #46463 we stopped filtering nodes by their running state.  But this means that the NodeName is no longer a unique key.  We need to rework the volume status checker to deal with this.

**Comment by gnufied** [comment]
Was discussing this with @wongma7 offline. Why can't we extend the filter to exclude terminated ones? I understand that AWS API doesn't provide a _documented_ way of doing negative filtering, but can we not simply list all the known states we care about? such as - `stopped`, `running`, `stopping` etc.

**Comment by justinsb** [comment]
We can do that too @gnufied  :-)
