### ISSUE TITLE
openapi not aggregating delegated API servers

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#47426]
The `kube-apiserver` is built by creating a delegation chain from one server to another.  This chain of discrete API servers allows for a code level separation of API servers so that each can be developed separately and later assembled. See https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L118 

The openapi isn't being aggregated through the chain.

@kubernetes/sig-api-machinery-misc

**Comment by sttts** [comment]
Neither is swagger aggregated, but only considers the outer go-restful container, instead of the whole chain.

**Comment by sttts** [comment]
Any progress here? 1.8 is approaching.

**Comment by mbohlool** [comment]
Closing this one in favor of #50011. If these are not duplicates, please reopen.
