### ISSUE TITLE
Allow users to specify the user secret namespace in Ceph volume driver

### ISSUE THREAD

**Issue by jamiehannaford** [kubernetes/kubernetes#47427]
The current Ceph driver causes issues when the kubelet mounts volumes in a different namespace from the one where the User secret is stored. By default the User secret is stored in the `default` namespace and the user has no way to override it, forcing them to manually copy it over or face various hard-to-debug errors in the logs. See [here](https://github.com/kubernetes/kubernetes/blob/1e1040b524dda1c97dad4faab1910972b71a5c79/pkg/volume/rbd/rbd.go#L113).

The user should be able to specify which namespace the user secret is stored in, similar to the way they can specify the `adminSecretNamespace`.

**Comment by rootfs** [comment]
The secret is in the same namespace as the pod
see https://github.com/kubernetes/kubernetes/blob/1e1040b524dda1c97dad4faab1910972b71a5c79/pkg/volume/util/util.go#L123

**Comment by gnufied** [comment]
That only applies to PVs created via dynamic provisioning. I think @jamiehannaford was talking about statically created PVs.

**Comment by rootfs** [comment]
> That only applies to PVs created via dynamic provisioning. I think @jamiehannaford was talking about statically created PVs.

`GetSecretForPod()` is called by rbd mounter, it is not a "provisioning thing". All rbd PVs expect secrets exist in the same namespace as the Pods.

**Comment by gnufied** [comment]
> GetSecretForPod() is called by rbd mounter, it is not a "provisioning thing". All rbd PVs expect secrets exist in the same namespace as the Pods.

Sure. But for statically provisioned PVs this can easily become a problem. Because PVs are not namespaced and for statically provisioned PVs they can be bound to any PVC (in any namespace) and then the assumption that secret will be in same namespace as pod falls apart.  I think that is the problem @jamiehannaford is running into. But I will let him clarify.

**Comment by rootfs** [comment]
> Sure. But for statically provisioned PVs this can easily become a problem. Because PVs are not namespaced and for statically provisioned PVs they can be bound to any PVC (in any namespace) and then the assumption that secret will be in same namespace as pod falls apart. I think that is the problem @jamiehannaford is running into. But I will let him clarify.

The secret has to be created in the same namespace as the Pods that use rbd. There is no wide open namespace for rbd secrets.

**Comment by jamiehannaford** [comment]
@rootfs I know the secret must be in the same namespace as the pod, my point is that there's no way to set the namespace in the first place. We're using rook, so the set up is:

1. deploy rook in `foo` namespace (uses ceph)
1. create PVC in `foo` namespace
1. ceph will then dynamically create a PV
1. ceph creates user secret in `default` namespace
1. pod which uses PVC in `foo` namespace doesn't have access to secret

To get around this, we can provide a `userSecretNamespace` which the volume mounter will use to retrieve the secret, instead of assuming it's the same as the pod.

**Comment by rootfs** [comment]
> ceph creates user secret in default namespace

Why ceph creates user secret in default namespace? After step 2, you have a namespace `foo`

**Comment by rootfs** [comment]
based on the [comment](https://github.com/kubernetes/kubernetes/issues/47452#issuecomment-308461782),  the user namespace idea could happen
