### ISSUE TITLE
Add `CriticalAddonsOnly` for daemonset by default

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#47444]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
If I enabled rescheduler, then the rescheduler will add `CriticalAddonsOnly` taint to node when selecting a node for critical pod. 

This will cause some daemonset pods got evicted if those daemonset do not have such tolerations. 

**What you expected to happen**:
Add `CriticalAddonsOnly` to daemonset by default just like what we did for [TaintNodeNotReady and TaintNodeUnreachable](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemoncontroller.go#L1083-L1101)

cc @gmarek 
**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by liggitt** [comment]
are all daemonset pods inherently critical addons?

**Comment by gyliu513** [comment]
I think currently not. We encounter an issue that the daemonset pods sometimes got evicted when enabling rescheduler due to taint based eviction. @liggitt

**Comment by liggitt** [comment]
Tolerating failure condition taints seems different than tolerating taints designed to limit to a particular type of pod. If not all daemonsets are critical addons, then it doesn't seem appropriate to automatically add that toleration to daemonset pods

**Comment by gyliu513** [comment]
In my understanding, I think the daemonset should have high priority than critical pod as daemonset is system services. If the daemonset do not have the `CriticalAddonsOnly` tolerations, then daemonset pod may got evicted if the node which is running daemonset pod got a `CriticalAddonsOnly` taint. As a workaround, I was now adding the `CriticalAddonsOnly` tolerations to my daemonset as a workaround, but as a long term solution, shall we add `CriticalAddonsOnly` tolerations as default for daemonset?

**Comment by k82cn** [comment]
IMO, DaemonSet is not always system services.

**Comment by gyliu513** [comment]
From https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/ , we can see the definition of DaemonSet.

```
What is a DaemonSet?

A DaemonSet ensures that all (or some) nodes run a copy of a pod. As nodes are added to the cluster, pods are added to them. As nodes are removed from the cluster, those pods are garbage collected. Deleting a DaemonSet will clean up the pods it created.
```

The first sentence is `A DaemonSet ensures that all (or some) nodes run a copy of a pod.`. If a demonset do not have `nodeSelector` or other filters, we should make sure it can always running on the nodes.

**Comment by liggitt** [comment]
I don't think that is intended to negate the power of taints/tolerations as the relate to daemonsets, it just likely needs to be updated to explain interactions with taints/tolerations.

**Comment by gyliu513** [comment]
What I want to do is follow [Make DaemonSets survive taint-based evictions when nodes turn unreachable/notReady](https://github.com/kubernetes/kubernetes/pull/41896) to make daemonset can still works even with rescheduler.

What is the concern if adding `CriticalAddonsOnly` for daemonset by default? My thinking is without rescheduler, the daemonset will never get evicted; but with rescheduler, the daemonset can be evicted frequently when there are rescheduling logic is triggered. I think that we should keep the behavior for daemonset same with and without rescheduler: Never get the daemonset pods got evicted.

**Comment by liggitt** [comment]
I don't really want controllers auto-adding tolerations the user did not request, especially when combined with admission plugins like [PodTolerationRestriction](https://github.com/kubernetes/kubernetes/pull/30302#issue-170248549) that prevent users from setting certain tolerations on their pods, in order to keep them off cluster-admin-tainted nodes. CriticalAddonsOnly is exactly the sort of taint I'd expect normal users to be prevented from tolerating

**Comment by foxish** [comment]
> If I enabled rescheduler, then the rescheduler will add CriticalAddonsOnly taint to node when selecting a node for critical pod.

I don't quite understand why the rescheduler tries to move critical addons between nodes in the first place.

**Comment by gyliu513** [comment]
Please check [here](https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/) for how does rescheduler works.

Basically, when a node add taint of `CriticalAddonsOnly`, it will stop other pod scheduled on to this node. If there are some daemonset pod is scheduling at this time, then they cannot start up. @foxish

**Comment by gmarek** [comment]
It's a discussion we need to have in 1.8 timeframe. We're currently in a limbo state, where NoSchedule Taints were designed as a better alternative for 'Unschedulable' bit, but Daemons on one hand ignore 'Unschedulabe', and on the other doesn't tolerate 'NoSchedule' Taints. I generally agree with @liggitt that in principle we shouldn't give Daemons special privileges by default, but on the other hand I see @gyliu513's point that they always had those... Can we agree to discuss it in July?

**Comment by k82cn** [comment]
> Basically, when a node add taint of CriticalAddonsOnly, it will stop other pod scheduled on to this node. If there are some daemonset pod is scheduling at this time, then they cannot start up. 

I think that's the right behavior; if there's not enough resources for DaemonSet pods, they're not created (DaemonSet will check resources on each nodes by Predicates). If the DaemonSet is critical, the user/admin should mark it as "critical" explicitly. But it should not tolerant `CriticalAddonsOnly` by default.

**Comment by gyliu513** [comment]
There are still cases that the host have enough resources, but only because the node have a `CriticalAddonsOnly` taint caused the daemonset cannot start up on the node, this is not expected. Echo @gmarek we should definitely have some discuss for this to find a solution.

**Comment by k82cn** [comment]
> have some discuss for this to find a solution.

I think `priority/preemption` is the solution for `CriticalAddonsOnly` :).

**Comment by gyliu513** [comment]
>have some discuss for this to find a solution.

>>I think priority/preemption is the solution for CriticalAddonsOnly :).

For my above case, I think there should not be any preemption as the host still have enough resources but only because the pod cannot tolerate the `CriticalAddonsOnly` taint.

**Comment by gmarek** [comment]
Indeed `CriticalAddons` was a hack we had to do due to lack of proper priorities/preemption mechanism. That being said I don't know when priority/preemption is going to be beta, but I'm skeptical about this year. We can move faster with Taints and Tolerations.

**Comment by gyliu513** [comment]
Ah, I see, if we can enable the `priority/preemption`, then there is no need to use rescheduler, so we will not need to have the `CriticalAddons` taint on the node. But I think for now we may need a solution for this problem before  `priority/preemption`.

**Comment by k82cn** [comment]
> We can move faster with Taints and Tolerations.

No objection if it's a bug level enhancement :).

For now, there're two requirements in this issue:
1. Add `CriticalAddonsOnly` to daemonset by default
1. The host have enough resources, but only because the node have a `CriticalAddonsOnly` taint caused the daemonset cannot start up on the node

which one will we handle "faster"?

**Comment by gyliu513** [comment]
There is actually only one requirement, the item 2) you listed above is the requirement, and item 1) is the solution that I proposed when file this issue.
