### ISSUE TITLE
GCE kube-up uses inconsistent CNI binary directories

### ISSUE THREAD

**Issue by caseydavenport** [kubernetes/kubernetes#47453]
**Kubernetes version** (use `kubectl version`):
master

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): debian, gci
- **Install tools**: cluster/kube-up.sh

**What happened**:

Creating a cluster with GCI uses the `/home/kubernetes/bin` directory for CNI plugins.
Creating a cluster with debian uses the `/opt/cni/bin` directory for CNI plugins, which is read-only on GCI.

This makes it impossible to create a DaemonSet which works for both image types.

**What you expected to happen**:

The CNI installation directory should be the same across all image types.  In this case, it should be `/home/kubernetes/bin`.

CC @dnardo

**Comment by caseydavenport** [comment]
Some related work here: https://github.com/kubernetes/kubernetes/pull/42079

**Comment by dchen1107** [comment]
Ok, I approved this one for 1.7 since 

It helps clean up our CVM based tests. The cleanup code is also self-contained, shouldn't cause any issues on other cloud providers. But will double check through the pr.
