### ISSUE TITLE
Azure Storage Driver should allow customization of secret location

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#47452]
From @liggitt :

In the process of provisioning a PV, it creates a secret in the namespace of the PVC containing the account name and key (password) needed to mount the PV. This secret is visible to a namespace-limited user.

Steps:

1. Run a cluster with
the azure cloud provider
dynamic PV provisioning enabled
a storage class specified for the azure file dynamic provisioner
kube-controller-manager set to --use-service-account-credentials=false (the default) OR with the persistent-volume-binder service account given permission to create secrets
2. As a namespace-limited user, create a PVC requesting the azure file storageclass

Result:
Depending on your authorization policy, a secret with the password for the storage account is created in the same namespace as the PVC.

Relevant source:
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/azure_file/azure_provision.go#L161-L169
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_storage.go#L273
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/azure_file/azure_util.go#L78

Note:
If the cluster is running with RBAC authorization only, and the controller manager is running with --use-service-account-credentials, the persistent-volume-binder role does not permit creation of secrets, so the Provision() operation would fail, and the credentials would not be exposed.

We should update the PVC controller so that the namespace where the secret is created is customizable.

**Comment by liggitt** [comment]
> We should update the PVC controller so that the namespace where the secret is created is customizable.

Actually, the extraction of credentials from the cloud provider into auto-created secrets at all surprised me... can the nodes not get the mount credentials from their cloud provider impl as well, rather than via secrets?

**Comment by gnufied** [comment]
Similar issue is present for ceph-rbd too. https://github.com/kubernetes/kubernetes/issues/47427 

In that case though, there is no cloudprovider from which secrets can be automatically derived from. Looking at AzureFile provisioner code, similar pattern has been used.

**Comment by liggitt** [comment]
Sure, both should likely be fixed. The automatic placement of the credentials extracted from the cloudprovider is what is particularly concerning to me

**Comment by rootfs** [comment]
@gnufied the rbd case is different: there is no automatic secret placement, the secret is assumed to exist in the same namespace as the pod. If it is missing, admin creates, not rbd provisioner. This is documented [here](https://github.com/kubernetes/kubernetes/blob/master/examples/persistent-volume-provisioning/README.md#ceph-rbd)

@liggitt I Is opening a new provisioning parameter `namespace` to store the credential good to the issue?  The credentials have to be created by the cloudprovider in azure file's case: there is no other way to know the location of the file share, and unfortunately the location (i.e. storage account name) [is part of the secret](https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/azure_file).

**Comment by rootfs** [comment]
second look, opening new provisioning parameter is not the only thing, I also need a new `namespace` in azure file volume source to pick up the namespace in [this line](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/azure_file/azure_file.go#L206) 

@liggitt do we have precedence to reference cross-namespace api objects?

**Comment by liggitt** [comment]
cross-namespace from a pod, no. fully-qualified namespace from a PV (which is cluster-scoped), yes.
