### ISSUE TITLE
client-go workqueue example should show how to enable multiple workers

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#47465]
One benefit of using workqueue to build controller is that it allows multiple workers to safely process changes in parallel, e.g., the [workers](https://github.com/kubernetes/kubernetes/blob/v1.7.0-beta.1/pkg/controller/replicaset/replica_set.go#L163-L165) in the replicaset controller. The client-go workqueue [example](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/examples/workqueue) should demonstrate this use case.

cc @ahmetb @rmohr @wallrj

**Comment by rmohr** [comment]
@caesarxuchao, I can update it. Do you already have something in mind, what the worker should do?

Maybe something like having two labels and and increment the values there with PUTs in between and sleep?

**Comment by fengzixu** [comment]
I would like to take that. Is this issue open? @nikhita 
/assign

**Comment by fengzixu** [comment]
@nikhita ping :)

**Comment by nikhita** [comment]
> Is this issue open?

This issue is not fixed but I think it would be nicer if we had another example i.e. we don't modify the current example.

@caesarxuchao @sttts  thoughts?

Once there is a fixed approach decided for this, please feel free to send a PR! :tada:
