### ISSUE TITLE
test failure:  Simple CustomResourceDefinition creating/deleting custom resource definition objects works [Conformance]

### ISSUE THREAD

**Issue by monopole** [kubernetes/kubernetes#47464]
[gubernator](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-cvm-1-7-upgrade-cluster-new/4#customresourcedefinition-resources-simple-customresourcedefinition-creatingdeleting-custom-resource-definition-objects-works-conformance)

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/custom_resource_definition.go:58
Jun 12 23:10:33.948: failed to create CustomResourceDefinition: the server could not find the requested resource
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/custom_resource_definition.go:49from junit_01.xml
```

Consistently failing in [grid](https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-cvm-1-5-cvm-1-7-upgrade-cluster-new&include-filter-by-regex=%5EOverall%24%7CCustomResourceDefinition%5C%20resources%5C%20Simple%5C%20CustomResourceDefinition%5C%20creating%5C/deleting%5C%20custom%5C%20resource%5C%20definition%5C%20objects%5C%20works%5C%20%5C%5BConformance%5C%5D)

/sig api
/assign @enisoc 

As discussed, this might be because deployments are not working in 1.7 tests run after a 1.5->1.7 upgrade.

**Comment by enisoc** [comment]
At first I thought this was an upgrade test that tries to create CRD before the upgrade, but according to @monopole it's trying to run the 1.7 e2e against a post-upgrade cluster, which should actually work. I'll look into it.

cc @deads2k @sttts @nikhita

**Comment by sttts** [comment]
CRDs are not the only resource failing, seeing storage classes and certificates as well. I am not even sure it's an aggregation problem because native resource should have static http handlers installed, so without going through APIService dynamic registration.

**Comment by sttts** [comment]
As this happens on GKE, we don't see master logs. Those might tell us what happens.

**Comment by enisoc** [comment]
This appears to be due to #47553.
