### ISSUE TITLE
Test Failure: Certificates API should support building a client with a CSR

### ISSUE THREAD

**Issue by monopole** [kubernetes/kubernetes#47466]
[jenkins](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-cvm-1-7-upgrade-cluster-new/4#k8sio-certificates-api-should-support-building-a-client-with-a-csr)
[grid](https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-cvm-1-5-cvm-1-7-upgrade-cluster-new&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Certificates%5C%20API%5C%20should%5C%20support%5C%20building%5C%20a%5C%20client%5C%20with%5C%20a%5C%20CSR)

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/certificates.go:120
Expected error:
    <*errors.StatusError | 0xc4210bfd00>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "the server could not find the requested resource",
            Reason: "NotFound",
            Details: {Name: "", Group: "", Kind: "", UID: "", Causes: nil, RetryAfterSeconds: 0},
            Code: 404,
        },
    }
    the server could not find the requested resource
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/certificates.go:70from
```
/sig api-machinery
/assign @enisoc 

Same root cause as #47464 ?

**Comment by enisoc** [comment]
This appears to be due to #47553.
