### ISSUE TITLE
Remove overlap annotation from Deployment

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#47463]
It's safe to remove `OverlapAnnotation` now.

- [ ] deployment controller: pkg/controller/deployment/deployment_controller.go
- [ ] deployment util: pkg/controller/deployment/util/deployment_util.go
- [ ] deployment reaper: pkg/kubectl/stop.go
- [ ] deployment describer: pkg/printers/internalversion/describe.go

@kubernetes/sig-apps-misc

**Comment by kargakis** [comment]
Dupe of https://github.com/kubernetes/kubernetes/issues/43322

**Comment by janetkuo** [comment]
Copied the list to #43322
