### ISSUE TITLE
1-5_1-7 upgrade test: configmap-related failures

### ISSUE THREAD

**Issue by monopole** [kubernetes/kubernetes#47472]
[ConfigMap optional updates should be reflected in volume [Conformance] [Volume]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-cvm-1-7-upgrade-cluster-new/4#k8sio-projected-optional-updates-should-be-reflected-in-volume-conformance-volume)

[ConfigMap should be consumable via the environment [Conformance]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-cvm-1-7-upgrade-cluster-new/4#k8sio-projected-should-be-consumable-from-pods-in-volume-conformance-volume)

[DNS configMap federations should be able to change federation configuration [Slow][Serial]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-cvm-1-7-upgrade-cluster-new/4#k8sio-dns-configmap-federations-should-be-able-to-change-federation-configuration-slowserial)

[DNS configMap nameserver should be able to change stubDomain configuration [Slow][Serial]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-cvm-1-7-upgrade-cluster-new/4#k8sio-dns-configmap-nameserver-should-be-able-to-change-stubdomain-configuration-slowserial)

/sig apps

1.7 release blocker?

**Comment by foxish** [comment]
Looking into this now.

**Comment by foxish** [comment]
There is an issue with the 1.5->1.7 tests where they're not going through 1.6 yet (cc @krousey). However, it's still not completely clear why these are occurring. 
These however look like storage and networking issues, and not sig-apps.

cc @kubernetes/sig-storage-bugs @kubernetes/sig-network-bugs

**Comment by cmluciano** [comment]
I'm not sure if the DNS tests are the overarching failure here. [Testgrid](https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-cvm-1-5-cvm-1-7-upgrade-cluster-new&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20DNS%5C%20configMap%5C%20federations%5C%20should%5C%20be%5C%20able%5C%20to%5C%20change%5C%20federation%5C%20configuration%5C%20%5C%5BSlow%5C%5D%5C%5BSerial%5C%5D) is showing a lot of green tests over the past few days. Overall these jobs seem to be failing in [this suite](https://k8s-testgrid.appspot.com/1.5-1.7-upgrade).

I drilled into one of the services related failures and found a note about [failure to validate a TLS certificate](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-cvm-1-7-upgrade-cluster/17).

@kubernetes/sig-cluster-lifecycle-misc any thoughts?

**Comment by mikedanese** [comment]
Those TLS errors are from goproxy test pod, not any certs that cluster-lifecycle owns. Looks like https://github.com/kubernetes/kubernetes/issues/38228#issuecomment-280213590

**Comment by cmluciano** [comment]
Nice find. I'm trying to determine what the fix would be here. Do we just need to cherrypick https://github.com/kubernetes/kubernetes/pull/44113 to 1.5/1.6?

**Comment by monopole** [comment]
These look like they are passing again in a few places, e.g.
https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-gci-1-5-cvm-1-7-upgrade-cluster&width=20&sort-by-failures=
And in other places there's no pass/fail, just white.

There were several problems with test-infra over last week, some of which have cleared which may be the issue here - see https://github.com/kubernetes/kubernetes/issues/47553

Now there there is more signal, will open more focussed issues as needed instead of this.
