### ISSUE TITLE
Network policy ingress from external ip

### ISSUE THREAD

**Issue by prasenforu** [kubernetes/kubernetes#47486]
In network policy we define ingress from pod 
But I want from external ip.

Not sure How I can implement?

Note: I am using kubeadm 1.6.4 with canal cni with ingress controler & RBAC

**Comment by prasenforu** [comment]
Normally it should go with Network.

Will be happy if Tim Hockin take care this issue.

**Comment by prasenforu** [comment]
Normally network policy support for ingress from
Podselector or namespaceselector.

But I am looking if I can do from any external ip or host.

**Comment by prasenforu** [comment]
@thockin

Looking for your input.

Thanks in advance.

**Comment by prasenforu** [comment]
Please help or close.

**Comment by cmluciano** [comment]
cc @danwinship

**Comment by danwinship** [comment]
There is currently no way to specify external IP addresses in NetworkPolicy rules. There has been some discussion about adding it but it's been on hold while we finalized the current NetworkPolicy support.

**Comment by thockin** [comment]
@cmluciano to close with his PRs

**Comment by cmluciano** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/49978

**Comment by cmluciano** [comment]
/close 

this was implemented in 1.8
[docs](https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-egress-traffic)
