### ISSUE TITLE
[Scheduler] predicates.go is bloated, we should consider separate each predicate func to it's own go file

### ISSUE THREAD

**Issue by wanghaoran1988** [kubernetes/kubernetes#47500]
As title, we need consider separate the predicate func to it's own go file for easier maintaining.
@k82cn @timothysc @bsalamat @davidopp

**Comment by bsalamat** [comment]
predicates.go is not super long today, at the same time I don't see any problem with breaking it into smaller separate files. Smaller files will be easier to manage in the future.
