### ISSUE TITLE
Secure traffic between pods in cluster

### ISSUE THREAD

**Issue by maxkondr** [kubernetes/kubernetes#47518]
Hi,
In some hosting environments/configurations, the network traffic between pods (applications) may traverse the public Internet. As a result, I'd like to secure the communication between the pods. 

For example, I have the following structure:

- Service_A - edge service in my product and provides access to my API to external users via public IP.
- Service_B and Service_C - microservices that has ClusterIP(s).

As I understand I can secure traffic user<-> Service_A by using Ingress controller with ssl certificate.
But how should I secure Service_A<->Service_B communication? Create additional ingress services to wrap microservices? Are there any best practices for such cases? 

One detail: microservices use gRPC for communication
Thanks

**Comment by qiujian16** [comment]
@maxkondr you may take look at this https://github.com/istio/istio

**Comment by maxkondr** [comment]
This solution looks interesting https://www.weave.works/docs/net/latest/tasks/manage/security-untrusted-networks/

**Comment by hzxuzhonghu** [comment]
internal ingress will work , deploy an internal ingress.

**Comment by maxkondr** [comment]
@hzxuzhonghu what do you mean by "internal ingress" ?

**Comment by hzxuzhonghu** [comment]
@maxkondr deploy an in cluster nginx-ingress or haproxy-ingress,  Service_A<->Service_B communication via this ingress LB. Also ingress can be a service, accessible by cluster domain.
