### ISSUE TITLE
Review Cluster Autoscaler code for Azure

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#47511]
Currently, the Azure support in Cluster Autoscaler (https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) is in a kind-of undefined state. There are some reports that it works, however the code doesn't compile with the most recent version of Azure client library and doesn't have a proper documentation. Community help is needed to:

* review the code and check whether it uses the correct Azure abstractions.
* test on a real Azure cluster.
* fix spotted issues.
* make it compile with the newest Azure libs.
* write good documentation.

Working on tracker: https://github.com/kubernetes/autoscaler/issues/449

cc: @jdumars @brendandburns

**Comment by doprdele** [comment]
+1

**Comment by VioletRainbows** [comment]
I've tried to make Azure CA works. Here are my findings:

- Unable understand the configuration requirement for `--cloud-config` (works with environment variables)
- It is able to scale, but k8s is not able to see the new nodes as per next point.
- Azure CA only works with Scale Sets, but k8s does not support Scale Set (yet?).

Relevant issues:
https://github.com/colemickens/azure-kubernetes-status/issues/17
https://github.com/kubernetes/kubernetes/issues/43287

**Comment by mwielgus** [comment]
As we didn't manage to find anyone to fix Azure support we have to disable it / comment it out until the situation improves.
cc: @jdumars @brendanburns

**Comment by mattjmcnaughton** [comment]
Just housekeeping - can this issue be closed since https://github.com/kubernetes/autoscaler/pull/229 is merged? Because the pr is in a different issue, Github couldn't automatically close the issue.

**Comment by agolomoodysaada** [comment]
Can we implement Kubernetes Autoscaler for Azure ACS? I don't mind working on it if someone could give me some guidance.

**Comment by MaciekPytel** [comment]
@agolomoodysaada I can help with general guidance and review if required. It's better to move the discussion about details to autoscaler repo though: https://github.com/kubernetes/autoscaler/issues/133.

Also feel free to ping me on slack if you want to have a quick chat about it (warning: I'm in central european timezone).

**Comment by andyzhangx** [comment]
@agolomoodysaada not yet, autoscaler depends on VMSS, and VMSS is not ready on azure now, even it's ready, we still needs azure-sdk-for-go sdk ready for VMSS.

**Comment by andyzhangx** [comment]
To be more precise: k8s on azure does not support VMSS now because VMSS does not support attach azure disk, azure autoscaler could be only used on a k8s cluster with VMSS. So that's the point here: you could implement autoscaler  now, but you could not test it as k8s does not support VMSS...

**Comment by feiskyer** [comment]
@andyzhangx Let me check and add it Azure back to autoscaler.

**Comment by jdumars** [comment]
@khenidak FYI

**Comment by jberkus** [comment]
Is this issue still tracking work to be done in 1.10?  If so, please add Kind and Priority labels to it before Code Slush begins Tuesday.  Thanks.

**Comment by jberkus** [comment]
@feiskyer if you're keeping this in 1.10, please add the required labels, or automation is going to kick it out. 

Also, please link to the PR(s) where the work is being done.  Thanks!

**Comment by MaciekPytel** [comment]
@feiskyer Azure cloudprovider has been merged back to CA after you fixed it. Are you planning to open any additional PRs related to it for 1.10? Otherwise I think there is no need to keep this issue in milestone. I would consider closing the issue and opening new one for any future work you want to do for 1.11 in autoscaler repo.

**Comment by feiskyer** [comment]
@MaciekPytel Thanks. There is still a PR on the way, but it should be considered part of https://github.com/kubernetes/autoscaler/issues/449. Let's close this one.
