### ISSUE TITLE
AWS not cleaning up routes

### ISSUE THREAD

**Issue by iterion** [kubernetes/kubernetes#47524]
Kubernetes on AWS seems to be leaving behind black hole routes when nodes leave the cluster.

v1.6.2
Debian Jessie
Linux ip-172-20-60-152 4.4.41-k8s #1 SMP Mon Jan 9 15:34:39 UTC 2017 x86_64 GNU/Linux
Provisioned with kops using kubenet networking

The cluster correctly create routes, but seems to not be attempting to clean up routes. So, a number of black hole routes are left behind. Ultimately, the cluster runs out of routes that are available to it (50 maximum by default on AWS) and new nodes fail to start.

When a node goes away its route should be deleted entirely.

Provision a new cluster using kops. Shut down a node and observe that the route table has not been cleaned up.

fyi @justinsb 

I'm investigating now to see if I can find a root cause, from my logs it seems that it's not even attempting to delete the route.

**Comment by devinburnette** [comment]
I'm also having this problem on v1.6.0 on AWS (provisioned with kops) running cluster autoscaler v0.5.3

**Comment by iterion** [comment]
From discussion on slack, it seems as if most people have cleanup scripts they're running to help. I think, though, for new users it could be frustrating and surprising. Especially if they plan on using the cluster-autoscaler. So, my personal preference would be 1.7.

**Comment by devinburnette** [comment]
Same. If it wasn't for the AWS imposed max on routes, I'd say we could wait, but this took me a while to troubleshoot in production and was a bit of a headache.

**Comment by justinsb** [comment]
OK - makes sense.  I think it's an easy fix, so I'll put it into 1.7 and see if others agree it can go in once we have a PR.

**Comment by iterion** [comment]
:+1: thanks @justinsb!

lmk if I can help out in any way.

**Comment by devinburnette** [comment]
Also related https://github.com/kubernetes/kubernetes/issues/33015

**Comment by justinsb** [comment]
Tentatively marketing approved-for-milestone, per https://github.com/kubernetes/kubernetes/pull/47572#issuecomment-308813052
