### ISSUE TITLE
E2E GKE cluster cannot up in both master and 1.7 branch

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#47534]
@caesarxuchao reports that GKE cluster cannot up with 1.7 branch. I quickly poked around, and found all gke test clusters are affected, not only 1.7 release branch. I also noticed that there is a new cloud SDK upgrade, which might be the cause. 

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-release-1-7/186/build-log.txt
```
W0614 17:16:33.877] ERROR: (gcloud.container.clusters.create) Operation [<Operation
W0614 17:16:33.877]  name: u'operation-1497459356306-b32c1acf'
W0614 17:16:33.878]  operationType: OperationTypeValueValuesEnum(CREATE_CLUSTER, 1)
W0614 17:16:33.878]  selfLink: u'https://test-container.sandbox.googleapis.com/v1/projects/752718673218/zones/us-central1-a/operations/operation-1497459356306-b32c1acf'
W0614 17:16:33.878]  status: StatusValueValuesEnum(DONE, 3)
W0614 17:16:33.878]  statusMessage: u'Timed out waiting for cluster initialization. Cluster API may not be available.'
W0614 17:16:33.878]  targetLink: u'https://test-container.sandbox.googleapis.com/v1/projects/752718673218/zones/us-central1-a/clusters/bootstrap-e2e'
W0614 17:16:33.878]  zone: u'us-central1-a'>] finished with error: Timed out waiting for cluster initialization. Cluster API may not be available.
W0614 17:16:34.505] 2017/06/14 17:16:34 util.go:131: Step './hack/e2e-internal/e2e-up.sh' finished in 21m34.239892608s
```

cc/ @gmarek @cheftako

**Comment by caesarxuchao** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-release-1-7/187/nodelog?junit=junit_runner.xml&wrap=on

```
error: failed to run Kubelet: cannot create certificate signing request: Post https://35.188.166.73/apis/certificates.k8s.io/v1beta1/certificatesigningrequests: dial tcp 35.188.166.73:443: getsockopt: connection refused
```
Maybe a kubelet cert rotation issue?

**Comment by yujuhong** [comment]
Caused by #47094. I believe @cheftako is investigating.

**Comment by cheftako** [comment]
#47094 <https://github.com/kubernetes/kubernetes/pull/47094> only went in
to 1.7. So it should not be the cause of any problems on GKE clusters which
pre-date 1.7
-Walter

**Comment by dchen1107** [comment]
Could be, that is why I cc-ed him. But based on the information I had from @caesarxuchao I kindly ruled out https://github.com/kubernetes/kubernetes/pull/47094 from @cheftako because the pr was merged two days, and @caesarxuchao did fast forward everyday to 1.7 branch. But the failure in 1.7 started yesterday. Unless the timelines I collected are mismatch here.

**Comment by dchen1107** [comment]
Ok, update the title. The failures are only on both master branch and 1.7 branch.

**Comment by caesarxuchao** [comment]
Thanks @yujuhong. The mistake i made was that i compared the timestamp of a relesae-1.7 branch commit with that of a the master branch commit. I should had used `git diff`.
