### ISSUE TITLE
Service is always forwarding the request to same pod

### ISSUE THREAD

**Issue by Rev1408** [kubernetes/kubernetes#47533]
I have a single node Kubernetes cluster, with Master tainted. I am running 2 pods and a service with Type: NodePort on the same node. I was expecting the service to load balance the requests between the two pods, but looks like all the requests are always getting forwarded to same pod.

**Comment by cmluciano** [comment]
can you dump the iptables rules on that node?

```
sudo iptables-save
```

**Comment by Rev1408** [comment]
@cmluciano IP tables is stopped on my node.

`
# Generated by iptables-save v1.6.0 on Wed Jun 14 14:16:19 2017
*mangle
:PREROUTING ACCEPT [735856780:654787400020]
:INPUT ACCEPT [724608001:601541728756]
:FORWARD ACCEPT [8505064:52979893648]
:OUTPUT ACCEPT [518239734:248437323893]
:POSTROUTING ACCEPT [526766053:301417897701]
-A POSTROUTING -o virbr0 -p udp -m udp --dport 68 -j CHECKSUM --checksum-fill
-A POSTROUTING -o virbr1 -p udp -m udp --dport 68 -j CHECKSUM --checksum-fill
COMMIT
# Completed on Wed Jun 14 14:16:19 2017
# Generated by iptables-save v1.6.0 on Wed Jun 14 14:16:19 2017
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:DOCKER - [0:0]
:KUBE-MARK-DROP - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-NODEPORTS - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-SEP-6FZLAPUAJM6OKK6A - [0:0]
:KUBE-SEP-CXEQ55XIH4PURQSE - [0:0]
:KUBE-SEP-IT2ZTR26TO4XFPTO - [0:0]
:KUBE-SEP-QL7KI24MTSZRY3Q3 - [0:0]
:KUBE-SEP-T76A7WETYR6OJELR - [0:0]
:KUBE-SEP-YIL6JZP7A3QYXJU2 - [0:0]
:KUBE-SERVICES - [0:0]
:KUBE-SVC-ERIFXISQEP7F7OF4 - [0:0]
:KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
:KUBE-SVC-RCFZYSCVQORLOLVD - [0:0]
:KUBE-SVC-TCOU7JCQXEZGVUNU - [0:0]
:KUBE-SVC-XGLOHA7QRQ3V22RZ - [0:0]
:WEAVE - [0:0]
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 192.168.122.0/24 -d 224.0.0.0/24 -j RETURN
-A POSTROUTING -s 192.168.122.0/24 -d 255.255.255.255/32 -j RETURN
-A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -p tcp -j MASQUERADE --to-ports 1024-65535
-A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -p udp -j MASQUERADE --to-ports 1024-65535
-A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -j MASQUERADE
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -j WEAVE
-A POSTROUTING -s 10.244.0.0/16 -d 10.244.0.0/16 -j RETURN
-A POSTROUTING -s 10.244.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE
-A POSTROUTING ! -s 10.244.0.0/16 -d 10.244.0.0/16 -j MASQUERADE
-A POSTROUTING -s 172.17.0.2/32 -d 172.17.0.2/32 -p tcp -m tcp --dport 80 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 8082 -j DNAT --to-destination 172.17.0.2:80
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-NODEPORTS -p tcp -m comment --comment "kube-system/kubernetes-dashboard:" -m tcp --dport 32634 -j KUBE-MARK-MASQ
-A KUBE-NODEPORTS -p tcp -m comment --comment "kube-system/kubernetes-dashboard:" -m tcp --dport 32634 -j KUBE-SVC-XGLOHA7QRQ3V22RZ
-A KUBE-NODEPORTS -p tcp -m comment --comment "default/memory-service:" -m tcp --dport 32450 -j KUBE-MARK-MASQ
-A KUBE-NODEPORTS -p tcp -m comment --comment "default/memory-service:" -m tcp --dport 32450 -j KUBE-SVC-RCFZYSCVQORLOLVD
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE
-A KUBE-SEP-6FZLAPUAJM6OKK6A -s 172.31.139.86/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
-A KUBE-SEP-6FZLAPUAJM6OKK6A -p tcp -m comment --comment "default/kubernetes:https" -m recent --set --name KUBE-SEP-6FZLAPUAJM6OKK6A --mask 255.255.255.255 --rsource -m tcp -j DNAT --to-destination 172.31.139.86:6443
-A KUBE-SEP-CXEQ55XIH4PURQSE -s 10.244.0.69/32 -m comment --comment "default/memory-service:" -j KUBE-MARK-MASQ
-A KUBE-SEP-CXEQ55XIH4PURQSE -p tcp -m comment --comment "default/memory-service:" -m tcp -j DNAT --to-destination 10.244.0.69:80
-A KUBE-SEP-IT2ZTR26TO4XFPTO -s 10.244.0.2/32 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-MARK-MASQ
-A KUBE-SEP-IT2ZTR26TO4XFPTO -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp" -m tcp -j DNAT --to-destination 10.244.0.2:53
-A KUBE-SEP-QL7KI24MTSZRY3Q3 -s 10.244.0.70/32 -m comment --comment "default/memory-service:" -j KUBE-MARK-MASQ
-A KUBE-SEP-QL7KI24MTSZRY3Q3 -p tcp -m comment --comment "default/memory-service:" -m tcp -j DNAT --to-destination 10.244.0.70:80
-A KUBE-SEP-T76A7WETYR6OJELR -s 10.244.0.26/32 -m comment --comment "kube-system/kubernetes-dashboard:" -j KUBE-MARK-MASQ
-A KUBE-SEP-T76A7WETYR6OJELR -p tcp -m comment --comment "kube-system/kubernetes-dashboard:" -m tcp -j DNAT --to-destination 10.244.0.26:9090
-A KUBE-SEP-YIL6JZP7A3QYXJU2 -s 10.244.0.2/32 -m comment --comment "kube-system/kube-dns:dns" -j KUBE-MARK-MASQ
-A KUBE-SEP-YIL6JZP7A3QYXJU2 -p udp -m comment --comment "kube-system/kube-dns:dns" -m udp -j DNAT --to-destination 10.244.0.2:53
-A KUBE-SERVICES ! -s 10.244.0.0/16 -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
-A KUBE-SERVICES ! -s 10.244.0.0/16 -d 10.110.38.64/32 -p tcp -m comment --comment "kube-system/kubernetes-dashboard: cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.110.38.64/32 -p tcp -m comment --comment "kube-system/kubernetes-dashboard: cluster IP" -m tcp --dport 80 -j KUBE-SVC-XGLOHA7QRQ3V22RZ
-A KUBE-SERVICES ! -s 10.244.0.0/16 -d 10.105.72.103/32 -p tcp -m comment --comment "default/memory-service: cluster IP" -m tcp --dport 8080 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.105.72.103/32 -p tcp -m comment --comment "default/memory-service: cluster IP" -m tcp --dport 8080 -j KUBE-SVC-RCFZYSCVQORLOLVD
-A KUBE-SERVICES -d 172.31.139.86/32 -p tcp -m comment --comment "default/memory-service: external IP" -m tcp --dport 8080 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 172.31.139.86/32 -p tcp -m comment --comment "default/memory-service: external IP" -m tcp --dport 8080 -m physdev ! --physdev-is-in -m addrtype ! --src-type LOCAL -j KUBE-SVC-RCFZYSCVQORLOLVD
-A KUBE-SERVICES -d 172.31.139.86/32 -p tcp -m comment --comment "default/memory-service: external IP" -m tcp --dport 8080 -m addrtype --dst-type LOCAL -j KUBE-SVC-RCFZYSCVQORLOLVD
-A KUBE-SERVICES ! -s 10.244.0.0/16 -d 10.96.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
-A KUBE-SERVICES ! -s 10.244.0.0/16 -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SERVICES -m comment --comment "kubernetes service nodeports; NOTE: this must be the last rule in this chain" -m addrtype --dst-type LOCAL -j KUBE-NODEPORTS
-A KUBE-SVC-ERIFXISQEP7F7OF4 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-SEP-IT2ZTR26TO4XFPTO
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m recent --rcheck --seconds 10800 --reap --name KUBE-SEP-6FZLAPUAJM6OKK6A --mask 255.255.255.255 --rsource -j KUBE-SEP-6FZLAPUAJM6OKK6A
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -j KUBE-SEP-6FZLAPUAJM6OKK6A
-A KUBE-SVC-RCFZYSCVQORLOLVD -m comment --comment "default/memory-service:" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-CXEQ55XIH4PURQSE
-A KUBE-SVC-RCFZYSCVQORLOLVD -m comment --comment "default/memory-service:" -j KUBE-SEP-QL7KI24MTSZRY3Q3
-A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns" -j KUBE-SEP-YIL6JZP7A3QYXJU2
-A KUBE-SVC-XGLOHA7QRQ3V22RZ -m comment --comment "kube-system/kubernetes-dashboard:" -j KUBE-SEP-T76A7WETYR6OJELR
COMMIT
# Completed on Wed Jun 14 14:16:19 2017
# Generated by iptables-save v1.6.0 on Wed Jun 14 14:16:19 2017
*filter
:INPUT ACCEPT [86:16144]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [87:19250]
:DOCKER - [0:0]
:DOCKER-ISOLATION - [0:0]
:KUBE-FIREWALL - [0:0]
:KUBE-SERVICES - [0:0]
:WEAVE-NPC - [0:0]
:WEAVE-NPC-DEFAULT - [0:0]
:WEAVE-NPC-INGRESS - [0:0]
-A INPUT -i virbr0 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -i virbr0 -p tcp -m tcp --dport 53 -j ACCEPT
-A INPUT -i virbr0 -p udp -m udp --dport 67 -j ACCEPT
-A INPUT -i virbr0 -p tcp -m tcp --dport 67 -j ACCEPT
-A INPUT -i virbr1 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -i virbr1 -p tcp -m tcp --dport 53 -j ACCEPT
-A INPUT -i virbr1 -p udp -m udp --dport 67 -j ACCEPT
-A INPUT -i virbr1 -p tcp -m tcp --dport 67 -j ACCEPT
-A INPUT -j KUBE-FIREWALL
-A INPUT -p tcp -m tcp --dport 30204 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 3128 -j ACCEPT
-A INPUT -d 172.17.0.1/32 -i docker0 -p tcp -m tcp --dport 6783 -j DROP
-A INPUT -d 172.17.0.1/32 -i docker0 -p udp -m udp --dport 6783 -j DROP
-A INPUT -d 172.17.0.1/32 -i docker0 -p udp -m udp --dport 6784 -j DROP
-A INPUT -i docker0 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -i docker0 -p tcp -m tcp --dport 53 -j ACCEPT
-A FORWARD -d 192.168.122.0/24 -o virbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 192.168.122.0/24 -i virbr0 -j ACCEPT
-A FORWARD -i virbr0 -o virbr0 -j ACCEPT
-A FORWARD -o virbr0 -j REJECT --reject-with icmp-port-unreachable
-A FORWARD -i virbr0 -j REJECT --reject-with icmp-port-unreachable
-A FORWARD -i virbr1 -o virbr1 -j ACCEPT
-A FORWARD -o virbr1 -j REJECT --reject-with icmp-port-unreachable
-A FORWARD -i virbr1 -j REJECT --reject-with icmp-port-unreachable
-A FORWARD -i docker0 -o weave -j DROP
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o weave -j WEAVE-NPC
-A FORWARD -o weave -m state --state NEW -j NFLOG --nflog-group 86
-A FORWARD -o weave -j DROP
-A FORWARD -i weave ! -o weave -j ACCEPT
-A FORWARD -o weave -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -o virbr0 -p udp -m udp --dport 68 -j ACCEPT
-A OUTPUT -o virbr1 -p udp -m udp --dport 68 -j ACCEPT
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -j KUBE-FIREWALL
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER-ISOLATION -j RETURN
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
-A WEAVE-NPC -m state --state RELATED,ESTABLISHED -j ACCEPT
-A WEAVE-NPC -d 224.0.0.0/4 -j ACCEPT
-A WEAVE-NPC -m state --state NEW -j WEAVE-NPC-DEFAULT
-A WEAVE-NPC -m state --state NEW -j WEAVE-NPC-INGRESS
COMMIT
# Completed on Wed Jun 14 14:16:19 2017
`

**Comment by cmluciano** [comment]
If you are using the default kube-proxy mode iptables mode, the flag ``--mode random --probability`` is being injected for your services. 

In the output above ``--mode random --probability 0.50000000000 -j KUBE-SEP-CXEQ55XIH4PURQSE`` is being set. This means that 50% of the time you will be directed to ``10.244.0.69:80``. If you deployed another replica, this should change to 33%. 

It's important to note that random does not mean uniform and it is possible that you will note the majority of the traffic could hit 1 pod.

adding @kubernetes/sig-network-misc to clarify if I am mistaken.

**Comment by caseydavenport** [comment]
```
-A KUBE-SEP-CXEQ55XIH4PURQSE -s 10.244.0.69/32 -m comment --comment "default/memory-service:" -j KUBE-MARK-MASQ
-A KUBE-SEP-CXEQ55XIH4PURQSE -p tcp -m comment --comment "default/memory-service:" -m tcp -j DNAT --to-destination 10.244.0.69:80
```

Looks to me like the kube-proxy thinks there's only one valid Pod backing that Service.

What does `kubectl get endpoints memory-service` output? Does it show two endpoints?

**Comment by thockin** [comment]
This is almost 2 months old.  Closing.
