### ISSUE TITLE
Kubelets in kubemark creating larger QPS than in real cluster

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#47544]
![kubelet](https://user-images.githubusercontent.com/4333971/27151453-e2a03ad6-514a-11e7-9031-769a00262096.jpg)

This has been plotted using apiserver logs from our 100-node gce test (run 2701) and 100-node kubemark test (run 3203). The first peak is from density test and the second from load test. Both of them had density running first and the graphs are almost aligned in terms of timing of the tests.

We need to understand why the hollow-kubelets are making 1.5-2 times the no. of api calls as real kubelets.

cc @kubernetes/sig-scalability-misc @gmarek @wojtek-t

**Comment by shyamjvs** [comment]
Similar to issue https://github.com/kubernetes/kubernetes/issues/47540, but that one's for difference in qpm due to apiserver. Also, this one is even more important as the difference seen is huge (thousands of qpm).

**Comment by shyamjvs** [comment]
The yellow line also includes calls from kube-proxy (as both proxy and kubelet use the same client named 'kubemark/v1.8.0'), however those are negligible (< 50 qpm) in comparison to kubelet.
Further for node-problem-detector we are having similar qpm across both, so that's fine.

![npd](https://user-images.githubusercontent.com/4333971/27152105-1722ecd4-514d-11e7-9dfd-22064c431b1c.jpg)

**Comment by shyamjvs** [comment]
There's also a difference seen for the client "kubectl/v1.6.4", and this difference is almost exclusively because of the kube-addon-manager which creates a plethora of addons (services, controllers and configmaps, clusterrolebindings for them) in the case of real cluster.

![kubectl](https://user-images.githubusercontent.com/4333971/27152923-d15499c0-514f-11e7-93ac-38a693d885d6.jpg)

It makes about ~100 calls once every minute to maintain all those addons. Basically it does a `kubectl apply` against the addons directory every minute to reconcile them (ref: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/kube-addons.sh#L135). But for our purpose of scalability, we can neglect this difference as it's not much compared to kubelets.

**Comment by shyamjvs** [comment]
Here's the top few calls (by count) due to kubelets in real cluster:

```
  19187 POST/api/v1/namespaces/e2e-tests-load-30-nodepods-1-n8jh3/events:
  15500 POST/api/v1/namespaces/e2e-tests-density-30-1-nbmqn/events:
  11267 GET/api/v1/namespaces/e2e-tests-load-30-nodepods-1-n8jh3/secrets/default-token-b5bgl:
   8715 GET/api/v1/namespaces/e2e-tests-density-30-1-nbmqn/secrets/default-token-pppbn:
   5094 POST/api/v1/namespaces/kube-system/events:
   2029 GET/api/v1/namespaces/kube-system/secrets/default-token-8h7f3?resourceVersion=0:
   1989 GET/api/v1/namespaces/kube-system/configmaps/fluentd-gcp-config-v1.0?resourceVersion=0:
   1954 GET/api/v1/namespaces/kube-system/secrets/node-problem-detector-token-ls57k?resourceVersion=0:
   1110 POST/api/v1/namespaces/default/events:
    779 GET/api/v1/namespaces/e2e-tests-load-30-nodepods-1-n8jh3/secrets/default-token-b5bgl?resourceVersion=0:

```

And in kubemark:

```
 103095 GET/api/v1/namespaces/e2e-tests-load-30-nodepods-1-3gdh2/secrets/default-token-l6kvz?resourceVersion=0:
  58596 GET/api/v1/namespaces/e2e-tests-density-30-1-crvpj/secrets/default-token-jxwk6?resourceVersion=0:
  14361 GET/api/v1/namespaces/e2e-tests-load-30-nodepods-1-3gdh2/secrets/default-token-l6kvz:
  11468 GET/api/v1/namespaces/e2e-tests-density-30-1-crvpj/secrets/default-token-jxwk6:
```

Hollow-kubelets seem to make many many `get secret` calls for the default-token in the load & density test namespace even though (IIUC) the CachingSecretManager is there on both kubelet and hollow-kubelet.

**Comment by shyamjvs** [comment]
/cc @wasylkowski 

Some useful commands I used to get the count of calls by kubelet:
`grep "kubelet/v1.8.0" kube-apiserver.log | grep "wrap.go:42" | awk '{print $5 $6}' | sort | uniq -c | sort -nr | less` (for real cluster)
`grep "kubemark/v1.8.0" kube-apiserver.log | grep "wrap.go:42" | awk '{print $5 $6}' | sort | uniq -c | sort -nr | less` (for kubemark cluster)

To be specific, I used [gce-scalability test's run 2701](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scalability/2701) and [kubemark-100 test's run 3203](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-100-gce/3203) for generating the data for comparison. Here's the script to get the counts of calls from different components for each minute of the test:

```
for i in {22..50}; do     # since this test ran from 07:22 to 07:50
grep " 07:$i" gce-2701-apiserver.log | grep "wrap.go" | awk '{print $9}' | sort | uniq -c | sort -nr | sed -e 's|^|'${i}' |';
echo "";
done > gce-calls.txt

for i in {26..52}; do     # since this test ran from 07:26 to 07:52
grep " 07:$i" kubemark-3203-apiserver.log | grep "wrap.go" | awk '{print $9}' | sort | uniq -c | sort -nr | sed -e 's|^|'${i}' |';
echo "";
done > kubemark-calls.txt
```

**Comment by wasylkowski** [comment]
I looked into this and all the spurious "GET secrets" calls are caused by hollow node's Volume Manager reconciler loop constantly looping and trying to mount a "secret" volume. As part of this process the "GET secrets" call gets issued. I will probably not have time to look more deeply into this, so I am sharing what I have found so far.

**Comment by wasylkowski** [comment]
As far as I can tell each mount ends up successful, and yet remount is attempted all the time. "Why" is to be investigated.

**Comment by wasylkowski** [comment]
Newest finding: a call to "rc.actualStateOfWorld.PodExistsInVolume" in the "reconcile" function inside Volume Manager's reconciler.go file results in a "remountRequiredError" error, and this is what is triggering endless remounts.

**Comment by gmarek** [comment]
cc @yujuhong - does someone from the Node team have time to look into the mock that we use?

**Comment by shyamjvs** [comment]
Is there a reason why we need to send get secret call for each attempt to mount the volume?
I would expect to get it only the first time and then keep it for subsequent retries (until 1 minute after which the secret-manager would anyway re-get).

**Comment by yujuhong** [comment]
> Is there a reason why we need to send get secret call for each attempt to mount the volume?
> I would expect to get it only the first time and then keep it for subsequent retries (until 1 minute after which the secret-manager would anyway re-get).

The TTL of the secrets are defined based on the size of the cluster: https://github.com/kubernetes/kubernetes/blob/v1.8.0-alpha.1/pkg/controller/ttl/ttlcontroller.go#L104
In a 100 node cluster, TTL is 0.

> cc @yujuhong - does someone from the Node team have time to look into the mock that we use?

The storage team may be able to help. /cc @saad-ali
