### ISSUE TITLE
components crash if Azure cloud-config file is not well-formed

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#47543]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): No

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): Looked for an issue field by me about this

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`): v1.6.x

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): n/a
- **Kernel** (e.g. `uname -a`): n/a
- **Install tools**: CUSTOM
- **Others**:

**What happened**:
You fail to specify cloud-config flag or you point to a file with missing fields and the components will crash due to panics for nil derefs.

**What you expected to happen**:
A more graceful crash/warning/error as appropriate.

**How to reproduce it** (as minimally and precisely as possible):
Don't specify the config file, or specify it with missing fields.

**Anything else we need to know**:
No

**Comment by discordianfish** [comment]
Also the code comments on the struct say that some fields are optional while leaving them out causes a panic.

**Comment by itowlson** [comment]
For the missing field case, do we have a definitive list of which fields are required?  I can try inferring from code comments, but @discordianfish observes those may be out of date.

**Comment by itowlson** [comment]
The existing tests around validation are a bit confusing.  The `TestCloudDefaultConfigFrom*` tests (which are really just testing that backoff and rate limiting are defaulted to false, not testing any other defaults) expect to be able to use a config JSON/YAML containing only the AAD client ID and secret, e.g. no resource group ID.  Is that really a valid cloud config?

**Comment by jdumars** [comment]
Bringing this to SIG-Azure meeting for discussion.

**Comment by discordianfish** [comment]
/remove-lifecycle stale
/lifecycle freeze

I'm so close writing a bot-bot unstaling these..

**Comment by justaugustus** [comment]
@colemickens @kubernetes/sig-azure-misc -- do we have an updated status for this?
/assign @kubernetes/sig-azure-misc

/remove-lifecycle rotten
/lifecycle frozen

**Comment by feiskyer** [comment]
The issues have been fixed. controller manager will fail with errors now instead of panic.

/close
