### ISSUE TITLE
QPS due to apiserver differing b/w kubemark and real cluster

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#47540]
![apiserver](https://user-images.githubusercontent.com/4333971/27150367-3ec43686-5147-11e7-84e7-c279de60f089.jpg)

This has been plotted using apiserver logs from our 100-node gce test ([run 2701](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scalability/2701)) and 100-node kubemark test ([run 3203](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-100-gce/3203)). The first peak is from density test and the second from load test. Both of them had density running first and the graphs are almost aligned in terms of timing of the tests.

Need to understand why we don't see any peaks in kubemark. I'll look deeper into it later this week.

cc @kubernetes/sig-scalability-misc @gmarek @wojtek-t

**Comment by shyamjvs** [comment]
The QPM arising from scheduler and controller-manger seem to be matching across both. It's just something wrong with the apiserver.

![scheduler](https://user-images.githubusercontent.com/4333971/27151104-d1ffe5ce-5149-11e7-8437-7c5ce6b3dbcd.jpg)

![controller-manager](https://user-images.githubusercontent.com/4333971/27151115-d76fcf7e-5149-11e7-920f-800a1ecf4d9d.jpg)

**Comment by gmarek** [comment]
Last two graphs are awesome!
