### ISSUE TITLE
switch from gazel to gazelle

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#47558]
Currently the Go rules in BUILD files are generated by [gazel](https://github.com/mikedanese/gazel).

We should switch to using the officially-supported [gazelle tool](https://github.com/bazelbuild/rules_go/tree/master/go/tools/gazelle), along with some sort of successor to gazel which generates the srcs and generated-code rules.

cc @spxtr @mikedanese

**Comment by ixdy** [comment]
I've moved `kazel` to `repo-infra/kazel`.

Next steps:
1. Make `hack/*-bazel.sh` scripts use `kazel` instead of `gazel`.
2. Make `kazel` run across the entire repo, similar to what `gazelle` will do.
3. Remove go rule functionality from `kazel` (or at least make it configurable)
4. Make `hack/*-bazel.sh` scripts use `gazelle` and `kazel` together.

An open question is how to version `kazel` and `gazelle`. It's now possible to call `gazelle` using bazel, which will use the appropriate version (https://github.com/bazelbuild/rules_go/issues/564#issuecomment-312033669), though that means that we'd need a bazel image to use with the `hack/*-bazel.sh` scripts. (We probably want a bazel image anyway.)
If we decide to go that route, we could probably version `kazel` the same way, since we already import the `repo-infra` repo into the main repo.

**Comment by mikedanese** [comment]
Opened https://github.com/bazelbuild/rules_go/issues/614 which I was planning on doing in gazel.

**Comment by ixdy** [comment]
Removing go rule functionality from `kazel` is proving to be a bit tricky, since we only want it to ignore go-like automanaged rules.

We'll probably want to remove the `automanaged` tag from all of our go rules; something like  https://github.com/bazelbuild/buildtools/tree/master/buildozer will probably be useful here.

We also need to make sure `gazelle` ignores rules we've explicitly removed the `automanaged` tag from.
A bazel query for that is
`https://github.com/bazelbuild/buildtools/tree/master/buildozer`
