### ISSUE TITLE
With dynamically provisioned volume, deleting a PVC tried to delete PV though volume is in use by Pod 

### ISSUE THREAD

**Issue by shilpamayanna** [kubernetes/kubernetes#47556]
Kubernetes version:1.6

1. Created out of tree dynamic provisioner as a Pod
2. Created storage class with provisioner
3. Created PVC with the storageclassname created in step 2
4. PV got created by the provisioner
5. Created a Pod with PVC. 
6. Deleted the PVC
7. This invoked PV delete though PV is in use by a Pod  

PV should not be deleted when it is in use

**Comment by gnufied** [comment]
This is being handled via https://github.com/kubernetes/kubernetes/issues/45143.

**Comment by gnufied** [comment]
closing as dupe.

/close
