### ISSUE TITLE
Consistent hash label key across controllers

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#47554]
Here are the hash label keys of all controllers:
- Deployment: `pod-template-hash`
- DaemonSet: `daemonset-controller-hash` (new in 1.7)
- StatefulSet: `statefulset.beta.kubernetes.io/revision` (new in 1.7)

Had a brief discussion with @bgrant0607 and @kow3ns about this, it should be consistent. We can use `controller-revision-hash` for DaemonSet and StatefulSet, and keep Deployment as-is. Deployment hash label key should be different from other two because Deployment pods hash labels is used by selector (unlike the other two controllers). 

We probably should have used hash annotations instead of hash labels for DaemonSet and StatefulSet, since we don't use hash labels to select their history or pods. Hash labels are chosen for consistency. This is fine since we don't modify hash label values. 

@kubernetes/sig-apps-misc @kubernetes/sig-apps-api-reviews

**Comment by yuyulei** [comment]
Actually, revisions created by  statefulset, daemonset has different label:

`
// revision created by statefulset 
label: controller.kubernetes.io/hash: "1618963020"

// revision created by daemonset
label: controller-revision-hash: "1976076852"
`
@kow3ns @janetkuo should be consistent?
