### ISSUE TITLE
Massive failures in 1.5 to 1.7 upgrade test jobs

### ISSUE THREAD

**Issue by monopole** [kubernetes/kubernetes#47553]
These 1.5 to 1.7 upgrade test jobs all have over 25% failure rates:
 
* [gke-cvm-1-5-cvm-1-7-upgrade-cluster-new]
* [gke-cvm-1-5-gci-1-7-upgrade-cluster-new]
* [gke-gci-1-5-cvm-1-7-upgrade-cluster-new]
* [gke-gci-1-5-gci-1-7-upgrade-cluster-new]

Per the [job naming convention], these `-new` tests first upgrade the cluster (i.e. master and nodes, from 1.5 to 1.7) and then run the _new_ test suite (1.7) with new kubectl.
 
Conversely, the remaining jobs in the 1.5-1.7 [job set] are relatively green:

 * [gke-cvm-1-5-cvm-1-7-upgrade-cluster]
 * [gke-cvm-1-5-cvm-1-7-upgrade-master]
 * [gke-cvm-1-5-gci-1-7-upgrade-cluster]
 * [gke-cvm-1-5-gci-1-7-upgrade-master]
 * [gke-gci-1-5-cvm-1-7-upgrade-cluster]
 * [gke-gci-1-5-cvm-1-7-upgrade-master]
 * [gke-gci-1-5-gci-1-7-upgrade-cluster]
 * [gke-gci-1-5-gci-1-7-upgrade-master]
 
These presumably run the 1.5 test suite with 1.5 kubectl, after either the master and nodes (or just the master) are upgraded to 1.7.
 
Although a two step upgrade isn’t encouraged, we do want skew from 1.7 to 1.5 to work, and these tests may be failing due to some unrecognized skew failure.

This [__spreadsheet__] shards the failures roughly by SIG.  

Can all leads take a look at the failure clusters assigned to their SIG and comment on this issue as to why the failure?  Hoping there's a common cause.
 
[job set]: https://k8s-testgrid.appspot.com/1.5-1.7-upgrade

[gke-cvm-1-5-cvm-1-7-upgrade-cluster-new]: https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-cvm-1-5-cvm-1-7-upgrade-cluster-new&sort-by-failures=
[gke-cvm-1-5-gci-1-7-upgrade-cluster-new]: https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-cvm-1-5-gci-1-7-upgrade-cluster-new&sort-by-failures=
[gke-gci-1-5-cvm-1-7-upgrade-cluster-new]: https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-gci-1-5-cvm-1-7-upgrade-cluster-new&sort-by-failures=
[gke-gci-1-5-gci-1-7-upgrade-cluster-new]: https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-gci-1-5-gci-1-7-upgrade-cluster-new&sort-by-failures=

[gke-cvm-1-5-cvm-1-7-upgrade-cluster]: https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-cvm-1-5-cvm-1-7-upgrade-cluster&sort-by-failures=
[gke-cvm-1-5-cvm-1-7-upgrade-master]: https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-cvm-1-5-cvm-1-7-upgrade-master&sort-by-failures=
[gke-cvm-1-5-gci-1-7-upgrade-cluster]: https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-cvm-1-5-gci-1-7-upgrade-cluster&sort-by-failures=
[gke-cvm-1-5-gci-1-7-upgrade-master]: https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-cvm-1-5-gci-1-7-upgrade-master&sort-by-failures=
[gke-gci-1-5-cvm-1-7-upgrade-cluster]: https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-gci-1-5-cvm-1-7-upgrade-cluster&sort-by-failures=
[gke-gci-1-5-cvm-1-7-upgrade-master]: https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-gci-1-5-cvm-1-7-upgrade-master&sort-by-failures=
[gke-gci-1-5-gci-1-7-upgrade-cluster]: https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-gci-1-5-gci-1-7-upgrade-cluster&sort-by-failures=
[gke-gci-1-5-gci-1-7-upgrade-master]: https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-gci-1-5-gci-1-7-upgrade-master&sort-by-failures=

[job naming convention]: https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md#test-jobs-naming-convention

[__spreadsheet__]: https://docs.google.com/spreadsheets/d/1_nloj0q3fwTJLHkwWYnUSA7bZABfSVROy2hNUvsWeR8/pubhtml

**Comment by monopole** [comment]
sigs mentioned in spreadsheet:

* apps @mattfarina 
* node @dawnchen, @derekwaynecarr 
* cli @pwittrock 
* cluster-lifecycle @lukemarsden 
* storage @saad-ali 
* network @bowei 
* scheduling @davidopp 
* api-machinery @deads2k 

Please look at the tests in rows assigned to a given SIG for a common cause.

**Comment by monopole** [comment]
@kubernetes/sig-apps-bugs 
@kubernetes/sig-api-machinery-bugs 
@kubernetes/sig-storage-bugs 
@kubernetes/sig-node-bugs 
@kubernetes/sig-cluster-lifecycle-bugs 
@kubernetes/sig-network-bugs

**Comment by smarterclayton** [comment]
About half of the failures in the first job are due to APIs that don't exist in 1.5 (initializers, storage classes?, taints, new fields, etc).

**Comment by smarterclayton** [comment]
How are we doing exclusions for these tests - PRs to the jobs?  List here and one PR to the job?

**Comment by smarterclayton** [comment]
I think we want a bulk skip for all of the failing jobs (the same tests will not work on 1.5 across all four)

**Comment by pwittrock** [comment]
Are we sure the cluster is being successfully upgraded?  From a spot check, it looks like the tests that are failing are new tests, and like Clayton pointed out, can't find the APIs.  If the cluster had been upgraded successfully, I would expect the APIs to be found.

**Comment by pwittrock** [comment]
Looks like the clusters were not being upgraded properly.

**Comment by monopole** [comment]
Closing this.  Expecting that when https://github.com/kubernetes/test-infra/pull/3069 filters through, we'll have a different set of problems.  Hopefully more green.

**Comment by ixdy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-cvm-1-7-upgrade-cluster-new/7 (started right after kubernetes/test-infra#3069 was merged) seems to be behaving more correctly.

**Comment by monopole** [comment]
reopening, as the test still aren't running correctly.

**Comment by monopole** [comment]
"Up" is failing in the -new tests, e.g. [gke-cvm-1-5-cvm-1-7-upgrade-cluster-new Up](https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-cvm-1-5-cvm-1-7-upgrade-cluster-new&include-filter-by-regex=%5EOverall%24%7CUp)

Extract from [Log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-cvm-1-7-upgrade-cluster-new/8/build-log.txt):
```
 ERROR: (gcloud.container.clusters.create) Operation [<Operation
W0615 18:40:28.684]  name: u'operation-1497552018556-177f01d5'
W0615 18:40:28.684]  operationType: OperationTypeValueValuesEnum(CREATE_CLUSTER, 1)
W0615 18:40:28.685]  selfLink: u'https://test-container.sandbox.googleapis.com/v1/projects/858159230786/zones/us-central1-f/operations/operation-1497552018556-177f01d5'
W0615 18:40:28.685]  status: StatusValueValuesEnum(DONE, 3)
W0615 18:40:28.686]  statusMessage: u'Failed to create cluster'
W0615 18:40:28.686]  targetLink: u'https://test-container.sandbox.googleapis.com/v1/projects/858159230786/zones/us-central1-f/clusters/bootstrap-e2e'
W0615 18:40:28.686]  zone: u'us-central1-f'>] finished with error: Failed to create cluster
W0615 18:40:29.920] 2017/06/15 18:40:29 util.go:131: Step './hack/e2e-internal/e2e-up.sh' finished in 45.798681034s
```

A little later:
```
W0615 18:41:26.227] ERROR: (gcloud.compute.networks.delete) Could not fetch resource:
W0615 18:41:26.227]  - The network resource 'projects/gke-up-c1-3-clat-up-clu-n/global/networks/bootstrap-e2e' is already being used by 'projects/gke-up-c1-3-clat-up-clu-n/global/firewalls/k8s-fw-l7--b305ff005b48c952'
```
then not much later 
```
W0615 18:41:46.047] 2017/06/15 18:41:46 main.go:195: Something went wrong: starting e2e cluster: error during ./hack/e2e-internal/e2e-up.sh: exit status 1

```

**Comment by ixdy** [comment]
I thought this might be a GKE issue, but that only seems to be affecting 1.7, e.g. the regular 1.5 GKE jobs are running without issue: http://k8s-testgrid.appspot.com/google-gke#gci-gke-1.5&width=20

I have no idea how to debug GKE startup failures.

**Comment by monopole** [comment]
Tracking (google only) GKE issue here: b/62674799

**Comment by timothysc** [comment]
There needs to be an exclusion filter applied to this as some api-promoted items simply won't work.

**Comment by monopole** [comment]
There were layers of problems.  The silliness of kubernetes/test-infra#3069, then an internal problem with cluster deletion cleanup and IP leaking (which prevented cluster creation referred to above), and now I'm waiting to get _some_ signal on the `upgrade-cluster` tests.  Some take 7h+ to run, so I'm keeping this issue open.

@smarterclayton, @timothsc - once the test infra is healthy, there's still the question of which tests should actually be run.  PR's to filter would be welcome.  I'm functioning as a build cop, and don't have the background on the changes over the last qtr that should have been accompanied by modifications of upgrade tests.  

FWIW, for 1.8 we're going to get upgrade tests against master (1.6 -> master, 1.7 -> master) in place as soon as 1.7 is out.

**Comment by monopole** [comment]
Hi @krousey , @krzyzacy (and @timothysc sic above)

I'm using this as a master issue for all the failing upgrade tests - please mention in it in related work, would like to close it and shard it into specific things to fix, once we get more data.

**Comment by smarterclayton** [comment]
Happy to

**Comment by monopole** [comment]
tests seem to be running.  filing new issues at a higher resolution now that we have a clearer signal
