### ISSUE TITLE
Validation of RBAC rules

### ISSUE THREAD

**Issue by jimmycuadra** [kubernetes/kubernetes#47574]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): rbac validation

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

It would be helpful if the API server could validate RBAC rules upon creation. Right now it's possible to create rules targeting resources which don't exist.

For example, I just ran into a case where port forwarding was being denied for one of our developers, and the problem turned out to be that "portforward" was misspelled in our RBAC rule that was should have allowed it.

It would have been great to have the API server catch this when the resources were first created. Something like:

```
$ kubectl apply -f rbac-rules.yml
Error: No resource "pods/portfoward" in API group "core".
```

**Comment by xilabao** [comment]
@liggitt

**Comment by liggitt** [comment]
The RBAC system does not know all the resources that it could be asked to authorize. Much of its power lies in its generic nature.

**Comment by liggitt** [comment]
I don't see this being built into the API, but as an external analysis/diagnostic tool, I agree it could be useful
