### ISSUE TITLE
Make sure the discovery fake client can be effectively used in unit tests

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#47608]
I had a brief look and it wasn't clear enough how should I use the fake discovery client - also some calls seemed like they existed only to satisfy the Discovery client interface. We should make sure the fake client is actually usable and start using it in unit tests (such as for https://github.com/kubernetes/kubernetes/pull/47450)

https://github.com/kubernetes/client-go/blob/master/discovery/fake/discovery.go

/sig cli

**Comment by shiywang** [comment]
will take a look
