### ISSUE TITLE
pull-kubernetes-federation-e2e-gce fails a lot today

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#47609]
e.g.,
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/47580/pull-kubernetes-federation-e2e-gce/10512/

@saad-ali  the build cop
@dchen1107

**Comment by csbell** [comment]
Waiting for a fix in https://github.com/kubernetes/kubernetes/issues/47600
