### ISSUE TITLE
garbage collector test fails on aws

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#47601]
https://k8s-testgrid.appspot.com/release-1.7-blocking#aws-release-1-7&width=20

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-release-1-7/213

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/garbage_collector.go:424
Jun 15 08:26:36.910: remaining rs are: &v1beta1.ReplicaSetList{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"/apis/extensions/v1beta1/namespaces/e2e-tests-gc-3lg8r/replicasets", ResourceVersion:"5268"}, Items:[]v1beta1.ReplicaSet(nil)}
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/garbage_collector.go:418
```

Probably caused by https://github.com/kubernetes/kubernetes/pull/45764, though don't understand why it only fails on aws. cc @kargakis @krmayankk 

@justinsb i remember GC tests were failing on aws (but not on other platform) months before, do you happen to know the cause?

cc @kubernetes/kubernetes-release-managers

**Comment by justinsb** [comment]
It looks like ff503dbc32b6041509829e98d7e952af7bd43694 is related and landed in the batch that caused the breakage.  Are other clouds experiencing the same problem?

**Comment by justinsb** [comment]
Just realized you said the same thing @caesarxuchao ... sorry!

Can finalizers be explicitly enabled / disabled?

**Comment by caesarxuchao** [comment]
yes, the "enable-garbage-collector" controls that.

But there is another test that relies on the finalizers, https://github.com/kubernetes/kubernetes/blob/master/test/e2e/garbage_collector.go#L264, that test is passing.

**Comment by dchen1107** [comment]
Close this one since it passed last couple days.

**Comment by caesarxuchao** [comment]
@justinsb did we do anything to fix it? I think nothing?
