### ISSUE TITLE
hyperkube lacks nsenter causing kubenet hooks to fail

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#47618]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): "nsenter"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.6.3

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): Xenial
- **Kernel** (e.g. `uname -a`): Latest xenial stable
- **Install tools**: ACS-Engine
- **Others**: n/a

**What happened**: Seeing lots of these in kubelet logs:

`Jun 15 21:51:52 k8s-agentpool1-79924091-2 docker[1565]: W0615 21:51:52.718090    1638 docker_sandbox.go:263] NetworkPlugin kubenet failed on the status hook for pod "nginx-306052057-7sw2h_namespace-32022": Unexpected command output nsenter: cannot open : No such file or directory`

**What you expected to happen**: Not see those warnings.

**How to reproduce it** (as minimally and precisely as possible):
Boot a cluster with `kubeadm` (kubeadm uses hyperkube as well, I've confirmed on my home cluster that these same warnings appear). I think the exact line is different since kubeadm uses CNI (in my case, I was using Calico).

**Anything else we need to know**:

cc: @luxas

---

Do we want to just install nsenter? Or whatever deb package provides it in hyperkube? If so, I can send a PR for it. Thanks.

**Comment by colemickens** [comment]
I can't tell if this is related: https://github.com/kubernetes/kubernetes/issues/42735

/sig sig-cluster-lifecycle-misc

**Comment by yanxuean** [comment]
I have a  similar problem。
In `GetPodNetworkStatus`,  `GetNetNS `should  return  `/proc/nnnn/ns/net`  but return null string .
Because container `pid = 0` ,  so print error info"NetworkPlugin cni failed on the status hook for pod '577db2f2-97ec-44a5-9c35-448980a13f6c-1-8px7k' - Unexpected command output nsenter: cannot open : No such file or directory".
I donn't know the reason.  I suspect HandlePodRemoves deleted pod,There is race condition.

```go
func (plugin *cniNetworkPlugin) GetPodNetworkStatus(namespace string, name string, id kubecontainer.ContainerID) (*network.PodNetworkStatus, error) {
	netnsPath, err := plugin.host.GetNetNS(id.ID)

	ip, err := network.GetPodIP(plugin.execer, plugin.nsenterPath, netnsPath, network.DefaultInterfaceName)   《--DefaultInterfaceName = "eth0"
	if err != nil {
		return nil, err
	}

	return &network.PodNetworkStatus{IP: ip}, nil
}
```

**Comment by yanxuean** [comment]
refer to    https://github.com/kubernetes/kubernetes/issues/45334

**Comment by luxas** [comment]
I'm pretty sure nsenter is in the hyperkube image: https://github.com/kubernetes/kubernetes/blob/master/cluster/images/hyperkube/Dockerfile#L28

As far as I can remember, it has always been there.

I guess the problem is something else...
