### ISSUE TITLE
Some GKE tests are failing because of calico-typha pod being unschedulable

### ISSUE THREAD

**Issue by mindprince** [kubernetes/kubernetes#47622]
Example: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-alpha-features/13492

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:216
Jun 15 13:35:54.975: Error waiting for all pods to be running and ready: 1 / 17 pods in namespace "kube-system" are NOT in RUNNING and READY state in 10m0s
POD                           NODE PHASE   GRACE CONDITIONS
calico-typha-3071995635-ww7ps      Pending       [{PodScheduled False 0001-01-01 00:00:00 +0000 UTC 2017-06-15 13:23:55 -0700 PDT Unschedulable No nodes are available that match all of the following predicates:: MatchNodeSelector (3).}]

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:167
```

cc - @dnardo @caseydavenport

Maybe related to #47188 

/sig network
/area platform/gke
/kind bug
/priority failing-test

**Comment by dnardo** [comment]
I guess DaemonSet's behave differently the deployments wrt to scheduling.  So in the DaemonSet case we return no nodes to run on since no labels match.  In the deployment case (Typha) we want to run at least one thing and cannot so it sits in pending.  

Maybe the default for typha should be replicas 0?  And then we can set the replicas at runtime?

**Comment by dnardo** [comment]
Actually maybe leave it as is for now but in the e2e test maybe we just set it to 0?

**Comment by caseydavenport** [comment]
Discussed with @dnardo, I think the right fix is [in this function](https://github.com/caseydavenport/kubernetes/blob/948c6c8027f47f0ac28098976dcd464770f785d4/cluster/gce/container-linux/configure-helper.sh#L56).

We should return typha_count=0 if NETWORK_POLICY_PROVIDER is not set to `calico`.

**Comment by mindprince** [comment]
@dnardo @caseydavenport The tests are still failing with the same error: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-alpha-features/13935

**Comment by dnardo** [comment]
I think the problem is here: 

  if [[ "${NETWORK_POLICY_PROVIDER:-}" == "calico" ]]; then
    setup-addon-manifests "addons" "calico-policy-controller"
.....
    sed -i -e "s@__CALICO_TYPHA_REPLICAS__@$(get-calico-typha-replicas)@g" "${typha_dep_file}"

I think we need to set that count to _CALICO_TYPHA_REPLICAS__ regardless of provider

**Comment by dchen1107** [comment]
ping ...

**Comment by caseydavenport** [comment]
@dchen1107 working on the fix that @dnardo suggested in PR https://github.com/kubernetes/kubernetes/pull/47669.

Tests are currently failing but haven't gotten to the bottom of it yet.

**Comment by mindprince** [comment]
This if fixed now.
