### ISSUE TITLE
Azure Attach/Detach Disk api calls do not correctly monitor status

### ISSUE THREAD

**Issue by shrutir25** [kubernetes/kubernetes#47623]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): Yes

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
Azure Attach/Detach
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Kubernetes version** (use `kubectl version`): 1.6.2

**Environment**:
- **Cloud provider or hardware configuration**: Azure

**What happened**:
Azure Disk attach / detach api calls do not correctly monitor status.  This generates large amounts of 400 level errors of type “AcquireDiskLeaseFailed” and  and "AttachDiskWhileBeingDetached"  for  k8* VMs created by Kubernetes template deployments, reducing the customer QPS.
 
/sig azure

**Comment by khenidak** [comment]
Thanks for reporting this one. 

This behavior has been fixed in the new plugin. The plug-in is available in v 1.7.2++ . The new plugin check if there is a lease on the disk before attempting to attach it.

**Comment by shrutir25** [comment]
@khenidak thanks for the update !

**Comment by andyzhangx** [comment]
Hi @khenidak , I am a little confused about this issue, it seems from v1.5, the plugin already checks if there is a lease before attaching, see:
https://github.com/kubernetes/kubernetes/blob/release-1.6/pkg/cloudprovider/providers/azure/azure_storage.go#L81
