### ISSUE TITLE
Figure out a way to automatically update swagger-spec for swagger ui on kubernetes.io

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#4763]
We use https://github.com/GoogleCloudPlatform/kubernetes/tree/gh-pages/swagger-spec to produce the static documentation at http://kubernetes.io/third_party/swagger-ui/.
The spec there is a copy of https://github.com/GoogleCloudPlatform/kubernetes/tree/master/api/swagger-spec which is generated from code using https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/update-swagger-spec.sh.
Right now, we need to manually copy the swagger spec files from master to gh-pages branch each time it changes.
We need to figure out a way to automate this, to prevent the documentation at http://kubernetes.io/third_party/swagger-ui/ from getting stale.

**Comment by smarterclayton** [comment]
Closing due to age, generally this has been solved by newer doc generation tools.
