### ISSUE TITLE
Rest api for upgradation pods image "x" to "y"

### ISSUE THREAD

**Issue by sidd14491** [kubernetes/kubernetes#47635]
I am trying to upgrade pods image "x" to "y" through rest call but it's throwing error every time
Content:
Method : PATCH
URL :http://10.213.18.39:8080/api/v1/namespaces/default/pods/csp.csp-shared-object-1582379414-8e1v5 

Body:
{
	"kind": "Pod",
	"apiVersion": "v1",
	"spec": {
		"containers": [{
			"image": "sspt-artifactory.juniper.net/shared-object-api-svr:3.1.0.dev367"
		}]
	}
}
Earlier image is ::sspt-artifactory.juniper.net/shared-object-api-svr:3.1.0.dev342 and am trying to upgrade sspt-artifactory.juniper.net/shared-object-api-svr:3.1.0.dev367

Content/Type : application/strategic-merge-patch+json

OS::: Ubuntu
So,can you suggest me any rest call avail for upgradation of pods if it is avail so pls guide me how can we do it

**Comment by liggitt** [comment]
when patching a list that specifies a mergeKey, you need to include the key in the patch item so the server knows which item in the list you are patching.

the mergeKey for containers is the "name" field, so this patch should work:
```json
{
  "kind": "Pod",
  "apiVersion": "v1",
  "spec": {
    "containers": [{
      "name": "your-container-name",
      "image": "sspt-artifactory.juniper.net/shared-object-api-svr:3.1.0.dev367"
    }]
  }
}
```

**Comment by sidd14491** [comment]
After giving mention json input:

{
  "kind": "Pod",
  "apiVersion": "v1",
  "spec": {
    "containers": [{
      "name": "csp.csp-shared-object-2386506139-orp8m",
      "image": "sspt-artifactory.juniper.net/shared-object-api-svr:3.1.0.dev379"
    }]
  }
}
Still it's failing
Giving following error
{
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "the server responded with the status code 415 but did not return more information",
    "details": {},
    "code": 415
}

**Comment by liggitt** [comment]
Ah, you need to indicate which patch type you are submitting with a `Content-Type: application/strategic-merge-patch+json` header

**Comment by sidd14491** [comment]
After giving content-type as you mentioned 
Input JSON
{
  "kind": "Pod",
  "apiVersion": "v1",
  "spec": {
    "containers": [{
      "name": "csp.csp-shared-object-2386506139-orp8m",
      "image": "sspt-artifactory.juniper.net/shared-object-api-svr:3.1.0.dev379"
    }]
  }
}


I am getting following error:


{
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "Pod \"csp.csp-shared-object-2386506139-orp8m\" is invalid: [spec.containers[1].name: Invalid value: \"csp.csp-shared-object\": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or '123-abc'), spec.containers: Forbidden: pod updates may not add or remove containers]",
    "reason": "Invalid",
    "details": {
        "name": "csp.csp-shared-object-2386506139-orp8m",
        "kind": "Pod",
        "causes": [
            {
                "reason": "FieldValueInvalid",
                "message": "Invalid value: \"csp.csp-shared-object\": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or '123-abc')",
                "field": "spec.containers[1].name"
            },
            {
                "reason": "FieldValueForbidden",
                "message": "Forbidden: pod updates may not add or remove containers",
                "field": "spec.containers"
            }
        ]
    },
    "code": 422
}

**Comment by liggitt** [comment]
Make sure the container name you specify matches the name of an existing container in the pod spec
