### ISSUE TITLE
compile kubernetes failed !!

### ISSUE THREAD

**Issue by y123456yz** [kubernetes/kubernetes#47644]
I compile the code as following, but failed:

$ go get -d k8s.io/kubernetes
$ cd $GOPATH/src/k8s.io/kubernetes
$ make

error info:
[root@localhost kubernetes]# make -j 2
+++ [0616 03:49:16] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [0616 03:49:16] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [0616 03:49:21] Generating bindata:
    test/e2e/generated/gobindata_util.go
+++ [0616 03:49:21] Generating bindata:
    test/e2e/generated/gobindata_util.go
/usr/share/gocode/src/github.com/src/k8s.io/kubernetes /usr/share/gocode/src/github.com/src/k8s.io/kubernetes/test/e2e/generated
/usr/share/gocode/src/github.com/src/k8s.io/kubernetes /usr/share/gocode/src/github.com/src/k8s.io/kubernetes/test/e2e/generated
/usr/share/gocode/src/github.com/src/k8s.io/kubernetes/test/e2e/generated
/usr/share/gocode/src/github.com/src/k8s.io/kubernetes/test/e2e/generated
+++ [0616 03:49:22] Building go targets for linux/amd64:
    cmd/libs/go2idl/defaulter-gen
+++ [0616 03:49:22] Building go targets for linux/amd64:
    cmd/libs/go2idl/deepcopy-gen
+++ [0616 03:49:30] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [0616 03:49:30] Generating bindata:
    test/e2e/generated/gobindata_util.go
/usr/share/gocode/src/github.com/src/k8s.io/kubernetes /usr/share/gocode/src/github.com/src/k8s.io/kubernetes/test/e2e/generated
+++ [0616 03:49:30] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [0616 03:49:30] Generating bindata:
    test/e2e/generated/gobindata_util.go
/usr/share/gocode/src/github.com/src/k8s.io/kubernetes /usr/share/gocode/src/github.com/src/k8s.io/kubernetes/test/e2e/generated
stat pkg/generated/bindata.go.tmp: no such file or directory
/usr/share/gocode/src/github.com/src/k8s.io/kubernetes/test/e2e/generated
../../../../../../test/e2e/generated/gobindata_util.go:19: running "../../../hack/generate-bindata.sh": exit status 2
+++ [0616 03:49:32] Building go targets for linux/amd64:
    cmd/libs/go2idl/conversion-gen
!!! [0616 03:49:32] Call tree:
!!! [0616 03:49:32]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0616 03:49:32] Call tree:
!!! [0616 03:49:32]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make[1]: *** [_output/bin/openapi-gen] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [generated_files] Error 2

**Comment by k82cn** [comment]
what's your go version & OS?

**Comment by y123456yz** [comment]
@k82cn 

[root@localhost ~]# uname -a
Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost ~]# go version
go version go1.6.3 linux/amd64
[root@localhost ~]#

**Comment by y123456yz** [comment]
[root@localhost ~]# cat /proc/version 
Linux version 3.10.0-327.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Thu Nov 19 22:10:57 UTC 2015
[root@localhost ~]#

**Comment by gyliu513** [comment]
You need to upgrade to your go version to 1.8.1

Please refer to https://github.com/kubernetes/kubernetes/issues/45214 for detail

@y123456yz

**Comment by gyliu513** [comment]
@y123456yz can this one be closed?
