### ISSUE TITLE
PersistentVolumes provide no way of finding remaining space / usage

### ISSUE THREAD

**Issue by tobilarscheid** [kubernetes/kubernetes#47649]
**What keywords did you search in Kubernetes issues before filing this one?**
volume free space 

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):

`Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T22:51:55Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.6-4+abe34653415733", GitCommit:"abe346534157336e6bd5a70702756cff19d43a49", GitTreeState:"clean", BuildDate:"2017-05-18T16:52:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Cloud provider or hardware configuration**: IBM Container Service

**What happened**:

I am trying to find out the remaining free space of a volume.

**What you expected to happen**:

I expect `kubectl describe pv` to output a usage or remaining capacity gauge.

**How to reproduce it** (as minimally and precisely as possible):

Run `kubectl describe pv %YOUR-PV`. There is no gauge.

**Anything else we need to know**:

Providing the gauge would allow monitoring solutions to expose this metric, as I think it is very important.

**Comment by tobilarscheid** [comment]
@kubernetes/sig-Storage-misc

**Comment by gnufied** [comment]
There was a plan to implement this for 1.7 but we ran out of time. We are planing to do this for 1.8 now. cc @jingxu97

**Comment by tobilarscheid** [comment]
Alright, thanks for your feedback! Is there a feature request or something I can subscribe to to get updates on this?

**Comment by ddysher** [comment]
@tobilarscheid you can subscribe to https://github.com/kubernetes/features/issues/293

**Comment by tobilarscheid** [comment]
Alright, thank you!
