### ISSUE TITLE
How kube-apiserver run with  Public network IP 

### ISSUE THREAD

**Issue by fatg1988** [kubernetes/kubernetes#47642]
my server is running on Aliyun ECS. Check the configuration and see only the intranet ip,
Public network IP is not in ifconfig result list.
**Can kube-apiservice use public network IP binding?**

The 3 configuration with the intranet IP and 0.0.0.0 normal, with the public network IP reported wrong.

  --advertise-address=${MASTER_IP} \\
  --bind-address=${MASTER_IP} \\
  --insecure-bind-address=${MASTER_IP} \\

ifconfig result:

`docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 172.30.37.1  netmask 255.255.255.0  broadcast 0.0.0.0
        ether 02:42:8b:b0:03:9e  txqueuelen 0  (Ethernet)
        RX packets 21997  bytes 4011073 (3.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 21635  bytes 9872155 (9.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.39.128  netmask 255.255.240.0  broadcast 172.17.47.255
        ether 00:16:3e:32:e4:08  txqueuelen 1000  (Ethernet)
        RX packets 186365  bytes 236808045 (225.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 96579  bytes 16329913 (15.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 172.30.37.0  netmask 255.255.255.255  broadcast 0.0.0.0
        ether 56:42:1b:0e:26:f0  txqueuelen 0  (Ethernet)
        RX packets 1952  bytes 189827 (185.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1729  bytes 200966 (196.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1  (Local Loopback)
        RX packets 276471  bytes 84447679 (80.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 276471  bytes 84447679 (80.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`

**How to change the Endpoints to Public network IP?**

`kubectl describe svc kubernetes
Name:			kubernetes
Namespace:		default
Labels:			component=apiserver
			provider=kubernetes
Annotations:		<none>
Selector:		<none>
Type:			ClusterIP
IP:			10.254.0.1
Port:			https	443/TCP
Endpoints:		172.17.39.128:6443
Session Affinity:	ClientIP
Events:			<none>`

`kubectl edit svc kubernetes

# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-06-15T06:19:04Z
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "27"
  selfLink: /api/v1/namespaces/default/services/kubernetes
  uid: 87db7f29-5192-11e7-99f3-00163e32e408
spec:
  clusterIP: 10.254.0.1
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: ClientIP
  type: ClusterIP
status:
  loadBalancer: {}`

**Comment by fatg1988** [comment]
/sig apiserver
k8s version 1.6.2

**Comment by caseydavenport** [comment]
I'm not very familiar with Aliyun ECS, but it looks like your instance doesn't have a public IP address assigned to it.  What about using a cloud [load-balancer](https://intl.aliyun.com/help/doc-detail/27552.htm) for getting external traffic to the master?

**Comment by prateekgogia** [comment]
If you install with Kubeadm, it gives you an option to advertise api-server address -  --apiserver-advertise-address=`publicIP`. This will generate kube.config file with this IP and Kubectl can remotely talk to this IP address. Hope, this helps.

**Comment by caseydavenport** [comment]
@fatg1988 did you ever find a resolution to this?  Is it OK if I close this issue?

It seems like if the master has a public IP on one of its interfaces, you can bind to it using the `--bind-address` and `--insecure-bind-address` options.  If the master doesn't have a public IP on one of its interfaces, you'll need to use a load balancer or something to get traffic from the outside world to the master.
