### ISSUE TITLE
udp proxy loop should use fine tuned buffer

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#47659]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

kube-proxy
proxy loop
proxysocket

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

in `kubernetes/pkg/proxy/userspace/proxysocket.go` the udp proxyLoop should use fine-tuned buffer, and not just a 4kb buffer.

**Comment by caseydavenport** [comment]
@yastij could you add some more detail about what the implications of this change would be?  i.e. what's the user-facing impact of this issue?

**Comment by yastij** [comment]
@caseydavenport - yea sure, here's the buffer i'm talking about : https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/userspace/proxysocket.go#L203

this modification shouldn't have much impact on the user-facing side.

we'll have to build a histogram of how much we read on the first iterations then fine tune our buffer.

**Comment by yastij** [comment]
got stuck on other issues, after @thockin feedback on state and usage of userspace, I think this can be closed @caseydavenport
