### ISSUE TITLE
gluster mounter runs unpermitted operations from nodes

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#47657]
https://github.com/kubernetes/kubernetes/pull/45528 added several operations to the glusterfs mount operation that nodes are not permitted to perform:

1. it looks up arbitrary secrets based on storage class parameters. this will not succeed, as the node authorizer will only allow nodes access to secrets referenced by pods or persistent volumes used by the node
2. it attempts to create a service and endpoint using the node's API client. nodes do not have permission to create arbitrary endpoints and services.

For both of those reasons, that recreate operation will fail when attempted from the node. The recreate operation should probably move to one of the storage-related controllers (provisioner or attach/detach)

cc @rootfs @humblec @kubernetes/sig-storage-bugs

**Comment by saad-ali** [comment]
Marking this with 1.7 milestone until we have a better idea of whether this is blocking or not for the 1.7 release.

**Comment by saad-ali** [comment]
CC @kubernetes/sig-storage-bugs 

> In some setups, after creation of dynamic PVs and before mounting/using these PVs in a pod, the endpoint/service got mistakenly deleted by the user/developer. By making these methods 'plugin' specific, we can call it from mounter if there are scenarios where the endpoint and service got wiped in between accidentally.

@humblec @rootfs Is the endpoint originally created by the user or by the volume plugin creating/deleting Endpoint objects? In addition to the concerns @liggitt raised, having a volume create new API objects seems like a bad idea (abstraction layer violation?).

**Comment by saad-ali** [comment]
From @liggitt on Slack:

> It seems like it is trying to add compensation for an error condition. There weren't any tests for it, so I'm guessing no one noticed it didn't work. I'd probably revert the PR for 1.7 and get the recreate running from a controller in 1.8

@humblec @rootfs Unless there is justification otherwise, I will roll back the PR on Monday.

**Comment by dchen1107** [comment]
cc/ @kubernetes/kubernetes-release-managers

**Comment by rootfs** [comment]
revert button doesn't work, have to do it manually

**Comment by saad-ali** [comment]
@dchen1107 Revert PR is approved and awaiting merge (https://github.com/kubernetes/kubernetes/pull/47726). Once that merges this issue can be closed.

**Comment by copejon** [comment]
Opened an E2E pr to catch this kind of behavior in the future.  WIP, still exploring a method to reproduce and catch the behavior.

https://github.com/kubernetes/kubernetes/pull/47795
