### ISSUE TITLE
Test API error return when attempting to {POST, PUT} an object that is too large

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#47668]
It seems that this error message is not being returned correctly ("apiserver received an error that is not an metav1.Status: etcdserver: request is too large").

**Comment by cnwalker** [comment]
Hey! I'm very new to kubernetes, but I'd like to take a crack at this one if possible. Any ideas on which files I should look at to get started?

**Comment by lavalamp** [comment]
@cnwalker I would probably write an integration test for this--should be an example in the test/integration directory. Just find a test that makes e.g. a pod, copy it, make it add a 1mb annotation, and test the error message.

**Comment by mkumatag** [comment]
I tried creating pod with some random sized annotation and got following error : 
```Failed to create pod: Pod "activedeadlineseconds-test-0" is invalid: metadata.annotations: Too long: must have at most 262144 characters```

Seems like they have restriction for annotation size - https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/validation/objectmeta.go#L39

**Comment by tcharding** [comment]
Hi @lavalamp, is this issue still worth working on? Can I confirm your original issue statement please. Is the issue that 'request is too large' is not the correct error message? Should the original error '...annotations: Too long: must have at most 262144 bytes' be being returned?

I implemented a test in `integration/pods/pods_test.go` and got the same error as @mkumatag listed above. Doing so does not seem to solve any issue though? Any hints on what you hoped to have fixed please?

**Comment by dungeonmaster18** [comment]
Hi @lavalamp anyone working on this? if not I would like to take this. I am a new contributor here. So if I can get more detailed guidance that will be appreciable.

**Comment by nkprince007** [comment]
Hi! I'm a newcomer here. Has this issue been taken by someone? If not I'd like to work on this. Please help me get started.

**Comment by anubhakushwaha** [comment]
@stts I would like to work upon this

**Comment by nikhita** [comment]
/remove-lifecycle stale

@sttts @anubhakushwaha afaik https://github.com/kubernetes/kubernetes/pull/61010 didn't completely fix this, did it?

Also, are we still looking for help on this issue? This has the help-wanted label and I want to make sure that all such issues are upto date. :)

**Comment by lavalamp** [comment]
Sorry, didn't notice the activity on this until now.

If there is a size limit on annotations, you may have to make multiple smallish ones to test the behavior.

It's great that we now test the behavior, but we should really return a constant error message when the object exceeds the size limit (whatever that is) and not pass through the etcd / gRPC error message, those don't help end users understand what happened.

**Comment by sttts** [comment]
@nikhita #61010 is indeed only the test, but a good starting point to fix it. I think it is still a good issue for newcomers to the apimachinery area. So let's keep that open and tagged. `etcdserver: request is too large` is actually not too bad. But of course we can do better.

**Comment by matthewkenigsberg** [comment]
I'd like to work on this. Should there be a size limit placed on objects as a whole, or should there just be a different error displayed to the user when etcd or gRPC returns an error?
