### ISSUE TITLE
LeaderElector only looks at its own LeaseDuration, not the leader's

### ISSUE THREAD

**Issue by bboreham** [kubernetes/kubernetes#47671]
This is an observation from reading the code; apologies if I've misunderstood.

[Line 220](https://github.com/kubernetes/kubernetes/blob/204fb62d4931b036732eeeca9e362c833ccc7a3b/pkg/client/leaderelection/leaderelection.go#L220) is the only place `LeaseDurationSeconds` is used.

At [Line 246](https://github.com/kubernetes/kubernetes/blob/204fb62d4931b036732eeeca9e362c833ccc7a3b/pkg/client/leaderelection/leaderelection.go#L246) `LeaderElector` considers whether the lock has expired, but only with reference to its own idea of the lease duration.

This means that, if two instances of this code were configured with, say, 10 seconds and 30 seconds for `LeaseDuration`, then the 10-second one would happily steal the lock from the 30-second one while the latter carried on thinking it had the lock until the next random check.

So if I've got that right, the code at line 246 should be more like `le.observedTime.Add(le.observedRecord.LeaseDurationSeconds * time.Second).After(now.Time)`

/sig node

**Comment by malc0lm** [comment]
I think [Line 242](https://github.com/kubernetes/kubernetes/blob/204fb62d4931b036732eeeca9e362c833ccc7a3b/pkg/client/leaderelection/leaderelection.go#L242) has already check your problem. It means that if local LeaderElector's observedRecord is not equal with leader's, it will update to leader's "oldLeaderElectionRecord" which is obtained by [Line 226](https://github.com/kubernetes/kubernetes/blob/204fb62d4931b036732eeeca9e362c833ccc7a3b/pkg/client/leaderelection/leaderelection.go#L226)

**Comment by malc0lm** [comment]
I think the situation which you described will not happen. `LeaseDuration` is just for non-leader candidates. And Leader renew lease every `RetryPeriod` which is default is 2s instead of `LeaseDuration`. So the 10-second one couldn't happily steal the lock from the 30-second one, if latter is alive.
