### ISSUE TITLE
pull-kubernetes-federation-e2e-gce still fails

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#47672]
The cause is different from #47609

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e_federation/framework/framework.go:65
Expected error:
    <*errors.errorString | 0xc420ba7a90>: {
        s: "error creating federation default client config: invalid configuration: [context was not found for specified context: e2e-f8n-agent-pr-50-0, cluster has no server defined]",
    }
    error creating federation default client config: invalid configuration: [context was not found for specified context: e2e-f8n-agent-pr-50-0, cluster has no server defined]
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e_federation/framework/framework.go:80
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46883/pull-kubernetes-federation-e2e-gce/10827/

In its recent runs, failed three times in a row: https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/pull/46883/pull-kubernetes-federation-e2e-gce/. Though the symptoms of the other two failures are different: 
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:216
BeforeSuite on Node 1 failed
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:216
```

cc @csbell @madhusudancs could you help take a look?
cc @saad-ali @dchen1107 @kubernetes/kubernetes-release-managers

**Comment by madhusudancs** [comment]
Presubmit jobs have been super healthy recently. 

/close

@nikhiljindal FYI, since you are the buildcop this week.
