### ISSUE TITLE
protobuf maps aren't order stable, defeating the "no mutate on write" guarantee

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#47678]
Maps are in random order due to Go.

Adding `stable_marshaller_all` to gen-go makes it stable.  Possibly at risk of altering some guarantees of generation.

@kubernetes/sig-api-machinery-pr-reviews 

We have to decide whether to put this in 1.7

**Comment by smarterclayton** [comment]
@lavalamp @dchen1107 

I don't know that it is the end of the world if we put it into 1.7.1 and backport.  The impact is more writes to etcd, but not fundamentally broken.

**Comment by smarterclayton** [comment]
I've got tests running against using stable_marshaller_all on our code, haven't done perf comparisons @wojtek-t

**Comment by lavalamp** [comment]
I am OK with inclusion in 1.7.
