### ISSUE TITLE
release-1.7 serial jobs are timing out

### ISSUE THREAD

**Issue by ethernetdan** [kubernetes/kubernetes#47677]
There are 1.7 release branch serial jobs timing out:

- [ci-kubernetes-e2e-gce-serial-release-1-7](https://k8s-testgrid.appspot.com/release-1.7-blocking#gce-serial-release-1-7)
- [ci-kubernetes-e2e-gci-gce-serial-release-1-7](https://k8s-testgrid.appspot.com/release-1.7-blocking#gci-gce-serial-release-1-7)
- [ci-kubernetes-e2e-gke-serial-release-1-7](https://k8s-testgrid.appspot.com/release-1.7-blocking#gke-serial-release-1-7)
- [ci-kubernetes-e2e-gci-gke-serial-release-1-7](https://k8s-testgrid.appspot.com/release-1.7-blocking#gci-gke-serial-release-1-7)

Looking into the cause

/cc @dchen1107 @ericchiang @caesarxuchao

**Comment by spiffxp** [comment]
/close
They're not consistently failing at this time; those that flake aren't failing due to timeout https://k8s-testgrid.appspot.com/sig-release-1.7-all#Summary
