### ISSUE TITLE
Pod Important Events filterd 

### ISSUE THREAD

**Issue by dhilipkumars** [kubernetes/kubernetes#47692]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`): tip

**Environment**:
- **Cloud provider or hardware configuration**: dind
- **OS** (e.g. from /etc/os-release): ubuntu
- **Kernel** (e.g. `uname -a`):
- **Install tools**: kubeadm
- **Others**:

**What happened**:
For a simple POD spec like below, most of the events have now stopped appearing 

```
apiVersion: v1
kind: Pod
metadata:
  name: init-test
spec:
  initContainers:
  - name: first
    image: bash
    command: ["/usr/local/bin/bash", "-c", "echo started"]
  containers:
  - name: main
    image: bash
    command: [ "/usr/local/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 1; echo :`date`;done;" ]
```
Following are the events produced, after init-contianer events no event about the main container has been updated.  (Probably because both these containers have same container ref / image)
```
  FirstSeen     LastSeen        Count   From                    SubObjectPath                   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------                   --------        ------                  -------
  1m            1m              1       default-scheduler                                       Normal          Scheduled               Successfully assigned init-test to kube-node-3
  1m            1m              1       kubelet, kube-node-3                                    Normal          SuccessfulMountVolume   MountVolume.SetUp succeeded for volume "default-token-td66p"
  1m            51s             2       kubelet, kube-node-3    spec.initContainers{first}      Normal          Pulling                 pulling image "bash"
  52s           46s             2       kubelet, kube-node-3    spec.initContainers{first}      Normal          Pulled                  Successfully pulled image "bash"
  52s           46s             2       kubelet, kube-node-3    spec.initContainers{first}      Normal          Created                 Created container
  52s           46s             2       kubelet, kube-node-3    spec.initContainers{first}      Normal          Started                 Started container

```
but the container `main` had been created, started and executed by the kubelet.
```
Jun 17 04:56:02 kube-node-3 hyperkube[7929]: I0617 04:56:02.549331    7929 server.go:351] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"init-test", UID:"3c8e40e9-5319-11e7-b676-02420ac00002", APIVersion:"v1", ResourceVersion:"7800", FieldPath:"spec.containers{main}"}): type: 'Normal' reason: 'Pulling' pulling image "bash"
Jun 17 04:56:07 kube-node-3 hyperkube[7929]: I0617 04:56:07.162689    7929 kuberuntime_container.go:110] Generating ref for container main: &v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"init-test", UID:"3c8e40e9-5319-11e7-b676-02420ac00002", APIVersion:"v1", ResourceVersion:"7800", FieldPath:"spec.containers{main}"}
Jun 17 04:56:07 kube-node-3 hyperkube[7929]: I0617 04:56:07.163342    7929 kubelet_pods.go:118] container: default/init-test/main podIP: "10.192.4.3" creating hosts mount: true
Jun 17 04:56:07 kube-node-3 hyperkube[7929]: I0617 04:56:07.164032    7929 server.go:351] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"init-test", UID:"3c8e40e9-5319-11e7-b676-02420ac00002", APIVersion:"v1", ResourceVersion:"7800", FieldPath:"spec.containers{main}"}): type: 'Normal' reason: 'Pulled' Successfully pulled image "bash"
Jun 17 04:56:07 kube-node-3 hyperkube[7929]: I0617 04:56:07.260751    7929 server.go:351] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"init-test", UID:"3c8e40e9-5319-11e7-b676-02420ac00002", APIVersion:"v1", ResourceVersion:"7800", FieldPath:"spec.containers{main}"}): type: 'Normal' reason: 'Created' Created container
Jun 17 04:56:07 kube-node-3 hyperkube[7929]: I0617 04:56:07.349768    7929 server.go:351] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"init-test", UID:"3c8e40e9-5319-11e7-b676-02420ac00002", APIVersion:"v1", ResourceVersion:"7800", FieldPath:"spec.containers{main}"}): type: 'Normal' reason: 'Started' Started container
```

@derekwaynecarr  Is this expected after this [PR](https://github.com/kubernetes/kubernetes/pull/47462)? 
**What you expected to happen**:
Should be able to see events about every container.

**How to reproduce it** (as minimally and precisely as possible):
Mentioned above

**Anything else we need to know**:

**Comment by dchen1107** [comment]
@derekwaynecarr I think this is the regression introduced by https://github.com/kubernetes/kubernetes/pull/47462 for 1.7 release. Could you please take a look?

**Comment by derekwaynecarr** [comment]
there should be an event per named container.

I am out of office.  @sjenning can you take a look?

**Comment by derekwaynecarr** [comment]
We should verify that event counting is actually looking at subobject path as a unique identifier.

**Comment by dhilipkumars** [comment]
@derekwaynecarr wondering how did we miss this is in e2e / node testing ? Are there no tests for scenarios like these? 
I would love to help in adding some tests to cover this if someone could point me in suitable place to add cases for these.

**Comment by sjenning** [comment]
looking now

**Comment by sjenning** [comment]
So https://github.com/kubernetes/kubernetes/pull/47462 didn't introduce this bug, but it did expose it.

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/record/events_cache.go#L45

`getEventKey()` only keys on event fields that are common at the pod level.  Events generated by different containers in the same pod will yield identical event keys.

This wasn't a problem before as the event message contained container specific information and thus didn't produce the same event key.

**Comment by sjenning** [comment]
I think this will fix it

```diff
diff --git a/staging/src/k8s.io/client-go/tools/record/events_cache.go b/staging/src/k8s.io/client-go/tools/record/events_cache.go
index f5846ac5c4..01704b6c0d 100644
--- a/staging/src/k8s.io/client-go/tools/record/events_cache.go
+++ b/staging/src/k8s.io/client-go/tools/record/events_cache.go
@@ -49,6 +49,7 @@ func getEventKey(event *v1.Event) string {
                event.InvolvedObject.Kind,
                event.InvolvedObject.Namespace,
                event.InvolvedObject.Name,
+               event.InvolvedObject.FieldPath,
                string(event.InvolvedObject.UID),
                event.InvolvedObject.APIVersion,
                event.Type,
```
