### ISSUE TITLE
Unable to register node with API server with RBAC authorization-mode

### ISSUE THREAD

**Issue by divyenpatel** [kubernetes/kubernetes#47695]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

Yes, request for help. Refered - https://kubernetes.io/docs/admin/authorization/rbac/ to enable RBAC on API Server

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
RBAC authorization Forbidden - unable to register node VM.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
```
root@master [ ~ ]# kubectl version  
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.772+7831a5426fca83", GitCommit:"7831a5426fca83d5f9a66341b7a07a64178f8807", GitTreeState:"clean", BuildDate:"2017-06-16T05:37:06Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: vsphere
- **OS** (e.g. from /etc/os-release): photon
- **Kernel** (e.g. `uname -a`): Linux master 4.4.8-esx #1-photon SMP Tue Jun 7 08:04:49 UTC 2016 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
Started API server with RBAC enabled on the master node. used` "--authorization-mode=RBAC"` flag. 

spec from kube-apiserver.json
```
    "spec": {
        "containers": [
            {
                "command": [
                    "/hyperkube",
                    "apiserver",
                    "--address=127.0.0.1",
                    "--etcd-servers=http://127.0.0.1:2379",
                    "--cloud-provider=vsphere",
                    "--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,ResourceQuota",
                    "--service-cluster-ip-range=10.0.0.0/16",
                    "--client-ca-file=/srv/kubernetes/ca.pem",
                    "--tls-cert-file=/srv/kubernetes/apiserver.pem",
                    "--tls-private-key-file=/srv/kubernetes/apiserver-key.pem",
                    "--secure-port=443",
                    "--storage-backend=etcd2",
                    "--allow-privileged",
                    "--authorization-mode=RBAC",
                    "--v=4",
                    "--cloud-config=/etc/kubernetes/vsphere.conf"
                ],
```

Node VMs are not able to register to the Master node.

Logs from Node VM.

```
{"log":"I0617 06:33:11.702223     697 kubelet_node_status.go:80] Attempting to register node node1\n","stream":"stderr","time":"2017-06-17T06:33:11.702884548Z"}
{"log":"E0617 06:33:11.704772     697 kubelet_node_status.go:104] Unable to register node \"node1\" with API server: User \"kubernetes-node_certificate\" cannot create nodes at the cluster scope. (post nodes)\n","stream":"stderr","time":"2017-06-17T06:33:11.704902558Z"}
{"log":"E0617 06:33:11.706422     697 event.go:200] Server rejected event '\u0026v1.Event{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, ObjectMeta:v1.ObjectMeta{Name:\"node1.14c8d50d732a19e2\", GenerateName:\"\", Namespace:\"default\", SelfLink:\"\", UID:\"\", ResourceVersion:\"\", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:\"\"}, InvolvedObject:v1.ObjectReference{Kind:\"Node\", Namespace:\"\", Name:\"node1\", UID:\"node1\", APIVersion:\"\", ResourceVersion:\"\", FieldPath:\"\"}, Reason:\"NodeHasSufficientDisk\", Message:\"Node node1 status is now: NodeHasSufficientDisk\", Source:v1.EventSource{Component:\"kubelet\", Host:\"node1\"}, FirstTimestamp:v1.Time{Time:time.Time{sec:63633277929, nsec:844120034, loc:(*time.Location)(0x91f42a0)}}, LastTimestamp:v1.Time{Time:time.Time{sec:63633277991, nsec:702191698, loc:(*time.Location)(0x91f42a0)}}, Count:15, Type:\"Normal\"}': 'User \"kubernetes-node_certificate\" cannot patch events in the namespace \"default\". (patch events node1.14c8d50d732a19e2)' (will not retry!)\n","stream":"stderr","time":"2017-06-17T06:33:11.706869462Z"}
{"log":"E0617 06:33:11.707987     697 event.go:200] Server rejected event '\u0026v1.Event{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, ObjectMeta:v1.ObjectMeta{Name:\"node1.14c8d50d732a3bef\", GenerateName:\"\", Namespace:\"default\", SelfLink:\"\", UID:\"\", ResourceVersion:\"\", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:\"\"}, InvolvedObject:v1.ObjectReference{Kind:\"Node\", Namespace:\"\", Name:\"node1\", UID:\"node1\", APIVersion:\"\", ResourceVersion:\"\", FieldPath:\"\"}, Reason:\"NodeHasSufficientMemory\", Message:\"Node node1 status is now: NodeHasSufficientMemory\", Source:v1.EventSource{Component:\"kubelet\", Host:\"node1\"}, FirstTimestamp:v1.Time{Time:time.Time{sec:63633277929, nsec:844128751, loc:(*time.Location)(0x91f42a0)}}, LastTimestamp:v1.Time{Time:time.Time{sec:63633277991, nsec:702199899, loc:(*time.Location)(0x91f42a0)}}, Count:15, Type:\"Normal\"}': 'User \"kubernetes-node_certificate\" cannot patch events in the namespace \"default\". (patch events node1.14c8d50d732a3bef)' (will not retry!)\n","stream":"stderr","time":"2017-06-17T06:33:11.708452386Z"}
{"log":"E0617 06:33:11.710181     697 event.go:200] Server rejected event '\u0026v1.Event{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, ObjectMeta:v1.ObjectMeta{Name:\"node1.14c8d50d732ab476\", GenerateName:\"\", Namespace:\"default\", SelfLink:\"\", UID:\"\", ResourceVersion:\"\", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:\"\"}, InvolvedObject:v1.ObjectReference{Kind:\"Node\", Namespace:\"\", Name:\"node1\", UID:\"node1\", APIVersion:\"\", ResourceVersion:\"\", FieldPath:\"\"}, Reason:\"NodeHasNoDiskPressure\", Message:\"Node node1 status is now: NodeHasNoDiskPressure\", Source:v1.EventSource{Component:\"kubelet\", Host:\"node1\"}, FirstTimestamp:v1.Time{Time:time.Time{sec:63633277929, nsec:844159606, loc:(*time.Location)(0x91f42a0)}}, LastTimestamp:v1.Time{Time:time.Time{sec:63633277991, nsec:702208029, loc:(*time.Location)(0x91f42a0)}}, Count:15, Type:\"Normal\"}': 'User \"kubernetes-node_certificate\" cannot patch events in the namespace \"default\". (patch events node1.14c8d50d732ab476)' (will not retry!)\n","stream":"stderr","time":"2017-06-17T06:33:11.710360503Z"}
{"log":"E0617 06:33:12.143901     697 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: User \"kubernetes-node_certificate\" cannot list pods at the cluster scope. (get pods)\n","stream":"stderr","time":"2017-06-17T06:33:12.144158629Z"}
{"log":"E0617 06:33:12.145993     697 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: User \"kubernetes-node_certificate\" cannot list nodes at the cluster scope. (get nodes)\n","stream":"stderr","time":"2017-06-17T06:33:12.146180664Z"}
{"log":"E0617 06:33:12.146045     697 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: User \"kubernetes-node_certificate\" cannot list services at the cluster scope. (get services)\n","stream":"stderr","time":"2017-06-17T06:33:12.146203213Z"}
```

Logs from Master VM
```

{"log":"I0617 06:32:41.983168       1 rbac.go:114] RBAC DENY: user \"kubernetes-node_certificate\" groups [\"kubernetes-anywhere\" \"system:authenticated\"] cannot \"list\" resource \"nodes\" cluster-wide\n","stream":"stderr","time":"2017-06-17T06:32:41.983227779Z"}
{"log":"I0617 06:32:41.983208       1 authorization.go:58] Forbidden: \"/api/v1/nodes?fieldSelector=metadata.name%3Dnode1\u0026resourceVersion=0\", Reason: \"\"\n","stream":"stderr","time":"2017-06-17T06:32:41.983246584Z"}
{"log":"I0617 06:32:41.983287       1 wrap.go:42] GET /api/v1/nodes?fieldSelector=metadata.name%3Dnode1\u0026resourceVersion=0: (518.851µs) 403 [[hyperkube/v1.8.0 (linux/amd64) kubernetes/7831a54] 10.162.57.253:53774]\n","stream":"stderr","time":"2017-06-17T06:32:41.983304058Z"}
{"log":"I0617 06:32:41.983505       1 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings?resourceVersion=0: (269.326µs) 200 [[hyperkube/v1.8.0 (linux/amd64) kubernetes/7831a54] 127.0.0.1:41580]\n","stream":"stderr","time":"2017-06-17T06:32:41.983561467Z"}
{"log":"I0617 06:32:41.983754       1 rbac.go:114] RBAC DENY: user \"kubernetes-node_certificate\" groups [\"kubernetes-anywhere\" \"system:authenticated\"] cannot \"list\" resource \"pods\" cluster-wide\n","stream":"stderr","time":"2017-06-17T06:32:41.983813506Z"}
{"log":"I0617 06:32:41.983791       1 authorization.go:58] Forbidden: \"/api/v1/pods?fieldSelector=spec.nodeName%3Dnode1\u0026resourceVersion=0\", Reason: \"\"\n","stream":"stderr","time":"2017-06-17T06:32:41.983829892Z"}
```

**What you expected to happen**:
Node should be registered to the master node. Are we missing any configuration in the node VMs?

**How to reproduce it** (as minimally and precisely as possible):
Just enabled "--authorization-mode=RBAC" on the API server on master node. No configuration change on the node VMs.

**Anything else we need to know**:

cc: @SandeepPissay

**Comment by liggitt** [comment]
You have given your nodes a username of `kubernetes-node_certificate` and a group `kubernetes-anywhere`. That user and group have no inherent permissions, which is why it cannot register a node (or do anything else a kubelet wants to do).

You need to do one of the following:
* give each of your nodes its own credential with a username of `system:node:<nodeName>` and a group of `system:nodes` (preferred, since it positions you well for partitioned node permissions coming in 1.7)
* OR manually grant the `system:node` clusterrole to whatever user or group you give your nodes (for example, `kubectl create clusterrolebinding my-node-binding --clusterrole=system:node --user=kubernetes-node_certificate`)

**Comment by rushabh268** [comment]
@liggitt  I just picked up 1.7.0 and am noticing this error in the master logs:
`kubelet_node_status.go:106]` Unable to register node "ovs-11.k8s.test.com" with API server: nodes "ovs-11.k8s.test.com" is forbidden: node ovs-10.k8s.test.com cannot modify node ovs-11.k8s.test.com`

**Comment by liggitt** [comment]
It appears the credential created for ovs-10.k8s.test.com is being used on a different node (ovs-11.k8s.test.com). Giving each node the correct credential would allow it to be authorized as expected

**Comment by rushabh268** [comment]
Can you please explain how can I do that? I am new to Kubernetes so not sure how to do that.

**Comment by luxas** [comment]
@rushabh268 Let's debug that on Slack instead... It's unrelated to this issue AFAICS

**Comment by maxim28** [comment]
@rushabh268 

> I just picked up 1.7.0 and am noticing this error in the master logs:
> kubelet_node_status.go:106] Unable to register node "ovs-11.k8s.test.com" with API server: nodes "ovs-11.k8s.test.com" is forbidden: node ovs-10.k8s.test.com cannot modify node ovs-11.k8s.test.com

hi, i also met this error like you. have you fixed this error? how?

**Comment by rushabh268** [comment]
@maxim28 I had to downgrade to 1.6.6 since I couldn't get any clear solution. I am still not sure why I was hitting this error in the first place.

**Comment by maxim28** [comment]
@rushabh268 maybe it is caused by 1.7, i also use this version

**Comment by luxas** [comment]
@maxim28 @rushabh268 In `v1.7.1` you can use the `--node-name` flag to explicitely set the node name to your liking so that flag and the node API object name (can be set via `--hostname-override` on the kubelet as well) match

**Comment by rushabh268** [comment]
@luxas I am still hitting the same error with v1.7.3. The node name its printing in the above error is correct but kubernetes is just not allowing it to register. Can you tell me how to do this:

```It appears the credential created for ovs-10.k8s.test.com is being used on a different node (ovs-11.k8s.test.com). Giving each node the correct credential would allow it to be authorized as expected```

**Comment by luxas** [comment]
@rushabh268 Then you're hostname is identical on two nodes(?) or the kubelet is somehow picking up an invalid node name to use.
Basically you have two flags:
 - `--node-name` on `kubeadm init`
 - `--hostname-override` on the `kubelet`

These values _must_ match and be unique per-node in the cluster.

**Comment by dreyk** [comment]
1. You should add "Node" authorization mode to apiserver
2. Also there is the bug in kubeadm. It generate wrong certificate for kubelet.

**Comment by tcederquist** [comment]
kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Similar issue: adding support for aws after the installation, I changed:
/etc/systemd/system/kubelet.service.d/10-kubeadm.conf
adding: --cloud-provider=aws

Now its trying to attach to the cluster by the aws node name but its been previously registered by the ad realm name of the machine. Is there a clean way to update this? Do I need to remove/add the nodes to the master again?

kubelet_node_status.go:106] Unable to register node "ip-172-30-0-70.ec2.internal" with API server: nodes "ip-172-30-0-70.ec2.internal" is forbidden: node ip-172-30-0-70.aws-ermas.com cannot modify node ip-172-30-0-70.ec2.internal

I've tried the --hostname-override and it gives the same error. Here is the startup string:
/usr/bin/kubelet --cloud-provider=aws --hostname-override=ip-172-30-0-70.aws-ermas.com --kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=10.96.0.10 --cluster-domain=cluster.local --authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt --cadvisor-port=0 --cgroup-driver=systemd

Removing cloud-provider and it works as normal. Best way to deal with this? the parm does not seem to work. online docs don't address this oddity. the command line parm --hostname-override seems to be ignored.

I'm adding aws to allow a pod to mount an aws ebs. Since the nodes are all kerberos enabled, It didn't appear I couldn't use kops due to the extra realm join requirements and wasn't looking forward to rebuilding the kubernetes cluster again if its avoidable.

**Comment by dreyk** [comment]
How did you run kubeadm join command?
Try add flag --node-name=ip-172-30-0-70.ec2.internal to it.
By default kubeadm generate certificate for node=hostname()(ip-172-30-0-70) and it's wrong, it should take to account cloud-provider specific node name generator.
https://github.com/kubernetes/kubernetes/pull/44793

**Comment by tcederquist** [comment]
I've reset the nodes and rejoined with your flag added. That fixed the name registration and they start and show up in the node list as the new ec2 name. Now my aws mounts are timing out but that's probably a different ticket as i see a few out there for older versions. Also, my master is not switched to cloud-provider=aws so the api server is out of sync which could be the issue too.

Since all the old pods and services are orphaned now (reset didn't drain) and nodes have the orphaned names and so many old terminated pods stranded that I think it'll be easier to toss out the cluster and start over, builds pretty fast. I'll init with =aws this time and use your switch on the worker node joins. Looks like switching to aws after install leaves too much behind.

Anyhow thank you very much for the quick response @dreyk. It was what I needed to move forward and see a rebuild was in order but using these flags this time.

**Comment by dreyk** [comment]
You should set provider flag for master too. Also u could try compile kubeadm from pull request that I have mentioned above, it will save your time I hope.

**Comment by cyrus-mc** [comment]
I have run into this issue. Reading over this, from what I can tell my setup appears correct (obviously isn't).

For starters I have just enabled RBAC, not Node Authorizer yet. And I am running on 1.7.6.

I verified that the binding between system:node and group system:nodes is present.

```
kubectl edit clusterrolebinding system:node
 
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: 2017-11-06T05:48:12Z
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:node
  resourceVersion: "101"
  selfLink: /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system%3Anode
  uid: 13335de6-c2b6-11e7-8b4f-026c742367b0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes

```

Then on the worker node, the kubelet is presenting a certificate with the following details:

```        
Subject: C=US, ST=, L=/postalCode=, O=system:nodes, OU=Kubernetes kubelet, CN=system:node:kubelet
```

However when the kubelet starts up it gives:

```
Nov 06 19:34:08 ip-10-36-72-151.us-west-2.compute.internal kubelet-wrapper[742]: I1106 19:34:08.405754     742 kubelet_node_status.go:82] Attempting to register node ip-10-36-72-151.us-west-2.compute.internal
Nov 06 19:34:08 ip-10-36-72-151.us-west-2.compute.internal kubelet-wrapper[742]: E1106 19:34:08.409698     742 kubelet_node_status.go:106] Unable to register node "ip-10-36-72-151.us-west-2.compute.internal" with API server: nodes "ip-10-36-72-151.us-west-2.compute.internal" is forbidden: node kubelet cannot modify node ip-10-36-72-151.us-west-2.compute.internal
Nov 06 19:34:15 ip-10-36-72-151.us-west-2.compute.internal kubelet-wrapper[742]: I1106 19:34:15.410130     742 kubelet_node_st
```

**Comment by liggitt** [comment]
it looks like you have the [NodeRestriction](https://kubernetes.io/docs/admin/admission-controllers/#noderestriction) admission plugin enabled, and have configured your kubelet credentials to have a username of `system:node:kubelet`, which uses the `system:node:<nodeName>` format, but does not match the actual name of your node (`ip-10-36-72-151.us-west-2.compute.internal`)

**Comment by liggitt** [comment]
your options are:
* stop using the NodeRestriction admission plugin
* stop using `system:node:<nodeName>` format username with a `<nodeName>` segment that does not actually match the name of your node

**Comment by rushabh268** [comment]
@liggitt How do I stop the NodeRestriction plugin? I am also seeing a similar issue

**Comment by liggitt** [comment]
> @liggitt How do I stop the NodeRestriction plugin? I am also seeing a similar issue

remove it from the `--admission-control` arg to the apiserver

**Comment by cyrus-mc** [comment]
@liggitt 

That solved my problem (also responded to you on Slack). 

I wasn't aware of the NodeRestriction plugin. Thought system:node:<nodeName> was required for the node authorizer.

How does the Node authorizer relate to the NodeRestriction admission control plugin?

**Comment by liggitt** [comment]
> How does the Node authorizer relate to the NodeRestriction admission control plugin?

The authorization layer does not have access to the content of requests, only the headers and URL. As such, it can only make authorization decisions based on the name of objects when the name is in the URL.

For a node creation request, the name is in the body of the request, so admission must determine whether the request is allowed or not.

The NodeRestriction admission plugin works in tandem with the Node authorization mode to limit nodes to creating/modifying their own Node API objects and pod scheduled to themselves.
