### ISSUE TITLE
Kubernetes sources impossible to use on Windows

### ISSUE THREAD

**Issue by dlsniper** [kubernetes/kubernetes#47705]
Due to the the symlinks in the project, especially in ` vendor/ `, like this: https://github.com/kubernetes/kubernetes/tree/a57c33bd2817323806b97da5c2f848108f7403d8/vendor/k8s.io any attempt to ` go get k8s.io/kubernetes ` results in incomplete sources being downloaded, which in turn results in more frustration with the project if you are trying to use Windows for example (as it's my case).

Is there any reason why this is not working as expected out of the box?

**Comment by dlsniper** [comment]
Also the bot is terrible for a new user interaction since I have no clue whatsoever what sig this belongs to nor do I personally care what sigs are there. It's not my job to triage the issues, at best it should be the bot that does this or maintainers of the project

**Comment by k82cn** [comment]
I think you can use `client-go` directly; if `client-go` can not meet the requirement, use `godep restore` in gopath and then import related packages.

**Comment by mml** [comment]
Please use client-go.  Reopen if client-go can't meet your needs.  Thanks!  @dlsniper
