### ISSUE TITLE
endpoints not showing up for service

### ISSUE THREAD

**Issue by deitch** [kubernetes/kubernetes#47711]
**Is this a request for help?** no.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): service endpoints missing

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Kubernetes version** (use `kubectl version`): 1.6.2 

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): 

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.8.0
VERSION_ID=1353.8.0
BUILD_ID=2017-05-30-2322
PRETTY_NAME="Container Linux by CoreOS 1353.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
```

- **Kernel** (e.g. `uname -a`): `4.9.24-coreos`
- **Install tools**: manual
- **Others**:

**What happened**:

Service in `kube-system` namespace sees no endpoints that are available

**What you expected to happen**: For it to see available endpoints

**How to reproduce it** (as minimally and precisely as possible):

Not sure I can. It appeared on the latest remove/replace of worker nodes, but was fine before

**Anything else we need to know**:

I have a traefik Ingress controller defined and a service for it:

```
$ kubectl describe service traefik-ingress-controller -n kube-system
Name:			traefik-ingress-controller
Namespace:		kube-system
Labels:			app=traefik-ingress-controller
Annotations:		kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"traefik-ingress-controller"},"name":"traefik-ingress-controller","nam...
Selector:		name=traefik-ingress-lb
Type:			NodePort
IP:			10.200.177.150
Port:			http	80/TCP
NodePort:		http	30080/TCP
Endpoints:
Port:			https	443/TCP
NodePort:		https	30443/TCP
Endpoints:
Session Affinity:	None
Events:			<none>

$ kubectl -n kube-system get pod --selector=name=traefik-ingress-lb
NAME                               READY     STATUS    RESTARTS   AGE
traefik-ingress-controller-8vlms   1/1       Running   0          1h
traefik-ingress-controller-c81cq   1/1       Running   0          1h
traefik-ingress-controller-s51mq   1/1       Running   0          59m
```

Selectors match, the pods are running just fine, yet the endpoints do not show up.

I suspect if I delete the service and recreate it, it probably will pick it up, but I shouldn't have to, and am concerned it might occur again; rather actually debug it.

How can I check what kube is doing to affiliate it? How often does it check? Where?

**Comment by deitch** [comment]
The system is asking for a SIG, but it isn't clear which SIG is appropriate for this. Taking best guess, apologies if I am wrong.

/sig sig/apps
/sig sig/scheduling

**Comment by cmluciano** [comment]
@kubernetes/sig-network-misc

**Comment by freehan** [comment]
can you provide the following output?
`kubectl describe endpoint traefik-ingress-controller -n kube-system -o yaml`

**Comment by cmluciano** [comment]
@freehan Should we close this issue pending more information or keep it open for someone to test out?

**Comment by deitch** [comment]
@cmluciano we are killing and recreating clusters with some regularity over these weeks. I am happy if you want to close it since I cannot recreate it yet. Just let me reopen it if I manage to recreate and get more info.

Just tell me, please, if it does come up again, what additional data should I get? There isn't much data in the docs on how the service resolves what endpoints it should use and how to figure out why it is misbehaving when it does. Happy to take pointers.

**Comment by freehan** [comment]
Please reopen when it happens again.
 
Please record related endpoints objects and pod objects.

**Comment by githubvick** [comment]
I'm facing same issue with Nginx by trying to expose the nodePort for Nginx-ingress-controller pod


```
Name:                   nginx-ing-svc
Namespace:              default
Labels:                 name=nginx-ingress-label
Selector:               name=nginx-ingress
Type:                   NodePort
IP:                     10.254.192.134
Port:                   http    80/TCP
NodePort:               http    30000/TCP
Endpoints:              <none>
Session Affinity:       None
No events.

 kubectl get pods
NAME                     READY     STATUS    RESTARTS   AGE
coffee-rc-lsm6m          1/1       Running   0          11m
nginx-ingress-rc-g8bjl   1/1       Running   0          11m
nginx-ingress-rc-w25lj   1/1       Running   0          11m
tea-rc-qxwts             1/1       Running   0          11m


[root@kubemaster ingress-example]# kubectl -n default get pod --selector=name=nginx-ingress
No resources found.
[root@kubemaster ingress-example]# kubectl -n default get pod --selector=name=nginx-ingress-rc
No resources found.
[root@kubemaster ingress-example]# kubectl -n default get pod --selector=name=nginx
No resources found.
[root@kubemaster ingress-example]# kubectl -n default get pod --selector=app=tea
NAME           READY     STATUS    RESTARTS   AGE
tea-rc-qxwts   1/1       Running   0          5m

apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ingress-rc
  labels:
    app: nginx-ingress
spec:
  replicas: 2
  selector:
    app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      containers:
      - image: nginxdemos/nginx-ingress:0.8.1
        imagePullPolicy: Always
        name: nginx-ingress
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx-ingress-label
  name: nginx-ing-svc
spec:
  ports:
   - port: 80
     targetPort: 80
     protocol: TCP
     name: http
     nodePort: 30000
  type: NodePort
  selector:
     name: nginx-ingress
```

**Comment by MrHohn** [comment]
@githubvick  Try `kubectl get pod --selector=app=nginx-ingress`.

**Comment by githubvick** [comment]
```
kubectl get pod --selector=app=nginx-ingress
NAME                     READY     STATUS    RESTARTS   AGE
nginx-ingress-rc-mdwgn   1/1       Running   0          3m
nginx-ingress-rc-r0lbk   1/1       Running   0          3m


kubectl get endpoints nginx-ing-svc  -n default -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: 2017-07-14T03:31:51Z
  labels:
    name: nginx-ingress-label
  name: nginx-ing-svc
  namespace: default
  resourceVersion: "6180620"
  selfLink: /api/v1/namespaces/default/endpoints/nginx-ing-svc
  uid: f9cd4c29-6844-11e7-8c31-005056224e9d
subsets: []

```

**Comment by MrHohn** [comment]
@githubvick Your service is using `name=nginx-ingress` while your pods are using `app=nginx-ingress`.

**Comment by githubvick** [comment]
Sorry, didn't notice that

**Comment by aliasmee** [comment]
### Env
OS: ubuntu 16.04
kubernetes version: v1.8.4

hi, I have the same problem now. 🤦‍♂️
#### service desc
```bash
$ kc describe svc/jenkins -njenkins
Name:                     jenkins
Namespace:                jenkins
Labels:                   app=jenkins
                          chart=jenkins-0.15.1
                          component=jenkins-jenkins-master
                          heritage=Tiller
                          release=jenkins
Annotations:              <none>
Selector:                 component=jenkins-jenkins-master
Type:                     NodePort
IP:                       10.96.189.22
Port:                     http  8080/TCP
TargetPort:               8080/TCP
NodePort:                 http  30481/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

#### get pod from selector
```bash
$ kc get po -l component=jenkins-jenkins-master -njenkins
NAME                       READY     STATUS    RESTARTS   AGE
jenkins-67cf45b496-jdgq7   1/1       Running   1          134d
```

#### get endpoint
```bash
$ kc get endpoints -n jenkins
No resources found.
```

`Oddly enough, the endpoint appeared again two minutes later:` 

$ kc get endpoints -njenkins  
```bash
NAME            ENDPOINTS            AGE
jenkins         10.244.5.147:8080    2m
jenkins-agent   10.244.5.147:50000   2m
```

This situation has been going on for a long time and no solution has been found.
Help out. Thanks

**Comment by otiszv** [comment]
Same the problem, svc lost the endpoint after a few time. If deleting the pod, then the svc endpoint is show up again

**Comment by mrwonkerz** [comment]
Im having the same problem on Windows Nodes, after some hours all svc on one node loses their endpoints. Kubernetes V1.15

**Comment by freehan** [comment]
May be fixed by this? https://github.com/kubernetes/kubernetes/pull/80273

**Comment by nistiwar** [comment]
same issue for a custom helm that I created:

kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:52:43Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-04-03T04:12:37Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}


kubectl describe  service/vnfdb-ui
Name:                     vnfdb-ui
Namespace:                test-helm
Labels:                   app.kubernetes.io/instance=vnfdb
                          app.kubernetes.io/managed-by=Tiller
                          app.kubernetes.io/name=ui
                          app.kubernetes.io/version=1.0
                          helm.sh/chart=ui-0.1.0
Annotations:              <none>
Selector:                 app.kubernetes.io/instance=vnfdb,app.kubernetes.io/name=ui
Type:                     LoadBalancer
IP:                       10.105.168.158
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  31063/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>

$ kubectl get pods -l app.kubernetes.io/instance=vnfdb,app.kubernetes.io/name=ui
NAME                        READY   STATUS    RESTARTS   AGE
vnfdb-ui-548d7f496d-ttrwm   1/1     Running   0          9m

$ kubectl get endpoints vnfdb-ui
NAME       ENDPOINTS   AGE
vnfdb-ui   <none>      9m33s

$ kubectl get endpoints vnfdb-ui -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2019-08-24T21:28:58Z"
  labels:
    app.kubernetes.io/instance: vnfdb
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: ui
    app.kubernetes.io/version: "1.0"
    helm.sh/chart: ui-0.1.0
  name: vnfdb-ui
  namespace: test-helm
  resourceVersion: "4744728"
  selfLink: /api/v1/namespaces/test-helm/endpoints/vnfdb-ui
  uid: 2f204839-c6b6-11e9-a0d5-005056a42a88

Any clue what is wrong here and how can I fix it?

**Comment by nistiwar** [comment]
Got it, apparently realized that its not only the selector that has to match labels. The port names should be the same in the pod definition and services definition as well. The latter was the culprit in my case.

**Comment by webPageDev** [comment]
Same the problem.My service and pod is running. But the service do not has endpoint,and this situation lasts for 10 hours. It is OK after I restart controller manager. My last operation was to delete the service and create the service again. I have not done any other operations since then. 
 Kubernetes V1.11.5

**Comment by engelmav** [comment]
> Got it, apparently realized that its not only the selector that has to match labels. The port names should be the same in the pod definition and services definition as well. The latter was the culprit in my case.

Good catch!

**Comment by sebgl** [comment]
Happens to us once in a while: https://github.com/elastic/cloud-on-k8s/issues/2602#issuecomment-622886052.

We have a process creating a service, then a test deleting that same service, which ends up being automatically recreated. Once in a while (every ~100 test), the re-created service never gets any endpoints, even after waiting for several hours. I'm fairly confident recreating the service again fixes it, but that's not a solution.
It just happened on a GKE cluster in version `1.14.10-gke.37`, for which I don't have controller-manager logs available unfortunately. I'll try to reach GCP support, they may be able to troubleshoot more from the controller-manager logs.

**Comment by robscott** [comment]
@sebgl Thanks for the detailed bug report! I'll try to recreate this scenario with some new tests.

/assign

**Comment by robscott** [comment]
A quick follow up to let you know we haven't forgotten about this issue. From what we can tell, this is being caused by an Endpoints informer cache that can potentially be out of date when syncService() runs. Essentially syncService() would be called twice - once for the delete and once for the create event. There's a chance that when the second run of syncService() happens the Endpoints cache may not have been updated with the latest run. If that happens, syncService() will not make any changes because it sees an endpoints resource that has all the right ports and addresses set. 

@swetharepakula is working on a fix here that will mirror what we've done for the EndpointSlice controller with the `EndpointSliceTracker`. This will involve watching Endpoints changes and calling syncService() if the change has not already been accounted for by the controller.

As far as I can tell, this should be a relatively rare bug. It should only happen if the cache is out of date, the recreated Service is identical, and the Pods have not changed at all. Given the relative complexity of the fix here, I'm not sure how far we'll be able to backport this. At the very least, we're hoping to have a fix in for 1.19.

**Comment by robscott** [comment]
I think @swetharepakula's [PR](https://github.com/kubernetes/kubernetes/pull/93030) is almost ready, sorry for not catching the lifecycle close earlier.

**Comment by longzhihun** [comment]
> Got it, apparently realized that its not only the selector that has to match labels. The port names should be the same in the pod definition and services definition as well. The latter was the culprit in my case.

Dude, you saved my life.
