### ISSUE TITLE
Service registry needs to be refactored to be a) fully based on generic store and b) potentially use an Initializer for service IP assignment

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#47712]
The service registry is the only Kube REST endpoint that doesn't use generic store directly (because of the complex allocation logic).  Now that we have initializers, we potentially can move cluster IP allocation to an initializer.  However, until we refactor the REST endpoint to be based on generic.Store, it doesn't support initializers (didn't do that in 1.7).  So:

1. Should we split the IP allocation bit to an initializer?  Pro: decouples that logic from master, Con: more work, potential chicken and egg scenarios in bootstrap
2. If we do, we'll need to expose range allocation as a public API resource (controllers don't have access to etcd).  Pro: other components need range allocations, plus the upcoming ROAR work implies we need to move versions, Con: more work, may not be able to agree on range allocation API design

I realized that in openshift we also need range allocation as an API (https://github.com/openshift/origin/issues/14731).

I don't know that this *has* to be done - but this logic is one of the things that doesn't fit particularly well in the master that we have long wanted to move to a controller.  And if we move to an initializer here it opens the door for other initializers like LB and better decoupling from core kube.

@kubernetes/sig-api-machinery-misc @kubernetes/sig-network-misc

**Comment by smarterclayton** [comment]
@thockin because we hate this code

**Comment by smarterclayton** [comment]
xref #44918

**Comment by mml** [comment]
cc @mbohlool
