### ISSUE TITLE
Scheduling jobs based on file availability in distributed file system

### ISSUE THREAD

**Issue by mitar** [kubernetes/kubernetes#47722]
I have a distributed file system providing a large number of datasets. This distributed file system is attached to many Kubernetes nodes on which I plan to run Kubernetes jobs to work with datasets. Not all datasets are available on all nodes and distributed file system moves them between nodes as needed.

Now, the question I have is how could I assure that jobs needing same datasets get scheduled to the same nodes, or to nodes which have datasets already locally. It seem Kubernetes would have to be able to talk to the distributed file system to get this metadata, and also this metadata is changing as well and is not static.

Is there already anything in place to support this? I see that I could use zones for this, but the issue is that there are many datasets available and I do not know in advance a partition of datasets across nodes. It will happen during runtime to see which datasets will be needed by jobs created.

**Comment by mitar** [comment]
@kubernetes/sig-scheduling-misc
/sig sig/scheduling

**Comment by k82cn** [comment]
@kubernetes/sig-scheduling-misc

**Comment by resouer** [comment]
@mitar For now one way to achieve this is writing your own predicate/priority algorithms and register them into scheduler (a.k.a. customize scheduler). It sounds like no general method to determine what FS you are referring. see: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/

**Comment by davidopp** [comment]
Thanks for your interest in Kubernetes. Please use StackOverflow or the kubernetes-users mailing lists for these kinds of questions. (You will get many more people reading them there than filing an issue.)

https://stackoverflow.com/questions/tagged/kubernetes
https://groups.google.com/forum/#!forum/kubernetes-users
