### ISSUE TITLE
Service exposed as nodeport is accessible using 'External IP' of another service(type=LoadBalancer)

### ISSUE THREAD

**Issue by spradeepv** [kubernetes/kubernetes#47723]
**Is this a request for help?** No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): Service, External IP

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Custom
- **OS** (e.g. from /etc/os-release): 
```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

```
- **Kernel** (e.g. `uname -a`):
`Linux kube-master-node 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

- **Install tools**: kubeadm
- **Others**: -
**What happened**:
I have a 3-node cluster formed using kubeadm. 

- Create a service of type=LoadBalancer. We have our own custom plugin to handle type=LoadBalancer which gives the external IP, say **service-1**

- Create a service with type=NodePort (None of the minions have external IP), say **service-2**

- I am able to access **service-2** using **service-1's** external IP and nodeport of **service-2** 

**What you expected to happen**:
Service which is exposed via type=LoadBalancer should not allow access to other services

**How to reproduce it** (as minimally and precisely as possible):
- Create a service of type=LoadBalancer. We have our own custom plugin to handle type=LoadBalancer which gives the external IP, say **service-1**

- Create a service with type=NodePort (None of the minions have external IP), say **service-2**

- I am able to access **service-2** using **service-1's** external IP and nodeport of **service-2**

**Anything else we need to know**:

**Comment by spradeepv** [comment]
@kubernetes/sig-Network-misc
/sig area/kube-proxy

**Comment by cmluciano** [comment]
/assign

Is the LB configured to select pods with the same label selector that the nodePorts do?

**Comment by cmluciano** [comment]
@kubernetes/sig-network-misc

**Comment by spradeepv** [comment]
@cmluciano our external IP is like service IP configured on one of the minions and it has DNAT rules added in all the minions. I guess this is similar to #22952.

**Comment by freehan** [comment]
hmmmmmm....Is this another iptables rule conflict case?

Rules to capture request for NodePort is happening earlier than rules for externalIP.

**Comment by spradeepv** [comment]
priority/important-soon

**Comment by spradeepv** [comment]
kind/bug

**Comment by cmluciano** [comment]
@freehan 

I think that might be the case https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L216-L217

**Comment by cmluciano** [comment]
Can you attach your `iptables-save` @spradeepv

**Comment by feiskyer** [comment]
>  We have our own custom plugin to handle type=LoadBalancer which gives the external IP.

Maybe explain how this works? e.g. whether the service's externalIP is also set on host interfaces. If so, then I think it is an expected behavior because NodePort is serving on all IPs of the host.

**Comment by dims** [comment]
@spradeepv @caseydavenport - How badly do we need this in 1.8? given that there is not PR yet for this issue? Can we please move this off of 1.8?

**Comment by spradeepv** [comment]
Sorry for the late reply. @bowei may I know how to create a e2e test reduction?

**Comment by spradeepv** [comment]
I was also thinking of a solution, where we can add a rule for each service which will restrict access to ports other than the service port and nodeport.

**Comment by spradeepv** [comment]
Something like this:
Initialize only once:
	sudo iptables -t nat -N KUBE-MARK-DROP-SVC
	sudo iptables -t nat -A KUBE-MARK-DROP-SVC -j MARK --set-xmark 0x8000/0x8000
	sudo iptables -t nat -A KUBE-MARK-DROP-SVC -j ACCEPT

Upon creation of each service:
   sudo iptables -t nat -N <SERVICE-NAME_NAMESPACE>
   sudo iptables -t nat -I PREROUTING --destination <ExtIP> -j <SERVICE-NAME_NAMESPACE>
   sudo iptables -t nat -A <SERVICE-NAME_NAMESPACE> -p <PROTOCOL> -m multiport --dports <SER-PORT,NODE-PORT> -j RETURN
   sudo iptables -t nat -A <SERVICE-NAME> -j KUBE-MARK-DROP-SVC
