### ISSUE TITLE
kube-proxy randomly returns 504 gateway timeouts (without actually waiting)

### ISSUE THREAD

**Issue by ghost** [kubernetes/kubernetes#47725]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): Yes and I have

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kube-proxy, gateway timeout, gateway, 504

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 
```json
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-22T10:12:27Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21
- **Kernel** (e.g. `uname -a`):
- **Install tools**: kops

**What happened**: I have setup a service with LoadBalancer (AWS ELB). The ELB sees all nodes as available. When trying to access that service, I randomly get 504 gateway timeouts that appear instantly, without actually waiting for a timeout. Restarting the kube-proxy does not seem to help at all. Refreshing/re-sending the request will solve it. It seems to happen every few requests as if on a round robin rotation.

**What you expected to happen**: kube-proxy should be able to handle such things.

**How to reproduce it** (as minimally and precisely as possible): Not sure here. Try running a kops cluster with an ELB service and a uWSGI web server as a backend

**Anything else we need to know**: We are using uWSGI as a server inside the containers.

**Comment by ami-fairfly** [comment]
@kubernetes/sig-network-misc

**Comment by cmluciano** [comment]
@kubernetes/sig-aws-misc

**Comment by bowei** [comment]
@ami-fairfly how were you able to narrow down the problem to the kube-proxy component? It sounds like the 504 is being generated from the ELB in this case.

**Comment by ami-fairfly** [comment]
@bowei We have done a few things to narrow down the problem:

- Tried switching the ELB to an out-of-cluster instance and it worked fine
- Tried removing a few relatively busy kubernetes instances from the ELB and it reduced the issue.
- Refreshing the browser a few times also helped reduce the amount of 504s.

I have to say that we tried upgrading to k8s 1.6 and so far the issue seems to have disappeared, although I have not seen anything related in the release notes.

**Comment by cmluciano** [comment]
@ami-fairfly do the problems in this issue https://github.com/kubernetes/kubernetes/issues/45126 sound familiar?

**Comment by nbutton23** [comment]
One thing to keep in mind with ELBs is that they have HTTP keep alive (called idle timeout) on by default, and its set to 60seconds. That needs to be 1 second less than your apps keep alive. This was the cause of 504s for several of our apps.  

http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/config-idle-timeout.html

To configure the ELB idle time-out you can set this annotation of your service. 
`// ServiceAnnotationLoadBalancerConnectionIdleTimeout is the annotation used
// on the service to specify the idle connection timeout.
const ServiceAnnotationLoadBalancerConnectionIdleTimeout = "service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout"
`

**Comment by cmluciano** [comment]
Interesting, maybe we need to add this to the docs on kops

**Comment by ami-fairfly** [comment]
@cmluciano That problem does not sound related.

@nbutton23 thanks, however since upgrading to Kube 1.6 we did not see this issue again. If this happens again however I will be sure to check the idle timeout.

Closing this for now as it seems gone in 1.6

**Comment by ami-fairfly** [comment]
Aaand we're back. This time on 1.6.7.

Some nodes are just causing 504, and I can't even tell which nodes.

Could really use some help here.

@nbutton23  - tried to raise the timeout, did not help.
@cmluciano any ideas?

**Comment by RyPeck** [comment]
@ami-fairfly Any chance - do you happen to have a high number of unhealthy instances in the target ELB?

**Comment by ami-fairfly** [comment]
@RyPeck It is always zero.

We do have nodes that are under high load (~80-90% CPU) but I would expect things to still work.

**Comment by ami-fairfly** [comment]
We're now on 1.7 and it is still happening. Less, but still.

**Comment by RyPeck** [comment]
@ami-fairfly this was already mentioned - but is the Idle Timeout on the ELB less than the Keep Alive for your application?

**Comment by ami-fairfly** [comment]
@RyPeck Should be. I also tried increasing it but to no avail.

What do you mean by KeepAlive? The ELB health check?

**Comment by RyPeck** [comment]
@ami-fairfly referring to the same documentation @nbutton23 referenced. Specifically the HTTP Keep Alive for your application should be 1 second greater than the ELB Idle Timeout.

http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/ts-elb-error-message.html#ts-elb-errorcodes-http504

In [NGINX](http://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_timeout) - this is set to 75 seconds by default. So this works with the AWS ELB Idle Timeout.

**Comment by ami-fairfly** [comment]
@RyPeck Looks much better, thanks!

**Comment by ami-fairfly** [comment]
@RyPeck aaand we're back to 504 :/

**Comment by amigold** [comment]
taking over from this accoutn

**Comment by RyPeck** [comment]
@amigold same symptoms as before, instant `504`? Sure you don't have a pod running the old uWSGI settings?

**Comment by amigold** [comment]
@RyPeck looks like after playing around some more with uWSGI it is now much better.
Lets close this anyway as I guess we proved its not kubernetes/kops related.

Thanks for the help!

**Comment by ikornaselur** [comment]
> looks like after playing around some more with uWSGI it is now much better.

Just curious, what else did you try with the uWSGI config?

**Comment by cmluciano** [comment]
/close 

issue with uWSGI

**Comment by amigold** [comment]
@ikornaselur I was accidentally using `http-socket` instead of `http` (for 3 years now). Also added the `harakiri` setting and adjusted threads/processes a bit.
