### ISSUE TITLE
kubectl rollout history is not record the update time

### ISSUE THREAD

**Issue by yan234280533** [kubernetes/kubernetes#47727]
If this is a FEATURE REQUEST, please:
  - Describe *in detail* the feature/behavior/change you'd like to see.

kubectl rollout history is not record the update time of the update

when I get the information of the history, it like this: 

root@VM-0-10-ubuntu:/home/ubuntu# kubectl rollout history deployment/nginx  --revision=5
deployments "nginx" with revision #5
  Labels:	pod-template-hash=2343239180
	qcloud-app=nginx
  Containers:
   nginx:
    Image:	nginx:stable
    Port:	
    Limits:
      cpu:	1
      memory:	128Mi
    Requests:
      cpu:	200m
      memory:	128Mi
    Volume Mounts:	<none>
    Environment Variables:
      TEST:	1
  No volumes.

However it not record the time when it update, So I cannot not when I do the update.

**Comment by xingzhou** [comment]
I'd like to take a look at this

**Comment by yan234280533** [comment]
@xingzhou  How about this,  is it  not have record the update time ?

**Comment by xingzhou** [comment]
@yan234280533, sorry that just finished one other ticket at hand and I'm starting to work on this ticket now. I haven't digged into the code too much, but IMO, the rollout of a deployment will create new `replicaset` object which will record the creation time. If this is correct, we can use the creation time to show the update time and as a result, this may just a change of `kubectl`'s display. I'll confirm this with the code and submit a patch then, thanks

**Comment by kargakis** [comment]
> @yan234280533, sorry that just finished one other ticket at hand and I'm starting to work on this ticket now. I haven't digged into the code too much, but IMO, the rollout of a deployment will create new replicaset object which will record the creation time. If this is correct, we can use the creation time to show the update time and as a result, this may just a change of kubectl's display. I'll confirm this with the code and submit a patch then, thanks

The creation time of a RS does not always map to the time the rollout started. For example, when we rollback, we reuse a previously created RS.

**Comment by xingzhou** [comment]
yes, @kargakis, I tried the rollback, it indeed reused the old object, just added one new revision history showing the original revision version number. So how about we adding a new annotation here in the RS to record the exact update time?

**Comment by kargakis** [comment]
@kubernetes/sig-apps-feature-requests

**Comment by xingzhou** [comment]
Added a new annotation for recording revision time of deployment. Now carry on working the revision time for DaemonSet

**Comment by xingzhou** [comment]
After some investigation in the code, found out that or `DaemonSet`, it's now using `ControllerRevision` object to record the revision information. So here I can see two solutions to record revision time for `DaemonSet`:
• Add a new attribute named `RevisionTime` to `ControllerRevision` object. Considering `ControllerRevision` is also used for `StatefulSet`, so `StatefulSet` can also record the time in the future
• Add a new annotation to `ControllerRevision` like what is proposed in PR #48412. By this way, only require minimum changes in the code to record revision time
The above two solutions are for discussion, @kargakis and @fabianofranz, welcome your comments!

**Comment by smarterclayton** [comment]
Why isn't revision time equal to the creation timestamp of the revision?
Why do we need two times?  We don't have accurate modification timestamps
of any DaemonSet/StatefulSet anyway.

**Comment by xingzhou** [comment]
@smarterclayton, IIUC, when we use rollout undo to rollback a DaemonSet, it will reuse the old ControllerRevision object and update the revision number, so there is no field at present to record the update time, like deployment revision, I'm thinking add a field or annotation to record this info.

**Comment by janetkuo** [comment]
> there is no field at present to record the update time, like deployment revision

Do we have such annotation in deployment?

**Comment by xingzhou** [comment]
@janetkuo, no, at present, only a revision annotation in ReplicaSet.
