### ISSUE TITLE
APIserver should have a metric for response size

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#47728]
Currently apiserver exposes metrics only for request counts and request latencies (labeled by verb, resource, etc..).
However we need more information about why the latencies might be high/low and one really important metric for it is the size of response body (specifically for GET and LIST calls).
This will also help us understand https://github.com/kubernetes/kubernetes/issues/44701 better and is relevant to https://github.com/kubernetes/kubernetes/issues/47419#issuecomment-308114098

cc @kubernetes/sig-api-machinery-feature-requests @kubernetes/sig-scalability-misc @gmarek @wojtek-t

**Comment by shyamjvs** [comment]
@smarterclayton @lavalamp Sounds reasonable?

**Comment by smarterclayton** [comment]
As long as we keep the cardinality under control.  

Also, we need to make apiserver_request_count differentiate between LIST namespace and LIST all, which I don't think it's doing now.  That's the one i'm mostly concerned about, although in the future we might have a middle ground.

**Comment by shyamjvs** [comment]
The cardinality shouldn't be too much given that we'd have one metric for <verb, resource> pair. Besides it'd be much less than request_count for example (which is also labeled by client and status code, that we probably don't need for our response_size metric).

> Also, we need to make apiserver_request_count differentiate between LIST namespace and LIST all, which I don't think it's doing now.
Yes we don't differentiate them currently. But what's the reason you have in your mind for this? Because listing in a namespace might end up being as good as listing in all if we have one huge namespace.
Maybe the no. of objects in a LIST response instead (but I'm not too inclined towards this as IIUC it means deserializing the response)?

**Comment by smarterclayton** [comment]
Mostly because listing things in a namespace is a very different action
than listing things across all.  If you have one huge namespace, you'll be
able to tell because latency of "list all" will be same as "list
namespace", and because you might want counts of how many things are
listing all (which is generally considered bad) vs listing namespace (which
is generally considered safe).

**Comment by shyamjvs** [comment]
Thanks for the explanation. That sgtm.
So do we want to just classify them as namespaced or not, or label the metrics by the namespace (this might hurt if there are many namespaces)?
