### ISSUE TITLE
local-up-cluster.sh failed with error: unable to recognize "kubedns-deployment.yaml"

### ISSUE THREAD

**Issue by mtanino** [kubernetes/kubernetes#47739]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): local-up-cluster.sh 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
$ kubectl.sh version
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.827+2d023ab085c43b-dirty", GitCommit:"2d023ab085c43b36ecbe56b250f00e7e70357fa5", GitTreeState:"dirty", BuildDate:"2017-06-19T16:44:31Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.827+2d023ab085c43b-dirty", GitCommit:"2d023ab085c43b36ecbe56b250f00e7e70357fa5", GitTreeState:"dirty", BuildDate:"2017-06-19T16:44:31Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: KVM
- **OS** (e.g. from /etc/os-release): fedora 25
- **Kernel** (e.g. `uname -a`): uname -a
Linux k8sbuild-master 4.11.3-200.fc25.x86_64 #1 SMP Thu May 25 19:03:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
local-up-cluster.sh fails to create kube-dns and StorageClass.
```
Waiting for apiserver to come up
+++ [0619 12:46:33] On try 5, apiserver: : 
Cluster "local-up-cluster" set.
use 'kubectl --kubeconfig=/var/run/kubernetes/admin-kube-aggregator.kubeconfig' to use the aggregated API server
Creating kube-system namespace
clusterrolebinding "system:kube-dns" created
serviceaccount "kube-dns" created
configmap "kube-dns" created
error: unable to recognize "kubedns-deployment.yaml": no matches for extensions/, Kind=Deployment
service "kube-dns" created
Kube-dns deployment and service successfully deployed.
kubelet ( 14184 ) is running.
Create default storage class for 
error: unable to recognize "/opt/kubernetes/cluster/addons/storage-class/local/default.yaml": no matches for storage.k8s.io/, Kind=StorageClass
Local Kubernetes cluster is running. Press Ctrl-C to shut it down.
```

**What you expected to happen**:
local-up-cluster.sh is successfully executed.

**How to reproduce it** (as minimally and precisely as possible):
1) Clone kubernetes from master branch
2) run local-up-cluster.sh
    $ export ENABLE_HOSTPATH_PROVISIONER="true"; ./hack/local-up-cluster.sh

If you already have kubernetes , try this
1) make clean_meta
2) run local-up-cluster.sh
    $ export ENABLE_HOSTPATH_PROVISIONER="true"; ./hack/local-up-cluster.sh

**Anything else we need to know**:
I think this problem is timing issue because sleeping 3 seconds before start_kubedns can avoid this problem.

```
--- a/hack/local-up-cluster.sh
+++ b/hack/local-up-cluster.sh
@@ -883,6 +883,7 @@ if [[ "${START_MODE}" != "kubeletonly" ]]; then
   start_apiserver
   start_controller_manager
   start_kubeproxy
+  sleep 3
   start_kubedns
   start_kubedashboard
 fi
```

**Comment by qiujian16** [comment]
I met the same issue sometimes...maybe we should add a function to check if all api-versions are up
