### ISSUE TITLE
Release 1.7 block umbrella: kubernetes/kubectl (size: 0)

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#47747]
1.7 release blocking issues for [kubernetes/kubectl](https://github.com/kubernetes/kubectl)

- [x] kubernetes/kubernetes#47571 `kubectl did not print readable message of statefulset PVC's capacity.`
- [x] #43464 `Kubectl upgrade tests failing 1.6 -> 1.7`

**Comment by mengqiy** [comment]
#47448: PodSecurityContext API compatibility broken between 1.6 and 1.7

**Comment by dchen1107** [comment]
All required work for v1.7 are done, and move this to 1.8 milestone.
