### ISSUE TITLE
No examples for CR in client-go

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#47743]
The [`README.md`](https://github.com/kubernetes/apiextensions-apiserver/tree/master/examples/client-go) says that there are examples to show "how to create/get/list instances of your new resource type". 

However, none of the examples show how to get a CustomResource (the instance) but only show how to use the CustomResourceDefinition.

@ahmetb Since you are working on examples, do you want to take this? If not, I'd be happy to work on it!

/cc @sttts

**Comment by ahmetb** [comment]
@nikhita The readme was created before [`examples/custom-resource` directory](https://github.com/kubernetes/client-go/tree/master/examples/custom-resources) was added. There's pointers to it from the TPR example. Would you mind updating the readme?

I don't have bandwidth in the short term to contribute a new example in this area. If you need help developing it, I am happy to provide but I am no expert.

**Comment by ahmetb** [comment]
Sorry, I thought we are talking about https://github.com/kubernetes/client-go/blob/master/examples/README.md.

**Comment by nikhita** [comment]
Oh now that you mention it, I think adding a link to the CustomResources example under `Advanced Concepts` would be a good idea. What do you think?

**Comment by nikhita** [comment]
Ah, gotcha. You meant to do this in the first place. :)
Will do that!
