### ISSUE TITLE
1.6 -1.7 persistent-volume-upgrade 

### ISSUE THREAD

**Issue by monopole** [kubernetes/kubernetes#47759]
[jenkins](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1-6-1-7-upgrade-master/61#persistent-volume-upgrade)

[history](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gce-upgrade-master&include-filter-by-regex=%5EOverall%24%7Cpersistent%5C-volume%5C-upgrade)

```
Expected error:
    <*errors.errorString | 0xc420b76f00>: {
        s: "expected pod \"pvc-tester-2088x\" success: gave up waiting for pod 'pvc-tester-2088x' to be 'success or failure' after 5m0s",
    }
    expected pod "pvc-tester-2088x" success: gave up waiting for pod 'pvc-tester-2088x' to be 'success or failure' after 5m0s
not to have occurred

k8s.io/kubernetes/test/e2e/framework.(*Framework).testContainerOutputMatcher(0xc4207009a0, 0x3799ae8, 0xf, 0xc420ab6c00, 0x0, 0xc420039e98, 0x1, 0x1, 0x38b3010)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2224 +0x240
k8s.io/kubernetes/test/e2e/framework.(*Framework).TestContainerOutput(0xc4207009a0, 0x3799ae8, 0xf, 0xc420ab6c00, 0x0, 0xc420039e98, 0x1, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:400 +0x8a
k8s.io/kubernetes/test/e2e/upgrades.(*PersistentVolumeUpgradeTest).testPod(0x568b4c0, 0xc4207009a0, 0x37e622c, 0x20)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/upgrades/persistent_volumes.go:113 +0xfc
k8s.io/kubernetes/test/e2e/upgrades.(*PersistentVolumeUpgradeTest).Test(0x568b4c0, 0xc4207009a0, 0xc4214f0000, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/upgrades/persistent_volumes.go:95 +0xa5
k8s.io/kubernetes/test/e2e.(*chaosMonkeyAdapter).Test(0xc4215f8340, 0xc4212e63c0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:205 +0x1ed
k8s.io/kubernetes/test/e2e.(*chaosMonkeyAdapter).Test-fm(0xc4212e63c0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:270 +0x34
k8s.io/kubernetes/test/e2e/chaosmonkey.(*chaosmonkey).Do.func1(0xc4212e63c0, 0xc4212de110)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/chaosmonkey/chaosmonkey.go:89 +0x76
created by k8s.io/kubernetes/test/e2e/chaosmonkey.(*chaosmonkey).Do
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/chaosmonkey/chaosmonkey.go:90 +0x1c7
```

/sig storage
/assign @msau42

**Comment by msau42** [comment]
The volumes are not able to attach because the controller manager (which runs the attach/detach controlller) keeps erroring and cannot come up.

I think this is the error:
I0619 17:55:00.511328       5 range_allocator.go:94] Node bootstrap-e2e-master has no CIDR, ignoring
I0619 17:55:00.511337       5 range_allocator.go:98] Node bootstrap-e2e-minion-group-5gkp has CIDR 10.180.3.0/24, occupying it in CIDR map
E0619 17:55:00.511355       5 controllermanager.go:432] Error starting "node"
F0619 17:55:00.511361       5 controllermanager.go:181] error starting controllers: failed to mark cidr as occupied: cidr 10.180.3.0/24 is out the range of cluster cidr 10.100.0.0/14

/sig network

**Comment by monopole** [comment]
/assign @bowei 

Bowei, can you delegate please?

**Comment by bowei** [comment]
Has this been resolved by https://github.com/kubernetes/kubernetes/issues/47379? It looks to be the same error as the other issue.

**Comment by msau42** [comment]
It looks like latest run of the test has passed.

**Comment by bowei** [comment]
close?

**Comment by dchen1107** [comment]
I am closing this as the dup of https://github.com/kubernetes/kubernetes/issues/47379#issuecomment-309912047

**Comment by monopole** [comment]
yay!  hope its not another flake.
