### ISSUE TITLE
test failure: Networking should provide unchanging, static URL paths for kubernetes api services

### ISSUE THREAD

**Issue by monopole** [kubernetes/kubernetes#47755]
This is a 1-6 to 1-7 upgrade failure.
/sig network
/assign @bowei 

[jenkins link](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-6-cvm-1-7-upgrade-cluster/28#k8sio-networking-should-provide-unchanging-static-url-paths-for-kubernetes-api-services)
[history](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-upgrade-cluster&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Networking%5C%20should%5C%20provide%5C%20unchanging%5C%2C%5C%20static%5C%20URL%5C%20paths%5C%20for%5C%20kubernetes%5C%20api%5C%20services)

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/networking.go:74
Jun 19 12:37:12.824: Failed: the server could not find the requested resource
Body: {
  "paths": [
    "/apis",
    "/apis/",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/metrics",
    "/version"
  ]
}
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/networking.go:71
```

**Comment by caesarxuchao** [comment]
it's https://github.com/kubernetes/kubernetes/pull/47478

**Comment by pwittrock** [comment]
@caesarxuchao Is this fixed then?

**Comment by caesarxuchao** [comment]
need to cherry-pick 47478 into 1.6 branch. i will do it.

**Comment by pwittrock** [comment]
gr8 thanks

**Comment by dchen1107** [comment]
Wait, are we sure cherry-picking #47478 is the right fix. In #47478, it says GKE will not enable the /logs endpoint in 1.7, but are we sure about GKE 1.6? 1.5?

**Comment by dchen1107** [comment]
Taking another look at #47478, it only changed the test to reflect the new change. Nothing will affect the real production.

**Comment by monopole** [comment]
Green as Opheodrys vernalis.  Thanks!
