### ISSUE TITLE
*-upgrade tests failing 1.6 -> 1.7

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#47754]
https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-upgrade-cluster&sort-by-failures=

**Comment by monopole** [comment]
I think this is a dupe of #47379, because the new red at 06-18 (run 27) has the common element of _getsockopt: connection refused_

(the other red is filed as  #43464, #47376, #47374, #47378, #47755)
