### ISSUE TITLE
Increase unit test coverage for GPU support

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#47750]
Code in https://github.com/kubernetes/kubernetes/tree/master/pkg/kubelet/gpu has non trivial logic  and isn't well tested. This has resulted in a couple of bugs. Increasing unit test coverage will relieve burden on e2e testing.

@jiayingz wanna take a stab at this?

**Comment by abdasgupta** [comment]
Hi @vishh , currently I do have some bandwidth to work on this. Can you point me to some of the bugs??

**Comment by vishh** [comment]
@abdasgupta @jiayingz is already working on this issue. you might want to co-ordinate with her.

Is there a specific area you are interested in contributing?

**Comment by abdasgupta** [comment]
I am mainly interested in contributing for gpu, node, scheduler. Please send me a note if there is anything that I can contribute on these area.

**Comment by mindprince** [comment]
/close

This part of the code is deprecated and scheduled for removal in 1.11
