### ISSUE TITLE
SchedulerPriorities - swarm of 1.6 -> 1.7 upgrade failures

### ISSUE THREAD

**Issue by monopole** [kubernetes/kubernetes#47769]
## [Triage dashboard](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=1-5-.*-1-7.*upgrade&test=SchedulerPriorities)

Includes links to these:
* SchedulerPriorities [Serial] Pods should be scheduled to low resource use rate node
* SchedulerPriorities [Serial] Pod should be prefer scheduled to node that satisify the NodeAffinity
* SchedulerPriorities [Serial] [Pod should avoid to schedule to node that have avoidPod annotation](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-gci-1-7-upgrade-cluster-new/18#k8sio-schedulerpriorities-serial-pod-should-avoid-to-schedule-to-node-that-have-avoidpod-annotation)

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:85
Expected error:
    <*errors.errorString | 0xc420c35060>: {
        s: "1 / 15 pods in namespace \"kube-system\" are NOT in RUNNING and READY state in 5m0s\nPOD                                 NODE                                         PHASE   GRACE CONDITIONS\nkube-dns-autoscaler-300991650-0bb9q gke-bootstrap-e2e-default-pool-55863395-k993 Pending       [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-06-19 17:03:21 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-06-19 17:03:21 +0000 UTC ContainersNotReady containers with unready status: [autoscaler]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-06-19 17:03:21 +0000 UTC  }]\n",
    }
    1 / 15 pods in namespace "kube-system" are NOT in RUNNING and READY state in 5m0s
    POD                                 NODE                                         PHASE   GRACE CONDITIONS
    kube-dns-autoscaler-300991650-0bb9q gke-bootstrap-e2e-default-pool-55863395-k993 Pending       [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-06-19 17:03:21 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-06-19 17:03:21 +0000 UTC ContainersNotReady containers with unready status: [autoscaler]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-06-19 17:03:21 +0000 UTC  }]
    
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:84
```

/sig scheduling
/assign @davidopp 

See also #47767

**Comment by dchen1107** [comment]
@kubernetes/sig-scheduling-misc

**Comment by dchen1107** [comment]
@davidopp we need to triage this issue to decide if there are release blocking or not.

**Comment by timothysc** [comment]
@k82cn This one would be better if you have cycles.

**Comment by k82cn** [comment]
sure, let me try this :).

**Comment by bsalamat** [comment]
Among the tests in the first post of this issue, "Pods should be scheduled to low resource use rate node" is failing a lot. As I had mentioned in a different issue, I tried reproducing this locally, but I was not able to. So, my guess is that some configuration/condition/state in our test clusters cause the test to fail.

The "least requested" priority function is tested extensively in our unit tests: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/priorities/least_requested_test.go
So, given the issues caused by the test and dependency of scheduling decisions on the config and state of the cluster, I think we can go ahead and delete the e2e test.

**Comment by monopole** [comment]
Thanks @bsalamat !  

Would it help if i broke out the other two failures into separate issues?

**Comment by bsalamat** [comment]
@monopole Please note that the other two are not failing that frequently. So, I don't see those as  blockers for 1.7: https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-cvm-1-5-cvm-1-7-upgrade-cluster-new

That said, as @dchen1107 has mentioned in #47883, the other e2e scheduler priority tests should probably be removed eventually. Our e2e test framework is not deterministic enough to run these tests, but given that the other two are passing at a reasonable rate, I would wait until we discuss their removal in our next sig-scheduling meeting.

**Comment by monopole** [comment]
OK, we're going to ignore 1.5->1.7.   Please focus now only on the 1.6 -> 1.7 tests.

PTAL at this [1.6->1.7 triage link](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=1-6-.*-1-7.*upgrade&test=SchedulerPriorities).

If the view is these test failures aren't "real" failures, but are artifacts of race-conditions in cluster testing, then please delete the tests (since they give us no signal) and devote time to eliminating those race conditions so we can get reliable test coverage.

**Comment by bsalamat** [comment]
`[k8s.io] SchedulerPriorities [Serial] Pods created by ReplicationController should spread to different node` is also similar to [SchedulerPriorities [Serial] Pods should be scheduled to low resource use rate node](https://github.com/kubernetes/kubernetes/issues/47381). It is failing a lot in our e2e tests, but have been running the test in my own GCE cluster and has been passing for 18 times so far. I think this one should be deleted as well for similar reasons.
