### ISSUE TITLE
1.5 to 1.6 upgrade failure: PrivilegedPod should test privileged pod

### ISSUE THREAD

**Issue by monopole** [kubernetes/kubernetes#47768]
[gubernator](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-gci-1-7-upgrade-cluster/18#k8sio-privilegedpod-should-test-privileged-pod)
[history](https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-cvm-1-5-gci-1-7-upgrade-cluster&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20PrivilegedPod%5C%20should%5C%20test%5C%20privileged%5C%20pod)

Failed on 6-19

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/privileged.go:65
Expected error:
    <*errors.errorString | 0xc4203a51d0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/pods.go:67
```

/sig apps
/assign @enisoc 

@enisoc Please reassign - not sure where to put this.

**Comment by bowei** [comment]
Nothing obvious jumps out at me, but it looks like the failure was part of a larger cluster of failures. Maybe something went wrong in the cluster setup?

**Comment by enisoc** [comment]
@bowei So as far as you know, there's no reason the "hostexec pod" should have a harder time scheduling than any other pod? If so, that does point towards a cluster failure unrelated to this specific test, since it would mean we are just unable to schedule pods in general.

**Comment by bowei** [comment]
@enisoc Yes, that is what I understand.

**Comment by enisoc** [comment]
This does seem to be a node problem unrelated to this particular test. There are just no nodes available for scheduling. When the test fails, it prints out node info for each node, and they are all empty like this:

```
I0619 15:37:04.831] Logging node info for node gke-bootstrap-e2e-default-pool-d0a689fb-brxd
I0619 15:37:04.852] Jun 19 15:37:04.852: INFO: Node Info: &TypeMeta{Kind:,APIVersion:,}
```

Also, the test appears to have gone green again in [subsequent runs](https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-cvm-1-5-gci-1-7-upgrade-cluster&width=20&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20PrivilegedPod%5C%20should%5C%20test%5C%20privileged%5C%20pod).

**Comment by monopole** [comment]
OK, five greens in a row. Closing.
