### ISSUE TITLE
 Daemon set [Serial] should run and stop complex daemon with node affinity (1.6->1.7)

### ISSUE THREAD

**Issue by monopole** [kubernetes/kubernetes#47765]
[gubernator](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-cvm-1-7-upgrade-cluster/18#k8sio-daemon-set-serial-should-run-and-stop-complex-daemon-with-node-affinity)
[history](https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-cvm-1-5-cvm-1-7-upgrade-cluster&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Daemon%5C%20set%5C%20%5C%5BSerial%5C%5D%5C%20should%5C%20run%5C%20and%5C%20stop%5C%20complex%5C%20daemon%5C%20with%5C%20node%5C%20affinity)

Started failing on 6-16
```
go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_set.go:272
error waiting for daemon pods to be running on no nodes
Expected error:
    <*errors.errorString | 0xc4203cb800>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_set.go:249
```

Same error reported in https://github.com/kubernetes/kubernetes/issues/46185

/sig node
/assign @mtaufen

**Comment by mtaufen** [comment]
Interesting, it's failing on the 1.5-1.7 upgrade test but passing in the 1.6-1.7 upgrade, serial 1.5, and serial 1.7 tests.

[Upgrade history](https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-cvm-1-5-cvm-1-7-upgrade-cluster&include-filter-by-regex=Daemon%20set)
[1.5 history](https://k8s-testgrid.appspot.com/release-1.5-all#gke-serial-1.5&include-filter-by-regex=Daemon%20set)
[1.7 history](https://k8s-testgrid.appspot.com/release-1.7-all#gke-serial-release-1-7&include-filter-by-regex=Daemon%20set)

**Comment by mtaufen** [comment]
Test is also failing in the [gce 1.5-1.6 upgrade test](https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gce-1.5-1.6-upgrade-cluster&include-filter-by-regex=Daemon%20set)

This failure is most likely because node affinity went from being an annotation in 1.5 to an api field in 1.6. @davidopp how was backwards compatibility handled for this?

**Comment by bsalamat** [comment]
Thanks, @mtaufen for looking into the issue. As you have found, the failure is expected as node affinity had a non-backward compatible change in 1.6. More context on this can be found at:
https://docs.google.com/document/d/1YP3OJTKMpXkWAhipPjx9-bDMxJ87JZ6AcVak7c3SGos

**Comment by dchen1107** [comment]
@davidopp I marked this for 1.7 blocking too for now. Please triage it. Thanks!

**Comment by davidopp** [comment]
@bsalamat Can you take care of getting this test disabled in the 1.5-1.7 upgrade suite?

**Comment by bsalamat** [comment]
I just had a quick conversation with @monopole. We may drop all these 1.5 to 1.7 tests. So, I will wait until I get a more definitive answer and then if we decide to keep them, I will ginkgo-skip them.

**Comment by monopole** [comment]
OK, we're (i.. Dawn and I) going to just ignore these broken tests in 1.5-1.7
Going forward,  please be cognizant of upgrade compatibility and test health. 

Focussing on 1.6->1.7, we've got some new failures yesterday (on the 22nd) despite many green runs preceding it.

https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-gci-upgrade-master&include-filter-by-regex=Daemon%20set

PTAL.  This issue still open for 1.6 -> 1.7

**Comment by bsalamat** [comment]
Similar to what I mentioned in the other issue for Scheduler predicates test, this one seems to have failed only when there are many other test failures in [the test grid](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-gci-upgrade-master). So, probably a bad build or test cluster issues.

**Comment by mtaufen** [comment]
Closing as no updates in 2 months. Feel free to re-open if you see this issue again.
