### ISSUE TITLE
We should monitor amount of free resources on master machine(s) in e2e tests.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#47777]
Only monitoring we currently have is poor-man's 'resource-usage-gatherer' which is run only in scale tests and trans resource usage of few known components. This is hard to maintain as we add more and more components to master machine, thus we need something that would monitor how much slack there is.

cc @ncdc @caesarxuchao @kubernetes/sig-scalability-misc @kubernetes/sig-api-machinery-misc @kubernetes/sig-testing-misc

**Comment by ncdc** [comment]
@gmarek what do you want to monitor, and at what granularity?

cc @timothysc @kensimon

**Comment by gmarek** [comment]
I mean have a metric that shows utilization of the machine. I don't have any opinion on granularity - anything reasonable is fine.

**Comment by timothysc** [comment]
There are zillions of tools to do this and we could even add one to the master deployments.  

I really don't want another metric though, b/c don't we already get that from the kubelet running the master today?

**Comment by gmarek** [comment]
I don't know if it does @kubernetes/sig-node-feature-requests.

**Comment by mml** [comment]
/assign mml
cc @jpbetz
