### ISSUE TITLE
imagePullPolicy: IfNotPresent not pulling images with latest tag

### ISSUE THREAD

**Issue by tuminoid** [kubernetes/kubernetes#47775]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):
no

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
imagepullpolicy ifnotpresent

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug report

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.5", GitCommit:"490c6f13df1cb6612e0993c4c14f2ff90f8cdbf3", GitTreeState:"clean", BuildDate:"2017-06-14T20:15:53Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Vagrant and OpenStack
- **OS** (e.g. from /etc/os-release): `Red Hat Enterprise Linux Server release 7.3 (Maipo)`
- **Kernel** (e.g. `uname -a`): `Linux kubeminion1 3.10.0-514.21.1.el7.x86_64 #1 SMP Sat Apr 22 02:41:35 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**: kubelet from rpm, self-hosted k8s
- **Others**:

**What happened**:
Per https://kubernetes.io/docs/concepts/configuration/overview/ :
```
The default container image pull policy is IfNotPresent, which causes the Kubelet to not pull an image if it already exists. If you would like to always force a pull, you must specify a pull image policy of Always in your .yaml file (imagePullPolicy: Always) or specify a :latest tag on your image.
```

I have (for testing), in my manifest:
`image: registry:5000/postgres:latest`

If I add `imagePullPolicy: IfNotPresent`, it does NOT get pulled when updated.
If I leave `imagePullPolicy` off the manifest (as per the documentation, it should still be `IfNotPresent`, it DOES get pulled.

**What you expected to happen**:
Image with `latest` tag gets pulled when `imagePullPolicy: IfNotPresent` is in the manifest.
Alternatively, if default has changed to `Always`, or `latest`is not pulled anymore by design, the documentation needs an update.

**How to reproduce it** (as minimally and precisely as possible):
- Push an image with latest tag to registry
- Docker pre-pull the image, so it certainly exists on the minion(s)
- Update the image, and repush the registry
- Launch a container using manifest, with `latest` tag used and use `imagePullPolicy: IfNotPresent`, observe via `kubectl describe` the image was not pulled
- Remove said container, comment out `imagePullPolicy: IfNotPresent`, and relaunch
- Observe via `kubectl describe` there is event for `Pulling` the image.

**Anything else we need to know**:

**Comment by zhouhaibing089** [comment]
> If I add imagePullPolicy: IfNotPresent, it does NOT get pulled when updated.
If I leave imagePullPolicy off the manifest (as per the documentation, it should still be IfNotPresent, it DOES get pulled.

I think this behavior is correct: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/defaults.go#L80-L91.

If the `ImagePullPolicy` is not set, it will look for the image tag, if it is `latest`, it will default to be `Always`, otherwise, default to be `IfNotPresent`.

Also, in my understanding, The documentation is also correct, the ImagePullPolicy defaults to be `IfNotPresent`, unless:

1. explicitly says `Always`.
2. or use the `latest` image and leave empty for the field `ImagePullPolicy`.

**Comment by tuminoid** [comment]
I think it is very confusing to have two different meanings of `IfNotPresent`: one when it is deducted by tag and one when it is explicit. If value is `IfNotPresent`, it should act the same way no matter what.

I'd argue that the convention I'm looking for is very much the standard in Linux configuration. Configuration files are filled with commented out defaults, like 
```
# by default, foo=bar
# FOO=bar
```
and uncommenting that line does not change behaviour, it just explicitly changes configuration value that it does not accidentally change when default value changes by the maintainer. Which is the exact case here, I "uncomment" the default value and behaviour changes.

**Comment by eedugon** [comment]
Hello,

I agree with @tuminoid comments.
If "IfNotPresent" policy is set for an image, and that image is using the "latest" tag, then it will never be updated, and that doesn't have any sense, right? The main purpose of `latest` is actually to fetch updates as soon as they are available.

I think the consistent behavior here would be to do always the same no matter if "IfNotPresent" is explicitly configured or is empty.

Although it's true that if we do that and we set an image tag to `latest`, then it will be impossible to avoid fetching the image in every reboot, but who wants that? If someone wants that, another tag + IfNotPresent should be used instead, from my point of view :)

**Comment by bryanlarsen** [comment]
There are two different behaviours here, and both are needed.   Having one of the behaviours only occur when it's not specified makes it difficult to template with something like helm.   And as the original bug raises, it also makes the documentation confusing.

Can we create a new value for the default behaviour?   Something like "IfNotPresentOrTaggedLatest" perhaps?

**Comment by RobCannon** [comment]
Is there way to set the behavior to not change the image, if one is present.  This is slightly different from pulling.  I want to be able to specify the image name without a tag in the spec file and then use 'set image' to change the image (with a tag) to update the image as the dev team produces new version of an image.  But if the ops team make a change in the spec file and applies that, the image should change.  

Currently, apply will set the image back to 'latest', but it is the latest is from when the file was first applied, so it will revert to the version that was first deployed.  This is very in-intuitive and it took me hours to figure out what was going on.  I don't want to embed a version tag in the spec file, because the version tag will change often and the ops team shouldn't have to keep track of that when k8s does a fine job of tracking that.

**Comment by tuminoid** [comment]
/remove-lifecycle stale

I'd like to see a project member comment on this.

**Comment by bartoszhernas** [comment]
Hi, we stumbled into a similar issue.

Our spec:
- no ImagePullPolicy
- GKE 1.10 Kubernetes
- image in spec has "latest" tag

When we do a release we update image via kubectl specifying the SHA of the image.
Additionally, we tag the newest image (coming from master branch) as "latest". 

Then I've added a new environment variable to the spec, and used "kubectl apply". 
Our latest tag is pointing to the image that was currently set. 

Unknowingly, the cluster used some old image that previously also had "latest" tag. 
I have no idea why this happened as we do not specify "ImagePullPolicy" in the spec, so according to the documentation, it should always be pulled.

I see also that this is a deprecated now, what is K8S' team suggestion for supporting this flow:
- CI updates images using `kubectl set image deployment/...`
- Spec is kept in YAML in separate repo
- Master images are always tagged with `latest`
- When we need to update the spec (scaling, new envs etc) we just do `kubectl apply -f`

Manually specifying the latest SHA any time we need to update the spec feels odd.

**Comment by stanislavb** [comment]
We experienced a similar issue to the one in the comment above.

* no ImagePullPolicy
* GKE 1.10.6 Kubernetes (also replicated in minikube with 1.10)
* image has no tag specified

Providing an ImagePullPolicy changed behavior so we are explicitly setting it to Always now even though I would expect the following to be true:

"An alternative, but deprecated way to have Kubernetes always pull the image is to use the :latest tag, which will implicitly set the imagePullPolicy to Always"
Source: https://kubernetes.io/docs/concepts/configuration/overview/

"If you did not specify tag of your image, it will be assumed as :latest, with pull image policy of Always correspondingly."
Source: https://kubernetes.io/docs/concepts/containers/images/

**Comment by DarrienG** [comment]
I'm not a Kubernetes maintainer (although I am one of the Kubernetes maintainers at my company), but this is standard docker best practices. Tags are supposed to be immutable, and when you try to think of them as something that is not, you get into weird situations like this.

If you want to always get the latest image, you should set `imagePullPolicy: Always`

**Comment by tuminoid** [comment]
> I'm not a Kubernetes maintainer (although I am one of the Kubernetes maintainers at my company), but this is standard docker best practices. Tags are supposed to be immutable, and when you try to think of them as something that is not, you get into weird situations like this.
> 
> If you want to always get the latest image, you should set `imagePullPolicy: Always`

I agree with you. We run `AlwaysPullImages` admission plugin anyways. The point is to get it consistent. Either fix to code to work as documented, or fix the documentation to match the code. I'd prefer `IfNotPresent` and omitting `imagePullPolicy` to do the same.

/remove-lifecycle stale

**Comment by DarrienG** [comment]
We'll see how it goes: https://github.com/kubernetes/website/pull/17141

**Comment by mikebrow** [comment]
It is consistent.. but it is also confusing. The documentation is correct, but you have to read it all to get the gist and because it's confusing it is easy to make mistakes. suggest clarification with examples

**Comment by hermes85pl** [comment]
Although I agree with @mikebrow that the documentation is clear, I cannot say that I like current behavior.

I cannot agree with @DarrienG that tags shouldn't change. The "latest" tag is one exception, but please look at the patterns that are commonly used. E.g. for "debian" you have "latest", but also "buster" and "10" that are likely to be updated, as well as "10.4" that is less likely to be updated. To me this approach makes a lot of sense and I support it.

In my opinion setting the image pull policy to "Always" for deployments should be the default as "IfNotPresent" could be perceived as only a small optimization (if there are no changes, not much is happening: only the digests are fetched and compared and that's it) in case you are sure that there were no fixes to the image or that you don't want them for some specific reason. On the other hand, if the user specifies the behavior they want, it should always be obeyed as it is now. I believe that this approach would be more intuitive despite what some purists used to believe about thats before containers became widespread and have proven to be used differently.

If the aforementioned approach was chosen, it would be fairly easy to provide concise and clear documentation for it.

**Comment by vggarg96** [comment]
Hello I am new to the kubernetes and i am trying to start the deployment. I have a local docker image with latest tag as I am testing my application and it is not feasible to keep changing the version. I set the imagePullPolicy to ifNotPresent but it is still trying to pull the image from the docker hub. any suggestions??

**Comment by jkleckner** [comment]
FYI to those interested in this risk.

There is a k8s AdmissionController called AlwaysPullImages that will rewrite all incoming (newly created) pods to use the Always policy. https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#alwayspullimages
