### ISSUE TITLE
kubectl  get nodes : NotReady  @kubernetes/kubernetes/TLS

### ISSUE THREAD

**Issue by liuyihe111** [kubernetes/kubernetes#47785]
I have deployed Kubernetes on two worker nodes. On the master node(192.168.6.130), I installed etcd docker kube-apiserver kube-controller-manager and kube-scheduler. On the minion node(192.168.6.131), I installed flanneld docker kube-proxy and kubelet. Then I configured Two-way TLS communication between two nodes.

The configuration process refer to the following file: 
https://www.kubernetes.org.cn/648.html

But I have a question after configuring the  Two-way TLS communication as follows:
![image](https://user-images.githubusercontent.com/28377923/27334276-5ae91972-55fb-11e7-9165-488b3d6dad28.png)

Then I add the Authentication parameters, but the result isn't changed:
![image](https://user-images.githubusercontent.com/28377923/27334448-efb5e404-55fb-11e7-8476-eb568ec7f34a.png)

Thanks for every kind friend helping me .

**Comment by liggitt** [comment]
for support questions, please use our troubleshooting guide and community support channels (see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

**Comment by liuyihe111** [comment]
@liggitt My master node and minion node both work normal. And before I configure TLS , I can get node ready . But notready after configuring TLS. So I want to know why it happen? And how to solve it ? 

Thank you very much!
