### ISSUE TITLE
AWS SDK can return error messages that include a return key

### ISSUE THREAD

**Issue by rrati** [kubernetes/kubernetes#47789]
The following log excerpt comes from the attach detach controller trying to attach a volume that is already attached to an instance.

attacher.go:73] Error attaching volume "aws://us-east-1c/<vol>": Error attaching EBS volume "<vol>" to instance "<instance>": VolumeInUse: <vol> is already attached to an instance
nestedpendingoperations.go:262] Operation for "\"kubernetes.io/aws-ebs/aws://us-east-1c/<vol>\"" failed. No retries permitted until <date> (durationBeforeRetry 2m0s). Error: Failed to attach volume "<pvc>" on node "<node>" with: Error attaching EBS volume "<vol>" to instance "<vol>": VolumeInUse: <vol> is already attached to an instance
aws.go:1248] Assigned mount device cm -> volume <vol>
aws.go:1271] Releasing in-process attachment entry: cm -> volume <vol>
status code: 400, request id:
status code: 400, request id:

The problem is that the AWS SDK produces an error message that includes a \n in it.  This can cause the log message to be split over multiple log entries.  That situation can be made worse if there are multiple events/logs going on at the same time.

We should handle log messages from aws that contain a \n character in a better way.

@kubernetes/sig-aws-misc @justinsb

**Comment by gnufied** [comment]
I propose that we replace those pesky "\n\t" with "---" and join the error logs. I don't see any value in log lines that span multiple lines.

**Comment by justinsb** [comment]
We should use %q as our formatter for these messages, not %s.

**Comment by justinsb** [comment]
Ah - hadn't twigged this was an `%v` with an error, but it does seem to work:

https://play.golang.org/p/Y0fHPbixek

**Comment by rrati** [comment]
The only issue I have with %q is that is kind of decreases readability imo.  It leaves the \n in the string vs interpret it, but that means you have information separated by \n characters.  Probably better than having it on multiple lines, but not ideal.  Unless there is something better I guess %q is better then the current situation.

**Comment by rrati** [comment]
Closed via #47919
