### ISSUE TITLE
Allow capital letters for TokenRegexpString

### ISSUE THREAD

**Issue by andrey01** [kubernetes/kubernetes#47781]
Dear Kubernetes engineers,

is there any particular reason why capital letters are not allowed in the token?

-
 https://github.com/kubernetes/kubernetes/blob/7e37b895d7c1e92ed6fee70f0e507688ac41ec7b/cmd/kubeadm/app/util/token/tokens.go#L36

- https://github.com/kubernetes/kubernetes/pull/41663/files#diff-de98975ccd7f6f36d122d19b7c169191R175

Thanks

**Comment by xilabao** [comment]
cc @luxas

**Comment by liggitt** [comment]
the token id is used in the name of the `Secret` object that stores the token, and Secret names cannot have upper-case characters

**Comment by liggitt** [comment]
the token id is used in the name of the `Secret` object that stores the token, and Secret names cannot have upper-case characters

**Comment by luxas** [comment]
@andrey01 Also read https://github.com/kubernetes/community/blob/master/contributors/design-proposals/bootstrap-discovery.md
