### ISSUE TITLE
Adding `failure-domain.beta.kubernetes.io/zone` label manually causes node controller panic

### ISSUE THREAD

**Issue by lukaszo** [kubernetes/kubernetes#47791]
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.1.51+594edb77397512-dirty", GitCommit:"594edb773975124b137fa12bc573478a0355e89c", GitTreeState:"dirty", BuildDate:"2017-06-20T10:51:10Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.1.51+594edb77397512-dirty", GitCommit:"594edb773975124b137fa12bc573478a0355e89c", GitTreeState:"dirty", BuildDate:"2017-06-20T11:29:14Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}

**What happened**: After adding `failure-domain.beta.kubernetes.io/zone` label to a node, node controller panics.

**What you expected to happen**: Everything should still work.

**How to reproduce it** (as minimally and precisely as possible):

Run `"cluster/kubectl.sh" label  nodes --all failure-domain.beta.kubernetes.io/zone=zone` and wait for the node controller to panic:

```
E0620 14:45:34.888655       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/salmon/code/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/salmon/code/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/salmon/code/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/salmon/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:514
/home/salmon/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:489
/home/salmon/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:63
/home/salmon/.gimme/versions/go1.8.linux.amd64/src/runtime/signal_unix.go:290
/home/salmon/code/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/node/rate_limited_queue.go:244
/home/salmon/code/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/node/nodecontroller.go:1023
/home/salmon/code/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/node/nodecontroller.go:659
/home/salmon/code/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/node/nodecontroller.go:490
/home/salmon/code/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/home/salmon/code/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98
/home/salmon/code/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/home/salmon/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3484942]
```

**Anything else we need to know**:

I've checked the code and it looks like the node controller expects the label to be present during node registration and it can not be added later.
Even if the label can not be added latter it shouldn't panic.

**Comment by k82cn** [comment]
/assign

let me try this :).
