### ISSUE TITLE
Local storage isolation doesn't work for pod with only overlay or scratch space request

### ISSUE THREAD

**Issue by ddysher** [kubernetes/kubernetes#47798]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

No

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

local isolation

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug

**Kubernetes version** (use `kubectl version`):

kubernetes HEAD

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

For local storage isolation, overlay resource predicates for pod with only overlay or scratch storage request doesn't work.

**What you expected to happen**:

If a pod requests only overlay or scratch storage, then local storage isolation feature should limit the pods.

**How to reproduce it** (as minimally and precisely as possible):

Run local cluster from master branch, and create following pods (against a machine with less overlay fs than 1024Gi).

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        storage.kubernetes.io/overlay: 1024Gi
```

**Anything else we need to know**:

**Comment by saad-ali** [comment]
CC @jingxu97

**Comment by saad-ali** [comment]
Fix is ready: https://github.com/kubernetes/kubernetes/pull/47179
