### ISSUE TITLE
NetworkPolicy with namespaceSelector on name i.s.o. custom label

### ISSUE THREAD

**Issue by boeboe** [kubernetes/kubernetes#47797]
@kubernetes/sig-network

I try to implement a network policy with namespaceSection based on the name of the namespace. This seems not to work however. When I add an extra custom label on that namespace and use that as selector in matchLabels, it works however.

Not working NetworkPolicy:

	apiVersion: extensions/v1beta1
	kind: NetworkPolicy
	metadata:
	  name: test-network-policy
	  namespace: default
	spec:
	  podSelector:
		matchLabels:
		  role: db
	  ingress:
	  - from:
		- namespaceSelector:
			matchLabels:
			  name: <namespace-name>
		ports:
		- protocol: tcp
		  port: 6379

Working NetworkPolicy:		  
		  
	apiVersion: extensions/v1beta1
	kind: NetworkPolicy
	metadata:
	  name: test-network-policy
	  namespace: default
	spec:
	  podSelector:
		matchLabels:
		  role: db
	  ingress:
	  - from:
		- namespaceSelector:
			matchLabels:
			  <custom label on namespace>: <value>
		ports:
		- protocol: tcp
		  port: 6379

Is this intended behaviour, since I cannot get this out of the documentation?
https://kubernetes.io/docs/concepts/services-networking/networkpolicies

**Comment by cmluciano** [comment]
@kubernetes/sig-network-misc cc @danwinship

**Comment by caseydavenport** [comment]
@boeboe that's the expected behavior - the `namespaceSelector` applies to labels on a Namespace, not fields on a Namespace.

**Comment by boeboe** [comment]
Thanks for your clarification @caseydavenport . I'll do a pull request on an extra note in the documentation later this week to stress this, since it feels a bit counterintuitive to me.

BR,
Bart

**Comment by caseydavenport** [comment]
Sounds good, always good to have more clear documentation! But I'm not sure I follow that `matchLabels` matching on labels is counterintuitive :)

/close

**Comment by jayunit100** [comment]
were going to propose this to the sig-network group
