### ISSUE TITLE
ability to bind PVC's with a storage class with a manually created PV

### ISSUE THREAD

**Issue by bryanlarsen** [kubernetes/kubernetes#47802]
Feature Request:

Some sort of mechanism so that manually created PersistentVolume's will bind a PersistentVolumeClaim with a volume.alpha.kubernetes.io/storage-class annotation.

Use case: deploying helm charts to a cluster that doesn't have a dynamic provisioner.

Most helm charts have storageClass variables to set the storage-class annotation on PVC's they create.   When not set, they usually default to the `default` storage-class.   They generally don't have the ability to remove the storage-class annotation, and because they have the storage-class annotation set, they will never bind to any manually created PersistentVolume's.

My workaround is to manually delete the annotation after deployment, allowing the PVC & PV to bind.   Subsequent upgrades of the chart will restore the annotation, but won't break the binding.

In theory helm charts should have the ability to remove the storage-class annotation and configure a selector instead, but in practice most won't.

Instead it's probably better to handle this in Kubernetes.   Possibilities:

- allow the user to create a manual StorageClass
- when the cluster doesn't have a dynamic provisioner, ignore storage-class
- allow the user to set a 'storage-class' annotation on PersistentVolume's that will bind to any PVC's with the same storage-class annotation

Note that we should probably have some way of assigning PVC's to specific PV's.   A selector is of course the right way to do that, but again we're asking a lot of helm chart authors.   Perhaps we could abuse storage-class for this, have the user use the same storage-class annotation on the PVC and matching PV.

**Comment by wongma7** [comment]
This is already possible so if it isn't working, it is a bug. The issue I think is that the alpha annotation is being used; the alpha annotation does not care about storage classes and it doesn't matter what its value is because just by being present, it will force a PV to be provisioned. Beta is when storage classes start mattering.

**Comment by bryanlarsen** [comment]
Sweet!   Creating PVC's with `storageClassName: ''` works great!   Unlike some sort of hacky selector magic, a PR to switch from the alpha/beta annotation to storageClassName will likely be accepted and future charts are likely to use the final form.
