### ISSUE TITLE
Unable to signify a successful operation on pod with last initializer from Initializers list.

### ISSUE THREAD

**Issue by bskiba** [kubernetes/kubernetes#47801]
I'm trying to use the initlializers feature (https://github.com/kubernetes/community/pull/132), and I am unable to signify that the operation of the initializer is successful. 

To reproduce: Create one intializer - "vpa-initializer.k8s.io" that operates on all pods.  Extract from configuration:
`InitializerConfiguration
{
  ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{
    Name:vpa-initializer-config.k8s.io,
  }
  Initializers:[{vpa-initializer.k8s.io [{[*] [*] [pods]}] 0xc4203771f0}],
}`
Initializer watches for uninitialized pods. A pod was added with  metadata.initializers.pending =  ["vpa"]
The initializer performs some work on the pod and then sets metadata.initializers.pending to and empty list. After that I've tried two scenarios, both fail: 
1. Write pod with `metadata.initializers.pending = []` and  `metadata.initializers.status.status = nil`
Result: `Pod is invalid: metadata.initializers.pending: Invalid value: "null": must be non-empty when result is not set`
2. Write pod with `metadata.initializers.pending = []` and `metadata.initializers.result.status = 'Success'`
Result: `Pod  is invalid: metadata.initializers.result.status: Invalid value: "Success": must be 'Failure'`

I believe this is a bug in validation code for initializers.

@lavalamp 
@smarterclayton 
@mwielgus

**Comment by smarterclayton** [comment]
To signal success, clear initializers altogether.

**Comment by bskiba** [comment]
Thanks, that does work. So basically the behaviour of the initializer depends on if it's the last one on the list? If it's not, remove itself from the pending list, otherwise clear initializers altogether?

**Comment by smarterclayton** [comment]
Yes
