### ISSUE TITLE
kubelet is incorrectly exposing `storage` as a new compute resource

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#47809]
Local storage is not expected to be available as a scheduling resource in v1.7.
Kubelet is incorrectly exposing a resource named `storage`.
This is incorrect because the feature is alpha and so it requires opt-in via feature flags and,
the resource names are invalid.
The expected resource names are listed [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L3533) - `storage.kubernetes.io/scratch` and `storage.kubernetes.io/overlay`.

cc @jingxu97 @saad-ali 

This is v1.7 blocker because we cannot expose a new resource in the API and rename it in a subsequent release.

@kubernetes/sig-storage-bugs

**Comment by saad-ali** [comment]
CC @dchen1107 

I'll find someone on the storage team to address this.
