### ISSUE TITLE
CRI package name is still `v1alpha1`

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#47814]
Although we [moved CRI from `v1alpha1` to `v1alpha1/runtime`](https://github.com/kubernetes/kubernetes/commit/9cc2ecc347908faf0a79104f645241da24d97558), we didn't change the package name. When using the package, I have to make an alias, or else I have to use `v1alpha1.xxxx` instead.

@feiskyer Another question is that is grpc using the directory name or package name? If the latter, does the original PR really fix the issue?

/cc @yujuhong

**Comment by yujuhong** [comment]
> @feiskyer Another question is that is grpc using the directory name or package name? If the latter, does the original PR really fix the issue?

Package name. It didn't fix the issue.
