### ISSUE TITLE
support what-can-i-do in kubernetes

### ISSUE THREAD

**Issue by xilabao** [kubernetes/kubernetes#47834]
Currently if people only have permission to get several named resources. they can't use `kubectl get <resource>` to get the list. If we can support `what-can-i-do`, it will be very helpful.
I saw it in openshift (https://github.com/openshift/origin/pull/8675). Could we add this to kubernetes? @deads2k @liggitt

**Comment by deads2k** [comment]
It requires a new API and it would only work for some authorizers (RBAC would work).  I'm in favor of doing it.

**Comment by mikedanese** [comment]
I feel like this is a dup of an older issue but I can't find it.  cc @kubernetes/sig-auth-misc

**Comment by bgrant0607** [comment]
Dupe of https://github.com/kubernetes/kubernetes/issues/31292
