### ISSUE TITLE
Nodeport only works on Pod Host

### ISSUE THREAD

**Issue by erikbgithub** [kubernetes/kubernetes#47838]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): nodeport, pod, redirect

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: on premise (with xen)
- **OS** (e.g. from /etc/os-release):

```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

- **Kernel** (e.g. `uname -a`): `Linux reliance-01 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux`
- **Install tools**: kubeadm
- **Others**:

**What happened**:
We created a kubernetes service, and want to publicly access it. If you access the NodePort on any other host but the pod-host then you can't access it.

**What you expected to happen**: That I can access it from any host.

**How to reproduce it** (as minimally and precisely as possible):

deploy a service like this one:

```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-06-21T10:47:19Z
  labels:
    app: appname
    tool-component: appname
  name: appname
  namespace: test
spec:
  ports:
  - name: appname
    port: 10002
    protocol: TCP
    targetPort: 10002
  selector:
    app: appname
    tool-component: appname
  type: NodePort
```

**Anything else we need to know**:

 1. It's probably not the overlay network (weave), since we can use the pod's ip and internal port from any host to access it.
 2. The pod ip is not mentioned in the ipsets of other hosts.
 3. check the iptables rules:
    ```
    [...]
    Chain WEAVE-NPC-DEFAULT (1 references)
     pkts bytes target     prot opt in     out     source               destination
    74168 6425K ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set weave-iuZcey(5DeXbzgRFs8Szo]+@p dst
        1    64 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set weave-k?Z;25^M}|1s7P3|H9i;*;MhG dst
        0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set weave-4vtqMI+kx/2]jD%_c0S%thO%V dst
     3269  196K ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set weave-1.iwr;e4~v)iFd4cvE8nqD0.) dst
    ```
 4. check the `ipset list`:
    ```
    Name: weave-local-pods
    Type: hash:ip
    Revision: 3
    Header: family inet hashsize 1024 maxelem 65536
    Size in memory: 16600
    References: 2
    Members:
    172.16.0.3
    172.16.0.4
    172.16.0.5
    172.16.0.2
    172.16.0.7

    Name: weave-iuZcey(5DeXbzgRFs8Szo]+@p
    Type: hash:ip
    Revision: 3
    Header: family inet hashsize 1024 maxelem 65536
    Size in memory: 16536
    References: 1
    Members:
    172.16.0.2
    172.16.0.3

    Name: weave-k?Z;25^M}|1s7P3|H9i;*;MhG
    Type: hash:ip
    Revision: 3
    Header: family inet hashsize 1024 maxelem 65536
    Size in memory: 16536
    References: 1
    Members:

    Name: weave-4vtqMI+kx/2]jD%_c0S%thO%V
    Type: hash:ip
    Revision: 3
    Header: family inet hashsize 1024 maxelem 65536
    Size in memory: 16504
    References: 1
    Members:

    Name: weave-1.iwr;e4~v)iFd4cvE8nqD0.)
    Type: hash:ip
    Revision: 3
    Header: family inet hashsize 1024 maxelem 65536
    Size in memory: 16552
    References: 1
    Members:
    172.16.0.5
    172.16.0.7
    172.16.0.4

    ```
 5. The pod has the IP: 172.16.240.2
 6. if we add an entry to `ipset` for that IP it works: `ipset add "weave-k?Z;25^M}|1s7P3|H9i;*;MhG" 172.16.240.2`

**Comment by dixudx** [comment]
It seems that you had not started the `kube-proxy` on minion/kubelet nodes.

**Comment by erikbgithub** [comment]
@dixudx do I need to do that manually? Usually kubeadm join 
or the pod should take care of such things, or not?

**Comment by erikbgithub** [comment]
@kubernetes/sig-onprem-misc

**Comment by erikbgithub** [comment]
@kubernetes/sig-onprem 
@kubernetes/sig-network

**Comment by dixudx** [comment]
@erikbgithub Actually `kubeadm init` will help install add-on components via the API server. Right now this is the internal DNS server and the `kube-proxy` **DaemonSet** if you've well configured.

1. Please check whether `kube-proxy` is running on every kubelet node.
2. If kube-proxy daemonsets are running well, please check your firewall setttings (I think this may be the root cause).

**Comment by erikbgithub** [comment]
@dixudx Okay, thanks. Is there a guide how to do it or do I need to experiment that out? The kube-proxy command does have a lot of parameters it seems.

**Comment by erikbgithub** [comment]
@dixudx I verified with my colleague. Apiserver has deployed kube-proxy to all nodes, and they seem to be running fine. There's also no firewall issue we are aware of. Communication between pods works. Even the port forwarding works if the ip is added to the ipset manually.

**Comment by dixudx** [comment]
@erikbgithub 

1. `kubeadm init` will help you install `kube-proxy`, refer to [create-cluster-kubeadm](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#24-initializing-your-master). But you can’t run kubeadm init twice without tearing down the cluster in between. I think you need to check whether `kube-proxy` daemonsets have been deployed successfully. If kube-proxy daemonsets are running well on every kubelet node, please check your firewall setttings of every host.

    ```
    $ kubectl get ds -o wide | grep kube-proxy
    ```

2. Also you can manually start `kube-proxy` using below unit-file (Remember to change the CIDR)

```
[Unit]
Description=Kubernetes Kube Proxy

[Service]
ExecStart=/usr/bin/kube-proxy \\
  --cluster-cidr=10.200.0.0/16 \\
  --masquerade-all=true \\
  --kubeconfig=/var/lib/kube-proxy/kube-proxy.kubeconfig \\
  --proxy-mode=iptables \\
  --v=2
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

**Comment by erikbgithub** [comment]
`get ds` lists 15/15 which matches the number of hosts. `get pods|grep ...` also mentions 15 `kube-proxy` pods and each hosts hostname in the NODE column.

What can be checked in the firewall? All `iptables` tables are defaulting to `ALLOW`, and there are lots of entries for weave, lots of forwarding.

Does the following look bad?
```
$  iptables-save|grep -i drop
 -A INPUT -d 172.17.0.1/32 -i docker0 -p tcp -m tcp --dport 6783 -j DROP
-A INPUT -d 172.17.0.1/32 -i docker0 -p udp -m udp --dport 6783 -j DROP
-A INPUT -d 172.17.0.1/32 -i docker0 -p udp -m udp --dport 6784 -j DROP
-A FORWARD -i docker0 -o weave -j DROP
-A FORWARD -o weave -j DROP
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
:KUBE-MARK-DROP - [0:0]
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
```


The IP Range `172.17.0.1/32`is the service range, as configured with kubeadm init.

**Comment by erikbgithub** [comment]
What we mean with the ipset stuff.

There are some rules like these:
```
-A WEAVE-NPC -m set --match-set weave-local-pods src -m set ! --match-set weave-local-pods dst -j ACCEPT
-A WEAVE-NPC-DEFAULT -m set --match-set weave-iuZcey(5DeXbzgRFs8Szo]+@p dst -j ACCEPT
-A WEAVE-NPC-DEFAULT -m set --match-set weave-k?Z;25^M}|1s7P3|H9i;*;MhG dst -j ACCEPT
-A WEAVE-NPC-DEFAULT -m set --match-set weave-4vtqMI+kx/2]jD%_c0S%thO%V dst -j ACCEPT
-A WEAVE-NPC-DEFAULT -m set --match-set weave-1.iwr;e4~v)iFd4cvE8nqD0.) dst -j ACCEPT
```


they match against a certain weave client on another host, I suppose. But some of them don't have the corresponding pod IPs added, which can be checked with `ipset` and looking for the `weave-<regex>` group.

**Comment by dixudx** [comment]
@erikbgithub  For **NodePort**, some rules like

* `-A KUBE-NODEPORT-CONTAINER -p tcp -m comment --comment "default/nginx-service-nodeport:" -m tcp --dport 32606 -j REDIRECT --to-ports 43981`;
* `-A KUBE-NODEPORT-HOST -p tcp -m comment --comment "default/nginx-service-nodeport:" -m tcp --dport 30975 -j DNAT --to-destination 192.168.0.201:43981`;

should exist on iptable rules.

**Comment by entropia1** [comment]
The iptables rules look fine. 

```
$ iptables-save | grep <app>
-A KUBE-NODEPORTS -p tcp -m comment --comment "<namespace>/<category>-<app>:<app>" -m tcp --dport 31946 -j KUBE-MARK-MASQ
-A KUBE-NODEPORTS -p tcp -m comment --comment "<namespace>/<category>-<app>:<app>" -m tcp --dport 31946 -j KUBE-SVC-IRE2LNVCRAZIL64O
-A KUBE-SEP-2NLZP5UD72HMCECW -s 172.16.240.2/32 -m comment --comment "<namespace>/<category>-<app>:<app>" -j KUBE-MARK-MASQ
-A KUBE-SEP-2NLZP5UD72HMCECW -p tcp -m comment --comment "<namespace>/<category>-<app>:<app>" -m tcp -j DNAT --to-destination 172.16.240.2:10002
-A KUBE-SERVICES ! -s 172.16.0.0/16 -d 172.17.20.232/32 -p tcp -m comment --comment "<namespace>/<category>-<app>:<app> cluster IP" -m tcp --dport 10002 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 172.17.20.232/32 -p tcp -m comment --comment "<namespace>/<category>-<app>:<app> cluster IP" -m tcp --dport 10002 -j KUBE-SVC-IRE2LNVCRAZIL64O
-A KUBE-SVC-IRE2LNVCRAZIL64O -m comment --comment "<namespace>/<category>-<app>:<app>" -j KUBE-SEP-2NLZP5UD72HMCECW
```

But the packages get dropped, because the IP (here: `172.16.240.2`) is not in any of the ipsets mentioned above. If we manually add the IP to any of the sets (e.g., `ipset add "weave-k?Z;25^M}|1s7P3|H9i;*;MhG" 172.16.240.2`), the port forwarding works.

**Comment by erikbgithub** [comment]
@dixudx entropia is a colleague working on the same issue btw.

**Comment by ivan-gallego** [comment]
There was a bug in weave-npc 1.9.7 (now fixed in the [newest](https://github.com/weaveworks/weave/releases/tag/v1.9.8) version):
https://github.com/weaveworks/weave/issues/3011

**Comment by errordeveloper** [comment]
As @ivan-gallego pointed out, this is 100% to do with weaveworks/weave#3011, which had been resolved in latest release of Weave Net. I think this issue can be closed.

**Comment by entropia1** [comment]
I can confirm that the new weave-npc version fixes the issue.

**Comment by erikbgithub** [comment]
Thanks everybody for the help!
