### ISSUE TITLE
[initializers] Can't modify spec of uninitialized pod.

### ISSUE THREAD

**Issue by bskiba** [kubernetes/kubernetes#47837]
I'm trying to use the initlializers feature (kubernetes/community#132) and I am unable to modify the spec of an uninitialized pod. 

The initializer gets an uninitialized pod, modifies the resources.requests for some containers in the pod spec and POSTs the modified pod.
Result:
`Pod is invalid: spec: Forbidden: pod updates may not change fields other than 'spec.containers[*].image', 'spec.initContainers[*].image', 'spec.activeDeadlineSeconds' or 'spec.tolerations' (only additions to existing tolerations)`

Shouldn't the checks for changes on uninitialized pods be relaxed?

@lavalamp 
@mwielgus 

/sig api-machinery

**Comment by mwielgus** [comment]
cc: @smarterclayton

**Comment by droot** [comment]
cc @caesarxuchao

**Comment by caesarxuchao** [comment]
Can we fix it by creating another set of validation rules for uninitialized pods?

**Comment by liggitt** [comment]
the issue is significantly more complex than that. making pod specs mutable means revisiting every admission plugin that depends on immutability of the pod spec and updating it to tolerate changes, and deal with computing deltas between old and new (for things like quota)

**Comment by caesarxuchao** [comment]
Thanks @liggitt. How about this: for non-mutating admission plugins (like PodSecurityPolicy), we make sure they validate PUT request of pods as well; for mutating admission plugins (like quota), in the short term we just keep the affected fields immutable. Will that work?

**Comment by mwielgus** [comment]
The main use case that VPA has is to modify pod cpu/memory requests in the initializer. 

@caesarxuchao will it work with what you suggests?

**Comment by caesarxuchao** [comment]
No, that would require complex changes in the quota admission plugin.

BTW, is there a doc on VPA?

**Comment by mwielgus** [comment]
https://github.com/kubernetes/community/pull/338

**Comment by mwielgus** [comment]
cc: @kgrygiel

**Comment by mwielgus** [comment]
@caesarxuchao Why can't we simply pass all spec updates to pods via quota admission plugin?

**Comment by smarterclayton** [comment]
Can someone do a review of the implications of mutable pod specs in admission?  Most should have provisions for that, and allowing mutation during initialization is acceptable.

Quota is the odd man out, where we need to determine when to reject:

1. At first mutation over?
2. At the end of initialization and report to user?
3. Whenever an initializer asks for too much (burden on initializer)?
4. Make quota the implicit last initializer and have it perform the rejection?

**Comment by caesarxuchao** [comment]
I went through the admission plugins except for the resourcequota. Two things caught my eyes:
* The PodPreset plugin modifies the pod only if the verb is CREATE. Initializers might change the pod afterwards. I heard the beta version PodPreset would be implemented as an initializer, so it should be fine. The cluster admin is responsible to arrange the order of initializers and ban conflicting initializers. @droot can confirm.
* The admission webhooks: if a webhook is configured to only validate CREATE operation, it might be surprised that the initializers might make unacceptable changes. This can be solved by documentation.

**Comment by caesarxuchao** [comment]
The resourcequota admission plugin does [handle](https://github.com/kubernetes/kubernetes/blob/v1.7.3/plugin/pkg/admission/resourcequota/controller.go#L465-L481) UPDATE and charges the delta. @liggitt do you have other concerns regarding the resourcequota plugin?

I think we disallow mutating resource requirements of pods because the schedule isn't capable of rescheduling if the pod doesn't fit the node after an update. But since the scheduling happens after the pod is initialized, so mutating uninitialized pods is fine.

Regarding "when to reject", I think the plugin should reject "whenever an initializer asks for too much". Because an initializer shouldn't expect following initializers to trim the resource requirements, and we should tell user which initializer has messed up.

**Comment by mml** [comment]
cc @cheftako to weigh in on cloud provider stuff

**Comment by smarterclayton** [comment]
AdmissionWebhook and PodPreset both sound acceptable to me.

**Comment by farcaller** [comment]
My use case is mounting a new secret into a pod based on metadata (tls provisioning). Is this something that is covered by this bug?

**Comment by liggitt** [comment]
There are definitely other affected admission plugins. We need a *very* detailed review to make sure we don't open security holes or break functionality. A quick scan showed:

* NodeRestriction only verifies resource references from pods on create
* PersistentVolumeLabel only labels on create
* PodNodeSelector only enforces on create
* InitialResources only assigns resources on create
* PodTolerationRestriction only enforces namespace-specified tolerations on create
* ServiceAccount only mounts tokens and enforces mirror-pod secret restrictions on create
* DefaultStorageClass only sets the storage class on PVC on create

**Comment by caesarxuchao** [comment]
Thanks @liggitt.
> NodeRestriction only verifies resource references from pods on create

Good catch. It seems I can just add the "Update" to `admitPod`.

> PersistentVolumeLabel only labels on create

It only cares about PersistentVolume. We can revisit when we relax its validation.

In my last inspection I only looked for "GetOperation()=Create" and missed all the cases where the plugin uses `admission.NewHandler(admission.Create)` to handle only creations. I'll go over them again.

**Comment by caesarxuchao** [comment]
> PodNodeSelector

We can let it handle `Update` of uninitialized pods as well. It's modification to the pod's nodeSelector is idempotent. It detects conflicts between the pod's nodeSelector and the namespace's nodeSelector or the cluster one. It rewrites pod's nodeSelector with the merged result of pod's nodeSelector and namespace's one.

> InitialResources

The plugin doesn't cause side-effect, so it can handle `Update`. The plugin calls out to monitoring services to get the resource usage stats, so it's expensive. We limit It to handle only create and update of uninitialzied pods.

> PodTolerationRestriction only enforces namespace-specified tolerations on create

We either make it handle updates to uninitialized pods, or we can keep pod.spec.tolerations immutable even if the pod is not initialized.

> ServiceAccount

The plugin make idempotent changes to the pod's spec. It can handle "Update" to uninitialized pods.

> DefaultStorageClass only sets the storage class on PVC on create

We can revisit it when we relax the validation of PVC.

**Comment by mwielgus** [comment]
@caesarxuchao - FYI, InitialResources doesn't work, should be removed and will be replaced by what is @bskiba working on.

**Comment by caesarxuchao** [comment]
@mwielgus thanks. I'll leave InitialResources as is.

**Comment by bgrant0607** [comment]
This is a general issue for initializers, not just a Pod issue.

IIRC, the original proposal suggested deferring validation.

**Comment by caesarxuchao** [comment]
@bgrant0607 

> This is a general issue for initializers, not just a Pod issue.

Yes. That said, my current plan is to only relax the validation requirements of uninitialized pods in 1.8. We will make progress on other resources in later releases.

> IIRC, the original proposal suggested deferring validation.

I think for the update made by each initializer controller, we should validate the updated object, and invoke all the existing admission plugins. My reason is two-fold:
* each initializer controller should be able to operate even if it's the only initializer in the system, so each initializer controller's modification should be valid, that is, not depending on other initializers to make the object valid.
* fail early on invalid update made by an initializer, so that user can see which initializer makes invalid update.

**Comment by php-coder** [comment]
> How about this: for non-mutating admission plugins (like PodSecurityPolicy)

@caesarxuchao PodSecurityPolicy admission plugin mutates a pod. It assigns default values to the `SecurityContext`.

@pweil- @liggitt Correct me if I'm wrong.

**Comment by liggitt** [comment]
> @caesarxuchao PodSecurityPolicy admission plugin mutates a pod. It assigns default values to the SecurityContext.
>
> @pweil- @liggitt Correct me if I'm wrong.

you are correct

**Comment by caesarxuchao** [comment]
@php-coder that was a bad example. Anyway, `PodSecurityPolicy` [handles](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/security/podsecuritypolicy/admission.go#L91) pod updates, and it looks like we don't need to update it to adapt to mutating pod spec.
