### ISSUE TITLE
Kibana UI is not loaded up with backend 404 status

### ISSUE THREAD

**Issue by chenww** [kubernetes/kubernetes#47848]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
"Kibana is loading"  "kibana 404 status" "kibana spinning"
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4+coreos.0", GitCommit:"8996efde382d88f0baef1f015ae801488fcad8c4", GitTreeState:"clean", BuildDate:"2017-05-19T21:11:20Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4+coreos.0", GitCommit:"8996efde382d88f0baef1f015ae801488fcad8c4", GitTreeState:"clean", BuildDate:"2017-05-19T21:11:20Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
Openstack VMs
- **OS** (e.g. from /etc/os-release):
cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"

- **Kernel** (e.g. `uname -a`):
$ uname -a
Linux weiwenSandbox 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**:
kargo
- **Others**:

**What happened**:
Kibana UI is at loading state forever

**What you expected to happen**:
Kibana UI can load

**How to reproduce it** (as minimally and precisely as possible):

1. Install k8s cluster with the latest kargo at https://github.com/kubernetes-incubator/kubespray
2. bring up kibana UI

**Anything else we need to know**:
versions:
Kibana: 4.6.1
ES: 2.4.1
kubernetes: 1.6.4
$ kubectl cluster-info
Kubernetes master is running at http://localhost:8080
Elasticsearch is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging
Kibana is running at 
http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kibana-logging
kubedns is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kubedns

When I access UI http://kibana.mycompany.local/app/kibana, kibana backend sends out the following logs and UI is at "Kibana is loading" state forever:

{"type":"response","@timestamp":"2017-06-21T15:23:51Z","tags":[],"pid":7,"method":"get","statusCode":200,"req":{"url":"/app/kibana","method":"get","headers":{"host":"kibana.mycompany.local","connection":"close","x-real-ip":"172.27.31.228","x-forwarded-for":"172.27.31.228","x-forwarded-host":"kibana.mycompany.local","x-forwarded-port":"80","x-forwarded-proto":"http","x-original-uri":"/app/kibana","x-scheme":"http","cache-control":"max-age=0","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,/;q=0.8","accept-encoding":"gzip, deflate, sdch","accept-language":"en-US,en;q=0.8,zh-CN;q=0.6"},"remoteAddress":"10.0.0.12","userAgent":"10.0.0.12"},"res":{"statusCode":200,"responseTime":7,"contentLength":9},"message":"GET /app/kibana 200 7ms - 9.0B"}
{"type":"response","@timestamp":"2017-06-21T15:23:51Z","tags":[],"pid":7,"method":"get","statusCode":404,"req":{"url":"/api/v1/proxy/namespaces/kube-system/services/kibana-logging/bundles/commons.bundle.js?v=10146","method":"get","headers":{"host":"kibana.mycompany.local","connection":"close","x-real-ip":"172.27.31.228","x-forwarded-for":"172.27.31.228","x-forwarded-host":"kibana.mycompany.local","x-forwarded-port":"80","x-forwarded-proto":"http","x-original-uri":"/api/v1/proxy/namespaces/kube-system/services/kibana-logging/bundles/commons.bundle.js?v=10146","x-scheme":"http","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36","accept":"/","referer":"http://kibana.mycompany.local/app/kibana","accept-encoding":"gzip, deflate, sdch","accept-language":"en-US,en;q=0.8,zh-CN;q=0.6"},"remoteAddress":"10.0.0.12","userAgent":"10.0.0.12","referer":"http://kibana.mycompany.local/app/kibana"},"res":{"statusCode":404,"responseTime":92,"contentLength":9},"message":"GET /api/v1/proxy/namespaces/kube-system/services/kibana-logging/bundles/commons.bundle.js?v=10146 404 92ms - 9.0B"}
{"type":"response","@timestamp":"2017-06-21T15:23:51Z","tags":[],"pid":7,"method":"get","statusCode":404,"req":{"url":"/api/v1/proxy/namespaces/kube-system/services/kibana-logging/bundles/commons.style.css?v=10146","method":"get","headers":{"host":"kibana.mycompany.local","connection":"close","x-real-ip":"172.27.31.228","x-forwarded-for":"172.27.31.228","x-forwarded-host":"kibana.mycompany.local","x-forwarded-port":"80","x-forwarded-proto":"http","x-original-uri":"/api/v1/proxy/namespaces/kube-system/services/kibana-logging/bundles/commons.style.css?v=10146","x-scheme":"http","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36","accept":"text/css,/;q=0.1","referer":"http://kibana.mycompany.local/app/kibana","accept-encoding":"gzip, deflate, sdch","accept-language":"en-US,en;q=0.8,zh-CN;q=0.6"},"remoteAddress":"10.0.0.12","userAgent":"10.0.0.12","referer":"http://kibana.mycompany.local/app/kibana"},"res":{"statusCode":404,"responseTime":189,"contentLength":9},"message":"GET /api/v1/proxy/namespaces/kube-system/services/kibana-logging/bundles/commons.style.css?v=10146 404 189ms - 9.0B"}
{"type":"response","@timestamp":"2017-06-21T15:23:51Z","tags":[],"pid":7,"method":"get","statusCode":404,"req":{"url":"/api/v1/proxy/namespaces/kube-system/services/kibana-logging/bundles/kibana.style.css?v=10146","method":"get","headers":{"host":"kibana.mycompany.local","connection":"close","x-real-ip":"172.27.31.228","x-forwarded-for":"172.27.31.228","x-forwarded-host":"kibana.mycompany.local","x-forwarded-port":"80","x-forwarded-proto":"http","x-original-uri":"/api/v1/proxy/namespaces/kube-system/services/kibana-logging/bundles/kibana.style.css?v=10146","x-scheme":"http","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36","accept":"text/css,/;q=0.1","referer":"http://kibana.mycompany.local/app/kibana","accept-encoding":"gzip, deflate, sdch","accept-language":"en-US,en;q=0.8,zh-CN;q=0.6"},"remoteAddress":"10.0.0.12","userAgent":"10.0.0.12","referer":"http://kibana.mycompany.local/app/kibana"},"res":{"statusCode":404,"responseTime":189,"contentLength":9},"message":"GET /api/v1/proxy/namespaces/kube-system/services/kibana-logging/bundles/kibana.style.css?v=10146 404 189ms - 9.0B"}

@kubernetes/sig-Apps-misc
/sig Apps
/area logging

**Comment by chenww** [comment]
@kubernetes/sig-Apps-misc

**Comment by chenww** [comment]
I figured this out as it is kargo issue in which it has KIBANA_BASE_URL configured. Remove it works.

        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://elasticsearch-logging:9200"
#          - name: "KIBANA_BASE_URL"
#            value: "/api/v1/proxy/namespaces/kube-system/services/kibana-logging"

**Comment by crassirostris** [comment]
@chenww Yup, the docs around this deployment is not in the best shape, sorry. If you remove this env variable, kibana starts working with the root path, but stops working through proxy. This is the Kibana's peculiarity :)
