### ISSUE TITLE
Need example admission plugin

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#47868]
The sample-apiserver should provide an example admission plugin that makes meaningful use of a plugininitializer.  One way to do this is to create a cluster-scoped resource in the group.  The cluster scoped resource could have a field that indicates Flunder.Names that are disallowed.  The admission plugin could list the cluster-scope resources and check against banned names.

It could later be expanded to first check a generated lister so that it is forced to create its own plugininitializer and add it to the chain.

@p0lyn0mial

**Comment by mml** [comment]
cc @cheftako

**Comment by p0lyn0mial** [comment]
@deads2k please close the issue as it has been implemented and I don't have sufficient rights.
