### ISSUE TITLE
Scheduler and kubelet should consider resources of terminated-but-not-yet-deleted pods to still be in use.

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#47867]
@vishh pointed out that for scheduling and kubelet admission, we should consider resources of terminated-but-not-yet-deleted pods to still be in use, because it may take an arbitrary amount of time for the system to deallocate resources. We didn't check to see if this is currently how it is implemented or not.

cc/ @vishh @bsalamat 

/sig scheduling

**Comment by davidopp** [comment]
cc/ @kubernetes/sig-scheduling-feature-requests

**Comment by k82cn** [comment]
For terminated-but-not-yet-deleted & phase is `PodRunning` case, the Pod is still in scheduler's cache, so it's handled well in scheduler; the Pod will be removed from cache when it's deleted. But in kubelet, it filtered terminated-but-not-yet-deleted out (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1783) when using scheduler.predicates.

The option in my mind is to pass all Pods (including terminated-but-not-yet-deleted) to each admin, and let each admin decide whether filter terminated-but-not-yet-deleted out.

**Comment by k82cn** [comment]
> But in kubelet, it filtered terminated-but-not-yet-deleted out (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1783) when using scheduler.predicates.

In `filterOutTerminatedPods` -> `podIsTerminated`, it already consider `terminated-but-not-yet-deleted` by `pod.DeletionTimestamp != nil && notRunning(status.ContainerStatuses)`. 

So both scheduler & kubelet handles terminated-but-not-yet-deleted pods well.

**Comment by davidopp** [comment]
Great, thanks for looking into it!

**Comment by xiang90** [comment]
@davidopp @k82cn shall this issue be closed then?

**Comment by k82cn** [comment]
I think so.

**Comment by bsalamat** [comment]
Just to clarify: Kubelet correctly accounts the resources used by terminated-but-not-yet-deleted pods, i.e, kubelet does not count the resource usage of those pods towards total usage on the node. Scheduler, however, does not do the same. Scheduler waits for a pod to be deleted, and then it deducts its resource request from the associated node total usage. Upon deletion of a pod, scheduler is notified and acts:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L262

So, scheduler and kubelet behaviors are not exactly the same. I am not sure if scheduler can receive an event when a pod's container status changes. If it could, we could make the logic the same as that of Kubelet.

**Comment by davidopp** [comment]
@bsalamat @k82cn I guess the current behavior is OK because it is conservative (scheduler considers the resources to be in use even though kubelet considers them free). And actually it seems that scheduler is more "correct" than kubelet, since the resources really aren't usable until the pod is deleted, right? (IIUC that was Vish's original point)

**Comment by bsalamat** [comment]
@davidopp I agree. The current behavior is correct, but a bit conservative. Basically, the scheduler side is more conservative and waits until a pod is deleted from the cache before considering its resources released. That said, I believe resources of terminated-but-not-deleted pods are usable on nodes (should be verified). So, the current behavior is a bit less than ideal in terms of efficiency, but AFAIK the duration between termination and deletion is only a few seconds. So, it may not be worth optimizing.

**Comment by davidopp** [comment]
>  I believe resources of terminated-but-not-deleted pods are usable on nodes

I thought @vishh was saying the opposite (see my first entry in this issue). Maybe e can clarify.
