### ISSUE TITLE
How to  add a non-namespaced scope resource into API?

### ISSUE THREAD

**Issue by fzu-huang** [kubernetes/kubernetes#47884]
I tried to add an resource named `Network` which is non-namespaced into API .
This is what I did:
Add this resource's struct into types.go and /v1/types.go.   I add two notes: `+genclient=true` and `+nonNamespaced=true` in case of create its client without namespace;
Add its storage.go, registry.go and strategy.go file into `pkg/registry/core/network`  which I created. I Changed the function `NamespaceScoped` and return `false` ;
Modify register.go  v1/registrer.go , Add my resource into function `AddKnownTypes`;
Modify `pkg/api/validation/validation.go` , ADD my resource's `validate` function;
Modify `pkg/registry/core/rest/storage_core.go` , add my resource's REST in function: `NewLegacyRESTStorage`;
Modify install.go and /v1/install.go. add my resource into `RootScopedKinds` in function `Install`.

then I run 
```
bash hack/update-codegen.sh && bash hack/update-generated-protobuf-dockerized.sh && bash hack/update-codecgen.sh
```
and there're some new generated files created, include some protbuf and client files.
I build  kube-apiserver and run successfully,  but when I try to create a Network:
````
[root@godev kubernetes]# curl -X POST http://localhost:8080/api/v1/networks -d '{"kind":"Network","apiVersion":"v1","metadata":{"name":"huangyangtestnetwork1991"},"spec":{"networkInfo":{"id":"31507cd5-1f48-4585-aebb-ebebd93ead83","ip":"10.173.32.25","mac":"fa:16:3e:c7:36:84","netType":"wan"}}}'
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server does not allow this method on the requested resource",
  "reason": "MethodNotAllowed",
  "details": {},
  "code": 405
}
````

when I use:
```
curl -X POST http://localhost:8080/api/v1/namespaces/default/networks -d '{"kind":"Network","apiVersion":"v1","metadata":{"name":"huangyangtestnetwork1991"},"spec":{"networkInfo":{"id":"31507cd5-1f48-4585-aebb-ebebd93ead83","ip":"10.173.32.25","mac":"fa:16:3e:c7:36:84","netType":"wan"}}}'
```
It created successfully, which means there must be something I missed to do to make my resource non-namespaced.  What did I miss??

**Comment by fzu-huang** [comment]
@kubernetes/sig- area/api-misc

**Comment by fzu-huang** [comment]
@kubernetes/sig-API Machinery-misc

**Comment by resouer** [comment]
It seems you are not using TPR? (which is recommended)
