### ISSUE TITLE
Make TolerateUnreadyEndpointsAnnotation beta

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#47880]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

Service. TolerateUnreadyEndpointsAnnotation.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

ref: 
- https://github.com/kubernetes/kubernetes/issues/39363
- https://github.com/kubernetes/kubernetes/issues/39207

TolerateUnreadyEndpointsAnnotation, aka `service.alpha.kubernetes.io/tolerate-unready-endpoints` annotation key, provides useful mechanism to discover pods without relying on healthiness/readiness. This is very useful and heavily wanted for stateful apps.

However, so far it is still alpha. What is the plan to make this beta?

**Comment by hongchaodeng** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by hongchaodeng** [comment]
@kubernetes/sig-network-feature-requests

**Comment by kargakis** [comment]
@kubernetes/sig-apps-feature-requests because of statefulsets

**Comment by enisoc** [comment]
ref #25283
