### ISSUE TITLE
Fine-grained control of secret data in volume

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#4789]
Currently the `SecretVolumeSource` does not allow the user to control:

1.  Which file names a piece of secret data should be presented with
2.  What permissions a piece of secret data should have

It should be possible to control both of these things.

**Comment by pmorie** [comment]
@erictune @thockin @csrwng

**Comment by pmorie** [comment]
@liggitt fyi

**Comment by derekwaynecarr** [comment]
I have a use case where a component requires 'secret' information across multiple sub-directories.

```
/secret-data/secret1/somefile
/secret-data/secret2/somefile
...
```

Both secret1 and secret2 are related, and it would be convenient to manage them as part of the same Kubernetes Secret resource.  

While I am not sure if my reaction is knee-jerk, my initial bias is that I should be able to control what sub-directories a secret key can present itself under relate to relative to the mounted directory rather than all keys being files that are immediate children of the parent directory.

**Comment by mfojtik** [comment]
I have use case where MongoDB 'keyFile' requires to have 0600 permissions, so having a mechanism to set the permissions for the file in secret will be extra useful. For now, the workaround is to copy the 'keyFile' to other location and change the permissions.

**Comment by derekwaynecarr** [comment]
For my use case requiring multiple directories, we have a work around, but I am not sure that would be possible for all other situations.  Sometimes it would be useful to have a tar as a secret value and I can ask it to be expanded prior to giving it to my container?

**Comment by soltysh** [comment]
My use case is to pass a SSH key through secret, with that I'm hitting too broad access permissions. SSH requires its key to be accessible only by the user owning those keys. Simple fix is possible, if I change in `pkg/volume/secret/secret.go` ` SetUpAt` to do `ioutil.WriteFile(hostFilePath, data, 0400)` it'll work, but just because I'm using root user. What if I'll try to user different user? There should also be possibility to define the user who will be the owner of that file, so he can safely use it, without additional hacks I'm using currently to modify those permissions.

**Comment by bgrant0607** [comment]
0400 seems like a reasonable default for secrets. 

In general, enabling permissions to be set on generated volumes (as opposed to attached or exposed volumes) would be useful.

**Comment by derekwaynecarr** [comment]
SSH keys is one example of where this is useful and almost required.

**Comment by pmorie** [comment]
Related: https://github.com/GoogleCloudPlatform/kubernetes/issues/7554

**Comment by pmorie** [comment]
As discussed in #6477, we have now solved all of the problems of validating paths.  We should refactor to an API similar to the one provided for the downward API volume.

**Comment by pmorie** [comment]
Applying the pattern from the downward API and the proposed `ConfigData` API yeilds:

```go
// SecretVolumeSource represents a volume containing ConfigData
// projected into files
type SecretVolumeSource struct {
  // A list of files containing config data in the volume.
  Items []SecretVolumeFile `json:"items,omitempty"`
}

// SecretVolumeFile represents a single file containing a Secret key
type SecretVolumeFile struct {
  // A reference to the secret key to project
  SecretKeySelector `json:",inline"`
  // Path is the relative path name of the file to be created.
  // Must not be absolute or contain the '..' path.
  // Must be utf-8 encoded.
  // The first item of the relative path must not start with '..'
  Path string `json:"path"`
}

// SecretKeySelector selects a key of a Secret.
//
// This mirrors the ConfigDataSelector type in the proposed ConfigData API
type SecretKeySelector struct {
  // The name of the secret in the pod's namespace to select from.
  SecretName string `json:"secretName"`
  // The key of the secret to select from.  Must be a valid secret key.
  Key string `json:"key"`
}
```

How do people feel about that?  Ultimately, we need this API to mirror what we do for #17554.

cc @deads2k @liggitt

**Comment by soltysh** [comment]
:+1: that should perfectly satisfy what I was looking for, at the same time being a better solution to what I proposed in #7908.

**Comment by pmorie** [comment]
@soltysh Yeah, the devil's in the details, though.  We will need policy to determine what users can specify for UID and GID at least, as well as probably for the mode field.

**Comment by pmorie** [comment]
@pweil- new policy touchpoint

**Comment by deads2k** [comment]
`SecretKeySelector.SecretName` feels a lot like a `LocalObjectReference`

**Comment by deads2k** [comment]
`FileInfo` seems like something that should have some reasonable default behavior.  What do you as a reasonable default?

**Comment by deads2k** [comment]
> @pweil- new policy touchpoint

Inspecting the actual data inside of an API object would really have to be done with an admission controller that runs after defaulting.  See https://github.com/kubernetes/kubernetes/issues/17549 and https://github.com/kubernetes/kubernetes/issues/17637 for details

**Comment by pmorie** [comment]
@deads2k What aspect of file info did you have in mind?

Being more explicit about the semantics, I think the presence of a `FileInfo` is an override for the placement of the data for a single secret key.  So, the default behavior of a secret volume with no such objects would be the existing behavior.

**Comment by rata** [comment]
Hi, is someone working on this? I opened another issue (https://github.com/kubernetes/kubernetes/issues/28317) that is quite similar, although I was planning to extend it for configmaps too (as was requested there).

If someone is working on this, can we coordinate to not step over each other?

**Comment by rata** [comment]
This can be closed, as the first one is implemented via "items" in the volume and the second via the "defaultMode" on the volume or "mode" in items. And both present in a released k8s version (in 1.4 is the first version with both).

Thanks!

**Comment by wernight** [comment]
The [`defaultMode`](http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_secretvolumesource) and `items.mode`) seem good but they are OR'ed with something (possibly somehow [`fsGroup`](http://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/#_v1_podsecuritycontext)) and as a result 0400 gets transformed into 420.

Editing (`kubectl edit ...`) does fix it, but doing an apply (`kubectl apply ...`) changes 0400 into 420, so `-r-----` gets changed into `-rw-r--r--`. I don't see clearly from the documentation how to force 0400 as I've not set any `fsGroup`.

**Comment by wernight** [comment]
Doing a `kubectl apply -f ...` **twice** also works. Note that normally the only thing that chances is the `image`. Even if done one right after the other.

**Comment by rata** [comment]
@wernight using a kubectl from 1.4 release (previous releases don't have this feature) fixes that, as reported in https://github.com/kubernetes/kubernetes/issues/34445 ?

**Comment by wernight** [comment]
Yes, upgrading the client fixes that.

**Comment by zamai** [comment]
spec:
      volumes:
      - name: config-volume
        secret:
          defaultMode: **0400**
Adding 0400 mode worked for me!

**Comment by rdxmb** [comment]
> There should also be possibility to define the user who will be the owner of that file, so he can safely use it, without additional hacks I'm using currently to modify those permissions.

Is there a solution for that?
