### ISSUE TITLE
httpGet in readiness and liveness probes fails on status > 200 and < 400

### ISSUE THREAD

**Issue by egeland** [kubernetes/kubernetes#47893]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): httpGet

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T20:41:24Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): `PRETTY_NAME="Debian GNU/Linux 8 (jessie)"`
- **Kernel** (e.g. `uname -a`): `Linux ip-10-44-40-175 4.4.65-k8s #1 SMP Tue May 2 15:48:24 UTC 2017 x86_64 GNU/Linux`
- **Install tools**: `kops`
- **Others**:

**What happened**:
A readiness probe getting a `302` error code causes the pod to be not be marked Ready.
A liveness probe getting a `302` error code causes the pod to be killed.

**What you expected to happen**:
As per the [documentation](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/):
> Any code greater than or equal to 200 and less than 400 indicates success. Any other code indicates failure.

**How to reproduce it** (as minimally and precisely as possible):
Create a deployment of an app that returns `302` HTTP status code, rather than `200`.
Add a readiness probe. Watch it fail to mark the pod as ready.
Add a liveness probe. Watch it kill the pod.

**Anything else we need to know**:
The expected behaviour is documented in at least two places, https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ and https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/

**Comment by resouer** [comment]
I checked thru the code: https://github.com/kubernetes/kubernetes/blob/master/pkg/probe/http/http.go#L86-L88 which seems no problem. 

How did you know the app returns 302 may I ask?

**Comment by egeland** [comment]
That's the behaviour we observed.
Let me gather some logs, to confirm.

**Comment by tfuentes** [comment]
I have have the same problem. My kubernetes is running in a GCE. Cluster and nodes have v1.6.4. Pods are Debian. 

Any updates?

**Comment by Fizzadar** [comment]
We are also seeing this issue, our uwsgi app is returning a 302 to the check and then being immediately nuked:

```
[pid: 7|app: 0|req: 1/1] 10.15.77.1 () {26 vars in 315 bytes} [Mon Jul 17 15:21:08 2017] GET /health => generated 381 bytes in 1 msecs (HTTP/1.1 302) 4 headers in 214 bytes (1 switches on core 0)
[pid: 9|app: 0|req: 1/2] 10.15.77.1 () {26 vars in 315 bytes} [Mon Jul 17 15:21:08 2017] GET /health => generated 381 bytes in 1 msecs (HTTP/1.1 302) 4 headers in 214 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
```

**Comment by froy001** [comment]
I ran into the same issue. Kubernetes on GCP.

**Kubernetes version:**
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5-gke.0", GitCommit:"2c2a807131fa8708abc92f3513fe167126c8cce5", GitTreeState:"clean", BuildDate:"2017-12-19T20:05:45Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}

**description:**
Running a wordpress deployment all works well. Since response code is 200.
```
10.12.4.1 - - [02/Feb/2018:13:12:54 +0000] "GET / HTTP/1.1" 200 23603 "-" "kube-probe/1.8+"
10.12.4.1 - - [02/Feb/2018:13:13:04 +0000] "GET / HTTP/1.1" 200 23603 "-" "kube-probe/1.8+"
10.12.4.1 - - [02/Feb/2018:13:13:14 +0000] "GET / HTTP/1.1" 200 23603 "-" "kube-probe/1.8+"
```
adding a localization plugins, which returns 301 or 302 triggers the readiness probe failure and cutting off traffic to the pod. 

```
10.12.4.1 - - [02/Feb/2018:13:20:14 +0000] "GET / HTTP/1.1" 302 253 "http://10.12.4.54:80/" "kube-probe/1.8+"
10.12.4.1 - - [02/Feb/2018:13:20:24 +0000] "GET / HTTP/1.1" 301 236 "-" "kube-probe/1.8+"
10.12.4.1 - - [02/Feb/2018:13:20:24 +0000] "GET / HTTP/1.1" 302 253 "http://10.12.4.54:80/" "kube-probe/1.8+"
```
When setting the readiness probe to periodSeconds: 500000 the site works.

**Comment by egeland** [comment]
/reopen

As far as I know, this is still a problem.

**Comment by ekapratama93** [comment]
Get the same error with NodeJS app with express-force-ssl

**Comment by Pega88** [comment]
same here with an apache server with .htaccess redirect

**Comment by dims** [comment]
Anyone wanna try this patch and let us know? http://paste.openstack.org/raw/723022/

**Comment by rbtcollins** [comment]
My question is, what are the semantics of a redirect here?
Is it ; "the health of the resource is the health of the url redirected to", or is it "the health of the resource is the response to the probe HTTP request".

e.g. should we follow HTTP redirects *at all* - and I would argue that we shouldn't.

**Comment by frizner** [comment]
The same issue with Solr

**Comment by thockin** [comment]
Are the redirects being used actually valid?  They should be followed.

**Comment by thockin** [comment]
Anyone having this problem, can you crank up Kubelet logs to --v=4 and look for "Probe succeeded for" or "Probe failed for" lines?

**Comment by thockin** [comment]
Please see https://github.com/kubernetes/kubernetes/issues/73172#issuecomment-472499665 - we do follow redirects and I can prove it.  Whether that is correct or not is TBD.  Closing this, please followup there.
