### ISSUE TITLE
Support vnet Load Balancer in different resourge group

### ISSUE THREAD

**Issue by VioletRainbows** [kubernetes/kubernetes#47913]
#**Feature request**
The goal is to be able to add a vnet in a different resource group when creating a load balancer. Currently, the Kubernetes Azure cloudprovider only works with the resource name and not the full ID when assigning a vnet to a load balancer.

**Use case**
The security team that handles vnet configuration does not work in the same resource group as the infra team.

**Example implementation**
https://github.com/VioletRainbows/kubernetes/commit/bc10971c11ee2dc732a8e3455f5e16e4f61de988

@brendandburns @colemickens

**Comment by titilambert** [comment]
Related to:
* https://github.com/kubernetes/kubernetes/issues/49577
* https://github.com/kubernetes/kubernetes/pull/49725

**Comment by VioletRainbows** [comment]
Fixed #49725
