### ISSUE TITLE
CertificateSigningRequest.Get: Status.Certificate is nil for approved CSR.

### ISSUE THREAD

**Issue by mberhault** [kubernetes/kubernetes#47911]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): no

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): "empty certificate", "empty csr", then expanded to looking at all issues with "certicate signing request" and a few others.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"dirty", BuildDate:"2017-06-22T04:31:09Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: minikube on osx
- **OS** (e.g. from /etc/os-release): `OSX 10.12.4`
- **Kernel** (e.g. `uname -a`): `Darwin brewer.lan 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64`
- **Install tools**:
- **Others**:

**What happened**:
(see `How to reproduce it` for exact steps/output)
I have an init container (see init-certs in the [config](https://raw.githubusercontent.com/cockroachdb/cockroach/master/cloud/kubernetes/cockroachdb-statefulset-secure.yaml), code [here](https://github.com/cockroachdb/k8s/tree/master/request-cert)) that requests a certificate through the Certificates api.

The CSR is properly created and shows up in `kubectl get csr`.
Once I approve the CSR (`kubectl certificate approve ...`, the status field of the `CertificateSigningRequest.Get` has the right `CertificateApproved` condition, but the `Certificate` field is nil.

**What you expected to happen**:

The certificate field should not be nil.
I've seen proper behavior on GCE. I've encountered this problem both on Azure and minikube (minikube details attached here, it's easier to iterate on).

**How to reproduce it** (as minimally and precisely as possible):
* start minikube
* create cluster: `kubectl create -f https://raw.githubusercontent.com/cockroachdb/cockroach/master/cloud/kubernetes/cockroachdb-statefulset-secure.yaml`
* the following pod and CSR should be created:
```
$ kubectl get all && kubectl get csr
NAME               READY     STATUS     RESTARTS   AGE
po/cockroachdb-0   0/1       Init:1/2   1          5m

NAME                     CLUSTER-IP   EXTERNAL-IP   PORT(S)              AGE
svc/cockroachdb          None         <none>        26257/TCP,8080/TCP   5m
svc/cockroachdb-public   10.0.0.204   <none>        26257/TCP,8080/TCP   5m
svc/kubernetes           10.0.0.1     <none>        443/TCP              2h

NAME                       DESIRED   CURRENT   AGE
statefulsets/cockroachdb   3         0         5m
NAME                 AGE       REQUESTOR                               CONDITION
node-cockroachdb-0   48s       system:serviceaccount:default:default   Pending
```
* approve the CSR: `kubectl certificate approve node-cockroachdb-0`
* inspect the approved CSR:
```
$ kubectl get csr node-cockroachdb-0 -o json
{
    "apiVersion": "certificates.k8s.io/v1beta1",
    "kind": "CertificateSigningRequest",
    "metadata": {
        "creationTimestamp": "2017-06-22T16:03:25Z",
        "name": "node-cockroachdb-0",
        "resourceVersion": "10335",
        "selfLink": "/apis/certificates.k8s.io/v1beta1/certificatesigningrequestsnode-cockroachdb-0",
        "uid": "52f9b4f9-5764-11e7-8447-0800279e07ef"
    },
    "spec": {
        "groups": [
            "system:serviceaccounts",
            "system:serviceaccounts:default",
            "system:authenticated"
        ],
        "request": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQzVEQ0NBY3dDQVFBd0l6RVNNQkFHQTFVRUNoTUpRMjlqYTNKdllXTm9NUTB3Q3dZRFZRUURFd1J1YjJSbApNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXJOcGJCNGtBeHhON2JNVVVQMGtpCmtNY0R2cTVuN3I5Ry9VQ1FOOHlIbDVOa1lnTEJzWmdHOCtkQUM0bnAxZTlKRXVZdVA5bnZQK2ZkZVhXc1BEUzAKMDlnL3A1MjlseThVcDNhUXRrMHJ6SDVpdHo4KzRHbFAzWDdXS2ZDdnVuTUVia245SU00THNSeFcxa0s5a1FVcwpGcjN0VnUyRnlxZGpmM3JQdU1RZ29Wb3VqNy8yT1NJYWxOZStOTWg1T3VvaHpFR1Izb1E5WmVWMktiUFBKOUhRCjJiY1NNcWNWZmpEUlZ4RUtvelFZRWNjdjJPcE44UEt3ZEszZzBzdzJoOWxtVU11WldONjk1S2d6UXFZMHV3cHMKdHZOTUFvK2x0OS9KbHlTd1U4NExpUnRIRDExZk90dElKaVhEY1pzUW96SytVT2lPR2hkMFZGeUtzN05Uby9uSQpId0lEQVFBQm9Id3dlZ1lKS29aSWh2Y05BUWtPTVcwd2F6QnBCZ05WSFJFRVlqQmdnZ2xzYjJOaGJHaHZjM1NDCk0yTnZZMnR5YjJGamFHUmlMVEF1WTI5amEzSnZZV05vWkdJdVpHVm1ZWFZzZEM1emRtTXVZMngxYzNSbGNpNXMKYjJOaGJJSVNZMjlqYTNKdllXTm9aR0l0Y0hWaWJHbGpod1IvQUFBQmh3U3NFUUFFTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQUlmN1R3d3YzcUx4RTBDaE15dGdSb2JtUDZmY204QWlGYUpwNENzVmx2QjRqS3ZVYXVJUldGCitmejhRelRDVHFNTmpmUitualpSbWRTcnE1ZWtSdjBXODJodG9HR3dHbTk3VTAwTEozdElyV1pRZi91c3ExTEUKVzBHcC9kSnR0ZmpsWSswMWd3RzhKbnBKZzBiNktiaXcxYzJiSzR0TXorU2swRjgvcGdaMTJGZVVGL0FNL0didgovNTJlR09uR1Zxdm5oWEVmVm1KcTlBZ2dvTXpGMWJVbXdGd1NUSzhBcTZqKy9MMVNpMUNmR1IrbFVncWVMaFp0CnBaelJLQVpUWHd0TFNXbDIxNzIzY0o2Y282bjVrQ2Vqcko2WURtSG9ucUFNOTlJd2I2ZTdKUFJnZzl0OHFLbDMKY3pJTWkvK2NyK2lNUC9vV2h6d2ZmZVZVZ0NNUURpMjcKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==",
        "uid": "c1c0a394-5750-11e7-9121-0800279e07ef",
        "usages": [
            "digital signature",
            "key encipherment",
            "client auth",
            "server auth"
        ],
        "username": "system:serviceaccount:default:default"
    },
    "status": {
        "conditions": [
            {
                "lastUpdateTime": "2017-06-22T16:04:38Z",
                "message": "This CSR was approved by kubectl certificate approve.",
                "reason": "KubectlApprove",
                "type": "Approved"
            }
        ]
    }
}
```

The `status` field should also contain a `certificate` field which has the raw generated certificate bytes.

**Anything else we need to know**:

**Comment by mberhault** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by mberhault** [comment]
BTW, the [API docs](https://kubernetes.io/docs/api-reference/v1.6/#certificatesigningrequeststatus-v1beta1-certificates) clearly say:
```
certificate      If request was approved, the controller will place the
string	         issued certificate here.
```

**Comment by pipejakob** [comment]
CC @mikedanese

**Comment by pipejakob** [comment]
After chatting on Slack, it seems that the issue here is that minikube wasn't starting the certificates controller, which is required for auto-signing approved CSRs. This can be enabled by the user through configuration, but is defaulted off. Since the Certificates API is now in Beta, it probably makes sense to default the certificates controller on, but in either case, this is a minikube issue, not API machinery.

**Comment by mberhault** [comment]
This is due to the cluster being starting without the certificates controller enabled. I've moved this issue to https://github.com/kubernetes/minikube/issues/1647 to have minikube start it up by default.

Closing this. Thank you for the help.
