### ISSUE TITLE
e2e versioned build artifact with same tags as everything else.  

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#47920]
**Is this a REQUEST?**:

Currently there is not a properly versioned build artifact that is created from the upstream release process that contains the e2e tests and associated tooling (kubectl).  

**Kubernetes version** (use `kubectl version`):

ALL

**What happened**:
Tried to find a well versioned e2e container for the release, and there is none that isn't tied into the test-infra or has some gcloud bindings built in.  

/cc @kubernetes/sig-release-feature-requests @kubernetes/test-infra-maintainers @dchen1107

**Comment by dchen1107** [comment]
@pwittrock I couldn't find any information / document related to this, and not sure how we handle it in previous release. But we need to figure out how to do this. Thanks!

**Comment by ixdy** [comment]
It's not really bundled, but for a given "official" version you can browse `gs://kubernetes-release/release/$version` (e.g. http://gcsweb.k8s.io/gcs/kubernetes-release/release/v1.6.6 for v1.6.6) and find all of the binary artifacts (including kubectl and e2e tests) there.

If you download `kubernetes.tar.gz` from here and extract it, and then run `kubernetes/cluster/get-kube-binaries.sh`, it'll download & extract all of the correct client/server binaries. If you set `KUBERNETES_DOWNLOAD_TESTS` to nonempty it'll also download the test binaries.

**Comment by ixdy** [comment]
but no, there isn't a `gcr.io/google-containers/kubernetes-e2e:v1.6.6` which would run correctly versioned tests or anything like that.

**Comment by timothysc** [comment]
@ixdy that really needs to be a thing as cluster "Conformance" testing is growing in importance, and will become a imperative in the near future.  

I'd gladly pitch in here, but I can't push to gcr.io.  

/cc @jbeda

**Comment by ixdy** [comment]
@fejta thoughts on how kubetest can help here?

**Comment by timothysc** [comment]
So discussion on release-call was that we should still produce a container b/c this will be an issue for conformance efforts, but it doesn't need to be for this release cycle 1.7.0, but it can be for 1.7.1+

**Comment by zmerlynn** [comment]
I'm not clear why it was closed, but c.f. https://github.com/kubernetes/kubernetes/issues/3013. Unless that's been fixed, our test binaries can't be isolated from k8s binaries.

**Comment by timothysc** [comment]
I want to make certain this isn't lost as the 1.7 series continues on.  

From tracing through `quick-release` I think the path that makes the most sense is to leverage the hyper-kube container build and add a target for e2e.

**Comment by ixdy** [comment]
how would this interact with `kubetest`?

**Comment by timothysc** [comment]
It could either be separate, or it's possible it could be the FROM image:sha for the test-infra containers.

**Comment by timothysc** [comment]
So I created my own and just moved on, but it's clear upstream should be the source, but there are a lot of weird suppositions in the tests that should be factored out, I'll start to create some PRs on those.

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/lifecycle frozen
This would still be useful for downstream.  It bugs me that we need to rely on a third-party tool that lags us in order to certify kubernetes distros as conformant for a given release
