### ISSUE TITLE
Kubelet & heapster extremely high disk i/o (reads)

### ISSUE THREAD

**Issue by weaseal** [kubernetes/kubernetes#47928]
![screenshot_2017-06-22_14-20-03](https://user-images.githubusercontent.com/5624010/27456975-d3d1fbee-5757-11e7-9766-1304e1022dfb.png)

**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kubelet high io

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug

**Kubernetes version** (use `kubectl version`): 1.5.3

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CentOS 7
- **Kernel** (e.g. `uname -a`): 3.10.0-514.21.2.el7.x86_64
- **Install tools**: kops 1.5.3
- **Others**:

**What happened**:
During heavy load, the kubernetes worker nodes enter a state of high disk IO and never exit that state, even after load completes.  This can/has happen to multiple worker nodes simultaneously and cause an outage.  Kubelet appears to be the primary offender.  As the node never recovers from this high IO state, debugging becomes difficult.  The node can only be accessed after rebooting.

I believe this is related to the issue that is described starting with comments AFTER this issue was closed: https://github.com/kubernetes/kubernetes/issues/23255 (March 22 onward)

**What you expected to happen**:
Disk IO to return to normal levels after load completes rather than permanently locking the node.

**How to reproduce it** (as minimally and precisely as possible):
I use jmeter to create a high degree of requests to my app.

**Anything else we need to know**:
When you're out of jam, bananas make a great substitute for a PBJ (PBB?) sandwich.

**Comment by yudiandreanp** [comment]
Any updates on this?

**Comment by enver** [comment]
Any update/workaround on this?

**Comment by dannolan** [comment]
Any updates on this?

**Comment by weaseal** [comment]
We mostly found this was a symptom of memory pressure on the host systems.  See here for resolutions https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/

**Comment by veerendra2** [comment]
I see similar issue in K8s `v1.11.2` installed with `kubeadm` on CentOS 7. 

https://stackoverflow.com/questions/51988566/high-number-of-disk-reads-in-kubernetes-nodes

**Comment by lesomnus** [comment]
I had a similar symptom and arrived here.
As @weaseal said, it was caused by the lack of memory capacity of the master, and the problem was solved by increasing the memory size.
The solution was too obvious, but I overlooked it.
