### ISSUE TITLE
kube-controller-manager needs to support multiple CIDRs

### ISSUE THREAD

**Issue by rpothier** [kubernetes/kubernetes#47924]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):
No
**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

kube-controller-manager currently supports --cluster-cidr and --node-cidr-mask-size
For IPv6, these arguments need to be made plural.
Multiple IP addresses are needed for the dual stack case, where IPv4 and IPv6 are used,
also for IPv6 only multiple V6 addresses may be used.

**Kubernetes version** (use `kubectl version`):
latest

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by k82cn** [comment]
/cc 

we have similar requirements; does anyone work on this?

**Comment by thockin** [comment]
Really, controller manager should not be doing this.  It should be some sort of IPAM controller that understands the nature of multiple networks.

**Comment by thockin** [comment]
see #57130
