### ISSUE TITLE
CRI: Handle infra container oom score adj in a runtime agnostic way

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#47938]
https://github.com/kubernetes/kubernetes/blob/886e04f1fffbb04faf8a9f9ee141143b2684ae68/pkg/kubelet/qos/policy.go#L29

Does kubelet care about whether the infra container oom adj is `-998` or not? (seems so)
Should this be part of node spec?
Should runtime decide the oom score?
Should we add an interface to pass some configuration to runtime in CRI?

@yujuhong @feiskyer @mrunalp @vishh

**Comment by mrunalp** [comment]
@Random-Liu The kubelet doesn't want the pod infra container to get killed so I think it makes sense that this gets sent as part of sandbox config over CRI. If the runtime spawns an infra container then it could use this value and if it doesn't then it can ignore it.

**Comment by yujuhong** [comment]
> @Random-Liu The kubelet doesn't want the pod infra container to get killed so I think it makes sense that this gets sent as part of sandbox config over CRI. If the runtime spawns an infra container then it could use this value and if it doesn't then it can ignore it.

SGTM

**Comment by yujuhong** [comment]
Hmm..for VM pods, we probably want to adjust the oom scores based on QoS class of the pod.

**Comment by vishh** [comment]
> Should this be part of node spec?

Infra container is a runtime artifact right? Why would it be part of the Node (distro) Spec?

> Should runtime decide the oom score?

Depends. As mentioned above, if kubelet decides to run an infra container across all runtimes, say for purposes of sharing all namespaces consistently, or providing exec/logs access consistently, etc., then kubelet has to decide the oom score. If it's the runtime that's managing an infra container, then the runtime can manage it.

> Should we add an interface to pass some configuration to runtime in CRI?

Depends on the long term as mentioned above. I see value in standardizing the infra container across all runtimes and providing centralized functionalities.
