### ISSUE TITLE
Lower etcd compacted logs frequency

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes/kubernetes#47941]
When we run apiserver, it will consistently produce logs like:

> I0620 15:27:44.627978 2765 compact.go:159] etcd: compacted rev (7825), endpoints ([http://127.0.0.1:2379])
I0620 15:32:44.632311 2765 compact.go:159] etcd: compacted rev (8193), endpoints ([http://127.0.0.1:2379])
I0620 15:37:44.643658 2765 compact.go:159] etcd: compacted rev (8552), endpoints ([http://127.0.0.1:2379])
...

which does not mean much overall, we may change the loglevel and lower the frequency.

**Comment by deads2k** [comment]
> (1) mentioning a sig: @kubernetes/sig-<team-name>-misc
> e.g., @kubernetes/sig-api-machinery-misc for API Machinery

@eparis @smarterclayton @lavalamp @apelisse @fejta This message from the bot is spamming me with every issue that gets opened without a sig and assigning them to api-machinery.  Granted, I *am* the center the universe, but can we get an updated message that won't do this?

**Comment by apelisse** [comment]
@crimsonfaith91 is working on this.

**Comment by crimsonfaith91** [comment]
@deads2k The reason behind is there is no quote for `@kubernetes/sig-api-machinery-misc`. I will create a PR to quote it.

**Comment by crimsonfaith91** [comment]
@deads2k The change is merged, but we still need permission from @cjwagner for deployment.
