### ISSUE TITLE
k8s garbage collector not working caused by 'cfq'

### ISSUE THREAD

**Issue by nils2504** [kubernetes/kubernetes#47949]
**BUG REPORT**:

> /kind bug

**What happened**:
Kubernetes nodes doesn't have any space left on disk and cluster gets stuck.
Garbage Collector doesn't clean up old docker images.

**What you expected to happen**:
garbage Collector should clean up unused docker images.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Running docker cleanup on images deletes about 150 Images with a whole size of 5GB.

Running cAdvisor /validate shows following message:
```
 None of the devices support 'cfq' I/O scheduler. No disk stats can be reported.
     Disk "xvda" Scheduler type "none".
```
Running `journalctl -u kubelet | grep -i `garbage`

`Jun 20 14:35:21 ip-172-21-4-239 kubelet[1551]: E0620 14:35:21.986898    1551 kubelet.go:1165] Image garbage collection failed: unable to find data for container /`

**Environment**:
- Kubernetes v1.6.4
- Running on AWS deployed with kops 1.6.1
- Debian (kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02)
- Kernel 4.4.65-k8s

@kubernetes/sig-node-bugs

**Comment by wangycc** [comment]
+1 
serious problem
