### ISSUE TITLE
http2-based scale test failure

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#47954]
Last kubemark-scale [test](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/482) failed with an error:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/perf/density.go:771
Expected error:
    <*url.Error | 0xc4a3cfc240>: {
        Op: "Get",
        URL: "https://104.154.194.87/api/v1/namespaces/e2e-tests-density-30-23-wzf41/replicationcontrollers/density-latency-pod-1922",
        Err: {
            s: "http2: no cached connection was available",
        },
    }
    Get https://104.154.194.87/api/v1/namespaces/e2e-tests-density-30-23-wzf41/replicationcontrollers/density-latency-pod-1922: http2: no cached connection was available
not to have occurred
```

We make test more resilient to such errors, but first I'd like to know if we should (i.e. do we expect such errors to occur). @kubernetes/sig-api-machinery-misc @timothysc @smarterclayton @kubernetes/sig-scalability-misc

**Comment by timothysc** [comment]
This sounds exactly like: https://github.com/kubernetes/kubernetes/issues/33557 , where we had too many connections per client.

**Comment by smarterclayton** [comment]
Is this a "retryable" error?  Our "retry on temporary error" logic is
old and tattered and needs to be improved - using the new interface in
Go for temporary errors might have handled this as well.
