### ISSUE TITLE
admission/v1alpha1 API should be moved to k8s.io/api

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#47972]
People writing webhook admission controllers needs import the types.

@lavalamp @whitlockjc WDYT?

**Comment by whitlockjc** [comment]
I'm still learning the rules around API group locations and such.  I defer to @lavalamp.

**Comment by smarterclayton** [comment]
Is there a reason not to move them?

**Comment by caesarxuchao** [comment]
This is not a deal breaker, but i'd like to point out that so far all the types in k8s.io/api are actually served by the kube-apiserver, but the apiserver does not serve admissionReviews.

**Comment by smarterclayton** [comment]
The default OOTB doesn't, but service catalog or another could very well.

**Comment by caesarxuchao** [comment]
Do you mean the service catalog extension apiserver will serve the admission API?

**Comment by smarterclayton** [comment]
Yes, it could implement admission controllers that are registered with the
master at the same time the service catalog is added to the aggregate API.

**Comment by caesarxuchao** [comment]
Ok. I'll move the API group.

**Comment by lavalamp** [comment]
I am not sure how that will work in practice, since the webhook location doesn't depend on the object under admission (maybe we should change that).

But it doesn't really matter, the k8s.io/api repo is a better place than the main kubernetes repo.

**Comment by smarterclayton** [comment]
I'm expecting to have endpoints like /admission/hook/* for servers
that process a wide range of chains.  I don't think there's much
coupling between a resource and the URL of the processing webhooks,
but it's an API clients will want to write to and servers will want to
respond to outside of apiserver.
