### ISSUE TITLE
"should not provision a volume in an unmanaged GCE zone" test can be sped up

### ISSUE THREAD

**Issue by wongma7** [kubernetes/kubernetes#47970]
This is not very high priority but @copejon @jeffvance I think a faster way to do this test instead of waiting for PVC to timeout is watch for a ProvisioningFailed event on the PVC and check that its reason is ~"invalid zone."~ "kubernetes does not manage zone" Happy to work on a PR at some point if you guys agree

**Comment by copejon** [comment]
@wongma7 Sounds good!  Shortening run times for e2e is always a good idea.  Let me know if you have any questions.
