### ISSUE TITLE
Invalid value error when creating service from exported config

### ISSUE THREAD

**Issue by WilliamDenniss** [kubernetes/kubernetes#47976]
/kind bug

**What happened**:
`kubectl get -o yaml --export` on a Service includes fields that shouldn't be exported.

**What you expected to happen**:
Resources exported with `kubectl get -o yaml --export` should be creatable without errors.

**How to reproduce it (as minimally and precisely as possible)**:
NB. Derived from https://cloud.google.com/container-engine/docs/quickstart
```
kubectl run hello-node --image=gcr.io/google-samples/node-hello:1.0 --port=8080
kubectl expose deployment hello-node --type="LoadBalancer"
kubectl get deployment hello-node -o yaml --export > deployment.yaml
kubectl get service hello-node -o yaml --export > service.yaml
kubectl delete svc,deployment hello-node
kubectl create -f deployment.yaml
kubectl create -f service.yaml
```

**Anything else we need to know?**:
Error when running the last command: `The Service "hello-node" is invalid: spec.clusterIP: Invalid value: "<unknown>": must be empty, 'None', or a valid IP address`

Contents of the exported service config:
```
$ cat service.yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: hello-node
  name: hello-node
  selfLink: /api/v1/namespaces//services/hello-node
spec:
  clusterIP: <unknown>
  ports:
  - nodePort: 31668
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: hello-node
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

The `clusterIP` field is causing the error, it should be omitted when exporting config.

Exposing with --dry-run=true yields the following config:

```
$ kubectl expose deployment hello-node --type="LoadBalancer" --dry-run=true -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: hello-node
  name: hello-node
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: hello-node
  type: LoadBalancer
status:
  loadBalancer: {}
```

Notably, clusterIP and nodePort are not present. My expectation is that the `--export config` would be closer to (or even equal to) the `--dry-run=true` output.

**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration**: GKE
- OS (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- Kernel (e.g. `uname -a`): Linux hello-node-3056736656-24pv9 4.4.35+ #1 SMP Wed Apr 5 13:00:57 PDT 2017 x86_64 GNU/Linux

**Comment by xiangpengzhao** [comment]
See: https://github.com/kubernetes/kubernetes/issues/28551

**Comment by xiangpengzhao** [comment]
See: https://github.com/kubernetes/kubernetes/issues/28551

**Comment by mkumatag** [comment]
I feel same as https://github.com/kubernetes/kubernetes/issues/28548

**Comment by WilliamDenniss** [comment]
Looks like this is a regression that was introduced in this commit: https://github.com/kubernetes/kubernetes/pull/22285/files#diff-a7196c94eb0ca7d377b6daf05d2b37cfL93

**Comment by zjj2wry** [comment]
@smarterclayton 
```
// this function aims to check if the service's ClusterIP is set or not
// the objective is not to perform validation here
func IsServiceIPSet(service *api.Service) bool {
	return service.Spec.ClusterIP != api.ClusterIPNone && service.Spec.ClusterIP != ""
}
``` 
this func prevent create 、update service.  should we update  <unknow> back to "" ?

**Comment by pwittrock** [comment]
@adohe Looks like you are the author of the referenced commit.  Is this something you would be able to own?

**Comment by shiywang** [comment]
@pwittrock I think @zjj2wry just made a pr to address that, it lgtm, but I'm not sure if @smarterclayton has some concern here, since he said in [commit](https://github.com/kubernetes/kubernetes/pull/22285/files#diff-a7196c94eb0ca7d377b6daf05d2b37cfL93)

> This prevents the exported resource from being created on another cluster, which defeats the purpose of export.

**Comment by zjj2wry** [comment]
@smarterclayton feel free close my PR if this on purpose

**Comment by mengqiy** [comment]
> This prevents the exported resource from being created on another cluster, which defeats the purpose of export.

I think this means the change is not good.

Link the potential fix here https://github.com/kubernetes/kubernetes/pull/52009

**Comment by pwittrock** [comment]
@mengqiy Would you verify the fix and close the issue if it is resolved?

**Comment by mengqiy** [comment]
Verified.
Closing.

**Comment by pwittrock** [comment]
Woot.  Thanks.
