### ISSUE TITLE
failure 1.5->1.7  EmptyDir wrapper volumes should not cause {problems}

### ISSUE THREAD

**Issue by monopole** [kubernetes/kubernetes#47988]
[gubernator](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-gci-1-7-upgrade-master/65#k8sio-emptydir-wrapper-volumes-should-not-cause-race-condition-when-used-for-configmaps-serial-slow) [grid](https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-cvm-1-5-gci-1-7-upgrade-master&width=5&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20EmptyDir%5C%20wrapper%5C%20volumes%5C%20should%5C%20not%5C%20cause%5C%20race%5C%20condition%5C%20when%5C%20used%5C%20for%5C%20configmaps%5C%20%5C%5BSerial%5C%5D%5C%20%5C%5BSlow%5C%5D)

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/empty_dir_wrapper.go:161
Test Panicked
/usr/local/go/src/runtime/panic.go:458
```

**Comment by monopole** [comment]
see also [gubernator](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-cvm-1-7-upgrade-master/68#k8sio-emptydir-wrapper-volumes-should-not-cause-race-condition-when-used-for-configmaps-serial-slow)

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/empty_dir_wrapper.go:161
Failed waiting for pod wrapped-volume-race-cfaedb90-5828-11e7-9b42-0a580a3c0ad4-1n0vd to enter running state
Expected error:
    <*errors.errorString | 0xc420458c30>: {
        s: "pod ran to completion",
    }
    pod ran to completion
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/empty_dir_wrapper.go:383
```

**Comment by monopole** [comment]
Given [this](https://github.com/kubernetes/kubernetes/commit/8ff00d17d82832422d428d4b39d8282378403216), @ivan4th can you comment on this please?

**Comment by monopole** [comment]
See also [EmptyDir wrapper volumes should not cause race condition when used for git_repo](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-gci-1-7-upgrade-master/65#k8sio-emptydir-wrapper-volumes-should-not-cause-race-condition-when-used-for-git_repo-serial-slow)

**Comment by dchen1107** [comment]
cc/ @verult please triage this. Thanks!

**Comment by msau42** [comment]
What versions of the e2e tests are run after the upgrade test?  Is it the 1.5 version of the test or the 1.7 version of the test?

**Comment by msau42** [comment]
I suspect that the UpgradeTest failing in this suite is also causing this test to fail.  The test was passing when the UpgradeTest was passing.

**Comment by spiffxp** [comment]
/close
This has aged out, we no longer test 1.5
