### ISSUE TITLE
Proxy version v1 should proxy logs on node [Conformance] 1.6->1.7 Upgrade Failure

### ISSUE THREAD

**Issue by monopole** [kubernetes/kubernetes#47985]
[gubernator](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-6-gci-1-7-upgrade-master/41#k8sio-proxy-version-v1-should-proxy-logs-on-node-conformance)

[history](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-gci-upgrade-master&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Proxy%5C%20version%5C%20v1%5C%20should%5C%20proxy%5C%20logs%5C%20on%5C%20node%5C%20%5C%5BConformance%5C%5D)

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:120
Jun 23 16:43:30.251: All nodes should be ready after test, Not ready nodes: ", gke-bootstrap-e2e-default-pool-2dfacab3-s32n"
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:335from junit_01.xml
```

/assign @liggitt

**Comment by spiffxp** [comment]
/sig network
because proxy (unsure if this is the right sig)

**Comment by cmluciano** [comment]
cc @nicksardo Do this have anything to do with the fixes you have been working on?

**Comment by nicksardo** [comment]
My changes were ingress specific for when the apiserver is unavailable after disruption (what's happening here).

**Comment by cmluciano** [comment]
The history looks to be green for the referenced test. Everything look good from your point @monopole ?
