### ISSUE TITLE
Kubernetes map docker exposed ports to random ports

### ISSUE THREAD

**Issue by killy001** [kubernetes/kubernetes#48020]
In Kubernetes, if I want to enable the docker host port mapping, I have to write the hostPort explicitly in the yaml file and kubernetes can't map the host ports to random ports like docker does in docker run -P.

    ports:
    - containerPort: 8080
      hostPort: 1379
      protocol: TCP
    - containerPort: 9090
      hostPort: 1380
      protocol: TCP

Now I have an actual requirement that docker needs to expose some ports like 880、8080、9090. Except that the docker inside has other services might using other ports. Now I need to map docker exposed ports to random ports in the hostNetwork mode.

My Solution: I expect to analyse kubernetes source code, learn about the process of kubernetes dealing with docker host ports mapping. In hostNetwork mode, scan host ports from 0-65535, check out some host unused ports, while kubernetes dealing with docker host ports mapping, try to map those unused ports to docker exposed ports. In this way, the yaml template like this:

    portmappingnet: true
    ports:
    - containerPort: 8080
      hostPort: random
      protocol: TCP
    - containerPort: 9090
      hostPort: random
      protocol: TCP

**I don't know whether this solution will work. Expect your replies. Thanks~**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by gyliu513** [comment]
Please check if https://github.com/kubernetes/kubernetes/issues/23920 can help

**Comment by cmluciano** [comment]
@killy001 I think the assumption is that if you are using hostNetwork to expose a port on the node, then that port is expected by the consumer of that application. 

Can you describe your uses-case a bit more?
- Are you using an external service discovery mechanism to route requests to these random host ports? 
- Do  you require the ability to use hostNetwork, if not, why not use NodePort?

**Comment by killy001** [comment]
@cmluciano  As we all known, docker run commands have an argument is -p or -P to solve the host port random mapping. Now my dockers want to be auto managed by the kubernetes. My dockers have some ports to be exposed such as 880\8080\9090 ，meanwhile there are other applications in the dockers using other ports such as 2379\2380\2381. Now I want to work out the docker exposed port such as 880\8080\9090  random mapping to the host port. I indeed require the ability to use hostNetwork. As that there are no conflicts between the docker inside other used ports with the host random mapping ports. It has nothing to do with the service in kubernetes. Thank you!

**Comment by cmluciano** [comment]
@kubernetes/sig-network-feature-requests

**Comment by smarterclayton** [comment]
Generally you would use service node ports for this use case, which can be randomly allocated.  Can you describe why host network is required?  We generally would need a very strong reason to add this capability, since it isn't necessarily aligned with the original design goals for pods.

**Comment by killy001** [comment]
@smarterclayton  

Why hostNetwork is required？
     
Inside the container, I need to get the host IP. Because the pod IP is allocated by docker0 randomly, so if I have a log service or others in my container, when problems occurs, I need to locate the problem quickly. Except that, if my services in the container have something to do with databases, while those databases are managed by other groups and its IP is allocated. Thus, I think hostNetwork is required.

**Comment by cmluciano** [comment]
You can communicate with those databases with a [headless service without a selector](https://kubernetes.io/docs/concepts/services-networking/service/#without-selectors)

**Comment by thockin** [comment]
See #49792 for more on random ports.  Dup.
