### ISSUE TITLE
K8s compile script can not trigger some syntax errors

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes/kubernetes#48024]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**:
I ran into a syntax error but script can not trigger it. #47225

**What you expected to happen**:
Script can show all the syntax errors

 /kind bug

**Comment by k82cn** [comment]
@jinzhejz , please help to check this.

**Comment by CaoShuFeng** [comment]
I don't think this is an issue.
I think "==" operator returns an "untyped bool" so the compile accept it.
https://github.com/kubernetes/kubernetes/pull/47225#issuecomment-310883007
I am still googleing some document about this.

**Comment by k82cn** [comment]
@CaoShuFeng , thanks; waiting for the doc about that :).

**Comment by CaoShuFeng** [comment]
This document explains the usage about "untyped string", it also works for "untyped bool"
https://blog.golang.org/constants

This is OK:
package main
import "fmt"
type Verbose bool
func main() {
        a := 0
        var b Verbose = (a == 0) // assign success because "a == 0" is untyped
        fmt.Printf("%v\n", b)
}

This is bad:
package main
import "fmt"
type Verbose bool
func main() {
        a := 0
        var b bool = true
        var c Verbose = b  // cannot use bool as type Verbose in assignment
        fmt.Printf("%v\n", b)
}

**Comment by NickrenREN** [comment]
Good to know. But i still don't think it's a good habit to do like that.

**Comment by CaoShuFeng** [comment]
Yeap,  I aggree with you @NickrenREN .
