### ISSUE TITLE
Basic StatefulSet functionality [StatefulSetBasic] should provide basic identity is flaky 

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#48031]
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/statefulset.go:129
Jun 25 08:20:20.050: Failed waiting for pods to enter running: Too many pods scheduled, expected 1 got 2
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/statefulset_utils.go:307
```
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/47014/pull-kubernetes-e2e-gce-etcd3/37616/

@kubernetes/sig-apps-test-failures

**Comment by pmichali** [comment]
@kargakis Not sure if this is resolving the flake. I'm seeing it on my PR (48276), and I think I saw it on another person's PR. I pulled a fresh branch, based on latest from master. The commit ID (37c9367) for 47014, is 13 commits down from my change.

**Comment by ericchiang** [comment]
cc @kubernetes/sig-apps-bugs

This test is consistently failing on upgrade tests https://k8s-testgrid.appspot.com/master-upgrade#gke-cvm-1.6-gci-master-upgrade-master

Can we identify someone to own this?

**Comment by ericchiang** [comment]
Example failure https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-stable-cvm-master-upgrade-master/1065

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/statefulset.go:130
Aug  7 07:13:08.447: Failed waiting for pods to enter running: Too many pods scheduled, expected 1 got 2
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/statefulset_utils.go:303
```

**Comment by spiffxp** [comment]
This remains the flakiest test for the least consistent PR job according to http://storage.googleapis.com/k8s-metrics/flakes-latest.json

/priority failing-test

**Comment by ericchiang** [comment]
pinging @kubernetes/sig-apps-bugs again

**Comment by enisoc** [comment]
I think I was the last person to touch this test, so I will investigate. If anyone has direct links to recent failures I'd appreciate them.

**Comment by enisoc** [comment]
I have several PRs out (see above) that should help with the most common cases seen in the triage dashboard:

https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&test=provide%20basic%20identity

**Comment by enisoc** [comment]
Making progress... we're not number 1 anymore:

```json
  "pr:pull-kubernetes-e2e-gce-etcd3": {
    "consistency": 0.849,
    "flakes": 109,
    "flakiest": {
      "[sig-cli] Kubectl client [k8s.io] Update Demo should create and stop a replication controller [Conformance]": 27,
      "[sig-apps] Job should run a job to completion when tasks sometimes fail and are not locally restarted": 25,
      "[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should provide basic identity": 25
    }
  }
```
http://storage.googleapis.com/k8s-metrics/flakes-latest.json

Hopefully it will go down more after yesterday's PR.

**Comment by enisoc** [comment]
StatefulSet has now fallen completely off the [wall of shame](http://storage.googleapis.com/k8s-metrics/flakes-latest.json)!

The [failure graph](https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=StatefulSet) has fallen from 30-40/hr to 0-1/hr.

Please reopen if the flakes return.
