### ISSUE TITLE
Need authorization for setting tolerations

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#48041]
A primary use case for taints and tolerations is to allow an administrator to statically carve a cluster into [dedicated node groups](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/taint-toleration-dedicated.md). The administrator sets (for example) a NoSchedule taint `dedicated=xxx` on a node to indicate that it is part of the `xxx` dedicated node group. (There may be many such groups in the cluster, e.g. `xxx`, `yyy`, `zzz`, etc.) Users who are allowed to run pods on the `xxx` group of nodes set a NoSchedule toleration for `dedicated=xxx` when they want a pod to be able to schedule on such a node.

Today, any user can set any toleration, so this mechanism cannot be used to securely partition the cluster. (The node taint side is fine, since RBAC can limit write access to node objects to cluster admins.) RBAC is not sufficient because it cannot be specified at the field (toleration in this case) granularity (and in fact even field granularity would not be sufficient, as some toleration key/value pairs may be acceptable for users to set, while others unacceptable). We need to fix this.

Note that there is no standard schema for taints and tolerations -- one cluster might use taint key `dedicated` while another might use taint key `nodeGroup` or whatever.

Probably the best solution to this problem is to use an admission controller that admits or blocks pod creation and update when it sets a toleration on such a "forbidden" toleration key. The design doc for dedicated nodes (see link above) hypothesized that we would probably not want end-users to be setting dedicated node tolerations on their pods anyway, and instead would want an admission controller that sets them based on other properties of the pod (and/or auth information of the user). So this solution is pretty much in line with our original thinking for this feature, we just hadn't considered the security aspect. Presumably the admission controller would be configured using something like a ConfigMap, that would map pod properties (and possibly auth info) to toleration(s) to set. Note that users would still be able to set other tolerations; here we're just talking about the "dedicated node group" toleration.

The ConfigMap could itself be generated by a command-line tool that takes a high-level policy and converts it to the ConfigMap and a script that runs `kubectl taint node` on the relevant nodes to set their dedicated node taints.

ref/ kubernetes/community#721
ref/ #25320
cc/ @Q-Lee 
cc/ @kubernetes/sig-auth-feature-requests 
cc/ @kubernetes/sig-scheduling-feature-requests

**Comment by mikedanese** [comment]
I suspect we want to add tolerations to pod security policy.

**Comment by liggitt** [comment]
> The node taint side is fine, since RBAC can limit write access to node objects to cluster admins

Actually, today, nodes can taint/untaint themselves (since they have write permission to their own spec. We want to restrict nodes' ability to steer pods to themselves by adding labels to themselves, or removing taints from themselves.

**Comment by davidopp** [comment]
@mikedanese : @Q-Lee had a proposal for using PodSecurityPolicy here https://github.com/kubernetes/community/pull/721 but I didn't have a chance to read it. I think @bgrant0607 was objecting because it required too big a change in PSP, or something like that. Anyway, I don't in principle have a problem with using PSP, just haven't thought about how it would work.

@liggitt : While it's true that today nodes don't set taints (it's all done by NodeController on the master), in the future we might want nodes (I assume by "node" you mean "kubelet") to set taints to indicate node problems. So for now I think it's fine to block nodes from setting and removing taints, but in the future we might want to loosen that so that a node can set and remove taints on its own node objects but not other node objects.

**Comment by liggitt** [comment]
> So for now I think it's fine to block nodes from setting and removing taints, but in the future we might want to loosen that so that a node can set and remove taints on its own node objects but not other node objects.

If an admin tainted a node to prevent control-plane pods from getting deployed to it, the kubelet shouldn't be able to remove that taint.

Same applies (in reverse) for adding labels... if a cluster-admin labels their master nodes with `node-role.kubernetes.io/master=true` and schedules a daemonset with privileged pods on those nodes with access to control-plane secrets, a random node should not be able to add that label to itself and steer privileged pods to itself.

**Comment by davidopp** [comment]
@liggitt I think this is just reinforcing the idea that auth rules on taints need to be configurable based on the taint key. A node might want to add and remove "docker is dead" or "primary disk is dead" taints, but (in your example) not add and remove the taint to prevent control-plane pods from getting deployed to it.

I think labels are different, in that there isn't really a good reason kubelets should be able to add or remove labels.

**Comment by davidopp** [comment]
@thockin suggested that one approach is to add a new non-namespaced kind (call it Taint), and have NodeSpec point to it rather than inlining the Taint in the NodeSpec as we do today. The name of the Taint object would be something like `<key>_<value>` (it probably wouldn't need to have any actual contents). RBAC would be used to give create/update/delete permission to whomever you want to allow to add/remove this taint to/from a node, and RBAC would be used to give read permission to whomever you want to allow to tolerate this Taint (enforced by an admission controller that would only admit a pod with tolerations if the user has read access to all the corresponding taints and all of those taint objects have already been created). 

There was also some idea of using ConfigMap instead (but the same basic approach) but I'm not sure that would work well since the names of ConfigMaps might conflict with the names of taints.

**Comment by timothysc** [comment]
Taints and Tolerations are an opt-in feature except for the defaults placed on masters.  Wouldn't it be more prudent to have a design guide around the feature and include initializers?  Right now we have so many features, but we are severely lacking on documentation on best practices of those features.  

/cc @jbeda

**Comment by davidopp** [comment]
We should also think about how to make Pod anti-affinity secure, since that's another way people will specify node-level isolation requirements.

**Comment by davidopp** [comment]
Note that pod anti-affinity, which is another way to do node-level isolation, is already secure since it is a field that only the owner of the pod/set that generated the pod can control.

**Comment by jbeda** [comment]
This is pretty hairy.  This seems like yet another place where we want to make AuthZ policy decisions but we want to have more information than just the URL of the resource being changed.

An idea in 2 parts:
* Part 1: we experiment with a new external admission controller called `ProtectedLabels` that can be configured with a policy to reject changes that set or modify any labels/taints/tolerations that are in a preset list by a users in a preset list.  This controller can start out simple but get more complex (including being dynamically configured using CRDs).
* Part 2: I'm still a little fuzzy on this.  We look to extend RBAC to support "synthetic" actions and objects.  In this way we can encode label to be set as a psuedo-url and then have the admission controller in Part 1 do a SubjectAccessReview to test to see if the current policy allows the action.  This way we keep the AuthZ config in one place but we allow it to be extended to new types of nouns/verbs that aren't directly tied to the API.

Someone can start experimenting and validating Part 1 right now without any changes to a main API.  We can see if folks actually use it and get feedback before making it more official.  If there is a way to do it externally there is no huge hurry to make it super official until we are sure that we have the right model.

**Comment by davidopp** [comment]
Yeah, an admission controller seems likely to be the way to go. We already resort to admission controllers for authorization in scenarios where RBAC policy isn't sufficient (e.g. [kubelet authorizer](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/kubelet-authorizer.md)). Integrating this with RBAC somehow is interesting (it sounds like you're suggesting something like defining a subresource to do the mutation and then tying the subresource to an admission controller in the RBAC rule).

**Comment by davidopp** [comment]
> Part 1: we experiment with a new external admission controller called ProtectedLabels that can be configured with a policy to reject changes that set or modify any labels/taints/tolerations that are in a preset list by a users in a preset list. This controller can start out simple but get more complex (including being dynamically configured using CRDs).

I forgot that there already is an [admission controller](https://github.com/kubernetes/kubernetes/blob/d490e2cf83316dfa302e54842e91752a029d5210/plugin/pkg/admission/podtolerationrestriction/admission.go), not enabled by default in upstream (but enabled in OpenShift), that enforces a whiltelist on tolerations (configurable per-namespace). This is essentially the same as what you (@jbeda) suggested in Part 1. Maybe we should just enable this in upstream and say it's good enough for now? The tolerations corresponding to the dedicated node group(s) that a namespace is allowed to use would be whitelist for the namespace.

**Comment by ericchiang** [comment]
/remove-lifecycle rotten

cc @colemickens 

ref https://github.com/kubernetes/kubernetes/issues/59366

**Comment by bsalamat** [comment]
Just to let others know, we currently have PodTolerationRestrictions and we are also working on designing Pod Scheduling Policies to address the problem of adding tolerations or other specifications that affect scheduling of a pod or other pods in the cluster.

**Comment by tallclair** [comment]
I'm calling this a duplicate of https://github.com/kubernetes/kubernetes/issues/61185
