### ISSUE TITLE
Do informers without resync/relist violate controller design best practices?

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#48046]
This came up in https://github.com/kubernetes/kubernetes/pull/47788. We have a controller design principle state [here](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/principles.md#control-logic) that:

> Functionality must be level-based, meaning the system must operate correctly given the desired state and the current/observed state, regardless of how many intermediate state updates may have been missed. Edge-triggered behavior must be just an optimization.

Do shared informers that never resync or relist violate this design principle? Did something change to make this no longer necessary? The shared informers used by most controllers in the contoller manager have a min resync default of 12 hours. I'm not sure if they relist.

@kubernetes/sig-api-machinery-misc @davidopp

**Comment by davidopp** [comment]
I interpret that statement as meaning the component needs to be able to retrieve all the state it needs when it starts up, and also needs to detect when it has missed updates (so it can relist). I don't read it as requiring any periodic reslist/resync. But @kubernetes/sig-api-machinery-misc would have the authoritative answer...

**Comment by deads2k** [comment]
It's not strictly a need to relist, but to consider the watch to be an optimization on a relist.  Given informers, a controller will may get notified of a change, but never see a *particular* change.  For instance:

 1. foo/a.spec.one updated to alpha
 2. controller is notified, but has a backed up internal queue
 3. foo/a.spec.one updated to bravo
 4. controller is notified, but the first change is still in queue
 5. controller pops foo/a's change notification and pulls the latest from cache.  It never observes a.spec.one == alpha.

The controller must behave properly when seeing only levels, not edges.

**Comment by smarterclayton** [comment]
The specific scenario in the other issue can probably be clarified as:

A kubernetes controller that acts only on level driven changes from
informer fed caches is not fully implemented *if* it needs to relist.  It
is not required to relist to be a controller, but correct level-driven
informer-fed controllers do not need to relist.  So the presence of
frequent relist may obscure logical bugs in a controller that result in
incorrect outcomes

**Comment by mikedanese** [comment]
Thanks for clarifying.
