### ISSUE TITLE
DNS is not starting in large cluster

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#48061]
IMPORTANT NOTE: we have only 1 data point for it for now, but we'll rerun the test to confirm.

On 1k Node cluster (at least on GKE) DNS pod is crashlooping because of liveness probe failure:
```
Killing container with id docker://dnsmasq:pod "kube-dns-3195784982-55h2h_kube-system(2218b585-5a4f-11e7-be65-42010af00003)" container "dnsmasq" is unhealthy, it will be killed and re-created.
Killing
Liveness probe failed: HTTP probe failed with statuscode: 503
Unhealthy
Readiness probe failed: Get http://10.0.8.3:8081/readiness: dial tcp 10.0.8.3:8081: getsockopt: connection refused
Unhealthy
```

@kubernetes/sig-network-bugs @kubernetes/sig-release-bugs @dchen1107 @bowei. @kubernetes/sig-scalability-misc

**Comment by gmarek** [comment]
Confirmed that it happened again. Good thing is that it works fine on GCE, so it's not a blocker.

**Comment by dchen1107** [comment]
Can someone explain a little bit why #3196 fix the potential issue here? Also mark this issue with label: team/gke. 

cc/ @kubernetes/kubernetes-release-managers

**Comment by gmarek** [comment]
It's kubernetes/test-infra#3196. We believe it's a problem in this test only, and that kube-dns tries to use invalid certificate when communicating with the API server. Sadly it takes some time to validate that, so we preferred to rise this early.

**Comment by cmluciano** [comment]
@bowei I think we bumped the resource sizing of DNS recently. Is this something that needs bumped further for large-scale tests/document fixes?

**Comment by bowei** [comment]
@cmluciano -- is that true? I don't think the resource allocation has been touched for a while now...

**Comment by gmarek** [comment]
It's diagnosed as a fallout of removing ip-masq-agent in our test environment.

**Comment by shyamjvs** [comment]
Linking issue https://github.com/kubernetes/kubernetes/issues/47344 for the record.
