### ISSUE TITLE
cluster/kube-push.sh doesn't upgrade configuration of cluster service RC

### ISSUE THREAD

**Issue by rsokolowski** [kubernetes/kubernetes#4806]
Environment: GCE
I've updated skydns configuration (cluster/addons/dns/skydns-rc.yaml.in) and wanted to push it to an existing cluster using cluster/kube-push.sh (or hack/dev-build-and-push.sh). The script has noticed changes in the skydns RC configuration: 
          ID: /etc/kubernetes/addons/dns/skydns-rc.yaml
    Function: file.managed
      Result: True
     Comment: File /etc/kubernetes/addons/dns/skydns-rc.yaml updated
     Changes:   
              ----------
              diff:
...
however did not affect the RCs or pods on the cluster. 
I'm not sure whether it is WAI, but it would be definitely useful to have cluster/kube-push.sh also update configuration on a cluster service (I don't know whether this is skydns specific or not).

**Comment by zmerlynn** [comment]
It's certainly working as implemented. :) The `kube-addons` "service" (which is a bash script) doesn't have an easy way to re-run this. Or, rather, it was out of scope to get that part working at the time.

What would really help is a `kubectl update` that had create semantics or vice-versa, then that script could run and generally work fine for the `kube-push` case (it would have to handle the delete case specially, after update probably .. right now I think even salt isn't handling delete correctly, if you disable SkyDNS and `kube-push`).

**Comment by mikedanese** [comment]
There hasn't been a need for this. We can fix it when we move to using kubectl apply instead of the shell script.
