### ISSUE TITLE
E2E: ci-kubernetes-e2e-gce-federation-release-1-7 is not running for a couple of days

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#48083]
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-federation-release-1-7/ is not running for last couple days, and the last run occurred at June 21 (No issue is reported yet):

Builds
334 2017-06-21 01:29 PDT 
333 2017-06-21 00:24 PDT took 1h3m 
332 2017-06-20 23:20 PDT took 1h2m 
331 2017-06-20 22:15 PDT took 1h3m 
330 2017-06-20 21:08 PDT took 1h5m 
329 2017-06-20 19:42 PDT took 1h24m 
328 2017-06-20 16:28 PDT 
...

On another hand, https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-federation-build-1.7/ is keeping building the new builds for test last couple days:

Builds
30 2017-06-26 08:13 PDT took 15m9s 
29 2017-06-24 15:56 PDT took 15m21s 
28 2017-06-23 17:54 PDT took 16m7s 
27 2017-06-23 17:05 PDT took 15m34s 
26 2017-06-23 14:14 PDT took 18m27s 
25 2017-06-22 14:44 PDT took 15m39s 
24 2017-06-21 23:54 PDT took 12m0s 
...

cc/ @kubernetes/sig-federation-misc 

@kubernetes/kubernetes-release-managers @ericchiang

**Comment by dchen1107** [comment]
cc/ @krzyzacy

**Comment by krzyzacy** [comment]
the jun.21 job was hanging on
```
W0621 08:49:54.570] I0621 08:49:54.570219   16881 round_trippers.go:414]     Date: Wed, 21 Jun 2017 08:49:54 GMT
W0621 08:49:54.581] I0621 08:49:54.580865   16881 request.go:991] Response Body: {"kind":"Service","apiVersion":"v1","metadata":{"name":"e2e-federation-apiserver","namespace":"federation-system","selfLink":"/api/v1/namespaces/federation-system/services/e2e-federation-apiserver","uid":"989ccba4-565e-11e7-b200-42010a80000a","resourceVersion":"528","creationTimestamp":"2017-06-21T08:49:54Z","labels":{"app":"federated-cluster"},"annotations":{"federation.alpha.kubernetes.io/federation-name":"e2e-federation"}},"spec":{"ports":[{"name":"https","protocol":"TCP","port":443,"targetPort":"https","nodePort":30098}],"selector":{"app":"federated-cluster","module":"federation-apiserver"},"clusterIP":"10.0.61.75","type":"LoadBalancer","sessionAffinity":"None","externalTrafficPolicy":"Cluster"},"status":{"loadBalancer":{}}}
I0621 08:49:54.681] Creating a namespace federation-system for federation system components... done
I0621 08:51:04.586] Creating federation control plane service.................. done
```

maybe we had some issue terminating the pod, let me kick off another one
/assign

**Comment by dchen1107** [comment]
RE: https://github.com/kubernetes/kubernetes/issues/48083#issuecomment-311141879 Why there is no catchall timeout to kill everything?

**Comment by krzyzacy** [comment]
It should, and the timeout logic was working for other jobs. Wonder if that was happening when we switched the prow cluster. @spxtr

**Comment by krzyzacy** [comment]
http://prow.k8s.io/log?pod=ci-kubernetes-e2e-gce-federation-release-1-7-335

after retrigger the 1.7 job is hanging getting nodes, and @nikhiljindal is investigating and probably can give more updates

/assign @nikhiljindal

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-federation-release-1-7/341 that run was green except for some resource leaking, I'll close the issue @dchen1107 

/close
