### ISSUE TITLE
Openstack LBaaSv2 - Kubernetes fails to delete Load Balancer

### ISSUE THREAD

**Issue by zioproto** [kubernetes/kubernetes#48094]
/sig openstack
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

> Uncomment only one, leave it on its own line: 
>
/kind bug

**What happened**:

I delete a service:
```
kubectl delete service my-nginx
```
Kubernetes is never able to delete the Loadbalancer from Openstack
```
$ kubectl get events
LASTSEEN   FIRSTSEEN   COUNT     NAME        KIND      SUBOBJECT   TYPE      REASON                       SOURCE               MESSAGE
3m         3m          1         my-nginx                   Service                                  Normal    CreatingLoadBalancer         service-controller       Creating load balancer
2m         2m          1         my-nginx                   Service                                  Normal    CreatedLoadBalancer          service-controller       Created load balancer
2s         1m          5         my-nginx                   Service                                  Normal    DeletingLoadBalancer         service-controller       Deleting load balancer
42s        1m          4         my-nginx                   Service                                  Warning   DeletingLoadBalancerFailed   service-controller       Error deleting load balancer (will retry): Resource not found
```
The problem is that there are no health monitors in Openstack, and Kubernetes refuses to go on and delete pools and loadbalancers and listeners.
On the neutron server I see DELETE requests without the health-monitor uuid, because the list of healthmonitors is empty.

**What you expected to happen**:
The loadbalancer is deleted.

In case the health monitors list is empty Kubernetes should go on and delete the rest of the Load Balancer.

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl run my-nginx --image=nginx --replicas=2 --port=80
kubectl expose deployment my-nginx --port=80 --type=LoadBalancer
kubectl delete service my-nginx
kubectl get events
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**:
Openstack Newton
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
https://github.com/zioproto/k8s-on-openstack
- Others:

**Comment by FengyunPan** [comment]
@zioproto From the "Error deleting load balancer (will retry): Resource not found" of event, I suspect that  you have deleted the neutron resource of service's LB, is it?
Or give me more detail log of kube-controller-manager?

**Comment by zioproto** [comment]
@FengyunPan I have not deleted anything in Openstack. The problem is that kubernetes never creates health monitors but then it tries to delete them forever.

this is the log you requested:
```I0630 07:31:46.850943       1 servicecontroller.go:759] Service has been deleted default/my-nginx
E0630 07:31:51.577371       1 servicecontroller.go:772] Failed to process service. Retrying in 5s: Resource not found
I0630 07:31:56.578075       1 servicecontroller.go:759] Service has been deleted default/my-nginx
E0630 07:31:59.069556       1 servicecontroller.go:772] Failed to process service. Retrying in 10s: Resource not found
I0630 07:32:09.069908       1 servicecontroller.go:759] Service has been deleted default/my-nginx
E0630 07:32:11.247040       1 servicecontroller.go:772] Failed to process service. Retrying in 20s: Resource not found```

**Comment by FengyunPan** [comment]
@zioproto Maybe your kubernetes version is incorrect. Can you try it on kubernetes v1.6.4+. My test as following:

**Comment by zioproto** [comment]
@FengyunPan I tested with v1.6.4 and I had the same. I am running Openstack Newton. Are you running the same version of Openstack as well ? thank you

**Comment by FengyunPan** [comment]
Yes, it work fine.

**Comment by FengyunPan** [comment]
Add pr #48336 to prevent the deletion of empty monitors.
