### ISSUE TITLE
Update links to k8s.io/docs/user-guide/...

### ISSUE THREAD

**Issue by chenopis** [kubernetes/kubernetes#48105]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
There are still links in the autogenerated docs (types.go files) to the deprecated `/docs/user-guide/` directory in k8s.io. 

**What you expected to happen**:
These need to be updated so that they go to the correct refactored docs.

**How to reproduce it (as minimally and precisely as possible)**:
See: https://github.com/kubernetes/kubernetes/search?utf8=%E2%9C%93&q=%2Fuser-guide%2F&type=

**Anything else we need to know?**:
Related to [kubernetes/kubernetes.github.io#4194](https://github.com/kubernetes/kubernetes.github.io/issues/4194)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6+
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others: http://kubernetes.io

**Comment by chenopis** [comment]
@kubernetes/sig-docs-maintainers

**Comment by chenopis** [comment]
Does the stupid robot always add `sig/api-machinery` because of its own comment?

**Comment by ahmetb** [comment]
> Does the stupid robot always add [REDACTED] because of its own comment?
>  😄 2

might be worth opening a bug on test-infra.

**Comment by crimsonfaith91** [comment]
@chenopis @ahmetb the PR https://github.com/kubernetes/test-infra/pull/3201 to resolve this has been merged. I am waiting someone to redeploy it.
