### ISSUE TITLE
RBAC role for just listing (not getting) secrets

### ISSUE THREAD

**Issue by mikebryant** [kubernetes/kubernetes#48128]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

/kind feature

I would like to be able to set up an RBAC role that allows listing secrets (and possibly access to the rest of the `metadata`), but not give access to the `data`

**Rationale**
We would like to run our clusters using readonly accounts, and only use higher privileged accounts if needed. So in general we want readonly access to everything but secrets.
It would however be useful to see the existence of secrets (e.g. to see whether secrets for service accounts have been created, or secrets from kube-cert-manager)

**Comment by luxas** [comment]
cc @DirectXMan12 We talked about this as well

**Comment by liggitt** [comment]
The API has a metadata-only access pattern, but that is for performance, not for security.

There are kube features (like `kubectl apply`) that put object content in annotations in the metadata

Currently, the authorization layer does not have information about whether the user is operating in metadata-only mode.

**Comment by DirectXMan12** [comment]
Just to clarify the usecase that @luxas was talking about, in the custom metrics API adapter for Prometheus, we need to know the *name* of potentially any object in the cluster (and be able to list by label selector).  However, *all* we need to know is names and labels, so it would be nice to be able to constrain access, so that in case of compromise, there's less data leakage.

**Comment by mml** [comment]
Leaving it to sig-auth to decide this feature is desirable and come up with a design first.

**Comment by liggitt** [comment]
moving to sig-api-machinery... listing names only without contents is an API issue
@kubernetes/sig-api-machinery-feature-requests

**Comment by stuart-warren** [comment]
We'd still really like this feature
