### ISSUE TITLE
kube-apiserver does not respect nsswitch.conf

### ISSUE THREAD

**Issue by jeroenjacobs1205** [kubernetes/kubernetes#48124]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

If have a wildcard dns entry like this on my bind dns server:

`* IN CNAME lb-001.mydomain.com`

this causes kube-apiserver to resolve localhost to lb-001.mydomain.com.

**What you expected to happen**:

nsswitch.conf contains this line:

`hosts:      files dns myhostname`

I would expect that kube-apiserver and uses /etc/hosts first, where localhost is defined:

`127.0.0.1   localhost localhost.localdomain
`

kube-apiserver exits with the following error:

 `controller.go:128] Unable to perform initial IP allocation check: unable to refresh the service IP block: Get https://localhost:6443/api/v1/services: dial tcp 192.168.120.20:6443: getsockopt: connection refused
`
The returned ip address is the one of the loadbalancer (lb-001)

**Anything else we need to know?**:

Cluster was configured via kubeadm

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.6
- Cloud provider or hardware configuration**: esx/vsphere
- OS (e.g. from /etc/os-release): centos7
- Kernel (e.g. `uname -a`): Linux master-001 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Others:

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
because kubeadm

**Comment by divyenpatel** [comment]
Can you provide output of 

```
$ getent ahosts localhost
::1             STREAM localhost
::1             DGRAM  
::1             RAW    
127.0.0.1       STREAM 
127.0.0.1       DGRAM  
127.0.0.1       RAW    

```

I guess this should not resolve to `192.168.120.20`

cc:  @luomiao @BaluDontu @tusharnt

**Comment by jeroenjacobs1205** [comment]
ipv6 is disabled here, so this is the output:

```
127.0.0.1       STREAM localhost
127.0.0.1       DGRAM  
127.0.0.1       RAW    

```

**Comment by divyenpatel** [comment]
Can you go to the container's directory
/var/lib/docker/containers/<container-id> and check `hosts` file, localhost should be mapped to 127.0.0.1, for container as well.
