### ISSUE TITLE
Clarify and update PodStatus/PodCondition

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#48127]
/kind bug

**What happened**:

I wanted to find out how to parse PodStatus. Found two problems:
- PodStatus docs do not state whether it contains at most one PodStatus of type Ready, or which one is authoritative in case there are more
- 1.6 PodCondition API docs say that the only type is Ready, while in a 1.6 I can see a couple more types:
```
    "status": {
        "conditions": [
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2017-06-06T18:38:49Z",
                "status": "True",
                "type": "Initialized"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2017-06-25T14:42:27Z",
                "status": "False",
                "type": "Ready"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2017-06-06T18:38:49Z",
                "status": "True",
                "type": "PodScheduled"
            }
        ],
```

**What you expected to happen**:

Documentation should say how many PodCondition-s there are in PodStatus of a given type.

**How to reproduce it (as minimally and precisely as possible)**:

Read https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions and https://kubernetes.io/docs/resources-reference/v1.6/#podcondition-v1-core

**Comment by porridge** [comment]
/sig docs
*sigh*

**Comment by tengqm** [comment]
Manually copied to website.
