### ISSUE TITLE
Is it possible to enable multiple cloud providers in controller manager

### ISSUE THREAD

**Issue by selvakumarnms** [kubernetes/kubernetes#48136]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by selvakumarnms** [comment]
Is it possible to enable multiple cloud providers in June controller manager service?

**Comment by selvakumarnms** [comment]
Is it possible to enable multiple cloud providers in kube controller manager service?

**Comment by spiffxp** [comment]
@kubernetes/sig-api-machinery-misc unsure if this is the right sig, who would know best about cloud provider stuff?

**Comment by deads2k** [comment]
> Is it possible to enable multiple cloud providers in kube controller manager service?

No, you can't.



> @kubernetes/sig-api-machinery-misc unsure if this is the right sig, who would know best about cloud provider stuff?

Not us, but I happen to know this one.  The cloud-provider flag only takes one value, not a slice.

@rrati @derekwaynecarr for the "who owns cloud providers" question.

**Comment by ncdc** [comment]
There have been discussions about how to handle concerns that cut across multiple clouds, but there is not a resolution yet to my knowledge. This would probably be best handled by the proposed sig-cloud (does not exist yet), or better yet, by the proposed sig-architecture (does not exist yet). Supporting multiple cloud providers would touch multiple components, so involving the broader architectural group probably makes more sense. For example, if the cluster supports both AWS and GCE, if a pod has a GCEPersistentDisk volume, the scheduler must ensure the pod is bound to a GCE node and not an AWS one. There would be the potential for similar issues with other cloud services as well, such as load balancers. I don't think this is a simple problem to solve, unfortunately.

**Comment by mml** [comment]
@selvakumarnms please re-open as a feature request if you have a specific use case to discuss.  Thanks!

/sig architecture
cc @cheftako
