### ISSUE TITLE
Remove TPR resource in favor of CRD

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#48152]
In 1.6 TPR was indicated as unstable and subject to change [[1]](https://github.com/kubernetes/kubernetes.github.io/blob/release-1.6/docs/tasks/access-kubernetes-api/extend-api-third-party-resource.md). Near the end of 1.6 we talked about a new API and how we would transition [[2]](https://github.com/kubernetes/community/blob/master/sig-api-machinery/api-extensions-position-statement.md#q-should-tpr-maintain-compatibility-or-should-we-break-compatibility-to-fix-and-extend-it). In 1.7 we updated the docs to announce deprecation and provided the alternative and a clean semi-automatic migration path [[3]](https://github.com/kubernetes/kubernetes.github.io/blob/release-1.7/docs/tasks/access-kubernetes-api/extend-api-third-party-resource.md). They were specifically called out in the release notes [[4]](https://github.com/kubernetes/features/pull/306). There is acknowledgement in the community that they will be removed [[5]](https://coreos.com/blog/custom-resource-kubernetes-v17), and following our [deprecation policy](https://kubernetes.io/docs/reference/deprecation-policy/) we can remove them in 1.8 and focus our efforts on adding features like [validation](https://github.com/kubernetes/community/pull/708) to CRDs.

@kubernetes/sig-api-machinery-misc @enisoc @smarterclayton @sttts @nikhita

**Comment by smarterclayton** [comment]
Seems appropriate for alpha transition

**Comment by enisoc** [comment]
The [migration helper](https://github.com/kubernetes/kubernetes/pull/46677) intentionally leaves behind the etcd data for TPRs, for rollback and to prevent watchers from seeing deletes.

Should we clean up this data eventually? Is there a precedent for how we handle etcd data for resources that were deprecated and removed?

**Comment by smarterclayton** [comment]
No precedent today.

**Comment by sttts** [comment]
Lgtm. Let's proceed with this.

**Comment by enisoc** [comment]
We need at least one PR with `release-note-action-required`. I put it on #48353 since that was the first step. I also added a link to the migration guide in the release note.

**Comment by deads2k** [comment]
> We need at least exactly one PR with release-note-action-required. I put it on #48353 since that was the first step. I also added a link to the migration guide in the release note.

Makes sense.  I put the release-note on that one, but forgot about the extra "action required" bit.

**Comment by sttts** [comment]
This is done.

**Comment by spiffxp** [comment]
I agree that this decision was well communicated, and do not wish to revert it, but I wanted to revisit it for a moment as prior art for future deprecations.  Did we remove TPR's a release too early?

If TPR's were actually alpha, then I think we did fine.  But https://v1-6.docs.kubernetes.io/docs/api-reference/v1.6/#thirdpartyresource-v1beta1-extensions shows them as v1beta1

CRD's don't show up in the API reference docs in v1.7 https://v1-7.docs.kubernetes.io/docs/api-reference/v1.7/

Using the table listed in https://kubernetes.io/docs/reference/deprecation-policy/ as an example, it seems like we should have kept TPR's around until v1.9:
- X+2 = 1.6 -> v1beta1 TPR
- X+3 = 1.7 -> v1beta1 CRD, v1beta1 TPR deprecated
- X+4 = 1.8 -> v1beta CRD, v1beta1 TPR deprecated... but we instead removed
- X+5 = 1.9 -> v1beta1 CRD

Am I misinterpreting the deprecation policy, or did we make an exception here?

**Comment by liggitt** [comment]
For the `extensions` group specifically, "beta" doesn't necessarily mean beta. Calling the extensions API group beta was a misnomer and pre-dated crisp alpha/beta/ga definitions and the deprecation policy. The objects within that API group were a mix of alpha and beta quality APIs.

TPR's were actually alpha. They did not complete the [gathered requirements for beta](https://github.com/kubernetes/kubernetes/issues/22768), and had [known issues](https://groups.google.com/d/msgid/kubernetes-sig-api-machinery/CAKCBhs7c2V7e%2BEwjhFfKoouhAmzw3hZosi34iaAB07aXKw-B6g%40mail.gmail.com). The [user guide was updated in 1.5](https://v1-5.docs.kubernetes.io/docs/user-guide/thirdpartyresources/) to indicate they were not considered stable.

**Comment by enisoc** [comment]
In addition, at the time when we did this, the Beta deprecation policy was to keep the old API around for "3 months, 1 release". It was later changed without any announcement (that I saw) to "6 months, 2 releases":

https://github.com/kubernetes/website/commit/8f9677227dac0d0032a9faaae1dd318e8ddbd095#diff-20e68d228e6f9fe6ccc143526a382670R78
