### ISSUE TITLE
NFS Volumes Example does not work on GKE 1.6.4

### ISSUE THREAD

**Issue by kingdonb** [kubernetes/kubernetes#48161]
/kind bug
/sig docs

**What happened**:
I followed the steps of examples/volumes/nfs and I did not get a working NFS server.  What appeared to happen was my "nfs" pvc was created and bound to a new PD, instead of being bound to the new unbound "nfs" pv.  The gce-pd provisioner appears to satisfy any requests with a `storageClassName: standard`, and the default behavior appears to be applying this storageClassName to any PVC that doesn't have one (it's a feature?)

**What you expected to happen**:
I just expected to 

**How to reproduce it (as minimally and precisely as possible)**:
Follow the steps in examples/volumes/nfs/README.md and don't read the solution in this gist:
https://gist.github.com/kingdonb/78f82adf9d3507aab6f397b0dd2526c3

**Anything else we need to know?**:
The solution is in this gist:
https://gist.github.com/kingdonb/78f82adf9d3507aab6f397b0dd2526c3

(Apply a storageClassName: something else)

There's something else you need to know, #33447 -- users have been reporting that this example does not work for a while, and there is an e2e that is said to fail too.  This thread terminates with some further information you need, but it's included in the gist above.

Without the information about storageClassName (I'm guessing something changed there since May, maybe you're applying a default storageClassName of 'standard' because people were having trouble figuring out how to get PVCs satisfied by gce-pd automatically? Don't know...)

> Edit `examples/volumes/nfs/nfs-pv.yaml`
> change the last line to `path: "/"`
> 
> Edit `examples/volumes/nfs/nfs-server-rc.yaml`
> change the image to the one that enabled NFSv4
> `image: gcr.io/google_containers/volume-nfs:0.8`

Above, is the important part of that thread needed to fix the example.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
kingdon@gke-temp:~/kubernetes$

- Cloud provider or hardware configuration**:
Google Container Engine cluster (defaults, node version 1.6.4)

Other details (eg. kernel) are irrelevant, GKE standard cluster with default options.

I have verified that by making the changes in the gist, the example can be made to work again.  Changes to the filesystem are reflected on two busybox clients and on the nfs server in /exports/

Try it, please update the example so that it works.  This was a lot of goose chasing!  I will provide PR if there is no other feedback, but I do not yet have a CLA.  From the changes I made in the gist, you probably do not need the "id" label selector.

**Comment by kingdonb** [comment]
@kubernetes/sig-docs This is a documentation issue also involving storage.

**Comment by kingdonb** [comment]
@k8s-merge-robot ping

**Comment by kingdonb** [comment]
I think I like the diff in linked gist version above, better than c6d22d05cf60d1ba49f25f5cedab94a09617129a

But, I am not a contributor

If I can get a reviewer who is a contributor to comment, I think you'll find that c6d22d05cf60d1ba49f25f5cedab94a09617129a which was made later is better and more brief.  Doesn't use the id label selector, just a `storageClassName` which still must match on pv and pvc (or the gce-pd provisioner will take over, I guess.)

Like I said, I think I prefer 928615ecab, but I'll be happy to discuss that with a reviewer if you have an opinion either way.  Will amend for PR on request.

**Comment by kingdonb** [comment]
Also related to #44377

**Comment by kingdonb** [comment]
I will gladly sign a Contributor Agreement, but I think I still need a reviewer.  Can anyone confirm this change?

**Comment by ahmetb** [comment]
cc: @saad-ali

**Comment by msau42** [comment]
Can this be closed? It looks like the nfs example has been fixed in kubernetes/examples#30

**Comment by kingdonb** [comment]
Yes, closing
