### ISSUE TITLE
"/approve no-issue" isn't working

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#48163]
See https://github.com/kubernetes/kubernetes/pull/48159#issuecomment-311514654 and on.

**Comment by zmerlynn** [comment]
@kubernetes/sig-contributor-experience-bugs

**Comment by xiangpengzhao** [comment]
cc @crimsonfaith91

**Comment by crimsonfaith91** [comment]
@apelisse It looks like `/approve no-issue` does not work immediately for https://github.com/kubernetes/kubernetes/pull/48159#issuecomment-311514654. Mind to step in to investigate it? Thanks!

**Comment by luxas** [comment]
It hasn't worked for me either for a couple of days...

**Comment by spxtr** [comment]
Authors couldn't approve no-issue, which was fixed. Dupe of https://github.com/kubernetes/test-infra/issues/3228.

**Comment by xiangpengzhao** [comment]
`/approve no-issue` didn't work in https://github.com/kubernetes/kubernetes/pull/44129#issuecomment-313272618

**Comment by spxtr** [comment]
See https://github.com/kubernetes/kubernetes/pull/44129#issuecomment-313282611

This is very confusing behavior.

**Comment by apelisse** [comment]
It's far from perfect, but it also makes sense to have approvers be actual approvers.

**Comment by spxtr** [comment]
Right, but I think this is super confusing:

<img width="782" alt="screen shot 2017-07-06 at 11 02 31 am" src="https://user-images.githubusercontent.com/7368979/27925727-b7f0cf70-623a-11e7-9ad4-1bedb0f59ac0.png">

It's not clear who can actually `/approve no-issue` it, and the PR author doesn't know how to proceed.

**Comment by apelisse** [comment]
Oh I completely agree with that, we could re-word the text. Suggestion?

**Comment by crimsonfaith91** [comment]
We can state the user is not one of the approvers, and remove the user from the list.

e.g.,
[APPROVALNOTIFIER] This PR is **NOT APPROVED** [_dims_ is not one of the approvers]
This pull-request has been approved by: _brendandburns_, _xiangpengzhao_

**Comment by apelisse** [comment]
What about the following?

> No associated issue. Update pull-request body to add a reference to an issue, or a valid approver for this pull-request should issue a `/approve no-issue` command.

**Comment by crimsonfaith91** [comment]
Yes, we should explain about validity of an approver. How about this?

[APPROVALNOTIFIER] This PR is **NOT APPROVED** [_dims_ is a valid approver]
This pull-request has been approved by: brendandburns, xiangpengzhao

No associated issue. Update pull-request body to add a reference to an issue, or a valid approver for this pull-request should issue a `/approve no-issue` command.

**Comment by spxtr** [comment]
In this case it should also say what it means to be a valid approver. I'm guessing valid approvers are those who can approve at least one file in the PR?

**Comment by apelisse** [comment]
Yeah, but I really don't want to create a notion of "invalid" approvers. Every one should be a valid approver, even though they can't approve any files.

**Comment by dims** [comment]
@apelisse +1, we should be welcoming reviews. 

@apelisse @spxtr In this specific case since @brendanburns had already approved and the bot failed just because of the missing issue number. The bot should honored the "/approve no-issue" i feel.

**Comment by crimsonfaith91** [comment]
@spxtr we can include definition of a valid approver under `Details` tab.

**Comment by apelisse** [comment]
I don't think I'm really opposed to letting people do `/approve no-issue`. Everytime we've opened the door to let people do more, it's only been positive, and the expected bad behaviors that we had initially expected never occurred.

I vote we let anyone do `/approve no-issue`.

cc @dchen1107 @grodrigues3 @pwittrock

**Comment by xiangpengzhao** [comment]
Letting anyone do `/approve no-issue` will encourage people to do more for community. But will this be safe enough? If a new contributor who is not so familiar with the code in a PR do a `/approve no-issue` and then the PR is merged, potential bug may be missed in this process. OTOH, OWNERS of that code can (relatively) review the code better and approve more carefully.

Of course, this is just a worry. It may never happen.

**Comment by dims** [comment]
Hate to bug on this one.. another example of "stuck" PR - https://github.com/kubernetes/kubernetes/pull/47436

**Comment by luxas** [comment]
I believe this has been fixed, so closing this one as stale
