### ISSUE TITLE
Improve kube-scheduler integration test

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#48176]
**Is this a BUG REPORT or FEATURE REQUEST?**:
enhancement

/kind feature
/sig scheduling

**What happened**:
Echo @bsalamat 's proposal in sig-scheduling: There are a few scheduling e2e tests that are flakier than accepted. If you go to [the following link](https://k8s-testgrid.appspot.com/release-1.7-blocking#gce-serial-release-1-7&sort-by-failures=) that sorts tests by their failures, you will see that a few scheduler tests are among the top 10. At the same time, reproducing the failures in a personal cluster is sometimes hard. That's why we think that the failures may be related to the fact that our test clusters are not deterministic enough to test all the scheduler logic. Some of these functionalities are already tested by our unit tests, but we would like to have better integration test coverage as well.

**Comment by bsalamat** [comment]
I am going to convert some of our e2e tests to integration tests this week.
