### ISSUE TITLE
Should not sync third party resources when it's disabled

### ISSUE THREAD

**Issue by liaoyw** [kubernetes/kubernetes#48174]
**Is this a BUG REPORT or FEATURE REQUEST?**: 
 /kind bug

**What happened**:
After we disabled thirdpartyresources, apiserver still try to sync resources. And report
```third party resource sync failed: the server could not find the requested resource```

**What you expected to happen**:
Not sync third party resources when it's disabled

**How to reproduce it (as minimally and precisely as possible)**:
Add ```--runtime-config=extensions/v1beta1/thirdpartyresources=false``` to apiserver arguments, and view log 

**Anything else we need to know?**:
```
tail -n 500 logs/kubernetes/kube-apiserver.INFO | grep third
I0628 12:49:25.230437    2621 wrap.go:75] GET /apis/extensions/v1beta1/thirdpartyresources: (114.821µs) 404 [[kube-apiserver/v1.6.4 (linux/amd64) kubernetes/8f8d593] 127.0.0.1:45320]
W0628 12:49:25.230690    2621 storage_extensions.go:127] third party resource sync failed: the server could not find the requested resource
I0628 12:49:35.231138    2621 wrap.go:75] GET /apis/extensions/v1beta1/thirdpartyresources: (136.212µs) 404 [[kube-apiserver/v1.6.4 (linux/amd64) kubernetes/8f8d593] 127.0.0.1:45320]
W0628 12:49:35.231360    2621 storage_extensions.go:127] third party resource sync failed: the server could not find the requested resource
I0628 12:49:45.231799    2621 wrap.go:75] GET /apis/extensions/v1beta1/thirdpartyresources: (130.379µs) 404 [[kube-apiserver/v1.6.4 (linux/amd64) kubernetes/8f8d593] 127.0.0.1:45320]
W0628 12:49:45.232035    2621 storage_extensions.go:127] third party resource sync failed: the server could not find the requested resource
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.4
- Cloud provider or hardware configuration**: 
- OS (e.g. from /etc/os-release): centos7.2
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by gosudream** [comment]
see #48152,  tpr will be removed

**Comment by liaoyw** [comment]
see #48152  tpr will be removed.
