### ISSUE TITLE
Kubernetes installation with Vagrant stuck

### ISSUE THREAD

**Issue by lvthillo** [kubernetes/kubernetes#48178]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Kubernetes installation stuck with 
```
Validating master
....................

After errors like:

 ----------
==> node-1:           ID: /var/lib/kubelet/ca.crt
==> node-1:     Function: file.managed
==> node-1:       Result: False
==> node-1:      Comment: Source file salt://kubelet/ca.crt not found
==> node-1:      Started: 06:57:14.203234
==> node-1:     Duration: 0.927 ms
==> node-1:      Changes:
==> node-1: ----------

----------
==> node-1:           ID: fix-service-kubelet
==> node-1:     Function: cmd.wait
==> node-1:         Name: /opt/kubernetes/helpers/services bounce kubelet
==> node-1:       Result: False
==> node-1:      Comment: One or more requisite failed: kubelet./var/lib/kubelet/ca.crt
==> node-1:      Started:
==> node-1:     Duration:
==> node-1:      Changes:
==> node-1: ----------
==> node-1:           ID: kubelet
==> node-1:     Function: service.running
==> node-1:       Result: False
==> node-1:      Comment: One or more requisite failed: kubelet./var/lib/kubelet/ca.crt
==> node-1:      Started:
==> node-1:     Duration:
==> node-1:      Changes:
==> node-1: ----------
```

**What you expected to happen**:
Finish installation

**How to reproduce it (as minimally and precisely as possible)**:
On mac OS Sierra: 10.12.5  

```
export KUBERNETES_PROVIDER=vagrant
curl -sS https://get.k8s.io | bash
cd kubernetes
export VAGRANT_DEFAULT_PROVIDER=virtualbox
export KUBERNETES_PROVIDER=vagrant
./cluster/kube-up.sh
```

**Anything else we need to know?**:
/

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ ./cluster/kubectl.sh version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"darwin/amd64"}
The connection to the server 10.245.1.2 was refused - did you specify the right host or port?
```

- Cloud provider or hardware configuration**:
```
$ vagrant version
Installed Version: 1.9.5
Latest Version: 1.9.5

You're running an up-to-date version of Vagrant!
```

VBOX: Version 5.1.22 r115126 (Qt5.6.2

- OS (e.g. from /etc/os-release):
In vagrant on Mac OS Sierra: 10.12.5
 
- Kernel (e.g. `uname -a`):
Of my OS
`16.6.0 Darwin Kernel Version 16.6.0`

- Install tools:/
- Others:/

**Comment by luxas** [comment]
@lvthillo I'd suggest you'd use https://github.com/kubernetes/minikube instead
I don't know the exact state of the Vagrant scripts, but something makes me think they are old and possibly, see: https://github.com/kubernetes/kubernetes/commits/master/cluster/vagrant/

The commits there are generic that touch things all over the codebase and not specific to the vagrant deployment.

We should probably just remove the vagrant provider in v1.8. `cluster/` has been deprecated for quite a while

cc @kubernetes/sig-cluster-lifecycle-misc

**Comment by lvthillo** [comment]
@luxas Okay thanks, I'll use minikube instead
