### ISSUE TITLE
[Scheduler] Some Thinkings about predicateFuncs 

### ISSUE THREAD

**Issue by sakeven** [kubernetes/kubernetes#48186]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

/sig scheduling

**Some Thoughts**:
1. When doing  [podFitsOnNode](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/core/generic_scheduler.go#L234), it **continues** checking even when predicate failed.  I know some reasons in issue #20064 and PR #29272. However, why not make it switchable to continue or abort? It could be more effective.

2. Based on 1., in some orders of predicates, it would be fast failed to abort checking. So why not use an array of predicates which is ordered instead of map? And we can adjust the order of predicateFuncs later.

I'm curious about the decision gathering all failed predicates.

**Comment by resouer** [comment]
So users are able to know status of its cluster at one time, instead of trying once again.
