### ISSUE TITLE
Generated shared informers lack an extension to provide additional indexes

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#48198]
Today, listers are generated with a `Expansion` interface which allows for custom listing methods.  These methods generally require custom indexes.  There is not a corresponding expansion or lookup in informers to provide the indexes.

The informer already has a dependency on the lister, so we should create a in the generated listers which returns `Additional<Type>Indexes` and respects information from the expansion.

@kubernetes/sig-api-machinery-misc

**Comment by deads2k** [comment]
Links here https://github.com/kubernetes/kubernetes/blob/master/pkg/client/listers/core/v1/pod.go#L34 and here https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/informers/core/v1/pod.go#L56 for code reference.

**Comment by ncdc** [comment]
That would definitely be better and clearer, but you can add additional indexes to the shared informer via something like `sharedInformers.Core().V1().Pods().Informer().AddIndexers()` (the type returned by the call to `Informer()` happens to be a `SharedIndexInformer`, which has the `AddIndexers` method).

**Comment by deads2k** [comment]
> That would definitely be better and clearer, but you can add additional indexes to the shared informer via something like sharedInformers.Core().V1().Pods().Informer().AddIndexers() (the type returned by the call to Informer() happens to be a SharedIndexInformer, which has the AddIndexers method).

That enables the informer as a side-effect of calling the method.  If you do that, then the lister/watcher will always come active even if you don't need it.  It also means that the lister won't always function properly with a shared informer unless someone externally twiddles that knob.

**Comment by ncdc** [comment]
I totally agree. I'm just pointing out that it's possible to do it today, but ugly.

**Comment by shiywang** [comment]
@deads2k sorry, just have some naive questions here. what is this `Additional<Type>Indexes`,  could you tell me more specific what kind of go type or method you want here ? every time I saw this `<>` just let me remind C++  template, and also what is this `Additional` means ?

**Comment by ncdc** [comment]
`<Type>` is an api type such as `Pod` or `Deployment`

**Comment by lavalamp** [comment]
While we're at it, do we really need multiple constructors for these informers?
