### ISSUE TITLE
Enable log rotate for container

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#48201]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature
/sig apps

**What happened**:
The logs in container cannot be rotated, docker already support this, it is better add this feature to kubernetes.

```
$ docker run -it --log-opt max-size=10m --log-opt max-file=3 busybox /bin/sh -c 'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 0.001; done'
```

More detail refer to: 

https://docs.docker.com/engine/admin/logging/overview/

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by crassirostris** [comment]
@gyliu513 What exactly would you like to see? Maybe I dedup this FR against https://github.com/kubernetes/kubernetes/issues/38495 or https://github.com/kubernetes/kubernetes/issues/15478?

**Comment by crassirostris** [comment]
BTW, logs _are_ rotated, either by logrotate tool or by docker, depending on the setup

**Comment by crassirostris** [comment]
BTW, logs _are_ rotated, either by logrotate tool or by docker, depending on the setup

**Comment by gyliu513** [comment]
Thanks @crassirostris , #38495 and #15478 is exactly what I want, I will close this one.
