### ISSUE TITLE
Mount chroot should use host resolv.conf

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#48212]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
NFS servers referenced via domain name, on GCE/GKE COS fail with:

```
Output: mount.nfs: Failed to resolve server <pod name>: Temporary failure in name resolution
```

**What you expected to happen**:
The mount utility should be able to resolve the domain name. 

**How to reproduce it (as minimally and precisely as possible)**:
Refer to an NFS server via domain name.

**Anything else we need to know?**:

Temporary work around: Copy the `/etc/resolv.conf` from the GCE VM (this will include the GCP search path, metadata DNS resolver) into the chroot env (`/home/kubernetes/containerized_mounter/rootfs)`).

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.6
- Cloud provider or hardware configuration**: GCE/GKE
- OS (e.g. from /etc/os-release): COS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jingxu97** [comment]
I actually have an old PR for this #42376, somehow it got skipped.

**Comment by jingxu97** [comment]
close this issue after PR is merged

**Comment by saad-ali** [comment]
This may not be fixed yet. @jingxu97 is investigating.

**Comment by monotek** [comment]
I also just run in this problem on Minikube & Google Kubernetes Engine. 
Both with version 1.8.3

**Comment by jingxu97** [comment]
After PR #42376 is merged, we can use nfs service name instead of hard coded IP address in client yaml file. But it must be the full DNS name, e.g., nfs-service.default.svc.cluster.local
Please see https://github.com/kubernetes/dns/blob/master/docs/specification.md for DNS name
