### ISSUE TITLE
Unstructured represents nil Object fields inconsistently

### ISSUE THREAD

**Issue by ironcladlou** [kubernetes/kubernetes#48211]
/kind bug

During the course of https://github.com/kubernetes/kubernetes/pull/48065, @ash2k [noted](https://github.com/kubernetes/kubernetes/pull/48065#issuecomment-311524304) that Unstructured is storing internal fields backing Object methods inconsistently with regards to nil. For example, SetOwnerReferences omits nil keys from the internal map, while SetInitializers, SetLabels, SetAnnotations, and SetDeletionTimestamp retain keys for nil values.

To remain consistent with marshalling behavior, we propose that Unstructured should omit keys for nil values internally for all fields which back Object methods.

/cc @ash2k @deads2k @caesarxuchao

**Comment by deads2k** [comment]
it should omit for nils that are `omitEmpty`, right?

@ash2k I couldn't assign you and @ironcladlou, you're assigned in spirit, so comment away :)

**Comment by ash2k** [comment]
> it should omit for nils that are omitEmpty, right?

@deads2k I'm not sure what `omitEmpty` you are talking about? Unstructured does not have any annotations/knowledge about contents of `Object` field so it just serializes it into JSON as is.

```go
func TestNil(t *testing.T) {
	u := Unstructured{
		Object: map[string]interface{}{
			"kind":       "Pod",
			"apiVersion": "v1",
			"metadata": map[string]interface{}{
				"name":              "test",
				//"deletionTimestamp": nil,
				"ownerReferences": []map[string]interface{}{
					{
						"controller": nil,
					},
				},
			},
		},
	}
	u.SetDeletionTimestamp(nil)
	data, _ := u.MarshalJSON()
	t.Logf("%s", data)
}
```
Outputs:
```
unstructured_test.go:58: {"apiVersion":"v1","kind":"Pod","metadata":{"deletionTimestamp":null,"name":"test","ownerReferences":[{"controller":null}]}}
```
I think its good to be consistent with how JSON is unmarshalled. Then code that retrieves data from the `map` does not need to handle `nil`s. At least not for primitive values like `int64`. Hm, what if actual JSON contains `null`? I guess the code still needs to handle `nil` (but not non-nil pointers!). Oh, well.
Anyway, I think its a good idea to not introduce new `nil` values into the map.

**Comment by deads2k** [comment]
@ash2k whether or not it is present is based on the omitEmpty tag here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L184.  If it isn't omit empty, you should write out an explicit nil.

**Comment by deads2k** [comment]
For fields we know about like type and objectMeta, it makes sense to remove.  I'm less certain of fields we don't have knowledge of which may or may not be omitEmpty.  Leaving it up to the caller seems to make sense.

**Comment by lavalamp** [comment]
I think code dealing with maps like this needs to handle both possibilities. That's just defensive coding :/

Functions can of course be written to make the error handling less verbose.
