### ISSUE TITLE
Improve user experience for creating / updating secrets

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#4822]
The serialized form of secret data is a base64 encoded string.  Currently this means that in order to create a secret, a user has to craft a json or yaml field containing their encoded secret data.  There should be a way for a user to create a secret from a set of cleartext files, binary files, or cleartext values specified from the command line.

**Comment by pmorie** [comment]
@liggit I know you have some opinions on this matter

**Comment by liggitt** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/4591/files#diff-24507fbfb739669903cc0ecbeb8769a5R77 is an example of what has to be done currently to create a secret

**Comment by liggitt** [comment]
Use cases off the top of my head:

1. Create a secret with specified keys mapped to contents of files
2. Create a secret with specified keys mapped to command-line data
3. Create a secret with a set of globbed files, using the filenames as keys

**Comment by pmorie** [comment]
@liggitt And presumably a switch to say whether a particular thing should be base64 encoded, yes?

**Comment by liggitt** [comment]
@pmorie I thought secrets always had to be base-64 encoded

**Comment by pmorie** [comment]
@liggitt they do but some users may have pre-encoded artifacts they want to
use for whatever reason

**Comment by bgrant0607** [comment]
This is config generation, similar to kubectl run-container and kubectl expose. The same pattern would work for this.

**Comment by pmorie** [comment]
@erictune @thockin fyi

**Comment by derekwaynecarr** [comment]
@sallyom is prototyping an openshift experimental command to let you bundle a secret from a directory, based on experience with that, we may look to push it upstream to Kubernetes for feedback

**Comment by erictune** [comment]
I wanted this last week.  Looking forward to it.

**Comment by bgrant0607** [comment]
This would be great. 

Per #7311 , it should be possible to invoke this via library call also, not just kubectl command.

**Comment by joltup** [comment]
+1...this is so necessary!

**Comment by derekwaynecarr** [comment]
If I push a secret command for kubectl is that subject to the v1 freeze?  

See: https://github.com/openshift/origin/blob/master/pkg/cmd/experimental/bundlesecret/bundle_secret.go

**Comment by thockin** [comment]
It becomes A triage issue - do we think the UX is bad enough that this is
necessary?  At a glance I feel probably not, but not strongly so.

**Comment by thockin** [comment]
I'll flag this a a 1.0 candidate, but I don't think it will fly.

**Comment by derekwaynecarr** [comment]
I just don't want to push something if it's not going to make it since there are other things I can look at pre-1.0.  Right now, there is NO end user experience to ease creation of secrets so was not sure if this fell under a general user experience bucket.  In practice, it is a pain to base64 and build JSON/Yaml.

Let me know, referenced command is not too big, but I can imagine nits on naming.  Right now, it's an experimental openshift command.

**Comment by pmorie** [comment]
I shoulda done something for this already :-/

**Comment by bgrant0607** [comment]
The code-complete deadline for 1.0 is basically Friday, so I'd prefer to defer this until after the big 1.0 push if possible.

**Comment by bgrant0607** [comment]
Previous attempt to do something in this space was #7975.

**Comment by bgrant0607** [comment]
More generally, I'd be happy to have support for "experimental" commands in kubectl.

I'll take a look at bundle-secret.

**Comment by bgrant0607** [comment]
I'd like to try to get this into 1.0. Does someone from the Redhat side have time to help?

cc @mikedanese

**Comment by liggitt** [comment]
We have a command to create a secret from a set of files and one to add a secret reference to a service account. I can open a PR tomorrow with them if you like. Would you prefer it under an experimental command group in kubectl?

**Comment by bgrant0607** [comment]
It doesn't need to be experimental.

In Openshift it has been moved to `osc secrets new`?

Why not `osc new secrets`, verb before noun, like the rest of our commands?

**Comment by sallyom** [comment]
I'm working on a different project now but glad to see this ;)

**Comment by liggitt** [comment]
> Why not osc new secrets, verb before noun, like the rest of our commands?

The existing `verb noun` commands apply generically to all types. Our `secrets [new | new-dockercfg | add]` commands are more akin to `kubectl config ...`, which groups a set of commands related to a particular object, and aren't generically applicable.

**Comment by bgrant0607** [comment]
I could imagine `new` being a generic generator invoker. 

I know `kubectl config` has a subcommand structure, but I'm not very comfortable with that approach without a principle that users could use to develop a mental model that would allow them to infer which pattern should be applied for a given operation. 

Maybe the principle for `config` could be that the commands in the group are just managing local state and not talking to the server.

What would the comparable principle be for secrets? Would the commands just create local files and the user would need to use a standard `kubectl create -f` to instantiate the secrets?

**Comment by bgrant0607** [comment]
For my reference, new command location:
https://github.com/openshift/origin/blob/master/pkg/cmd/cli/secrets/new.go

**Comment by liggitt** [comment]
Discussion of structure/behavior of generic `new` commands is related to https://github.com/GoogleCloudPlatform/kubernetes/issues/10495#issuecomment-117144285

**Comment by bgrant0607** [comment]
I've come around to the idea of command groups for related non-general-purpose commands, but I don't know that we need/want one in this case.

I'd like this to be of comparable convenience to run and expose, at least for the common use cases, such as imagePullSecrets. That implies to me that we probably don't want to bury the command(s) in a command group.

I don't think the generic `new` is relevant to this, either, at least not in the way I'm currently thinking about it -- I just updated #10495.

This could look something like `kubectl make-secret mysecret --dockercfg=...`. We could similarly add flags for other special cases like service accounts and kubeconfig. The generic case would be something like `kubectl make-secret mysecret --key=mysecretkey --secret-data-file=./mysecret.cert`. For adding to or updating an existing secret, we could perhaps add a `--update` flag.

**Comment by bgrant0607** [comment]
@kubernetes/rh-ux Does someone from your side have time to work on this?

**Comment by bgrant0607** [comment]
Example support issue where multiple people had trouble figuring out how to use imagePullSecrets: #12835

**Comment by pmorie** [comment]
@bgrant0607 I have bandwidth to work on this.

**Comment by bgrant0607** [comment]
Awesome. Thanks much, @pmorie.

FYI, we'll want something similar for the ConfigData resource (#6477) once it lands.

**Comment by pmorie** [comment]
Full disclosure: I haven't made progress on this yet.  Someone else may pick it up.

**Comment by derekwaynecarr** [comment]
I think I have some time this week to help close this out.

**Comment by derekwaynecarr** [comment]
@bgrant0607 

OpenShift has separate commands for generic secret creation versus dockercfg, basicauth, or sshauth secrets each with their own options.  

How do you feel about the following that combines the required options into a KEY=PAIR syntax for what we have downstream as separate commands.  Not sure if there is a problem with delimiter necessarily, but I think , separated should be fine.

```
kubectl make-secret NAME [KEY=]SOURCE ... [options]

Examples:
// Create a new secret named my-secret with keys for each file in folder "bar"
$ kubectl make-secret my-secret path/to/bar

// Create a new secret named my-secret with specified keys instead of names of keys on disk
$ kubectl make-secret my-secret key1=~/path/to/somefile key2=~/path/to/someotherfile

// Create a new secret named my-secret for use with a Docker registry
$ kubectl make-secret my-secret --dockercfg=email=jdoe,password=xyz,username=jdoe

// Create a new secret named my-secret for use in basic authentication
$ kubectl make-secret my-secret --basicauth=username=jdoe,password=foo,ca-cert=ca-cert.xyz

// Create a new secret named my-secret for use with git repositories
$ kubectl make-secret my-secret --gitconfig=path/to/.gitconfig

Options:
 --dockercfg=email=<email>,password=<password>,server=<server>,username=<username>
 --basicauth=username=<username>,password=<password>,ca-cert=<FILENAME>
 --sshauth=ssh-privatekey=<FILENAME>,ca-cert=<FILENAME>
 --gitconfig=<path/to/.gitconfig>
 ```

Thoughts?

**Comment by pmorie** [comment]
One challenge is different secret types have different logical schemas for keys.  What if we delegated the parsing to the actual secret type and have sensible options for opaque secrets?
A stab at what that might look like:

```
kubectl make-secret NAME [KEY=]SOURCE ... [options]

Examples:

// Create a new secret named my-secret with keys for each file in folder "bar"
$ kubectl make-secret my-secret --dir=path/to/bar

// Create a new secret named my-secret with specified keys
$ kubectl make-secret my-secret key1=foo key2=bar

// Create a new secret named my-secret with specified keys instead of names of keys on disk
// Totally willing to discuss the :file syntax
$ kubectl make-secret my-secret key1:file=~/path/to/somefile key2:file=~/path/to/someotherfile

// Create a new secret named my-secret for use with a Docker registry
// Does this validate that you supplied the right keys?
$ kubectl make-secret my-secret --type=dockercfg email=jdoe password=xyz username=jdoe

// Create a new secret named my-secret for use in basic authentication
$ kubectl make-secret my-secret --type=basicauth username=jdoe password=foo ca-cert:file=ca-cert.xyz

// Create a new secret named my-secret for use with git repositories
$ kubectl make-secret my-secret --type=gitconfig path/to/.gitconfig

Options:
 --dockercfg=email=<email>,password=<password>,server=<server>,username=<username>
 --basicauth=username=<username>,password=<password>,ca-cert=<FILENAME>
 --sshauth=ssh-privatekey=<FILENAME>,ca-cert=<FILENAME>
 --gitconfig=<path/to/.gitconfig>
  ... all the other traditional options ...
 ```

**Comment by bgrant0607** [comment]
Hmm. 

I don't know that we want to introduce a new option syntax that isn't flags and isn't json or yaml.

I've previously thought it would be useful to have a way to automatically translate API fields to kubectl flags to make kubectl easier to maintain as we add features, or to be able to take in json/yaml but without line breaks, without quoting, and with minimal punctuation generally. The latter might look like:
```
$ kubectl make-secret my-secret --type=dockercfg email:jdoe password:xyz username:jdoe
```

It doesn't feel as consistent as all flags, though, and help/documentation would look awkward.

Exploring the subcommand approach:

We could use make-secret as the command group and the secret type as the subcommand:
```
$ kubectl make-secret dockercfg my-secret --email=jdoe --password=xyz --username=jdoe
```

I thought somewhere there was an example with a secret command group, but I can't find it now. Maybe something like:
```
$ kubectl secret make-dockercfg my-secret --email=jdoe --password=xyz --username=jdoe
```

I prefer `make-secret`, but am open to discussion of pros and cons.

**Comment by pmorie** [comment]
I also prefer `make-secret`.

**Comment by smarterclayton** [comment]
Having three verbs (create, new, and make) where new and make are similar could lead to confusion.  I assume at some point in the future we will want to seed new with inputs that are driven by arguments.  Do we risk confusion by having multiple overlapping verbs that are used in similar contexts?  Perhaps we should create subcommands under create instead.

**Comment by pmorie** [comment]
> Perhaps we should create subcommands under create instead.

So, create with no subcommand stays the same and subcommands enable helpers for certain resources?

`kubectl create secret ...`

That seems reasonable at least to limit the proliferation of new high-level verbs

**Comment by smarterclayton** [comment]
It's probably easier to say that "create" is the mechanical (argument
driven) create approach, and "create" itself only allows "-f" today.

**Comment by bgrant0607** [comment]
What would this look like?
```
# new
kubectl create deployment --edit --name myappfe --labels "app=myapp,tier=fe"
# make-secret
kubectl create secret dockercfg ...
# make-configdata
kubectl create configdata ...
```

**Comment by smarterclayton** [comment]
One downside to stacking under create is that accidental arguments
(incorrectly specifying -f) might lead to an unexpected command.  The
benefit is that it's likely to fit with user's expectations that we've
established for other verbs.

**Comment by bgrant0607** [comment]
We should be careful to not reuse flags, such as `-f`, for different purposes. 

This pattern could also work for creating a namespace with no arguments (#10495):
```
kubectl create namespace
```
Though that might be error-prone if a user hit return accidentally before specifying `-f`, so we might want to require `--new` or `--default` or some other flag.

**Comment by derekwaynecarr** [comment]
@smarterclayton @bgrant0607 @deads2k  - I had hoped to spend time on this today in code, but I don't think we are there yet.

Assume the create <subcommand> pattern:

```
kubectl create namespace <name>
kubectl create secret opaque <name> -f path/to/bar
kubectl create secret opaque <name> key1=~/path/to/somefile key2=~/path/to/someotherfile
kubectl create secret dockercfg <name> --email=jdoe --password=xyz --username=jdoe
```

Major pain points:
1. we need a ```dry-run``` on all sub-commands.
2. inconsistency of short/long-form names with what the user sees in kubectl get.  If I can say, ```kubectl get ns``` or ```kubectl get po```, I would expect a similar ```kubectl create ns``` or ```kubectl create po``` command.  I think that type of use case is best matched with the ```kubectl new``` command that @DirectXMan12 was looking at that launches the editor with full resource.

I would prefer that all of our porcelain commands map to the verb that best corresponds to the noun.

For example:

| Resource | Verb |
| --- | --- | 
| secret | confide, whisper, gossip |
| namespace | organize, arrange, establish, partition |
| rc | run |
| service | expose |

So how do folks just feel about:

```
Usage:
  kubectl confide [options]

Available commands:
  kubectl confide opaque <name> -f path/to/bar
  kubectl confide opaque <name> key1=~/path/to/somefile key2=~/path/to/someotherfile
  kubectl confide dockercfg <name> --email=jdoe --password=xyz --username=jdoe
```

Thoughts?

**Comment by thockin** [comment]
"secret" is both a verb and a noun.
 So is "namespace".

Things like "run" are lovely because they abstract multiple
frequently-done-together steps.  "expose" is on the hairy edge of that, but
plausible.  "confide" feels "too cute" to me.

**Comment by derekwaynecarr** [comment]
@thockin - ```secrete``` is a verb. but I hope we are not discharging slimy substances.  ```secret``` is an adjective and a noun.  as for "confide" being cute, I updated the table with many options.  I would prefer either a single verb that expresses the concept, or a phrase ```make-secret```, but I think subcommands on create that dont have a 1:1 match with the values I can pass into kubectl get or kubectl delete is a user-fail.

**Comment by liggitt** [comment]
definitely also a verb - https://en.wiktionary.org/wiki/secret#Verb :)

**Comment by derekwaynecarr** [comment]
@liggitt - not according to Google https://www.google.com/search?q=divide&ie=utf-8&oe=utf-8#q=define+secret

**Comment by thockin** [comment]
"secret" is a valid verb, but is generally seen as obsolete.  "secrete"
actually means both "to emit a fluid" and "to conceal or hide", but I don't
think `kubectl secrete` is a good UX :).  `kubectl secret` otoh seems fine
to me.

**Comment by thockin** [comment]
pfft, like Google knows anything.

**Comment by thockin** [comment]
Caveat: I am just a user on this.  UX is not my area, and I have not thought deeply about it.  But I have used and scripted a lot of CLIs.

I sort of prefer the polymorphic nature of the earlier proposals, myself, though I might not overload "create".

`kubectl new secret foo --type=opaque -f key1=~/path/to/somefile -v key2=literal_value`

**Comment by ncdc** [comment]
Reping @kubernetes/rh-ux

**Comment by deads2k** [comment]
> I sort of prefer the polymorphic nature of the earlier proposals, myself, though I might not overload "create".
> 
> kubectl new secret foo --type=opaque -f key1=~/path/to/somefile -v key2=literal_value

I like the idea of a simple `kubectl new <subcommand-per-resource> args specific to resource` too.  

@derekwaynecarr didn't you have a proposal for that a while back?

**Comment by pmorie** [comment]
I kind of like `kubectl secrete`

**Comment by derekwaynecarr** [comment]
@deads2k - the new command is in this PR https://github.com/kubernetes/kubernetes/pull/14294

**Comment by pmorie** [comment]
In seriousness, I like what you proposed, @derekwaynecarr , but I am little unclear in the meaning of:

```
kubectl confide opaque <name> -f path/to/bar
```

Does a key get inferred from the filename?

**Comment by thockin** [comment]
We've already established that @pmorie has no taste :)

**Comment by pmorie** [comment]
> Things like "run" are lovely because they abstract multiple frequently-done-together steps. "expose" is on the hairy edge of that, but plausible.

@thockin I think `confide` meets the decision plane you described here.  If anyone can think of a better single word that expresses telling a secret, I'm all ears, but if we're bikeshedding the word to use, does that mean @derekwaynecarr has rung the bell otherwise?

**Comment by pmorie** [comment]
I do think this will eventually become a macro, case in point, say we make this add the secret to a service account as well?

**Comment by derekwaynecarr** [comment]
@pmorie
 
```
kubectl <confide | divulge | reveal | spill-the-beans> opaque <name> -f /path/to/bar
```

results in ```Secret``` whose ```SecretType``` is ```opaque``` and has keys for each file in folder "bar", so equivalanent to ```oc secrets new my-secret path/to/bar```

I think the macro extension to optionally associate it with a service account makes a lot of sense as that will be the next thing someone will want to do easily.

**Comment by thockin** [comment]
Adding a secret to a service account must be possible when the SA did not
exist at the time the secret was "confided".  So we necessarily need a
second command.  Frankly "confide" sounds more like "grant an SA access to
this secret"  but it's still "cute" and too anthropomorphic for my design
sense (but I could cope).

**Comment by derekwaynecarr** [comment]
@thockin - irony of Kubernetes project name from a company called Google whose parent is Alphabet is not lost on me this Friday afternoon.  the world is "too cute" for the guy whose Github picture is a cartoon ;-)

**Comment by derekwaynecarr** [comment]
@thockin - point on "adding existing secret to a service account" is well-taken, mulling on that some more.

**Comment by thockin** [comment]
I find the mixture of bare-word args and flags to be confusing.
Specifically "opaque" should be a --type flag in my mind.

We have poor consistency with regards to name.  `kubectl run NAME` vs
`kubectl expose pod foo --name NAME`.  Is the distinction that in run the
name is required and in expose it is not?    I would have (yay hindsight)
argued for `kubectl expose [NAME] --from pod/foo` or something for better
consistency.  That ship has sailed, so the rule of thumb feels like:
 required-name should be the first bare-word arg; optional name should be
--name; details about how to do an operation are flags; targets of
operations may be bareword args (e.g. expose pod foo - "pod foo" is the
target of the "expose").

**Comment by derekwaynecarr** [comment]
@thockin - my initial bias was --type as flag, but I think the issue was each type has different arguments that make sense, and we didnt want to invent a new flag syntax.  see reaction to https://github.com/kubernetes/kubernetes/issues/4822#issuecomment-144548003

**Comment by thockin** [comment]
puke.  yeah.  Is it so bad to have the flagset for "confide" (or whetever)
include flags for all values of --type, and just document which flags apply
to which --type?

**Comment by liggitt** [comment]
> Is it so bad to have the flagset for "confide" (or whetever) include flags for all values of --type, and just document which flags apply to which --type?

It gets really messy, which is why we ended up with subcommands per type

**Comment by pmorie** [comment]
@derekwaynecarr 

```
kubectl <confide | divulge | reveal | spill-the-beans> opaque <name> -f /path/to/bar
```

`whisper`?

**Comment by thockin** [comment]
I can see it both ways.  I concede that point.

**Comment by pmorie** [comment]
Bikeshedding lvl 999:

I actually like `confide` and `whisper` better than `divulge` or `reveal`

**Comment by bgrant0607** [comment]
How about `stash`: to store (something) safely and secretly in a specified place?

**Comment by derekwaynecarr** [comment]
@bgrant0607 - ```stash``` is good for me.

**Comment by pmorie** [comment]
+1 to stash

:trophy:

**Comment by thockin** [comment]
I still like "new" as the creation (but that opens the door for much more
discussion) and confide or grant as the way to assign to an SA.

Maybe I'm just wrong and "create" is the in-wall plumbing, "new" is exposed
plumbing, and "confide" or "secret" or "stash" is porcelain.

**Comment by thockin** [comment]
What about "deposit"?  as in to a vault.  Or "escrow"?  Nah.  "confide" or
"secret" have connotations that work.  "stash" is pretty generic, it might
as well be "store" or "hold".  "guard"?

**Comment by pmorie** [comment]
I'm afraid the trophy has already been awarded @thockin

**Comment by pmorie** [comment]
hrm

**Comment by pmorie** [comment]
I like deposit pretty well, actually.

**Comment by derekwaynecarr** [comment]
vault uses read/write - https://vaultproject.io/docs/commands/read-write.html

**Comment by bprashanth** [comment]
> I like deposit pretty well, actually.

wait no, i like bury. 
I kid I kid.

**Comment by ncdc** [comment]
I just had the same thought re bury, ha...

**Comment by bgrant0607** [comment]
`secret` would be the most obvious by far, and is a verb. Hopefully enough people have seen period British TV shows. Can we stop bikeshedding and just go with that?

`new` is taken for another purpose: #14294

**Comment by pmorie** [comment]
@bgrant0607 +1 to picking a new.  `secret` is fine with me.

**Comment by liggitt** [comment]
> `secret` would be the most obvious by far, and is a verb. Hopefully enough people have seen period British TV shows. Can we stop bikeshedding and just go with that?

jolly good

**Comment by pmorie** [comment]
![](http://i1.cdnds.net/14/02/618x387/uktv-blackadder-goes-forth.jpg)

**Comment by derekwaynecarr** [comment]
*secrets away to write a CLI command...

**Comment by ncdc** [comment]
@derekwaynecarr now that we've settled on the name, would it be worth circling back here with an updated set of usage examples?

**Comment by thockin** [comment]
http://www.columbia.edu/~xs23/benny.jpg

**Comment by derekwaynecarr** [comment]
@ncdc - will comment with an updated set of usage patterns.

**Comment by derekwaynecarr** [comment]
This is what a first PR would look like:

```
Create an opaque secret based on a file or directory
Usage:
  kubectl secret make NAME [options]

Examples:
  // Create a new secret named my-secret with keys for each file in folder "bar"
  $ kubectl secret make my-secret --from-file=path/to/bar

  // Create a new secret named my-secret with specified keys instead of names on disk
  $ kubectl secret make my-secret --from-file=key1=~/path/to/somefile --from-file=key2=~/path/to/someotherfile

  // Create a new secret named my-secret with specified literal values
  $ kubectl secret make my-secret --from-literal=key1=value1

Create a dockercfg secret with specified options
Usage:
  kubectl secret make-dockercfg NAME [options]

Examples:
  // Create a new secret named my-secret for use with a Docker registry
  $ kubectl secret make-dockercfg my-secret --email=jdoe --password=xyz --username=jdoe
```

It appears to meet the semantics @bgrant0607 expressed here:
https://github.com/kubernetes/kubernetes/issues/4822#issuecomment-144584226

It appears to satisfy the desires of @thockin as understood here:
https://github.com/kubernetes/kubernetes/issues/4822#issuecomment-148782470

It uses ```--from-file``` instead of ```source-file``` since we appear to use that somewhere in the project that cannot support a key=value pair.

OpenShift has additional subcommands for basicauth and sshauth secrets, but don't think that should block getting the initial syntax.  If we upstream that it can follow-on.

Similarly, OpenShift has 
```$ oc secrets add serviceaccount/sa-name secrets/secret-name --for=pull,mount```.  

Open for debate if you want:

```
[1] $ kubectl grant serviceaccount/sa-name --from=secrets/secret-name 
[2] $ kubectl secret add ...
[3] $ kubectl secret grant ...
```

Please ack if you are good on ```kubectl secret make``` above and will submit PR when done.

**Comment by ncdc** [comment]
If you do `--from-file=key1=/path/to/dir` is that a validation error because you're trying to assign a directory to a single key?

**Comment by derekwaynecarr** [comment]
@ncdc - yes, need to check if we do that in oc

**Comment by smarterclayton** [comment]
-1 on the cute proposals - our job is not to reach for a thesaurus, it's to
establish clear lines of meaning between the concept (secret) and the
interaction mechanism.

The reason why the "command noun verb <args>" shows up in a lot of places
is that new users often go looking for concepts (or see references to them
and try to find them in other places).  Few users, wanting to provide a
secret to the platform, would jump to "confide" unless they were of a
particularly literary bent.  Also, not all generic verbs are truly
generic.  We've already bent "expose" in OpenShift because it applies to
pods (as a service) or a service (as a route or ingress).  The overlap of
use creates additional flags (confusing, as David notes), or leads to
deeper hierarchy (kubectl new <type>, which fits for many users, but then
results in harder shortcuts).  The "concept command" encapsulates common
use cases with the concept, which is easy for a new user to locate (if i
want to work with secrets maybe i should run kubectl secrets -h) and easy
to reference for future (hey, I created a secret, if I want to use it maybe
I should go back).

Interactions with secrets are rarely one touch.  The three most likely are
"grant" (which has common overlap with policy, so would at some point need
to support both secrets or policy), "mount as volume" (which has common
overlap with PVC), or "export".  Both grant and mount as volume are likely
the immediate follow ups to a request to create a secret (and in fact, most
users would probably prefer a single action that creates a secret and
mounts it or shares it).  It's hard to predict every interaction that could
exist in the future with secrets (use secret with a build, or a third party
integration).

I'm not in love with the "concept command" as a top level... but generic
verbs have their limits, and we should be able to recognize when a generic
verb is insufficient.

**Comment by derekwaynecarr** [comment]
@smarterclayton - can you comment on the result I proposed "kubectl secret"
as parent command and "kubectl secret make" as opaque secret subcommand,
and "kubectl secret make-dockercfg" as the type specific secret syntax?  I
think it aligns with where discussion ended, and addresses @thockin
critique on oc secrets use of arguments where flags were preferred.

**Comment by smarterclayton** [comment]
Yes I'm ok with the current syntax at a high level.
