### ISSUE TITLE
Kubeadm Does Not Properly Form A Master Endpoint When Using IPv6

### ISSUE THREAD

**Issue by danehans** [kubernetes/kubernetes#48227]
kubeadm uses ip:port to create a master endpoint url. This works fine when using an ipv4 address but not for ipv6. According to [rfc 3386](https://www.ietf.org/rfc/rfc3986.txt), an ipv6 address should be encased in brackets when being joined by a port using a colon.

/area kubeadm
/area ipv6

**Comment by luxas** [comment]
@danehans Please open kubeadm issues in the https://github.com/kubernetes/kubeadm repo.
Thanks!
