### ISSUE TITLE
IPv6: client-go update to handle IPv6 addresses for PortForwarder

### ISSUE THREAD

**Issue by pmichali** [kubernetes/kubernetes#48225]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: When using IPv6 addresses, the kubelet passes the address to client-go, which does not correctly format the address for use in API requests.  For example:

Failed to list *v1.Pod: Get https://2001:129::136:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dnode136&resourceVersi
on=0: dial tcp: too many colons in address 2001:129::136:6443

**What you expected to happen**: The URI should have https://[2001:129::136]:6443, so that SplitHostPort() will correctly be able to separate the host and port components.

**How to reproduce it (as minimally and precisely as possible)**:
Create cluster using IPv6 address (e.g. kubeadm init --apiserver-advertise-address=2001:129::136). When the kubelet starts up, it'll log this error.

**Anything else we need to know?**:
This is being handled as part of effort to support IPv6 in Kubernetes. Was found by a co-worker, I'll work on a commit to fix.

**Environment**:
- Kubernetes version (use `kubectl version`): Using latest, via KubeAdm
- Cloud provider or hardware configuration**: bare-metal
- OS (e.g. from /etc/os-release): Ubuntu 16.04 
- Kernel (e.g. `uname -a`): 4.4.0-81-generic
- Install tools: Using KubeAdm
- Others:

**Comment by pmichali** [comment]
The point of failure is here:
```
// getListener creates a listener on the interface targeted by the given hostname on the given port with
// the given protocol. protocol is in net.Listen style which basically admits values like tcp, tcp4, tcp6
func (pf *PortForwarder) getListener(protocol string, hostname string, port *ForwardedPort) (net.Listener, error) {
    listener, err := net.Listen(protocol, fmt.Sprintf("%s:%d", hostname, port.Local))
    if err != nil {
        return nil, fmt.Errorf("Unable to create listener: Error %s", err)
    }
    listenerAddress := listener.Addr().String()
    host, localPort, _ := net.SplitHostPort(listenerAddress)
```

SplitHostPort will accept IPv4 and IPv6 addresses, but the latter must have square brackets around the IPv6 address.

**Comment by spiffxp** [comment]
/sig api-machinery
because client-go

**Comment by cmluciano** [comment]
Should we open this on the [client-go](https://github.com/kubernetes/client-go) repository?

**Comment by pmichali** [comment]
@cmluciano I see in the client-go repo read me that it states:

> Please send pull requests against the client packages in the Kubernetes main repository, and run the /staging/copy.sh script to update the staging area in the main repository. Changes in the staging area will be published to this repository every day.

Does that confirm that I should do a PR here?

**Comment by pmichali** [comment]
One thing that I was wonder, was whether or not the hostname/address provided in the call to getListener, has been validated.
```func (pf *PortForwarder) getListener(protocol string, **hostname** string, port *ForwardedPort) (net.Listener, error) {
```

If so, and it can only be a hostname, IPv4, or IPv6 address as a string, we could just check if there is a ":" in the name to determine IPv6. Otherwise, I could use net.ParseIP(), and net.To4() to determine if IPv6. I'll start working with the latter assumption, but please let me know, if the former could be used.

**Comment by pmichali** [comment]
Also, I'm making the assumption that we'd want to make client-go be able to handle IPv6 addresses, rather than having each user of client-go (e.g. kubelet) from ensuring that the IP address is of the right form.

IOW, have client-go add the needed [] around IPv6 addresses, rather than have kubelet do that. My thought is that there may be cases where we want just the IP address and not the modified IP.  Does that sound OK?
