### ISSUE TITLE
ingress-upgrade failed after changing subnetwork

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#48239]
Last night, all upgrade tests failed with 1.7 builds https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build-1.7/38. For example, the upgrade build https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gce-upgrade-cluster-new&include-filter-by-regex=-upgrade

started failing with build 79. We identified the culprit is subnetwork change: https://github.com/kubernetes/kubernetes/pull/48143#issuecomment-311607056

After merging the fix https://github.com/kubernetes/kubernetes/pull/48202, all upgrade tests passed as showing with build 86 and above at 

https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gce-upgrade-cluster-new&include-filter-by-regex=-upgrade

@gmarek @nicksardo @MrHohn Could you guys triage this issue?

**Comment by dchen1107** [comment]
culprit pr could be one(s) between commit-075d957b5891ef156cb1f6764187c77b02f4fb41 and commit 65fdb6ffd9e374030db147cfa97e324044eb68c2

**Comment by MrHohn** [comment]
Took a quick look at [build log](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1-6-1-7-upgrade-cluster-new/86?log#log), seems like the ingress test failed before upgrading master/nodes, which means commits in 1.7 branch might not matter:
```
I0628 19:49:55.733] Jun 28 19:21:32.843: INFO: host  path https://35.190.12.221/: Get https://35.190.12.221/: EOF unreachable
I0628 19:49:55.734] Jun 28 19:21:32.843: INFO: Unexpected error occurred: Failed to execute a successful GET within 15m0s, Last response body for https://35.190.12.221/, host :
I0628 19:49:55.734] 
I0628 19:49:55.734] 
I0628 19:49:55.734] timed out waiting for the condition
I0628 19:49:55.734] 
I0628 19:49:55.735] STEP: Deleting ingress
I0628 19:49:55.735] STEP: Cleaning up cloud resources
I0628 19:49:55.735] Jun 28 19:21:42.753: INFO: Monitoring glbc's cleanup of gce resources:
I0628 19:49:55.735] k8s-ig--f63312b71d28f1f6 (instance-group)
I0628 19:49:55.736] 
I0628 19:49:55.736] STEP: Performing final delete of any remaining resources
I0628 19:49:55.736] STEP: No resources leaked.
I0628 19:49:55.736] Jun 28 19:21:57.064: INFO: Deleting addresses: e2e-tests-ingress-upgrade-46vp2-static-ip
I0628 19:49:55.736] STEP: Starting disruption
I0628 19:49:55.737] Jun 28 19:22:04.327: INFO: Running /workspace/kubernetes_skew/cluster/gce/upgrade.sh [-M v1.7.0-rc.1.53+65fdb6ffd9e374]
I0628 19:49:55.737] == Pre-Upgrade Node OS and Kubelet Versions ==
I0628 19:49:55.737] name: "bootstrap-e2e-master", osImage: "Container-Optimized OS from Google", kubeletVersion: "v1.6.7-beta.0.34+913594700a1c30"
I0628 19:49:55.737] name: "bootstrap-e2e-minion-group-db98", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.6.7-beta.0.34+913594700a1c30"
I0628 19:49:55.738] name: "bootstrap-e2e-minion-group-q5g7", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.6.7-beta.0.34+913594700a1c30"
I0628 19:49:55.738] name: "bootstrap-e2e-minion-group-xpkr", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.6.7-beta.0.34+913594700a1c30"
```

**Comment by MrHohn** [comment]
Checked the corresponding GCE projects: `gce-up-c1-3-g1-4-up-clu-n` and `gke-up-g1-3-g1-4-up-clu`, etc., found many quota errors:
```
BACKEND_SERVICES quota limit reached
You have reached your quota limit for BACKEND_SERVICES.
```
So this is likely caused by leaking GCE resources instead of code changes.

**Comment by MrHohn** [comment]
It also seems this failure happened after the upgrade test frequency was increased.

My guess is that by increasing the frequency, there could be multiple clusters running within the same project in the same time. We soon hit the quota limit because each cluster will require backend service quota for ingress (default quota is 5).

**Comment by nicksardo** [comment]
Cleaning up old resources in the project.

**Comment by nicksardo** [comment]
GLBC cannot talk with the apiserver after upgrade, so it doesn't know to delete the ingress. Therefore, HTTP(S) resources leak and cause future tests to break. 

I can fix the logic for the test to teardown resources regardless of the GLBC; however, this isn't the root issue. Presumably that's #47379
