### ISSUE TITLE
Kubernetes terminating pods without explanation

### ISSUE THREAD

**Issue by michele** [kubernetes/kubernetes#48245]
/kind bug
/sig apps

**What happened**:

We're stress testing our API which is on a kube (1.5.2) cluster hosted on AWS. It's a blend of Rails and Go microservices.

When sending several hundreds requests per second something strange happens: all involved pods are responding correctly and averaging around 50ms, all seems fine, until some pods are (randomly, I'd say) restarted.

Upon checking the pods, it says:

```
    Last State:		Terminated
      Reason:		Completed
      Exit Code:	0
```

And running `kubectl logs pod-xxxxx --previous` shows the pod received a `SIGINT`.

All deployments are configured with a liveness probe, however these pods are not restarted because of this, because the events log doesn't show signs of unhealthiness. And if we try and stress the API above what it can handle, will get restarts because of unhealthiness and `describe pod` will show this.

Really, it seems like kube is just terminating the pods, but we are left with no clues as to why it's doing this.

**What you expected to happen**:

Pods shouldn't be randomly terminated, or if they are terminated for a reason which is not unhealthiness, out of resources, etc, it should explain why in the events log.

**How to reproduce it (as minimally and precisely as possible)**:

Basic cluster with a microservice-based web API. Several pods per deployment. Running tests with Locust.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Debian Jessie
- Kerne: `Linux ip-172-20-0-226 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u1 (2017-06-18) x86_64 GNU/Linux`
- Install tools: `kube-up`

**Comment by janetkuo** [comment]
/sig node 

I'm not sure what terminated the container. Maybe sig nodes team can help answer this quesiton. Would kubelet ever send `SIGINT`? @kubernetes/sig-node-bugs

**Comment by JTarasovic** [comment]
To add a second data point, I also run clusters in AWS and am seeing the same thing. It seems to happen during rolling upgrades where pods will get reshuffled to different nodes.

I also see that the pod(s) get sent a `SIGINT` and terminate gracefully; leaving it in a Completed state without any events that would indicate why it is "Completed".

I am running 1.6.4 in both clusters. 

**Environment**:
- Kubernetes version (use `kubectl version`): 
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4+coreos.0", GitCommit:"8996efde382d88f0baef1f015ae801488fcad8c4", GitTreeState:"clean", BuildDate:"2017-05-19T21:11:20Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): container linux
- Kernel (e.g. `uname -a`): 4.11

**Comment by thiagoalves** [comment]
/reopen /remove-lifecycle rotten

This is what I get in Kubelet logs

```
Aug  8 21:48:03 sw16 kubelet-wrapper.sh[3020]: I0808 21:48:03.197371    3020 kubelet.go:1853] SyncLoop (DELETE, "api"): "devspaces-7xmzakto-0_devspace-staging(5871738d-9b54-11e8-90bc-12642777bb76)"
```

and inside the Pod container

```
2018-08-08T21:32:27.829+0000 I CONTROL  [signalProcessingThread] got signal 15 (Terminated), will terminate after current cmd ends
2018-08-08T21:32:27.829+0000 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
2018-08-08T21:32:27.829+0000 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-27017.sock
2018-08-08T21:32:27.830+0000 I CONTROL  [signalProcessingThread] Shutting down free monitoring
2018-08-08T21:32:27.830+0000 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
2018-08-08T21:32:27.835+0000 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
2018-08-08T21:32:27.945+0000 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
2018-08-08T21:32:27.945+0000 I CONTROL  [signalProcessingThread] now exiting
2018-08-08T21:32:27.945+0000 I CONTROL  [signalProcessingThread] shutting down with code:0
```

Not sure how to get more info about who or what is terminating the Pods

**Comment by chrissnell** [comment]
This has been happening to me as well.  Random SIGINT terminations.  We are running cluster autoscaling and these happen as the cluster scales.  I capture logs from everything and see no relevant logs from any Kube components when this happens.  Just the SIGINT in the pod itself.

**Comment by chrissnell** [comment]
Oddly, like @thiagoalves, I'm seeing these in a MongoDB container, too.

**Comment by chrissnell** [comment]
@thiagoalves - can you try the `/reopen` and the `/remove-lifecycle rotten` commands on individual lines?  I don't think the bot parsed them correctly and I'd like to see this re-opened.

**Comment by ryanmahan** [comment]
@thiagoalves did you ever find out what was causing those logs? I have the same problem on my k8s instance with a mongo helm chart.

**Comment by thiagoalves** [comment]
@ryanmahan Unfortunately it's been 1.5 years since I posted the logs and I don't remember the details :(

**Comment by VassilisVassiliadis** [comment]
@ryanmahan It's hard to say, but the pods were probably getting evicted because they were not in the `Guaranteed` QoS class.

Check this out for more information https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed

**Comment by khaderkhan** [comment]
My pods are running on GCP and I'm getting this error since the past 12+ hours. It was working perfectly fine before that. 
`Port:           3000/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 03 Feb 2020 14:09:08 +0530
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 03 Feb 2020 14:02:51 +0530
      Finished:     Mon, 03 Feb 2020 14:04:07 +0530
    Ready:          False
    Restart Count:  8`
What could be the reason for this?
