### ISSUE TITLE
Not getting external IP in nginx-https example

### ISSUE THREAD

**Issue by Pensu** [kubernetes/kubernetes#48257]
Hi,

I am trying to run nginx-https example, I am running in on local cluster. Local cluster is being run using ./hack/local-up-cluster script. Now, I am able to run rc and pod and service, but I can't see the external IP in svc.

```
# cluster/kubectl.sh get svc
NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)                      AGE
kubernetes   10.0.0.1     <none>        443/TCP                      2h
nginxsvc     10.0.0.128   <nodes>       80:30283/TCP,443:31491/TCP   2h
```

Any idea what could be going wrong here? Or where to start debugging?

**Comment by kargakis** [comment]
/sig apps

Please reopen this issue in https://github.com/kubernetes/examples
