### ISSUE TITLE
kubectl logs

### ISSUE THREAD

**Issue by jiaqianjing** [kubernetes/kubernetes#48252]
**What happened**:
It's looks like time out when I used `kubectl log  xxxx`.But I can get logs  from using `docker logs xxxx` on the work node. I am not sure about principle of `kubectl logs`. 
Is it related to flanneld's network?  And my docker log-driver used journald.
How does `kubectl logs xxx` work

**Anything else we need to know?**:

**Environment**:
- Docker version 
```
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-59.el7.centos.x86_64
 Go version:      go1.6.3
 Git commit:      3999ccb-unsupported
 Built:           Thu Dec 15 17:24:43 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-59.el7.centos.x86_64
 Go version:      go1.6.3
 Git commit:      3999ccb-unsupported
 Built:           Thu Dec 15 17:24:43 2016
 OS/Arch:         linux/amd64
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.4.19899+2aa99337bd8dd4", GitCommit:"2aa99337bd8dd43ec378ba1df6570df214828548", GitTreeState:"clean", BuildDate:"2017-01-16T01:36:45Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.4.19899+2aa99337bd8dd4", GitCommit:"2aa99337bd8dd43ec378ba1df6570df214828548", GitTreeState:"clean", BuildDate:"2017-01-16T01:36:45Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux minion-gpu-18 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by spzala** [comment]
@jiaqianjing hello, this looks like a question that should be asked on the https://stackoverflow.com/questions/tagged/kubernetes or other places recommended in the https://github.com/kubernetes/community/blob/master/contributors/devel/on-call-user-support.md Asking question there will hopefully provide a quicker answer. If that looks good to you, can we please close this issue as it can not really be validated as a bug. Thanks!

**Comment by jiaqianjing** [comment]
@spzala thx, you can close this issue.

**Comment by spzala** [comment]
Thanks @jiaqianjing ! @grodrigues3 can you please close the issue since I do not have privilege to close? Thanks!

**Comment by spzala** [comment]
Thanks @jiaqianjing
