### ISSUE TITLE
Move pkg/apimachinery/test to apimachinery.

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#48265]
Tests in https://github.com/kubernetes/kubernetes/tree/master/pkg/apimachinery/tests were placed there because they relied on kubernetes types, but the intent of the tests is to test API machinery.  They should be refactored to remove the cycle and moved to unit tests in the `staging/src/k8s.io/apimachinery`.

**Comment by deads2k** [comment]
@shiywang

**Comment by shiywang** [comment]
hey @deads2k I met some cycle dependency problem while I working on this one
```console
import cycle not allowed in test
package k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime (test)
imports k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1
imports k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime
```
tree 
k8s.io/apimachinery/pkg
├── api
├── apimachinery
├── apis
│   └── meta
│       ├── internalversion
│       ├── v1           -------> previously rely some package from k8s.io/apimachinery/pkg/runtime
│       │   ├── unstructured
│       │   └── validation
│       └── v1alpha1
├── runtime    -----------> after move [runtime_unversioned_test.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/apimachinery/tests/runtime_unversioned_test.go) here, caused cycle dependency problem

I check this runtime_unversioned_test.go test file, it just use `metav1.Status` for some encode decode tests, there's two workaround I come up with one is bump this `metav1.Status` to remove `imports k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1`  
another way is move all those https://github.com/kubernetes/kubernetes/tree/master/pkg/apimachinery/tests into a dependent directory.
@deads2k do you have some suggestions ?

**Comment by deads2k** [comment]
> @deads2k do you have some suggestions ?

As long as the tests end up in `k8s.io/apimachinery` somewhere, if you have to create a separate test package for them at the moment, that's an acceptable outcome.  Also, I suspect that if you simply named the test package (inside the test folder) `runtime_test` it would work.
