### ISSUE TITLE
Allow adding tolerations to stateful sets

### ISSUE THREAD

**Issue by ashic** [kubernetes/kubernetes#48268]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature Request

/kind feature

I have a yaml file for a stateful set. I'm trying to add a toleration to it. 

**What happened**:

When I run kubectl apply -f file.yaml, I get the following error:

```
The StatefulSet "stateful-set-1" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas' and 'containers' are forbidden.
```

**What you expected to happen**:

I expect the pods to have the specified tolerations applied.

**How to reproduce it (as minimally and precisely as possible)**:
* Create a stateful set via a yaml file.
* Once created, change the file to add a toleration. Try applying it.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration**:
AWS EC2 with kops.

**Comment by kargakis** [comment]
In 1.6, the pod template spec is locked down to just the image field. It should be possible to update tolerations in 1.7 cc: @kow3ns
