### ISSUE TITLE
kubelet cert issue caused serial-release-1-7 failure

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#48282]
Failed serial test run: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial-release-1-7/107

node minion-group-bxn4 didn't come back after restart and caused the failure

In the [kubelet log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial-release-1-7/107/artifacts/bootstrap-e2e-minion-group-bxn4/kubelet.log), the node was back but kubelet failed to register the node with apiserver:

```
E0629 05:29:43.583645    2413 kubelet_node_status.go:106] Unable to register node "bootstrap-e2e-minion-group-bxn4" with API server: Post https://35.192.63.12/api/v1/nodes: x509: certificate signed by unknown authority
```

Might be a one-time flake.

cc @dchen1107 @mikedanese

**Comment by carldanley** [comment]
I'm also getting:

```
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
```

Fresh `kubeadm init`. My comment *may* be unrelated but I wasn't sure so dropped a comment here anyways. I've even reinstalled everything 2-3 times and still same issue, just won't generate a good cert.

**Comment by ConorNevin** [comment]
I'm also gettting this error with `kubeadm join` on a fresh 1.7 cluster

**Comment by jackjacek** [comment]
I'm also getting that after upgrade. Any workarounds? I can't start any pods anymore, even though kubectl works fine.

**Comment by roberthbailey** [comment]
@kubernetes/sig-cluster-lifecycle-bugs

**Comment by mikedanese** [comment]
kubeadm join returning `x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error"` is unrelated to this bug. They just coincidentally return the same error message. Please file a new bug in github.com/kubernetes/kubeadm if you are still seeing this.

**Comment by liggitt** [comment]
@mikedanese is this still an issue?

**Comment by mikedanese** [comment]
This issue is obsolete. Let's open a new one if we still see this.
