### ISSUE TITLE
Determine SIG escalation paths for issues impacting test infrastructure

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#48283]
As part of the governance discussions we are driving all assets and processes of the Kubernetes project to be owned by SIGs.  Ownership of the test-infrastructure is tentatively defined as owned by sig/testing.  However we need to get consensus on if this is the correct SIG, and define the scope of what the SIG owns.  E.g. configuration of common test jobs, gcp quota, etc

**Comment by spiffxp** [comment]
This would be useful info to help flesh out kubernetes/test-infra#3349
