### ISSUE TITLE
Links in v1.7.0 CHANGELOG are all in bad markdown format

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#48325]
See: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md/#v170

All the links are shown like below format.

`([#39164](https://github.com/kubernetes/kubernetes/pull/39164), [@danwinship](https://github.com/danwinship))`

/cc @dchen1107 
@kubernetes/kubernetes-release-managers

**Comment by luxas** [comment]
@xiangpengzhao Can/will you fix this?

**Comment by xiangpengzhao** [comment]
@luxas I'd like to, but TBH, there are so many such broken formats. I haven't find a quick way to fix them yet.

Seems like the root cause is the CHANGELOG of v1.7 is copied from google docs and the original content of the doc isn't raw markdown format. Those links are double linked in the doc.

So IMO we'd better un-link these links in the original doc first.

@caesarxuchao any thoughts?

**Comment by idvoretskyi** [comment]
cc @calebamiles

**Comment by xiangpengzhao** [comment]
regex saves my life, will send a PR.
