### ISSUE TITLE
Namespaces selfLink is missing a path delimiter

### ISSUE THREAD

**Issue by CallMeFoxie** [kubernetes/kubernetes#48321]
/kind bug

Hi, I think I've run into a wrong selfLink generator, kubernetes 1.6.4 and 1.6.6, did not test 1.7.0 yet.

`curl -sS localhost:8080/api/v1/namespaces/default | jq .metadata.selfLink`
"/api/v1/namespacesdefault"

should be /api/v1/namespaces/default

Whole output:
`{
  "kind": "Namespace",
  "apiVersion": "v1",
  "metadata": {
    "name": "default",
    "selfLink": "/api/v1/namespacesdefault",
    "uid": "96bd5329-ee9c-11e6-b3a9-842b2bfe82f1",
    "resourceVersion": "54",
    "creationTimestamp": "2017-02-09T07:51:39Z"
  },
  "spec": {
    "finalizers": [
      "kubernetes"
    ]
  },
  "status": {
    "phase": "Active"
  }
`

Same goes for listing namespaces:
`curl -sS localhost:8080/api/v1/namespaces | jq .items[1].metadata.selfLink`
"/api/v1/namespacesdefault"

Did not manage to find it in any other selfLinks. (Happens with any namespace listing, not just default.)

Cheers
Ashley

**Comment by CallMeFoxie** [comment]
OK it seems to be fine in v1.7.0, can be probably closed :)

**Comment by lavalamp** [comment]
If there's not a test, there should be.
