### ISSUE TITLE
Security hole when use NodePort to access service

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#48332]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

There is a security hole when using the host NodePort mode service:

1) Create a service and use NodePort.
2) After the service created, normal user will get the host IP address and one NodePort which in 31000 - 32000
3) Normal user can use tool to access this node IP with other port which in 31000 - 32000 as well, it is not safe.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dixudx** [comment]
This is inevitable. As long as we know the IP, we can scan the host to discover the ports and services, using tools like **nmap**. For such exposed services, TLS + AuthX are better added.

**Comment by gyliu513** [comment]
Thanks @dixudx I see, any comments for how to enable the NodePort services with TLS + AuthX?

**Comment by cmluciano** [comment]
@gyliu513 

[Openshift article](https://docs.openshift.com/container-platform/3.4/admin_guide/ipsec.html)
istio.io for more service-to-service use-case

**Comment by gyliu513** [comment]
Thanks @cmluciano , close this one now
