### ISSUE TITLE
Kubernetes 1.7.0 local storage teardown failed

### ISSUE THREAD

**Issue by CallMeFoxie** [kubernetes/kubernetes#48331]
/kind bug

Tearing down (for example simple updating pods in stateful set) of local-storage PVC seems to be broken:

> I0630 10:46:44.480172   24010 reconciler.go:186] operationExecutor.UnmountVolume started for volume "test" (UniqueName: "kubernetes.io/local-volume/97513921-5d70-11e7-a549-180373f4ecc0-test-affinity-test-1") pod "97513921-5d70-11e7-a549-180373f4ecc0" (UID: "97513921-5d70-11e7-a549-180373f4ecc0") 
> I0630 10:46:44.480243   24010 local.go:271] Unmounting volume "test-affinity-test-1" at path "/www/adm/kubernetes/root/pods/97513921-5d70-11e7-a549-> 180373f4ecc0/volumes/kubernetes.io~local-volume/test-affinity-test-1"
W0630 10:46:44.480277   24010 util.go:87] Warning: "/www/adm/kubernetes/root/pods/97513921-5d70-11e7-a549-180373f4ecc0/volumes/kubernetes.io~local-volume/test-affinity-test-1" is not a mountpoint, deleting
> E0630 10:46:44.480328   24010 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/local-volume/97513921-5d70-11e7-a549-180373f4ecc0-test-affinity-test-1\" (\"97513921-5d70-11e7-a549-180373f4ecc0\")" failed. No retries permitted until 2017-06-30 10:46:48.48030593 +0200 CEST (durationBeforeRetry 4s). Error: UnmountVolume.TearDown failed for volume "test" (UniqueName: "kubernetes.io/local-volume/97513921-5d70-11e7-a549-180373f4ecc0-test-affinity-test-1") pod "97513921-5d70-11e7-a549-180373f4ecc0" (UID: "97513921-5d70-11e7-a549-180373f4ecc0") : remove /www/adm/kubernetes/root/pods/97513921-5d70-11e7-a549-180373f4ecc0/volumes/kubernetes.io~local-volume/test-affinity-test-1: device or resource busy

I've managed to track it down to
pkg/volume/local/local.go calling through some pkg/volume/util/util.go  mounter.IsLikelyNotMountPoint(dir)

which literally has written in its comments:
> // IsLikelyNotMountPoint determines if a directory is not a mountpoint.
> // It is fast but not necessarily ALWAYS correct. If the path is in fact
> // a bind mount from one part of a mount to another it will not be detected.
> // mkdir /tmp/a /tmp/b; mount --bin /tmp/a /tmp/b; IsLikelyNotMountPoint("/tmp/b")
> // will return true. When in fact /tmp/b is a mount point. If this situation
> // if of interest to you, don't use this function...

which makes it detect it as a normal directory rather than a mount dir (as it is a normal directory... just bind mounted)

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.0
- Cloud provider or hardware configuration**: self hosted

Testing out a (dirty?) patch as we're speaking

**Comment by CallMeFoxie** [comment]
The dirt fix is to call unmount on the mounter directly as if it fails it returns False anyway:
`
diff --git a/pkg/volume/local/local.go b/pkg/volume/local/local.go
index bf23136..a0629c6 100644
--- a/pkg/volume/local/local.go
+++ b/pkg/volume/local/local.go
@@ -28,7 +28,6 @@ import (
 	"k8s.io/kubernetes/pkg/util/mount"
 	"k8s.io/kubernetes/pkg/util/strings"
 	"k8s.io/kubernetes/pkg/volume"
-	"k8s.io/kubernetes/pkg/volume/util"
 	"k8s.io/kubernetes/pkg/volume/validation"
 )
 
@@ -269,5 +268,6 @@ func (u *localVolumeUnmounter) TearDown() error {
 // TearDownAt unmounts the bind mount
 func (u *localVolumeUnmounter) TearDownAt(dir string) error {
 	glog.V(4).Infof("Unmounting volume %q at path %q\n", u.volName, dir)
-	return util.UnmountPath(dir, u.mounter)
+	//return util.UnmountPath(dir, u.mounter)
+	return u.mounter.Unmount(dir);
 }
`

I am trying to come up with a better solution than this but all boils down to the fact that if you bind mount /var/storage/local -> /var/lib/kubernetes/.../volumes/..-local-storage/ it will still be the same Dev, so that cannot be used either.
The best solution is to read /proc/mounts or from getmntent() syscall structure.
Or just force try to unmount it as the patch above does?

If it is OK I can make a PR for it.

**Comment by ianchakeres** [comment]
I experienced this issue while writing some e2e tests - https://github.com/kubernetes/kubernetes/pull/47999

These tests can be used to reproduce the issue on GCE.

The run-one-command pod tests succeed (e.g. "when one pod requests one prebound PVC), while the pods that are created and deleted independently end up encountering this bug.

For example,
Context("when two pods request one prebound PVC one after other"
Context("when two pods request one prebound PVC at the same time"

@msau42 @jeffvance

**Comment by CallMeFoxie** [comment]
I am unsure if this fix fixes the GCE issues as well as I've never used GCE (or AWS for that matter) but it seems to fix it for self hosted kubernetes.

Can make it into PR if it's a reasonable fix? Only unsure about the err at opening /proc/mounts - not sure how it behaves on GCE/AWS/within docker.

**Comment by ianchakeres** [comment]
@CallMeFoxie - Let's reuse listProcMounts(procMountsPath) to get all the info from /proc/mounts. 

Yes. Let's get a PR, and I'll test it on GCE. 

You want to submit the PR or should I?

**Comment by ianchakeres** [comment]
Here's the code I'm testing.
```        
        mountPoints := listProcMounts(procMountsPath)
        for _, mp := range mountPoints {
            if mp.Path == file {
               return false, nil
            }
	}
```

**Comment by msau42** [comment]
If I understand correctly, the issue is if the underlying directory is a just a dir and not a mount point, and you bind mount that, then IsLikelyNotMountPoint() will detect it as a directory instead of a mount.

If that's the case, I'm curious why Ian's tests are only running into this problem in the case of two pods accessing the same volume.

**Comment by msau42** [comment]
For the fix, I would prefer that a new method is used instead of IsLikelyNotMountPoint(). It is being used by other plugins and having to iterate through all the mounts on a node could impact performance.  Also it is only the local storage plugin where the underyling directory may not be a mount point.

**Comment by ianchakeres** [comment]
@msau42 The tests are failing even if I run one pod after the other. I'll create a test that just uses one pod with create and destroy (instead of one-command pod) to see if I can repro the error.

**Comment by msau42** [comment]
Ok, sounds like this is just a generic issue than with non-mount point local volumes then, which fits in with the root cause.

**Comment by msau42** [comment]
Btw, I noticed in the common `Unmount` method, that if it thinks it is not a mount point, then it's going to go and delete all the contents of the directory.  This is definitely not the behavior we want because the directory cleanup should only happen when the PV gets released and not during unmount.

So we should definitely get a fix into the next 1.7 patch.

cc @saad-ali

**Comment by msau42** [comment]
Actually nevermind, the unmount calls `os.Remove`, not `os.RemoveAll`, so it's not as bad.  Sorry for the scare.

**Comment by arunmk** [comment]
Is there a way to know the release for which this fix is scheduled?

Thanks
