### ISSUE TITLE
Add API endpoint to allow Pre-pulling an image to node(s)

### ISSUE THREAD

**Issue by ilackarms** [kubernetes/kubernetes#48349]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature request

/kind feature

**Anything else we need to know?**:
Cold start (first pod pull / launch) can be very slow, especially for large images. It would be nice to be able to pre-pull the image to any/all nodes in the cluster (expose the CRI PullImage through the kubelet, bubble it up through the apisever). Currently as a workaround I have to run a daemonset with a `sleep`  entrypoint in order to achieve this.

**Comment by luxas** [comment]
This should not be about the client implementing the feature but about the server implementing the feature as we discussed. Please update the description accordingly

**Comment by luxas** [comment]
cc @kubernetes/sig-node-feature-requests 

@ilackarms Could you still elaborate in the description what you want?
Describe what a "Pull API" in the Kubelet API could look like, etc.

**Comment by ilackarms** [comment]
@luxas 

we have [`ImageManagerService.PullImage`](https://github.com/kubernetes/kubernetes/blob/f75478875a3a60fb7eec7e5891c06ea0bf1832b1/pkg/kubelet/apis/cri/services.go#L108)  which is currently only invoked (afaict) in  [`kubeGenericRuntimeManager.startContainer`](https://github.com/kubernetes/kubernetes/blob/df41787b1a3f51b73fb6db8a2203f0a7c7c92931/pkg/kubelet/kuberuntime/kuberuntime_container.go#L90https://github.com/kubernetes/kubernetes/blob/df41787b1a3f51b73fb6db8a2203f0a7c7c92931/pkg/kubelet/kuberuntime/kuberuntime_container.go#L90).

I'm not super familiar with the API of the kubelet; however I assume there's some REST/HTTP api for invoking container start (consumed internally by kube-scheduler?) on the kubelet. Either this, or kubelets watch ETCD for "Desired" container, and pick up changes in ETCD.

In the first case (controlling kubelet via its REST API): add a `POST` `/api/<version>/images/pull/:image_name` endpoint which directly invokes `ImageManagerService.PullImage` on the kubelet (user provides an image spec / name via request body or request path).

In the second case (kubelet self-manages based on watching ETCD), create a new task type for kubelet (e.g. PrePullImage, PullImage) that can be created through an api call to the apiserver (e.g. `POST` `/api/v1/images/prepull/:image_name`). kubelet watches ETCD for this task type and runs a pre-pull accordingly.

Does this design sound more or less acceptable?

**Comment by luxas** [comment]
@yujuhong @Random-Liu ^

**Comment by spxtr** [comment]
@kubernetes/sig-node-feature-requests

**Comment by spxtr** [comment]
@kubernetes/sig-node-feature-requests

**Comment by spxtr** [comment]
@kubernetes/sig-node-feature-requests

**Comment by spxtr** [comment]
@kubernetes/sig-node-feature-requests
