### ISSUE TITLE
Building k8s 1.7.0 use docker  on mac failed 

### ISSUE THREAD

**Issue by Aleishus** [kubernetes/kubernetes#48342]
/kind bug
/sig cli

I use the script "build/run.sh make" to build k8s 1.7 failed . My os is Osx 10.12.5 and I user docker for mac to build .
I find  the function in script  "https://github.com/kubernetes/kubernetes/blob/v1.7.0/build/common.sh" has some problem. 
```bash
function kube::build::destroy_container() {
  "${DOCKER[@]}" kill "$1" >/dev/null 2>&1 || true
  "${DOCKER[@]}" wait "$1" >/dev/null 2>&1 || true
  "${DOCKER[@]}" rm -f -v "$1" >/dev/null 2>&1 || true
}
```
if the container does not exist  ,the command `docker wait $1` will wait forever.
my docker version is :
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by ianchakeres** [comment]
Here's the related issue on docker, https://github.com/docker/for-mac/issues/1714

**Comment by cblecker** [comment]
This looks to be resolved in https://github.com/docker/docker-ce/releases/tag/v17.06.1-ce
/close
