### ISSUE TITLE
Kubelet failing to update pod with updated configmap in large cluster

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#48359]
Ref https://github.com/kubernetes/kubernetes/issues/47344#issuecomment-312349193

This is in regard to the following e2e tests checking configmap(/secret/projected) update being reflected in pod volume:
[k8s.io] ConfigMap updates should be reflected in volume [Conformance] [Volume]
[k8s.io] ConfigMap optional updates should be reflected in volume [Conformance] [Volume]
(similar ones for secret,projected)

This one's the last correctness test (on 5k-node cluster) that needs fixing :)
The logs for the run are here - http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-enormous-cluster/13/
We are using n1-standard-1 nodes running all default daemons.

cc @kubernetes/sig-node-bugs @kubernetes/sig-scalability-misc @dchen1107

**Comment by shyamjvs** [comment]
I tried digging up a bit and from the [kubelet logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-enormous-cluster/13/artifacts/_artifacts/e2e-enormous-cluster-minion-group-7ps3/kubelet.log) on the node where the pod (for the configmap test) was created, it seems like the pod's container crashed:

```
..
I0627 23:48:36.124587    1501 operation_generator.go:472] MountVolume.SetUp succeeded for volume "configmap-volume" (UniqueName: "kubernetes.io/configmap/22bd6f6e-5b93-11e7-813a-42010a8e0002-configmap-volume") pod "pod-configmaps-22ba0b69-5b93-11e7-8c06-0242ac110007" (UID: "22bd6f6e-5b93-11e7-813a-42010a8e0002")
I0627 23:48:36.132181    1501 operation_generator.go:472] MountVolume.SetUp succeeded for volume "default-token-dz5v3" (UniqueName: "kubernetes.io/secret/22bd6f6e-5b93-11e7-813a-42010a8e0002-default-token-dz5v3") pod "pod-configmaps-22ba0b69-5b93-11e7-8c06-0242ac110007" (UID: "22bd6f6e-5b93-11e7-813a-42010a8e0002")
I0627 23:48:36.262978    1501 kuberuntime_manager.go:457] Container {Name:configmap-volume-test Image:gcr.io/google_containers/mounttest:0.8 Command:[/mt --break_on_expected_content=false --retry_time=120 --file_content_in_loop=/etc/configmap-volume/data-1] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:configmap-volume ReadOnly:true MountPath:/etc/configmap-volume SubPath:} {Name:default-token-dz5v3 ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
```

even before the configmap was updated:
```
I0627 16:48:35.828] [It] updates should be reflected in volume [Conformance] [Volume]
I0627 16:48:35.828]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/configmap.go:155
I0627 16:48:35.828] [1mSTEP[0m: Creating configMap with name configmap-test-upd-22aea69a-5b93-11e7-8c06-0242ac110007
I0627 16:48:35.903] [1mSTEP[0m: Creating the pod
I0627 16:48:38.102] [1mSTEP[0m: Updating configmap configmap-test-upd-22aea69a-5b93-11e7-8c06-0242ac110007
I0627 16:48:38.141] [1mSTEP[0m: waiting to observe update in volume
I0627 16:53:38.143] [AfterEach] [k8s.io] ConfigMap
```

@yujuhong Could you take a look into this if possible? :)

**Comment by shyamjvs** [comment]
cc @wojtek-t

**Comment by shyamjvs** [comment]
Figured out the reason for the failure. It's because of the '--retry_time=120' argument to the container command in the test pod (ref https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/secrets.go#L265) which is leading to the pod entering success status 2m after it's started. So we don't even give enough time for the secret to get updated by kubelet before the pod terminates.

**Comment by shyamjvs** [comment]
I've tested (on the currently running 5k node cluster) with the retry time increased to podLogTimeout (= 540s) and it works. I'll send out a PR fixing this and also changing equivalent tests for configMap and projected to be similar to that of secrets as we've now moved to caching manager for configmaps too.

**Comment by wojtek-t** [comment]
Great - so my suggestion was correct.

**Comment by shyamjvs** [comment]
@wojtek-t Yup, thanks :)
Though I wonder how this test for secret was passing before (when you increased test timeout), because the retry_time for the pod was still 2m back then which means the update was actually happening under 2m previously(?)

**Comment by wojtek-t** [comment]
I don't know - maybe something changed with the container itself? It's probably not worth investigating now.

**Comment by shyamjvs** [comment]
As long as it's not a regression in kubelet we're fine.
