### ISSUE TITLE
Nginx loses requests when the Ingress Controller reloads its configuration

### ISSUE THREAD

**Issue by maxlaverse** [kubernetes/kubernetes#48358]
**Is this a BUG REPORT or FEATURE REQUEST?**:
This is a BUG REPORT
/kind bug
/sig network

**What happened**:
We found out that before the Ingress Controller reloads its configuration it first tests it by executing:
```
/usr/sbin/nginx -t -c /tmp/nginx-cfg061503324
```

This command checks for the syntax and tries to open the files referred in the configuration.
The problem is that is also `bind`s and `listen`s on the sockets defined in the configuration. Those sockets are already used by the running instance and receiving traffic. On a default nginx setup, those calls would silently fail during the configuration test.

But because the nginx Ingress Controller uses the `reuseport` option on the nginx `listen` directive, the test process will successfully `bind` and `listen` to the sockets.  Linux will start 3-way handshakes on the incoming connections and stack them up in this new process. Linux has established connections and even buffered some data. Therefore when the configuration test is complete and the temporary nginx process stops, all the stacked connections are reset. 

**What you expected to happen**:
We expect no connection to be lost with the nginx Ingress Controller under perfect conditions.

**How to reproduce it (as minimally and precisely as possible)**:
Run Apache Bench to make a significant amount of requests through the Ingress:
```bash
# 10.244.12.1 is the IP of an nginx ingress controller pod.
$ ab -n 100000 -c 30 10.244.12.1/hithere.html
```

In our test case we deployed an Nginx pod with a static page named `hithere.html`. The request rate is around 13k requests per seconds.
The command above should fail from time to time with `apr_socket_recv: Connection reset by peer (104)`.

The Ingress Controller is only reloading the configuration every 10 seconds and it can take some time before you actually see the error. To make it fail faster, connect to the ingress controller pod you are testing and simulate multiple configuration reloads:
```bash
$ kubectl exec -n kube-system -ti nginx-ingress-controller-181132680-4v55s bash
$ for i in `seq 1 10`; do /usr/sbin/nginx -c /etc/nginx/nginx.conf -t; done
```

You should see Apache Bench systematically failing because of reset connections.

**Anything else we need to know?**:
We've opened [a ticket](https://trac.nginx.org/nginx/ticket/1300) on the nginx issue tracking system last week as we believe it's an issue that should be solved in nginx itself. Calling `listen` when testing the configuration sounds wrong.

However we don't know how long the nginx team will take to acknowledge (or refuse) this issue and fix it. This problem is probably affecting other users of the nginx Ingress Controller and we wanted at least to make other people aware of it. We could maybe fix the nginx Ingress Controller in the meantime if it takes too long.

We plan to use a simple workaround rather than fixing and forking nginx directly.
It consists in a very simple library pre-loaded before the `nginx -t` command is launched, library that overrides the `listen` implementation.

```c
#include <stdio.h>

int listen(int sockfd, int backlog)
{
 printf("Would have called listen() on a socket\n");
 return 0;
}
```

Compiled with:
```
$ gcc -fPIC -shared  -o fakelisten.so fakelisten.c -ldl
```

We would then modify the nginx Ingress Controller to preload this library before running the configuration test (`LD_PRELOAD=fakelisten.so nginx -t -c ...`). 

**Environment**:
- Kubernetes version `1.6.6`
- Nginx Ingress Controller version `0.9.0-beta.3`
- OS `16.04.2 LTS (Xenial Xerus)`
- Kernel `Linux node-1 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by aledbf** [comment]
@maxlaverse this issue is fixed in nginx 1.13.4 (http://nginx.org/en/CHANGES)
Current master in kubernetes/ingress is already updated. Next release will this this issue.

**Comment by aledbf** [comment]
This is fixed in master. Please use the image `quay.io/aledbf/nginx-ingress-controller:0.179`

**Test the ingress:**
```
$ curl -H 'Host: no-sticky-ingress.example.com'  http://$(minikube ip)/

Hostname: http-svc-w088k

Pod Information:
	node name:	 minikube
	pod name:	 http-svc-w088k
	pod namespace:	 default
	pod IP:  	 172.17.0.2

Server values:
	server_version=nginx: 1.13.0 - lua: 10008

Request Information:
	client_address=172.17.0.4
	method=GET
	real path=/
	query=
	request_version=1.1
	request_uri=http://no-sticky-ingress.example.com:8080/

Request Headers:
	accept=*/*
	connection=close
	host=no-sticky-ingress.example.com
	user-agent=curl/7.52.1
	x-forwarded-for=192.168.99.1
	x-forwarded-host=no-sticky-ingress.example.com
	x-forwarded-port=80
	x-forwarded-proto=http
	x-original-uri=/
	x-real-ip=192.168.99.1
	x-scheme=http

Request Body:
	-no body in request-
```

**Reference:**
```console
$ ab -n 100000 -H 'Host: no-sticky-ingress.example.com' -c 30 http://$(minikube ip)/
This is ApacheBench, Version 2.3 <$Revision: 1757674 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 192.168.99.100 (be patient)
Completed 10000 requests
Completed 20000 requests
Completed 30000 requests
Completed 40000 requests
Completed 50000 requests
Completed 60000 requests
Completed 70000 requests
Completed 80000 requests
Completed 90000 requests
Completed 100000 requests
Finished 100000 requests


Server Software:        nginx/1.13.4
Server Hostname:        192.168.99.100
Server Port:            80

Document Path:          /
Document Length:        690 bytes

Concurrency Level:      30
Time taken for tests:   28.486 seconds
Complete requests:      100000
Failed requests:        0
Total transferred:      81300000 bytes
HTML transferred:       69000000 bytes
Requests per second:    3510.47 [#/sec] (mean)
Time per request:       8.546 [ms] (mean)
Time per request:       0.285 [ms] (mean, across all concurrent requests)
Transfer rate:          2787.12 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.7      0       8
Processing:     0    8   5.9      8      42
Waiting:        0    8   5.9      7      42
Total:          0    9   6.0      8      43

Percentage of the requests served within a certain time (ms)
  50%      8
  66%     12
  75%     13
  80%     14
  90%     16
  95%     18
  98%     21
  99%     23
 100%     43 (longest request)
```

**Test:**

In a different terminal I am running (test the config each 5 seconds)
```console
kubectl exec -n kube-system nginx-ingress-controller-3565525679-jg4z9 -it bash
for i in `seq 1 100`; do /usr/sbin/nginx -c /etc/nginx/nginx.conf -t;sleep 5; done
```

**Start ab:**
```console
$ ab -n 100000 -H 'Host: no-sticky-ingress.example.com' -c 30 http://$(minikube ip)/
This is ApacheBench, Version 2.3 <$Revision: 1757674 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 192.168.99.100 (be patient)
Completed 10000 requests
Completed 20000 requests
Completed 30000 requests
Completed 40000 requests
Completed 50000 requests
Completed 60000 requests
Completed 70000 requests
Completed 80000 requests
Completed 90000 requests
Completed 100000 requests
Finished 100000 requests


Server Software:        nginx/1.13.4
Server Hostname:        192.168.99.100
Server Port:            80

Document Path:          /
Document Length:        690 bytes

Concurrency Level:      30
Time taken for tests:   27.723 seconds
Complete requests:      100000
Failed requests:        0
Total transferred:      81300000 bytes
HTML transferred:       69000000 bytes
Requests per second:    3607.06 [#/sec] (mean)
Time per request:       8.317 [ms] (mean)
Time per request:       0.277 [ms] (mean, across all concurrent requests)
Transfer rate:          2863.81 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.8      0       8
Processing:     0    8   6.0      7      78
Waiting:        0    8   6.0      7      78
Total:          0    8   6.0      8      78

Percentage of the requests served within a certain time (ms)
  50%      8
  66%     11
  75%     13
  80%     14
  90%     16
  95%     18
  98%     20
  99%     23
 100%     78 (longest request)
```

**Comment by aledbf** [comment]
@maxlaverse if you see the same results please close the issue.

**Comment by maxlaverse** [comment]
@aledbf I'll rerun the tests when I'm back, the 21st or the week after.

**Comment by maxlaverse** [comment]
I re-ran the tests on our installation and had no error with an even lower sleep time (1 sec) in the `nginx -t` loop.

```bash
ab -n 100000 -c 30 10.12.67.80:80/hithere.html
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 10.12.67.80 (be patient)
Completed 10000 requests
Completed 20000 requests
Completed 30000 requests
Completed 40000 requests
Completed 50000 requests
Completed 60000 requests
Completed 70000 requests
Completed 80000 requests
Completed 90000 requests
Completed 100000 requests
Finished 100000 requests


Server Software:        nginx/1.13.4
Server Hostname:        10.12.67.80
Server Port:            80

Document Path:          /hithere.html
Document Length:        53 bytes

Concurrency Level:      30
Time taken for tests:   8.766 seconds
Complete requests:      100000
Failed requests:        0
Total transferred:      34900000 bytes
HTML transferred:       5300000 bytes
Requests per second:    11408.07 [#/sec] (mean)
Time per request:       2.630 [ms] (mean)
Time per request:       0.088 [ms] (mean, across all concurrent requests)
Transfer rate:          3888.10 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.4      0      37
Processing:     0    2   1.9      2      81
Waiting:        0    2   1.9      2      80
Total:          1    3   2.0      2      82

Percentage of the requests served within a certain time (ms)
  50%      2
  66%      3
  75%      3
  80%      3
  90%      4
  95%      5
  98%      8
  99%     10
 100%     82 (longest request)
```

Do you have any hint when you might release a new official image with the fix @aledbf ? And/Or a link to a document describing the life of an Ingress release ?

**Comment by aledbf** [comment]
> Do you have any hint when you might release a new official image with the fix @aledbf ? 

End of this week

>  And/Or a link to a document describing the life of an Ingress release ?

There's no document describing the life of an Ingress release. We try to release a version every 3-5 weeks

**Comment by maxlaverse** [comment]
Thanks
