### ISSUE TITLE
case sensitive storageclass.beta.kubernetes.io/is-default-class

### ISSUE THREAD

**Issue by ReSearchITEng** [kubernetes/kubernetes#48350]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
/kind bug

**What happened**:
storageclass.beta.kubernetes.io/is-default-class is working as default when it's set to:
storageclass.beta.kubernetes.io/is-default-class: true

but is not working as default when set to True
storageclass.beta.kubernetes.io/is-default-class: True
**What you expected to happen**:
case insensitive, and work also with yes/Yes/YES/TRUE/..
**How to reproduce it (as minimally and precisely as possible)**:

create pvc without requesting a specific class (aka no annotations for storage-class in the pvc)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
k8s 1.6.6
- Install tools:
kubeadm

**Comment by dims** [comment]
@ReSearchITEng : can you please check if https://github.com/kubernetes/kubernetes/pull/48442 works for you?

**Comment by ReSearchITEng** [comment]
Thanks for the fix!
I cannot build it myself. Here is a simple storage class:
https://raw.githubusercontent.com/ReSearchITEng/kubeadm-playbook/master/nfs.yaml

once deployed, from CLI it should show "(default)":
```
$kubectl get sc
NAME                TYPE
nfs.k8s (default)   nfs.k8s
```

**Comment by msau42** [comment]
@dims can this be closed?

**Comment by dims** [comment]
yep, @msau42 

/close

wont-fix. please see discussion in the PR
