### ISSUE TITLE
flake: race detected during execution of test TestReplicaSetController

### ISSUE THREAD

**Issue by wongma7** [kubernetes/kubernetes#48368]
occurred here: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/48366/pull-kubernetes-unit/38649/

log: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/48366/pull-kubernetes-unit/38649/?log#log

`I0630 15:14:38.018] FAIL	k8s.io/kubernetes/federation/pkg/federation-controller/sync	9.274s`

**Comment by sakeven** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/48333/pull-kubernetes-unit/38592/ same

**Comment by cblecker** [comment]
ID from triage tool: 2093fd01d5f51de5f467f5

Seen a number of these: https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&test=TestReplicaSetController

@kubernetes/sig-federation-test-failures

**Comment by alexandercampbell** [comment]
Same failure on my PR: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/48572/pull-kubernetes-unit/39298

**Comment by smarterclayton** [comment]
@kubernetes/sig-federation-bugs @kubernetes/sig-testing-bugs 

This is flaking quite a lot, can we get some eyes on it?

**Comment by alexandercampbell** [comment]
fwiw, I ran the test with the race detector locally 10-15 times and could not reproduce the issue.

```bash
go test -race -v -run '^TestReplicaSetController$' k8s.io/kubernetes/federation/pkg/federation-controller/sync
```

**Comment by marun** [comment]
This test duplicates e2e coverage, and I'm going to propose its removal.
