### ISSUE TITLE
Can't fix it

### ISSUE THREAD

**Issue by richjon83** [kubernetes/kubernetes#48379]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xiangpengzhao** [comment]
Hi @richjon83, what is this issue for? I don't see any useful information in the description. We are going to close this issue, feel free to create a new issue if you have feature requests or find bugs of Kubernetes. Thanks!

/cc @thockin
