### ISSUE TITLE
Make test/images/volumes-tester multiarch

### ISSUE THREAD

**Issue by mkumatag** [kubernetes/kubernetes#48376]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
This issue is to track work to convert test/images/volumes-tester to multi architecture.

**Comment by luxas** [comment]
ping @mkumatag any update here?

**Comment by mkumatag** [comment]
Depends on https://github.com/kubernetes/kubernetes/pull/54300
