### ISSUE TITLE
Immutable Job error is wrong

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#48388]
Reading and then writing a (terminated?) Job from the server should be a no-op and be valid.  Instead, I get an immutable update error from pod template (which is wrong, and might be related to defaulting or protobuf serialization), and the immutable field error prints the entire pod template, which is also terrible.

1. find out why a no-op update on jobs doesn't complete successfully (this blocks storage migration)
2. fix the validation error for immutable pod template specs to not dump the Go String representation of the entire struct - that's horrible and unhelpful.

Against Kube 1.6, have not tested 1.7, during a storage update from JSON -> protobuf, which prevents those jobs from being updated.

**Comment by smarterclayton** [comment]
@soltysh discovered while testing migration of our 1.6 data to protobuf

**Comment by smarterclayton** [comment]
```
error:     jobs/scheduled-job-test-1497250440 -n XXXX: Job.batch "scheduled-job-test-1497250440" is invalid: spec.template: Invalid value: api.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"controller-uid":"ebfae158-4f3b-11e7-b1dd-122631632f42", "job-name":"scheduled-job-test-1497250440"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), InitContainers:[]api.Container(nil), Containers:[]api.Container{api.Container{Name:"test-job-container", Image:"XXXXX", Command:[]string{"python", "./test_job.py"}, Args:[]string(nil), WorkingDir:"", Ports:[]api.ContainerPort(nil), EnvFrom:[]api.EnvFromSource(nil), Env:[]api.EnvVar(nil), Resources:api.ResourceRequirements{Limits:api.ResourceList(nil), Requests:api.ResourceList(nil)}, VolumeMounts:[]api.VolumeMount(nil), LivenessProbe:(*api.Probe)(nil), ReadinessProbe:(*api.Probe)(nil), Lifecycle:(*api.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"Always", SecurityContext:(*api.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, RestartPolicy:"Never", TerminationGracePeriodSeconds:(*int64)(0xc50d8a7cb8), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*api.PodSecurityContext)(0xc512058b40), ImagePullSecrets:[]api.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*api.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]api.Toleration(nil)}}: field is immutable
```

**Comment by smarterclayton** [comment]
```
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"CronJob","namespace":"xxxx","name":"scheduled-job-test","uid":"a0e50edf-4ef5-11e7-b1dd-122631632f42","apiVersion":"batch","resourceVersion":"524176032"}}
  creationTimestamp: 2017-06-14T19:17:04Z
  labels:
    controller-uid: 0d07e0f3-5136-11e7-835c-12d641ec7610
    job-name: scheduled-job-test-1497467820
  name: scheduled-job-test-1497467820
  namespace: xxxx
  resourceVersion: "524185014"
  selfLink: /apis/batch/v1/namespaces/xxxx/jobs/scheduled-job-test-1497467820
  uid: 0d07e0f3-5136-11e7-835c-12d641ec7610
spec:
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 0d07e0f3-5136-11e7-835c-12d641ec7610
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 0d07e0f3-5136-11e7-835c-12d641ec7610
        job-name: scheduled-job-test-1497467820
    spec:
      containers:
      - command:
        - python
        - ./test_job.py
        image: x.x.x.x
        imagePullPolicy: Always
        name: test-job-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
```

**Comment by smarterclayton** [comment]
@derekwaynecarr is there anyone who can look at this?

**Comment by DirectXMan12** [comment]
I'll take a look

**Comment by DirectXMan12** [comment]
@smarterclayton I cannot seem to reproduce this.  I've attempted with Kubernetes v1.6.2, as well as openshift/origin@83efc339e7c9939d56e481a77b51320ae14d4155.

I've attempted creating the job both by `kubectl create -f`-ing the given YAML (I had to unset the label selectors here) and by converting the YAML to JSON and directly injecting it into etcd.

Once created, I attempted to get the object using `kubectl get --raw /apis/v1/batch/namespaces/xxxx/jobs/scheduled-job-test-1497467820`, `kubectl get job -o yaml`, and `kubectl get job -o json`.

Once gotten, I attempted to update via `kubectl update -f` and `curl -XPUT -H 'Content-Type: application/json' https://$KUBE/apis/v1/batch/namespaces/xxxx/jobs/apis/v1/batch/namespaces/xxxx/jobs/scheduled-job-test-1497467820 -d @./job-out.json`.

Using the `kubectl create -f` method, I also tried with an in-progress job.

I also tried with `oadm storage migrate --confirm` on OpenShift.

The only thing I was able to reproduce was the unhelpful validation message, but *only* when I tried to actually change the image name after the job was created.  I could not get a normal get+update to trigger the validation issue.

Am I missing anything?

**Comment by smarterclayton** [comment]
Was due to a custom admission controller attempting to mutate the job.

**Comment by kron4eg** [comment]
Today I hit the same problem and found this issue.
@DirectXMan12 reproduction is pretty easy.

* kubectl apply any Job
* change "spec.template.spec.containers.image" to anything else
* kubectl apply that Job one more time with new image

Result: this error and complaining about immutable field.

**Comment by soltysh** [comment]
@kron4eg but that's expected. You can't mutate certain parts of the job after it is created. That's how this should work.

**Comment by harrissAvalon** [comment]
@soltysh According to [Kubectl documentation](https://kubernetes.io/docs/user-guide/kubectl/v1.7/#-em-image-em-) a `job` is one of the resources listed as able to update a container image. Is that not the case?

**Comment by soltysh** [comment]
Good catch, that part of docs is generated from `kubectl set image --help`. I've updated the necessary part of description in https://github.com/kubernetes/kubernetes/pull/52164

**Comment by smarterclayton** [comment]
Yes, the bug isn't that it's wrong.  The bug is that the error message

**Comment by soltysh** [comment]
#52164 merged and I think this is solved. Feel free to re-open if needed.

**Comment by mattmoor** [comment]
> You can't mutate certain parts of the job after it is created. That's how this should work.

@soltysh @smarterclayton So I just hit this experimenting with an Initializer that resolves tag references to digests.  It feels to me like the restrictions around mutability of the PodSpec should only be enforced post-Initialization, which may want to do all kinds of things (e.g. tweaking PullPolicy, injecting sidecars).  Perhaps there is another issue tracking that?

**Comment by mattmoor** [comment]
I believe Istio is running into this when injecting sidecars (see linked issue).

**Comment by smarterclayton** [comment]
It's covered under https://github.com/kubernetes/kubernetes/issues/49038

**Comment by duzy** [comment]
> Today I hit the same problem and found this issue.
> @DirectXMan12 reproduction is pretty easy.
> 
> * kubectl apply any Job
> * change "spec.template.spec.containers.image" to anything else
> * kubectl apply that Job one more time with new image
> 
> Result: this error and complaining about immutable field.

I'm having exactly the same result. Have to delete the job manually and apply again.

**Comment by lukeschlather** [comment]
This error is still absolute garbage. Can it print the actual field that is immutable rather than vomiting the entire template?

**Comment by TBBle** [comment]
The error is correct. The [whole `spec.template` field is immutable](https://github.com/kubernetes/kubernetes/issues/89657#issuecomment-608224842), which is what it says.

**Comment by smarterclayton** [comment]
The error is not correct - errors on immutable structs should not print the struct, it should print either nothing or list the field that is changed.

**Comment by deads2k** [comment]
Closing due to age and inactivity.  Please reopen if it's still a problem on the latest supported version.

/close
