### ISSUE TITLE
Helper programs network isolation

### ISSUE THREAD

**Issue by josselin-c** [kubernetes/kubernetes#4838]
In a pod with two containers, how would you isolate one of the container from the network (except maybe for some whitelist)?
I don't have AppArmor available so I can't set a custom profile to the container and I'm not sure how I could to this with SELinux + iptables.
Going for '--net=none' could be a start but I don't know how to set this in the manifest files.

**Comment by thockin** [comment]
We do not have an answer here, yet.  We're expecting a proposal for network
plugins $soon, which will give us some ideas on how to implement arbitrary
network insanity, on the low end of which is various forns of isolation.
