### ISSUE TITLE
Kubelet should manage hosts file for HostNetwork Pods instead of Docker

### ISSUE THREAD

**Issue by rickypai** [kubernetes/kubernetes#48397]
Currently, kubelet mounts hosts file for [non-hostNetwork](https://github.com/kubernetes/kubernetes/blob/48b3fb84abdc0fee12299eed262da287d48110de/pkg/kubelet/kubelet_pods.go#L112-L118) pods. For hostNetwork pods, the behavior is different and instead, kubelet relies on docker (or whatever container runtime) to [mount](
https://github.com/kubernetes/kubernetes/issues/43632#issuecomment-304376441) the host's hosts file.

We should have kubelet handle hosts file for hostNetwork pods. This would have several benefits:

1. better control over hosts file in case the container runtime does something [unexpected](https://github.com/moby/moby/issues/17190)
2. more consistent behavior between hostNetwork and non-hostNetwork pods
3. ensure consistent behavior between different container runtimes
4. kubelet-managed hosts file enables features like [HostAliases](https://github.com/kubernetes/kubernetes/pull/45148) to be used for hostNetwork pods

Implementation would require:
1. make kubelet's [hostsFileContent](https://github.com/kubernetes/kubernetes/blob/48b3fb84abdc0fee12299eed262da287d48110de/pkg/kubelet/kubelet_pods.go#L233) or its caller output different content based on hostNetwork.
  i. If it's not hostNetwork, use existing behavior.
  ii. If it's using hostNetwork, read the content from the host's hosts file.
2. remove hostNetwork constraint in deciding whether to mount the file

Open Questions:
1. how do we treat changes to the host's hosts file? should the file's content be static between container restarts of the same Pod? or should every container restart pick up the latest content of the hosts file? the former seems better for consistency, but letter might be more in line with other features that use host resources like host volumes.
2. the condition to manage hosts file also excludes windows even though windows also [support](https://support.rackspace.com/how-to/modify-your-hosts-file/) the use of hosts file and the same format. seems like this should be supported also.
3. before windows-support ships, should it have validation against windows platform? the tricky bit is the client, API, and minions' kubelet may be running on different platforms, and currently, there's no precedence to platform validation.

/kind feature
/sig node

@yujuhong @hongchaodeng @thockin

**Comment by cmluciano** [comment]
@kubernetes/sig-network-feature-requests @kubernetes/sig-node-feature-requests
