### ISSUE TITLE
Storage version migration is broken due to an optimization in GuaranteedUpdate

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#48393]
Pull https://github.com/kubernetes/kubernetes/pull/35415 optimized guaranteed update to avoid a Get against etcd3.  Instead of reading the data that etcd has, it reserializes the in memory version of the object.  The problem is that we use the delta between the etcd version and the new version we are writing to get rid of out of date versions (i.e. going from v1beta3 to v1, we switched the apiserver config to v1, then issued a no-op write to all objects).  With the optimization in place, the only way to force a write is to make a concrete change to the serialized object, like adding an annotation.

Until we fix this, we can't drop an old API version, and someone updating to protobuf can't for instance ensure all their data is protobuf at rest.

**Comment by wojtek-t** [comment]
I commented on the issue. I think that the other potential workaround to deprecate an API version (and do migration) is to disable cacher for a given resource for the moment of migration. And then reenable it back.
I obviously agree that this is a regression and this workaround is hacky and not very convenient, but I think it's possible.
