### ISSUE TITLE
Local storage: pod gets scheduled to node that does not have persistent volume available

### ISSUE THREAD

**Issue by praseodym** [kubernetes/kubernetes#48401]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I am trying out the local storage support in 1.7 combined with the [external static provisioner](https://github.com/kubernetes-incubator/external-storage/tree/master/local-volume). On one of my nodes (`k8s-01`), I created a local volume which the provisioner picked up as persistent volume `local-pv-87b4a99e` in Kubernetes. Then, I created a simple PostgreSQL statefulset. Its PVC got successfully bound to that PV. However, its pod got scheduled to the wrong node (seemingly any of my three nodes) instead of the one that has the local PV available. This results in the following error (from `kubectl describe pod postgres-test-0`):
```
  5m		1m		10	kubelet, k8s-02				Warning		FailedMount		MountVolume.SetUp failed for volume "local-pv-87b4a99e" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: /mnt/local-storage/data/4b359fbb-3daa-49d7-87fd-b97222f7a4e0 /var/lib/kubelet/pods/5c2c8edd-5f4d-11e7-879c-00505699a646/volumes/kubernetes.io~local-volume/local-pv-87b4a99e  [bind]
Output: mount: special device /mnt/local-storage/data/4b359fbb-3daa-49d7-87fd-b97222f7a4e0 does not exist
```

When the pod is scheduled to the node with local storage available (e.g. by cordoning other nodes), things work as expected.

The StatefulSet, PV and PVC exports are available in this Gist: https://gist.github.com/praseodym/a75600721d217cbb5f5c3241ff988a01

**What you expected to happen**:
The pod gets only ever scheduled to node `k8s-01` because that is where the persistent volume is available.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy local storage external static provisioner
2. Create local volume which is exposed as a persistent volume
3. Create stateful set with PVC template
4. Observe that the PVC gets bound
4. Observe that the pod does not (always) get scheduled to the node on which the bound volume is available

**Anything else we need to know?**:

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.7.0
- **Cloud provider or hardware configuration**: VMware
- **OS** (e.g. from /etc/os-release): Debian Stretch
- **Kernel** (e.g. `uname -a`): Linux 4.9.0-3-amd64
- Install tools: kubeadm

**Comment by praseodym** [comment]
I think the problem is that I forgot to enable the local storage feature gate for the scheduler. Will report back.

**Comment by praseodym** [comment]
Adding the feature gate to the scheduler and controller-manager fixed the problem. Sorry for bothering!

**Comment by agargiulo** [comment]
@praseodym How did you resolve this? I feel like I'm running into the same or similar issue and can't track down what's wrong with my cluster.

**Comment by praseodym** [comment]
@agargiulo I ensured `--feature-gates=PersistentLocalVolumes=true` was given as a parameter to all appropriate Kubernetes components (_Kubernetes API Server, controller-manager, scheduler, and all kubelets_ as described in the [README](https://github.com/kubernetes-incubator/external-storage/blob/master/local-volume/README.md#option-3-baremetal-environments)).
