### ISSUE TITLE
Fix Markdown ASCIIRenderer Problem with help message

### ISSUE THREAD

**Issue by shiywang** [kubernetes/kubernetes#48409]
while I was working on pr https://github.com/kubernetes/kubernetes/pull/46560, we found the help message `KUBECTL_EXTERNAL_DIFF` in apply-diff command will becomes `KUBECTL EXTERNAL DIFF` after printing out. also `KUBE_EDITOR` in edit command will also becomes `KUBE _EDITOR` if you look carefully.

we should fix that if we can, I will investigate it, since @fabianofranz is the author of that part of [markdown render code](https://github.com/shiywang/kubernetes/blob/2b178ad608bd443efeaf3e9ea7c700e72ab68de1/pkg/kubectl/cmd/templates/normalizers.go#L73), do you have any idea on why this happened if you already know the root cause?

/assign @shiywang
cc @mengqiy

**Comment by shiywang** [comment]
new pr here: https://github.com/kubernetes/kubernetes/pull/49174

**Comment by zjj2wry** [comment]
@shiywang this is related with #50292. maybe is upstream markdown lib cause. i updated vendor fix this - -, but maybe this is not good fix.

**Comment by shiywang** [comment]
@zjj2wry feel free to submit a pr, I haven't dig this problem yet.

**Comment by shiywang** [comment]
close this due to there's a better description one in https://github.com/kubernetes/kubernetes/issues/50292
