### ISSUE TITLE
Make monitoring (heapster + influxdb + grafana) more Kubernetes friendly

### ISSUE THREAD

**Issue by pires** [kubernetes/kubernetes#4841]
So, having something like
```
yaml
- name: "INFLUXDB_HOST"
  value: '"+window.location.hostname+"/api/v1beta1/proxy/services/monitoring-influxdb'
```
is very limitative when it comes to running ```influxdb``` + ```grafana```inside Kubernetes **but** accessing from external service addresses (```publicIPs```) possibly set in ```grafana-service.yaml```.

Since ```nginx``` is already used for hosting ```grafana```, we should leverage on it for achieving some sort of reverse-proxy for ```http://
localhost:8086```(```influxdb``` is running in the same pod).

**Comment by thockin** [comment]
@vishh

**Comment by thockin** [comment]
I'm guessing at P2 - please consider and adjust

**Comment by vishh** [comment]
Once we can specify multiple ports per kubernetes service, this can be
achieved without needing a reverse proxy. You can set the "INFLUXDB_HOST"
to be be "+window.location.hostname+" and "INFLUXDB_PORT" to a service port
that connects to influxdb. However I do agree that having a reverse proxy
helps separate influxdb and grafana into separate pods.

Are you having any issues accessing Grafana via the proxy on the api-server?

**Comment by pires** [comment]
I've made it work with a reverse-proxy.

_"+window.location.hostname+"_ won't work outside of the cluster, unless you make ```influxdb``` publicly accessible on the same IP as well.

Snippets of what I did:

**nginx.conf**
```
location /db/ {
    proxy_pass http://127.0.0.1:8086/db/;

    proxy_set_header           X-Real-IP   $remote_addr;
    proxy_set_header           X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header           X-Forwarded-Proto  $scheme;
    proxy_set_header           X-Forwarded-Server  $host;
    proxy_set_header           X-Forwarded-Host  $host;
    proxy_set_header           Host  $host;

    client_max_body_size       10m;
    client_body_buffer_size    128k;

    proxy_connect_timeout      90;
    proxy_send_timeout         90;
    proxy_read_timeout         90;

    proxy_buffer_size          4k;
    proxy_buffers              4 32k;
    proxy_busy_buffers_size    64k;
    proxy_temp_file_write_size 64k;
}
```

**app/config.js**
```javascript
datasources: {
    'metrics': {
        type: 'influxdb',
        url: window.location.origin+"/db/k8s",
        username: "root",
        password: "root"
    },
    'grafana': {
        type: 'influxdb',
        url: window.location.origin+"/db/grafana",
        username: "root",
        password: "root",
        grafanaDB: true
    }
}
```

**Comment by vishh** [comment]
Multiple ports per service should make influxdb and grafana accessible from the same IP. 
Thanks for sharing your config @pires! I you have some time feel free to post a PR against [heapster](https://github.com/GoogleCloudPlatform/heapster). If not, I will update the Grafana container once I find some time.

**Comment by pires** [comment]
@vishh am working on that PR.

Anyway, there's no need to expose ```influxdb``` outside the cluster.

**Comment by vishh** [comment]
Exposing Influxdb helps with debugging. So having a way to expose if needed should be good enough. Looking forward to the PR @pires !!

**Comment by pires** [comment]
Well, with reverse-proxy you can access it, just not directly, so you can debug queries, etc. Other than that, you'll need to dissect the container.

**Comment by pires** [comment]
PR at https://github.com/GoogleCloudPlatform/heapster/pull/142

@vishh please pay special attention to the observation I make regarding the ```influx-grafana-controller.yaml```. I am providing a PR for that as well, but it will depend on the merge of the aforementioned PR.

**Comment by vishh** [comment]
@pires: Can you shed some light on why accessing the cluster services via the proxy does not work you? We are moving logging to also be accessible only via the proxy on the master and any user feedback here will be helpful.

**Comment by pires** [comment]
As it is, the service is only accessible from inside the cluster, which IMHO doesn't make sense. You want to monitor it remotely. I've set a ```publicIPs``` entry for ```grafana``` and it wasn't working. This way, it works both internally and from the outside, if you access IP or DNS instead of calling the proxy through the API - which for me doesn't make sense either.
Most probably, this is what's killing it for you ```url: window.location.origin```.

**Comment by vishh** [comment]
We are considering monitoring as a cluster service and the intention is to
have a common auth model for the master and all cluster services.
Controlling access to cluster services via the API proxy is convenient for
achieving that goal.

**Comment by pires** [comment]
I understand your considerations and honestly don't want to pick a fight with this, but your instructions do not work for me.
If it's ok by you, I'll just close my two PRs and maintain my own images and pod descriptors.

**Comment by vishh** [comment]
Thanks for the PRs. I will pick it up from here and try to get it to work
in both the modes.

**Comment by pires** [comment]
OK @vishh feel free to merge this into your code then :-)

**Comment by bgrant0607** [comment]
@vishh Is this still an issue?

**Comment by pires** [comment]
I don't think this is an issue anymore since services are much more powerful these days and satisfy the external access requirement.
