### ISSUE TITLE
Two or more default StorageClasses can be created

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#48416]
/kind bug

DefaultStorageClass admission plugin expects that there is only one default StorageClass defined and it refuses to work when there are more of them. The admission plugin should be extended to check newly created/updated StorageClassses and forbid creation of two default ones.

cc @kubernetes/sig-storage-bugs 
/assign

**Comment by liggitt** [comment]
> The admission plugin should be extended to check newly created/updated StorageClassses and forbid creation of two default ones

This is racy... admission doesn't serialize, so two defaults could be admitted concurrently (within the same API server or via different API servers in an HA setup)

**Comment by gnufied** [comment]
> This is racy... admission can happen in parallel, so two defaults could be admitted concurrently (within the same API server or via different API servers in an HA setup)

I think until we have a solution that solves this properly (transactions may be?) - I think the solution proposed here is "good enough", since it solves a real problem.

**Comment by liggitt** [comment]
It's a rare enough issue, easily correctable if it occurs. I'd wait for an initializer solution.

**Comment by gnufied** [comment]
@liggitt is there any documentation for the initializer solution? I was looking at - https://github.com/kubernetes/community/blob/master/contributors/design-proposals/apiserver-build-in-admission-plugins.md 

Is that the same thing you were talking about?

**Comment by wongma7** [comment]
@gnufied https://github.com/kubernetes/community/blob/master/contributors/design-proposals/admission_control_extension.md

**Comment by jsafrane** [comment]
Admission webhooks looks nice, however I see several issues:

* They are not enabled by default in any installation tool I checked (kubeadm, kops, cluster/kube-up.sh).
* While writing such webhook does not look complicated, deploying one in a default installation is a different matter.
* To keep things synchronous, we would need to run just one "master" instance of the webhook pod. What happens when the pod becomes unavailable? Will it stop API server(s) from working until there is a new "master" pod recreated / reelected?
