### ISSUE TITLE
rktnetes: ip netns side-effects

### ISSUE THREAD

**Issue by JulienBalestra** [kubernetes/kubernetes#48427]
/kind bug

**What happened**:
Double MAC address for an IP address when using rktnetes + common `rkt` in systemd.

**What you expected to happen**:
rktnetes and rkt can work on the same host.

**How to reproduce it (as minimally and precisely as possible)**:

I asked to systemd to run a simple container before the kubelet:
```
rkt run --insecure-options=all --net='bond0:IP=172.20.0.2' enjoliver.local/debian:latest --exec dgr/bin/busybox -- httpd -fv
```

As we can see the correct order of the mounts:
```
nsfs on /run/netns/cni-e3dc9abb-4cfc-cadc-aa1c-ca8d2ee4791f type nsfs (rw)
tmpfs on /run/netns type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
nsfs on /run/netns/k8s_a822b7b1-5fdf-11e7-8260-525400ab2147 type nsfs (rw)
nsfs on /run/netns/k8s_a822b7b1-5fdf-11e7-8260-525400ab2147 type nsfs (rw)
nsfs on /run/netns/k8s_a8207c60-5fdf-11e7-8260-525400ab2147 type nsfs (rw)
nsfs on /run/netns/k8s_a8207c60-5fdf-11e7-8260-525400ab2147 type nsfs (rw)
```

Now I have 3 containers running with a CNI MACvlan configuration.
```
ip netns
k8s_a822b7b1-5fdf-11e7-8260-525400ab2147
k8s_a8207c60-5fdf-11e7-8260-525400ab2147
cni-e3dc9abb-4cfc-cadc-aa1c-ca8d2ee4791f
```

And I cannot use the rkt-one:
```
ip netns exec cni-e3dc9abb-4cfc-cadc-aa1c-ca8d2ee4791f ip a
setting the network namespace "cni-e3dc9abb-4cfc-cadc-aa1c-ca8d2ee4791f" failed: Invalid argument
```

But it works for the 2 others:

```
ip netns exec k8s_a8207c60-5fdf-11e7-8260-525400ab2147 ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 0a:58:ac:14:43:01 brd ff:ff:ff:ff:ff:ff
    inet 172.20.67.1/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::858:acff:fe14:4301/64 scope link 
       valid_lft forever preferred_lft forever
```

The application of the rkt container still works:
```
curl 172.20.0.2 -I 
HTTP/1.0 404 Not Found
```

The previous `/run/netns/cni-e3dc9abb-4cfc-cadc-aa1c-ca8d2ee4791f` will be inaccessible for `rkt gc`.
The associated network resources un-garbage collected are a real problem in a MACvlan configuration.
The old MAC stays and if a new rkt container starts over the same IP address, you'll have two MACs for one IP address.

```
arping -I rack0 172.20.0.2
ARPING 172.20.0.2 from 172.20.0.1 rack0
Unicast reply from 172.20.0.2 [CE:6B:70:E3:CB:A9]  1.061ms
Unicast reply from 172.20.0.2 [96:68:9A:55:E5:4B]  1.144ms
```

```
ip netns
cni-a4c0c2ab-358a-7c56-af6d-3bd3e078b1a5
k8s_a822b7b1-5fdf-11e7-8260-525400ab2147
k8s_a8207c60-5fdf-11e7-8260-525400ab2147
cni-e3dc9abb-4cfc-cadc-aa1c-ca8d2ee4791f
```

```
ip netns exec cni-a4c0c2ab-358a-7c56-af6d-3bd3e078b1a5 ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether ce:6b:70:e3:cb:a9 brd ff:ff:ff:ff:ff:ff
    inet 172.20.0.2/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::cc6b:70ff:fee3:cba9/64 scope link 
       valid_lft forever preferred_lft forever
4: eth1@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether a2:a0:2a:83:d6:14 brd ff:ff:ff:ff:ff:ff
    inet 172.31.0.2/16 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a0a0:2aff:fe83:d614/64 scope link 
       valid_lft forever preferred_lft forever
```

**Anything else we need to know?**:

With rktnetes when a Kubelet starts pods with the `hostNetwork: false`, it calls `ip netns add <uuid>` in the `RunPod` / [`setupPodNetwork`](https://github.com/kubernetes/kubernetes/blob/d026286d39c43a7eb13030893a29d2b5446a0e04/pkg/kubelet/rkt/rkt.go#L1318)

The command `ip netns add ns-test-0` will mount `/run/netns` in addition.
```sudo ip netns add ns-test-0 ; mount | grep netns 
tmpfs on /run/netns type tmpfs (rw,nosuid,noexec,relatime,size=1609316k,mode=755)
nsfs on /run/netns/ns-test-0 type nsfs (rw)
nsfs on /run/netns/ns-test-0 type nsfs (rw)
```
The problem appear if you want to use something who deals with netns but without mounting the `/run/netns` like `rkt` does today.

If a rkt container is started  **before** a kubernetes `hostNetwork: false` pod it becomes a problem.

You can hack this by asking to systemd to mount a `/run/netns` tmpfs during the boot.

I replaced `ip netns add <uuid>` by the following [code](https://github.com/JulienBalestra/netns/blob/master/netns/ns.go) and it works but want to discuss about it before submitting a PR @yifan-gu @squeed 

**Environment**:
- Kubernetes version (use `kubectl version`): 
1.6.6, 1.7.0 + master

- Cloud provider or hardware configuration**: 
Baremetal and KVM

- OS (e.g. from /etc/os-release): 
Container Linux by CoreOS 1353.8.0 (Ladybug)

- Kernel (e.g. `uname -a`): 
```
Linux cp-0-172-20-0-67 4.9.24-coreos #1 SMP Tue May 30 23:12:01 UTC 2017 x86_64 Intel Core Processor (Broadwell) GenuineIntel GNU/Linux
```

- Install tools: 
[enjoliver](https://github.com/JulienBalestra/enjoliver)

**Comment by yifan-gu** [comment]
I guess one thing I don't understand is why mounting the `/run/netns` via `ip netns add` will cause the problem here?

**Comment by yifan-gu** [comment]
Reviewed the WIP patch, want to see if there are better options than using cgo + lockosthread. Especially for cgo I am not sure if there will be some build problem with that?

**Comment by JulienBalestra** [comment]
### Issue

@yifan-gu the issue come with the following steps:

1. system boot
2. systemd unit `ExecStart=<rkt --net=someNetwork my-aci:1>`
    
    - new netns like `/run/netns/cni-a4c0c2ab-358a-7c56-af6d-3bd3e078b1a5`


3. systemd unit `ExecStart=<kubelet>`
4. kubelet **RunPod** `hostNetwork: false`

    - called `ip netns add`: mounted `/run/netns` tmpfs
5. `my-aci:1` loose its cni-netns

### Solutions
For me there are few options:
1. don't run rkt --net containers outside of Kubernetes
2. dig into `ip netns` but doesn't looks like an easy [process](https://github.com/shemminger/iproute2/issues/11)
3. create a ip binary and override the $PATH of the kubelet

    - I tried but really [hacky](https://github.com/JulienBalestra/netns/blob/fe802a49a27c9aec509870d14261f7aecaf433d2/main.go#L11) + add a non explicit dependency needed to be maintain on the host
4. in the kubelet

    - need a new process: that's what you reviewed on my k8s fork.

### CGO

> Especially for cgo I am not sure if there will be some build problem with that?

I didn't have any trouble to compile hyperkube because the only include I need is `unistd.h`
Should this include be everywhere ?

Currently I counted around 25 `import "C"` in the Kubernetes repository

Sadly I didn't see other options: I'm far to be a netns stuff expert
But ATM the number 4 is the more suitable (for me).

**Comment by squeed** [comment]
Perhaps rkt should mount the tmpfs on `/run/netns` as well? That would be an easy fix.
