### ISSUE TITLE
Running vagrant on MacOS

### ISSUE THREAD

**Issue by johscheuer** [kubernetes/kubernetes#48424]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

I wanted to setup the vagrant Kubernetes setup [docs](https://github.com/kubernetes/community/blob/master/contributors/devel/local-cluster/vagrant.md) to test my binaries.

**What you expected to happen**:
Setup a minimal Kubernetes Cluster for testing with the `cluster/kube-up.sh` script. The needed certificats should be automatically generated by the setup:

https://github.com/kubernetes/kubernetes/blob/master/cluster/vagrant/util.sh#L293-L295

**How to reproduce it (as minimally and precisely as possible)**:
Run `./cluster/kube-up.sh` on MacOS

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**: Vagrant 1.9.6, VBox 5.1
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`): `Darwin .... 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64`
- Install tools:
- Others:

Logs:

```bash
./cluster/kube-up.sh 
... Starting cluster using provider: vagrant
... calling verify-prereqs
... calling verify-kube-binaries
... calling kube-up
Create Cluster
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'node-1' up with 'virtualbox' provider...
==> master: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> master: flag to force provisioning. Provisioners marked to run always will still run.
==> node-1: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> node-1: flag to force provisioning. Provisioners marked to run always will still run.
cat: /srv/kubernetes/kubecfg.crt: No such file or directory
```

**Comment by calvn** [comment]
Getting the same issue as well. @johscheuer have you found a proper way to develop on MacOS?

I found https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md, but that only works on linux as kubelet is not supported on darwin.

**Comment by dixudx** [comment]
@calvn You can enable `DOCKERIZE_KUBELET` by assigning a non-empty value.

**Comment by calvn** [comment]
Thanks, I'll give that a try!

**Comment by calvn** [comment]
@dixudx It seems that `DOCKERIZE_KUBELET` doesn't do anything since `start_kubelet` never gets called on MacOS. https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh#L898

**Comment by johscheuer** [comment]
I actually ended up testing on gce (just for simplicity)

**Comment by calvn** [comment]
So you just uploaded your modified binaries/releases (i.e. binaries/tars from `_output`) to gce every time when iterating/developing for k8s?
