### ISSUE TITLE
It should be possible to setup kubemark with kube-aggregator

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#48428]
We want kubemark setups to be as similar to real clusters as possible. Since we are launching kube-aggregator in real clusters, we should add a possibility (and probably also enable by default) to have kube-aggregator in front of apiserver(s).

@gmarek @shyamjvs @kubernetes/sig-scalability-feature-requests

**Comment by deads2k** [comment]
@cheftako was working on being able to use it in e2es.

**Comment by sttts** [comment]
With kube-aggregator integrated into kube-apiserver, is this still relevant?

**Comment by cheftako** [comment]
There are a few flags which need to be set up for kubemark to actually be properly testing with the aggregator. I am digging around in that code this week anyway. I will try to get to it and make sure its set up properly.

**Comment by shyamjvs** [comment]
@cheftako Thanks for looking. Let me know if I you need something.
