### ISSUE TITLE
Container events for failed probes not appearing

### ISSUE THREAD

**Issue by benbc** [kubernetes/kubernetes#48422]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I have defined readiness and liveness probes for the container in a Kubernetes deployment. When these fail I expect to see their output included in an event for the pod. However I don't see such events. I do see other events for the same pod.

The code that should produce the events is here: https://github.com/kubernetes/kubernetes/blob/v1.6.4/pkg/kubelet/prober/prober.go#L94.

What I see instead is logs indicating that a "ref" for the container could not be retrieved. I see similar logs for other places in the code that try to record container-related events.

**What you expected to happen**:

The events for the failed probe should appear in the event stream

These events are potentially very useful. In particular it's the only way to see output from a failing probe so that I can diagnose probes that are failing unexpectedly.

**How to reproduce it (as minimally and precisely as possible)**:

Follow [the probe example](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-command) from the documentation on GKE. Inspect the event stream and node logs.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.6.4
- Cloud provider or hardware configuration**: GKE

**Comment by supereagle** [comment]
@benbc  I have tested the example you mentioned on v1.6.4, but not reproduced this error.

There is event for probe failure in `kubectl describe pod liveness-exec`: 
`Warning		Unhealthy		Liveness probe failed: cat: /tmp/healthy: No such file or directory`

**Comment by benbc** [comment]
@supereagle Thank you for looking at this? What environment did you run that in, GKE?

**Comment by supereagle** [comment]
I test on my k8s cluster setup with VMs.  The k8s version is v1.6.4

**Comment by supereagle** [comment]
@benbc  Sorry for my mistake, I have reproduced this error. I will continue to look at this.

**Comment by benbc** [comment]
Thank you @supereagle.

**Comment by supereagle** [comment]
@benbc   This bug has been fixed by @derekwaynecarr in PR #46246, and cherry-picked into release-1.6 by PR #48099. The latest release [v1.6.7](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#downloads-for-v167) has included this patch, you can have a try on this release.

**Comment by benbc** [comment]
@supereagle Thank you.

I'm a little suprised that this is fixed by that PR. In my testing I see the `No ref for container` warning log ([here](https://github.com/yujuhong/kubernetes/blob/8f9935326781088f5f9e7587a2ca1d192a4269c7/pkg/kubelet/prober/prober.go#L98)), which I think indicates that the call to `.Eventf()` where the fix is ([here](https://github.com/yujuhong/kubernetes/blob/8f9935326781088f5f9e7587a2ca1d192a4269c7/pkg/kubelet/prober/prober.go#L103) or [here](https://github.com/yujuhong/kubernetes/blob/8f9935326781088f5f9e7587a2ca1d192a4269c7/pkg/kubelet/prober/prober.go#L108)) will never be made.

**Comment by supereagle** [comment]
In my test environment, not found the error `No ref for container`. Maybe this is another bug, but I am not sure how to reproduce it. You can have a try to verify this on the latest release v1.6.7.

**Comment by benbc** [comment]
@supereagle I'm not sure what I was doing differently. I am now seeing (on GKE) the error log `event.go:259] Could not construct reference to: '&v1.ObjectReference{Kind:"Pod"...`, which is suspect _is_ fixed by the PR you pointed to.

Kubernetes 1.6.7 is not yet available on GKE, so I can't test the fix in my exact environment.

I'll mark this as closed and reopen it if the problem turns out not to have been fixed by 1.6.7.

Thanks for your help.

**Comment by benbc** [comment]
I have confirmed that I no longer see the problem in 1.6.7 on GKE. Thanks for your help.

**Comment by supereagle** [comment]
@benbc  Thanks for your confirmation.
