### ISSUE TITLE
How to enable the CGO_ENABLED

### ISSUE THREAD

**Issue by jianzhangbjz** [kubernetes/kubernetes#48420]
Hi, 

I added a new package(`test`) in `plugin/pkg/scheduler/algorithm/priorities/` folder, but when exec `make`, got the below errors, the `import` package error. I referred to [godep.md](https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md), tried `go install ./...`, `./hack/godep-restore.sh` and `./hack/godep-save.sh` commands, but still can't solve it. 
So, how to update the packages dependencies? Or something else I missed?
 
```
    test/e2e_node/e2e_node.test
    cmd/gke-certificates-controller
plugin/pkg/scheduler/algorithm/priorities/test.go:7:2: no buildable Go source files in /home/zhangjian/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/priorities/test
!!! [0703 09:22:46] Call tree:
!!! [0703 09:22:46]  1: /home/zhangjian/src/k8s.io/kubernetes/hack/lib/golang.sh:740 kube::golang::build_binaries_for_platform(...)
!!! [0703 09:22:46]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0703 09:22:46] Call tree:
!!! [0703 09:22:46]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0703 09:22:46] Call tree:
!!! [0703 09:22:46]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make: *** [all] Error 1
```
```
root@test1:/home/zhangjian/src/k8s.io/kubernetes# go env
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/zhangjian"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build026544174=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```
```
root@test1:~# godep version
godep v74 (linux/amd64/go1.7.6)
```

**Comment by xiangpengzhao** [comment]
Are there any go files in your `test` dir? I think the error `no buildable Go source files` self explains.

**Comment by jianzhangbjz** [comment]
Sure, there are go files.

**Comment by jianzhangbjz** [comment]
My new `go` package, invoked `c` functions, so should I cross-compiling?
Already set `CGO_ENABLED=1`, but `make` still did not work.

**Comment by gyliu513** [comment]
I think that you may want to upgrade you go version to 1.8.1

```
root@k8s001:~# go version
go version go1.8.1 linux/amd64
root@k8s001:~#
```

**Comment by gyliu513** [comment]
Similar as https://github.com/kubernetes/kubernetes/issues/44096

**Comment by jianzhangbjz** [comment]
Still did not work, have already changed to `go.1.8.3`, like:
```
root@test1:/home/zhangjian/src/k8s.io/kubernetes# go version
go version go1.8.3 linux/amd64
```

**Comment by jianzhangbjz** [comment]
Whether the code of `cgo` lead to this issue?

**Comment by gyliu513** [comment]
Please check if this can help you https://github.com/kubernetes/kubernetes/issues/45214#issuecomment-298529356

**Comment by jianzhangbjz** [comment]
I compiled the `Go` binary from the source, and also cleaned the old folder, checkout to the `go master` branch to compile the `go`, but it still did not take effect.
Today, I will replace the `cgo` code and have a try. :) thanks @gyliu513

**Comment by jianzhangbjz** [comment]
Still did not work. I doubt it is a problem of package management. I just want to add myself package not the third package(example.com/xxx/xxx), is there any way?

**Comment by jianzhangbjz** [comment]
I found a `BUILD` file in each folder, like: [plugin/pkg/scheduler/algorithm/priorities/util/BUILD](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/priorities/util/BUILD). Is it auto-generated? Maybe the problem is here.

**Comment by xiangpengzhao** [comment]
It is auto-generated, but it's only used by [Building with Bazel](https://github.com/kubernetes/community/blob/master/contributors/devel/bazel.md), e.g. `make bazel-build`.

**Comment by xiangpengzhao** [comment]
Did you try to run the raw `go build` to build your own source files? Were there any errors? There may be some clues.

**Comment by jianzhangbjz** [comment]
@xiangpengzhao Oh, thanks!, Running `go build ./...` command under the `$GOPATH/src/k8s.io/kubernetes` folder, got a lot of `can't load package` errors about `staging`, but none of my source package. Then, run `go build ./...` cmd under the `$GOPATH/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/priorities`, no errors.

**Comment by xiangpengzhao** [comment]
I have no more ideas...

Since this issue is neither a bug nor a feature request, could you please re-post your question to [kubernetes on stackoverflow](https://stackoverflow.com/questions/tagged/kubernetes)? Hope we can get an answer there:)

**Comment by jianzhangbjz** [comment]
Sure, here: [How to add new packages in Kubernetes](https://stackoverflow.com/questions/44944004/how-to-add-new-packages-in-kubernetes). I doubt I missed something for the steps of updating package,  and hope to find the docs of the steps of adding new algorithm packages. :)

**Comment by jianzhangbjz** [comment]
This problem turned out to be caused by the `CGO_ENABLED` variable! Although I already set it enabled in environment variable as the below shows, but it is disabled in the [hack/lib/golang.sh](hack/lib/golang.sh), still need to modify it manually, it was torture. :scream:
```
root@heatonli-test1:/home/zhangjian/src/k8s.io/kubernetes# go env
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/zhangjian"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build959694934=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by spxtr** [comment]
What package are you trying to add? Why does it need CGO?
cc @ixdy , also see #48541

**Comment by jianzhangbjz** [comment]
@spxtr It is our own schedule algorithm packages made of the `c` code. We need to add it into `priority` module via the `cgo`.
