### ISSUE TITLE
CIDR issue

### ISSUE THREAD

**Issue by treemanzhou** [kubernetes/kubernetes#48436]
Hi developers 
    If I created multiple CIDR IPpool, How can I define which IPpool allocate IP when I make a pod run.  ,

**Comment by cmluciano** [comment]
I think this is only possible with some CNI plugins.

cc @caseydavenport @bboreham

**Comment by bboreham** [comment]
As far as I know there is no specific configuration inside Kubernetes to ask for a pod ip to conform to anything. 

This feature could be added on the outside by an annotation, and the CNI plugin could be extended to look for that annotation. I, personally, don't know of a plugin that does this.

**Comment by treemanzhou** [comment]
thanks a lot
