### ISSUE TITLE
Provisioned AWS EBS with invalid encryption key do not exist

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#48438]
/kind bug
When user requests an encrypted PV in AWS storage class and refers to an invalid / non-existing encryption key, then AWS provisioner happily creates the PV, but the backing AWS EBS volume does not exist.

Create class:
```shell
$ kubectl create -f - <<EOF
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "50"
  encrypted: "true"
  kmsKeyId: arn:aws:kms:us-east-1:555555555555:alias/nonExistingKey
EOF

storageclass "fast" created
```

Create a PVC:
```
$ kubectl create -f - <<EOF
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fastclaim
  annotations:
    "volume.beta.kubernetes.io/storage-class": "fast"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3.5Gi
EOF

persistentvolumeclaim "fastclaim" created
```

PVC is dynamically provisioned:
```
$ kubectl get pvc
NAME        STATUS    VOLUME                                     CAPACITY   ACCESSMODES   STORAGECLASS   AGE
fastclaim   Bound     pvc-4dc6cf13-6000-11e7-bb6f-0e908fa925c2   4Gi        RWO           fast           1m
```

But the backing AWS EBS does not exist:
```
$ kubectl describe pv pvc-4dc6cf13-6000-11e7-bb6f-0e908fa925c2
Name:           pvc-4dc6cf13-6000-11e7-bb6f-0e908fa925c2
Labels:         failure-domain.beta.kubernetes.io/region=us-east-1
                failure-domain.beta.kubernetes.io/zone=us-east-1d
Annotations:    kubernetes.io/createdby=aws-ebs-dynamic-provisioner
                pv.kubernetes.io/bound-by-controller=yes
                pv.kubernetes.io/provisioned-by=kubernetes.io/aws-ebs
StorageClass:   fast
Status:         Bound
Claim:          default/fastclaim
Reclaim Policy: Delete
Access Modes:   RWO
Capacity:       4Gi
Message:
Source:
    Type:       AWSElasticBlockStore (a Persistent Disk resource in AWS)
    VolumeID:   aws://us-east-1d/vol-0655743bad08b10ed
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
Events:         <none>

$ aws ec2 describe-volumes --volume-ids=vol-0655743bad08b10ed

An error occurred (InvalidVolume.NotFound) when calling the DescribeVolumes operation: The volume 'vol-0655743bad08b10ed' does not exist.
```

@kubernetes/sig-aws-misc
@kubernetes/sig-storage-bugs

**Comment by jsafrane** [comment]
Interesting, AWS cli has the same behavior. I.e. creation of a volume with an invalid key succeeds:

```
$ aws ec2 create-volume \
    --size=1 \
    --volume-type=gp2 \
    --availability-zone=us-east-1d \
    --encrypted --kms-key-id=arn:aws:kms:us-east-1:555555555555:alias/nonExistingKey

{
    "VolumeId": "vol-048aabc5ae0ea478a",
    "Size": 1,
    "SnapshotId": "",
    "AvailabilityZone": "us-east-1d",
...
}
```

But the volume itself does not exist:
```
$ aws ec2 describe-volumes --volume-ids=vol-048aabc5ae0ea478a

An error occurred (InvalidVolume.NotFound) when calling the DescribeVolumes operation: The volume 'vol-048aabc5ae0ea478a' does not exist.
```

Everything works when using an existing encryption key.

@justinsb, do you have any idea what's going on here and how to fix it? We could probably run DescribeVolume on a EBS after creation, just to check it's really created.

**Comment by jingxu97** [comment]
@jsafrane how about gce pd? I assume it will fail if creating a gce pd with invalid key?

**Comment by jsafrane** [comment]
@jingxu97 GCE does not manage encryption keys centrally via API calls, so it's not possible to get into this situation there.

**Comment by jsafrane** [comment]
I tried a simple fix, but when I use an invalid encryption key and AWS `CreateVolume` call returns a volume, subsequent `DescribeVolumes` on this volume is actually successful. The volume seem to exist for a short while, it appears after approx. 500ms . Now what?

**Comment by gnufied** [comment]
As suggested elsewhere this seems like an oversight/bug in EBS's implementation of `CreateVolume` API call. No error is shown in cloudtrail logs too when this happens.  We need to get in touch with Amazon and clarify what should be expected behaviour.

**Comment by dobbymoodge** [comment]
This is expected behavior, but since only engineers at Amazon expect this behavior I'm going to say it's still a bug. Here's the _official response_ I got from AWS Support:

> Thanks for your patience.  I've received word from our service team, and they've said that this is expected behavior because we will give a status of 'creating' and process the request internally, which tries the given KMS key, then fails.  They say that you can use Cloudwatch events as a workaround to see check error messages if the KMS key does not exist.  I'm pushing this into a feature request, as I believe a 4XX Client Error should be sent back if the KMS key does not exist.
> 
> Personally, I believe that adding a quick error-checking function such as describing the KMS key would be a good workaround in this case, which will fail the entire operation if the key doesn't exist when describing the key.
> 
> I don't have an ETA as to when this will be pushed out as a feature, but please let me know if you have any questions in the meantime.

The suggestion to validate the key *before* calling `CreateVolume` does seem to work, at least from the cli:

```
$ aws kms describe-key --key-id=arn:aws:kms:us-east-1:555555555555:alias/nonExistingKey ; echo "describe-key returned: $?"

An error occurred (AccessDeniedException) when calling the DescribeKey operation:
describe-key returned: 255
```

**Comment by jsafrane** [comment]
> $ aws kms describe-key --key-id=arn:aws:kms:us-east-1:555555555555:alias/nonExistingKey 

@dobbymoodge thanks for the feedback from Amazon. I'll add such check to AWS cloud provider to work around this.

/assign
