### ISSUE TITLE
<invalid> age shown for a running pod

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#48447]
Created a gossip-based cluster using kops 1.6.2. Created a WildFly RC using the resource file https://github.com/arun-gupta/kubernetes-java-sample/blob/master/wildfly-rc.yaml.

Watched the status as `kubectl get -w po`. Its shown as:

```
NAME               READY     STATUS              RESTARTS   AGE
wildfly-rc-1l9qv   0/1       ContainerCreating   0          <invalid>
wildfly-rc-6p7wk   1/1       Running   0         <invalid>
wildfly-rc-1l9qv   1/1       Running   0         6s
```

The second pod `AGE` is shown as `<invalid>` even though it's in `Running` status.

Terminating the watch and viewing the status again shows the output correctly as:

```
NAME               READY     STATUS    RESTARTS   AGE
wildfly-rc-1l9qv   1/1       Running   0          45s
wildfly-rc-6p7wk   1/1       Running   0         45s
```

**Comment by dixudx** [comment]
@arun-gupnta pod AGE shown as `<invalid>` is because of [the time difference between your kubectl
server and kubelet node](https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/internalversion/printers.go#L311). Maybe they are synced to different NTP servers.

**Comment by gtirloni** [comment]
@dixudx that's exactly the issue I was having with minikube + VirtualBox on Linux. After sleeping the host, the guest would get out of sync by roughly 30sec. Starting/stopping the VM didn't help. I had to restart the host and then the minikube VM would get sync'ed correctly.
