### ISSUE TITLE
Can't use  a load balancer in front of the etcd cluster for etcd-servers

### ISSUE THREAD

**Issue by FengyunPan** [kubernetes/kubernetes#48455]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
hang up when get kubernetes resource

**What you expected to happen**:
success to get pod 

**How to reproduce it (as minimally and precisely as possible)**:
1.    Set up an etcd cluster.
2.   Configure a load balancer in front of the etcd cluster. For example, let the address of the load balancer be $LB.
3.   Start Kubernetes API Servers with the flag --etcd-servers=$LB:2379
4.   run "kubectl get pod", then hang up

**Anything else we need to know?**:
It is OK to test it on etcd v2, but hang on etcd v3.
Maybe etcd v3 can't support loadbalancer ip of etcd cluster.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"b4c624f7fbb0ba2baa7ce4bd9cfabb4a85945cdb", GitTreeState:"clean", BuildDate:"2017-06-13T11:43:39Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"b4c624f7fbb0ba2baa7ce4bd9cfabb4a85945cdb", GitTreeState:"clean", BuildDate:"2017-06-13T11:43:39Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): centos 7.2
- Install tools:
- Others:
-bash-4.3# ETCDCTL_API=3 etcdctl version
etcdctl version: 3.1.3
API version: 3.1

**Comment by FengyunPan** [comment]
cc @xiang90  PTAL

**Comment by xiang90** [comment]
etcd3 uses http2. make sure your lb supports http2.

also this has nothing to do with k8s as far as i can tell. so closing.

**Comment by FengyunPan** [comment]
Sorry, can you tell more about it. My etcd3 has been disabled TLS and my lb is a simple loadbalance from Neutron, so it seems there is no relationship with https, please correct me if my understanding is wrong.

**Comment by xiang90** [comment]
@FengyunPan i never said it has anything to do with https. i said http2.

**Comment by FengyunPan** [comment]
Sorry, I'll check it, thank you very much.

**Comment by FengyunPan** [comment]
The reason is my lb can't support http2.

**Comment by chestack** [comment]
@xiang90 , any client should use http2 when to connect to etcd api (v3)?

**Comment by Jake-Smullin** [comment]
I'm actually experiencing this as well. I can confirm my NLB uses http2, created with `enable_http2` set to true. When I provide the api-servers with the flag --etcd-servers=https://$NLB_DNS:2379 keeps complaining about not being able to sync with the caches ```E0810 22:00:20.614259       1 controller_utils.go:1022] Unable to sync caches for crd-autoregister controller
I0810 22:00:20.614281       1 crdregistration_controller.go:115] Shutting down crd-autoregister controller
E0810 22:00:20.614299       1 customresource_discovery_controller.go:155] timed out waiting for caches to sync
I0810 22:00:20.614302       1 serve.go:129] Stopped listening on 127.0.0.1:8080
I0810 22:00:20.614313       1 naming_controller.go:278] Shutting down NamingConditionController
E0810 22:00:20.614322       1 cache.go:35] Unable to sync caches for APIServiceRegistrationController controller
E0810 22:00:20.614333       1 cache.go:35] Unable to sync caches for AvailableConditionController controller
I0810 22:00:20.614343       1 crd_finalizer.go:246] Shutting down CRDFinalizer
I0810 22:00:20.614348       1 controller.go:90] Shutting down OpenAPI AggregationController``` any help would be appreciated, our ETCD cluster will now use dynamic IPs not static so I can't just place the actual IPs:2379 of the quorum as the flags value anymore.
