### ISSUE TITLE
Heapster metrics don't match container runtime metrics

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/kubernetes#48458]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Kubernetes container CPU metrics (from heapster) do not correlate with container run time (Docker) CPU utilization metrics.

**What you expected to happen**:

We recently switched over our production environment to Kubernetes. I'd like to enforce CPU limits on the containers. I'm getting conflicting CPU metrics that do not fit together. Here's my setup:

* DataDog agents running as a `Daemonset`
* Existing applications running without CPU Limits
* Containers in question are multi-threaded Ruby applications
* Two metrics: `kubernetes.cpu.usage.{avg,max}` and `docker.cpu.usage`
* `c4.xlarge` cluster nodes (4 vCPUs or 4000m in Kubernetes terms)

`kubernetes.cpu.usage.max` reports ~600m for the containers in question. `docker.cpu.usage` reports ~60%. It follows that a 1000m CPU limit would be more than enough capacity under normal operation. 

I set the limit to 1000m. Then `docker.container.throttles` goes up significantly while `kubernetes.cpu.usage.max` and `docker.cpu.usage` stay the same. The system all fells to it's knees during this time. This does not make sense to me.

I researched Docker stats. It seems that `docker stats` (and the underlying API) _normalize_ load according to CPU cores. So in my case, `docker.cpu.usage` of 60% comes (4000m * 0.60) to 2400m in Kubernetes terms. However this does not correlate with any Kubernetes numbers. I did another experiment to test my hypothesis that Kubernetes numbers are incorrect. I set the limit to 2600m (for some extra headroom). This did not result in any throttles. However Kubernetes observed CPU usage did not change. This leaves me confused.

**How to reproduce it (as minimally and precisely as possible)**:

Honestly, I'm not sure if this is a problem with my applications or Kubernetes. In theory it should be easy enough to:

1. Start a multi-threaded process (like a Ruby web application running Puma) on a multi-core machine
2. Trigger sufficient load
3. Correlate runtime metrics (`docker stats`) with Kubernetes heapster metrics.

**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"clean", BuildDate:"2017-03-28T13:54:20Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T09:42:05Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
`
- Cloud provider or hardware configuration**: AWS  w/ c4.xlarge nodes
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`): `Linux ip-172-20-53-132 4.4.65-k8s #1 SMP Tue May 2 15:48:24 UTC 2017 x86_64 GNU/Linux`
- Install tools: kops 1.6.1
- Others:

**Comment by ahawkins** [comment]
/sig node


On Tue, Jul 4, 2017, at 01:30 PM, Kubernetes Submit Queue wrote:
> @ahawkins[1] There are no sig labels on this issue. Please add a sig
> label[2] by:> (1) mentioning a sig: @kubernetes/sig-<team-name>-misc
> e.g., @kubernetes/sig-api-machinery-* for API Machinery
> (2) specifying the label manually: /sig <label>
> e.g., /sig scalability for sig/scalability
> 
> *Note: method (1) will trigger a notification to the team. You can
> find the team list here[3] and label list here[4]*> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[5], or mute the thread[6].> 

Links:

  1. https://github.com/ahawkins
  2. https://github.com/kubernetes/test-infra/blob/master/commands.md
  3. https://github.com/kubernetes/community/blob/master/sig-list.md
  4. https://github.com/kubernetes/kubernetes/labels
  5. https://github.com/kubernetes/kubernetes/issues/48458#issuecomment-312808680

**Comment by ahawkins** [comment]
ping @kubernetes/sig-node-misc

**Comment by DirectXMan12** [comment]
@kubernetes/sig-node-bugs @kubernetes/heapster-maintainers 

@ahawkins is it just the metrics through Heapster?  If you look at the Prometheus metrics exposed by Kubelet, or at the summary endpoint `$KUBELET/stats/summary`, do you get the same numbers as through Heapster?  Just want to make sure it's not a Heapster issue.
