### ISSUE TITLE
Expose namespace_id through the Downward API

### ISSUE THREAD

**Issue by loburm** [kubernetes/kubernetes#48461]
/kind feature

Currently Downward API supports only pod name and namespace name. For the prometheus-to-sd component we need to have an access also to id's of these objects, so correct gke_container resource for Stackdriver could be created: https://cloud.google.com/monitoring/api/resources

**Comment by xiangpengzhao** [comment]
@loburm This is introduced by https://github.com/kubernetes/kubernetes/pull/48125

**Comment by piosz** [comment]
@xiangpengzhao awesome! how about namespace_uid?

**Comment by xiangpengzhao** [comment]
@piosz I misread. I thought only pod uid was expected. namespace uid is not supported yet. If supportting it makes sense, I will send a PR to add it.

**Comment by piosz** [comment]
@xiangpengzhao the original issue was only about pod_id while we'd like to see also namespace_id, so I'd glad to see PR with namespace_id also.

Also could you please update [the documentation](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api)?

**Comment by xiangpengzhao** [comment]
Thanks! Will do.

**Comment by piosz** [comment]
thanks @xiangpengzhao!

**Comment by xiangpengzhao** [comment]
Take another look at the issue and find that we aren't able to expose namespace uid through the Downward API, unfortunately.

Currently Downward API supports `fieldRef` which selects a field of the pod, and `resourceFieldRef` which selects a resource of the container. However, namespace-uid is not a field of the pod. We can't expose it as a field.

@piosz @loburm

**Comment by piosz** [comment]
Got it. Thanks @xiangpengzhao for the clarification.
@loburm it seems we need to live without namespace-id.

**Comment by loburm** [comment]
Thanks for checking it.
