### ISSUE TITLE
Get pod log too slow 

### ISSUE THREAD

**Issue by WIZARD-CXY** [kubernetes/kubernetes#48465]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

When I want to get a pod log, it takes so long to get the result back. For example:
$ kubectl logs  test-args-4026945960-4pmmv --since=59s -n u-keadmin-default

the apiserver log is below(use 1m7s for this request):
```
I0704 09:27:27.119187       1 wrap.go:75] GET /api/v1/namespaces/u-keadmin-default/pods/test-args-4026945960-4pmmv/log?follow=true&sinceSeconds=59: (1m7.037577335s) 200 [[kubectl/v1.6.1 (darwin/amd64) kubernetes/$Format] 10.200.20.66:52790
```
and the kubelet cpu usage is high.I did the cpu profiling on kubelet and found out json Unmarshal is using most cpu time.
**What you expected to happen**:
quickly get pod log
**How to reproduce it (as minimally and precisely as possible)**:
use kubectl to get a long-running pod's log

**Anything else we need to know?**:
I look through the code and find that there are two log format supported, one is cri format, one is docker json-file log. CRI log format is simple and cpu-friendly. Can we use that for docker container?

**Environment**:
- Kubernetes version (use `kubectl version`):  1.6.0
- Cloud provider or hardware configuration**: bare
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.4
- Install tools: kubeadm
- Others:
none

**Comment by WIZARD-CXY** [comment]
@kubernetes/sig-node

**Comment by WIZARD-CXY** [comment]
@Random-Liu, I found out you implemented almost log functionality, can u give me some advice on how to quickly get pod log? Thanks

**Comment by WIZARD-CXY** [comment]
@k8s-merge-robot /sig node

**Comment by WIZARD-CXY** [comment]
I read the design-proposal doc https://github.com/kubernetes/community/blob/master/contributors/design-proposals/kubelet-cri-logging.md

```
In the short term, the ongoing docker-CRI integration [3] will support the proposed solution only partially by (1) creating symbolic links for kubelet to access, but not manage the logs, and (2) add support for json format in kubelet. A more sophisticated solution that either involves using a custom plugin or launching a separate process to copy and decorate the log will be considered as a mid-term solution.
```
And I think  maybe we can write a docker log plugin to do this?https://docs.docker.com/engine/admin/logging/plugins/#install-the-logging-driver-plugin

**Comment by crassirostris** [comment]
/sig instrumentation

@WIZARD-CXY What is the volume of logs? What is the network throughput?

**Comment by crassirostris** [comment]
@WIZARD-CXY 1 minute seems highly suspicious. Usually, container logs would be under 10MB in size, you don't need much time to parse 10MB of jsons. Anyway, to confirm your suspicion about parsing logs, you can try using `tail` option, otherwise kubelet reads and parses all entries starting from the beginning of the file [\[1\]](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_logs.go#L121).

> And I think maybe we can write a docker log plugin to do this?https://docs.docker.com/engine/admin/logging/plugins/#install-the-logging-driver-plugin

Kubernetes abstract docker away, we don't plan to have a runtime-specific solution

> I look through the code and find that there are two log format supported, one is cri format, one is docker json-file log. CRI log format is simple and cpu-friendly. Can we use that for docker container?

We're working on that, but there're some problems, e.g. described in https://github.com/kubernetes/kubernetes/issues/44976

**Comment by WIZARD-CXY** [comment]
@crassirostris thanks for your reply. The log has about 1000 lines and the network bandwidth is large enough because I use it in a small cluster, the network throughput is not a problem.

**Comment by WIZARD-CXY** [comment]
@crassirostris I think I know why it is slow. Although they are all 900 lines of log, but use tail(time <1s) to specify the line is much more faster than use since(about 1m). Because according to function ```ReadLogs``` implementation, when you use since method, it needs to json.Unmarshal all the log lines in the log file to determine whether it should be in the result or not while tail method is much easiser(it just use Seek to reach the right read point . So if log  file is really large(maybe it has 10-day log), but you want to access  only 10m ago's log, using "since" is really painful.

**Comment by WIZARD-CXY** [comment]
I think when use since option to get log, kubelet should use binary search to get to the right read point instead of linear search which  is really slow. I can submit a pr to fix this. @crassirostris @Random-Liu

**Comment by crassirostris** [comment]
@WIZARD-CXY Yes, that's exactly what I meant

> I think when use since option to get log, kubelet should use binary search to get to the right read point instead of linear search which is really slow. I can submit a pr to fix this. @crassirostris @Random-Liu

Binary search is an obvious enhancement, but I don't know the node team plans regarding it. I think the complexity in the `ReadLogs` function is getting out of hand and it requires careful refactoring, but I'll be happy to see your contribution :)

Let's wait for what @Random-Liu thinks about this

**Comment by WIZARD-CXY** [comment]
ok

**Comment by WIZARD-CXY** [comment]
@Random-Liu any thoughts?

**Comment by WIZARD-CXY** [comment]
I read the docker log search code only to find it is using linear search to find the correct since read point.The function signature (in docker 1.13.0) is ```func (l *JSONFileLogger) readLogs(logWatcher *logger.LogWatcher, config logger.ReadConfig) { ```

**Comment by crassirostris** [comment]
@WIZARD-CXY Oh, he's not available currently

@yujuhong @dashpole @dchen1107 Do you have any thoughts on tuning the read logs method's performance? Are you OK with contributions to this part?

**Comment by yujuhong** [comment]
The log reading code in kubelet mimics what's in the moby/docker code, so both of them use the same seek method. 

> @WIZARD-CXY 1 minute seems highly suspicious. Usually, container logs would be under 10MB in size, you don't need much time to parse 10MB of jsons. Anyway, to confirm your suspicion about parsing logs, you can try using tail option, otherwise kubelet reads and parses all entries starting from the beginning of the file [1].

@WIZARD-CXY, as @crassirostris mentioned, parsing a 10MB log should not take a minute in typical conditions. What's the size of your log and could you rotate the logs more frequently if the file sizes are too large?

I'd like to confirm the impact of this issue before diving in to optimize the code :)

**Comment by WIZARD-CXY** [comment]
@yujuhong The log size is very large (apiserver log). I think about the log-rotate solution too, but it is not enough IMHO, Because if we rotate the log per day, what about querying the log of day before yesterday? For very large logs we should use elasticsearch to do the log search job. But I think it is still nice to use binary search to speed up the log search when using kubectl

**Comment by WIZARD-CXY** [comment]
I thought it was a easy piece of work to do only to find I am wrong because it is not straightforward to jump to arbitratry line of a log file which binary search requires. But I think if we code up this feature using one day's time, it is worth doing. :)

**Comment by crassirostris** [comment]
If it's about apiserver logs, even GCE setup rotates it once every 100MB and reading it from the beginning can actually cause some delays. If using a third-party solution is not an option, binarysearching the offset seems reasonable

> I thought it was a easy piece of work to do only to find I am wrong because it is not straightforward to jump to arbitratry line of a log file which binary search requires.

You just have to linearly find the next `\n` after selecting the middle point. It works fine, I've seen this approach used before on many-GB files.

**Comment by WIZARD-CXY** [comment]
My approach is using binary search on file size.First seek to middle of the file and then look around for the line and get time of this line then decide which half to jump to.

**Comment by crassirostris** [comment]
@WIZARD-CXY Yup, I meant exactly that, sorry for confusing

**Comment by yujuhong** [comment]
> For very large logs we should use elasticsearch to do the log search job. But I think it is still nice to use binary search to speed up the log search when using kubectl

Indeed, this is a "nice" feature to have, but not a necessity since logs can be archived and searched more efficiently in other manners.

> If it's about apiserver logs, even GCE setup rotates it once every 100MB and reading it from the beginning can actually cause some delays. If using a third-party solution is not an option, binarysearching the offset seems reasonable

By default in a GCE cluster, kubelet on the master node does not serve logs (`--enable-debugging-handler=false`), so this is not really an issue.

I am not against optimizing the seeking, but I do have some doubts on whether the benefits outweigh the extra complexity. If @crassirostris has time to review/shepherd the implementation, I'd be fine with that.

**Comment by crassirostris** [comment]
> By default in a GCE cluster, kubelet on the master node does not serve logs (--enable-debugging-handler=false), so this is not really an issue.

That's a great point, thanks

> I am not against optimizing the seeking, but I do have some doubts on whether the benefits outweigh the extra complexit. If @crassirostris has time to review/shepherd the implementation, I'd be fine with that.

Sure, and big thanks for that! :)

Additionally, I've just realized that apiserver logs are not written to the stdout of the process in some setups. Also, in the future, we might want to read previous rotations of the container's log, which will also reduce the value of the binary searching in a single file. Also there's a CRI format issue regarding using end line as a separator, which may also influence the code

And, unfortunately, I'm pretty overloaded this quarter and won't be able to provide a quality review in time. As a mitigation, I can suggest introducing log rotations, exporting logs to a better accessible place or some combination of those. But if there's someone else who's ready to wight all possible problems and shepherd the implementation, I'll be happy to see it happening

**Comment by WIZARD-CXY** [comment]
@crassirostris I understand your concern. close for now
