### ISSUE TITLE
unable to list third party defined resource 1.7.0

### ISSUE THREAD

**Issue by sbezverk** [kubernetes/kubernetes#48476]
/kind bug
@kubernetes/sig-auth
**What happened**:
thirdpartyresource defines new kind networks.kuberbetes.com, I modify cluster roles
to allow system:nodes group to access it:

```- apiGroups:
 - "extensions"
  resources:
  - networks.kubernetes.com
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - patch
  - update

and in cluster role bindings

subjects:
- kind: Group
  name: system:nodes
```
**What you expected to happen**:
I am expecting to be able to list it with system:node:{node name} but instead I get forbidden.

kubectl get networks --as-group=system:nodes --as=system:node:sbezverk-srv-10.sbezverk.cisco.com
Error from server (Forbidden): User "system:node:sbezverk-srv-10.sbezverk.cisco.com" cannot list networkses.kubernetes.com in the namespace "default". (get networkses.kubernetes.com)

If I run command with regular user admin, it works fine.
```
kubectl get networks
NAME           KIND                         ARGS                                               PLUGIN
flannel-conf   Networks.v1.kubernetes.com   [ { "delegate": { "isDefaultGateway": true } } ]   flannel
```
**How to reproduce it (as minimally and precisely as possible)**:

create new thridpartyresource and try to access it with system:node:{node-name} account
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.0
- Cloud provider or hardware configuration**: Baremetal, cluster bootstrapped with kubeadm
- OS (e.g. from /etc/os-release): Centos 7.3
- Kernel (e.g. `uname -a`): 3.10.0-514.26.1.el7.x86_64
- Install tools: kubeadm init
- Others:

**Comment by sbezverk** [comment]
@kubernetes/sig-auth

**Comment by xilabao** [comment]
do you create the cluster role using "kubectl create role" command? I think the apiGroup should be "kubernetes.com" and the resource should be "networks".

**Comment by sbezverk** [comment]
@xilabao I do not use "kubectl create role" command, I just created yams file with definitions I needed.  
I tried what you suggested but still see the same issue:
```apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:tpr
rules:
- apiGroups:
  - "extensions"
  resources:
  - thirdpartyresources
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - "kubernetes.com"
  resources:
  - networks
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - patch
  - update
```

```kubectl get networks --as-group=system:nodes --as=system:node:sbezverk-srv-10.sbezverk.cisco.com

Error from server (Forbidden): User "system:node:sbezverk-srv-10.sbezverk.cisco.com" cannot list networkses.kubernetes.com in the namespace "default". (get networkses.kubernetes.com)
```

**Comment by xilabao** [comment]
`networkses.kubernetes.com` is odd.  the name might be "network.kubernetes.com"

```
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
metadata:
  name: network.kubernetes.com
...
```

**Comment by liggitt** [comment]
The resource is likely `networkses`:

```
- apiGroups:
  - "kubernetes.com"
  resources:
  - networkses
  ...
```

**Comment by liggitt** [comment]
the forbidden error from the API server lists the actual resource name (`kubectl get ... --v=6` also shows the actual resource name in the URL. The policy must match the resource name in the URL.
