### ISSUE TITLE
REST API: labelSelector matchExpressions?

### ISSUE THREAD

**Issue by bryanlarsen** [kubernetes/kubernetes#48472]
When writing some code against the Rest Job List API (https://kubernetes.io/docs/api-reference/v1.6/#list-45), I expected the labelSelector parameter to use the same syntax as the new style selectors (with matchLabels and matchExpressions).   So then I set about trying to find the documentation on how you expect an object to be encoded into a query string.   It was only after I failed to find such documentation that I decided to try old style selector encoded naively: `?labelSelector=component%3Dfoo` that I got it to work.

So that brings up two points:

1: query string encoding should be documented in the API OVERVIEW section of the API Reference; or at least that's where I expected it.   I did find examples suggesting that it's encoded something like ?labelSelector=foo%3Dhello%2Cbar=%3Dworld but it'd be nice to get that explicitly documented.

2: it'd be nice to get matchExpressions support into the API.

**Comment by bryanlarsen** [comment]
@kubernetes/sig-api-machinery-*

**Comment by lavalamp** [comment]
@kubernetes/sig-docs-maintainers for the documentation issue

@deads2k @smarterclayton I am not sure who owns the label selector parameter, does one of you know? It does seem like it should support both syntaxes.
