### ISSUE TITLE
build/ docker scripts hang on Docker 17.06.0-ce

### ISSUE THREAD

**Issue by cblecker** [kubernetes/kubernetes#48478]
Ran into a local environment issue when running things through the build/ scripts and docker images. When running Docker CE for Mac 17.06, I found there was a functionality change on `docker wait`.. previously if the container specified didn't exist, `docker wait` would just exit with an error and a non-zero status. However, on 17.06, the command (and the build/ script) hangs and doesn't exit.

`docker wait` is used here: https://github.com/kubernetes/kubernetes/blob/733bb2c31d84f8d1c153d7115a21d5d5c7607cc7/build/common.sh#L387

Upstream issue opened: https://github.com/moby/moby/issues/33948

/area build-release
/sig contributor-experience
/assign
cc: @ixdy @luxas @sttts

**Comment by cblecker** [comment]
Looks like this is a bug that will be fixed in 17.06.1. Reverting back to 17.03 (previous stable) fixes in short term.

**Comment by ixdy** [comment]
FWIW, it seems that workaround was added in Dec 2014 (https://github.com/kubernetes/kubernetes/commit/21eb09fb6a2) for https://github.com/docker/docker/issues/3968.

The comment there suggests it was hard to reproduce as of docker 1.11; apparently https://github.com/moby/moby/pull/20848 (targeted for docker 1.13) may have fixed it for good.

**Comment by ixdy** [comment]
cc @zmerlynn

**Comment by cblecker** [comment]
cc @spiffxp who I'm guessing stumbled on this same thing an opened dupe tickets with docker/moby heh

**Comment by spiffxp** [comment]
Yeah note to self, filing issues on moby directly gets a faster response. Thanks @cblecker

**Comment by pmichali** [comment]
I did this hack to get around the issue:
```
diff --git a/build/common.sh b/build/common.sh
index 67b0a4927d..01b475fa4f 100755
--- a/build/common.sh
+++ b/build/common.sh
@@ -383,9 +383,14 @@ function kube::build::short_hash() {
 # container, wait to ensure it's stopped, then try the remove. This is
 # a workaround for bug https://github.com/docker/docker/issues/3968.
 function kube::build::destroy_container() {
-  "${DOCKER[@]}" kill "$1" >/dev/null 2>&1 || true
-  "${DOCKER[@]}" wait "$1" >/dev/null 2>&1 || true
-  "${DOCKER[@]}" rm -f -v "$1" >/dev/null 2>&1 || true
+  if "${DOCKER[@]}" ps -a | grep "$1"; then
+      echo "Container exists"
+      "${DOCKER[@]}" kill "$1" >/dev/null 2>&1 || true
+      "${DOCKER[@]}" wait "$1" >/dev/null 2>&1 || true
+      "${DOCKER[@]}" rm -f -v "$1" >/dev/null 2>&1 || true
+  else
+      echo "No running container"
+  fi
 }

 # ---------------------------------------------------------------------------
```

**Comment by cblecker** [comment]
Fixed in our repo by https://github.com/kubernetes/kubernetes/pull/48762
