### ISSUE TITLE
Add --allow-host-ports flag to master and kubelet

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#4849]
People often use hostPort when they shouldn't. Additionally, host ports are a precious resource. Eventually we should have a policy that controls access by namespace. For now, we should use the same approach as privileged.

hostDir is similar security-wise to privileged, but doesn't cause as much confusion as hostPort.

@thockin @derekwaynecarr

**Comment by thockin** [comment]
I am in favor of this, given that we know we need better docs already.
HostPorts almost always indicate some misunderstanding.

**Comment by bgrant0607** [comment]
See also #1567.

**Comment by erictune** [comment]
Suggest making this a "capability" as described in #2502

**Comment by mikedanese** [comment]
This is handled by pod security policy so I don't think we need the flag.
