### ISSUE TITLE
Pod which is Complete is back to life

### ISSUE THREAD

**Issue by Iwan-Zotow** [kubernetes/kubernetes#48506]
/kind bug

**What happened**:

Running multiple computation jobs on Google Computing Engine, Docker, and watch how many pods are
done and how many still running. When checking pods for completion, one pods (and I
don't know which one) suddenly moves back to Running.

See terminal output below

beamuser@pigsty:~/Documents/EGS/runEGS/XcScripts$ kubectl get pods -a | grep Co | wc
    588    2940   34104
beamuser@pigsty:~/Documents/EGS/runEGS/XcScripts$ kubectl get pods -a | grep Co | wc
    593    2965   34394
beamuser@pigsty:~/Documents/EGS/runEGS/XcScripts$ kubectl get pods -a | grep Co | wc
    597    2985   39402
beamuser@pigsty:~/Documents/EGS/runEGS/XcScripts$ kubectl get pods -a | grep Co | wc
    596    2980   34568
beamuser@pigsty:~/Documents/EGS/runEGS/XcScripts$ kubectl get pods -a | grep Co | wc
    596    2980   34568

**What you expected to happen**:

There is no restart policy, and once pod is completed it should stay completed

**How to reproduce it (as minimally and precisely as possible)**:

Cannot reproduce at will, but it happens sometimes

**Environment**:

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
Google Computing Engine
- OS (e.g. from /etc/os-release):
Linux/Docker
- Kernel (e.g. `uname -a`):
Linux pigsty 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
Docker version 1.12.6, build 78d1802

**Comment by yujuhong** [comment]
I believe this has more to do with how `kubectl` displays the information. The `STATUS` column of `kubectl` may show `Completed` even though the pod is being restarted.
