### ISSUE TITLE
Change mechanism of zone selection for dynamic provisioning

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#48504]
Using AWS as an example, the current zone selection mechanism looks like following (assuming no zone is specified in StorageClass)

1. Filter all running instances in the region. The region information is usually derived from zone information configured in cloudprovider's config. 
2. Make a set of zones from running instances in the region.
3. select a zone from list of zones in step#2 using round robin method (more or less)

This creates bunch of problems if there are more than one clusters running in the region or there are nodes which don't participate in Kube cluster. 

Our current fix to solve this problem is - tag all instances participating in clustering with some sort of cluster-id (we have 2 distinct ways of tagging instances right now but leaving that aside).  The tagging mechanism is very much tool specific and relying on it completely leads to surprising behaviour.

In stead of relying on running instances, can we not instead keep a set of zones via node information present in node informer and use this set for determining zone of PV?

This will most likely result in change in `Provision` interface because for most part-  volume plugins don't initialize or have access to informers, so `zone` has to be selected before making `Provision` call or some other related change has to be done. 

cc @jsafrane @kubernetes/sig-storage-api-reviews

**Comment by jsafrane** [comment]
What Cinder provisioner does is that it lists nodes from API server. They have region+zone labels and we can be sure they belong to the right cluster. On the other way, this list is not cached... Perhaps we could enhance `Provision()` call with a node informer?

**Comment by msau42** [comment]
FWIW for gce, we added a call to the cloud provider to list the nodes from the informer and cache the zones.

**Comment by msau42** [comment]
ref #52322
