### ISSUE TITLE
Document apiserver's proxy, especially rewriting

### ISSUE THREAD

**Issue by discordianfish** [kubernetes/kubernetes#48503]
> Uncomment only one, leave it on its own line: 
/kind feature

**What happened**:
I'm trying to reach a application which includes some resources in HTML, some other dynamically from js.

The apiserver proxy appears to dynamically rewrite the html to "fix" URL urls by prepending the proxy path (e.g `/api/v1/namespaces/default/services/prometheus/proxy/`). That doesn't work for things loaded via js.

Now the application supports setting a proxy prefix to support reverse proxies exposing the service on a different path, which prefixes all URLs, including those loaded by js. But since the apiserver proxy seems also prefixes the path, you end up with both.

**What you expected to happen**:
It took my too long to figure out it's the apiserver proxy which adds the second set of prefixes. In fact, I'm still not 100% sure and I can't find any documentation about this.

While I'm not sure how I feel about the rewriting in general, it should be at least documented but I couldn't find anything in https://kubernetes.io/docs/concepts/cluster-administration/proxies/ nor https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#manually-constructing-apiserver-proxy-urls

**Comment by discordianfish** [comment]
@kubernetes/sig-networking

**Comment by lavalamp** [comment]
@mml suggests that the rewriter could at least leave an HTML comment behind explaining it has helpfully "fixed" your HTML.

**Comment by shiywang** [comment]
@lavalamp I would like to take a look on this one, could you assign to me ?

**Comment by nikhita** [comment]
@shiywang This issue has a help-wanted label. Are you still intending to work on this? If yes, I'll remove the label.

Just trying to make sure that all help-wanted issues are issues where we are really looking for help, and they are up-to date. :)

**Comment by discordianfish** [comment]
Not going to waste more time with that bot.
