### ISSUE TITLE
LoadBalancer service without affinity

### ISSUE THREAD

**Issue by FengyunPan** [kubernetes/kubernetes#48500]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
Creating service(type: LoadBalancer, sessionAffinity: ClientIP), service has no affinity.

**What you expected to happen**:
The service has affinity
**How to reproduce it (as minimally and precisely as possible)**:
1. Create a service, its yaml as following:
kind: Service
apiVersion: v1
metadata:
  labels:
    app: application
  name: application
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9091
  sessionAffinity: ClientIP
  selector:
    app: application
2. Get request from Neutron, check the value of "Persistence"

**Anything else we need to know?**:
Kubernetes's OpenStack cloudprovider can't set persistence to "SOURCE_IP".

**Environment**:
- Kubernetes version (use `kubectl version`):    kubernetes 1.6.4

**Comment by cblecker** [comment]
Fixed in #48501
/close
