### ISSUE TITLE
Make nodes upload logs to GCS directly instead of going through jenkins worker

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#48513]
We're currently copying logs from each of the nodes to the jenkins worker (through ssh) and then uploading that bulk of logs from the worker to GCS. This poses multiple issues:
- It's super time-consuming (eg. on large cluster (5k-node) this takes ~5 hrs) and so wastes money
- We're blocked on the worker's network bandwidth
- We overwhelm the worker's disk (thrashing it in case of 5k-node tests)

We already have a [logexporter](https://github.com/kubernetes/test-infra/tree/master/logexporter) tool that can directly upload node logs to GCS when run as a container on the node.
I tested by running it on 5k-node cluster as a daemonset and it took just 7 mins to upload all the logs (nothing compared to the current time of 5 hrs).
It remains to be incorporated into the e2e testing framework.

cc @kubernetes/sig-scalability-misc @kubernetes/test-infra-maintainers

**Comment by shyamjvs** [comment]
FYI, https://github.com/kubernetes/kubernetes/pull/48204 was sent a short-term fix.
cc @spiffxp

**Comment by krzyzacy** [comment]
will move the job from jenkins to prow make it easier to incorporate with logexporter?

**Comment by shyamjvs** [comment]
I don't think it affects much. I need to make the change inside the kubetest binary (where we do the logdump step) and that isn't really related to where we're running it IIUC.

**Comment by krzyzacy** [comment]
ah, true, not super familiar with the dump script, so I guess the plan is to add another dump mode for scalability jobs? Or the logexporter will be good for any e2e tests?

**Comment by fejta** [comment]
Nice work so far!

BTW should we make this the default behavior once we have it working for the large jobs?

**Comment by wojtek-t** [comment]
> BTW should we make this the default behavior once we have it working for the large jobs?

We need a careful discussion about this. The problem is e.g. what if node is unready after tests?
As of now, we won't be able to schedule anything there, and thus won't get logs from it.
At some point we may be in better position, when we will be able to schedule on not-ready nodes (this is planned, there is an open issue for it), but still if kubelet will be down we won't be able to gather logs using this approach.

That said, I think that long term we should have some kind of hybrid (use logexporter for healthy nodes, and ssh to unhealthy or sth like that) and once we have this, this should be used by all jobs (not only the large ones).

**Comment by shyamjvs** [comment]
+1 to what Wojtek wrote. In fact not just kubelets, we want most control plane components to be working. However we don't need the scheduler as most likely we're going to run it as a daemonset.

**Comment by wojtek-t** [comment]
Daemons may use scheduler in the relatively near future: https://github.com/kubernetes/kubernetes/issues/42002

**Comment by shyamjvs** [comment]
Aah! Thanks for the lead.

**Comment by zmerlynn** [comment]
> The problem is e.g. what if node is unready after tests?
As of now, we won't be able to schedule anything there, and thus won't get logs from it.
At some point we may be in better position, when we will be able to schedule on not-ready nodes (this is planned, there is an open issue for it), but still if kubelet will be down we won't be able to gather logs using this approach.

It's worse than this. The most common case I want logs when kubelet is down is actually when we have cluster up failures and kubelet or some other piece never came up. A log dump mechanism that relies on kubernetes while we're testing kubernetes is going to be insufficient, and I don't think we should switch. This is the exact reason that the custom pieces in `log-dump.sh` have to shell out to something cloud provider specific to even query the viable nodes - when I was working on kops testing, I tried to just use the `get nodes` approach and there were too many cases that logs weren't there for the nodes I needed.

Can we discuss the whole approach before we switch over to a solution that seems unlikely to fulfill needs?

**Comment by zmerlynn** [comment]
Ah, I re-read the PR. You're ensuring logexport on the node is working or SSHing when it isn't. And it keeps the original use of the cloud provider to get the node list. SGTM.

**Comment by shyamjvs** [comment]
Ok... So finally logexporter has become stable after all those fixes and is working fine in multiple of our scalability jobs.
E.g - 
https://k8s-testgrid.appspot.com/google-gce-scale#gce
https://k8s-testgrid.appspot.com/google-gce-scale#gci-gce
https://k8s-testgrid.appspot.com/google-gce-scale#gce-scale-performance

**Comment by shyamjvs** [comment]
@fejta We should move all the remaining jobs to using logexporter too (except previous release branches which don't have logexporter support). It's super fast (an order of magnitude faster for large tests) and clean.

**Comment by shyamjvs** [comment]
Filed the above issue to move all our jobs to using it. Closing this one.
Thanks everyone! :)
