### ISSUE TITLE
Pods sometimes don't get an IP if kubelet restarts while ContainerCreating

### ISSUE THREAD

**Issue by Cynerva** [kubernetes/kubernetes#48510]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I had a couple pods end up with no IP after a restart of kubelet. With no network, they're not able to function properly.

```
$ kubectl get po -n kube-system heapster-v1.4.0-2334915603-qzq18 -o wide
NAME                               READY     STATUS    RESTARTS   AGE       IP        NODE
heapster-v1.4.0-2334915603-qzq18   4/4       Running   29         2h        <none>    ip-172-31-28-248
```

This message from kubelet logs is spammed indefinitely:
```
W0705 18:17:32.236607   15544 docker_sandbox.go:342] failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod "heapster-v1.4.0-2334915603-qzq18_kube-system": Unexpected command output Device "eth0" does not exist.
W0705 18:17:33.294672   15544 docker_sandbox.go:342] failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod "heapster-v1.4.0-2334915603-qzq18_kube-system": Unexpected command output Device "eth0" does not exist.
...
```

**What you expected to happen**:

The pods should get IPs assigned to them.

**How to reproduce it (as minimally and precisely as possible)**:

This seems to occur occasionally when kubelet is restarted during pod creation:

1. Set up a Kubernetes cluster with CNI and flannel
2. Create a simple pod, e.g. ubuntu or busybox
3. As soon as the pod enters ContainerCreating state, restart kubelet
4. Wait for pod to come up, check IP with `kubectl get po -o wide`

About 50% of the time for me, the pod will come up with no IP and stay that way.

**Anything else we need to know?**:

User can work around this by recreating the pods.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.0
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.4.0-1020-aws
- Install tools: Juju
- Others:

**Comment by Cynerva** [comment]
@kubernetes/sig-network-bugs Could y'all take a look at this? Not sure if you're the right folks to tag, bit of a guess on my part. Thanks!

**Comment by caseydavenport** [comment]
I've managed to re-create this and I'm looking into the cause.

Looks like, at least in my repro scenario, the kubelet restart occurs at such a time that the CNI plugin execution isn't occurring and thus is leaving the pod sandbox without networking configured.

When the kubelet starts back up it tries to sync the pod, notices that that sandbox container already exists, and thus skips CNI execution this time around.

Currently looking for the right fix - would be nice if we could tell if the network was properly set up as part of checking if the pod sandbox has changed, and trigger a re-creation if so.

**Comment by caseydavenport** [comment]
Hacked up a tentative fix here: https://github.com/kubernetes/kubernetes/pull/48970

Haven't been able to repro yet.

**Comment by thockin** [comment]
@yujuhong FYI

**Comment by caseydavenport** [comment]
This didn't make it into v1.8.

I'd appreciate reviews on #48970 - still looking for input into whether that's the right approach.

**Comment by rkamudhan** [comment]
I seen this scenario in our DPDK pods many times, I will check the fix in our set up..

**Comment by dims** [comment]
Since this is a bug, i have requested the release team to mark the PR #48970 as milestone v1.8 too.

**Comment by dchen1107** [comment]
@dims,  I raised my concern at #48970, but ok with it as a temporary fix. Marked it for v1.8. Thanks!

**Comment by caseydavenport** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/48970 - thanks all.

/close

**Comment by lwhibernate** [comment]
+       // Needs to create a new sandbox when the sandbox does not have an IP address.
+       if !kubecontainer.IsHostNetworkPod(pod) && sandboxStatus.Network.Ip == "" {
+               glog.V(2).Infof("Sandbox for pod %q has no IP address.  Need to start a new one", format.Pod(pod))
+               return true, sandboxStatus.Metadata.Attempt + 1, sandboxStatus.Id
+       }

Is there a case that sandboxStatus.Network is nil pointer?

Thanks

Wei
