### ISSUE TITLE
Add support for Google Cloud KMS as encryption provider for encryption at rest

### ISSUE THREAD

**Issue by sakshamsharma** [kubernetes/kubernetes#48522]
Google Cloud KMS should be available as an encryption provider using envelope encryption (KEK-DEK).

Documents on this feature:
[A Plan For Kubernetes Secrets](https://docs.google.com/document/d/1JAwPuZg47UhfRVlof-lMw08OJztunW8pvTNxDK3rCF8/edit)
[Encryption of secrets at the database layer](https://github.com/kubernetes/community/pull/607/files)
[Implementing KMS plugins](https://docs.google.com/document/d/19SbqLrSC_MpmxbLCxasubRJLaZxgqfw1KeIwg3fHHLU/edit?usp=sharing)

/kind feature

**Comment by ericchiang** [comment]
Similar to https://github.com/kubernetes/kubernetes/issues/52916

Support for a gRPC-based KMS integration point will be alpha in 1.10.

Feature issue: kubernetes/features#460
Docs: kubernetes/website#7479

Closing since the ability to integrate with Google Cloud KMS merged.

/close
