### ISSUE TITLE
CrashLoopBack error does not go to pod/container log

### ISSUE THREAD

**Issue by bamb00** [kubernetes/kubernetes#48520]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug
> @kubernetes/sig-log

**What happened**:
CrashLoopBackOff occurs but does not get write to log and fluentd unable to collect
**What you expected to happen**:
Occurrences of the error "CrashLoopBackOff" should write to the Pod log even if the container did not receive the message/event.  This would allow user to identified which nodes where the pod is residing experiencing the "CrashLoopBackOff" occurrence.
**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy Fluentd daemonset
2. Deploy a pod that write a message to "terminationMessagePath" then exits after 10 sec
3. Verify the pod exits and then restarts with the "CrashLoopBackOff" from the UI
4. Kibana display the pod info but does not display the value "CrashLoopbackOff"
**Anything else we need to know?**:
5. Run the command "kubectl get pod pod_name -o=yaml" to get the container status last state and current state.  It will show the "CrashLoopBackOff"
**Environment**:
- Kubernetes version (use `kubectl version`): 1.5.4
- Cloud provider or hardware configuration**:  vSphere
- OS (e.g. from /etc/os-release):  CentOS 7.3
- Kernel (e.g. `uname -a`): 3.10
- Install tools:
- Others:

       containerStatuses:
       - containerID: docker://534f09bafe227d1f60eab13f533c623ae66ec92b870d77249745e2b4d1c79773
         image: debian
         imageID: docker-pullable://docker.io/debian@sha256:
                      7d067f77d2ae5a23fe6920f8fbc2936c4b0d417e9d01b26372561860750815f0
         lastState:
            terminated:
              containerID: docker:
                          //534f09bafe227d1f60eab13f533c623ae66ec92b870d77249745e2b4d1c79773
              exitCode: 0
              finishedAt: 2017-07-05T23:17:03Z
              message: |
                   Sleep expired
              reason: Completed
              startedAt: 2017-07-05T23:16:03Z
           name: dt-msg-path-demo-container
           ready: false
           restartCount: 10
           state:
              waiting:
                 message: Back-off 5m0s restarting failed container=dt-msg-path-demo-container
                          pod=dt-msg-path-demo_default(be6d744e-61d2-11e7-90f0-00505691b7ad)
                 reason: CrashLoopBackOff

**Comment by bamb00** [comment]
sig/log

**Comment by divyenpatel** [comment]
can you provide YAML file for deploying this pod.

cc: @luomiao @BaluDontu @tusharnt

**Comment by bamb00** [comment]
apiVersion: v1
kind: Pod
metadata:
  name: dt-msg-path-demo
spec:
  containers:
  - name: dt-msg-path-demo-container
    image: debian
    command: ["/bin/sh"]
    args: ["-c", "sleep 60 && echo Sleep expired > /var/log/containers/dt.log"]
    terminationMessagePath: "/var/log/containers/dt.log"

**Comment by crassirostris** [comment]
@bamb00 There are two separate problems that can be happening:

- kubelet doesn't write logs about this event, you can check it by filtering kubelet logs manually while on the node (using `journalctf -u kubelet`)
- fluentd doesn't pick up the logs, you can check fluentd pod's logs for any signs of problems

**Comment by bamb00** [comment]
@crassirostris Kubelet does not write this event...Is this by design, known issue, future feature? Also, where is the kubelet log path and can fluentd collect the log from kubelet?

Thanks.

**Comment by crassirostris** [comment]
@bamb00 Configurations of fluentd, present in this repo (e.g. [fluentd-gcp](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-configmap.yaml)) already export kubelet logs, including ones in journald. Where those logs are depends on the OS, on COS, these logs are in journald under unit `kubelet`, on ubuntu AFAIR under /var/log/kubelet.log.

You can also export Kubernetes events with this information, like [event-exporter](https://github.com/kubernetes/contrib/tree/master/fluentd/event-exporter) for Stackdriver does.

**Comment by bamb00** [comment]
From this link https://kubernetes.io/docs/tasks/debug-application-cluster/debug-cluster/ 
the kubelet.log should be in /var/log/kubelet.log.  I'm running CentOS 7.3.

**Comment by bamb00** [comment]
Fluentd needs the path to the kubelet log file.  Looks like kubelet.log file is located in /var/log for Ubuntu and CentOS does not.  Can I explicitly set kubelet.log to a path like /var/log/ in CentOS?

**Comment by crassirostris** [comment]
@bamb00 Sure, it's not controlled by Kubernetes or kubelet though, it's part of the deployment. For example, if you're using init scripts, just fix the init script for kubelet. If you're using systemd, then logs are in journald, but you can change that probably in the unit file. And so on.

**Comment by raffian** [comment]
Can't find `/var/log/kubelet.log` on Openshift 3.6, RHEL 7.3, does it go by a another name or is located in a  different location?

**Comment by crassirostris** [comment]
@raffian Try `journalctl -u kubelet`

**Comment by raffian** [comment]
@crassirostris  I could not find any journals using the command you supplied, but no worries, we got it from `var/log/messages`,

**Comment by DeadZen** [comment]
This issue is not even remotely close to solved
