### ISSUE TITLE
Align GroupName in pkg/apis

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#48527]
**Is this a BUG REPORT or FEATURE REQUEST?**:
enhancement/cleanup

/kind bug
/sig api-machinery

**What happened**:
In `pkg/apis`, there're 3 types of GroupName: `xxx`, `xxx.k8s.io`, `xxx.kubernetes.io`. Should we align them to `xxx.k8s.io`?

@kubernetes/sig-api-machinery-misc

**Comment by sttts** [comment]
These determine the HTTP path. So we cannot fix our broken naming easily.

**Comment by k82cn** [comment]
yes. Agree that's complex; I try to create a PR today; but I found lots of code are using text, e.g. "apps".

**Comment by sttts** [comment]
It break the api, that's the bigger problem.

**Comment by deads2k** [comment]
I think we should align them (we chose `k8s.io`) and it can be done by double registering for some period of time.

**Comment by k82cn** [comment]
I think this's not urgent issue. If we agree to do that, I may contribute after 1.8.

cc/ @smarterclayton

**Comment by lavalamp** [comment]
We cannot fix this for existing APIs easily. We mandate *.k8s.io for new APIs.

**Comment by k82cn** [comment]
ok; so we can close this issue I think :).

----
Da (Klaus), Ma (马达) | PMP® | Software Architect, IBM Cloud private
Development
IBM Spectrum Computing, IBM System
+86-10-8245 4084 | klaus1982.cn@gmail.com | http://k82.me
