### ISSUE TITLE
GCE: Config's network name ignored when it's not a url

### ISSUE THREAD

**Issue by nicksardo** [kubernetes/kubernetes#48521]
#47881 broke support for specifying network name.

**Comment by lavalamp** [comment]
This seems to be responsible for the bloodbath here: http://k8s-testgrid.appspot.com/google-gke#gke&width=20

Since this has been broken for a while we're just going to roll forward-- Nick already has a PR out.

**Comment by nicksardo** [comment]
@bowei @lavalamp 

On second thought, I believe I'm swapping one issue for another. My PR fixes the network's name, but may be breaking the network's project ID for GKE tests.

**Currently:**
The compute project ID is used as the network project. This is used for generating network and subnetwork URLS. 

**PR's Behavior**
With the introduction of shared networks, the cloudprovider should get the network project via configuration. If not specified, it'll look at the local network metadata to determine which network project the local VM is using. This makes sense for unmanaged K8s clusters on XPN. However, on GKE, the master is not running on the same network as the cluster; therefore, the configuration value is needed. Plumbing the network project via environment variable has not yet merged upstream.

After this PR merges, I'll submit another PR that uses the compute project ID instead of metadata as default. I'll revert this default behavior after several weeks when the GKE dependency is active.
