### ISSUE TITLE
Test image dependencies from kubernetes/kubernetes.github.io repo

### ISSUE THREAD

**Issue by mkumatag** [kubernetes/kubernetes#48530]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
Part of conformance test following images are used in `test/e2e` which needs to be ported to support multi architecture

1. gcr.io/google_containers/liveness:e2e	- https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/liveness/image/Dockerfile
2. gcr.io/google_containers/update-demo:nautilus - https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/update-demo/images/nautilus/Dockerfile
3. gcr.io/google_containers/update-demo:kitten - https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/update-demo/images/kitten/Dockerfile

As most of the test images are under `test/images` which is easy to maintain. I'm in dilemma to move these images here or keep it in the doc repo only and port them to support multiarchitecture?

I'm looking for suggestions here from broader team!

**Comment by luxas** [comment]
Feel free to move these over here.
They aren't used anymore in the docs repo, I checked that now.

What is used by core e2e/conformance tests should be in the core repo until we move the full `test/` out

Side note, there probably is some other images that are unused as well:
```
$ find . -type f -print | grep Dockerfile
./docs/user-guide/horizontal-pod-autoscaling/image/Dockerfile
./docs/user-guide/environment-guide/containers/show/Dockerfile
./docs/user-guide/environment-guide/containers/backend/Dockerfile
./docs/user-guide/jobs/work-queue-2/Dockerfile
./docs/user-guide/jobs/work-queue-1/Dockerfile
./docs/user-guide/update-demo/images/kitten/Dockerfile
./docs/user-guide/update-demo/images/nautilus/Dockerfile
./docs/user-guide/liveness/image/Dockerfile
./docs/tasks/job/fine-parallel-processing-work-queue/Dockerfile
./docs/tasks/job/coarse-parallel-processing-work-queue/Dockerfile
./docs/tasks/access-application-cluster/hello/Dockerfile
./docs/tasks/access-application-cluster/frontend/Dockerfile
./docs/tutorials/stateless-application/Dockerfile
./docs/tutorials/stateful-application/Dockerfile
./staging-container/Dockerfile
```
But as long as they are not used in core, no reason to move over.

**Comment by mkumatag** [comment]
but I see in docs they are using the `liveness` image in docs : https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

**Comment by luxas** [comment]
yes, there is that one reference, but that's no reason not to move.
That one reference will still be valid after the move, it don't require _the source to be there_
