### ISSUE TITLE
List only accessible namespaces

### ISSUE THREAD

**Issue by liubog2008** [kubernetes/kubernetes#48537]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

**What happened**:

Now RBAC can only enable or disable request to LIST namespaces.

**What you expected to happen**:
 
I hope to LIST partial namespaces in which I can access namespaced resource. Or I can LIST only "gettable" namespaces.

**Environment**:
- Kubernetes version v1.6

**Comment by liggitt** [comment]
an ACL-filtered list API is a very different type of API from traditional Kubernetes APIs. It has implications on resource version and watch (neither can be supported in a way that works well with existing list/watch informers)

an example of what this could look like is available as an extension API server at https://github.com/openshift/kube-projects that surfaces a new resource (`projects.project.openshift.io`) that maps 1:1 to kubernetes namespaces, and whose list operation returns only the namespaces you have the ability to `get`

**Comment by liubog2008** [comment]
Thanks very very much, that's what I want. @liggitt
