### ISSUE TITLE
How to release the Retain PersistentVolumes

### ISSUE THREAD

**Issue by guillelb** [kubernetes/kubernetes#48554]
Using k8s v1.6.1.

I created PVs with reclaimpolicy: Retain. In the k8s doc sais "Retain – manual reclamation"

Once, I used it by a PVC, and PVCs are deleted, I want to release the volumes, but volumes are still "Bound"

**PVs**
```
kubectl get pv
NAME      CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                                 STORAGECLASS   REASON    AGE
pv0       1Gi        RWX           Retain          Bound     default/pvc1   anything                 6d
pv3       1Gi        RWO           Retain          Bound     default/pvc2   anything                 1h
pv4       1Gi        RWO           Retain          Bound     default/pvc3   anything                 1h
```

How can I release the volumes, and put in Available state again?

**Comment by mtanino** [comment]
I think if the Pods and PVCs are deleted without any problem, the STATUS of PVs will be changed to "Released" automatically.

Did you see any problem on your kubelet log?

**Comment by msau42** [comment]
The docs have been updated with steps on how to manually reclaim a volume:
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaiming

**Comment by mtanino** [comment]
@guillelb @msau42 
Do you still have a problem that the volume doesn't become "Released" status?
```
Once, I used it by a PVC, and PVCs are deleted, I want to release the volumes, but volumes are still "Bound"
```
If the volume became "Released", you can reclaim it with above steps.

**Comment by msau42** [comment]
Please follow the steps to reclaim a volume in the documentation, and reopen if you see an issue.

/close
