### ISSUE TITLE
Move ReplicaSet and DaemonSet to apps API group

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#48558]
TODOs:
- [ ] DaemonSet moved to apps group 
- [ ] ReplicaSet moved to apps group 

@kubernetes/sig-apps-feature-requests

**Comment by smarterclayton** [comment]
Are we going to bump the API version as was requested (after the fact) for deployments?

**Comment by janetkuo** [comment]
@smarterclayton #48746 bumps deployments to apps/v1beta2.

Closing this in favor of umbrella issue #49135
