### ISSUE TITLE
Reserving a service IP for custom use / apiserver HA

### ISSUE THREAD

**Issue by gg7** [kubernetes/kubernetes#48563]
/kind feature

I currently use multiple `A` DNS records for my canonical apiserver address in order to provide some kind of fault-tolerance if a master goes down in my on-premise Kubernetes deployment:

```
;; ANSWER SECTION:
master.cluster1.k8s.local.       60      IN      A       10.0.1.1
master.cluster1.k8s.local.       60      IN      A       10.0.2.1
master.cluster1.k8s.local.       60      IN      A       10.0.3.1
```

This works most of the time, but if a master dies sometimes various `kubelet`s fail to report node statuses multiple times and Kubernetes starts rescheduling pods. If kubelet and kube-proxy are supposed to handle multiple A records more intelligently than trying to connect to `api_servers[rand() % len(api_servers)]` please let me know, as I don't think this is working (I'm running v1.6.6).

I could monitor all apiservers and update DNS automatically, but that's non-trivial. As far as I know I have these other options:

1. Deploy a load balancer and make that highly-available. I dislike this as this is yet another thing to maintain.
2. Run pacemaker/keepalived on the Kubernetes masters and use a virtual IP for the apiserver address.
3. Use a routing protocol like OSPF/BGP to advertise a virtual IP for the apiservers. Routers can then either pick one of the apiservers or use equal-cost multi-path routing (ECMP) to provide basic load-balancing.

Options 2 and 3 mean that I have to define a routable virtual IP address. I already advertise (and route) the service range (`--service-cluster-ip-range`) of my clusters and ideally I'd like to reserve a /32 in there for the apiservers. I could define a new subnet, but why complicate my routing? All I need is a single IP address.

AFAIK I could define a headless service with a port that I won't use and then use its virtual IP address together with custom `iptables` rules, but that sounds like a horrible hack. What if in a future release kube-proxy starts inserting `<IP address>:*` iptables rules instead of the `<IP address>:<port>` rules?

Questions:

* Is there an easy way for me to reserve a certain IP address in the ClusterIP range so that it won't be handled by kube-proxy at all? If not, is this a feature worth implementing?
* Is the headless service hack acceptable?
* Should I investigate alternative HA methods for the apiservers?

/area admin 
/area HA
/area kube-proxy 
/sig cluster-lifecycle
/sig cluster-ops 
/sig network 
@sig-cluster-lifecycle-misc

**Comment by bboreham** [comment]
Today I find I have a similar question.  @gg7 did you find a resolution?
