### ISSUE TITLE
Addon manager should support addons switching between mode=Reconcile and mode=EnsureExists without modifying the addon manifest

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#48569]
/kind feature

Cluster add-ons should support switching between `addonmanager.kubernetes.io/mode=Reconcile` and `addonmanager.kubernetes.io/mode=EnsureExists` by updating the addon definition via kubernetes API.

Current addons like dashboard, fluentd agent and kube-dns specify `addonmanager.kubernetes.io/mode=Reconcile` in their manifest files. This effectively means they cannot be updated without updating the manifest file, which is a poor experience. I'm not sure whether the solution is having them all default to `addonmanager.kubernetes.io/mode=EnsureExists`, but it should be possible to switch between the modes by simply updating the addon's config, e.g. with `kubectl edit`.

**Comment by jlowdermilk** [comment]
cc @mikedanese

**Comment by Kamshak** [comment]
@mikedanese just pinging :) Would love to have this feature

**Comment by oliveiracdz** [comment]
Hi, everyone!

Any workaround?

Tks!
