### ISSUE TITLE
Advanced Auditing Beta Changes

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#48561]
As we work with the new "advanced auditing" API, we're noticing places where the API could be improved. I'm opening this issue to track all the changes we'd like to make to the API when it goes to beta.

## API Changes:

- [x] `audit.Event.ObjectRef.APIVersion` currently holds both the the API group and version, separated by a `/`. We should break these out into separate fields.
- [x] Policy should be able to specify subresources. This could either be a separate field, or allow matching of `/` delimited resources (e.g. `pods/status` for the pods resource and status subresource)
- [x] ( @ericchiang ) It would be useful to be able to specify resource names in the policy. E.g. [ingress controller configmap](https://github.com/kubernetes/kubernetes/blob/14cd03aed64b3a442af51e5fac4ab9aafafb0e1f/cluster/gce/gci/configure-helper.sh#L526). `Resources` in the [`GroupResources`]
(https://github.com/kubernetes/kubernetes/blob/14cd03aed64b3a442af51e5fac4ab9aafafb0e1f/staging/src/k8s.io/apiserver/pkg/apis/audit/types.go#L198) struct should be changed to a struct that includes Resource + ResourceNames (slice) + (Subresource)
- [x] `audit.Event.Metadata.CreationTimestamp` shows up as null in the json serialized events we output, which looks sloppy. We should consider cleaning this up. One possibility is to get rid of the `audit.Event.Timestamp` field, and use CreationTimestamp.
- [x] We want to omit the RequestReceived stage in GKE. The policy may be the right place to specify that.

## Other Changes:

- [x] feature gate `AdvancedAuditing` moves to beta and defaults to enabled

## Postponed to post 1.8.0

- [ ] It would be nice to identify the server that sent the audit event, i.e. the aggregator vs. an end-user apiserver. Implementation TBD.

/cc @sttts @soltysh @ericchiang @ihmccreery 

Feature: kubernetes/features#22

**Comment by CaoShuFeng** [comment]
I am very glad to implement the first one if no one has started it.
> audit.Event.ObjectRef.APIVersion currently holds both the the API group and version, separated by a /. We should break these out into separate fields.

**Comment by tallclair** [comment]
Note that the first one is a breaking change, since it would mean we populate the `APIVersion` differently. I think it should be done in the transition to the Beta API, rather than an augment to the alpha API.

**Comment by lavalamp** [comment]
Please note that SIG API doesn't own the *contents* of apis and we don't need to own issues like this one.

**Comment by ericchiang** [comment]
I think the GKE audit policy really demonstrated how many edge cases there are when composing an audit policy. Don't capture the request body of TokenSubjectReview, ignore kube-proxy watching endpoints, etc.

It'd be great to formalize that knowledge somehow. Either by creating a default audit policy in the API server (like default RBAC roles), or by having a real example audit policy in documentation.

**Comment by CaoShuFeng** [comment]
>Note that the first one is a breaking change, since it would mean we populate the APIVersion differently. I think it should be done in the transition to the Beta API, rather than an augment to the alpha API.

Thanks for pointing it out!

**Comment by tallclair** [comment]
I think we should consider adding user agent to the audit user info. I know it can be spoofed trivially, but we've had a couple people ask for it.

**Comment by CaoShuFeng** [comment]
Hi, can we implement a feature that support reading audits by kubectl or [dashborad](https://github.com/kubernetes/dashboard)?
I think this is a common use case.
What's your opinion?

**Comment by tallclair** [comment]
I think audit logs should be exposed similarly to other master/apiserver logs. I'm hesitant to build a custom audit log solution.

**Comment by sttts** [comment]
Making them available via kube-apiserver doesn't sound right. Nothing stops you though from creating a custom read-only audit-event-apiserver which preferably is backed by an independent storage (maybe not even etcd) and hook that into the cluster with apiserver aggregation. Of course, use the audit webhook to feed the events into audit-event-apiserver.

**Comment by tallclair** [comment]
Copying from https://github.com/kubernetes/kubernetes/pull/46592#issuecomment-316553044, with regards to omitting ReqeustRecieved stage from the batched webhook output:

> My priority is just to reduce the number of events that are sent by the webhook, so an alternative would be to do some deduplication in the webhook. One way of doing so would be to put the early stages in a sort of "TTL Cache" which holds the latest stage of the event. If the ResponseComplete stage is logged, then that event is removed from the cache and added to the queue as with today. If an event is evicted from the cache (either due to size or TTL expiration), then the latest stage is added to the queue. The end result should be that most requests just send a ResponseComplete event, but requests that take an unusually long time to complete are guaranteed to be sent within X seconds (60?) of the request start time. (Obviously this would only be for the batching mode).

I think we should pursue this option before adding more configuration to the policy, but open for discussion.

**Comment by ericchiang** [comment]
I like the batching webhook mode doing de-duplication. It's a nice middle ground between sending less events and adding even more configuration to omit stages. It also provides a sane default option.

Looking at https://github.com/kubernetes/kubernetes/pull/46897, it already takes a lot of prior knowledge to write these policy files. I think that's a strong argument for not making the policy more complex.

**Comment by crassirostris** [comment]
@sttts @ericchiang @CaoShuFeng 

We recently discussed the issue of omitting stages with @tallclair and here are some thoughts:

- Sometimes having this stage can actually be useful, e.g. to detect a query of death -- a request without a response
- This logic is useful not only with the batching webhook, it's even more useful with e.g. blocking webhook

Also I personally think that the logic with omitStages is cleaner and easier to maintain and explain to users

**Comment by tallclair** [comment]
Yeah, I wasn't thinking about the blocking use case. I'm OK with keeping `omitStages` for that reason, although I'd be interested in any suggestions to improve on the API...

**Comment by sttts** [comment]
Which compatibility guarantees do we give for outward apis? For the alpha I guess we can just switch and call every webhook with v1beta1 objects. But when v1 is arriving, we probably need a better story. Do we want to negotiate via HTTP headers? Do we want a config option?

**Comment by ericchiang** [comment]
@sttts we've had issues with this for our existing webhooks, how to migrate them from v1beta1 to v1. @liggitt had some thoughts about this.

**Comment by tallclair** [comment]
If the API doesn't change going from v1beta1 to v1 (or there are only additions), I think it should be a non-issue. If it does change, maybe we should consider making it configurable?

**Comment by liggitt** [comment]
> If the API doesn't change going from v1beta1 to v1 (or there are only additions), I think it should be a non-issue. 

I hope it's an issue or all the webhooks would be assuming identical semantics, and not honoring the sent version, which will cause problems if you expect the versioning mechanism to allow you to make changes

**Comment by liggitt** [comment]
For the authn/authz webhooks, I'm considering using the preferredVersion field in the webhook kubeconfig to allow people to opt in to v1 now, announce the default will change to v1 in a future release, and when it does, allow people to stay on v1beta1 by explicitly specifying that in their webhook kubeconfig

**Comment by CaoShuFeng** [comment]
Hi, does some one has interest about this pr:
https://github.com/kubernetes/kubernetes/pull/49377
I get this idea because openstack does the same thing.

**Comment by crassirostris** [comment]
I like preferredVersion better than negotiation headers because it's easier and more explicit

By the way, @sttts noticed that there's inconsistency between the changes. https://github.com/kubernetes/kubernetes/issues/49115 upgrades the API to beta and then changes the beta version, whereas https://github.com/kubernetes/kubernetes/pull/48836 changes the alpha version directly. Should we maybe split https://github.com/kubernetes/kubernetes/pull/49115 into two commits: one upgrading the API version and another introducing the changes? Then https://github.com/kubernetes/kubernetes/pull/48836 can follow the first PR and change the beta API directly

We can also try to use preferredVersion in this release, to switch from alpha to beta. Since we don't need to support alpha, we will make beta default, but at least the mechanism will be in place for beta -> v1 change later.

**Comment by tallclair** [comment]
+1 for splitting #49115 into 2 changes. RE: #48836 - I think it's OK to add fields to the alpha API, just not change or remove fields (or field semantics).

**Comment by crassirostris** [comment]
>  It would be nice to identify the server that sent the audit event, i.e. the aggregator vs. an end-user apiserver. Implementation TBD.

@timstclair Is it a blocker for beta? Can it be later added to the GA version if needed? IIUC, it can be implemented right now by adding a parameter to the webhook address and process this parameter later in the pipeline

**Comment by tallclair** [comment]
Definitely not a blocker. It's (relatively) easy to add information to the API. We just want to make sure that the information we currently have is in the right state before going to beta / GA.

**Comment by tallclair** [comment]
RE: Metadata.CreationTimestamp
Perhaps we should just reevaluate whether the metadata is necessary in the first place, since we're not using any of the fields?
xref: https://github.com/kubernetes/kubernetes/pull/49656

**Comment by crassirostris** [comment]
+1 to https://github.com/kubernetes/kubernetes/pull/49656#issuecomment-319888254, I'll be happy to see it go and have two separate timestamps

FYI @CaoShuFeng

**Comment by crassirostris** [comment]
> Definitely not a blocker. It's (relatively) easy to add information to the API. We just want to make sure that the information we currently have is in the right state before going to beta / GA.

Sounds good. I spun up a separate issue for the discussion: https://github.com/kubernetes/kubernetes/issues/50076

**Comment by ericchiang** [comment]
>  feature gate AdvancedAuditing moves to beta and defaults to enabled

Bit late but I don't think we can do this. Turning the AdvancedAuditing feature gate on by default changes the behavior of the existing audit log flags. E.g. it starts outputting JSON instead of the existing scheme.

**Comment by CaoShuFeng** [comment]
> Turning the AdvancedAuditing feature gate on by default changes the behavior of the existing audit log flags. 
Yes, you are right.

We should never turn this feature on?
Or this change will break some tests again like https://github.com/kubernetes/kubernetes/issues/51556, so we should turn the gate on and update some test at the same time?

**Comment by ericchiang** [comment]
> We should never turn this feature on?

Maybe we let users opt into this through `--audit-log-format`?

e.g. if you supply `--audit-log-format=legacy`, which we make the default again, you get the old audit log implementation. If you supply `--audit-log-format=json` you get the new implementation.

Don't know how cleanly that would interact with `--audit-policy-file`.

> Or this change will break some tests again like #51556, so we should turn the gate on and update some test at the same time?

Don't have a good answer there. We'd probably just update the e2e tests to use the `--audit-log-format=json` flag.

@sttts @crassirostris @soltysh any thoughts here? I'd like to see a PR soon that formally bumps the feature flag to beta, but I think we have to address this first.

**Comment by CaoShuFeng** [comment]
> Don't know how cleanly that would interact with --audit-policy-file.

With current implementation, if user doesn't pass --audit-policy-file to kube-apiserver, nothing will be recorded.

**Comment by CaoShuFeng** [comment]
> Maybe we let users opt into this through --audit-log-format?

This option is not a switch between Lagacy audit/Advanced audit.
This option is used for the format of Advanced audit. 
I known this --audit-log-format hasn't been released yet, but it has been merged for 2 months, can we change it's behavior now?

**Comment by crassirostris** [comment]
> @sttts @crassirostris @soltysh any thoughts here? I'd like to see a PR soon that formally bumps the feature flag to beta, but I think we have to address this first.

Wait, hasn't https://github.com/kubernetes/kubernetes/pull/51943 already done this?

**Comment by crassirostris** [comment]
The way I see it, you can still enable basic auth by disabling advanced audit logging, so it's not a problem. @CaoShuFeng even added this to the documentation in https://github.com/kubernetes/kubernetes.github.io/pull/5300

**Comment by ericchiang** [comment]
> Wait, hasn't #51943 already done this?

Wasn't aware we already did this. I'll call it out explicitly in the release notes. https://github.com/kubernetes/features/blob/master/release-1.8/release_notes_draft.md#action-required-before-upgrading

**Comment by crassirostris** [comment]
@ericchiang Thanks!

**Comment by tallclair** [comment]
Good progress has been made on this, but the remaining issues aren't blockers. Moving to 1.9, but maybe we should consider this complete?

**Comment by crassirostris** [comment]
@tallclair Everything except for the discussion about api-aggregator (and/or federation?) is done, I think it makes sense to close this one and one a new one later

**Comment by crassirostris** [comment]
Thanks everyone for working on audit logging in 1.8!

Closing in favor of https://github.com/kubernetes/kubernetes/issues/54551
