### ISSUE TITLE
kubectl bash completion causes bash file path completion to fail

### ISSUE THREAD

**Issue by amitkgupta** [kubernetes/kubernetes#48575]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Bash file path completion fails when trying to run `kubectl` commands and `source /usr/local/etc/bash_completion.d/kubectl` is in `~/.bash_profile`.  If I run `kubectl delete -f ../<TAB>` then I get the error message show below in the section on reproduction.

**What you expected to happen**:

I espect to see files/directories that `../` can complete to.

**How to reproduce it (as minimally and precisely as possible)**:

```
Amits-MacBook-Pro:boku amitgupta$ cat ~/.bash_profile
### kubectl ###
source /usr/local/etc/bash_completion.d/kubectl
Amits-MacBook-Pro:boku amitgupta$ exec -l $SHELL
Amits-MacBook-Pro:boku amitgupta$ kubectl ../bash: __ltrim_colon_completions: command not found
```

I hit `<TAB>` after `kubectl ../`.

**Anything else we need to know?**:

This problem arises only with the `kubectl` command, not any others.

It arises no matter what I seem to put in after `kubectl`, even `kubectl <SPACE><TAB>` brings up the issue, doesn't have to be something like `kubectl delete -f ../<TAB>`.

The error message changes.  In the example above, it says `bash: __ltrim_colon_completions: command not found`, but sometimes it says `bash: _filedir: command not found` in the same place.  

When I remove `kubectl` Bash completions from my `~/.bash_profile` (and restart/re-login to the shell), the problem goes away.  These file completions came with my Homebrew installation of `kubectl`.

There is no difference between what Homebrew provided and what `kubectl completion bash` provides:

```
$ diff <(kubectl completion bash) /usr/local/etc/bash_completion.d/kubectl

```

**Environment**:
- Kubernetes version (use `kubectl version`):
  ```
  $ kubectl version
  Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-30T09:51:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration**: N/A
- OS (e.g. from /etc/os-release):
  ```
  $ sw_vers
  ProductName:	Mac OS X
  ProductVersion:	10.12.5
  BuildVersion:	16F2104
  ```
- Kernel (e.g. `uname -a`):
  ```
  $ uname -a
  Darwin Amits-MacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:13:31 PDT 2017; root:xnu-3789.60.24~4/RELEASE_X86_64 x86_64
  ```
- Install tools:
  ```
  $ brew --version
  Homebrew 1.2.4
  Homebrew/homebrew-core (git revision 36f1; last commit 2017-07-06)

  $ brew info --json=v1 kubectl | jq '.[0].name,.[0].installed[0].version' -r
  kubernetes-cli
  1.7.0
  ```
- Others:
  ```
  $ bash --version
  GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
  Copyright (C) 2007 Free Software Foundation, Inc.
  ```

**Comment by superbrothers** [comment]
You need to source bash-completion from either `/etc/bashrc` or `~/.bashrc`. See `kubectl completion -h` for more details.

```
$ kubectl completion -h
Output shell completion code for the specified shell (bash or zsh). The shell code must be evalutated to provide
interactive completion of kubectl commands.  This can be done by sourcing it from the .bash _profile. 

Note: this requires the bash-completion framework, which is not installed by default on Mac.  This can be installed by
using homebrew: 

  $ brew install bash-completion
  
Once installed, bash completion must be evaluated.  This can be done by adding the following line to the .bash profile 

  $ source $(brew --prefix)/etc/bash_completion
  
Note for zsh users: [1] zsh completions are only supported in versions of zsh >= 5.2

Examples:
  # Install bash completion on a Mac using homebrew
  brew install bash-completion
  printf "
  # Bash completion support
  source $(brew --prefix)/etc/bash_completion
  " >> $HOME/.bash_profile
  source $HOME/.bash_profile
  
  # Load the kubectl completion code for bash into the current shell
  source <(kubectl completion bash)
  
  # Write bash completion code to a file and source if from .bash_profile
  kubectl completion bash > ~/.kube/completion.bash.inc
  printf "
  # Kubectl shell completion
  source '$HOME/.kube/completion.bash.inc'
  " >> $HOME/.bash_profile
  source $HOME/.bash_profile
  
  # Load the kubectl completion code for zsh[1] into the current shell
  source <(kubectl completion zsh)

Usage:
  kubectl completion SHELL [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).
```

**Comment by Amit-PivotalLabs** [comment]
I stated in my issue that I sourced bash completion in my `~/.bash_profile`.  You (@superbrothers) stated that I need to source it from either `/etc/bashrc` or `~/.bashrc`, and then point to the help output which **does not** say anything about `bashrc` and in fact explicitly says to do what I'm already doing, which is to use `.bash_profile`.

@cblecker could you please re-open this issue?

**Comment by cblecker** [comment]
@Amit-PivotalLabs Is this still an issue with the latest version of kubectl? Can you provide fresh outputs, as well as the versions of kubectl, and bash? Can you also run a `brew upgrade` to ensure you have the latest version of bash_completion?

**Comment by Amit-PivotalLabs** [comment]
Sure.  On the first line below, I'm doing `kubectl<SPACE><TAB>` and you can see the output I'm getting.

```
$ kubectl  -bash: __ltrim_colon_completions: command not found

$ kubectl version -c
Flag shorthand -c has been deprecated, please use --client instead.
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T21:07:53Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}

$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by Amit-PivotalLabs** [comment]
Think I figured it out, I missed the part in the Examples section of the `kubectl completion -h` output which says to `brew install bash-completion`.  The completion kind of works even without this, e.g. `kubectl ap<TAB>` gives:

```
$ kubectl apbash: __ltrim_colon_completions: command not found

api-versions  apply
```

**Comment by Amit-PivotalLabs** [comment]
I'm able to complete other things without installing `bash-completion`, e.g `brew i<TAB>` gives:

```
$ brew i
info     install  irb
```

so there's something I'm missing about how bash completion generally works, what additional stuff you get when you `brew install bash-completion`, and how `kubectl` uses that additional stuff, but for the purposes of this issue I don't have any further questions.

**Comment by cblecker** [comment]
@Amit-PivotalLabs I'm glad you were able to figure it out!

**Comment by simonxy** [comment]
I had same problem on OSX with native bash:
```
$ kubectl  -bash: __ltrim_colon_completions: command not found
```
It seems like, the whole thing only works when:

- upgrade bash to ver. 4+, https://coderwall.com/p/dmuxma/upgrade-bash-on-your-mac-os
- install bash-complete@2 from brew, ```brew install bash-completion@2```
- run ```kubectl completion bash > ~/.kube/kubectl_autocompletion```, then source it in ```~/.bash_profile```
```
...

if [ -f /usr/local/share/bash-completion/bash_completion ]; then
  . /usr/local/share/bash-completion/bash_completion
fi

source ~/.kube/kubectl_autocompletion
```
above code snippet is what the final addition to my ~/.bash_profile

**Comment by andersonVSA** [comment]
I had the same in Manjaro ( archlinux ), in addition to @simonxy : 
`
pacman -S bash-completion
kubectl completion bash > ~/.kube/kubectl_autocompletion
`
add to .bashrc
`
if [ -f /usr/local/share/bash-completion/bash_completion ]; then
  . /usr/local/share/bash-completion/bash_completion
fi
source ~/.kube/kubectl_autocompletion
`
and run 
`
source .bashrc
`

**Comment by loganmzz** [comment]
I'm on Windows with MinGW. After digging into system directories, it seems `bash_completion` script which contains helper functions such as `_filedir` is missing.

I had to get files from Git repository at https://github.com/scop/bash-completion/blob/master/bash_completion to `/usr/share/bash-completion/bash_completion`

Then add following line at top on my `~/.bashrc`:

```bash
source /usr/share/bash-completion/bash_completion
```

**Comment by smbl64** [comment]
Btw, on macOS if you have upgraded your bash to 4+, make sure to change your shell via `chsh`. More info here:
https://apple.stackexchange.com/a/55998/273340

**Comment by subfuzion** [comment]
I realize this issue is closed, but in case this helps anyone ... 
**IF** you are using a mac
**AND** you are using tmux
**AND** you used homebrew to install bash and bash-completion@2
**THEN** test without tmux and if it works, make sure you also tell tmux to use the correct shell by putting this in your `.tmux.conf`:

    set-option -g default-shell "/usr/local/bin/bash"

Just reloading the config wasn't enough; I had to kill the running tmux server

    tmux kill-server

**Comment by ahoehma** [comment]
> I used this and it works:
> 
> 1. Create the folder and file:
>    mkdir ~/.bash_completion.d
>    vi ~/.bash_completion.d/kubectl
> 2. copy in the following to vi:
>    _kubectl()
>    {
>    local cur=${COMP_WORDS[COMP_CWORD]}
>    COMPREPLY=( $(compgen -W "$(kubectl get pods --no-headers --output=custom-columns=NAME:.metadata.name )" -- $cur) )
>    }
>    complete -F _kubectl kubectl
> 3. add the following to your .bash_profile and then reload it.
>    . ~/.bash_completion.d/kubectl

this doesn't do anything

**Comment by rcmonitor** [comment]
> I still have this bug :-(
> Any hint to fix this file-name-completion-bug?

Same thing here:
git + cmder + kubectl on windows
```
$ git --version
git version 2.45.2.windows.1
$ kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.2
WARNING: version difference between client (1.29) and server (1.27) exceeds the supported minor version skew of +/-1
$ choco list | grep Cmder
Cmder 1.3.24
```
The completion itself is working, but it inserts erroneous string in between like this:
```
kubectl apply -f depC:\tools\Cmder\vendor\conemu-maximus5\..\git-for-windows\usr\bin\bash: _filedir: command not found
loy_net_inspector.yaml
```
Changing `bash` used by task from `%ConEmuDir%\..\git-for-windows\usr\bin\bash.exe` to `c:\Program Files\Git\bin\bash.exe` didn't fix the error; just changed the output:
```
kubectl apply -f depbash: _filedir: command not found
loy_net_inspector.yaml
```


Got it fixed by directly editing completion.bash.inc file generated via
```
kubectl completion bash > .kube/completion.bash.inc
```
Changed 
```
        filteringCmd="_filedir $fullFilter"
        __kubectl_debug "File filtering command: $filteringCmd"
        $filteringCmd
```
to be:
```
        filteringCmd="_filedir $fullFilter"
        __kubectl_debug "File filtering command: $filteringCmd"
        $filteringCmd 2> /dev/null
```
Now everything works as expected:
```
kubectl apply -f deploy_net_inspector.yaml
```

Probably, this error suppression may be integrated into `kubectl completion` generation script based on some condition...

**Comment by loganmzz** [comment]
@rcmonitor @ahoehma See my comment: https://github.com/kubernetes/kubernetes/issues/48575#issuecomment-456416305

**Comment by rcmonitor** [comment]
> @rcmonitor @ahoehma See my comment: [#48575 (comment)](https://github.com/kubernetes/kubernetes/issues/48575#issuecomment-456416305)

Thx for quick reply

Just tried this solution.
Unfortunately, didn't work for me.
Got back to my workaround.

**Comment by loganmzz** [comment]
> > @rcmonitor @ahoehma See my comment: [#48575 (comment)](https://github.com/kubernetes/kubernetes/issues/48575#issuecomment-456416305)
> 
> Thx for quick reply
> 
> Just tried this solution. Unfortunately, didn't work for me. Got back to my workaround.

Just looked at linked script, seems things have changed since my comment. The faulty function is missing, but found reference in sibling `bash_completion.d` directory. Don't know how to fix/update bash_completion installation in MinGW. May be better to open issue in MinGW to solve this issue. As it may be encountered with other Bash completions.

**Comment by hatsuyuki15** [comment]
> > @rcmonitor @ahoehma See my comment: [#48575 (comment)](https://github.com/kubernetes/kubernetes/issues/48575#issuecomment-456416305)
> 
> Thx for quick reply
> 
> Just tried this solution. Unfortunately, didn't work for me. Got back to my workaround.

Try the script at [v2.11.0](https://github.com/scop/bash-completion/blob/v2.11.0/bash_completion)

**Comment by wu0407** [comment]
> sibling

download the https://github.com/scop/bash-completion/blob/main/bash_completion.d/000_bash_completion_compat.bash and save as /usr/share/bash-completion/000_bash_completion_compat.bash. 
add source line in ~/.bashrc
```
source /usr/share/bash-completion/bash_completion
source /usr/share/bash-completion/000_bash_completion_compat.bash
```
