### ISSUE TITLE
Cannot autoscale StatefulSet via kubectl

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#48591]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig cli

**What happened**:

I can create HPA policy for StatefulSet but cannot scale the StatefulSet via kubectl.

```
root@pc001:~/istio-0.1.6# kubectl autoscale statefulset mysql --cpu-percent=50 --min=1 --max=10
error: cannot autoscale a {apps StatefulSet}
```
**What you expected to happen**:

I should be able to scale the StatefulSet via kubectl.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by georgebuckerfield** [comment]
It looks like this isn't supported yet?
https://kubernetes.io/docs/user-guide/kubectl/v1.6/#autoscale

Related https://github.com/kubernetes/kubernetes/issues/44033

**Comment by gyliu513** [comment]
It's weird, the document already claim support https://kubernetes.io/docs/tasks/run-application/scale-stateful-set/

**Comment by georgebuckerfield** [comment]
AFAIK, scaling is a separate thing to autoscaling. You should be able to do:
```
kubectl scale statefulset mysql --replicas=5
```
But not: 
```
kubectl autoscale statefulset mysql ...
```

**Comment by gyliu513** [comment]
Ah, I see, thanks @georgebuckerfield

**Comment by kow3ns** [comment]
@gyliu513 This isn't a bug. Autoscaling isn't implemented for StatefulSets or DaemonSets.  Auto-scaling a stateless application based on cpu utilization generally makes sense. Autoscaling a stateful workload based on that criteria can often do more harm (at least in the short term) than good. If you are asking for an implementation of horizontal Pod auto-scaling for StatefulSet you should open this as a feature request.

**Comment by gyliu513** [comment]
Thanks @kow3ns , can you please explain more for why scale a statefulset often do more harm than good?

**Comment by kow3ns** [comment]
HPA based on CPU makes two assumptions.

1. CPU varies with direct proportion to QPS
1. QPS is load balanced, and when auto scaling occurs, the increased capacity of a new Pod will decrease the per Pod QPS, and therefore will decrease the per Pod CPU utilization.

Stateful workloads may violate .1. For example, log structured merge trees and append only btrees may cause CPU spikes during compaction that are only loosely correlated with QPS and that do not vary with direct proportion to the current QPS.

More importantly, for distributed storage applications, when you increase the number of processes in the system by increasing the number of Pods, you may trigger replication or replica re-balancing (depending on the nature of the stateful application). This is likely to increase network and CPU utilization in the short term. Only after the re-balance or replication is complete would you be able to make use of the additional capacity offered by the new Pods. 

For synchronously and asynchronously replicated ACID systems, reducing the number or replicas based on CPU utilization might be safe, but, for BASE systems,  scaling down will also trigger a re-balance (so the systems data are not under-replicated), and potentially require global anti-entropy repair.

That isn't to say that Autoscaling is not possible, but it is not likely to have a trivial, general solution for StatefulSet. That is why I suggest opening this as a feature request.

**Comment by gyliu513** [comment]
Thanks @kow3ns for the detailed explanation, there is already a feature request https://github.com/kubernetes/kubernetes/issues/44033 , so I will close this one.

**Comment by YueHonghui** [comment]
@kow3ns  I think Statefulset can't meet the requirements of applications like database、distributed storage service or even spark. Those applications is too complicate to fit in statefulset. They should be manipulated by customized controller through CRD, like what so many Operators does.
We need a controller which provides persistent identifier for pods, so we can create reference between pods and other resource persistently. It is reasonable to provide ability of horizontally auto scaling for such types of applications.
