### ISSUE TITLE
kube-control-manager hanged by "attempting to acquire leader lease..." /sig controller-manager /sig bug

### ISSUE THREAD

**Issue by fogongzi** [kubernetes/kubernetes#48590]
/area [controller-manager]
/kind [bug]
**Is this a BUG REPORT or FEATURE REQUEST?:**

/kind bug
/area controller-manager 

I install kubernetes 1.7 on ubuntu 17.04. The master includes three nodes and owns high availability by etcd election. Only a node (10.71.156.238) with kube-control-manager looks good. The other two nodes(10.71.156.176,10.71.156.170) with kube-control-manager is always hangin with "attempting to acquire leader lease..." **and the logs are as follows:**
Jul 06 15:04:34 kube-master kube-controller-manager[18261]: I0706 15:04:34.943413   18261 flags.go:52] FLAG: --service-sync-period="5m0s"
Jul 06 15:04:34 kube-master kube-controller-manager[18261]: I0706 15:04:34.943422   18261 flags.go:52] FLAG: --stderrthreshold="2"
Jul 06 15:04:34 kube-master kube-controller-manager[18261]: I0706 15:04:34.943431   18261 flags.go:52] FLAG: --terminated-pod-gc-threshold="12500"
Jul 06 15:04:34 kube-master kube-controller-manager[18261]: I0706 15:04:34.943440   18261 flags.go:52] FLAG: --unhealthy-zone-threshold="0.55"
Jul 06 15:04:34 kube-master kube-controller-manager[18261]: I0706 15:04:34.943449   18261 flags.go:52] FLAG: --use-service-account-credentials="true"
Jul 06 15:04:34 kube-master kube-controller-manager[18261]: I0706 15:04:34.943456   18261 flags.go:52] FLAG: --v="0"
Jul 06 15:04:34 kube-master kube-controller-manager[18261]: I0706 15:04:34.943464   18261 flags.go:52] FLAG: --version="false"
Jul 06 15:04:34 kube-master kube-controller-manager[18261]: I0706 15:04:34.943480   18261 flags.go:52] FLAG: --vmodule=""
Jul 06 15:04:34 kube-master kube-controller-manager[18261]: I0706 15:04:34.943515   18261 controllermanager.go:107] Version: 1.7.0
Jul 06 15:04:34 kube-master kube-controller-manager[18261]: I0706 15:04:34.955717   18261 leaderelection.go:179] attempting to acquire leader lease...

**The node (10.71.156.238) with kube-control-manager of logs are as follows:**
Jul 07 16:09:36 kube-master-3 kube-controller-manager[14686]: W0707 16:09:36.250472   14686 reflector.go:323] k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72: watch of *v1beta1.Role ended with: very short watch
Jul 07 16:09:37 kube-master-3 kube-controller-manager[14686]: W0707 16:09:37.263226   14686 reflector.go:323] k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72: watch of *v1beta1.Role ended with: too old resource version: 968615 (968654)
Jul 07 16:09:47 kube-master-3 kube-controller-manager[14686]: W0707 16:09:47.095653   14686 reflector.go:323] k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72: watch of *v1.ServiceAccount ended with: very short watch
Jul 07 16:09:48 kube-master-3 kube-controller-manager[14686]: W0707 16:09:48.063006   14686 reflector.go:323] k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72: watch of *v1.PodTemplate ended with: very short watch
Jul 07 16:09:49 kube-master-3 kube-controller-manager[14686]: W0707 16:09:49.077683   14686 reflector.go:323] k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72: watch of *v1.PodTemplate ended with: too old resource version: 968615 (968654)
Jul 07 16:09:50 kube-master-3 kube-controller-manager[14686]: W0707 16:09:50.258290   14686 reflector.go:323] k8s.io/kubernetes/pkg/controller/bootstrap/bootstrapsigner.go:152: watch of *v1.Secret ended with: very short watch
Jul 07 16:09:53 kube-master-3 kube-controller-manager[14686]: W0707 16:09:53.925920   14686 reflector.go:323] k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72: watch of *v1beta1.StatefulSet ended with: very short watch
Jul 07 16:09:55 kube-master-3 kube-controller-manager[14686]: W0707 16:09:55.058561   14686 reflector.go:323] k8s.io/kubernetes/pkg/controller/bootstrap/bootstrapsigner.go:151: watch of *v1.ConfigMap ended with: very short watch
Jul 07 16:09:55 kube-master-3 kube-controller-manager[14686]: W0707 16:09:55.892659   14686 reflector.go:323] k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72: watch of *v1.Job ended with: very short watch
Jul 07 16:09:57 kube-master-3 kube-controller-manager[14686]: W0707 16:09:57.555309   14686 reflector.go:323] k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72: watch of *v1.ReplicationController ended with: very short watch.

**The etcd version is 3.2.0 and etcd logs are as follows:**
Jul 07 15:55:05 kube-master etcd[8661]: store.index: compact 2036684
Jul 07 15:55:05 kube-master etcd[8661]: finished scheduled compaction at 2036684 (took 2.643997ms)
Jul 07 16:00:05 kube-master etcd[8661]: store.index: compact 2037200
Jul 07 16:00:05 kube-master etcd[8661]: finished scheduled compaction at 2037200 (took 3.670872ms)
Jul 07 16:00:05 kube-master etcd[8661]: apply entries took too long [105.064338ms for 1 entries]
Jul 07 16:00:05 kube-master etcd[8661]: avoid queries with large range/delete range!
Jul 07 16:05:05 kube-master etcd[8661]: store.index: compact 2037722
Jul 07 16:05:05 kube-master etcd[8661]: finished scheduled compaction at 2037722 (took 2.982671ms)
Jul 07 16:10:05 kube-master etcd[8661]: store.index: compact 2038246
Jul 07 16:10:05 kube-master etcd[8661]: finished scheduled compaction at 2038246 (took 1.99918ms)

The makes creation of k8s object too slow such as Deployment,POD and so on. At the same time kubectl command responses very slowly. So how can I solve the problem? Thanks!

**Comment by fogongzi** [comment]
@kubernetes/sig-controller-manager-bugs

**Comment by xiangpengzhao** [comment]
dup of #49000
