### ISSUE TITLE
Reuse existing Persistent Volume (GCE)

### ISSUE THREAD

**Issue by whitecolor** [kubernetes/kubernetes#48609]
I trying to reuse persistent volume on GCE (kubernetes 1.6.4) for new Deployment (via PVC):

- Created PVC (using heml releases), 
- PV was provisioned
- Manually changed PV reclaim policy to `Retain` from `Delete`
- Delete helm release - it deletes PVC, but due to policy change PV stays (status `Released`)
- Deploy new release with `PVC.spec.volumeName` set to existing PV name
- Deployment fail to work:

```
 Unable to mount volumes for pod "store-more-mongodb-2323256449-rhbt4_backyard(c31b771c-6321-11e7-b339-42010af000cb)": timeout expired waiting for volumes to attach/mount for pod "backyard"/"store-more-mongodb-2323256449-rhbt4". list of unattached/unmounted volumes=[data]
Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "backyard"/"store-more-mongodb-2323256449-rhbt4". list of unattached/unmounted volumes=[data] 
```

I wonder is it possible to do on GCE an how?

**Comment by whitecolor** [comment]
Seems to work if to remove `ClaimRef` from PV, then is becomes `Available`, and is bound to with new PVC with `volumeName` set.

I would like to confirm if this is a valid method and doesn't break any rules. 

Also there is a question of the validity of PV  reclaim policy change for this case to `Retain`, is it this a valid method to keep it from deletion?

**Comment by mtanino** [comment]
When I removed entire ClaimRef entry from released PV, I could succeed to reuse existing PV to new PVC.

```
k8sbuild-master % k get pv,pvc,storageclass,pod,deployment
NAME        CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS     CLAIM                 STORAGECLASS   REASON    AGE
pv/pv0001   1Gi        RWO           Retain          Released   default/nginx-pvc02   slow                     9m
k8sbuild-master % kubectl edit pv pv0001
persistentvolume "pv0001" edited


apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-class: slow
  creationTimestamp: 2017-07-07T16:05:37Z
  name: pv0001
  resourceVersion: "83003"
  selfLink: /api/v1/persistentvolumes/pv0001
  uid: 1dda823b-632e-11e7-9345-525400645a80
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  iscsi:
    fsType: ext4
    iqn: iqn.2017-05.com.example:rhel7
    iscsiInterface: default
    lun: 0
    readOnly: true
    targetPortal: 192.168.122.85:3260
  persistentVolumeReclaimPolicy: Retain
status:
  phase: Released

k8sbuild-master % k get pv,pvc,storageclass,pod,deployment
NAME        CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS      CLAIM     STORAGECLASS   REASON    AGE
pv/pv0001   1Gi        RWO           Retain          Available             slow                     10m
k8sbuild-master % k get pv,pvc,storageclass,pod,deployment
NAME        CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                 STORAGECLASS   REASON    AGE
pv/pv0001   1Gi        RWO           Retain          Bound     default/nginx-pvc02   slow                     11m

NAME              STATUS    VOLUME    CAPACITY   ACCESSMODES   STORAGECLASS   AGE
pvc/nginx-pvc02   Bound     pv0001    1Gi        RWO           slow           2s
```

**Comment by whitecolor** [comment]
Yes, now it is working for me too after I delete pod (kicked Deployment). Just need to ensure that it will be stable.

So I would like to confirm if this is a valid method and doesn't break any rules. 

Also, there is a question of the validity of PV  reclaim policy change for this case to `Retain`, is it this a valid method to keep it from deletion?

**Comment by mtanino** [comment]
But if I didn't remove entire ClaimRef entry like below, the PV status was changed to Available but it couldn't be reused. This seems like a bug.
And I'm not sure what change is applied via dashboard UI.

```
k8sbuild-master % k get pv,pvc,storageclass,pod,deployment
NAME        CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS     CLAIM                 STORAGECLASS   REASON    AGE
pv/pv0001   1Gi        RWO           Retain          Released   default/nginx-pvc02   slow                     9s
k8sbuild-master % kubectl edit pv pv0001
persistentvolume "pv0001" edited

apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-class: slow
  creationTimestamp: 2017-07-07T16:24:11Z
  name: pv0001
  resourceVersion: "83655"
  selfLink: /api/v1/persistentvolumes/pv0001
  uid: b56f5e68-6330-11e7-9345-525400645a80
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
  iscsi:
    fsType: ext4
    iqn: iqn.2017-05.com.example:rhel7
    iscsiInterface: default
    lun: 0
    readOnly: true
    targetPortal: 192.168.122.85:3260
  persistentVolumeReclaimPolicy: Retain
status:
  phase: Released

k8sbuild-master % k get pv,pvc,storageclass,pod,deployment
NAME        CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS      CLAIM     STORAGECLASS   REASON    AGE
pv/pv0001   1Gi        RWO           Retain          Available   /         slow                     58s

k8sbuild-master % k create -f pvc.yaml
persistentvolumeclaim "nginx-pvc02" created
k8sbuild-master % k get pv,pvc,storageclass,pod,deployment
NAME        CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS      CLAIM     STORAGECLASS   REASON    AGE
pv/pv0001   1Gi        RWO           Retain          Available   /         slow                     1m

NAME              STATUS    VOLUME    CAPACITY   ACCESSMODES   STORAGECLASS   AGE
pvc/nginx-pvc02   Pending                                      slow           3s
```

**Comment by mtanino** [comment]
@gnufied @jsafrane @rootfs

**Comment by whitecolor** [comment]
I still have the error of deployment on the first start (just after creation), then I delete the pod, it recreates it and starts ok.

**Comment by jsafrane** [comment]
> Delete helm release - it deletes PVC, but due to policy change PV stays (status Released)
> Deploy new release with PVC.spec.volumeName set to existing PV name

When you delete a PVC, corresponding PV becomes `Released`. This PV can contain sensitive data (say credit card numbers) and therefore nobody can ever bind to it, even if it is a PVC with the same name and in the same namespace as the previous one - who knows who's trying to steal the data!

Admin intervention is required here. He has two options:

* Make the PV available to everybody - delete `PV.Spec.ClaimRef`, Such PV can bound to any PVC (assuming that capacity, access mode and selectors match)
* Make the PV available to a specific PVC - pre-fill `PV.Spec.ClaimRef` with a pointer to a PVC. Leave the `PV.Spec.ClaimRef,UID` empty, as the PVC does not to need exist at this point and you don't know PVC's UID. This PV can be bound only to the specified PVC.


@whitecolor, in your case you should be fine by clearing `PV.Spec.ClaimRef.UID` in the PV. Only the re-created PVC (with any UID) can then use the PV. And it's your responsibility that only the right person can craft appropriate PVC so nobody can steal your data.

**Comment by whitecolor** [comment]
> in your case you should be fine by clearing PV.Spec.ClaimRef.UID in the PV. Only the re-created PVC (with any UID) can then use the PV. And it's your responsibility that only the right person can craft appropriate PVC so nobody can steal your data.

Thanks for the comment. Good, that is techically supported by solution, probably it should be documented somewhere. Though as I said after creation new PVC bound to exiting PV (via its UID) and deployment that uses this PV, deployment failed to start with error above, after I deleted the pod, it started again. Probably kind of bug, as I said i'm on GCE (1.6.4).

**Comment by mtanino** [comment]
@jsafrane 

Thank you for the comment. I'll add these steps to the documentation.
By the way, @whitecolor mentioned that there is a case admin want to keep physical disk even if PV/PVC are deleted.
Do we currently have a way to do this?

```
usecase is: you had dynamically provisioned some storage, and then want to delete the PV/PVC but keeping the disk so you can use it somewhere else outside the cluster
```

FYI, we got a following comment on the slack.
```
gnufied [8:29 AM] 
@dirbaio deleting a PV should always delete the underlying GCE PD, regardless of reclaimPolicy afaik
[8:29] reclaimPolicy dictates bonding between PVC & PV
[8:30] if deleting PV doesn't delete GCE PD, then it is a bug
```

**Comment by jsafrane** [comment]
> I'll add these steps to the documentation.

Thanks! It should not be part of regular operation and it's very advanced topic / workaround, but it's part of the API and it's supported. 

> there is a case admin want to keep physical disk even if PV/PVC are deleted. Do we currently have a way to do this?

Right now you can set the policy to Retain. We're adding a policy field to StorageClass for 1.8 in #47987 so admin can configure it for some/all provisioned PVs.

> deleting a PV should always delete the underlying GCE PD, regardless of reclaimPolicy afaik
> ...
> if deleting PV doesn't delete GCE PD, then it is a bug

That's not true, deleting a PV does not do anything to the GCE PD, it remains there. Deleting PVC triggers the reclaim policy and deletion of both PV and GCE PD if the policy says so.

**Comment by msau42** [comment]
To clarify, for the scenario where you want to delete the PV, but keep the disk, you can:

1. Set the reclaim policy to Retain.
2. Delete the PVC
3. Delete the PV

The disk will not be deleted.  Only if reclaim policy is Delete, and you deleted the PVC, then we will delete the disk.

**Comment by mtanino** [comment]
@msau42 
Yes. I confirmed those steps worked fine.

**Comment by mtanino** [comment]
@whitecolor @jsafrane 
Since the document have been updated, I think we can close this issue. Thanks.

**Comment by gridcellcoder** [comment]
@jsafrane 
> Admin intervention is required here. He has two options:
> 
> * Make the PV available to everybody - delete `PV.Spec.ClaimRef`, Such PV can bound to any PVC (assuming that capacity, access mode and selectors match)
> * Make the PV available to a specific PVC - pre-fill `PV.Spec.ClaimRef` with a pointer to a PVC. Leave the `PV.Spec.ClaimRef,UID` empty, as the PVC does not to need exist at this point and you don't know PVC's UID. This PV can be bound only to the specified PVC.

Does this work if the cluster is deleted? i.e. is there a way to get a PV and PVC to bind to an existing persistent volume (say from a previously deleted cluster)? 

The use case is this: load some data - delete cluster to save costs - restart cluster with previous GCE disks that have data- bind them to the PVC

your method works if the cluster is alive, but we're looking for a solution when the cluster is no more.

**Comment by msau42** [comment]
@gridcellcoder yes, you can manually create a new PV object in your new cluster with the details of the PD. You can look at https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/preexisting-pd for an example

**Comment by gridcellcoder** [comment]
> @gridcellcoder yes, you can manually create a new PV object in your new cluster with the details of the PD. You can look at https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/preexisting-pd for an example

That's a neat solution @msau42 do you know if it can work with `StatefulSets` https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/. This approach uses dynamically created PVC so is it possible to manipulate the `volumeClaimTemplates` to reuse disks?

**Comment by msau42** [comment]
The Statefulset PVCs are generated with a fixed syntax: `statefulset-pvc-index` so when you manually create the PV, you can set the claimref and storageclass name to match the PVC that will be created.

**Comment by Hermain** [comment]
> Seems to work if to remove `claimRef` from PV, then is becomes `Available`, and is `Bound` to with new PVC with `volumeName` set.
> 
> But deployment still doesn't work with the same error.

Not necessary to remove the entire claimRef if the deploment/statefullset has not changed. The uid: field is enough to unbind the volume and you don't risk using that volume for the wrong statefullset/replica since the other labels wont match.

**Comment by robersongomes** [comment]
Those are the steps that worked for me:

1. Remove `claimRef` from PV: 
`kubectl patch pv my-pv-name-123465789 -p '{"spec":{"claimRef": null}}'`

2. Create a PVC setting volumeName: 
```
apiVersion: v1
kind: PersistentVolumeClaim
...
spec:
  ...
  volumeName: my-pv-name-123465789
  ...
```

**Comment by ebuildy** [comment]
Didnt find for GCE, but for Azure, it's quite explicit:

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/vendor/k8s.io/component-helpers/storage/volume/pv_helpers.go#L158

```
if claim.Name != volume.Spec.ClaimRef.Name || claim.Namespace != volume.Spec.ClaimRef.Namespace {
		return false
	}
	if volume.Spec.ClaimRef.UID != "" && claim.UID != volume.Spec.ClaimRef.UID {
		return false
	}
```

The driver tries to re-use if possible a PV with good ``claimRef.name`` and ``claimRef.namespace``
