### ISSUE TITLE
pull-kubernetes-federation-e2e-gce: error during ./federation/cluster/federation-up.sh: exit status 1

### ISSUE THREAD

**Issue by dcbw** [kubernetes/kubernetes#48623]
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/48613/pull-kubernetes-federation-e2e-gce/13405/build-log.txt

Pretty hard to figure out what's going wrong because there are no artifacts, despite the build log saying it fetched some.

**Comment by csbell** [comment]
Test cluster is back up now. http://prow.k8s.io/?type=presubmit&job=pull-kubernetes-federation-e2e-gce shows resumed passing tests.
/close
