### ISSUE TITLE
The latest Elasticsearch and Kibana images are missing in gcr.io

### ISSUE THREAD

**Issue by anisimovsergey** [kubernetes/kubernetes#48620]
/kind bug

Elasticsearch and Kibana images, used in fluentd-elasticsearch addon, were updated to newer versions (5.4.0) in CL [b23b919](https://github.com/kubernetes/kubernetes/commit/b23b919b05c84cef84473ff938e33438da33bca0)

I expect that I should be able to fetch corresponding Docker images using
**gcr.io/google_containers/elasticsearch:v5.4.0-1** and **gcr.io/google_containers/kibana:v5.4.0** but unfortunately they are not in the registry.

**Comment by cblecker** [comment]
/area logging
/sig instrumentation
cc: @coffeepac @crassirostris @piosz

**Comment by crassirostris** [comment]
@anisimovsergey Thanks for noticing! Built and pushed
