### ISSUE TITLE
"no kind ClusterRole is registered for version rbac.authorization.k8s.io/v1beta1" when creating RBAC resources on K8S 1.6.6

### ISSUE THREAD

**Issue by gaballard** [kubernetes/kubernetes#48629]
Is this a BUG REPORT or FEATURE REQUEST?:

/kind bug

What happened:

I create a ClusterRole resource. I try to apply the ClusterRole to my Google Container Engine-hosted K8S v1.6.6 cluster. The cluster has RBAC enabled. All attempts produce the following error:

`error: unable to decode "[filename].yaml": no kind "ClusterRole" is registered for version "rbac.authorization.k8s.io/v1beta1"`

Extremely similar to #48628.

What you expected to happen:

The resource is created.

How to reproduce it (as minimally and precisely as possible):

1. Set up a cluster running Kubernetes 1.6.6 with RBAC enabled on Google Container Engine
2. Create a ClusterRole resource and attempt to apply it

Anything else we need to know?:

Environment:

Kubernetes version (use kubectl version): 1.6.6
Cloud provider or hardware configuration**: Google Container Engine
OS (e.g. from /etc/os-release): Container-Optimized OS (cos)
Kernel (e.g. uname -a): 4.4.52+

**Comment by guilhem** [comment]
I just faced the same problem.
On my case, this was due to using `kubectl apply`. Using `kubectl create` "fixed" the problem.

Thx to https://github.com/coreos/prometheus-operator/issues/363#issuecomment-300770068

**Comment by liggitt** [comment]
@gaballard what version of kubectl are you running?

cc @kubernetes/sig-cli-bugs

**Comment by liggitt** [comment]
@gaballard can you provide the following:
* output of `kubectl version`
* output of `kubectl api-versions`
* the yaml of the cluster role you were creating

**Comment by liggitt** [comment]
closing due to lack of information

**Comment by arkachat** [comment]
[root@localhost ~]#  kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard-head.yaml
Error from server (AlreadyExists): error when creating "https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard-head.yaml": secrets "kubernetes-dashboard-certs" already exists
Error from server (AlreadyExists): error when creating "https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard-head.yaml": serviceaccounts "kubernetes-dashboard-head" already exists
Error from server (BadRequest): error when creating "https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard-head.yaml": Role in version "v1beta1" cannot be handled as a Role: no kind "Role" is registered for version "rbac.authorization.k8s.io/v1beta1"
Error from server (BadRequest): error when creating "https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard-head.yaml": RoleBinding in version "v1beta1" cannot be handled as a RoleBinding: no kind "RoleBinding" is registered for version "rbac.authorization.k8s.io/v1beta1"
error validating "https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard-head.yaml": error validating data: [found invalid field tolerations for v1.PodSpec, found invalid field initContainers for v1.PodSpec]; if you choose to ignore these errors, turn validation off with --validate=false
[root@localhost ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"269f928217957e7126dc87e6adfa82242bfe5b1e", GitTreeState:"clean", BuildDate:"2017-07-03T15:31:10Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"269f928217957e7126dc87e6adfa82242bfe5b1e", GitTreeState:"clean", BuildDate:"2017-07-03T15:31:10Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
[root@localhost ~]# 
[root@localhost ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"269f928217957e7126dc87e6adfa82242bfe5b1e", GitTreeState:"clean", BuildDate:"2017-07-03T15:31:10Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"269f928217957e7126dc87e6adfa82242bfe5b1e", GitTreeState:"clean", BuildDate:"2017-07-03T15:31:10Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
[root@localhost ~]# kubectl api-versions
apps/v1beta1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1beta1
autoscaling/v1
batch/v1
certificates.k8s.io/v1alpha1
extensions/v1beta1
policy/v1beta1
rbac.authorization.k8s.io/v1alpha1
storage.k8s.io/v1beta1
v1

**Comment by arkachat** [comment]
@liggitt Can you help me with this info ..

**Comment by liggitt** [comment]
you are trying to create RBAC resources from the master dashboard branch, which are defined in v1beta1 form, against a 1.5 server. RBAC v1beta1 was not added until 1.6

**Comment by arkachat** [comment]
Thanks .. Is there an option to install it on the default centos 1.5 version?

**Comment by liggitt** [comment]
with a newer version of kubectl (1.6+) that understands rbac v1beta1 objects, you can run the manifest through `kubectl convert`:

```
kubectl version

... must have a client version of 1.6 or higher ...

kubectl convert -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard-head.yaml --output-version=rbac.authorization.k8s.io/v1alpha1 | kubectl apply -f -
```

**Comment by arkachat** [comment]
Thank you :)

**Comment by KIVagant** [comment]
FYI: I got this problem on one node where `kubectl` had outdated v1.5 version while server was in 1.10.

**Comment by JohnBoyB** [comment]
I got the same problem in version v1.23.1

**Comment by JohnBoyB** [comment]
**Solution**
I was able to solve the problem by changing the apiVersion from rbac.authorization.k8s.io/v1beta1 to rbac.authorization.k8s.io/v1
