### ISSUE TITLE
"No kind is registered for the type runtime.Unknown" error when creating RBAC resources on 1.6.6

### ISSUE THREAD

**Issue by gaballard** [kubernetes/kubernetes#48628]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I create a List resource containing ClusterRole or ClusterRoleBinding resources. I try to create or apply the List to my Google Container Engine-hosted K8S v1.6.6 cluster. The cluster has RBAC enabled. All attempts produce the following error:

`error: unable to get type info from the object "*runtime.Unknown": no kind is registered for the type runtime.Unknown`

The error seems to be a Go error originating from [https://github.com/kubernetes/apimachinery/blob/master/pkg/runtime/error.go](https://github.com/kubernetes/apimachinery/blob/master/pkg/runtime/error.go).

**What you expected to happen**:

The resource is created.

**How to reproduce it (as minimally and precisely as possible)**:

1. Set up a cluster running Kubernetes 1.6.6 with RBAC enabled on Google Container Engine
2. Add a ClusterRole or ClusterRoleBinding resource to a List and attempt to apply it

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.6
- Cloud provider or hardware configuration**: Google Container Engine
- OS (e.g. from /etc/os-release): Container-Optimized OS (cos)
- Kernel (e.g. `uname -a`): 4.4.52+

**Comment by guilhem** [comment]
I just faced the same problem.
On my case, this was due to using `kubectl apply`. Using `kubectl create` "fixed" the problem.

Thx to https://github.com/coreos/prometheus-operator/issues/363#issuecomment-300770068

**Comment by liggitt** [comment]
@gaballard do you have the contents of the file you are trying to create available?

@kubernetes/sig-cli-bugs

**Comment by liggitt** [comment]
@gaballard can you provide the following:
* output of `kubectl version`
* output of `kubectl api-versions`
* the yaml of the cluster role you were creating

**Comment by felixhummel** [comment]
I had the same problem with an outdated `kubectl`. Just update, so versions match, and it works! \o/

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by liggitt** [comment]
closing due to lack of information
