### ISSUE TITLE
kubectl should use websockets for exec, port forward, logs, and attach

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#48633]
SPDY is dead (https://github.com/kubernetes/kubernetes/issues/7452).  WebSockets is at least better supported.  We can tunnel most things over web sockets and it is better supported than SPDY.  We should switch kubectl to only use web sockets, and fix the various issues.  I'd like to deprecate SPDY in 1.8 and potentially remove in 1.9, given that there are almost no integrations leveraging SPDY out there in the wild.

* proxy doesn't support web sockets or spdy https://github.com/kubernetes/kubernetes/issues/32026
* stderr and stdout mangled https://github.com/kubernetes/kubernetes/issues/28167
* multi-watch will be over websockets https://github.com/kubernetes/kubernetes/issues/1685
* web sockets are usable from browser

**Comment by smarterclayton** [comment]
I'll take refactoring exec and port forward to share code and allow web sockets.

**Comment by stephenlb** [comment]
+1 for http/2.

**Comment by smarterclayton** [comment]
It's unlikely we'll get there anytime soon, unless someone steps up for the
end to end work.  The near term is about reducing to a single solution
rather than two.

On Jul 7, 2017, at 10:00 PM, Stephen L. Blum <notifications@github.com>
wrote:

+1 for http/2.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/48633#issuecomment-313826635>,
or mute the thread

**Comment by lavalamp** [comment]
cc @mbohlool

**Comment by NormanWang06** [comment]
@smarterclayton 
1.8 is released! 
But kubectl exec still use SPDY/3.1.
Is there any way we can set kubectl to use websocket? or server side version must be 1.8+?

client version is: v1.8.0
server version is: v1.6.6

**Comment by Kaijun** [comment]
any further work for this?
