### ISSUE TITLE
Typo in pod evicted status message

### ISSUE THREAD

**Issue by spadgett** [kubernetes/kubernetes#48632]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

The `pod.status.message` for evicted pods has a typo (extra "Pod" before the sentence).

```yaml
status:
  message: 'Pod The node was low on resource: [MemoryPressure].'
  phase: Failed
  reason: Evicted
  startTime: '2017-07-07T19:36:11Z'
```

**How to reproduce it (as minimally and precisely as possible)**:

Enable `evication-hard` in the node config `kubeletArguments` with a large memory available value to force a pod to be evicted. Check the pod YAML for the status message.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.1

@jwforres @derekwaynecarr

**Comment by dixudx** [comment]
@spadgett I've tested on v1.6.4. Had been got fixed.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
status:
  message: 'The node was low on resource: memory.'
  phase: Failed
  reason: Evicted
  startTime: 2017-07-08T05:34:52Z
```

**Comment by spadgett** [comment]
> I've tested on v1.6.4. Had been got fixed.

@dixudx Great, thanks. I'll close the issue since it's fixed.
