### ISSUE TITLE
Create integration testing framework

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#48634]
/assign Q-Lee
/sig testing
/kind feature

Created as a result of sig-testing v1.8 / 2017 planning.  Accidentally created originally as kubernetes/test-infra#3372

@fejta @Q-Lee can you provide some context here?  I'm assuming this is about creating a `test/integration/framework` package that is similar to `test/e2e/framework`, presumably with the idea that making it easier to write integration tests will make it easier to discourage / move away from slower, flakier e2e tests.

**Comment by kargakis** [comment]
cc: @dhilipkumars

**Comment by dhilipkumars** [comment]
@spiffxp I'm currently working on this for apps here is the rough [plan](https://github.com/kubernetes/kubernetes/pull/50144).  Could you please take a look and comment please?
