### ISSUE TITLE
Write a design doc on adding priority to ResourceQuota

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#48647]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature Request

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

@kubernetes/sig-scheduling-feature-requests

**Comment by bsalamat** [comment]
ref/ #47604

**Comment by resouer** [comment]
https://github.com/kubernetes/community/pull/933/files is under actively review and discuss.

**Comment by resouer** [comment]
https://github.com/kubernetes/community/pull/933/ has been merged so doc can be drafted.

**Comment by bsalamat** [comment]
This is already written and the feature is implemented: #57963.
