### ISSUE TITLE
Implement priority/preemption in pod scheduling logic

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#48646]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature request

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

Tracking issue for implementing priority and preemption in Kubernetes scheduler.

**Comment by bsalamat** [comment]
@kubernetes/sig-scheduling-feature-requests 

/assign

**Comment by bsalamat** [comment]
ref/ #47604

**Comment by ravisantoshgudimetla** [comment]
@bsalamat I can pick this up, in case you haven't started implementation. I think this could be broken down into further tasks, based on https://github.com/kubernetes/community/pull/745/files like:

- Implement a  queue which holds the incoming pods in scheduler.
- Modify scheduler logic to pre-empt some pods based priority scheme described in above doc.
etc. WDYT?

**Comment by bsalamat** [comment]
@ravisantoshgudimetla I am already working on this, but this is one of the five issues listed in https://github.com/kubernetes/kubernetes/issues/47604. Feel free to pick any other one. Those are mostly around the idea of adding priority to ResourceQuota and would make more sense if you started by adding a design doc on that topic.
