### ISSUE TITLE
Write user documentation for priority and preemption

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#48649]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature request

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

@kubernetes/sig-scheduling-feature-requests 

ref/ #47604

**Comment by WIZARD-CXY** [comment]
Look forward to

**Comment by bsalamat** [comment]
The document is already added: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
