### ISSUE TITLE
kudernetes commands error out dial tcp i/o timeout. kudeadm join command fails.

### ISSUE THREAD

**Issue by sudharkrish** [kubernetes/kubernetes#48643]
> /kind bug

**What happened**:
After successfully initializing cluster on Master Node, kudeadm join command from slave nodes to Master Node fails.

**What you expected to happen**:
After successfully initializing cluster on Master Node, expected that I can join slave nodes to Master Node.

**How to reproduce it (as minimally and precisely as possible)**:

Using kubernetes version 1.7.0.
Following installation steps in this URL: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

1. On the Master Node, when I run kubeadmin init, I was getting the following tcp timeout error:

sudo kubeadm init --apiserver-ad dvertise-address=192.168.1.104 --pod-network-cidr=10.244.0.0/16 –skip-preflight- -checks
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters. 
unable to get URL "https://storage.googleapis.com/kubernetes-release/release/stable-1.7.txt": Get https://storage.googleapis.com/kubernetes-release/release/stable-1.7.txt: dial tcp 172.217.3.208:443: i/o timeout 

2. So tried specifying the kubernetes version, since I read online that this prevents fetch from external website, and with that kubeadmin init was successful.
sudo kubeadm init --kubernetes-version v1.7.0 --apiserver-advertise-address=192.168.1.104 --pod-network-cidr=10.244.0.0/16 --skip-preflight-checks 

3. Ran the below commands and they went through fine.
  mkdir -p $HOME/.kube 
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config 
  sudo chown $(id -u):$(id -g) $HOME/.kube/config 

4. Tried to deploy a pod network to the cluster, but fails with the same tcp timeout error:
kubectl apply -f 
http://docs.projectcalico.org/v2.3/ getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml 

Unable to connect to the server: dial tcp 151.101.0.133:80: i/o timeout 

5. Downloaded the calico.yaml file using browser, and ran the command, it was successful.
sudo kubectl apply -f ~/Downloads/calico.yaml 

On the Slave Node:
1. Ran the join command, and it fails trying to get cluster info

Output of join command in slave node:
skris14@sudha-ubuntu-16:~$ sudo kubeadm join --token 84525a.8184f7137b525f3a 192.168.1.104:6443
[sudo] password for skris14: 
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[preflight] Running pre-flight checks
[discovery] Trying to connect to API Server "192.168.1.104:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://192.168.1.104:6443"
[discovery] Failed to request cluster info, will try again: [Get https://192.168.1.104:6443/: EOF]
^C

**Anything else we need to know?**:
Between the Master Node and Slave Node, there is network communication, since ping, ssh,telnet and scp commands work fine between the 2 Nodes.
Also, from the slave node's browser window, I am able to reach the web server(apiserver) running at port 6443.

**Environment**:
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**: Private
- OS (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS
- Kernel (e.g. `uname -a`): Linux skris14-ubuntu16.04-VM1 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm

**Comment by sudharkrish** [comment]
@kubernetes/sig-Network-misc

**Comment by sudharkrish** [comment]
Please help
@kubernetes/sig-api-machinery
/sig api-machinery

**Comment by sudharkrish** [comment]
Just wondering, if anyone is looking at this issue.

**Comment by luxas** [comment]
Hi!

Thank you for filing this issue. We appreciate your interest in Kubernetes and kubeadm.
In order to make the kubernetes/kubernetes issue tracker more usable, we're routing issues to different repositories with different focuses.

I think this issue belongs in the kubeadm repository. Please move this issue to the [kubeadm repo tracker](https://github.com/kubernetes/kubeadm/issues) in order for the kubeadm team to be able to track this efficiently. If you disagree with my assessment of moving this issue, please speak up and/or reopen the issue. Finally, please try to reproduce the bug with the latest Kubernetes version, it might as well already have been fixed :)

Thank you and have a good day!
