### ISSUE TITLE
Auto-generation by deepcopy is broken

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#48675]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

While working on PR #48630, deepcopy did not update auto-generated files at all places. 

After updating the `gengo` vendor directory, I did a `./hack/update-codegen.sh` which only updated _some_ of the deepcopy files. This made tests fail (https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/48630/pull-kubernetes-verify/38489/). 

Later, I removed the files where the CI complained and auto-generated again using make. This updated the other files too. (https://github.com/kubernetes/kubernetes/pull/48630/commits/38ac8a2eb610848064a8f780db6315f86a8312c2)

**What you expected to happen**:

Running  `./hack/update-codegen.sh` should update the auto-generated files at all places where it is necessary.

**How to reproduce it (as minimally and precisely as possible)**:
This does not seem to be reproducible always. But to reproduce it, please follow the steps mentioned in the description above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.823+a57c33bd281732", GitCommit:"a57c33bd2817323806b97da5c2f848108f7403d8", GitTreeState:"clean", BuildDate:"2017-06-19T02:15:29Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
```
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
godep version:

```
godep v79 (linux/amd64/go1.8.1)
```

**Comment by sttts** [comment]
I have seen this as well. I was changing gengo at the same time. So maybe it only happens in that case.

**Comment by sttts** [comment]
@nikhita deepcopy is not in ./hack/update-codegen.sh, but in `Makefile.generated_files`.

**Comment by mbohlool** [comment]
@nikhita if you do a `make clean_generated` and then `make generated_files` does it fix the problem?

**Comment by sttts** [comment]
@mbohlool a clever `find ...  | xargs rm` which is probably equivalent to `clean_generated` helps.

**Comment by thockin** [comment]
I am looking at ways to make this clearer and easier to debug

**Comment by thockin** [comment]
I added a bunch of debugging if you run make with `DBG_CODEGEN=1`.  We also fixed some pretty corner-case rsync bugs that could cause this.  Closing for now, please reopen if it recurs.
