### ISSUE TITLE
kubeadm setup to kubectl proxy => http: proxy error: x509: certificate is valid for [internal IPs]

### ISSUE THREAD

**Issue by evictor** [kubernetes/kubernetes#48680]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug report

/kind bug

**What happened**: Cannot use `kubectl proxy` from a remote machine with a cluster set up using `kubeadm`; receive the error `Starting to serve on 127.0.0.1:8001I0709 20:48:16.424033    4250 logs.go:41] http: proxy error: x509: certificate is valid for [several internal IPs], not [external IP used to access the cluster master]`. Note that `kubectl proxy` on the master machine itself works fine.

**What you expected to happen**: I expect `kubectl proxy` to work.

**How to reproduce it (as minimally and precisely as possible)**: Created a cluster with `kubeadm` following the official guide installed with Calico. Kube version is 1.7.0, Docker version is 1.13 because I could not get 1.12 from the package repo. Ubuntu 16.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.0
- Cloud provider or hardware configuration**: On Azure, but set up manually using `kubeadm`.
- OS (e.g. from /etc/os-release): Ubuntu 16.04.2 LTS
- Kernel (e.g. `uname -a`): Linux k8s-master-58998207-0 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Others:

**Comment by evictor** [comment]
@sig-cluster-lifecycle-bugs

**Comment by evictor** [comment]
@kubernetes/sig-cluster-lifecycle-bugs

**Comment by evictor** [comment]
Is there a way to add a SAN to some certificate somewhere to allow access via the public IP? Or tunnel, or VPN, or...?

**Comment by liggitt** [comment]
kubeadm-specific issues are tracked in https://github.com/kubernetes/kubeadm/issues/
I'd suggest moving this issue there

**Comment by evictor** [comment]
Thanks, will do.
