### ISSUE TITLE
Flake? E2E Test failed with GCP quota exceeded

### ISSUE THREAD

**Issue by fasaxc** [kubernetes/kubernetes#48688]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

CI tests for #48469 failed with a quota error:

```
I0708 13:01:19.525] Creating new network: e2e-38580
W0708 13:02:07.576] ERROR: (gcloud.compute.networks.create) Could not fetch resource:
W0708 13:02:07.577]  - Quota 'SUBNETWORKS' exceeded.  Limit: 100.0
```

Full logs:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/48469/pull-kubernetes-kubemark-e2e-gce/38580/build-log.txt

**What you expected to happen**:

Clean test run.

**How to reproduce it (as minimally and precisely as possible)**:

I don't know wnough about the test infrastructure to know.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Unknown (test infra)
- Cloud provider or hardware configuration**: GCP
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fasaxc** [comment]
@kubernetes/sig-testing-misc

**Comment by kargakis** [comment]
@krzyzacy IIUC, your new tool, boskos, is destined for fixing these kinds of failures, right?

**Comment by krzyzacy** [comment]
no, that should be janitor, and seems something is leaking badly from the test

**Comment by krzyzacy** [comment]
I'll check the project, @MrHohn IMO it does not even run test, any suspicious?

**Comment by MrHohn** [comment]
Quick update: Seems like the auto-network includes more regions than before so we hit quota limit when too many PR jobs are running together.

**Comment by krzyzacy** [comment]
sent a quota bump, will need a better design in the future.
