### ISSUE TITLE
kubeadm join doesn't work for 1.7.

### ISSUE THREAD

**Issue by zhangqx2010** [kubernetes/kubernetes#48687]
/kind bug

**What happened**:
I deployed a lab cluster in 1.6. And then use kubeadm reset to tear down the cluster.
Then I install 1.7 version kubelet and kubeadm.
kubeadm init on master succeeded.

On the other node:
```
kubeadm join --token 94bdf4.a838c6738b453d5f x.x.x.x:6443
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[preflight] Running pre-flight checks
[preflight] Starting the kubelet service
[discovery] Trying to connect to API Server "x.x.x.x:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://x.x.x.x:6443"
[discovery] Cluster info signature and contents are valid, will use API Server "https://x.x.x.x:6443"
[discovery] Successfully established connection with API Server "x.x.x.x:6443"
[bootstrap] Detected server version: v1.7.0
[bootstrap] The server supports the Certificates API (certificates.k8s.io/v1beta1)
[csr] Created API client to obtain unique certificate for this node, generating keys and certificate signing request
[csr] Received signed certificate from the API server, generating KubeConfig...
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"

Node join complete:
* Certificate signing request sent to master and response
  received.
* Kubelet informed of new secure connection details.

Run 'kubectl get nodes' on the master to see this machine join.
```

kubectl get nodes only show master
```
kubectl get nodes
NAME                         STATUS    AGE       VERSION
01v                                 Ready     1h        v1.7.0
```

**What you expected to happen**:
On Master:
kubectl get nodes show all nodes

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
Red Hat Enterprise Linux Server release 7.2 (Maipo)
- Kernel (e.g. `uname -a`):
``Linux  3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux``
- Install tools:
- Others:

**Comment by zhangqx2010** [comment]
noticed error in system log on 02v:

```
[root@02V ~]# journalctl -u kubelet -f
-- Logs begin at Thu 2017-07-06 19:09:20 CST. --
Jul 10 17:10:56 02v kubelet[11838]: I0710 17:10:56.584585   11838 kubelet_node_status.go:82] Attempting to register node 02v
Jul 10 17:10:56 02v kubelet[11838]: E0710 17:10:56.586048   11838 kubelet_node_status.go:106] Unable to register node "02v" with API server: nodes "02v" is forbidden: node 02v cannot modify node 02v
Jul 10 17:10:59 02v kubelet[11838]: W0710 17:10:59.808888   11838 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d
Jul 10 17:10:59 02v kubelet[11838]: E0710 17:10:59.808982   11838 kubelet.go:2136] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Jul 10 17:10:59 02v kubelet[11838]: E0710 17:10:59.847905   11838 eviction_manager.go:238] eviction manager: unexpected err: failed GetNode: node '02v' not found
Jul 10 17:11:03 02v kubelet[11838]: I0710 17:11:03.586198   11838 kubelet_node_status.go:247] Setting node annotation to enable volume controller attach/detach
Jul 10 17:11:03 02v kubelet[11838]: I0710 17:11:03.587894   11838 kubelet_node_status.go:82] Attempting to register node 02v
Jul 10 17:11:03 02v kubelet[11838]: E0710 17:11:03.589451   11838 kubelet_node_status.go:106] Unable to register node "02v" with API server: nodes "02v" is forbidden: node 02v cannot modify node 02v
Jul 10 17:11:04 02v kubelet[11838]: W0710 17:11:04.813435   11838 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d
Jul 10 17:11:04 02v kubelet[11838]: E0710 17:11:04.813551   11838 kubelet.go:2136] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Jul 10 17:11:09 02v kubelet[11838]: W0710 17:11:09.814294   11838 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d
Jul 10 17:11:09 02v kubelet[11838]: E0710 17:11:09.814684   11838 kubelet.go:2136] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Jul 10 17:11:09 02v kubelet[11838]: E0710 17:11:09.850698   11838 eviction_manager.go:238] eviction manager: unexpected err: failed GetNode: node '02v' not found
Jul 10 17:11:10 02v kubelet[11838]: I0710 17:11:10.589607   11838 kubelet_node_status.go:247] Setting node annotation to enable volume controller attach/detach
Jul 10 17:11:10 02v kubelet[11838]: I0710 17:11:10.591263   11838 kubelet_node_status.go:82] Attempting to register node 02v
Jul 10 17:11:10 02v kubelet[11838]: E0710 17:11:10.592735   11838 kubelet_node_status.go:106] Unable to register node "02v" with API server: nodes "02v" is forbidden: node 02v cannot modify node 02v
```

**Comment by luxas** [comment]
> Jul 10 17:47:20 02v kubelet[13271]: E0710 17:47:20.076793   13271 kubelet_node_status.go:106] Unable to register node "02v" with API server: nodes "02v" is forbidden: node 02v cannot modify node 02v

@liggitt This looks pretty strange ^

**Comment by liggitt** [comment]
> @liggitt This looks pretty strange

indeed... that comes from https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/noderestriction/admission.go#L211

**Comment by luxas** [comment]
@liggitt It's not the first time I see users reporting that... I can't really say what the problem is
Maybe we should do `%q` instead of `%s` consistently?

**Comment by zhangqx2010** [comment]
Thanks for update! @luxas @liggitt 
You bro really throw the right clue to me. 
For security reason I hidden the real hostname for my servers.
In UAT env, my servers hostname is upper case while in kubelet logs I saw the name is lower case.
So at this time I changed my hostname to lower case and tried kubeadm join command, the cluster was set up.

So my issue is solved. (you can choose close this issue now)
But I don't the reason why by design hostname is changed to lower case for resgister. In 1.6 that works fine.
I suggest using exact hostname instead of lower-cased hostname so that it won't be confuzing.
Or if there is reason to desgin lower-cased hostname when registering, hopefully you can tell me. :)

**Comment by liggitt** [comment]
Node API objects names must be lower-case, so the hostname is lower-cased to comply with the API validation.

**Comment by liggitt** [comment]
> @liggitt It's not the first time I see users reporting that

@luxas, it seems likely these are upgraded installations from the previous version, where the master node client cert was generated with a non-lowercased username. I thought kubeadm upgrades were not supported from 1.6 to 1.7.

In any case, a check should be done as part of that phase to ensure the cert is valid (has not expired, has the expected signer, username, and groups)

**Comment by luxas** [comment]
@liggitt Manual upgrades from v1.6->v1.7 are supported.
Automated upgrades coming in v1.7: https://docs.google.com/document/d/1PRrC2tvB-p7sotIA5rnHy5WAOGdJJOIXPPv23hUFGrY/edit#

**Comment by liggitt** [comment]
> Manual upgrades from v1.6->v1.7 are supported.

What's involved in a manual upgrade? Where is that documented? Does it involve removing/regenerating the credentials and manifests that were modified in 1.7?

**Comment by zhangqx2010** [comment]
Also when kubeadm 1.7 doc release, lower-cased hostname may described as a best practice.

**Comment by luxas** [comment]
@liggitt https://kubernetes.io/docs/tasks/administer-cluster/kubeadm-upgrade-1-7/
Credentials are not modified in any way.

However, an upgrade wasn't the case here as he used v1.7 from `init` time. In any case, what occured here will be fixed with: https://github.com/kubernetes/kubernetes/pull/48594
