### ISSUE TITLE
GPU tests consistently failing in 1.7 branch

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#48694]
https://k8s-testgrid.appspot.com/release-1.7-blocking#gce-gpu-1-7

They started failing around 07/07/2017.

@vishh @davidopp

**Comment by cmluciano** [comment]
@mindprince Is this still awaiting the new gcloud sdk release?

**Comment by mindprince** [comment]
These are GCE GPU tests. These are unrelated to gcloud release (that's for GKE).

I think something is wrong with the test setup, the gce gpu tests are passing on the master branch: https://k8s-testgrid.appspot.com/google-gce#gce-gpu

On the 1.7 branch, the test grid is showing a lot of unrelated tests being run and the GPU tests are not being run: 

@krzyzacy Did something change in how we run 1.7 tests?

**Comment by krzyzacy** [comment]
/assign

caused by https://github.com/kubernetes/test-infra/commit/1aedc7b48d027c789a84ed412ab8ed1e55fa6e15

**Comment by mindprince** [comment]
The last passing build log has GINKGO_TEST_ARGS=--ginkgo.focus=\[Feature:GPU\].
The failing build log doesn't have this environment variable set.

Trying to find out why.

**Comment by krzyzacy** [comment]
/close
close via https://github.com/kubernetes/test-infra/issues/3411
