### ISSUE TITLE
Headless service can not using node port , so it can not to using cloudprovider LB. 

### ISSUE THREAD

**Issue by yan234280533** [kubernetes/kubernetes#48692]
We use headless service to deploy stateful resource. The stateful resource is deploy ok. But we found that the headless service can not  support node port and LoadBalance service type. So it can not support be called through LB.

How can we to solve it?

**Comment by xiangpengzhao** [comment]
There is no LB for headless service. Why do you need LB for a headless service? Any more details about your use case?

See: https://kubernetes.io/docs/concepts/services-networking/service/#headless-services

/sig network

**Comment by thockin** [comment]
Headless Services can not use LBs.  The LB set can change dynamically, and allocating external IPs is not possible in that scale.  If you have a relatively static deployment, you can use a service per backend.
