### ISSUE TITLE
Apiserver request logger panicking on post/put/delete requests in kubemark-scale

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#48700]
kubemark-scale has been failing since run 506 (almost 5 days now). Both load and density tests are failing some requests to create/scale/delete RCs and services with msgs like these:

```
I0707 15:36:44.057] Jul  7 15:36:44.056: INFO: Unexpected error occurred: Error creating replication controller: Post https://104.198.188.213/api/v1/namespaces/e2e-tests-load-30-nodepods-20-4cts4/replicationcontrollers: stream error: stream ID 37; INTERNAL_ERROR
...
I0707 18:51:04.466] Jul  7 18:51:04.465: INFO: Unexpected error occurred: error while scaling RC load-small-6613 to 4 replicas: Scaling the resource failed with: Put https://104.198.188.213/api/v1/namespaces/e2e-tests-load-30-nodepods-14-q0dvg/replicationcontrollers/load-small-6613: stream error: stream ID 185; INTERNAL_ERROR; Current resource version 14448933
...
I0708 02:13:34.688] Jul  8 02:13:34.687: INFO: Unexpected error occurred: Delete https://104.198.188.213/api/v1/namespaces/e2e-tests-load-30-nodepods-26-z9shq/services/load-small-12625-svc: stream error: stream ID 74505; INTERNAL_ERROR
```

cc @kubernetes/sig-scalability-misc @gmarek @wojtek-t

**Comment by shyamjvs** [comment]
From the apiserver logs, it seems like something's wrong around the request logging:

```
I0707 22:36:43.975078       8 asm_amd64.s:514] POST /api/v1/namespaces/e2e-tests-load-30-nodepods-20-4cts4/replicationcontrollers: (21.716µs) 0 [[e2e.test/v1.8.0 (linux/amd64) kubernetes/7df2bce] 130.211.194.8:50438]
E0707 22:36:43.975312       8 runtime.go:66] Observed a panic: "multiple NewLogged calls!" (multiple NewLogged calls!)
E0707 22:36:44.033813       8 wrap.go:34] APIServer panic'd on POST /api/v1/namespaces/e2e-tests-load-30-nodepods-20-4cts4/replicationcontrollers: multiple NewLogged calls!
```

**Comment by shyamjvs** [comment]
cc @kubernetes/sig-api-machinery-bugs 

/assign @lavalamp 
Feel free to reassign as apt :)

**Comment by shyamjvs** [comment]
Fyi, here's the build-log I looked into:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/508/build-log.txt
and the master logs:
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/508/artifacts/kubemark-5000-kubemark-master/

**Comment by lavalamp** [comment]
It appears that the events etcd cluster is misconfigured or down. Otherwise apiserver looks OK.

I am not sure where you got the `Observed a panic: "multiple NewLogged calls!" (multiple NewLogged calls!)` line from, it doesn't appear in the apiserver log you linked.

**Comment by shyamjvs** [comment]
@lavalamp The apiserver.log is very big (~23GB) and it takes super long to load, so searching in browser doesn't work well. I just downloaded it  and verified that we do have such logs:

```
shyamjvs@shyamjvs:~/Pictures$ grep "multiple NewLogged calls!" kube-apiserver.log | head -20
E0707 16:44:11.604086       8 runtime.go:66] Observed a panic: "multiple NewLogged calls!" (multiple NewLogged calls!)
...
E0707 16:44:11.615904       8 wrap.go:34] APIServer panic'd on PATCH /api/v1/nodes/hollow-node-79qdg/status: multiple NewLogged calls!
E0707 16:44:11.616134       8 runtime.go:66] Observed a panic: "multiple NewLogged calls!" (multiple NewLogged calls!)
E0707 16:44:11.616648       8 runtime.go:66] Observed a panic: "multiple NewLogged calls!" (multiple NewLogged calls!)
E0707 16:44:11.616794       8 wrap.go:34] APIServer panic'd on PATCH /api/v1/nodes/hollow-node-0tk8h/status: multiple NewLogged calls!
E0707 16:44:11.616892       8 wrap.go:34] APIServer panic'd on PATCH /api/v1/nodes/hollow-node-nk9vd/status: multiple NewLogged calls!
```

And I've checked the etcd-events logs and everything seems ok with it (like before). I'm almost sure the problem is in apiserver as PATCH node-status, POST pod-bindings, etc are failing:

```
E0707 16:45:12.639921       8 wrap.go:34] APIServer panic'd on POST /api/v1/namespaces/e2e-tests-density-30-48-bjp03/pods/density150000-47-234aaaf4-632f-11e7-87d9-0242ac110003-d2w0x/binding: multiple NewLogged calls!
E0707 16:45:12.734797       8 wrap.go:34] APIServer panic'd on POST /api/v1/namespaces/e2e-tests-density-30-48-bjp03/pods/density150000-47-234aaaf4-632f-11e7-87d9-0242ac110003-xzqk4/binding: multiple NewLogged calls!
E0707 16:45:12.739518       8 wrap.go:34] APIServer panic'd on POST /api/v1/namespaces/e2e-tests-density-30-48-bjp03/pods/density150000-47-234aaaf4-632f-11e7-87d9-0242ac110003-q2mn8/binding: multiple NewLogged calls!
```

**Comment by shyamjvs** [comment]
Also the test is failing due to failure responses on create RC requests. It seems to be something around apiserver's client-side logic rather than etcd side (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/filters/wrap.go#L34).

**Comment by shyamjvs** [comment]
Reassigning it to you. Feel free to give it back as apt :)

**Comment by lavalamp** [comment]
hm, I am not sure why vim didn't find that. grepping seems to work.

**Comment by lavalamp** [comment]
I filed https://github.com/kubernetes/kubernetes/issues/48782

I think the issue is being triggered by having more requests in flight than allowed. I think there is a flag that can be set higher, or you can try to figure out what is causing the big increase in requests.

**Comment by shyamjvs** [comment]
@lavalamp The issue is not due to 429s. We have them happening all the time during scale tests (even before this failure). However they were handled gracefully. After digging up a bit it seems like the apiserver panic'ing is indeed the root cause, as it results in the response code being 0 which makes the e2e.test client think that it failed to create stuff.

**Comment by shyamjvs** [comment]
Looking at the diff of the commits when this started failing (https://github.com/kubernetes/kubernetes/compare/bce32b66c...9dd6a935fc58a7)

**Comment by shyamjvs** [comment]
All of them seem fine except PR #48445 (cc @deads2k @sttts ) which I'm almost 100% sure is the reason for this.
IIUC moving the PanicRecovery handler to after the MaxInflight handler is causing NewLogged to be called twice (while previously it was called only in MaxInflight).

**Comment by shyamjvs** [comment]
I think we can get rid of the logging in inflight handler now that PanicRecovery does it anyway at the end. Will send a PR for this.
