### ISSUE TITLE
Client TCP connections have to wait full timeout when set of endpoints goes from empty to non-empty

### ISSUE THREAD

**Issue by fasaxc** [kubernetes/kubernetes#48719]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

* I started a TCP client and server pod in parallel.  
* The client tries to access the server through a service IP
* Client manages to get its SYN packet sent before kube-proxy finishes setting up the NAT rules for the service.  
* The first packet establishes a conntrack entry for the TCP connection but the conntrack entry isn't NATted.
* All subsequent SYN retries get blackholed rather than NATted.
* Client waits for connection timeout.
* Subsequent TCP connections get NATted correctly.

We hit this while testing Calico with the k8s e2e's but doing the stop/continue trick with calico to slow down our policy rendering doesn't reproduce the issue; only preventing the NAT rule from being in place seems to have an effect:  https://github.com/projectcalico/felix/issues/1490

This issue is closely related, for UDP: https://github.com/kubernetes/kubernetes/issues/48370. However, the impact for UDP is more severe due to the lack of a connection timeout.

**What you expected to happen**:

Ideally, the initial TCP connection should connect as soon as the NAT rules are inserted.  Failing that, it'd be good to get a timely rejection rather than sending the traffic into a black hole.  

Flushing the (TCP) conntrack entries for a service IP as described in https://github.com/kubernetes/kubernetes/issues/48370 may work to fix this.  I also noticed there was an iptables rule that looks like it was designed to help in this case but it only applies in the OUTPUT chain: `-A KUBE-SERVICES -d 10.102.151.4/32 -p tcp -m comment --comment "default/nginx: has no endpoints" -m tcp --dport 80 -j REJECT --reject-with icmp-port-unreachable`.

**How to reproduce it (as minimally and precisely as possible)**:

* send `kube-proxy` a SIGSTOP to pause it
* create server (e.g. nginx) pod
* create client (e.g. busybox) pod
* create service for server pod
* from client, try to `wget` the server via its service
* send `kube-proxy` a SIGCONT
* should have a conntrack entry with orig src/dst = client/service and reply src/dst = service/client; wget should time out
* subsequent wget should return quickly

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7
- Cloud provider or hardware configuration**:  GCE
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux smc-ubuntu 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Others:

**Comment by bowei** [comment]
@freehan seems like another use case for flushing the conntrack entry?

**Comment by freehan** [comment]
`KUBE-SERVICES` is also attached to `PREROUTING`. So if the iptables rules for the service are present, it should work. 

Correct me if I am wrong, I feel this mostly happens between the gap of service creation and the actual iptables rule got installed. 

I think we should be conservative about flushing TCP entries. I do not want to disrupt service accidentally. One real solution is to add a service status field to indicate whether the service is fully implemented, but that gets very complicated.

**Comment by fasaxc** [comment]
> KUBE-SERVICES is also attached to PREROUTING

@freehan Are you sure about that?  It's not what I was seeing. However, I think I tested _that_ behaviour on 1.6.6 (whatever GKE had available at the time), so it could have been added in 1.7.

**Comment by freehan** [comment]
@fasaxc 
Check the `nat` table.

**Comment by fasaxc** [comment]
@freehan `nat.PREROUTING`does jump to `nat.KUBE-SERVICES` but that ends up being a no-op because there are no entries in the per-endpoint chain.  The `REJECT` rule is in `filter.KUBE-SERVICES` and I don't see that being hit.

On GKE, with kubenet (or on a manually set-up cluster with Calico), my test packets hit `filter.FORWARD`, which doesn't link to `filter.KUBE-SERVICES`.  If I manually add a link there, my connection is dropped cleanly:

```
sudo iptables -I FORWARD -j KUBE-SERVICES
```

Test pod now sees:
```
/ # wget nginx
Connecting to nginx (10.59.241.106:80)
wget: can't connect to remote host (10.59.241.106): Connection refused
```

Hooking the FORWARD chain may not work with Calico out-of-the-box, since Calico also hooks the forward chain to implement policy.  We may need to tweak Calico's config when using it with k8s to let packets fall through to the KUBE-SERVICES chain.  Please give me a heads up if you think that's the right approach so I can make sure Calico is in sync.

My full `iptables-save` output for the host with my client pod is below. 
```
$ sudo iptables-save
# Generated by iptables-save v1.4.21 on Thu Jul 13 09:16:20 2017
*nat
:PREROUTING ACCEPT [4:256]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [1:60]
:POSTROUTING ACCEPT [1:60]
:DOCKER - [0:0]
:KUBE-MARK-DROP - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-NODEPORTS - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-SEP-4ZJ6JMKFTAQL2QGU - [0:0]
:KUBE-SEP-A65DVPHOGKZU7WYW - [0:0]
:KUBE-SEP-LDS3E5PXDWAH3XIG - [0:0]
:KUBE-SEP-M3M7BU5YYKAXTMCW - [0:0]
:KUBE-SEP-MR6ZLD7YDNCOEJTJ - [0:0]
:KUBE-SEP-RLJH2MB6ZDFDUPGX - [0:0]
:KUBE-SEP-USFKHRZCUFG7PX7B - [0:0]
:KUBE-SEP-YJEHVO2LCBHZXWHD - [0:0]
:KUBE-SERVICES - [0:0]
:KUBE-SVC-4N57TFCL4MD7ZTDA - [0:0]
:KUBE-SVC-BJM46V3U5RZHCFRZ - [0:0]
:KUBE-SVC-ERIFXISQEP7F7OF4 - [0:0]
:KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
:KUBE-SVC-TCOU7JCQXEZGVUNU - [0:0]
:KUBE-SVC-XGLOHA7QRQ3V22RZ - [0:0]
:KUBE-SVC-XP4WJ6VSLGWALMW5 - [0:0]
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A POSTROUTING ! -d 10.0.0.0/8 -m comment --comment "kubenet: SNAT for outbound traffic from cluster" -m addrtype ! --dst-type LOCAL -j MASQUERADE
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-NODEPORTS -p tcp -m comment --comment "kube-system/default-http-backend:http" -m tcp --dport 32588 -j KUBE-MARK-MASQ
-A KUBE-NODEPORTS -p tcp -m comment --comment "kube-system/default-http-backend:http" -m tcp --dport 32588 -j KUBE-SVC-XP4WJ6VSLGWALMW5
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE
-A KUBE-SEP-4ZJ6JMKFTAQL2QGU -s 10.56.0.4/32 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-MARK-MASQ
-A KUBE-SEP-4ZJ6JMKFTAQL2QGU -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp" -m tcp -j DNAT --to-destination 10.56.0.4:53
-A KUBE-SEP-A65DVPHOGKZU7WYW -s 10.56.1.6/32 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-MARK-MASQ
-A KUBE-SEP-A65DVPHOGKZU7WYW -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp" -m tcp -j DNAT --to-destination 10.56.1.6:53
-A KUBE-SEP-LDS3E5PXDWAH3XIG -s 10.56.0.4/32 -m comment --comment "kube-system/kube-dns:dns" -j KUBE-MARK-MASQ
-A KUBE-SEP-LDS3E5PXDWAH3XIG -p udp -m comment --comment "kube-system/kube-dns:dns" -m udp -j DNAT --to-destination 10.56.0.4:53
-A KUBE-SEP-M3M7BU5YYKAXTMCW -s 35.184.192.70/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
-A KUBE-SEP-M3M7BU5YYKAXTMCW -p tcp -m comment --comment "default/kubernetes:https" -m recent --set --name KUBE-SEP-M3M7BU5YYKAXTMCW --mask 255.255.255.255 --rsource -m tcp -j DNAT --to-destination 35.184.192.70:443
-A KUBE-SEP-MR6ZLD7YDNCOEJTJ -s 10.56.1.6/32 -m comment --comment "kube-system/kube-dns:dns" -j KUBE-MARK-MASQ
-A KUBE-SEP-MR6ZLD7YDNCOEJTJ -p udp -m comment --comment "kube-system/kube-dns:dns" -m udp -j DNAT --to-destination 10.56.1.6:53
-A KUBE-SEP-RLJH2MB6ZDFDUPGX -s 10.56.1.3/32 -m comment --comment "kube-system/kubernetes-dashboard:" -j KUBE-MARK-MASQ
-A KUBE-SEP-RLJH2MB6ZDFDUPGX -p tcp -m comment --comment "kube-system/kubernetes-dashboard:" -m tcp -j DNAT --to-destination 10.56.1.3:9090
-A KUBE-SEP-USFKHRZCUFG7PX7B -s 10.56.1.2/32 -m comment --comment "kube-system/default-http-backend:http" -j KUBE-MARK-MASQ
-A KUBE-SEP-USFKHRZCUFG7PX7B -p tcp -m comment --comment "kube-system/default-http-backend:http" -m tcp -j DNAT --to-destination 10.56.1.2:8080
-A KUBE-SEP-YJEHVO2LCBHZXWHD -s 10.56.0.5/32 -m comment --comment "kube-system/heapster:" -j KUBE-MARK-MASQ
-A KUBE-SEP-YJEHVO2LCBHZXWHD -p tcp -m comment --comment "kube-system/heapster:" -m tcp -j DNAT --to-destination 10.56.0.5:8082
-A KUBE-SERVICES ! -s 10.56.0.0/14 -d 10.59.240.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.59.240.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
-A KUBE-SERVICES ! -s 10.56.0.0/14 -d 10.59.245.136/32 -p tcp -m comment --comment "kube-system/default-http-backend:http cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.59.245.136/32 -p tcp -m comment --comment "kube-system/default-http-backend:http cluster IP" -m tcp --dport 80 -j KUBE-SVC-XP4WJ6VSLGWALMW5
-A KUBE-SERVICES ! -s 10.56.0.0/14 -d 10.59.245.9/32 -p tcp -m comment --comment "kube-system/heapster: cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.59.245.9/32 -p tcp -m comment --comment "kube-system/heapster: cluster IP" -m tcp --dport 80 -j KUBE-SVC-BJM46V3U5RZHCFRZ
-A KUBE-SERVICES ! -s 10.56.0.0/14 -d 10.59.250.22/32 -p tcp -m comment --comment "kube-system/kubernetes-dashboard: cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.59.250.22/32 -p tcp -m comment --comment "kube-system/kubernetes-dashboard: cluster IP" -m tcp --dport 80 -j KUBE-SVC-XGLOHA7QRQ3V22RZ
-A KUBE-SERVICES ! -s 10.56.0.0/14 -d 10.59.240.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.59.240.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SERVICES ! -s 10.56.0.0/14 -d 10.59.240.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.59.240.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
-A KUBE-SERVICES ! -s 10.56.0.0/14 -d 10.59.241.106/32 -p tcp -m comment --comment "default/nginx: cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.59.241.106/32 -p tcp -m comment --comment "default/nginx: cluster IP" -m tcp --dport 80 -j KUBE-SVC-4N57TFCL4MD7ZTDA
-A KUBE-SERVICES -m comment --comment "kubernetes service nodeports; NOTE: this must be the last rule in this chain" -m addrtype --dst-type LOCAL -j KUBE-NODEPORTS
-A KUBE-SVC-BJM46V3U5RZHCFRZ -m comment --comment "kube-system/heapster:" -j KUBE-SEP-YJEHVO2LCBHZXWHD
-A KUBE-SVC-ERIFXISQEP7F7OF4 -m comment --comment "kube-system/kube-dns:dns-tcp" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-4ZJ6JMKFTAQL2QGU
-A KUBE-SVC-ERIFXISQEP7F7OF4 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-SEP-A65DVPHOGKZU7WYW
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m recent --rcheck --seconds 10800 --reap --name KUBE-SEP-M3M7BU5YYKAXTMCW --mask 255.255.255.255 --rsource -j KUBE-SEP-M3M7BU5YYKAXTMCW
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -j KUBE-SEP-M3M7BU5YYKAXTMCW
-A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-LDS3E5PXDWAH3XIG
-A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns" -j KUBE-SEP-MR6ZLD7YDNCOEJTJ
-A KUBE-SVC-XGLOHA7QRQ3V22RZ -m comment --comment "kube-system/kubernetes-dashboard:" -j KUBE-SEP-RLJH2MB6ZDFDUPGX
-A KUBE-SVC-XP4WJ6VSLGWALMW5 -m comment --comment "kube-system/default-http-backend:http" -j KUBE-SEP-USFKHRZCUFG7PX7B
COMMIT
# Completed on Thu Jul 13 09:16:20 2017
# Generated by iptables-save v1.4.21 on Thu Jul 13 09:16:20 2017
*mangle
:PREROUTING ACCEPT [11674222:7161295983]
:INPUT ACCEPT [4297253:3207160973]
:FORWARD ACCEPT [7376967:3954134060]
:OUTPUT ACCEPT [4563430:514996387]
:POSTROUTING ACCEPT [11940387:4469130179]
COMMIT
# Completed on Thu Jul 13 09:16:20 2017
# Generated by iptables-save v1.4.21 on Thu Jul 13 09:16:20 2017
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT DROP [0:0]
:DOCKER - [0:0]
:DOCKER-ISOLATION - [0:0]
:KUBE-FIREWALL - [0:0]
:KUBE-METADATA-SERVER - [0:0]
:KUBE-SERVICES - [0:0]
-A INPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A INPUT -j KUBE-FIREWALL
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -j ACCEPT
-A INPUT -p udp -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -p tcp -j ACCEPT
-A FORWARD -p udp -j ACCEPT
-A FORWARD -p icmp -j ACCEPT
-A FORWARD -d 169.254.169.254/32 -p tcp -m tcp --dport 80 -j KUBE-METADATA-SERVER
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -j KUBE-FIREWALL
-A OUTPUT -m state --state NEW,RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A DOCKER-ISOLATION -j RETURN
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
-A KUBE-SERVICES -d 10.59.241.106/32 -p tcp -m comment --comment "default/nginx: has no endpoints" -m tcp --dport 80 -j REJECT --reject-with icmp-port-unreachable
COMMIT
# Completed on Thu Jul 13 09:16:20 2017
```

**Comment by freehan** [comment]
I see. In summary, appending `KUBE-SERVICES` chain to `FORWARD` in `filter` table will solve the problem. 

Not sure if there is any side effect. Should be a easy one line chanage:
https://github.com/kubernetes/kubernetes/blob/release-1.7/pkg/proxy/iptables/proxier.go#L1034

**Comment by thockin** [comment]
The question is what "correct" behavior is for a service with no endpoints - ICMP reject or TCP retry?  I assumed retry, but I could be convinced.

**Comment by fasaxc** [comment]
Is there any mileage in using `-j REJECT --reject-with tcp-reset`?  That would simulate a closed port, which seems "right" to me if there are no services backing an endpoint.  (It's as if the service wasn't running on the "host" addressed by the service's IP.)

My only problem with TCP retry is the pragmatic one that the retries get blackholed by the stale conntrack entry.

**Comment by chino** [comment]
I would think that immediately rejecting seems better from a user experience/debugging perspective of least surprise?  I also imagine it would create unnecessary/variable delays for code that's sitting in loops waiting to reach a service?

For UDP there is no handshake mechanism so the user is completely blind that anything is failing without some kind of icmp response I believe?

In Calico (and I imagine others as well) if nothing handles the packet then it ends up routing to the default gateway which seems completely wrong and again very confusing?

I agree that tcp-reset seems more natural.

**Comment by cmluciano** [comment]
@caseydavenport @dcbw Any thoughts on this? I'm not sure if this is something podreadiness is meant to solve, but it seems like there are a couple of iptables enhancements we might be able to make.

**Comment by uxon123** [comment]
If this is how it works currently, is there a way to workaround this? Can I configure TCP timeout to a smaller value (5-10s instead of 2 minutes), so that my TCP clients wouldn't be waiting so long, when there are already pods which can serve them?

**Comment by bowei** [comment]
It does seems to be a better experience to do an active reject rather than a passive "eat the packet". (RST for TCP, ICMP for UDP) as it matches the typical situation (there is no server) which for a single server would result in a RST if the client connects too early.

@thockin 
Are there other motivations for not NACKing the connection? The TCP SYN retry window is typically small, so the the current setting would mostly only benefit the situation where you just happen to try to connect when a server is starting up.

**Comment by marwinski** [comment]
We are experiencing the same issue with Gardener on the Azure platform (I am quite sure it also hits AKS but they may not know that yet). We found this only after investigating why our clusters were sometime behaving sloppy.

Problem is that one component in AKS makes quite aggressive re-use of ports (we are in contact with Azure to figure out why that is happening - in general however this does not appear to be a problem). So, when the last pod backing a service goes down due to a crash, update, restart (in our case the API server) and a connection attempt comes at that time a conntrack entry is created and the SYN is forwarded. As ports are re-used, this broken entry can remain for hours blocking any connection attempt during that period of time as ports are re-used and the 2 minute default timeout in the conntrack table is always reset. 

I do fully agree with @fasaxc and @chino: rejecting this connection attempt and not being rewarded with a stale conntrack entry would solve the above issue and appears to be the right thing to do.

**Comment by khenidak** [comment]
Adding more context:
Test approach:
1. A simple nginx deployment, with a readiness probe that always fail
```
...
 readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3223
            scheme: HTTP
...
```
2. Exposed as `type=LoadBalancer`
3. Service will never have an endpoint 
```
$ kubectl get endpoints n01
NAME      ENDPOINTS   AGE
n01                   7m
```
3. Service will get an both `ClusterIP` and `External-IP`
```
$ kubectl get svc n01
NAME      TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)        AGE
n01       LoadBalancer   10.0.245.192   <<someip>>   80:32707/TCP   9m
```

Test Steps:
1. Curling from the cluster on service ip will result into `connection refused`
```
$ curl 10.0.245.192
curl: (7) Failed to connect to 10.0.245.192 port 80: Connection refused
```  

The reason behind are these rules:
```
-A KUBE-EXTERNAL-SERVICES -p tcp -m comment --comment "default/n01: has no endpoints" -m addrtype --dst-type LOCAL -m tcp --dport 32707 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.0.245.192/32 -p tcp -m comment --comment "default/n01: has no endpoints" -m tcp --dport 80 -j REJECT --reject-with icmp-port-unreachable
```

> basically `Node Port` and `ClusterIP` are both correctly reject with `icmp-port-unreachable`

2. Curling external IP will result in a hang.
The reason of this hang is `azure` uses `direct server return` in other words traffic hits the node, not on `Node Port` but on `external-ip:service-port`; there are no rules that rejects this traffic if there are no service endpoints, the traffic is just black holed.

> The above behavior will be in any cloud provider that uses `dsr`

4. One of the interesting things is the above behavior means that curling `external-ip:wrong-port` (in case of `dsr`) will also result in a hang not `icmp-port-unreachable` (which is consistent with curling a `ClusterIP:wrong-port`). I do believe we should keep this behavior for external services, but for internal we need reject with `cmp-port-unreachable`, maybe later.

Proposed solutions:
1. We need to merge https://github.com/kubernetes/kubernetes/pull/72879. with a little modification. 
   1. move the `reject` rule here https://github.com/kubernetes/kubernetes/pull/72879/files#diff-d51765b83fe795b469e8a86276b12dc9R911
    2. Make sure that the rule is removed once endpoints start to show up.

**Comment by thockin** [comment]
I independently found this same issue via another bug report.  Looking at the fix now, trying to add good e2e for it.

**Comment by spiffxp** [comment]
/milestone v1.14
We're entering [burndown](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14#burndown) and this looks relevant to the 1.14 release. Please `/milestone clear` if I am incorrect

**Comment by gianarb** [comment]
Hello,

I'm a bug triage shadow and I'd like to remind that code freeze is coming in 2 days (Friday, 8th March). :snowflake:  Is it still planned for this issue to be fixed for 1.14?

**Comment by soggiest** [comment]
We are in the middle of code freeze for 1.14. can we get some more reviews on this and someone assigned to work on it? 
@kubernetes/sig-network-bugs

**Comment by cmluciano** [comment]
@soggiest This should be fixed as soon as https://github.com/kubernetes/kubernetes/pull/74394 merges. It's mostly approved and is currently running through CI.
