### ISSUE TITLE
kubernetes packages differ for each build

### ISSUE THREAD

**Issue by bmwiedemann** [kubernetes/kubernetes#48710]
/kind bug

**What happened**:
```
/usr/bin/hyperkube
/usr/bin/kubeadm
/usr/src/kubernetes/platforms/linux/amd64/e2e.test
```
have a date+time string embedded in them in the format
2018-08-15T19:08:34Z
that differs for each build

**What you expected to happen**:
It should be possible to build reproducibly, generating identical binaries no matter when (and where)

**How to reproduce it (as minimally and precisely as possible)**:
on openSUSE do
```bash
osc checkout openSUSE:Factory/kubernetes
cd $_
osc build --keep-pkg=RPMS --vm-type=kvm
cd RPMS
unrpm kubernetes-kubeadm-1.6.1-0.x86_64.rpm
strings usr/bin/kubeadm | grep $(date +%Y-%m-%d)
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: 1.6.1
- OS: openSUSE (any)

proposed fix: #48708

**Comment by ixdy** [comment]
oh look, this bug.

I think the embedded date/time issues have been fixed, and we're addressing the manpage issues. @bmwiedemann are you aware of other issues not yet resolved?

**Comment by bmwiedemann** [comment]
/remove-lifecycle stale

sorry for missing the question earlier.

I have tested kubernetes-1.9.3 and got different diffs now:
http://rb.zq1.de/compare.factory-20180228/kubernetes-compare.out

## man pages
there one side of the diff is
```diff
+This file is autogenerated, but we've stopped checking such files into the
+repository to reduce the need for rebases. Please run hack/generate\-docs.sh to
+populate this file.
```

and the other side is a properly rendered man page.

`docs/admin/cloud-controller-manager.md` shows similar diffs

This kind of diff usually indicates some race problem with build scripts, build dependencies and/or parallelism

we even explicitly call `./hack/generate-docs.sh` in
https://build.opensuse.org/package/view_file/openSUSE:Factory/kubernetes/kubernetes.spec

Not sure if we do something wrong on the openSUSE packaging side or if it is an upstream kubernetes problem



For reproducing this kind of problem, the reproducer in the top post needs some added `-j2` or `-j3` option, e.g.
```
osc build -j2 --keep-pkg=RPMS --vm-type=kvm
```
with the expectation that the build result should not depend on the number of CPUs in the build machine and the ordering chosen by the kernel's process scheduler.


## build IDs / future Copyright

Additionally, the build-ids of kubeadm and hyperkube differ between builds. This likely comes from diffs in source files like this:
```diff
--- /home/abuild/rpmbuild/BUILD/kubernetes-1.9.3+d2835416544f298c919e2ead3be3d0864b52323b/cmd/kubeadm/app/apis/kubeadm/v1alpha1/zz_generated.conversion.go 2018-03-12 05:06:42.389095313 +0000
+++ /home/abuild/rpmbuild/BUILD/kubernetes-1.9.3+d2835416544f298c919e2ead3be3d0864b52323b/cmd/kubeadm/app/apis/kubeadm/v1alpha1/zz_generated.conversion.go 2033-04-13 18:22:48.122239818 +0000
@@ -1,7 +1,7 @@
 // +build !ignore_autogenerated

 /*
-Copyright 2018 The Kubernetes Authors.
+Copyright 2033 The Kubernetes Authors.

 Licensed under the Apache License, Version 2.0 (the "License");
```

On this topic see also https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated
and maybe check with a copyright-lawyer.
IANAL+IMHO building code does not warrant updating a copyright.

**Comment by bmwiedemann** [comment]
/remove-lifecycle stale
issue still needs work. See comment from Mar 12

**Comment by ixdy** [comment]
I believe the generated files no longer include a copyright date.

The man pages might still be problematic.

**Comment by ixdy** [comment]
ref https://github.com/kubernetes/kubernetes/pull/59172 for generated files.

**Comment by bmwiedemann** [comment]
More testing showed that kubernetes builds reproducibly when replacing /dev/random and urandom with /dev/zero so something is explicitly putting randomness in the go-buildid section. Not just a hash of something that happens to change for other reasons.

**Comment by bmwiedemann** [comment]
With kubernetes-1.11.1 
the random build-ids are still there
and there is a new ordering issue in many man-pages:
```diff
/usr/share/man/man1/kubectl-create-rolebinding.1        2018-09-16
@@ -39,7 +39,7 @@

 .PP
 \fB\-o\fP, \fB\-\-output\fP=""
-    Output format. One of: json|yaml|name|template|go\-template|go\-template\-file|templatefile|jsonpath|jsonpath\-file.
+    Output format. One of: json|yaml|name|go\-template|go\-template\-file|templatefile|template|jsonpath|jsonpath\-file.
```

**Comment by dims** [comment]
related to https://github.com/kubernetes/release/issues/637
