### ISSUE TITLE
Enhance the codegen script within the staging sample apiserver to work with multiple groups and versions

### ISSUE THREAD

**Issue by maleck13** [kubernetes/kubernetes#48714]
> /kind feature

The codegen script located in ```staging/src/k8s.io/sample-apiserver/hack/update-codegen.sh``` was updated as part of the following PR
https://github.com/kubernetes/kubernetes/pull/48549
This PR fixed several issues with the script but further enhancements could be made:

1) It currently only works with a single group and version. It would be better if it could be used with multiple groups and versions.

2) It uses a trap on exit to remove generated binaries. Instead it should use  temp dir for these generated binaries and remove the trap on exit.

@sttts ping issue for follow up to https://github.com/kubernetes/kubernetes/pull/48549

**Comment by sttts** [comment]
@maleck13 are you working on this? Would assign the issue then.

**Comment by maleck13** [comment]
@sttts Happy to have it assigned to me. However I cannot work on it immediately

**Comment by sttts** [comment]
Implemended in https://github.com/kubernetes/kubernetes/issues/48714
