### ISSUE TITLE
kubefed should emit error when passing invalid dns-provider 

### ISSUE THREAD

**Issue by henriquetruta** [kubernetes/kubernetes#48732]
/kind bug

**What happened**:
I've misspelled the dns-provider (put googlecloud-dns instead of google-clouddns) when running `kubefed init`
It successfully ran and said everything was ok. However, federation-control-plane pod entered in CrashLoopBackOff and I could only see the error in the pod's logs:
```F0710 20:15:37.946633       1 controllermanager.go:174] Cloud provider could not be initialized: unknown DNS provider "googlecloud-dns"```

**What you expected to happen**:
If any string different than 'google-clouddns', 'aws-route53' or 'coredns' is provided in `dns-provider`, kubefed should return an error to the client.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#22.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
