### ISSUE TITLE
pods have a bug of recreate hosts file.

### ISSUE THREAD

**Issue by rkasdf** [kubernetes/kubernetes#48745]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I'm using k8s 1.6.4, when I create a pod with more than one container, I add some hosts to the /etc/hosts when I start one of the container in the pod, but the hosts file changed at first but then change to the initial pods hosts.

**What you expected to happen**:
The hosts in the pod will keep changed at the lifetime of the pod.

**How to reproduce it (as minimally and precisely as possible)**:
1. create a pod with more than one container;
2. in a container use script to add hosts;
3. recreate the pod sometimes will reproduce the bug.

**Anything else we need to know?**:

func ensureHostsFile(fileName, hostIP, hostName, hostDomainName string) error {     
   if \_, err := os.Stat(fileName); os.IsExist(err) {     
   glog.V(4).Infof("kubernetes-managed etc-hosts file exits. Will not be recreated: %q", fileName)
   return nil
   }
 
I read the source code and find there is a bug in tag 1.6.7 pkg/kubelet/kubelet_pods.go 214-218.  You should use "\_, err := os.Stat(fileName); !os.IsNotExist(err)" instead of the source code. So multiple containers  in a pods will not  recreate the hosts file again.

**Environment**:
- Kubernetes version (use `kubectl version`):

 Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
I see the bug exist in all the versions before 1.7, but in version 1.7 you remove the check of recreate hosts file.

**Comment by rkasdf** [comment]
@kubernetes/sig-node-misc

**Comment by supereagle** [comment]
The same with issue #44473, has been fix by PR #45329, but not cherry-picked into release-1.6.  I will create  a PR to cherry pick this into release-1.6.

**Comment by supereagle** [comment]
This bug is not caused by the code mentioned by @rkasdf. 
Even this code has logical error, but it has no effect on the result: no matter whether the host file exists or not, it will always be recreated.

**Comment by rkasdf** [comment]
I know your point, I think this is important to provide a way for users who use k8s below version 1.7 to add hosts, but the recreating /etc/hosts will make the user who use scripts  adding hosts failed. Since you know the bug, I will close the issue.
