### ISSUE TITLE
Kubelet fails to download Infra-Pod from ECR

### ISSUE THREAD

**Issue by rmt** [kubernetes/kubernetes#48754]
/kind bug
/sig aws

**What happened**:

When trying to bootstrap an EC2 instance using docker images from ECR, every image works _except_ for the pod infra container image (as supplied to kubelet via the --pod-infra-container-image argument).  If I pre-download the image (docker login & docker pull), then it works.  Subsequent static pods configured by Kubelet, also using the same ECR registry, work fine.  Similarly, using the pod infra container image from gcr's public docker repo (clean install) results in it bootstrapping as expected, with all other images coming from the ECR registry.

**What you expected to happen**:

When running kubelet, if '--cloud-provider aws' is given, and the --pod-infra-container-image argument is pointing to an ECR-hosted image, then docker pull should be run with AWS-sourced credentials.

**How to reproduce it (as minimally and precisely as possible)**:

See above, plus the kubelet command:

`/usr/bin/kubelet --cgroup-driver=systemd --allow-privileged=true --cgroup-root=/ --cloud-provider=aws --pod-infra-container-image=gcr.io/google_containers/pause-amd64:3.0 --cluster-dns=100.64.0.10 --cluster-domain=cluster.local --enable-debugging-handlers=true --eviction-hard=memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5% --hostname-override=ip-10-123-216-51.eu-west-1.compute.internal --kubeconfig=/var/lib/kubelet/kubeconfig --network-plugin=cni --node-labels=kubernetes.io/role=master --non-masquerade-cidr=100.64.0.0/10 --pod-manifest-path=/etc/kubernetes/manifests --register-schedulable=true --register-with-taints=node-role.kubernetes.io/master=:NoSchedule --require-kubeconfig=true --v=2 --cni-bin-dir=/opt/cni/bin/ --cni-conf-dir=/etc/cni/net.d/`

(The above works.  Change --pod-infra-container-image to an ECR hosted image to replicate this)

**Anything else we need to know?**:

We're using IAM roles with the EC2 instances (and not hard-coded AWS credentials)

@kubernetes/sig-aws
@kubernetes/sig-node

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.4
- Cloud provider or hardware configuration**: aws
- OS (e.g. from /etc/os-release): CentOS Linux 7
- Kernel (e.g. `uname -a`):3.10.0-514.21.2.el7.x86_64
- Install tools: Custom Puppet
- Others:

**Comment by franklin-stripe** [comment]
I ran into this issue myself, and discovered that the bug is fixed in 1.8+. Previously the infra pod docker pull was not using a credential provider: https://github.com/kubernetes/kubernetes/commit/4d5d97438b737f798709899746d8007e2291f7db
