### ISSUE TITLE
No InternalIP when upgrading to kubernetes >= 1.6.5 with VSphere Cloud Provider

### ISSUE THREAD

**Issue by cbonte** [kubernetes/kubernetes#48760]
**BUG REPORT**:

/kind bug

**What happened**:
After upgrading the kubernetes cluster from 1.6.4 with the VSphere Cloud Provider enabled to 1.6.5/1.6.6 or 1.6.7, the cluster nodes don't have anymore InternalIPs

```
# kubectl get node debug.k8s.debug-01 -o yaml
...
status:
  addresses:
  - address: 10.9.65.204
    type: ExternalIP
  - address: debug.k8s.debug-01
    type: Hostname
...
```

Several issues occur at this step.
For example, it breaks heapster with such an error :
```
E0711 12:59:05.000192       1 kubelet.go:282] Node debug.k8s.debug-01 has no valid hostname and/or IP address: debug.k8s.debug-01
```
**What you expected to happen**:
The node should have an InternalIP.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a 1 node kubernetes cluster in a VM, and enable the _vsphere_ cloud provider.

**Anything else we need to know?**:
with kubernetes 1.6.4 we get :
```
status:
  addresses:
  - address: 10.9.65.204
    type: InternalIP
  - address: debug.k8s.debug-01
    type: Hostname
```
Downgrading to 1.6.4 fixes the issue.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7+coreos.0", GitCommit:"c8c505ee26ac3ab4d1dff506c46bc5538bc66733", GitTreeState:"clean", BuildDate:"2017-07-06T17:38:33Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7+coreos.0", GitCommit:"c8c505ee26ac3ab4d1dff506c46bc5538bc66733", GitTreeState:"clean", BuildDate:"2017-07-06T17:38:33Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: vsphere
- OS (e.g. from /etc/os-release):
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`):
```
Linux debug.k8s.debug-01 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux
```
- Install tools:
- Others: It may be related to some changes around PR kubernetes#45201

@kubernetes/sig-cluster-ops-bugs @kubernetes/sig-network-bugs
/area platform/vsphere cloudprovider

**Comment by cbonte** [comment]
Performing some more tests on a mini instance outside of the production cluster, I think I've identified the issue.
The configuration required to start kubelet with the `--node-ip` option (otherwise the wrong IP/interface is used to communicate between nodes). The issue is triggered when this option is set.

The `vsphere` cloud provider looks OK. But the issue is located here :
https://github.com/kubernetes/kubernetes/blob/release-1.6/pkg/kubelet/kubelet_node_status.go#L407

When the `nodeIP` is not `nil`, the loop iterates on the node addresses and returns only the first one found. Since PR kubernetes#45201, the list always return en ExternalIP first.

I think the loop in `kubelet_node_status.go` should iterate on all the addresses to rebuild the list, so that it will include the ExternalIP and the InternalIP. Can someone confirm the analysis ?

**Comment by yastij** [comment]
ping @kerneltime

**Comment by cbonte** [comment]
Modifying the code like this solved the issue :
 ```diff
diff --git a/pkg/kubelet/kubelet_node_status.go b/pkg/kubelet/kubelet_node_status.go
index a0da169f6b..ce347523e9 100644
--- a/pkg/kubelet/kubelet_node_status.go
+++ b/pkg/kubelet/kubelet_node_status.go
@@ -405,15 +405,16 @@ func (kl *Kubelet) setNodeAddress(node *v1.Node) error {
 			return fmt.Errorf("failed to get node address from cloud provider: %v", err)
 		}
 		if kl.nodeIP != nil {
+			node.Status.Addresses = []v1.NodeAddress{}
 			for _, nodeAddress := range nodeAddresses {
 				if nodeAddress.Address == kl.nodeIP.String() {
-					node.Status.Addresses = []v1.NodeAddress{
-						{Type: nodeAddress.Type, Address: nodeAddress.Address},
-						{Type: v1.NodeHostName, Address: kl.GetHostname()},
-					}
-					return nil
+					node.Status.Addresses = append(node.Status.Addresses, v1.NodeAddress{Type: nodeAddress.Type, Address: nodeAddress.Address})
 				}
 			}
+			if len(node.Status.Addresses) > 0 {
+				node.Status.Addresses = append(node.Status.Addresses, v1.NodeAddress{Type: v1.NodeHostName, Address: kl.GetHostname()})
+				return nil
+			}
 			return fmt.Errorf("failed to get node address from cloud provider that matches ip: %v", kl.nodeIP)
 		}
```
which returns :
```yaml
status:
  addresses:
  - address: debug.k8s.debug-01
    type: Hostname
  - address: 10.9.65.204
    type: ExternalIP
  - address: 10.9.65.204
    type: InternalIP
```
I guess it can be done in a cleaner way, but it was to quickly test the fix.

**Comment by divyenpatel** [comment]
CC: @BaluDontu @luomiao @tusharnt

**Comment by luomiao** [comment]
@cbonte 
Thanks for filing this issue related to vSphere cloud provider.
I agree with your analysis.
It seems the current `setNodeAddress` function assumes that the IP address specified by user can only be InternalIP.
Your fix to `kubelet_node_status.go` is a better solution than work-around in cloud provider.

**Comment by cbonte** [comment]
Hi, what are the next steps to discuss about the PR ?
@luomiao Are you able to make some tests ?
