### ISSUE TITLE
OIDC with CiLogon - failing with --oidc-username-claim=email

### ISSUE THREAD

**Issue by dimm0** [kubernetes/kubernetes#48777]
/kind bug
/sig auth

**What happened**:
When using OIDC plugin with CiLogon for authentication and having api-server configured with "--oidc-username-claim=email", I get an error:

```
E0710 23:01:00.850970       7 authentication.go:58] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, [crypto/rsa: verification error, invalid bearer token, 'email_verified' claim not present]]]
```

CiLogon is not returning email_verified field, but according to the [example](http://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse) the email-verified field is optional and can default to false.

**What you expected to happen**:
If email_verified field is missing, treat it as false.

**How to reproduce it (as minimally and precisely as possible)**:
Configure the OIDC plugin with CiLogon according to the kubernetes docs
Configure api-server with "--oidc-username-claim=email" parameter
Try to authenticate

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-30T09:51:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration**:
Baremetal
- OS (e.g. from /etc/os-release): (server)
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
```

**Comment by thomastaylor312** [comment]
I also just ran into this issue while using Okta

**Comment by thomastaylor312** [comment]
This is happening right [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc.go#L243). I am willing to submit a patch for this if we are ok with defaulting it to `false`

**Comment by ericchiang** [comment]
This is a dup of https://github.com/kubernetes/kubernetes/issues/46806

**Comment by thomastaylor312** [comment]
Thanks for catching that @ericchiang

**Comment by ericchiang** [comment]
Going to close as a duplicate.
