### ISSUE TITLE
OIDC with CiLogon - client_id string failing because of ',' symbol

### ISSUE THREAD

**Issue by dimm0** [kubernetes/kubernetes#48776]
> /kind bug
> /sig auth

**What happened**:
When using OIDC plugin with CiLogon, the client-id is causing problems.
First, I can't add it to the client config file:

#kubectl config set-credentials user1  --auth-provider-arg=client-id="myproxy:oa4mp,2012:/client_id/<my_client_id_string>"

error: Error: invalid auth-provider-arg format: 2012:/client_id/<my_client_id_string>

The comma is causing it to fail, and everything works without the comma. I added it later to the config file manually.

Later, when trying to automatically refresh the otherwise working fine token, I'm getting the error from CiLogon:

```
Error Report - Apache Tomcat/7.0.77
------------
Error  : 500
Host   : cilogon.org
Servlet: accessToken
URL    : /oauth2/token

Exception
---------
javax.servlet.ServletException: no client id
    edu.uiuc.ncsa.myproxy.oa4mp.oauth2.servlet.OA2ExceptionHandler.handleException(OA2ExceptionHandler.java:74)
    edu.uiuc.ncsa.security.servlet.AbstractServlet.handleException(AbstractServlet.java:125)
    edu.uiuc.ncsa.security.servlet.AbstractServlet.doPost(AbstractServlet.java:161)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
```

Which makes me think it's a problem with comma in the client id string again.

**What you expected to happen**:
Expecting the string to be properly protected and not treated as an array.

**How to reproduce it (as minimally and precisely as possible)**:
kubectl config set-credentials user1 --auth-provider-arg=client-id="a,b" - fails
kubectl config set-credentials user1 --auth-provider-arg=client-id="ab" - works fine

Refresh token - create the OIDC provider with CiLogon according to kubernetes docs and try to refresh the token.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-30T09:51:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration**:
Baremetal
- OS (e.g. from /etc/os-release): (server)
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
```

**Comment by supereagle** [comment]
I think it is not a bug, but a usage error. `--auth-provider-arg` is an array for multiple values, which are separated by comma. So it is not recommended that the values contain commas.

```shell
# kubectl config set-credentials --help
Sets a user entry in kubeconfig 
......
Options:
      --auth-provider='': auth provider for the user entry in kubeconfig
      --auth-provider-arg=[]: 'key=value' arugments for the auth provider
```

**Comment by dimm0** [comment]
The OAuth spec is not prohibiting any symbols in the client-id string. And it's not working as an array with comma either..

I understand why --auth-provider-arg=client-id=a,b wouldn't work, but IMHO --auth-provider-arg=client-id="a,b" should be treated as a string

And the main problem is on the server side. It's working for verifying the existing token, but not working for refreshing one.

**Comment by wangxinnong** [comment]
You can pass the argument as the following:
'"client-id=myproxy:oa4mp,2012:/client_id/<my_client_id_string>"'
or:
`"client-id=myproxy:oa4mp,2012:/client_id/<my_client_id_string>"`
(double quotes are contained in single quotes or backquotes)

#kubectl config set-credentials user1 --auth-provider=oidc --auth-provider-arg='"client-id=myproxy:oa4mp,2012:/client_id/<my_client_id_string>"'

The kubeconfig will be created:
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users:
- name: user1
  user:
    auth-provider:
      config:
        client-id: myproxy:oa4mp,2012:/client_id/<my_client_id_string>
      name: oidc

**Comment by dimm0** [comment]
Found the source of problem: https://github.com/golang/oauth2/issues/244
