### ISSUE TITLE
Kubernetes pods logs file is not symlinked to docker-container logs

### ISSUE THREAD

**Issue by jeevarathinam-dhanapal** [kubernetes/kubernetes#48796]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
kubernetes pod logs are not linked to the respective docker container log file.
kubectl logs -f <pod-name> throws "no such file or directory" error

**What you expected to happen**:
Even after the kubelet restart, "kubectl logs -f <pod-name>"  should show the logs

**How to reproduce it (as minimally and precisely as possible)**:
1. Restart kubelet service without restarting docker service
2. kubectl logs -f <pod-name>

Note - Restarting the docker.service fixes the issue temporarily. 

**Anything else we need to know?**:
Docker inspect <container-id> gives the pod-log file details which is not linked to the container log mentioned in the inspect output

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.6
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): CoreOS 1409.6.0
- Kernel (e.g. `uname -a`):  x86_64 Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz GenuineIntel GNU/Linux
- Docker version : 1.12.6

**Comment by feiskyer** [comment]
Docker container's log file is linked at pod creation time, it should not change on restarting kubelet. Did your pod be also restarted after kubelet? Is there any error message in kubelet's log?

**Comment by jeevarathinam-dhanapal** [comment]
There is no error messages in the kubelet logs. After the kubelet restart, it looks like, the link is either broken or the pod is looking for logs in a file which is not created.

"kubectl logs -f kong-m90qh
failed to open log file "/var/log/pods/abc424df-4d8b-11e7-82ef-06a653f2b1ab/kong_6.log": open /var/log/pods/abc424df-4d8b-11e7-82ef-06a653f2b1ab/kong_6.log: no such file or directory"

**Comment by jeevarathinam-dhanapal** [comment]
bump
