### ISSUE TITLE
Kubelet tries to use system-wide http_proxy setting for communicating with local pods

### ISSUE THREAD

**Issue by ace13** [kubernetes/kubernetes#48792]
/kind bug

**What happened**:
An additional proxy server was set up for our internal Kubernetes cluster, to replace one that had been running as an internet-accessible Kubernetes node.
This means that the proxy no longer has access to the Kubernetes CIDRs, which the old one had.

At this point, liveness and readyness checks started failing for all pods, corresponding to entries in the proxy access log;
```
1499844148.511    998 10.133.0.10 TCP_MISS_ABORTED/000 0 GET http://10.254.73.2:10254/healthz - HIER_DIRECT/10.254.73.2 -
```

**What you expected to happen**:
Kubelet ignores proxy settings when trying to communicate with pods hosted on the local machine.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ cat /etc/systemd/system.conf.d/01-proxy-environment.conf 
[Manager]
DefaultEnvironment="http_proxy=http://proxy-server.localdomain:3128"
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.5.2
- Cloud provider or hardware configuration: Bare-metal
- OS (e.g. from /etc/os-release): CentOS Linux release 7.3.1611 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-514.26.2.el7.x86_64

**Comment by cmluciano** [comment]
@kubernetes/sig-network-misc

**Comment by duan-yue** [comment]
For merely livenessProbe, I find the proxy is set [here ](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/net/http.go#L64-L67), it only reads NO_PROXY and excludes ip in NO_PROXY.  So we can exclude all hosts who have the same cidr as k8s cluster.  If you think this solution is feasible, I would like to submit such a patch. @xiangpengzhao @cmluciano

**Comment by ace13** [comment]
If kubelet is able to append the cluster CIDR to its NO_PROXY variable itself then that would definitely solve the issue for me.

Certainly more appropriate than my current workaround of running a tainted k8s node on the proxy server.

**Comment by duan-yue** [comment]
It seems that we can not get CIDR through API in this issue #25533 . sad.

**Comment by 2rs2ts** [comment]
FYI it is not possible to use a CIDR in NO_PROXY. https://unix.stackexchange.com/questions/23452/set-a-network-range-in-the-no-proxy-environment-variable

**Comment by 2rs2ts** [comment]
Sorry, I am incorrect. It does work for kubelet, but not for curl. I figured my tests with curl were sufficient.

**Comment by liggitt** [comment]
> If kubelet is able to append the cluster CIDR to its NO_PROXY variable itself then that would definitely solve the issue for me.

kubelet cannot assume you don't want to go through the configured proxy in order to reach the pod network.

> FYI it is not possible to use a CIDR in NO_PROXY. https://unix.stackexchange.com/questions/23452/set-a-network-range-in-the-no-proxy-environment-variable

kubernetes components support CIDR in NO_PROXY. See https://github.com/kubernetes/kubernetes/pull/23003

**Comment by jayunit100** [comment]
> kubelet cannot assume you don't want to go through the configured proxy in order to reach the pod network.

@liggitt  it makes sense that right now we cannot do this.  In the future, could we make the proxy more configurable ? Example of where it would be nice to have this bifurcated traffic: some proxy's are slow.  I recently saw some sputtering performance in a control plane and , although I never confirmed, i noticed that this might be correlated to air-gapped kubernetes clusters that have proxying turned on...
