### ISSUE TITLE
AWS cloud provider doesn't support assuming roles

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#48814]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: It's not possible to configure the AWS cloud provider to assume a role

**What you expected to happen**: It should be possible to assume a role

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new EC2 VM using an assumed role such that only that role can see the VM
1. Set the environment variable `AWS_SDK_LOAD_CONFIG` to true
1. Set up `~/.aws/credentials` appropriately for a `default` profile with credentials
1. Set up `~/.aws/config` with another profile e.g. `foo` with `source_profile` and `role_arn` set appropriately
1. Set the environment variable `AWS_PROFILE` to `foo`
1. Run `hack/local-up-cluster.sh` or whatever method you prefer to start the cluster
1. You'll get an error that initializing the aws cloud provider failed because it couldn't describe its VM instance

**Anything else we need to know?**:
The AWS cloud provider supports the following credentials providers, in this [order](https://github.com/kubernetes/kubernetes/blob/9737b4118924be1fd2d862cf360a2d25813b1b2d/pkg/cloudprovider/providers/aws/aws.go#L688-L692):

1. environment variables for access key, secret access key, session token
1. ec2 metadata
1. shared credentials (~/.aws/credentials)

If you don't specify credentials providers when creating a session, it defaults to the following [logic](https://github.com/kubernetes/kubernetes/blob/9737b4118924be1fd2d862cf360a2d25813b1b2d/vendor/github.com/aws/aws-sdk-go/aws/session/session.go#L295-L338):

1. environment variables for access key, secret access key, session token
1. support for assuming a role
1. credentials from config files (~/.aws/credentials and/or ~/.aws/config)
1. remote credentials provider (ec2)

I'm wondering if it would make sense to either remove our hard-coded providers list and instead use the default logic from the session, or copy the logic from the session into the aws cloud provider (so we don't have a behavior change if/when we upgrade aws-sdk-go). Or if there's some better way, I'm all ears, as I am by no means an expert on this area. WDYT?

cc @jbeda @timothysc @mattmoyer @justinsb @rrati

**Comment by mattmoyer** [comment]
I think using the default credential provider chain in aws-sdk-go is probably the best option. I'm not sure if we need to copy the logic vs. just vendoring the package.

**Comment by ncdc** [comment]
We already have it vendored, fyi

**Comment by justinsb** [comment]
No particular objection.  But ... is there a use case for bringing up a cluster in this way?  It feels very metal ;-)

**Comment by ncdc** [comment]
I am testing some things on AWS in an assumed role. I spin up a VM, clone kube/kube, run `hack/local-up-cluster.sh`. Without some sort of change, there's no way for the AWS cloud provider to find my instance using the assumed role.

**Comment by justinsb** [comment]
Is there a reason you aren't using an instance profile?

**Comment by ncdc** [comment]
I didn't know those existed! Will the aws sdk be able to use that to pick up the assume role info?

**Comment by jbeda** [comment]
To be clear, instance profiles work if you set up the instance with them
from the start. When using EC2 as dev machine for development it may be
needed to use the on disk creds w/ roles.

Deviating from standard sdk behavior seems strange if there is no explicit
reason.

**Comment by ncdc** [comment]
I can do a PR to either remove the custom credentials setup or copy the logic from the sdk, whatever we decide upon.

**Comment by alexaandru** [comment]
@jbeda - re _"set up the instance with them from the start"_  - no longer true as of February: https://aws.amazon.com/blogs/security/new-attach-an-aws-iam-role-to-an-existing-amazon-ec2-instance-by-using-the-aws-cli/
