### ISSUE TITLE
kube-proxy should report it's own version information

### ISSUE THREAD

**Issue by stuart-warren** [kubernetes/kubernetes#48811]
**BUG REPORT**:

/kind bug

**What happened**:
We run the kube-proxy in a self hosted manner via hyperkube and the kubelet in rkt on the host.

After deploying a new version of a kube-proxy daemonset I noticed that the nodes `.status.nodeInfo.kubeProxyVersion` field was still showing the old version information.

This appears to be due to the kubelet assuming that the kube-proxy is the sameversion and reporting as such:
https://github.com/kubernetes/kubernetes/blob/787f5e0fe5e10c08c52055f451e16a4b545524be/pkg/kubelet/kubelet_node_status.go#L619

**What you expected to happen**:
the nodes `.status.nodeInfo.kubeProxyVersion` field to be set accurately

**How to reproduce it (as minimally and precisely as possible)**:
run differing versions of the kubelet and kube-proxy on a node

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-30T09:50:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0+coreos.0", GitCommit:"8c1bf133b4129042ef8f7d1ffac1be14ee83ed10", GitTreeState:"clean", BuildDate:"2017-06-30T17:46:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**: Openstack
- OS (e.g. from /etc/os-release): Container Linux 1353.7.0
- Kernel (e.g. `uname -a`): `Linux kubernetes-kubernetes-zone2-1-1499865995 4.9.24-coreos #1 SMP Wed Apr 26 21:44:23 UTC 2017 x86_64 Intel Xeon E3-12xx v2 (Ivy Bridge) GenuineIntel GNU/Linux`
- Install tools: heat/kubernetes
- Others:

**Comment by cmluciano** [comment]
@kubernetes/sig-network-feature-requests

**Comment by vikaschoudhary16** [comment]
@cmluciano If anybody has not started working on this already, i would like to look into it. Can you please assign this to me?

**Comment by dixudx** [comment]
@vikaschoudhary16 Already WIP in PR #48988.
