### ISSUE TITLE
kubectl exec fails : error sending request on centos 7 & k8s v1.7.0 

### ISSUE THREAD

**Issue by csarora** [kubernetes/kubernetes#48819]
**OS :** Centos 7 Vsphere VM 
**k8s version :** v1.7.0 + Weave Networking , single master node installation with **proxy enabled** 
Installed k8 successfully using **kubeadm init --kubernetes-version v1.7.0**
all the pods are up and new deployment get success .
**## Issue : Kubectl exec fails** 

`[root@dotricorder03-master-01 ~]# kubectl exec -it busybox /bin/sh
error: error sending request: Post https://172.22.16.69:6443/api/v1/namespaces/default/pods/busybox/exec?command=%2Fbin%2Fsh&container=busybox&container=busybox&stdin=true&stdout=true&tty=true: EOF`

Please help 
@kubernetes/sig-api-machinery
/sig api-machinery

**Comment by ncdc** [comment]
What do you mean by "with proxy enabled"?

Can you check the log files for the apiserver, kubelet, weave (?) and see if you see any errors?

@liggitt do you remember any EOF errors around exec/spdy?

**Comment by liggitt** [comment]
> @liggitt do you remember any EOF errors around exec/spdy?

No. @tallclair this ring any bells around the CRI redirect paths?

**Comment by tallclair** [comment]
I have seen an EOF error before, but I can't remember what the context was. I think we need to see the logs to comment further.

**Comment by csarora** [comment]
@ncdc Proxy enabled means in our vpshere centos VM we first export proxy ,  http_proxy , https_proxy and no_proxy. 
@tallclair   this EOF error for kubectl exec occurs ony for v1.6.*+ or v1.7  but for  v1.5.* works fine on same VM, for v6 too all PODS are coming up successfully only exec fails.
Is it something to do with hostname of VM ?

**Comment by csarora** [comment]
I am able to resolve the issue , it was proxy issue . closing it

**Comment by kakuism** [comment]
@csarora can you share what the solution was? In my setup all the proxies are set, still the error persists.

**Comment by Hades32** [comment]
@csarora same for me... :(

**Comment by suxiaohei** [comment]
@Hades32 close terminal proxy.

**Comment by changsen-dev** [comment]
check your terminal proxy(http_proxy && https_proxy)
