### ISSUE TITLE
Slow unit tests recently added

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#4881]
The following tests have crept back up in execution time, and are probably (not certainly) using sleeps or other unreliable mechanisms to control timing.  As per the usual policy, they should be fixed to not sleep.

```
pkg/kubelet	4.140s
pkg/proxy	2.781s
pkg/probe/http	1.012s
pkg/registry/service	0.502s
```

Slow tests are tools of the enemy.

**Comment by thockin** [comment]
@zmerlynn

**Comment by ixdy** [comment]
pkg/api is another - it takes 6s+ without coverage enabled, and significantly more time with coverage enabled.

**Comment by smarterclayton** [comment]
We can turn the fuzzing iterations down again, although I wouldn't want to go below 10 iterations.

**Comment by ixdy** [comment]
On Travis/Shippable (where we have coverage enabled) pkg/api regularly takes 30-40s, and sometimes times out at 60s. We can increase the timeout, or we can figure out how to make this test run more quickly.

**Comment by thockin** [comment]
Fast tests that don't test well are not so useful.  I am all for fast tests
but that alone is not a goal.

**Comment by smarterclayton** [comment]
The nice thing about fuzzing is we do it across both builds, and usually multiple times per pull.  So it's a low risk to drop.

**Comment by smarterclayton** [comment]
Also, improving conversion performance would help this test and overall cpu use (it dominates most workloads we've profiled).  Some targeting optimization is warranted and would pay big dividends.

**Comment by wojtek-t** [comment]
I looked into pkg/kubelet (which is the longest one) and the longest test is:
pkg/kubelet/runonce_test.go
I will investigate it deeper tomorrow.

**Comment by wojtek-t** [comment]
BWT - it really seems that this test is sleeping for exactly 3 seconds while running. Will try to fix it.
