### ISSUE TITLE
Convert all remaining printers to TableHandlers (from Handlers)

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#48820]
Will allow us to continue moving Get to the server side and reusing the code.  Each resource type can be done as a separate commit / PR.

**Comment by fabianofranz** [comment]
Examples:

https://github.com/kubernetes/kubernetes/pull/48022
https://github.com/kubernetes/kubernetes/pull/48034

**Comment by fabianofranz** [comment]
cc @wanghaoran1988

**Comment by wanghaoran1988** [comment]
I will babysit this

**Comment by shiywang** [comment]
just have a question here, resource like `externaladmissionhookconfigurations ` we just print `[]string{"NAME", "AGE"}`, and I think it's already covered by [AddDefaultHandlers](https://github.com/kubernetes/kubernetes/blob/1108738200331ace6c4752fb10ecf417d9e99a32/pkg/printers/internalversion/printers.go#L259-L259), so it's not necessary to add extra handler for resource only print `NAME` and `AGE` right ?  like this pr: https://github.com/kubernetes/kubernetes/pull/48040 should I close it ?

**Comment by lavalamp** [comment]
fyi @bryk

**Comment by wanghaoran1988** [comment]
/assign
/close
This is already done by:
https://github.com/kubernetes/kubernetes/pull/49359
https://github.com/kubernetes/kubernetes/pull/49700

**Comment by fabianofranz** [comment]
All printers converted in master.
