### ISSUE TITLE
SIG Apps Test Reorganization

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#48839]
- [x] Label & move all sig-apps owned tests
    - [x] Workload controller tests (https://github.com/kubernetes/kubernetes/pull/48828) 
    - [x] Disruption controller tests (https://github.com/kubernetes/kubernetes/pull/48827)
    - [x] [Network partition tests](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network_partition.go) co-owned with sig-network
    - [x] Upgrade tests (https://github.com/kubernetes/kubernetes/pull/48845, https://github.com/kubernetes/kubernetes/pull/48895)
- [x] Add sig-apps dashboard pages
    - [x] Add gce and gke tests (https://github.com/kubernetes/test-infra/pull/3469/)
    - [x] Upgrade tests - added TODO
- [x] Miscellaneous tasks
    - [x] Add sig owners for statefulset test clusters (e.g. https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L2411-L2423) (https://github.com/kubernetes/test-infra/pull/3471)
    - [x] Investigate and fix missing tests

cc @grodrigues3 @crimsonfaith91 @kubernetes/sig-apps-misc

**Comment by crimsonfaith91** [comment]
@foxish i will work on moving upgrade tests.
/assign @crimsonfaith91

**Comment by crimsonfaith91** [comment]
@foxish i will also work on adding sig owners for statefulset test clusters.

**Comment by foxish** [comment]
@crimsonfaith91, for some reason, the [GKE tests](https://k8s-testgrid.appspot.com/sig-apps#gke) aren't populating; can you take a look?

**Comment by foxish** [comment]
Same with flaky and serial tests.

**Comment by foxish** [comment]
Looks like a GKE issue is also happening. Cluster-up fails. https://k8s-testgrid.appspot.com/google-gke

**Comment by crimsonfaith91** [comment]
Definitely! Look at them now. Thanks! @foxish

**Comment by crimsonfaith91** [comment]
Update: The GKE cluster is down. Reached out to primary on-call. He will find the GKE cluster maintainers to investigate it.

**Comment by crimsonfaith91** [comment]
@foxish Do you mind to reopen this issue? I used `fixes` rather than `xref` for one of my PRs, resulting with this issue got closed when the PR was merged.

Perhaps we can also list a task (#48895) about creating a subdirectory `upgrades/apps` and moving sig-apps upgrade tests there.

**Comment by crimsonfaith91** [comment]
Update: GKE tests are still failing.

**Comment by foxish** [comment]
Will keep this issue open till all the dashboards are alive, in order to track.
Thanks @crimsonfaith91 for all the changes to improve our test organization.

**Comment by foxish** [comment]
Dashboard operational. Closing!
/close

**Comment by crimsonfaith91** [comment]
@foxish Are there `gke-slow` tests for sig-apps?

**Comment by foxish** [comment]
I think no. The only gce slow tests for sigapps are cronjob and that is
still alpha (not enabled in gke).

**Comment by crimsonfaith91** [comment]
@foxish Noted. I guess we can have `gke-slow` column for the test grid so that cronjob tests are loaded when the cronjob is alpha.
