### ISSUE TITLE
pod status is always terminating

### ISSUE THREAD

**Issue by bruceauyeung** [kubernetes/kubernetes#48866]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
i have a k8s cluster(1.6.4), all components run as static pods expect that kubelet runs as a normal docker container(bootstrapped by a systemd service). all conponents are started using hyperkube image
now i shutdown a node (saying node A ), user pods on that node successfully migrate onto another node
but after started node A again, user pods on this node be always be terminating
kubelet logs on node A:

> Jul 13 16:54:15 host-20-20-20-201 kubelet[9744]: E0713 08:54:15.666305    9785 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/secret/b1a82f2a-67a1-11e7-93d5-fa163e1a2c07-default-token-cxhvh\" (\"b1a82f2a-67a1-11e7-93d5-fa163e1a2c07\")" failed. No retries permitted until 2017-07-13 08:56:15.666273944 +0000 UTC (durationBeforeRetry 2m0s). Error: UnmountVolume.TearDown failed for volume "kubernetes.io/secret/b1a82f2a-67a1-11e7-93d5-fa163e1a2c07-default-token-cxhvh" (volume.spec.Name: "default-token-cxhvh") pod "b1a82f2a-67a1-11e7-93d5-fa163e1a2c07" (UID: "b1a82f2a-67a1-11e7-93d5-fa163e1a2c07") with: remove /var/lib/kubelet/pods/b1a82f2a-67a1-11e7-93d5-fa163e1a2c07/volumes/kubernetes.io~secret/default-token-cxhvh: device or resource busy

it's very similar with https://github.com/kubernetes/kubernetes/issues/22911
and https://github.com/kubernetes/kubernetes/pull/27054 beleives this issue has already been fixed

then i tried to restart kubelet service, and then all terminating user pods on node A are terminated
but kubelet logs throw errors constantly :

> Jul 13 17:11:17 host-20-20-20-201 kubelet[12931]: E0713 09:11:17.918192   12972 kubelet_volumes.go:114] Orphaned pod "b1a84483-67a1-11e7-93d5-fa163e1a2c07" found, but volume paths are still present on disk.

**What you expected to happen**:
user pods on node A are terminated successfully without restarting kubelet service manually
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 

> \# kubectl version
> Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4+d6f433224538d", GitCommit:"dcd97c39eb8c0e388170721eac0da4eaef92e79b"}
> Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4+d6f433224538d", GitCommit:"dcd97c39eb8c0e388170721eac0da4eaef92e79b"}

- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): 

> centos 7.2

- Kernel (e.g. `uname -a`): 

> Linux host-20-20-20-201 3.10.0-514.6.1.el7.x86_64 #1 SMP Thu Feb 16 19:50:09 CST 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: customized kargo
- Others:

**Comment by r7vme** [comment]
We are having similar problem with `device or resource busy`. For me most suspicious is message that `ContainerDied`, while docker still waiting for container shut down. Looks like docker can not properly shutdown container. Does kubelet rely on docker in unmounting volumes?

docker log
```
Jul 27 15:10:48 0000616c4f12308e dockerd[5440]: time="2017-07-27T15:10:48.637159275Z" level=info msg="Container f4d96f2b4501382da3d0e29c96cf2136efaedf84d732015894bebd6e66e0ed62 failed to exit within 30 seconds of signal 15 - using the force"
```
kubelet logs
```
Jul 27 15:10:18 0000616c4f12308e sh[30897]: I0727 15:10:18.635491   31303 kubelet.go:1824] SyncLoop (DELETE, "api"): "master-82ard-2290518562-kgq
kg_cgmq1(dac12813-672f-11e7-af42-0894ef3abdb6)"
Jul 27 15:10:18 0000616c4f12308e sh[30897]: I0727 15:10:18.635786   31303 kuberuntime_container.go:535] Killing container "docker://f4d96f2b45013
82da3d0e29c96cf2136efaedf84d732015894bebd6e66e0ed62" with 30 second grace period
Jul 27 15:10:18 0000616c4f12308e sh[30897]: I0727 15:10:18.635825   31303 kuberuntime_container.go:535] Killing container "docker://61affdca34953
53270549a9a0e6d23466638f51afe942029261f24cb9e91da0e" with 30 second grace period
...
Jul 27 15:10:19 0000616c4f12308e sh[30897]: I0727 15:10:19.724407   31303 kubelet.go:1842] SyncLoop (PLEG): "master-82ard-2290518562-kgqkg_cgmq1(dac12813-672f-11e7-af42-0894ef3abdb6)", event: &pleg.PodLifecycleEvent{ID:"dac12813-672f-11e7-af42-0894ef3abdb6", Type:"ContainerDied", Data:"61affdca3495353270549a9a0e6d23466638f51afe942029261f24cb9e91da0e"}
...
Jul 27 15:10:48 0000616c4f12308e sh[30897]: E0727 15:10:48.635974   31303 remote_runtime.go:224] StopContainer "f4d96f2b4501382da3d0e29c96cf2136efaedf84d732015894bebd6e66e0ed62" from runtime service failed: rpc error: code = 4 desc = context deadline exceeded
Jul 27 15:10:48 0000616c4f12308e sh[30897]: E0727 15:10:48.636039   31303 kuberuntime_container.go:552] Container "docker://f4d96f2b4501382da3d0e29c96cf2136efaedf84d732015894bebd6e66e0ed62" termination failed with gracePeriod 30: rpc error: code = 4 desc = context deadline exceeded
```

Versions:
kubelet 1.6.4
docker 1.11.2

**Comment by ijumps** [comment]
This may due to bad `hostpath` mount. For now, all `hostpath` use private mount, when you run a pod use `hostpath` to mount `/` into container, any pod create before this pod may not umount secret successfully. In this case, a slave mount should be used.

You can check the path (e.g. `/var/lib/kubelet/pods/b1a82f2a-67a1-11e7-93d5-fa163e1a2c07/volumes/kubernetes.io~secret/default-token-cxhvh`) with tools like `lsof` and `fuser` to identify which process open this file. This may not work because of namespace separation.

It's not easy to find which process open that file, but you can do some trick like this:

```
# you can pick up the pod id from the path
cat /proc/*/mounts | grep b1a82f2a-67a1-11e7-93d5-fa163e1a2c07
```

then you can see the pid of the process (normally run in container) occupy this file.

Hope this will help you.

---

FYI: https://github.com/kubernetes/kubernetes/pull/46444

**Comment by aga20** [comment]
Hello,

thank you @ijumps. Your explanation was a good start for me to debug my issue. In my case a systemd service start a kubelet container and our systemd service file was a little old and [this line](https://github.com/kubernetes/kubernetes-anywhere/blob/master/phase2/ignition/vanilla/kubelet.service#L19) was rw not shared in our case. 
In addition I had to comment out the `MountFlags=slave` in my the docker service file. Maybe this isn't good but the kubelet can Terminate the pods after I stop and start the VM. 
Any idea what can be the good solution in this case?

**Comment by tadas-subonis** [comment]
I had a bunch of Pod like that so I had to come up with a command that would clean up all the terminating pods:
```
kubectl get pods -o json | jq -c '.items[] | select(.metadata.deletionTimestamp) | .metadata.name' | xargs -I '{}' kubectl delete pod --force --grace-period 0 '{}'
```
