### ISSUE TITLE
kube-apiserver 1.7 breaks high availability

### ISSUE THREAD

**Issue by pavels** [kubernetes/kubernetes#48865]
/kind bug

**What happened**:

while migrating from 1.4 to 1.7 (and to etcd V3 api) we found that our high availability setup broke. We have setup very similar to this: https://kubernetes.io/docs/admin/high-availability/ - we have 3x complete control plane (etcd with 3 nodes + 3 api servers, 3 controllers and 3 schedulers) and we have haproxy on each worker node load balancing the api servers (kubelet on worker nodes connects to localhost).

First we was unable to even get the correct readiness of the nodes, they was randomly changing and each api server reported different nodes as ready and notready. Addding `--etcd-quorum-read` parameter to api server helped - this parameter is not documented in the "Building High-Availability Cluster" documentation even if it is apparently crucial to make the setup work.

After adding `--etcd-quorum-read` the situation got much better but still not correct. It happens sometimes that different api servers report different pods and pod statuses which confuses kubelets on worker nodes and very quickly makes the cluster completely inoperable.

It seems that the api server is not that stateless, that there is some kind of caching going on.

Is there some HA guidelines? We are now disabled 2 api servers and running just one. We probably can utilize pacemaker  or something similar but it would be quiet strange to have etcd with its advanced consensus algorithms and than pacemaker to keep only one api server running. 

Maybe adding flag to api server that would mean something like "i don't care it is going to be slow, i need it as correct as possible, so no caching, only quorum reads etc...)?

Also there are issues https://github.com/kubernetes/kubernetes/issues/19902 and https://github.com/kubernetes/kubernetes/issues/19816 - the second one is closed with last comment that api server is fast enough so you don't need to horizontally scale it and that HA needs to be redesigned and is closed.

**Environment**:
- Kubernetes version (use `kubectl version`):  `Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration**: Own servers
- OS (e.g. from /etc/os-release): `CentOS Linux 7 (Core)`
- Kernel (e.g. `uname -a`): `3.10.0-327.el7.x86_64`

**Comment by liggitt** [comment]
yes, quorum read is expected to be on in HA envs. you are correct that that should be better documented/enforced.

the API server has a watch cache, but attempts to watch from newer resource versions should block until the API server observes the events from the underlying etcd. get/list operations do not use the API cache unless explicitly opted into with a `resourceVersion=0` parameter.

I know of two issues related to the watch cache (https://github.com/kubernetes/kubernetes/pull/42729 and https://github.com/kubernetes/kubernetes/pull/43152) that can impact update and patch in isolated situations, but I don't know of any that would impact reads.

How did you migrate your etcd nodes from v2 to v3? If you check etcd cluster health using etcdctl, do your etcd nodes all agree they are part of the same cluster and have the same leader?

**Comment by pavels** [comment]
the migration was done as follows
1) stop kubernetes backplane and diable
2) stop kubelet (that stops etcd)
3) replace etcd version
4) start kubelet (api server atc. is disabled) - wait until cluster converges and is healthy
5) stop again - do migration on every node using etcdctl migrate
6) start again - wait until cluster is healthy
7) start api servers, controllers etc...

our etcd status is as follows
`
$ETCDCTL_API=3 /opt/kubernetes/etcdctl-run -w table endpoint status
+--------------------------+------------------+---------+---------+-----------+-----------+------------+
|         ENDPOINT         |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+--------------------------+------------------+---------+---------+-----------+-----------+------------+
| http://192.168.42.1:4001 | 563baa8485c86275 |   3.2.2 |  140 MB |     false |      1698 |   83806036 |
| http://192.168.42.2:4001 | 9e93855e13f1a661 |   3.2.2 |  128 MB |     false |      1698 |   83806036 |
| http://192.168.42.3:4001 | 81898c0672f115a3 |   3.2.2 |  298 MB |      true |      1698 |   83806036 |
+--------------------------+------------------+---------+---------+-----------+-----------+------------+
`

it was similar when i was doing the upgrade

I can try again and switch on api server and wait what happen, but i need to plan for downtime as last time it brought everything to complete halt in minute or two.

**Comment by liggitt** [comment]
the difference in DB size seems odd to me... @xiang90, is that expected?

**Comment by liggitt** [comment]
possibly https://github.com/coreos/etcd/issues/8305

**Comment by liggitt** [comment]
> stop again - do migration on every node using etcdctl migrate

did you run the migrate command with `--no-ttl` or did you migrate all keys?

If you migrated all keys, this sounds like the same issue we've run into testing etcd migrations with openshift. The documented process to migrate multiple etcd members does not handle the situation where there are keys with actively expiring TTLs.

Even without active writers, the members can end up with inconsistent v3 mvcc stores, which wreaks havoc with future writes.

If you shut down your apiservers and controllers and let the etcd members converge, what does this show:
```
ETCDCTL_API=3 /opt/kubernetes/etcdctl-run -w json endpoint status
```

The mvcc version should be consistent between the members.
