### ISSUE TITLE
1.7 upgrade tests are failing in lots of different ways

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#48876]
They need to be triaged and issues need to be created.

https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-cluster-new
https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-cluster

@krousey 
/sig cluster-lifecycle

**Comment by krousey** [comment]
This was likely broken because of https://github.com/kubernetes/kubernetes/pull/48845. The upgrade framework overloads the test name for namespace creation. I'm working on a PR to sanitize the name before creating a namespace.
