### ISSUE TITLE
Network policy examples not working

### ISSUE THREAD

**Issue by kanor1306** [kubernetes/kubernetes#48878]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I followed the examples in https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/ and I didn't manage to get the network isolation, I could access the deployed nginx even without the label.

**What you expected to happen**:
I expected the nginx pod to be isolated from pods without the label access: "true"

**How to reproduce it (as minimally and precisely as possible)**:
In a cluster with Flannel + Calico (not the Canal setup), follow the steps in https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/ . In the step 'Test access to the service when access label is not defined' you are supposed to get a timeout, but I get a response.

**Anything else we need to know?**:
I have verified other network policies and they work (like, namespace isolation and then allowing some connections), but I am interested in achieving this without using a namespace wide network policy. 

Version of software: 
Flannel: 0.5.5
Calico-node: 1.3.0
Calico-cni: 1.9.1
Calico-policy-controller: 0.6.0

**Environment**:
- Kubernetes version (use `kubectl version`): version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**: Bare metal
- OS (e.g. from /etc/os-release):  CentOS 7
- Kernel (e.g. `uname -a`): 3.10.0-514.26.2.el7.x86_64
- Install tools: Puppet

**Comment by kanor1306** [comment]
@kubernetes/sig-network

**Comment by feiskyer** [comment]
@kanor1306 https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/ is for kubernetes v1.7 now. Should refer to https://github.com/kubernetes/kubernetes.github.io/blob/release-1.6/docs/concepts/services-networking/network-policies.md since you are using kubernetes v1.6.

**Comment by feiskyer** [comment]
@dcbw @thockin Is possible to add a link to v1.6 documentation?

**Comment by kanor1306** [comment]
Oh of course, I didn't realize about the NetworkPolicy changes from 1.6 to 1.7. Thanks @feiskyer !

I will close the issue.
