### ISSUE TITLE
windows/amd64 cross-build is broken: vendor/github.com/docker/docker/pkg/term/windows

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#48887]
The windows/amd64 cross-build has been failing since yesterday morning.
From https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-cross-build/2320:
```
I0712 10:13:02.637] +++ [0712 10:11:46] windows/amd64: go build started
I0712 10:13:02.637] # k8s.io/kubernetes/vendor/github.com/docker/docker/pkg/term/windows
I0712 10:13:02.637] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:139: undefined: winterm.WORD
I0712 10:13:02.637] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:146: undefined: winterm.WORD
I0712 10:13:02.637] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:210: undefined: winterm.WORD
I0712 10:13:02.637] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:210: undefined: winterm.DWORD
I0712 10:13:02.638] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:226: undefined: winterm.DWORD
```

It looks like #47140 is the culprit. The Azure dependencies were updated, but docker wasn't updated to support the changes until 1.12, and we vendor 1.11.

/assign @brendandburns  
/cc @krousey @kubernetes/sig-windows-bugs

**Comment by ixdy** [comment]
hm, I guess sig-windows is probably not the right group here. sorry for the spam!

**Comment by brendandburns** [comment]
I'll get a fix for this sometime today...

apologies!

**Comment by ixdy** [comment]
And now [we're broken again](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-cross-build/2369):
```
I0714 17:04:14.667] # k8s.io/kubernetes/vendor/github.com/docker/docker/pkg/term/windows
I0714 17:04:14.667] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:192: cannot use keyEvent.VirtualKeyCode (type winterm.WORD) as type uint16 in argument to formatVirtualKey
I0714 17:04:14.667] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:192: cannot use keyEvent.ControlKeyState (type winterm.DWORD) as type uint32 in argument to formatVirtualKey
I0714 17:04:14.667] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:195: cannot use keyEvent.ControlKeyState (type winterm.DWORD) as type uint32 in argument to getControlKeys
```

It seems that #48308 updated the docker dependency, which made the `go-ansiterm` revert in #48933 now incorrect.

cc @karataliu @yguo0905 @yujuhong @dchen1107

**Comment by karataliu** [comment]
@ixdy twists and turns here 
Yeah, since we have got an updated docker version now, we can revert the go-ansiterm version downgrade change #48933. Thanks for the follow up.

Is the cross-build test a required one for check-in now? If it is, then no such breaks should happen.

**Comment by cblecker** [comment]
It isn't by default.. I believe this is because it's long running and resource intensive.

@ixdy: is it potentially worth adding Godeps to the cross-build [run_if_changed list](https://github.com/kubernetes/test-infra/blob/3b0fbf35c9f1e4a91b75ea141d3cf4d3da051c39/prow/config.yaml#L102)? I don't know if this could prevent this in the future, or if it would just consume a lot of resources for very little gain (if this is a corner case).
