### ISSUE TITLE
Enabling PSP after a cluster is already running can lead to pods that not mutable

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#48885]
openshift/origin#15188 highlighted that some mutating admission controllers can result in failure to update pods (which includes removing finalizers) unless they are disabled.  PSP is affected by this, but it is likely that users will want to turn PSP on for existing clusters and still have some mechanism for grandfathering old pods (i.e, don't break the cluster).

Needs to be resolved before PSP can be turned on for existing clusters at scale.

**Comment by liggitt** [comment]
As long as a cluster admin has access to a PSP that allows the pod, they can remove the offending pod.

Controller-wise, it's not different from removing PSP permissions from a service account while there are still pods present that were only allowed because of those permissions.

**Comment by enj** [comment]
@kubernetes/sig-auth-misc

**Comment by liggitt** [comment]
can short-circuit in the PSP admission plugin for updates that change only finalizer-related fields

**Comment by dims** [comment]
@smarterclayton @liggitt move to 1.10?

**Comment by liggitt** [comment]
I think this can actually be closed. finalizer-only changes now skip PSP application, allowing removal of non-compliant pods
