### ISSUE TITLE
Service discovery doesn't happen immediately -

### ISSUE THREAD

**Issue by githubvick** [kubernetes/kubernetes#48900]
[yaml.txt](https://github.com/kubernetes/kubernetes/files/1146549/yaml.txt)
[log.txt](https://github.com/kubernetes/kubernetes/files/1146521/log.txt)

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
bug
> /kind feature

**What happened**:

A kube service is created, the subsequent pod is not able to discover the service immediately but only after a couple of minutes as shown in the logs.

**What you expected to happen**:

The service should be discovered immediately.

**How to reproduce it (as minimally and precisely as possible)**:
Create mongodb pod and service as a deployment, reference the mongoservice in the employee deployment as below. 
```
kubectl create -f $HOME/azure/kube_objs/mongo-depl.yaml
kubectl create -f $HOME/azure/kube_objs/emp-depl.yaml
kubectl create -f $HOME/azure/kube_objs/mission-depl.yaml
kubectl create -f $HOME/azure/kube_objs/reward-depl.yaml
```

**Anything else we need to know?**:
Kubernetes cluster installation and config is done through Ansible. 
The above commands are executed as a  script.
Attached the logs.
**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"269f928217957e7126dc87e6adfa82242bfe5b1e", GitTreeState:"clean", BuildDate:"2017-07-03T15:31:10Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"269f928217957e7126dc87e6adfa82242bfe5b1e", GitTreeState:"clean", BuildDate:"2017-07-03T15:31:10Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**: Azure VM
- OS (e.g. from /etc/os-release): NAME="CentOS Linux" VERSION="7 (Core)"
- Kernel (e.g. `uname -a`): Linux hostname 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:
 @kubernetes/sig-azure

**Comment by githubvick** [comment]
[log.txt](https://github.com/kubernetes/kubernetes/files/1146542/log.txt)

**Comment by githubvick** [comment]
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodbdepl
  labels:
    name: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongodb
    spec:
      containers:
      - resources:
          limits:
            cpu: 0.3
        image: mongo
        imagePullPolicy: IfNotPresent
        name: mongodb
        ports:
          - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongowhatever
  name: mongoservice
spec:
  ports:
   - port: 27017
     nodePort: 30061
     targetPort: 27017
     protocol: TCP
  type: NodePort
  selector:
    name: mongodb
****

**Comment by feiskyer** [comment]
@githubvick I think the latency is expected, before the service is available, kubernetes needs to do a few things:

- kubelet pull mongodb image and create the container ( the time depends on image pulling and start container)
- service/endpoints controller discover the pod's IP
- kube-proxy configure actuall rules for the service ( it could be slow if there are many services in cluster)

So the service can't be available immediately.
