### ISSUE TITLE
[ignore] Testing issue for sig-mention-handler

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/kubernetes#48916]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by crimsonfaith91** [comment]
@grodrigues3 Is it `@kubernetes/contributor-experience-<group-suffix>` or `@kubernetes/sig-contributor-experience-<group-suffix>`?

**Comment by cblecker** [comment]
@crimsonfaith91 the latter :)

**Comment by crimsonfaith91** [comment]
@cblecker Many thanks! :)

**Comment by xiangpengzhao** [comment]
/sig contributor-experience
test label

**Comment by xiangpengzhao** [comment]
@kubernetes/sig-contributor-experience-bugs
test notification when having label.

**Comment by xiangpengzhao** [comment]
@crimsonfaith91 I test #2956 (#3398) as above, it works as expected. Thanks!

**Comment by crimsonfaith91** [comment]
@xiangpengzhao Thanks for verify them! :)

**Comment by grodrigues3** [comment]
Nice @crimsonfaith91.  Thanks for testing
