### ISSUE TITLE
cni0 does not forward IP packet among containers but arping works after installed k8s 1.7

### ISSUE THREAD

**Issue by ryanlyy** [kubernetes/kubernetes#48923]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
In Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-62-generic x86_64), I installed k8s using kubeadm. After that I create two centos container using kubectl. When ping from one container to another container, it fails. I tried apring from one container to another container seems it works well.

tcpdump show cni0 receives ICMP msg from container veth but does not forward that packet to another veth of target container. brctl showmac show target mac is there.

And I create two container using docker run, ping works well between those two container created by docker run. So it means docker environment works well(docker-ce) using docker0.

**What you expected to happen**:
containers created by kubectl can talk eachother (i.e: ping works)
**How to reproduce it (as minimally and precisely as possible)**:
1. install ubuntu VM 16.04.2 LTS (GNU/Linux 4.4.0-62-generic x86_64)
2. Install k8s using kubeadm
3. create two container using kubectl
4. ping each in container

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
root@ubuntu:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T01:48:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
root@ubuntu:~#

- Cloud provider or hardware configuration**:
virt-manager create ubuntu VM
- OS (e.g. from /etc/os-release):
16.04.2 LTS (GNU/Linux 4.4.0-62-generic x86_64)
- Kernel (e.g. `uname -a`):
16.04.2 LTS (GNU/Linux 4.4.0-62-generic x86_64)

- Install tools:
docker-ce, kubeadm, k8s
- Others:

**Comment by ryanlyy** [comment]
@kubernetes/sig-network-bugs

**Comment by ryanlyy** [comment]
@kubernetes/sig-network-bugs

**Comment by cmluciano** [comment]
What release of docker is this?

**Comment by dcbw** [comment]
@ryanlyy what IP addresess do the two containers attached to cni0 have, and what IP address does the cni0 bridge have?  Can the containers ping the bridge IP?

**Comment by ryanlyy** [comment]
Thanks a lot for your support. this issue has been addressed. it is because in new docker version (CE), iptables FORWARD chain is DROP in default. after change it, it works. so I will close this ticket.

**Comment by pehlert** [comment]
I just had this same issue and it took me quite a while to figure it out.. The command that solved it for me was: `iptables -P FORWARD ACCEPT`.. Is this a bug in the kubeadm setup (or specific to Ubuntu?)?
