### ISSUE TITLE
Allow defining different timeouts for different verbs in client go

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#48926]
Or at least different for steaming and non-streaming calls. This is required to introduce meaningful timeout in Kubelet that wouldn't cause frequent watch relists. #48640

@kubernetes/sig-api-machinery-feature-requests @kubernetes/sig-scalability-misc @derekwaynecarr

**Comment by derekwaynecarr** [comment]
@gmarek - thanks for following up on this.  agreed completely.

**Comment by lavalamp** [comment]
@caesarxuchao is willing to review a PR that adds multiple different timeouts.

**Comment by gmarek** [comment]
@kubernetes/sig-api-machinery-feature-requests - we also need someone to work on this.

**Comment by szuecs** [comment]
Can we have an estimate, how long this will take to implement?
For us it was the root cause of an production outage we had yesterday.

**Comment by rchakra3** [comment]
Is this still required and could I work on it? I'm looking for something to work on as a new contributor :)

**Comment by edevil** [comment]
I think so.
