### ISSUE TITLE
hostname-override is ignored when a cloud provider is configured

### ISSUE THREAD

**Issue by matlockx** [kubernetes/kubernetes#48929]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When using the hostname-override flag and a cloud provider the hostname-override value gets ignored. See 

https://github.com/kubernetes/kubernetes/blob/7df2bce1ece551800edb1a8f1f62adecbd11cff5/pkg/kubelet/kubelet.go#L308
and
https://github.com/kubernetes/kubernetes/blob/7df2bce1ece551800edb1a8f1f62adecbd11cff5/pkg/kubelet/kubelet.go#L320

@kubernetes/sig-node-bugs

**What you expected to happen**:
The docu of the flag states 'If non-empty, will use this string as identification instead of the actual hostname' so i would that to be still valid even if I use a cloud provider.

**How to reproduce it (as minimally and precisely as possible)**:
Start kubelet with override-hostname and a cloud provider.
This might be a problem when running an update on a cluster by adding a cloud provider and using override-hostname. The node might not update its state because the node identifier changed.

**Anything else we need to know?**:
I'm not sure whether this is actually working as expected. If so, it's not clear to me by reading the docu.
**Environment**:
- Kubernetes version (use `kubectl version`):
```
[mjoeh@kube-master-02 ~]$ /usr/local/bin/kubectl version
2017-07-14 09:20:07.926109 I | proto: duplicate proto type registered: google.protobuf.Any
2017-07-14 09:20:07.926791 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-07-14 09:20:07.926829 I | proto: duplicate proto type registered: google.protobuf.Timestamp
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0+coreos.0", GitCommit:"8c1bf133b4129042ef8f7d1ffac1be14ee83ed10", GitTreeState:"clean", BuildDate:"2017-06-30T17:46:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0+coreos.0", GitCommit:"8c1bf133b4129042ef8f7d1ffac1be14ee83ed10", GitTreeState:"clean", BuildDate:"2017-06-30T17:46:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**:
vsphere
- OS (e.g. from /etc/os-release):
CentOS Linux release 7.3.1611 (Core)
- Kernel (e.g. `uname -a`):
Linux kube-master-02.t24.stagec.sg-cloud.co.uk 4.4.76-1.el7.elrepo.x86_64 #1 SMP Wed Jul 5 12:10:20 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubespray
- Others:

**Comment by matlockx** [comment]
If you consider this a bug too, I can provide a PR.

**Comment by matlockx** [comment]
@kubernetes/sig-node-bug

**Comment by matlockx** [comment]
@kubernetes/sig-node-bugs
/sig node

**Comment by divyenpatel** [comment]
For vSphere cloud provider, vm name should match with the node name.

Kubernetes sends hostname to the vsphere cloud provider and then vsphere cloud provider finds vm reference using this name for attaching and detaching disk to the vm.

https://github.com/vmware/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L686
https://github.com/vmware/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L1148

@matlockx  How is hostname name going to be mapped to the vm name after the fix?

cc: @BaluDontu @luomiao @tusharnt

**Comment by matlockx** [comment]
Ok, in that case the fix would be make it clear in the documentation, that override Hostname might be ignored when using a cloud provider. I ran into this when using kubespray. Kubespray always sets the node name to the unqualified name. When we updated the cluster then and activated the cloud provider all nodes weren't any longer registered, because their node names changed and they didn't re-register with the new ones.

**Comment by divyenpatel** [comment]
@matlockx we are tracking this issue and make it clear in the documentation - https://github.com/vmware/kubernetes/issues/200

**Comment by matlockx** [comment]
👍 @divyenpatel so i close this here?

**Comment by divyenpatel** [comment]
@matlockx we can close this.
I have made this clear in the documentation.
PR: https://github.com/kubernetes/kubernetes.github.io/pull/4418

Mentioned VM name constraints and provided note that says "After enabling the vSphere Cloud Provider, Node names will be set to the VM names from the vCenter Inventory."

**Comment by matlockx** [comment]
Great!  Thanks

**Comment by matlockx** [comment]
Addressed by https://github.com/kubernetes/kubernetes.github.io/pull/4418
