### ISSUE TITLE
one node down, but pods on the node status.phase still Running

### ISSUE THREAD

**Issue by wilhelmguo** [kubernetes/kubernetes#48920]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
[root@docker3006 ~]# kubectl get nodes
NAME                           STATUS     AGE       VERSION
docker3005.se.zzzc.qihoo.net   NotReady   18h       v1.7.0

Here is the pod json.

{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "nginx-test-1771026684-wj1sm",
    "generateName": "nginx-test-1771026684-",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/pods/nginx-test-1771026684-wj1sm",
    "uid": "791576d6-6847-11e7-965e-6c92bf0db0c9",
    "resourceVersion": "3322513",
    "creationTimestamp": "2017-07-14T03:49:44Z",
    "deletionTimestamp": "2017-07-14T03:53:01Z",
    "deletionGracePeriodSeconds": 30,
    "labels": {
      "app": "nginx-test",
      "pod-template-hash": "1771026684"
    },
    "annotations": {
      "kubernetes.io/created-by": "{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicaSet\",\"namespace\":\"default\",\"name\":\"nginx-test-1771026684\",\"uid\":\"790f92e4-6847-11e7-965e-6c92bf0db0c9\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"3322159\"}}\n"
    },
    "ownerReferences": [
      {
        "apiVersion": "extensions/v1beta1",
        "kind": "ReplicaSet",
        "name": "nginx-test-1771026684",
        "uid": "790f92e4-6847-11e7-965e-6c92bf0db0c9",
        "controller": true,
        "blockOwnerDeletion": true
      }
    ]
  },
  "spec": {
    "volumes": [
      {
        "name": "default-token-4s932",
        "secret": {
          "secretName": "default-token-4s932",
          "defaultMode": 420
        }
      }
    ],
    "containers": [
      {
        "name": "nginx-test",
        "image": "nginx",
        "resources": {},
        "volumeMounts": [
          {
            "name": "default-token-4s932",
            "readOnly": true,
            "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
          }
        ],
        "terminationMessagePath": "/dev/termination-log",
        "terminationMessagePolicy": "File",
        "imagePullPolicy": "Always",
        "securityContext": {
          "privileged": false
        }
      }
    ],
    "restartPolicy": "Always",
    "terminationGracePeriodSeconds": 30,
    "dnsPolicy": "ClusterFirst",
    "serviceAccountName": "default",
    "serviceAccount": "default",
    "nodeName": "docker3005",
    "securityContext": {},
    "schedulerName": "default-scheduler"
  },
  "status": {
    "phase": "Running",
    "conditions": [
      {
        "type": "Initialized",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2017-07-14T03:49:44Z"
      },
      {
        "type": "Ready",
        "status": "False",
        "lastProbeTime": null,
        "lastTransitionTime": "2017-07-14T03:49:49Z"
      },
      {
        "type": "PodScheduled",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2017-07-14T03:49:44Z"
      }
    ],
    "message": "Node docker3005 which was running pod nginx-test-1771026684-wj1sm is unresponsive",
    "reason": "NodeLost",
    "hostIP": "10.172.189.139",
    "podIP": "172.17.46.10",
    "startTime": "2017-07-14T03:49:44Z",
    "containerStatuses": [
      {
        "name": "nginx-test",
        "state": {
          "running": {
            "startedAt": "2017-07-14T03:49:49Z"
          }
        },
        "lastState": {},
        "ready": true,
        "restartCount": 0,
        "image": "nginx:latest",
        "imageID": "docker-pullable://nginx@sha256:423210a5903e9683d2bc8436ed06343ad5955c1aec71a04e1d45bd70b0d68460",
        "containerID": "docker://c4d5a6d4dd72d767f02f18d1e05cb6780aeddefb2d9f2d4ecc4a41255285a33d"
      }
    ],
    "qosClass": "BestEffort"
  }
} 

**What you expected to happen**:
Then  pod on the node status.phase still Running.If the node lost , should  we mark pods on the node status.phase unknown?
**How to reproduce it (as minimally and precisely as possible)**:
Stop one node kubelet and  network.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**:
bare metal
- OS (e.g. from /etc/os-release):
Centos7.2
- Kernel (e.g. `uname -a`):
3.10.0
- Install tools:
- Others:

**Comment by xiangpengzhao** [comment]
ref: #45016
See discussion in #45465

/cc @derekwaynecarr @xiang90

**Comment by WIZARD-CXY** [comment]
I think it is not a bug at least for me. You can read the doc https://kubernetes.io/docs/concepts/architecture/nodes/ to know more.

**Comment by smarterclayton** [comment]
@derekwaynecarr is the pod still marked ready?  It should not be considered ready during NodeLost I don't think.

**Comment by smarterclayton** [comment]
On second thought, it probably has to remain ready because the master can't be sure of partition.  However, I'm also concerned with having to special case NodeLost in clients
