### ISSUE TITLE
Make the BootstrapTokenAuthenticator only act on prefixed tokens

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#48945]
Discussed in the sig-cluster-lifecycle meeting...
Currently the BootstrapTokenAuthenticator decides whether a given token is a bootstrap token by looking at the format `<six chars>.<sixteen chars>`.
However, it might be better to only support tokens with a specific `k8s-bt` prefix or something so that the "fast route" will be faster when we move this to beta.
Also this might reduce possible confusion that might occur later on.

cc @jbeda @mattmoyer @liggitt @ericchiang @ncdc @timothysc

**Comment by luxas** [comment]
This would include making kubeadm add the prefix when talking to v1.8-something masters as well

**Comment by liggitt** [comment]
the authenticator is already working from a cache of the bootstrap tokens, so the lookup is essentially free. combined with the format check, I think we already have a pretty fast path.

**Comment by timothysc** [comment]
punting to @mattmoyer on this side.

**Comment by luxas** [comment]
@liggitt What do you think about this from a correctness or cleanliness standpoint then?
Shouldn't we be explicit with that "this is a bootstrap token" instead of implicitely relying on the format?

**Comment by luxas** [comment]
@jbeda @liggitt @timothysc @mattmoyer @ericchiang Can we come to a conclusion on this issue?
Go/No-go? This would make the Bootstrap Token more distinct and more easily discoverable.
It would possibly even improve the fast paths' performance.
It would be a backwards-incompatible change to the flow; which introduces a risk.

Is it worth the risk or should we just consider the pattern well-describing enough?

**Comment by liggitt** [comment]
my $0.02 is that the benefit doesn't outweigh the friction of a format change

**Comment by mattmoyer** [comment]
It should be possible to do this in a couple of stages so there's no impact:
 1. (1.8) Add support in `plugin/pkg/auth/authenticator/token/bootstrap/bootstrap.go:parseToken` for recognizing and stripping off a `k8s-bootstrap-v1.` prefix, but still recognize tokens without the prefix.

 2. (1.8) In `kubeadm`, add support for the prefix when talking to 1.8+ clusters.

 3. (1.10) Update `parseToken` to require the prefix.

 4. (1.10) Remove the older code path in `kubeadm` that doesn't add the prefix.

This means kubeadm 1.10 support 1.7 clusters and 1.10 clusters won't support kubeadm 1.7 clients. That setup should normally only happen during cluster upgrades, so 1 minor version seems 

If we stage it out like that I don't think that would cause any friction for users. It is a fair amount of friction in terms of the number of PRs/issues, but I'm +1 on this change just for clarity/debuggability.

**Comment by ericchiang** [comment]
@mattmoyer since kubeadm advertises its API as beta, including the alpha bootstrap format, things other than kubeadm are generating tokens https://github.com/kubernetes/kubernetes-anywhere/blob/bf3661f8ee1679aea2e36431be43cd2a8d4e212b/phase1/gce/do#L10-L12

Don't know how many similar snippets there are, but we're going to have to track those down too. Not just update `kubeadm`.

**Comment by jbeda** [comment]
I'm torn here.  I wish we had put a prefix on these from the get-go.

After looking at the multi-version plan to switch over, I can't say I'm excited about that.  Specifically in @mattmoyer's step (2) above, we'd have to detect the cluster version and act differently on that. That isn't something we do right now and it smells bad.

How about this: we change the authentication to accept prefixed tokens (something short, please?) and we have `kubeadm init` generate tokens with the prefix.  `kubeadm join` will pass whatever it gets verbatim.  We officially deprecate the old format but don't enforce it yet.  We can then see how widely folks update to the newer format over time and remove the old support at some point.  My guess is that over time everyone will follow the example of `kubeadm init` and we'll be in good shape.

**Comment by timothysc** [comment]
In general, I'm going to defer these questions to sig-auth folks.

**Comment by luxas** [comment]
We discussed this in the SIG Meeting and decided that as we don't have any "champion" for adding this prefix really (there has just been discussions about it here and in the SIG meeting), we'll just leave this as-is. It would be cool from a correctness perspective, but the regex format is kind of well-known at this point as well. Not doing this because of the risk and added complexity it implies.
