### ISSUE TITLE
Validation tests are a mess

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#4894]
This is not a critical issue, but validation tests are a mess. Each one is using slightly different mechanism to produce examples and check for errors, even though they are doing exactly the same thing. It should be rewritten using some uniform mechanism.

**Comment by thockin** [comment]
agree

**Comment by smarterclayton** [comment]
Validation tests aren't in terrible shape.  It could be better, but so could lots of things.  Re-open if you disagree.
