### ISSUE TITLE
NotFound errors do not line up with API endpoint's group version

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#48959]
Currently it is possible to `GET` a specific `resource.group` and have the `NotFound` response point to a different group:

```
$ oc get deployments.apps foo --loglevel=6
...
GET https://10.13.129.233:8443/apis/apps/v1beta1/namespaces/default/deployments/foo 404 Not Found in 56 milliseconds
I0714 15:41:43.563012   18990 helpers.go:205] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "deployments.extensions \"foo\" not found",
  "reason": "NotFound",
  "details": {
    "name": "foo",
    "group": "extensions",
    "kind": "deployments"
  },
  "code": 404
}]
F0714 15:41:43.563052   18990 helpers.go:119] Error from server (NotFound): deployments.extensions "foo" not found
```

This is because `registry.Store` uses the `QualifiedResource`'s group information in `NotFound` errors instead of the current endpoint's group information.

@kubernetes/sig-api-machinery-misc

**Comment by sttts** [comment]
We have the request context to get the request info which then has the endpoint `GroupResource`.

**Comment by shiywang** [comment]
@sttts @enj I would like to take a look this one, could you assign to me ?

**Comment by liggitt** [comment]
I think I would have expected distinct rest stores serving the two groups, each with their own qualifiedresource

**Comment by deads2k** [comment]
> I think I would have expected distinct rest stores serving the two groups, each with their own qualifiedresource

Why wouldn't we want to share most of the storage.  The same get,list,watch caches as a for instance.

**Comment by lavalamp** [comment]
@enj how is this impacting you?

**Comment by enj** [comment]
@lavalamp see openshift/origin/issues/15213
