### ISSUE TITLE
Need to enforce RWO for FC PV

### ISSUE THREAD

**Issue by rootfs** [kubernetes/kubernetes#48953]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
RWO FC PV is not enforced. As a result, such PV can be attached to multiple nodes and led to data corruption.

**What you expected to happen**:
RWO FC PV should be single attached

**How to reproduce it (as minimally and precisely as possible)**:
- Create a FC PV
- Create 2 Pods that claim this FC PV
- If Pods are running on different nodes, the PV is multi attached

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xingzhou** [comment]
I think #47333 might cover this
