### ISSUE TITLE
Make the cluster-id tag required for aws

### ISSUE THREAD

**Issue by rrati** [kubernetes/kubernetes#48954]
/kind feature

A Kubernetes cluster in AWS can run without the cluster-id being set on nodes, but odd issues can pop up.  If multiple clusters exist in the same AZ under the same user account, then things can get even more interesting.  We should make tagging the AWS instances required and fail to start the cluster if they are not set.  If either KubernetesCluster or kubernetes.io/cluster is set then the cluster will start, otherwise print an error indicating the instances need to be tagged.

There should be a flag to support legacy behavior (ie no labeling needed).   This flag should be on one or more of:

kube-apiserver
kube-controller-manager
cloud-controller-manager

@kubernetes/sig-aws-misc @justinsb

**Comment by wongma7** [comment]
cc https://github.com/kubernetes/kubernetes/issues/48504 . When an AWS cluster is not tagged, volumes may get provisioned in zones outside cluster and they'll be unexpectedly unusable by the user

**Comment by rrati** [comment]
I am working on this
