### ISSUE TITLE
no generator for statefulset and daemonset

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/kubernetes#48957]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: There is no generator for statefulset and daemonset listed [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory_client_access.go#L461-L488).

**What you expected to happen**: There is one for statefulset and daemonset.

**How to reproduce it (as minimally and precisely as possible)**: N/A

**Anything else we need to know?**: Having the generator will facilitate testing.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by crimsonfaith91** [comment]
@mengqiy 
/sig cli

**Comment by mengqiy** [comment]
I think it is a feature rather than a bug.
/kind feature
/remove kind feature

Not sure if there are any concern to add generator for statefulset and daemonset?
@kubernetes/sig-apps-feature-requests Thoughts?

**Comment by crimsonfaith91** [comment]
@mengqiy Thanks for correcting it! :)
