### ISSUE TITLE
Discovery is missing shortNames for svc and netpol

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#48962]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: API discovery is missing `shortNames` for `svc` and `netpol`

**What you expected to happen**: it ideally shouldn't be missing, as these are defined [here](https://github.com/kubernetes/kubernetes/blob/b1040171b68217dccb617de85defa4a5063c638b/pkg/kubectl/kubectl.go#L46-L141), which is used by `kubectl` when resolving shortcuts (in addition to the dynamic discovery information).

**How to reproduce it (as minimally and precisely as possible)**:

1. `curl $apiserver/api/v1` - `services` has `null` for `shortNames`
1. `curl $apiserver/apis/extensions/v1beta1` - `networkpolicies` has `null` for `shortNames`

**Anything else we need to know?**:

For services, the serviceRESTStorage object created [here](https://github.com/kubernetes/kubernetes/blob/b1040171b68217dccb617de85defa4a5063c638b/pkg/registry/core/rest/storage_core.go?utf8=%E2%9C%93#L145) does implement the required `ShortNames()` function correctly, but this isn't the REST storage that's directly installed into the apiserver. Instead, it gets wrapped inside a `service.Registry` and then passed to a wrapper REST storage [here](https://github.com/kubernetes/kubernetes/blob/b1040171b68217dccb617de85defa4a5063c638b/pkg/registry/core/rest/storage_core.go?utf8=%E2%9C%93#L180), which ultimately ends up getting installed [here](https://github.com/kubernetes/kubernetes/blob/b1040171b68217dccb617de85defa4a5063c638b/pkg/registry/core/rest/storage_core.go?utf8=%E2%9C%93#L198). I'm guessing that because `serviceRESTStorage` isn't directly installed, its `ShortNames()` implementation isn't available and it's not being used.

For networkpolicies, we just need to implement `ShortNames()`.

cc @deads2k @liggitt @timothysc @skriss @jbeda

**Comment by ncdc** [comment]
cc @kubernetes/sig-api-machinery-bugs

**Comment by supereagle** [comment]
@ncdc  Your analysis is right. If you are not working on this, I think I can submit a PR to fix it.

**Comment by ncdc** [comment]
I am not currently working on this. If you have time, we'd definitely
appreciate the help. Thanks!

**Comment by lavalamp** [comment]
SIG API Machinery doesn't own the *contents* of the API.
