### ISSUE TITLE
If node is unreachable, also set NetworkUnavailable/InodePressure to Unknown

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#48982]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

If node is unreachable, NodeController only set `v1.NodeOutOfDisk`, `v1.NodeMemoryPressure`, `v1.NodeDiskPressure` to unknown; it's better to also set NetworkUnavailable & InodePressure to unknown.

**Comment by xiangpengzhao** [comment]
Isn't `NetworkUnavailable` a known condition if node is unreachable?

**Comment by k82cn** [comment]
`NetworkUnavailable` is the status of container, e.g. CNI is not ready. If node is unreachable, it should be Unknown.

**Comment by xiangpengzhao** [comment]
Thanks for explanation!

**Comment by k82cn** [comment]
will not set NetworkUnavailable & InodePressure to unknown, refer to https://github.com/kubernetes/kubernetes/pull/48983#issuecomment-315624739 .
