### ISSUE TITLE
Refactor NodeController to use evictor objects instead of flag

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#48987]
**Is this a BUG REPORT or FEATURE REQUEST?**:
enhancement/cleanup

/kind feature

**Description**:
NodeController uses `useTaintBasedEvictions` to distinguish taint-based-eviction and default-pod-eviction; this tag is scattered around the code :(. The proposal is to create an interface `Evictor` and two implementation: TaintEvictor & DefaltEvictor for code cleanup.

**Comment by k82cn** [comment]
no sig own NodeController now; added to sig-node temporarily :).

**Comment by gmarek** [comment]
I think it's more a cleanup that feature. Also as we're most likely going to remove 'normal eviction' after 'taint-based eviction' are in GA I'm not completely convinced that it's worth doing. But if someone has free cycles then by all means he/she's free to do it, as this is a good pattern.

**Comment by tcharding** [comment]
May I please verify this with you @k82cn? Is the idea that for each occurrence of an if/else branch on `useTaintBasedEvictions` add a method to the interface and and then have the two concrete types implement the method with the respective logic from the original if/else branch?

**Comment by k82cn** [comment]
> have the two concrete types implement the method with the respective logic from the original if/else branch

Yes :).

**Comment by tcharding** [comment]
Commenting again to save you too much effort in replying @k82cn, I'm guessing we are in different timezones. I have implemented the changes as outlined in my question above. I want to clean the commits up a bit and then I'll submit a WIP PR tomorrow after I've had some sleep.

**Comment by tcharding** [comment]
That was weird, your reply wasn't visible until I hit `comment`. Excuse the noise.
