### ISSUE TITLE
spurious changes in types.generated.go with hack/update-all.sh

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#48984]
I'm seeing changes show up in types.generated.go when running hack/update-all.sh that are unrelated to the changes I'm making, and cause CI to fail.

Example:
https://github.com/kubernetes/kubernetes/pull/45294/commits/4774babcacf1d8ae34e2300c8cc48f1ad6ca77bc#diff-84c1f4a54ef63a83dfee0975f6895d71
https://k8s-gubernator.appspot.com/pr/45294
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45294/pull-kubernetes-verify/39502/

I ran with my PR rebased on latest master, ran `make clean` and `hack/godep-restore.sh` first, am running go1.8.3, etc

cc @caesarxuchao @sttts

**Comment by caesarxuchao** [comment]
Perhaps it's because https://github.com/kubernetes/kubernetes/blob/master/hack/update-codecgen.sh#L74-L75 and that we moved the types.go to k8s.io/api.

`my_prefix` was added in https://github.com/kubernetes/kubernetes/pull/25240. I don't understand why we needed to limit the tsort within k8s.io/kubernetes. @thockin do you remember? Can we just update my_prefix to `vendor/k8s.io/api` to fix the problem?

**Comment by sttts** [comment]
The changes in the conversion do not look like a wrong generation order.

Can it be that we are just hitting https://github.com/kubernetes/kubernetes/issues/48675 when switching between branches?

**Comment by liggitt** [comment]
the changes in conversion are expected, and CI is not complaining about those.

the changed in types.generated.go are the issue - https://github.com/kubernetes/kubernetes/commit/4774babcacf1d8ae34e2300c8cc48f1ad6ca77bc#diff-84c1f4a54ef63a83dfee0975f6895d71

**Comment by sttts** [comment]
ic. ugorji....

**Comment by liggitt** [comment]
`git ls-files --others` doesn't show any untracked files related to generation or types or anything else

**Comment by sttts** [comment]
The ugorji build order looks wrong:
```
processing ./vendor/k8s.io/api//storage/v1beta1/types.go
processing ./vendor/k8s.io/api//rbac/v1beta1/types.go
processing ./vendor/k8s.io/api//rbac/v1alpha1/types.go
processing ./vendor/k8s.io/api//policy/v1beta1/types.go
processing ./vendor/k8s.io/api//networking/v1/types.go
processing ./vendor/k8s.io/api//imagepolicy/v1alpha1/types.go
processing ./vendor/k8s.io/api//extensions/v1beta1/types.go
processing ./vendor/k8s.io/api//core/v1/types.go
processing ./vendor/k8s.io/api//certificates/v1beta1/types.go
processing ./vendor/k8s.io/api//batch/v2alpha1/types.go
processing ./vendor/k8s.io/api//batch/v1/types.go
processing ./vendor/k8s.io/api//autoscaling/v2alpha1/types.go
processing ./vendor/k8s.io/api//autoscaling/v1/types.go
processing ./vendor/k8s.io/api//authorization/v1beta1/types.go
processing ./vendor/k8s.io/api//authorization/v1/types.go
processing ./vendor/k8s.io/api//authentication/v1beta1/types.go
processing ./vendor/k8s.io/api//apps/v1beta1/types.go
processing ./vendor/k8s.io/api//admissionregistration/v1alpha1/types.go
processing ./vendor/k8s.io/api//admission/v1alpha1/types.go
processing ./pkg/kubectl/testing/types.go
processing ./pkg/controller/garbagecollector/metaonly/types.go
processing ./pkg/apis/admission/types.go
processing ./federation/apis/federation/v1beta1/types.go
processing ./cmd/libs/go2idl/client-gen/test_apis/testgroup/v1/types.go
processing ./vendor/k8s.io/metrics//pkg/apis/metrics/v1alpha1/types.go
processing ./vendor/k8s.io/metrics//pkg/apis/metrics/types.go
processing ./vendor/k8s.io/metrics//pkg/apis/custom_metrics/v1alpha1/types.go
processing ./vendor/k8s.io/metrics//pkg/apis/custom_metrics/types.go
processing ./vendor/k8s.io/apiserver//pkg/storage/testing/types.go
processing ./vendor/k8s.io/apiserver//pkg/endpoints/testing/types.go
processing ./vendor/k8s.io/apiserver//pkg/apis/example/v1/types.go
processing ./vendor/k8s.io/apiserver//pkg/apis/audit/v1alpha1/types.go
```

Core should be after batch and extensions as the later two depend on core/v1.

**Comment by liggitt** [comment]
as @caesarxuchao pointed out, the sort does not include things under k8s.io/api, so it's not surprising it is wrong.

I tried briefly to modify that to include the types where they live now, and didn't have great success

**Comment by liggitt** [comment]
it's also possible the sort is getting confused on package names with/without 'vendor'

**Comment by sttts** [comment]
The tsort is broken. Am on it.

**Comment by liggitt** [comment]
yeah, just got there:
```
DBG: does ./vendor/k8s.io/apiserver//pkg/apis/audit/v1alpha1/types.go depend on k8s.io/kubernetes/vendor/k8s.io/api//core/v1?
...
DBG:   checking against k8s.io/kubernetes/vendor/k8s.io/api/core/v1
...
DBG: = no
```

> Am on it.

thanks

**Comment by ericchiang** [comment]
I'm also seeing issues with protobuf generation scripts on master (hit this in https://github.com/kubernetes/kubernetes/pull/48836).

Running `./hack/update-generated-protobuf.sh` creates this diff:

```
$ git rev-parse HEAD
c9ab8108030e8686f05364bf5c4dfb7baf2f9661
$ git status
On branch master
Your branch is ahead of 'origin/master' by 3816 commits.
  (use "git push" to publish your local commits)
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	pkg/apis/admission/v1alpha1/generated.proto
	pkg/apis/admission/v1alpha1/zz_generated.deepcopy.go

nothing added to commit but untracked files present (use "git add" to track)
```

Don't know if this is related.

**Comment by caesarxuchao** [comment]
@ericchiang i had a PR merged in which i moved admission to k8s.io/api, I guess you saw those files after rebase? You can remove those two untracked files.
