### ISSUE TITLE
Consider splitting CHANGELOG in separate files

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#48985]
The CHANGELOG becomes longer and longer as we have more and more releases (though we remove some oldest releases changelog). It also has bad order of releases (not listed by version but release date). This make it hard to read.

How about splitting it?

- create a sub-dir `CHANGELOG` in repo root
- every release has its own changelog file with name `version name.md` in the above dir.
- the changelog files will be listed by version name automatically.

/sig release
/cc @dchen1107

**Comment by caesarxuchao** [comment]
I agree with the idea, but i don't have the bandwidth to implement it.

/unassign @caesarxuchao

**Comment by zhangxiaoyu-zidif** [comment]
I agree with it! That will be easy to find focused release. No need to scroll mouse for a long long time...

**Comment by varunkashyap4dg** [comment]
I looked into this. Splitting the file into multiple files is easy - though laborious. I have a question about where does CHANGELOG.md ties into the document munging scripts? I suppose those would need updates too? So can someone point me to the design of how munging of documents happens?

**Comment by xiangpengzhao** [comment]
cc @kubernetes/sig-release-members

**Comment by varunkashyap4dg** [comment]
@xiangpengzhao actually I already ran it through folks at sig-release and sig-testing this morning. There in it was decided to also comment here to see if there is more info!

**Comment by xiangpengzhao** [comment]
@varunkashyap4dg Thanks!

BTW, I take a quick search and find that some scripts would be influenced by this.

https://github.com/kubernetes/release/blob/master/changelog-update

https://github.com/kubernetes/release/blob/master/anago

https://github.com/kubernetes/release/blob/master/relnotes

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-release-feature-requests

**Comment by CallMeFoxie** [comment]
So it seems that github does not show >1MB files online so we've reached 
```
View Raw
(Sorry about that, but we can’t show files that are this big right now.)
```
stage

I'd say splitting is a good idea sooner rather than later :)

**Comment by xiangpengzhao** [comment]
@CallMeFoxie yeah, seems like we do have to split the CHANGELOG ASAP, at least before we release 1.8. We may also need to modify the scripts I mentioned above accordingly.

@jdumars @kubernetes/sig-release-feature-requests any thoughts?

**Comment by jdumars** [comment]
@abgworrall @calebamiles @ericchiang unfortunately, this work cannot wait, so we need to slot it into blocking items.

**Comment by david-mcmahon** [comment]
Just seeing this now.  Yes, this idea was raised a few times back in 2016.  I have been a big proponent of doing this. I'm glad there's more interest now.  Subdirs is one option.  CHANGELOG-1.N (per branch) at the top level may also be desirable to keep it at the top level dir.

**Comment by abgworrall** [comment]
@dchen1107 suggested moving the 1.2 work into a separate (temporary) `CHANGELOG-1.2.md` file, rather than delete it outright, if we're after a temporary change today. SGTM.

**Comment by abitrolly** [comment]
Could all [phased out milestones](https://github.com/kubernetes/kubernetes/milestones) be archived into `CHANGELOG-1.x.md` automatically during release process?

**Comment by david-mcmahon** [comment]
@abitrolly The simpler implementation would be to just maintain CHANGELOG-1.x.md per minor release.  Less moving parts.

**Comment by abitrolly** [comment]
@david-mcmahon indeed. I'd also wish to have a release notes with interesting highlights on top of each log for minor version.
