### ISSUE TITLE
kubelet "Unable to mount volumes" for short lived pod that ran to completion/mounted volumes successfully

### ISSUE THREAD

**Issue by vdavidoff** [kubernetes/kubernetes#48998]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
While reviewing kubelet logs after a 1.6.0 -> 1.7.1 upgrade, I noticed errors indicating failure to attach volumes to a pod (spawned by a cronjob) for which I know the volume attachment was successful. These errors show up after the only container in the pod has already exited, with its execution and kubelet logging prior to these errors all indicating there was no issue with these volumes. The only non-sandbox container in the pod is very short lived (~300ms) and I think that could be a factor here.

Looking back through older logs, it appears as though this is _not_ new for 1.7.1, and occurred in 1.6.0 as well.

```
E0716 12:32:13.958184    2898 kubelet.go:1621] Unable to mount volumes for pod "kube-cronjob-cleanup-cronjob-1500208200-xtdb1_default(818db162-6a22-11e7-a6cf-00163e215c33)": timeout expired waiting for volumes to attach/mount for pod "default"/"kube-cronjob-cleanup-cronjob-1500208200-xtdb1". list of unattached/unmounted volumes=[config cluster-nfs-storage-root default-token-pr6lq]; skipping pod
E0716 12:32:13.958235    2898 pod_workers.go:182] Error syncing pod 818db162-6a22-11e7-a6cf-00163e215c33 ("kube-cronjob-cleanup-cronjob-1500208200-xtdb1_default(818db162-6a22-11e7-a6cf-00163e215c33)"), skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"kube-cronjob-cleanup-cronjob-1500208200-xtdb1". list of unattached/unmounted volumes=[config cluster-nfs-storage-root default-token-pr6lq]
```

**What you expected to happen**:
Since the pod already ran to completion and was entirely successful, including in its handling of these volumes, I wouldn't expect to see errors about the volumes at this stage.

**How to reproduce it (as minimally and precisely as possible)**:
It looks like this happens whenever I have a short lived pod (internal logging suggests it runs for 300ms from init to exit) that is spawned by a cronjob and mounts a configmap, secret, and NFS share. I suspect that it's the short-liveness of the pod that's a factor, but I'm not sure.

**Anything else we need to know?**:
For a little more context, given the pod above, here's the logging showing the mounts being successfully attached, and when the container that mounted them was destroyed (after successfully running to completion).

```
I0716 12:30:09.468445    2898 operation_generator.go:472] MountVolume.SetUp succeeded for volume "config" (UniqueName: "kubernetes.io/configmap/818db162-6a22-11e7-a6cf-00163e215c33-config") pod "kube-cronjob-cleanup-cronjob-1500208200-xtdb1" (UID: "818db162-6a22-11e7-a6cf-00163e215c33") 
I0716 12:30:09.527663    2898 operation_generator.go:472] MountVolume.SetUp succeeded for volume "default-token-pr6lq" (UniqueName: "kubernetes.io/secret/818db162-6a22-11e7-a6cf-00163e215c33-default-token-pr6lq") pod "kube-cronjob-cleanup-cronjob-1500208200-xtdb1" (UID: "818db162-6a22-11e7-a6cf-00163e215c33") 
I0716 12:30:09.594366    2898 operation_generator.go:472] MountVolume.SetUp succeeded for volume "cluster-nfs-storage-root" (UniqueName: "kubernetes.io/nfs/818db162-6a22-11e7-a6cf-00163e215c33-cluster-nfs-storage-root") pod "kube-cronjob-cleanup-cronjob-1500208200-xtdb1" (UID: "818db162-6a22-11e7-a6cf-00163e215c33") 

I0716 12:30:10.736459    2898 manager.go:970] Destroyed container: "/kubepods/besteffort/pod818db162-6a22-11e7-a6cf-00163e215c33/606ba3081a7189604754f3a2ea2b98548b8ef1fe6b28ba45110ae71c53bed650" (aliases: [k8s_kube-cronjob-cleanup-cronjob_kube-cronjob-cleanup-cronjob-1500208200-xtdb1_default_818db162-6a22-11e7-a6cf-00163e215c33_0 606ba3081a7189604754f3a2ea2b98548b8ef1fe6b28ba45110ae71c53bed650], namespace: "docker")

I0716 12:30:11.760824    2898 kubelet_pods.go:936] Killing unwanted pod "kube-cronjob-cleanup-cronjob-1500208200-xtdb1"
I0716 12:30:11.762352    2898 plugins.go:412] Calling network plugin kubernetes.io/no-op to tear down pod "kube-cronjob-cleanup-cronjob-1500208200-xtdb1_default"
I0716 12:30:11.789600    2898 manager.go:970] Destroyed container: "/kubepods/besteffort/pod818db162-6a22-11e7-a6cf-00163e215c33/c398a9c84581d91a2ddb00c2fefb183834d4ff4b0f1edb6b99230260093ffb47" (aliases: [k8s_POD_kube-cronjob-cleanup-cronjob-1500208200-xtdb1_default_818db162-6a22-11e7-a6cf-00163e215c33_0 c398a9c84581d91a2ddb00c2fefb183834d4ff4b0f1edb6b99230260093ffb47], namespace: "docker")
```

Note that the sandbox container is cleaned up about 1 second after the primary container has exited (`I0716 12:30:11.760824`).

The logging from inside the container (i.e. the `command`) indicate it started at `[2017-07-16 12:30:10,436]` and ended at `[2017-07-16 12:30:10,694]`.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.1
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): Ubuntu 14.04
- Kernel (e.g. `uname -a`): Linux REDACTED 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Server/client binaries installed from binary releases, core (apiserver, controller-manager, scheduler) running in hyperkube, built by me from official release sources
- Others:

**Comment by vdavidoff** [comment]
Not to confuse the issue, but I just found errors in the `controller-manager` logs that I think might also be similar in that they could be related to the short-liveness of the container/pod. These are happening for the same pod in both 1.6.0 and 1.7.1.

```
E0716 18:30:09.122339       1 jobcontroller.go:277] Error syncing job: Operation cannot be fulfilled on jobs.batch "kube-cronjob-cleanup-cronjob-1500229800": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by bcorijn** [comment]
I see these kind of logs as well on very short lived pods on Kube 1.6 btw. I have a very lightweight container that boots, does a REST call and then exits. I regularly see logs like this one:
```
Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "nautilus"/"nautilus-nautilus-facjd-6dltw". list of unattached/unmounted volumes=[default-token-d819h]
```
I assume the asynchronous mounting of the volume is just too slow for the short lived container..

**Comment by edude03** [comment]
I'm seeing this issue with cronjobs on Kubernetes 1.7.0 as well. Interestingly, I do see this on long lived containers as well.

**Comment by huaixichen** [comment]
any update on this issue?
