### ISSUE TITLE
Implement ipvs util package

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#48992]
PR #46580 "Implement IPVS-based in-cluster service load balancing" looks a bit huge and it's not easy to review. I admit PR #46580 has many files changed and it costs time to review and fix comments. Should we split the original work into small ones and do that one by one?

In my view, PR #46580 can be cut into at least 2 smaller ones - implementing ipvs util package and godeps = 1 PR, main part of implementing ipvs mode for kube-proxy = 1 PR.

This issue is about the work of "implementing ipvs util package and godeps", hopefully can make it easier to review.

Once this work is done, we may step into reviewing the "main part of implementing ipvs mode for kube-proxy"?

@thockin Please let me know if it helps you reviewing the ipvs work. Thanks!

@haibinxie @quinton-hoole @bowei @kevin-wangzefeng @deepak-vij @dhilipkumars

/sig network

**Comment by bowei** [comment]
yes -- splitting into consumable independent piece is the best (fastest) way to get code reviewed.

**Comment by m1093782566** [comment]
I am closing this PR.
