### ISSUE TITLE
Exported staging repos are not tagged

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#49011]
We synchronize master and release *branches* between the k8s.io/kubernetes repo and the staging repos (k8s.io/api, k8s.io/apiserver, ...), but we don't tag the later on releases. Everybody vendoring the staging repos has to manually extract the right revision somehow, e.g. via the `kubernetes-sha`.

IMO we should add tagging of the staging repos to the release process.

**Comment by caesarxuchao** [comment]
cc @rmmh

**Comment by sttts** [comment]
Fixed, as far as the publishing bot runs (or doesn't run) nightly.
