### ISSUE TITLE
API changes devel doc is (very) outdated

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#49023]
E.g. it still refers to `pkg/api/v1/...`
Just take a look: https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md#changing-versioned-apis

@kubernetes/sig-api-machinery-bugs

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by caesarxuchao** [comment]
We have https://github.com/kubernetes/community/pull/788
