### ISSUE TITLE
Initializer.FailurePolicy default value not documented

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes#49030]
[`Initializer.FailurePolicy` field does not document](https://kubernetes.io/docs/api-reference/v1.7/#initializer-v1alpha1-admissionregistration):
- the 1.7 limitation (only "Ignore" can be used): not sure if fixing this is any worthy as it'll show up in the next minor release, which would probably put the feature to beta
- default value of the field: should be specified. it appears like it's "Ignore" currently but I am not sure what it will be once the feature is beta+.

> ![image](https://user-images.githubusercontent.com/159209/28279139-604a6b80-6ad4-11e7-8568-63612b89ebf1.png)

/assign @caesarxuchao 
/sig api-machinery
/kind documentation

**Comment by munnerz** [comment]
+1 - I spent 10m scratching my head the other day as my resources were still be created after a timeout error was returned by `kubectl create`. It'd be good to either make this error message better (e.g. `Initialization of this resource failed, resource was created anyway`) and to document this default!

**Comment by caesarxuchao** [comment]
The failure policy field is removed in 1.8 (https://github.com/kubernetes/kubernetes/pull/51300). Slow-to-initialize objects are not deleted.

Closing the issue since the field doesn't exist anymore.
