### ISSUE TITLE
kubectl get: does not show uninitialized resources

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes#49032]
With the addition of dynamic admission controllers and [Initializers](https://kubernetes.io/docs/admin/extensible-admission-controllers/#what-are-initializers), it's very likely that users will create deployments but their `kubectl get pods` output will not show any pods being created because it's stuck at some initializer.

kubectl should provide a way to query resources that are pending initialization as well (`?includeUninitialized=true`). Currently the only way is to query them via the API manually.

Perhaps a `kubectl get <resource> --show-uninitialized` would help.

/sig cli
/kind feature

**Comment by dixudx** [comment]
I've submitted a PR #50445. PTAL.

**Comment by gyliu513** [comment]
This was already fixed in https://github.com/kubernetes/kubernetes/pull/50497 , I think we can close this now. @ahmetb @dixudx

**Comment by dixudx** [comment]
@gyliu513 Yes. We've already implemented this. Please close it. Thanks.

**Comment by gyliu513** [comment]
I think @ahmetb can help close.

**Comment by dixudx** [comment]
ping @ahmetb to close this.
