### ISSUE TITLE
Remove --insecure-allow-any-token authenticator

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#49031]
/kind feature

Impersonation is sufficiently capable that this method seems redundant, even when debugging.

@deads2k I remember you were the one who originally requested this. Any objections to removing?

/cc @kubernetes/sig-auth-feature-requests

**Comment by deads2k** [comment]
> @deads2k I remember you were the one who originally requested this. Any objections to removing?

Yeah, I made it.  I'm ok removing it.

**Comment by ynux** [comment]
Thanks for removing this. This makes one of the CIS benchmark controls for  Kubernetes superfluous (https://www.cisecurity.org/cis-benchmarks/)
