### ISSUE TITLE
Initializer configs can block initializers from being deployed

### ISSUE THREAD

**Issue by kelseyhightower** [kubernetes/kubernetes#49048]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind feature

**What happened**:

Deployed an initializer with an initializer configuration in place.

**What you expected to happen**:

The initializer would deploy even if an initializer configuration was in place.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create an initializer configuration that forces all deployments to be initialized. 
2. Deploy an initializer controller using a deployment.

Example initializer: https://github.com/kelseyhightower/kubernetes-initializer-tutorial

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration**:

```
GKE
```

**Comment by kelseyhightower** [comment]
While we could ask people to create the initializer deployments before initializer-configurations, if they get it wrong then objects, including the initializer will be stuck in the API.

**Comment by caesarxuchao** [comment]
When creating the deployment of the initializer controller, the admin should explicitly set the initializer field of the deployment to an empty list, so that it bypass the intializers.

We should document this.

**Comment by kelseyhightower** [comment]
@caesarxuchao  Thanks! I'll add that to my tutorial.

**Comment by smarterclayton** [comment]
A couple of ideas that have been kicked around:

* have exclusions in the initializer config for namespace (or an annotation
on a namespace that can bypass certain initializers)
* namespaces have to opt in to certain initializer configs
* apps have to opt in to certain initializer configs
* fail open

I hate fail open because it ends up being non-deterministic :)

**Comment by kelseyhightower** [comment]
It really depends on the target usage. If an initializer is being used to enforce a company policy then we need to make it "impossible" to opt out. If an initializer is being used for an optional configuration like injecting an envoy side car container, then we need to make it opt-in.

I think this needs to be defined in the  initializer config for consistency.

**Comment by smarterclayton** [comment]
Yeah, today you have to be an initializer yourself to bypass initialization
(you have to have the same permissions you would to initialize that
resource).

**Comment by mikkeloscar** [comment]
Has there been any further thoughts on this?

I'm designing an initializer controller that is injecting stuff into pods. If it works well it would be deployed to 80 clusters which do regular node updates where all nodes/pods are rotated. So it's pretty clear that modifying the controller pods manually every time to make it run will not scale :)

If I could white list certain resources on a per namespace basis this would be enough. Note it can't be white listed by name as I would not know the pod name of the controller ahead of time (when deployed as a deployment).

**Comment by caesarxuchao** [comment]
Please check out the [admission webhooks](http://blog.kubernetes.io/2018/01/extensible-admission-is-beta.html), a beta feature, as an alternative to initializers feature.

Also webhooks provide a [namespaceSelector](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/admissionregistration/v1beta1/types.go#L193) to blacklist/whitelist based on namespaces.
