### ISSUE TITLE
Several API type strategies have Export func that may be unused

### ISSUE THREAD

**Issue by dgoodwin** [kubernetes/kubernetes#49042]
/kind bug

**What happened**:

Secrets have some export logic in their strategy, but does not appear to take effect on the command line when doing a kubectl get --export.

**What you expected to happen**:

Some kind of error given the condition in the secret strategy mentioned below. However it appears the secret strategy Export function may not be wired up. (as well as several other types)

**How to reproduce it (as minimally and precisely as possible)**:

```
$ kubeadm init
$ kubectl get secret default-token-w5cs4 -o yaml --export
```

No error is thrown, some generic metadata is stripped but the code is happy to export the object despite the fact that it violates the condition mentioned below.

**Anything else we need to know?**:

In the generic registry Store we can see the main place where exports should be run:

https://github.com/kubernetes/kubernetes/blob/10dc1aac61f8f2e9a9381a525289d8ae87ba0cc9/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L1227

This ExportStrategy is set in a handful of strategies, such as:

https://github.com/kubernetes/kubernetes/blob/10dc1aac61f8f2e9a9381a525289d8ae87ba0cc9/pkg/registry/core/limitrange/storage/storage.go#L46

In addition to limitrange we find similar for node, podtemplate, and service strategies.

However several other strategies have an Export function defined matching: Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error

```
(dgoodwin@wrx {master} ~/go/src/k8s.io/kubernetes) $ git grep Export | grep Context | grep Object | grep bool
pkg/registry/certificates/certificates/strategy.go:func (s csrStrategy) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
pkg/registry/core/limitrange/strategy.go:func (limitrangeStrategy) Export(genericapirequest.Context, runtime.Object, bool) error {
pkg/registry/core/node/strategy.go:func (ns nodeStrategy) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
pkg/registry/core/podtemplate/strategy.go:func (podTemplateStrategy) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
pkg/registry/core/secret/strategy.go:func (s strategy) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
pkg/registry/core/service/strategy.go:func (svcStrategy) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
pkg/registry/rbac/clusterrole/strategy.go:func (s strategy) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
pkg/registry/rbac/clusterrolebinding/strategy.go:func (s strategy) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
pkg/registry/rbac/role/strategy.go:func (s strategy) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
pkg/registry/rbac/rolebinding/strategy.go:func (s strategy) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store_test.go:func (t testPodExport) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
staging/src/k8s.io/apiserver/pkg/registry/rest/export.go:       Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error
```

Looking specifically at the Secret strategy: https://github.com/kubernetes/kubernetes/blob/10dc1aac61f8f2e9a9381a525289d8ae87ba0cc9/pkg/registry/core/secret/strategy.go#L79

It appears that this Export method may not be wired up and thus is unused. In testing with kubectl on the API, it appears we cannot get the condition on line 90 in the link above to trigger even if trying to kubectl get --export secrets X where X is of type kubernetes.io/service-account-token, or is tied to a service account by UID.

This may imply that secret, clusterrole, clusterrolebinding, role, and rolebinding strategies all have an Export function defined that is not used.

The fix might just be as simple as setting ExportStrategy in places such as: https://github.com/kubernetes/kubernetes/blob/10dc1aac61f8f2e9a9381a525289d8ae87ba0cc9/pkg/registry/core/secret/storage/storage.go#L44

If so please let me know and I will try to pursue unit tests and a fix for each.

**Environment**:
- Kubernetes version (use `kubectl version`): 
  ```
  Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T02:00:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T01:48:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
  ```

- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`): Linux centos1.aos.example.com 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm, oc

**Comment by dgoodwin** [comment]
CC @deads2k @csrwng

**Comment by deads2k** [comment]
This bug demonstrates that the export feature isn't heavily used yet and may give us a chance to consider what we really need the export API to look like.  The original idea was sound, "give me a representation of this object that I can re-use", but the full intent is less clearly defined.  Re-use how?

Object linkage is a complicated thing and questions like "same cluster' or "different cluster" start to change how you expect the export to look for items like PVCs or anything else that isn't fully contained in a single namespace.  In addition, the API isn't well suited to handle things like "export all my secrets" since there is no way to simply exclude non-exportable entities instead of straight out failing.

I think it's a good idea to fix the code that is broken, but I think we should take the time to consider how the API should grow to accommodate the known use-cases.  The simplest change would be to switch the bool for a string and start by only allowing true/false.

**Comment by lavalamp** [comment]
cc @mml

**Comment by dgoodwin** [comment]
Does this look like the right track? (repeat for the other types not wired up)
https://github.com/dgoodwin/kubernetes/commit/9dee7698302b575cc7e16277912f976f173199da

**Comment by deads2k** [comment]
> Does this look like the right track? (repeat for the other types not wired up)

Yes, though I'd prefer having the unit test on the strategy method itself.  I think we should also create a test that runs against a storage map (constructed in the apiserver) and checks to see that the "normal" strategies are set with a whitelist for the exceptions.

**Comment by dgoodwin** [comment]
The strategy does have tests for the actual export logic itself, this bug was in the store and I couldn't see any way to test it at the strategy level. I will investigate testing the storage map, that would probably cover it.

**Comment by dgoodwin** [comment]
Half tempted to validate each store in the map and if Create/Update/DeleteStrategy satisfies the Export interface but ExportStrategy is nil, we fail the test. That would miss if someone were setting a different strategy object for export than the others, but then of course ExportStrategy would obviously be getting set and thus no bug.

**Comment by dgoodwin** [comment]
@deads2k running into some issues trying to test at the level you suggested, some of them are arguably indicating problems in how exporters are structured right now. 

In pkg/registry/core/rest.LegacyRESTStorageProvider we have a map of strings to apiserver/pkg/registry/rest.Storage. That interface doesn't define much of interest for Export. We can check that these objects satisfy rest.Exporter but they do by default as apiserver/pkg/registry/generic/registry.Store defines an Export method, and all objects are exportable by default.

registry.Store adds another layer of export logic inside it's Export method, if ExportStrategy is defined we call that in addition to the default export logic.

At the pkg/registry/core/rest.LegacyRESTStorageProvider things do not look good for unit testing. We can't type check to get this to a concrete registry.Store as far as I can tell (still quite new to go but it looks this way to me), I'm about to try reflection to see if the underlying type has a ExportStrategy field, but at this point something feels quite off in going to these lengths to unit test this.

I think a more significant refactor is required, or we need to take another approach with testing. Will try to come up with some proposals tomorrow.

**Comment by dgoodwin** [comment]
Possible suggestion via @Miciah was to add a HasExportStrategy bool or ExportStrategy (getter) to the Exporter interface, allowing us to test if a given rest.Storage implements Exporter, and if so call that method to make sure it has the custom logic defined.

**Comment by dgoodwin** [comment]
PR up with a different approach that felt better than the one in previous comment.
