### ISSUE TITLE
kubectl annotate patches too much

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#49044]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I used `kubectl --v=10 annotate` to learn about patching object metadata, and was surprised to find more than the metadata in the PATCH request body.  Here is an example:
```
    $ kubectl --v=10 annotate pods mypod bar=foo
    ...
    I0717 18:55:21.106675  161234 request.go:991] Request Body: {"metadata":{"annotations":{"bar":"foo"}},"status":{"conditions":[{"lastProbeTime":null,"lastTransitionTime":"2017-07-14T00:36:40Z","status":"True","type":"Initialized"},{"lastProbeTime":null,"lastTransitionTime":"2017-07-14T00:37:06Z","status":"True","type":"Ready"},{"lastProbeTime":null,"lastTransitionTime":"2017-07-14T00:36:40Z","status":"True","type":"PodScheduled"}]}}

    I0717 18:55:21.106795  161234 round_trippers.go:398] curl -k -v -XPATCH  -H "Content-Type: application/merge-patch+json" -H "User-Agent: kubectl/v1.6.4 (linux/amd64) kubernetes/d6f4332" -H "Accept: application/json" https://172.16.11.12:443/api/v1/namespaces/default/pods/mypod

    I0717 18:55:21.112228  161234 round_trippers.go:417] PATCH https://172.16.11.12:443/api/v1/namespaces/default/pods/mypod 200 OK in 5 milliseconds
```

**What you expected to happen**:
I expected to see my new annotation, but not the pod's status, in the request body.

**How to reproduce it (as minimally and precisely as possible)**:
I hope the above makes this clear.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.4 in client and server
- Cloud provider or hardware configuration**: bare metal install
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.4.0-34-generic
- Install tools: private Ansible
- Others: N/A

**Comment by MikeSpreitzer** [comment]
@sig-cli-bugs

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-cli-bugs

**Comment by mengqiy** [comment]
Can you provide the step to reproduce?

**Comment by MikeSpreitzer** [comment]
Just make a pod, then
```
$ kubectl --v=10 annotate pods $podname bar=foo
```

**Comment by dixudx** [comment]
The root cause is that when [creating a patch for merge](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/annotate.go#L255), [nil value](https://github.com/evanphx/json-patch/blob/master/merge.go#L204-L245) will be considered as different value. That's why `status` (due to `"lastProbeTime":null`) is in the request body.
