### ISSUE TITLE
GCE e2e tests have not passed since June.

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#49059]
Despite the name `etcd3`, this is not a special environment.  etcd3 has been the default for awhile.

https://k8s-testgrid.appspot.com/release-master-blocking#gce-etcd3

Example failure:  https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-etcd3/12735

This seems to be an infrastructure problem related to bringing the cluster up.

Assigning to test-infra oncall for assistance.

**Comment by mml** [comment]
cc @wojtek-t @pwittrock

**Comment by spxtr** [comment]
I don't have admin for that project. It looks like the pr-kubekins service account has Pub/Sub admin, which is not enough.

**Comment by spxtr** [comment]
@gmarek @wojtek-t can one of you two either give me access to the `k8s-jkns-e2e-etcd3` project or else fix the permissions for `pr-kubekins` and `kubekins` service accounts in that project?

**Comment by wojtek-t** [comment]
@spxtr - I just added you as an owner.

**Comment by spxtr** [comment]
Thanks, this *should* be fixed now.

**Comment by krzyzacy** [comment]
assume you don't want to make pr-kubekins as a project owner :-) Maybe run that internal version of check_project script instead.

**Comment by wojtek-t** [comment]
Yeah - seems to be fixed now.
