### ISSUE TITLE
kubeadm cannot work with machines that cannot resolve their own host

### ISSUE THREAD

**Issue by erikh** [kubernetes/kubernetes#49065]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

```
null_resource.kubeadm_join.1 (remote-exec): [kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
null_resource.kubeadm_join.1 (remote-exec): [preflight] Running pre-flight checks
null_resource.kubeadm_join.0 (remote-exec): [preflight] Some fatal errors occurred:
null_resource.kubeadm_join.0 (remote-exec):     hostname "" a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with analphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
null_resource.kubeadm_join.0 (remote-exec): [preflight] If you know what you are doing,you can skip pre-flight checks with `--skip-preflight-checks`
null_resource.kubeadm_join.1 (remote-exec): [preflight] WARNING: hostname "" could not be reached
null_resource.kubeadm_join.1 (remote-exec): [preflight] WARNING: hostname "" lookup : no such host
null_resource.kubeadm_join.1 (remote-exec): [preflight] Some fatal errors occurred:
null_resource.kubeadm_join.1 (remote-exec):     hostname "" a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with analphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
null_resource.kubeadm_join.1 (remote-exec): [preflight] If you know what you are doing,you can skip pre-flight checks with `--skip-preflight-checks`
```

**What you expected to happen**:

Just some plain ol' joining and initializing.

**How to reproduce it (as minimally and precisely as possible)**:

should just be able to `kubeadm init/join` with some machines that do not have resolvable hostnames. I don't even know if CentOS is a requirement.

**Anything else we need to know?**:

Centos 7.3, provisioned by terraform into a private ESX cluster. DNS is working just fine, but the machines do not have reverse lookup. IP addresses are used throughout.

Sorry, I cannot share detailed infrastructure data.

```
$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T01:48:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

I think https://github.com/kubernetes/kubernetes/pull/40771/files is the problem. `net.LookupHost` only considers DNS. Should fallback to `os.Hostname` literal response.

**Comment by erikh** [comment]
maybe I'm reading the code wrong, and it needs to consider net.Interfaces() instead, or there should be a flag for it. Either way this feels pretty broken atm, and worked fine about 2 weeks ago.

**Comment by arthur0** [comment]
Same on Unbuntu 16.04

```

**Comment by cmluciano** [comment]
@kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by luxas** [comment]
known issue, will be fixed in v1.7.2: https://github.com/kubernetes/kubeadm/issues/347

**Comment by erikh** [comment]
awesome, thanks!

**Comment by kris-nova** [comment]
Seeing this is kubicorn at the moment - do we have an ETA on a 1.7.2 release or a patch for kubeadm?

**Comment by luxas** [comment]
Just do --skip-preflight-checks until tomorrow ;)

v1.7.2 is planned for tomorrow and will have the fix

**Comment by kris-nova** [comment]
In case anyone else needs this - the syntax for installing `1.7.0` on Ubuntu is:

```
apt-get install kubeadm-1.7.0-00 -y
```

**Comment by kris-nova** [comment]
Thanks @luxas 😄

**Comment by buchanae** [comment]
> The syntax for installing 1.7.0 on Ubuntu is:

`apt-get install kubeadm=1.7.0-00 -y --allow-downgrades`

This is what I needed, for anyone else landing here.

**Comment by ReSearchITEng** [comment]
kubeadm 1.7.2 -> issue still there

**Comment by Caldas** [comment]
Indeed I'm using **kubeadm 1.7.2** and issue is still there

**Comment by mkjpryor-stfc** [comment]
Same here. kubernetes/kubeadm 1.7.2 on Ubuntu Xenial still gives this error. Host resolution using /etc/hosts, not DNS server.

**Comment by jujes** [comment]
Same issue here, using kubernetes/kubeadm 1.7.2 on Ubuntu Xenial.....
@luxas still gives this error, some one how testing testing testing.... it before release????

**Comment by erikh** [comment]
I think the problem may be related to how kubeadm is compiled, vs how it is
written. Is netgo (instead of the cgo glibc backend) forced on? It's
probably not consuling nsswitch (which yields /etc/hosts resolution)
because of that.

from the https://golang.org/pkg/net/#hdr-Name_Resolution go doc:

The method for resolving domain names, whether indirectly with functions
like Dial or directly with functions like LookupHost and LookupAddr, varies
by operating system.

On Unix systems, the resolver has two options for resolving names. It can
use a pure Go resolver that sends DNS requests directly to the servers
listed in /etc/resolv.conf, or it can use a cgo-based resolver that calls C
library routines such as getaddrinfo and getnameinfo.

**Comment by TimothyYe** [comment]
Same issue when using kubeadm 1.7.2 , On CentOS 7.3

**Comment by luxas** [comment]
Can anybody reproduce this with v1.7.3? Seems like something in the cherrypick process for v1.7.2 went a little bit wrong, but I'm sure I've cherrypicked the necessary change(s) into v1.7.3.

Sorry for the inconvenience, but now it really is fixed.

**Comment by dimm0** [comment]
Still in 1.7.3, Centos 7.3

**Comment by erikh** [comment]
Are you all compiling with netgo or cgo for dns?

**Comment by dimm0** [comment]
I was using the standard RPMs from the distro

**Comment by f0** [comment]
@luxas still present with 1.8.0

**Comment by luxas** [comment]
Please install kubeadm the documented, official way from debs/rpms.
I don't think this issue exists in v1.8.0
In case you think so, I'm glad to get that reported, but then open a new issue in kubernetes/kubeadm, please don't answer here

**Comment by jianhuihi** [comment]
Still in 1.9.0, Centos 7.2

**Comment by f0** [comment]
same with 1.10.2 on Container Linux on vmware

**Comment by erikh** [comment]
This is a pretty trivial patch for those of you who still need kubeadm (I don't personally). See the three comments I have made over the last year, it's a very simple solution.

**Comment by luxas** [comment]
@erikh @seh Please open a clean issue in kubernetes/kubeadm and describe exactly what needs to be changed, and we can try to get it prioritized for v1.11 stable then. Also, contributions are welcome :wink:
