### ISSUE TITLE
add flannel -public-ip to support custom openstack(using floating ip)

### ISSUE THREAD

**Issue by zengbiao** [kubernetes/kubernetes#49077]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind feature

**What happened**:
   minion flannel will write vm's ip to subnet key of etcd. if we need deploy k8s cluster in two different openstack tenant. only floating ip is visibility. but flannel map cluster ip to vm's private ip. this will cause some network problems.

**What you expected to happen**:
just add -public-ip="floating ip" to flannel

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dixudx** [comment]
@zengbiao I don't think Kubernetes should support this. You can achieve the same goal by setting `FLANNELD_IFACE=<your_floating_ip>` and pass this environment when flanneld starts. This should not be controlled/managed by Kubernetes and also flannel always starts before Kubernetes.

**Comment by caseydavenport** [comment]
Yeah, this doesn't sounds like a Kubernetes issue to me.  If anything it's probably a feature request against flannel.

As mentioned above, seems like Flannel might already have support for this.

/assign
