### ISSUE TITLE
SetAnnotations() could not distinguish  nil  and {}

### ISSUE THREAD

**Issue by shiywang** [kubernetes/kubernetes#49075]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig api-machinery

**What happened**:
when I was working on pr https://github.com/kubernetes/kubernetes/pull/46560, I suspect it may be a bug with SetAnnotations(), since it cannot distinguish SetAnnotations(targetObj, nil) with SetAnnotations(targetObj, {}).

**What you expected to happen**:
SetAnnotations(targetObj, {})                  set   `annotations: {}`
SetAnnotations(targetObj, nil)                 remove  `annotations` field

**How to reproduce it (as minimally and precisely as possible)**:
see comments here : https://github.com/kubernetes/kubernetes/pull/46560#discussion_r127489967

**Comment by shiywang** [comment]
cc @mengqiy @liggitt

**Comment by liggitt** [comment]
cc @ironcladlou

**Comment by dixudx** [comment]
@shiywang @liggitt I followed the calling path and found that [SetAnnotations](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/meta/meta.go#L547-L553) will create an empty annotation `map[string]string` if obj.annotations is nil.

**Comment by lavalamp** [comment]
I am not sure it is a good idea to make decisions based on nil vs {}, is this important for something?
