### ISSUE TITLE
Allow "hack/verify-golint.sh" to respect "WHAT" flag

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#49084]
`hack/verify-golint.sh` can cost minutes to complete the lint. But in some cases we don't want to golint the whole project, e.g. I only want to verify if the files I modified can pass golint. Running the whole golint would be boring in this case, especially when I fix lint errors and run `hack/verify-golint.sh` again to verify if the fix is okay.

I would like to have a `WHAT` flag for `hack/verify-golint.sh` as `make test` has. With this flag, contritutors can specify which pkg they want to run golint for.

/cc @spxtr

**Comment by xiangpengzhao** [comment]
Felt painful when fixing `hack/verify-golint.sh` in https://github.com/kubernetes/kubernetes/pull/48256

**Comment by spxtr** [comment]
You can just run `golint ./path/to/your/pkg`, no need to use the script for that.

**Comment by xiangpengzhao** [comment]
Thanks @spxtr for quick response! 

However, golint cannot do recursive pkg linting. (Can it? or I might miss something) What I really expected is that `hack/verify-golint.sh` can respect `WHAT` to support recursive pkg linting. e.g. I modify several files in `pkg/util/foo` and `pkg/util/bar` and `pkg/util/baz`, I want to run `hack/verify-golint.sh WHAT=./pkg/util` to verify those files. (Though this may also golint other sub-pkgs in `pkg/util`, that's okay)

**Comment by spxtr** [comment]
Yes, it can. `golint ./pkg/util/...`

**Comment by xiangpengzhao** [comment]
Thanks @spxtr for pointing it out!
/close
