### ISSUE TITLE
No yaml example in DaemonSet doc

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#49080]
It seems we have no yaml example in the whole DS doc here: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/, 

This is not good, if I were user, I would expect that every `k8s.io/concepts/workloads` has at least one example yaml. 

And this issue also apply to many other concepts doc besides DS.

**Comment by GabrielSVinha** [comment]
@resouer I believe that all the `k8s.io/concepts/workloads` have YAML examples on them. Can you check it out and comment here (or close the issue if you think it's done).

**Comment by resouer** [comment]
Yes, this has been fixed.
