### ISSUE TITLE
"message": "pods \"kube-apiserver-k8s-master\" not found",

### ISSUE THREAD

**Issue by justlooks** [kubernetes/kubernetes#49097]
> Environment:
> 
> Kubernetes version (use kubectl version): v1.7.0
> Cloud provider or hardware configuration**:
> OS (e.g. from /etc/os-release): CentOS 7
> Kernel (e.g. uname -a): Linux k8s-master 3.10.0-514.6.2.el7.x86_64
> Install tools: Kubeadm
> Others:
> docker version : Docker version 1.12.6,
> My RPM version :
> docker-1.12.6-16.el7.centos.x86_64.rpm
> kubectl-1.7.0-0.x86_64.rpm
> kubernetes-cni-0.5.1-0.x86_64.rpm
> kubeadm-1.7.0-0.x86_64.rpm
> kubelet-1.7.0-0.x86_64.rpm
> 
> i use kubectl get all pods ,it's ok
> [root@k8s-master kubernetes]# kubectl get pods --all-namespaces
> NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE
> default       test-3800968474-wtscv                   1/1       Running   0          5m
> kube-system   etcd-k8s-master                         1/1       Running   0          4d
> kube-system   kube-apiserver-k8s-master               1/1       Running   0          4d
> kube-system   kube-controller-manager-k8s-master      1/1       Running   0          4d
> kube-system   kube-dns-2425271678-9st7f               3/3       Running   11         4d
> kube-system   kube-flannel-ds-4sdl3                   2/2       Running   0          4d
> kube-system   kube-flannel-ds-g6bf6                   2/2       Running   1          4d
> kube-system   kube-flannel-ds-ww7m1                   2/2       Running   0          4d
> kube-system   kube-proxy-jh25c                        1/1       Running   0          4d
> kube-system   kube-proxy-k8dd1                        1/1       Running   0          4d
> kube-system   kube-proxy-npr4q                        1/1       Running   0          4d
> kube-system   kube-scheduler-k8s-master               1/1       Running   0          4d
> kube-system   kubernetes-dashboard-2209332821-0w4r7   1/1       Running   0          3d
> 
> but when i use curl ,it says " message": "pods \"kube-apiserver-k8s-master\" not found "
> why? anyone can help ?
> 
> [root@k8s-master kubernetes]# curl http://127.0.0.1:8001/api/v1/proxy/namespaces/default/pods/kubernetes-dashboard-2209332821-0w4r7/
> {
>   "kind": "Status",
>   "apiVersion": "v1",
>   "metadata": {},
>   "status": "Failure",
>   "message": "pods \"kubernetes-dashboard-2209332821-0w4r7\" not found",
>   "reason": "NotFound",
>   "details": {
>     "name": "kubernetes-dashboard-2209332821-0w4r7",
>     "kind": "pods"
>   },
>   "code": 404
> }[root@k8s-master kubernetes]# curl http://127.0.0.1:8001/api/v1/proxy/namespaces/default/pods/kube-apiserver-k8s-master/
> {
>   "kind": "Status",
>   "apiVersion": "v1",
>   "metadata": {},
>   "status": "Failure",
>   "message": "pods \"kube-apiserver-k8s-master\" not found",
>   "reason": "NotFound",
>   "details": {
>     "name": "kube-apiserver-k8s-master",
>     "kind": "pods"
>   },
>   "code": 404
> }
>

**Comment by abdasgupta** [comment]
Is it not working - curl http://127.0.0.1:8001/api/v1/proxy/namespaces/kube-system/pods/kube-apiserver-k8s-master/ ??
It looks like your pods are in kube-system namespace but you are querying default namespace.

**Comment by justlooks** [comment]
seems not work
[root@k8s-master ~]# curl http://127.0.0.1:8001/api/v1/proxy/namespaces/kube-system/kubernetes-dashboard-2209332821-0w4r7/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404
}[root@k8s-master ~]# curl http://127.0.0.1:8001/api/v1/proxy/namespaces/kube-system/kube-apiserver-k8s-master/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404
}

**Comment by justlooks** [comment]
@abdasgupta  seems not work
[root@k8s-master ~]# curl http://127.0.0.1:8001/api/v1/proxy/namespaces/kube-system/kubernetes-dashboard-2209332821-0w4r7/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404
}[root@k8s-master ~]# curl http://127.0.0.1:8001/api/v1/proxy/namespaces/kube-system/kube-apiserver-k8s-master/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404
}

**Comment by abdasgupta** [comment]
you need to remove the "proxy" element from the url as well..
curl http://127.0.0.1:8001/api/v1/namespaces/kube-system/pods/kube-apiserver-k8s-master/
