### ISSUE TITLE
Create subresource end points for replication controllers

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#4909]
As discussed on https://github.com/GoogleCloudPlatform/kubernetes/issues/2726 it would be nice to have replicationControllers/foo/status as a watchable endpoint that discards updates to the spec. Giving  status and spec different resource versions is out of scope of this bug.

**Comment by bprashanth** [comment]
@lavalamp @bgrant0607, think I got the priority right

**Comment by brendandburns** [comment]
I don't think that this makes the v1.0 list.

**Comment by bgrant0607** [comment]
cc @erictune @mikedanese @derekwaynecarr

**Comment by derekwaynecarr** [comment]
@bgrant0607 - is it a backward incompatible change in your view to restrict update of RC.Status when doing an update and instead requiring to put to a /status endpoint like the rest?  I began to look at that this afternoon, but worried it may be viewed as an incompatible change.

**Comment by bgrant0607** [comment]
By "restrict", I assume you mean just dropping status on POST, PUT, and PATCH to the regular endpoint and only applying updates performed using the /status subresource.

It is technically a breaking change, but the RC manager isn't very pluggable at the moment, and a user would need to upgrade the apiserver and controller-manager at different times to expose a problem. A user posting to status is almost certainly accidental (e.g., `kubectl get rc foo | sed | kubectl replace -f -`) and would be soon overwritten by controller-manager, anyway. Additionally, it's reasonable that an admin would want to lock this down -- it's closing a DoS hole.

We should do it and write good release notes.

**Comment by derekwaynecarr** [comment]
Ok.  Will send PR Monday.

**Comment by bgrant0607** [comment]
Mostly looks pretty reasonable, thanks.

You need to regenerate the swagger spec again.

**Comment by bgrant0607** [comment]
Oops, meant to put that on the PR.
