### ISSUE TITLE
Containerized kubelet can't unmount vSphere volumes

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#49106]
/kind bug
Kubernetes ~~1.7.0~~ 1.6.1

vSphere volume plugin uses spaces in its mount points such as `/var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/[datastore1] kubevols/kubernetes-dynamic-pvc-4aacaa9b-6ba5-11e7-8f64-0050569f1b82.vmdk`.

When kubelet runs in a container it uses `/bin/findmnt` to check if a directory is a mount point or not and it parses findmnt output up to the first space. When the directory name contains a space, it interprets findmnt output in a wrong way and does not unmount it. As result, vSphere volumes are not unmounted.

/assign
@kubernetes/sig-storage-bugs

**Comment by divyenpatel** [comment]
CC: @BaluDontu @tusharnt @luomiao

**Comment by divyenpatel** [comment]
We made related space fix as part of this PR - https://github.com/kubernetes/kubernetes/pull/38338. This replaces `\040` to empty space
Change is cherry picked to 1.5 release.

**Comment by jsafrane** [comment]
This sounds like a different bug... I already have #38338 in my test kubernetes. It fixes `ConstructVolumeSpec` that's IMO used only by attach/detach controller.

I see a space in a directory created by kubelet calling `plugin.SetUpAt()`, where `VolumePath` was filled by dynamic provisioning:

```
volumePath: '[datastore1] kubevols/kubernetes-dynamic-pvc-4aacaa9b-6ba5-11e7-8f64-0050569f1b82.vmdk'
```

(and there is nothing wrong about the space, just NsEnterMounter is buggy...)
