### ISSUE TITLE
Regression: masters no longer printed by `kubectl get nodes`

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#49124]
`kubectl get nodes` used to show masters, but as of e25a5b1546392221c79e4d48dff4643c2341a002 it no longer does.

This is not in accordance with our deprecation policy I believe.

cc @luxas

**Comment by luxas** [comment]
That commit/PR is not relevant as there are no supported users/deployment methods that are using `kubeadm.alpha.kubernetes.io/role` label. kubeadm v1.4 or v1.5 was the last.

What you're really looking for is who/what removed printing things based on the `kubernetes.io/role` label...

**Comment by justinsb** [comment]
No blame on you @luxas 

The regression is that we have stopped printing masters in `kubectl get nodes`.  There may be more to it that a simple revert of https://github.com/kubernetes/kubernetes/commit/e25a5b1546392221c79e4d48dff4643c2341a002, but we should probably start there.

**Comment by luxas** [comment]
This has been fixed in recent versions
