### ISSUE TITLE
kubectl plugin <subcommand> does not pass flags to subcommand

### ISSUE THREAD

**Issue by containscafeine** [kubernetes/kubernetes#49122]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

My plugin.yaml looks like -
```console
$ cat ~/.kube/plugins/base64/plugin.yaml 
name: "base64"
shortdesc: "base64 command"
command: "base64"
```

**What happened**:

kubectl binary does not pass flag to the binary.

This works fine -
```console
$ kubectl plugin base64 plaintext.txt 
c2VjcmV0
```

But this fails,
```console
$ kubectl plugin base64 -d encoded.txt 
Error: unknown shorthand flag: 'd' in -d


Usage:
  kubectl plugin base64 [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).
```

**What you expected to happen**:

I'd expect `-d` to be passed to the plugin command and the file should be decoded, i.e. this should happen -
```console
$ kubectl plugin base64 -d encoded.txt
secret
```

**How to reproduce it (as minimally and precisely as possible)**:
Create the plugin.yaml file like -
```console
$ cat ~/.kube/plugins/base64/plugin.yaml 
name: "base64"
shortdesc: "base64 command"
command: "base64"
```

Create a file with encoded data, `echo secret | base64 > encoded.txt`

Then run the command, `kubectl plugin base64 -d encoded.txt`

**Environment**:
- Kubernetes version (use `kubectl version`):
kubectl is v1.7.1
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T02:00:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-30T10:17:58Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration**:
I'm on minikube v0.20.0
```console
$ minikube version
minikube version: v0.20.0
```

- OS (e.g. from /etc/os-release):
Fedora 25

- Kernel (e.g. `uname -a`):
```console
$ uname -a
Linux containscafeine 4.10.13-200.fc25.x86_64 #1 SMP Thu Apr 27 20:39:25 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

ping @fabianofranz, I think :)

**Comment by xingzhou** [comment]
I'd like to take a look at this

**Comment by fabianofranz** [comment]
Known issue and already fixed in https://github.com/kubernetes/kubernetes/pull/47267.
