### ISSUE TITLE
Clustered redis example fails to re-elect and failover

### ISSUE THREAD

**Issue by vishvananda** [kubernetes/kubernetes#4914]
Following the clustered redis example, everything works fine until I delete the original redis master. I see the pods getting recreated, but a new master doesn't seem to be getting elected. I can retrieve data from redis but i can't write anything. I see the following over and over in the log of the redis servers:

[19] 27 Feb 23:20:10.585 # Error condition on socket for SYNC: No route to host
[19] 27 Feb 23:20:10.883 * Connecting to MASTER 10.244.37.12:6379

Which was the ip address of my original master:

redis-master                 10.244.37.12        redis               kubernetes/redis:v1    10.130.78.11/10.130.78.11   name=redis,redis-sentinel=true,role=master              Running
                                                 sentinel            kubernetes/redis:v1

Not sure what I might have missed.

**Comment by vishvananda** [comment]
I see the following in the sentinel logs:

[16] 27 Feb 23:23:19.591 # +failover-state-select-slave master mymaster 10.244.37.12 6379
[16] 27 Feb 23:23:19.647 # -failover-abort-no-good-slave master mymaster 10.244.37.12 6379

**Comment by thockin** [comment]
@brendandburns has the best experience here, I think

**Comment by vishvananda** [comment]
I'm also a bit unclear as to how the proxy is supposed to work with this config. The proxy will pick a random redis server to send a request to and if it is a slave it doesn't seem to accept writes.

**Comment by erictune** [comment]
@brendanburns 
there was a request on IRC for the Dockerfile for kubernetes/redis-proxy.  I think you probably have that file.  It doesn't appear to be in github.

**Comment by AntonioMeireles** [comment]
@brendanburns

(for context) was me who made the request above :smile:. i'm mostly curious about where the *proxy* blob comes from (according to [this](https://gist.github.com/AntonioMeireles/1c74cf978909b9ef611f))

**Comment by mulloymorrow** [comment]
HA proxy seems to be helpful here: https://robertianhawdon.me.uk/2014/02/11/sysops-installing-a-high-availability-redis-service-on-centos-6-x-in-windows-azure/

**Comment by mulloymorrow** [comment]
Mike working on a solution: https://github.com/mikedanese/k8s-haproxy/commits?author=mikedanese

**Comment by AntonioMeireles** [comment]
@brendandburns don't forget to see above please, when you have a spare minute... :smile:

**Comment by piosz** [comment]
I can take w look.

**Comment by piosz** [comment]
@AntonioMeireles @vishvananda That seems to be no longer a problem since we are using kube-dns instead of SERVICE_HOST, SERVICE_PORT env variables (see #5284). Could you please verify if you still have such problem?

**Comment by jayunit100** [comment]
well, wether or not this is a bug, is independent of wether redis HA is working, right?  after all ENV variables are a supported feature, and clustered redis, if using env variables, should work just the same since it could have a master service.

**Comment by bgrant0607** [comment]
Is this about:
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/redis
?

There is no master service.

It's not clear to me how that example is expected to work. 

The redis and sentinel controllers create separate pods. sentinel.py is not in the image directory, so I don't know what it's doing, but I don't see how it can find the redis replicas.

**Comment by piosz** [comment]
Sorry, I've thought it was about guestbook example. I'll take a look into redis example tomorrow.

**Comment by bgrant0607** [comment]
IIUC, the guestbook example doesn't even pretend to handle master failure.

**Comment by dereknex** [comment]
I have same error,
I have two nodes:

NAME            LABELS                                 STATUS
192.168.33.10   kubernetes.io/hostname=192.168.33.10   Ready
192.168.33.20   kubernetes.io/hostname=192.168.33.20   Ready

Pods:
POD                  IP          CONTAINER(S)   IMAGE(S)          HOST                          LABELS                   STATUS    CREATED      MESSAGE
redis-master-h8git   10.0.87.2                                    192.168.33.10/192.168.33.10   name=redis,role=master   Running   18 minutes   
                                 redis-master   gurpartap/redis                                                          Running   18 minutes   
redis-slave-35d48    10.0.87.5                                    192.168.33.10/192.168.33.10   name=redis,role=slave    Running   16 minutes   
                                 redis-slave    gurpartap/redis                                                          Running   16 minutes   
redis-slave-axx0c    10.0.87.7                                    192.168.33.10/192.168.33.10   name=redis,role=slave    Running   16 minutes   
                                 redis-slave    gurpartap/redis                                                          Running   16 minutes   
redis-slave-ji7zr    10.0.58.3                                    192.168.33.20/192.168.33.20   name=redis,role=slave    Running   16 minutes   
                                 redis-slave    gurpartap/redis                                                          Running   16 minutes   
redis-slave-jiiyt    10.0.87.6                                    192.168.33.10/192.168.33.10   name=redis,role=slave    Running   16 minutes   
                                 redis-slave    gurpartap/redis                                                          Running   16 minutes   

The redis master on 192.168.33.10 host, have three redis slaves on 192.168.33.10 host, have  one redis slave on 192.168.33.20 host.

Work on 192.168.33.10 host three redis slaves is fine, but on 192.168.33.20 host slave error as below:
[6] 03 Jun 02:15:49.677 * MASTER <-> SLAVE sync started
[6] 03 Jun 02:15:51.781 # Error condition on socket for SYNC: No route to host

And the 192.168.33.10 iptables as below:
Chain KUBE-PORTALS-CONTAINER (1 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             10.100.0.2           /* default/kubernetes: */ tcp dpt:https to:192.168.33.10:55428
DNAT       tcp  --  anywhere             10.100.0.1           /* default/kubernetes-ro: */ tcp dpt:http to:192.168.33.10:59689
DNAT       tcp  --  anywhere             10.100.38.222        /* default/redis-master: */ tcp dpt:6379 to:192.168.33.10:60702
DNAT       tcp  --  anywhere             10.100.244.226       /* default/redis-slave: */ tcp dpt:6379 to:192.168.33.10:43282

Chain KUBE-PORTALS-HOST (1 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             10.100.0.2           /* default/kubernetes: */ tcp dpt:https to:192.168.33.10:55428
DNAT       tcp  --  anywhere             10.100.0.1           /* default/kubernetes-ro: */ tcp dpt:http to:192.168.33.10:59689
DNAT       tcp  --  anywhere             10.100.38.222        /* default/redis-master: */ tcp dpt:6379 to:192.168.33.10:60702
DNAT       tcp  --  anywhere             10.100.244.226       /* default/redis-slave: */ tcp dpt:6379 to:192.168.33.10:43282

The services as below:

NAME            LABELS                                    SELECTOR                 IP(S)            PORT(S)
kubernetes      component=apiserver,provider=kubernetes   <none>                   10.100.0.2       443/TCP
kubernetes-ro   component=apiserver,provider=kubernetes   <none>                   10.100.0.1       80/TCP
redis-master    name=redis,role=master                    name=redis,role=master   10.100.38.222    6379/TCP
redis-slave     name=redis,role=slave                     name=redis,role=slave    10.100.244.226   6379/TCP

And the 192.168.33.20 iptables as below:

Chain KUBE-PORTALS-CONTAINER (1 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             10.100.0.2           /* default/kubernetes: */ tcp dpt:https to:192.168.33.20:46990
DNAT       tcp  --  anywhere             10.100.0.1           /* default/kubernetes-ro: */ tcp dpt:http to:192.168.33.20:50396
DNAT       tcp  --  anywhere             10.100.38.222        /* default/redis-master: */ tcp dpt:6379 to:192.168.33.20:45492
DNAT       tcp  --  anywhere             10.100.244.226       /* default/redis-slave: */ tcp dpt:6379 to:192.168.33.20:59599

Chain KUBE-PORTALS-HOST (1 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             10.100.0.2           /* default/kubernetes: */ tcp dpt:https to:192.168.33.20:46990
DNAT       tcp  --  anywhere             10.100.0.1           /* default/kubernetes-ro: */ tcp dpt:http to:192.168.33.20:50396
DNAT       tcp  --  anywhere             10.100.38.222        /* default/redis-master: */ tcp dpt:6379 to:192.168.33.20:45492
DNAT       tcp  --  anywhere             10.100.244.226       /* default/redis-slave: */ tcp dpt:6379 to:192.168.33.20:59599

The proxy redirect all service's IP to local random port, Is it right?
If right, how to access work on other node's service ?

**Comment by moosilauke18** [comment]
The original problem seems to work when you remove the master pod, it does re-elect/failover.  However, it becomes hard to write to redis since you can only write to the master and the master in the example is elected.  Basically if you put a service in front of the redis pods, it will proxy to one of the replicas, where only one is the actual master.

**Comment by bgrant0607** [comment]
It looks like the sentinels think they know which component the master is. If non-masters failed readiness probes, they'd get removed from the endpoints list for the service.

**Comment by goltermann** [comment]
It looks like all questions have been answered here.  Please reopen if needed.

**Comment by manaspatkar21** [comment]
I am also expierencing a similar issue as @vishvananda, Redis master to slave failover does not work.

I observed that the redis master does not record the origin ip of the slave, instead it records the flannel ip of the VM where the redis slave pod is running, resulting into the issue. Is there any solution for this ?

**Comment by hardcoar** [comment]
hi. how does this work? like @bgrant0607 said, there's no master service and @moosilauke18 said, there's a chance that a service in front will proxy a write request into a slave. is there any way to proxy writes to master and reads to slaves using a service?

**Comment by erictune** [comment]
@mamspatkar21 @hadcoar have you tried the "redis-cluster" helm chart?  
https://github.com/helm/charts/tree/master/redis-cluster
That uses a service for the redis-sentinel, but no service for the redis masters.
So, there should not be any issues with the service munging the IPs or sending writes to the wrong place.   It requires that you use a client which understands how to discover a master using the redis-sentinel (which redis-cli does not seem to be able to do, but some clients can (ones that follow: http://redis.io/topics/sentinel-clients) .  Looks like one client that supports it is https://github.com/nrk/predis.

**Comment by klausenbusk** [comment]
> @brendandburns
> there was a request on IRC for the Dockerfile for kubernetes/redis-proxy. I think you probably have that file. It doesn't appear to be in github.

Any update on this? @brendandburns

**Comment by rogeruiz** [comment]
@manaspatkar21 We ran into this too on our deployment of redis HA. Setting the `slave-announce-ip` to the value of `$(hostname -i)` worked for us. We originally were going to disable ipmasq on `docker` and then enable it on `flannel` but ultimately the easier thing was to properly configure redis servers with that property.
