### ISSUE TITLE
Controllers make too many requests when denied by quota

### ISSUE THREAD

**Issue by joelsmith** [kubernetes/kubernetes#49145]
/kind bug

A quota-limited user put a large number for replicas in a replica set.

**What happened**: The controller attempted to start 500 pods even though the quota only allowed 5 pods. A large number of requests were made for each controller pass, and an enormous volume of failure events was generated.

**What you expected to happen**: The controller should realize that pod creation is failing and skip the later pod creation attempts.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a namespace and add a quota to the namespace
```kubectl create quota my-quota --hard=pods=5```
2. Create a replica set in the namespace with a number that far exceeds the quota
3. Watch the controller logs and events

**Anything else we need to know?**:

Fix in https://github.com/kubernetes/kubernetes/pull/49142

**Comment by kargakis** [comment]
@kubernetes/sig-apps-bugs
