### ISSUE TITLE
Local Storage Request/Limit Validation Discussion

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#49158]
## Feature: local storage request/limit
From v1.7, we add the feature to allow users set local storage limit for pod’s emptyDir and container’s writable layer (overlay) to better provide storage capacity isolation.

For all type of resources in Kubernetes, user can set value for request and/or limit. The relationship between request and limit is defined as follows 

- A BestEffort quality of service is provided when a request and limit are not specified.
- A Burstable quality of service is provided when a request is specified that is less than an optionally specified limit.
- A Guaranteed quality of service is provided when a limit is specified that is equal to an optionally specified request.

The quality of service has an impact on what happens if the resource is compressible or not. For incompressible resource such as memory,  a BestEffort container will be able to consume as much resource as is available on the node. In addition, a BestEffort container has the greatest chance of being killed if there is an out of resource event on the node. A Burstable container will be scheduled on the node to get the amount of resource requested, but it may consume more. If there is an out of resource event on the node, containers of this type will be killed after BestEffort containers when attempting to reclaim resource. A Guaranteed container will get the amount of resource requested, but no more. In the event of a system out of resource event, it will only be killed if there are no more BestEffort or Burstable containers on the system.

For Burstable container setting, one problem is that resource could be over-committed. The scheduler will tend to pack more Pods to the nodes. When disk is under pressure, the eviction manager will try to reclaim storage resource and evict pods to free up resource if reclaim is not enough. Storage is also an incompressible resource like memory. However, unlike memory, reclaim storage resource and free disk space take much longer time and incur more overhead. So the system would be much more stable if it can allocate enough resources for the workload at the first place to avoid reclaim. 

## Proposal: request/limit validation
One proposal is to enforce that request is always equal to limit for local storage. User will set a reasonable value for storage request/limit so that Pod gets enough disk space.  In this way, the system will schedule the Pods to nodes where there is sufficient resource and also make sure Pods will not use more than requested to avoid over commitment. The reason behind this is that storage is relatively cheap. One future Vertical pod autoscaling can help reduce wastage. https://github.com/kgrygiel/community/blob/master/contributors/design-proposals/vertical-pod-autoscaler.md

The downside of this proposal is that for some very burstable workload, it might be difficult to set it a good value for request and limit. If the value is too big, it will waste resource. Otherwise, if the value is small, the pod might get evicted very easily. 

Open this issue for further discussion on how we should validate the local storage request/limit. Feedback is appreciated.

**Comment by ddysher** [comment]
IIUC, storage request/limit is not counted when calculating Be, Bu, Gu, for mostly the same reason listed here.
> For all type of resources in Kubernetes, user can set value for request and/or limit. The relationship between request and limit is defined as follows

One major concern is cluster utilization.  We've seen people struggling with guessing the right cpu, memory for their application, and request<limit is the generally accepted ways for improving utilization.  For production cluster, we are always using request=limit for predictable outcome.

Storage is cheap but not an infinite resource, and the request for storage grows linearly with overall capacity. I'm quite sure the restriction on storage will affect utilization negatively.  However, I do think having request=limit for storage makes more sense, because 1. we favor stability over utilization; 2. we already treat differently for storage in QoS calculation for good reasons; it's natural to do this for isolation as well.  For utilization, i'm betting on VPA :)

**Comment by dims** [comment]
@jingxu97 @dixudx Looks like this is too late for 1.8, can we please drop the 1.8 milestone?

**Comment by jingxu97** [comment]
Yes, we can drop this one from 1.8
