### ISSUE TITLE
External provisioner test is failing on GKE

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#49156]
[testgrid](https://k8s-testgrid.appspot.com/sig-storage#gke-slow)

[logs](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-slow/7598#sig-storage-dynamic-provisioning-sig-storage-dynamicprovisioner-external-should-let-an-external-dynamic-provisioner-create-and-delete-persistent-volumes-slow)

/kind bug
/sig storage

**Comment by msau42** [comment]
From the logs, it looks like provisioning succeeded, but mounting failed.

This could be the same issue as #49150 where with nfs on gke.

**Comment by wongma7** [comment]
thanks for looking, the test depends on NFS mounting so you are correct

**Comment by msau42** [comment]
Fixed by #49595
/close
