### ISSUE TITLE
why i can not visit dashboard ？

### ISSUE THREAD

**Issue by justlooks** [kubernetes/kubernetes#49170]
> Environment:
> 
> Kubernetes version (use kubectl version): v1.7.0
> Cloud provider or hardware configuration**:
> OS (e.g. from /etc/os-release): CentOS 7
> Kernel (e.g. uname -a): Linux k8s-master 3.10.0-514.6.2.el7.x86_64
> Install tools: Kubeadm
> Others:
> docker version : Docker version 1.12.6,
> My RPM version :
> docker-1.12.6-16.el7.centos.x86_64.rpm
> kubectl-1.7.0-0.x86_64.rpm
> kubernetes-cni-0.5.1-0.x86_64.rpm
> kubeadm-1.7.0-0.x86_64.rpm
> kubelet-1.7.0-0.x86_64.rpm
> 
> my k8s master node have a outside ip （121.199.31.235） and a internal ip (10.132.41.234)
> i init master with option "--apiserver-advertise-address 10.132.41.234",and i run the command on my master node "kubectl proxy --address='0.0.0.0' --accept-hosts='^.*$'" ,and on my workstation i use the following command ,it worked
> 
> # curl http://121.199.31.235:8001/api/v1/namespaces/kube-system/pods/kubernetes-dashboard-2209332821-0w4r7/
> {
>   "kind": "Pod",
>   "apiVersion": "v1",
>   "metadata": {
>     "name": "kubernetes-dashboard-2209332821-0w4r7",
>     "generateName": "kubernetes-dashboard-2209332821-",
>     "namespace": "kube-system",
>     "selfLink": "/api/v1/namespaces/kube-system/pods/kubernetes-dashboard-2209332821-0w4r7",
>     "uid": "7d0056ae-6877-11e7-9f2c-00163e024627",
>     "resourceVersion": "99810",
>     "creationTimestamp": "2017-07-14T09:33:26Z",
>     "labels": {
>       "k8s-app": "kubernetes-dashboard",
>       "pod-template-hash": "2209332821"
>     },
>     "annotations": {
>       "kubernetes.io/created-by": "{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicaSet\",\"namespace\":\"kube-system\",\"name\":\"kubernetes-dashboard-2209332821\",\"uid\":\"7cfd5ddd-6877-11e7-9f2c-00163e024627\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"99787\"}}\n"
>     },
>     "ownerReferences": [
>       {
>         "apiVersion": "extensions/v1beta1",
>         "kind": "ReplicaSet",
>         "name": "kubernetes-dashboard-2209332821",
>         "uid": "7cfd5ddd-6877-11e7-9f2c-00163e024627",
>         "controller": true,
>         "blockOwnerDeletion": true
>       }
>     ]
>   },
>   "spec": {
>     "volumes": [
>       {
>         "name": "kubernetes-dashboard-token-3f032",
>         "secret": {
>           "secretName": "kubernetes-dashboard-token-3f032",
>           "defaultMode": 420
>         }
>       }
>     ],
>     "containers": [
>       {
>         "name": "kubernetes-dashboard",
>         "image": "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.1",
>         "ports": [
>           {
>             "containerPort": 9090,
>             "protocol": "TCP"
>           }
>         ],
>         "resources": {},
>         "volumeMounts": [
>           {
>             "name": "kubernetes-dashboard-token-3f032",
>             "readOnly": true,
>             "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
>           }
>         ],
>         "livenessProbe": {
>           "httpGet": {
>             "path": "/",
>             "port": 9090,
>             "scheme": "HTTP"
>           },
>           "initialDelaySeconds": 30,
>           "timeoutSeconds": 30,
>           "periodSeconds": 10,
>           "successThreshold": 1,
>           "failureThreshold": 3
>         },
>         "terminationMessagePath": "/dev/termination-log",
>         "terminationMessagePolicy": "File",
>         "imagePullPolicy": "IfNotPresent"
>       }
>     ],
>     "restartPolicy": "Always",
>     "terminationGracePeriodSeconds": 30,
>     "dnsPolicy": "ClusterFirst",
>     "serviceAccountName": "kubernetes-dashboard",
>     "serviceAccount": "kubernetes-dashboard",
>     "nodeName": "k8s-node1",
>     "securityContext": {},
>     "schedulerName": "default-scheduler",
>     "tolerations": [
>       {
>         "key": "node-role.kubernetes.io/master",
>         "effect": "NoSchedule"
>       },
>       {
>         "key": "node.alpha.kubernetes.io/notReady",
>         "operator": "Exists",
>         "effect": "NoExecute",
>         "tolerationSeconds": 300
>       },
>       {
>         "key": "node.alpha.kubernetes.io/unreachable",
>         "operator": "Exists",
>         "effect": "NoExecute",
>         "tolerationSeconds": 300
>       }
>     ]
>   },
>   "status": {
>     "phase": "Running",
>     "conditions": [
>       {
>         "type": "Initialized",
>         "status": "True",
>         "lastProbeTime": null,
>         "lastTransitionTime": "2017-07-14T09:33:29Z"
>       },
>       {
>         "type": "Ready",
>         "status": "True",
>         "lastProbeTime": null,
>         "lastTransitionTime": "2017-07-14T09:33:32Z"
>       },
>       {
>         "type": "PodScheduled",
>         "status": "True",
>         "lastProbeTime": null,
>         "lastTransitionTime": "2017-07-14T09:33:26Z"
>       }
>     ],
>     "hostIP": "10.165.97.219",
>     "podIP": "10.244.1.8",
>     "startTime": "2017-07-14T09:33:29Z",
>     "containerStatuses": [
>       {
>         "name": "kubernetes-dashboard",
>         "state": {
>           "running": {
>             "startedAt": "2017-07-14T09:33:31Z"
>           }
>         },
>         "lastState": {},
>         "ready": true,
>         "restartCount": 0,
>         "image": "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.1",
>         "imageID": "docker://sha256:2769cef613d222125eb23dc0249a01fecd9c983e60190458d07963d5c3203546",
>         "containerID": "docker://22078771cefe85509987395c7a80881e619069dc3d0f4953f02d81062788a648"
>       }
>     ],
>     "qosClass": "BestEffort"
>   }
> 
> # curl http://121.199.31.235:8001/
> {
>   "paths": [
>     "/api",
>     "/api/v1",
>     "/apis",
>     "/apis/",
>     "/apis/apiextensions.k8s.io",
>     "/apis/apiextensions.k8s.io/v1beta1",
>     "/apis/apiregistration.k8s.io",
>     "/apis/apiregistration.k8s.io/v1beta1",
>     "/apis/apps",
>     "/apis/apps/v1beta1",
>     "/apis/authentication.k8s.io",
>     "/apis/authentication.k8s.io/v1",
>     "/apis/authentication.k8s.io/v1beta1",
>     "/apis/authorization.k8s.io",
>     "/apis/authorization.k8s.io/v1",
>     "/apis/authorization.k8s.io/v1beta1",
>     "/apis/autoscaling",
>     "/apis/autoscaling/v1",
>     "/apis/batch",
>     "/apis/batch/v1",
>     "/apis/certificates.k8s.io",
>     "/apis/certificates.k8s.io/v1beta1",
>     "/apis/extensions",
>     "/apis/extensions/v1beta1",
>     "/apis/networking.k8s.io",
>     "/apis/networking.k8s.io/v1",
>     "/apis/policy",
>     "/apis/policy/v1beta1",
>     "/apis/rbac.authorization.k8s.io",
>     "/apis/rbac.authorization.k8s.io/v1alpha1",
>     "/apis/rbac.authorization.k8s.io/v1beta1",
>     "/apis/settings.k8s.io",
>     "/apis/settings.k8s.io/v1alpha1",
>     "/apis/storage.k8s.io",
>     "/apis/storage.k8s.io/v1",
>     "/apis/storage.k8s.io/v1beta1",
>     "/healthz",
>     "/healthz/autoregister-completion",
>     "/healthz/ping",
>     "/healthz/poststarthook/apiservice-registration-controller",
>     "/healthz/poststarthook/apiservice-status-available-controller",
>     "/healthz/poststarthook/bootstrap-controller",
>     "/healthz/poststarthook/ca-registration",
>     "/healthz/poststarthook/extensions/third-party-resources",
>     "/healthz/poststarthook/generic-apiserver-start-informers",
>     "/healthz/poststarthook/kube-apiserver-autoregistration",
>     "/healthz/poststarthook/rbac/bootstrap-roles",
>     "/healthz/poststarthook/start-apiextensions-controllers",
>     "/healthz/poststarthook/start-apiextensions-informers",
>     "/healthz/poststarthook/start-kube-aggregator-informers",
>     "/healthz/poststarthook/start-kube-apiserver-informers",
>     "/logs",
>     "/metrics",
>     "/swagger-2.0.0.json",
>     "/swagger-2.0.0.pb-v1",
>     "/swagger-2.0.0.pb-v1.gz",
>     "/swagger.json",
>     "/swaggerapi",
>     "/ui",
>     "/ui/",
>     "/version"
>   ]
> }
> 
> BUT when i issue this command ,it seems get no respond,and i also can not i visit this url on chrome ,anyone can help?
> 
> Alex@MacBook-Pro-2:~% curl http://121.199.31.235:8001/ui
> <a href="/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy">Temporary Redirect</a>.
> 
> Alex@MacBook-Pro-2:~% curl http://121.199.31.235:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy
> Alex@MacBook-Pro-2:~% curl -v http://121.199.31.235:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy
> *   Trying 121.199.31.235...
> * Connected to 121.199.31.235 (121.199.31.235) port 8001 (#0)
> > GET /api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy HTTP/1.1
> > Host: 121.199.31.235:8001
> > User-Agent: curl/7.43.0
> > Accept: */*
> >
> < HTTP/1.1 301 Moved Permanently
> < Content-Length: 0
> < Content-Type: text/plain; charset=utf-8
> < Date: Wed, 19 Jul 2017 01:44:16 GMT
> < Location: /api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/
> <
> * Connection #0 to host 121.199.31.235 left intact
> 
> /sig hallo

**Comment by xiangpengzhao** [comment]
@justlooks please edit the format, it's not so readable. Thanks!
