### ISSUE TITLE
Presubmit is not failing on test failures

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#49187]
I've just seen this:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49056/pull-kubernetes-e2e-gce-etcd3/41375/

What is extremely frightening for me are those lines:
```
I0719 07:36:18.229] Summarizing 3 Failures:
I0719 07:36:18.229] 
I0719 07:36:18.230] [Fail] [k8s.io] Networking [k8s.io] Granular Checks: Pods [It] should function for node-pod communication: http [Conformance] 
I0719 07:36:18.230] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/networking_utils.go:273
I0719 07:36:18.230] 
I0719 07:36:18.230] [Fail] [k8s.io] [HPA] Horizontal pod autoscaling (scale resource: CPU) [k8s.io] ReplicationController light [It] Should scale from 1 pod to 2 pods 
I0719 07:36:18.230] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/autoscaling_utils.go:257
I0719 07:36:18.230] 
I0719 07:36:18.230] [Fail] [k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] [It] should provide basic identity 
I0719 07:36:18.230] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/statefulset_utils.go:323
I0719 07:36:18.230] 
I0719 07:36:18.230] Ran 304 of 652 Specs in 2578.287 seconds
I0719 07:36:18.237] SUCCESS! -- 304 Passed | 0 Failed | 0 Pending | 348 Skipped 
```

I guess we should stop merging anything before understanding and fixing this...
@kubernetes/test-infra-maintainers

**Comment by wojtek-t** [comment]
Ohh - actually this PR wasn't merged. Maybe it's just the log that is misleading...

**Comment by xiangpengzhao** [comment]
https://github.com/kubernetes/kubernetes/pull/48256#issuecomment-316245279

The above PR reported `pull-kubernetes-kubemark-e2e-gce` failure after it's merged. It's weird.

**Comment by wojtek-t** [comment]
> The above PR reported pull-kubernetes-kubemark-e2e-gce failure after it's merged. It's weird.

Our infra was trying to merge the PR in two ways:
- by merging just this PR
- as part of batch of PR
The tests for the second finished first and it was merged, but then it appeared that tests for first option failed. This is "working as intended".

**Comment by xiangpengzhao** [comment]
@wojtek-t thanks for explanation!

**Comment by kargakis** [comment]
> Ohh - actually this PR wasn't merged. Maybe it's just the log that is misleading...

I saw that you rerun only one test before it got merged (for clarity, the PR is https://github.com/kubernetes/kubernetes/pull/49056) which suggests that this is simply a matter of a misleading log.

**Comment by spiffxp** [comment]
/close
WAI but is confusing.  Batch merges should link to their results https://github.com/kubernetes/test-infra/issues/5183
