### ISSUE TITLE
Provide cluster resource usage api?

### ISSUE THREAD

**Issue by saiwl** [kubernetes/kubernetes#49184]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

I want to monitor the resource usage in our cluster, such as cpu usage and memory usage. However, I cannot get the resource usage information of a node using the existing api directly. I have to request all the pods on the node, and calculate the resource usage. I think this is very wasteful. Node usage should be provided directly and I think the information is already there because the scheduler needs it, or the api is already provided but I don't know? If then hope you can tell me. Thank you! 

/sig node

**Comment by dixudx** [comment]
@saiwl You can try to fetch such resource info through node v1 api (http://<your_clusterip_and_port>/api/v1/nodes/<node_name>).

For cli,

```
$ kubectl get node -o=custom-columns=Name:.metadata.name,Allocatable:.status.allocatable,Capacity:.status.capacity
```

**Comment by saiwl** [comment]
@dixudx The node info fetched through apiserver doesn't include the allocated info. Only the capacity. `kubectl` command fetches the pods info on a node and calculate the allocated info, then show to users.

**Comment by jianzhangbjz** [comment]
@saiwl You can enable `--enable-swagger-ui` flag in `kube-apiserver`, and then get the api from the `http://node:port/swagger-ui/`. Or you can get them from the output of `kubectl describe nodes`. Or `cadvisor`. :)
