### ISSUE TITLE
"Pod Disks should be able to detach from a node which was deleted" failing in release 1.7 branch

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#49185]
All the failures of this test are exactly the same - they are failing in this line:
https://github.com/kubernetes/kubernetes/blob/release-1.7/test/e2e/storage/pd.go#L452

which means that what is failing is running:
"gcloud compute instances list"

This may block 1.7.2 release.

@kubernetes/test-infra-maintainers @kubernetes/sig-storage-bugs @saad-ali

**Comment by wojtek-t** [comment]
It is failing in those suites:
https://k8s-testgrid.appspot.com/release-1.7-blocking#gci-gce-serial-release-1-7
https://k8s-testgrid.appspot.com/release-1.7-blocking#gce-serial-release-1-7


Interestingly GKE suites look fine...

**Comment by saad-ali** [comment]
CC @kubernetes/sig-storage-bugs

**Comment by saad-ali** [comment]
Looks like the test is only enabled to run on GCE not GKE.

And it looks like it is failing on master, 1.7, and 1.6 branches (it was introduced in 1.6):
* [gce-serial (master)](https://k8s-testgrid.appspot.com/google-gce#gce-serial&include-filter-by-regex=should%20be%20able%20to%20detach%20from%20a%20node%20which%20was%20deleted)
* [gci-gce-serial (master)](https://k8s-testgrid.appspot.com/google-gce#gci-gce-serial&include-filter-by-regex=should%20be%20able%20to%20detach%20from%20a%20node%20which%20was%20deleted)
* [gce-serial-release-1-7](https://k8s-testgrid.appspot.com/release-1.7-blocking#gce-serial-release-1-7&include-filter-by-regex=should%20be%20able%20to%20detach%20from%20a%20node%20which%20was%20deleted&include-filter-by-regex=should%20be%20able%20to%20detach%20from%20a%20node%20which%20was%20deleted)
* [gce-serial-1.6](https://k8s-testgrid.appspot.com/release-1.6-blocking#gce-serial-1.6&include-filter-by-regex=should%20be%20able%20to%20detach%20from%20a%20node%20which%20was%20deleted)

I'm going to add more logging to see what exactly the `gcloud` command is failing with.

**Comment by wojtek-t** [comment]
@saad-ali thanks for the update. I treat those failure as non-blocker then.

**Comment by wojtek-t** [comment]
I looked into logs and those are as following:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/pd.go:470
Unable to get list of node instances err=exit status 1 output=ERROR: (gcloud.compute.instances.list) Some requests did not succeed:
 - Required 'compute.instances.list' permission for 'projects/k8s-prow-builds'
```

I will check if I can change permissions in that project.

**Comment by wojtek-t** [comment]
@fejta @krzyzacy - seems like this has been broken by move to prow or sth like that.
Can you please fix?

**Comment by spxtr** [comment]
That is the project in which we are running the tests. Please do not give kubekins or pr-kubekins svc accounts access to that project. Probably some tests are misconfigured to point to that project by default or something.

**Comment by krzyzacy** [comment]
wait what how?

**Comment by krzyzacy** [comment]
ok I think I know what was going on

**Comment by fejta** [comment]
This is not a regression caused by https://github.com/kubernetes/kubernetes/blob/release-1.7/test/e2e/framework/test_context.go#L206

This is actually a bug in the test. This particular line of code is making [a raw gcloud](https://github.com/kubernetes/kubernetes/blob/release-1.7/test/e2e/storage/pd.go#L452).

Instead this should be passing `--project=cloudConfig.ProjectId` from [text_context.go](https://github.com/kubernetes/kubernetes/blob/release-1.7/test/e2e/framework/test_context.go#L206) like we do [elsewhere](https://github.com/kubernetes/kubernetes/blob/0dff56b4d88ec7551084bf89028dbeebf569620e/test/e2e/framework/ingress_utils.go#L649)

**Comment by krzyzacy** [comment]
/unassign
/unassign @fejta 
/assign @saad-ali 

This is probably going to pass now since I added `gcloud config set project` back, but still please fix the test to use the right test-context, we'll probably remove that call and fix everywhere not using the context properly instead.

**Comment by krzyzacy** [comment]
looks green now
/close
