### ISSUE TITLE
Proper Way to Install the kubenetes cluster on Centos Bare metal with 4node

### ISSUE THREAD

**Issue by thatsk** [kubernetes/kubernetes#49198]
@kubernetes/sig-area-test-infra
**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T02:00:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**:
Master 2GB(kubemaster1.example.com) (172.20.20.10)
other nodes (kubenode[1.3]example.com)2GB(172.20.20.[11.13])
- OS (e.g. from /etc/os-release):
Centos 7.3.1611
- Kernel (e.g. `uname -a`):
Linux  3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubeadm.x86_64                       1.7.1-0                         @kubernetes
kubectl.x86_64                       1.7.1-0                         @kubernetes
kubelet.x86_64                       1.7.1-0                         @kubernetes
kubernetes-cni.x86_64                0.5.1-0                         @kubernetes
Docker Version:-
docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

There is **no Proper Document for Kubernetes Cluster** So that People Can build their cluster using kubernetes , Centos, weavenet.
So I'm Creating this issue for it.
So i'm Starting from Scratch. I'm creating local lab setup with 4 nodes using Vagrantfile. PFA.
On kubemaster1.example.com:-
First i have disabled the selinux using disabled option.
Then as per Kubernetes Doc I have installed the rpm:-
[https://kubernetes.io/docs/setup/independent/install-kubeadm/]
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF
setenforce 0
yum install -y kubelet kubeadm
systemctl enable kubelet && systemctl start kubelet

That time kubelet service won't start because we have to configure the cluster .
So I have gone to next step for configuring the cluster using kubeadm
[https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm]

using kubeadm init command i'm initalizing the cluster but it won't start so start debugging
#24809
#43805

So the two issues fix for starting cluster one is
/etc/sysctl.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv6.conf.default.router_solicitations = 0
net.ipv6.conf.default.accept_ra_rtr_pref = 0
net.ipv6.conf.default.accept_ra_pinfo = 0
net.ipv6.conf.default.accept_ra_defrtr = 0
net.ipv6.conf.default.autoconf = 0
net.ipv6.conf.default.dad_transmits = 0
net.ipv6.conf.default.max_addresses = 1

Second one is :-
vi /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

KUBELET_CGROUP_ARGS=--cgroup-driver=cgroupfs

Then It starts initalizing.
But it continously giving error of 
Jul 19 10:38:18 kubemaster1 kubelet: W0719 10:38:18.949232    9853 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d
Jul 19 10:38:18 kubemaster1 kubelet: E0719 10:38:18.950589    9853 kubelet.go:2136] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Then it gives me:-
Your Kubernetes master has initialized successfully!

To start using your cluster, you need to run (as a regular user):

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  http://kubernetes.io/docs/admin/addons/

You can now join any number of machines by running the following on each node
as root:

  kubeadm join --token <token> 172.20.20.10:6443

When i check the all is working fine using 
kubectl get pods all --namespaces
kube-dns is not starting due to no allocatable node is there So i have used below command to schedule the kube-dns
**kubectl taint nodes --all node-role.kubernetes.io/master-**

So after that Dns is working fine.
and after that i have installed weave net because i dont want to use flannel  because due to below reason:-
[http://chunqi.li/2015/11/15/Battlefield-Calico-Flannel-Weave-and-Docker-Overlay-Network]
using this command:-
kubectl apply -f https://git.io/weave-kube-1.6

Then I'm going to join the node it give me error:-
root@kubenode1:/home/vagrant$ kubeadm join --token 54981c.22c56c60d5e9bf78 172.20.20.10:6443

[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[preflight] Running pre-flight checks
[preflight] WARNING: docker version is greater than the most recently validated version. Docker version: 17.06.0-ce. Max validated version: 1.12
[preflight] WARNING: hostname "" could not be reached
[preflight] WARNING: hostname "" lookup : no such host
[preflight] Some fatal errors occurred:
        hostname "" a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
[preflight] If you know what you are doing, you can skip pre-flight checks with `--skip-preflight-checks`

So that time i have to join that node to master so i have used --skip-preflight-checks
Then i have got the message 
root@kubenode1:/home/vagrant$ kubeadm join --token 54981c.22c56c60d5e9bf78 172.20.20.10:6443 --skip-preflight-checks
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[preflight] Skipping pre-flight checks
[discovery] Trying to connect to API Server "172.20.20.10:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://172.20.20.10:6443"
[discovery] Cluster info signature and contents are valid, will use API Server "https://172.20.20.10:6443"
[discovery] Successfully established connection with API Server "172.20.20.10:6443"
[bootstrap] Detected server version: v1.7.1
[bootstrap] The server supports the Certificates API (certificates.k8s.io/v1beta1)
[csr] Created API client to obtain unique certificate for this node, generating keys and certificate signing request
[csr] Received signed certificate from the API server, generating KubeConfig...
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"

Node join complete:
* Certificate signing request sent to master and response
  received.
* Kubelet informed of new secure connection details.

Run 'kubectl get nodes' on the master to see this machine join.

But when i run that command 👎 
kubectl get nodes
root@kubenode1:/home/vagrant$ kubectl get nodes
The connection to the server localhost:8080 was refused - did you specify the right host or port?

Where i have done wrong i don't know.

If anyone knows can you sort out because it might help other to build their cluster
[Vagrantfile.txt](https://github.com/kubernetes/kubernetes/files/1158902/Vagrantfile.txt)

**Comment by joantune** [comment]
@thatsk: I am struggling to use kubeadm 1.7 too. I enjoyed your thorough guide and report of what you were trying, although a bit dismaying. I think that you need to do /sig area-kubeadm

**Comment by piersbarrios** [comment]
At no point did you start docker, right ? 

systemctl enable docker && systemctl start docker

**Comment by piersbarrios** [comment]
Did you follow the instruction in kubeadm init ? 

```
To start using your cluster, you need to run (as a regular user):

mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
```

-----
By the way, at no point did you start docker in your instructions (although docker seems to be running because kubernetes starts) : 
`systemctl enable docker && systemctl start docker`

**Comment by piersbarrios** [comment]
Concerning having to do --skip-preflight-checks to join nodes. This is referenced as an official workaround https://github.com/kubernetes/kubeadm/issues/347 and should be fixed in 1.7.2

**Comment by joantune** [comment]
Sorry guys for the late reply.

@thatsk and everybody: following the instructions, I was able to install and successfully run `kubeadm`. However I used Ubuntu. I was drawn to this issue because of a specific error that I was having, but I think I was using outdated documentation that pointed me to use an old kubeadm (1.4 if i'm not mistaken) after using the official .deb repository and installing `kubeadm` 1.7.1 everything went smoothly minus the already mentioned need of using `--skip-preflight-checks`

**Comment by piersbarrios** [comment]
**Here is how I did it on my side**

**Comment by piersbarrios** [comment]
**Here is how I did it on my side: two VMs, (one master, one node)**
FYI: I use nano to edit files

**Vagrantfile** 
```
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :master, primary: true do |master_config|
    master_config.vm.box = "maier/centos-7.3.1611-x86_64"    
    master_config.vm.hostname = "K8t-M"
    master_config.vm.network "private_network", ip: "10.10.10.10"
  end
  config.vm.define :minion1 do |minion_config|
    minion_config.vm.box = "maier/centos-7.3.1611-x86_64"
    minion_config.vm.hostname = "K8t-Node"
    minion_config.vm.network "private_network", ip: "10.10.10.11"
  end
end
```

I am going to use two terminals, one for each VM. let's call them T1 and T2

**T1:** `mkdir kubernetes_playground && cd kubernetes_playground`
**T1:** add the Vagrantfile
**T1:** `vagrant up && vagrant ssh master`

**T2:** `vagrant ssh minion1`

**T1 & T2:** `sudo su`
(https://kubernetes.io/docs/setup/independent/install-kubeadm/)
**T1 & T2:** `yum install nano docker -y && systemctl enable docker && systemctl start docker`
**T1 & T2:** 
```
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF
setenforce 0
yum install -y kubelet kubeadm
systemctl enable kubelet && systemctl start kubelet
```
**T1 & T2:** `nano /proc/sys/net/bridge/bridge-nf-call-iptables`
Change the value from 0 to 1

**T1 & T2:** `nano /etc/systemd/system/kubelet.service.d/10-kubeadm.conf`
Delete the line with $KUBELET_NETWORK_ARGS
(from https://github.com/kubernetes/kubernetes/issues/48798#issuecomment-316223833)
**T1 & T2:** `systemctl daemon-reload && systemctl restart kubelet`

**T1:** `kubeadm init --apiserver-advertise-address 10.10.10.10`

(from the kubeadm init instructions)
**T1:**
```
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
```
**T1:**`kubectl apply -f https://git.io/weave-kube-1.6`


(WARNING: take your kubeadm join instruction with the correct token
**T2:** `kubeadm join --token XXX 10.10.10.10:6443 --skip-preflight-checks`

I'm going to do a vagrant destroy and start over to check this.

**Comment by bertrandrigaud** [comment]
Running on centos7 (kernel 3.10.0-514.26.2.el7.x86_64)
`kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:23:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?`

`kubeadm join --token=XXX xxx.xxx.xxx.xxx:6443
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[preflight] Running pre-flight checks
[preflight] WARNING: hostname "" could not be reached
[preflight] WARNING: hostname "" lookup : no such host
[preflight] Some fatal errors occurred:
	hostname "" a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
[preflight] If you know what you are doing, you can skip pre-flight checks with `--skip-preflight-checks`

--skip-preflight-checks issue is still there in kubeadm 1.7.2
skipping preflight-checks works but then `kubectl get nodes` on master won't show anything.

**Comment by m-no-2017** [comment]
I fixed the "WARNING: hostname "" lookup" with a correction of the /etc/hosts entries and a restart of the kubelet services on all nodes.  
_Note: The hostname lookup and node registration comes from the kubelet and the kubelet relies on the docker service._  
Just my few cents but i had a similar problem with a manual (no kubeadm) bootstrap of a k8s HA cluster (props to [this](https://github.com/kelseyhightower/kubernetes-the-hard-way) guy):
- kubelet could not resolve hostname
- no registration triggered
- kube-proxy fell back to localhost IP as listener address
- cluster had no nodes ready (not even listed the nodes)

**Comment by vikasgubbi** [comment]
Please advice how to fix the below error message. I am new to kubernetes

#kubeadm join --token 3c4bdf.c38ebcd0449f5632  x.x.x.x:6443 --skip-preflight-checks  --discovery-token-unsafe-skip-ca-verification
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[preflight] Skipping pre-flight checks
[discovery] Trying to connect to API Server "x.x.x.x:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://x.x.x.x:6443"
[discovery] Cluster info signature and contents are valid and no TLS pinning was specified, will use API Server "x.x.x.x:6443"
[discovery] Successfully established connection with API Server "x.x.x.x:6443"
failed to check server version: Get https://x.x.x.x:6443/version: x509: certificate has expired or is not yet valid

**Comment by thatsk** [comment]
Have you tried kubeadm 1.8. it must work

**Comment by vikasgubbi** [comment]
Yes, its latest version.

[root@kubemaster ~]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:27:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by mgmjoke** [comment]
oooh! It went well.
You're a god!

**Comment by thatsk** [comment]
ok i think we are good to close this ticket

**Comment by thatsk** [comment]
the new issue with new version :
https://github.com/kubernetes/kubernetes/issues/56850
