### ISSUE TITLE
field label spec.schedulerName not supported 

### ISSUE THREAD

**Issue by shivramsrivastava** [kubernetes/kubernetes#49190]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:

When trying to list object using field  spec.SchedulerName, we are getting the below error message.

**Failed to list  `*v1.Pod` : field label not supported: spec.schedulerName**

**What you expected to happen**:

To be able to fetch pods using the list and watch based on the field 'spec.schedulerName'

**How to reproduce it (as minimally and precisely as possible)**:

Create a simple controller to with a list and watch method.
Set the FieldSelector  ( in the ListOptions structure ) in the ListFunc and the WatchFunc to 'spec.SchedulerName=custome-SchedulerName'
Running this controller yields the above error.

**Anything else we need to know?**:

Description:

Unable to fetch pods based on the field 'spec.schedulerName'.
This was added in 1.6 version, for multi scheduler support in kubernetes.

We need to be able to fetch pods 

1) Assigned to a particular custom scheduler.
2) Should be able to fetch the state transition of the pods scheduled by a custom scheduler using the fields selector.

  Whats the correct way to use 'schedulerName' fields for fetching objects?
  Or is there any other way for the custom scheduler to determine the above information from the kubernetes?
  
  
  This is an urgent issue, any quick help/suggestion will be of great help.
  
  

**Environment**:
- Kubernetes version :
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T01:48:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Install tools: kubeadm

@kubernetes/sig-scheduling-bugs

@davidopp 
@deepak-vij

**Comment by lavalamp** [comment]
cc @bsalamat

**Comment by lavalamp** [comment]
SIG API Machinery doesn't own the *contents* of the API--we only need to be involved if the mechanism needs to be general.

**Comment by davidopp** [comment]
@lavalamp Given the error message mentioned in the bug report at the top of this thread, do you have a suggestion of what we forgot to do when we added the SchedulerName field to the PodSpec? i.e. to enable field selection on the schedulerName field?
