### ISSUE TITLE
Fix k8s.io/metrics dependency on k8s.io/api

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#49200]
Compare https://github.com/kubernetes/kubernetes/pull/49091#issuecomment-316364570.

**Comment by deads2k** [comment]
@DirectXMan12 The dependency on particular types (especially *those* types), is likely to lead to bad behavior.  We should remove temptation if the cost isn't very high.

**Comment by lavalamp** [comment]
It is not obvious that this is actually an important layering problem? What bad thing happens if the metrics api depends on the core API? I don't think the core API would ever depend on the metrics API, so it shouldn't be a problem in the future?

**Comment by DirectXMan12** [comment]
Yeah, I'm not entirely certain what the issue is here.  IMO, we *want* to say that they're the same object reference.  That way, for instance, if I have a function which fetches an object from an object reference, it works on *any* object reference, not just the one from the core API.
