### ISSUE TITLE
clientset always crated from LoopbackClientConfig

### ISSUE THREAD

**Issue by p0lyn0mial** [kubernetes/kubernetes#49208]
**What happened**: The issue I am observing is that [clienset](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/options/admission.go#L72) meant for [generic admission plugin](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/initializer/initializer.go) are always created from `LoopbackClientConfig `. This can lead to a situation in which an admission plugin accepting `clientset` will be unable to talk to kube API server. The generic admission initializer can be used by an admission plugin that lives within an external API server i.e. federation. 

The situation resembles the one we [had](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/options/serving.go#L201) with `SharedInformerFactory`. Back then we decided that `informers` will use in-cluster configuration by default. Only kube API can "force" the usage of `LoopbackConfig` for `informers`

**What you expected to happen**: I think the behaviour of `clientset` should be similar to the one that `informers` have. By default use in-cluster config, when forced use `LoopbackConfig`.

**Comment by p0lyn0mial** [comment]
@deads2k @sttts FYI

**Comment by lavalamp** [comment]
Please ask @caesarxuchao for a review / discussion if you want to make changes here.

**Comment by p0lyn0mial** [comment]
@caesarxuchao Sad to say but I am the author of that code and I know it is buggy :)
@caesarxuchao I am open to suggestions on possible solutions.

**Comment by nikhita** [comment]
/remove-lifecycle stale

@p0lyn0mial This issue has a help-wanted label. Do you intend to work on this? If yes, I'll remove the label.

Just trying to make sure that all help-wanted issues are issues where we are really looking for help. :)

**Comment by nikhita** [comment]
/remove-lifecycle stale

I don't think this qualifies for a help-wanted issue.
/remove-help

**Comment by liggitt** [comment]
this now is constructed using a client config specifically for communicating with the kube apiserver:

https://github.com/kubernetes/kubernetes/blob/7098f1ad383b84bc8e807b049ab42629a70bb04e/staging/src/k8s.io/apiserver/pkg/server/options/admission.go#L142-L146

called from

https://github.com/kubernetes/kubernetes/blob/7098f1ad383b84bc8e807b049ab42629a70bb04e/staging/src/k8s.io/apiserver/pkg/server/options/recommended.go#L111

by default, this uses the explicitly set kube server client config, or in-cluster config, not loopback:

https://github.com/kubernetes/kubernetes/blob/7098f1ad383b84bc8e807b049ab42629a70bb04e/staging/src/k8s.io/apiserver/pkg/server/config.go#L196-L199
