### ISSUE TITLE
Split configMap, secret, and downwardAPI tests into two files: volume and non-volume

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#49217]
As part of https://github.com/kubernetes/kubernetes/issues/49161 all tests should be labeld with `sig-*` to signify which SIG owns them. 

Today all configMap, secret, and downwardAPI E2E tests can be found here:
* [test/e2e/common/configmap.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/configmap.go)
* [test/e2e/common/downward_api.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/downward_api.go)
* [test/e2e/common/secrets.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/secrets.go)

These include volume and non-volume tests. Volume tests should be owned by `sig-storage` and non-volume tests should be owned by someone else (APIMachinery?). Ideally we want `KubeDescribe` to be prefixed with the `[sig-*]` label, but because these files contain a mix, each test is instead suffixed.

Suggestion: split these tests into two files: volume and non-volume. So that all the tests in a file can have a single `KubeDescribe` with a single `[sig-*]` prefix.

Suggestion from @pwittrock and @grodrigues3

**Comment by xiangpengzhao** [comment]
@saad-ali any updates here? If so, please ping me in order to update https://github.com/kubernetes/kubernetes/issues/49161#issuecomment-320502371. Thanks!

**Comment by davidz627** [comment]
Oops. I'll be working on this anyway.

**Comment by xiangpengzhao** [comment]
@davidz627 thanks! Please also ping me in your coming PR(s).

**Comment by davidz627** [comment]
PR: #51567

**Comment by davidz627** [comment]
I noticed there are other tests such as:
[k8s.io] EmptyDir volumes should support (non-root,0644,default) [Conformance] [sig-storage]
in test/e2e/common/empty_dir.go.

That are not referenced in this issue but seem to pertain to the same umbrella issue. Are these referenced in a different issue or am I just misunderstanding?

**Comment by xiangpengzhao** [comment]
@davidz627 they were covered by https://github.com/kubernetes/kubernetes/issues/49161#issuecomment-320502371
