### ISSUE TITLE
hack/update-staging-godeps.sh is not working on head

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#49210]
first in notices that Godeps are wrong and removes
```
-                       "ImportPath": "github.com/davecgh/go-spew/spew",
-                       "Rev": "782f4967f2dc4564575ca782fe2d04090b5faca8"
```
which is fine.

But afterwards it fails:
```
Updating godeps for k8s.io/apiextensions-apiserver
  godep: Package (github.com/emicklei/go-restful/swagger) not found
```

@kubernetes/sig-api-machinery-bugs

**Comment by cblecker** [comment]
@gmarek Did you run `hack/godep-restore.sh` before running the update script? I found a bug in the current master version of the script (#49247) but it doesn't seem related.

**Comment by caesarxuchao** [comment]
Could it be caused by:

```
# If you haven't followed this doc step-by-step and haven't created a dedicated GOPATH,
# make sure there is no client-go or other staging repo in $GOPATH before running the next command.
./hack/update-staging-godeps.sh
```

It's recently updated in https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md.

**Comment by caesarxuchao** [comment]
@gmarek do you still have the issue? Is the updated [doc](https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md) working for you?
