### ISSUE TITLE
phase out cluster/ directory

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#49213]
sig-cluster-lifecycle has decided to phase out the cluster/ directory over the next couple releases in favor of deployment automations maintained outside of the core repo and outside of kubernetes orgs.
 
@kubernetes/sig-cluster-lifecycle-misc

**Comment by madhusudancs** [comment]
cc @kubernetes/sig-federation-misc

**Comment by madhusudancs** [comment]
This affects federation. Federation test-infra depends on `cluster/` right now. What's the recommended solution for cloud resource provisioning? It's `kubeadm` for cluster turn up, I believe?

**Comment by roberthbailey** [comment]
What kind of resource provisioning are you thinking of? kubeadm is designed to run on machines that are pre-provisioned. For e2e tests of kubeadm we are currently using kubernetes-anywhere (which uses terraform) to create the VMs on which to run tests.

**Comment by csbell** [comment]
The dependency seems to be mostly on some of the cluster bash lib utilities
(cluster/lib/logging.sh) and some wrappers kubectl.sh. Copying the relevant
bits to federation/cluster/common.sh might be workable.

Since federation tests are blocking, any attempts to move cluster/ will
show be apparent.

**Comment by madhusudancs** [comment]
> What kind of resource provisioning are you thinking of? 

VMs, network, etc. We just need kubernetes clusters running on GCE like most other kubernetes tests would need, with an exception that we need multiple clusters instead of one and some additional network configuration. It has been a while since I last tried kubernetes-anywhere, so may be that's an alternative worth evaluating.

> The dependency seems to be mostly on some of the cluster bash lib utilities (cluster/lib/logging.sh) and some wrappers kubectl.sh. Copying the relevant bits to federation/cluster/common.sh might be workable.

Federation tests are entirely built on top `kube-{up,down}.sh`. They also use `cluster/lib`. But it depends on pretty much everything that's related to `kube-up`.

**Comment by luxas** [comment]
@madhusudancs I'd love to see if we can get federation e2e's working smoothly on top of kubeadm e2e clusters. 

The only thing that would be a hard limit is spawning two or more clusters, right?
Then we'd be running `kubefed init --args` and something like `e2e.test --ginkgo.focus="Federation"` and it should work?

**Comment by madhusudancs** [comment]
@luxas at a high level, yes. There are some intricate details. For example, clusters must use different CIDRs for pod addresses, they should be in different zones, etc. But those details could be worked out and shouldn't be hard. And spawning multiple clusters shouldn't be difficult as well. They could be separate, possibly parallel, invocations of kubeadm.

**Comment by luxas** [comment]
@madhusudancs Yeah, I think it should be pretty straightforward as long as one knows how to create VMs on GCE :)

Would you like to join our SIG call later today to spec out details?

**Comment by madhusudancs** [comment]
@luxas I am already too late for today's meeting. I cannot join the meeting next week and the week following that because it overlaps with SIG-Federation meetings. May be in 3 weeks from now, if you can put it on the agenda?

**Comment by madhusudancs** [comment]
Also cc @shashidharatd who is interested in this.

**Comment by luxas** [comment]
@madhusudancs We have a meeting on Friday 9 PT if that works for you as well

**Comment by irfanurrehman** [comment]
@luxas, I am also interested in this effort. Is the link posted on the community page for [sig-cluster-lifecycle](https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle) the meeting link to join?
@madhusudancs @shashidharatd can we consolidate this effort (may be post this meeting, or some other time) to address this and [similar discussion](https://docs.google.com/document/d/18mk62nOXE_MCSSnb4yJD_8UadtzJrYyJxFwbrgabHe8/edit#bookmark=id.goz5rxbpw7ao) from our last federation sig meeting also.

**Comment by madhusudancs** [comment]
@luxas I can't make it to the meeting tomorrow too. 

@irfanurrehman @shashidharatd feel free to go if you can tomorrow. 

> @madhusudancs @shashidharatd can we consolidate this effort (may be post this meeting, or some other time) to address this and similar discussion from our last federation sig meeting also.

Sure.

**Comment by luxas** [comment]
How about we put this on the agenda for 08/04 or 08/15?

@madhusudancs You mean the sig-cluster-lifecycle calls on those dates, right?

**Comment by madhusudancs** [comment]
@luxas yeah.

**Comment by bgrant0607** [comment]
Ref #24343

**Comment by urzds** [comment]
If the `openstack-heat` provider for `kube-up` is now deprecated: What is the currently recommended method to setup Kubernetes on OpenStack?

/cc @magreiner

**Comment by luxas** [comment]
@dims @shashidharatd @jamiehannaford  ^

**Comment by jamiehannaford** [comment]
@urzds I'm not sure about official recommendation by K8s/CNCF, but my team has had a lot of success with CoreOS's [tectonic-installer](https://github.com/coreos/tectonic-installer). I believe [Kubespray](https://github.com/kubernetes-incubator/kubespray) also supports OpenStack. There are a lot of different provisioning tools out there, so it really depends on the technologies you're most familiar and comfortable with.

Hopefully when the kubelet uses dynamic config and OpenStack gets a stable cloud controller, you'll just need to deploy your infra and then K8s upwards is handled by kubeadm.

**Comment by dims** [comment]
@urzds - see https://medium.com/@arthur.souzamiranda/kubernetes-with-openstack-cloud-provider-current-state-and-upcoming-changes-part-1-of-2-48b161ea449a on how to use OpenStack with kubeadm. It's a great way to start experimenting

**Comment by civik** [comment]
So with the deprecation of this repo, where is one to find example configuration artifacts that are version controlled, and with all params defined with sane defaults for each k8s component?  The config/ repo was the closest thing I have found to this.

**Comment by luxas** [comment]
This is what kubeadm does @civik; defines sane defaults for you for any best-practice cluster.
It is intentionally limited in scope so that it doesn't deal with provisioning in order to fit into the maximum amount of envs.

See for example our design doc: https://github.com/kubernetes/kubeadm/blob/master/docs/design/design_v1.8.md

**Comment by roberthbailey** [comment]
We've also had discussions about storing canonical addon definitions outside of the main repo (e.g. https://github.com/kubernetes/k8s.io/issues/5) but we haven't settled on where that would be or what form they would take. I think it's safe to say that having a new home for example manifests should be in scope for us before removing the addon manifests from the cluster directory.

**Comment by civik** [comment]
@luxas I guess my counter to that would be that until kubectl can be blessed for use for a 'production' deployment that shouldn't be the place for defining the 'according to Hoyle' configs. If I'm deploying Kubernetes in a custom built pipeline that deploys a HA cluster, I currently have to run kubectl 'out of band' to somewhat manually determine what config options/defaults have changed.  It would be nice if there was a traditional example conf file for the components with all the options with their defaults, with descriptive in-line comments.  Changes to switches and defaults between versions would then be as simple as a diff.

**Comment by mikedanese** [comment]
I'm going send PRs to remove some of the deprecated kube-up dirs this release.

**Comment by mikedanese** [comment]
I want to delete cluster/{windows/,photon-controller/,libvirt-coreos/,gce/container-linux} this release.

**Comment by mikedanese** [comment]
Various non-critical addons have been pretty noisy in the vulnscans. Unfortunately many of our e2e tests currently depend on them.

**Comment by luxas** [comment]
@mikedanese @kubernetes/cloud-provider-gcp-maintainers What's the status of moving out the GCE cluster setup code you have to the new cloud-provider repo in favor of `cluster/`?

**Comment by mikedanese** [comment]
It's blocked on decoupling from e2e. Someone needs to do the work, and it unfortunately hasn't been prioritized.

**Comment by luxas** [comment]
cc @roberthbailey

**Comment by dims** [comment]
i know this is the older one, but let's continue the conversation in https://github.com/kubernetes/kubernetes/issues/78995

/close
