### ISSUE TITLE
Kube-controller-manager fails to start with Azure cloud provider 

### ISSUE THREAD

**Issue by githubvick** [kubernetes/kubernetes#49228]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:

Kube controller manager crashes when adding cloud provider argument as Azure

**What you expected to happen**:
Kube controller manager should function properly,

**How to reproduce it (as minimally and precisely as possible)**:

Add cloud prov parameter in kubeapiserver
KUBE_API_ARGS="--tls-cert-file=/etc/kubernetes/certs/server.crt --tls-private-key-file=/etc/kubernetes/certs/server.key --client-ca-file=/etc/kubernetes/certs/ca.crt --token-auth-file=/etc/kubernetes/tokens/known_tokens.csv --service-account-key-file=/etc/kubernetes/certs/server.crt --bind-address=0.0.0.0 --apiserver-count=1 --cloud-provider=azure "
Add parameter in controller manager

KUBE_CONTROLLER_MANAGER_ARGS="--kubeconfig=/etc/kubernetes/controller-manager.kubeconfig --service-account-private-key-file=/etc/kubernetes/certs/server.key --root-ca-file=/etc/kubernetes/certs/ca.crt --cloud-provider=azure "

kube api server starts but kube controller managers crashes

**Anything else we need to know?**:
Kubernetes was installed through Ansible contrib

**Environment**:
- Kubernetes version (use `kubectl version`):kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"269f928217957e7126dc87e6adfa82242bfe5b1e", GitTreeState:"clean", BuildDate:"2017-07-03T15:31:10Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"269f928217957e7126dc87e6adfa82242bfe5b1e", GitTreeState:"clean", BuildDate:"2017-07-03T15:31:10Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
[testadmin@hostname ~]$

- Cloud provider or hardware configuration**: Azure
- OS (e.g. from /etc/os-release):
 NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"

- Kernel (e.g. `uname -a`): Linux hostname 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
Error gist below
```
Jul 19 19:36:53 hostname systemd[1]: kube-controller-manager.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 19 19:36:54 hostname kube-controller-manager[17502]: I0719 19:36:54.355473   17502 leaderelection.go:188] sucessfully acquired lease kube-system/kube-controller-manager
Jul 19 19:36:54 hostname kube-controller-manager[17502]: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
Jul 19 19:36:54 hostname kube-controller-manager[17502]: panic: runtime error: invalid memory address or nil pointer dereference
```
Complete logs in file
[logs.txt](https://github.com/kubernetes/kubernetes/files/1160292/logs.txt)

/sig azure

**Comment by githubvick** [comment]
@dixudx I'm trying to make this work atleast with the conf file.

When I specify this way 

KUBE_CONTROLLER_MANAGER_ARGS="--kubeconfig=/etc/kubernetes/controller-manager.kubeconfig --service-account-private-key-file=/etc/kubernetes/certs/server.key --root-ca-file=/etc/kubernetes/certs/ca.crt --cloud-provider=azure --cloud-config=/etc/azure/azure.conf"

It starts properly, but fails when I try to deploy a load balancer. The logs are attached. Could you please suggest some way this could be fixed?
[log.txt](https://github.com/kubernetes/kubernetes/files/1162857/log.txt)

**Comment by dixudx** [comment]
@githubvick This seems to be another issue. Would you please open a new issue for tracking. Also I want to identify that you're still using v1.5.2, right? Please also add a new argument `-v 1` to `KUBE_CONTROLLER_MANAGER_ARGS` to enable more loggings. Thanks.

**Comment by githubvick** [comment]
Yes, I am using v1.5.2.

I had added --v=4 to controller manager and the logs attached.
[log.txt](https://github.com/kubernetes/kubernetes/files/1165893/log.txt)
