### ISSUE TITLE
federation-controller/service TestServiceController unit test flake

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#49221]
[k8s.io/kubernetes/federation/pkg/federation-controller/service TestServiceController 30s](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/48217/pull-kubernetes-unit/41693/)
```
go test -v k8s.io/kubernetes/federation/pkg/federation-controller/service -run TestServiceController$
<autogenerated>:12: 
                         
	Error Trace:	servicecontroller_test.go:156
	
	Error:      	Received unexpected error:
	
	            	timed out waiting for the condition
```
@kubernetes/sig-federation-test-failures

**Comment by dixudx** [comment]
This test passes in my local env. Also passed in [latest 48217/pull-kubernetes-unit](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/48217/pull-kubernetes-unit/41708/).

This issue can be closed now I think.

**Comment by kargakis** [comment]
@dixudx any idea what fixed it?

**Comment by dixudx** [comment]
@kargakis I tried, but didn't find anything. It cannot reproduce right now. And that log did not show anything valuable.
