### ISSUE TITLE
Open API generates conflicting Operation ID

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#49250]
**BUG REPORT**: 
I found this while adding apps/v1beta2 ReplicaSet (originally extensions/v1beta1) in https://github.com/kubernetes/kubernetes/pull/49238

When updating swagger docs I got this error in swagger-api-server.log:
```
F0719 16:35:31.282498  109744 openapi.go:38] Failed to register open api spec for root: Duplicate Operation ID readAppsV1beta2NamespacedScaleScale for path /apis/apps/v1beta2/namespaces/{namespace}/deployments/{name}/scale and /apis/apps/v1beta2/namespaces/{namespace}/replicasets/{name}/scale.
```

I believe it is because of some bugs in open api, see [api/openapi-spec/swagger.json](https://github.com/kubernetes/kubernetes/blob/v1.8.0-alpha.2/api/openapi-spec/swagger.json):
```json
"/apis/apps/v1beta1/namespaces/{namespace}/deployments/{name}/scale": {
     "operationId": "readAppsV1beta1NamespacedScaleScale",
}

"/apis/extensions/v1beta1/namespaces/{namespace}/deployments/{name}/scale": { 
     "operationId": "readExtensionsV1beta1NamespacedDeploymentsScale",
}
```

`/extensions/v1beta1/deployments/scale` won't conflict with `/extensions/v1beta1/replicasets/scale` because it's named `readExtensionsV1beta1Namespaced<Resource>Scale`. 

`/apps/v1beta2/deployments/scale` will conflict with `/apps/v1beta2/replicasets/scale` because they both name it `readAppsV1beta1NamespacedScaleScale`. 

/assign @mehdy 
@kubernetes/sig-api-machinery-bugs

**Comment by crimsonfaith91** [comment]
I also have the same bug for statefulset (working on a statefulset PR).

**Comment by janetkuo** [comment]
cc @pwittrock

**Comment by janetkuo** [comment]
Just sync with @mbohlool offline. Open API expects kind name to be unique (such as `PodStatus`, `DeploymentStatus` for `status` subresource). Because `Scale` kind name is not unique, it generates conflicting Operation ID `...ScaleScale` for both Deployments, ReplicaSets, and StatefulSets. 

@mbohlool is trying to fix the root cause. If that's too much work for 1.8, here's a hack that we can potentially use as a temp fix:
https://github.com/mbohlool/kubernetes/blame/4379bbdafbd38bdc67f2ceb5cb7a4e778baebf04/staging/src/k8s.io/apiserver/pkg/endpoints/openapi/openapi.go#L66-L66

**Comment by crimsonfaith91** [comment]
+1 for temp fix

**Comment by mbohlool** [comment]
I believe I identified a fix for the root cause and it shouldn't be hard to implement. Will send a PR soon.

**Comment by crimsonfaith91** [comment]
@mbohlool Thanks! Appreciate it! :)
