### ISSUE TITLE
kubeadm init hang up problem when NOT using systemd and selinux

### ISSUE THREAD

**Issue by byungnam** [kubernetes/kubernetes#49269]
Hi. 

I'm currently trying to install kubernetes for my Gentoo machines with help of the [manual](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/) (I know kubernetes manuals are written for Ubuntu or CentOS but I believe a Linux is a Linux and a binary can be executed in any of the distributions). At the beginning, everything went pretty harsh, but I've managed to get to the stage to start `kubeadm init`. 

The problem is that I'm stuck on the message `Created API client, waiting for the control plane to become ready`. I've already searched the problem and found several threads previously discussed in #33544 #45064 #33729 but none of them were helpful for me because my machine neither uses selinux nor systemd.

Below is what I see when I executed `kubeadm init`
```
ns2 ~/kubernetes # ./kubernetes/server/bin/kubeadm init
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.7.1
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks
[preflight] WARNING: docker version is greater than the most recently validated version. Docker version: 17.03.1-ce. Max validated version: 1.12
[preflight] WARNING: no supported init system detected, skipping checking for services
[preflight] WARNING: no supported init system detected, skipping checking for services
[preflight] WARNING: no supported init system detected, skipping checking for services
[preflight] WARNING: socat not found in system path
[preflight] No supported init system detected, won't ensure kubelet is running.
[certificates] Generated CA certificate and key.
[certificates] Generated API server certificate and key.
[certificates] API Server serving cert is signed for DNS names [ns2 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 163.152.163.55]
[certificates] Generated API server kubelet client certificate and key.
[certificates] Generated service account token signing key and public key.
[certificates] Generated front-proxy CA certificate and key.
[certificates] Generated front-proxy client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/scheduler.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/controller-manager.conf"
[apiclient] Created API client, waiting for the control plane to become ready

```

Any help would be appreciated.

Thank you.

**Environment**:
- kubectl version : Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T02:00:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
-(Maybe the above message can be another strange one though.)
- OS :  Gentoo Linux
- Kernel : Linux ns2 4.9.34-gentoo #7 SMP Wed Jul 19 13:04:15 KST 2017 x86_64 Intel(R) Xeon(R) CPU X5680 @ 3.33GHz GenuineIntel GNU/Linux

/area kubeadm
/help-wanted

**Comment by luxas** [comment]
Please reopen this in https://github.com/kubernetes/kubeadm
