### ISSUE TITLE
Create more examples

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#4926]
It would be great to create more examples using Kubernetes.

List of examples:
https://github.com/GoogleCloudPlatform/kubernetes/issues?q=is%3Aopen+is%3Aissue+label%3Akind%2Fexample

**Comment by hTrap** [comment]
Hello, 
I am a prospective gsoc2015 applicant and would really like to contribute to this community, I chose this project as it would help me understand the code base of the project and also its use-cases and limitations, which would help me in future contributions.
Could you assign me a small task of creating a small example, that would help me get to speed more effectively.

**Comment by bgrant0607** [comment]
Hi, @hTrap. Thanks for your interest. Please give me a couple days to scope this project properly.

**Comment by hTrap** [comment]
@bgrant0607 sure, till then ill go through the docs and set it up locally .

**Comment by thockin** [comment]
I'll give you the same advice I give every prospective newcomer to the
project:

1) Learn go.  Just doing to golang tour should be sufficient.

2) Learn git and GitHub.  GitHub has a walk-through that is pretty easy.

3) Set up a kubernetes cluster from the docs - GCE or Vagrant are most
likely to work on any given version.  Anything that does not work EXACTLY
as the docs say should either have a bug filed or a doc fix offered.

4) Once you have a cluster up, pick a piece of the system that sounds
interesting - scheduler, kubelet, apiserver, proxy, controllers, etc.
Start at main() and trace through code.  Every time you find something that
doesn't make sense - hack.  Add comments, rename variables, refactor
functions, etc until it is clearer.  Send pull requests.

If you can make it 30 minutes without finding something you want to fix,
I'll be shocked :)

**Comment by hTrap** [comment]
@thockin Thanks a lot for the heads up, i was already working on the first 3 points, the fourth one is really helpful. Though a couple of months back i went through the docs and fixed a few minor typos in the docs as and when they were coming up ,  i never went through the code base. I guess now i will. Thanks a lot for your help, i'll keep you guys posted.

**Comment by xudifsd** [comment]
Hi, I'm also interested in gsco2015, I have a cluster seted up, and currently digging the source code. I'm wondering if there are any idea page or guidelines or something like that, so we can read code more targetedly and more efficiently.
For example, I think idea page from [clojure community](http://dev.clojure.org/display/community/Project+Ideas) is much easier to understand for a student.

**Comment by rashmimargani** [comment]
Hi,

I'm GSOC  2015 applicant,  I like to contribute this community.. previously i have been assigned on docker container  live migration with vmware project in institution............ but, i never went through code  base, i and my team spent lot time in understanding constraints in docker. Anyone please suggest me with few things, so that i can trace the code fast enough.... and understand whole project clearly.

**Comment by bgrant0607** [comment]
Thanks for the pointer @xudifsd. 

I created a wiki re. participation: https://github.com/GoogleCloudPlatform/kubernetes/wiki/Google-Summer-of-Code-(GSoC)

GSoC project ideas are labeled kind/gsoc:
https://github.com/GoogleCloudPlatform/kubernetes/labels/kind%2Fgsoc

"Starter project" ideas are labeled help-wanted (note that not all are necessarily small/easy):
https://github.com/GoogleCloudPlatform/kubernetes/labels/status%2Fhelp-wanted

This specific issue was about creating a more comprehensive, better documented set of examples using popular open-source applications. I'd expect:
* Well organized, ideally attractive catalog of examples, ideally with parameterized/reusable configurations (#2837)
* Easy to launch the examples
* Each example should be systematically organized (#2841), esp. in a way that can take full advantage of kubectl bulk creation by directory
* Realistic deployment configurations
* Correct usage of Kubernetes APIs, tools, features, etc. -- demonstrates best practices
* Screencasts or videos, in addition to detailed textual walkthroughs
  * Visually attractive demo, such as the [update demo](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/update-demo)
* Thorough documentation / filed feature requests for any workarounds that were necessary
* Necessary changes to third-party apps pushed upstream
* Coverage of Kubernetes features:
  * Multiple containers and volumes per pod
  * Scaling
  * Secrets
  * Persistent volumes
  * Canary deployment, rolling update, and/or rollback
  * DNS
  * Endpoints API
  * Log retrieval
  * Resource monitoring
* Coverage of representative workloads, including:
  * content-management system (e.g., Drupal)
  * storage backends -- some kvs/db not represented by the time May rolls around (mongodb?)
  * some application using master election (e.g., [Postgres](https://blog.compose.io/high-availability-for-postgresql-batteries-not-included/))
  * message queues (e.g., Kafka, RabbitMQ)
  * load balancers (e.g., HAProxy, nginx)
  * data processing (e.g., Hadoop)
* Documented common patterns, best practices, and troubleshooting tips

**Comment by kirtijagtap** [comment]
Hi, I am new to GSoC as well as GoogleCloud Platform, but though it would be a great idea to start with this issue for GSoC. I am willing to put in all the work necessary. Please allow me to work on the project.

**Comment by bgrant0607** [comment]
@kirtijagtap You need to apply through the GSoC site. Please take a look at the [wiki](https://github.com/GoogleCloudPlatform/kubernetes/wiki/Google-Summer-of-Code-(GSoC)).

**Comment by bgrant0607** [comment]
cc @timstclair

**Comment by bgrant0607** [comment]
This is blocked on #15193 and #5465

**Comment by bgrant0607** [comment]
We need a good example of a multi-container pod.

Here's one:
http://paulbakker.io/kubernetes/kubernetes-static-sites/

Which is a more complete version of:
https://github.com/kubernetes/kubernetes/blob/4ca66d2aefa20c27b670b2fa890052daadc05294/docs/user-guide/production-pods.md#helper-containers

**Comment by bgrant0607** [comment]
Openshift examples:
https://github.com/openshift/origin/tree/master/examples

Openshift also has examples in other repos, such as:
https://github.com/openshift/postgresql/tree/master/examples/replica

Helm charts:
https://github.com/helm/charts

DM templates:
https://github.com/kubernetes/application-dm-templates

**Comment by bgrant0607** [comment]
Jenkins: https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes

**Comment by bgrant0607** [comment]
We need a good example of a production-ready deployment, with things like:
* liveness and readiness probes
* logs collected from a volume
* proper resource requests
* terminationGracePeriodSeconds and/or preStop hook
* terminationMessagePath
* private registry
* secrets and configmap
* securityContext (ideally runAsNonRoot)

cc @kubernetes/examples

**Comment by bgrant0607** [comment]
We have guidelines now:
https://github.com/kubernetes/kubernetes/blob/master/examples/guidelines.md
