### ISSUE TITLE
[feature] Shall we keep controller/scheduler re-campaigning as a follower instead of crashing after leadership lost

### ISSUE THREAD

**Issue by wu8685** [kubernetes/kubernetes#49260]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Every time apiserver or etcd unavailable, the controller manager/scheduler leader will choose to crash to give up leadership.

**What you expected to happen**:

Crashing is a convenient way to lose leadership, and it is expected in codes. But a service is not expected to crash caused by the reason not from itself.
Instead of crashing, could controller manager/scheduler just stop what it is doing as a leader and re-campaign leader election as a follower.

**How to reproduce it (as minimally and precisely as possible)**:

Stop all of kube-apiservers or half of etcd nodes to make leadership [renew()](https://github.com/kubernetes/client-go/blob/master/tools/leaderelection/leaderelection.go#L146) timeout

**Comment by wu8685** [comment]
@kubernetes/sig-cluster-ops-feature-requests
@kubernetes/sig-architecture-feature-requests
@kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by timothysc** [comment]
State is indeterminate and reconciliation is cleaner with a restart, b/c it would need to repopulate all of it's caches.  

All workloads will continue running and fail-over timeout is tunable.
