### ISSUE TITLE
Port collision between kube-proxy and node-problem-detector (standalone mode)

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#49263]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Since k8s v1.7, kube-proxy starts listening on 0.0.0.0:10256 to serve default /healthz traffic from L4 external/internal loadbalancer (https://github.com/kubernetes/kubernetes/pull/44968).

When node-problem-detector runs in [`standalone`](https://github.com/kubernetes/kubernetes/blob/v1.7.1/cluster/gce/config-default.sh#L180-L191) mode, it is a real daemon on node. By default, it will bind 127.0.0.1:10256 for the use of node problem detector server (https://github.com/kubernetes/node-problem-detector/blob/v0.4/cmd/options/options.go#L66-L67).

This breaks kube-proxy's default healthz server:
```
E0719 22:13:54.263011       5 healthcheck.go:302] Failed to start healthz on 0.0.0.0:10256: listen tcp 0.0.0.0:10256: bind: address already in use
```

**What you expected to happen**:
kube-proxy and node-problem-detector should use different ports.

**How to reproduce it (as minimally and precisely as possible)**:
Create a 1.7 cluster with node-problem-detector enabled with standalone mode.

**Anything else we need to know?**:
/assign
/sig network
cc @ajitak @Random-Liu @nicksardo 

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kumudt** [comment]
I am facing this issue on Kubernetes 1.8.9 (After upgrading via Kops from 1.7.11). Is the fix available for 1.8.9?

**Comment by MrHohn** [comment]
@kumudt This should not longer be an issue for 1.7.2+ cluster. Are you observing the "bind: address already in use" error from kube-proxy logs? Could you confirm what component is occupying the same port?

**Comment by kumudt** [comment]
@MrHohn Yes. In the describe nodes, I can see an event with message Failed to start node healthz on 0.0.0.0:10256: listen tcp 0.0.0.0:10256: bind: address already in use.

K8s Version: v1.8.9
Installed with Kops 1.8.1 on AWS
OS Image: Debian GNU/Linux 9 (stretch)
Kernel Version: 4.9.0-6-amd64
Docker Run Time: docker://1.13.1

**Comment by MrHohn** [comment]
@kumudt Could you confirm what component is occupying port 10256? Have you tried `netstat -l` on the node?

**Comment by kumudt** [comment]
@MrHohn didn't find much in netstat -l
For port 10256, I could only see this.
tcp6       0      0 [::]:10256              [::]:*                  LISTEN

**Comment by kumudt** [comment]
This shows that 10256 is listening by kube-proxy
```
tcp6       0      0 :::10256                :::*                    LISTEN      30662/kube-proxy  
```
But, the node events and kube proxy logs shows the same error log.
There are lot of retries on the kube-proxy pod though. Maybe it is trying to collide with it's own process. This is happening on only one of the nodes in our cluster.

**Comment by MrHohn** [comment]
@kumudt  Sounds like you are having a different issue other than just port collision. It would be better to file a new bug (with sig-node?).

**Comment by disha94** [comment]
@MrHohn Facing a similar issue..
https://github.com/kubernetes/kubernetes/issues/61901

**Comment by arminmor** [comment]
I am facing the same issue here.

I have a cluster of 10 nodes, 1 master, 1 etcd. 

Services on 6 nodes (out of 10) can not "reach"/"be reached from" other containers. However, the other 4 nodes work perfectly and if I put pods (using nodeSelector) on them the can "reach"/"be reached from" other containers placed on the other nodes (4 nodes).

I checked the describe node, kube-proxy and calico logs for the 6 nodes:

describe node:
```
Events:
 Type Reason Age From Message
 ---- ------ ---- ---- -------
 Warning FailedToStartNodeHealthcheck 3m (x73391 over 50d) kube-proxy, sael0688 Failed to start node healthz on 0.0.0.0:10256: listen tcp 0.0.0.0:10256: bind: address already in use
```
 
kube-proxy:
 
```
1 server.go:483] starting metrics server failed: listen tcp 127.0.0.1:10249: bind: address already in use
1 proxier.go:1379] can't open "nodePort for ingress-nginx/ingress-nginx:http" (:30868/tcp), skipping this nodePort: listen tcp :30868: bind: address already in use
1 proxier.go:1379] can't open "nodePort for ingress-nginx/ingress-nginx:https" (:30344/tcp), skipping this nodePort: listen tcp :30344: bind: address already in use
1 healthcheck.go:317] Failed to start node healthz on 0.0.0.0:10256: listen tcp 0.0.0.0:10256: bind: address already in use
```
calico-node:
`[ERROR][101] health.go 193: Health endpoint failed, trying to restart it... error=listen tcp :9099: bind: address already in use`

Does anybody know what causes this issue and how I should resolve this?

**Comment by MrHohn** [comment]
> I am facing the same issue here.

@arminmor That is not the same issue. The issue reported here was specifically for the port collision between kube-proxy and node-problem-detector on port 10256, which was a configuration mistake.

What your encountered seems more like #61901 (opened by @disha94).

**Comment by arminmor** [comment]
> @arminmor That is not the same issue. The issue reported here was specifically for the port collision between kube-proxy and node-problem-detector on port 10256, which was a configuration mistake.
> 
> What your encountered seems more like #61901 (opened by @disha94).

@MrHohn thanks! I sent my comments (updated) in #61901.

**Comment by aabed** [comment]
I am suffering from the same problem
Kubernetes 1.10.3 on AWS using kops

**Comment by pablolibo** [comment]
the same problem, I am using EKS (Kubernetes 1.10.3) 👎
