### ISSUE TITLE
kubeadm jobs from 1.7 branch are failing

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#49272]
Both kubeadm jobs from 1.7 branch are failing now:
https://k8s-testgrid.appspot.com/release-1.7-blocking#gce-kubeadm-1.7
https://k8s-testgrid.appspot.com/release-1.7-blocking#gce-kubeadm-1.6-on-1.7

This is a result of broken PR submitted by @fejta in test-infra repo.

Those tests were supposed to be fixed by:
https://github.com/kubernetes/test-infra/pull/3589 by @krzyzacy but apparently that didn't help.

Both suites are still failing to start with:
```
W0719 16:48:44.441] flag provided but not defined: -gcp-project
W0719 16:48:44.441] Usage of kubetest:
```

@k8s-mirror-cluster-lifecycle-bugs @luxas @kubernetes/test-infra-maintainers

**Comment by wojtek-t** [comment]
I talked with @luxas offline and he said that "it shouldn't block the 1.7.2 release though".

**Comment by luxas** [comment]
> I talked with @luxas offline and he said that "it shouldn't block the 1.7.2 release though".

No, since the jobs have been green between the infra regressions, this is an infra-only problem.

I have no idea why, but https://github.com/kubernetes/test-infra/pull/3589 fixed "only" 4 of 6 kubeadm suites, these jobs are still failing with the same `flag provided but not defined: -gcp-project` error:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle#kubeadm-gce-1.7
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle#kubeadm-gce-1.6-on-1.7

May it be that jenkins hasn't reloaded those jobs correctly or...?

**Comment by wojtek-t** [comment]
> May it be that jenkins hasn't reloaded those jobs correctly or...?

Those are running on prow so Jenkins is no longer involved. I looked into current prow config in "k8s-prow" GCP project and the config looks as expected there.

I have no idea what is happening there...

**Comment by wojtek-t** [comment]
I think we missed the fact that they didn't run since the new config was deployed yesterday (because they are configured as postsubmit).

That said, I kicked them manually now and they are still failing, e.g.:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-1-7/80/

I have no idea why this doesn't really work...

**Comment by wojtek-t** [comment]
OK - I know what is going on - the rerun command actually contains the old image.
Will try to play with it...

**Comment by wojtek-t** [comment]
OK - it seems that I managed to successfully kick those jobs and now they seem to be doing something useful (i.e. we fixed the problem of bad image):
https://prow.k8s.io/log?job=ci-kubernetes-e2e-kubeadm-gce-1-6-on-1-7&id=73
https://prow.k8s.io/log?job=ci-kubernetes-e2e-kubeadm-gce-1-7&id=82

**Comment by wojtek-t** [comment]
So I hope that kubeadm jobs will get back to healthy soon-ish.

**Comment by wojtek-t** [comment]
The first one already succeeded:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-1-7/82/

I hope the second will succeed too soon.

**Comment by wojtek-t** [comment]
OK - both passed. Closing this issue.

**Comment by luxas** [comment]
@wojtek-t Thanks for restarting those jobs!
