### ISSUE TITLE
Pod hostname access from cluster - Help

### ISSUE THREAD

**Issue by dorsegal** [kubernetes/kubernetes#49270]
Hi,

Is there a way to access a pod by its hostname?
I have a pod with hostname **example-2190400937-qbc0f** that need to connect to another pod
**example-2190400937-fxbdn**

those two pods need to connect directly based on their hostname
what is the best way to achieve this with out services?

**Comment by feiskyer** [comment]
@dorsegal kubernetes doesn't support accessing pod's hostname by default, but you could create a headless service with same pod's name. 

> If there exists a headless service in the same namespace as the pod and with the same name as the subdomain, the cluster’s KubeDNS Server also returns an A record for the Pod’s fully qualified hostname. Given a Pod with the hostname set to “busybox-1” and the subdomain set to “default-subdomain”, and a headless Service named “default-subdomain” in the same namespace, the pod will see it’s own FQDN as “busybox-1.default-subdomain.my-namespace.svc.cluster.local”. DNS serves an A record at that name, pointing to the Pod’s IP. Both pods “busybox1” and “busybox2” can have their distinct A records.

Refer [here](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/).

**Comment by m1093782566** [comment]
+1

**Comment by dcbw** [comment]
Given this workaorund, can this issue be closed?

**Comment by dorsegal** [comment]
@dcbw Yes thank you!

**Comment by niuhp** [comment]
@dorsegal @k8s-merge-robot @dcbw Is this problem solved? I have the same problem，i want to deploy the eureka cluster,what is the best way

**Comment by thockin** [comment]
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

search for subdomain and hostname

**Comment by jdanekrh** [comment]
The important qualifier is the part

> If there exists a headless service in the same namespace as the pod and with the same name as the subdomain, [...]

I missed that on multiple scanning through the https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/ document.
