### ISSUE TITLE
Manual upgrade 1.5.1  to 1.6.7

### ISSUE THREAD

**Issue by kikiyou** [kubernetes/kubernetes#49288]
kube-apiserver mouch err log

E0720 10:06:54.197481       1 cacher.go:274] unexpected ListAndWatch error: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.go:215: Failed to list *certificates.CertificateSigningRequest: no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1alpha1"
E0720 10:06:55.202607       1 cacher.go:274] unexpected ListAndWatch error: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.go:215: Failed to list *certificates.CertificateSigningRequest: no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1alpha1"
E0720 10:06:56.205063       1 cacher.go:274] unexpected ListAndWatch error: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.go:215: Failed to list *certificates.CertificateSigningRequest: no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1alpha1"
E0720 10:06:57.207568       1 cacher.go:274] unexpected ListAndWatch error: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.go:215: Failed to list *certificates.CertificateSigningRequest: no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1alpha1"
E0720 10:06:58.213078       1 cacher.go:274] unexpected ListAndWatch error: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.go:215: Failed to list *certificates.CertificateSigningRequest: no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1alpha1"
E0720 10:06:59.215488       1 cacher.go:274] unexpected ListAndWatch error: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.go:215: Failed to list *certificates.CertificateSigningRequest: no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1alpha1"

**Comment by kikiyou** [comment]
area/apiserver
area/upgrade

**Comment by liggitt** [comment]
The v1alpha1 certificates.k8s.io API was removed in 1.6

Per the 1.6.0 release notes, if you were using the alpha API in 1.5, you must remove your existing objects prior to upgrading.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#certificates-api
