### ISSUE TITLE
Encryption configuration file: show a warning when the file is readable to all

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubernetes#49287]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
PR #46460 introduces a new configuration file that is specified by the `--experimental-encryption-provider-config` option to the api server and contains a sensitive data -- keys that are used for encrypting/decrypting data in the ectd.

At this moment, Kubernetes reads this file and doesn't do any extra check to ensure that the file has strong enough permissions.

**What you expected to happen**:
Kubernetes should at least **issue a warning when this file is readable or writable to any user**. If we want to treat this situation even more serious, we can abort startup process of the API server.

CC @sakshamsharma @smarterclayton

**Comment by ericchiang** [comment]
/assign

Do we want to only do this for the encryption config file or all sensitive files? I know the CIS benchmarks specifically mention file permissions for several flags.

**Comment by php-coder** [comment]
/reopen
/remove-lifecycle rotten

CC @simo5

**Comment by php-coder** [comment]
> Kubernetes should at least issue a warning when this file is readable or writable to any user. If we want to treat this situation even more serious, we can abort startup process of the API server.

It's better to fail in order to prevent insecure configurations but it will be breaking change. Perhaps, it can be announced with "action-required".

> Do we want to only do this for the encryption config file or all sensitive files?

@ericchiang I'd like to see it for all sensitive files but this issue is about only one of them, that I'm aware of.

**Comment by php-coder** [comment]
@stlaz JFYI
