### ISSUE TITLE
Encryption configuration file: don't try to read the file fully

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubernetes#49290]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature
/sig auth

**What happened**:
PR #46460 introduces a new configuration file that is specified by the `--experimental-encryption-provider-config` option to the api server.

At the current implementation, [`ParseEncryptionConfiguration` uses `ioutil.ReadAll()` to load this file](https://github.com/kubernetes/kubernetes/blob/2853f46b02c863274477b0924923fe2ad3798614/staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig/config.go#L60) into the memory.

**What you expected to happen**:
Consider using [`http.MaxBytesReader`](https://golang.org/pkg/net/http/#MaxBytesReader) or [`io.LimitReader`](https://golang.org/pkg/io/#LimitReader) to limit the max number of bytes that can be read from a file. This can prevent the situation when api server is eating too much memory or even crashing if the config file is huge.

CC @sakshamsharma @smarterclayton

**Comment by sakshamsharma** [comment]
How big of a file should we allow? How about 10 KB?

**Comment by php-coder** [comment]
How about 100Kb? The size doesn't matter because it's trivial to change it.

**Comment by odeke-em** [comment]
Could we also decide if we need to make this value configurable by some sort of flag passed in when to the api server?
 How bad is the problem? What is the typical file size?
I am new to the k8 community so please pardon my noobish concerns, but I think that arbitrarily using any value, without surveying for common file sizes might cause more problems.

**Comment by sakshamsharma** [comment]
The configuration file should not exceed a few hundred bytes in any practical use-case I can imagine.

**Comment by liggitt** [comment]
> The configuration file should not exceed a few hundred bytes in any practical use-case I can imagine.

Agree. If a malicious user has control over this file, you have much bigger problems than the file size.
