### ISSUE TITLE
Extend cloudprovider Zones API to support out-of-tree CCMs

### ISSUE THREAD

**Issue by prydie** [kubernetes/kubernetes#49308]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I'm currently part of a team working on implementing an out-of-tree cloud controller manager (CCM) for [Oracle Bare Metal Cloud][4].

For in-tree cloud-providers the [`cloudprovider.GetZone()`][1] method is [called from `kubelet`][2]. This allows in-tree cloud providers to implement [`GetZone()`][1] by querying local metadata services (as `kubelet` is of course running on the node itself).

For out-of-tree cloud-providers [`GetZone()`][1] is called in [`AddCloudNode()`][3] in the context of the cloud-controller-manager binary. Thus, local metadata services return the failure zone and region for the node on which the CCM is running rather than the node itself.

**What you expected to happen**:

Out-of-tree cloud providers should have access to the same functionality as in-tree cloud-providers.

I propose extending the [`cloudprovider.Zones()`][5] interface to include a `GetZoneByProviderID(providerId string)` method and utilising this method in [`AddCloudNode()`][3].

Alternatively (or additionally) the signature of [`GetZone()`][1] could be modified to take a `types.NodeName` parameter and the existing cloud-providers updated. This would be consistent with the other interfaces in the `cloudprovider` package.

**How to reproduce it (as minimally and precisely as possible)**:

 - Deploy an out-of-tree cloud controller manager as a daemon set running on the master nodes.
 - Add node to cluster in a different failure zone to the node on which the leader CCM is running.
 - Note that the node is labeled as being in the failure zone and region of the node the CCM is running on.

**Anything else we need to know?**:

I am very happy to implement this as an initial contribution to k8s if there is consensus on the issue.

**Environment**:
- Kubernetes version (use `kubectl version`):
   ```
   Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T02:00:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
   Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
   ```
- Cloud provider or hardware configuration: [Oracle Bare Metal Cloud][4]
- OS (e.g. from /etc/os-release):  Oracle Linux 7.3
- Kernel (e.g. `uname -a`): `4.1.12-94.3.6.el7uek.x86_64 x86_64 GNU/Linux`
- Install tools: `kubeadm`

/cc @luxas @thockin @wlan0 @rrati @roberthbailey @tjfontaine

[1]: https://github.com/kubernetes/kubernetes/blob/5529d01a22299728c59e7e3db92ccbf908ebae4f/pkg/cloudprovider/cloud.go#L185
[2]: https://github.com/kubernetes/kubernetes/blob/c35bf2aa7b476c2523687b923f9e485df333f1d2/pkg/kubelet/kubelet_node_status.go#L310
[3]: https://github.com/kubernetes/kubernetes/blob/c35bf2aa7b476c2523687b923f9e485df333f1d2/pkg/controller/cloud/nodecontroller.go#L267
[4]: https://cloud.oracle.com/en_US/bare-metal
[5]: https://github.com/kubernetes/kubernetes/blob/c35bf2aa7b476c2523687b923f9e485df333f1d2/pkg/cloudprovider/cloud.go#L183

**Comment by prydie** [comment]
@kubernetes/sig-cluster-lifecycle-proposals

**Comment by wlan0** [comment]
@pyrdie Thanks for filing the issue. This is definitely required.

I am in favor of creating the new method -`GetZoneByProviderID(providerID string)` 

If we update the existing `GetZone()` to take in NodeName as a parameter, then it'll break the contract for all the existing in-tree and out-of-tree cloudproviders when they rebase to a newer kubernetes revision.

I'd be happy to look at a PR if you make one. Thanks again!

**Comment by prydie** [comment]
@wlan0 Great! The `GetZoneByProviderID(providerId string)` solution seemed the obvious one to me also.

I'll put a PR together early next week presuming the other relavent parties are happy with that solution.

**Comment by jhorwit2** [comment]
It doesn't fit the style of the other functions, but should we also add 

`GetZoneByNodeName(name type.NodeName) (cloudprovider.Zone, error)`

as well as 

`GetZoneByProviderID(providerId string) (cloudprovider.Zone, error)`

so we keep support for both like we do other methods while keeping backwards compatibility on `GetZone()`.

**Comment by luxas** [comment]
@jhorwit2 Feel free to implement something like that and we'll see :)

**Comment by jhorwit2** [comment]
:) 

@luxas i'll let you know soon if I can.

**Comment by andrewsykim** [comment]
FYI after speaking with some people on slack, I've started work on this issue. Please let me know if there are design changes I should consider.

**Comment by jhorwit2** [comment]
Thanks @andrewsykim!
