### ISSUE TITLE
REST api - missing an example how to filter based on labels

### ISSUE THREAD

**Issue by abonas** [kubernetes/kubernetes#4931]
There's an option to filter a GET request with labels, but there's no example on how to do it, especially
when need to filter based on more than one label.
So for instance, this works for filtering based on one label:
http://localhost:8080/api/v1beta3/services?labels=component=apiserver

but what is the right syntax to filter based on 2 labels?

**Comment by bgrant0607** [comment]
Look at the bottom of:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/labels.md

Please let me know if it doesn't work.

**Comment by abonas** [comment]
@bgrant0607 yes it works, for example:
http://localhost:8080/api/v1beta3/services?labels=component=apiserver,provider=kubernetes

my question is - does it do an AND between the labels? so the entities returned must have both labels in order to be returned? (this is how it looks it's currently working now, but is it the expected behavior?)

**Comment by bgrant0607** [comment]
Yes, they are ANDed together, just like the selectors in the API.

@sdminonne Please clarify this when you update labels.md.
