### ISSUE TITLE
kubernetes service exposing shellinabox timeout after approx. 60 seconds

### ISSUE THREAD

**Issue by Rev1408** [kubernetes/kubernetes#49329]
I have kubernetes installed on bare metal ubuntu server, below is the output of kubectl version command

> Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:38:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

I am running google shellinabox inside a docker container. It all works well with the docker container, but when I put the same image inside a kubernetes pod and expose it with a kubernetes service, my browser session to shellinabox times out after ~60 secs. Since this works fine with standalone docker container, I think this is caused by kubernetes. Is there any timeout on the kubernetes and how do I configure that.

Any help?

**Comment by xiangpengzhao** [comment]
/sig network

Could you please provide more info about your service and pods, for debugging?

**Comment by thockin** [comment]
how are you accessing the service?

**Comment by Rev1408** [comment]
I got this fixed by adding sessionAffinity: ClientIP to service
