### ISSUE TITLE
Clean up deprecated DaemonSet templateGeneration field

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#49336]
We already announced deprecation of `.spec.templateGeneration` of extensions/v1beta1 DaemonSet in 1.7. 

Moving forward in 1.8, we'll need to:
* Add an `deprecated.daemonset.template.generation=<generation>` annotation (tentative name) to support conversion between extensions/v1beta1 DaemonSet and apps/v1beta2 DaemonSet. 
* Keep existing `templateGeneration` behavior for backward compatibility. 

@kubernetes/sig-apps-misc

**Comment by dhilipkumars** [comment]
@janetkuo is anyone already working on this issue? I would love to pick this up.

**Comment by dixudx** [comment]
@dhilipkumars I created a PR #49454. You can add your comments there.

**Comment by dhilipkumars** [comment]
@dixudx could you assign this to yourself in this case please?

**Comment by dixudx** [comment]
@dhilipkumars I am not a member. Only kubernetes members can be assigned.
