### ISSUE TITLE
Kubeadm preflight checks cannot be skipped while using --config

### ISSUE THREAD

**Issue by goten4** [kubernetes/kubernetes#49360]
/sig cluster-lifecycle

**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Since 1.7.1, you cannot add extra parameters when you use --config, but some parameters (like --skip-preflight-checks) aren't implemented in the config file.

**What you expected to happen**:
Add skipPreflightChecks in the config syntax or allow the combination of --config and --skip-preflight-checks parameters.

**How to reproduce it (as minimally and precisely as possible)**:
Install kubeadm 1.7.1, and run :
`$ kubeadm init --skip-preflight-checks --config kubeadm.yaml`

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.1
- Cloud provider or hardware configuration**: any
- OS (e.g. from /etc/os-release): Debian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`): Linux 4.9.20-std-1
- Install tools: kubeadm
- Others:

**Comment by xiangpengzhao** [comment]
And please re-open this in https://github.com/kubernetes/kubeadm

**Comment by goten4** [comment]
So sorry, I missed the separate repo for kubeadm, and the issue was already created there (https://github.com/kubernetes/kubeadm/issues/352) !
