### ISSUE TITLE
Move some Go types from core/v1 to meta/v1 package

### ISSUE THREAD

**Issue by ash2k** [kubernetes/kubernetes#49372]
I'd like to suggest to move certain Go types from core/v1 to meta/v1. Here is the list:
- ResourceName
- ConditionStatus
- Protocol
- ObjectReference
- LocalObjectReference
- SerializedReference
- EnvVar
- EnvFromSource

Motivation: they are not top level api objects like e.g. `Deployment` or `Service` and are used in other non-core k8.io/api packages. They are more like `TypeMeta` and `ObjectMeta`.
By moving them to meta/v1 coupling between api type packages will be reduced. Also think about external users who want to reuse structs like `EnvVar` and don't want/need to depend on anything else core/v1.
I think about it that way: if core/v1 is deprecated and finally removed (thought experiment!), which Go structs/types that are not API types makes sense to keep?

Also 1.8 will break code that depends on api types because of move to k8.io/api. So maybe its a good opportunity to do move reshuffling?

There are probably more types that could be moved and/or not all of the ones I listed above should be moved. I just quickly compiled this list to get some feedback on the idea, didn't do deep analysis.

/kind cleanup
/sig api-machinery

@deads2k @caesarxuchao

**Comment by deads2k** [comment]
metav1 contains types that are critical to the type system, not generally useful types.


1. ResourceName - related to quota, this belongs in v1
2. ConditionStatus - related to particular items.  I think we should suggest, but I don't think we should be prescriptive.  I wouldn't move this or conditions generally.
3. Protocol - in service of services and endpoints.  This belongs in v1.
4. ObjectReference - this type was mistake, it's not correct for most use-cases and in other API areas we've chosen to make specific reference types with more correct information to better effect.  I'm not strictly against this notion, but I'm definitely against moving this implementation.
5. LocalObjectReference - this type isn't complete.  It's not wrong, but we found it wasn't prescriptive enough for most API.
6. SerializedReference - I don't even remember using this anywhere.
7. EnvVar - not related to the type system.
8. EnvFromSource - not related to the type system.


@kubernetes/sig-api-machinery-misc
