### ISSUE TITLE
Broken/flaky e2e tests for ha masters

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#49375]
Recently e2e tests for HA master become broken/flaky. Please see:
https://k8s-testgrid.appspot.com/google-gce#gce-ha-master

**Comment by wojtek-t** [comment]
Should be fixed by https://github.com/kubernetes/kubernetes/pull/49486

**Comment by wojtek-t** [comment]
Fixed now: https://k8s-testgrid.appspot.com/google-gce#gce-ha-master
