### ISSUE TITLE
Update to etcd 3.1.X 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#49386]
For the 1.8 cycle we should incremental update to etcd 3.1.X to pickup known fixes along with fixing some other problems that we're uncovered during 1.7 (https://github.com/coreos/etcd/pull/8199) 

/cc @kubernetes/sig-cluster-lifecycle-misc @kubernetes/sig-scalability-misc @kubernetes/sig-api-machinery-misc

**Comment by liggitt** [comment]
@smarterclayton were you expecting 3.1.x or 3.2.x?

**Comment by timothysc** [comment]
@liggitt upgrade docs explicitly state minor version upgrades are recommended, and compatible.  I would not want to jump to 3.2 unless @xiang90 and @hongchaodeng have vetted a 3.0.17 -> 3.2.x upgrade.

**Comment by hongchaodeng** [comment]
Will update to 3.1.10 first

**Comment by hongchaodeng** [comment]
We also need someone from Google (I assume who have access) to push image to:
```
gcr.io/google_containers/etcd:3.1.10
```

**Comment by luxas** [comment]
@wojtek-t ^
