### ISSUE TITLE
Missing unit tests in /pkg/api/v1helper & pkg/util/taints for some functions.

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#49384]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature

**What happened**:
While working on #46514, I noticed that some fn's like AddorUpdateTaints, DeleteTaintsByKey etc. are missing unit tests.

**What you expected to happen**:
Write unit tests for them.

**Comment by xingzhou** [comment]
yeap, @ravisantoshgudimetla, if you are not working on this, I can provide a patch on this

**Comment by ravisantoshgudimetla** [comment]
Sure @xingzhou, please go ahead. 
cc @vikaschoudhary16.

**Comment by adshmh** [comment]
@ravisantoshgudimetla  I see a few more functions missing unit tests under /pkg/api/v1/helper. If no one is working on this, I can add unit tests for those.

**Comment by drinktee** [comment]
I'm adding some unit test for v1/helper.  @adshmh  Have  you already done?
