### ISSUE TITLE
Kube-controller-manager crashes when creating svc loadbalancer with Azure

### ISSUE THREAD

**Issue by githubvick** [kubernetes/kubernetes#49389]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
Kube controller manager crashes when creating svc type LoadBalancer

**What you expected to happen**:

Load balancer should be created automatically and properly

**How to reproduce it (as minimally and precisely as possible)**:

Add cloud prov parameter in kubeapiserver
KUBE_API_ARGS="--tls-cert-file=/etc/kubernetes/certs/server.crt --tls-private-key-file=/etc/kubernetes/certs/server.key --client-ca-file=/etc/kubernetes/certs/ca.crt --token-auth-file=/etc/kubernetes/tokens/known_tokens.csv --service-account-key-file=/etc/kubernetes/certs/server.crt --bind-address=0.0.0.0 --apiserver-count=1 --cloud-provider=azure --cloud-config=/etc/azure/azure.conf"
Add parameter in controller manager

KUBE_CONTROLLER_MANAGER_ARGS="--kubeconfig=/etc/kubernetes/controller-manager.kubeconfig --service-account-private-key-file=/etc/kubernetes/certs/server.key --root-ca-file=/etc/kubernetes/certs/ca.crt --cloud-provider=azure --cloud-config=/etc/azure/azure.conf"

Also added the cloud provider config to kubelet to check if that was the issue..

**Anything else we need to know?**:
Kubernetes was installed through Ansible contrib. 
Followed this tutorial to create the load balancerhttps://kubernetes.io/docs/tasks/access-application-cluster/load-balance-access-application-cluster/

**Environment**:
- Kubernetes version (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"269f928217957e7126dc87e6adfa82242bfe5b1e", GitTreeState:"clean", BuildDate:"2017-07-03T15:31:10Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"269f928217957e7126dc87e6adfa82242bfe5b1e", GitTreeState:"clean", BuildDate:"2017-07-03T15:31:10Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**:Azure
- OS (e.g. from /etc/os-release): NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
- Kernel (e.g. `uname -a`): Linux hostname 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
Azure.conf has these values
tenantId:
subscriptionId:
aadClientId:
aadClientSecret:
aadTenantId:
resourceGroup: myservices
location: eastus

/sig azure

[log.txt](https://github.com/kubernetes/kubernetes/files/1166002/log.txt)

**Comment by githubvick** [comment]
Hi, could some one suggest some workaround for this if possible. I'm trying to get the architecture signed off and the load balancer is the last part.

Does it work on version 1.7? Again I've tried to upgrade, but it seems like the packages are not updated on Cent OS repo and I'm stuck on that front as well. https://bugs.centos.org/view.php?id=13608

**Comment by githubvick** [comment]
Just found out the properties to set from here.

https://github.com/kubernetes/kubernetes/blob/a47614dd1502e84617dfdea7fd1c39d467bb3b97/pkg/cloudprovider/providers/azure/azure.go#L36

Now I'm getting the same error as that as in here https://github.com/Azure/acs-engine/issues/194

Is there a workaround/fix for this in 1.5.2? I'm using centos and there are no rpm>1.5.2 to upgrade for kubernetes,kubernetes-master and so I'm stuck on using this.

**Comment by githubvick** [comment]
Somehow after manually installing version 1.6 and bringing up the cluster on Centos, gives this error now.

`balancer for service default/example-service: [ensure(default/example-service): lb(kubernetes) - failed to ensure host in pool: "compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/virtualMachines/52.170.33.243' under resource group 'myservices' was not found.\"", ensure(default/example-service): lb(kubernetes) - failed to ensure host in pool: "compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/virtualMachines/52.170.35.161' under resource group 'myservices' was not found.\"", ensure(default/example-service): lb(kubernetes) - failed to ensure host in pool: "compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/virtualMachines/52.170.34.196' under resource group 'myservices' was not found.\""]
`
But all the virtual machines are under the resource group myservices.

Could someone please provide some suggestions and help?

**Comment by gatneil** [comment]
Not sure what the underlying reason is, but the error you're getting is happening on a GET request on the virtual machine. The "Microsoft.Compute/virtualMachines/52.170.33.243" part looks suspicious: the last part of this should be the virtual machine name (the one you see when you look at the VM in the Azure Portal), not its IP address (unless you or the code named the VM with an IP address?). I'm not particularly familiar with kub or ansible, but my guess would be that something is trying to refer to the VM via IP address when the Azure API is expecting a VM name. Sorry for the semi-response; hope this helps a bit!

**Comment by githubvick** [comment]
@gatneil thx for your response and pointers.

The vm name is actually k8s-0, k8s-1 and so on, I am actually provisioning the VM through terraform, but I dont see any visible difference in the Azure console between the VM's created manually and through Terraform. Let me try to reproduce the issue with VM's created manually.

**Comment by githubvick** [comment]
@gatneil Same error, this time with the hostname :(

```
Aug 09 19:48:41 kubemaster kube-controller-manager[4164]: E0809 19:48:41.170321    4164 servicecontroller.go:753] Failed to process service. Retrying in 5s: Failed to create load balancer for service default/example-service: network.SecurityGroupsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Network/networkSecurityGroups/k8scluster' under resource group 'MstCsaPoc' was not found."
Aug 09 19:48:43 kubemaster sudo[4651]: testadmin : TTY=pts/0 ; PWD=/home/testadmin ; USER=root ; COMMAND=/bin/journalctl -xe
Aug 09 19:48:45 kubemaster kube-addons.sh[29031]: Error from server (AlreadyExists): error when creating "/etc/kubernetes/addons/kube-dash/kube-dash-svc.yaml": services "kubernetes-dashboard" already exists
Aug 09 19:48:45 kubemaster kube-addons.sh[29031]: INFO: == Failed to execute /usr/bin/kubectl create --namespace=kube-system -f /etc/kubernetes/addons/kube-dash/kube-dash-svc.yaml at 2017-08-09T19:48:45+0000. 21 tries remaining. ==
Aug 09 19:48:46 kubemaster kube-controller-manager[4164]: E0809 19:48:46.222197    4164 servicecontroller.go:753] Failed to process service. Retrying in 10s: Failed to create load balancer for service default/example-service: network.SecurityGroupsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Network/networkSecurityGroups/k8scluster' under resource group 'MstCsaPoc' was not found."
Aug 09 19:48:55 kubemaster kube-addons.sh[29031]: Error from server (AlreadyExists): error when creating "/etc/kubernetes/addons/kube-dash/kube-dash-svc.yaml": services "kubernetes-dashboard" already exists
Aug 09 19:48:55 kubemaster kube-addons.sh[29031]: INFO: == Failed to execute /usr/bin/kubectl create --namespace=kube-system -f /etc/kubernetes/addons/kube-dash/kube-dash-svc.yaml at 2017-08-09T19:48:55+0000. 20 tries remaining. ==
Aug 09 19:48:56 kubemaster kube-controller-manager[4164]: E0809 19:48:56.290997    4164 servicecontroller.go:753] Failed to process service. Retrying in 20s: Failed to create load balancer for service default/example-service: network.SecurityGroupsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Network/networkSecurityGroups/k8scluster' under resource group 'MstCsaPoc' was not found."
Aug 09 19:49:01 kubemaster sudo[4670]: testadmin : TTY=pts/0 ; PWD=/home/testadmin ; USER=root ; COMMAND=/bin/journalctl -xe

```

**Comment by githubvick** [comment]
@gatneil Same error :( when creating the VM's manually as well. 52.170.83.40 is the node ip.

```
Failed to create load balancer for service default/example-service: ensure(default/example-service): lb(kubernetes) - failed to ensure host in pool: "compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/virtualMachines/52.170.83.40' under resource group 'MstCsaPoc' was not found.\""
Aug 09 19:53:08 kubemaster kube-controller-manager[4950]: E0809 19:53:08.372773    4950 servicecontroller.go:753] Failed to process service. Retrying in 10s: Failed to create load balancer for service default/example-service: ensure(default/example-service): lb(kubernetes) - failed to ensure host in pool: "compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/virtualMachines/52.170.83.40' under resource group 'MstCsaPoc' was not found.\""
Aug 09 19:53:18 kubemaster kube-controller-manager[4950]: E0809 19:53:18.494789    4950 servicecontroller.go:753] Failed to process service. Retrying in 20s: Failed to create load balancer for service default/example-service: ensure(default/example-service): lb(kubernetes) - failed to ensure host in pool: "compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/virtualMachines/52.170.83.40' under resource group 'MstCsaPoc' was not found.\""
Aug 09 19:53:38 kubemaster kube-controller-manager[4950]: E0809 19:53:38.628265    4950 servicecontroller.go:753] Failed to process service. Retrying in 40s: Failed to create load balancer for service default/example-service: ensure(default/example-service): lb(kubernetes) - failed to ensure host in pool: "compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/virtualMachines/52.170.83.40' under resource group 'MstCsaPoc' was not found.\""

```

**Comment by colemickens** [comment]
@gatneil is correct. If the cloudprovider can't lookup the VM instance, then it can't find the NIC to put it in the backend pool.

It seems like your node name is being reported as the IP. I'm going to venture a guess that the bringup you're using copied the AWS implementation that overrides the reported hostname to be the node IP. If you undo that, you should get the right hostname reported, the right VM name in the NIC lookup, and you should get past this problem... if my assumption is correct.

Please link to the `kubelet` config in the bringup you're using and I can confirm this suspicion.

**Comment by colemickens** [comment]
/sig azure

cc: @jdumars @brendanburns mostly as FYI as this is likely a configuration issue.

**Comment by githubvick** [comment]
I'm actually using the ansible code from https://github.com/kubernetes/contrib/tree/master/ansible with minor modifications to suit Azure,I understood your point, will check it out and let you know.

**Comment by githubvick** [comment]
Nope, changed it to reflect the dns name of the instance. didn't work still

`Aug 10 20:04:32 k8s0 kube-controller-manager[31980]: E0810 20:04:32.621142   31980 servicecontroller.go:753] Failed to process service. Retrying in 5s: Failed to create load balancer for service default/example-service: [ensure(default/example-service): lb(kubernetes) - failed to ensure host in pool: "compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/virtualMachines/k8s1.eastus.cloudapp.azure.com' under resource group 'myservices' was not found.\"", ensure(default/example-service): lb(kubernetes) - failed to ensure host in pool: "compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/virtualMachines/k8s2.eastus.cloudapp.azure.com' under resource group 'myservices' was not found.\""]
`

**Comment by colemickens** [comment]
Because it's still clearly not correct. You need to put the VM name (which in Azure is the hostname). Not the FQDN.

As you can see in the error message, `Microsoft.Compute/virtualMachines/k8s2.eastus.cloudapp.azure.com` is not a valid Azure resource identifier.

It's probably `Microsoft.Compute/virtualMachines/k8s2`.

Also, if you could please file a corresponding bug against `contrib` so that this can be fixed for anyone using the Ansible playbook with Azure, it would be great. Thanks.

**Comment by githubvick** [comment]
Yes, finally able to get through the error and onto the next hurdle. It has something to do with availability sets. I'm starting to research a bit more about them.

```
Failed to process service. Retrying in 20s: Failed to create load balancer for service default/example-service: ensure(default/example-service): lb(kubernetes) - failed to ensure host in pool: "network.InterfacesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"NetworkInterfaceAndLoadBalancerAreInDifferentAvailabilitySets\" Message=\"Network interface /subscriptions/82ec80ce-376f-469f-adef-f2f9ad788277/resourceGroups/myservices/providers/Microsoft.Network/networkInterfaces/mysvcsni2 uses load balancer /subscriptions/82ec80ce-376f-469f-adef-f2f9ad788277/resourceGroups/myservices/providers/Microsoft.Network/loadBalancers/kubernetes associated with different availability set (/subscriptions/82ec80ce-376f-469f-adef-f2f9ad788277/resourceGroups/myservices/providers/Microsoft.Compute/virtualMachines/k8s-1) than availability set of the NIC (/subscriptions/82ec80ce-376f-469f-adef-f2f9ad788277/resourceGroups/myservices/providers/Microsoft.Compute/virtualMachines/k8s-2).\" Details=[]"
Aug 14 15:08:00 k8s0 kube-addons.sh[29674]: Error from server (AlreadyExists): error when creating "STDIN": secrets "token-system-kubectl-k8srandom0.eastus.cloudapp.azure.com" already exists

```

**Comment by githubvick** [comment]
Finally got it working.... big thanks to @colemickens
