### ISSUE TITLE
Support testing the latest image in an image family in node e2e benchmarks

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/kubernetes#49397]
The benchmark tests in node e2e are defined in https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/jenkins/benchmark/benchmark-config.yaml. We currently need to list the image name (or regex) in each test. I'd like to add a new field `image-family` so that the test will always run against the latest image in that family. (This will be more clear than using a regex.) It will avoid changes like https://github.com/kubernetes/kubernetes/pull/49396.

/sig node
/area node-e2e
/assign

**Comment by rithujohn191** [comment]
@yguo0905 was this issue closed on purpose? It would be very valuable to add support for testing using `--image-family` in node e2e tests
