### ISSUE TITLE
Plan to implement Windows Server Container Stats  

### ISSUE THREAD

**Issue by bobbypage** [kubernetes/kubernetes#49398]
This is a proposal to support stats inside the kubelet for Windows Server containers.  
   
**Summary**  
Stats are missing from Windows Server containers, despite the fact that stats are important to enable monitoring of Windows Server containers (via ingestion into components such as Heapster) as well as enabling auto scaling features that rely on metrics to function properly. 
   
**Rational and Paint Points**  
Currently, the /stats/summary api will consistently crash the kubelet on Windows server containers. Usually, stats are populated from CAdvisor, which reads them directly from cgroups on Linux.    
  
For Windows, CAdvisor is not supported and there are no plans to support it on Windows in the future https://github.com/google/cadvisor/issues/1394). The community has also been investigating pushing stats into the CRI and defining a set of “minimum required container metrics” in order to decouple Kubelet’s reliance on CAdvisor. Some of the discussion about the CRI stats can be found here:  
   
A better story of container metrics for runtime integration (https://github.com/kubernetes/kubernetes/issues/27097)  
CRI: instruct kubelet to (optionally) consume container stats from CRI (https://github.com/kubernetes/kubernetes/issues/46984)  
CRI: support non-builtin container runtimes (https://github.com/kubernetes/kubernetes/issues/47872)  
   
Currently, the CRI stats have not been implemented fully. The kubelet does not read stats from CRI and the CRI stats providers are not implemented as well, it's still a work in progress by the community.   
   
**Plan**   
Due to the fact that the CRI stats work is still under development, the plan is to first add support for windows stats via a CAdvisor via windows-shim as a short term solution, and later reuse this work by refactoring the code to use CRI stats interfaces when they will be ready.   
   
Currently, in the kubelet, CAdvisor is abstracted away via small shim (cadvisor_linux.go and cadvisor_win.go in pkg/kubelet/cadvisor). On Linux, the CAdvisor shim usually redirects calls to the underlying CAdvisor library directly, but on Windows the shim returns empty CAdvisor data structures. The proposal is to fill these data structures with the correct metrics on the Windows side using a combination of native windows perf monitoring subsystem (PerfCounters to get node stats) and calling out to the docker engine REST API to get container stats.

**Comment by yujuhong** [comment]
/sig node

See my reply in https://github.com/kubernetes/kubernetes/pull/50396#issuecomment-322858759
