### ISSUE TITLE
Connecting containers 

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#494]
I wanted to lay out the general problem of interconnecting containers in terms of use cases and requirements and map out some of the solutions that matter at different scales, to help start a discussion about what additional constructs would be useful in Kubernetes.

#### Problem statement:

1. A container may depend on one or more remote network services, available over standard IPv4/6 networking
2. The address of the remote network service can changed at any time - but it is desirable to not require a restart of the container or containers that depend on that remote service.
3. It should be possible to make the connection between the container and the remote network service secure without changing the container (introduce a TLS tunnel or VPN)
4. Software inside a container must be able to identify the network address / destination of a specific remote service and distinguish between multiples
5. Stateless remote services should be able to be transparently load balanced (from the containers perspective) without the software inside the container having to change
6. Some client software, talking to a remote network service, is more reliable when some or all of the remote service endpoints are directly available (a MongoDB client can tolerate the loss of one of the cluster instances if all of the instance IPs are available)
7. In general solutions which favor the broadest possible sets of software (including software that is not specifically written with the solution in mind) are preferred
8. Where possible, performance of network traffic should be on par with direct connections

#### Ways of identifying the address of a remote service to software in a container:

1.  Environment variables
    * Client code has a convention to look up certain environment variables passed to it
      * Examples: Docker links v1, most PaaS, 12-factor apps
    * Advantages
      * common pattern
    * Disadvantages
      * client code has to be written to use the specific name
      * no one uses the same names, not all names make sense for all use cases
        * Reqt: Allow redefining names
      * have to restart the process to pick up a new environment value

2.  Dynamic Config file
    * Client code reads configuration file generated by host infrastructure from a template
      * Examples: confd, OpenShift templatizing conf with erb
    * Advantages
      * works well for most common services
    * Disadvantages
      * someone needs to write the template
      * have to define a template format everyone can/will use, or support multiple (good luck...)
      * requires specific client code to reload file, otherwise process restart

3. Static cluster description file
    * File describing relationship destinations generated by host infrastructure into container
    * Advantages
      * can be more complex than environment variables
    * Disadvantages
      * client code has to read the file and use it
      * have to define a cluster format everyone can/will use (good luck...)
      * requires specific client code to reload file, otherwise process restart

4. Read from remote service discovery service
    * Client code runs and connects to a remote service, reads values
      * Examples: Zookeeper/etcd
    * Advantages
      * client code can react to changes
    * Disadvantages
      * client code may need a library, has to be written to load that value, react to changes, and remaining code still has to react
      * harder than environment variables
      * how does the client code know where the remote service is? (recursive)
      * how is the connection between the client code and the remote service secured?
      * can the infrastructure for the service discovery be shared efficiently?

5. Read from local service discovery service
    * Client code runs and connects to a local service, reads values, updates anytime something changes
      * Examples: Zookeeper/etcd with local cache, Docker links v2 (ish)
    * Advantages
      * can perform more complicated lookups
      * arbitrarily low latency on changes, as long as code is written to pull that
      * client code can depend on a file descriptor passed to the process or a convention
    * Disadvantages
      * client code may need a library, has to be written to load that value, react to changes, and remaining code still has to react
      * requires distribution of destination mappings to many systems (all outbound links to each container on a host)

6. Run local service discovery client in the container
    * The top process in the container is a process monitor / manager, which connects to a remote endpoint and provides information
      * Examples: fabric8 Java Docker containers (each container is itself a host for smaller services in the JVM)
      * Note that this is no different than any other container that exposes no metadata to the infrastructure, so it's supportable and supported.
    * Advantages
      * Is opaque to the calling infrastructure, and can connect to other service discovery mechanisms
    * Disadvantages
      * hides details about the container processes from the infrastructure
      * depends on a specific service discovery infrastructure, so the container code is coupled to an infrastructure.

#### Ways of allowing the address of a remote service to change over time

1. DNS
    * Requires cluster membership changes be propagated to a DNS server efficiently
      * SkyDNS
    * Advantages
      * allows client software to easily get the address
      * allows multiple remote IP addresses to be returned
        * Caveat: only some client libraries properly try multiple IP addresses, and most browsers do not (in a way that is useful to end users)
    * Disadvantages
      * latency for DNS propagation can be high (can be solved via clients)
      * most client libraries and code caches DNS entries for the entire life of the process, requires restart
      * client code still needs to hardcode the address, or get it from an environment

2. Remote Proxy
    * Create a highly available proxy remotely that proxies ports to backends
    * Advantages
      * client software can rely on the proxy not moving
    * Disadvantages
      * all traffic routed through proxy may saturate proxy
      * proxy has to be HA, implement ip-address failover / heartbeating
      * adds latency to every network connection
      * malicious containers can attack proxy

3. Local Proxy
    * Have an outbound proxy on each host that connects to remote hosts
    * Advantages
      * client software can rely on the proxy not moving
      * can implement outbound security rules to other locations
      * proxy is implicitly highly available and load balancing is local
    * Disadvantages
      * adds (small) latency to every network connection
      * requires distribution of destination mappings to many systems (all outbound links to each container on a host)

4. iptables/tc Local Proxy
    * iptables, tc, or hardware routing defined to perform destination network-address-translation (DNAT) from local addresses to remote ones
      * Examples: geard, CoreOS jumpering
      * 127.0.0.1:3306 inside container maps to remote host 9.34.8.3:34856, running a hosted MySQL service
    * Advantages
      * can remap ports to match default development conventions (high port on proxy to common port internally)
      * can make container environment look identical across vastly different systems
      * can be changed on the fly without restart, without software changes
      * less latency than a local proxy for 1-1 connections
      * like SDN but cheaper
    * Disadvantages
      * iptables DNAT is slower than direct network access - although tc can get very close
      * requires distribution of destination mappings to many systems (all outbound links to each container on a host)

5. Read from remote service discovery service
    * As above

6. Read from local service discovery service
    * As above

#### Docker links (current and future)

Docker linking currently injects environment variables of a known form into a container, representing links defined on the host.  The next iteration of Docker links will most likely implement local service discovery (a discovery endpoint injected into a container) via the definenvironition of links on the host, with the existence of a proxy on that host connecting to outbound servers.  It will also likely support adapters for exposing environment variables, dynamic config files, or a static cluster file.

#### Observations:

1. The remote connections of a service do not change EXCEPT:
  * ... when the destination is a stateless scalable service (suitable for load balancing)
  * ... when creating or changing topology (itself rare)
  * ... when a failure occurs on a non-resilient network service and a new component replaces the old one at a different address

2. Propagating changes is complex due to fan out (one container reused by ten or more containers) and the potential for propagation to traverse more than a single edge.  Limiting propagation is important in a large scale solution.

3. Hardcoding actual IP addresses (and ports, when port proxying is in play) inside environment variables is the simplest thing that works, but has a set of disadvantages that in OpenShift resulted in us looking into other options

4. Need to continue to consider that significant parts of connections will move into Docker links.  However, there are still concerns with performance (a required proxy), environment variables (no way to change the environment variables to match real use cases with parameterizing links), and state of implementation (doesn't exist yet)

**Comment by thockin** [comment]
Obsolete
