### ISSUE TITLE
Kubeadm Fails Due to Valid Argument

### ISSUE THREAD

**Issue by plombardi89** [kubernetes/kubernetes#49415]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: Running `kubeadm init --config=<path>` fails.

**What you expected to happen**: `kubeadm init --config=<path>` configures based on the provided file.

**How to reproduce it (as minimally and precisely as possible)**:

Create a file `/tmp/kubeadm.yaml` with the below content:

```
---
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
token: m52zte.m52ztet6s1jknlpg
cloudProvider: aws
kubernetesVersion: v1.7.1
apiServerCertSANs:
- plombardi.kubernaut.io
```

Run `kubeadm init --config=/tmp/kubeadm.yaml`

Get error: 

```
kubeadm init --config /tmp/kubeadm.yaml
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.7.1
[init] Using Authorization modes: [Node RBAC]
[init] WARNING: For cloudprovider integrations to work --cloud-provider must be set for all kubelets in the cluster.
	(/etc/systemd/system/kubelet.service.d/10-kubeadm.conf should be edited for this purpose)
[preflight] Running pre-flight checks
[preflight] WARNING: docker version is greater than the most recently validated version. Docker version: 17.06.0-ce. Max validated version: 1.12
can not mix '--config' with other arguments

```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): NA
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): CentOS 7.3 1703_01
- Kernel (e.g. `uname -a`): Linux ip-10-10-0-216.ec2.internal 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others: Kubeadm Version = `kubeadm version: &version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T01:48:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by xiangpengzhao** [comment]
@plombardi89 please re-open this in https://github.com/kubernetes/kubeadm :)
