### ISSUE TITLE
TestEtcdStoragePath test failures

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#49423]
Seeing a variety of failures

Address already in use failures
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49117/pull-kubernetes-unit/42260/

Stack traces:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49168/pull-kubernetes-unit/42305/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49168/pull-kubernetes-unit/42269/

Creation errors:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49219/pull-kubernetes-unit/42214/

**Comment by caesarxuchao** [comment]
cc @jpbetz

**Comment by pci** [comment]
Here's another false negative in TestEtcdStoragePath:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/50398/pull-kubernetes-unit/47478/
