### ISSUE TITLE
GCE Cloud Provider: Update ExternalTrafficPolicy on LoadBalancer Service without downtime

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#49425]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
Target pool on GCP seems to support in place update of health check (manually tested). Since health check on LB is the only difference we have between `ExternalTrafficPolicy=Local` and `ExternalTrafficPolicy=Cluster`, we should be able to update `ExternalTrafficPolicy` on LoadBalancer Service without bring down the traffic.

**What you expected to happen**:
Update ExternalTrafficPolicy on LoadBalancer Service without downtime.

**Anything else we need to know?**:
/sig network
/assign

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8
- Cloud provider or hardware configuration**: GCE

**Comment by cblecker** [comment]
@MrHohn is this something that is still in progress?

**Comment by MrHohn** [comment]
@cblecker This is something we want but I don't have enough bandwidth at this moment.

Would be great to have some help :) cc @grayluck 

/remove-lifecycle stale

**Comment by grayluck** [comment]
I'm on it.

**Comment by MrHohn** [comment]
This is still something good to have (though not at a high demand), but the previous attempt seems to bring in non-trivial changes logically. The  GCE LB related codes in cloud provider were implemented in a somehow fragile way, so we probably need to first overhaul that before we can safely patch changes like this.

/remove-triage unresolved

**Comment by andrewsykim** [comment]
cc @bowei 
/triage accepted

**Comment by thockin** [comment]
@bowei keep or close?

**Comment by bowei** [comment]
/close

I haven't seen anyone ask for this.
