### ISSUE TITLE
[documentation]Container v1 core > volumeMounts must be a list.

### ISSUE THREAD

**Issue by dElogics** [kubernetes/kubernetes#49435]
/kind bug

In the API reference -- 
https://kubernetes.io/docs/api-reference/v1.7/#container-v1-core
volumeMounts is a list, but as per the documentation, it must be a array.

**Comment by supereagle** [comment]
The structure of `VolumeMounts`:
```go
	// Pod volumes to mount into the container's filesystem.
	// Cannot be updated.
	// +optional
	// +patchMergeKey=mountPath
	// +patchStrategy=merge
	VolumeMounts []VolumeMount `json:"volumeMounts,omitempty" patchStrategy:"merge" patchMergeKey:"mountPath" protobuf:"bytes,9,rep,name=volumeMounts"`
```
In go, the structure of `VolumeMounts` is slice. I think `volumeMounts` can be thought as list or array, there is no significant difference.

**Comment by dElogics** [comment]
But the in the YAML it's a list (here arrays and lists are different things), which's a source of confusion.

**Comment by supereagle** [comment]
Form [YAML Spec](http://www.yaml.org/spec/1.2/spec.html):
> There are myriad flavors of data structures, but they can all be adequately represented with three basic primitives: mappings (hashes/dictionaries), sequences (arrays/lists) and scalars (strings/numbers).

[Generic Sequence](http://www.yaml.org/spec/1.2/spec.html#id2802662):
> Represents a collection indexed by sequential integers starting with zero. Example bindings to native types include Perl’s array, Python’s list or tuple, and Java’s array or Vector.

According to the YAML Spec, there is only sequence data structure, it can be parsed to map or list for different languages.

**Comment by lavalamp** [comment]
As @supereagle says, we don't recognize a difference between lists and arrays. Maybe it is a distinction about your language? Can you paste a .yaml you got and a .yaml that you expected?
