### ISSUE TITLE
SKAHP It please..

### ISSUE THREAD

**Issue by onefam** [kubernetes/kubernetes#49437]
[

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xiangpengzhao** [comment]
@onefam As there isn't valid info in this issue, can we close it? Feel free to create new issues if you find bugs or have feature requests.
