### ISSUE TITLE
Pod is ContainerCreating in other node by scheduled when rbd is locked by one node

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/kubernetes#49432]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
At present, the Ceph RBD is used to verify the scheduling of multiple instances on k8s.After the first pod instance mounts the RBD, the cloud hard disk that the RBD represents is exclusive to the node (only the other pod copies of the pod on the same a nodes can be mounted);If scheduling to another node that other pod always not running and is meaningless ?could schedule in one node or K8s should not schedule other pod to another node?

The pod status：
![image](https://user-images.githubusercontent.com/25783555/28557706-99d5de80-7140-11e7-8ccb-7a7022075b7a.png)

other pod is ContainerCreating and the logs：
MountVolume.SetUp failed for volume "kubernetes.io/rbd/b54b5ce7-686d-11e7-9cf5-fa163e7dc0ae-ceph-pv" (spec.Name: "ceph-pv") pod "b54b5ce7-686d-11e7-9cf5-fa163e7dc0ae" (UID: "b54b5ce7-686d-11e7-9cf5-fa163e7dc0ae") with: rbd: image foo is locked by other nodes

The deployment is defined:
-bash-4.2# cat test-deploy.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  strategy:
    type: Recreate
  replicas: 5
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: index.tenxcloud.com/docker_library/nginx:latest
        imagePullPolicy: Never
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: ceph-pv
          mountPath: /tmp/rbd
      volumes:
      - name: ceph-pv
        persistentVolumeClaim:
          claimName: ceph-claim
**What you expected to happen**:
K8s should not schedule other pod  to another node and schedule on one node that mount rbd!
**How to reproduce it (as minimally and precisely as possible)**:
n/a

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):GitVersion:"v1.5.1+82450d0", GitCommit:"6795200f715bf142523a49e76452f5ddd97fb366"
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):-bash-4.2# cat redhat-release
NewStart Carrier Grade Server Linux release 5
- Kernel (e.g. `uname -a`):-bash-4.2# uname -a
Linux master-jlx-k8s 3.10.0-514.6.1.el7.x86_64 #1 SMP Thu Feb 16 19:50:09 CST 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by jianglingxia** [comment]
cc @jingxu97 
can you review the issue or you encountered it ?thanks very much!

**Comment by jianglingxia** [comment]
@dims cinder also monopoly， if the first pod instance mounts the cinder, the cloud hard disk that the cinder represents is exclusive to the node (only the other pod copies of the pod on the same a nodes can be mounted)，Can you help me solve this problem?thanks

**Comment by wanghaoran1988** [comment]
@jianglingxia I suggest you using different pv for the pods,  per pv per pods, if you are deploy mysql, try statefulSet instead of deployment.

**Comment by jingxu97** [comment]
@jianglingxia, if you don't have any restrictions on your pod spec, the scheduler would assign the pod to different nodes since it does not consider whether the pods are using the same volume or not. But one thing you can try is to use node affinity https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
In this way, you can assign different pods to the same node. Hope it helps and please let me know if you have any questions.

**Comment by jianglingxia** [comment]
If use statefulset and the pv of rbd then the result different from rc or deployment is other pod maynot created but still scheduled other node and ContainerCreating 
`kubectl get po -n rbd -o wide
web-0     1/1       Running             0          4m        172.16.62.5   192.167.0.114
web-1     0/1       ContainerCreating   0          4m        <none>        192.167.0.113`
As @jingxu97  said,if I don't have any restrictions on my pod spec, the scheduler would assign the pod to different nodes,but if I assign different pods to the same node,the workload or What about load Balancing?

**Comment by jianglingxia** [comment]
the pod in the case of multiple replicas, can mount different volumes by different replicas ? In the case of RC hanging volumes, multiple replicas are identical instances, so multiple replicas are also the same volume, and it is not possible to take different volumes on different replicas. Did statefulset solve the problem? @jingxu97 thanks

**Comment by wanghaoran1988** [comment]
You can set a pv template for the statefulset, then each pod will have a pv

**Comment by jianglingxia** [comment]
like the yaml that I define ,How to modify it like you said？thanks @wanghaoran1988 
[root@jlx-vm:~/test]$ cat web.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: index.tenxcloud.com/docker_library/nginx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: nfs
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs

**Comment by wanghaoran1988** [comment]
@jianglingxia You can set the volumeClaimTemplates in the spec, and here is an example from openshift repo:
https://github.com/openshift/origin/blob/master/examples/statefulsets/mysql/galera/mysql-galera.yaml#L111

**Comment by jianglingxia** [comment]
How does k8s use this kind of storage of  cinder to store ? How do I configure this environment?thanks very much @wanghaoran1988 @jingxu97 @dims

**Comment by gun1x** [comment]
I am getting the same issue now. Containers which have PVC for a RBD storageclass get stuck in ContainerCreating.
