### ISSUE TITLE
Do not modify ELB security group

### ISSUE THREAD

**Issue by zihaoyu** [kubernetes/kubernetes#49445]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

We run Kuberentes on AWS. We are trying out `LoadBalancer` service type.

We use Terraform heavily for managing infrastructure on AWS. As a result we have several shared security groups with "perfect" rules. One of them is supposed to be attached to ELBs so our own IPs, partners, etc are whitelisted. Right now, it seems there isn't a way for Kubernetes to use the security group as is. There are several alternatives:

- Pass my existing security group as `service.beta.kubernetes.io/aws-load-balancer-extra-security-groups` annotation. However, Kubernetes still tries to create one first, or use a global security group. If I don't provide any IP range, Kubernetes will whitelist `0.0.0.0/0`. This seems insecure.
- Provide my own IP ranges as either annotation `service.beta.kubernetes.io/load-balancer-source-ranges` or `service.Spec.LoadBalancerSourceRanges`. Then Kubernetes will create a security group for this ELB with the given IPs. This means I need to duplicate my IPs in all microservices.
- Provide my own IP ranges as either annotation `service.beta.kubernetes.io/load-balancer-source-ranges` or `service.Spec.LoadBalancerSourceRanges`, and use a global security group. Then Kubernetes will modify the global SG with the given IPs. This seems problematic when lots of microservices share one SG but some want different IPs whitelisted.

I want to entertain the idea below:

- Allow users to sepcify another security group to `kube-controller-manager` or `Service` object, which Kubernetes will take it and attach it to ELBs as is.
- If such security group is provided, skip other IP whitelisting steps.

**What you expected to happen**:

I can give Kubernetes existing security group(s). Kuberentes just attaches the security group(s) to the managed ELBs without modifying the rules.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

It may already be possible to achieve this, and I'm not aware of. Or there are other concerns so that Kubernetes didn't choose to implement this feature.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.1
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nbutton23** [comment]
PR https://github.com/kubernetes/kubernetes/pull/49805 may help with this. . .

**Comment by KIVagant** [comment]
This problem could be really critical if one has the Kubernetes dashboard installed. If for some reasons the `kubernetes-dashboard` service recreates AWS ELB, the related security group will be recreated as well and then botnets could find the ELB and [attack your cluster](https://info.redlock.io/hubfs/WebsiteResources/RL_Cloud_Security_Trends_Oct_2107.pdf?t=1507325492499).

**Comment by winjer** [comment]
just had some downtime on a production cluster because of this. i really need it too ;)

**Comment by yossip** [comment]
+1

**Comment by KIVagant** [comment]
> /kind feature

As for me, it isn't a feature, it's a kind of bug.

**Comment by justinsb** [comment]
Some comments on #62774 which may be relevant - please comment if an alternative annotation that did replace the default security-groups (as opposed to adding to them) would/wouldn't meet your use-case: https://github.com/kubernetes/kubernetes/pull/62774#issuecomment-385294099

**Comment by johnzheng1975** [comment]
For me, I don't add any annotation, I just want to change its security group rule.
After it will create a aws elb, and a specificed secruity group with 0.0.0.0, I change 0.0.0.0 to xx.xx.xx.xx/32.
However, the security group rule will change back to 0.0.0.0 after some minutes.

Is this by design?

**Comment by Raffo** [comment]
I guess this is part of how the controller works. If you look at #62774 , the PR fixes this problem by allowing you to specify the behaviour you want with an annotation. For the way Kubernetes works, the ELB is owned by Kubernetes and you should never be forced to modify the resource manually, thing that ultimately will not work.

**Comment by Raffo** [comment]
/remove-lifecycle stale 

This is still relevant cause #62774 is not merged yet.

**Comment by rehevkor5** [comment]
This is a good change. The situation pre-1.13.0 is somewhat surprising because explicitly setting `loadBalancerSourceRanges` to an empty array like so:

```
  loadBalancerSourceRanges: []
```

has no effect, and the `0.0.0.0/0` Security Group Ingress is still added.
