### ISSUE TITLE
Tutorial: Part "Installing a sample application" is not working

### ISSUE THREAD

**Issue by kamilgregorczyk** [kubernetes/kubernetes#49458]
> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I just finished this tutorial on virtualbox: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
**What you expected to happen**:
When I did step "(Optional) Installing a sample application" I expected to have a working website under master ip but i got connection refused.
```
kubectl -n sock-shop get svc front-end
NAME        CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
front-end   10.111.95.59   <nodes>       80:30001/TCP   12m
```

```
root@ubuntu:~# kubectl get pods -n sock-shop
NAME                            READY     STATUS    RESTARTS   AGE
carts-2469883122-cs39q          1/1       Running   0          14m
carts-db-1721187500-3mlpr       1/1       Running   0          14m
catalogue-4293036822-nnbsk      1/1       Running   0          14m
catalogue-db-1846494424-ld97t   1/1       Running   0          14m
front-end-2337481689-lx0p6      1/1       Running   0          14m
orders-733484335-c9kjb          1/1       Running   0          14m
orders-db-3728196820-rdc6l      1/1       Running   0          14m
payment-3050936124-clp99        1/1       Running   0          14m
queue-master-2067646375-brgsf   1/1       Running   0          14m
rabbitmq-241640118-wk6zl        1/1       Running   0          14m
shipping-2463450563-trqgf       1/1       Running   0          14m
user-1574605338-czrkg           1/1       Running   0          14m
user-db-3152184577-wjvcx        1/1       Running   0          14m
```

```
root@ubuntu:~# curl 127.0.0.1:30001
curl: (7) Failed to connect to 127.0.0.1 port 30001: Connection refused
```

```
root@ubuntu:~# curl 192.168.0.241:30001
curl: (7) Failed to connect to 192.168.0.241 port 30001: Connection refused
```

```
root@ubuntu:~# curl 10.111.95.59:30001
curl: (7) Failed to connect to 10.111.95.59 port 30001: Connection timed out
```

**How to reproduce it (as minimally and precisely as possible)**:
I got 1 master and 3 workers on virtualbox, network is done over flannel.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: v1.7.2
- OS (e.g. from /etc/os-release):
- Kernel: Linux ubuntu 4.10.0-19-generic #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Lin
- Others: Virtualbox

**Comment by kweisamx** [comment]
Hi @kamilgregorczyk 

You can check the network first, because the cluster IP is under overlay network.
And you need to understand the network environment to help you get service , 

the ref will help you 
[https://stackoverflow.com/questions/41963433/what-does-it-mean-for-a-service-to-be-of-type-nodeport-and-have-both-port-and-t](https://stackoverflow.com/questions/41963433/what-does-it-mean-for-a-service-to-be-of-type-nodeport-and-have-both-port-and-t)
And if you want to check the port lived, you can go to the node which your pod in , then 
`netstat -an | grep <your nodeport>` to check the port lived or not ,
I hope it helps you.

**Comment by kamilgregorczyk** [comment]
But tutorial says something completely different:

> Then go to the IP address of your cluster’s master node in your browser, and specify the given port. So for example, http://<master_ip>:<port>. In the example above, this was 30001, but it may be a different port for you.

So I do expect that by entering http://master_ip:30001 it will get me there. I don't really care it it works for me ;) I find kubernetes really powerful tools but tutorials are terrible, when I was going through this one that I mentioned above, I had to use google 4 times for help because something didn't work.

**Comment by kweisamx** [comment]
Yes I agree kubernetes is very power and its document is .......,
maybe you can use docker create a pod,then get in to curl the service, check the service is fine.
I hope it helps you.=)

**Comment by sajattack** [comment]
@kubernetes/sig-docs-support

**Comment by sajattack** [comment]
@kubernetes/kind/support

**Comment by sajattack** [comment]
@kubernetes/kind-support

**Comment by kamilgregorczyk** [comment]
Current version of docs works as expected, thanks.

**Comment by spzala** [comment]
@kamilgregorczyk thanks for the update, so can we close the issue now?

**Comment by kamilgregorczyk** [comment]
yes

**Comment by spzala** [comment]
thanks @kamilgregorczyk

**Comment by oumkale** [comment]
Hello @spzala,
The front-end pod is crashing again and again during catalogue pod delete?
Liveness:     http-get http://:8079/ delay=300s timeout=1s period=3s #success=1 #failure=3
    Readiness:    http-get http://:8079/ delay=30s timeout=1s period=3s #success=1 #failure=3

Connection refused
