### ISSUE TITLE
Tutorial: Part "(Optional) Proxying API Server to localhost" not working

### ISSUE THREAD

**Issue by kamilgregorczyk** [kubernetes/kubernetes#49459]
> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
After I finished tutorial from this url: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/ I expected proxy (part (Optional) Proxying API Server to localhost) to be working properly and reaching out to /api works but /ui and /ui/ gives me such json:
```
{
kind: "Status",
apiVersion: "v1",
metadata: { },
status: "Failure",
message: "no endpoints available for service "kubernetes-dashboard"",
reason: "ServiceUnavailable",
code: 503
}
```

```
root@ubuntu:~# kubectl get pods -n kube-system
NAME                                    READY     STATUS             RESTARTS   AGE
etcd-master                             1/1       Unknown            0          2h
kube-apiserver-master                   1/1       Unknown            0          2h
kube-controller-manager-master          1/1       Unknown            0          2h
kube-dns-2425271678-9vcg1               2/3       CrashLoopBackOff   13         19m
kube-dns-2425271678-cxzt1               3/3       Unknown            0          2h
kube-flannel-ds-3073h                   2/2       NodeLost           6          2h
kube-flannel-ds-64rvd                   2/2       Running            0          1h
kube-flannel-ds-h45x3                   2/2       Running            0          1h
kube-flannel-ds-nwd2j                   2/2       Running            1          1h
kube-proxy-h7bkt                        1/1       Running            0          1h
kube-proxy-kl57g                        1/1       Running            0          1h
kube-proxy-mc5dn                        1/1       NodeLost           0          2h
kube-proxy-v391n                        1/1       Running            0          1h
kube-scheduler-master                   1/1       Unknown            0          2h
kubernetes-dashboard-2209332821-dpx4z   0/1       CrashLoopBackOff   20         1h
```
I tried running proxy on host (mac) and on the master itself but nothing worked. If there's more work that's need to be done to make it work then it should be in this tutorial.

**What you expected to happen**:
Well, kubernetes dashboard
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: 1.7,2
- OS (e.g. from /etc/os-release): Ubuntu 17.04
- Kernel (e.g. `uname -a`): Linux ubuntu 4.10.0-19-generic #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Others: Virtual machine (1 master, 3 workers)

**Comment by luxas** [comment]
Working as intended. If you install the [dashboard](https://github.com/kubernetes/dashboard], the `/ui` endpoint will work. The `/ui` endpoint is just a shorthand for proxying the kubernetes-dashboard service

**Comment by kamilgregorczyk** [comment]
As you can see in my post kubernetes-dashboard is installed.

**Comment by luxas** [comment]
Oh, didn't see that. It's crashlooping, hence there's no available endpoint for the service to connect to.
When you get the dashboard `Running` this will work

I don't think there are action items for kubeadm. If there are, please open a new issue in the kubeadm repo
